Terraria: Main.DrawNPCDirect
DrawNPCDirect()
void Main.DrawNPCDirect (SpriteBatch mySpriteBatch, NPC rCurrentNPC, bool behindTiles, Vector2 screenPos) inline
     {
         int type = rCurrentNPC.type;
         rCurrentNPC.SetFrameSize();
         if (rCurrentNPC.realLife == -1 && rCurrentNPC.life >= rCurrentNPC.lifeMax && !rCurrentNPC.boss)
         {
             bool flag = Lighting.GetColor((int)((double)rCurrentNPC.position.X + (double)rCurrentNPC.width * 0.5) / 16, (int)(((double)rCurrentNPC.position.Y + (double)rCurrentNPC.height * 0.5) / 16.0)).ToVector3().Length() > 0.4325f;
             bool flag2 = false;
             if (LockOnHelper.AimedTarget == rCurrentNPC)
             {
                 flag2 = true;
             }
             else if (rCurrentNPC.Distance(Main.player[myPlayer].Center) < 350f && flag)
             {
                 flag2 = true;
             }
             if (flag2 && rCurrentNPC.lifeMax < 5)
             {
                 flag2 = false;
             }
             if (flag2 && rCurrentNPC.aiStyle == 25 && rCurrentNPC.ai[0] == 0f)
             {
                 flag2 = false;
             }
             if (flag2)
             {
                 rCurrentNPC.nameOver = MathHelper.Clamp(rCurrentNPC.nameOver + 0.025f, 0f, 1f);
             }
             else
             {
                 rCurrentNPC.nameOver = MathHelper.Clamp(rCurrentNPC.nameOver - 0.025f, 0f, 1f);
             }
         }
         else
         {
             rCurrentNPC.nameOver = MathHelper.Clamp(rCurrentNPC.nameOver - 0.025f, 0f, 1f);
         }
         if (type == 1 && rCurrentNPC.ai[0] == -999f)
         {
             return;
         }
         if (type == 101)
         {
             bool flag3 = true;
             Vector2 vector = new Vector2(rCurrentNPC.position.X + (float)(rCurrentNPC.width / 2), rCurrentNPC.position.Y + (float)(rCurrentNPC.height / 2));
             float num = rCurrentNPC.ai[0] * 16f + 8f - vector.X;
             float num2 = rCurrentNPC.ai[1] * 16f + 8f - vector.Y;
             float rotation = (float)Math.Atan2(num2, num) - 1.57f;
             bool flag4 = true;
             while (flag4)
             {
                 float num3 = 0.75f;
                 int height = 28;
                 float num4 = (float)Math.Sqrt(num * num + num2 * num2);
                 if (num4 < 28f * num3)
                 {
                     height = (int)num4 - 40 + 28;
                     flag4 = false;
                 }
                 num4 = 20f * num3 / num4;
                 num *= num4;
                 num2 *= num4;
                 vector.X += num;
                 vector.Y += num2;
                 num = rCurrentNPC.ai[0] * 16f + 8f - vector.X;
                 num2 = rCurrentNPC.ai[1] * 16f + 8f - vector.Y;
                 Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f));
                 if (rCurrentNPC.IsABestiaryIconDummy)
                 {
                     color = rCurrentNPC.GetBestiaryEntryColor();
                 }
                 if (!flag3)
                 {
                     flag3 = true;
                     mySpriteBatch.Draw(TextureAssets.Chain10.Value, new Vector2(vector.X - screenPos.X, vector.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain10.Width(), height), color, rotation, new Vector2((float)TextureAssets.Chain10.Width() * 0.5f, (float)TextureAssets.Chain10.Height() * 0.5f), num3, SpriteEffects.None, 0f);
                 }
                 else
                 {
                     flag3 = false;
                     mySpriteBatch.Draw(TextureAssets.Chain11.Value, new Vector2(vector.X - screenPos.X, vector.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain10.Width(), height), color, rotation, new Vector2((float)TextureAssets.Chain10.Width() * 0.5f, (float)TextureAssets.Chain10.Height() * 0.5f), num3, SpriteEffects.None, 0f);
                 }
             }
         }
         else if (rCurrentNPC.aiStyle == 13)
         {
             Vector2 vector2 = new Vector2(rCurrentNPC.position.X + (float)(rCurrentNPC.width / 2), rCurrentNPC.position.Y + (float)(rCurrentNPC.height / 2));
             float num5 = rCurrentNPC.ai[0] * 16f + 8f - vector2.X;
             float num6 = rCurrentNPC.ai[1] * 16f + 8f - vector2.Y;
             float rotation2 = (float)Math.Atan2(num6, num5) - 1.57f;
             bool flag5 = true;
             while (flag5)
             {
                 int num7 = 28;
                 int num8 = 40;
                 if (type == 259 || type == 260)
                 {
                     num8 = 20;
                     num7 = 12;
                 }
                 float num9 = (float)Math.Sqrt(num5 * num5 + num6 * num6);
                 if (num9 < (float)num8)
                 {
                     num7 = (int)num9 - num8 + num7;
                     flag5 = false;
                 }
                 num9 = (float)num7 / num9;
                 num5 *= num9;
                 num6 *= num9;
                 vector2.X += num5;
                 vector2.Y += num6;
                 num5 = rCurrentNPC.ai[0] * 16f + 8f - vector2.X;
                 num6 = rCurrentNPC.ai[1] * 16f + 8f - vector2.Y;
                 Microsoft.Xna.Framework.Color color2 = Lighting.GetColor((int)vector2.X / 16, (int)(vector2.Y / 16f));
                 if (rCurrentNPC.IsABestiaryIconDummy)
                 {
                     color2 = rCurrentNPC.GetBestiaryEntryColor();
                 }
                 if (type == 259 || type == 260)
                 {
                     color2.B = byte.MaxValue;
                     if (color2.R < 100)
                     {
                         color2.R = 100;
                     }
                     if (color2.G < 150)
                     {
                         color2.G = 150;
                     }
                 }
                 switch (type)
                 {
                 case 56:
                     mySpriteBatch.Draw(TextureAssets.Chain5.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain4.Width(), num7), color2, rotation2, new Vector2((float)TextureAssets.Chain4.Width() * 0.5f, (float)TextureAssets.Chain4.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                     break;
                 case 175:
                     mySpriteBatch.Draw(TextureAssets.Chain14.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain14.Width(), num7), color2, rotation2, new Vector2((float)TextureAssets.Chain14.Width() * 0.5f, (float)TextureAssets.Chain14.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                     break;
                 case 259:
                     mySpriteBatch.Draw(TextureAssets.Chain24.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain24.Width(), num7), color2, rotation2, new Vector2((float)TextureAssets.Chain24.Width() * 0.5f, (float)TextureAssets.Chain24.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                     break;
                 case 260:
                     mySpriteBatch.Draw(TextureAssets.Chain25.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain25.Width(), num7), color2, rotation2, new Vector2((float)TextureAssets.Chain25.Width() * 0.5f, (float)TextureAssets.Chain25.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                     break;
                 default:
                     mySpriteBatch.Draw(TextureAssets.Chain4.Value, new Vector2(vector2.X - screenPos.X, vector2.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain4.Width(), num7), color2, rotation2, new Vector2((float)TextureAssets.Chain4.Width() * 0.5f, (float)TextureAssets.Chain4.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                     break;
                 }
             }
         }
         if (type == 327)
         {
             float rotation3 = 0f;
             Vector2 vector3 = new Vector2(rCurrentNPC.Center.X, rCurrentNPC.Center.Y + 80f);
             int num10 = (int)rCurrentNPC.localAI[1];
             Microsoft.Xna.Framework.Color color3 = Lighting.GetColor((int)vector3.X / 16, (int)(vector3.Y / 16f));
             mySpriteBatch.Draw(TextureAssets.PumpkingCloak.Value, new Vector2(vector3.X - screenPos.X, vector3.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.PumpkingCloak.Height() / 5 * num10, TextureAssets.PumpkingCloak.Width(), TextureAssets.PumpkingCloak.Height() / 5), color3, rotation3, new Vector2((float)TextureAssets.PumpkingCloak.Width() * 0.5f, (float)TextureAssets.PumpkingCloak.Height() * 0.5f / 5f), 1f, SpriteEffects.None, 0f);
         }
         if (type == 328)
         {
             Vector2 vector4 = new Vector2(rCurrentNPC.position.X + (float)rCurrentNPC.width * 0.5f - 5f * rCurrentNPC.ai[0], rCurrentNPC.position.Y + 20f);
             for (int i = 0; i < 2; i++)
             {
                 float num11 = npc[(int)rCurrentNPC.ai[1]].position.X + (float)(npc[(int)rCurrentNPC.ai[1]].width / 2) - vector4.X;
                 float num12 = npc[(int)rCurrentNPC.ai[1]].position.Y + (float)(npc[(int)rCurrentNPC.ai[1]].height / 2) - 30f - vector4.Y;
                 float num13 = 0f;
                 if (i == 0)
                 {
                     num11 -= 200f * rCurrentNPC.ai[0];
                     num12 += 130f;
                     num13 = (float)Math.Sqrt(num11 * num11 + num12 * num12);
                     num13 = 92f / num13;
                     vector4.X += num11 * num13;
                     vector4.Y += num12 * num13;
                 }
                 else
                 {
                     num11 -= 50f * rCurrentNPC.ai[0];
                     num12 += 80f;
                     num13 = (float)Math.Sqrt(num11 * num11 + num12 * num12);
                     num13 = 60f / num13;
                     vector4.X += num11 * num13;
                     vector4.Y += num12 * num13;
                 }
                 float rotation4 = (float)Math.Atan2(num12, num11) - 1.57f;
                 Microsoft.Xna.Framework.Color color4 = Lighting.GetColor((int)vector4.X / 16, (int)(vector4.Y / 16f));
                 mySpriteBatch.Draw(TextureAssets.PumpkingArm.Value, new Vector2(vector4.X - screenPos.X, vector4.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.PumpkingArm.Width(), TextureAssets.PumpkingArm.Height()), color4, rotation4, new Vector2((float)TextureAssets.PumpkingArm.Width() * 0.5f, (float)TextureAssets.PumpkingArm.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                 if (i == 0)
                 {
                     vector4.X += num11 * num13 / 2f;
                     vector4.Y += num12 * num13 / 2f;
                 }
             }
         }
         if (type == 36)
         {
             Vector2 vector5 = new Vector2(rCurrentNPC.position.X + (float)rCurrentNPC.width * 0.5f - 5f * rCurrentNPC.ai[0], rCurrentNPC.position.Y + 20f);
             for (int j = 0; j < 2; j++)
             {
                 float num14 = npc[(int)rCurrentNPC.ai[1]].position.X + (float)(npc[(int)rCurrentNPC.ai[1]].width / 2) - vector5.X;
                 float num15 = npc[(int)rCurrentNPC.ai[1]].position.Y + (float)(npc[(int)rCurrentNPC.ai[1]].height / 2) - vector5.Y;
                 float num16 = 0f;
                 if (j == 0)
                 {
                     num14 -= 200f * rCurrentNPC.ai[0];
                     num15 += 130f;
                     num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
                     num16 = 92f / num16;
                     vector5.X += num14 * num16;
                     vector5.Y += num15 * num16;
                 }
                 else
                 {
                     num14 -= 50f * rCurrentNPC.ai[0];
                     num15 += 80f;
                     num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
                     num16 = 60f / num16;
                     vector5.X += num14 * num16;
                     vector5.Y += num15 * num16;
                 }
                 float rotation5 = (float)Math.Atan2(num15, num14) - 1.57f;
                 Microsoft.Xna.Framework.Color color5 = Lighting.GetColor((int)vector5.X / 16, (int)(vector5.Y / 16f));
                 mySpriteBatch.Draw(TextureAssets.BoneArm.Value, new Vector2(vector5.X - screenPos.X, vector5.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.BoneArm.Width(), TextureAssets.BoneArm.Height()), color5, rotation5, new Vector2((float)TextureAssets.BoneArm.Width() * 0.5f, (float)TextureAssets.BoneArm.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                 if (j == 0)
                 {
                     vector5.X += num14 * num16 / 2f;
                     vector5.Y += num15 * num16 / 2f;
                 }
                 else if (base.IsActive)
                 {
                     vector5.X += num14 * num16 - 16f;
                     vector5.Y += num15 * num16 - 6f;
                     int num17 = Dust.NewDust(new Vector2(vector5.X, vector5.Y), 30, 10, 5, num14 * 0.02f, num15 * 0.02f, 0, default(Microsoft.Xna.Framework.Color), 2f);
                     dust[num17].noGravity = true;
                 }
             }
         }
         if (rCurrentNPC.aiStyle == 47)
         {
             float scale = rCurrentNPC.scale;
             Vector2 vector6 = new Vector2(rCurrentNPC.Center.X, rCurrentNPC.Center.Y);
             Vector2 center = rCurrentNPC.Center;
             if (NPC.golemBoss != -1)
             {
                 center = npc[NPC.golemBoss].Center;
             }
             float num18 = center.X - vector6.X;
             float num19 = center.Y - vector6.Y;
             num19 -= 7f * scale;
             num18 = ((type != 247) ? (num18 + 66f * scale) : (num18 - 70f * scale));
             float rotation6 = (float)Math.Atan2(num19, num18) - 1.57f;
             bool flag6 = true;
             while (flag6)
             {
                 float num20 = (float)Math.Sqrt(num18 * num18 + num19 * num19);
                 if (num20 < 16f)
                 {
                     flag6 = false;
                     continue;
                 }
                 num20 = 16f * scale / num20;
                 num18 *= num20;
                 num19 *= num20;
                 vector6.X += num18;
                 vector6.Y += num19;
                 num18 = center.X - vector6.X;
                 num19 = center.Y - vector6.Y;
                 num19 -= 7f * scale;
                 num18 = ((type != 247) ? (num18 + 66f * scale) : (num18 - 70f * scale));
                 if (getGoodWorld)
                 {
                     num19 += 8f;
                 }
                 Microsoft.Xna.Framework.Color color6 = Lighting.GetColor((int)vector6.X / 16, (int)(vector6.Y / 16f));
                 mySpriteBatch.Draw(TextureAssets.Chain21.Value, new Vector2(vector6.X - screenPos.X, vector6.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain21.Width(), TextureAssets.Chain21.Height()), color6, rotation6, new Vector2((float)TextureAssets.Chain21.Width() * 0.5f, (float)TextureAssets.Chain21.Height() * 0.5f), scale, SpriteEffects.None, 0f);
             }
         }
         if (rCurrentNPC.aiStyle >= 33 && rCurrentNPC.aiStyle <= 36)
         {
             Vector2 vector7 = new Vector2(rCurrentNPC.position.X + (float)rCurrentNPC.width * 0.5f - 5f * rCurrentNPC.ai[0], rCurrentNPC.position.Y + 20f);
             for (int k = 0; k < 2; k++)
             {
                 float num21 = npc[(int)rCurrentNPC.ai[1]].position.X + (float)(npc[(int)rCurrentNPC.ai[1]].width / 2) - vector7.X;
                 float num22 = npc[(int)rCurrentNPC.ai[1]].position.Y + (float)(npc[(int)rCurrentNPC.ai[1]].height / 2) - vector7.Y;
                 float num23 = 0f;
                 if (k == 0)
                 {
                     num21 -= 200f * rCurrentNPC.ai[0];
                     num22 += 130f;
                     num23 = (float)Math.Sqrt(num21 * num21 + num22 * num22);
                     num23 = 92f / num23;
                     vector7.X += num21 * num23;
                     vector7.Y += num22 * num23;
                 }
                 else
                 {
                     num21 -= 50f * rCurrentNPC.ai[0];
                     num22 += 80f;
                     num23 = (float)Math.Sqrt(num21 * num21 + num22 * num22);
                     num23 = 60f / num23;
                     vector7.X += num21 * num23;
                     vector7.Y += num22 * num23;
                 }
                 float rotation7 = (float)Math.Atan2(num22, num21) - 1.57f;
                 Microsoft.Xna.Framework.Color color7 = Lighting.GetColor((int)vector7.X / 16, (int)(vector7.Y / 16f));
                 mySpriteBatch.Draw(TextureAssets.BoneArm2.Value, new Vector2(vector7.X - screenPos.X, vector7.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.BoneArm.Width(), TextureAssets.BoneArm.Height()), color7, rotation7, new Vector2((float)TextureAssets.BoneArm.Width() * 0.5f, (float)TextureAssets.BoneArm.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                 if (k == 0)
                 {
                     vector7.X += num21 * num23 / 2f;
                     vector7.Y += num22 * num23 / 2f;
                 }
                 else if (base.IsActive)
                 {
                     vector7.X += num21 * num23 - 16f;
                     vector7.Y += num22 * num23 - 6f;
                     int num24 = Dust.NewDust(new Vector2(vector7.X, vector7.Y), 30, 10, 6, num21 * 0.02f, num22 * 0.02f, 0, default(Microsoft.Xna.Framework.Color), 2.5f);
                     dust[num24].noGravity = true;
                 }
             }
         }
         if (rCurrentNPC.aiStyle == 20)
         {
             Vector2 vector8 = new Vector2(rCurrentNPC.position.X + (float)(rCurrentNPC.width / 2), rCurrentNPC.position.Y + (float)(rCurrentNPC.height / 2));
             float num25 = rCurrentNPC.ai[1] - vector8.X;
             float num26 = rCurrentNPC.ai[2] - vector8.Y;
             float num27 = (rCurrentNPC.rotation = (float)Math.Atan2(num26, num25) - 1.57f);
             bool flag7 = true;
             while (flag7)
             {
                 int height2 = 12;
                 float num28 = (float)Math.Sqrt(num25 * num25 + num26 * num26);
                 if (num28 < 20f)
                 {
                     height2 = (int)num28 - 20 + 12;
                     flag7 = false;
                 }
                 num28 = 12f / num28;
                 num25 *= num28;
                 num26 *= num28;
                 vector8.X += num25;
                 vector8.Y += num26;
                 num25 = rCurrentNPC.ai[1] - vector8.X;
                 num26 = rCurrentNPC.ai[2] - vector8.Y;
                 Microsoft.Xna.Framework.Color color8 = Lighting.GetColor((int)vector8.X / 16, (int)(vector8.Y / 16f));
                 mySpriteBatch.Draw(TextureAssets.Chain.Value, new Vector2(vector8.X - screenPos.X, vector8.Y - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain.Width(), height2), color8, num27, new Vector2((float)TextureAssets.Chain.Width() * 0.5f, (float)TextureAssets.Chain.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
             }
             mySpriteBatch.Draw(TextureAssets.SpikeBase.Value, new Vector2(rCurrentNPC.ai[1] - screenPos.X, rCurrentNPC.ai[2] - screenPos.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.SpikeBase.Width(), TextureAssets.SpikeBase.Height()), Lighting.GetColor((int)rCurrentNPC.ai[1] / 16, (int)(rCurrentNPC.ai[2] / 16f)), num27 - 0.75f, new Vector2((float)TextureAssets.SpikeBase.Width() * 0.5f, (float)TextureAssets.SpikeBase.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
         }
         Microsoft.Xna.Framework.Color npcColor = Lighting.GetColor((int)((double)rCurrentNPC.position.X + (double)rCurrentNPC.width * 0.5) / 16, (int)(((double)rCurrentNPC.position.Y + (double)rCurrentNPC.height * 0.5) / 16.0));
         if (rCurrentNPC.IsABestiaryIconDummy)
         {
             npcColor = rCurrentNPC.GetBestiaryEntryColor();
         }
         if (type >= 277 && type <= 280)
         {
             if (npcColor.R < byte.MaxValue)
             {
                 npcColor.R = byte.MaxValue;
             }
             if (npcColor.G < 175)
             {
                 npcColor.G = 175;
             }
         }
         if (type == -4)
         {
             int r = npcColor.R;
             int g = npcColor.G;
             int b = npcColor.B;
             r *= 2;
             if (r > 255)
             {
                 r = 255;
             }
             g *= 2;
             if (g > 255)
             {
                 g = 255;
             }
             b *= 2;
             if (b > 255)
             {
                 b = 255;
             }
             npcColor = new Microsoft.Xna.Framework.Color(r, g, b);
         }
         if (behindTiles && type != 113 && type != 114)
         {
             int num29 = (int)((rCurrentNPC.position.X - 8f) / 16f);
             int num30 = (int)((rCurrentNPC.position.X + (float)rCurrentNPC.width + 8f) / 16f);
             int num31 = (int)((rCurrentNPC.position.Y - 8f) / 16f);
             int num32 = (int)((rCurrentNPC.position.Y + (float)rCurrentNPC.height + 8f) / 16f);
             for (int l = num29; l <= num30; l++)
             {
                 for (int m = num31; m <= num32; m++)
                 {
                     if (Lighting.Brightness(l, m) == 0f)
                     {
                         npcColor = Microsoft.Xna.Framework.Color.Black;
                     }
                 }
             }
         }
         npcColor = rCurrentNPC.GetNPCColorTintedByBuffs(npcColor);
         if (type == 50)
         {
             Vector2 zero = Vector2.Zero;
             float num33 = 0f;
             zero.Y -= rCurrentNPC.velocity.Y;
             zero.X -= rCurrentNPC.velocity.X * 2f;
             num33 += rCurrentNPC.velocity.X * 0.05f;
             if (rCurrentNPC.frame.Y == 120)
             {
                 zero.Y += 2f;
             }
             if (rCurrentNPC.frame.Y == 360)
             {
                 zero.Y -= 2f;
             }
             if (rCurrentNPC.frame.Y == 480)
             {
                 zero.Y -= 6f;
             }
             mySpriteBatch.Draw(TextureAssets.Ninja.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) + zero.X, rCurrentNPC.position.Y - screenPos.Y + (float)(rCurrentNPC.height / 2) + zero.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Ninja.Width(), TextureAssets.Ninja.Height()), npcColor, num33, new Vector2(TextureAssets.Ninja.Width() / 2, TextureAssets.Ninja.Height() / 2), 1f, SpriteEffects.None, 0f);
         }
         if (type == 71)
         {
             Vector2 zero2 = Vector2.Zero;
             float num34 = 0f;
             zero2.Y -= rCurrentNPC.velocity.Y * 0.3f;
             zero2.X -= rCurrentNPC.velocity.X * 0.6f;
             num34 += rCurrentNPC.velocity.X * 0.09f;
             if (rCurrentNPC.frame.Y == 120)
             {
                 zero2.Y += 2f;
             }
             if (rCurrentNPC.frame.Y == 360)
             {
                 zero2.Y -= 2f;
             }
             if (rCurrentNPC.frame.Y == 480)
             {
                 zero2.Y -= 6f;
             }
             GetItemDrawFrame(327, out var itemTexture, out var rectangle);
             mySpriteBatch.Draw(itemTexture, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) + zero2.X, rCurrentNPC.position.Y - screenPos.Y + (float)(rCurrentNPC.height / 2) + zero2.Y), rectangle, npcColor, num34, rectangle.Size() / 2f, 1f, SpriteEffects.None, 0f);
         }
         if (type == 69)
         {
             mySpriteBatch.Draw(TextureAssets.AntLion.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2), rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height + 14f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.AntLion.Width(), TextureAssets.AntLion.Height()), npcColor, (0f - rCurrentNPC.rotation) * 0.3f, new Vector2(TextureAssets.AntLion.Width() / 2, TextureAssets.AntLion.Height() / 2), 1f, SpriteEffects.None, 0f);
         }
         if (type == 1 && rCurrentNPC.ai[1] > 0f)
         {
             DrawNPC_SlimeItem(rCurrentNPC, type, npcColor, 0f);
         }
         float num35 = 0f;
         float num36 = NPCAddHeight(rCurrentNPC);
         Vector2 halfSize = new Vector2(TextureAssets.Npc[type].Width() / 2, TextureAssets.Npc[type].Height() / npcFrameCount[type] / 2);
         if (type == 108 || type == 124 || type == 625)
         {
             num35 = 2f;
         }
         else if (type == 357)
         {
             num35 = rCurrentNPC.localAI[0];
         }
         else if (type == 467)
         {
             num35 = 7f;
         }
         else if (type == 537)
         {
             num35 = 2f;
         }
         else if (type == 581)
         {
             num35 = -6f;
         }
         else if (type == 490)
         {
             num35 = 4f;
         }
         else if (type == 484)
         {
             num35 = 2f;
         }
         else if (type == 483)
         {
             num35 = 14f;
         }
         else if (type == 477)
         {
             num36 = 22f;
         }
         else if (type == 478)
         {
             num35 -= 2f;
         }
         else if (type == 606)
         {
             num35 -= 2f;
         }
         else if (type == 612 || type == 613)
         {
             num35 -= 2f;
         }
         else if (type == 469 && rCurrentNPC.ai[2] == 1f)
         {
             num35 = 14f;
         }
         else
         {
             switch (type)
             {
             case 4:
                 halfSize = new Vector2(55f, 107f);
                 break;
             case 125:
                 halfSize = new Vector2(55f, 107f);
                 break;
             case 126:
                 halfSize = new Vector2(55f, 107f);
                 break;
             case 626:
             case 627:
                 if (rCurrentNPC.wet)
                 {
                     num35 = -2f;
                     halfSize = rCurrentNPC.frame.Size() * new Vector2(0.5f, 0.5f) + new Vector2(0f, -4f);
                 }
                 else
                 {
                     num35 = 2f;
                 }
                 break;
             case 63:
             case 64:
             case 103:
                 halfSize.Y += 4f;
                 break;
             case 69:
                 halfSize.Y += 8f;
                 break;
             case 262:
                 halfSize.Y = 77f;
                 num36 += 26f;
                 break;
             case 264:
                 halfSize.Y = 21f;
                 num36 += 2f;
                 break;
             case 266:
                 num36 += 50f * rCurrentNPC.scale;
                 break;
             case 268:
                 num36 += 16f;
                 break;
             case 288:
                 num36 += 6f;
                 break;
             }
         }
         if (rCurrentNPC.aiStyle == 10 || type == 72)
         {
             npcColor = Microsoft.Xna.Framework.Color.White;
         }
         SpriteEffects spriteEffects = SpriteEffects.None;
         if (rCurrentNPC.spriteDirection == 1)
         {
             spriteEffects = SpriteEffects.FlipHorizontally;
         }
         if (type == 124 && rCurrentNPC.localAI[0] == 0f)
         {
             int num37 = 0;
             if (rCurrentNPC.frame.Y > 56)
             {
                 num37 += 4;
             }
             num37 += rCurrentNPC.frame.Y / 56;
             if (num37 >= OffsetsPlayerHeadgear.Length)
             {
                 num37 = 0;
             }
             float y = OffsetsPlayerHeadgear[num37].Y;
             LoadProjectile(582);
             Texture2D value = TextureAssets.Projectile[582].Value;
             if (rCurrentNPC.townNpcVariationIndex == 1)
             {
                 value = TextureAssets.Extra[263].Value;
             }
             Vector2 position = rCurrentNPC.Center - screenPos;
             position -= new Vector2(value.Width, value.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
             position += new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY + y);
             position += new Vector2(-rCurrentNPC.spriteDirection * 2, -2f);
             mySpriteBatch.Draw(value, position, null, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, value.Size() * new Vector2(0f, 0.5f), rCurrentNPC.scale, spriteEffects, 0f);
         }
         switch (type)
         {
         default:
             if (type != 546 && type != 552 && type != 553 && type != 554 && type != 561 && type != 562 && type != 563 && type != 555 && type != 556 && type != 557 && type != 558 && type != 559 && type != 560 && type != 574 && type != 575 && type != 568 && type != 569 && type != 572 && type != 573 && type != 566 && type != 567 && type != 570 && type != 578 && type != 571 && type != 583 && type != 584 && type != 585 && type != 618 && type != 620 && type != 661)
             {
                 switch (type)
                 {
                 case 551:
                 {
                     Texture2D value2 = TextureAssets.Npc[type].Value;
                     Vector2 vector9 = rCurrentNPC.Center - screenPos;
                     Microsoft.Xna.Framework.Rectangle frame = rCurrentNPC.frame;
                     _ = frame.Size() / 2f;
                     SpriteEffects spriteEffects2 = spriteEffects ^ SpriteEffects.FlipHorizontally;
                     float rotation8 = rCurrentNPC.rotation;
                     Microsoft.Xna.Framework.Color color9 = npcColor;
                     Microsoft.Xna.Framework.Color color10 = Microsoft.Xna.Framework.Color.Lerp(color9, Microsoft.Xna.Framework.Color.White, 0.6f);
                     color10.A = 66;
                     Vector2 vector10 = new Vector2(171f, 44f);
                     Vector2 vector11 = new Vector2(230f, 52f);
                     Vector2 vector12 = Vector2.Lerp(vector10, vector11, 0.5f) + new Vector2(-50f, 30f);
                     int num38 = (int)rCurrentNPC.localAI[0] / 4;
                     Vector2 spinningpoint = vector10 - vector12;
                     Vector2 spinningpoint2 = vector11 - vector12;
                     Texture2D value3 = TextureAssets.Extra[82].Value;
                     if (spriteEffects2.HasFlag(SpriteEffects.FlipHorizontally))
                     {
                         spinningpoint2.X *= -1f;
                     }
                     Microsoft.Xna.Framework.Rectangle value4 = value3.Frame(2, 5, num38 / 5, num38 % 5);
                     Vector2 origin = new Vector2(16f, 176f);
                     if (spriteEffects2.HasFlag(SpriteEffects.FlipHorizontally))
                     {
                         origin.X = (float)value4.Width - origin.X;
                     }
                     if (spriteEffects2.HasFlag(SpriteEffects.FlipHorizontally))
                     {
                         vector12.X = (float)frame.Width - vector12.X;
                     }
                     Texture2D value5 = TextureAssets.Extra[81].Value;
                     if (spriteEffects2.HasFlag(SpriteEffects.FlipHorizontally))
                     {
                         spinningpoint.X *= -1f;
                     }
                     Microsoft.Xna.Framework.Rectangle value6 = value5.Frame(2, 5, num38 / 5, num38 % 5);
                     Vector2 origin2 = new Vector2(215f, 170f);
                     if (spriteEffects2.HasFlag(SpriteEffects.FlipHorizontally))
                     {
                         origin2.X = (float)value6.Width - origin2.X;
                     }
                     float lerpValue = Utils.GetLerpValue(0f, 30f, rCurrentNPC.localAI[1], clamped: true);
                     if (lerpValue == 1f)
                     {
                         lerpValue = Utils.GetLerpValue(60f, 30f, rCurrentNPC.localAI[1], clamped: true);
                     }
                     lerpValue = 2f;
                     Vector2 vector13 = rCurrentNPC.Size / 2f - screenPos;
                     int num39 = -3;
                     int num40 = 0;
                     byte b2 = 2;
                     for (int n = 9; n > num40; n += num39)
                     {
                         Vector2 vector14 = rCurrentNPC.oldPos[n] + vector13;
                         float num41 = rCurrentNPC.oldRot[n];
                         Microsoft.Xna.Framework.Color color11 = color9 * (1f - (float)n / 10f) * 0.35f;
                         color11.A /= b2;
                         mySpriteBatch.Draw(value3, vector14 + spinningpoint2.RotatedBy(num41), value4, color11, num41, origin, 1f, spriteEffects2, 0f);
                         mySpriteBatch.Draw(value2, vector14, frame, color11, num41, vector12, 1f, spriteEffects2, 0f);
                         mySpriteBatch.Draw(value5, vector14 + spinningpoint.RotatedBy(num41), value6, color11, num41, origin2, 1f, spriteEffects2, 0f);
                     }
                     mySpriteBatch.Draw(value3, vector9 + spinningpoint2.RotatedBy(rotation8), value4, color9, rotation8, origin, 1f, spriteEffects2, 0f);
                     mySpriteBatch.Draw(value2, vector9, frame, color9, rotation8, vector12, 1f, spriteEffects2, 0f);
                     mySpriteBatch.Draw(TextureAssets.GlowMask[226].Value, vector9, frame, color10 * (0.7f + 0.3f * lerpValue), rotation8, vector12, 1f, spriteEffects2, 0f);
                     mySpriteBatch.Draw(value5, vector9 + spinningpoint.RotatedBy(rotation8), value6, color9, rotation8, origin2, 1f, spriteEffects2, 0f);
                     return;
                 }
                 case 657:
                 {
                     Texture2D value10 = TextureAssets.Npc[type].Value;
                     Vector2 position7 = rCurrentNPC.Bottom - screenPos;
                     position7.Y += 2f;
                     int num53 = npcFrameCount[rCurrentNPC.type];
                     int num54 = rCurrentNPC.frame.Y / rCurrentNPC.frame.Height;
                     Microsoft.Xna.Framework.Rectangle rectangle3 = value10.Frame(2, 16, num54 / num53, num54 % num53);
                     rectangle3.Inflate(0, -2);
                     Vector2 origin4 = rectangle3.Size() * new Vector2(0.5f, 1f);
                     Microsoft.Xna.Framework.Color color15 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.White, npcColor, 0.5f);
                     if (rCurrentNPC.life <= rCurrentNPC.lifeMax / 2)
                     {
                         DrawNPCDirect_QueenSlimeWings(rCurrentNPC, mySpriteBatch, screenPos, rCurrentNPC.Center, color15);
                     }
                     Texture2D value11 = TextureAssets.Extra[186].Value;
                     Microsoft.Xna.Framework.Rectangle rectangle4 = value11.Frame();
                     Vector2 origin5 = rectangle4.Size() * new Vector2(0.5f, 0.5f);
                     Vector2 vector16 = new Vector2(rCurrentNPC.Center.X, rCurrentNPC.Center.Y);
                     float num55 = 0f;
                     switch (num54)
                     {
                     case 1:
                     case 6:
                         num55 -= 10f;
                         break;
                     case 3:
                     case 5:
                         num55 += 10f;
                         break;
                     case 4:
                     case 12:
                     case 13:
                     case 14:
                     case 15:
                         num55 += 18f;
                         break;
                     case 7:
                     case 8:
                         num55 -= 14f;
                         break;
                     case 9:
                         num55 -= 16f;
                         break;
                     case 10:
                         num55 -= 18f;
                         break;
                     case 11:
                         num55 += 20f;
                         break;
                     case 20:
                         num55 -= 14f;
                         break;
                     case 21:
                     case 23:
                         num55 -= 18f;
                         break;
                     case 22:
                         num55 -= 22f;
                         break;
                     }
                     vector16.Y += num55;
                     if (rCurrentNPC.rotation != 0f)
                     {
                         vector16 = vector16.RotatedBy(rCurrentNPC.rotation, rCurrentNPC.Bottom);
                     }
                     vector16 -= screenPos;
                     if (!rCurrentNPC.IsABestiaryIconDummy)
                     {
                         mySpriteBatch.End();
                         mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Transform);
                     }
                     GameShaders.Misc["QueenSlime"].Apply();
                     if (rCurrentNPC.ai[0] == 4f && rCurrentNPC.velocity.Y != 0f)
                     {
                         float num56 = 1f;
                         if (rCurrentNPC.ai[2] == 1f)
{
                             num56 = 6f;
                         }
                         for (int num57 = 7; num57 >= 0; num57--)
{
                             float num58 = 1f - (float)num57 / 8f;
                             Vector2 vector17 = rCurrentNPC.oldPos[num57] + new Vector2((float)rCurrentNPC.width * 0.5f, rCurrentNPC.height);
                             vector17 -= (rCurrentNPC.Bottom - Vector2.Lerp(vector17, rCurrentNPC.Bottom, 0.75f)) * num56;
                             vector17 -= screenPos;
                             Microsoft.Xna.Framework.Color color16 = color15 * num58;
                             mySpriteBatch.Draw(value10, vector17, rectangle3, color16, rCurrentNPC.rotation, origin4, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                         }
                     }
                     if (!rCurrentNPC.IsABestiaryIconDummy)
                     {
                         mySpriteBatch.End();
                         mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
                     }
                     pixelShader.CurrentTechnique.Passes[0].Apply();
                     mySpriteBatch.Draw(value11, vector16, rectangle4, color15, rCurrentNPC.rotation, origin5, 1f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     GameShaders.Misc["QueenSlime"].Apply();
                     if (!rCurrentNPC.IsABestiaryIconDummy)
                     {
                         mySpriteBatch.End();
                         mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Transform);
                     }
                     DrawData value12 = new DrawData(value10, position7, rectangle3, rCurrentNPC.GetAlpha(color15), rCurrentNPC.rotation, origin4, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally);
                     GameShaders.Misc["QueenSlime"].Apply(value12);
                     value12.Draw(mySpriteBatch);
                     pixelShader.CurrentTechnique.Passes[0].Apply();
                     if (!rCurrentNPC.IsABestiaryIconDummy)
                     {
                         mySpriteBatch.End();
                         mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
                     }
                     Texture2D value13 = TextureAssets.Extra[177].Value;
                     rectangle3 = value13.Frame();
                     origin4 = rectangle3.Size() * new Vector2(0.5f, 0.5f);
                     position7 = new Vector2(rCurrentNPC.Center.X, rCurrentNPC.Top.Y - (float)rectangle3.Bottom + 44f);
                     float num59 = 0f;
                     switch (num54)
                     {
                     case 1:
                         num59 -= 10f;
                         break;
                     case 3:
                     case 5:
                     case 6:
                         num59 += 10f;
                         break;
                     case 4:
                     case 12:
                     case 13:
                     case 14:
                     case 15:
                         num59 += 18f;
                         break;
                     case 7:
                     case 8:
                         num59 -= 14f;
                         break;
                     case 9:
                         num59 -= 16f;
                         break;
                     case 10:
                         num59 -= 18f;
                         break;
                     case 11:
                         num59 += 20f;
                         break;
                     case 20:
                         num59 -= 14f;
                         break;
                     case 21:
                     case 23:
                         num59 -= 18f;
                         break;
                     case 22:
                         num59 -= 22f;
                         break;
                     }
                     position7.Y += num59;
                     if (rCurrentNPC.rotation != 0f)
                     {
                         position7 = position7.RotatedBy(rCurrentNPC.rotation, rCurrentNPC.Bottom);
                     }
                     position7 -= screenPos;
                     mySpriteBatch.Draw(value13, position7, rectangle3, color15, rCurrentNPC.rotation, origin4, 1f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     return;
                 }
                 case 576:
                 case 577:
                 {
                     Texture2D value17 = TextureAssets.Npc[type].Value;
                     Vector2 vector18 = rCurrentNPC.Bottom - screenPos;
                     Microsoft.Xna.Framework.Rectangle rectangle7 = value17.Frame(5, 10, rCurrentNPC.frame.Y / 10, rCurrentNPC.frame.Y % 10);
                     Vector2 origin8 = rectangle7.Size() * new Vector2(0.5f, 1f);
                     origin8.Y -= 4f;
                     int num60 = 94;
                     if (rCurrentNPC.spriteDirection == 1)
                     {
                         origin8.X = num60;
                     }
                     else
                     {
                         origin8.X = rectangle7.Width - num60;
                     }
                     Microsoft.Xna.Framework.Color value18 = Microsoft.Xna.Framework.Color.White;
                     float amount3 = 0f;
                     float amount4 = 0f;
                     int num61 = 0;
                     float num62 = 0f;
                     Microsoft.Xna.Framework.Color color18 = npcColor;
                     if (rCurrentNPC.localAI[3] < 60f)
                     {
                         _ = 8f;
                         float num63 = rCurrentNPC.localAI[3] / 60f;
                         num61 = 3;
                         num62 = 1f - num63 * num63;
                         value18 = new Microsoft.Xna.Framework.Color(127, 0, 255, 0);
                         amount4 = 1f;
                         color18 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color18, num63 * num63);
                     }
                     for (int num64 = 0; num64 < num61; num64++)
                     {
                         Microsoft.Xna.Framework.Color value19 = npcColor;
                         value19 = Microsoft.Xna.Framework.Color.Lerp(value19, value18, amount3);
                         value19 = rCurrentNPC.GetAlpha(value19);
                         value19 = Microsoft.Xna.Framework.Color.Lerp(value19, value18, amount4);
                         value19 *= 1f - num62;
                         Vector2 position10 = vector18;
                         position10 -= new Vector2(value17.Width, value17.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position10 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value17, position10, rectangle7, value19, rCurrentNPC.rotation, origin8, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     }
                     mySpriteBatch.Draw(value17, vector18, rectangle7, rCurrentNPC.GetAlpha(color18), rCurrentNPC.rotation, origin8, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     return;
                 }
                 case 594:
                 {
                     Texture2D value14 = TextureAssets.Npc[type].Value;
                     Vector2 position8 = rCurrentNPC.Top - screenPos;
                     Microsoft.Xna.Framework.Rectangle rectangle5 = value14.Frame(8, 1, rCurrentNPC.frame.Y);
                     Microsoft.Xna.Framework.Rectangle value15 = value14.Frame(8);
                     Vector2 origin6 = rectangle5.Size() * new Vector2(0.5f, 0f);
                     Microsoft.Xna.Framework.Color color17 = npcColor;
                     float scale3 = 1f;
                     NPC nPC = rCurrentNPC.AI_113_WindyBalloon_GetSlaveNPC();
                     if (nPC != null)
                     {
                         scale3 = nPC.scale;
                         if (nPC.ai[1] > 0f)
{
                             DrawNPC_SlimeItem(nPC, nPC.type, color17, rCurrentNPC.rotation);
                         }
                         mySpriteBatch.Draw(value14, position8, value15, nPC.GetAlpha(color17), rCurrentNPC.rotation, origin6, scale3, spriteEffects, 0f);
                         mySpriteBatch.Draw(value14, position8, value15, nPC.GetColor(color17), rCurrentNPC.rotation, origin6, scale3, spriteEffects, 0f);
                     }
                     mySpriteBatch.Draw(value14, position8, rectangle5, rCurrentNPC.GetAlpha(color17), rCurrentNPC.rotation, origin6, scale3, spriteEffects, 0f);
                     return;
                 }
                 case 686:
                 {
                     Texture2D value16 = TextureAssets.Npc[type].Value;
                     Vector2 position9 = rCurrentNPC.Top - screenPos;
                     Microsoft.Xna.Framework.Rectangle rectangle6 = value16.Frame();
                     Vector2 origin7 = rectangle6.Size() * new Vector2(0.5f, 0f);
                     Microsoft.Xna.Framework.Color newColor2 = npcColor;
                     mySpriteBatch.Draw(value16, position9, rectangle6, rCurrentNPC.GetAlpha(newColor2), rCurrentNPC.rotation, origin7, rCurrentNPC.scale, spriteEffects, 0f);
                     return;
                 }
                 case 564:
                 case 565:
                 {
                     Texture2D value20 = TextureAssets.Npc[type].Value;
                     Vector2 vector19 = rCurrentNPC.Bottom - screenPos;
                     Microsoft.Xna.Framework.Rectangle rectangle8 = value20.Frame(5, 9, rCurrentNPC.frame.Y / 9, rCurrentNPC.frame.Y % 9);
                     Vector2 origin9 = rectangle8.Size() * new Vector2(0.5f, 1f);
                     origin9.Y -= 10f;
                     int num65 = 52;
                     if (rCurrentNPC.spriteDirection == 1)
                     {
                         origin9.X = num65;
                     }
                     else
                     {
                         origin9.X = rectangle8.Width - num65;
                     }
                     Microsoft.Xna.Framework.Color value21 = Microsoft.Xna.Framework.Color.White;
                     float amount5 = 0f;
                     float amount6 = 0f;
                     int num66 = 0;
                     float num67 = 0f;
                     float num68 = 0f;
                     Microsoft.Xna.Framework.Color color19 = npcColor;
                     if (rCurrentNPC.localAI[3] < 60f)
                     {
                         float num69 = rCurrentNPC.localAI[3] / 60f;
                         num66 = 3;
                         num67 = 1f - num69 * num69;
                         num68 = 8f;
                         value21 = new Microsoft.Xna.Framework.Color(127, 0, 255, 0);
                         amount6 = 1f;
                         color19 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color19, num69 * num69);
                     }
                     for (int num70 = 0; num70 < num66; num70++)
                     {
                         Microsoft.Xna.Framework.Color value22 = npcColor;
                         value22 = Microsoft.Xna.Framework.Color.Lerp(value22, value21, amount5);
                         value22 = rCurrentNPC.GetAlpha(value22);
                         value22 = Microsoft.Xna.Framework.Color.Lerp(value22, value21, amount6);
                         value22 *= 1f - num67;
                         Vector2 position11 = vector19;
                         position11 -= new Vector2(value20.Width, value20.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position11 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         position11 += ((float)num70 / (float)num66 * ((float)Math.PI * 2f)).ToRotationVector2() * num68 * num67;
                         mySpriteBatch.Draw(value20, position11, rectangle8, value22, rCurrentNPC.rotation, origin9, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     }
                     Microsoft.Xna.Framework.Color alpha2 = rCurrentNPC.GetAlpha(color19);
                     num66 = 4;
                     num68 = 4f;
                     num67 = 0.625f + (float)Math.Sin(GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 0.75f + (float)Math.PI) * 0.125f;
                     for (int num71 = 0; num71 < num66; num71++)
                     {
                         Microsoft.Xna.Framework.Color color20 = alpha2;
                         color20 *= 1f - num67;
                         Vector2 position12 = vector19;
                         position12 -= new Vector2(value20.Width, value20.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position12 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         position12 += ((float)num71 / (float)num66 * ((float)Math.PI * 2f)).ToRotationVector2() * num68 * num67;
                         mySpriteBatch.Draw(value20, position12, rectangle8, color20, rCurrentNPC.rotation, origin9, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     }
                     mySpriteBatch.Draw(value20, vector19, rectangle8, alpha2, rCurrentNPC.rotation, origin9, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     if (rCurrentNPC.Opacity > 0f)
                     {
                         Microsoft.Xna.Framework.Color white2 = Microsoft.Xna.Framework.Color.White;
                         white2.A /= 2;
                         white2 *= rCurrentNPC.Opacity;
                         mySpriteBatch.Draw(TextureAssets.GlowMask[225].Value, vector19, rectangle8, white2, rCurrentNPC.rotation, origin9, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                         num66 = 4;
                         num68 = 4f;
                         num67 = 0.5f + (float)Math.Sin(GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 0.75f) * 0.5f;
                         for (int num72 = 0; num72 < num66; num72++)
{
                             Microsoft.Xna.Framework.Color color21 = white2 * 0.35f;
                             color21 *= 1f - num67;
                             Vector2 position13 = vector19;
                             position13 -= new Vector2(value20.Width, value20.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                             position13 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                             position13 += ((float)num72 / (float)num66 * ((float)Math.PI * 2f)).ToRotationVector2() * num68 * num67;
                             mySpriteBatch.Draw(TextureAssets.GlowMask[225].Value, position13, rectangle8, color21, rCurrentNPC.rotation, origin9, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                         }
                     }
                     return;
                 }
                 case 548:
                 {
                     Texture2D value8 = TextureAssets.Npc[type].Value;
                     Vector2 vector15 = rCurrentNPC.Bottom - screenPos;
                     Microsoft.Xna.Framework.Rectangle rectangle2 = value8.Frame();
                     Vector2 origin3 = rectangle2.Size() / 2f;
                     origin3.Y += 30f;
                     origin3.Y += 8f;
                     origin3.X -= 1f;
                     Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
                     float amount = 0f;
                     float amount2 = 0f;
                     int num42 = 0;
                     float num43 = 0f;
                     float num44 = 0f;
                     Microsoft.Xna.Framework.Color newColor = npcColor;
                     for (int num45 = 0; num45 < num42; num45++)
                     {
                         Microsoft.Xna.Framework.Color value9 = npcColor;
                         value9 = Microsoft.Xna.Framework.Color.Lerp(value9, white, amount);
                         value9 = rCurrentNPC.GetAlpha(value9);
                         value9 = Microsoft.Xna.Framework.Color.Lerp(value9, white, amount2);
                         value9 *= 1f - num43;
                         Vector2 position3 = vector15;
                         position3 -= new Vector2(value8.Width, value8.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position3 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         position3 += ((float)num45 / (float)num42 * ((float)Math.PI * 2f)).ToRotationVector2() * num44 * num43;
                         mySpriteBatch.Draw(value8, position3, rectangle2, value9, rCurrentNPC.rotation, origin3, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     }
                     Microsoft.Xna.Framework.Color alpha = rCurrentNPC.GetAlpha(newColor);
                     num42 = 4;
                     num44 = 4f;
                     num43 = 0.625f + (float)Math.Sin(GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 0.75f + (float)Math.PI) * 0.125f;
                     for (int num46 = 0; num46 < num42; num46++)
                     {
                         Microsoft.Xna.Framework.Color color12 = alpha;
                         color12.A = 0;
                         color12 *= 1f - num43;
                         Vector2 position4 = vector15;
                         position4 -= new Vector2(value8.Width, value8.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position4 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         position4 += ((float)num46 / (float)num42 * ((float)Math.PI * 2f)).ToRotationVector2() * num44 * num43;
                         mySpriteBatch.Draw(value8, position4, rectangle2, color12, rCurrentNPC.rotation, origin3, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     }
                     mySpriteBatch.Draw(value8, vector15, rectangle2, alpha, rCurrentNPC.rotation, origin3, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     if (rCurrentNPC.ai[1] == 2f)
                     {
                         float num47 = Math.Min(1f, rCurrentNPC.ai[0] / 120f);
                         mySpriteBatch.Draw(value8, vector15, rectangle2, new Microsoft.Xna.Framework.Color(1f, 1f, 1f, 0f) * num47, rCurrentNPC.rotation, origin3, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                         float progress = MathHelper.Clamp(rCurrentNPC.ai[0] / 450f, 0f, 1f);
                         if (!Terraria.Graphics.Effects.Filters.Scene["CrystalWin"].IsActive())
{
                             Terraria.Graphics.Effects.Filters.Scene.Activate("CrystalWin", rCurrentNPC.Center);
                         }
                         else
{
                             Terraria.Graphics.Effects.Filters.Scene["CrystalWin"].GetShader().UseProgress(progress);
                         }
                         Terraria.Graphics.Effects.Filters.Scene["CrystalWin"].GetShader().UseTargetPosition(rCurrentNPC.Center);
                     }
                     num42 = 4;
                     num44 = 4f;
                     num43 = 0.625f + (float)Math.Sin(GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 0.75f) * 0.125f;
                     for (int num48 = 0; num48 < num42; num48++)
                     {
                         Microsoft.Xna.Framework.Color color13 = alpha;
                         color13.A = 0;
                         color13 *= 0.3f;
                         color13 *= 1f - num43;
                         Vector2 position5 = vector15;
                         position5 -= new Vector2(value8.Width, value8.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position5 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         position5 += ((float)num48 / (float)num42 * ((float)Math.PI * 2f)).ToRotationVector2() * num44 * num43;
                         mySpriteBatch.Draw(value8, position5, rectangle2, color13, rCurrentNPC.rotation, origin3, rCurrentNPC.scale, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     }
                     if (rCurrentNPC.alpha < 255)
                     {
                         float num49 = GlobalTimeWrappedHourly % 3f / 3f;
                         float num50 = num49;
                         if (num50 > 0.5f)
{
                             num50 = 1f - num49;
                         }
                         if (num50 < 0f)
{
                             num50 = 0f;
                         }
                         float num51 = (num49 + 0.5f) % 1f;
                         float num52 = num51;
                         if (num52 > 0.5f)
{
                             num52 = 1f - num51;
                         }
                         if (num52 < 0f)
{
                             num52 = 0f;
                         }
                         value8 = TextureAssets.GlowMask[239].Value;
                         rectangle2 = value8.Frame();
                         origin3 = rectangle2.Size() / 2f;
                         Vector2 position6 = vector15 + new Vector2(0f, -40f);
                         Microsoft.Xna.Framework.Color color14 = new Microsoft.Xna.Framework.Color(140, 50, 255, 0);
                         color14 *= 0.6f;
                         mySpriteBatch.Draw(value8, position6, rectangle2, color14, rCurrentNPC.rotation, origin3, rCurrentNPC.scale * 0.75f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                         num43 = 1f + num49 * 0.75f;
                         mySpriteBatch.Draw(value8, position6, rectangle2, color14 * num50, rCurrentNPC.rotation, origin3, rCurrentNPC.scale * 0.75f * num43, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                         num43 = 1f + num51 * 0.75f;
                         mySpriteBatch.Draw(value8, position6, rectangle2, color14 * num52, rCurrentNPC.rotation, origin3, rCurrentNPC.scale * 0.75f * num43, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                         value8 = TextureAssets.Extra[89].Value;
                         rectangle2 = value8.Frame();
                         origin3 = rectangle2.Size() / 2f;
                         Vector2 scale2 = new Vector2(0.75f, 1f + num43) * 1.5f;
                         num43 = 1f + num51 * 0.75f;
                         if (rCurrentNPC.dontTakeDamageFromHostiles)
{
                             scale2.Y *= 0.6f;
                         }
                         position6.Y -= 6f;
                         mySpriteBatch.Draw(value8, position6, rectangle2, color14 * num52, rCurrentNPC.rotation + (float)Math.PI / 2f, origin3, scale2, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                         mySpriteBatch.Draw(value8, position6, rectangle2, Microsoft.Xna.Framework.Color.Lerp(color14, Microsoft.Xna.Framework.Color.White, 0.5f), rCurrentNPC.rotation + (float)Math.PI / 2f, origin3, 1.5f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
                     }
                     return;
                 }
                 default:
                     if (type < 621 || type > 623)
                     {
                         break;
                     }
                     goto case 371;
                 case 371:
                 case 454:
                 case 455:
                 case 456:
                 case 457:
                 case 458:
                 case 459:
                 {
                     Texture2D value7 = TextureAssets.Npc[type].Value;
                     Vector2 position2 = rCurrentNPC.Center - screenPos;
                     position2 -= new Vector2(value7.Width, value7.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                     position2 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     mySpriteBatch.Draw(value7, position2, rCurrentNPC.frame, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     return;
                 }
                 }
                 switch (type)
                 {
                 case 549:
                 {
                     Texture2D value58 = TextureAssets.Npc[type].Value;
                     Vector2 vector61 = rCurrentNPC.Center - screenPos;
                     Microsoft.Xna.Framework.Rectangle frame9 = rCurrentNPC.frame;
                     Vector2 origin22 = new Vector2(70f, 127f);
                     origin22.Y += 8f;
                     Vector2 scale6 = new Vector2(rCurrentNPC.scale);
                     float num201 = rCurrentNPC.localAI[0];
                     if (num201 < 120f)
                     {
                         scale6 *= num201 / 240f + 0.5f;
                     }
                     Microsoft.Xna.Framework.Color alpha12 = rCurrentNPC.GetAlpha(npcColor);
                     float lerpValue2 = Utils.GetLerpValue(0f, 120f, num201, clamped: true);
                     float num202 = MathHelper.Lerp(32f, 0f, lerpValue2);
                     Microsoft.Xna.Framework.Color color42 = alpha12;
                     color42.A = (byte)MathHelper.Lerp((int)color42.A, 0f, lerpValue2);
                     color42 *= lerpValue2;
                     if (num201 >= 120f)
                     {
                         color42 = alpha12;
                     }
                     mySpriteBatch.Draw(value58, vector61, frame9, color42, rCurrentNPC.rotation, origin22, scale6, spriteEffects, 0f);
                     float y3 = (((rCurrentNPC.ai[0] + 54f) % 180f - 120f) / 180f * 2f * ((float)Math.PI * 2f)).ToRotationVector2().Y;
                     if (num201 >= 120f)
                     {
                         num202 = y3 * 0f;
                         color42.A = (byte)((float)(int)color42.A * 0.5f);
                         color42 *= y3 / 2f + 0.5f;
                         float num203 = 1f;
                         for (float num204 = 0f; num204 < num203; num204 += 1f)
{
                             mySpriteBatch.Draw(value58, vector61 + ((float)Math.PI * 2f / num203 * num204).ToRotationVector2() * num202, frame9, color42, rCurrentNPC.rotation, origin22, scale6, spriteEffects, 0f);
                         }
                     }
                     float num205 = rCurrentNPC.ai[0] / 180f - 0.76f;
                     if (num205 < 0f)
                     {
                         num205 += 1f;
                     }
                     float num206 = 0f;
                     float num207 = 0f;
                     float num208 = 0.6f;
                     float num209 = 0.8f;
                     if (num205 >= num208 && num205 <= num209)
                     {
                         num206 = Utils.GetLerpValue(num208, num209, num205);
                         num207 = MathHelper.Lerp(0.75f, 0.85f, num206);
                     }
                     num208 = num209;
                     num209 = num208 + 0.13f;
                     if (num205 >= num208 && num205 <= num209)
                     {
                         num206 = 1f - Utils.GetLerpValue(num208, num209, num205);
                         num207 = MathHelper.Lerp(1.3f, 0.85f, num206);
                     }
                     Vector2 vector62 = new Vector2(0f, -150f);
                     int frameNumber = frame9.Y / frame9.Height;
                     float num210 = MathHelper.Clamp((num201 - 100f) / 40f, 0f, 1f);
                     DrawElderEye(mySpriteBatch, rCurrentNPC.Center + vector62, 0.75f * num210, 0.75f, frameNumber, Microsoft.Xna.Framework.Color.White);
                     DrawElderEye(mySpriteBatch, rCurrentNPC.Center + vector62, 0.75f * num210, 0.75f, frameNumber, new Microsoft.Xna.Framework.Color(255, 255, 255, 127) * (y3 / 2f + 0.5f));
                     if (num206 > 0f && num207 > 0f)
                     {
                         DrawElderEye(mySpriteBatch, rCurrentNPC.Center + vector62, num206 * 0.5f, num207, frameNumber, new Microsoft.Xna.Framework.Color(255, 255, 255, 127));
                     }
                     if (num201 < 120f)
                     {
                         float num211 = (float)Math.PI * 2f * lerpValue2 * (float)Math.Pow(lerpValue2, 2.0) * 2f + lerpValue2;
                         color42.A = (byte)((float)(int)alpha12.A * (float)Math.Pow(lerpValue2, 2.0) * 0.5f);
                         float num212 = 3f;
                         for (float num213 = 0f; num213 < num212; num213 += 1f)
{
                             mySpriteBatch.Draw(value58, vector61 + (num211 + (float)Math.PI * 2f / num212 * num213).ToRotationVector2() * num202, frame9, color42, rCurrentNPC.rotation, origin22, scale6, spriteEffects, 0f);
                         }
                     }
                     break;
                 }
                 case 636:
                     DrawNPCDirect_HallowBoss(mySpriteBatch, rCurrentNPC, ref screenPos, type, ref npcColor, ref halfSize, spriteEffects);
                     break;
                 case 677:
                     DrawNPCDirect_Faeling(mySpriteBatch, rCurrentNPC, ref screenPos, type, ref npcColor, ref halfSize, spriteEffects);
                     break;
                 case 668:
                     DrawNPCDirect_Deerclops(mySpriteBatch, rCurrentNPC, ref screenPos, type, ref npcColor, ref halfSize, spriteEffects);
                     break;
                 case 422:
                 case 493:
                 case 507:
                 case 517:
                 {
                     Texture2D value60 = TextureAssets.Npc[type].Value;
                     Vector2 vector65 = rCurrentNPC.Center - screenPos;
                     Vector2 vector66 = vector65 - new Vector2(300f, 310f);
                     vector65 -= new Vector2(value60.Width, value60.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                     vector65 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     mySpriteBatch.Draw(value60, vector65, rCurrentNPC.frame, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     switch (type)
                     {
                     case 493:
                     {
                         value60 = TextureAssets.GlowMask[132].Value;
                         float num228 = 4f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 4f;
                         for (int num229 = 0; num229 < 4; num229++)
{
                             mySpriteBatch.Draw(value60, vector65 + rCurrentNPC.velocity.RotatedBy((float)num229 * ((float)Math.PI / 2f)) * num228, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0) * rCurrentNPC.Opacity, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         break;
                     }
                     case 507:
                     {
                         value60 = TextureAssets.GlowMask[143].Value;
                         float num224 = 4f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 4f;
                         for (int num225 = 0; num225 < 4; num225++)
{
                             mySpriteBatch.Draw(value60, vector65 + rCurrentNPC.velocity.RotatedBy((float)num225 * ((float)Math.PI / 2f)) * num224, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0) * rCurrentNPC.Opacity, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         break;
                     }
                     case 422:
                     {
                         value60 = TextureAssets.GlowMask[149].Value;
                         float num226 = 4f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 4f;
                         for (int num227 = 0; num227 < 4; num227++)
{
                             mySpriteBatch.Draw(value60, vector65 + rCurrentNPC.velocity.RotatedBy((float)num227 * ((float)Math.PI / 2f)) * num226, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0) * rCurrentNPC.Opacity, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         break;
                     }
                     case 517:
                     {
                         value60 = TextureAssets.GlowMask[162].Value;
                         float num222 = 2f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 9f;
                         for (int num223 = 0; num223 < 4; num223++)
{
                             mySpriteBatch.Draw(value60, vector65 + rCurrentNPC.velocity.RotatedBy((float)num223 * ((float)Math.PI / 2f)) * num222 + Vector2.UnitX * 2f, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0) * rCurrentNPC.Opacity, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         break;
                     }
                     }
                     int num230 = 0;
                     string key = "";
                     switch (type)
                     {
                     case 422:
                         num230 = NPC.ShieldStrengthTowerVortex;
                         key = "Vortex";
                         break;
                     case 507:
                         num230 = NPC.ShieldStrengthTowerNebula;
                         key = "Nebula";
                         break;
                     case 517:
                         num230 = NPC.ShieldStrengthTowerSolar;
                         key = "Solar";
                         break;
                     case 493:
                         num230 = NPC.ShieldStrengthTowerStardust;
                         key = "Stardust";
                         break;
                     }
                     float num231 = (float)num230 / (float)NPC.ShieldStrengthTowerMax;
                     if (rCurrentNPC.IsABestiaryIconDummy)
                     {
                         break;
                     }
                     if (num230 > 0)
                     {
                         mySpriteBatch.End();
                         mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointWrap, DepthStencilState.Default, RasterizerState.CullNone, null, Transform);
                         float num232 = 0f;
                         if (rCurrentNPC.ai[3] > 0f && rCurrentNPC.ai[3] <= 30f)
{
                             num232 = 1f - rCurrentNPC.ai[3] / 30f;
                         }
                         Terraria.Graphics.Effects.Filters.Scene[key].GetShader().UseIntensity(1f + num232).UseProgress(0f);
                         DrawData value61 = new DrawData(Assets.Request<Texture2D>("Images/Misc/Perlin", (AssetRequestMode)1).Value, vector66 + new Vector2(300f, 300f), new Microsoft.Xna.Framework.Rectangle(0, 0, 600, 600), Microsoft.Xna.Framework.Color.White * (num231 * 0.8f + 0.2f), rCurrentNPC.rotation, new Vector2(300f, 300f), rCurrentNPC.scale * (1f + num232 * 0.05f), spriteEffects);
                         GameShaders.Misc["ForceField"].UseColor(new Vector3(1f + num232 * 0.5f));
                         GameShaders.Misc["ForceField"].Apply(value61);
                         value61.Draw(mySpriteBatch);
                         mySpriteBatch.End();
                         mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
                     }
                     else if (rCurrentNPC.ai[3] > 0f)
                     {
                         mySpriteBatch.End();
                         mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointWrap, DepthStencilState.Default, RasterizerState.CullNone, null, Transform);
                         float num233 = rCurrentNPC.ai[3] / 120f;
                         float num234 = Math.Min(rCurrentNPC.ai[3] / 30f, 1f);
                         Terraria.Graphics.Effects.Filters.Scene[key].GetShader().UseIntensity(Math.Min(5f, 15f * num233) + 1f).UseProgress(num233);
                         DrawData value62 = new DrawData(Assets.Request<Texture2D>("Images/Misc/Perlin", (AssetRequestMode)1).Value, vector66 + new Vector2(300f, 300f), new Microsoft.Xna.Framework.Rectangle(0, 0, 600, 600), new Microsoft.Xna.Framework.Color(new Vector4(1f - (float)Math.Sqrt(num234))), rCurrentNPC.rotation, new Vector2(300f, 300f), rCurrentNPC.scale * (1f + num234), spriteEffects);
                         GameShaders.Misc["ForceField"].UseColor(new Vector3(2f));
                         GameShaders.Misc["ForceField"].Apply(value62);
                         value62.Draw(mySpriteBatch);
                         mySpriteBatch.End();
                         mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
                     }
                     else
                     {
                         Terraria.Graphics.Effects.Filters.Scene[key].GetShader().UseIntensity(0f).UseProgress(0f);
                     }
                     break;
                 }
                 case 402:
                 {
                     LoadNPC(403);
                     LoadNPC(404);
                     Texture2D value59 = TextureAssets.Npc[rCurrentNPC.type].Value;
                     Vector2 vector63 = rCurrentNPC.Center - screenPos;
                     vector63 -= new Vector2(value59.Width, value59.Height / npcFrameCount[rCurrentNPC.type]) * rCurrentNPC.scale / 2f;
                     vector63 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     int num214 = 0;
                     float num215 = 2f / (float)rCurrentNPC.oldPos.Length * 0.7f;
                     float num216 = 600f;
                     float num217 = num216 - 30f;
                     float num218 = Utils.Remap(rCurrentNPC.ai[2], 0f, num216, 0f, 1f);
                     float num219 = 1f - Utils.Remap(num218, 0.5f, num217 / num216, 0f, 1f) * Utils.Remap(num218, num217 / num216, 1f, 1f, 0f);
                     int num220 = rCurrentNPC.oldPos.Length - 1;
                     while ((float)num220 >= 1f)
                     {
                         for (int num221 = 0; num221 < 2; num221++)
{
                             value59 = ((num214 != 0) ? TextureAssets.Npc[403].Value : TextureAssets.Npc[404].Value);
                             Vector2 position21 = vector63 + rCurrentNPC.oldPos[num220] - rCurrentNPC.position;
                             float rotation10 = rCurrentNPC.oldRot[num220];
                             if (num220 >= 1 && num221 == 1)
{
                                 Vector2 vector64 = Vector2.Lerp(rCurrentNPC.oldPos[num220], rCurrentNPC.oldPos[num220 - 1], 0.5f) - rCurrentNPC.oldPos[num220];
                                 rotation10 = MathHelper.WrapAngle(rCurrentNPC.oldRot[num220 - 1] * 0.5f + rCurrentNPC.oldRot[num220] * 0.5f);
                                 position21 += vector64;
                             }
                             float scale7 = rCurrentNPC.scale;
                             mySpriteBatch.Draw(value59, position21, null, rCurrentNPC.GetAlpha(npcColor) * (0.8f - num215 * (float)num220 / 2f) * num219, rotation10, halfSize, scale7, spriteEffects, 0f);
                             value59 = ((num214 != 0) ? TextureAssets.GlowMask[133].Value : TextureAssets.GlowMask[134].Value);
                             mySpriteBatch.Draw(value59, position21, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * (1f - num215 * (float)num220 / 2f) * num219, rotation10, halfSize, scale7, spriteEffects, 0f);
                             num214++;
                         }
                         num220 -= 2;
                     }
                     value59 = TextureAssets.Npc[rCurrentNPC.type].Value;
                     mySpriteBatch.Draw(value59, vector63, rCurrentNPC.frame, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     value59 = TextureAssets.GlowMask[135].Value;
                     mySpriteBatch.Draw(value59, vector63, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * num219, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     DrawPrettyStarSparkle(Utils.Remap(rCurrentNPC.ai[2], 0f, num216, 0f, 1f), SpriteEffects.None, vector63, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), Microsoft.Xna.Framework.Color.CornflowerBlue, num218, 0.5f, num217 / num216, num217 / num216, 1f, (float)Math.PI * 2f * num218, new Vector2(2f, 2f), new Vector2(2f, 2f));
                     break;
                 }
                 case 519:
                 {
                     Texture2D value63 = TextureAssets.Npc[rCurrentNPC.type].Value;
                     Vector2 vector67 = rCurrentNPC.Center - screenPos;
                     vector67 -= new Vector2(value63.Width, value63.Height / npcFrameCount[rCurrentNPC.type]) * rCurrentNPC.scale / 2f;
                     vector67 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     value63 = TextureAssets.Npc[rCurrentNPC.type].Value;
                     mySpriteBatch.Draw(value63, vector67, rCurrentNPC.frame, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     int num235 = 0;
                     float num236 = 1f / (float)rCurrentNPC.oldPos.Length * 0.7f;
                     int num237 = rCurrentNPC.oldPos.Length - 1;
                     while ((float)num237 >= 0f)
                     {
                         float num238 = (float)(rCurrentNPC.oldPos.Length - num237) / (float)rCurrentNPC.oldPos.Length;
                         Microsoft.Xna.Framework.Color pink = Microsoft.Xna.Framework.Color.Pink;
                         pink *= 1f - num236 * (float)num237 / 1f;
                         pink.A = (byte)((float)(int)pink.A * (1f - num238));
                         mySpriteBatch.Draw(value63, vector67 + rCurrentNPC.oldPos[num237] - rCurrentNPC.position, null, pink, rCurrentNPC.oldRot[num237], halfSize, rCurrentNPC.scale * MathHelper.Lerp(0.3f, 1.1f, num238), spriteEffects, 0f);
                         num235++;
                         num237--;
                     }
                     break;
                 }
                 case 522:
                 {
                     Texture2D value70 = TextureAssets.Npc[rCurrentNPC.type].Value;
                     Vector2 vector68 = rCurrentNPC.Center - screenPos;
                     vector68 -= new Vector2(value70.Width, value70.Height / npcFrameCount[rCurrentNPC.type]) * rCurrentNPC.scale / 2f;
                     vector68 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     int num256 = 0;
                     float num257 = 1f / (float)rCurrentNPC.oldPos.Length * 1.1f;
                     int num258 = rCurrentNPC.oldPos.Length - 1;
                     while ((float)num258 >= 0f)
                     {
                         float num259 = (float)(rCurrentNPC.oldPos.Length - num258) / (float)rCurrentNPC.oldPos.Length;
                         Microsoft.Xna.Framework.Color white6 = Microsoft.Xna.Framework.Color.White;
                         white6 *= 1f - num257 * (float)num258 / 1f;
                         white6.A = (byte)((float)(int)white6.A * (1f - num259));
                         mySpriteBatch.Draw(value70, vector68 + rCurrentNPC.oldPos[num258] - rCurrentNPC.position, null, white6, rCurrentNPC.oldRot[num258], halfSize, rCurrentNPC.scale * MathHelper.Lerp(0.8f, 0.3f, num259), spriteEffects, 0f);
                         num256++;
                         num258--;
                     }
                     value70 = TextureAssets.Extra[57].Value;
                     mySpriteBatch.Draw(value70, vector68, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), 0f, value70.Size() / 2f, rCurrentNPC.scale, spriteEffects, 0f);
                     break;
                 }
                 case 370:
                 case 372:
                 case 373:
                 {
                     Texture2D value64 = TextureAssets.Npc[type].Value;
                     Microsoft.Xna.Framework.Color value65 = Microsoft.Xna.Framework.Color.White;
                     float amount8 = 0f;
                     bool flag12 = type == 370 && rCurrentNPC.ai[0] > 4f;
                     bool num239 = type == 370 && rCurrentNPC.ai[0] > 9f;
                     int num240 = 120;
                     int num241 = 60;
                     Microsoft.Xna.Framework.Color color43 = npcColor;
                     if (num239)
                     {
                         npcColor = buffColor(npcColor, 0.4f, 0.8f, 0.4f, 1f);
                     }
                     else if (flag12)
                     {
                         npcColor = buffColor(npcColor, 0.5f, 0.7f, 0.5f, 1f);
                     }
                     else if (type == 370 && rCurrentNPC.ai[0] == 4f && rCurrentNPC.ai[2] > (float)num240)
                     {
                         float num242 = rCurrentNPC.ai[2] - (float)num240;
                         num242 /= (float)num241;
                         npcColor = buffColor(npcColor, 1f - 0.5f * num242, 1f - 0.3f * num242, 1f - 0.5f * num242, 1f);
                     }
                     int num243 = 10;
                     int num244 = 2;
                     switch (type)
                     {
                     case 370:
                         if (rCurrentNPC.ai[0] == -1f)
{
                             num243 = 0;
                         }
                         if (rCurrentNPC.ai[0] == 0f || rCurrentNPC.ai[0] == 5f || rCurrentNPC.ai[0] == 10f)
{
                             num243 = 7;
                         }
                         if (rCurrentNPC.ai[0] == 1f)
{
                             value65 = Microsoft.Xna.Framework.Color.Blue;
                             amount8 = 0.5f;
                         }
                         else
{
                             color43 = npcColor;
                         }
                         break;
                     case 372:
                     case 373:
                         if (rCurrentNPC.ai[0] == 1f)
{
                             value65 = Microsoft.Xna.Framework.Color.Blue;
                             amount8 = 0.5f;
                         }
                         break;
                     }
                     for (int num245 = 1; num245 < num243; num245 += num244)
                     {
                         _ = ref rCurrentNPC.oldPos[num245];
                         Microsoft.Xna.Framework.Color value66 = color43;
                         value66 = Microsoft.Xna.Framework.Color.Lerp(value66, value65, amount8);
                         value66 = rCurrentNPC.GetAlpha(value66);
                         value66 *= (float)(num243 - num245) / 15f;
                         Vector2 position22 = rCurrentNPC.oldPos[num245] + new Vector2(rCurrentNPC.width, rCurrentNPC.height) / 2f - screenPos;
                         position22 -= new Vector2(value64.Width, value64.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position22 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value64, position22, rCurrentNPC.frame, value66, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     int num246 = 0;
                     float num247 = 0f;
                     float num248 = 0f;
                     if (type == 370)
                     {
                         if (rCurrentNPC.ai[0] == -1f)
{
                             num246 = 0;
                         }
                         if (rCurrentNPC.ai[0] == 3f || rCurrentNPC.ai[0] == 8f)
{
                             int num249 = 60;
                             int num250 = 30;
                             if (rCurrentNPC.ai[2] > (float)num249)
{
                                 num246 = 6;
                                 num247 = 1f - (float)Math.Cos((rCurrentNPC.ai[2] - (float)num249) / (float)num250 * ((float)Math.PI * 2f));
                                 num247 /= 3f;
                                 num248 = 40f;
                             }
                         }
                         if (rCurrentNPC.ai[0] == 4f && rCurrentNPC.ai[2] > (float)num240)
{
                             num246 = 6;
                             num247 = 1f - (float)Math.Cos((rCurrentNPC.ai[2] - (float)num240) / (float)num241 * ((float)Math.PI * 2f));
                             num247 /= 3f;
                             num248 = 60f;
                         }
                         if (rCurrentNPC.ai[0] == 9f && rCurrentNPC.ai[2] > (float)num240)
{
                             num246 = 6;
                             num247 = 1f - (float)Math.Cos((rCurrentNPC.ai[2] - (float)num240) / (float)num241 * ((float)Math.PI * 2f));
                             num247 /= 3f;
                             num248 = 60f;
                         }
                         if (rCurrentNPC.ai[0] == 12f)
{
                             num246 = 6;
                             num247 = 1f - (float)Math.Cos(rCurrentNPC.ai[2] / 30f * ((float)Math.PI * 2f));
                             num247 /= 3f;
                             num248 = 20f;
                         }
                     }
                     for (int num251 = 0; num251 < num246; num251++)
                     {
                         Microsoft.Xna.Framework.Color value67 = npcColor;
                         value67 = Microsoft.Xna.Framework.Color.Lerp(value67, value65, amount8);
                         value67 = rCurrentNPC.GetAlpha(value67);
                         value67 *= 1f - num247;
                         Vector2 position23 = rCurrentNPC.Center + ((float)num251 / (float)num246 * ((float)Math.PI * 2f) + rCurrentNPC.rotation).ToRotationVector2() * num248 * num247 - screenPos;
                         position23 -= new Vector2(value64.Width, value64.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position23 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value64, position23, rCurrentNPC.frame, value67, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     Vector2 position24 = rCurrentNPC.Center - screenPos;
                     position24 -= new Vector2(value64.Width, value64.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                     position24 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     mySpriteBatch.Draw(value64, position24, rCurrentNPC.frame, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     if (type != 370 || !(rCurrentNPC.ai[0] >= 4f))
                     {
                         break;
                     }
                     value64 = TextureAssets.DukeFishron.Value;
                     Microsoft.Xna.Framework.Color color44 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Color.Yellow, 0.5f);
                     value65 = Microsoft.Xna.Framework.Color.Yellow;
                     amount8 = 1f;
                     num247 = 0.5f;
                     num248 = 10f;
                     num244 = 1;
                     if (rCurrentNPC.ai[0] == 4f)
                     {
                         float num252 = rCurrentNPC.ai[2] - (float)num240;
                         num252 /= (float)num241;
                         value65 *= num252;
                         color44 *= num252;
                     }
                     if (rCurrentNPC.ai[0] == 12f)
                     {
                         float num253 = rCurrentNPC.ai[2];
                         num253 /= 30f;
                         if (num253 > 0.5f)
{
                             num253 = 1f - num253;
                         }
                         num253 *= 2f;
                         num253 = 1f - num253;
                         value65 *= num253;
                         color44 *= num253;
                     }
                     for (int num254 = 1; num254 < num243; num254 += num244)
                     {
                         _ = ref rCurrentNPC.oldPos[num254];
                         Microsoft.Xna.Framework.Color value68 = color44;
                         value68 = Microsoft.Xna.Framework.Color.Lerp(value68, value65, amount8);
                         value68 *= (float)(num243 - num254) / 15f;
                         Vector2 position25 = rCurrentNPC.oldPos[num254] + new Vector2(rCurrentNPC.width, rCurrentNPC.height) / 2f - screenPos;
                         position25 -= new Vector2(value64.Width, value64.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position25 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value64, position25, rCurrentNPC.frame, value68, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     for (int num255 = 1; num255 < num246; num255++)
                     {
                         Microsoft.Xna.Framework.Color value69 = color44;
                         value69 = Microsoft.Xna.Framework.Color.Lerp(value69, value65, amount8);
                         value69 = rCurrentNPC.GetAlpha(value69);
                         value69 *= 1f - num247;
                         Vector2 position26 = rCurrentNPC.Center + ((float)num255 / (float)num246 * ((float)Math.PI * 2f) + rCurrentNPC.rotation).ToRotationVector2() * num248 * num247 - screenPos;
                         position26 -= new Vector2(value64.Width, value64.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position26 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value64, position26, rCurrentNPC.frame, value69, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     mySpriteBatch.Draw(value64, position24, rCurrentNPC.frame, color44, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     break;
                 }
                 case 439:
                 case 440:
                 {
                     int num260 = rCurrentNPC.frame.Y / (TextureAssets.Npc[type].Height() / npcFrameCount[type]);
                     Texture2D value71 = TextureAssets.Npc[type].Value;
                     Texture2D value72 = TextureAssets.Extra[30].Value;
                     Microsoft.Xna.Framework.Rectangle rectangle11 = value72.Frame();
                     rectangle11.Height /= 2;
                     if (num260 >= 4)
                     {
                         rectangle11.Y += rectangle11.Height;
                     }
                     Microsoft.Xna.Framework.Color white7 = Microsoft.Xna.Framework.Color.White;
                     float amount9 = 0f;
                     Microsoft.Xna.Framework.Color color45 = npcColor;
                     int num261 = 0;
                     int num262 = 0;
                     int num263 = 0;
                     if (rCurrentNPC.ai[0] == -1f)
                     {
                         if (rCurrentNPC.ai[1] >= 320f && rCurrentNPC.ai[1] < 960f)
{
                             white7 = Microsoft.Xna.Framework.Color.White;
                             amount9 = 0.5f;
                             num261 = 6;
                             num262 = 2;
                             num263 = 1;
                         }
                     }
                     else if (rCurrentNPC.ai[0] == 1f)
                     {
                         white7 = Microsoft.Xna.Framework.Color.White;
                         amount9 = 0.5f;
                         num261 = 4;
                         num262 = 2;
                         num263 = 1;
                     }
                     else
                     {
                         color45 = npcColor;
                     }
                     for (int num264 = num263; num264 < num261; num264 += num262)
                     {
                         _ = ref rCurrentNPC.oldPos[num264];
                         Microsoft.Xna.Framework.Color value73 = color45;
                         value73 = Microsoft.Xna.Framework.Color.Lerp(value73, white7, amount9);
                         value73 = rCurrentNPC.GetAlpha(value73);
                         value73 *= (float)(num261 - num264) / (float)num261;
                         value73.A = 100;
                         Vector2 position27 = rCurrentNPC.oldPos[num264] + new Vector2(rCurrentNPC.width, rCurrentNPC.height) / 2f - screenPos;
                         position27 -= rectangle11.Size() * rCurrentNPC.scale / 2f;
                         position27 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value72, position27, rectangle11, value73, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     int num265 = 0;
                     float num266 = 0f;
                     float num267 = 0f;
                     if (rCurrentNPC.ai[0] == 5f && rCurrentNPC.ai[1] >= 0f && rCurrentNPC.ai[1] < 30f)
                     {
                         num265 = 4;
                         num266 = 1f - (float)Math.Cos((rCurrentNPC.ai[1] - 0f) / 30f * (float)Math.PI);
                         num266 /= 2f;
                         num267 = 70f;
                     }
                     for (int num268 = 0; num268 < num265; num268++)
                     {
                         Microsoft.Xna.Framework.Color value74 = npcColor;
                         value74 = Microsoft.Xna.Framework.Color.Lerp(value74, white7, amount9);
                         value74 = rCurrentNPC.GetAlpha(value74);
                         value74 *= 1f - num266;
                         Vector2 position28 = rCurrentNPC.Center + ((float)num268 / (float)num265 * ((float)Math.PI * 2f) + rCurrentNPC.rotation).ToRotationVector2() * num267 * num266 - screenPos;
                         position28 -= new Vector2(value71.Width, value71.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position28 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value72, position28, rectangle11, value74, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     Vector2 position29 = rCurrentNPC.Center - screenPos;
                     position29 -= new Vector2(value71.Width, value71.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                     position29 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     mySpriteBatch.Draw(value71, position29, rCurrentNPC.frame, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     break;
                 }
                 case 392:
                 case 393:
                 case 394:
                 case 395:
                 {
                     Texture2D value75 = TextureAssets.Npc[type].Value;
                     Vector2 vec = rCurrentNPC.Center - screenPos + Vector2.UnitY * rCurrentNPC.gfxOffY;
                     vec = vec.Floor();
                     float num269 = 0f;
                     if (type == 393)
                     {
                         num269 = -8f;
                     }
                     mySpriteBatch.Draw(value75, vec, rCurrentNPC.frame, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize + Vector2.UnitY * num269, rCurrentNPC.scale, spriteEffects, 0f);
                     if (type == 392)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[48].Value, vec, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, halfSize + Vector2.UnitY * num269, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     if (type == 395)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[49].Value, vec, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, halfSize + Vector2.UnitY * num269, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     if (type == 394)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[50].Value, vec, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, halfSize + Vector2.UnitY * num269, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     break;
                 }
                 case 83:
                 case 84:
                 case 179:
                     mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35), rCurrentNPC.frame, Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     break;
                 case 87:
                 case 88:
                 case 89:
                 case 90:
                 case 91:
                 case 92:
                 {
                     Microsoft.Xna.Framework.Color alpha13 = rCurrentNPC.GetAlpha(npcColor);
                     byte b3 = (byte)((tileColor.R + tileColor.G + tileColor.B) / 3);
                     if (alpha13.R < b3)
                     {
                         alpha13.R = b3;
                     }
                     if (alpha13.G < b3)
                     {
                         alpha13.G = b3;
                     }
                     if (alpha13.B < b3)
                     {
                         alpha13.B = b3;
                     }
                     mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35), rCurrentNPC.frame, alpha13, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     break;
                 }
                 default:
                 {
                     switch (type)
                     {
                     case 491:
                     {
                         Texture2D value38 = TextureAssets.Npc[rCurrentNPC.type].Value;
                         Microsoft.Xna.Framework.Rectangle frame3 = rCurrentNPC.frame;
                         Vector2 origin15 = frame3.OriginFlip(new Vector2(208f, 460f), spriteEffects);
                         Vector2 vector34 = rCurrentNPC.Center - screenPos;
                         Vector2 vector35 = new Vector2((!spriteEffects.HasFlag(SpriteEffects.FlipHorizontally)) ? 1 : (-1), 1f);
                         Microsoft.Xna.Framework.Color alpha7 = rCurrentNPC.GetAlpha(npcColor);
                         mySpriteBatch.Draw(value38, vector34, frame3, alpha7, rCurrentNPC.rotation, origin15, rCurrentNPC.scale, spriteEffects, 0f);
                         int num89 = (int)rCurrentNPC.localAI[3] / 8;
                         value38 = TextureAssets.Extra[40].Value;
                         frame3 = value38.Frame(1, 4, 0, num89 % 4);
                         origin15 = frame3.Size() * new Vector2(0.5f, 1f);
                         mySpriteBatch.Draw(value38, vector34 + (new Vector2(102f, -384f) * vector35).RotatedBy(rCurrentNPC.rotation), frame3, alpha7, rCurrentNPC.rotation, origin15, rCurrentNPC.scale, spriteEffects, 0f);
                         value38 = TextureAssets.Extra[41].Value;
                         frame3 = value38.Frame(1, 8, 0, num89 % 8);
                         origin15 = frame3.Size() * new Vector2(0.5f, 0f) + new Vector2(0f, 10f);
                         for (int num90 = 0; num90 < 5; num90++)
{
                             mySpriteBatch.Draw(value38, vector34 + (new Vector2(-96 + 34 * num90, 40f) * vector35).RotatedBy(rCurrentNPC.rotation), frame3, alpha7, rCurrentNPC.rotation, origin15, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         value38 = TextureAssets.Extra[42].Value;
                         frame3 = value38.Frame(1, 4, 0, num89 % 4);
                         origin15 = frame3.Size() * new Vector2(0.5f, 0f);
                         for (int num91 = 0; num91 < 2; num91++)
{
                             mySpriteBatch.Draw(value38, vector34 + (new Vector2(158 - 106 * num91, -302f) * vector35).RotatedBy(rCurrentNPC.rotation), frame3, alpha7, rCurrentNPC.rotation, origin15, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         value38 = TextureAssets.Extra[43].Value;
                         frame3 = value38.Frame(1, 4, 0, num89 % 4);
                         origin15 = frame3.Size() * new Vector2(0.5f, 0f);
                         for (int num92 = 0; num92 < 2; num92++)
{
                             mySpriteBatch.Draw(value38, vector34 + (new Vector2(42 - 178 * num92, -444f) * vector35).RotatedBy(rCurrentNPC.rotation), frame3, alpha7, rCurrentNPC.rotation, origin15, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         value38 = TextureAssets.Extra[44].Value;
                         frame3 = value38.Frame(1, 4, 0, num89 % 4);
                         origin15 = frame3.Size() * new Vector2(0.5f, 0f);
                         mySpriteBatch.Draw(value38, vector34 + (new Vector2(-134f, -302f) * vector35).RotatedBy(rCurrentNPC.rotation), frame3, alpha7, rCurrentNPC.rotation, origin15, rCurrentNPC.scale, spriteEffects, 0f);
                         value38 = TextureAssets.Extra[45].Value;
                         frame3 = value38.Frame(1, 4, 0, (2 + num89) % 4);
                         origin15 = frame3.Size() * new Vector2(0.5f, 0f);
                         mySpriteBatch.Draw(value38, vector34 + (new Vector2(-60f, -330f) * vector35).RotatedBy(rCurrentNPC.rotation), frame3, alpha7, rCurrentNPC.rotation, origin15, rCurrentNPC.scale, spriteEffects, 0f);
                         LoadNPC(492);
                         if (!TextureAssets.Npc[492].IsLoaded)
{
                             return;
                         }
                         value38 = TextureAssets.Npc[492].Value;
                         frame3 = value38.Frame(1, 9);
                         origin15 = frame3.Size() * new Vector2(0.5f, 0f) + new Vector2(0f, 10f);
                         for (int num93 = 0; num93 < 4; num93++)
{
                             int num94 = (int)rCurrentNPC.ai[num93];
                             if (num94 >= 0)
{
                                 frame3.Y = npc[num94].frame.Y;
                                 mySpriteBatch.Draw(value38, vector34 + (new Vector2(-122 + 68 * num93, -20f) * vector35).RotatedBy(rCurrentNPC.rotation), frame3, alpha7, rCurrentNPC.rotation, origin15, rCurrentNPC.scale, spriteEffects, 0f);
                             }
                         }
                         return;
                     }
                     case 398:
                     {
                         bool flag8 = false;
                         Texture2D value23 = TextureAssets.Npc[type].Value;
                         Texture2D value24 = TextureAssets.Extra[16].Value;
                         Texture2D value25 = TextureAssets.Extra[14].Value;
                         float num74 = 340f;
                         float num75 = 0.5f;
                         Vector2 vector20 = new Vector2(220f, -60f);
                         Vector2 vector21 = new Vector2(76f, 66f);
                         Texture2D value26 = TextureAssets.Extra[13].Value;
                         Vector2 origin10 = new Vector2(value26.Width, 278f);
                         Vector2 origin11 = new Vector2(0f, 278f);
                         Vector2 vector22 = new Vector2(0f, 76f);
                         Vector2 center2 = rCurrentNPC.Center;
                         Microsoft.Xna.Framework.Point point = (rCurrentNPC.Center + new Vector2(0f, -150f)).ToTileCoordinates();
                         Microsoft.Xna.Framework.Color alpha4 = rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(Lighting.GetColor(point.X, point.Y), Microsoft.Xna.Framework.Color.White, 0.3f));
                         for (int num76 = 0; num76 < 2; num76++)
{
                             bool flag9 = num76 == 0;
                             Vector2 vector23 = new Vector2((!flag9) ? 1 : (-1), 1f);
                             int num77 = -1;
                             for (int num78 = 0; num78 < 200; num78++)
{
                                 if (npc[num78].active && npc[num78].type == 397 && npc[num78].ai[2] == (float)num76 && npc[num78].ai[3] == (float)rCurrentNPC.whoAmI)
{
                                     num77 = num78;
                                     break;
                                 }
                             }
                             if (num77 != -1)
{
                                 Vector2 vector24 = center2 + vector20 * vector23;
                                 Vector2 vector25 = (npc[num77].Center + vector22 - vector24) * num75;
                                 if (flag8)
{
                                     dust[Dust.NewDust(vector24 + vector25, 0, 0, 6)].noGravity = true;
                                 }
                                 float num79 = (float)Math.Acos(vector25.Length() / num74) * (0f - vector23.X);
                                 SpriteEffects effects = ((!flag9) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
                                 Vector2 origin12 = vector21;
                                 if (!flag9)
{
                                     origin12.X = (float)value25.Width - origin12.X;
                                 }
                                 mySpriteBatch.Draw(value25, vector24 - screenPos, null, alpha4, vector25.ToRotation() - num79 - (float)Math.PI / 2f, origin12, 1f, effects, 0f);
                                 if (flag8)
{
                                     dust[Dust.NewDust(vector24, 0, 0, 6)].noGravity = true;
                                 }
                                 if (flag8)
{
                                     dust[Dust.NewDust(center2, 0, 0, 6)].noGravity = true;
                                 }
                                 if (flag8)
{
                                     dust[Dust.NewDust(vector24 + new Vector2(0f, num74).RotatedBy(vector25.ToRotation() - num79 - (float)Math.PI / 2f), 0, 0, 6)].noGravity = true;
                                 }
                             }
                         }
                         mySpriteBatch.Draw(value26, center2 - screenPos, null, alpha4, 0f, origin10, 1f, SpriteEffects.None, 0f);
                         mySpriteBatch.Draw(value26, center2 - screenPos, null, alpha4, 0f, origin11, 1f, SpriteEffects.FlipHorizontally, 0f);
                         mySpriteBatch.Draw(value24, center2 - screenPos, null, alpha4, 0f, new Vector2(112f, 101f), 1f, SpriteEffects.None, 0f);
                         mySpriteBatch.Draw(value23, center2 - screenPos, rCurrentNPC.frame, alpha4, 0f, rCurrentNPC.frame.Size() / 2f, 1f, SpriteEffects.None, 0f);
                         return;
                     }
                     case 397:
                     {
                         Texture2D value39 = TextureAssets.Npc[type].Value;
                         float num95 = 0.5f;
                         Vector2 vector36 = new Vector2(220f, -60f);
                         Vector2 vector37 = new Vector2(0f, 76f);
                         Texture2D value40 = TextureAssets.Extra[15].Value;
                         Vector2 vector38 = new Vector2(60f, 30f);
                         float num96 = 340f;
                         Vector2 center3 = npc[(int)rCurrentNPC.ai[3]].Center;
                         Microsoft.Xna.Framework.Point point4 = rCurrentNPC.Center.ToTileCoordinates();
                         Microsoft.Xna.Framework.Color alpha8 = rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(Lighting.GetColor(point4.X, point4.Y), Microsoft.Xna.Framework.Color.White, 0.3f));
                         bool flag10 = rCurrentNPC.ai[2] == 0f;
                         Vector2 vector39 = new Vector2((!flag10) ? 1 : (-1), 1f);
                         Vector2 origin16 = new Vector2(120f, 180f);
                         if (!flag10)
{
                             origin16.X = (float)value39.Width - origin16.X;
                         }
                         Texture2D value41 = TextureAssets.Extra[17].Value;
                         Texture2D value42 = TextureAssets.Extra[19].Value;
                         Vector2 vector40 = new Vector2(26f, 42f);
                         if (!flag10)
{
                             vector40.X = (float)value41.Width - vector40.X;
                         }
                         Vector2 vector41 = new Vector2(30f, 66f);
                         Vector2 vector42 = new Vector2(1f * (0f - vector39.X), 3f);
                         Texture2D value43 = TextureAssets.Extra[26].Value;
                         Microsoft.Xna.Framework.Rectangle value44 = value43.Frame();
                         value44.Height /= 4;
                         Vector2 vector43 = center3 + vector36 * vector39;
                         Vector2 vector44 = rCurrentNPC.Center + vector37;
                         Vector2 v = vector43 - vector44;
                         v *= 1f - num95;
                         Vector2 origin17 = vector38;
                         if (!flag10)
{
                             origin17.X = (float)value40.Width - origin17.X;
                         }
                         float num97 = (float)Math.Acos(v.Length() / num96) * (0f - vector39.X);
                         mySpriteBatch.Draw(value40, vector44 - screenPos, null, alpha8, v.ToRotation() + num97 - (float)Math.PI / 2f, origin17, 1f, spriteEffects, 0f);
                         if (rCurrentNPC.ai[0] == -2f)
{
                             int num98 = (int)rCurrentNPC.ai[1];
                             num98 /= 8;
                             value44.Y += value44.Height * num98;
                             mySpriteBatch.Draw(value43, rCurrentNPC.Center - screenPos, value44, alpha8, 0f, vector40 - new Vector2(4f, 4f), 1f, spriteEffects, 0f);
                         }
                         else
{
                             mySpriteBatch.Draw(value41, rCurrentNPC.Center - screenPos, null, alpha8, 0f, vector40, 1f, spriteEffects, 0f);
                             Vector2 vector45 = Utils.Vector2FromElipse(rCurrentNPC.localAI[0].ToRotationVector2(), vector41 * rCurrentNPC.localAI[1]);
                             mySpriteBatch.Draw(value42, rCurrentNPC.Center - screenPos + vector45 + vector42, null, alpha8, 0f, new Vector2(value42.Width, value42.Height) / 2f, 1f, SpriteEffects.None, 0f);
                         }
                         mySpriteBatch.Draw(value39, rCurrentNPC.Center - screenPos, rCurrentNPC.frame, alpha8, 0f, origin16, 1f, spriteEffects, 0f);
                         return;
                     }
                     case 396:
                     {
                         Texture2D value29 = TextureAssets.Npc[type].Value;
                         Vector2 origin13 = new Vector2(191f, 130f);
                         Texture2D value30 = TextureAssets.Extra[18].Value;
                         Texture2D value31 = TextureAssets.Extra[19].Value;
                         Vector2 vector26 = new Vector2(19f, 34f);
                         Vector2 vector27 = new Vector2(27f, 59f);
                         Vector2 vector28 = new Vector2(0f, 0f);
                         Texture2D value32 = TextureAssets.Extra[25].Value;
                         Vector2 vector29 = new Vector2(0f, 214f).RotatedBy(rCurrentNPC.rotation);
                         Microsoft.Xna.Framework.Rectangle rectangle9 = value32.Frame();
                         rectangle9.Height /= 3;
                         rectangle9.Y += rectangle9.Height * (int)(rCurrentNPC.localAI[2] / 7f);
                         Texture2D value33 = TextureAssets.Extra[29].Value;
                         Vector2 vector30 = new Vector2(0f, 4f).RotatedBy(rCurrentNPC.rotation);
                         Microsoft.Xna.Framework.Rectangle rectangle10 = value33.Frame();
                         rectangle10.Height /= 4;
                         rectangle10.Y += rectangle10.Height * (int)(rCurrentNPC.localAI[3] / 5f);
                         Texture2D value34 = TextureAssets.Extra[26].Value;
                         Microsoft.Xna.Framework.Rectangle value35 = value34.Frame();
                         value35.Height /= 4;
                         _ = npc[(int)rCurrentNPC.ai[3]].Center;
                         Microsoft.Xna.Framework.Point point2 = rCurrentNPC.Center.ToTileCoordinates();
                         Microsoft.Xna.Framework.Color alpha5 = rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(Lighting.GetColor(point2.X, point2.Y), Microsoft.Xna.Framework.Color.White, 0.3f));
                         if (rCurrentNPC.ai[0] < 0f)
{
                             int num84 = (int)rCurrentNPC.ai[1];
                             num84 /= 8;
                             value35.Y += value35.Height * num84;
                             mySpriteBatch.Draw(value34, rCurrentNPC.Center - screenPos, value35, alpha5, rCurrentNPC.rotation, vector26 + new Vector2(4f, 4f), 1f, spriteEffects, 0f);
                         }
                         else
{
                             mySpriteBatch.Draw(value30, rCurrentNPC.Center - screenPos, null, alpha5, rCurrentNPC.rotation, vector26, 1f, spriteEffects, 0f);
                             Vector2 vector31 = Utils.Vector2FromElipse(rCurrentNPC.localAI[0].ToRotationVector2(), vector27 * rCurrentNPC.localAI[1]);
                             mySpriteBatch.Draw(value31, rCurrentNPC.Center - screenPos + vector31 + vector28, null, alpha5, rCurrentNPC.rotation, new Vector2(value31.Width, value31.Height) / 2f, 1f, SpriteEffects.None, 0f);
                         }
                         mySpriteBatch.Draw(value29, rCurrentNPC.Center - screenPos, rCurrentNPC.frame, alpha5, rCurrentNPC.rotation, origin13, 1f, spriteEffects, 0f);
                         mySpriteBatch.Draw(value33, (rCurrentNPC.Center - screenPos + vector30).Floor(), rectangle10, alpha5, rCurrentNPC.rotation, rectangle10.Size() / 2f, 1f, spriteEffects, 0f);
                         mySpriteBatch.Draw(value32, (rCurrentNPC.Center - screenPos + vector29).Floor(), rectangle9, alpha5, rCurrentNPC.rotation, rectangle9.Size() / 2f, 1f, spriteEffects, 0f);
                         return;
                     }
                     case 400:
                     {
                         Texture2D value36 = TextureAssets.Npc[type].Value;
                         Texture2D value37 = TextureAssets.Extra[19].Value;
                         Vector2 origin14 = new Vector2(40f, 40f);
                         Vector2 vector32 = new Vector2(30f, 30f);
                         _ = rCurrentNPC.Center;
                         Microsoft.Xna.Framework.Point point3 = rCurrentNPC.Center.ToTileCoordinates();
                         Microsoft.Xna.Framework.Color alpha6 = rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Lerp(Lighting.GetColor(point3.X, point3.Y), Microsoft.Xna.Framework.Color.White, 0.3f));
                         mySpriteBatch.Draw(value36, rCurrentNPC.Center - screenPos, rCurrentNPC.frame, alpha6, rCurrentNPC.rotation, origin14, 1f, spriteEffects, 0f);
                         Vector2 vector33 = Utils.Vector2FromElipse(rCurrentNPC.localAI[0].ToRotationVector2(), vector32 * rCurrentNPC.localAI[1]);
                         mySpriteBatch.Draw(value37, rCurrentNPC.Center - screenPos + vector33, null, alpha6, rCurrentNPC.rotation, value37.Size() / 2f, rCurrentNPC.localAI[2], SpriteEffects.None, 0f);
                         return;
                     }
                     case 416:
                     {
                         int num85 = -1;
                         int num86 = (int)rCurrentNPC.ai[0];
                         Vector2 position15 = rCurrentNPC.position;
                         Vector2 spinningpoint3 = Vector2.Zero;
                         if (npc[num86].active && npc[num86].type == 415)
{
                             num85 = num86;
                         }
                         if (num85 != -1)
{
                             Vector2 position16 = rCurrentNPC.position;
                             rCurrentNPC.Bottom = npc[num85].Bottom;
                             position15 = rCurrentNPC.position;
                             rCurrentNPC.position = position16;
                             rCurrentNPC.gfxOffY = npc[num85].gfxOffY;
                             spinningpoint3 = npc[num85].velocity;
                         }
                         Microsoft.Xna.Framework.Rectangle frame2 = rCurrentNPC.frame;
                         mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(position15.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, position15.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame2, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         if (rCurrentNPC.color != default(Microsoft.Xna.Framework.Color))
{
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(position15.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, position15.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame2, rCurrentNPC.GetColor(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         mySpriteBatch.Draw(TextureAssets.GlowMask[156].Value, position15 + rCurrentNPC.Size * new Vector2(0.5f, 1f) - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         float num87 = 0.5f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                         for (int num88 = 0; num88 < 4; num88++)
{
                             mySpriteBatch.Draw(TextureAssets.GlowMask[156].Value, position15 + rCurrentNPC.Size * new Vector2(0.5f, 1f) - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + spinningpoint3.RotatedBy((float)num88 * ((float)Math.PI / 2f)) * num87, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         return;
                     }
                     case 399:
                     {
                         Texture2D value27 = TextureAssets.Npc[type].Value;
                         (rCurrentNPC.position - screenPos + Vector2.UnitY * rCurrentNPC.gfxOffY).Floor();
                         float num80 = 5f;
                         for (int num81 = 0; (float)num81 < num80; num81++)
{
                             float num82 = 1f - (GlobalTimeWrappedHourly + (float)num81) % num80 / num80;
                             Microsoft.Xna.Framework.Color color22 = Microsoft.Xna.Framework.Color.LimeGreen;
                             if (rCurrentNPC.ai[0] == 1f)
{
                                 color22 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.LimeGreen, Microsoft.Xna.Framework.Color.Red, MathHelper.Clamp(rCurrentNPC.ai[1] / 20f, 0f, 1f));
                             }
                             if (rCurrentNPC.ai[0] == 2f)
{
                                 color22 = Microsoft.Xna.Framework.Color.Red;
                             }
                             color22 *= 1f - num82;
                             color22.A = 0;
                             for (int num83 = 0; num83 < 2; num83++)
{
                                 mySpriteBatch.Draw(TextureAssets.Extra[27].Value, rCurrentNPC.Center - screenPos + Vector2.UnitY * (rCurrentNPC.gfxOffY - 4f + 6f), null, color22, (float)Math.PI / 2f, new Vector2(10f, 48f), num82 * 4f, SpriteEffects.None, 0f);
                             }
                         }
                         mySpriteBatch.Draw(value27, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         value27 = TextureAssets.GlowMask[100].Value;
                         mySpriteBatch.Draw(value27, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha / 2, 127 - rCurrentNPC.alpha / 2, 127 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         value27 = TextureAssets.Extra[20].Value;
                         Microsoft.Xna.Framework.Rectangle value28 = value27.Frame(1, 4, 0, (int)rCurrentNPC.ai[0] + 1);
                         Vector2 position14 = new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)value27.Width * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY + 18f + 6f);
                         mySpriteBatch.Draw(value27, position14, value28, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         value27 = TextureAssets.GlowMask[101].Value;
                         mySpriteBatch.Draw(value27, position14, value28, new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha / 2, 127 - rCurrentNPC.alpha / 2, 127 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         return;
                     }
                     case 94:
                     {
                         for (int num73 = 1; num73 < 6; num73 += 2)
{
                             _ = ref rCurrentNPC.oldPos[num73];
                             Microsoft.Xna.Framework.Color alpha3 = rCurrentNPC.GetAlpha(npcColor);
                             alpha3.R = (byte)(alpha3.R * (10 - num73) / 15);
                             alpha3.G = (byte)(alpha3.G * (10 - num73) / 15);
                             alpha3.B = (byte)(alpha3.B * (10 - num73) / 15);
                             alpha3.A = (byte)(alpha3.A * (10 - num73) / 15);
                             alpha3 = rCurrentNPC.GetShimmerColor(alpha3);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num73].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num73].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, alpha3, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         break;
                     }
                     case 384:
                         return;
                     }
                     if (type == 125 || type == 126 || type == 127 || type == 128 || type == 129 || type == 130 || type == 131 || (type == 139 && rCurrentNPC.ai[3] == 0f) || type == 140)
                     {
                         for (int num99 = 9; num99 >= 0; num99 -= 2)
{
                             _ = ref rCurrentNPC.oldPos[num99];
                             Microsoft.Xna.Framework.Color alpha9 = rCurrentNPC.GetAlpha(npcColor);
                             alpha9.R = (byte)(alpha9.R * (10 - num99) / 20);
                             alpha9.G = (byte)(alpha9.G * (10 - num99) / 20);
                             alpha9.B = (byte)(alpha9.B * (10 - num99) / 20);
                             alpha9.A = (byte)(alpha9.A * (10 - num99) / 20);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num99].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num99].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, alpha9, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     if (type == 417 && rCurrentNPC.ai[0] >= 6f && rCurrentNPC.ai[0] <= 6f)
                     {
                         for (int num100 = 5; num100 >= 0; num100--)
{
                             _ = ref rCurrentNPC.oldPos[num100];
                             Microsoft.Xna.Framework.Color alpha10 = rCurrentNPC.GetAlpha(npcColor);
                             alpha10.R = (byte)(alpha10.R * (10 - num100) / 20);
                             alpha10.G = (byte)(alpha10.G * (10 - num100) / 20);
                             alpha10.B = (byte)(alpha10.B * (10 - num100) / 20);
                             alpha10.A = (byte)(alpha10.A * (10 - num100) / 20);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num100].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num100].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, alpha10, rCurrentNPC.oldRot[num100], halfSize, MathHelper.Lerp(0.5f, 1f, (5f - (float)num100) / 6f), spriteEffects, 0f);
                         }
                     }
                     if (type == 419 && rCurrentNPC.ai[2] <= -9f)
                     {
                         int num101 = TextureAssets.GlowMask[154].Height() / npcFrameCount[type];
                         int num102 = rCurrentNPC.frame.Y / num101;
                         for (int num103 = 6; num103 >= 0; num103--)
{
                             _ = ref rCurrentNPC.oldPos[num103];
                             Microsoft.Xna.Framework.Color white3 = Microsoft.Xna.Framework.Color.White;
                             white3.R = (byte)(255 * (10 - num103) / 20);
                             white3.G = (byte)(255 * (10 - num103) / 20);
                             white3.B = (byte)(255 * (10 - num103) / 20);
                             white3.A = 0;
                             Microsoft.Xna.Framework.Rectangle frame4 = rCurrentNPC.frame;
                             int num104 = (num102 - 3 - num103) % 3;
                             if (num104 < 0)
{
                                 num104 += 3;
                             }
                             num104 += 5;
                             frame4.Y = num101 * num104;
                             mySpriteBatch.Draw(TextureAssets.GlowMask[154].Value, new Vector2(rCurrentNPC.oldPos[num103].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num103].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), frame4, white3, rCurrentNPC.oldRot[num103], halfSize, MathHelper.Lerp(0.75f, 1.2f, (10f - (float)num103) / 10f), spriteEffects, 0f);
                         }
                     }
                     if (type == 418 && (rCurrentNPC.ai[0] == 2f || rCurrentNPC.ai[0] == 4f))
                     {
                         Texture2D value45 = TextureAssets.Extra[55].Value;
                         Vector2 origin18 = new Vector2(value45.Width / 2, value45.Height / 8 + 14);
                         int num105 = (int)rCurrentNPC.ai[1] / 2;
                         float num106 = -(float)Math.PI / 2f * (float)rCurrentNPC.spriteDirection;
                         float num107 = rCurrentNPC.ai[1] / 45f;
                         if (num107 > 1f)
{
                             num107 = 1f;
                         }
                         num105 %= 4;
                         for (int num108 = 6; num108 >= 0; num108--)
{
                             _ = ref rCurrentNPC.oldPos[num108];
                             Microsoft.Xna.Framework.Color value46 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Gold, Microsoft.Xna.Framework.Color.OrangeRed, num107);
                             value46 = Microsoft.Xna.Framework.Color.Lerp(value46, Microsoft.Xna.Framework.Color.Blue, (float)num108 / 12f);
                             value46.A = (byte)(64f * num107);
                             value46.R = (byte)(value46.R * (10 - num108) / 20);
                             value46.G = (byte)(value46.G * (10 - num108) / 20);
                             value46.B = (byte)(value46.B * (10 - num108) / 20);
                             value46.A = (byte)(value46.A * (10 - num108) / 20);
                             value46 *= num107;
                             int num109 = (num105 - num108) % 4;
                             if (num109 < 0)
{
                                 num109 += 4;
                             }
                             Microsoft.Xna.Framework.Rectangle value47 = value45.Frame(1, 4, 0, num109);
                             mySpriteBatch.Draw(value45, new Vector2(rCurrentNPC.oldPos[num108].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num108].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), value47, value46, rCurrentNPC.oldRot[num108] + num106, origin18, MathHelper.Lerp(0.1f, 1.2f, (10f - (float)num108) / 10f), spriteEffects, 0f);
                         }
                     }
                     if (type == 516)
                     {
                         int num110 = TextureAssets.Npc[type].Height() / npcFrameCount[type];
                         int num111 = rCurrentNPC.frame.Y / num110;
                         for (int num112 = 6; num112 >= 0; num112--)
{
                             _ = ref rCurrentNPC.oldPos[num112];
                             Microsoft.Xna.Framework.Color white4 = Microsoft.Xna.Framework.Color.White;
                             white4.R = (byte)(255 * (10 - num112) / 20);
                             white4.G = (byte)(255 * (10 - num112) / 20);
                             white4.B = (byte)(255 * (10 - num112) / 20);
                             white4.A = (byte)(255 * (10 - num112) / 20);
                             white4 = Microsoft.Xna.Framework.Color.Lerp(white4, Microsoft.Xna.Framework.Color.Transparent, (float)num112 / 6f);
                             Microsoft.Xna.Framework.Rectangle frame5 = rCurrentNPC.frame;
                             int num113 = (num111 - 4 - num112) % 4;
                             if (num113 < 0)
{
                                 num113 += 4;
                             }
                             frame5.Y = num110 * num113;
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num112].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num112].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), frame5, white4, rCurrentNPC.rotation, halfSize, MathHelper.Lerp(0.35f, 1.2f, (10f - (float)num112) / 10f), spriteEffects, 0f);
                         }
                     }
                     if (rCurrentNPC.type == 390 && rCurrentNPC.IsABestiaryIconDummy)
                     {
                         LoadNPC(391);
                         Texture2D value48 = TextureAssets.Npc[391].Value;
                         Microsoft.Xna.Framework.Rectangle value49 = value48.Frame(1, npcFrameCount[391], 0, (int)rCurrentNPC.localAI[3]);
                         Vector2 vector46 = new Vector2(-rCurrentNPC.width - 8, 10f);
                         mySpriteBatch.Draw(value48, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY) + vector46, value49, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     Microsoft.Xna.Framework.Rectangle frame6 = rCurrentNPC.frame;
                     if (type == 182 || type == 289)
                     {
                         frame6.Height -= 2;
                     }
                     switch (type)
                     {
                     case 420:
                     case 421:
                     case 423:
                     case 424:
                     {
                         float num117 = 9f + 3f * (float)Math.Cos((float)Math.PI * 2f * GlobalTimeWrappedHourly);
                         Vector2 spinningpoint5 = Vector2.UnitX * num117;
                         Microsoft.Xna.Framework.Color color24 = Microsoft.Xna.Framework.Color.Teal * (num117 / 12f) * 0.8f;
                         color24.A /= 2;
                         for (float num118 = 0f; num118 < (float)Math.PI * 2f; num118 += (float)Math.PI / 2f)
{
                             Vector2 vector49 = rCurrentNPC.position + spinningpoint5.RotatedBy(num118);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(vector49.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, vector49.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, color24, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         break;
                     }
                     case 662:
                     {
                         float num114 = 4f + 2f * (float)Math.Cos((float)Math.PI * 2f * GlobalTimeWrappedHourly);
                         Vector2 spinningpoint4 = Vector2.UnitX * num114;
                         Microsoft.Xna.Framework.Color color23 = Microsoft.Xna.Framework.Color.Cyan * (num114 / 12f) * 0.4f;
                         color23.A /= 4;
                         for (float num115 = 0.9f; num115 >= 0f; num115 -= 0.125f)
{
                             Vector2 vector47 = rCurrentNPC.position - rCurrentNPC.velocity * 10f * num115;
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(vector47.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, vector47.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, color23 * (1f - num115), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         for (float num116 = 0f; num116 < (float)Math.PI * 2f; num116 += (float)Math.PI / 2f)
{
                             Vector2 vector48 = rCurrentNPC.position + spinningpoint4.RotatedBy(num116);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(vector48.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, vector48.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, color23, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         break;
                     }
                     }
                     if (rCurrentNPC.aiStyle == 7)
                     {
                         DrawNPCExtras(rCurrentNPC, beforeDraw: true, num36, num35, npcColor, halfSize, spriteEffects, screenPos);
                     }
                     if (type == 346 && (double)rCurrentNPC.life < (double)rCurrentNPC.lifeMax * 0.5)
                     {
                         mySpriteBatch.Draw(TextureAssets.SantaTank.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 356)
                     {
                         frame6.Height--;
                         mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 360)
                     {
                         float num119 = 0f;
                         if (rCurrentNPC.ai[2] == 0f)
{
                             if (rCurrentNPC.rotation == 3.14f || rCurrentNPC.rotation == -3.14f)
{
                                 num36 = 2f;
                             }
                             if (rCurrentNPC.direction < 0 && (rCurrentNPC.rotation == 1.57f || rCurrentNPC.rotation == 4.71f))
{
                                 num119 = 1f;
                             }
                             if (rCurrentNPC.direction > 0 && (rCurrentNPC.rotation == 1.57f || rCurrentNPC.rotation == 4.71f))
{
                                 num119 = -1f;
                             }
                         }
                         mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale + num119, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 655)
                     {
                         float num120 = 0f;
                         if (rCurrentNPC.ai[2] == 0f)
{
                             if (rCurrentNPC.rotation == 3.14f || rCurrentNPC.rotation == -3.14f)
{
                                 num36 = 2f;
                             }
                             if (rCurrentNPC.direction < 0 && (rCurrentNPC.rotation == 1.57f || rCurrentNPC.rotation == 4.71f))
{
                                 num120 = 1f;
                             }
                             if (rCurrentNPC.direction > 0 && (rCurrentNPC.rotation == 1.57f || rCurrentNPC.rotation == 4.71f))
{
                                 num120 = -1f;
                             }
                         }
                         mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale + num120, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.Orange), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 266 && rCurrentNPC.life < rCurrentNPC.lifeMax && (expertMode || getGoodWorld))
                     {
                         Microsoft.Xna.Framework.Color alpha11 = rCurrentNPC.GetAlpha(npcColor);
                         float num121 = 1f - (float)rCurrentNPC.life / (float)rCurrentNPC.lifeMax;
                         if (expertMode)
{
                             num121 *= 2f;
                         }
                         num121 *= num121;
                         if (getGoodWorld)
{
                             num121 = 1f;
                         }
                         num121 = MathHelper.Clamp(num121, 0f, 1f);
                         alpha11.R = (byte)((float)(int)alpha11.R * num121);
                         alpha11.G = (byte)((float)(int)alpha11.G * num121);
                         alpha11.B = (byte)((float)(int)alpha11.B * num121);
                         alpha11.A = (byte)((float)(int)alpha11.A * num121);
                         for (int num122 = 0; num122 < 4; num122++)
{
                             Vector2 position17 = rCurrentNPC.position;
                             float num123 = Math.Abs(rCurrentNPC.Center.X - Main.player[myPlayer].Center.X);
                             float num124 = Math.Abs(rCurrentNPC.Center.Y - Main.player[myPlayer].Center.Y);
                             if (num122 == 0 || num122 == 2)
{
                                 position17.X = Main.player[myPlayer].Center.X + num123;
                             }
                             else
{
                                 position17.X = Main.player[myPlayer].Center.X - num123;
                             }
                             position17.X -= rCurrentNPC.width / 2;
                             if (num122 == 0 || num122 == 1)
{
                                 position17.Y = Main.player[myPlayer].Center.Y + num124;
                             }
                             else
{
                                 position17.Y = Main.player[myPlayer].Center.Y - num124;
                             }
                             position17.Y -= rCurrentNPC.height / 2;
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(position17.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, position17.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, alpha11, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 421 && rCurrentNPC.ai[0] == 5f)
                     {
                         Player player = Main.player[rCurrentNPC.target];
                         if (player.gravDir == -1f)
{
                             spriteEffects |= SpriteEffects.FlipVertically;
                         }
                         mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(player.direction * 4, player.gfxOffY) + ((player.gravDir == 1f) ? player.Top : player.Bottom) - screenPos, frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, frame6.Size() / 2f, rCurrentNPC.scale, spriteEffects, 0f);
                         mySpriteBatch.Draw(TextureAssets.GlowMask[146].Value, new Vector2(player.direction * 4, player.gfxOffY) + ((player.gravDir == 1f) ? player.Top : player.Bottom) - screenPos, frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, frame6.Size() / 2f, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else
                     {
                         switch (type)
{
                         case 518:
{
                             Vector2 vector53 = new Vector2(-10f, 0f);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize + vector53, rCurrentNPC.scale, spriteEffects, 0f);
                             if (rCurrentNPC.color != default(Microsoft.Xna.Framework.Color))
{
                                 mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetColor(npcColor), rCurrentNPC.rotation, halfSize + vector53, rCurrentNPC.scale, spriteEffects, 0f);
                             }
                             break;
                         }
                         case 676:
                         case 681:
{
                             if (!rCurrentNPC.IsABestiaryIconDummy)
{
                                 mySpriteBatch.End();
                                 mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Transform);
                             }
                             DrawData value50 = new DrawData(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects);
                             GameShaders.Misc["RainbowTownSlime"].Apply(value50);
                             value50.Draw(mySpriteBatch);
                             pixelShader.CurrentTechnique.Passes[0].Apply();
                             if (!rCurrentNPC.IsABestiaryIconDummy)
{
                                 mySpriteBatch.End();
                                 mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
                             }
                             break;
                         }
                         case 685:
{
                             Vector2 scale4 = new Vector2(rCurrentNPC.scale);
                             float num131 = rCurrentNPC.rotation;
                             int num132 = 9;
                             Vector2 vector50 = rCurrentNPC.oldPos[num132];
                             if (vector50 != Vector2.Zero && rCurrentNPC.velocity.Y == 0f)
{
                                 Vector2 position18 = rCurrentNPC.position;
                                 Vector2 vector51 = vector50 - position18;
                                 float num133 = (float)Math.Sin(vector51.X / 30f * ((float)Math.PI * 2f));
                                 float num134 = (float)Math.Sin(vector51.Y / 30f * ((float)Math.PI * 2f));
                                 float num135 = Utils.Remap(vector51.Length(), 0f, 30f, 0f, 1f);
                                 scale4.X += num133 * num135 * 0.25f;
                                 scale4.Y += num134 * num135 * 0.25f;
                                 float num136 = (float)Math.Sin(Utils.Remap(vector51.Length(), 0f, 20f, 0f, 1f) * ((float)Math.PI * 2f));
                                 num131 += num136 * ((float)Math.PI / 4f) * 0.1f * (float)rCurrentNPC.spriteDirection;
                             }
                             Vector2 vector52 = new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - 2f - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY);
                             if (rCurrentNPC.velocity.Y == 0f)
{
                                 vector52 = vector52.Floor();
                                 int num137 = 2;
                                 float num138 = vector52.X % 16f;
                                 if (num138 < (float)num137)
{
                                     vector52.X -= num138;
                                 }
                                 if (num138 > (float)(16 - num137))
{
                                     vector52.X += 16f - num138;
                                 }
                             }
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, vector52, frame6, rCurrentNPC.GetAlpha(npcColor), num131, halfSize, scale4, spriteEffects, 0f);
                             break;
                         }
                         case 267:
{
                             Vector2 position19 = rCurrentNPC.Center + new Vector2(0f, num36 + num35 + rCurrentNPC.gfxOffY) - screenPos;
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, position19, frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             if (rCurrentNPC.color != default(Microsoft.Xna.Framework.Color))
{
                                 mySpriteBatch.Draw(TextureAssets.Npc[type].Value, position19, frame6, rCurrentNPC.GetColor(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             }
                             break;
                         }
                         default:
                             if (rCurrentNPC.aiStyle == 7 && rCurrentNPC.ai[0] == 25f)
{
                                 int num125 = type;
                                 float num126 = Utils.Remap(rCurrentNPC.ai[1], 0f, 60f, 0f, 1f);
                                 mySpriteBatch.End();
                                 mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Transform);
                                 DrawData drawData = new DrawData(TextureAssets.Npc[num125].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, Microsoft.Xna.Framework.Color.White * Utils.Remap(num126, 0f, 1f, 0f, 1f) * ((float)(int)rCurrentNPC.GetAlpha(npcColor).A / 255f), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects);
                                 drawData.shader = ContentSamples.CommonlyUsedContentSamples.ColorOnlyShaderIndex;
                                 GameShaders.Armor.Apply(ContentSamples.CommonlyUsedContentSamples.ColorOnlyShaderIndex, rCurrentNPC, drawData);
                                 float num127 = Utils.Remap(rCurrentNPC.ai[1], 45f, 90f, 0f, 1f);
                                 for (float num128 = 0f; num128 < 1f; num128 += 1f / 6f)
{
                                     DrawData drawData2 = drawData;
                                     drawData2.color = hslToRgb(num128, 0.9f, 0.65f) * num127 * 0.5f;
                                     drawData2.position += ((GlobalTimeWrappedHourly + num128) * ((float)Math.PI * 2f)).ToRotationVector2() * 4f * num127;
                                     drawData2.Draw(mySpriteBatch);
                                 }
                                 drawData.Draw(mySpriteBatch);
                                 pixelShader.CurrentTechnique.Passes[0].Apply();
                                 Microsoft.Xna.Framework.Color drawColor = new Microsoft.Xna.Framework.Color(255, 255, 255, 0);
                                 float num129 = (float)Math.Sin(timeForVisualEffects * 6.2831854820251465 / 20.0);
                                 DrawPrettyStarSparkle(num126, SpriteEffects.None, drawData.position, drawColor, hslToRgb(GlobalTimeWrappedHourly % 1f, 1f, 0.65f, 127), Utils.Remap(rCurrentNPC.ai[1], 30f, 60f, 0f, 30f), 0f, 30f, 30f, 36f, 0f, new Vector2(1.5f, 2.5f) * (1f + num129 * 0.025f), new Vector2(2f, 2f));
                                 DrawPrettyStarSparkle(num126, SpriteEffects.None, drawData.position, drawColor, hslToRgb(GlobalTimeWrappedHourly % 1f, 1f, 0.65f, 127), Utils.Remap(rCurrentNPC.ai[1], 30f, 60f, 0f, 30f), 0f, 30f, 30f, 36f, (float)Math.PI / 4f, new Vector2(2.5f, 2.5f) * (1f + num129 * 0.025f), new Vector2(1f, 1f));
                                 mySpriteBatch.End();
                                 mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
                             }
                             else
{
                                 int num130 = type;
                                 if (NPC.IsMechQueenUp && num130 == 134)
{
                                     num130 = 136;
                                     LoadNPC(num130);
                                 }
                                 mySpriteBatch.Draw(TextureAssets.Npc[num130].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 if (rCurrentNPC.color != default(Microsoft.Xna.Framework.Color))
{
                                     mySpriteBatch.Draw(TextureAssets.Npc[num130].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetColor(npcColor), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 }
                             }
                             break;
                         }
                     }
                     if (rCurrentNPC.confused)
                     {
                         mySpriteBatch.Draw(TextureAssets.Confuse.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 - (float)TextureAssets.Confuse.Height() - 20f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Confuse.Width(), TextureAssets.Confuse.Height()), rCurrentNPC.GetShimmerColor(new Microsoft.Xna.Framework.Color(250, 250, 250, 70)), rCurrentNPC.velocity.X * -0.05f, new Vector2(TextureAssets.Confuse.Width() / 2, TextureAssets.Confuse.Height() / 2), essScale + 0.2f, SpriteEffects.None, 0f);
                     }
                     if (type == 247 || type == 248)
                     {
                         Vector2 vector54 = new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY);
                         Texture2D value51 = TextureAssets.Npc[type].Value;
                         if (rCurrentNPC.ai[0] == 1f)
{
                             for (int num139 = 0; num139 < 3; num139++)
{
                                 int num140 = num139 * 5;
                                 int num141 = num140 + 15;
                                 float num142 = Utils.Remap(rCurrentNPC.ai[1], num140, num141, 0f, 1f);
                                 if (num142 != 0f)
{
                                     float num143 = Utils.Remap(num142, 0f, 1f, 2f, 1.1f + 0.1f * (float)num139);
                                     float num144 = num142;
                                     mySpriteBatch.Draw(color: new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * num144, texture: value51, position: vector54, sourceRectangle: frame6, rotation: rCurrentNPC.rotation, origin: halfSize, scale: rCurrentNPC.scale * num143, effects: spriteEffects, layerDepth: 0f);
                                 }
                             }
                         }
                         if (rCurrentNPC.ai[0] == 2f)
{
                             Microsoft.Xna.Framework.Color color26 = new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * Utils.Remap(rCurrentNPC.ai[1], 0f, 30f, 1f, 0f);
                             for (int num145 = 0; num145 < 3; num145++)
{
                                 float num146 = 1f;
                                 Vector2 position20 = vector54 + rCurrentNPC.velocity * num145 * -2f;
                                 float num147 = Utils.Remap(num145, 0f, 3f, 1f, 0f);
                                 mySpriteBatch.Draw(value51, position20, frame6, color26 * num147, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale * num146, spriteEffects, 0f);
                             }
                             for (int num148 = 0; num148 < 3; num148++)
{
                                 float num149 = 1.1f + 0.1f * (float)num148;
                                 mySpriteBatch.Draw(value51, vector54, frame6, color26, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale * num149, spriteEffects, 0f);
                             }
                         }
                     }
                     if (type >= 639 && type <= 645)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[286].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.White), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     if (type >= 646 && type <= 652)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[287].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, rCurrentNPC.GetAlpha(Microsoft.Xna.Framework.Color.White), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     if (type >= 134 && type <= 136 && npcColor != Microsoft.Xna.Framework.Color.Black)
                     {
                         mySpriteBatch.Draw(TextureAssets.Dest[type - 134].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * (1f - (float)rCurrentNPC.alpha / 255f), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 125)
                     {
                         mySpriteBatch.Draw(TextureAssets.EyeLaser.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 139)
                     {
                         mySpriteBatch.Draw(TextureAssets.Probe.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 127)
                     {
                         if (NPC.IsMechQueenUp)
{
                             rCurrentNPC.whoAmI = rCurrentNPC.whoAmI;
                             for (int num150 = 0; num150 < 200; num150++)
{
                                 if (!npc[num150].active || (npc[num150].type != 125 && npc[num150].type != 126))
{
                                     continue;
                                 }
                                 float scale5 = npc[num150].scale;
                                 float x = npc[num150].Center.X;
                                 float y2 = npc[num150].Center.Y;
                                 Vector2 mechQueenCenter = rCurrentNPC.GetMechQueenCenter();
                                 Vector2 vector55 = new Vector2((npc[num150].type == 125) ? (-18) : 20, -18f);
                                 vector55 = vector55.RotatedBy(rCurrentNPC.rotation);
                                 Vector2 vector56 = mechQueenCenter + vector55;
                                 float num151 = x - vector56.X;
                                 float num152 = y2 - vector56.Y;
                                 float rotation9 = (float)Math.Atan2(num152, num151) - 1.57f;
                                 bool flag11 = true;
                                 float num153 = (float)Math.Sqrt(num151 * num151 + num152 * num152);
                                 if (num153 > 2000f)
{
                                     flag11 = false;
                                 }
                                 float num154 = 40f * scale5;
                                 while (flag11)
{
                                     num153 = (float)Math.Sqrt(num151 * num151 + num152 * num152);
                                     if (num153 < num154)
{
                                         flag11 = false;
                                         continue;
                                     }
                                     num153 = (float)TextureAssets.Chain12.Height() * scale5 / num153;
                                     num151 *= num153;
                                     num152 *= num153;
                                     Microsoft.Xna.Framework.Color color27 = Lighting.GetColor((int)vector56.X / 16, (int)(vector56.Y / 16f));
                                     spriteBatch.Draw(TextureAssets.Chain12.Value, new Vector2(vector56.X - screenPosition.X, vector56.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain12.Width(), TextureAssets.Chain12.Height()), color27, rotation9, new Vector2((float)TextureAssets.Chain12.Width() * 0.5f, 0f), scale5, SpriteEffects.None, 0f);
                                     vector56.X += num151;
                                     vector56.Y += num152;
                                     num151 = x - vector56.X;
                                     num152 = y2 - vector56.Y;
                                 }
                             }
                         }
                         else
{
                             mySpriteBatch.Draw(TextureAssets.BoneEyes.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 131)
                     {
                         mySpriteBatch.Draw(TextureAssets.BoneLaser.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 120)
                     {
                         for (int num155 = 1; num155 < rCurrentNPC.oldPos.Length; num155++)
{
                             _ = ref rCurrentNPC.oldPos[num155];
                             Microsoft.Xna.Framework.Color newColor3 = default(Microsoft.Xna.Framework.Color);
                             newColor3.R = (byte)(150 * (10 - num155) / 15);
                             newColor3.G = (byte)(100 * (10 - num155) / 15);
                             newColor3.B = (byte)(150 * (10 - num155) / 15);
                             newColor3.A = (byte)(50 * (10 - num155) / 15);
                             newColor3 = rCurrentNPC.GetShimmerColor(newColor3);
                             mySpriteBatch.Draw(TextureAssets.Chaos.Value, new Vector2(rCurrentNPC.oldPos[num155].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num155].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, newColor3, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 137 || type == 138)
                     {
                         for (int num156 = 1; num156 < rCurrentNPC.oldPos.Length; num156++)
{
                             _ = ref rCurrentNPC.oldPos[num156];
                             Microsoft.Xna.Framework.Color newColor4 = default(Microsoft.Xna.Framework.Color);
                             newColor4.R = (byte)(150 * (10 - num156) / 15);
                             newColor4.G = (byte)(100 * (10 - num156) / 15);
                             newColor4.B = (byte)(150 * (10 - num156) / 15);
                             newColor4.A = (byte)(50 * (10 - num156) / 15);
                             newColor4 = rCurrentNPC.GetShimmerColor(newColor4);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num156].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num156].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, newColor4, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 327)
                     {
                         mySpriteBatch.Draw(TextureAssets.PumpkingFace.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         for (int num157 = 1; num157 < 10; num157++)
{
                             Microsoft.Xna.Framework.Color color28 = new Microsoft.Xna.Framework.Color(110 - num157 * 10, 110 - num157 * 10, 110 - num157 * 10, 110 - num157 * 10);
                             Vector2 vector57 = new Vector2((float)rand.Next(-10, 11) * 0.2f, (float)rand.Next(-10, 11) * 0.2f);
                             mySpriteBatch.Draw(TextureAssets.PumpkingFace.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36) + vector57, rCurrentNPC.frame, color28, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 325)
                     {
                         mySpriteBatch.Draw(TextureAssets.TreeFace.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         for (int num158 = 1; num158 < 10; num158++)
{
                             Microsoft.Xna.Framework.Color color29 = new Microsoft.Xna.Framework.Color(110 - num158 * 10, 110 - num158 * 10, 110 - num158 * 10, 110 - num158 * 10);
                             Vector2 vector58 = new Vector2((float)rand.Next(-10, 11) * 0.2f, (float)rand.Next(-10, 11) * 0.2f);
                             mySpriteBatch.Draw(TextureAssets.TreeFace.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36) + vector58, rCurrentNPC.frame, color29, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 345)
                     {
                         mySpriteBatch.Draw(TextureAssets.IceQueen.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         for (int num159 = 1; num159 < 5; num159++)
{
                             mySpriteBatch.Draw(color: new Microsoft.Xna.Framework.Color(100 - num159 * 10, 100 - num159 * 10, 100 - num159 * 10, 100 - num159 * 10), texture: TextureAssets.IceQueen.Value, position: new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36) - rCurrentNPC.velocity * num159 * 0.2f, sourceRectangle: rCurrentNPC.frame, rotation: rCurrentNPC.rotation, origin: halfSize, scale: rCurrentNPC.scale, effects: spriteEffects, layerDepth: 0f);
                         }
                     }
                     else if (type == 355)
                     {
                         mySpriteBatch.Draw(TextureAssets.Firefly.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 358)
                     {
                         mySpriteBatch.Draw(TextureAssets.Lightningbug.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 654)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[290].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 653)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[288].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 3f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 82)
                     {
                         mySpriteBatch.Draw(TextureAssets.WraithEye.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         for (int num160 = 1; num160 < 10; num160++)
{
                             mySpriteBatch.Draw(color: new Microsoft.Xna.Framework.Color(110 - num160 * 10, 110 - num160 * 10, 110 - num160 * 10, 110 - num160 * 10), texture: TextureAssets.WraithEye.Value, position: new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36) - rCurrentNPC.velocity * num160 * 0.5f, sourceRectangle: rCurrentNPC.frame, rotation: rCurrentNPC.rotation, origin: halfSize, scale: rCurrentNPC.scale, effects: spriteEffects, layerDepth: 0f);
                         }
                     }
                     else if (type == 253)
                     {
                         mySpriteBatch.Draw(TextureAssets.ReaperEye.Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 3f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, Microsoft.Xna.Framework.Color.White, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         for (int num161 = 1; num161 < 20; num161++)
{
                             mySpriteBatch.Draw(color: new Microsoft.Xna.Framework.Color(210 - num161 * 20, 210 - num161 * 20, 210 - num161 * 20, 210 - num161 * 20), texture: TextureAssets.ReaperEye.Value, position: new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 3f + halfSize.Y * rCurrentNPC.scale + num36) - rCurrentNPC.velocity * num161 * 0.5f, sourceRectangle: rCurrentNPC.frame, rotation: rCurrentNPC.rotation, origin: halfSize, scale: rCurrentNPC.scale, effects: spriteEffects, layerDepth: 0f);
                         }
                     }
                     else if (type == 245 && rCurrentNPC.alpha == 0 && !getGoodWorld)
                     {
                         mySpriteBatch.Draw(color: new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, 0), texture: TextureAssets.Golem[3].Value, position: new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), sourceRectangle: frame6, rotation: rCurrentNPC.rotation, origin: halfSize, scale: rCurrentNPC.scale, effects: spriteEffects, layerDepth: 0f);
                     }
                     else if (type == 246 && !getGoodWorld)
                     {
                         Microsoft.Xna.Framework.Color color34 = new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, 0);
                         if (rCurrentNPC.frame.Y < 222)
{
                             if (!getGoodWorld)
{
                                 mySpriteBatch.Draw(TextureAssets.Golem[1].Value, new Vector2(rCurrentNPC.Center.X - screenPos.X - 20f, rCurrentNPC.Center.Y - screenPos.Y - 27f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Golem[1].Width(), TextureAssets.Golem[1].Height() / 2), color34, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                             }
                             Microsoft.Xna.Framework.Rectangle value52 = frame6;
                             value52.Y = 0;
                             mySpriteBatch.Draw(TextureAssets.Extra[107].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), value52, color34, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                         else if (!getGoodWorld && rCurrentNPC.frame.Y < 444)
{
                             mySpriteBatch.Draw(TextureAssets.Golem[2].Value, new Vector2(rCurrentNPC.Center.X - screenPos.X + 26f, rCurrentNPC.Center.Y - screenPos.Y - 28f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Golem[2].Width(), TextureAssets.Golem[2].Height() / 4), color34, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                         }
                         else if (!getGoodWorld)
{
                             mySpriteBatch.Draw(TextureAssets.Golem[2].Value, new Vector2(rCurrentNPC.Center.X - screenPos.X - 38f, rCurrentNPC.Center.Y - screenPos.Y - 28f), new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.Golem[2].Height() / 2, TextureAssets.Golem[2].Width(), TextureAssets.Golem[2].Height() / 4), color34, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                         }
                     }
                     else if (type == 249 && !getGoodWorld)
                     {
                         Microsoft.Xna.Framework.Color color35 = new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, 0);
                         if (!getGoodWorld)
{
                             mySpriteBatch.Draw(TextureAssets.Golem[1].Value, new Vector2(rCurrentNPC.Center.X - screenPos.X - 20f, rCurrentNPC.Center.Y - screenPos.Y - 47f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Golem[1].Width(), TextureAssets.Golem[1].Height() / 2), color35, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                         }
                         int num162 = (int)rCurrentNPC.frameCounter / 4;
                         Texture2D value53 = TextureAssets.Extra[106].Value;
                         Microsoft.Xna.Framework.Rectangle value54 = value53.Frame(1, 8);
                         _ = Microsoft.Xna.Framework.Color.White;
                         value54.Y += value54.Height * 2 * num162 + frame6.Y;
                         mySpriteBatch.Draw(value53, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), value54, color35, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         value53 = TextureAssets.Extra[107].Value;
                         value54 = frame6;
                         mySpriteBatch.Draw(value53, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), value54, color35, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 383)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[11].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         if (rCurrentNPC.ai[2] != 0f && npc[(int)rCurrentNPC.ai[2] - 1].active && npc[(int)rCurrentNPC.ai[2] - 1].type == 384)
{
                             _ = rCurrentNPC.ai[2];
                             mySpriteBatch.Draw(TextureAssets.Npc[384].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), null, new Microsoft.Xna.Framework.Color(100, 100, 100, 0), rCurrentNPC.rotation, new Vector2(TextureAssets.Npc[384].Width(), TextureAssets.Npc[384].Height()) / 2f, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 381)
                     {
                         Vector2 zero3 = Vector2.Zero;
                         Vector2 origin19 = Vector2.Zero;
                         int num163 = TextureAssets.Npc[type].Height() / npcFrameCount[type];
                         int num164 = rCurrentNPC.frame.Y / num163;
                         Microsoft.Xna.Framework.Rectangle value55 = new Microsoft.Xna.Framework.Rectangle(0, 0, 32, 42);
                         switch (num164)
{
                         case 0:
                             zero3 += new Vector2(8f, 32f);
                             break;
                         case 1:
                             zero3 += new Vector2(6f, 72f);
                             break;
                         case 2:
                             zero3 += new Vector2(8f, 126f);
                             break;
                         case 3:
                             zero3 += new Vector2(6f, 174f);
                             break;
                         case 4:
                             zero3 += new Vector2(6f, 224f);
                             break;
                         case 5:
                             zero3 += new Vector2(8f, 272f);
                             break;
                         case 6:
                             zero3 += new Vector2(10f, 318f);
                             break;
                         case 7:
                             zero3 += new Vector2(14f, 366f);
                             break;
                         case 8:
                             zero3 += new Vector2(10f, 414f);
                             break;
                         }
                         zero3.Y -= num163 * num164;
                         zero3 -= halfSize;
                         int num165 = 2;
                         if (rCurrentNPC.ai[2] > 0f)
{
                             num165 = (int)rCurrentNPC.ai[2] - 1;
                         }
                         if (rCurrentNPC.velocity.Y != 0f)
{
                             num165 = 3;
                         }
                         value55.Y += 44 * num165;
                         switch (num165)
{
                         case 0:
                             origin19 = new Vector2(10f, 18f);
                             break;
                         case 1:
                             origin19 = new Vector2(8f, 20f);
                             break;
                         case 2:
                             origin19 = new Vector2(8f, 20f);
                             break;
                         case 3:
                             origin19 = new Vector2(8f, 20f);
                             break;
                         case 4:
                             origin19 = new Vector2(6f, 18f);
                             break;
                         }
                         if (spriteEffects.HasFlag(SpriteEffects.FlipHorizontally))
{
                             zero3.X *= -1f;
                             origin19.X = (float)value55.Width - origin19.X;
                         }
                         zero3 += rCurrentNPC.Center;
                         zero3 -= screenPos;
                         zero3.Y += rCurrentNPC.gfxOffY;
                         mySpriteBatch.Draw(TextureAssets.Extra[0].Value, zero3, value55, npcColor, rCurrentNPC.rotation, origin19, rCurrentNPC.scale, spriteEffects, 0f);
                         mySpriteBatch.Draw(TextureAssets.GlowMask[24].Value, zero3, value55, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, origin19, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 382)
                     {
                         Vector2 zero4 = Vector2.Zero;
                         Vector2 origin20 = Vector2.Zero;
                         int num166 = TextureAssets.Npc[type].Height() / npcFrameCount[type];
                         int num167 = rCurrentNPC.frame.Y / num166;
                         Microsoft.Xna.Framework.Rectangle value56 = new Microsoft.Xna.Framework.Rectangle(0, 0, 30, 42);
                         switch (num167)
{
                         case 0:
                             zero4 += new Vector2(8f, 30f);
                             break;
                         case 1:
                             zero4 += new Vector2(6f, 68f);
                             break;
                         case 2:
                             zero4 += new Vector2(8f, 120f);
                             break;
                         case 3:
                             zero4 += new Vector2(6f, 166f);
                             break;
                         case 4:
                             zero4 += new Vector2(6f, 214f);
                             break;
                         case 5:
                             zero4 += new Vector2(8f, 260f);
                             break;
                         case 6:
                             zero4 += new Vector2(14f, 304f);
                             break;
                         case 7:
                             zero4 += new Vector2(14f, 350f);
                             break;
                         case 8:
                             zero4 += new Vector2(10f, 396f);
                             break;
                         }
                         zero4.Y -= num166 * num167;
                         zero4 -= halfSize;
                         int num168 = 2;
                         if (rCurrentNPC.ai[2] > 0f)
{
                             num168 = (int)rCurrentNPC.ai[2] - 1;
                         }
                         if (rCurrentNPC.velocity.Y != 0f)
{
                             num168 = 3;
                         }
                         value56.Y += 44 * num168;
                         switch (num168)
{
                         case 0:
                             origin20 = new Vector2(10f, 18f);
                             break;
                         case 1:
                             origin20 = new Vector2(8f, 20f);
                             break;
                         case 2:
                             origin20 = new Vector2(8f, 20f);
                             break;
                         case 3:
                             origin20 = new Vector2(8f, 20f);
                             break;
                         case 4:
                             origin20 = new Vector2(6f, 18f);
                             break;
                         }
                         if (spriteEffects.HasFlag(SpriteEffects.FlipHorizontally))
{
                             zero4.X *= -1f;
                             origin20.X = (float)value56.Width - origin20.X;
                         }
                         zero4 += rCurrentNPC.Center;
                         zero4 -= screenPos;
                         zero4.Y += rCurrentNPC.gfxOffY;
                         mySpriteBatch.Draw(TextureAssets.Extra[1].Value, zero4, value56, npcColor, rCurrentNPC.rotation, origin20, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 520)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[164].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         Vector2 zero5 = Vector2.Zero;
                         Vector2 origin21 = new Vector2(4f, 4f);
                         int num169 = TextureAssets.Npc[type].Height() / npcFrameCount[type];
                         _ = rCurrentNPC.frame.Y / num169;
                         if (spriteEffects.HasFlag(SpriteEffects.FlipHorizontally))
{
                             zero5.X *= -1f;
                             origin21.X = (float)TextureAssets.Extra[56].Width() - origin21.X;
                         }
                         zero5 += rCurrentNPC.Top + new Vector2(0f, 20f);
                         zero5 -= screenPos;
                         zero5.Y += rCurrentNPC.gfxOffY;
                         float num170 = rCurrentNPC.localAI[3];
                         if (spriteEffects.HasFlag(SpriteEffects.FlipHorizontally))
{
                             num170 += (float)Math.PI;
                         }
                         mySpriteBatch.Draw(TextureAssets.Extra[56].Value, zero5, null, npcColor, num170, origin21, rCurrentNPC.scale, spriteEffects, 0f);
                         mySpriteBatch.Draw(TextureAssets.GlowMask[165].Value, zero5, null, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), num170, origin21, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 386)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[31].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 387)
                     {
                         Microsoft.Xna.Framework.Color color36 = new Microsoft.Xna.Framework.Color(1f, 1f, 1f, 1f) * 0.75f;
                         if (rCurrentNPC.ai[0] > 0f)
{
                             float amount7 = (rCurrentNPC.ai[0] + 1f) / 60f;
                             color36 = Microsoft.Xna.Framework.Color.Lerp(color36, Microsoft.Xna.Framework.Color.White, amount7);
                             color36.A = (byte)MathHelper.Lerp((int)color36.A, 0f, amount7);
                         }
                         color36 *= (255f - (float)rCurrentNPC.alpha) / 255f;
                         mySpriteBatch.Draw(TextureAssets.GlowMask[32].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, color36, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 388)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[33].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 389)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[34].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 4 && rCurrentNPC.ai[1] >= 4f && rCurrentNPC.ai[0] == 3f)
                     {
                         for (int num171 = 1; num171 < rCurrentNPC.oldPos.Length; num171++)
{
                             _ = ref rCurrentNPC.oldPos[num171];
                             Microsoft.Xna.Framework.Color color37 = npcColor;
                             color37.R = (byte)(0.5 * (double)(int)color37.R * (double)(10 - num171) / 20.0);
                             color37.G = (byte)(0.5 * (double)(int)color37.G * (double)(10 - num171) / 20.0);
                             color37.B = (byte)(0.5 * (double)(int)color37.B * (double)(10 - num171) / 20.0);
                             color37.A = (byte)(0.5 * (double)(int)color37.A * (double)(10 - num171) / 20.0);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num171].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num171].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, color37, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 437)
                     {
                         Microsoft.Xna.Framework.Color white5 = Microsoft.Xna.Framework.Color.White;
                         white5.A = 200;
                         mySpriteBatch.Draw(TextureAssets.GlowMask[109].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), frame6, white5, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         mySpriteBatch.Draw(TextureAssets.GlowMask[108].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + num35 + rCurrentNPC.gfxOffY), null, white5, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (type == 471 && rCurrentNPC.ai[3] < 0f)
                     {
                         for (int num172 = 1; num172 < rCurrentNPC.oldPos.Length; num172++)
{
                             _ = ref rCurrentNPC.oldPos[num172];
                             Microsoft.Xna.Framework.Color color38 = npcColor;
                             color38.R = (byte)(0.5 * (double)(int)color38.R * (double)(10 - num172) / 20.0);
                             color38.G = (byte)(0.5 * (double)(int)color38.G * (double)(10 - num172) / 20.0);
                             color38.B = (byte)(0.5 * (double)(int)color38.B * (double)(10 - num172) / 20.0);
                             color38.A = (byte)(0.5 * (double)(int)color38.A * (double)(10 - num172) / 20.0);
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num172].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num172].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, color38, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 477 && rCurrentNPC.velocity.Length() > 9f)
                     {
                         for (int num173 = 1; num173 < rCurrentNPC.oldPos.Length; num173++)
{
                             _ = ref rCurrentNPC.oldPos[num173];
                             Microsoft.Xna.Framework.Color color39 = npcColor;
                             color39.R = (byte)(0.5 * (double)(int)color39.R * (double)(10 - num173) / 20.0);
                             color39.G = (byte)(0.5 * (double)(int)color39.G * (double)(10 - num173) / 20.0);
                             color39.B = (byte)(0.5 * (double)(int)color39.B * (double)(10 - num173) / 20.0);
                             color39.A = (byte)(0.5 * (double)(int)color39.A * (double)(10 - num173) / 20.0);
                             Microsoft.Xna.Framework.Rectangle frame7 = rCurrentNPC.frame;
                             int num174 = TextureAssets.Npc[type].Height() / npcFrameCount[type];
                             frame7.Y -= num174 * num173;
                             while (frame7.Y < 0)
{
                                 frame7.Y += num174 * npcFrameCount[type];
                             }
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num173].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num173].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), frame7, color39, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     if (type == 479 && (double)rCurrentNPC.velocity.Length() > 6.5)
                     {
                         for (int num175 = 1; num175 < rCurrentNPC.oldPos.Length; num175++)
{
                             _ = ref rCurrentNPC.oldPos[num175];
                             Microsoft.Xna.Framework.Color color40 = npcColor;
                             color40.R = (byte)(0.5 * (double)(int)color40.R * (double)(10 - num175) / 20.0);
                             color40.G = (byte)(0.5 * (double)(int)color40.G * (double)(10 - num175) / 20.0);
                             color40.B = (byte)(0.5 * (double)(int)color40.B * (double)(10 - num175) / 20.0);
                             color40.A = (byte)(0.5 * (double)(int)color40.A * (double)(10 - num175) / 20.0);
                             Microsoft.Xna.Framework.Rectangle frame8 = rCurrentNPC.frame;
                             int num176 = TextureAssets.Npc[type].Height() / npcFrameCount[type];
                             frame8.Y -= num176 * num175;
                             while (frame8.Y < 0)
{
                                 frame8.Y += num176 * npcFrameCount[type];
                             }
                             mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num175].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num175].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), frame8, color40, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                         }
                     }
                     else if (type == 472)
                     {
                         mySpriteBatch.Draw(TextureAssets.GlowMask[110].Value, new Vector2(rCurrentNPC.position.X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.position.Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                     }
                     else if (rCurrentNPC.aiStyle == 87)
                     {
                         if ((int)rCurrentNPC.ai[0] == 4 || rCurrentNPC.ai[0] == 5f || rCurrentNPC.ai[0] == 6f)
{
                             for (int num177 = 1; num177 < rCurrentNPC.oldPos.Length; num177++)
{
                                 _ = ref rCurrentNPC.oldPos[num177];
                                 Microsoft.Xna.Framework.Color newColor5 = npcColor;
                                 newColor5.R = (byte)(0.5 * (double)(int)newColor5.R * (double)(10 - num177) / 20.0);
                                 newColor5.G = (byte)(0.5 * (double)(int)newColor5.G * (double)(10 - num177) / 20.0);
                                 newColor5.B = (byte)(0.5 * (double)(int)newColor5.B * (double)(10 - num177) / 20.0);
                                 newColor5.A = (byte)(0.5 * (double)(int)newColor5.A * (double)(10 - num177) / 20.0);
                                 newColor5 = rCurrentNPC.GetShimmerColor(newColor5);
                                 mySpriteBatch.Draw(TextureAssets.Npc[type].Value, new Vector2(rCurrentNPC.oldPos[num177].X - screenPos.X + (float)(rCurrentNPC.width / 2) - (float)TextureAssets.Npc[type].Width() * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, rCurrentNPC.oldPos[num177].Y - screenPos.Y + (float)rCurrentNPC.height - (float)TextureAssets.Npc[type].Height() * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36), rCurrentNPC.frame, newColor5, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             }
                         }
                     }
                     else
                     {
                         switch (type)
{
                         case 50:
{
                             Texture2D value57 = TextureAssets.Extra[39].Value;
                             Vector2 center4 = rCurrentNPC.Center;
                             float num199 = 0f;
                             switch (rCurrentNPC.frame.Y / (TextureAssets.Npc[type].Height() / npcFrameCount[type]))
{
                             case 0:
                                 num199 = 2f;
                                 break;
                             case 1:
                                 num199 = -6f;
                                 break;
                             case 2:
                                 num199 = 2f;
                                 break;
                             case 3:
                                 num199 = 10f;
                                 break;
                             case 4:
                                 num199 = 2f;
                                 break;
                             case 5:
                                 num199 = 0f;
                                 break;
                             }
                             center4.Y += rCurrentNPC.gfxOffY - (70f - num199) * rCurrentNPC.scale;
                             mySpriteBatch.Draw(value57, center4 - screenPos, null, npcColor, 0f, value57.Size() / 2f, 1f, spriteEffects, 0f);
                             break;
                         }
                         case 411:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[136].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 409:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[138].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 410:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[137].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 407:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[139].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 405:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[141].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 406:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[142].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 424:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[144].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 423:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[145].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 421:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[146].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 420:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[147].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 425:
{
                             Vector2 vector60 = rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY);
                             mySpriteBatch.Draw(TextureAssets.GlowMask[150].Value, vector60, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             Vector2 drawpos = vector60 + new Vector2(27 * -rCurrentNPC.spriteDirection, 0f);
                             float num200 = rCurrentNPC.ai[3];
                             DrawPrettyStarSparkle(Utils.Remap(num200, 0f, 15f, 0f, 1f), SpriteEffects.None, drawpos, new Microsoft.Xna.Framework.Color(255, 255, 255, 0), Microsoft.Xna.Framework.Color.Green, num200, 0f, 30f, 30f, 36f, 0f, new Vector2(3f, 1.5f), new Vector2(2f, 2f));
                             break;
                         }
                         case 429:
                             mySpriteBatch.Draw(TextureAssets.GlowMask[151].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         case 418:
{
                             mySpriteBatch.Draw(TextureAssets.GlowMask[161].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             float num197 = 0.25f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 0.25f;
                             for (int num198 = 0; num198 < 4; num198++)
{
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[161].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((float)num198 * ((float)Math.PI / 2f)) * num197, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             }
                             break;
                         }
                         case 412:
                         case 413:
                         case 414:
{
                             Microsoft.Xna.Framework.Color color41 = new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 0);
                             int num194 = 157 + type - 412;
                             if (type == 414 && rCurrentNPC.localAI[2] != 0f)
{
                                 int num195 = (int)rCurrentNPC.localAI[2];
                                 if (rCurrentNPC.localAI[2] < 0f)
{
                                     num195 = 128 + (int)rCurrentNPC.localAI[2];
                                 }
                                 int num196 = 255 - num195;
                                 color41 = new Microsoft.Xna.Framework.Color(num196, num195, num195, num196);
                             }
                             mySpriteBatch.Draw(TextureAssets.GlowMask[num194].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, color41, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                             break;
                         }
                         default:
                             switch (type)
{
                             case 415:
{
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[155].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 float num178 = 0.5f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                 for (int num179 = 0; num179 < 4; num179++)
{
                                     mySpriteBatch.Draw(TextureAssets.GlowMask[155].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((float)num179 * ((float)Math.PI / 2f)) * num178, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 }
                                 break;
                             }
                             case 419:
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[154].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 if (rCurrentNPC.ai[2] >= -6f)
{
                                     float num182 = 0.5f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                     for (int num183 = 0; num183 < 4; num183++)
{
                                         mySpriteBatch.Draw(TextureAssets.GlowMask[154].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((float)num183 * ((float)Math.PI / 2f)) * num182, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                     }
                                 }
                                 else
{
                                     float num184 = 4f;
                                     for (int num185 = 0; num185 < 4; num185++)
{
                                         mySpriteBatch.Draw(TextureAssets.GlowMask[154].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + Vector2.UnitX.RotatedBy((float)num185 * ((float)Math.PI / 2f)) * num184, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                     }
                                 }
                                 break;
                             case 417:
{
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[160].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 float num192 = 0.25f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 0.25f;
                                 for (int num193 = 0; num193 < 4; num193++)
{
                                     mySpriteBatch.Draw(TextureAssets.GlowMask[160].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((float)num193 * ((float)Math.PI / 2f)) * num192, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 }
                                 break;
                             }
                             case 516:
{
                                 mySpriteBatch.Draw(TextureAssets.Npc[type].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 float num186 = 0.5f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                 for (int num187 = 0; num187 < 4; num187++)
{
                                     mySpriteBatch.Draw(TextureAssets.Npc[type].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((float)num187 * ((float)Math.PI / 2f)) * num186, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 }
                                 break;
                             }
                             case 518:
{
                                 Vector2 vector59 = new Vector2(-10f, 0f);
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[163].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha), rCurrentNPC.rotation, halfSize + vector59, rCurrentNPC.scale, spriteEffects, 0f);
                                 float num190 = 0.5f + (rCurrentNPC.GetAlpha(npcColor).ToVector3() - new Vector3(0.5f)).Length() * 0.5f;
                                 for (int num191 = 0; num191 < 4; num191++)
{
                                     mySpriteBatch.Draw(TextureAssets.GlowMask[163].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + rCurrentNPC.velocity.RotatedBy((float)num191 * ((float)Math.PI / 2f)) * num190, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize + vector59, rCurrentNPC.scale, spriteEffects, 0f);
                                 }
                                 break;
                             }
                             case 344:
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[253].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 100) * 0.5f, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             case 346:
{
                                 float num180 = 4f;
                                 for (int num181 = 0; num181 < 4; num181++)
{
                                     mySpriteBatch.Draw(TextureAssets.GlowMask[254].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + Vector2.UnitX.RotatedBy((float)num181 * ((float)Math.PI / 2f)) * num180, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 }
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[254].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 100), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             }
                             case 315:
{
                                 float num188 = 2f;
                                 for (int num189 = 0; num189 < 4; num189++)
{
                                     mySpriteBatch.Draw(TextureAssets.GlowMask[255].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY) + Vector2.UnitX.RotatedBy((float)num189 * ((float)Math.PI / 2f)) * num188, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(64, 64, 64, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 }
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[255].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 200), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             }
                             case 525:
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[169].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 100), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             case 526:
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[170].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 100), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             case 527:
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[171].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(200, 200, 200, 100), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             case 533:
                                 mySpriteBatch.Draw(TextureAssets.GlowMask[172].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 100), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             case 160:
{
                                 Texture2D texture2D2 = null;
                                 texture2D2 = ((rCurrentNPC.townNpcVariationIndex != 1) ? TextureAssets.GlowMask[166].Value : TextureAssets.GlowMask[352].Value);
                                 mySpriteBatch.Draw(texture2D2, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             }
                             case 209:
{
                                 Texture2D texture2D = null;
                                 texture2D = ((rCurrentNPC.townNpcVariationIndex != 1) ? TextureAssets.GlowMask[167].Value : ((rCurrentNPC.altTexture != 1) ? TextureAssets.GlowMask[350].Value : TextureAssets.GlowMask[351].Value));
                                 mySpriteBatch.Draw(texture2D, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                                 break;
                             }
                             }
                             break;
                         }
                     }
                     if (rCurrentNPC.aiStyle == 7)
                     {
                         DrawNPCExtras(rCurrentNPC, beforeDraw: false, num36, num35, npcColor, halfSize, spriteEffects, screenPos);
                     }
                     break;
                 }
                 case 488:
                     break;
                 }
                 break;
             }
             goto case 426;
         case 426:
         case 427:
         case 428:
         case 521:
         case 523:
         case 541:
         case 542:
         case 543:
         case 544:
         case 545:
         case 581:
         {
             Texture2D value76 = TextureAssets.Npc[type].Value;
             Microsoft.Xna.Framework.Color color46 = Microsoft.Xna.Framework.Color.White;
             float amount10 = 0f;
             float amount11 = 0f;
             int num270 = 0;
             int num271 = 0;
             int num272 = 1;
             int num273 = 15;
             int num274 = 0;
             float scale8 = rCurrentNPC.scale;
             float value77 = rCurrentNPC.scale;
             int num275 = 0;
             float num276 = 0f;
             float num277 = 0f;
             float num278 = 0f;
             Microsoft.Xna.Framework.Color color47 = npcColor;
             Vector2 origin23 = halfSize;
             switch (type)
             {
             case 558:
             case 559:
             case 560:
             case 574:
             case 575:
                 if (rCurrentNPC.ai[0] != 2f)
                 {
                     num270 = 0;
                     break;
                 }
                 num270 = 6;
                 num271 = 2;
                 num273 = num270 * 3;
                 num274 = 1;
                 break;
             case 566:
             case 567:
             case 578:
                 num270 = 0;
                 num36 = -2f;
                 break;
             case 552:
             case 553:
             case 554:
             case 555:
             case 556:
             case 557:
             case 561:
             case 562:
             case 563:
             case 568:
             case 569:
             case 570:
             case 571:
             case 572:
             case 573:
                 num270 = 0;
                 if (type == 561 || type == 562 || type == 563)
                 {
                     num36 = -8f;
                 }
                 if (type == 555 || type == 556 || type == 557)
                 {
                     num36 = -5f;
                 }
                 if (type == 572 || type == 573)
                 {
                     num36 = -4f;
                 }
                 if (type == 570 || type == 571)
                 {
                     spriteEffects ^= SpriteEffects.FlipHorizontally;
                     num36 = -2f;
                 }
                 if (type == 568 || type == 569)
                 {
                     spriteEffects ^= SpriteEffects.FlipHorizontally;
                     num36 = -3f;
                     num275 = 4;
                     num277 = 4f;
                     num276 = (float)Math.Cos(GlobalTimeWrappedHourly % 1.5f / 1.5f * ((float)Math.PI * 2f)) / 6f + 0.75f;
                     color46 = Microsoft.Xna.Framework.Color.HotPink;
                     color46.A = 127;
                     amount10 = 0.5f;
                 }
                 if (rCurrentNPC.localAI[3] < 60f)
                 {
                     float num291 = rCurrentNPC.localAI[3] / 60f;
                     num275 = 3;
                     num276 = 1f - num291 * num291;
                     num277 = 8f;
                     color46 = new Microsoft.Xna.Framework.Color(127, 0, 255, 0);
                     amount11 = 1f;
                     color47 = Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color47, num291 * num291);
                 }
                 break;
             case 541:
                 num275 = 4;
                 num277 = 6f;
                 num276 = (float)Math.Cos(GlobalTimeWrappedHourly % 2.4f / 2.4f * ((float)Math.PI * 2f)) / 2f + 0.5f;
                 color46 = Microsoft.Xna.Framework.Color.Gold;
                 amount10 = 0.5f;
                 break;
             case 661:
                 num275 = 6;
                 num277 = 6f;
                 num276 = (float)Math.Cos(GlobalTimeWrappedHourly % 2.4f / 2.4f * ((float)Math.PI * 2f)) / 2f + 0.5f;
                 num276 = MathHelper.Max(num276, Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[2], clamped: true));
                 amount10 = 0.5f;
                 break;
             case 426:
                 num275 = 4;
                 num277 = 4f;
                 num276 = (float)Math.Cos(GlobalTimeWrappedHourly % 1.2f / 1.2f * ((float)Math.PI * 2f)) / 2f + 0.5f;
                 color46 = Microsoft.Xna.Framework.Color.Turquoise;
                 amount10 = 0.5f;
                 num270 = 6;
                 num271 = 2;
                 num273 = num270;
                 break;
             case 427:
                 num270 = 8;
                 num271 = 2;
                 num273 = num270 * 3;
                 break;
             case 546:
                 num270 = 8;
                 num271 = 2;
                 num273 = num270 * 3;
                 break;
             case 542:
             case 543:
             case 544:
             case 545:
                 num270 = 6;
                 num271 = 3;
                 num273 = num270 * 2;
                 break;
             case 581:
                 num270 = 6;
                 num271 = 2;
                 num273 = num270 * 3;
                 break;
             case 521:
                 num270 = 10;
                 num271 = 2;
                 num273 = num270;
                 num274 = 1;
                 value77 = 0.3f;
                 break;
             case 523:
                 num275 = 3;
                 num277 = 10f * rCurrentNPC.scale;
                 amount10 = 0.5f;
                 amount11 = 0.8f;
                 color46 = Microsoft.Xna.Framework.Color.HotPink;
                 color46.A = 128;
                 num278 = rCurrentNPC.localAI[0];
                 num276 = rCurrentNPC.localAI[1];
                 break;
             case 620:
                 num36 = -9f;
                 origin23 = rCurrentNPC.frame.Size() * new Vector2(0.5f, 0.5f) + new Vector2(-4 * rCurrentNPC.spriteDirection, 0f);
                 num275 = 4;
                 num277 = 6f;
                 num276 = (float)Math.Cos(GlobalTimeWrappedHourly % 2.4f / 2.4f * ((float)Math.PI * 2f)) / 2f + 0.5f;
                 color46 = Microsoft.Xna.Framework.Color.Gold;
                 amount10 = 0.5f;
                 num270 = 6;
                 num271 = 2;
                 num273 = num270 * 3;
                 num274 = 1;
                 break;
             case 618:
             {
                 float num279 = 90f;
                 float num280 = 180f;
                 if (rCurrentNPC.ai[0] == 1f && rCurrentNPC.ai[1] < num279)
                 {
                     int num281 = 3;
                     float num282 = num279 / (float)num281;
                     float num283 = rCurrentNPC.ai[1] % num282 / num282;
                     num275 = 6;
                     num277 = 15f;
                     num276 = num283 * 0.8f + 0.2f;
                 }
                 if (rCurrentNPC.ai[0] == 3f && rCurrentNPC.ai[1] < num280)
                 {
                     int num284 = 1;
                     float num285 = num280 / (float)num284;
                     float num286 = rCurrentNPC.ai[1] % num285 / num285;
                     num275 = 4;
                     num277 = 25f;
                     num276 = num286;
                     Vector2 vector69 = rCurrentNPC.scale * new Vector2(1f, 0.5f + num286 * 0.75f);
                     Texture2D value78 = TextureAssets.Extra[59].Value;
                     Microsoft.Xna.Framework.Rectangle rectangle12 = value78.Frame();
                     Vector2 origin24 = rectangle12.Size() * new Vector2(0.5f, 0.5f);
                     for (int num287 = 0; num287 < num275; num287++)
                     {
                         Microsoft.Xna.Framework.Color white8 = Microsoft.Xna.Framework.Color.White;
                         white8 *= Utils.GetLerpValue(0f, 0.5f, num276) * Utils.GetLerpValue(1f, 0.5f, num276) * 0.25f;
                         white8.A = 0;
                         white8.G = 0;
                         white8.B = 0;
                         float num288 = (float)num287 / (float)num275 * ((float)Math.PI * 2f) + rCurrentNPC.rotation + num278;
                         Vector2 position30 = rCurrentNPC.Center + num288.ToRotationVector2() * num277 * num276 - screenPos;
                         position30 -= new Vector2(value76.Width, value76.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position30 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value78, position30, rectangle12, white8, num288, origin24, vector69 * 1.8f, spriteEffects, 0f);
                     }
                     for (int num289 = 0; num289 < num275; num289++)
                     {
                         Microsoft.Xna.Framework.Color white9 = Microsoft.Xna.Framework.Color.White;
                         white9 *= Utils.GetLerpValue(0f, 0.5f, num276) * Utils.GetLerpValue(1f, 0.5f, num276) * 0.25f;
                         white9.A = 0;
                         float num290 = (float)num289 / (float)num275 * ((float)Math.PI * 2f) + rCurrentNPC.rotation + num278;
                         Vector2 position31 = rCurrentNPC.Center + num290.ToRotationVector2() * num277 * num276 - screenPos;
                         position31 -= new Vector2(value76.Width, value76.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                         position31 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                         mySpriteBatch.Draw(value78, position31, rectangle12, white9, num290, origin24, vector69 * 1.5f, spriteEffects, 0f);
                     }
                 }
                 break;
             }
             }
             for (int num292 = num272; num292 < num270; num292 += num271)
             {
                 _ = ref rCurrentNPC.oldPos[num292];
                 Microsoft.Xna.Framework.Color value79 = color47;
                 value79 = Microsoft.Xna.Framework.Color.Lerp(value79, color46, amount10);
                 value79 = rCurrentNPC.GetAlpha(value79);
                 value79 *= (float)(num270 - num292) / (float)num273;
                 _ = rCurrentNPC.rotation;
                 if (num274 == 1)
                 {
                     _ = rCurrentNPC.oldRot[num292];
                 }
                 float scale9 = MathHelper.Lerp(scale8, value77, 1f - (float)(num270 - num292) / (float)num273);
                 Vector2 position32 = rCurrentNPC.oldPos[num292] + new Vector2(rCurrentNPC.width, rCurrentNPC.height) / 2f - screenPos;
                 position32 -= new Vector2(value76.Width, value76.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                 position32 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                 mySpriteBatch.Draw(value76, position32, rCurrentNPC.frame, value79, rCurrentNPC.rotation, halfSize, scale9, spriteEffects, 0f);
             }
             for (int num293 = 0; num293 < num275; num293++)
             {
                 Microsoft.Xna.Framework.Color value80 = npcColor;
                 value80 = Microsoft.Xna.Framework.Color.Lerp(value80, color46, amount10);
                 value80 = rCurrentNPC.GetAlpha(value80);
                 value80 = Microsoft.Xna.Framework.Color.Lerp(value80, color46, amount11);
                 value80 *= 1f - num276;
                 Vector2 position33 = rCurrentNPC.Center + ((float)num293 / (float)num275 * ((float)Math.PI * 2f) + rCurrentNPC.rotation + num278).ToRotationVector2() * num277 * num276 - screenPos;
                 position33 -= new Vector2(value76.Width, value76.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                 position33 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                 mySpriteBatch.Draw(value76, position33, rCurrentNPC.frame, value80, rCurrentNPC.rotation, origin23, rCurrentNPC.scale, spriteEffects, 0f);
             }
             Vector2 vector70 = rCurrentNPC.Center - screenPos;
             vector70 -= new Vector2(value76.Width, value76.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
             vector70 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
             mySpriteBatch.Draw(value76, vector70, rCurrentNPC.frame, rCurrentNPC.GetAlpha(color47), rCurrentNPC.rotation, origin23, rCurrentNPC.scale, spriteEffects, 0f);
             switch (type)
             {
             case 427:
                 mySpriteBatch.Draw(TextureAssets.GlowMask[152].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 255 - rCurrentNPC.alpha, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                 break;
             case 426:
                 mySpriteBatch.Draw(TextureAssets.GlowMask[153].Value, rCurrentNPC.Bottom - screenPos + new Vector2((float)(-TextureAssets.Npc[type].Width()) * rCurrentNPC.scale / 2f + halfSize.X * rCurrentNPC.scale, (float)(-TextureAssets.Npc[type].Height()) * rCurrentNPC.scale / (float)npcFrameCount[type] + 4f + halfSize.Y * rCurrentNPC.scale + num36 + rCurrentNPC.gfxOffY), rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 128 - rCurrentNPC.alpha / 2, 0), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                 break;
             }
             if (type == 541)
             {
                 Microsoft.Xna.Framework.Color color48 = new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 0).MultiplyRGBA(Microsoft.Xna.Framework.Color.Gold);
                 for (int num294 = 0; num294 < num275; num294++)
                 {
                     Microsoft.Xna.Framework.Color newColor6 = color48;
                     newColor6 = rCurrentNPC.GetAlpha(newColor6);
                     newColor6 *= 1f - num276;
                     Vector2 position34 = rCurrentNPC.Center + ((float)num294 / (float)num275 * ((float)Math.PI * 2f) + rCurrentNPC.rotation + num278).ToRotationVector2() * (4f * num276 + 2f) - screenPos;
                     position34 -= new Vector2(value76.Width, value76.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                     position34 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     mySpriteBatch.Draw(TextureAssets.GlowMask[216].Value, position34, rCurrentNPC.frame, newColor6, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                 }
                 mySpriteBatch.Draw(TextureAssets.GlowMask[216].Value, vector70, rCurrentNPC.frame, color48, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
             }
             if (type == 661)
             {
                 num278 = MathHelper.Lerp(0f, 3f, Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[2], clamped: true));
                 for (int num295 = 0; num295 < num275; num295++)
                 {
                     Microsoft.Xna.Framework.Color newColor7 = new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 0).MultiplyRGBA(hslToRgb((GlobalTimeWrappedHourly + (float)num295 / (float)num275) % 1f, 1f, 0.5f));
                     newColor7 = rCurrentNPC.GetAlpha(newColor7);
                     newColor7 *= 1f - num276 * 0.5f;
                     newColor7.A = 0;
                     float num296 = 2f + rCurrentNPC.ai[2];
                     Vector2 position35 = rCurrentNPC.Center + ((float)num295 / (float)num275 * ((float)Math.PI * 2f) + rCurrentNPC.rotation + num278).ToRotationVector2() * (num296 * num276 + 2f) - screenPos;
                     position35 -= new Vector2(value76.Width, value76.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                     position35 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     mySpriteBatch.Draw(value76, position35, rCurrentNPC.frame, newColor7, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                 }
                 mySpriteBatch.Draw(value76, vector70, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * 0.1f, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
             }
             if ((type == 568 || type == 569) && rCurrentNPC.localAI[3] >= 60f)
             {
                 Microsoft.Xna.Framework.Color color49 = new Microsoft.Xna.Framework.Color(127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 127 - rCurrentNPC.alpha, 0).MultiplyRGBA(color46);
                 for (int num297 = 0; num297 < num275; num297++)
                 {
                     Microsoft.Xna.Framework.Color newColor8 = color49;
                     newColor8 = rCurrentNPC.GetAlpha(newColor8);
                     newColor8 *= 1f - num276;
                     Vector2 position36 = rCurrentNPC.Center + ((float)num297 / (float)num275 * ((float)Math.PI * 2f) + rCurrentNPC.rotation + num278).ToRotationVector2() * (4f * num276 + 2f) - screenPos;
                     position36 -= new Vector2(value76.Width, value76.Height / npcFrameCount[type]) * rCurrentNPC.scale / 2f;
                     position36 += halfSize * rCurrentNPC.scale + new Vector2(0f, num35 + num36 + rCurrentNPC.gfxOffY);
                     mySpriteBatch.Draw(TextureAssets.GlowMask[224].Value, position36, rCurrentNPC.frame, newColor8, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                 }
                 mySpriteBatch.Draw(TextureAssets.GlowMask[224].Value, vector70, rCurrentNPC.frame, color49, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
                 float num298 = rCurrentNPC.localAI[0];
                 if (num298 > 0f)
                 {
                     byte a = (byte)((Math.Cos(num298 * ((float)Math.PI * 2f) / 60f) * 0.5 + 0.5) * 32.0 + 0.0);
                     Microsoft.Xna.Framework.Color color50 = new Microsoft.Xna.Framework.Color(180, 90, 255, a) * 0.75f;
                     float num299 = 1f;
                     if (num298 < 60f)
                     {
                         float lerpValue3 = Utils.GetLerpValue(0f, 60f, num298);
                         color50 *= lerpValue3;
                         num299 = MathHelper.Lerp(1f, 0.5f, 1f - lerpValue3 * lerpValue3);
                     }
                     Texture2D value81 = TextureAssets.Extra[89].Value;
                     Vector2 origin25 = value81.Size() / 2f;
                     Vector2 scale10 = new Vector2(num299);
                     float num300 = num298 * 0.0041887905f;
                     float num301 = (float)Math.PI / 2f;
                     scale10.Y *= 1f;
                     scale10.X *= 1f;
                     for (float num302 = 0f; num302 < 16f; num302 += 1f)
                     {
                         float num303 = num300 + (float)Math.PI * 2f * (num302 / 16f);
                         Vector2 position37 = rCurrentNPC.Center - screenPos + num303.ToRotationVector2() * 400f * num299;
                         mySpriteBatch.Draw(value81, position37, null, color50, num303 + (float)Math.PI / 2f + num301, origin25, scale10, SpriteEffects.None, 0f);
                     }
                 }
             }
             if (type == 546)
             {
                 mySpriteBatch.Draw(TextureAssets.Extra[76].Value, vector70, rCurrentNPC.frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 200), MathHelper.Clamp(rCurrentNPC.velocity.X * 0.1f, -(float)Math.PI / 8f, (float)Math.PI / 8f), halfSize, rCurrentNPC.scale, spriteEffects, 0f);
             }
             if ((type == 566 || type == 567) && rCurrentNPC.localAI[3] >= 115f)
             {
                 int frameY = (int)(GlobalTimeWrappedHourly % 0.5f / 0.5f * 4f);
                 Texture2D value82 = TextureAssets.Extra[80].Value;
                 Microsoft.Xna.Framework.Rectangle rectangle13 = value82.Frame(1, 4, 0, frameY);
                 Vector2 vector71 = new Vector2(rCurrentNPC.spriteDirection * 8, -26f) * rCurrentNPC.scale;
                 int num304 = rCurrentNPC.frame.Y / rCurrentNPC.frame.Height;
                 int num305 = 0;
                 switch (num304)
                 {
                 case 0:
                     num305 = 6;
                     break;
                 case 1:
                     num305 = 4;
                     break;
                 case 2:
                     num305 = 2;
                     break;
                 case 3:
                     num305 = 6;
                     break;
                 case 4:
                     num305 = 8;
                     break;
                 case 5:
                     num305 = 6;
                     break;
                 case 6:
                     num305 = 4;
                     break;
                 case 7:
                     num305 = 6;
                     break;
                 case 8:
                     num305 = 2;
                     break;
                 }
                 Microsoft.Xna.Framework.Color color51 = new Microsoft.Xna.Framework.Color(255, 255, 255, 130);
                 vector71.Y += num305;
                 mySpriteBatch.Draw(value82, vector70 + vector71 * rCurrentNPC.scale, rectangle13, color51, MathHelper.Clamp(rCurrentNPC.velocity.X * 0.1f, -(float)Math.PI / 8f, (float)Math.PI / 8f), rectangle13.Size() / 2f, rCurrentNPC.scale * 0.7f, spriteEffects ^ SpriteEffects.FlipHorizontally, 0f);
             }
             if (type == 618)
             {
                 mySpriteBatch.Draw(TextureAssets.Extra[129].Value, vector70, rCurrentNPC.frame, rCurrentNPC.GetAlpha(color47), rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, spriteEffects, 0f);
             }
             break;
         }
         }
     }
References Entity.active, NPC.ai, NPC.AI_113_WindyBalloon_GetSlaveNPC(), LockOnHelper.AimedTarget, NPC.aiStyle, NPC.alpha, NPC.altTexture, TextureAssets.AntLion, ArmorShaderDataSet.Apply(), GameShaders.Armor, Assets, TextureAssets.BoneArm, TextureAssets.BoneArm2, TextureAssets.BoneEyes, TextureAssets.BoneLaser, NPC.boss, Entity.Bottom, Lighting.Brightness(), buffColor(), Entity.Center, TextureAssets.Chain, TextureAssets.Chain10, TextureAssets.Chain11, TextureAssets.Chain12, TextureAssets.Chain14, TextureAssets.Chain21, TextureAssets.Chain24, TextureAssets.Chain25, TextureAssets.Chain4, TextureAssets.Chain5, TextureAssets.Chaos, DrawData.color, NPC.color, ContentSamples.CommonlyUsedContentSamples.ColorOnlyShaderIndex, TextureAssets.Confuse, NPC.confused, DefaultSamplerState, TextureAssets.Dest, Entity.direction, Entity.Distance(), NPC.dontTakeDamageFromHostiles, DrawData.Draw(), DrawElderEye(), DrawNPC_SlimeItem(), DrawNPCDirect_Deerclops(), DrawNPCDirect_Faeling(), DrawNPCDirect_HallowBoss(), DrawNPCDirect_QueenSlimeWings(), DrawNPCExtras(), DrawPrettyStarSparkle(), TextureAssets.DukeFishron, dust, essScale, expertMode, TextureAssets.Extra, TextureAssets.EyeLaser, TextureAssets.Firefly, NPC.frame, NPC.frameCounter, NPC.GetAlpha(), NPC.GetBestiaryEntryColor(), NPC.GetColor(), Lighting.GetColor(), getGoodWorld, GetItemDrawFrame(), Utils.GetLerpValue(), NPC.GetMechQueenCenter(), NPC.GetNPCColorTintedByBuffs(), NPC.GetShimmerColor(), NPC.gfxOffY, Player.gfxOffY, GlobalTimeWrappedHourly, TextureAssets.GlowMask, TextureAssets.Golem, NPC.golemBoss, Player.gravDir, Entity.height, hslToRgb(), TextureAssets.IceQueen, NPC.IsABestiaryIconDummy, Asset< T >.IsLoaded, NPC.IsMechQueenUp, NPC.life, NPC.lifeMax, TextureAssets.Lightningbug, LoadNPC(), LoadProjectile(), NPC.localAI, GameShaders.Misc, mouseTextColor, myPlayer, NPC.nameOver, Dust.NewDust(), UnifiedRandom.Next(), TextureAssets.Ninja, Dust.noGravity, TextureAssets.Npc, npc, NPCAddHeight(), npcFrameCount, OffsetsPlayerHeadgear, NPC.oldPos, NPC.oldRot, NPC.Opacity, pixelShader, player, DrawData.position, Entity.position, TextureAssets.Probe, TextureAssets.Projectile, TextureAssets.PumpkingArm, TextureAssets.PumpkingCloak, TextureAssets.PumpkingFace, rand, Rasterizer, NPC.realLife, TextureAssets.ReaperEye, Utils.Remap(), NPC.rotation, TextureAssets.SantaTank, NPC.scale, screenPosition, NPC.SetFrameSize(), DrawData.shader, NPC.ShieldStrengthTowerMax, NPC.ShieldStrengthTowerNebula, NPC.ShieldStrengthTowerSolar, NPC.ShieldStrengthTowerStardust, NPC.ShieldStrengthTowerVortex, Entity.Size, TextureAssets.SpikeBase, spriteBatch, NPC.spriteDirection, NPC.target, tileColor, timeForVisualEffects, Entity.Top, NPC.townNpcVariationIndex, Transform, TextureAssets.TreeFace, NPC.type, Asset< T >.Value, Utils.Vector2FromElipse(), Entity.velocity, Entity.wet, Entity.whoAmI, Entity.width, and TextureAssets.WraithEye.
Referenced by UnlockableNPCEntryIcon.Draw(), Segments.NPCSegment.Draw(), and DrawNPC().