Terraria: Main.DrawInterface_Resources_Buffs
DrawInterface_Resources_Buffs()
void Main.DrawInterface_Resources_Buffs () inline
     {
         recBigList = false;
         int num = -1;
         int num2 = 11;
         for (int i = 0; i < Player.maxBuffs; i++)
         {
             if (player[myPlayer].buffType[i] > 0)
             {
                 _ = player[myPlayer].buffType[i];
                 int x = 32 + i * 38;
                 int num3 = 76;
                 int num4 = i;
                 while (num4 >= num2)
                 {
                     num4 -= num2;
                     x = 32 + num4 * 38;
                     num3 += 50;
                 }
                 num = DrawBuffIcon(num, i, x, num3);
             }
             else
             {
                 buffAlpha[i] = 0.4f;
             }
         }
         if (num < 0)
         {
             return;
         }
         int num5 = player[myPlayer].buffType[num];
         if (num5 > 0)
         {
             string buffName = Lang.GetBuffName(num5);
             string buffTooltip = GetBuffTooltip(player[myPlayer], num5);
             if (num5 == 147)
             {
                 bannerMouseOver = true;
             }
             if (meleeBuff[num5])
             {
                 MouseTextHackZoom(buffName, -10, 0, buffTooltip);
             }
             else
             {
                 MouseTextHackZoom(buffName, buffTooltip);
             }
         }
     }
References bannerMouseOver, buffAlpha, Player.buffType, DrawBuffIcon(), Lang.GetBuffName(), GetBuffTooltip(), Player.maxBuffs, meleeBuff, MouseTextHackZoom(), myPlayer, player, and recBigList.
Referenced by GUIBarsDrawInner().