Terraria: Main.DrawMultisegmentPet
DrawMultisegmentPet()
void Main.DrawMultisegmentPet (Projectile proj) inline private
     {
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         Texture2D texture2D = null;
         if (proj.type == 887)
         {
             texture2D = TextureAssets.GlowMask[275].Value;
         }
         int num = 5;
         int num2 = 16;
         switch (proj.type)
         {
         case 883:
             num = 5;
             num2 = 16;
             break;
         case 887:
             num = 6;
             num2 = 16;
             break;
         case 893:
             num = 8;
             num2 = 20;
             break;
         }
         SpriteEffects effects = ((proj.spriteDirection != 1) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
         Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, projFrames[proj.type]);
         Vector2 origin = rectangle.Size() / 2f;
         Vector2 position = proj.Center - screenPosition;
         Microsoft.Xna.Framework.Color alpha = proj.GetAlpha(Lighting.GetColor(proj.Center.ToTileCoordinates()));
         Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White * ((float)(int)mouseTextColor / 255f);
         Vector2 vector = proj.Center;
         int num3 = 1;
         int num4 = projFrames[proj.type] - 1;
         for (int i = 1; i < num; i++)
         {
             int frameY = num3;
             if (i == num - 1)
             {
                 frameY = num4;
             }
             else if (proj.type == 893 && i != 2 && i != 5)
             {
                 frameY = 2;
             }
             Microsoft.Xna.Framework.Rectangle value2 = value.Frame(1, projFrames[proj.type], 0, frameY);
             Vector2 vector2 = proj.oldPos[i * 10] + proj.Size / 2f;
             float num5 = (vector - vector2).ToRotation();
             vector2 = vector - new Vector2(num2, 0f).RotatedBy(num5, Vector2.Zero);
             num5 = (vector - vector2).ToRotation() + (float)Math.PI / 2f;
             Vector2 position2 = vector2 - screenPosition;
             SpriteEffects effects2 = ((!(vector2.X < vector.X)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             vector = vector2;
             EntitySpriteDraw(value, position2, value2, proj.GetAlpha(Lighting.GetColor(vector2.ToTileCoordinates())), num5, origin, proj.scale, effects2);
             if (texture2D != null)
             {
                 EntitySpriteDraw(texture2D, position2, value2, proj.GetAlpha(color), num5, origin, proj.scale, effects2);
             }
         }
         EntitySpriteDraw(value, position, rectangle, alpha, proj.rotation, origin, proj.scale, effects);
         if (texture2D != null)
         {
             EntitySpriteDraw(texture2D, position, rectangle, color, proj.rotation, origin, proj.scale, effects);
         }
     }
References Entity.Center, EntitySpriteDraw(), Projectile.GetAlpha(), Lighting.GetColor(), TextureAssets.GlowMask, mouseTextColor, Projectile.oldPos, TextureAssets.Projectile, projFrames, Projectile.rotation, Projectile.scale, screenPosition, Entity.Size, Projectile.spriteDirection, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().