Terraria: Main.DrawSettingButton
DrawSettingButton()
static void Main.DrawSettingButton (ref bool mouseOver, ref float scale, int posX, int posY, string text, string textSizeMatcher, Action clickAction) inline static
     {
         Vector2 vector = FontAssets.MouseText.Value.MeasureString(textSizeMatcher);
         Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(text);
         Vector2 vector3 = FontAssets.DeathText.Value.MeasureString(text);
         float num = vector.X / vector2.X;
         if (mouseOver)
         {
             if ((double)scale < 0.96)
             {
                 scale += 0.02f;
             }
         }
         else if ((double)scale > 0.8)
         {
             scale -= 0.02f;
         }
         UILinkPointNavigator.SetPosition(308, new Vector2(posX, posY));
         for (int i = 0; i < 5; i++)
         {
             int num2 = 0;
             int num3 = 0;
             Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Black;
             if (i == 0)
             {
                 num2 = -2;
             }
             if (i == 1)
             {
                 num2 = 2;
             }
             if (i == 2)
             {
                 num3 = -2;
             }
             if (i == 3)
             {
                 num3 = 2;
             }
             if (i == 4)
             {
                 color = Microsoft.Xna.Framework.Color.White;
             }
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, text, new Vector2(posX + num2, posY + num3), color, 0f, new Vector2(vector3.X / 2f, vector3.Y / 2f), (scale - 0.2f) * num, SpriteEffects.None, 0f);
         }
         if ((float)mouseX > (float)posX - vector3.X / 2f && (float)mouseX < (float)posX + vector3.X / 2f && (float)mouseY > (float)posY - vector3.Y / 2f && (float)mouseY < (float)posY + vector3.Y / 2f - 10f && !LocalPlayer.mouseInterface)
         {
             if (!PlayerInput.IgnoreMouseInterface)
             {
                 if (!mouseOver)
                 {
                     SoundEngine.PlaySound(12);
                 }
                 mouseOver = true;
                 player[myPlayer].mouseInterface = true;
                 if (mouseLeftRelease && mouseLeft)
                 {
                     mouseOver = false;
                     scale = 0.8f;
                     clickAction();
                 }
             }
         }
         else
         {
             mouseOver = false;
         }
     }
References FontAssets.DeathText, DynamicSpriteFontExtensionMethods.DrawString(), PlayerInput.IgnoreMouseInterface, LocalPlayer, Player.mouseInterface, mouseLeft, mouseLeftRelease, FontAssets.MouseText, mouseX, mouseY, myPlayer, player, SoundEngine.PlaySound(), UILinkPointNavigator.SetPosition(), spriteBatch, and Asset< T >.Value.
Referenced by DrawInterface_29_SettingsButton().