Terraria: Main.DrawNPCDirect_HallowBoss
DrawNPCDirect_HallowBoss()
static void Main.DrawNPCDirect_HallowBoss (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Microsoft.Xna.Framework.Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
     {
         Texture2D value = TextureAssets.Npc[typeCache].Value;
         Vector2 vector = rCurrentNPC.Center - screenPos;
         bool flag = rCurrentNPC.AI_120_HallowBoss_IsInPhase2();
         int num = (int)rCurrentNPC.ai[0];
         Texture2D value2 = TextureAssets.Extra[159].Value;
         Microsoft.Xna.Framework.Rectangle rectangle = value2.Frame(1, 11, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 11);
         Microsoft.Xna.Framework.Color color = rCurrentNPC.GetAlpha(npcColor);
         Texture2D value3 = TextureAssets.Extra[158].Value;
         Texture2D value4 = TextureAssets.Extra[160].Value;
         Texture2D value5 = TextureAssets.Extra[157].Value;
         DrawNPCDirect_GetHallowBossArmFrame(rCurrentNPC, out var armFrame_Count, out var armFrameToUseLeft, out var armFrameToUseRight);
         Microsoft.Xna.Framework.Rectangle rectangle2 = value3.Frame(1, armFrame_Count, 0, armFrameToUseLeft);
         Microsoft.Xna.Framework.Rectangle rectangle3 = value4.Frame(1, armFrame_Count, 0, armFrameToUseRight);
         Vector2 origin = rectangle2.Size() / 2f;
         Vector2 origin2 = rectangle3.Size() / 2f;
         int num2 = 0;
         int num3 = 0;
         if (armFrameToUseLeft == 5)
         {
             num2 = 1;
         }
         if (armFrameToUseRight == 5)
         {
             num3 = 1;
         }
         float num4 = 1f;
         int num5 = 0;
         int num6 = 0;
         float num7 = 0f;
         float num8 = 0f;
         float num9 = 0f;
         if (num == 8 || num == 9)
         {
             num7 = Utils.GetLerpValue(0f, 30f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(90f, 30f, rCurrentNPC.ai[1], clamped: true);
             num8 = Utils.GetLerpValue(0f, 30f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(90f, 70f, rCurrentNPC.ai[1], clamped: true);
             num9 = Utils.GetLerpValue(0f, 15f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(45f, 30f, rCurrentNPC.ai[1], clamped: true);
             color = Microsoft.Xna.Framework.Color.Lerp(color, Microsoft.Xna.Framework.Color.White, num7);
             num4 *= 1f - num9;
             num5 = 4;
             num6 = 3;
         }
         if (num == 10)
         {
             num7 = Utils.GetLerpValue(30f, 90f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(165f, 90f, rCurrentNPC.ai[1], clamped: true);
             num8 = Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(180f, 120f, rCurrentNPC.ai[1], clamped: true);
             num9 = Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(180f, 120f, rCurrentNPC.ai[1], clamped: true);
             color = Microsoft.Xna.Framework.Color.Lerp(color, Microsoft.Xna.Framework.Color.White, num7);
             num4 *= 1f - num9;
             num6 = 4;
         }
         if (num6 + num5 > 0)
         {
             for (int i = -num6; i <= num6 + num5; i++)
             {
                 if (i == 0)
                 {
                     continue;
                 }
                 Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.White;
                 Vector2 position = vector;
                 if (num == 8 || num == 9)
                 {
                     float hue = ((float)i + 5f) / 10f;
                     float num10 = 200f;
                     float num11 = (float)timeForVisualEffects / 60f;
                     Vector3 vector2 = Vector3.Transform(matrix: Matrix.CreateRotationX((num11 - 0.3f + (float)i * 0.1f) * 0.7f * ((float)Math.PI * 2f)) * Matrix.CreateRotationY((num11 - 0.8f + (float)i * 0.3f) * 0.7f * ((float)Math.PI * 2f)) * Matrix.CreateRotationZ((num11 + (float)i * 0.5f) * 0.1f * ((float)Math.PI * 2f)), position: Vector3.Forward);
                     num10 += Utils.GetLerpValue(-1f, 1f, vector2.Z, clamped: true) * 150f;
                     Vector2 spinningpoint = new Vector2(vector2.X, vector2.Y) * num10 * num7;
                     float lerpValue = Utils.GetLerpValue(90f, 0f, rCurrentNPC.ai[1], clamped: true);
                     color2 = hslToRgb(hue, 1f, MathHelper.Lerp(0.5f, 1f, lerpValue)) * 0.8f * num8;
                     color2.A /= 3;
                     position += spinningpoint.RotatedBy(rCurrentNPC.ai[1] / 180f * ((float)Math.PI * 2f));
                 }
                 if (num == 10)
                 {
                     if (rCurrentNPC.ai[1] >= 90f)
                     {
                         float num12 = (float)timeForVisualEffects / 90f;
                         int num13 = i;
                         if (num13 < 0)
{
                             num13++;
                         }
                         Vector2 vector3 = (((float)num13 + 0.5f) * ((float)Math.PI / 4f) + (float)Math.PI * 2f * num12).ToRotationVector2();
                         position += vector3 * new Vector2(600f * num7, 150f * num7);
                     }
                     else
                     {
                         position += 200f * new Vector2(i, 0f) * num7;
                     }
                     color2 = Microsoft.Xna.Framework.Color.White * 0.8f * num8 * num4;
                     color2.A /= 3;
                 }
                 if (i > num6)
                 {
                     float lerpValue2 = Utils.GetLerpValue(30f, 70f, rCurrentNPC.ai[1], clamped: true);
                     if (lerpValue2 == 0f)
                     {
                         continue;
                     }
                     position = vector + rCurrentNPC.velocity * -3f * ((float)i - 4f) * lerpValue2;
                     color2 *= 1f - num9;
                 }
                 mySpriteBatch.Draw(value2, position, rectangle, color2, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
                 mySpriteBatch.Draw(value5, position, rectangle, color2, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
                 if (flag)
                 {
                     Texture2D value6 = TextureAssets.Extra[187].Value;
                     Microsoft.Xna.Framework.Rectangle value7 = value6.Frame(1, 8, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 8);
                     mySpriteBatch.Draw(value6, position, value7, color2, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                 }
                 mySpriteBatch.Draw(value, position, rCurrentNPC.frame, color2, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                 for (int j = 0; j < 2; j++)
                 {
                     if (j == num2)
                     {
                         mySpriteBatch.Draw(value3, position, rectangle2, color2, rCurrentNPC.rotation, origin, rCurrentNPC.scale, npcSpriteEffect, 0f);
                     }
                     if (j == num3)
                     {
                         mySpriteBatch.Draw(value4, position, rectangle3, color2, rCurrentNPC.rotation, origin2, rCurrentNPC.scale, npcSpriteEffect, 0f);
                     }
                 }
             }
         }
         color *= num4;
         mySpriteBatch.Draw(value2, vector, rectangle, color, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
         if (!rCurrentNPC.IsABestiaryIconDummy)
         {
             mySpriteBatch.End();
             mySpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Transform);
         }
         DrawData value8 = new DrawData(value5, vector, rectangle, color, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect);
         GameShaders.Misc["HallowBoss"].Apply(value8);
         value8.Draw(mySpriteBatch);
         pixelShader.CurrentTechnique.Passes[0].Apply();
         if (!rCurrentNPC.IsABestiaryIconDummy)
         {
             mySpriteBatch.End();
             mySpriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         }
         float num14 = (float)Math.Sin(GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 0.5f) * 0.5f + 0.5f;
         Microsoft.Xna.Framework.Color color3 = hslToRgb((num14 * 0.08f + 0.6f) % 1f, 1f, 0.5f);
         color3.A = 0;
         color3 *= 0.6f;
         if (NPC.ShouldEmpressBeEnraged())
         {
             color3 = OurFavoriteColor;
             color3.A = 0;
             color3 *= 0.3f;
         }
         color3 *= num4 * rCurrentNPC.Opacity;
         if (flag)
         {
             Texture2D value9 = TextureAssets.Extra[187].Value;
             Microsoft.Xna.Framework.Rectangle value10 = value9.Frame(1, 8, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 8);
             mySpriteBatch.Draw(value9, vector, value10, color, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
             for (float num15 = 0f; num15 < 1f; num15 += 0.25f)
             {
                 Vector2 vector4 = rCurrentNPC.rotation.ToRotationVector2().RotatedBy(num15 * ((float)Math.PI * 2f) + (float)Math.PI / 4f) * MathHelper.Lerp(2f, 8f, num14);
                 mySpriteBatch.Draw(value9, vector + vector4, value10, color3, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
             }
         }
         mySpriteBatch.Draw(value, vector, rCurrentNPC.frame, color, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
         if (flag)
         {
             Texture2D value11 = TextureAssets.Extra[188].Value;
             for (float num16 = 0f; num16 < 1f; num16 += 0.25f)
             {
                 Vector2 vector5 = rCurrentNPC.rotation.ToRotationVector2().RotatedBy(num16 * ((float)Math.PI * 2f) + (float)Math.PI / 4f) * MathHelper.Lerp(2f, 8f, num14);
                 mySpriteBatch.Draw(value11, vector + vector5, null, color3, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
             }
         }
         for (int k = 0; k < 2; k++)
         {
             if (k == num2)
             {
                 mySpriteBatch.Draw(value3, vector, rectangle2, color, rCurrentNPC.rotation, origin, rCurrentNPC.scale, npcSpriteEffect, 0f);
             }
             if (k == num3)
             {
                 mySpriteBatch.Draw(value4, vector, rectangle3, color, rCurrentNPC.rotation, origin2, rCurrentNPC.scale, npcSpriteEffect, 0f);
             }
         }
     }
References NPC.ai, NPC.AI_120_HallowBoss_IsInPhase2(), Entity.Center, DefaultSamplerState, DrawData.Draw(), DrawNPCDirect_GetHallowBossArmFrame(), TextureAssets.Extra, NPC.frame, NPC.GetAlpha(), Utils.GetLerpValue(), GlobalTimeWrappedHourly, hslToRgb(), NPC.IsABestiaryIconDummy, NPC.localAI, GameShaders.Misc, TextureAssets.Npc, NPC.Opacity, OurFavoriteColor, pixelShader, Rasterizer, NPC.rotation, NPC.scale, NPC.ShouldEmpressBeEnraged(), timeForVisualEffects, Transform, Asset< T >.Value, and Entity.velocity.
Referenced by DrawNPCDirect().