Terraria: Main.DamageVar
DamageVar()
static int Main.DamageVar (float dmg, float luck = 0f) inline static
     {
         float num = dmg * (1f + (float)rand.Next(-15, 16) * 0.01f);
         if (luck > 0f)
         {
             if (rand.NextFloat() < luck)
             {
                 float num2 = dmg * (1f + (float)rand.Next(-15, 16) * 0.01f);
                 if (num2 > num)
                 {
                     num = num2;
                 }
             }
         }
         else if (luck < 0f && rand.NextFloat() < 0f - luck)
         {
             float num3 = dmg * (1f + (float)rand.Next(-15, 16) * 0.01f);
             if (num3 < num)
             {
                 num = num3;
             }
         }
         return (int)Math.Round(num);
     }
References UnifiedRandom.Next(), and rand.
Referenced by Player.ApplyTouchDamage(), NPC.BeHurtByOtherNPC(), Projectile.BombsHurtPlayers(), Projectile.Damage(), Player.GetMinecartDamage(), Player.ItemCheck_MeleeHitPVP(), Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Player.ProcessHitAgainstNPC(), and Player.Update_NPCCollision().