Terraria: Main.BindSettingsTo
BindSettingsTo()
void Main.BindSettingsTo (Preferences preferences) inline private
     {
         waterfallManager.BindTo(preferences);
         MinimapFrameManagerInstance.BindTo(preferences);
         BigBossProgressBar.BindTo(preferences);
         ResourceSetsManager.BindTo(preferences);
         ChromaInitializer.BindTo(preferences);
         Terraria.Graphics.Effects.Filters.Scene.BindTo(preferences);
         if (SocialAPI.Cloud != null)
         {
             SocialAPI.Cloud.BindTo(preferences);
         }
         preferences.OnSave += SaveResourcePacks;
         preferences.OnLoad += LoadResourcePacks;
     }
References BigBossProgressBar, SelectionHolder< TCycleType >.BindTo(), BigProgressBarSystem.BindTo(), PlayerResourceSetsManager.BindTo(), ChromaInitializer.BindTo(), CloudSocialModule.BindTo(), WaterfallManager.BindTo(), SocialAPI.Cloud, LoadResourcePacks(), MinimapFrameManagerInstance, Preferences.OnLoad, Preferences.OnSave, ResourceSetsManager, SaveResourcePacks(), and waterfallManager.
Referenced by Initialize().