Terraria: Main.UpdateServer
UpdateServer()
static void Main.UpdateServer () inline static private
     {
         netPlayCounter++;
         if (netPlayCounter % 3600 == 0)
         {
             NetMessage.SendData(7);
             netPlayCounter = 0;
         }
         for (int i = 0; i < maxNetPlayers; i++)
         {
             if (player[i].active && Netplay.Clients[i].IsActive)
             {
                 Netplay.Clients[i].SpamUpdate();
             }
         }
         if (Math.IEEERemainder(netPlayCounter, 900.0) == 0.0)
         {
             bool flag = true;
             int num = lastItemUpdate;
             int num2 = 0;
             while (flag)
             {
                 num++;
                 if (num >= 400)
                 {
                     num = 0;
                 }
                 num2++;
                 if (!Main.item[num].active || Main.item[num].playerIndexTheItemIsReservedFor == 255)
                 {
                     NetMessage.SendData(21, -1, -1, null, num);
                 }
                 if (num2 >= maxItemUpdates || num == lastItemUpdate)
                 {
                     flag = false;
                 }
             }
             lastItemUpdate = num;
         }
         for (int j = 0; j < 400; j++)
         {
             Item item = Main.item[j];
             if (item.active && (item.playerIndexTheItemIsReservedFor == 255 || !player[item.playerIndexTheItemIsReservedFor].active))
             {
                 item.FindOwner(j);
             }
         }
         for (int k = 0; k < 255; k++)
         {
             if (Netplay.Clients[k].IsActive)
             {
                 Netplay.Clients[k].TimeOutTimer++;
                 if (Netplay.Clients[k].State == 0)
                 {
                     Netplay.Clients[k].TimeOutTimer += 3;
                 }
                 if (!stopTimeOuts && Netplay.Clients[k].TimeOutTimer > 7200)
                 {
                     Netplay.Clients[k].PendingTermination = true;
                     Netplay.Clients[k].PendingTerminationApproved = true;
                 }
             }
             if (player[k].active)
             {
                 RemoteClient.CheckSection(k, player[k].position);
             }
         }
     }
References Entity.active, RemoteClient.CheckSection(), Netplay.Clients, Item.FindOwner(), RemoteClient.IsActive, item, lastItemUpdate, maxItemUpdates, maxNetPlayers, netPlayCounter, RemoteClient.PendingTermination, RemoteClient.PendingTerminationApproved, player, Item.playerIndexTheItemIsReservedFor, NetMessage.SendData(), RemoteClient.SpamUpdate(), RemoteClient.State, stopTimeOuts, and RemoteClient.TimeOutTimer.
Referenced by DoUpdateInWorld().