Terraria: Main.HelpText
HelpText()
static void Main.HelpText () inline static private
     {
         bool flag = false;
         if (player[myPlayer].statLifeMax > 100)
         {
             flag = true;
         }
         bool flag2 = false;
         if (player[myPlayer].statManaMax > 20)
         {
             flag2 = true;
         }
         bool flag3 = true;
         bool flag4 = false;
         bool flag5 = false;
         bool flag6 = false;
         bool flag7 = false;
         bool flag8 = false;
         bool flag9 = false;
         bool flag10 = false;
         bool flag11 = false;
         bool flag12 = false;
         bool flag13 = false;
         for (int i = 0; i < 58; i++)
         {
             if (player[myPlayer].inventory[i].pick > 0 && player[myPlayer].inventory[i].Name != "Copper Pickaxe")
             {
                 flag3 = false;
             }
             if (player[myPlayer].inventory[i].axe > 0 && player[myPlayer].inventory[i].Name != "Copper Axe")
             {
                 flag3 = false;
             }
             if (player[myPlayer].inventory[i].hammer > 0)
             {
                 flag3 = false;
             }
             if (player[myPlayer].inventory[i].type == 11 || player[myPlayer].inventory[i].type == 12 || player[myPlayer].inventory[i].type == 13 || player[myPlayer].inventory[i].type == 14 || player[myPlayer].inventory[i].type == 699 || player[myPlayer].inventory[i].type == 700 || player[myPlayer].inventory[i].type == 701 || player[myPlayer].inventory[i].type == 702)
             {
                 flag4 = true;
             }
             if (player[myPlayer].inventory[i].type == 19 || player[myPlayer].inventory[i].type == 20 || player[myPlayer].inventory[i].type == 21 || player[myPlayer].inventory[i].type == 22 || player[myPlayer].inventory[i].type == 703 || player[myPlayer].inventory[i].type == 704 || player[myPlayer].inventory[i].type == 705 || player[myPlayer].inventory[i].type == 706)
             {
                 flag5 = true;
             }
             if (player[myPlayer].inventory[i].type == 75)
             {
                 flag6 = true;
             }
             if (player[myPlayer].inventory[i].type == 38)
             {
                 flag7 = true;
             }
             if (player[myPlayer].inventory[i].type == 68 || player[myPlayer].inventory[i].type == 70 || player[myPlayer].inventory[i].type == 1330 || player[myPlayer].inventory[i].type == 1331 || player[myPlayer].inventory[i].type == 67 || player[myPlayer].inventory[i].type == 2886)
             {
                 flag8 = true;
             }
             if (player[myPlayer].inventory[i].type == 84 || player[myPlayer].inventory[i].type == 1236 || player[myPlayer].inventory[i].type == 1237 || player[myPlayer].inventory[i].type == 1238 || player[myPlayer].inventory[i].type == 1239 || player[myPlayer].inventory[i].type == 1240 || player[myPlayer].inventory[i].type == 1241 || player[myPlayer].inventory[i].type == 939 || player[myPlayer].inventory[i].type == 1273 || player[myPlayer].inventory[i].type == 2585 || player[myPlayer].inventory[i].type == 2360 || player[myPlayer].inventory[i].type == 185 || player[myPlayer].inventory[i].type == 1800 || player[myPlayer].inventory[i].type == 1915)
             {
                 flag9 = true;
             }
             if (player[myPlayer].inventory[i].type == 3347)
             {
                 flag10 = true;
             }
             if (player[myPlayer].inventory[i].type == 174)
             {
                 flag11 = true;
             }
             if (player[myPlayer].inventory[i].type == 1141)
             {
                 flag12 = true;
             }
             if (player[myPlayer].inventory[i].type == 1533 || player[myPlayer].inventory[i].type == 1534 || player[myPlayer].inventory[i].type == 1535 || player[myPlayer].inventory[i].type == 1536 || player[myPlayer].inventory[i].type == 1537 || player[myPlayer].inventory[i].type == 4714)
             {
                 flag13 = true;
             }
         }
         bool flag14 = false;
         bool flag15 = false;
         bool flag16 = false;
         bool flag17 = false;
         bool flag18 = false;
         bool flag19 = false;
         bool flag20 = false;
         bool flag21 = false;
         bool flag22 = false;
         bool flag23 = false;
         bool flag24 = false;
         bool flag25 = false;
         bool flag26 = false;
         bool flag27 = false;
         bool flag28 = false;
         bool flag29 = false;
         bool flag30 = false;
         bool flag31 = false;
         bool flag32 = false;
         bool flag33 = false;
         bool flag34 = false;
         bool flag35 = false;
         bool flag36 = false;
         bool flag37 = false;
         bool flag38 = false;
         int num = 0;
         for (int j = 0; j < 200; j++)
         {
             if (npc[j].active)
             {
                 if (npc[j].townNPC && npc[j].type != 37)
                 {
                     num++;
                 }
                 if (npc[j].type == 17)
                 {
                     flag14 = true;
                 }
                 if (npc[j].type == 18)
                 {
                     flag15 = true;
                 }
                 if (npc[j].type == 19)
                 {
                     flag17 = true;
                 }
                 if (npc[j].type == 20)
                 {
                     flag16 = true;
                 }
                 if (npc[j].type == 54)
                 {
                     flag22 = true;
                 }
                 if (npc[j].type == 124)
                 {
                     flag19 = true;
                 }
                 if (npc[j].type == 38)
                 {
                     flag18 = true;
                 }
                 if (npc[j].type == 108)
                 {
                     flag20 = true;
                 }
                 if (npc[j].type == 107)
                 {
                     flag21 = true;
                 }
                 if (npc[j].type == 228)
                 {
                     flag23 = true;
                 }
                 if (npc[j].type == 178)
                 {
                     flag24 = true;
                 }
                 if (npc[j].type == 209)
                 {
                     flag25 = true;
                 }
                 if (npc[j].type == 353)
                 {
                     flag26 = true;
                 }
                 if (npc[j].type == 633)
                 {
                     flag38 = true;
                 }
                 if (npc[j].type == 369)
                 {
                     flag27 = true;
                 }
                 if (npc[j].type == 441)
                 {
                     flag28 = true;
                 }
                 if (npc[j].type == 229)
                 {
                     flag29 = true;
                 }
                 if (npc[j].type == 207)
                 {
                     flag30 = true;
                 }
                 if (npc[j].type == 160)
                 {
                     flag31 = true;
                 }
                 if (npc[j].type == 588)
                 {
                     flag32 = true;
                 }
                 if (npc[j].type == 227)
                 {
                     flag33 = true;
                 }
                 if (npc[j].type == 208)
                 {
                     flag34 = true;
                 }
                 if (npc[j].type == 550)
                 {
                     flag35 = true;
                 }
                 if (npc[j].type == 368)
                 {
                     flag36 = true;
                 }
                 if (npc[j].type == 453)
                 {
                     flag37 = true;
                 }
             }
         }
         object obj = Lang.CreateDialogSubstitutionObject();
         while (true)
         {
             helpText++;
             if (Language.Exists("GuideHelpText.Help_" + helpText))
             {
                 LocalizedText text = Language.GetText("GuideHelpText.Help_" + helpText);
                 if (text.CanFormatWith(obj))
                 {
                     npcChatText = text.FormatWith(obj);
                     return;
                 }
             }
             if (flag3)
             {
                 if (helpText == 1)
                 {
                     npcChatText = Lang.dialog(177);
                     return;
                 }
                 if (helpText == 2)
                 {
                     npcChatText = Lang.dialog(178);
                     return;
                 }
                 if (helpText == 3)
                 {
                     npcChatText = Lang.dialog(179);
                     return;
                 }
                 if (helpText == 4)
                 {
                     npcChatText = Lang.dialog(180);
                     return;
                 }
                 if (helpText == 5)
                 {
                     npcChatText = Lang.dialog(181);
                     return;
                 }
                 if (helpText == 6)
                 {
                     npcChatText = Lang.dialog(182);
                     return;
                 }
             }
             if (flag3 && !flag4 && !flag5 && helpText == 11)
             {
                 npcChatText = Lang.dialog(183);
                 return;
             }
             if (flag3 && flag4 && !flag5)
             {
                 if (helpText == 21)
                 {
                     npcChatText = Lang.dialog(184);
                     return;
                 }
                 if (helpText == 22)
                 {
                     npcChatText = Lang.dialog(185);
                     return;
                 }
             }
             if (flag3 && flag5)
             {
                 if (helpText == 31)
                 {
                     npcChatText = Lang.dialog(186);
                     return;
                 }
                 if (helpText == 32)
                 {
                     npcChatText = Lang.dialog(187);
                     return;
                 }
             }
             if (!flag && helpText == 41)
             {
                 npcChatText = Lang.dialog(188);
                 return;
             }
             if (!flag2 && helpText == 42)
             {
                 npcChatText = Lang.dialog(189);
                 return;
             }
             if (!flag2 && !flag6 && helpText == 43)
             {
                 npcChatText = Lang.dialog(190);
                 return;
             }
             if (!flag14 && !flag15)
             {
                 if (helpText == 51)
                 {
                     npcChatText = Lang.dialog(191);
                     return;
                 }
                 if (helpText == 52)
                 {
                     npcChatText = Lang.dialog(192);
                     return;
                 }
                 if (helpText == 53)
                 {
                     npcChatText = Lang.dialog(193);
                     return;
                 }
                 if (helpText == 54)
                 {
                     npcChatText = Lang.dialog(194);
                     return;
                 }
                 if (helpText == 55)
                 {
                     npcChatText = Language.GetTextValue("GuideHelpText.Help_1065");
                     return;
                 }
             }
             if (!flag14 && helpText == 61)
             {
                 npcChatText = Lang.dialog(195);
                 return;
             }
             if (!flag15 && helpText == 62)
             {
                 npcChatText = Lang.dialog(196);
                 return;
             }
             if (!flag17 && helpText == 63)
             {
                 npcChatText = Lang.dialog(197);
                 return;
             }
             if (!flag16 && helpText == 64)
             {
                 npcChatText = Lang.dialog(198);
                 return;
             }
             if (!flag19 && helpText == 65 && NPC.downedBoss3)
             {
                 npcChatText = Lang.dialog(199);
                 return;
             }
             if (!flag22 && helpText == 66 && NPC.downedBoss3)
             {
                 npcChatText = Lang.dialog(200);
                 return;
             }
             if (!flag18 && helpText == 67)
             {
                 npcChatText = Lang.dialog(201);
                 return;
             }
             if (!flag21 && NPC.downedBoss2 && helpText == 68)
             {
                 npcChatText = Lang.dialog(202);
                 return;
             }
             if (!flag20 && hardMode && helpText == 69)
             {
                 npcChatText = Lang.dialog(203);
                 return;
             }
             if (!flag23 && helpText == 70 && NPC.downedBoss2)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1100");
                 return;
             }
             if (!flag24 && helpText == 71 && hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1101");
                 return;
             }
             if (!flag25 && helpText == 72 && NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1102");
                 return;
             }
             if (!flag26 && helpText == 73)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1103");
                 return;
             }
             if (!flag27 && helpText == 74)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1104");
                 return;
             }
             if (!flag28 && helpText == 75 && hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1105");
                 return;
             }
             if (!flag29 && helpText == 76 && hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1106");
                 return;
             }
             if (!flag30 && helpText == 77)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1107");
                 return;
             }
             if (!flag31 && helpText == 78 && hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1108");
                 return;
             }
             if (!flag32 && helpText == 79)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1109");
                 return;
             }
             if (!flag33 && helpText == 80 && num >= 5)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1110");
                 return;
             }
             if (!flag34 && helpText == 81 && num >= 11)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1111");
                 return;
             }
             if (!flag35 && NPC.downedBoss2 && helpText == 82)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1112");
                 return;
             }
             if (!flag36 && helpText == 83 && flag14)
             {
                 npcChatText = Language.GetTextValueWith("GuideHelpTextSpecific.Help_1113", obj);
                 return;
             }
             if (!flag37 && helpText == 84 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1114");
                 return;
             }
             if (!flag38 && helpText == 85 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1115");
                 return;
             }
             if (flag7 && !WorldGen.crimson && helpText == 100)
             {
                 npcChatText = Lang.dialog(204);
                 return;
             }
             if (flag8 && helpText == 101)
             {
                 npcChatText = Lang.dialog(WorldGen.crimson ? 403 : 205);
                 return;
             }
             if ((flag7 || flag8) && helpText == 102)
             {
                 npcChatText = Lang.dialog(WorldGen.crimson ? 402 : 206);
                 return;
             }
             if (flag7 && WorldGen.crimson && helpText == 103)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1159");
                 return;
             }
             if (!flag9 && LocalPlayer.miscEquips[4].IsAir && helpText == 201 && !hardMode && !NPC.downedBoss3 && !NPC.downedBoss2)
             {
                 npcChatText = Lang.dialog(207);
                 return;
             }
             if (helpText == 202 && !hardMode && player[myPlayer].statLifeMax >= 140)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1120");
                 return;
             }
             if (helpText == 203 && hardMode && NPC.downedMechBossAny)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1121");
                 return;
             }
             if (helpText == 204 && !NPC.downedGoblins && player[myPlayer].statLifeMax >= 200 && WorldGen.shadowOrbSmashed)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1122");
                 return;
             }
             if (helpText == 205 && hardMode && !NPC.downedPirates && player[myPlayer].statLifeMax >= 200)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1123");
                 return;
             }
             if (helpText == 206 && hardMode && NPC.downedGolemBoss && !NPC.downedMartians)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1124");
                 return;
             }
             if (helpText == 207 && (NPC.downedBoss1 || NPC.downedBoss2 || NPC.downedBoss3))
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1125");
                 return;
             }
             if (helpText == 208 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1130");
                 return;
             }
             if (helpText == 209 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1131");
                 return;
             }
             if (helpText == 210 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1132");
                 return;
             }
             if (helpText == 211 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1133");
                 return;
             }
             if (helpText == 212 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1134");
                 return;
             }
             if (helpText == 213 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1135");
                 return;
             }
             if (helpText == 214 && !hardMode && (flag4 || flag5))
             {
                 npcChatText = Language.GetTextValueWith("GuideHelpTextSpecific.Help_1136", obj);
                 return;
             }
             if (helpText == 215 && LocalPlayer.anglerQuestsFinished < 1)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1137");
                 return;
             }
             if (helpText == 216 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1138");
                 return;
             }
             if (helpText == 1000 && !NPC.downedBoss1 && !NPC.downedBoss2)
             {
                 npcChatText = Lang.dialog(208);
                 return;
             }
             if (helpText == 1001 && !NPC.downedBoss1 && !NPC.downedBoss2)
             {
                 npcChatText = Lang.dialog(209);
                 return;
             }
             if (helpText == 1002 && !NPC.downedBoss2)
             {
                 if (WorldGen.crimson)
                 {
                     npcChatText = Lang.dialog(331);
                 }
                 else
                 {
                     npcChatText = Lang.dialog(210);
                 }
                 return;
             }
             if (helpText == 1050 && !NPC.downedBoss1 && player[myPlayer].statLifeMax < 200)
             {
                 npcChatText = Lang.dialog(211);
                 return;
             }
             if (helpText == 1051 && !NPC.downedBoss1 && player[myPlayer].statDefense <= 10)
             {
                 npcChatText = Lang.dialog(212);
                 return;
             }
             if (helpText == 1052 && !NPC.downedBoss1 && player[myPlayer].statLifeMax >= 200 && player[myPlayer].statDefense > 10)
             {
                 npcChatText = Lang.dialog(WorldGen.crimson ? 404 : 213);
                 return;
             }
             if (helpText == 1053 && NPC.downedBoss1 && !NPC.downedBoss2 && player[myPlayer].statLifeMax < 300)
             {
                 npcChatText = Lang.dialog(214);
                 return;
             }
             if (helpText == 1054 && NPC.downedBoss1 && !NPC.downedBoss2 && !WorldGen.crimson && player[myPlayer].statLifeMax >= 300)
             {
                 npcChatText = Lang.dialog(215);
                 return;
             }
             if (helpText == 1055 && NPC.downedBoss1 && !NPC.downedBoss2 && !WorldGen.crimson && player[myPlayer].statLifeMax >= 300)
             {
                 npcChatText = Lang.dialog(216);
                 return;
             }
             if (helpText == 1056 && NPC.downedBoss1 && NPC.downedBoss2 && !NPC.downedBoss3)
             {
                 npcChatText = Lang.dialog(217);
                 return;
             }
             if (helpText == 1057 && NPC.downedBoss1 && NPC.downedBoss2 && NPC.downedBoss3 && !hardMode && player[myPlayer].statLifeMax < 400)
             {
                 npcChatText = Lang.dialog(218);
                 return;
             }
             if (helpText == 1058 && NPC.downedBoss1 && NPC.downedBoss2 && NPC.downedBoss3 && !hardMode && player[myPlayer].statLifeMax >= 400)
             {
                 npcChatText = Lang.dialog(219);
                 return;
             }
             if (helpText == 1059 && NPC.downedBoss1 && NPC.downedBoss2 && NPC.downedBoss3 && !hardMode && player[myPlayer].statLifeMax >= 400)
             {
                 npcChatText = Lang.dialog(220);
                 return;
             }
             if (helpText == 1060 && NPC.downedBoss1 && NPC.downedBoss2 && NPC.downedBoss3 && !hardMode && player[myPlayer].statLifeMax >= 400)
             {
                 npcChatText = Lang.dialog(221);
                 return;
             }
             if (helpText == 1061 && hardMode && !NPC.downedPlantBoss)
             {
                 npcChatText = Lang.dialog(WorldGen.crimson ? 401 : 222);
                 return;
             }
             if (helpText == 1062 && hardMode && !NPC.downedPlantBoss)
             {
                 npcChatText = Lang.dialog(223);
                 return;
             }
             if (helpText == 1140 && NPC.downedBoss1 && !NPC.downedBoss2 && WorldGen.crimson && player[myPlayer].statLifeMax >= 300)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1140");
                 return;
             }
             if (helpText == 1141 && NPC.downedBoss1 && !NPC.downedBoss2 && WorldGen.crimson && player[myPlayer].statLifeMax >= 300)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1141");
                 return;
             }
             if (helpText == 1142 && NPC.downedBoss2 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1142");
                 return;
             }
             if (helpText == 1143 && NPC.downedBoss2 && !NPC.downedQueenBee && player[myPlayer].statLifeMax >= 300)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1143");
                 return;
             }
             if (helpText == 1144 && flag10)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1144");
                 return;
             }
             if (helpText == 1145 && flag11 && !hardMode)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1145");
                 return;
             }
             if (helpText == 1146 && hardMode && player[myPlayer].wingsLogic == 0 && !LocalPlayer.mount.Active && !NPC.downedPlantBoss)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1146");
                 return;
             }
             if (helpText == 1147 && hardMode && WorldGen.SavedOreTiers.Adamantite == 111 && !NPC.downedMechBossAny)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1147");
                 return;
             }
             if (helpText == 1148 && hardMode && WorldGen.SavedOreTiers.Adamantite == 223 && !NPC.downedMechBossAny)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1148");
                 return;
             }
             if (helpText == 1149 && hardMode && NPC.downedMechBossAny && player[myPlayer].statLifeMax < 500)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1149");
                 return;
             }
             if (helpText == 1150 && hardMode && NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3 && !NPC.downedPlantBoss)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1150");
                 return;
             }
             if (helpText == 1151 && hardMode && NPC.downedPlantBoss && !NPC.downedGolemBoss && flag12)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1151");
                 return;
             }
             if (helpText == 1152 && hardMode && NPC.downedPlantBoss && !NPC.downedGolemBoss && !flag12)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1152");
                 return;
             }
             if (helpText == 1153 && hardMode && flag13)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1153");
                 return;
             }
             if (helpText == 1154 && hardMode && !NPC.downedFishron)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1154");
                 return;
             }
             if (helpText == 1155 && hardMode && NPC.downedGolemBoss && !NPC.downedHalloweenTree && !NPC.downedHalloweenKing)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1155");
                 return;
             }
             if (helpText == 1156 && hardMode && NPC.downedGolemBoss && !NPC.downedChristmasIceQueen && !NPC.downedChristmasTree && !NPC.downedChristmasSantank)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1156");
                 return;
             }
             if (helpText == 1157 && hardMode && NPC.downedGolemBoss && NPC.AnyNPCs(437) && !NPC.downedMoonlord)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1157");
                 return;
             }
             if (helpText == 1158 && hardMode && NPC.LunarApocalypseIsUp && !NPC.downedMoonlord)
             {
                 npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1158");
                 return;
             }
             if (helpText == 1159 && NPC.downedBoss1 && NPC.downedBoss2 && !NPC.downedDeerclops)
             {
                 break;
             }
             if (helpText > 1200)
             {
                 helpText = 0;
             }
         }
         npcChatText = Language.GetTextValue("GuideHelpTextSpecific.Help_1160");
     }
References Mount.Active, WorldGen.SavedOreTiers.Adamantite, Player.anglerQuestsFinished, NPC.AnyNPCs(), LocalizedText.CanFormatWith(), Lang.CreateDialogSubstitutionObject(), WorldGen.crimson, Lang.dialog(), NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedChristmasIceQueen, NPC.downedChristmasSantank, NPC.downedChristmasTree, NPC.downedDeerclops, NPC.downedFishron, NPC.downedGoblins, NPC.downedGolemBoss, NPC.downedHalloweenKing, NPC.downedHalloweenTree, NPC.downedMartians, NPC.downedMechBoss1, NPC.downedMechBoss2, NPC.downedMechBoss3, NPC.downedMechBossAny, NPC.downedMoonlord, NPC.downedPirates, NPC.downedPlantBoss, NPC.downedQueenBee, Language.Exists(), LocalizedText.FormatWith(), Language.GetText(), Language.GetTextValue(), Language.GetTextValueWith(), hardMode, helpText, Item.IsAir, LocalPlayer, NPC.LunarApocalypseIsUp, Player.miscEquips, Player.mount, myPlayer, npc, npcChatText, player, WorldGen.shadowOrbSmashed, Player.statDefense, and Player.statLifeMax.
Referenced by GUIChatDrawInner().