Terraria: Main.UpdateAudio_DecideOnNewMusic
UpdateAudio_DecideOnNewMusic()
void Main.UpdateAudio_DecideOnNewMusic () inline private
     {
         bool flag = false;
         bool flag2 = false;
         bool flag3 = false;
         bool flag4 = false;
         bool flag5 = false;
         bool flag6 = false;
         bool flag7 = false;
         bool flag8 = false;
         bool flag9 = false;
         bool flag10 = false;
         bool flag11 = false;
         bool flag12 = false;
         bool flag13 = false;
         bool flag14 = false;
         bool flag15 = false;
         bool flag16 = false;
         bool flag17 = false;
         bool flag18 = LocalPlayer.townNPCs > 2f;
         bool flag19 = slimeRain;
         if (SceneMetrics.ShadowCandleCount > 0 || LocalPlayer.inventory[LocalPlayer.selectedItem].type == 5322)
         {
             flag18 = false;
         }
         float num = 0f;
         for (int i = 0; i < maxMusic; i++)
         {
             if (musicFade[i] > num)
             {
                 num = musicFade[i];
                 if (num == 1f)
                 {
                     lastMusicPlayed = i;
                 }
             }
         }
         if (lastMusicPlayed == 50)
         {
             musicNoCrossFade[51] = true;
         }
         if (!showSplash)
         {
             Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle((int)screenPosition.X, (int)screenPosition.Y, screenWidth, screenHeight);
             int num2 = 5000;
             for (int j = 0; j < 200; j++)
             {
                 if (!npc[j].active)
                 {
                     continue;
                 }
                 num2 = 5000;
                 int num3 = 0;
                 switch (npc[j].type)
                 {
                 case 13:
                 case 14:
                 case 15:
                 case 127:
                 case 128:
                 case 129:
                 case 130:
                 case 131:
                     num3 = 1;
                     break;
                 case 26:
                 case 27:
                 case 28:
                 case 29:
                 case 111:
                 case 471:
                     num3 = 11;
                     break;
                 case 113:
                 case 114:
                 case 125:
                 case 126:
                     num3 = 2;
                     break;
                 case 134:
                 case 135:
                 case 136:
                 case 143:
                 case 144:
                 case 145:
                 case 266:
                     num3 = 3;
                     break;
                 case 212:
                 case 213:
                 case 214:
                 case 215:
                 case 216:
                 case 491:
                     num3 = 8;
                     break;
                 case 245:
                     num3 = 4;
                     break;
                 case 222:
                     num3 = 5;
                     break;
                 case 262:
                 case 263:
                 case 264:
                     num3 = 6;
                     break;
                 case 381:
                 case 382:
                 case 383:
                 case 385:
                 case 386:
                 case 388:
                 case 389:
                 case 390:
                 case 391:
                 case 395:
                 case 520:
                     num3 = 9;
                     break;
                 case 398:
                     num3 = 7;
                     break;
                 case 422:
                 case 493:
                 case 507:
                 case 517:
                     num3 = 10;
                     break;
                 case 439:
                     num3 = 4;
                     break;
                 case 438:
                     if (npc[j].ai[1] == 1f)
                     {
                         num2 = 1600;
                         num3 = 4;
                     }
                     break;
                 case 657:
                     num3 = 13;
                     break;
                 case 636:
                     num3 = 14;
                     break;
                 case 370:
                     num3 = 15;
                     break;
                 case 668:
                     num3 = 16;
                     break;
                 }
                 if (NPCID.Sets.BelongsToInvasionOldOnesArmy[npc[j].type])
                 {
                     num3 = 12;
                 }
                 if (num3 == 0 && npc[j].boss)
                 {
                     num3 = 1;
                 }
                 if (remixWorld && getGoodWorld && (npc[j].type == 127 || npc[j].type == 134 || npc[j].type == 125 || npc[j].type == 126))
                 {
                     num3 = 17;
                 }
                 if (num3 == 0)
                 {
                     continue;
                 }
                 Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle((int)(npc[j].position.X + (float)(npc[j].width / 2)) - num2, (int)(npc[j].position.Y + (float)(npc[j].height / 2)) - num2, num2 * 2, num2 * 2);
                 if (rectangle.Intersects(value))
                 {
                     switch (num3)
                     {
                     case 1:
                         flag = true;
                         break;
                     case 2:
                         flag3 = true;
                         break;
                     case 3:
                         flag4 = true;
                         break;
                     case 4:
                         flag5 = true;
                         break;
                     case 5:
                         flag6 = true;
                         break;
                     case 6:
                         flag7 = true;
                         break;
                     case 7:
                         flag8 = true;
                         break;
                     case 8:
                         flag9 = true;
                         break;
                     case 9:
                         flag10 = true;
                         break;
                     case 10:
                         flag11 = true;
                         break;
                     case 11:
                         flag12 = true;
                         break;
                     case 12:
                         flag13 = true;
                         break;
                     case 13:
                         flag14 = true;
                         break;
                     case 14:
                         flag15 = true;
                         break;
                     case 15:
                         flag16 = true;
                         break;
                     case 16:
                         flag2 = true;
                         break;
                     case 17:
                         flag17 = true;
                         break;
                     }
                     break;
                 }
             }
         }
         _ = (screenPosition.X + (float)(screenWidth / 2)) / 16f;
         if (musicVolume == 0f)
         {
             newMusic = 0;
             return;
         }
         if (gameMenu)
         {
             if (netMode != 2)
             {
                 if (WorldGen.drunkWorldGen)
                 {
                     if (WorldGen.remixWorldGen)
                     {
                         newMusic = 70;
                     }
                     else
                     {
                         newMusic = 60;
                     }
                 }
                 else if (WorldGen.remixWorldGen)
                 {
                     newMusic = 8;
                 }
                 else if (menuMode == 3000)
                 {
                     newMusic = 89;
                 }
                 else if (WorldGen.tenthAnniversaryWorldGen)
                 {
                     newMusic = 11;
                 }
                 else if (playOldTile)
                 {
                     newMusic = 6;
                 }
                 else if (!_isAsyncLoadComplete)
                 {
                     newMusic = 50;
                 }
                 else if (!audioSystem.IsTrackPlaying(50))
                 {
                     newMusic = 51;
                     if (musicNoCrossFade[51])
                     {
                         musicFade[51] = 1f;
                     }
                 }
             }
             else
             {
                 newMusic = 0;
             }
             return;
         }
         float num4 = (float)maxTilesX / 4200f;
         num4 *= num4;
         float num5 = (float)((double)((screenPosition.Y + (float)(screenHeight / 2)) / 16f - (65f + 10f * num4)) / (worldSurface / 5.0));
         if (CreditsRollEvent.IsEventOngoing)
         {
             newMusic = 89;
         }
         else if (player[myPlayer].happyFunTorchTime)
         {
             newMusic = 13;
         }
         else if (flag8)
         {
             newMusic = 38;
         }
         else if (flag17)
         {
             newMusic = 81;
         }
         else if (flag10)
         {
             newMusic = 37;
         }
         else if (flag11)
         {
             newMusic = 34;
         }
         else if (flag7)
         {
             newMusic = 24;
         }
         else if (flag15)
         {
             newMusic = 57;
         }
         else if (flag16)
         {
             newMusic = 58;
         }
         else if (flag3)
         {
             newMusic = 12;
         }
         else if (flag)
         {
             newMusic = 5;
         }
         else if (flag4)
         {
             newMusic = 13;
         }
         else if (flag5)
         {
             newMusic = 17;
         }
         else if (flag6)
         {
             newMusic = 25;
         }
         else if (flag14)
         {
             newMusic = 56;
         }
         else if (flag2)
         {
             newMusic = 90;
         }
         else if (flag9)
         {
             newMusic = 35;
         }
         else if (flag12)
         {
             newMusic = 39;
         }
         else if (flag13)
         {
             newMusic = 41;
         }
         else if (eclipse && !remixWorld && (double)player[myPlayer].position.Y < worldSurface * 16.0 + (double)(screenHeight / 2))
         {
             newMusic = 27;
         }
         else if (eclipse && remixWorld && (double)player[myPlayer].position.Y > rockLayer * 16.0)
         {
             newMusic = 27;
         }
         else if (flag19 && !player[myPlayer].ZoneGraveyard && (!bloodMoon || dayTime) && (double)player[myPlayer].position.Y < worldSurface * 16.0 + (double)(screenHeight / 2))
         {
             newMusic = 48;
         }
         else if (remixWorld && bloodMoon && !player[myPlayer].ZoneCrimson && !player[myPlayer].ZoneCorrupt && (double)player[myPlayer].position.Y > rockLayer * 16.0 && player[myPlayer].position.Y <= (float)(UnderworldLayer * 16))
         {
             newMusic = 2;
         }
         else if (remixWorld && bloodMoon && player[myPlayer].position.Y > (float)(UnderworldLayer * 16) && (double)(player[myPlayer].Center.X / 16f) > (double)maxTilesX * 0.37 + 50.0 && (double)(player[myPlayer].Center.X / 16f) < (double)maxTilesX * 0.63)
         {
             newMusic = 2;
         }
         else if (player[myPlayer].ZoneShimmer)
         {
             newMusic = 91;
         }
         else if (flag18 && dayTime && ((cloudAlpha == 0f && !_shouldUseWindyDayMusic) || (double)player[myPlayer].position.Y >= worldSurface * 16.0 + (double)(screenHeight / 2)) && !player[myPlayer].ZoneGraveyard)
         {
             newMusic = 46;
         }
         else if (flag18 && !dayTime && ((!bloodMoon && cloudAlpha == 0f) || (double)player[myPlayer].position.Y >= worldSurface * 16.0 + (double)(screenHeight / 2)) && !player[myPlayer].ZoneGraveyard)
         {
             newMusic = 47;
         }
         else if (player[myPlayer].ZoneSandstorm)
         {
             newMusic = 40;
         }
         else if (player[myPlayer].position.Y > (float)(UnderworldLayer * 16))
         {
             newMusic = 36;
         }
         else if (num5 < 1f)
         {
             newMusic = (dayTime ? 42 : 15);
         }
         else if (tile[(int)(player[myPlayer].Center.X / 16f), (int)(player[myPlayer].Center.Y / 16f)].wall == 87)
         {
             newMusic = 26;
         }
         else if (player[myPlayer].ZoneDungeon)
         {
             newMusic = 23;
         }
         else if ((bgStyle == 9 && (double)player[myPlayer].position.Y < worldSurface * 16.0 + (double)(screenHeight / 2)) || undergroundBackground == 2)
         {
             newMusic = 29;
         }
         else if (player[myPlayer].ZoneCorrupt)
         {
             if (player[myPlayer].ZoneCrimson && SceneMetrics.BloodTileCount > SceneMetrics.EvilTileCount)
             {
                 if ((double)player[myPlayer].position.Y > worldSurface * 16.0 + (double)(screenHeight / 2))
                 {
                     newMusic = 33;
                 }
                 else
                 {
                     newMusic = 16;
                 }
             }
             else if ((double)player[myPlayer].position.Y > worldSurface * 16.0 + (double)(screenHeight / 2))
             {
                 newMusic = 10;
             }
             else
             {
                 newMusic = 8;
             }
         }
         else if (player[myPlayer].ZoneCrimson)
         {
             if ((double)player[myPlayer].position.Y > worldSurface * 16.0 + (double)(screenHeight / 2))
             {
                 newMusic = 33;
             }
             else
             {
                 newMusic = 16;
             }
         }
         else if (player[myPlayer].ZoneMeteor)
         {
             newMusic = 2;
         }
         else if (player[myPlayer].ZoneGraveyard)
         {
             newMusic = 53;
         }
         else if (player[myPlayer].ZoneJungle)
         {
             if (remixWorld)
             {
                 if ((double)player[myPlayer].position.Y > rockLayer * 16.0 + (double)(screenHeight / 2))
                 {
                     newMusic = 7;
                 }
                 else if (newMusic == 7 && (double)player[myPlayer].position.Y > (rockLayer - 50.0) * 16.0 + (double)(screenHeight / 2))
                 {
                     newMusic = 7;
                 }
                 else if ((double)player[myPlayer].position.Y < worldSurface * 16.0 + (double)(screenHeight / 2))
                 {
                     newMusic = (dayTime ? 42 : 15);
                 }
                 else
                 {
                     newMusic = 54;
                 }
             }
             else if ((double)player[myPlayer].position.Y > rockLayer * 16.0 + (double)(screenHeight / 2))
             {
                 newMusic = 54;
             }
             else if (newMusic == 54 && (double)player[myPlayer].position.Y > (rockLayer - 50.0) * 16.0 + (double)(screenHeight / 2))
             {
                 newMusic = 54;
             }
             else if (_shouldUseStormMusic && (double)player[myPlayer].position.Y < worldSurface * 16.0 + (double)(screenHeight / 2))
             {
                 newMusic = 52;
             }
             else if (dayTime)
             {
                 newMusic = 7;
             }
             else
             {
                 newMusic = 55;
             }
         }
         else if (player[myPlayer].ZoneSnow)
         {
             if ((double)player[myPlayer].position.Y > worldSurface * 16.0 + (double)(screenHeight / 2))
             {
                 if (remixWorld && (double)player[myPlayer].position.Y > rockLayer * 16.0 + (double)(screenHeight / 2))
                 {
                     newMusic = 14;
                 }
                 else
                 {
                     newMusic = 20;
                 }
             }
             else if (remixWorld)
             {
                 newMusic = (dayTime ? 42 : 15);
             }
             else
             {
                 newMusic = 14;
             }
         }
         else if ((double)player[myPlayer].position.Y >= worldSurface * 16.0 + (double)(screenHeight / 2) && (remixWorld || !WorldGen.oceanDepths((int)(screenPosition.X + (float)(screenWidth / 2)) / 16, (int)(screenPosition.Y + (float)(screenHeight / 2)) / 16)))
         {
             if (player[myPlayer].ZoneHallow)
             {
                 if (remixWorld && (double)player[myPlayer].position.Y >= rockLayer * 16.0 + (double)(screenHeight / 2))
                 {
                     newMusic = 9;
                 }
                 else
                 {
                     newMusic = 11;
                 }
             }
             else if (player[myPlayer].ZoneUndergroundDesert)
             {
                 if ((double)player[myPlayer].position.Y >= worldSurface * 16.0 + (double)(screenHeight / 2))
                 {
                     newMusic = 61;
                 }
                 else
                 {
                     newMusic = 21;
                 }
             }
             else
             {
                 if (ugMusic == 0)
                 {
                     ugMusic = 4;
                 }
                 if (!audioSystem.IsTrackPlaying(4) && !audioSystem.IsTrackPlaying(31))
                 {
                     if (musicFade[4] == 1f)
                     {
                         musicFade[31] = 1f;
                     }
                     if (musicFade[31] == 1f)
                     {
                         musicFade[4] = 1f;
                     }
                     switch (rand.Next(2))
                     {
                     case 0:
                         ugMusic = 4;
                         musicFade[31] = 0f;
                         break;
                     case 1:
                         ugMusic = 31;
                         musicFade[4] = 0f;
                         break;
                     }
                 }
                 newMusic = ugMusic;
                 if (remixWorld && (double)(player[myPlayer].position.Y / 16f) > rockLayer && player[myPlayer].position.Y / 16f < (float)(maxTilesY - 350))
                 {
                     if (cloudAlpha > 0f)
                     {
                         newMusic = 19;
                     }
                     else if (player[myPlayer].ZoneDesert)
                     {
                         newMusic = 21;
                     }
                     else if (_shouldUseWindyDayMusic)
                     {
                         newMusic = 44;
                     }
                 }
             }
         }
         else if (dayTime && player[myPlayer].ZoneHallow)
         {
             if (_shouldUseStormMusic)
             {
                 newMusic = 52;
             }
             else if (cloudAlpha > 0f && !gameMenu)
             {
                 newMusic = 19;
             }
             else if (_shouldUseWindyDayMusic && !remixWorld)
             {
                 newMusic = 44;
             }
             else
             {
                 newMusic = 9;
             }
         }
         else if (_shouldUseStormMusic)
         {
             if (bloodMoon)
             {
                 newMusic = 2;
             }
             else
             {
                 newMusic = 52;
             }
         }
         else if (WorldGen.oceanDepths((int)(screenPosition.X + (float)(screenWidth / 2)) / 16, (int)(screenPosition.Y + (float)(screenHeight / 2)) / 16))
         {
             if (bloodMoon)
             {
                 newMusic = 2;
             }
             else if (flag18)
             {
                 if (dayTime)
                 {
                     newMusic = 46;
                 }
                 else
                 {
                     newMusic = 47;
                 }
             }
             else
             {
                 newMusic = (dayTime ? 22 : 43);
             }
         }
         else if (player[myPlayer].ZoneDesert)
         {
             if ((double)player[myPlayer].position.Y >= worldSurface * 16.0)
             {
                 int num6 = (int)(player[myPlayer].Center.X / 16f);
                 int num7 = (int)(player[myPlayer].Center.Y / 16f);
                 if (WorldGen.InWorld(num6, num7) && (WallID.Sets.Conversion.Sandstone[tile[num6, num7].wall] || WallID.Sets.Conversion.HardenedSand[tile[num6, num7].wall]))
                 {
                     newMusic = 61;
                 }
                 else
                 {
                     newMusic = 21;
                 }
             }
             else
             {
                 newMusic = 21;
             }
         }
         else if (remixWorld)
         {
             newMusic = (dayTime ? 42 : 15);
         }
         else if (dayTime)
         {
             if (cloudAlpha > 0f && !gameMenu)
             {
                 if (time < 10800.0)
                 {
                     newMusic = 59;
                 }
                 else
                 {
                     newMusic = 19;
                 }
             }
             else
             {
                 if (dayMusic == 0)
                 {
                     dayMusic = 1;
                 }
                 if (!audioSystem.IsTrackPlaying(1) && !audioSystem.IsTrackPlaying(18))
                 {
                     if (rand.Next(2) == 0)
                     {
                         dayMusic = 1;
                     }
                     else
                     {
                         dayMusic = 18;
                     }
                 }
                 newMusic = dayMusic;
                 if (_shouldUseWindyDayMusic && !remixWorld)
                 {
                     newMusic = 44;
                 }
             }
         }
         else if (!dayTime)
         {
             if (bloodMoon)
             {
                 newMusic = 2;
             }
             else if (cloudAlpha > 0f && !gameMenu)
             {
                 newMusic = 19;
             }
             else
             {
                 newMusic = 3;
             }
         }
         if (((double)(screenPosition.Y / 16f) < worldSurface + 10.0 || remixWorld) && pumpkinMoon)
         {
             newMusic = 30;
         }
         if (((double)(screenPosition.Y / 16f) < worldSurface + 10.0 || remixWorld) && snowMoon)
         {
             newMusic = 32;
         }
     }
References _isAsyncLoadComplete, _shouldUseStormMusic, _shouldUseWindyDayMusic, audioSystem, NPCID.Sets.BelongsToInvasionOldOnesArmy, bgStyle, bloodMoon, SceneMetrics.BloodTileCount, Entity.Center, cloudAlpha, dayMusic, dayTime, WorldGen.drunkWorldGen, eclipse, SceneMetrics.EvilTileCount, gameMenu, getGoodWorld, WallID.Sets.Conversion.HardenedSand, Entity.height, Player.inventory, WorldGen.InWorld(), CreditsRollEvent.IsEventOngoing, IAudioSystem.IsTrackPlaying(), lastMusicPlayed, LocalPlayer, maxMusic, maxTilesX, maxTilesY, menuMode, musicFade, musicNoCrossFade, musicVolume, myPlayer, netMode, newMusic, UnifiedRandom.Next(), npc, WorldGen.oceanDepths(), player, playOldTile, Entity.position, pumpkinMoon, rand, remixWorld, WorldGen.remixWorldGen, rockLayer, WallID.Sets.Conversion.Sandstone, screenHeight, screenPosition, screenWidth, Player.selectedItem, SceneMetrics.ShadowCandleCount, showSplash, slimeRain, snowMoon, WorldGen.tenthAnniversaryWorldGen, tile, time, Player.townNPCs, Item.type, NPC.type, ugMusic, undergroundBackground, UnderworldLayer, Tile.wall, Entity.width, worldSurface, and Player.ZoneGraveyard.
Referenced by UpdateAudio().