Terraria: Main.DrawInterface_40_InteractItemIcon
DrawInterface_40_InteractItemIcon()
void Main.DrawInterface_40_InteractItemIcon () inline private
     {
         if (HoveringOverAnNPC || LocalPlayer.mouseInterface)
         {
             return;
         }
         Item item = player[myPlayer].inventory[player[myPlayer].selectedItem];
         int num = item.type;
         if (player[myPlayer].UsingBiomeTorches)
         {
             switch (num)
             {
             case 8:
                 num = player[myPlayer].BiomeTorchHoldStyle(num);
                 break;
             case 966:
                 num = player[myPlayer].BiomeCampfireHoldStyle(num);
                 break;
             }
         }
         if (player[myPlayer].cursorItemIconID != 0)
         {
             num = player[myPlayer].cursorItemIconID;
         }
         bool flag = player[myPlayer].cursorItemIconEnabled && (player[myPlayer].inventory[player[myPlayer].selectedItem].type > 0 || player[myPlayer].cursorItemIconID != 0);
         ItemIconCacheVerification();
         bool flag2 = _itemIconCacheTime > 0 && mouseItem.type < 1;
         if (!(flag || flag2))
         {
             return;
         }
         int t = _itemIconCacheSelectedItemID;
         if (!flag)
         {
             Utils.Swap(ref t, ref player[myPlayer].cursorItemIconID);
         }
         Microsoft.Xna.Framework.Color currentColor = player[myPlayer].inventory[player[myPlayer].selectedItem].GetAlpha(Microsoft.Xna.Framework.Color.White);
         Microsoft.Xna.Framework.Color color = player[myPlayer].inventory[player[myPlayer].selectedItem].GetColor(Microsoft.Xna.Framework.Color.White);
         if (player[myPlayer].cursorItemIconID != 0)
         {
             currentColor = Microsoft.Xna.Framework.Color.White;
             color = default(Microsoft.Xna.Framework.Color);
         }
         if (player[myPlayer].cursorItemIconID == 269)
         {
             currentColor = player[myPlayer].shirtColor;
         }
         float num2 = 1f;
         num2 = cursorScale;
         ItemSlot.GetItemLight(ref currentColor, num);
         SpriteEffects effects = SpriteEffects.None;
         if (player[myPlayer].cursorItemIconReversed)
         {
             effects = SpriteEffects.FlipHorizontally;
         }
         if (num > 0)
         {
             int num3 = 10 + player[myPlayer].cursorItemIconPush;
             instance.LoadItem(num);
             spriteBatch.Draw(TextureAssets.Item[num].Value, new Vector2(mouseX + num3, mouseY + num3), Item.GetDrawHitbox(num, null), currentColor, 0f, default(Vector2), num2, effects, 0f);
             if (num == item.type && TryGetAmmo(item, out var ammoItem, out var ammoColor, out var ammoScale, out var ammoOffset))
             {
                 float scale = num2 * ammoScale;
                 int type = ammoItem.type;
                 Microsoft.Xna.Framework.Color alpha = ammoItem.GetAlpha(ammoColor);
                 instance.LoadItem(type);
                 spriteBatch.Draw(TextureAssets.Item[type].Value, new Vector2(mouseX + 10, mouseY + 10) + ammoOffset, Item.GetDrawHitbox(type, null), alpha, 0f, default(Vector2), scale, effects, 0f);
             }
         }
         if (player[myPlayer].cursorItemIconText != "")
         {
             MouseText(player[myPlayer].cursorItemIconText, 0, 0);
         }
         if (player[myPlayer].cursorItemIconID == 0 && player[myPlayer].inventory[player[myPlayer].selectedItem].color != default(Microsoft.Xna.Framework.Color))
         {
             instance.LoadItem(player[myPlayer].inventory[player[myPlayer].selectedItem].type);
             spriteBatch.Draw(TextureAssets.Item[player[myPlayer].inventory[player[myPlayer].selectedItem].type].Value, new Vector2(mouseX + 10, mouseY + 10), Item.GetDrawHitbox(player[myPlayer].inventory[player[myPlayer].selectedItem].type, null), color, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
         }
         if (!flag)
         {
             Utils.Swap(ref t, ref player[myPlayer].cursorItemIconID);
         }
     }
References _itemIconCacheSelectedItemID, _itemIconCacheTime, Player.BiomeCampfireHoldStyle(), Player.BiomeTorchHoldStyle(), Player.cursorItemIconEnabled, Player.cursorItemIconID, Player.cursorItemIconPush, cursorScale, Item.GetAlpha(), Item.GetColor(), Item.GetDrawHitbox(), ItemSlot.GetItemLight(), HoveringOverAnNPC, instance, Player.inventory, TextureAssets.Item, item, ItemIconCacheVerification(), LoadItem(), LocalPlayer, Player.mouseInterface, mouseItem, MouseText(), mouseX, mouseY, myPlayer, player, Player.selectedItem, Player.shirtColor, spriteBatch, TryGetAmmo(), Item.type, and Asset< T >.Value.
Referenced by DrawInterface_11_IngameOptionsMenu(), and SetupDrawInterfaceLayers().