Terraria: Main.DrawClothesWindow
DrawClothesWindow()
void Main.DrawClothesWindow () inline protected
     {
         if (npcChatText != "" || playerInventory || player[myPlayer].chest != -1 || npcShop != 0 || player[myPlayer].talkNPC != -1 || InGuideCraftMenu)
         {
             CancelClothesWindow();
             return;
         }
         if (!LocalPlayer.IsInInteractionRangeToMultiTileHitbox(interactedDresserTopLeftX, interactedDresserTopLeftY) || !tile[interactedDresserTopLeftX, interactedDresserTopLeftY].active())
         {
             CancelClothesWindow();
             return;
         }
         int num = 477;
         int num2 = num / 2;
         num2 = 180;
         num = 511;
         num -= num / 2 - num2 - 26;
         int num3 = screenHeight / 2 + 60;
         int num4 = screenWidth / 2 - num / 2;
         int num5 = num3 + 32;
         int num6 = num4 + 22;
         num5 -= 16;
         int num7 = num4 + num - num2;
         int num8 = num3 + 18;
         if (selClothes == 0)
         {
             selColor = player[myPlayer].shirtColor;
         }
         if (selClothes == 1)
         {
             selColor = player[myPlayer].underShirtColor;
         }
         if (selClothes == 2)
         {
             selColor = player[myPlayer].pantsColor;
         }
         if (selClothes == 3)
         {
             selColor = player[myPlayer].shoeColor;
         }
         if (selClothes == 4)
         {
             selColor = player[myPlayer].eyeColor;
         }
         if (selClothes == 5)
         {
             selColor = player[myPlayer].skinColor;
         }
         Utils.DrawInvBG(spriteBatch, new Microsoft.Xna.Framework.Rectangle(num4, num3, num, 133));
         if (!PlayerInput.IgnoreMouseInterface && mouseX > num4 && mouseX < num4 + TextureAssets.ClothesStyleBack.Width() && mouseY > num3 && mouseY < num3 + TextureAssets.ClothesStyleBack.Height())
         {
             player[myPlayer].mouseInterface = true;
         }
         Vector2 vector = new Vector2(num4 + num / 2 - 16 - 28, num3 + 66 + dresserInterfaceDummy.height / 2 - 20);
         vector.Y += 18f;
         vector.X += 58f;
         Microsoft.Xna.Framework.Rectangle r = new Microsoft.Xna.Framework.Rectangle((int)vector.X - dresserInterfaceDummy.width / 2 - 15, (int)vector.Y - dresserInterfaceDummy.height - 33, dresserInterfaceDummy.width + 30, dresserInterfaceDummy.height + 66);
         bool flag = r.Contains(MouseScreen.ToPoint());
         int num9 = selClothes;
         int num10 = (mouseTextColor * 2 + 255) / 3;
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(num10, (int)((double)num10 / 1.1), num10 / 2, num10);
         float num11 = 0.9f;
         string textValue = Language.GetTextValue("GameUI.Change");
         int num12 = num4 + num - num2 + 22;
         num12 = num4 + 22;
         int num13 = num3 + 94;
         bool flag2 = false;
         if (oldClothesColor[0] != player[myPlayer].shirtColor || oldClothesColor[1] != player[myPlayer].underShirtColor || oldClothesColor[2] != player[myPlayer].pantsColor || oldClothesColor[3] != player[myPlayer].shoeColor || oldClothesColor[4] != player[myPlayer].eyeColor || oldClothesColor[5] != player[myPlayer].skinColor || oldClothesStyle != player[myPlayer].skinVariant)
         {
             flag2 = true;
         }
         Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(textValue);
         bool flag3 = false;
         UILinkPointNavigator.SetPosition(2803, new Vector2(num12, num13) + vector2 * num11 * 0.5f);
         if (flag2 && mouseX > num12 && (float)mouseX < (float)num12 + vector2.X && mouseY > num13 && (float)mouseY < (float)num13 + vector2.Y)
         {
             flag3 = true;
             num11 = 1.1f;
             if (!npcChatFocus1)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus1 = true;
             player[myPlayer].releaseUseItem = false;
         }
         else
         {
             if (npcChatFocus1)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus1 = false;
         }
         for (int i = 0; i < 5; i++)
         {
             int num14 = num12;
             int num15 = num13;
             Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Black;
             if (flag3)
             {
                 color2 = Microsoft.Xna.Framework.Color.Brown;
             }
             if (i == 0)
             {
                 num14 -= 2;
             }
             if (i == 1)
             {
                 num14 += 2;
             }
             if (i == 2)
             {
                 num15 -= 2;
             }
             if (i == 3)
             {
                 num15 += 2;
             }
             if (i == 4)
             {
                 color2 = (flag2 ? color : new Microsoft.Xna.Framework.Color(100, 100, 100));
             }
             Vector2 vector3 = FontAssets.MouseText.Value.MeasureString(textValue);
             vector3 *= 0.5f;
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, textValue, new Vector2((float)num14 + vector3.X, (float)num15 + vector3.Y), color2, 0f, vector3, num11, SpriteEffects.None, 0f);
         }
         num11 = 0.9f;
         string textValue2 = Language.GetTextValue("GameUI.Cancel");
         num12 += 130;
         bool flag4 = false;
         vector2 = FontAssets.MouseText.Value.MeasureString(textValue2);
         UILinkPointNavigator.SetPosition(2804, new Vector2(num12, num13) + vector2 * num11 * 0.5f);
         if (mouseX > num12 && (float)mouseX < (float)num12 + vector2.X && mouseY > num13 && (float)mouseY < (float)num13 + vector2.Y)
         {
             flag4 = true;
             num11 = 1.1f;
             if (!npcChatFocus2)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus2 = true;
             player[myPlayer].releaseUseItem = false;
         }
         else
         {
             if (npcChatFocus2)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus2 = false;
         }
         for (int j = 0; j < 5; j++)
         {
             int num16 = num12;
             int num17 = num13;
             Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.Black;
             if (flag4)
             {
                 color3 = Microsoft.Xna.Framework.Color.Brown;
             }
             if (j == 0)
             {
                 num16 -= 2;
             }
             if (j == 1)
             {
                 num16 += 2;
             }
             if (j == 2)
             {
                 num17 -= 2;
             }
             if (j == 3)
             {
                 num17 += 2;
             }
             if (j == 4)
             {
                 color3 = color;
             }
             Vector2 vector4 = FontAssets.MouseText.Value.MeasureString(textValue2);
             vector4 *= 0.5f;
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, textValue2, new Vector2((float)num16 + vector4.X, (float)num17 + vector4.Y), color3, 0f, vector4, num11, SpriteEffects.None, 0f);
         }
         if (mouseLeft && mouseLeftRelease)
         {
             if (npcChatFocus1)
             {
                 SaveClothesWindow();
                 return;
             }
             if (npcChatFocus2)
             {
                 CancelClothesWindow();
                 return;
             }
         }
         if (!mouseLeft)
         {
             grabColorSlider = 0;
             blockMouse = false;
         }
         int num18 = 167;
         Vector3 vector5 = rgbToHsl(selColor);
         float num19 = vector5.X;
         float num20 = vector5.Y;
         float z = vector5.Z;
         if (hBar == -1f || sBar == -1f || lBar == -1f)
         {
             hBar = num19;
             sBar = num20;
             lBar = z;
         }
         else
         {
             num19 = hBar;
             num20 = sBar;
             z = lBar;
         }
         spriteBatch.Draw(TextureAssets.Hue.Value, new Vector2(num6, num5), Microsoft.Xna.Framework.Color.White);
         if ((mouseX > num6 - 4 && mouseX < num6 + TextureAssets.Hue.Width() + 4 && mouseY > num5 - 4 && mouseY < num5 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 1)
         {
             spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num6, num5), OurFavoriteColor);
         }
         spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num6 + (float)(TextureAssets.Hue.Width() - 2) * hBar - (float)(TextureAssets.ColorSlider.Width() / 2), num5 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
         if (((mouseX > num6 - 4 && mouseX < num6 + TextureAssets.Hue.Width() + 4 && mouseY > num5 - 4 && mouseY < num5 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 1) && mouseLeft && !blockMouse)
         {
             grabColorSlider = 1;
             num19 = mouseX - num6;
             num19 /= (float)TextureAssets.Hue.Width();
             if (num19 < 0f)
             {
                 num19 = 0f;
             }
             if (num19 > 1f)
             {
                 num19 = 1f;
             }
             hBar = num19;
         }
         UILinkPointNavigator.SetPosition(2800, new Vector2(num6, num5) + TextureAssets.Hue.Value.Size() / 2f);
         num5 += 26;
         spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2(num6, num5), Microsoft.Xna.Framework.Color.White);
         for (int k = 0; k <= num18; k++)
         {
             float saturation = (float)k / (float)num18;
             Microsoft.Xna.Framework.Color color4 = hslToRgb(num19, saturation, z);
             spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2(num6 + k + 5, num5 + 4), color4);
         }
         if ((mouseX > num6 - 4 && mouseX < num6 + TextureAssets.Hue.Width() + 4 && mouseY > num5 - 4 && mouseY < num5 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 2)
         {
             spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num6, num5), OurFavoriteColor);
         }
         spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num6 + (float)(TextureAssets.Hue.Width() - 2) * sBar - (float)(TextureAssets.ColorSlider.Width() / 2), num5 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
         if (((mouseX > num6 - 4 && mouseX < num6 + TextureAssets.Hue.Width() + 4 && mouseY > num5 - 4 && mouseY < num5 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 2) && mouseLeft && !blockMouse)
         {
             grabColorSlider = 2;
             num20 = mouseX - num6;
             num20 /= (float)TextureAssets.Hue.Width();
             if (num20 < 0f)
             {
                 num20 = 0f;
             }
             if (num20 > 1f)
             {
                 num20 = 1f;
             }
             sBar = num20;
         }
         UILinkPointNavigator.SetPosition(2801, new Vector2(num6, num5) + TextureAssets.Hue.Value.Size() / 2f);
         num5 += 26;
         spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2(num6, num5), Microsoft.Xna.Framework.Color.White);
         float num21 = 0.15f;
         for (int l = 0; l <= num18; l++)
         {
             float luminosity = (float)l / (float)num18;
             Microsoft.Xna.Framework.Color color5 = hslToRgb(num19, num20, luminosity);
             spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2(num6 + l + 5, num5 + 4), color5);
         }
         if ((mouseX > num6 - 4 && mouseX < num6 + TextureAssets.Hue.Width() + 4 && mouseY > num5 - 4 && mouseY < num5 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 3)
         {
             spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num6, num5), OurFavoriteColor);
         }
         spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num6 + (float)(TextureAssets.Hue.Width() - 2) * ((lBar - num21) / (1f - num21)) - (float)(TextureAssets.ColorSlider.Width() / 2), num5 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
         if (((mouseX > num6 - 4 && mouseX < num6 + TextureAssets.Hue.Width() + 4 && mouseY > num5 - 4 && mouseY < num5 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 3) && mouseLeft && !blockMouse)
         {
             grabColorSlider = 3;
             z = mouseX - num6;
             z /= (float)TextureAssets.Hue.Width();
             if (z < 0f)
             {
                 z = 0f;
             }
             if (z > 1f)
             {
                 z = 1f;
             }
             z = z * (1f - num21) + num21;
             lBar = z;
         }
         UILinkPointNavigator.SetPosition(2802, new Vector2(num6, num5) + TextureAssets.Hue.Value.Size() / 2f);
         selColor = hslToRgb(hBar, sBar, lBar);
         if (selClothes == 0)
         {
             player[myPlayer].shirtColor = selColor;
         }
         if (selClothes == 1)
         {
             player[myPlayer].underShirtColor = selColor;
         }
         if (selClothes == 2)
         {
             player[myPlayer].pantsColor = selColor;
         }
         if (selClothes == 3)
         {
             player[myPlayer].shoeColor = selColor;
         }
         if (selClothes == 4)
         {
             player[myPlayer].eyeColor = selColor;
         }
         if (selClothes == 5)
         {
             player[myPlayer].skinColor = selColor;
         }
         int num22 = num7;
         int num23 = num8;
         num23 -= 8;
         for (int m = 0; m < 6; m++)
         {
             if (num9 == m)
             {
                 spriteBatch.Draw(TextureAssets.InventoryBack14.Value, new Vector2(num22, num23), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height()), new Microsoft.Xna.Framework.Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
             else
             {
                 spriteBatch.Draw(TextureAssets.InventoryBack8.Value, new Vector2(num22, num23), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height()), new Microsoft.Xna.Framework.Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
             if (mouseX > num22 && mouseX < num22 + TextureAssets.InventoryBack.Width() && mouseY > num23 && mouseY < num23 + TextureAssets.InventoryBack.Height() && mouseLeft && mouseLeftRelease)
             {
                 mouseLeftRelease = false;
                 selClothes = m;
                 SoundEngine.PlaySound(12);
                 hBar = -1f;
                 lBar = -1f;
                 sBar = -1f;
             }
             float x = num22 + TextureAssets.InventoryBack.Width() / 2 - TextureAssets.Clothes[m].Width() / 2;
             float y = num23 + TextureAssets.InventoryBack.Height() / 2 - TextureAssets.Clothes[m].Height() / 2;
             Microsoft.Xna.Framework.Color color6 = Microsoft.Xna.Framework.Color.White;
             if (m == 0)
             {
                 color6 = player[myPlayer].shirtColor;
             }
             if (m == 1)
             {
                 color6 = player[myPlayer].underShirtColor;
             }
             if (m == 2)
             {
                 color6 = player[myPlayer].pantsColor;
             }
             if (m == 3)
             {
                 color6 = player[myPlayer].shoeColor;
             }
             if (m == 4)
             {
                 color6 = player[myPlayer].eyeColor;
             }
             if (m == 5)
             {
                 color6 = player[myPlayer].skinColor;
             }
             spriteBatch.Draw(TextureAssets.Clothes[m].Value, new Vector2(x, y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Clothes[m].Width(), TextureAssets.Clothes[m].Height()), color6, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             if (m == 4)
             {
                 Texture2D value = Assets.Request<Texture2D>("Images/UI/CharCreation/ColorEyeBack", (AssetRequestMode)1).Value;
                 spriteBatch.Draw(value, new Vector2(x, y), value.Frame(), Microsoft.Xna.Framework.Color.White, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
             UILinkPointNavigator.SetPosition(2806 + m, new Vector2(x, y) + TextureAssets.Clothes[m].Value.Size() * 0.75f);
             num22 += 56;
             if (m == 1)
             {
                 num22 -= 112;
                 num23 += 56;
             }
             if (m == 3)
             {
                 num23 -= 56;
             }
             if (m == 4)
             {
                 num23 += 56;
                 num22 -= 56;
             }
         }
         dresserInterfaceDummy.skinVariant = player[myPlayer].skinVariant;
         dresserInterfaceDummy.eyeColor = player[myPlayer].eyeColor;
         dresserInterfaceDummy.hairColor = player[myPlayer].hairColor;
         dresserInterfaceDummy.hair = player[myPlayer].hair;
         dresserInterfaceDummy.skinColor = player[myPlayer].skinColor;
         dresserInterfaceDummy.shirtColor = player[myPlayer].shirtColor;
         dresserInterfaceDummy.underShirtColor = player[myPlayer].underShirtColor;
         dresserInterfaceDummy.shoeColor = player[myPlayer].shoeColor;
         dresserInterfaceDummy.pantsColor = player[myPlayer].pantsColor;
         dresserInterfaceDummy.Bottom = screenPosition + vector;
         dresserInterfaceDummy.direction = -1;
         dresserInterfaceDummy.gravDir = 1f;
         dresserInterfaceDummy.PlayerFrame();
         dresserInterfaceDummy.socialIgnoreLight = true;
         Microsoft.Xna.Framework.Color c = new Microsoft.Xna.Framework.Color(46, 106, 98) * 0.6f;
         if (flag)
         {
             c = new Microsoft.Xna.Framework.Color(46, 106, 98) * 2f * 0.6f;
             if (mouseLeft && mouseLeftRelease)
             {
                 mouseLeftRelease = false;
                 SoundEngine.PlaySound(12);
                 CycleClothingStyle(player[myPlayer]);
             }
         }
         UILinkPointNavigator.SetPosition(2805, r.Center.ToVector2());
         Utils.DrawInvBG(spriteBatch, r, c);
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Immediate, null, null, null, null, null, UIScaleMatrix);
         PlayerRenderer.DrawPlayer(Camera, dresserInterfaceDummy, dresserInterfaceDummy.position, dresserInterfaceDummy.fullRotation, dresserInterfaceDummy.fullRotationOrigin);
     }
References Tile.active(), Assets, blockMouse, Entity.Bottom, CancelClothesWindow(), chest, TextureAssets.Clothes, TextureAssets.ClothesStyleBack, TextureAssets.ColorBar, TextureAssets.ColorBlip, TextureAssets.ColorHighlight, TextureAssets.ColorSlider, CycleClothingStyle(), Entity.direction, Utils.DrawInvBG(), IPlayerRenderer.DrawPlayer(), DynamicSpriteFontExtensionMethods.DrawString(), dresserInterfaceDummy, Player.eyeColor, Player.fullRotation, Player.fullRotationOrigin, Language.GetTextValue(), grabColorSlider, Player.gravDir, Player.hair, Player.hairColor, hBar, Entity.height, hslToRgb(), TextureAssets.Hue, PlayerInput.IgnoreMouseInterface, InGuideCraftMenu, interactedDresserTopLeftX, interactedDresserTopLeftY, TextureAssets.InventoryBack, TextureAssets.InventoryBack14, TextureAssets.InventoryBack8, Player.IsInInteractionRangeToMultiTileHitbox(), lBar, LocalPlayer, Player.mouseInterface, mouseLeft, mouseLeftRelease, MouseScreen, FontAssets.MouseText, mouseTextColor, mouseX, mouseY, myPlayer, npcChatFocus1, npcChatFocus2, npcChatText, npcShop, oldClothesColor, oldClothesStyle, OurFavoriteColor, Player.pantsColor, player, Player.PlayerFrame(), playerInventory, PlayerRenderer, SoundEngine.PlaySound(), Entity.position, Player.releaseUseItem, rgbToHsl(), SaveClothesWindow(), sBar, screenHeight, screenPosition, screenWidth, selClothes, selColor, UILinkPointNavigator.SetPosition(), Player.shirtColor, Player.shoeColor, Player.skinColor, Player.skinVariant, Player.socialIgnoreLight, spriteBatch, tile, UIScaleMatrix, Player.underShirtColor, Asset< T >.Value, and Entity.width.
Referenced by DrawInterface_22_DresserWindow().