Terraria: Main.OldDrawBackground
OldDrawBackground()
void Main.OldDrawBackground () inline protected
     {
         Microsoft.Xna.Framework.Color[] slices = new Microsoft.Xna.Framework.Color[9];
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         int num = (int)(255f * (1f - gfxQuality) + 140f * gfxQuality);
         int num2 = (int)(200f * (1f - gfxQuality) + 40f * gfxQuality);
         int num3 = 128;
         Vector2 vector = new Vector2(offScreenRange, offScreenRange);
         if (drawToScreen)
         {
             vector = Vector2.Zero;
         }
         float num4;
         float num5;
         float num6 = (num5 = (num4 = 0.9f));
         float num7 = 0f;
         if (SceneMetrics.BloodTileCount > SceneMetrics.EvilTileCount && SceneMetrics.BloodTileCount > SceneMetrics.HolyTileCount)
         {
             num7 = SceneMetrics.BloodTileCount;
         }
         else if (SceneMetrics.HolyTileCount > SceneMetrics.EvilTileCount)
         {
             num7 = SceneMetrics.HolyTileCount;
         }
         else if (SceneMetrics.EvilTileCount > SceneMetrics.HolyTileCount)
         {
             num7 = SceneMetrics.EvilTileCount;
         }
         num7 = MathHelper.Clamp(num7 / 800f, 0f, 1f);
         float num8 = (float)((double)screenPosition.Y - worldSurface * 16.0) / 300f;
         if (num8 < 0f)
         {
             num8 = 0f;
         }
         else if (num8 > 1f)
         {
             num8 = 1f;
         }
         float num9 = 1f * (1f - num8) + num4 * num8;
         float globalBrightness = Lighting.GlobalBrightness;
         Lighting.GlobalBrightness = globalBrightness * (1f - num8) + 1f * num8;
         float value = (float)((double)(screenPosition.Y - (float)(screenHeight / 2) + 200f) - rockLayer * 16.0) / 300f;
         value = MathHelper.Clamp(value, 0f, 1f);
         if (SceneMetrics.BloodTileCount > SceneMetrics.EvilTileCount && SceneMetrics.BloodTileCount > SceneMetrics.HolyTileCount)
         {
             num4 = 1f * num7 + num4 * (1f - num7);
             num5 = 0.55f * num7 + num5 * (1f - num7);
             num6 = 0.5f * num7 + num6 * (1f - num7);
         }
         else if (SceneMetrics.EvilTileCount > 0)
         {
             num4 = 0.8f * num7 + num4 * (1f - num7);
             num5 = 0.75f * num7 + num5 * (1f - num7);
             num6 = 1.1f * num7 + num6 * (1f - num7);
         }
         else if (SceneMetrics.HolyTileCount > 0)
         {
             num4 = 1f * num7 + num4 * (1f - num7);
             num5 = 0.7f * num7 + num5 * (1f - num7);
             num6 = 0.9f * num7 + num6 * (1f - num7);
         }
         num4 = 1f * (num9 - value) + num4 * value;
         num5 = 1f * (num9 - value) + num5 * value;
         num6 = 1f * (num9 - value) + num6 * value;
         int num10 = (int)((screenPosition.X + (float)(screenWidth / 2)) / 16f);
         int num11 = 3;
         num11 = ((num10 <= caveBackX[0]) ? caveBackStyle[0] : ((num10 <= caveBackX[1]) ? caveBackStyle[1] : ((num10 > caveBackX[2]) ? caveBackStyle[3] : caveBackStyle[2])));
         num11 += 3;
         if (SceneMetrics.SnowTileCount > SceneMetrics.SnowTileThreshold && (screenPosition.Y + (float)screenHeight) / 16f < (float)(maxTilesY - 250))
         {
             num11 = 1;
         }
         if (SceneMetrics.JungleTileCount > SceneMetrics.JungleTileThreshold)
         {
             if (num11 == 1)
             {
                 if (SceneMetrics.JungleTileCount > SceneMetrics.SnowTileCount)
                 {
                     num11 = 11;
                 }
             }
             else
             {
                 num11 = 11;
             }
         }
         if (SceneMetrics.EnoughTilesForGlowingMushroom)
         {
             num11 = 2;
         }
         if (num11 != undergroundBackground)
         {
             oldUndergroundBackground = undergroundBackground;
             undergroundBackground = num11;
             ugBackTransition = 1f;
         }
         if (ugBackTransition > 0f)
         {
             ugBackTransition -= 0.25f;
         }
         if (ugBackTransition < 0f)
         {
             ugBackTransition = 0f;
         }
         int[] array = new int[6];
         int[] array2 = new int[6];
         for (int i = 0; i < 2; i++)
         {
             int num12 = undergroundBackground;
             if (i == 1)
             {
                 num12 = oldUndergroundBackground;
             }
             int[] array3 = new int[6];
             switch (num12)
             {
             case 0:
                 array3[0] = 1;
                 array3[1] = 2;
                 array3[2] = 4;
                 array3[3] = 3;
                 array3[4] = 6;
                 array3[5] = 5;
                 break;
             case 1:
                 if (iceBackStyle == 0)
                 {
                     array3[1] = 33;
                     array3[3] = 32;
                     array3[0] = 40;
                     array3[2] = 34;
                 }
                 else if (iceBackStyle == 1)
                 {
                     array3[1] = 118;
                     array3[3] = 117;
                     array3[0] = 160;
                     array3[2] = 161;
                 }
                 else if (iceBackStyle == 2)
                 {
                     array3[1] = 165;
                     array3[3] = 167;
                     array3[0] = 164;
                     array3[2] = 166;
                 }
                 else
                 {
                     array3[1] = 120;
                     array3[3] = 119;
                     array3[0] = 162;
                     array3[2] = 163;
                 }
                 array3[4] = array3[3];
                 break;
             case 2:
                 array3[0] = 62;
                 array3[1] = 63;
                 array3[2] = 64;
                 array3[3] = 65;
                 array3[4] = 143 + hellBackStyle;
                 break;
             case 3:
                 array3[0] = 66;
                 array3[1] = 67;
                 array3[2] = 68;
                 array3[3] = 69;
                 array3[4] = 128 + hellBackStyle;
                 break;
             case 4:
                 array3[0] = 70;
                 array3[1] = 71;
                 array3[2] = 68;
                 array3[3] = 72;
                 array3[4] = 128 + hellBackStyle;
                 break;
             case 5:
                 array3[0] = 73;
                 array3[1] = 74;
                 array3[2] = 75;
                 array3[3] = 76;
                 array3[4] = 131 + hellBackStyle;
                 break;
             case 6:
                 array3[0] = 77;
                 array3[1] = 78;
                 array3[2] = 79;
                 array3[3] = 80;
                 array3[4] = 134 + hellBackStyle;
                 break;
             case 7:
                 array3[0] = 77;
                 array3[1] = 81;
                 array3[2] = 79;
                 array3[3] = 82;
                 array3[4] = 134 + hellBackStyle;
                 break;
             case 8:
                 array3[0] = 83;
                 array3[1] = 84;
                 array3[2] = 85;
                 array3[3] = 86;
                 array3[4] = 137 + hellBackStyle;
                 break;
             case 9:
                 array3[0] = 83;
                 array3[1] = 87;
                 array3[2] = 88;
                 array3[3] = 89;
                 array3[4] = 137 + hellBackStyle;
                 break;
             case 10:
                 array3[0] = 121;
                 array3[1] = 122;
                 array3[2] = 123;
                 array3[3] = 124;
                 array3[4] = 140 + hellBackStyle;
                 break;
             case 11:
                 if (jungleBackStyle == 0)
                 {
                     array3[0] = 153;
                     array3[1] = 147;
                     array3[2] = 148;
                     array3[3] = 149;
                     array3[4] = 150 + hellBackStyle;
                 }
                 else
                 {
                     array3[0] = 146;
                     array3[1] = 154;
                     array3[2] = 155;
                     array3[3] = 156;
                     array3[4] = 157 + hellBackStyle;
                 }
                 break;
             }
             if (hellBackStyle == 0)
             {
                 array3[5] = 125;
             }
             if (hellBackStyle == 1)
             {
                 array3[5] = 126;
             }
             if (hellBackStyle == 2)
             {
                 array3[5] = 127;
             }
             LoadBackground(array3[0]);
             LoadBackground(array3[1]);
             LoadBackground(array3[2]);
             LoadBackground(array3[3]);
             LoadBackground(array3[4]);
             LoadBackground(array3[5]);
             if (i == 0)
             {
                 for (int j = 0; j < 6; j++)
                 {
                     array[j] = array3[j];
                 }
             }
             else
             {
                 for (int k = 0; k < 6; k++)
                 {
                     array2[k] = array3[k];
                 }
             }
         }
         globalBrightness = 1.2f * (1f - value) + 1f * value;
         bgParallax = caveParallax;
         bgStartX = (int)(0.0 - Math.IEEERemainder((double)num3 + (double)screenPosition.X * bgParallax, num3) - (double)(num3 / 2)) - (int)vector.X;
         bgLoops = (screenWidth + (int)vector.X * 2) / num3 + 2;
         bgTopY = (int)((float)((int)worldSurface * 16 - 16) - screenPosition.Y + 16f);
         for (int l = 0; l < bgLoops; l++)
         {
             for (int m = 0; m < num3 / 16; m++)
             {
                 int num13 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
                 if (num13 == -8)
                 {
                     num13 = 8;
                 }
                 float num14 = bgStartX + num3 * l + m * 16 + 8;
                 float num15 = bgTopY;
                 Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)((num14 + screenPosition.X) / 16f), (int)((screenPosition.Y + num15) / 16f));
                 color.R = (byte)((float)(int)color.R * num4);
                 color.G = (byte)((float)(int)color.G * num5);
                 color.B = (byte)((float)(int)color.B * num6);
                 spriteBatch.Draw(TextureAssets.Background[array[0]].Value, new Vector2(bgStartX + num3 * l + 16 * m + num13, bgTopY) + vector, new Microsoft.Xna.Framework.Rectangle(16 * m + num13 + 16, 0, 16, 16), color);
                 if (ugBackTransition > 0f)
                 {
                     Microsoft.Xna.Framework.Color color2 = color;
                     color2.R = (byte)((float)(int)color2.R * ugBackTransition);
                     color2.G = (byte)((float)(int)color2.G * ugBackTransition);
                     color2.B = (byte)((float)(int)color2.B * ugBackTransition);
                     color2.A = (byte)((float)(int)color2.A * ugBackTransition);
                     spriteBatch.Draw(TextureAssets.Background[array2[0]].Value, new Vector2(bgStartX + num3 * l + 16 * m + num13, bgTopY) + vector, new Microsoft.Xna.Framework.Rectangle(16 * m + num13 + 16, 0, 16, 16), color2);
                 }
             }
         }
         double num16 = maxTilesY - 230;
         double num17 = (int)((num16 - worldSurface) / 6.0) * 6;
         num16 = worldSurface + num17 - 5.0;
         bool flag = false;
         bool flag2 = false;
         bgTopY = (int)((float)((int)worldSurface * 16) - screenPosition.Y + 16f);
         if (worldSurface * 16.0 <= (double)(screenPosition.Y + (float)screenHeight + (float)offScreenRange))
         {
             bgParallax = caveParallax;
             bgStartX = (int)(0.0 - Math.IEEERemainder((double)num3 + (double)screenPosition.X * bgParallax, num3) - (double)(num3 / 2)) - (int)vector.X;
             bgLoops = (screenWidth + (int)vector.X * 2) / num3 + 2;
             if (worldSurface * 16.0 < (double)(screenPosition.Y - 16f))
             {
                 bgStartY = (int)(Math.IEEERemainder(bgTopY, backgroundHeight[2]) - (double)backgroundHeight[2]);
                 bgLoopsY = (screenHeight - bgStartY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
             }
             else
             {
                 bgStartY = bgTopY;
                 bgLoopsY = (screenHeight - bgTopY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
             }
             if (rockLayer * 16.0 < (double)(Camera.ScaledPosition.Y + 600f))
             {
                 bgLoopsY = (int)(rockLayer * 16.0 - (double)screenPosition.Y + 600.0 - (double)bgStartY) / backgroundHeight[2];
                 flag2 = true;
             }
             int num18 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
             if (num18 == -8)
             {
                 num18 = 8;
             }
             for (int n = 0; n < bgLoops; n++)
             {
                 for (int num19 = 0; num19 < bgLoopsY; num19++)
                 {
                     for (int num20 = 0; num20 < num3 / 16; num20++)
                     {
                         for (int num21 = 0; num21 < 6; num21++)
{
                             float num22 = bgStartY + num19 * 96 + num21 * 16 + 8;
                             int num23 = (int)(((float)(bgStartX + num3 * n + num20 * 16 + 8) + screenPosition.X) / 16f);
                             int num24 = (int)((num22 + screenPosition.Y) / 16f);
                             Microsoft.Xna.Framework.Color color3 = Lighting.GetColor(num23, num24);
                             if (tile[num23, num24] == null)
{
                                 tile[num23, num24] = new Tile();
                             }
                             if (color3.R > 0 || color3.G > 0 || color3.B > 0)
{
                                 if (!drawToScreen)
{
                                     Lighting.GetCornerColors(num23, num24, out var vertices);
                                     tileBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num18, bgStartY + backgroundHeight[array2[1]] * num19 + 16 * num21) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num18 + 16, 16 * num21, 16, 16), vertices, Vector2.Zero, 1f, SpriteEffects.None);
                                 }
                                 else if ((color3.R > num || (double)(int)color3.G > (double)num * 1.1 || (double)(int)color3.B > (double)num * 1.2) && !tile[num23, num24].active() && WallLightAt(num23, num24) && ugBackTransition == 0f)
{
                                     Lighting.GetColor9Slice(num23, num24, ref slices);
                                     try
{
                                         for (int num25 = 0; num25 < 9; num25++)
{
                                             int num26 = 0;
                                             int num27 = 0;
                                             int width = 4;
                                             int height = 4;
                                             Microsoft.Xna.Framework.Color color4 = color3;
                                             Microsoft.Xna.Framework.Color color5 = color3;
                                             switch (num25)
{
                                             case 0:
                                                 if (!tile[num23 - 1, num24 - 1].active())
{
                                                     color5 = slices[num25];
                                                 }
                                                 break;
                                             case 1:
                                                 width = 8;
                                                 num26 = 4;
                                                 if (!tile[num23, num24 - 1].active())
{
                                                     color5 = slices[num25];
                                                 }
                                                 break;
                                             case 2:
                                                 num26 = 12;
                                                 if (!tile[num23 + 1, num24 - 1].active())
{
                                                     color5 = slices[num25];
                                                 }
                                                 break;
                                             case 3:
                                                 height = 8;
                                                 num27 = 4;
                                                 if (!tile[num23 - 1, num24].active())
{
                                                     color5 = slices[num25];
                                                 }
                                                 break;
                                             case 4:
                                                 width = 8;
                                                 height = 8;
                                                 num26 = 4;
                                                 num27 = 4;
                                                 break;
                                             case 5:
                                                 num26 = 12;
                                                 num27 = 4;
                                                 height = 8;
                                                 if (!tile[num23 + 1, num24].active())
{
                                                     color5 = slices[num25];
                                                 }
                                                 break;
                                             case 6:
                                                 num27 = 12;
                                                 if (!tile[num23 - 1, num24 + 1].active())
{
                                                     color5 = slices[num25];
                                                 }
                                                 break;
                                             case 7:
                                                 width = 8;
                                                 height = 4;
                                                 num26 = 4;
                                                 num27 = 12;
                                                 if (!tile[num23, num24 + 1].active())
{
                                                     color5 = slices[num25];
                                                 }
                                                 break;
                                             case 8:
                                                 num26 = 12;
                                                 num27 = 12;
                                                 if (!tile[num23 + 1, num24 + 1].active())
{
                                                     color5 = slices[num25];
                                                 }
                                                 break;
                                             }
                                             color4.R = (byte)((color3.R + color5.R) / 2);
                                             color4.G = (byte)((color3.G + color5.G) / 2);
                                             color4.B = (byte)((color3.B + color5.B) / 2);
                                             color4.R = (byte)((float)(int)color4.R * num4);
                                             color4.G = (byte)((float)(int)color4.G * num5);
                                             color4.B = (byte)((float)(int)color4.B * num6);
                                             spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num26 + num18, bgStartY + backgroundHeight[array[1]] * num19 + 16 * num21 + num27) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num26 + num18 + 16, 16 * num21 + num27, width, height), color4);
                                             if (ugBackTransition > 0f)
{
                                                 Microsoft.Xna.Framework.Color color6 = color4;
                                                 color6.R = (byte)((float)(int)color6.R * ugBackTransition);
                                                 color6.G = (byte)((float)(int)color6.G * ugBackTransition);
                                                 color6.B = (byte)((float)(int)color6.B * ugBackTransition);
                                                 color6.A = (byte)((float)(int)color6.A * ugBackTransition);
                                                 spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num26 + num18, bgStartY + backgroundHeight[array2[1]] * num19 + 16 * num21 + num27) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num26 + num18 + 16, 16 * num21 + num27, width, height), color6);
                                             }
                                         }
                                     }
                                     catch
{
                                         color3.R = (byte)((float)(int)color3.R * num4);
                                         color3.G = (byte)((float)(int)color3.G * num5);
                                         color3.B = (byte)((float)(int)color3.B * num6);
                                         spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num18, bgStartY + backgroundHeight[array[1]] * num19 + 16 * num21) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num18 + 16, 16 * num21, 16, 16), color3);
                                     }
                                 }
                                 else if ((color3.R > num2 || (double)(int)color3.G > (double)num2 * 1.1 || (double)(int)color3.B > (double)num2 * 1.2) && ugBackTransition == 0f)
{
                                     Lighting.GetColor4Slice(num23, num24, ref slices);
                                     for (int num28 = 0; num28 < 4; num28++)
{
                                         int num29 = 0;
                                         int num30 = 0;
                                         Microsoft.Xna.Framework.Color color7 = color3;
                                         Microsoft.Xna.Framework.Color color8 = slices[num28];
                                         switch (num28)
{
                                         case 1:
                                             num29 = 8;
                                             break;
                                         case 2:
                                             num30 = 8;
                                             break;
                                         case 3:
                                             num29 = 8;
                                             num30 = 8;
                                             break;
                                         }
                                         color7.R = (byte)((color3.R + color8.R) / 2);
                                         color7.G = (byte)((color3.G + color8.G) / 2);
                                         color7.B = (byte)((color3.B + color8.B) / 2);
                                         color7.R = (byte)((float)(int)color7.R * num4);
                                         color7.G = (byte)((float)(int)color7.G * num5);
                                         color7.B = (byte)((float)(int)color7.B * num6);
                                         spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num29 + num18, bgStartY + backgroundHeight[array[1]] * num19 + 16 * num21 + num30) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num29 + num18 + 16, 16 * num21 + num30, 8, 8), color7);
                                         if (ugBackTransition > 0f)
{
                                             Microsoft.Xna.Framework.Color color9 = color7;
                                             color9.R = (byte)((float)(int)color9.R * ugBackTransition);
                                             color9.G = (byte)((float)(int)color9.G * ugBackTransition);
                                             color9.B = (byte)((float)(int)color9.B * ugBackTransition);
                                             color9.A = (byte)((float)(int)color9.A * ugBackTransition);
                                             spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num29 + num18, bgStartY + backgroundHeight[array2[1]] * num19 + 16 * num21 + num30) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num29 + num18 + 16, 16 * num21 + num30, 8, 8), color9);
                                         }
                                     }
                                 }
                                 else
{
                                     color3.R = (byte)((float)(int)color3.R * num4);
                                     color3.G = (byte)((float)(int)color3.G * num5);
                                     color3.B = (byte)((float)(int)color3.B * num6);
                                     spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num18, bgStartY + backgroundHeight[array[1]] * num19 + 16 * num21) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num18 + 16, 16 * num21, 16, 16), color3);
                                     if (ugBackTransition > 0f)
{
                                         Microsoft.Xna.Framework.Color color10 = color3;
                                         color10.R = (byte)((float)(int)color10.R * ugBackTransition);
                                         color10.G = (byte)((float)(int)color10.G * ugBackTransition);
                                         color10.B = (byte)((float)(int)color10.B * ugBackTransition);
                                         color10.A = (byte)((float)(int)color10.A * ugBackTransition);
                                         spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num18, bgStartY + backgroundHeight[array2[1]] * num19 + 16 * num21) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num18 + 16, 16 * num21, 16, 16), color10);
                                     }
                                 }
                             }
                             else
{
                                 color3.R = (byte)((float)(int)color3.R * num4);
                                 color3.G = (byte)((float)(int)color3.G * num5);
                                 color3.B = (byte)((float)(int)color3.B * num6);
                                 spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2(bgStartX + num3 * n + 16 * num20 + num18, bgStartY + backgroundHeight[array[1]] * num19 + 16 * num21) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num20 + num18 + 16, 16 * num21, 16, 16), color3);
                             }
                         }
                     }
                 }
             }
             if (ugBackTransition > 0f)
             {
                 for (int num31 = 0; num31 < bgLoops; num31++)
                 {
                     for (int num32 = 0; num32 < bgLoopsY; num32++)
                     {
                         for (int num33 = 0; num33 < num3 / 16; num33++)
{
                             for (int num34 = 0; num34 < 6; num34++)
{
                                 float num35 = bgStartY + num32 * 96 + num34 * 16 + 8;
                                 int num36 = (int)(((float)(bgStartX + num3 * num31 + num33 * 16 + 8) + screenPosition.X) / 16f);
                                 int num37 = (int)((num35 + screenPosition.Y) / 16f);
                                 Microsoft.Xna.Framework.Color color11 = Lighting.GetColor(num36, num37);
                                 if (tile[num36, num37] == null)
{
                                     tile[num36, num37] = new Tile();
                                 }
                                 if (color11.R > 0 || color11.G > 0 || color11.B > 0)
{
                                     Lighting.GetCornerColors(num36, num37, out var vertices2, ugBackTransition);
                                     byte a = (byte)(255f * ugBackTransition);
                                     vertices2.BottomLeftColor.A = a;
                                     vertices2.BottomRightColor.A = a;
                                     vertices2.TopLeftColor.A = a;
                                     vertices2.TopRightColor.A = a;
                                     tileBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2(bgStartX + num3 * num31 + 16 * num33 + num18, bgStartY + backgroundHeight[array2[1]] * num32 + 16 * num34) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num33 + num18 + 16, 16 * num34, 16, 16), vertices2, Vector2.Zero, 1f, SpriteEffects.None);
                                 }
                             }
                         }
                     }
                 }
             }
             if (flag2)
             {
                 bgParallax = caveParallax;
                 bgStartX = (int)(0.0 - Math.IEEERemainder((double)num3 + (double)screenPosition.X * bgParallax, num3) - (double)(num3 / 2)) - (int)vector.X;
                 bgLoops = (screenWidth + (int)vector.X * 2) / num3 + 2;
                 bgTopY = bgStartY + bgLoopsY * backgroundHeight[2];
                 if (bgTopY > -32)
                 {
                     for (int num38 = 0; num38 < bgLoops; num38++)
                     {
                         for (int num39 = 0; num39 < num3 / 16; num39++)
{
                             float num40 = bgStartX + num3 * num38 + num39 * 16 + 8;
                             float num41 = bgTopY;
                             Microsoft.Xna.Framework.Color color12 = Lighting.GetColor((int)((num40 + screenPosition.X) / 16f), (int)((screenPosition.Y + num41) / 16f));
                             color12.R = (byte)((float)(int)color12.R * num4);
                             color12.G = (byte)((float)(int)color12.G * num5);
                             color12.B = (byte)((float)(int)color12.B * num6);
                             spriteBatch.Draw(TextureAssets.Background[array[2]].Value, new Vector2(bgStartX + num3 * num38 + 16 * num39 + num18, bgTopY) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num39 + num18 + 16, 0, 16, 16), color12);
                             if (ugBackTransition > 0f)
{
                                 Microsoft.Xna.Framework.Color color13 = color12;
                                 color13.R = (byte)((float)(int)color13.R * ugBackTransition);
                                 color13.G = (byte)((float)(int)color13.G * ugBackTransition);
                                 color13.B = (byte)((float)(int)color13.B * ugBackTransition);
                                 color13.A = (byte)((float)(int)color13.A * ugBackTransition);
                                 spriteBatch.Draw(TextureAssets.Background[array2[2]].Value, new Vector2(bgStartX + num3 * num38 + 16 * num39 + num18, bgTopY) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num39 + num18 + 16, 0, 16, 16), color13);
                             }
                         }
                     }
                 }
             }
         }
         bgTopY = (int)((float)((int)rockLayer * 16) - screenPosition.Y + 16f + 600f - 8f);
         if (rockLayer * 16.0 <= (double)(screenPosition.Y + 600f))
         {
             bgParallax = caveParallax;
             bgStartX = (int)(0.0 - Math.IEEERemainder((double)num3 + (double)screenPosition.X * bgParallax, num3) - (double)(num3 / 2)) - (int)vector.X;
             bgLoops = (screenWidth + (int)vector.X * 2) / num3 + 2;
             if (rockLayer * 16.0 + (double)screenHeight < (double)(screenPosition.Y - 16f))
             {
                 bgStartY = (int)(Math.IEEERemainder(bgTopY, backgroundHeight[3]) - (double)backgroundHeight[3]);
                 bgLoopsY = (screenHeight - bgStartY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
             }
             else
             {
                 bgStartY = bgTopY;
                 bgLoopsY = (screenHeight - bgTopY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
             }
             if (num16 * 16.0 < (double)(screenPosition.Y + 600f))
             {
                 bgLoopsY = (int)(num16 * 16.0 - (double)screenPosition.Y + 600.0 - (double)bgStartY) / backgroundHeight[2];
                 flag = true;
             }
             int num42 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
             if (num42 == -8)
             {
                 num42 = 8;
             }
             for (int num43 = 0; num43 < bgLoops; num43++)
             {
                 for (int num44 = 0; num44 < bgLoopsY; num44++)
                 {
                     for (int num45 = 0; num45 < num3 / 16; num45++)
                     {
                         for (int num46 = 0; num46 < 6; num46++)
{
                             float num47 = bgStartY + num44 * 96 + num46 * 16 + 8;
                             int num48 = (int)(((float)(bgStartX + num3 * num43 + num45 * 16 + 8) + screenPosition.X) / 16f);
                             int num49 = (int)((num47 + screenPosition.Y) / 16f);
                             Microsoft.Xna.Framework.Color color14 = Lighting.GetColor(num48, num49);
                             if ((!ShouldDrawBackgroundTileAt(num48, num49) && color14.R != 0 && color14.G != 0 && color14.B != 0) || (color14.R <= 0 && color14.G <= 0 && color14.B <= 0) || (!WallLightAt(num48, num49) && caveParallax == 0f))
{
                                 continue;
                             }
                             if (Lighting.NotRetro && color14.R < 230 && color14.G < 230 && color14.B < 230 && ugBackTransition == 0f)
{
                                 if ((color14.R > num || (double)(int)color14.G > (double)num * 1.1 || (double)(int)color14.B > (double)num * 1.2) && !tile[num48, num49].active())
{
                                     Lighting.GetColor9Slice(num48, num49, ref slices);
                                     for (int num50 = 0; num50 < 9; num50++)
{
                                         int num51 = 0;
                                         int num52 = 0;
                                         int width2 = 4;
                                         int height2 = 4;
                                         Microsoft.Xna.Framework.Color color15 = color14;
                                         Microsoft.Xna.Framework.Color color16 = color14;
                                         switch (num50)
{
                                         case 0:
                                             if (!tile[num48 - 1, num49 - 1].active())
{
                                                 color16 = slices[num50];
                                             }
                                             break;
                                         case 1:
                                             width2 = 8;
                                             num51 = 4;
                                             if (!tile[num48, num49 - 1].active())
{
                                                 color16 = slices[num50];
                                             }
                                             break;
                                         case 2:
                                             num51 = 12;
                                             if (!tile[num48 + 1, num49 - 1].active())
{
                                                 color16 = slices[num50];
                                             }
                                             break;
                                         case 3:
                                             height2 = 8;
                                             num52 = 4;
                                             if (!tile[num48 - 1, num49].active())
{
                                                 color16 = slices[num50];
                                             }
                                             break;
                                         case 4:
                                             width2 = 8;
                                             height2 = 8;
                                             num51 = 4;
                                             num52 = 4;
                                             break;
                                         case 5:
                                             num51 = 12;
                                             num52 = 4;
                                             height2 = 8;
                                             if (!tile[num48 + 1, num49].active())
{
                                                 color16 = slices[num50];
                                             }
                                             break;
                                         case 6:
                                             num52 = 12;
                                             if (!tile[num48 - 1, num49 + 1].active())
{
                                                 color16 = slices[num50];
                                             }
                                             break;
                                         case 7:
                                             width2 = 8;
                                             height2 = 4;
                                             num51 = 4;
                                             num52 = 12;
                                             if (!tile[num48, num49 + 1].active())
{
                                                 color16 = slices[num50];
                                             }
                                             break;
                                         case 8:
                                             num51 = 12;
                                             num52 = 12;
                                             if (!tile[num48 + 1, num49 + 1].active())
{
                                                 color16 = slices[num50];
                                             }
                                             break;
                                         }
                                         color15.R = (byte)((color14.R + color16.R) / 2);
                                         color15.G = (byte)((color14.G + color16.G) / 2);
                                         color15.B = (byte)((color14.B + color16.B) / 2);
                                         color15.R = (byte)((float)(int)color15.R * num4);
                                         color15.G = (byte)((float)(int)color15.G * num5);
                                         color15.B = (byte)((float)(int)color15.B * num6);
                                         spriteBatch.Draw(TextureAssets.Background[array[3]].Value, new Vector2(bgStartX + num3 * num43 + 16 * num45 + num51 + num42, bgStartY + backgroundHeight[array[3]] * num44 + 16 * num46 + num52) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num45 + num51 + num42 + 16, 16 * num46 + num52, width2, height2), color15);
                                         if (ugBackTransition > 0f)
{
                                             Microsoft.Xna.Framework.Color color17 = color15;
                                             color17.R = (byte)((float)(int)color17.R * ugBackTransition);
                                             color17.G = (byte)((float)(int)color17.G * ugBackTransition);
                                             color17.B = (byte)((float)(int)color17.B * ugBackTransition);
                                             color17.A = (byte)((float)(int)color17.A * ugBackTransition);
                                             spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2(bgStartX + num3 * num43 + 16 * num45 + num51 + num42, bgStartY + backgroundHeight[array2[3]] * num44 + 16 * num46 + num52) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num45 + num51 + num42 + 16, 16 * num46 + num52, width2, height2), color17);
                                         }
                                     }
                                 }
                                 else if (color14.R > num2 || (double)(int)color14.G > (double)num2 * 1.1 || (double)(int)color14.B > (double)num2 * 1.2)
{
                                     Lighting.GetColor4Slice(num48, num49, ref slices);
                                     for (int num53 = 0; num53 < 4; num53++)
{
                                         int num54 = 0;
                                         int num55 = 0;
                                         Microsoft.Xna.Framework.Color color18 = color14;
                                         Microsoft.Xna.Framework.Color color19 = slices[num53];
                                         switch (num53)
{
                                         case 1:
                                             num54 = 8;
                                             break;
                                         case 2:
                                             num55 = 8;
                                             break;
                                         case 3:
                                             num54 = 8;
                                             num55 = 8;
                                             break;
                                         }
                                         color18.R = (byte)((color14.R + color19.R) / 2);
                                         color18.G = (byte)((color14.G + color19.G) / 2);
                                         color18.B = (byte)((color14.B + color19.B) / 2);
                                         color18.R = (byte)((float)(int)color18.R * num4);
                                         color18.G = (byte)((float)(int)color18.G * num5);
                                         color18.B = (byte)((float)(int)color18.B * num6);
                                         spriteBatch.Draw(TextureAssets.Background[array[3]].Value, new Vector2(bgStartX + num3 * num43 + 16 * num45 + num54 + num42, bgStartY + backgroundHeight[array[3]] * num44 + 16 * num46 + num55) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num45 + num54 + num42 + 16, 16 * num46 + num55, 8, 8), color18);
                                         if (ugBackTransition > 0f)
{
                                             Microsoft.Xna.Framework.Color color20 = color18;
                                             color20.R = (byte)((float)(int)color20.R * ugBackTransition);
                                             color20.G = (byte)((float)(int)color20.G * ugBackTransition);
                                             color20.B = (byte)((float)(int)color20.B * ugBackTransition);
                                             color20.A = (byte)((float)(int)color20.A * ugBackTransition);
                                             spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2(bgStartX + num3 * num43 + 16 * num45 + num54 + num42, bgStartY + backgroundHeight[array2[3]] * num44 + 16 * num46 + num55) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num45 + num54 + num42 + 16, 16 * num46 + num55, 8, 8), color20);
                                         }
                                     }
                                 }
                                 else
{
                                     color14.R = (byte)((float)(int)color14.R * num4);
                                     color14.G = (byte)((float)(int)color14.G * num5);
                                     color14.B = (byte)((float)(int)color14.B * num6);
                                     spriteBatch.Draw(TextureAssets.Background[array[3]].Value, new Vector2(bgStartX + num3 * num43 + 16 * num45 + num42, bgStartY + backgroundHeight[array[3]] * num44 + 16 * num46) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num45 + num42 + 16, 16 * num46, 16, 16), color14);
                                     if (ugBackTransition > 0f)
{
                                         Microsoft.Xna.Framework.Color color21 = color14;
                                         color21.R = (byte)((float)(int)color21.R * ugBackTransition);
                                         color21.G = (byte)((float)(int)color21.G * ugBackTransition);
                                         color21.B = (byte)((float)(int)color21.B * ugBackTransition);
                                         color21.A = (byte)((float)(int)color21.A * ugBackTransition);
                                         spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2(bgStartX + num3 * num43 + 16 * num45 + num42, bgStartY + backgroundHeight[array2[3]] * num44 + 16 * num46) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num45 + num42 + 16, 16 * num46, 16, 16), color21);
                                     }
                                 }
                             }
                             else
{
                                 color14.R = (byte)((float)(int)color14.R * num4);
                                 color14.G = (byte)((float)(int)color14.G * num5);
                                 color14.B = (byte)((float)(int)color14.B * num6);
                                 spriteBatch.Draw(TextureAssets.Background[array[3]].Value, new Vector2(bgStartX + num3 * num43 + 16 * num45 + num42, bgStartY + backgroundHeight[array[3]] * num44 + 16 * num46) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num45 + num42 + 16, 16 * num46, 16, 16), color14);
                                 if (ugBackTransition > 0f)
{
                                     Microsoft.Xna.Framework.Color color22 = color14;
                                     color22.R = (byte)((float)(int)color22.R * ugBackTransition);
                                     color22.G = (byte)((float)(int)color22.G * ugBackTransition);
                                     color22.B = (byte)((float)(int)color22.B * ugBackTransition);
                                     color22.A = (byte)((float)(int)color22.A * ugBackTransition);
                                     spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2(bgStartX + num3 * num43 + 16 * num45 + num42, bgStartY + backgroundHeight[array2[3]] * num44 + 16 * num46) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num45 + num42 + 16, 16 * num46, 16, 16), color22);
                                 }
                             }
                         }
                     }
                 }
             }
             num3 = 128;
             if (flag)
             {
                 bgParallax = caveParallax;
                 bgStartX = (int)(0.0 - Math.IEEERemainder((double)num3 + (double)screenPosition.X * bgParallax, num3) - (double)(num3 / 2)) - (int)vector.X;
                 bgLoops = (screenWidth + (int)vector.X * 2) / num3 + 2;
                 bgTopY = bgStartY + bgLoopsY * backgroundHeight[2];
                 for (int num56 = 0; num56 < bgLoops; num56++)
                 {
                     for (int num57 = 0; num57 < num3 / 16; num57++)
                     {
                         float num58 = bgStartX + num3 * num56 + num57 * 16 + 8;
                         float num59 = bgTopY;
                         Microsoft.Xna.Framework.Color color23 = Lighting.GetColor((int)((num58 + screenPosition.X) / 16f), (int)((screenPosition.Y + num59) / 16f));
                         color23.R = (byte)((float)(int)color23.R * num4);
                         color23.G = (byte)((float)(int)color23.G * num5);
                         color23.B = (byte)((float)(int)color23.B * num6);
                         spriteBatch.Draw(TextureAssets.Background[array[4]].Value, new Vector2(bgStartX + num3 * num56 + 16 * num57 + num42, bgTopY) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num57 + num42 + 16, magmaBGFrame * 16, 16, 16), color23);
                         if (ugBackTransition > 0f)
{
                             Microsoft.Xna.Framework.Color color24 = color23;
                             color24.R = (byte)((float)(int)color24.R * ugBackTransition);
                             color24.G = (byte)((float)(int)color24.G * ugBackTransition);
                             color24.B = (byte)((float)(int)color24.B * ugBackTransition);
                             color24.A = (byte)((float)(int)color24.A * ugBackTransition);
                             spriteBatch.Draw(TextureAssets.Background[array2[4]].Value, new Vector2(bgStartX + num3 * num56 + 16 * num57 + num42, bgTopY) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num57 + num42 + 16, magmaBGFrame * 16, 16, 16), color24);
                         }
                     }
                 }
             }
         }
         bgTopY = (int)((float)((int)num16 * 16) - screenPosition.Y + 16f + 600f) - 8;
         if (num16 * 16.0 <= (double)(screenPosition.Y + 600f))
         {
             bgStartX = (int)(0.0 - Math.IEEERemainder((double)num3 + (double)screenPosition.X * bgParallax, num3) - (double)(num3 / 2)) - (int)vector.X;
             bgLoops = (screenWidth + (int)vector.X * 2) / num3 + 2;
             if (num16 * 16.0 + (double)screenHeight < (double)(screenPosition.Y - 16f))
             {
                 bgStartY = (int)(Math.IEEERemainder(bgTopY, backgroundHeight[2]) - (double)backgroundHeight[2]);
                 bgLoopsY = (screenHeight - bgStartY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
             }
             else
             {
                 bgStartY = bgTopY;
                 bgLoopsY = (screenHeight - bgTopY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
             }
             num = (int)((double)num * 1.5);
             num2 = (int)((double)num2 * 1.5);
             int num60 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
             if (num60 == -8)
             {
                 num60 = 8;
             }
             for (int num61 = 0; num61 < bgLoops; num61++)
             {
                 for (int num62 = 0; num62 < bgLoopsY; num62++)
                 {
                     for (int num63 = 0; num63 < num3 / 16; num63++)
                     {
                         for (int num64 = 0; num64 < 6; num64++)
{
                             float num65 = bgStartY + num62 * 96 + num64 * 16 + 8;
                             int num66 = (int)(((float)(bgStartX + num3 * num61 + num63 * 16 + 8) + screenPosition.X) / 16f);
                             int num67 = (int)((num65 + screenPosition.Y) / 16f);
                             Microsoft.Xna.Framework.Color color25 = Lighting.GetColor(num66, num67);
                             if ((!ShouldDrawBackgroundTileAt(num66, num67) && color25.R != 0 && color25.G != 0 && color25.B != 0) || (color25.R <= 0 && color25.G <= 0 && color25.B <= 0) || (!WallLightAt(num66, num67) && caveParallax == 0f))
{
                                 continue;
                             }
                             if (Lighting.NotRetro && color25.R < 230 && color25.G < 230 && color25.B < 230)
{
                                 if ((color25.R > num || (double)(int)color25.G > (double)num * 1.1 || (double)(int)color25.B > (double)num * 1.2) && !tile[num66, num67].active())
{
                                     Lighting.GetColor9Slice(num66, num67, ref slices);
                                     for (int num68 = 0; num68 < 9; num68++)
{
                                         int num69 = 0;
                                         int num70 = 0;
                                         int width3 = 4;
                                         int height3 = 4;
                                         Microsoft.Xna.Framework.Color color26 = color25;
                                         Microsoft.Xna.Framework.Color color27 = color25;
                                         switch (num68)
{
                                         case 0:
                                             if (!tile[num66 - 1, num67 - 1].active())
{
                                                 color27 = slices[num68];
                                             }
                                             break;
                                         case 1:
                                             width3 = 8;
                                             num69 = 4;
                                             if (!tile[num66, num67 - 1].active())
{
                                                 color27 = slices[num68];
                                             }
                                             break;
                                         case 2:
                                             num69 = 12;
                                             if (!tile[num66 + 1, num67 - 1].active())
{
                                                 color27 = slices[num68];
                                             }
                                             break;
                                         case 3:
                                             height3 = 8;
                                             num70 = 4;
                                             if (!tile[num66 - 1, num67].active())
{
                                                 color27 = slices[num68];
                                             }
                                             break;
                                         case 4:
                                             width3 = 8;
                                             height3 = 8;
                                             num69 = 4;
                                             num70 = 4;
                                             break;
                                         case 5:
                                             num69 = 12;
                                             num70 = 4;
                                             height3 = 8;
                                             if (!tile[num66 + 1, num67].active())
{
                                                 color27 = slices[num68];
                                             }
                                             break;
                                         case 6:
                                             num70 = 12;
                                             if (!tile[num66 - 1, num67 + 1].active())
{
                                                 color27 = slices[num68];
                                             }
                                             break;
                                         case 7:
                                             width3 = 8;
                                             height3 = 4;
                                             num69 = 4;
                                             num70 = 12;
                                             if (!tile[num66, num67 + 1].active())
{
                                                 color27 = slices[num68];
                                             }
                                             break;
                                         case 8:
                                             num69 = 12;
                                             num70 = 12;
                                             if (!tile[num66 + 1, num67 + 1].active())
{
                                                 color27 = slices[num68];
                                             }
                                             break;
                                         }
                                         color26.R = (byte)((color25.R + color27.R) / 2);
                                         color26.G = (byte)((color25.G + color27.G) / 2);
                                         color26.B = (byte)((color25.B + color27.B) / 2);
                                         color26.R = (byte)((float)(int)color26.R * num4);
                                         color26.G = (byte)((float)(int)color26.G * num5);
                                         color26.B = (byte)((float)(int)color26.B * num6);
                                         spriteBatch.Draw(TextureAssets.Background[array[5]].Value, new Vector2(bgStartX + num3 * num61 + 16 * num63 + num69 + num60, bgStartY + backgroundHeight[2] * num62 + 16 * num64 + num70) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num63 + num69 + num60 + 16, 16 * num64 + backgroundHeight[2] * magmaBGFrame + num70, width3, height3), color26, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                     }
                                 }
                                 else if (color25.R > num2 || (double)(int)color25.G > (double)num2 * 1.1 || (double)(int)color25.B > (double)num2 * 1.2)
{
                                     Lighting.GetColor4Slice(num66, num67, ref slices);
                                     for (int num71 = 0; num71 < 4; num71++)
{
                                         int num72 = 0;
                                         int num73 = 0;
                                         Microsoft.Xna.Framework.Color color28 = color25;
                                         Microsoft.Xna.Framework.Color color29 = slices[num71];
                                         switch (num71)
{
                                         case 1:
                                             num72 = 8;
                                             break;
                                         case 2:
                                             num73 = 8;
                                             break;
                                         case 3:
                                             num72 = 8;
                                             num73 = 8;
                                             break;
                                         }
                                         color28.R = (byte)((color25.R + color29.R) / 2);
                                         color28.G = (byte)((color25.G + color29.G) / 2);
                                         color28.B = (byte)((color25.B + color29.B) / 2);
                                         color28.R = (byte)((float)(int)color28.R * num4);
                                         color28.G = (byte)((float)(int)color28.G * num5);
                                         color28.B = (byte)((float)(int)color28.B * num6);
                                         spriteBatch.Draw(TextureAssets.Background[array[5]].Value, new Vector2(bgStartX + num3 * num61 + 16 * num63 + num72 + num60, bgStartY + backgroundHeight[2] * num62 + 16 * num64 + num73) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num63 + num72 + num60 + 16, 16 * num64 + backgroundHeight[2] * magmaBGFrame + num73, 8, 8), color28, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                     }
                                 }
                                 else
{
                                     color25.R = (byte)((float)(int)color25.R * num4);
                                     color25.G = (byte)((float)(int)color25.G * num5);
                                     color25.B = (byte)((float)(int)color25.B * num6);
                                     spriteBatch.Draw(TextureAssets.Background[array[5]].Value, new Vector2(bgStartX + num3 * num61 + 16 * num63 + num60, bgStartY + backgroundHeight[2] * num62 + 16 * num64) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num63 + num60 + 16, 16 * num64 + backgroundHeight[2] * magmaBGFrame, 16, 16), color25, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                                 }
                             }
                             else
{
                                 color25.R = (byte)((float)(int)color25.R * num4);
                                 color25.G = (byte)((float)(int)color25.G * num5);
                                 color25.B = (byte)((float)(int)color25.B * num6);
                                 spriteBatch.Draw(TextureAssets.Background[array[5]].Value, new Vector2(bgStartX + num3 * num61 + 16 * num63 + num60, bgStartY + backgroundHeight[2] * num62 + 16 * num64) + vector, new Microsoft.Xna.Framework.Rectangle(16 * num63 + num60 + 16, 16 * num64 + backgroundHeight[2] * magmaBGFrame, 16, 16), color25, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                             }
                         }
                     }
                 }
             }
         }
         Lighting.GlobalBrightness = globalBrightness;
         TimeLogger.DrawTime(3, stopwatch.Elapsed.TotalMilliseconds);
     }
References Tile.active(), TextureAssets.Background, backgroundHeight, bgLoops, bgLoopsY, bgParallax, bgStartX, bgStartY, bgTopY, SceneMetrics.BloodTileCount, caveBackStyle, caveBackX, caveParallax, TileBatch.Draw(), TimeLogger.DrawTime(), drawToScreen, SceneMetrics.EnoughTilesForGlowingMushroom, SceneMetrics.EvilTileCount, Lighting.GetColor(), Lighting.GetColor4Slice(), Lighting.GetColor9Slice(), Lighting.GetCornerColors(), gfxQuality, Lighting.GlobalBrightness, hellBackStyle, SceneMetrics.HolyTileCount, iceBackStyle, jungleBackStyle, SceneMetrics.JungleTileCount, SceneMetrics.JungleTileThreshold, LoadBackground(), magmaBGFrame, maxTilesY, Lighting.NotRetro, offScreenRange, oldUndergroundBackground, rockLayer, Camera.ScaledPosition, screenHeight, screenPosition, screenWidth, ShouldDrawBackgroundTileAt(), SceneMetrics.SnowTileCount, SceneMetrics.SnowTileThreshold, spriteBatch, Tile, tile, tileBatch, ugBackTransition, undergroundBackground, Asset< T >.Value, WallLightAt(), and worldSurface.
Referenced by DrawBackground().