Terraria: Main.snowing
snowing()
static void Main.snowing () inline static
     {
         if (remixWorld)
         {
             return;
         }
         Vector2 scaledSize = Camera.ScaledSize;
         Vector2 scaledPosition = Camera.ScaledPosition;
         if (gamePaused || SceneMetrics.SnowTileCount <= 0 || (!((double)player[myPlayer].position.Y < worldSurface * 16.0) && (!remixWorld || !((double)player[myPlayer].position.Y > worldSurface * 16.0))))
         {
             return;
         }
         float num = (float)SceneMetrics.SnowTileCount / (float)SceneMetrics.SnowTileMax;
         num *= num;
         num *= num;
         float num2 = Camera.ScaledSize.X / (float)maxScreenW;
         int num3 = (int)(500f * num2);
         num3 = (int)((float)num3 * (1f + 2f * cloudAlpha));
         float num4 = 1f + 50f * cloudAlpha;
         bool flag = NPC.IsADeerclopsNearScreen();
         if (flag)
         {
             num /= 20f;
             num3 /= 3;
         }
         for (int i = 0; (float)i < num4; i++)
         {
             try
             {
                 if (!((float)snowDust < (float)num3 * (gfxQuality / 2f + 0.5f) + (float)num3 * 0.1f))
                 {
                     break;
                 }
                 if (!(rand.NextFloat() < num))
                 {
                     continue;
                 }
                 int num5 = rand.Next((int)scaledSize.X + 1500) - 750;
                 int num6 = (int)scaledPosition.Y - rand.Next(50);
                 if (player[myPlayer].velocity.Y > 0f)
                 {
                     num6 -= (int)player[myPlayer].velocity.Y;
                 }
                 if (rand.Next(5) == 0)
                 {
                     num5 = rand.Next(500) - 500;
                 }
                 else if (rand.Next(5) == 0)
                 {
                     num5 = rand.Next(500) + (int)scaledSize.X;
                 }
                 if (num5 < 0 || (float)num5 > scaledSize.X)
                 {
                     num6 += rand.Next((int)((double)scaledSize.Y * 0.8)) + (int)((double)scaledSize.Y * 0.1);
                 }
                 num5 += (int)scaledPosition.X;
                 int num7 = num5 / 16;
                 int num8 = num6 / 16;
                 if (WorldGen.InWorld(num7, num8) && tile[num7, num8] != null && !tile[num7, num8].nactive() && tile[num7, num8].wall == 0)
                 {
                     int num9 = Dust.NewDust(new Vector2(num5, num6), 10, 10, 76);
                     dust[num9].scale += cloudAlpha * 0.2f;
                     dust[num9].velocity.Y = 3f + (float)rand.Next(30) * 0.1f;
                     dust[num9].velocity.Y *= dust[num9].scale;
                     if (!raining)
                     {
                         dust[num9].velocity.X = windSpeedCurrent + (float)rand.Next(-10, 10) * 0.1f;
                         dust[num9].velocity.X += windSpeedCurrent * 15f;
                     }
                     else
                     {
                         dust[num9].velocity.X = (float)Math.Sqrt(Math.Abs(windSpeedCurrent)) * (float)Math.Sign(windSpeedCurrent) * (cloudAlpha + 0.5f) * 10f + rand.NextFloat() * 0.2f - 0.1f;
                         dust[num9].velocity.Y *= 0.5f;
                     }
                     dust[num9].velocity.Y *= 1f + 0.3f * cloudAlpha;
                     dust[num9].scale += cloudAlpha * 0.2f;
                     if (flag)
                     {
                         dust[num9].scale -= 0.5f;
                     }
                     dust[num9].velocity *= 1f + cloudAlpha * 0.5f;
                 }
                 continue;
             }
             catch
             {
             }
         }
     }
References cloudAlpha, dust, gamePaused, gfxQuality, WorldGen.InWorld(), NPC.IsADeerclopsNearScreen(), maxScreenW, myPlayer, Tile.nactive(), Dust.NewDust(), UnifiedRandom.Next(), player, Entity.position, raining, rand, remixWorld, Dust.scale, Camera.ScaledPosition, Camera.ScaledSize, snowDust, SceneMetrics.SnowTileCount, SceneMetrics.SnowTileMax, tile, Dust.velocity, Tile.wall, windSpeedCurrent, and worldSurface.
Referenced by DoUpdate().