Terraria: Main.DrawTrail
DrawTrail()
static void Main.DrawTrail (Projectile proj, Vector2 rotatableOffsetFromCenter, Microsoft.Xna.Framework.Color baseColor) inline static private
     {
         Vector2 vector = proj.Size / 2f;
         Texture2D value = TextureAssets.MagicPixel.Value;
         Microsoft.Xna.Framework.Rectangle value2 = new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1);
         Vector2[] oldPos = proj.oldPos;
         float[] oldRot = proj.oldRot;
         int num = oldPos.Length;
         for (int num2 = num - 1; num2 > 0; num2--)
         {
             if (!(oldPos[num2] == Vector2.Zero))
             {
                 Vector2 vector2 = oldPos[num2] + vector + rotatableOffsetFromCenter.RotatedBy(oldRot[num2]);
                 Vector2 v = oldPos[num2 - 1] + vector + rotatableOffsetFromCenter.RotatedBy(oldRot[num2 - 1]) - vector2;
                 float y = v.Length();
                 float num3 = v.ToRotation();
                 float num4 = Utils.Remap(num2, 0f, num, 1f, 0f);
                 EntitySpriteDraw(value, vector2 - screenPosition, value2, baseColor * num4, num3 + (float)Math.PI / 2f, new Vector2((float)value2.Width / 2f, value2.Height), new Vector2(4f, y), SpriteEffects.None);
             }
         }
     }
References EntitySpriteDraw(), TextureAssets.MagicPixel, Projectile.oldPos, Projectile.oldRot, Utils.Remap(), screenPosition, Entity.Size, and Asset< T >.Value.
Referenced by DrawContinuousTrail().