Terraria: Main.CheckMonoliths
CheckMonoliths()
static void Main.CheckMonoliths () inline static private
     {
         if (dedServ)
         {
             return;
         }
         bool flag = player[myPlayer].ZoneTowerVortex || player[myPlayer].ZoneTowerNebula || player[myPlayer].ZoneTowerStardust || player[myPlayer].ZoneTowerSolar;
         bool stardustMonolithShader = player[myPlayer].stardustMonolithShader;
         bool nebulaMonolithShader = player[myPlayer].nebulaMonolithShader;
         bool vortexMonolithShader = player[myPlayer].vortexMonolithShader;
         bool solarMonolithShader = player[myPlayer].solarMonolithShader;
         bool moonLordMonolithShader = player[myPlayer].moonLordMonolithShader;
         for (int i = 0; i < MonolithFilterNames.Length; i++)
         {
             bool flag2 = !flag && i == SceneMetrics.ActiveMonolithType;
             if ((i == 0 && vortexMonolithShader) || (i == 1 && nebulaMonolithShader) || (i == 2 && stardustMonolithShader) || (i == 3 && solarMonolithShader) || (i == 4 && moonLordMonolithShader))
             {
                 flag2 = true;
             }
             if (flag2)
             {
                 if (!Terraria.Graphics.Effects.Filters.Scene[MonolithFilterNames[i]].IsActive())
                 {
                     Terraria.Graphics.Effects.Filters.Scene.Activate(MonolithFilterNames[i], default(Vector2));
                 }
                 if (!SkyManager.Instance[MonolithSkyNames[i]].IsActive())
                 {
                     SkyManager.Instance.Activate(MonolithSkyNames[i], default(Vector2));
                 }
             }
             else
             {
                 if (Terraria.Graphics.Effects.Filters.Scene[MonolithFilterNames[i]].IsActive())
                 {
                     Terraria.Graphics.Effects.Filters.Scene.Deactivate(MonolithFilterNames[i]);
                 }
                 if (SkyManager.Instance[MonolithSkyNames[i]].IsActive())
                 {
                     SkyManager.Instance.Deactivate(MonolithSkyNames[i]);
                 }
             }
         }
     }
References EffectManager< T >.Activate(), SceneMetrics.ActiveMonolithType, EffectManager< T >.Deactivate(), dedServ, SkyManager.Instance, MonolithFilterNames, MonolithSkyNames, Player.moonLordMonolithShader, myPlayer, Player.nebulaMonolithShader, player, Player.solarMonolithShader, Player.stardustMonolithShader, Player.vortexMonolithShader, Player.ZoneTowerNebula, Player.ZoneTowerSolar, Player.ZoneTowerStardust, and Player.ZoneTowerVortex.
Referenced by DoDraw().