Terraria: Main.DrawSurfaceBG_Mushroom
DrawSurfaceBG_Mushroom()
void Main.DrawSurfaceBG_Mushroom (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
     {
         float num = 0.33f;
         Vector3 vector = new Vector3(0.1f, 0.15f, 0.3f);
         float num2 = 0.5f;
         Vector3 vector2 = new Vector3(0.1f, 0.175f, 0.3f);
         float num3 = 0.75f;
         Vector3 vector3 = new Vector3(0.125f, 0.2f, 0.3f);
         num = 0.5f;
         num2 = 0.625f;
         num3 = 0.75f;
         vector *= 3f;
         vector2 *= 3f;
         vector3 *= 3f;
         float num4 = (float)(int)ColorOfSurfaceBackgroundsModified.A / 255f;
         Microsoft.Xna.Framework.Color colorOfSurfaceBackgroundsModified = ColorOfSurfaceBackgroundsModified;
         float num5 = (float)rand.Next(28, 42) * 0.001f;
         num5 += (float)(270 - mouseTextColor) / 5000f;
         float x = vector.X;
         float num6 = vector.Y + num5 / 2f;
         float num7 = vector.Z + num5;
         x *= 255f;
         num6 *= 255f;
         num7 *= 255f;
         x *= num * num4;
         num6 *= num * num4;
         num7 *= num * num4;
         if (x > 255f)
         {
             x = 255f;
         }
         if (num6 > 255f)
         {
             num6 = 255f;
         }
         if (num7 > 255f)
         {
             num7 = 255f;
         }
         if (x > (float)(int)colorOfSurfaceBackgroundsModified.R)
         {
             colorOfSurfaceBackgroundsModified.R = (byte)x;
         }
         if (num6 > (float)(int)colorOfSurfaceBackgroundsModified.G)
         {
             colorOfSurfaceBackgroundsModified.G = (byte)num6;
         }
         if (num7 > (float)(int)colorOfSurfaceBackgroundsModified.B)
         {
             colorOfSurfaceBackgroundsModified.B = (byte)num7;
         }
         bgScale = 1.25f;
         bgScale *= bgGlobalScaleMultiplier;
         LoadBackground(bgTexIndexes[0]);
         bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[0]] * bgScale);
         bgParallax = 0.4;
         SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
         SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
         bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
         bgTopY = (int)(backgroundTopMagicNumber * 1800.0 + 1400.0) + (int)scAdj + pushBGTopHack;
         SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
         if (gameMenu)
         {
             bgTopY = 320 + pushBGTopHack;
         }
         if (bgWidthScaled != 0)
         {
             bgLoops = screenWidth / bgWidthScaled + 2;
         }
         if (TextureAssets.Background[bgTexIndexes[0]].Value == null)
         {
             return;
         }
         if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
         {
             for (int i = 0; i < bgLoops; i++)
             {
                 spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[0]].Value, new Vector2(bgStartX + bgWidthScaled * i, bgTopY), GetBackgroundRect(bgTexIndexes[0]), colorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
             }
         }
         colorOfSurfaceBackgroundsModified = ColorOfSurfaceBackgroundsModified;
         num5 = (float)rand.Next(28, 42) * 0.001f;
         num5 += (float)(270 - mouseTextColor) / 5000f;
         x = vector2.X;
         num6 = vector2.Y + num5 / 2f;
         num7 = vector2.Z + num5;
         x *= 255f;
         num6 *= 255f;
         num7 *= 255f;
         x *= num2 * num4;
         num6 *= num2 * num4;
         num7 *= num2 * num4;
         if (x > 255f)
         {
             x = 255f;
         }
         if (num6 > 255f)
         {
             num6 = 255f;
         }
         if (num7 > 255f)
         {
             num7 = 255f;
         }
         if (x > (float)(int)colorOfSurfaceBackgroundsModified.R)
         {
             colorOfSurfaceBackgroundsModified.R = (byte)x;
         }
         if (num6 > (float)(int)colorOfSurfaceBackgroundsModified.G)
         {
             colorOfSurfaceBackgroundsModified.G = (byte)num6;
         }
         if (num7 > (float)(int)colorOfSurfaceBackgroundsModified.B)
         {
             colorOfSurfaceBackgroundsModified.B = (byte)num7;
         }
         bgScale = 1.32f;
         bgScale *= bgGlobalScaleMultiplier;
         LoadBackground(bgTexIndexes[1]);
         bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[1]] * bgScale);
         bgParallax = 0.43;
         SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
         SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
         bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
         bgTopY = (int)(backgroundTopMagicNumber * 1950.0 + 1675.0) + (int)scAdj + pushBGTopHack;
         SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
         if (gameMenu)
         {
             bgTopY = 400 + pushBGTopHack;
             bgStartX -= 80;
         }
         if (bgWidthScaled == 0)
         {
             return;
         }
         bgLoops = screenWidth / bgWidthScaled + 2;
         if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
         {
             for (int j = 0; j < bgLoops; j++)
             {
                 spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2(bgStartX + bgWidthScaled * j, bgTopY), GetBackgroundRect(bgTexIndexes[1]), colorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
             }
         }
         colorOfSurfaceBackgroundsModified = ColorOfSurfaceBackgroundsModified;
         num5 = (float)rand.Next(28, 42) * 0.001f;
         num5 += (float)(270 - mouseTextColor) / 3000f;
         x = vector3.X;
         num6 = vector3.Y + num5 / 2f;
         num7 = vector3.Z + num5;
         x *= 255f * num4 * num3;
         num6 *= 255f * num4 * num3;
         num7 *= 255f * num4 * num3;
         if (x > 255f)
         {
             x = 255f;
         }
         if (num6 > 255f)
         {
             num6 = 255f;
         }
         if (num7 > 255f)
         {
             num7 = 255f;
         }
         if (x > (float)(int)colorOfSurfaceBackgroundsModified.R)
         {
             colorOfSurfaceBackgroundsModified.R = (byte)x;
         }
         if (num6 > (float)(int)colorOfSurfaceBackgroundsModified.G)
         {
             colorOfSurfaceBackgroundsModified.G = (byte)num6;
         }
         if (num7 > (float)(int)colorOfSurfaceBackgroundsModified.B)
         {
             colorOfSurfaceBackgroundsModified.B = (byte)num7;
         }
         bgScale = 1.36f;
         bgScale *= bgGlobalScaleMultiplier;
         LoadBackground(bgTexIndexes[2]);
         bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[2]] * bgScale);
         bgParallax = 0.49;
         SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
         SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
         bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
         bgTopY = (int)(backgroundTopMagicNumber * 2100.0 + 1950.0) + (int)scAdj + pushBGTopHack;
         SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
         if (gameMenu)
         {
             bgTopY = 480 + pushBGTopHack;
             bgStartX -= 120;
         }
         if (bgWidthScaled == 0)
         {
             return;
         }
         bgLoops = screenWidth / bgWidthScaled + 2;
         if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
         {
             for (int k = 0; k < bgLoops; k++)
             {
                 spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2(bgStartX + bgWidthScaled * k, bgTopY), GetBackgroundRect(bgTexIndexes[2]), colorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
             }
         }
         SkyManager.Instance.DrawToDepth(spriteBatch, 1f);
     }
References TextureAssets.Background, backgroundWidth, bgLoops, bgParallax, bgScale, bgStartX, bgTopY, bgWidthScaled, ColorOfSurfaceBackgroundsModified, SkyManager.DrawToDepth(), gameMenu, GetBackgroundRect(), SkyManager.Instance, LoadBackground(), mouseTextColor, UnifiedRandom.Next(), rand, scAdj, screenPosition, screenWidth, SetBackgroundOffsets(), spriteBatch, Asset< T >.Value, and worldSurface.
Referenced by DrawSurfaceBG().