Terraria: Main.InputTextSign
InputTextSign()
static void Main.InputTextSign () inline static
     {
         if (!IngameFancyUI.CanShowVirtualKeyboard(1) || UIVirtualKeyboard.KeyboardContext != 1)
         {
             PlayerInput.WritingText = true;
             instance.HandleIME();
             npcChatText = GetInputText(npcChatText, allowMultiLine: true);
             if (inputTextEnter)
             {
                 byte[] bytes = new byte[1] { 10 };
                 npcChatText += Encoding.ASCII.GetString(bytes);
             }
             else if (inputTextEscape)
             {
                 InputTextSignCancel();
             }
         }
     }
References IngameFancyUI.CanShowVirtualKeyboard(), GetInputText(), HandleIME(), inputTextEnter, inputTextEscape, InputTextSignCancel(), instance, UIVirtualKeyboard.KeyboardContext, npcChatText, and PlayerInput.WritingText.
Referenced by DoUpdate_WhilePaused(), and Player.Update().