Terraria: Main.DrawInterface_14_EntityHealthBars
DrawInterface_14_EntityHealthBars()
void Main.DrawInterface_14_EntityHealthBars () inline private
     {
         if (HealthBarDrawSettings == 0)
         {
             return;
         }
         int num = -1;
         if (PlayerInput.UsingGamepad)
         {
             Player localPlayer = LocalPlayer;
             for (int i = 0; i < 200; i++)
             {
                 NPC nPC = npc[i];
                 if ((nPC.life == nPC.lifeMax || nPC.dontTakeDamage) && !nPC.dontTakeDamage && nPC.nameOver > 0f && (num == -1 || nPC.Distance(localPlayer.Center) < npc[num].Distance(localPlayer.Center)))
                 {
                     num = i;
                 }
             }
         }
         bool flag = false;
         for (int num2 = 199; num2 >= 0; num2--)
         {
             if (npc[num2].active && npc[num2].type > 0 && npc[num2].shimmerTransparency == 0f)
             {
                 npc[num2].position += npc[num2].netOffset;
                 if (npc[num2].life != npc[num2].lifeMax && !npc[num2].dontTakeDamage)
                 {
                     float scale = 1f;
                     int type = npc[num2].type;
                     if (type == 4)
                     {
                         scale = 1.5f;
                     }
                     if (type == 35)
                     {
                         scale = 1.5f;
                     }
                     if (type == 36)
                     {
                         scale = 1.5f;
                     }
                     if (type == 50)
                     {
                         scale = 1.5f;
                     }
                     if (type == 113)
                     {
                         scale = 1.5f;
                     }
                     if (type == 114)
                     {
                         scale = 1.5f;
                     }
                     if (type == 125)
                     {
                         scale = 1.5f;
                     }
                     if (type == 126)
                     {
                         scale = 1.5f;
                     }
                     if (type == 127)
                     {
                         scale = 1.5f;
                     }
                     if (type == 128)
                     {
                         scale = 1.5f;
                     }
                     if (type == 129)
                     {
                         scale = 1.5f;
                     }
                     if (type == 130)
                     {
                         scale = 1.5f;
                     }
                     if (type == 131)
                     {
                         scale = 1.5f;
                     }
                     if (type == 222)
                     {
                         scale = 1.5f;
                     }
                     if (type >= 245 && type <= 249)
                     {
                         scale = 1.5f;
                     }
                     if (type == 262)
                     {
                         scale = 1.5f;
                     }
                     if (type == 266)
                     {
                         scale = 1.5f;
                     }
                     if (type == 564 || type == 565 || type == 551 || type == 576 || type == 577)
                     {
                         scale = 1.5f;
                     }
                     if (type == 87)
                     {
                         scale = 1.5f;
                     }
                     if (type == 510 || type == 454 || type == 621)
                     {
                         scale = 1.5f;
                     }
                     if (type == 439 || type == 370)
                     {
                         scale = 1.5f;
                     }
                     float num3 = 10f;
                     if (HealthBarDrawSettings == 2)
                     {
                         num3 -= 34f;
                     }
                     if ((!expertMode || type != 266) && ((type != 439 && type != 440) || npc[num2].ai[0] != 5f))
                     {
                         if (type >= 134 && type <= 136)
{
                             scale = 1.5f;
                             if (!flag)
{
                                 flag = true;
                                 Vector2 vector = default(Vector2);
                                 float num4 = 999999f;
                                 for (int j = 0; j < 200; j++)
{
                                     if (npc[j].active && npc[j].type >= 134 && npc[j].type <= 136)
{
                                         Vector2 vector2 = player[myPlayer].Center - npc[j].Center;
                                         if (vector2.Length() < num4 && Collision.CanHit(player[myPlayer].Center, 1, 1, npc[j].Center, 1, 1))
{
                                             num4 = vector2.Length();
                                             vector = npc[j].position;
                                         }
                                     }
                                 }
                                 if (num4 < (float)screenWidth)
{
                                     if (destroyerHB.X < 100f && destroyerHB.Y < 100f)
{
                                         destroyerHB = vector;
                                     }
                                     else
{
                                         destroyerHB = (destroyerHB * 49f + vector) / 50f;
                                     }
                                     vector = destroyerHB;
                                     int num5 = num2;
                                     if (type != 134 && npc[num2].realLife != -1)
{
                                         num5 = npc[num2].realLife;
                                     }
                                     float num6 = Lighting.Brightness((int)((npc[num2].position.X + (float)(npc[num2].width / 2)) / 16f), (int)((npc[num2].position.Y + (float)(npc[num2].height / 2) + npc[num2].gfxOffY) / 16f));
                                     num6 = (num6 + 1f) / 2f;
                                     DrawHealthBar(vector.X + (float)(npc[num2].width / 2), vector.Y + (float)(npc[num2].height / 2), npc[num5].life, npc[num5].lifeMax, num6, scale);
                                 }
                                 else
{
                                     destroyerHB = new Vector2(0f, 0f);
                                 }
                             }
                         }
                         else
{
                             switch (type)
{
                             case 7:
                                 DrawInterface_Healthbar_Worm(npc[num2], 9, scale);
                                 break;
                             case 95:
                                 DrawInterface_Healthbar_Worm(npc[num2], 97, scale);
                                 break;
                             case 10:
                                 DrawInterface_Healthbar_Worm(npc[num2], 12, scale);
                                 break;
                             case 87:
                                 DrawInterface_Healthbar_Worm(npc[num2], 92, scale);
                                 break;
                             default:
                                 switch (type)
{
                                 case 412:
                                     DrawInterface_Healthbar_Worm(npc[num2], 414, scale);
                                     break;
                                 case 39:
                                     DrawInterface_Healthbar_Worm(npc[num2], 41, scale);
                                     break;
                                 case 98:
                                     DrawInterface_Healthbar_Worm(npc[num2], 100, scale);
                                     break;
                                 case 454:
                                     DrawInterface_Healthbar_Worm(npc[num2], 459, scale);
                                     break;
                                 default:
                                     switch (type)
{
                                     case 510:
                                         DrawInterface_Healthbar_Worm(npc[num2], 512, scale);
                                         break;
                                     case 621:
                                         DrawInterface_Healthbar_Worm(npc[num2], 623, scale);
                                         break;
                                     case 513:
                                         DrawInterface_Healthbar_Worm(npc[num2], 515, scale);
                                         break;
                                     case 117:
                                         DrawInterface_Healthbar_Worm(npc[num2], 119, scale);
                                         break;
                                     default:
                                         if (HealthBarDrawSettings == 1)
{
                                             num3 += NPCAddHeight(npc[num2]);
                                             DrawHealthBar(npc[num2].position.X + (float)(npc[num2].width / 2), npc[num2].position.Y + (float)npc[num2].height + num3 + npc[num2].gfxOffY, npc[num2].life, npc[num2].lifeMax, Lighting.Brightness((int)((npc[num2].position.X + (float)(npc[num2].width / 2)) / 16f), (int)((npc[num2].position.Y + (float)(npc[num2].height / 2) + npc[num2].gfxOffY) / 16f)), scale);
                                         }
                                         else if (HealthBarDrawSettings == 2)
{
                                             num3 -= NPCAddHeight(npc[num2]) / 2f;
                                             DrawHealthBar(npc[num2].position.X + (float)(npc[num2].width / 2), npc[num2].position.Y + num3 + npc[num2].gfxOffY, npc[num2].life, npc[num2].lifeMax, Lighting.Brightness((int)((npc[num2].position.X + (float)(npc[num2].width / 2)) / 16f), (int)((npc[num2].position.Y + (float)(npc[num2].height / 2) + npc[num2].gfxOffY) / 16f)), scale);
                                         }
                                         break;
                                     case 118:
                                     case 119:
                                     case 511:
                                     case 512:
                                     case 514:
                                     case 515:
                                     case 622:
                                     case 623:
                                         break;
                                     }
                                     break;
                                 case 40:
                                 case 41:
                                 case 99:
                                 case 100:
                                 case 413:
                                 case 414:
                                 case 455:
                                 case 456:
                                 case 457:
                                 case 458:
                                 case 459:
                                     break;
                                 }
                                 break;
                             case 8:
                             case 9:
                             case 11:
                             case 12:
                             case 88:
                             case 89:
                             case 90:
                             case 91:
                             case 92:
                             case 96:
                             case 97:
                                 break;
                             }
                         }
                     }
                 }
                 else if (!npc[num2].dontTakeDamage && npc[num2].nameOver > 0f && PlayerInput.UsingGamepad && num2 == num)
                 {
                     Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, npc[num2].GivenOrTypeName, Vector2.One);
                     Vector2 vector3 = npc[num2].Bottom - screenPosition + new Vector2(0f, 10f);
                     if (NPC.GetNPCLocation(num2, seekHead: true, averageDirection: true, out var _, out var pos))
                     {
                         vector3 = pos - screenPosition + new Vector2(0f, 10 + npc[num2].height / 2);
                         if (player[myPlayer].gravDir == -1f)
{
                             vector3 = ReverseGravitySupport(vector3, -npc[num2].height - 20);
                         }
                         Vector2 origin = stringSize * new Vector2(0.5f, 0f);
                         ChatManager.DrawColorCodedStringShadow(spriteBatch, FontAssets.MouseText.Value, npc[num2].GivenOrTypeName, vector3, Microsoft.Xna.Framework.Color.Black * npc[num2].nameOver * 0.5f, 0f, origin, Vector2.One);
                         ChatManager.DrawColorCodedString(spriteBatch, FontAssets.MouseText.Value, npc[num2].GivenOrTypeName, vector3, Microsoft.Xna.Framework.Color.White * npc[num2].nameOver, 0f, origin, Vector2.One);
                     }
                 }
                 if (npc[num2].type == 548 && !npc[num2].dontTakeDamageFromHostiles && DD2Event.TimeLeftBetweenWaves > 0 && !hideUI)
                 {
                     Vector2 position = npc[num2].Bottom - screenPosition + new Vector2(0f, -100f);
                     int num7 = DD2Event.TimeLeftBetweenWaves / 60;
                     string text = $"{num7}";
                     DynamicSpriteFont value = FontAssets.MouseText.Value;
                     float num8 = 1f;
                     Vector2 origin2 = value.MeasureString(text) * num8 * new Vector2(0.5f, 0.5f);
                     ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, position, Microsoft.Xna.Framework.Color.White, 0f, origin2, Vector2.One * num8);
                 }
                 npc[num2].position -= npc[num2].netOffset;
             }
         }
         for (int k = 0; k < 255; k++)
         {
             if (k != myPlayer && player[k].active && !player[k].ghost && !player[k].dead && !player[k].invis && player[k].statLife != player[k].statLifeMax2)
             {
                 if (HealthBarDrawSettings == 1)
                 {
                     int num9 = 10;
                     DrawHealthBar(player[k].position.X + (float)(player[k].width / 2), player[k].position.Y + (float)player[k].height + (float)num9 + player[k].gfxOffY, player[k].statLife, player[k].statLifeMax2, player[k].stealth * Lighting.Brightness((int)((player[k].position.X + (float)(player[k].width / 2)) / 16f), (int)((player[k].position.Y + (float)(player[k].height / 2) + player[k].gfxOffY) / 16f)));
                 }
                 else if (HealthBarDrawSettings == 2)
                 {
                     int num10 = -20;
                     DrawHealthBar(player[k].position.X + (float)(player[k].width / 2), player[k].position.Y + (float)num10 + player[k].gfxOffY, player[k].statLife, player[k].statLifeMax2, player[k].stealth * Lighting.Brightness((int)((player[k].position.X + (float)(player[k].width / 2)) / 16f), (int)((player[k].position.Y + (float)(player[k].height / 2) + player[k].gfxOffY) / 16f)));
                 }
             }
         }
     }
References Entity.Bottom, Lighting.Brightness(), Collision.CanHit(), Entity.Center, destroyerHB, Entity.Distance(), NPC.dontTakeDamage, ChatManager.DrawColorCodedString(), ChatManager.DrawColorCodedStringShadow(), ChatManager.DrawColorCodedStringWithShadow(), DrawHealthBar(), DrawInterface_Healthbar_Worm(), expertMode, NPC.GetNPCLocation(), ChatManager.GetStringSize(), NPC.gfxOffY, Player.gfxOffY, NPC.GivenOrTypeName, HealthBarDrawSettings, Entity.height, hideUI, NPC.life, NPC.lifeMax, LocalPlayer, DynamicSpriteFont.MeasureString(), FontAssets.MouseText, myPlayer, NPC.nameOver, NPC.netOffset, npc, NPCAddHeight(), player, Entity.position, NPC.realLife, ReverseGravitySupport(), screenPosition, screenWidth, spriteBatch, Player.statLife, Player.statLifeMax2, Player.stealth, DD2Event.TimeLeftBetweenWaves, NPC.type, PlayerInput.UsingGamepad, Asset< T >.Value, and Entity.width.
Referenced by SetupDrawInterfaceLayers().