Terraria: Main.DrawInfoAccs
DrawInfoAccs()
void Main.DrawInfoAccs () inline private
     {
         if (!CanShowInfoAccs)
         {
             return;
         }
         bool flag = false;
         bool flag2 = false;
         bool flag3 = false;
         bool flag4 = false;
         bool flag5 = false;
         bool flag6 = false;
         bool flag7 = false;
         bool flag8 = false;
         bool flag9 = false;
         bool flag10 = false;
         bool flag11 = false;
         bool flag12 = false;
         int num = -1;
         int num2 = -10;
         int num3 = 0;
         string text = "";
         float num4 = 215f;
         int startX = 0;
         if (GameCulture.FromCultureName(GameCulture.CultureName.Russian).IsActive)
         {
             startX = -50;
             num4 += 50f;
         }
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(100, 100, 100, mouseTextColor);
         for (int i = 0; i < 12; i++)
         {
             string text2 = "";
             string text3 = "";
             Microsoft.Xna.Framework.Color infoTextColor = new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor);
             Microsoft.Xna.Framework.Color infoTextShadowColor = Microsoft.Xna.Framework.Color.Black;
             if (player[myPlayer].accWatch > 0 && !flag && (!player[myPlayer].hideInfo[0] || playerInventory))
             {
                 num = 0;
                 text3 = Lang.inter[95].Value;
                 string textValue = Language.GetTextValue("GameUI.TimeAtMorning");
                 double num5 = time;
                 if (!dayTime)
                 {
                     num5 += 54000.0;
                 }
                 num5 = num5 / 86400.0 * 24.0;
                 double num6 = 7.5;
                 num5 = num5 - num6 - 12.0;
                 if (num5 < 0.0)
                 {
                     num5 += 24.0;
                 }
                 if (num5 >= 12.0)
                 {
                     textValue = Language.GetTextValue("GameUI.TimePastMorning");
                 }
                 int num7 = (int)num5;
                 double num8 = num5 - (double)num7;
                 num8 = (int)(num8 * 60.0);
                 string text4 = string.Concat(num8);
                 if (num8 < 10.0)
                 {
                     text4 = "0" + text4;
                 }
                 if (num7 > 12)
                 {
                     num7 -= 12;
                 }
                 if (num7 == 0)
                 {
                     num7 = 12;
                 }
                 if (player[myPlayer].accWatch == 1)
                 {
                     text4 = "00";
                 }
                 else if (player[myPlayer].accWatch == 2)
                 {
                     text4 = ((!(num8 < 30.0)) ? "30" : "00");
                 }
                 text2 = num7 + ":" + text4 + " " + textValue;
                 flag = true;
             }
             else if (player[myPlayer].accWeatherRadio && !flag5 && (!player[myPlayer].hideInfo[1] || playerInventory))
             {
                 num = 1;
                 text3 = Lang.inter[96].Value;
                 string text5 = "";
                 text5 = (IsItStorming ? Language.GetTextValue("GameUI.Storm") : (((double)maxRaining > 0.6) ? Language.GetTextValue("GameUI.HeavyRain") : (((double)maxRaining >= 0.2) ? Language.GetTextValue("GameUI.Rain") : ((maxRaining > 0f) ? Language.GetTextValue("GameUI.LightRain") : ((cloudBGActive > 0f) ? Language.GetTextValue("GameUI.Overcast") : ((numClouds > 90) ? Language.GetTextValue("GameUI.MostlyCloudy") : ((numClouds > 55) ? Language.GetTextValue("GameUI.Cloudy") : ((numClouds <= 15) ? Language.GetTextValue("GameUI.Clear") : Language.GetTextValue("GameUI.PartlyCloudy")))))))));
                 text2 = text5;
                 int num9 = (int)(windSpeedCurrent * 50f);
                 if (num9 < 0)
                 {
                     text2 += Language.GetTextValue("GameUI.EastWind", Math.Abs(num9));
                 }
                 else if (num9 > 0)
                 {
                     text2 += Language.GetTextValue("GameUI.WestWind", num9);
                 }
                 if (Sandstorm.Happening)
                 {
                     if (GlobalTimeWrappedHourly % 10f >= 5f)
                     {
                         text2 = Language.GetTextValue("GameUI.Sandstorm");
                     }
                     text2 += " +";
                 }
                 flag5 = true;
             }
             else if (player[myPlayer].accCalendar && !flag8 && (!player[myPlayer].hideInfo[7] || playerInventory))
             {
                 num = ((bloodMoon && !dayTime) ? 8 : ((!eclipse || !dayTime) ? 7 : 8));
                 text3 = Lang.inter[102].Value;
                 if (moonPhase == 0)
                 {
                     text2 = Language.GetTextValue("GameUI.FullMoon");
                 }
                 else if (moonPhase == 1)
                 {
                     text2 = Language.GetTextValue("GameUI.WaningGibbous");
                 }
                 else if (moonPhase == 2)
                 {
                     text2 = Language.GetTextValue("GameUI.ThirdQuarter");
                 }
                 else if (moonPhase == 3)
                 {
                     text2 = Language.GetTextValue("GameUI.WaningCrescent");
                 }
                 else if (moonPhase == 4)
                 {
                     text2 = Language.GetTextValue("GameUI.NewMoon");
                 }
                 else if (moonPhase == 5)
                 {
                     text2 = Language.GetTextValue("GameUI.WaxingCrescent");
                 }
                 else if (moonPhase == 6)
                 {
                     text2 = Language.GetTextValue("GameUI.FirstQuarter");
                 }
                 else if (moonPhase == 7)
                 {
                     text2 = Language.GetTextValue("GameUI.WaxingGibbous");
                 }
                 flag8 = true;
             }
             else if (player[myPlayer].accFishFinder && !flag4 && (!player[myPlayer].hideInfo[2] || playerInventory))
             {
                 bool flag13 = false;
                 num = 2;
                 text3 = Lang.inter[97].Value;
                 for (int j = 0; j < 1000; j++)
                 {
                     if (projectile[j].active && projectile[j].owner == myPlayer && projectile[j].bobber)
                     {
                         flag13 = true;
                         break;
                     }
                 }
                 if (flag13)
                 {
                     text2 = player[myPlayer].displayedFishingInfo;
                 }
                 else
                 {
                     PlayerFishingConditions fishingConditions = player[myPlayer].GetFishingConditions();
                     text2 = ((fishingConditions.BaitItemType != 2673) ? (player[myPlayer].displayedFishingInfo = Language.GetTextValue("GameUI.FishingPower", fishingConditions.FinalFishingLevel)) : Language.GetTextValue("GameUI.FishingWarning"));
                 }
                 flag4 = true;
             }
             else if (player[myPlayer].accOreFinder && !flag10 && (!player[myPlayer].hideInfo[10] || playerInventory))
             {
                 num = 10;
                 text3 = Lang.inter[104].Value;
                 if (SceneMetrics.bestOre <= 0)
                 {
                     text2 = Language.GetTextValue("GameUI.NoTreasureNearby");
                     infoTextColor = color;
                 }
                 else
                 {
                     int baseOption = 0;
                     int num10 = SceneMetrics.bestOre;
                     if (SceneMetrics.ClosestOrePosition.HasValue)
                     {
                         Microsoft.Xna.Framework.Point value = SceneMetrics.ClosestOrePosition.Value;
                         Tile tileSafely = Framing.GetTileSafely(value);
                         if (tileSafely.active())
{
                             MapHelper.GetTileBaseOption(value.X, value.Y, tileSafely.type, tileSafely, ref baseOption);
                             num10 = tileSafely.type;
                             if (TileID.Sets.BasicChest[num10] || TileID.Sets.BasicChestFake[num10])
{
                                 baseOption = 0;
                             }
                         }
                     }
                     text2 = Language.GetTextValue("GameUI.OreDetected", Lang.GetMapObjectName(MapHelper.TileToLookup(num10, baseOption)));
                 }
                 flag10 = true;
             }
             else if (player[myPlayer].accCritterGuide && !flag11 && (!player[myPlayer].hideInfo[11] || playerInventory))
             {
                 flag11 = true;
                 num = 11;
                 text3 = Lang.inter[105].Value;
                 int num11 = 1300;
                 int num12 = 0;
                 int num13 = -1;
                 if (player[myPlayer].accCritterGuideCounter <= 0)
                 {
                     player[myPlayer].accCritterGuideCounter = 15;
                     for (int k = 0; k < 200; k++)
                     {
                         if (npc[k].active && npc[k].rarity > num12 && (npc[k].Center - player[myPlayer].Center).Length() < (float)num11)
{
                             num13 = k;
                             num12 = npc[k].rarity;
                         }
                     }
                     player[myPlayer].accCritterGuideNumber = (byte)num13;
                 }
                 else
                 {
                     player[myPlayer].accCritterGuideCounter--;
                     num13 = player[myPlayer].accCritterGuideNumber;
                 }
                 if (num13 >= 0 && num13 < 200 && npc[num13].active && npc[num13].rarity > 0)
                 {
                     text2 = npc[num13].GivenOrTypeName;
                     DrawInfoAccs_AdjustInfoTextColorsForNPC(npc[num13], ref infoTextColor, ref infoTextShadowColor);
                 }
                 else
                 {
                     text2 = Language.GetTextValue("GameUI.NoRareCreatures");
                     infoTextColor = color;
                 }
             }
             else if (player[myPlayer].accThirdEye && !flag6 && (!player[myPlayer].hideInfo[5] || playerInventory))
             {
                 flag6 = true;
                 num = 5;
                 text3 = Lang.inter[100].Value;
                 int num14 = 2000;
                 if (player[myPlayer].accThirdEyeCounter == 0)
                 {
                     player[myPlayer].accThirdEyeNumber = 0;
                     player[myPlayer].accThirdEyeCounter = 15;
                     for (int l = 0; l < 200; l++)
                     {
                         if (npc[l].active && !npc[l].friendly && npc[l].damage > 0 && npc[l].lifeMax > 5 && !npc[l].dontCountMe && (npc[l].Center - player[myPlayer].Center).Length() < (float)num14)
{
                             player[myPlayer].accThirdEyeNumber++;
                         }
                     }
                 }
                 else
                 {
                     player[myPlayer].accThirdEyeCounter--;
                 }
                 if (player[myPlayer].accThirdEyeNumber != 0)
                 {
                     text2 = ((player[myPlayer].accThirdEyeNumber != 1) ? Language.GetTextValue("GameUI.EnemiesNearby", player[myPlayer].accThirdEyeNumber) : Language.GetTextValue("GameUI.OneEnemyNearby"));
                 }
                 else
                 {
                     text2 = Language.GetTextValue("GameUI.NoEnemiesNearby");
                     infoTextColor = color;
                 }
             }
             else if (player[myPlayer].accJarOfSouls && !flag7 && (!player[myPlayer].hideInfo[6] || playerInventory))
             {
                 flag7 = true;
                 num = 6;
                 text3 = Lang.inter[101].Value;
                 int lastCreatureHit = player[myPlayer].lastCreatureHit;
                 if (lastCreatureHit <= 0)
                 {
                     text2 = Language.GetTextValue("GameUI.NoKillCount");
                     infoTextColor = color;
                 }
                 else
                 {
                     text2 = Lang.GetNPCNameValue(Item.BannerToNPC(lastCreatureHit)) + ": " + NPC.killCount[lastCreatureHit];
                 }
             }
             else if (player[myPlayer].accDreamCatcher && !flag12 && (!player[myPlayer].hideInfo[12] || playerInventory))
             {
                 num = 12;
                 text3 = Lang.inter[106].Value;
                 player[myPlayer].checkDPSTime();
                 int dPS = player[myPlayer].getDPS();
                 flag12 = true;
                 if (dPS == 0)
                 {
                     text2 = Language.GetTextValue("GameUI.NoDPS");
                     infoTextColor = color;
                 }
                 else
                 {
                     text2 = Language.GetTextValue("GameUI.DPS", player[myPlayer].getDPS());
                 }
             }
             else if (player[myPlayer].accStopwatch && !flag9 && (!player[myPlayer].hideInfo[9] || playerInventory))
             {
                 num = 9;
                 text3 = Lang.inter[103].Value;
                 Vector2 vector = player[myPlayer].velocity + player[myPlayer].instantMovementAccumulatedThisFrame;
                 if (player[myPlayer].mount.Active && player[myPlayer].mount.IsConsideredASlimeMount && player[myPlayer].velocity.Y != 0f && !player[myPlayer].SlimeDontHyperJump)
                 {
                     vector.Y += player[myPlayer].velocity.Y;
                 }
                 int num15 = (int)(1f + vector.Length() * 6f);
                 if (num15 > player[myPlayer].speedSlice.Length)
                 {
                     num15 = player[myPlayer].speedSlice.Length;
                 }
                 float num16 = 0f;
                 for (int num17 = num15 - 1; num17 > 0; num17--)
                 {
                     player[myPlayer].speedSlice[num17] = player[myPlayer].speedSlice[num17 - 1];
                 }
                 player[myPlayer].speedSlice[0] = vector.Length();
                 for (int m = 0; m < player[myPlayer].speedSlice.Length; m++)
                 {
                     if (m < num15)
                     {
                         num16 += player[myPlayer].speedSlice[m];
                     }
                     else
                     {
                         player[myPlayer].speedSlice[m] = num16 / (float)num15;
                     }
                 }
                 num16 /= (float)num15;
                 int num18 = 42240;
                 int num19 = 216000;
                 float num20 = num16 * (float)num19 / (float)num18;
                 if (!player[myPlayer].merman && !player[myPlayer].ignoreWater)
                 {
                     if (player[myPlayer].honeyWet)
                     {
                         num20 /= 4f;
                     }
                     else if (player[myPlayer].wet)
                     {
                         num20 /= 2f;
                     }
                 }
                 text2 = Language.GetTextValue("GameUI.Speed", Math.Round(num20));
                 flag9 = true;
             }
             else if (player[myPlayer].accCompass > 0 && !flag3 && (!player[myPlayer].hideInfo[3] || playerInventory))
             {
                 num = 3;
                 text3 = Lang.inter[98].Value;
                 int num21 = (int)((player[myPlayer].position.X + (float)(player[myPlayer].width / 2)) * 2f / 16f - (float)maxTilesX);
                 text2 = ((num21 > 0) ? Language.GetTextValue("GameUI.CompassEast", num21) : ((num21 >= 0) ? Language.GetTextValue("GameUI.CompassCenter") : Language.GetTextValue("GameUI.CompassWest", -num21)));
                 flag3 = true;
             }
             else if (player[myPlayer].accDepthMeter > 0 && !flag2 && (!player[myPlayer].hideInfo[4] || playerInventory))
             {
                 num = 4;
                 text3 = Lang.inter[99].Value;
                 int num22 = (int)((double)((player[myPlayer].position.Y + (float)player[myPlayer].height) * 2f / 16f) - worldSurface * 2.0);
                 string text6 = "";
                 float num23 = (float)maxTilesX / 4200f;
                 num23 *= num23;
                 int num24 = 1200;
                 float num25 = (float)((double)(player[myPlayer].Center.Y / 16f - (65f + 10f * num23)) / (worldSurface / 5.0));
                 text6 = ((player[myPlayer].position.Y > (float)((maxTilesY - 204) * 16)) ? Language.GetTextValue("GameUI.LayerUnderworld") : (((double)player[myPlayer].position.Y > rockLayer * 16.0 + (double)(num24 / 2) + 16.0) ? Language.GetTextValue("GameUI.LayerCaverns") : ((num22 > 0) ? Language.GetTextValue("GameUI.LayerUnderground") : ((!(num25 >= 1f)) ? Language.GetTextValue("GameUI.LayerSpace") : Language.GetTextValue("GameUI.LayerSurface")))));
                 string text7 = "";
                 num22 = Math.Abs(num22);
                 text7 = ((num22 != 0) ? Language.GetTextValue("GameUI.Depth", num22) : Language.GetTextValue("GameUI.DepthLevel"));
                 text2 = text7 + " " + text6;
                 flag2 = true;
             }
             if (!(text2 != ""))
             {
                 continue;
             }
             GetInfoAccIconPosition(num3, startX, out var X, out var Y);
             if (num >= 0)
             {
                 num3++;
                 int num26 = 22;
                 if (screenHeight < 650)
                 {
                     num26 = 20;
                 }
                 Vector2 vector2 = new Vector2(X, Y + 74 + num26 * i + 52);
                 int num27 = num;
                 if (num27 == 8)
                 {
                     num27 = 7;
                 }
                 Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.White;
                 bool flag14 = false;
                 if (playerInventory)
                 {
                     vector2 = new Vector2(X, Y);
                     if ((float)mouseX >= vector2.X && (float)mouseY >= vector2.Y && (float)mouseX <= vector2.X + (float)TextureAssets.InfoIcon[num].Width() && (float)mouseY <= vector2.Y + (float)TextureAssets.InfoIcon[num].Height() && !PlayerInput.IgnoreMouseInterface)
                     {
                         flag14 = true;
                         player[myPlayer].mouseInterface = true;
                         if (mouseLeft && mouseLeftRelease)
{
                             SoundEngine.PlaySound(12);
                             mouseLeftRelease = false;
                             player[myPlayer].hideInfo[num27] = !player[myPlayer].hideInfo[num27];
                         }
                         if (!mouseText)
{
                             text = text3;
                             mouseText = true;
                         }
                     }
                     if (player[myPlayer].hideInfo[num27])
                     {
                         color2 = new Microsoft.Xna.Framework.Color(80, 80, 80, 70);
                     }
                 }
                 else if ((float)mouseX >= vector2.X && (float)mouseY >= vector2.Y && (float)mouseX <= vector2.X + (float)TextureAssets.InfoIcon[num].Width() && (float)mouseY <= vector2.Y + (float)TextureAssets.InfoIcon[num].Height() && !mouseText)
                 {
                     num2 = i;
                     text = text3;
                     mouseText = true;
                 }
                 UILinkPointNavigator.SetPosition(1558 + num3 - 1, vector2 + TextureAssets.InfoIcon[num].Value.Size() * 0.75f);
                 spriteBatch.Draw(TextureAssets.InfoIcon[num].Value, vector2, new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.InfoIcon[num].Width(), TextureAssets.InfoIcon[num].Height()), color2, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                 if (flag14)
                 {
                     spriteBatch.Draw(TextureAssets.InfoIcon[13].Value, vector2 - Vector2.One * 2f, null, OurFavoriteColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                 }
                 X += 20;
             }
             UILinkPointNavigator.Shortcuts.INFOACCCOUNT = num3;
             if (playerInventory)
             {
                 continue;
             }
             Vector2 vector3 = new Vector2(1f);
             Vector2 vector4 = FontAssets.MouseText.Value.MeasureString(text2);
             if (vector4.X > num4)
             {
                 vector3.X = num4 / vector4.X;
             }
             if (vector3.X < 0.58f)
             {
                 vector3.Y = 1f - vector3.X / 3f;
             }
             for (int n = 0; n < 5; n++)
             {
                 int num28 = 0;
                 int num29 = 0;
                 Microsoft.Xna.Framework.Color color3 = infoTextShadowColor;
                 if (n == 0)
                 {
                     num28 = -2;
                 }
                 if (n == 1)
                 {
                     num28 = 2;
                 }
                 if (n == 2)
                 {
                     num29 = -2;
                 }
                 if (n == 3)
                 {
                     num29 = 2;
                 }
                 if (n == 4)
                 {
                     color3 = infoTextColor;
                 }
                 if (i > num2 && i < num2 + 2)
                 {
                     color3 = new Microsoft.Xna.Framework.Color(color3.R / 3, color3.G / 3, color3.B / 3, color3.A / 3);
                 }
                 int num30 = 22;
                 if (screenHeight < 650)
                 {
                     num30 = 20;
                 }
                 DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text2, new Vector2(X + num28, Y + 74 + num30 * i + num29 + 48), color3, 0f, default(Vector2), vector3, SpriteEffects.None, 0f);
             }
         }
         if (!string.IsNullOrEmpty(text))
         {
             if (playerInventory)
             {
                 player[myPlayer].mouseInterface = true;
             }
             MouseText(text, 0, 0);
         }
     }
References Player.accCritterGuideCounter, Player.accCritterGuideNumber, Player.accThirdEyeCounter, Player.accThirdEyeNumber, Tile.active(), PlayerFishingConditions.BaitItemType, Item.BannerToNPC(), TileID.Sets.BasicChest, TileID.Sets.BasicChestFake, SceneMetrics.bestOre, bloodMoon, CanShowInfoAccs, Entity.Center, Player.checkDPSTime(), SceneMetrics.ClosestOrePosition, cloudBGActive, dayTime, Player.displayedFishingInfo, DrawInfoAccs_AdjustInfoTextColorsForNPC(), DynamicSpriteFontExtensionMethods.DrawString(), eclipse, PlayerFishingConditions.FinalFishingLevel, GameCulture.FromCultureName(), Player.getDPS(), Player.GetFishingConditions(), GetInfoAccIconPosition(), Lang.GetMapObjectName(), Lang.GetNPCNameValue(), Language.GetTextValue(), MapHelper.GetTileBaseOption(), Framing.GetTileSafely(), NPC.GivenOrTypeName, GlobalTimeWrappedHourly, Sandstorm.Happening, Player.hideInfo, PlayerInput.IgnoreMouseInterface, UILinkPointNavigator.Shortcuts.INFOACCCOUNT, TextureAssets.InfoIcon, Player.instantMovementAccumulatedThisFrame, Lang.inter, GameCulture.IsActive, Mount.IsConsideredASlimeMount, IsItStorming, NPC.killCount, Player.lastCreatureHit, maxRaining, maxTilesX, maxTilesY, moonPhase, Player.mount, Player.mouseInterface, mouseLeft, mouseLeftRelease, FontAssets.MouseText, mouseText, MouseText(), mouseTextColor, mouseX, mouseY, myPlayer, npc, numClouds, OurFavoriteColor, player, playerInventory, SoundEngine.PlaySound(), Entity.position, projectile, NPC.rarity, rockLayer, screenHeight, UILinkPointNavigator.SetPosition(), Player.SlimeDontHyperJump, Player.speedSlice, spriteBatch, MapHelper.TileToLookup(), time, Tile.type, Asset< T >.Value, LocalizedText.Value, Entity.velocity, Entity.width, windSpeedCurrent, worldSurface, X, and Y.
Referenced by DrawInterface_28_InfoAccs().