Terraria: Main.DrawWallOfStars
DrawWallOfStars()
static void Main.DrawWallOfStars () inline static
     {
         bool flag = true;
         if (flag)
         {
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         }
         int num = Projectile.NewProjectile(Projectile.GetNoneSource(), Vector2.Zero, Vector2.UnitX, 12, 0, 0f, myPlayer);
         Projectile projectile = Main.projectile[num];
         for (int i = 0; i < 5; i++)
         {
             float num2 = 10f;
             Vector2 vector = new Vector2((float)screenWidth / num2 * (GlobalTimeWrappedHourly % num2), -100f);
             vector.X += 14 * i;
             vector.Y += i % 2 * 14;
             while (vector.Y < (float)(screenHeight + 100))
             {
                 vector.Y += 26f;
                 projectile.position = Vector2.One * 10f;
                 projectile.velocity = Vector2.UnitX * 10f;
                 projectile.rotation = GlobalTimeWrappedHourly * ((float)Math.PI * 2f);
                 projectile.Update(num);
                 projectile.position = vector + screenPosition;
                 instance.DrawProj(num);
             }
         }
         projectile.position = Vector2.One * 10f;
         projectile.Kill();
         if (flag)
         {
             spriteBatch.End();
         }
     }
References DefaultSamplerState, DrawProj(), Projectile.GetNoneSource(), GlobalTimeWrappedHourly, instance, Projectile.Kill(), myPlayer, Projectile.NewProjectile(), Entity.position, projectile, Rasterizer, Projectile.rotation, screenHeight, screenPosition, screenWidth, spriteBatch, Transform, Projectile.Update(), and Entity.velocity.