Terraria: Main.ItemIconCacheUpdate
ItemIconCacheUpdate()
static void Main.ItemIconCacheUpdate (int selectedItemID) inline static
     {
         _itemIconCacheScreenPosition = MouseScreen;
         _itemIconCacheSelectedItemID = selectedItemID;
         _itemIconCacheTime = 10;
     }
References _itemIconCacheScreenPosition, _itemIconCacheSelectedItemID, _itemIconCacheTime, and MouseScreen.
Referenced by Player.ItemCheck_OwnerOnlyCode(), Player.ItemCheck_UseBuckets(), Player.ItemCheck_UseMiningTools(), and Player.ItemCheck_UseWiringTools().