Terraria: Main.DrawInterface_16_MapOrMinimap
DrawInterface_16_MapOrMinimap()
void Main.DrawInterface_16_MapOrMinimap () inline private
     {
         mH = 0;
         if (!mapEnabled)
         {
             return;
         }
         if (!mapFullscreen && mapStyle == 1)
         {
             mH = 256;
             try
             {
                 DrawMap(new GameTime());
             }
             catch (Exception e)
             {
                 if (!ignoreErrors)
                 {
                     throw;
                 }
                 TimeLogger.DrawException(e);
             }
         }
         PlayerInput.SetZoom_UI();
         if (mH + RecommendedEquipmentAreaPushUp > screenHeight)
         {
             mH = screenHeight - RecommendedEquipmentAreaPushUp;
         }
     }
References TimeLogger.DrawException(), DrawMap(), ignoreErrors, mapEnabled, mapFullscreen, mapStyle, mH, RecommendedEquipmentAreaPushUp, screenHeight, and PlayerInput.SetZoom_UI().
Referenced by DrawInterface_11_IngameOptionsMenu(), and SetupDrawInterfaceLayers().