Terraria: Main.DrawPageIcons
DrawPageIcons()
static int Main.DrawPageIcons (int yPos) inline static private
     {
         int num = -1;
         Vector2 vector = new Vector2(screenWidth - 162, yPos);
         vector.X += 82f;
         Texture2D value = TextureAssets.EquipPage[(EquipPage == 2) ? 3 : 2].Value;
         if (Collision.CheckAABBvAABBCollision(vector, value.Size(), new Vector2(mouseX, mouseY), Vector2.One) && (mouseItem.stack < 1 || mouseItem.dye > 0))
         {
             num = 2;
         }
         if (num == 2)
         {
             spriteBatch.Draw(TextureAssets.EquipPage[6].Value, vector, null, OurFavoriteColor, 0f, new Vector2(2f), 0.9f, SpriteEffects.None, 0f);
         }
         spriteBatch.Draw(value, vector, null, Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, 0.9f, SpriteEffects.None, 0f);
         UILinkPointNavigator.SetPosition(305, vector + value.Size() * 0.75f);
         vector.X -= 48f;
         value = TextureAssets.EquipPage[(EquipPage == 1) ? 5 : 4].Value;
         if (Collision.CheckAABBvAABBCollision(vector, value.Size(), new Vector2(mouseX, mouseY), Vector2.One) && mouseItem.stack < 1)
         {
             num = 1;
         }
         if (num == 1)
         {
             spriteBatch.Draw(TextureAssets.EquipPage[7].Value, vector, null, OurFavoriteColor, 0f, new Vector2(2f), 0.9f, SpriteEffects.None, 0f);
         }
         spriteBatch.Draw(value, vector, null, Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, 0.9f, SpriteEffects.None, 0f);
         UILinkPointNavigator.SetPosition(306, vector + value.Size() * 0.75f);
         vector.X -= 48f;
         value = TextureAssets.EquipPage[(EquipPage == 3) ? 10 : 8].Value;
         if (Collision.CheckAABBvAABBCollision(vector, value.Size(), new Vector2(mouseX, mouseY), Vector2.One) && mouseItem.stack < 1)
         {
             num = 3;
         }
         if (num == 3 && !CaptureModeDisabled)
         {
             spriteBatch.Draw(TextureAssets.EquipPage[9].Value, vector, null, OurFavoriteColor, 0f, Vector2.Zero, 0.9f, SpriteEffects.None, 0f);
         }
         spriteBatch.Draw(value, vector, null, CaptureModeDisabled ? Microsoft.Xna.Framework.Color.Red : Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, 0.9f, SpriteEffects.None, 0f);
         UILinkPointNavigator.SetPosition(307, vector + value.Size() * 0.75f);
         if (num != -1)
         {
             player[myPlayer].mouseInterface = true;
             if (mouseLeft && mouseLeftRelease)
             {
                 bool flag = true;
                 if (num == 3)
                 {
                     if (CaptureModeDisabled)
                     {
                         flag = false;
                     }
                     else if (PlayerInput.UsingGamepad)
                     {
                         CaptureInterface.QuickScreenshot();
                     }
                     else
                     {
                         CaptureManager.Instance.Active = true;
                         blockMouse = true;
                     }
                 }
                 else if (EquipPageSelected != num)
                 {
                     EquipPageSelected = num;
                 }
                 else
                 {
                     EquipPageSelected = 0;
                 }
                 if (flag)
                 {
                     SoundEngine.PlaySound(10);
                 }
             }
         }
         ItemSlot.SelectEquipPage(mouseItem);
         if (EquipPage == -1)
         {
             EquipPage = EquipPageSelected;
         }
         return num;
     }
References CaptureManager.Active, blockMouse, CaptureModeDisabled, Collision.CheckAABBvAABBCollision(), Item.dye, TextureAssets.EquipPage, EquipPage, EquipPageSelected, CaptureManager.Instance, Player.mouseInterface, mouseItem, mouseLeft, mouseLeftRelease, mouseX, mouseY, myPlayer, OurFavoriteColor, player, SoundEngine.PlaySound(), CaptureInterface.QuickScreenshot(), screenWidth, ItemSlot.SelectEquipPage(), UILinkPointNavigator.SetPosition(), spriteBatch, Item.stack, PlayerInput.UsingGamepad, and Asset< T >.Value.
Referenced by DrawInventory().