Terraria: Main.DrawNPCHousesInWorld
DrawNPCHousesInWorld()
void Main.DrawNPCHousesInWorld () inline protected
     {
         _npcsWithBannersToDraw.Clear();
         _occupantsListToDrawNPCHouses.Clear();
         for (int i = 0; i < 200; i++)
         {
             if (npc[i].active && npc[i].townNPC && !npc[i].homeless && npc[i].homeTileX > 0 && npc[i].homeTileY > 0 && npc[i].type != 37)
             {
                 _npcsWithBannersToDraw.Add(i);
             }
         }
         _npcsWithBannersToDraw.Sort(NPCBannerSorter);
         for (int j = 0; j < _npcsWithBannersToDraw.Count; j++)
         {
             int num = _npcsWithBannersToDraw[j];
             NPC nPC = npc[num];
             if (!nPC.active || !nPC.townNPC || nPC.homeless || nPC.homeTileX <= 0 || nPC.homeTileY <= 0 || nPC.type == 37)
             {
                 continue;
             }
             int num2 = 0;
             int housingCategory = nPC.housingCategory;
             int homeTileX = nPC.homeTileX;
             int num3 = nPC.homeTileY - 1;
             WorldGen.TownManager.AddOccupantsToList(homeTileX, num3 + 1, _occupantsListToDrawNPCHouses);
             if (_occupantsListToDrawNPCHouses.Contains(nPC.type))
             {
                 num2 = 1;
             }
             int num4 = 0;
             for (int num5 = _npcsWithBannersToDraw.Count - 1; num5 > j; num5--)
             {
                 int num6 = _npcsWithBannersToDraw[num5];
                 if (npc[num6].homeTileX == homeTileX && npc[num6].homeTileY == num3 + 1)
                 {
                     num4++;
                 }
             }
             int num7 = num4 * 26;
             if (tile[homeTileX, num3] == null)
             {
                 continue;
             }
             bool flag = false;
             while (!tile[homeTileX, num3].active() || !tileSolid[tile[homeTileX, num3].type])
             {
                 num3--;
                 if (num3 < 10)
                 {
                     break;
                 }
                 if (tile[homeTileX, num3] == null)
                 {
                     flag = true;
                     break;
                 }
             }
             if (flag)
             {
                 continue;
             }
             int num8 = 8;
             int num9 = 18;
             if (tile[homeTileX, num3].type == 19)
             {
                 num9 -= 8;
             }
             num3++;
             int num10 = 0;
             float num11 = num3 * 16;
             num11 += (float)num7;
             SpriteEffects effects = SpriteEffects.None;
             Texture2D value = TextureAssets.HouseBanner.Value;
             Microsoft.Xna.Framework.Rectangle value2 = value.Frame(2, 2);
             if (num2 > 0)
             {
                 value2.X += value2.Width * num2;
             }
             if (housingCategory > 0)
             {
                 value2.Y += value2.Height * housingCategory;
             }
             if (player[myPlayer].gravDir == -1f)
             {
                 num11 -= screenPosition.Y;
                 num11 = screenPosition.Y + (float)screenHeight - num11;
                 num11 -= (float)value2.Height;
                 effects = SpriteEffects.FlipVertically;
                 num10 = 4;
             }
             spriteBatch.Draw(value, new Vector2(homeTileX * 16 - (int)screenPosition.X + num8, num11 - (float)(int)screenPosition.Y + (float)num9 + (float)num10), value2, Lighting.GetColor(homeTileX, num3), 0f, new Vector2(value2.Width / 2, value2.Height / 2), 1f, effects, 0f);
             int headIndexSafe = TownNPCProfiles.GetHeadIndexSafe(nPC);
             float scale = 1f;
             float num12 = 0f;
             num12 = ((TextureAssets.NpcHead[headIndexSafe].Width() <= TextureAssets.NpcHead[headIndexSafe].Height()) ? ((float)TextureAssets.NpcHead[headIndexSafe].Height()) : ((float)TextureAssets.NpcHead[headIndexSafe].Width()));
             if (num12 > 24f)
             {
                 scale = 24f / num12;
             }
             spriteBatch.Draw(TextureAssets.NpcHead[headIndexSafe].Value, new Vector2(homeTileX * 16 - (int)screenPosition.X + num8, num11 - (float)(int)screenPosition.Y + (float)num9 + 2f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.NpcHead[headIndexSafe].Width(), TextureAssets.NpcHead[headIndexSafe].Height()), Lighting.GetColor(homeTileX, num3), 0f, new Vector2(TextureAssets.NpcHead[headIndexSafe].Width() / 2, TextureAssets.NpcHead[headIndexSafe].Height() / 2), scale, effects, 0f);
             homeTileX = homeTileX * 16 - (int)screenPosition.X + num8 - value2.Width / 2;
             num3 = (int)num11 - (int)screenPosition.Y + 4;
             int num13 = -8;
             if (mouseX >= homeTileX && mouseX <= homeTileX + value2.Width && mouseY >= num3 && mouseY <= num3 + value2.Height + num13)
             {
                 string nPCHouseBannerText = Lang.GetNPCHouseBannerText(nPC, num2);
                 MouseText(nPCHouseBannerText, 0, 0);
                 if (mouseRightRelease && mouseRight)
                 {
                     mouseRightRelease = false;
                     WorldGen.kickOut(num);
                     SoundEngine.PlaySound(12);
                 }
             }
         }
     }
References _npcsWithBannersToDraw, _occupantsListToDrawNPCHouses, Entity.active, TownRoomManager.AddOccupantsToList(), Lighting.GetColor(), TownNPCProfiles.GetHeadIndexSafe(), Lang.GetNPCHouseBannerText(), NPC.homeless, NPC.homeTileX, NPC.homeTileY, TextureAssets.HouseBanner, NPC.housingCategory, WorldGen.kickOut(), mouseRight, mouseRightRelease, MouseText(), mouseX, mouseY, myPlayer, npc, NPCBannerSorter(), TextureAssets.NpcHead, player, SoundEngine.PlaySound(), screenHeight, screenPosition, spriteBatch, tile, tileSolid, WorldGen.TownManager, NPC.townNPC, NPC.type, and Asset< T >.Value.
Referenced by DrawInterface_7_TownNPCHouseBanners().