Terraria: Main.StartSlimeRain
StartSlimeRain()
static void Main.StartSlimeRain (bool announce = true) inline static
     {
         if (remixWorld || slimeRain)
         {
             return;
         }
         if (netMode == 1)
         {
             slimeRainTime = 54000.0;
             slimeRain = true;
             SkyManager.Instance.Activate("Slime", default(Vector2));
         }
         else
         {
             if (raining)
             {
                 return;
             }
             if (slimeRainTime <= 0.0)
             {
                 slimeRainTime = rand.Next(32400, 54000);
             }
             slimeRain = true;
             slimeRainKillCount = 0;
             if (netMode == 0)
             {
                 SkyManager.Instance.Activate("Slime", default(Vector2));
                 if (announce)
                 {
                     slimeWarningTime = slimeWarningDelay;
                 }
             }
             else if (announce)
             {
                 slimeWarningTime = slimeWarningDelay;
                 NetMessage.SendData(7);
             }
         }
     }
References EffectManager< T >.Activate(), SkyManager.Instance, netMode, UnifiedRandom.Next(), raining, rand, remixWorld, NetMessage.SendData(), slimeRain, slimeRainKillCount, slimeRainTime, slimeWarningDelay, and slimeWarningTime.
Referenced by MessageBuffer.GetData(), WorldFile.LoadWorld(), and UpdateTime().