Terraria: Main.DrawMenu
DrawMenu()
void Main.DrawMenu (GameTime gameTime) inline protected
     {
         if (!IsEngineLoaded)
         {
             IsEngineLoaded = true;
             if (Main.OnEngineLoad != null)
             {
                 Main.OnEngineLoad();
             }
         }
         GamepadMainMenuHandler.Update();
         GamepadMainMenuHandler.MenuItemPositions.Clear();
         int num = menuMode;
         if (menuMode <= 1 && slimeRain)
         {
             StopSlimeRain();
         }
         render = false;
         SceneMetrics.Reset();
         drawingPlayerChat = false;
         chatMonitor.Clear();
         screenLastPosition = screenPosition;
         screenPosition.Y = (float)(worldSurface * 16.0 - (double)screenHeight);
         MenuXMovement = 4f;
         if (alreadyGrabbingSunOrMoon)
         {
             playOldTile = true;
             if (starGame)
             {
                 playOldTile = false;
             }
         }
         screenPosition.X += MenuXMovement;
         if (screenPosition.X > 2.1474835E+09f)
         {
             screenPosition.X = 0f;
         }
         if (screenPosition.X < -2.1474835E+09f)
         {
             screenPosition.X = 0f;
         }
         Star.UpdateStars();
         Cloud.UpdateClouds();
         DrawFPS();
         background = 0;
         byte b = (byte)((255 + tileColor.R * 2) / 3);
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(b, b, b, 255);
         if (WorldGen.remixWorldGen)
         {
             logoRotation += logoRotationSpeed * 4E-05f;
             if ((double)logoRotation < 3.04)
             {
                 logoRotation += logoRotationSpeed * 0.0016f;
                 if (logoRotationSpeed < 0f)
                 {
                     logoRotationSpeed = 0f;
                 }
             }
             if ((double)logoRotation > 3.22)
             {
                 logoRotationDirection = -1f;
             }
             else if ((double)logoRotation < 3.06)
             {
                 logoRotationDirection = 1f;
             }
             if (logoRotationSpeed < 20f && logoRotationDirection == 1f)
             {
                 logoRotationSpeed += 1f;
             }
             else if (logoRotationSpeed > -20f && logoRotationDirection == -1f)
             {
                 logoRotationSpeed -= 1f;
             }
             logoScale += logoScaleSpeed * 9E-05f;
             if (logoScale > 1f)
             {
                 logoScaleDirection = -1f;
             }
             else if (logoScale < 0.9f)
             {
                 logoScaleDirection = 1f;
             }
             if (logoScaleSpeed < 50f && logoScaleDirection == 1f)
             {
                 logoScaleSpeed += 1f;
             }
             else if (logoScaleSpeed > -50f && logoScaleDirection == -1f)
             {
                 logoScaleSpeed -= 1f;
             }
         }
         else if (WorldGen.drunkWorldGen)
         {
             logoRotation += logoRotationSpeed * 4E-06f;
             if (logoRotationSpeed > 0f)
             {
                 logoRotationSpeed += 1500f;
             }
             else
             {
                 logoRotationSpeed -= 1500f;
             }
             logoScale -= 0.05f;
             if (logoScale < 0f)
             {
                 logoScale = 0f;
             }
         }
         else
         {
             if ((double)logoRotation > 0.09)
             {
                 logoRotation += logoRotationSpeed * 0.0016f;
                 if (logoRotationSpeed > 0f)
                 {
                     logoRotationSpeed = 0f;
                 }
             }
             logoRotation += logoRotationSpeed * 4E-06f;
             if ((double)logoRotation > 0.08)
             {
                 logoRotationDirection = -1f;
             }
             else if ((double)logoRotation < -0.08)
             {
                 logoRotationDirection = 1f;
             }
             if (logoRotationSpeed < 20f && logoRotationDirection == 1f)
             {
                 logoRotationSpeed += 1f;
             }
             else if (logoRotationSpeed > -20f && logoRotationDirection == -1f)
             {
                 logoRotationSpeed -= 1f;
             }
             logoScale += logoScaleSpeed * 9E-06f;
             if ((double)logoScale > 1.35)
             {
                 logoScaleDirection = -1f;
             }
             else if (logoScale < 1f)
             {
                 logoScaleDirection = 1f;
             }
             if (logoScaleSpeed < 50f && logoScaleDirection == 1f)
             {
                 logoScaleSpeed += 1f;
             }
             else if (logoScaleSpeed > -50f && logoScaleDirection == -1f)
             {
                 logoScaleSpeed -= 1f;
             }
         }
         Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color((byte)((float)(int)color.R * ((float)LogoA / 255f)), (byte)((float)(int)color.G * ((float)LogoA / 255f)), (byte)((float)(int)color.B * ((float)LogoA / 255f)), (byte)((float)(int)color.A * ((float)LogoA / 255f)));
         Microsoft.Xna.Framework.Color color3 = new Microsoft.Xna.Framework.Color((byte)((float)(int)color.R * ((float)LogoB / 255f)), (byte)((float)(int)color.G * ((float)LogoB / 255f)), (byte)((float)(int)color.B * ((float)LogoB / 255f)), (byte)((float)(int)color.A * ((float)LogoB / 255f)));
         if (playOldTile)
         {
             spriteBatch.Draw(TextureAssets.Logo3.Value, new Vector2(screenWidth / 2, 100f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Logo.Width(), TextureAssets.Logo.Height()), color2, logoRotation, new Vector2(TextureAssets.Logo.Width() / 2, TextureAssets.Logo.Height() / 2), logoScale, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.Logo4.Value, new Vector2(screenWidth / 2, 100f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Logo.Width(), TextureAssets.Logo.Height()), color3, logoRotation, new Vector2(TextureAssets.Logo.Width() / 2, TextureAssets.Logo.Height() / 2), logoScale, SpriteEffects.None, 0f);
         }
         else
         {
             spriteBatch.Draw(TextureAssets.Logo.Value, new Vector2(screenWidth / 2, 100f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Logo.Width(), TextureAssets.Logo.Height()), color2, logoRotation, new Vector2(TextureAssets.Logo.Width() / 2, TextureAssets.Logo.Height() / 2), logoScale, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.Logo2.Value, new Vector2(screenWidth / 2, 100f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Logo.Width(), TextureAssets.Logo.Height()), color3, logoRotation, new Vector2(TextureAssets.Logo.Width() / 2, TextureAssets.Logo.Height() / 2), logoScale, SpriteEffects.None, 0f);
         }
         if (dayTime && !WorldGen.remixWorldGen)
         {
             LogoA += 2;
             if (LogoA > 255)
             {
                 LogoA = 255;
             }
             LogoB--;
             if (LogoB < 0)
             {
                 LogoB = 0;
             }
         }
         else
         {
             LogoB += 2;
             if (LogoB > 255)
             {
                 LogoB = 255;
             }
             LogoA--;
             if (LogoA < 0)
             {
                 LogoA = 0;
                 LogoT = true;
             }
         }
         int num2 = 250;
         int num3 = screenWidth / 2;
         int num4 = 80;
         int num5 = 0;
         int num6 = menuMode;
         int num7 = 0;
         int num8 = 0;
         bool flag = false;
         bool flag2 = false;
         bool flag3 = false;
         int num9 = 0;
         bool[] array = new bool[maxMenuItems];
         bool[] array2 = new bool[maxMenuItems];
         bool[] array3 = new bool[maxMenuItems];
         int[] array4 = new int[maxMenuItems];
         int[] array5 = new int[maxMenuItems];
         byte[] array6 = new byte[maxMenuItems];
         float[] array7 = new float[maxMenuItems];
         bool[] array8 = new bool[maxMenuItems];
         bool flag4 = false;
         bool flag5 = UILinkPointNavigator.Shortcuts.BackButtonInUse && !UILinkPointNavigator.Shortcuts.BackButtonLock;
         for (int i = 0; i < maxMenuItems; i++)
         {
             array[i] = false;
             array2[i] = false;
             array4[i] = 0;
             array5[i] = 0;
             array7[i] = 1f;
         }
         string[] array9 = new string[maxMenuItems];
         if (menuMode == -1)
         {
             menuMode = 0;
         }
         if (Program.LoadedEverything)
         {
             GamepadMainMenuHandler.CanRun = true;
         }
         if (menuMode == 1212)
         {
             array9[0] = Lang.menu[102].Value;
             num4 = 50;
             num2 = 200;
             num4 = 33;
             num2 = 200;
             array4[0] = -20;
             array4[1] = 25;
             array4[2] = 25;
             array4[3] = 25;
             array4[4] = 25;
             array4[5] = 25;
             array4[6] = 25;
             array4[7] = 25;
             array4[8] = 25;
             array4[9] = 25;
             array[0] = true;
             array9[1] = Language.GetTextValue("Language.English");
             array9[2] = Language.GetTextValue("Language.German");
             array9[3] = Language.GetTextValue("Language.Italian");
             array9[4] = Language.GetTextValue("Language.French");
             array9[5] = Language.GetTextValue("Language.Spanish");
             array9[6] = Language.GetTextValue("Language.Russian");
             array9[7] = Language.GetTextValue("Language.Chinese");
             array9[8] = Language.GetTextValue("Language.Portuguese");
             array9[9] = Language.GetTextValue("Language.Polish");
             num5 = 10;
             for (int j = 0; j < num5; j++)
             {
                 array7[j] = 0.75f;
             }
             array7[0] = 1f;
             if (selectedMenu >= 1)
             {
                 changeTheTitle = true;
                 LanguageManager.Instance.SetLanguage(selectedMenu);
                 menuMode = 0;
                 SoundEngine.PlaySound(10);
                 SaveSettings();
             }
         }
         else if (menuMode == 1213)
         {
             array9[0] = Lang.menu[102].Value;
             array[0] = true;
             array9[1] = Language.GetTextValue("Language.English");
             array9[2] = Language.GetTextValue("Language.German");
             array9[3] = Language.GetTextValue("Language.Italian");
             array9[4] = Language.GetTextValue("Language.French");
             array9[5] = Language.GetTextValue("Language.Spanish");
             array9[6] = Language.GetTextValue("Language.Russian");
             array9[7] = Language.GetTextValue("Language.Chinese");
             array9[8] = Language.GetTextValue("Language.Portuguese");
             array9[9] = Language.GetTextValue("Language.Polish");
             array9[10] = Lang.menu[5].Value;
             num5 = 11;
             if (selectedMenu == 10 || flag5)
             {
                 flag5 = false;
                 menuMode = 11;
                 SoundEngine.PlaySound(11);
             }
             else if (selectedMenu >= 1)
             {
                 changeTheTitle = true;
                 LanguageManager.Instance.SetLanguage(selectedMenu);
                 SoundEngine.PlaySound(12);
                 SaveSettings();
             }
             num4 = 33;
             num2 = 200;
             array4[0] = -20;
             array4[10] = 10;
             for (int k = 0; k < num5; k++)
             {
                 array7[k] = 0.75f;
             }
             array7[0] = 0.85f;
             array7[10] = 0.95f;
         }
         else if (netMode == 2)
         {
             bool flag6 = true;
             for (int l = 0; l < 8; l++)
             {
                 if (l >= 255)
                 {
                     continue;
                 }
                 try
                 {
                     array9[l] = Netplay.Clients[l].StatusText;
                     if (Netplay.Clients[l].IsActive && showSpam)
                     {
                         ref string reference = ref array9[l];
                         reference = reference + " (" + NetMessage.buffer[l].spamCount + ")";
                     }
                 }
                 catch
                 {
                     array9[l] = "";
                 }
                 array[l] = true;
                 if (array9[l] != "" && array9[l] != null)
                 {
                     flag6 = false;
                 }
             }
             if (flag6)
             {
                 array9[0] = Lang.menu[0].Value;
                 array9[1] = Lang.menu[1].Value + Netplay.ListenPort + ".";
             }
             num5 = 11;
             array9[9] = statusText;
             array[9] = true;
             num2 = 170;
             num4 = 30;
             array4[10] = 20;
             array4[10] = 40;
             array9[10] = Lang.menu[2].Value;
             if (selectedMenu == 10 || flag5)
             {
                 flag5 = false;
                 Netplay.Disconnect = true;
                 SoundEngine.PlaySound(11);
             }
         }
         else if (menuMode == 31)
         {
             if (PlayerInput.SettingsForUI.ShowGamepadHints)
             {
                 UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Lang.menu[3].Value, Netplay.ServerPassword, OnSubmitServerPasswordFromRequest, CanceledGivingServerPassword, 0, allowEmpty: true);
                 uIVirtualKeyboard.HideContents = HidePassword;
                 UserInterface.ActiveInstance.SetState(uIVirtualKeyboard);
                 menuMode = 888;
             }
             string serverPassword = Netplay.ServerPassword;
             PlayerInput.WritingText = true;
             instance.HandleIME();
             Netplay.ServerPassword = GetInputText(Netplay.ServerPassword);
             if (serverPassword != Netplay.ServerPassword)
             {
                 SoundEngine.PlaySound(12);
             }
             array9[0] = Lang.menu[3].Value;
             textBlinkerCount++;
             if (textBlinkerCount >= 20)
             {
                 if (textBlinkerState == 0)
                 {
                     textBlinkerState = 1;
                 }
                 else
                 {
                     textBlinkerState = 0;
                 }
                 textBlinkerCount = 0;
             }
             array9[1] = Netplay.ServerPassword;
             if (HidePassword)
             {
                 array9[1] = "";
                 for (int m = 0; m < Netplay.ServerPassword.Length; m++)
                 {
                     array9[1] += "*";
                 }
             }
             if (textBlinkerState == 1)
             {
                 array9[1] += "|";
                 array5[1] = 1;
             }
             else
             {
                 array9[1] += " ";
             }
             array[0] = true;
             array[1] = true;
             array4[1] = -20;
             array4[2] = 20;
             array9[2] = Lang.menu[4].Value;
             array9[3] = Lang.menu[5].Value;
             num5 = 4;
             if (selectedMenu == 3 || flag5)
             {
                 flag5 = false;
                 CanceledGivingServerPassword();
             }
             else if (selectedMenu == 2 || inputTextEnter)
             {
                 OnSubmitServerPasswordFromRequest();
             }
         }
         else if ((netMode == 1 && menuMode != 888) || menuMode == 14)
         {
             num5 = 2;
             array9[0] = statusText;
             array[0] = true;
             num2 = 300;
             int num10 = statusText.Split('\n').Length - 1;
             array7[0] = 1f - (float)num10 * 0.04f;
             array4[0] = num10 * -18;
             array4[1] = num10 * 28;
             array9[1] = Lang.menu[6].Value;
             gameTips.Update();
             gameTips.Draw();
             if (selectedMenu == 1 || flag5)
             {
                 flag5 = false;
                 Netplay.InvalidateAllOngoingIPSetAttempts();
                 Netplay.Disconnect = true;
                 Netplay.Connection.Socket.Close();
                 SoundEngine.PlaySound(11);
                 menuMode = 0;
                 netMode = 0;
                 if (tServer != null)
                 {
                     try
                     {
                         tServer.Kill();
                         tServer = null;
                     }
                     catch
                     {
                     }
                 }
             }
         }
         else if (menuMode == 882)
         {
             num5 = 2;
             array[0] = true;
             num2 = 300;
             array9[0] = statusText;
             array9[1] = Lang.menu[6].Value;
             if (selectedMenu == 1 || flag5)
             {
                 flag5 = false;
                 SoundEngine.PlaySound(11);
                 menuMode = 0;
                 netMode = 0;
                 if (SocialAPI.Network != null)
                 {
                     SocialAPI.Network.CancelJoin();
                 }
             }
         }
         else if (menuMode == 30)
         {
             if (PlayerInput.SettingsForUI.ShowGamepadHints)
             {
                 UIVirtualKeyboard uIVirtualKeyboard2 = new UIVirtualKeyboard(Lang.menu[7].Value, Netplay.ServerPassword, OnSubmitServerPassword, ExitServerPasswordMenu, 0, allowEmpty: true);
                 uIVirtualKeyboard2.HideContents = HidePassword;
                 UserInterface.ActiveInstance.SetState(uIVirtualKeyboard2);
                 menuMode = 888;
             }
             string serverPassword2 = Netplay.ServerPassword;
             PlayerInput.WritingText = true;
             instance.HandleIME();
             Netplay.ServerPassword = GetInputText(Netplay.ServerPassword);
             if (serverPassword2 != Netplay.ServerPassword)
             {
                 SoundEngine.PlaySound(12);
             }
             array9[0] = Lang.menu[7].Value;
             textBlinkerCount++;
             if (textBlinkerCount >= 20)
             {
                 if (textBlinkerState == 0)
                 {
                     textBlinkerState = 1;
                 }
                 else
                 {
                     textBlinkerState = 0;
                 }
                 textBlinkerCount = 0;
             }
             array9[1] = Netplay.ServerPassword;
             if (HidePassword)
             {
                 array9[1] = "";
                 for (int n = 0; n < Netplay.ServerPassword.Length; n++)
                 {
                     array9[1] += "*";
                 }
             }
             if (textBlinkerState == 1)
             {
                 array9[1] += "|";
                 array5[1] = 1;
             }
             else
             {
                 array9[1] += " ";
             }
             array[0] = true;
             array[1] = true;
             array4[1] = -20;
             array4[2] = 20;
             array9[2] = Lang.menu[4].Value;
             array9[3] = Lang.menu[5].Value;
             num5 = 4;
             if (selectedMenu == 3 || flag5)
             {
                 flag5 = false;
                 ExitServerPasswordMenu();
             }
             else if (selectedMenu == 2 || inputTextEnter || autoPass)
             {
                 OnSubmitServerPassword();
             }
         }
         else if (menuMode == 889)
         {
             num2 = 200;
             num4 = 60;
             array4[1] = 30;
             array4[2] = 30;
             array4[3] = 30;
             array4[4] = 70;
             array4[5] = 70;
             num5 = 6;
             array9[0] = Lang.menu[135].Value;
             array9[4] = Lang.menu[144].Value;
             array9[5] = Lang.menu[5].Value;
             array[0] = true;
             if (!MenuServerMode.HasFlag(ServerMode.Lobby))
             {
                 MenuServerMode = ServerMode.None;
                 array[2] = true;
                 array[3] = true;
                 array9[1] = Lang.menu[136].Value;
                 array9[2] = "";
                 array9[3] = "";
             }
             else
             {
                 array9[1] = Lang.menu[137].Value;
                 if (MenuServerMode.HasFlag(ServerMode.FriendsCanJoin))
                 {
                     array9[2] = Lang.menu[139].Value;
                     if (MenuServerMode.HasFlag(ServerMode.FriendsOfFriends))
                     {
                         array9[3] = Lang.menu[143].Value;
                     }
                     else
                     {
                         array9[3] = Lang.menu[142].Value;
                     }
                 }
                 else
                 {
                     array9[2] = Lang.menu[138].Value;
                     if (MenuServerMode.HasFlag(ServerMode.FriendsOfFriends))
                     {
                         array9[3] = Lang.menu[141].Value;
                     }
                     else
                     {
                         array9[3] = Lang.menu[140].Value;
                     }
                 }
             }
             if (flag5)
             {
                 flag5 = false;
                 selectedMenu = 5;
             }
             switch (selectedMenu)
             {
             case 1:
                 MenuServerMode ^= ServerMode.Lobby;
                 SoundEngine.PlaySound(12);
                 break;
             case 2:
                 MenuServerMode ^= ServerMode.FriendsCanJoin;
                 SoundEngine.PlaySound(12);
                 break;
             case 3:
                 MenuServerMode ^= ServerMode.FriendsOfFriends;
                 SoundEngine.PlaySound(12);
                 break;
             case 4:
                 clrInput();
                 Netplay.ServerPassword = "";
                 GetInputText("");
                 autoPass = false;
                 menuMode = 30;
                 SoundEngine.PlaySound(10);
                 break;
             case 5:
                 menuMode = 6;
                 SoundEngine.PlaySound(11);
                 break;
             }
         }
         else if (menuMode == 15)
         {
             num5 = 2;
             array9[0] = statusText;
             array[0] = true;
             num2 = 80;
             num4 = 400;
             array9[1] = Lang.menu[5].Value;
             if (selectedMenu == 1 || flag5)
             {
                 flag5 = false;
                 Netplay.Disconnect = true;
                 SoundEngine.PlaySound(11);
                 menuMode = 0;
                 netMode = 0;
             }
         }
         else if (menuMode == 200)
         {
             num5 = 3;
             array9[0] = Lang.menu[9].Value;
             array[0] = true;
             num2 -= 30;
             array4[1] = 70;
             array4[2] = 50;
             array9[1] = Lang.menu[10].Value;
             array9[2] = Lang.menu[6].Value;
             if (selectedMenu == 1)
             {
                 if (FileUtilities.Exists(worldPathName + ".bak", ActiveWorldFileData.IsCloudSave))
                 {
                     FileUtilities.Move(worldPathName, worldPathName + ".bad", ActiveWorldFileData.IsCloudSave);
                     FileUtilities.Move(worldPathName + ".bak", worldPathName, ActiveWorldFileData.IsCloudSave);
                     SoundEngine.PlaySound(10);
                     WorldGen.playWorld();
                     menuMode = 10;
                 }
                 else
                 {
                     SoundEngine.PlaySound(11);
                     menuMode = 0;
                     netMode = 0;
                 }
             }
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 SoundEngine.PlaySound(11);
                 menuMode = 0;
                 netMode = 0;
             }
         }
         else if (menuMode == 201)
         {
             num5 = 3;
             array9[0] = Lang.menu[9].Value;
             array[0] = true;
             array[1] = true;
             num2 -= 30;
             array4[1] = -30;
             array4[2] = 50;
             array9[1] = Lang.menu[11].Value;
             array9[2] = Lang.menu[5].Value;
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 SoundEngine.PlaySound(11);
                 menuMode = 0;
                 netMode = 0;
             }
         }
         else if (menuMode == 10)
         {
             num5 = 1;
             array9[0] = statusText;
             array[0] = true;
             num2 = 300;
             gameTips.Update();
             gameTips.Draw();
         }
         else if (menuMode == 100)
         {
             num5 = 1;
             array9[0] = statusText;
             array[0] = true;
             num2 = 300;
         }
         else if (menuMode == 0)
         {
             _blockFancyUIWhileLoading = false;
             _pendingCharacterSelect = null;
             DD2Event.Ongoing = false;
             eclipse = false;
             pumpkinMoon = false;
             snowMoon = false;
             ServerSideCharacter = false;
             menuMultiplayer = false;
             menuServer = false;
             netMode = 0;
             ClearVisualPostProcessEffects();
             int num11 = 0;
             num2 = 220;
             num5 = 7;
             num4 = 52;
             array9[num11] = Lang.menu[12].Value;
             if (selectedMenu == num11)
             {
                 SoundEngine.PlaySound(10);
                 ClearPendingPlayerSelectCallbacks();
                 menuMode = 1;
             }
             num11++;
             array9[num11] = Lang.menu[13].Value;
             if (selectedMenu == num11)
             {
                 SoundEngine.PlaySound(10);
                 menuMode = 12;
             }
             num11++;
             array9[num11] = Lang.menu[131].Value;
             if (selectedMenu == num11)
             {
                 SoundEngine.PlaySound(10);
                 menuMode = 888;
                 MenuUI.SetState(AchievementsMenu);
             }
             num11++;
             if (SocialAPI.Workshop != null)
             {
                 array9[num11] = Language.GetText("UI.Workshop").Value;
                 if (selectedMenu == num11)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 888;
                     UIWorkshopHub uIWorkshopHub = new UIWorkshopHub(null);
                     uIWorkshopHub.EnterHub();
                     MenuUI.SetState(uIWorkshopHub);
                 }
             }
             else
             {
                 array9[num11] = Language.GetText("UI.ResourcePacks").Value;
                 if (selectedMenu == num11)
                 {
                     SoundEngine.PlaySound(10);
                     OpenResourcePacksMenu(null);
                 }
             }
             num11++;
             array9[num11] = Lang.menu[14].Value;
             if (selectedMenu == num11)
             {
                 SoundEngine.PlaySound(10);
                 menuMode = 11;
             }
             num11++;
             array9[num11] = Language.GetText("UI.Credits").Value;
             if (selectedMenu == num11)
             {
                 SoundEngine.PlaySound(10);
                 menuMode = 3000;
                 SkyManager.Instance.Activate("CreditsRoll", default(Vector2));
             }
             num11++;
             array9[num11] = Lang.menu[15].Value;
             if (selectedMenu == num11)
             {
                 GameAskedToQuit = true;
             }
             num11++;
         }
         else if (menuMode == 1)
         {
             OpenCharacterSelectUI();
         }
         else if (menuMode == 2)
         {
             flag4 = true;
             if (selectedMenu == 0)
             {
                 menuMode = 17;
                 SoundEngine.PlaySound(10);
                 selColor = PendingPlayer.hairColor;
             }
             if (selectedMenu == 1)
             {
                 menuMode = 18;
                 SoundEngine.PlaySound(10);
                 selColor = PendingPlayer.eyeColor;
             }
             if (selectedMenu == 2)
             {
                 menuMode = 19;
                 SoundEngine.PlaySound(10);
                 selColor = PendingPlayer.skinColor;
             }
             if (selectedMenu == 3)
             {
                 menuMode = 20;
                 SoundEngine.PlaySound(10);
             }
             array9[0] = Lang.menu[18].Value;
             array9[1] = Lang.menu[19].Value;
             array9[2] = Lang.menu[20].Value;
             array9[3] = Lang.menu[21].Value;
             num2 = 220;
             for (int num12 = 0; num12 < 9; num12++)
             {
                 if (num12 < 6)
                 {
                     array7[num12] = 0.75f;
                 }
                 else
                 {
                     array7[num12] = 0.9f;
                 }
             }
             num4 = 38;
             array4[6] = 6;
             array4[7] = 12;
             array4[8] = 18;
             num7 = screenWidth / 2 - 16;
             num8 = 176;
             if (PendingPlayer.Male)
             {
                 array9[4] = Lang.menu[22].Value;
             }
             else
             {
                 array9[4] = Lang.menu[23].Value;
             }
             if (selectedMenu == 4)
             {
                 if (PendingPlayer.Male)
                 {
                     SoundEngine.PlaySound(20);
                     PendingPlayer.Male = false;
                 }
                 else
                 {
                     SoundEngine.PlaySound(1);
                     PendingPlayer.Male = true;
                 }
             }
             if (PendingPlayer.difficulty == 2)
             {
                 array9[5] = Lang.menu[24].Value;
                 array6[5] = PendingPlayer.difficulty;
             }
             else if (PendingPlayer.difficulty == 1)
             {
                 array9[5] = Lang.menu[25].Value;
                 array6[5] = PendingPlayer.difficulty;
             }
             else
             {
                 array9[5] = Lang.menu[26].Value;
             }
             if (selectedMenu == 5)
             {
                 SoundEngine.PlaySound(10);
                 menuMode = 222;
             }
             if (selectedMenu == 7)
             {
                 SoundEngine.PlaySound(12);
                 PendingPlayer.hair = rand.Next(51);
                 PendingPlayer.eyeColor = randColor();
                 while (PendingPlayer.eyeColor.R + PendingPlayer.eyeColor.G + PendingPlayer.eyeColor.B > 300)
                 {
                     PendingPlayer.eyeColor = randColor();
                 }
                 PendingPlayer.hairColor = randColor();
                 PendingPlayer.pantsColor = randColor();
                 PendingPlayer.shirtColor = randColor();
                 PendingPlayer.shoeColor = randColor();
                 PendingPlayer.skinColor = randColor();
                 float num13 = (float)rand.Next(60, 120) * 0.01f;
                 if (num13 > 1f)
                 {
                     num13 = 1f;
                 }
                 PendingPlayer.skinColor.R = (byte)((float)rand.Next(240, 255) * num13);
                 PendingPlayer.skinColor.G = (byte)((float)rand.Next(110, 140) * num13);
                 PendingPlayer.skinColor.B = (byte)((float)rand.Next(75, 110) * num13);
                 PendingPlayer.underShirtColor = randColor();
                 int num14 = PendingPlayer.hair + 1;
                 if (num14 == 5 || num14 == 6 || num14 == 7 || num14 == 10 || num14 == 12 || num14 == 19 || num14 == 22 || num14 == 23 || num14 == 26 || num14 == 27 || num14 == 30 || num14 == 33)
                 {
                     PendingPlayer.Male = false;
                 }
                 else
                 {
                     PendingPlayer.Male = true;
                 }
                 PendingPlayer.skinVariant = rand.Next(PlayerVariantID.Count);
             }
             array9[7] = Lang.menu[27].Value;
             array9[6] = Lang.menu[28].Value;
             array9[8] = Lang.menu[5].Value;
             num5 = 9;
             if (selectedMenu == 8 || flag5)
             {
                 flag5 = false;
                 SoundEngine.PlaySound(11);
                 menuMode = 1;
             }
             else if (selectedMenu == 6)
             {
                 SoundEngine.PlaySound(10);
                 PendingPlayer.name = "";
                 menuMode = 3;
                 clrInput();
             }
         }
         else if (menuMode == 222)
         {
             if (focusMenu == 3)
             {
                 array9[0] = Lang.menu[29].Value;
             }
             else if (focusMenu == 2)
             {
                 array9[0] = Lang.menu[30].Value;
             }
             else if (focusMenu == 1)
             {
                 array9[0] = Lang.menu[31].Value;
             }
             else
             {
                 array9[0] = Lang.menu[32].Value;
             }
             num4 = 50;
             array4[1] = 25;
             array4[2] = 25;
             array4[3] = 25;
             array[0] = true;
             array9[1] = Lang.menu[26].Value;
             array9[2] = Lang.menu[25].Value;
             array6[2] = 1;
             array9[3] = Lang.menu[24].Value;
             array6[3] = 2;
             num5 = 4;
             if (selectedMenu == 1)
             {
                 PendingPlayer.difficulty = 0;
                 menuMode = 2;
             }
             else if (selectedMenu == 2)
             {
                 menuMode = 2;
                 PendingPlayer.difficulty = 1;
             }
             else if (selectedMenu == 3)
             {
                 PendingPlayer.difficulty = 2;
                 menuMode = 2;
             }
         }
         else if (menuMode == 20)
         {
             flag4 = true;
             if (selectedMenu == 0)
             {
                 menuMode = 21;
                 SoundEngine.PlaySound(10);
                 selColor = PendingPlayer.shirtColor;
             }
             if (selectedMenu == 1)
             {
                 menuMode = 22;
                 SoundEngine.PlaySound(10);
                 selColor = PendingPlayer.underShirtColor;
             }
             if (selectedMenu == 2)
             {
                 menuMode = 23;
                 SoundEngine.PlaySound(10);
                 selColor = PendingPlayer.pantsColor;
             }
             if (selectedMenu == 3)
             {
                 selColor = PendingPlayer.shoeColor;
                 menuMode = 24;
                 SoundEngine.PlaySound(10);
             }
             if (selectedMenu == 5 || flag5)
             {
                 flag5 = false;
                 SoundEngine.PlaySound(11);
                 menuMode = 2;
             }
             if (selectedMenu == 4)
             {
                 SoundEngine.PlaySound(12);
                 CycleClothingStyle(PendingPlayer);
             }
             num7 = screenWidth / 2 - 16;
             num8 = 210;
             num2 = 260;
             num4 = 50;
             num5 = 6;
             array9[0] = Lang.menu[33].Value;
             array9[1] = Lang.menu[34].Value;
             array9[2] = Lang.menu[35].Value;
             array9[3] = Lang.menu[36].Value;
             array9[4] = Lang.menu[127].Value;
             array9[5] = Lang.menu[5].Value;
             array4[5] = 20;
         }
         else if (menuMode == 17)
         {
             flag4 = true;
             num7 = screenWidth / 2 - 16;
             num8 = 210;
             flag = true;
             num9 = 390;
             num2 = 260;
             num4 = 60;
             PendingPlayer.hairColor = selColor;
             num5 = 3;
             array9[0] = Lang.menu[37].Value + " " + (PendingPlayer.hair + 1);
             array9[1] = Lang.menu[38].Value;
             array[1] = true;
             array4[2] = 150;
             array4[1] = 10;
             array9[2] = Lang.menu[5].Value;
             int num15 = 51;
             if (focusMenu == 0)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 9;
             }
             if (selectedMenu == 0)
             {
                 SoundEngine.PlaySound(12);
                 PendingPlayer.hair++;
                 if (PendingPlayer.hair >= num15)
                 {
                     PendingPlayer.hair = 0;
                 }
             }
             else if (selectedMenu2 == 0)
             {
                 SoundEngine.PlaySound(12);
                 PendingPlayer.hair--;
                 if (PendingPlayer.hair < 0)
                 {
                     PendingPlayer.hair = num15 - 1;
                 }
             }
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 menuMode = 2;
                 SoundEngine.PlaySound(11);
             }
         }
         else if (menuMode == 18)
         {
             flag4 = true;
             num7 = screenWidth / 2 - 16;
             num8 = 210;
             flag = true;
             num9 = 370;
             num2 = 240;
             num4 = 60;
             PendingPlayer.eyeColor = selColor;
             num5 = 3;
             array9[0] = "";
             array9[1] = Lang.menu[39].Value;
             array[1] = true;
             array4[2] = 170;
             array4[1] = 10;
             array9[2] = Lang.menu[5].Value;
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 menuMode = 2;
                 SoundEngine.PlaySound(11);
             }
         }
         else if (menuMode == 19)
         {
             flag4 = true;
             num7 = screenWidth / 2 - 16;
             num8 = 210;
             flag = true;
             num9 = 370;
             num2 = 240;
             num4 = 60;
             PendingPlayer.skinColor = selColor;
             num5 = 3;
             array9[0] = "";
             array9[1] = Lang.menu[40].Value;
             array[1] = true;
             array4[2] = 170;
             array4[1] = 10;
             array9[2] = Lang.menu[5].Value;
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 menuMode = 2;
                 SoundEngine.PlaySound(11);
             }
         }
         else if (menuMode == 21)
         {
             flag4 = true;
             num7 = screenWidth / 2 - 16;
             num8 = 210;
             flag = true;
             num9 = 370;
             num2 = 240;
             num4 = 60;
             PendingPlayer.shirtColor = selColor;
             num5 = 3;
             array9[0] = "";
             array9[1] = Lang.menu[41].Value;
             array[1] = true;
             array4[2] = 170;
             array4[1] = 10;
             array9[2] = Lang.menu[5].Value;
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 menuMode = 20;
                 SoundEngine.PlaySound(11);
             }
         }
         else if (menuMode == 22)
         {
             flag4 = true;
             num7 = screenWidth / 2 - 16;
             num8 = 210;
             flag = true;
             num9 = 370;
             num2 = 240;
             num4 = 60;
             PendingPlayer.underShirtColor = selColor;
             num5 = 3;
             array9[0] = "";
             array9[1] = Lang.menu[42].Value;
             array[1] = true;
             array4[2] = 170;
             array4[1] = 10;
             array9[2] = Lang.menu[5].Value;
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 menuMode = 20;
                 SoundEngine.PlaySound(11);
             }
         }
         else if (menuMode == 23)
         {
             flag4 = true;
             num7 = screenWidth / 2 - 16;
             num8 = 210;
             flag = true;
             num9 = 370;
             num2 = 240;
             num4 = 60;
             PendingPlayer.pantsColor = selColor;
             num5 = 3;
             array9[0] = "";
             array9[1] = Lang.menu[43].Value;
             array[1] = true;
             array4[2] = 170;
             array4[1] = 10;
             array9[2] = Lang.menu[5].Value;
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 menuMode = 20;
                 SoundEngine.PlaySound(11);
             }
         }
         else if (menuMode == 24)
         {
             flag4 = true;
             num7 = screenWidth / 2 - 16;
             num8 = 210;
             flag = true;
             num9 = 370;
             num2 = 240;
             num4 = 60;
             PendingPlayer.shoeColor = selColor;
             num5 = 3;
             array9[0] = "";
             array9[1] = Lang.menu[44].Value;
             array[1] = true;
             array4[2] = 170;
             array4[1] = 10;
             array9[2] = Lang.menu[5].Value;
             if (selectedMenu == 2 || flag5)
             {
                 flag5 = false;
                 menuMode = 20;
                 SoundEngine.PlaySound(11);
             }
         }
         else if (menuMode == 3)
         {
             UIVirtualKeyboard uIVirtualKeyboard3 = new UIVirtualKeyboard(Lang.menu[45].Value, "", OnCharacterNamed, CreateGoToMenuEvent(2));
             uIVirtualKeyboard3.SetMaxInputLength(20);
             menuMode = 888;
             MenuUI.SetState(uIVirtualKeyboard3);
         }
         else if (menuMode != 4)
         {
             if (menuMode == 5)
             {
                 array9[0] = Lang.menu[46].Value + " " + PlayerList[selectedPlayer].Player.name + "?";
                 array[0] = true;
                 array9[1] = Lang.menu[104].Value;
                 array9[2] = Lang.menu[105].Value;
                 num5 = 3;
                 if (selectedMenu == 1)
                 {
                     ErasePlayer(selectedPlayer);
                     SoundEngine.PlaySound(10);
                     menuMode = 1;
                 }
                 else if (selectedMenu == 2 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = 1;
                 }
             }
             else if (menuMode == 6)
             {
                 menuMode = 888;
                 MenuUI.SetState(_worldSelectMenu);
             }
             else if (menuMode == -7)
             {
                 num2 = 200;
                 num4 = 60;
                 array4[2] = 30;
                 array4[3] = 30;
                 array4[4] = 30;
                 array6[3] = 1;
                 array6[4] = 2;
                 array4[5] = 70;
                 if (focusMenu == 2)
                 {
                     array9[1] = Language.GetTextValue("UI.WorldDescriptionNormal");
                 }
                 else if (focusMenu == 3)
                 {
                     array9[1] = Language.GetTextValue("UI.WorldDescriptionExpert");
                 }
                 else if (focusMenu == 4)
                 {
                     array9[1] = Language.GetTextValue("UI.WorldDescriptionMaster");
                 }
                 array9[0] = Lang.menu[32].Value;
                 array[0] = true;
                 array[1] = true;
                 array9[2] = Language.GetTextValue("UI.Normal");
                 array9[3] = Language.GetTextValue("UI.Expert");
                 array9[4] = Language.GetTextValue("UI.Master");
                 array9[5] = Language.GetTextValue("UI.Back");
                 num5 = 6;
                 if (selectedMenu == 2)
                 {
                     GameMode = 0;
                     SoundEngine.PlaySound(10);
                     menuMode = 7;
                     if (SettingsUnlock_WorldEvil)
                     {
                         menuMode = -71;
                     }
                 }
                 else if (selectedMenu == 3)
                 {
                     GameMode = 1;
                     SoundEngine.PlaySound(10);
                     menuMode = 7;
                     if (SettingsUnlock_WorldEvil)
                     {
                         menuMode = -71;
                     }
                 }
                 else if (selectedMenu == 4)
                 {
                     GameMode = 2;
                     SoundEngine.PlaySound(10);
                     menuMode = 7;
                     if (SettingsUnlock_WorldEvil)
                     {
                         menuMode = -71;
                     }
                 }
                 else if (selectedMenu == 5 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = 16;
                 }
                 clrInput();
             }
             else if (menuMode == -71)
             {
                 num2 = 200;
                 num4 = 60;
                 array4[1] = 30;
                 array4[2] = 30;
                 array4[3] = 30;
                 array4[4] = 70;
                 num5 = 5;
                 int num16 = 0;
                 array9[num16] = Lang.misc[100].Value;
                 array[num16] = true;
                 num16++;
                 array9[num16] = Lang.misc[101].Value;
                 if (selectedMenu == num16)
                 {
                     WorldGen.WorldGenParam_Evil = 0;
                     SoundEngine.PlaySound(10);
                     menuMode = 7;
                 }
                 num16++;
                 array9[num16] = Lang.misc[102].Value;
                 if (selectedMenu == num16)
                 {
                     WorldGen.WorldGenParam_Evil = 1;
                     SoundEngine.PlaySound(10);
                     menuMode = 7;
                 }
                 num16++;
                 array9[num16] = Lang.misc[103].Value;
                 if (selectedMenu == num16)
                 {
                     WorldGen.WorldGenParam_Evil = -1;
                     SoundEngine.PlaySound(10);
                     menuMode = 7;
                 }
                 num16++;
                 array9[num16] = Language.GetTextValue("UI.Back");
                 if (selectedMenu == num16 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = -7;
                 }
                 num16++;
                 clrInput();
             }
             else if (menuMode == 7)
             {
                 menuMode = 888;
                 MenuUI.SetState(new UIVirtualKeyboard(Lang.menu[48].Value, "", OnWorldNamed, CreateGoToMenuEvent(-7)));
             }
             else if (menuMode == 5000)
             {
                 menuMode = 888;
                 MenuUI.SetState(new UIVirtualKeyboard(Language.GetTextValue("UI.EnterSeed"), "", OnSeedSelected, CreateGoToMenuEvent(7), 0, allowEmpty: true));
             }
             else if (menuMode == 8)
             {
                 num2 = 180;
                 num4 = 40;
                 num5 = 8;
                 array4[7] += 30;
                 for (int num17 = 0; num17 < num5; num17++)
                 {
                     array7[num17] = 0.8f;
                 }
                 array9[7] = Lang.menu[5].Value;
                 for (int num18 = 0; num18 < 7; num18++)
                 {
                     if (num18 < WorldList.Count)
                     {
                         array9[num18] = WorldList[num18 + menuSkip].Name;
                         if (WorldList[num18 + menuSkip].GameMode == 1)
{
                             array6[num18] = 1;
                         }
                         else if (WorldList[num18 + menuSkip].GameMode == 2)
{
                             array6[num18] = 2;
                         }
                     }
                     else
                     {
                         array9[num18] = null;
                     }
                 }
                 if (WorldList.Count > 7 + menuSkip)
                 {
                     array9[6] = Language.GetTextValue("UI.More");
                     array9[6] = "";
                     array7[6] = 0.6f;
                     array4[6] += 8;
                     menuWide[6] = true;
                 }
                 if (menuSkip > 0)
                 {
                     array9[0] = "";
                     array7[0] = 0.6f;
                     array4[0] += 8;
                     menuWide[0] = true;
                 }
                 if (selectedMenu == 0 && menuSkip > 0)
                 {
                     SoundEngine.PlaySound(12);
                     menuSkip -= 5;
                     if (menuSkip < 0)
                     {
                         menuSkip = 0;
                     }
                 }
                 else if (selectedMenu == 6 && menuSkip < WorldList.Count - 7)
                 {
                     SoundEngine.PlaySound(12);
                     menuSkip += 5;
                     if (menuSkip >= PlayerList.Count - 7)
                     {
                         menuSkip = WorldList.Count - 7;
                     }
                 }
                 else if (selectedMenu == 7 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = 6;
                 }
                 else if (selectedMenu >= 0)
                 {
                     selectedWorld = selectedMenu + menuSkip;
                     SoundEngine.PlaySound(10);
                     menuMode = 9;
                 }
             }
             else if (menuMode == 9)
             {
                 array9[0] = Lang.menu[46].Value + " " + WorldList[selectedWorld].Name + "?";
                 array[0] = true;
                 array9[1] = Lang.menu[104].Value;
                 array9[2] = Lang.menu[105].Value;
                 num5 = 3;
                 if (selectedMenu == 1)
                 {
                     EraseWorld(selectedWorld);
                     SoundEngine.PlaySound(10);
                     menuMode = 6;
                 }
                 else if (selectedMenu == 2 || flag5)
                 {
                     SoundEngine.PlaySound(11);
                     menuMode = 6;
                 }
             }
             else if (menuMode == 3000)
             {
                 num5 = 1;
                 num2 = 500;
                 array7[0] = 0.9f;
                 array9[0] = Lang.menu[5].Value;
                 if (selectedMenu == 0 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = 0;
                 }
             }
             else if (menuMode == 11)
             {
                 num2 = 210;
                 num4 = 37;
                 num5 = 8;
                 array4[num5 - 1] = 8;
                 for (int num19 = 0; num19 < num5; num19++)
                 {
                     array7[num19] = 0.75f;
                 }
                 int num20 = 0;
                 array9[num20] = Lang.menu[114].Value;
                 if (selectedMenu == num20)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 112;
                 }
                 num20++;
                 array9[num20] = Lang.menu[210].Value;
                 if (selectedMenu == num20)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 1112;
                 }
                 num20++;
                 array9[num20] = Lang.menu[63].Value;
                 if (selectedMenu == num20)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 1111;
                 }
                 num20++;
                 array9[num20] = Lang.menu[65].Value;
                 if (selectedMenu == num20)
                 {
                     SoundEngine.PlaySound(11);
                     menuMode = 26;
                 }
                 num20++;
                 array9[num20] = Lang.menu[218].Value;
                 if (selectedMenu == num20)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 1125;
                 }
                 num20++;
                 array9[num20] = Lang.menu[219].Value;
                 if (selectedMenu == num20)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 1127;
                 }
                 num20++;
                 array9[num20] = Lang.menu[103].Value;
                 if (selectedMenu == num20)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 1213;
                 }
                 num20++;
                 array9[num20] = Lang.menu[5].Value;
                 if (selectedMenu == num20 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = 0;
                     SaveSettings();
                 }
             }
             else if (menuMode == 112)
             {
                 num2 = 250;
                 num4 = 52;
                 num5 = 5;
                 array4[num5 - 1] = 18;
                 for (int num21 = 0; num21 < num5; num21++)
                 {
                     array7[num21] = 0.78f;
                 }
                 int num22 = 0;
                 if (autoSave)
                 {
                     array9[num22] = Lang.menu[67].Value;
                 }
                 else
                 {
                     array9[num22] = Lang.menu[68].Value;
                 }
                 if (selectedMenu == num22)
                 {
                     SoundEngine.PlaySound(12);
                     if (autoSave)
                     {
                         autoSave = false;
                     }
                     else
                     {
                         autoSave = true;
                     }
                 }
                 num22++;
                 if (autoPause)
                 {
                     array9[num22] = Lang.menu[69].Value;
                 }
                 else
                 {
                     array9[num22] = Lang.menu[70].Value;
                 }
                 if (selectedMenu == num22)
                 {
                     SoundEngine.PlaySound(12);
                     if (autoPause)
                     {
                         autoPause = false;
                     }
                     else
                     {
                         autoPause = true;
                     }
                 }
                 num22++;
                 if (mapEnabled)
                 {
                     array9[num22] = Lang.menu[112].Value;
                 }
                 else
                 {
                     array9[num22] = Lang.menu[113].Value;
                 }
                 if (selectedMenu == num22)
                 {
                     SoundEngine.PlaySound(12);
                     if (mapEnabled)
                     {
                         mapEnabled = false;
                     }
                     else
                     {
                         mapEnabled = true;
                     }
                 }
                 num22++;
                 array9[num22] = (HidePassword ? Lang.menu[212].Value : Lang.menu[211].Value);
                 if (selectedMenu == num22)
                 {
                     SoundEngine.PlaySound(12);
                     HidePassword = !HidePassword;
                 }
                 num22++;
                 array9[num22] = Lang.menu[5].Value;
                 if (selectedMenu == num22 || flag5)
                 {
                     flag5 = false;
                     menuMode = 11;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 1112)
             {
                 num2 = 210;
                 num4 = 32;
                 num5 = 10;
                 array4[num5 - 1] = 18;
                 for (int num23 = 0; num23 < num5; num23++)
                 {
                     array7[num23] = 0.7f;
                 }
                 int num24 = 0;
                 if (showItemText)
                 {
                     array9[num24] = Lang.menu[71].Value;
                 }
                 else
                 {
                     array9[num24] = Lang.menu[72].Value;
                 }
                 if (selectedMenu == num24)
                 {
                     SoundEngine.PlaySound(12);
                     if (showItemText)
                     {
                         showItemText = false;
                     }
                     else
                     {
                         showItemText = true;
                     }
                 }
                 num24++;
                 array9[num24] = Lang.menu[123].Value + " " + Lang.menu[124 + invasionProgressMode].Value;
                 if (selectedMenu == num24)
                 {
                     SoundEngine.PlaySound(12);
                     invasionProgressMode++;
                     if (invasionProgressMode >= 3)
                     {
                         invasionProgressMode = 0;
                     }
                 }
                 num24++;
                 array9[num24] = (placementPreview ? Lang.menu[128].Value : Lang.menu[129].Value);
                 if (selectedMenu == num24)
                 {
                     SoundEngine.PlaySound(12);
                     placementPreview = !placementPreview;
                 }
                 num24++;
                 array9[num24] = (ItemSlot.Options.HighlightNewItems ? Lang.inter[117].Value : Lang.inter[116].Value);
                 if (selectedMenu == num24)
                 {
                     SoundEngine.PlaySound(12);
                     ItemSlot.Options.HighlightNewItems = !ItemSlot.Options.HighlightNewItems;
                 }
                 num24++;
                 array9[num24] = (MouseShowBuildingGrid ? Lang.menu[229].Value : Lang.menu[230].Value);
                 if (selectedMenu == num24)
                 {
                     SoundEngine.PlaySound(12);
                     MouseShowBuildingGrid = !MouseShowBuildingGrid;
                 }
                 num24++;
                 array9[num24] = (GamepadDisableInstructionsDisplay ? Lang.menu[241].Value : Lang.menu[242].Value);
                 if (selectedMenu == num24)
                 {
                     SoundEngine.PlaySound(12);
                     GamepadDisableInstructionsDisplay = !GamepadDisableInstructionsDisplay;
                 }
                 num24++;
                 string textValue = Language.GetTextValue("UI.MinimapFrame_" + MinimapFrameManagerInstance.ActiveSelectionKeyName);
                 array9[num24] = Language.GetTextValue("UI.SelectMapBorder", textValue);
                 if (selectedMenu == num24)
                 {
                     MinimapFrameManagerInstance.CycleSelection();
                 }
                 num24++;
                 string activeSetKeyName = ResourceSetsManager.ActiveSetKeyName;
                 string textValue2 = Language.GetTextValue("UI.HealthManaStyle_" + activeSetKeyName);
                 array9[num24] = Language.GetTextValue("UI.SelectHealthStyle", textValue2);
                 if (selectedMenu == num24)
                 {
                     ResourceSetsManager.CycleResourceSet();
                 }
                 num24++;
                 array9[num24] = Language.GetTextValue(BigProgressBarSystem.ShowText ? "UI.ShowBossLifeTextOn" : "UI.ShowBossLifeTextOff");
                 if (selectedMenu == num24)
                 {
                     BigProgressBarSystem.ToggleShowText();
                 }
                 num24++;
                 array9[num24] = Lang.menu[5].Value;
                 if (selectedMenu == num24 || flag5)
                 {
                     flag5 = false;
                     menuMode = 11;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 1111)
             {
                 bgScroll = (int)Math.Round((1f - caveParallax) * 500f);
                 int num25 = 0;
                 array9[num25] = Lang.menu[51].Value;
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 111;
                 }
                 num25++;
                 array9[num25] = Lang.menu[52].Value;
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(11);
                     menuMode = 28;
                 }
                 num25++;
                 array9[num25] = Lang.menu[(int)(247 + FrameSkipMode)].Value;
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(12);
                     CycleFrameSkipMode();
                 }
                 num25++;
                 array9[num25] = Language.GetTextValue("UI.LightMode_" + Lighting.Mode);
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(12);
                     Lighting.NextLightMode();
                 }
                 num25++;
                 switch (qaStyle)
                 {
                 case 0:
                     array9[num25] = Lang.menu[59].Value;
                     break;
                 case 1:
                     array9[num25] = Lang.menu[60].Value;
                     break;
                 case 2:
                     array9[num25] = Lang.menu[61].Value;
                     break;
                 default:
                     array9[num25] = Lang.menu[62].Value;
                     break;
                 }
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(12);
                     if (++qaStyle > 3)
                     {
                         qaStyle = 0;
                     }
                 }
                 num25++;
                 array9[num25] = (BackgroundEnabled ? Lang.menu[100].Value : Lang.menu[101].Value);
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(12);
                     BackgroundEnabled = !BackgroundEnabled;
                 }
                 num25++;
                 array9[num25] = (ChildSafety.Disabled ? Lang.menu[132].Value : Lang.menu[133].Value);
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(12);
                     ChildSafety.Disabled = !ChildSafety.Disabled;
                 }
                 num25++;
                 array9[num25] = (SettingsEnabled_MinersWobble ? Lang.menu[250].Value : Lang.menu[251].Value);
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(12);
                     SettingsEnabled_MinersWobble = !SettingsEnabled_MinersWobble;
                 }
                 num25++;
                 array9[num25] = (SettingsEnabled_TilesSwayInWind ? Language.GetTextValue("UI.TilesSwayInWindOn") : Language.GetTextValue("UI.TilesSwayInWindOff"));
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(12);
                     SettingsEnabled_TilesSwayInWind = !SettingsEnabled_TilesSwayInWind;
                 }
                 num25++;
                 array9[num25] = Language.GetTextValue("UI.Effects");
                 if (selectedMenu == num25)
                 {
                     SoundEngine.PlaySound(11);
                     menuMode = 2008;
                 }
                 int num26 = num25;
                 int num27 = num26;
                 array9[num27] = Lang.menu[5].Value;
                 array4[num27] = 8;
                 if (selectedMenu == num27 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     SaveSettings();
                     menuMode = 11;
                 }
                 num2 = 186;
                 num4 = 30;
                 num5 = num27 + 1;
                 for (int num28 = 0; num28 < num26; num28++)
                 {
                     array7[num28] = 0.6f;
                 }
             }
             else if (menuMode == 2008)
             {
                 num2 = 240;
                 num4 = 60;
                 num5 = 6;
                 array9[0] = "";
                 array9[1] = Language.GetTextValue("UI.Effects");
                 array[1] = true;
                 array4[1] = 10;
                 array9[2] = Language.GetTextValue("GameUI.StormEffects", UseStormEffects ? Language.GetTextValue("GameUI.Enabled") : Language.GetTextValue("GameUI.Disabled"));
                 array7[2] = 0.8f;
                 array9[3] = Language.GetTextValue("GameUI.HeatDistortion", UseHeatDistortion ? Language.GetTextValue("GameUI.Enabled") : Language.GetTextValue("GameUI.Disabled"));
                 array7[3] = 0.8f;
                 array9[4] = Language.GetTextValue("GameUI.WaveQuality", WaveQuality switch
                 {
                     1 => Language.GetTextValue("GameUI.QualityLow"),
                     2 => Language.GetTextValue("GameUI.QualityMedium"),
                     3 => Language.GetTextValue("GameUI.QualityHigh"),
                     _ => Language.GetTextValue("GameUI.QualityOff"),
                 });
                 array7[4] = 0.8f;
                 array9[5] = Lang.menu[5].Value;
                 if (selectedMenu == 2)
                 {
                     UseStormEffects = !UseStormEffects;
                 }
                 if (selectedMenu == 3)
                 {
                     UseHeatDistortion = !UseHeatDistortion;
                 }
                 if (selectedMenu == 4)
                 {
                     WaveQuality = (WaveQuality + 1) % 4;
                 }
                 if (selectedMenu == 5 || flag5)
                 {
                     flag5 = false;
                     menuMode = 1111;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 111)
             {
                 for (int num29 = 0; num29 < 9; num29++)
                 {
                     array7[num29] = 0.85f;
                 }
                 num2 = 210;
                 num4 = 55;
                 int num30 = 0;
                 array9[num30] = Lang.menu[73].Value + ": " + PendingResolutionWidth + "x" + PendingResolutionHeight;
                 if (selectedMenu == num30)
                 {
                     SoundEngine.PlaySound(12);
                     int num31 = 0;
                     for (int num32 = 0; num32 < numDisplayModes; num32++)
                     {
                         if (displayWidth[num32] == PendingResolutionWidth && displayHeight[num32] == PendingResolutionHeight)
{
                             num31 = num32;
                             break;
                         }
                     }
                     num31 = (num31 + 1) % numDisplayModes;
                     PendingResolutionWidth = displayWidth[num31];
                     PendingResolutionHeight = displayHeight[num31];
                 }
                 num30++;
                 if (IsBorderlessDisplayAvailable())
                 {
                     array9[num30] = Lang.menu[PendingBorderlessState ? 245 : 246].Value;
                     if (selectedMenu == num30)
                     {
                         SoundEngine.PlaySound(12);
                         PendingBorderlessState = !PendingBorderlessState;
                     }
                     num30++;
                 }
                 array9[num30] = (graphics.IsFullScreen ? Lang.menu[49].Value : Lang.menu[50].Value);
                 if (selectedMenu == num30)
                 {
                     ToggleFullScreen();
                 }
                 num30++;
                 array4[num30] = 100;
                 array9[num30] = Lang.menu[134].Value;
                 if (selectedMenu == num30)
                 {
                     if (graphics.IsFullScreen || PendingBorderlessState != screenBorderless || PendingResolutionWidth != screenWidth || PendingResolutionHeight != screenHeight)
                     {
                         screenBorderless = PendingBorderlessState;
                         screenBorderlessPendingResizes = (screenBorderless ? 6 : 0);
                         SetResolution(PendingResolutionWidth, PendingResolutionHeight);
                     }
                     SoundEngine.PlaySound(11);
                     menuMode = 1111;
                 }
                 num30++;
                 array9[num30] = Lang.menu[5].Value;
                 array4[num30] = 100;
                 if (selectedMenu == num30 || flag5)
                 {
                     flag5 = false;
                     PendingResolutionWidth = graphics.PreferredBackBufferWidth;
                     PendingResolutionHeight = graphics.PreferredBackBufferHeight;
                     PendingBorderlessState = screenBorderless;
                     menuMode = 1111;
                     SoundEngine.PlaySound(11);
                 }
                 num30++;
                 num5 = num30;
             }
             else if (menuMode == 1125)
             {
                 num2 = 232;
                 num4 = 38;
                 num5 = 7;
                 array4[num5 - 1] = 18;
                 for (int num33 = 0; num33 < num5; num33++)
                 {
                     array7[num33] = 0.73f;
                 }
                 int num34 = 0;
                 array9[num34] = Lang.menu[64].Value;
                 if (selectedMenu == num34)
                 {
                     SoundEngine.PlaySound(10);
                     selColor = mouseColor;
                     mouseColorSlider.SetHSL(mouseColor);
                     menuMode = 25;
                 }
                 num34++;
                 array9[num34] = Lang.menu[217].Value;
                 if (selectedMenu == num34)
                 {
                     SoundEngine.PlaySound(10);
                     selColor = MouseBorderColor;
                     mouseBorderColorSlider.SetHSL(mouseColor);
                     menuMode = 252;
                 }
                 num34++;
                 array9[num34] = (cSmartCursorModeIsToggleAndNotHold ? Lang.menu[121].Value : Lang.menu[122].Value);
                 if (selectedMenu == num34)
                 {
                     SoundEngine.PlaySound(12);
                     cSmartCursorModeIsToggleAndNotHold = !cSmartCursorModeIsToggleAndNotHold;
                 }
                 num34++;
                 array9[num34] = (Player.SmartCursorSettings.SmartAxeAfterPickaxe ? Lang.menu[214].Value : Lang.menu[213].Value);
                 if (selectedMenu == num34)
                 {
                     SoundEngine.PlaySound(12);
                     Player.SmartCursorSettings.SmartAxeAfterPickaxe = !Player.SmartCursorSettings.SmartAxeAfterPickaxe;
                 }
                 num34++;
                 array9[num34] = (Player.SmartCursorSettings.SmartBlocksEnabled ? Lang.menu[215].Value : Lang.menu[216].Value);
                 if (selectedMenu == num34)
                 {
                     SoundEngine.PlaySound(12);
                     Player.SmartCursorSettings.SmartBlocksEnabled = !Player.SmartCursorSettings.SmartBlocksEnabled;
                 }
                 num34++;
                 switch (LockOnHelper.UseMode)
                 {
                 case LockOnHelper.LockOnMode.FocusTarget:
                     array9[num34] = Lang.menu[232].Value;
                     break;
                 case LockOnHelper.LockOnMode.TargetClosest:
                     array9[num34] = Lang.menu[233].Value;
                     break;
                 case LockOnHelper.LockOnMode.ThreeDS:
                     array9[num34] = Lang.menu[234].Value;
                     break;
                 }
                 if (selectedMenu == num34)
                 {
                     SoundEngine.PlaySound(12);
                     LockOnHelper.CycleUseModes();
                 }
                 num34++;
                 array9[num34] = Lang.menu[5].Value;
                 if (selectedMenu == num34 || flag5)
                 {
                     flag5 = false;
                     menuMode = 11;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 25)
             {
                 flag = true;
                 num9 = 320;
                 num2 = 200;
                 num4 = 10;
                 mouseColor = selColor;
                 mouseColorSlider.SetHSL(mouseColor);
                 num5 = 3;
                 array9[0] = "";
                 array9[1] = Lang.menu[64].Value;
                 array[1] = true;
                 array4[2] = 250;
                 array4[1] = 10;
                 array9[2] = Lang.menu[5].Value;
                 if (selectedMenu == 2 || flag5)
                 {
                     flag5 = false;
                     menuMode = 1125;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 252)
             {
                 flag = true;
                 num9 = 320;
                 num2 = 200;
                 num4 = 10;
                 MouseBorderColor = selColor;
                 mouseBorderColorSlider.SetHSL(mouseColor);
                 num5 = 3;
                 array9[0] = "";
                 array9[1] = Lang.menu[217].Value;
                 array[1] = true;
                 array4[2] = 250;
                 array4[1] = 10;
                 array9[2] = Lang.menu[5].Value;
                 if (selectedMenu == 2 || flag5)
                 {
                     flag5 = false;
                     menuMode = 1125;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 26)
             {
                 flag2 = true;
                 num2 = 200;
                 num4 = 10;
                 num5 = 3;
                 array9[0] = "";
                 array9[1] = Lang.menu[65].Value;
                 array[1] = true;
                 array4[2] = 250;
                 array4[1] = 10;
                 array9[2] = Lang.menu[5].Value;
                 if (selectedMenu == 2 || flag5)
                 {
                     flag5 = false;
                     menuMode = 11;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 28)
             {
                 caveParallax = 1f - (float)bgScroll / 500f;
                 flag3 = true;
                 num2 = 240;
                 num4 = 60;
                 num5 = 3;
                 array9[0] = "";
                 array9[1] = Lang.menu[52].Value;
                 array[1] = true;
                 array4[2] = 170;
                 array4[1] = 10;
                 array9[2] = Lang.menu[5].Value;
                 if (selectedMenu == 2 || flag5)
                 {
                     flag5 = false;
                     menuMode = 1111;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 272727)
             {
                 num2 = 200;
                 num4 = 30;
                 num5 = 14;
                 string[] array10 = new string[12]
                 {
                     cMapStyle, cMapFull, cMapZoomIn, cMapZoomOut, cMapAlphaUp, cMapAlphaDown, null, null, null, null,
                     null, null
                 };
                 if (setKey >= 0)
                 {
                     array10[setKey] = "_";
                 }
                 array9[0] = Lang.menu[106].Value + array10[0];
                 array9[1] = Lang.menu[107].Value + array10[1];
                 array9[2] = Lang.menu[108].Value + array10[2];
                 array9[3] = Lang.menu[109].Value + array10[3];
                 array9[4] = Lang.menu[110].Value + array10[4];
                 array9[5] = Lang.menu[111].Value + array10[5];
                 for (int num35 = 0; num35 < 6; num35++)
                 {
                     array8[num35] = true;
                     array7[num35] = 0.55f;
                     array5[num35] = -140;
                 }
                 array7[6] = 0.8f;
                 array7[6] = 0.8f;
                 array4[6] = 6;
                 array9[6] = Lang.menu[86].Value;
                 array4[7] = 16;
                 array9[7] = Lang.menu[5].Value;
                 if (selectedMenu == 7 || flag5)
                 {
                     flag5 = false;
                     menuMode = 11;
                     SoundEngine.PlaySound(11);
                 }
                 else if (selectedMenu == 6)
                 {
                     cMapStyle = "Tab";
                     cMapFull = "M";
                     cMapZoomIn = "Add";
                     cMapZoomOut = "Subtract";
                     cMapAlphaUp = "PageUp";
                     cMapAlphaDown = "PageDown";
                     setKey = -1;
                     SoundEngine.PlaySound(11);
                 }
                 else if (selectedMenu >= 0)
                 {
                     setKey = selectedMenu;
                 }
                 if (setKey >= 0)
                 {
                     List<Microsoft.Xna.Framework.Input.Keys> pressedKeys = PlayerInput.GetPressedKeys();
                     if (pressedKeys.Count > 0)
                     {
                         string text = string.Concat(pressedKeys[0]);
                         if (text != "None")
{
                             if (setKey == 0)
{
                                 cMapStyle = text;
                             }
                             if (setKey == 1)
{
                                 cMapFull = text;
                             }
                             if (setKey == 2)
{
                                 cMapZoomIn = text;
                             }
                             if (setKey == 3)
{
                                 cMapZoomOut = text;
                             }
                             if (setKey == 4)
{
                                 cMapAlphaUp = text;
                             }
                             if (setKey == 5)
{
                                 cMapAlphaDown = text;
                             }
                             setKey = -1;
                         }
                     }
                 }
             }
             else if (menuMode == 27)
             {
                 num2 = 176;
                 num4 = 22;
                 num5 = 16;
                 string[] array11 = new string[14]
                 {
                     cUp, cDown, cLeft, cRight, cJump, cThrowItem, cInv, cHeal, cMana, cBuff,
                     cHook, cTorch, cSmart, cMount
                 };
                 if (setKey >= 0)
                 {
                     array11[setKey] = "_";
                 }
                 array9[0] = Lang.menu[74].Value + array11[0];
                 array9[1] = Lang.menu[75].Value + array11[1];
                 array9[2] = Lang.menu[76].Value + array11[2];
                 array9[3] = Lang.menu[77].Value + array11[3];
                 array9[4] = Lang.menu[78].Value + array11[4];
                 array9[5] = Lang.menu[79].Value + array11[5];
                 array9[6] = Lang.menu[80].Value + array11[6];
                 array9[7] = Lang.menu[81].Value + array11[7];
                 array9[8] = Lang.menu[82].Value + array11[8];
                 array9[9] = Lang.menu[83].Value + array11[9];
                 array9[10] = Lang.menu[84].Value + array11[10];
                 array9[11] = Lang.menu[85].Value + array11[11];
                 array9[12] = Lang.menu[120].Value + array11[12];
                 array9[13] = Lang.menu[130].Value + array11[13];
                 for (int num36 = 0; num36 < 14; num36++)
                 {
                     array8[num36] = true;
                     array7[num36] = 0.45f;
                     array5[num36] = -80;
                 }
                 array7[14] = 0.8f;
                 array4[14] = 6;
                 array9[14] = Lang.menu[86].Value;
                 array7[15] = 0.8f;
                 array4[15] = 16;
                 array9[15] = Lang.menu[5].Value;
                 if (selectedMenu == 15 || flag5)
                 {
                     flag5 = false;
                     menuMode = 11;
                     SoundEngine.PlaySound(11);
                 }
                 else if (selectedMenu == 14)
                 {
                     ResetKeyBindings();
                     setKey = -1;
                     SoundEngine.PlaySound(11);
                 }
                 else if (selectedMenu >= 0)
                 {
                     setKey = selectedMenu;
                 }
                 if (setKey >= 0)
                 {
                     List<Microsoft.Xna.Framework.Input.Keys> pressedKeys2 = PlayerInput.GetPressedKeys();
                     if (pressedKeys2.Count > 0)
                     {
                         string text2 = string.Concat(pressedKeys2[0]);
                         if (text2 != "None")
{
                             if (setKey == 0)
{
                                 cUp = text2;
                             }
                             if (setKey == 1)
{
                                 cDown = text2;
                             }
                             if (setKey == 2)
{
                                 cLeft = text2;
                             }
                             if (setKey == 3)
{
                                 cRight = text2;
                             }
                             if (setKey == 4)
{
                                 cJump = text2;
                             }
                             if (setKey == 5)
{
                                 cThrowItem = text2;
                             }
                             if (setKey == 6)
{
                                 cInv = text2;
                             }
                             if (setKey == 7)
{
                                 cHeal = text2;
                             }
                             if (setKey == 8)
{
                                 cMana = text2;
                             }
                             if (setKey == 9)
{
                                 cBuff = text2;
                             }
                             if (setKey == 10)
{
                                 cHook = text2;
                             }
                             if (setKey == 11)
{
                                 cTorch = text2;
                             }
                             if (setKey == 12)
{
                                 cSmart = text2;
                             }
                             if (setKey == 13)
{
                                 cMount = text2;
                             }
                             setKey = -1;
                         }
                     }
                 }
             }
             else if (menuMode == 1127)
             {
                 num2 = 250;
                 num4 = 52;
                 num5 = 4;
                 array4[num5 - 1] = 18;
                 for (int num37 = 0; num37 < num5; num37++)
                 {
                     array7[num37] = 0.78f;
                 }
                 int num38 = 0;
                 array9[num38] = (ReversedUpDownArmorSetBonuses ? Lang.menu[220].Value : Lang.menu[221].Value);
                 if (selectedMenu == num38)
                 {
                     SoundEngine.PlaySound(12);
                     ReversedUpDownArmorSetBonuses = !ReversedUpDownArmorSetBonuses;
                 }
                 num38++;
                 if (ItemSlot.Options.DisableQuickTrash)
                 {
                     array9[num38] = Lang.menu[253].Value;
                 }
                 else
                 {
                     array9[num38] = (ItemSlot.Options.DisableLeftShiftTrashCan ? Lang.menu[224].Value : Lang.menu[223].Value);
                 }
                 if (selectedMenu == num38)
                 {
                     SoundEngine.PlaySound(12);
                     if (ItemSlot.Options.DisableQuickTrash)
                     {
                         ItemSlot.Options.DisableQuickTrash = false;
                         ItemSlot.Options.DisableLeftShiftTrashCan = true;
                     }
                     else if (ItemSlot.Options.DisableLeftShiftTrashCan)
                     {
                         ItemSlot.Options.DisableLeftShiftTrashCan = false;
                     }
                     else
                     {
                         ItemSlot.Options.DisableQuickTrash = true;
                         ItemSlot.Options.DisableLeftShiftTrashCan = false;
                     }
                 }
                 num38++;
                 array9[num38] = Lang.menu[222].Value;
                 if (selectedMenu == num38)
                 {
                     SoundEngine.PlaySound(10);
                     menuMode = 888;
                     MenuUI.SetState(ManageControlsMenu);
                 }
                 num38++;
                 array9[num38] = Lang.menu[5].Value;
                 if (selectedMenu == num38 || flag5)
                 {
                     flag5 = false;
                     menuMode = 11;
                     SoundEngine.PlaySound(11);
                 }
             }
             else if (menuMode == 12)
             {
                 int num39 = ((SocialAPI.Network != null) ? 1 : 0);
                 menuServer = false;
                 array9[0] = Lang.menu[(SocialAPI.Network != null) ? 146 : 87].Value;
                 array9[1] = Lang.menu[145].Value;
                 array9[1 + num39] = Lang.menu[88].Value;
                 array9[2 + num39] = Lang.menu[5].Value;
                 if (selectedMenu == 0)
                 {
                     LoadPlayers();
                     menuMultiplayer = true;
                     SoundEngine.PlaySound(10);
                     ClearPendingPlayerSelectCallbacks();
                     menuMode = 1;
                 }
                 else if (selectedMenu == 1 + num39)
                 {
                     LoadPlayers();
                     SoundEngine.PlaySound(10);
                     ClearPendingPlayerSelectCallbacks();
                     menuMode = 1;
                     menuMultiplayer = true;
                     menuServer = true;
                 }
                 else if (selectedMenu == 1)
                 {
                     SoundEngine.PlaySound(10);
                     SocialAPI.Friends.OpenJoinInterface();
                 }
                 else if (selectedMenu == 2 + num39 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = 0;
                 }
                 num5 = 3 + num39;
             }
             else if (menuMode == 13)
             {
                 if (PlayerInput.SettingsForUI.ShowGamepadHints)
                 {
                     num2 = 180;
                     num4 = 30;
                     int num40 = 0;
                     array9[num40] = Lang.menu[89].Value.Replace(":", "");
                     if (selectedMenu == num40)
                     {
                         UIVirtualKeyboard state = new UIVirtualKeyboard(Lang.menu[89].Value, getIP, OnSubmitServerIP, CreateGoToMenuEvent(13), 0, allowEmpty: true);
                         UserInterface.ActiveInstance.SetState(state);
                         menuMode = 888;
                     }
                     array7[num40] = 0.6f;
                     array4[num40] = 40;
                     num40++;
                     for (int num41 = 0; num41 <= 6; num41++)
                     {
                         if (recentWorld[num41] != null && recentWorld[num41] != "")
{
                             array9[num40] = recentWorld[num41] + " (" + recentIP[num41] + ":" + recentPort[num41] + ")";
                         }
                         else
{
                             array9[num40] = "";
                             array[num40] = true;
                         }
                         array7[num40] = 0.6f;
                         array4[num40] = 40;
                         if (selectedMenu == num40)
{
                             autoPass = false;
                             Netplay.ListenPort = recentPort[num41];
                             getIP = recentIP[num41];
                             Netplay.SetRemoteIPAsync(getIP, StartClientGameplay);
                             menuMode = 14;
                             statusText = Language.GetTextValue("Net.ConnectingTo", getIP);
                         }
                         num40++;
                     }
                     array4[num40] = 64;
                     array9[num40] = Lang.menu[5].Value;
                     if (selectedMenu == num40 || flag5)
                     {
                         flag5 = false;
                         SoundEngine.PlaySound(11);
                         menuMode = 1;
                     }
                     num40++;
                     num5 = num40;
                 }
                 else
                 {
                     string text3 = getIP;
                     PlayerInput.WritingText = true;
                     instance.HandleIME();
                     getIP = GetInputText(getIP);
                     if (text3 != getIP)
                     {
                         SoundEngine.PlaySound(12);
                     }
                     num5 = 11;
                     num2 = 180;
                     num4 = 30;
                     array9[0] = Lang.menu[89].Value;
                     array[0] = true;
                     array9[1] = getIP;
                     array4[1] = 19;
                     if (textBlinkerState == 1)
                     {
                         array9[1] += "|";
                         array5[1] = 1;
                     }
                     else
                     {
                         array9[1] += " ";
                     }
                     array[1] = true;
                     array4[9] = 44;
                     array9[9] = Lang.menu[4].Value;
                     array2[9] = true;
                     if (getIP != "")
                     {
                         if (getIP.Substring(0, 1) == " ")
{
                             getIP = "";
                         }
                         for (int num42 = 0; num42 < getIP.Length; num42++)
{
                             if (getIP != " ")
{
                                 array2[9] = false;
                             }
                         }
                     }
                     array4[10] = 64;
                     array9[10] = Lang.menu[5].Value;
                     for (int num43 = 2; num43 <= 8; num43++)
                     {
                         int num44 = num43 - 2;
                         if (recentWorld[num44] != null && recentWorld[num44] != "")
{
                             array9[num43] = recentWorld[num44] + " (" + recentIP[num44] + ":" + recentPort[num44] + ")";
                         }
                         else
{
                             array9[num43] = "";
                             array[num43] = true;
                         }
                         array7[num43] = 0.6f;
                         array4[num43] = 40;
                     }
                     if (selectedMenu >= 2 && selectedMenu < 9)
                     {
                         autoPass = false;
                         int num45 = selectedMenu - 2;
                         Netplay.ListenPort = recentPort[num45];
                         getIP = recentIP[num45];
                         Netplay.SetRemoteIPAsync(getIP, StartClientGameplay);
                         menuMode = 14;
                         statusText = Language.GetTextValue("Net.ConnectingTo", getIP);
                     }
                     if (selectedMenu == 10 || flag5)
                     {
                         flag5 = false;
                         SoundEngine.PlaySound(11);
                         menuMode = 1;
                     }
                     if (selectedMenu == 9 || (!array2[2] && inputTextEnter))
                     {
                         OnSubmitServerIP(getIP);
                     }
                     textBlinkerCount++;
                     if (textBlinkerCount >= 20)
                     {
                         if (textBlinkerState == 0)
{
                             textBlinkerState = 1;
                         }
                         else
{
                             textBlinkerState = 0;
                         }
                         textBlinkerCount = 0;
                     }
                 }
             }
             else if (menuMode == 131)
             {
                 if (PlayerInput.SettingsForUI.ShowGamepadHints)
                 {
                     UIVirtualKeyboard uIVirtualKeyboard4 = new UIVirtualKeyboard(Lang.menu[90].Value, getPort, OnSubmitServerPort, CreateGoToMenuEvent(13), 0, allowEmpty: true);
                     uIVirtualKeyboard4.CustomTextValidationForUpdate = IsGoodPortAddress;
                     uIVirtualKeyboard4.CustomTextValidationForSubmit = IsGoodPortAddress;
                     UserInterface.ActiveInstance.SetState(uIVirtualKeyboard4);
                     menuMode = 888;
                 }
                 int num46 = 7777;
                 PlayerInput.WritingText = true;
                 instance.HandleIME();
                 string text4 = getPort;
                 getPort = GetInputText(getPort);
                 if (text4 != getPort)
                 {
                     SoundEngine.PlaySound(12);
                 }
                 array9[0] = Lang.menu[90].Value;
                 array2[2] = true;
                 if (getPort != "")
                 {
                     bool flag7 = false;
                     try
                     {
                         num46 = Convert.ToInt32(getPort);
                         if (num46 > 0 && num46 <= 65535)
{
                             flag7 = true;
                         }
                     }
                     catch
                     {
                     }
                     if (flag7)
                     {
                         array2[2] = false;
                     }
                 }
                 textBlinkerCount++;
                 if (textBlinkerCount >= 20)
                 {
                     if (textBlinkerState == 0)
                     {
                         textBlinkerState = 1;
                     }
                     else
                     {
                         textBlinkerState = 0;
                     }
                     textBlinkerCount = 0;
                 }
                 array9[1] = getPort;
                 if (textBlinkerState == 1)
                 {
                     array9[1] += "|";
                     array5[1] = 1;
                 }
                 else
                 {
                     array9[1] += " ";
                 }
                 array[0] = true;
                 array[1] = true;
                 array4[1] = -20;
                 array4[2] = 20;
                 array9[2] = Lang.menu[4].Value;
                 array9[3] = Lang.menu[5].Value;
                 num5 = 4;
                 if (selectedMenu == 3 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = 1;
                 }
                 if (selectedMenu == 2 || (!array2[2] && inputTextEnter))
                 {
                     OnSubmitServerPort(getPort);
                 }
             }
             else if (menuMode == 16)
             {
                 num2 = 200;
                 num4 = 60;
                 array4[1] = 30;
                 array4[2] = 30;
                 array4[3] = 30;
                 array4[4] = 70;
                 array9[0] = Lang.menu[91].Value;
                 array[0] = true;
                 array9[1] = Lang.menu[92].Value;
                 array9[2] = Lang.menu[93].Value;
                 array9[3] = Lang.menu[94].Value;
                 array9[4] = Lang.menu[5].Value;
                 num5 = 5;
                 if (selectedMenu == 4 || flag5)
                 {
                     flag5 = false;
                     menuMode = 6;
                     SoundEngine.PlaySound(11);
                 }
                 else if (selectedMenu > 0)
                 {
                     if (selectedMenu == 1)
                     {
                         maxTilesX = 4200;
                         maxTilesY = 1200;
                     }
                     else if (selectedMenu == 2)
                     {
                         maxTilesX = 6400;
                         maxTilesY = 1800;
                     }
                     else
                     {
                         maxTilesX = 8400;
                         maxTilesY = 8400;
                     }
                     clrInput();
                     menuMode = -7;
                     SoundEngine.PlaySound(10);
                     WorldGen.setWorldSize();
                 }
             }
             else if (menuMode == 1000000)
             {
                 num5 = 2;
                 array9[0] = statusText;
                 array[0] = true;
                 num2 = 220;
                 num4 = 250;
                 array9[1] = Lang.menu[5].Value;
                 if (selectedMenu == 1 || flag5)
                 {
                     flag5 = false;
                     SoundEngine.PlaySound(11);
                     menuMode = 6;
                     netMode = 0;
                 }
             }
             else if (menuMode == 1000001)
             {
                 num5 = 2;
                 array9[0] = statusText;
                 array[0] = true;
                 num2 = 220;
                 num4 = 250;
                 RejectionMenuInfo rejectionMenuInfo = RejectionMenuInfo;
                 if (rejectionMenuInfo != null)
                 {
                     array9[0] = rejectionMenuInfo.TextToShow;
                 }
                 array9[1] = Lang.menu[5].Value;
                 if (selectedMenu == 1 || flag5)
                 {
                     flag5 = false;
                     ReturnFromRejectionMenuAction returnFromRejectionMenuAction = null;
                     if (RejectionMenuInfo != null)
                     {
                         returnFromRejectionMenuAction = RejectionMenuInfo.ExitAction;
                     }
                     if (returnFromRejectionMenuAction != null)
                     {
                         returnFromRejectionMenuAction();
                     }
                     else
                     {
                         SoundEngine.PlaySound(11);
                         menuMode = 0;
                         netMode = 0;
                     }
                 }
             }
         }
         if (menuMode == 888)
         {
             if (!_blockFancyUIWhileLoading)
             {
                 MenuUI.Draw(spriteBatch, gameTime);
             }
         }
         else
         {
             MenuUI.SetState(null);
         }
         if (UILinkPointNavigator.Shortcuts.BackButtonInUse && !flag5)
         {
             UILinkPointNavigator.Shortcuts.BackButtonLock = true;
         }
         int num47 = focusMenu;
         if (menuMode != num6)
         {
             if (menuMode == 10 || netMode == 1 || menuMode == 14)
             {
                 gameTips.ClearTips();
             }
             blockMouse = true;
             menuSkip = 0;
             num5 = 0;
             if (PlayerInput.UsingGamepad && InvisibleCursorForGamepad)
             {
                 num47 = (focusMenu = -1);
                 mouseX = (mouseY = (PlayerInput.MouseX = (PlayerInput.MouseY = 0)));
             }
             for (int num48 = 0; num48 < maxMenuItems; num48++)
             {
                 menuItemScale[num48] = 0.8f;
             }
         }
         if (!mouseLeft)
         {
             blockMouse = true;
         }
         selectedMenu = -1;
         selectedMenu2 = -1;
         focusMenu = -1;
         bool flag8 = mouseLeft && !PlayerInput.UsingGamepad;
         if (!flag)
         {
             grabColorSlider = 0;
             hBar = -1f;
             sBar = -1f;
             lBar = -1f;
             aBar = -1f;
         }
         if (flag)
         {
             if (!mouseLeft)
             {
                 grabColorSlider = 0;
                 blockMouse = false;
             }
             int num49 = focusColor;
             focusColor = 0;
             int num50 = num9;
             int num51 = screenWidth / 2 - TextureAssets.Hue.Width() / 2;
             int num52 = 167;
             Vector3 vector = rgbToHsl(selColor);
             float num53 = vector.X;
             float num54 = vector.Y;
             float luminosity = vector.Z;
             float num55 = (float)(int)selColor.A / 255f;
             if (hBar == -1f || sBar == -1f || lBar == -1f || aBar == -1f)
             {
                 hBar = num53;
                 sBar = num54;
                 lBar = luminosity;
                 aBar = num55;
             }
             else
             {
                 num53 = hBar;
                 num54 = sBar;
                 luminosity = lBar;
                 num55 = aBar;
             }
             spriteBatch.Draw(TextureAssets.Hue.Value, new Vector2(num51, num50), Microsoft.Xna.Framework.Color.White);
             if ((mouseX > num51 - 4 && mouseX < num51 + TextureAssets.Hue.Width() + 4 && mouseY > num50 - 4 && mouseY < num50 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 1)
             {
                 spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num51, num50), OurFavoriteColor);
             }
             spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num51 + (float)(TextureAssets.Hue.Width() - 2) * hBar - (float)(TextureAssets.ColorSlider.Width() / 2), num50 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
             if ((mouseX > num51 - 4 && mouseX < num51 + TextureAssets.Hue.Width() + 4 && mouseY > num50 - 4 && mouseY < num50 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 1)
             {
                 focusColor = 1;
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 5;
                 if (flag8 && !blockMouse)
                 {
                     grabColorSlider = 1;
                     num53 = mouseX - num51;
                     num53 /= (float)TextureAssets.Hue.Width();
                     if (num53 < 0f)
                     {
                         num53 = 0f;
                     }
                     if (num53 > 1f)
                     {
                         num53 = 1f;
                     }
                     hBar = num53;
                 }
             }
             GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2(num51, num50) + TextureAssets.ColorBar.Value.Size() / 2f);
             num50 += 26;
             spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2(num51, num50), Microsoft.Xna.Framework.Color.White);
             for (int num56 = 0; num56 <= num52; num56++)
             {
                 float saturation = (float)num56 / (float)num52;
                 Microsoft.Xna.Framework.Color color4 = hslToRgb(num53, saturation, luminosity);
                 spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2(num51 + num56 + 5, num50 + 4), color4);
             }
             if ((mouseX > num51 - 4 && mouseX < num51 + TextureAssets.Hue.Width() + 4 && mouseY > num50 - 4 && mouseY < num50 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 2)
             {
                 spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num51, num50), OurFavoriteColor);
             }
             spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num51 + (float)(TextureAssets.Hue.Width() - 2) * sBar - (float)(TextureAssets.ColorSlider.Width() / 2), num50 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
             if ((mouseX > num51 - 4 && mouseX < num51 + TextureAssets.Hue.Width() + 4 && mouseY > num50 - 4 && mouseY < num50 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 2)
             {
                 focusColor = 2;
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 6;
                 if (flag8 && !blockMouse)
                 {
                     grabColorSlider = 2;
                     num54 = mouseX - num51;
                     num54 /= (float)TextureAssets.Hue.Width();
                     if (num54 < 0f)
                     {
                         num54 = 0f;
                     }
                     if (num54 > 1f)
                     {
                         num54 = 1f;
                     }
                     sBar = num54;
                 }
             }
             GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2(num51, num50) + TextureAssets.ColorBar.Value.Size() / 2f);
             num50 += 26;
             spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2(num51, num50), Microsoft.Xna.Framework.Color.White);
             float num57 = 0.15f;
             if (menuMode == 252)
             {
                 num57 = 0f;
             }
             for (int num58 = 0; num58 <= num52; num58++)
             {
                 float luminosity2 = (float)num58 / (float)num52;
                 Microsoft.Xna.Framework.Color color5 = hslToRgb(num53, num54, luminosity2);
                 spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2(num51 + num58 + 5, num50 + 4), color5);
             }
             if ((mouseX > num51 - 4 && mouseX < num51 + TextureAssets.Hue.Width() + 4 && mouseY > num50 - 4 && mouseY < num50 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 3)
             {
                 spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num51, num50), OurFavoriteColor);
             }
             spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num51 + (float)(TextureAssets.Hue.Width() - 2) * ((lBar - num57) / (1f - num57)) - (float)(TextureAssets.ColorSlider.Width() / 2), num50 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
             if ((mouseX > num51 - 4 && mouseX < num51 + TextureAssets.Hue.Width() + 4 && mouseY > num50 - 4 && mouseY < num50 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 3)
             {
                 focusColor = 3;
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 7;
                 if (flag8 && !blockMouse)
                 {
                     grabColorSlider = 3;
                     luminosity = mouseX - num51;
                     luminosity /= (float)TextureAssets.Hue.Width();
                     if (luminosity < 0f)
                     {
                         luminosity = 0f;
                     }
                     if (luminosity > 1f)
                     {
                         luminosity = 1f;
                     }
                     luminosity = (lBar = luminosity * (1f - num57) + num57);
                 }
             }
             GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2(num51, num50) + TextureAssets.ColorBar.Value.Size() / 2f);
             bool flag9 = false;
             if (menuMode == 252)
             {
                 num50 += 26;
                 flag9 = true;
                 spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2(num51, num50), Microsoft.Xna.Framework.Color.White);
                 Microsoft.Xna.Framework.Color color6 = hslToRgb(num53, num54, luminosity);
                 for (int num59 = 0; num59 <= num52; num59++)
                 {
                     float num60 = (float)num59 / (float)num52;
                     Microsoft.Xna.Framework.Color color7 = color6 * num60;
                     spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2(num51 + num59 + 5, num50 + 4), color7);
                 }
                 if ((mouseX > num51 - 4 && mouseX < num51 + TextureAssets.Hue.Width() + 4 && mouseY > num50 - 4 && mouseY < num50 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 4)
                 {
                     spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num51, num50), OurFavoriteColor);
                 }
                 spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num51 + (float)(TextureAssets.Hue.Width() - 2) * aBar - (float)(TextureAssets.ColorSlider.Width() / 2), num50 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
                 if ((mouseX > num51 - 4 && mouseX < num51 + TextureAssets.Hue.Width() + 4 && mouseY > num50 - 4 && mouseY < num50 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 4)
                 {
                     focusColor = 4;
                     UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 8;
                     if (mouseLeft && !blockMouse)
                     {
                         grabColorSlider = 4;
                         num55 = mouseX - num51;
                         num55 /= (float)TextureAssets.Hue.Width();
                         if (num55 < 0f)
{
                             num55 = 0f;
                         }
                         if (num55 > 1f)
{
                             num55 = 1f;
                         }
                         aBar = num55;
                     }
                 }
                 GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2(num51, num50) + TextureAssets.ColorBar.Value.Size() / 2f);
             }
             if (num49 != focusColor)
             {
                 SoundEngine.PlaySound(12);
             }
             selColor = hslToRgb(hBar, sBar, lBar);
             if (flag9)
             {
                 selColor.A = (byte)(aBar * 255f);
             }
         }
         else if (flag)
         {
             string text5 = "";
             for (int num61 = 0; num61 < 6; num61++)
             {
                 int num62 = num9;
                 int num63 = 370 + screenWidth / 2 - 400;
                 if (num61 == 0)
                 {
                     text5 = Lang.menu[95].Value;
                 }
                 if (num61 == 1)
                 {
                     text5 = Lang.menu[96].Value;
                     num62 += 30;
                 }
                 if (num61 == 2)
                 {
                     text5 = Lang.menu[97].Value;
                     num62 += 60;
                 }
                 if (num61 == 3)
                 {
                     text5 = string.Concat(selColor.R);
                     num63 += 90;
                 }
                 if (num61 == 4)
                 {
                     text5 = string.Concat(selColor.G);
                     num63 += 90;
                     num62 += 30;
                 }
                 if (num61 == 5)
                 {
                     text5 = string.Concat(selColor.B);
                     num63 += 90;
                     num62 += 60;
                 }
                 for (int num64 = 0; num64 < 5; num64++)
                 {
                     Microsoft.Xna.Framework.Color color8 = Microsoft.Xna.Framework.Color.Black;
                     if (num64 == 4)
                     {
                         color8 = color;
                         color8.R = (byte)((255 + color8.R) / 2);
                         color8.G = (byte)((255 + color8.R) / 2);
                         color8.B = (byte)((255 + color8.R) / 2);
                     }
                     int num65 = 255;
                     int num66 = color8.R - (255 - num65);
                     if (num66 < 0)
                     {
                         num66 = 0;
                     }
                     color8 = new Microsoft.Xna.Framework.Color((byte)num66, (byte)num66, (byte)num66, (byte)num65);
                     int num67 = 0;
                     int num68 = 0;
                     if (num64 == 0)
                     {
                         num67 = -2;
                     }
                     if (num64 == 1)
                     {
                         num67 = 2;
                     }
                     if (num64 == 2)
                     {
                         num68 = -2;
                     }
                     if (num64 == 3)
                     {
                         num68 = 2;
                     }
                     DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, text5, new Vector2(num63 + num67, num62 + num68), color8, 0f, default(Vector2), 0.5f, SpriteEffects.None, 0f);
                 }
             }
             bool flag10 = false;
             for (int num69 = 0; num69 < 2; num69++)
             {
                 for (int num70 = 0; num70 < 3; num70++)
                 {
                     int num71 = num9 + num70 * 30 - 12;
                     int num72 = 360 + screenWidth / 2 - 400;
                     float num73 = 0.9f;
                     if (num69 == 0)
                     {
                         num72 -= 70;
                         num71 += 2;
                     }
                     else
                     {
                         num72 -= 40;
                     }
                     text5 = "-";
                     if (num69 == 1)
                     {
                         text5 = "+";
                     }
                     Vector2 vector2 = new Vector2(24f, 24f);
                     int num74 = 142;
                     if (mouseX > num72 && (float)mouseX < (float)num72 + vector2.X && mouseY > num71 + 13 && (float)mouseY < (float)(num71 + 13) + vector2.Y)
                     {
                         if (focusColor != (num69 + 1) * (num70 + 10))
{
                             SoundEngine.PlaySound(12);
                         }
                         focusColor = (num69 + 1) * (num70 + 10);
                         flag10 = true;
                         num74 = 255;
                         if (mouseLeft)
{
                             if (colorDelay <= 1)
{
                                 if (colorDelay == 0)
{
                                     colorDelay = 40;
                                 }
                                 else
{
                                     colorDelay = 3;
                                 }
                                 int num75 = num69;
                                 if (num69 == 0)
{
                                     num75 = -1;
                                     if (selColor.R + selColor.G + selColor.B <= 150)
{
                                         num75 = 0;
                                     }
                                 }
                                 if (num70 == 0 && selColor.R + num75 >= 0 && selColor.R + num75 <= 255)
{
                                     selColor.R = (byte)(selColor.R + num75);
                                 }
                                 if (num70 == 1 && selColor.G + num75 >= 0 && selColor.G + num75 <= 255)
{
                                     selColor.G = (byte)(selColor.G + num75);
                                 }
                                 if (num70 == 2 && selColor.B + num75 >= 0 && selColor.B + num75 <= 255)
{
                                     selColor.B = (byte)(selColor.B + num75);
                                 }
                             }
                             colorDelay--;
                         }
                         else
{
                             colorDelay = 0;
                         }
                     }
                     for (int num76 = 0; num76 < 5; num76++)
                     {
                         Microsoft.Xna.Framework.Color color9 = Microsoft.Xna.Framework.Color.Black;
                         if (num76 == 4)
{
                             color9 = color;
                             color9.R = (byte)((255 + color9.R) / 2);
                             color9.G = (byte)((255 + color9.R) / 2);
                             color9.B = (byte)((255 + color9.R) / 2);
                         }
                         int num77 = color9.R - (255 - num74);
                         if (num77 < 0)
{
                             num77 = 0;
                         }
                         color9 = new Microsoft.Xna.Framework.Color((byte)num77, (byte)num77, (byte)num77, (byte)num74);
                         int num78 = 0;
                         int num79 = 0;
                         if (num76 == 0)
{
                             num78 = -2;
                         }
                         if (num76 == 1)
{
                             num78 = 2;
                         }
                         if (num76 == 2)
{
                             num79 = -2;
                         }
                         if (num76 == 3)
{
                             num79 = 2;
                         }
                         DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, text5, new Vector2(num72 + num78, num71 + num79), color9, 0f, default(Vector2), num73, SpriteEffects.None, 0f);
                     }
                 }
             }
             if (!flag10)
             {
                 focusColor = 0;
                 colorDelay = 0;
             }
         }
         if (flag2)
         {
             float x = screenWidth / 2 - 40 + 37;
             int num80 = 320;
             string text6 = "";
             for (int num81 = 0; num81 < 6; num81++)
             {
                 int num82 = num80;
                 int num83 = 370 + screenWidth / 2 - 400 + 37;
                 switch (num81)
                 {
                 case 0:
                     text6 = Lang.menu[98].Value;
                     num82 += 30;
                     break;
                 case 1:
                     text6 = Lang.menu[99].Value;
                     break;
                 case 2:
                     text6 = Lang.menu[119].Value;
                     num82 += 60;
                     break;
                 case 3:
                     text6 = Math.Round(musicVolume * 100f) + "%";
                     num83 += 90;
                     break;
                 case 4:
                     text6 = Math.Round(soundVolume * 100f) + "%";
                     num83 += 90;
                     num82 += 30;
                     break;
                 case 5:
                     text6 = Math.Round(ambientVolume * 100f) + "%";
                     num83 += 90;
                     num82 += 60;
                     break;
                 }
                 Microsoft.Xna.Framework.Color color10 = color;
                 color10.R = (byte)((255 + color10.R) / 2);
                 color10.G = (byte)((255 + color10.R) / 2);
                 color10.B = (byte)((255 + color10.R) / 2);
                 int num84 = 255;
                 int num85 = color10.R - (255 - num84);
                 if (num85 < 0)
                 {
                     num85 = 0;
                 }
                 Utils.DrawBorderStringFourWay(textColor: new Microsoft.Xna.Framework.Color((byte)num85, (byte)num85, (byte)num85, (byte)num84), sb: spriteBatch, font: FontAssets.DeathText.Value, text: text6, x: num83, y: num82, borderColor: Microsoft.Xna.Framework.Color.Black, origin: Vector2.Zero, scale: 0.5f);
             }
             int rightHover = IngameOptions.rightHover;
             IngameOptions.rightHover = -1;
             if (!mouseLeft)
             {
                 IngameOptions.rightLock = -1;
             }
             IngameOptions.valuePosition = new Vector2(x, num80 - 18 + 30);
             GamepadMainMenuHandler.MenuItemPositions.Add(IngameOptions.valuePosition - TextureAssets.ColorBar.Value.Size() * new Vector2(0.5f, 0f));
             float num86 = IngameOptions.DrawValueBar(spriteBatch, 1f, musicVolume);
             if (IngameOptions.inBar || IngameOptions.rightLock == 3)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 2;
                 IngameOptions.rightHover = 3;
                 if (flag8 && IngameOptions.rightLock == 3)
                 {
                     musicVolume = num86;
                 }
             }
             IngameOptions.valuePosition = new Vector2(x, num80 - 18 + 60);
             GamepadMainMenuHandler.MenuItemPositions.Add(IngameOptions.valuePosition - TextureAssets.ColorBar.Value.Size() * new Vector2(0.5f, 0f));
             float num87 = IngameOptions.DrawValueBar(spriteBatch, 1f, soundVolume);
             if (IngameOptions.inBar || IngameOptions.rightLock == 2)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 3;
                 IngameOptions.rightHover = 2;
                 if (flag8 && IngameOptions.rightLock == 2)
                 {
                     soundVolume = num87;
                 }
             }
             IngameOptions.valuePosition = new Vector2(x, num80 - 18 + 90);
             GamepadMainMenuHandler.MenuItemPositions.Add(IngameOptions.valuePosition - TextureAssets.ColorBar.Value.Size() * new Vector2(0.5f, 0f));
             float num88 = IngameOptions.DrawValueBar(spriteBatch, 1f, ambientVolume);
             if (IngameOptions.inBar || IngameOptions.rightLock == 4)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 4;
                 IngameOptions.rightHover = 4;
                 if (flag8 && IngameOptions.rightLock == 4)
                 {
                     ambientVolume = num88;
                 }
             }
             if (IngameOptions.rightHover != -1)
             {
                 IngameOptions.rightLock = IngameOptions.rightHover;
             }
             if (IngameOptions.rightHover != rightHover)
             {
                 SoundEngine.PlaySound(12);
             }
         }
         if (flag3)
         {
             int num89 = 400;
             string text7 = "";
             for (int num90 = 0; num90 < 4; num90++)
             {
                 int num91 = num89;
                 int num92 = 370 + screenWidth / 2 - 400;
                 if (num90 == 0)
                 {
                     text7 = Lang.menu[52].Value + ": " + bgScroll;
                 }
                 for (int num93 = 0; num93 < 5; num93++)
                 {
                     Microsoft.Xna.Framework.Color color11 = Microsoft.Xna.Framework.Color.Black;
                     if (num93 == 4)
                     {
                         color11 = color;
                         color11.R = (byte)((255 + color11.R) / 2);
                         color11.G = (byte)((255 + color11.R) / 2);
                         color11.B = (byte)((255 + color11.R) / 2);
                     }
                     int num94 = 255;
                     int num95 = color11.R - (255 - num94);
                     if (num95 < 0)
                     {
                         num95 = 0;
                     }
                     color11 = new Microsoft.Xna.Framework.Color((byte)num95, (byte)num95, (byte)num95, (byte)num94);
                     int num96 = 0;
                     int num97 = 0;
                     if (num93 == 0)
                     {
                         num96 = -2;
                     }
                     if (num93 == 1)
                     {
                         num96 = 2;
                     }
                     if (num93 == 2)
                     {
                         num97 = -2;
                     }
                     if (num93 == 3)
                     {
                         num97 = 2;
                     }
                     DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, text7, new Vector2(num92 + num96, num91 + num97), color11, 0f, default(Vector2), 0.5f, SpriteEffects.None, 0f);
                 }
             }
             IngameOptions.rightHover = -1;
             if (!mouseLeft)
             {
                 IngameOptions.rightLock = -1;
             }
             IngameOptions.valuePosition = new Vector2(screenWidth / 2 - 40, num89 + 12);
             GamepadMainMenuHandler.MenuItemPositions.Add(IngameOptions.valuePosition - TextureAssets.ColorBar.Value.Size() * new Vector2(0.5f, 0f));
             float num98 = IngameOptions.DrawValueBar(spriteBatch, 1f, (float)bgScroll / 100f);
             if (IngameOptions.inBar || IngameOptions.rightLock == 2)
             {
                 UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 1;
                 IngameOptions.rightHover = 2;
                 if (flag8 && IngameOptions.rightLock == 2)
                 {
                     bgScroll = (int)(num98 * 100f);
                     caveParallax = 1f - (float)bgScroll / 500f;
                 }
             }
             if (IngameOptions.rightHover != -1)
             {
                 IngameOptions.rightLock = IngameOptions.rightHover;
             }
         }
         bool flag11 = false;
         for (int num99 = 0; num99 < num5; num99++)
         {
             if (array9[num99] == null)
             {
                 continue;
             }
             Vector2 vector3 = FontAssets.DeathText.Value.MeasureString(array9[num99]);
             vector3.X *= 0.5f;
             vector3.Y *= 0.5f;
             for (int num100 = 0; num100 < 5; num100++)
             {
                 Microsoft.Xna.Framework.Color color12 = Microsoft.Xna.Framework.Color.Black;
                 if (num100 == 4)
                 {
                     switch (array6[num99])
                     {
                     case 0:
                         color12 = color;
                         break;
                     case 1:
                         color12 = mcColor;
                         break;
                     case 2:
                         color12 = hcColor;
                         break;
                     case 3:
                         color12 = highVersionColor;
                         break;
                     case 4:
                     case 5:
                     case 6:
                         color12 = errorColor;
                         break;
                     default:
                         color12 = color;
                         break;
                     }
                     color12.R = (byte)((255 + color12.R) / 2);
                     color12.G = (byte)((255 + color12.G) / 2);
                     color12.B = (byte)((255 + color12.B) / 2);
                 }
                 int num101 = (int)(255f * (menuItemScale[num99] * 2f - 1f));
                 if (array[num99])
                 {
                     num101 = 255;
                 }
                 int num102 = color12.R - (255 - num101);
                 if (num102 < 0)
                 {
                     num102 = 0;
                 }
                 int num103 = color12.G - (255 - num101);
                 if (num103 < 0)
                 {
                     num103 = 0;
                 }
                 int num104 = color12.B - (255 - num101);
                 if (num104 < 0)
                 {
                     num104 = 0;
                 }
                 if (num47 == num99 && num100 == 4)
                 {
                     float num105 = (float)num101 / 255f;
                     num102 = (int)((float)num102 * (1f - num105) + 255f * num105);
                     num103 = (int)((float)num103 * (1f - num105) + 215f * num105);
                     num104 = (int)((float)num104 * (1f - num105) + 0f * num105);
                 }
                 color12 = new Microsoft.Xna.Framework.Color((byte)num102, (byte)num103, (byte)num104, (byte)num101);
                 if (array3[num99])
                 {
                     if (num100 == 4)
                     {
                         color12.R = (byte)(color12.R * mouseTextColor / 300);
                         color12.G = (byte)(color12.G * mouseTextColor / 300);
                         color12.B = (byte)(color12.B * mouseTextColor / 300);
                         color12.A = (byte)(color12.A * mouseTextColor / 300);
                     }
                     else
                     {
                         color12.A -= (byte)(mouseTextColor / 5);
                     }
                 }
                 int num106 = 0;
                 int num107 = 0;
                 if (num100 == 0)
                 {
                     num106 = -2;
                 }
                 if (num100 == 1)
                 {
                     num106 = 2;
                 }
                 if (num100 == 2)
                 {
                     num107 = -2;
                 }
                 if (num100 == 3)
                 {
                     num107 = 2;
                 }
                 float num108 = menuItemScale[num99];
                 if (menuMode == 15 && num99 == 0)
                 {
                     num108 *= 0.35f;
                 }
                 else if (menuMode == 1000000 && num99 == 0)
                 {
                     num108 *= 0.75f;
                 }
                 else if (netMode == 2)
                 {
                     num108 *= 0.5f;
                 }
                 num108 *= array7[num99];
                 if (!array8[num99])
                 {
                     DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, array9[num99], new Vector2(num3 + num106 + array5[num99], (float)(num2 + num4 * num99 + num107) + vector3.Y * array7[num99] + (float)array4[num99]), color12, 0f, vector3, num108, SpriteEffects.None, 0f);
                 }
                 else
                 {
                     DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, array9[num99], new Vector2(num3 + num106 + array5[num99], (float)(num2 + num4 * num99 + num107) + vector3.Y * array7[num99] + (float)array4[num99]), color12, 0f, new Vector2(0f, vector3.Y), num108, SpriteEffects.None, 0f);
                 }
             }
             if (!array[num99] && !array2[num99])
             {
                 GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2(num3 + array5[num99], (float)(num2 + num4 * num99) + vector3.Y * array7[num99] + (float)array4[num99]));
             }
             if (!array8[num99])
             {
                 int num109 = 0;
                 menuWide[num99] = false;
                 Vector2 vector4 = FontAssets.DeathText.Value.MeasureString(array9[num99]) * array7[num99];
                 if (!((float)mouseX > (float)num3 - vector4.X * 0.5f + (float)array5[num99] - (float)num109) || !((float)mouseX < (float)num3 + vector4.X * 0.5f * array7[num99] + (float)array5[num99] + (float)num109) || mouseY <= num2 + num4 * num99 + array4[num99] || !((float)mouseY < (float)(num2 + num4 * num99 + array4[num99]) + 50f * array7[num99]) || !hasFocus)
                 {
                     continue;
                 }
                 focusMenu = num99;
                 if (array[num99] || array2[num99])
                 {
                     focusMenu = -1;
                     continue;
                 }
                 if (num47 != focusMenu)
                 {
                     flag11 = true;
                 }
                 if (mouseLeftRelease && mouseLeft)
                 {
                     selectedMenu = num99;
                 }
                 if (mouseRightRelease && mouseRight)
                 {
                     selectedMenu2 = num99;
                 }
                 continue;
             }
             Vector2 vector5 = FontAssets.DeathText.Value.MeasureString(array9[num99]) * array7[num99];
             if (mouseX <= num3 + array5[num99] || !((float)mouseX < (float)num3 + vector5.X + (float)array5[num99]) || mouseY <= num2 + num4 * num99 + array4[num99] || !((float)mouseY < (float)(num2 + num4 * num99 + array4[num99]) + 50f * array7[num99]) || !hasFocus)
             {
                 continue;
             }
             focusMenu = num99;
             if (array[num99] || array2[num99])
             {
                 focusMenu = -1;
                 continue;
             }
             if (num47 != focusMenu)
             {
                 flag11 = true;
             }
             if (mouseLeftRelease && mouseLeft)
             {
                 selectedMenu = num99;
             }
             if (mouseRightRelease && mouseRight)
             {
                 selectedMenu2 = num99;
             }
         }
         if (flag11 && num47 != focusMenu)
         {
             SoundEngine.PlaySound(12);
         }
         if (GamepadMainMenuHandler.MenuItemPositions.Count == 0)
         {
             Vector2 vector6 = new Vector2((float)Math.Cos(GlobalTimeWrappedHourly * ((float)Math.PI * 2f)), (float)Math.Sin(GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 2f)) * new Vector2(30f, 15f) + Vector2.UnitY * 20f;
             UILinkPointNavigator.SetPosition(2000, new Vector2(screenWidth, screenHeight) / 2f + vector6);
         }
         for (int num110 = 0; num110 < maxMenuItems; num110++)
         {
             if (num110 == focusMenu)
             {
                 if (menuItemScale[num110] < 1f)
                 {
                     menuItemScale[num110] += 0.02f;
                 }
                 if (menuItemScale[num110] > 1f)
                 {
                     menuItemScale[num110] = 1f;
                 }
             }
             else if ((double)menuItemScale[num110] > 0.8)
             {
                 menuItemScale[num110] -= 0.02f;
             }
         }
         if (flag4)
         {
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, UIScaleMatrix);
             Player pendingPlayer = PendingPlayer;
             pendingPlayer.PlayerFrame();
             pendingPlayer.position.X = (float)num7 + screenPosition.X;
             pendingPlayer.position.Y = (float)num8 + screenPosition.Y;
             PlayerRenderer.DrawPlayer(Camera, pendingPlayer, pendingPlayer.position, 0f, Vector2.Zero);
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, UIScaleMatrix);
         }
         float num111 = 0f;
         if (!WorldGen.drunkWorldGen && menuMode == 0)
         {
             DrawSocialMediaButtons(color, num111);
             num111 += 32f;
         }
         if (!WorldGen.drunkWorldGen)
         {
             DrawVersionNumber(color, num111);
             num111 += 20f;
         }
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerStateForCursor, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, UIScaleMatrix);
         WorkshopPublishingIndicator.Draw(spriteBatch);
         IssueReporterIndicator.Draw(spriteBatch);
         DrawCursor(DrawThickCursor());
         DrawPendingMouseText();
         if (fadeCounter > 0)
         {
             Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
             byte b2 = 0;
             fadeCounter--;
             float num112 = (float)fadeCounter / 120f * 255f;
             if (quickSplash)
             {
                 num112 = (float)fadeCounter / 75f * 255f;
             }
             b2 = (byte)num112;
             white = new Microsoft.Xna.Framework.Color(b2, b2, b2, b2);
             spriteBatch.Draw(TextureAssets.Fade.Value, new Microsoft.Xna.Framework.Rectangle(-5, -5, screenWidth + 10, screenHeight + 10), white);
         }
         spriteBatch.End();
         if (mouseLeft)
         {
             mouseLeftRelease = false;
         }
         else
         {
             mouseLeftRelease = true;
         }
         if (mouseRight)
         {
             mouseRightRelease = false;
         }
         else
         {
             mouseRightRelease = true;
         }
         if (menuMode == num)
         {
             GamepadMainMenuHandler.LastDrew = num;
         }
     }
References _blockFancyUIWhileLoading, _pendingCharacterSelect, _worldSelectMenu, aBar, AchievementsMenu, EffectManager< T >.Activate(), UserInterface.ActiveInstance, SelectionHolder< TCycleType >.ActiveSelectionKeyName, PlayerResourceSetsManager.ActiveSetKeyName, ActiveWorldFileData, alreadyGrabbingSunOrMoon, ambientVolume, autoPass, autoPause, autoSave, UILinkPointNavigator.Shortcuts.BackButtonInUse, UILinkPointNavigator.Shortcuts.BackButtonLock, background, BackgroundEnabled, bgScroll, blockMouse, NetMessage.buffer, CanceledGivingServerPassword(), NetSocialModule.CancelJoin(), GamepadMainMenuHandler.CanRun, caveParallax, cBuff, cDown, changeTheTitle, chatMonitor, cHeal, cHook, cInv, cJump, IChatMonitor.Clear(), ClearPendingPlayerSelectCallbacks(), GameTipsDisplay.ClearTips(), ClearVisualPostProcessEffects(), cLeft, Netplay.Clients, ISocket.Close(), clrInput(), cMana, cMapAlphaDown, cMapAlphaUp, cMapFull, cMapStyle, cMapZoomIn, cMapZoomOut, cMount, TextureAssets.ColorBar, TextureAssets.ColorBlip, colorDelay, TextureAssets.ColorHighlight, TextureAssets.ColorSlider, Netplay.Connection, PlayerVariantID.Count, CreateGoToMenuEvent(), cRight, cSmart, cSmartCursorModeIsToggleAndNotHold, cThrowItem, cTorch, cUp, UIVirtualKeyboard.CustomTextValidationForSubmit, UIVirtualKeyboard.CustomTextValidationForUpdate, CycleClothingStyle(), CycleFrameSkipMode(), PlayerResourceSetsManager.CycleResourceSet(), SelectionHolder< TCycleType >.CycleSelection(), LockOnHelper.CycleUseModes(), dayTime, FontAssets.DeathText, Player.difficulty, ChildSafety.Disabled, ItemSlot.Options.DisableLeftShiftTrashCan, ItemSlot.Options.DisableQuickTrash, Netplay.Disconnect, displayHeight, displayWidth, GameTipsDisplay.Draw(), IssueReportsIndicator.Draw(), WorkshopPublishingIndicator.Draw(), UserInterface.Draw(), Utils.DrawBorderStringFourWay(), DrawCursor(), DrawFPS(), drawingPlayerChat, DrawPendingMouseText(), IPlayerRenderer.DrawPlayer(), DrawSocialMediaButtons(), DynamicSpriteFontExtensionMethods.DrawString(), DrawThickCursor(), IngameOptions.DrawValueBar(), DrawVersionNumber(), WorldGen.drunkWorldGen, E, eclipse, UIWorkshopHub.EnterHub(), ErasePlayer(), EraseWorld(), errorColor, FileUtilities.Exists(), RejectionMenuInfo.ExitAction, ExitServerPasswordMenu(), Player.eyeColor, TextureAssets.Fade, fadeCounter, focusColor, focusMenu, SocialAPI.Friends, GameAskedToQuit, GameMode, GamepadDisableInstructionsDisplay, gameTips, GetInputText(), getIP, getPort, PlayerInput.GetPressedKeys(), Language.GetText(), Language.GetTextValue(), GlobalTimeWrappedHourly, grabColorSlider, graphics, Player.hair, Player.hairColor, HandleIME(), hasFocus, hBar, hcColor, UIVirtualKeyboard.HideContents, HidePassword, ItemSlot.Options.HighlightNewItems, highVersionColor, hslToRgb(), TextureAssets.Hue, IngameOptions.inBar, inputTextEnter, SkyManager.Instance, LanguageManager.Instance, instance, Lang.inter, Netplay.InvalidateAllOngoingIPSetAttempts(), invasionProgressMode, InvisibleCursorForGamepad, RemoteClient.IsActive, IsBorderlessDisplayAvailable(), FileData.IsCloudSave, IsEngineLoaded, IsGoodPortAddress(), IssueReporterIndicator, GamepadMainMenuHandler.LastDrew, lBar, Netplay.ListenPort, Program.LoadedEverything, LoadPlayers(), TextureAssets.Logo, TextureAssets.Logo2, TextureAssets.Logo3, TextureAssets.Logo4, LogoA, LogoB, logoRotation, logoRotationDirection, logoRotationSpeed, logoScale, logoScaleDirection, logoScaleSpeed, LogoT, Player.Male, ManageControlsMenu, mapEnabled, maxMenuItems, maxTilesX, maxTilesY, mcColor, Lang.menu, GamepadMainMenuHandler.MenuItemPositions, menuItemScale, menuMode, menuMultiplayer, menuServer, MenuServerMode, menuSkip, MenuUI, menuWide, MenuXMovement, MinimapFrameManagerInstance, Lang.misc, Lighting.Mode, MouseBorderColor, mouseBorderColorSlider, mouseColor, mouseColorSlider, mouseLeft, mouseLeftRelease, mouseRight, mouseRightRelease, MouseShowBuildingGrid, mouseTextColor, PlayerInput.MouseX, mouseX, PlayerInput.MouseY, mouseY, FileUtilities.Move(), musicVolume, Player.name, netMode, SocialAPI.Network, UnifiedRandom.Next(), Lighting.NextLightMode(), numDisplayModes, OnCharacterNamed(), OnEngineLoad, DD2Event.Ongoing, OnSeedSelected(), OnSubmitServerIP(), OnSubmitServerPassword(), OnSubmitServerPasswordFromRequest(), OnSubmitServerPort(), OnWorldNamed(), OpenCharacterSelectUI(), FriendsSocialModule.OpenJoinInterface(), OpenResourcePacksMenu(), UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE, OurFavoriteColor, Player.pantsColor, PendingBorderlessState, PendingPlayer, PendingResolutionHeight, PendingResolutionWidth, placementPreview, Player.PlayerFrame(), PlayerList, PlayerRenderer, playOldTile, SoundEngine.PlaySound(), WorldGen.playWorld(), Entity.position, pumpkinMoon, qaStyle, quickSplash, rand, randColor(), recentIP, recentPort, recentWorld, RejectionMenuInfo, WorldGen.remixWorldGen, render, SceneMetrics.Reset(), ResetKeyBindings(), ResourceSetsManager, ReturnFromRejectionMenuAction(), ReversedUpDownArmorSetBonuses, rgbToHsl(), IngameOptions.rightHover, IngameOptions.rightLock, SamplerStateForCursor, SaveSettings(), sBar, screenBorderless, screenBorderlessPendingResizes, screenHeight, screenLastPosition, screenPosition, screenWidth, selColor, selectedMenu, selectedMenu2, selectedPlayer, selectedWorld, Netplay.ServerPassword, ServerSideCharacter, ColorSlidersSet.SetHSL(), setKey, LanguageManager.SetLanguage(), UIVirtualKeyboard.SetMaxInputLength(), UILinkPointNavigator.SetPosition(), Netplay.SetRemoteIPAsync(), SetResolution(), UserInterface.SetState(), SettingsEnabled_MinersWobble, SettingsEnabled_TilesSwayInWind, SettingsUnlock_WorldEvil, WorldGen.setWorldSize(), Player.shirtColor, Player.shoeColor, PlayerInput.SettingsForUI.ShowGamepadHints, showItemText, showSpam, BigProgressBarSystem.ShowText, Player.skinColor, Player.skinVariant, slimeRain, Player.SmartCursorSettings.SmartAxeAfterPickaxe, Player.SmartCursorSettings.SmartBlocksEnabled, snowMoon, RemoteServer.Socket, soundVolume, MessageBuffer.spamCount, spriteBatch, starGame, StartClientGameplay(), statusText, RemoteClient.StatusText, StopSlimeRain(), textBlinkerCount, textBlinkerState, RejectionMenuInfo.TextToShow, tileColor, ToggleFullScreen(), BigProgressBarSystem.ToggleShowText(), tServer, UIScaleMatrix, Player.underShirtColor, GameTipsDisplay.Update(), GamepadMainMenuHandler.Update(), Cloud.UpdateClouds(), Star.UpdateStars(), UseHeatDistortion, LockOnHelper.UseMode, UseStormEffects, PlayerInput.UsingGamepad, Asset< T >.Value, LocalizedText.Value, IngameOptions.valuePosition, WaveQuality, SocialAPI.Workshop, WorldGen.WorldGenParam_Evil, WorldList, worldPathName, worldSurface, and PlayerInput.WritingText.
Referenced by DoDraw().