Terraria: Main.DrawHealthBar
DrawHealthBar()
void Main.DrawHealthBar (float X, float Y, int Health, int MaxHealth, float alpha, float scale = 1f, bool noFlip = false) inline
     {
         if (Health <= 0)
         {
             return;
         }
         float num = (float)Health / (float)MaxHealth;
         if (num > 1f)
         {
             num = 1f;
         }
         int num2 = (int)(36f * num);
         float num3 = X - 18f * scale;
         float num4 = Y;
         if (player[myPlayer].gravDir == -1f && !noFlip)
         {
             num4 -= screenPosition.Y;
             num4 = screenPosition.Y + (float)screenHeight - num4;
         }
         float num5 = 0f;
         float num6 = 0f;
         float num7 = 0f;
         float num8 = 255f;
         num -= 0.1f;
         if ((double)num > 0.5)
         {
             num6 = 255f;
             num5 = 255f * (1f - num) * 2f;
         }
         else
         {
             num6 = 255f * num * 2f;
             num5 = 255f;
         }
         float num9 = 0.95f;
         num5 = num5 * alpha * num9;
         num6 = num6 * alpha * num9;
         num8 = num8 * alpha * num9;
         if (num5 < 0f)
         {
             num5 = 0f;
         }
         if (num5 > 255f)
         {
             num5 = 255f;
         }
         if (num6 < 0f)
         {
             num6 = 0f;
         }
         if (num6 > 255f)
         {
             num6 = 255f;
         }
         if (num8 < 0f)
         {
             num8 = 0f;
         }
         if (num8 > 255f)
         {
             num8 = 255f;
         }
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color((byte)num5, (byte)num6, (byte)num7, (byte)num8);
         if (num2 < 3)
         {
             num2 = 3;
         }
         if (num2 < 34)
         {
             if (num2 < 36)
             {
                 spriteBatch.Draw(TextureAssets.Hb2.Value, new Vector2(num3 - screenPosition.X + (float)num2 * scale, num4 - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(2, 0, 2, TextureAssets.Hb2.Height()), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
             }
             if (num2 < 34)
             {
                 spriteBatch.Draw(TextureAssets.Hb2.Value, new Vector2(num3 - screenPosition.X + (float)(num2 + 2) * scale, num4 - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(num2 + 2, 0, 36 - num2 - 2, TextureAssets.Hb2.Height()), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
             }
             if (num2 > 2)
             {
                 spriteBatch.Draw(TextureAssets.Hb1.Value, new Vector2(num3 - screenPosition.X, num4 - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, num2 - 2, TextureAssets.Hb1.Height()), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
             }
             spriteBatch.Draw(TextureAssets.Hb1.Value, new Vector2(num3 - screenPosition.X + (float)(num2 - 2) * scale, num4 - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(32, 0, 2, TextureAssets.Hb1.Height()), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
         }
         else
         {
             if (num2 < 36)
             {
                 spriteBatch.Draw(TextureAssets.Hb2.Value, new Vector2(num3 - screenPosition.X + (float)num2 * scale, num4 - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(num2, 0, 36 - num2, TextureAssets.Hb2.Height()), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
             }
             spriteBatch.Draw(TextureAssets.Hb1.Value, new Vector2(num3 - screenPosition.X, num4 - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, num2, TextureAssets.Hb1.Height()), color, 0f, new Vector2(0f, 0f), scale, SpriteEffects.None, 0f);
         }
     }
References TextureAssets.Hb1, TextureAssets.Hb2, myPlayer, player, screenHeight, screenPosition, spriteBatch, Asset< T >.Value, X, and Y.
Referenced by LegacyMultiplayerClosePlayersOverlay.Draw(), DrawInterface_14_EntityHealthBars(), DrawInterface_Healthbar_Worm(), and NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawLifeBar().