Terraria: Main.ClientInitialize
ClientInitialize()
void Main.ClientInitialize () inline private
     {
         //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
         //IL_01d6: Expected O, but got Unknown
         MessageBuffer.OnTileChangeReceived += OnTileChangeEvent;
         LanguageManager.Instance.OnLanguageChanged += delegate
         {
             ItemTooltip.InvalidateTooltips();
         };
         PlayerInput.OnBindingChange += ItemTooltip.InvalidateTooltips;
         clientUUID = Guid.NewGuid().ToString();
         _ = Terraria.Graphics.Effects.Filters.Scene;
         Platform.Current.InitializeClientServices(base.Window.Handle);
         Platform.Get<IImeService>().AddKeyListener((Action<char>)delegate(char keyStroke)
         {
             if (keyCount < 10)
             {
                 keyInt[keyCount] = keyStroke;
                 keyString[keyCount] = keyStroke.ToString() ?? "";
                 keyCount++;
             }
         });
         base.Window.AllowUserResizing = true;
         LoadSettings();
         PreventUpdatingTargets = false;
         SetDisplayMonitor();
         PlayerInput.CacheOriginalScreenDimensions();
         if (screenWidth > GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width)
         {
             screenWidth = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width;
         }
         if (screenHeight > GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height)
         {
             screenHeight = GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height;
         }
         UpdateDisplaySettings();
         graphics.ApplyChanges();
         if (Main.OnResolutionChanged != null)
         {
             Main.OnResolutionChanged(new Vector2(screenWidth, screenHeight));
         }
         CheckBunny();
         base.GraphicsDevice.DeviceLost += GraphicsDeviceLost;
         base.GraphicsDevice.DeviceReset += GraphicsDeviceLost;
         base.GraphicsDevice.DeviceResetting += GraphicsDeviceLost;
         if (_needsLanguageSelect)
         {
             menuMode = 1212;
         }
         _achievements = new AchievementManager();
         _achievementAdvisor = new AchievementAdvisor();
         OpenRecent();
         UILinksInitializer.Load();
         Chroma = new ChromaEngine();
         ChromaPainter = new ChromaHotkeyPainter();
         ChromaPainter.CollectBoundKeys();
         CacheSupportedDisplaySizes();
         if (autoJoin)
         {
             LoadPlayers();
             menuMode = 1;
             menuMultiplayer = true;
         }
         fpsTimer.Start();
     }
References _achievementAdvisor, _achievements, _needsLanguageSelect, AchievementAdvisor, autoJoin, PlayerInput.CacheOriginalScreenDimensions(), CacheSupportedDisplaySizes(), CheckBunny(), Chroma, ChromaPainter, clientUUID, ChromaHotkeyPainter.CollectBoundKeys(), Platform.Current, fpsTimer, graphics, GraphicsDeviceLost(), Platform.InitializeClientServices(), LanguageManager.Instance, ItemTooltip.InvalidateTooltips(), keyCount, keyInt, keyString, UILinksInitializer.Load(), LoadPlayers(), LoadSettings(), menuMode, menuMultiplayer, PlayerInput.OnBindingChange, LanguageManager.OnLanguageChanged, OnResolutionChanged, OnTileChangeEvent(), MessageBuffer.OnTileChangeReceived, OpenRecent(), PreventUpdatingTargets, screenHeight, screenWidth, SetDisplayMonitor(), and UpdateDisplaySettings().
Referenced by Initialize().