Terraria: Main.DrawSurfaceBG_GoodEvilDesert
DrawSurfaceBG_GoodEvilDesert()
void Main.DrawSurfaceBG_GoodEvilDesert (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack) inline private
     {
         LoadBackground(26);
         bgScale = 1.25f;
         bgScale *= bgGlobalScaleMultiplier;
         bgWidthScaled = (int)((float)backgroundWidth[26] * bgScale);
         bgParallax = 0.37;
         SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
         bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
         bgTopY = (int)(backgroundTopMagicNumber * 1800.0 + 1750.0) + (int)scAdj + pushBGTopHack;
         if (gameMenu)
         {
             bgTopY = 320 + pushBGTopHack;
         }
         bgLoops = screenWidth / bgWidthScaled + 2;
         if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
         {
             for (int i = 0; i < bgLoops; i++)
             {
                 spriteBatch.Draw(TextureAssets.Background[26].Value, new Vector2(bgStartX + bgWidthScaled * i, bgTopY), new Microsoft.Xna.Framework.Rectangle(0, 0, backgroundWidth[26], backgroundHeight[26]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
             }
         }
         bgScale = 1.34f;
         bgScale *= bgGlobalScaleMultiplier;
         LoadBackground(27);
         bgWidthScaled = (int)((float)backgroundWidth[27] * bgScale);
         bgParallax = 0.49;
         SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
         bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
         bgTopY = (int)(backgroundTopMagicNumber * 2100.0 + 2150.0) + (int)scAdj + pushBGTopHack;
         if (gameMenu)
         {
             bgTopY = 480 + pushBGTopHack;
             bgStartX -= 120;
         }
         bgLoops = screenWidth / bgWidthScaled + 2;
         if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
         {
             for (int j = 0; j < bgLoops; j++)
             {
                 spriteBatch.Draw(TextureAssets.Background[27].Value, new Vector2(bgStartX + bgWidthScaled * j, bgTopY), new Microsoft.Xna.Framework.Rectangle(0, 0, backgroundWidth[27], backgroundHeight[27]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, SpriteEffects.None, 0f);
             }
         }
     }
References TextureAssets.Background, backgroundHeight, backgroundWidth, bgLoops, bgParallax, bgScale, bgStartX, bgTopY, bgWidthScaled, ColorOfSurfaceBackgroundsModified, SkyManager.DrawToDepth(), gameMenu, SkyManager.Instance, LoadBackground(), scAdj, screenPosition, screenWidth, spriteBatch, Asset< T >.Value, and worldSurface.
Referenced by DrawSurfaceBG().