Terraria: Main.Initialize
Initialize()
override void Main.Initialize () inline protected virtual
Reimplemented from Game.
     {
         musicFade[50] = 1f;
         if (dedServ)
         {
             netMode = 2;
         }
         for (int i = 0; i < 10; i++)
         {
             recentWorld[i] = "";
             recentIP[i] = "";
             recentPort[i] = 0;
         }
         if (rand == null)
         {
             rand = new UnifiedRandom((int)DateTime.Now.Ticks);
         }
         SetTitle();
         lo = rand.Next(6);
         waterfallManager = new WaterfallManager();
         _windowMover = new WindowStateController();
         sittingManager = new AnchoredEntitiesCollection();
         sleepingManager = new AnchoredEntitiesCollection();
         gameTips = new GameTipsDisplay();
         if (player[myPlayer] == null)
         {
             player[myPlayer] = new Player();
         }
         ContentSamples.Initialize();
         PlayerInput.Initialize();
         player[myPlayer] = new Player();
         WorldGen.Hooks.OnWorldLoad += delegate
         {
             AmbienceServer = new AmbienceServer();
             LocalGolfState = new GolfState();
             if (!dedServ)
             {
                 Lighting.Clear();
             }
         };
         DontStarveSeed.Initialize();
         ResourceSetsManager = new PlayerResourceSetsManager();
         MinimapFrameManagerInstance = new MinimapFrameManager();
         PlayerInput.OnActionableInput += delegate
         {
             if (LocalGolfState != null)
             {
                 LocalGolfState.CancelBallTracking();
             }
         };
         SceneMetrics = new SceneMetrics();
         BindSettingsTo(Configuration);
         if (dedServ)
         {
             Initialize_AlmostEverything();
             return;
         }
         TimeLogger.Initialize();
         LoadContent_TryEnteringHiDef();
         ClientInitialize();
         base.Initialize();
     }
References _windowMover, AmbienceServer, BindSettingsTo(), GolfState.CancelBallTracking(), Lighting.Clear(), ClientInitialize(), Configuration, dedServ, gameTips, DontStarveSeed.Initialize(), PlayerInput.Initialize(), ContentSamples.Initialize(), TimeLogger.Initialize(), Initialize_AlmostEverything(), lo, LoadContent_TryEnteringHiDef(), LocalGolfState, MinimapFrameManagerInstance, musicFade, myPlayer, netMode, UnifiedRandom.Next(), PlayerInput.OnActionableInput, WorldGen.Hooks.OnWorldLoad, Player, player, rand, recentIP, recentPort, recentWorld, ResourceSetsManager, SceneMetrics, SetTitle(), sittingManager, sleepingManager, and waterfallManager.
Referenced by DedServ().