Terraria: Main.DrawInterface_10_CheckCaptureManager
DrawInterface_10_CheckCaptureManager()
static bool Main.DrawInterface_10_CheckCaptureManager () inline static private
     {
         bool result = true;
         PlayerInput.SetDesiredZoomContext(ZoomContext.Unscaled_MouseInWorld);
         CaptureManager.Instance.Update();
         if (CaptureManager.Instance.Active)
         {
             CaptureManager.Instance.Draw(spriteBatch);
             result = false;
             _MouseOversCanClear = true;
             PlayerInput.SetZoom_UI();
             Matrix uIScaleMatrix = UIScaleMatrix;
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, uIScaleMatrix);
             DrawPendingMouseText();
         }
         return result;
     }
References _MouseOversCanClear, CaptureManager.Active, CaptureManager.Draw(), DrawPendingMouseText(), CaptureManager.Instance, PlayerInput.SetDesiredZoomContext(), PlayerInput.SetZoom_UI(), spriteBatch, UIScaleMatrix, and CaptureManager.Update().
Referenced by SetupDrawInterfaceLayers().