Terraria: Main.DoUpdate
DoUpdate()
void Main.DoUpdate (ref GameTime gameTime) inline protected
     {
         gameTimeCache = gameTime;
         if (showSplash)
         {
             UpdateAudio();
             GlobalTimeWrappedHourly = (float)(gameTime.TotalGameTime.TotalSeconds % 3600.0);
             ChromaInitializer.UpdateEvents();
             Chroma.Update(GlobalTimeWrappedHourly);
             return;
         }
         PartySky.MultipleSkyWorkaroundFix = true;
         LocalPlayer.cursorItemIconReversed = false;
         if (!GlobalTimerPaused)
         {
             GlobalTimeWrappedHourly = (float)(gameTime.TotalGameTime.TotalSeconds % 3600.0);
         }
         UpdateCreativeGameModeOverride();
         UpdateWorldPreparationState();
         if (Player.BlockInteractionWithProjectiles > 0 && !mouseRight && mouseRightRelease)
         {
             Player.BlockInteractionWithProjectiles--;
         }
         PlayerInput.SetZoom_UI();
         for (int num = DelayedProcesses.Count - 1; num >= 0; num--)
         {
             IEnumerator enumerator = DelayedProcesses[num];
             if (!enumerator.MoveNext())
             {
                 DelayedProcesses.Remove(enumerator);
             }
         }
         if (!gameMenu || menuMode != 888)
         {
             MenuUI.SetState(null);
         }
         else
         {
             InGameUI.SetState(null);
         }
         CurrentInputTextTakerOverride = null;
         if (!dedServ)
         {
             AchievementAdvisor.Update();
         }
         PlayerInput.SetZoom_Unscaled();
         MouseOversTryToClear();
         PlayerInput.ResetInputsOnActiveStateChange();
         if (!dedServ && Main.OnTickForThirdPartySoftwareOnly != null)
         {
             Main.OnTickForThirdPartySoftwareOnly();
         }
         if (_hasPendingNetmodeChange)
         {
             netMode = _targetNetMode;
             _hasPendingNetmodeChange = false;
         }
         if (CaptureManager.Instance.IsCapturing)
         {
             return;
         }
         if (ActivePlayerFileData != null)
         {
             ActivePlayerFileData.UpdatePlayTimer();
         }
         Netplay.UpdateInMainThread();
         gameInactive = !base.IsActive;
         if (changeTheTitle)
         {
             changeTheTitle = false;
             SetTitle();
         }
         _worldUpdateTimeTester.Restart();
         if (!WorldGen.gen)
         {
             WorldGen.destroyObject = false;
         }
         if (gameMenu)
         {
             mapFullscreen = false;
         }
         UpdateSettingUnlocks();
         if (dedServ)
         {
             if (dedServFPS)
             {
                 updatesCountedForFPS++;
                 if (!fpsTimer.IsRunning)
                 {
                     fpsTimer.Restart();
                 }
                 if (fpsTimer.ElapsedMilliseconds >= 1000)
                 {
                     dedServCount1 += updatesCountedForFPS;
                     dedServCount2++;
                     float num2 = (float)dedServCount1 / (float)dedServCount2;
                     Console.WriteLine(updatesCountedForFPS + "  (" + num2 + ")");
                     updatesCountedForFPS = 0;
                     fpsTimer.Restart();
                 }
             }
             else
             {
                 if (fpsTimer.IsRunning)
                 {
                     fpsTimer.Stop();
                 }
                 updatesCountedForFPS = 0;
             }
         }
         DoUpdate_AutoSave();
         if (!dedServ)
         {
             ChromaInitializer.UpdateEvents();
             Chroma.Update(GlobalTimeWrappedHourly);
             if (superFast)
             {
                 base.IsFixedTimeStep = false;
                 graphics.SynchronizeWithVerticalRetrace = false;
             }
             else
             {
                 if (FrameSkipMode == FrameSkipMode.Off || FrameSkipMode == FrameSkipMode.Subtle)
                 {
                     if (base.IsActive)
                     {
                         base.IsFixedTimeStep = false;
                     }
                     else
                     {
                         base.IsFixedTimeStep = true;
                     }
                 }
                 else
                 {
                     base.IsFixedTimeStep = true;
                     graphics.SynchronizeWithVerticalRetrace = true;
                 }
                 graphics.SynchronizeWithVerticalRetrace = true;
             }
             if (showSplash)
             {
                 return;
             }
             updatesCountedForFPS++;
             if (fpsTimer.ElapsedMilliseconds >= 1000)
             {
                 if ((float)fpsCount >= 30f + 30f * gfxQuality)
                 {
                     gfxQuality += gfxRate;
                     gfxRate += 0.005f;
                 }
                 else if ((float)fpsCount < 29f + 30f * gfxQuality)
                 {
                     gfxRate = 0.01f;
                     gfxQuality -= 0.1f;
                 }
                 if (gfxQuality < 0f)
                 {
                     gfxQuality = 0f;
                 }
                 if (gfxQuality > 1f)
                 {
                     gfxQuality = 1f;
                 }
                 if (maxQ && base.IsActive)
                 {
                     gfxQuality = 1f;
                     maxQ = false;
                 }
                 updateRate = uCount;
                 frameRate = fpsCount;
                 fpsCount = 0;
                 fpsTimer.Restart();
                 updatesCountedForFPS = 0;
                 drawsCountedForFPS = 0;
                 uCount = 0;
                 if (gfxQuality < 0.8f)
                 {
                     mapTimeMax = (int)((1f - gfxQuality) * 60f);
                 }
                 else
                 {
                     mapTimeMax = 0;
                 }
             }
             if (FrameSkipMode == FrameSkipMode.Off || FrameSkipMode == FrameSkipMode.Subtle)
             {
                 UpdateTimeAccumulator += gameTime.ElapsedGameTime.TotalSeconds;
                 if (UpdateTimeAccumulator < 0.01666666753590107 && !superFast)
                 {
                     if (FrameSkipMode == FrameSkipMode.Subtle)
                     {
                         instance.SuppressDraw();
                     }
                     return;
                 }
                 gameTime = new GameTime(gameTime.TotalGameTime, new TimeSpan(166666L));
                 UpdateTimeAccumulator -= 0.01666666753590107;
                 UpdateTimeAccumulator = Math.Min(UpdateTimeAccumulator, 0.01666666753590107);
             }
             uCount++;
             drawSkip = false;
             PlayerInput.AllowExecutionOfGamepadInstructions = true;
             TryPlayingCreditsRoll();
             PlayerInput.SetZoom_UI();
             UpdateUIStates(gameTime);
             PlayerInput.SetZoom_Unscaled();
             Terraria.Graphics.Effects.Filters.Scene.Update(gameTime);
             Overlays.Scene.Update(gameTime);
             LiquidRenderer.Instance.Update(gameTime);
             UpdateAudio();
             InGameNotificationsTracker.Update();
             ItemSlot.UpdateInterface();
             if (teamCooldown > 0)
             {
                 teamCooldown--;
             }
             DoUpdate_AnimateBackgrounds();
             Animation.UpdateAll();
             if (qaStyle == 1)
             {
                 gfxQuality = 1f;
             }
             else if (qaStyle == 2)
             {
                 gfxQuality = 0.5f;
             }
             else if (qaStyle == 3)
             {
                 gfxQuality = 0f;
             }
             maxDustToDraw = (int)(6000f * (gfxQuality * 0.7f + 0.3f));
             if ((double)gfxQuality < 0.9)
             {
                 maxDustToDraw = (int)((float)maxDustToDraw * gfxQuality);
             }
             if (maxDustToDraw < 1000)
             {
                 maxDustToDraw = 1000;
             }
             Gore.goreTime = (int)(600f * gfxQuality);
             if (!WorldGen.gen)
             {
                 Liquid.cycles = (int)(17f - 10f * gfxQuality);
                 Liquid.curMaxLiquid = (int)((double)Liquid.maxLiquid * 0.25 + (double)Liquid.maxLiquid * 0.75 * (double)gfxQuality);
                 if (Setting_UseReducedMaxLiquids)
                 {
                     Liquid.curMaxLiquid = (int)(2500f + 2500f * gfxQuality);
                 }
             }
             if (superFast)
             {
                 graphics.SynchronizeWithVerticalRetrace = false;
                 drawSkip = false;
             }
             if ((double)gfxQuality < 0.2)
             {
                 LegacyLighting.RenderPhases = 8;
             }
             else if ((double)gfxQuality < 0.4)
             {
                 LegacyLighting.RenderPhases = 7;
             }
             else if ((double)gfxQuality < 0.6)
             {
                 LegacyLighting.RenderPhases = 6;
             }
             else if ((double)gfxQuality < 0.8)
             {
                 LegacyLighting.RenderPhases = 5;
             }
             else
             {
                 LegacyLighting.RenderPhases = 4;
             }
             if (!WorldGen.gen && Liquid.quickSettle)
             {
                 Liquid.curMaxLiquid = Liquid.maxLiquid;
                 if (Setting_UseReducedMaxLiquids)
                 {
                     Liquid.curMaxLiquid = 5000;
                 }
                 Liquid.cycles = 1;
             }
             if (WorldGen.tenthAnniversaryWorldGen && !gameMenu)
             {
                 WorldGen.tenthAnniversaryWorldGen = false;
             }
             if (WorldGen.drunkWorldGen || WorldGen.remixWorldGen)
             {
                 if (!gameMenu)
                 {
                     WorldGen.drunkWorldGen = false;
                     WorldGen.remixWorldGen = false;
                     logoRotation = 0f;
                     logoRotationSpeed = 0f;
                     logoScale = 1f;
                 }
             }
             else if (gameMenu && Math.Abs(logoRotationSpeed) > 1000f)
             {
                 logoRotation = 0f;
                 logoRotationSpeed = 0f;
                 logoScale = 1f;
             }
             UpdateOldNPCShop();
             hasFocus = base.IsActive;
             if (Platform.IsWindows)
             {
                 Form form = Control.FromHandle(base.Window.Handle) as Form;
                 bool num3 = form.WindowState == FormWindowState.Minimized;
                 bool flag = Form.ActiveForm == form;
                 hasFocus |= flag;
                 if (num3)
                 {
                     hasFocus = false;
                 }
             }
             if (!hasFocus && netMode == 0)
             {
                 if (!Platform.IsOSX)
                 {
                     base.IsMouseVisible = true;
                 }
                 if (netMode != 2 && myPlayer >= 0)
                 {
                     player[myPlayer].delayUseItem = true;
                 }
                 mouseLeftRelease = false;
                 mouseRightRelease = false;
                 if (gameMenu)
                 {
                     UpdateMenu();
                 }
                 gamePaused = true;
                 return;
             }
             if (!Platform.IsOSX)
             {
                 base.IsMouseVisible = false;
             }
             SkyManager.Instance.Update(gameTime);
             if (!gamePaused)
             {
                 EmoteBubble.UpdateAll();
             }
             ScreenObstruction.Update();
             ScreenDarkness.Update();
             MoonlordDeathDrama.Update();
             DoUpdate_AnimateCursorColors();
             DoUpdate_AnimateTileGlows();
             DoUpdate_AnimateDiscoRGB();
             DoUpdate_AnimateVisualPlayerAura();
             DoUpdate_AnimateWaterfalls();
             DoUpdate_AnimateWalls();
             AnimateTiles();
             DoUpdate_AnimateItemIcons();
             DoUpdate_F10_ToggleFPS();
             DoUpdate_F9_ToggleLighting();
             DoUpdate_F8_ToggleNetDiagnostics();
             DoUpdate_F7_ToggleGraphicsDiagnostics();
             DoUpdate_F11_ToggleUI();
             DoUpdate_AltEnter_ToggleFullscreen();
             DoUpdate_HandleInput();
             DoUpdate_HandleChat();
             DoUpdate_Enter_ToggleChat();
             if ((timeForVisualEffects += 1.0) >= 216000.0)
             {
                 timeForVisualEffects = 0.0;
             }
             if (gameMenu)
             {
                 UpdateMenu();
                 if (netMode != 2)
                 {
                     return;
                 }
                 gamePaused = false;
             }
             if (!CanUpdateGameplay && netMode != 2)
             {
                 return;
             }
             CheckInvasionProgressDisplay();
         }
         UpdateWindyDayState();
         if (netMode == 2)
         {
             cloudAlpha = maxRaining;
         }
         bool flag2 = base.IsActive;
         if (netMode == 1)
         {
             TrySyncingMyPlayer();
         }
         if (CanPauseGame())
         {
             DoUpdate_WhilePaused();
             gamePaused = true;
             return;
         }
         gamePaused = false;
         if (Main.OnTickForInternalCodeOnly != null)
         {
             Main.OnTickForInternalCodeOnly();
         }
         if ((dedServ || (netMode != 1 && !gameMenu && !gamePaused)) && AmbienceServer != null)
         {
             AmbienceServer.Update();
         }
         WorldGen.BackgroundsCache.UpdateFlashValues();
         if (LocalGolfState != null)
         {
             LocalGolfState.Update();
         }
         if ((flag2 || netMode == 1) && cloudAlpha > 0f)
         {
             Rain.MakeRain();
         }
         if (netMode != 1)
         {
             updateCloudLayer();
         }
         for (int i = 0; i < dayRate; i++)
         {
             UpdateWeather(gameTime, i);
         }
         UnpausedUpdateSeed = Utils.RandomNextSeed(UnpausedUpdateSeed);
         Ambience();
         if (netMode != 2)
         {
             try
             {
                 snowing();
             }
             catch
             {
                 if (!ignoreErrors)
                 {
                     throw;
                 }
             }
             Sandstorm.EmitDust();
         }
         if (netMode != 2)
         {
             if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
             {
                 Star.UpdateStars();
                 Cloud.UpdateClouds();
             }
             else if (shimmerAlpha > 0f)
             {
                 Star.UpdateStars();
                 int num4 = rand.Next(numStars);
                 if (rand.Next(90) == 0)
                 {
                     if (star[num4] != null && !star[num4].hidden && !star[num4].falling)
                     {
                         star[num4].Fall();
                     }
                     for (int j = 0; j < numStars; j++)
                     {
                         if (star[j].hidden)
{
                             Star.SpawnStars(j);
                         }
                     }
                 }
             }
         }
         PortalHelper.UpdatePortalPoints();
         LucyAxeMessage.UpdateMessageCooldowns();
         if (ShouldUpdateEntities())
         {
             DoUpdateInWorld(_worldUpdateTimeTester);
         }
         if (netMode != 2)
         {
             ChromaPainter.Update();
         }
     }
References _hasPendingNetmodeChange, _targetNetMode, _worldUpdateTimeTester, ActivePlayerFileData, PlayerInput.AllowExecutionOfGamepadInstructions, Ambience(), AnimateTiles(), WorldGen.BackgroundsCache, Player.BlockInteractionWithProjectiles, CanPauseGame(), CanUpdateGameplay, changeTheTitle, CheckInvasionProgressDisplay(), Chroma, ChromaPainter, cloudAlpha, CurrentInputTextTakerOverride, Player.cursorItemIconReversed, dayRate, dedServ, dedServCount1, dedServCount2, dedServFPS, DelayedProcesses, Player.delayUseItem, WorldGen.destroyObject, DoUpdate_AltEnter_ToggleFullscreen(), DoUpdate_AnimateBackgrounds(), DoUpdate_AnimateCursorColors(), DoUpdate_AnimateDiscoRGB(), DoUpdate_AnimateItemIcons(), DoUpdate_AnimateTileGlows(), DoUpdate_AnimateVisualPlayerAura(), DoUpdate_AnimateWalls(), DoUpdate_AnimateWaterfalls(), DoUpdate_AutoSave(), DoUpdate_Enter_ToggleChat(), DoUpdate_F10_ToggleFPS(), DoUpdate_F11_ToggleUI(), DoUpdate_F7_ToggleGraphicsDiagnostics(), DoUpdate_F8_ToggleNetDiagnostics(), DoUpdate_F9_ToggleLighting(), DoUpdate_HandleChat(), DoUpdate_HandleInput(), DoUpdate_WhilePaused(), DoUpdateInWorld(), drawsCountedForFPS, drawSkip, WorldGen.drunkWorldGen, Sandstorm.EmitDust(), Star.Fall(), fpsCount, fpsTimer, frameRate, gameInactive, gameMenu, gamePaused, gameTimeCache, WorldGen.gen, gfxQuality, gfxRate, GlobalTimerPaused, GlobalTimeWrappedHourly, Gore.goreTime, graphics, hasFocus, ignoreErrors, InGameUI, LiquidRenderer.Instance, CaptureManager.Instance, SkyManager.Instance, instance, CaptureManager.IsCapturing, Platform.IsOSX, Platform.IsWindows, L, Liquid, LocalGolfState, LocalPlayer, logoRotation, logoRotationSpeed, logoScale, Rain.MakeRain(), mapFullscreen, mapTimeMax, maxDustToDraw, maxQ, maxRaining, menuMode, MenuUI, mouseLeftRelease, MouseOversTryToClear(), mouseRight, mouseRightRelease, PartySky.MultipleSkyWorkaroundFix, myPlayer, netMode, UnifiedRandom.Next(), numStars, OnTickForInternalCodeOnly, OnTickForThirdPartySoftwareOnly, player, qaStyle, rand, Utils.RandomNextSeed(), WorldGen.remixWorldGen, LegacyLighting.RenderPhases, PlayerInput.ResetInputsOnActiveStateChange(), Overlays.Scene, screenPosition, UserInterface.SetState(), Setting_UseReducedMaxLiquids, SetTitle(), PlayerInput.SetZoom_UI(), PlayerInput.SetZoom_Unscaled(), shimmerAlpha, ShouldUpdateEntities(), showSplash, snowing(), Star.SpawnStars(), star, superFast, Game.SuppressDraw(), teamCooldown, WorldGen.tenthAnniversaryWorldGen, timeForVisualEffects, TryPlayingCreditsRoll(), TrySyncingMyPlayer(), uCount, UnpausedUpdateSeed, AmbienceServer.Update(), MoonlordDeathDrama.Update(), ScreenDarkness.Update(), ScreenObstruction.Update(), GolfState.Update(), ChromaHotkeyPainter.Update(), AchievementAdvisor.Update(), InGameNotificationsTracker.Update(), ChromaEngine.Update(), LiquidRenderer.Update(), OverlayManager.Update(), SkyManager.Update(), EmoteBubble.UpdateAll(), Animation.UpdateAll(), UpdateAudio(), updateCloudLayer(), Cloud.UpdateClouds(), UpdateCreativeGameModeOverride(), ChromaInitializer.UpdateEvents(), BackgroundChangeFlashInfo.UpdateFlashValues(), Netplay.UpdateInMainThread(), ItemSlot.UpdateInterface(), UpdateMenu(), LucyAxeMessage.UpdateMessageCooldowns(), UpdateOldNPCShop(), PlayerFileData.UpdatePlayTimer(), PortalHelper.UpdatePortalPoints(), updateRate, updatesCountedForFPS, UpdateSettingUnlocks(), Star.UpdateStars(), UpdateTimeAccumulator, UpdateUIStates(), UpdateWeather(), UpdateWindyDayState(), UpdateWorldPreparationState(), and worldSurface.
Referenced by Update().