Terraria: Main.ClearVisualPostProcessEffects
ClearVisualPostProcessEffects()
static void Main.ClearVisualPostProcessEffects () inline static private
     {
         for (int i = 0; i < 13; i++)
         {
             string key = "";
             switch (i)
             {
             case 0:
                 key = "Solar";
                 break;
             case 1:
                 key = "Vortex";
                 break;
             case 2:
                 key = "Nebula";
                 break;
             case 3:
                 key = "Stardust";
                 break;
             case 4:
                 key = "MoonLord";
                 break;
             case 5:
                 key = "MonolithSolar";
                 break;
             case 6:
                 key = "MonolithVortex";
                 break;
             case 7:
                 key = "MonolithNebula";
                 break;
             case 8:
                 key = "MonolithStardust";
                 break;
             case 9:
                 key = "Blizzard";
                 break;
             case 10:
                 key = "HeatDistortion";
                 break;
             case 11:
                 key = "Sandstorm";
                 break;
             case 12:
                 key = "MonolithMoonLord";
                 break;
             }
             if (SkyManager.Instance[key] != null && SkyManager.Instance[key].IsActive())
             {
                 SkyManager.Instance[key].Deactivate();
             }
             if (Overlays.Scene[key] != null && Overlays.Scene[key].IsVisible())
             {
                 Overlays.Scene[key].Deactivate();
             }
             if (Terraria.Graphics.Effects.Filters.Scene[key] != null && Terraria.Graphics.Effects.Filters.Scene[key].IsActive())
             {
                 Terraria.Graphics.Effects.Filters.Scene[key].Deactivate();
             }
         }
         if (Terraria.Graphics.Effects.Filters.Scene["BloodMoon"].IsActive())
         {
             Terraria.Graphics.Effects.Filters.Scene["BloodMoon"].Deactivate();
         }
         if (Terraria.Graphics.Effects.Filters.Scene["Graveyard"].IsActive())
         {
             Terraria.Graphics.Effects.Filters.Scene["Graveyard"].Deactivate();
         }
         if (Terraria.Graphics.Effects.Filters.Scene["Sepia"].IsActive())
         {
             Terraria.Graphics.Effects.Filters.Scene["Sepia"].Deactivate();
         }
         if (Terraria.Graphics.Effects.Filters.Scene["BloodMoon"].IsActive())
         {
             Terraria.Graphics.Effects.Filters.Scene["BloodMoon"].Deactivate();
         }
         if (Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].IsActive())
         {
             Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].Deactivate();
         }
         if (Terraria.Graphics.Effects.Filters.Scene["WaterDistortion"].IsActive())
         {
             Terraria.Graphics.Effects.Filters.Scene["WaterDistortion"].Deactivate();
         }
         if (SkyManager.Instance["Martian"].IsActive())
         {
             SkyManager.Instance["Martian"].Deactivate();
         }
         if (SkyManager.Instance["Party"].IsActive())
         {
             SkyManager.Instance["Party"].Deactivate();
         }
         if (SkyManager.Instance["Slime"].IsActive())
         {
             SkyManager.Instance["Slime"].Deactivate();
         }
         if (SkyManager.Instance["Ambience"].IsActive())
         {
             SkyManager.Instance["Ambience"].Deactivate();
         }
         slimeRain = false;
         slimeRainTime = 0.0;
         slimeWarningTime = 0;
         BirthdayParty.WorldClear();
         LanternNight.WorldClear();
         Sandstorm.WorldClear();
         CreditsRollEvent.Reset();
         maxRaining = 0f;
         raining = false;
     }
References EffectManager< T >.Deactivate(), SkyManager.Instance, maxRaining, raining, CreditsRollEvent.Reset(), Overlays.Scene, slimeRain, slimeRainTime, slimeWarningTime, BirthdayParty.WorldClear(), LanternNight.WorldClear(), and Sandstorm.WorldClear().
Referenced by DrawMenu().