Terraria: Main.OpenReportsMenu
OpenReportsMenu()
static void Main.OpenReportsMenu () inline static
     {
         List<IProvideReports> list = new List<IProvideReports>();
         list.Add(IssueReporter);
         if (SocialAPI.Workshop != null)
         {
             list.Add(SocialAPI.Workshop.IssueReporter);
         }
         UIReportsPage state = new UIReportsPage(MenuUI.CurrentState, menuMode, list);
         menuMode = 888;
         MenuUI.SetState(state);
     }
References UserInterface.CurrentState, WorkshopSocialModule.IssueReporter, IssueReporter, menuMode, MenuUI, UserInterface.SetState(), and SocialAPI.Workshop.
Referenced by WorkshopSocialModule._issueReporter_OnNeedToOpenUI(), UIWorkshopHub.GoLogsClick(), and IssueReportsIndicator.OpenUI().