Terraria: Main.NewText
NewText()
static void Main.NewText (string newText, byte R = byte.MaxValue, byte G = byte.MaxValue, byte B = byte.MaxValue) inline static
     {
         chatMonitor.NewText(newText, R, G, B);
         SoundEngine.PlaySound(12);
     }
References B, chatMonitor, G, IChatMonitor.NewText(), SoundEngine.PlaySound(), and R.
Referenced by WorldGen.BroadcastText(), CoinLossRevengeSystem.CacheEnemy(), NPC.checkDead(), WorldGen.CheckOrb(), NPC.CheckProgressFrostMoon(), NPC.CheckProgressPumpkinMoon(), Player.CheckSpawn_Internal(), NPC.CountKillForBannersAndDropThem(), WorldUtils.DebugRegen(), LegacyNetBufferPool.DisplayBufferSizes(), NPC.DoDeathEvents(), NPC.DoDeathEvents_CelebrateBossDeath(), DrawInterface_38_MouseCarriedObject(), DrawPVPIcons(), TimeLogger.EndDrawFrame(), DD2Event.FailureMessage(), Projectile.HandleMovement(), InvasionWarning(), Player.ItemCheck_UseCombatBook(), Player.ItemCheck_UseEventItems(), Player.ItemCheck_UsePeddlersSatchel(), Player.KillMe(), WorldGen.meteor(), WorldGen.MoveTownNPC(), TimeLogger.NewDrawFrame(), NPC.NewNPC(), NPC.NPCLoot(), AchievementInitializer.OnAchievementCompleted(), DD2Film.OnBegin(), DD2Film.OnEnd(), GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), WorldGen.SmashAltar(), WorldGen.smCallBack(), NPC.SpawnBoss(), CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), NPC.SpawnOnPlayer(), NPC.SpawnSkeletron(), WorldGen.SpawnTownNPC(), WorldGen.SpawnTravelNPC(), NPC.SpawnWOF(), TimeLogger.Start(), startPumpkinMoon(), startSnowMoon(), PortalHelper.SupportedTilesAreFine(), Player.TileInteractionsUse(), WorldGen.UnspawnTravelNPC(), TestHighFPSIssues.Update(), DontStarveDarknessDamageDealer.UpdateDarknessState(), UpdateSlimeRainWarning(), UpdateTime_StartDay(), and UpdateTime_StartNight().