Terraria: Main.DrawTrashItemSlot
DrawTrashItemSlot()
static void Main.DrawTrashItemSlot (int pivotTopLeftX, int pivotTopLeftY) inline static private
     {
         inventoryScale = 0.85f;
         int num = 448 + pivotTopLeftX;
         int num2 = 258 + pivotTopLeftY;
         if ((player[myPlayer].chest != -1 || npcShop > 0) && !recBigList)
         {
             num2 += 168;
             inventoryScale = 0.755f;
             num += 5;
         }
         new Microsoft.Xna.Framework.Color(150, 150, 150, 150);
         if (mouseX >= num && (float)mouseX <= (float)num + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num2 && (float)mouseY <= (float)num2 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
         {
             player[myPlayer].mouseInterface = true;
             ItemSlot.LeftClick(ref player[myPlayer].trashItem, 6);
             if (mouseLeftRelease && mouseLeft)
             {
                 Recipe.FindRecipes();
             }
             ItemSlot.MouseHover(ref player[myPlayer].trashItem, 6);
         }
         ItemSlot.Draw(spriteBatch, ref player[myPlayer].trashItem, 6, new Vector2(num, num2));
     }
References chest, ItemSlot.Draw(), Recipe.FindRecipes(), PlayerInput.IgnoreMouseInterface, TextureAssets.InventoryBack, inventoryScale, ItemSlot.LeftClick(), ItemSlot.MouseHover(), Player.mouseInterface, mouseLeft, mouseLeftRelease, mouseX, mouseY, myPlayer, npcShop, player, recBigList, and spriteBatch.
Referenced by DrawInventory().