Terraria: Main.DrawBlack
DrawBlack()
void Main.DrawBlack (bool force = false) inline protected
     {
         if (shimmerAlpha == 1f)
         {
             return;
         }
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         Vector2 vector = (drawToScreen ? Vector2.Zero : new Vector2(offScreenRange, offScreenRange));
         int num = (tileColor.R + tileColor.G + tileColor.B) / 3;
         float num2 = (float)((double)num * 0.4) / 255f;
         if (Lighting.Mode == LightMode.Retro)
         {
             num2 = (float)(tileColor.R - 55) / 255f;
             if (num2 < 0f)
             {
                 num2 = 0f;
             }
         }
         else if (Lighting.Mode == LightMode.Trippy)
         {
             num2 = (float)(num - 55) / 255f;
             if (num2 < 0f)
             {
                 num2 = 0f;
             }
         }
         Microsoft.Xna.Framework.Point screenOverdrawOffset = GetScreenOverdrawOffset();
         Microsoft.Xna.Framework.Point point = new Microsoft.Xna.Framework.Point(-offScreenRange / 16 + screenOverdrawOffset.X, -offScreenRange / 16 + screenOverdrawOffset.Y);
         int num3 = (int)((screenPosition.X - vector.X) / 16f - 1f) + point.X;
         int num4 = (int)((screenPosition.X + (float)screenWidth + vector.X) / 16f) + 2 - point.X;
         int num5 = (int)((screenPosition.Y - vector.Y) / 16f - 1f) + point.Y;
         int num6 = (int)((screenPosition.Y + (float)screenHeight + vector.Y) / 16f) + 5 - point.Y;
         if (num3 < 0)
         {
             num3 = point.X;
         }
         if (num4 > maxTilesX)
         {
             num4 = maxTilesX - point.X;
         }
         if (num5 < 0)
         {
             num5 = point.Y;
         }
         if (num6 > maxTilesY)
         {
             num6 = maxTilesY - point.Y;
         }
         if (!force)
         {
             if (num5 < maxTilesY / 2)
             {
                 num6 = Math.Min(num6, (int)worldSurface + 1);
                 num5 = Math.Min(num5, (int)worldSurface + 1);
             }
             else
             {
                 num6 = Math.Max(num6, UnderworldLayer);
                 num5 = Math.Max(num5, UnderworldLayer);
             }
         }
         bool flag = ShouldShowInvisibleWalls();
         for (int i = num5; i < num6; i++)
         {
             bool flag2 = i >= UnderworldLayer;
             if (flag2)
             {
                 num2 = 0.2f;
             }
             for (int j = num3; j < num4; j++)
             {
                 int num7 = j;
                 for (; j < num4; j++)
                 {
                     if (!WorldGen.InWorld(j, i))
                     {
                         return;
                     }
                     if (Main.tile[j, i] == null)
                     {
                         Main.tile[j, i] = new Tile();
                     }
                     Tile tile = Main.tile[j, i];
                     float num8 = Lighting.Brightness(j, i);
                     num8 = (float)Math.Floor(num8 * 255f) / 255f;
                     byte b = tile.liquid;
                     bool num9 = num8 <= num2 && ((!flag2 && b < 250) || WorldGen.SolidTile(tile) || (b >= 200 && num8 == 0f));
                     bool flag3 = tile.active() && tileBlockLight[tile.type] && (!tile.invisibleBlock() || flag);
                     bool flag4 = !WallID.Sets.Transparent[tile.wall] && (!tile.invisibleWall() || flag);
                     if (!num9 || (!flag4 && !flag3) || (!drawToScreen && LiquidRenderer.Instance.HasFullWater(j, i) && tile.wall == 0 && !tile.halfBrick() && !((double)i <= worldSurface)))
                     {
                         break;
                     }
                 }
                 if (j - num7 > 0)
                 {
                     spriteBatch.Draw(TextureAssets.BlackTile.Value, new Vector2(num7 << 4, i << 4) - screenPosition + vector, new Microsoft.Xna.Framework.Rectangle(0, 0, j - num7 << 4, 16), Microsoft.Xna.Framework.Color.Black);
                 }
             }
         }
         TimeLogger.DrawTime(5, stopwatch.Elapsed.TotalMilliseconds);
     }
References Tile.active(), TextureAssets.BlackTile, Lighting.Brightness(), TimeLogger.DrawTime(), drawToScreen, GetScreenOverdrawOffset(), Tile.halfBrick(), LiquidRenderer.HasFullWater(), LiquidRenderer.Instance, Tile.invisibleBlock(), Tile.invisibleWall(), WorldGen.InWorld(), Tile.liquid, maxTilesX, maxTilesY, Lighting.Mode, offScreenRange, screenHeight, screenPosition, screenWidth, shimmerAlpha, ShouldShowInvisibleWalls(), WorldGen.SolidTile(), spriteBatch, Tile, tile, tileBlockLight, tileColor, WallID.Sets.Transparent, Tile.type, UnderworldLayer, Asset< T >.Value, Tile.wall, and worldSurface.
Referenced by DoDraw_WallsAndBlacks(), DrawCapture(), and RenderBlack().