Terraria: Main.Initialize_AlmostEverything
Initialize_AlmostEverything()
void Main.Initialize_AlmostEverything () inline private
     {
         TilePaintSystem = new TilePaintSystemV2();
         TilesRenderer = new TileDrawing(TilePaintSystem);
         WallsRenderer = new WallDrawing(TilePaintSystem);
         CreativePowerManager.Initialize();
         LocalFavoriteData.Load();
         CloudFavoritesData.Load();
         Initialize_Entities();
         FindAnnouncementBoxStatus();
         CustomCurrencyManager.Initialize();
         WingStatsInitializer.Load();
         TileObjectData.Initialize();
         Animation.Initialize();
         Chest.Initialize();
         Wiring.Initialize();
         Framing.Initialize();
         ItemRarity.Initialize();
         TileEntity.InitializeAll();
         Projectile.InitializeStaticThings();
         TorchID.Initialize();
         InitializeItemAnimations();
         BestiaryDatabase bestiaryDatabase = new BestiaryDatabase();
         BestiaryDatabaseNPCsPopulator bestiaryDatabaseNPCsPopulator = new BestiaryDatabaseNPCsPopulator();
         bestiaryDatabaseNPCsPopulator.Populate(bestiaryDatabase);
         BestiaryDB = bestiaryDatabase;
         ContentSamples.RebuildBestiarySortingIDsByBestiaryDatabaseContents(bestiaryDatabase);
         BestiaryTracker = new BestiaryUnlocksTracker();
         ItemDropDatabase itemDropDatabase = new ItemDropDatabase();
         itemDropDatabase.Populate();
         ItemDropsDB = itemDropDatabase;
         bestiaryDatabase.Merge(ItemDropsDB);
         bestiaryDatabaseNPCsPopulator.AddDropOverrides(bestiaryDatabase);
         PylonSystem = new TeleportPylonsSystem();
         ItemDropSolver = new ItemDropResolver(itemDropDatabase);
         ShopHelper = new ShopHelper();
         CreativeItemSacrificesCatalog.Instance.Initialize();
         if (!dedServ)
         {
             BestiaryUI = new UIBestiaryTest(BestiaryDB);
             ContentThatNeedsRenderTargets.Add(MapPlayerRenderer);
         }
         if (!dedServ)
         {
             Lighting.Initialize();
             MapHelper.Initialize();
         }
         else
         {
             Mount.Initialize();
             Minecart.Initialize();
         }
         WorldGen.RandomizeBackgrounds(rand);
         if (treeBGSet1[0] == 173)
         {
             WorldGen.RandomizeBackgrounds(rand);
         }
         if (treeBGSet1[0] == 173)
         {
             WorldGen.RandomizeBackgrounds(rand);
         }
         WorldGen.RandomizeCaveBackgrounds();
         WorldGen.Hooks.Initialize();
         WorldGen.Hooks.OnWorldLoad += ResetGameCounter;
         bgAlphaFrontLayer[0] = 1f;
         bgAlphaFarBackLayer[0] = 1f;
         invBottom = 258;
         Initialize_TileAndNPCData1();
         Initialize_TileAndNPCData2();
         Initialize_Items();
         for (int i = 1; i < ProjectileID.Count; i++)
         {
             Projectile obj = new Projectile();
             obj.SetDefaults(i);
             if (obj.hostile)
             {
                 projHostile[i] = true;
             }
             if (obj.aiStyle == 7)
             {
                 projHook[i] = true;
             }
         }
         for (int j = 0; j < Recipe.maxRecipes; j++)
         {
             recipe[j] = new Recipe();
             availableRecipeY[j] = 65 * j;
         }
         Recipe.SetupRecipes();
         ContentSamples.FixItemsAfterRecipesAreAdded();
         for (int k = 0; k < Liquid.maxLiquid; k++)
         {
             liquid[k] = new Liquid();
         }
         for (int l = 0; l < 50000; l++)
         {
             liquidBuffer[l] = new LiquidBuffer();
         }
         shop[0] = new Chest();
         Chest.SetupTravelShop();
         for (int m = 1; m < 100; m++)
         {
             shop[m] = new Chest();
             shop[m].SetupShop(m);
         }
         teamColor[0] = Microsoft.Xna.Framework.Color.White;
         teamColor[1] = new Microsoft.Xna.Framework.Color(218, 59, 59);
         teamColor[2] = new Microsoft.Xna.Framework.Color(59, 218, 85);
         teamColor[3] = new Microsoft.Xna.Framework.Color(59, 149, 218);
         teamColor[4] = new Microsoft.Xna.Framework.Color(242, 221, 100);
         teamColor[5] = new Microsoft.Xna.Framework.Color(224, 100, 242);
         Netplay.Initialize();
         NetworkInitializer.Load();
         ChatInitializer.Load();
         LucyAxeMessage.Initialize();
         if (menuMode == 1)
         {
             LoadPlayers();
         }
         if (skipMenu)
         {
             WorldGen.clearWorld();
             gameMenu = false;
             LoadPlayers();
             PlayerList[0].SetAsActive();
             LoadWorlds();
             WorldGen.GenerateWorld(new UnifiedRandom().Next());
             WorldGen.EveryTileFrame();
             player[myPlayer].Spawn(PlayerSpawnContext.SpawningIntoWorld);
         }
         else if (Platform.IsWindows && !dedServ)
         {
             IntPtr systemMenu = GetSystemMenu(base.Window.Handle, bRevert: false);
             int menuItemCount = GetMenuItemCount(systemMenu);
             RemoveMenu(systemMenu, menuItemCount - 1, 1024);
         }
         if (!dedServ)
         {
             SoundID.FillAccessMap();
             Star.SpawnStars();
             ItemSorting.SetupWhiteLists();
         }
     }
References BestiaryDatabaseNPCsPopulator.AddDropOverrides(), Projectile.aiStyle, availableRecipeY, BestiaryDB, BestiaryTracker, BestiaryUI, bgAlphaFarBackLayer, bgAlphaFrontLayer, WorldGen.clearWorld(), CloudFavoritesData, ContentThatNeedsRenderTargets, ProjectileID.Count, dedServ, WorldGen.EveryTileFrame(), SoundID.FillAccessMap(), FindAnnouncementBoxStatus(), ContentSamples.FixItemsAfterRecipesAreAdded(), gameMenu, WorldGen.GenerateWorld(), GetMenuItemCount(), GetSystemMenu(), Projectile.hostile, CreativeItemSacrificesCatalog.Initialize(), CreativePowerManager.Initialize(), CustomCurrencyManager.Initialize(), ItemRarity.Initialize(), LucyAxeMessage.Initialize(), TorchID.Initialize(), MapHelper.Initialize(), TileObjectData.Initialize(), Animation.Initialize(), Chest.Initialize(), Framing.Initialize(), Lighting.Initialize(), Minecart.Initialize(), Mount.Initialize(), Netplay.Initialize(), Wiring.Initialize(), WorldGen.Hooks.Initialize(), Initialize_Entities(), Initialize_Items(), Initialize_TileAndNPCData1(), Initialize_TileAndNPCData2(), TileEntity.InitializeAll(), InitializeItemAnimations(), Projectile.InitializeStaticThings(), CreativeItemSacrificesCatalog.Instance, invBottom, Platform.IsWindows, ItemDropsDB, ItemDropSolver, Liquid, liquid, liquidBuffer, ChatInitializer.Load(), NetworkInitializer.Load(), WingStatsInitializer.Load(), FavoritesFile.Load(), LoadPlayers(), LoadWorlds(), LocalFavoriteData, MapPlayerRenderer, Recipe.maxRecipes, menuMode, BestiaryDatabase.Merge(), myPlayer, WorldGen.Hooks.OnWorldLoad, player, PlayerList, ItemDropDatabase.Populate(), BestiaryDatabaseNPCsPopulator.Populate(), projHook, projHostile, PylonSystem, rand, WorldGen.RandomizeBackgrounds(), WorldGen.RandomizeCaveBackgrounds(), ContentSamples.RebuildBestiarySortingIDsByBestiaryDatabaseContents(), recipe, RemoveMenu(), ResetGameCounter(), Projectile.SetDefaults(), Recipe.SetupRecipes(), Chest.SetupShop(), Chest.SetupTravelShop(), ItemSorting.SetupWhiteLists(), shop, ShopHelper, skipMenu, Player.Spawn(), Star.SpawnStars(), teamColor, TilePaintSystem, TilesRenderer, treeBGSet1, and WallsRenderer.
Referenced by DrawSplash(), and Initialize().