Terraria: Main.GUIChatDrawInner
GUIChatDrawInner()
void Main.GUIChatDrawInner () inline protected
     {
         if (player[myPlayer].talkNPC < 0 && player[myPlayer].sign == -1)
         {
             npcChatText = "";
             return;
         }
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(200, 200, 200, 200);
         int num = (mouseTextColor * 2 + 255) / 3;
         Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(num, num, num, num);
         bool flag = InGameUI.CurrentState is UIVirtualKeyboard && PlayerInput.UsingGamepad;
         string textValue = npcChatText;
         bool num2 = player[myPlayer].talkNPC != -1 && CanDryadPlayStardewAnimation(LocalPlayer, npc[player[myPlayer].talkNPC]);
         if (player[myPlayer].talkNPC != -1 && npc[player[myPlayer].talkNPC].ai[0] == 24f && NPC.RerollDryadText == 2)
         {
             NPC.RerollDryadText = 1;
         }
         if (num2 && NPC.RerollDryadText == 1 && npc[player[myPlayer].talkNPC].ai[0] != 24f && player[myPlayer].talkNPC != -1 && npc[player[myPlayer].talkNPC].active && npc[player[myPlayer].talkNPC].type == 20)
         {
             NPC.RerollDryadText = 0;
             npcChatText = npc[player[myPlayer].talkNPC].GetChat();
             NPC.PreventJojaColaDialog = true;
         }
         if (num2 && !NPC.PreventJojaColaDialog)
         {
             textValue = Language.GetTextValue("StardewTalk.PlayerHasColaAndIsHoldingIt");
         }
         bool flag2 = player[myPlayer].talkNPC != -1;
         _textDisplayCache.PrepareCache(textValue);
         string[] textLines = _textDisplayCache.TextLines;
         int amountOfLines = _textDisplayCache.AmountOfLines;
         bool flag3 = false;
         if (editSign)
         {
             textBlinkerCount++;
             if (textBlinkerCount >= 20)
             {
                 if (textBlinkerState == 0)
                 {
                     textBlinkerState = 1;
                 }
                 else
                 {
                     textBlinkerState = 0;
                 }
                 textBlinkerCount = 0;
             }
             if (textBlinkerState == 1)
             {
                 flag3 = true;
             }
             instance.DrawWindowsIMEPanel(new Vector2(screenWidth / 2, 90f), 0.5f);
         }
         amountOfLines++;
         spriteBatch.Draw(TextureAssets.ChatBack.Value, new Vector2(screenWidth / 2 - TextureAssets.ChatBack.Width() / 2, 100f), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.ChatBack.Width(), (amountOfLines + 1) * 30), color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         spriteBatch.Draw(TextureAssets.ChatBack.Value, new Vector2(screenWidth / 2 - TextureAssets.ChatBack.Width() / 2, 100 + (amountOfLines + 1) * 30), new Microsoft.Xna.Framework.Rectangle(0, TextureAssets.ChatBack.Height() - 30, TextureAssets.ChatBack.Width(), 30), color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         for (int i = 0; i < amountOfLines; i++)
         {
             string text = textLines[i];
             if (text != null)
             {
                 if (i == amountOfLines - 1 && flag3)
                 {
                     text += "|";
                 }
                 if (flag2)
                 {
                     ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, new Vector2(170 + (screenWidth - 800) / 2, 120 + i * 30), color2, 0f, Vector2.Zero, Vector2.One);
                 }
                 else
                 {
                     Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, text, 170 + (screenWidth - 800) / 2, 120 + i * 30, color2, Microsoft.Xna.Framework.Color.Black, Vector2.Zero);
                 }
             }
         }
         Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(screenWidth / 2 - TextureAssets.ChatBack.Width() / 2, 100, TextureAssets.ChatBack.Width(), (amountOfLines + 2) * 30);
         int num3 = 120 + amountOfLines * 30 + 30;
         num3 -= 235;
         UIVirtualKeyboard.ShouldHideText = !PlayerInput.SettingsForUI.ShowGamepadHints;
         if (!PlayerInput.UsingGamepad)
         {
             num3 = 9999;
         }
         UIVirtualKeyboard.OffsetDown = num3;
         if (npcChatCornerItem != 0)
         {
             Vector2 position = new Vector2(screenWidth / 2 + TextureAssets.ChatBack.Width() / 2, 100 + (amountOfLines + 1) * 30 + 30);
             position -= Vector2.One * 8f;
             Item item = new Item();
             item.netDefaults(npcChatCornerItem);
             float num4 = 1f;
             GetItemDrawFrame(item.type, out var itemTexture, out var rectangle2);
             if (rectangle2.Width > 32 || rectangle2.Height > 32)
             {
                 num4 = ((rectangle2.Width <= rectangle2.Height) ? (32f / (float)rectangle2.Height) : (32f / (float)rectangle2.Width));
             }
             spriteBatch.Draw(itemTexture, position, rectangle2, item.GetAlpha(Microsoft.Xna.Framework.Color.White), 0f, rectangle2.Size(), num4, SpriteEffects.None, 0f);
             if (item.color != default(Microsoft.Xna.Framework.Color))
             {
                 spriteBatch.Draw(itemTexture, position, rectangle2, item.GetColor(item.color), 0f, rectangle2.Size(), num4, SpriteEffects.None, 0f);
             }
             if (new Microsoft.Xna.Framework.Rectangle((int)position.X - (int)((float)rectangle2.Width * num4), (int)position.Y - (int)((float)rectangle2.Height * num4), (int)((float)rectangle2.Width * num4), (int)((float)rectangle2.Height * num4)).Contains(new Microsoft.Xna.Framework.Point(mouseX, mouseY)))
             {
                 cursorOverride = 2;
                 if (mouseLeftRelease && mouseLeft)
                 {
                     if (!drawingPlayerChat)
                     {
                         OpenPlayerChat();
                     }
                     if (ChatManager.AddChatText(FontAssets.MouseText.Value, ItemTagHandler.GenerateTag(item), Vector2.One))
                     {
                         SoundEngine.PlaySound(12);
                     }
                 }
                 MouseText(item.Name, -11, 0);
             }
         }
         num = mouseTextColor;
         color2 = new Microsoft.Xna.Framework.Color(num, (int)((double)num / 1.1), num / 2, num);
         string focusText = "";
         string focusText2 = "";
         int num5 = player[myPlayer].statLifeMax2 - player[myPlayer].statLife;
         for (int j = 0; j < Player.maxBuffs; j++)
         {
             int num6 = player[myPlayer].buffType[j];
             if (debuff[num6] && player[myPlayer].buffTime[j] > 60 && (num6 < 0 || num6 >= BuffID.Count || !BuffID.Sets.NurseCannotRemoveDebuff[num6]))
             {
                 num5 += 100;
             }
         }
         if (NPC.downedGolemBoss)
         {
             num5 *= 200;
         }
         else if (NPC.downedPlantBoss)
         {
             num5 *= 150;
         }
         else if (NPC.downedMechBossAny)
         {
             num5 *= 100;
         }
         else if (hardMode)
         {
             num5 *= 60;
         }
         else if (NPC.downedBoss3 || NPC.downedQueenBee)
         {
             num5 *= 25;
         }
         else if (NPC.downedBoss2)
         {
             num5 *= 10;
         }
         else if (NPC.downedBoss1)
         {
             num5 *= 3;
         }
         if (expertMode)
         {
             num5 *= 2;
         }
         num5 = (int)((double)num5 * player[myPlayer].currentShoppingSettings.PriceAdjustment);
         string text2 = null;
         string text3 = null;
         if (player[myPlayer].sign > -1)
         {
             focusText = ((!editSign) ? Lang.inter[48].Value : Lang.inter[47].Value);
         }
         else if (npc[player[myPlayer].talkNPC].type == 20)
         {
             focusText = Lang.inter[28].Value;
             focusText2 = Lang.inter[49].Value;
             if (CanDryadPlayStardewAnimation(LocalPlayer, npc[player[myPlayer].talkNPC]))
             {
                 focusText2 = Language.GetTextValue("StardewTalk.GiveColaButtonText");
             }
         }
         else if (NPCID.Sets.IsTownPet[npc[player[myPlayer].talkNPC].type])
         {
             focusText = Language.GetTextValue("UI.PetTheAnimal");
         }
         else if (npc[player[myPlayer].talkNPC].type == 207)
         {
             focusText = Lang.inter[28].Value;
             if (hardMode)
             {
                 focusText2 = Lang.inter[107].Value;
             }
         }
         else if (npc[player[myPlayer].talkNPC].type == 453)
         {
             focusText = Lang.inter[28].Value;
         }
         else if (npc[player[myPlayer].talkNPC].type == 550)
         {
             focusText = Lang.inter[28].Value;
             focusText2 = Language.GetTextValue("UI.BartenderHelp");
         }
         else if (npc[player[myPlayer].talkNPC].type == 588)
         {
             focusText = Lang.inter[28].Value;
         }
         else if (npc[player[myPlayer].talkNPC].type == 633)
         {
             focusText = Lang.inter[28].Value;
         }
         else if (npc[player[myPlayer].talkNPC].type == 663)
         {
             focusText = Lang.inter[28].Value;
         }
         else if (npc[player[myPlayer].talkNPC].type == 353)
         {
             focusText = Lang.inter[28].Value;
             focusText2 = Language.GetTextValue("GameUI.HairStyle");
         }
         else if (npc[player[myPlayer].talkNPC].type == 368)
         {
             focusText = Lang.inter[28].Value;
         }
         else if (npc[player[myPlayer].talkNPC].type == 369)
         {
             focusText = Lang.inter[64].Value;
         }
         else if (npc[player[myPlayer].talkNPC].type == 208)
         {
             focusText = Lang.inter[28].Value;
             if (TOWMusicUnlocked)
             {
                 focusText2 = Language.GetTextValue("GameUI.Music");
             }
         }
         else if (npc[player[myPlayer].talkNPC].type == 227)
         {
             focusText = Lang.inter[28].Value;
             focusText2 = Language.GetTextValue("GameUI.PainterDecor");
         }
         else if (npc[player[myPlayer].talkNPC].type == 17 || npc[player[myPlayer].talkNPC].type == 19 || npc[player[myPlayer].talkNPC].type == 38 || npc[player[myPlayer].talkNPC].type == 54 || npc[player[myPlayer].talkNPC].type == 107 || npc[player[myPlayer].talkNPC].type == 108 || npc[player[myPlayer].talkNPC].type == 124 || npc[player[myPlayer].talkNPC].type == 142 || npc[player[myPlayer].talkNPC].type == 160 || npc[player[myPlayer].talkNPC].type == 178 || npc[player[myPlayer].talkNPC].type == 207 || npc[player[myPlayer].talkNPC].type == 209 || npc[player[myPlayer].talkNPC].type == 228 || npc[player[myPlayer].talkNPC].type == 229)
         {
             focusText = Lang.inter[28].Value;
             if (npc[player[myPlayer].talkNPC].type == 107)
             {
                 focusText2 = Lang.inter[19].Value;
             }
         }
         else if (npc[player[myPlayer].talkNPC].type == 37)
         {
             if (!IsItDay())
             {
                 focusText = Lang.inter[50].Value;
             }
         }
         else if (npc[player[myPlayer].talkNPC].type == 22)
         {
             focusText = Lang.inter[51].Value;
             focusText2 = Lang.inter[25].Value;
         }
         else if (npc[player[myPlayer].talkNPC].type == 441)
         {
             if (player[myPlayer].taxMoney <= 0)
             {
                 focusText = Lang.inter[89].Value;
             }
             else
             {
                 string text4 = "";
                 int num7 = 0;
                 int num8 = 0;
                 int num9 = 0;
                 int num10 = 0;
                 int taxMoney = player[myPlayer].taxMoney;
                 taxMoney = (int)((double)taxMoney / player[myPlayer].currentShoppingSettings.PriceAdjustment);
                 if (taxMoney < 0)
                 {
                     taxMoney = 0;
                 }
                 num5 = taxMoney;
                 if (taxMoney >= 1000000)
                 {
                     num7 = taxMoney / 1000000;
                     taxMoney -= num7 * 1000000;
                 }
                 if (taxMoney >= 10000)
                 {
                     num8 = taxMoney / 10000;
                     taxMoney -= num8 * 10000;
                 }
                 if (taxMoney >= 100)
                 {
                     num9 = taxMoney / 100;
                     taxMoney -= num9 * 100;
                 }
                 if (taxMoney >= 1)
                 {
                     num10 = taxMoney;
                 }
                 if (num7 > 0)
                 {
                     text4 = text4 + num7 + " " + Lang.inter[15].Value + " ";
                 }
                 if (num8 > 0)
                 {
                     text4 = text4 + num8 + " " + Lang.inter[16].Value + " ";
                 }
                 if (num9 > 0)
                 {
                     text4 = text4 + num9 + " " + Lang.inter[17].Value + " ";
                 }
                 if (num10 > 0)
                 {
                     text4 = text4 + num10 + " " + Lang.inter[18].Value + " ";
                 }
                 float num11 = (float)(int)mouseTextColor / 255f;
                 if (num7 > 0)
                 {
                     color2 = new Microsoft.Xna.Framework.Color((byte)(220f * num11), (byte)(220f * num11), (byte)(198f * num11), mouseTextColor);
                 }
                 else if (num8 > 0)
                 {
                     color2 = new Microsoft.Xna.Framework.Color((byte)(224f * num11), (byte)(201f * num11), (byte)(92f * num11), mouseTextColor);
                 }
                 else if (num9 > 0)
                 {
                     color2 = new Microsoft.Xna.Framework.Color((byte)(181f * num11), (byte)(192f * num11), (byte)(193f * num11), mouseTextColor);
                 }
                 else if (num10 > 0)
                 {
                     color2 = new Microsoft.Xna.Framework.Color((byte)(246f * num11), (byte)(138f * num11), (byte)(96f * num11), mouseTextColor);
                 }
                 if (text4 == "")
                 {
                     focusText = Lang.inter[89].Value;
                 }
                 else
                 {
                     text4 = text4.Substring(0, text4.Length - 1);
                     focusText = Lang.inter[89].Value + " (" + text4 + ")";
                 }
                 focusText = Lang.inter[89].Value;
                 text3 = focusText;
                 text2 = "";
                 for (int k = 0; k < focusText.Length; k++)
                 {
                     text2 += " ";
                 }
                 focusText = focusText + text2 + "        ";
             }
         }
         else if (npc[player[myPlayer].talkNPC].type == 18)
         {
             string text5 = "";
             int num12 = 0;
             int num13 = 0;
             int num14 = 0;
             int num15 = 0;
             int num16 = num5;
             if (num16 > 0 && num16 < 1)
             {
                 num16 = 1;
             }
             if (num16 < 0)
             {
                 num16 = 0;
             }
             num5 = num16;
             if (num16 >= 1000000)
             {
                 num12 = num16 / 1000000;
                 num16 -= num12 * 1000000;
             }
             if (num16 >= 10000)
             {
                 num13 = num16 / 10000;
                 num16 -= num13 * 10000;
             }
             if (num16 >= 100)
             {
                 num14 = num16 / 100;
                 num16 -= num14 * 100;
             }
             if (num16 >= 1)
             {
                 num15 = num16;
             }
             if (num12 > 0)
             {
                 text5 = text5 + num12 + " " + Lang.inter[15].Value + " ";
             }
             if (num13 > 0)
             {
                 text5 = text5 + num13 + " " + Lang.inter[16].Value + " ";
             }
             if (num14 > 0)
             {
                 text5 = text5 + num14 + " " + Lang.inter[17].Value + " ";
             }
             if (num15 > 0)
             {
                 text5 = text5 + num15 + " " + Lang.inter[18].Value + " ";
             }
             float num17 = (float)(int)mouseTextColor / 255f;
             if (num12 > 0)
             {
                 color2 = new Microsoft.Xna.Framework.Color((byte)(220f * num17), (byte)(220f * num17), (byte)(198f * num17), mouseTextColor);
             }
             else if (num13 > 0)
             {
                 color2 = new Microsoft.Xna.Framework.Color((byte)(224f * num17), (byte)(201f * num17), (byte)(92f * num17), mouseTextColor);
             }
             else if (num14 > 0)
             {
                 color2 = new Microsoft.Xna.Framework.Color((byte)(181f * num17), (byte)(192f * num17), (byte)(193f * num17), mouseTextColor);
             }
             else if (num15 > 0)
             {
                 color2 = new Microsoft.Xna.Framework.Color((byte)(246f * num17), (byte)(138f * num17), (byte)(96f * num17), mouseTextColor);
             }
             if (text5 == "")
             {
                 focusText = Lang.inter[54].Value;
             }
             else
             {
                 text5 = text5.Substring(0, text5.Length - 1);
                 focusText = Lang.inter[54].Value + " (" + text5 + ")";
             }
         }
         if (!flag)
         {
             DrawNPCChatButtons(num, color2, amountOfLines, focusText, focusText2);
             if (text2 != null)
             {
                 float num18 = 130 + amountOfLines * 30;
                 float num19 = 180 + (screenWidth - 800) / 2;
                 num19 += ChatManager.GetStringSize(FontAssets.MouseText.Value, text3, new Vector2(0.9f)).X - 20f;
                 int taxMoney2 = player[myPlayer].taxMoney;
                 taxMoney2 = (int)((double)taxMoney2 / player[myPlayer].currentShoppingSettings.PriceAdjustment);
                 ItemSlot.DrawMoney(spriteBatch, "", num19, num18 - 40f, Utils.CoinsSplit(taxMoney2), horizontal: true);
             }
         }
         if (PlayerInput.IgnoreMouseInterface)
         {
             return;
         }
         if (rectangle.Contains(new Microsoft.Xna.Framework.Point(mouseX, mouseY)))
         {
             player[myPlayer].mouseInterface = true;
         }
         if (!mouseLeft || !mouseLeftRelease || !rectangle.Contains(new Microsoft.Xna.Framework.Point(mouseX, mouseY)))
         {
             return;
         }
         mouseLeftRelease = false;
         player[myPlayer].releaseUseItem = false;
         player[myPlayer].mouseInterface = true;
         if (npcChatFocus1)
         {
             CloseNPCChatOrSign();
         }
         else if (npcChatFocus2)
         {
             if (player[myPlayer].sign != -1)
             {
                 if (editSign)
                 {
                     SubmitSignText();
                 }
                 else
                 {
                     IngameFancyUI.OpenVirtualKeyboard(1);
                 }
             }
             else if (NPCID.Sets.IsTownPet[npc[player[myPlayer].talkNPC].type])
             {
                 player[myPlayer].PetAnimal(player[myPlayer].talkNPC);
             }
             else if (npc[player[myPlayer].talkNPC].type == 369)
             {
                 npcChatCornerItem = 0;
                 SoundEngine.PlaySound(12);
                 bool flag4 = false;
                 if (!anglerQuestFinished && !anglerWhoFinishedToday.Contains(player[myPlayer].name))
                 {
                     int num20 = player[myPlayer].FindItem(anglerQuestItemNetIDs[anglerQuest]);
                     if (num20 != -1)
                     {
                         player[myPlayer].inventory[num20].stack--;
                         if (player[myPlayer].inventory[num20].stack <= 0)
{
                             player[myPlayer].inventory[num20] = new Item();
                         }
                         flag4 = true;
                         SoundEngine.PlaySound(24);
                         player[myPlayer].anglerQuestsFinished++;
                         player[myPlayer].GetAnglerReward(npc[player[myPlayer].talkNPC], anglerQuestItemNetIDs[anglerQuest]);
                     }
                 }
                 npcChatText = Lang.AnglerQuestChat(flag4);
                 if (flag4)
                 {
                     anglerQuestFinished = true;
                     if (netMode == 1)
                     {
                         NetMessage.SendData(75);
                     }
                     else
                     {
                         anglerWhoFinishedToday.Add(player[myPlayer].name);
                     }
                     AchievementsHelper.HandleAnglerService();
                 }
             }
             else if (npc[player[myPlayer].talkNPC].type == 17)
             {
                 OpenShop(1);
             }
             else if (npc[player[myPlayer].talkNPC].type == 19)
             {
                 OpenShop(2);
             }
             else if (npc[player[myPlayer].talkNPC].type == 124)
             {
                 OpenShop(8);
             }
             else if (npc[player[myPlayer].talkNPC].type == 142)
             {
                 OpenShop(9);
             }
             else if (npc[player[myPlayer].talkNPC].type == 37)
             {
                 if (netMode == 0)
                 {
                     NPC.SpawnSkeletron(myPlayer);
                 }
                 else
                 {
                     NetMessage.SendData(51, -1, -1, null, myPlayer, 1f);
                 }
                 npcChatText = "";
             }
             else if (npc[player[myPlayer].talkNPC].type == 20)
             {
                 OpenShop(3);
             }
             else if (npc[player[myPlayer].talkNPC].type == 38)
             {
                 OpenShop(4);
             }
             else if (npc[player[myPlayer].talkNPC].type == 54)
             {
                 OpenShop(5);
             }
             else if (npc[player[myPlayer].talkNPC].type == 107)
             {
                 OpenShop(6);
             }
             else if (npc[player[myPlayer].talkNPC].type == 108)
             {
                 OpenShop(7);
             }
             else if (npc[player[myPlayer].talkNPC].type == 160)
             {
                 OpenShop(10);
             }
             else if (npc[player[myPlayer].talkNPC].type == 178)
             {
                 OpenShop(11);
             }
             else if (npc[player[myPlayer].talkNPC].type == 207)
             {
                 OpenShop(12);
             }
             else if (npc[player[myPlayer].talkNPC].type == 208)
             {
                 OpenShop(13);
             }
             else if (npc[player[myPlayer].talkNPC].type == 209)
             {
                 OpenShop(14);
             }
             else if (npc[player[myPlayer].talkNPC].type == 227)
             {
                 OpenShop(15);
             }
             else if (npc[player[myPlayer].talkNPC].type == 228)
             {
                 OpenShop(16);
             }
             else if (npc[player[myPlayer].talkNPC].type == 229)
             {
                 OpenShop(17);
             }
             else if (npc[player[myPlayer].talkNPC].type == 353)
             {
                 OpenShop(18);
             }
             else if (npc[player[myPlayer].talkNPC].type == 368)
             {
                 OpenShop(19);
             }
             else if (npc[player[myPlayer].talkNPC].type == 453)
             {
                 OpenShop(20);
             }
             else if (npc[player[myPlayer].talkNPC].type == 550)
             {
                 OpenShop(21);
             }
             else if (npc[player[myPlayer].talkNPC].type == 588)
             {
                 OpenShop(22);
             }
             else if (npc[player[myPlayer].talkNPC].type == 633)
             {
                 OpenShop(23);
             }
             else if (npc[player[myPlayer].talkNPC].type == 663)
             {
                 OpenShop(24);
             }
             else if (npc[player[myPlayer].talkNPC].type == 22)
             {
                 SoundEngine.PlaySound(12);
                 HelpText();
             }
             else if (npc[player[myPlayer].talkNPC].type == 441)
             {
                 if (player[myPlayer].taxMoney > 0)
                 {
                     int taxMoney3 = player[myPlayer].taxMoney;
                     taxMoney3 = (int)((double)taxMoney3 / player[myPlayer].currentShoppingSettings.PriceAdjustment);
                     while (taxMoney3 > 0)
                     {
                         EntitySource_Gift source = new EntitySource_Gift(npc[player[myPlayer].talkNPC]);
                         if (taxMoney3 > 1000000)
{
                             int num21 = taxMoney3 / 1000000;
                             taxMoney3 -= 1000000 * num21;
                             int number = Item.NewItem(source, (int)player[myPlayer].position.X, (int)player[myPlayer].position.Y, player[myPlayer].width, player[myPlayer].height, 74, num21);
                             if (netMode == 1)
{
                                 NetMessage.SendData(21, -1, -1, null, number, 1f);
                             }
                             continue;
                         }
                         if (taxMoney3 > 10000)
{
                             int num22 = taxMoney3 / 10000;
                             taxMoney3 -= 10000 * num22;
                             int number2 = Item.NewItem(source, (int)player[myPlayer].position.X, (int)player[myPlayer].position.Y, player[myPlayer].width, player[myPlayer].height, 73, num22);
                             if (netMode == 1)
{
                                 NetMessage.SendData(21, -1, -1, null, number2, 1f);
                             }
                             continue;
                         }
                         if (taxMoney3 > 100)
{
                             int num23 = taxMoney3 / 100;
                             taxMoney3 -= 100 * num23;
                             int number3 = Item.NewItem(source, (int)player[myPlayer].position.X, (int)player[myPlayer].position.Y, player[myPlayer].width, player[myPlayer].height, 72, num23);
                             if (netMode == 1)
{
                                 NetMessage.SendData(21, -1, -1, null, number3, 1f);
                             }
                             continue;
                         }
                         int num24 = taxMoney3;
                         if (num24 < 1)
{
                             num24 = 1;
                         }
                         taxMoney3 -= num24;
                         int number4 = Item.NewItem(source, (int)player[myPlayer].position.X, (int)player[myPlayer].position.Y, player[myPlayer].width, player[myPlayer].height, 71, num24);
                         if (netMode == 1)
{
                             NetMessage.SendData(21, -1, -1, null, number4, 1f);
                         }
                     }
                     npcChatText = Lang.dialog(rand.Next(380, 382));
                     player[myPlayer].taxMoney = 0;
                 }
                 else
                 {
                     npcChatText = Lang.dialog(rand.Next(390, 401));
                 }
             }
             else
             {
                 if (npc[player[myPlayer].talkNPC].type != 18)
                 {
                     return;
                 }
                 SoundEngine.PlaySound(12);
                 if (num5 > 0)
                 {
                     if (player[myPlayer].BuyItem(num5))
                     {
                         AchievementsHelper.HandleNurseService(num5);
                         SoundEngine.PlaySound(SoundID.Item4);
                         player[myPlayer].HealEffect(player[myPlayer].statLifeMax2 - player[myPlayer].statLife);
                         if ((double)player[myPlayer].statLife < (double)player[myPlayer].statLifeMax2 * 0.25)
{
                             npcChatText = Lang.dialog(227);
                         }
                         else if ((double)player[myPlayer].statLife < (double)player[myPlayer].statLifeMax2 * 0.5)
{
                             npcChatText = Lang.dialog(228);
                         }
                         else if ((double)player[myPlayer].statLife < (double)player[myPlayer].statLifeMax2 * 0.75)
{
                             npcChatText = Lang.dialog(229);
                         }
                         else
{
                             npcChatText = Lang.dialog(230);
                         }
                         player[myPlayer].statLife = player[myPlayer].statLifeMax2;
                         for (int l = 0; l < Player.maxBuffs; l++)
{
                             int num25 = player[myPlayer].buffType[l];
                             if (debuff[num25] && player[myPlayer].buffTime[l] > 0 && (num25 < 0 || num25 >= BuffID.Count || !BuffID.Sets.NurseCannotRemoveDebuff[num25]))
{
                                 player[myPlayer].DelBuff(l);
                                 l = -1;
                             }
                         }
                     }
                     else
                     {
                         int num26 = rand.Next(3);
                         if (num26 == 0)
{
                             npcChatText = Lang.dialog(52);
                         }
                         if (num26 == 1)
{
                             npcChatText = Lang.dialog(53);
                         }
                         if (num26 == 2)
{
                             npcChatText = Lang.dialog(54);
                         }
                     }
                 }
                 else
                 {
                     int num27 = rand.Next(3);
                     if (!ChildSafety.Disabled)
                     {
                         num27 = rand.Next(1, 3);
                     }
                     switch (num27)
                     {
                     case 0:
                         npcChatText = Lang.dialog(55);
                         break;
                     case 1:
                         npcChatText = Lang.dialog(56);
                         break;
                     case 2:
                         npcChatText = Lang.dialog(57);
                         break;
                     }
                 }
             }
         }
         else if (npcChatFocus4)
         {
             npcChatCornerItem = 0;
             SoundEngine.PlaySound(12);
             npcChatText = player[myPlayer].currentShoppingSettings.HappinessReport;
         }
         else
         {
             if (!npcChatFocus3 || player[myPlayer].talkNPC < 0)
             {
                 return;
             }
             if (npc[player[myPlayer].talkNPC].type == 20)
             {
                 SoundEngine.PlaySound(12);
                 npcChatText = Lang.GetDryadWorldStatusDialog(out var worldIsEntirelyPure);
                 if (CanDryadPlayStardewAnimation(LocalPlayer, npc[player[myPlayer].talkNPC]))
                 {
                     NPC.PreventJojaColaDialog = true;
                     NPC.RerollDryadText = 2;
                     LocalPlayer.ConsumeItem(5275, reverseOrder: true);
                     if (netMode == 1)
                     {
                         NetMessage.SendData(144);
                     }
                     else
                     {
                         NPC.HaveDryadDoStardewAnimation();
                     }
                     npcChatText = Language.GetTextValue("StardewTalk.PlayerGivesCola");
                 }
                 else if (worldIsEntirelyPure)
                 {
                     AchievementsHelper.HandleSpecialEvent(player[myPlayer], 27);
                 }
             }
             if (npc[player[myPlayer].talkNPC].type == 208)
             {
                 SoundEngine.PlaySound(12);
                 int num28 = rand.Next(1, 4);
                 npcChatText = Language.GetTextValue("PartyGirlSpecialText.Music" + num28);
                 swapMusic = !swapMusic;
             }
             else if (npc[player[myPlayer].talkNPC].type == 22)
             {
                 playerInventory = true;
                 npcChatText = "";
                 SoundEngine.PlaySound(12);
                 InGuideCraftMenu = true;
                 UILinkPointNavigator.GoToDefaultPage();
             }
             else if (npc[player[myPlayer].talkNPC].type == 107)
             {
                 playerInventory = true;
                 npcChatText = "";
                 SoundEngine.PlaySound(12);
                 InReforgeMenu = true;
                 UILinkPointNavigator.GoToDefaultPage();
             }
             else if (npc[player[myPlayer].talkNPC].type == 353)
             {
                 OpenHairWindow();
             }
             else if (npc[player[myPlayer].talkNPC].type == 207)
             {
                 npcChatCornerItem = 0;
                 SoundEngine.PlaySound(12);
                 bool gotDye = false;
                 int num29 = player[myPlayer].FindItem(ItemID.Sets.ExoticPlantsForDyeTrade);
                 if (num29 != -1)
                 {
                     player[myPlayer].inventory[num29].stack--;
                     if (player[myPlayer].inventory[num29].stack <= 0)
                     {
                         player[myPlayer].inventory[num29] = new Item();
                     }
                     gotDye = true;
                     SoundEngine.PlaySound(24);
                     player[myPlayer].GetDyeTraderReward(npc[player[myPlayer].talkNPC]);
                 }
                 npcChatText = Lang.DyeTraderQuestChat(gotDye);
             }
             else if (npc[player[myPlayer].talkNPC].type == 550)
             {
                 SoundEngine.PlaySound(12);
                 HelpText();
                 npcChatText = Lang.BartenderHelpText(npc[player[myPlayer].talkNPC]);
             }
             else if (npc[player[myPlayer].talkNPC].type == 227)
             {
                 OpenShop(25);
             }
         }
     }
References _textDisplayCache, Entity.active, ChatManager.AddChatText(), NPC.ai, Main.TextDisplayCache.AmountOfLines, anglerQuest, Lang.AnglerQuestChat(), anglerQuestFinished, anglerQuestItemNetIDs, Player.anglerQuestsFinished, anglerWhoFinishedToday, Lang.BartenderHelpText(), Player.buffType, CanDryadPlayStardewAnimation(), TextureAssets.ChatBack, CloseNPCChatOrSign(), Utils.CoinsSplit(), Item.color, Player.ConsumeItem(), BuffID.Count, Player.currentShoppingSettings, UserInterface.CurrentState, cursorOverride, debuff, Player.DelBuff(), Lang.dialog(), ChildSafety.Disabled, NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedGolemBoss, NPC.downedMechBossAny, NPC.downedPlantBoss, NPC.downedQueenBee, Utils.DrawBorderStringFourWay(), ChatManager.DrawColorCodedStringWithShadow(), drawingPlayerChat, ItemSlot.DrawMoney(), DrawNPCChatButtons(), DrawWindowsIMEPanel(), Lang.DyeTraderQuestChat(), editSign, ItemID.Sets.ExoticPlantsForDyeTrade, expertMode, Player.FindItem(), ItemTagHandler.GenerateTag(), Item.GetAlpha(), Player.GetAnglerReward(), NPC.GetChat(), Item.GetColor(), Lang.GetDryadWorldStatusDialog(), Player.GetDyeTraderReward(), GetItemDrawFrame(), ChatManager.GetStringSize(), Language.GetTextValue(), UILinkPointNavigator.GoToDefaultPage(), AchievementsHelper.HandleAnglerService(), AchievementsHelper.HandleNurseService(), AchievementsHelper.HandleSpecialEvent(), ShoppingSettings.HappinessReport, hardMode, NPC.HaveDryadDoStardewAnimation(), Player.HealEffect(), Entity.height, HelpText(), PlayerInput.IgnoreMouseInterface, InGameUI, InGuideCraftMenu, InReforgeMenu, instance, Lang.inter, Player.inventory, IsItDay(), NPCID.Sets.IsTownPet, item, SoundID.Item4, LocalPlayer, Player.maxBuffs, Player.mouseInterface, mouseLeft, mouseLeftRelease, FontAssets.MouseText, MouseText(), mouseTextColor, mouseX, mouseY, myPlayer, Item.Name, Player.name, Item.netDefaults(), netMode, Item.NewItem(), UnifiedRandom.Next(), npc, npcChatCornerItem, npcChatFocus1, npcChatFocus2, npcChatFocus3, npcChatFocus4, npcChatText, BuffID.Sets.NurseCannotRemoveDebuff, UIVirtualKeyboard.OffsetDown, OpenHairWindow(), OpenPlayerChat(), OpenShop(), IngameFancyUI.OpenVirtualKeyboard(), Player.PetAnimal(), player, playerInventory, SoundEngine.PlaySound(), Entity.position, Main.TextDisplayCache.PrepareCache(), NPC.PreventJojaColaDialog, ShoppingSettings.PriceAdjustment, rand, Player.releaseUseItem, NPC.RerollDryadText, screenWidth, NetMessage.SendData(), UIVirtualKeyboard.ShouldHideText, PlayerInput.SettingsForUI.ShowGamepadHints, sign, NPC.SpawnSkeletron(), spriteBatch, Item.stack, Player.statLife, Player.statLifeMax2, SubmitSignText(), swapMusic, Player.talkNPC, Player.taxMoney, textBlinkerCount, textBlinkerState, Main.TextDisplayCache.TextLines, TOWMusicUnlocked, Item.type, NPC.type, PlayerInput.UsingGamepad, Asset< T >.Value, LocalizedText.Value, Entity.width, and X.
Referenced by GUIChatDraw().