Terraria: Main.SubmitSignText
SubmitSignText()
static void Main.SubmitSignText () inline static
     {
         SoundEngine.PlaySound(12);
         int num = player[myPlayer].sign;
         Sign.TextSign(num, npcChatText);
         editSign = false;
         if (netMode == 1)
         {
             NetMessage.SendData(47, -1, -1, null, num);
         }
     }
References editSign, myPlayer, netMode, npcChatText, player, SoundEngine.PlaySound(), NetMessage.SendData(), Player.sign, and Sign.TextSign().
Referenced by GUIChatDrawInner().