Terraria: Main.BuyHairWindow
BuyHairWindow()
static void Main.BuyHairWindow () inline static
     {
         SoundEngine.PlaySound(18);
         hairWindow = false;
         player[myPlayer].SetTalkNPC(-1);
         npcChatCornerItem = 0;
         NetMessage.SendData(4, -1, -1, null, myPlayer);
     }
References hairWindow, myPlayer, npcChatCornerItem, player, SoundEngine.PlaySound(), NetMessage.SendData(), and Player.SetTalkNPC().
Referenced by DrawHairWindow().