Terraria: Main.CheckForMoonEventsStartingTemporarySeasons
CheckForMoonEventsStartingTemporarySeasons()
static void Main.CheckForMoonEventsStartingTemporarySeasons () inline static
     {
         if (netMode != 1)
         {
             bool num = forceHalloweenForToday;
             bool flag = forceXMasForToday;
             forceXMasForToday = false;
             forceHalloweenForToday = false;
             int waveNumber = NPC.waveNumber;
             _ = NPC.waveKills;
             if (pumpkinMoon && waveNumber >= 15)
             {
                 forceHalloweenForToday = true;
             }
             if (snowMoon && waveNumber >= 15)
             {
                 forceXMasForToday = true;
             }
             Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(50, 255, 130);
             if (num != forceHalloweenForToday)
             {
                 WorldGen.BroadcastText(NetworkText.FromKey(forceHalloweenForToday ? "Misc.StartedVictoryHalloween" : "Misc.EndedVictoryHalloween"), color);
             }
             if (flag != forceXMasForToday)
             {
                 WorldGen.BroadcastText(NetworkText.FromKey(forceXMasForToday ? "Misc.StartedVictoryXmas" : "Misc.EndedVictoryXmas"), color);
             }
         }
     }
References WorldGen.BroadcastText(), forceHalloweenForToday, forceXMasForToday, NetworkText.FromKey(), netMode, pumpkinMoon, snowMoon, NPC.waveKills, and NPC.waveNumber.
Referenced by UpdateTime_StartDay().