Terraria: Main.DrawBuffIcon
DrawBuffIcon()
static int Main.DrawBuffIcon (int drawBuffText, int buffSlotOnPlayer, int x, int y) inline static
     {
         int num = player[myPlayer].buffType[buffSlotOnPlayer];
         if (num == 0)
         {
             return drawBuffText;
         }
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(buffAlpha[buffSlotOnPlayer], buffAlpha[buffSlotOnPlayer], buffAlpha[buffSlotOnPlayer], buffAlpha[buffSlotOnPlayer]);
         spriteBatch.Draw(TextureAssets.Buff[num].Value, new Vector2(x, y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Buff[num].Width(), TextureAssets.Buff[num].Height()), color, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         if (TryGetBuffTime(buffSlotOnPlayer, out var buffTimeValue) && buffTimeValue > 2)
         {
             string text = Lang.LocalizedDuration(new TimeSpan(0, 0, buffTimeValue / 60), abbreviated: true, showAllAvailableUnits: false);
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.ItemStack.Value, text, new Vector2(x, y + TextureAssets.Buff[num].Height()), color, 0f, default(Vector2), 0.8f, SpriteEffects.None, 0f);
         }
         if (mouseX < x + TextureAssets.Buff[num].Width() && mouseY < y + TextureAssets.Buff[num].Height() && mouseX > x && mouseY > y)
         {
             drawBuffText = buffSlotOnPlayer;
             buffAlpha[buffSlotOnPlayer] += 0.1f;
             bool flag = mouseRight && mouseRightRelease;
             if (PlayerInput.UsingGamepad)
             {
                 flag = mouseLeft && mouseLeftRelease && playerInventory;
                 if (playerInventory)
                 {
                     player[myPlayer].mouseInterface = true;
                 }
             }
             else
             {
                 player[myPlayer].mouseInterface = true;
             }
             if (flag)
             {
                 TryRemovingBuff(buffSlotOnPlayer, num);
             }
         }
         else
         {
             buffAlpha[buffSlotOnPlayer] -= 0.05f;
         }
         if (buffAlpha[buffSlotOnPlayer] > 1f)
         {
             buffAlpha[buffSlotOnPlayer] = 1f;
         }
         else if ((double)buffAlpha[buffSlotOnPlayer] < 0.4)
         {
             buffAlpha[buffSlotOnPlayer] = 0.4f;
         }
         if (PlayerInput.UsingGamepad && !playerInventory)
         {
             drawBuffText = -1;
         }
         return drawBuffText;
     }
References TextureAssets.Buff, buffAlpha, Player.buffType, DynamicSpriteFontExtensionMethods.DrawString(), FontAssets.ItemStack, Lang.LocalizedDuration(), Player.mouseInterface, mouseLeft, mouseLeftRelease, mouseRight, mouseRightRelease, mouseX, mouseY, myPlayer, player, playerInventory, spriteBatch, TryGetBuffTime(), TryRemovingBuff(), PlayerInput.UsingGamepad, and Asset< T >.Value.
Referenced by DrawInterface_Resources_Buffs(), and DrawInventory().