Terraria: Main.DrawNetplayStatusText
DrawNetplayStatusText()
static void Main.DrawNetplayStatusText () inline static private
     {
         if (netMode == 1 && !string.IsNullOrWhiteSpace(Netplay.Connection.StatusText))
         {
             string text = Netplay.Connection.StatusText;
             if (!Netplay.Connection.HideStatusTextPercent)
             {
                 text = text + ": " + (int)((float)Netplay.Connection.StatusCount / (float)Netplay.Connection.StatusMax * 100f) + "%";
             }
             if (_netplayStatusTextSnippets == null || _oldNetplayStatusText != text)
             {
                 _netplayStatusTextSnippets = ChatManager.ParseMessage(text, Microsoft.Xna.Framework.Color.White).ToArray();
                 _oldNetplayStatusText = text;
             }
             Vector2 position = new Vector2(628f - ChatManager.GetStringSize(FontAssets.MouseText.Value, _netplayStatusTextSnippets, Vector2.One).X * 0.5f + (float)(screenWidth - 800), 84f);
             int hoveredSnippet;
             if (Netplay.Connection.StatusTextHasShadows)
             {
                 ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, _netplayStatusTextSnippets, position, 0f, Vector2.Zero, Vector2.One, out hoveredSnippet);
             }
             else
             {
                 ChatManager.DrawColorCodedString(spriteBatch, FontAssets.MouseText.Value, _netplayStatusTextSnippets, position, new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor), 0f, Vector2.Zero, Vector2.One, out hoveredSnippet, -1f);
             }
         }
     }
References _netplayStatusTextSnippets, _oldNetplayStatusText, TextSnippet.Color, Netplay.Connection, ChatManager.DrawColorCodedString(), ChatManager.DrawColorCodedStringWithShadow(), ChatManager.GetStringSize(), RemoteServer.HideStatusTextPercent, FontAssets.MouseText, mouseTextColor, netMode, ChatManager.ParseMessage(), screenWidth, spriteBatch, RemoteServer.StatusCount, RemoteServer.StatusMax, RemoteServer.StatusText, RemoteServer.StatusTextHasShadows, and Asset< T >.Value.
Referenced by DoDraw().