Terraria: Main.DrawProj_Flamethrower
DrawProj_Flamethrower()
static void Main.DrawProj_Flamethrower (Projectile proj) inline static private
     {
         bool flag = proj.ai[0] == 1f;
         float num = 60f;
         float num2 = 12f;
         float fromMax = num + num2;
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         Microsoft.Xna.Framework.Color transparent = Microsoft.Xna.Framework.Color.Transparent;
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(255, 80, 20, 200);
         Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(255, 255, 20, 70);
         Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(255, 80, 20, 100), color2, 0.25f);
         Microsoft.Xna.Framework.Color color4 = new Microsoft.Xna.Framework.Color(80, 80, 80, 100);
         float num3 = 0.35f;
         float num4 = 0.7f;
         float num5 = 0.85f;
         float num6 = ((proj.localAI[0] > num - 10f) ? 0.175f : 0.2f);
         if (flag)
         {
             color = new Microsoft.Xna.Framework.Color(95, 120, 255, 200);
             color2 = new Microsoft.Xna.Framework.Color(50, 180, 255, 70);
             color3 = new Microsoft.Xna.Framework.Color(95, 160, 255, 100);
             color4 = new Microsoft.Xna.Framework.Color(33, 125, 202, 100);
         }
         int num7 = 3;
         int num8 = 2;
         int verticalFrames = 7;
         float num9 = Utils.Remap(proj.localAI[0], num, fromMax, 1f, 0f);
         float num10 = Math.Min(proj.localAI[0], 20f);
         float num11 = Utils.Remap(proj.localAI[0], 0f, fromMax, 0f, 1f);
         float num12 = Utils.Remap(num11, 0.2f, 0.5f, 0.25f, 1f);
         Microsoft.Xna.Framework.Rectangle rectangle = ((!flag) ? value.Frame(1, verticalFrames, 0, 3) : value.Frame(1, verticalFrames, 0, (int)Utils.Remap(num11, 0.5f, 1f, 3f, 5f)));
         if (!(num11 < 1f))
         {
             return;
         }
         for (int i = 0; i < 2; i++)
         {
             for (float num13 = 1f; num13 >= 0f; num13 -= num6)
             {
                 transparent = ((num11 < 0.1f) ? Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color.Transparent, color, Utils.GetLerpValue(0f, 0.1f, num11, clamped: true)) : ((num11 < 0.2f) ? Microsoft.Xna.Framework.Color.Lerp(color, color2, Utils.GetLerpValue(0.1f, 0.2f, num11, clamped: true)) : ((num11 < num3) ? color2 : ((num11 < num4) ? Microsoft.Xna.Framework.Color.Lerp(color2, color3, Utils.GetLerpValue(num3, num4, num11, clamped: true)) : ((num11 < num5) ? Microsoft.Xna.Framework.Color.Lerp(color3, color4, Utils.GetLerpValue(num4, num5, num11, clamped: true)) : ((!(num11 < 1f)) ? Microsoft.Xna.Framework.Color.Transparent : Microsoft.Xna.Framework.Color.Lerp(color4, Microsoft.Xna.Framework.Color.Transparent, Utils.GetLerpValue(num5, 1f, num11, clamped: true))))))));
                 float num14 = (1f - num13) * Utils.Remap(num11, 0f, 0.2f, 0f, 1f);
                 Vector2 vector = proj.Center - screenPosition + proj.velocity * (0f - num10) * num13;
                 Microsoft.Xna.Framework.Color color5 = transparent * num14;
                 Microsoft.Xna.Framework.Color color6 = color5;
                 if (!flag)
                 {
                     color6.G /= 2;
                     color6.B /= 2;
                     color6.A = (byte)Math.Min((float)(int)color5.A + 80f * num14, 255f);
                     Utils.Remap(proj.localAI[0], 20f, fromMax, 0f, 1f);
                 }
                 float num15 = 1f / num6 * (num13 + 1f);
                 float num16 = proj.rotation + num13 * ((float)Math.PI / 2f) + GlobalTimeWrappedHourly * num15 * 2f;
                 float num17 = proj.rotation - num13 * ((float)Math.PI / 2f) - GlobalTimeWrappedHourly * num15 * 2f;
                 switch (i)
                 {
                 case 0:
                     EntitySpriteDraw(value, vector + proj.velocity * (0f - num10) * num6 * 0.5f, rectangle, color6 * num9 * 0.25f, num16 + (float)Math.PI / 4f, rectangle.Size() / 2f, num12, SpriteEffects.None);
                     EntitySpriteDraw(value, vector, rectangle, color6 * num9, num17, rectangle.Size() / 2f, num12, SpriteEffects.None);
                     break;
                 case 1:
                     if (!flag)
                     {
                         EntitySpriteDraw(value, vector + proj.velocity * (0f - num10) * num6 * 0.2f, rectangle, color5 * num9 * 0.25f, num16 + (float)Math.PI / 2f, rectangle.Size() / 2f, num12 * 0.75f, SpriteEffects.None);
                         EntitySpriteDraw(value, vector, rectangle, color5 * num9, num17 + (float)Math.PI / 2f, rectangle.Size() / 2f, num12 * 0.75f, SpriteEffects.None);
                     }
                     break;
                 }
             }
         }
     }
References Projectile.ai, Entity.Center, EntitySpriteDraw(), Utils.GetLerpValue(), GlobalTimeWrappedHourly, Projectile.localAI, TextureAssets.Projectile, Utils.Remap(), Projectile.rotation, screenPosition, Projectile.type, Asset< T >.Value, and Entity.velocity.
Referenced by DrawProjDirect().