Terraria: Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition
DrawMapIcons_PotionOfReturnAppearAfterUsePosition()
void Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Microsoft.Xna.Framework.Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
     {
         Vector2? potionOfReturnOriginalUsePosition = LocalPlayer.PotionOfReturnOriginalUsePosition;
         if (!potionOfReturnOriginalUsePosition.HasValue)
         {
             return;
         }
         Vector2 vec = (potionOfReturnOriginalUsePosition + new Vector2(0f, -LocalPlayer.height / 2)).Value / 16f - mapTopLeft;
         vec *= mapScale;
         vec += mapX2Y2AndOff;
         vec = vec.Floor();
         if (!mapRect.HasValue || mapRect.Value.Contains(vec.ToPoint()))
         {
             Texture2D value = TextureAssets.Extra[173].Value;
             Microsoft.Xna.Framework.Rectangle rectangle = value.Frame();
             spriteBatch.Draw(value, vec, rectangle, Microsoft.Xna.Framework.Color.White, 0f, rectangle.Size() / 2f, drawScale, SpriteEffects.None, 0f);
             if (Utils.CenteredRectangle(vec, rectangle.Size() * drawScale).Contains(MouseScreen.ToPoint()))
             {
                 mouseTextString = Language.GetTextValue("GameUI.PotionOfReturnExitPortal");
                 _ = MouseScreen + new Vector2(-28f) + new Vector2(4f, 0f);
             }
         }
     }
References Utils.CenteredRectangle(), TextureAssets.Extra, Language.GetTextValue(), Entity.height, LocalPlayer, MouseScreen, Player.PotionOfReturnOriginalUsePosition, spriteBatch, and Asset< T >.Value.
Referenced by DrawMiscMapIcons().