Terraria: Main.SetGraphicsProfileInternal
SetGraphicsProfileInternal()
static void Main.SetGraphicsProfileInternal () inline static private
     {
         _currentGraphicsProfile = _selectedGraphicsProfile;
         graphics.GraphicsProfile = _selectedGraphicsProfile;
         switch (_selectedGraphicsProfile)
         {
         case GraphicsProfile.HiDef:
             maxScreenW = 4096;
             maxScreenH = 4096;
             _renderTargetMaxSize = 4096;
             TrySupporting8K();
             break;
         case GraphicsProfile.Reach:
             maxScreenW = 1920;
             maxScreenH = 1200;
             _renderTargetMaxSize = 2048;
             break;
         }
         try
         {
             graphics.ApplyChanges();
         }
         catch (NoSuitableGraphicsDeviceException)
         {
             if (_currentGraphicsProfile == GraphicsProfile.HiDef)
             {
                 _selectedGraphicsProfile = GraphicsProfile.Reach;
                 SetGraphicsProfileInternal();
             }
         }
         instance.EnsureRenderTargetContent();
     }
References _currentGraphicsProfile, _renderTargetMaxSize, _selectedGraphicsProfile, EnsureRenderTargetContent(), graphics, instance, maxScreenH, maxScreenW, and TrySupporting8K().
Referenced by SetGraphicsProfile().