Terraria: Main.DrawWhip_RainbowWhip
DrawWhip_RainbowWhip()
static Vector2 Main.DrawWhip_RainbowWhip (Projectile proj, List< Vector2 > controlPoints) inline static
     {
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         Microsoft.Xna.Framework.Rectangle rectangle = value.Frame(1, 5);
         int height = rectangle.Height;
         rectangle.Height -= 2;
         Vector2 vector = rectangle.Size() / 2f;
         Vector2 vector2 = controlPoints[0];
         float miscCounterNormalized = player[proj.owner].miscCounterNormalized;
         for (int i = 0; i < controlPoints.Count - 1; i++)
         {
             bool flag = true;
             Vector2 origin = vector;
             switch (i)
             {
             case 0:
                 origin.Y -= 4f;
                 break;
             case 39:
                 rectangle.Y = height * 4;
                 break;
             default:
                 flag = i % 2 == 0;
                 rectangle.Y = height * (1 + i % 3);
                 break;
             }
             Vector2 vector3 = controlPoints[i];
             Vector2 vector4 = controlPoints[i + 1] - vector3;
             if (flag)
             {
                 Microsoft.Xna.Framework.Color color = hslToRgb((miscCounterNormalized * 5f + (float)i * 0.05f) % 1f, 1f, 0.5f);
                 Microsoft.Xna.Framework.Color color2 = color;
                 float lerpValue = Utils.GetLerpValue(controlPoints.Count - 10, controlPoints.Count - 2, i, clamped: true);
                 float num = MathHelper.Lerp(1f, 1f, lerpValue);
                 color2.A /= 2;
                 color2.A = (byte)((float)(int)color2.A * lerpValue);
                 float rotation = vector4.ToRotation() - (float)Math.PI / 2f;
                 Microsoft.Xna.Framework.Color color3 = Lighting.GetColor(vector3.ToTileCoordinates());
                 spriteBatch.Draw(value, vector2 - screenPosition, rectangle, Microsoft.Xna.Framework.Color.Lerp(color3, color2, 0.5f), rotation, origin, num, SpriteEffects.None, 0f);
                 color2.A = 0;
                 spriteBatch.Draw(value, vector2 - screenPosition, rectangle, color2 * 0.1f, rotation, origin, num * 1.2f, SpriteEffects.None, 0f);
                 if (i == 39)
                 {
                     color2 = color;
                     color2.A = 127;
                     spriteBatch.Draw(value, vector2 - screenPosition, rectangle, color2 * 0.3f, rotation, origin, num * 1.4f, SpriteEffects.None, 0f);
                 }
             }
             vector2 += vector4;
         }
         return vector2;
     }
References Lighting.GetColor(), Utils.GetLerpValue(), hslToRgb(), Player.miscCounterNormalized, Projectile.owner, player, TextureAssets.Projectile, screenPosition, spriteBatch, Projectile.type, and Asset< T >.Value.
Referenced by DrawWhip().