Terraria: Main.DrawTileCracks
DrawTileCracks()
void Main.DrawTileCracks (int crackType, HitTile hitter) inline
     {
         Vector2 vector = new Vector2(offScreenRange, offScreenRange);
         if (drawToScreen)
         {
             vector = Vector2.Zero;
         }
         bool flag = ShouldShowInvisibleWalls();
         for (int i = 0; i < hitter.data.Length; i++)
         {
             if (hitter.data[i].type != crackType)
             {
                 continue;
             }
             int damage = hitter.data[i].damage;
             if (damage < 20)
             {
                 continue;
             }
             int x = hitter.data[i].X;
             int y = hitter.data[i].Y;
             if (!WorldGen.InWorld(x, y))
             {
                 continue;
             }
             bool flag2 = tile[x, y] != null;
             if (flag2 && crackType == 1)
             {
                 flag2 = flag2 && tile[x, y].active() && (flag || !tile[x, y].invisibleBlock());
             }
             if (flag2 && crackType == 2)
             {
                 flag2 = flag2 && tile[x, y].wall != 0 && (flag || !tile[x, y].invisibleWall());
             }
             if (!flag2)
             {
                 continue;
             }
             bool flag3 = false;
             bool flag4 = false;
             if (tile[x, y].type == 10)
             {
                 flag3 = false;
             }
             else if (tileSolid[tile[x, y].type] && !tileSolidTop[tile[x, y].type])
             {
                 flag3 = true;
             }
             else if (WorldGen.IsTreeType(tile[x, y].type))
             {
                 flag4 = true;
                 int num = tile[x, y].frameX / 22;
                 int num2 = tile[x, y].frameY / 22;
                 if (num2 < 9)
                 {
                     flag3 = ((num != 1 && num != 2) || num2 < 6 || num2 > 8) && (num != 3 || num2 > 2) && (num != 4 || num2 < 3 || num2 > 5) && ((num != 5 || num2 < 6 || num2 > 8) ? true : false);
                 }
             }
             else if (tile[x, y].type == 72)
             {
                 flag4 = true;
                 if (tile[x, y].frameX <= 34)
                 {
                     flag3 = true;
                 }
             }
             if (flag3 && tile[x, y].slope() == 0 && !tile[x, y].halfBrick())
             {
                 int num3 = 0;
                 if (damage >= 80)
                 {
                     num3 = 3;
                 }
                 else if (damage >= 60)
                 {
                     num3 = 2;
                 }
                 else if (damage >= 40)
                 {
                     num3 = 1;
                 }
                 else if (damage >= 20)
                 {
                     num3 = 0;
                 }
                 Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle(hitter.data[i].crackStyle * 18, num3 * 18, 16, 16);
                 if (flag4)
                 {
                     value.X = (4 + hitter.data[i].crackStyle / 2) * 18;
                 }
                 spriteBatch.Draw(TextureAssets.TileCrack.Value, new Vector2(x * 16 - (int)screenPosition.X, y * 16 - (int)screenPosition.Y) + vector, value, Lighting.GetColor(x, y), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
         }
     }
References Tile.active(), HitTile.HitTileObject.crackStyle, HitTile.HitTileObject.damage, HitTile.data, drawToScreen, Tile.frameX, Tile.frameY, Lighting.GetColor(), Tile.halfBrick(), Tile.invisibleBlock(), Tile.invisibleWall(), WorldGen.InWorld(), WorldGen.IsTreeType(), offScreenRange, screenPosition, ShouldShowInvisibleWalls(), spriteBatch, tile, TextureAssets.TileCrack, tileSolid, tileSolidTop, HitTile.HitTileObject.type, Tile.type, Asset< T >.Value, Tile.wall, HitTile.HitTileObject.X, and HitTile.HitTileObject.Y.
Referenced by TileDrawing.Draw(), and WallDrawing.DrawWalls().