Terraria: Main.DrawItem
DrawItem()
void Main.DrawItem (Item item, int whoami) inline protected
     {
         if (!item.active || item.IsAir)
         {
             return;
         }
         instance.LoadItem(item.type);
         DrawItem_GetBasics(item, whoami, out var texture, out var frame, out var glowmaskFrame);
         Vector2 vector = frame.Size() / 2f;
         Vector2 vector2 = new Vector2((float)(item.width / 2) - vector.X, item.height - frame.Height);
         Vector2 vector3 = item.position - screenPosition + vector + vector2;
         float num = item.velocity.X * 0.2f;
         if (item.shimmered)
         {
             num = 0f;
         }
         float scale = 1f;
         Microsoft.Xna.Framework.Color color = Lighting.GetColor(item.Center.ToTileCoordinates());
         Microsoft.Xna.Framework.Color currentColor = item.GetAlpha(color);
         if (item.shimmered)
         {
             currentColor.R = (byte)(255f * (1f - item.shimmerTime));
             currentColor.G = (byte)(255f * (1f - item.shimmerTime));
             currentColor.B = (byte)(255f * (1f - item.shimmerTime));
             currentColor.A = (byte)(255f * (1f - item.shimmerTime));
         }
         else if (item.shimmerTime > 0f)
         {
             currentColor.R = (byte)((float)(int)currentColor.R * (1f - item.shimmerTime));
             currentColor.G = (byte)((float)(int)currentColor.G * (1f - item.shimmerTime));
             currentColor.B = (byte)((float)(int)currentColor.B * (1f - item.shimmerTime));
             currentColor.A = (byte)((float)(int)currentColor.A * (1f - item.shimmerTime));
         }
         ItemSlot.GetItemLight(ref currentColor, ref scale, item);
         int num2 = item.glowMask;
         if (!gamePaused && base.IsActive && (item.IsACoin || item.type == 58 || item.type == 109) && color.R > 60 && (float)rand.Next(500) - (Math.Abs(item.velocity.X) + Math.Abs(item.velocity.Y)) * 10f < (float)(color.R / 50))
         {
             int type = 43;
             Microsoft.Xna.Framework.Color newColor = Microsoft.Xna.Framework.Color.White;
             int alpha = 254;
             float scale2 = 0.5f;
             if (item.IsACoin)
             {
                 newColor = default(Microsoft.Xna.Framework.Color);
                 alpha = 0;
                 scale2 = 1f;
             }
             switch (item.type)
             {
             case 71:
                 type = 244;
                 break;
             case 72:
                 type = 245;
                 break;
             case 73:
                 type = 246;
                 break;
             case 74:
                 type = 247;
                 break;
             }
             int num3 = Dust.NewDust(item.position, item.width, item.height, type, 0f, 0f, alpha, newColor, scale2);
             dust[num3].velocity *= 0f;
         }
         if (ItemID.Sets.BossBag[item.type])
         {
             float num4 = (float)item.timeSinceItemSpawned / 240f + GlobalTimeWrappedHourly * 0.04f;
             float globalTimeWrappedHourly = GlobalTimeWrappedHourly;
             globalTimeWrappedHourly %= 4f;
             globalTimeWrappedHourly /= 2f;
             if (globalTimeWrappedHourly >= 1f)
             {
                 globalTimeWrappedHourly = 2f - globalTimeWrappedHourly;
             }
             globalTimeWrappedHourly = globalTimeWrappedHourly * 0.5f + 0.5f;
             for (float num5 = 0f; num5 < 1f; num5 += 0.25f)
             {
                 spriteBatch.Draw(texture, vector3 + new Vector2(0f, 8f).RotatedBy((num5 + num4) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly, frame, new Microsoft.Xna.Framework.Color(90, 70, 255, 50), num, vector, scale, SpriteEffects.None, 0f);
             }
             for (float num6 = 0f; num6 < 1f; num6 += 0.34f)
             {
                 spriteBatch.Draw(texture, vector3 + new Vector2(0f, 4f).RotatedBy((num6 + num4) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly, frame, new Microsoft.Xna.Framework.Color(140, 120, 255, 77), num, vector, scale, SpriteEffects.None, 0f);
             }
         }
         else if (item.type == 75)
         {
             float num7 = (float)item.timeSinceItemSpawned / 240f + GlobalTimeWrappedHourly * 0.04f;
             float globalTimeWrappedHourly2 = GlobalTimeWrappedHourly;
             globalTimeWrappedHourly2 %= 5f;
             globalTimeWrappedHourly2 /= 2.5f;
             if (globalTimeWrappedHourly2 >= 1f)
             {
                 globalTimeWrappedHourly2 = 2f - globalTimeWrappedHourly2;
             }
             globalTimeWrappedHourly2 = globalTimeWrappedHourly2 * 0.5f + 0.5f;
             for (float num8 = 0f; num8 < 1f; num8 += 0.25f)
             {
                 spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + new Vector2(0f, 8f).RotatedBy((num8 + num7) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly2, frame, new Microsoft.Xna.Framework.Color(50, 50, 255, 50), num, vector, scale, SpriteEffects.None, 0f);
             }
             for (float num9 = 0f; num9 < 1f; num9 += 0.34f)
             {
                 spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + new Vector2(0f, 4f).RotatedBy((num9 + num7) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly2, frame, new Microsoft.Xna.Framework.Color(120, 120, 255, 127), num, vector, scale, SpriteEffects.None, 0f);
             }
         }
         else if (item.type == 4143)
         {
             float num10 = (float)item.timeSinceItemSpawned / 240f + GlobalTimeWrappedHourly * 0.04f;
             float globalTimeWrappedHourly3 = GlobalTimeWrappedHourly;
             globalTimeWrappedHourly3 %= 5f;
             globalTimeWrappedHourly3 /= 2.5f;
             if (globalTimeWrappedHourly3 >= 1f)
             {
                 globalTimeWrappedHourly3 = 2f - globalTimeWrappedHourly3;
             }
             globalTimeWrappedHourly3 = globalTimeWrappedHourly3 * 0.5f + 0.5f;
             for (float num11 = 0f; num11 < 1f; num11 += 0.34f)
             {
                 spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + new Vector2(0f, 8f).RotatedBy((num11 + num10) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly3, frame, new Microsoft.Xna.Framework.Color(30, 30, 155, 60), num, vector, scale, SpriteEffects.None, 0f);
             }
             for (float num12 = 0f; num12 < 1f; num12 += 0.34f)
             {
                 spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + new Vector2(0f, 4f).RotatedBy((num12 + num10) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly3, frame, new Microsoft.Xna.Framework.Color(60, 60, 127, 57), num, vector, scale, SpriteEffects.None, 0f);
             }
             spriteBatch.Draw(texture, vector3, frame, new Microsoft.Xna.Framework.Color(255, 255, 255, 128), num, vector, scale, SpriteEffects.None, 0f);
         }
         if ((item.type >= 1522 && item.type <= 1527) || item.type == 3643)
         {
             currentColor = ((!(item.shimmerTime > 0f)) ? new Microsoft.Xna.Framework.Color(250, 250, 250, mouseTextColor / 2) : new Microsoft.Xna.Framework.Color((int)(250f * (1f - item.shimmerTime)), (int)(250f * (1f - item.shimmerTime)), (int)(250f * (1f - item.shimmerTime)), (int)((float)(mouseTextColor / 2) * (1f - item.shimmerTime))));
             scale = (float)(int)mouseTextColor / 1000f + 0.8f;
         }
         if (item.type == 3779)
         {
             num2 = -1;
         }
         spriteBatch.Draw(texture, vector3, frame, currentColor, num, vector, scale, SpriteEffects.None, 0f);
         if (item.shimmered)
         {
             spriteBatch.Draw(texture, vector3, frame, new Microsoft.Xna.Framework.Color(currentColor.R, currentColor.G, currentColor.B, 0), num, vector, scale, SpriteEffects.None, 0f);
         }
         if (item.color != Microsoft.Xna.Framework.Color.Transparent)
         {
             spriteBatch.Draw(texture, vector3, frame, item.GetColor(color), num, vector, scale, SpriteEffects.None, 0f);
         }
         if (num2 != -1)
         {
             Microsoft.Xna.Framework.Color color2 = new Microsoft.Xna.Framework.Color(250, 250, 250, item.alpha);
             int type2 = item.type;
             if (type2 == 5146)
             {
                 color2 = new Microsoft.Xna.Framework.Color(DiscoR, DiscoG, DiscoB);
             }
             spriteBatch.Draw(TextureAssets.GlowMask[num2].Value, vector3, frame, color2, num, vector, scale, SpriteEffects.None, 0f);
         }
         if (ItemID.Sets.TrapSigned[item.type])
         {
             spriteBatch.Draw(TextureAssets.Wire.Value, vector3 + frame.Size().RotatedBy(num) * 0.45f * item.scale, new Microsoft.Xna.Framework.Rectangle(4, 58, 8, 8), currentColor, 0f, new Vector2(4f), 1f, SpriteEffects.None, 0f);
         }
         if (item.type == 3858)
         {
             spriteBatch.Draw(TextureAssets.GlowMask[233].Value, vector3, glowmaskFrame, new Microsoft.Xna.Framework.Color(255, 255, 255, 63) * 0.75f, num, glowmaskFrame.Size() / 2f, scale, SpriteEffects.None, 0f);
         }
         if (ItemID.Sets.DrawUnsafeIndicator[item.type])
         {
             Vector2 vector4 = new Vector2(-4f, -4f) * scale;
             Texture2D value = TextureAssets.Extra[258].Value;
             Microsoft.Xna.Framework.Rectangle rectangle = value.Frame();
             spriteBatch.Draw(value, vector3 + vector4 + frame.Size().RotatedBy(num) * 0.45f * item.scale, rectangle, currentColor, num, rectangle.Size() / 2f, 1f, SpriteEffects.None, 0f);
         }
     }
References Entity.active, Item.alpha, ItemID.Sets.BossBag, Entity.Center, Item.color, DiscoB, DiscoG, DiscoR, DrawItem_GetBasics(), ItemID.Sets.DrawUnsafeIndicator, dust, TextureAssets.Extra, gamePaused, Item.GetAlpha(), Item.GetColor(), Lighting.GetColor(), ItemSlot.GetItemLight(), GlobalTimeWrappedHourly, TextureAssets.GlowMask, Item.glowMask, Entity.height, instance, Item.IsACoin, Item.IsAir, TextureAssets.Item, item, LoadItem(), mouseTextColor, Dust.NewDust(), UnifiedRandom.Next(), Entity.position, rand, Item.scale, screenPosition, Item.shimmered, Item.shimmerTime, spriteBatch, Item.timeSinceItemSpawned, ItemID.Sets.TrapSigned, Item.type, Asset< T >.Value, Dust.velocity, Entity.velocity, Entity.width, and TextureAssets.Wire.
Referenced by DrawItems().