Terraria: Main.DoUpdate_WhilePaused
DoUpdate_WhilePaused()
static void Main.DoUpdate_WhilePaused () inline static private
     {
         if (!drawingPlayerChat && !editSign && !editChest && !blockInput)
         {
             Main.player[myPlayer].controlInv = PlayerInput.Triggers.Current.Inventory;
             Main.player[myPlayer].controlCreativeMenu = PlayerInput.Triggers.Current.OpenCreativePowersMenu;
             Player player = Main.player[myPlayer];
             if (player.controlCreativeMenu)
             {
                 if (player.releaseCreativeMenu)
                 {
                     player.ToggleCreativeMenu();
                 }
                 player.releaseCreativeMenu = false;
             }
             else
             {
                 player.releaseCreativeMenu = true;
             }
             if (player.controlInv)
             {
                 if (player.releaseInventory)
                 {
                     player.ToggleInv();
                 }
                 player.releaseInventory = false;
             }
             else
             {
                 player.releaseInventory = true;
             }
         }
         if (playerInventory)
         {
             Main.player[myPlayer].RefreshInfoAccs();
             Recipe.GetThroughDelayedFindRecipes();
             int num = PlayerInput.ScrollWheelDelta / 120;
             bool flag = true;
             if (recBigList)
             {
                 int num2 = 42;
                 int num3 = 340;
                 int num4 = 310;
                 PlayerInput.SetZoom_UI();
                 int num5 = (screenWidth - num4 - 280) / num2;
                 int num6 = (screenHeight - num3 - 20) / num2;
                 if (new Microsoft.Xna.Framework.Rectangle(num4, num3, num5 * num2, num6 * num2).Contains(MouseScreen.ToPoint()))
                 {
                     int num7 = Math.Sign(num);
                     while (num != 0)
                     {
                         if (num < 0)
{
                             recStart -= num5;
                             if (recStart < 0)
{
                                 recStart = 0;
                             }
                         }
                         else
{
                             recStart += num5;
                             SoundEngine.PlaySound(12);
                             if (recStart > numAvailableRecipes - num5)
{
                                 recStart = numAvailableRecipes - num5;
                             }
                         }
                         num -= num7;
                     }
                 }
                 PlayerInput.SetZoom_World();
             }
             if (flag)
             {
                 focusRecipe += num;
                 if (focusRecipe > numAvailableRecipes - 1)
                 {
                     focusRecipe = numAvailableRecipes - 1;
                 }
                 if (focusRecipe < 0)
                 {
                     focusRecipe = 0;
                 }
             }
             Main.player[myPlayer].dropItemCheck();
         }
         Main.player[myPlayer].head = Main.player[myPlayer].armor[0].headSlot;
         Main.player[myPlayer].body = Main.player[myPlayer].armor[1].bodySlot;
         Main.player[myPlayer].legs = Main.player[myPlayer].armor[2].legSlot;
         if (!Main.player[myPlayer].hostile)
         {
             if (Main.player[myPlayer].armor[10].headSlot >= 0)
             {
                 Main.player[myPlayer].head = Main.player[myPlayer].armor[10].headSlot;
             }
             if (Main.player[myPlayer].armor[11].bodySlot >= 0)
             {
                 Main.player[myPlayer].body = Main.player[myPlayer].armor[11].bodySlot;
             }
             if (Main.player[myPlayer].armor[12].legSlot >= 0)
             {
                 Main.player[myPlayer].legs = Main.player[myPlayer].armor[12].legSlot;
             }
         }
         if (editSign)
         {
             if (Main.player[myPlayer].sign == -1)
             {
                 editSign = false;
             }
             else
             {
                 InputTextSign();
             }
         }
         else if (editChest && Main.player[myPlayer].chest == -1)
         {
             editChest = false;
         }
         Player.tileTargetX = (int)(((float)mouseX + screenPosition.X) / 16f);
         Player.tileTargetY = (int)(((float)mouseY + screenPosition.Y) / 16f);
         Main.player[myPlayer].LookForTileInteractions();
         Main.player[myPlayer].lastChest = Main.player[myPlayer].chest;
         if (playerInventory)
         {
             Main.player[myPlayer].AdjTiles();
         }
     }
References Player.AdjTiles(), Player.armor, blockInput, Player.body, Item.bodySlot, Player.chest, Player.controlCreativeMenu, Player.controlInv, TriggersPack.Current, drawingPlayerChat, Player.dropItemCheck(), editChest, editSign, focusRecipe, Recipe.GetThroughDelayedFindRecipes(), Player.head, Item.headSlot, Player.hostile, InputTextSign(), TriggersSet.Inventory, Player.lastChest, Player.legs, Item.legSlot, Player.LookForTileInteractions(), MouseScreen, mouseX, mouseY, myPlayer, numAvailableRecipes, TriggersSet.OpenCreativePowersMenu, player, playerInventory, SoundEngine.PlaySound(), recBigList, recStart, Player.RefreshInfoAccs(), Player.releaseCreativeMenu, Player.releaseInventory, screenHeight, screenPosition, screenWidth, PlayerInput.ScrollWheelDelta, PlayerInput.SetZoom_UI(), PlayerInput.SetZoom_World(), Player.sign, Player.tileTargetX, Player.tileTargetY, Player.ToggleCreativeMenu(), Player.ToggleInv(), and PlayerInput.Triggers.
Referenced by DoUpdate().