Terraria: Main.LoadWorlds
LoadWorlds()
static void Main.LoadWorlds () inline static
     {
         WorldList.Clear();
         if (!Utils.TryCreatingDirectory(WorldPath))
         {
             return;
         }
         string[] files = Directory.GetFiles(WorldPath, "*.wld");
         int num = Math.Min(files.Length, maxLoadWorld);
         if (dedServ)
         {
             for (int i = 0; i < num; i++)
             {
                 WorldFileData allMetadata = WorldFile.GetAllMetadata(files[i], cloudSave: false);
                 if (allMetadata != null)
                 {
                     WorldList.Add(allMetadata);
                 }
                 else
                 {
                     WorldList.Add(WorldFileData.FromInvalidWorld(files[i], cloudSave: false));
                 }
             }
         }
         else
         {
             for (int j = 0; j < num; j++)
             {
                 WorldFileData allMetadata2 = WorldFile.GetAllMetadata(files[j], cloudSave: false);
                 if (allMetadata2 != null)
                 {
                     WorldList.Add(allMetadata2);
                 }
                 else
                 {
                     WorldList.Add(WorldFileData.FromInvalidWorld(files[j], cloudSave: false));
                 }
             }
         }
         if (SocialAPI.Cloud != null)
         {
             foreach (string item in from path in SocialAPI.Cloud.GetFiles()
                 where path.StartsWith(CloudWorldPath, StringComparison.CurrentCultureIgnoreCase) && path.EndsWith(".wld", StringComparison.CurrentCultureIgnoreCase)
                 select path)
             {
                 WorldFileData allMetadata3 = WorldFile.GetAllMetadata(item, cloudSave: true);
                 if (allMetadata3 != null)
                 {
                     WorldList.Add(allMetadata3);
                 }
                 else
                 {
                     WorldList.Add(WorldFileData.FromInvalidWorld(item, cloudSave: true));
                 }
             }
         }
         WorldList.Sort(WorldListSortMethod);
     }
References SocialAPI.Cloud, CloudWorldPath, dedServ, WorldFileData.FromInvalidWorld(), WorldFile.GetAllMetadata(), CloudSocialModule.GetFiles(), item, maxLoadWorld, Utils.TryCreatingDirectory(), WorldList, WorldListSortMethod(), and WorldPath.
Referenced by DedServ(), EraseWorld(), Initialize_AlmostEverything(), UIWorkshopWorldImport.OnActivate(), UIWorldSelect.OnActivate(), UIWorkshopSelectWorldToPublish.PopulateEntries(), WorldGen.RenameWorldCallBack(), and SelectPlayer().