Terraria: Main.DrawHairWindow
DrawHairWindow()
void Main.DrawHairWindow () inline protected
     {
         if (npcChatText != "" || playerInventory || player[myPlayer].chest != -1 || npcShop != 0 || player[myPlayer].talkNPC == -1 || InGuideCraftMenu)
         {
             CancelHairWindow();
             return;
         }
         Hairstyles.UpdateUnlocks();
         int count = Hairstyles.AvailableHairstyles.Count;
         int num = screenHeight / 2 + 60;
         int num2 = screenWidth / 2 - TextureAssets.HairStyleBack.Width() / 2;
         int num3 = num + 42;
         int num4 = num2 + 22;
         int num5 = num2 + 234;
         int num6 = num + 18;
         selColor = player[myPlayer].hairColor;
         spriteBatch.Draw(TextureAssets.HairStyleBack.Value, new Vector2(num2, num), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.HairStyleBack.Width(), TextureAssets.HairStyleBack.Height()), new Microsoft.Xna.Framework.Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         if (new Microsoft.Xna.Framework.Rectangle(num2, num, TextureAssets.HairStyleBack.Width(), TextureAssets.HairStyleBack.Height()).Contains(MouseScreen.ToPoint()))
         {
             int num7 = PlayerInput.ScrollWheelDelta / 120;
             num7 = -num7;
             int num8 = Math.Sign(num7);
             while (num7 != 0)
             {
                 if (num7 < 0)
                 {
                     hairStart -= 5;
                     SoundEngine.PlaySound(12);
                 }
                 else
                 {
                     hairStart += 5;
                     SoundEngine.PlaySound(12);
                 }
                 num7 -= num8;
             }
         }
         if (mouseX > num2 && mouseX < num2 + TextureAssets.HairStyleBack.Width() && mouseY > num && mouseY < num + TextureAssets.HairStyleBack.Height())
         {
             player[myPlayer].mouseInterface = true;
         }
         int num9 = num5 - 18;
         int num10 = num6 + 74;
         if (hairStart > 1)
         {
             if (mouseX >= num9 && mouseX <= num9 + TextureAssets.CraftUpButton.Width() && mouseY >= num10 && mouseY <= num10 + TextureAssets.CraftUpButton.Height())
             {
                 player[myPlayer].mouseInterface = true;
                 if (mouseLeftRelease && mouseLeft)
                 {
                     hairStart -= 15;
                     SoundEngine.PlaySound(12);
                 }
             }
             spriteBatch.Draw(TextureAssets.ScrollLeftButton.Value, new Vector2(num9, num10), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.CraftUpButton.Width(), TextureAssets.CraftUpButton.Height()), new Microsoft.Xna.Framework.Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         if (hairStart + 15 < count)
         {
             num9 += 296;
             if (mouseX >= num9 && mouseX <= num9 + TextureAssets.CraftUpButton.Width() && mouseY >= num10 && mouseY <= num10 + TextureAssets.CraftUpButton.Height())
             {
                 player[myPlayer].mouseInterface = true;
                 if (mouseLeftRelease && mouseLeft)
                 {
                     hairStart += 15;
                     SoundEngine.PlaySound(12);
                 }
             }
             spriteBatch.Draw(TextureAssets.ScrollRightButton.Value, new Vector2(num9, num10), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.CraftUpButton.Width(), TextureAssets.CraftUpButton.Height()), new Microsoft.Xna.Framework.Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         if (hairStart + 15 >= count)
         {
             hairStart = count - 15;
         }
         if (hairStart < 0)
         {
             hairStart = 0;
         }
         int num11 = 0;
         if (oldHairStyle != player[myPlayer].hair)
         {
             num11 += 100000;
         }
         if (oldHairColor != player[myPlayer].hairColor)
         {
             num11 += 20000;
         }
         num11 = (int)((double)num11 * player[myPlayer].currentShoppingSettings.PriceAdjustment);
         num11 = (int)Math.Round((float)num11 / 10000f) * 10000;
         string text = "";
         string text2 = "";
         int num12 = 0;
         int num13 = 0;
         int num14 = 0;
         int num15 = 0;
         int num16 = num11;
         _ = 0;
         if (num16 < 0)
         {
             num16 = 0;
         }
         num11 = num16;
         if (num16 >= 1000000)
         {
             num12 = num16 / 1000000;
             num16 -= num12 * 1000000;
         }
         if (num16 >= 10000)
         {
             num13 = num16 / 10000;
             num16 -= num13 * 10000;
         }
         if (num16 >= 100)
         {
             num14 = num16 / 100;
             num16 -= num14 * 100;
         }
         if (num16 >= 1)
         {
             num15 = num16;
         }
         if (num12 > 0)
         {
             text2 = text2 + num12 + " " + Lang.inter[15].Value + " ";
         }
         if (num13 > 0)
         {
             text2 = text2 + num13 + " " + Lang.inter[16].Value + " ";
         }
         if (num14 > 0)
         {
             text2 = text2 + num14 + " " + Lang.inter[17].Value + " ";
         }
         if (num15 > 0)
         {
             text2 = text2 + num15 + " " + Lang.inter[18].Value + " ";
         }
         text = Language.GetTextValue("GameUI.BuyWithValue", text2);
         if (num11 == 0)
         {
             text = Language.GetTextValue("GameUI.Buy");
         }
         int num17 = (mouseTextColor * 2 + 255) / 3;
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(num17, (int)((double)num17 / 1.1), num17 / 2, num17);
         float num18 = 0.9f;
         string text3 = text;
         int num19 = num2 + 18;
         int num20 = num + 156;
         bool flag = false;
         if (num11 > 0)
         {
             ItemSlot.DrawSavings(spriteBatch, num19, num20 - 70, horizontal: true);
         }
         if (num11 > 0 && mouseX > num19 && (float)mouseX < (float)num19 + FontAssets.MouseText.Value.MeasureString(text3).X && mouseY > num20 && (float)mouseY < (float)num20 + FontAssets.MouseText.Value.MeasureString(text3).Y)
         {
             flag = true;
             num18 = 1.1f;
             if (!npcChatFocus1)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus1 = true;
             player[myPlayer].releaseUseItem = false;
         }
         else
         {
             if (npcChatFocus1)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus1 = false;
         }
         Vector2 vector = FontAssets.MouseText.Value.MeasureString(text3);
         vector *= 0.5f;
         UILinkPointNavigator.SetPosition(2603, new Vector2(num19, num20) + vector);
         for (int i = 0; i < 5; i++)
         {
             int num21 = num19;
             int num22 = num20;
             Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Black;
             if (flag)
             {
                 color2 = Microsoft.Xna.Framework.Color.Brown;
             }
             if (i == 0)
             {
                 num21 -= 2;
             }
             if (i == 1)
             {
                 num21 += 2;
             }
             if (i == 2)
             {
                 num22 -= 2;
             }
             if (i == 3)
             {
                 num22 += 2;
             }
             if (i == 4)
             {
                 color2 = ((num11 != 0) ? color : new Microsoft.Xna.Framework.Color(100, 100, 100));
             }
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, text3, new Vector2((float)num21 + vector.X, (float)num22 + vector.Y), color2, 0f, vector, num18, SpriteEffects.None, 0f);
         }
         num18 = 0.9f;
         string textValue = Language.GetTextValue("GameUI.Cancel");
         num19 += 130;
         flag = false;
         if (mouseX > num19 && (float)mouseX < (float)num19 + FontAssets.MouseText.Value.MeasureString(textValue).X && mouseY > num20 && (float)mouseY < (float)num20 + FontAssets.MouseText.Value.MeasureString(textValue).Y)
         {
             flag = true;
             num18 = 1.1f;
             if (!npcChatFocus2)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus2 = true;
             player[myPlayer].releaseUseItem = false;
         }
         else
         {
             if (npcChatFocus2)
             {
                 SoundEngine.PlaySound(12);
             }
             npcChatFocus2 = false;
         }
         vector = FontAssets.MouseText.Value.MeasureString(textValue);
         vector *= 0.5f;
         UILinkPointNavigator.SetPosition(2604, new Vector2(num19, num20) + vector);
         for (int j = 0; j < 5; j++)
         {
             int num23 = num19;
             int num24 = num20;
             Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.Black;
             if (flag)
             {
                 color3 = Microsoft.Xna.Framework.Color.Brown;
             }
             if (j == 0)
             {
                 num23 -= 2;
             }
             if (j == 1)
             {
                 num23 += 2;
             }
             if (j == 2)
             {
                 num24 -= 2;
             }
             if (j == 3)
             {
                 num24 += 2;
             }
             if (j == 4)
             {
                 color3 = color;
             }
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, textValue, new Vector2((float)num23 + vector.X, (float)num24 + vector.Y), color3, 0f, vector, num18, SpriteEffects.None, 0f);
         }
         if (mouseLeft && mouseLeftRelease)
         {
             if (npcChatFocus1)
             {
                 if (player[myPlayer].BuyItem(num11))
                 {
                     BuyHairWindow();
                     return;
                 }
             }
             else if (npcChatFocus2)
             {
                 CancelHairWindow();
                 return;
             }
         }
         if (!mouseLeft)
         {
             grabColorSlider = 0;
             blockMouse = false;
         }
         int num25 = 167;
         Vector3 vector2 = rgbToHsl(selColor);
         float num26 = vector2.X;
         float num27 = vector2.Y;
         float z = vector2.Z;
         float num28 = (float)(int)selColor.A / 255f;
         if (hBar == -1f || sBar == -1f || lBar == -1f || aBar == -1f)
         {
             hBar = num26;
             sBar = num27;
             lBar = z;
             aBar = (float)(int)selColor.A / 255f;
         }
         else
         {
             num26 = hBar;
             num27 = sBar;
             z = lBar;
             aBar = num28;
         }
         UILinkPointNavigator.SetPosition(2600, new Vector2(num4, num3) + TextureAssets.Hue.Value.Size() / 2f);
         spriteBatch.Draw(TextureAssets.Hue.Value, new Vector2(num4, num3), Microsoft.Xna.Framework.Color.White);
         if ((mouseX > num4 - 4 && mouseX < num4 + TextureAssets.Hue.Width() + 4 && mouseY > num3 - 4 && mouseY < num3 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 1)
         {
             spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num4, num3), OurFavoriteColor);
         }
         spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num4 + (float)(TextureAssets.Hue.Width() - 2) * hBar - (float)(TextureAssets.ColorSlider.Width() / 2), num3 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
         if (((mouseX > num4 - 4 && mouseX < num4 + TextureAssets.Hue.Width() + 4 && mouseY > num3 - 4 && mouseY < num3 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 1) && mouseLeft && !blockMouse)
         {
             grabColorSlider = 1;
             num26 = mouseX - num4;
             num26 /= (float)TextureAssets.Hue.Width();
             if (num26 < 0f)
             {
                 num26 = 0f;
             }
             if (num26 > 1f)
             {
                 num26 = 1f;
             }
             hBar = num26;
         }
         num3 += 26;
         UILinkPointNavigator.SetPosition(2601, new Vector2(num4, num3) + TextureAssets.ColorBar.Value.Size() / 2f);
         spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2(num4, num3), Microsoft.Xna.Framework.Color.White);
         for (int k = 0; k <= num25; k++)
         {
             float saturation = (float)k / (float)num25;
             Microsoft.Xna.Framework.Color color4 = hslToRgb(num26, saturation, z);
             spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2(num4 + k + 5, num3 + 4), color4);
         }
         if ((mouseX > num4 - 4 && mouseX < num4 + TextureAssets.Hue.Width() + 4 && mouseY > num3 - 4 && mouseY < num3 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 2)
         {
             spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num4, num3), OurFavoriteColor);
         }
         spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num4 + (float)(TextureAssets.Hue.Width() - 2) * sBar - (float)(TextureAssets.ColorSlider.Width() / 2), num3 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
         if (((mouseX > num4 - 4 && mouseX < num4 + TextureAssets.Hue.Width() + 4 && mouseY > num3 - 4 && mouseY < num3 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 2) && mouseLeft && !blockMouse)
         {
             grabColorSlider = 2;
             num27 = mouseX - num4;
             num27 /= (float)TextureAssets.Hue.Width();
             if (num27 < 0f)
             {
                 num27 = 0f;
             }
             if (num27 > 1f)
             {
                 num27 = 1f;
             }
             sBar = num27;
         }
         num3 += 26;
         UILinkPointNavigator.SetPosition(2602, new Vector2(num4, num3) + TextureAssets.ColorBar.Value.Size() / 2f);
         spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2(num4, num3), Microsoft.Xna.Framework.Color.White);
         float num29 = 0.15f;
         for (int l = 0; l <= num25; l++)
         {
             float luminosity = (float)l / (float)num25;
             Microsoft.Xna.Framework.Color color5 = hslToRgb(num26, num27, luminosity);
             spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2(num4 + l + 5, num3 + 4), color5);
         }
         if ((mouseX > num4 - 4 && mouseX < num4 + TextureAssets.Hue.Width() + 4 && mouseY > num3 - 4 && mouseY < num3 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 3)
         {
             spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2(num4, num3), OurFavoriteColor);
         }
         spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num4 + (float)(TextureAssets.Hue.Width() - 2) * ((lBar - num29) / (1f - num29)) - (float)(TextureAssets.ColorSlider.Width() / 2), num3 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2), Microsoft.Xna.Framework.Color.White);
         if (((mouseX > num4 - 4 && mouseX < num4 + TextureAssets.Hue.Width() + 4 && mouseY > num3 - 4 && mouseY < num3 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 3) && mouseLeft && !blockMouse)
         {
             grabColorSlider = 3;
             z = mouseX - num4;
             z /= (float)TextureAssets.Hue.Width();
             if (z < 0f)
             {
                 z = 0f;
             }
             if (z > 1f)
             {
                 z = 1f;
             }
             z = z * (1f - num29) + num29;
             lBar = z;
         }
         selColor = hslToRgb(hBar, sBar, lBar);
         player[myPlayer].hairColor = selColor;
         int num30 = num5;
         int num31 = num6;
         _ = hairStart;
         int num32 = 0;
         int num33 = 0;
         for (int m = 0; m < 15; m++)
         {
             int num34 = Hairstyles.AvailableHairstyles[hairStart + m];
             UILinkPointNavigator.SetPosition(2605 + m, new Vector2(num30, num31) + TextureAssets.InventoryBack.Value.Size() * 0.75f);
             if (player[myPlayer].hair == num34)
             {
                 spriteBatch.Draw(TextureAssets.InventoryBack14.Value, new Vector2(num30, num31), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height()), new Microsoft.Xna.Framework.Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
             else
             {
                 spriteBatch.Draw(TextureAssets.InventoryBack8.Value, new Vector2(num30, num31), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height()), new Microsoft.Xna.Framework.Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
             if (mouseX > num30 && mouseX < num30 + TextureAssets.InventoryBack.Width() && mouseY > num31 && mouseY < num31 + TextureAssets.InventoryBack.Height())
             {
                 Asset<Texture2D> val = Assets.Request<Texture2D>("Images/UI/PanelBorder", (AssetRequestMode)1);
                 Utils.DrawSplicedPanel(spriteBatch, val.Value, num30, num31, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height(), val.Width() / 2 - 1, val.Width() / 2 - 1, val.Height() / 2 - 1, val.Height() / 2 - 1, OurFavoriteColor);
                 if (mouseLeft && mouseLeftRelease)
                 {
                     mouseLeftRelease = false;
                     player[myPlayer].hair = num34;
                     SoundEngine.PlaySound(12);
                 }
             }
             LoadHair(num34);
             float x = num30 + TextureAssets.InventoryBack.Width() / 2 - TextureAssets.PlayerHair[num34].Width() / 2;
             float y = num31 + 4;
             spriteBatch.Draw(TextureAssets.Players[num32, 0].Value, new Vector2(x, y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.PlayerHair[num34].Width(), 56), player[myPlayer].skinColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.Players[num32, 1].Value, new Vector2(x, y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.PlayerHair[num34].Width(), 56), new Microsoft.Xna.Framework.Color(255, 255, 255, 255), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.Players[num32, 2].Value, new Vector2(x, y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.PlayerHair[num34].Width(), 56), player[myPlayer].eyeColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             Vector2 vector3 = player[myPlayer].GetHairDrawOffset(num34, hatHair: false) * player[myPlayer].Directions;
             spriteBatch.Draw(TextureAssets.PlayerHair[num34].Value, new Vector2(x, y) + vector3, new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.PlayerHair[num34].Width(), 56), selColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             num33++;
             num30 += 56;
             if (num33 >= 5)
             {
                 num33 = 0;
                 num30 = num5;
                 num31 += 56;
             }
         }
     }
References aBar, Assets, HairstyleUnlocksHelper.AvailableHairstyles, blockMouse, BuyHairWindow(), CancelHairWindow(), chest, TextureAssets.ColorBar, TextureAssets.ColorBlip, TextureAssets.ColorHighlight, TextureAssets.ColorSlider, TextureAssets.CraftUpButton, Player.currentShoppingSettings, Player.Directions, ItemSlot.DrawSavings(), Utils.DrawSplicedPanel(), DynamicSpriteFontExtensionMethods.DrawString(), Player.eyeColor, Player.GetHairDrawOffset(), Language.GetTextValue(), grabColorSlider, Player.hair, Player.hairColor, hairStart, TextureAssets.HairStyleBack, Hairstyles, hBar, hslToRgb(), TextureAssets.Hue, InGuideCraftMenu, Lang.inter, TextureAssets.InventoryBack, TextureAssets.InventoryBack14, TextureAssets.InventoryBack8, lBar, LoadHair(), Player.mouseInterface, mouseLeft, mouseLeftRelease, MouseScreen, FontAssets.MouseText, mouseTextColor, mouseX, mouseY, myPlayer, npcChatFocus1, npcChatFocus2, npcChatText, npcShop, oldHairColor, oldHairStyle, OurFavoriteColor, player, TextureAssets.PlayerHair, playerInventory, TextureAssets.Players, SoundEngine.PlaySound(), ShoppingSettings.PriceAdjustment, Player.releaseUseItem, rgbToHsl(), sBar, screenHeight, screenWidth, TextureAssets.ScrollLeftButton, TextureAssets.ScrollRightButton, PlayerInput.ScrollWheelDelta, selColor, UILinkPointNavigator.SetPosition(), Player.skinColor, spriteBatch, HairstyleUnlocksHelper.UpdateUnlocks(), Asset< T >.Value, and LocalizedText.Value.
Referenced by DrawInterface_21_HairWindow().