Terraria: Main.HoverOverNPCs
HoverOverNPCs()
void Main.HoverOverNPCs (Microsoft.Xna.Framework.Rectangle mouseRectangle) inline private
     {
         Player player = Main.player[myPlayer];
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = npc[i];
             if (!(nPC.active & (nPC.shimmerTransparency == 0f || nPC.CanApplyHunterPotionEffects())))
             {
                 continue;
             }
             int type = nPC.type;
             LoadNPC(type);
             nPC.position += nPC.netOffset;
             Microsoft.Xna.Framework.Rectangle value = new Microsoft.Xna.Framework.Rectangle((int)nPC.Bottom.X - nPC.frame.Width / 2, (int)nPC.Bottom.Y - nPC.frame.Height, nPC.frame.Width, nPC.frame.Height);
             if (nPC.type >= 87 && nPC.type <= 92)
             {
                 value = new Microsoft.Xna.Framework.Rectangle((int)((double)nPC.position.X + (double)nPC.width * 0.5 - 32.0), (int)((double)nPC.position.Y + (double)nPC.height * 0.5 - 32.0), 64, 64);
             }
             bool flag = mouseRectangle.Intersects(value);
             bool flag2 = flag || (SmartInteractShowingGenuine && SmartInteractNPC == i);
             if (flag2 && ((nPC.type != 85 && nPC.type != 341 && nPC.type != 629 && nPC.aiStyle != 87) || nPC.ai[0] != 0f) && nPC.type != 488)
             {
                 if (nPC.type == 685)
                 {
                     player.cursorItemIconEnabled = true;
                     player.cursorItemIconID = 327;
                     player.cursorItemIconText = "";
                     player.noThrow = 2;
                     if (!player.dead)
                     {
                         PlayerInput.SetZoom_MouseInWorld();
                         if (mouseRight && npcChatRelease)
{
                             npcChatRelease = false;
                             if (PlayerInput.UsingGamepad)
{
                                 player.releaseInventory = false;
                             }
                             if (player.talkNPC != i && !player.tileInteractionHappened && TryFreeingElderSlime(i))
{
                                 NPC.TransformElderSlime(i);
                                 SoundEngine.PlaySound(22);
                             }
                         }
                     }
                 }
                 else
                 {
                     bool flag3 = SmartInteractShowingGenuine && SmartInteractNPC == i;
                     if (nPC.townNPC || nPC.type == 105 || nPC.type == 106 || nPC.type == 123 || nPC.type == 354 || nPC.type == 376 || nPC.type == 579 || nPC.type == 453 || nPC.type == 589)
                     {
                         Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle((int)(player.position.X + (float)(player.width / 2) - (float)(Player.tileRangeX * 16)), (int)(player.position.Y + (float)(player.height / 2) - (float)(Player.tileRangeY * 16)), Player.tileRangeX * 16 * 2, Player.tileRangeY * 16 * 2);
                         Microsoft.Xna.Framework.Rectangle value2 = new Microsoft.Xna.Framework.Rectangle((int)nPC.position.X, (int)nPC.position.Y, nPC.width, nPC.height);
                         if (rectangle.Intersects(value2))
{
                             flag3 = true;
                         }
                     }
                     if (player.ownedProjectileCounts[651] > 0)
                     {
                         flag3 = false;
                     }
                     if (flag3 && !player.dead)
                     {
                         PlayerInput.SetZoom_MouseInWorld();
                         HoveringOverAnNPC = true;
                         currentNPCShowingChatBubble = i;
                         if (mouseRight && npcChatRelease)
{
                             npcChatRelease = false;
                             if (PlayerInput.UsingGamepad)
{
                                 player.releaseInventory = false;
                             }
                             if (player.talkNPC != i && !player.tileInteractionHappened)
{
                                 CancelHairWindow();
                                 SetNPCShopIndex(0);
                                 InGuideCraftMenu = false;
                                 player.dropItemCheck();
                                 npcChatCornerItem = 0;
                                 player.sign = -1;
                                 editSign = false;
                                 player.SetTalkNPC(i);
                                 playerInventory = false;
                                 player.chest = -1;
                                 Recipe.FindRecipes();
                                 npcChatText = nPC.GetChat();
                                 SoundEngine.PlaySound(24);
                             }
                         }
                     }
                     if (flag && !player.mouseInterface)
                     {
                         player.cursorItemIconEnabled = false;
                         string text = nPC.GivenOrTypeName;
                         int num = i;
                         if (nPC.realLife >= 0)
{
                             num = nPC.realLife;
                         }
                         if (npc[num].lifeMax > 1 && !npc[num].dontTakeDamage)
{
                             text = text + ": " + npc[num].life + "/" + npc[num].lifeMax;
                         }
                         MouseTextHackZoom(text);
                         mouseText = true;
                         nPC.position -= nPC.netOffset;
                         break;
                     }
                     if (flag2)
                     {
                         nPC.position -= nPC.netOffset;
                         break;
                     }
                 }
             }
             nPC.position -= nPC.netOffset;
         }
     }
References Entity.active, NPC.ai, NPC.aiStyle, Entity.Bottom, NPC.CanApplyHunterPotionEffects(), CancelHairWindow(), Player.chest, currentNPCShowingChatBubble, Player.cursorItemIconEnabled, Player.cursorItemIconID, Player.cursorItemIconText, Player.dead, Player.dropItemCheck(), editSign, Recipe.FindRecipes(), NPC.frame, NPC.GetChat(), NPC.GivenOrTypeName, Entity.height, HoveringOverAnNPC, InGuideCraftMenu, NPC.life, NPC.lifeMax, LoadNPC(), Player.mouseInterface, mouseRight, mouseText, MouseTextHackZoom(), myPlayer, NPC.netOffset, Player.noThrow, npc, npcChatCornerItem, npcChatRelease, npcChatText, Player.ownedProjectileCounts, player, playerInventory, SoundEngine.PlaySound(), Entity.position, NPC.realLife, Player.releaseInventory, SetNPCShopIndex(), Player.SetTalkNPC(), PlayerInput.SetZoom_MouseInWorld(), NPC.shimmerTransparency, Player.sign, SmartInteractNPC, SmartInteractShowingGenuine, Player.talkNPC, Player.tileInteractionHappened, Player.tileRangeX, Player.tileRangeY, NPC.townNPC, NPC.TransformElderSlime(), TryFreeingElderSlime(), NPC.type, PlayerInput.UsingGamepad, and Entity.width.
Referenced by DrawMouseOver().