Terraria: Main.UpdateDisplaySettings
UpdateDisplaySettings()
void Main.UpdateDisplaySettings () inline
     {
         if (startFullscreen)
         {
             FullscreenStartup();
         }
         SetResolution(base.GraphicsDevice.Viewport.Width, base.GraphicsDevice.Viewport.Height);
     }
References FullscreenStartup(), SetResolution(), and startFullscreen.
Referenced by ClientInitialize(), DoDraw(), and InitTargets().