Terraria: Main.DrawProj_TrueNightsEdge
DrawProj_TrueNightsEdge()
void Main.DrawProj_TrueNightsEdge (Projectile proj) inline private
     {
         Asset<Texture2D> val = TextureAssets.Projectile[proj.type];
         Microsoft.Xna.Framework.Rectangle rectangle = val.Frame(1, 4);
         Vector2 origin = rectangle.Size() / 2f;
         float num = proj.scale * 1.1f;
         SpriteEffects effects = ((!(proj.ai[0] >= 0f)) ? SpriteEffects.FlipVertically : SpriteEffects.None);
         float num2 = 0.975f;
         float fromValue = Lighting.GetColor(proj.Center.ToTileCoordinates()).ToVector3().Length() / (float)Math.Sqrt(3.0);
         fromValue = Utils.Remap(fromValue, 0.2f, 1f, 0f, 1f);
         float num3 = MathHelper.Min(0.15f + fromValue * 0.85f, Utils.Remap(proj.localAI[0], 30f, 96f, 1f, 0f));
         _ = proj.Size / 2f;
         float num4 = 2f;
         for (float num5 = num4; num5 >= 0f; num5 -= 1f)
         {
             if (!(proj.oldPos[(int)num5] == Vector2.Zero))
             {
                 Vector2 vector = proj.Center - proj.velocity * 0.5f * num5;
                 float num6 = proj.oldRot[(int)num5] + proj.ai[0] * ((float)Math.PI * 2f) * 0.1f * (0f - num5);
                 Vector2 position = vector - screenPosition;
                 float num7 = 1f - num5 / num4;
                 float num8 = proj.Opacity * num7 * num7 * 0.85f;
                 float amount = proj.Opacity * proj.Opacity;
                 Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(40, 20, 60, 120), new Microsoft.Xna.Framework.Color(80, 160, 50, 120), amount);
                 spriteBatch.Draw(val.Value, position, rectangle, color * num3 * num8, num6 + proj.ai[0] * ((float)Math.PI / 4f) * -1f, origin, num * num2, effects, 0f);
                 Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(80, 40, 180), new Microsoft.Xna.Framework.Color(155, 255, 100), amount);
                 Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.White * num8 * 0.5f;
                 color3.A = (byte)((float)(int)color3.A * (1f - num3));
                 Microsoft.Xna.Framework.Color color4 = color3 * num3 * 0.5f;
                 color4.G = (byte)((float)(int)color4.G * num3);
                 color4.R = (byte)((float)(int)color4.R * (0.25f + num3 * 0.75f));
                 float num9 = 3f;
                 for (float num10 = (float)Math.PI * -2f + (float)Math.PI * 2f / num9; num10 < 0f; num10 += (float)Math.PI * 2f / num9)
                 {
                     float num11 = Utils.Remap(num10, (float)Math.PI * -2f, 0f, 0f, 0.5f);
                     spriteBatch.Draw(val.Value, position, rectangle, color4 * 0.15f * num11, num6 + proj.ai[0] * 0.01f + num10, origin, num, effects, 0f);
                     spriteBatch.Draw(val.Value, position, rectangle, Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(80, 30, 160), new Microsoft.Xna.Framework.Color(200, 255, 0), amount) * fromValue * num8 * num11, num6 + num10, origin, num * 0.8f, effects, 0f);
                     spriteBatch.Draw(val.Value, position, rectangle, color2 * fromValue * num8 * MathHelper.Lerp(0.05f, 0.4f, fromValue) * num11, num6 + num10, origin, num * num2, effects, 0f);
                     spriteBatch.Draw(val.Value, position, val.Frame(1, 4, 0, 3), Microsoft.Xna.Framework.Color.White * MathHelper.Lerp(0.05f, 0.5f, fromValue) * num8 * num11, num6 + num10, origin, num, effects, 0f);
                 }
                 spriteBatch.Draw(val.Value, position, rectangle, color4 * 0.15f, num6 + proj.ai[0] * 0.01f, origin, num, effects, 0f);
                 spriteBatch.Draw(val.Value, position, rectangle, Microsoft.Xna.Framework.Color.Lerp(new Microsoft.Xna.Framework.Color(80, 30, 160), new Microsoft.Xna.Framework.Color(200, 255, 0), amount) * num3 * num8, num6, origin, num * 0.8f, effects, 0f);
                 spriteBatch.Draw(val.Value, position, rectangle, color2 * fromValue * num8 * MathHelper.Lerp(0.05f, 0.4f, num3), num6, origin, num * num2, effects, 0f);
                 spriteBatch.Draw(val.Value, position, val.Frame(1, 4, 0, 3), Microsoft.Xna.Framework.Color.White * MathHelper.Lerp(0.05f, 0.5f, num3) * num8, num6, origin, num, effects, 0f);
             }
         }
         float num12 = 1f - proj.localAI[0] * 1f / 80f;
         if (num12 < 0.5f)
         {
             num12 = 0.5f;
         }
         Vector2 drawpos = proj.Center - screenPosition + (proj.rotation + 0.47123894f * proj.ai[0]).ToRotationVector2() * ((float)val.Width() * 0.5f - 4f) * num * num12;
         float num13 = MathHelper.Min(num3, MathHelper.Lerp(1f, fromValue, Utils.Remap(proj.localAI[0], 0f, 80f, 0f, 1f)));
         DrawPrettyStarSparkle(proj.Opacity, SpriteEffects.None, drawpos, new Microsoft.Xna.Framework.Color(255, 255, 255, 0) * proj.Opacity * 0.5f * num13, new Microsoft.Xna.Framework.Color(150, 255, 100) * num13, proj.Opacity, 0f, 1f, 1f, 2f, (float)Math.PI / 4f, new Vector2(2f, 2f), Vector2.One);
     }
References Projectile.ai, Entity.Center, DrawPrettyStarSparkle(), Lighting.GetColor(), Projectile.localAI, Projectile.oldPos, Projectile.oldRot, Projectile.Opacity, TextureAssets.Projectile, Utils.Remap(), Projectile.rotation, Projectile.scale, screenPosition, Entity.Size, spriteBatch, Projectile.type, Asset< T >.Value, and Entity.velocity.
Referenced by DrawProjDirect().