Terraria: Main.OpenPlayerSelect
OpenPlayerSelect()
static void Main.OpenPlayerSelect (OnPlayerSelected method) inline static
     {
         if ((gameMenu && (menuMode == 10 || menuMode == 14)) || WorldGen.gen)
         {
             return;
         }
         if (!gameMenu)
         {
             WorldGen.SaveAndQuit(delegate
             {
                 menuMode = 888;
                 _blockFancyUIWhileLoading = true;
                 LoadPlayers();
                 MenuUI.SetState(_characterSelectMenu);
                 _blockFancyUIWhileLoading = false;
                 _pendingCharacterSelect = method;
             });
         }
         else
         {
             menuMode = 888;
             _blockFancyUIWhileLoading = true;
             LoadPlayers();
             MenuUI.SetState(_characterSelectMenu);
             _blockFancyUIWhileLoading = false;
             _pendingCharacterSelect = method;
         }
     }
References _blockFancyUIWhileLoading, _characterSelectMenu, _pendingCharacterSelect, gameMenu, WorldGen.gen, LoadPlayers(), menuMode, MenuUI, WorldGen.SaveAndQuit(), and UserInterface.SetState().
Referenced by NetClientSocialModule.CheckParameters(), NetClientSocialModule.ConnectToLobby(), NetClientSocialModule.OnLobbyJoinRequest(), and NetClientSocialModule.OnRailRespondInvation().