Terraria: Main.DrawInterface_30_Hotbar
DrawInterface_30_Hotbar()
void Main.DrawInterface_30_Hotbar () inline private
     {
         try
         {
             GUIHotbarDrawInner();
         }
         catch (Exception e)
         {
             if (ignoreErrors)
             {
                 TimeLogger.DrawException(e);
                 return;
             }
             throw;
         }
     }
References TimeLogger.DrawException(), GUIHotbarDrawInner(), and ignoreErrors.
Referenced by SetupDrawInterfaceLayers().