Terraria: Main.DrawProj_LightsBane
DrawProj_LightsBane()
void Main.DrawProj_LightsBane (Projectile proj) inline private
     {
         spriteBatch.End();
         if (_multiplyBlendState == null)
         {
             _ = BlendState.AlphaBlend;
             _ = BlendState.Additive;
             _multiplyBlendState = new BlendState
             {
                 ColorBlendFunction = BlendFunction.ReverseSubtract,
                 ColorDestinationBlend = Blend.One,
                 ColorSourceBlend = Blend.SourceAlpha,
                 AlphaBlendFunction = BlendFunction.ReverseSubtract,
                 AlphaDestinationBlend = Blend.One,
                 AlphaSourceBlend = Blend.SourceAlpha
             };
         }
         BlendState multiplyBlendState = _multiplyBlendState;
         spriteBatch.Begin(SpriteSortMode.Deferred, multiplyBlendState, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         Vector2 position = proj.Center - screenPosition;
         LoadProjectile(proj.type);
         Asset<Texture2D> val = TextureAssets.Projectile[proj.type];
         Microsoft.Xna.Framework.Rectangle rectangle = val.Frame(1, 13, 0, proj.frame);
         Vector2 vector = rectangle.Size() / 2f;
         Vector2 vector2 = new Vector2(0.7f, 0.7f) * proj.scale;
         float num = Utils.Remap(proj.frame, 0f, 3f, 0f, 1f) * Utils.Remap(proj.frame, 4f, 12f, 1f, 0f);
         Microsoft.Xna.Framework.Rectangle value = val.Frame(1, 13, 0, 12);
         Vector2 origin = vector + new Vector2(0f, 0f);
         spriteBatch.Draw(val.Value, position, value, Microsoft.Xna.Framework.Color.White * 0.3f * num, proj.rotation, origin, new Vector2(1f, 6f) * vector2, SpriteEffects.None, 0f);
         spriteBatch.Draw(val.Value, position, value, Microsoft.Xna.Framework.Color.White * 0.3f * num, proj.rotation, origin, new Vector2(2f, 2f) * vector2, SpriteEffects.None, 0f);
         spriteBatch.Draw(val.Value, position, rectangle, Microsoft.Xna.Framework.Color.White, proj.rotation, vector, vector2, SpriteEffects.None, 0f);
         spriteBatch.Draw(val.Value, position, rectangle, Microsoft.Xna.Framework.Color.White, proj.rotation, vector, vector2, SpriteEffects.None, 0f);
         spriteBatch.Draw(val.Value, position, rectangle, Microsoft.Xna.Framework.Color.White, proj.rotation, vector, vector2, SpriteEffects.None, 0f);
         spriteBatch.Draw(val.Value, position, rectangle, Microsoft.Xna.Framework.Color.White, proj.rotation, vector, vector2, SpriteEffects.None, 0f);
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.Additive, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         spriteBatch.Draw(val.Value, position, rectangle, Microsoft.Xna.Framework.Color.Magenta, proj.rotation, vector, vector2, SpriteEffects.None, 0f);
         spriteBatch.Draw(val.Value, position, rectangle, Microsoft.Xna.Framework.Color.Magenta, proj.rotation, vector, vector2, SpriteEffects.None, 0f);
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
     }
References _multiplyBlendState, Entity.Center, DefaultSamplerState, Projectile.frame, LoadProjectile(), TextureAssets.Projectile, Rasterizer, Utils.Remap(), Projectile.rotation, Projectile.scale, screenPosition, spriteBatch, Transform, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().