Terraria: Main.DrawInterface_33_MouseText
DrawInterface_33_MouseText()
void Main.DrawInterface_33_MouseText () inline private
     {
         if (mouseItem.stack <= 0)
         {
             mouseItem.type = 0;
         }
         if (hoverItemName != null && hoverItemName != "" && mouseItem.type == 0)
         {
             player[myPlayer].cursorItemIconEnabled = false;
             if (SettingsEnabled_OpaqueBoxBehindTooltips)
             {
                 MouseText(hoverItemName, rare, 0, mouseX + 6, mouseY + 6);
             }
             else
             {
                 MouseText(hoverItemName, rare, 0);
             }
             mouseText = true;
         }
         if (LocalPlayer.rulerLine && LocalPlayer.builderAccStatus[0] == 0 && LocalPlayer.velocity.Length() <= 6f)
         {
             int num = Math.Abs(rulerLineDisplayValues.X) + 1;
             int num2 = Math.Abs(rulerLineDisplayValues.Y) + 1;
             if (num > 1 || num2 > 1)
             {
                 Utils.DrawBorderString(spriteBatch, num + "x" + num2, MouseScreen + new Vector2(16f, 0f), new Microsoft.Xna.Framework.Color(0.24f, 0.8f, 0.9f, 1f), GameZoomTarget, 0f, 0.8f);
             }
         }
         DrawInterface_InstrumentMouseText();
     }
References Player.builderAccStatus, Player.cursorItemIconEnabled, Utils.DrawBorderString(), DrawInterface_InstrumentMouseText(), GameZoomTarget, hoverItemName, LocalPlayer, mouseItem, MouseScreen, mouseText, MouseText(), mouseX, mouseY, myPlayer, player, rare, Player.rulerLine, rulerLineDisplayValues, SettingsEnabled_OpaqueBoxBehindTooltips, spriteBatch, Item.stack, Item.type, and Entity.velocity.
Referenced by SetupDrawInterfaceLayers().