Terraria: Main.DrawBackGore
DrawBackGore()
void Main.DrawBackGore () inline private
     {
         if (!drawBackGore)
         {
             return;
         }
         drawBackGore = false;
         if (ignoreErrors)
         {
             try
             {
                 DrawGoreBehind();
                 return;
             }
             catch (Exception e)
             {
                 TimeLogger.DrawException(e);
                 return;
             }
         }
         DrawGoreBehind();
     }
References drawBackGore, TimeLogger.DrawException(), DrawGoreBehind(), and ignoreErrors.
Referenced by DoDraw_WallsTilesNPCs().