Terraria: Main.MouseText_DrawItemTooltip
MouseText_DrawItemTooltip()
void Main.MouseText_DrawItemTooltip (MouseTextCache info, int rare, byte diff, int X, int Y) inline private
     {
         bool settingsEnabled_OpaqueBoxBehindTooltips = SettingsEnabled_OpaqueBoxBehindTooltips;
         Microsoft.Xna.Framework.Color color = new Microsoft.Xna.Framework.Color(mouseTextColor, mouseTextColor, mouseTextColor, mouseTextColor);
         Item hoverItem = HoverItem;
         int yoyoLogo = -1;
         int researchLine = -1;
         rare = hoverItem.rare;
         float knockBack = hoverItem.knockBack;
         float num = 1f;
         if (hoverItem.melee && player[myPlayer].kbGlove)
         {
             num += 1f;
         }
         if (player[myPlayer].kbBuff)
         {
             num += 0.5f;
         }
         if (num != 1f)
         {
             hoverItem.knockBack *= num;
         }
         if (hoverItem.ranged && player[myPlayer].shroomiteStealth)
         {
             hoverItem.knockBack *= 1f + (1f - player[myPlayer].stealth) * 0.5f;
         }
         int num2 = 30;
         int numLines = 1;
         string[] array = new string[num2];
         bool[] array2 = new bool[num2];
         bool[] array3 = new bool[num2];
         for (int i = 0; i < num2; i++)
         {
             array2[i] = false;
             array3[i] = false;
         }
         MouseText_DrawItemTooltip_GetLinesInfo(hoverItem, ref yoyoLogo, ref researchLine, knockBack, ref numLines, array, array2, array3);
         float num3 = (float)(int)mouseTextColor / 255f;
         float num4 = num3;
         int a = mouseTextColor;
         if (npcShop > 0 && hoverItem.value >= 0 && (hoverItem.type < 71 || hoverItem.type > 74))
         {
             LocalPlayer.GetItemExpectedPrice(hoverItem, out var calcForSelling, out var calcForBuying);
             long num5 = ((hoverItem.isAShopItem || hoverItem.buyOnce) ? calcForBuying : calcForSelling);
             if (hoverItem.shopSpecialCurrency != -1)
             {
                 CustomCurrencyManager.GetPriceText(hoverItem.shopSpecialCurrency, array, ref numLines, num5);
                 color = new Microsoft.Xna.Framework.Color((byte)(255f * num4), (byte)(255f * num4), (byte)(255f * num4), a);
             }
             else if (num5 > 0)
             {
                 string text = "";
                 long num6 = 0L;
                 long num7 = 0L;
                 long num8 = 0L;
                 long num9 = 0L;
                 long num10 = num5 * hoverItem.stack;
                 if (!hoverItem.buy)
                 {
                     num10 = num5 / 5;
                     if (num10 < 1)
                     {
                         num10 = 1L;
                     }
                     long num11 = num10;
                     num10 *= hoverItem.stack;
                     int amount = shopSellbackHelper.GetAmount(hoverItem);
                     if (amount > 0)
                     {
                         num10 += (-num11 + calcForBuying) * Math.Min(amount, hoverItem.stack);
                     }
                 }
                 if (num10 < 1)
                 {
                     num10 = 1L;
                 }
                 if (num10 >= 1000000)
                 {
                     num6 = num10 / 1000000;
                     num10 -= num6 * 1000000;
                 }
                 if (num10 >= 10000)
                 {
                     num7 = num10 / 10000;
                     num10 -= num7 * 10000;
                 }
                 if (num10 >= 100)
                 {
                     num8 = num10 / 100;
                     num10 -= num8 * 100;
                 }
                 if (num10 >= 1)
                 {
                     num9 = num10;
                 }
                 if (num6 > 0)
                 {
                     text = text + num6 + " " + Lang.inter[15].Value + " ";
                 }
                 if (num7 > 0)
                 {
                     text = text + num7 + " " + Lang.inter[16].Value + " ";
                 }
                 if (num8 > 0)
                 {
                     text = text + num8 + " " + Lang.inter[17].Value + " ";
                 }
                 if (num9 > 0)
                 {
                     text = text + num9 + " " + Lang.inter[18].Value + " ";
                 }
                 if (!hoverItem.buy)
                 {
                     array[numLines] = Lang.tip[49].Value + " " + text;
                 }
                 else
                 {
                     array[numLines] = Lang.tip[50].Value + " " + text;
                 }
                 numLines++;
                 if (num6 > 0)
                 {
                     color = new Microsoft.Xna.Framework.Color((byte)(220f * num4), (byte)(220f * num4), (byte)(198f * num4), a);
                 }
                 else if (num7 > 0)
                 {
                     color = new Microsoft.Xna.Framework.Color((byte)(224f * num4), (byte)(201f * num4), (byte)(92f * num4), a);
                 }
                 else if (num8 > 0)
                 {
                     color = new Microsoft.Xna.Framework.Color((byte)(181f * num4), (byte)(192f * num4), (byte)(193f * num4), a);
                 }
                 else if (num9 > 0)
                 {
                     color = new Microsoft.Xna.Framework.Color((byte)(246f * num4), (byte)(138f * num4), (byte)(96f * num4), a);
                 }
             }
             else if (hoverItem.type != 3817)
             {
                 array[numLines] = Lang.tip[51].Value;
                 numLines++;
                 color = new Microsoft.Xna.Framework.Color((byte)(120f * num4), (byte)(120f * num4), (byte)(120f * num4), a);
             }
         }
         Vector2 zero = Vector2.Zero;
         int num12 = 0;
         for (int j = 0; j < numLines; j++)
         {
             Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, array[j], Vector2.One);
             if (stringSize.X > zero.X)
             {
                 zero.X = stringSize.X;
             }
             zero.Y += stringSize.Y + (float)num12;
         }
         if (yoyoLogo != -1)
         {
             zero.Y += 24f;
         }
         X += toolTipDistance;
         Y += toolTipDistance;
         int num13 = 4;
         if (settingsEnabled_OpaqueBoxBehindTooltips)
         {
             X += 8;
             Y += 2;
             num13 = 18;
         }
         int num14 = screenWidth;
         int num15 = screenHeight;
         if ((float)X + zero.X + (float)num13 > (float)num14)
         {
             X = (int)((float)num14 - zero.X - (float)num13);
         }
         if ((float)Y + zero.Y + (float)num13 > (float)num15)
         {
             Y = (int)((float)num15 - zero.Y - (float)num13);
         }
         int num16 = 0;
         num3 = (float)(int)mouseTextColor / 255f;
         if (settingsEnabled_OpaqueBoxBehindTooltips)
         {
             num3 = MathHelper.Lerp(num3, 1f, 1f);
             int num17 = 14;
             int num18 = 9;
             Utils.DrawInvBG(spriteBatch, new Microsoft.Xna.Framework.Rectangle(X - num17, Y - num18, (int)zero.X + num17 * 2, (int)zero.Y + num18 + num18 / 2), new Microsoft.Xna.Framework.Color(23, 25, 81, 255) * 0.925f);
         }
         for (int k = 0; k < numLines; k++)
         {
             if (k == yoyoLogo)
             {
                 float num19 = 1f;
                 int num20 = (int)((float)(int)mouseTextColor * num19);
                 Microsoft.Xna.Framework.Color color2 = Microsoft.Xna.Framework.Color.Black;
                 for (int l = 0; l < 5; l++)
                 {
                     int num21 = X;
                     int num22 = Y + num16;
                     if (l == 4)
                     {
                         color2 = new Microsoft.Xna.Framework.Color(num20, num20, num20, num20);
                     }
                     switch (l)
                     {
                     case 0:
                         num21--;
                         break;
                     case 1:
                         num21++;
                         break;
                     case 2:
                         num22--;
                         break;
                     case 3:
                         num22++;
                         break;
                     }
                     spriteBatch.Draw(TextureAssets.OneDropLogo.Value, new Vector2(num21, num22), null, color2, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                 }
             }
             else
             {
                 Microsoft.Xna.Framework.Color black = Microsoft.Xna.Framework.Color.Black;
                 black = new Microsoft.Xna.Framework.Color(num4, num4, num4, num4);
                 if (k == 0)
                 {
                     if (rare == -13)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(255f * num4), (byte)(masterColor * 200f * num4), 0, a);
                     }
                     if (rare == -11)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(255f * num4), (byte)(175f * num4), (byte)(0f * num4), a);
                     }
                     if (rare == -1)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(130f * num4), (byte)(130f * num4), (byte)(130f * num4), a);
                     }
                     if (rare == 1)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(150f * num4), (byte)(150f * num4), (byte)(255f * num4), a);
                     }
                     if (rare == 2)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(150f * num4), (byte)(255f * num4), (byte)(150f * num4), a);
                     }
                     if (rare == 3)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(255f * num4), (byte)(200f * num4), (byte)(150f * num4), a);
                     }
                     if (rare == 4)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(255f * num4), (byte)(150f * num4), (byte)(150f * num4), a);
                     }
                     if (rare == 5)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(255f * num4), (byte)(150f * num4), (byte)(255f * num4), a);
                     }
                     if (rare == 6)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(210f * num4), (byte)(160f * num4), (byte)(255f * num4), a);
                     }
                     if (rare == 7)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(150f * num4), (byte)(255f * num4), (byte)(10f * num4), a);
                     }
                     if (rare == 8)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(255f * num4), (byte)(255f * num4), (byte)(10f * num4), a);
                     }
                     if (rare == 9)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(5f * num4), (byte)(200f * num4), (byte)(255f * num4), a);
                     }
                     if (rare == 10)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(255f * num4), (byte)(40f * num4), (byte)(100f * num4), a);
                     }
                     if (rare >= 11)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)(180f * num4), (byte)(40f * num4), (byte)(255f * num4), a);
                     }
                     if (diff == 1)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)((float)(int)mcColor.R * num4), (byte)((float)(int)mcColor.G * num4), (byte)((float)(int)mcColor.B * num4), a);
                     }
                     if (diff == 2)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)((float)(int)hcColor.R * num4), (byte)((float)(int)hcColor.G * num4), (byte)((float)(int)hcColor.B * num4), a);
                     }
                     if (hoverItem.expert || rare == -12)
                     {
                         black = new Microsoft.Xna.Framework.Color((byte)((float)DiscoR * num4), (byte)((float)DiscoG * num4), (byte)((float)DiscoB * num4), a);
                     }
                 }
                 else if (array2[k])
                 {
                     black = ((!array3[k]) ? new Microsoft.Xna.Framework.Color((byte)(120f * num4), (byte)(190f * num4), (byte)(120f * num4), a) : new Microsoft.Xna.Framework.Color((byte)(190f * num4), (byte)(120f * num4), (byte)(120f * num4), a));
                 }
                 else if (k == numLines - 1)
                 {
                     black = color;
                 }
                 if (k == researchLine)
                 {
                     black = Colors.JourneyMode;
                 }
                 ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, array[k], new Vector2(X, Y + num16), black, 0f, Vector2.Zero, Vector2.One);
             }
             num16 += (int)(FontAssets.MouseText.Value.MeasureString(array[k]).Y + (float)num12);
         }
     }
References Item.buy, Item.buyOnce, DiscoB, DiscoG, DiscoR, ChatManager.DrawColorCodedStringWithShadow(), Utils.DrawInvBG(), Item.expert, ItemShopSellbackHelper.GetAmount(), Player.GetItemExpectedPrice(), CustomCurrencyManager.GetPriceText(), ChatManager.GetStringSize(), hcColor, HoverItem, Lang.inter, Item.isAShopItem, Colors.JourneyMode, Player.kbGlove, Item.knockBack, L, LocalPlayer, masterColor, mcColor, Item.melee, FontAssets.MouseText, MouseText_DrawItemTooltip_GetLinesInfo(), mouseTextColor, myPlayer, npcShop, TextureAssets.OneDropLogo, player, Item.ranged, Item.rare, rare, screenHeight, screenWidth, SettingsEnabled_OpaqueBoxBehindTooltips, shopSellbackHelper, Item.shopSpecialCurrency, Player.shroomiteStealth, spriteBatch, Item.stack, Player.stealth, Lang.tip, toolTipDistance, Item.type, Asset< T >.Value, LocalizedText.Value, Item.value, X, and Y.
Referenced by MouseTextInner().