Terraria: Main.DoDraw_WallsTilesNPCs
DoDraw_WallsTilesNPCs()
void Main.DoDraw_WallsTilesNPCs () inline private
     {
         try
         {
             CacheNPCDraws();
             CacheProjDraws();
             DrawCachedNPCs(DrawCacheNPCsMoonMoon, behindTiles: true);
             DoDraw_WallsAndBlacks();
             DrawWoF();
             DrawBackGore();
             MoonlordDeathDrama.DrawPieces(spriteBatch);
             MoonlordDeathDrama.DrawExplosions(spriteBatch);
             DrawCachedNPCs(DrawCacheNPCsBehindNonSolidTiles, behindTiles: true);
             DoDraw_Tiles_NonSolid();
             tileBatch.Begin(Rasterizer, Transform);
             DoDraw_Waterfalls();
             tileBatch.End();
         }
         catch (Exception e)
         {
             TimeLogger.DrawException(e);
         }
         spriteBatch.End();
         try
         {
             bool detectCreature = player[myPlayer].detectCreature;
             if (!detectCreature)
             {
                 DoDraw_DrawNPCsBehindTiles();
             }
             DoDraw_Tiles_Solid();
             if (detectCreature)
             {
                 DoDraw_DrawNPCsBehindTiles();
             }
             DrawPlayers_BehindNPCs();
             DoDraw_DrawNPCsOverTiles();
             TimeLogger.DetailedDrawReset();
         }
         catch (Exception e2)
         {
             TimeLogger.DrawException(e2);
         }
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
     }
References TileBatch.Begin(), CacheNPCDraws(), CacheProjDraws(), DefaultSamplerState, TimeLogger.DetailedDrawReset(), Player.detectCreature, DoDraw_DrawNPCsBehindTiles(), DoDraw_DrawNPCsOverTiles(), DoDraw_Tiles_NonSolid(), DoDraw_Tiles_Solid(), DoDraw_WallsAndBlacks(), DoDraw_Waterfalls(), DrawBackGore(), DrawCachedNPCs(), DrawCacheNPCsBehindNonSolidTiles, DrawCacheNPCsMoonMoon, TimeLogger.DrawException(), MoonlordDeathDrama.DrawExplosions(), MoonlordDeathDrama.DrawPieces(), DrawPlayers_BehindNPCs(), DrawWoF(), TileBatch.End(), myPlayer, player, Rasterizer, spriteBatch, tileBatch, and Transform.
Referenced by DoDraw().