Terraria: Main.QuitGame
QuitGame()
void Main.QuitGame () inline protected
     {
         SaveSettings();
         if (!dedServ)
         {
             SocialAPI.Shutdown();
         }
         Assets.TransferCompletedAssets();
         Exit();
     }
References Assets, dedServ, Game.Exit(), SaveSettings(), SocialAPI.Shutdown(), and IAssetRepository.TransferCompletedAssets().
Referenced by Update().