Terraria: Main.TryAllowingToCraftRecipe
TryAllowingToCraftRecipe()
static bool Main.TryAllowingToCraftRecipe (Recipe currentRecipe, bool tryFittingItemInInventoryToAllowCrafting, out bool movedAnItemToAllowCrafting) inline static private
     {
         movedAnItemToAllowCrafting = false;
         if (mouseItem.IsAir)
         {
             return true;
         }
         if (mouseItem.IsTheSameAs(currentRecipe.createItem) && mouseItem.stack + currentRecipe.createItem.stack <= mouseItem.maxStack)
         {
             return true;
         }
         if (tryFittingItemInInventoryToAllowCrafting && LocalPlayer.ItemSpace(mouseItem).CanTakeItemToPersonalInventory)
         {
             mouseItem = LocalPlayer.GetItem(myPlayer, mouseItem, GetItemSettings.InventoryUIToInventorySettingsShowAsNew);
             if (mouseItem.IsAir)
             {
                 movedAnItemToAllowCrafting = true;
                 return true;
             }
             if (mouseItem.IsTheSameAs(currentRecipe.createItem) && mouseItem.stack + currentRecipe.createItem.stack <= mouseItem.maxStack)
             {
                 movedAnItemToAllowCrafting = true;
                 return true;
             }
         }
         return false;
     }
References Player.ItemSpaceStatus.CanTakeItemToPersonalInventory, Recipe.createItem, Player.GetItem(), GetItemSettings.InventoryUIToInventorySettingsShowAsNew, Item.IsAir, Item.IsTheSameAs(), Player.ItemSpace(), LocalPlayer, Item.maxStack, mouseItem, myPlayer, and Item.stack.
Referenced by HoverOverCraftingItemButton().