Terraria: Main.HoverOverCraftingItemButton
HoverOverCraftingItemButton()
static void Main.HoverOverCraftingItemButton (int recipeIndex) inline static private
     {
         Recipe recipe = Main.recipe[availableRecipe[recipeIndex]];
         player[myPlayer].mouseInterface = true;
         bool flag = (mouseLeftRelease && mouseLeft) || (mouseRightRelease && mouseRight);
         bool flag2 = mouseLeft || mouseRight;
         if (focusRecipe == recipeIndex && guideItem.IsAir)
         {
             bool flag3 = LocalPlayer.ItemTimeIsZero && LocalPlayer.itemAnimation == 0 && !player[myPlayer].HasLockedInventory() && !_preventCraftingBecauseClickWasUsedToChangeFocusedRecipe;
             bool num = _currentRecipeBeingCrafted != -1 && _currentRecipeBeingCrafted != availableRecipe[recipeIndex];
             bool flag4 = _currentRecipeBeingCrafted != -1 && Main.recipe[_currentRecipeBeingCrafted].createItem.maxStack == 1;
             bool flag5 = num || flag4;
             if (flag2 && !flag5 && flag3 && stackSplit <= 1)
             {
                 bool usingGamepad = PlayerInput.UsingGamepad;
                 bool movedAnItemToAllowCrafting;
                 bool num2 = TryAllowingToCraftRecipe(recipe, usingGamepad, out movedAnItemToAllowCrafting);
                 if (movedAnItemToAllowCrafting)
                 {
                     _preventCraftingBecauseClickWasUsedToChangeFocusedRecipe = true;
                 }
                 if (num2 && !movedAnItemToAllowCrafting)
                 {
                     if (_currentRecipeBeingCrafted == -1)
                     {
                         _currentRecipeBeingCrafted = availableRecipe[recipeIndex];
                     }
                     ItemSlot.RefreshStackSplitCooldown();
                     CraftItem(recipe);
                 }
             }
         }
         else if (flag)
         {
             focusRecipe = recipeIndex;
             stackSplit = 15;
             _preventCraftingBecauseClickWasUsedToChangeFocusedRecipe = true;
         }
         craftingHide = true;
         HoverItem = recipe.createItem.Clone();
         ItemSlot.MouseHover(22);
         hoverItemName = recipe.createItem.Name;
         if (recipe.createItem.stack > 1)
         {
             hoverItemName = hoverItemName + " (" + recipe.createItem.stack + ")";
         }
         if (!flag2)
         {
             _preventCraftingBecauseClickWasUsedToChangeFocusedRecipe = false;
             _currentRecipeBeingCrafted = -1;
         }
     }
References _currentRecipeBeingCrafted, _preventCraftingBecauseClickWasUsedToChangeFocusedRecipe, availableRecipe, Item.Clone(), craftingHide, CraftItem(), Recipe.createItem, focusRecipe, guideItem, Player.HasLockedInventory(), HoverItem, hoverItemName, Item.IsAir, Player.itemAnimation, Player.ItemTimeIsZero, LocalPlayer, Item.maxStack, ItemSlot.MouseHover(), Player.mouseInterface, mouseLeft, mouseLeftRelease, mouseRight, mouseRightRelease, myPlayer, Item.Name, player, recipe, ItemSlot.RefreshStackSplitCooldown(), Item.stack, stackSplit, TryAllowingToCraftRecipe(), and PlayerInput.UsingGamepad.
Referenced by DrawInventory().