Terraria: Main.LoadPlayers
LoadPlayers()
static void Main.LoadPlayers () inline static
     {
         PlayerList.Clear();
         if (!Utils.TryCreatingDirectory(PlayerPath))
         {
             return;
         }
         string[] files = Directory.GetFiles(PlayerPath, "*.plr");
         int num = Math.Min(maxLoadPlayer, files.Length);
         for (int i = 0; i < num; i++)
         {
             PlayerFileData fileData = Player.GetFileData(files[i], cloudSave: false);
             if (fileData != null)
             {
                 PlayerList.Add(fileData);
             }
         }
         if (SocialAPI.Cloud != null)
         {
             foreach (string item in from path in SocialAPI.Cloud.GetFiles()
                 where path.StartsWith(CloudPlayerPath, StringComparison.CurrentCultureIgnoreCase) && path.EndsWith(".plr", StringComparison.CurrentCultureIgnoreCase)
                 select path)
             {
                 PlayerFileData fileData2 = Player.GetFileData(item, cloudSave: true);
                 if (fileData2 != null)
                 {
                     PlayerList.Add(fileData2);
                 }
             }
         }
         PlayerList.Sort(PlayerListSortMethod);
     }
References SocialAPI.Cloud, CloudPlayerPath, Player.GetFileData(), CloudSocialModule.GetFiles(), item, maxLoadPlayer, PlayerList, PlayerListSortMethod(), PlayerPath, and Utils.TryCreatingDirectory().
Referenced by ClientInitialize(), DrawMenu(), ErasePlayer(), UICharacterCreation.FinishCreatingCharacter(), Initialize_AlmostEverything(), UICharacterSelect.OnActivate(), OnCharacterNamed(), and OpenPlayerSelect().