Terraria: Main.EraseWorld
EraseWorld()
static void Main.EraseWorld (int i) inline static private
     {
         try
         {
             if (!WorldList[i].IsCloudSave)
             {
                 Platform.Get<IPathService>().MoveToRecycleBin(WorldList[i].Path);
                 Platform.Get<IPathService>().MoveToRecycleBin(WorldList[i].Path + ".bak");
                 for (int j = 2; j <= 9; j++)
                 {
                     Platform.Get<IPathService>().MoveToRecycleBin(WorldList[i].Path + ".bak" + j);
                 }
             }
             else if (SocialAPI.Cloud != null)
             {
                 SocialAPI.Cloud.Delete(WorldList[i].Path);
             }
             LoadWorlds();
         }
         catch
         {
         }
     }
References SocialAPI.Cloud, CloudSocialModule.Delete(), LoadWorlds(), and WorldList.
Referenced by DedServ(), and DrawMenu().