Terraria: Main.IsTileBiomeSightable
IsTileBiomeSightable()
static bool Main.IsTileBiomeSightable (ushort type, short tileFrameX, short tileFrameY, ref Microsoft.Xna.Framework.Color sightColor) inline static
     {
         if (TileID.Sets.CorruptBiomeSight[type] || (remixWorld && type == 474))
         {
             sightColor = new Microsoft.Xna.Framework.Color(200, 100, 240);
             return true;
         }
         if (TileID.Sets.CrimsonBiomeSight[type] || (remixWorld && type == 195))
         {
             sightColor = new Microsoft.Xna.Framework.Color(255, 100, 100);
             return true;
         }
         if (TileID.Sets.HallowBiomeSight[type])
         {
             sightColor = new Microsoft.Xna.Framework.Color(255, 160, 240);
             return true;
         }
         return false;
     }
References TileID.Sets.CorruptBiomeSight, TileID.Sets.CrimsonBiomeSight, TileID.Sets.HallowBiomeSight, and remixWorld.
Referenced by TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), TileDrawing.DrawSingleTile(), and TileDrawing.DrawVineStrip().