Terraria: Main.DrawInterface_11_IngameOptionsMenu
DrawInterface_11_IngameOptionsMenu()
bool Main.DrawInterface_11_IngameOptionsMenu () inline private
     {
         bool result = true;
         if (ingameOptionsWindow)
         {
             DrawInterface_16_MapOrMinimap();
             PlayerInput.SetZoom_UI();
             Matrix uIScaleMatrix = UIScaleMatrix;
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, uIScaleMatrix);
             IngameOptions.Draw(this, spriteBatch);
             DrawInterface_40_InteractItemIcon();
             DrawPendingMouseText();
             result = false;
             _MouseOversCanClear = true;
         }
         return result;
     }
References _MouseOversCanClear, IngameOptions.Draw(), DrawInterface_16_MapOrMinimap(), DrawInterface_40_InteractItemIcon(), DrawPendingMouseText(), ingameOptionsWindow, PlayerInput.SetZoom_UI(), spriteBatch, and UIScaleMatrix.
Referenced by SetupDrawInterfaceLayers().