Terraria: Main.DrawBG
DrawBG()
void Main.DrawBG () inline private
     {
         float num = Math.Min(PlayerInput.RealScreenHeight, LogicCheckScreenHeight);
         float num2 = screenPosition.Y + (float)(screenHeight / 2) - num / 2f;
         scAdj = (float)(worldSurface * 16.0) / (num2 + num);
         float num3 = (float)maxTilesY * 0.15f * 16f;
         num3 -= num2;
         if (num3 < 0f)
         {
             num3 = 0f;
         }
         num3 *= 0.00025f;
         float num4 = num3 * num3;
         scAdj *= 0.45f - num4;
         if (maxTilesY <= 1200)
         {
             scAdj *= -500f;
         }
         else if (maxTilesY <= 1800)
         {
             scAdj *= -300f;
         }
         else
         {
             scAdj *= -150f;
         }
         float num5 = screenHeight;
         screenOff = num5 - 600f;
         bgTopY = (int)((double)(0f - screenPosition.Y + screenOff / 2f) / (worldSurface * 16.0) * 1200.0 + 1190.0) + (int)scAdj;
         cTop = bgTopY - 50;
         if (resetClouds)
         {
             Cloud.resetClouds();
             resetClouds = false;
         }
         bgScale = 1f;
         bgWidthScaled = (int)((float)backgroundWidth[treeMntBGSet1[0]] * bgScale);
         ColorOfSurfaceBackgroundsModified = ColorOfTheSkies;
         ColorOfSurfaceBackgroundsBase = ColorOfTheSkies;
         int preferredBGStyleForPlayer = GetPreferredBGStyleForPlayer();
         int num6 = 30;
         backgroundLayerTransitionSpeed = 0.05f;
         if (preferredBGStyleForPlayer == 0)
         {
             num6 = 60;
         }
         if (bgDelay < 0)
         {
             bgDelay++;
         }
         else if (preferredBGStyleForPlayer != bgStyle)
         {
             bgDelay++;
             if (bgDelay > num6)
             {
                 bgDelay = -60;
                 bgStyle = preferredBGStyleForPlayer;
                 if (preferredBGStyleForPlayer == 0)
                 {
                     bgDelay = 0;
                 }
             }
         }
         else if (bgDelay > 0)
         {
             bgDelay--;
         }
         if (gameMenu)
         {
             backgroundLayerTransitionSpeed = 0.02f;
             if (!dayTime)
             {
                 bgStyle = 1;
             }
             else
             {
                 bgStyle = 0;
             }
             preferredBGStyleForPlayer = bgStyle;
             if (WorldGen.drunkWorldGen)
             {
                 bgStyle = 9;
             }
         }
         if (instantBGTransitionCounter > 0)
         {
             instantBGTransitionCounter--;
             bgStyle = preferredBGStyleForPlayer;
             backgroundLayerTransitionSpeed = 1f;
         }
         UpdateBGVisibility_BackLayer(null, null);
         UpdateBGVisibility_FrontLayer(null, null);
         try
         {
             DrawSurfaceBG();
             if (BackgroundEnabled)
             {
                 DrawUnderworldBackground(flat: false);
             }
         }
         catch (Exception ex)
         {
             if (!ignoreErrors)
             {
                 throw ex;
             }
             TimeLogger.DrawException(ex);
         }
         TimeLogger.DetailedDrawTime(8);
     }
References BackgroundEnabled, backgroundLayerTransitionSpeed, backgroundWidth, bgDelay, bgScale, bgStyle, bgTopY, bgWidthScaled, ColorOfSurfaceBackgroundsBase, ColorOfSurfaceBackgroundsModified, ColorOfTheSkies, cTop, dayTime, TimeLogger.DetailedDrawTime(), TimeLogger.DrawException(), DrawSurfaceBG(), DrawUnderworldBackground(), WorldGen.drunkWorldGen, gameMenu, GetPreferredBGStyleForPlayer(), ignoreErrors, instantBGTransitionCounter, LogicCheckScreenHeight, maxTilesY, PlayerInput.RealScreenHeight, Cloud.resetClouds(), resetClouds, scAdj, screenHeight, screenOff, screenPosition, treeMntBGSet1, UpdateBGVisibility_BackLayer(), UpdateBGVisibility_FrontLayer(), and worldSurface.
Referenced by DoDraw().