Terraria: Main.PrepareDrawnProjectileDrawing
PrepareDrawnProjectileDrawing()
void Main.PrepareDrawnProjectileDrawing (Projectile proj) inline
     {
         CurrentDrawnEntity = proj;
         int projectileDesiredShader = GetProjectileDesiredShader(proj);
         Matrix value = Transform;
         if (proj.isAPreviewDummy)
         {
             value = UIScaleMatrix;
         }
         PrepareDrawnEntityDrawing(proj, projectileDesiredShader, value);
     }
References CurrentDrawnEntity, GetProjectileDesiredShader(), Projectile.isAPreviewDummy, PrepareDrawnEntityDrawing(), Transform, and UIScaleMatrix.
Referenced by DrawProj_EmpressBlade(), and DrawProjDirect().