Terraria: Main.DrawItemIcon
DrawItemIcon()
static void Main.DrawItemIcon (SpriteBatch spriteBatch, Item theItem, Vector2 screenPositionForItemCenter, Microsoft.Xna.Framework.Color itemLightColor, float sizeLimit) inline static
     {
         GetItemDrawFrame(theItem.type, out var itemTexture, out var frame);
         ItemSlot.DrawItem_GetColorAndScale(theItem, theItem.scale, ref itemLightColor, sizeLimit, ref frame, out var itemLight, out var finalDrawScale);
         spriteBatch.Draw(itemTexture, screenPositionForItemCenter, frame, itemLight, 0f, frame.Size() / 2f, finalDrawScale, SpriteEffects.None, 0f);
         if (theItem.color != Microsoft.Xna.Framework.Color.Transparent)
         {
             spriteBatch.Draw(itemTexture, screenPositionForItemCenter, frame, theItem.GetColor(itemLightColor), 0f, frame.Size() / 2f, finalDrawScale, SpriteEffects.None, 0f);
         }
     }
References Item.color, ItemSlot.DrawItem_GetColorAndScale(), Item.GetColor(), GetItemDrawFrame(), Item.scale, spriteBatch, and Item.type.