Terraria: Main.TryInteractingWithMoneyTrough2
TryInteractingWithMoneyTrough2()
static void Main.TryInteractingWithMoneyTrough2 (Projectile proj) inline static private
     {
         if (gamePaused && !gameMenu)
         {
             return;
         }
         Vector2 vector = proj.position - screenPosition;
         if (!((float)mouseX > vector.X) || !((float)mouseX < vector.X + (float)proj.width) || !((float)mouseY > vector.Y) || !((float)mouseY < vector.Y + (float)proj.height))
         {
             return;
         }
         int num = (int)(player[myPlayer].Center.X / 16f);
         int num2 = (int)(player[myPlayer].Center.Y / 16f);
         int num3 = (int)proj.Center.X / 16;
         int num4 = (int)proj.Center.Y / 16;
         int lastTileRangeX = player[myPlayer].lastTileRangeX;
         int lastTileRangeY = player[myPlayer].lastTileRangeY;
         if (num < num3 - lastTileRangeX || num > num3 + lastTileRangeX + 1 || num2 < num4 - lastTileRangeY || num2 > num4 + lastTileRangeY + 1)
         {
             return;
         }
         Player localPlayer = LocalPlayer;
         player[myPlayer].noThrow = 2;
         player[myPlayer].cursorItemIconEnabled = true;
         player[myPlayer].cursorItemIconID = 3213;
         if (PlayerInput.UsingGamepad)
         {
             player[myPlayer].GamepadEnableGrappleCooldown();
         }
         if (mouseRight && mouseRightRelease && Player.BlockInteractionWithProjectiles == 0)
         {
             mouseRightRelease = false;
             localPlayer.tileInteractAttempted = true;
             localPlayer.tileInteractionHappened = true;
             localPlayer.releaseUseTile = false;
             if (player[myPlayer].chest == -2)
             {
                 SoundEngine.PlaySound(SoundID.Item59);
                 player[myPlayer].chest = -1;
                 Recipe.FindRecipes();
                 return;
             }
             player[myPlayer].piggyBankProjTracker.Set(proj);
             player[myPlayer].chest = -2;
             player[myPlayer].chestX = (int)(proj.Center.X / 16f);
             player[myPlayer].chestY = (int)(proj.Center.Y / 16f);
             player[myPlayer].SetTalkNPC(-1);
             SetNPCShopIndex(0);
             playerInventory = true;
             SoundEngine.PlaySound(SoundID.Item59);
             Recipe.FindRecipes();
         }
     }
References Player.BlockInteractionWithProjectiles, Entity.Center, chest, Player.chest, Player.chestX, Player.chestY, Player.cursorItemIconEnabled, Player.cursorItemIconID, Recipe.FindRecipes(), gameMenu, Player.GamepadEnableGrappleCooldown(), gamePaused, Entity.height, SoundID.Item59, Player.lastTileRangeX, Player.lastTileRangeY, LocalPlayer, mouseRight, mouseRightRelease, mouseX, mouseY, myPlayer, Player.noThrow, Player.piggyBankProjTracker, player, playerInventory, SoundEngine.PlaySound(), Entity.position, Player.releaseUseTile, screenPosition, TrackedProjectileReference.Set(), SetNPCShopIndex(), Player.SetTalkNPC(), Player.tileInteractAttempted, Player.tileInteractionHappened, PlayerInput.UsingGamepad, and Entity.width.