Terraria: Main.ResetAllContentBasedRenderTargets
ResetAllContentBasedRenderTargets()
void Main.ResetAllContentBasedRenderTargets () inline
     {
         TilePaintSystem.Reset();
         for (int i = 0; i < ContentThatNeedsRenderTargets.Count; i++)
         {
             ContentThatNeedsRenderTargets[i].Reset();
         }
     }
References ContentThatNeedsRenderTargets, TilePaintSystemV2.Reset(), and TilePaintSystem.
Referenced by UIResourcePackSelectionMenu.CreateOffsetButton(), and UIResourcePackSelectionMenu.CreatePackToggleButton().