Terraria: Main.ApplyColorOfTheSkiesToTiles
ApplyColorOfTheSkiesToTiles()
static void Main.ApplyColorOfTheSkiesToTiles () inline static private
     {
         Microsoft.Xna.Framework.Color colorOfTheSkies = ColorOfTheSkies;
         tileColor.A = byte.MaxValue;
         tileColor.R = (byte)((colorOfTheSkies.R + colorOfTheSkies.G + colorOfTheSkies.B + colorOfTheSkies.R * 7) / 10);
         tileColor.G = (byte)((colorOfTheSkies.R + colorOfTheSkies.G + colorOfTheSkies.B + colorOfTheSkies.G * 7) / 10);
         tileColor.B = (byte)((colorOfTheSkies.R + colorOfTheSkies.G + colorOfTheSkies.B + colorOfTheSkies.B * 7) / 10);
         tileColor = SkyManager.Instance.ProcessTileColor(tileColor);
     }
References ColorOfTheSkies, SkyManager.Instance, SkyManager.ProcessTileColor(), and tileColor.
Referenced by DoDraw(), and DrawCapture().