Terraria: Main.DrawStarsInBackground
DrawStarsInBackground()
void Main.DrawStarsInBackground (SceneArea sceneArea, bool artificial) inline private
     {
         if (netMode == 2 || ((double)screenPosition.Y >= worldSurface * 16.0 + 16.0 && shimmerAlpha == 0f))
         {
             return;
         }
         float num = 1f;
         if (GraveyardVisualIntensity > 0f)
         {
             float num2 = 1f - GraveyardVisualIntensity * 1.4f;
             if (num2 <= 0f)
             {
                 return;
             }
             num *= num2;
         }
         Microsoft.Xna.Framework.Color colorOfTheSkies = ColorOfTheSkies;
         if (shimmerAlpha > 0f)
         {
             colorOfTheSkies *= 1f - shimmerAlpha;
         }
         if (remixWorld || !(255f * (1f - cloudAlpha * atmo) - (float)(int)colorOfTheSkies.R - 25f <= 0f))
         {
             for (int i = 0; i < numStars; i++)
             {
                 DrawStar(ref sceneArea, num, colorOfTheSkies, i, star[i], artificial);
             }
         }
     }
References atmo, cloudAlpha, ColorOfTheSkies, DrawStar(), GraveyardVisualIntensity, netMode, numStars, remixWorld, screenPosition, shimmerAlpha, star, and worldSurface.
Referenced by DoDraw(), and DrawCapture().