Terraria: Main.DrawPVPIcons
DrawPVPIcons()
static void Main.DrawPVPIcons () inline static private
     {
         if (EquipPage == 1)
         {
             if (hidePVPIcons)
             {
                 return;
             }
         }
         else
         {
             hidePVPIcons = false;
         }
         inventoryScale = 0.6f;
         int num = (int)(52f * inventoryScale);
         int num2 = 707 - num * 4 + screenWidth - 800;
         int num3 = 114 + mH + num * 2 + num / 2 - 12;
         if (EquipPage == 2)
         {
             num2 += num + num / 2;
         }
         int num4 = (player[myPlayer].hostile ? 2 : 0);
         if (mouseX > num2 - 7 && mouseX < num2 + 25 && mouseY > num3 - 2 && mouseY < num3 + 37 && !PlayerInput.IgnoreMouseInterface)
         {
             player[myPlayer].mouseInterface = true;
             if (teamCooldown == 0)
             {
                 num4++;
             }
             if (mouseLeft && mouseLeftRelease && teamCooldown == 0)
             {
                 teamCooldown = teamCooldownLen;
                 SoundEngine.PlaySound(12);
                 player[myPlayer].hostile = !player[myPlayer].hostile;
                 NetMessage.SendData(30, -1, -1, null, myPlayer);
             }
         }
         Microsoft.Xna.Framework.Rectangle rectangle = TextureAssets.Pvp[0].Frame(4, 6);
         rectangle.Location = new Microsoft.Xna.Framework.Point(rectangle.Width * num4, rectangle.Height * player[myPlayer].team);
         rectangle.Width -= 2;
         rectangle.Height--;
         spriteBatch.Draw(TextureAssets.Pvp[0].Value, new Vector2(num2 - 10, num3), rectangle, Microsoft.Xna.Framework.Color.White, 0f, Vector2.Zero, Vector2.One, SpriteEffects.None, 0f);
         UILinkPointNavigator.SetPosition(1550, new Vector2(num2 - 10, num3) + rectangle.Size() * 0.75f);
         num3 += 60;
         num2 -= 10;
         rectangle = TextureAssets.Pvp[1].Frame(6);
         Microsoft.Xna.Framework.Rectangle r = rectangle;
         for (int i = 0; i < 6; i++)
         {
             r.Location = new Microsoft.Xna.Framework.Point(num2 + i % 2 * 20, num3 + i / 2 * 20);
             rectangle.X = rectangle.Width * i;
             bool flag = false;
             if (r.Contains(MouseScreen.ToPoint()) && !PlayerInput.IgnoreMouseInterface)
             {
                 player[myPlayer].mouseInterface = true;
                 if (teamCooldown == 0)
                 {
                     flag = true;
                 }
                 if (mouseLeft && mouseLeftRelease && player[myPlayer].team != i && teamCooldown == 0)
                 {
                     if (!player[myPlayer].TeamChangeAllowed())
                     {
                         NewText(Lang.misc[84].Value, byte.MaxValue, 240, 20);
                     }
                     else
                     {
                         teamCooldown = teamCooldownLen;
                         SoundEngine.PlaySound(12);
                         player[myPlayer].team = i;
                         NetMessage.SendData(45, -1, -1, null, myPlayer);
                     }
                 }
             }
             r.Width = rectangle.Width - 2;
             if (flag)
             {
                 spriteBatch.Draw(TextureAssets.Pvp[2].Value, r.Location.ToVector2() + new Vector2(-2f), Microsoft.Xna.Framework.Color.White);
             }
             Microsoft.Xna.Framework.Rectangle value = rectangle;
             value.Width -= 2;
             spriteBatch.Draw(TextureAssets.Pvp[1].Value, r.Location.ToVector2(), value, Microsoft.Xna.Framework.Color.White);
             UILinkPointNavigator.SetPosition(1550 + i + 1, r.Location.ToVector2() + r.Size() * 0.75f);
         }
     }
References EquipPage, hidePVPIcons, Player.hostile, PlayerInput.IgnoreMouseInterface, inventoryScale, mH, Lang.misc, Player.mouseInterface, mouseLeft, mouseLeftRelease, MouseScreen, mouseX, mouseY, myPlayer, NewText(), player, SoundEngine.PlaySound(), TextureAssets.Pvp, screenWidth, NetMessage.SendData(), UILinkPointNavigator.SetPosition(), spriteBatch, Player.team, teamCooldown, teamCooldownLen, Asset< T >.Value, and LocalizedText.Value.
Referenced by DrawInventory().