Terraria: Main.UpdateTime_StartNight
UpdateTime_StartNight()
static void Main.UpdateTime_StartNight (ref bool stopEvents) inline static
     {
         if (fastForwardTimeToDusk)
         {
             fastForwardTimeToDusk = false;
             UpdateTimeRate();
         }
         if (moondialCooldown > 0)
         {
             moondialCooldown--;
         }
         NPC.ResetBadgerHatTime();
         NPC.freeCake = false;
         Star.NightSetup();
         NPC.setFireFlyChance();
         BirthdayParty.CheckNight();
         LanternNight.CheckNight();
         WorldGen.mysticLogsEvent.StartNight();
         WorldGen.prioritizedTownNPCType = 0;
         checkForSpawns = 0;
         if (rand.Next(50) == 0 && netMode != 1 && NPC.downedBoss2)
         {
             WorldGen.spawnMeteor = true;
         }
         if (LanternNight.LanternsUp)
         {
             stopEvents = true;
         }
         if (eclipse && netMode != 1)
         {
             AchievementsHelper.NotifyProgressionEvent(3);
         }
         eclipse = false;
         if (netMode != 1)
         {
             AchievementsHelper.NotifyProgressionEvent(0);
         }
         if (!IsFastForwardingTime() && !stopEvents)
         {
             if (!NPC.downedBoss1 && netMode != 1)
             {
                 bool flag = false;
                 for (int i = 0; i < 255; i++)
                 {
                     if (player[i].active && player[i].statLifeMax >= 200 && player[i].statDefense > 10)
                     {
                         flag = true;
                         break;
                     }
                 }
                 if (flag && rand.Next(3) == 0)
                 {
                     int num = 0;
                     for (int j = 0; j < 200; j++)
                     {
                         if (npc[j].active && npc[j].townNPC)
{
                             num++;
                         }
                     }
                     if (num >= 4)
                     {
                         WorldGen.spawnEye = true;
                         if (netMode == 0)
{
                             NewText(Lang.misc[9].Value, 50, byte.MaxValue, 130);
                         }
                         else if (netMode == 2)
{
                             ChatHelper.BroadcastChatMessage(Lang.misc[9].ToNetworkText(), new Microsoft.Xna.Framework.Color(50, 255, 130));
                         }
                     }
                 }
             }
             if (netMode != 1 && !pumpkinMoon && !DD2Event.Ongoing && !snowMoon && WorldGen.altarCount > 0 && hardMode && !WorldGen.spawnEye && rand.Next(10) == 0)
             {
                 bool flag2 = false;
                 for (int k = 0; k < 200; k++)
                 {
                     if (npc[k].active && npc[k].boss)
                     {
                         flag2 = true;
                     }
                 }
                 if (!flag2 && (!NPC.downedMechBoss1 || !NPC.downedMechBoss2 || !NPC.downedMechBoss3))
                 {
                     if (remixWorld && getGoodWorld)
                     {
                         if (rand.Next(2) == 0)
{
                             WorldGen.spawnHardBoss = rand.Next(3) + 1;
                             if (netMode == 0)
{
                                 NewText(Lang.misc[108].Value, 50, byte.MaxValue, 130);
                             }
                             else if (netMode == 2)
{
                                 ChatHelper.BroadcastChatMessage(Lang.misc[108].ToNetworkText(), new Microsoft.Xna.Framework.Color(50, 255, 130));
                             }
                         }
                     }
                     else
                     {
                         for (int l = 0; l < 1000; l++)
{
                             int num2 = rand.Next(3) + 1;
                             if (num2 == 1 && !NPC.downedMechBoss1)
{
                                 WorldGen.spawnHardBoss = num2;
                                 if (netMode == 0)
{
                                     NewText(Lang.misc[28].Value, 50, byte.MaxValue, 130);
                                 }
                                 else if (netMode == 2)
{
                                     ChatHelper.BroadcastChatMessage(Lang.misc[28].ToNetworkText(), new Microsoft.Xna.Framework.Color(50, 255, 130));
                                 }
                                 break;
                             }
                             if (num2 == 2 && !NPC.downedMechBoss2)
{
                                 WorldGen.spawnHardBoss = num2;
                                 if (netMode == 0)
{
                                     NewText(Lang.misc[29].Value, 50, byte.MaxValue, 130);
                                 }
                                 else if (netMode == 2)
{
                                     ChatHelper.BroadcastChatMessage(Lang.misc[29].ToNetworkText(), new Microsoft.Xna.Framework.Color(50, 255, 130));
                                 }
                                 break;
                             }
                             if (num2 == 3 && !NPC.downedMechBoss3)
{
                                 WorldGen.spawnHardBoss = num2;
                                 if (netMode == 0)
{
                                     NewText(Lang.misc[30].Value, 50, byte.MaxValue, 130);
                                 }
                                 else if (netMode == 2)
{
                                     ChatHelper.BroadcastChatMessage(Lang.misc[30].ToNetworkText(), new Microsoft.Xna.Framework.Color(50, 255, 130));
                                 }
                                 break;
                             }
                         }
                     }
                 }
             }
             int maxValue = 9;
             if (tenthAnniversaryWorld)
             {
                 maxValue = 6;
             }
             if (!WorldGen.spawnEye && moonPhase != 4 && rand.Next(maxValue) == 0 && netMode != 1)
             {
                 for (int m = 0; m < 255; m++)
                 {
                     if (player[m].active && player[m].statLifeMax > 120)
                     {
                         bloodMoon = true;
                         break;
                     }
                 }
                 if (bloodMoon)
                 {
                     sundialCooldown = 0;
                     moondialCooldown = 0;
                     AchievementsHelper.NotifyProgressionEvent(4);
                     if (netMode == 0)
                     {
                         NewText(Lang.misc[8].Value, 50, byte.MaxValue, 130);
                     }
                     else if (netMode == 2)
                     {
                         ChatHelper.BroadcastChatMessage(Lang.misc[8].ToNetworkText(), new Microsoft.Xna.Framework.Color(50, 255, 130));
                     }
                 }
             }
         }
         time = 0.0;
         dayTime = false;
         if (netMode == 2)
         {
             NetMessage.SendData(7);
         }
     }
References WorldGen.altarCount, bloodMoon, ChatHelper.BroadcastChatMessage(), checkForSpawns, BirthdayParty.CheckNight(), LanternNight.CheckNight(), dayTime, NPC.downedBoss1, NPC.downedBoss2, NPC.downedMechBoss1, NPC.downedMechBoss2, NPC.downedMechBoss3, eclipse, fastForwardTimeToDusk, NPC.freeCake, getGoodWorld, hardMode, IsFastForwardingTime(), LanternNight.LanternsUp, Lang.misc, moondialCooldown, moonPhase, WorldGen.mysticLogsEvent, netMode, NewText(), UnifiedRandom.Next(), Star.NightSetup(), AchievementsHelper.NotifyProgressionEvent(), npc, DD2Event.Ongoing, player, WorldGen.prioritizedTownNPCType, pumpkinMoon, rand, remixWorld, NPC.ResetBadgerHatTime(), NetMessage.SendData(), NPC.setFireFlyChance(), snowMoon, WorldGen.spawnEye, WorldGen.spawnHardBoss, WorldGen.spawnMeteor, MysticLogFairiesEvent.StartNight(), sundialCooldown, tenthAnniversaryWorld, time, LocalizedText.ToNetworkText(), UpdateTimeRate(), and LocalizedText.Value.
Referenced by SkipToTime(), and UpdateTime().