Terraria: Main.DrawCursor
DrawCursor()
static void Main.DrawCursor (Vector2 bonus, bool smart = false) inline static
     {
         if (gameMenu && alreadyGrabbingSunOrMoon)
         {
             return;
         }
         if (player[myPlayer].dead || player[myPlayer].mouseInterface)
         {
             ClearSmartInteract();
             TileInteractionLX = (TileInteractionHX = (TileInteractionLY = (TileInteractionHY = -1)));
         }
         Microsoft.Xna.Framework.Color color = cursorColor;
         if (!gameMenu && LocalPlayer.hasRainbowCursor)
         {
             color = hslToRgb(GlobalTimeWrappedHourly * 0.25f % 1f, 1f, 0.5f);
         }
         bool flag = UILinkPointNavigator.Available && !PlayerInput.InBuildingMode;
         if (PlayerInput.SettingsForUI.ShowGamepadCursor)
         {
             if ((player[myPlayer].dead && !player[myPlayer].ghost && !gameMenu) || PlayerInput.InvisibleGamepadInMenus)
             {
                 return;
             }
             Vector2 t = new Vector2(mouseX, mouseY);
             Vector2 t2 = Vector2.Zero;
             bool flag2 = SmartCursorIsUsed;
             if (flag2)
             {
                 PlayerInput.smartSelectPointer.UpdateCenter(ScreenSize.ToVector2() / 2f);
                 t2 = PlayerInput.smartSelectPointer.GetPointerPosition();
                 if (Vector2.Distance(t2, t) < 1f)
                 {
                     flag2 = false;
                 }
                 else
                 {
                     Utils.Swap(ref t, ref t2);
                 }
             }
             float num = 1f;
             if (flag2)
             {
                 num = 0.3f;
                 color = Microsoft.Xna.Framework.Color.White * GamepadCursorAlpha;
                 int num2 = 17;
                 int frameX = 0;
                 spriteBatch.Draw(TextureAssets.Cursors[num2].Value, t2 + bonus, TextureAssets.Cursors[num2].Frame(1, 1, frameX), color, (float)Math.PI / 2f * GlobalTimeWrappedHourly, TextureAssets.Cursors[num2].Frame(1, 1, frameX).Size() / 2f, cursorScale, SpriteEffects.None, 0f);
             }
             if (smart && !flag)
             {
                 color = Microsoft.Xna.Framework.Color.White * GamepadCursorAlpha * num;
                 int num3 = 13;
                 int frameX2 = 0;
                 spriteBatch.Draw(TextureAssets.Cursors[num3].Value, t + bonus, TextureAssets.Cursors[num3].Frame(2, 1, frameX2), color, 0f, TextureAssets.Cursors[num3].Frame(2, 1, frameX2).Size() / 2f, cursorScale, SpriteEffects.None, 0f);
             }
             else
             {
                 color = Microsoft.Xna.Framework.Color.White;
                 int num4 = 15;
                 spriteBatch.Draw(TextureAssets.Cursors[num4].Value, new Vector2(mouseX, mouseY) + bonus, null, color, 0f, TextureAssets.Cursors[num4].Value.Size() / 2f, cursorScale, SpriteEffects.None, 0f);
             }
         }
         else
         {
             int num5 = smart.ToInt();
             spriteBatch.Draw(TextureAssets.Cursors[num5].Value, new Vector2(mouseX, mouseY) + bonus + Vector2.One, null, new Microsoft.Xna.Framework.Color((int)((float)(int)color.R * 0.2f), (int)((float)(int)color.G * 0.2f), (int)((float)(int)color.B * 0.2f), (int)((float)(int)color.A * 0.5f)), 0f, default(Vector2), cursorScale * 1.1f, SpriteEffects.None, 0f);
             spriteBatch.Draw(TextureAssets.Cursors[num5].Value, new Vector2(mouseX, mouseY) + bonus, null, color, 0f, default(Vector2), cursorScale, SpriteEffects.None, 0f);
         }
     }
References alreadyGrabbingSunOrMoon, UILinkPointNavigator.Available, ClearSmartInteract(), cursorColor, TextureAssets.Cursors, cursorScale, gameMenu, GamepadCursorAlpha, SmartSelectGamepadPointer.GetPointerPosition(), GlobalTimeWrappedHourly, Player.hasRainbowCursor, hslToRgb(), PlayerInput.InBuildingMode, PlayerInput.InvisibleGamepadInMenus, LocalPlayer, mouseX, mouseY, myPlayer, player, ScreenSize, PlayerInput.SettingsForUI.ShowGamepadCursor, SmartCursorIsUsed, PlayerInput.smartSelectPointer, spriteBatch, TileInteractionHX, TileInteractionHY, TileInteractionLX, TileInteractionLY, SmartSelectGamepadPointer.UpdateCenter(), and Asset< T >.Value.
Referenced by DoDraw(), IngameFancyUI.Draw(), DrawInterface_36_Cursor(), DrawMap(), and DrawMenu().