Terraria: Main.DrawInterface_Resources_GolfPower
DrawInterface_Resources_GolfPower()
static void Main.DrawInterface_Resources_GolfPower () inline static private
     {
         Projectile projectile = null;
         for (int i = 0; i < 1000; i++)
         {
             Projectile projectile2 = Main.projectile[i];
             if (projectile2.active && projectile2.owner == myPlayer && projectile2.type == 722)
             {
                 projectile = projectile2;
                 break;
             }
         }
         if (projectile == null)
         {
             return;
         }
         Projectile projectile3 = GolfHelper.FindGolfBallForHelper(projectile);
         if (projectile3 != null)
         {
             float relativeStrength = GolfHelper.CalculateShotStrength(projectile, projectile3).RelativeStrength;
             if (!(relativeStrength < 0.001f))
             {
                 Vector2 position = LocalPlayer.Bottom - Camera.ScaledPosition;
                 position *= GameViewMatrix.Zoom;
                 position /= UIScale;
                 position.X -= 27f;
                 position.Y += 14f;
                 spriteBatch.Draw(TextureAssets.GolfSwingBarPanel.Value, position, null, Microsoft.Xna.Framework.Color.White);
                 spriteBatch.Draw(TextureAssets.GolfSwingBarFill.Value, position, new Microsoft.Xna.Framework.Rectangle(0, 0, (int)(54f * relativeStrength), 14), Microsoft.Xna.Framework.Color.White);
             }
         }
     }
References Entity.active, Entity.Bottom, GolfHelper.CalculateShotStrength(), GolfHelper.FindGolfBallForHelper(), GameViewMatrix, TextureAssets.GolfSwingBarFill, TextureAssets.GolfSwingBarPanel, LocalPlayer, myPlayer, Projectile.owner, projectile, GolfHelper.ShotStrength.RelativeStrength, Camera.ScaledPosition, spriteBatch, Projectile.type, UIScale, Asset< T >.Value, and SpriteViewMatrix.Zoom.
Referenced by DrawInterface_9_WireSelection().