Terraria: Main.DrawProj_FairyQueenRangedItemShot
DrawProj_FairyQueenRangedItemShot()
void Main.DrawProj_FairyQueenRangedItemShot (Projectile proj) inline private
     {
         Vector2 vector = proj.Center - screenPosition;
         Microsoft.Xna.Framework.Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0f);
         Microsoft.Xna.Framework.Color fairyQueenWeaponsColor2 = proj.GetFairyQueenWeaponsColor(0.5f);
         Texture2D value = TextureAssets.Projectile[proj.type].Value;
         Vector2 origin = value.Frame().Size() / 2f;
         Microsoft.Xna.Framework.Color color = Microsoft.Xna.Framework.Color.White * proj.Opacity;
         color.A /= 2;
         float num = MathHelper.Lerp(0.7f, 1f, Utils.GetLerpValue(0f, 5f, proj.ai[0], clamped: true));
         float opacity = proj.Opacity;
         if (opacity > 0f)
         {
             float lerpValue = Utils.GetLerpValue(0f, 1f, proj.velocity.Length(), clamped: true);
             for (float num2 = 0f; num2 < 1f; num2 += 1f / 6f)
             {
                 Vector2 vector2 = proj.rotation.ToRotationVector2() * -120f * num2 * lerpValue;
                 spriteBatch.Draw(value, vector + vector2, null, fairyQueenWeaponsColor * opacity * (1f - num2), proj.rotation, origin, num, SpriteEffects.None, 0f);
             }
             for (float num3 = 0f; num3 < 1f; num3 += 0.25f)
             {
                 Vector2 vector3 = (num3 * ((float)Math.PI * 2f) + proj.rotation).ToRotationVector2() * 4f * num;
                 spriteBatch.Draw(value, vector + vector3, null, fairyQueenWeaponsColor2 * opacity, proj.rotation, origin, num, SpriteEffects.None, 0f);
             }
         }
         spriteBatch.Draw(value, vector, null, color, proj.rotation, origin, num, SpriteEffects.None, 0f);
     }
References Projectile.ai, Entity.Center, Projectile.GetFairyQueenWeaponsColor(), Utils.GetLerpValue(), Projectile.Opacity, TextureAssets.Projectile, Projectile.rotation, screenPosition, spriteBatch, Projectile.type, Asset< T >.Value, and Entity.velocity.
Referenced by DrawProjDirect().