Terraria: Main.Draw
Draw()
override void Main.Draw (GameTime gameTime) inline protected virtual
Reimplemented from Game.
     {
         if (!_isDrawingOrUpdating && IsGraphicsDeviceAvailable)
         {
             _isDrawingOrUpdating = true;
             EnsureRenderTargetContent();
             DoDraw(gameTime);
             if (Main.OnPostDraw != null)
             {
                 Main.OnPostDraw(gameTime);
             }
             Assets.TransferCompletedAssets();
             _isDrawingOrUpdating = false;
         }
     }
References _isDrawingOrUpdating, Assets, DoDraw(), EnsureRenderTargetContent(), IsGraphicsDeviceAvailable, OnPostDraw, and IAssetRepository.TransferCompletedAssets().
Referenced by DoDraw().