Terraria: Main.DrawProj_PiercingStarlight
DrawProj_PiercingStarlight()
void Main.DrawProj_PiercingStarlight (Projectile proj) inline private
     {
         float num = proj.ai[1];
         if (num == 0f)
         {
             num = 1f;
         }
         int num2 = (int)Math.Ceiling(3f * num);
         LoadProjectile(proj.type);
         LoadItem(4923);
         int num3 = 2;
         Vector2 vector = proj.Center - proj.rotation.ToRotationVector2() * num3;
         for (int i = 0; i < 1; i++)
         {
             float num4 = rand.NextFloat();
             float num5 = Utils.GetLerpValue(0f, 0.3f, num4, clamped: true) * Utils.GetLerpValue(1f, 0.5f, num4, clamped: true);
             Microsoft.Xna.Framework.Color color = proj.GetAlpha(Lighting.GetColor(proj.Center.ToTileCoordinates())) * num5;
             Texture2D value = TextureAssets.Item[4923].Value;
             Vector2 origin = value.Size() / 2f;
             float num6 = rand.NextFloatDirection();
             float num7 = 8f + MathHelper.Lerp(0f, 20f, num4) + rand.NextFloat() * 6f;
             float num8 = proj.rotation + num6 * ((float)Math.PI * 2f) * 0.04f;
             float num9 = num8 + (float)Math.PI / 4f;
             Vector2 position = vector + num8.ToRotationVector2() * num7 + rand.NextVector2Circular(8f, 8f) - screenPosition;
             SpriteEffects spriteEffects = SpriteEffects.None;
             if (proj.rotation < -(float)Math.PI / 2f || proj.rotation > (float)Math.PI / 2f)
             {
                 num9 += (float)Math.PI / 2f;
                 spriteEffects |= SpriteEffects.FlipHorizontally;
             }
             spriteBatch.Draw(value, position, null, color, num9, origin, 1f, spriteEffects, 0f);
         }
         for (int j = 0; j < num2; j++)
         {
             float num10 = rand.NextFloat();
             float num11 = Utils.GetLerpValue(0f, 0.3f, num10, clamped: true) * Utils.GetLerpValue(1f, 0.5f, num10, clamped: true);
             float amount = Utils.GetLerpValue(0f, 0.3f, num10, clamped: true) * Utils.GetLerpValue(1f, 0.5f, num10, clamped: true);
             float num12 = MathHelper.Lerp(0.6f, 1f, amount);
             Microsoft.Xna.Framework.Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0.25f, 0f, (rand.NextFloat() * 0.33f + GlobalTimeWrappedHourly) % 1f);
             Texture2D value2 = TextureAssets.Projectile[proj.type].Value;
             Microsoft.Xna.Framework.Color color2 = fairyQueenWeaponsColor;
             color2 *= num11 * 0.5f;
             Vector2 origin2 = value2.Size() / 2f;
             Microsoft.Xna.Framework.Color color3 = Microsoft.Xna.Framework.Color.White * num11;
             color3.A /= 2;
             Microsoft.Xna.Framework.Color color4 = color3 * 0.5f;
             float num13 = 1f;
             float num14 = (num - 1f) / 2f;
             float num15 = rand.NextFloat() * 2f * num;
             num15 += num14;
             float num16 = rand.NextFloatDirection();
             Vector2 vector2 = new Vector2(2.8f + num15 * (1f + num14), 1f) * num13 * num12;
             float value3 = 50f * num;
             Vector2 vector3 = proj.rotation.ToRotationVector2() * ((j >= 1) ? 56 : 0);
             float num17 = 0.03f - (float)j * 0.012f;
             num17 /= num;
             float num18 = 30f + MathHelper.Lerp(0f, value3, num10) + num15 * 16f;
             float num19 = proj.rotation + num16 * ((float)Math.PI * 2f) * num17;
             float rotation = num19;
             Vector2 position2 = vector + num19.ToRotationVector2() * num18 + rand.NextVector2Circular(20f, 20f) + vector3 - screenPosition;
             color2 *= num13;
             color4 *= num13;
             SpriteEffects effects = SpriteEffects.None;
             spriteBatch.Draw(value2, position2, null, color2, rotation, origin2, vector2, effects, 0f);
             spriteBatch.Draw(value2, position2, null, color4, rotation, origin2, vector2 * 0.6f, effects, 0f);
         }
     }
References Projectile.ai, Entity.Center, Projectile.GetAlpha(), Lighting.GetColor(), Projectile.GetFairyQueenWeaponsColor(), Utils.GetLerpValue(), GlobalTimeWrappedHourly, TextureAssets.Item, LoadItem(), LoadProjectile(), TextureAssets.Projectile, rand, Projectile.rotation, screenPosition, spriteBatch, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().