Terraria: Main.DrawInterface_35_YouDied
DrawInterface_35_YouDied()
static void Main.DrawInterface_35_YouDied () inline static private
     {
         if (player[myPlayer].dead)
         {
             float num = -60f;
             string value = Lang.inter[38].Value;
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, value, new Vector2((float)(screenWidth / 2) - FontAssets.DeathText.Value.MeasureString(value).X / 2f, (float)(screenHeight / 2) + num), player[myPlayer].GetDeathAlpha(Microsoft.Xna.Framework.Color.Transparent), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             if (player[myPlayer].lostCoins > 0)
             {
                 num += 50f;
                 string textValue = Language.GetTextValue("Game.DroppedCoins", player[myPlayer].lostCoinString);
                 DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, textValue, new Vector2((float)(screenWidth / 2) - FontAssets.MouseText.Value.MeasureString(textValue).X / 2f, (float)(screenHeight / 2) + num), player[myPlayer].GetDeathAlpha(Microsoft.Xna.Framework.Color.Transparent), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
             num += (float)((player[myPlayer].lostCoins > 0) ? 24 : 50);
             num += 20f;
             float num2 = 0.7f;
             string textValue2 = Language.GetTextValue("Game.RespawnInSuffix", ((float)(int)(1f + (float)player[myPlayer].respawnTimer / 60f)).ToString());
             DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.DeathText.Value, textValue2, new Vector2((float)(screenWidth / 2) - FontAssets.MouseText.Value.MeasureString(textValue2).X * num2 / 2f, (float)(screenHeight / 2) + num), player[myPlayer].GetDeathAlpha(Microsoft.Xna.Framework.Color.Transparent), 0f, default(Vector2), num2, SpriteEffects.None, 0f);
         }
     }
References FontAssets.DeathText, DynamicSpriteFontExtensionMethods.DrawString(), Player.GetDeathAlpha(), Language.GetTextValue(), Lang.inter, FontAssets.MouseText, myPlayer, player, screenHeight, screenWidth, spriteBatch, Asset< T >.Value, and LocalizedText.Value.
Referenced by SetupDrawInterfaceLayers().