Terraria: Main.GetBuffTooltip
GetBuffTooltip()
static string Main.GetBuffTooltip (Player player, int buffType) inline static
     {
         string text = Lang.GetBuffDescription(buffType);
         switch (buffType)
         {
         case 26:
             if (expertMode)
             {
                 text = Language.GetTextValue("BuffDescription.WellFed_Expert");
             }
             break;
         case 206:
             if (expertMode)
             {
                 text = Language.GetTextValue("BuffDescription.WellFed2_Expert");
             }
             break;
         case 207:
             if (expertMode)
             {
                 text = Language.GetTextValue("BuffDescription.WellFed3_Expert");
             }
             break;
         case 94:
         {
             int num = (int)(player.manaSickReduction * 100f) + 1;
             text = text + num + "%";
             break;
         }
         }
         return text;
     }
References expertMode, Lang.GetBuffDescription(), Language.GetTextValue(), Player.manaSickReduction, and player.
Referenced by DrawInterface_Resources_Buffs(), and DrawInventory().