Terraria: Main.PostContentLoadInitialize
PostContentLoadInitialize()
static void Main.PostContentLoadInitialize () inline static private
     {
         LiquidRenderer.LoadContent();
         AchievementInitializer.Load();
         AchievementAdvisor.Initialize();
         DyeInitializer.Load();
         ScreenEffectInitializer.Load();
         InGameNotificationsTracker.Initialize();
         LinkButtonsInitializer.Load();
         _stardewAnimation = new StardewValleyAnimation();
         moonType = rand.Next(9);
         windSpeedCurrent = (float)rand.Next(-800, 801) * 0.001f;
         windSpeedTarget = windSpeedCurrent;
         numClouds = rand.Next(200);
         Mount.Initialize();
         Minecart.Initialize();
         CacheSupportedDisplaySizes();
         ContentSamples.RebuildItemCreativeSortingIDsAfterRecipesAreSetUp();
         ContentSamples.CommonlyUsedContentSamples.PrepareAfterEverythingElseLoaded();
     }
References _stardewAnimation, CacheSupportedDisplaySizes(), AchievementAdvisor.Initialize(), InGameNotificationsTracker.Initialize(), Minecart.Initialize(), Mount.Initialize(), AchievementInitializer.Load(), DyeInitializer.Load(), LinkButtonsInitializer.Load(), ScreenEffectInitializer.Load(), LiquidRenderer.LoadContent(), moonType, UnifiedRandom.Next(), numClouds, ContentSamples.CommonlyUsedContentSamples.PrepareAfterEverythingElseLoaded(), rand, ContentSamples.RebuildItemCreativeSortingIDsAfterRecipesAreSetUp(), windSpeedCurrent, and windSpeedTarget.
Referenced by DrawSplash().