Terraria: Main.UpdateMenu
UpdateMenu()
static void Main.UpdateMenu () inline static private
     {
         if (WorldGen.drunkWorldGen)
         {
             if (WorldGen.remixWorldGen)
             {
                 screenPosition.X -= 20f;
             }
             if (WorldGen.drunkWorldGenText)
             {
                 numClouds = rand.Next(100, 200);
                 statusText = string.Concat(rand.Next(999999999));
                 for (int i = 0; i < 3; i++)
                 {
                     if (rand.Next(2) == 0)
                     {
                         statusText += rand.Next(999999999);
                     }
                 }
             }
         }
         gamePaused = false;
         thunderDelay = 0;
         lightning = 0f;
         lightningSpeed = 0f;
         GraveyardVisualIntensity = 0f;
         InGameNotificationsTracker.Clear();
         playerInventory = false;
         exitScale = 0.8f;
         if (netMode == 0)
         {
             if (instance.IsActive && hasFocus && (!dayTime || WorldGen.remixWorldGen) && (rand.Next(12) == 0 || (WorldGen.drunkWorldGen && !remixWorld)))
             {
                 int num = rand.Next(numStars);
                 if (star[num] != null && !star[num].hidden && !star[num].falling)
                 {
                     star[num].Fall();
                 }
             }
             if (gameMenu)
             {
                 if (WorldGen.gen)
                 {
                     lockMenuBGChange = true;
                 }
                 else if (menuMode == 0)
                 {
                     lockMenuBGChange = false;
                 }
                 if (!lockMenuBGChange)
                 {
                     if (dayTime)
                     {
                         menuBGChangedDay = false;
                     }
                     else if (!menuBGChangedDay && time >= 16200.0)
                     {
                         menuBGChangedDay = true;
                         int style = WorldGen.corruptBG;
                         WorldGen.RandomizeBackgrounds(rand);
                         if (treeBGSet1[0] == 173)
{
                             WorldGen.RandomizeBackgrounds(rand);
                         }
                         if (treeBGSet1[0] == 173)
{
                             WorldGen.RandomizeBackgrounds(rand);
                         }
                         WorldGen.setBG(1, style);
                     }
                     if (!dayTime)
                     {
                         menuBGChangedNight = false;
                     }
                     else if (!menuBGChangedNight && time >= 27000.0)
                     {
                         moonType = rand.Next(9);
                         menuBGChangedNight = true;
                         int treeBG = WorldGen.treeBG1;
                         WorldGen.RandomizeBackgrounds(rand);
                         WorldGen.setBG(0, treeBG);
                     }
                 }
                 else
                 {
                     menuBGChangedDay = true;
                     menuBGChangedNight = true;
                 }
             }
             if (alreadyGrabbingSunOrMoon)
             {
                 return;
             }
             if (WorldGen.drunkWorldGen && !WorldGen.remixWorldGen)
             {
                 time -= 6.0;
                 if (dayTime)
                 {
                     time -= 1000.0;
                 }
                 if (time < 0.0)
                 {
                     time = 32400.0;
                     dayTime = false;
                 }
             }
             else if (dayTime)
             {
                 time += 33.88235294117647;
             }
             else
             {
                 time += 30.857142857142858;
             }
             if (!dayTime)
             {
                 if (time > 32400.0)
                 {
                     bloodMoon = false;
                     time = 0.0;
                     dayTime = true;
                     if (starGame)
                     {
                         dayTime = false;
                     }
                     moonPhase++;
                     if (moonPhase >= 7)
                     {
                         moonPhase = 0;
                     }
                 }
             }
             else if (time > 54000.0)
             {
                 time = 0.0;
                 dayTime = false;
             }
         }
         else if (netMode == 1)
         {
             UpdateTime();
         }
     }
References alreadyGrabbingSunOrMoon, bloodMoon, InGameNotificationsTracker.Clear(), WorldGen.corruptBG, dayTime, WorldGen.drunkWorldGen, WorldGen.drunkWorldGenText, exitScale, Star.Fall(), gameMenu, gamePaused, WorldGen.gen, GraveyardVisualIntensity, hasFocus, instance, Game.IsActive, lightning, lightningSpeed, lockMenuBGChange, menuBGChangedDay, menuBGChangedNight, menuMode, moonPhase, moonType, netMode, UnifiedRandom.Next(), numClouds, numStars, playerInventory, rand, WorldGen.RandomizeBackgrounds(), remixWorld, WorldGen.remixWorldGen, screenPosition, WorldGen.setBG(), star, starGame, statusText, thunderDelay, time, WorldGen.treeBG1, treeBGSet1, and UpdateTime().
Referenced by DoUpdate().