Terraria: Main.ShouldNormalEventsBeAbleToStart
ShouldNormalEventsBeAbleToStart()
static bool Main.ShouldNormalEventsBeAbleToStart () inline static
     {
         if (!NPC.LunarApocalypseIsUp && !NPC.AnyNPCs(398) && NPC.MoonLordCountdown <= 0)
         {
             return LanternNight.LanternsUp;
         }
         return true;
     }
References NPC.AnyNPCs(), LanternNight.LanternsUp, NPC.LunarApocalypseIsUp, and NPC.MoonLordCountdown.
Referenced by SkipToTime(), and UpdateTime().