Terraria: Main.DrawNPCs
DrawNPCs()
void Main.DrawNPCs (bool behindTiles = false) inline protected
     {
         bool flag = false;
         Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle((int)screenPosition.X - 800, (int)screenPosition.Y - 800, screenWidth + 1600, screenHeight + 1600);
         for (int num = 199; num >= 0; num--)
         {
             try
             {
                 if (npc[num].active && npc[num].type > 0 && npc[num].type < NPCID.Count && !npc[num].hide)
                 {
                     npc[num].position += npc[num].netOffset;
                     if (npc[num].behindTiles == behindTiles)
                     {
                         if (npc[num].type == 125 || npc[num].type == 126)
{
                             if (!NPC.IsMechQueenUp && !flag)
{
                                 flag = true;
                                 for (int i = 0; i < 200; i++)
{
                                     if (!npc[i].active || num == i || (npc[i].type != 125 && npc[i].type != 126))
{
                                         continue;
                                     }
                                     float scale = npc[i].scale;
                                     float x = npc[i].Center.X;
                                     float num2 = npc[i].Bottom.Y - (float)npc[i].height * 0.5f * scale;
                                     float x2 = npc[num].Center.X;
                                     float y = npc[num].Bottom.Y - (float)npc[num].height * 0.5f * scale;
                                     Vector2 vector = new Vector2(x2, y);
                                     float num3 = x - vector.X;
                                     float num4 = num2 - vector.Y;
                                     float rotation = (float)Math.Atan2(num4, num3) - 1.57f;
                                     bool flag2 = true;
                                     float num5 = (float)Math.Sqrt(num3 * num3 + num4 * num4);
                                     if (num5 > 2000f)
{
                                         flag2 = false;
                                     }
                                     float num6 = 40f * scale;
                                     while (flag2)
{
                                         num5 = (float)Math.Sqrt(num3 * num3 + num4 * num4);
                                         if (num5 < num6)
{
                                             flag2 = false;
                                             continue;
                                         }
                                         num5 = (float)TextureAssets.Chain12.Height() * scale / num5;
                                         num3 *= num5;
                                         num4 *= num5;
                                         vector.X += num3;
                                         vector.Y += num4;
                                         num3 = x - vector.X;
                                         num4 = num2 - vector.Y;
                                         Microsoft.Xna.Framework.Color color = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f));
                                         spriteBatch.Draw(TextureAssets.Chain12.Value, new Vector2(vector.X - screenPosition.X, vector.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain12.Width(), TextureAssets.Chain12.Height()), color, rotation, new Vector2((float)TextureAssets.Chain12.Width() * 0.5f, (float)TextureAssets.Chain12.Height() * 0.5f), scale, SpriteEffects.None, 0f);
                                     }
                                 }
                             }
                         }
                         else if (npc[num].type == 263 && npc[num].aiStyle == 52 && NPC.plantBoss >= 0)
{
                             Vector2 vector2 = new Vector2(npc[num].position.X + (float)(npc[num].width / 2), npc[num].position.Y + (float)(npc[num].height / 2));
                             float num7 = npc[NPC.plantBoss].Center.X - vector2.X;
                             float num8 = npc[NPC.plantBoss].Center.Y - vector2.Y;
                             float rotation2 = (float)Math.Atan2(num8, num7) - 1.57f;
                             bool flag3 = true;
                             while (flag3)
{
                                 int num9 = 16;
                                 int num10 = 32;
                                 float num11 = (float)Math.Sqrt(num7 * num7 + num8 * num8);
                                 if (num11 < (float)num10)
{
                                     num9 = (int)num11 - num10 + num9;
                                     flag3 = false;
                                 }
                                 num11 = (float)num9 / num11;
                                 num7 *= num11;
                                 num8 *= num11;
                                 vector2.X += num7;
                                 vector2.Y += num8;
                                 num7 = npc[NPC.plantBoss].Center.X - vector2.X + npc[NPC.plantBoss].netOffset.X;
                                 num8 = npc[NPC.plantBoss].Center.Y - vector2.Y + npc[NPC.plantBoss].netOffset.Y;
                                 Microsoft.Xna.Framework.Color color2 = Lighting.GetColor((int)vector2.X / 16, (int)(vector2.Y / 16f));
                                 spriteBatch.Draw(TextureAssets.Chain26.Value, new Vector2(vector2.X - screenPosition.X, vector2.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain26.Width(), num9), color2, rotation2, new Vector2((float)TextureAssets.Chain26.Width() * 0.5f, (float)TextureAssets.Chain26.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                             }
                         }
                         else if (npc[num].type == 264 && npc[num].aiStyle == 53 && NPC.plantBoss >= 0)
{
                             int num12 = NPC.plantBoss;
                             if (npc[num].ai[3] > 0f)
{
                                 num12 = (int)npc[num].ai[3] - 1;
                             }
                             Vector2 vector3 = new Vector2(npc[num].position.X + (float)(npc[num].width / 2), npc[num].position.Y + (float)(npc[num].height / 2));
                             float num13 = npc[num12].Center.X - vector3.X;
                             float num14 = npc[num12].Center.Y - vector3.Y;
                             float rotation3 = (float)Math.Atan2(num14, num13) - 1.57f;
                             bool flag4 = true;
                             while (flag4)
{
                                 int num15 = 16;
                                 int num16 = 32;
                                 float num17 = (float)Math.Sqrt(num13 * num13 + num14 * num14);
                                 if (num17 < (float)num16)
{
                                     num15 = (int)num17 - num16 + num15;
                                     flag4 = false;
                                 }
                                 num17 = (float)num15 / num17;
                                 num13 *= num17;
                                 num14 *= num17;
                                 vector3.X += num13;
                                 vector3.Y += num14;
                                 num13 = npc[num12].Center.X - vector3.X + npc[num12].netOffset.X;
                                 num14 = npc[num12].Center.Y - vector3.Y + npc[num12].netOffset.Y;
                                 Microsoft.Xna.Framework.Color color3 = Lighting.GetColor((int)vector3.X / 16, (int)(vector3.Y / 16f));
                                 spriteBatch.Draw(TextureAssets.Chain27.Value, new Vector2(vector3.X - screenPosition.X, vector3.Y - screenPosition.Y), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Chain27.Width(), num15), color3, rotation3, new Vector2((float)TextureAssets.Chain27.Width() * 0.5f, (float)TextureAssets.Chain27.Height() * 0.5f), 1f, SpriteEffects.None, 0f);
                             }
                         }
                         if (NPCID.Sets.MustAlwaysDraw[npc[num].type] || rectangle.Intersects(new Microsoft.Xna.Framework.Rectangle((int)npc[num].position.X, (int)npc[num].position.Y, npc[num].width, npc[num].height)))
{
                             DrawNPCCheckAlt(npc[num]);
                             DrawNPC(num, behindTiles);
                         }
                     }
                     npc[num].position -= npc[num].netOffset;
                 }
             }
             catch
             {
                 npc[num].active = false;
             }
         }
     }
References Entity.active, Entity.Bottom, Entity.Center, TextureAssets.Chain12, TextureAssets.Chain26, TextureAssets.Chain27, NPCID.Count, DrawNPC(), DrawNPCCheckAlt(), Lighting.GetColor(), Entity.height, NPC.hide, NPC.IsMechQueenUp, NPCID.Sets.MustAlwaysDraw, NPC.netOffset, npc, NPC.plantBoss, Entity.position, NPC.scale, screenHeight, screenPosition, screenWidth, spriteBatch, NPC.type, Asset< T >.Value, and Entity.width.
Referenced by DoDraw_DrawNPCsBehindTiles(), DoDraw_DrawNPCsOverTiles(), and DrawCapture().