Terraria: Main.UpdateOceanWaterLineForAmbience
UpdateOceanWaterLineForAmbience()
void Main.UpdateOceanWaterLineForAmbience () inline private
     {
         int num = DrawSurfaceBG_GetLayerYOffset(oceanBG);
         int num2 = 0;
         switch (oceanBG)
         {
         case 28:
         case 110:
         case 111:
         case 209:
         case 210:
             num2 = 102;
             break;
         case 283:
             num2 = 124;
             break;
         }
         float yScreenPosition = (float)(bgTopY + num) + (float)num2 * bgScale;
         AmbientSkyDrawCache.Instance.SetOceanLineInfo(yScreenPosition, bgAlphaFarBackLayer[3]);
     }
References bgAlphaFarBackLayer, bgScale, bgTopY, DrawSurfaceBG_GetLayerYOffset(), AmbientSkyDrawCache.Instance, oceanBG, and AmbientSkyDrawCache.SetOceanLineInfo().
Referenced by DrawSurfaceBG_BackMountainsStep2().