Terraria: Main.DrawProjectiles
DrawProjectiles()
void Main.DrawProjectiles () inline protected
     {
         PlayerInput.SetZoom_MouseInWorld();
         spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, null, Transform);
         int num = 0;
         CurrentDrawnEntity = null;
         CurrentDrawnEntityShader = 0;
         if (ignoreErrors)
         {
             for (int i = 0; i < 1000; i++)
             {
                 if (projectile[i].active && projectile[i].type > 0 && !projectile[i].hide)
                 {
                     num++;
                     try
                     {
                         DrawProj(i);
                     }
                     catch (Exception e)
                     {
                         TimeLogger.DrawException(e);
                         projectile[i].active = false;
                     }
                 }
             }
         }
         else
         {
             for (int j = 0; j < 1000; j++)
             {
                 if (projectile[j].active && projectile[j].type > 0 && !projectile[j].hide)
                 {
                     DrawProj(j);
                 }
             }
         }
         CurrentDrawnEntity = null;
         CurrentDrawnEntityShader = 0;
         spriteBatch.End();
         TimeLogger.DetailedDrawTime(20);
     }
References Entity.active, CurrentDrawnEntity, CurrentDrawnEntityShader, DefaultSamplerState, TimeLogger.DetailedDrawTime(), TimeLogger.DrawException(), DrawProj(), ignoreErrors, projectile, Rasterizer, PlayerInput.SetZoom_MouseInWorld(), spriteBatch, and Transform.
Referenced by DoDraw(), and DrawCapture().