Terraria: Main.EnsureRenderTargetContent
EnsureRenderTargetContent()
void Main.EnsureRenderTargetContent () inline protected
     {
         if (waterTarget == null || waterTarget.IsContentLost || backWaterTarget == null || backWaterTarget.IsContentLost || blackTarget == null || blackTarget.IsContentLost || tileTarget == null || tileTarget.IsContentLost || tile2Target == null || tile2Target.IsContentLost || wallTarget == null || wallTarget.IsContentLost || backgroundTarget == null || backgroundTarget.IsContentLost || screenTarget == null || screenTarget.IsContentLost || screenTargetSwap == null || screenTargetSwap.IsContentLost)
         {
             InitTargets();
         }
     }
References backgroundTarget, backWaterTarget, blackTarget, InitTargets(), screenTarget, screenTargetSwap, tile2Target, tileTarget, wallTarget, and waterTarget.
Referenced by Draw(), and SetGraphicsProfileInternal().