Terraria: Main.DrawBestiaryIcon
DrawBestiaryIcon()
static void Main.DrawBestiaryIcon (int pivotTopLeftX, int pivotTopLeftY) inline static private
     {
         inventoryScale = 0.85f;
         int num = (int)((float)(450 + pivotTopLeftX) - 56f * inventoryScale * 2f);
         int num2 = 258 + pivotTopLeftY;
         int num3 = 244;
         int width = 30;
         int num4 = 30;
         num3 = 244;
         num = 498;
         num2 = num3 + num4 + 4;
         if ((player[myPlayer].chest != -1 || npcShop > 0) && !recBigList)
         {
             num2 += 168;
             inventoryScale = 0.755f;
             num += 5;
             num3 += 24;
         }
         if (editChest)
         {
             num2 += 24;
         }
         Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(num, num2, (int)((float)TextureAssets.InventoryBack.Width() * inventoryScale), (int)((float)TextureAssets.InventoryBack.Height() * inventoryScale));
         rectangle = new Microsoft.Xna.Framework.Rectangle(num, num2, width, num4);
         bool flag = false;
         if (rectangle.Contains(new Microsoft.Xna.Framework.Point(mouseX, mouseY)) && !PlayerInput.IgnoreMouseInterface)
         {
             player[myPlayer].mouseInterface = true;
             flag = true;
             if (mouseLeft && mouseLeftRelease)
             {
                 player[myPlayer].SetTalkNPC(-1);
                 npcChatCornerItem = 0;
                 npcChatText = "";
                 mouseLeftRelease = false;
                 SoundEngine.PlaySound(12);
                 IngameFancyUI.OpenUIState(BestiaryUI);
                 BestiaryUI.OnOpenPage();
             }
         }
         Texture2D value = TextureAssets.BestiaryMenuButton.Value;
         Vector2 position = rectangle.Center.ToVector2();
         Microsoft.Xna.Framework.Rectangle rectangle2 = value.Frame(2, 1, flag ? 1 : 0);
         rectangle2.Width -= 2;
         rectangle2.Height -= 2;
         Vector2 origin = rectangle2.Size() / 2f;
         Microsoft.Xna.Framework.Color white = Microsoft.Xna.Framework.Color.White;
         spriteBatch.Draw(value, position, rectangle2, white, 0f, origin, 1f, SpriteEffects.None, 0f);
         UILinkPointNavigator.SetPosition(310, position);
         if (!mouseText && flag)
         {
             instance.MouseText(Language.GetTextValue("GameUI.Bestiary"), 0, 0);
         }
     }
References TextureAssets.BestiaryMenuButton, BestiaryUI, chest, editChest, Language.GetTextValue(), PlayerInput.IgnoreMouseInterface, instance, TextureAssets.InventoryBack, inventoryScale, Player.mouseInterface, mouseLeft, mouseLeftRelease, mouseText, MouseText(), mouseX, mouseY, myPlayer, npcChatCornerItem, npcChatText, npcShop, UIBestiaryTest.OnOpenPage(), IngameFancyUI.OpenUIState(), player, SoundEngine.PlaySound(), recBigList, UILinkPointNavigator.SetPosition(), Player.SetTalkNPC(), spriteBatch, and Asset< T >.Value.
Referenced by DrawInventory().