Terraria: Main.DrawPlayerChat
DrawPlayerChat()
void Main.DrawPlayerChat () inline protected
     {
         TextSnippet[] array = null;
         if (drawingPlayerChat)
         {
             PlayerInput.WritingText = true;
         }
         HandleIME();
         if (drawingPlayerChat)
         {
             textBlinkerCount++;
             if (textBlinkerCount >= 20)
             {
                 if (textBlinkerState == 0)
                 {
                     textBlinkerState = 1;
                 }
                 else
                 {
                     textBlinkerState = 0;
                 }
                 textBlinkerCount = 0;
             }
             string text = chatText;
             if (screenWidth > 800)
             {
                 int num = screenWidth - 300;
                 int num2 = 78;
                 spriteBatch.Draw(TextureAssets.TextBack.Value, new Vector2(num2, screenHeight - 36), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.TextBack.Width() - 100, TextureAssets.TextBack.Height()), new Microsoft.Xna.Framework.Color(100, 100, 100, 100), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                 num -= 400;
                 num2 += 400;
                 while (num > 0)
                 {
                     if (num > 300)
                     {
                         spriteBatch.Draw(TextureAssets.TextBack.Value, new Vector2(num2, screenHeight - 36), new Microsoft.Xna.Framework.Rectangle(100, 0, TextureAssets.TextBack.Width() - 200, TextureAssets.TextBack.Height()), new Microsoft.Xna.Framework.Color(100, 100, 100, 100), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                         num -= 300;
                         num2 += 300;
                     }
                     else
                     {
                         spriteBatch.Draw(TextureAssets.TextBack.Value, new Vector2(num2, screenHeight - 36), new Microsoft.Xna.Framework.Rectangle(TextureAssets.TextBack.Width() - num, 0, TextureAssets.TextBack.Width() - (TextureAssets.TextBack.Width() - num), TextureAssets.TextBack.Height()), new Microsoft.Xna.Framework.Color(100, 100, 100, 100), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                         num = 0;
                     }
                 }
             }
             else
             {
                 spriteBatch.Draw(TextureAssets.TextBack.Value, new Vector2(78f, screenHeight - 36), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.TextBack.Width(), TextureAssets.TextBack.Height()), new Microsoft.Xna.Framework.Color(100, 100, 100, 100), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
             }
             int hoveredSnippet = -1;
             List<TextSnippet> list = ChatManager.ParseMessage(text, Microsoft.Xna.Framework.Color.White);
             string compositionString = Platform.Get<IImeService>().CompositionString;
             if (compositionString != null && compositionString.Length > 0)
             {
                 list.Add(new TextSnippet(compositionString, new Microsoft.Xna.Framework.Color(255, 240, 20)));
             }
             if (textBlinkerState == 1)
             {
                 list.Add(new TextSnippet("|", Microsoft.Xna.Framework.Color.White));
             }
             array = list.ToArray();
             ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, array, new Vector2(88f, screenHeight - 30), 0f, Vector2.Zero, Vector2.One, out hoveredSnippet);
             if (hoveredSnippet > -1)
             {
                 array[hoveredSnippet].OnHover();
                 if (mouseLeft && mouseLeftRelease)
                 {
                     array[hoveredSnippet].OnClick();
                 }
             }
         }
         chatMonitor.DrawChat(drawingPlayerChat);
         if (drawingPlayerChat && array != null)
         {
             Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, array, Vector2.Zero);
             DrawWindowsIMEPanel(new Vector2(88f, screenHeight - 30) + new Vector2(stringSize.X + 10f, -6f));
         }
         TimeLogger.DetailedDrawTime(10);
     }
References chatMonitor, chatText, TimeLogger.DetailedDrawTime(), IChatMonitor.DrawChat(), ChatManager.DrawColorCodedStringWithShadow(), drawingPlayerChat, DrawWindowsIMEPanel(), ChatManager.GetStringSize(), HandleIME(), mouseLeft, mouseLeftRelease, FontAssets.MouseText, TextSnippet.OnClick(), TextSnippet.OnHover(), ChatManager.ParseMessage(), screenHeight, screenWidth, spriteBatch, TextureAssets.TextBack, textBlinkerCount, textBlinkerState, Asset< T >.Value, and PlayerInput.WritingText.
Referenced by DoDraw(), and DrawInterface_34_PlayerChat().