Terraria: Main.DrawWhip
DrawWhip()
void Main.DrawWhip (Projectile proj) inline private
     {
         List<Vector2> list = new List<Vector2>();
         Projectile.FillWhipControlPoints(proj, list);
         Texture2D value = TextureAssets.FishingLine.Value;
         Microsoft.Xna.Framework.Rectangle value2 = value.Frame();
         Vector2 origin = new Vector2(value2.Width / 2, 2f);
         Microsoft.Xna.Framework.Color originalColor = Microsoft.Xna.Framework.Color.White;
         switch (proj.type)
         {
         case 847:
             originalColor = Microsoft.Xna.Framework.Color.OrangeRed;
             break;
         case 849:
             originalColor = Microsoft.Xna.Framework.Color.SlateBlue;
             originalColor = Microsoft.Xna.Framework.Color.Black;
             break;
         case 848:
             originalColor = Microsoft.Xna.Framework.Color.DarkBlue;
             break;
         case 912:
             originalColor = Microsoft.Xna.Framework.Color.LightBlue;
             break;
         case 913:
             originalColor = Microsoft.Xna.Framework.Color.Firebrick;
             break;
         case 914:
             originalColor = Microsoft.Xna.Framework.Color.ForestGreen;
             break;
         case 915:
             originalColor = Microsoft.Xna.Framework.Color.White;
             break;
         case 952:
             originalColor = Microsoft.Xna.Framework.Color.Tan;
             break;
         }
         Vector2 vector = list[0];
         for (int i = 0; i < list.Count - 1; i++)
         {
             Vector2 vector2 = list[i];
             Vector2 vector3 = list[i + 1] - vector2;
             float rotation = vector3.ToRotation() - (float)Math.PI / 2f;
             Microsoft.Xna.Framework.Color color = Lighting.GetColor(vector2.ToTileCoordinates(), originalColor);
             Vector2 scale = new Vector2(1f, (vector3.Length() + 2f) / (float)value2.Height);
             spriteBatch.Draw(value, vector - screenPosition, value2, color, rotation, origin, scale, SpriteEffects.None, 0f);
             vector += vector3;
         }
         switch (proj.type)
         {
         case 847:
             vector = DrawWhip_WhipSword(proj, list);
             break;
         case 841:
             vector = DrawWhip_WhipBland(proj, list);
             break;
         case 848:
             vector = DrawWhip_WhipMace(proj, list);
             break;
         case 849:
             vector = DrawWhip_WhipScythe(proj, list);
             break;
         case 912:
             vector = DrawWhip_CoolWhip(proj, list);
             break;
         case 913:
             vector = DrawWhip_FireWhip(proj, list);
             break;
         case 914:
             vector = DrawWhip_ThornWhip(proj, list);
             break;
         case 915:
             vector = DrawWhip_RainbowWhip(proj, list);
             break;
         case 952:
             vector = DrawWhip_BoneWhip(proj, list);
             break;
         }
     }
References DrawWhip_BoneWhip(), DrawWhip_CoolWhip(), DrawWhip_FireWhip(), DrawWhip_RainbowWhip(), DrawWhip_ThornWhip(), DrawWhip_WhipBland(), DrawWhip_WhipMace(), DrawWhip_WhipScythe(), DrawWhip_WhipSword(), Projectile.FillWhipControlPoints(), TextureAssets.FishingLine, Lighting.GetColor(), screenPosition, spriteBatch, Projectile.type, and Asset< T >.Value.
Referenced by DrawProjDirect().