Terraria: Main.startSnowMoon
startSnowMoon()
static void Main.startSnowMoon () inline static
     {
         snowMoon = true;
         pumpkinMoon = false;
         bloodMoon = false;
         invasionProgress = -1;
         invasionProgressDisplayLeft = 0;
         invasionProgressAlpha = 0f;
         invasionProgressIcon = 0;
         if (netMode != 1)
         {
             NPC.totalInvasionPoints = 0f;
             NPC.waveKills = 0f;
             NPC.waveNumber = 1;
             NetworkText invasionWaveText = Lang.GetInvasionWaveText(1, 338, 342);
             if (netMode == 0)
             {
                 NewText(invasionWaveText.ToString(), 175, 75);
             }
             else if (netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(invasionWaveText, new Microsoft.Xna.Framework.Color(175, 75, 255));
             }
         }
     }
References bloodMoon, ChatHelper.BroadcastChatMessage(), Lang.GetInvasionWaveText(), invasionProgress, invasionProgressAlpha, invasionProgressDisplayLeft, invasionProgressIcon, netMode, NewText(), pumpkinMoon, snowMoon, NetworkText.ToString(), NPC.totalInvasionPoints, NPC.waveKills, and NPC.waveNumber.
Referenced by MessageBuffer.GetData(), and Player.ItemCheck_UseEventItems().