Terraria: Main.GetPlayerPathFromName
GetPlayerPathFromName()
static string Main.GetPlayerPathFromName (string playerName, bool cloudSave) inline static
     {
         char[] invalidFileNameChars = Path.GetInvalidFileNameChars();
         string text = "";
         playerName = playerName.Replace(".", "_");
         playerName = playerName.Replace("*", "_");
         foreach (char c in playerName)
         {
             text += ((!invalidFileNameChars.Contains(c)) ? ((c != ' ') ? c : '_') : '-');
         }
         string text2 = (cloudSave ? CloudPlayerPath : PlayerPath);
         if (FileUtilities.GetFullPath(text2 + Path.DirectorySeparatorChar + text + ".plr", cloudSave).StartsWith("\\\\.\\", StringComparison.Ordinal))
         {
             text += "_";
         }
         if (FileUtilities.Exists(text2 + Path.DirectorySeparatorChar + text + ".plr", cloudSave))
         {
             int num = 2;
             while (FileUtilities.Exists(text2 + Path.DirectorySeparatorChar.ToString() + text + num + ".plr", cloudSave))
             {
                 num++;
             }
             text += num;
         }
         return text2 + Path.DirectorySeparatorChar + text + ".plr";
     }
References CloudPlayerPath, FileUtilities.Exists(), FileUtilities.GetFullPath(), and PlayerPath.
Referenced by PlayerFileData.CreateAndSave(), PlayerFileData.MoveToCloud(), and PlayerFileData.MoveToLocal().