Terraria: Main.DrawLoadoutButtons
DrawLoadoutButtons()
static void Main.DrawLoadoutButtons (int inventoryTop, bool demonHeartSlotAvailable, bool masterModeSlotAvailable) inline static private
     {
         int num = 10;
         Player player = Main.player[myPlayer];
         if (!demonHeartSlotAvailable)
         {
             num--;
         }
         if (!masterModeSlotAvailable)
         {
             num--;
         }
         int x = screenWidth - 58 + 14;
         int num2 = (int)((float)(inventoryTop - 2) + 0f * inventoryScale);
         int num3 = (int)((float)(inventoryTop - 2) + (float)(num * 56) * inventoryScale);
         Texture2D value = TextureAssets.Extra[259].Value;
         Microsoft.Xna.Framework.Rectangle rectangle = new Microsoft.Xna.Framework.Rectangle(x, num2 + 2, 4, num3 - num2);
         ItemSlot.GetLoadoutColor(player.CurrentLoadoutIndex);
         int num4 = player.Loadouts.Length;
         int num5 = 32;
         int num6 = 4;
         int num7 = -1;
         _ = FontAssets.ItemStack.Value;
         for (int i = 0; i < num4; i++)
         {
             Microsoft.Xna.Framework.Rectangle rectangle2 = new Microsoft.Xna.Framework.Rectangle(rectangle.X + rectangle.Width, rectangle.Y + (num5 + num6) * i, 32, num5);
             Microsoft.Xna.Framework.Color loadoutColor = ItemSlot.GetLoadoutColor(i);
             _ = player.Loadouts[i];
             int frameX = ((i == player.CurrentLoadoutIndex) ? 1 : 0);
             bool flag = false;
             if (rectangle2.Contains(MouseScreen.ToPoint()))
             {
                 flag = true;
                 loadoutColor = Microsoft.Xna.Framework.Color.Lerp(loadoutColor, Microsoft.Xna.Framework.Color.White, 0.8f);
                 player.mouseInterface = true;
                 if (!mouseText)
                 {
                     instance.MouseText(Language.GetTextValue("UI.Loadout" + (i + 1)), 0, 0);
                     mouseText = true;
                 }
                 if (mouseLeft && mouseLeftRelease)
                 {
                     player.TrySwitchingLoadout(i);
                 }
             }
             Microsoft.Xna.Framework.Rectangle rectangle3 = value.Frame(3, 3, frameX, i);
             spriteBatch.Draw(value, rectangle2.Center.ToVector2(), rectangle3, Microsoft.Xna.Framework.Color.White, 0f, rectangle3.Size() / 2f, 1f, SpriteEffects.None, 0f);
             if (flag)
             {
                 rectangle3 = value.Frame(3, 3, 2, i);
                 spriteBatch.Draw(value, rectangle2.Center.ToVector2(), rectangle3, OurFavoriteColor, 0f, rectangle3.Size() / 2f, 1f, SpriteEffects.None, 0f);
             }
             UILinkPointNavigator.SetPosition(312 + i, rectangle2.Center.ToVector2());
         }
         if (_lastHoveredLoadoutIndex != num7)
         {
             _lastHoveredLoadoutIndex = num7;
             SoundEngine.PlaySound(12);
         }
     }
References _lastHoveredLoadoutIndex, Player.CurrentLoadoutIndex, TextureAssets.Extra, ItemSlot.GetLoadoutColor(), Language.GetTextValue(), instance, inventoryScale, FontAssets.ItemStack, Player.Loadouts, Player.mouseInterface, mouseLeft, mouseLeftRelease, MouseScreen, mouseText, MouseText(), myPlayer, OurFavoriteColor, player, SoundEngine.PlaySound(), screenWidth, UILinkPointNavigator.SetPosition(), spriteBatch, Player.TrySwitchingLoadout(), and Asset< T >.Value.
Referenced by DrawInventory().