Terraria: Main.DrawToMap_Section
DrawToMap_Section()
void Main.DrawToMap_Section (int secX, int secY) inline protected
     {
         Stopwatch stopwatch = Stopwatch.StartNew();
         Microsoft.Xna.Framework.Color[] mapColorCacheArray = _mapColorCacheArray;
         int num = secX * 200;
         int num2 = num + 200;
         int num3 = secY * 150;
         int num4 = num3 + 150;
         int num5 = num / textureMaxWidth;
         int num6 = num3 / textureMaxHeight;
         int num7 = num % textureMaxWidth;
         int num8 = num3 % textureMaxHeight;
         if (!checkMap(num5, num6))
         {
             return;
         }
         int num9 = 0;
         _ = Microsoft.Xna.Framework.Color.Transparent;
         for (int i = num3; i < num4; i++)
         {
             for (int j = num; j < num2; j++)
             {
                 MapTile mapTile = Map[j, i];
                 mapColorCacheArray[num9] = MapHelper.GetMapTileXnaColor(ref mapTile);
                 num9++;
             }
         }
         try
         {
             base.GraphicsDevice.SetRenderTarget(mapTarget[num5, num6]);
         }
         catch (ObjectDisposedException)
         {
             initMap[num5, num6] = false;
             return;
         }
         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
         double totalMilliseconds = stopwatch.Elapsed.TotalMilliseconds;
         mapSectionTexture.SetData(mapColorCacheArray, 0, mapColorCacheArray.Length);
         _ = stopwatch.Elapsed.TotalMilliseconds;
         totalMilliseconds = stopwatch.Elapsed.TotalMilliseconds;
         spriteBatch.Draw(mapSectionTexture, new Vector2(num7, num8), Microsoft.Xna.Framework.Color.White);
         spriteBatch.End();
         base.GraphicsDevice.SetRenderTarget(null);
         _ = stopwatch.Elapsed.TotalMilliseconds;
         stopwatch.Stop();
     }
References _mapColorCacheArray, checkMap(), MapHelper.GetMapTileXnaColor(), initMap, Map, mapSectionTexture, mapTarget, spriteBatch, textureMaxHeight, and textureMaxWidth.
Referenced by DoDraw().