Terraria: Main.DrawMiscMapIcons
DrawMiscMapIcons()
void Main.DrawMiscMapIcons (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Microsoft.Xna.Framework.Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
     {
         DrawMapIcons_PotionOfReturnHomePosition(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
         DrawMapIcons_PotionOfReturnAppearAfterUsePosition(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
         DrawMapIcons_LastGolfballHit(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
     }
References DrawMapIcons_LastGolfballHit(), DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), DrawMapIcons_PotionOfReturnHomePosition(), and spriteBatch.
Referenced by DrawMap().