Terraria: Main.SetDisplayMode
SetDisplayMode()
static void Main.SetDisplayMode (int width, int height, bool fullscreen) inline static
     {
         bool flag = false;
         Form form = null;
         if (Platform.IsWindows)
         {
             form = (Form)Control.FromHandle(instance.Window.Handle);
             screenMaximized = form.WindowState == FormWindowState.Maximized;
             if (screenBorderless && screenMaximized && !graphics.IsFullScreen)
             {
                 screenMaximized = false;
                 form.WindowState = FormWindowState.Normal;
             }
             flag = form.FormBorderStyle == FormBorderStyle.None;
         }
         else
         {
             screenMaximized = false;
         }
         bool flag2 = false;
         int num3;
         int num4;
         if (screenBorderless || screenMaximized || graphics.IsFullScreen || fullscreen)
         {
             bool flag3 = false;
             if (PlayerInput.SteamDeckIsUsed)
             {
                 flag3 = true;
                 if (!fullscreen && !graphics.IsFullScreen)
                 {
                     width = 1280;
                     height = 800;
                     TryPickingDefaultUIScale(800f);
                 }
             }
             if (Platform.IsWindows)
             {
                 form.MinimumSize = new Size(0, 0);
                 if (!fullscreen && !flag3)
                 {
                     SetDisplayModeAsBorderless(ref width, ref height, form);
                 }
             }
             if (width > maxScreenW)
             {
                 float num = (float)height / (float)width;
                 width = maxScreenW;
                 height = (int)(num * (float)width);
             }
             if (height > maxScreenH)
             {
                 float num2 = (float)width / (float)height;
                 height = maxScreenH;
                 width = (int)(num2 * (float)height);
             }
             PlayerInput.RawMouseScale = new Vector2((float)width / (float)instance.Window.ClientBounds.Width, (float)height / (float)instance.Window.ClientBounds.Height);
             if (!graphics.IsFullScreen)
             {
                 num3 = Math.Max(graphics.PreferredBackBufferWidth, graphics.GraphicsDevice.Viewport.Width);
                 num4 = Math.Max(graphics.PreferredBackBufferHeight, graphics.GraphicsDevice.Viewport.Height);
                 if (num3 != graphics.PreferredBackBufferWidth || num4 != graphics.PreferredBackBufferHeight)
                 {
                     flag2 = true;
                 }
             }
             else
             {
                 num3 = graphics.PreferredBackBufferWidth;
                 num4 = graphics.PreferredBackBufferHeight;
             }
         }
         else
         {
             PlayerInput.RawMouseScale = Vector2.One;
             if (Platform.IsWindows)
             {
                 form.MinimumSize = new Size(minScreenW, minScreenH);
                 if (flag)
                 {
                     width = displayWidth[0];
                     height = displayHeight[0];
                 }
             }
             width = Math.Min(width, maxScreenW);
             height = Math.Min(height, maxScreenH);
             num3 = graphics.GraphicsDevice.Viewport.Width;
             num4 = graphics.GraphicsDevice.Viewport.Height;
             flag2 = graphics.PreferredBackBufferWidth != graphics.GraphicsDevice.Viewport.Width || graphics.PreferredBackBufferHeight != graphics.GraphicsDevice.Viewport.Height;
         }
         if (Platform.IsWindows && !fullscreen && !flag2)
         {
             if (form.ClientSize.Width < graphics.PreferredBackBufferWidth)
             {
                 width = form.ClientSize.Width;
                 flag2 = true;
             }
             if (form.ClientSize.Height < graphics.PreferredBackBufferHeight)
             {
                 height = form.ClientSize.Height;
                 flag2 = true;
             }
         }
         width &= 0x7FFFFFFE;
         height &= 0x7FFFFFFE;
         width = Math.Max(width, minScreenW);
         height = Math.Max(height, minScreenH);
         if (graphics.IsFullScreen != fullscreen)
         {
             graphics.PreferredBackBufferWidth = width;
             graphics.PreferredBackBufferHeight = height;
             graphics.ApplyChanges();
             graphics.ToggleFullScreen();
         }
         if (width != num3 || height != num4 || flag2)
         {
             mapTime = 0;
             if (gamePaused)
             {
                 renderNow = true;
             }
             screenWidth = width;
             screenHeight = height;
             graphics.PreferredBackBufferWidth = screenWidth;
             graphics.PreferredBackBufferHeight = screenHeight;
             graphics.ApplyChanges();
             PlayerInput.CacheOriginalScreenDimensions();
             FixUIScale();
             if (Main.OnResolutionChanged != null)
             {
                 Main.OnResolutionChanged(new Vector2(screenWidth, screenHeight));
             }
             PendingResolutionWidth = screenWidth;
             PendingResolutionHeight = screenHeight;
             PlayerInput.CacheOriginalScreenDimensions();
             if (Platform.IsWindows && !fullscreen)
             {
                 if (screenBorderless)
                 {
                     ApplyBorderlessResolution(form);
                     form.FormBorderStyle = FormBorderStyle.None;
                 }
                 else
                 {
                     form.FormBorderStyle = FormBorderStyle.Sizable;
                 }
                 form.SendToBack();
                 form.BringToFront();
             }
             Lighting.Initialize();
             if (!drawToScreen && !_isResizingAndRemakingTargets)
             {
                 _isResizingAndRemakingTargets = true;
                 instance.InitTargets();
                 _isResizingAndRemakingTargets = false;
             }
             UserInterface.ActiveInstance.Recalculate();
             instance._needsMenuUIRecalculation = true;
             Console.WriteLine(Language.GetTextValue("Misc.ResolutionChanged", width, height));
             chatMonitor.OnResolutionChange();
         }
         if (!graphics.SynchronizeWithVerticalRetrace)
         {
             graphics.SynchronizeWithVerticalRetrace = true;
             graphics.ApplyChanges();
         }
     }
References _isResizingAndRemakingTargets, _needsMenuUIRecalculation, UserInterface.ActiveInstance, ApplyBorderlessResolution(), PlayerInput.CacheOriginalScreenDimensions(), chatMonitor, displayHeight, displayWidth, drawToScreen, FixUIScale(), gamePaused, Language.GetTextValue(), graphics, Lighting.Initialize(), InitTargets(), instance, Platform.IsWindows, mapTime, maxScreenH, maxScreenW, minScreenH, minScreenW, IChatMonitor.OnResolutionChange(), OnResolutionChanged, PendingResolutionHeight, PendingResolutionWidth, PlayerInput.RawMouseScale, UserInterface.Recalculate(), renderNow, screenBorderless, screenHeight, screenMaximized, screenWidth, SetDisplayModeAsBorderless(), PlayerInput.SteamDeckIsUsed, TryPickingDefaultUIScale(), and Game.Window.
Referenced by FullscreenStartup(), LoadSettings(), OpenLegacySettings(), SetFullScreen(), and SetResolution().