Terraria: Main.DoLightTiles
DoLightTiles()
void Main.DoLightTiles () inline private
     {
         GetAreaToLight(out firstTileX, out lastTileX, out firstTileY, out lastTileY);
         if (!drawSkip)
         {
             Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
         }
     }
References drawSkip, firstTileX, firstTileY, GetAreaToLight(), lastTileX, lastTileY, and Lighting.LightTiles().
Referenced by DoDraw().