Terraria: Main.GetPreferredBGStyleForPlayer
GetPreferredBGStyleForPlayer()
static int Main.GetPreferredBGStyleForPlayer () inline static
     {
         int num = bgStyle;
         int num2 = (int)((screenPosition.X + (float)(screenWidth / 2)) / 16f);
         if (WorldGen.oceanDepths((int)(screenPosition.X + (float)(screenWidth / 2)) / 16, (int)(screenPosition.Y + (float)(screenHeight / 2)) / 16))
         {
             num = (player[myPlayer].ZoneHallow ? 6 : (player[myPlayer].ZoneCorrupt ? ((SceneMetrics.BloodTileCount <= SceneMetrics.EvilTileCount) ? 1 : 8) : (player[myPlayer].ZoneCrimson ? 8 : ((SceneMetrics.HoneyBlockCount <= 400) ? 4 : 3))));
         }
         else if (player[myPlayer].ZoneGlowshroom)
         {
             num = 9;
         }
         else if (player[myPlayer].ZoneDesert)
         {
             num = (player[myPlayer].ZoneCorrupt ? 5 : (player[myPlayer].ZoneCrimson ? 5 : ((!player[myPlayer].ZoneHallow) ? 2 : 5)));
         }
         else if (player[myPlayer].ZoneHallow)
         {
             num = 6;
         }
         else if (player[myPlayer].ZoneCorrupt)
         {
             num = ((SceneMetrics.BloodTileCount <= SceneMetrics.EvilTileCount) ? 1 : 8);
         }
         else if (player[myPlayer].ZoneCrimson)
         {
             num = 8;
         }
         else if (player[myPlayer].ZoneJungle)
         {
             num = 3;
         }
         else if (player[myPlayer].ZoneSnow)
         {
             num = 7;
         }
         else
         {
             num = 0;
             if (num2 >= treeX[0])
             {
                 if (WorldGen.treeBG1 != WorldGen.treeBG2 && num2 < treeX[1])
                 {
                     num = 10;
                 }
                 else if (WorldGen.treeBG1 != WorldGen.treeBG3 && num2 < treeX[2])
                 {
                     num = 11;
                 }
                 else if (WorldGen.treeBG1 != WorldGen.treeBG4)
                 {
                     num = 12;
                 }
             }
         }
         return num;
     }
References bgStyle, SceneMetrics.BloodTileCount, SceneMetrics.EvilTileCount, SceneMetrics.HoneyBlockCount, myPlayer, WorldGen.oceanDepths(), player, screenHeight, screenPosition, screenWidth, WorldGen.treeBG1, WorldGen.treeBG2, WorldGen.treeBG3, WorldGen.treeBG4, treeX, Player.ZoneCorrupt, Player.ZoneCrimson, and Player.ZoneHallow.
Referenced by DrawBG(), and CaptureBiome.GetBiomeByLocation().