Terraria: Main.SaveSettings
SaveSettings()
static bool Main.SaveSettings () inline static
     {
         Preferences configuration = Configuration;
         configuration.Clear();
         configuration.Put("ResetDefaultUIScale", false);
         configuration.Put("SmartCursorToggle", cSmartCursorModeIsToggleAndNotHold);
         configuration.Put("MapEnabled", mapEnabled);
         configuration.Put("InvasionBarMode", invasionProgressMode);
         configuration.Put("AutoSave", autoSave);
         configuration.Put("AutoPause", autoPause);
         configuration.Put("Language", Language.ActiveCulture.Name);
         configuration.Put("PlacementPreview", placementPreview);
         configuration.Put("GoreVisualsAllowed", ChildSafety.Disabled);
         configuration.Put("WorldRollbacksToKeep", WorldRollingBackupsCountToKeep);
         configuration.Put("TeamNameplateDistance", teamNamePlateDistance);
         configuration.Put("MultiplayerNPCSmoothingRange", multiplayerNPCSmoothingRange);
         configuration.Put("VolumeSound", soundVolume);
         configuration.Put("VolumeAmbient", ambientVolume);
         configuration.Put("VolumeMusic", musicVolume);
         configuration.Put("UnlockMusicSwap", TOWMusicUnlocked);
         configuration.Put("UseExperimentalFeatures", UseExperimentalFeatures);
         configuration.Put("KeyFavoriteModifier", cFavoriteKey);
         configuration.Put("Fullscreen", graphics.IsFullScreen);
         configuration.Put("WindowMaximized", screenMaximized);
         configuration.Put("WindowBorderless", screenBorderless);
         int num = graphics.PreferredBackBufferWidth;
         int num2 = graphics.PreferredBackBufferHeight;
         if (IsInTheMiddleOfLoadingSettings)
         {
             if (LastLoadedResolution.X != 0)
             {
                 num = LastLoadedResolution.X;
             }
             if (LastLoadedResolution.Y != 0)
             {
                 num2 = LastLoadedResolution.Y;
             }
         }
         configuration.Put("DisplayWidth", num);
         configuration.Put("DisplayHeight", num2);
         configuration.Put("GraphicsQuality", qaStyle);
         configuration.Put("BackgroundEnabled", BackgroundEnabled);
         configuration.Put("FrameSkipMode", FrameSkipMode);
         configuration.Put("LightingMode", Lighting.Mode);
         configuration.Put("BackgroundParallax", bgScroll);
         configuration.Put("ShowItemText", showItemText);
         configuration.Put("LastLaunchedVersion", 279);
         configuration.Put("ClientUUID", clientUUID);
         configuration.Put("UseSmartCursorForCommonBlocks", Player.SmartCursorSettings.SmartBlocksEnabled);
         configuration.Put("UseSmartAxeAfterSmartPickaxe", Player.SmartCursorSettings.SmartAxeAfterPickaxe);
         configuration.Put("SmartCursorHoldCanReleaseMidUse", Player.SmartCursorSettings.SmartCursorHoldCanReleaseMidUse);
         configuration.Put("DisableLeftShiftTrashCan", ItemSlot.Options.DisableLeftShiftTrashCan);
         configuration.Put("DisableQuickTrash", ItemSlot.Options.DisableQuickTrash);
         configuration.Put("HighlightNewItems", ItemSlot.Options.HighlightNewItems);
         configuration.Put("HidePasswords", HidePassword);
         configuration.Put("ReverseUpDownForArmorSetBonuses", ReversedUpDownArmorSetBonuses);
         configuration.Put("MouseShowBuildingGrid", MouseShowBuildingGrid);
         configuration.Put("AllowUnfocusedInputOnGamepad", AllowUnfocusedInputOnGamepad);
         configuration.Put("LockOnPriority", LockOnHelper.UseMode);
         configuration.Put("InvisibleCursorForGamepad", InvisibleCursorForGamepad);
         configuration.Put("GamepadDisableInstructionsDisplay", GamepadDisableInstructionsDisplay);
         configuration.Put("SettingsUnlock_WorldEvil", SettingsUnlock_WorldEvil);
         configuration.Put("SettingsEnabled_MinersWobble", SettingsEnabled_MinersWobble);
         configuration.Put("SettingBlockGamepadsEntirely", SettingBlockGamepadsEntirely);
         configuration.Put("SettingsEnabled_OpaqueBoxBehindTooltips", SettingsEnabled_OpaqueBoxBehindTooltips);
         configuration.Put("SettingDontScaleMainMenuUp", SettingDontScaleMainMenuUp);
         configuration.Put("SettingsEnabled_TilesSwayInWind", SettingsEnabled_TilesSwayInWind);
         configuration.Put("SettingsEnabled_AutoReuseAllItems", SettingsEnabled_AutoReuseAllItems);
         configuration.Put("UseStormEffect", UseStormEffects);
         configuration.Put("UseHeatDistortion", UseHeatDistortion);
         configuration.Put("WaveQuality", WaveQuality);
         configuration.Put("Support4K", Support4K);
         configuration.Put("MouseColor", new Dictionary<string, byte>
         {
             { "R", mouseColor.R },
             { "G", mouseColor.G },
             { "B", mouseColor.B }
         });
         configuration.Put("MouseBorderColor", new Dictionary<string, byte>
         {
             { "R", MouseBorderColor.R },
             { "G", MouseBorderColor.G },
             { "B", MouseBorderColor.B },
             { "A", MouseBorderColor.A }
         });
         configuration.Put("QuickLaunch", SkipAssemblyLoad);
         configuration.Put("Zoom", GameZoomTarget);
         configuration.Put("UIScale", _uiScaleWanted);
         configuration.Put("MapScale", MapScale);
         configuration.Put("FlashIconForEvents", Enum.GetName(typeof(GameNotificationType), _flashNotificationType));
         configuration.Put("Display", _windowMover.ScreenDeviceName);
         configuration.Put("DisplayScreen", _windowMover.ScreenDeviceName);
         configuration.Put("ThrottleWhenInactive", instance.InactiveSleepTime != TimeSpan.Zero);
         configuration.Put("DoorAutoOpeningMode", DoorOpeningHelper.PreferenceSettings);
         configuration.Put("HoverControlMode", Player.Settings.HoverControl);
         configuration.Put("WaterfallDrawLimit", instance.waterfallManager.maxWaterfallCount);
         configuration.Put("DisableIntenseVisualEffects", DisableIntenseVisualEffects);
         if (Configuration.Save())
         {
             return PlayerInput.Save();
         }
         return false;
     }
References _flashNotificationType, _uiScaleWanted, _windowMover, Language.ActiveCulture, AllowUnfocusedInputOnGamepad, ambientVolume, autoPause, autoSave, BackgroundEnabled, bgScroll, cFavoriteKey, Preferences.Clear(), clientUUID, Configuration, cSmartCursorModeIsToggleAndNotHold, ChildSafety.Disabled, DisableIntenseVisualEffects, ItemSlot.Options.DisableLeftShiftTrashCan, ItemSlot.Options.DisableQuickTrash, GamepadDisableInstructionsDisplay, GameZoomTarget, graphics, HidePassword, ItemSlot.Options.HighlightNewItems, Player.Settings.HoverControl, Game.InactiveSleepTime, instance, invasionProgressMode, InvisibleCursorForGamepad, IsInTheMiddleOfLoadingSettings, LastLoadedResolution, mapEnabled, MapScale, WaterfallManager.maxWaterfallCount, Lighting.Mode, MouseBorderColor, mouseColor, MouseShowBuildingGrid, multiplayerNPCSmoothingRange, musicVolume, GameCulture.Name, placementPreview, DoorOpeningHelper.PreferenceSettings, Preferences.Put(), qaStyle, ReversedUpDownArmorSetBonuses, PlayerInput.Save(), Preferences.Save(), screenBorderless, WindowStateController.ScreenDeviceName, screenMaximized, SettingBlockGamepadsEntirely, SettingDontScaleMainMenuUp, SettingsEnabled_AutoReuseAllItems, SettingsEnabled_MinersWobble, SettingsEnabled_OpaqueBoxBehindTooltips, SettingsEnabled_TilesSwayInWind, SettingsUnlock_WorldEvil, showItemText, SkipAssemblyLoad, Player.SmartCursorSettings.SmartAxeAfterPickaxe, Player.SmartCursorSettings.SmartBlocksEnabled, Player.SmartCursorSettings.SmartCursorHoldCanReleaseMidUse, soundVolume, Support4K, teamNamePlateDistance, TOWMusicUnlocked, UseExperimentalFeatures, UseHeatDistortion, LockOnHelper.UseMode, UseStormEffects, waterfallManager, WaveQuality, and WorldRollingBackupsCountToKeep.
Referenced by IngameOptions.Close(), DrawMenu(), UIResourcePackSelectionMenu.HandleBackButtonUsage(), InitTargets(), LoadSettings(), QuitGame(), and UpdateSettingUnlocks().