Terraria: Main.UpdateTime
UpdateTime()
static void Main.UpdateTime () inline static private
     {
         if (LanternNight.LanternsUp)
         {
             cloudBGActive = 0f;
             if (numClouds > 30)
             {
                 numClouds = 30;
             }
         }
         if (ladyBugRainBoost > 0)
         {
             ladyBugRainBoost -= dayRate;
         }
         if (pumpkinMoon)
         {
             bloodMoon = false;
             snowMoon = false;
         }
         if (snowMoon)
         {
             bloodMoon = false;
         }
         if ((netMode != 1 && !gameMenu) || netMode == 2)
         {
             if (slimeRainTime > 0.0)
             {
                 slimeRainTime -= dayRate;
                 if (slimeRainTime <= 0.0)
                 {
                     StopSlimeRain();
                 }
             }
             else if (slimeRainTime < 0.0)
             {
                 slimeRainTime += dayRate;
                 if (slimeRainTime > 0.0)
                 {
                     slimeRainTime = 0.0;
                 }
             }
             if (raining)
             {
                 if (!CreativePowerManager.Instance.GetPower<CreativePowers.FreezeRainPower>().Enabled)
                 {
                     if (LanternNight.LanternsUp)
                     {
                         StopRain();
                     }
                     else
                     {
                         rainTime -= dayRate;
                         if (dayRate > 0)
{
                             int num = 86400 / dayRate / 24;
                             if (rainTime <= 0)
{
                                 StopRain();
                             }
                             else if (rand.Next(num * 2) == 0)
{
                                 ChangeRain();
                             }
                         }
                     }
                 }
             }
             else if (!slimeRain && !LanternNight.LanternsUp && !LanternNight.NextNightIsLanternNight)
             {
                 int num2 = 86400;
                 num2 /= ((dayRate == 0) ? 1 : dayRate);
                 if (!CreativePowerManager.Instance.GetPower<CreativePowers.FreezeRainPower>().Enabled && dayRate != 0)
                 {
                     if (rand.Next((int)((double)num2 * 5.75)) == 0)
                     {
                         StartRain();
                     }
                     else if (cloudBGActive >= 1f && rand.Next((int)((double)num2 * 4.25)) == 0)
                     {
                         StartRain();
                     }
                     else if (ladyBugRainBoost > 0 && rand.Next(num2) == 0)
                     {
                         StartRain();
                     }
                 }
                 if (!raining && !NPC.BusyWithAnyInvasionOfSorts() && dayTime && time < 27000.0 && dayRate > 0)
                 {
                     int num3 = (int)(450000.00000000006 / (double)dayRate);
                     if (!NPC.downedSlimeKing)
                     {
                         num3 /= 2;
                     }
                     if (hardMode)
                     {
                         num3 = (int)((double)num3 * 1.5);
                     }
                     bool flag = AnyPlayerReadyToFightKingSlime();
                     if (!flag)
                     {
                         num3 *= 5;
                     }
                     if (num3 > 0 && (flag || expertMode) && rand.Next(num3) == 0)
                     {
                         StartSlimeRain();
                     }
                 }
             }
         }
         if (maxRaining != oldMaxRaining)
         {
             if (netMode == 2)
             {
                 NetMessage.SendData(7);
             }
             oldMaxRaining = maxRaining;
         }
         UpdateTimeRate();
         double num4 = time;
         time += dayRate;
         CultistRitual.UpdateTime();
         BirthdayParty.UpdateTime();
         LanternNight.UpdateTime();
         Sandstorm.UpdateTime();
         DD2Event.UpdateTime();
         CreditsRollEvent.UpdateTime();
         WorldGen.mysticLogsEvent.UpdateTime();
         PylonSystem.Update();
         if (!dedServ)
         {
             if (NPC.MoonLordCountdown > 0)
             {
                 float num5 = MathHelper.Clamp((float)Math.Sin((float)NPC.MoonLordCountdown / 60f * 0.5f) * 2f, 0f, 1f);
                 num5 *= 0.75f - 0.5f * ((float)NPC.MoonLordCountdown / (float)NPC.MaxMoonLordCountdown);
                 if (!Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].IsActive())
                 {
                     Terraria.Graphics.Effects.Filters.Scene.Activate("MoonLordShake", Main.player[myPlayer].position);
                 }
                 Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].GetShader().UseIntensity(num5);
             }
             else if (Terraria.Graphics.Effects.Filters.Scene["MoonLordShake"].IsActive())
             {
                 Terraria.Graphics.Effects.Filters.Scene.Deactivate("MoonLordShake");
             }
         }
         if (NPC.MoonLordCountdown > 0)
         {
             NPC.MoonLordCountdown--;
             if (NPC.MoonLordCountdown <= 0 && netMode != 1)
             {
                 NPC.SpawnOnPlayer(Player.FindClosest(new Vector2(maxTilesX / 2, (float)worldSurface / 2f) * 16f, 0, 0), 398);
             }
         }
         if (NPC.taxCollector && netMode != 2 && !gameMenu)
         {
             Main.player[myPlayer].taxTimer += dayRate;
             if (Main.player[myPlayer].taxTimer >= Player.taxRate)
             {
                 Main.player[myPlayer].taxTimer -= Player.taxRate;
                 Main.player[myPlayer].CollectTaxes();
             }
         }
         if (netMode != 1)
         {
             UpdateSlimeRainWarning();
         }
         if (netMode != 1)
         {
             if (NPC.travelNPC)
             {
                 if (!dayTime || time > 48600.0)
                 {
                     WorldGen.UnspawnTravelNPC();
                 }
             }
             else if (!IsFastForwardingTime() && dayTime && time < 27000.0)
             {
                 int num6 = dayRate;
                 if (num6 < 1)
                 {
                     num6 = 1;
                 }
                 int num7 = (int)(27000.0 / (double)num6);
                 num7 *= 4;
                 if (rand.Next(num7) == 0)
                 {
                     int num8 = 0;
                     for (int i = 0; i < 200; i++)
                     {
                         if (npc[i].active && npc[i].townNPC && npc[i].type != 37 && npc[i].type != 453)
{
                             num8++;
                         }
                     }
                     if (num8 >= 2)
                     {
                         WorldGen.SpawnTravelNPC();
                     }
                 }
             }
             NPC.travelNPC = false;
         }
         bool stopEvents = ShouldNormalEventsBeAbleToStart();
         if (!dayTime)
         {
             eclipse = false;
             if (!IsFastForwardingTime() && !stopEvents)
             {
                 if (WorldGen.spawnEye && netMode != 1 && time > 4860.0)
                 {
                     for (int j = 0; j < 255; j++)
                     {
                         if (Main.player[j].active && !Main.player[j].dead && ((double)Main.player[j].position.Y < worldSurface * 16.0 || remixWorld))
{
                             NPC.SpawnOnPlayer(j, 4);
                             WorldGen.spawnEye = false;
                             break;
                         }
                     }
                 }
                 if (WorldGen.spawnHardBoss > 0 && netMode != 1 && time > 4860.0)
                 {
                     bool flag2 = false;
                     for (int k = 0; k < 200; k++)
                     {
                         if (npc[k].active && npc[k].boss)
{
                             flag2 = true;
                         }
                     }
                     if (!flag2)
                     {
                         for (int l = 0; l < 255; l++)
{
                             if (Main.player[l].active && !Main.player[l].dead && ((double)Main.player[l].position.Y < worldSurface * 16.0 || remixWorld))
{
                                 if (remixWorld && getGoodWorld)
{
                                     NPC.SpawnMechQueen(l);
                                 }
                                 else if (WorldGen.spawnHardBoss == 1)
{
                                     NPC.SpawnOnPlayer(l, 134);
                                 }
                                 else if (WorldGen.spawnHardBoss == 2)
{
                                     NPC.SpawnOnPlayer(l, 125);
                                     NPC.SpawnOnPlayer(l, 126);
                                 }
                                 else if (WorldGen.spawnHardBoss == 3)
{
                                     NPC.SpawnOnPlayer(l, 127);
                                 }
                                 break;
                             }
                         }
                     }
                     WorldGen.spawnHardBoss = 0;
                 }
                 if (netMode != 1)
                 {
                     double num9 = 16200.0;
                     bool num10 = num4 < num9 && time >= num9;
                     bool flag3 = raining;
                     if (num10 && flag3 && (!NPC.downedDeerclops || rand.Next(4) == 0))
                     {
                         for (int m = 0; m < 255; m++)
{
                             Player player = Main.player[m];
                             if (player.active && !player.dead && !((double)player.position.Y >= worldSurface * 16.0) && player.ZoneSnow && !(player.townNPCs > 0f) && (player.statLifeMax2 >= 200 || player.statDefense >= 9) && !NPC.AnyDanger())
{
                                 NPC.SpawnOnPlayer(m, 668);
                                 break;
                             }
                         }
                     }
                 }
             }
             if (time > 32400.0)
             {
                 UpdateTime_StartDay(ref stopEvents);
             }
             HandleMeteorFall();
         }
         else
         {
             WorldGen.spawnHardBoss = 0;
             WorldGen.spawnEye = false;
             bloodMoon = false;
             stopMoonEvent();
             if (time > 54000.0)
             {
                 UpdateTime_StartNight(ref stopEvents);
             }
             UpdateTime_SpawnTownNPCs();
         }
     }
References Entity.active, NPC.AnyDanger(), AnyPlayerReadyToFightKingSlime(), bloodMoon, NPC.BusyWithAnyInvasionOfSorts(), ChangeRain(), cloudBGActive, Player.CollectTaxes(), dayRate, dayTime, Player.dead, dedServ, NPC.downedDeerclops, NPC.downedSlimeKing, eclipse, CreativePowers.ASharedTogglePower.Enabled, expertMode, Player.FindClosest(), gameMenu, getGoodWorld, HandleMeteorFall(), hardMode, CreativePowerManager.Instance, IsFastForwardingTime(), ladyBugRainBoost, LanternNight.LanternsUp, NPC.MaxMoonLordCountdown, maxRaining, maxTilesX, NPC.MoonLordCountdown, myPlayer, WorldGen.mysticLogsEvent, netMode, UnifiedRandom.Next(), LanternNight.NextNightIsLanternNight, npc, numClouds, oldMaxRaining, player, Entity.position, pumpkinMoon, PylonSystem, raining, rainTime, rand, remixWorld, NetMessage.SendData(), ShouldNormalEventsBeAbleToStart(), slimeRain, slimeRainTime, snowMoon, WorldGen.spawnEye, WorldGen.spawnHardBoss, NPC.SpawnMechQueen(), NPC.SpawnOnPlayer(), WorldGen.SpawnTravelNPC(), StartRain(), StartSlimeRain(), Player.statDefense, Player.statLifeMax2, stopMoonEvent(), StopRain(), StopSlimeRain(), NPC.taxCollector, Player.taxRate, Player.taxTimer, time, Player.townNPCs, NPC.travelNPC, WorldGen.UnspawnTravelNPC(), TeleportPylonsSystem.Update(), UpdateSlimeRainWarning(), BirthdayParty.UpdateTime(), CreditsRollEvent.UpdateTime(), CultistRitual.UpdateTime(), DD2Event.UpdateTime(), LanternNight.UpdateTime(), MysticLogFairiesEvent.UpdateTime(), Sandstorm.UpdateTime(), UpdateTime_SpawnTownNPCs(), UpdateTime_StartDay(), UpdateTime_StartNight(), UpdateTimeRate(), worldSurface, and Player.ZoneSnow.
Referenced by DoUpdateInWorld(), and UpdateMenu().