Terraria: Main.SetFullScreen
SetFullScreen()
static void Main.SetFullScreen (bool fullscreen) inline static
     {
         SetDisplayMode(PendingResolutionWidth, PendingResolutionHeight, fullscreen);
     }
References PendingResolutionHeight, PendingResolutionWidth, and SetDisplayMode().
Referenced by OpenLegacySettings(), and ToggleFullScreen().