Terraria: Main.LoadDedConfig
LoadDedConfig()
void Main.LoadDedConfig (string configPath) inline
     {
         if (!File.Exists(configPath))
         {
             return;
         }
         using StreamReader streamReader = new StreamReader(configPath);
         string text;
         while ((text = streamReader.ReadLine()) != null)
         {
             try
             {
                 if (text.Length > 6 && text.Substring(0, 6).ToLower() == "world=")
                 {
                     string text2 = text.Substring(6);
                     try
                     {
                         string text3 = Platform.Get<IPathService>().ExpandPathVariables(text2);
                         new FileInfo(text3);
                         autoGenFileLocation = text3;
                         ActiveWorldFileData = WorldFile.GetAllMetadata(text3, cloudSave: false);
                     }
                     catch
                     {
                     }
                 }
                 if (text.Length > 5 && text.Substring(0, 5).ToLower() == "port=")
                 {
                     string value = text.Substring(5);
                     try
                     {
                         Netplay.ListenPort = Convert.ToInt32(value);
                     }
                     catch
                     {
                     }
                 }
                 if (text.Length > 21 && text.Substring(0, 21).ToLower() == "worldrollbackstokeep=")
                 {
                     string value2 = text.Substring(21);
                     try
                     {
                         WorldRollingBackupsCountToKeep = Convert.ToInt32(value2);
                     }
                     catch
                     {
                     }
                 }
                 if (text.Length > 11 && text.Substring(0, 11).ToLower() == "maxplayers=")
                 {
                     string value3 = text.Substring(11);
                     try
                     {
                         int num = Convert.ToInt32(value3);
                         if (num <= 255 && num >= 1)
{
                             SetNetPlayers(num);
                         }
                     }
                     catch
                     {
                     }
                 }
                 if (text.Length > 11 && text.Substring(0, 9).ToLower() == "priority=" && !Program.LaunchParameters.ContainsKey("-forcepriority"))
                 {
                     string value4 = text.Substring(9);
                     try
                     {
                         int num2 = Convert.ToInt32(value4);
                         if (num2 >= 0 && num2 <= 5)
{
                             Process currentProcess = Process.GetCurrentProcess();
                             switch (num2)
{
                             case 0:
                                 currentProcess.PriorityClass = ProcessPriorityClass.RealTime;
                                 break;
                             case 1:
                                 currentProcess.PriorityClass = ProcessPriorityClass.High;
                                 break;
                             case 2:
                                 currentProcess.PriorityClass = ProcessPriorityClass.AboveNormal;
                                 break;
                             case 3:
                                 currentProcess.PriorityClass = ProcessPriorityClass.Normal;
                                 break;
                             case 4:
                                 currentProcess.PriorityClass = ProcessPriorityClass.BelowNormal;
                                 break;
                             case 5:
                                 currentProcess.PriorityClass = ProcessPriorityClass.Idle;
                                 break;
                             }
                         }
                     }
                     catch
                     {
                     }
                 }
                 if (text.Length > 9 && text.Substring(0, 9).ToLower() == "password=")
                 {
                     Netplay.ServerPassword = ConvertFromSafeArgument(text.Substring(9));
                 }
                 if (text.Length > 5 && text.Substring(0, 5).ToLower() == "motd=")
                 {
                     motd = text.Substring(5);
                 }
                 if (text.Length > 5 && text.Substring(0, 5).ToLower() == "lang=")
                 {
                     string value5 = text.Substring(5);
                     LanguageManager.Instance.SetLanguage(Convert.ToInt32(value5));
                 }
                 if (text.Length > 5 && text.Substring(0, 5).ToLower() == "language=")
                 {
                     string language = text.Substring(9);
                     LanguageManager.Instance.SetLanguage(language);
                 }
                 if (text.Length >= 10 && text.Substring(0, 10).ToLower() == "worldpath=")
                 {
                     string text4 = text.Substring(10);
                     WorldPath = Platform.Get<IPathService>().ExpandPathVariables(text4);
                 }
                 if (text.Length >= 10 && text.Substring(0, 10).ToLower() == "worldname=")
                 {
                     worldName = text.Substring(10);
                 }
                 if (text.Length >= 5 && text.Substring(0, 5).ToLower() == "seed=")
                 {
                     AutogenSeedName = text.Substring(5);
                 }
                 if (text.Length > 8 && text.Substring(0, 8).ToLower() == "banlist=")
                 {
                     string text5 = text.Substring(8);
                     Netplay.BanFilePath = Platform.Get<IPathService>().ExpandPathVariables(text5);
                 }
                 if (text.Length > 11 && text.Substring(0, 11).ToLower() == "difficulty=")
                 {
                     switch (text.Substring(11))
                     {
                     case "0":
                         GameMode = 0;
                         break;
                     case "1":
                         GameMode = 1;
                         break;
                     case "2":
                         GameMode = 2;
                         break;
                     case "3":
                         GameMode = 3;
                         break;
                     }
                 }
                 if (text.Length > 11 && text.Substring(0, 11).ToLower() == "autocreate=")
                 {
                     string worldSize = text.Substring(11);
                     autoCreate(worldSize);
                 }
                 if (text.Length > 7 && text.Substring(0, 7).ToLower() == "secure=" && text.Substring(7) == "1")
                 {
                     Netplay.SpamCheck = true;
                 }
                 if (text.Length > 5 && text.Substring(0, 5).ToLower() == "upnp=" && text.Substring(5) != "1")
                 {
                     Netplay.UseUPNP = false;
                 }
                 string text6 = "slowliquids=";
                 if (text.Length > text6.Length && text.Substring(0, text6.Length).ToLower() == text6 && text.Substring(text6.Length) == "1")
                 {
                     Setting_UseReducedMaxLiquids = true;
                 }
                 if (text.Length > 10 && text.Substring(0, 10).ToLower() == "npcstream=")
                 {
                     string value6 = text.Substring(10);
                     try
                     {
                         npcStreamSpeed = Convert.ToInt32(value6);
                     }
                     catch
                     {
                     }
                 }
                 CreativePowerManager.TryListingPermissionsFrom(text);
             }
             catch
             {
             }
         }
     }
References ActiveWorldFileData, autoCreate(), autoGenFileLocation, AutogenSeedName, Netplay.BanFilePath, ConvertFromSafeArgument(), GameMode, WorldFile.GetAllMetadata(), LanguageManager.Instance, Program.LaunchParameters, Netplay.ListenPort, motd, npcStreamSpeed, Netplay.ServerPassword, LanguageManager.SetLanguage(), SetNetPlayers(), Setting_UseReducedMaxLiquids, Netplay.SpamCheck, CreativePowerManager.TryListingPermissionsFrom(), Netplay.UseUPNP, worldName, WorldPath, and WorldRollingBackupsCountToKeep.
Referenced by LaunchInitializer.LoadServerParameters().