Terraria: Main.ClosePlayerChat
ClosePlayerChat()
static void Main.ClosePlayerChat () inline static
     {
         drawingPlayerChat = false;
         PlayerInput.WritingText = false;
         player[myPlayer].releaseHook = false;
         player[myPlayer].releaseThrow = false;
     }
References drawingPlayerChat, myPlayer, player, Player.releaseHook, Player.releaseThrow, and PlayerInput.WritingText.
Referenced by IngameFancyUI.ClearChat(), DoUpdate_HandleChat(), and IngameOptions.Open().