Terraria: Main.DrawGore
DrawGore()
void Main.DrawGore () inline protected
     {
         drawBackGore = false;
         for (int i = 0; i < 600; i++)
         {
             if (!gore[i].active || gore[i].type <= 0)
             {
                 continue;
             }
             if (((gore[i].type >= 706 && gore[i].type <= 717) || gore[i].type == 943 || gore[i].type == 1147 || (gore[i].type >= 1160 && gore[i].type <= 1162)) && (gore[i].frame < 7 || gore[i].frame > 9))
             {
                 drawBackGore = true;
                 continue;
             }
             LoadGore(gore[i].type);
             if (gore[i].Frame.ColumnCount > 1 || gore[i].Frame.RowCount > 1)
             {
                 Microsoft.Xna.Framework.Rectangle sourceRectangle = gore[i].Frame.GetSourceRectangle(TextureAssets.Gore[gore[i].type].Value);
                 Vector2 vector = new Vector2(0f, 0f);
                 if (gore[i].type == 1217)
                 {
                     vector.Y += 4f;
                 }
                 Microsoft.Xna.Framework.Color alpha = gore[i].GetAlpha(Lighting.GetColor((int)((double)gore[i].position.X + (double)sourceRectangle.Width * 0.5) / 16, (int)(((double)gore[i].position.Y + (double)sourceRectangle.Height * 0.5) / 16.0)));
                 spriteBatch.Draw(TextureAssets.Gore[gore[i].type].Value, new Vector2(gore[i].position.X - screenPosition.X + (float)(sourceRectangle.Width / 2), gore[i].position.Y - screenPosition.Y + (float)(sourceRectangle.Height / 2) - 2f) + vector, sourceRectangle, alpha, gore[i].rotation, new Vector2(sourceRectangle.Width / 2, sourceRectangle.Height / 2), gore[i].scale, SpriteEffects.None, 0f);
             }
             else
             {
                 Microsoft.Xna.Framework.Color alpha2 = gore[i].GetAlpha(Lighting.GetColor((int)((double)gore[i].position.X + (double)TextureAssets.Gore[gore[i].type].Width() * 0.5) / 16, (int)(((double)gore[i].position.Y + (double)TextureAssets.Gore[gore[i].type].Height() * 0.5) / 16.0)));
                 spriteBatch.Draw(TextureAssets.Gore[gore[i].type].Value, new Vector2(gore[i].position.X - screenPosition.X + (float)(TextureAssets.Gore[gore[i].type].Width() / 2), gore[i].position.Y - screenPosition.Y + (float)(TextureAssets.Gore[gore[i].type].Height() / 2)), new Microsoft.Xna.Framework.Rectangle(0, 0, TextureAssets.Gore[gore[i].type].Width(), TextureAssets.Gore[gore[i].type].Height()), alpha2, gore[i].rotation, new Vector2(TextureAssets.Gore[gore[i].type].Width() / 2, TextureAssets.Gore[gore[i].type].Height() / 2), gore[i].scale, SpriteEffects.None, 0f);
             }
         }
         TimeLogger.DetailedDrawTime(24);
     }
References TimeLogger.DetailedDrawTime(), drawBackGore, Gore.Frame, Gore.GetAlpha(), Lighting.GetColor(), SpriteFrame.GetSourceRectangle(), TextureAssets.Gore, gore, LoadGore(), Gore.position, Gore.rotation, SpriteFrame.RowCount, Gore.scale, screenPosition, spriteBatch, Gore.type, and Asset< T >.Value.
Referenced by DoDraw(), and DrawCapture().