Terraria: Main.SortDrawCacheWorms
SortDrawCacheWorms()
void Main.SortDrawCacheWorms () inline protected
     {
         SortBabyBirdProjectiles(DrawCacheProjsOverPlayers);
         SortStardustDragonProjectiles(DrawCacheProjsBehindProjectiles);
     }
References DrawCacheProjsBehindProjectiles, DrawCacheProjsOverPlayers, SortBabyBirdProjectiles(), and SortStardustDragonProjectiles().
Referenced by DoDraw().