Terraria: Main.DrawPendingMouseText
DrawPendingMouseText()
static void Main.DrawPendingMouseText () inline static private
     {
         DrawGamepadInstructions();
         if (instance._mouseTextCache.isValid)
         {
             instance.MouseTextInner(instance._mouseTextCache);
             DrawInterface_36_Cursor();
             instance._mouseTextCache.isValid = false;
             instance._mouseTextCache.noOverride = false;
         }
     }
References _mouseTextCache, DrawGamepadInstructions(), DrawInterface_36_Cursor(), instance, Main.MouseTextCache.isValid, MouseTextInner(), and Main.MouseTextCache.noOverride.
Referenced by DoDraw(), DrawInterface_10_CheckCaptureManager(), DrawInterface_11_IngameOptionsMenu(), DrawInterface_12_IngameFancyUI(), DrawInterface_41_InterfaceLogic4(), DrawInterface_8_CheckF11UIHideToggle(), and DrawMenu().