Terraria: Main.DrawToMap
DrawToMap()
void Main.DrawToMap () inline protected
     {
         if (!mapEnabled)
         {
             return;
         }
         int num = maxTilesX / textureMaxWidth;
         int num2 = maxTilesY / textureMaxHeight;
         for (int i = 0; i <= num; i++)
         {
             for (int j = 0; j <= num2; j++)
             {
                 if (!checkMap(i, j))
                 {
                     return;
                 }
             }
         }
         if (clearMap)
         {
             for (int k = 0; k <= num; k++)
             {
                 for (int l = 0; l <= num2; l++)
                 {
                     base.GraphicsDevice.SetRenderTarget(mapTarget[k, l]);
                     base.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
                     base.GraphicsDevice.SetRenderTarget(null);
                 }
             }
             clearMap = false;
         }
         int num3 = -1;
         int num4 = -1;
         bool flag = false;
         int num5 = 0;
         int num6 = mapMinY;
         int num7 = mapMinY;
         int num8 = mapMaxY;
         int num9 = mapMaxY;
         int num10 = 1;
         if (mapMinY / textureMaxHeight != mapMaxY / textureMaxHeight)
         {
             num8 = textureMaxHeight;
             num7 = textureMaxHeight;
             num10 = 2;
         }
         for (int m = 0; m < num10; m++)
         {
             switch (m)
             {
             case 0:
                 mapMinY = num6;
                 mapMaxY = num8;
                 break;
             case 1:
                 mapMinY = num7;
                 mapMaxY = num9;
                 break;
             }
             if (mapMinX < 0)
             {
                 mapMinX = 0;
             }
             if (mapMinX >= maxTilesX)
             {
                 mapMinX = maxTilesX - 1;
             }
             if (mapMinY < 0)
             {
                 mapMinY = 0;
             }
             if (mapMinY >= maxTilesY)
             {
                 mapMinY = maxTilesY - 1;
             }
             for (int n = mapMinX; n < mapMaxX; n++)
             {
                 for (int num11 = mapMinY; num11 < mapMaxY; num11++)
                 {
                     MapTile mapTile = Map[n, num11];
                     if (!mapTile.IsChanged || mapTarget[n / textureMaxWidth, num11 / textureMaxHeight].IsContentLost)
                     {
                         continue;
                     }
                     num5++;
                     if (num5 >= maxMapUpdates)
                     {
                         continue;
                     }
                     if (loadMap)
                     {
                         loadMapLastX = n;
                     }
                     Map.ConsumeUpdate(n, num11);
                     int num12 = n / textureMaxWidth;
                     int num13 = num11 / textureMaxHeight;
                     if (num12 != num3 || num13 != num4)
                     {
                         num3 = num12;
                         num4 = num13;
                         if (flag)
{
                             spriteBatch.End();
                             base.GraphicsDevice.SetRenderTarget(null);
                         }
                         flag = true;
                         base.GraphicsDevice.SetRenderTarget(mapTarget[num12, num13]);
                         spriteBatch.Begin();
                     }
                     int num14 = n - num12 * textureMaxWidth;
                     int num15 = num11 - num13 * textureMaxHeight;
                     Microsoft.Xna.Framework.Color mapTileXnaColor = MapHelper.GetMapTileXnaColor(ref mapTile);
                     int num16 = 1;
                     int num17 = 1;
                     int num18 = num11 + 1;
                     while (num18 < mapMaxY)
                     {
                         MapTile other;
                         MapTile mapTile2 = (other = Map[n, num18]);
                         if (!mapTile2.IsChanged || !mapTile.Equals(ref other) || num18 / textureMaxHeight != num13)
{
                             break;
                         }
                         Map.ConsumeUpdate(n, num18);
                         num16++;
                         num18++;
                         num11++;
                     }
                     if (num16 == 1)
                     {
                         for (num18 = n + 1; num18 < mapMaxX; num18++)
{
                             MapTile other;
                             MapTile mapTile2 = (other = Map[num18, num11]);
                             if (!mapTile2.IsChanged || !mapTile.Equals(ref other) || num18 / textureMaxWidth != num12)
{
                                 break;
                             }
                             Map.ConsumeUpdate(num18, num11);
                             num17++;
                         }
                     }
                     spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Vector2(num14, num15), new Microsoft.Xna.Framework.Rectangle(0, 0, num17, num16), mapTileXnaColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
                 }
             }
         }
         for (int num19 = 0; num19 < MapHelper.numUpdateTile; num19++)
         {
             int num20 = MapHelper.updateTileX[num19];
             int num21 = MapHelper.updateTileY[num19];
             MapTile mapTile3 = Map[num20, num21];
             if (!mapTile3.IsChanged)
             {
                 continue;
             }
             Map.ConsumeUpdate(num20, num21);
             int num22 = num20 / textureMaxWidth;
             int num23 = num21 / textureMaxHeight;
             if (num22 != num3 || num23 != num4)
             {
                 num3 = num22;
                 num4 = num23;
                 if (flag)
                 {
                     spriteBatch.End();
                     base.GraphicsDevice.SetRenderTarget(null);
                 }
                 flag = true;
                 base.GraphicsDevice.SetRenderTarget(mapTarget[num22, num23]);
                 spriteBatch.Begin();
             }
             int num24 = num20 - num22 * textureMaxWidth;
             int num25 = num21 - num23 * textureMaxHeight;
             Microsoft.Xna.Framework.Color mapTileXnaColor2 = MapHelper.GetMapTileXnaColor(ref mapTile3);
             spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Vector2(num24, num25), new Microsoft.Xna.Framework.Rectangle(0, 0, 1, 1), mapTileXnaColor2, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
         }
         MapHelper.numUpdateTile = 0;
         if (flag)
         {
             spriteBatch.End();
             base.GraphicsDevice.SetRenderTarget(null);
         }
         mapReady = true;
         loadMapLastX = 0;
         loadMap = false;
         loadMapLock = false;
     }
References checkMap(), clearMap, WorldMap.ConsumeUpdate(), MapTile.Equals(), MapHelper.GetMapTileXnaColor(), MapTile.IsChanged, loadMap, loadMapLastX, loadMapLock, TextureAssets.MagicPixel, Map, mapEnabled, mapMaxX, mapMaxY, mapMinX, mapMinY, mapReady, mapTarget, maxMapUpdates, maxTilesX, maxTilesY, MapHelper.numUpdateTile, spriteBatch, textureMaxHeight, textureMaxWidth, MapHelper.updateTileX, MapHelper.updateTileY, and Asset< T >.Value.
Referenced by DoDraw().