Terraria: Main.DrawThickCursor
DrawThickCursor()
static Vector2 Main.DrawThickCursor (bool smart = false) inline static
     {
         if (ThickMouse)
         {
             bool showGamepadCursor = PlayerInput.SettingsForUI.ShowGamepadCursor;
             if (gameMenu && alreadyGrabbingSunOrMoon)
             {
                 return Vector2.Zero;
             }
             if (showGamepadCursor && PlayerInput.InvisibleGamepadInMenus)
             {
                 return Vector2.Zero;
             }
             if (showGamepadCursor && player[myPlayer].dead && !player[myPlayer].ghost && !gameMenu)
             {
                 return Vector2.Zero;
             }
             bool flag = UILinkPointNavigator.Available && !PlayerInput.InBuildingMode;
             Microsoft.Xna.Framework.Color mouseBorderColor = MouseBorderColor;
             int num = 11;
             num += smart.ToInt();
             for (int i = 0; i < 4; i++)
             {
                 Vector2 vector = Vector2.Zero;
                 switch (i)
                 {
                 case 0:
                     vector = new Vector2(0f, 1f);
                     break;
                 case 1:
                     vector = new Vector2(1f, 0f);
                     break;
                 case 2:
                     vector = new Vector2(0f, -1f);
                     break;
                 case 3:
                     vector = new Vector2(-1f, 0f);
                     break;
                 }
                 vector *= 1f;
                 vector += Vector2.One * 2f;
                 Vector2 origin = new Vector2(2f);
                 Microsoft.Xna.Framework.Rectangle? sourceRectangle = null;
                 float scale = cursorScale * 1.1f;
                 if (showGamepadCursor)
                 {
                     if (smart && !flag)
                     {
                         num = 13;
                         int frameX = 0;
                         vector = Vector2.One;
                         sourceRectangle = TextureAssets.Cursors[num].Frame(2, 1, frameX);
                         origin = TextureAssets.Cursors[num].Frame(2, 1, frameX).Size() / 2f;
                         mouseBorderColor *= GamepadCursorAlpha;
                     }
                     else
                     {
                         num = 15;
                         vector = Vector2.One;
                         origin = TextureAssets.Cursors[num].Value.Size() / 2f;
                     }
                 }
                 spriteBatch.Draw(TextureAssets.Cursors[num].Value, new Vector2(mouseX, mouseY) + vector, sourceRectangle, mouseBorderColor, 0f, origin, scale, SpriteEffects.None, 0f);
             }
             return new Vector2(2f);
         }
         return Vector2.Zero;
     }
References alreadyGrabbingSunOrMoon, UILinkPointNavigator.Available, TextureAssets.Cursors, cursorScale, gameMenu, GamepadCursorAlpha, PlayerInput.InBuildingMode, PlayerInput.InvisibleGamepadInMenus, MouseBorderColor, mouseX, mouseY, myPlayer, player, PlayerInput.SettingsForUI.ShowGamepadCursor, spriteBatch, ThickMouse, and Asset< T >.Value.
Referenced by DoDraw(), IngameFancyUI.Draw(), Utils.DrawCursorSingle(), DrawInterface_36_Cursor(), DrawMap(), and DrawMenu().