Terraria: Main.UpdateAudio
UpdateAudio()
void Main.UpdateAudio () inline protected
     {
         if (!SoundEngine.IsAudioSupported || !_musicLoaded)
         {
             return;
         }
         if (!dedServ && !showSplash)
         {
             SoundEngine.Update();
         }
         if (musicVolume == 0f)
         {
             curMusic = 0;
         }
         try
         {
             if (dedServ)
             {
                 return;
             }
             bool flag = base.IsActive;
             if (!flag)
             {
                 audioSystem.PauseAll();
                 SoundEngine.StopAmbientSounds();
             }
             else
             {
                 audioSystem.ResumeAll();
             }
             if (drunkWorld)
             {
                 TOWMusicUnlocked = true;
             }
             if (gameMenu)
             {
                 swapMusic = false;
             }
             if (swapMusic)
             {
                 if (drunkWorld && !remixWorld)
                 {
                     UpdateAudio_DecideOnNewMusic();
                 }
                 else
                 {
                     UpdateAudio_DecideOnTOWMusic();
                 }
             }
             else if (!gameMenu && drunkWorld && !remixWorld)
             {
                 UpdateAudio_DecideOnTOWMusic();
             }
             else
             {
                 UpdateAudio_DecideOnNewMusic();
             }
             if (musicBox2 >= 0)
             {
                 SceneMetrics.ActiveMusicBox = musicBox2;
             }
             if (SceneMetrics.ActiveMusicBox >= 0)
             {
                 if (SceneMetrics.ActiveMusicBox == 0)
                 {
                     newMusic = 1;
                 }
                 if (SceneMetrics.ActiveMusicBox == 1)
                 {
                     newMusic = 2;
                 }
                 if (SceneMetrics.ActiveMusicBox == 2)
                 {
                     newMusic = 3;
                 }
                 if (SceneMetrics.ActiveMusicBox == 4)
                 {
                     newMusic = 4;
                 }
                 if (SceneMetrics.ActiveMusicBox == 5)
                 {
                     newMusic = 5;
                 }
                 if (SceneMetrics.ActiveMusicBox == 3)
                 {
                     newMusic = 6;
                 }
                 if (SceneMetrics.ActiveMusicBox == 6)
                 {
                     newMusic = 7;
                 }
                 if (SceneMetrics.ActiveMusicBox == 7)
                 {
                     newMusic = 8;
                 }
                 if (SceneMetrics.ActiveMusicBox == 9)
                 {
                     newMusic = 9;
                 }
                 if (SceneMetrics.ActiveMusicBox == 8)
                 {
                     newMusic = 10;
                 }
                 if (SceneMetrics.ActiveMusicBox == 11)
                 {
                     newMusic = 11;
                 }
                 if (SceneMetrics.ActiveMusicBox == 10)
                 {
                     newMusic = 12;
                 }
                 if (SceneMetrics.ActiveMusicBox == 12)
                 {
                     newMusic = 13;
                 }
                 if (SceneMetrics.ActiveMusicBox == 13)
                 {
                     newMusic = 14;
                 }
                 if (SceneMetrics.ActiveMusicBox == 14)
                 {
                     newMusic = 15;
                 }
                 if (SceneMetrics.ActiveMusicBox == 15)
                 {
                     newMusic = 16;
                 }
                 if (SceneMetrics.ActiveMusicBox == 16)
                 {
                     newMusic = 17;
                 }
                 if (SceneMetrics.ActiveMusicBox == 17)
                 {
                     newMusic = 18;
                 }
                 if (SceneMetrics.ActiveMusicBox == 18)
                 {
                     newMusic = 19;
                 }
                 if (SceneMetrics.ActiveMusicBox == 19)
                 {
                     newMusic = 20;
                 }
                 if (SceneMetrics.ActiveMusicBox == 20)
                 {
                     newMusic = 21;
                 }
                 if (SceneMetrics.ActiveMusicBox == 21)
                 {
                     newMusic = 22;
                 }
                 if (SceneMetrics.ActiveMusicBox == 22)
                 {
                     newMusic = 23;
                 }
                 if (SceneMetrics.ActiveMusicBox == 23)
                 {
                     newMusic = 24;
                 }
                 if (SceneMetrics.ActiveMusicBox == 24)
                 {
                     newMusic = 25;
                 }
                 if (SceneMetrics.ActiveMusicBox == 25)
                 {
                     newMusic = 26;
                 }
                 if (SceneMetrics.ActiveMusicBox == 26)
                 {
                     newMusic = 27;
                 }
                 if (SceneMetrics.ActiveMusicBox == 27)
                 {
                     newMusic = 29;
                 }
                 if (SceneMetrics.ActiveMusicBox == 28)
                 {
                     newMusic = 30;
                 }
                 if (SceneMetrics.ActiveMusicBox == 29)
                 {
                     newMusic = 31;
                 }
                 if (SceneMetrics.ActiveMusicBox == 30)
                 {
                     newMusic = 32;
                 }
                 if (SceneMetrics.ActiveMusicBox == 31)
                 {
                     newMusic = 33;
                 }
                 if (SceneMetrics.ActiveMusicBox == 32)
                 {
                     newMusic = 38;
                 }
                 if (SceneMetrics.ActiveMusicBox == 33)
                 {
                     newMusic = 37;
                 }
                 if (SceneMetrics.ActiveMusicBox == 34)
                 {
                     newMusic = 35;
                 }
                 if (SceneMetrics.ActiveMusicBox == 35)
                 {
                     newMusic = 36;
                 }
                 if (SceneMetrics.ActiveMusicBox == 36)
                 {
                     newMusic = 34;
                 }
                 if (SceneMetrics.ActiveMusicBox == 37)
                 {
                     newMusic = 39;
                 }
                 if (SceneMetrics.ActiveMusicBox == 38)
                 {
                     newMusic = 40;
                 }
                 if (SceneMetrics.ActiveMusicBox == 39)
                 {
                     newMusic = 41;
                 }
                 if (SceneMetrics.ActiveMusicBox == 40)
                 {
                     newMusic = 44;
                 }
                 if (SceneMetrics.ActiveMusicBox == 41)
                 {
                     newMusic = 48;
                 }
                 if (SceneMetrics.ActiveMusicBox == 42)
                 {
                     newMusic = 42;
                 }
                 if (SceneMetrics.ActiveMusicBox == 43)
                 {
                     newMusic = 43;
                 }
                 if (SceneMetrics.ActiveMusicBox == 44)
                 {
                     newMusic = 46;
                 }
                 if (SceneMetrics.ActiveMusicBox == 45)
                 {
                     newMusic = 47;
                 }
                 if (SceneMetrics.ActiveMusicBox == 46)
                 {
                     newMusic = 49;
                 }
                 if (SceneMetrics.ActiveMusicBox == 47)
                 {
                     newMusic = 51;
                 }
                 if (SceneMetrics.ActiveMusicBox == 48)
                 {
                     newMusic = 52;
                 }
                 if (SceneMetrics.ActiveMusicBox == 49)
                 {
                     newMusic = 53;
                 }
                 if (SceneMetrics.ActiveMusicBox == 50)
                 {
                     newMusic = 54;
                 }
                 if (SceneMetrics.ActiveMusicBox == 51)
                 {
                     newMusic = 55;
                 }
                 if (SceneMetrics.ActiveMusicBox == 52)
                 {
                     newMusic = 56;
                 }
                 if (SceneMetrics.ActiveMusicBox == 53)
                 {
                     newMusic = 57;
                 }
                 if (SceneMetrics.ActiveMusicBox == 54)
                 {
                     newMusic = 58;
                 }
                 if (SceneMetrics.ActiveMusicBox == 55)
                 {
                     newMusic = 59;
                 }
                 if (SceneMetrics.ActiveMusicBox == 56)
                 {
                     newMusic = 60;
                 }
                 if (SceneMetrics.ActiveMusicBox == 57)
                 {
                     newMusic = 61;
                 }
                 if (SceneMetrics.ActiveMusicBox == 58)
                 {
                     newMusic = 62;
                 }
                 if (SceneMetrics.ActiveMusicBox == 59)
                 {
                     newMusic = 63;
                 }
                 if (SceneMetrics.ActiveMusicBox == 60)
                 {
                     newMusic = 64;
                 }
                 if (SceneMetrics.ActiveMusicBox == 61)
                 {
                     newMusic = 65;
                 }
                 if (SceneMetrics.ActiveMusicBox == 62)
                 {
                     newMusic = 66;
                 }
                 if (SceneMetrics.ActiveMusicBox == 63)
                 {
                     newMusic = 67;
                 }
                 if (SceneMetrics.ActiveMusicBox == 64)
                 {
                     newMusic = 68;
                 }
                 if (SceneMetrics.ActiveMusicBox == 65)
                 {
                     newMusic = 69;
                 }
                 if (SceneMetrics.ActiveMusicBox == 66)
                 {
                     newMusic = 70;
                 }
                 if (SceneMetrics.ActiveMusicBox == 67)
                 {
                     newMusic = 71;
                 }
                 if (SceneMetrics.ActiveMusicBox == 68)
                 {
                     newMusic = 72;
                 }
                 if (SceneMetrics.ActiveMusicBox == 69)
                 {
                     newMusic = 73;
                 }
                 if (SceneMetrics.ActiveMusicBox == 70)
                 {
                     newMusic = 74;
                 }
                 if (SceneMetrics.ActiveMusicBox == 71)
                 {
                     newMusic = 75;
                 }
                 if (SceneMetrics.ActiveMusicBox == 72)
                 {
                     newMusic = 76;
                 }
                 if (SceneMetrics.ActiveMusicBox == 73)
                 {
                     newMusic = 77;
                 }
                 if (SceneMetrics.ActiveMusicBox == 74)
                 {
                     newMusic = 78;
                 }
                 if (SceneMetrics.ActiveMusicBox == 75)
                 {
                     newMusic = 79;
                 }
                 if (SceneMetrics.ActiveMusicBox == 76)
                 {
                     newMusic = 80;
                 }
                 if (SceneMetrics.ActiveMusicBox == 77)
                 {
                     newMusic = 81;
                 }
                 if (SceneMetrics.ActiveMusicBox == 78)
                 {
                     newMusic = 82;
                 }
                 if (SceneMetrics.ActiveMusicBox == 79)
                 {
                     newMusic = 83;
                 }
                 if (SceneMetrics.ActiveMusicBox == 80)
                 {
                     newMusic = 84;
                 }
                 if (SceneMetrics.ActiveMusicBox == 81)
                 {
                     newMusic = 85;
                 }
                 if (SceneMetrics.ActiveMusicBox == 82)
                 {
                     newMusic = 86;
                 }
                 if (SceneMetrics.ActiveMusicBox == 83)
                 {
                     newMusic = 87;
                 }
                 if (SceneMetrics.ActiveMusicBox == 84)
                 {
                     newMusic = 88;
                 }
                 if (SceneMetrics.ActiveMusicBox == 85)
                 {
                     newMusic = 89;
                 }
                 if (SceneMetrics.ActiveMusicBox == 86)
                 {
                     newMusic = 90;
                 }
                 if (SceneMetrics.ActiveMusicBox == 87)
                 {
                     newMusic = 91;
                 }
             }
             if (gameMenu || musicVolume == 0f)
             {
                 musicBox2 = -1;
                 SceneMetrics.ActiveMusicBox = -1;
             }
             if (musicVolume == 0f)
             {
                 newMusic = 0;
             }
             audioSystem.Update();
             audioSystem.UpdateMisc();
             curMusic = newMusic;
             float num = 1f;
             if (NPC.MoonLordCountdown > 0)
             {
                 num = (float)NPC.MoonLordCountdown / (float)NPC.MaxMoonLordCountdown;
                 num *= num;
                 if ((float)NPC.MoonLordCountdown > (float)NPC.MaxMoonLordCountdown * 0.2f)
                 {
                     num = MathHelper.Lerp(0f, 1f, num);
                 }
                 else
                 {
                     num = 0f;
                     curMusic = 0;
                 }
                 if (NPC.MoonLordCountdown == 1 && curMusic >= 1 && curMusic < maxMusic)
                 {
                     musicFade[curMusic] = 0f;
                 }
             }
             bool isMainTrackAudible = musicFade[curMusic] > 0.25f;
             for (int i = 1; i < maxMusic; i++)
             {
                 float num2 = musicFade[i] * musicVolume * num;
                 if (i >= 62 && i <= 88)
                 {
                     num2 *= 0.9f;
                 }
                 else if (i == 52)
                 {
                     num2 *= 1.15f;
                     if (num2 > 1f)
                     {
                         num2 = 1f;
                     }
                 }
                 float num3 = shimmerAlpha;
                 switch (i)
                 {
                 case 28:
                 {
                     float num7 = 0.5f;
                     float num8 = cloudAlpha / 9f * 10f * num7 + (1f - num7);
                     if (num3 > 0f)
                     {
                         num8 *= 1f - num3;
                     }
                     if (num8 > 1f)
                     {
                         num8 = 1f;
                     }
                     if (gameMenu)
                     {
                         num8 = 0f;
                     }
                     num8 *= (float)Math.Pow(atmo, 4.0);
                     if (remixWorld)
                     {
                         if (cloudAlpha > 0f && (double)(player[myPlayer].position.Y / 16f) > rockLayer && player[myPlayer].position.Y / 16f < (float)(maxTilesY - 350) && !player[myPlayer].ZoneSnow && !player[myPlayer].ZoneDungeon)
{
                             float trackVolume5 = musicFade[i];
                             audioSystem.UpdateAmbientCueState(i, flag, ref trackVolume5, ambientVolume * num8);
                             musicFade[i] = trackVolume5;
                         }
                         else
{
                             float trackVolume6 = musicFade[i];
                             audioSystem.UpdateAmbientCueTowardStopping(i, 0.005f, ref trackVolume6, ambientVolume * num8);
                             musicFade[i] = trackVolume6;
                         }
                     }
                     else if (cloudAlpha > 0f && (double)player[myPlayer].position.Y < worldSurface * 16.0 + (double)(screenHeight / 2) && !player[myPlayer].ZoneSnow)
                     {
                         float trackVolume7 = musicFade[i];
                         audioSystem.UpdateAmbientCueState(i, flag, ref trackVolume7, ambientVolume * num8);
                         musicFade[i] = trackVolume7;
                     }
                     else
                     {
                         float trackVolume8 = musicFade[i];
                         audioSystem.UpdateAmbientCueTowardStopping(i, 0.005f, ref trackVolume8, ambientVolume * num8);
                         musicFade[i] = trackVolume8;
                     }
                     break;
                 }
                 case 45:
                 {
                     float num4 = 0.7f;
                     float num5 = Math.Abs(windSpeedCurrent) * num4 + (1f - num4);
                     if (num3 > 0f)
                     {
                         num5 *= 1f - num3;
                     }
                     if (num5 > 1f)
                     {
                         num5 = 1f;
                     }
                     num5 *= 0.9f;
                     float num6 = 20f;
                     num5 *= (float)Math.Pow(atmo, 4.0);
                     if (remixWorld)
                     {
                         if (!gameMenu && Math.Abs(windSpeedCurrent) >= num6 / 50f && (double)(player[myPlayer].position.Y / 16f) > rockLayer && player[myPlayer].position.Y / 16f < (float)(maxTilesY - 350) && !player[myPlayer].ZoneDungeon)
{
                             float trackVolume = musicFade[i];
                             audioSystem.UpdateAmbientCueState(i, flag, ref trackVolume, ambientVolume * num5);
                             musicFade[i] = trackVolume;
                         }
                         else
{
                             float trackVolume2 = musicFade[i];
                             audioSystem.UpdateAmbientCueTowardStopping(i, 0.005f, ref trackVolume2, ambientVolume * num5);
                             musicFade[i] = trackVolume2;
                         }
                     }
                     else if (!gameMenu && Math.Abs(windSpeedCurrent) >= num6 / 50f && (double)player[myPlayer].position.Y < worldSurface * 16.0 + (double)(screenHeight / 2))
                     {
                         float trackVolume3 = musicFade[i];
                         audioSystem.UpdateAmbientCueState(i, flag, ref trackVolume3, ambientVolume * num5);
                         musicFade[i] = trackVolume3;
                     }
                     else
                     {
                         float trackVolume4 = musicFade[i];
                         audioSystem.UpdateAmbientCueTowardStopping(i, 0.005f, ref trackVolume4, ambientVolume * num5);
                         musicFade[i] = trackVolume4;
                     }
                     break;
                 }
                 default:
                 {
                     float tempFade = musicFade[i];
                     if (i == curMusic)
                     {
                         audioSystem.UpdateCommonTrack(flag, i, num2, ref tempFade);
                     }
                     else
                     {
                         audioSystem.UpdateCommonTrackTowardStopping(i, num2, ref tempFade, isMainTrackAudible);
                     }
                     musicFade[i] = tempFade;
                     break;
                 }
                 }
             }
             audioSystem.UpdateAudioEngine();
             if (musicError > 0)
             {
                 musicError--;
             }
         }
         catch
         {
             musicError++;
             if (musicError >= 100)
             {
                 musicError = 0;
                 musicVolume = 0f;
             }
         }
     }
References _musicLoaded, SceneMetrics.ActiveMusicBox, ambientVolume, atmo, audioSystem, cloudAlpha, curMusic, dedServ, drunkWorld, gameMenu, SoundEngine.IsAudioSupported, NPC.MaxMoonLordCountdown, maxMusic, maxTilesY, NPC.MoonLordCountdown, musicBox2, musicError, musicFade, musicVolume, myPlayer, newMusic, IAudioSystem.PauseAll(), player, Entity.position, remixWorld, IAudioSystem.ResumeAll(), rockLayer, screenHeight, shimmerAlpha, showSplash, SoundEngine.StopAmbientSounds(), swapMusic, TOWMusicUnlocked, IAudioSystem.Update(), SoundEngine.Update(), IAudioSystem.UpdateAmbientCueState(), IAudioSystem.UpdateAmbientCueTowardStopping(), UpdateAudio_DecideOnNewMusic(), UpdateAudio_DecideOnTOWMusic(), IAudioSystem.UpdateAudioEngine(), IAudioSystem.UpdateCommonTrack(), IAudioSystem.UpdateCommonTrackTowardStopping(), IAudioSystem.UpdateMisc(), windSpeedCurrent, worldSurface, Player.ZoneDungeon, and Player.ZoneSnow.
Referenced by DoUpdate().