Terraria: Main.DrawWaters
DrawWaters()
void Main.DrawWaters (bool isBackground = false) inline private
     {
         drewLava = false;
         if (!isBackground)
         {
             waterStyle = CalculateWaterStyle();
             for (int i = 0; i < 15; i++)
             {
                 if (IsLiquidStyleWater(waterStyle))
                 {
                     if (waterStyle != i)
                     {
                         liquidAlpha[i] = Math.Max(liquidAlpha[i] - 0.2f, 0f);
                     }
                     else
                     {
                         liquidAlpha[i] = Math.Min(liquidAlpha[i] + 0.2f, 1f);
                     }
                 }
             }
         }
         if (!drawToScreen && !isBackground)
         {
             Vector2 vector = (drawToScreen ? Vector2.Zero : new Vector2(offScreenRange, offScreenRange));
             int val = (int)((Camera.ScaledPosition.X - vector.X) / 16f - 1f);
             int val2 = (int)((Camera.ScaledPosition.X + Camera.ScaledSize.X + vector.X) / 16f) + 2;
             int val3 = (int)((Camera.ScaledPosition.Y - vector.Y) / 16f - 1f);
             int val4 = (int)((Camera.ScaledPosition.Y + Camera.ScaledSize.Y + vector.Y) / 16f) + 5;
             val = Math.Max(val, 5) - 2;
             val3 = Math.Max(val3, 5);
             val2 = Math.Min(val2, maxTilesX - 5) + 2;
             val4 = Math.Min(val4, maxTilesY - 5) + 4;
             Microsoft.Xna.Framework.Rectangle drawArea = new Microsoft.Xna.Framework.Rectangle(val, val3, val2 - val, val4 - val3);
             LiquidRenderer.Instance.PrepareDraw(drawArea);
         }
         bool flag = false;
         for (int j = 0; j < 15; j++)
         {
             if (IsLiquidStyleWater(j) && liquidAlpha[j] > 0f && j != waterStyle)
             {
                 DrawLiquid(isBackground, j, isBackground ? 1f : liquidAlpha[j], drawSinglePassLiquids: false);
                 flag = true;
             }
         }
         DrawLiquid(isBackground, waterStyle, flag ? liquidAlpha[waterStyle] : 1f);
     }
References CalculateWaterStyle(), DrawLiquid(), drawToScreen, drewLava, LiquidRenderer.Instance, IsLiquidStyleWater(), liquidAlpha, maxTilesX, maxTilesY, offScreenRange, LiquidRenderer.PrepareDraw(), Camera.ScaledPosition, Camera.ScaledSize, and waterStyle.
Referenced by DoDraw(), RenderBackground(), and RenderWater().