Terraria: Main.UpdateTime_SpawnTownNPCs
UpdateTime_SpawnTownNPCs()
static void Main.UpdateTime_SpawnTownNPCs () inline static private
     {
         int worldUpdateRate = WorldGen.GetWorldUpdateRate();
         if (netMode == 1 || worldUpdateRate <= 0)
         {
             return;
         }
         checkForSpawns++;
         if (checkForSpawns < 7200 / worldUpdateRate)
         {
             return;
         }
         checkForSpawns = 0;
         int num = 0;
         for (int i = 0; i < 255; i++)
         {
             if (player[i].active)
             {
                 num++;
             }
         }
         for (int j = 0; j < NPCID.Count; j++)
         {
             townNPCCanSpawn[j] = false;
         }
         WorldGen.prioritizedTownNPCType = 0;
         int num2 = 0;
         int num3 = 0;
         int num4 = 0;
         int num5 = 0;
         int num6 = 0;
         int num7 = 0;
         int num8 = 0;
         int num9 = 0;
         int num10 = 0;
         int num11 = 0;
         int num12 = 0;
         int num13 = 0;
         int num14 = 0;
         int num15 = 0;
         int num16 = 0;
         int num17 = 0;
         int num18 = 0;
         int num19 = 0;
         int num20 = 0;
         int num21 = 0;
         int num22 = 0;
         int num23 = 0;
         int num24 = 0;
         int num25 = 0;
         int num26 = 0;
         int num27 = 0;
         int num28 = 0;
         int num29 = 0;
         int num30 = 0;
         int num31 = 0;
         int num32 = 0;
         int num33 = 0;
         int num34 = 0;
         int num35 = 0;
         int num36 = 0;
         int num37 = 0;
         int num38 = 0;
         int num39 = 0;
         int num40 = 0;
         for (int k = 0; k < 200; k++)
         {
             if (npc[k].active && npc[k].townNPC)
             {
                 if (npc[k].type != 368 && npc[k].type != 37 && npc[k].type != 453 && !npc[k].homeless)
                 {
                     WorldGen.QuickFindHome(k);
                 }
                 if (npc[k].type == 37)
                 {
                     num7++;
                 }
                 if (npc[k].type == 17)
                 {
                     num2++;
                 }
                 if (npc[k].type == 18)
                 {
                     num3++;
                 }
                 if (npc[k].type == 19)
                 {
                     num5++;
                 }
                 if (npc[k].type == 20)
                 {
                     num4++;
                 }
                 if (npc[k].type == 22)
                 {
                     num6++;
                 }
                 if (npc[k].type == 38)
                 {
                     num8++;
                 }
                 if (npc[k].type == 54)
                 {
                     num9++;
                 }
                 if (npc[k].type == 107)
                 {
                     num11++;
                 }
                 if (npc[k].type == 108)
                 {
                     num10++;
                 }
                 if (npc[k].type == 124)
                 {
                     num12++;
                 }
                 if (npc[k].type == 142)
                 {
                     num13++;
                 }
                 if (npc[k].type == 160)
                 {
                     num14++;
                 }
                 if (npc[k].type == 178)
                 {
                     num15++;
                 }
                 if (npc[k].type == 207)
                 {
                     num16++;
                 }
                 if (npc[k].type == 208)
                 {
                     num17++;
                 }
                 if (npc[k].type == 209)
                 {
                     num18++;
                 }
                 if (npc[k].type == 227)
                 {
                     num19++;
                 }
                 if (npc[k].type == 228)
                 {
                     num20++;
                 }
                 if (npc[k].type == 229)
                 {
                     num21++;
                 }
                 if (npc[k].type == 353)
                 {
                     num22++;
                 }
                 if (npc[k].type == 369)
                 {
                     num23++;
                 }
                 if (npc[k].type == 441)
                 {
                     num24++;
                 }
                 if (npc[k].type == 550)
                 {
                     num25++;
                 }
                 if (npc[k].type == 588)
                 {
                     num26++;
                 }
                 if (npc[k].type == 633)
                 {
                     num27++;
                 }
                 if (npc[k].type == 637)
                 {
                     num28++;
                 }
                 if (npc[k].type == 638)
                 {
                     num29++;
                 }
                 if (npc[k].type == 656)
                 {
                     num30++;
                 }
                 if (npc[k].type == 670)
                 {
                     num31++;
                 }
                 if (npc[k].type == 678)
                 {
                     num32++;
                 }
                 if (npc[k].type == 679)
                 {
                     num33++;
                 }
                 if (npc[k].type == 680)
                 {
                     num34++;
                 }
                 if (npc[k].type == 681)
                 {
                     num35++;
                 }
                 if (npc[k].type == 682)
                 {
                     num36++;
                 }
                 if (npc[k].type == 683)
                 {
                     num37++;
                 }
                 if (npc[k].type == 684)
                 {
                     num38++;
                 }
                 if (npc[k].type == 663)
                 {
                     num39++;
                 }
                 num40++;
             }
         }
         if (WorldGen.prioritizedTownNPCType == 0)
         {
             bool flag = NPC.SpawnAllowed_Merchant();
             bool flag2 = NPC.SpawnAllowed_ArmsDealer();
             bool flag3 = NPC.SpawnAllowed_Nurse();
             bool flag4 = NPC.SpawnAllowed_DyeTrader();
             bool flag5 = NPC.SpawnAllowed_Demolitionist();
             BestiaryUnlockProgressReport bestiaryProgressReport = GetBestiaryProgressReport();
             if (!NPC.downedBoss3 && num7 == 0)
             {
                 int num41 = NPC.NewNPC(NPC.GetSpawnSourceForTownSpawn(), dungeonX * 16 + 8, dungeonY * 16, 37);
                 npc[num41].homeless = false;
                 npc[num41].homeTileX = dungeonX;
                 npc[num41].homeTileY = dungeonY;
             }
             bool flag6 = false;
             if (rand.Next(40) == 0)
             {
                 flag6 = true;
             }
             bool flag7 = flag6 && num40 >= 14;
             if (NPC.unlockedPartyGirlSpawn)
             {
                 flag7 = true;
             }
             bool flag8 = BirthdayParty.GenuineParty;
             if (NPC.unlockedSlimeGreenSpawn)
             {
                 flag8 = true;
             }
             if (num6 < 1)
             {
                 townNPCCanSpawn[22] = true;
             }
             if (flag && num2 < 1)
             {
                 townNPCCanSpawn[17] = true;
             }
             if (flag3 && num3 < 1 && num2 > 0)
             {
                 townNPCCanSpawn[18] = true;
             }
             if (flag2 && num5 < 1)
             {
                 townNPCCanSpawn[19] = true;
             }
             if ((NPC.downedBoss1 || NPC.downedBoss2 || NPC.downedBoss3) && num4 < 1)
             {
                 townNPCCanSpawn[20] = true;
             }
             if (flag5 && num2 > 0 && num8 < 1)
             {
                 townNPCCanSpawn[38] = true;
             }
             if (NPC.savedStylist && num22 < 1)
             {
                 townNPCCanSpawn[353] = true;
             }
             if (NPC.savedAngler && num23 < 1)
             {
                 townNPCCanSpawn[369] = true;
             }
             if (NPC.downedBoss3 && num9 < 1)
             {
                 townNPCCanSpawn[54] = true;
             }
             if (NPC.savedGoblin && num11 < 1)
             {
                 townNPCCanSpawn[107] = true;
             }
             if (NPC.savedTaxCollector && num24 < 1)
             {
                 townNPCCanSpawn[441] = true;
             }
             if (NPC.savedWizard && num10 < 1)
             {
                 townNPCCanSpawn[108] = true;
             }
             if (NPC.savedMech && num12 < 1)
             {
                 townNPCCanSpawn[124] = true;
             }
             if (NPC.downedFrost && num13 < 1 && xMas)
             {
                 townNPCCanSpawn[142] = true;
             }
             if (((tenthAnniversaryWorld && !remixWorld) || NPC.downedMechBossAny) && num15 < 1)
             {
                 townNPCCanSpawn[178] = true;
             }
             if (flag4 && num16 < 1 && num40 >= 4)
             {
                 townNPCCanSpawn[207] = true;
             }
             if (NPC.downedQueenBee && num20 < 1)
             {
                 townNPCCanSpawn[228] = true;
             }
             if (NPC.downedPirates && num21 < 1)
             {
                 townNPCCanSpawn[229] = true;
             }
             if (num14 < 1 && hardMode)
             {
                 townNPCCanSpawn[160] = true;
             }
             if (hardMode && NPC.downedPlantBoss && num18 < 1)
             {
                 townNPCCanSpawn[209] = true;
             }
             if (num40 >= 8 && num19 < 1)
             {
                 townNPCCanSpawn[227] = true;
             }
             if (flag7 && num17 < 1)
             {
                 townNPCCanSpawn[208] = true;
             }
             if (NPC.savedBartender && num25 < 1)
             {
                 townNPCCanSpawn[550] = true;
             }
             if (NPC.savedGolfer && num26 < 1)
             {
                 townNPCCanSpawn[588] = true;
             }
             if (bestiaryProgressReport.CompletionPercent >= 0.1f && num27 < 1)
             {
                 townNPCCanSpawn[633] = true;
             }
             if (NPC.boughtCat && num28 < 1)
             {
                 townNPCCanSpawn[637] = true;
             }
             if (NPC.boughtDog && num29 < 1)
             {
                 townNPCCanSpawn[638] = true;
             }
             if (NPC.boughtBunny && num30 < 1)
             {
                 townNPCCanSpawn[656] = true;
             }
             if (NPC.unlockedSlimeBlueSpawn && num31 < 1)
             {
                 townNPCCanSpawn[670] = true;
             }
             if (flag8 && num32 < 1)
             {
                 townNPCCanSpawn[678] = true;
             }
             if (NPC.unlockedSlimeOldSpawn && num33 < 1)
             {
                 townNPCCanSpawn[679] = true;
             }
             if (NPC.unlockedSlimePurpleSpawn && num34 < 1)
             {
                 townNPCCanSpawn[680] = true;
             }
             if (NPC.unlockedSlimeRainbowSpawn && num35 < 1)
             {
                 townNPCCanSpawn[681] = true;
             }
             if (NPC.unlockedSlimeRedSpawn && num36 < 1)
             {
                 townNPCCanSpawn[682] = true;
             }
             if (NPC.unlockedSlimeYellowSpawn && num37 < 1)
             {
                 townNPCCanSpawn[683] = true;
             }
             if (NPC.unlockedSlimeCopperSpawn && num38 < 1)
             {
                 townNPCCanSpawn[684] = true;
             }
             bool flag9 = num2 > 0 && num3 > 0 && num4 > 0 && num5 > 0 && num6 > 0 && num8 > 0 && num9 > 0 && num10 > 0 && num11 > 0 && num12 > 0 && num14 > 0 && num15 > 0 && num16 > 0 && num17 > 0 && num18 > 0 && num19 > 0 && num20 > 0 && num21 > 0 && num22 > 0 && num23 > 0 && num24 > 0 && num25 > 0 && num26 > 0 && num27 > 0;
             if (tenthAnniversaryWorld && !remixWorld)
             {
                 flag9 = true;
             }
             if (NPC.unlockedPrincessSpawn)
             {
                 flag9 = true;
             }
             if (flag9 && num39 < 1)
             {
                 townNPCCanSpawn[663] = true;
             }
             int num42 = WorldGen.prioritizedTownNPCType;
             if (num42 == 0 && NPC.boughtCat && num28 < 1)
             {
                 num42 = 637;
             }
             if (num42 == 0 && NPC.boughtDog && num29 < 1)
             {
                 num42 = 638;
             }
             if (num42 == 0 && NPC.boughtBunny && num30 < 1)
             {
                 num42 = 656;
             }
             if (num42 == 0 && NPC.unlockedSlimeBlueSpawn && num31 < 1)
             {
                 num42 = 670;
             }
             if (num42 == 0 && flag8 && num32 < 1)
             {
                 num42 = 678;
             }
             if (num42 == 0 && NPC.unlockedSlimeOldSpawn && num33 < 1)
             {
                 num42 = 679;
             }
             if (num42 == 0 && NPC.unlockedSlimePurpleSpawn && num34 < 1)
             {
                 num42 = 680;
             }
             if (num42 == 0 && NPC.unlockedSlimeRainbowSpawn && num35 < 1)
             {
                 num42 = 681;
             }
             if (num42 == 0 && NPC.unlockedSlimeRedSpawn && num36 < 1)
             {
                 num42 = 682;
             }
             if (num42 == 0 && NPC.unlockedSlimeYellowSpawn && num37 < 1)
             {
                 num42 = 683;
             }
             if (num42 == 0 && NPC.unlockedSlimeCopperSpawn && num38 < 1)
             {
                 num42 = 684;
             }
             if (num42 == 0 && num6 < 1)
             {
                 num42 = 22;
             }
             if (num42 == 0 && flag && num2 < 1)
             {
                 num42 = 17;
             }
             if (num42 == 0 && flag3 && num3 < 1 && num2 > 0)
             {
                 num42 = 18;
             }
             if (num42 == 0 && flag2 && num5 < 1)
             {
                 num42 = 19;
             }
             if (num42 == 0 && NPC.savedGoblin && num11 < 1)
             {
                 num42 = 107;
             }
             if (num42 == 0 && NPC.savedTaxCollector && num24 < 1)
             {
                 num42 = 441;
             }
             if (num42 == 0 && NPC.savedWizard && num10 < 1)
             {
                 num42 = 108;
             }
             if (num42 == 0 && hardMode && num14 < 1)
             {
                 num42 = 160;
             }
             if (num42 == 0 && (NPC.downedBoss1 || NPC.downedBoss2 || NPC.downedBoss3) && num4 < 1)
             {
                 num42 = 20;
             }
             if (num42 == 0 && flag5 && num2 > 0 && num8 < 1)
             {
                 num42 = 38;
             }
             if (num42 == 0 && NPC.downedQueenBee && num20 < 1)
             {
                 num42 = 228;
             }
             if (num42 == 0 && NPC.downedMechBossAny && num15 < 1)
             {
                 num42 = 178;
             }
             if (num42 == 0 && NPC.savedMech && num12 < 1)
             {
                 num42 = 124;
             }
             if (num42 == 0 && NPC.savedAngler && num23 < 1)
             {
                 num42 = 369;
             }
             if (num42 == 0 && hardMode && NPC.downedPlantBoss && num18 < 1)
             {
                 num42 = 209;
             }
             if (num42 == 0 && NPC.downedPirates && num21 < 1)
             {
                 num42 = 229;
             }
             if (num42 == 0 && NPC.downedBoss3 && num9 < 1)
             {
                 num42 = 54;
             }
             if (num42 == 0 && NPC.savedStylist && num22 < 1)
             {
                 num42 = 353;
             }
             if (num42 == 0 && num40 >= 4 && flag4 && num16 < 1)
             {
                 num42 = 207;
             }
             if (num42 == 0 && num40 >= 8 && num19 < 1)
             {
                 num42 = 227;
             }
             if (num42 == 0 && flag7 && num17 < 1)
             {
                 num42 = 208;
             }
             if (num42 == 0 && NPC.downedFrost && num13 < 1 && xMas)
             {
                 num42 = 142;
             }
             if (num42 == 0 && NPC.savedBartender && num25 < 1)
             {
                 num42 = 550;
             }
             if (num42 == 0 && NPC.savedGolfer && num26 < 1)
             {
                 num42 = 588;
             }
             if (num42 == 0 && bestiaryProgressReport.CompletionPercent >= 0.1f && num27 < 1)
             {
                 num42 = 633;
             }
             if (num42 == 0 && flag9 && num39 < 1)
             {
                 num42 = 663;
             }
             WorldGen.prioritizedTownNPCType = num42;
         }
     }
References NPC.boughtBunny, NPC.boughtCat, NPC.boughtDog, checkForSpawns, BestiaryUnlockProgressReport.CompletionPercent, NPCID.Count, NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedFrost, NPC.downedMechBossAny, NPC.downedPirates, NPC.downedPlantBoss, NPC.downedQueenBee, dungeonX, dungeonY, BirthdayParty.GenuineParty, GetBestiaryProgressReport(), NPC.GetSpawnSourceForTownSpawn(), WorldGen.GetWorldUpdateRate(), hardMode, NPC.homeless, NPC.homeTileX, NPC.homeTileY, netMode, NPC.NewNPC(), UnifiedRandom.Next(), npc, player, WorldGen.prioritizedTownNPCType, WorldGen.QuickFindHome(), rand, remixWorld, NPC.savedAngler, NPC.savedBartender, NPC.savedGoblin, NPC.savedGolfer, NPC.savedMech, NPC.savedStylist, NPC.savedTaxCollector, NPC.savedWizard, NPC.SpawnAllowed_ArmsDealer(), NPC.SpawnAllowed_Demolitionist(), NPC.SpawnAllowed_DyeTrader(), NPC.SpawnAllowed_Merchant(), NPC.SpawnAllowed_Nurse(), tenthAnniversaryWorld, townNPCCanSpawn, NPC.unlockedPartyGirlSpawn, NPC.unlockedPrincessSpawn, NPC.unlockedSlimeBlueSpawn, NPC.unlockedSlimeCopperSpawn, NPC.unlockedSlimeGreenSpawn, NPC.unlockedSlimeOldSpawn, NPC.unlockedSlimePurpleSpawn, NPC.unlockedSlimeRainbowSpawn, NPC.unlockedSlimeRedSpawn, NPC.unlockedSlimeYellowSpawn, and xMas.
Referenced by UpdateTime().