Terraria: Main.DrawInterface
DrawInterface()
void Main.DrawInterface (GameTime gameTime) inline protected
     {
         _drawInterfaceGameTime = gameTime;
         if (_needToSetupDrawInterfaceLayers)
         {
             SetupDrawInterfaceLayers();
         }
         PlayerInput.SetZoom_UI();
         using (List<GameInterfaceLayer>.Enumerator enumerator = _gameInterfaceLayers.GetEnumerator())
         {
             while (enumerator.MoveNext() && enumerator.Current.Draw())
             {
             }
         }
         PlayerInput.SetZoom_World();
     }
References _drawInterfaceGameTime, _gameInterfaceLayers, _needToSetupDrawInterfaceLayers, SetupDrawInterfaceLayers(), PlayerInput.SetZoom_UI(), and PlayerInput.SetZoom_World().
Referenced by DoDraw().