Terraria: System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal
StoreAlignedNonTemporal() [12/20]
static unsafe void System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal (sbyte * address, Vector256< sbyte > source) inline static inherited
Definition at line 912 of file Avx.cs.
    {
        StoreAlignedNonTemporal(address, source);
    }
References System.source, and System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal().
Referenced by System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal(), and System.Runtime.Intrinsics.X86.Avx.StoreAlignedNonTemporal().