Terraria: System.Collections.Immutable.ImmutableSortedDictionary.Node.RemoveRecursive
RemoveRecursive()
Node System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.RemoveRecursive (TKey key, IComparer< TKey > keyComparer, out bool mutated) inline private
Definition at line 931 of file ImmutableSortedDictionary.cs.
        {
            if (IsEmpty)
            {
                mutated = false;
                return this;
            }
            Node node = this;
            int num = keyComparer.Compare(key, _key);
            if (num == 0)
            {
                mutated = true;
                if (_right.IsEmpty && _left.IsEmpty)
                {
                    node = EmptyNode;
                }
                else if (_right.IsEmpty && !_left.IsEmpty)
                {
                    node = _left;
                }
                else if (!_right.IsEmpty && _left.IsEmpty)
                {
                    node = _right;
                }
                else
                {
                    Node node2 = _right;
                    while (!node2._left.IsEmpty)
                    {
                        node2 = node2._left;
                    }
                    bool mutated2;
                    Node right = _right.Remove(node2._key, keyComparer, out mutated2);
                    node = node2.Mutate(_left, right);
                }
            }
            else if (num < 0)
            {
                Node left = _left.Remove(key, keyComparer, out mutated);
                if (mutated)
                {
                    node = Mutate(left);
                }
            }
            else
            {
                Node right2 = _right.Remove(key, keyComparer, out mutated);
                if (mutated)
                {
                    node = Mutate(null, right2);
                }
            }
            if (!node.IsEmpty)
            {
                return MakeBalanced(node);
            }
            return node;
        }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._key, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._left, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._right, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.EmptyNode, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.IsEmpty, System.key, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.MakeBalanced(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Mutate(), and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Remove().
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Remove().