Terraria: System.Collections.Immutable.ImmutableSortedDictionary.Node.RotateLeft
RotateLeft()
static Node System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.RotateLeft (Node tree) inline static private
Definition at line 782 of file ImmutableSortedDictionary.cs.
        {
            Requires.NotNull(tree, "tree");
            if (tree._right.IsEmpty)
            {
                return tree;
            }
            Node right = tree._right;
            return right.Mutate(tree.Mutate(null, right._left));
        }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._left, and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Mutate().
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.DoubleLeft(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.DoubleRight(), and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.MakeBalanced().