Terraria: System.Collections.Immutable.ImmutableSortedDictionary.Node.SetOrAdd
SetOrAdd()
Node System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.SetOrAdd (TKey key, TValue value, IComparer< TKey > keyComparer, IEqualityComparer< TValue > valueComparer, bool overwriteExistingValue, out bool replacedExistingValue, out bool mutated) inline private
Definition at line 883 of file ImmutableSortedDictionary.cs.
        {
            replacedExistingValue = false;
            if (IsEmpty)
            {
                mutated = true;
                return new Node(key, value, this, this);
            }
            Node node = this;
            int num = keyComparer.Compare(key, _key);
            if (num > 0)
            {
                Node right = _right.SetOrAdd(key, value, keyComparer, valueComparer, overwriteExistingValue, out replacedExistingValue, out mutated);
                if (mutated)
                {
                    node = Mutate(null, right);
                }
            }
            else if (num < 0)
            {
                Node left = _left.SetOrAdd(key, value, keyComparer, valueComparer, overwriteExistingValue, out replacedExistingValue, out mutated);
                if (mutated)
                {
                    node = Mutate(left);
                }
            }
            else
            {
                if (valueComparer.Equals(_value, value))
                {
                    mutated = false;
                    return this;
                }
                if (!overwriteExistingValue)
                {
                    throw new ArgumentException(System.SR.Format(System.SR.DuplicateKey, key));
                }
                mutated = true;
                replacedExistingValue = true;
                node = new Node(key, value, _left, _right);
            }
            if (!mutated)
            {
                return node;
            }
            return MakeBalanced(node);
        }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Node(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._key, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._left, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._right, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._value, System.SR.DuplicateKey, System.SR.Format(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.IsEmpty, System.key, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.MakeBalanced(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Mutate(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.SetOrAdd(), and System.value.
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Add(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.SetItem(), and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.SetOrAdd().