Terraria: System.Collections.Immutable.ImmutableSortedDictionary.Node.Search
Search()
Node System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Search (TKey key, IComparer< TKey > keyComparer) inline private
Definition at line 1008 of file ImmutableSortedDictionary.cs.
        {
            if (IsEmpty)
            {
                return this;
            }
            int num = keyComparer.Compare(key, _key);
            if (num == 0)
            {
                return this;
            }
            if (num > 0)
            {
                return _right.Search(key, keyComparer);
            }
            return _left.Search(key, keyComparer);
        }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._key, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._left, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._right, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.IsEmpty, System.key, and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Search().
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Contains(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.ContainsKey(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Search(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.TryGetKey(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.TryGetValue(), and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.ValueRef().