Terraria: System.Collections.Immutable.ImmutableSortedDictionary.Node.RotateRight
RotateRight()
static Node System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.RotateRight (Node tree) inline static private
Definition at line 793 of file ImmutableSortedDictionary.cs.
        {
            Requires.NotNull(tree, "tree");
            if (tree._left.IsEmpty)
            {
                return tree;
            }
            Node left = tree._left;
            return left.Mutate(null, tree.Mutate(left._right));
        }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._right, and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Mutate().
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.DoubleLeft(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.DoubleRight(), and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.MakeBalanced().