Terraria: System.Collections.Immutable.ImmutableSortedDictionary.Node.Freeze
Freeze()
void System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Freeze () inline package
Definition at line 772 of file ImmutableSortedDictionary.cs.
        {
            if (!_frozen)
            {
                _left.Freeze();
                _right.Freeze();
                _frozen = true;
            }
        }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._frozen, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._left, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node._right, and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Freeze().
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.ImmutableSortedDictionary(), and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.Freeze().