Terraria: System.Xml.IXmlLineInfo.HasLineInfo
HasLineInfo()
bool System.Xml.IXmlLineInfo.HasLineInfo ()
Implemented in System.Runtime.Serialization.XmlSerializableReader, System.Xml.XmlDictionaryReader.XmlWrappedReader, System.Xml.XmlUTF8TextReader, System.Xml.Linq.XNodeReader, System.Xml.Linq.XObject, System.Xml.XPath.XNodeNavigator, MS.Internal.Xml.Cache.XPathDocumentNavigator, System.Xml.PositionInfo, System.Xml.ReaderPositionInfo, System.Xml.XmlAsyncCheckReaderWithLineInfo, System.Xml.XmlSubtreeReader, System.Xml.XmlTextReader, System.Xml.XmlTextReaderImpl, System.Xml.XmlValidatingReader, System.Xml.XmlValidatingReaderImpl, System.Xml.XmlWrappingReader, System.Xml.XsdCachingReader, and System.Xml.XsdValidatingReader.
Referenced by System.Xml.ReaderPositionInfo.HasLineInfo(), System.Xml.XmlAsyncCheckReaderWithLineInfo.HasLineInfo(), System.Xml.XmlWrappingReader.HasLineInfo(), System.Xml.Linq.XDocument.InitLoad(), System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(), System.Xml.Linq.XContainer.ContentReader.ReadContentFromAsync(), System.Xml.XmlExceptionHelper.ThrowXmlException(), and System.Xml.XmlExceptionHelper.ThrowXmlException().