Terraria: System.Xml.XmlAsyncCheckWriter.CheckAsync
CheckAsync()
void System.Xml.XmlAsyncCheckWriter.CheckAsync () inline private
Definition at line 58 of file XmlAsyncCheckWriter.cs.
    {
        if (!_lastTask.IsCompleted)
        {
            throw new InvalidOperationException(System.SR.Xml_AsyncIsRunningException);
        }
    }
References System.Xml.XmlAsyncCheckWriter._lastTask, System.Threading.Tasks.Task< TResult >.IsCompleted, and System.SR.Xml_AsyncIsRunningException.
Referenced by System.Xml.XmlAsyncCheckWriter.Close(), System.Xml.XmlAsyncCheckWriter.Dispose(), System.Xml.XmlAsyncCheckWriter.DisposeAsyncCore(), System.Xml.XmlAsyncCheckWriter.Flush(), System.Xml.XmlAsyncCheckWriter.FlushAsync(), System.Xml.XmlAsyncCheckWriter.LookupPrefix(), System.Xml.XmlAsyncCheckWriter.WriteAttributes(), System.Xml.XmlAsyncCheckWriter.WriteAttributesAsync(), System.Xml.XmlAsyncCheckWriter.WriteBase64(), System.Xml.XmlAsyncCheckWriter.WriteBase64Async(), System.Xml.XmlAsyncCheckWriter.WriteBinHex(), System.Xml.XmlAsyncCheckWriter.WriteBinHexAsync(), System.Xml.XmlAsyncCheckWriter.WriteCData(), System.Xml.XmlAsyncCheckWriter.WriteCDataAsync(), System.Xml.XmlAsyncCheckWriter.WriteCharEntity(), System.Xml.XmlAsyncCheckWriter.WriteCharEntityAsync(), System.Xml.XmlAsyncCheckWriter.WriteChars(), System.Xml.XmlAsyncCheckWriter.WriteCharsAsync(), System.Xml.XmlAsyncCheckWriter.WriteComment(), System.Xml.XmlAsyncCheckWriter.WriteCommentAsync(), System.Xml.XmlAsyncCheckWriter.WriteDocType(), System.Xml.XmlAsyncCheckWriter.WriteDocTypeAsync(), System.Xml.XmlAsyncCheckWriter.WriteEndAttribute(), System.Xml.XmlAsyncCheckWriter.WriteEndAttributeAsync(), System.Xml.XmlAsyncCheckWriter.WriteEndDocument(), System.Xml.XmlAsyncCheckWriter.WriteEndDocumentAsync(), System.Xml.XmlAsyncCheckWriter.WriteEndElement(), System.Xml.XmlAsyncCheckWriter.WriteEndElementAsync(), System.Xml.XmlAsyncCheckWriter.WriteEntityRef(), System.Xml.XmlAsyncCheckWriter.WriteEntityRefAsync(), System.Xml.XmlAsyncCheckWriter.WriteFullEndElement(), System.Xml.XmlAsyncCheckWriter.WriteFullEndElementAsync(), System.Xml.XmlAsyncCheckWriter.WriteName(), System.Xml.XmlAsyncCheckWriter.WriteNameAsync(), System.Xml.XmlAsyncCheckWriter.WriteNmToken(), System.Xml.XmlAsyncCheckWriter.WriteNmTokenAsync(), System.Xml.XmlAsyncCheckWriter.WriteNode(), System.Xml.XmlAsyncCheckWriter.WriteNode(), System.Xml.XmlAsyncCheckWriter.WriteNodeAsync(), System.Xml.XmlAsyncCheckWriter.WriteNodeAsync(), System.Xml.XmlAsyncCheckWriter.WriteProcessingInstruction(), System.Xml.XmlAsyncCheckWriter.WriteProcessingInstructionAsync(), System.Xml.XmlAsyncCheckWriter.WriteQualifiedName(), System.Xml.XmlAsyncCheckWriter.WriteQualifiedNameAsync(), System.Xml.XmlAsyncCheckWriter.WriteRaw(), System.Xml.XmlAsyncCheckWriter.WriteRaw(), System.Xml.XmlAsyncCheckWriter.WriteRawAsync(), System.Xml.XmlAsyncCheckWriter.WriteRawAsync(), System.Xml.XmlAsyncCheckWriter.WriteStartAttribute(), System.Xml.XmlAsyncCheckWriter.WriteStartAttributeAsync(), System.Xml.XmlAsyncCheckWriter.WriteStartDocument(), System.Xml.XmlAsyncCheckWriter.WriteStartDocument(), System.Xml.XmlAsyncCheckWriter.WriteStartDocumentAsync(), System.Xml.XmlAsyncCheckWriter.WriteStartDocumentAsync(), System.Xml.XmlAsyncCheckWriter.WriteStartElement(), System.Xml.XmlAsyncCheckWriter.WriteStartElementAsync(), System.Xml.XmlAsyncCheckWriter.WriteString(), System.Xml.XmlAsyncCheckWriter.WriteStringAsync(), System.Xml.XmlAsyncCheckWriter.WriteSurrogateCharEntity(), System.Xml.XmlAsyncCheckWriter.WriteSurrogateCharEntityAsync(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteWhitespace(), and System.Xml.XmlAsyncCheckWriter.WriteWhitespaceAsync().