Terraria: System.Reflection.EventInfo.AddEventHandler
AddEventHandler() [2/2]
virtual void System.Reflection.EventInfo.AddEventHandler (object? target, Delegate? handler) inline virtual inherited
Definition at line 82 of file EventInfo.cs.
    {
        MethodInfo addMethod = GetAddMethod(nonPublic: false);
        if (addMethod == null)
        {
            throw new InvalidOperationException(SR.InvalidOperation_NoPublicAddMethod);
        }
        addMethod.Invoke(target, new object[1] { handler });
    }
References System.Reflection.EventInfo.GetAddMethod(), System.SR.InvalidOperation_NoPublicAddMethod, and System.Reflection.MethodBase.Invoke().
Referenced by System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler().