Terraria: System.Reflection.EventInfo.GetAddMethod
GetAddMethod() [1/2]
MethodInfo? System.Reflection.EventInfo.GetAddMethod () inline inherited
Definition at line 59 of file EventInfo.cs.
    {
        return GetAddMethod(nonPublic: false);
    }
References System.Reflection.EventInfo.GetAddMethod().
Referenced by System.Reflection.EventInfo.AddEventHandler(), System.ComponentModel.ReflectEventDescriptor.FillMethods(), System.Reflection.EventInfo.GetAddMethod(), System.Runtime.InteropServices.ComAwareEventInfo.GetAddMethod(), System.Reflection.EventInfoExtensions.GetAddMethod(), and System.Reflection.EventInfoExtensions.GetAddMethod().