Terraria: System.Threading.Tasks.ValueTask.FromException
FromException()
static ValueTask System.Threading.Tasks.ValueTask< TResult >.FromException (Exception exception) inline static
Definition at line 190 of file ValueTask.cs.
    {
        return new ValueTask(Task.FromException(exception));
    }
References System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.exception, and System.Threading.Tasks.Task< TResult >.FromException().
Referenced by System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.AcceptAsync(), System.Data.Common.DbConnection.BeginDbTransactionAsync(), System.Threading.TimerQueueTimer.CloseAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.DisconnectAsync(), System.Net.Security.AuthenticatedStream.DisposeAsync(), System.IO.BinaryWriter.DisposeAsync(), System.IO.Stream.DisposeAsync(), System.IO.TextWriter.DisposeAsync(), System.Net.Http.Http3RequestStream.Http3ReadStream.ReadAsync(), System.IO.MemoryStream.ReadAsync(), System.IO.UnmanagedMemoryStream.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsync(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.ReadAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync(), System.IO.Pipes.PipeStream.ReadAsyncCore(), System.IO.RandomAccess.ReadAtOffsetAsync(), System.IO.RandomAccess.ReadFileScatterAsync(), System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveFromAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(), System.Net.Sockets.Socket.SendFileAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendPacketsAsync(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendToAsync(), System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync(), System.Net.Http.Http2Connection.Http2Stream.Http2WriteStream.WriteAsync(), System.Net.Http.Http3RequestStream.Http3WriteStream.WriteAsync(), System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(), System.IO.MemoryStream.WriteAsync(), System.IO.UnmanagedMemoryStream.WriteAsync(), System.Security.Cryptography.CryptoStream.WriteAsync(), System.IO.Pipes.PipeStream.WriteAsyncCore(), System.IO.RandomAccess.WriteAtOffsetAsync(), System.IO.RandomAccess.WriteFileGatherAsync(), and System.Net.Security.SslStream.WriteSingleChunk< TIOAdapter >().