Terraria: System.Threading.Tasks.ValueTask.ConfigureAwait
ConfigureAwait() [1/2]
ConfiguredValueTaskAwaitable System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait (bool continueOnCapturedContext) inline
Definition at line 312 of file ValueTask.cs.
    {
        ValueTask value = new ValueTask(_obj, _token, continueOnCapturedContext);
        return new ConfiguredValueTaskAwaitable(in value);
    }
References System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.Threading.Tasks.ValueTask< TResult >._obj, System.Threading.Tasks.ValueTask< TResult >._token, and System.value.
Referenced by System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(), System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(), System.Net.Sockets.TcpClient.CompleteConnectAsync(), System.Net.Http.ConnectHelper.ConnectQuicAsync(), System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(), System.Net.Http.HttpContent.CopyToAsync(), System.IO.BufferedStream.CopyToAsyncCore(), System.Net.Http.HttpConnection.CopyToContentLengthAsync(), System.Net.Http.HttpConnection.CopyToUntilEofWithExistingBufferedDataAsync(), System.IO.Compression.BrotliStream.DisposeAsync(), System.IO.Compression.DeflateStream.DisposeAsync(), System.IO.Strategies.BufferedFileStreamStrategy.DisposeAsync(), System.IO.BufferedStream.DisposeAsync(), System.Text.TranscodingStream.DisposeAsync(), System.Xml.XmlWriter.DisposeAsync(), System.Xml.XmlEncodedRawTextWriter.DisposeAsyncCore(), System.Xml.XmlUtf8RawTextWriter.DisposeAsyncCore(), System.Security.Cryptography.CryptoStream.DisposeAsyncCore(), System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), System.Net.Security.SslStream.FillHandshakeBufferAsync< TIOAdapter >(), System.IO.Compression.DeflateStream.FlushAsync(), System.IO.BufferedStream.FlushAsyncInternal(), System.Net.Http.HttpConnection.FlushThenWriteWithoutBufferingAsync(), System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(), System.Net.WebSockets.ManagedWebSocket.HandleReceivedPingPongAsync(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), System.IO.Compression.DeflateStream.PurgeBuffersAsync(), System.IO.StreamBuffer.ReadAsync(), System.Net.Quic.Implementations.Mock.MockStream.ReadAsync(), System.Net.Security.NegotiateStream.ReadAsync< TAdapter >(), System.IO.Compression.DeflateManagedStream.ReadAsyncCore(), System.IO.StreamReader.ReadAsyncInternal(), System.IO.TextReader.ReadBlockAsyncInternal(), System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(), System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(), System.IO.StreamReader.ReadLineAsyncInternal(), System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(), System.IO.StreamReader.ReadToEndAsyncInternal(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.WebSockets.ManagedWebSocket.SendCloseFrameAsync(), System.Net.Http.Http2Connection.Http2Stream.SendDataAsync(), System.Net.Http.HttpConnection.SendRequestContentAsync(), System.Net.Http.Http2Connection.SendStreamDataAsync(), System.Net.WebSockets.ManagedWebSocket.WaitForWriteTaskAsync(), System.Net.Quic.Implementations.Mock.MockStream.WriteAsync(), System.IO.StreamBuffer.WriteAsync(), System.Net.Http.HttpConnection.WriteAsync(), System.Net.Quic.Implementations.Mock.MockStream.WriteAsync(), System.IO.Compression.DeflateStream.WriteAsyncMemory(), System.Net.Http.HttpConnection.WriteByteSlowAsync(), System.Net.Http.HttpConnection.WriteBytesSlowAsync(), and System.Net.Security.SslStream.WriteSingleChunk< TIOAdapter >().