Terraria: System.Threading.Tasks.ValueTask.AsTask
AsTask() [1/2]
Task System.Threading.Tasks.ValueTask< TResult >.AsTask () inline
Definition at line 233 of file ValueTask.cs.
    {
        object obj = _obj;
        object obj2;
        if (obj != null)
        {
            obj2 = obj as Task;
            if (obj2 == null)
            {
                return GetTaskForValueTaskSource(Unsafe.As<IValueTaskSource>(obj));
            }
        }
        else
        {
            obj2 = Task.CompletedTask;
        }
        return (Task)obj2;
    }
References System.Threading.Tasks.ValueTask< TResult >._obj, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Threading.Tasks.ValueTask< TResult >.GetTaskForValueTaskSource(), and System.obj.
Referenced by System.Net.Http.Http3Connection.Abort(), System.IO.Strategies.Net5CompatFileStreamStrategy.BeginWrite(), System.Net.Http.Http3Connection.CheckForShutdown(), System.Threading.Tasks.ValueTask< TResult >.Preserve(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Read(), System.IO.Compression.DeflateManagedStream.ReadAsync(), System.IO.Compression.DeflateStream.ReadAsync(), System.IO.Pipes.PipeStream.ReadAsync(), System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync(), System.IO.BufferedStream.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsync(), System.IO.StreamReader.ReadAsync(), System.IO.TextReader.ReadAsync(), System.IO.TextReader.ReadBlockAsync(), System.IO.StreamReader.ReadBlockAsync(), System.Net.Http.HttpMessageHandlerStage.Send(), System.Net.WebSockets.ManagedWebSocket.SendKeepAliveFrameAsync(), System.IO.StreamBuffer.ResettableValueTaskSource.Wait(), System.IO.Pipes.NamedPipeServerStream.WaitForConnection(), System.IO.Pipes.NamedPipeServerStream.WaitForConnectionAsync(), System.Net.Http.Http2Connection.Http2Stream.WaitForData(), System.Net.WebSockets.ManagedWebSocket.WaitForServerToCloseConnectionAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.Write(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Write(), System.IO.Compression.DeflateStream.CopyToStream.WriteAsync(), System.IO.Compression.DeflateStream.WriteAsync(), System.IO.Pipes.PipeStream.WriteAsync(), System.Net.Sockets.NetworkStream.WriteAsync(), System.IO.Strategies.Net5CompatFileStreamStrategy.WriteAsync(), and System.Security.Cryptography.CryptoStream.WriteAsync().