Terraria: System.Threading.Tasks.ValueTask.FromCanceled
FromCanceled()
static ValueTask System.Threading.Tasks.ValueTask< TResult >.FromCanceled (CancellationToken cancellationToken) inline static
Definition at line 180 of file ValueTask.cs.
    {
        return new ValueTask(Task.FromCanceled(cancellationToken));
    }
References System.Threading.Tasks.ValueTask< TResult >.ValueTask(), System.cancellationToken, and System.Threading.Tasks.Task< TResult >.FromCanceled().
Referenced by System.Net.Sockets.Socket.AcceptAsync(), System.Data.Common.DbConnection.BeginDbTransactionAsync(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.Socket.DisconnectAsync(), System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(), System.Net.Http.EmptyReadStream.ReadAsync(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsync(), System.IO.Stream.NullStream.ReadAsync(), System.Text.TranscodingStream.ReadAsync(), System.IO.Compression.BrotliStream.ReadAsync(), System.IO.Pipes.PipeStream.ReadAsync(), System.IO.ReadOnlyMemoryStream.ReadAsync(), System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync(), System.IO.BufferedStream.ReadAsync(), System.IO.FileStream.ReadAsync(), System.IO.MemoryStream.ReadAsync(), System.IO.UnmanagedMemoryStream.ReadAsync(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.ReadAsync(), System.IO.StreamReader.ReadAsync(), System.IO.StringReader.ReadAsync(), System.IO.RandomAccess.ReadAsync(), System.IO.RandomAccess.ReadAsync(), System.IO.Compression.DeflateManagedStream.ReadAsyncInternal(), System.IO.Compression.DeflateStream.ReadAsyncMemory(), System.IO.StreamReader.ReadBlockAsync(), System.IO.StringReader.ReadBlockAsync(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveFromAsync(), System.Net.Sockets.Socket.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.Socket.SendAsyncForNetworkStream(), System.Net.Sockets.Socket.SendFileAsync(), System.Net.Sockets.Socket.SendToAsync(), System.Threading.PeriodicTimer.State.WaitForNextTickAsync(), System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(), System.Text.TranscodingStream.WriteAsync(), System.IO.Compression.BrotliStream.WriteAsync(), System.IO.Pipes.PipeStream.WriteAsync(), System.IO.ChunkedMemoryStream.WriteAsync(), System.IO.Strategies.BufferedFileStreamStrategy.WriteAsync(), System.IO.BufferedStream.WriteAsync(), System.IO.FileStream.WriteAsync(), System.IO.MemoryStream.WriteAsync(), System.IO.Stream.NullStream.WriteAsync(), System.IO.UnmanagedMemoryStream.WriteAsync(), System.IO.RandomAccess.WriteAsync(), System.IO.RandomAccess.WriteAsync(), and System.IO.Compression.DeflateStream.WriteAsyncMemory().