Terraria: System.Threading.Tasks.ValueTask.GetTaskForValueTaskSource
GetTaskForValueTaskSource() [1/2]
Task System.Threading.Tasks.ValueTask< TResult >.GetTaskForValueTaskSource (IValueTaskSource t) inline private
Definition at line 261 of file ValueTask.cs.
    {
        ValueTaskSourceStatus status = t.GetStatus(_token);
        if (status != 0)
        {
            try
            {
                t.GetResult(_token);
                return Task.CompletedTask;
            }
            catch (Exception ex)
            {
                if (status == ValueTaskSourceStatus.Canceled)
                {
                    if (ex is OperationCanceledException ex2)
                    {
                        Task task = new Task();
                        task.TrySetCanceled(ex2.CancellationToken, ex2);
                        return task;
                    }
                    return s_canceledTask ?? (s_canceledTask = Task.FromCanceled(new CancellationToken(canceled: true)));
                }
                return Task.FromException(ex);
            }
        }
        return new ValueTaskSourceAsTask(t, _token);
    }
References System.Threading.Tasks.ValueTask< TResult >._token, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.Tasks.Sources.IValueTaskSource< out TResult >.GetResult(), System.Threading.Tasks.Sources.IValueTaskSource< out TResult >.GetStatus(), System.Threading.Tasks.ValueTask< TResult >.s_canceledTask, and System.task.
Referenced by System.Threading.Tasks.ValueTask< TResult >.AsTask().