Terraria: WorldGen.ActiveAndWalkableTile
ActiveAndWalkableTile()
static bool WorldGen.ActiveAndWalkableTile (int i, int j) inline static
     {
         try
         {
             Tile tile = Main.tile[i, j];
             if (tile == null)
             {
                 return true;
             }
             if (tile.active() && Main.tileSolid[tile.type] && !tile.inActive())
             {
                 return true;
             }
         }
         catch
         {
         }
         return false;
     }
References Tile.active(), Tile.inActive(), Main.tile, Main.tileSolid, and Tile.type.
Referenced by NPC.AI_123_Deerclops_FindSpotToSpawnSpike(), NPC.AI_123_Deerclops_TryMakingSpike(), NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), and TileDrawing.DrawTiles_EmitParticles().