Terraria: WorldGen.Check6x3
Check6x3()
static void WorldGen.Check6x3 (int i, int j, int type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         int num = i;
         int num2 = j;
         num += Main.tile[i, j].frameX / 18 * -1;
         num2 += Main.tile[i, j].frameY / 18 * -1;
         for (int k = num; k < num + 6; k++)
         {
             for (int l = num2; l < num2 + 3; l++)
             {
                 int num3 = (k - num) * 18;
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || Main.tile[k, l].frameX != num3 || Main.tile[k, l].frameY != (l - num2) * 18)
                 {
                     flag = true;
                 }
             }
             if (Main.tile[k, num2 + 3] == null)
             {
                 Main.tile[k, num2 + 3] = new Tile();
             }
             if (!SolidTileAllowBottomSlope(k, num2 + 3) && (!Main.tile[k, num2 + 3].nactive() || !Main.tileSolidTop[Main.tile[k, num2 + 3].type] || Main.tile[k, num2 + 3].frameY != 0))
             {
                 flag = true;
             }
         }
         if (!flag)
         {
             return;
         }
         destroyObject = true;
         for (int m = num; m < num + 6; m++)
         {
             for (int n = num2; n < num2 + 3; n++)
             {
                 if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                 {
                     KillTile(m, n);
                 }
             }
         }
         if (type == 275)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2162);
         }
         if (type == 413)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3565);
         }
         if (type == 414)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3566);
         }
         if (type == 276)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2163);
         }
         if (type == 277)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2164);
         }
         if (type == 278)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2165);
         }
         if (type == 279)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2166);
         }
         if (type == 280)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2167);
         }
         if (type == 281)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2168);
         }
         if (type == 296)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2186);
         }
         if (type == 297)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2187);
         }
         if (type == 309)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2206);
         }
         if (type == 358)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3070);
         }
         if (type == 359)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3071);
         }
         if (type == 542)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4396);
         }
         if (type == 550)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4461);
         }
         if (type == 551)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4462);
         }
         if (type == 553)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4473);
         }
         if (type == 554)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4474);
         }
         if (type == 558)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4481);
         }
         if (type == 559)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4483);
         }
         if (type == 599)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4882);
         }
         if (type == 600)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4883);
         }
         if (type == 601)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4884);
         }
         if (type == 602)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4885);
         }
         if (type == 603)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4886);
         }
         if (type == 604)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4887);
         }
         if (type == 605)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4888);
         }
         if (type == 606)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4889);
         }
         if (type == 607)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4890);
         }
         if (type == 608)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4891);
         }
         if (type == 609)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4892);
         }
         if (type == 610)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4893);
         }
         if (type == 611)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4894);
         }
         if (type == 612)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4895);
         }
         if (type == 632)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5213);
         }
         if (type == 640)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5301);
         }
         if (type == 643)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5314);
         }
         if (type == 644)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5315);
         }
         if (type == 645)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5316);
         }
         destroyObject = false;
         for (int num4 = num - 1; num4 < num + 7; num4++)
         {
             for (int num5 = num2 - 1; num5 < num2 + 4; num5++)
             {
                 TileFrame(num4, num5);
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.nactive(), Item.NewItem(), Main.tile, Main.tileSolidTop, and Tile.type.