Terraria: WorldGen.PlaceWire
PlaceWire()
static bool WorldGen.PlaceWire (int i, int j) inline static
     {
         if (!Main.tile[i, j].wire())
         {
             SoundEngine.PlaySound(0, i * 16, j * 16);
             Main.tile[i, j].wire(wire: true);
             return true;
         }
         return false;
     }
References SoundEngine.PlaySound(), Main.tile, and Tile.wire().
Referenced by MessageBuffer.GetData(), Player.ItemCheck_UseWiringTools(), Wiring.MassWireOperationStep(), and WorldUtils.WireLine().