Terraria: WorldGen.InWorld
InWorld()
static bool WorldGen.InWorld (int x, int y, int fluff = 0) inline static
     {
         if (x < fluff || x >= Main.maxTilesX - fluff || y < fluff || y >= Main.maxTilesY - fluff)
         {
             return false;
         }
         return true;
     }
References Main.maxTilesX, and Main.maxTilesY.
Referenced by DesertHive.AddTileVariance(), NPC.AI(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), NPC.AI_006_Worms(), NPC.AI_007_TownEntities(), Projectile.AI_010(), Projectile.AI_016(), NPC.AI_107_ImprovedWalkers(), NPC.AI_111_DD2LightningBug(), NPC.AI_112_FairyCritter(), Projectile.AI_121_StardustDragon(), Projectile.AI_155_MysticSnakeCoil(), BiomeTileCheck(), Player.CanDoWireStuffHere(), Wiring.CheckLogicGate(), Conditions.IsSolid.CheckValidity(), NPC.Collision_MoveSlopesAndStairFall(), WorldFile.ConvertOldTileEntities(), StrayMethods.CountSandHorizontally(), countWires(), Projectile.CreateGroundExplosion(), HiveBiome.CreateHiveTunnel(), DelegateMethods.CutTiles(), Gore.DeactivateIfOutsideOfWorld(), Player.DoEyebrellaRainEffect(), Main.DrawBackground(), Main.DrawBlack(), HitTile.DrawFreshAnimations(), Main.DrawProjDirect(), Main.DrawTileCracks(), Sandstorm.EmitDust(), Mount.EmitGolfCartWheelDust(), EmptyLiquid(), Collision.ExpandVertically(), TELogicSensor.FigureCheckType(), FillWallHolesInSpot(), NPC.FindCattailTop(), NPC.FindTreeBranch(), WorldGen.Spread.Gem(), GenerateWorld(), Projectile.GetAlpha(), NPC.GetBirdFlightRecommendation(), MessageBuffer.GetData(), Framing.GetTileSafely(), Gore.Gore_UpdateLeaf(), Wiring.HitSwitch(), CommonConditions.UndergroundBiome.InTemple(), DeadMansChestBiome.IsAGoodSpot(), CommonConditions.Depth.IsPlayerInFrontOfDirtWall(), IsTileNearby(), TileLightScanner.IsTileNullOrTouchingNull(), Collision.IsWorldPointSolid(), Player.ItemCheck_PlayInstruments(), WorldFile.LoadTileEntities(), Wiring.MassWireOperationStep(), mayanTrap(), WorldGen.Spread.Moss(), CaveHouseBiome.Place(), HiveBiome.Place(), DesertHive.PlaceClustersArea(), TileEntity.PlaceEntityNet(), PlaceLiquid(), placeTrap(), Utils.PlotTileArea(), TeleportHelpers.RequestMagicConchTeleportPosition(), DelegateMethods.SearchAvoidedByNPCs(), Projectile.Shimmer(), Item.Shimmering(), BlockBecauseYouAreOverAnImportantTile.ShouldBlockSmartInteract(), Main.snowing(), NPC.Spawning_FlyingAntlionCheck(), NPC.Spawning_SandstoneCheck(), NPC.SpawnTileOrAboveHasAnyWallInSet(), NPC.SpawnWOF(), WorldGen.Spread.Spider(), SmartCursorHelper.Step_Pickaxe_MineSolids(), Collision.StepConveyorBelt(), Collision.StepDown(), Collision.StepUp(), Player.TileInteractionsCheckLongDistance(), DoorOpeningHelper.TryGetHandler(), Player.TryInteractingWithMinecartTrackInNearbyArea(), Player.TryPlacingAGolfBallNearANearbyTee(), AmbientWindSystem.TrySpawningWind(), Liquid.UndergroundDesertCheck(), Gore.Update(), Player.Update(), Main.UpdateAudio_DecideOnNewMusic(), Player.UpdateBiomes(), Item.UpdateItem(), Wiring.UpdateMech(), NPC.UpdateNPC(), Mount.UseDrill(), WorldGen.Spread.Wall(), WorldGen.Spread.Wall2(), and WorldGen.Spread.WallDungeon().