Terraria: WorldGen.CloseDoor
CloseDoor()
static bool WorldGen.CloseDoor (int i, int j, bool forced = false) inline static
     {
         int num = 0;
         int num2 = i;
         int num3 = j;
         if (Main.tile[i, j] == null)
         {
             Main.tile[i, j] = new Tile();
         }
         int frameX = Main.tile[i, j].frameX;
         Tile tile = Main.tile[i, j];
         if (tile.type != 11)
         {
             return false;
         }
         int num4 = tile.frameY;
         int num5 = 0;
         int num6 = 0;
         while (num4 >= 54)
         {
             num4 -= 54;
             num5++;
         }
         if (frameX >= 72)
         {
             num5 += 36 * (frameX / 72);
             num6 += 54 * (frameX / 72);
         }
         num3 = j - num4 / 18;
         switch (frameX % 72)
         {
         case 0:
             num2 = i;
             num = 1;
             break;
         case 18:
             num2 = i - 1;
             num = 1;
             break;
         case 36:
             num2 = i + 1;
             num = -1;
             break;
         case 54:
             num2 = i;
             num = -1;
             break;
         }
         int num7 = num2;
         if (num == -1)
         {
             num7 = num2 - 1;
         }
         if (!forced)
         {
             for (int k = num3; k < num3 + 3; k++)
             {
                 if (!Collision.EmptyTile(num2, k, ignoreTiles: true))
                 {
                     return false;
                 }
             }
         }
         for (int l = num7; l < num7 + 2; l++)
         {
             for (int m = num3; m < num3 + 3; m++)
             {
                 if (l == num2)
                 {
                     if (Main.tile[l, m] == null)
                     {
                         Main.tile[l, m] = new Tile();
                     }
                     Main.tile[l, m].type = 10;
                     Main.tile[l, m].frameX = (short)(genRand.Next(3) * 18 + num6);
                 }
                 else
                 {
                     if (Main.tile[l, m] == null)
                     {
                         Main.tile[l, m] = new Tile();
                     }
                     Main.tile[l, m].active(active: false);
                 }
             }
         }
         if (Main.netMode != 1 && Wiring.running)
         {
             Wiring.SkipWire(num2, num3);
             Wiring.SkipWire(num2, num3 + 1);
             Wiring.SkipWire(num2, num3 + 2);
         }
         for (int n = num2 - 1; n <= num2 + 1; n++)
         {
             for (int num8 = num3 - 1; num8 <= num3 + 2; num8++)
             {
                 TileFrame(n, num8);
             }
         }
         SoundEngine.PlaySound(9, i * 16, j * 16);
         return true;
     }
References Tile.active(), Collision.EmptyTile(), Tile.frameX, Tile.frameY, Main.netMode, SoundEngine.PlaySound(), Wiring.running, Wiring.SkipWire(), Main.tile, and Tile.type.
Referenced by NPC.AI_007_TownEntities(), MessageBuffer.GetData(), Wiring.HitWireSingle(), Player.TileInteractionsUse(), and DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor().