Terraria: WorldGen.CloudLake
CloudLake()
static void WorldGen.CloudLake (int i, int j) inline static
     {
         //IL_0089: Unknown result type (might be due to invalid IL or missing references)
         //IL_009a: Unknown result type (might be due to invalid IL or missing references)
         //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
         //IL_0104: Unknown result type (might be due to invalid IL or missing references)
         //IL_011a: Unknown result type (might be due to invalid IL or missing references)
         //IL_012f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0563: Unknown result type (might be due to invalid IL or missing references)
         //IL_0574: Unknown result type (might be due to invalid IL or missing references)
         //IL_018f: Unknown result type (might be due to invalid IL or missing references)
         //IL_05c9: Unknown result type (might be due to invalid IL or missing references)
         //IL_05de: Unknown result type (might be due to invalid IL or missing references)
         //IL_05f9: Unknown result type (might be due to invalid IL or missing references)
         //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
         //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
         //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
         //IL_02da: Unknown result type (might be due to invalid IL or missing references)
         //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
         //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
         //IL_0320: Unknown result type (might be due to invalid IL or missing references)
         //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
         //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
         //IL_0341: Unknown result type (might be due to invalid IL or missing references)
         //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
         //IL_0362: Unknown result type (might be due to invalid IL or missing references)
         //IL_0659: Unknown result type (might be due to invalid IL or missing references)
         //IL_07d6: Unknown result type (might be due to invalid IL or missing references)
         //IL_07d7: Unknown result type (might be due to invalid IL or missing references)
         //IL_07d8: Unknown result type (might be due to invalid IL or missing references)
         //IL_07dd: Unknown result type (might be due to invalid IL or missing references)
         //IL_0802: Unknown result type (might be due to invalid IL or missing references)
         //IL_0215: Unknown result type (might be due to invalid IL or missing references)
         //IL_0224: Unknown result type (might be due to invalid IL or missing references)
         //IL_0694: Unknown result type (might be due to invalid IL or missing references)
         //IL_0823: Unknown result type (might be due to invalid IL or missing references)
         //IL_06a6: Unknown result type (might be due to invalid IL or missing references)
         //IL_069c: Unknown result type (might be due to invalid IL or missing references)
         //IL_0844: Unknown result type (might be due to invalid IL or missing references)
         //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
         //IL_0865: Unknown result type (might be due to invalid IL or missing references)
         //IL_06e9: Unknown result type (might be due to invalid IL or missing references)
         //IL_06f8: Unknown result type (might be due to invalid IL or missing references)
         double num = genRand.Next(100, 150);
         double num2 = num;
         double num3 = genRand.Next(20, 30);
         int num4 = i;
         int num5 = i;
         int num6 = i;
         int num7 = j;
         Vector2D val = default(Vector2D);
         val.X = i;
         val.Y = j;
         Vector2D val2 = default(Vector2D);
         val2.X = (double)genRand.Next(-20, 21) * 0.2;
         while (val2.X > -2.0 && val2.X < 2.0)
         {
             val2.X = (double)genRand.Next(-20, 21) * 0.2;
         }
         val2.Y = (double)genRand.Next(-20, -10) * 0.02;
         while (num > 0.0 && num3 > 0.0)
         {
             num -= (double)genRand.Next(4);
             num3 -= 1.0;
             int num8 = (int)(val.X - num * 0.5);
             int num9 = (int)(val.X + num * 0.5);
             int num10 = (int)(val.Y - num * 0.5);
             int num11 = (int)(val.Y + num * 0.5);
             if (num8 < 0)
             {
                 num8 = 0;
             }
             if (num9 > Main.maxTilesX)
             {
                 num9 = Main.maxTilesX;
             }
             if (num10 < 0)
             {
                 num10 = 0;
             }
             if (num11 > Main.maxTilesY)
             {
                 num11 = Main.maxTilesY;
             }
             num2 = num * (double)genRand.Next(80, 120) * 0.01;
             double num12 = val.Y + 1.0;
             for (int k = num8; k < num9; k++)
             {
                 if (genRand.Next(2) == 0)
                 {
                     num12 += (double)genRand.Next(-1, 2);
                 }
                 if (num12 < val.Y)
                 {
                     num12 = val.Y;
                 }
                 if (num12 > val.Y + 2.0)
                 {
                     num12 = val.Y + 2.0;
                 }
                 for (int l = num10; l < num11; l++)
                 {
                     if (!((double)l > num12))
                     {
                         continue;
                     }
                     double num13 = Math.Abs((double)k - val.X);
                     double num14 = Math.Abs((double)l - val.Y) * 3.0;
                     if (Math.Sqrt(num13 * num13 + num14 * num14) < num2 * 0.4)
                     {
                         if (k < num4)
{
                             num4 = k;
                         }
                         if (k > num5)
{
                             num5 = k;
                         }
                         if (l < num6)
{
                             num6 = l;
                         }
                         if (l > num7)
{
                             num7 = l;
                         }
                         Main.tile[k, l].active(active: true);
                         Main.tile[k, l].type = 189;
                         SquareTileFrame(k, l);
                     }
                 }
             }
             val += val2;
             val2.X += (double)genRand.Next(-20, 21) * 0.05;
             if (val2.X > 1.0)
             {
                 val2.X = 1.0;
             }
             if (val2.X < -1.0)
             {
                 val2.X = -1.0;
             }
             if (val2.Y > 0.2)
             {
                 val2.Y = -0.2;
             }
             if (val2.Y < -0.2)
             {
                 val2.Y = -0.2;
             }
         }
         int num15 = num4;
         int num17;
         for (num15 += genRand.Next(5); num15 < num5; num15 += genRand.Next(num17, (int)((double)num17 * 1.5)))
         {
             int num16 = num7;
             while (!Main.tile[num15, num16].active())
             {
                 num16--;
             }
             num16 += genRand.Next(-3, 4);
             num17 = genRand.Next(4, 8);
             int num18 = 189;
             if (genRand.Next(4) == 0)
             {
                 num18 = 196;
             }
             for (int m = num15 - num17; m <= num15 + num17; m++)
             {
                 for (int n = num16 - num17; n <= num16 + num17; n++)
                 {
                     if (n > num6)
                     {
                         double num19 = Math.Abs(m - num15);
                         double num20 = Math.Abs(n - num16) * 2;
                         if (Math.Sqrt(num19 * num19 + num20 * num20) < (double)(num17 + genRand.Next(2)))
{
                             Main.tile[m, n].active(active: true);
                             Main.tile[m, n].type = (ushort)num18;
                             SquareTileFrame(m, n);
                         }
                     }
                 }
             }
         }
         num = genRand.Next(80, 95);
         num2 = num;
         num3 = genRand.Next(10, 15);
         val.X = i;
         val.Y = num6;
         val2.X = (double)genRand.Next(-20, 21) * 0.2;
         while (val2.X > -2.0 && val2.X < 2.0)
         {
             val2.X = (double)genRand.Next(-20, 21) * 0.2;
         }
         val2.Y = (double)genRand.Next(-20, -10) * 0.02;
         while (num > 0.0 && num3 > 0.0)
         {
             num -= (double)genRand.Next(4);
             num3 -= 1.0;
             int num8 = (int)(val.X - num * 0.5);
             int num9 = (int)(val.X + num * 0.5);
             int num10 = num6 - 1;
             int num11 = (int)(val.Y + num * 0.5);
             if (num8 < 0)
             {
                 num8 = 0;
             }
             if (num9 > Main.maxTilesX)
             {
                 num9 = Main.maxTilesX;
             }
             if (num10 < 0)
             {
                 num10 = 0;
             }
             if (num11 > Main.maxTilesY)
             {
                 num11 = Main.maxTilesY;
             }
             num2 = num * (double)genRand.Next(80, 120) * 0.01;
             double num21 = val.Y + 1.0;
             for (int num22 = num8; num22 < num9; num22++)
             {
                 if (genRand.Next(2) == 0)
                 {
                     num21 += (double)genRand.Next(-1, 2);
                 }
                 if (num21 < val.Y)
                 {
                     num21 = val.Y;
                 }
                 if (num21 > val.Y + 2.0)
                 {
                     num21 = val.Y + 2.0;
                 }
                 for (int num23 = num10; num23 < num11; num23++)
                 {
                     if (!((double)num23 > num21 - 2.0))
                     {
                         continue;
                     }
                     double num24 = Math.Abs((double)num22 - val.X);
                     double num25 = Math.Abs((double)num23 - val.Y) * 3.0;
                     if (!(Math.Sqrt(num24 * num24 + num25 * num25) < num2 * 0.4) || Main.tile[num22, num23].type != 189)
                     {
                         continue;
                     }
                     Main.tile[num22, num23].active(active: false);
                     if ((double)num23 > num21 + 1.0)
                     {
                         if (WillWaterPlacedHereStayPut(num22, num23))
{
                             Main.tile[num22, num23].liquid = byte.MaxValue;
                         }
                         Main.tile[num22, num23].honey(honey: false);
                         Main.tile[num22, num23].lava(lava: false);
                     }
                 }
             }
             val += val2;
             val2.X += (double)genRand.Next(-20, 21) * 0.05;
             if (val2.X > 1.0)
             {
                 val2.X = 1.0;
             }
             if (val2.X < -1.0)
             {
                 val2.X = -1.0;
             }
             if (val2.Y > 0.2)
             {
                 val2.Y = -0.2;
             }
             if (val2.Y < 0.0)
             {
                 val2.Y = 0.0;
             }
         }
         for (int num26 = num4 - 20; num26 <= num5 + 20; num26++)
         {
             for (int num27 = num6 - 20; num27 <= num7 + 20; num27++)
             {
                 bool flag = true;
                 for (int num28 = num26 - 1; num28 <= num26 + 1; num28++)
                 {
                     for (int num29 = num27 - 1; num29 <= num27 + 1; num29++)
                     {
                         if (!Main.tile[num28, num29].active())
{
                             flag = false;
                         }
                     }
                 }
                 if (flag)
                 {
                     Main.tile[num26, num27].wall = 73;
                 }
             }
         }
         for (int num30 = num4; num30 <= num5; num30++)
         {
             int num31;
             for (num31 = num6 - 10; !Main.tile[num30, num31 + 1].active(); num31++)
             {
             }
             if (num31 >= num7 || Main.tile[num30, num31 + 1].type != 189)
             {
                 continue;
             }
             if (genRand.Next(10) == 0)
             {
                 int num32 = genRand.Next(1, 3);
                 for (int num33 = num30 - num32; num33 <= num30 + num32; num33++)
                 {
                     if (Main.tile[num33, num31].type == 189 && WillWaterPlacedHereStayPut(num33, num31))
                     {
                         Main.tile[num33, num31].active(active: false);
                         Main.tile[num33, num31].liquid = byte.MaxValue;
                         Main.tile[num33, num31].lava(lava: false);
                         SquareTileFrame(num30, num31);
                     }
                     if (Main.tile[num33, num31 + 1].type == 189 && WillWaterPlacedHereStayPut(num33, num31 + 1))
                     {
                         Main.tile[num33, num31 + 1].active(active: false);
                         Main.tile[num33, num31 + 1].liquid = byte.MaxValue;
                         Main.tile[num33, num31 + 1].lava(lava: false);
                         SquareTileFrame(num30, num31 + 1);
                     }
                     if (num33 > num30 - num32 && num33 < num30 + 2 && Main.tile[num33, num31 + 2].type == 189 && WillWaterPlacedHereStayPut(num33, num31 + 2))
                     {
                         Main.tile[num33, num31 + 2].active(active: false);
                         Main.tile[num33, num31 + 2].liquid = byte.MaxValue;
                         Main.tile[num33, num31 + 2].lava(lava: false);
                         SquareTileFrame(num30, num31 + 2);
                     }
                 }
             }
             if (genRand.Next(5) == 0 && WillWaterPlacedHereStayPut(num30, num31))
             {
                 Main.tile[num30, num31].liquid = byte.MaxValue;
             }
             Main.tile[num30, num31].lava(lava: false);
             SquareTileFrame(num30, num31);
         }
         int num34 = genRand.Next(1, 4);
         for (int num35 = 0; num35 <= num34; num35++)
         {
             int num36 = genRand.Next(num4 - 5, num5 + 5);
             int num37 = num6 - genRand.Next(20, 40);
             int num38 = genRand.Next(4, 8);
             int num39 = 189;
             if (genRand.Next(4) != 0)
             {
                 num39 = 196;
             }
             for (int num40 = num36 - num38; num40 <= num36 + num38; num40++)
             {
                 for (int num41 = num37 - num38; num41 <= num37 + num38; num41++)
                 {
                     double num42 = Math.Abs(num40 - num36);
                     double num43 = Math.Abs(num41 - num37) * 2;
                     if (Math.Sqrt(num42 * num42 + num43 * num43) < (double)(num38 + genRand.Next(-1, 2)))
                     {
                         Main.tile[num40, num41].active(active: true);
                         Main.tile[num40, num41].type = (ushort)num39;
                         SquareTileFrame(num40, num41);
                     }
                 }
             }
             for (int num44 = num36 - num38 + 2; num44 <= num36 + num38 - 2; num44++)
             {
                 int num45;
                 for (num45 = num37 - num38; !Main.tile[num44, num45].active(); num45++)
                 {
                 }
                 if (WillWaterPlacedHereStayPut(num44, num45))
                 {
                     Main.tile[num44, num45].active(active: false);
                     Main.tile[num44, num45].liquid = byte.MaxValue;
                     SquareTileFrame(num44, num45);
                 }
             }
         }
     }
References Tile.active(), Tile.honey(), Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.tile, Tile.type, Tile.wall, Vector2D.X, and Vector2D.Y.
Referenced by GenerateWorld().