Terraria: WorldGen.PlaceTile
PlaceTile()
static bool WorldGen.PlaceTile (int i, int j, int Type, bool mute = false, bool forced = false, int plr = -1, int style = 0) inline static
     {
         int num = Type;
         if (gen && Main.tile[i, j].active() && Main.tile[i, j].type == 488)
         {
             return false;
         }
         if (num >= TileID.Count)
         {
             return false;
         }
         bool result = false;
         if (i >= 0 && j >= 0 && i < Main.maxTilesX && j < Main.maxTilesY)
         {
             Tile tile = Main.tile[i, j];
             if (tile == null)
             {
                 tile = new Tile();
                 Main.tile[i, j] = tile;
             }
             if (tile.active())
             {
                 if (num == 23 && tile.type == 59)
                 {
                     num = 661;
                 }
                 if (num == 199 && tile.type == 59)
                 {
                     num = 662;
                 }
             }
             if (forced || Collision.EmptyTile(i, j) || !Main.tileSolid[num] || (num == 23 && tile.type == 0 && tile.active()) || (num == 199 && tile.type == 0 && tile.active()) || (num == 2 && tile.type == 0 && tile.active()) || (num == 109 && tile.type == 0 && tile.active()) || (num == 60 && tile.type == 59 && tile.active()) || (num == 661 && tile.type == 59 && tile.active()) || (num == 662 && tile.type == 59 && tile.active()) || (num == 70 && tile.type == 59 && tile.active()) || (num == 633 && tile.type == 57 && tile.active()) || (Main.tileMoss[num] && (tile.type == 1 || tile.type == 38) && tile.active()))
             {
                 if (num == 23 && (tile.type != 0 || !tile.active()))
                 {
                     return false;
                 }
                 if (num == 199 && (tile.type != 0 || !tile.active()))
                 {
                     return false;
                 }
                 if (num == 2 && (tile.type != 0 || !tile.active()))
                 {
                     return false;
                 }
                 if (num == 109 && (tile.type != 0 || !tile.active()))
                 {
                     return false;
                 }
                 if (num == 60 && (tile.type != 59 || !tile.active()))
                 {
                     return false;
                 }
                 if (num == 661 && (tile.type != 59 || !tile.active()))
                 {
                     return false;
                 }
                 if (num == 662 && (tile.type != 59 || !tile.active()))
                 {
                     return false;
                 }
                 if (num == 70 && (tile.type != 59 || !tile.active()))
                 {
                     return false;
                 }
                 if (num == 633 && (tile.type != 57 || !tile.active()))
                 {
                     return false;
                 }
                 if (Main.tileMoss[num])
                 {
                     if ((tile.type != 1 && tile.type != 38) || !tile.active())
                     {
                         return false;
                     }
                     if (tile.type == 38)
                     {
                         num = num switch
{
                             381 => 517,
                             534 => 535,
                             536 => 537,
                             539 => 540,
                             625 => 626,
                             627 => 628,
                             _ => 512 + num - 179,
                         };
                     }
                 }
                 if (num == 81)
                 {
                     if (Main.tile[i, j - 1] == null)
                     {
                         Main.tile[i, j - 1] = new Tile();
                     }
                     if (Main.tile[i, j + 1] == null)
                     {
                         Main.tile[i, j + 1] = new Tile();
                     }
                     if (Main.tile[i, j - 1].active())
                     {
                         return false;
                     }
                     if (!Main.tile[i, j + 1].active() || !Main.tileSolid[Main.tile[i, j + 1].type] || Main.tile[i, j + 1].halfBrick() || Main.tile[i, j + 1].slope() != 0)
                     {
                         return false;
                     }
                 }
                 if ((num == 373 || num == 375 || num == 374 || num == 461) && (Main.tile[i, j - 1] == null || Main.tile[i, j - 1].bottomSlope()))
                 {
                     return false;
                 }
                 if (tile.liquid > 0 || tile.checkingLiquid())
                 {
                     switch (num)
                     {
                     case 4:
                         if (style != 8 && style != 11 && style != 17)
{
                             return false;
                         }
                         break;
                     case 3:
                     case 20:
                     case 24:
                     case 27:
                     case 32:
                     case 51:
                     case 69:
                     case 72:
                     case 201:
                     case 352:
                     case 529:
                     case 624:
                     case 637:
                     case 656:
                         return false;
                     }
                 }
                 if (TileID.Sets.ResetsHalfBrickPlacementAttempt[num] && (!tile.active() || !Main.tileFrameImportant[tile.type]))
                 {
                     tile.halfBrick(halfBrick: false);
                     tile.frameY = 0;
                     tile.frameX = 0;
                 }
                 if (num == 624)
                 {
                     if ((!tile.active() || Main.tileCut[tile.type] || TileID.Sets.BreakableWhenPlacing[tile.type]) && HasValidGroundForAbigailsFlowerBelowSpot(i, j))
                     {
                         tile.active(active: true);
                         tile.type = 624;
                         tile.halfBrick(halfBrick: false);
                         tile.slope(0);
                         tile.frameX = 0;
                         tile.frameY = 0;
                     }
                 }
                 else if (num == 656)
                 {
                     if ((!tile.active() || Main.tileCut[tile.type] || TileID.Sets.BreakableWhenPlacing[tile.type]) && HasValidGroundForGlowTulipBelowSpot(i, j))
                     {
                         tile.active(active: true);
                         tile.type = 656;
                         tile.halfBrick(halfBrick: false);
                         tile.slope(0);
                         tile.frameX = 0;
                         tile.frameY = 0;
                     }
                 }
                 else if (num == 3 || num == 24 || num == 110 || num == 201 || num == 637)
                 {
                     if (IsFitToPlaceFlowerIn(i, j, num))
                     {
                         if (num == 24 && genRand.Next(13) == 0)
{
                             tile.active(active: true);
                             tile.type = 32;
                             SquareTileFrame(i, j);
                         }
                         else if (num == 201 && genRand.Next(13) == 0)
{
                             tile.active(active: true);
                             tile.type = 352;
                             SquareTileFrame(i, j);
                         }
                         else if (Main.tile[i, j + 1].type == 78 || Main.tile[i, j + 1].type == 380 || Main.tile[i, j + 1].type == 579)
{
                             tile.active(active: true);
                             tile.type = (ushort)num;
                             int num2 = genRand.NextFromList<int>(6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 24, 27, 30, 33, 36, 39, 42);
                             switch (num2)
{
                             case 21:
                             case 24:
                             case 27:
                             case 30:
                             case 33:
                             case 36:
                             case 39:
                             case 42:
                                 num2 += genRand.Next(3);
                                 break;
                             }
                             tile.frameX = (short)(num2 * 18);
                         }
                         else if (tile.wall >= 0 && tile.wall < WallID.Count && WallID.Sets.AllowsPlantsToGrow[tile.wall] && Main.tile[i, j + 1].wall >= 0 && Main.tile[i, j + 1].wall < WallID.Count && WallID.Sets.AllowsPlantsToGrow[Main.tile[i, j + 1].wall])
{
                             if (genRand.Next(50) == 0 || ((num == 24 || num == 201) && genRand.Next(40) == 0))
{
                                 tile.active(active: true);
                                 tile.type = (ushort)num;
                                 if (num == 201)
{
                                     tile.frameX = 270;
                                 }
                                 else
{
                                     tile.frameX = 144;
                                 }
                             }
                             else if (genRand.Next(35) == 0 || (Main.tile[i, j].wall >= 63 && Main.tile[i, j].wall <= 70))
{
                                 tile.active(active: true);
                                 tile.type = (ushort)num;
                                 int num3 = genRand.NextFromList<int>(6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20);
                                 if (num == 201)
{
                                     num3 = genRand.NextFromList<int>(6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22);
                                 }
                                 if (num == 637)
{
                                     num3 = genRand.NextFromList<int>(6, 7, 8, 9, 10);
                                 }
                                 tile.frameX = (short)(num3 * 18);
                             }
                             else
{
                                 tile.active(active: true);
                                 tile.type = (ushort)num;
                                 tile.frameX = (short)(genRand.Next(6) * 18);
                             }
                         }
                     }
                 }
                 else if (num == 61)
                 {
                     if (j + 1 < Main.maxTilesY && Main.tile[i, j + 1].active() && Main.tile[i, j + 1].slope() == 0 && !Main.tile[i, j + 1].halfBrick() && Main.tile[i, j + 1].type == 60)
                     {
                         bool flag = (double)j > Main.rockLayer || Main.remixWorld || remixWorldGen;
                         if (genRand.Next(16) == 0 && (double)j > Main.worldSurface)
{
                             tile.active(active: true);
                             tile.type = 69;
                             SquareTileFrame(i, j);
                         }
                         else if (genRand.Next(60) == 0 && flag)
{
                             tile.active(active: true);
                             tile.type = (ushort)num;
                             tile.frameX = 144;
                         }
                         else if (genRand.Next(230) == 0 && flag)
{
                             tile.active(active: true);
                             tile.type = (ushort)num;
                             tile.frameX = 162;
                         }
                         else if (genRand.Next(15) == 0)
{
                             tile.active(active: true);
                             tile.type = (ushort)num;
                             if (genRand.Next(3) != 0)
{
                                 tile.frameX = (short)(genRand.Next(2) * 18 + 108);
                             }
                             else
{
                                 tile.frameX = (short)(genRand.Next(13) * 18 + 180);
                             }
                         }
                         else
{
                             tile.active(active: true);
                             tile.type = (ushort)num;
                             tile.frameX = (short)(genRand.Next(6) * 18);
                         }
                     }
                 }
                 else if (num == 518)
                 {
                     PlaceLilyPad(i, j);
                 }
                 else if (num == 519)
                 {
                     PlaceCatTail(i, j);
                 }
                 else if (num == 529)
                 {
                     PlantSeaOat(i, j);
                 }
                 else if (num == 571)
                 {
                     PlaceBamboo(i, j);
                 }
                 else if (num == 549)
                 {
                     PlaceUnderwaterPlant(549, i, j);
                 }
                 else if (num == 71)
                 {
                     if (j + 1 < Main.maxTilesY && Main.tile[i, j + 1].active() && Main.tile[i, j + 1].slope() == 0 && !Main.tile[i, j + 1].halfBrick() && Main.tile[i, j + 1].type == 70)
                     {
                         Point point = new Point(-1, -1);
                         if ((double)j > Main.worldSurface)
{
                             point = PlaceCatTail(i, j);
                         }
                         if (InWorld(point.X, point.Y))
{
                             if (gen)
{
                                 int num4 = genRand.Next(14);
                                 for (int k = 0; k < num4; k++)
{
                                     GrowCatTail(point.X, point.Y);
                                 }
                                 SquareTileFrame(point.X, point.Y);
                             }
                         }
                         else
{
                             tile.active(active: true);
                             tile.type = (ushort)num;
                             tile.frameX = (short)(genRand.Next(5) * 18);
                         }
                     }
                 }
                 else if (num == 129)
                 {
                     if (SolidTile(i - 1, j) || SolidTile(i + 1, j) || SolidTile(i, j - 1) || SolidTile(i, j + 1))
                     {
                         tile.active(active: true);
                         tile.type = (ushort)num;
                         tile.frameX = (short)(style * 18);
                         SquareTileFrame(i, j);
                     }
                 }
                 else if (num == 178)
                 {
                     if (SolidTile(i - 1, j, noDoors: true) || SolidTile(i + 1, j, noDoors: true) || SolidTile(i, j - 1) || SolidTile(i, j + 1))
                     {
                         tile.active(active: true);
                         tile.type = (ushort)num;
                         tile.frameX = (short)(style * 18);
                         tile.frameY = (short)(genRand.Next(3) * 18);
                         SquareTileFrame(i, j);
                     }
                 }
                 else if (num == 184)
                 {
                     if ((Main.tileMoss[Main.tile[i - 1, j].type] && SolidTile(i - 1, j)) || (Main.tileMoss[Main.tile[i + 1, j].type] && SolidTile(i + 1, j)) || (Main.tileMoss[Main.tile[i, j - 1].type] && SolidTile(i, j - 1)) || (Main.tileMoss[Main.tile[i, j + 1].type] && SolidTile(i, j + 1)))
                     {
                         tile.active(active: true);
                         tile.type = (ushort)num;
                         tile.frameX = (short)(style * 18);
                         tile.frameY = (short)(genRand.Next(3) * 18);
                         SquareTileFrame(i, j);
                     }
                     if ((TileID.Sets.tileMossBrick[Main.tile[i - 1, j].type] && SolidTile(i - 1, j)) || (TileID.Sets.tileMossBrick[Main.tile[i + 1, j].type] && SolidTile(i + 1, j)) || (TileID.Sets.tileMossBrick[Main.tile[i, j - 1].type] && SolidTile(i, j - 1)) || (TileID.Sets.tileMossBrick[Main.tile[i, j + 1].type] && SolidTile(i, j + 1)))
                     {
                         tile.active(active: true);
                         tile.type = (ushort)num;
                         tile.frameX = (short)(style * 18);
                         tile.frameY = (short)(genRand.Next(3) * 18);
                         SquareTileFrame(i, j);
                     }
                 }
                 else if (num == 485)
                 {
                     PlaceObject(i, j, num, mute, style);
                 }
                 else if (num == 171)
                 {
                     PlaceXmasTree(i, j, 171);
                 }
                 else if (num == 254)
                 {
                     Place2x2Style(i, j, (ushort)num, style);
                 }
                 else if (num == 335 || num == 564 || num == 594)
                 {
                     Place2x2(i, j, (ushort)num, 0);
                 }
                 else if (num == 654 || num == 319 || num == 132 || num == 484 || num == 138 || num == 664 || num == 142 || num == 143 || num == 282 || (num >= 288 && num <= 295) || (num >= 316 && num <= 318))
                 {
                     Place2x2(i, j, (ushort)num, 0);
                 }
                 else if (num == 411)
                 {
                     Place2x2(i, j, (ushort)num, 0);
                 }
                 else if (num == 457)
                 {
                     Place2x2Horizontal(i, j, 457, style);
                 }
                 else if (num == 137)
                 {
                     tile.active(active: true);
                     tile.type = (ushort)num;
                     tile.frameY = (short)(18 * style);
                 }
                 else if (num == 136)
                 {
                     if (Main.tile[i - 1, j] == null)
                     {
                         Main.tile[i - 1, j] = new Tile();
                     }
                     if (Main.tile[i + 1, j] == null)
                     {
                         Main.tile[i + 1, j] = new Tile();
                     }
                     if (Main.tile[i, j + 1] == null)
                     {
                         Main.tile[i, j + 1] = new Tile();
                     }
                     if ((Main.tile[i - 1, j].nactive() && !Main.tile[i - 1, j].halfBrick() && !TileID.Sets.NotReallySolid[Main.tile[i - 1, j].type] && Main.tile[i - 1, j].slope() == 0 && (SolidTile(i - 1, j) || TileID.Sets.IsBeam[Main.tile[i - 1, j].type] || (Main.tile[i - 1, j].type == 5 && Main.tile[i - 1, j - 1].type == 5 && Main.tile[i - 1, j + 1].type == 5))) || (Main.tile[i + 1, j].nactive() && !Main.tile[i + 1, j].halfBrick() && !TileID.Sets.NotReallySolid[Main.tile[i + 1, j].type] && Main.tile[i + 1, j].slope() == 0 && (SolidTile(i + 1, j) || TileID.Sets.IsBeam[Main.tile[i + 1, j].type] || (Main.tile[i + 1, j].type == 5 && Main.tile[i + 1, j - 1].type == 5 && Main.tile[i + 1, j + 1].type == 5))) || (Main.tile[i, j + 1].nactive() && !Main.tile[i, j + 1].halfBrick() && SolidTile(i, j + 1) && Main.tile[i, j + 1].slope() == 0) || tile.wall > 0)
                     {
                         tile.active(active: true);
                         tile.type = (ushort)num;
                         SquareTileFrame(i, j);
                     }
                 }
                 else if (num == 442)
                 {
                     if (Main.tile[i - 1, j] == null)
                     {
                         Main.tile[i - 1, j] = new Tile();
                     }
                     if (Main.tile[i + 1, j] == null)
                     {
                         Main.tile[i + 1, j] = new Tile();
                     }
                     if (Main.tile[i, j + 1] == null)
                     {
                         Main.tile[i, j + 1] = new Tile();
                     }
                     if ((Main.tile[i - 1, j].nactive() && !Main.tile[i - 1, j].halfBrick() && !TileID.Sets.NotReallySolid[Main.tile[i - 1, j].type] && Main.tile[i - 1, j].slope() == 0 && (SolidTile(i - 1, j) || TileID.Sets.IsBeam[Main.tile[i - 1, j].type] || (Main.tile[i - 1, j].type == 5 && Main.tile[i - 1, j - 1].type == 5 && Main.tile[i - 1, j + 1].type == 5))) || (Main.tile[i + 1, j].nactive() && !Main.tile[i + 1, j].halfBrick() && !TileID.Sets.NotReallySolid[Main.tile[i + 1, j].type] && Main.tile[i + 1, j].slope() == 0 && (SolidTile(i + 1, j) || TileID.Sets.IsBeam[Main.tile[i + 1, j].type] || (Main.tile[i + 1, j].type == 5 && Main.tile[i + 1, j - 1].type == 5 && Main.tile[i + 1, j + 1].type == 5))) || (Main.tile[i, j + 1].nactive() && !Main.tile[i, j + 1].halfBrick() && SolidTile(i, j + 1) && Main.tile[i, j + 1].slope() == 0))
                     {
                         tile.active(active: true);
                         tile.type = (ushort)num;
                         SquareTileFrame(i, j);
                     }
                 }
                 else if (num == 4)
                 {
                     if (Main.tile[i - 1, j] == null)
                     {
                         Main.tile[i - 1, j] = new Tile();
                     }
                     if (Main.tile[i + 1, j] == null)
                     {
                         Main.tile[i + 1, j] = new Tile();
                     }
                     if (Main.tile[i, j + 1] == null)
                     {
                         Main.tile[i, j + 1] = new Tile();
                     }
                     Tile tile2 = Main.tile[i - 1, j];
                     Tile tile3 = Main.tile[i + 1, j];
                     Tile tile4 = Main.tile[i, j + 1];
                     if (tile.wall > 0 || (tile2.active() && (tile2.slope() == 0 || tile2.slope() % 2 != 1) && ((Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type] && !TileID.Sets.NotReallySolid[tile2.type]) || TileID.Sets.IsBeam[tile2.type] || (IsTreeType(tile2.type) && IsTreeType(Main.tile[i - 1, j - 1].type) && IsTreeType(Main.tile[i - 1, j + 1].type)))) || (tile3.active() && (tile3.slope() == 0 || tile3.slope() % 2 != 0) && ((Main.tileSolid[tile3.type] && !Main.tileSolidTop[tile3.type] && !TileID.Sets.NotReallySolid[tile3.type]) || TileID.Sets.IsBeam[tile3.type] || (IsTreeType(tile3.type) && IsTreeType(Main.tile[i + 1, j - 1].type) && IsTreeType(Main.tile[i + 1, j + 1].type)))) || (tile4.active() && Main.tileSolid[tile4.type] && ((TileID.Sets.Platforms[tile4.type] && TopEdgeCanBeAttachedTo(i, j + 1)) || ((!Main.tileSolidTop[tile4.type] || (tile4.type == 380 && tile4.slope() == 0)) && !TileID.Sets.NotReallySolid[tile4.type] && !tile4.halfBrick() && tile4.slope() == 0))))
                     {
                         tile.active(active: true);
                         tile.type = (ushort)num;
                         tile.frameY = (short)(22 * style);
                         SquareTileFrame(i, j);
                     }
                 }
                 else if (num == 10)
                 {
                     if (Main.tile[i, j - 1] == null)
                     {
                         Main.tile[i, j - 1] = new Tile();
                     }
                     if (Main.tile[i, j - 2] == null)
                     {
                         Main.tile[i, j - 2] = new Tile();
                     }
                     if (Main.tile[i, j - 3] == null)
                     {
                         Main.tile[i, j - 3] = new Tile();
                     }
                     if (Main.tile[i, j + 1] == null)
                     {
                         Main.tile[i, j + 1] = new Tile();
                     }
                     if (Main.tile[i, j + 2] == null)
                     {
                         Main.tile[i, j + 2] = new Tile();
                     }
                     if (Main.tile[i, j + 3] == null)
                     {
                         Main.tile[i, j + 3] = new Tile();
                     }
                     if (!Main.tile[i, j - 1].active() && !Main.tile[i, j - 2].active() && Main.tile[i, j - 3].active() && Main.tileSolid[Main.tile[i, j - 3].type])
                     {
                         PlaceDoor(i, j - 1, num, style);
                         SquareTileFrame(i, j);
                     }
                     else
                     {
                         if (Main.tile[i, j + 1].active() || Main.tile[i, j + 2].active() || !Main.tile[i, j + 3].active() || !Main.tileSolid[Main.tile[i, j + 3].type])
{
                             return false;
                         }
                         PlaceDoor(i, j + 1, num, style);
                         SquareTileFrame(i, j);
                     }
                 }
                 else if ((num >= 275 && num <= 281) || num == 296 || num == 297 || num == 309 || num == 358 || num == 359 || num == 413 || num == 414 || num == 542)
                 {
                     Place6x3(i, j, (ushort)num);
                 }
                 else if (num == 237 || num == 244 || num == 285 || num == 286 || num == 298 || num == 299 || num == 310 || num == 339 || num == 538 || (num >= 361 && num <= 364) || num == 532 || num == 533 || num == 486 || num == 488 || num == 544 || num == 582 || num == 619 || num == 629)
                 {
                     Place3x2(i, j, (ushort)num);
                 }
                 else if (num == 128)
                 {
                     PlaceMan(i, j, style);
                     SquareTileFrame(i, j);
                 }
                 else if (num == 269)
                 {
                     PlaceWoman(i, j, style);
                     SquareTileFrame(i, j);
                 }
                 else if (num == 334)
                 {
                     int style2 = 0;
                     if (style == -1)
                     {
                         style2 = 1;
                     }
                     Place3x3Wall(i, j, 334, style2);
                     SquareTileFrame(i, j);
                 }
                 else if (num == 149)
                 {
                     if (SolidTile(i - 1, j) || SolidTile(i + 1, j) || SolidTile(i, j - 1) || SolidTile(i, j + 1))
                     {
                         tile.frameX = (short)(18 * style);
                         tile.active(active: true);
                         tile.type = (ushort)num;
                         SquareTileFrame(i, j);
                     }
                 }
                 else if (num == 139 || num == 35)
                 {
                     PlaceMB(i, j, (ushort)num, style);
                     SquareTileFrame(i, j);
                 }
                 else if (num == 165)
                 {
                     PlaceTight(i, j);
                     SquareTileFrame(i, j);
                 }
                 else if (num == 235)
                 {
                     Place3x1(i, j, (ushort)num);
                     SquareTileFrame(i, j);
                 }
                 else if (num == 240)
                 {
                     Place3x3Wall(i, j, (ushort)num, style);
                 }
                 else if (num == 440)
                 {
                     Place3x3Wall(i, j, (ushort)num, style);
                 }
                 else if (num == 245)
                 {
                     Place2x3Wall(i, j, (ushort)num, style);
                 }
                 else if (num == 246)
                 {
                     Place3x2Wall(i, j, (ushort)num, style);
                 }
                 else if (num == 241)
                 {
                     Place4x3Wall(i, j, (ushort)num, style);
                 }
                 else if (num == 242)
                 {
                     Place6x4Wall(i, j, (ushort)num, style);
                 }
                 else if (num == 34)
                 {
                     PlaceChand(i, j, (ushort)num, style);
                     SquareTileFrame(i, j);
                 }
                 else if (num == 106 || num == 212 || num == 219 || num == 220 || num == 228 || num == 231 || num == 243 || num == 247 || num == 283 || (num >= 300 && num <= 308) || num == 354 || num == 355 || num == 491 || num == 642)
                 {
                     Place3x3(i, j, (ushort)num, style);
                     SquareTileFrame(i, j);
                 }
                 else
                 {
                     switch (num)
                     {
                     case 13:
                     case 33:
                     case 49:
                     case 50:
                     case 78:
                     case 174:
                     case 372:
                     case 646:
                         PlaceOnTable1x1(i, j, num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 14:
                     case 26:
                     case 86:
                     case 87:
                     case 88:
                     case 89:
                     case 114:
                     case 186:
                     case 187:
                     case 215:
                     case 217:
                     case 218:
                     case 377:
                     case 469:
                         Place3x2(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 236:
                         PlaceJunglePlant(i, j, (ushort)num, genRand.Next(3), 0);
                         SquareTileFrame(i, j);
                         break;
                     case 238:
                         PlaceJunglePlant(i, j, (ushort)num, 0, 0);
                         SquareTileFrame(i, j);
                         break;
                     case 20:
                     {
                         if (Main.tile[i, j + 1] == null)
{
                             Main.tile[i, j + 1] = new Tile();
                         }
                         int type = Main.tile[i, j + 1].type;
                         if (Main.tile[i, j + 1].active() && (type == 2 || type == 109 || type == 147 || type == 60 || type == 23 || type == 199 || type == 661 || type == 662 || type == 53 || type == 234 || type == 116 || type == 112))
{
                             Place1x2(i, j, (ushort)num, style);
                             SquareTileFrame(i, j);
                         }
                         break;
                     }
                     case 15:
                     case 216:
                     case 338:
                     case 390:
                         if (Main.tile[i, j - 1] == null)
{
                             Main.tile[i, j - 1] = new Tile();
                         }
                         if (Main.tile[i, j] == null)
{
                             Main.tile[i, j] = new Tile();
                         }
                         Place1x2(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 227:
                         PlaceDye(i, j, style);
                         SquareTileFrame(i, j);
                         break;
                     case 567:
                         PlaceGnome(i, j, style);
                         SquareTileFrame(i, j);
                         break;
                     case 16:
                     case 18:
                     case 29:
                     case 103:
                     case 134:
                     case 462:
                         Place2x1(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 92:
                     case 93:
                     case 453:
                         Place1xX(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 104:
                     case 105:
                     case 320:
                     case 337:
                     case 349:
                     case 356:
                     case 378:
                     case 456:
                     case 506:
                     case 545:
                     case 663:
                         Place2xX(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 17:
                     case 77:
                     case 133:
                         Place3x2(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 207:
                         Place2xX(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 410:
                     case 480:
                     case 509:
                     case 657:
                     case 658:
                         Place2xX(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     case 465:
                     case 531:
                     case 591:
                     case 592:
                         Place2xX(i, j, (ushort)num, style);
                         SquareTileFrame(i, j);
                         break;
                     default:
                         if (TileID.Sets.BasicChest[num])
{
                             PlaceChest(i, j, (ushort)num, notNearOtherChests: false, style);
                             SquareTileFrame(i, j);
                             break;
                         }
                         switch (num)
{
                         case 91:
                             PlaceBanner(i, j, (ushort)num, style);
                             SquareTileFrame(i, j);
                             break;
                         case 419:
                         case 420:
                         case 423:
                         case 424:
                         case 429:
                         case 445:
                             PlaceLogicTiles(i, j, num, style);
                             SquareTileFrame(i, j);
                             break;
                         case 36:
                         case 135:
                         case 141:
                         case 144:
                         case 210:
                         case 239:
                         case 324:
                         case 476:
                         case 494:
                             Place1x1(i, j, num, style);
                             SquareTileFrame(i, j);
                             break;
                         case 101:
                         case 102:
                         case 463:
                             Place3x4(i, j, (ushort)num, style);
                             SquareTileFrame(i, j);
                             break;
                         case 464:
                         case 466:
                             Place5x4(i, j, (ushort)num, style);
                             SquareTileFrame(i, j);
                             break;
                         case 27:
                             PlaceSunflower(i, j, 27);
                             SquareTileFrame(i, j);
                             break;
                         case 28:
                             PlacePot(i, j, 28, genRand.Next(4));
                             SquareTileFrame(i, j);
                             break;
                         case 42:
                         case 270:
                         case 271:
                             Place1x2Top(i, j, (ushort)num, style);
                             SquareTileFrame(i, j);
                             break;
                         case 55:
                         case 425:
                         case 510:
                         case 511:
                             PlaceSign(i, j, (ushort)num, style);
                             break;
                         case 85:
                         case 376:
                             Place2x2Horizontal(i, j, (ushort)num, style);
                             break;
                         default:
                             if (Main.tileAlch[num])
{
                                 PlaceAlch(i, j, style);
                                 break;
                             }
                             switch (num)
{
                             case 94:
                             case 95:
                             case 97:
                             case 98:
                             case 99:
                             case 100:
                             case 125:
                             case 126:
                             case 172:
                             case 173:
                             case 287:
                                 Place2x2(i, j, (ushort)num, style);
                                 break;
                             case 96:
                                 Place2x2Style(i, j, (ushort)num, style);
                                 break;
                             case 79:
                             case 90:
{
                                 int direction = 1;
                                 if (plr > -1)
{
                                     direction = Main.player[plr].direction;
                                 }
                                 Place4x2(i, j, (ushort)num, direction, style);
                                 break;
                             }
                             case 209:
                                 PlaceCannon(i, j, (ushort)num, style);
                                 break;
                             case 81:
                                 tile.frameX = (short)(26 * genRand.Next(6));
                                 tile.active(active: true);
                                 tile.type = (ushort)num;
                                 break;
                             case 19:
                                 tile.frameY = (short)(18 * style);
                                 tile.active(active: true);
                                 tile.type = (ushort)num;
                                 break;
                             case 380:
                                 tile.frameY = (short)(18 * style);
                                 tile.active(active: true);
                                 tile.type = (ushort)num;
                                 break;
                             case 314:
                                 Minecart.PlaceTrack(tile, style);
                                 break;
                             default:
                                 tile.active(active: true);
                                 tile.type = (ushort)num;
                                 if (Main.tenthAnniversaryWorld && !Main.remixWorld && (num == 53 || num == 396 || num == 397))
{
                                     tile.color(7);
                                 }
                                 break;
                             }
                             break;
                         }
                         break;
                     }
                 }
                 if (tile.active())
                 {
                     if (TileID.Sets.BlocksWaterDrawingBehindSelf[tile.type])
                     {
                         SquareWallFrame(i, j);
                     }
                     SquareTileFrame(i, j);
                     result = true;
                     if (!mute)
                     {
                         switch (num)
{
                         case 127:
                             SoundEngine.PlaySound(SoundID.Item30, i * 16, j * 16);
                             break;
                         case 314:
                             SoundEngine.PlaySound(SoundID.Item52, i * 16, j * 16);
                             break;
                         case 330:
                         case 331:
                         case 332:
                         case 333:
                             SoundEngine.PlaySound(18, i * 16, j * 16);
                             break;
                         default:
                             SoundEngine.PlaySound(0, i * 16, j * 16);
                             break;
                         }
                         if (num == 22 || num == 140)
{
                             for (int l = 0; l < 3; l++)
{
                                 Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 14);
                             }
                         }
                     }
                 }
             }
         }
         return result;
     }
References Tile.active(), WallID.Sets.AllowsPlantsToGrow, TileID.Sets.BasicChest, TileID.Sets.BlocksWaterDrawingBehindSelf, Tile.bottomSlope(), TileID.Sets.BreakableWhenPlacing, Tile.checkingLiquid(), Tile.color(), TileID.Count, WallID.Count, Entity.direction, Collision.EmptyTile(), Tile.frameX, Tile.frameY, Tile.halfBrick(), TileID.Sets.IsBeam, SoundID.Item30, SoundID.Item52, Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Dust.NewDust(), TileID.Sets.NotReallySolid, Minecart.PlaceTrack(), TileID.Sets.Platforms, Main.player, SoundEngine.PlaySound(), Main.remixWorld, TileID.Sets.ResetsHalfBrickPlacementAttempt, Main.rockLayer, Tile.slope(), SolidTile, Main.tenthAnniversaryWorld, Main.tile, Main.tileAlch, Main.tileCut, Main.tileFrameImportant, Main.tileMoss, TileID.Sets.tileMossBrick, Main.tileSolid, Main.tileSolidTop, Tile.type, Tile.wall, and Main.worldSurface.
Referenced by DeadMansChestBiome.ActuallyPlaceBoulderTrap(), DesertHive.AddTileVariance(), NPC.AI_003_Fighters(), Projectile.AI_155_MysticSnakeCoil(), ActionGrass.Apply(), ActionPlaceStatue.Apply(), Actions.PlaceTile.Apply(), HouseBuilder.FillRooms(), WorldGen.Spread.Gem(), GenerateWorld(), MessageBuffer.GetData(), Liquid.LiquidCheck(), mayanTrap(), CampsiteBiome.Place(), EnchantedSwordBiome.Place(), MiningExplosivesBiome.Place(), MinecartDiggerHelper.PlaceATrack(), HouseBuilder.PlaceBiomeSpecificPriorityTool(), HouseBuilder.PlaceBiomeSpecificTool(), HouseBuilder.PlaceDoors(), placeLavaTrap(), PlaceLiquid(), TrackGenerator.PlacePath(), PlaceStatueTrap(), Player.PlaceThing_Tiles_PlaceIt(), placeTNTBarrel(), placeTrap(), Projectile.SpawnWebs(), WorldGen.Spread.Spider(), DelegateMethods.SpreadDirt(), Statue(), and StonePatch().