Terraria: WorldGen.PlaceActuator
PlaceActuator()
static bool WorldGen.PlaceActuator (int i, int j) inline static
     {
         if (!Main.tile[i, j].actuator())
         {
             SoundEngine.PlaySound(0, i * 16, j * 16);
             Main.tile[i, j].actuator(actuator: true);
             return true;
         }
         return false;
     }
References Tile.actuator(), SoundEngine.PlaySound(), and Main.tile.
Referenced by MessageBuffer.GetData(), Player.ItemCheck_UseWiringTools(), Wiring.MassWireOperationStep(), and Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate().