Terraria: WorldGen.PlantSeaOat
PlantSeaOat()
static bool WorldGen.PlantSeaOat (int x, int y) inline static private
     {
         if (Main.tile[x, y].wall > 0 || Main.tile[x, y].active() || Main.tile[x, y].liquid > 0 || !SolidTileAllowBottomSlope(x, y + 1) || !TileID.Sets.Conversion.Sand[Main.tile[x, y + 1].type])
         {
             return false;
         }
         if (!SeaOatWaterCheck(x, y))
         {
             return false;
         }
         Main.tile[x, y].active(active: true);
         Main.tile[x, y].slope(0);
         Main.tile[x, y].halfBrick(halfBrick: false);
         Main.tile[x, y].type = 529;
         Main.tile[x, y].frameX = (short)(genRand.Next(5) * 18);
         int num = 0;
         Main.tile[x, y].frameY = (short)(num * 34);
         if (Main.netMode == 2)
         {
             NetMessage.SendTileSquare(-1, x, y);
         }
         return true;
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.liquid, Main.netMode, TileID.Sets.Conversion.Sand, NetMessage.SendTileSquare(), Tile.slope(), Main.tile, Tile.type, and Tile.wall.