Terraria: WorldGen.meteor
meteor()
static bool WorldGen.meteor (int i, int j, bool ignorePlayers = false) inline static
     {
         if (i < 50 || i > Main.maxTilesX - 50)
         {
             return false;
         }
         if (j < 50 || j > Main.maxTilesY - 50)
         {
             return false;
         }
         int num = 35;
         Rectangle rectangle = new Rectangle((i - num) * 16, (j - num) * 16, num * 2 * 16, num * 2 * 16);
         for (int k = 0; k < 255; k++)
         {
             if (Main.player[k].active && !ignorePlayers)
             {
                 Rectangle value = new Rectangle((int)(Main.player[k].position.X + (float)(Main.player[k].width / 2) - (float)(NPC.sWidth / 2) - (float)NPC.safeRangeX), (int)(Main.player[k].position.Y + (float)(Main.player[k].height / 2) - (float)(NPC.sHeight / 2) - (float)NPC.safeRangeY), NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                 if (rectangle.Intersects(value))
                 {
                     return false;
                 }
             }
         }
         for (int l = 0; l < 200; l++)
         {
             if (Main.npc[l].active)
             {
                 Rectangle value2 = new Rectangle((int)Main.npc[l].position.X, (int)Main.npc[l].position.Y, Main.npc[l].width, Main.npc[l].height);
                 if (rectangle.Intersects(value2))
                 {
                     return false;
                 }
             }
         }
         for (int m = i - num; m < i + num; m++)
         {
             for (int n = j - num; n < j + num; n++)
             {
                 if (Main.tile[m, n].active())
                 {
                     if (TileID.Sets.BasicChest[Main.tile[m, n].type] || Main.tileDungeon[Main.tile[m, n].type])
                     {
                         return false;
                     }
                     switch (Main.tile[m, n].type)
                     {
                     case 226:
                     case 470:
                     case 475:
                     case 488:
                     case 597:
                         return false;
                     }
                 }
             }
         }
         stopDrops = true;
         num = genRand.Next(17, 23);
         for (int num2 = i - num; num2 < i + num; num2++)
         {
             for (int num3 = j - num; num3 < j + num; num3++)
             {
                 if (num3 <= j + Main.rand.Next(-2, 3) - 5)
                 {
                     continue;
                 }
                 double num4 = Math.Abs(i - num2);
                 double num5 = Math.Abs(j - num3);
                 if (Math.Sqrt(num4 * num4 + num5 * num5) < (double)num * 0.9 + (double)Main.rand.Next(-4, 5))
                 {
                     if (!Main.tileSolid[Main.tile[num2, num3].type])
                     {
                         Main.tile[num2, num3].active(active: false);
                     }
                     Main.tile[num2, num3].type = 37;
                 }
             }
         }
         num = genRand.Next(8, 14);
         for (int num6 = i - num; num6 < i + num; num6++)
         {
             for (int num7 = j - num; num7 < j + num; num7++)
             {
                 if (num7 > j + Main.rand.Next(-2, 3) - 4)
                 {
                     double num8 = Math.Abs(i - num6);
                     double num9 = Math.Abs(j - num7);
                     if (Math.Sqrt(num8 * num8 + num9 * num9) < (double)num * 0.8 + (double)Main.rand.Next(-3, 4))
                     {
                         Main.tile[num6, num7].active(active: false);
                     }
                 }
             }
         }
         num = genRand.Next(25, 35);
         for (int num10 = i - num; num10 < i + num; num10++)
         {
             for (int num11 = j - num; num11 < j + num; num11++)
             {
                 double num12 = Math.Abs(i - num10);
                 double num13 = Math.Abs(j - num11);
                 if (Math.Sqrt(num12 * num12 + num13 * num13) < (double)num * 0.7)
                 {
                     if (TileID.Sets.GetsDestroyedForMeteors[Main.tile[num10, num11].type])
                     {
                         KillTile(num10, num11);
                     }
                     Main.tile[num10, num11].liquid = 0;
                 }
                 if (Main.tile[num10, num11].type == 37)
                 {
                     if (!SolidTile(num10 - 1, num11) && !SolidTile(num10 + 1, num11) && !SolidTile(num10, num11 - 1) && !SolidTile(num10, num11 + 1))
                     {
                         Main.tile[num10, num11].active(active: false);
                     }
                     else if ((Main.tile[num10, num11].halfBrick() || Main.tile[num10 - 1, num11].topSlope()) && !SolidTile(num10, num11 + 1))
                     {
                         Main.tile[num10, num11].active(active: false);
                     }
                 }
                 SquareTileFrame(num10, num11);
                 SquareWallFrame(num10, num11);
             }
         }
         num = genRand.Next(23, 32);
         for (int num14 = i - num; num14 < i + num; num14++)
         {
             for (int num15 = j - num; num15 < j + num; num15++)
             {
                 if (num15 <= j + genRand.Next(-3, 4) - 3 || !Main.tile[num14, num15].active() || Main.rand.Next(10) != 0)
                 {
                     continue;
                 }
                 double num16 = Math.Abs(i - num14);
                 double num17 = Math.Abs(j - num15);
                 if (Math.Sqrt(num16 * num16 + num17 * num17) < (double)num * 0.8)
                 {
                     if (TileID.Sets.GetsDestroyedForMeteors[Main.tile[num14, num15].type])
                     {
                         KillTile(num14, num15);
                     }
                     Main.tile[num14, num15].type = 37;
                     SquareTileFrame(num14, num15);
                 }
             }
         }
         num = genRand.Next(30, 38);
         for (int num18 = i - num; num18 < i + num; num18++)
         {
             for (int num19 = j - num; num19 < j + num; num19++)
             {
                 if (num19 <= j + genRand.Next(-2, 3) || !Main.tile[num18, num19].active() || Main.rand.Next(20) != 0)
                 {
                     continue;
                 }
                 double num20 = Math.Abs(i - num18);
                 double num21 = Math.Abs(j - num19);
                 if (Math.Sqrt(num20 * num20 + num21 * num21) < (double)num * 0.85)
                 {
                     if (TileID.Sets.GetsDestroyedForMeteors[Main.tile[num18, num19].type])
                     {
                         KillTile(num18, num19);
                     }
                     Main.tile[num18, num19].type = 37;
                     SquareTileFrame(num18, num19);
                 }
             }
         }
         stopDrops = false;
         if (Main.netMode == 0)
         {
             Main.NewText(Lang.gen[59].Value, 50, byte.MaxValue, 130);
         }
         else if (Main.netMode == 2)
         {
             ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.gen[59].Key), new Color(50, 255, 130));
         }
         if (Main.netMode != 1)
         {
             NetMessage.SendTileSquare(-1, i, j, 40);
         }
         return true;
     }
References Entity.active, Tile.active(), TileID.Sets.BasicChest, ChatHelper.BroadcastChatMessage(), Color, NetworkText.FromKey(), Lang.gen, genRand, TileID.Sets.GetsDestroyedForMeteors, Tile.halfBrick(), Entity.height, LocalizedText.Key, KillTile(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.netMode, Main.NewText(), UnifiedRandom.Next(), Main.npc, Main.player, Entity.position, Main.rand, NPC.safeRangeX, NPC.safeRangeY, NetMessage.SendTileSquare(), NPC.sHeight, SolidTile(), SquareTileFrame(), SquareWallFrame(), stopDrops, NPC.sWidth, Main.tile, Main.tileDungeon, Main.tileSolid, Tile.topSlope(), Tile.type, LocalizedText.Value, and Entity.width.
Referenced by dropMeteor().