Terraria: WorldGen.SwitchMB
SwitchMB()
static void WorldGen.SwitchMB (int i, int j) inline static
     {
         int num = i;
         int num2 = j;
         int num3;
         for (num3 = Main.tile[i, j].frameY / 18; num3 >= 2; num3 -= 2)
         {
         }
         int num4 = Main.tile[i, j].frameX / 18;
         if (num4 >= 2)
         {
             num4 -= 2;
         }
         num = i - num4;
         num2 = j - num3;
         for (int k = num; k < num + 2; k++)
         {
             for (int l = num2; l < num2 + 2; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 if (Main.tile[k, l].active() && (Main.tile[k, l].type == 139 || Main.tile[k, l].type == 35))
                 {
                     if (Main.tile[k, l].frameX < 36)
                     {
                         Main.tile[k, l].frameX += 36;
                     }
                     else
                     {
                         Main.tile[k, l].frameX -= 36;
                     }
                 }
             }
         }
         if (Wiring.running)
         {
             Wiring.SkipWire(num, num2);
             Wiring.SkipWire(num + 1, num2);
             Wiring.SkipWire(num, num2 + 1);
             Wiring.SkipWire(num + 1, num2 + 1);
         }
         NetMessage.SendTileSquare(-1, num, num2, 2, 2);
     }
References Tile.active(), Tile.frameX, Tile.frameY, Wiring.running, NetMessage.SendTileSquare(), Wiring.SkipWire(), Main.tile, and Tile.type.
Referenced by Wiring.HitWireSingle(), and Player.TileInteractionsUse().