Terraria: WorldGen.GrowCactus
GrowCactus()
static void WorldGen.GrowCactus (int i, int j) inline static
     {
         int num = j;
         int num2 = i;
         if (!Main.tile[i, j].nactive() || Main.tile[i, j].halfBrick() || (!gen && Main.tile[i, j].slope() != 0) || Main.tile[i, j - 1].liquid > 0 || (Main.tile[i, j].type != 53 && Main.tile[i, j].type != 80 && Main.tile[i, j].type != 234 && Main.tile[i, j].type != 112 && Main.tile[i, j].type != 116))
         {
             return;
         }
         int num3 = 0;
         for (int k = i - cactusWaterWidth; k < i + cactusWaterWidth; k++)
         {
             for (int l = j - cactusWaterHeight; l < j + cactusWaterHeight; l++)
             {
                 num3 += Main.tile[k, l].liquid;
             }
         }
         if ((!Main.remixWorld || !((double)j > Main.worldSurface)) && num3 / 255 > cactusWaterLimit)
         {
             return;
         }
         if (Main.tile[i, j].type == 53 || Main.tile[i, j].type == 112 || Main.tile[i, j].type == 116 || Main.tile[i, j].type == 234)
         {
             if (Main.tile[i, j - 1].active() || Main.tile[i - 1, j - 1].active() || Main.tile[i + 1, j - 1].active())
             {
                 return;
             }
             int num4 = 0;
             int num5 = 0;
             for (int m = i - 6; m <= i + 6; m++)
             {
                 for (int n = j - 3; n <= j + 1; n++)
                 {
                     try
                     {
                         if (!Main.tile[m, n].active())
{
                             continue;
                         }
                         if (Main.tile[m, n].type == 80)
{
                             num4++;
                             if (num4 >= 4)
{
                                 return;
                             }
                         }
                         if (Main.tile[m, n].type == 53 || Main.tile[m, n].type == 112 || Main.tile[m, n].type == 116 || Main.tile[m, n].type == 234)
{
                             num5++;
                         }
                     }
                     catch
                     {
                     }
                 }
             }
             if (num5 > 10)
             {
                 if (gen && genRand.Next(2) == 0)
                 {
                     Main.tile[i, j].slope(0);
                 }
                 Main.tile[i, j - 1].active(active: true);
                 Main.tile[i, j - 1].type = 80;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, i, j - 1);
                 }
                 SquareTileFrame(num2, num - 1);
             }
         }
         else
         {
             if (Main.tile[i, j].type != 80)
             {
                 return;
             }
             while (Main.tile[num2, num].active() && Main.tile[num2, num].type == 80)
             {
                 num++;
                 if (!Main.tile[num2, num].active() || Main.tile[num2, num].type != 80)
                 {
                     if (Main.tile[num2 - 1, num].active() && Main.tile[num2 - 1, num].type == 80 && Main.tile[num2 - 1, num - 1].active() && Main.tile[num2 - 1, num - 1].type == 80 && num2 >= i)
                     {
                         num2--;
                     }
                     if (Main.tile[num2 + 1, num].active() && Main.tile[num2 + 1, num].type == 80 && Main.tile[num2 + 1, num - 1].active() && Main.tile[num2 + 1, num - 1].type == 80 && num2 <= i)
                     {
                         num2++;
                     }
                 }
             }
             num--;
             int num6 = num - j;
             int num7 = i - num2;
             num2 = i - num7;
             num = j;
             int num8 = 11 - num6;
             int num9 = 0;
             for (int num10 = num2 - 2; num10 <= num2 + 2; num10++)
             {
                 for (int num11 = num - num8; num11 <= num + num6; num11++)
                 {
                     if (Main.tile[num10, num11].active() && Main.tile[num10, num11].type == 80)
                     {
                         num9++;
                     }
                 }
             }
             if (Main.drunkWorld)
             {
                 if (num9 >= genRand.Next(11, 20))
                 {
                     return;
                 }
             }
             else if (num9 >= genRand.Next(11, 13))
             {
                 return;
             }
             num2 = i;
             num = j;
             if (num7 == 0)
             {
                 if (num6 == 0)
                 {
                     if (!Main.tile[num2, num - 1].active())
                     {
                         Main.tile[num2, num - 1].active(active: true);
                         Main.tile[num2, num - 1].type = 80;
                         SquareTileFrame(num2, num - 1);
                         if (Main.netMode == 2)
{
                             NetMessage.SendTileSquare(-1, num2, num - 1);
                         }
                     }
                     return;
                 }
                 bool flag = false;
                 bool flag2 = false;
                 if (Main.tile[num2, num - 1].active() && Main.tile[num2, num - 1].type == 80)
                 {
                     if (!Main.tile[num2 - 1, num].active() && !Main.tile[num2 - 2, num + 1].active() && !Main.tile[num2 - 1, num - 1].active() && !Main.tile[num2 - 1, num + 1].active() && !Main.tile[num2 - 2, num].active())
                     {
                         flag = true;
                     }
                     if (!Main.tile[num2 + 1, num].active() && !Main.tile[num2 + 2, num + 1].active() && !Main.tile[num2 + 1, num - 1].active() && !Main.tile[num2 + 1, num + 1].active() && !Main.tile[num2 + 2, num].active())
                     {
                         flag2 = true;
                     }
                 }
                 int num12 = genRand.Next(3);
                 if (num12 == 0 && flag)
                 {
                     Main.tile[num2 - 1, num].active(active: true);
                     Main.tile[num2 - 1, num].type = 80;
                     SquareTileFrame(num2 - 1, num);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, num2 - 1, num);
                     }
                 }
                 else if (num12 == 1 && flag2)
                 {
                     Main.tile[num2 + 1, num].active(active: true);
                     Main.tile[num2 + 1, num].type = 80;
                     SquareTileFrame(num2 + 1, num);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, num2 + 1, num);
                     }
                 }
                 else
                 {
                     if (num6 >= genRand.Next(2, 8))
                     {
                         return;
                     }
                     if (Main.tile[num2 - 1, num - 1].active())
                     {
                         _ = Main.tile[num2 - 1, num - 1].type;
                         _ = 80;
                     }
                     if ((!Main.tile[num2 + 1, num - 1].active() || Main.tile[num2 + 1, num - 1].type != 80) && !Main.tile[num2, num - 1].active())
                     {
                         Main.tile[num2, num - 1].active(active: true);
                         Main.tile[num2, num - 1].type = 80;
                         SquareTileFrame(num2, num - 1);
                         if (Main.netMode == 2)
{
                             NetMessage.SendTileSquare(-1, num2, num - 1);
                         }
                     }
                 }
             }
             else if (!Main.tile[num2, num - 1].active() && !Main.tile[num2, num - 2].active() && !Main.tile[num2 + num7, num - 1].active() && Main.tile[num2 - num7, num - 1].active() && Main.tile[num2 - num7, num - 1].type == 80)
             {
                 Main.tile[num2, num - 1].active(active: true);
                 Main.tile[num2, num - 1].type = 80;
                 SquareTileFrame(num2, num - 1);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, num2, num - 1);
                 }
             }
         }
     }
References Tile.active(), Main.drunkWorld, Tile.halfBrick(), Tile.liquid, Tile.nactive(), Main.netMode, Main.remixWorld, NetMessage.SendTileSquare(), Tile.slope(), Main.tile, Tile.type, and Main.worldSurface.