Terraria: WorldGen.RandomizeCaveBackgrounds
RandomizeCaveBackgrounds()
static void WorldGen.RandomizeCaveBackgrounds () inline static
     {
         int maxValue = 8;
         if (Main.maxTilesX == 4200)
         {
             Main.caveBackX[0] = genRand.Next((int)((double)Main.maxTilesX * 0.5 - (double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.5 + (double)Main.maxTilesX * 0.25));
             Main.caveBackX[1] = Main.maxTilesX;
             Main.caveBackX[2] = Main.maxTilesX;
             Main.caveBackStyle[0] = genRand.Next(maxValue);
             Main.caveBackStyle[1] = genRand.Next(maxValue);
             while (Main.caveBackStyle[1] == Main.caveBackStyle[0])
             {
                 Main.caveBackStyle[1] = genRand.Next(maxValue);
             }
         }
         else if (Main.maxTilesX == 6400)
         {
             Main.caveBackX[0] = genRand.Next((int)((double)Main.maxTilesX * 0.334 - (double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.334 + (double)Main.maxTilesX * 0.2));
             Main.caveBackX[1] = genRand.Next((int)((double)Main.maxTilesX * 0.667 - (double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.667 + (double)Main.maxTilesX * 0.2));
             Main.caveBackX[2] = Main.maxTilesX;
             Main.caveBackStyle[0] = genRand.Next(maxValue);
             Main.caveBackStyle[1] = genRand.Next(maxValue);
             Main.caveBackStyle[2] = genRand.Next(maxValue);
             while (Main.caveBackStyle[1] == Main.caveBackStyle[0])
             {
                 Main.caveBackStyle[1] = genRand.Next(maxValue);
             }
             while (Main.caveBackStyle[2] == Main.caveBackStyle[0] || Main.caveBackStyle[2] == Main.caveBackStyle[1])
             {
                 Main.caveBackStyle[2] = genRand.Next(maxValue);
             }
         }
         else
         {
             Main.caveBackX[0] = genRand.Next((int)((double)Main.maxTilesX * 0.25 - (double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.25 + (double)Main.maxTilesX * 0.15));
             Main.caveBackX[1] = genRand.Next((int)((double)Main.maxTilesX * 0.5 - (double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.5 + (double)Main.maxTilesX * 0.15));
             Main.caveBackX[2] = genRand.Next((int)((double)Main.maxTilesX * 0.75 - (double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.75 + (double)Main.maxTilesX * 0.15));
             Main.caveBackStyle[0] = genRand.Next(maxValue);
             Main.caveBackStyle[1] = genRand.Next(maxValue);
             Main.caveBackStyle[2] = genRand.Next(maxValue);
             Main.caveBackStyle[3] = genRand.Next(maxValue);
             while (Main.caveBackStyle[1] == Main.caveBackStyle[0])
             {
                 Main.caveBackStyle[1] = genRand.Next(maxValue);
             }
             while (Main.caveBackStyle[2] == Main.caveBackStyle[0] || Main.caveBackStyle[2] == Main.caveBackStyle[1])
             {
                 Main.caveBackStyle[2] = genRand.Next(maxValue);
             }
             while (Main.caveBackStyle[3] == Main.caveBackStyle[0] || Main.caveBackStyle[3] == Main.caveBackStyle[1] || Main.caveBackStyle[3] == Main.caveBackStyle[2])
             {
                 Main.caveBackStyle[3] = genRand.Next(maxValue);
             }
         }
         Main.iceBackStyle = genRand.Next(4);
         Main.hellBackStyle = genRand.Next(3);
         Main.jungleBackStyle = genRand.Next(2);
     }
References Main.caveBackStyle, Main.caveBackX, genRand, Main.hellBackStyle, Main.iceBackStyle, Main.jungleBackStyle, Main.maxTilesX, and UnifiedRandom.Next().
Referenced by GenerateWorld(), Main.Initialize_AlmostEverything(), and WorldFile.LoadWorld_Version1_Old_BeforeRelease88().