Terraria: WorldGen.PlaceOnTable1x1
PlaceOnTable1x1()
static void WorldGen.PlaceOnTable1x1 (int x, int y, int type, int style = 0) inline static
     {
         bool flag = false;
         if (Main.tile[x, y] == null)
         {
             Main.tile[x, y] = new Tile();
         }
         if (Main.tile[x, y + 1] == null)
         {
             Main.tile[x, y + 1] = new Tile();
         }
         if (!Main.tile[x, y].active() && Main.tile[x, y + 1].nactive() && Main.tileTable[Main.tile[x, y + 1].type])
         {
             flag = true;
         }
         if (type == 78 && !Main.tile[x, y].active() && Main.tile[x, y + 1].nactive() && Main.tileSolid[Main.tile[x, y + 1].type] && !Main.tile[x, y + 1].halfBrick() && Main.tile[x, y + 1].slope() == 0)
         {
             flag = true;
         }
         if (flag)
         {
             Main.tile[x, y].active(active: true);
             Main.tile[x, y].type = (ushort)type;
             if (type == 33)
             {
                 Main.tile[x, y].frameX = 0;
                 Main.tile[x, y].frameY = (short)(style * 22);
             }
             else
             {
                 Main.tile[x, y].frameX = (short)(style * 18);
                 Main.tile[x, y].frameY = 0;
             }
             if (type == 50)
             {
                 Main.tile[x, y].frameX = (short)(18 * genRand.Next(5));
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.nactive(), Tile.slope(), Main.tile, Main.tileSolid, Main.tileTable, and Tile.type.