Terraria: WorldGen.GrowSpike
GrowSpike()
static void WorldGen.GrowSpike (int i, int j, ushort spikeType, ushort landType) inline static
     {
         int num = -1;
         switch (landType)
         {
         case 23:
             num = 661;
             break;
         case 199:
             num = 662;
             break;
         }
         int num2 = i;
         int num3 = j;
         int num4 = 0;
         if (Main.tile[num2 + 1, num3].active() && Main.tile[num2 + 1, num3].type == spikeType)
         {
             num4++;
         }
         if (Main.tile[num2 - 1, num3].active() && Main.tile[num2 - 1, num3].type == spikeType)
         {
             num4++;
         }
         if (Main.tile[num2, num3 + 1].active() && Main.tile[num2, num3 + 1].type == spikeType)
         {
             num4++;
         }
         if (Main.tile[num2, num3 - 1].active() && Main.tile[num2, num3 - 1].type == spikeType)
         {
             num4++;
         }
         if (num4 >= 3 && Main.tile[i, j].type != landType && Main.tile[i, j].type != num)
         {
             return;
         }
         switch (genRand.Next(4))
         {
         case 0:
             num3--;
             break;
         case 1:
             num3++;
             break;
         case 2:
             num2--;
             break;
         case 3:
             num2++;
             break;
         }
         if (Main.tile[num2, num3].active())
         {
             return;
         }
         num4 = 0;
         if (Main.tile[num2 + 1, num3].active() && Main.tile[num2 + 1, num3].type == spikeType)
         {
             num4++;
         }
         if (Main.tile[num2 - 1, num3].active() && Main.tile[num2 - 1, num3].type == spikeType)
         {
             num4++;
         }
         if (Main.tile[num2, num3 + 1].active() && Main.tile[num2, num3 + 1].type == spikeType)
         {
             num4++;
         }
         if (Main.tile[num2, num3 - 1].active() && Main.tile[num2, num3 - 1].type == spikeType)
         {
             num4++;
         }
         if (num4 >= 2)
         {
             return;
         }
         int num5 = 7;
         int num6 = num2 - num5;
         int num7 = num2 + num5;
         int num8 = num3 - num5;
         int num9 = num3 + num5;
         bool flag = false;
         for (int k = num6; k < num7; k++)
         {
             for (int l = num8; l < num9; l++)
             {
                 if (Math.Abs(k - num2) * 2 + Math.Abs(l - num3) < 9 && Main.tile[k, l].active() && (Main.tile[k, l].type == landType || Main.tile[k, l].type == num) && Main.tile[k, l - 1].active() && Main.tile[k, l - 1].type == spikeType && Main.tile[k, l - 1].liquid == 0)
                 {
                     flag = true;
                     break;
                 }
             }
         }
         if (flag)
         {
             Main.tile[num2, num3].type = spikeType;
             Main.tile[num2, num3].active(active: true);
             Main.tile[num2, num3].CopyPaintAndCoating(Main.tile[i, j]);
             SquareTileFrame(num2, num3);
             if (Main.netMode == 2)
             {
                 NetMessage.SendTileSquare(-1, num2, num3, 1);
             }
         }
     }
References Tile.active(), Tile.CopyPaintAndCoating(), Tile.liquid, Main.netMode, NetMessage.SendTileSquare(), Main.tile, and Tile.type.