Terraria: WorldGen.IslandHouse
IslandHouse()
static void WorldGen.IslandHouse (int i, int j, int islandStyle) inline static
     {
         //IL_009b: Unknown result type (might be due to invalid IL or missing references)
         //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
         //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
         //IL_0103: Unknown result type (might be due to invalid IL or missing references)
         //IL_011a: Unknown result type (might be due to invalid IL or missing references)
         //IL_021d: Unknown result type (might be due to invalid IL or missing references)
         //IL_022a: Unknown result type (might be due to invalid IL or missing references)
         //IL_0237: Unknown result type (might be due to invalid IL or missing references)
         //IL_0244: Unknown result type (might be due to invalid IL or missing references)
         //IL_0305: Unknown result type (might be due to invalid IL or missing references)
         bool flag = crimson;
         if (drunkWorldGen)
         {
             flag = (GenVars.crimsonLeft && i < Main.maxTilesX / 2) || ((!GenVars.crimsonLeft && i > Main.maxTilesX / 2) ? true : false);
         }
         byte type = 202;
         byte wall = 82;
         Vector2D val = default(Vector2D);
         ((Vector2D)(ref val))._002Ector((double)i, (double)j);
         int num = 1;
         if (genRand.Next(2) == 0)
         {
             num = -1;
         }
         int num2 = genRand.Next(7, 12);
         int num3 = genRand.Next(5, 7);
         val.X = i + (num2 + 2) * num;
         for (int k = j - 15; k < j + 30; k++)
         {
             if (Main.tile[(int)val.X, k].active())
             {
                 val.Y = k - 1;
                 break;
             }
         }
         val.X = i;
         int num4 = (int)(val.X - (double)num2 - 1.0);
         int num5 = (int)(val.X + (double)num2 + 1.0);
         int num6 = (int)(val.Y - (double)num3 - 1.0);
         int num7 = (int)(val.Y + 2.0);
         if (num4 < 0)
         {
             num4 = 0;
         }
         if (num5 > Main.maxTilesX)
         {
             num5 = Main.maxTilesX;
         }
         if (num6 < 0)
         {
             num6 = 0;
         }
         if (num7 > Main.maxTilesY)
         {
             num7 = Main.maxTilesY;
         }
         for (int l = num4; l <= num5; l++)
         {
             for (int m = num6 - 1; m < num7 + 1; m++)
             {
                 if (m != num6 - 1 || (l != num4 && l != num5))
                 {
                     Main.tile[l, m].active(active: true);
                     Main.tile[l, m].liquid = 0;
                     Main.tile[l, m].type = type;
                     Main.tile[l, m].wall = 0;
                     Main.tile[l, m].halfBrick(halfBrick: false);
                     Main.tile[l, m].slope(0);
                 }
             }
         }
         num4 = (int)(val.X - (double)num2);
         num5 = (int)(val.X + (double)num2);
         num6 = (int)(val.Y - (double)num3);
         num7 = (int)(val.Y + 1.0);
         if (num4 < 0)
         {
             num4 = 0;
         }
         if (num5 > Main.maxTilesX)
         {
             num5 = Main.maxTilesX;
         }
         if (num6 < 0)
         {
             num6 = 0;
         }
         if (num7 > Main.maxTilesY)
         {
             num7 = Main.maxTilesY;
         }
         for (int n = num4; n <= num5; n++)
         {
             for (int num8 = num6; num8 < num7; num8++)
             {
                 if ((num8 != num6 || (n != num4 && n != num5)) && Main.tile[n, num8].wall == 0)
                 {
                     Main.tile[n, num8].active(active: false);
                     Main.tile[n, num8].wall = wall;
                 }
             }
         }
         int num9 = i + (num2 + 1) * num;
         int num10 = (int)val.Y;
         for (int num11 = num9 - 2; num11 <= num9 + 2; num11++)
         {
             Main.tile[num11, num10].active(active: false);
             Main.tile[num11, num10 - 1].active(active: false);
             Main.tile[num11, num10 - 2].active(active: false);
         }
         if (remixWorldGen)
         {
             if (flag)
             {
                 PlaceTile(num9, num10, 10, mute: true, forced: false, -1, 5);
             }
             else
             {
                 PlaceTile(num9, num10, 10, mute: true, forced: false, -1, 38);
             }
         }
         else
         {
             PlaceTile(num9, num10, 10, mute: true, forced: false, -1, 9);
         }
         num9 = i + (num2 + 1) * -num - num;
         for (int num12 = num6; num12 <= num7 + 1; num12++)
         {
             Main.tile[num9, num12].active(active: true);
             Main.tile[num9, num12].liquid = 0;
             Main.tile[num9, num12].type = type;
             Main.tile[num9, num12].wall = 0;
             Main.tile[num9, num12].halfBrick(halfBrick: false);
             Main.tile[num9, num12].slope(0);
         }
         int contain = 0;
         int num13 = GenVars.skyIslandHouseCount;
         if (num13 > 3)
         {
             num13 = genRand.Next(4);
         }
         switch (num13)
         {
         case 0:
             contain = 159;
             break;
         case 1:
             contain = 65;
             break;
         case 2:
             contain = 158;
             break;
         case 3:
             contain = 2219;
             break;
         }
         if (getGoodWorldGen)
         {
             AddBuriedChest(i, num10 - 3, contain, notNearOtherChests: false, 2, trySlope: false, 0);
         }
         else
         {
             AddBuriedChest(i, num10 - 3, contain, notNearOtherChests: false, 13, trySlope: false, 0);
         }
         if (islandStyle > 0)
         {
             for (int num14 = 0; num14 < 100000; num14++)
             {
                 int num15 = i + genRand.Next(-50, 51);
                 int num16 = num10 + genRand.Next(21);
                 if ((num14 >= 50000 || Main.tile[num15, num16].type != 202) && !Main.tile[num15, num16].active())
                 {
                     Place2xX(num15, num16, 207, islandStyle);
                     if (Main.tile[num15, num16].active())
                     {
                         SwitchFountain(num15, num16);
                         break;
                     }
                 }
             }
         }
         GenVars.skyIslandHouseCount++;
         if (!remixWorldGen)
         {
             int num17 = i - num2 / 2 + 1;
             int num18 = i + num2 / 2 - 1;
             int num19 = 1;
             if (num2 > 10)
             {
                 num19 = 2;
             }
             int num20 = (num6 + num7) / 2 - 1;
             for (int num21 = num17 - num19; num21 <= num17 + num19; num21++)
             {
                 for (int num22 = num20 - 1; num22 <= num20 + 1; num22++)
                 {
                     Main.tile[num21, num22].wall = 21;
                 }
             }
             for (int num23 = num18 - num19; num23 <= num18 + num19; num23++)
             {
                 for (int num24 = num20 - 1; num24 <= num20 + 1; num24++)
                 {
                     Main.tile[num23, num24].wall = 21;
                 }
             }
         }
         int num25 = i + (num2 / 2 + 1) * -num;
         if (remixWorldGen)
         {
             if (flag)
             {
                 PlaceTile(num25, num7 - 1, 14, mute: true, forced: false, -1, 5);
                 PlaceTile(num25 - 2, num7 - 1, 15, mute: true, forced: false, 0, 8);
                 PlaceTile(num25 + 2, num7 - 1, 15, mute: true, forced: false, 0, 8);
             }
             else
             {
                 PlaceTile(num25, num7 - 1, 469, mute: true, forced: false, -1, 2);
                 PlaceTile(num25 - 2, num7 - 1, 15, mute: true, forced: false, 0, 38);
                 PlaceTile(num25 + 2, num7 - 1, 15, mute: true, forced: false, 0, 38);
             }
         }
         else
         {
             PlaceTile(num25, num7 - 1, 14, mute: true, forced: false, -1, 7);
             PlaceTile(num25 - 2, num7 - 1, 15, mute: true, forced: false, 0, 10);
             PlaceTile(num25 + 2, num7 - 1, 15, mute: true, forced: false, 0, 10);
         }
         Main.tile[num25 - 2, num7 - 1].frameX += 18;
         Main.tile[num25 - 2, num7 - 2].frameX += 18;
         if (!remixWorldGen)
         {
             int i2 = num4 + 1;
             int j2 = num6;
             PlaceTile(i2, j2, 91, mute: true, forced: false, -1, genRand.Next(7, 10));
             i2 = num5 - 1;
             j2 = num6;
             PlaceTile(i2, j2, 91, mute: true, forced: false, -1, genRand.Next(7, 10));
             if (num > 0)
             {
                 i2 = num4;
                 j2 = num6 + 1;
             }
             else
             {
                 i2 = num5;
                 j2 = num6 + 1;
             }
             PlaceTile(i2, j2, 91, mute: true, forced: false, -1, genRand.Next(7, 10));
         }
         if (islandStyle != 1)
         {
             return;
         }
         int num26 = genRand.Next(3, 6);
         for (int num27 = 0; num27 < 100000; num27++)
         {
             int num28 = i + genRand.Next(-50, 51);
             int num29 = num10 + genRand.Next(-10, 21);
             if (!Main.tile[num28, num29].active())
             {
                 GrowPalmTree(num28, num29 + 1);
                 if (Main.tile[num28, num29].active())
                 {
                     num26--;
                 }
             }
             if (num26 <= 0)
             {
                 break;
             }
         }
     }
References Tile.active(), GenVars.crimsonLeft, Tile.frameX, Tile.halfBrick(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, GenVars.skyIslandHouseCount, Tile.slope(), Main.tile, Tile.type, Tile.wall, Vector2D.X, and Vector2D.Y.