Terraria: WorldGen.SwitchMonolith
SwitchMonolith()
static void WorldGen.SwitchMonolith (int i, int j) inline static
     {
         int num = i;
         int num2 = j;
         int num3;
         for (num3 = Main.tile[i, j].frameX / 18; num3 >= 2; num3 -= 2)
         {
         }
         int num4;
         for (num4 = Main.tile[i, j].frameY / 18; num4 >= 3; num4 -= 3)
         {
         }
         num = i - num3;
         num2 = j - num4;
         for (int k = num; k < num + 2; k++)
         {
             for (int l = num2; l < num2 + 3; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 Tile tile = Main.tile[k, l];
                 if (!tile.active())
                 {
                     continue;
                 }
                 if (tile.type == 410)
                 {
                     if (tile.frameY < 56)
                     {
                         tile.frameY += 56;
                     }
                     else
                     {
                         tile.frameY -= 56;
                     }
                 }
                 else if (tile.type == 480)
                 {
                     if (tile.frameY < 54)
                     {
                         tile.frameY += 54;
                     }
                     else
                     {
                         tile.frameY -= 54;
                     }
                 }
                 else if (tile.type == 509)
                 {
                     if (tile.frameY < 54)
                     {
                         tile.frameY += 54;
                     }
                     else
                     {
                         tile.frameY -= 54;
                     }
                 }
                 else if (tile.type == 657)
                 {
                     if (tile.frameY < 54)
                     {
                         tile.frameY += 54;
                     }
                     else
                     {
                         tile.frameY -= 54;
                     }
                 }
                 else if (tile.type == 658)
                 {
                     short num5 = 54;
                     short num6 = 3;
                     short num7 = (short)(num5 * num6);
                     tile.frameY += num5;
                     if (tile.frameY >= num7)
                     {
                         tile.frameY -= num7;
                     }
                 }
             }
         }
         if (Wiring.running)
         {
             Wiring.SkipWire(num, num2);
             Wiring.SkipWire(num, num2 + 1);
             Wiring.SkipWire(num, num2 + 2);
             Wiring.SkipWire(num + 1, num2);
             Wiring.SkipWire(num + 1, num2 + 1);
             Wiring.SkipWire(num + 1, num2 + 2);
         }
         NetMessage.SendTileSquare(-1, num, num2, 2, 3);
     }
References Tile.active(), Tile.frameX, Tile.frameY, Wiring.running, NetMessage.SendTileSquare(), Wiring.SkipWire(), Main.tile, and Tile.type.
Referenced by Wiring.HitWireSingle(), and Player.TileInteractionsUse().