Terraria: WorldGen.BiomeTileCheck
BiomeTileCheck()
static bool WorldGen.BiomeTileCheck (int x, int y) inline static
     {
         int num = 50;
         for (int i = x - num; i <= x + num; i++)
         {
             for (int j = y - num; j <= y + num; j++)
             {
                 if (!InWorld(i, j))
                 {
                     continue;
                 }
                 if (Main.tile[i, j].active())
                 {
                     int type = Main.tile[i, j].type;
                     if (type == 368 || type == 367 || type == 147 || type == 161 || type == 162 || type == 70 || type == 72 || type == 396 || type == 397)
                     {
                         return true;
                     }
                 }
                 int wall = Main.tile[i, j].wall;
                 if (wall == 187 || wall == 216)
                 {
                     return true;
                 }
             }
         }
         return false;
     }
References Tile.active(), InWorld(), Main.tile, Tile.type, and Tile.wall.
Referenced by GraniteBiome.CanPlace(), and MarbleBiome.Place().