Terraria: WorldGen.AnchorValid
AnchorValid()
static bool WorldGen.AnchorValid (Tile tileCache, AnchorType anchor) inline static
     {
         bool flag = false;
         if (tileCache.nactive())
         {
             if ((anchor & AnchorType.SolidTile) == AnchorType.SolidTile && Main.tileSolid[tileCache.type] && !Main.tileSolidTop[tileCache.type] && !Main.tileNoAttach[tileCache.type] && tileCache.blockType() == 0)
             {
                 flag = true;
             }
             if ((anchor & AnchorType.SolidBottom) == AnchorType.SolidBottom && ((Main.tileSolid[tileCache.type] && (!Main.tileSolidTop[tileCache.type] || (TileID.Sets.Platforms[tileCache.type] && (tileCache.halfBrick() || tileCache.topSlope())))) || tileCache.topSlope() || tileCache.halfBrick()) && !TileID.Sets.NotReallySolid[tileCache.type] && !tileCache.bottomSlope())
             {
                 flag = true;
             }
             if (!flag && ((anchor & AnchorType.SolidWithTop) == AnchorType.SolidWithTop || (anchor & AnchorType.Table) == AnchorType.Table))
             {
                 if (TileID.Sets.Platforms[tileCache.type])
                 {
                     int num = tileCache.frameX / TileObjectData.PlatformFrameWidth();
                     if ((!tileCache.halfBrick() && num >= 0 && num <= 7) || (num >= 12 && num <= 16) || (num >= 25 && num <= 26))
                     {
                         flag = true;
                     }
                 }
                 else if (Main.tileSolid[tileCache.type] && Main.tileSolidTop[tileCache.type])
                 {
                     flag = true;
                 }
             }
             if (!flag && (anchor & AnchorType.Table) == AnchorType.Table && !TileID.Sets.Platforms[tileCache.type] && Main.tileTable[tileCache.type] && tileCache.blockType() == 0)
             {
                 flag = true;
             }
             if (!flag && (anchor & AnchorType.SolidSide) == AnchorType.SolidSide && Main.tileSolid[tileCache.type] && !Main.tileSolidTop[tileCache.type])
             {
                 int num2 = tileCache.blockType();
                 if ((uint)(num2 - 4) <= 1u)
                 {
                     flag = true;
                 }
             }
         }
         else if (!flag && (anchor & AnchorType.EmptyTile) == AnchorType.EmptyTile)
         {
             flag = true;
         }
         return flag;
     }
References Tile.blockType(), Tile.bottomSlope(), Tile.frameX, Tile.halfBrick(), Tile.nactive(), TileID.Sets.NotReallySolid, TileObjectData.PlatformFrameWidth(), TileID.Sets.Platforms, Main.tileNoAttach, Main.tileSolid, Main.tileSolidTop, Main.tileTable, Tile.topSlope(), and Tile.type.