Terraria: WorldGen.EmptyTileCheck
EmptyTileCheck()
static bool WorldGen.EmptyTileCheck (int startX, int endX, int startY, int endY, int ignoreID = -1) inline static
     {
         if (startX < 0)
         {
             return false;
         }
         if (endX >= Main.maxTilesX)
         {
             return false;
         }
         if (startY < 0)
         {
             return false;
         }
         if (endY >= Main.maxTilesY)
         {
             return false;
         }
         bool flag = false;
         if (ignoreID != -1 && TileID.Sets.CommonSapling[ignoreID])
         {
             flag = true;
         }
         for (int i = startX; i < endX + 1; i++)
         {
             for (int j = startY; j < endY + 1; j++)
             {
                 if (!Main.tile[i, j].active())
                 {
                     continue;
                 }
                 switch (ignoreID)
                 {
                 case -1:
                     return false;
                 case 11:
                 {
                     ushort type = Main.tile[i, j].type;
                     if (type == 11)
                     {
                         continue;
                     }
                     return false;
                 }
                 case 71:
                 {
                     ushort type = Main.tile[i, j].type;
                     if (type == 71)
                     {
                         continue;
                     }
                     return false;
                 }
                 }
                 if (flag)
                 {
                     if (TileID.Sets.CommonSapling[Main.tile[i, j].type])
                     {
                         break;
                     }
                     switch (Main.tile[i, j].type)
                     {
                     case 3:
                     case 24:
                     case 32:
                     case 61:
                     case 62:
                     case 69:
                     case 71:
                     case 73:
                     case 74:
                     case 82:
                     case 83:
                     case 84:
                     case 110:
                     case 113:
                     case 184:
                     case 201:
                     case 233:
                     case 352:
                     case 485:
                     case 529:
                     case 530:
                     case 637:
                     case 655:
                         continue;
                     }
                     return false;
                 }
             }
         }
         return true;
     }
References Tile.active(), TileID.Sets.CommonSapling, Main.maxTilesX, Main.maxTilesY, Main.tile, and Tile.type.
Referenced by SmartCursorHelper.Step_Acorns(), and SmartCursorHelper.Step_GemCorns().