Terraria: WorldGen.RoomNeeds
RoomNeeds()
static bool WorldGen.RoomNeeds (int npcType) inline static
     {
         roomChair = false;
         roomDoor = false;
         roomTable = false;
         roomTorch = false;
         for (int i = 0; i < TileID.Sets.RoomNeeds.CountsAsChair.Length; i++)
         {
             if (houseTile[TileID.Sets.RoomNeeds.CountsAsChair[i]])
             {
                 roomChair = true;
                 break;
             }
         }
         for (int j = 0; j < TileID.Sets.RoomNeeds.CountsAsTable.Length; j++)
         {
             if (houseTile[TileID.Sets.RoomNeeds.CountsAsTable[j]])
             {
                 roomTable = true;
                 break;
             }
         }
         for (int k = 0; k < TileID.Sets.RoomNeeds.CountsAsTorch.Length; k++)
         {
             if (houseTile[TileID.Sets.RoomNeeds.CountsAsTorch[k]])
             {
                 roomTorch = true;
                 break;
             }
         }
         for (int l = 0; l < TileID.Sets.RoomNeeds.CountsAsDoor.Length; l++)
         {
             if (houseTile[TileID.Sets.RoomNeeds.CountsAsDoor[l]])
             {
                 roomDoor = true;
                 break;
             }
         }
         if (roomChair && roomTable && roomDoor && roomTorch)
         {
             canSpawn = true;
         }
         else
         {
             canSpawn = false;
         }
         return canSpawn;
     }
References canSpawn, TileID.Sets.RoomNeeds.CountsAsChair, TileID.Sets.RoomNeeds.CountsAsDoor, TileID.Sets.RoomNeeds.CountsAsTable, TileID.Sets.RoomNeeds.CountsAsTorch, houseTile, roomChair, roomDoor, roomTable, and roomTorch.
Referenced by MoveTownNPC(), QuickFindHome(), and SpawnTownNPC().