Terraria: WorldGen.NotTheBees
NotTheBees()
static void WorldGen.NotTheBees () inline static private
     {
         int num = Main.maxTilesX / 7;
         if (!notTheBees)
         {
             return;
         }
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             for (int j = 0; j < Main.maxTilesY - 180; j++)
             {
                 if (remixWorldGen && (i < num + genRand.Next(3) || i >= Main.maxTilesX - num - genRand.Next(3) || ((double)j > (Main.worldSurface * 2.0 + Main.rockLayer) / 3.0 + (double)genRand.Next(3) && j < Main.maxTilesY - 350 - genRand.Next(3))))
                 {
                     continue;
                 }
                 if (Main.tile[i, j].type == 52)
                 {
                     Main.tile[i, j].type = 62;
                 }
                 if ((SolidOrSlopedTile(i, j) || TileID.Sets.CrackedBricks[Main.tile[i, j].type]) && !TileID.Sets.Ore[Main.tile[i, j].type] && Main.tile[i, j].type != 123 && Main.tile[i, j].type != 40)
                 {
                     if (Main.tile[i, j].type == 191 || Main.tile[i, j].type == 383)
                     {
                         if (!remixWorldGen)
{
                             Main.tile[i, j].type = 383;
                         }
                     }
                     else if (Main.tile[i, j].type == 192 || Main.tile[i, j].type == 384)
                     {
                         if (!remixWorldGen)
{
                             Main.tile[i, j].type = 384;
                         }
                     }
                     else if (Main.tile[i, j].type != 151 && Main.tile[i, j].type != 662 && Main.tile[i, j].type != 661 && Main.tile[i, j].type != 189 && Main.tile[i, j].type != 196 && Main.tile[i, j].type != 120 && Main.tile[i, j].type != 158 && Main.tile[i, j].type != 175 && Main.tile[i, j].type != 45 && Main.tile[i, j].type != 119)
                     {
                         if (Main.tile[i, j].type >= 63 && Main.tile[i, j].type <= 68)
{
                             Main.tile[i, j].type = 230;
                         }
                         else if (Main.tile[i, j].type != 57 && Main.tile[i, j].type != 76 && Main.tile[i, j].type != 75 && Main.tile[i, j].type != 229 && Main.tile[i, j].type != 230 && Main.tile[i, j].type != 407 && Main.tile[i, j].type != 404)
{
                             if (Main.tile[i, j].type == 224)
{
                                 Main.tile[i, j].type = 229;
                             }
                             else if (Main.tile[i, j].type == 53)
{
                                 if (i < beachDistance + genRand.Next(3) || i > Main.maxTilesX - beachDistance - genRand.Next(3))
{
                                     Main.tile[i, j].type = 229;
                                 }
                             }
                             else if ((i <= beachDistance - genRand.Next(3) || i >= Main.maxTilesX - beachDistance + genRand.Next(3) || (Main.tile[i, j].type != 397 && Main.tile[i, j].type != 396)) && Main.tile[i, j].type != 10 && Main.tile[i, j].type != 203 && Main.tile[i, j].type != 25 && Main.tile[i, j].type != 137 && Main.tile[i, j].type != 138 && Main.tile[i, j].type != 141)
{
                                 if (Main.tileDungeon[Main.tile[i, j].type] || TileID.Sets.CrackedBricks[Main.tile[i, j].type])
{
                                     Main.tile[i, j].color(14);
                                 }
                                 else if (Main.tile[i, j].type == 226)
{
                                     Main.tile[i, j].color(15);
                                 }
                                 else if (Main.tile[i, j].type != 202 && Main.tile[i, j].type != 70 && Main.tile[i, j].type != 48 && Main.tile[i, j].type != 232)
{
                                     if (TileID.Sets.Conversion.Grass[Main.tile[i, j].type] || Main.tile[i, j].type == 60 || Main.tile[i, j].type == 70)
{
                                         if (j > GenVars.lavaLine + genRand.Next(-2, 3) + 2)
{
                                             Main.tile[i, j].type = 70;
                                         }
                                         else
{
                                             Main.tile[i, j].type = 60;
                                         }
                                     }
                                     else if (Main.tile[i, j].type == 0 || Main.tile[i, j].type == 59)
{
                                         Main.tile[i, j].type = 59;
                                     }
                                     else if (Main.tile[i, j].type != 633)
{
                                         if (j > GenVars.lavaLine + genRand.Next(-2, 3) + 2)
{
                                             Main.tile[i, j].type = 230;
                                         }
                                         else if (!remixWorldGen || (double)j > Main.worldSurface + (double)genRand.Next(-1, 2))
{
                                             Main.tile[i, j].type = 225;
                                         }
                                     }
                                 }
                             }
                         }
                     }
                 }
                 if (Main.tile[i, j].wall != 15 && Main.tile[i, j].wall != 64 && Main.tile[i, j].wall != 204 && Main.tile[i, j].wall != 205 && Main.tile[i, j].wall != 206 && Main.tile[i, j].wall != 207 && Main.tile[i, j].wall != 23 && Main.tile[i, j].wall != 24 && Main.tile[i, j].wall != 42 && Main.tile[i, j].wall != 10 && Main.tile[i, j].wall != 21 && Main.tile[i, j].wall != 82 && Main.tile[i, j].wall != 187 && Main.tile[i, j].wall != 216 && Main.tile[i, j].wall != 34 && Main.tile[i, j].wall != 244)
                 {
                     if (Main.tile[i, j].wall == 87)
                     {
                         Main.tile[i, j].wallColor(15);
                     }
                     else if (Main.wallDungeon[Main.tile[i, j].wall])
                     {
                         Main.tile[i, j].wallColor(14);
                     }
                     else if (Main.tile[i, j].wall == 2)
                     {
                         Main.tile[i, j].wall = 2;
                     }
                     else if (Main.tile[i, j].wall == 196)
                     {
                         Main.tile[i, j].wall = 196;
                     }
                     else if (Main.tile[i, j].wall == 197)
                     {
                         Main.tile[i, j].wall = 197;
                     }
                     else if (Main.tile[i, j].wall == 198)
                     {
                         Main.tile[i, j].wall = 198;
                     }
                     else if (Main.tile[i, j].wall == 199)
                     {
                         Main.tile[i, j].wall = 199;
                     }
                     else if (Main.tile[i, j].wall == 63)
                     {
                         Main.tile[i, j].wall = 64;
                     }
                     else if (Main.tile[i, j].wall != 3 && Main.tile[i, j].wall != 83 && Main.tile[i, j].wall != 73 && Main.tile[i, j].wall != 62 && Main.tile[i, j].wall != 13 && Main.tile[i, j].wall != 14 && Main.tile[i, j].wall > 0 && (!remixWorldGen || (double)j > Main.worldSurface + (double)genRand.Next(-1, 2)))
                     {
                         Main.tile[i, j].wall = 86;
                     }
                 }
                 if (Main.tile[i, j].liquid > 0 && j <= GenVars.lavaLine + 2)
                 {
                     if ((double)j > Main.rockLayer && (i < beachDistance + 200 || i > Main.maxTilesX - beachDistance - 200))
                     {
                         Main.tile[i, j].honey(honey: false);
                     }
                     else if (Main.wallDungeon[Main.tile[i, j].wall])
                     {
                         Main.tile[i, j].honey(honey: false);
                     }
                     else
                     {
                         Main.tile[i, j].honey(honey: true);
                     }
                 }
             }
         }
     }
References Tile.color(), TileID.Sets.CrackedBricks, TileID.Sets.Conversion.Grass, Tile.honey(), GenVars.lavaLine, Tile.liquid, Main.maxTilesX, Main.maxTilesY, TileID.Sets.Ore, Main.rockLayer, Main.tile, Main.tileDungeon, Tile.type, Tile.wall, Tile.wallColor(), Main.wallDungeon, and Main.worldSurface.
Referenced by GenerateWorld().