Terraria: WorldGen.oceanDepths
oceanDepths()
static bool WorldGen.oceanDepths (int x, int y) inline static
     {
         if ((double)y > oceanLevel)
         {
             return false;
         }
         if (x < beachDistance || x > Main.maxTilesX - beachDistance)
         {
             return true;
         }
         return false;
     }
References beachDistance, Main.maxTilesX, and oceanLevel.
Referenced by Main.DrawBackground(), Main.GetPreferredBGStyleForPlayer(), DeadMansChestBiome.IsAGoodSpot(), TrackGenerator.IsLocationInvalid(), TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition(), SceneMetrics.ScanAndExportToMain(), Liquid.SettleWaterAt(), NPC.SpawnNPC(), Main.UpdateAudio_DecideOnNewMusic(), Main.UpdateAudio_DecideOnTOWMusic(), Player.UpdateBiomes(), and Player.UpdateTorchLuck_ConsumeCountersAndCalculate().