Terraria: WorldGen.PlaceUnderwaterPlant
PlaceUnderwaterPlant()
static void WorldGen.PlaceUnderwaterPlant (ushort type, int x, int y) inline static
     {
         if (CanUnderwaterPlantGrowHere(type, x, y, ignoreSelf: false))
         {
             Tile tileSafely = Framing.GetTileSafely(x, y + 1);
             tileSafely.slope(0);
             tileSafely.halfBrick(halfBrick: false);
             Tile tileSafely2 = Framing.GetTileSafely(x, y);
             tileSafely2.active(active: true);
             tileSafely2.type = type;
             tileSafely2.frameX = 0;
             tileSafely2.frameY = 0;
             tileSafely2.slope(0);
             tileSafely2.halfBrick(halfBrick: false);
             SquareTileFrame(x, y);
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Tile.halfBrick(), Tile.slope(), and Tile.type.