Terraria: WorldGen.CheckBanner
CheckBanner()
static void WorldGen.CheckBanner (int x, int j, byte type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         int num = Main.tile[x, j].frameY / 18;
         int num2 = 0;
         while (num >= 3)
         {
             num -= 3;
             num2++;
         }
         num = j - num;
         int frameX = Main.tile[x, j].frameX;
         bool flag = false;
         for (int i = 0; i < 3; i++)
         {
             if (Main.tile[x, num + i] == null)
             {
                 Main.tile[x, num + i] = new Tile();
             }
             if (!Main.tile[x, num + i].active())
             {
                 flag = true;
             }
             else if (Main.tile[x, num + i].type != type)
             {
                 flag = true;
             }
             else if (Main.tile[x, num + i].frameY != i * 18 + num2 * 18 * 3)
             {
                 flag = true;
             }
             else if (Main.tile[x, num + i].frameX != frameX)
             {
                 flag = true;
             }
         }
         if (Main.tile[x, num - 1] == null)
         {
             Main.tile[x, num - 1] = new Tile();
         }
         Tile tile = Main.tile[x, num - 1];
         if (!tile.nactive())
         {
             flag = true;
         }
         bool num3 = tile.topSlope() || tile.halfBrick() || Main.tileSolid[tile.type];
         bool flag2 = !Main.tileSolidTop[tile.type] || (TileID.Sets.Platforms[tile.type] && (tile.halfBrick() || tile.topSlope()));
         bool flag3 = num3 && flag2 && !TileID.Sets.NotReallySolid[tile.type] && !tile.bottomSlope();
         if (TileID.Sets.Platforms[tile.type] || tile.type == 380)
         {
             flag3 = true;
         }
         if (!flag3)
         {
             flag = true;
         }
         if (!flag)
         {
             return;
         }
         destroyObject = true;
         for (int k = 0; k < 3; k++)
         {
             if (Main.tile[x, num + k].type == type)
             {
                 KillTile(x, num + k);
             }
         }
         if (type == 91)
         {
             int num4 = frameX / 18;
             num4 += num2 * 111;
             if (num4 == 310)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 5352);
             }
             else if (num4 >= 297)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 4668 + num4);
             }
             else if (num4 >= 295)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 4392 + num4);
             }
             else if (num4 >= 294)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 4602);
             }
             else if (num4 >= 288)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 4253 + num4);
             }
             else if (num4 >= 278)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 3559 + num4);
             }
             else if (num4 >= 273)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 3516 + num4);
             }
             else if (num4 >= 272)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 3780);
             }
             else if (num4 >= 270)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 3323 + num4);
             }
             else if (num4 >= 207)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 3183 + num4);
             }
             else if (num4 >= 109)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 2788 + num4);
             }
             else if (num4 >= 22)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 1593 + num4);
             }
             else if (num4 >= 10 && num4 <= 15)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 1441 + num4);
             }
             else if (num4 >= 16 && num4 <= 21)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 1448 + num4);
             }
             else if (num4 >= 7 && num4 <= 9)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 838 + num4);
             }
             else if (num4 >= 4 && num4 <= 6)
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 785 + num4);
             }
             else
             {
                 Item.NewItem(GetItemSource_FromTileBreak(x, num + 1), x * 16, (num + 1) * 16, 32, 32, 337 + num4);
             }
         }
         destroyObject = false;
     }
References Tile.active(), Tile.bottomSlope(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.nactive(), Item.NewItem(), TileID.Sets.NotReallySolid, TileID.Sets.Platforms, Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.topSlope(), and Tile.type.