Terraria: WorldGen.countTiles
countTiles()
static int WorldGen.countTiles (int x, int y, bool jungle = false, bool lavaOk = false) inline static
     {
         numTileCount = 0;
         shroomCount = 0;
         lavaCount = 0;
         iceCount = 0;
         sandCount = 0;
         rockCount = 0;
         CountedTiles.Clear();
         nextCount(x, y, jungle, lavaOk);
         return numTileCount;
     }
References CountedTiles, iceCount, lavaCount, nextCount(), numTileCount, rockCount, sandCount, and shroomCount.
Referenced by gemCave(), and DeadMansChestBiome.IsAGoodSpot().