Terraria: WorldGen.GrowAlch
GrowAlch()
static void WorldGen.GrowAlch (int x, int y) inline static
     {
         if (!Main.tile[x, y].active())
         {
             return;
         }
         if (Main.tile[x, y].liquid > 0)
         {
             int num = Main.tile[x, y].frameX / 18;
             if ((!Main.tile[x, y].lava() || num != 5) && (Main.tile[x, y].liquidType() != 0 || (num != 1 && num != 4)))
             {
                 KillTile(x, y);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
                 SquareTileFrame(x, y);
             }
         }
         if (Main.tile[x, y].type == 82)
         {
             if (genRand.Next(50) == 0)
             {
                 bool flag = false;
                 if (Main.tile[x, y].frameX == 108)
                 {
                     if (genRand.Next(2) == 0)
                     {
                         flag = true;
                     }
                 }
                 else
                 {
                     flag = true;
                 }
                 if (flag)
                 {
                     Main.tile[x, y].type = 83;
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, x, y);
                     }
                     SquareTileFrame(x, y);
                 }
             }
             else if (Main.dayTime && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 0 && genRand.Next(50) == 0)
             {
                 Main.tile[x, y].type = 83;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
                 SquareTileFrame(x, y);
             }
             else if (!Main.dayTime && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 18 && genRand.Next(50) == 0)
             {
                 Main.tile[x, y].type = 83;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
                 SquareTileFrame(x, y);
             }
             else if (Main.raining && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 72 && genRand.Next(50) == 0)
             {
                 Main.tile[x, y].type = 83;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
                 SquareTileFrame(x, y);
             }
             else if ((double)y > Main.worldSurface && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 36 && genRand.Next(50) == 0)
             {
                 Main.tile[x, y].type = 83;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
                 SquareTileFrame(x, y);
             }
             else if (y > Main.maxTilesY - 200 && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 90 && genRand.Next(50) == 0)
             {
                 Main.tile[x, y].type = 83;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
                 SquareTileFrame(x, y);
             }
         }
         else if (Main.tile[x, y].frameX == 36 && genRand.Next(3) != 0)
         {
             if (Main.tile[x, y].type == 83)
             {
                 if (genRand.Next(2) == 0)
                 {
                     Main.tile[x, y].type = 84;
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, x, y);
                     }
                 }
             }
             else if (Main.tile[x, y].type == 84 || genRand.Next(5) == 0)
             {
                 Main.tile[x, y].type = 83;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
             }
         }
         else if (Main.tile[x, y].frameX == 108 && Main.tile[x, y].type == 83 && genRand.Next(30) == 0)
         {
             Main.tile[x, y].type = 84;
             if (Main.netMode == 2)
             {
                 NetMessage.SendTileSquare(-1, x, y);
             }
             SquareTileFrame(x, y);
         }
     }
References Tile.active(), Main.dayTime, Tile.frameX, Tile.lava(), Tile.liquid, Tile.liquidType(), Main.maxTilesY, Main.netMode, Main.raining, NetMessage.SendTileSquare(), Main.tile, Tile.type, and Main.worldSurface.