Terraria: WorldGen.UpdateWorld_GrassGrowth
UpdateWorld_GrassGrowth()
static void WorldGen.UpdateWorld_GrassGrowth (int i, int j, int minI, int maxI, int minJ, int maxJ, bool underground) inline static private
     {
         if (!InWorld(i, j, 10))
         {
             return;
         }
         if (underground)
         {
             int type = Main.tile[i, j].type;
             int num = -1;
             int num2 = -1;
             int num3 = -1;
             int maxValue = 1;
             int num4 = type;
             int num5 = -1;
             switch (type)
             {
             case 23:
                 num = 0;
                 num2 = 59;
                 num4 = 23;
                 num5 = 661;
                 num3 = 24;
                 maxValue = 2;
                 if (!AllowedToSpreadInfections)
                 {
                     return;
                 }
                 break;
             case 199:
                 num = 0;
                 num2 = 59;
                 num4 = 199;
                 num5 = 662;
                 num3 = 201;
                 maxValue = 2;
                 if (!AllowedToSpreadInfections)
                 {
                     return;
                 }
                 break;
             case 661:
                 num = 59;
                 num2 = 0;
                 num4 = 661;
                 num5 = 23;
                 num3 = 24;
                 maxValue = 2;
                 if (!AllowedToSpreadInfections)
                 {
                     return;
                 }
                 break;
             case 662:
                 num = 59;
                 num2 = 0;
                 num4 = 662;
                 num5 = 199;
                 num3 = 201;
                 maxValue = 2;
                 if (!AllowedToSpreadInfections)
                 {
                     return;
                 }
                 break;
             case 60:
                 num = 59;
                 num3 = 61;
                 maxValue = 10;
                 break;
             case 70:
                 num = 59;
                 num3 = 71;
                 maxValue = 10;
                 break;
             case 633:
                 num = 57;
                 num3 = 637;
                 maxValue = 2;
                 break;
             }
             bool flag = false;
             if (num3 != -1 && !Main.tile[i, minJ].active() && genRand.Next(maxValue) == 0)
             {
                 flag = true;
                 if (PlaceTile(i, minJ, num3, mute: true))
                 {
                     Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                 }
                 if (Main.netMode == 2 && Main.tile[i, minJ].active())
                 {
                     NetMessage.SendTileSquare(-1, i, minJ);
                 }
             }
             if (num != -1)
             {
                 bool flag2 = false;
                 TileColorCache color = Main.tile[i, j].BlockColorAndCoating();
                 for (int k = minI; k < maxI; k++)
                 {
                     for (int l = minJ; l < maxJ; l++)
                     {
                         if (!InWorld(k, l, 10) || (i == k && j == l) || !Main.tile[k, l].active())
{
                             continue;
                         }
                         if (Main.tile[k, l].type == num)
{
                             SpreadGrass(k, l, num, num4, repeat: false, color);
                             if (Main.tile[k, l].type == num4)
{
                                 SquareTileFrame(k, l);
                                 flag2 = true;
                             }
                         }
                         else if (num2 > -1 && num5 > -1 && Main.tile[k, l].type == num2)
{
                             SpreadGrass(k, l, num2, num5, repeat: false, color);
                             if (Main.tile[k, l].type == num5)
{
                                 SquareTileFrame(k, l);
                                 flag2 = true;
                             }
                         }
                     }
                 }
                 if (Main.netMode == 2 && flag2)
                 {
                     NetMessage.SendTileSquare(-1, i, j, 3);
                 }
             }
             switch (type)
             {
             case 60:
             {
                 if (flag || genRand.Next(25) != 0 || Main.tile[i, minJ].liquid != 0)
                 {
                     break;
                 }
                 if (Main.hardMode && NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3 && genRand.Next(60) == 0)
                 {
                     bool flag3 = true;
                     int num6 = 150;
                     for (int m = i - num6; m < i + num6; m += 2)
                     {
                         for (int n = j - num6; n < j + num6; n += 2)
{
                             if (m > 1 && m < Main.maxTilesX - 2 && n > 1 && n < Main.maxTilesY - 2 && Main.tile[m, n].active() && Main.tile[m, n].type == 238)
{
                                 flag3 = false;
                                 break;
                             }
                         }
                     }
                     if (flag3)
                     {
                         PlaceJunglePlant(i, minJ, 238, 0, 0);
                         SquareTileFrame(i, minJ);
                         SquareTileFrame(i + 2, minJ);
                         SquareTileFrame(i - 1, minJ);
                         if (Main.tile[i, minJ].type == 238 && Main.netMode == 2)
{
                             NetMessage.SendTileSquare(-1, i, minJ, 5);
                         }
                     }
                 }
                 int maxValue2 = (Main.expertMode ? 30 : 40);
                 if (Main.hardMode && NPC.downedMechBossAny && genRand.Next(maxValue2) == 0)
                 {
                     bool flag4 = true;
                     int num7 = 60;
                     if (Main.expertMode)
                     {
                         num7 -= 10;
                     }
                     for (int num8 = i - num7; num8 < i + num7; num8 += 2)
                     {
                         for (int num9 = j - num7; num9 < j + num7; num9 += 2)
{
                             if (num8 > 1 && num8 < Main.maxTilesX - 2 && num9 > 1 && num9 < Main.maxTilesY - 2 && Main.tile[num8, num9].active() && Main.tile[num8, num9].type == 236)
{
                                 flag4 = false;
                                 break;
                             }
                         }
                     }
                     if (flag4)
                     {
                         PlaceJunglePlant(i, minJ, 236, genRand.Next(3), 0);
                         SquareTileFrame(i, minJ);
                         SquareTileFrame(i + 1, minJ + 1);
                         if (Main.tile[i, minJ].type == 236 && Main.netMode == 2)
{
                             NetMessage.SendTileSquare(-1, i, minJ, 4);
                         }
                     }
                     break;
                 }
                 PlaceJunglePlant(i, minJ, 233, genRand.Next(8), 0);
                 if (Main.tile[i, minJ].type != 233)
                 {
                     break;
                 }
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, i, minJ, 4);
                     break;
                 }
                 PlaceJunglePlant(i, minJ, 233, genRand.Next(12), 1);
                 if (Main.tile[i, minJ].type == 233 && Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, i, minJ, 3);
                 }
                 break;
             }
             case 70:
                 if (Main.tile[i, j - 1].liquid > 0)
                 {
                     PlaceCatTail(i, j - 1);
                 }
                 if (genRand.Next(250) == 0 && GrowTree(i, j) && PlayerLOS(i, j))
                 {
                     TreeGrowFXCheck(i, j - 1);
                 }
                 break;
             }
             return;
         }
         int num10 = Main.tile[i, j].type;
         switch (num10)
         {
         case 2:
         case 23:
         case 32:
         case 109:
         case 199:
         case 352:
         case 477:
         case 492:
         case 661:
         case 662:
         {
             if (Main.halloween && genRand.Next(75) == 0 && (num10 == 2 || num10 == 109))
             {
                 int num13 = 100;
                 int num14 = 0;
                 for (int num15 = i - num13; num15 < i + num13; num15 += 2)
                 {
                     for (int num16 = j - num13; num16 < j + num13; num16 += 2)
                     {
                         if (num15 > 1 && num15 < Main.maxTilesX - 2 && num16 > 1 && num16 < Main.maxTilesY - 2 && Main.tile[num15, num16].active() && Main.tile[num15, num16].type == 254)
{
                             num14++;
                         }
                     }
                 }
                 if (num14 < 6)
                 {
                     PlacePumpkin(i, minJ);
                     if (Main.netMode == 2 && Main.tile[i, minJ].type == 254)
                     {
                         NetMessage.SendTileSquare(-1, i - 1, minJ - 1, 2, 2);
                     }
                 }
             }
             if (!Main.tile[i, minJ].active() && Main.tile[i, minJ].liquid == 0)
             {
                 int num17 = -1;
                 if (num10 == 2 && genRand.Next(12) == 0)
                 {
                     num17 = 3;
                 }
                 else if (num10 == 23 && genRand.Next(10) == 0)
                 {
                     num17 = 24;
                 }
                 else if (num10 == 199 && genRand.Next(10) == 0)
                 {
                     num17 = 201;
                 }
                 else if (num10 == 661 && genRand.Next(10) == 0)
                 {
                     num17 = 24;
                 }
                 else if (num10 == 662 && genRand.Next(10) == 0)
                 {
                     num17 = 201;
                 }
                 else if (num10 == 109 && genRand.Next(10) == 0)
                 {
                     num17 = 110;
                 }
                 else if (num10 == 633 && genRand.Next(10) == 0)
                 {
                     num17 = 637;
                 }
                 if (num17 != -1 && PlaceTile(i, minJ, num17, mute: true))
                 {
                     Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, i, minJ);
                     }
                 }
             }
             bool flag6 = false;
             switch (num10)
             {
             case 32:
                 num10 = 23;
                 if (!AllowedToSpreadInfections)
                 {
                     return;
                 }
                 break;
             case 352:
                 num10 = 199;
                 if (!AllowedToSpreadInfections)
                 {
                     return;
                 }
                 break;
             case 477:
                 num10 = 2;
                 break;
             case 492:
                 num10 = 109;
                 break;
             }
             int grass = num10;
             int num18 = -1;
             if (num10 == 23 || num10 == 661)
             {
                 grass = 23;
                 num18 = 661;
             }
             if (num10 == 199 || num10 == 662)
             {
                 grass = 199;
                 num18 = 662;
             }
             bool flag7 = AllowedToSpreadInfections && (num10 == 23 || num10 == 199 || num10 == 109 || num10 == 492 || num10 == 661 || num10 == 662) && InWorld(i, j, 10);
             for (int num19 = minI; num19 < maxI; num19++)
             {
                 for (int num20 = minJ; num20 < maxJ; num20++)
                 {
                     if (!InWorld(num19, num20, 10) || (i == num19 && j == num20) || !Main.tile[num19, num20].active())
                     {
                         continue;
                     }
                     int type2 = Main.tile[num19, num20].type;
                     if (!flag7 && type2 != 0 && (num18 == -1 || type2 != 59))
                     {
                         continue;
                     }
                     TileColorCache color3 = Main.tile[i, j].BlockColorAndCoating();
                     if (type2 == 0 || (num18 > -1 && type2 == 59) || ((num10 == 23 || num10 == 661 || num10 == 199 || num10 == 662) && (type2 == 2 || type2 == 109 || type2 == 477 || type2 == 492)))
                     {
                         SpreadGrass(num19, num20, 0, grass, repeat: false, color3);
                         if (num18 > -1)
{
                             SpreadGrass(num19, num20, 59, num18, repeat: false, color3);
                         }
                         if (AllowedToSpreadInfections && (num10 == 23 || num10 == 199 || num10 == 661 || num10 == 662))
{
                             SpreadGrass(num19, num20, 2, grass, repeat: false, color3);
                             SpreadGrass(num19, num20, 109, grass, repeat: false, color3);
                             SpreadGrass(num19, num20, 477, grass, repeat: false, color3);
                             SpreadGrass(num19, num20, 492, grass, repeat: false, color3);
                             if (num18 > -1)
{
                                 SpreadGrass(num19, num20, 60, num18, repeat: false, color3);
                             }
                         }
                         if (Main.tile[num19, num20].type == num10 || (num18 > -1 && Main.tile[num19, num20].type == num18))
{
                             SquareTileFrame(num19, num20);
                             flag6 = true;
                         }
                     }
                     if (type2 == 0 || ((num10 == 109 || num10 == 492) && (type2 == 2 || type2 == 477 || type2 == 23 || type2 == 199)))
                     {
                         SpreadGrass(num19, num20, 0, grass, repeat: false, color3);
                         if (num10 == 109)
{
                             SpreadGrass(num19, num20, 2, grass, repeat: false, color3);
                         }
                         switch (num10)
{
                         case 492:
                             SpreadGrass(num19, num20, 477, grass, repeat: false, color3);
                             break;
                         case 109:
                             SpreadGrass(num19, num20, 477, 492, repeat: false, color3);
                             break;
                         }
                         if ((num10 == 492 || num10 == 109) && AllowedToSpreadInfections)
{
                             SpreadGrass(num19, num20, 23, 109, repeat: false, color3);
                         }
                         if ((num10 == 492 || num10 == 109) && AllowedToSpreadInfections)
{
                             SpreadGrass(num19, num20, 199, 109, repeat: false, color3);
                         }
                         if (Main.tile[num19, num20].type == num10)
{
                             SquareTileFrame(num19, num20);
                             flag6 = true;
                         }
                     }
                 }
             }
             if (Main.netMode == 2 && flag6)
             {
                 NetMessage.SendTileSquare(-1, i, j, 3);
             }
             break;
         }
         case 70:
         {
             if (!Main.tile[i, j].inActive())
             {
                 if (!Main.tile[i, minJ].active() && genRand.Next(10) == 0)
                 {
                     PlaceTile(i, minJ, 71, mute: true);
                     if (Main.tile[i, minJ].active())
                     {
                         Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                     }
                     if (Main.netMode == 2 && Main.tile[i, minJ].active())
                     {
                         NetMessage.SendTileSquare(-1, i, minJ);
                     }
                 }
                 if (genRand.Next(300) == 0)
                 {
                     bool flag8 = PlayerLOS(i, j);
                     if (GrowTree(i, j) && flag8)
                     {
                         TreeGrowFXCheck(i, j - 1);
                     }
                 }
             }
             bool flag9 = false;
             TileColorCache color4 = Main.tile[i, j].BlockColorAndCoating();
             for (int num21 = minI; num21 < maxI; num21++)
             {
                 for (int num22 = minJ; num22 < maxJ; num22++)
                 {
                     if ((i != num21 || j != num22) && Main.tile[num21, num22].active() && Main.tile[num21, num22].type == 59)
                     {
                         SpreadGrass(num21, num22, 59, num10, repeat: false, color4);
                         if (Main.tile[num21, num22].type == num10)
{
                             SquareTileFrame(num21, num22);
                             flag9 = true;
                         }
                     }
                 }
             }
             if (Main.netMode == 2 && flag9)
             {
                 NetMessage.SendTileSquare(-1, i, j, 3);
             }
             break;
         }
         case 60:
         {
             if (!Main.tile[i, minJ].active() && genRand.Next(7) == 0)
             {
                 PlaceTile(i, minJ, 61, mute: true);
                 if (Main.tile[i, minJ].active())
                 {
                     Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                 }
                 if (Main.netMode == 2 && Main.tile[i, minJ].active())
                 {
                     NetMessage.SendTileSquare(-1, i, minJ);
                 }
             }
             else if (genRand.Next(500) == 0 && (!Main.tile[i, minJ].active() || Main.tile[i, minJ].type == 61 || Main.tile[i, minJ].type == 74 || Main.tile[i, minJ].type == 69))
             {
                 if (GrowTree(i, j) && PlayerLOS(i, j))
                 {
                     TreeGrowFXCheck(i, j - 1);
                 }
             }
             else if (genRand.Next(25) == 0 && Main.tile[i, minJ].liquid == 0)
             {
                 PlaceJunglePlant(i, minJ, 233, genRand.Next(8), 0);
                 if (Main.tile[i, minJ].type == 233)
                 {
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, i, minJ, 4);
                     }
                     else
                     {
                         PlaceJunglePlant(i, minJ, 233, genRand.Next(12), 1);
                         if (Main.tile[i, minJ].type == 233 && Main.netMode == 2)
{
                             NetMessage.SendTileSquare(-1, i, minJ, 3);
                         }
                     }
                 }
             }
             bool flag10 = false;
             TileColorCache color5 = Main.tile[i, j].BlockColorAndCoating();
             for (int num23 = minI; num23 < maxI; num23++)
             {
                 for (int num24 = minJ; num24 < maxJ; num24++)
                 {
                     if ((i != num23 || j != num24) && Main.tile[num23, num24].active() && Main.tile[num23, num24].type == 59)
                     {
                         SpreadGrass(num23, num24, 59, num10, repeat: false, color5);
                         if (Main.tile[num23, num24].type == num10)
{
                             SquareTileFrame(num23, num24);
                             flag10 = true;
                         }
                     }
                 }
             }
             if (Main.netMode == 2 && flag10)
             {
                 NetMessage.SendTileSquare(-1, i, j, 3);
             }
             break;
         }
         case 633:
         {
             if (!Main.tile[i, minJ].active() && genRand.Next(10) == 0)
             {
                 PlaceTile(i, minJ, 637, mute: true);
                 if (Main.tile[i, minJ].active())
                 {
                     Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                 }
                 if (Main.netMode == 2 && Main.tile[i, minJ].active())
                 {
                     NetMessage.SendTileSquare(-1, i, minJ);
                 }
             }
             TileColorCache color2 = Main.tile[i, j].BlockColorAndCoating();
             bool flag5 = false;
             for (int num11 = minI; num11 < maxI; num11++)
             {
                 for (int num12 = minJ; num12 < maxJ; num12++)
                 {
                     if ((i != num11 || j != num12) && Main.tile[num11, num12].active() && Main.tile[num11, num12].type == 57)
                     {
                         SpreadGrass(num11, num12, 57, num10, repeat: false, color2);
                         if (Main.tile[num11, num12].type == num10)
{
                             SquareTileFrame(num11, num12);
                             flag5 = true;
                         }
                     }
                 }
             }
             if (Main.netMode == 2 && flag5)
             {
                 NetMessage.SendTileSquare(-1, i, j, 3);
             }
             break;
         }
         }
     }
References Tile.active(), Tile.BlockColorAndCoating(), Tile.CopyPaintAndCoating(), NPC.downedMechBoss1, NPC.downedMechBoss2, NPC.downedMechBoss3, NPC.downedMechBossAny, Main.expertMode, Main.halloween, Main.hardMode, Tile.inActive(), Tile.liquid, Main.maxTilesY, Main.netMode, NetMessage.SendTileSquare(), Main.tile, and Tile.type.