Terraria: WorldGen.CheckSign
CheckSign()
static void WorldGen.CheckSign (int x, int y, ushort type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         int num = x - 2;
         int num2 = x + 3;
         int num3 = y - 2;
         int num4 = y + 3;
         if (num < 0 || num2 > Main.maxTilesX || num3 < 0 || num4 > Main.maxTilesY)
         {
             return;
         }
         bool flag = false;
         for (int i = num; i < num2; i++)
         {
             for (int j = num3; j < num4; j++)
             {
                 if (Main.tile[i, j] == null)
                 {
                     Main.tile[i, j] = new Tile();
                 }
             }
         }
         int num5 = Main.tile[x, y].frameX / 18;
         int num6 = Main.tile[x, y].frameY / 18;
         num5 %= 2;
         num6 %= 2;
         int num7 = x - num5;
         int num8 = y - num6;
         int num9 = Main.tile[num7, num8].frameX / 18 / 2;
         int num10 = Main.tile[num7, num8].frameY / 18 / 2;
         int num11 = Main.tile[x, y].frameX / 18;
         int num12 = 0;
         while (num11 > 1)
         {
             num11 -= 2;
             num12++;
         }
         num = num7;
         num2 = num7 + 2;
         num3 = num8;
         num4 = num8 + 2;
         num5 = 0;
         for (int k = num; k < num2; k++)
         {
             num6 = 0;
             for (int l = num3; l < num4; l++)
             {
                 if (!Main.tile[k, l].active() || Main.tile[k, l].type != type)
                 {
                     flag = true;
                     break;
                 }
                 if (Main.tile[k, l].frameX / 18 != num5 + num9 * 2 || Main.tile[k, l].frameY / 18 != num6 + num10 * 2)
                 {
                     flag = true;
                     break;
                 }
                 num6++;
             }
             num5++;
         }
         if (!flag)
         {
             if (type == 85)
             {
                 if (SolidTileAllowBottomSlope(num7, num8 + 2) && SolidTileAllowBottomSlope(num7 + 1, num8 + 2))
                 {
                     num9 = num12;
                 }
                 else
                 {
                     flag = true;
                 }
             }
             else if (TopEdgeCanBeAttachedTo(num7, num8 + 2) && TopEdgeCanBeAttachedTo(num7 + 1, num8 + 2))
             {
                 num9 = 0;
             }
             else if (BottomEdgeCanBeAttachedTo(num7, num8 - 1) && BottomEdgeCanBeAttachedTo(num7 + 1, num8 - 1))
             {
                 num9 = 1;
             }
             else if (RightEdgeCanBeAttachedTo(num7 - 1, num8) && RightEdgeCanBeAttachedTo(num7 - 1, num8 + 1))
             {
                 num9 = 2;
             }
             else if (LeftEdgeCanBeAttachedTo(num7 + 2, num8) && LeftEdgeCanBeAttachedTo(num7 + 2, num8 + 1))
             {
                 num9 = 3;
             }
             else if (Main.tile[num7, num8].wall > 0 && Main.tile[num7 + 1, num8].wall > 0 && Main.tile[num7, num8 + 1].wall > 0 && Main.tile[num7 + 1, num8 + 1].wall > 0)
             {
                 num9 = 4;
             }
             else
             {
                 flag = true;
             }
         }
         if (flag)
         {
             if (type == 395)
             {
                 int num13 = TEItemFrame.Find(num7, num8);
                 if (num13 != -1 && ((TEItemFrame)TileEntity.ByID[num13]).item.stack > 0)
                 {
                     ((TEItemFrame)TileEntity.ByID[num13]).DropItem();
                     if (Main.netMode != 2)
                     {
                         Main.LocalPlayer.InterruptItemUsageIfOverTile(395);
                     }
                 }
             }
             destroyObject = true;
             for (int m = num; m < num2; m++)
             {
                 for (int n = num3; n < num4; n++)
                 {
                     if (Main.tile[m, n].type == type)
                     {
                         KillTile(m, n);
                     }
                 }
             }
             if (type != 395)
             {
                 Sign.KillSign(num7, num8);
             }
             switch (type)
             {
             case 85:
             {
                 int type2 = 321;
                 if (num12 >= 6 && num12 <= 10)
                 {
                     type2 = 3229 + num12 - 6;
                 }
                 else if (num12 >= 1 && num12 <= 5)
                 {
                     type2 = 1173 + num12 - 1;
                 }
                 Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, type2);
                 if (Main.netMode != 1 && genRand.Next(2) == 0 && NPC.CountNPCS(316) < 2)
                 {
                     int num14 = Player.FindClosest(new Vector2(x * 16, y * 16), 16, 16);
                     if (Main.player[num14].ZoneGraveyard || !Main.dayTime || (double)y > Main.worldSurface)
                     {
                         NPC.SpawnOnPlayer(num14, 316);
                     }
                 }
                 break;
             }
             case 395:
                 Item.NewItem(GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 3270);
                 TEItemFrame.Kill(num7, num8);
                 break;
             case 425:
                 Item.NewItem(GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 3617);
                 break;
             case 573:
                 Item.NewItem(GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 4710);
                 break;
             case 511:
                 Item.NewItem(GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 4320);
                 break;
             case 510:
                 Item.NewItem(GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 4319);
                 break;
             default:
                 Item.NewItem(GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 171);
                 break;
             }
             destroyObject = false;
             return;
         }
         int num15 = 36 * num9;
         for (int num16 = 0; num16 < 2; num16++)
         {
             for (int num17 = 0; num17 < 2; num17++)
             {
                 Main.tile[num7 + num16, num8 + num17].active(active: true);
                 Main.tile[num7 + num16, num8 + num17].type = type;
                 Main.tile[num7 + num16, num8 + num17].frameX = (short)(num15 + 18 * num16);
                 Main.tile[num7 + num16, num8 + num17].frameY = (short)(18 * num17 + num10 * 36);
             }
         }
     }
References Tile.active(), TileEntity.ByID, NPC.CountNPCS(), Main.dayTime, TEItemFrame.Find(), Player.FindClosest(), Tile.frameX, Tile.frameY, Player.InterruptItemUsageIfOverTile(), TEItemFrame.Kill(), Sign.KillSign(), Main.LocalPlayer, Main.maxTilesX, Main.maxTilesY, Main.netMode, Item.NewItem(), Main.player, NPC.SpawnOnPlayer(), Main.tile, Tile.type, Tile.wall, Main.worldSurface, and Player.ZoneGraveyard.