Terraria: WorldGen.Place2x2
Place2x2()
static void WorldGen.Place2x2 (int x, int y, ushort type, int style) inline static
     {
         if (type == 95 || type == 126)
         {
             y++;
         }
         if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
         {
             return;
         }
         if (type == 172)
         {
             if (!CanPlaceSink(x, y, type, style))
             {
                 return;
             }
         }
         else
         {
             for (int i = x - 1; i < x + 1; i++)
             {
                 for (int j = y - 1; j < y + 1; j++)
                 {
                     Tile tileSafely = Framing.GetTileSafely(i, j);
                     if (tileSafely.active() || (type == 98 && tileSafely.liquid > 0))
                     {
                         return;
                     }
                 }
                 switch (type)
                 {
                 case 95:
                 case 126:
                 {
                     Tile tileSafely = Framing.GetTileSafely(i, y - 2);
                     if (!tileSafely.nactive() || !Main.tileSolid[tileSafely.type] || Main.tileSolidTop[tileSafely.type])
                     {
                         return;
                     }
                     break;
                 }
                 default:
                 {
                     Tile tileSafely = Framing.GetTileSafely(i, y + 1);
                     if (!tileSafely.nactive() || (!SolidTile2(tileSafely) && !Main.tileTable[tileSafely.type]))
                     {
                         return;
                     }
                     break;
                 }
                 case 132:
                     break;
                 }
             }
         }
         if (type == 132)
         {
             bool flag = true;
             if (Main.tile[x - 1, y + 1] == null)
             {
                 Main.tile[x - 1, y + 1] = new Tile();
             }
             if (Main.tile[x, y + 1] == null)
             {
                 Main.tile[x, y + 1] = new Tile();
             }
             if (!Main.tile[x - 1, y + 1].nactive() || (!SolidTile2(x - 1, y + 1) && !Main.tileTable[Main.tile[x - 1, y + 1].type]))
             {
                 flag = false;
             }
             if (!Main.tile[x, y + 1].nactive() || (!SolidTile2(x, y + 1) && !Main.tileTable[Main.tile[x, y + 1].type]))
             {
                 flag = false;
             }
             if (!flag && (Main.tile[x - 1, y - 1].wall < 1 || Main.tile[x, y - 1].wall < 1 || Main.tile[x - 1, y].wall < 1 || Main.tile[x - 1, y].wall < 1))
             {
                 return;
             }
         }
         x--;
         y--;
         int num = ((type == 172) ? 38 : 36);
         for (int k = 0; k < 2; k++)
         {
             for (int l = 0; l < 2; l++)
             {
                 Tile tileSafely = Main.tile[x + k, y + l];
                 tileSafely.active(active: true);
                 tileSafely.frameX = (short)(k * 18);
                 tileSafely.frameY = (short)(style * num + l * 18);
                 tileSafely.type = type;
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Main.tile, Main.tileSolid, Main.tileSolidTop, Main.tileTable, Tile.type, and Tile.wall.