Terraria: WorldGen.KillTile_DropBait
KillTile_DropBait()
static void WorldGen.KillTile_DropBait (int i, int j, Tile tileCache) inline static private
     {
         int num = -1;
         int num2 = -1;
         int num3 = -1;
         int num4 = -1;
         int num5 = Player.FindClosest(new Vector2(i * 16, j * 16), 16, 16);
         if (tileCache.type == 3)
         {
             num = 400;
             num2 = 100;
             if (Main.player[num5].flowerBoots && tileCache.frameX >= 108)
             {
                 num *= 10000;
                 num2 *= 10000;
             }
         }
         if (tileCache.type == 73)
         {
             num = 200;
             num2 = 50;
             if (Main.player[num5].flowerBoots && tileCache.frameX >= 108)
             {
                 num *= 10000;
                 num2 *= 10000;
             }
         }
         if (tileCache.type == 637)
         {
             num4 = 100;
             if (Main.player[num5].flowerBoots && tileCache.frameX >= 108)
             {
                 num4 *= 10000;
             }
         }
         if (tileCache.type == 61)
         {
             num3 = 80;
             if (Main.player[num5].flowerBoots && tileCache.frameX >= 108)
             {
                 num3 *= 10000;
             }
         }
         if (tileCache.type == 74)
         {
             num3 = 40;
             if (Main.player[num5].flowerBoots && tileCache.frameX >= 108)
             {
                 num3 *= 10000;
             }
         }
         if (tileCache.type == 62)
         {
             num3 = 250;
         }
         if (tileCache.type == 185)
         {
             if (tileCache.frameY == 0 && tileCache.frameX < 214)
             {
                 num = 6;
             }
             if (tileCache.frameY == 18 && (tileCache.frameX < 214 || tileCache.frameX >= 1368))
             {
                 num = 6;
             }
         }
         else if (tileCache.type == 186)
         {
             if (tileCache.frameX >= 378 && tileCache.frameX <= 700)
             {
                 num = 6;
             }
         }
         else if (tileCache.type == 187)
         {
             if (tileCache.frameX >= 756 && tileCache.frameX <= 916)
             {
                 num = 6;
             }
             if (tileCache.frameX <= 322)
             {
                 num = 6;
             }
         }
         else if (tileCache.type == 233)
         {
             num3 = 10;
         }
         int num6 = 357;
         if (Main.player[num5].ZoneGraveyard)
         {
             num6 = 606;
         }
         if (num > 0 && NPC.CountNPCS(num6) < 5 && genRand.Next(num) == 0)
         {
             int type = num6;
             if (num6 == 357 && Player.GetClosestRollLuck(i, j, NPC.goldCritterChance) == 0f)
             {
                 type = 448;
             }
             int num7 = NPC.NewNPC(GetNPCSource_TileBreak(i, j), i * 16 + 10, j * 16, type);
             Main.npc[num7].TargetClosest();
             Main.npc[num7].velocity.Y = (float)genRand.Next(-50, -21) * 0.1f;
             Main.npc[num7].velocity.X = (float)genRand.Next(0, 26) * 0.1f * (float)(-Main.npc[num7].direction);
             Main.npc[num7].direction *= -1;
             Main.npc[num7].netUpdate = true;
         }
         if (num2 > 0 && NPC.CountNPCS(377) < 5 && genRand.Next(num2) == 0)
         {
             int type2 = 377;
             if (Player.GetClosestRollLuck(i, j, NPC.goldCritterChance) == 0f)
             {
                 type2 = 446;
             }
             int num8 = NPC.NewNPC(GetNPCSource_TileBreak(i, j), i * 16 + 10, j * 16, type2);
             Main.npc[num8].TargetClosest();
             Main.npc[num8].velocity.Y = (float)genRand.Next(-50, -21) * 0.1f;
             Main.npc[num8].velocity.X = (float)genRand.Next(0, 26) * 0.1f * (float)(-Main.npc[num8].direction);
             Main.npc[num8].direction *= -1;
             Main.npc[num8].netUpdate = true;
         }
         if (num3 > 0 && NPC.CountNPCS(485) + NPC.CountNPCS(486) + NPC.CountNPCS(487) < 8 && genRand.Next(num3) == 0)
         {
             int type3 = 485;
             if (genRand.Next(4) == 0)
             {
                 type3 = 486;
             }
             if (genRand.Next(12) == 0)
             {
                 type3 = 487;
             }
             int num9 = NPC.NewNPC(GetNPCSource_TileBreak(i, j), i * 16 + 10, j * 16, type3);
             Main.npc[num9].TargetClosest();
             Main.npc[num9].velocity.Y = (float)genRand.Next(-50, -21) * 0.1f;
             Main.npc[num9].velocity.X = (float)genRand.Next(0, 26) * 0.1f * (float)(-Main.npc[num9].direction);
             Main.npc[num9].direction *= -1;
             Main.npc[num9].netUpdate = true;
         }
         if (num4 > 0 && NPC.CountNPCS(654) + NPC.CountNPCS(653) < 8 && genRand.Next(num4) == 0)
         {
             int type4 = 653;
             if (genRand.Next(2) == 0)
             {
                 type4 = 654;
             }
             int num10 = NPC.NewNPC(GetNPCSource_TileBreak(i, j), i * 16 + 10, j * 16, type4);
             Main.npc[num10].TargetClosest();
             Main.npc[num10].velocity.Y = (float)genRand.Next(-50, -21) * 0.1f;
             Main.npc[num10].velocity.X = (float)genRand.Next(0, 26) * 0.1f * (float)(-Main.npc[num10].direction);
             Main.npc[num10].direction *= -1;
             Main.npc[num10].netUpdate = true;
         }
     }
References NPC.CountNPCS(), Entity.direction, Player.FindClosest(), Player.flowerBoots, Tile.frameX, Tile.frameY, Player.GetClosestRollLuck(), NPC.goldCritterChance, NPC.netUpdate, NPC.NewNPC(), Main.npc, Main.player, NPC.TargetClosest(), Tile.type, Entity.velocity, and Player.ZoneGraveyard.