Terraria: WorldGen.SpreadGrass
SpreadGrass()
static void WorldGen.SpreadGrass (int i, int j, int dirt = 0, int grass = 2, bool repeat = true, TileColorCache color = default(TileColorCache)) inline static
     {
         try
         {
             if (!InWorld(i, j, 10) || !Main.tile[i, j].active() || Main.tile[i, j].type != dirt)
             {
                 return;
             }
             if (gen && (grass == 199 || grass == 23))
             {
                 int num = beachDistance;
                 if ((!tenthAnniversaryWorldGen && (double)i > (double)Main.maxTilesX * 0.45 && (double)i <= (double)Main.maxTilesX * 0.55) || i < num || i >= Main.maxTilesX - num)
                 {
                     return;
                 }
             }
             else if ((gen || (grass != 199 && grass != 23 && grass != 661 && grass != 662)) && (Main.tile[i, j].type != dirt || !Main.tile[i, j].active() || ((double)j >= Main.worldSurface && dirt == 0)) && !growGrassUnderground)
             {
                 return;
             }
             int num2 = i - 1;
             int num3 = i + 2;
             int num4 = j - 1;
             int num5 = j + 2;
             if (num2 < 0)
             {
                 num2 = 0;
             }
             if (num3 > Main.maxTilesX)
             {
                 num3 = Main.maxTilesX;
             }
             if (num4 < 0)
             {
                 num4 = 0;
             }
             if (num5 > Main.maxTilesY)
             {
                 num5 = Main.maxTilesY;
             }
             bool flag = true;
             for (int k = num2; k < num3; k++)
             {
                 for (int l = num4; l < num5; l++)
                 {
                     if (!Main.tile[k, l].active() || !Main.tileSolid[Main.tile[k, l].type])
                     {
                         flag = false;
                     }
                     if (Main.tile[k, l].lava() && Main.tile[k, l].liquid > 0)
                     {
                         flag = true;
                         break;
                     }
                 }
             }
             if (flag || !TileID.Sets.CanBeClearedDuringGeneration[Main.tile[i, j].type] || ((grass == 23 || grass == 661) && Main.tile[i, j - 1].type == 27) || ((grass == 199 || grass == 662) && Main.tile[i, j - 1].type == 27) || (grass == 109 && Main.tile[i, j - 1].type == 27))
             {
                 return;
             }
             Main.tile[i, j].type = (ushort)grass;
             Main.tile[i, j].UseBlockColors(color);
             for (int m = num2; m < num3; m++)
             {
                 for (int n = num4; n < num5; n++)
                 {
                     if (!Main.tile[m, n].active() || Main.tile[m, n].type != dirt)
                     {
                         continue;
                     }
                     try
                     {
                         if (repeat && grassSpread < 1000)
{
                             grassSpread++;
                             SpreadGrass(m, n, dirt, grass);
                             grassSpread--;
                         }
                     }
                     catch
                     {
                     }
                 }
             }
         }
         catch
         {
         }
     }
References Tile.active(), TileID.Sets.CanBeClearedDuringGeneration, Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.tile, Main.tileSolid, Tile.type, Tile.UseBlockColors(), and Main.worldSurface.
Referenced by GenerateWorld(), and neonMossBiome().