Terraria: WorldGen.IsFitToPlaceFlowerIn
IsFitToPlaceFlowerIn()
static bool WorldGen.IsFitToPlaceFlowerIn (int x, int y, int typeAttemptedToPlace) inline static
     {
         if (y < 1 || y > Main.maxTilesY - 1)
         {
             return false;
         }
         Tile tile = Main.tile[x, y + 1];
         if (tile.active() && tile.slope() == 0 && !tile.halfBrick())
         {
             if (((tile.type != 2 && tile.type != 78 && tile.type != 380 && tile.type != 477 && tile.type != 579) || typeAttemptedToPlace != 3) && ((tile.type != 23 && tile.type != 661) || typeAttemptedToPlace != 24) && ((tile.type != 109 && tile.type != 492) || typeAttemptedToPlace != 110) && ((tile.type != 199 && tile.type != 662) || typeAttemptedToPlace != 201))
             {
                 if (tile.type == 633)
                 {
                     return typeAttemptedToPlace == 637;
                 }
                 return false;
             }
             return true;
         }
         return false;
     }
References Tile.active(), Tile.halfBrick(), Main.maxTilesY, Tile.slope(), Main.tile, and Tile.type.
Referenced by Player.PlaceThing_Tiles_BlockPlacementForAssortedThings().