Terraria: WorldGen.TryToggleLight
TryToggleLight()
static bool WorldGen.TryToggleLight (int x, int y, bool? forcedState, bool skipWires) inline static
     {
         Tile tile = Main.tile[x, y];
         if (!tile.active())
         {
             return false;
         }
         switch (tile.type)
         {
         default:
             return false;
         case 4:
             Wiring.ToggleTorch(x, y, tile, forcedState);
             return true;
         case 33:
         case 49:
         case 174:
         case 372:
         case 646:
             Wiring.ToggleCandle(x, y, tile, forcedState);
             return true;
         case 405:
             Wiring.ToggleFirePlace(x, y, tile, forcedState, skipWires);
             return true;
         case 95:
         case 100:
         case 126:
         case 173:
         case 564:
             Wiring.Toggle2x2Light(x, y, tile, forcedState, skipWires);
             return true;
         case 92:
             Wiring.ToggleLampPost(x, y, tile, forcedState, skipWires);
             return true;
         case 215:
             Wiring.ToggleCampFire(x, y, tile, forcedState, skipWires);
             return true;
         case 34:
             Wiring.ToggleChandelier(x, y, tile, forcedState, skipWires);
             return true;
         case 93:
             Wiring.ToggleLamp(x, y, tile, forcedState, skipWires);
             return true;
         case 42:
             Wiring.ToggleHangingLantern(x, y, tile, forcedState, skipWires);
             return true;
         case 149:
             Wiring.ToggleHolidayLight(x, y, tile, forcedState);
             return true;
         }
     }
References Tile.active(), Main.tile, Wiring.Toggle2x2Light(), Wiring.ToggleCampFire(), Wiring.ToggleCandle(), Wiring.ToggleChandelier(), Wiring.ToggleFirePlace(), Wiring.ToggleHangingLantern(), Wiring.ToggleHolidayLight(), Wiring.ToggleLamp(), Wiring.ToggleLampPost(), Wiring.ToggleTorch(), and Tile.type.