Terraria: WorldGen.PlaceLiquid
PlaceLiquid()
static bool WorldGen.PlaceLiquid (int x, int y, byte liquidType, byte amount) inline static
     {
         if (!InWorld(x, y))
         {
             return false;
         }
         Tile tile = Main.tile[x, y];
         if (tile == null)
         {
             return false;
         }
         byte b = tile.liquidType();
         if (tile.nactive() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
         {
             return false;
         }
         if (tile.liquid == 0 || liquidType == b)
         {
             tile.liquidType(liquidType);
             if (amount + tile.liquid > 255)
             {
                 amount = (byte)(255 - tile.liquid);
             }
             tile.liquid += amount;
             SquareTileFrame(x, y);
             if (Main.netMode != 0)
             {
                 NetMessage.sendWater(x, y);
             }
             return true;
         }
         int liquidMergeTileType = 0;
         bool waterNearby = b == 0;
         bool lavaNearby = b == 1;
         bool honeyNearby = b == 2;
         bool shimmerNearby = b == 3;
         int liquidMergeType = 0;
         Liquid.GetLiquidMergeTypes(liquidType, out liquidMergeTileType, out liquidMergeType, waterNearby, lavaNearby, honeyNearby, shimmerNearby);
         if (liquidMergeTileType != 0)
         {
             tile.liquid = 0;
             tile.liquidType(0);
             PlaceTile(x, y, liquidMergeTileType, mute: true);
             SquareTileFrame(x, y);
             if (Main.netMode != 0)
             {
                 NetMessage.SendTileSquare(-1, x - 1, y - 1, GetLiquidChangeType(liquidType, b));
             }
             return true;
         }
         return false;
     }
References GetLiquidChangeType(), InWorld(), Liquid, Tile.liquid, Tile.liquidType(), Tile.nactive(), Main.netMode, PlaceTile(), NetMessage.SendTileSquare(), NetMessage.sendWater(), SquareTileFrame(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by DelegateMethods.SpreadHoney(), DelegateMethods.SpreadLava(), and DelegateMethods.SpreadWater().