Terraria: WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections
CheckProjectilePressurePad_GetPossiblePlacementDirections()
static void WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections (int i, int j, out bool canUp, out bool canLeft, out bool canRight, out bool canDown) inline static private
     {
         canUp = false;
         canLeft = false;
         canRight = false;
         canDown = false;
         _ = Main.tile[i, j];
         Tile tile = Main.tile[i, j - 1];
         Tile tile2 = Main.tile[i, j + 1];
         Tile tile3 = Main.tile[i - 1, j];
         Tile tile4 = Main.tile[i + 1, j];
         Tile tile5 = Main.tile[i - 1, j + 1];
         Tile tile6 = Main.tile[i + 1, j + 1];
         Tile tile7 = Main.tile[i - 1, j - 1];
         Tile tile8 = Main.tile[i + 1, j - 1];
         int num = -1;
         int num2 = -1;
         int num3 = -1;
         int num4 = -1;
         int tree = -1;
         int tree2 = -1;
         int tree3 = -1;
         int tree4 = -1;
         if (tile != null && tile.nactive() && !tile.bottomSlope())
         {
             num2 = tile.type;
         }
         if (tile2 != null && tile2.nactive() && !tile2.halfBrick() && !tile2.topSlope())
         {
             num = tile2.type;
         }
         if (tile3 != null && tile3.nactive() && (tile3.slope() == 0 || tile3.slope() % 2 != 1))
         {
             num3 = tile3.type;
         }
         if (tile4 != null && tile4.nactive() && (tile4.slope() == 0 || tile4.slope() % 2 != 0))
         {
             num4 = tile4.type;
         }
         if (tile5 != null && tile5.nactive())
         {
             tree = tile5.type;
         }
         if (tile6 != null && tile6.nactive())
         {
             tree2 = tile6.type;
         }
         if (tile7 != null && tile7.nactive())
         {
             tree3 = tile7.type;
         }
         if (tile8 != null && tile8.nactive())
         {
             tree4 = tile8.type;
         }
         if (num >= 0 && Main.tileSolid[num] && (!Main.tileNoAttach[num] || TileID.Sets.Platforms[num]) && (tile2.bottomSlope() || tile2.slope() == 0) && !tile2.halfBrick())
         {
             canDown = true;
         }
         if (num2 >= 0 && Main.tileSolid[num2] && (!Main.tileNoAttach[num2] || (TileID.Sets.Platforms[num2] && tile.halfBrick())) && (tile.topSlope() || tile.slope() == 0 || tile.halfBrick()))
         {
             canUp = true;
         }
         if ((num3 >= 0 && Main.tileSolid[num3] && !Main.tileNoAttach[num3] && (tile3.leftSlope() || tile3.slope() == 0) && !tile3.halfBrick()) || (num3 >= 0 && TileID.Sets.IsBeam[num3]) || (IsTreeType(num3) && IsTreeType(tree3) && IsTreeType(tree)))
         {
             canLeft = true;
         }
         if ((num4 >= 0 && Main.tileSolid[num4] && !Main.tileNoAttach[num4] && (tile4.rightSlope() || tile4.slope() == 0) && !tile4.halfBrick()) || (num4 >= 0 && TileID.Sets.IsBeam[num4]) || (IsTreeType(num4) && IsTreeType(tree4) && IsTreeType(tree2)))
         {
             canRight = true;
         }
     }
References Tile.bottomSlope(), Tile.halfBrick(), TileID.Sets.IsBeam, Tile.leftSlope(), Tile.nactive(), TileID.Sets.Platforms, Tile.rightSlope(), Tile.slope(), Main.tile, Main.tileNoAttach, Main.tileSolid, Tile.topSlope(), and Tile.type.