Terraria: WorldGen.OrePatch
OrePatch()
static bool WorldGen.OrePatch (int X, int Y) inline static
     {
         //IL_04b1: Unknown result type (might be due to invalid IL or missing references)
         //IL_04b3: Unknown result type (might be due to invalid IL or missing references)
         //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
         //IL_04ba: Unknown result type (might be due to invalid IL or missing references)
         //IL_050e: Unknown result type (might be due to invalid IL or missing references)
         //IL_052d: Unknown result type (might be due to invalid IL or missing references)
         //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
         //IL_03ee: Unknown result type (might be due to invalid IL or missing references)
         //IL_03f3: Unknown result type (might be due to invalid IL or missing references)
         //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
         ushort type = (ushort)SavedOreTiers.Copper;
         if (genRand.Next(3) == 0)
         {
             type = (ushort)SavedOreTiers.Iron;
         }
         int num = X;
         int num2 = Y;
         while (!SolidTile(num, num2))
         {
             num2++;
             if ((double)num2 > Main.worldSurface)
             {
                 return false;
             }
         }
         if (!TileID.Sets.Conversion.Grass[Main.tile[num, num2].type] || !TileID.Sets.Conversion.Grass[Main.tile[num - 1, num2].type] || !TileID.Sets.Conversion.Grass[Main.tile[num + 1, num2].type])
         {
             return false;
         }
         if (Main.tile[num, num2].wall > 0)
         {
             return false;
         }
         for (int i = num - 10; i <= num + 10; i++)
         {
             for (int j = num2 + 7; j <= num2 + 30; j++)
             {
                 if (!Main.tile[i, j].active() || Main.tileDungeon[Main.tile[i, j].type] || TileID.Sets.Clouds[Main.tile[i, j].type] || TileID.Sets.Conversion.Sand[Main.tile[i, j].type] || Main.tile[i, j].wall == 0)
                 {
                     return false;
                 }
             }
         }
         num2 += genRand.Next(2);
         Main.tile[num, num2].type = type;
         Main.tile[num, num2].active(active: true);
         OreHelper(num, num2);
         if (!gen)
         {
             SquareTileFrame(num, num2);
         }
         int num3 = num2;
         while (num2 < num3 + genRand.Next(8, 13))
         {
             num += genRand.Next(-1, 2);
             num2 += genRand.Next(1, 3);
             if (genRand.Next(3) == 0)
             {
                 num2++;
             }
             Main.tile[num, num2].type = type;
             Main.tile[num, num2].active(active: true);
             OreHelper(num, num2);
             if (!gen)
             {
                 SquareTileFrame(num, num2);
             }
             if (genRand.Next(4) == 0)
             {
                 int num4 = num + genRand.Next(-2, 3);
                 int num5 = num2 + genRand.Next(2);
                 Main.tile[num4, num5].type = type;
                 Main.tile[num4, num5].active(active: true);
                 OreHelper(num4, num5);
                 if (!gen)
                 {
                     SquareTileFrame(num4, num5);
                 }
             }
         }
         Vector2D val = default(Vector2D);
         ((Vector2D)(ref val))._002Ector((double)num, (double)num2);
         Vector2D val2 = default(Vector2D);
         val2.X = genRand.NextDouble() * 0.6 - 0.3;
         val2.Y = genRand.NextDouble() * 0.5 + 0.5;
         double num6 = genRand.Next(5, 9);
         int num7 = genRand.Next(9, 14);
         if (genRand.Next(3) == 0)
         {
             num6 += (double)genRand.Next(2);
         }
         if (genRand.Next(3) == 0)
         {
             num7 += genRand.Next(2);
         }
         while (num7 > 0)
         {
             num7--;
             for (int k = num - (int)num6 * 4; (double)k <= (double)num + num6 * 4.0; k++)
             {
                 for (int l = num2 - (int)num6 * 4; (double)l <= (double)num2 + num6 * 4.0; l++)
                 {
                     double num8 = num6 * (0.5 + genRand.NextDouble() * 0.5) * 0.1;
                     double num9 = num6 * (0.7 + genRand.NextDouble() * 0.6) * 0.3;
                     if (genRand.Next(8) == 0)
                     {
                         num9 *= 2.0;
                     }
                     Vector2D val3 = val - new Vector2D((double)k, (double)l);
                     if (((Vector2D)(ref val3)).Length() < num8)
                     {
                         Main.tile[k, l].active(active: false);
                     }
                     else if (((Vector2D)(ref val3)).Length() < num9)
                     {
                         Main.tile[k, l].type = type;
                         if (genRand.Next(4) == 0)
{
                             Main.tile[k, l].active(active: true);
                         }
                         OreHelper(k, l);
                         if (!gen)
{
                             SquareTileFrame(k, l);
                         }
                     }
                 }
             }
             val += val2;
             val2.X += genRand.NextDouble() * 0.2 - 0.1;
             val2.Y += genRand.NextDouble() * 0.2 - 0.1;
             Utils.Clamp(val2.X, -0.3, 0.3);
             Utils.Clamp(val2.Y, 0.5, 1.0);
         }
         return true;
     }
References Tile.active(), TileID.Sets.Clouds, WorldGen.SavedOreTiers.Copper, gen, genRand, TileID.Sets.Conversion.Grass, WorldGen.SavedOreTiers.Iron, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), OreHelper(), TileID.Sets.Conversion.Sand, SolidTile(), SquareTileFrame(), Main.tile, Main.tileDungeon, Tile.type, Tile.wall, Main.worldSurface, X, Vector2D.X, Y, and Vector2D.Y.