Terraria: WorldGen.TriggerLunarApocalypse
TriggerLunarApocalypse()
static void WorldGen.TriggerLunarApocalypse () inline static
     {
         List<int> list = new List<int> { 517, 422, 507, 493 };
         int[] array = new int[4];
         for (int i = 0; i < 4; i++)
         {
             array[i] = list[Main.rand.Next(list.Count)];
             list.Remove(array[i]);
         }
         int num = Main.maxTilesX / 5;
         int num2 = (int)Main.worldSurface;
         for (int j = 0; j < 4; j++)
         {
             int num3 = num * (1 + j);
             bool flag = false;
             for (int k = 0; k < 30; k++)
             {
                 int num4 = Main.rand.Next(-100, 101);
                 if (Main.remixWorld && Main.getGoodWorld)
                 {
                     int num5 = Main.rand.Next((int)Main.worldSurface, Main.maxTilesY - 350);
                     if (!PlayerLOS(num3 + num4 - 10, num5) && !PlayerLOS(num3 + num4 + 10, num5) && !PlayerLOS(num3 + num4 - 10, num5 - 20) && !PlayerLOS(num3 + num4 + 10, num5 - 20))
                     {
                         int num6 = NPC.NewNPC(new EntitySource_WorldEvent(), (num3 + num4) * 16, num5 * 16, array[j]);
                         if (Main.netMode == 2 && num6 < 200)
{
                             NetMessage.SendData(23, -1, -1, null, num6);
                         }
                         flag = true;
                         break;
                     }
                     continue;
                 }
                 for (int num7 = num2; num7 > 100; num7--)
                 {
                     if (!Collision.SolidTiles(num3 + num4 - 10, num3 + num4 + 10, num7 - 20, num7 + 15) && !PlayerLOS(num3 + num4 - 10, num7) && !PlayerLOS(num3 + num4 + 10, num7) && !PlayerLOS(num3 + num4 - 10, num7 - 20) && !PlayerLOS(num3 + num4 + 10, num7 - 20))
                     {
                         int num8 = NPC.NewNPC(new EntitySource_WorldEvent(), (num3 + num4) * 16, num7 * 16, array[j]);
                         if (Main.netMode == 2 && num8 < 200)
{
                             NetMessage.SendData(23, -1, -1, null, num8);
                         }
                         flag = true;
                         break;
                     }
                 }
                 if (flag)
                 {
                     break;
                 }
             }
             if (!flag)
             {
                 NPC.NewNPC(new EntitySource_WorldEvent(), num3 * 16, (num2 - 40) * 16, array[j]);
             }
         }
         NPC.TowerActiveVortex = (NPC.TowerActiveNebula = (NPC.TowerActiveSolar = (NPC.TowerActiveStardust = true)));
         NPC.LunarApocalypseIsUp = true;
         NPC.ShieldStrengthTowerSolar = (NPC.ShieldStrengthTowerVortex = (NPC.ShieldStrengthTowerNebula = (NPC.ShieldStrengthTowerStardust = NPC.ShieldStrengthTowerMax)));
         NetMessage.SendData(101);
         MessageLunarApocalypse();
     }
References Main.getGoodWorld, NPC.LunarApocalypseIsUp, Main.maxTilesX, Main.maxTilesY, Main.netMode, NPC.NewNPC(), UnifiedRandom.Next(), Main.rand, Main.remixWorld, NetMessage.SendData(), NPC.ShieldStrengthTowerMax, NPC.ShieldStrengthTowerNebula, NPC.ShieldStrengthTowerSolar, NPC.ShieldStrengthTowerStardust, NPC.ShieldStrengthTowerVortex, Collision.SolidTiles(), NPC.TowerActiveNebula, NPC.TowerActiveSolar, NPC.TowerActiveStardust, NPC.TowerActiveVortex, and Main.worldSurface.
Referenced by NPC.DoDeathEvents().