Terraria: WorldGen.PlaceAlch
PlaceAlch()
static bool WorldGen.PlaceAlch (int x, int y, int style) inline static
     {
         if (Main.tile[x, y] == null)
         {
             Main.tile[x, y] = new Tile();
         }
         if (Main.tile[x, y + 1] == null)
         {
             Main.tile[x, y + 1] = new Tile();
         }
         if (!Main.tile[x, y].active() && Main.tile[x, y + 1].nactive() && !Main.tile[x, y + 1].halfBrick() && Main.tile[x, y + 1].slope() == 0)
         {
             bool flag = false;
             switch (style)
             {
             case 0:
                 if (Main.tile[x, y + 1].type != 2 && Main.tile[x, y + 1].type != 477 && Main.tile[x, y + 1].type != 492 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380 && Main.tile[x, y + 1].type != 109)
                 {
                     flag = true;
                 }
                 if (Main.tile[x, y].liquid > 0)
                 {
                     flag = true;
                 }
                 break;
             case 1:
                 if (Main.tile[x, y + 1].type != 60 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                 {
                     flag = true;
                 }
                 if (Main.tile[x, y].liquid > 0)
                 {
                     flag = true;
                 }
                 break;
             case 2:
                 if (Main.tile[x, y + 1].type != 0 && Main.tile[x, y + 1].type != 59 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                 {
                     flag = true;
                 }
                 if (Main.tile[x, y].liquid > 0)
                 {
                     flag = true;
                 }
                 break;
             case 3:
                 if (Main.tile[x, y + 1].type != 661 && Main.tile[x, y + 1].type != 662 && Main.tile[x, y + 1].type != 203 && Main.tile[x, y + 1].type != 199 && Main.tile[x, y + 1].type != 23 && Main.tile[x, y + 1].type != 25 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                 {
                     flag = true;
                 }
                 if (Main.tile[x, y].liquid > 0)
                 {
                     flag = true;
                 }
                 break;
             case 4:
                 if (Main.tile[x, y + 1].type != 53 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380 && Main.tile[x, y + 1].type != 116)
                 {
                     flag = true;
                 }
                 if (Main.tile[x, y].liquid > 0 && Main.tile[x, y].lava())
                 {
                     flag = true;
                 }
                 break;
             case 5:
                 if (Main.tile[x, y + 1].type != 57 && Main.tile[x, y + 1].type != 633 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                 {
                     flag = true;
                 }
                 if (Main.tile[x, y].liquid > 0 && !Main.tile[x, y].lava())
                 {
                     flag = true;
                 }
                 break;
             case 6:
                 if (Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380 && Main.tile[x, y + 1].type != 147 && Main.tile[x, y + 1].type != 161 && Main.tile[x, y + 1].type != 163 && Main.tile[x, y + 1].type != 164 && Main.tile[x, y + 1].type != 200)
                 {
                     flag = true;
                 }
                 if (Main.tile[x, y].liquid > 0 && Main.tile[x, y].lava())
                 {
                     flag = true;
                 }
                 break;
             }
             if (!flag)
             {
                 Main.tile[x, y].active(active: true);
                 Main.tile[x, y].type = 82;
                 Main.tile[x, y].frameX = (short)(18 * style);
                 Main.tile[x, y].frameY = 0;
                 return true;
             }
         }
         return false;
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.lava(), Tile.liquid, Tile.nactive(), Tile.slope(), Main.tile, and Tile.type.