Terraria: WorldGen.QuickFindHome
QuickFindHome()
static void WorldGen.QuickFindHome (int npc) inline static
     {
         bool flag = Main.tileSolid[379];
         Main.tileSolid[379] = true;
         if (Main.npc[npc].homeTileX > 10 && Main.npc[npc].homeTileY > 10 && Main.npc[npc].homeTileX < Main.maxTilesX - 10 && Main.npc[npc].homeTileY < Main.maxTilesY)
         {
             canSpawn = false;
             StartRoomCheck(Main.npc[npc].homeTileX, Main.npc[npc].homeTileY - 1);
             if (!canSpawn)
             {
                 for (int i = Main.npc[npc].homeTileX - 1; i < Main.npc[npc].homeTileX + 2; i++)
                 {
                     for (int j = Main.npc[npc].homeTileY - 1; j < Main.npc[npc].homeTileY + 2 && !StartRoomCheck(i, j); j++)
                     {
                     }
                 }
             }
             if (!canSpawn)
             {
                 int num = 10;
                 for (int k = Main.npc[npc].homeTileX - num; k <= Main.npc[npc].homeTileX + num; k += 2)
                 {
                     for (int l = Main.npc[npc].homeTileY - num; l <= Main.npc[npc].homeTileY + num && !StartRoomCheck(k, l); l += 2)
                     {
                     }
                 }
             }
             if (canSpawn)
             {
                 RoomNeeds(Main.npc[npc].type);
                 if (canSpawn)
                 {
                     ScoreRoom(npc, Main.npc[npc].type);
                 }
                 if (canSpawn && hiScore > 0)
                 {
                     canSpawn = IsRoomConsideredOccupiedForNPCIndex(npc);
                 }
                 if (canSpawn && hiScore > 0)
                 {
                     Main.npc[npc].homeTileX = bestX;
                     Main.npc[npc].homeTileY = bestY;
                     Main.npc[npc].homeless = false;
                     AchievementsHelper.NotifyProgressionEvent(8);
                     canSpawn = false;
                 }
                 else
                 {
                     Main.npc[npc].homeless = true;
                 }
             }
             else
             {
                 Main.npc[npc].homeless = true;
             }
         }
         Main.tileSolid[379] = flag;
     }
References bestX, bestY, canSpawn, hiScore, NPC.homeless, NPC.homeTileX, NPC.homeTileY, IsRoomConsideredOccupiedForNPCIndex(), Main.maxTilesX, Main.maxTilesY, AchievementsHelper.NotifyProgressionEvent(), Main.npc, RoomNeeds(), ScoreRoom(), StartRoomCheck(), Main.tileSolid, and NPC.type.
Referenced by NPC.AI_007_TownEntities_TeleportToHome(), and Main.UpdateTime_SpawnTownNPCs().