Terraria: WorldGen.CheckPot
CheckPot()
static void WorldGen.CheckPot (int i, int j, int type = 28) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         int num = 0;
         int num2 = j;
         for (num += Main.tile[i, j].frameX / 18; num > 1; num -= 2)
         {
         }
         num *= -1;
         num += i;
         int num3 = Main.tile[i, j].frameY / 18;
         int num4 = 0;
         while (num3 > 1)
         {
             num3 -= 2;
             num4++;
         }
         num2 -= num3;
         for (int k = num; k < num + 2; k++)
         {
             for (int l = num2; l < num2 + 2; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 int num5;
                 for (num5 = Main.tile[k, l].frameX / 18; num5 > 1; num5 -= 2)
                 {
                 }
                 if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || num5 != k - num || Main.tile[k, l].frameY != (l - num2) * 18 + num4 * 36)
                 {
                     flag = true;
                 }
             }
             if (Main.tile[k, num2 + 2] == null)
             {
                 Main.tile[k, num2 + 2] = new Tile();
             }
             if (!SolidTile2(k, num2 + 2))
             {
                 flag = true;
             }
         }
         if (!flag)
         {
             return;
         }
         destroyObject = true;
         if (num4 >= 7 && num4 <= 9)
         {
             SoundEngine.PlaySound(6, i * 16, j * 16);
         }
         else if (num4 >= 16 && num4 <= 24)
         {
             SoundEngine.PlaySound(4, i * 16, j * 16);
         }
         else
         {
             SoundEngine.PlaySound(13, i * 16, j * 16);
         }
         for (int m = num; m < num + 2; m++)
         {
             for (int n = num2; n < num2 + 2; n++)
             {
                 if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                 {
                     KillTile(m, n);
                 }
             }
         }
         switch (num4)
         {
         case 0:
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 51);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 52);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 53);
             break;
         case 1:
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 166);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 167);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 168);
             break;
         case 2:
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 169);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 170);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 171);
             break;
         case 3:
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 172);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 173);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 174);
             break;
         case 4:
         case 5:
         case 6:
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 197);
             Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 198);
             break;
         default:
             if (num4 >= 7 && num4 <= 9)
             {
                 Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 199);
                 Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 200);
             }
             else if (num4 >= 10 && num4 <= 12)
             {
                 Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 201);
                 Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 202);
             }
             else if (num4 >= 13 && num4 <= 15)
             {
                 Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 203);
                 Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 204);
             }
             else
             {
                 if ((num4 >= 16 && num4 <= 18) || (num4 >= 19 && num4 <= 21) || (num4 >= 22 && num4 <= 24))
                 {
                     break;
                 }
                 if (num4 >= 25 && num4 <= 27)
                 {
                     Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), genRand.Next(217, 220));
                     Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), genRand.Next(217, 220));
                 }
                 else if (num4 >= 28 && num4 <= 30)
                 {
                     Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), genRand.Next(315, 317));
                     Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), genRand.Next(315, 317));
                 }
                 else if (num4 >= 31 && num4 <= 33)
                 {
                     int num6 = genRand.Next(2, 5);
                     for (int num7 = 0; num7 < num6; num7++)
                     {
                         Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 698 + genRand.Next(6));
                     }
                 }
                 else if (num4 >= 34 && num4 <= 36)
                 {
                     Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 1122);
                     Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 1123);
                     Gore.NewGore(new Vector2(i * 16, j * 16), default(Vector2), 1124);
                 }
             }
             break;
         }
         if (Main.netMode != 1 && type != 653)
         {
             SpawnThingsFromPot(i, j, num, num2, num4);
         }
         destroyObject = false;
     }
References Tile.active(), Tile.frameX, Tile.frameY, Main.netMode, Gore.NewGore(), SoundEngine.PlaySound(), Main.tile, and Tile.type.