Terraria: WorldGen.IsRope
IsRope()
static bool WorldGen.IsRope (int x, int y) inline static
     {
         if (Main.tile[x, y] == null || !Main.tile[x, y].active())
         {
             return false;
         }
         if (Main.tileRope[Main.tile[x, y].type])
         {
             return true;
         }
         if ((Main.tile[x, y].type == 314 || TileID.Sets.Platforms[Main.tile[x, y].type]) && Main.tile[x, y - 1] != null && Main.tile[x, y + 1] != null && Main.tile[x, y - 1].active() && Main.tile[x, y + 1].active() && Main.tileRope[Main.tile[x, y - 1].type] && Main.tileRope[Main.tile[x, y + 1].type])
         {
             return true;
         }
         return false;
     }
References Tile.active(), TileID.Sets.Platforms, Main.tile, Main.tileRope, and Tile.type.
Referenced by TileDrawing.DrawBasicTile(), TileDrawing.DrawTile_MinecartTrack(), Player.FindPulley(), and Player.Update().