Terraria: WorldGen.Check2x2
Check2x2()
static void WorldGen.Check2x2 (int i, int j, int type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         int num = 0;
         int num2 = Main.tile[i, j].frameX / 18 * -1;
         if (num2 < -1)
         {
             num2 += 2;
             num = 36;
         }
         num2 += i;
         int num3 = ((type == 172) ? 38 : 36);
         int num4 = Main.tile[i, j].frameY;
         int num5 = 0;
         while (num4 >= num3)
         {
             num4 -= num3;
             num5++;
         }
         int num6 = j - num4 / 18;
         int num7 = 0;
         if (type == 652)
         {
             num7 = Main.tile[i, j].frameX / 36;
             num2 = Main.tile[i, j].frameX % 36 / 18 * -1 + i;
             num = num7 * 36;
         }
         for (int k = num2; k < num2 + 2; k++)
         {
             for (int l = num6; l < num6 + 2; l++)
             {
                 Tile tileSafely = Framing.GetTileSafely(k, l);
                 if (!tileSafely.active() || tileSafely.type != type || tileSafely.frameX != (k - num2) * 18 + num || tileSafely.frameY != (l - num6) * 18 + num5 * num3)
                 {
                     flag = true;
                     break;
                 }
             }
             if (type == 95 || type == 126)
             {
                 Framing.GetTileSafely(k, num6 - 1);
                 if (!Main.tile[k, num6 - 1].active() || !Main.tileSolid[Main.tile[k, num6 - 1].type] || Main.tileSolidTop[Main.tile[k, num6 - 1].type])
                 {
                     flag = true;
                 }
             }
             else if (!TileID.Sets.Boulders[type] && type != 132)
             {
                 Tile tileSafely2 = Framing.GetTileSafely(k, num6 + 2);
                 if (!tileSafely2.active() || (!Main.tileSolid[tileSafely2.type] && !Main.tileTable[tileSafely2.type]))
                 {
                     flag = true;
                 }
                 if (tileSafely2.halfBrick())
                 {
                     flag = true;
                 }
             }
         }
         if (TileID.Sets.Boulders[type])
         {
             if (Main.tile[num2, num6 - 1] == null)
             {
                 Main.tile[num2, num6 - 1] = new Tile();
             }
             if (Main.tile[num2 + 1, num6 - 1] == null)
             {
                 Main.tile[num2 + 1, num6 - 1] = new Tile();
             }
             ushort type2 = Main.tile[num2, num6 - 1].type;
             ushort type3 = Main.tile[num2 + 1, num6 - 1].type;
             if (!TileID.Sets.BasicChest[type2] && !TileID.Sets.BasicChest[type3] && type2 != 88 && type3 != 88 && !TileID.Sets.BasicChestFake[type2] && !TileID.Sets.BasicChestFake[type3] && type2 != 470 && type3 != 470 && type2 != 475 && type3 != 475 && !SolidTileAllowBottomSlope(num2, num6 + 2) && !SolidTileAllowBottomSlope(num2 + 1, num6 + 2))
             {
                 flag = true;
             }
         }
         else if (type == 132)
         {
             flag = false;
             num6 = Main.tile[i, j].frameY / 18 * -1;
             num6 += j;
             num = 0;
             num2 = Main.tile[i, j].frameX / 18 * -1;
             while (num2 < -1)
             {
                 num2 += 2;
                 num += 36;
             }
             num2 += i;
             for (int m = num2; m < num2 + 2; m++)
             {
                 for (int n = num6; n < num6 + 2; n++)
                 {
                     if (Main.tile[m, n] == null)
                     {
                         Main.tile[m, n] = new Tile();
                     }
                     if (!Main.tile[m, n].active() || Main.tile[m, n].type != type || Main.tile[m, n].frameX != (m - num2) * 18 + num || Main.tile[m, n].frameY != (n - num6) * 18)
                     {
                         flag = true;
                     }
                 }
             }
             if (Main.tile[num2, num6 + 2] == null)
             {
                 Main.tile[num2, num6 + 2] = new Tile();
             }
             if (Main.tile[num2 + 1, num6 + 2] == null)
             {
                 Main.tile[num2 + 1, num6 + 2] = new Tile();
             }
             bool flag2 = false;
             ushort type4 = Main.tile[num2, num6 + 2].type;
             ushort type5 = Main.tile[num2 + 1, num6 + 2].type;
             if (!Main.tile[num2, num6 + 2].active() || (!Main.tileSolid[type4] && !Main.tileSolidTop[type4]) || Main.tile[num2, num6 + 2].halfBrick() || (Main.tile[num2, num6 + 2].slope() != 0 && !Main.tile[num2, num6 + 2].bottomSlope()))
             {
                 flag2 = true;
             }
             if (!Main.tile[num2 + 1, num6 + 2].active() || (!Main.tileSolid[type5] && !Main.tileSolidTop[type5]) || Main.tile[num2 + 1, num6 + 2].halfBrick() || (Main.tile[num2 + 1, num6 + 2].slope() != 0 && !Main.tile[num2 + 1, num6 + 2].bottomSlope()))
             {
                 flag2 = true;
             }
             if (flag2)
             {
                 if (Main.tile[num2, num6].wall < 1 || Main.tile[num2 + 1, num6].wall < 1 || Main.tile[num2, num6 + 1].wall < 1 || Main.tile[num2 + 1, num6 + 1].wall < 1)
                 {
                     flag = true;
                 }
                 else if (num < 72)
                 {
                     for (int num8 = num2; num8 < num2 + 2; num8++)
                     {
                         for (int num9 = num6; num9 < num6 + 2; num9++)
{
                             Main.tile[num8, num9].frameX += 72;
                         }
                     }
                 }
             }
             else if (num >= 72)
             {
                 for (int num10 = num2; num10 < num2 + 2; num10++)
                 {
                     for (int num11 = num6; num11 < num6 + 2; num11++)
                     {
                         Main.tile[num10, num11].frameX -= 72;
                     }
                 }
             }
         }
         if (!flag)
         {
             return;
         }
         destroyObject = true;
         for (int num12 = num2; num12 < num2 + 2; num12++)
         {
             for (int num13 = num6; num13 < num6 + 2; num13++)
             {
                 if (Main.tile[num12, num13].type == type && Main.tile[num12, num13].active())
                 {
                     KillTile(num12, num13);
                 }
             }
         }
         int num14 = 0;
         switch (type)
         {
         case 521:
             num14 = 4327;
             break;
         case 522:
             num14 = 4328;
             break;
         case 523:
             num14 = 4329;
             break;
         case 524:
             num14 = 4330;
             break;
         case 525:
             num14 = 4331;
             break;
         case 526:
             num14 = 4332;
             break;
         case 527:
             num14 = 4333;
             break;
         case 564:
             num14 = 4553;
             break;
         case 565:
             num14 = 4552;
             break;
         case 594:
             num14 = 4869;
             break;
         case 621:
             num14 = 3750;
             break;
         case 622:
             num14 = 5008;
             break;
         }
         if (type == 598)
         {
             num14 = 4880;
         }
         if (type == 360)
         {
             num14 = 3072;
         }
         if (type == 580)
         {
             num14 = 4846;
         }
         if (type == 620)
         {
             num14 = 4964;
         }
         if (type == 505)
         {
             num14 = 4275;
         }
         if (type == 543)
         {
             num14 = 4398;
         }
         if (type == 568)
         {
             num14 = 4655;
         }
         if (type == 569)
         {
             num14 = 4656;
         }
         if (type == 570)
         {
             num14 = 4657;
         }
         if (type >= 288 && type <= 295)
         {
             num14 = 2178 + type - 288;
         }
         if (type >= 316 && type <= 318)
         {
             num14 = 2439 + type - 316;
         }
         if (type == 85)
         {
             num14 = 321;
         }
         if (type == 94)
         {
             num14 = 352;
         }
         if (type == 95)
         {
             num14 = 344;
         }
         if (type == 96)
         {
             num14 = 345;
         }
         if (type == 97)
         {
             num14 = 346;
         }
         if (type == 98)
         {
             num14 = 347;
         }
         if (type == 99)
         {
             num14 = 348;
         }
         if (type == 335)
         {
             num14 = 2700;
         }
         if (type == 411)
         {
             num14 = 3545;
         }
         if (type == 652)
         {
             num14 = ((num7 < 3) ? 195 : ((num7 >= 6) ? 331 : 62));
         }
         if (type == 100)
         {
             switch (num5)
             {
             case 0:
                 num14 = 349;
                 break;
             case 1:
             case 2:
             case 3:
             case 4:
             case 5:
             case 6:
             case 7:
             case 8:
             case 9:
             case 10:
             case 11:
             case 12:
                 num14 = 2092 + num5 - 1;
                 break;
             default:
                 if (num5 >= 13 && num5 <= 16)
                 {
                     num14 = 2149 + num5 - 13;
                     break;
                 }
                 switch (num5)
                 {
                 case 17:
                     num14 = 2227;
                     break;
                 case 18:
                     num14 = 2522;
                     break;
                 case 19:
                     num14 = 2541;
                     break;
                 case 20:
                     num14 = 2555;
                     break;
                 case 21:
                     num14 = 2570;
                     break;
                 case 22:
                     num14 = 2664;
                     break;
                 case 23:
                     num14 = 2665;
                     break;
                 case 24:
                     num14 = 2666;
                     break;
                 case 25:
                     num14 = 2667;
                     break;
                 case 26:
                     num14 = 2668;
                     break;
                 case 27:
                     num14 = 2825;
                     break;
                 case 28:
                     num14 = 3168;
                     break;
                 case 29:
                     num14 = 3170;
                     break;
                 case 30:
                     num14 = 3169;
                     break;
                 case 31:
                     num14 = 3893;
                     break;
                 case 32:
                     num14 = 3935;
                     break;
                 case 33:
                     num14 = 3961;
                     break;
                 case 34:
                     num14 = 4149;
                     break;
                 case 35:
                     num14 = 4170;
                     break;
                 case 36:
                     num14 = 4191;
                     break;
                 case 37:
                     num14 = 4212;
                     break;
                 case 38:
                     num14 = 4302;
                     break;
                 case 39:
                     num14 = 4570;
                     break;
                 case 40:
                     num14 = 5152;
                     break;
                 case 41:
                     num14 = 5173;
                     break;
                 case 42:
                     num14 = 5194;
                     break;
                 }
                 break;
             }
         }
         if (type == 173)
         {
             num14 = 714;
         }
         if (type == 125)
         {
             num14 = 487;
         }
         if (type == 287)
         {
             num14 = 2177;
         }
         if (type == 126)
         {
             num14 = 488;
         }
         if (type == 132)
         {
             num14 = 513;
         }
         if (type == 142)
         {
             num14 = 581;
         }
         if (type == 143)
         {
             num14 = 582;
         }
         if (type == 282)
         {
             num14 = 250;
         }
         if (type == 319)
         {
             num14 = 2490;
         }
         if (type == 490)
         {
             num14 = 4075;
         }
         if (type == 172)
         {
             num14 = 2827 + num5;
             switch (num5)
             {
             case 29:
                 num14 = 3147;
                 break;
             case 30:
                 num14 = 3149;
                 break;
             case 31:
                 num14 = 3148;
                 break;
             case 32:
                 num14 = 3896;
                 break;
             case 33:
                 num14 = 3946;
                 break;
             case 34:
                 num14 = 3972;
                 break;
             case 35:
                 num14 = 4160;
                 break;
             case 36:
                 num14 = 4181;
                 break;
             case 37:
                 num14 = 4202;
                 break;
             case 38:
                 num14 = 4223;
                 break;
             case 39:
                 num14 = 4312;
                 break;
             case 40:
                 num14 = 4581;
                 break;
             case 41:
                 num14 = 5163;
                 break;
             case 42:
                 num14 = 5184;
                 break;
             case 43:
                 num14 = 5205;
                 break;
             }
         }
         if (num14 != 0)
         {
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num14);
         }
         if (!gen && Main.netMode != 1)
         {
             switch (type)
             {
             case 138:
                 Projectile.NewProjectile(GetProjectileSource_TileBreak(num2, num6), (float)(num2 * 16) + 15.5f, num6 * 16 + 16, 0f, 0f, 99, 70, 10f, Main.myPlayer);
                 break;
             case 484:
                 Projectile.NewProjectile(GetProjectileSource_TileBreak(num2, num6), (float)(num2 * 16) + 15.5f, num6 * 16 + 16, 0f, 0f, 727, 35, 10f, Main.myPlayer);
                 break;
             case 654:
                 Projectile.NewProjectile(GetProjectileSource_TileBreak(num2, num6), num2 * 16 + 8, num6 * 16 + 8, 0f, 0f, 1002, 400, 10f, Main.myPlayer);
                 break;
             case 664:
                 Projectile.NewProjectile(GetProjectileSource_TileBreak(num2, num6), (float)(num2 * 16) + 15.5f, num6 * 16 + 16, 0f, 0f, 1013, 70, 10f, Main.myPlayer);
                 break;
             case 665:
                 Projectile.NewProjectile(GetProjectileSource_TileBreak(num2, num6), (float)(num2 * 16) + 15.5f, num6 * 16 + 16, 0f, 0f, 1014, 70, 10f, Main.myPlayer);
                 break;
             }
         }
         destroyObject = false;
         for (int num15 = num2 - 1; num15 < num2 + 3; num15++)
         {
             for (int num16 = num6 - 1; num16 < num6 + 3; num16++)
             {
                 TileFrame(num15, num16);
             }
         }
     }
References Tile.active(), TileID.Sets.BasicChest, TileID.Sets.BasicChestFake, Tile.bottomSlope(), TileID.Sets.Boulders, Tile.frameX, Tile.frameY, Framing.GetTileSafely(), Tile.halfBrick(), Main.myPlayer, Main.netMode, Item.NewItem(), Projectile.NewProjectile(), Tile.slope(), Main.tile, Main.tileSolid, Main.tileSolidTop, Main.tileTable, Tile.type, and Tile.wall.