Terraria: WorldGen.Check3x3
Check3x3()
static void WorldGen.Check3x3 (int i, int j, int type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         int num = i;
         int num2 = j;
         num = Main.tile[i, j].frameX / 18;
         int num3 = 0;
         while (num >= 3)
         {
             num3++;
             num -= 3;
         }
         int num4 = i - num;
         int num5 = 54 * num3;
         int num6 = Main.tile[i, j].frameY / 54;
         int num7 = Main.tile[i, j].frameY % 54 / 18;
         if (num >= 3)
         {
             num -= 3;
         }
         num = i - num;
         num2 -= num7;
         for (int k = num; k < num + 3; k++)
         {
             for (int l = num2; l < num2 + 3; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || Main.tile[k, l].frameX != (k - num4) * 18 + num5 || Main.tile[k, l].frameY != (l - num2) * 18 + num6 * 54)
                 {
                     flag = true;
                 }
             }
         }
         if (type == 106 || type == 212 || type == 219 || type == 220 || type == 228 || type == 231 || type == 243 || type == 247 || type == 283 || (type >= 300 && type <= 308) || type == 354 || type == 355 || type == 499 || type == 406 || type == 412 || type == 452 || type == 455 || type == 491 || type == 642)
         {
             for (int m = num; m < num + 3; m++)
             {
                 if (Main.tile[m, num2 + 3] == null)
                 {
                     Main.tile[m, num2 + 3] = new Tile();
                 }
                 if (!SolidTileAllowBottomSlope(m, num2 + 3))
                 {
                     flag = true;
                     break;
                 }
             }
         }
         else
         {
             if (Main.tile[num + 1, num2 - 1] == null)
             {
                 Main.tile[num + 1, num2 - 1] = new Tile();
             }
             if (!Main.tile[num + 1, num2 - 1].nactive() || !Main.tileSolid[Main.tile[num + 1, num2 - 1].type] || Main.tileSolidTop[Main.tile[num + 1, num2 - 1].type])
             {
                 flag = true;
             }
         }
         if (!flag)
         {
             return;
         }
         destroyObject = true;
         for (int n = num; n < num + 3; n++)
         {
             for (int num8 = num2; num8 < num2 + 3; num8++)
             {
                 if (Main.tile[n, num8].type == type && Main.tile[n, num8].active())
                 {
                     KillTile(n, num8);
                 }
             }
         }
         switch (type)
         {
         case 106:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 363);
             break;
         case 243:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1430);
             break;
         case 212:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 951);
             break;
         case 219:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 997);
             break;
         case 642:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5296);
             break;
         case 220:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 998);
             break;
         case 228:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1120);
             break;
         case 247:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1551);
             break;
         case 283:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2172);
             break;
         case 300:
         case 301:
         case 302:
         case 303:
         case 304:
         case 305:
         case 306:
             Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2192 + type - 300);
             break;
         default:
             switch (type)
             {
             case 307:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2203);
                 break;
             case 308:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2204);
                 break;
             case 406:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3365);
                 break;
             case 452:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3742);
                 break;
             case 354:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2999);
                 break;
             case 355:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3000);
                 break;
             case 499:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4142);
                 break;
             case 412:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3549);
                 break;
             case 455:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3747);
                 break;
             case 491:
                 Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4076);
                 break;
             case 231:
             {
                 int num9 = (i + 1) * 16 + 8;
                 int num10 = j * 16;
                 Gore.NewGore(new Vector2(num9, num10), default(Vector2), 300);
                 Gore.NewGore(new Vector2(num9, num10 + 8), default(Vector2), 301);
                 Gore.NewGore(new Vector2(num9, num10 + 16), default(Vector2), 302);
                 float num11 = i * 16;
                 float num12 = j * 16;
                 float num13 = -1f;
                 int plr = 0;
                 for (int num14 = 0; num14 < 255; num14++)
                 {
                     if (Main.player[num14].active && !Main.player[num14].dead)
                     {
                         float num15 = Math.Abs(Main.player[num14].position.X - num11) + Math.Abs(Main.player[num14].position.Y - num12);
                         if (num15 < num13 || num13 == -1f)
{
                             plr = num14;
                             num13 = num15;
                         }
                     }
                 }
                 if (num13 < 4800f && !Main.gameMenu)
                 {
                     NPC.SpawnOnPlayer(plr, 222);
                 }
                 break;
             }
             }
             break;
         }
         destroyObject = false;
         for (int num16 = num - 1; num16 < num + 4; num16++)
         {
             for (int num17 = num2 - 1; num17 < num2 + 4; num17++)
             {
                 TileFrame(num16, num17);
             }
         }
     }
References Entity.active, Tile.active(), Player.dead, Tile.frameX, Tile.frameY, Main.gameMenu, Tile.nactive(), Gore.NewGore(), Item.NewItem(), Main.player, Entity.position, NPC.SpawnOnPlayer(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.