Terraria: WorldGen.EveryTileFrame
EveryTileFrame()
static void WorldGen.EveryTileFrame () inline static
     {
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         noLiquidCheck = true;
         noTileActions = true;
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             float num = (float)i / (float)Main.maxTilesX;
             Main.statusText = Lang.gen[55].Value + " " + (int)(num * 100f + 1f) + "%";
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 if (Main.tile[i, j].active())
                 {
                     TileFrame(i, j, resetFrame: true);
                 }
                 if (Main.tile[i, j].wall > 0)
                 {
                     Framing.WallFrame(i, j, resetFrame: true);
                 }
             }
         }
         noLiquidCheck = false;
         noTileActions = false;
         _ = stopwatch.ElapsedMilliseconds;
     }
References Tile.active(), Lang.gen, Main.maxTilesX, Main.maxTilesY, Main.statusText, Main.tile, LocalizedText.Value, Tile.wall, and Framing.WallFrame().
Referenced by Main.Initialize_AlmostEverything().