Terraria: WorldGen.CheckCatTail
CheckCatTail()
static void WorldGen.CheckCatTail (int x, int j) inline static
     {
         if (Main.tile[x, j] == null)
         {
             return;
         }
         int num = j;
         bool flag = false;
         int num2 = num;
         while ((!Main.tile[x, num2].active() || !Main.tileSolid[Main.tile[x, num2].type] || Main.tileSolidTop[Main.tile[x, num2].type]) && num2 < Main.maxTilesY - 50)
         {
             if (Main.tile[x, num2].active() && Main.tile[x, num2].type != 519)
             {
                 flag = true;
             }
             if (!Main.tile[x, num2].active())
             {
                 break;
             }
             num2++;
             if (Main.tile[x, num2] == null)
             {
                 return;
             }
         }
         num = num2 - 1;
         if (Main.tile[x, num] == null)
         {
             return;
         }
         while (Main.tile[x, num] != null && Main.tile[x, num].liquid > 0 && num > 50)
         {
             if ((Main.tile[x, num].active() && Main.tile[x, num].type != 519) || Main.tile[x, num].liquidType() != 0)
             {
                 flag = true;
             }
             num--;
             if (Main.tile[x, num] == null)
             {
                 return;
             }
         }
         num++;
         if (Main.tile[x, num] == null)
         {
             return;
         }
         int num3 = num;
         int num4 = catTailDistance;
         if (num2 - num3 > num4)
         {
             flag = true;
         }
         int type = Main.tile[x, num2].type;
         int num5 = -1;
         switch (type)
         {
         case 2:
         case 477:
             num5 = 0;
             break;
         case 53:
             num5 = 18;
             break;
         case 199:
         case 234:
         case 662:
             num5 = 54;
             break;
         case 23:
         case 112:
         case 661:
             num5 = 72;
             break;
         case 70:
             num5 = 90;
             break;
         }
         if (!Main.tile[x, num2].nactive())
         {
             flag = true;
         }
         if (num5 < 0)
         {
             flag = true;
         }
         num = num2 - 1;
         if (Main.tile[x, num] != null && !Main.tile[x, num].active())
         {
             for (int num6 = num; num6 >= num3; num6--)
             {
                 if (Main.tile[x, num6] == null)
                 {
                     return;
                 }
                 if (Main.tile[x, num6].active() && Main.tile[x, num6].type == 519)
                 {
                     num = num6;
                     break;
                 }
             }
         }
         while (Main.tile[x, num] != null && Main.tile[x, num].active() && Main.tile[x, num].type == 519)
         {
             num--;
         }
         num++;
         if (Main.tile[x, num2 - 1] != null && Main.tile[x, num2 - 1].liquid < 127 && genRand.Next(4) == 0)
         {
             flag = true;
         }
         if (Main.tile[x, num] != null && Main.tile[x, num].frameX >= 180 && Main.tile[x, num].liquid > 127 && genRand.Next(4) == 0)
         {
             flag = true;
         }
         if (Main.tile[x, num] != null && Main.tile[x, num2 - 1] != null && Main.tile[x, num].frameX > 18)
         {
             if (Main.tile[x, num2 - 1].frameX < 36 || Main.tile[x, num2 - 1].frameX > 72)
             {
                 flag = true;
             }
             else if (Main.tile[x, num].frameX < 90)
             {
                 flag = true;
             }
             else if (Main.tile[x, num].frameX >= 108 && Main.tile[x, num].frameX <= 162)
             {
                 Main.tile[x, num].frameX = 90;
             }
         }
         if (num2 > num + 4 && Main.tile[x, num + 4] != null && Main.tile[x, num + 3] != null && Main.tile[x, num + 4].liquid == 0 && Main.tile[x, num + 3].type == 519)
         {
             flag = true;
         }
         if (flag)
         {
             int num7 = num3;
             if (num < num3)
             {
                 num7 = num;
             }
             num7 -= 4;
             for (int i = num7; i <= num2; i++)
             {
                 if (Main.tile[x, i] != null && Main.tile[x, i].active() && Main.tile[x, i].type == 519)
                 {
                     KillTile(x, i);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, x, i);
                     }
                     SquareTileFrame(x, i);
                 }
             }
         }
         else
         {
             if (num5 == Main.tile[x, num].frameY)
             {
                 return;
             }
             for (int k = num; k < num2; k++)
             {
                 if (Main.tile[x, k] != null && Main.tile[x, k].active() && Main.tile[x, k].type == 519)
                 {
                     Main.tile[x, k].frameY = (short)num5;
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, x, num);
                     }
                 }
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.liquid, Tile.liquidType(), Main.maxTilesY, Tile.nactive(), Main.netMode, NetMessage.SendData(), NetMessage.SendTileSquare(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.