Terraria: WorldGen.CheckTorch
CheckTorch()
static void WorldGen.CheckTorch (int x, int y) inline static
     {
         for (int i = x - 1; i <= x + 1; i++)
         {
             for (int j = y - 1; j <= y + 1; j++)
             {
                 if (Main.tile[i, j] == null)
                 {
                     return;
                 }
             }
         }
         Tile tile = Main.tile[x, y];
         Tile tile2 = Main.tile[x, y - 1];
         Tile tile3 = Main.tile[x, y + 1];
         Tile tile4 = Main.tile[x - 1, y];
         Tile tile5 = Main.tile[x + 1, y];
         Tile tile6 = Main.tile[x - 1, y + 1];
         Tile tile7 = Main.tile[x + 1, y + 1];
         Tile tile8 = Main.tile[x - 1, y - 1];
         Tile tile9 = Main.tile[x + 1, y - 1];
         short num = 0;
         if (tile.frameX >= 66)
         {
             num = 66;
         }
         int num2 = -1;
         int num3 = -1;
         int num4 = -1;
         int tree = -1;
         int tree2 = -1;
         int tree3 = -1;
         int tree4 = -1;
         if (tile2 != null && tile2.active() && !tile2.bottomSlope())
         {
             _ = tile2.type;
         }
         if (tile3 != null && tile3.active() && ((TileID.Sets.Platforms[tile3.type] && TopEdgeCanBeAttachedTo(x, y + 1)) || (!tile3.halfBrick() && !tile3.topSlope())))
         {
             num2 = tile3.type;
         }
         if (tile4 != null && tile4.active() && (tile4.slope() == 0 || tile4.slope() % 2 != 1))
         {
             num3 = tile4.type;
         }
         if (tile5 != null && tile5.active() && (tile5.slope() == 0 || tile5.slope() % 2 != 0))
         {
             num4 = tile5.type;
         }
         if (tile6 != null && tile6.active())
         {
             tree = tile6.type;
         }
         if (tile7 != null && tile7.active())
         {
             tree2 = tile7.type;
         }
         if (tile8 != null && tile8.active())
         {
             tree3 = tile8.type;
         }
         if (tile9 != null && tile9.active())
         {
             tree4 = tile9.type;
         }
         if (num2 >= 0 && Main.tileSolid[num2] && (!Main.tileNoAttach[num2] || TileID.Sets.Platforms[num2]))
         {
             tile.frameX = num;
         }
         else if ((num3 >= 0 && Main.tileSolid[num3] && !Main.tileNoAttach[num3]) || (num3 >= 0 && TileID.Sets.IsBeam[num3]) || (IsTreeType(num3) && IsTreeType(tree3) && IsTreeType(tree)))
         {
             tile.frameX = (short)(22 + num);
         }
         else if ((num4 >= 0 && Main.tileSolid[num4] && !Main.tileNoAttach[num4]) || (num4 >= 0 && TileID.Sets.IsBeam[num4]) || (IsTreeType(num4) && IsTreeType(tree4) && IsTreeType(tree2)))
         {
             tile.frameX = (short)(44 + num);
         }
         else if (tile.wall > 0)
         {
             tile.frameX = num;
         }
         else
         {
             KillTile(x, y);
         }
     }
References Tile.active(), Tile.bottomSlope(), Tile.frameX, Tile.halfBrick(), TileID.Sets.IsBeam, TileID.Sets.Platforms, Tile.slope(), Main.tile, Main.tileNoAttach, Main.tileSolid, Tile.topSlope(), Tile.type, and Tile.wall.