Terraria: WorldGen.paintCoatTile
paintCoatTile()
static bool WorldGen.paintCoatTile (int x, int y, byte paintCoatId, bool broadcast = false) inline static
     {
         Tile tile = Main.tile[x, y];
         if (tile == null || !tile.active())
         {
             return false;
         }
         List<Color> oldColors = coatingColors(tile, block: true);
         switch (paintCoatId)
         {
         default:
             return false;
         case 0:
             if (!tile.fullbrightBlock() && !tile.invisibleBlock())
             {
                 return false;
             }
             tile.fullbrightBlock(fullbrightBlock: false);
             tile.invisibleBlock(invisibleBlock: false);
             SquareTileFrame(x, y, resetFrame: false);
             break;
         case 1:
             if (tile.fullbrightBlock())
             {
                 return false;
             }
             tile.fullbrightBlock(fullbrightBlock: true);
             break;
         case 2:
             if (tile.invisibleBlock())
             {
                 return false;
             }
             tile.invisibleBlock(invisibleBlock: true);
             SquareTileFrame(x, y, resetFrame: false);
             break;
         }
         if (broadcast)
         {
             NetMessage.SendData(63, -1, -1, null, x, y, (int)paintCoatId, 1f);
         }
         paintCoatEffect(x, y, paintCoatId, oldColors);
         return true;
     }
References Tile.active(), Tile.fullbrightBlock(), Tile.invisibleBlock(), NetMessage.SendData(), and Main.tile.
Referenced by Player.ApplyCoating(), MessageBuffer.GetData(), and Player.PlaceThing_PaintScrapper_TryScrapping().