Terraria: WorldGen.FinishRemixWorld
FinishRemixWorld()
static void WorldGen.FinishRemixWorld () inline static private
     {
         for (int i = 25; i < Main.maxTilesX - 25; i++)
         {
             for (int j = 25; j < Main.maxTilesY - 25; j++)
             {
                 int conversionType = 1;
                 if (crimson)
                 {
                     conversionType = 4;
                 }
                 if (notTheBees && (double)j < Main.worldSurface)
                 {
                     if (Main.tile[i, j].honey())
                     {
                         if (Main.tileLavaDeath[Main.tile[i, j].type])
{
                             KillTile(i, j);
                         }
                         Main.tile[i, j].lava(lava: true);
                     }
                     if (Main.tile[i, j].type == 375)
                     {
                         Main.tile[i, j].type = 374;
                     }
                     if (Main.tile[i, j].type == 230 || Main.tile[i, j].type == 229 || Main.tile[i, j].type == 659 || Main.tile[i, j].type == 56)
                     {
                         KillTile(i, j);
                     }
                     if (Main.tile[i, j].type == 82 || Main.tile[i, j].type == 83 || Main.tile[i, j].type == 84)
                     {
                         TileFrame(i, j);
                     }
                 }
                 if ((double)j < Main.worldSurface + (double)genRand.Next(3))
                 {
                     if (drunkWorldGen)
                     {
                         if (GenVars.crimsonLeft)
{
                             if (i < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                                 Convert(i, j, 4, 1);
                             }
                             else
{
                                 Convert(i, j, 1, 1);
                             }
                         }
                         else if (i < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                             Convert(i, j, 1, 1);
                         }
                         else
{
                             Convert(i, j, 4, 1);
                         }
                     }
                     else
                     {
                         Convert(i, j, conversionType, 1);
                     }
                 }
                 if ((double)j < Main.worldSurface - (double)genRand.Next(19, 22) && (Main.tile[i, j].wall == 178 || Main.tile[i, j].wall == 180))
                 {
                     Main.tile[i, j].wall = 0;
                 }
                 if (Main.tile[i, j].active() && Main.tile[i, j].type == 56)
                 {
                     KillTile(i, j);
                 }
                 if (Main.tile[i, j].type == 189 || Main.tile[i, j].type == 196 || Main.tile[i, j].type == 202)
                 {
                     if (drunkWorldGen)
                     {
                         if (GenVars.crimsonLeft)
{
                             if (i < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                                 Main.tile[i, j].type = 195;
                             }
                             else
{
                                 Main.tile[i, j].type = 474;
                             }
                         }
                         else if (i < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                             Main.tile[i, j].type = 474;
                         }
                         else
{
                             Main.tile[i, j].type = 195;
                         }
                     }
                     else if (crimson)
                     {
                         Main.tile[i, j].type = 195;
                     }
                     else
                     {
                         Main.tile[i, j].type = 474;
                     }
                 }
                 if (Main.tile[i, j].wall == 73 || Main.tile[i, j].wall == 82)
                 {
                     if (drunkWorldGen)
                     {
                         if (GenVars.crimsonLeft)
{
                             if (i < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                                 Main.tile[i, j].wall = 77;
                             }
                             else
{
                                 Main.tile[i, j].wall = 233;
                             }
                         }
                         else if (i < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                             Main.tile[i, j].wall = 233;
                         }
                         else
{
                             Main.tile[i, j].wall = 77;
                         }
                     }
                     else if (crimson)
                     {
                         Main.tile[i, j].wall = 77;
                     }
                     else
                     {
                         Main.tile[i, j].wall = 233;
                     }
                 }
                 if ((double)j > Main.rockLayer && j < Main.maxTilesY - 350 && Main.tile[i, j].type == 0 && Main.tile[i, j].active() && (!Main.tile[i - 1, j - 1].active() || !SolidTile(i, j - 1) || !Main.tile[i + 1, j - 1].active() || !Main.tile[i - 1, j].active() || !Main.tile[i + 1, j].active() || !Main.tile[i - 1, j + 1].active() || !Main.tile[i, j + 1].active() || !Main.tile[i + 1, j + 1].active()))
                 {
                     Main.tile[i, j].type = 2;
                 }
             }
         }
         Liquid.QuickWater(-2);
         int num = (int)((double)Main.maxTilesX * 0.38);
         int num2 = (int)((double)Main.maxTilesX * 0.62);
         _ = Main.maxTilesY;
         int num3 = Main.maxTilesY - 135;
         _ = Main.maxTilesY;
         for (int k = num; k < num2 + 15; k++)
         {
             for (int l = Main.maxTilesY - 200; l < num3 + 10; l++)
             {
                 Main.tile[k, l].liquid = 0;
                 if (Main.tile[k, l].type == 58)
                 {
                     Main.tile[k, l].type = 57;
                 }
             }
         }
         AddTrees(undergroundOnly: true);
         for (int m = 0; m < Main.maxTilesX; m++)
         {
             byte color = 22;
             byte color2 = 22;
             if (drunkWorldGen)
             {
                 if ((GenVars.crimsonLeft && m < Main.maxTilesX / 2) || (!GenVars.crimsonLeft && m > Main.maxTilesX / 2))
                 {
                     color2 = 13;
                     color = 13;
                 }
             }
             else if (crimson)
             {
                 color2 = 13;
                 color = 13;
             }
             for (int n = 0; n < Main.maxTilesY; n++)
             {
                 if (Main.tile[m, n].active() && (Main.tileDungeon[Main.tile[m, n].type] || TileID.Sets.CrackedBricks[Main.tile[m, n].type]))
                 {
                     Main.tile[m, n].color(color);
                 }
                 if (Main.wallDungeon[Main.tile[m, n].wall])
                 {
                     Main.tile[m, n].wallColor(25);
                     if (Main.tile[m, n].type == 19 && Main.tile[m, n].frameY != 180)
                     {
                         Main.tile[m, n].color(color);
                     }
                 }
                 if (Main.tile[m, n].active())
                 {
                     bool flag = false;
                     if (Main.tenthAnniversaryWorld)
                     {
                         if (Main.tile[m, n].type == 191)
{
                             flag = true;
                         }
                         if (Main.tile[m, n].active() && Main.tile[m, n].type == 151)
{
                             Main.tile[m, n].color(color);
                         }
                     }
                     if (Main.tile[m, n].type == 226)
                     {
                         flag = true;
                     }
                     if (Main.tile[m, n].type == 137)
                     {
                         int num4 = Main.tile[m, n].frameY / 18;
                         if (num4 >= 1 && num4 <= 4)
{
                             flag = true;
                         }
                     }
                     if (flag)
                     {
                         Main.tile[m, n].color(color2);
                     }
                 }
                 if (Main.tile[m, n].wall == 244)
                 {
                     Main.tile[m, n].wallColor(25);
                 }
                 if (Main.tile[m, n].wall == 34)
                 {
                     Main.tile[m, n].wallColor(25);
                 }
                 if (Main.tile[m, n].wall == 87)
                 {
                     Main.tile[m, n].wallColor(25);
                     Main.tile[m, n].color(color2);
                 }
             }
         }
         double num5 = (double)Main.maxTilesX / 4200.0;
         num5 *= (double)genRand.Next(2, 5);
         for (int num6 = 0; (double)num6 < num5; num6++)
         {
             int num7 = genRand.Next((int)((double)Main.maxTilesX * 0.39), (int)((double)Main.maxTilesX * 0.61));
             int num8 = genRand.Next(10, 31);
             for (int num9 = num7 - num8; num9 <= num7 + num8; num9++)
             {
                 for (int num10 = Main.maxTilesY - 250; num10 < Main.maxTilesY - 25; num10++)
                 {
                     if (Main.tile[num9, num10].type == 637)
                     {
                         Main.tile[num9, num10].frameX = (short)(18 * Main.rand.Next(6, 11));
                     }
                 }
             }
         }
         if (notTheBees)
         {
             for (int num11 = 3; num11 < Main.maxTilesX - 3; num11++)
             {
                 bool flag2 = true;
                 for (int num12 = 0; (double)num12 < Main.worldSurface; num12++)
                 {
                     if (flag2)
                     {
                         if (Main.tile[num11, num12].wall == 86)
{
                             Main.tile[num11, num12].wall = 0;
                         }
                         if (Main.tile[num11, num12].active())
{
                             flag2 = false;
                         }
                     }
                     else if (Main.tile[num11, num12].wall == 0 && Main.tile[num11, num12 + 1].wall == 0 && Main.tile[num11, num12 + 2].wall == 0 && Main.tile[num11, num12 + 3].wall == 0 && Main.tile[num11, num12 + 4].wall == 0 && Main.tile[num11 - 1, num12].wall == 0 && Main.tile[num11 + 1, num12].wall == 0 && Main.tile[num11 - 2, num12].wall == 0 && Main.tile[num11 + 2, num12].wall == 0 && !Main.tile[num11, num12].active() && !Main.tile[num11, num12 + 1].active() && !Main.tile[num11, num12 + 2].active() && !Main.tile[num11, num12 + 3].active())
                     {
                         flag2 = true;
                     }
                 }
             }
         }
         Liquid.QuickWater(-2);
         for (int num13 = 0; num13 < Main.maxTilesX; num13++)
         {
             for (int num14 = 0; num14 < Main.maxTilesY; num14++)
             {
                 if (Main.tile[num13, num14].type == 518)
                 {
                     CheckLilyPad(num13, num14);
                 }
             }
         }
     }
References Tile.active(), Tile.color(), TileID.Sets.CrackedBricks, GenVars.crimsonLeft, Tile.frameX, Tile.frameY, Tile.honey(), Tile.lava(), Liquid, Tile.liquid, Main.maxTilesX, Main.maxTilesY, UnifiedRandom.Next(), Main.rand, Main.rockLayer, SolidTile, Main.tenthAnniversaryWorld, Main.tile, Main.tileDungeon, Main.tileLavaDeath, Tile.type, Tile.wall, Tile.wallColor(), Main.wallDungeon, and Main.worldSurface.