Terraria: WorldGen.KillTile
KillTile()
static void WorldGen.KillTile (int i, int j, bool fail = false, bool effectOnly = false, bool noItem = false) inline static
     {
         if (i < 0 || j < 0 || i >= Main.maxTilesX || j >= Main.maxTilesY)
         {
             return;
         }
         Tile tile = Main.tile[i, j];
         if (tile == null)
         {
             tile = new Tile();
             Main.tile[i, j] = tile;
         }
         if (!tile.active())
         {
             return;
         }
         if (j >= 1 && Main.tile[i, j - 1] == null)
         {
             Main.tile[i, j - 1] = new Tile();
         }
         int num = CheckTileBreakability(i, j);
         if (num == 1)
         {
             fail = true;
         }
         if (num == 2)
         {
             return;
         }
         if (gen)
         {
             noItem = true;
         }
         if (!effectOnly && !stopDrops)
         {
             if (!noItem && FixExploitManEaters.SpotProtected(i, j))
             {
                 return;
             }
             if (!Main.dedServ && !gen && !Main.gameMenu)
             {
                 KillTile_PlaySounds(i, j, fail, tile);
             }
         }
         if (tile.type == 128 || tile.type == 269)
         {
             int num2 = i;
             int num3 = tile.frameX;
             int num4;
             for (num4 = tile.frameX; num4 >= 100; num4 -= 100)
             {
             }
             while (num4 >= 36)
             {
                 num4 -= 36;
             }
             if (num4 == 18)
             {
                 num3 = Main.tile[i - 1, j].frameX;
                 num2--;
             }
             if (num3 >= 100)
             {
                 int num5 = 0;
                 while (num3 >= 100)
                 {
                     num3 -= 100;
                     num5++;
                 }
                 int num6 = Main.tile[num2, j].frameY / 18;
                 if (num6 == 0)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, Item.headType[num5]);
                 }
                 if (num6 == 1)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, Item.bodyType[num5]);
                 }
                 if (num6 == 2)
                 {
                     Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, Item.legType[num5]);
                 }
                 for (num3 = Main.tile[num2, j].frameX; num3 >= 100; num3 -= 100)
                 {
                 }
                 Main.tile[num2, j].frameX = (short)num3;
             }
         }
         if (tile.type == 334)
         {
             int num7 = i;
             int frameX = tile.frameX;
             int num8 = tile.frameX;
             int num9 = 0;
             while (num8 >= 5000)
             {
                 num8 -= 5000;
                 num9++;
             }
             if (num9 != 0)
             {
                 num8 = (num9 - 1) * 18;
             }
             num8 %= 54;
             if (num8 == 18)
             {
                 frameX = Main.tile[i - 1, j].frameX;
                 num7--;
             }
             if (num8 == 36)
             {
                 frameX = Main.tile[i - 2, j].frameX;
                 num7 -= 2;
             }
             if (frameX >= 5000)
             {
                 int num10 = frameX % 5000;
                 num10 -= 100;
                 int frameX2 = Main.tile[num7 + 1, j].frameX;
                 frameX2 = ((frameX2 < 25000) ? (frameX2 - 10000) : (frameX2 - 25000));
                 if (Main.netMode != 1)
                 {
                     Item item = new Item();
                     item.netDefaults(num10);
                     item.Prefix(frameX2);
                     int num11 = Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, num10, 1, noBroadcast: true);
                     item.position = Main.item[num11].position;
                     Main.item[num11] = item;
                     NetMessage.SendData(21, -1, -1, null, num11);
                 }
                 frameX = Main.tile[num7, j].frameX;
                 int num12 = 0;
                 while (frameX >= 5000)
                 {
                     frameX -= 5000;
                     num12++;
                 }
                 if (num12 != 0)
                 {
                     frameX = (num12 - 1) * 18;
                 }
                 Main.tile[num7, j].frameX = (short)frameX;
                 Main.tile[num7 + 1, j].frameX = (short)(frameX + 18);
             }
         }
         if (tile.type == 395)
         {
             int num13 = TEItemFrame.Find(i - tile.frameX % 36 / 18, j - tile.frameY % 36 / 18);
             if (num13 != -1 && ((TEItemFrame)TileEntity.ByID[num13]).item.stack > 0)
             {
                 ((TEItemFrame)TileEntity.ByID[num13]).DropItem();
                 if (Main.netMode != 2)
                 {
                     Main.LocalPlayer.InterruptItemUsageIfOverTile(395);
                 }
                 return;
             }
         }
         if (tile.type == 471)
         {
             int num14 = TEWeaponsRack.Find(i - tile.frameX % 54 / 18, j - tile.frameY % 54 / 18);
             if (num14 != -1 && ((TEWeaponsRack)TileEntity.ByID[num14]).item.stack > 0)
             {
                 ((TEWeaponsRack)TileEntity.ByID[num14]).DropItem();
                 if (Main.netMode != 2)
                 {
                     Main.LocalPlayer.InterruptItemUsageIfOverTile(471);
                 }
                 return;
             }
         }
         if (tile.type == 520)
         {
             int num15 = TEFoodPlatter.Find(i, j);
             if (num15 != -1 && ((TEFoodPlatter)TileEntity.ByID[num15]).item.stack > 0)
             {
                 ((TEFoodPlatter)TileEntity.ByID[num15]).DropItem();
                 if (Main.netMode != 2)
                 {
                     Main.LocalPlayer.InterruptItemUsageIfOverTile(520);
                 }
                 return;
             }
         }
         if ((tile.type == 470 && (CheckTileBreakability2_ShouldTileSurvive(i, j) || fail)) || (tile.type == 475 && (CheckTileBreakability2_ShouldTileSurvive(i, j) || fail)))
         {
             return;
         }
         int num16 = KillTile_GetTileDustAmount(fail, tile);
         for (int k = 0; k < num16; k++)
         {
             KillTile_MakeTileDust(i, j, tile);
         }
         if (effectOnly)
         {
             return;
         }
         AttemptFossilShattering(i, j, tile, fail);
         if (fail)
         {
             if (Main.netMode != 1 && TileID.Sets.IsShakeable[tile.type])
             {
                 ShakeTree(i, j);
             }
             if (tile.type == 2 || tile.type == 23 || tile.type == 109 || tile.type == 199 || tile.type == 477 || tile.type == 492)
             {
                 tile.type = 0;
             }
             if (tile.type == 633)
             {
                 tile.type = 57;
             }
             if (tile.type == 60 || tile.type == 661 || tile.type == 662 || tile.type == 70)
             {
                 tile.type = 59;
             }
             if (Main.tileMoss[tile.type])
             {
                 tile.type = 1;
             }
             if (TileID.Sets.tileMossBrick[tile.type])
             {
                 tile.type = 38;
             }
             SquareTileFrame(i, j);
             return;
         }
         if (Main.getGoodWorld && Main.netMode != 1 && tile.type == 57)
         {
             for (int l = 0; l < 8; l++)
             {
                 int maxValue = 2;
                 int num17 = i;
                 int num18 = j;
                 switch (l)
                 {
                 case 0:
                     num17--;
                     break;
                 case 1:
                     num17++;
                     break;
                 case 2:
                     num18--;
                     break;
                 case 3:
                     num18++;
                     break;
                 case 4:
                     num17--;
                     num18--;
                     break;
                 case 5:
                     num17++;
                     num18--;
                     break;
                 case 6:
                     num17--;
                     num18++;
                     break;
                 case 7:
                     num17++;
                     num18++;
                     break;
                 }
                 Tile tile2 = Main.tile[num17, num18];
                 if (tile2.active() && genRand.Next(maxValue) == 0 && tile2.type == 57 && !SolidTile(num17, num18 + 1))
                 {
                     KillTile(num17, num18, fail: false, effectOnly: false, noItem: true);
                     if (Main.netMode == 2)
                     {
                         NetMessage.TrySendData(17, -1, -1, null, 20, num17, num18);
                     }
                     int num19 = Projectile.NewProjectile(GetProjectileSource_TileBreak(num17, num18), num17 * 16 + 8, num18 * 16 + 8, 0f, 0.41f, 40, 15, 0f, Main.myPlayer);
                     Main.projectile[num19].netUpdate = true;
                 }
             }
         }
         if (Main.netMode != 1 && tile.type >= 481 && tile.type <= 483)
         {
             for (int m = 0; m < 8; m++)
             {
                 int num20 = 6;
                 int num21 = i;
                 int num22 = j;
                 switch (m)
                 {
                 case 0:
                     num21--;
                     break;
                 case 1:
                     num21++;
                     break;
                 case 2:
                     num22--;
                     num20 /= 2;
                     break;
                 case 3:
                     num22++;
                     break;
                 case 4:
                     num21--;
                     num22--;
                     break;
                 case 5:
                     num21++;
                     num22--;
                     break;
                 case 6:
                     num21--;
                     num22++;
                     break;
                 case 7:
                     num21++;
                     num22++;
                     break;
                 }
                 Tile tile3 = Main.tile[num21, num22];
                 if (tile3.active() && genRand.Next(num20) == 0 && tile3.type >= 481 && tile3.type <= 483)
                 {
                     tile.active(active: false);
                     KillTile(num21, num22, fail: false, effectOnly: false, noItem: true);
                     if (Main.netMode == 2)
                     {
                         NetMessage.TrySendData(17, -1, -1, null, 20, num21, num22);
                     }
                 }
             }
             int type = tile.type - 481 + 736;
             int damage = 20;
             EntitySource_TileBreak projectileSource_TileBreak = GetProjectileSource_TileBreak(i, j);
             if (Main.netMode == 0)
             {
                 Projectile.NewProjectile(projectileSource_TileBreak, i * 16 + 8, j * 16 + 8, 0f, 0.41f, type, damage, 0f, Main.myPlayer);
             }
             else if (Main.netMode == 2)
             {
                 int num23 = Projectile.NewProjectile(projectileSource_TileBreak, i * 16 + 8, j * 16 + 8, 0f, 0.41f, type, damage, 0f, Main.myPlayer);
                 Main.projectile[num23].netUpdate = true;
             }
         }
         if (CheckTileBreakability2_ShouldTileSurvive(i, j))
         {
             return;
         }
         if (tile.type == 51 && tile.wall == 62 && genRand.Next(4) != 0)
         {
             noItem = true;
         }
         if (!noItem && !stopDrops && Main.netMode != 1)
         {
             KillTile_DropBait(i, j, tile);
             KillTile_DropItems(i, j, tile);
         }
         if (tile.type == 520)
         {
             TEFoodPlatter.Kill(i, j);
         }
         if (tile.type == 423)
         {
             TELogicSensor.Kill(i, j);
         }
         if (Main.netMode != 2)
         {
             AchievementsHelper.NotifyTileDestroyed(Main.player[Main.myPlayer], tile.type);
         }
         tile.active(active: false);
         tile.halfBrick(halfBrick: false);
         tile.frameX = -1;
         tile.frameY = -1;
         tile.ClearBlockPaintAndCoating();
         tile.frameNumber(0);
         if (Main.netMode != 1)
         {
             if (tile.type == 58 && j > Main.UnderworldLayer)
             {
                 tile.lava(lava: true);
                 tile.liquid = 128;
             }
             else if (tile.type == 230 && Main.getGoodWorld && genRand.Next(2) == 0)
             {
                 tile.lava(lava: true);
                 tile.liquid = 128;
             }
         }
         if (tile.type == 419)
         {
             Wiring.PokeLogicGate(i, j + 1);
         }
         else if (TileID.Sets.BlocksWaterDrawingBehindSelf[tile.type])
         {
             SquareWallFrame(i, j);
         }
         tile.type = 0;
         tile.inActive(inActive: false);
         SquareTileFrame(i, j);
         while (!destroyObject && ExploitDestroyQueue.Count > 0)
         {
             Point point = ExploitDestroyQueue.Dequeue();
             if (Framing.GetTileSafely(point.X, point.Y).active())
             {
                 SquareTileFrame(point.X, point.Y);
                 NetMessage.SendTileSquare(-1, point.X, point.Y);
             }
         }
     }
References Tile.active(), TileID.Sets.BlocksWaterDrawingBehindSelf, Item.bodyType, TileEntity.ByID, Tile.ClearBlockPaintAndCoating(), Main.dedServ, TEFoodPlatter.Find(), TEItemFrame.Find(), TEWeaponsRack.Find(), Tile.frameNumber(), Tile.frameX, Tile.frameY, Main.gameMenu, Main.getGoodWorld, Framing.GetTileSafely(), Tile.halfBrick(), Item.headType, Tile.inActive(), Player.InterruptItemUsageIfOverTile(), TileID.Sets.IsShakeable, Main.item, TEFoodPlatter.Kill(), TELogicSensor.Kill(), Tile.lava(), Item.legType, Tile.liquid, Main.LocalPlayer, Main.maxTilesX, Main.maxTilesY, Main.myPlayer, Item.netDefaults(), Main.netMode, Projectile.netUpdate, Item.NewItem(), Projectile.NewProjectile(), AchievementsHelper.NotifyTileDestroyed(), Main.player, Wiring.PokeLogicGate(), Entity.position, Item.Prefix(), Main.projectile, NetMessage.SendData(), NetMessage.SendTileSquare(), SolidTile, FixExploitManEaters.SpotProtected(), Main.tile, Main.tileMoss, TileID.Sets.tileMossBrick, NetMessage.TrySendData(), Tile.type, Main.UnderworldLayer, and Tile.wall.
Referenced by Liquid.AddWater(), NPC.AI_003_Fighters(), NPC.AI_006_Worms(), Projectile.AI_007_GrapplingHooks(), Projectile.AI_010(), NPC.AI_107_ImprovedWalkers(), Projectile.AI_155_RemoveRope(), Player.ApplyTouchDamage(), Player.CheckCrackedBrickBreak(), Player.CheckIceBreak(), WorldFile.ClearTempTiles(), DelegateMethods.CutTiles(), Projectile.CutTilesAt(), Projectile.ExplodeCrackedTiles(), Projectile.ExplodeTiles(), Minecart.FrameTrack(), TEDisplayDoll.Framing_CheckTile(), TEHatRack.Framing_CheckTile(), TETeleportationPylon.Framing_CheckTile(), TEWeaponsRack.Framing_CheckTile(), JunglePass.GenerateTunnelToSurface(), GenerateWorld(), MessageBuffer.GetData(), Projectile.HandleMovement(), Collision.HitTiles(), Wiring.HitWireSingle(), Player.ItemCheck_CheckCanUse(), Player.ItemCheck_CutTiles(), Player.ItemCheck_TryPlacingWearablesOnMannequins(), Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Player.ItemCheck_UseMiningTools_TryPoundingTile(), Projectile.Kill(), Liquid.LiquidCheck(), mayanTrap(), meteor(), MinecartDiggerHelper.MineTheTileIfNecessary(), TEFoodPlatter.OnPlayerInteraction(), TEItemFrame.OnPlayerInteraction(), TEWeaponsRack.OnPlayerInteraction(), Player.PickTile(), TileObject.Place(), TEFoodPlatter.PlaceItemInFrame(), TEItemFrame.PlaceItemInFrame(), TEWeaponsRack.PlaceItemInFrame(), TrackGenerator.PlacePath(), Player.PlaceThing_PaintScrapper_LongMoss(), Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), placeTrap(), Player.PlaceWeapon(), TETeleportationPylon.RejectPlacementFromNet(), Player.Spawn_ForceClearArea(), DelegateMethods.SpreadDirt(), Player.StickyMovement(), Collision.SwitchTiles(), and Player.TileInteractionsUse().