Terraria: WorldGen.clearWorld
clearWorld()
static void WorldGen.clearWorld () inline static
     {
         //IL_0298: Unknown result type (might be due to invalid IL or missing references)
         //IL_029d: Unknown result type (might be due to invalid IL or missing references)
         ResetTreeShakes();
         Main.ladyBugRainBoost = 0;
         Main.getGoodWorld = false;
         Main.drunkWorld = false;
         Main.tenthAnniversaryWorld = false;
         Main.dontStarveWorld = false;
         Main.notTheBeesWorld = false;
         Main.remixWorld = false;
         Main.noTrapsWorld = false;
         Main.zenithWorld = false;
         Main.afterPartyOfDoom = false;
         Main.shimmerAlpha = 0f;
         Main.shimmerDarken = 0f;
         Main.shimmerBrightenDelay = 0f;
         NPC.ResetBadgerHatTime();
         NPC.freeCake = false;
         NPC.mechQueen = -1;
         Main.mapDelay = 2;
         Main.waterStyle = 0;
         Main.ResetWindCounter(resetExtreme: true);
         TownManager = new TownRoomManager();
         PressurePlateHelper.Reset();
         TownManager.Clear();
         NPC.ResetKillCount();
         Main.instance.ClearCachedTileDraws();
         MapHelper.ResetMapData();
         TileEntity.Clear();
         Main.checkXMas();
         Main.checkHalloween();
         DontStarveDarknessDamageDealer.Reset();
         Wiring.ClearAll();
         Main.ParticleSystem_World_BehindPlayers.Particles.Clear();
         Main.ParticleSystem_World_OverPlayers.Particles.Clear();
         if (Main.mapReady)
         {
             for (int i = 0; i < lastMaxTilesX; i++)
             {
                 _ = (float)i / (float)lastMaxTilesX;
                 Main.statusText = Lang.gen[65].Value;
             }
             if (Main.Map != null)
             {
                 Main.Map.Clear();
             }
         }
         NPC.MoonLordCountdown = 0;
         Main.forceHalloweenForToday = false;
         Main.forceXMasForToday = false;
         NPC.RevengeManager.Reset();
         Main.pumpkinMoon = false;
         Main.clearMap = true;
         Main.mapTime = 0;
         Main.updateMap = false;
         Main.mapReady = false;
         Main.refreshMap = false;
         Main.eclipse = false;
         Main.slimeRain = false;
         Main.slimeRainTime = 0.0;
         Main.slimeWarningTime = 0;
         Main.sundialCooldown = 0;
         Main.moondialCooldown = 0;
         Main.fastForwardTimeToDawn = false;
         Main.fastForwardTimeToDusk = false;
         BirthdayParty.WorldClear();
         LanternNight.WorldClear();
         mysticLogsEvent.WorldClear();
         CreditsRollEvent.Reset();
         Sandstorm.WorldClear();
         Main.DroneCameraTracker.WorldClear();
         Main.LocalGolfState.WorldClear();
         Main.CurrentPan = Vector2.Zero;
         Main.UpdateTimeRate();
         Main.wofNPCIndex = -1;
         NPC.waveKills = 0f;
         spawnHardBoss = 0;
         totalSolid2 = 0;
         totalGood2 = 0;
         totalEvil2 = 0;
         totalBlood2 = 0;
         totalSolid = 0;
         totalGood = 0;
         totalEvil = 0;
         totalBlood = 0;
         WorldFile.ResetTemps();
         Main.maxRaining = 0f;
         totalX = 0;
         totalD = 0;
         tEvil = 0;
         tBlood = 0;
         tGood = 0;
         spawnEye = false;
         prioritizedTownNPCType = 0;
         shadowOrbCount = 0;
         altarCount = 0;
         SavedOreTiers.Copper = -1;
         SavedOreTiers.Iron = -1;
         SavedOreTiers.Silver = -1;
         SavedOreTiers.Gold = -1;
         SavedOreTiers.Cobalt = -1;
         SavedOreTiers.Mythril = -1;
         SavedOreTiers.Adamantite = -1;
         GenVars.shimmerPosition = Vector2D.Zero;
         Main.cloudBGActive = 0f;
         Main.raining = false;
         Main.hardMode = false;
         Main.helpText = 0;
         Main.BartenderHelpTextIndex = 0;
         Main.dungeonX = 0;
         Main.dungeonY = 0;
         NPC.downedBoss1 = false;
         NPC.downedBoss2 = false;
         NPC.downedBoss3 = false;
         NPC.downedQueenBee = false;
         NPC.downedSlimeKing = false;
         NPC.downedMechBossAny = false;
         NPC.downedMechBoss1 = false;
         NPC.downedMechBoss2 = false;
         NPC.downedMechBoss3 = false;
         NPC.downedFishron = false;
         NPC.downedAncientCultist = false;
         NPC.downedMoonlord = false;
         NPC.downedHalloweenKing = false;
         NPC.downedHalloweenTree = false;
         NPC.downedChristmasIceQueen = false;
         NPC.downedChristmasSantank = false;
         NPC.downedChristmasTree = false;
         NPC.downedPlantBoss = false;
         NPC.downedGolemBoss = false;
         NPC.downedEmpressOfLight = false;
         NPC.downedQueenSlime = false;
         NPC.downedDeerclops = false;
         NPC.combatBookWasUsed = false;
         NPC.combatBookVolumeTwoWasUsed = false;
         NPC.peddlersSatchelWasUsed = false;
         NPC.savedStylist = false;
         NPC.savedGoblin = false;
         NPC.savedWizard = false;
         NPC.savedMech = false;
         NPC.savedTaxCollector = false;
         NPC.savedAngler = false;
         NPC.savedBartender = false;
         NPC.savedGolfer = false;
         NPC.boughtCat = false;
         NPC.boughtDog = false;
         NPC.boughtBunny = false;
         NPC.unlockedSlimeBlueSpawn = false;
         NPC.unlockedSlimeGreenSpawn = false;
         NPC.unlockedSlimeOldSpawn = false;
         NPC.unlockedSlimePurpleSpawn = false;
         NPC.unlockedSlimeRainbowSpawn = false;
         NPC.unlockedSlimeRedSpawn = false;
         NPC.unlockedSlimeYellowSpawn = false;
         NPC.unlockedSlimeCopperSpawn = false;
         NPC.unlockedMerchantSpawn = false;
         NPC.unlockedDemolitionistSpawn = false;
         NPC.unlockedPartyGirlSpawn = false;
         NPC.unlockedDyeTraderSpawn = false;
         NPC.unlockedTruffleSpawn = false;
         NPC.unlockedArmsDealerSpawn = false;
         NPC.unlockedNurseSpawn = false;
         NPC.unlockedPrincessSpawn = false;
         Array.Clear(NPC.ShimmeredTownNPCs, 0, NPC.ShimmeredTownNPCs.Length);
         NPC.downedGoblins = false;
         NPC.downedClown = false;
         NPC.downedFrost = false;
         NPC.downedPirates = false;
         NPC.downedMartians = false;
         NPC.downedTowerSolar = (NPC.downedTowerVortex = (NPC.downedTowerNebula = (NPC.downedTowerStardust = (NPC.LunarApocalypseIsUp = false))));
         NPC.TowerActiveSolar = (NPC.TowerActiveVortex = (NPC.TowerActiveNebula = (NPC.TowerActiveStardust = false)));
         DD2Event.ResetProgressEntirely();
         NPC.ClearFoundActiveNPCs();
         Main.BestiaryTracker.Reset();
         Main.PylonSystem.Reset();
         CreativePowerManager.Instance.Reset();
         Main.CreativeMenu.Reset();
         shadowOrbSmashed = false;
         spawnMeteor = false;
         stopDrops = false;
         Main.invasionDelay = 0;
         Main.invasionType = 0;
         Main.invasionSize = 0;
         Main.invasionWarn = 0;
         Main.invasionX = 0.0;
         Main.invasionSizeStart = 0;
         Main.treeX[0] = Main.maxTilesX;
         Main.treeX[1] = Main.maxTilesX;
         Main.treeX[2] = Main.maxTilesX;
         Main.treeStyle[0] = 0;
         Main.treeStyle[1] = 0;
         Main.treeStyle[2] = 0;
         Main.treeStyle[3] = 0;
         noLiquidCheck = false;
         Liquid.numLiquid = 0;
         LiquidBuffer.numLiquidBuffer = 0;
         if (Main.netMode == 1 || lastMaxTilesX > Main.maxTilesX || lastMaxTilesY > Main.maxTilesY)
         {
             for (int j = 0; j < lastMaxTilesX; j++)
             {
                 float num = (float)j / (float)lastMaxTilesX;
                 Main.statusText = Lang.gen[46].Value + " " + (int)(num * 100f + 1f) + "%";
                 for (int k = 0; k < lastMaxTilesY; k++)
                 {
                     Main.tile[j, k] = null;
                 }
             }
         }
         lastMaxTilesX = Main.maxTilesX;
         lastMaxTilesY = Main.maxTilesY;
         if (Main.netMode != 2)
         {
             Main.sectionManager = new WorldSections(Main.maxTilesX / 200, Main.maxTilesY / 150);
         }
         if (Main.netMode != 1)
         {
             for (int l = 0; l < Main.maxTilesX; l++)
             {
                 float num2 = (float)l / (float)Main.maxTilesX;
                 Main.statusText = Lang.gen[47].Value + " " + (int)(num2 * 100f + 1f) + "%";
                 for (int m = 0; m < Main.maxTilesY; m++)
                 {
                     if (Main.tile[l, m] == null)
                     {
                         Main.tile[l, m] = new Tile();
                     }
                     else
                     {
                         Main.tile[l, m].ClearEverything();
                     }
                 }
             }
         }
         for (int n = 0; n < Main.countsAsHostForGameplay.Length; n++)
         {
             Main.countsAsHostForGameplay[n] = false;
         }
         CombatText.clearAll();
         PopupText.ClearAll();
         for (int num3 = 0; num3 < 6000; num3++)
         {
             Main.dust[num3] = new Dust();
             Main.dust[num3].dustIndex = num3;
         }
         for (int num4 = 0; num4 < 600; num4++)
         {
             Main.gore[num4] = new Gore();
         }
         for (int num5 = 0; num5 < 400; num5++)
         {
             Main.item[num5] = new Item();
             Main.item[num5].whoAmI = num5;
             Main.timeItemSlotCannotBeReusedFor[num5] = 0;
         }
         for (int num6 = 0; num6 < 200; num6++)
         {
             Main.npc[num6] = new NPC();
             Main.npc[num6].whoAmI = num6;
         }
         for (int num7 = 0; num7 < 1000; num7++)
         {
             Main.projectile[num7] = new Projectile();
             Main.projectile[num7].whoAmI = num7;
         }
         for (int num8 = 0; num8 < 8000; num8++)
         {
             Main.chest[num8] = null;
         }
         for (int num9 = 0; num9 < 1000; num9++)
         {
             Main.sign[num9] = null;
         }
         for (int num10 = 0; num10 < Liquid.maxLiquid; num10++)
         {
             Main.liquid[num10] = new Liquid();
         }
         for (int num11 = 0; num11 < 50000; num11++)
         {
             Main.liquidBuffer[num11] = new LiquidBuffer();
         }
         setWorldSize();
         Star.SpawnStars();
         worldCleared = true;
     }
References WorldGen.SavedOreTiers.Adamantite, Main.afterPartyOfDoom, altarCount, Main.BartenderHelpTextIndex, Main.BestiaryTracker, NPC.boughtBunny, NPC.boughtCat, NPC.boughtDog, Main.checkHalloween(), Main.checkXMas(), Main.chest, TileEntity.Clear(), TownRoomManager.Clear(), WorldMap.Clear(), CombatText.clearAll(), PopupText.ClearAll(), Wiring.ClearAll(), Main.ClearCachedTileDraws(), Tile.ClearEverything(), NPC.ClearFoundActiveNPCs(), Main.clearMap, Main.cloudBGActive, WorldGen.SavedOreTiers.Cobalt, NPC.combatBookVolumeTwoWasUsed, NPC.combatBookWasUsed, WorldGen.SavedOreTiers.Copper, Main.countsAsHostForGameplay, Main.CreativeMenu, Main.CurrentPan, Main.dontStarveWorld, NPC.downedAncientCultist, NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedChristmasIceQueen, NPC.downedChristmasSantank, NPC.downedChristmasTree, NPC.downedClown, NPC.downedDeerclops, NPC.downedEmpressOfLight, NPC.downedFishron, NPC.downedFrost, NPC.downedGoblins, NPC.downedGolemBoss, NPC.downedHalloweenKing, NPC.downedHalloweenTree, NPC.downedMartians, NPC.downedMechBoss1, NPC.downedMechBoss2, NPC.downedMechBoss3, NPC.downedMechBossAny, NPC.downedMoonlord, NPC.downedPirates, NPC.downedPlantBoss, NPC.downedQueenBee, NPC.downedQueenSlime, NPC.downedSlimeKing, NPC.downedTowerNebula, NPC.downedTowerSolar, NPC.downedTowerStardust, NPC.downedTowerVortex, Main.DroneCameraTracker, Main.drunkWorld, Main.dungeonX, Main.dungeonY, Main.dust, Dust.dustIndex, Main.eclipse, Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Main.forceHalloweenForToday, Main.forceXMasForToday, NPC.freeCake, Lang.gen, Main.getGoodWorld, WorldGen.SavedOreTiers.Gold, Main.gore, Main.hardMode, Main.helpText, CreativePowerManager.Instance, Main.instance, Main.invasionDelay, Main.invasionSize, Main.invasionSizeStart, Main.invasionType, Main.invasionWarn, Main.invasionX, WorldGen.SavedOreTiers.Iron, Main.item, Main.ladyBugRainBoost, lastMaxTilesX, lastMaxTilesY, Liquid, Main.liquid, Main.liquidBuffer, Main.LocalGolfState, NPC.LunarApocalypseIsUp, Main.Map, Main.mapDelay, Main.mapReady, Main.mapTime, Main.maxRaining, Main.maxTilesX, Main.maxTilesY, NPC.mechQueen, Main.moondialCooldown, NPC.MoonLordCountdown, mysticLogsEvent, WorldGen.SavedOreTiers.Mythril, Main.netMode, noLiquidCheck, Main.noTrapsWorld, Main.notTheBeesWorld, NPC, Main.npc, LiquidBuffer.numLiquidBuffer, ParticleRenderer.Particles, Main.ParticleSystem_World_BehindPlayers, Main.ParticleSystem_World_OverPlayers, NPC.peddlersSatchelWasUsed, prioritizedTownNPCType, Main.projectile, Main.pumpkinMoon, Main.PylonSystem, Main.raining, Main.refreshMap, Main.remixWorld, BestiaryUnlocksTracker.Reset(), CreativePowerManager.Reset(), CreativeUI.Reset(), CreditsRollEvent.Reset(), CoinLossRevengeSystem.Reset(), DontStarveDarknessDamageDealer.Reset(), PressurePlateHelper.Reset(), TeleportPylonsSystem.Reset(), NPC.ResetBadgerHatTime(), NPC.ResetKillCount(), MapHelper.ResetMapData(), DD2Event.ResetProgressEntirely(), WorldFile.ResetTemps(), ResetTreeShakes(), Main.ResetWindCounter(), NPC.RevengeManager, NPC.savedAngler, NPC.savedBartender, NPC.savedGoblin, NPC.savedGolfer, NPC.savedMech, NPC.savedStylist, NPC.savedTaxCollector, NPC.savedWizard, Main.sectionManager, setWorldSize(), shadowOrbCount, shadowOrbSmashed, Main.shimmerAlpha, Main.shimmerBrightenDelay, Main.shimmerDarken, NPC.ShimmeredTownNPCs, GenVars.shimmerPosition, Main.sign, WorldGen.SavedOreTiers.Silver, Main.slimeRain, Main.slimeRainTime, Main.slimeWarningTime, spawnEye, spawnHardBoss, spawnMeteor, Star.SpawnStars(), Main.statusText, stopDrops, Main.sundialCooldown, tBlood, Main.tenthAnniversaryWorld, tEvil, tGood, Tile, Main.tile, Main.timeItemSlotCannotBeReusedFor, totalBlood, totalBlood2, totalD, totalEvil, totalEvil2, totalGood, totalGood2, totalSolid, totalSolid2, totalX, NPC.TowerActiveNebula, NPC.TowerActiveSolar, NPC.TowerActiveStardust, NPC.TowerActiveVortex, TownManager, Main.treeStyle, Main.treeX, NPC.unlockedArmsDealerSpawn, NPC.unlockedDemolitionistSpawn, NPC.unlockedDyeTraderSpawn, NPC.unlockedMerchantSpawn, NPC.unlockedNurseSpawn, NPC.unlockedPartyGirlSpawn, NPC.unlockedPrincessSpawn, NPC.unlockedSlimeBlueSpawn, NPC.unlockedSlimeCopperSpawn, NPC.unlockedSlimeGreenSpawn, NPC.unlockedSlimeOldSpawn, NPC.unlockedSlimePurpleSpawn, NPC.unlockedSlimeRainbowSpawn, NPC.unlockedSlimeRedSpawn, NPC.unlockedSlimeYellowSpawn, NPC.unlockedTruffleSpawn, Main.updateMap, Main.UpdateTimeRate(), LocalizedText.Value, Main.waterStyle, NPC.waveKills, Entity.whoAmI, Main.wofNPCIndex, DroneCameraTracker.WorldClear(), BirthdayParty.WorldClear(), LanternNight.WorldClear(), MysticLogFairiesEvent.WorldClear(), Sandstorm.WorldClear(), GolfState.WorldClear(), worldCleared, Main.zenithWorld, and Vector2D.Zero.
Referenced by WorldUtils.DebugRegen(), Main.Initialize_AlmostEverything(), Netplay.InnerClientLoop(), WorldFile.LoadHeader(), WorldFile.LoadWorld(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), and worldGenCallback().