Terraria: WorldGen.CheckBamboo
CheckBamboo()
static void WorldGen.CheckBamboo (int x, int y) inline static
     {
         Tile tile = Main.tile[x, y + 1];
         if (tile == null)
         {
             return;
         }
         if (!tile.active() || (tile.type != 60 && tile.type != 571))
         {
             KillTile(x, y);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x, y);
             }
             SquareTileFrame(x, y);
             return;
         }
         Tile tile2 = Main.tile[x, y - 1];
         if (tile2 == null)
         {
             return;
         }
         Tile tile3 = Main.tile[x, y];
         if (tile3 == null)
         {
             return;
         }
         bool num = tile2.active() && tile2.type == 571;
         bool flag = tile.active() && tile.type == 571;
         int num2 = tile3.frameX / 18;
         tile3.frameY = 0;
         if (num)
         {
             if (flag)
             {
                 if (num2 < 5 || num2 > 14)
                 {
                     tile3.frameX = (short)(genRand.Next(5, 15) * 18);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, x, y);
                     }
                 }
             }
             else if (num2 < 1 || num2 > 4)
             {
                 tile3.frameX = (short)(genRand.Next(1, 5) * 18);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
             }
         }
         else if (flag)
         {
             if (num2 < 15 || num2 > 19)
             {
                 tile3.frameX = (short)(genRand.Next(15, 20) * 18);
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendTileSquare(-1, x, y);
                 }
             }
         }
         else if (num2 != 0)
         {
             tile3.frameX = 0;
             if (Main.netMode == 2)
             {
                 NetMessage.SendTileSquare(-1, x, y);
             }
         }
     }
References Tile.active(), Tile.frameX, Tile.frameY, Main.netMode, NetMessage.SendData(), NetMessage.SendTileSquare(), Main.tile, and Tile.type.