Terraria: WorldGen.KillTile_MakeTileDust
KillTile_MakeTileDust()
static int WorldGen.KillTile_MakeTileDust (int i, int j, Tile tileCache) inline static
     {
         int num = 0;
         if (tileCache.type == 216)
         {
             num = -1;
         }
         if (tileCache.type == 324)
         {
             num = ((tileCache.frameY != 0) ? (281 + tileCache.frameX / 18) : 280);
         }
         if (tileCache.type == 216)
         {
             num = -1;
         }
         if (tileCache.type == 335)
         {
             num = -1;
         }
         if (tileCache.type == 338)
         {
             num = -1;
         }
         if (tileCache.type == 0)
         {
             num = 0;
         }
         if (tileCache.type == 192)
         {
             num = 3;
         }
         if (tileCache.type == 208)
         {
             num = 126;
         }
         else if (tileCache.type == 408 || tileCache.type == 409)
         {
             num = 265;
         }
         else if (tileCache.type == 669)
         {
             num = 314;
         }
         else if (tileCache.type == 670)
         {
             num = 315;
         }
         else if (tileCache.type == 671)
         {
             num = 316;
         }
         else if (tileCache.type == 672)
         {
             num = 317;
         }
         else if (tileCache.type == 673)
         {
             num = 318;
         }
         else if (tileCache.type == 674)
         {
             num = 319;
         }
         else if (tileCache.type == 675)
         {
             num = 320;
         }
         else if (tileCache.type == 676)
         {
             num = 321;
         }
         if (tileCache.type == 16)
         {
             num = 1;
             if (tileCache.frameX >= 36)
             {
                 num = 82;
             }
         }
         else if (tileCache.type == 415 || tileCache.type == 500)
         {
             num = 6;
         }
         else if (tileCache.type == 416 || tileCache.type == 501)
         {
             num = 61;
         }
         else if (tileCache.type == 417 || tileCache.type == 502)
         {
             num = 242;
         }
         else if (tileCache.type == 418 || tileCache.type == 503)
         {
             num = 135;
         }
         else if (tileCache.type == 474)
         {
             num = 18;
         }
         if (tileCache.type == 1 || tileCache.type == 17 || tileCache.type == 38 || tileCache.type == 39 || tileCache.type == 41 || tileCache.type == 43 || tileCache.type == 44 || tileCache.type == 481 || tileCache.type == 482 || tileCache.type == 483 || tileCache.type == 48 || Main.tileStone[tileCache.type] || tileCache.type == 85 || tileCache.type == 90 || tileCache.type == 92 || tileCache.type == 96 || tileCache.type == 97 || tileCache.type == 99 || tileCache.type == 117 || tileCache.type == 130 || tileCache.type == 131 || tileCache.type == 132 || tileCache.type == 135 || tileCache.type == 135 || tileCache.type == 142 || tileCache.type == 143 || tileCache.type == 144 || tileCache.type == 210 || tileCache.type == 207 || tileCache.type == 235 || tileCache.type == 247 || tileCache.type == 272 || tileCache.type == 273 || tileCache.type == 283 || tileCache.type == 410 || tileCache.type == 480 || tileCache.type == 509 || tileCache.type == 618 || tileCache.type == 657 || tileCache.type == 658 || tileCache.type == 677 || tileCache.type == 678 || tileCache.type == 679)
         {
             num = 1;
         }
         if (tileCache.type == 379)
         {
             num = 257;
         }
         if (tileCache.type == 311)
         {
             num = 207;
         }
         if (tileCache.type == 312)
         {
             num = 208;
         }
         if (tileCache.type == 313)
         {
             num = 209;
         }
         if (tileCache.type == 104)
         {
             num = -1;
         }
         if (tileCache.type == 95 || tileCache.type == 98 || tileCache.type == 100 || tileCache.type == 174 || tileCache.type == 173)
         {
             num = 6;
         }
         if (tileCache.type == 30 || tileCache.type == 86 || tileCache.type == 94 || tileCache.type == 106 || tileCache.type == 114 || tileCache.type == 124 || tileCache.type == 128 || tileCache.type == 269)
         {
             num = 7;
         }
         if (tileCache.type == 372)
         {
             num = 242;
         }
         if (tileCache.type == 646)
         {
             num = 29;
         }
         if (tileCache.type == 49)
         {
             num = 29;
         }
         if (tileCache.type == 371)
         {
             num = 243;
         }
         if (tileCache.type == 334)
         {
             num = 7;
         }
         switch (tileCache.type)
         {
         case 10:
         case 11:
         case 87:
         case 89:
         case 93:
         case 139:
         case 209:
         case 319:
         case 320:
         case 386:
         case 387:
         case 390:
         case 405:
         case 406:
         case 411:
         case 412:
         case 419:
         case 420:
         case 421:
         case 422:
         case 423:
         case 424:
         case 425:
         case 428:
         case 429:
         case 441:
         case 442:
         case 445:
         case 446:
         case 447:
         case 448:
         case 449:
         case 450:
         case 451:
         case 452:
         case 453:
         case 455:
         case 456:
         case 457:
         case 462:
         case 463:
         case 464:
         case 465:
         case 466:
         case 468:
         case 476:
         case 486:
         case 487:
         case 489:
         case 490:
         case 491:
         case 493:
         case 494:
         case 497:
         case 510:
         case 511:
         case 520:
         case 521:
         case 522:
         case 523:
         case 524:
         case 525:
         case 526:
         case 527:
         case 531:
         case 545:
         case 547:
         case 548:
         case 560:
         case 564:
         case 565:
         case 567:
         case 572:
         case 579:
         case 591:
         case 592:
         case 593:
         case 594:
         case 613:
         case 614:
         case 621:
         case 622:
         case 623:
         case 624:
         case 630:
         case 631:
         case 656:
             num = -1;
             break;
         case 668:
             num = 0;
             break;
         case 407:
             num = 10;
             break;
         case 454:
             num = 139;
             break;
         case 41:
         case 481:
         case 677:
             num = 275;
             break;
         case 43:
         case 482:
         case 678:
             num = 276;
             break;
         case 44:
         case 483:
         case 679:
             num = 277;
             break;
         case 473:
             num = 82;
             break;
         case 472:
         case 546:
         case 557:
             num = 8;
             break;
         case 498:
             num = 30;
             break;
         case 517:
         case 687:
             num = 258;
             break;
         case 535:
         case 689:
             num = 299;
             break;
         case 537:
         case 690:
             num = 300;
             break;
         case 540:
         case 688:
             num = 301;
             break;
         case 626:
         case 691:
             num = 305;
             break;
         case 184:
         {
             int num2 = tileCache.frameX / 22;
             num = num2 switch
             {
                 5 => 258,
                 6 => 299,
                 7 => 300,
                 8 => 301,
                 9 => 305,
                 10 => 267,
                 _ => 93 + num2,
             };
             break;
         }
         case 515:
             num = 96;
             break;
         case 516:
             num = 97;
             break;
         case 514:
             num = 95;
             break;
         case 513:
             num = 94;
             break;
         case 512:
             num = 93;
             break;
         case 541:
             num = 226;
             break;
         case 590:
             num = 1;
             break;
         case 583:
             num = ((genRand.Next(10) != 0) ? 1 : 87);
             break;
         case 584:
             num = ((genRand.Next(10) != 0) ? 1 : 86);
             break;
         case 585:
             num = ((genRand.Next(10) != 0) ? 1 : 88);
             break;
         case 586:
             num = ((genRand.Next(10) != 0) ? 1 : 89);
             break;
         case 587:
             num = ((genRand.Next(10) != 0) ? 1 : 90);
             break;
         case 588:
             num = ((genRand.Next(10) != 0) ? 1 : 91);
             break;
         case 589:
             num = ((genRand.Next(10) != 0) ? 1 : 138);
             break;
         case 595:
             num = 78;
             break;
         case 596:
             num = 78;
             break;
         case 615:
             num = 78;
             break;
         case 616:
             num = 78;
             break;
         case 633:
             num = ((genRand.Next(6) != 0) ? 237 : 36);
             break;
         case 637:
         case 638:
             num = 237;
             break;
         case 634:
             num = ((genRand.Next(10) != 0) ? 36 : 31);
             if (genRand.Next(12) == 0)
             {
                 num = 6;
             }
             break;
         }
         if (Main.tileMoss[tileCache.type])
         {
             num = ((tileCache.type == 381) ? 258 : ((tileCache.type == 534) ? 299 : ((tileCache.type == 536) ? 300 : ((tileCache.type == 539) ? 301 : ((tileCache.type == 625) ? 305 : ((tileCache.type != 627) ? (tileCache.type - 179 + 93) : 267))))));
         }
         if (tileCache.type == 240)
         {
             int num3 = tileCache.frameX / 54;
             if (tileCache.frameY >= 54)
             {
                 num3 += 36 * (tileCache.frameY / 54);
             }
             num = 7;
             if (num3 == 16 || num3 == 17)
             {
                 num = 26;
             }
             if (num3 >= 46 && num3 <= 49)
             {
                 num = -1;
             }
         }
         if (tileCache.type == 241)
         {
             num = 1;
         }
         if (tileCache.type == 242)
         {
             num = -1;
         }
         if (tileCache.type == 529)
         {
             num = Main.tile[i, j + 1].type switch
             {
                 116 => num = 47,
                 234 => num = 125,
                 112 => num = 17,
                 _ => (i >= beachDistance && i <= Main.maxTilesX - beachDistance) ? 289 : 290,
             };
         }
         if (tileCache.type == 356)
         {
             num = -1;
         }
         if (tileCache.type == 663)
         {
             num = -1;
         }
         if (tileCache.type == 351)
         {
             num = -1;
         }
         if (tileCache.type == 246)
         {
             num = -1;
         }
         if (tileCache.type == 36)
         {
             num = -1;
         }
         if (tileCache.type == 365)
         {
             num = 239;
         }
         if (tileCache.type == 366)
         {
             num = 30;
         }
         if (tileCache.type == 504)
         {
             num = -1;
         }
         if (tileCache.type == 357 || tileCache.type == 367 || tileCache.type == 561)
         {
             num = 236;
         }
         if (tileCache.type == 368 || tileCache.type == 369 || tileCache.type == 576)
         {
             num = 240;
         }
         if (tileCache.type == 170)
         {
             num = 196;
         }
         if (tileCache.type == 315)
         {
             num = 225;
         }
         if (tileCache.type == 641)
         {
             num = ((genRand.Next(2) != 0) ? 161 : 243);
         }
         if (tileCache.type == 659)
         {
             num = 308;
         }
         if (tileCache.type == 667)
         {
             num = 308;
         }
         if (tileCache.type == 346)
         {
             num = 128;
         }
         if (tileCache.type == 347)
         {
             num = 117;
         }
         if (tileCache.type == 348)
         {
             num = 42;
         }
         if (tileCache.type == 350)
         {
             num = 226;
         }
         if (tileCache.type == 370)
         {
             num = ((genRand.Next(2) != 0) ? 23 : 6);
         }
         if (tileCache.type == 171)
         {
             num = ((genRand.Next(2) != 0) ? (-1) : 196);
         }
         if (tileCache.type == 326)
         {
             num = 13;
         }
         if (tileCache.type == 327)
         {
             num = 13;
         }
         if (tileCache.type == 345)
         {
             num = 13;
         }
         if (tileCache.type == 458)
         {
             num = 13;
         }
         if (tileCache.type == 459)
         {
             num = 13;
         }
         if (tileCache.type == 336)
         {
             num = 6;
         }
         if (tileCache.type == 340)
         {
             num = 75;
         }
         if (tileCache.type == 341)
         {
             num = 65;
         }
         if (tileCache.type == 342)
         {
             num = 135;
         }
         if (tileCache.type == 343)
         {
             num = 169;
         }
         if (tileCache.type == 344)
         {
             num = 156;
         }
         if (tileCache.type == 328)
         {
             num = 13;
         }
         if (tileCache.type == 329)
         {
             num = 13;
         }
         if (tileCache.type == 507)
         {
             num = 13;
         }
         if (tileCache.type == 508)
         {
             num = 13;
         }
         if (tileCache.type == 562)
         {
             num = -1;
         }
         if (tileCache.type == 571)
         {
             num = 40;
         }
         if (tileCache.type == 563)
         {
             num = -1;
         }
         if (tileCache.type == 330)
         {
             num = 9;
         }
         if (tileCache.type == 331)
         {
             num = 11;
         }
         if (tileCache.type == 332)
         {
             num = 19;
         }
         if (tileCache.type == 333)
         {
             num = 11;
         }
         if (tileCache.type == 101)
         {
             num = -1;
         }
         if (tileCache.type == 19)
         {
             num = (tileCache.frameY / 18) switch
             {
                 0 => 7,
                 1 => 77,
                 2 => 78,
                 3 => 79,
                 4 => 26,
                 5 => 126,
                 6 => 275,
                 7 => 277,
                 8 => 276,
                 9 => 1,
                 10 => 214,
                 11 => 214,
                 12 => 214,
                 13 => 109,
                 14 => 13,
                 15 => 189,
                 16 => 191,
                 17 => 215,
                 18 => 26,
                 19 => 214,
                 20 => 4,
                 21 => 10,
                 22 => 32,
                 23 => 78,
                 24 => 147,
                 25 => 40,
                 26 => 226,
                 27 => 23,
                 28 => 240,
                 29 => 236,
                 30 => 68 + Main.rand.Next(3),
                 31 => 10,
                 32 => 78,
                 33 => 148,
                 34 => 5,
                 35 => 80,
                 37 => 18,
                 38 => 6,
                 39 => 61,
                 40 => 242,
                 41 => 135,
                 42 => 287,
                 44 => 273,
                 45 => 243,
                 46 => 243,
                 47 => 36,
                 48 => 226,
                 _ => 1,
             };
         }
         if (tileCache.type == 79)
         {
             int num4 = tileCache.frameY / 36;
             num = ((num4 == 0) ? 7 : ((num4 == 1) ? 77 : ((num4 == 2) ? 78 : ((num4 == 3) ? 79 : ((num4 == 4) ? 126 : ((num4 == 8) ? 109 : ((num4 < 9) ? 1 : (-1))))))));
         }
         if (tileCache.type == 18)
         {
             switch (tileCache.frameX / 36)
             {
             case 0:
                 num = 7;
                 break;
             case 1:
                 num = 77;
                 break;
             case 2:
                 num = 78;
                 break;
             case 3:
                 num = 79;
                 break;
             case 4:
                 num = 26;
                 break;
             case 5:
                 num = 40;
                 break;
             case 6:
                 num = 5;
                 break;
             case 7:
                 num = 26;
                 break;
             case 8:
                 num = 4;
                 break;
             case 9:
                 num = 126;
                 break;
             case 10:
                 num = 148;
                 break;
             case 11:
             case 12:
             case 13:
                 num = 1;
                 break;
             case 14:
                 num = 109;
                 break;
             case 15:
                 num = 126;
                 break;
             default:
                 num = -1;
                 break;
             }
         }
         if (tileCache.type == 14 || tileCache.type == 87 || tileCache.type == 88 || tileCache.type == 469)
         {
             num = -1;
         }
         if (tileCache.type >= 255 && tileCache.type <= 261)
         {
             int num5 = tileCache.type - 255;
             num = 86 + num5;
             if (num5 == 6)
             {
                 num = 138;
             }
         }
         if (tileCache.type >= 262 && tileCache.type <= 268)
         {
             int num6 = tileCache.type - 262;
             num = 86 + num6;
             if (num6 == 6)
             {
                 num = 138;
             }
         }
         if (tileCache.type == 178)
         {
             int num7 = tileCache.frameX / 18;
             num = 86 + num7;
             if (num7 == 6)
             {
                 num = 138;
             }
         }
         if (tileCache.type == 440)
         {
             num = (tileCache.frameX / 54) switch
             {
                 0 => 90,
                 1 => 88,
                 2 => 89,
                 3 => 87,
                 4 => 86,
                 5 => 91,
                 6 => 138,
                 _ => -1,
             };
             if (tileCache.frameY < 54)
             {
                 num = -1;
             }
         }
         switch (tileCache.type)
         {
         case 426:
         case 427:
             num = 90;
             break;
         case 430:
         case 435:
             num = 89;
             break;
         case 431:
         case 436:
             num = 88;
             break;
         case 432:
         case 437:
             num = 87;
             break;
         case 433:
         case 438:
             num = 86;
             break;
         case 434:
         case 439:
             num = 91;
             break;
         case 496:
             num = 109;
             break;
         case 549:
             num = 3;
             break;
         case 552:
             num = 32;
             break;
         }
         if (tileCache.type == 186)
         {
             num = ((tileCache.frameX <= 360) ? 26 : ((tileCache.frameX <= 846) ? 1 : ((tileCache.frameX <= 954) ? 9 : ((tileCache.frameX <= 1062) ? 11 : ((tileCache.frameX <= 1170) ? 10 : ((tileCache.frameX > 1332) ? ((tileCache.frameX > 1386) ? 80 : 10) : 0))))));
         }
         if (tileCache.type == 187)
         {
             if (tileCache.frameX <= 144)
             {
                 num = 1;
             }
             else if (tileCache.frameX <= 306)
             {
                 num = 38;
             }
             else if (tileCache.frameX <= 468)
             {
                 num = 36;
             }
             else if (tileCache.frameX <= 738)
             {
                 num = 30;
             }
             else if (tileCache.frameX <= 970)
             {
                 num = 1;
             }
             else if (tileCache.frameX <= 1132)
             {
                 num = 148;
             }
             else if (tileCache.frameX <= 1132)
             {
                 num = 155;
             }
             else if (tileCache.frameX <= 1348)
             {
                 num = 1;
             }
             else if (tileCache.frameX <= 1564)
             {
                 num = 0;
             }
             else if (tileCache.frameX <= 1890)
             {
                 num = 250;
             }
             else if (tileCache.frameX <= 2196)
             {
                 num = 240;
             }
             else if (tileCache.frameX <= 2520)
             {
                 num = 236;
             }
         }
         if (tileCache.type == 647)
         {
             int num8 = tileCache.frameX / 54;
             if (num8 < 7)
             {
                 num = 26;
             }
             else if (num8 < 16)
             {
                 num = 1;
             }
             else if (num8 < 18)
             {
                 num = 9;
             }
             else if (num8 < 20)
             {
                 num = 11;
             }
             else if (num8 < 22)
             {
                 num = 10;
             }
             else if (num8 < 26)
             {
                 num = 7;
             }
             else if (num8 < 32)
             {
                 num = 80;
             }
             else if (num8 < 35)
             {
                 num = 80;
             }
         }
         if (tileCache.type == 648)
         {
             int num9 = tileCache.frameX / 54;
             num9 += tileCache.frameY / 36 * 35;
             if (num9 < 3)
             {
                 num = 1;
             }
             else if (num9 < 6)
             {
                 num = 38;
             }
             else if (num9 < 9)
             {
                 num = 36;
             }
             else if (num9 < 14)
             {
                 num = 30;
             }
             else if (num9 < 17)
             {
                 num = 1;
             }
             else if (num9 < 18)
             {
                 num = 1;
             }
             else if (num9 < 21)
             {
                 num = 148;
             }
             else if (num9 < 29)
             {
                 num = 155;
             }
             else if (num9 < 35)
             {
                 num = 287;
             }
             else if (num9 < 41)
             {
                 num = 240;
             }
             else if (num9 < 47)
             {
                 num = 236;
             }
             else if (num9 < 50)
             {
                 num = 0;
             }
             else if (num9 < 52)
             {
                 num = 2;
             }
             else if (num9 < 55)
             {
                 num = 26;
             }
         }
         if (tileCache.type == 105)
         {
             num = 1;
             if (tileCache.frameX >= 1548 && tileCache.frameX <= 1654 && tileCache.frameY < 54)
             {
                 num = 148;
             }
         }
         if (tileCache.type == 349)
         {
             num = 1;
         }
         if (tileCache.type == 337 || tileCache.type == 506)
         {
             num = 1;
         }
         if (tileCache.type == 239)
         {
             int num10 = tileCache.frameX / 18;
             if (num10 == 0)
             {
                 num = 9;
             }
             if (num10 == 1)
             {
                 num = 81;
             }
             if (num10 == 2)
             {
                 num = 8;
             }
             if (num10 == 3)
             {
                 num = 82;
             }
             if (num10 == 4)
             {
                 num = 11;
             }
             if (num10 == 5)
             {
                 num = 83;
             }
             if (num10 == 6)
             {
                 num = 10;
             }
             if (num10 == 7)
             {
                 num = 84;
             }
             if (num10 == 8)
             {
                 num = 14;
             }
             if (num10 == 9)
             {
                 num = 23;
             }
             if (num10 == 10)
             {
                 num = 25;
             }
             if (num10 == 11)
             {
                 num = 48;
             }
             if (num10 == 12)
             {
                 num = 144;
             }
             if (num10 == 13)
             {
                 num = 49;
             }
             if (num10 == 14)
             {
                 num = 145;
             }
             if (num10 == 15)
             {
                 num = 50;
             }
             if (num10 == 16)
             {
                 num = 146;
             }
             if (num10 == 17)
             {
                 num = 128;
             }
             if (num10 == 18)
             {
                 num = 84;
             }
             if (num10 == 19)
             {
                 num = 117;
             }
             if (num10 == 20)
             {
                 num = 42;
             }
             if (num10 == 21)
             {
                 num = -1;
             }
             if (num10 == 22)
             {
                 num = 265;
             }
         }
         if (tileCache.type == 185)
         {
             if (tileCache.frameY == 18)
             {
                 int num11 = tileCache.frameX / 36;
                 if (num11 < 6)
                 {
                     num = 1;
                 }
                 else if (num11 < 16)
                 {
                     num = 26;
                 }
                 else if (num11 == 16)
                 {
                     num = 9;
                 }
                 else if (num11 == 17)
                 {
                     num = 11;
                 }
                 else if (num11 == 18)
                 {
                     num = 10;
                 }
                 else if (num11 == 19)
                 {
                     num = 86;
                 }
                 else if (num11 == 20)
                 {
                     num = 87;
                 }
                 else if (num11 == 21)
                 {
                     num = 88;
                 }
                 else if (num11 == 22)
                 {
                     num = 89;
                 }
                 else if (num11 == 23)
                 {
                     num = 90;
                 }
                 else if (num11 == 24)
                 {
                     num = 91;
                 }
                 else if (num11 < 31)
                 {
                     num = 80;
                 }
                 else if (num11 < 33)
                 {
                     num = 7;
                 }
                 else if (num11 < 34)
                 {
                     num = 8;
                 }
                 else if (num11 < 38)
                 {
                     num = 30;
                 }
                 else if (num11 < 41)
                 {
                     num = 1;
                 }
                 else if (num11 < 47)
                 {
                     num = 287;
                 }
                 else if (num11 < 53)
                 {
                     num = 240;
                 }
                 else if (num11 < 59)
                 {
                     num = 236;
                 }
             }
             else
             {
                 int num12 = tileCache.frameX / 18;
                 if (num12 < 6)
                 {
                     num = 1;
                 }
                 else if (num12 < 12)
                 {
                     num = 0;
                 }
                 else if (num12 < 28)
                 {
                     num = 26;
                 }
                 else if (num12 < 33)
                 {
                     num = 1;
                 }
                 else if (num12 < 36)
                 {
                     num = 0;
                 }
                 else if (num12 < 48)
                 {
                     num = 80;
                 }
                 else if (num12 < 54)
                 {
                     num = 30;
                 }
                 else if (num12 < 60)
                 {
                     num = 287;
                 }
                 else if (num12 < 66)
                 {
                     num = 240;
                 }
                 else if (num12 < 72)
                 {
                     num = 236;
                 }
                 else if (num12 < 73)
                 {
                     num = 0;
                 }
                 else if (num12 < 77)
                 {
                     num = 32;
                 }
             }
         }
         if (tileCache.type == 649)
         {
             int num13 = tileCache.frameX / 36 + tileCache.frameY / 18 * 53;
             if (num13 < 6)
             {
                 num = 1;
             }
             else if (num13 < 16)
             {
                 num = 26;
             }
             else if (num13 == 16)
             {
                 num = 9;
             }
             else if (num13 == 17)
             {
                 num = 11;
             }
             else if (num13 == 18)
             {
                 num = 10;
             }
             else if (num13 == 19)
             {
                 num = 86;
             }
             else if (num13 == 20)
             {
                 num = 87;
             }
             else if (num13 == 21)
             {
                 num = 88;
             }
             else if (num13 == 22)
             {
                 num = 89;
             }
             else if (num13 == 23)
             {
                 num = 90;
             }
             else if (num13 == 24)
             {
                 num = 91;
             }
             else if (num13 < 31)
             {
                 num = 80;
             }
             else if (num13 < 33)
             {
                 num = 7;
             }
             else if (num13 < 34)
             {
                 num = 8;
             }
             else if (num13 < 38)
             {
                 num = 30;
             }
             else if (num13 < 41)
             {
                 num = 1;
             }
             else if (num13 < 47)
             {
                 num = 287;
             }
             else if (num13 < 53)
             {
                 num = 240;
             }
             else if (num13 < 59)
             {
                 num = 236;
             }
             else if (num13 < 62)
             {
                 num = 0;
             }
             else if (num13 < 65)
             {
                 num = 32;
             }
         }
         if (tileCache.type == 650)
         {
             int num14 = tileCache.frameX / 18;
             if (num14 < 6)
             {
                 num = 1;
             }
             else if (num14 < 12)
             {
                 num = 0;
             }
             else if (num14 < 28)
             {
                 num = 26;
             }
             else if (num14 < 33)
             {
                 num = 1;
             }
             else if (num14 < 36)
             {
                 num = 0;
             }
             else if (num14 < 48)
             {
                 num = 80;
             }
             else if (num14 < 54)
             {
                 num = 30;
             }
             else if (num14 < 60)
             {
                 num = 287;
             }
             else if (num14 < 66)
             {
                 num = 240;
             }
             else if (num14 < 72)
             {
                 num = 236;
             }
             else if (num14 < 73)
             {
                 num = 0;
             }
             else if (num14 < 77)
             {
                 num = 32;
             }
         }
         if (tileCache.type == 237)
         {
             num = 148;
         }
         if (tileCache.type == 157)
         {
             num = 77;
         }
         if (tileCache.type == 158 || tileCache.type == 232 || tileCache.type == 383 || tileCache.type == 575)
         {
             num = 78;
         }
         if (tileCache.type == 159)
         {
             num = 78;
         }
         if (tileCache.type == 15)
         {
             num = -1;
         }
         if (tileCache.type == 191)
         {
             num = 7;
         }
         if (tileCache.type == 5)
         {
             num = 7;
             if (i > 5 && i < Main.maxTilesX - 5)
             {
                 int num15 = i;
                 int k = j;
                 if (tileCache.frameX == 66 && tileCache.frameY <= 45)
                 {
                     num15++;
                 }
                 if (tileCache.frameX == 88 && tileCache.frameY >= 66 && tileCache.frameY <= 110)
                 {
                     num15--;
                 }
                 if (tileCache.frameX == 22 && tileCache.frameY >= 132 && tileCache.frameY <= 176)
                 {
                     num15--;
                 }
                 if (tileCache.frameX == 44 && tileCache.frameY >= 132 && tileCache.frameY <= 176)
                 {
                     num15++;
                 }
                 if (tileCache.frameX == 44 && tileCache.frameY >= 132 && tileCache.frameY <= 176)
                 {
                     num15++;
                 }
                 if (tileCache.frameX == 44 && tileCache.frameY >= 198)
                 {
                     num15++;
                 }
                 if (tileCache.frameX == 66 && tileCache.frameY >= 198)
                 {
                     num15--;
                 }
                 for (; Main.tile[num15, k] != null && (!Main.tile[num15, k].active() || !Main.tileSolid[Main.tile[num15, k].type]); k++)
                 {
                 }
                 if (Main.tile[num15, k] != null)
                 {
                     if (Main.tile[num15, k].active() && Main.tile[num15, k].type == 23)
                     {
                         num = 77;
                     }
                     if (Main.tile[num15, k].active() && Main.tile[num15, k].type == 661)
                     {
                         num = 77;
                     }
                     if (Main.tile[num15, k].active() && Main.tile[num15, k].type == 60)
                     {
                         num = 78;
                     }
                     if (Main.tile[num15, k].active() && Main.tile[num15, k].type == 70)
                     {
                         num = 26;
                     }
                     if (Main.tile[num15, k].active() && Main.tile[num15, k].type == 109)
                     {
                         num = 79;
                     }
                     if (Main.tile[num15, k].active() && Main.tile[num15, k].type == 199)
                     {
                         num = 121;
                     }
                     if (Main.tile[num15, k].active() && Main.tile[num15, k].type == 662)
                     {
                         num = 121;
                     }
                     if (Main.tile[num15, k].active() && Main.tile[num15, k].type == 147)
                     {
                         num = 122;
                     }
                 }
             }
         }
         if (tileCache.type == 323)
         {
             num = 215;
             if (i > 5 && i < Main.maxTilesX - 5)
             {
                 int l;
                 for (l = j; Main.tile[i, l] != null && (!Main.tile[i, l].active() || !Main.tileSolid[Main.tile[i, l].type]); l++)
                 {
                 }
                 if (Main.tile[i, l] != null)
                 {
                     if (Main.tile[i, l].active() && Main.tile[i, l].type == 234)
                     {
                         num = 121;
                     }
                     if (Main.tile[i, l].active() && Main.tile[i, l].type == 116)
                     {
                         num = 79;
                     }
                     if (Main.tile[i, l].active() && Main.tile[i, l].type == 112)
                     {
                         num = 77;
                     }
                 }
             }
         }
         if (tileCache.type == 137)
         {
             switch (tileCache.frameY / 18)
             {
             default:
                 num = 1;
                 break;
             case 1:
             case 2:
             case 3:
             case 4:
                 num = 148;
                 break;
             case 5:
                 num = 1;
                 break;
             }
         }
         if (tileCache.type == 443)
         {
             num = 1;
         }
         if (tileCache.type == 444)
         {
             num = -1;
         }
         if (tileCache.type == 212)
         {
             num = -1;
         }
         if (tileCache.type == 213)
         {
             num = 129;
         }
         if (tileCache.type == 214)
         {
             num = 1;
         }
         if (tileCache.type == 215)
         {
             num = -6;
         }
         if (tileCache.type == 325)
         {
             num = 81;
         }
         if (tileCache.type == 251)
         {
             num = 189;
         }
         if (tileCache.type == 252)
         {
             num = 190;
         }
         if (tileCache.type == 253)
         {
             num = 191;
         }
         if (tileCache.type == 254)
         {
             if (tileCache.frameX < 72)
             {
                 num = 3;
             }
             else if (tileCache.frameX < 108)
             {
                 num = 3;
                 if (genRand.Next(3) == 0)
                 {
                     num = 189;
                 }
             }
             else if (tileCache.frameX < 144)
             {
                 num = 3;
                 if (genRand.Next(2) == 0)
                 {
                     num = 189;
                 }
             }
             else
             {
                 num = 3;
                 if (genRand.Next(4) != 0)
                 {
                     num = 189;
                 }
             }
         }
         if (tileCache.type == 467)
         {
             num = -1;
         }
         if (tileCache.type == 21)
         {
             num = ((tileCache.frameX >= 1008) ? (-1) : ((tileCache.frameX >= 612) ? 11 : ((tileCache.frameX >= 576) ? 148 : ((tileCache.frameX >= 540) ? 26 : ((tileCache.frameX >= 504) ? 126 : ((tileCache.frameX >= 468) ? 116 : ((tileCache.frameX >= 432) ? 7 : ((tileCache.frameX >= 396) ? 11 : ((tileCache.frameX >= 360) ? 10 : ((tileCache.frameX >= 324) ? 79 : ((tileCache.frameX >= 288) ? 78 : ((tileCache.frameX >= 252) ? 77 : ((tileCache.frameX >= 216) ? 1 : ((tileCache.frameX >= 180) ? 7 : ((tileCache.frameX >= 108) ? 37 : ((tileCache.frameX < 36) ? 7 : 10))))))))))))))));
         }
         if (tileCache.type == 382)
         {
             num = 3;
         }
         if (tileCache.type == 2 || tileCache.type == 477)
         {
             num = ((genRand.Next(2) != 0) ? 2 : 0);
         }
         if (tileCache.type == 127)
         {
             num = 67;
         }
         if (tileCache.type == 91)
         {
             num = -1;
         }
         if (tileCache.type == 198)
         {
             num = 109;
         }
         if (tileCache.type == 26)
         {
             num = ((tileCache.frameX < 54) ? 8 : 5);
         }
         if (tileCache.type == 34)
         {
             num = -1;
         }
         if (tileCache.type == 6)
         {
             num = 8;
         }
         if (tileCache.type == 7 || tileCache.type == 47 || tileCache.type == 284 || tileCache.type == 682)
         {
             num = 9;
         }
         if (tileCache.type == 8 || tileCache.type == 45 || tileCache.type == 102 || tileCache.type == 680)
         {
             num = 10;
         }
         if (tileCache.type == 9 || tileCache.type == 42 || tileCache.type == 46 || tileCache.type == 126 || tileCache.type == 136 || tileCache.type == 681)
         {
             num = 11;
         }
         if (tileCache.type == 166 || tileCache.type == 175)
         {
             num = 81;
         }
         if (tileCache.type == 167)
         {
             num = 82;
         }
         if (tileCache.type == 168 || tileCache.type == 176)
         {
             num = 83;
         }
         if (tileCache.type == 169 || tileCache.type == 177)
         {
             num = 84;
         }
         if (tileCache.type == 199 || tileCache.type == 662)
         {
             num = 117;
         }
         if (tileCache.type == 205)
         {
             num = 125;
         }
         if (tileCache.type == 201)
         {
             num = 125;
         }
         if (tileCache.type == 211)
         {
             num = 128;
         }
         if (tileCache.type == 227)
         {
             switch (tileCache.frameX / 34)
             {
             case 0:
             case 1:
                 num = 26;
                 break;
             case 3:
                 num = 3;
                 break;
             case 2:
             case 4:
             case 5:
             case 6:
                 num = 40;
                 break;
             case 7:
                 num = 117;
                 break;
             case 8:
                 num = 17;
                 break;
             case 9:
                 num = 6;
                 break;
             case 10:
                 num = 3;
                 break;
             case 11:
                 num = 26;
                 break;
             }
         }
         if (tileCache.type == 204 || tileCache.type == 478)
         {
             num = 117;
             if (genRand.Next(2) == 0)
             {
                 num = 1;
             }
         }
         if (tileCache.type == 203)
         {
             num = 117;
         }
         if (tileCache.type == 243)
         {
             num = ((genRand.Next(2) != 0) ? 13 : 7);
         }
         if (tileCache.type == 219)
         {
             num = -1;
         }
         if (tileCache.type == 642)
         {
             num = -128;
         }
         if (tileCache.type == 244)
         {
             num = ((genRand.Next(2) == 0) ? 1 : 13);
         }
         if (tileCache.type == 597)
         {
             num = -1;
         }
         else if ((tileCache.type >= 358 && tileCache.type <= 364) || (tileCache.type >= 275 && tileCache.type <= 282) || tileCache.type == 285 || tileCache.type == 286 || (tileCache.type >= 288 && tileCache.type <= 297) || (tileCache.type >= 316 && tileCache.type <= 318) || tileCache.type == 298 || tileCache.type == 299 || tileCache.type == 309 || tileCache.type == 310 || tileCache.type == 339 || tileCache.type == 538 || tileCache.type == 413 || tileCache.type == 414 || tileCache.type == 505 || tileCache.type == 521 || tileCache.type == 522 || tileCache.type == 523 || tileCache.type == 524 || tileCache.type == 525 || tileCache.type == 526 || tileCache.type == 527 || tileCache.type == 532 || tileCache.type == 543 || tileCache.type == 544 || tileCache.type == 550 || tileCache.type == 551 || tileCache.type == 533 || tileCache.type == 553 || tileCache.type == 554 || tileCache.type == 555 || tileCache.type == 556 || tileCache.type == 558 || tileCache.type == 559 || tileCache.type == 542 || tileCache.type == 391 || tileCache.type == 394 || tileCache.type == 392 || tileCache.type == 393 || tileCache.type == 568 || tileCache.type == 569 || tileCache.type == 570 || tileCache.type == 582 || tileCache.type == 580 || tileCache.type == 598 || tileCache.type == 599 || tileCache.type == 600 || tileCache.type == 601 || tileCache.type == 602 || tileCache.type == 603 || tileCache.type == 604 || tileCache.type == 605 || tileCache.type == 606 || tileCache.type == 607 || tileCache.type == 608 || tileCache.type == 609 || tileCache.type == 610 || tileCache.type == 611 || tileCache.type == 612 || tileCache.type == 619 || tileCache.type == 620 || tileCache.type == 629 || tileCache.type == 632 || tileCache.type == 640 || tileCache.type == 643 || tileCache.type == 644 || tileCache.type == 645)
         {
             num = 13;
             if (genRand.Next(3) != 0)
             {
                 num = -1;
             }
         }
         if (tileCache.type == 13)
         {
             num = ((tileCache.frameX < 90) ? 13 : (-1));
         }
         if (tileCache.type == 189)
         {
             num = 16;
         }
         if (tileCache.type == 460)
         {
             num = 16;
         }
         if (tileCache.type == 530)
         {
             num = Main.tile[i, j + 2 - tileCache.frameY / 18].type switch
             {
                 116 => 47,
                 234 => 125,
                 112 => 17,
                 _ => (tileCache.frameX >= 270) ? 291 : 40,
             };
         }
         if (tileCache.type == 518)
         {
             if (tileCache.frameY == 0)
             {
                 num = 3;
             }
             else if (tileCache.frameY == 18)
             {
                 num = 47;
             }
             else if (tileCache.frameY == 36)
             {
                 num = 40;
             }
         }
         else if (tileCache.type == 519)
         {
             if (tileCache.frameY == 0)
             {
                 num = 3;
             }
             else if (tileCache.frameY == 18)
             {
                 num = 40;
             }
             else if (tileCache.frameY == 36)
             {
                 num = 47;
             }
             else if (tileCache.frameY == 54)
             {
                 num = 125;
             }
             else if (tileCache.frameY == 72)
             {
                 num = 17;
             }
             else if (tileCache.frameY == 90)
             {
                 num = 26;
             }
         }
         else if (tileCache.type == 636)
         {
             num = 17;
         }
         else if (tileCache.type == 528)
         {
             num = 26;
         }
         if (tileCache.type == 12)
         {
             num = 12;
         }
         if (tileCache.type == 639)
         {
             num = 48;
         }
         if (tileCache.type == 3 || tileCache.type == 73)
         {
             num = 3;
         }
         if (tileCache.type == 54)
         {
             num = 13;
         }
         if (tileCache.type == 22 || tileCache.type == 140)
         {
             num = 14;
         }
         if (tileCache.type == 78)
         {
             num = 22;
         }
         if (tileCache.type == 28 || tileCache.type == 653)
         {
             num = 22;
             if (tileCache.frameY >= 72 && tileCache.frameY <= 90)
             {
                 num = 1;
             }
             if (tileCache.frameY >= 144 && tileCache.frameY <= 234)
             {
                 num = 48;
             }
             if (tileCache.frameY >= 252 && tileCache.frameY <= 358)
             {
                 num = 85;
             }
             if (tileCache.frameY >= 360 && tileCache.frameY <= 466)
             {
                 num = 26;
             }
             if (tileCache.frameY >= 468 && tileCache.frameY <= 574)
             {
                 num = 36;
             }
             if (tileCache.frameY >= 576 && tileCache.frameY <= 790)
             {
                 num = 18;
             }
             if (tileCache.frameY >= 792 && tileCache.frameY <= 898)
             {
                 num = 5;
             }
             if (tileCache.frameY >= 900 && tileCache.frameY <= 1006)
             {
                 num = 0;
             }
             if (tileCache.frameY >= 1008 && tileCache.frameY <= 1114)
             {
                 num = 148;
             }
             if (tileCache.frameY >= 1116 && tileCache.frameY <= 1222)
             {
                 num = 241;
             }
             if (tileCache.frameY >= 1224 && tileCache.frameY <= 1330)
             {
                 num = 287;
             }
         }
         if (tileCache.type == 163)
         {
             num = 118;
         }
         if (tileCache.type == 164)
         {
             num = 119;
         }
         if (tileCache.type == 200)
         {
             num = 120;
         }
         if (tileCache.type == 221 || tileCache.type == 248)
         {
             num = 144;
         }
         if (tileCache.type == 222 || tileCache.type == 249)
         {
             num = 145;
         }
         if (tileCache.type == 223 || tileCache.type == 250)
         {
             num = 146;
         }
         if (tileCache.type == 224)
         {
             num = 149;
         }
         if (tileCache.type == 225)
         {
             num = 147;
         }
         if (tileCache.type == 229)
         {
             num = 153;
         }
         if (tileCache.type == 231)
         {
             num = 153;
             if (genRand.Next(3) == 0)
             {
                 num = 26;
             }
         }
         if (tileCache.type == 226)
         {
             num = 148;
         }
         if (tileCache.type == 103)
         {
             num = -1;
         }
         if (tileCache.type == 29)
         {
             num = 23;
         }
         if (tileCache.type == 40)
         {
             num = 28;
         }
         if (tileCache.type == 50)
         {
             num = 22;
         }
         if (tileCache.type == 51)
         {
             num = 30;
         }
         if (tileCache.type == 52 || tileCache.type == 353)
         {
             num = 3;
         }
         if (tileCache.type == 53 || tileCache.type == 81 || tileCache.type == 151 || tileCache.type == 202 || tileCache.type == 274 || tileCache.type == 495)
         {
             num = 32;
         }
         if (tileCache.type == 56 || tileCache.type == 152)
         {
             num = 37;
         }
         if (tileCache.type == 75 || tileCache.type == 683)
         {
             num = 109;
         }
         if (tileCache.type == 57 || tileCache.type == 119 || tileCache.type == 141 || tileCache.type == 234 || tileCache.type == 635 || tileCache.type == 654)
         {
             num = 36;
         }
         if (tileCache.type == 59 || tileCache.type == 120)
         {
             num = 38;
         }
         if (tileCache.type == 61 || tileCache.type == 62 || tileCache.type == 74 || tileCache.type == 80 || tileCache.type == 188 || tileCache.type == 233 || tileCache.type == 236 || tileCache.type == 384 || tileCache.type == 652 || tileCache.type == 651)
         {
             num = 40;
         }
         if (tileCache.type == 485)
         {
             num = 32;
         }
         if (tileCache.type == 238)
         {
             num = ((genRand.Next(3) != 0) ? 166 : 167);
         }
         if (tileCache.type == 69)
         {
             num = 7;
         }
         if (tileCache.type == 655)
         {
             num = 166;
         }
         if (tileCache.type == 71 || tileCache.type == 72 || tileCache.type == 190 || tileCache.type == 578)
         {
             num = 26;
         }
         if (tileCache.type == 70)
         {
             num = 17;
         }
         if (tileCache.type == 112)
         {
             num = 14;
         }
         if (tileCache.type == 123)
         {
             num = 53;
         }
         if (tileCache.type == 161)
         {
             num = 80;
         }
         if (tileCache.type == 206)
         {
             num = 80;
         }
         if (tileCache.type == 162)
         {
             num = 80;
         }
         if (tileCache.type == 165)
         {
             num = (tileCache.frameX / 54) switch
             {
                 0 => 80,
                 1 => 1,
                 2 => 30,
                 3 => 147,
                 4 => 1,
                 5 => 14,
                 6 => 117,
                 7 => 250,
                 8 => 240,
                 9 => 236,
                 _ => 1,
             };
         }
         if (tileCache.type == 666)
         {
             num = 322;
         }
         if (tileCache.type == 193)
         {
             num = 4;
         }
         if (tileCache.type == 194)
         {
             num = 26;
         }
         if (tileCache.type == 195)
         {
             num = 5;
         }
         if (tileCache.type == 196)
         {
             num = 108;
         }
         if (tileCache.type == 460)
         {
             num = 108;
         }
         if (tileCache.type == 197)
         {
             num = 4;
         }
         if (tileCache.type == 153)
         {
             num = 26;
         }
         if (tileCache.type == 154)
         {
             num = 32;
         }
         if (tileCache.type == 155)
         {
             num = 2;
         }
         if (tileCache.type == 156)
         {
             num = 1;
         }
         if (tileCache.type == 116 || tileCache.type == 118 || tileCache.type == 147 || tileCache.type == 148)
         {
             num = 51;
         }
         if (tileCache.type == 109 || tileCache.type == 492)
         {
             num = ((genRand.Next(2) != 0) ? 47 : 0);
         }
         if (tileCache.type == 110 || tileCache.type == 113 || tileCache.type == 115)
         {
             num = 47;
         }
         if (tileCache.type == 107 || tileCache.type == 121 || tileCache.type == 685)
         {
             num = 48;
         }
         if (tileCache.type == 108 || tileCache.type == 122 || tileCache.type == 146 || tileCache.type == 686)
         {
             num = 49;
         }
         if (tileCache.type == 111 || tileCache.type == 145 || tileCache.type == 150)
         {
             num = 50;
         }
         if (tileCache.type == 133)
         {
             num = 50;
             if (tileCache.frameX >= 54)
             {
                 num = 146;
             }
         }
         if (tileCache.type == 134)
         {
             num = 49;
             if (tileCache.frameX >= 36)
             {
                 num = 145;
             }
         }
         if (tileCache.type == 149)
         {
             num = 49;
         }
         if (Main.tileAlch[tileCache.type])
         {
             int num16 = tileCache.frameX / 18;
             if (num16 == 0)
             {
                 num = 3;
             }
             if (num16 == 1)
             {
                 num = 3;
             }
             if (num16 == 2)
             {
                 num = 7;
             }
             if (num16 == 3)
             {
                 num = 17;
             }
             if (num16 == 4)
             {
                 num = 289;
             }
             if (num16 == 5)
             {
                 num = 6;
             }
             if (num16 == 6)
             {
                 num = 224;
             }
         }
         if (tileCache.type == 58 || tileCache.type == 76 || tileCache.type == 77 || tileCache.type == 684)
         {
             num = ((genRand.Next(2) != 0) ? 25 : 6);
         }
         if (tileCache.type == 37)
         {
             num = ((genRand.Next(2) != 0) ? 23 : 6);
         }
         if (tileCache.type == 32)
         {
             num = ((genRand.Next(2) != 0) ? 24 : 14);
         }
         if (tileCache.type == 352)
         {
             num = ((genRand.Next(3) != 0) ? 125 : 5);
         }
         if (tileCache.type == 23 || tileCache.type == 24 || tileCache.type == 661)
         {
             num = ((genRand.Next(2) != 0) ? 17 : 14);
         }
         if (tileCache.type == 25 || tileCache.type == 31)
         {
             num = ((tileCache.type == 31 && tileCache.frameX >= 36) ? 5 : ((genRand.Next(2) != 0) ? 1 : 14));
         }
         if (tileCache.type == 20)
         {
             num = (tileCache.frameX / 54) switch
             {
                 1 => 122,
                 2 => 78,
                 3 => 77,
                 4 => 121,
                 5 => 79,
                 _ => 7,
             };
         }
         if (tileCache.type == 27)
         {
             num = ((genRand.Next(2) != 0) ? 19 : 3);
         }
         if (tileCache.type == 129)
         {
             if (tileCache.frameX >= 324)
             {
                 num = 69;
             }
             num = ((tileCache.frameX != 0 && tileCache.frameX != 54 && tileCache.frameX != 108) ? ((tileCache.frameX != 18 && tileCache.frameX != 72 && tileCache.frameX != 126) ? 70 : 69) : 68);
         }
         if (tileCache.type == 385)
         {
             num = genRand.Next(68, 71);
         }
         if (tileCache.type == 4)
         {
             int num17 = (int)MathHelper.Clamp(tileCache.frameY / 22, 0f, TorchID.Count - 1);
             num = TorchID.Dust[num17];
         }
         if (tileCache.type == 35)
         {
             num = 189;
             if (tileCache.frameX < 36 && genRand.Next(2) == 0)
             {
                 num = 6;
             }
         }
         if ((tileCache.type == 34 || tileCache.type == 42) && genRand.Next(2) == 0)
         {
             num = 6;
         }
         if (tileCache.type == 270)
         {
             num = -1;
         }
         if (tileCache.type == 271)
         {
             num = -1;
         }
         if (tileCache.type == 581)
         {
             num = -1;
         }
         if (tileCache.type == 660)
         {
             num = -1;
         }
         if (tileCache.type == 79 || tileCache.type == 90 || tileCache.type == 101)
         {
             num = -1;
         }
         if (tileCache.type == 33 || tileCache.type == 34 || tileCache.type == 42 || tileCache.type == 93 || tileCache.type == 100)
         {
             num = -1;
         }
         if (tileCache.type == 321 || tileCache.type == 574)
         {
             num = 214;
         }
         if (tileCache.type == 322)
         {
             num = 215;
         }
         if (tileCache.type == 635)
         {
             num = 36;
         }
         bool flag = tileCache.type == 178 || tileCache.type == 440;
         ushort type = tileCache.type;
         if (type == 178 || (uint)(type - 426) <= 1u || (uint)(type - 430) <= 10u)
         {
             flag = true;
         }
         if (num >= 0)
         {
             if (tileCache.type == 627 || tileCache.type == 628 || (tileCache.type == 184 && tileCache.frameX / 22 == 10))
             {
                 int num18 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, num, 0f, 0f, 0, new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB));
                 Main.dust[num18].noGravity = true;
                 Main.dust[num18].noLightEmittence = true;
                 return num18;
             }
             if (tileCache.type == 518)
             {
                 int num19 = tileCache.liquid / 16;
                 num19 -= 3;
                 if (SolidTile(i, j - 1) && num19 > 8)
                 {
                     num19 = 8;
                 }
                 return Dust.NewDust(new Vector2(i * 16, j * 16 - num19), 16, 16, num);
             }
             if (tileCache.type == 352 && num == 5)
             {
                 int num20 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 5, 0f, 0f, 100);
                 Main.dust[num20].scale = 1.5f;
                 Main.dust[num20].noGravity = true;
                 Main.dust[num20].velocity *= 1.65f;
                 Main.dust[num20].fadeIn = 1.6f;
                 return num20;
             }
             if (tileCache.type == 160 || tileCache.type == 692)
             {
                 int num21 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 66, 0f, 0f, 100, new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB), 0.75f);
                 Main.dust[num21].noGravity = true;
                 return num21;
             }
             if (tileCache.type == 323)
             {
                 int frameY = tileCache.frameY;
                 return Dust.NewDust(new Vector2(i * 16 + frameY, j * 16), 16, 16, num);
             }
             if (tileCache.type == 314)
             {
                 int num22 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, 213, genRand.Next(-2, 3), genRand.Next(-2, 3));
                 Main.dust[num22].noGravity = true;
                 Main.dust[num22].fadeIn = Main.dust[num22].scale + 1f + 0.01f * (float)genRand.Next(0, 51);
                 Main.dust[num22].noGravity = true;
                 return num22;
             }
             if (flag)
             {
                 int num23 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, num, 0f, 0f, 75, default(Color), 0.75f);
                 Main.dust[num23].noLight = true;
                 return num23;
             }
             if (tileCache.type == 193 || (tileCache.type == 18 && num == 4) || (tileCache.type == 19 && num == 4))
             {
                 return Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, num, 0f, 0f, 75, new Color(0, 80, 255, 100), 0.75f);
             }
             if (tileCache.type == 197)
             {
                 return Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, num, 0f, 0f, 75, new Color(97, 200, 255, 100), 0.75f);
             }
             if (tileCache.type == 185 && num >= 86 && num <= 91)
             {
                 int num24 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, num, 0f, 0f, 75, default(Color), 0.75f);
                 Main.dust[num24].noLight = true;
                 return num24;
             }
             if (tileCache.type == 4 && num == 66)
             {
                 int num25 = Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, num, 0f, 0f, 0, new Color((float)Main.DiscoR / 255f, (float)Main.DiscoG / 255f, (float)Main.DiscoB / 255f));
                 Main.dust[num25].noGravity = true;
                 return num25;
             }
             if (num == 139)
             {
                 int type2 = num + Main.rand.Next(4);
                 return Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, type2);
             }
             return Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, num);
         }
         return 6000;
     }
References Tile.active(), Color, TorchID.Count, Main.DiscoB, Main.DiscoG, Main.DiscoR, TorchID.Dust, Main.dust, Dust.fadeIn, Tile.frameX, Tile.frameY, Tile.liquid, Main.maxTilesX, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Main.rand, Dust.scale, SolidTile, Main.tile, Main.tileAlch, Main.tileMoss, Main.tileSolid, Main.tileStone, Tile.type, and Dust.velocity.
Referenced by NPC.AI_110_Betsy(), Projectile.AI_135_OgreStomp(), Projectile.CreateGroundExplosion(), Projectile.CreateImpactExplosion(), Mount.EmitGolfCartWheelDust(), Player.MowGrassTile(), and Player.PlaceThing_TryReplacingTiles().