Terraria: WorldGen.ExplodeMine
ExplodeMine()
static void WorldGen.ExplodeMine (int i, int j, bool fromWiring) inline static
     {
         _ = Main.tile[i, j].type;
         KillTile(i, j, fail: false, effectOnly: false, noItem: true);
         NetMessage.SendTileSquare(-1, i, j);
         Projectile.NewProjectile(GetProjectileSource_PlayerOrWires(i, j, fromWiring, Main.LocalPlayer), i * 16 + 8, j * 16 + 8, 0f, 0f, 164, 250, 10f, Main.myPlayer);
     }
References Main.LocalPlayer, Main.myPlayer, Projectile.NewProjectile(), NetMessage.SendTileSquare(), Main.tile, and Tile.type.
Referenced by Wiring.HitWireSingle(), and Collision.SwitchTiles().