Terraria: WorldGen.FinishNotTheBees
FinishNotTheBees()
static void WorldGen.FinishNotTheBees () inline static private
     {
         if (!notTheBees)
         {
             return;
         }
         int num = 0;
         for (int i = 20; (double)i < Main.worldSurface; i++)
         {
             for (int j = 20; j < Main.maxTilesX - 20; j++)
             {
                 if (Main.tile[j, i].active() && TileID.Sets.Clouds[Main.tile[j, i].type])
                 {
                     num = i;
                     break;
                 }
             }
         }
         for (int k = 25; k < Main.maxTilesX - 25; k++)
         {
             for (int l = 25; l < Main.maxTilesY - 25; l++)
             {
                 if (Main.tile[k, l].type == 571)
                 {
                     TileFrame(k, l);
                 }
                 int num2 = 20;
                 if (remixWorldGen)
                 {
                     num2 = 10;
                 }
                 if (Main.tile[k, l].type == 25 || (remixWorldGen && Main.tile[k, l].type == 23 && (double)l < Main.worldSurface))
                 {
                     for (int m = k - num2; m <= k + num2; m++)
                     {
                         for (int n = l - num2; n <= l + num2; n++)
{
                             if (Main.tile[m, n].type == 60)
{
                                 if (Main.tile[m, n + 1].type == 444)
{
                                     KillTile(m, n + 1);
                                 }
                                 Main.tile[m, n].type = 661;
                                 if (Main.tile[m, n - 1].type == 61 || Main.tile[m, n - 1].type == 74)
{
                                     Main.tile[m, n - 1].active(active: false);
                                     PlaceTile(m, n - 1, 24);
                                 }
                             }
                             else if (Main.tile[m, n - 1].type == 233 || Main.tile[m, n - 1].type == 82)
{
                                 KillTile(m, n - 1);
                             }
                         }
                     }
                 }
                 else if (Main.tile[k, l].type == 203 || (remixWorldGen && Main.tile[k, l].type == 199 && (double)l < Main.worldSurface))
                 {
                     for (int num3 = k - num2; num3 <= k + num2; num3++)
                     {
                         for (int num4 = l - num2; num4 <= l + num2; num4++)
{
                             if (Main.tile[num3, num4].type == 60)
{
                                 if (Main.tile[num3, num4 + 1].type == 444)
{
                                     KillTile(num3, num4 + 1);
                                 }
                                 Main.tile[num3, num4].type = 662;
                                 if (Main.tile[num3, num4 - 1].type == 61 || Main.tile[num3, num4 - 1].type == 74)
{
                                     Main.tile[num3, num4 - 1].active(active: false);
                                     PlaceTile(num3, num4 - 1, 201);
                                 }
                                 else if (Main.tile[num3, num4 - 1].type == 233 || Main.tile[num3, num4 - 1].type == 82)
{
                                     KillTile(num3, num4 - 1);
                                 }
                             }
                         }
                     }
                 }
                 if (Main.tile[k, l].type == 382 || Main.tile[k, l].type == 52)
                 {
                     Main.tile[k, l].type = 62;
                 }
                 if (l > GenVars.lavaLine + genRand.Next(-2, 3) + 2)
                 {
                     if (!remixWorldGen)
                     {
                         SpreadGrass(k, l, 59, 70);
                     }
                 }
                 else
                 {
                     SpreadGrass(k, l, 59, 60);
                 }
                 if ((double)l > Main.rockLayer + 20.0 + (double)genRand.Next(-2, 3) && l <= GenVars.lavaLine + 2 - 20 - genRand.Next(-2, 3) && (k < beachDistance + 200 - 20 - genRand.Next(-2, 3) || k > Main.maxTilesX - beachDistance - 200 + 20 + genRand.Next(-2, 3)))
                 {
                     if (Main.tile[k, l].liquid > 0)
                     {
                         Main.tile[k, l].honey(honey: false);
                         Main.tile[k, l].lava(lava: false);
                     }
                     if (Main.tile[k, l].type == 59)
                     {
                         bool flag = false;
                         for (int num5 = k - 1; num5 <= k + 1; num5++)
{
                             for (int num6 = l - 1; num6 <= l + 1; num6++)
{
                                 if (Main.tile[num5, num6].type == 60)
{
                                     flag = true;
                                 }
                             }
                         }
                         if (!flag)
{
                             if ((double)l < (Main.rockLayer + (double)GenVars.lavaLine) / 2.0)
{
                                 Main.tile[k, l].type = 161;
                             }
                             else
{
                                 Main.tile[k, l].type = 147;
                             }
                         }
                     }
                 }
                 if (!remixWorldGen)
                 {
                     if ((Main.tile[k, l].type == 7 || Main.tile[k, l].type == 166 || Main.tile[k, l].type == 6 || Main.tile[k, l].type == 167) && (double)l > ((double)GenVars.lavaLine + Main.rockLayer * 2.0) / 3.0 + (double)genRand.Next(-2, 3) + 2.0)
                     {
                         Main.tile[k, l].type = 0;
                     }
                 }
                 else if (!remixWorldGen && (Main.tile[k, l].type == 123 || Main.tile[k, l].type == 40) && (double)l > ((double)GenVars.lavaLine + Main.rockLayer) / 2.0 + (double)genRand.Next(-2, 3) + 2.0)
                 {
                     Main.tile[k, l].type = 1;
                 }
                 if (l <= num || (Main.tile[k, l].liquid != 0 && (Main.tile[k, l].lava() || Main.tile[k, l].shimmer())))
                 {
                     continue;
                 }
                 if (getGoodWorldGen)
                 {
                     if (genRand.Next(150) == 0)
                     {
                         PlaceTile(k, l, 231, mute: true);
                     }
                 }
                 else if (genRand.Next(25) == 0)
                 {
                     PlaceTile(k, l, 231, mute: true);
                 }
             }
         }
         for (int num7 = 20; num7 < num; num7++)
         {
             for (int num8 = 20; num8 <= Main.maxTilesX - 20; num8++)
             {
                 Main.tile[num8, num7].honey(honey: false);
                 if (Main.tile[num8, num7].type == 375)
                 {
                     Main.tile[num8, num7].type = 373;
                 }
                 if (!remixWorldGen)
                 {
                     if (Main.tile[num8, num7].type == 60)
                     {
                         Main.tile[num8, num7].type = 2;
                         if (genRand.Next(2) == 0)
{
                             GrowTreeWithSettings(num8, num7, GrowTreeSettings.Profiles.VanityTree_Willow);
                         }
                         else
{
                             GrowTreeWithSettings(num8, num7, GrowTreeSettings.Profiles.VanityTree_Sakura);
                         }
                         if (!Main.tile[num8, num7 - 1].active())
{
                             PlaceTile(num8, num7 - 1, 3);
                         }
                     }
                     if (Main.tile[num8, num7].type == 59)
                     {
                         Main.tile[num8, num7].type = 0;
                     }
                 }
                 else
                 {
                     GrowTree(num8, num7);
                 }
             }
         }
     }
References Tile.active(), TileID.Sets.Clouds, Tile.honey(), Tile.lava(), GenVars.lavaLine, Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.rockLayer, Tile.shimmer(), Main.tile, Tile.type, WorldGen.GrowTreeSettings.Profiles.VanityTree_Sakura, WorldGen.GrowTreeSettings.Profiles.VanityTree_Willow, and Main.worldSurface.