Terraria: WorldGen.UpdateWorld
UpdateWorld()
static void WorldGen.UpdateWorld () inline static
     {
         if (gen)
         {
             return;
         }
         AllowedToSpreadInfections = true;
         CreativePowers.StopBiomeSpreadPower power = CreativePowerManager.Instance.GetPower<CreativePowers.StopBiomeSpreadPower>();
         if (power != null && power.GetIsUnlocked())
         {
             AllowedToSpreadInfections = !power.Enabled;
         }
         int wallDist = 3;
         Wiring.UpdateMech();
         TileEntity.UpdateStart();
         foreach (TileEntity value in TileEntity.ByID.Values)
         {
             value.Update();
         }
         TileEntity.UpdateEnd();
         UpdateLunarApocalypse();
         if (Main.netMode != 1)
         {
             totalD++;
             if (totalD >= 30)
             {
                 totalD = 0;
                 CountTiles(totalX);
                 totalX++;
                 if (totalX >= Main.maxTilesX)
                 {
                     totalX = 0;
                 }
             }
         }
         Liquid.skipCount++;
         if (Liquid.skipCount > 1)
         {
             Liquid.UpdateLiquid();
             Liquid.skipCount = 0;
         }
         int worldUpdateRate = GetWorldUpdateRate();
         if (worldUpdateRate == 0)
         {
             return;
         }
         double num = 3E-05f * (float)worldUpdateRate;
         double num2 = 1.5E-05f * (float)worldUpdateRate;
         double num3 = 2.5E-05f * (float)worldUpdateRate;
         bool checkNPCSpawns = false;
         spawnDelay++;
         if (Main.invasionType > 0 || Main.eclipse)
         {
             spawnDelay = 0;
         }
         if (spawnDelay >= 20)
         {
             checkNPCSpawns = true;
             spawnDelay = 0;
             if (prioritizedTownNPCType != 37)
             {
                 for (int i = 0; i < 200; i++)
                 {
                     if (Main.npc[i].active && Main.npc[i].homeless && Main.npc[i].townNPC && Main.npc[i].type != 368)
                     {
                         prioritizedTownNPCType = Main.npc[i].type;
                         break;
                     }
                 }
             }
         }
         double num4 = (double)(Main.maxTilesX * Main.maxTilesY) * num;
         int num5 = 151;
         int num6 = (int)Utils.Lerp(num5, (double)num5 * 2.8, Utils.Clamp((double)Main.maxTilesX / 4200.0 - 1.0, 0.0, 1.0));
         for (int j = 0; (double)j < num4; j++)
         {
             if (Main.rand.Next(num6 * 100) == 0)
             {
                 PlantAlch();
             }
             int i2 = genRand.Next(10, Main.maxTilesX - 10);
             int j2 = genRand.Next(10, (int)Main.worldSurface - 1);
             UpdateWorld_OvergroundTile(i2, j2, checkNPCSpawns, wallDist);
         }
         if (Main.remixWorld)
         {
             for (int k = 0; (double)k < (double)(Main.maxTilesX * Main.maxTilesY) * num3; k++)
             {
                 int i3 = genRand.Next(10, Main.maxTilesX - 10);
                 int j3 = genRand.Next((int)Main.worldSurface - 1, Main.maxTilesY - 20);
                 growGrassUnderground = true;
                 UpdateWorld_UndergroundTile(i3, j3, checkNPCSpawns, wallDist);
                 UpdateWorld_OvergroundTile(i3, j3, checkNPCSpawns, wallDist);
                 growGrassUnderground = false;
             }
         }
         else
         {
             for (int l = 0; (double)l < (double)(Main.maxTilesX * Main.maxTilesY) * num2; l++)
             {
                 int i4 = genRand.Next(10, Main.maxTilesX - 10);
                 int j4 = genRand.Next((int)Main.worldSurface - 1, Main.maxTilesY - 20);
                 UpdateWorld_UndergroundTile(i4, j4, checkNPCSpawns, wallDist);
             }
         }
         if (Main.dayTime && !Main.remixWorld)
         {
             return;
         }
         for (int m = 0; m < Main.dayRate; m++)
         {
             double num7 = (double)Main.maxTilesX / 4200.0;
             num7 *= (double)Star.starfallBoost;
             if (!((double)Main.rand.Next(8000) < 10.0 * num7))
             {
                 continue;
             }
             int num8 = 12;
             int num9 = Main.rand.Next(Main.maxTilesX - 50) + 100;
             num9 *= 16;
             int num10 = Main.rand.Next((int)((double)Main.maxTilesY * 0.05));
             num10 *= 16;
             Vector2 position = new Vector2(num9, num10);
             int num11 = -1;
             if (Main.expertMode && Main.rand.Next(15) == 0)
             {
                 int num12 = Player.FindClosest(position, 1, 1);
                 if ((double)Main.player[num12].position.Y < Main.worldSurface * 16.0 && Main.player[num12].afkCounter < 3600)
                 {
                     int num13 = Main.rand.Next(1, 640);
                     position.X = Main.player[num12].position.X + (float)Main.rand.Next(-num13, num13 + 1);
                     num11 = num12;
                 }
             }
             if (!Collision.SolidCollision(position, 16, 16))
             {
                 float num14 = Main.rand.Next(-100, 101);
                 float num15 = Main.rand.Next(200) + 100;
                 float num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
                 num16 = (float)num8 / num16;
                 num14 *= num16;
                 num15 *= num16;
                 Projectile.NewProjectile(new EntitySource_ByProjectileSourceId(11), position.X, position.Y, num14, num15, 720, 0, 0f, Main.myPlayer, 0f, num11);
             }
         }
     }
References Entity.active, Player.afkCounter, TileEntity.ByID, Main.dayRate, Main.dayTime, E, Main.eclipse, CreativePowers.ASharedTogglePower.Enabled, Main.expertMode, Player.FindClosest(), NPC.homeless, CreativePowerManager.Instance, Main.invasionType, Utils.Lerp(), Liquid, Main.maxTilesX, Main.maxTilesY, Main.myPlayer, Main.netMode, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.npc, Main.player, Entity.position, Main.rand, Main.remixWorld, Collision.SolidCollision(), Star.starfallBoost, NPC.townNPC, NPC.type, TileEntity.Update(), TileEntity.UpdateEnd(), Wiring.UpdateMech(), TileEntity.UpdateStart(), and Main.worldSurface.
Referenced by Main.DoUpdateInWorld().