Terraria: WorldGen.RandomizeBackgroundBasedOnPlayer
RandomizeBackgroundBasedOnPlayer()
static void WorldGen.RandomizeBackgroundBasedOnPlayer (UnifiedRandom random, Player player) inline static
     {
         if (player.ZoneGlowshroom)
         {
             int num = mushroomBG;
             while (num == mushroomBG)
             {
                 setBG(8, random.Next(4));
             }
         }
         else if (player.ZoneUnderworldHeight)
         {
             int num = underworldBG;
             while (num == underworldBG)
             {
                 setBG(9, random.Next(3));
             }
         }
         else if (player.ZoneDesert)
         {
             int num = desertBG;
             while (num == desertBG)
             {
                 setBG(6, random.Next(5));
             }
         }
         else if (player.ZoneHallow)
         {
             int num = hallowBG;
             while (num == hallowBG)
             {
                 setBG(4, random.Next(5));
             }
         }
         else if (player.ZoneCorrupt)
         {
             int num = corruptBG;
             while (num == corruptBG)
             {
                 setBG(1, random.Next(5));
             }
         }
         else if (player.ZoneCrimson)
         {
             int num = crimsonBG;
             while (num == crimsonBG)
             {
                 setBG(5, random.Next(6));
             }
         }
         else if (player.ZoneJungle)
         {
             int num = jungleBG;
             while (num == jungleBG)
             {
                 setBG(2, random.Next(6));
             }
         }
         else if (player.ZoneSnow)
         {
             int num = snowBG;
             while (num == snowBG)
             {
                 snowBG = random.Next(8);
                 if (snowBG == 2 && random.Next(2) == 0)
                 {
                     if (random.Next(2) == 0)
                     {
                         snowBG = 21;
                     }
                     else
                     {
                         snowBG = 22;
                     }
                 }
                 if (snowBG == 3 && random.Next(2) == 0)
                 {
                     if (random.Next(2) == 0)
                     {
                         snowBG = 31;
                     }
                     else
                     {
                         snowBG = 32;
                     }
                 }
                 if (snowBG == 4 && random.Next(2) == 0)
                 {
                     if (random.Next(2) == 0)
                     {
                         snowBG = 41;
                     }
                     else
                     {
                         snowBG = 42;
                     }
                 }
                 setBG(3, snowBG);
             }
         }
         else if (player.ZoneBeach)
         {
             int num = oceanBG;
             while (num == oceanBG)
             {
                 setBG(7, random.Next(6));
             }
         }
         else
         {
             int num2 = (int)(player.Center.X / 16f);
             if (num2 < Main.treeX[0])
             {
                 int num = treeBG1;
                 while (IsBackgroundConsideredTheSame(num, treeBG1))
                 {
                     treeBG1 = RollRandomForestBGStyle(random);
                 }
                 setBG(0, treeBG1);
             }
             else if (num2 < Main.treeX[1])
             {
                 int num = treeBG2;
                 while (IsBackgroundConsideredTheSame(num, treeBG2))
                 {
                     treeBG2 = RollRandomForestBGStyle(random);
                 }
                 setBG(10, treeBG2);
             }
             else if (num2 < Main.treeX[2])
             {
                 int num = treeBG3;
                 while (IsBackgroundConsideredTheSame(num, treeBG3))
                 {
                     treeBG3 = RollRandomForestBGStyle(random);
                 }
                 setBG(11, treeBG3);
             }
             else
             {
                 int num = treeBG4;
                 while (IsBackgroundConsideredTheSame(num, treeBG4))
                 {
                     treeBG4 = RollRandomForestBGStyle(random);
                 }
                 setBG(12, treeBG4);
             }
         }
         BackgroundsCache.UpdateCache();
     }
References BackgroundsCache, Entity.Center, corruptBG, crimsonBG, desertBG, hallowBG, IsBackgroundConsideredTheSame(), jungleBG, mushroomBG, UnifiedRandom.Next(), oceanBG, RollRandomForestBGStyle(), setBG(), snowBG, treeBG1, treeBG2, treeBG3, treeBG4, Main.treeX, underworldBG, BackgroundChangeFlashInfo.UpdateCache(), Player.ZoneBeach, Player.ZoneCorrupt, Player.ZoneCrimson, Player.ZoneDesert, Player.ZoneGlowshroom, Player.ZoneHallow, Player.ZoneJungle, Player.ZoneSnow, and Player.ZoneUnderworldHeight.
Referenced by Projectile.Kill().