Terraria: WorldGen.PlaceOasis
PlaceOasis()
static bool WorldGen.PlaceOasis (int X, int Y) inline static
     {
         //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
         //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
         int i = Y;
         if (!Main.tile[X, i].active() && Main.tile[X, i].wall == 0)
         {
             for (; !Main.tile[X, i].active() && Main.tile[X, i].wall == 0 && (double)i <= Main.worldSurface; i++)
             {
             }
             if ((double)i > Main.worldSurface - 10.0)
             {
                 return false;
             }
             if (Main.tile[X, i].type != 53)
             {
                 return false;
             }
             int num = 350;
             for (int j = 0; j < GenVars.numOasis; j++)
             {
                 if (Vector2D.Distance(GenVars.oasisPosition[j].ToVector2D(), new Vector2D((double)X, (double)i)) < (double)num)
                 {
                     return false;
                 }
             }
             int num2 = genRand.Next(45, 61);
             int oasisHeight = GenVars.oasisHeight;
             int num3 = num2 + 50;
             int num4 = 4;
             for (int k = X - num3; k <= X + num3; k++)
             {
                 for (int l = i - oasisHeight; l <= i + oasisHeight + num4; l++)
                 {
                     Tile tile = Main.tile[k, l];
                     if (tile.active())
                     {
                         if (Main.tileSolid[tile.type])
{
                             if ((tile.type == 151 || tile.type == 397) && Math.Abs(k - X) < num2 && Math.Abs(l - i) < oasisHeight / 2)
{
                                 return false;
                             }
                             if (tile.type != 53)
{
                                 return false;
                             }
                         }
                     }
                     else if ((tile.liquid > 0 || tile.wall > 0) && Math.Abs(k - X) < num2 && Math.Abs(l - i) < oasisHeight / 2)
                     {
                         return false;
                     }
                 }
                 if (k > X - num2 / 2 && k < X - num2 / 2)
                 {
                     if (Main.tile[k, i - 6].active())
                     {
                         return false;
                     }
                     if (!Main.tile[k, i + 1].active())
                     {
                         return false;
                     }
                 }
             }
             int num5 = 5;
             int num6 = i;
             while (!Main.tile[X - num2, i + num5].active() || Main.tile[X - num2, i + num5].wall != 0 || !Main.tile[X + num2, i + num5].active() || Main.tile[X + num2, i + num5].wall != 0)
             {
                 i++;
                 if (i - num6 > 20)
                 {
                     break;
                 }
             }
             int num7 = num2 / 2;
             int num8 = X - num2 * 3;
             int num9 = X + num2 * 3;
             int num10 = i - oasisHeight * 4;
             int num11 = i + oasisHeight * 3;
             if (num8 < 0)
             {
                 num8 = 0;
             }
             if (num9 > Main.maxTilesX)
             {
                 num9 = Main.maxTilesX;
             }
             if (num10 < 0)
             {
                 num10 = 0;
             }
             if (num11 > Main.maxTilesY)
             {
                 num11 = Main.maxTilesY;
             }
             for (int m = num8; m < num9; m++)
             {
                 for (int n = num10; n < num11; n++)
                 {
                     double num12 = (double)Math.Abs(m - X) * 0.7;
                     double num13 = (double)Math.Abs(n - i) * 1.35;
                     double num14 = Math.Sqrt(num12 * num12 + num13 * num13);
                     double num15 = (double)num7 * (0.53 + genRand.NextDouble() * 0.04);
                     double num16 = (double)Math.Abs(m - X) / (double)(num9 - X);
                     num16 = 1.0 - num16;
                     num16 *= 2.3;
                     num16 *= num16;
                     num16 *= num16;
                     if (num14 < num15)
                     {
                         if (n == i + 1)
{
                             Main.tile[m, n].liquid = 127;
                         }
                         else if (n > i + 1)
{
                             Main.tile[m, n].liquid = byte.MaxValue;
                         }
                         Main.tile[m, n].lava(lava: false);
                         Main.tile[m, n].active(active: false);
                     }
                     else if (n < i && num12 < num15 + (double)(Math.Abs(n - i) * 3) * num16)
                     {
                         if (Main.tile[m, n].type == 53)
{
                             Main.tile[m, n].active(active: false);
                         }
                     }
                     else if (n >= i && num12 < num15 + (double)Math.Abs(n - i) * num16 && Main.tile[m, n].wall == 0)
                     {
                         if (Main.tile[m, n].active() && Main.tileSolid[Main.tile[m, n].type] && !Main.tileSolidTop[Main.tile[m, n].type])
{
                             Main.tile[m, n].slope(0);
                             Main.tile[m, n].halfBrick(halfBrick: false);
                             continue;
                         }
                         Main.tile[m, n].active(active: true);
                         Main.tile[m, n].type = 53;
                         Main.tile[m, n].slope(0);
                         Main.tile[m, n].halfBrick(halfBrick: false);
                     }
                 }
             }
             int num17 = 50;
             num8 = X - num2 * 2;
             num9 = X + num2 * 2;
             num11 = i + oasisHeight * 2;
             for (int num18 = num8; num18 < num9; num18++)
             {
                 for (int num19 = num11; num19 >= i; num19--)
                 {
                     double num20 = (double)Math.Abs(num18 - X) * 0.7;
                     double num21 = (double)Math.Abs(num19 - i) * 1.35;
                     double num22 = Math.Sqrt(num20 * num20 + num21 * num21);
                     double num23 = (double)num7 * 0.5700000000000001;
                     if (num22 > num23)
                     {
                         bool flag = false;
                         if (!Main.tile[num18, num19].active() && Main.tile[num18, num19].wall == 0)
{
                             int num24 = -1;
                             int num25 = -1;
                             for (int num26 = num18; num26 <= num18 + num17 && Main.tile[num26, num19 + 1].active() && Main.tileSolid[Main.tile[num26, num19 + 1].type] && Main.tile[num26, num19].wall <= 0; num26++)
{
                                 if (Main.tile[num26, num19].active() && Main.tileSolid[Main.tile[num26, num19].type])
{
                                     if (Main.tile[num26, num19].type == 53)
{
                                         flag = true;
                                     }
                                     num25 = num26;
                                     break;
                                 }
                                 if (Main.tile[num26, num19].active())
{
                                     break;
                                 }
                             }
                             int num27 = num18;
                             while (num27 >= num18 - num17 && Main.tile[num27, num19 + 1].active() && Main.tileSolid[Main.tile[num27, num19 + 1].type] && Main.tile[num27, num19].wall <= 0)
{
                                 if (Main.tile[num27, num19].active() && Main.tileSolid[Main.tile[num27, num19].type])
{
                                     if (Main.tile[num27, num19].type == 53)
{
                                         flag = true;
                                     }
                                     num24 = num27;
                                     break;
                                 }
                                 if (Main.tile[num27, num19].active())
{
                                     break;
                                 }
                                 num27--;
                             }
                             flag = true;
                             if (num24 > -1 && num25 > -1 && flag)
{
                                 int num28 = 0;
                                 for (int num29 = num24 + 1; num29 < num25; num29++)
{
                                     if (num25 - num24 > 5 && genRand.Next(5) == 0)
{
                                         num28 = genRand.Next(5, 10);
                                     }
                                     Main.tile[num29, num19].active(active: true);
                                     Main.tile[num29, num19].type = 53;
                                     if (num28 > 0)
{
                                         num28--;
                                         Main.tile[num29, num19 - 1].active(active: true);
                                         Main.tile[num29, num19 - 1].type = 53;
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
             if (GenVars.numOasis < GenVars.maxOasis)
             {
                 GenVars.oasisPosition[GenVars.numOasis] = new Point(X, i);
                 GenVars.oasisWidth[GenVars.numOasis] = num2;
                 GenVars.numOasis++;
             }
             return true;
         }
         return false;
     }
References Tile.active(), Vector2D.Distance(), genRand, Tile.halfBrick(), Tile.lava(), Tile.liquid, GenVars.maxOasis, Main.maxTilesX, Main.maxTilesY, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), GenVars.numOasis, GenVars.oasisHeight, GenVars.oasisPosition, GenVars.oasisWidth, Tile.slope(), Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.type, Tile.wall, Main.worldSurface, X, and Y.