Terraria: WorldGen.CheckChest
CheckChest()
static void WorldGen.CheckChest (int i, int j, int type) inline static
     {
         if (destroyObject)
         {
             return;
         }
         bool flag = false;
         int num = 0;
         int num2 = j;
         num += Main.tile[i, j].frameX / 18;
         num2 += Main.tile[i, j].frameY / 18 * -1;
         while (num > 1)
         {
             num -= 2;
         }
         num *= -1;
         num += i;
         for (int k = num; k < num + 2; k++)
         {
             for (int l = num2; l < num2 + 2; l++)
             {
                 if (Main.tile[k, l] == null)
                 {
                     Main.tile[k, l] = new Tile();
                 }
                 int num3;
                 for (num3 = Main.tile[k, l].frameX / 18; num3 > 1; num3 -= 2)
                 {
                 }
                 if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || num3 != k - num || Main.tile[k, l].frameY != (l - num2) * 18)
                 {
                     flag = true;
                 }
             }
             if (Main.tile[k, num2 + 2] == null)
             {
                 Main.tile[k, num2 + 2] = new Tile();
             }
             if ((!Main.tile[k, num2 + 2].active() || !Main.tileSolid[Main.tile[k, num2 + 2].type]) && Chest.CanDestroyChest(num, num2))
             {
                 flag = true;
             }
         }
         if (!flag)
         {
             return;
         }
         int chestItemDrop = GetChestItemDrop(i, j, type);
         destroyObject = true;
         for (int m = num; m < num + 2; m++)
         {
             for (int n = num2; n < num2 + 3; n++)
             {
                 if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                 {
                     Chest.DestroyChest(m, n);
                     KillTile(m, n);
                 }
             }
         }
         Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, chestItemDrop);
         destroyObject = false;
     }
References Tile.active(), Chest.CanDestroyChest(), Chest.DestroyChest(), Tile.frameX, Tile.frameY, Item.NewItem(), Main.tile, Main.tileSolid, and Tile.type.