Terraria: WorldGen.PlaceTight
PlaceTight()
static void WorldGen.PlaceTight (int x, int y, bool spiders = false) inline static
     {
         if (Main.tile[x, y - 1] == null)
         {
             Main.tile[x, y - 1] = new Tile();
         }
         if (Main.tile[x, y] == null)
         {
             Main.tile[x, y] = new Tile();
         }
         if (Main.tile[x, y + 1] == null)
         {
             Main.tile[x, y + 1] = new Tile();
         }
         if (!Main.tile[x, y].shimmer())
         {
             PlaceUncheckedStalactite(x, y, genRand.Next(2) == 0, genRand.Next(3), spiders);
             if (Main.tile[x, y].type == 165)
             {
                 CheckTight(x, y);
             }
         }
     }
References Tile.shimmer(), Main.tile, and Tile.type.
Referenced by ActionStalagtite.Apply(), MarbleBiome.PlaceSlab(), and WorldGen.Spread.Spider().