Terraria: WorldGen.PlaceLilyPad
PlaceLilyPad()
static bool WorldGen.PlaceLilyPad (int x, int j) inline static
     {
         int num = j;
         if (x < 50 || x > Main.maxTilesX - 50 || num < 50 || num > Main.maxTilesY - 50)
         {
             return false;
         }
         if (Main.tile[x, num].active() || Main.tile[x, num].liquid == 0 || Main.tile[x, num].liquidType() != 0)
         {
             return false;
         }
         while (Main.tile[x, num].liquid > 0 && num > 50)
         {
             num--;
         }
         num++;
         if (Main.tile[x, num].active() || Main.tile[x, num - 1].active() || Main.tile[x, num].liquid == 0 || Main.tile[x, num].liquidType() != 0)
         {
             return false;
         }
         if (Main.tile[x, num].wall != 0 && Main.tile[x, num].wall != 15 && Main.tile[x, num].wall != 70 && (Main.tile[x, num].wall < 63 || Main.tile[x, num].wall > 68))
         {
             return false;
         }
         int num2 = 5;
         int num3 = 0;
         for (int i = x - num2; i <= x + num2; i++)
         {
             for (int k = num - num2; k <= num + num2; k++)
             {
                 if (Main.tile[i, k].active() && Main.tile[i, k].type == 518)
                 {
                     num3++;
                 }
             }
         }
         if (num3 > 3)
         {
             return false;
         }
         int l;
         for (l = num; (!Main.tile[x, l].active() || !Main.tileSolid[Main.tile[x, l].type] || Main.tileSolidTop[Main.tile[x, l].type]) && l < Main.maxTilesY - 50; l++)
         {
             if (Main.tile[x, l].active() && Main.tile[x, l].type == 519)
             {
                 return false;
             }
         }
         int num4 = 12;
         if (l - num > num4)
         {
             return false;
         }
         if (l - num < 3)
         {
             return false;
         }
         int type = Main.tile[x, l].type;
         int num5 = -1;
         if (type == 2 || type == 477)
         {
             num5 = 0;
         }
         if (type == 109 || type == 109 || type == 116)
         {
             num5 = 18;
         }
         if (type == 60)
         {
             num5 = 36;
         }
         if (num5 < 0)
         {
             return false;
         }
         Main.tile[x, num].active(active: true);
         Main.tile[x, num].type = 518;
         if (genRand.Next(2) == 0)
         {
             Main.tile[x, num].frameX = (short)(18 * genRand.Next(3));
         }
         else if (genRand.Next(15) == 0)
         {
             Main.tile[x, num].frameX = (short)(18 * genRand.Next(18));
         }
         else
         {
             int num6 = Main.maxTilesX / 5;
             if (x < num6)
             {
                 Main.tile[x, num].frameX = (short)(18 * genRand.Next(6, 9));
             }
             else if (x < num6 * 2)
             {
                 Main.tile[x, num].frameX = (short)(18 * genRand.Next(9, 12));
             }
             else if (x < num6 * 3)
             {
                 Main.tile[x, num].frameX = (short)(18 * genRand.Next(3, 6));
             }
             else if (x < num6 * 4)
             {
                 Main.tile[x, num].frameX = (short)(18 * genRand.Next(15, 18));
             }
             else
             {
                 Main.tile[x, num].frameX = (short)(18 * genRand.Next(12, 15));
             }
         }
         Main.tile[x, num].frameY = (short)num5;
         Main.tile[x, num].halfBrick(halfBrick: false);
         Main.tile[x, num].slope(0);
         SquareTileFrame(x, num);
         return true;
     }
References Tile.active(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.liquid, Tile.liquidType(), Main.maxTilesX, Main.maxTilesY, Tile.slope(), Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.type, and Tile.wall.