Terraria: WorldGen.PlaceCatTail
PlaceCatTail()
static Point WorldGen.PlaceCatTail (int x, int j) inline static
     {
         int num = j;
         Point result = new Point(-1, -1);
         if (x < 50 || x > Main.maxTilesX - 50 || num < 50 || num > Main.maxTilesY - 50)
         {
             return result;
         }
         if ((Main.tile[x, num].active() && Main.tile[x, num].type != 71) || Main.tile[x, num].liquid == 0 || Main.tile[x, num].liquidType() != 0)
         {
             return result;
         }
         while (Main.tile[x, num].liquid > 0 && num > 50)
         {
             num--;
         }
         num++;
         if (Main.tile[x, num].active() || Main.tile[x, num - 1].active() || Main.tile[x, num].liquid == 0 || Main.tile[x, num].liquidType() != 0)
         {
             return result;
         }
         if (Main.tile[x, num].wall != 0 && Main.tile[x, num].wall != 80 && Main.tile[x, num].wall != 81 && Main.tile[x, num].wall != 69 && (Main.tile[x, num].wall < 63 || Main.tile[x, num].wall > 68))
         {
             return result;
         }
         int num2 = 7;
         int num3 = 0;
         for (int i = x - num2; i <= x + num2; i++)
         {
             for (int k = num - num2; k <= num + num2; k++)
             {
                 if (Main.tile[i, k].active() && Main.tile[i, k].type == 519)
                 {
                     num3++;
                     break;
                 }
             }
         }
         if (num3 > 3)
         {
             return result;
         }
         int l;
         for (l = num; (!Main.tile[x, l].active() || !Main.tileSolid[Main.tile[x, l].type] || Main.tileSolidTop[Main.tile[x, l].type]) && l < Main.maxTilesY - 50; l++)
         {
             if (Main.tile[x, l].active() && Main.tile[x, l].type != 71)
             {
                 return result;
             }
         }
         int num4 = catTailDistance - 1;
         if (l - num > num4)
         {
             return result;
         }
         if (l - num < 2)
         {
             return result;
         }
         int type = Main.tile[x, l].type;
         if (!Main.tile[x, l].nactive())
         {
             return result;
         }
         int num5 = -1;
         switch (type)
         {
         case 2:
         case 477:
             num5 = 0;
             break;
         case 53:
             if (x < beachDistance || x > Main.maxTilesX - beachDistance)
             {
                 return result;
             }
             num5 = 18;
             break;
         case 199:
         case 234:
         case 662:
             num5 = 54;
             break;
         case 23:
         case 112:
         case 661:
             num5 = 72;
             break;
         case 70:
             num5 = 90;
             break;
         }
         if (num5 < 0)
         {
             return result;
         }
         if (Main.tile[x, l].topSlope() && gen && genRand.Next(3) != 0)
         {
             Main.tile[x, l].slope(0);
         }
         else if (Main.tile[x, l].topSlope() || Main.tile[x, l].halfBrick())
         {
             return result;
         }
         num = l - 1;
         Main.tile[x, num].active(active: true);
         Main.tile[x, num].type = 519;
         Main.tile[x, num].frameX = 0;
         Main.tile[x, num].frameY = (short)num5;
         Main.tile[x, num].halfBrick(halfBrick: false);
         Main.tile[x, num].slope(0);
         Main.tile[x, num].CopyPaintAndCoating(Main.tile[x, num + 1]);
         SquareTileFrame(x, num);
         return new Point(x, num);
     }
References Tile.active(), Tile.CopyPaintAndCoating(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.liquid, Tile.liquidType(), Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Tile.slope(), Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.topSlope(), Tile.type, and Tile.wall.