Terraria: WorldGen.GetCactusType
GetCactusType()
static void WorldGen.GetCactusType (int tileX, int tileY, int frameX, int frameY, out bool evil, out bool good, out bool crimson) inline static
     {
         evil = false;
         good = false;
         crimson = false;
         int num = tileX;
         if (frameX == 36)
         {
             num--;
         }
         if (frameX == 54)
         {
             num++;
         }
         if (frameX == 108)
         {
             num = ((frameY != 18) ? (num + 1) : (num - 1));
         }
         int num2 = tileY;
         bool flag = false;
         Tile tile = Main.tile[num, num2];
         if (tile == null)
         {
             return;
         }
         if (tile.type == 80 && tile.active())
         {
             flag = true;
         }
         while (tile != null && (!tile.active() || !Main.tileSolid[tile.type] || !flag))
         {
             if (tile.type == 80 && tile.active())
             {
                 flag = true;
             }
             num2++;
             if (num2 > tileY + 20)
             {
                 break;
             }
             tile = Main.tile[num, num2];
         }
         if (tile.type == 112)
         {
             evil = true;
         }
         if (tile.type == 116)
         {
             good = true;
         }
         if (tile.type == 234)
         {
             crimson = true;
         }
     }
References Tile.active(), Main.tile, Main.tileSolid, and Tile.type.
Referenced by TileDrawing.DrawSingleTile(), MapHelper.GetTileBaseOption(), and TileDrawing.GetTileDrawData().