Terraria: WorldGen.SpawnTownNPC
SpawnTownNPC()
static TownNPCSpawnResult WorldGen.SpawnTownNPC (int x, int y) inline static
     {
         if (Main.wallHouse[Main.tile[x, y].wall])
         {
             canSpawn = true;
         }
         if (!canSpawn)
         {
             return TownNPCSpawnResult.Blocked;
         }
         if (!StartRoomCheck(x, y))
         {
             return TownNPCSpawnResult.Blocked;
         }
         if (!RoomNeeds(prioritizedTownNPCType))
         {
             return TownNPCSpawnResult.Blocked;
         }
         int num = FindAHomelessNPC();
         int type = prioritizedTownNPCType;
         if (num != -1)
         {
             type = Main.npc[num].type;
         }
         Point roomPosition = Point.Zero;
         bool flag = NPCID.Sets.IsTownPet[type] && TownManager.HasRoom(type, out roomPosition);
         if ((roomHasStinkbug || roomHasEchoStinkbug) && !flag)
         {
             return TownNPCSpawnResult.Blocked;
         }
         ScoreRoom(-1, type);
         if (hiScore <= 0)
         {
             return TownNPCSpawnResult.Blocked;
         }
         bool canSpawnNewTownNPC = true;
         if (!IsThereASpawnablePrioritizedTownNPC(bestX, bestY, ref canSpawnNewTownNPC))
         {
             return TownNPCSpawnResult.Blocked;
         }
         type = prioritizedTownNPCType;
         if (num != -1)
         {
             Main.townNPCCanSpawn[prioritizedTownNPCType] = false;
             Main.npc[num].homeTileX = bestX;
             Main.npc[num].homeTileY = bestY;
             Main.npc[num].homeless = false;
             AchievementsHelper.NotifyProgressionEvent(8);
             prioritizedTownNPCType = 0;
             return TownNPCSpawnResult.RelocatedHomeless;
         }
         if (canSpawnNewTownNPC && num == -1)
         {
             if (TownManager.HasRoom(type, out var roomPosition2) && !currentlyTryingToUseAlternateHousingSpot)
             {
                 int num2 = bestX;
                 int num3 = bestY;
                 currentlyTryingToUseAlternateHousingSpot = true;
                 TownNPCSpawnResult townNPCSpawnResult = SpawnTownNPC(roomPosition2.X, roomPosition2.Y - 2);
                 currentlyTryingToUseAlternateHousingSpot = false;
                 bestX = num2;
                 bestY = num3;
                 if (townNPCSpawnResult == TownNPCSpawnResult.Successful)
                 {
                     return townNPCSpawnResult;
                 }
             }
             int num4 = bestX;
             int num5 = bestY;
             int npcTypeToSpawn = prioritizedTownNPCType;
             if (IsRoomConsideredAlreadyOccupied(num4, num5, npcTypeToSpawn))
             {
                 return TownNPCSpawnResult.BlockedInfiHousing;
             }
             bool flag2 = false;
             if (!flag2)
             {
                 flag2 = true;
                 Rectangle value = new Rectangle(num4 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num5 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                 for (int i = 0; i < 255; i++)
                 {
                     if (Main.player[i].active && new Rectangle((int)Main.player[i].position.X, (int)Main.player[i].position.Y, Main.player[i].width, Main.player[i].height).Intersects(value))
                     {
                         flag2 = false;
                         break;
                     }
                 }
             }
             if (!flag2 && !((double)num5 > Main.worldSurface))
             {
                 for (int j = 1; j < 500; j++)
                 {
                     for (int k = 0; k < 2; k++)
                     {
                         num4 = ((k != 0) ? (bestX - j) : (bestX + j));
                         if (num4 > 10 && num4 < Main.maxTilesX - 10)
{
                             int num6 = bestY - j;
                             double num7 = bestY + j;
                             if (num6 < 10)
{
                                 num6 = 10;
                             }
                             if (num7 > Main.worldSurface)
{
                                 num7 = Main.worldSurface;
                             }
                             for (int l = num6; (double)l < num7; l++)
{
                                 num5 = l;
                                 if (!Main.tile[num4, num5].nactive() || !Main.tileSolid[Main.tile[num4, num5].type])
{
                                     continue;
                                 }
                                 if (Collision.SolidTiles(num4 - 1, num4 + 1, num5 - 3, num5 - 1))
{
                                     break;
                                 }
                                 flag2 = true;
                                 Rectangle value2 = new Rectangle(num4 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num5 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                                 for (int m = 0; m < 255; m++)
{
                                     if (Main.player[m].active && new Rectangle((int)Main.player[m].position.X, (int)Main.player[m].position.Y, Main.player[m].width, Main.player[m].height).Intersects(value2))
{
                                         flag2 = false;
                                         break;
                                     }
                                 }
                                 break;
                             }
                         }
                         if (flag2)
{
                             break;
                         }
                     }
                     if (flag2)
                     {
                         break;
                     }
                 }
             }
             int num8 = NPC.NewNPC(NPC.GetSpawnSourceForTownSpawn(), num4 * 16, num5 * 16, type, 1);
             Main.townNPCCanSpawn[type] = false;
             Main.npc[num8].homeTileX = bestX;
             Main.npc[num8].homeTileY = bestY;
             if (num4 < bestX)
             {
                 Main.npc[num8].direction = 1;
             }
             else if (num4 > bestX)
             {
                 Main.npc[num8].direction = -1;
             }
             Main.npc[num8].netUpdate = true;
             string fullName = Main.npc[num8].FullName;
             if (Main.netMode == 0)
             {
                 Main.NewText(Language.GetTextValue("Announcement.HasArrived", fullName), 50, 125);
             }
             else if (Main.netMode == 2)
             {
                 ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasArrived", Main.npc[num8].GetFullNetName()), new Color(50, 125, 255));
             }
             AchievementsHelper.NotifyProgressionEvent(8);
             switch (Main.npc[num8].type)
             {
             case 160:
                 AchievementsHelper.NotifyProgressionEvent(18);
                 NPC.unlockedTruffleSpawn = true;
                 NetMessage.SendData(7);
                 break;
             case 17:
                 NPC.unlockedMerchantSpawn = true;
                 break;
             case 207:
                 NPC.unlockedDyeTraderSpawn = true;
                 break;
             case 18:
                 NPC.unlockedNurseSpawn = true;
                 break;
             case 19:
                 NPC.unlockedArmsDealerSpawn = true;
                 break;
             case 38:
                 NPC.unlockedDemolitionistSpawn = true;
                 break;
             case 208:
                 NPC.unlockedPartyGirlSpawn = true;
                 break;
             case 663:
                 NPC.unlockedPrincessSpawn = true;
                 break;
             case 678:
                 NPC.unlockedSlimeGreenSpawn = true;
                 break;
             }
             CheckAchievement_RealEstateAndTownSlimes();
             prioritizedTownNPCType = 0;
         }
         return TownNPCSpawnResult.Successful;
     }
References Entity.active, bestX, bestY, ChatHelper.BroadcastChatMessage(), canSpawn, CheckAchievement_RealEstateAndTownSlimes(), Color, currentlyTryingToUseAlternateHousingSpot, Entity.direction, FindAHomelessNPC(), NetworkText.FromKey(), NPC.FullName, NPC.GetFullNetName(), NPC.GetSpawnSourceForTownSpawn(), Language.GetTextValue(), TownRoomManager.HasRoom(), Entity.height, hiScore, NPC.homeless, NPC.homeTileX, NPC.homeTileY, IsRoomConsideredAlreadyOccupied(), IsThereASpawnablePrioritizedTownNPC(), NPCID.Sets.IsTownPet, Main.maxTilesX, Tile.nactive(), Main.netMode, NPC.netUpdate, NPC.NewNPC(), Main.NewText(), AchievementsHelper.NotifyProgressionEvent(), Main.npc, Main.player, Entity.position, prioritizedTownNPCType, roomHasEchoStinkbug, roomHasStinkbug, RoomNeeds(), NPC.safeRangeX, NPC.safeRangeY, ScoreRoom(), NetMessage.SendData(), NPC.sHeight, Collision.SolidTiles(), StartRoomCheck(), NPC.sWidth, Main.tile, Main.tileSolid, TownManager, Main.townNPCCanSpawn, NPC.type, Tile.type, NPC.unlockedArmsDealerSpawn, NPC.unlockedDemolitionistSpawn, NPC.unlockedDyeTraderSpawn, NPC.unlockedMerchantSpawn, NPC.unlockedNurseSpawn, NPC.unlockedPartyGirlSpawn, NPC.unlockedPrincessSpawn, NPC.unlockedSlimeGreenSpawn, NPC.unlockedTruffleSpawn, Tile.wall, Main.wallHouse, Entity.width, and Main.worldSurface.
Referenced by moveRoom().