Terraria: WorldGen.ShakeTree
ShakeTree()
static void WorldGen.ShakeTree (int i, int j) inline static private
     {
         if (numTreeShakes == maxTreeShakes)
         {
             return;
         }
         GetTreeBottom(i, j, out var x, out var y);
         int num = y;
         TreeTypes treeType = GetTreeType(Main.tile[x, y].type);
         if (treeType == TreeTypes.None)
         {
             return;
         }
         for (int k = 0; k < numTreeShakes; k++)
         {
             if (treeShakeX[k] == x && treeShakeY[k] == y)
             {
                 return;
             }
         }
         treeShakeX[numTreeShakes] = x;
         treeShakeY[numTreeShakes] = y;
         numTreeShakes++;
         y--;
         while (y > 10 && Main.tile[x, y].active() && TileID.Sets.IsShakeable[Main.tile[x, y].type])
         {
             y--;
         }
         y++;
         if (!IsTileALeafyTreeTop(x, y) || Collision.SolidTiles(x - 2, x + 2, y - 2, y + 2))
         {
             return;
         }
         if (Main.getGoodWorld && genRand.Next(17) == 0)
         {
             Projectile.NewProjectile(GetProjectileSource_ShakeTree(x, y), x * 16, y * 16, (float)Main.rand.Next(-100, 101) * 0.002f, 0f, 28, 0, 0f, Main.myPlayer, 16f, 16f);
         }
         else if (genRand.Next(300) == 0 && treeType == TreeTypes.Forest)
         {
             Item.NewItem(GetItemSource_ShakeTree(x, y), x * 16, y * 16, 16, 16, 832);
         }
         else if (genRand.Next(300) == 0 && treeType == TreeTypes.Forest)
         {
             Item.NewItem(GetItemSource_ShakeTree(x, y), x * 16, y * 16, 16, 16, 933);
         }
         else if (genRand.Next(200) == 0 && treeType == TreeTypes.Jungle)
         {
             Item.NewItem(GetItemSource_ShakeTree(x, y), x * 16, y * 16, 16, 16, 3360);
         }
         else if (genRand.Next(200) == 0 && treeType == TreeTypes.Jungle)
         {
             Item.NewItem(GetItemSource_ShakeTree(x, y), x * 16, y * 16, 16, 16, 3361);
         }
         else if (genRand.Next(1000) == 0 && treeType == TreeTypes.Forest)
         {
             Item.NewItem(GetItemSource_ShakeTree(x, y), x * 16, y * 16, 16, 16, 4366);
         }
         else if (genRand.Next(7) == 0 && (treeType == TreeTypes.Forest || treeType == TreeTypes.Snow || treeType == TreeTypes.Hallowed || treeType == TreeTypes.Ash))
         {
             Item.NewItem(GetItemSource_ShakeTree(x, y), x * 16, y * 16, 16, 16, 27, genRand.Next(1, 3));
         }
         else if (genRand.Next(8) == 0 && treeType == TreeTypes.Mushroom)
         {
             Item.NewItem(GetItemSource_ShakeTree(x, y), x * 16, y * 16, 16, 16, 194, genRand.Next(1, 2));
         }
         else if (genRand.Next(35) == 0 && Main.halloween)
         {
             Item.NewItem(GetItemSource_ShakeTree(x, y), x * 16, y * 16, 16, 16, 1809, genRand.Next(1, 3));
         }
         else if (genRand.Next(12) == 0)
         {
             int dropItem = 0;
             KillTile_GetItemDrops(i, j, Main.tile[i, j], out dropItem, out var _, out var _, out var _);
             Item.NewItem(GetItemSource_FromTreeShake(x, y), x * 16, y * 16, 16, 16, dropItem, genRand.Next(1, 4));
         }
         else if (genRand.Next(20) == 0)
         {
             int type = 71;
             int num2 = genRand.Next(50, 100);
             if (genRand.Next(30) == 0)
             {
                 type = 73;
                 num2 = 1;
                 if (genRand.Next(5) == 0)
                 {
                     num2++;
                 }
                 if (genRand.Next(10) == 0)
                 {
                     num2++;
                 }
             }
             else if (genRand.Next(10) == 0)
             {
                 type = 72;
                 num2 = genRand.Next(1, 21);
                 if (genRand.Next(3) == 0)
                 {
                     num2 += genRand.Next(1, 21);
                 }
                 if (genRand.Next(4) == 0)
                 {
                     num2 += genRand.Next(1, 21);
                 }
             }
             Item.NewItem(GetItemSource_FromTreeShake(x, y), x * 16, y * 16, 16, 16, type, num2);
         }
         else if (genRand.Next(15) == 0 && (treeType == TreeTypes.Forest || treeType == TreeTypes.Hallowed))
         {
             int type2 = genRand.Next(5) switch
             {
                 0 => 74,
                 1 => 297,
                 2 => 298,
                 3 => 299,
                 _ => 538,
             };
             if (Player.GetClosestRollLuck(x, y, NPC.goldCritterChance) == 0f)
             {
                 type2 = ((genRand.Next(2) != 0) ? 539 : 442);
             }
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, type2);
         }
         else if (genRand.Next(50) == 0 && treeType == TreeTypes.Hallowed && !Main.dayTime)
         {
             int type3 = Main.rand.NextFromList(new short[3] { 583, 584, 585 });
             if (Main.tenthAnniversaryWorld && Main.rand.Next(4) != 0)
             {
                 type3 = 583;
             }
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, type3);
         }
         else if (genRand.Next(50) == 0 && treeType == TreeTypes.Forest && !Main.dayTime)
         {
             NPC obj = Main.npc[NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, 611)];
             obj.velocity.Y = 1f;
             obj.netUpdate = true;
         }
         else if (genRand.Next(50) == 0 && treeType == TreeTypes.Jungle && Main.dayTime)
         {
             NPC obj2 = Main.npc[NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, Main.rand.NextFromList(new short[5] { 671, 672, 673, 674, 675 }))];
             obj2.velocity.Y = 1f;
             obj2.netUpdate = true;
         }
         else if (genRand.Next(40) == 0 && treeType == TreeTypes.Forest && !Main.dayTime && Main.halloween)
         {
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, 301);
         }
         else if (genRand.Next(50) == 0 && (treeType == TreeTypes.Forest || treeType == TreeTypes.Hallowed))
         {
             for (int l = 0; l < 5; l++)
             {
                 Point point = new Point(x + Main.rand.Next(-2, 2), y - 1 + Main.rand.Next(-2, 2));
                 int type4 = ((Player.GetClosestRollLuck(x, y, NPC.goldCritterChance) != 0f) ? Main.rand.NextFromList(new short[3] { 74, 297, 298 }) : 442);
                 NPC obj3 = Main.npc[NPC.NewNPC(new EntitySource_ShakeTree(x, y), point.X * 16, point.Y * 16, type4)];
                 obj3.velocity = Main.rand.NextVector2CircularEdge(3f, 3f);
                 obj3.netUpdate = true;
             }
         }
         else if (genRand.Next(40) == 0 && treeType == TreeTypes.Jungle)
         {
             for (int m = 0; m < 5; m++)
             {
                 Point point2 = new Point(x + Main.rand.Next(-2, 2), y - 1 + Main.rand.Next(-2, 2));
                 NPC obj4 = Main.npc[NPC.NewNPC(new EntitySource_ShakeTree(x, y), point2.X * 16, point2.Y * 16, Main.rand.NextFromList(new short[2] { 210, 211 }))];
                 obj4.ai[1] = 65f;
                 obj4.netUpdate = true;
             }
         }
         else if (genRand.Next(20) == 0 && (treeType == TreeTypes.Palm || treeType == TreeTypes.PalmCorrupt || treeType == TreeTypes.PalmCrimson || treeType == TreeTypes.PalmHallowed) && !IsPalmOasisTree(x))
         {
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, 603);
         }
         else if (genRand.Next(30) == 0 && (treeType == TreeTypes.Crimson || treeType == TreeTypes.PalmCrimson))
         {
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16 + 8, (y - 1) * 16, -22);
         }
         else if (genRand.Next(30) == 0 && (treeType == TreeTypes.Corrupt || treeType == TreeTypes.PalmCorrupt))
         {
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16 + 8, (y - 1) * 16, -11);
         }
         else if (genRand.Next(30) == 0 && treeType == TreeTypes.Jungle && !Main.dayTime)
         {
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, 51);
         }
         else if (genRand.Next(40) == 0 && treeType == TreeTypes.Jungle)
         {
             Projectile.NewProjectile(GetProjectileSource_ShakeTree(x, y), x * 16 + 8, (y - 1) * 16, 0f, 0f, 655, 0, 0f, Main.myPlayer);
         }
         else if (genRand.Next(20) == 0 && (treeType == TreeTypes.Forest || treeType == TreeTypes.Hallowed) && !Main.raining && !NPC.TooWindyForButterflies && Main.dayTime)
         {
             int type5 = 356;
             if (Player.GetClosestRollLuck(x, y, NPC.goldCritterChance) == 0f)
             {
                 type5 = 444;
             }
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, type5);
         }
         else if (genRand.Next(20) == 0 && treeType == TreeTypes.Ash && y > Main.maxTilesY - 250)
         {
             int num3 = genRand.Next(3);
             NPC.NewNPC(new EntitySource_ShakeTree(x, y), x * 16, y * 16, num3 switch
             {
                 0 => 654,
                 1 => 653,
                 _ => 655,
             });
         }
         else if (Main.remixWorld && genRand.Next(20) == 0 && treeType == TreeTypes.Ash && y > Main.maxTilesY - 250)
         {
             Item.NewItem(GetItemSource_FromTreeShake(x, y), x * 16, y * 16, 16, 16, 965, genRand.Next(20, 41));
         }
         else if (genRand.Next(12) == 0 && treeType == TreeTypes.Forest)
         {
             int num4 = genRand.Next(5);
             Item.NewItem(GetItemSource_FromTreeShake(x, y), x * 16, y * 16, 16, 16, num4 switch
             {
                 0 => 4009,
                 1 => 4293,
                 2 => 4282,
                 3 => 4290,
                 _ => 4291,
             });
         }
         else if (genRand.Next(12) == 0 && treeType == TreeTypes.Snow)
         {
             Item.NewItem(Type: (genRand.Next(2) != 0) ? 4295 : 4286, source: GetItemSource_FromTreeShake(x, y), X: x * 16, Y: y * 16, Width: 16, Height: 16);
         }
         else if (genRand.Next(12) == 0 && treeType == TreeTypes.Jungle)
         {
             Item.NewItem(Type: (genRand.Next(2) != 0) ? 4292 : 4294, source: GetItemSource_FromTreeShake(x, y), X: x * 16, Y: y * 16, Width: 16, Height: 16);
         }
         else if (genRand.Next(12) == 0 && (treeType == TreeTypes.Palm || treeType == TreeTypes.PalmCorrupt || treeType == TreeTypes.PalmCrimson || treeType == TreeTypes.PalmHallowed) && !IsPalmOasisTree(x))
         {
             Item.NewItem(Type: (genRand.Next(2) != 0) ? 4287 : 4283, source: GetItemSource_FromTreeShake(x, y), X: x * 16, Y: y * 16, Width: 16, Height: 16);
         }
         else if (genRand.Next(12) == 0 && (treeType == TreeTypes.Corrupt || treeType == TreeTypes.PalmCorrupt))
         {
             Item.NewItem(Type: (genRand.Next(2) != 0) ? 4289 : 4284, source: GetItemSource_FromTreeShake(x, y), X: x * 16, Y: y * 16, Width: 16, Height: 16);
         }
         else if (genRand.Next(12) == 0 && (treeType == TreeTypes.Hallowed || treeType == TreeTypes.PalmHallowed))
         {
             Item.NewItem(Type: (genRand.Next(2) != 0) ? 4288 : 4297, source: GetItemSource_FromTreeShake(x, y), X: x * 16, Y: y * 16, Width: 16, Height: 16);
         }
         else if (genRand.Next(12) == 0 && (treeType == TreeTypes.Crimson || treeType == TreeTypes.PalmCrimson))
         {
             Item.NewItem(Type: (genRand.Next(2) != 0) ? 4285 : 4296, source: GetItemSource_FromTreeShake(x, y), X: x * 16, Y: y * 16, Width: 16, Height: 16);
         }
         else if (genRand.Next(12) == 0 && treeType == TreeTypes.Ash)
         {
             Item.NewItem(Type: (genRand.Next(2) != 0) ? 5278 : 5277, source: GetItemSource_FromTreeShake(x, y), X: x * 16, Y: y * 16, Width: 16, Height: 16);
         }
         int treeHeight = 0;
         int treeFrame = 0;
         int passStyle = 0;
         GetTreeLeaf(x, Main.tile[x, y], Main.tile[x, num], ref treeHeight, out treeFrame, out passStyle);
         if (passStyle != -1)
         {
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(112, -1, -1, null, 1, x, y, 1f, passStyle);
             }
             if (Main.netMode == 0)
             {
                 TreeGrowFX(x, y, 1, passStyle, hitTree: true);
             }
         }
     }
References Tile.active(), Main.dayTime, Player.GetClosestRollLuck(), Main.getGoodWorld, NPC.goldCritterChance, Main.halloween, TileID.Sets.IsShakeable, Main.myPlayer, NPC.netUpdate, Item.NewItem(), NPC.NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), Main.npc, Main.rand, Collision.SolidTiles(), Main.tenthAnniversaryWorld, Main.tile, Tile.type, and Entity.velocity.