Terraria: WorldGen.FinishNoTraps
FinishNoTraps()
static void WorldGen.FinishNoTraps () inline static private
     {
         Main.tileSolid[138] = false;
         for (int i = 50; i < Main.maxTilesX - 50; i++)
         {
             for (int j = 50; j < Main.maxTilesY - 50; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (genRand.Next(5) == 0 && tile.active() && tile.type == 12 && tile.frameX == 0 && tile.frameY == 0)
                 {
                     Main.tile[i, j].type = 665;
                     Main.tile[i, j + 1].type = 665;
                     Main.tile[i + 1, j].type = 665;
                     Main.tile[i + 1, j + 1].type = 665;
                 }
                 if (i % 2 != 0 || j % 2 != 0 || !Main.tile[i, j].active() || (Main.tile[i, j].type != 105 && (Main.tile[i, j].type != 467 || (Main.tile[i, j].frameX != 144 && Main.tile[i, j].frameX != 162))))
                 {
                     continue;
                 }
                 bool flag = false;
                 for (int k = i - 1; k <= i + 1; k++)
                 {
                     for (int l = j - 1; l <= j + 1; l++)
                     {
                         if (Main.tile[k, l].wire())
{
                             flag = true;
                         }
                     }
                 }
                 if (!flag)
                 {
                     bool flag2 = false;
                     int num = 25;
                     int num2 = -1;
                     int num3 = -1;
                     for (int m = 0; m < num * num; m++)
                     {
                         num2 = genRand.Next(i - num, i + num + 1);
                         num3 = genRand.Next(j - num, j + num + 1);
                         if (Main.tile[num2, num3].wire())
{
                             flag2 = true;
                             break;
                         }
                     }
                     if (flag2)
                     {
                         int num4 = i;
                         int num5 = j;
                         Main.tile[num4, num5].wire(wire: true);
                         while (num4 != num2)
{
                             if (num4 < num2)
{
                                 num4++;
                             }
                             if (num4 > num2)
{
                                 num4--;
                             }
                             Main.tile[num4, num5].wire(wire: true);
                         }
                         while (num5 != num3)
{
                             if (num5 < num3)
{
                                 num5++;
                             }
                             if (num5 > num3)
{
                                 num5--;
                             }
                             Main.tile[num4, num5].wire(wire: true);
                         }
                     }
                     else if (Main.tile[i, j].type == 105)
                     {
                         num = 15;
                         bool flag3 = false;
                         for (int n = 0; n < num * num; n++)
{
                             num2 = i + genRand.Next(-num, num + 1);
                             num3 = j + genRand.Next(-num, num + 1);
                             PlaceTile(num2, num3, 135, mute: true, forced: true, -1, genRand.Next(2, 4));
                             if (Main.tile[num2, num3].type == 135)
{
                                 flag3 = true;
                                 break;
                             }
                         }
                         if (flag3)
{
                             int num6 = i;
                             int num7 = j;
                             Main.tile[num6, num7].wire(wire: true);
                             while (num6 != num2)
{
                                 if (num6 < num2)
{
                                     num6++;
                                 }
                                 if (num6 > num2)
{
                                     num6--;
                                 }
                                 Main.tile[num6, num7].wire(wire: true);
                             }
                             while (num7 != num3)
{
                                 if (num7 < num3)
{
                                     num7++;
                                 }
                                 if (num7 > num3)
{
                                     num7--;
                                 }
                                 Main.tile[num6, num7].wire(wire: true);
                             }
                         }
                     }
                 }
                 if (Main.tile[i, j].type == 467)
                 {
                     int num8 = 8;
                     for (int num9 = 0; num9 < num8 * num8; num9++)
                     {
                         int num10 = i + genRand.Next(-num8, num8 + 1);
                         int num11 = j + genRand.Next(-num8, num8 + 1);
                         if (Main.tile[num10, num11].type != 0 && Main.tile[num10, num11].type != 1 && !TileID.Sets.Ore[Main.tile[num10, num11].type] && Main.tile[num10, num11].type != 59 && Main.tile[num10, num11].type != 151)
{
                             continue;
                         }
                         bool flag4 = true;
                         for (int num12 = num10 - 1; num12 <= num10 + 1; num12++)
{
                             for (int num13 = num11 - 1; num13 <= num11 + 1; num13++)
{
                                 if (!SolidTile(num12, num13))
{
                                     flag4 = false;
                                 }
                             }
                         }
                         if (!flag4)
{
                             continue;
                         }
                         Tile tile2 = Main.tile[num10, num11];
                         tile2.type = 141;
                         tile2.frameX = (tile2.frameY = 0);
                         tile2.slope(0);
                         tile2.halfBrick(halfBrick: false);
                         TileFrame(num10, num11, resetFrame: true);
                         if (Main.tile[num10, num11].type != 141)
{
                             continue;
                         }
                         int num14 = i;
                         int num15 = j;
                         Main.tile[num14, num15].wire(wire: true);
                         while (num14 != num10)
{
                             if (num14 < num10)
{
                                 num14++;
                             }
                             if (num14 > num10)
{
                                 num14--;
                             }
                             Main.tile[num14, num15].wire(wire: true);
                         }
                         while (num15 != num11)
{
                             if (num15 < num11)
{
                                 num15++;
                             }
                             if (num15 > num11)
{
                                 num15--;
                             }
                             Main.tile[num14, num15].wire(wire: true);
                         }
                         break;
                     }
                 }
                 else
                 {
                     j++;
                 }
             }
         }
         Main.tileSolid[138] = true;
         for (int num16 = 0; num16 < 8000 && Main.chest[num16] != null; num16++)
         {
             if (genRand.Next(20) != 0 || Main.chest[num16].item[1].stack == 0)
             {
                 continue;
             }
             for (int num17 = 1; num17 < 40; num17++)
             {
                 if (Main.chest[num16].item[num17].stack == 0)
                 {
                     Main.chest[num16].item[num17].SetDefaults(5346);
                     break;
                 }
             }
         }
     }
References Tile.active(), Main.chest, Tile.frameX, Tile.frameY, Tile.halfBrick(), Chest.item, Main.maxTilesX, Main.maxTilesY, TileID.Sets.Ore, Item.SetDefaults(), Tile.slope(), SolidTile, Item.stack, Main.tile, Main.tileSolid, Tile.type, and Tile.wire().