Terraria: WorldGen.placeTrap
placeTrap()
static bool WorldGen.placeTrap (int x2, int y2, int type = -1) inline static
     {
         //IL_0008: Unknown result type (might be due to invalid IL or missing references)
         //IL_000d: Unknown result type (might be due to invalid IL or missing references)
         int num = y2;
         if (Vector2D.Distance(new Vector2D((double)x2, (double)y2), GenVars.shimmerPosition) < 100.0)
         {
             return false;
         }
         bool flag = false;
         bool flag2 = false;
         if (noTrapsWorldGen)
         {
             Main.tileSolid[138] = false;
         }
         while (!SolidTile(x2, num))
         {
             num++;
             if (num > Main.maxTilesY - 10)
             {
                 return false;
             }
             if (num >= Main.maxTilesY - 300)
             {
                 flag2 = true;
             }
         }
         if (noTrapsWorldGen)
         {
             Main.tileSolid[138] = true;
         }
         num--;
         if (!noTrapsWorldGen && IsTileNearby(x2, num, 70, 20))
         {
             return false;
         }
         if (Main.tile[x2, num].wall == 87)
         {
             return false;
         }
         if (Main.tile[x2, num].liquid > 0 && Main.tile[x2, num].lava())
         {
             flag = true;
         }
         if (Main.remixWorld)
         {
             if (type == -1 && genRand.Next(20) == 0)
             {
                 type = 2;
             }
             else if (type == -1 && (double)num < Main.rockLayer - 30.0 && genRand.Next(3) != 0)
             {
                 type = 3;
             }
             else if (type == -1)
             {
                 type = genRand.Next(2);
             }
         }
         else if (type == -1 && genRand.Next(20) == 0)
         {
             type = 2;
         }
         else if (type == -1 && num > GenVars.lavaLine + 30 && genRand.Next(6) != 0)
         {
             type = 3;
         }
         else if (type == -1)
         {
             type = genRand.Next(2);
         }
         if (!InWorld(x2, num, 3))
         {
             return false;
         }
         if (flag && type != 3)
         {
             return false;
         }
         if (flag2 && type != 3)
         {
             return false;
         }
         if (Main.tile[x2, num].nactive() || Main.tile[x2 - 1, num].nactive() || Main.tile[x2 + 1, num].nactive() || Main.tile[x2, num - 1].nactive() || Main.tile[x2 - 1, num - 1].nactive() || Main.tile[x2 + 1, num - 1].nactive() || Main.tile[x2, num - 2].nactive() || Main.tile[x2 - 1, num - 2].nactive() || Main.tile[x2 + 1, num - 2].nactive())
         {
             return false;
         }
         if (Main.tile[x2, num + 1].type == 48)
         {
             return false;
         }
         if (Main.tile[x2, num + 1].type == 232)
         {
             return false;
         }
         if (type == 1)
         {
             for (int i = x2 - 3; i <= x2 + 3; i++)
             {
                 for (int j = num - 3; j <= num + 3; j++)
                 {
                     if (Main.tile[i, j].type == 147 || Main.tile[i, j].type == 161)
                     {
                         type = 0;
                     }
                 }
             }
         }
         if (noTrapsWorldGen)
         {
             Main.tileSolid[138] = false;
         }
         switch (type)
         {
         case 0:
         {
             int num20 = x2;
             int num21 = num;
             num21 -= genRand.Next(3);
             while (!SolidTile(num20, num21) && !Main.tileCracked[Main.tile[num20, num21].type])
             {
                 num20--;
                 if (num20 < 0)
                 {
                     return false;
                 }
             }
             int num22 = num20;
             num20 = x2;
             while (!SolidTile(num20, num21) && !Main.tileCracked[Main.tile[num20, num21].type])
             {
                 num20++;
                 if (num20 > Main.maxTilesX)
                 {
                     return false;
                 }
             }
             int num23 = num20;
             int num24 = x2 - num22;
             int num25 = num23 - x2;
             bool flag5 = false;
             bool flag6 = false;
             if (num24 > 5 && num24 < 50)
             {
                 flag5 = true;
             }
             if (num25 > 5 && num25 < 50)
             {
                 flag6 = true;
             }
             if (flag5 && !SolidTile(num22, num21 + 1))
             {
                 flag5 = false;
             }
             if (flag6 && !SolidTile(num23, num21 + 1))
             {
                 flag6 = false;
             }
             if (flag5 && (Main.tile[num22, num21].type == 10 || Main.tile[num22, num21].type == 48 || Main.tile[num22, num21 + 1].type == 10 || Main.tile[num22, num21 + 1].type == 48))
             {
                 flag5 = false;
             }
             if (flag6 && (Main.tile[num23, num21].type == 10 || Main.tile[num23, num21].type == 48 || Main.tile[num23, num21 + 1].type == 10 || Main.tile[num23, num21 + 1].type == 48))
             {
                 flag6 = false;
             }
             int num26 = 0;
             if (flag5 && flag6)
             {
                 num26 = 1;
                 num20 = num22;
                 if (genRand.Next(2) == 0)
                 {
                     num20 = num23;
                     num26 = -1;
                 }
             }
             else if (flag6)
             {
                 num20 = num23;
                 num26 = -1;
             }
             else
             {
                 if (!flag5)
                 {
                     trapDiag[type, 0]++;
                     return false;
                 }
                 num20 = num22;
                 num26 = 1;
             }
             if (Main.tile[num20, num21].type == 190)
             {
                 trapDiag[type, 0]++;
                 return false;
             }
             if (Main.tile[x2, num].wall > 0)
             {
                 PlaceTile(x2, num, 135, mute: true, forced: true, -1, 2);
             }
             else
             {
                 PlaceTile(x2, num, 135, mute: true, forced: true, -1, genRand.Next(2, 4));
             }
             KillTile(num20, num21);
             PlaceTile(num20, num21, 137, mute: true, forced: true);
             if (num26 == 1)
             {
                 Main.tile[num20, num21].frameX += 18;
             }
             int num27 = x2;
             int num28 = num;
             while (num27 != num20 || num28 != num21)
             {
                 Main.tile[num27, num28].wire(wire: true);
                 if (num27 > num20)
                 {
                     num27--;
                 }
                 if (num27 < num20)
                 {
                     num27++;
                 }
                 Main.tile[num27, num28].wire(wire: true);
                 if (num28 > num21)
                 {
                     num28--;
                 }
                 if (num28 < num21)
                 {
                     num28++;
                 }
                 Main.tile[num27, num28].wire(wire: true);
             }
             trapDiag[type, 1]++;
             return true;
         }
         case 1:
         {
             if (noTrapsWorldGen)
             {
                 Main.tileSolid[138] = true;
             }
             int num3 = x2;
             int num4 = num - 8;
             num3 += genRand.Next(-1, 2);
             if (noTrapsWorldGen)
             {
                 if (IsTileNearby(num3, num4, 138, 6))
                 {
                     return false;
                 }
                 if (IsTileNearby(num3, num4, 664, 6))
                 {
                     return false;
                 }
             }
             else
             {
                 if (IsTileNearby(num3, num4, 138, 10))
                 {
                     return false;
                 }
                 if (IsTileNearby(num3, num4, 664, 10))
                 {
                     return false;
                 }
                 if (IsTileNearby(num3, num4, 665, 10))
                 {
                     return false;
                 }
             }
             bool flag3 = true;
             while (flag3)
             {
                 bool flag4 = true;
                 int num5 = 0;
                 for (int m = num3 - 2; m <= num3 + 3; m++)
                 {
                     for (int n = num4; n <= num4 + 3; n++)
                     {
                         if (!SolidTile(m, n))
{
                             flag4 = false;
                         }
                         if (Main.tile[m, n].active())
{
                             if (Main.tile[m, n].type == 226)
{
                                 trapDiag[type, 0]++;
                                 return false;
                             }
                             if (Main.tile[m, n].type == 0 || Main.tile[m, n].type == 1 || Main.tile[m, n].type == 59)
{
                                 num5++;
                             }
                         }
                     }
                 }
                 num4--;
                 if ((double)num4 < Main.worldSurface)
                 {
                     trapDiag[type, 0]++;
                     return false;
                 }
                 if (flag4 && num5 > 2)
                 {
                     flag3 = false;
                 }
             }
             if (num - num4 <= 5 || num - num4 >= 40)
             {
                 trapDiag[type, 0]++;
                 return false;
             }
             for (int num6 = num3; num6 <= num3 + 1; num6++)
             {
                 for (int num7 = num4; num7 <= num; num7++)
                 {
                     KillTile(num6, num7);
                 }
             }
             for (int num8 = num3 - 2; num8 <= num3 + 3; num8++)
             {
                 for (int num9 = num4 - 2; num9 <= num4 + 3; num9++)
                 {
                     if (SolidTile(num8, num9))
                     {
                         Main.tile[num8, num9].type = 1;
                     }
                 }
             }
             if (IsTileNearby(num3, num4, 21, 4) || IsTileNearby(num3, num4, 467, 4))
             {
                 trapDiag[type, 0]++;
                 return false;
             }
             PlaceTile(x2, num, 135, mute: true, forced: true, -1, 7);
             PlaceTile(num3, num4 + 2, 130, mute: true);
             PlaceTile(num3 + 1, num4 + 2, 130, mute: true);
             if ((tenthAnniversaryWorldGen || noTrapsWorldGen) && genRand.Next(3) == 0)
             {
                 PlaceTile(num3 + 1, num4 + 1, 664, mute: true);
             }
             else
             {
                 PlaceTile(num3 + 1, num4 + 1, 138, mute: true);
             }
             num4 += 2;
             Main.tile[num3, num4].wire(wire: true);
             Main.tile[num3 + 1, num4].wire(wire: true);
             num4++;
             PlaceTile(num3, num4, 130, mute: true);
             PlaceTile(num3 + 1, num4, 130, mute: true);
             Main.tile[num3, num4].wire(wire: true);
             Main.tile[num3 + 1, num4].wire(wire: true);
             PlaceTile(num3, num4 + 1, 130, mute: true);
             PlaceTile(num3 + 1, num4 + 1, 130, mute: true);
             Main.tile[num3, num4 + 1].wire(wire: true);
             Main.tile[num3 + 1, num4 + 1].wire(wire: true);
             int num10 = x2;
             int num11 = num;
             while (num10 != num3 || num11 != num4)
             {
                 Main.tile[num10, num11].wire(wire: true);
                 if (num10 > num3)
                 {
                     num10--;
                 }
                 if (num10 < num3)
                 {
                     num10++;
                 }
                 Main.tile[num10, num11].wire(wire: true);
                 if (num11 > num4)
                 {
                     num11--;
                 }
                 if (num11 < num4)
                 {
                     num11++;
                 }
                 Main.tile[num10, num11].wire(wire: true);
             }
             trapDiag[type, 1]++;
             return true;
         }
         case 2:
         {
             int num12 = genRand.Next(4, 7);
             int num13 = x2;
             num13 += genRand.Next(-1, 2);
             int num14 = num;
             for (int num15 = 0; num15 < num12; num15++)
             {
                 num14++;
                 if (!SolidTile(num13, num14))
                 {
                     trapDiag[type, 0]++;
                     return false;
                 }
             }
             for (int num16 = num13 - 2; num16 <= num13 + 2; num16++)
             {
                 for (int num17 = num14 - 2; num17 <= num14 + 2; num17++)
                 {
                     if (!SolidTile(num16, num17))
                     {
                         return false;
                     }
                 }
             }
             KillTile(num13, num14);
             Main.tile[num13, num14].active(active: true);
             Main.tile[num13, num14].type = 141;
             Main.tile[num13, num14].frameX = 0;
             Main.tile[num13, num14].frameY = (short)(18 * genRand.Next(2));
             PlaceTile(x2, num, 135, mute: true, forced: true, -1, genRand.Next(2, 4));
             int num18 = x2;
             int num19 = num;
             while (num18 != num13 || num19 != num14)
             {
                 Main.tile[num18, num19].wire(wire: true);
                 if (num18 > num13)
                 {
                     num18--;
                 }
                 if (num18 < num13)
                 {
                     num18++;
                 }
                 Main.tile[num18, num19].wire(wire: true);
                 if (num19 > num14)
                 {
                     num19--;
                 }
                 if (num19 < num14)
                 {
                     num19++;
                 }
                 Main.tile[num18, num19].wire(wire: true);
             }
             trapDiag[type, 1]++;
             break;
         }
         case 3:
         {
             if (Main.tile[x2 + 1, num].active())
             {
                 return false;
             }
             if (Main.tile[x2, num].liquid > 0 && !Main.tile[x2, num].lava())
             {
                 return false;
             }
             if (noTrapsWorldGen && (tenthAnniversaryWorldGen || notTheBees))
             {
                 if (genRand.Next(3) != 0)
                 {
                     return false;
                 }
                 if (IsTileNearby(x2, num, 443, 30))
                 {
                     return false;
                 }
             }
             for (int k = x2; k <= x2 + 1; k++)
             {
                 int j2 = num + 1;
                 if (!SolidTile(k, j2))
                 {
                     return false;
                 }
             }
             int num2 = genRand.Next(2);
             for (int l = 0; l < 2; l++)
             {
                 Main.tile[x2 + l, num].active(active: true);
                 Main.tile[x2 + l, num].type = 443;
                 Main.tile[x2 + l, num].frameX = (short)(18 * l + 36 * num2);
                 Main.tile[x2 + l, num].frameY = 0;
             }
             return true;
         }
         }
         if (noTrapsWorldGen)
         {
             Main.tileSolid[138] = true;
         }
         return false;
     }
References Tile.active(), Vector2D.Distance(), Tile.frameX, Tile.frameY, genRand, InWorld(), IsTileNearby(), KillTile(), Tile.lava(), GenVars.lavaLine, Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.nactive(), UnifiedRandom.Next(), noTrapsWorldGen, notTheBees, PlaceTile(), Main.remixWorld, Main.rockLayer, GenVars.shimmerPosition, SolidTile(), tenthAnniversaryWorldGen, Main.tile, Main.tileCracked, Main.tileSolid, trapDiag, Tile.type, Tile.wall, Tile.wire(), and Main.worldSurface.