Terraria: WorldGen.moveRoom
moveRoom()
static void WorldGen.moveRoom (int x, int y, int n) inline static
     {
         if (Main.netMode == 1)
         {
             NetMessage.SendData(60, -1, -1, null, n, x, y);
             return;
         }
         prioritizedTownNPCType = Main.npc[n].type;
         Main.npc[n].homeless = true;
         SpawnTownNPC(x, y);
         TownManager.SetRoom(Main.npc[n].type, Main.npc[n].homeTileX, Main.npc[n].homeTileY);
     }
References NPC.homeless, NPC.homeTileX, NPC.homeTileY, Main.netMode, Main.npc, prioritizedTownNPCType, NetMessage.SendData(), TownRoomManager.SetRoom(), SpawnTownNPC(), TownManager, and NPC.type.
Referenced by Main.DrawInterface_38_MouseCarriedObject(), and MessageBuffer.GetData().