Terraria: WorldGen.RightEdgeCanBeAttachedTo
RightEdgeCanBeAttachedTo()
static bool WorldGen.RightEdgeCanBeAttachedTo (int i, int j) inline static
     {
         try
         {
             Tile tile = Main.tile[i, j];
             if (tile == null)
             {
                 return true;
             }
             if (tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type] && !tile.rightSlope() && !tile.halfBrick() && !tile.inActive() && !Main.tileNoAttach[tile.type])
             {
                 return true;
             }
         }
         catch
         {
         }
         return false;
     }
References Tile.active(), Tile.halfBrick(), Tile.inActive(), Tile.rightSlope(), Main.tile, Main.tileNoAttach, Main.tileSolid, Main.tileSolidTop, and Tile.type.