Terraria: WorldGen.PaintTheSand
PaintTheSand()
static void WorldGen.PaintTheSand (byte tilePaintColor, byte wallPaintColor) inline static private
     {
         for (int i = 20; i < Main.maxTilesX - 20; i++)
         {
             for (int j = 20; j < Main.maxTilesY - 20; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile.active() && (tile.type == 53 || tile.type == 396 || tile.type == 397))
                 {
                     tile.color(tilePaintColor);
                     if ((double)j > Main.worldSurface)
                     {
                         if (Main.tile[i, j - 1].type == 165 || Main.tile[i, j - 1].type == 185 || Main.tile[i, j - 1].type == 186 || Main.tile[i, j - 1].type == 187)
{
                             Main.tile[i, j - 1].color(tilePaintColor);
                         }
                         if (Main.tile[i, j - 2].type == 165 || Main.tile[i, j - 2].type == 185 || Main.tile[i, j - 2].type == 186 || Main.tile[i, j - 2].type == 187)
{
                             Main.tile[i, j - 2].color(tilePaintColor);
                         }
                         if (Main.tile[i, j + 1].type == 165)
{
                             Main.tile[i, j + 1].color(tilePaintColor);
                         }
                         if (Main.tile[i, j + 2].type == 165)
{
                             Main.tile[i, j + 2].color(tilePaintColor);
                         }
                     }
                 }
                 if (tile.wall == 187 || tile.wall == 216)
                 {
                     tile.wallColor(tilePaintColor);
                 }
             }
         }
     }
References Tile.active(), Tile.color(), Main.maxTilesX, Main.maxTilesY, Main.tile, Tile.type, Tile.wall, Tile.wallColor(), and Main.worldSurface.