Terraria: WorldGen.AddLifeCrystal
AddLifeCrystal()
static bool WorldGen.AddLifeCrystal (int i, int j) inline static
     {
         for (int k = j; k < Main.maxTilesY; k++)
         {
             if (Main.tile[i, k].active() && Main.tileSolid[Main.tile[i, k].type])
             {
                 int num = k - 1;
                 if (Main.tile[i, num - 1].lava() || Main.tile[i - 1, num - 1].lava())
                 {
                     return false;
                 }
                 if (Main.tile[i, num - 1].shimmer())
                 {
                     return false;
                 }
                 if (!EmptyTileCheck(i - 1, i, num - 1, num))
                 {
                     return false;
                 }
                 if (Main.wallDungeon[Main.tile[i, num].wall])
                 {
                     return false;
                 }
                 Tile tile = Main.tile[i - 1, num + 1];
                 Tile tile2 = Main.tile[i, num + 1];
                 if (!tile.nactive() || !Main.tileSolid[tile.type])
                 {
                     return false;
                 }
                 if (!tile2.nactive() || !Main.tileSolid[tile2.type])
                 {
                     return false;
                 }
                 if (tile.blockType() != 0)
                 {
                     tile.slope(0);
                     tile.halfBrick(halfBrick: false);
                 }
                 if (tile2.blockType() != 0)
                 {
                     tile2.slope(0);
                     tile2.halfBrick(halfBrick: false);
                 }
                 Main.tile[i - 1, num - 1].active(active: true);
                 Main.tile[i - 1, num - 1].type = 12;
                 Main.tile[i - 1, num - 1].frameX = 0;
                 Main.tile[i - 1, num - 1].frameY = 0;
                 Main.tile[i, num - 1].active(active: true);
                 Main.tile[i, num - 1].type = 12;
                 Main.tile[i, num - 1].frameX = 18;
                 Main.tile[i, num - 1].frameY = 0;
                 Main.tile[i - 1, num].active(active: true);
                 Main.tile[i - 1, num].type = 12;
                 Main.tile[i - 1, num].frameX = 0;
                 Main.tile[i - 1, num].frameY = 18;
                 Main.tile[i, num].active(active: true);
                 Main.tile[i, num].type = 12;
                 Main.tile[i, num].frameX = 18;
                 Main.tile[i, num].frameY = 18;
                 return true;
             }
         }
         return false;
     }
References Tile.active(), Tile.blockType(), Tile.frameX, Tile.frameY, Tile.halfBrick(), Tile.lava(), Main.maxTilesY, Tile.nactive(), Tile.shimmer(), Tile.slope(), Main.tile, Main.tileSolid, Tile.type, Tile.wall, and Main.wallDungeon.