Terraria: WorldGen.paintColor
paintColor()
static Color WorldGen.paintColor (int color) inline static
     {
         Color white = Color.White;
         if (color == 1 || color == 13)
         {
             white.R = byte.MaxValue;
             white.G = 0;
             white.B = 0;
         }
         if (color == 2 || color == 14)
         {
             white.R = byte.MaxValue;
             white.G = 127;
             white.B = 0;
         }
         if (color == 3 || color == 15)
         {
             white.R = byte.MaxValue;
             white.G = byte.MaxValue;
             white.B = 0;
         }
         if (color == 4 || color == 16)
         {
             white.R = 127;
             white.G = byte.MaxValue;
             white.B = 0;
         }
         if (color == 5 || color == 17)
         {
             white.R = 0;
             white.G = byte.MaxValue;
             white.B = 0;
         }
         if (color == 6 || color == 18)
         {
             white.R = 0;
             white.G = byte.MaxValue;
             white.B = 127;
         }
         if (color == 7 || color == 19)
         {
             white.R = 0;
             white.G = byte.MaxValue;
             white.B = byte.MaxValue;
         }
         if (color == 8 || color == 20)
         {
             white.R = 0;
             white.G = 127;
             white.B = byte.MaxValue;
         }
         if (color == 9 || color == 21)
         {
             white.R = 0;
             white.G = 0;
             white.B = byte.MaxValue;
         }
         if (color == 10 || color == 22)
         {
             white.R = 127;
             white.G = 0;
             white.B = byte.MaxValue;
         }
         if (color == 11 || color == 23)
         {
             white.R = byte.MaxValue;
             white.G = 0;
             white.B = byte.MaxValue;
         }
         if (color == 12 || color == 24)
         {
             white.R = byte.MaxValue;
             white.G = 0;
             white.B = 127;
         }
         if (color == 25)
         {
             white.R = 75;
             white.G = 75;
             white.B = 75;
         }
         if (color == 26)
         {
             white.R = byte.MaxValue;
             white.G = byte.MaxValue;
             white.B = byte.MaxValue;
         }
         if (color == 27)
         {
             white.R = 175;
             white.G = 175;
             white.B = 175;
         }
         if (color == 28)
         {
             white.R = byte.MaxValue;
             white.G = 178;
             white.B = 125;
         }
         if (color == 29)
         {
             white.R = 25;
             white.G = 25;
             white.B = 25;
         }
         if (color == 30)
         {
             white.R = 200;
             white.G = 200;
             white.B = 200;
             white.A = 150;
         }
         return white;
     }
References Color.
Referenced by TileLightScanner.ApplyTileLight(), TileDrawing.DrawTrees(), MapHelper.MapColor(), and Main.TryApplyingPlayerStringColor().