Terraria: WorldGen.LaunchRocket
LaunchRocket()
static void WorldGen.LaunchRocket (int x, int y, bool fromWiring) inline static
     {
         int num = Main.tile[x, y].frameY;
         int num2 = 0;
         while (num >= 40)
         {
             num -= 40;
             num2++;
         }
         if (num == 18)
         {
             y--;
         }
         Vector2 vector = new Vector2(x * 16 + 8, y * 16 + 4);
         int type = 167 + num2;
         int damage = 150;
         int num3 = 7;
         int num4 = Projectile.NewProjectile(GetProjectileSource_PlayerOrWires(x, y, fromWiring, Main.LocalPlayer), vector.X, vector.Y + 2f, 0f, -8f, type, damage, num3, Main.myPlayer);
         Main.projectile[num4].originatedFromActivableTile = true;
         Main.tile[x, y].active(active: false);
         Main.tile[x, y + 1].active(active: false);
         NetMessage.SendTileSquare(-1, x, y, 1, 2);
     }
References Tile.active(), Tile.frameY, Main.LocalPlayer, Main.myPlayer, Projectile.NewProjectile(), Projectile.originatedFromActivableTile, Main.projectile, NetMessage.SendTileSquare(), and Main.tile.
Referenced by Wiring.HitWireSingle(), and Player.TileInteractionsUse().