Terraria: WorldGen.HellFort
HellFort()
static void WorldGen.HellFort (int i, int j, ushort tileType = 75, byte wallType = 14) inline static
     {
         int[] array = new int[5];
         int[] array2 = new int[5];
         int[] array3 = new int[10];
         int[] array4 = new int[10];
         int num = 8;
         int num2 = 20;
         if (drunkWorldGen)
         {
             num /= 2;
             num2 *= 2;
         }
         array[2] = i - genRand.Next(num / 2, num2 / 2);
         array2[2] = i + genRand.Next(num / 2, num2 / 2);
         array[3] = array2[2];
         array2[3] = array[3] + genRand.Next(num, num2);
         array[4] = array2[3];
         array2[4] = array[4] + genRand.Next(num, num2);
         array2[1] = array[2];
         array[1] = array2[1] - genRand.Next(num, num2);
         array2[0] = array[1];
         array[0] = array2[0] - genRand.Next(num, num2);
         num = 6;
         num2 = 12;
         array3[3] = j - genRand.Next(num, num2);
         array4[3] = j;
         for (int k = 4; k < 10; k++)
         {
             array3[k] = array4[k - 1];
             array4[k] = array3[k] + genRand.Next(num, num2);
         }
         for (int num3 = 2; num3 >= 0; num3--)
         {
             array4[num3] = array3[num3 + 1];
             array3[num3] = array4[num3] - genRand.Next(num, num2);
         }
         bool flag = false;
         bool flag2 = false;
         bool[,] array5 = new bool[5, 10];
         int num4 = 3;
         int num5 = 3;
         for (int l = 0; l < 2; l++)
         {
             if (genRand.Next(3) == 0 || drunkWorldGen)
             {
                 flag = true;
                 int num6 = genRand.Next(10);
                 if (num6 < num4)
                 {
                     num4 = num6;
                 }
                 if (num6 > num5)
                 {
                     num5 = num6;
                 }
                 int num7 = 1;
                 if (genRand.Next(2) == 0 || drunkWorldGen)
                 {
                     array5[0, num6] = true;
                     array5[1, num6] = true;
                     num7 = 0;
                 }
                 else
                 {
                     array5[1, num6] = true;
                 }
                 int num8 = genRand.Next(2);
                 if (num8 == 0)
                 {
                     num8 = -1;
                 }
                 int num9 = genRand.Next(10);
                 while (num9 > 0 && num6 >= 0 && num6 < 10)
                 {
                     array5[num7, num6] = true;
                     num6 += num8;
                 }
             }
             if (genRand.Next(3) == 0 || drunkWorldGen)
             {
                 flag2 = true;
                 int num10 = genRand.Next(10);
                 if (num10 < num4)
                 {
                     num4 = num10;
                 }
                 if (num10 > num5)
                 {
                     num5 = num10;
                 }
                 int num11 = 3;
                 if (genRand.Next(2) == 0 || drunkWorldGen)
                 {
                     array5[3, num10] = true;
                     array5[4, num10] = true;
                     num11 = 4;
                 }
                 else
                 {
                     array5[3, num10] = true;
                 }
                 int num12 = genRand.Next(2);
                 if (num12 == 0)
                 {
                     num12 = -1;
                 }
                 int num13 = genRand.Next(10);
                 while (num13 > 0 && num10 >= 0 && num10 < 10)
                 {
                     array5[num11, num10] = true;
                     num10 += num12;
                 }
             }
         }
         for (int m = 0; m < 5; m++)
         {
             int num14 = array[m];
             bool flag3 = false;
             if (num14 < 10 || num14 > Main.maxTilesX - 10)
             {
                 flag3 = true;
             }
             else
             {
                 for (int n = Main.UnderworldLayer; n < Main.maxTilesY; n++)
                 {
                     if (Main.tile[num14, n].wall > 0)
                     {
                         flag3 = true;
                     }
                 }
             }
             if (flag3)
             {
                 for (int num15 = 0; num15 < 10; num15++)
                 {
                     array5[m, num15] = false;
                 }
             }
         }
         int num16 = genRand.Next(10);
         if (num16 < num4)
         {
             num4 = num16;
         }
         num16 = genRand.Next(10);
         if (num16 > num5)
         {
             num5 = num16;
         }
         if (!flag && !flag2)
         {
             while (num5 - num4 < 5)
             {
                 num16 = genRand.Next(10);
                 if (num16 < num4)
                 {
                     num4 = num16;
                 }
                 num16 = genRand.Next(10);
                 if (num16 > num5)
                 {
                     num5 = num16;
                 }
             }
         }
         for (int num17 = num4; num17 <= num5; num17++)
         {
             array5[2, num17] = true;
         }
         for (int num18 = 0; num18 < 5; num18++)
         {
             for (int num19 = 0; num19 < 10; num19++)
             {
                 if (array5[num18, num19] && (array3[num19] < Main.UnderworldLayer || array4[num19] > Main.maxTilesY - 20))
                 {
                     array5[num18, num19] = false;
                 }
             }
         }
         for (int num20 = 0; num20 < 5; num20++)
         {
             for (int num21 = 0; num21 < 10; num21++)
             {
                 if (!array5[num20, num21])
                 {
                     continue;
                 }
                 for (int num22 = array[num20]; num22 <= array2[num20]; num22++)
                 {
                     for (int num23 = array3[num21]; num23 <= array4[num21]; num23++)
                     {
                         if (num22 < 10)
{
                             break;
                         }
                         if (num22 > Main.maxTilesX - 10)
{
                             break;
                         }
                         Main.tile[num22, num23].liquid = 0;
                         if (num22 == array[num20] || num22 == array2[num20] || num23 == array3[num21] || num23 == array4[num21])
{
                             Main.tile[num22, num23].active(active: true);
                             Main.tile[num22, num23].type = tileType;
                             Main.tile[num22, num23].halfBrick(halfBrick: false);
                             Main.tile[num22, num23].slope(0);
                         }
                         else
{
                             Main.tile[num22, num23].wall = wallType;
                             Main.tile[num22, num23].active(active: false);
                         }
                     }
                 }
             }
         }
         int style = 19;
         int style2 = 13;
         for (int num24 = 0; num24 < 4; num24++)
         {
             bool[] array6 = new bool[10];
             bool flag4 = false;
             for (int num25 = 0; num25 < 10; num25++)
             {
                 if (array5[num24, num25] && array5[num24 + 1, num25])
                 {
                     array6[num25] = true;
                     flag4 = true;
                 }
             }
             while (flag4)
             {
                 int num26 = genRand.Next(10);
                 if (array6[num26])
                 {
                     flag4 = false;
                     Main.tile[array2[num24], array4[num26] - 1].active(active: false);
                     Main.tile[array2[num24], array4[num26] - 2].active(active: false);
                     Main.tile[array2[num24], array4[num26] - 3].active(active: false);
                     Main.tile[array2[num24], array4[num26] - 1].wall = wallType;
                     Main.tile[array2[num24], array4[num26] - 2].wall = wallType;
                     Main.tile[array2[num24], array4[num26] - 3].wall = wallType;
                     PlaceTile(array2[num24], array4[num26] - 1, 10, mute: true, forced: false, -1, style);
                 }
             }
         }
         for (int num27 = 0; num27 < 5; num27++)
         {
             for (int num28 = 0; num28 < 10; num28++)
             {
                 if (!array5[num27, num28])
                 {
                     continue;
                 }
                 if (num28 > 0 && array5[num27, num28 - 1])
                 {
                     int num29 = genRand.Next(array[num27] + 2, array2[num27] - 1);
                     int num30 = genRand.Next(array[num27] + 2, array2[num27] - 1);
                     int num31 = 0;
                     while (num30 - num29 < 2 || num30 - num29 > 5)
                     {
                         num29 = genRand.Next(array[num27] + 2, array2[num27] - 1);
                         num30 = genRand.Next(array[num27] + 2, array2[num27] - 1);
                         num31++;
                         if (num31 > 10000)
{
                             break;
                         }
                     }
                     if (num31 > 10000)
                     {
                         break;
                     }
                     for (int num32 = num29; num32 <= num30 && num32 >= 20 && num32 <= Main.maxTilesX - 20; num32++)
                     {
                         Main.tile[num32, array3[num28]].active(active: false);
                         PlaceTile(num32, array3[num28], 19, mute: true, forced: true, -1, style2);
                         Main.tile[num32, array3[num28]].wall = wallType;
                     }
                 }
                 if (num27 < 4 && array5[num27 + 1, num28] && genRand.Next(3) == 0)
                 {
                     Main.tile[array2[num27], array4[num28] - 1].active(active: false);
                     Main.tile[array2[num27], array4[num28] - 2].active(active: false);
                     Main.tile[array2[num27], array4[num28] - 3].active(active: false);
                     Main.tile[array2[num27], array4[num28] - 1].wall = wallType;
                     Main.tile[array2[num27], array4[num28] - 2].wall = wallType;
                     Main.tile[array2[num27], array4[num28] - 3].wall = wallType;
                     PlaceTile(array2[num27], array4[num28] - 1, 10, mute: true, forced: false, -1, style);
                 }
             }
         }
         bool flag5 = false;
         for (int num33 = 0; num33 < 5; num33++)
         {
             bool[] array7 = new bool[10];
             for (int num34 = 0; num34 < 10; num34++)
             {
                 if (array5[num33, num34])
                 {
                     flag5 = true;
                     array7[num34] = true;
                 }
             }
             if (!flag5)
             {
                 continue;
             }
             bool flag6 = false;
             for (int num35 = 0; num35 < 10; num35++)
             {
                 if (array7[num35])
                 {
                     if (!Main.tile[array[num33] - 1, array4[num35] - 1].active() && !Main.tile[array[num33] - 1, array4[num35] - 2].active() && !Main.tile[array[num33] - 1, array4[num35] - 3].active() && Main.tile[array[num33] - 1, array4[num35] - 1].liquid == 0 && Main.tile[array[num33] - 1, array4[num35] - 2].liquid == 0 && Main.tile[array[num33] - 1, array4[num35] - 3].liquid == 0)
                     {
                         flag6 = true;
                     }
                     else
                     {
                         array7[num35] = false;
                     }
                 }
             }
             while (flag6)
             {
                 int num36 = genRand.Next(10);
                 if (array7[num36])
                 {
                     flag6 = false;
                     Main.tile[array[num33], array4[num36] - 1].active(active: false);
                     Main.tile[array[num33], array4[num36] - 2].active(active: false);
                     Main.tile[array[num33], array4[num36] - 3].active(active: false);
                     PlaceTile(array[num33], array4[num36] - 1, 10, mute: true, forced: false, -1, style);
                 }
             }
             break;
         }
         bool flag7 = false;
         for (int num37 = 4; num37 >= 0; num37--)
         {
             bool[] array8 = new bool[10];
             for (int num38 = 0; num38 < 10; num38++)
             {
                 if (array5[num37, num38])
                 {
                     flag7 = true;
                     array8[num38] = true;
                 }
             }
             if (flag7)
             {
                 bool flag8 = false;
                 for (int num39 = 0; num39 < 10; num39++)
                 {
                     if (array8[num39])
                     {
                         if (num37 < 20 || num37 > Main.maxTilesX - 20)
{
                             break;
                         }
                         if (!Main.tile[array2[num37] + 1, array4[num39] - 1].active() && !Main.tile[array2[num37] + 1, array4[num39] - 2].active() && !Main.tile[array2[num37] + 1, array4[num39] - 3].active() && Main.tile[array2[num37] + 1, array4[num39] - 1].liquid == 0 && Main.tile[array2[num37] + 1, array4[num39] - 2].liquid == 0 && Main.tile[array2[num37] + 1, array4[num39] - 3].liquid == 0)
{
                             flag8 = true;
                         }
                         else
{
                             array8[num39] = false;
                         }
                     }
                 }
                 while (flag8)
                 {
                     int num40 = genRand.Next(10);
                     if (array8[num40])
                     {
                         flag8 = false;
                         Main.tile[array2[num37], array4[num40] - 1].active(active: false);
                         Main.tile[array2[num37], array4[num40] - 2].active(active: false);
                         Main.tile[array2[num37], array4[num40] - 3].active(active: false);
                         PlaceTile(array2[num37], array4[num40] - 1, 10, mute: true, forced: false, -1, style);
                     }
                 }
                 break;
             }
         }
         bool flag9 = false;
         for (int num41 = 0; num41 < 10; num41++)
         {
             bool[] array9 = new bool[10];
             for (int num42 = 0; num42 < 5; num42++)
             {
                 if (array5[num42, num41])
                 {
                     flag9 = true;
                     array9[num42] = true;
                 }
             }
             if (!flag9)
             {
                 continue;
             }
             bool flag10 = true;
             while (flag10)
             {
                 int num43 = genRand.Next(5);
                 if (!array9[num43])
                 {
                     continue;
                 }
                 int num44 = genRand.Next(array[num43] + 2, array2[num43] - 1);
                 int num45 = genRand.Next(array[num43] + 2, array2[num43] - 1);
                 int num46 = 0;
                 while (num45 - num44 < 2 || num45 - num44 > 5)
                 {
                     num44 = genRand.Next(array[num43] + 2, array2[num43] - 1);
                     num45 = genRand.Next(array[num43] + 2, array2[num43] - 1);
                     num46++;
                     if (num46 > 10000)
                     {
                         break;
                     }
                 }
                 if (num46 > 10000)
                 {
                     break;
                 }
                 for (int num47 = num44; num47 <= num45 && num47 >= 10 && num47 <= Main.maxTilesX - 10; num47++)
                 {
                     if (Main.tile[num47, array3[num41] - 1].active() || Main.tile[num47, array3[num41] - 1].liquid > 0)
                     {
                         flag10 = false;
                     }
                 }
                 if (flag10)
                 {
                     for (int num48 = num44; num48 <= num45 && num48 >= 10 && num48 <= Main.maxTilesX - 10; num48++)
                     {
                         Main.tile[num48, array3[num41]].active(active: false);
                         PlaceTile(num48, array3[num41], 19, mute: true, forced: true, -1, style2);
                     }
                 }
                 flag10 = false;
             }
             break;
         }
     }
References Tile.active(), Tile.halfBrick(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.slope(), Main.tile, Tile.type, Main.UnderworldLayer, and Tile.wall.