Terraria: WorldGen.setBG
setBG()
static void WorldGen.setBG (int bg, int style) inline static
     {
         switch (bg)
         {
         case 0:
             treeBG1 = style;
             SetForestBGSet(style, Main.treeMntBGSet1, Main.treeBGSet1);
             break;
         case 10:
             treeBG2 = style;
             SetForestBGSet(style, Main.treeMntBGSet2, Main.treeBGSet2);
             break;
         case 11:
             treeBG3 = style;
             SetForestBGSet(style, Main.treeMntBGSet3, Main.treeBGSet3);
             break;
         case 12:
             treeBG4 = style;
             SetForestBGSet(style, Main.treeMntBGSet4, Main.treeBGSet4);
             break;
         case 1:
             corruptBG = style;
             switch (style)
             {
             default:
                 Main.corruptBG[0] = 12;
                 Main.corruptBG[1] = 13;
                 Main.corruptBG[2] = 14;
                 break;
             case 1:
                 Main.corruptBG[0] = 56;
                 Main.corruptBG[1] = 57;
                 Main.corruptBG[2] = 58;
                 break;
             case 2:
                 Main.corruptBG[0] = 211;
                 Main.corruptBG[1] = 212;
                 Main.corruptBG[2] = 213;
                 break;
             case 3:
                 Main.corruptBG[0] = 225;
                 Main.corruptBG[1] = 226;
                 Main.corruptBG[2] = 227;
                 break;
             case 4:
                 Main.corruptBG[0] = 240;
                 Main.corruptBG[1] = 241;
                 Main.corruptBG[2] = 242;
                 break;
             }
             break;
         case 2:
             jungleBG = style;
             switch (style)
             {
             default:
                 Main.jungleBG[0] = 15;
                 Main.jungleBG[1] = 16;
                 Main.jungleBG[2] = 17;
                 break;
             case 1:
                 Main.jungleBG[0] = 59;
                 Main.jungleBG[1] = 60;
                 Main.jungleBG[2] = 61;
                 break;
             case 2:
                 Main.jungleBG[0] = 222;
                 Main.jungleBG[1] = 223;
                 Main.jungleBG[2] = 224;
                 break;
             case 3:
                 Main.jungleBG[0] = 237;
                 Main.jungleBG[1] = 238;
                 Main.jungleBG[2] = 239;
                 break;
             case 4:
                 Main.jungleBG[0] = 284;
                 Main.jungleBG[1] = 285;
                 Main.jungleBG[2] = 286;
                 break;
             case 5:
                 Main.jungleBG[0] = 271;
                 Main.jungleBG[1] = 272;
                 Main.jungleBG[2] = 273;
                 break;
             }
             break;
         case 3:
             snowBG = style;
             Main.snowMntBG[0] = 35;
             Main.snowMntBG[1] = 36;
             switch (style)
             {
             default:
                 Main.snowBG[0] = 37;
                 Main.snowBG[1] = 38;
                 Main.snowBG[2] = 39;
                 break;
             case 1:
                 Main.snowBG[0] = 97;
                 Main.snowBG[1] = 96;
                 Main.snowBG[2] = 95;
                 break;
             case 2:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 99;
                 Main.snowBG[0] = -1;
                 Main.snowBG[1] = -1;
                 Main.snowBG[2] = -1;
                 break;
             case 21:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 99;
                 Main.snowBG[0] = 95;
                 Main.snowBG[1] = 96;
                 Main.snowBG[2] = 97;
                 break;
             case 22:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 99;
                 Main.snowBG[0] = 37;
                 Main.snowBG[1] = 38;
                 Main.snowBG[2] = 39;
                 break;
             case 3:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 100;
                 Main.snowBG[0] = -1;
                 Main.snowBG[1] = -1;
                 Main.snowBG[2] = -1;
                 break;
             case 31:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 100;
                 Main.snowBG[0] = 95;
                 Main.snowBG[1] = 96;
                 Main.snowBG[2] = 97;
                 break;
             case 32:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 100;
                 Main.snowBG[0] = 37;
                 Main.snowBG[1] = 38;
                 Main.snowBG[2] = 39;
                 break;
             case 4:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 101;
                 Main.snowBG[0] = -1;
                 Main.snowBG[1] = -1;
                 Main.snowBG[2] = -1;
                 break;
             case 41:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 101;
                 Main.snowBG[0] = 95;
                 Main.snowBG[1] = 96;
                 Main.snowBG[2] = 97;
                 break;
             case 42:
                 Main.snowMntBG[0] = 98;
                 Main.snowMntBG[1] = 101;
                 Main.snowBG[0] = 37;
                 Main.snowBG[1] = 38;
                 Main.snowBG[2] = 39;
                 break;
             case 5:
                 Main.snowMntBG[0] = -1;
                 Main.snowMntBG[1] = -1;
                 Main.snowBG[0] = 258;
                 Main.snowBG[1] = 259;
                 Main.snowBG[2] = 260;
                 break;
             case 6:
                 Main.snowMntBG[0] = -1;
                 Main.snowMntBG[1] = -1;
                 Main.snowBG[0] = 263;
                 Main.snowBG[1] = 264;
                 Main.snowBG[2] = 265;
                 break;
             case 7:
                 Main.snowMntBG[0] = 269;
                 Main.snowMntBG[1] = 270;
                 Main.snowBG[0] = 267;
                 Main.snowBG[1] = 266;
                 Main.snowBG[2] = 268;
                 break;
             }
             break;
         case 4:
             hallowBG = style;
             switch (style)
             {
             default:
                 Main.hallowBG[0] = 29;
                 Main.hallowBG[1] = 30;
                 Main.hallowBG[2] = 31;
                 break;
             case 1:
                 Main.hallowBG[0] = 102;
                 Main.hallowBG[1] = 103;
                 Main.hallowBG[2] = 104;
                 break;
             case 2:
                 Main.hallowBG[0] = 219;
                 Main.hallowBG[1] = 220;
                 Main.hallowBG[2] = 221;
                 break;
             case 3:
                 Main.hallowBG[0] = 243;
                 Main.hallowBG[1] = 244;
                 Main.hallowBG[2] = 245;
                 break;
             case 4:
                 Main.hallowBG[0] = -1;
                 Main.hallowBG[1] = 261;
                 Main.hallowBG[2] = 262;
                 break;
             }
             break;
         case 5:
             crimsonBG = style;
             switch (style)
             {
             default:
                 Main.crimsonBG[0] = 43;
                 Main.crimsonBG[1] = 44;
                 Main.crimsonBG[2] = 45;
                 break;
             case 1:
                 Main.crimsonBG[0] = 105;
                 Main.crimsonBG[1] = 106;
                 Main.crimsonBG[2] = 107;
                 break;
             case 2:
                 Main.crimsonBG[0] = 174;
                 Main.crimsonBG[1] = -1;
                 Main.crimsonBG[2] = 175;
                 break;
             case 3:
                 Main.crimsonBG[0] = 214;
                 Main.crimsonBG[1] = 215;
                 Main.crimsonBG[2] = 216;
                 break;
             case 4:
                 Main.crimsonBG[0] = -1;
                 Main.crimsonBG[1] = 229;
                 Main.crimsonBG[2] = 230;
                 break;
             case 5:
                 Main.crimsonBG[0] = 255;
                 Main.crimsonBG[1] = 256;
                 Main.crimsonBG[2] = 257;
                 break;
             }
             break;
         case 6:
             desertBG = style;
             switch (style)
             {
             default:
                 Main.desertBG[0] = 21;
                 Main.desertBG[1] = 20;
                 Main.desertBG[2] = -1;
                 break;
             case 1:
                 Main.desertBG[0] = 108;
                 Main.desertBG[1] = 109;
                 Main.desertBG[2] = -1;
                 break;
             case 2:
                 Main.desertBG[0] = 207;
                 Main.desertBG[1] = 208;
                 Main.desertBG[2] = -1;
                 break;
             case 3:
                 Main.desertBG[0] = 217;
                 Main.desertBG[1] = 218;
                 Main.desertBG[2] = -1;
                 break;
             case 4:
                 Main.desertBG[0] = 248;
                 Main.desertBG[1] = 249;
                 Main.desertBG[2] = 250;
                 break;
             }
             break;
         case 7:
             oceanBG = style;
             switch (style)
             {
             default:
                 Main.oceanBG = 28;
                 break;
             case 1:
                 Main.oceanBG = 110;
                 break;
             case 2:
                 Main.oceanBG = 111;
                 break;
             case 3:
                 Main.oceanBG = 209;
                 break;
             case 4:
                 Main.oceanBG = 210;
                 break;
             case 5:
                 Main.oceanBG = 283;
                 break;
             }
             break;
         case 8:
             mushroomBG = style;
             switch (style)
             {
             default:
                 Main.mushroomBG[0] = 46;
                 Main.mushroomBG[1] = 47;
                 Main.mushroomBG[2] = 48;
                 break;
             case 1:
                 Main.mushroomBG[0] = 231;
                 Main.mushroomBG[1] = 232;
                 Main.mushroomBG[2] = 233;
                 break;
             case 2:
                 Main.mushroomBG[0] = 234;
                 Main.mushroomBG[1] = 235;
                 Main.mushroomBG[2] = 236;
                 break;
             case 3:
                 Main.mushroomBG[0] = 287;
                 Main.mushroomBG[1] = 288;
                 Main.mushroomBG[2] = 289;
                 break;
             }
             break;
         case 9:
             underworldBG = style;
             switch (style)
             {
             default:
                 Main.underworldBG[0] = 0;
                 Main.underworldBG[1] = 1;
                 Main.underworldBG[2] = 2;
                 Main.underworldBG[3] = 3;
                 Main.underworldBG[4] = 4;
                 break;
             case 1:
                 Main.underworldBG[0] = 5;
                 Main.underworldBG[1] = 6;
                 Main.underworldBG[2] = 7;
                 Main.underworldBG[3] = 8;
                 Main.underworldBG[4] = 9;
                 break;
             case 2:
                 Main.underworldBG[0] = 10;
                 Main.underworldBG[1] = 11;
                 Main.underworldBG[2] = 12;
                 Main.underworldBG[3] = 13;
                 Main.underworldBG[4] = 9;
                 break;
             }
             break;
         }
     }
References Main.corruptBG, corruptBG, Main.crimsonBG, crimsonBG, Main.desertBG, desertBG, Main.hallowBG, hallowBG, Main.jungleBG, jungleBG, Main.mushroomBG, mushroomBG, Main.oceanBG, oceanBG, SetForestBGSet(), Main.snowBG, snowBG, Main.snowMntBG, treeBG1, treeBG2, treeBG3, treeBG4, Main.treeBGSet1, Main.treeBGSet2, Main.treeBGSet3, Main.treeBGSet4, Main.treeMntBGSet1, Main.treeMntBGSet2, Main.treeMntBGSet3, Main.treeMntBGSet4, Main.underworldBG, and underworldBG.
Referenced by MessageBuffer.GetData(), WorldFile.LoadHeader(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), RandomizeBackgroundBasedOnPlayer(), RandomizeBackgrounds(), and Main.UpdateMenu().