Terraria: WorldGen.KillTile_GetTileDustAmount
KillTile_GetTileDustAmount()
static int WorldGen.KillTile_GetTileDustAmount (bool fail, Tile tileCache) inline static
     {
         switch (tileCache.type)
         {
         default:
             if (!fail)
             {
                 return 10;
             }
             return 3;
         case 654:
             return 0;
         case 630:
         case 631:
             return 0;
         case 231:
             if (!fail)
             {
                 return 6;
             }
             return 3;
         case 481:
         case 482:
         case 483:
             return 3;
         case 541:
             return 1;
         case 549:
             return 2;
         case 125:
         case 138:
         case 172:
         case 287:
         case 300:
         case 301:
         case 302:
         case 303:
         case 304:
         case 305:
         case 306:
         case 307:
         case 308:
         case 354:
         case 355:
         case 373:
         case 374:
         case 375:
         case 376:
         case 461:
         case 484:
         case 499:
         case 564:
         case 565:
         case 593:
         case 594:
         case 617:
         case 664:
         case 665:
             return 0;
         case 534:
         case 536:
         case 539:
         case 625:
         case 627:
             if (!fail)
             {
                 return 5;
             }
             return 3;
         case 184:
             if (tileCache.frameX / 22 >= 5)
             {
                 return 5;
             }
             if (!fail)
             {
                 return 10;
             }
             return 3;
         }
     }
References Tile.frameX, and Tile.type.
Referenced by NPC.AI_110_Betsy(), Projectile.AI_135_OgreStomp(), Projectile.CreateGroundExplosion(), Projectile.CreateImpactExplosion(), Mount.EmitGolfCartWheelDust(), Player.MowGrassTile(), and Player.PlaceThing_TryReplacingTiles().