Terraria: System.Text.RegularExpressions.RegexRunner.MatchLength
MatchLength()
int System.Text.RegularExpressions.RegexRunner.MatchLength (int cap) inline protected
Definition at line 429 of file RegexRunner.cs.
    {
        return runmatch.MatchLength(cap);
    }
References System.Text.RegularExpressions.Match.MatchLength(), and System.Text.RegularExpressions.RegexRunner.runmatch.
Referenced by System.Text.RegularExpressions.RegexInterpreter.Go(), and System.Text.RegularExpressions.RegexRunner.TransferCapture().