Terraria: System.Data.Common.DbConnectionStringBuilder.GetProperties
GetProperties() [6/6]
virtual void System.Data.Common.DbConnectionStringBuilder.GetProperties (Hashtable propertyDescriptors) inline protected virtual
Definition at line 387 of file DbConnectionStringBuilder.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DbConnectionStringBuilder.GetProperties|API> {0}", ObjectID);
        try
        {
            Type type = GetType();
            Attribute[] attributesFromCollection;
            foreach (PropertyDescriptor property in TypeDescriptor.GetProperties(this, noCustomTypeDesc: true))
            {
                if ("ConnectionString" != property.Name)
                {
                    string displayName = property.DisplayName;
                    if (!propertyDescriptors.ContainsKey(displayName))
                    {
                        attributesFromCollection = GetAttributesFromCollection(property.Attributes);
                        PropertyDescriptor value = new DbConnectionStringBuilderDescriptor(property.Name, property.ComponentType, property.PropertyType, property.IsReadOnly, attributesFromCollection);
                        propertyDescriptors[displayName] = value;
                    }
                }
                else if (BrowsableConnectionString)
                {
                    propertyDescriptors["ConnectionString"] = property;
                }
                else
                {
                    propertyDescriptors.Remove("ConnectionString");
                }
            }
            if (IsFixedSize)
            {
                return;
            }
            attributesFromCollection = null;
            foreach (string key in Keys)
            {
                if (propertyDescriptors.ContainsKey(key))
                {
                    continue;
                }
                object obj = this[key];
                Type type2;
                if (obj != null)
                {
                    type2 = obj.GetType();
                    if (typeof(string) == type2)
                    {
                        bool result2;
                        if (int.TryParse((string)obj, out var _))
{
                            type2 = typeof(int);
                        }
                        else if (bool.TryParse((string)obj, out result2))
{
                            type2 = typeof(bool);
                        }
                    }
                }
                else
                {
                    type2 = typeof(string);
                }
                Attribute[] attributes = null;
                if (StringComparer.OrdinalIgnoreCase.Equals("Password", key) || StringComparer.OrdinalIgnoreCase.Equals("pwd", key))
                {
                    attributes = new Attribute[3]
                    {
                        BrowsableAttribute.Yes,
                        PasswordPropertyTextAttribute.Yes,
                        RefreshPropertiesAttribute.All
                    };
                }
                else if (attributesFromCollection == null)
                {
                    attributesFromCollection = new Attribute[2]
                    {
                        BrowsableAttribute.Yes,
                        RefreshPropertiesAttribute.All
                    };
                    attributes = attributesFromCollection;
                }
                PropertyDescriptor value2 = new DbConnectionStringBuilderDescriptor(key, GetType(), type2, isReadOnly: false, attributes);
                propertyDescriptors[key] = value2;
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.Common.DbConnectionStringBuilder.BrowsableConnectionString, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Data.Common.DbConnectionStringBuilder.Dictionary, System.Data.Common.DbConnectionStringBuilder.GetAttributesFromCollection(), System.ComponentModel.TypeDescriptor.GetProperties(), System.Data.Common.DbConnectionStringBuilder.IsFixedSize, System.Collections.Generic.Dictionary< TKey, TValue >.IsReadOnly, System.key, System.Data.Common.DbConnectionStringBuilder.Keys, System.Data.DataCommonEventSource.Log, System.obj, System.Data.Common.DbConnectionStringBuilder.ObjectID, System.StringComparer.OrdinalIgnoreCase, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.type, System.value, System.ComponentModel.BrowsableAttribute.Yes, and System.ComponentModel.PasswordPropertyTextAttribute.Yes.