Terraria: System.Text.RegularExpressions.RegexRunner.InitializeForGo
InitializeForGo()
void System.Text.RegularExpressions.RegexRunner.InitializeForGo () inline private
Definition at line 249 of file RegexRunner.cs.
    {
        if (runmatch == null)
        {
            runmatch = ((runregex.caps == null) ? new Match(runregex, runregex.capsize, runtext, runtextbeg, runtextend - runtextbeg, runtextstart) : new MatchSparse(runregex, runregex.caps, runregex.capsize, runtext, runtextbeg, runtextend - runtextbeg, runtextstart));
        }
        else
        {
            runmatch.Reset(runregex, runtext, runtextbeg, runtextend, runtextstart);
        }
        if (runcrawl != null)
        {
            runtrackpos = runtrack.Length;
            runstackpos = runstack.Length;
            runcrawlpos = runcrawl.Length;
            return;
        }
        InitTrackCount();
        int num;
        int num2 = (num = runtrackcount * 8);
        if (num2 < 32)
        {
            num2 = 32;
        }
        if (num < 16)
        {
            num = 16;
        }
        runtrack = new int[num2];
        runtrackpos = num2;
        runstack = new int[num];
        runstackpos = num;
        runcrawl = new int[32];
        runcrawlpos = 32;
    }
References System.Text.RegularExpressions.Regex.caps, System.Text.RegularExpressions.Regex.capsize, System.Text.RegularExpressions.RegexRunner.InitTrackCount(), System.Text.RegularExpressions.Match.Reset(), System.Text.RegularExpressions.RegexRunner.runcrawl, System.Text.RegularExpressions.RegexRunner.runcrawlpos, System.Text.RegularExpressions.RegexRunner.runmatch, System.Text.RegularExpressions.RegexRunner.runregex, System.Text.RegularExpressions.RegexRunner.runstack, System.Text.RegularExpressions.RegexRunner.runstackpos, System.Text.RegularExpressions.RegexRunner.runtext, System.Text.RegularExpressions.RegexRunner.runtextbeg, System.Text.RegularExpressions.RegexRunner.runtextend, System.Text.RegularExpressions.RegexRunner.runtextstart, System.Text.RegularExpressions.RegexRunner.runtrack, System.Text.RegularExpressions.RegexRunner.runtrackcount, and System.Text.RegularExpressions.RegexRunner.runtrackpos.
Referenced by System.Text.RegularExpressions.RegexRunner.Scan(), and System.Text.RegularExpressions.RegexRunner.Scan< TState >().