Terraria: System.Text.RegularExpressions.RegexRunner.Scan
Scan() [2/2]
Match? System.Text.RegularExpressions.RegexRunner.Scan (Regex regex, string text, int textbeg, int textend, int textstart, int prevlen, bool quick, TimeSpan timeout) inline package
Definition at line 52 of file RegexRunner.cs.
    {
        _timeout = -1;
        bool flag = (_ignoreTimeout = Regex.InfiniteMatchTimeout == timeout);
        if (!flag)
        {
            Regex.ValidateMatchTimeout(timeout);
            _timeout = (int)(timeout.TotalMilliseconds + 0.5);
            _timeoutOccursAt = Environment.TickCount + _timeout;
            _timeoutChecksToSkip = 1000;
        }
        int num = 1;
        int num2 = textend;
        if (regex.RightToLeft)
        {
            num = -1;
            num2 = textbeg;
        }
        runtextpos = textstart;
        if (prevlen == 0)
        {
            if (textstart == num2)
            {
                return Match.Empty;
            }
            runtextpos += num;
        }
        runregex = regex;
        runtext = text;
        runtextstart = textstart;
        runtextbeg = textbeg;
        runtextend = textend;
        bool flag2 = false;
        while (true)
        {
            if (FindFirstChar())
            {
                if (!flag)
                {
                    DoCheckTimeout();
                }
                if (!flag2)
                {
                    InitializeForGo();
                    flag2 = true;
                }
                Go();
                Match match = runmatch;
                if (match._matchcount[0] > 0)
                {
                    runtext = null;
                    if (quick)
                    {
                        runmatch.Text = null;
                        return null;
                    }
                    runmatch = null;
                    match.Tidy(runtextpos);
                    return match;
                }
                runtrackpos = runtrack.Length;
                runstackpos = runstack.Length;
                runcrawlpos = runcrawl.Length;
            }
            if (runtextpos == num2)
            {
                break;
            }
            runtextpos += num;
        }
        runtext = null;
        if (runmatch != null)
        {
            runmatch.Text = null;
        }
        return Match.Empty;
    }
References System.Text.RegularExpressions.RegexRunner._ignoreTimeout, System.Text.RegularExpressions.RegexRunner._timeout, System.Text.RegularExpressions.RegexRunner._timeoutChecksToSkip, System.Text.RegularExpressions.RegexRunner._timeoutOccursAt, System.Text.RegularExpressions.RegexRunner.DoCheckTimeout(), System.Text.RegularExpressions.Match.Empty, System.Text.RegularExpressions.RegexRunner.FindFirstChar(), System.Text.RegularExpressions.RegexRunner.Go(), System.Text.RegularExpressions.RegexRunner.InitializeForGo(), System.match, System.Text.RegularExpressions.Regex.RightToLeft, System.Text.RegularExpressions.RegexRunner.runcrawl, System.Text.RegularExpressions.RegexRunner.runcrawlpos, System.Text.RegularExpressions.RegexRunner.runmatch, System.Text.RegularExpressions.RegexRunner.runregex, System.Text.RegularExpressions.RegexRunner.runstack, System.Text.RegularExpressions.RegexRunner.runstackpos, System.Text.RegularExpressions.RegexRunner.runtext, System.Text.RegularExpressions.RegexRunner.runtextbeg, System.Text.RegularExpressions.RegexRunner.runtextend, System.Text.RegularExpressions.RegexRunner.runtextpos, System.Text.RegularExpressions.RegexRunner.runtextstart, System.Text.RegularExpressions.RegexRunner.runtrack, System.Text.RegularExpressions.RegexRunner.runtrackpos, System.text, System.Text.RegularExpressions.Match.Tidy(), System.timeout, and System.Text.RegularExpressions.Regex.ValidateMatchTimeout().