Terraria: System.Text.RegularExpressions.RegexRunner.MatchIndex
MatchIndex()
int System.Text.RegularExpressions.RegexRunner.MatchIndex (int cap) inline protected
Definition at line 424 of file RegexRunner.cs.
    {
        return runmatch.MatchIndex(cap);
    }
References System.Text.RegularExpressions.Match.MatchIndex(), and System.Text.RegularExpressions.RegexRunner.runmatch.
Referenced by System.Text.RegularExpressions.RegexInterpreter.Go(), and System.Text.RegularExpressions.RegexRunner.TransferCapture().