Terraria: System.Data.Common.DbConnectionStringBuilder.GetProperties
GetProperties() [1/6]
PropertyDescriptorCollection System.Data.Common.DbConnectionStringBuilder.GetProperties () inline private
Implements System.ComponentModel.ICustomTypeDescriptor.
Definition at line 363 of file DbConnectionStringBuilder.cs.
    {
        PropertyDescriptorCollection propertyDescriptorCollection = _propertyDescriptors;
        if (propertyDescriptorCollection == null)
        {
            long scopeId = DataCommonEventSource.Log.EnterScope("<comm.DbConnectionStringBuilder.GetProperties|INFO> {0}", ObjectID);
            try
            {
                Hashtable hashtable = new Hashtable(StringComparer.OrdinalIgnoreCase);
                GetProperties(hashtable);
                PropertyDescriptor[] array = new PropertyDescriptor[hashtable.Count];
                hashtable.Values.CopyTo(array, 0);
                propertyDescriptorCollection = (_propertyDescriptors = new PropertyDescriptorCollection(array));
            }
            finally
            {
                DataCommonEventSource.Log.ExitScope(scopeId);
            }
        }
        return propertyDescriptorCollection;
    }
References System.Data.Common.DbConnectionStringBuilder._propertyDescriptors, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Hashtable.Count, System.Data.Common.DbConnectionStringBuilder.Dictionary, System.Data.Common.DbConnectionStringBuilder.GetProperties(), System.Data.DataCommonEventSource.Log, System.Data.Common.DbConnectionStringBuilder.ObjectID, System.StringComparer.OrdinalIgnoreCase, and System.Collections.Hashtable.Values.
Referenced by System.Data.Common.DbConnectionStringBuilder.GetProperties(), and System.Data.Common.DbConnectionStringBuilder.GetProperties().