Terraria: System.Reflection.PseudoCustomAttribute.GetCustomAttributes
GetCustomAttributes() [1/4]
static void System.Reflection.PseudoCustomAttribute.GetCustomAttributes (RuntimeFieldInfo field, RuntimeType caType, ref RuntimeType::ListBuilder< Attribute > pcas) inline static package
Definition at line 165 of file PseudoCustomAttribute.cs.
    {
        bool flag = caType == typeof(object) || caType == typeof(Attribute);
        if (!flag && !s_pca.Contains(caType))
        {
            return;
        }
        if (flag || caType == typeof(MarshalAsAttribute))
        {
            Attribute marshalAsCustomAttribute = GetMarshalAsCustomAttribute(field);
            if (marshalAsCustomAttribute != null)
            {
                pcas.Add(marshalAsCustomAttribute);
            }
        }
        if (flag || caType == typeof(FieldOffsetAttribute))
        {
            Attribute marshalAsCustomAttribute = GetFieldOffsetCustomAttribute(field);
            if (marshalAsCustomAttribute != null)
            {
                pcas.Add(marshalAsCustomAttribute);
            }
        }
        if ((flag || caType == typeof(NonSerializedAttribute)) && (field.Attributes & FieldAttributes.NotSerialized) != 0)
        {
            pcas.Add(new NonSerializedAttribute());
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.PseudoCustomAttribute.GetFieldOffsetCustomAttribute(), System.Reflection.PseudoCustomAttribute.GetMarshalAsCustomAttribute(), and System.Reflection.PseudoCustomAttribute.s_pca.