Terraria: System.Reflection.PseudoCustomAttribute.GetCustomAttributes
GetCustomAttributes() [4/4]
static void System.Reflection.PseudoCustomAttribute.GetCustomAttributes (RuntimeType type, RuntimeType caType, ref RuntimeType::ListBuilder< Attribute > pcas) inline static package
Definition at line 37 of file PseudoCustomAttribute.cs.
    {
        bool flag = caType == typeof(object) || caType == typeof(Attribute);
        if (flag || s_pca.Contains(caType))
        {
            if ((flag || caType == typeof(SerializableAttribute)) && (type.Attributes & TypeAttributes.Serializable) != 0)
            {
                pcas.Add(new SerializableAttribute());
            }
            if ((flag || caType == typeof(ComImportAttribute)) && (type.Attributes & TypeAttributes.Import) != 0)
            {
                pcas.Add(new ComImportAttribute());
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.PseudoCustomAttribute.s_pca, and System.type.
Referenced by System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.CustomAttribute.GetCustomAttributes(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), and System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal().