Terraria: System.Reflection.PseudoCustomAttribute.GetMarshalAsCustomAttribute
GetMarshalAsCustomAttribute() [1/3]
static MarshalAsAttribute System.Reflection.PseudoCustomAttribute.GetMarshalAsCustomAttribute (int token, RuntimeModule scope) inline static private
Definition at line 282 of file PseudoCustomAttribute.cs.
    {
        ConstArray fieldMarshal = ModuleHandle.GetMetadataImport(scope).GetFieldMarshal(token);
        if (fieldMarshal.Length == 0)
        {
            return null;
        }
        MetadataImport.GetMarshalAs(fieldMarshal, out var unmanagedType, out var safeArraySubType, out var safeArrayUserDefinedSubType, out var arraySubType, out var sizeParamIndex, out var sizeConst, out var marshalType, out var marshalCookie, out var iidParamIndex);
        RuntimeType safeArrayUserDefinedSubType2 = (string.IsNullOrEmpty(safeArrayUserDefinedSubType) ? null : RuntimeTypeHandle.GetTypeByNameUsingCARules(safeArrayUserDefinedSubType, scope));
        RuntimeType marshalTypeRef = null;
        try
        {
            marshalTypeRef = ((marshalType == null) ? null : RuntimeTypeHandle.GetTypeByNameUsingCARules(marshalType, scope));
        }
        catch (TypeLoadException)
        {
        }
        MarshalAsAttribute marshalAsAttribute = new MarshalAsAttribute(unmanagedType);
        marshalAsAttribute.SafeArraySubType = safeArraySubType;
        marshalAsAttribute.SafeArrayUserDefinedSubType = safeArrayUserDefinedSubType2;
        marshalAsAttribute.IidParameterIndex = iidParamIndex;
        marshalAsAttribute.ArraySubType = arraySubType;
        marshalAsAttribute.SizeParamIndex = (short)sizeParamIndex;
        marshalAsAttribute.SizeConst = sizeConst;
        marshalAsAttribute.MarshalType = marshalType;
        marshalAsAttribute.MarshalTypeRef = marshalTypeRef;
        marshalAsAttribute.MarshalCookie = marshalCookie;
        return marshalAsAttribute;
    }
References System.Reflection.MetadataImport.GetMarshalAs(), System.ModuleHandle.GetMetadataImport(), and System.RuntimeTypeHandle.GetTypeByNameUsingCARules().