Terraria: System.Security.AccessControl.FileSystemAccessRule.AccessMaskFromRights
AccessMaskFromRights()
static int System.Security.AccessControl.FileSystemAccessRule.AccessMaskFromRights (FileSystemRights fileSystemRights, AccessControlType controlType) inline static package
Definition at line 34 of file FileSystemAccessRule.cs.
    {
        if (fileSystemRights < (FileSystemRights)0 || fileSystemRights > FileSystemRights.FullControl)
        {
            throw new ArgumentOutOfRangeException("fileSystemRights", System.SR.Format(System.SR.Argument_InvalidEnumValue, fileSystemRights, "FileSystemRights"));
        }
        switch (controlType)
        {
        case AccessControlType.Allow:
            fileSystemRights |= FileSystemRights.Synchronize;
            break;
        case AccessControlType.Deny:
            if (fileSystemRights != FileSystemRights.FullControl && fileSystemRights != (FileSystemRights.Modify | FileSystemRights.ChangePermissions | FileSystemRights.TakeOwnership | FileSystemRights.Synchronize))
            {
                fileSystemRights &= ~FileSystemRights.Synchronize;
            }
            break;
        }
        return (int)fileSystemRights;
    }
References System.SR.Argument_InvalidEnumValue, and System.SR.Format().
Referenced by System.Security.AccessControl.FileSystemSecurity.RemoveAccessRule(), and System.Security.AccessControl.FileSystemSecurity.RemoveAccessRuleSpecific().