Terraria: System.Net.Sockets.SocketPal.WindowsIoctl
WindowsIoctl()
static SocketError System.Net.Sockets.SocketPal.WindowsIoctl (SafeSocketHandle handle, int ioControlCode, byte[] optionInValue, byte[] optionOutValue, out int optionLength) inline static
Definition at line 468 of file SocketPal.cs.
    {
        if (ioControlCode == -2147195266)
        {
            throw new InvalidOperationException(System.SR.net_sockets_useblocking);
        }
        SocketError socketError = global::Interop.Winsock.WSAIoctl_Blocking(handle, ioControlCode, optionInValue, (optionInValue != null) ? optionInValue.Length : 0, optionOutValue, (optionOutValue != null) ? optionOutValue.Length : 0, out optionLength, IntPtr.Zero, IntPtr.Zero);
        if (socketError != SocketError.SocketError)
        {
            return SocketError.Success;
        }
        return GetLastSocketError();
    }
References System.Net.Sockets.SocketPal.GetLastSocketError(), System.handle, System.SR.net_sockets_useblocking, and System.IntPtr.Zero.
Referenced by System.Net.Sockets.Socket.IOControl(), and System.Net.Sockets.IOControlKeepAlive.Set().