Terraria: System.Net.Sockets.SocketPal.TransmitFileHelper
TransmitFileHelper()
static unsafe bool System.Net.Sockets.SocketPal.TransmitFileHelper (SafeHandle socket, SafeHandle fileHandle, NativeOverlapped * overlapped, IntPtr pinnedPreBuffer, int preBufferLength, IntPtr pinnedPostBuffer, int postBufferLength, TransmitFileOptions flags) inline static private
Definition at line 809 of file SocketPal.cs.
    {
        bool flag = false;
        global::Interop.Mswsock.TransmitFileBuffers transmitFileBuffers = default(global::Interop.Mswsock.TransmitFileBuffers);
        if (preBufferLength > 0)
        {
            flag = true;
            transmitFileBuffers.Head = pinnedPreBuffer;
            transmitFileBuffers.HeadLength = preBufferLength;
        }
        if (postBufferLength > 0)
        {
            flag = true;
            transmitFileBuffers.Tail = pinnedPostBuffer;
            transmitFileBuffers.TailLength = postBufferLength;
        }
        bool success = false;
        IntPtr fileHandle2 = IntPtr.Zero;
        try
        {
            if (fileHandle != null)
            {
                fileHandle.DangerousAddRef(ref success);
                fileHandle2 = fileHandle.DangerousGetHandle();
            }
            return global::Interop.Mswsock.TransmitFile(socket, fileHandle2, 0, 0, overlapped, flag ? (&transmitFileBuffers) : null, flags);
        }
        finally
        {
            if (success)
            {
                fileHandle.DangerousRelease();
            }
        }
    }
References System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), and System.IntPtr.Zero.
Referenced by System.Net.Sockets.SocketPal.SendFile().