Terraria: System.Net.Sockets.SocketPal.Accept
Accept()
static SocketError System.Net.Sockets.SocketPal.Accept (SafeSocketHandle listenSocket, byte[] socketAddress, ref int socketAddressSize, out SafeSocketHandle socket) inline static
Definition at line 159 of file SocketPal.cs.
    {
        IntPtr preexistingHandle = global::Interop.Winsock.accept(listenSocket, socketAddress, ref socketAddressSize);
        socket = new SafeSocketHandle(preexistingHandle, ownsHandle: true);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(null, socket, "Accept");
        }
        if (!socket.IsInvalid)
        {
            return SocketError.Success;
        }
        return GetLastSocketError();
    }
References System.Net.Sockets.SocketPal.GetLastSocketError(), System.Net.NetEventSource.Info(), and System.Net.NetEventSource.Log.
Referenced by System.Net.Sockets.Socket.Accept().