Terraria: System.Net.Sockets.SocketPal.ReceiveMessageFrom
ReceiveMessageFrom() [2/2]
static unsafe SocketError System.Net.Sockets.SocketPal.ReceiveMessageFrom (Socket socket, SafeSocketHandle handle, Span< byte > buffer, ref SocketFlags socketFlags, System::Net::Internals::SocketAddress socketAddress, out System::Net::Internals::SocketAddress receiveAddress, out IPPacketInformation ipPacketInformation, out int bytesTransferred) inline static
Definition at line 391 of file SocketPal.cs.
    {
        Socket.GetIPProtocolInformation(socket.AddressFamily, socketAddress, out var isIPv, out var isIPv2);
        bytesTransferred = 0;
        receiveAddress = socketAddress;
        ipPacketInformation = default(IPPacketInformation);
        fixed (byte* ptr2 = &MemoryMarshal.GetReference(buffer))
        {
            fixed (byte* ptr = socketAddress.Buffer)
            {
                Unsafe.SkipInit(out global::Interop.Winsock.WSAMsg wSAMsg);
                wSAMsg.socketAddress = (IntPtr)ptr;
                wSAMsg.addressLength = (uint)socketAddress.Size;
                wSAMsg.flags = socketFlags;
                Unsafe.SkipInit(out WSABuffer wSABuffer);
                wSABuffer.Length = buffer.Length;
                wSABuffer.Pointer = (IntPtr)ptr2;
                wSAMsg.buffers = (IntPtr)(&wSABuffer);
                wSAMsg.count = 1u;
                if (isIPv)
                {
                    Unsafe.SkipInit(out global::Interop.Winsock.ControlData controlData);
                    wSAMsg.controlBuffer.Pointer = (IntPtr)(&controlData);
                    wSAMsg.controlBuffer.Length = sizeof(global::Interop.Winsock.ControlData);
                    if (socket.WSARecvMsgBlocking(handle, (IntPtr)(&wSAMsg), out bytesTransferred) == SocketError.SocketError)
                    {
                        return GetLastSocketError();
                    }
                    ipPacketInformation = GetIPPacketInformation(&controlData);
                }
                else if (isIPv2)
                {
                    Unsafe.SkipInit(out global::Interop.Winsock.ControlDataIPv6 controlDataIPv);
                    wSAMsg.controlBuffer.Pointer = (IntPtr)(&controlDataIPv);
                    wSAMsg.controlBuffer.Length = sizeof(global::Interop.Winsock.ControlDataIPv6);
                    if (socket.WSARecvMsgBlocking(handle, (IntPtr)(&wSAMsg), out bytesTransferred) == SocketError.SocketError)
                    {
                        return GetLastSocketError();
                    }
                    ipPacketInformation = GetIPPacketInformation(&controlDataIPv);
                }
                else
                {
                    wSAMsg.controlBuffer.Pointer = IntPtr.Zero;
                    wSAMsg.controlBuffer.Length = 0;
                    if (socket.WSARecvMsgBlocking(handle, (IntPtr)(&wSAMsg), out bytesTransferred) == SocketError.SocketError)
                    {
                        return GetLastSocketError();
                    }
                }
                socketFlags = wSAMsg.flags;
            }
        }
        return SocketError.Success;
    }
References System.buffer, System.Net.Sockets.SocketPal.GetIPPacketInformation(), System.Net.Sockets.Socket.GetIPProtocolInformation(), System.Net.Sockets.SocketPal.GetLastSocketError(), System.handle, and System.IntPtr.Zero.