Terraria: System.Net.Sockets.SocketPal.Poll
Poll()
static unsafe SocketError System.Net.Sockets.SocketPal.Poll (SafeSocketHandle handle, int microseconds, SelectMode mode, out bool status) inline static
Definition at line 671 of file SocketPal.cs.
    {
        bool success = false;
        try
        {
            handle.DangerousAddRef(ref success);
            IntPtr intPtr = handle.DangerousGetHandle();
            IntPtr* ptr = stackalloc IntPtr[2]
            {
                (IntPtr)1,
                intPtr
            };
            global::Interop.Winsock.TimeValue socketTime = default(global::Interop.Winsock.TimeValue);
            int num;
            if (microseconds != -1)
            {
                MicrosecondsToTimeValue((uint)microseconds, ref socketTime);
                num = global::Interop.Winsock.select(0, (mode == SelectMode.SelectRead) ? ptr : null, (mode == SelectMode.SelectWrite) ? ptr : null, (mode == SelectMode.SelectError) ? ptr : null, ref socketTime);
            }
            else
            {
                num = global::Interop.Winsock.select(0, (mode == SelectMode.SelectRead) ? ptr : null, (mode == SelectMode.SelectWrite) ? ptr : null, (mode == SelectMode.SelectError) ? ptr : null, IntPtr.Zero);
            }
            if (num == -1)
            {
                status = false;
                return GetLastSocketError();
            }
            status = (int)(*ptr) != 0 && ptr[1] == intPtr;
            return SocketError.Success;
        }
        finally
        {
            if (success)
            {
                handle.DangerousRelease();
            }
        }
    }
References System.Net.Sockets.SocketPal.GetLastSocketError(), System.handle, System.Net.Sockets.SocketPal.MicrosecondsToTimeValue(), and System.IntPtr.Zero.
Referenced by System.Net.Sockets.Socket.Poll().