Terraria: System.Net.Sockets.SocketPal.GetLastSocketError
GetLastSocketError()
static SocketError System.Net.Sockets.SocketPal.GetLastSocketError () inline static
Definition at line 22 of file SocketPal.cs.
    {
        return (SocketError)Marshal.GetLastWin32Error();
    }
References System.Runtime.InteropServices.Marshal.GetLastWin32Error().
Referenced by System.Net.Sockets.SocketPal.Accept(), System.Net.Sockets.SocketPal.Bind(), System.Net.Sockets.SocketPal.Connect(), System.Net.Sockets.SocketPal.CreateSocket(), System.Net.Sockets.SocketPal.CreateSocket(), System.Net.Sockets.SocketPal.Disconnect(), System.Net.Sockets.SocketPal.DuplicateSocket(), System.Net.Sockets.Socket.EnableReuseUnicastPort(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationConnect(), System.Net.Sockets.SocketPal.GetAvailable(), System.Net.Sockets.SocketAsyncEventArgs.GetIOCPResult(), System.Net.Sockets.SocketPal.GetIPv6MulticastOption(), System.Net.Sockets.SocketPal.GetLingerOption(), System.Net.Sockets.SocketPal.GetMulticastOption(), System.Net.Sockets.SocketPal.GetPeerName(), System.Net.Sockets.SocketPal.GetRawSockOpt(), System.Net.Sockets.SocketPal.GetSockName(), System.Net.Sockets.SocketPal.GetSockOpt(), System.Net.Sockets.SocketPal.GetSockOpt(), System.Net.Sockets.SocketAsyncEventArgs.HandleCompletionPortCallbackError(), System.Net.Sockets.SocketPal.Listen(), System.Net.Sockets.Socket.LoadSocketTypeFromHandle(), System.Net.Sockets.SocketPal.Poll(), System.Net.Sockets.SocketPal.Receive(), System.Net.Sockets.SocketPal.Receive(), System.Net.Sockets.SocketPal.ReceiveFrom(), System.Net.Sockets.SocketPal.ReceiveMessageFrom(), System.Net.Sockets.SocketPal.Select(), System.Net.Sockets.SocketPal.Send(), System.Net.Sockets.SocketPal.Send(), System.Net.Sockets.SocketPal.SendFile(), System.Net.Sockets.SocketPal.SendTo(), System.Net.Sockets.SocketPal.SetBlocking(), System.Net.Sockets.SocketPal.SetIPv6MulticastOption(), System.Net.Sockets.SocketPal.SetLingerOption(), System.Net.Sockets.SocketPal.SetMulticastOption(), System.Net.Sockets.SocketPal.SetRawSockOpt(), System.Net.Sockets.SocketPal.SetSockOpt(), System.Net.Sockets.SocketPal.SetSockOpt(), System.Net.Sockets.SocketPal.Shutdown(), and System.Net.Sockets.SocketPal.WindowsIoctl().