Terraria: System.Net.Sockets.SocketPal.CreateSocket
CreateSocket() [1/2]
static SocketError System.Net.Sockets.SocketPal.CreateSocket (AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType, out SafeSocketHandle socket) inline static
Definition at line 27 of file SocketPal.cs.
    {
        global::Interop.Winsock.EnsureInitialized();
        IntPtr preexistingHandle = global::Interop.Winsock.WSASocketW(addressFamily, socketType, protocolType, IntPtr.Zero, 0u, global::Interop.Winsock.SocketConstructorFlags.WSA_FLAG_OVERLAPPED | global::Interop.Winsock.SocketConstructorFlags.WSA_FLAG_NO_HANDLE_INHERIT);
        socket = new SafeSocketHandle(preexistingHandle, ownsHandle: true);
        if (socket.IsInvalid)
        {
            SocketError lastSocketError = GetLastSocketError();
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, $"WSASocketW failed with error {lastSocketError}", "CreateSocket");
            }
            socket.Dispose();
            return lastSocketError;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(null, socket, "CreateSocket");
        }
        return SocketError.Success;
    }
References System.Net.NetEventSource.Error(), System.Net.Sockets.SocketPal.GetLastSocketError(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.IntPtr.Zero.
Referenced by System.Net.Sockets.Socket.Socket(), and System.Net.Sockets.Socket.Socket().