Terraria: System.Net.Sockets.SocketPal.Receive
Receive() [2/3]
static unsafe SocketError System.Net.Sockets.SocketPal.Receive (SafeSocketHandle handle, IList< ArraySegment< byte > > buffers, SocketFlags socketFlags, out int bytesTransferred) inline static
Definition at line 295 of file SocketPal.cs.
    {
        int count = buffers.Count;
        bool flag = count <= 16;
        WSABuffer[] array = null;
        GCHandle[] array2 = null;
        Span<WSABuffer> span = default(Span<WSABuffer>);
        Span<GCHandle> span2 = default(Span<GCHandle>);
        if (flag)
        {
            span = stackalloc WSABuffer[16];
            span2 = stackalloc GCHandle[16];
        }
        else
        {
            span = (array = ArrayPool<WSABuffer>.Shared.Rent(count));
            span2 = (array2 = ArrayPool<GCHandle>.Shared.Rent(count));
        }
        span2 = span2.Slice(0, count);
        span2.Clear();
        try
        {
            for (int i = 0; i < count; i++)
            {
                ArraySegment<byte> segment = buffers[i];
                RangeValidationHelpers.ValidateSegment(segment);
                span2[i] = GCHandle.Alloc(segment.Array, GCHandleType.Pinned);
                span[i].Length = segment.Count;
                span[i].Pointer = Marshal.UnsafeAddrOfPinnedArrayElement(segment.Array, segment.Offset);
            }
            SocketError socketError = global::Interop.Winsock.WSARecv(handle, span, count, out bytesTransferred, ref socketFlags, null, IntPtr.Zero);
            if (socketError == SocketError.SocketError)
            {
                socketError = GetLastSocketError();
            }
            return socketError;
        }
        finally
        {
            for (int j = 0; j < count; j++)
            {
                if (span2[j].IsAllocated)
                {
                    span2[j].Free();
                }
            }
            if (!flag)
            {
                ArrayPool<WSABuffer>.Shared.Return(array);
                ArrayPool<GCHandle>.Shared.Return(array2);
            }
        }
    }
References System.Runtime.InteropServices.GCHandle.Alloc(), System.array, System.buffers, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Sockets.SocketPal.GetLastSocketError(), System.handle, System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement(), System.Net.RangeValidationHelpers.ValidateSegment(), and System.IntPtr.Zero.
Referenced by System.Net.Sockets.Socket.Dispose(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), and System.Net.Sockets.Socket.Receive().