Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastingSourceCore.ConsumeMessage
ConsumeMessage()
TOutput System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ConsumeMessage (DataflowMessageHeader messageHeader, ITargetBlock< TOutput > target, out bool messageConsumed) inline package
Definition at line 480 of file BroadcastBlock.cs.
        {
            if (!messageHeader.IsValid)
            {
                throw new ArgumentException(System.SR.Argument_InvalidMessageHeader, "messageHeader");
            }
            if (target == null)
            {
                throw new ArgumentNullException("target");
            }
            TOutput currentMessage;
            lock (OutgoingLock)
            {
                lock (ValueLock)
                {
                    if (messageHeader.Id != _nextMessageId)
                    {
                        messageConsumed = false;
                        return default(TOutput);
                    }
                    if (_nextMessageReservedFor == target)
                    {
                        _nextMessageReservedFor = null;
                        _enableOffering = true;
                    }
                    _targetRegistry.Remove(target, onlyIfReachedMaxMessages: true);
                    OfferAsyncIfNecessary();
                    CompleteBlockIfPossible();
                    currentMessage = _currentMessage;
                }
            }
            messageConsumed = true;
            return CloneItem(currentMessage);
        }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._currentMessage, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._enableOffering, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._nextMessageId, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._nextMessageReservedFor, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._targetRegistry, System.SR.Argument_InvalidMessageHeader, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CloneItem(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferAsyncIfNecessary(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OutgoingLock, System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.Remove(), and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.BroadcastBlock< T >.ConsumeMessage().