Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastingSourceCore.CompleteBlockIfPossible
CompleteBlockIfPossible()
void System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CompleteBlockIfPossible () inline private
Definition at line 397 of file BroadcastBlock.cs.
        {
            if (!_completionReserved)
            {
                bool flag = _taskForOutputProcessing != null;
                bool flag2 = _decliningPermanently && _messages.Count == 0;
                if (!flag && (flag2 || CanceledOrFaulted))
                {
                    CompleteBlockIfPossible_Slow();
                }
            }
        }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._completionReserved, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._decliningPermanently, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._taskForOutputProcessing, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CanceledOrFaulted, and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CompleteBlockIfPossible_Slow().
Referenced by System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ConsumeMessage(), and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferMessagesLoopCore().