Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastingSourceCore.TryReceive
TryReceive()
bool System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.TryReceive (Predicate< TOutput > filter, [MaybeNullWhen(false)] out TOutput item) inline package
Definition at line 149 of file BroadcastBlock.cs.
        {
            TOutput currentMessage;
            bool currentMessageIsValid;
            lock (OutgoingLock)
            {
                lock (ValueLock)
                {
                    currentMessage = _currentMessage;
                    currentMessageIsValid = _currentMessageIsValid;
                }
            }
            if (currentMessageIsValid && (filter == null || filter(currentMessage)))
            {
                item = CloneItem(currentMessage);
                return true;
            }
            item = default(TOutput);
            return false;
        }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._currentMessage, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._currentMessageIsValid, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CloneItem(), System.item, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OutgoingLock, and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.BroadcastBlock< T >.TryReceive(), and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.TryReceiveAll().