Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastingSourceCore.CompleteBlockOncePossible
CompleteBlockOncePossible()
void System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CompleteBlockOncePossible () inline private
Definition at line 419 of file BroadcastBlock.cs.
        {
            TargetRegistry<TOutput>.LinkedTargetInfo firstTarget;
            List<Exception> exceptions;
            lock (OutgoingLock)
            {
                firstTarget = _targetRegistry.ClearEntryPoints();
                lock (ValueLock)
                {
                    _messages.Clear();
                    exceptions = _exceptions;
                    _exceptions = null;
                }
            }
            if (exceptions != null)
            {
                _completionTask.TrySetException(exceptions);
            }
            else if (_dataflowBlockOptions.CancellationToken.IsCancellationRequested)
            {
                _completionTask.TrySetCanceled();
            }
            else
            {
                _completionTask.TrySetResult(default(VoidResult));
            }
            _targetRegistry.PropagateCompletion(firstTarget);
            DataflowEtwProvider log = DataflowEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.DataflowBlockCompleted(_owningSource);
            }
        }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._completionTask, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._exceptions, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._owningSource, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._targetRegistry, System.Threading.Tasks.Dataflow.DataflowBlockOptions.CancellationToken, System.Collections.Generic.Queue< T >.Clear(), System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.ClearEntryPoints(), System.exceptions, System.Threading.CancellationToken.IsCancellationRequested, System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OutgoingLock, System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.PropagateCompletion(), and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ValueLock.