Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastingSourceCore.LinkTo
LinkTo()
IDisposable System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.LinkTo (ITargetBlock< TOutput > target, DataflowLinkOptions linkOptions) inline package
Definition at line 453 of file BroadcastBlock.cs.
        {
            if (target == null)
            {
                throw new ArgumentNullException("target");
            }
            if (linkOptions == null)
            {
                throw new ArgumentNullException("linkOptions");
            }
            lock (OutgoingLock)
            {
                if (_completionReserved)
                {
                    OfferCurrentMessageToNewTarget(target);
                    if (linkOptions.PropagateCompletion)
                    {
                        Common.PropagateCompletionOnceCompleted(_completionTask.Task, target);
                    }
                    return Disposables.Nop;
                }
                _targetRegistry.Add(ref target, linkOptions);
                OfferCurrentMessageToNewTarget(target);
                return Common.CreateUnlinker(OutgoingLock, _targetRegistry, target);
            }
        }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._completionReserved, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._completionTask, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._targetRegistry, System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.Add(), System.Threading.Tasks.Dataflow.Internal.Disposables.Nop, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferCurrentMessageToNewTarget(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OutgoingLock, and System.Threading.Tasks.Dataflow.Internal.Common.PropagateCompletionOnceCompleted().
Referenced by System.Threading.Tasks.Dataflow.BroadcastBlock< T >.LinkTo().