Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastingSourceCore.OfferMessagesLoopCore
OfferMessagesLoopCore()
void System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferMessagesLoopCore () inline private
Definition at line 359 of file BroadcastBlock.cs.
        {
            try
            {
                int actualMaxMessagesPerTask = _dataflowBlockOptions.ActualMaxMessagesPerTask;
                lock (OutgoingLock)
                {
                    for (int i = 0; i < actualMaxMessagesPerTask; i++)
                    {
                        if (CanceledOrFaulted)
{
                            break;
                        }
                        if (!OfferToTargets())
{
                            break;
                        }
                    }
                }
            }
            catch (Exception exception)
            {
                _owningSource.CompleteCore(exception, storeExceptionEvenIfAlreadyCompleting: true);
            }
            finally
            {
                lock (OutgoingLock)
                {
                    lock (ValueLock)
                    {
                        _taskForOutputProcessing = null;
                        OfferAsyncIfNecessary(isReplacementReplica: true);
                        CompleteBlockIfPossible();
                    }
                }
            }
        }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._owningSource, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._taskForOutputProcessing, System.Threading.Tasks.Dataflow.DataflowBlockOptions.ActualMaxMessagesPerTask, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CanceledOrFaulted, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.CompleteCore(), System.exception, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferAsyncIfNecessary(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferToTargets(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OutgoingLock, and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ValueLock.