Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastingSourceCore.OfferToTargets
OfferToTargets()
bool System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferToTargets () inline private
Definition at line 253 of file BroadcastBlock.cs.
        {
            DataflowMessageHeader header = default(DataflowMessageHeader);
            TOutput message = default(TOutput);
            int num = 0;
            lock (ValueLock)
            {
                if (_nextMessageReservedFor != null || _messages.Count <= 0)
                {
                    _enableOffering = false;
                    return false;
                }
                if (_targetRegistry.FirstTargetNode == null)
                {
                    while (_messages.Count > 1)
                    {
                        _messages.Dequeue();
                        num++;
                    }
                }
                message = (_currentMessage = _messages.Dequeue());
                num++;
                _currentMessageIsValid = true;
                header = new DataflowMessageHeader(++_nextMessageId);
                if (_messages.Count == 0)
                {
                    _enableOffering = false;
                }
            }
            if (header.IsValid)
            {
                if (_itemsRemovedAction != null)
                {
                    _itemsRemovedAction(num);
                }
                TargetRegistry<TOutput>.LinkedTargetInfo linkedTargetInfo = _targetRegistry.FirstTargetNode;
                while (linkedTargetInfo != null)
                {
                    TargetRegistry<TOutput>.LinkedTargetInfo next = linkedTargetInfo.Next;
                    ITargetBlock<TOutput> target = linkedTargetInfo.Target;
                    OfferMessageToTarget(header, message, target);
                    linkedTargetInfo = next;
                }
            }
            return true;
        }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._currentMessage, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._currentMessageIsValid, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._enableOffering, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._itemsRemovedAction, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._nextMessageId, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._nextMessageReservedFor, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._targetRegistry, System.Collections.Generic.Queue< T >.Count, System.Collections.Generic.Queue< T >.Dequeue(), System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.FirstTargetNode, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferMessageToTarget(), and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ValueLock.
Referenced by System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferMessagesLoopCore().