Terraria: System.Threading.Tasks.Dataflow.BroadcastBlock.BroadcastingSourceCore.OfferAsyncIfNecessary
OfferAsyncIfNecessary()
void System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferAsyncIfNecessary (bool isReplacementReplica = false) inline private
Definition at line 321 of file BroadcastBlock.cs.
        {
            bool flag = _taskForOutputProcessing != null;
            bool flag2 = _enableOffering && _messages.Count > 0;
            if (!(!flag && flag2) || CanceledOrFaulted)
            {
                return;
            }
            _taskForOutputProcessing = new Task(delegate(object thisSourceCore)
            {
                ((BroadcastingSourceCore<TOutput>)thisSourceCore).OfferMessagesLoopCore();
            }, this, Common.GetCreationOptionsForTask(isReplacementReplica));
            DataflowEtwProvider log = DataflowEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.TaskLaunchedForMessageHandling(_owningSource, _taskForOutputProcessing, DataflowEtwProvider.TaskLaunchedReason.OfferingOutputMessages, _messages.Count);
            }
            Exception ex = Common.StartTaskSafe(_taskForOutputProcessing, _dataflowBlockOptions.TaskScheduler);
            if (ex == null)
            {
                return;
            }
            AddException(ex);
            _decliningPermanently = true;
            _taskForOutputProcessing = null;
            Task.Factory.StartNew(delegate(object state)
            {
                BroadcastingSourceCore<TOutput> broadcastingSourceCore = (BroadcastingSourceCore<TOutput>)state;
                lock (broadcastingSourceCore.OutgoingLock)
                {
                    lock (broadcastingSourceCore.ValueLock)
                    {
                        broadcastingSourceCore.CompleteBlockIfPossible();
                    }
                }
            }, this, CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
        }
References System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._dataflowBlockOptions, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._decliningPermanently, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._enableOffering, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._messages, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._owningSource, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >._taskForOutputProcessing, System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.AddException(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CanceledOrFaulted, System.Collections.Generic.Queue< T >.Count, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe(), System.state, and System.Threading.Tasks.Dataflow.DataflowBlockOptions.TaskScheduler.
Referenced by System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.AddMessage(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ConsumeMessage(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferMessagesLoopCore(), and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ReleaseReservation().