Terraria: System.Xml.PrefixHandle.GetString
GetString() [1/5]
string System.Xml.PrefixHandle.GetString () inline
Definition at line 156 of file PrefixHandle.cs.
    {
        PrefixHandleType type = _type;
        if (type != PrefixHandleType.Buffer)
        {
            return GetString(type);
        }
        return _bufferReader.GetString(_offset, _length);
    }
References System.Xml.PrefixHandle._bufferReader, System.Xml.PrefixHandle._length, System.Xml.PrefixHandle._offset, System.Xml.PrefixHandle._type, System.Xml.PrefixHandle.GetString(), System.Xml.XmlBufferReader.GetString(), and System.type.
Referenced by System.Xml.PrefixHandle.CompareTo(), System.Xml.PrefixHandle.Equals2(), System.Xml.PrefixHandle.GetHashCode(), System.Xml.PrefixHandle.GetString(), System.Xml.PrefixHandle.GetString(), System.Xml.PrefixHandle.GetString(), and System.Xml.PrefixHandle.ToString().