Terraria: System.Xml.PrefixHandle.GetAlphaPrefix
GetAlphaPrefix()
static PrefixHandleType System.Xml.PrefixHandle.GetAlphaPrefix (int index) inline static
Definition at line 126 of file PrefixHandle.cs.
    {
        return (PrefixHandleType)(1 + index);
    }
References System.index.
Referenced by System.Xml.ValueHandle.GetQNameDictionaryText(), System.Xml.XmlBinaryReader.ReadAttributes2(), System.Xml.XmlBinaryReader.ReadNode(), System.Xml.XmlUTF8TextReader.ReadQualifiedName(), System.Xml.PrefixHandle.SetValue(), and System.Xml.XmlBaseReader.NamespaceManager.TryGetShortPrefix().