Terraria: System.Xml.PrefixHandle.SetValue
SetValue() [1/3]
void System.Xml.PrefixHandle.SetValue (int offset, int length) inline
Definition at line 92 of file PrefixHandle.cs.
    {
        switch (length)
        {
        case 0:
            SetValue(PrefixHandleType.Empty);
            return;
        case 1:
        {
            byte @byte = _bufferReader.GetByte(offset);
            if (@byte >= 97 && @byte <= 122)
            {
                SetValue(GetAlphaPrefix(@byte - 97));
                return;
            }
            break;
        }
        }
        _type = PrefixHandleType.Buffer;
        _offset = offset;
        _length = length;
    }
References System.Xml.PrefixHandle._bufferReader, System.Xml.PrefixHandle._length, System.Xml.PrefixHandle._offset, System.Xml.PrefixHandle._type, System.Xml.PrefixHandle.GetAlphaPrefix(), System.Xml.XmlBufferReader.GetByte(), System.length, System.offset, and System.Xml.PrefixHandle.SetValue().