Terraria: System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init
Init()
void System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init () inline package
Definition at line 79 of file ParseRecord.cs.
    {
        _parseTypeEnum = InternalParseTypeE.Empty;
        _objectTypeEnum = InternalObjectTypeE.Empty;
        _arrayTypeEnum = InternalArrayTypeE.Empty;
        _memberTypeEnum = InternalMemberTypeE.Empty;
        _memberValueEnum = InternalMemberValueE.Empty;
        _objectPositionEnum = InternalObjectPositionE.Empty;
        _name = null;
        _value = null;
        _keyDt = null;
        _dtType = null;
        _dtTypeCode = InternalPrimitiveTypeE.Invalid;
        _objectId = 0L;
        _idRef = 0L;
        _arrayElementTypeString = null;
        _arrayElementType = null;
        _isArrayVariant = false;
        _arrayElementTypeCode = InternalPrimitiveTypeE.Invalid;
        _rank = 0;
        _lengthA = null;
        _lowerBoundA = null;
        _indexMap = null;
        _memberIndex = 0;
        _linearlength = 0;
        _rectangularMap = null;
        _isLowerBound = false;
        _isValueTypeFixup = false;
        _newObj = null;
        _objectA = null;
        _primitiveArray = null;
        _objectInfo = null;
        _isRegistered = false;
        _memberData = null;
        _si = null;
        _consecutiveNullArrayEntryCount = 0;
    }
References System.Runtime.Serialization.Formatters.Binary.ParseRecord._arrayElementType, System.Runtime.Serialization.Formatters.Binary.ParseRecord._arrayElementTypeCode, System.Runtime.Serialization.Formatters.Binary.ParseRecord._arrayElementTypeString, System.Runtime.Serialization.Formatters.Binary.ParseRecord._arrayTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord._consecutiveNullArrayEntryCount, System.Runtime.Serialization.Formatters.Binary.ParseRecord._dtType, System.Runtime.Serialization.Formatters.Binary.ParseRecord._dtTypeCode, System.Runtime.Serialization.Formatters.Binary.ParseRecord._idRef, System.Runtime.Serialization.Formatters.Binary.ParseRecord._indexMap, System.Runtime.Serialization.Formatters.Binary.ParseRecord._isArrayVariant, System.Runtime.Serialization.Formatters.Binary.ParseRecord._isLowerBound, System.Runtime.Serialization.Formatters.Binary.ParseRecord._isRegistered, System.Runtime.Serialization.Formatters.Binary.ParseRecord._isValueTypeFixup, System.Runtime.Serialization.Formatters.Binary.ParseRecord._keyDt, System.Runtime.Serialization.Formatters.Binary.ParseRecord._lengthA, System.Runtime.Serialization.Formatters.Binary.ParseRecord._linearlength, System.Runtime.Serialization.Formatters.Binary.ParseRecord._lowerBoundA, System.Runtime.Serialization.Formatters.Binary.ParseRecord._memberData, System.Runtime.Serialization.Formatters.Binary.ParseRecord._memberIndex, System.Runtime.Serialization.Formatters.Binary.ParseRecord._memberTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord._memberValueEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord._name, System.Runtime.Serialization.Formatters.Binary.ParseRecord._newObj, System.Runtime.Serialization.Formatters.Binary.ParseRecord._objectA, System.Runtime.Serialization.Formatters.Binary.ParseRecord._objectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord._objectInfo, System.Runtime.Serialization.Formatters.Binary.ParseRecord._objectPositionEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord._objectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord._parseTypeEnum, System.Runtime.Serialization.Formatters.Binary.ParseRecord._primitiveArray, System.Runtime.Serialization.Formatters.Binary.ParseRecord._rank, System.Runtime.Serialization.Formatters.Binary.ParseRecord._rectangularMap, System.Runtime.Serialization.Formatters.Binary.ParseRecord._si, System.Runtime.Serialization.Formatters.Binary.ParseRecord._value, and System.L.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectProgress.Init(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveUnTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberReference(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectNull(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectString(), and System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().