Terraria: BestiaryEntry.Enemy
Enemy()
static BestiaryEntry BestiaryEntry.Enemy (int npcNetId) inline static
     {
         NPC nPC = ContentSamples.NpcsByNetId[npcNetId];
         List<IBestiaryInfoElement> list = new List<IBestiaryInfoElement>
         {
             new NPCNetIdBestiaryInfoElement(npcNetId),
             new NamePlateInfoElement(Lang.GetNPCName(npcNetId).Key, npcNetId),
             new NPCPortraitInfoElement(ContentSamples.NpcBestiaryRarityStars[npcNetId]),
             new NPCKillCounterInfoElement(npcNetId)
         };
         list.Add(new NPCStatsReportInfoElement(npcNetId));
         if (nPC.rarity != 0)
         {
             list.Add(new RareSpawnBestiaryInfoElement(nPC.rarity));
         }
         IBestiaryUICollectionInfoProvider uIInfoProvider;
         if (nPC.boss || NPCID.Sets.ShouldBeCountedAsBoss[nPC.type])
         {
             list.Add(new BossBestiaryInfoElement());
             uIInfoProvider = new CommonEnemyUICollectionInfoProvider(nPC.GetBestiaryCreditId(), quickUnlock: true);
         }
         else
         {
             uIInfoProvider = new CommonEnemyUICollectionInfoProvider(nPC.GetBestiaryCreditId(), quickUnlock: false);
         }
         string key = Lang.GetNPCName(nPC.netID).Key;
         key = key.Replace("NPCName.", "");
         string text = "Bestiary_FlavorText.npc_" + key;
         if (Language.Exists(text))
         {
             list.Add(new FlavorTextBestiaryInfoElement(text));
         }
         return new BestiaryEntry
         {
             Icon = new UnlockableNPCEntryIcon(npcNetId),
             Info = list,
             UIInfoProvider = uIInfoProvider
         };
     }
References NPC.boss, Language.Exists(), NPC.GetBestiaryCreditId(), Lang.GetNPCName(), Icon, Info, LocalizedText.Key, NPC.netID, ContentSamples.NpcBestiaryRarityStars, ContentSamples.NpcsByNetId, NPC.rarity, NPCID.Sets.ShouldBeCountedAsBoss, NPC.type, and UIInfoProvider.
Referenced by BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated(), and BestiaryDatabaseNPCsPopulator.AddMultiEntryNPCS_Manual().