Terraria: DunesBiome.PlaceHill
PlaceHill()
static void DunesBiome.PlaceHill (int startX, int endX, double scale, DunesDescription description) inline static private
     {
         Point startPoint = new Point(startX, description.Surface[startX]);
         Point endPoint = new Point(endX, description.Surface[endX]);
         Point point = new Point((startPoint.X + endPoint.X) / 2, (startPoint.Y + endPoint.Y) / 2 - (int)(35.0 * scale));
         int num = (endPoint.X - point.X) / 4;
         int minValue = (endPoint.X - point.X) / 16;
         if (description.WindDirection == WindDirection.Left)
         {
             point.X -= WorldGen.genRand.Next(minValue, num + 1);
         }
         else
         {
             point.X += WorldGen.genRand.Next(minValue, num + 1);
         }
         Point point2 = new Point(0, (int)(scale * 12.0));
         Point point3 = new Point(point2.X / -2, point2.Y / -2);
         PlaceCurvedLine(startPoint, point, (description.WindDirection != 0) ? point3 : point2, description);
         PlaceCurvedLine(point, endPoint, (description.WindDirection == WindDirection.Left) ? point3 : point2, description);
     }
References WorldGen.genRand, UnifiedRandom.Next(), PlaceCurvedLine(), DunesBiome.DunesDescription.Surface, and DunesBiome.DunesDescription.WindDirection.
Referenced by PlaceSingle().