Terraria: UIText.InternalSetText
InternalSetText()
void UIText.InternalSetText (object text, float textScale, bool large) inline private
     {
         DynamicSpriteFont val = (large ? FontAssets.DeathText.Value : FontAssets.MouseText.Value);
         _text = text;
         _isLarge = large;
         _textScale = textScale;
         _lastTextReference = _text.ToString();
         if (IsWrapped)
         {
             _visibleText = val.CreateWrappedText(_lastTextReference, GetInnerDimensions().Width / _textScale);
         }
         else
         {
             _visibleText = _lastTextReference;
         }
         Vector2 vector = val.MeasureString(_visibleText);
         Vector2 vector2 = (_textSize = ((!IsWrapped) ? (new Vector2(vector.X, large ? 32f : 16f) * textScale) : (new Vector2(vector.X, vector.Y + WrappedTextBottomPadding) * textScale)));
         MinWidth.Set(vector2.X + PaddingLeft + PaddingRight, 0f);
         MinHeight.Set(vector2.Y + PaddingTop + PaddingBottom, 0f);
         if (this.OnInternalTextChange != null)
         {
             this.OnInternalTextChange();
         }
     }
References _isLarge, _lastTextReference, _text, _textScale, _textSize, _visibleText, DynamicSpriteFont.CreateWrappedText(), FontAssets.DeathText, UIElement.GetInnerDimensions(), IsWrapped, DynamicSpriteFont.MeasureString(), UIElement.MinHeight, UIElement.MinWidth, FontAssets.MouseText, OnInternalTextChange, UIElement.PaddingBottom, UIElement.PaddingLeft, UIElement.PaddingRight, UIElement.PaddingTop, StyleDimension.Set(), Asset< T >.Value, CalculatedStyle.Width, and WrappedTextBottomPadding.
Referenced by UIText(), Recalculate(), SetText(), and VerifyTextState().