Terraria: Terraria.GameContent.NetModules.NetBestiaryModule.Deserialize
Deserialize()
override bool Terraria.GameContent.NetModules.NetBestiaryModule.Deserialize (BinaryReader reader, int userId) inline
Definition at line 41 of file NetBestiaryModule.cs.
    {
        if (Main.dedServ)
        {
            return false;
        }
        switch ((BestiaryUnlockType)reader.ReadByte())
        {
        case BestiaryUnlockType.Kill:
        {
            short key3 = reader.ReadInt16();
            string bestiaryCreditId3 = ContentSamples.NpcsByNetId[key3].GetBestiaryCreditId();
            ushort killCount = reader.ReadUInt16();
            Main.BestiaryTracker.Kills.SetKillCountDirectly(bestiaryCreditId3, killCount);
            break;
        }
        case BestiaryUnlockType.Chat:
        {
            short key2 = reader.ReadInt16();
            string bestiaryCreditId2 = ContentSamples.NpcsByNetId[key2].GetBestiaryCreditId();
            Main.BestiaryTracker.Chats.SetWasChatWithDirectly(bestiaryCreditId2);
            break;
        }
        case BestiaryUnlockType.Sight:
        {
            short key = reader.ReadInt16();
            string bestiaryCreditId = ContentSamples.NpcsByNetId[key].GetBestiaryCreditId();
            Main.BestiaryTracker.Sights.SetWasSeenDirectly(bestiaryCreditId);
            break;
        }
        }
        return true;
    }
References Terraria.Main.BestiaryTracker, Terraria.Main.dedServ, Terraria.ID.ContentSamples.NpcsByNetId, System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), and System.IO.BinaryReader.ReadUInt16().