Terraria: UIReportsPage.PopulateLogs
PopulateLogs()
void UIReportsPage.PopulateLogs (UIList listContents) inline private
     {
         List<IssueReport> list = (from report in _reporters.SelectMany((IProvideReports reporter) => reporter.GetReports())
             orderby report.timeReported
             select report).ToList();
         if (list.Count == 0)
         {
             UIText item = new UIText(Language.GetTextValue("Workshop.ReportLogsInitialMessage"))
             {
                 HAlign = 0f,
                 VAlign = 0f,
                 Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                 Height = StyleDimension.FromPixelsAndPercent(0f, 0f),
                 IsWrapped = true,
                 WrappedTextBottomPadding = 0f,
                 TextOriginX = 0.5f,
                 TextColor = Color.Gray
             };
             listContents.Add(item);
         }
         for (int i = 0; i < list.Count; i++)
         {
             UIText uIText = new UIText(list[i].reportText)
             {
                 HAlign = 0f,
                 VAlign = 0f,
                 Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
                 Height = StyleDimension.FromPixelsAndPercent(0f, 0f),
                 IsWrapped = true,
                 WrappedTextBottomPadding = 0f,
                 TextOriginX = 0f
             };
             listContents.Add(uIText);
             Asset<Texture2D> val = Main.Assets.Request<Texture2D>("Images/UI/Divider", (AssetRequestMode)1);
             UIImage element = new UIImage(val)
             {
                 Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                 Height = StyleDimension.FromPixels(val.Height()),
                 ScaleToFit = true,
                 VAlign = 1f
             };
             uIText.Append(element);
         }
         UIElement item2 = new UIElement();
         listContents.Add(item2);
     }
References UIElement.UIElement(), _reporters, UIList.Add(), UIElement.Append(), Main.Assets, Color, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), IProvideReports.GetReports(), Language.GetTextValue(), UIElement.HAlign, UIElement.Height, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().