Terraria: System.RuntimeType.CheckValue
CheckValue()
object System.RuntimeType.CheckValue (object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr) inline package
Definition at line 2997 of file RuntimeType.cs.
    {
        if (IsInstanceOfType(value))
        {
            Type type = value.GetType();
            if ((object)type != this && RuntimeTypeHandle.IsValueType(this))
            {
                return AllocateValueType(this, value, fForceTypeChange: true);
            }
            return value;
        }
        if (base.IsByRef)
        {
            RuntimeType elementType = RuntimeTypeHandle.GetElementType(this);
            if (elementType.IsInstanceOfType(value) || value == null)
            {
                return AllocateValueType(elementType, value, fForceTypeChange: false);
            }
        }
        else
        {
            if (value == null)
            {
                return value;
            }
            if (this == s_typedRef)
            {
                return value;
            }
        }
        bool flag = base.IsPointer || IsEnum || base.IsPrimitive;
        if (flag)
        {
            Pointer pointer = value as Pointer;
            RuntimeType valueType = ((pointer == null) ? ((RuntimeType)value.GetType()) : ((RuntimeType)pointer.GetPointerType()));
            if (CanValueSpecialCast(valueType, this))
            {
                if (pointer != null)
                {
                    return pointer.GetPointerValue();
                }
                return value;
            }
        }
        if ((invokeAttr & BindingFlags.ExactBinding) == BindingFlags.ExactBinding)
        {
            throw new ArgumentException(SR.Format(SR.Arg_ObjObjEx, value.GetType(), this));
        }
        return TryChangeType(value, binder, culture, flag);
    }
References System.RuntimeType.RuntimeType(), System.RuntimeType.AllocateValueType(), System.SR.Arg_ObjObjEx, System.RuntimeType.CanValueSpecialCast(), System.culture, System.elementType, System.SR.Format(), System.RuntimeTypeHandle.GetElementType(), System.Type.GetType(), System.Type.IsEnum, System.RuntimeType.IsInstanceOfType(), System.RuntimeTypeHandle.IsValueType(), System.pointer, System.RuntimeType.s_typedRef, System.RuntimeType.TryChangeType(), System.type, and System.value.
Referenced by System.Reflection.MethodBase.CheckArguments(), and System.Reflection.RtFieldInfo.SetValue().