Terraria: System.RuntimeType.RuntimeType
RuntimeType()
System.RuntimeType.RuntimeType () inline package
Definition at line 2088 of file RuntimeType.cs.
    {
        throw new NotSupportedException();
    }
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.AddSpecialInterface(), System.RuntimeType.CheckValue(), System.RuntimeType.RuntimeTypeCache.GetEnclosingType(), System.RuntimeType.GetInterfaceMap(), System.RuntimeType.GetMethodBase(), System.RuntimeType.IsSubclassOf(), System.RuntimeType.MakeGenericType(), System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateInterfaces(), System.RuntimeType.TryChangeType(), and System.RuntimeType.ValidateGenericArguments().