Terraria: System.RuntimeType.GetMethods
GetMethods() [2/2]
override MethodInfo[] System.RuntimeType.GetMethods (BindingFlags bindingAttr) inline
Implements System.Reflection.IReflect.
Definition at line 2242 of file RuntimeType.cs.
    {
        return GetMethodCandidates(null, -1, bindingAttr, CallingConventions.Any, null, allowPrefixLookup: false).ToArray();
    }
References System.RuntimeType.GetMethodCandidates().
Referenced by System.Reflection.Emit.TypeBuilder.GetMethods(), and System.Reflection.RuntimeModule.GetMethods().