Terraria: System.RuntimeType.GetPropertyCandidates
GetPropertyCandidates()
ListBuilder< PropertyInfo > System.RuntimeType.GetPropertyCandidates (string name, BindingFlags bindingAttr, Type[] types, bool allowPrefixLookup) inline private
Definition at line 2176 of file RuntimeType.cs.
    {
        FilterHelper(bindingAttr, ref name, allowPrefixLookup, out var prefixLookup, out var ignoreCase, out var listType);
        RuntimePropertyInfo[] propertyList = Cache.GetPropertyList(listType, name);
        bindingAttr ^= BindingFlags.DeclaredOnly;
        ListBuilder<PropertyInfo> result = new ListBuilder<PropertyInfo>(propertyList.Length);
        foreach (RuntimePropertyInfo runtimePropertyInfo in propertyList)
        {
            if ((bindingAttr & runtimePropertyInfo.BindingFlags) == runtimePropertyInfo.BindingFlags && (!prefixLookup || FilterApplyPrefixLookup(runtimePropertyInfo, name, ignoreCase)) && (types == null || runtimePropertyInfo.GetIndexParameters().Length == types.Length))
            {
                result.Add(runtimePropertyInfo);
            }
        }
        return result;
    }
References System.RuntimeType.FilterApplyPrefixLookup(), and System.RuntimeType.FilterHelper().
Referenced by System.RuntimeType.GetMember(), System.RuntimeType.GetMembers(), System.RuntimeType.GetProperties(), and System.RuntimeType.GetPropertyImpl().