Terraria: System.RuntimeType.GetBaseType
GetBaseType()
RuntimeType System.RuntimeType.GetBaseType () inline private
Definition at line 3998 of file RuntimeType.cs.
    {
        if (base.IsInterface)
        {
            return null;
        }
        if (RuntimeTypeHandle.IsGenericVariable(this))
        {
            Type[] genericParameterConstraints = GetGenericParameterConstraints();
            RuntimeType runtimeType = ObjectType;
            for (int i = 0; i < genericParameterConstraints.Length; i++)
            {
                RuntimeType runtimeType2 = (RuntimeType)genericParameterConstraints[i];
                if (runtimeType2.IsInterface)
                {
                    continue;
                }
                if (runtimeType2.IsGenericParameter)
                {
                    GenericParameterAttributes genericParameterAttributes = runtimeType2.GenericParameterAttributes & GenericParameterAttributes.SpecialConstraintMask;
                    if ((genericParameterAttributes & GenericParameterAttributes.ReferenceTypeConstraint) == 0 && (genericParameterAttributes & GenericParameterAttributes.NotNullableValueTypeConstraint) == 0)
                    {
                        continue;
                    }
                }
                runtimeType = runtimeType2;
            }
            if (runtimeType == ObjectType)
            {
                GenericParameterAttributes genericParameterAttributes2 = GenericParameterAttributes & GenericParameterAttributes.SpecialConstraintMask;
                if ((genericParameterAttributes2 & GenericParameterAttributes.NotNullableValueTypeConstraint) != 0)
                {
                    runtimeType = ValueType;
                }
            }
            return runtimeType;
        }
        return RuntimeTypeHandle.GetBaseType(this);
    }
References System.RuntimeTypeHandle.GetBaseType(), and System.RuntimeTypeHandle.IsGenericVariable().
Referenced by System.RuntimeType.IsDelegate(), and System.RuntimeType.IsSubclassOf().