Terraria: System.RuntimeType.GetMemberWithSameMetadataDefinitionAs
GetMemberWithSameMetadataDefinitionAs()
override MemberInfo System.RuntimeType.GetMemberWithSameMetadataDefinitionAs (MemberInfo member) inline virtual
Reimplemented from System.Type.
Definition at line 2710 of file RuntimeType.cs.
    {
        if ((object)member == null)
        {
            throw new ArgumentNullException("member");
        }
        RuntimeType runtimeType = this;
        while (runtimeType != null)
        {
            MemberInfo memberInfo = member.MemberType switch
            {
                MemberTypes.Method => GetMethodWithSameMetadataDefinitionAs(runtimeType, member),
                MemberTypes.Constructor => GetConstructorWithSameMetadataDefinitionAs(runtimeType, member),
                MemberTypes.Property => GetPropertyWithSameMetadataDefinitionAs(runtimeType, member),
                MemberTypes.Field => GetFieldWithSameMetadataDefinitionAs(runtimeType, member),
                MemberTypes.Event => GetEventWithSameMetadataDefinitionAs(runtimeType, member),
                MemberTypes.NestedType => GetNestedTypeWithSameMetadataDefinitionAs(runtimeType, member),
                _ => null,
            };
            if (memberInfo != null)
            {
                return memberInfo;
            }
            runtimeType = runtimeType.GetBaseType();
        }
        throw Type.CreateGetMemberWithSameMetadataDefinitionAsNotFoundException(member);
    }
References System.Type.CreateGetMemberWithSameMetadataDefinitionAsNotFoundException(), System.RuntimeType.GetConstructorWithSameMetadataDefinitionAs(), System.RuntimeType.GetEventWithSameMetadataDefinitionAs(), System.RuntimeType.GetFieldWithSameMetadataDefinitionAs(), System.RuntimeType.GetMethodWithSameMetadataDefinitionAs(), System.RuntimeType.GetNestedTypeWithSameMetadataDefinitionAs(), and System.RuntimeType.GetPropertyWithSameMetadataDefinitionAs().