Terraria: System.RuntimeType.ValidateGenericArguments
ValidateGenericArguments()
static void System.RuntimeType.ValidateGenericArguments (MemberInfo definition, RuntimeType[] genericArguments, Exception e) inline static package
Definition at line 1800 of file RuntimeType.cs.
    {
        RuntimeType[] typeContext = null;
        RuntimeType[] methodContext = null;
        RuntimeType[] genericArgumentsInternal;
        if (definition is Type)
        {
            RuntimeType runtimeType = (RuntimeType)definition;
            genericArgumentsInternal = runtimeType.GetGenericArgumentsInternal();
            typeContext = genericArguments;
        }
        else
        {
            RuntimeMethodInfo runtimeMethodInfo = (RuntimeMethodInfo)definition;
            genericArgumentsInternal = runtimeMethodInfo.GetGenericArgumentsInternal();
            methodContext = genericArguments;
            RuntimeType runtimeType2 = (RuntimeType)runtimeMethodInfo.DeclaringType;
            if (runtimeType2 != null)
            {
                typeContext = runtimeType2.GetTypeHandleInternal().GetInstantiationInternal();
            }
        }
        for (int i = 0; i < genericArguments.Length; i++)
        {
            Type type = genericArguments[i];
            Type type2 = genericArgumentsInternal[i];
            if (!RuntimeTypeHandle.SatisfiesConstraints(type2.GetTypeHandleInternal().GetTypeChecked(), typeContext, methodContext, type.GetTypeHandleInternal().GetTypeChecked()))
            {
                throw new ArgumentException(SR.Format(SR.Argument_GenConstraintViolation, i.ToString(), type, definition, type2), e);
            }
        }
    }
References System.RuntimeType.RuntimeType(), System.SR.Argument_GenConstraintViolation, System.SR.Format(), System.RuntimeTypeHandle.SatisfiesConstraints(), and System.type.
Referenced by System.Reflection.RuntimeMethodInfo.MakeGenericMethod(), and System.RuntimeType.MakeGenericType().