Terraria: System.RuntimeType.GetType
GetType() [5/8]
static RuntimeType System.RuntimeType.GetType (string typeName, bool throwOnError, bool ignoreCase, ref StackCrawlMark stackMark) inline static package
Definition at line 1664 of file RuntimeType.cs.
    {
        if (typeName == null)
        {
            throw new ArgumentNullException("typeName");
        }
        return RuntimeTypeHandle.GetTypeByName(typeName, throwOnError, ignoreCase, ref stackMark);
    }
References System.RuntimeTypeHandle.GetTypeByName().
Referenced by System.Type.GetType(), System.Type.GetType(), System.Type.GetType(), and System.TypeNameParser.ResolveType().