Terraria: System.RuntimeType.GetEventCandidates
GetEventCandidates()
ListBuilder< EventInfo > System.RuntimeType.GetEventCandidates (string name, BindingFlags bindingAttr, bool allowPrefixLookup) inline private
Definition at line 2192 of file RuntimeType.cs.
    {
        FilterHelper(bindingAttr, ref name, allowPrefixLookup, out var prefixLookup, out var ignoreCase, out var listType);
        RuntimeEventInfo[] eventList = Cache.GetEventList(listType, name);
        bindingAttr ^= BindingFlags.DeclaredOnly;
        ListBuilder<EventInfo> result = new ListBuilder<EventInfo>(eventList.Length);
        foreach (RuntimeEventInfo runtimeEventInfo in eventList)
        {
            if ((bindingAttr & runtimeEventInfo.BindingFlags) == runtimeEventInfo.BindingFlags && (!prefixLookup || FilterApplyPrefixLookup(runtimeEventInfo, name, ignoreCase)))
            {
                result.Add(runtimeEventInfo);
            }
        }
        return result;
    }
References System.RuntimeType.FilterApplyPrefixLookup(), and System.RuntimeType.FilterHelper().
Referenced by System.RuntimeType.GetEvents(), System.RuntimeType.GetMember(), and System.RuntimeType.GetMembers().