Terraria: System.RuntimeType.GetMethodImplCommon
GetMethodImplCommon()
MethodInfo System.RuntimeType.GetMethodImplCommon (string name, int genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers) inline private
Definition at line 2376 of file RuntimeType.cs.
    {
        ListBuilder<MethodInfo> methodCandidates = GetMethodCandidates(name, genericParameterCount, bindingAttr, callConv, types, allowPrefixLookup: false);
        if (methodCandidates.Count == 0)
        {
            return null;
        }
        MethodBase[] match;
        if (types == null || types.Length == 0)
        {
            MethodInfo methodInfo = methodCandidates[0];
            if (methodCandidates.Count == 1)
            {
                return methodInfo;
            }
            if (types == null)
            {
                for (int i = 1; i < methodCandidates.Count; i++)
                {
                    MethodInfo m = methodCandidates[i];
                    if (!System.DefaultBinder.CompareMethodSig(m, methodInfo))
                    {
                        throw new AmbiguousMatchException(SR.Arg_AmbiguousMatchException);
                    }
                }
                match = methodCandidates.ToArray();
                return System.DefaultBinder.FindMostDerivedNewSlotMeth(match, methodCandidates.Count) as MethodInfo;
            }
        }
        if (binder == null)
        {
            binder = Type.DefaultBinder;
        }
        Binder binder2 = binder;
        match = methodCandidates.ToArray();
        return binder2.SelectMethod(bindingAttr, match, types, modifiers) as MethodInfo;
    }
References System.SR.Arg_AmbiguousMatchException, System.DefaultBinder.CompareMethodSig(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Type.DefaultBinder, System.DefaultBinder.FindMostDerivedNewSlotMeth(), System.RuntimeType.GetMethodCandidates(), and System.match.
Referenced by System.RuntimeType.GetMethodImpl(), and System.RuntimeType.GetMethodImpl().