Terraria: System.RuntimeType.FilterHelper
FilterHelper() [1/2]
static void System.RuntimeType.FilterHelper (BindingFlags bindingFlags, ref string name, bool allowPrefixLookup, out bool prefixLookup, out bool ignoreCase, out MemberListType listType) inline static private
Definition at line 1880 of file RuntimeType.cs.
    {
        prefixLookup = false;
        ignoreCase = false;
        if (name != null)
        {
            if ((bindingFlags & BindingFlags.IgnoreCase) != 0)
            {
                name = name.ToLowerInvariant();
                ignoreCase = true;
                listType = MemberListType.CaseInsensitive;
            }
            else
            {
                listType = MemberListType.CaseSensitive;
            }
            if (allowPrefixLookup && name.EndsWith("*", StringComparison.Ordinal))
            {
                name = name[0..^1];
                prefixLookup = true;
                listType = MemberListType.All;
            }
        }
        else
        {
            listType = MemberListType.All;
        }
    }
Referenced by System.RuntimeType.FilterHelper(), System.RuntimeType.GetConstructorCandidates(), System.RuntimeType.GetEvent(), System.RuntimeType.GetEventCandidates(), System.RuntimeType.GetField(), System.RuntimeType.GetFieldCandidates(), System.RuntimeType.GetInterface(), System.RuntimeType.GetMethodCandidates(), System.RuntimeType.GetNestedType(), System.RuntimeType.GetNestedTypeCandidates(), and System.RuntimeType.GetPropertyCandidates().