Terraria: System.RuntimeType.GetTypeCodeImpl
GetTypeCodeImpl()
override TypeCode System.RuntimeType.GetTypeCodeImpl () inline protected virtual
Reimplemented from System.Type.
Definition at line 3513 of file RuntimeType.cs.
    {
        TypeCode typeCode = Cache.TypeCode;
        if (typeCode != 0)
        {
            return typeCode;
        }
        typeCode = RuntimeTypeHandle.GetCorElementType(this) switch
        {
            CorElementType.ELEMENT_TYPE_BOOLEAN => TypeCode.Boolean,
            CorElementType.ELEMENT_TYPE_CHAR => TypeCode.Char,
            CorElementType.ELEMENT_TYPE_I1 => TypeCode.SByte,
            CorElementType.ELEMENT_TYPE_U1 => TypeCode.Byte,
            CorElementType.ELEMENT_TYPE_I2 => TypeCode.Int16,
            CorElementType.ELEMENT_TYPE_U2 => TypeCode.UInt16,
            CorElementType.ELEMENT_TYPE_I4 => TypeCode.Int32,
            CorElementType.ELEMENT_TYPE_U4 => TypeCode.UInt32,
            CorElementType.ELEMENT_TYPE_I8 => TypeCode.Int64,
            CorElementType.ELEMENT_TYPE_U8 => TypeCode.UInt64,
            CorElementType.ELEMENT_TYPE_R4 => TypeCode.Single,
            CorElementType.ELEMENT_TYPE_R8 => TypeCode.Double,
            CorElementType.ELEMENT_TYPE_VALUETYPE => ((object)this != typeof(decimal)) ? (((object)this != typeof(DateTime)) ? ((!IsEnum) ? TypeCode.Object : Type.GetTypeCode(Enum.InternalGetUnderlyingType(this))) : TypeCode.DateTime) : TypeCode.Decimal,
            _ => ((object)this != typeof(string)) ? (((object)this != typeof(DBNull)) ? TypeCode.Object : TypeCode.DBNull) : TypeCode.String,
        };
        Cache.TypeCode = typeCode;
        return typeCode;
    }
References System.RuntimeTypeHandle.GetCorElementType(), System.Type.GetTypeCode(), and System.Enum.InternalGetUnderlyingType().