Terraria: System.RuntimeType.FilterApplyPrefixLookup
FilterApplyPrefixLookup()
static bool System.RuntimeType.FilterApplyPrefixLookup (MemberInfo memberInfo, string name, bool ignoreCase) inline static private
Definition at line 1914 of file RuntimeType.cs.
    {
        if (ignoreCase)
        {
            if (!memberInfo.Name.StartsWith(name, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }
        }
        else if (!memberInfo.Name.StartsWith(name, StringComparison.Ordinal))
        {
            return false;
        }
        return true;
    }
Referenced by System.RuntimeType.FilterApplyBase(), System.RuntimeType.GetConstructorCandidates(), System.RuntimeType.GetEventCandidates(), System.RuntimeType.GetFieldCandidates(), System.RuntimeType.GetMethodCandidates(), and System.RuntimeType.GetPropertyCandidates().