Terraria: System.RuntimeType.InitializeCache
InitializeCache()
RuntimeTypeCache System.RuntimeType.InitializeCache () inline private
Definition at line 2108 of file RuntimeType.cs.
    {
        if (m_cache == IntPtr.Zero)
        {
            RuntimeTypeHandle runtimeTypeHandle = new RuntimeTypeHandle(this);
            IntPtr gCHandle = runtimeTypeHandle.GetGCHandle(GCHandleType.WeakTrackResurrection);
            IntPtr intPtr = Interlocked.CompareExchange(ref m_cache, gCHandle, IntPtr.Zero);
            if (intPtr != IntPtr.Zero)
            {
                runtimeTypeHandle.FreeGCHandle(gCHandle);
            }
        }
        RuntimeTypeCache runtimeTypeCache = (RuntimeTypeCache)GCHandle.InternalGet(m_cache);
        if (runtimeTypeCache == null)
        {
            runtimeTypeCache = new RuntimeTypeCache(this);
            RuntimeTypeCache runtimeTypeCache2 = (RuntimeTypeCache)GCHandle.InternalCompareExchange(m_cache, runtimeTypeCache, null);
            if (runtimeTypeCache2 != null)
            {
                runtimeTypeCache = runtimeTypeCache2;
            }
        }
        return runtimeTypeCache;
    }
References System.Threading.Interlocked.CompareExchange(), System.Runtime.InteropServices.GCHandle.InternalCompareExchange(), System.Runtime.InteropServices.GCHandle.InternalGet(), System.RuntimeType.m_cache, and System.IntPtr.Zero.