Terraria: System.RuntimeType.GetRuntimeModule
GetRuntimeModule()
RuntimeModule System.RuntimeType.GetRuntimeModule () inline package
Definition at line 3508 of file RuntimeType.cs.
    {
        return RuntimeTypeHandle.GetModule(this);
    }
References System.RuntimeTypeHandle.GetModule().
Referenced by System.Reflection.CustomAttribute.GetAttributeUsage(), System.Reflection.RuntimeCustomAttributeData.GetCustomAttributesInternal(), System.Reflection.MdFieldInfo.GetRuntimeModule(), System.Reflection.RuntimeEventInfo.GetRuntimeModule(), System.Reflection.RuntimeMethodInfo.GetRuntimeModule(), System.Reflection.RuntimePropertyInfo.GetRuntimeModule(), and System.Reflection.Emit.DynamicMethod.Init().