Terraria: System.RuntimeType.ForwardCallToInvokeMember
ForwardCallToInvokeMember()
object System.RuntimeType.ForwardCallToInvokeMember (string memberName, BindingFlags flags, object target, object[] aArgs, bool[] aArgsIsByRef, int[] aArgsWrapperTypes, Type[] aArgsTypes, Type retType) inline private
Definition at line 3265 of file RuntimeType.cs.
    {
        if (!Marshal.IsBuiltInComSupported)
        {
            throw new NotSupportedException(SR.NotSupported_COM);
        }
        int num = aArgs.Length;
        ParameterModifier[] array = null;
        if (num > 0)
        {
            ParameterModifier parameterModifier = new ParameterModifier(num);
            for (int i = 0; i < num; i++)
            {
                parameterModifier[i] = aArgsIsByRef[i];
            }
            array = new ParameterModifier[1] { parameterModifier };
            if (aArgsWrapperTypes != null)
            {
                WrapArgsForInvokeCall(aArgs, aArgsWrapperTypes);
            }
        }
        flags |= BindingFlags.DoNotWrapExceptions;
        object obj = InvokeMember(memberName, flags, null, target, aArgs, array, null, null);
        for (int j = 0; j < num; j++)
        {
            if (array[0][j] && aArgs[j] != null)
            {
                Type type = aArgsTypes[j];
                if ((object)type != aArgs[j].GetType())
                {
                    aArgs[j] = ForwardCallBinder.ChangeType(aArgs[j], type, null);
                }
            }
        }
        if (obj != null && (object)retType != obj.GetType())
        {
            obj = ForwardCallBinder.ChangeType(obj, retType, null);
        }
        return obj;
    }
References System.array, System.RuntimeType.ForwardCallBinder, System.Type.GetType(), System.RuntimeType.InvokeMember(), System.Runtime.InteropServices.Marshal.IsBuiltInComSupported, System.SR.NotSupported_COM, System.obj, System.type, and System.RuntimeType.WrapArgsForInvokeCall().