Terraria: System.RuntimeType.GetMembers
GetMembers() [2/2]
override MemberInfo[] System.RuntimeType.GetMembers (BindingFlags bindingAttr) inline
Implements System.Reflection.IReflect.
Definition at line 2286 of file RuntimeType.cs.
    {
        ListBuilder<MethodInfo> methodCandidates = GetMethodCandidates(null, -1, bindingAttr, CallingConventions.Any, null, allowPrefixLookup: false);
        ListBuilder<ConstructorInfo> constructorCandidates = GetConstructorCandidates(null, bindingAttr, CallingConventions.Any, null, allowPrefixLookup: false);
        ListBuilder<PropertyInfo> propertyCandidates = GetPropertyCandidates(null, bindingAttr, null, allowPrefixLookup: false);
        ListBuilder<EventInfo> eventCandidates = GetEventCandidates(null, bindingAttr, allowPrefixLookup: false);
        ListBuilder<FieldInfo> fieldCandidates = GetFieldCandidates(null, bindingAttr, allowPrefixLookup: false);
        ListBuilder<Type> nestedTypeCandidates = GetNestedTypeCandidates(null, bindingAttr, allowPrefixLookup: false);
        MemberInfo[] array = new MemberInfo[methodCandidates.Count + constructorCandidates.Count + propertyCandidates.Count + eventCandidates.Count + fieldCandidates.Count + nestedTypeCandidates.Count];
        int num = 0;
        object[] array2 = array;
        methodCandidates.CopyTo(array2, num);
        num += methodCandidates.Count;
        array2 = array;
        constructorCandidates.CopyTo(array2, num);
        num += constructorCandidates.Count;
        array2 = array;
        propertyCandidates.CopyTo(array2, num);
        num += propertyCandidates.Count;
        array2 = array;
        eventCandidates.CopyTo(array2, num);
        num += eventCandidates.Count;
        array2 = array;
        fieldCandidates.CopyTo(array2, num);
        num += fieldCandidates.Count;
        array2 = array;
        nestedTypeCandidates.CopyTo(array2, num);
        num += nestedTypeCandidates.Count;
        return array;
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.RuntimeType.GetConstructorCandidates(), System.RuntimeType.GetEventCandidates(), System.RuntimeType.GetFieldCandidates(), System.RuntimeType.GetMethodCandidates(), System.RuntimeType.GetNestedTypeCandidates(), and System.RuntimeType.GetPropertyCandidates().
Referenced by System.Reflection.Emit.TypeBuilder.GetMembers().