Terraria: System.RuntimeType.TryChangeType
TryChangeType()
object System.RuntimeType.TryChangeType (object value, Binder binder, CultureInfo culture, bool needsSpecialCast) inline private
Definition at line 3048 of file RuntimeType.cs.
    {
        if (binder != null && binder != Type.DefaultBinder)
        {
            value = binder.ChangeType(value, this, culture);
            if (IsInstanceOfType(value))
            {
                return value;
            }
            if (base.IsByRef)
            {
                RuntimeType elementType = RuntimeTypeHandle.GetElementType(this);
                if (elementType.IsInstanceOfType(value) || value == null)
                {
                    return AllocateValueType(elementType, value, fForceTypeChange: false);
                }
            }
            else if (value == null)
            {
                return value;
            }
            if (needsSpecialCast)
            {
                Pointer pointer = value as Pointer;
                RuntimeType valueType = ((pointer == null) ? ((RuntimeType)value.GetType()) : ((RuntimeType)pointer.GetPointerType()));
                if (CanValueSpecialCast(valueType, this))
                {
                    if (pointer != null)
                    {
                        return pointer.GetPointerValue();
                    }
                    return value;
                }
            }
        }
        throw new ArgumentException(SR.Format(SR.Arg_ObjObjEx, value.GetType(), this));
    }
References System.RuntimeType.RuntimeType(), System.RuntimeType.AllocateValueType(), System.SR.Arg_ObjObjEx, System.RuntimeType.CanValueSpecialCast(), System.culture, System.Type.DefaultBinder, System.elementType, System.SR.Format(), System.RuntimeTypeHandle.GetElementType(), System.RuntimeType.IsInstanceOfType(), System.pointer, and System.value.
Referenced by System.RuntimeType.CheckValue().