Terraria: System.RuntimeType.SanityCheckGenericArguments
SanityCheckGenericArguments()
static void System.RuntimeType.SanityCheckGenericArguments (RuntimeType[] genericArguments, RuntimeType[] genericParameters) inline static package
Definition at line 4046 of file RuntimeType.cs.
    {
        if (genericArguments == null)
        {
            throw new ArgumentNullException();
        }
        for (int i = 0; i < genericArguments.Length; i++)
        {
            if (genericArguments[i] == null)
            {
                throw new ArgumentNullException();
            }
            ThrowIfTypeNeverValidGenericArgument(genericArguments[i]);
        }
        if (genericArguments.Length != genericParameters.Length)
        {
            throw new ArgumentException(SR.Format(SR.Argument_NotEnoughGenArguments, genericArguments.Length, genericParameters.Length));
        }
    }
References System.SR.Argument_NotEnoughGenArguments, and System.SR.Format().
Referenced by System.Reflection.RuntimeMethodInfo.MakeGenericMethod(), and System.RuntimeType.MakeGenericType().