Terraria: System.RuntimeType.GetFieldInfo
GetFieldInfo() [2/2]
static FieldInfo System.RuntimeType.GetFieldInfo (RuntimeType reflectedType, IRuntimeFieldInfo field) inline static package
Definition at line 1767 of file RuntimeType.cs.
    {
        RuntimeFieldHandleInternal value = field.Value;
        if (reflectedType == null)
        {
            reflectedType = RuntimeFieldHandle.GetApproxDeclaringType(value);
        }
        else
        {
            RuntimeType approxDeclaringType = RuntimeFieldHandle.GetApproxDeclaringType(value);
            if (reflectedType != approxDeclaringType && (!RuntimeFieldHandle.AcquiresContextFromThis(value) || !RuntimeTypeHandle.CompareCanonicalHandles(approxDeclaringType, reflectedType)))
            {
                throw new ArgumentException(SR.Format(SR.Argument_ResolveFieldHandle, reflectedType, approxDeclaringType));
            }
        }
        FieldInfo field2 = reflectedType.Cache.GetField(value);
        GC.KeepAlive(field);
        return field2;
    }
References System.RuntimeFieldHandle.AcquiresContextFromThis(), System.SR.Argument_ResolveFieldHandle, System.RuntimeTypeHandle.CompareCanonicalHandles(), System.SR.Format(), System.RuntimeFieldHandle.GetApproxDeclaringType(), System.GC.KeepAlive(), and System.value.