Terraria: System.RuntimeType.GetMethodBase
GetMethodBase() [4/4]
static MethodBase System.RuntimeType.GetMethodBase (RuntimeType reflectedType, RuntimeMethodHandleInternal methodHandle) inline static package
Definition at line 1692 of file RuntimeType.cs.
    {
        if (RuntimeMethodHandle.IsDynamicMethod(methodHandle))
        {
            return RuntimeMethodHandle.GetResolver(methodHandle)?.GetDynamicMethod();
        }
        RuntimeType runtimeType = RuntimeMethodHandle.GetDeclaringType(methodHandle);
        RuntimeType[] array = null;
        if ((object)reflectedType == null)
        {
            reflectedType = runtimeType;
        }
        if (reflectedType != runtimeType && !reflectedType.IsSubclassOf(runtimeType))
        {
            if (reflectedType.IsArray)
            {
                MethodBase[] array2 = reflectedType.GetMember(RuntimeMethodHandle.GetName(methodHandle), MemberTypes.Constructor | MemberTypes.Method, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic) as MethodBase[];
                bool flag = false;
                for (int i = 0; i < array2.Length; i++)
                {
                    IRuntimeMethodInfo runtimeMethodInfo = (IRuntimeMethodInfo)array2[i];
                    if (runtimeMethodInfo.Value.Value == methodHandle.Value)
                    {
                        flag = true;
                    }
                }
                if (!flag)
                {
                    throw new ArgumentException(SR.Format(SR.Argument_ResolveMethodHandle, reflectedType, runtimeType));
                }
            }
            else if (runtimeType.IsGenericType)
            {
                RuntimeType runtimeType2 = (RuntimeType)runtimeType.GetGenericTypeDefinition();
                RuntimeType runtimeType3 = reflectedType;
                while (runtimeType3 != null)
                {
                    RuntimeType runtimeType4 = runtimeType3;
                    if (runtimeType4.IsGenericType && !runtimeType3.IsGenericTypeDefinition)
                    {
                        runtimeType4 = (RuntimeType)runtimeType4.GetGenericTypeDefinition();
                    }
                    if (runtimeType4 == runtimeType2)
                    {
                        break;
                    }
                    runtimeType3 = runtimeType3.GetBaseType();
                }
                if (runtimeType3 == null)
                {
                    throw new ArgumentException(SR.Format(SR.Argument_ResolveMethodHandle, reflectedType, runtimeType));
                }
                runtimeType = runtimeType3;
                if (!RuntimeMethodHandle.IsGenericMethodDefinition(methodHandle))
                {
                    array = RuntimeMethodHandle.GetMethodInstantiationInternal(methodHandle);
                }
                methodHandle = RuntimeMethodHandle.GetMethodFromCanonical(methodHandle, runtimeType);
            }
            else if (!runtimeType.IsAssignableFrom(reflectedType))
            {
                throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, SR.Argument_ResolveMethodHandle, reflectedType.ToString(), runtimeType.ToString()));
            }
        }
        methodHandle = RuntimeMethodHandle.GetStubIfNeeded(methodHandle, runtimeType, array);
        MethodBase result = (RuntimeMethodHandle.IsConstructor(methodHandle) ? reflectedType.Cache.GetConstructor(runtimeType, methodHandle) : ((!RuntimeMethodHandle.HasMethodInstantiation(methodHandle) || RuntimeMethodHandle.IsGenericMethodDefinition(methodHandle)) ? reflectedType.Cache.GetMethod(runtimeType, methodHandle) : reflectedType.Cache.GetGenericMethodInfo(methodHandle)));
        GC.KeepAlive(array);
        return result;
    }
References System.RuntimeType.RuntimeType(), System.SR.Argument_ResolveMethodHandle, System.array, System.Globalization.CultureInfo.CurrentCulture, System.SR.Format(), System.Format, System.RuntimeMethodHandle.GetDeclaringType(), System.RuntimeMethodHandle.GetMethodFromCanonical(), System.RuntimeMethodHandle.GetMethodInstantiationInternal(), System.RuntimeMethodHandle.GetName(), System.RuntimeMethodHandle.GetResolver(), System.RuntimeMethodHandle.GetStubIfNeeded(), System.RuntimeMethodHandle.HasMethodInstantiation(), System.RuntimeMethodHandle.IsConstructor(), System.RuntimeMethodHandle.IsDynamicMethod(), System.RuntimeMethodHandle.IsGenericMethodDefinition(), and System.GC.KeepAlive().