Terraria: System.RuntimeType.CreateInstanceImpl
CreateInstanceImpl()
object System.RuntimeType.CreateInstanceImpl (BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture) inline package
Definition at line 3116 of file RuntimeType.cs.
    {
        CreateInstanceCheckThis();
        if (args == null)
        {
            args = Array.Empty<object>();
        }
        if (binder == null)
        {
            binder = Type.DefaultBinder;
        }
        bool publicOnly = (bindingAttr & BindingFlags.NonPublic) == 0;
        bool wrapExceptions = (bindingAttr & BindingFlags.DoNotWrapExceptions) == 0;
        object result;
        if (args.Length == 0 && (bindingAttr & BindingFlags.Public) != 0 && (bindingAttr & BindingFlags.Instance) != 0 && (IsGenericCOMObjectImpl() || base.IsValueType))
        {
            result = CreateInstanceDefaultCtor(publicOnly, wrapExceptions);
        }
        else
        {
            ConstructorInfo[] constructors = GetConstructors(bindingAttr);
            List<MethodBase> list = new List<MethodBase>(constructors.Length);
            Type[] array = new Type[args.Length];
            for (int i = 0; i < args.Length; i++)
            {
                object obj = args[i];
                if (obj != null)
                {
                    array[i] = obj.GetType();
                }
            }
            for (int j = 0; j < constructors.Length; j++)
            {
                if (FilterApplyConstructorInfo((RuntimeConstructorInfo)constructors[j], bindingAttr, CallingConventions.Any, array))
                {
                    list.Add(constructors[j]);
                }
            }
            if (list.Count == 0)
            {
                throw new MissingMethodException(SR.Format(SR.MissingConstructor_Name, FullName));
            }
            MethodBase[] match = list.ToArray();
            object state = null;
            MethodBase methodBase;
            try
            {
                methodBase = binder.BindToMethod(bindingAttr, match, ref args, null, culture, null, out state);
            }
            catch (MissingMethodException)
            {
                methodBase = null;
            }
            if ((object)methodBase == null)
            {
                throw new MissingMethodException(SR.Format(SR.MissingConstructor_Name, FullName));
            }
            if (methodBase.GetParametersNoCopy().Length == 0)
            {
                if (args.Length != 0)
                {
                    throw new NotSupportedException(SR.NotSupported_CallToVarArg);
                }
                result = Activator.CreateInstance(this, nonPublic: true, wrapExceptions);
            }
            else
            {
                result = ((ConstructorInfo)methodBase).Invoke(bindingAttr, binder, args, culture);
                if (state != null)
                {
                    binder.ReorderArgumentArray(ref args, state);
                }
            }
        }
        return result;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Activator.CreateInstance(), System.RuntimeType.CreateInstanceCheckThis(), System.RuntimeType.CreateInstanceDefaultCtor(), System.culture, System.Type.DefaultBinder, System.RuntimeType.FilterApplyConstructorInfo(), System.SR.Format(), System.RuntimeType.FullName, System.Type.GetConstructors(), System.RuntimeType.IsGenericCOMObjectImpl(), System.list, System.match, System.SR.MissingConstructor_Name, System.SR.NotSupported_CallToVarArg, System.obj, and System.state.