Terraria: System.RuntimeType.GetInterfaceMap
GetInterfaceMap()
override InterfaceMapping System.RuntimeType.GetInterfaceMap ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)] Type ifaceType) inline virtual
Reimplemented from System.Type.
Definition at line 2317 of file RuntimeType.cs.
    {
        if (IsGenericParameter)
        {
            throw new InvalidOperationException(SR.Arg_GenericParameter);
        }
        if ((object)ifaceType == null)
        {
            throw new ArgumentNullException("ifaceType");
        }
        RuntimeType runtimeType = ifaceType as RuntimeType;
        if (runtimeType == null)
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeType, "ifaceType");
        }
        RuntimeTypeHandle typeHandleInternal = runtimeType.GetTypeHandleInternal();
        GetTypeHandleInternal().VerifyInterfaceIsImplemented(typeHandleInternal);
        if (IsSZArray && ifaceType.IsGenericType)
        {
            throw new ArgumentException(SR.Argument_ArrayGetInterfaceMap);
        }
        int numVirtualsAndStaticVirtuals = RuntimeTypeHandle.GetNumVirtualsAndStaticVirtuals(runtimeType);
        System.Runtime.CompilerServices.Unsafe.SkipInit(out InterfaceMapping result);
        result.InterfaceType = ifaceType;
        result.TargetType = this;
        result.InterfaceMethods = new MethodInfo[numVirtualsAndStaticVirtuals];
        result.TargetMethods = new MethodInfo[numVirtualsAndStaticVirtuals];
        for (int i = 0; i < numVirtualsAndStaticVirtuals; i++)
        {
            RuntimeMethodHandleInternal methodAt = RuntimeTypeHandle.GetMethodAt(runtimeType, i);
            MethodBase methodBase = GetMethodBase(runtimeType, methodAt);
            result.InterfaceMethods[i] = (MethodInfo)methodBase;
            RuntimeMethodHandleInternal interfaceMethodImplementation = GetTypeHandleInternal().GetInterfaceMethodImplementation(typeHandleInternal, methodAt);
            if (!interfaceMethodImplementation.IsNullHandle())
            {
                RuntimeType runtimeType2 = RuntimeMethodHandle.GetDeclaringType(interfaceMethodImplementation);
                if (!runtimeType2.IsInterface)
                {
                    runtimeType2 = this;
                }
                MethodBase methodBase2 = GetMethodBase(runtimeType2, interfaceMethodImplementation);
                result.TargetMethods[i] = (MethodInfo)methodBase2;
            }
        }
        return result;
    }
References System.RuntimeType.RuntimeType(), System.SR.Arg_GenericParameter, System.SR.Argument_ArrayGetInterfaceMap, System.SR.Argument_MustBeRuntimeType, System.RuntimeMethodHandle.GetDeclaringType(), System.RuntimeTypeHandle.GetMethodAt(), System.RuntimeType.GetMethodBase(), System.RuntimeTypeHandle.GetNumVirtualsAndStaticVirtuals(), System.Type.GetTypeHandleInternal(), System.RuntimeType.IsGenericParameter, and System.RuntimeType.IsSZArray.
Referenced by System.Reflection.Emit.TypeBuilder.GetInterfaceMap().