Terraria: System.RuntimeType.GetField
GetField() [2/2]
override FieldInfo System.RuntimeType.GetField (string name, BindingFlags bindingAttr) inline
Implements System.Reflection.IReflect.
Definition at line 2511 of file RuntimeType.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException();
        }
        FilterHelper(bindingAttr, ref name, out var _, out var listType);
        RuntimeFieldInfo[] fieldList = Cache.GetFieldList(listType, name);
        FieldInfo fieldInfo = null;
        bindingAttr ^= BindingFlags.DeclaredOnly;
        bool flag = false;
        foreach (RuntimeFieldInfo runtimeFieldInfo in fieldList)
        {
            if ((bindingAttr & runtimeFieldInfo.BindingFlags) != runtimeFieldInfo.BindingFlags)
            {
                continue;
            }
            if (fieldInfo != null)
            {
                if ((object)runtimeFieldInfo.DeclaringType == fieldInfo.DeclaringType)
                {
                    throw new AmbiguousMatchException(SR.Arg_AmbiguousMatchException);
                }
                if (fieldInfo.DeclaringType.IsInterface && runtimeFieldInfo.DeclaringType.IsInterface)
                {
                    flag = true;
                }
            }
            if (fieldInfo == null || runtimeFieldInfo.DeclaringType.IsSubclassOf(fieldInfo.DeclaringType) || fieldInfo.DeclaringType.IsInterface)
            {
                fieldInfo = runtimeFieldInfo;
            }
        }
        if (flag && fieldInfo.DeclaringType.IsInterface)
        {
            throw new AmbiguousMatchException(SR.Arg_AmbiguousMatchException);
        }
        return fieldInfo;
    }
References System.SR.Arg_AmbiguousMatchException, and System.RuntimeType.FilterHelper().
Referenced by System.Reflection.Emit.TypeBuilder.GetField(), and System.Reflection.RuntimeModule.GetField().