Terraria: System.RuntimeType.GetMethodBase
GetMethodBase() [2/4]
static MethodBase System.RuntimeType.GetMethodBase (RuntimeModule scope, int typeMetadataToken) inline static package
Definition at line 1674 of file RuntimeType.cs.
    {
        return GetMethodBase(new ModuleHandle(scope).ResolveMethodHandle(typeMetadataToken).GetMethodInfo());
    }
References System.RuntimeType.GetMethodBase().
Referenced by System.Reflection.RuntimeCustomAttributeData.RuntimeCustomAttributeData(), System.Reflection.Associates.AssignAssociates(), System.Delegate.DynamicInvokeImpl(), System.Reflection.RuntimeMethodInfo.GetBaseDefinition(), System.Exception.GetExceptionMethodFromStackTrace(), System.Reflection.RuntimeMethodInfo.GetGenericMethodDefinition(), System.RuntimeType.GetInterfaceMap(), System.Diagnostics.StackFrameHelper.GetMethodBase(), System.RuntimeType.GetMethodBase(), System.RuntimeType.GetMethodBase(), System.RuntimeType.GetMethodBase(), System.Reflection.MethodBase.GetMethodFromHandle(), System.Reflection.MethodBase.GetMethodFromHandle(), System.Delegate.GetMethodImpl(), System.MulticastDelegate.GetMethodImpl(), System.Reflection.RuntimeMethodInfo.GetParentDefinition(), System.Reflection.Emit.DynamicScope.GetTokenFor(), System.Reflection.RuntimeMethodInfo.InternalGetCurrentMethod(), System.Reflection.RuntimeMethodInfo.MakeGenericMethod(), and System.Reflection.RuntimeModule.ResolveMethod().