Terraria: System.RuntimeType.IsAssignableFrom
IsAssignableFrom() [1/4]
override bool System.RuntimeType.IsAssignableFrom ([NotNullWhen(true)] Type c) inline
Definition at line 3652 of file RuntimeType.cs.
    {
        if ((object)c == null)
        {
            return false;
        }
        if ((object)c == this)
        {
            return true;
        }
        if (c.UnderlyingSystemType is RuntimeType type)
        {
            return RuntimeTypeHandle.CanCastTo(type, this);
        }
        if (c is TypeBuilder)
        {
            if (c.IsSubclassOf(this))
            {
                return true;
            }
            if (base.IsInterface)
            {
                return c.ImplementInterface(this);
            }
            if (IsGenericParameter)
            {
                Type[] genericParameterConstraints = GetGenericParameterConstraints();
                for (int i = 0; i < genericParameterConstraints.Length; i++)
                {
                    if (!genericParameterConstraints[i].IsAssignableFrom(c))
                    {
                        return false;
                    }
                }
                return true;
            }
        }
        return false;
    }
References System.RuntimeTypeHandle.CanCastTo(), System.Type.ImplementInterface(), System.Type.IsSubclassOf(), System.type, and System.Type.UnderlyingSystemType.