Terraria: System.IO.Enumeration.FileSystemName.TranslateWin32Expression
TranslateWin32Expression()
static string System.IO.Enumeration.FileSystemName.TranslateWin32Expression (string? expression) inline static
Definition at line 11 of file FileSystemName.cs.
    {
        if (string.IsNullOrEmpty(expression) || expression == "*" || expression == "*.*")
        {
            return "*";
        }
        bool flag = false;
        Span<char> initialBuffer = stackalloc char[32];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        int length = expression.Length;
        for (int i = 0; i < length; i++)
        {
            char c = expression[i];
            switch (c)
            {
            case '.':
                flag = true;
                if (i >= 1 && i == length - 1 && expression[i - 1] == '*')
                {
                    valueStringBuilder[valueStringBuilder.Length - 1] = '<';
                }
                else if (i < length - 1 && (expression[i + 1] == '?' || expression[i + 1] == '*'))
                {
                    valueStringBuilder.Append('"');
                }
                else
                {
                    valueStringBuilder.Append('.');
                }
                break;
            case '?':
                flag = true;
                valueStringBuilder.Append('>');
                break;
            default:
                valueStringBuilder.Append(c);
                break;
            }
        }
        if (!flag)
        {
            return expression;
        }
        return valueStringBuilder.ToString();
    }
References System.Text.ValueStringBuilder.Append(), System.length, and System.Text.ValueStringBuilder.ToString().
Referenced by System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs().