Terraria: System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.ClassLayoutTableReader
ClassLayoutTableReader()
System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.ClassLayoutTableReader (int numberOfRows, bool declaredSorted, int typeDefTableRowRefSize, MemoryBlock containingBlock, int containingBlockOffset) inline package
Definition at line 21 of file ClassLayoutTableReader.cs.
    {
        NumberOfRows = numberOfRows;
        _IsTypeDefTableRowRefSizeSmall = typeDefTableRowRefSize == 2;
        _PackagingSizeOffset = 0;
        _ClassSizeOffset = _PackagingSizeOffset + 2;
        _ParentOffset = _ClassSizeOffset + 4;
        RowSize = _ParentOffset + typeDefTableRowRefSize;
        Block = containingBlock.GetMemoryBlockAt(containingBlockOffset, RowSize * numberOfRows);
        if (!declaredSorted && !CheckSorted())
        {
            Throw.TableNotSorted(TableIndex.ClassLayout);
        }
    }
References System.Reflection.Metadata.Ecma335.ClassLayoutTableReader._ClassSizeOffset, System.Reflection.Metadata.Ecma335.ClassLayoutTableReader._IsTypeDefTableRowRefSizeSmall, System.Reflection.Metadata.Ecma335.ClassLayoutTableReader._PackagingSizeOffset, System.Reflection.Metadata.Ecma335.ClassLayoutTableReader._ParentOffset, System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.Block, System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.CheckSorted(), System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.RowSize, and System.Reflection.Throw.TableNotSorted().