Terraria: RemoteServer.ClientReadCallBack
ClientReadCallBack()
void RemoteServer.ClientReadCallBack (object state, int length) inline
     {
         try
         {
             if (!Netplay.Disconnect)
             {
                 if (length == 0)
                 {
                     Netplay.Disconnect = true;
                     Main.statusText = Language.GetTextValue("Net.LostConnection");
                 }
                 else if (Main.ignoreErrors)
                 {
                     try
                     {
                         NetMessage.ReceiveBytes(ReadBuffer, length);
                     }
                     catch
                     {
                     }
                 }
                 else
                 {
                     NetMessage.ReceiveBytes(ReadBuffer, length);
                 }
             }
             IsReading = false;
         }
         catch (Exception value)
         {
             try
             {
                 using StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", append: true);
                 streamWriter.WriteLine(DateTime.Now);
                 streamWriter.WriteLine(value);
                 streamWriter.WriteLine("");
             }
             catch
             {
             }
             Netplay.Disconnect = true;
         }
     }
References Netplay.Disconnect, Language.GetTextValue(), Main.ignoreErrors, IsReading, ReadBuffer, NetMessage.ReceiveBytes(), and Main.statusText.
Referenced by Netplay.InnerClientLoop().