Terraria: System.Net.ContextAwareResult.CaptureOrComplete
CaptureOrComplete() [2/2]
bool System.Net.ContextAwareResult.CaptureOrComplete (ref ExecutionContext cachedContext, bool returnContext) inline private
Definition at line 87 of file ContextAwareResult.cs.
    {
        bool flag = base.AsyncCallback != null || (_flags & StateFlags.CaptureContext) != 0;
        if ((_flags & StateFlags.CaptureIdentity) != 0 && !base.InternalPeekCompleted && !flag)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "starting identity capture", "CaptureOrComplete");
            }
            SafeCaptureIdentity();
        }
        if (flag && !base.InternalPeekCompleted)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "starting capture", "CaptureOrComplete");
            }
            if (cachedContext == null)
            {
                cachedContext = ExecutionContext.Capture();
            }
            if (cachedContext != null)
            {
                if (!returnContext)
                {
                    _context = cachedContext;
                    cachedContext = null;
                }
                else
                {
                    _context = cachedContext;
                }
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"_context:{_context}", "CaptureOrComplete");
            }
        }
        else
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "Skipping capture", "CaptureOrComplete");
            }
            cachedContext = null;
        }
        if (base.CompletedSynchronously)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "Completing synchronously", "CaptureOrComplete");
            }
            base.Complete(IntPtr.Zero);
            return true;
        }
        return false;
    }
References System.Net.ContextAwareResult._context, System.Net.ContextAwareResult._flags, System.Threading.ExecutionContext.Capture(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.ContextAwareResult.SafeCaptureIdentity(), and System.IntPtr.Zero.