Terraria: System.Net.ContextAwareResult.Complete
Complete() [2/2]
override void System.Net.ContextAwareResult.Complete (IntPtr userToken) inline protected virtual
Reimplemented from System.Net.LazyAsyncResult.
Definition at line 145 of file ContextAwareResult.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"_context(set):{_context != null} userToken:{userToken}", "Complete");
        }
        if ((_flags & StateFlags.PostBlockStarted) == 0)
        {
            base.Complete(userToken);
        }
        else
        {
            if (base.CompletedSynchronously)
            {
                return;
            }
            ExecutionContext context = _context;
            if (userToken != IntPtr.Zero || context == null)
            {
                base.Complete(userToken);
                return;
            }
            ExecutionContext.Run(context, delegate(object s)
            {
                ((ContextAwareResult)s).CompleteCallback();
            }, this);
        }
    }
References System.Net.ContextAwareResult.ContextAwareResult(), System.Net.ContextAwareResult._context, System.Net.ContextAwareResult._flags, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Threading.ExecutionContext.Run(), System.s, and System.IntPtr.Zero.