Terraria: System.Net.NetworkInformation.TeredoHelper.UnsafeNotifyStableUnicastIpAddressTable
UnsafeNotifyStableUnicastIpAddressTable()
static unsafe bool System.Net.NetworkInformation.TeredoHelper.UnsafeNotifyStableUnicastIpAddressTable (Action< object > callback, object state) inline static
Definition at line 27 of file TeredoHelper.cs.
    {
        TeredoHelper teredoHelper = new TeredoHelper(callback, state);
        try
        {
            SafeFreeMibTable table;
            uint num = global::Interop.IpHlpApi.NotifyStableUnicastIpAddressTable(AddressFamily.Unspecified, out table, (delegate* unmanaged<IntPtr, IntPtr, void>)(delegate*<IntPtr, IntPtr, void>)(&OnStabilized), GCHandle.ToIntPtr(teredoHelper._gcHandle), out teredoHelper._cancelHandle);
            table.Dispose();
            switch (num)
            {
            case 997u:
                teredoHelper = null;
                return false;
            default:
                throw new Win32Exception((int)num);
            case 0u:
                return true;
            }
        }
        finally
        {
            teredoHelper?.Dispose();
        }
    }
References System.Net.NetworkInformation.TeredoHelper.TeredoHelper(), System.Net.NetworkInformation.TeredoHelper._cancelHandle, System.Net.NetworkInformation.TeredoHelper._gcHandle, System.Net.NetworkInformation.TeredoHelper.Dispose(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.NetworkInformation.TeredoHelper.OnStabilized(), System.state, and System.Runtime.InteropServices.GCHandle.ToIntPtr().
Referenced by System.Net.NetworkInformation.SystemIPGlobalProperties.GetUnicastAddressesAsync().