Terraria: System.Net.NetworkInformation.TeredoHelper.OnStabilized
OnStabilized()
static void System.Net.NetworkInformation.TeredoHelper.OnStabilized (IntPtr context, IntPtr table) inline static private
Definition at line 62 of file TeredoHelper.cs.
    {
        global::Interop.IpHlpApi.FreeMibTable(table);
        TeredoHelper teredoHelper = (TeredoHelper)GCHandle.FromIntPtr(context).Target;
        if (teredoHelper._runCallbackCalled)
        {
            return;
        }
        lock (teredoHelper)
        {
            if (!teredoHelper._runCallbackCalled)
            {
                teredoHelper._runCallbackCalled = true;
                ThreadPool.QueueUserWorkItem(delegate(object o)
                {
                    TeredoHelper teredoHelper2 = (TeredoHelper)o;
                    teredoHelper2.Dispose();
                    teredoHelper2._callback(teredoHelper2._state);
                }, teredoHelper);
            }
        }
    }
References System.Net.NetworkInformation.TeredoHelper.TeredoHelper(), System.Net.NetworkInformation.TeredoHelper._callback, System.Net.NetworkInformation.TeredoHelper._runCallbackCalled, System.Net.NetworkInformation.TeredoHelper._state, System.Net.NetworkInformation.TeredoHelper.Dispose(), System.Runtime.InteropServices.GCHandle.FromIntPtr(), and System.Threading.ThreadPool.QueueUserWorkItem().
Referenced by System.Net.NetworkInformation.TeredoHelper.UnsafeNotifyStableUnicastIpAddressTable().