Terraria: System.Net.NetworkInformation.TeredoHelper.Dispose
Dispose()
void System.Net.NetworkInformation.TeredoHelper.Dispose () inline private
Definition at line 52 of file TeredoHelper.cs.
    {
        _cancelHandle?.Dispose();
        if (_gcHandle.IsAllocated)
        {
            _gcHandle.Free();
        }
    }
References System.Net.NetworkInformation.TeredoHelper._cancelHandle, System.Net.NetworkInformation.TeredoHelper._gcHandle, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Runtime.InteropServices.GCHandle.Free(), and System.Runtime.InteropServices.GCHandle.IsAllocated.
Referenced by System.Net.NetworkInformation.TeredoHelper.OnStabilized(), and System.Net.NetworkInformation.TeredoHelper.UnsafeNotifyStableUnicastIpAddressTable().