Terraria: System.Net.FtpDataStream.BeginRead
BeginRead() [2/2]
override IAsyncResult System.Net.FtpDataStream.BeginRead (byte[] buffer, int offset, int size, AsyncCallback callback, object state) inline
Definition at line 240 of file FtpDataStream.cs.
    {
        CheckError();
        LazyAsyncResult lazyAsyncResult = new LazyAsyncResult(this, state, callback);
        try
        {
            _networkStream.BeginRead(buffer, offset, size, AsyncReadCallback, lazyAsyncResult);
            return lazyAsyncResult;
        }
        catch
        {
            CheckError();
            throw;
        }
    }
References System.Net.FtpDataStream._networkStream, System.Net.FtpDataStream.AsyncReadCallback(), System.Net.Sockets.NetworkStream.BeginRead(), System.buffer, System.Net.FtpDataStream.CheckError(), System.offset, and System.state.