Terraria: System.Net.FtpDataStream.Read
Read() [1/2]
override int System.Net.FtpDataStream.Read (byte[] buffer, int offset, int size) inline
Definition at line 177 of file FtpDataStream.cs.
    {
        CheckError();
        int num;
        try
        {
            num = _networkStream.Read(buffer, offset, size);
        }
        catch
        {
            CheckError();
            throw;
        }
        if (num == 0)
        {
            _isFullyRead = true;
            Close();
        }
        return num;
    }
References System.Net.FtpDataStream._isFullyRead, System.Net.FtpDataStream._networkStream, System.buffer, System.Net.FtpDataStream.CheckError(), System.IO.Stream.Close(), System.offset, and System.Net.Sockets.NetworkStream.Read().