Terraria: System.Net.FtpDataStream.CloseEx
CloseEx()
void ICloseEx. System.Net.FtpDataStream.CloseEx (CloseExState closeState) inline private
Implements System.Net.ICloseEx.
Definition at line 107 of file FtpDataStream.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"state = {closeState}", "CloseEx");
        }
        lock (this)
        {
            if (_closing)
            {
                return;
            }
            _closing = true;
            _writeable = false;
            _readable = false;
        }
        try
        {
            try
            {
                if ((closeState & CloseExState.Abort) == 0)
                {
                    _networkStream.Close(-1);
                }
                else
                {
                    _networkStream.Close(0);
                }
            }
            finally
            {
                _request.DataStreamClosed(closeState);
            }
        }
        catch (Exception ex)
        {
            bool flag = true;
            if (ex is WebException { Response: FtpWebResponse response } && !_isFullyRead && response.StatusCode == FtpStatusCode.ConnectionClosed)
            {
                flag = false;
            }
            if (flag && (closeState & CloseExState.Silent) == 0)
            {
                throw;
            }
        }
    }
References System.Net.FtpDataStream._closing, System.Net.FtpDataStream._isFullyRead, System.Net.FtpDataStream._networkStream, System.Net.FtpDataStream._readable, System.Net.FtpDataStream._request, System.Net.FtpDataStream._writeable, System.Net.Sockets.NetworkStream.Close(), System.Net.FtpWebRequest.DataStreamClosed(), System.Net.NetEventSource.Info(), and System.Net.NetEventSource.Log.