Terraria: System.Net.FtpDataStream.AsyncReadCallback
AsyncReadCallback()
void System.Net.FtpDataStream.AsyncReadCallback (IAsyncResult ar) inline private
Definition at line 212 of file FtpDataStream.cs.
    {
        LazyAsyncResult lazyAsyncResult = (LazyAsyncResult)ar.AsyncState;
        try
        {
            try
            {
                int num = _networkStream.EndRead(ar);
                if (num == 0)
                {
                    _isFullyRead = true;
                    Close();
                }
                lazyAsyncResult.InvokeCallback(num);
            }
            catch (Exception result)
            {
                if (!lazyAsyncResult.IsCompleted)
                {
                    lazyAsyncResult.InvokeCallback(result);
                }
            }
        }
        catch
        {
        }
    }
References System.Net.FtpDataStream._isFullyRead, System.Net.FtpDataStream._networkStream, System.IAsyncResult.AsyncState, System.IO.Stream.Close(), System.Net.Sockets.NetworkStream.EndRead(), System.Net.LazyAsyncResult.InvokeCallback(), and System.Net.LazyAsyncResult.IsCompleted.
Referenced by System.Net.FtpDataStream.BeginRead().