Terraria: Item.Prefix
Prefix()
bool Item.Prefix (int prefixWeWant) inline
     {
         if (!WorldGen.gen && Main.rand == null)
         {
             Main.rand = new UnifiedRandom();
         }
         if (prefixWeWant == 0)
         {
             return false;
         }
         if (!CanHavePrefixes())
         {
             return false;
         }
         UnifiedRandom unifiedRandom = (WorldGen.gen ? WorldGen.genRand : Main.rand);
         int rolledPrefix = prefixWeWant;
         float dmg = 1f;
         float kb = 1f;
         float spd = 1f;
         float size = 1f;
         float shtspd = 1f;
         float mcst = 1f;
         int crt = 0;
         bool flag = true;
         while (flag)
         {
             flag = false;
             if (rolledPrefix == -1 && unifiedRandom.Next(4) == 0)
             {
                 rolledPrefix = 0;
             }
             if (prefixWeWant < -1)
             {
                 rolledPrefix = -1;
             }
             if ((rolledPrefix == -1 || rolledPrefix == -2 || rolledPrefix == -3) && !RollAPrefix(unifiedRandom, ref rolledPrefix))
             {
                 return false;
             }
             switch (prefixWeWant)
             {
             case -3:
                 return true;
             case -1:
                 if (PrefixID.Sets.ReducedNaturalChance[rolledPrefix] && unifiedRandom.Next(3) != 0)
                 {
                     rolledPrefix = 0;
                 }
                 break;
             }
             if (!TryGetPrefixStatMultipliersForItem(rolledPrefix, out dmg, out kb, out spd, out size, out shtspd, out mcst, out crt))
             {
                 flag = true;
                 rolledPrefix = -1;
             }
             if (prefixWeWant == -2 && rolledPrefix == 0)
             {
                 rolledPrefix = -1;
                 flag = true;
             }
         }
         damage = (int)Math.Round((float)damage * dmg);
         useAnimation = (int)Math.Round((float)useAnimation * spd);
         useTime = (int)Math.Round((float)useTime * spd);
         reuseDelay = (int)Math.Round((float)reuseDelay * spd);
         mana = (int)Math.Round((float)mana * mcst);
         knockBack *= kb;
         scale *= size;
         shootSpeed *= shtspd;
         crit += crt;
         float num = 1f * dmg * (2f - spd) * (2f - mcst) * size * kb * shtspd * (1f + (float)crt * 0.02f);
         if (rolledPrefix == 62 || rolledPrefix == 69 || rolledPrefix == 73 || rolledPrefix == 77)
         {
             num *= 1.05f;
         }
         if (rolledPrefix == 63 || rolledPrefix == 70 || rolledPrefix == 74 || rolledPrefix == 78 || rolledPrefix == 67)
         {
             num *= 1.1f;
         }
         if (rolledPrefix == 64 || rolledPrefix == 71 || rolledPrefix == 75 || rolledPrefix == 79 || rolledPrefix == 66)
         {
             num *= 1.15f;
         }
         if (rolledPrefix == 65 || rolledPrefix == 72 || rolledPrefix == 76 || rolledPrefix == 80 || rolledPrefix == 68)
         {
             num *= 1.2f;
         }
         if ((double)num >= 1.2)
         {
             rare += 2;
         }
         else if ((double)num >= 1.05)
         {
             rare++;
         }
         else if ((double)num <= 0.8)
         {
             rare -= 2;
         }
         else if ((double)num <= 0.95)
         {
             rare--;
         }
         if (rare > -11)
         {
             if (rare < -1)
             {
                 rare = -1;
             }
             if (rare > 11)
             {
                 rare = 11;
             }
         }
         num *= num;
         value = (int)((float)value * num);
         prefix = (byte)rolledPrefix;
         return true;
     }
References CanHavePrefixes(), crit, damage, WorldGen.gen, WorldGen.genRand, knockBack, mana, UnifiedRandom.Next(), prefix, Main.rand, rare, PrefixID.Sets.ReducedNaturalChance, reuseDelay, RollAPrefix(), scale, shootSpeed, TryGetPrefixStatMultipliersForItem(), useAnimation, useTime, and value.
Referenced by WorldGen.AddBuriedChest(), Main.CraftItem(), Player.Deserialize(), DeserializeFrom(), Main.DrawInventory(), TileDrawing.DrawSpecialTilesLegacy(), MessageBuffer.GetData(), ItemSlot.GetGamepadInstructions(), ItemSlot.HandleShopSlot(), Player.KillMe(), WorldGen.KillTile(), WorldFile.LoadChests(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), NewItem(), ItemSlot.OverrideHover(), ItemTagHandler.Parse(), ItemSlot.PickItemMovementAction(), WorldGen.PrefixItemFromOptions(), TEDisplayDoll.ReadExtraData(), TEFoodPlatter.ReadExtraData(), TEHatRack.ReadExtraData(), TEItemFrame.ReadExtraData(), TEWeaponsRack.ReadExtraData(), TEDisplayDoll.ReadItem(), TEHatRack.ReadItem(), Refresh(), UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty(), Player.TryDroppingSingleItem(), TEFoodPlatter.TryPlacing(), TEItemFrame.TryPlacing(), and TEWeaponsRack.TryPlacing().