Terraria: Item.DropCache
DropCache()
static void Item.DropCache (IEntitySource reason, Vector2 pos, Vector2 spread, int t, bool stopCaching = true) inline static
     {
         if (cachedItemSpawnsByType[t] == -1)
         {
             return;
         }
         int num = cachedItemSpawnsByType[t];
         cachedItemSpawnsByType[t] = (stopCaching ? (-1) : 0);
         Item item = new Item();
         item.SetDefaults(t);
         while (num > 0)
         {
             int num2 = item.maxStack;
             if (num < num2)
             {
                 num2 = num;
             }
             NewItem(reason, (int)pos.X, (int)pos.Y, (int)spread.X, (int)spread.Y, t, num2);
             num -= num2;
         }
     }
References cachedItemSpawnsByType, maxStack, NewItem(), and SetDefaults().
Referenced by Wiring.MassWireOperationInner().