Terraria: Item.GetAlpha
GetAlpha()
Color Item.GetAlpha (Color newColor) inline
     {
         if (ItemID.Sets.BossBag[type])
         {
             return Color.Lerp(newColor, Color.White, 0.4f);
         }
         switch (type)
         {
         case 1326:
         case 5335:
             return Color.Lerp(newColor, Color.White, 0.75f);
         case 5043:
             return new Color(255, 255, 255, newColor.A - alpha);
         case 3065:
         case 4956:
             return new Color(255, 255, 255, newColor.A - alpha);
         case 75:
         case 3858:
             return new Color(255, 255, 255, 255);
         case 119:
         case 120:
         case 121:
         case 122:
         case 217:
         case 218:
         case 219:
         case 220:
             return new Color(255, 255, 255, 255);
         case 501:
             return new Color(200, 200, 200, 50);
         case 757:
         case 1306:
         case 3456:
         case 3457:
         case 3458:
         case 3459:
             return new Color(255, 255, 255, 200);
         case 520:
         case 521:
         case 522:
         case 547:
         case 548:
         case 549:
         case 575:
         case 1332:
         case 3453:
         case 3454:
         case 3455:
         case 3580:
             return new Color(255, 255, 255, 50);
         case 58:
         case 184:
         case 1734:
         case 1735:
         case 1867:
         case 1868:
             return new Color(200, 200, 200, 200);
         case 1572:
             return new Color(200, 200, 255, 125);
         case 787:
             return new Color(255, 255, 255, 175);
         case 1826:
             return new Color(255, 255, 255, 200);
         case 1508:
             return new Color(200, 200, 200, 0);
         case 502:
             return new Color(255, 255, 255, 150);
         case 51:
             return new Color(255, 255, 255, 0);
         case 1260:
             return new Color(255, 255, 255, 175);
         case 1446:
         case 1506:
         case 1507:
         case 1543:
         case 1544:
         case 1545:
             return new Color(newColor.R, newColor.G, newColor.B, Main.gFade);
         case 198:
         case 199:
         case 200:
         case 201:
         case 202:
         case 203:
         case 3764:
         case 3765:
         case 3766:
         case 3767:
         case 3768:
         case 3769:
         case 4258:
         case 4259:
             return Color.White;
         case 2763:
         case 2764:
         case 2765:
         case 2782:
         case 2783:
         case 2784:
         case 2785:
         case 2786:
         case 3522:
             return new Color(250, 250, 250, 255 - alpha);
         case 3191:
             return new Color(250, 250, 250, 200);
         case 3822:
             return Color.Lerp(Color.White, newColor, 0.5f) * ((255f - (float)alpha) / 255f);
         case 4143:
             return Color.Lerp(Color.White, newColor, 0f) * ((255f - (float)alpha) / 255f);
         case 4354:
         case 4377:
         case 4378:
         case 4389:
         case 5127:
         case 5128:
         {
             Color color = default(Color);
             color = type switch
             {
                 4377 => new Color(50, 255, 50, 200),
                 4378 => new Color(50, 200, 255, 255),
                 4389 => new Color(255, 50, 125, 200),
                 5127 => new Color(150, 50, 250, 200),
                 5128 => new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB, 200),
                 _ => new Color(255, 150, 150, 200),
             };
             if (newColor.R > color.R)
             {
                 color.R = newColor.R;
             }
             if (newColor.G > color.G)
             {
                 color.G = newColor.G;
             }
             if (newColor.B > color.B)
             {
                 color.B = newColor.B;
             }
             if (newColor.A > color.A)
             {
                 color.A = newColor.A;
             }
             return color;
         }
         default:
         {
             float num = (float)(255 - alpha) / 255f;
             int r = (int)((float)(int)newColor.R * num);
             int g = (int)((float)(int)newColor.G * num);
             int b = (int)((float)(int)newColor.B * num);
             int num2 = newColor.A - alpha;
             if (num2 < 0)
             {
                 num2 = 0;
             }
             if (num2 > 255)
             {
                 num2 = 255;
             }
             return new Color(r, g, b, num2);
         }
         }
     }
References alpha, ItemID.Sets.BossBag, Color, color, Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.gFade, and type.
Referenced by ItemSlot.Draw(), Main.DrawInterface_40_InteractItemIcon(), Main.DrawItem(), ItemSlot.DrawItemIcon(), PlayerDrawLayers.DrawPlayer_27_HeldItem(), PlayerDrawLayers.DrawPlayer_30_BladedGlove(), and Main.GUIChatDrawInner().