Terraria: Item.CanRollPrefix
CanRollPrefix()
bool Item.CanRollPrefix (int prefix) inline
     {
         if (!CanHavePrefixes())
         {
             return false;
         }
         int[] rollablePrefixes = GetRollablePrefixes();
         if (rollablePrefixes == null)
         {
             return false;
         }
         for (int i = 0; i < rollablePrefixes.Length; i++)
         {
             if (rollablePrefixes[i] == prefix)
             {
                 return true;
             }
         }
         return false;
     }
References CanHavePrefixes(), GetRollablePrefixes(), and prefix.
Referenced by CanApplyPrefix(), and FixAgainstExploit().