Terraria: Item.TurnToAir
TurnToAir()
void Item.TurnToAir (bool fullReset = false) inline
References dye, mountType, netID, prefix, SetDefaults(), shoot, stack, and type.
Referenced by DD2Event.ClearAllDD2EnergyCrystalsInChests(), Player.ClearPlayerTempInfo(), MinecartDiggerHelper.ConsumeATrackItem(), Player.ConsumeItem(), DeserializeFrom(), Player.DropItems(), Player.FixLoadedData_EliminiateDuplicateAccessories(), Player.PickAmmo(), Player.PlaceThing_ItemInExtractinator(), Player.PurgeDD2EnergyCrystals(), Player.QuickBuff(), Player.QuickHeal(), Player.QuickMana(), ItemSorting.RefillItemStack(), CreativeUI.Reset(), CreativeUI.SacrificeItem(), ItemSlot.SellOrTrash(), ItemSorting.SortCoins(), Player.TryDroppingSingleItem(), Main.TryFreeingElderSlime(), and Projectile.UseGasTrapInChest().