Terraria: Item.CombineWithNearbyItems
CombineWithNearbyItems()
void Item.CombineWithNearbyItems (int myItemIndex) inline private
     {
         if (!CanCombineStackInWorld() || stack >= maxStack)
         {
             return;
         }
         for (int i = myItemIndex + 1; i < 400; i++)
         {
             Item item = Main.item[i];
             if (!item.active || item.type != type || item.shimmered != shimmered || item.stack <= 0 || item.playerIndexTheItemIsReservedFor != playerIndexTheItemIsReservedFor)
             {
                 continue;
             }
             float num = Math.Abs(position.X + (float)(width / 2) - (item.position.X + (float)(item.width / 2))) + Math.Abs(position.Y + (float)(height / 2) - (item.position.Y + (float)(item.height / 2)));
             int num2 = 30;
             if ((double)numberOfNewItems > 40.0)
             {
                 num2 *= 2;
             }
             if ((double)numberOfNewItems > 80.0)
             {
                 num2 *= 2;
             }
             if ((double)numberOfNewItems > 120.0)
             {
                 num2 *= 2;
             }
             if ((double)numberOfNewItems > 160.0)
             {
                 num2 *= 2;
             }
             if ((double)numberOfNewItems > 200.0)
             {
                 num2 *= 2;
             }
             if ((double)numberOfNewItems > 240.0)
             {
                 num2 *= 2;
             }
             if (num < (float)num2)
             {
                 position = (position + item.position) / 2f;
                 velocity = (velocity + item.velocity) / 2f;
                 int num3 = item.stack;
                 if (num3 > maxStack - stack)
                 {
                     num3 = maxStack - stack;
                 }
                 item.stack -= num3;
                 stack += num3;
                 if (item.stack <= 0)
                 {
                     item.SetDefaults();
                     item.active = false;
                 }
                 if (Main.netMode != 0 && playerIndexTheItemIsReservedFor == Main.myPlayer)
                 {
                     NetMessage.SendData(21, -1, -1, null, myItemIndex);
                     NetMessage.SendData(21, -1, -1, null, i);
                 }
             }
         }
     }
References Entity.active, CanCombineStackInWorld(), Entity.height, Main.item, maxStack, Main.myPlayer, Main.netMode, numberOfNewItems, playerIndexTheItemIsReservedFor, Entity.position, NetMessage.SendData(), SetDefaults(), shimmered, stack, type, Entity.velocity, and Entity.width.
Referenced by TryCombiningIntoNearbyItems().