Terraria: Item.SetDefaults1
SetDefaults1()
void Item.SetDefaults1 (int type) inline
References accessory, alpha, ammo, AmmoID.Arrow, autoReuse, axe, backSlot, balloonSlot, bodySlot, buffTime, buffType, AmmoID.Bullet, buyPrice(), channel, AmmoID.Coin, Color, color, CommonMaxStack, consumable, createTile, createWall, crit, damage, AmmoID.Dart, defense, ItemVariants.DisabledBossSummonVariant, dungeonPrice, eclipsePrice, faceSlot, AmmoID.FallenStar, flame, AmmoID.Flare, AmmoID.Gel, glowMask, Player.hairColor, hammer, handOffSlot, handOnSlot, hasVanityEffects, headSlot, healLife, healMana, Entity.height, hellPrice, holdStyle, SoundID.Item1, SoundID.Item10, SoundID.Item11, SoundID.Item12, SoundID.Item13, SoundID.Item15, SoundID.Item157, SoundID.Item16, SoundID.Item2, SoundID.Item20, SoundID.Item21, SoundID.Item23, SoundID.Item25, SoundID.Item28, SoundID.Item29, SoundID.Item3, SoundID.Item31, SoundID.Item34, SoundID.Item36, SoundID.Item38, SoundID.Item4, SoundID.Item41, SoundID.Item43, SoundID.Item5, SoundID.Item6, SoundID.Item61, SoundID.Item63, SoundID.Item64, SoundID.Item8, SoundID.Item9, knockBack, legSlot, lifeRegen, magic, makeNPC, MakeUsableWithChlorophyteExtractinator(), mana, maxStack, mech, melee, Main.myPlayer, neckSlot, noMelee, notAmmo, noUseGraphic, noWet, Player.pantsColor, pick, placeStyle, Main.player, potion, ranged, rare, ItemVariants.RebalancedVariant, reuseDelay, AmmoID.Rocket, AmmoID.Sand, scale, sellPrice(), SetShopValues(), shadowOrbPrice, shieldSlot, Player.shirtColor, shoeSlot, shoot, shootsEveryUse, shootSpeed, AmmoID.Snowball, AmmoID.Solution, ItemVariants.StrongerVariant, tileBoost, tileWand, type, useAmmo, useAnimation, UseSound, useStyle, useTime, useTurn, value, vanity, Variant, waistSlot, ItemVariants.WeakerVariant, Entity.width, and wingSlot.
Referenced by SetDefaults(), and SetDefaults4().