Terraria: Item.BannerToNPC
BannerToNPC()
static int Item.BannerToNPC (int i) inline static
     {
         return i switch
         {
             1 => 102,
             2 => 250,
             3 => 257,
             4 => 69,
             5 => 157,
             6 => 77,
             7 => 49,
             8 => 74,
             9 => 163,
             10 => 241,
             11 => 242,
             12 => 239,
             13 => 39,
             14 => 46,
             15 => 120,
             16 => 85,
             17 => 109,
             18 => 47,
             19 => 57,
             20 => 67,
             21 => 173,
             22 => 179,
             23 => 83,
             24 => 62,
             25 => 2,
             26 => 177,
             27 => 6,
             28 => 84,
             29 => 161,
             30 => 181,
             31 => 182,
             32 => 224,
             33 => 226,
             34 => 162,
             35 => 259,
             36 => 256,
             37 => 122,
             38 => 27,
             39 => 29,
             40 => 26,
             41 => 73,
             42 => 28,
             43 => 55,
             44 => 48,
             45 => 60,
             46 => 174,
             47 => 42,
             48 => 169,
             49 => 206,
             50 => 24,
             51 => 63,
             52 => 236,
             53 => 199,
             54 => 43,
             55 => 23,
             56 => 205,
             57 => 78,
             58 => 258,
             59 => 252,
             60 => 170,
             61 => 58,
             62 => 212,
             63 => 75,
             64 => 223,
             65 => 253,
             66 => 65,
             67 => 21,
             68 => 32,
             69 => 1,
             70 => 185,
             71 => 164,
             72 => 254,
             73 => 166,
             74 => 153,
             75 => 141,
             76 => 225,
             77 => 86,
             78 => 158,
             79 => 61,
             80 => 196,
             81 => 104,
             82 => 155,
             83 => 98,
             84 => 10,
             85 => 82,
             86 => 87,
             87 => 3,
             88 => 175,
             89 => 197,
             91 => 273,
             92 => 379,
             93 => 438,
             95 => 287,
             96 => 101,
             97 => 217,
             98 => 168,
             99 => 81,
             100 => 94,
             101 => 183,
             102 => 34,
             103 => 218,
             104 => 7,
             105 => 285,
             106 => 52,
             107 => 71,
             108 => 288,
             109 => 350,
             110 => 347,
             111 => 251,
             112 => 352,
             113 => 316,
             114 => 93,
             115 => 289,
             116 => 152,
             117 => 342,
             118 => 111,
             120 => 315,
             121 => 277,
             122 => 329,
             123 => 304,
             124 => 150,
             125 => 243,
             126 => 147,
             127 => 268,
             128 => 137,
             129 => 138,
             130 => 51,
             132 => 351,
             133 => 219,
             134 => 151,
             135 => 59,
             136 => 381,
             137 => 388,
             138 => 386,
             139 => 389,
             140 => 385,
             141 => 383,
             142 => 382,
             143 => 390,
             144 => 387,
             145 => 144,
             146 => 16,
             147 => 283,
             148 => 348,
             149 => 290,
             150 => 148,
             151 => -4,
             152 => 330,
             153 => 140,
             154 => 341,
             156 => 281,
             157 => 244,
             158 => 301,
             160 => 172,
             161 => 269,
             162 => 305,
             163 => 391,
             164 => 110,
             165 => 293,
             166 => 291,
             167 => 121,
             168 => 56,
             169 => 145,
             170 => 143,
             171 => 184,
             172 => 204,
             173 => 326,
             174 => 221,
             175 => 292,
             176 => 53,
             177 => 45,
             178 => 44,
             179 => 167,
             180 => 380,
             184 => 343,
             185 => 338,
             90 => -6,
             119 => -3,
             131 => -10,
             155 => -7,
             159 => -8,
             183 => -9,
             186 => 471,
             187 => 498,
             188 => 496,
             189 => 494,
             190 => 462,
             191 => 461,
             192 => 468,
             193 => 477,
             195 => 469,
             196 => 460,
             197 => 466,
             198 => 467,
             199 => 463,
             201 => 480,
             202 => 481,
             203 => 483,
             204 => 482,
             205 => 489,
             206 => 490,
             207 => 513,
             208 => 510,
             209 => 581,
             210 => 580,
             211 => 524,
             212 => 529,
             213 => 533,
             214 => 532,
             215 => 530,
             216 => 411,
             217 => 402,
             218 => 407,
             219 => 409,
             220 => 406,
             221 => 405,
             222 => 418,
             223 => 417,
             224 => 412,
             225 => 416,
             226 => 415,
             227 => 419,
             228 => 424,
             229 => 421,
             230 => 420,
             231 => 423,
             232 => 428,
             233 => 426,
             234 => 427,
             235 => 429,
             236 => 425,
             237 => 216,
             238 => 214,
             239 => 213,
             240 => 215,
             241 => 520,
             242 => 156,
             243 => 64,
             244 => 103,
             245 => 79,
             246 => 80,
             247 => 31,
             248 => 154,
             249 => 537,
             250 => 220,
             251 => 541,
             252 => 542,
             253 => 543,
             254 => 544,
             255 => 545,
             256 => 546,
             257 => 555,
             258 => 552,
             259 => 566,
             260 => 570,
             261 => 574,
             262 => 572,
             263 => 568,
             264 => 558,
             265 => 561,
             266 => 578,
             267 => 536,
             268 => 586,
             269 => 587,
             270 => 619,
             271 => 621,
             272 => 620,
             273 => 618,
             274 => 628,
             275 => 624,
             276 => 631,
             277 => 630,
             278 => 635,
             279 => 634,
             280 => 582,
             281 => 464,
             282 => 465,
             283 => 470,
             284 => 473,
             285 => 474,
             286 => 475,
             287 => 176,
             288 => 133,
             289 => 676,
             _ => 0,
         };
     }
Referenced by NPC.CountKillForBannersAndDropThem(), Main.DrawInfoAccs(), and Main.MouseText_DrawBuffTooltip().