Terraria: Item.FindDecraftAmount
FindDecraftAmount()
int Item.FindDecraftAmount () inline private
     {
         int decraftingRecipeIndex = ShimmerTransforms.GetDecraftingRecipeIndex(GetShimmerEquivalentType());
         if (decraftingRecipeIndex < 0)
         {
             return -1;
         }
         return stack / Main.recipe[decraftingRecipeIndex].createItem.stack;
     }
References Recipe.createItem, ShimmerTransforms.GetDecraftingRecipeIndex(), GetShimmerEquivalentType(), Main.recipe, and stack.
Referenced by CanShimmer(), and GetShimmered().