Terraria: Item.netDefaults
netDefaults()
void Item.netDefaults (int type) inline
     {
         if (type < 0)
         {
             switch (type)
             {
             case -1:
                 SetDefaults(3521);
                 break;
             case -2:
                 SetDefaults(3520);
                 break;
             case -3:
                 SetDefaults(3519);
                 break;
             case -4:
                 SetDefaults(3518);
                 break;
             case -5:
                 SetDefaults(3517);
                 break;
             case -6:
                 SetDefaults(3516);
                 break;
             case -7:
                 SetDefaults(3515);
                 break;
             case -8:
                 SetDefaults(3514);
                 break;
             case -9:
                 SetDefaults(3513);
                 break;
             case -10:
                 SetDefaults(3512);
                 break;
             case -11:
                 SetDefaults(3511);
                 break;
             case -12:
                 SetDefaults(3510);
                 break;
             case -13:
                 SetDefaults(3509);
                 break;
             case -14:
                 SetDefaults(3508);
                 break;
             case -15:
                 SetDefaults(3507);
                 break;
             case -16:
                 SetDefaults(3506);
                 break;
             case -17:
                 SetDefaults(3505);
                 break;
             case -18:
                 SetDefaults(3504);
                 break;
             case -19:
                 SetDefaults(3764);
                 break;
             case -20:
                 SetDefaults(3765);
                 break;
             case -21:
                 SetDefaults(3766);
                 break;
             case -22:
                 SetDefaults(3767);
                 break;
             case -23:
                 SetDefaults(3768);
                 break;
             case -24:
                 SetDefaults(3769);
                 break;
             case -25:
                 SetDefaults(3503);
                 break;
             case -26:
                 SetDefaults(3502);
                 break;
             case -27:
                 SetDefaults(3501);
                 break;
             case -28:
                 SetDefaults(3500);
                 break;
             case -29:
                 SetDefaults(3499);
                 break;
             case -30:
                 SetDefaults(3498);
                 break;
             case -31:
                 SetDefaults(3497);
                 break;
             case -32:
                 SetDefaults(3496);
                 break;
             case -33:
                 SetDefaults(3495);
                 break;
             case -34:
                 SetDefaults(3494);
                 break;
             case -35:
                 SetDefaults(3493);
                 break;
             case -36:
                 SetDefaults(3492);
                 break;
             case -37:
                 SetDefaults(3491);
                 break;
             case -38:
                 SetDefaults(3490);
                 break;
             case -39:
                 SetDefaults(3489);
                 break;
             case -40:
                 SetDefaults(3488);
                 break;
             case -41:
                 SetDefaults(3487);
                 break;
             case -42:
                 SetDefaults(3486);
                 break;
             case -43:
                 SetDefaults(3485);
                 break;
             case -44:
                 SetDefaults(3484);
                 break;
             case -45:
                 SetDefaults(3483);
                 break;
             case -46:
                 SetDefaults(3482);
                 break;
             case -47:
                 SetDefaults(3481);
                 break;
             case -48:
                 SetDefaults(3480);
                 break;
             }
         }
         else
         {
             SetDefaults(type);
         }
     }
References SetDefaults(), and type.
Referenced by Player.Deserialize(), DeserializeFrom(), TileDrawing.DrawSpecialTilesLegacy(), MessageBuffer.GetData(), Main.GUIChatDrawInner(), ItemSlot.HandleShopSlot(), Player.KillMe(), WorldGen.KillTile(), WorldFile.LoadChests(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Main.MouseText_DrawItemTooltip_GetLinesInfo(), ItemTagHandler.Parse(), TEDisplayDoll.ReadExtraData(), TEFoodPlatter.ReadExtraData(), TEHatRack.ReadExtraData(), TEItemFrame.ReadExtraData(), TEWeaponsRack.ReadExtraData(), Refresh(), SetDefaults(), Chest.SetupShop(), ItemSorting.SetupWhiteLists(), Player.TryDroppingSingleItem(), TEFoodPlatter.TryPlacing(), TEItemFrame.TryPlacing(), and TEWeaponsRack.TryPlacing().