Terraria: Item.RollAPrefix
RollAPrefix()
bool Item.RollAPrefix (UnifiedRandom random, ref int rolledPrefix) inline private
     {
         int[] rollablePrefixes = GetRollablePrefixes();
         if (rollablePrefixes == null)
         {
             return false;
         }
         rolledPrefix = rollablePrefixes[random.Next(rollablePrefixes.Length)];
         return true;
     }
References GetRollablePrefixes(), and UnifiedRandom.Next().
Referenced by Prefix().