Terraria: Item.AffixName
AffixName()
string Item.AffixName () inline
     {
         if (prefix < 0 || prefix >= Lang.prefix.Length)
         {
             return Name;
         }
         string text = Lang.prefix[prefix].Value;
         if (text == "")
         {
             return Name;
         }
         if (text.StartsWith("("))
         {
             return Name + " " + text;
         }
         return text + " " + Name;
     }
References Name, prefix, Lang.prefix, and LocalizedText.Value.
Referenced by Main.DrawMouseOver(), Main.GUIHotbarDrawInner(), PopupText.NewText(), and ItemTagHandler.Parse().