Terraria: Item.UpdateItem
UpdateItem()
void Item.UpdateItem (int i) inline
     {
         whoAmI = i;
         if (Main.timeItemSlotCannotBeReusedFor[i] > 0)
         {
             if (Main.netMode == 2)
             {
                 Main.timeItemSlotCannotBeReusedFor[i]--;
                 return;
             }
             Main.timeItemSlotCannotBeReusedFor[i] = 0;
         }
         if (!active)
         {
             return;
         }
         if (instanced)
         {
             if (Main.netMode == 2)
             {
                 active = false;
                 return;
             }
             keepTime = 6000;
             ownTime = 0;
             noGrabDelay = 0;
             playerIndexTheItemIsReservedFor = Main.myPlayer;
         }
         if (Main.netMode == 0)
         {
             playerIndexTheItemIsReservedFor = Main.myPlayer;
         }
         float gravity = 0.1f;
         float maxFallSpeed = 7f;
         if (Main.netMode == 1)
         {
             int num = (int)(position.X + (float)(width / 2)) / 16;
             int num2 = (int)(position.Y + (float)(height / 2)) / 16;
             if (num >= 0 && num2 >= 0 && num < Main.maxTilesX && num2 < Main.maxTilesY && Main.tile[num, num2] == null)
             {
                 gravity = 0f;
                 velocity.X = 0f;
                 velocity.Y = 0f;
             }
         }
         Vector2 wetVelocity = velocity * 0.5f;
         if (shimmerWet)
         {
             gravity = 0.065f;
             maxFallSpeed = 4f;
             wetVelocity = velocity * 0.375f;
         }
         else if (honeyWet)
         {
             gravity = 0.05f;
             maxFallSpeed = 3f;
             wetVelocity = velocity * 0.25f;
         }
         else if (wet)
         {
             gravity = 0.08f;
             maxFallSpeed = 5f;
         }
         if (ownTime > 0)
         {
             ownTime--;
         }
         else
         {
             ownIgnore = -1;
         }
         if (keepTime > 0)
         {
             keepTime--;
         }
         if (!beingGrabbed)
         {
             if (shimmered)
             {
                 if (Main.rand.Next(30) == 0)
                 {
                     int num3 = Dust.NewDust(position, width, height, 309);
                     Main.dust[num3].position.X += Main.rand.Next(-8, 5);
                     Main.dust[num3].position.Y += Main.rand.Next(-8, 5);
                     Main.dust[num3].scale *= 1.1f;
                     Main.dust[num3].velocity *= 0.3f;
                     switch (Main.rand.Next(6))
                     {
                     case 0:
                         Main.dust[num3].color = new Color(255, 255, 210);
                         break;
                     case 1:
                         Main.dust[num3].color = new Color(190, 245, 255);
                         break;
                     case 2:
                         Main.dust[num3].color = new Color(255, 150, 255);
                         break;
                     default:
                         Main.dust[num3].color = new Color(190, 175, 255);
                         break;
                     }
                 }
                 Lighting.AddLight(base.Center, (1f - shimmerTime) * 0.8f, (1f - shimmerTime) * 0.8f, (1f - shimmerTime) * 0.8f);
                 gravity = 0f;
                 if (shimmerWet)
                 {
                     if (velocity.Y > -4f)
                     {
                         velocity.Y -= 0.05f;
                     }
                 }
                 else
                 {
                     int num4 = 2;
                     int num5 = (int)(base.Center.X / 16f);
                     int num6 = (int)(base.Center.Y / 16f);
                     bool flag = false;
                     for (int j = num6; j < num6 + num4; j++)
                     {
                         if (WorldGen.InWorld(num5, j) && Main.tile[num5, j] != null && Main.tile[num5, j].shimmer() && Main.tile[num5, j].liquid > 0)
{
                             flag = true;
                             break;
                         }
                     }
                     if (flag)
                     {
                         if (velocity.Y > -4f)
{
                             velocity.Y -= 0.05f;
                         }
                     }
                     else
                     {
                         velocity.Y *= 0.9f;
                     }
                 }
             }
             if (shimmerWet && !shimmered)
             {
                 Shimmering();
             }
             else if (shimmerTime > 0f)
             {
                 shimmerTime -= 0.01f;
                 if (shimmerTime < 0f)
                 {
                     shimmerTime = 0f;
                 }
             }
             if (shimmerTime == 0f)
             {
                 TryCombiningIntoNearbyItems(i);
             }
             if (timeLeftInWhichTheItemCannotBeTakenByEnemies > 0)
             {
                 timeLeftInWhichTheItemCannotBeTakenByEnemies--;
             }
             if (timeLeftInWhichTheItemCannotBeTakenByEnemies == 0 && Main.netMode != 2 && playerIndexTheItemIsReservedFor == Main.myPlayer)
             {
                 GetPickedUpByMonsters_Special(i);
                 if (Main.expertMode && IsACoin)
                 {
                     GetPickedUpByMonsters_Money(i);
                 }
             }
             MoveInWorld(gravity, maxFallSpeed, ref wetVelocity, i);
             if (lavaWet)
             {
                 CheckLavaDeath(i);
             }
             DespawnIfMeetingConditions(i);
         }
         else
         {
             beingGrabbed = false;
         }
         UpdateItem_VisualEffects();
         if (timeSinceItemSpawned < 2147483547)
         {
             int num7 = ItemID.Sets.ItemSpawnDecaySpeed[type];
             timeSinceItemSpawned += num7;
         }
         if (Main.netMode == 2 && playerIndexTheItemIsReservedFor != Main.myPlayer)
         {
             timeSinceTheItemHasBeenReservedForSomeone++;
             if (timeSinceTheItemHasBeenReservedForSomeone >= 300)
             {
                 timeSinceTheItemHasBeenReservedForSomeone = 0;
                 NetMessage.SendData(39, playerIndexTheItemIsReservedFor, -1, null, i);
                 playerIndexTheItemIsReservedFor = 255;
             }
         }
         if (wet)
         {
             position += wetVelocity;
         }
         else
         {
             position += velocity;
         }
         if (noGrabDelay > 0)
         {
             noGrabDelay--;
         }
     }
References Entity.active, Lighting.AddLight(), beingGrabbed, CheckLavaDeath(), Color, Dust.color, DespawnIfMeetingConditions(), Main.dust, Main.expertMode, GetPickedUpByMonsters_Money(), GetPickedUpByMonsters_Special(), Entity.height, Entity.honeyWet, instanced, WorldGen.InWorld(), IsACoin, ItemID.Sets.ItemSpawnDecaySpeed, keepTime, Entity.lavaWet, Tile.liquid, Main.maxTilesX, Main.maxTilesY, MoveInWorld(), Main.myPlayer, Main.netMode, Dust.NewDust(), UnifiedRandom.Next(), noGrabDelay, ownIgnore, ownTime, playerIndexTheItemIsReservedFor, Dust.position, Entity.position, Main.rand, Dust.scale, NetMessage.SendData(), Tile.shimmer(), shimmered, Shimmering(), shimmerTime, Entity.shimmerWet, Main.tile, Main.timeItemSlotCannotBeReusedFor, timeLeftInWhichTheItemCannotBeTakenByEnemies, timeSinceItemSpawned, timeSinceTheItemHasBeenReservedForSomeone, TryCombiningIntoNearbyItems(), type, UpdateItem_VisualEffects(), Dust.velocity, Entity.velocity, Entity.wet, Entity.whoAmI, and Entity.width.
Referenced by Main.DoUpdateInWorld().