Terraria: Item.NewItem
NewItem() [1/3]
static int Item.NewItem (IEntitySource source, int X, int Y, int Width, int Height, int Type, int Stack = 1, bool noBroadcast = false, int pfix = 0, bool noGrabDelay = false, bool reverseLookup = false) inline static
     {
         if (WorldGen.gen)
         {
             return 0;
         }
         if (Main.rand == null)
         {
             Main.rand = new UnifiedRandom();
         }
         if (Main.tenthAnniversaryWorld)
         {
             if (Type == 58)
             {
                 Type = Main.rand.NextFromList(new short[3] { 1734, 1867, 58 });
             }
             if (Type == 184)
             {
                 Type = Main.rand.NextFromList(new short[3] { 1735, 1868, 184 });
             }
         }
         if (Main.halloween)
         {
             if (Type == 58)
             {
                 Type = 1734;
             }
             if (Type == 184)
             {
                 Type = 1735;
             }
         }
         if (Main.xMas)
         {
             if (Type == 58)
             {
                 Type = 1867;
             }
             if (Type == 184)
             {
                 Type = 1868;
             }
         }
         if (Type > 0 && cachedItemSpawnsByType[Type] != -1)
         {
             cachedItemSpawnsByType[Type] += Stack;
             return 400;
         }
         Main.item[400] = new Item();
         int num = 400;
         if (Main.netMode != 1)
         {
             num = PickAnItemSlotToSpawnItemOn(reverseLookup, num);
         }
         Main.timeItemSlotCannotBeReusedFor[num] = 0;
         Main.item[num] = new Item();
         Item item = Main.item[num];
         item.SetDefaults(Type);
         item.Prefix(pfix);
         item.stack = Stack;
         item.position.X = X + Width / 2 - item.width / 2;
         item.position.Y = Y + Height / 2 - item.height / 2;
         item.wet = Collision.WetCollision(item.position, item.width, item.height);
         item.velocity.X = (float)Main.rand.Next(-30, 31) * 0.1f;
         item.velocity.Y = (float)Main.rand.Next(-40, -15) * 0.1f;
         if (Type == 859 || Type == 4743)
         {
             item.velocity *= 0f;
         }
         if (Type == 520 || Type == 521 || (item.type >= 0 && ItemID.Sets.NebulaPickup[item.type]))
         {
             item.velocity.X = (float)Main.rand.Next(-30, 31) * 0.1f;
             item.velocity.Y = (float)Main.rand.Next(-30, 31) * 0.1f;
         }
         item.active = true;
         item.timeSinceItemSpawned = ItemID.Sets.OverflowProtectionTimeOffset[item.type];
         numberOfNewItems++;
         if (ItemSlot.Options.HighlightNewItems && item.type >= 0 && !ItemID.Sets.NeverAppearsAsNewInInventory[item.type])
         {
             item.newAndShiny = true;
         }
         if (Main.netMode == 2 && !noBroadcast)
         {
             NetMessage.SendData(21, -1, -1, null, num, noGrabDelay.ToInt());
         }
         else if (Main.netMode == 0)
         {
             item.playerIndexTheItemIsReservedFor = Main.myPlayer;
         }
         return num;
     }
References Entity.active, cachedItemSpawnsByType, WorldGen.gen, Main.halloween, Entity.height, ItemSlot.Options.HighlightNewItems, Main.item, Main.myPlayer, ItemID.Sets.NebulaPickup, Main.netMode, ItemID.Sets.NeverAppearsAsNewInInventory, newAndShiny, UnifiedRandom.Next(), noGrabDelay, numberOfNewItems, ItemID.Sets.OverflowProtectionTimeOffset, PickAnItemSlotToSpawnItemOn(), playerIndexTheItemIsReservedFor, Entity.position, Prefix(), Main.rand, NetMessage.SendData(), SetDefaults(), stack, Main.tenthAnniversaryWorld, Main.timeItemSlotCannotBeReusedFor, timeSinceItemSpawned, type, Entity.velocity, Entity.wet, Collision.WetCollision(), Entity.width, X, Main.xMas, and Y.