Terraria: Item.GetDrawHitbox
GetDrawHitbox()
static Rectangle Item.GetDrawHitbox (int type, Player user) inline static
     {
         if (Main.dedServ)
         {
             return Rectangle.Empty;
         }
         Main.instance.LoadItem(type);
         if (ItemID.Sets.IsFood[type])
         {
             return TextureAssets.Item[type].Frame(1, 3, 0, 1);
         }
         switch (type)
         {
         case 75:
             return TextureAssets.Item[type].Frame(1, 8);
         case 520:
         case 521:
         case 547:
         case 548:
         case 549:
         case 575:
         case 3453:
         case 3454:
         case 3455:
         case 3580:
         case 3581:
         case 4068:
         case 4069:
         case 4070:
             return TextureAssets.Item[type].Frame(1, 4);
         default:
             return TextureAssets.Item[type].Frame();
         }
     }
References Main.dedServ, Main.instance, ItemID.Sets.IsFood, TextureAssets.Item, Main.LoadItem(), and type.
Referenced by Main.DrawInterface_40_InteractItemIcon(), Main.DrawMouseOver(), Player.ItemCheck(), and Player.PlayerFrame().