Terraria: Item.FixAgainstExploit
FixAgainstExploit()
void Item.FixAgainstExploit () inline
     {
         if (ItemID.Sets.ItemsThatShouldNotBeInInventory[type])
         {
             SetDefaults();
             return;
         }
         if (stack > maxStack)
         {
             stack = maxStack;
         }
         if (prefix != 0 && !CanRollPrefix(prefix))
         {
             ResetPrefix();
         }
     }
References CanRollPrefix(), ItemID.Sets.ItemsThatShouldNotBeInInventory, maxStack, prefix, ResetPrefix(), SetDefaults(), stack, and type.
Referenced by TEDisplayDoll.FixLoadedData(), TEFoodPlatter.FixLoadedData(), TEHatRack.FixLoadedData(), TEItemFrame.FixLoadedData(), TEWeaponsRack.FixLoadedData(), Chest.FixLoadedData(), EquipmentLoadout.FixLoadedData(), and Player.FixLoadedData_Items().