Terraria: Item.NewItem
NewItem() [3/3]
static int Item.NewItem (IEntitySource source, Vector2 pos, Vector2 randomBox, int Type, int Stack = 1, bool noBroadcast = false, int prefixGiven = 0, bool noGrabDelay = false, bool reverseLookup = false) inline static
References noGrabDelay.
Referenced by Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Projectile.AI_192_JuminoAnimation(), NPC.AI_87_BigMimic_ShootItem(), Player.ApplyNPCOnHitEffects(), Lang.BartenderHelpText(), NPC.CatchNPC(), WorldGen.Check1x2(), WorldGen.Check1x2Top(), WorldGen.Check1xX(), WorldGen.Check2x1(), WorldGen.Check2x2(), WorldGen.Check2x2Style(), WorldGen.Check2x3Wall(), WorldGen.Check2x5(), WorldGen.Check2xX(), WorldGen.Check3x1(), WorldGen.Check3x2(), WorldGen.Check3x2Wall(), WorldGen.Check3x3(), WorldGen.Check3x3Wall(), WorldGen.Check3x4(), WorldGen.Check3x5(), WorldGen.Check3x6(), WorldGen.Check4x2(), WorldGen.Check4x3Wall(), WorldGen.Check5x4(), WorldGen.Check6x3(), WorldGen.Check6x4Wall(), WorldGen.CheckBanner(), WorldGen.CheckCannon(), WorldGen.CheckChand(), WorldGen.CheckChest(), WorldGen.CheckGnome(), WorldGen.CheckJunglePlant(), WorldGen.CheckMan(), WorldGen.CheckMB(), WorldGen.CheckOrb(), WorldGen.CheckSign(), WorldGen.CheckSunflower(), WorldGen.CheckSuper(), WorldGen.CheckTallGate(), WorldGen.CheckTrapDoor(), WorldGen.CheckWeaponsRack(), WorldGen.CheckWoman(), WorldGen.CheckXmasTree(), NPC.CountKillForBannersAndDropThem(), Projectile.Damage(), NPC.DoDeathEvents(), NPC.DoDeathEvents_DropBossPotionsAndHearts(), DropCache(), Player.DropCoins(), WorldGen.DropDoorItem(), Projectile.DropGeodeGems(), TEFoodPlatter.DropItem(), TEItemFrame.DropItem(), TEWeaponsRack.DropItem(), Player.dropItemCheck(), CommonCode.DropItemForEachInteractingPlayerOnThePlayer(), Player.DropItemFromExtractinator(), CommonCode.DropItemFromNPC(), NPC.DropItemInstanced(), CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0(), Player.DropSelectedItem(), DD2Event.DropStarterCrystals(), WorldGen.dropXmasTree(), TEDisplayDoll.Framing_CheckTile(), TEHatRack.Framing_CheckTile(), TETeleportationPylon.Framing_CheckTile(), TEWeaponsRack.Framing_CheckTile(), Player.GetAnglerReward_Bait(), Player.GetAnglerReward_Decoration(), Player.GetAnglerReward_MainReward(), Player.GetAnglerReward_Money(), MessageBuffer.GetData(), Player.GetDyeTraderReward(), GetShimmered(), NPC.GetShimmered(), Main.GUIChatDrawInner(), Player.ItemCheck_CutTiles(), Projectile.Kill(), WorldGen.KillActuator(), Player.KillMe(), WorldGen.KillTile(), WorldGen.KillTile_DropItems(), WorldGen.KillWall_DropItems(), WorldGen.KillWire(), WorldGen.KillWire2(), WorldGen.KillWire3(), WorldGen.KillWire4(), NewItem(), NPC.NPCLoot_DropCommonLifeAndMana(), NPC.NPCLoot_DropHeals(), NPC.NPCLoot_DropMoney(), Player.OpenFishingCrate(), Player.OpenGoodieBag(), Player.OpenHerbBag(), Player.OpenLegacyPresent(), Player.OpenLockBox(), Player.OpenPresent(), Player.OpenShadowLockbox(), Player.PlaceThing_PaintScrapper_LongMoss(), Player.PutItemInInventoryFromItemUsage(), Player.QuickSpawnItem(), WorldGen.ShakeTree(), WorldGen.SpawnThingsFromPot(), WorldGen.ToggleGemLock(), Player.TorchAttack(), Player.TryDroppingSingleItem(), TEFoodPlatter.TryPlacing(), TEItemFrame.TryPlacing(), TEWeaponsRack.TryPlacing(), Player.TryToPoop(), Player.Update(), and Projectile.UseGasTrapInChest().