Terraria: Item.CanShimmer
CanShimmer()
bool Item.CanShimmer () inline
     {
         int shimmerEquivalentType = GetShimmerEquivalentType();
         if (ShimmerTransforms.IsItemTransformLocked(shimmerEquivalentType))
         {
             return false;
         }
         bool flag = false;
         if ((type == 1326 || type == 779 || type == 3031 || type == 5364) && NPC.downedMoonlord)
         {
             flag = true;
         }
         if (type == 4986 && !NPC.unlockedSlimeRainbowSpawn)
         {
             flag = true;
         }
         if (type == 3461 || createTile == 139)
         {
             flag = true;
         }
         if (!flag && ItemID.Sets.ShimmerTransformToItem[shimmerEquivalentType] <= 0 && FindDecraftAmount() <= 0 && !ItemID.Sets.CommonCoin[type])
         {
             return makeNPC > 0;
         }
         return true;
     }
References ItemID.Sets.CommonCoin, createTile, NPC.downedMoonlord, FindDecraftAmount(), GetShimmerEquivalentType(), ShimmerTransforms.IsItemTransformLocked(), makeNPC, ItemID.Sets.ShimmerTransformToItem, type, and NPC.unlockedSlimeRainbowSpawn.
Referenced by Shimmering().