Terraria: Item.BannerToItem
BannerToItem()
static int Item.BannerToItem (int banner) inline static
     {
         int num = 0;
         if (banner == 289)
         {
             return 5352;
         }
         if (banner >= 276)
         {
             return 4965 + banner - 276;
         }
         if (banner >= 274)
         {
             return 4687 + banner - 274;
         }
         if (banner == 273)
         {
             return 4602;
         }
         if (banner >= 267)
         {
             return 4541 + banner - 267;
         }
         if (banner >= 257)
         {
             return 3837 + banner - 257;
         }
         if (banner >= 252)
         {
             return 3789 + banner - 252;
         }
         if (banner == 251)
         {
             return 3780;
         }
         if (banner >= 249)
         {
             return 3593 + banner - 249;
         }
         if (banner >= 186)
         {
             return 3390 + banner - 186;
         }
         if (banner >= 88)
         {
             return 2897 + banner - 88;
         }
         return 1615 + banner - 1;
     }
Referenced by Player.ApplyDamageToNPC(), NPC.CountKillForBannersAndDropThem(), Projectile.Damage(), CommonEnemyUICollectionInfoProvider.GetKillCountNeeded(), Player.ProcessHitAgainstNPC(), SceneMetrics.ScanAndExportToMain(), and Player.Update_NPCCollision().