Terraria: Item.UpdateItem_VisualEffects
UpdateItem_VisualEffects()
void Item.UpdateItem_VisualEffects () inline private
     {
         if (type == 5043)
         {
             float num = (float)Main.rand.Next(90, 111) * 0.01f;
             num *= (Main.essScale + 0.5f) / 2f;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.25f * num, 0.25f * num, 0.25f * num);
         }
         else if (type == 3191)
         {
             float num2 = (float)Main.rand.Next(90, 111) * 0.01f;
             num2 *= (Main.essScale + 0.5f) / 2f;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.3f * num2, 0.1f * num2, 0.25f * num2);
         }
         else if (type == 520 || type == 3454)
         {
             float num3 = (float)Main.rand.Next(90, 111) * 0.01f;
             num3 *= Main.essScale;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * num3, 0.1f * num3, 0.25f * num3);
         }
         else if (type == 521 || type == 3455)
         {
             float num4 = (float)Main.rand.Next(90, 111) * 0.01f;
             num4 *= Main.essScale;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.25f * num4, 0.1f * num4, 0.5f * num4);
         }
         else if (type == 547 || type == 3453)
         {
             float num5 = (float)Main.rand.Next(90, 111) * 0.01f;
             num5 *= Main.essScale;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * num5, 0.3f * num5, 0.05f * num5);
         }
         else if (type == 548)
         {
             float num6 = (float)Main.rand.Next(90, 111) * 0.01f;
             num6 *= Main.essScale;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.1f * num6, 0.1f * num6, 0.6f * num6);
         }
         else if (type == 575)
         {
             float num7 = (float)Main.rand.Next(90, 111) * 0.01f;
             num7 *= Main.essScale;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.1f * num7, 0.3f * num7, 0.5f * num7);
         }
         else if (type == 549)
         {
             float num8 = (float)Main.rand.Next(90, 111) * 0.01f;
             num8 *= Main.essScale;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.1f * num8, 0.5f * num8, 0.2f * num8);
         }
         else if (type == 58 || type == 1734 || type == 1867)
         {
             float num9 = (float)Main.rand.Next(90, 111) * 0.01f;
             num9 *= Main.essScale * 0.5f;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * num9, 0.1f * num9, 0.1f * num9);
         }
         else if (type == 184 || type == 1735 || type == 1868 || type == 4143)
         {
             float num10 = (float)Main.rand.Next(90, 111) * 0.01f;
             num10 *= Main.essScale * 0.5f;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.1f * num10, 0.1f * num10, 0.5f * num10);
         }
         else if (type == 522)
         {
             float num11 = (float)Main.rand.Next(90, 111) * 0.01f;
             num11 *= Main.essScale * 0.2f;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * num11, 1f * num11, 0.1f * num11);
         }
         else if (type == 1332)
         {
             float num12 = (float)Main.rand.Next(90, 111) * 0.01f;
             num12 *= Main.essScale * 0.2f;
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f * num12, 1f * num12, 0.1f * num12);
         }
         else if (type == 3456)
         {
             Lighting.AddLight(base.Center, new Vector3(0.2f, 0.4f, 0.5f) * Main.essScale);
         }
         else if (type == 3457)
         {
             Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.5f) * Main.essScale);
         }
         else if (type == 3458)
         {
             Lighting.AddLight(base.Center, new Vector3(0.5f, 0.4f, 0.2f) * Main.essScale);
         }
         else if (type == 3459)
         {
             Lighting.AddLight(base.Center, new Vector3(0.2f, 0.2f, 0.5f) * Main.essScale);
         }
         else if (type == 501)
         {
             if (Main.rand.Next(6) == 0)
             {
                 int num13 = Dust.NewDust(position, width, height, 55, 0f, 0f, 200, color);
                 Main.dust[num13].velocity *= 0.3f;
                 Main.dust[num13].scale *= 0.5f;
             }
         }
         else if (type == 3822)
         {
             Lighting.AddLight(base.Center, 0.1f, 0.3f, 0.1f);
         }
         else if (type == 1970)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0f, 0.75f);
         }
         else if (type == 1972)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0f, 0.75f);
         }
         else if (type == 1971)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0.75f, 0f);
         }
         else if (type == 1973)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0.75f, 0f);
         }
         else if (type == 1974)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0f, 0f);
         }
         else if (type == 1975)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0.75f, 0.75f);
         }
         else if (type == 1976)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0.375f, 0f);
         }
         else if (type == 2679)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0f, 0.6f);
         }
         else if (type == 2687)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0f, 0.6f);
         }
         else if (type == 2689)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0.6f, 0f);
         }
         else if (type == 2683)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0.6f, 0f);
         }
         else if (type == 2685)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0f, 0f);
         }
         else if (type == 2681)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0.6f, 0.6f);
         }
         else if (type == 2677)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0.375f, 0f);
         }
         else if (type == 105)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.95f, 0.8f);
             }
         }
         else if (type == 2701)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.7f, 0.65f, 0.55f);
         }
         else if (createTile == 4)
         {
             int torchID = placeStyle;
             if ((!wet && ItemID.Sets.Torches[type]) || ItemID.Sets.WaterTorches[type])
             {
                 Lighting.AddLight(base.Center, torchID);
             }
         }
         else if (type == 3114)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0f, 1f);
             }
         }
         else if (type == 1245)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.5f, 0f);
             }
         }
         else if (type == 433)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * Main.demonTorch + 1f * (1f - Main.demonTorch), 0.3f, 1f * Main.demonTorch + 0.5f * (1f - Main.demonTorch));
             }
         }
         else if (type == 523)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.85f, 1.2f, 0.7f);
         }
         else if (type == 974)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0.85f, 1.4f);
             }
         }
         else if (type == 1333)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1.25f, 1.25f, 0.7f);
         }
         else if (type == 4383)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1.4f, 0.85f, 0.55f);
             }
         }
         else if (type == 5293)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.25f, 0.65f, 1f);
             }
         }
         else if (type == 5353)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.81f, 0.72f, 1f);
             }
         }
         else if (type == 4384)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.25f, 1.3f, 0.8f);
         }
         else if (type == 3045)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), (float)Main.DiscoR / 255f, (float)Main.DiscoG / 255f, (float)Main.DiscoB / 255f);
         }
         else if (type == 3004)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.95f, 0.65f, 1.3f);
         }
         else if (type == 2274)
         {
             float r = 0.75f;
             float g = 1.3499999f;
             float b = 1.5f;
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), r, g, b);
             }
         }
         else if (type >= 427 && type <= 432)
         {
             if (!wet)
             {
                 float r2 = 0f;
                 float g2 = 0f;
                 float b2 = 0f;
                 int num14 = type - 426;
                 if (num14 == 1)
                 {
                     r2 = 0.1f;
                     g2 = 0.2f;
                     b2 = 1.1f;
                 }
                 if (num14 == 2)
                 {
                     r2 = 1f;
                     g2 = 0.1f;
                     b2 = 0.1f;
                 }
                 if (num14 == 3)
                 {
                     r2 = 0f;
                     g2 = 1f;
                     b2 = 0.1f;
                 }
                 if (num14 == 4)
                 {
                     r2 = 0.9f;
                     g2 = 0f;
                     b2 = 0.9f;
                 }
                 if (num14 == 5)
                 {
                     r2 = 1.3f;
                     g2 = 1.3f;
                     b2 = 1.3f;
                 }
                 if (num14 == 6)
                 {
                     r2 = 0.9f;
                     g2 = 0.9f;
                     b2 = 0f;
                 }
                 Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), r2, g2, b2);
             }
         }
         else if (type == 2777 || type == 2778 || type == 2779 || type == 2780 || type == 2781 || type == 2760 || type == 2761 || type == 2762 || type == 3524)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.4f, 0.16f, 0.36f);
         }
         else if (type == 2772 || type == 2773 || type == 2774 || type == 2775 || type == 2776 || type == 2757 || type == 2758 || type == 2759 || type == 3523)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0.36f, 0.4f);
         }
         else if (type == 2782 || type == 2783 || type == 2784 || type == 2785 || type == 2786 || type == 2763 || type == 2764 || type == 2765 || type == 3522)
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f, 0.25f, 0.05f);
         }
         else if (type == 3462 || type == 3463 || type == 3464 || type == 3465 || type == 3466 || type == 3381 || type == 3382 || type == 3383 || type == 3525)
         {
             Lighting.AddLight(base.Center, 0.3f, 0.3f, 0.2f);
         }
         else if (type == 41)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.75f, 0.55f);
             }
         }
         else if (type == 988)
         {
             if (!wet)
             {
                 Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.35f, 0.65f, 1f);
             }
         }
         else if (type == 1326)
         {
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 1f, 0.1f, 0.8f);
         }
         else if (type == 5335)
         {
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.85f, 0.1f, 0.8f);
         }
         else if (type >= 5140 && type <= 5146)
         {
             float num15 = 1f;
             float num16 = 1f;
             float num17 = 1f;
             switch (type)
             {
             case 5140:
                 num15 *= 0.9f;
                 num16 *= 0.8f;
                 num17 *= 0.1f;
                 break;
             case 5141:
                 num15 *= 0.25f;
                 num16 *= 0.1f;
                 num17 *= 0f;
                 break;
             case 5142:
                 num15 *= 0f;
                 num16 *= 0.25f;
                 num17 *= 0f;
                 break;
             case 5143:
                 num15 *= 0f;
                 num16 *= 0.16f;
                 num17 *= 0.34f;
                 break;
             case 5144:
                 num15 *= 0.3f;
                 num16 *= 0f;
                 num17 *= 0.17f;
                 break;
             case 5145:
                 num15 *= 0.3f;
                 num16 *= 0f;
                 num17 *= 0.35f;
                 break;
             case 5146:
                 num15 *= (float)Main.DiscoR / 255f;
                 num16 *= (float)Main.DiscoG / 255f;
                 num17 *= (float)Main.DiscoB / 255f;
                 break;
             }
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), num15, num16, num17);
         }
         else if (type == 282)
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.7f, 1f, 0.8f);
         }
         else if (type == 286)
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.7f, 0.8f, 1f);
         }
         else if (type == 3112)
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.6f, 0.85f);
         }
         else if (type == 4776)
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.7f, 0f, 1f);
         }
         else if (type == 3002)
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1.05f, 0.95f, 0.55f);
         }
         else if (type == 331)
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.55f, 0.75f, 0.6f);
         }
         else if (type == 183)
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.15f, 0.45f, 0.9f);
         }
         else if (type == 75)
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.8f, 0.7f, 0.1f);
             if (timeSinceItemSpawned % 12 == 0)
             {
                 Dust dust = Dust.NewDustPerfect(base.Center + new Vector2(0f, (float)height * 0.2f) + Main.rand.NextVector2CircularEdge(width, (float)height * 0.6f) * (0.3f + Main.rand.NextFloat() * 0.5f), 228, new Vector2(0f, (0f - Main.rand.NextFloat()) * 0.3f - 1.5f), 127);
                 dust.scale = 0.5f;
                 dust.fadeIn = 1.1f;
                 dust.noGravity = true;
                 dust.noLight = true;
             }
         }
         else if (ItemID.Sets.BossBag[type])
         {
             Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.4f, 0.4f, 0.4f);
             if (timeSinceItemSpawned % 12 == 0)
             {
                 Dust dust2 = Dust.NewDustPerfect(base.Center + new Vector2(0f, (float)height * -0.1f) + Main.rand.NextVector2CircularEdge((float)width * 0.6f, (float)height * 0.6f) * (0.3f + Main.rand.NextFloat() * 0.5f), 279, new Vector2(0f, (0f - Main.rand.NextFloat()) * 0.3f - 1.5f), 127);
                 dust2.scale = 0.5f;
                 dust2.fadeIn = 1.1f;
                 dust2.noGravity = true;
                 dust2.noLight = true;
                 dust2.alpha = 0;
             }
         }
     }
References Lighting.AddLight(), Dust.alpha, ItemID.Sets.BossBag, color, createTile, Main.demonTorch, Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.dust, Main.essScale, Dust.fadeIn, Entity.height, Dust.NewDust(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, placeStyle, Entity.position, Main.rand, Dust.scale, timeSinceItemSpawned, ItemID.Sets.Torches, type, Dust.velocity, ItemID.Sets.WaterTorches, Entity.wet, and Entity.width.
Referenced by UpdateItem().