Terraria: Item.SetFoodDefaults
SetFoodDefaults()
void Item.SetFoodDefaults (int type) inline private
     {
         switch (type)
         {
         case 4022:
             DefaultToFood(22, 22, 207, 172800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 50));
             break;
         case 1919:
             DefaultToFood(22, 22, 207, 14400);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 25));
             break;
         case 1920:
             DefaultToFood(22, 22, 207, 14400);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 25));
             break;
         case 4011:
             DefaultToFood(22, 22, 207, 57600);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
             break;
         case 3532:
             DefaultToFood(22, 22, 207, 86400);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
             break;
         case 1911:
             DefaultToFood(22, 22, 207, 14400, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 10));
             break;
         case 4013:
             DefaultToFood(22, 22, 207, 86400);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
             break;
         case 4615:
             DefaultToFood(22, 22, 207, 57600, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 4));
             break;
         case 4027:
             DefaultToFood(22, 22, 207, 57600, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
             break;
         case 4025:
             DefaultToFood(22, 22, 207, 43200);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
             break;
         case 4029:
             DefaultToFood(22, 22, 207, 28800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4036:
             DefaultToFood(22, 22, 207, 28800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4037:
             DefaultToFood(22, 22, 207, 57600);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
             break;
         case 4015:
             DefaultToFood(22, 22, 207, 28800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 2426:
             DefaultToFood(22, 22, 206, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 75));
             break;
         case 2427:
             DefaultToFood(22, 22, 206, 28800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 25));
             break;
         case 4034:
             DefaultToFood(22, 22, 206, 50400);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 50));
             break;
         case 357:
             DefaultToFood(22, 22, 206, 28800, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 1787:
             DefaultToFood(22, 22, 206, 28800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 10));
             break;
         case 4012:
             DefaultToFood(22, 22, 206, 36000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4016:
             DefaultToFood(22, 22, 206, 50400);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4017:
             DefaultToFood(22, 22, 206, 72000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
             break;
         case 5042:
             DefaultToFood(22, 22, 206, 36000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4018:
             DefaultToFood(22, 22, 206, 57600, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4288:
             DefaultToFood(22, 22, 206, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4019:
             DefaultToFood(22, 22, 206, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4020:
             DefaultToFood(22, 22, 206, 50400);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4021:
             DefaultToFood(22, 22, 206, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4023:
             DefaultToFood(22, 22, 206, 57600);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 3195:
             DefaultToFood(22, 22, 206, 50400, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4026:
             DefaultToFood(22, 22, 206, 50400, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4028:
             DefaultToFood(22, 22, 206, 57600);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4032:
             DefaultToFood(22, 22, 206, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4035:
             DefaultToFood(22, 22, 206, 64800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2, 50));
             break;
         case 4403:
             DefaultToFood(22, 22, 206, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 2267:
             DefaultToFood(22, 22, 206, 28800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 55));
             break;
         case 4623:
             DefaultToFood(22, 22, 206, 72000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 2268:
             DefaultToFood(22, 22, 206, 36000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 75));
             break;
         case 4297:
             DefaultToFood(22, 22, 206, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 5092:
             DefaultToFood(22, 22, 206, 28800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 50));
             break;
         case 5093:
             DefaultToFood(22, 22, 206, 21600);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4009:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4614:
             DefaultToFood(22, 22, 26, 36000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4014:
             DefaultToFood(22, 22, 26, 36000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4024:
             DefaultToFood(22, 22, 26, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4030:
             DefaultToFood(22, 22, 26, 90000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1, 50));
             break;
         case 4031:
             DefaultToFood(22, 22, 26, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 969:
             DefaultToFood(12, 12, 26, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 2));
             useStyle = 9;
             break;
         case 2425:
             DefaultToFood(22, 22, 26, 28800);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 25));
             break;
         case 4282:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4283:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4617:
             DefaultToFood(22, 22, 26, 54000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4284:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4285:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4621:
             DefaultToFood(22, 22, 26, 72000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4286:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4287:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4289:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4624:
             DefaultToFood(22, 22, 26, 54000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4625:
             DefaultToFood(22, 22, 26, 90000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
             break;
         case 4290:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4291:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4616:
             DefaultToFood(22, 22, 26, 36000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4292:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 967:
             DefaultToFood(12, 12, 26, 3600);
             SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 1));
             useStyle = 9;
             break;
         case 4293:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4618:
             DefaultToFood(22, 22, 26, 36000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4619:
             DefaultToFood(22, 22, 26, 72000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4294:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4295:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4296:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4622:
             DefaultToFood(22, 22, 26, 72000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 4411:
             DefaultToFood(22, 22, 26, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4620:
             DefaultToFood(22, 22, 26, 72000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
             break;
         case 5009:
             DefaultToFood(22, 22, 26, 18000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 0, 20));
             break;
         case 5041:
             DefaultToFood(22, 22, 26, 72000, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 4033:
             DefaultToFood(22, 22, 26, 36000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 50));
             break;
         case 5275:
             DefaultToFood(22, 22, 26, 7200, useGulpSound: true);
             SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 1, 25));
             break;
         case 5277:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 5278:
             DefaultToFood(22, 22, 26, 18000);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
             break;
         case 2266:
             DefaultToFood(22, 22, 25, 14400, useGulpSound: true);
             SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 5));
             break;
         case 353:
             DefaultToFood(22, 22, 25, 7200, useGulpSound: true);
             SetShopValues(ItemRarityColor.White0, 100);
             maxStack = CommonMaxStack;
             holdStyle = 1;
             ammo = 353;
             notAmmo = true;
             break;
         case 1912:
             DefaultToHealingPotion(22, 22, 80);
             SetShopValues(ItemRarityColor.Blue1, 40);
             break;
         }
         float num = 0f;
         num = ((buffType == 207) ? (num + 12f) : ((buffType != 206) ? (num + 3f) : (num + 8f)));
         num += (float)(buffTime / 14400);
         rare = (int)(num / 4f);
     }
References ammo, buffTime, buffType, buyPrice(), CommonMaxStack, DefaultToFood(), DefaultToHealingPotion(), holdStyle, maxStack, notAmmo, rare, SetShopValues(), type, and useStyle.
Referenced by SetDefaults().