Terraria: Terraria.Projectile.StatusPlayer
StatusPlayer()
void Terraria.Projectile.StatusPlayer (int i) inline
    {
        if (Main.player[i].creativeGodMode)
        {
            return;
        }
        if (type == 119)
        {
            Main.player[i].AddBuff(324, 240);
        }
        if (type == 359)
        {
            Main.player[i].AddBuff(324, 420);
        }
        if (type == 472)
        {
            Main.player[i].AddBuff(149, Main.rand.Next(30, 150));
        }
        if (type == 961)
        {
            Main.player[i].AddBuff(47, 20);
        }
        if (type == 467)
        {
            Main.player[i].AddBuff(24, Main.rand.Next(30, 150));
        }
        if (type == 581)
        {
            if (Main.expertMode)
            {
                Main.player[i].AddBuff(164, Main.rand.Next(300, 540));
            }
            else if (Main.rand.Next(2) == 0)
            {
                Main.player[i].AddBuff(164, Main.rand.Next(360, 720));
            }
        }
        if (type == 687)
        {
            Main.player[i].AddBuff(24, 60 * Main.rand.Next(7, 11));
        }
        if (type == 258 && Main.rand.Next(2) == 0)
        {
            Main.player[i].AddBuff(24, 60 * Main.rand.Next(5, 8));
        }
        if (type == 572 && Main.rand.Next(3) != 0)
        {
            Main.player[i].AddBuff(20, Main.rand.Next(120, 240));
        }
        if (type == 276)
        {
            if (Main.expertMode)
            {
                Main.player[i].AddBuff(20, Main.rand.Next(120, 540));
            }
            else if (Main.rand.Next(2) == 0)
            {
                Main.player[i].AddBuff(20, Main.rand.Next(180, 420));
            }
        }
        if (type == 436 && Main.rand.Next(5) >= 2)
        {
            Main.player[i].AddBuff(31, 300);
        }
        if (type == 435 && Main.rand.Next(3) != 0)
        {
            Main.player[i].AddBuff(144, 300);
        }
        if (type == 682)
        {
            Main.player[i].AddBuff(196, 300);
        }
        if (type == 437)
        {
            Main.player[i].AddBuff(144, 60 * Main.rand.Next(4, 9));
        }
        if (type == 348)
        {
            if (Main.rand.Next(2) == 0)
            {
                Main.player[i].AddBuff(46, 600);
            }
            else
            {
                Main.player[i].AddBuff(46, 300);
            }
            if (Main.rand.Next(3) != 0)
            {
                if (Main.rand.Next(16) == 0)
                {
                    Main.player[i].AddBuff(47, 60);
                }
                else if (Main.rand.Next(12) == 0)
                {
                    Main.player[i].AddBuff(47, 40);
                }
                else if (Main.rand.Next(8) == 0)
                {
                    Main.player[i].AddBuff(47, 20);
                }
            }
        }
        if (type == 349)
        {
            if (Main.rand.Next(3) == 0)
            {
                Main.player[i].AddBuff(46, 600);
            }
            else if (Main.rand.Next(2) == 0)
            {
                Main.player[i].AddBuff(46, 300);
            }
        }
        if (type >= 399 && type <= 402 && !hostile)
        {
            Main.player[i].AddBuff(24, 60 * Main.rand.Next(3, 7));
        }
        if (type == 55 || type == 719)
        {
            if (Main.rand.Next(3) == 0)
            {
                Main.player[i].AddBuff(20, 600);
            }
            else if (Main.expertMode)
            {
                Main.player[i].AddBuff(20, Main.rand.Next(60, 300));
            }
        }
        if (type == 44 && Main.rand.Next(3) == 0)
        {
            Main.player[i].AddBuff(22, 900);
        }
        if (type == 293)
        {
            Main.player[i].AddBuff(80, 60 * Main.rand.Next(2, 7));
        }
        if (type == 299)
        {
            Main.player[i].AddBuff(23, 240);
        }
        if (type == 82 && Main.rand.Next(3) == 0)
        {
            Main.player[i].AddBuff(24, 420);
        }
        if (type == 285 && !hostile)
        {
            if (Main.rand.Next(3) == 0)
            {
                Main.player[i].AddBuff(31, 180);
            }
            else
            {
                Main.player[i].AddBuff(31, 60);
            }
        }
        if (type == 96 || type == 101)
        {
            if (Main.rand.Next(6) == 0)
            {
                Main.player[i].AddBuff(39, 180);
            }
            else if (Main.rand.Next(4) == 0)
            {
                Main.player[i].AddBuff(39, 180);
            }
            else if (Main.rand.Next(2) == 0)
            {
                Main.player[i].AddBuff(39, 120);
            }
        }
        else if (type == 288)
        {
            Main.player[i].AddBuff(69, 900);
        }
        else if (type == 253 && !hostile)
        {
            Main.player[i].AddBuff(324, 600);
        }
        if (type == 291 || type == 292)
        {
            Main.player[i].AddBuff(24, 60 * Main.rand.Next(8, 16));
        }
        if (type == 98)
        {
            Main.player[i].AddBuff(20, 600);
        }
        if (type == 184)
        {
            Main.player[i].AddBuff(20, 900);
        }
        if (type == 980)
        {
            Main.player[i].AddBuff(70, 300);
        }
        if (type == 290)
        {
            Main.player[i].AddBuff(32, 60 * Main.rand.Next(5, 16));
        }
        if (type == 174)
        {
            Main.player[i].AddBuff(46, 1200);
            if (!Main.player[i].frozen && Main.rand.Next(20) == 0)
            {
                Main.player[i].AddBuff(47, 90);
            }
            else if (!Main.player[i].frozen && Main.expertMode && Main.rand.Next(20) == 0)
            {
                Main.player[i].AddBuff(47, 60);
            }
        }
        if (type == 257)
        {
            Main.player[i].AddBuff(46, 2700);
            if (!Main.player[i].frozen && Main.rand.Next(5) == 0)
            {
                Main.player[i].AddBuff(47, 60);
            }
        }
        if (type == 177)
        {
            Main.player[i].AddBuff(46, 1500);
            if (!Main.player[i].frozen && Main.rand.Next(10) == 0)
            {
                Main.player[i].AddBuff(47, Main.rand.Next(30, 120));
            }
        }
        if (type == 128 && Main.rand.Next(3) == 0)
        {
            Main.player[i].AddBuff(44, 360);
        }
        if (type == 176)
        {
            if (Main.rand.Next(4) == 0)
            {
                Main.player[i].AddBuff(20, 1200);
            }
            else if (Main.rand.Next(2) == 0)
            {
                Main.player[i].AddBuff(20, 300);
            }
        }
    }
References Terraria.Player.AddBuff(), Terraria.Player.creativeGodMode, Terraria.Main.expertMode, Terraria.Player.frozen, Terraria.Projectile.hostile, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, and Terraria.Projectile.type.
Referenced by Terraria.Projectile.BombsHurtPlayers(), and Terraria.Projectile.Damage().