Terraria: Terraria.Projectile.Kill
Kill()
void Terraria.Projectile.Kill () inline
    {
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d70: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d90: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dad: Unknown result type (might be due to invalid IL or missing references)
        //IL_d1f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_d1f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_159ed: Unknown result type (might be due to invalid IL or missing references)
        if (!active)
        {
            return;
        }
        Main.projectileIdentity[owner, identity] = -1;
        int num = timeLeft;
        timeLeft = 0;
        bool flag = true;
        if (type >= 0 && type < ProjectileID.Count && ProjectileID.Sets.DontCancelChannelOnKill[type])
        {
            flag = false;
        }
        if (owner == Main.myPlayer && flag)
        {
            Main.player[owner].TryCancelChannel(this);
        }
        if (Main.getGoodWorld && aiStyle == 16)
        {
            TryGettingHitByOtherPlayersExplosives();
        }
        if (Main.netMode != 1 && Main.getGoodWorld)
        {
            if (type == 472)
            {
                SpawnWebs();
            }
            if (type == 99)
            {
                BoulderExplosion();
            }
        }
        if (type == 1020)
        {
            if (position.Y - (float)height <= (float)(16 * Main.offScreenRange) && owner == Main.myPlayer)
            {
                Main.Achievements.GetCondition("TO_INFINITY_AND_BEYOND", "Do").Complete();
            }
            SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]))?.Stop();
            SoundEngine.PlaySound(SoundID.Item62, position);
            Color transparent = Color.Transparent;
            for (int i = 0; i < 15; i++)
            {
                Dust dust = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, transparent, 0.8f);
                dust.fadeIn = 0f;
                Dust dust2 = dust;
                dust2.velocity *= 0.5f;
            }
            for (int j = 0; j < 5; j++)
            {
                Dust dust3 = Dust.NewDustDirect(position, width, height, 228, 0f, 0f, 100, transparent, 2.5f);
                dust3.noGravity = true;
                Dust dust2 = dust3;
                dust2.velocity *= 2.5f;
                dust3 = Dust.NewDustDirect(position, width, height, 228, 0f, 0f, 100, transparent, 1.1f);
                dust2 = dust3;
                dust2.velocity *= 2f;
                dust3.noGravity = true;
            }
            for (int k = 0; k < 3; k++)
            {
                Dust dust4 = Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 100, transparent, 1.1f);
                Dust dust2 = dust4;
                dust2.velocity *= 2f;
                dust4.noGravity = true;
            }
            for (int l = -1; l <= 1; l += 2)
            {
                for (int m = -1; m <= 1; m += 2)
                {
                    if (Main.rand.Next(5) == 0)
                    {
                        Gore gore = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                        Gore gore2 = gore;
                        gore2.velocity *= 0.2f;
                        gore2 = gore;
                        gore2.scale *= 0.65f;
                        gore2 = gore;
                        gore2.velocity += new Vector2(l, m) * 0.5f;
                    }
                }
            }
        }
        else if (type == 949)
        {
            SoundEngine.PlaySound(SoundID.Item10, base.Center);
            int num2 = (int)ai[0];
            float num3 = 20f;
            for (float num4 = 0f; num4 < num3; num4++)
            {
                Vector2 vector = position;
                int num5 = Dust.NewDust(vector, 4, 4, num2, 0f, 0f, 100);
                if (Main.rand.Next(3) != 0)
                {
                    Main.dust[num5].noGravity = true;
                }
                Dust dust2 = Main.dust[num5];
                dust2.velocity *= 0.8f;
                if (num2 == 66)
                {
                    Main.dust[num5].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                    Main.dust[num5].noGravity = true;
                }
            }
        }
        else if (type == 985)
        {
            if (localAI[1] != 1f)
            {
                Color value = new Color(64, 220, 96);
                Color value2 = new Color(15, 84, 125);
                for (int n = 0; n < 20; n++)
                {
                    float num6 = Main.rand.NextFloatDirection();
                    float num7 = 1f - Math.Abs(num6);
                    float f = rotation + num6 * ((float)Math.PI / 2f) * 0.9f;
                    Vector2 vector2 = base.Center + f.ToRotationVector2() * Utils.Remap(Main.rand.NextFloat(), 0f, 1f, 60f, 85f) * scale;
                    float num8 = Main.rand.NextFloat();
                    vector2 -= rotation.ToRotationVector2() * num8 * 70f * scale;
                    Color value3 = Color.Lerp(value2, value, 1f);
                    value3 = Color.Lerp(value3, Color.White, 0.5f);
                    Color.Lerp(value3, Color.White, Main.rand.NextFloat() * 0.3f);
                    Dust dust5 = Dust.NewDustPerfect(vector2, 107, velocity.RotatedBy(num6 * ((float)Math.PI / 4f)) * 0.2f * Main.rand.NextFloat(), 100, default(Color), 1.4f * num7);
                    Dust dust2 = dust5;
                    dust2.position -= dust5.velocity * Main.rand.NextFloat() * 3f;
                    dust2 = dust5;
                    dust2.scale *= 1f - num8;
                }
                for (int num9 = 0; num9 < 10; num9++)
                {
                    float num10 = Main.rand.NextFloatDirection();
                    float num11 = 1f - Math.Abs(num10);
                    float f2 = rotation + num10 * ((float)Math.PI / 2f) * 0.9f;
                    Vector2 vector3 = base.Center + f2.ToRotationVector2() * Utils.Remap(Main.rand.NextFloat(), 0f, 1f, 70f, 85f) * scale;
                    float num12 = Main.rand.NextFloat() * 0.25f;
                    vector3 -= rotation.ToRotationVector2() * (0.2f + num12) * 70f * scale;
                    Color value4 = Color.Lerp(value2, value, 0.66f);
                    value4 = Color.Lerp(value4, Color.White, 0.33f);
                    Color.Lerp(value4, Color.White, Main.rand.NextFloat() * 0.3f);
                    Dust dust6 = Dust.NewDustPerfect(vector3, 107, velocity.RotatedBy(num10 * ((float)Math.PI / 4f)) * 0.2f * Main.rand.NextFloat(), 100, default(Color), 1.4f * num11);
                    Dust dust2 = dust6;
                    dust2.position -= dust6.velocity * Main.rand.NextFloat() * 3f;
                    dust2 = dust6;
                    dust2.scale *= 1f - num12;
                }
                for (int num13 = 0; num13 < 10; num13++)
                {
                    float num14 = Main.rand.NextFloatDirection();
                    float num15 = 1f - Math.Abs(num14);
                    float f3 = rotation + num14 * ((float)Math.PI / 2f) * 0.9f;
                    Vector2 vector4 = base.Center + f3.ToRotationVector2() * Utils.Remap(Main.rand.NextFloat(), 0f, 1f, 60f, 75f) * scale;
                    float num16 = Main.rand.NextFloat() * 0.25f;
                    vector4 -= rotation.ToRotationVector2() * (0.5f + num16) * 70f * scale;
                    Color value5 = Color.Lerp(value2, value, 0.33f);
                    value5 = Color.Lerp(value5, Color.White, 0.16f);
                    Color.Lerp(value5, Color.White, Main.rand.NextFloat() * 0.3f);
                    Dust dust7 = Dust.NewDustPerfect(vector4, 107, velocity.RotatedBy(num14 * ((float)Math.PI / 4f)) * 0.2f * Main.rand.NextFloat(), 100, default(Color), 1.4f * num15);
                    Dust dust2 = dust7;
                    dust2.position -= dust7.velocity * Main.rand.NextFloat() * 3f;
                    dust2 = dust7;
                    dust2.scale *= 1f - num16;
                }
            }
        }
        else if (type == 756)
        {
            for (float num17 = 0f; num17 < 1f; num17 += 0.025f)
            {
                Dust dust8 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(16f, 16f) * scale + velocity.SafeNormalize(Vector2.UnitY) * num17 * 200f * scale, 5, Main.rand.NextVector2Circular(3f, 3f));
                dust8.velocity.Y += -0.3f;
                Dust dust2 = dust8;
                dust2.velocity += velocity * 0.2f;
                dust8.scale = 1f;
                dust8.alpha = 100;
            }
        }
        else if (type == 961)
        {
            for (float num18 = 0f; num18 < 1f; num18 += 0.25f)
            {
                Dust dust9 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(16f, 16f) * scale + velocity.SafeNormalize(Vector2.UnitY) * num18 * 200f * scale, 16, Main.rand.NextVector2Circular(3f, 3f));
                dust9.velocity.Y += -0.3f;
                Dust dust2 = dust9;
                dust2.velocity += velocity * 0.2f;
                dust9.scale = 1f;
                dust9.alpha = 100;
            }
        }
        else if (type == 962)
        {
            for (int num19 = 0; num19 < 20; num19++)
            {
                Dust dust10 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(16f, 16f) * scale, 16, Main.rand.NextVector2Circular(2f, 2f));
                Dust dust2 = dust10;
                dust2.velocity += velocity * 0.1f;
                dust10.scale = 1f;
                dust10.alpha = 100;
            }
        }
        else if (type == 932)
        {
            Color fairyQueenWeaponsColor = GetFairyQueenWeaponsColor();
            SoundEngine.PlaySound(SoundID.Item10, base.Center);
            Vector2 target = base.Center;
            Main.rand.NextFloat();
            int num20 = 10;
            for (int num21 = 0; num21 < num20; num21++)
            {
                Vector2 vector5 = position - velocity * num21;
                int num22 = Main.rand.Next(1, 3);
                float num23 = MathHelper.Lerp(0.3f, 1f, Utils.GetLerpValue(num20, 0f, num21, clamped: true));
                if ((float)num21 >= (float)oldPos.Length * 0.3f)
                {
                    num22--;
                }
                if ((float)num21 >= (float)oldPos.Length * 0.75f)
                {
                    num22 -= 2;
                }
                vector5.DirectionTo(target).SafeNormalize(Vector2.Zero);
                target = vector5;
                for (float num24 = 0f; num24 < (float)num22; num24++)
                {
                    int num25 = Dust.NewDust(vector5, width, height, 267, 0f, 0f, 0, fairyQueenWeaponsColor);
                    Dust dust2 = Main.dust[num25];
                    dust2.velocity *= Main.rand.NextFloat() * 0.8f;
                    Main.dust[num25].noGravity = true;
                    Main.dust[num25].scale = 0.9f + Main.rand.NextFloat() * 1.2f;
                    Main.dust[num25].fadeIn = Main.rand.NextFloat() * 1.2f * num23;
                    dust2 = Main.dust[num25];
                    dust2.scale *= num23;
                    if (num25 != 6000)
                    {
                        Dust dust11 = Dust.CloneDust(num25);
                        dust2 = dust11;
                        dust2.scale /= 2f;
                        dust2 = dust11;
                        dust2.fadeIn *= 0.85f;
                        dust11.color = new Color(255, 255, 255, 255);
                    }
                }
            }
        }
        else if (type == 931)
        {
            Color fairyQueenWeaponsColor2 = GetFairyQueenWeaponsColor();
            SoundEngine.PlaySound(SoundID.Item10, base.Center);
            Vector2 target2 = base.Center;
            Main.rand.NextFloat();
            for (int num26 = 0; num26 < oldPos.Length; num26++)
            {
                Vector2 vector6 = oldPos[num26];
                if (vector6 == Vector2.Zero)
                {
                    break;
                }
                int num27 = Main.rand.Next(1, 3);
                float num28 = MathHelper.Lerp(0.3f, 1f, Utils.GetLerpValue(oldPos.Length, 0f, num26, clamped: true));
                if ((float)num26 >= (float)oldPos.Length * 0.3f)
                {
                    num27--;
                }
                if ((float)num26 >= (float)oldPos.Length * 0.75f)
                {
                    num27 -= 2;
                }
                vector6.DirectionTo(target2).SafeNormalize(Vector2.Zero);
                target2 = vector6;
                for (float num29 = 0f; num29 < (float)num27; num29++)
                {
                    int num30 = Dust.NewDust(vector6, width, height, 267, 0f, 0f, 0, fairyQueenWeaponsColor2);
                    Dust dust2 = Main.dust[num30];
                    dust2.velocity *= Main.rand.NextFloat() * 0.8f;
                    Main.dust[num30].noGravity = true;
                    Main.dust[num30].scale = 0.9f + Main.rand.NextFloat() * 1.2f;
                    Main.dust[num30].fadeIn = Main.rand.NextFloat() * 1.2f * num28;
                    dust2 = Main.dust[num30];
                    dust2.scale *= num28;
                    if (num30 != 6000)
                    {
                        Dust dust12 = Dust.CloneDust(num30);
                        dust2 = dust12;
                        dust2.scale /= 2f;
                        dust2 = dust12;
                        dust2.fadeIn *= 0.85f;
                        dust12.color = new Color(255, 255, 255, 255);
                    }
                }
            }
        }
        else if (type == 79)
        {
            int newWidth = width;
            int newHeight = height;
            Resize(128, 128);
            maxPenetrate = -1;
            penetrate = -1;
            Damage();
            Resize(newWidth, newHeight);
            SoundEngine.PlaySound(SoundID.Item10, base.Center);
            Vector2 target3 = base.Center;
            float num31 = Main.rand.NextFloat();
            for (int num32 = 0; num32 < oldPos.Length; num32++)
            {
                Vector2 vector7 = oldPos[num32];
                if (vector7 == Vector2.Zero)
                {
                    break;
                }
                Color newColor = Main.hslToRgb((num31 + Utils.GetLerpValue(oldPos.Length, 0f, num32, clamped: true)) % 1f, 1f, 0.65f);
                int num33 = Main.rand.Next(1, 4);
                float lerpValue = Utils.GetLerpValue(oldPos.Length, 0f, num32, clamped: true);
                float num34 = MathHelper.Lerp(0.3f, 1f, lerpValue);
                if ((float)num32 >= (float)oldPos.Length * 0.3f)
                {
                    num33--;
                }
                if ((float)num32 >= (float)oldPos.Length * 0.65f)
                {
                    num33 -= 2;
                }
                if ((float)num32 >= (float)oldPos.Length * 0.85f)
                {
                    num33 -= 3;
                }
                Vector2 vector8 = vector7.DirectionTo(target3).SafeNormalize(Vector2.Zero);
                target3 = vector7;
                Vector2 vector9 = base.Size / 2f;
                for (float num35 = 0f; num35 < (float)num33; num35++)
                {
                    int num36 = Dust.NewDust(vector7, width, height, 267, 0f, 0f, 0, newColor);
                    Dust dust2 = Main.dust[num36];
                    dust2.velocity *= Main.rand.NextFloat() * 0.8f;
                    Main.dust[num36].noGravity = true;
                    Main.dust[num36].scale = 0.9f + Main.rand.NextFloat() * 1.2f;
                    Main.dust[num36].fadeIn = Main.rand.NextFloat() * 1.2f * num34;
                    dust2 = Main.dust[num36];
                    dust2.velocity += vector8 * 6f;
                    dust2 = Main.dust[num36];
                    dust2.scale *= num34;
                    Main.dust[num36].position = Vector2.Lerp(vector7 + vector9, Main.dust[num36].position, lerpValue);
                    if (num36 != 6000)
                    {
                        Dust dust13 = Dust.CloneDust(num36);
                        dust2 = dust13;
                        dust2.scale /= 2f;
                        dust2 = dust13;
                        dust2.fadeIn *= 0.85f;
                        dust13.color = new Color(255, 255, 255, 255);
                    }
                }
            }
            for (float num37 = 0f; num37 < 0.5f; num37 += 0.25f)
            {
                ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.RainbowRodHit, new ParticleOrchestraSettings
                {
                    PositionInWorld = base.Center,
                    MovementVector = Vector2.UnitX.RotatedBy(num37 * ((float)Math.PI * 2f)) * 16f
                }, owner);
            }
            for (int num38 = 0; num38 < 14; num38++)
            {
                int num39 = Dust.NewDust(position, width, height, 66, 0f, 0f, 100, Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f), 1.7f);
                Main.dust[num39].noGravity = true;
                Dust dust2 = Main.dust[num39];
                dust2.velocity *= 3f;
            }
        }
        else if (type == 16)
        {
            int newWidth2 = width;
            int newHeight2 = height;
            Resize(128, 128);
            maxPenetrate = -1;
            penetrate = -1;
            Damage();
            Resize(newWidth2, newHeight2);
            SoundEngine.PlaySound(SoundID.Item10, base.Center);
            Vector2 target4 = base.Center;
            for (int num40 = 0; num40 < oldPos.Length; num40++)
            {
                Vector2 vector10 = oldPos[num40];
                if (vector10 == Vector2.Zero)
                {
                    break;
                }
                Color newColor2 = Main.hslToRgb(4f / 9f + Main.rand.NextFloat() * (2f / 9f), 1f, 0.65f);
                int num41 = Main.rand.Next(1, 4);
                float num42 = MathHelper.Lerp(0.3f, 1f, Utils.GetLerpValue(oldPos.Length, 0f, num40, clamped: true));
                if ((float)num40 >= (float)oldPos.Length * 0.3f)
                {
                    num41--;
                }
                if ((float)num40 >= (float)oldPos.Length * 0.75f)
                {
                    num41 -= 2;
                }
                Vector2 vector11 = vector10.DirectionTo(target4).SafeNormalize(Vector2.Zero);
                target4 = vector10;
                for (float num43 = 0f; num43 < (float)num41; num43++)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        int num44 = Dust.NewDust(vector10, width, height, 267, 0f, 0f, 0, newColor2);
                        Dust dust2 = Main.dust[num44];
                        dust2.velocity *= Main.rand.NextFloat() * 0.8f;
                        Main.dust[num44].noGravity = true;
                        Main.dust[num44].scale = Main.rand.NextFloat() * 0.8f;
                        Main.dust[num44].fadeIn = Main.rand.NextFloat() * 1.2f * num42;
                        dust2 = Main.dust[num44];
                        dust2.velocity += vector11 * 6f;
                        dust2 = Main.dust[num44];
                        dust2.scale *= num42;
                        if (num44 != 6000)
{
                            Dust dust14 = Dust.CloneDust(num44);
                            dust2 = dust14;
                            dust2.scale /= 2f;
                            dust2 = dust14;
                            dust2.fadeIn /= 2f;
                            dust14.color = new Color(255, 255, 255, 255);
                        }
                    }
                    else
                    {
                        Dust dust15 = Dust.NewDustDirect(vector10, width, height, 15, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100);
                        Main.rand.Next(2);
                        dust15.noGravity = true;
                        Dust dust2 = dust15;
                        dust2.velocity *= 2f;
                        dust2 = dust15;
                        dust2.velocity += vector11 * 9f;
                        dust2 = dust15;
                        dust2.scale *= num42;
                        dust15.fadeIn = (0.6f + Main.rand.NextFloat() * 0.4f) * num42;
                        dust15.noLightEmittence = (dust15.noLight = true);
                    }
                }
            }
            for (int num45 = 0; num45 < 20; num45++)
            {
                Dust dust16 = Dust.NewDustDirect(position, width, height, 15);
                dust16.noGravity = true;
                dust16.velocity = Main.rand.NextVector2Circular(1f, 1f) * 1.5f;
                dust16.scale = 1.2f + Main.rand.NextFloat() * 0.5f;
                dust16.noLightEmittence = (dust16.noLight = true);
                Dust dust2 = dust16;
                dust2.velocity += velocity * 0.01f;
                dust2 = dust16;
                dust2.position += dust16.velocity * Main.rand.Next(1, 16);
                dust16 = Dust.NewDustDirect(position, width, height, 15, 0f, 0f, 100);
                dust2 = dust16;
                dust2.velocity *= 1.2f;
                dust16.noLightEmittence = (dust16.noLight = true);
                dust2 = dust16;
                dust2.velocity += velocity * 0.01f;
                dust2 = dust16;
                dust2.scale *= 0.8f + Main.rand.NextFloat() * 0.2f;
                dust2 = dust16;
                dust2.position += dust16.velocity * Main.rand.Next(1, 16);
            }
        }
        else if (type == 34)
        {
            int newWidth3 = width;
            int newHeight3 = height;
            Resize(96, 96);
            maxPenetrate = -1;
            penetrate = -1;
            Damage();
            Resize(newWidth3, newHeight3);
            SoundEngine.PlaySound(SoundID.Item10, position);
            Vector2 target5 = base.Center;
            for (int num46 = 0; num46 < oldPos.Length; num46++)
            {
                Vector2 vector12 = oldPos[num46];
                if (vector12 == Vector2.Zero)
                {
                    break;
                }
                Color newColor3 = Main.hslToRgb(Main.rand.NextFloat() * (1f / 9f), 1f, 0.5f);
                int num47 = Main.rand.Next(1, 5);
                float num48 = MathHelper.Lerp(0.3f, 1f, Utils.GetLerpValue(oldPos.Length, 0f, num46, clamped: true));
                if ((float)num46 >= (float)oldPos.Length * 0.3f)
                {
                    num47--;
                }
                if ((float)num46 >= (float)oldPos.Length * 0.75f)
                {
                    num47 -= 2;
                }
                Vector2 vector13 = vector12.DirectionTo(target5).SafeNormalize(Vector2.Zero);
                target5 = vector12;
                for (float num49 = 0f; num49 < (float)num47; num49++)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        int num50 = Dust.NewDust(vector12, width, height, 267, 0f, 0f, 0, newColor3);
                        Dust dust2 = Main.dust[num50];
                        dust2.velocity *= Main.rand.NextFloat() * 0.8f;
                        Main.dust[num50].noGravity = true;
                        Main.dust[num50].scale = Main.rand.NextFloat() * 1f;
                        Main.dust[num50].fadeIn = Main.rand.NextFloat() * 2f;
                        dust2 = Main.dust[num50];
                        dust2.velocity += vector13 * 8f;
                        dust2 = Main.dust[num50];
                        dust2.scale *= num48;
                        if (num50 != 6000)
{
                            Dust dust17 = Dust.CloneDust(num50);
                            dust2 = dust17;
                            dust2.scale /= 2f;
                            dust2 = dust17;
                            dust2.fadeIn /= 2f;
                            dust17.color = new Color(255, 255, 255, 255);
                        }
                    }
                    else
                    {
                        Dust dust18 = Dust.NewDustDirect(vector12, width, height, 6, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100);
                        Dust dust2;
                        if (Main.rand.Next(2) == 0)
{
                            dust18.noGravity = true;
                            dust2 = dust18;
                            dust2.scale *= 2.5f;
                        }
                        dust2 = dust18;
                        dust2.velocity *= 2f;
                        dust2 = dust18;
                        dust2.velocity += vector13 * 6f;
                        dust2 = dust18;
                        dust2.scale *= num48;
                        dust18.noLightEmittence = (dust18.noLight = true);
                    }
                }
            }
            for (int num51 = 0; num51 < 20; num51++)
            {
                Dust dust19 = Dust.NewDustDirect(position, width, height, 6, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100);
                dust19.noGravity = true;
                dust19.velocity = Main.rand.NextVector2Circular(1f, 1f) * 6f;
                dust19.scale = 1.6f;
                dust19.fadeIn = 1.3f + Main.rand.NextFloat() * 1f;
                dust19.noLightEmittence = (dust19.noLight = true);
                Dust dust2 = dust19;
                dust2.velocity += velocity * 0.1f;
                dust19 = Dust.NewDustDirect(position, width, height, 6, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100);
                dust2 = dust19;
                dust2.velocity *= 2f;
                dust19.noLightEmittence = (dust19.noLight = true);
                dust2 = dust19;
                dust2.velocity += velocity * 0.1f;
            }
        }
        if (type == 873)
        {
            int num52 = 20;
            float num53 = (float)Math.PI * 2f / (float)num52;
            float num54 = velocity.ToRotation();
            Color value6 = AI_171_GetColor();
            for (int num55 = 0; num55 < num52; num55++)
            {
                Dust dust20 = Dust.NewDustPerfect(base.Center, 267);
                dust20.fadeIn = 1f;
                dust20.noGravity = true;
                dust20.alpha = 100;
                dust20.color = Color.Lerp(value6, Color.White, Main.rand.NextFloat() * 0.4f);
                if (num55 % 4 == 0)
                {
                    dust20.velocity = num54.ToRotationVector2() * 3.2f;
                    dust20.scale = 2.3f;
                }
                else if (num55 % 2 == 0)
                {
                    dust20.velocity = num54.ToRotationVector2() * 1.8f;
                    dust20.scale = 1.9f;
                }
                else
                {
                    dust20.velocity = num54.ToRotationVector2();
                    dust20.scale = 1.6f;
                }
                num54 += num53;
                Dust dust2 = dust20;
                dust2.velocity += velocity * Main.rand.NextFloat() * 0.5f;
            }
        }
        _ = type;
        _ = 857;
        if (type == 1012)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num56 = 0; num56 < 40; num56++)
            {
                Vector2 vector14 = Vector2.UnitY.RotatedBy((float)num56 * ((float)Math.PI * 2f)) * (2f + Main.rand.NextFloat() * 0.5f);
                vector14 += velocity * Main.rand.NextFloat();
                Color white = Color.White;
                if (Main.rand.Next(3) == 0)
                {
                    Dust dust21 = Dust.NewDustDirect(newColor: Main.rand.Next(3) switch
                    {
                        0 => new Color(226, 116, 56),
                        1 => new Color(243, 175, 93),
                        2 => new Color(254, 210, 146),
                        _ => new Color(176, 64, 36),
                    }, Position: position + Main.rand.NextVector2Circular(18f, 18f) * scale, Width: 2, Height: 2, Type: 284, SpeedX: vector14.X, SpeedY: vector14.Y, Alpha: 0, Scale: Main.rand.NextFloat() * 1f + 1f);
                    Dust dust2 = dust21;
                    dust2.position -= velocity;
                    dust21.fadeIn = 1f;
                }
                else
                {
                    vector14 *= 0.3f;
                    Dust dust22 = Dust.NewDustDirect(position + Main.rand.NextVector2Circular(18f, 18f) * scale, 2, 2, 138, vector14.X, vector14.Y, 0, default(Color), Main.rand.NextFloat() * 0.3f + 0.6f);
                    Dust dust2 = dust22;
                    dust2.position -= velocity;
                }
            }
        }
        if (type == 920)
        {
            for (int num57 = 0; num57 < 6; num57++)
            {
                Vector2 vector15 = Vector2.UnitY.RotatedBy((float)num57 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.5f) * (2f + Main.rand.NextFloat() * 0.5f);
                int num58 = Dust.NewDust(position + base.Size * Main.rand.NextVector2Square(0f, 1f), 4, 4, 4, vector15.X, vector15.Y, 80, new Color(78, 136, 255, 150), 1.5f);
                Main.dust[num58].noGravity = true;
            }
        }
        if (type == 921)
        {
            for (int num59 = 0; num59 < 12; num59++)
            {
                Vector2 vector16 = Vector2.UnitY.RotatedBy((float)num59 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.5f) * (3f + Main.rand.NextFloat() * 0.5f);
                int num60 = Dust.NewDust(position + base.Size * Main.rand.NextVector2Square(0f, 1f), 6, 6, 243, vector16.X, vector16.Y, 80, default(Color), 1.5f);
                Main.dust[num60].noGravity = true;
            }
        }
        if (type == 926)
        {
            for (int num61 = 0; num61 < 22; num61++)
            {
                Vector2 vector17 = Vector2.UnitY.RotatedBy((float)num61 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.5f) * (3f + Main.rand.NextFloat() * 0.5f);
                int num62 = Dust.NewDust(position - new Vector2(8f, 8f), width + 16, height + 16, 31, vector17.X, vector17.Y, 40, NPC.AI_121_QueenSlime_GetDustColor(), 1.5f);
                Main.dust[num62].noGravity = true;
            }
        }
        if (type == 937)
        {
            for (int num63 = 0; num63 < 12; num63++)
            {
                Vector2 vector18 = Vector2.UnitY.RotatedBy((float)num63 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.5f) * (3f + Main.rand.NextFloat() * 0.5f);
                int num64 = Dust.NewDust(position - new Vector2(8f, 8f), width + 16, height + 16, 31, vector18.X, vector18.Y, 40, NPC.AI_121_QueenSlime_GetDustColor(), 1.5f);
                Main.dust[num64].noGravity = true;
            }
        }
        if (type == 818)
        {
            for (float num65 = 0f; num65 < 1f; num65 += 0.34f)
            {
                Dust.NewDustPerfect(position + base.Size * Main.rand.NextVector2Square(0f, 1f), 278, Vector2.UnitY.RotatedBy(num65 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.5f) * (2f + Main.rand.NextFloat() * 0.5f), 150, Color.Lerp(Color.White, Color.Gold, Main.rand.NextFloat()), 0.4f).noGravity = true;
            }
            for (float num66 = 0f; num66 < 1f; num66 += 0.34f)
            {
                Dust.NewDustPerfect(position + base.Size * Main.rand.NextVector2Square(0f, 1f), 278, Vector2.UnitY.RotatedBy(num66 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.5f) * (1f + Main.rand.NextFloat() * 0.5f), 150, Color.Lerp(Color.White, Main.OurFavoriteColor, Main.rand.NextFloat()), 0.7f).noGravity = true;
            }
        }
        if (type == 856)
        {
            for (int num67 = 0; num67 < 6; num67++)
            {
                Dust.NewDust(position, width, height, 58, 0f, 0f, 150, default(Color), 0.8f);
            }
            for (float num68 = 0f; num68 < 1f; num68 += 0.34f)
            {
                Dust.NewDustPerfect(base.Center, 278, Vector2.UnitY.RotatedBy(num68 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.5f) * (4f + Main.rand.NextFloat() * 2f), 150, Color.Lerp(Color.White, Color.HotPink, Main.rand.NextFloat() * 0.5f + 0.5f)).noGravity = true;
            }
            for (float num69 = 0f; num69 < 1f; num69 += 0.34f)
            {
                Dust.NewDustPerfect(base.Center, 278, Vector2.UnitY.RotatedBy(num69 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.5f) * (2f + Main.rand.NextFloat() * 1f), 150, Color.Lerp(Color.White, Color.Orange, Main.rand.NextFloat() * 0.5f + 0.5f)).noGravity = true;
            }
            Vector2 vector19 = new Vector2(Main.screenWidth, Main.screenHeight);
            if (base.Hitbox.Intersects(Utils.CenteredRectangle(Main.screenPosition + vector19 / 2f, vector19 + new Vector2(400f))))
            {
                for (int num70 = 0; num70 < 1; num70++)
                {
                    Gore.NewGore(position, Main.rand.NextVector2CircularEdge(0.5f, 0.5f) * 3f, Utils.SelectRandom<int>(Main.rand, 16));
                }
            }
            ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.StellarTune, new ParticleOrchestraSettings
            {
                PositionInWorld = base.Center
            }, owner);
            position = base.Center;
            width = (height = 128);
            base.Center = position;
            maxPenetrate = -1;
            penetrate = -1;
            Damage();
        }
        if (type == 818)
        {
            Damage();
        }
        if (type == 686)
        {
            SoundEngine.PlayTrackedSound(SoundID.DD2_BetsyFireballImpact, base.Center);
        }
        else if (type == 711)
        {
            SoundEngine.PlayTrackedSound(SoundID.DD2_BetsysWrathImpact, base.Center);
        }
        else if (type == 704)
        {
            ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
            if (activeSound != null)
            {
                activeSound.Volume = 0f;
                activeSound.Stop();
            }
        }
        if (type == 710)
        {
            ai[1] = -1f;
            position = base.Center;
            width = (height = 40);
            base.Center = position;
            Damage();
            SoundEngine.PlaySound(SoundID.Item14, position);
            for (int num71 = 0; num71 < 2; num71++)
            {
                int num72 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num72].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
            }
            for (int num73 = 0; num73 < 10; num73++)
            {
                int num74 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.5f);
                Main.dust[num74].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Main.dust[num74].noGravity = true;
                Dust dust2 = Main.dust[num74];
                dust2.velocity *= 2f;
            }
            for (int num75 = 0; num75 < 5; num75++)
            {
                int num76 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num76].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num76].noGravity = true;
                Dust dust2 = Main.dust[num76];
                dust2.velocity *= 2f;
            }
        }
        else if (type == 711)
        {
            Rectangle hitbox = base.Hitbox;
            for (int num77 = 0; num77 < oldPos.Length / 2; num77 += 2)
            {
                hitbox.X = (int)oldPos[num77].X;
                hitbox.Y = (int)oldPos[num77].Y;
                for (int num78 = 0; num78 < 2; num78++)
                {
                    int num79 = Utils.SelectRandom<int>(Main.rand, 6, 55, 158);
                    int num80 = Dust.NewDust(hitbox.TopLeft(), width, height, num79, direction, -2.5f);
                    Main.dust[num80].alpha = 200;
                    Dust dust2 = Main.dust[num80];
                    dust2.velocity *= 2.4f;
                    dust2 = Main.dust[num80];
                    dust2.scale += Main.rand.NextFloat();
                    dust2 = Main.dust[num80];
                    dust2.scale -= 0.5f;
                    if (Main.dust[num80].type == 55)
                    {
                        Main.dust[num80].color = Color.Lerp(new Color(128, 0, 180, 128), Color.Gold, Main.rand.NextFloat());
                    }
                    Main.dust[num80].noLight = true;
                }
            }
            for (int num81 = 10; num81 < oldPos.Length; num81 += 2)
            {
                hitbox.X = (int)oldPos[num81].X;
                hitbox.Y = (int)oldPos[num81].Y;
                for (int num82 = 0; num82 < 2; num82++)
                {
                    if (Main.rand.Next(3) != 0)
                    {
                        int num83 = Utils.SelectRandom<int>(Main.rand, 55);
                        int num84 = Dust.NewDust(hitbox.TopLeft(), width, height, num83, direction, -2.5f);
                        Main.dust[num84].alpha = 120;
                        Dust dust2 = Main.dust[num84];
                        dust2.velocity *= 2.4f;
                        dust2 = Main.dust[num84];
                        dust2.scale += Main.rand.NextFloat() * 0.7f;
                        dust2 = Main.dust[num84];
                        dust2.scale -= 0.5f;
                        if (Main.dust[num84].type == 55)
{
                            Main.dust[num84].color = Color.Lerp(Color.Purple, Color.Black, Main.rand.NextFloat());
                        }
                        Main.dust[num84].noLight = true;
                    }
                }
            }
            for (int num85 = 5; num85 < oldPos.Length; num85++)
            {
                hitbox.X = (int)oldPos[num85].X;
                hitbox.Y = (int)oldPos[num85].Y;
                for (int num86 = 0; num86 < 1; num86++)
                {
                    if (Main.rand.Next(3) != 0)
                    {
                        int num87 = Utils.SelectRandom<int>(Main.rand, 55);
                        int num88 = Dust.NewDust(hitbox.TopLeft(), width, height, num87, direction, -2.5f);
                        Main.dust[num88].alpha = 80;
                        Dust dust2 = Main.dust[num88];
                        dust2.velocity *= 0.3f;
                        dust2 = Main.dust[num88];
                        dust2.velocity += velocity * 0.5f;
                        dust2 = Main.dust[num88];
                        dust2.scale += Main.rand.NextFloat() * 0.7f;
                        dust2 = Main.dust[num88];
                        dust2.scale -= 0.5f;
                        if (Main.dust[num88].type == 55)
{
                            Main.dust[num88].color = Color.Lerp(Color.Purple, Color.Black, Main.rand.NextFloat());
                        }
                        Main.dust[num88].noLight = true;
                    }
                }
            }
            for (int num89 = 0; num89 < 20; num89++)
            {
                if (Main.rand.Next(3) != 0)
                {
                    int num90 = 228;
                    Dust dust23 = Main.dust[Dust.NewDust(position, width, height, num90)];
                    dust23.noGravity = true;
                    dust23.scale = 1.25f + Main.rand.NextFloat();
                    dust23.fadeIn = 1.5f;
                    Dust dust2 = dust23;
                    dust2.velocity *= 6f;
                    dust23.noLight = true;
                }
            }
            for (int num91 = 0; num91 < 20; num91++)
            {
                if (Main.rand.Next(3) != 0)
                {
                    int num92 = 55;
                    Dust dust24 = Main.dust[Dust.NewDust(position, width, height, num92)];
                    dust24.noGravity = true;
                    dust24.scale = 1.25f + Main.rand.NextFloat();
                    dust24.fadeIn = 1.5f;
                    Dust dust2 = dust24;
                    dust2.velocity *= 6f;
                    dust24.noLight = true;
                    dust24.color = new Color(0, 0, 220, 128);
                }
            }
            if (owner == Main.myPlayer)
            {
                position = base.Center;
                base.Size = new Vector2(140f);
                base.Center = position;
                penetrate = -1;
                usesLocalNPCImmunity = true;
                localNPCHitCooldown = -1;
                Damage();
            }
        }
        else if (type == 662 || type == 685)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            Vector2 vector20 = oldVelocity.SafeNormalize(Vector2.Zero);
            Vector2 vector21 = position + vector20 * 16f;
            for (int num93 = 0; num93 < 16; num93++)
            {
                if (Main.rand.Next(2) == 0)
                {
                    vector21 -= vector20 * 8f;
                    continue;
                }
                Dust dust25 = Dust.NewDustDirect(vector21, width, height, 11);
                dust25.position = (dust25.position + base.Center) / 2f;
                Dust dust2 = dust25;
                dust2.velocity += oldVelocity * 0.4f;
                dust2 = dust25;
                dust2.velocity *= 0.5f;
                dust25.noGravity = true;
                vector21 -= vector20 * 8f;
            }
        }
        if (type == 680)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            Vector2 vector22 = oldVelocity.SafeNormalize(Vector2.Zero);
            Vector2 vector23 = position + vector22 * 16f;
            for (int num94 = 0; num94 < 16; num94++)
            {
                if (Main.rand.Next(2) == 0)
                {
                    vector23 -= vector22 * 8f;
                    continue;
                }
                Dust dust26 = Dust.NewDustDirect(vector23, width, height, 11);
                dust26.position = (dust26.position + base.Center) / 2f;
                Dust dust2 = dust26;
                dust2.velocity += oldVelocity * 0.4f;
                dust2 = dust26;
                dust2.velocity *= 0.5f;
                dust26.noGravity = true;
                vector23 -= vector22 * 8f;
            }
            Dust.NewDustDirect(position, width, height, 11, 0f, 0f, 0, Color.Red, 1.6f).noGravity = true;
        }
        if (type == 664 || type == 666 || type == 668 || type == 706)
        {
            int num95 = 4;
            int num96 = 20;
            int num97 = 10;
            int num98 = 20;
            int num99 = 20;
            int num100 = 4;
            float num101 = 1.5f;
            int num102 = 6;
            int num103 = 6;
            if (Main.player[owner].setApprenticeT3)
            {
                num95 += 4;
                num99 += 10;
                num96 += 20;
                num98 += 30;
                num97 /= 2;
                num100 += 4;
                num101 += 0.5f;
                num102 += 7;
                num103 = 270;
            }
            position = base.Center;
            width = (height = 16 * num102);
            base.Center = position;
            Damage();
            SoundEngine.PlaySound(SoundID.Item100, position);
            for (int num104 = 0; num104 < num95; num104++)
            {
                int num105 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num105].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
            }
            for (int num106 = 0; num106 < num96; num106++)
            {
                Dust dust27 = Dust.NewDustDirect(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 200, default(Color), 2.5f);
                dust27.position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 10f;
                Dust dust2 = dust27;
                dust2.velocity *= 16f;
                if (dust27.velocity.Y > -2f)
                {
                    dust27.velocity.Y *= -0.4f;
                }
                dust27.noLight = true;
                dust27.noGravity = true;
            }
            for (int num107 = 0; num107 < num98; num107++)
            {
                Dust dust28 = Dust.NewDustDirect(new Vector2(position.X, position.Y), width, height, num103, 0f, 0f, 100, default(Color), 1.5f);
                dust28.position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Dust dust2 = dust28;
                dust2.velocity *= 2f;
                dust28.noGravity = true;
                dust28.fadeIn = num101;
            }
            for (int num108 = 0; num108 < num97; num108++)
            {
                int num109 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.7f);
                Main.dust[num109].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num109].noGravity = true;
                Dust dust2 = Main.dust[num109];
                dust2.velocity *= 3f;
            }
            for (int num110 = 0; num110 < num99; num110++)
            {
                int num111 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num111].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num111].noGravity = true;
                Dust dust2 = Main.dust[num111];
                dust2.velocity *= 3f;
            }
            for (int num112 = 0; num112 < num100; num112++)
            {
                int num113 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Main.gore[num113].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Gore gore2 = Main.gore[num113];
                gore2.position -= Vector2.One * 16f;
                if (Main.rand.Next(2) == 0)
                {
                    Main.gore[num113].position.Y -= 30f;
                }
                gore2 = Main.gore[num113];
                gore2.velocity *= 0.3f;
                Main.gore[num113].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num113].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
        }
        else if (type == 681)
        {
            position.X += width / 2;
            position.Y += height / 2;
            SoundEngine.PlaySound(SoundID.DD2_GoblinBomb, position);
            width = 22;
            height = 22;
            position.X -= width / 2;
            position.Y -= height / 2;
            for (int num114 = 0; num114 < 10; num114++)
            {
                int num115 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Dust dust2 = Main.dust[num115];
                dust2.velocity *= 1.4f;
                num115 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                dust2 = Main.dust[num115];
                dust2.velocity *= 1.4f;
                Main.dust[num115].noGravity = true;
                Main.dust[num115].fadeIn = 2f;
            }
            for (int num116 = 0; num116 < 10; num116++)
            {
                int num117 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                Main.dust[num117].noGravity = true;
                Dust dust2 = Main.dust[num117];
                dust2.velocity *= 5f;
                num117 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                dust2 = Main.dust[num117];
                dust2.velocity *= 3f;
            }
            int num118 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
            Gore gore2 = Main.gore[num118];
            gore2.velocity *= 0.4f;
            Main.gore[num118].velocity.X += 1f;
            Main.gore[num118].velocity.Y += 1f;
            num118 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
            gore2 = Main.gore[num118];
            gore2.velocity *= 0.4f;
            Main.gore[num118].velocity.X -= 1f;
            Main.gore[num118].velocity.Y += 1f;
            num118 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
            gore2 = Main.gore[num118];
            gore2.velocity *= 0.4f;
            Main.gore[num118].velocity.X += 1f;
            Main.gore[num118].velocity.Y -= 1f;
            num118 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
            gore2 = Main.gore[num118];
            gore2.velocity *= 0.4f;
            Main.gore[num118].velocity.X -= 1f;
            Main.gore[num118].velocity.Y -= 1f;
            position.X += width / 2;
            position.Y += height / 2;
            width = 80;
            height = 80;
            position.X -= width / 2;
            position.Y -= height / 2;
            Damage();
        }
        if (type == 669)
        {
            SoundEngine.PlaySound(13, (int)position.X, (int)position.Y);
            Vector2 vector24 = new Vector2(20f, 20f);
            for (int num119 = 0; num119 < 10; num119++)
            {
                Dust dust29 = Dust.NewDustDirect(base.Center - vector24 / 2f, (int)vector24.X, (int)vector24.Y, 4, 0f, 0f, 100, new Color(255, 255, 255, 110), 1.1f);
                Dust dust2 = dust29;
                dust2.velocity *= 1.4f;
            }
            for (int num120 = 0; num120 < 40; num120++)
            {
                Dust dust30 = Dust.NewDustDirect(base.Center - vector24 / 2f, (int)vector24.X, (int)vector24.Y, 4, 0f, 0f, 50, new Color(245, 200, 30, 155), 1.2f);
                dust30.noGravity = true;
                Dust dust2 = dust30;
                dust2.velocity *= 4f;
                dust30 = Dust.NewDustDirect(base.Center - vector24 / 2f, (int)vector24.X, (int)vector24.Y, 4, 0f, 0f, 50, new Color(245, 200, 30, 155), 0.8f);
                dust2 = dust30;
                dust2.velocity *= 2f;
            }
        }
        if (Main.myPlayer == owner && bobber)
        {
            PopupText.ClearSonarText();
            if (ai[1] > 0f && ai[1] < (float)ItemID.Count)
            {
                AI_061_FishingBobber_GiveItemToPlayer(Main.player[owner], (int)ai[1]);
            }
            ai[1] = 0f;
        }
        if (type == 634 || type == 635)
        {
            int num121 = Utils.SelectRandom<int>(Main.rand, 242, 73, 72, 71, 255);
            int num122 = 255;
            int num123 = 255;
            int num124 = 50;
            float num125 = 1.7f;
            float num126 = 0.8f;
            float num127 = 2f;
            Vector2 vector25 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
            Vector2 vector26 = vector25 * velocity.Length() * MaxUpdates;
            if (type == 635)
            {
                num122 = 88;
                num123 = 88;
                num121 = Utils.SelectRandom<int>(Main.rand, 242, 59, 88);
                num125 = 3.7f;
                num126 = 1.5f;
                num127 = 2.2f;
                vector26 *= 0.5f;
            }
            SoundEngine.PlaySound(SoundID.Item14, position);
            position = base.Center;
            width = (height = num124);
            base.Center = position;
            maxPenetrate = -1;
            penetrate = -1;
            Damage();
            for (int num128 = 0; num128 < 40; num128++)
            {
                num121 = Utils.SelectRandom<int>(Main.rand, 242, 73, 72, 71, 255);
                if (type == 635)
                {
                    num121 = Utils.SelectRandom<int>(Main.rand, 242, 59, 88);
                }
                int num129 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num121, 0f, 0f, 200, default(Color), num125);
                Main.dust[num129].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Main.dust[num129].noGravity = true;
                Dust dust2 = Main.dust[num129];
                dust2.velocity *= 3f;
                dust2 = Main.dust[num129];
                dust2.velocity += vector26 * Main.rand.NextFloat();
                num129 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num122, 0f, 0f, 100, default(Color), num126);
                Main.dust[num129].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                dust2 = Main.dust[num129];
                dust2.velocity *= 2f;
                Main.dust[num129].noGravity = true;
                Main.dust[num129].fadeIn = 1f;
                Main.dust[num129].color = Color.Crimson * 0.5f;
                dust2 = Main.dust[num129];
                dust2.velocity += vector26 * Main.rand.NextFloat();
            }
            for (int num130 = 0; num130 < 20; num130++)
            {
                int num131 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num123, 0f, 0f, 0, default(Color), num127);
                Main.dust[num131].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 3f;
                Main.dust[num131].noGravity = true;
                Dust dust2 = Main.dust[num131];
                dust2.velocity *= 0.5f;
                dust2 = Main.dust[num131];
                dust2.velocity += vector26 * (0.6f + 0.6f * Main.rand.NextFloat());
            }
        }
        else if (type == 651)
        {
            if (localAI[0] == 1f && owner == Main.myPlayer)
            {
                Player master = Main.player[owner];
                Point ps = new Vector2(ai[0], ai[1]).ToPoint();
                Point pe = base.Center.ToTileCoordinates();
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(109, -1, -1, null, ps.X, ps.Y, pe.X, pe.Y, (int)WiresUI.Settings.ToolMode);
                }
                else
                {
                    Wiring.MassWireOperation(ps, pe, master);
                }
            }
        }
        else if (type == 641)
        {
            if (owner == Main.myPlayer)
            {
                for (int num132 = 0; num132 < 1000; num132++)
                {
                    if (Main.projectile[num132].active && Main.projectile[num132].owner == owner && Main.projectile[num132].type == 642)
                    {
                        Main.projectile[num132].Kill();
                    }
                }
            }
        }
        else if (type == 643)
        {
            if (owner == Main.myPlayer)
            {
                for (int num133 = 0; num133 < 1000; num133++)
                {
                    if (Main.projectile[num133].active && Main.projectile[num133].owner == owner && Main.projectile[num133].type == 644)
                    {
                        Main.projectile[num133].Kill();
                    }
                }
            }
        }
        else if (type == 645)
        {
            bool flag2 = WorldGen.SolidTile(Framing.GetTileSafely((int)position.X / 16, (int)position.Y / 16));
            for (int num134 = 0; num134 < 4; num134++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
            }
            for (int num135 = 0; num135 < 4; num135++)
            {
                int num136 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229, 0f, 0f, 0, default(Color), 2.5f);
                Main.dust[num136].noGravity = true;
                Dust dust2 = Main.dust[num136];
                dust2.velocity *= 3f;
                if (flag2)
                {
                    Main.dust[num136].noLight = true;
                }
                num136 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229, 0f, 0f, 100, default(Color), 1.5f);
                dust2 = Main.dust[num136];
                dust2.velocity *= 2f;
                Main.dust[num136].noGravity = true;
                if (flag2)
                {
                    Main.dust[num136].noLight = true;
                }
            }
            for (int num137 = 0; num137 < 1; num137++)
            {
                int num138 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num138];
                gore2.velocity *= 0.3f;
                Main.gore[num138].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num138].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
        }
        else if (type == 636)
        {
            Rectangle hitbox2 = base.Hitbox;
            for (int num139 = 0; num139 < 6; num139 += 3)
            {
                hitbox2.X = (int)oldPos[num139].X;
                hitbox2.Y = (int)oldPos[num139].Y;
                for (int num140 = 0; num140 < 5; num140++)
                {
                    int num141 = Utils.SelectRandom<int>(Main.rand, 6, 259, 158);
                    int num142 = Dust.NewDust(hitbox2.TopLeft(), width, height, num141, 2.5f * (float)direction, -2.5f);
                    Main.dust[num142].alpha = 200;
                    Dust dust2 = Main.dust[num142];
                    dust2.velocity *= 2.4f;
                    dust2 = Main.dust[num142];
                    dust2.scale += Main.rand.NextFloat();
                }
            }
            if (Main.myPlayer == owner)
            {
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 953, damage, 10f, owner, 0f, 0.85f + Main.rand.NextFloat() * 1.15f);
            }
        }
        else if (type == 614)
        {
            for (int num143 = 0; num143 < 10; num143++)
            {
                Dust dust31 = Main.dust[Dust.NewDust(position, width, height, 229)];
                dust31.noGravity = true;
                Dust dust2 = dust31;
                dust2.velocity *= 3f;
            }
        }
        if (type == 644)
        {
            DoRainbowCrystalStaffExplosion();
            if (Main.myPlayer == owner)
            {
                friendly = true;
                int num144 = width;
                int num145 = height;
                int num146 = penetrate;
                position = base.Center;
                width = (height = 60);
                base.Center = position;
                penetrate = -1;
                maxPenetrate = -1;
                Damage();
                penetrate = num146;
                position = base.Center;
                width = num144;
                height = num145;
                base.Center = position;
            }
        }
        if (type == 608)
        {
            maxPenetrate = -1;
            penetrate = -1;
            Damage();
            SoundEngine.PlaySound(SoundID.Item14, position);
            for (int num147 = 0; num147 < 4; num147++)
            {
                int num148 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num148].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
            }
            for (int num149 = 0; num149 < 30; num149++)
            {
                int num150 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 200, default(Color), 3.7f);
                Main.dust[num150].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Main.dust[num150].noGravity = true;
                Dust dust2 = Main.dust[num150];
                dust2.velocity *= 3f;
                Main.dust[num150].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].ArmorSetDye(), Main.player[owner]);
                num150 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num150].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                dust2 = Main.dust[num150];
                dust2.velocity *= 2f;
                Main.dust[num150].noGravity = true;
                Main.dust[num150].fadeIn = 2.5f;
                Main.dust[num150].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].ArmorSetDye(), Main.player[owner]);
            }
            for (int num151 = 0; num151 < 10; num151++)
            {
                int num152 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.7f);
                Main.dust[num152].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num152].noGravity = true;
                Dust dust2 = Main.dust[num152];
                dust2.velocity *= 3f;
                Main.dust[num152].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].ArmorSetDye(), Main.player[owner]);
            }
            for (int num153 = 0; num153 < 10; num153++)
            {
                int num154 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num154].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num154].noGravity = true;
                Dust dust2 = Main.dust[num154];
                dust2.velocity *= 3f;
            }
            for (int num155 = 0; num155 < 2; num155++)
            {
                int num156 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Main.gore[num156].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Gore gore2 = Main.gore[num156];
                gore2.velocity *= 0.3f;
                Main.gore[num156].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num156].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
        }
        else if (type == 661)
        {
            position = base.Center;
            width = (height = 160);
            base.Center = position;
            maxPenetrate = -1;
            penetrate = -1;
            Damage();
            SoundEngine.PlaySound(SoundID.Item14, position);
            Vector2 vector27 = base.Center + Vector2.One * -20f;
            int num157 = 40;
            int num158 = num157;
            for (int num159 = 0; num159 < 4; num159++)
            {
                int num160 = Dust.NewDust(vector27, num157, num158, 240, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num160].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * num157 / 2f;
            }
            for (int num161 = 0; num161 < 20; num161++)
            {
                int num162 = Dust.NewDust(vector27, num157, num158, 62, 0f, 0f, 200, default(Color), 3.7f);
                Main.dust[num162].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * num157 / 2f;
                Main.dust[num162].noGravity = true;
                Main.dust[num162].noLight = true;
                Dust dust2 = Main.dust[num162];
                dust2.velocity *= 3f;
                dust2 = Main.dust[num162];
                dust2.velocity += DirectionTo(Main.dust[num162].position) * (2f + Main.rand.NextFloat() * 4f);
                num162 = Dust.NewDust(vector27, num157, num158, 62, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num162].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * num157 / 2f;
                dust2 = Main.dust[num162];
                dust2.velocity *= 2f;
                Main.dust[num162].noGravity = true;
                Main.dust[num162].fadeIn = 1f;
                Main.dust[num162].color = Color.Crimson * 0.5f;
                Main.dust[num162].noLight = true;
                dust2 = Main.dust[num162];
                dust2.velocity += DirectionTo(Main.dust[num162].position) * 8f;
            }
            for (int num163 = 0; num163 < 20; num163++)
            {
                int num164 = Dust.NewDust(vector27, num157, num158, 62, 0f, 0f, 0, default(Color), 2.7f);
                Main.dust[num164].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * num157 / 2f;
                Main.dust[num164].noGravity = true;
                Main.dust[num164].noLight = true;
                Dust dust2 = Main.dust[num164];
                dust2.velocity *= 3f;
                dust2 = Main.dust[num164];
                dust2.velocity += DirectionTo(Main.dust[num164].position) * 2f;
            }
            for (int num165 = 0; num165 < 70; num165++)
            {
                int num166 = Dust.NewDust(vector27, num157, num158, 240, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num166].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * num157 / 2f;
                Main.dust[num166].noGravity = true;
                Dust dust2 = Main.dust[num166];
                dust2.velocity *= 3f;
                dust2 = Main.dust[num166];
                dust2.velocity += DirectionTo(Main.dust[num166].position) * 3f;
            }
        }
        else if (type == 617)
        {
            position = base.Center;
            width = (height = 176);
            base.Center = position;
            maxPenetrate = -1;
            penetrate = -1;
            Damage();
            SoundEngine.PlaySound(SoundID.Item14, position);
            for (int num167 = 0; num167 < 4; num167++)
            {
                int num168 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 240, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num168].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
            }
            for (int num169 = 0; num169 < 30; num169++)
            {
                int num170 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 62, 0f, 0f, 200, default(Color), 3.7f);
                Main.dust[num170].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Main.dust[num170].noGravity = true;
                Dust dust2 = Main.dust[num170];
                dust2.velocity *= 3f;
                num170 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 90, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num170].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                dust2 = Main.dust[num170];
                dust2.velocity *= 2f;
                Main.dust[num170].noGravity = true;
                Main.dust[num170].fadeIn = 1f;
                Main.dust[num170].color = Color.Crimson * 0.5f;
            }
            for (int num171 = 0; num171 < 10; num171++)
            {
                int num172 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 62, 0f, 0f, 0, default(Color), 2.7f);
                Main.dust[num172].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num172].noGravity = true;
                Dust dust2 = Main.dust[num172];
                dust2.velocity *= 3f;
            }
            for (int num173 = 0; num173 < 10; num173++)
            {
                int num174 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 240, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num174].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num174].noGravity = true;
                Dust dust2 = Main.dust[num174];
                dust2.velocity *= 3f;
            }
            for (int num175 = 0; num175 < 2; num175++)
            {
                int num176 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Main.gore[num176].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Gore gore2 = Main.gore[num176];
                gore2.velocity *= 0.3f;
                Main.gore[num176].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num176].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
            if (Main.myPlayer == owner)
            {
                for (int num177 = 0; num177 < 1000; num177++)
                {
                    if (Main.projectile[num177].active && Main.projectile[num177].type == 618 && Main.projectile[num177].ai[1] == (float)whoAmI)
                    {
                        Main.projectile[num177].Kill();
                    }
                }
                int num178 = Main.rand.Next(5, 9);
                int num179 = Main.rand.Next(5, 9);
                int num180 = Utils.SelectRandom<int>(Main.rand, 86, 90);
                int num181 = ((num180 == 86) ? 90 : 86);
                for (int num182 = 0; num182 < num178; num182++)
                {
                    Vector2 vector28 = base.Center + Utils.RandomVector2(Main.rand, -30f, 30f);
                    Vector2 vector29 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    while (vector29.X == 0f && vector29.Y == 0f)
                    {
                        vector29 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    }
                    vector29.Normalize();
                    if (vector29.Y > 0.2f)
                    {
                        vector29.Y *= -1f;
                    }
                    vector29 *= (float)Main.rand.Next(70, 101) * 0.1f;
                    NewProjectile(GetProjectileSource_FromThis(), vector28.X, vector28.Y, vector29.X, vector29.Y, 620, (int)((double)damage * 0.65), knockBack * 0.8f, owner, num180);
                }
                for (int num183 = 0; num183 < num179; num183++)
                {
                    Vector2 vector30 = base.Center + Utils.RandomVector2(Main.rand, -30f, 30f);
                    Vector2 vector31 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    while (vector31.X == 0f && vector31.Y == 0f)
                    {
                        vector31 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    }
                    vector31.Normalize();
                    if (vector31.Y > 0.4f)
                    {
                        vector31.Y *= -1f;
                    }
                    vector31 *= (float)Main.rand.Next(40, 81) * 0.1f;
                    NewProjectile(GetProjectileSource_FromThis(), vector30.X, vector30.Y, vector31.X, vector31.Y, 620, (int)((double)damage * 0.65), knockBack * 0.8f, owner, num181);
                }
            }
        }
        else if (type == 658)
        {
            for (int num184 = 0; num184 < 10; num184++)
            {
                int num185 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 269, velocity.X * 0.1f, velocity.Y * 0.1f, 0, default(Color), 0.5f);
                Dust dust2;
                if (Main.rand.Next(3) == 0)
                {
                    Main.dust[num185].fadeIn = 0.75f + (float)Main.rand.Next(-10, 11) * 0.01f;
                    Main.dust[num185].scale = 0.25f + (float)Main.rand.Next(-10, 11) * 0.005f;
                    dust2 = Main.dust[num185];
                    dust2.type++;
                }
                else
                {
                    Main.dust[num185].scale = 1f + (float)Main.rand.Next(-10, 11) * 0.01f;
                }
                Main.dust[num185].noGravity = true;
                dust2 = Main.dust[num185];
                dust2.velocity *= 1.25f;
                dust2 = Main.dust[num185];
                dust2.velocity -= oldVelocity / 10f;
            }
        }
        else if (type == 620 || type == 618)
        {
            if (type == 618)
            {
                ai[0] = 86f;
            }
            for (int num186 = 0; num186 < 10; num186++)
            {
                int num187 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, (int)ai[0], velocity.X * 0.1f, velocity.Y * 0.1f, 0, default(Color), 0.5f);
                Dust dust2;
                if (Main.rand.Next(3) == 0)
                {
                    Main.dust[num187].fadeIn = 0.75f + (float)Main.rand.Next(-10, 11) * 0.01f;
                    Main.dust[num187].scale = 0.25f + (float)Main.rand.Next(-10, 11) * 0.005f;
                    dust2 = Main.dust[num187];
                    dust2.type++;
                }
                else
                {
                    Main.dust[num187].scale = 1f + (float)Main.rand.Next(-10, 11) * 0.01f;
                }
                Main.dust[num187].noGravity = true;
                dust2 = Main.dust[num187];
                dust2.velocity *= 1.25f;
                dust2 = Main.dust[num187];
                dust2.velocity -= oldVelocity / 10f;
            }
        }
        else if (type == 619)
        {
            SoundEngine.PlaySound(SoundID.Item50, position);
            for (int num188 = 0; num188 < 20; num188++)
            {
                int num189 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, (int)ai[0], velocity.X * 0.1f, velocity.Y * 0.1f, 0, default(Color), 0.5f);
                Dust dust2;
                if (Main.rand.Next(3) == 0)
                {
                    Main.dust[num189].fadeIn = 1.1f + (float)Main.rand.Next(-10, 11) * 0.01f;
                    Main.dust[num189].scale = 0.35f + (float)Main.rand.Next(-10, 11) * 0.01f;
                    dust2 = Main.dust[num189];
                    dust2.type++;
                }
                else
                {
                    Main.dust[num189].scale = 1.2f + (float)Main.rand.Next(-10, 11) * 0.01f;
                }
                Main.dust[num189].noGravity = true;
                dust2 = Main.dust[num189];
                dust2.velocity *= 2.5f;
                dust2 = Main.dust[num189];
                dust2.velocity -= oldVelocity / 10f;
            }
            if (Main.myPlayer == owner)
            {
                int num190 = Main.rand.Next(3, 6);
                for (int num191 = 0; num191 < num190; num191++)
                {
                    Vector2 vector32 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    while (vector32.X == 0f && vector32.Y == 0f)
                    {
                        vector32 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    }
                    vector32.Normalize();
                    vector32 *= (float)Main.rand.Next(70, 101) * 0.1f;
                    NewProjectile(GetProjectileSource_FromThis(), oldPosition.X + (float)(width / 2), oldPosition.Y + (float)(height / 2), vector32.X, vector32.Y, 620, (int)((double)damage * 0.8), knockBack * 0.8f, owner, ai[0]);
                }
            }
        }
        if (type == 601)
        {
            Color portalColor = PortalHelper.GetPortalColor(owner, (int)ai[0]);
            Color color = portalColor;
            color.A = byte.MaxValue;
            for (int num192 = 0; num192 < 6; num192++)
            {
                Vector2 vector33 = Vector2.UnitY.RotatedByRandom(6.2831854820251465) * (3f * Main.rand.NextFloat());
                Dust dust32 = Main.dust[Dust.NewDust(base.Center, 0, 0, 263)];
                dust32.position = base.Center;
                dust32.velocity = vector33 + velocity / 5f;
                dust32.color = color;
                dust32.scale = 2f;
                dust32.noLight = true;
                dust32.noGravity = true;
            }
        }
        if (type == 596)
        {
            position = base.Center;
            width = (height = 60);
            base.Center = position;
            int num193 = 30;
            if (Main.expertMode)
            {
                num193 = 22;
            }
            damage = num193;
            Damage();
            SoundEngine.PlaySound(SoundID.Item14, position);
            for (int num194 = 0; num194 < 4; num194++)
            {
                int num195 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num195].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
            }
            for (int num196 = 0; num196 < 20; num196++)
            {
                int num197 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 27, 0f, 0f, 0, default(Color), 2.5f);
                Main.dust[num197].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Main.dust[num197].noGravity = true;
                Dust dust2 = Main.dust[num197];
                dust2.velocity *= 2f;
            }
            for (int num198 = 0; num198 < 10; num198++)
            {
                int num199 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num199].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num199].noGravity = true;
                Dust dust2 = Main.dust[num199];
                dust2.velocity *= 2f;
            }
        }
        if (type == 659)
        {
            if (ai[0] >= 0f)
            {
                int num200 = 80;
                position = base.Center;
                width = (height = num200);
                base.Center = position;
                Damage();
                SoundEngine.PlaySound(SoundID.Item14, position);
                int num201 = 15;
                int num202 = num201 + 15;
                for (int num203 = 0; num203 < num202; num203++)
                {
                    int num204 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 27, 0f, 0f, 0, default(Color), 2f + Main.rand.NextFloat() * 0.5f);
                    Main.dust[num204].noGravity = true;
                    if (num203 < num201)
                    {
                        float num205 = (float)(num203 + 1) / (float)num201 * ((float)Math.PI * 2f);
                        Main.dust[num204].fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                        Main.dust[num204].position = base.Center;
                        Main.dust[num204].velocity = Vector2.UnitY.RotatedBy(num205) * (5f + Main.rand.NextFloat() * 1.5f);
                    }
                    else
                    {
                        Main.dust[num204].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * Main.rand.NextFloat() * width / 3f;
                        Main.dust[num204].fadeIn = 0.5f + Main.rand.NextFloat() * 0.5f;
                        Dust dust2 = Main.dust[num204];
                        dust2.velocity *= 2f;
                    }
                }
                for (int num206 = 0; num206 < 10; num206++)
                {
                    int num207 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                    Main.dust[num207].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 3f;
                    Main.dust[num207].fadeIn = 0.5f + Main.rand.NextFloat() * 0.5f;
                    Main.dust[num207].noGravity = true;
                    Dust dust2 = Main.dust[num207];
                    dust2.velocity *= 1.5f;
                }
            }
        }
        else if (type >= 625 && type <= 628)
        {
            for (int num208 = 0; num208 < 6; num208++)
            {
                int num209 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100, default(Color), 2f);
                Main.dust[num209].noGravity = true;
                Main.dust[num209].noLight = true;
            }
        }
        if (type == 631)
        {
            int num210 = Main.rand.Next(5, 10);
            for (int num211 = 0; num211 < num210; num211++)
            {
                int num212 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100);
                Dust dust2 = Main.dust[num212];
                dust2.velocity *= 1.6f;
                Main.dust[num212].velocity.Y -= 1f;
                dust2 = Main.dust[num212];
                dust2.position -= Vector2.One * 4f;
                Main.dust[num212].position = Vector2.Lerp(Main.dust[num212].position, base.Center, 0.5f);
                Main.dust[num212].noGravity = true;
            }
        }
        if (type == 539)
        {
            position = base.Center;
            width = (height = 80);
            base.Center = position;
            Damage();
            SoundEngine.PlaySound(4, (int)position.X, (int)position.Y, 7);
            for (int num213 = 0; num213 < 4; num213++)
            {
                int num214 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num214].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
            }
            for (int num215 = 0; num215 < 20; num215++)
            {
                int num216 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 176, 0f, 0f, 200, default(Color), 3.7f);
                Main.dust[num216].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Main.dust[num216].noGravity = true;
                Dust dust2 = Main.dust[num216];
                dust2.velocity *= 3f;
            }
            for (int num217 = 0; num217 < 20; num217++)
            {
                int num218 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 180, 0f, 0f, 0, default(Color), 2.7f);
                Main.dust[num218].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num218].noGravity = true;
                Dust dust2 = Main.dust[num218];
                dust2.velocity *= 3f;
            }
            for (int num219 = 0; num219 < 10; num219++)
            {
                int num220 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num220].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num220].noGravity = true;
                Dust dust2 = Main.dust[num220];
                dust2.velocity *= 3f;
            }
        }
        else if (type == 585)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y, 27);
            for (int num221 = 0; num221 < 20; num221++)
            {
                int num222 = Dust.NewDust(position, width, height, 26, 0f, 0f, 100);
                Main.dust[num222].noGravity = true;
                Dust dust2 = Main.dust[num222];
                dust2.velocity *= 1.2f;
                Main.dust[num222].scale = 1.3f;
                dust2 = Main.dust[num222];
                dust2.velocity -= oldVelocity * 0.3f;
                num222 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, 27, 0f, 0f, 100, default(Color), 2f);
                Main.dust[num222].noGravity = true;
                dust2 = Main.dust[num222];
                dust2.velocity *= 3f;
            }
        }
        else if (type == 590)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y, 27);
            int num223 = 165;
            if (ai[2] == 1f)
            {
                num223 = 31;
            }
            for (int num224 = 0; num224 < 10; num224++)
            {
                int num225 = Dust.NewDust(position, width, height, num223, 0f, 0f, 50, default(Color), 1.5f);
                Dust dust2 = Main.dust[num225];
                dust2.velocity *= 2f;
                Main.dust[num225].noGravity = true;
            }
            float num226 = 0.6f + Main.rand.NextFloat() * 0.4f;
            int num227 = 375;
            if (ai[2] == 1f)
            {
                num227 = 61;
            }
            int num228 = Gore.NewGore(position, Vector2.Zero, num227, num226);
            Gore gore2 = Main.gore[num228];
            gore2.velocity *= 0.3f;
            num228 = Gore.NewGore(position, Vector2.Zero, num227 + 1, num226);
            gore2 = Main.gore[num228];
            gore2.velocity *= 0.3f;
            num228 = Gore.NewGore(position, Vector2.Zero, num227 + 2, num226);
            gore2 = Main.gore[num228];
            gore2.velocity *= 0.3f;
        }
        else if (type == 587)
        {
            Color newColor5 = Main.hslToRgb(ai[1], 1f, 0.5f);
            newColor5.A = 200;
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num229 = 0; num229 < 10; num229++)
            {
                int num230 = Dust.NewDust(position, width, height, 76, 0f, 0f, 0, newColor5);
                Main.dust[num230].noGravity = true;
                Dust dust2 = Main.dust[num230];
                dust2.velocity *= 1.2f;
                Main.dust[num230].scale = 0.9f;
                dust2 = Main.dust[num230];
                dust2.velocity -= oldVelocity * 0.3f;
                num230 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, 76, 0f, 0f, 0, newColor5, 1.1f);
                Main.dust[num230].noGravity = true;
                dust2 = Main.dust[num230];
                dust2.velocity *= 2f;
            }
        }
        else if (type == 572)
        {
            for (int num231 = 0; num231 < 15; num231++)
            {
                int num232 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 40, velocity.X * 0.1f, velocity.Y * 0.1f, 100);
                Dust dust2 = Main.dust[num232];
                dust2.velocity *= 3f;
                Main.dust[num232].noGravity = true;
                Main.dust[num232].scale = 1.25f;
                Main.dust[num232].position = (base.Center + position) / 2f;
            }
        }
        else if (type == 581)
        {
            for (int num233 = 0; num233 < 30; num233++)
            {
                int num234 = Utils.SelectRandom<int>(Main.rand, 229, 229, 161);
                Dust dust33 = Main.dust[Dust.NewDust(position, width, height, num234)];
                dust33.noGravity = true;
                dust33.scale = 1.25f + Main.rand.NextFloat();
                dust33.fadeIn = 0.25f;
                Dust dust2 = dust33;
                dust2.velocity *= 2f;
                dust33.noLight = true;
            }
        }
        else if (type == 671)
        {
            for (int num235 = 0; num235 < 30; num235++)
            {
                int num236 = Utils.SelectRandom<int>(Main.rand, 27, 27, 62);
                Dust dust34 = Main.dust[Dust.NewDust(position, width, height, num236)];
                dust34.noGravity = true;
                dust34.scale = 1.25f + Main.rand.NextFloat();
                dust34.fadeIn = 0.25f;
                Dust dust2 = dust34;
                dust2.velocity *= 2f;
                dust34.noLight = true;
            }
        }
        else if (type == 811 || type == 814)
        {
            for (int num237 = 0; num237 < 30; num237++)
            {
                Dust dust35 = Main.dust[Dust.NewDust(position, width, height, 5)];
                dust35.scale = 1.25f + Main.rand.NextFloat();
                Dust dust2 = dust35;
                dust2.velocity *= 2f;
            }
        }
        else if (type == 819)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num238 = 0; num238 < 20; num238++)
            {
                Dust dust36 = Main.dust[Dust.NewDust(position, width, height, 5)];
                dust36.scale = 1f + Main.rand.NextFloat() * 0.5f;
                Dust dust2 = dust36;
                dust2.velocity *= 1.5f;
            }
        }
        else if (type == 675)
        {
            for (int num239 = 0; num239 < 40; num239++)
            {
                int num240 = Utils.SelectRandom<int>(Main.rand, 27, 242, 73, 72, 71, 255, 255, 255);
                Dust dust37 = Main.dust[Dust.NewDust(position, width, height, num240)];
                dust37.noGravity = true;
                dust37.scale = 1.25f + Main.rand.NextFloat();
                dust37.fadeIn = 0.25f;
                Dust dust2 = dust37;
                dust2.velocity *= 3f;
                dust37.noLight = true;
            }
        }
        else if (type == 676)
        {
            for (int num241 = 0; num241 < 120; num241++)
            {
                int num242 = Utils.SelectRandom<int>(Main.rand, 4, 256);
                Dust dust38 = Main.dust[Dust.NewDust(position, width, height, num242, 0f, 0f, 100)];
                dust38.scale = 0.8f + Main.rand.NextFloat() * 0.6f;
                dust38.fadeIn = 0.5f;
                Dust dust2 = dust38;
                dust2.velocity *= 4.5f;
                dust38.noLight = true;
                if (dust38.velocity.Y > 0f)
                {
                    dust2 = dust38;
                    dust2.velocity *= -0.5f;
                }
                if (dust38.type == 4)
                {
                    dust38.color = new Color(80, 170, 40, 120);
                }
            }
            for (int num243 = 0; num243 < 10; num243++)
            {
                Gore.NewGoreDirect(base.Center, new Vector2(MathHelper.Lerp(-5f, 5f, Main.rand.NextFloat()), (0f - Main.rand.NextFloat()) * 5f), 1024);
            }
            for (int num244 = 0; num244 < 10; num244++)
            {
                Gore.NewGoreDirect(base.Center, new Vector2(MathHelper.Lerp(-5f, 5f, Main.rand.NextFloat()), (0f - Main.rand.NextFloat()) * 5f), 1025);
            }
            for (int num245 = 0; num245 < 10; num245++)
            {
                Gore.NewGoreDirect(base.Center, new Vector2(MathHelper.Lerp(-5f, 5f, Main.rand.NextFloat()), (0f - Main.rand.NextFloat()) * 5f), 1026);
            }
            for (int num246 = 0; num246 < 20; num246++)
            {
                Gore.NewGoreDirect(base.Center, new Vector2(MathHelper.Lerp(-0.5f, 0.5f, Main.rand.NextFloat()), (0f - Main.rand.NextFloat()) * 2f), 1026);
            }
            if (Main.netMode != 2)
            {
                Player player = Main.player[Main.myPlayer];
                if (!player.dead && player.active && (player.Center - base.Center).Length() < 300f && !player.creativeGodMode)
                {
                    player.AddBuff(197, 900, quiet: false);
                }
            }
        }
        else if (type == 686)
        {
            Rectangle hitbox3 = base.Hitbox;
            for (int num247 = 0; num247 < oldPos.Length / 2; num247 += 2)
            {
                hitbox3.X = (int)oldPos[num247].X;
                hitbox3.Y = (int)oldPos[num247].Y;
                for (int num248 = 0; num248 < 3; num248++)
                {
                    int num249 = Utils.SelectRandom<int>(Main.rand, 6, 55, 158);
                    int num250 = Dust.NewDust(hitbox3.TopLeft(), width, height, num249, direction, -2.5f);
                    Main.dust[num250].alpha = 200;
                    Dust dust2 = Main.dust[num250];
                    dust2.velocity *= 2.4f;
                    dust2 = Main.dust[num250];
                    dust2.scale += Main.rand.NextFloat();
                    dust2 = Main.dust[num250];
                    dust2.scale -= 0.5f;
                    if (Main.dust[num250].type == 55)
                    {
                        Main.dust[num250].color = Color.Lerp(Color.Red, Color.Gold, Main.rand.NextFloat());
                    }
                    Main.dust[num250].noLight = true;
                }
            }
            for (int num251 = 10; num251 < oldPos.Length; num251 += 2)
            {
                hitbox3.X = (int)oldPos[num251].X;
                hitbox3.Y = (int)oldPos[num251].Y;
                for (int num252 = 0; num252 < 2; num252++)
                {
                    int num253 = Utils.SelectRandom<int>(Main.rand, 55);
                    int num254 = Dust.NewDust(hitbox3.TopLeft(), width, height, num253, direction, -2.5f);
                    Main.dust[num254].alpha = 120;
                    Dust dust2 = Main.dust[num254];
                    dust2.velocity *= 2.4f;
                    dust2 = Main.dust[num254];
                    dust2.scale += Main.rand.NextFloat() * 0.7f;
                    dust2 = Main.dust[num254];
                    dust2.scale -= 0.5f;
                    if (Main.dust[num254].type == 55)
                    {
                        Main.dust[num254].color = Color.Lerp(Color.Purple, Color.Black, Main.rand.NextFloat());
                    }
                    Main.dust[num254].noLight = true;
                }
            }
            for (int num255 = 5; num255 < oldPos.Length; num255++)
            {
                hitbox3.X = (int)oldPos[num255].X;
                hitbox3.Y = (int)oldPos[num255].Y;
                for (int num256 = 0; num256 < 1; num256++)
                {
                    int num257 = Utils.SelectRandom<int>(Main.rand, 55);
                    int num258 = Dust.NewDust(hitbox3.TopLeft(), width, height, num257, direction, -2.5f);
                    Main.dust[num258].alpha = 80;
                    Dust dust2 = Main.dust[num258];
                    dust2.velocity *= 0.3f;
                    dust2 = Main.dust[num258];
                    dust2.velocity += velocity * 0.5f;
                    dust2 = Main.dust[num258];
                    dust2.scale += Main.rand.NextFloat() * 0.7f;
                    dust2 = Main.dust[num258];
                    dust2.scale -= 0.5f;
                    if (Main.dust[num258].type == 55)
                    {
                        Main.dust[num258].color = Color.Lerp(Color.Purple, Color.Black, Main.rand.NextFloat());
                    }
                    Main.dust[num258].noLight = true;
                }
            }
            for (int num259 = 0; num259 < 30; num259++)
            {
                int num260 = 228;
                Dust dust39 = Main.dust[Dust.NewDust(position, width, height, num260)];
                dust39.noGravity = true;
                dust39.scale = 1.25f + Main.rand.NextFloat();
                dust39.fadeIn = 1.5f;
                Dust dust2 = dust39;
                dust2.velocity *= 6f;
                dust39.noLight = true;
            }
        }
        if (type == 405)
        {
            SoundEngine.PlaySound(SoundID.Item54, position);
            _ = base.Center;
            for (int num261 = 0; num261 < 20; num261++)
            {
                int num262 = 10;
                int num263 = Dust.NewDust(base.Center - Vector2.One * num262, num262 * 2, num262 * 2, 212);
                Dust dust40 = Main.dust[num263];
                Vector2 vector34 = Vector2.Normalize(dust40.position - base.Center);
                dust40.position = base.Center + vector34 * num262 * scale;
                if (num261 < 30)
                {
                    dust40.velocity = vector34 * dust40.velocity.Length();
                }
                else
                {
                    dust40.velocity = vector34 * Main.rand.Next(45, 91) / 10f;
                }
                dust40.color = Main.hslToRgb((float)(0.4000000059604645 + Main.rand.NextDouble() * 0.20000000298023224), 0.9f, 0.5f);
                dust40.color = Color.Lerp(dust40.color, Color.White, 0.3f);
                dust40.noGravity = true;
                dust40.scale = 0.7f;
            }
        }
        if (type == 501)
        {
            SoundEngine.PlaySound(13, (int)position.X, (int)position.Y);
            int num264 = 20;
            position.X -= num264;
            position.Y -= num264;
            width += num264 * 2;
            height += num264 * 2;
            num264 += 20;
            for (int num265 = 0; num265 < 20; num265++)
            {
                int num266 = Dust.NewDust(position, width, height, 188, 0f, 0f, 100, default(Color), 1.5f);
                Dust dust2 = Main.dust[num266];
                dust2.velocity *= 0.5f;
            }
            for (int num267 = 0; num267 < 5; num267++)
            {
                int num268 = Gore.NewGore(new Vector2(position.X + (float)Main.rand.Next(width), position.Y + (float)Main.rand.Next(height)), default(Vector2), Main.rand.Next(435, 438));
                Gore gore2 = Main.gore[num268];
                gore2.velocity *= 0.5f;
                switch (num267)
                {
                case 0:
                    Main.gore[num268].velocity.X += 1f;
                    Main.gore[num268].velocity.Y += 1f;
                    break;
                case 1:
                    Main.gore[num268].velocity.X -= 1f;
                    Main.gore[num268].velocity.Y += 1f;
                    break;
                case 2:
                    Main.gore[num268].velocity.X += 1f;
                    Main.gore[num268].velocity.Y -= 1f;
                    break;
                default:
                    Main.gore[num268].velocity.X -= 1f;
                    Main.gore[num268].velocity.Y -= 1f;
                    break;
                }
                gore2 = Main.gore[num268];
                gore2.velocity *= 0.5f;
            }
            position.X -= num264;
            position.Y -= num264;
            width += num264 * 2;
            height += num264 * 2;
            Damage();
        }
        if (type == 410)
        {
            SoundEngine.PlaySound(SoundID.Item54, position);
            _ = base.Center;
            for (int num269 = 0; num269 < 10; num269++)
            {
                int num270 = (int)(10f * ai[1]);
                int num271 = Dust.NewDust(base.Center - Vector2.One * num270, num270 * 2, num270 * 2, 212);
                Dust dust41 = Main.dust[num271];
                Vector2 vector35 = Vector2.Normalize(dust41.position - base.Center);
                dust41.position = base.Center + vector35 * num270 * scale;
                if (num269 < 30)
                {
                    dust41.velocity = vector35 * dust41.velocity.Length();
                }
                else
                {
                    dust41.velocity = vector35 * Main.rand.Next(45, 91) / 10f;
                }
                dust41.color = Main.hslToRgb((float)(0.4000000059604645 + Main.rand.NextDouble() * 0.20000000298023224), 0.9f, 0.5f);
                dust41.color = Color.Lerp(dust41.color, Color.White, 0.3f);
                dust41.noGravity = true;
                dust41.scale = 0.7f;
            }
        }
        if (type == 629 && Main.netMode != 1)
        {
            switch (Main.npc[(int)ai[0]].type)
            {
            case 517:
                if (NPC.ShieldStrengthTowerSolar != 0)
                {
                    Main.npc[(int)ai[0]].ai[3] = 1f;
                }
                NPC.ShieldStrengthTowerSolar = (int)MathHelper.Clamp(NPC.ShieldStrengthTowerSolar - 1, 0f, NPC.ShieldStrengthTowerMax);
                break;
            case 422:
                if (NPC.ShieldStrengthTowerVortex != 0)
                {
                    Main.npc[(int)ai[0]].ai[3] = 1f;
                }
                NPC.ShieldStrengthTowerVortex = (int)MathHelper.Clamp(NPC.ShieldStrengthTowerVortex - 1, 0f, NPC.ShieldStrengthTowerMax);
                break;
            case 507:
                if (NPC.ShieldStrengthTowerNebula != 0)
                {
                    Main.npc[(int)ai[0]].ai[3] = 1f;
                }
                NPC.ShieldStrengthTowerNebula = (int)MathHelper.Clamp(NPC.ShieldStrengthTowerNebula - 1, 0f, NPC.ShieldStrengthTowerMax);
                break;
            case 493:
                if (NPC.ShieldStrengthTowerStardust != 0)
                {
                    Main.npc[(int)ai[0]].ai[3] = 1f;
                }
                NPC.ShieldStrengthTowerStardust = (int)MathHelper.Clamp(NPC.ShieldStrengthTowerStardust - 1, 0f, NPC.ShieldStrengthTowerMax);
                break;
            }
            Main.npc[(int)ai[0]].netUpdate = true;
            NetMessage.SendData(101);
        }
        if (aiStyle == 105 && owner == Main.myPlayer && ai[1] == 0f)
        {
            Vector2 vector36 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
            vector36.Normalize();
            vector36 *= 0.3f;
            NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector36.X, vector36.Y, Main.rand.Next(569, 572), damage, 0f, owner);
        }
        if (type == 452)
        {
            SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 103);
            position = base.Center;
            width = (height = 144);
            position.X -= width / 2;
            position.Y -= height / 2;
            for (int num272 = 0; num272 < 4; num272++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
            }
            for (int num273 = 0; num273 < 40; num273++)
            {
                int num274 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229, 0f, 0f, 0, default(Color), 2.5f);
                Main.dust[num274].noGravity = true;
                Dust dust2 = Main.dust[num274];
                dust2.velocity *= 3f;
                num274 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229, 0f, 0f, 100, default(Color), 1.5f);
                dust2 = Main.dust[num274];
                dust2.velocity *= 2f;
                Main.dust[num274].noGravity = true;
            }
            for (int num275 = 0; num275 < 1; num275++)
            {
                int num276 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num276];
                gore2.velocity *= 0.3f;
                Main.gore[num276].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num276].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
            Damage();
        }
        if (type == 454)
        {
            SoundEngine.PlaySound(4, (int)position.X, (int)position.Y, 6);
            position = base.Center;
            width = (height = 208);
            position.X -= width / 2;
            position.Y -= height / 2;
            for (int num277 = 0; num277 < 7; num277++)
            {
                int num278 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num278].position = new Vector2(width / 2, 0f).RotatedBy(6.2831854820251465 * Main.rand.NextDouble()) * (float)Main.rand.NextDouble() + base.Center;
            }
            for (int num279 = 0; num279 < 60; num279++)
            {
                int num280 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229, 0f, 0f, 0, default(Color), 2.5f);
                Main.dust[num280].position = new Vector2(width / 2, 0f).RotatedBy(6.2831854820251465 * Main.rand.NextDouble()) * (float)Main.rand.NextDouble() + base.Center;
                Main.dust[num280].noGravity = true;
                Dust dust2 = Main.dust[num280];
                dust2.velocity *= 1f;
                num280 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num280].position = new Vector2(width / 2, 0f).RotatedBy(6.2831854820251465 * Main.rand.NextDouble()) * (float)Main.rand.NextDouble() + base.Center;
                dust2 = Main.dust[num280];
                dust2.velocity *= 1f;
                Main.dust[num280].noGravity = true;
            }
            for (int num281 = 0; num281 < 3; num281++)
            {
                int num282 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num282];
                gore2.velocity *= 0.3f;
                Main.gore[num282].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num282].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
            Damage();
        }
        if (type == 467)
        {
            position = base.Center;
            width = (height = 176);
            base.Center = position;
            Damage();
            SoundEngine.PlaySound(SoundID.Item14, position);
            for (int num283 = 0; num283 < 4; num283++)
            {
                int num284 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num284].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
            }
            for (int num285 = 0; num285 < 30; num285++)
            {
                int num286 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 200, default(Color), 3.7f);
                Main.dust[num286].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Main.dust[num286].noGravity = true;
                Dust dust2 = Main.dust[num286];
                dust2.velocity *= 3f;
                num286 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num286].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                dust2 = Main.dust[num286];
                dust2.velocity *= 2f;
                Main.dust[num286].noGravity = true;
                Main.dust[num286].fadeIn = 2.5f;
            }
            for (int num287 = 0; num287 < 10; num287++)
            {
                int num288 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.7f);
                Main.dust[num288].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num288].noGravity = true;
                Dust dust2 = Main.dust[num288];
                dust2.velocity *= 3f;
            }
            for (int num289 = 0; num289 < 10; num289++)
            {
                int num290 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num290].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num290].noGravity = true;
                Dust dust2 = Main.dust[num290];
                dust2.velocity *= 3f;
            }
            for (int num291 = 0; num291 < 2; num291++)
            {
                int num292 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Main.gore[num292].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Gore gore2 = Main.gore[num292];
                gore2.velocity *= 0.3f;
                Main.gore[num292].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num292].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
        }
        if (type == 468)
        {
            position = base.Center;
            width = (height = 176);
            base.Center = position;
            Damage();
            SoundEngine.PlaySound(SoundID.Item14, position);
            for (int num293 = 0; num293 < 4; num293++)
            {
                int num294 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num294].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
            }
            for (int num295 = 0; num295 < 20; num295++)
            {
                int num296 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 27, 0f, 0f, 200, default(Color), 3.7f);
                Main.dust[num296].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Main.dust[num296].noGravity = true;
                Dust dust2 = Main.dust[num296];
                dust2.velocity *= 3f;
                num296 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 27, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num296].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                dust2 = Main.dust[num296];
                dust2.velocity *= 2f;
                Main.dust[num296].noGravity = true;
                Main.dust[num296].fadeIn = 2.5f;
            }
            for (int num297 = 0; num297 < 10; num297++)
            {
                int num298 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 27, 0f, 0f, 0, default(Color), 2.7f);
                Main.dust[num298].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num298].noGravity = true;
                Dust dust2 = Main.dust[num298];
                dust2.velocity *= 3f;
            }
            for (int num299 = 0; num299 < 10; num299++)
            {
                int num300 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num300].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                Main.dust[num300].noGravity = true;
                Dust dust2 = Main.dust[num300];
                dust2.velocity *= 3f;
            }
            for (int num301 = 0; num301 < 2; num301++)
            {
                int num302 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Main.gore[num302].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                Gore gore2 = Main.gore[num302];
                gore2.velocity *= 0.3f;
                Main.gore[num302].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num302].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
        }
        if (type == 485)
        {
            for (int num303 = 0; num303 < 15; num303++)
            {
                int num304 = Dust.NewDust(position, width, height, 6);
                Main.dust[num304].noGravity = true;
                Dust dust2 = Main.dust[num304];
                dust2.velocity -= oldVelocity * Main.rand.Next(20, 60) * 0.01f;
            }
        }
        else if (type == 484)
        {
            for (int num305 = 0; num305 < 5; num305++)
            {
                int num306 = Dust.NewDust(position, width, height, 78);
                Main.dust[num306].noGravity = true;
                Dust dust2 = Main.dust[num306];
                dust2.velocity -= oldVelocity / 5f;
                Main.dust[num306].scale = 0.85f;
            }
        }
        else if (type == 483)
        {
            SoundEngine.PlaySound(SoundID.Item14, position);
            if (owner == Main.myPlayer)
            {
                int num307 = Main.rand.Next(4, 8);
                int[] array = new int[num307];
                int num308 = 0;
                for (int num309 = 0; num309 < 200; num309++)
                {
                    if (!Main.npc[num309].CanBeChasedBy(this, ignoreDontTakeDamage: true))
                    {
                        continue;
                    }
                    float num310 = Distance(Main.npc[num309].Center);
                    if (!(num310 > 2000f) && Collision.CanHitLine(position, width, height, Main.npc[num309].position, Main.npc[num309].width, Main.npc[num309].height))
                    {
                        array[num308] = num309;
                        num308++;
                        if (num308 == num307)
{
                            break;
                        }
                    }
                }
                if (num308 > 1)
                {
                    for (int num311 = 0; num311 < 100; num311++)
                    {
                        int num312 = Main.rand.Next(num308);
                        int num313;
                        for (num313 = num312; num313 == num312; num313 = Main.rand.Next(num308))
{
                        }
                        int num314 = array[num312];
                        array[num312] = array[num313];
                        array[num313] = num314;
                    }
                }
                Vector2 vector37 = new Vector2(-1f, -1f);
                for (int num315 = 0; num315 < num308; num315++)
                {
                    Vector2 vector38 = Main.npc[array[num315]].Center - base.Center;
                    vector38.Normalize();
                    vector37 += vector38;
                }
                vector37.Normalize();
                for (int num316 = 0; num316 < num307; num316++)
                {
                    float num317 = Main.rand.Next(8, 15);
                    Vector2 vector39 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    vector39.Normalize();
                    if (num308 > 0)
                    {
                        vector39 += vector37;
                        vector39.Normalize();
                    }
                    vector39 *= num317;
                    if (num308 > 0)
                    {
                        num308--;
                        vector39 = Main.npc[array[num308]].Center - base.Center;
                        vector39.Normalize();
                        vector39 *= num317;
                    }
                    NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector39.X, vector39.Y, 484, (int)((double)damage * 0.7), knockBack * 0.7f, owner);
                }
            }
            for (int num318 = 0; num318 < 20; num318++)
            {
                int num319 = Dust.NewDust(position, width, height, 78);
                Main.dust[num319].noGravity = true;
                Dust dust2 = Main.dust[num319];
                dust2.velocity *= 4f;
            }
            for (int num320 = 0; num320 < 7; num320++)
            {
                int num321 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Dust dust2 = Main.dust[num321];
                dust2.velocity *= 0.9f;
                Main.dust[num321].scale = 0.9f;
            }
            for (int num322 = 0; num322 < 3; num322++)
            {
                int num323 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                Main.dust[num323].noGravity = true;
                Dust dust2 = Main.dust[num323];
                dust2.velocity *= 3f;
                num323 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                dust2 = Main.dust[num323];
                dust2.velocity *= 2f;
            }
            int num324 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
            Gore gore2 = Main.gore[num324];
            gore2.velocity *= 0.3f;
            Main.gore[num324].velocity.X += Main.rand.Next(-1, 2);
            Main.gore[num324].velocity.Y += Main.rand.Next(-1, 2);
            if (owner == Main.myPlayer)
            {
                int num325 = 100;
                position.X -= num325 / 2;
                position.Y -= num325 / 2;
                width += num325;
                height++;
                penetrate = -1;
                Damage();
            }
        }
        if (type == 523)
        {
            SoundEngine.PlaySound(SoundID.Item54, position);
            for (int num326 = 0; num326 < 25; num326++)
            {
                int num327 = Dust.NewDust(position, width, height, 256);
                Main.dust[num327].noGravity = true;
                Main.dust[num327].position = (Main.dust[num327].position + position) / 2f;
                Main.dust[num327].velocity = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                Main.dust[num327].velocity.Normalize();
                Dust dust2 = Main.dust[num327];
                dust2.velocity *= (float)Main.rand.Next(1, 30) * 0.1f;
                Main.dust[num327].alpha = alpha;
            }
        }
        else if (type == 522)
        {
            SoundEngine.PlaySound(SoundID.Item118, position);
            for (int num328 = 0; num328 < 10; num328++)
            {
                int num329 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 254, velocity.X * 0.1f, velocity.Y * 0.1f, 0, default(Color), 0.5f);
                Dust dust2;
                if (Main.rand.Next(3) == 0)
                {
                    Main.dust[num329].fadeIn = 0.75f + (float)Main.rand.Next(-10, 11) * 0.01f;
                    Main.dust[num329].scale = 0.25f + (float)Main.rand.Next(-10, 11) * 0.005f;
                    dust2 = Main.dust[num329];
                    dust2.type++;
                }
                else
                {
                    Main.dust[num329].scale = 1f + (float)Main.rand.Next(-10, 11) * 0.01f;
                }
                Main.dust[num329].noGravity = true;
                dust2 = Main.dust[num329];
                dust2.velocity *= 1.25f;
                dust2 = Main.dust[num329];
                dust2.velocity -= oldVelocity / 10f;
            }
        }
        else if (type == 521)
        {
            SoundEngine.PlaySound(SoundID.Item110, position);
            for (int num330 = 0; num330 < 20; num330++)
            {
                int num331 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 254, velocity.X * 0.1f, velocity.Y * 0.1f, 0, default(Color), 0.5f);
                Dust dust2;
                if (Main.rand.Next(3) == 0)
                {
                    Main.dust[num331].fadeIn = 1.1f + (float)Main.rand.Next(-10, 11) * 0.01f;
                    Main.dust[num331].scale = 0.35f + (float)Main.rand.Next(-10, 11) * 0.01f;
                    dust2 = Main.dust[num331];
                    dust2.type++;
                }
                else
                {
                    Main.dust[num331].scale = 1.2f + (float)Main.rand.Next(-10, 11) * 0.01f;
                }
                Main.dust[num331].noGravity = true;
                dust2 = Main.dust[num331];
                dust2.velocity *= 2.5f;
                dust2 = Main.dust[num331];
                dust2.velocity -= oldVelocity / 10f;
            }
            if (Main.myPlayer == owner)
            {
                int num332 = Main.rand.Next(3, 6);
                for (int num333 = 0; num333 < num332; num333++)
                {
                    Vector2 vector40 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    while (vector40.X == 0f && vector40.Y == 0f)
                    {
                        vector40 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    }
                    vector40.Normalize();
                    vector40 *= (float)Main.rand.Next(70, 101) * 0.1f;
                    NewProjectile(GetProjectileSource_FromThis(), oldPosition.X + (float)(width / 2), oldPosition.Y + (float)(height / 2), vector40.X, vector40.Y, 522, (int)((double)damage * 0.8), knockBack * 0.8f, owner);
                }
            }
        }
        if (type == 520)
        {
            SoundEngine.PlaySound(SoundID.Item50, position);
            for (int num334 = 0; num334 < 10; num334++)
            {
                int num335 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 252, velocity.X * 0.1f, velocity.Y * 0.1f, 0, default(Color), 0.75f);
                Main.dust[num335].noGravity = true;
                Dust dust2 = Main.dust[num335];
                dust2.velocity -= oldVelocity / 3f;
            }
        }
        if (type == 459 || type == 709)
        {
            int num336 = 3;
            int num337 = 10;
            int num338 = 0;
            if (scale >= 1f)
            {
                position = base.Center;
                width = (height = 144);
                base.Center = position;
                num336 = 7;
                num337 = 30;
                num338 = 2;
                Damage();
            }
            for (int num339 = 0; num339 < num336; num339++)
            {
                int num340 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num340].position = new Vector2(width / 2, 0f).RotatedBy(6.2831854820251465 * Main.rand.NextDouble()) * (float)Main.rand.NextDouble() + base.Center;
            }
            for (int num341 = 0; num341 < num337; num341++)
            {
                int num342 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 226, 0f, 0f, 0, default(Color), 1.5f);
                Main.dust[num342].position = new Vector2(width / 2, 0f).RotatedBy(6.2831854820251465 * Main.rand.NextDouble()) * (float)Main.rand.NextDouble() + base.Center;
                Main.dust[num342].noGravity = true;
                Dust dust2 = Main.dust[num342];
                dust2.velocity *= 1f;
            }
            for (int num343 = 0; num343 < num338; num343++)
            {
                int num344 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num344];
                gore2.velocity *= 0.3f;
                Main.gore[num344].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num344].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
            if (type == 709 && Main.myPlayer == owner)
            {
                Rectangle value7 = new Rectangle((int)base.Center.X - 40, (int)base.Center.Y - 40, 80, 80);
                for (int num345 = 0; num345 < 1000; num345++)
                {
                    if (num345 != whoAmI && Main.projectile[num345].active && Main.projectile[num345].owner == owner && Main.projectile[num345].type == 443 && Main.projectile[num345].getRect().Intersects(value7))
                    {
                        Main.projectile[num345].ai[1] = 1f;
                        Main.projectile[num345].velocity = (base.Center - Main.projectile[num345].Center) / 5f;
                        Main.projectile[num345].netUpdate = true;
                    }
                }
                int num346 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 443, damage, 0f, owner);
                Main.projectile[num346].timeLeft = 30 * Main.rand.Next(2, 6);
                float[] array2 = Main.projectile[num346].localAI;
                SlotId val = SoundEngine.PlayTrackedSound(SoundID.DD2_SkyDragonsFuryCircle, base.Center);
                array2[0] = ((SlotId)(ref val)).ToFloat();
            }
        }
        if (owner != Main.myPlayer && type == 453 && Main.player[owner].mount.AbilityActive)
        {
            Main.player[owner].mount.UseAbility(Main.player[owner], position, toggleOn: false);
        }
        if (type == 441)
        {
            Main.player[owner].mount.StopAbilityCharge();
        }
        if (type == 444)
        {
            SoundEngine.PlaySound(SoundID.Item96, position);
            int num347 = Main.rand.Next(5, 9);
            for (int num348 = 0; num348 < num347; num348++)
            {
                int num349 = Dust.NewDust(base.Center, 0, 0, 171, 0f, 0f, 100, default(Color), 1.4f);
                Dust dust2 = Main.dust[num349];
                dust2.velocity *= 0.8f;
                Main.dust[num349].position = Vector2.Lerp(Main.dust[num349].position, base.Center, 0.5f);
                Main.dust[num349].noGravity = true;
            }
            if (owner == Main.myPlayer)
            {
                Vector2 vector41 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY);
                if (Main.player[owner].gravDir == -1f)
                {
                    vector41.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y;
                }
                Vector2 vector42 = Vector2.Normalize(vector41 - base.Center);
                vector42 *= localAI[1];
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector42.X, vector42.Y, (int)localAI[0], damage, knockBack, owner);
            }
        }
        if (type == 472)
        {
            for (int num350 = 0; num350 < 20; num350++)
            {
                int num351 = Dust.NewDust(position, width, height, 30);
                Main.dust[num351].noGravity = true;
                Dust dust2 = Main.dust[num351];
                dust2.velocity *= 0.45f;
                dust2 = Main.dust[num351];
                dust2.velocity += velocity * 0.9f;
            }
        }
        if (type == 639 || type == 640)
        {
            int num352 = Main.rand.Next(5, 10);
            for (int num353 = 0; num353 < num352; num353++)
            {
                int num354 = Dust.NewDust(base.Center, 0, 0, 220, 0f, 0f, 100, default(Color), 0.5f);
                Dust dust2 = Main.dust[num354];
                dust2.velocity *= 1.6f;
                Main.dust[num354].velocity.Y -= 1f;
                Main.dust[num354].position = Vector2.Lerp(Main.dust[num354].position, base.Center, 0.5f);
                Main.dust[num354].noGravity = true;
            }
            if (owner == Main.myPlayer && type == 639)
            {
                int num355 = num + 1;
                int nextSlot = GetNextSlot();
                if (Main.ProjectileUpdateLoopIndex < nextSlot && Main.ProjectileUpdateLoopIndex != -1)
                {
                    num355++;
                }
                Vector2 vector43 = new Vector2(ai[0], ai[1]);
                NewProjectile(GetProjectileSource_FromThis(), localAI[0], localAI[1], vector43.X, vector43.Y, 640, damage, knockBack, owner, 0f, num355);
            }
        }
        if (type == 684)
        {
            int num356 = Main.rand.Next(15, 25);
            for (int num357 = 0; num357 < num356; num357++)
            {
                int num358 = Dust.NewDust(base.Center, 0, 0, 60, 0f, 0f, 100, new Color(255, 255, 255, 0), 1.3f);
                Dust dust2 = Main.dust[num358];
                dust2.velocity *= 8f * (0.3f + 0.7f * Main.rand.NextFloat());
                Main.dust[num358].fadeIn = 1.3f + Main.rand.NextFloat() * 0.2f;
                Main.dust[num358].noLight = true;
                Main.dust[num358].noGravity = true;
                dust2 = Main.dust[num358];
                dust2.position += Main.dust[num358].velocity * 4f;
            }
        }
        if (type == 435)
        {
            int num359 = Main.rand.Next(5, 10);
            for (int num360 = 0; num360 < num359; num360++)
            {
                int num361 = Dust.NewDust(base.Center, 0, 0, 226, 0f, 0f, 100, default(Color), 0.5f);
                Dust dust2 = Main.dust[num361];
                dust2.velocity *= 1.6f;
                Main.dust[num361].velocity.Y -= 1f;
                Main.dust[num361].position = Vector2.Lerp(Main.dust[num361].position, base.Center, 0.5f);
                Main.dust[num361].noGravity = true;
            }
        }
        if (type == 732)
        {
            int num362 = Main.rand.Next(5, 10);
            for (int num363 = 0; num363 < num362; num363++)
            {
                int num364 = Dust.NewDust(base.Center, 0, 0, 226, 0f, 0f, 100, default(Color), 0.5f);
                Dust dust2 = Main.dust[num364];
                dust2.velocity *= 1.6f;
                Main.dust[num364].velocity.Y -= 1f;
                Main.dust[num364].velocity = Main.dust[num364].velocity * 0.5f + velocity * ((float)num363 / (float)num362) * 0.7f;
                Main.dust[num364].position = Vector2.Lerp(Main.dust[num364].position, base.Center, 0.5f);
                Main.dust[num364].noGravity = true;
            }
        }
        if (type == 682)
        {
            int num365 = 22;
            for (int num366 = 0; num366 < num365; num366++)
            {
                int num367 = Dust.NewDust(base.Center, 0, 0, 272, 0f, 0f, 0, default(Color), 0.5f);
                Dust dust2 = Main.dust[num367];
                dust2.velocity *= 1.6f;
                Main.dust[num367].velocity.Y -= 1f;
                Main.dust[num367].position = Vector2.Lerp(Main.dust[num367].position, base.Center, 0.5f);
            }
        }
        if (type == 436)
        {
            int num368 = Main.rand.Next(5, 10);
            for (int num369 = 0; num369 < num368; num369++)
            {
                int num370 = Dust.NewDust(base.Center, 0, 0, 220, 0f, 0f, 100, default(Color), 0.5f);
                Dust dust2 = Main.dust[num370];
                dust2.velocity *= 1.6f;
                Main.dust[num370].velocity.Y -= 1f;
                Main.dust[num370].position = Vector2.Lerp(Main.dust[num370].position, base.Center, 0.5f);
                Main.dust[num370].noGravity = true;
            }
        }
        if (type == 462)
        {
            int num371 = Main.rand.Next(5, 10);
            for (int num372 = 0; num372 < num371; num372++)
            {
                int num373 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, default(Color), 0.5f);
                Dust dust2 = Main.dust[num373];
                dust2.velocity *= 1.6f;
                Main.dust[num373].velocity.Y -= 1f;
                dust2 = Main.dust[num373];
                dust2.position -= Vector2.One * 4f;
                Main.dust[num373].position = Vector2.Lerp(Main.dust[num373].position, base.Center, 0.5f);
                Main.dust[num373].noGravity = true;
            }
        }
        if (type == 442)
        {
            SoundEngine.PlaySound(SoundID.Item94, position);
            int num374 = Main.rand.Next(3, 7);
            for (int num375 = 0; num375 < num374; num375++)
            {
                int num376 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100, default(Color), 2.1f);
                Dust dust2 = Main.dust[num376];
                dust2.velocity *= 2f;
                Main.dust[num376].noGravity = true;
            }
            if (Main.myPlayer == owner)
            {
                Rectangle value8 = new Rectangle((int)base.Center.X - 40, (int)base.Center.Y - 40, 80, 80);
                for (int num377 = 0; num377 < 1000; num377++)
                {
                    if (num377 != whoAmI && Main.projectile[num377].active && Main.projectile[num377].owner == owner && Main.projectile[num377].type == 443 && Main.projectile[num377].getRect().Intersects(value8))
                    {
                        Main.projectile[num377].ai[1] = 1f;
                        Main.projectile[num377].velocity = (base.Center - Main.projectile[num377].Center) / 5f;
                        Main.projectile[num377].netUpdate = true;
                    }
                }
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 443, damage, 0f, owner);
            }
        }
        if (type == 440)
        {
            int num378 = Main.rand.Next(3, 7);
            for (int num379 = 0; num379 < num378; num379++)
            {
                int num380 = Dust.NewDust(base.Center - velocity / 2f, 0, 0, 135, 0f, 0f, 100, default(Color), 2.1f);
                Dust dust2 = Main.dust[num380];
                dust2.velocity *= 2f;
                Main.dust[num380].noGravity = true;
            }
        }
        if (type == 606)
        {
            int num381 = Main.rand.Next(3, 7);
            for (int num382 = 0; num382 < num381; num382++)
            {
                int num383 = Dust.NewDust(base.Center - velocity / 2f, 0, 0, 182, 0f, 0f, 100, default(Color), 1.6f);
                Dust dust2 = Main.dust[num383];
                dust2.velocity *= 1.5f;
                Main.dust[num383].noGravity = true;
            }
        }
        if (type == 449)
        {
            int num384 = Main.rand.Next(3, 7);
            for (int num385 = 0; num385 < num384; num385++)
            {
                int num386 = Dust.NewDust(base.Center - velocity / 2f, 0, 0, 228, 0f, 0f, 100, default(Color), 2.1f);
                Dust dust2 = Main.dust[num386];
                dust2.velocity *= 2f;
                Main.dust[num386].noGravity = true;
            }
        }
        if (type == 495)
        {
            for (int num387 = 0; num387 < 15; num387++)
            {
                int num388 = Dust.NewDust(base.Center, 10, 10, 27);
                Main.dust[num388].noGravity = true;
                Dust dust2 = Main.dust[num388];
                dust2.velocity -= oldVelocity * 0.3f;
            }
        }
        if (type == 497)
        {
            for (int num389 = 0; num389 < 15; num389++)
            {
                int num390 = Dust.NewDust(base.Center, 10, 10, 27);
                Main.dust[num390].noGravity = true;
                Dust dust2 = Main.dust[num390];
                dust2.velocity *= 2f;
                dust2 = Main.dust[num390];
                dust2.velocity -= oldVelocity * 0.3f;
                dust2 = Main.dust[num390];
                dust2.scale += (float)Main.rand.Next(150) * 0.001f;
            }
        }
        if (type == 448)
        {
            SoundEngine.PlaySound(SoundID.Item14, position);
            position = base.Center;
            width = (height = 112);
            position.X -= width / 2;
            position.Y -= height / 2;
            for (int num391 = 0; num391 < 4; num391++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
            }
            for (int num392 = 0; num392 < 40; num392++)
            {
                int num393 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 228, 0f, 0f, 0, default(Color), 2.5f);
                Main.dust[num393].noGravity = true;
                Dust dust2 = Main.dust[num393];
                dust2.velocity *= 3f;
                num393 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 228, 0f, 0f, 100, default(Color), 1.5f);
                dust2 = Main.dust[num393];
                dust2.velocity *= 2f;
                Main.dust[num393].noGravity = true;
            }
            for (int num394 = 0; num394 < 1; num394++)
            {
                int num395 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num395];
                gore2.velocity *= 0.3f;
                Main.gore[num395].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num395].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
            Damage();
        }
        else if (type == 715 || type == 716 || type == 717 || type == 718)
        {
            SoundEngine.PlaySound(SoundID.Item14, position);
            position = base.Center;
            width = (height = 128);
            if (type == 717 || type == 718)
            {
                width = (height = 240);
            }
            position.X -= width / 2;
            position.Y -= height / 2;
            Damage();
            AI_147_Explosion();
        }
        if (type == 616)
        {
            SoundEngine.PlaySound(SoundID.Item14, position);
            position = base.Center;
            width = (height = 80);
            position.X -= width / 2;
            position.Y -= height / 2;
            for (int num396 = 0; num396 < 4; num396++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
            }
            for (int num397 = 0; num397 < 40; num397++)
            {
                int num398 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229, 0f, 0f, 200, default(Color), 2.5f);
                Main.dust[num398].noGravity = true;
                Dust dust2 = Main.dust[num398];
                dust2.velocity *= 2f;
                num398 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229, 0f, 0f, 200, default(Color), 1.5f);
                dust2 = Main.dust[num398];
                dust2.velocity *= 1.2f;
                Main.dust[num398].noGravity = true;
            }
            for (int num399 = 0; num399 < 1; num399++)
            {
                int num400 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num400];
                gore2.velocity *= 0.3f;
                Main.gore[num400].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num400].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
            Damage();
        }
        if (type == 502)
        {
            Vector2 vector44 = new Vector2(width, height) / 2f;
            for (int num401 = 0; num401 < oldPos.Length; num401++)
            {
                if (!(oldPos[num401] == Vector2.Zero))
                {
                    int num402 = Dust.NewDust(oldPos[num401] + vector44, 0, 0, 66, 0f, 0f, 150, Color.Transparent, 0.7f);
                    Main.dust[num402].color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f);
                    Main.dust[num402].noGravity = true;
                }
            }
        }
        if (type == 510)
        {
            SoundEngine.PlaySound(SoundID.Item107, position);
            Gore.NewGore(base.Center, -oldVelocity * 0.2f, 704);
            Gore.NewGore(base.Center, -oldVelocity * 0.2f, 705);
            if (owner == Main.myPlayer)
            {
                int num403 = Main.rand.Next(20, 31);
                for (int num404 = 0; num404 < num403; num404++)
                {
                    Vector2 vector45 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                    vector45.Normalize();
                    vector45 *= (float)Main.rand.Next(10, 201) * 0.01f;
                    NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector45.X, vector45.Y, 511 + Main.rand.Next(3), damage, 1f, owner);
                }
            }
        }
        if (type == 868 || type == 869 || type == 996)
        {
            SoundEngine.PlaySound(SoundID.Item107, position);
            for (int num405 = 0; num405 < 15; num405++)
            {
                Dust.NewDust(position, width, height, 13, 0f, -2f, 0, default(Color), 1.5f);
            }
            if (Main.netMode != 1)
            {
                switch (type)
                {
                case 868:
                    WorldGen.TreeTops.RandomizeTreeStyleBasedOnWorldPosition(Main.rand, base.Center);
                    break;
                case 869:
                    WorldGen.RandomizeBackgroundBasedOnPlayer(Main.rand, Main.player[owner]);
                    break;
                case 996:
                    WorldGen.RandomizeMoonState(Main.rand, garenteeNewStyle: true);
                    break;
                }
                NetMessage.SendData(7);
            }
        }
        else if (type == 836)
        {
            for (int num406 = 0; num406 < 3; num406++)
            {
                int num407 = Dust.NewDust(position, width, height, 31, 0f, 0f, 50, Color.White, 0.8f);
                Dust dust2 = Main.dust[num407];
                dust2.velocity *= 0.5f;
                Main.dust[num407].noGravity = true;
            }
        }
        if (type == 408)
        {
            for (int num408 = 0; num408 < 15; num408++)
            {
                int num409 = Dust.NewDust(base.Center - Vector2.One * 10f, 50, 50, 5, 0f, -2f);
                Dust dust2 = Main.dust[num409];
                dust2.velocity /= 2f;
            }
            int num410 = 0;
            int num411 = 10;
            num410 = Gore.NewGore(base.Center, velocity * 0.8f, 584);
            Gore gore2 = Main.gore[num410];
            gore2.timeLeft /= num411;
            num410 = Gore.NewGore(base.Center, velocity * 0.9f, 585);
            gore2 = Main.gore[num410];
            gore2.timeLeft /= num411;
            num410 = Gore.NewGore(base.Center, velocity * 1f, 586);
            gore2 = Main.gore[num410];
            gore2.timeLeft /= num411;
        }
        if (type == 385)
        {
            SoundEngine.PlaySound(4, (int)base.Center.X, (int)base.Center.Y, 19);
            int num412 = 36;
            for (int num413 = 0; num413 < num412; num413++)
            {
                Vector2 spinningpoint = Vector2.Normalize(velocity) * new Vector2((float)width / 2f, height) * 0.75f;
                spinningpoint = spinningpoint.RotatedBy((float)(num413 - (num412 / 2 - 1)) * ((float)Math.PI * 2f) / (float)num412) + base.Center;
                Vector2 vector46 = spinningpoint - base.Center;
                int num414 = Dust.NewDust(spinningpoint + vector46, 0, 0, 172, vector46.X * 2f, vector46.Y * 2f, 100, default(Color), 1.4f);
                Main.dust[num414].noGravity = true;
                Main.dust[num414].noLight = true;
                Main.dust[num414].velocity = vector46;
            }
            if (owner == Main.myPlayer)
            {
                if (ai[1] < 1f)
                {
                    int num415 = (Main.expertMode ? 25 : 40);
                    int num416 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X - (float)(direction * 30), base.Center.Y - 4f, (float)(-direction) * 0.01f, 0f, 384, num415, 4f, owner, 16f, 15f);
                    Main.projectile[num416].netUpdate = true;
                }
                else
                {
                    int num417 = (int)(base.Center.Y / 16f);
                    int num418 = (int)(base.Center.X / 16f);
                    int num419 = 100;
                    if (num418 < 10)
                    {
                        num418 = 10;
                    }
                    if (num418 > Main.maxTilesX - 10)
                    {
                        num418 = Main.maxTilesX - 10;
                    }
                    if (num417 < 10)
                    {
                        num417 = 10;
                    }
                    if (num417 > Main.maxTilesY - num419 - 10)
                    {
                        num417 = Main.maxTilesY - num419 - 10;
                    }
                    int num420 = num417 + num419;
                    int num421 = num417 + 15;
                    for (int num422 = num417; num422 < num420; num422++)
                    {
                        Tile tile = Main.tile[num418, num422];
                        if (tile.active() && (Main.tileSolid[tile.type] || tile.liquid != 0))
{
                            num421 = num422;
                            break;
                        }
                    }
                    num417 = num421;
                    int num423 = (Main.expertMode ? 50 : 80);
                    int num424 = NewProjectile(GetProjectileSource_FromThis(), num418 * 16 + 8, num417 * 16 - 24, 0f, 0f, 386, num423, 4f, Main.myPlayer, 16f, 24f);
                    Main.projectile[num424].netUpdate = true;
                }
            }
        }
        else if (type >= 424 && type <= 426)
        {
            SoundEngine.PlaySound(SoundID.Item89, position);
            position.X += width / 2;
            position.Y += height / 2;
            width = (int)(128f * scale);
            height = (int)(128f * scale);
            position.X -= width / 2;
            position.Y -= height / 2;
            for (int num425 = 0; num425 < 8; num425++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
            }
            for (int num426 = 0; num426 < 32; num426++)
            {
                int num427 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                Main.dust[num427].noGravity = true;
                Dust dust2 = Main.dust[num427];
                dust2.velocity *= 3f;
                num427 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                dust2 = Main.dust[num427];
                dust2.velocity *= 2f;
                Main.dust[num427].noGravity = true;
            }
            for (int num428 = 0; num428 < 2; num428++)
            {
                int num429 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num429];
                gore2.velocity *= 0.3f;
                Main.gore[num429].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num429].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
            if (owner == Main.myPlayer)
            {
                localAI[1] = -1f;
                maxPenetrate = 0;
                Damage();
            }
            for (int num430 = 0; num430 < 5; num430++)
            {
                int num431 = Utils.SelectRandom<int>(Main.rand, 6, 259, 158);
                int num432 = Dust.NewDust(position, width, height, num431, 2.5f * (float)direction, -2.5f);
                Main.dust[num432].alpha = 200;
                Dust dust2 = Main.dust[num432];
                dust2.velocity *= 2.4f;
                dust2 = Main.dust[num432];
                dust2.scale += Main.rand.NextFloat();
            }
        }
        if (type == 399)
        {
            SoundEngine.PlaySound(13, (int)position.X, (int)position.Y);
            Vector2 vector47 = new Vector2(20f, 20f);
            for (int num433 = 0; num433 < 5; num433++)
            {
                Dust.NewDust(base.Center - vector47 / 2f, (int)vector47.X, (int)vector47.Y, 12, 0f, 0f, 0, Color.Red);
            }
            for (int num434 = 0; num434 < 10; num434++)
            {
                int num435 = Dust.NewDust(base.Center - vector47 / 2f, (int)vector47.X, (int)vector47.Y, 31, 0f, 0f, 100, default(Color), 1.5f);
                Dust dust2 = Main.dust[num435];
                dust2.velocity *= 1.4f;
            }
            for (int num436 = 0; num436 < 20; num436++)
            {
                int num437 = Dust.NewDust(base.Center - vector47 / 2f, (int)vector47.X, (int)vector47.Y, 6, 0f, 0f, 100, default(Color), 2.5f);
                Main.dust[num437].noGravity = true;
                Dust dust2 = Main.dust[num437];
                dust2.velocity *= 5f;
                num437 = Dust.NewDust(base.Center - vector47 / 2f, (int)vector47.X, (int)vector47.Y, 6, 0f, 0f, 100, default(Color), 1.5f);
                dust2 = Main.dust[num437];
                dust2.velocity *= 3f;
            }
            if (Main.myPlayer == owner)
            {
                for (int num438 = 0; num438 < 6; num438++)
                {
                    float num439 = (0f - velocity.X) * (float)Main.rand.Next(20, 50) * 0.01f + (float)Main.rand.Next(-20, 21) * 0.4f;
                    float num440 = (0f - Math.Abs(velocity.Y)) * (float)Main.rand.Next(30, 50) * 0.01f + (float)Main.rand.Next(-20, 5) * 0.4f;
                    NewProjectile(GetProjectileSource_FromThis(), base.Center.X + num439, base.Center.Y + num440, num439, num440, 400 + Main.rand.Next(3), (int)((double)damage * 0.5), 0f, owner);
                }
            }
        }
        if (type == 384 || type == 386)
        {
            for (int num441 = 0; num441 < 20; num441++)
            {
                int num442 = Dust.NewDust(position, width, height, 212, direction * 2, 0f, 100, default(Color), 1.4f);
                Dust dust42 = Main.dust[num442];
                dust42.color = Color.CornflowerBlue;
                dust42.color = Color.Lerp(dust42.color, Color.White, 0.3f);
                dust42.noGravity = true;
            }
        }
        if (type == 507 || type == 508)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            Vector2 vector48 = position;
            Vector2 vector49 = oldVelocity;
            vector49.Normalize();
            vector48 += vector49 * 16f;
            for (int num443 = 0; num443 < 20; num443++)
            {
                int num444 = Dust.NewDust(vector48, width, height, 81);
                Main.dust[num444].position = (Main.dust[num444].position + base.Center) / 2f;
                Dust dust2 = Main.dust[num444];
                dust2.velocity += oldVelocity * 0.4f;
                dust2 = Main.dust[num444];
                dust2.velocity *= 0.5f;
                Main.dust[num444].noGravity = true;
                vector48 -= vector49 * 8f;
            }
        }
        if (type == 598)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            Vector2 vector50 = position;
            Vector2 vector51 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
            vector50 += vector51 * 16f;
            for (int num445 = 0; num445 < 20; num445++)
            {
                int num446 = Dust.NewDust(vector50, width, height, 81);
                Main.dust[num446].position = (Main.dust[num446].position + base.Center) / 2f;
                Dust dust2 = Main.dust[num446];
                dust2.velocity += vector51 * 2f;
                dust2 = Main.dust[num446];
                dust2.velocity *= 0.5f;
                Main.dust[num446].noGravity = true;
                vector50 -= vector51 * 8f;
            }
        }
        if (type == 971)
        {
            Vector2 vector52 = position;
            Vector2 vector53 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
            vector52 += vector53 * 8f;
            for (int num447 = 0; num447 < 6; num447++)
            {
                int num448 = Dust.NewDust(vector52, width, height, 4);
                Main.dust[num448].color = new Color(10, 10, 10, 150);
                Main.dust[num448].position = (Main.dust[num448].position + base.Center) / 2f;
                Dust dust2 = Main.dust[num448];
                dust2.velocity += vector53;
                dust2 = Main.dust[num448];
                dust2.velocity *= 0.5f;
                Main.dust[num448].noGravity = true;
                vector52 -= vector53 * 4f;
            }
        }
        if (type == 1 || type == 81 || type == 98 || type == 980)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num449 = 0; num449 < 10; num449++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 7);
            }
        }
        if (type == 336 || type == 345)
        {
            for (int num450 = 0; num450 < 6; num450++)
            {
                int num451 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 196);
                Main.dust[num451].noGravity = true;
                Main.dust[num451].scale = scale;
            }
        }
        if (type == 358)
        {
            velocity = oldVelocity * 0.2f;
            for (int num452 = 0; num452 < 100; num452++)
            {
                int num453 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 211, 0f, 0f, 75, default(Color), 1.2f);
                Dust dust2;
                if (Main.rand.Next(2) == 0)
                {
                    dust2 = Main.dust[num453];
                    dust2.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust2 = Main.dust[num453];
                    dust2.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust2 = Main.dust[num453];
                    dust2.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num453].scale = 0.6f;
                }
                else
                {
                    Main.dust[num453].noGravity = true;
                }
                dust2 = Main.dust[num453];
                dust2.velocity *= 0.3f;
                dust2 = Main.dust[num453];
                dust2.velocity += velocity;
                dust2 = Main.dust[num453];
                dust2.velocity *= 1f + (float)Main.rand.Next(-100, 101) * 0.01f;
                Main.dust[num453].velocity.X += (float)Main.rand.Next(-50, 51) * 0.015f;
                Main.dust[num453].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.015f;
                Main.dust[num453].position = base.Center;
            }
        }
        if (type == 406)
        {
            int num454 = 175;
            Color newColor6 = new Color(0, 80, 255, 100);
            velocity = oldVelocity * 0.2f;
            for (int num455 = 0; num455 < 40; num455++)
            {
                int num456 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 4, 0f, 0f, num454, newColor6, 1.6f);
                Dust dust2;
                if (Main.rand.Next(2) == 0)
                {
                    dust2 = Main.dust[num456];
                    dust2.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust2 = Main.dust[num456];
                    dust2.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust2 = Main.dust[num456];
                    dust2.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num456].scale = 0.6f;
                }
                else
                {
                    Main.dust[num456].noGravity = true;
                }
                dust2 = Main.dust[num456];
                dust2.velocity *= 0.3f;
                dust2 = Main.dust[num456];
                dust2.velocity += velocity;
                dust2 = Main.dust[num456];
                dust2.velocity *= 1f + (float)Main.rand.Next(-100, 101) * 0.01f;
                Main.dust[num456].velocity.X += (float)Main.rand.Next(-50, 51) * 0.015f;
                Main.dust[num456].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.015f;
                Main.dust[num456].position = base.Center;
            }
        }
        if (type == 344)
        {
            for (int num457 = 0; num457 < 8; num457++)
            {
                int num458 = Dust.NewDust(position, width, height, 197, 0f, 0f, 50);
                Main.dust[num458].noGravity = true;
                Main.dust[num458].velocity.X *= 0.75f;
                Main.dust[num458].velocity.Y *= 0.75f;
                Dust dust2 = Main.dust[num458];
                dust2.velocity -= velocity * 0.025f;
            }
        }
        else if (type == 343)
        {
            SoundEngine.PlaySound(SoundID.Item27, position);
            for (int num459 = 4; num459 < 31; num459++)
            {
                float num460 = oldVelocity.X * (30f / (float)num459);
                float num461 = oldVelocity.Y * (30f / (float)num459);
                int num462 = Dust.NewDust(new Vector2(oldPosition.X - num460, oldPosition.Y - num461), 8, 8, 197, oldVelocity.X, oldVelocity.Y, 100, default(Color), 1.2f);
                Main.dust[num462].noGravity = true;
                Dust dust2 = Main.dust[num462];
                dust2.velocity *= 0.5f;
            }
        }
        else if (type == 349)
        {
            SoundEngine.PlaySound(SoundID.Item27, position);
            for (int num463 = 0; num463 < 3; num463++)
            {
                int num464 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 76);
                Main.dust[num464].noGravity = true;
                Main.dust[num464].noLight = true;
                Main.dust[num464].scale = 0.7f;
            }
        }
        if (type == 323)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num465 = 0; num465 < 20; num465++)
            {
                int num466 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 7);
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num466].noGravity = true;
                    Main.dust[num466].scale = 1.3f;
                    Dust dust2 = Main.dust[num466];
                    dust2.velocity *= 1.5f;
                    dust2 = Main.dust[num466];
                    dust2.velocity -= oldVelocity * 0.5f;
                    dust2 = Main.dust[num466];
                    dust2.velocity *= 1.5f;
                }
                else
                {
                    Dust dust2 = Main.dust[num466];
                    dust2.velocity *= 0.75f;
                    dust2 = Main.dust[num466];
                    dust2.velocity -= oldVelocity * 0.25f;
                    Main.dust[num466].scale = 0.8f;
                }
            }
        }
        if (type == 589)
        {
            SoundEngine.PlaySound(SoundID.Item27, position);
            Color newColor7 = Color.Red;
            if (ai[1] == 1f)
            {
                newColor7 = Color.Green;
            }
            if (ai[1] == 2f)
            {
                newColor7 = Color.Purple;
            }
            if (ai[1] == 3f)
            {
                newColor7 = Color.Gold;
            }
            if (ai[1] == 4f)
            {
                newColor7 = Color.White;
            }
            newColor7.A = 100;
            for (int num467 = 0; num467 < 30; num467++)
            {
                int num468 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 11, 0f, 0f, 0, newColor7);
                Dust dust2 = Main.dust[num468];
                dust2.velocity *= 1f + Main.rand.NextFloat() * 1f;
                if (num467 < 10)
                {
                    Main.dust[num468].noGravity = true;
                    dust2 = Main.dust[num468];
                    dust2.velocity *= 0.5f;
                }
            }
        }
        if (type == 346)
        {
            SoundEngine.PlaySound(SoundID.Item27, position);
            for (int num469 = 0; num469 < 20; num469++)
            {
                int num470 = 10;
                if (ai[1] == 1f)
                {
                    num470 = 4;
                }
                int num471 = Dust.NewDust(position, width, height, num470);
                Main.dust[num471].noGravity = true;
            }
        }
        if (type == 335)
        {
            SoundEngine.PlaySound(SoundID.Item27, position);
            for (int num472 = 0; num472 < 20; num472++)
            {
                int num473 = 90 - (int)ai[1];
                int num474 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num473);
                Main.dust[num474].noLight = true;
                Main.dust[num474].scale = 0.8f;
            }
        }
        if (type == 318)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num475 = 0; num475 < 10; num475++)
            {
                int num476 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 30);
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num476].noGravity = true;
                }
            }
        }
        if (type == 378)
        {
            for (int num477 = 0; num477 < 10; num477++)
            {
                int num478 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 30);
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num478].noGravity = true;
                }
            }
        }
        else if (type == 311)
        {
            for (int num479 = 0; num479 < 5; num479++)
            {
                int num480 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 189);
                Main.dust[num480].scale = 0.85f;
                Main.dust[num480].noGravity = true;
                Dust dust2 = Main.dust[num480];
                dust2.velocity += velocity * 0.5f;
            }
        }
        else if (type == 316)
        {
            for (int num481 = 0; num481 < 5; num481++)
            {
                int num482 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 195);
                Main.dust[num482].scale = 0.85f;
                Main.dust[num482].noGravity = true;
                Dust dust2 = Main.dust[num482];
                dust2.velocity += velocity * 0.5f;
            }
        }
        else if (type == 184 || type == 195)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num483 = 0; num483 < 5; num483++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 7);
            }
        }
        else if (type == 275 || type == 276)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num484 = 0; num484 < 5; num484++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 7);
            }
        }
        else if (type == 291)
        {
            if (owner == Main.myPlayer)
            {
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 292, damage, knockBack, owner);
            }
        }
        else if (type == 295)
        {
            if (owner == Main.myPlayer)
            {
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 296, (int)((double)damage * 0.75), knockBack, owner);
            }
        }
        else if (type == 270 || type == 837)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y, 27);
            if (type == 270)
            {
                for (int num485 = 0; num485 < 20; num485++)
                {
                    int num486 = Dust.NewDust(position, width, height, 26, 0f, 0f, 100);
                    Main.dust[num486].noGravity = true;
                    Dust dust2 = Main.dust[num486];
                    dust2.velocity *= 1.2f;
                    Main.dust[num486].scale = 1.3f;
                    dust2 = Main.dust[num486];
                    dust2.velocity -= oldVelocity * 0.3f;
                    num486 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, 5, 0f, 0f, 100, default(Color), 1.5f);
                    Main.dust[num486].noGravity = true;
                    dust2 = Main.dust[num486];
                    dust2.velocity *= 3f;
                }
            }
            else
            {
                for (int num487 = 0; num487 < 20; num487++)
                {
                    int num488 = Dust.NewDust(position, width, height, 26, 0f, 0f, 100);
                    Main.dust[num488].noGravity = true;
                    Dust dust2 = Main.dust[num488];
                    dust2.velocity *= 1.2f;
                    Main.dust[num488].scale = 1.3f;
                    dust2 = Main.dust[num488];
                    dust2.velocity -= oldVelocity * 0.3f;
                    num488 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, 6, 0f, 0f, 100, default(Color), 2f);
                    Main.dust[num488].noGravity = true;
                    dust2 = Main.dust[num488];
                    dust2.velocity *= 3f;
                }
            }
        }
        else if (type == 265)
        {
            for (int num489 = 0; num489 < 15; num489++)
            {
                int num490 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 163, 0f, 0f, 100, default(Color), 1.2f);
                Main.dust[num490].noGravity = true;
                Dust dust2 = Main.dust[num490];
                dust2.velocity *= 1.2f;
                dust2 = Main.dust[num490];
                dust2.velocity -= oldVelocity * 0.3f;
            }
        }
        else if (type == 355)
        {
            for (int num491 = 0; num491 < 15; num491++)
            {
                int num492 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 205, 0f, 0f, 100, default(Color), 1.2f);
                Main.dust[num492].noGravity = true;
                Dust dust2 = Main.dust[num492];
                dust2.velocity *= 1.2f;
                dust2 = Main.dust[num492];
                dust2.velocity -= oldVelocity * 0.3f;
            }
        }
        else if (type == 304)
        {
            for (int num493 = 0; num493 < 3; num493++)
            {
                int num494 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 182, 0f, 0f, 100, default(Color), 0.8f);
                Main.dust[num494].noGravity = true;
                Dust dust2 = Main.dust[num494];
                dust2.velocity *= 1.2f;
                dust2 = Main.dust[num494];
                dust2.velocity -= oldVelocity * 0.3f;
            }
        }
        else if (type == 263)
        {
            SoundEngine.PlaySound(SoundID.Item27, position);
            for (int num495 = 0; num495 < 15; num495++)
            {
                int num496 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 92, velocity.X, velocity.Y, Main.rand.Next(0, 101), default(Color), 1f + (float)Main.rand.Next(40) * 0.01f);
                Main.dust[num496].noGravity = true;
                Dust dust2 = Main.dust[num496];
                dust2.velocity *= 2f;
            }
        }
        else if (type == 261)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num497 = 0; num497 < 15; num497++)
            {
                Dust dust43 = Dust.NewDustDirect(new Vector2(position.X, position.Y), width, height, 148);
                Dust dust2 = dust43;
                dust2.velocity *= 2f;
                dust43.velocity.Y -= 0.4f;
            }
            for (int num498 = 0; num498 < 3; num498++)
            {
                Dust dust44 = Dust.NewDustDirect(new Vector2(position.X, position.Y), width, height, 228);
                Dust dust2 = dust44;
                dust2.velocity *= 2f;
                dust44.noLight = true;
                dust2 = dust44;
                dust2.scale *= 0.8f;
                dust44.velocity.Y -= 0.3f;
            }
        }
        else if (type == 928)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num499 = 0; num499 < 25; num499++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 5, velocity.X, velocity.Y, 0, Color.White, 1.3f);
            }
        }
        else if (type == 229)
        {
            for (int num500 = 0; num500 < 25; num500++)
            {
                int num501 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 157);
                Main.dust[num501].noGravity = true;
                Dust dust2 = Main.dust[num501];
                dust2.velocity *= 1.5f;
                Main.dust[num501].scale = 1.5f;
            }
        }
        else if (type == 239)
        {
            if (velocity.Y > 0f)
            {
                int num502 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 2f), 2, 2, 154);
                Main.dust[num502].position.X -= 2f;
                Main.dust[num502].alpha = 38;
                Dust dust2 = Main.dust[num502];
                dust2.velocity *= 0.1f;
                dust2 = Main.dust[num502];
                dust2.velocity += -oldVelocity * 0.25f;
                Main.dust[num502].scale = 0.95f;
            }
        }
        else if (type == 245)
        {
            if (velocity.Y > 0f)
            {
                int num503 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 2f), 2, 2, 114);
                Main.dust[num503].noGravity = true;
                Main.dust[num503].position.X -= 2f;
                Main.dust[num503].alpha = 38;
                Dust dust2 = Main.dust[num503];
                dust2.velocity *= 0.1f;
                dust2 = Main.dust[num503];
                dust2.velocity += -oldVelocity * 0.25f;
                Main.dust[num503].scale = 0.95f;
            }
        }
        else if (type == 264)
        {
            if (velocity.Y > 0f)
            {
                int num504 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 2f), 2, 2, 54);
                Main.dust[num504].noGravity = true;
                Main.dust[num504].position.X -= 2f;
                Main.dust[num504].alpha = 38;
                Dust dust2 = Main.dust[num504];
                dust2.velocity *= 0.1f;
                dust2 = Main.dust[num504];
                dust2.velocity += -oldVelocity * 0.25f;
                Main.dust[num504].scale = 0.95f;
            }
        }
        else if (type == 206 || type == 225)
        {
            SoundEngine.PlaySound(6, (int)position.X, (int)position.Y);
            for (int num505 = 0; num505 < 5; num505++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 40);
            }
        }
        else if (type == 227)
        {
            SoundEngine.PlaySound(6, (int)position.X, (int)position.Y);
            for (int num506 = 0; num506 < 15; num506++)
            {
                int num507 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 157);
                Main.dust[num507].noGravity = true;
                Dust dust2 = Main.dust[num507];
                dust2.velocity += oldVelocity * Main.rand.NextFloat();
                Main.dust[num507].scale = 1.5f;
            }
        }
        else if (type == 237 && owner == Main.myPlayer)
        {
            NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 238, damage, knockBack, owner);
        }
        else if (type == 243 && owner == Main.myPlayer)
        {
            NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 244, damage, knockBack, owner);
        }
        else if (type == 120)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num508 = 0; num508 < 10; num508++)
            {
                int num509 = Dust.NewDust(new Vector2(position.X - velocity.X, position.Y - velocity.Y), width, height, 67, velocity.X, velocity.Y, 100);
                if (num508 < 5)
                {
                    Main.dust[num509].noGravity = true;
                }
                Dust dust2 = Main.dust[num509];
                dust2.velocity *= 0.2f;
            }
        }
        else if (type == 181 || type == 189 || type == 566)
        {
            for (int num510 = 0; num510 < 6; num510++)
            {
                int num511 = Dust.NewDust(position, width, height, 150, velocity.X, velocity.Y, 50);
                Main.dust[num511].noGravity = true;
                Main.dust[num511].scale = 1f;
            }
        }
        else if (type == 178)
        {
            for (int num512 = 0; num512 < 85; num512++)
            {
                int num513 = Main.rand.Next(139, 143);
                int num514 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num513, velocity.X, velocity.Y, 0, default(Color), 1.2f);
                Main.dust[num514].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num514].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num514].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num514].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num514].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.dust[num514].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                Dust dust2 = Main.dust[num514];
                dust2.scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
            }
            for (int num515 = 0; num515 < 40; num515++)
            {
                int num516 = Main.rand.Next(276, 283);
                int num517 = Gore.NewGore(position, velocity, num516);
                Main.gore[num517].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num517].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num517].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num517].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Gore gore2 = Main.gore[num517];
                gore2.scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                Main.gore[num517].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.gore[num517].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
            }
        }
        else if (type == 289)
        {
            for (int num518 = 0; num518 < 30; num518++)
            {
                int num519 = Main.rand.Next(139, 143);
                int num520 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num519, velocity.X, velocity.Y, 0, default(Color), 1.2f);
                Main.dust[num520].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num520].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num520].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num520].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num520].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.dust[num520].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                Dust dust2 = Main.dust[num520];
                dust2.scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
            }
            for (int num521 = 0; num521 < 15; num521++)
            {
                int num522 = Main.rand.Next(276, 283);
                int num523 = Gore.NewGore(position, velocity, num522);
                Main.gore[num523].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num523].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num523].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num523].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Gore gore2 = Main.gore[num523];
                gore2.scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                Main.gore[num523].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.gore[num523].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
            }
        }
        else if (type == 475 || type == 505 || type == 506)
        {
            if (ai[1] == 0f)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            }
            if (ai[1] < 10f)
            {
                Vector2 vector54 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                float num524 = 0f - velocity.X;
                float num525 = 0f - velocity.Y;
                float num526 = 1f;
                if (ai[0] <= 17f)
                {
                    num526 = ai[0] / 17f;
                }
                int num527 = (int)(30f * num526);
                float num528 = 1f;
                if (ai[0] <= 30f)
                {
                    num528 = ai[0] / 30f;
                }
                float num529 = 0.4f * num528;
                float num530 = num529;
                num525 += num530;
                for (int num531 = 0; num531 < num527; num531++)
                {
                    float num532 = (float)Math.Sqrt(num524 * num524 + num525 * num525);
                    float num533 = 5.6f;
                    if (Math.Abs(num524) + Math.Abs(num525) < 1f)
                    {
                        num533 *= Math.Abs(num524) + Math.Abs(num525) / 1f;
                    }
                    num532 = num533 / num532;
                    num524 *= num532;
                    num525 *= num532;
                    Math.Atan2(num525, num524);
                    int num534 = 3;
                    if (type == 506)
                    {
                        num534 = 30;
                    }
                    if (type == 505)
                    {
                        num534 = 239;
                    }
                    if ((float)num531 > ai[1])
                    {
                        for (int num535 = 0; num535 < 4; num535++)
{
                            int num536 = Dust.NewDust(vector54, width, height, num534);
                            Main.dust[num536].noGravity = true;
                            Dust dust2 = Main.dust[num536];
                            dust2.velocity *= 0.3f;
                        }
                    }
                    vector54.X += num524;
                    vector54.Y += num525;
                    num524 = 0f - velocity.X;
                    num525 = 0f - velocity.Y;
                    num530 += num529;
                    num525 += num530;
                }
            }
        }
        else if (type == 171)
        {
            if (ai[1] == 0f)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            }
            if (ai[1] < 10f)
            {
                Vector2 vector55 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                float num537 = 0f - velocity.X;
                float num538 = 0f - velocity.Y;
                float num539 = 1f;
                if (ai[0] <= 17f)
                {
                    num539 = ai[0] / 17f;
                }
                int num540 = (int)(30f * num539);
                float num541 = 1f;
                if (ai[0] <= 30f)
                {
                    num541 = ai[0] / 30f;
                }
                float num542 = 0.4f * num541;
                float num543 = num542;
                num538 += num543;
                for (int num544 = 0; num544 < num540; num544++)
                {
                    float num545 = (float)Math.Sqrt(num537 * num537 + num538 * num538);
                    float num546 = 5.6f;
                    if (Math.Abs(num537) + Math.Abs(num538) < 1f)
                    {
                        num546 *= Math.Abs(num537) + Math.Abs(num538) / 1f;
                    }
                    num545 = num546 / num545;
                    num537 *= num545;
                    num538 *= num545;
                    Math.Atan2(num538, num537);
                    if ((float)num544 > ai[1])
                    {
                        for (int num547 = 0; num547 < 4; num547++)
{
                            int num548 = Dust.NewDust(vector55, width, height, 129);
                            Main.dust[num548].noGravity = true;
                            Dust dust2 = Main.dust[num548];
                            dust2.velocity *= 0.3f;
                        }
                    }
                    vector55.X += num537;
                    vector55.Y += num538;
                    num537 = 0f - velocity.X;
                    num538 = 0f - velocity.Y;
                    num543 += num542;
                    num538 += num543;
                }
            }
        }
        else if (type == 117)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num549 = 0; num549 < 10; num549++)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 26);
            }
        }
        else if (type == 166)
        {
            SoundEngine.PlaySound(SoundID.Item51, position);
            for (int num550 = 0; num550 < 10; num550++)
            {
                int num551 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 76);
                Main.dust[num551].noGravity = true;
                Dust dust2 = Main.dust[num551];
                dust2.velocity -= oldVelocity * 0.25f;
            }
        }
        else if (type == 158)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num552 = 0; num552 < 10; num552++)
            {
                int num553 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 9);
                Main.dust[num553].noGravity = true;
                Dust dust2 = Main.dust[num553];
                dust2.velocity -= velocity * 0.5f;
            }
        }
        else if (type == 159)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num554 = 0; num554 < 10; num554++)
            {
                int num555 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 11);
                Main.dust[num555].noGravity = true;
                Dust dust2 = Main.dust[num555];
                dust2.velocity -= velocity * 0.5f;
            }
        }
        else if (type == 160)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num556 = 0; num556 < 10; num556++)
            {
                int num557 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 19);
                Main.dust[num557].noGravity = true;
                Dust dust2 = Main.dust[num557];
                dust2.velocity -= velocity * 0.5f;
            }
        }
        else if (type == 161)
        {
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            for (int num558 = 0; num558 < 10; num558++)
            {
                int num559 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 11);
                Main.dust[num559].noGravity = true;
                Dust dust2 = Main.dust[num559];
                dust2.velocity -= velocity * 0.5f;
            }
        }
        else if (type >= 191 && type <= 194)
        {
            int num560 = Gore.NewGore(new Vector2(position.X - (float)(width / 2), position.Y - (float)(height / 2)), new Vector2(0f, 0f), Main.rand.Next(61, 64), scale);
            Gore gore2 = Main.gore[num560];
            gore2.velocity *= 0.1f;
        }
        else if (!Main.projPet[type])
        {
            if (type == 93)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num561 = 0; num561 < 10; num561++)
                {
                    int num562 = Dust.NewDust(position, width, height, 57, 0f, 0f, 100);
                    Main.dust[num562].noGravity = true;
                    Main.dust[num562].fadeIn = 1f;
                    Main.dust[num562].velocity.X *= 2f;
                    Main.dust[num562].velocity.Y *= 2f;
                    Main.dust[num562].velocity.Y -= Main.rand.NextFloat() * 1.5f;
                }
            }
            else if (type == 99 || type == 1013 || type == 727 || type == 1014 || type == 1021)
            {
                short num563 = 1;
                num563 = type switch
                {
                    1013 => 243,
                    727 => 40,
                    1014 => 12,
                    1021 => 323,
                    _ => 1,
                };
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num564 = 0; num564 < 30; num564++)
                {
                    int num565 = Dust.NewDust(position, width, height, num563);
                    if (Main.rand.Next(2) == 0)
                    {
                        Dust dust2 = Main.dust[num565];
                        dust2.scale *= 1.4f;
                    }
                    velocity *= 1.9f;
                }
                if (type == 1014 && owner == Main.myPlayer)
                {
                    int number = Item.NewItem(new EntitySource_Loot(this), position, base.Size, 29);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(21, -1, -1, null, number, 1f);
                    }
                }
            }
            else if (type == 1005)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num566 = 0; num566 < 10; num566++)
                {
                    int num567 = Dust.NewDust(position, width, height, 1);
                    if (Main.rand.Next(2) == 0)
                    {
                        Dust dust2 = Main.dust[num567];
                        dust2.scale *= 1.1f;
                    }
                    velocity *= 1.6f;
                }
            }
            else if (type == 772)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num568 = 0; num568 < 6; num568++)
                {
                    Dust.NewDust(position, width, height, 1);
                    velocity *= 1.9f;
                }
                for (int num569 = 0; num569 < 20; num569++)
                {
                    Dust dust45 = Dust.NewDustDirect(position, width, height, Main.rand.NextFromList<int>(86, 87, 88, 89, 90), 0f, 0f, 0, default(Color), 0.7f);
                    dust45.noGravity = true;
                    Dust dust2 = dust45;
                    dust2.velocity *= 2.9f;
                    dust45.velocity.Y *= 0.8f;
                    dust45.fadeIn = 1.1f;
                }
                for (int num570 = 0; num570 < 7; num570++)
                {
                    Dust dust46 = Dust.NewDustDirect(position, width, height, Main.rand.NextFromList<int>(86, 87, 88, 89, 90), 0f, 0f, 0, default(Color), 0.7f);
                    dust46.noGravity = true;
                    Dust dust2 = dust46;
                    dust2.velocity *= 2.9f;
                    dust46.velocity.Y *= 0.8f;
                    dust46.fadeIn = 1.1f;
                    dust46.noLight = true;
                }
                if (owner == Main.myPlayer)
                {
                    DropGeodeGems();
                }
            }
            else if (type == 763)
            {
                for (int num571 = 0; num571 < 4; num571++)
                {
                    int num572 = Dust.NewDust(position, width, height, 40);
                    if (Main.rand.Next(2) == 0)
                    {
                        Dust dust2 = Main.dust[num572];
                        dust2.scale *= 0.8f;
                    }
                    Main.dust[num572].noGravity = true;
                    velocity *= 1.9f;
                }
            }
            else if (type == 655)
            {
                SoundEngine.PlaySound(4, (int)position.X, (int)position.Y);
                for (int num573 = 0; num573 < 30; num573++)
                {
                    int num574 = Dust.NewDust(position, width, height, 147);
                    if (Main.rand.Next(2) == 0)
                    {
                        Dust dust2 = Main.dust[num574];
                        dust2.scale *= 1.4f;
                    }
                    velocity *= 1.9f;
                }
                if (Main.netMode != 1 && !wet)
                {
                    int num575 = 2;
                    if (Main.rand.Next(3) == 0)
                    {
                        num575++;
                    }
                    if (Main.rand.Next(3) == 0)
                    {
                        num575++;
                    }
                    if (Main.rand.Next(3) == 0)
                    {
                        num575++;
                    }
                    int availableAmountOfNPCsToSpawnUpToSlot = NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(num575);
                    for (int num576 = 0; num576 < availableAmountOfNPCsToSpawnUpToSlot; num576++)
                    {
                        int num577 = Main.rand.Next(210, 212);
                        int num578 = NPC.NewNPC(GetNPCSource_FromThis(), (int)base.Center.X, (int)base.Center.Y, num577, 1);
                        Main.npc[num578].velocity.X = (float)Main.rand.Next(-200, 201) * 0.002f;
                        Main.npc[num578].velocity.Y = (float)Main.rand.Next(-200, 201) * 0.002f;
                        Main.npc[num578].netUpdate = true;
                    }
                }
            }
            else if (type == 728)
            {
                SoundEngine.PlaySound(SoundID.Item10, position);
                for (int num579 = 0; num579 < 7; num579++)
                {
                    Dust.NewDust(position, width, height, 58, velocity.X * 0.1f, velocity.Y * 0.1f, 150, default(Color), 0.8f);
                }
                for (float num580 = 0f; num580 < 1f; num580 += 0.125f)
                {
                    Dust.NewDustPerfect(base.Center, 278, Vector2.UnitY.RotatedBy(num580 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * 0.5f) * (4f + Main.rand.NextFloat() * 4f), 150, Color.CornflowerBlue).noGravity = true;
                }
                for (float num581 = 0f; num581 < 1f; num581 += 0.25f)
                {
                    Dust.NewDustPerfect(base.Center, 278, Vector2.UnitY.RotatedBy(num581 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * 0.5f) * (2f + Main.rand.NextFloat() * 3f), 150, Color.Gold).noGravity = true;
                }
                Vector2 vector56 = new Vector2(Main.screenWidth, Main.screenHeight);
                if (base.Hitbox.Intersects(Utils.CenteredRectangle(Main.screenPosition + vector56 / 2f, vector56 + new Vector2(400f))))
                {
                    for (int num582 = 0; num582 < 7; num582++)
                    {
                        Gore.NewGore(position, Main.rand.NextVector2CircularEdge(0.5f, 0.5f) * velocity.Length(), Utils.SelectRandom<int>(Main.rand, 16, 17, 17, 17, 17, 17, 17, 17));
                    }
                }
            }
            else if (type == 729)
            {
                SoundEngine.PlaySound(SoundID.Item10, position);
                for (int num583 = 0; num583 < 10; num583++)
                {
                    Dust dust47 = Dust.NewDustDirect(position, width, height, 279, velocity.X * 0.1f, velocity.Y * 0.1f, 150, default(Color), 1.2f);
                    dust47.noGravity = true;
                    dust47.velocity.X *= 2f;
                }
            }
            else if (type == 723 || type == 724 || type == 725 || type == 726 || type == 907)
            {
                if (type == 723)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num584 = 0; num584 < 10; num584++)
                    {
                        Dust dust48 = Dust.NewDustDirect(position, width, height, 88, velocity.X * 0.1f, velocity.Y * 0.1f, 150, default(Color), 1.2f);
                        dust48.noGravity = true;
                        dust48.velocity.X *= 2f;
                    }
                    for (int num585 = 0; num585 < 3; num585++)
                    {
                        Gore gore3 = Gore.NewGoreDirect(position, new Vector2(velocity.X * 0.05f, velocity.Y * 0.05f), Utils.SelectRandom<int>(Main.rand, 16, 17, 17));
                        Gore gore2 = gore3;
                        gore2.velocity *= 2f;
                    }
                    if (owner == Main.myPlayer && Main.player[owner].starCloakCooldown == 0)
                    {
                        Main.player[owner].starCloakCooldown = 60;
                        int number2 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 4143);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(21, -1, -1, null, number2, 1f);
                        }
                    }
                }
                else
                {
                    if (type == 907)
                    {
                        SoundEngine.PlaySound(SoundID.Item27, position);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item10, position);
                    }
                    for (int num586 = 0; num586 < 10; num586++)
                    {
                        Dust dust49 = Main.dust[Dust.NewDust(position, width, height, 58, velocity.X * 0.1f, velocity.Y * 0.1f, 150, default(Color), 1.2f)];
                        if (type == 907)
{
                            Dust dust2 = dust49;
                            dust2.velocity *= 0.75f;
                        }
                    }
                    for (int num587 = 0; num587 < 3; num587++)
                    {
                        Gore gore4 = Main.gore[Gore.NewGore(position, new Vector2(velocity.X * 0.05f, velocity.Y * 0.05f), Main.rand.Next(16, 18))];
                        if (type == 907)
{
                            Gore gore2 = gore4;
                            gore2.velocity *= 0.5f;
                        }
                    }
                }
            }
            else if (type == 91 || type == 92)
            {
                SoundEngine.PlaySound(SoundID.Item10, position);
                for (int num588 = 0; num588 < 10; num588++)
                {
                    Dust.NewDust(position, width, height, 58, velocity.X * 0.1f, velocity.Y * 0.1f, 150, default(Color), 1.2f);
                }
                for (int num589 = 0; num589 < 3; num589++)
                {
                    Gore.NewGore(position, new Vector2(velocity.X * 0.05f, velocity.Y * 0.05f), Main.rand.Next(16, 18));
                }
                if ((type == 91 || (type == 92 && ai[0] > 0f)) && owner == Main.myPlayer)
                {
                    float x = position.X + (float)Main.rand.Next(-400, 400);
                    float y = position.Y - (float)Main.rand.Next(600, 900);
                    Vector2 vector57 = new Vector2(x, y);
                    float num590 = position.X + (float)(width / 2) - vector57.X;
                    float num591 = position.Y + (float)(height / 2) - vector57.Y;
                    int num592 = 22;
                    float num593 = (float)Math.Sqrt(num590 * num590 + num591 * num591);
                    num593 = (float)num592 / num593;
                    num590 *= num593;
                    num591 *= num593;
                    int num594 = damage;
                    if (type == 91)
                    {
                        num594 /= 3;
                    }
                    int num595 = NewProjectile(GetProjectileSource_FromThis(), x, y, num590, num591, 92, num594, knockBack, owner);
                    if (type == 91)
                    {
                        Main.projectile[num595].ai[1] = position.Y;
                        Main.projectile[num595].ai[0] = 1f;
                    }
                    else
                    {
                        Main.projectile[num595].ai[1] = position.Y;
                    }
                }
            }
            else if (type == 89)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num596 = 0; num596 < 5; num596++)
                {
                    int num597 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 68);
                    Main.dust[num597].noGravity = true;
                    Dust dust2 = Main.dust[num597];
                    dust2.velocity *= 1.5f;
                    dust2 = Main.dust[num597];
                    dust2.scale *= 0.9f;
                }
                if (type == 89 && owner == Main.myPlayer)
                {
                    for (int num598 = 0; num598 < 2; num598++)
                    {
                        float num599 = (0f - velocity.X) * (float)Main.rand.Next(40, 70) * 0.01f + (float)Main.rand.Next(-20, 21) * 0.4f;
                        float num600 = (0f - velocity.Y) * (float)Main.rand.Next(40, 70) * 0.01f + (float)Main.rand.Next(-20, 21) * 0.4f;
                        NewProjectile(GetProjectileSource_FromThis(), position.X + num599, position.Y + num600, num599, num600, 90, (int)((double)damage * 0.5), 0f, owner);
                    }
                }
            }
            else if (type == 967)
            {
                SoundEngine.PlaySound(SoundID.Item45, position);
                for (int num601 = 0; num601 < 20; num601++)
                {
                    int num602 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 219, velocity.X, velocity.Y, 0, default(Color), 0.5f + (float)Main.rand.Next(-20, 40) * 0.01f);
                    Main.dust[num602].noGravity = true;
                    Main.dust[num602].velocity = Main.rand.NextVector2Circular(6f, 6f);
                }
            }
            else if (type == 969)
            {
                ActiveSound activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
                if (activeSound2 != null)
                {
                    activeSound2.Volume = 0f;
                    activeSound2.Stop();
                }
            }
            else if (type == 177)
            {
                for (int num603 = 0; num603 < 20; num603++)
                {
                    int num604 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 137, 0f, 0f, Main.rand.Next(0, 101), default(Color), 1f + (float)Main.rand.Next(-20, 40) * 0.01f);
                    Dust dust2 = Main.dust[num604];
                    dust2.velocity -= oldVelocity * 0.2f;
                    if (Main.rand.Next(3) == 0)
                    {
                        dust2 = Main.dust[num604];
                        dust2.scale *= 0.8f;
                        dust2 = Main.dust[num604];
                        dust2.velocity *= 0.5f;
                    }
                    else
                    {
                        Main.dust[num604].noGravity = true;
                    }
                }
            }
            else if (type == 119 || type == 118 || type == 128 || type == 359)
            {
                int num605 = 10;
                if (type == 119 || type == 359)
                {
                    num605 = 20;
                }
                SoundEngine.PlaySound(SoundID.Item27, position);
                for (int num606 = 0; num606 < num605; num606++)
                {
                    int num607 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 92);
                    if (Main.rand.Next(3) != 0)
                    {
                        Dust dust2 = Main.dust[num607];
                        dust2.velocity *= 2f;
                        Main.dust[num607].noGravity = true;
                        dust2 = Main.dust[num607];
                        dust2.scale *= 1.75f;
                    }
                    else
                    {
                        Dust dust2 = Main.dust[num607];
                        dust2.scale *= 0.5f;
                    }
                }
            }
            else if (type == 309)
            {
                int num608 = 10;
                SoundEngine.PlaySound(SoundID.Item27, position);
                for (int num609 = 0; num609 < num608; num609++)
                {
                    int num610 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 185);
                    if (Main.rand.Next(2) == 0)
                    {
                        Dust dust2 = Main.dust[num610];
                        dust2.velocity *= 2f;
                        Main.dust[num610].noGravity = true;
                        dust2 = Main.dust[num610];
                        dust2.scale *= 1.75f;
                    }
                }
            }
            else if (type == 308)
            {
                int num611 = 80;
                SoundEngine.PlaySound(SoundID.Item27, position);
                for (int num612 = 0; num612 < num611; num612++)
                {
                    int num613 = Dust.NewDust(new Vector2(position.X, position.Y + 16f), width, height - 16, 185);
                    Dust dust2 = Main.dust[num613];
                    dust2.velocity *= 2f;
                    Main.dust[num613].noGravity = true;
                    dust2 = Main.dust[num613];
                    dust2.scale *= 1.15f;
                }
            }
            else if (aiStyle == 29 && type <= 126)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                int num614 = type - 121 + 86;
                for (int num615 = 0; num615 < 15; num615++)
                {
                    int num616 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num614, oldVelocity.X, oldVelocity.Y, 50, default(Color), 1.2f);
                    Main.dust[num616].noGravity = true;
                    Dust dust2 = Main.dust[num616];
                    dust2.scale *= 1.25f;
                    dust2 = Main.dust[num616];
                    dust2.velocity *= 0.5f;
                }
            }
            else if (type == 597)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num617 = 0; num617 < 15; num617++)
                {
                    int num618 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 262, oldVelocity.X, oldVelocity.Y, 50, default(Color), 1.2f);
                    Main.dust[num618].noGravity = true;
                    Dust dust2 = Main.dust[num618];
                    dust2.scale *= 1.25f;
                    dust2 = Main.dust[num618];
                    dust2.velocity *= 0.5f;
                }
            }
            else if (type == 731)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num619 = 0; num619 < 15; num619++)
                {
                    Dust dust50 = Dust.NewDustDirect(position, width, height, 226, oldVelocity.X * 0.5f, oldVelocity.Y * 0.5f, 50, default(Color), 0.5f);
                    if (Main.rand.Next(3) != 0)
                    {
                        dust50.noGravity = true;
                        Dust dust2 = dust50;
                        dust2.scale *= 1.5f;
                        dust2 = dust50;
                        dust2.velocity *= 0.5f;
                    }
                }
            }
            else if (type == 337)
            {
                SoundEngine.PlaySound(SoundID.Item27, position);
                for (int num620 = 0; num620 < 10; num620++)
                {
                    int num621 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 197);
                    Main.dust[num621].noGravity = true;
                }
            }
            else if (type == 379 || type == 377)
            {
                for (int num622 = 0; num622 < 5; num622++)
                {
                    int num623 = Dust.NewDust(position, width, height, 171, 0f, 0f, 100);
                    Main.dust[num623].scale = (float)Main.rand.Next(1, 10) * 0.1f;
                    Main.dust[num623].noGravity = true;
                    Main.dust[num623].fadeIn = 1.5f;
                    Dust dust2 = Main.dust[num623];
                    dust2.velocity *= 0.75f;
                }
            }
            else if (type == 80)
            {
                if (ai[0] >= 0f)
                {
                    SoundEngine.PlaySound(SoundID.Item27, position);
                    for (int num624 = 0; num624 < 10; num624++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 67);
                    }
                }
                int num625 = (int)position.X / 16;
                int num626 = (int)position.Y / 16;
                if (Main.tile[num625, num626] == null)
                {
                    Main.tile[num625, num626] = new Tile();
                }
                if (Main.tile[num625, num626].type == 127 && Main.tile[num625, num626].active())
                {
                    WorldGen.KillTile(num625, num626);
                }
            }
            else if (type == 76 || type == 77 || type == 78)
            {
                for (int num627 = 0; num627 < 5; num627++)
                {
                    int num628 = Dust.NewDust(position, width, height, 27, 0f, 0f, 80, default(Color), 1.5f);
                    Main.dust[num628].noGravity = true;
                }
            }
            else if (type == 55 || type == 719)
            {
                for (int num629 = 0; num629 < 5; num629++)
                {
                    int num630 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 18, 0f, 0f, 0, default(Color), 1.5f);
                    Main.dust[num630].noGravity = true;
                }
            }
            else if (type == 51 || type == 267)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num631 = 0; num631 < 5; num631++)
                {
                    Dust.NewDust(new Vector2(position.X, position.Y), width, height, 0, 0f, 0f, 0, default(Color), 0.7f);
                }
            }
            else if (type == 478)
            {
                if (owner == Main.myPlayer)
                {
                    NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 480, (int)((double)damage * 0.8), knockBack * 0.5f, owner);
                }
            }
            else if (type == 477 || type == 479)
            {
                for (int num632 = 0; num632 < 5; num632++)
                {
                }
                Collision.HitTiles(position, velocity, width, height);
            }
            else if (type == 2 || type == 82)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num633 = 0; num633 < 10; num633++)
                {
                    Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100);
                }
            }
            else if (type == 474)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num634 = 0; num634 < 20; num634++)
                {
                    Dust.NewDust(new Vector2(position.X, position.Y), width, height, 26, 0f, 0f, 0, default(Color), 0.9f);
                }
            }
            else if (type == 172)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num635 = 0; num635 < 20; num635++)
                {
                    Dust.NewDust(new Vector2(position.X, position.Y), width, height, 135, 0f, 0f, 100);
                }
            }
            else if (type == 103)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num636 = 0; num636 < 20; num636++)
                {
                    int num637 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 75, 0f, 0f, 100);
                    if (Main.rand.Next(2) == 0)
                    {
                        Dust dust2 = Main.dust[num637];
                        dust2.scale *= 2.5f;
                        Main.dust[num637].noGravity = true;
                        dust2 = Main.dust[num637];
                        dust2.velocity *= 5f;
                    }
                }
            }
            else if (type == 278)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num638 = 0; num638 < 20; num638++)
                {
                    int num639 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 169, 0f, 0f, 100);
                    if (Main.rand.Next(2) == 0)
                    {
                        Dust dust2 = Main.dust[num639];
                        dust2.scale *= 1.5f;
                        Main.dust[num639].noGravity = true;
                        dust2 = Main.dust[num639];
                        dust2.velocity *= 5f;
                    }
                }
            }
            else if (type == 3 || type == 48 || type == 54 || type == 599 || type == 909)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num640 = 0; num640 < 10; num640++)
                {
                    Dust.NewDust(new Vector2(position.X, position.Y), width, height, 1, velocity.X * 0.1f, velocity.Y * 0.1f, 0, default(Color), 0.75f);
                }
            }
            else if (type == 330)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num641 = 0; num641 < 10; num641++)
                {
                    Dust.NewDust(new Vector2(position.X, position.Y), width, height, 0, velocity.X * 0.4f, velocity.Y * 0.4f, 0, default(Color), 0.75f);
                }
            }
            else if (type == 4)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int num642 = 0; num642 < 10; num642++)
                {
                    Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 150, default(Color), 1.1f);
                }
            }
            else if (type == 5)
            {
                SoundEngine.PlaySound(SoundID.Item10, position);
                for (int num643 = 0; num643 < 60; num643++)
                {
                    int num644 = Main.rand.Next(3);
                    Dust.NewDust(position, width, height, num644 switch
                    {
                        0 => 15,
                        1 => 57,
                        _ => 58,
                    }, velocity.X * 0.5f, velocity.Y * 0.5f, 150, default(Color), 1.5f);
                }
            }
            else if (type == 9 || type == 12 || type == 503 || type == 955)
            {
                SoundEngine.PlaySound(SoundID.Item10, position);
                if (type == 12 || type == 955)
                {
                    Color newColor8 = Color.CornflowerBlue;
                    if (Main.tenthAnniversaryWorld && (type == 12 || type == 955))
                    {
                        newColor8 = Color.HotPink;
                        newColor8.A /= 2;
                    }
                    for (int num645 = 0; num645 < 7; num645++)
                    {
                        Dust.NewDust(position, width, height, 58, velocity.X * 0.1f, velocity.Y * 0.1f, 150, default(Color), 0.8f);
                    }
                    for (float num646 = 0f; num646 < 1f; num646 += 0.125f)
                    {
                        Dust.NewDustPerfect(base.Center, 278, Vector2.UnitY.RotatedBy(num646 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * 0.5f) * (4f + Main.rand.NextFloat() * 4f), 150, newColor8).noGravity = true;
                    }
                    for (float num647 = 0f; num647 < 1f; num647 += 0.25f)
                    {
                        Dust.NewDustPerfect(base.Center, 278, Vector2.UnitY.RotatedBy(num647 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * 0.5f) * (2f + Main.rand.NextFloat() * 3f), 150, Color.Gold).noGravity = true;
                    }
                    Vector2 vector58 = new Vector2(Main.screenWidth, Main.screenHeight);
                    if (base.Hitbox.Intersects(Utils.CenteredRectangle(Main.screenPosition + vector58 / 2f, vector58 + new Vector2(400f))))
                    {
                        for (int num648 = 0; num648 < 7; num648++)
{
                            Gore.NewGore(position, Main.rand.NextVector2CircularEdge(0.5f, 0.5f) * velocity.Length(), Utils.SelectRandom<int>(Main.rand, 16, 17, 17, 17, 17, 17, 17, 17));
                        }
                    }
                }
                else
                {
                    int num649 = 10;
                    int num650 = 3;
                    if (type == 503)
                    {
                        num649 = 40;
                        num650 = 2;
                        velocity /= 2f;
                    }
                    for (int num651 = 0; num651 < num649; num651++)
                    {
                        Dust.NewDust(position, width, height, 58, velocity.X * 0.1f, velocity.Y * 0.1f, 150, default(Color), 1.2f);
                    }
                    for (int num652 = 0; num652 < num650; num652++)
                    {
                        int num653 = Main.rand.Next(16, 18);
                        if (type == 503)
{
                            num653 = 16;
                        }
                        Gore.NewGore(position, new Vector2(velocity.X * 0.05f, velocity.Y * 0.05f), num653);
                    }
                    if (type == 12 && damage < 100)
                    {
                        for (int num654 = 0; num654 < 10; num654++)
{
                            Dust.NewDust(position, width, height, 57, velocity.X * 0.1f, velocity.Y * 0.1f, 150, default(Color), 1.2f);
                        }
                        for (int num655 = 0; num655 < 3; num655++)
{
                            Gore.NewGore(position, new Vector2(velocity.X * 0.05f, velocity.Y * 0.05f), Main.rand.Next(16, 18));
                        }
                    }
                }
            }
            else if (type == 281)
            {
                if (ai[0] != -3f)
                {
                    SoundEngine.PlaySound(4, (int)position.X, (int)position.Y);
                    int num656 = Gore.NewGore(position, new Vector2((float)Main.rand.Next(-20, 21) * 0.2f, (float)Main.rand.Next(-20, 21) * 0.2f), 76);
                    Gore gore2 = Main.gore[num656];
                    gore2.velocity -= velocity * 0.5f;
                    num656 = Gore.NewGore(new Vector2(position.X, position.Y), new Vector2((float)Main.rand.Next(-20, 21) * 0.2f, (float)Main.rand.Next(-20, 21) * 0.2f), 77);
                    gore2 = Main.gore[num656];
                    gore2.velocity -= velocity * 0.5f;
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    for (int num657 = 0; num657 < 20; num657++)
                    {
                        int num658 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                        Dust dust2 = Main.dust[num658];
                        dust2.velocity *= 1.4f;
                    }
                    for (int num659 = 0; num659 < 10; num659++)
                    {
                        int num660 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                        Main.dust[num660].noGravity = true;
                        Dust dust2 = Main.dust[num660];
                        dust2.velocity *= 5f;
                        num660 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = Main.dust[num660];
                        dust2.velocity *= 3f;
                    }
                    num656 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    gore2 = Main.gore[num656];
                    gore2.velocity *= 0.4f;
                    Main.gore[num656].velocity.X += 1f;
                    Main.gore[num656].velocity.Y += 1f;
                    num656 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    gore2 = Main.gore[num656];
                    gore2.velocity *= 0.4f;
                    Main.gore[num656].velocity.X -= 1f;
                    Main.gore[num656].velocity.Y += 1f;
                    num656 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    gore2 = Main.gore[num656];
                    gore2.velocity *= 0.4f;
                    Main.gore[num656].velocity.X += 1f;
                    Main.gore[num656].velocity.Y -= 1f;
                    num656 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    gore2 = Main.gore[num656];
                    gore2.velocity *= 0.4f;
                    Main.gore[num656].velocity.X -= 1f;
                    Main.gore[num656].velocity.Y -= 1f;
                    if (damage > 0)
                    {
                        position.X += width / 2;
                        position.Y += height / 2;
                        width = 128;
                        height = 128;
                        position.X -= width / 2;
                        position.Y -= height / 2;
                        if (ai[0] == -2f)
{
                            hostile = true;
                        }
                        Damage();
                    }
                }
            }
            else if (type == 162)
            {
                SoundEngine.PlaySound(SoundID.Item14, position);
                for (int num661 = 0; num661 < 20; num661++)
                {
                    int num662 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                    Dust dust2 = Main.dust[num662];
                    dust2.velocity *= 1.4f;
                }
                for (int num663 = 0; num663 < 10; num663++)
                {
                    int num664 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                    Main.dust[num664].noGravity = true;
                    Dust dust2 = Main.dust[num664];
                    dust2.velocity *= 5f;
                    num664 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                    dust2 = Main.dust[num664];
                    dust2.velocity *= 3f;
                }
                int num665 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num665];
                gore2.velocity *= 0.4f;
                Main.gore[num665].velocity.X += 1f;
                Main.gore[num665].velocity.Y += 1f;
                num665 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                gore2 = Main.gore[num665];
                gore2.velocity *= 0.4f;
                Main.gore[num665].velocity.X -= 1f;
                Main.gore[num665].velocity.Y += 1f;
                num665 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                gore2 = Main.gore[num665];
                gore2.velocity *= 0.4f;
                Main.gore[num665].velocity.X += 1f;
                Main.gore[num665].velocity.Y -= 1f;
                num665 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                gore2 = Main.gore[num665];
                gore2.velocity *= 0.4f;
                Main.gore[num665].velocity.X -= 1f;
                Main.gore[num665].velocity.Y -= 1f;
                position.X += width / 2;
                position.Y += height / 2;
                width = 128;
                height = 128;
                position.X -= width / 2;
                position.Y -= height / 2;
                Damage();
            }
            else if (type == 240)
            {
                SoundEngine.PlaySound(SoundID.Item14, position);
                for (int num666 = 0; num666 < 20; num666++)
                {
                    int num667 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                    Dust dust2 = Main.dust[num667];
                    dust2.velocity *= 1.4f;
                }
                for (int num668 = 0; num668 < 10; num668++)
                {
                    int num669 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                    Main.dust[num669].noGravity = true;
                    Dust dust2 = Main.dust[num669];
                    dust2.velocity *= 5f;
                    num669 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                    dust2 = Main.dust[num669];
                    dust2.velocity *= 3f;
                }
                int num670 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                Gore gore2 = Main.gore[num670];
                gore2.velocity *= 0.4f;
                Main.gore[num670].velocity.X += 1f;
                Main.gore[num670].velocity.Y += 1f;
                num670 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                gore2 = Main.gore[num670];
                gore2.velocity *= 0.4f;
                Main.gore[num670].velocity.X -= 1f;
                Main.gore[num670].velocity.Y += 1f;
                num670 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                gore2 = Main.gore[num670];
                gore2.velocity *= 0.4f;
                Main.gore[num670].velocity.X += 1f;
                Main.gore[num670].velocity.Y -= 1f;
                num670 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                gore2 = Main.gore[num670];
                gore2.velocity *= 0.4f;
                Main.gore[num670].velocity.X -= 1f;
                Main.gore[num670].velocity.Y -= 1f;
                position.X += width / 2;
                position.Y += height / 2;
                width = 96;
                height = 96;
                position.X -= width / 2;
                position.Y -= height / 2;
                Damage();
            }
            else
            {
                _ = type;
                _ = 162;
                if (type == 283 || type == 282)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num671 = 0; num671 < 10; num671++)
                    {
                        int num672 = Dust.NewDust(position, width, height, 171, 0f, 0f, 100);
                        Main.dust[num672].scale = (float)Main.rand.Next(1, 10) * 0.1f;
                        Main.dust[num672].noGravity = true;
                        Main.dust[num672].fadeIn = 1.5f;
                        Dust dust2 = Main.dust[num672];
                        dust2.velocity *= 0.75f;
                    }
                }
                else if (type == 284)
                {
                    for (int num673 = 0; num673 < 10; num673++)
                    {
                        int num674 = Main.rand.Next(139, 143);
                        int num675 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num674, (0f - velocity.X) * 0.3f, (0f - velocity.Y) * 0.3f, 0, default(Color), 1.2f);
                        Main.dust[num675].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                        Main.dust[num675].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                        Main.dust[num675].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                        Main.dust[num675].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                        Main.dust[num675].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                        Main.dust[num675].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                        Dust dust2 = Main.dust[num675];
                        dust2.scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
                    }
                    for (int num676 = 0; num676 < 5; num676++)
                    {
                        int num677 = Main.rand.Next(276, 283);
                        int num678 = Gore.NewGore(position, -velocity * 0.3f, num677);
                        Main.gore[num678].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                        Main.gore[num678].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                        Main.gore[num678].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                        Main.gore[num678].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                        Gore gore2 = Main.gore[num678];
                        gore2.scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                        Main.gore[num678].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                        Main.gore[num678].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                    }
                }
                else if (type == 286)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    for (int num679 = 0; num679 < 7; num679++)
                    {
                        int num680 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                    }
                    for (int num681 = 0; num681 < 3; num681++)
                    {
                        int num682 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                        Main.dust[num682].noGravity = true;
                        Dust dust2 = Main.dust[num682];
                        dust2.velocity *= 3f;
                        num682 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = Main.dust[num682];
                        dust2.velocity *= 2f;
                    }
                    int num683 = Gore.NewGore(new Vector2(position.X - 10f, position.Y - 10f), default(Vector2), Main.rand.Next(61, 64));
                    Gore gore2 = Main.gore[num683];
                    gore2.velocity *= 0.3f;
                    Main.gore[num683].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                    Main.gore[num683].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
                    if (owner == Main.myPlayer)
                    {
                        localAI[1] = -1f;
                        maxPenetrate = 0;
                        position.X += width / 2;
                        position.Y += height / 2;
                        width = 80;
                        height = 80;
                        position.X -= width / 2;
                        position.Y -= height / 2;
                        Damage();
                    }
                }
                else if (type == 14 || type == 20 || type == 36 || type == 83 || type == 84 || type == 389 || type == 104 || type == 279 || type == 100 || type == 110 || type == 180 || type == 207 || type == 357 || type == 242 || type == 302 || type == 257 || type == 259 || type == 285 || type == 287 || type == 576 || type == 577 || type == 876 || type == 968)
                {
                    Collision.HitTiles(position, velocity, width, height);
                    SoundEngine.PlaySound(SoundID.Item10, position);
                }
                else if (type == 981)
                {
                    Collision.HitTiles(position, velocity, width, height);
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.SilverBulletSparkle, new ParticleOrchestraSettings
                    {
                        PositionInWorld = base.Center,
                        MovementVector = Vector2.Zero
                    }, owner);
                }
                else if (type == 1006)
                {
                    Collision.HitTiles(position, velocity, width, height);
                    SoundEngine.PlaySound(0, position);
                    float num684 = Main.rand.NextFloat() * ((float)Math.PI * 2f);
                    for (float num685 = 0f; num685 < 1f; num685 += 1f)
                    {
                        float num686 = num684 + (float)Math.PI * 2f * num685;
                        Vector2 vector59 = Vector2.UnitX.RotatedBy(num686);
                        Vector2 center = base.Center;
                        float num687 = 0.4f;
                        ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.ShimmerArrow, new ParticleOrchestraSettings
{
                            PositionInWorld = center,
                            MovementVector = vector59 * num687
                        }, owner);
                    }
                }
                else if (type == 660)
                {
                    Collision.HitTiles(position, velocity, width, height);
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    int num688 = Main.rand.Next(4, 10);
                    for (int num689 = 0; num689 < num688; num689++)
                    {
                        int num690 = Dust.NewDust(base.Center, 0, 0, 180, 0f, 0f, 100);
                        Dust dust2 = Main.dust[num690];
                        dust2.velocity *= 1.6f;
                        Main.dust[num690].velocity.Y -= 1f;
                        dust2 = Main.dust[num690];
                        dust2.velocity += -velocity * (Main.rand.NextFloat() * 2f - 1f) * 0.5f;
                        Main.dust[num690].scale = 2f;
                        Main.dust[num690].fadeIn = 0.5f;
                        Main.dust[num690].noGravity = true;
                    }
                }
                else if (type == 761 || type == 762)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    if (owner == Main.myPlayer && !noDropItem)
                    {
                        int num691 = 4343;
                        if (type == 762)
{
                            num691 = 4344;
                        }
                        int num692 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, num691);
                        Main.item[num692].noGrabDelay = 0;
                        if (Main.netMode == 1 && num692 >= 0)
{
                            NetMessage.SendData(21, -1, -1, null, num692, 1f);
                        }
                    }
                }
                else if (type == 712)
                {
                    Collision.HitTiles(position, velocity, width, height);
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    int num693 = Main.rand.Next(6, 12);
                    for (int num694 = 0; num694 < num693; num694++)
                    {
                        int num695 = Dust.NewDust(base.Center, 0, 0, 15, 0f, 0f, 100);
                        Dust dust2 = Main.dust[num695];
                        dust2.velocity *= 1.6f;
                        Main.dust[num695].velocity.Y -= 1f;
                        dust2 = Main.dust[num695];
                        dust2.velocity += -velocity * (Main.rand.NextFloat() * 2f - 1f) * 0.5f;
                        Main.dust[num695].scale = 1f;
                        Main.dust[num695].fadeIn = 1.5f;
                        Main.dust[num695].noGravity = true;
                        Main.dust[num695].color = new Color(255, 255, 255, 0) * 0.3f;
                        dust2 = Main.dust[num695];
                        dust2.velocity *= 0.7f;
                        dust2 = Main.dust[num695];
                        dust2.position += Main.dust[num695].velocity * 5f;
                    }
                    for (int num696 = 0; num696 < 3; num696++)
                    {
                        Gore gore5 = Gore.NewGoreDirect(position, Vector2.Zero, 1008, 1f + Main.rand.NextFloatDirection() * 0.2f);
                        Gore gore2 = gore5;
                        gore2.velocity *= 4f;
                    }
                }
                else if (type == 638)
                {
                    Collision.HitTiles(position, velocity, width, height);
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    int num697 = Main.rand.Next(2, 5);
                    for (int num698 = 0; num698 < num697; num698++)
                    {
                        int num699 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100);
                        Dust dust2 = Main.dust[num699];
                        dust2.velocity *= 1.6f;
                        Main.dust[num699].velocity.Y -= 1f;
                        dust2 = Main.dust[num699];
                        dust2.position -= Vector2.One * 4f;
                        Main.dust[num699].position = Vector2.Lerp(Main.dust[num699].position, base.Center, 0.5f);
                        Main.dust[num699].noGravity = true;
                    }
                }
                else if (type == 15 || type == 321)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num700 = 0; num700 < 20; num700++)
                    {
                        int num701 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100, default(Color), 2f);
                        Main.dust[num701].noGravity = true;
                        Dust dust2 = Main.dust[num701];
                        dust2.velocity *= 2f;
                        num701 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100);
                        dust2 = Main.dust[num701];
                        dust2.velocity *= 2f;
                    }
                }
                else if (type == 253)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num702 = 0; num702 < 20; num702++)
                    {
                        int num703 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 135, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100, default(Color), 2f);
                        Main.dust[num703].noGravity = true;
                        Dust dust2 = Main.dust[num703];
                        dust2.velocity *= 2f;
                        num703 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 135, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100);
                        dust2 = Main.dust[num703];
                        dust2.velocity *= 2f;
                    }
                }
                else if (type == 95 || type == 96)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num704 = 0; num704 < 20; num704++)
                    {
                        int num705 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 75, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100, default(Color), 2f * scale);
                        Main.dust[num705].noGravity = true;
                        Dust dust2 = Main.dust[num705];
                        dust2.velocity *= 2f;
                        num705 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 75, (0f - velocity.X) * 0.2f, (0f - velocity.Y) * 0.2f, 100, default(Color), 1f * scale);
                        dust2 = Main.dust[num705];
                        dust2.velocity *= 2f;
                    }
                }
                else if (type == 17)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num706 = 0; num706 < 5; num706++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 0);
                    }
                }
                else if (type == 31 || type == 42)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num707 = 0; num707 < 5; num707++)
                    {
                        int num708 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 32);
                        Dust dust2 = Main.dust[num708];
                        dust2.velocity *= 0.6f;
                    }
                }
                else if (type >= 411 && type <= 414)
                {
                    int num709 = 9;
                    if (type == 412 || type == 414)
                    {
                        num709 = 11;
                    }
                    if (type == 413)
                    {
                        num709 = 19;
                    }
                    for (int num710 = 0; num710 < 5; num710++)
                    {
                        int num711 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num709, 0f, velocity.Y / 2f);
                        Main.dust[num711].noGravity = true;
                        Dust dust2 = Main.dust[num711];
                        dust2.velocity -= velocity * 0.5f;
                    }
                }
                else if (type == 109)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num712 = 0; num712 < 5; num712++)
                    {
                        int num713 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 51, 0f, 0f, 0, default(Color), 0.6f);
                        Dust dust2 = Main.dust[num713];
                        dust2.velocity *= 0.6f;
                    }
                }
                else if (type == 39)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num714 = 0; num714 < 5; num714++)
                    {
                        int num715 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 38);
                        Dust dust2 = Main.dust[num715];
                        dust2.velocity *= 0.6f;
                    }
                }
                else if (type == 71)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num716 = 0; num716 < 5; num716++)
                    {
                        int num717 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 53);
                        Dust dust2 = Main.dust[num717];
                        dust2.velocity *= 0.6f;
                    }
                }
                else if (type == 179)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num718 = 0; num718 < 5; num718++)
                    {
                        int num719 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 149);
                        Dust dust2 = Main.dust[num719];
                        dust2.velocity *= 0.6f;
                    }
                }
                else if (type == 40)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num720 = 0; num720 < 5; num720++)
                    {
                        int num721 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 36);
                        Dust dust2 = Main.dust[num721];
                        dust2.velocity *= 0.6f;
                    }
                }
                else if (type == 21 || type == 471 || type == 532)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num722 = 0; num722 < 10; num722++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 26, 0f, 0f, 0, default(Color), 0.8f);
                    }
                }
                else if (type == 583)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num723 = 0; num723 < 10; num723++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 4, 0f, 0f, 100, new Color(20, 250, 20, 240), 0.8f);
                    }
                }
                else if (type == 584)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int num724 = 0; num724 < 10; num724++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 4, 0f, 0f, 100, new Color(250, 20, 120, 240), 0.8f);
                    }
                }
                else if (type == 24)
                {
                    for (int num725 = 0; num725 < 10; num725++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 1, velocity.X * 0.1f, velocity.Y * 0.1f, 0, default(Color), 0.75f);
                    }
                }
                else if (type == 27)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num726 = 0; num726 < 30; num726++)
                    {
                        int num727 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 172, velocity.X * 0.1f, velocity.Y * 0.1f, 100);
                        Main.dust[num727].noGravity = true;
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 172, velocity.X * 0.1f, velocity.Y * 0.1f, 100, default(Color), 0.5f);
                    }
                }
                else if (type == 38)
                {
                    for (int num728 = 0; num728 < 10; num728++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 42, velocity.X * 0.1f, velocity.Y * 0.1f);
                    }
                }
                else if (type == 44 || type == 45)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num729 = 0; num729 < 30; num729++)
                    {
                        int num730 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 27, velocity.X, velocity.Y, 100, default(Color), 1.7f);
                        Main.dust[num730].noGravity = true;
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 27, velocity.X, velocity.Y, 100);
                    }
                }
                else if (type == 41)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    for (int num731 = 0; num731 < 10; num731++)
                    {
                        int num732 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                    }
                    for (int num733 = 0; num733 < 5; num733++)
                    {
                        int num734 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                        Main.dust[num734].noGravity = true;
                        Dust dust2 = Main.dust[num734];
                        dust2.velocity *= 3f;
                        num734 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = Main.dust[num734];
                        dust2.velocity *= 2f;
                    }
                    int num735 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    Gore gore2 = Main.gore[num735];
                    gore2.velocity *= 0.4f;
                    Main.gore[num735].velocity.X += (float)Main.rand.Next(-10, 11) * 0.1f;
                    Main.gore[num735].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.1f;
                    num735 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    gore2 = Main.gore[num735];
                    gore2.velocity *= 0.4f;
                    Main.gore[num735].velocity.X += (float)Main.rand.Next(-10, 11) * 0.1f;
                    Main.gore[num735].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.1f;
                    if (owner == Main.myPlayer)
                    {
                        penetrate = -1;
                        position.X += width / 2;
                        position.Y += height / 2;
                        width = 64;
                        height = 64;
                        position.X -= width / 2;
                        position.Y -= height / 2;
                        Damage();
                    }
                }
                else if (type == 514)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    for (int num736 = 0; num736 < 10; num736++)
                    {
                        int num737 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.3f);
                        Dust dust2 = Main.dust[num737];
                        dust2.velocity *= 1.4f;
                    }
                    for (int num738 = 0; num738 < 6; num738++)
                    {
                        int num739 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.1f);
                        Main.dust[num739].noGravity = true;
                        Dust dust2 = Main.dust[num739];
                        dust2.velocity *= 4.6f;
                        num739 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.3f);
                        dust2 = Main.dust[num739];
                        dust2.velocity *= 3.3f;
                        if (Main.rand.Next(2) == 0)
{
                            num739 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.1f);
                            dust2 = Main.dust[num739];
                            dust2.velocity *= 2.7f;
                        }
                    }
                    if (owner == Main.myPlayer)
                    {
                        penetrate = -1;
                        position.X += width / 2;
                        position.Y += height / 2;
                        width = 112;
                        height = 112;
                        position.X -= width / 2;
                        position.Y -= height / 2;
                        ai[0] = 2f;
                        Damage();
                    }
                }
                else if (type == 306)
                {
                    SoundEngine.PlaySound(3, (int)position.X, (int)position.Y);
                    for (int num740 = 0; num740 < 20; num740++)
                    {
                        int num741 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 184);
                        Dust dust2 = Main.dust[num741];
                        dust2.scale *= 1.1f;
                        Main.dust[num741].noGravity = true;
                    }
                    for (int num742 = 0; num742 < 30; num742++)
                    {
                        int num743 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 184);
                        Dust dust2 = Main.dust[num743];
                        dust2.velocity *= 2.5f;
                        dust2 = Main.dust[num743];
                        dust2.scale *= 0.8f;
                        Main.dust[num743].noGravity = true;
                    }
                    if (owner == Main.myPlayer)
                    {
                        int num744 = Main.rand.Next(2, 5);
                        if (Main.rand.Next(1, 101) == 100)
{
                            num744 = 15;
                        }
                        for (int num745 = 0; num745 < num744; num745++)
{
                            float num746 = (float)Main.rand.Next(-35, 36) * 0.02f;
                            float num747 = (float)Main.rand.Next(-35, 36) * 0.02f;
                            num746 *= 10f;
                            num747 *= 10f;
                            NewProjectile(GetProjectileSource_FromThis(), position.X, position.Y, num746, num747, 307, (int)((double)damage * 0.75), (int)((double)knockBack * 0.35), Main.myPlayer);
                        }
                    }
                }
                else if (type == 469)
                {
                    if (owner == Main.myPlayer)
                    {
                        int num748 = 6;
                        for (int num749 = 0; num749 < num748; num749++)
{
                            if (num749 % 2 != 1 || Main.rand.Next(3) == 0)
{
                                Vector2 vector60 = position;
                                Vector2 vector61 = oldVelocity;
                                vector61.Normalize();
                                vector61 *= 8f;
                                float num750 = (float)Main.rand.Next(-35, 36) * 0.01f;
                                float num751 = (float)Main.rand.Next(-35, 36) * 0.01f;
                                vector60 -= vector61 * num749;
                                num750 += oldVelocity.X / 6f;
                                num751 += oldVelocity.Y / 6f;
                                int num752 = NewProjectile(GetProjectileSource_FromThis(), vector60.X, vector60.Y, num750, num751, Main.player[owner].beeType(), Main.player[owner].beeDamage(damage / 3), Main.player[owner].beeKB(0f), Main.myPlayer);
                                Main.projectile[num752].magic = false;
                                Main.projectile[num752].ranged = true;
                                Main.projectile[num752].penetrate = 2;
                            }
                        }
                    }
                }
                else if (type == 183)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    for (int num753 = 0; num753 < 20; num753++)
                    {
                        int num754 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                        Dust dust2 = Main.dust[num754];
                        dust2.velocity *= 1f;
                    }
                    int num755 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    Main.gore[num755].velocity.X += 1f;
                    Main.gore[num755].velocity.Y += 1f;
                    Gore gore2 = Main.gore[num755];
                    gore2.velocity *= 0.3f;
                    num755 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    Main.gore[num755].velocity.X -= 1f;
                    Main.gore[num755].velocity.Y += 1f;
                    gore2 = Main.gore[num755];
                    gore2.velocity *= 0.3f;
                    num755 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    Main.gore[num755].velocity.X += 1f;
                    Main.gore[num755].velocity.Y -= 1f;
                    gore2 = Main.gore[num755];
                    gore2.velocity *= 0.3f;
                    num755 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    Main.gore[num755].velocity.X -= 1f;
                    Main.gore[num755].velocity.Y -= 1f;
                    gore2 = Main.gore[num755];
                    gore2.velocity *= 0.3f;
                    if (owner == Main.myPlayer)
                    {
                        int num756 = Main.rand.Next(15, 25);
                        for (int num757 = 0; num757 < num756; num757++)
{
                            float speedX = (float)Main.rand.Next(-35, 36) * 0.02f;
                            float speedY = (float)Main.rand.Next(-35, 36) * 0.02f;
                            NewProjectile(GetProjectileSource_FromThis(), position.X, position.Y, speedX, speedY, Main.player[owner].beeType(), Main.player[owner].beeDamage(damage), Main.player[owner].beeKB(0f), Main.myPlayer);
                        }
                    }
                }
                else if (aiStyle == 34)
                {
                    if (owner != Main.myPlayer)
                    {
                        timeLeft = 60;
                    }
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    if (type == 167)
                    {
                        for (int num758 = 0; num758 < 400; num758++)
{
                            float num759 = 16f;
                            if (num758 < 300)
{
                                num759 = 12f;
                            }
                            if (num758 < 200)
{
                                num759 = 8f;
                            }
                            if (num758 < 100)
{
                                num759 = 4f;
                            }
                            int num760 = 130;
                            int num761 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num760, 0f, 0f, 100);
                            float num762 = Main.dust[num761].velocity.X;
                            float y2 = Main.dust[num761].velocity.Y;
                            if (num762 == 0f && y2 == 0f)
{
                                num762 = 1f;
                            }
                            float num763 = (float)Math.Sqrt(num762 * num762 + y2 * y2);
                            num763 = num759 / num763;
                            num762 *= num763;
                            y2 *= num763;
                            Dust dust2 = Main.dust[num761];
                            dust2.velocity *= 0.5f;
                            Main.dust[num761].velocity.X += num762;
                            Main.dust[num761].velocity.Y += y2;
                            Main.dust[num761].scale = 1.3f;
                            Main.dust[num761].noGravity = true;
                        }
                    }
                    if (type == 168)
                    {
                        for (int num764 = 0; num764 < 400; num764++)
{
                            float num765 = 2f * ((float)num764 / 100f);
                            if (num764 > 100)
{
                                num765 = 10f;
                            }
                            if (num764 > 250)
{
                                num765 = 13f;
                            }
                            int num766 = 131;
                            int num767 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num766, 0f, 0f, 100);
                            float num768 = Main.dust[num767].velocity.X;
                            float y3 = Main.dust[num767].velocity.Y;
                            if (num768 == 0f && y3 == 0f)
{
                                num768 = 1f;
                            }
                            float num769 = (float)Math.Sqrt(num768 * num768 + y3 * y3);
                            num769 = num765 / num769;
                            if (num764 <= 200)
{
                                num768 *= num769;
                                y3 *= num769;
                            }
                            else
{
                                num768 = num768 * num769 * 1.25f;
                                y3 = y3 * num769 * 0.75f;
                            }
                            Dust dust2 = Main.dust[num767];
                            dust2.velocity *= 0.5f;
                            Main.dust[num767].velocity.X += num768;
                            Main.dust[num767].velocity.Y += y3;
                            if (num764 > 100)
{
                                Main.dust[num767].scale = 1.3f;
                                Main.dust[num767].noGravity = true;
                            }
                        }
                    }
                    if (type == 169)
                    {
                        Vector2 vector62 = ((float)Main.rand.NextDouble() * ((float)Math.PI * 2f)).ToRotationVector2();
                        float num770 = Main.rand.Next(5, 9);
                        float num771 = Main.rand.Next(12, 17);
                        float value9 = Main.rand.Next(3, 7);
                        float num772 = 20f;
                        for (float num773 = 0f; num773 < num770; num773++)
{
                            for (int num774 = 0; num774 < 2; num774++)
{
                                Vector2 value10 = vector62.RotatedBy(((num774 == 0) ? 1f : (-1f)) * ((float)Math.PI * 2f) / (num770 * 2f));
                                for (float num775 = 0f; num775 < num772; num775++)
{
                                    Vector2 vector63 = Vector2.Lerp(vector62, value10, num775 / num772);
                                    float num776 = MathHelper.Lerp(num771, value9, num775 / num772);
                                    int num777 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, 133, 0f, 0f, 100, default(Color), 1.3f);
                                    Dust dust2 = Main.dust[num777];
                                    dust2.velocity *= 0.1f;
                                    Main.dust[num777].noGravity = true;
                                    dust2 = Main.dust[num777];
                                    dust2.velocity += vector63 * num776;
                                }
                            }
                            vector62 = vector62.RotatedBy((float)Math.PI * 2f / num770);
                        }
                        for (float num778 = 0f; num778 < num770; num778++)
{
                            for (int num779 = 0; num779 < 2; num779++)
{
                                Vector2 value11 = vector62.RotatedBy(((num779 == 0) ? 1f : (-1f)) * ((float)Math.PI * 2f) / (num770 * 2f));
                                for (float num780 = 0f; num780 < num772; num780++)
{
                                    Vector2 vector64 = Vector2.Lerp(vector62, value11, num780 / num772);
                                    float num781 = MathHelper.Lerp(num771, value9, num780 / num772) / 2f;
                                    int num782 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, 133, 0f, 0f, 100, default(Color), 1.3f);
                                    Dust dust2 = Main.dust[num782];
                                    dust2.velocity *= 0.1f;
                                    Main.dust[num782].noGravity = true;
                                    dust2 = Main.dust[num782];
                                    dust2.velocity += vector64 * num781;
                                }
                            }
                            vector62 = vector62.RotatedBy((float)Math.PI * 2f / num770);
                        }
                        for (int num783 = 0; num783 < 100; num783++)
{
                            float num784 = num771;
                            int num785 = 132;
                            int num786 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num785, 0f, 0f, 100);
                            float num787 = Main.dust[num786].velocity.X;
                            float y4 = Main.dust[num786].velocity.Y;
                            if (num787 == 0f && y4 == 0f)
{
                                num787 = 1f;
                            }
                            float num788 = (float)Math.Sqrt(num787 * num787 + y4 * y4);
                            num788 = num784 / num788;
                            num787 *= num788;
                            y4 *= num788;
                            Dust dust2 = Main.dust[num786];
                            dust2.velocity *= 0.5f;
                            Main.dust[num786].velocity.X += num787;
                            Main.dust[num786].velocity.Y += y4;
                            Main.dust[num786].scale = 1.3f;
                            Main.dust[num786].noGravity = true;
                        }
                    }
                    if (type == 170)
                    {
                        for (int num789 = 0; num789 < 400; num789++)
{
                            int num790 = 133;
                            float num791 = 16f;
                            if (num789 > 100)
{
                                num791 = 11f;
                            }
                            if (num789 > 100)
{
                                num790 = 134;
                            }
                            if (num789 > 200)
{
                                num791 = 8f;
                            }
                            if (num789 > 200)
{
                                num790 = 133;
                            }
                            if (num789 > 300)
{
                                num791 = 5f;
                            }
                            if (num789 > 300)
{
                                num790 = 134;
                            }
                            int num792 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num790, 0f, 0f, 100);
                            float num793 = Main.dust[num792].velocity.X;
                            float y5 = Main.dust[num792].velocity.Y;
                            if (num793 == 0f && y5 == 0f)
{
                                num793 = 1f;
                            }
                            float num794 = (float)Math.Sqrt(num793 * num793 + y5 * y5);
                            num794 = num791 / num794;
                            if (num789 > 300)
{
                                num793 = num793 * num794 * 0.7f;
                                y5 *= num794;
                            }
                            else if (num789 > 200)
{
                                num793 *= num794;
                                y5 = y5 * num794 * 0.7f;
                            }
                            else if (num789 > 100)
{
                                num793 = num793 * num794 * 0.7f;
                                y5 *= num794;
                            }
                            else
{
                                num793 *= num794;
                                y5 = y5 * num794 * 0.7f;
                            }
                            Dust dust2 = Main.dust[num792];
                            dust2.velocity *= 0.5f;
                            Main.dust[num792].velocity.X += num793;
                            Main.dust[num792].velocity.Y += y5;
                            if (Main.rand.Next(3) != 0)
{
                                Main.dust[num792].scale = 1.3f;
                                Main.dust[num792].noGravity = true;
                            }
                        }
                    }
                    if (type == 415)
                    {
                        Vector2 vector65 = (vector65 = ((float)Main.rand.NextDouble() * ((float)Math.PI * 2f)).ToRotationVector2());
                        float num795 = Main.rand.Next(5, 9);
                        float num796 = (float)Main.rand.Next(10, 15) * 0.66f;
                        float num797 = (float)Main.rand.Next(4, 7) / 2f;
                        int num798 = 30;
                        for (int num799 = 0; (float)num799 < (float)num798 * num795; num799++)
{
                            if (num799 % num798 == 0)
{
                                vector65 = vector65.RotatedBy((float)Math.PI * 2f / num795);
                            }
                            float num800 = MathHelper.Lerp(num797, num796, (float)(num799 % num798) / (float)num798);
                            int num801 = 130;
                            int num802 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num801, 0f, 0f, 100);
                            Dust dust2 = Main.dust[num802];
                            dust2.velocity *= 0.1f;
                            dust2 = Main.dust[num802];
                            dust2.velocity += vector65 * num800;
                            Main.dust[num802].scale = 1.3f;
                            Main.dust[num802].noGravity = true;
                        }
                        for (int num803 = 0; num803 < 100; num803++)
{
                            float num804 = num796;
                            if (num803 < 30)
{
                                num804 = (num797 + num796) / 2f;
                            }
                            int num805 = 130;
                            int num806 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num805, 0f, 0f, 100);
                            float num807 = Main.dust[num806].velocity.X;
                            float y6 = Main.dust[num806].velocity.Y;
                            if (num807 == 0f && y6 == 0f)
{
                                num807 = 1f;
                            }
                            float num808 = (float)Math.Sqrt(num807 * num807 + y6 * y6);
                            num808 = num804 / num808;
                            num807 *= num808;
                            y6 *= num808;
                            Dust dust2 = Main.dust[num806];
                            dust2.velocity *= 0.5f;
                            Main.dust[num806].velocity.X += num807;
                            Main.dust[num806].velocity.Y += y6;
                            Main.dust[num806].scale = 1.3f;
                            Main.dust[num806].noGravity = true;
                        }
                    }
                    if (type == 416)
                    {
                        Vector2 vector66 = ((float)Main.rand.NextDouble() * ((float)Math.PI * 2f)).ToRotationVector2();
                        Vector2 vector67 = vector66;
                        float num809 = Main.rand.Next(3, 6) * 2;
                        int num810 = 20;
                        float num811 = ((Main.rand.Next(2) == 0) ? 1f : (-1f));
                        bool flag3 = true;
                        for (int num812 = 0; (float)num812 < (float)num810 * num809; num812++)
{
                            if (num812 % num810 == 0)
{
                                vector67 = vector67.RotatedBy(num811 * ((float)Math.PI * 2f / num809));
                                vector66 = vector67;
                                flag3 = !flag3;
                            }
                            else
{
                                float num813 = (float)Math.PI * 2f / ((float)num810 * num809);
                                vector66 = vector66.RotatedBy(num813 * num811 * 3f);
                            }
                            float num814 = MathHelper.Lerp(1f, 8f, (float)(num812 % num810) / (float)num810);
                            int num815 = 131;
                            int num816 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num815, 0f, 0f, 100, default(Color), 1.4f);
                            Dust dust2 = Main.dust[num816];
                            dust2.velocity *= 0.1f;
                            dust2 = Main.dust[num816];
                            dust2.velocity += vector66 * num814;
                            if (flag3)
{
                                Main.dust[num816].scale = 0.9f;
                            }
                            Main.dust[num816].noGravity = true;
                        }
                    }
                    if (type == 417)
                    {
                        float num817 = (float)Main.rand.NextDouble() * ((float)Math.PI * 2f);
                        float num818 = (float)Main.rand.NextDouble() * ((float)Math.PI * 2f);
                        float num819 = 4f + (float)Main.rand.NextDouble() * 3f;
                        float num820 = 4f + (float)Main.rand.NextDouble() * 3f;
                        float num821 = num819;
                        if (num820 > num821)
{
                            num821 = num820;
                        }
                        for (int num822 = 0; num822 < 150; num822++)
{
                            int num823 = 132;
                            float num824 = num821;
                            if (num822 > 50)
{
                                num824 = num820;
                            }
                            if (num822 > 50)
{
                                num823 = 133;
                            }
                            if (num822 > 100)
{
                                num824 = num819;
                            }
                            if (num822 > 100)
{
                                num823 = 132;
                            }
                            int num825 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num823, 0f, 0f, 100);
                            Vector2 vector68 = Main.dust[num825].velocity;
                            vector68.Normalize();
                            vector68 *= num824;
                            if (num822 > 100)
{
                                vector68.X *= 0.5f;
                                vector68 = vector68.RotatedBy(num817);
                            }
                            else if (num822 > 50)
{
                                vector68.Y *= 0.5f;
                                vector68 = vector68.RotatedBy(num818);
                            }
                            Dust dust2 = Main.dust[num825];
                            dust2.velocity *= 0.2f;
                            dust2 = Main.dust[num825];
                            dust2.velocity += vector68;
                            if (num822 <= 200)
{
                                Main.dust[num825].scale = 1.3f;
                                Main.dust[num825].noGravity = true;
                            }
                        }
                    }
                    if (type == 418)
                    {
                        Vector2 vector69 = ((float)Main.rand.NextDouble() * ((float)Math.PI * 2f)).ToRotationVector2();
                        float num826 = Main.rand.Next(5, 12);
                        float num827 = (float)Main.rand.Next(9, 14) * 0.66f;
                        float num828 = (float)Main.rand.Next(2, 4) * 0.66f;
                        float num829 = 15f;
                        for (float num830 = 0f; num830 < num826; num830++)
{
                            for (int num831 = 0; num831 < 2; num831++)
{
                                Vector2 value12 = vector69.RotatedBy(((num831 == 0) ? 1f : (-1f)) * ((float)Math.PI * 2f) / (num826 * 2f));
                                for (float num832 = 0f; num832 < num829; num832++)
{
                                    Vector2 vector70 = Vector2.SmoothStep(vector69, value12, num832 / num829);
                                    float num833 = MathHelper.SmoothStep(num827, num828, num832 / num829);
                                    int num834 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, 134, 0f, 0f, 100, default(Color), 1.3f);
                                    Dust dust2 = Main.dust[num834];
                                    dust2.velocity *= 0.1f;
                                    Main.dust[num834].noGravity = true;
                                    dust2 = Main.dust[num834];
                                    dust2.velocity += vector70 * num833;
                                }
                            }
                            vector69 = vector69.RotatedBy((float)Math.PI * 2f / num826);
                        }
                        for (int num835 = 0; num835 < 120; num835++)
{
                            float num836 = num827;
                            int num837 = 133;
                            if (num835 < 80)
{
                                num836 = num828 - 0.5f;
                            }
                            else
{
                                num837 = 131;
                            }
                            int num838 = Dust.NewDust(new Vector2(position.X, position.Y), 6, 6, num837, 0f, 0f, 100);
                            float num839 = Main.dust[num838].velocity.X;
                            float y7 = Main.dust[num838].velocity.Y;
                            if (num839 == 0f && y7 == 0f)
{
                                num839 = 1f;
                            }
                            float num840 = (float)Math.Sqrt(num839 * num839 + y7 * y7);
                            num840 = num836 / num840;
                            num839 *= num840;
                            y7 *= num840;
                            Dust dust2 = Main.dust[num838];
                            dust2.velocity *= 0.2f;
                            Main.dust[num838].velocity.X += num839;
                            Main.dust[num838].velocity.Y += y7;
                            Main.dust[num838].scale = 1.3f;
                            Main.dust[num838].noGravity = true;
                        }
                    }
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 192;
                    height = 192;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                    penetrate = -1;
                    Damage();
                }
                else if (type == 312)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 22;
                    height = 22;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                    for (int num841 = 0; num841 < 30; num841++)
                    {
                        int num842 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                        Dust dust2 = Main.dust[num842];
                        dust2.velocity *= 1.4f;
                    }
                    for (int num843 = 0; num843 < 20; num843++)
                    {
                        int num844 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 3.5f);
                        Main.dust[num844].noGravity = true;
                        Dust dust2 = Main.dust[num844];
                        dust2.velocity *= 7f;
                        num844 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = Main.dust[num844];
                        dust2.velocity *= 3f;
                    }
                    for (int num845 = 0; num845 < 2; num845++)
                    {
                        float num846 = 0.4f;
                        if (num845 == 1)
{
                            num846 = 0.8f;
                        }
                        int num847 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                        Gore gore2 = Main.gore[num847];
                        gore2.velocity *= num846;
                        Main.gore[num847].velocity.X += 1f;
                        Main.gore[num847].velocity.Y += 1f;
                        num847 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num847];
                        gore2.velocity *= num846;
                        Main.gore[num847].velocity.X -= 1f;
                        Main.gore[num847].velocity.Y += 1f;
                        num847 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num847];
                        gore2.velocity *= num846;
                        Main.gore[num847].velocity.X += 1f;
                        Main.gore[num847].velocity.Y -= 1f;
                        num847 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num847];
                        gore2.velocity *= num846;
                        Main.gore[num847].velocity.X -= 1f;
                        Main.gore[num847].velocity.Y -= 1f;
                    }
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 128;
                    height = 128;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                    Damage();
                }
                else if (type == 910 || type == 911)
                {
                    Resize(22, 22);
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    Color transparent2 = Color.Transparent;
                    int num848 = 0;
                    for (int num849 = 0; num849 < 30; num849++)
                    {
                        Dust dust51 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, transparent2, 1.5f);
                        Dust dust2 = dust51;
                        dust2.velocity *= 1.4f;
                    }
                    for (int num850 = 0; num850 < 80; num850++)
                    {
                        Dust dust52 = Dust.NewDustDirect(position, width, height, num848, 0f, 0f, 100, transparent2, 2.2f);
                        dust52.noGravity = true;
                        dust52.velocity.Y -= 1.2f;
                        Dust dust2 = dust52;
                        dust2.velocity *= 4f;
                        dust52 = Dust.NewDustDirect(position, width, height, num848, 0f, 0f, 100, transparent2, 1.3f);
                        dust52.velocity.Y -= 1.2f;
                        dust2 = dust52;
                        dust2.velocity *= 2f;
                    }
                    for (int num851 = 1; num851 <= 2; num851++)
                    {
                        for (int num852 = -1; num852 <= 1; num852 += 2)
{
                            for (int num853 = -1; num853 <= 1; num853 += 2)
{
                                Gore gore6 = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                                Gore gore2 = gore6;
                                gore2.velocity *= ((num851 == 1) ? 0.4f : 0.8f);
                                gore2 = gore6;
                                gore2.velocity += new Vector2(num852, num853);
                            }
                        }
                    }
                    if (Main.netMode != 1)
                    {
                        Point pt = base.Center.ToTileCoordinates();
                        Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(pt, 4.2f, DelegateMethods.SpreadDirt);
                    }
                }
                else if (type == 784 || type == 785 || type == 786 || type == 805 || type == 903)
                {
                    Resize(22, 22);
                    if (type == 785)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, position);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, position);
                    }
                    Color transparent3 = Color.Transparent;
                    int num854 = Dust.dustWater();
                    for (int num855 = 0; num855 < 30; num855++)
                    {
                        Dust dust53 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, transparent3, 1.5f);
                        Dust dust2 = dust53;
                        dust2.velocity *= 1.4f;
                    }
                    for (int num856 = 0; num856 < 80; num856++)
                    {
                        Dust dust54 = Dust.NewDustDirect(position, width, height, num854, 0f, 0f, 100, transparent3, 2.2f);
                        dust54.noGravity = true;
                        dust54.velocity.Y -= 1.2f;
                        Dust dust2 = dust54;
                        dust2.velocity *= 7f;
                        dust54 = Dust.NewDustDirect(position, width, height, num854, 0f, 0f, 100, transparent3, 1.3f);
                        dust54.velocity.Y -= 1.2f;
                        dust2 = dust54;
                        dust2.velocity *= 4f;
                    }
                    for (int num857 = 1; num857 <= 2; num857++)
                    {
                        for (int num858 = -1; num858 <= 1; num858 += 2)
{
                            for (int num859 = -1; num859 <= 1; num859 += 2)
{
                                Gore gore7 = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                                Gore gore2 = gore7;
                                gore2.velocity *= ((num857 == 1) ? 0.4f : 0.8f);
                                gore2 = gore7;
                                gore2.velocity += new Vector2(num858, num859);
                            }
                        }
                    }
                    if (Main.netMode != 1)
                    {
                        Point pt2 = base.Center.ToTileCoordinates();
                        Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(pt2, 3f, DelegateMethods.SpreadWater);
                    }
                }
                else if (type == 787 || type == 788 || type == 789 || type == 806 || type == 904)
                {
                    Resize(22, 22);
                    if (type == 788)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, position);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, position);
                    }
                    Color transparent4 = Color.Transparent;
                    int num860 = 35;
                    for (int num861 = 0; num861 < 30; num861++)
                    {
                        Dust dust55 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, transparent4, 1.5f);
                        Dust dust2 = dust55;
                        dust2.velocity *= 1.4f;
                    }
                    for (int num862 = 0; num862 < 80; num862++)
                    {
                        Dust dust56 = Dust.NewDustDirect(position, width, height, num860, 0f, 0f, 100, transparent4, 1.2f);
                        Dust dust2 = dust56;
                        dust2.velocity *= 7f;
                        dust56 = Dust.NewDustDirect(position, width, height, num860, 0f, 0f, 100, transparent4, 0.3f);
                        dust2 = dust56;
                        dust2.velocity *= 4f;
                    }
                    for (int num863 = 1; num863 <= 2; num863++)
                    {
                        for (int num864 = -1; num864 <= 1; num864 += 2)
{
                            for (int num865 = -1; num865 <= 1; num865 += 2)
{
                                Gore gore8 = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                                Gore gore2 = gore8;
                                gore2.velocity *= ((num863 == 1) ? 0.4f : 0.8f);
                                gore2 = gore8;
                                gore2.velocity += new Vector2(num864, num865);
                            }
                        }
                    }
                    if (Main.netMode != 1)
                    {
                        Point pt3 = base.Center.ToTileCoordinates();
                        Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(pt3, 3f, DelegateMethods.SpreadLava);
                    }
                }
                else if (type == 790 || type == 791 || type == 792 || type == 807 || type == 905)
                {
                    Resize(22, 22);
                    if (type == 791)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, position);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, position);
                    }
                    Color transparent5 = Color.Transparent;
                    int num866 = 152;
                    for (int num867 = 0; num867 < 30; num867++)
                    {
                        Dust dust57 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, transparent5, 1.5f);
                        Dust dust2 = dust57;
                        dust2.velocity *= 1.4f;
                    }
                    for (int num868 = 0; num868 < 80; num868++)
                    {
                        Dust dust58 = Dust.NewDustDirect(position, width, height, num866, 0f, 0f, 100, transparent5, 2.2f);
                        Dust dust2 = dust58;
                        dust2.velocity *= 7f;
                        dust58 = Dust.NewDustDirect(position, width, height, num866, 0f, 0f, 100, transparent5, 1.3f);
                        dust2 = dust58;
                        dust2.velocity *= 4f;
                    }
                    for (int num869 = 1; num869 <= 2; num869++)
                    {
                        for (int num870 = -1; num870 <= 1; num870 += 2)
{
                            for (int num871 = -1; num871 <= 1; num871 += 2)
{
                                Gore gore9 = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                                Gore gore2 = gore9;
                                gore2.velocity *= ((num869 == 1) ? 0.4f : 0.8f);
                                gore2 = gore9;
                                gore2.velocity += new Vector2(num870, num871);
                            }
                        }
                    }
                    if (Main.netMode != 1)
                    {
                        Point pt4 = base.Center.ToTileCoordinates();
                        Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(pt4, 3f, DelegateMethods.SpreadHoney);
                    }
                }
                else if (type == 799 || type == 800 || type == 801 || type == 810 || type == 906)
                {
                    Resize(22, 22);
                    if (type == 800)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, position);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, position);
                    }
                    Color transparent6 = Color.Transparent;
                    int num872 = 31;
                    for (int num873 = 0; num873 < 30; num873++)
                    {
                        Dust dust59 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, transparent6, 1.5f);
                        Dust dust2 = dust59;
                        dust2.velocity *= 1.4f;
                    }
                    for (int num874 = 0; num874 < 80; num874++)
                    {
                        Dust dust60 = Dust.NewDustDirect(position, width, height, num872, 0f, 0f, 100, transparent6, 1.2f);
                        Dust dust2 = dust60;
                        dust2.velocity *= 7f;
                        dust60 = Dust.NewDustDirect(position, width, height, num872, 0f, 0f, 100, transparent6, 0.3f);
                        dust2 = dust60;
                        dust2.velocity *= 4f;
                    }
                    for (int num875 = 1; num875 <= 2; num875++)
                    {
                        for (int num876 = -1; num876 <= 1; num876 += 2)
{
                            for (int num877 = -1; num877 <= 1; num877 += 2)
{
                                Gore gore10 = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                                Gore gore2 = gore10;
                                gore2.velocity *= ((num875 == 1) ? 0.4f : 0.8f);
                                gore2 = gore10;
                                gore2.velocity += new Vector2(num876, num877);
                            }
                        }
                    }
                    if (Main.netMode != 1)
                    {
                        Point pt5 = base.Center.ToTileCoordinates();
                        Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(pt5, 3.5f, DelegateMethods.SpreadDry);
                    }
                }
                else if (type == 793 || type == 796 || type == 794 || type == 797 || type == 795 || type == 798 || type == 808 || type == 809)
                {
                    if (type == 794 || type == 797)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, base.Center);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, base.Center);
                    }
                    Resize(50, 50);
                    float num878 = 3f;
                    for (int num879 = 0; num879 < 50; num879++)
                    {
                        Dust dust61 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, default(Color), 2f);
                        dust61.velocity = (dust61.position - base.Center).SafeNormalize(Vector2.Zero);
                        Dust dust2 = dust61;
                        dust2.velocity *= 2f + (float)Main.rand.Next(5) * 0.1f;
                        dust61.velocity.Y -= num878 * 0.5f;
                        dust61.color = Color.Black * 0.9f;
                        if (Main.rand.Next(2) == 0)
{
                            dust61.scale = 0.5f;
                            dust61.fadeIn = 1f + (float)Main.rand.Next(10) * 0.1f;
                            dust61.color = Color.Black * 0.8f;
                        }
                    }
                    for (int num880 = 0; num880 < 30; num880++)
                    {
                        Dust dust62 = Dust.NewDustDirect(position, width, height, 6, 0f, 0f, 100);
                        dust62.noGravity = true;
                        dust62.fadeIn = 1.4f;
                        dust62.velocity = (dust62.position - base.Center).SafeNormalize(Vector2.Zero);
                        Dust dust2 = dust62;
                        dust2.velocity *= 5.5f + (float)Main.rand.Next(61) * 0.1f;
                        dust62.velocity.Y -= num878 * 0.5f;
                        dust62 = Dust.NewDustDirect(position, width, height, 6, 0f, 0f, 100);
                        dust62.velocity = (dust62.position - base.Center).SafeNormalize(Vector2.Zero);
                        dust62.velocity.Y -= num878 * 0.25f;
                        dust2 = dust62;
                        dust2.velocity *= 1.5f + (float)Main.rand.Next(5) * 0.1f;
                        dust62.fadeIn = 0f;
                        dust62.scale = 0.6f;
                        dust62 = Dust.NewDustDirect(position, width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                        dust62.noGravity = num880 % 2 == 0;
                        dust62.velocity = (dust62.position - base.Center).SafeNormalize(Vector2.Zero);
                        dust2 = dust62;
                        dust2.velocity *= 3f + (float)Main.rand.Next(21) * 0.2f;
                        dust62.velocity.Y -= num878 * 0.5f;
                        dust62.fadeIn = 1.2f;
                        if (!dust62.noGravity)
{
                            dust62.scale = 0.4f;
                            dust62.fadeIn = 0f;
                        }
                        else
{
                            dust2 = dust62;
                            dust2.velocity *= 2f + (float)Main.rand.Next(5) * 0.2f;
                            dust62.velocity.Y -= num878 * 0.5f;
                        }
                    }
                    int num881 = 0;
                    for (int num882 = 1; num882 <= 3; num882++)
                    {
                        float num883 = (float)Math.PI * 2f * Main.rand.NextFloat();
                        for (float num884 = 0f; num884 < 1f; num884 += 1f / 11f)
{
                            float f4 = (float)Math.PI * 2f * num884 + num883;
                            Vector2 spinningpoint2 = f4.ToRotationVector2();
                            spinningpoint2 *= new Vector2(1f, 0.4f);
                            spinningpoint2 = spinningpoint2.RotatedBy((float)num881 - (float)Math.PI);
                            Vector2 vector71 = ((float)num881 - (float)Math.PI / 2f).ToRotationVector2();
                            Vector2 vector72 = base.Center + vector71 * 16f * 0f;
                            Dust dust63 = Dust.NewDustPerfect(vector72, 6, spinningpoint2);
                            dust63.fadeIn = 1.8f;
                            dust63.noGravity = true;
                            Dust dust2 = dust63;
                            dust2.velocity *= (float)num882 * (Main.rand.NextFloat() * 2f + 0.2f);
                            dust2 = dust63;
                            dust2.velocity += vector71 * 0.8f * num882;
                            dust2 = dust63;
                            dust2.velocity *= 2f;
                        }
                    }
                    for (int num885 = 1; num885 <= 3; num885++)
                    {
                        for (int num886 = -1; num886 <= 1; num886 += 2)
{
                            for (int num887 = -1; num887 <= 1; num887 += 2)
{
                                Gore gore11 = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                                Gore gore2 = gore11;
                                gore2.velocity *= (float)num885 / 3f;
                                gore2 = gore11;
                                gore2.velocity += new Vector2(num886, num887);
                            }
                        }
                    }
                    Resize(10, 10);
                }
                else if (type == 779 || type == 783 || type == 862 || type == 863)
                {
                    Resize(22, 22);
                    SoundEngine.PlaySound(SoundID.Item62, position);
                    Color transparent7 = Color.Transparent;
                    for (int num888 = 0; num888 < 15; num888++)
                    {
                        Dust dust64 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, transparent7, 0.8f);
                        dust64.fadeIn = 0f;
                        Dust dust2 = dust64;
                        dust2.velocity *= 0.5f;
                    }
                    for (int num889 = 0; num889 < 5; num889++)
                    {
                        Dust dust65 = Dust.NewDustDirect(position, width, height, 228, 0f, 0f, 100, transparent7, 2.5f);
                        dust65.noGravity = true;
                        Dust dust2 = dust65;
                        dust2.velocity *= 2.5f;
                        dust65 = Dust.NewDustDirect(position, width, height, 228, 0f, 0f, 100, transparent7, 1.1f);
                        dust2 = dust65;
                        dust2.velocity *= 2f;
                        dust65.noGravity = true;
                    }
                    for (int num890 = 0; num890 < 3; num890++)
                    {
                        Dust dust66 = Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 100, transparent7, 1.1f);
                        Dust dust2 = dust66;
                        dust2.velocity *= 2f;
                        dust66.noGravity = true;
                    }
                    for (int num891 = -1; num891 <= 1; num891 += 2)
                    {
                        for (int num892 = -1; num892 <= 1; num892 += 2)
{
                            if (Main.rand.Next(5) == 0)
{
                                Gore gore12 = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                                Gore gore2 = gore12;
                                gore2.velocity *= 0.2f;
                                gore2 = gore12;
                                gore2.scale *= 0.65f;
                                gore2 = gore12;
                                gore2.velocity += new Vector2(num891, num892) * 0.5f;
                            }
                        }
                    }
                }
                else if (type == 776 || type == 780 || type == 777 || type == 781 || type == 778 || type == 782 || type == 803 || type == 804)
                {
                    Resize(22, 22);
                    if (type == 777 || type == 781)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, position);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, position);
                    }
                    Color transparent8 = Color.Transparent;
                    for (int num893 = 0; num893 < 30; num893++)
                    {
                        Dust dust67 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, transparent8, 1.5f);
                        Dust dust2 = dust67;
                        dust2.velocity *= 1.4f;
                    }
                    for (int num894 = 0; num894 < 40; num894++)
                    {
                        Dust dust68 = Dust.NewDustDirect(position, width, height, 228, 0f, 0f, 100, transparent8, 3.5f);
                        dust68.noGravity = true;
                        Dust dust2 = dust68;
                        dust2.velocity *= 7f;
                        dust68 = Dust.NewDustDirect(position, width, height, 228, 0f, 0f, 100, transparent8, 1.3f);
                        dust2 = dust68;
                        dust2.velocity *= 4f;
                        dust68.noGravity = true;
                    }
                    for (int num895 = 0; num895 < 8; num895++)
                    {
                        Dust dust69 = Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 100, transparent8, 1.3f);
                        Dust dust2 = dust69;
                        dust2.velocity *= 4f;
                        dust69.noGravity = true;
                    }
                    for (int num896 = 2; num896 <= 2; num896++)
                    {
                        for (int num897 = -1; num897 <= 1; num897 += 2)
{
                            for (int num898 = -1; num898 <= 1; num898 += 2)
{
                                Gore gore13 = Gore.NewGoreDirect(position, Vector2.Zero, Main.rand.Next(61, 64));
                                Gore gore2 = gore13;
                                gore2.velocity *= ((num896 == 1) ? 0.4f : 0.8f);
                                gore2 = gore13;
                                gore2.velocity += new Vector2(num897, num898);
                            }
                        }
                    }
                    if (owner == Main.myPlayer)
                    {
                        int num899 = 779;
                        if (type == 780 || type == 781 || type == 782)
{
                            num899 = 783;
                        }
                        if (type == 803)
{
                            num899 = 862;
                        }
                        if (type == 804)
{
                            num899 = 863;
                        }
                        float num900 = Main.rand.NextFloat() * ((float)Math.PI * 2f);
                        for (float num901 = 0f; num901 < 1f; num901 += 1f / 6f)
{
                            float f5 = num900 + num901 * ((float)Math.PI * 2f);
                            Vector2 vector73 = f5.ToRotationVector2() * (4f + Main.rand.NextFloat() * 2f);
                            vector73 += Vector2.UnitY * -1f;
                            int num902 = NewProjectile(GetProjectileSource_FromThis(), base.Center, vector73, num899, damage / 2, 0f, owner);
                            Projectile projectile = Main.projectile[num902];
                            Projectile projectile2 = projectile;
                            projectile2.timeLeft -= Main.rand.Next(30);
                        }
                    }
                }
                else if (type == 133 || type == 134 || type == 135 || type == 136 || type == 137 || type == 138 || type == 303 || type == 338 || type == 339 || type == 930)
                {
                    if (type == 30 || type == 133 || type == 136)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, position);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, position);
                    }
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 22;
                    height = 22;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                    for (int num903 = 0; num903 < 30; num903++)
                    {
                        int num904 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                        Dust dust2 = Main.dust[num904];
                        dust2.velocity *= 1.4f;
                    }
                    for (int num905 = 0; num905 < 20; num905++)
                    {
                        int num906 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 3.5f);
                        Main.dust[num906].noGravity = true;
                        Dust dust2 = Main.dust[num906];
                        dust2.velocity *= 7f;
                        num906 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = Main.dust[num906];
                        dust2.velocity *= 3f;
                    }
                    for (int num907 = 0; num907 < 2; num907++)
                    {
                        float num908 = 0.4f;
                        if (num907 == 1)
{
                            num908 = 0.8f;
                        }
                        int num909 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                        Gore gore2 = Main.gore[num909];
                        gore2.velocity *= num908;
                        Main.gore[num909].velocity.X += 1f;
                        Main.gore[num909].velocity.Y += 1f;
                        num909 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num909];
                        gore2.velocity *= num908;
                        Main.gore[num909].velocity.X -= 1f;
                        Main.gore[num909].velocity.Y += 1f;
                        num909 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num909];
                        gore2.velocity *= num908;
                        Main.gore[num909].velocity.X += 1f;
                        Main.gore[num909].velocity.Y -= 1f;
                        num909 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num909];
                        gore2.velocity *= num908;
                        Main.gore[num909].velocity.X -= 1f;
                        Main.gore[num909].velocity.Y -= 1f;
                    }
                }
                else if (type == 139 || type == 140 || type == 141 || type == 142 || type == 143 || type == 144 || type == 340 || type == 341)
                {
                    if (type == 139)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, position);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, position);
                    }
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 80;
                    height = 80;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                    for (int num910 = 0; num910 < 40; num910++)
                    {
                        int num911 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 2f);
                        Dust dust2 = Main.dust[num911];
                        dust2.velocity *= 3f;
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num911].scale = 0.5f;
                            Main.dust[num911].fadeIn = 1f + (float)Main.rand.Next(10) * 0.1f;
                        }
                    }
                    for (int num912 = 0; num912 < 70; num912++)
                    {
                        int num913 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 3f);
                        Main.dust[num913].noGravity = true;
                        Dust dust2 = Main.dust[num913];
                        dust2.velocity *= 5f;
                        num913 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                        dust2 = Main.dust[num913];
                        dust2.velocity *= 2f;
                    }
                    for (int num914 = 0; num914 < 3; num914++)
                    {
                        float num915 = 0.33f;
                        if (num914 == 1)
{
                            num915 = 0.66f;
                        }
                        if (num914 == 2)
{
                            num915 = 1f;
                        }
                        int num916 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
                        Gore gore2 = Main.gore[num916];
                        gore2.velocity *= num915;
                        Main.gore[num916].velocity.X += 1f;
                        Main.gore[num916].velocity.Y += 1f;
                        num916 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num916];
                        gore2.velocity *= num915;
                        Main.gore[num916].velocity.X -= 1f;
                        Main.gore[num916].velocity.Y += 1f;
                        num916 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num916];
                        gore2.velocity *= num915;
                        Main.gore[num916].velocity.X += 1f;
                        Main.gore[num916].velocity.Y -= 1f;
                        num916 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
                        gore2 = Main.gore[num916];
                        gore2.velocity *= num915;
                        Main.gore[num916].velocity.X -= 1f;
                        Main.gore[num916].velocity.Y -= 1f;
                    }
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 10;
                    height = 10;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                }
                else if (type == 246)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    for (int num917 = 0; num917 < 10; num917++)
                    {
                        int num918 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                        Dust dust2 = Main.dust[num918];
                        dust2.velocity *= 0.9f;
                    }
                    for (int num919 = 0; num919 < 5; num919++)
                    {
                        int num920 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                        Main.dust[num920].noGravity = true;
                        Dust dust2 = Main.dust[num920];
                        dust2.velocity *= 3f;
                        num920 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = Main.dust[num920];
                        dust2.velocity *= 2f;
                    }
                    int num921 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    Gore gore2 = Main.gore[num921];
                    gore2.velocity *= 0.3f;
                    Main.gore[num921].velocity.X += Main.rand.Next(-1, 2);
                    Main.gore[num921].velocity.Y += Main.rand.Next(-1, 2);
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 150;
                    height = 150;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                    penetrate = -1;
                    maxPenetrate = 0;
                    Damage();
                    if (owner == Main.myPlayer)
                    {
                        int num922 = Main.rand.Next(2, 6);
                        for (int num923 = 0; num923 < num922; num923++)
{
                            float num924 = Main.rand.Next(-100, 101);
                            num924 += 0.01f;
                            float num925 = Main.rand.Next(-100, 101);
                            num924 -= 0.01f;
                            float num926 = (float)Math.Sqrt(num924 * num924 + num925 * num925);
                            num926 = 8f / num926;
                            num924 *= num926;
                            num925 *= num926;
                            int num927 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X - oldVelocity.X, base.Center.Y - oldVelocity.Y, num924, num925, 249, damage, knockBack, owner);
                            Main.projectile[num927].maxPenetrate = 0;
                        }
                    }
                }
                else if (type == 249)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    for (int num928 = 0; num928 < 7; num928++)
                    {
                        int num929 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                        Dust dust2 = Main.dust[num929];
                        dust2.velocity *= 0.8f;
                    }
                    for (int num930 = 0; num930 < 2; num930++)
                    {
                        int num931 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2.5f);
                        Main.dust[num931].noGravity = true;
                        Dust dust2 = Main.dust[num931];
                        dust2.velocity *= 2.5f;
                        num931 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = Main.dust[num931];
                        dust2.velocity *= 1.5f;
                    }
                    int num932 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(61, 64));
                    Gore gore2 = Main.gore[num932];
                    gore2.velocity *= 0.2f;
                    Main.gore[num932].velocity.X += Main.rand.Next(-1, 2);
                    Main.gore[num932].velocity.Y += Main.rand.Next(-1, 2);
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 100;
                    height = 100;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                    penetrate = -1;
                    Damage();
                }
                else if (type == 588)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    position = base.Center;
                    width = (height = 22);
                    base.Center = position;
                    for (int num933 = 0; num933 < 8; num933++)
                    {
                        int num934 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 219 + Main.rand.Next(5));
                        Dust dust2 = Main.dust[num934];
                        dust2.velocity *= 1.4f;
                        Main.dust[num934].fadeIn = 1f;
                        Main.dust[num934].noGravity = true;
                    }
                    for (int num935 = 0; num935 < 15; num935++)
                    {
                        int num936 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 139 + Main.rand.Next(4), 0f, 0f, 0, default(Color), 1.6f);
                        Main.dust[num936].noGravity = true;
                        Dust dust2 = Main.dust[num936];
                        dust2.velocity *= 5f;
                        num936 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 139 + Main.rand.Next(4), 0f, 0f, 0, default(Color), 1.9f);
                        dust2 = Main.dust[num936];
                        dust2.velocity *= 3f;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        int num937 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(276, 283));
                        Gore gore2 = Main.gore[num937];
                        gore2.velocity *= 0.4f;
                        Main.gore[num937].velocity.X += 1f;
                        Main.gore[num937].velocity.Y += 1f;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        int num937 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(276, 283));
                        Gore gore2 = Main.gore[num937];
                        gore2.velocity *= 0.4f;
                        Main.gore[num937].velocity.X -= 1f;
                        Main.gore[num937].velocity.Y += 1f;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        int num937 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(276, 283));
                        Gore gore2 = Main.gore[num937];
                        gore2.velocity *= 0.4f;
                        Main.gore[num937].velocity.X += 1f;
                        Main.gore[num937].velocity.Y -= 1f;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        int num937 = Gore.NewGore(new Vector2(position.X, position.Y), default(Vector2), Main.rand.Next(276, 283));
                        Gore gore2 = Main.gore[num937];
                        gore2.velocity *= 0.4f;
                        Main.gore[num937].velocity.X -= 1f;
                        Main.gore[num937].velocity.Y -= 1f;
                    }
                }
                else if (type == 773)
                {
                    Player player2 = Main.player[owner];
                    Vector2 v = DirectionTo(player2.Center);
                    float num938 = v.ToRotation() + (float)Math.PI / 2f;
                    num938 += (float)Math.PI;
                    Point scarabBombDigDirectionSnap = GetScarabBombDigDirectionSnap8();
                    num938 = scarabBombDigDirectionSnap.ToVector2().ToRotation() + (float)Math.PI / 2f;
                    if (type == 794 || type == 797)
                    {
                        SoundEngine.PlaySound(SoundID.Item62, base.Center);
                    }
                    else
                    {
                        SoundEngine.PlaySound(SoundID.Item14, base.Center);
                    }
                    Resize(80, 80);
                    for (int num939 = 0; num939 < 60; num939++)
                    {
                        Dust dust70 = Dust.NewDustDirect(position, width, height, 31, 0f, 0f, 100, default(Color), 2f);
                        dust70.velocity.Y -= 0.5f;
                        Dust dust2 = dust70;
                        dust2.velocity *= 1.2f;
                        dust70.color = Color.Black * 0.9f;
                        if (Main.rand.Next(2) == 0)
{
                            dust70.scale = 0.5f;
                            dust70.fadeIn = 1f + (float)Main.rand.Next(10) * 0.1f;
                            dust70.color = Color.Black * 0.8f;
                        }
                    }
                    for (int num940 = 0; num940 < 30; num940++)
                    {
                        Dust dust71 = Dust.NewDustDirect(position, width, height, 59, 0f, 0f, 100);
                        dust71.noGravity = true;
                        if (Math.Abs(velocity.X) > 0.25f)
{
                            velocity.X *= 0.25f / Math.Abs(velocity.X);
                        }
                        dust71.velocity.Y -= 0.5f;
                        dust71.fadeIn = 1.2f;
                        Dust dust2 = dust71;
                        dust2.velocity *= 8f;
                        dust71.velocity = dust71.velocity.RotatedBy(num938);
                        dust71 = Dust.NewDustDirect(position, width, height, 59, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = dust71;
                        dust2.velocity *= 2f;
                        dust71.velocity = dust71.velocity.RotatedBy(num938);
                        dust71.velocity.Y -= 1.5f;
                        dust71 = Dust.NewDustDirect(position, width, height, 59, 0f, 0f, 100, default(Color), 1.5f);
                        dust71.noGravity = true;
                        dust71.velocity.Y -= 1f;
                        dust71.fadeIn = 2f;
                        dust2 = dust71;
                        dust2.velocity *= 4f;
                        dust71.velocity = dust71.velocity.RotatedBy(num938);
                    }
                    bool flag4 = Math.Abs(scarabBombDigDirectionSnap.X) + Math.Abs(scarabBombDigDirectionSnap.Y) == 1;
                    for (int num941 = 1; num941 <= 3; num941++)
                    {
                        float num942 = (float)Math.PI * 2f * Main.rand.NextFloat();
                        for (float num943 = 0f; num943 < 1f; num943 += 1f / 12f)
{
                            float f6 = (float)Math.PI * 2f * num943 + num942;
                            Vector2 value13 = f6.ToRotationVector2();
                            value13 *= new Vector2(0.7f, 0.3f);
                            Dust dust72 = Dust.NewDustPerfect(base.Center, 59, value13);
                            dust72.fadeIn = 2f;
                            dust72.noGravity = true;
                            Dust dust2 = dust72;
                            dust2.velocity *= (float)num941 + Main.rand.NextFloat() * 0.6f;
                            dust72.velocity.Y -= (float)num941 * 0.8f;
                            dust72.velocity = dust72.velocity.RotatedBy(num938);
                            if (flag4)
{
                                dust2 = dust72;
                                dust2.velocity += scarabBombDigDirectionSnap.ToVector2() * (Main.rand.NextFloat() * 11f + 6f);
                            }
                            else
{
                                dust2 = dust72;
                                dust2.velocity += scarabBombDigDirectionSnap.ToVector2() * (Main.rand.NextFloat() * 7f + 5f);
                            }
                        }
                    }
                    Vector2 vector74 = (num938 - (float)Math.PI / 2f).ToRotationVector2();
                    for (int num944 = 1; num944 <= 1; num944++)
                    {
                        for (int num945 = -1; num945 <= 1; num945 += 2)
{
                            for (int num946 = -1; num946 <= 1; num946 += 2)
{
                                Gore gore14 = Gore.NewGoreDirect(base.Center - Vector2.One * 20f, Vector2.Zero, Main.rand.Next(61, 64));
                                gore14.velocity = gore14.velocity * 0.5f + vector74 * 3f;
                                Gore gore2 = gore14;
                                gore2.velocity += new Vector2(num945, num946) * 0.2f;
                            }
                        }
                    }
                    Resize(10, 10);
                    if (owner == Main.myPlayer)
                    {
                        Point p = base.Center.ToTileCoordinates();
                        Vector2 vector75 = p.ToWorldCoordinates();
                        bool wallSplode = false;
                        int num947 = 15;
                        if (scarabBombDigDirectionSnap.X == 0 || scarabBombDigDirectionSnap.Y == 0)
{
                            num947 = (int)((double)num947 * Math.Sqrt(2.0));
                        }
                        for (int num948 = 0; num948 < num947; num948++)
{
                            Vector2 vec = vector75 + scarabBombDigDirectionSnap.ToVector2() * 16f * num948 * 1f;
                            Point p2 = vec.ToTileCoordinates();
                            if (ShouldWallExplode(p2.ToWorldCoordinates(), 9999, p2.X - 1, p2.X + 1, p2.Y - 1, p2.Y + 1))
{
                                wallSplode = true;
                                break;
                            }
                        }
                        for (int num949 = 0; num949 < num947; num949++)
{
                            Vector2 vec2 = vector75 + scarabBombDigDirectionSnap.ToVector2() * 16f * num949 * 1f;
                            Point p3 = vec2.ToTileCoordinates();
                            ExplodeTiles(p3.ToWorldCoordinates(), 9999, p3.X - 1, p3.X + 1, p3.Y - 1, p3.Y + 1, wallSplode);
                        }
                    }
                }
                else if (type == 28 || type == 30 || type == 37 || type == 75 || type == 102 || type == 164 || type == 397 || type == 517 || type == 516 || type == 519 || type == 773)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 22;
                    height = 22;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                    int num950 = 6;
                    if (type == 773)
                    {
                        num950 = 59;
                    }
                    for (int num951 = 0; num951 < 20; num951++)
                    {
                        int num952 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                        Dust dust2 = Main.dust[num952];
                        dust2.velocity *= 1.4f;
                    }
                    for (int num953 = 0; num953 < 10; num953++)
                    {
                        int num954 = Dust.NewDust(position, width, height, num950, 0f, 0f, 100, default(Color), 2.5f);
                        Main.dust[num954].noGravity = true;
                        Dust dust2 = Main.dust[num954];
                        dust2.velocity *= 5f;
                        num954 = Dust.NewDust(position, width, height, num950, 0f, 0f, 100, default(Color), 1.5f);
                        dust2 = Main.dust[num954];
                        dust2.velocity *= 3f;
                    }
                    int num955 = Gore.NewGore(position, default(Vector2), Main.rand.Next(61, 64));
                    Gore gore2 = Main.gore[num955];
                    gore2.velocity *= 0.4f;
                    Main.gore[num955].velocity.X += 1f;
                    Main.gore[num955].velocity.Y += 1f;
                    num955 = Gore.NewGore(position, default(Vector2), Main.rand.Next(61, 64));
                    gore2 = Main.gore[num955];
                    gore2.velocity *= 0.4f;
                    Main.gore[num955].velocity.X -= 1f;
                    Main.gore[num955].velocity.Y += 1f;
                    num955 = Gore.NewGore(position, default(Vector2), Main.rand.Next(61, 64));
                    gore2 = Main.gore[num955];
                    gore2.velocity *= 0.4f;
                    Main.gore[num955].velocity.X += 1f;
                    Main.gore[num955].velocity.Y -= 1f;
                    num955 = Gore.NewGore(position, default(Vector2), Main.rand.Next(61, 64));
                    gore2 = Main.gore[num955];
                    gore2.velocity *= 0.4f;
                    Main.gore[num955].velocity.X -= 1f;
                    Main.gore[num955].velocity.Y -= 1f;
                    if (type == 102)
                    {
                        Vector2 vector76 = position;
                        position.X += width / 2;
                        position.Y += height / 2;
                        width = 128;
                        height = 128;
                        position.X -= width / 2;
                        position.Y -= height / 2;
                        damage = 40;
                        Damage();
                        position = vector76;
                        width = 22;
                        height = 22;
                    }
                    if (type == 75)
                    {
                        Resize(128, 128);
                        damage = 60;
                        knockBack = 8f;
                        Damage();
                        Resize(22, 22);
                    }
                }
                else if (type == 29 || type == 108 || type == 470 || type == 637 || type == 1002)
                {
                    SoundEngine.PlaySound(SoundID.Item14, position);
                    if (type == 29)
                    {
                        position.X += width / 2;
                        position.Y += height / 2;
                        width = 200;
                        height = 200;
                        position.X -= width / 2;
                        position.Y -= height / 2;
                    }
                    for (int num956 = 0; num956 < 50; num956++)
                    {
                        int num957 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 2f);
                        Dust dust2 = Main.dust[num957];
                        dust2.velocity *= 1.4f;
                    }
                    for (int num958 = 0; num958 < 80; num958++)
                    {
                        int num959 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 3f);
                        Main.dust[num959].noGravity = true;
                        Dust dust2 = Main.dust[num959];
                        dust2.velocity *= 5f;
                        num959 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                        dust2 = Main.dust[num959];
                        dust2.velocity *= 3f;
                    }
                    for (int num960 = 0; num960 < 2; num960++)
                    {
                        int num961 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
                        Main.gore[num961].scale = 1.5f;
                        Main.gore[num961].velocity.X += 1.5f;
                        Main.gore[num961].velocity.Y += 1.5f;
                        num961 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
                        Main.gore[num961].scale = 1.5f;
                        Main.gore[num961].velocity.X -= 1.5f;
                        Main.gore[num961].velocity.Y += 1.5f;
                        num961 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
                        Main.gore[num961].scale = 1.5f;
                        Main.gore[num961].velocity.X += 1.5f;
                        Main.gore[num961].velocity.Y -= 1.5f;
                        num961 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
                        Main.gore[num961].scale = 1.5f;
                        Main.gore[num961].velocity.X -= 1.5f;
                        Main.gore[num961].velocity.Y -= 1.5f;
                    }
                    position.X += width / 2;
                    position.Y += height / 2;
                    width = 10;
                    height = 10;
                    position.X -= width / 2;
                    position.Y -= height / 2;
                }
                else if (type == 69)
                {
                    SoundEngine.PlaySound(13, (int)position.X, (int)position.Y);
                    for (int num962 = 0; num962 < 5; num962++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 13);
                    }
                    for (int num963 = 0; num963 < 30; num963++)
                    {
                        int num964 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 33, 0f, -2f, 0, default(Color), 1.1f);
                        Main.dust[num964].alpha = 100;
                        Main.dust[num964].velocity.X *= 1.5f;
                        Dust dust2 = Main.dust[num964];
                        dust2.velocity *= 3f;
                    }
                }
                else if (type == 70)
                {
                    SoundEngine.PlaySound(13, (int)position.X, (int)position.Y);
                    for (int num965 = 0; num965 < 5; num965++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 13);
                    }
                    for (int num966 = 0; num966 < 30; num966++)
                    {
                        int num967 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 52, 0f, -2f, 0, default(Color), 1.1f);
                        Main.dust[num967].alpha = 100;
                        Main.dust[num967].velocity.X *= 1.5f;
                        Dust dust2 = Main.dust[num967];
                        dust2.velocity *= 3f;
                    }
                }
                else if (type == 621)
                {
                    SoundEngine.PlaySound(13, (int)position.X, (int)position.Y);
                    for (int num968 = 0; num968 < 5; num968++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 13);
                    }
                    for (int num969 = 0; num969 < 30; num969++)
                    {
                        int num970 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 266, 0f, -2f, 0, default(Color), 1.1f);
                        Main.dust[num970].alpha = 100;
                        Main.dust[num970].velocity.X *= 1.5f;
                        Dust dust2 = Main.dust[num970];
                        dust2.velocity *= 3f;
                    }
                }
                else if (type == 114 || type == 115)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num971 = 4; num971 < 31; num971++)
                    {
                        float num972 = oldVelocity.X * (30f / (float)num971);
                        float num973 = oldVelocity.Y * (30f / (float)num971);
                        int num974 = Dust.NewDust(new Vector2(position.X - num972, position.Y - num973), 8, 8, 27, oldVelocity.X, oldVelocity.Y, 100, default(Color), 1.4f);
                        Main.dust[num974].noGravity = true;
                        Dust dust2 = Main.dust[num974];
                        dust2.velocity *= 0.5f;
                        num974 = Dust.NewDust(new Vector2(position.X - num972, position.Y - num973), 8, 8, 27, oldVelocity.X, oldVelocity.Y, 100, default(Color), 0.9f);
                        dust2 = Main.dust[num974];
                        dust2.velocity *= 0.5f;
                    }
                }
                else if (type == 116)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num975 = 4; num975 < 31; num975++)
                    {
                        float num976 = oldVelocity.X * (30f / (float)num975);
                        float num977 = oldVelocity.Y * (30f / (float)num975);
                        int num978 = Dust.NewDust(new Vector2(position.X - num976, position.Y - num977), 8, 8, 64, oldVelocity.X, oldVelocity.Y, 100, default(Color), 1.8f);
                        Main.dust[num978].noGravity = true;
                        num978 = Dust.NewDust(new Vector2(position.X - num976, position.Y - num977), 8, 8, 64, oldVelocity.X, oldVelocity.Y, 100, default(Color), 1.4f);
                        Main.dust[num978].noGravity = true;
                    }
                }
                else if (type == 173)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num979 = 4; num979 < 24; num979++)
                    {
                        float num980 = oldVelocity.X * (30f / (float)num979);
                        float num981 = oldVelocity.Y * (30f / (float)num979);
                        int num982 = Main.rand.Next(3);
                        int num983 = Dust.NewDust(new Vector2(position.X - num980, position.Y - num981), 8, 8, num982 switch
{
                            0 => 15,
                            1 => 57,
                            _ => 58,
                        }, oldVelocity.X * 0.2f, oldVelocity.Y * 0.2f, 100, default(Color), 1.8f);
                        Dust dust2 = Main.dust[num983];
                        dust2.velocity *= 1.5f;
                        Main.dust[num983].noGravity = true;
                    }
                }
                else if (type == 132)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num984 = 4; num984 < 31; num984++)
                    {
                        float num985 = oldVelocity.X * (30f / (float)num984);
                        float num986 = oldVelocity.Y * (30f / (float)num984);
                        int num987 = Dust.NewDust(new Vector2(oldPosition.X - num985, oldPosition.Y - num986), 8, 8, 107, oldVelocity.X, oldVelocity.Y, 100, default(Color), 1.8f);
                        Main.dust[num987].noGravity = true;
                        Dust dust2 = Main.dust[num987];
                        dust2.velocity *= 0.5f;
                        num987 = Dust.NewDust(new Vector2(oldPosition.X - num985, oldPosition.Y - num986), 8, 8, 107, oldVelocity.X, oldVelocity.Y, 100, default(Color), 1.4f);
                        dust2 = Main.dust[num987];
                        dust2.velocity *= 0.05f;
                    }
                }
                else if (type == 156)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num988 = 4; num988 < 31; num988++)
                    {
                        float num989 = oldVelocity.X * (30f / (float)num988);
                        float num990 = oldVelocity.Y * (30f / (float)num988);
                        int num991 = Dust.NewDust(new Vector2(oldPosition.X - num989, oldPosition.Y - num990), 8, 8, 73, oldVelocity.X, oldVelocity.Y, 255, default(Color), 1.8f);
                        Main.dust[num991].noGravity = true;
                        Dust dust2 = Main.dust[num991];
                        dust2.velocity *= 0.5f;
                        num991 = Dust.NewDust(new Vector2(oldPosition.X - num989, oldPosition.Y - num990), 8, 8, 73, oldVelocity.X, oldVelocity.Y, 255, default(Color), 1.4f);
                        dust2 = Main.dust[num991];
                        dust2.velocity *= 0.05f;
                        Main.dust[num991].noGravity = true;
                    }
                }
                else if (type == 157)
                {
                    SoundEngine.PlaySound(SoundID.Item10, position);
                    for (int num992 = 4; num992 < 31; num992++)
                    {
                        int num993 = Dust.NewDust(position, width, height, 107, oldVelocity.X, oldVelocity.Y, 100, default(Color), 1.8f);
                        Main.dust[num993].noGravity = true;
                        Dust dust2 = Main.dust[num993];
                        dust2.velocity *= 0.5f;
                    }
                }
                else if (type == 370)
                {
                    SoundEngine.PlaySound(SoundID.Item4, position);
                    for (int num994 = 0; num994 < 5; num994++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 13);
                    }
                    for (int num995 = 0; num995 < 30; num995++)
                    {
                        Vector2 vector77 = new Vector2(Main.rand.Next(-10, 11), Main.rand.Next(-10, 11));
                        vector77.Normalize();
                        int num996 = Gore.NewGore(base.Center + vector77 * 10f, vector77 * Main.rand.Next(4, 9) * 0.66f + Vector2.UnitY * 1.5f, 331, (float)Main.rand.Next(40, 141) * 0.01f);
                        Main.gore[num996].sticky = false;
                    }
                }
                else if (type == 371)
                {
                    SoundEngine.PlaySound(13, (int)position.X, (int)position.Y);
                    SoundEngine.PlaySound(SoundID.Item16, position);
                    for (int num997 = 0; num997 < 5; num997++)
                    {
                        Dust.NewDust(new Vector2(position.X, position.Y), width, height, 13);
                    }
                    for (int num998 = 0; num998 < 30; num998++)
                    {
                        Vector2 vector78 = new Vector2(Main.rand.Next(-10, 11), Main.rand.Next(-10, 11));
                        vector78.Normalize();
                        vector78 *= 0.4f;
                        int num999 = Gore.NewGore(base.Center + vector78 * 10f, vector78 * Main.rand.Next(4, 9) * 0.66f + Vector2.UnitY * 1.5f, Main.rand.Next(435, 438), (float)Main.rand.Next(20, 100) * 0.01f);
                        Main.gore[num999].sticky = false;
                    }
                }
                else if (type == 936)
                {
                    SoundEngine.PlaySound(SoundID.Item21, position);
                    for (int num1000 = 0; num1000 < 20; num1000++)
                    {
                        Color newColor9 = Main.hslToRgb(0.7f + 0.2f * Main.rand.NextFloat(), 1f, 0.7f);
                        newColor9.A /= 2;
                        int num1001 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 4, 0f, 0f, 150, newColor9);
                        Dust dust2 = Main.dust[num1001];
                        dust2.velocity *= 1.5f;
                        newColor9 = Main.hslToRgb(0.7f + 0.2f * Main.rand.NextFloat(), 1f, 0.5f);
                        newColor9.A /= 2;
                        num1001 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 4, 0f, 0f, 150, newColor9, 1.8f);
                        dust2 = Main.dust[num1001];
                        dust2.velocity *= 3f;
                        Main.dust[num1001].noGravity = true;
                    }
                }
            }
        }
        if (owner == Main.myPlayer && (type == 370 || type == 371 || type == 936))
        {
            float num1002 = 80f;
            int num1003 = 119;
            if (type == 371)
            {
                num1003 = 120;
            }
            if (type == 936)
            {
                num1003 = 320;
            }
            for (int num1004 = 0; num1004 < 255; num1004++)
            {
                Player player3 = Main.player[num1004];
                if (player3.active && !player3.dead && Vector2.Distance(base.Center, player3.Center) < num1002)
                {
                    player3.AddBuff(num1003, 1800, quiet: false);
                }
            }
            for (int num1005 = 0; num1005 < 200; num1005++)
            {
                NPC nPC = Main.npc[num1005];
                if (nPC.active && nPC.life > 0 && Vector2.Distance(base.Center, nPC.Center) < num1002)
                {
                    nPC.AddBuff(num1003, 1800);
                }
            }
        }
        if (owner == Main.myPlayer)
        {
            if (type == 30 || type == 517 || type == 397 || type == 588)
            {
                int num1006 = 4;
                Vector2 center2 = base.Center;
                int num1007 = (int)(center2.X / 16f - (float)num1006);
                int num1008 = (int)(center2.X / 16f + (float)num1006);
                int num1009 = (int)(center2.Y / 16f - (float)num1006);
                int num1010 = (int)(center2.Y / 16f + (float)num1006);
                if (num1007 < 0)
                {
                    num1007 = 0;
                }
                if (num1008 > Main.maxTilesX)
                {
                    num1008 = Main.maxTilesX;
                }
                if (num1009 < 0)
                {
                    num1009 = 0;
                }
                if (num1010 > Main.maxTilesY)
                {
                    num1010 = Main.maxTilesY;
                }
                ExplodeCrackedTiles(center2, num1006, num1007, num1008, num1009, num1010);
            }
            if (type == 28 || type == 29 || type == 37 || type == 108 || type == 136 || type == 137 || type == 138 || type == 142 || type == 143 || type == 144 || type == 339 || type == 341 || type == 470 || type == 516 || type == 519 || type == 637 || type == 716 || type == 718 || type == 780 || type == 781 || type == 782 || type == 804 || type == 783 || type == 863 || type == 796 || type == 797 || type == 798 || type == 809 || (type == 102 && Main.getGoodWorld && !Main.remixWorld))
            {
                int num1011 = 3;
                if (type == 102)
                {
                    num1011 = 4;
                }
                if (type == 28 || type == 37 || type == 516 || type == 519)
                {
                    num1011 = 4;
                }
                if (type == 29 || type == 470 || type == 637 || type == 796 || type == 797 || type == 798 || type == 809)
                {
                    num1011 = 7;
                }
                if (type == 142 || type == 143 || type == 144 || type == 341)
                {
                    num1011 = 5;
                }
                if (type == 716 || type == 780 || type == 781 || type == 782 || type == 804 || type == 783 || type == 863)
                {
                    num1011 = 3;
                }
                if (type == 718)
                {
                    num1011 = 5;
                }
                if (type == 108)
                {
                    num1011 = 10;
                }
                if (type == 1002)
                {
                    num1011 = 10;
                }
                Vector2 center3 = position;
                if (type == 716 || type == 718 || type == 773)
                {
                    center3 = base.Center;
                }
                int num1012 = num1011;
                int num1013 = num1011;
                int num1014 = (int)(center3.X / 16f - (float)num1012);
                int num1015 = (int)(center3.X / 16f + (float)num1012);
                int num1016 = (int)(center3.Y / 16f - (float)num1013);
                int num1017 = (int)(center3.Y / 16f + (float)num1013);
                if (num1014 < 0)
                {
                    num1014 = 0;
                }
                if (num1015 > Main.maxTilesX)
                {
                    num1015 = Main.maxTilesX;
                }
                if (num1016 < 0)
                {
                    num1016 = 0;
                }
                if (num1017 > Main.maxTilesY)
                {
                    num1017 = Main.maxTilesY;
                }
                bool wallSplode2 = ShouldWallExplode(center3, num1011, num1014, num1015, num1016, num1017);
                ExplodeTiles(center3, num1011, num1014, num1015, num1016, num1017, wallSplode2);
            }
            if (Main.netMode != 0)
            {
                NetMessage.SendData(29, -1, -1, null, identity, owner);
            }
            if (!noDropItem)
            {
                int num1018 = -1;
                if (type >= 736 && type <= 738)
                {
                    SoundEngine.PlaySound(SoundID.Item127, position);
                    for (int num1019 = 0; num1019 < 3; num1019++)
                    {
                        Dust.NewDust(position, 16, 16, type - 736 + 275);
                    }
                    int num1020 = (int)(base.Center.X / 16f);
                    int num1021 = (int)(base.Center.Y / 16f) + 1;
                    if (Main.myPlayer == owner && Main.tile[num1020, num1021].active() && TileID.Sets.CrackedBricks[Main.tile[num1020, num1021].type] && Main.rand.Next(2) == 0)
                    {
                        WorldGen.KillTile(num1020, num1021);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 20, num1020, num1021);
                        }
                    }
                }
                else if (aiStyle == 10)
                {
                    int num1022 = (int)(position.X + (float)(width / 2)) / 16;
                    int num1023 = (int)(position.Y + (float)(height / 2)) / 16;
                    int num1024 = 0;
                    int num1025 = 2;
                    if (type == 109)
                    {
                        num1024 = 147;
                        num1025 = 0;
                    }
                    if (type == 31)
                    {
                        num1024 = 53;
                        num1025 = 169;
                        if (ai[0] == 2f)
{
                            num1025 = 0;
                        }
                    }
                    if (type == 42)
                    {
                        num1024 = 53;
                        num1025 = 0;
                    }
                    if (type == 56)
                    {
                        num1024 = 112;
                        num1025 = 370;
                    }
                    if (type == 65)
                    {
                        num1024 = 112;
                        num1025 = 0;
                    }
                    if (type == 67)
                    {
                        num1024 = 116;
                        num1025 = 408;
                    }
                    if (type == 68)
                    {
                        num1024 = 116;
                        num1025 = 0;
                    }
                    if (type == 71)
                    {
                        num1024 = 123;
                        num1025 = 424;
                    }
                    if (type == 39)
                    {
                        num1024 = 59;
                        num1025 = 0;
                    }
                    if (type == 40)
                    {
                        num1024 = 57;
                        num1025 = 0;
                    }
                    if (type == 179)
                    {
                        num1024 = 224;
                        num1025 = 1103;
                    }
                    if (type == 241)
                    {
                        num1024 = 234;
                        num1025 = 1246;
                    }
                    if (type == 354)
                    {
                        num1024 = 234;
                        num1025 = 0;
                    }
                    if (type == 411)
                    {
                        num1024 = 330;
                        num1025 = 71;
                    }
                    if (type == 412)
                    {
                        num1024 = 331;
                        num1025 = 72;
                    }
                    if (type == 413)
                    {
                        num1024 = 332;
                        num1025 = 73;
                    }
                    if (type == 414)
                    {
                        num1024 = 333;
                        num1025 = 74;
                    }
                    if (type == 812)
                    {
                        num1024 = 495;
                        num1025 = 4090;
                    }
                    if (type == 109)
                    {
                        int num1026 = Player.FindClosest(position, width, height);
                        if ((double)(base.Center - Main.player[num1026].Center).Length() > (double)Main.LogicCheckScreenWidth * 0.75)
{
                            num1024 = -1;
                            num1025 = 593;
                        }
                    }
                    if (Main.tile[num1022, num1023].nactive() && Main.tile[num1022, num1023].halfBrick() && velocity.Y > 0f && Math.Abs(velocity.Y) > Math.Abs(velocity.X))
                    {
                        num1023--;
                    }
                    if (!Main.tile[num1022, num1023].active() && num1024 >= 0)
                    {
                        bool flag5 = false;
                        bool flag6 = false;
                        if (num1023 < Main.maxTilesY - 2)
{
                            Tile tile2 = Main.tile[num1022, num1023 + 1];
                            if (tile2 != null && tile2.active())
{
                                if (tile2.active() && tile2.type == 314)
{
                                    flag6 = true;
                                }
                                if (tile2.active() && WorldGen.BlockBelowMakesSandFall(num1022, num1023))
{
                                    flag6 = true;
                                }
                            }
                        }
                        if (!flag6)
{
                            flag5 = WorldGen.PlaceTile(num1022, num1023, num1024, mute: false, forced: true);
                        }
                        if (!flag6 && Main.tile[num1022, num1023].active() && Main.tile[num1022, num1023].type == num1024)
{
                            if (Main.tile[num1022, num1023 + 1].halfBrick() || Main.tile[num1022, num1023 + 1].slope() != 0)
{
                                WorldGen.SlopeTile(num1022, num1023 + 1);
                                if (Main.netMode != 0)
{
                                    NetMessage.SendData(17, -1, -1, null, 14, num1022, num1023 + 1);
                                }
                            }
                            if (Main.netMode != 0)
{
                                NetMessage.SendData(17, -1, -1, null, 1, num1022, num1023, num1024);
                            }
                        }
                        else if (!flag5 && num1025 > 0)
{
                            num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, num1025);
                        }
                    }
                    else if (num1025 > 0)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, num1025);
                    }
                }
                if (type == 171)
                {
                    if (ai[1] == 0f)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 985);
                        Main.item[num1018].noGrabDelay = 0;
                    }
                    else if (ai[1] < 10f)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 965, (int)(10f - ai[1]));
                        Main.item[num1018].noGrabDelay = 0;
                    }
                }
                if (type == 475)
                {
                    if (ai[1] == 0f)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 3005);
                        Main.item[num1018].noGrabDelay = 0;
                    }
                    else if (ai[1] < 10f)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 2996, (int)(10f - ai[1]));
                        Main.item[num1018].noGrabDelay = 0;
                    }
                }
                if (type == 505)
                {
                    if (ai[1] == 0f)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 3079);
                        Main.item[num1018].noGrabDelay = 0;
                    }
                    else if (ai[1] < 10f)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 3077, (int)(10f - ai[1]));
                        Main.item[num1018].noGrabDelay = 0;
                    }
                }
                if (type == 506)
                {
                    if (ai[1] == 0f)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 3080);
                        Main.item[num1018].noGrabDelay = 0;
                    }
                    else if (ai[1] < 10f)
                    {
                        num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 3078, (int)(10f - ai[1]));
                        Main.item[num1018].noGrabDelay = 0;
                    }
                }
                if (type == 12 && damage > 500 && !Main.remixWorld)
                {
                    num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 75);
                }
                if (type == 155)
                {
                    num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 859);
                }
                if (type == 861)
                {
                    num1018 = Item.NewItem(GetItemSource_DropAsItem(), (int)position.X, (int)position.Y, width, height, 4743);
                }
                if (Main.netMode == 1 && num1018 >= 0)
                {
                    NetMessage.SendData(21, -1, -1, null, num1018, 1f);
                }
            }
            if (type == 69 || type == 70 || type == 621)
            {
                int i2 = (int)(position.X + (float)(width / 2)) / 16;
                int j2 = (int)(position.Y + (float)(height / 2)) / 16;
                if (type == 69)
                {
                    WorldGen.Convert(i2, j2, 2);
                }
                if (type == 70)
                {
                    WorldGen.Convert(i2, j2, 1);
                }
                if (type == 621)
                {
                    WorldGen.Convert(i2, j2, 4);
                }
            }
            if (type == 378)
            {
                int num1027 = Main.rand.Next(2, 4);
                if (Main.rand.Next(5) == 0)
                {
                    num1027++;
                }
                for (int num1028 = 0; num1028 < num1027; num1028++)
                {
                    float x2 = velocity.X;
                    float y8 = velocity.Y;
                    x2 *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                    y8 *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                    NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, x2, y8, 379, damage, knockBack, owner);
                }
            }
        }
        active = false;
    }
References Terraria.Mount.AbilityActive, Terraria.Main.Achievements, Terraria.Entity.active, Terraria.Tile.active(), Terraria.NPC.AddBuff(), Terraria.Player.AddBuff(), Terraria.Projectile.ai, Terraria.NPC.AI_121_QueenSlime_GetDustColor(), Terraria.Dust.alpha, Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.ArmorSetDye(), Terraria.Player.beeDamage(), Terraria.Player.beeKB(), Terraria.Player.beeType(), Terraria.WorldGen.BlockBelowMakesSandFall(), Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.PopupText.ClearSonarText(), Terraria.Dust.CloneDust(), Terraria.Dust.color, Terraria.WorldGen.Convert(), Terraria.ID.ItemID.Count, Terraria.ID.ProjectileID.Count, Terraria.ID.TileID.Sets.CrackedBricks, Terraria.Player.creativeGodMode, Terraria.GameContent.Damage, Terraria.ID.SoundID.DD2_BetsyFireballImpact, Terraria.ID.SoundID.DD2_BetsysWrathImpact, Terraria.ID.SoundID.DD2_GoblinBomb, Terraria.ID.SoundID.DD2_SkyDragonsFuryCircle, Terraria.Player.dead, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.ID.ProjectileID.Sets.DontCancelChannelOnKill, Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Main.expertMode, Terraria.Dust.fadeIn, Terraria.Player.FindClosest(), ReLogic.Utilities.SlotId.FromFloat(), Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(), Terraria.Main.getGoodWorld, Terraria.Utils.GetLerpValue(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.Projectile.getRect(), Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Framing.GetTileSafely(), Terraria.Main.gore, Terraria.Player.gravDir, Terraria.Tile.halfBrick(), Terraria.Entity.height, Terraria.Collision.HitTiles(), Terraria.Main.hslToRgb(), Terraria.Main.item, Terraria.ID.SoundID.Item10, Terraria.ID.SoundID.Item100, Terraria.ID.SoundID.Item107, Terraria.ID.SoundID.Item110, Terraria.ID.SoundID.Item118, Terraria.ID.SoundID.Item127, Terraria.ID.SoundID.Item14, Terraria.ID.SoundID.Item16, Terraria.ID.SoundID.Item21, Terraria.ID.SoundID.Item27, Terraria.ID.SoundID.Item4, Terraria.ID.SoundID.Item45, Terraria.ID.SoundID.Item50, Terraria.ID.SoundID.Item51, Terraria.ID.SoundID.Item54, Terraria.ID.SoundID.Item62, Terraria.ID.SoundID.Item89, Terraria.ID.SoundID.Item94, Terraria.ID.SoundID.Item96, Terraria.Projectile.Kill(), Terraria.WorldGen.KillTile(), Terraria.NPC.life, Terraria.Projectile.localAI, Terraria.Main.LogicCheckScreenWidth, Terraria.Projectile.magic, Terraria.Wiring.MassWireOperation(), Terraria.Projectile.maxPenetrate, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Player.mount, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Projectile.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Gore.NewGoreDirect(), Terraria.Item.NewItem(), Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Item.noGrabDelay, Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Main.npc, Terraria.Main.offScreenRange, Terraria.Main.OurFavoriteColor, Terraria.Projectile.owner, Terraria.Projectile.penetrate, Terraria.WorldGen.PlaceTile(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Dust.position, Terraria.Entity.position, Terraria.Gore.position, Terraria.Main.projectile, Terraria.Main.projectileIdentity, Terraria.Main.ProjectileUpdateLoopIndex, Terraria.Main.projPet, Terraria.Main.rand, Terraria.WorldGen.RandomizeBackgroundBasedOnPlayer(), Terraria.WorldGen.RandomizeMoonState(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition(), Terraria.Utils.RandomVector2(), Terraria.Projectile.ranged, Terraria.Utils.Remap(), Terraria.Main.remixWorld, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Dust.scale, Terraria.Gore.scale, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.NetMessage.SendData(), Terraria.Player.setApprenticeT3, Terraria.Dust.shader, Terraria.NPC.ShieldStrengthTowerMax, Terraria.NPC.ShieldStrengthTowerNebula, Terraria.NPC.ShieldStrengthTowerSolar, Terraria.NPC.ShieldStrengthTowerStardust, Terraria.NPC.ShieldStrengthTowerVortex, Terraria.Tile.slope(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SolidTile(), Terraria.DelegateMethods.SpreadDirt(), Terraria.DelegateMethods.SpreadDry(), Terraria.DelegateMethods.SpreadHoney(), Terraria.DelegateMethods.SpreadLava(), Terraria.DelegateMethods.SpreadWater(), Terraria.Player.starCloakCooldown, Terraria.Gore.sticky, Terraria.Audio.ActiveSound.Stop(), Terraria.Mount.StopAbilityCharge(), Terraria.Main.tenthAnniversaryWorld, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Projectile.timeLeft, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.WorldGen.TreeTops, Terraria.Player.TryCancelChannel(), Terraria.Dust.type, Terraria.NPC.type, Terraria.Projectile.type, Terraria.Tile.type, Terraria.Mount.UseAbility(), Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Gore.velocity, and Terraria.Entity.width.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.Projectile.AI_152_SuperStarSlash(), Terraria.Projectile.AI_154_VoidLens(), Terraria.GameContent.Events.DD2Event.ClearAllTowersInGame(), Terraria.Projectile.Damage(), Terraria.Player.DashMovement(), Terraria.Player.DestroyOldestProximityMinesOverMinesCap(), Terraria.Player.DropSelectedItem_InterruptActionsThatUseAnimations(), Terraria.Player.FreeUpPetsAndMinions(), Terraria.MessageBuffer.GetData(), Terraria.Projectile.HandleMovement(), Terraria.Player.Hurt(), Terraria.Projectile.Interrupt(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_TryDestroyingDrones(), Terraria.Player.ItemCheck_TurretAltFeatureUse(), Terraria.Projectile.Kill(), Terraria.Projectile.KillOldestJavelin(), Terraria.Projectile.NewProjectile(), Terraria.NPC.PopAllAttachedProjectilesAndTakeDamageForThem(), Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup(), Terraria.Player.QuickGrapple(), Terraria.Player.RemoveAllFishingBobbers(), Terraria.Player.RemoveAllGrapplingHooks(), Terraria.GameContent.PortalHelper.RemoveIntersectingPortals(), Terraria.GameContent.PortalHelper.RemoveMyOldPortal(), Terraria.Projectile.Shimmer(), Terraria.Player.TileInteractionsUse(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Projectile.Update(), Terraria.Player.UpdateAbigailStatus(), Terraria.Player.UpdateBuffs(), Terraria.Player.UpdateMaxTurrets(), Terraria.Player.UpdateStormTigerStatus(), and Terraria.Player.WOFTongue().