Terraria: Terraria.Projectile.AI
AI()
void Terraria.Projectile.AI () inline
References Terraria.Entity.active, Terraria.Projectile.AI_001(), Terraria.Projectile.aiStyle, Terraria.Projectile.alpha, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Projectile.Colliding(), Terraria.Projectile.damage, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Projectile.FindTargetWithLineOfSight(), Terraria.Projectile.frame, Terraria.Projectile.frameCounter, Terraria.Main.gore, Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.Player.InOpposingTeam(), Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item14, Terraria.ID.SoundID.Item7, Terraria.Projectile.Kill(), Terraria.Projectile.knockBack, Terraria.Projectile.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.netUpdate, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Projectile.rotation, Terraria.Dust.scale, Terraria.Gore.scale, Terraria.Projectile.soundDelay, Terraria.Projectile.spriteDirection, Terraria.Projectile.tileCollide, Terraria.NPC.townNPC, Terraria.Projectile.type, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Main.windPhysics, and Terraria.Main.windPhysicsStrength.
Referenced by Terraria.Projectile.Update().