Terraria: Terraria.Projectile.ghostHeal
ghostHeal()
void Terraria.Projectile.ghostHeal (int dmg, Vector2 Position, Entity victim) inline
    {
        float num = 0.2f;
        num -= (float)numHits * 0.05f;
        if (num <= 0f)
        {
            return;
        }
        float num2 = (float)dmg * num;
        if ((int)num2 <= 0 || Main.player[Main.myPlayer].lifeSteal <= 0f)
        {
            return;
        }
        Main.player[Main.myPlayer].lifeSteal -= num2;
        if (!magic)
        {
            return;
        }
        float num3 = 0f;
        int num4 = owner;
        for (int i = 0; i < 255; i++)
        {
            if (Main.player[i].active && !Main.player[i].dead && ((!Main.player[owner].hostile && !Main.player[i].hostile) || Main.player[owner].team == Main.player[i].team) && Distance(Main.player[i].Center) <= 3000f)
            {
                int num5 = Main.player[i].statLifeMax2 - Main.player[i].statLife;
                if ((float)num5 > num3)
                {
                    num3 = num5;
                    num4 = i;
                }
            }
        }
        NewProjectile(GetProjectileSource_OnHit(victim, 15), Position.X, Position.Y, 0f, 0f, 298, 0, 0f, owner, num4, num2);
    }
References Terraria.Entity.active, Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.Distance(), Terraria.Projectile.GetProjectileSource_OnHit(), Terraria.Player.hostile, Terraria.Player.lifeSteal, Terraria.Projectile.magic, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Projectile.numHits, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Player.statLife, Terraria.Player.statLifeMax2, and Terraria.Player.team.
Referenced by Terraria.Projectile.Damage().