Terraria: Terraria.Projectile.BombsHurtPlayers
BombsHurtPlayers()
void Terraria.Projectile.BombsHurtPlayers (Rectangle projRectangle, int j) inline private
    {
        if (aiStyle != 16 || ProjectileID.Sets.RocketsSkipDamageForPlayers[type] || (timeLeft > 1 && type != 108 && type != 164 && type != 1002) || !Main.player[j].active || Main.player[j].dead || Main.player[j].immune || (ownerHitCheck && !CanHitWithMeleeWeapon(Main.player[j])))
        {
            return;
        }
        Rectangle value = new Rectangle((int)Main.player[j].position.X, (int)Main.player[j].position.Y, Main.player[j].width, Main.player[j].height);
        if (!projRectangle.Intersects(value))
        {
            return;
        }
        if (Main.player[j].position.X + (float)(Main.player[j].width / 2) < position.X + (float)(width / 2))
        {
            direction = -1;
        }
        else
        {
            direction = 1;
        }
        int num = Main.DamageVar(damage, 0f - Main.player[j].luck);
        int playerIndex = owner;
        bool pvp = true;
        if (type == 108 || type == 1002)
        {
            playerIndex = -1;
            pvp = false;
        }
        if (ProjectileID.Sets.IsAGravestone[type])
        {
            playerIndex = (int)ai[0];
        }
        bool dodgeable = IsDamageDodgable();
        PlayerDeathReason damageSource = PlayerDeathReason.ByProjectile(playerIndex, whoAmI);
        if (Main.player[j].Hurt(damageSource, num, direction, pvp, quiet: false, Crit: false, -1, dodgeable) > 0.0 && !Main.player[j].dead)
        {
            StatusPlayer(j);
        }
        if (trap)
        {
            Main.player[j].trapDebuffSource = true;
            if (Main.player[j].dead)
            {
                AchievementsHelper.HandleSpecialEvent(Main.player[j], 4);
            }
        }
    }
References Terraria.Entity.active, Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.DataStructures.PlayerDeathReason.ByProjectile(), Terraria.Projectile.CanHitWithMeleeWeapon(), Terraria.Projectile.damage, Terraria.Main.DamageVar(), Terraria.Player.dead, Terraria.Entity.direction, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Entity.height, Terraria.Player.Hurt(), Terraria.Player.immune, Terraria.ID.ProjectileID.Sets.IsAGravestone, Terraria.Projectile.IsDamageDodgable(), Terraria.Player.luck, Terraria.Projectile.owner, Terraria.Projectile.ownerHitCheck, Terraria.Main.player, Terraria.Entity.position, Terraria.ID.ProjectileID.Sets.RocketsSkipDamageForPlayers, Terraria.Projectile.StatusPlayer(), Terraria.Projectile.timeLeft, Terraria.Projectile.trap, Terraria.Player.trapDebuffSource, Terraria.Projectile.type, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Projectile.Damage().