Terraria: UIBestiaryInfoLine.DrawSelf
DrawSelf()
override void UIBestiaryInfoLine< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         CalculatedStyle innerDimensions = GetInnerDimensions();
         Vector2 pos = innerDimensions.Position();
         pos.Y -= 2f * _textScale;
         pos.X += (innerDimensions.Width - _textSize.X) * 0.5f;
         Utils.DrawBorderString(spriteBatch, Text, pos, _color, _textScale);
     }
References UIBestiaryInfoLine< T >._color, UIBestiaryInfoLine< T >._textScale, UIBestiaryInfoLine< T >._textSize, Utils.DrawBorderString(), UIElement.GetInnerDimensions(), CalculatedStyle.Position(), UIBestiaryInfoLine< T >.Text, and CalculatedStyle.Width.