Terraria: Terraria.Projectile.AI_134_Ballista_FindTarget
AI_134_Ballista_FindTarget()
int Terraria.Projectile.AI_134_Ballista_FindTarget (float shot_range, float deadBottomAngle, Vector2 shootingSpot) inline private
Definition at line 57701 of file Projectile.cs.
    {
        int num = -1;
        NPC ownerMinionAttackTargetNPC = OwnerMinionAttackTargetNPC;
        if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this))
        {
            for (int i = 0; i < 1; i++)
            {
                if (!ownerMinionAttackTargetNPC.CanBeChasedBy(this))
                {
                    continue;
                }
                float num2 = Vector2.Distance(shootingSpot, ownerMinionAttackTargetNPC.Center);
                if (!(num2 > shot_range))
                {
                    Vector2 vector = (ownerMinionAttackTargetNPC.Center - shootingSpot).SafeNormalize(Vector2.UnitY);
                    if ((!(Math.Abs(vector.X) < Math.Abs(vector.Y) * deadBottomAngle) || !(vector.Y > 0f)) && (num == -1 || num2 < Vector2.Distance(shootingSpot, Main.npc[num].Center)) && Collision.CanHitLine(shootingSpot, 0, 0, ownerMinionAttackTargetNPC.Center, 0, 0))
                    {
                        num = ownerMinionAttackTargetNPC.whoAmI;
                    }
                }
            }
            if (num != -1)
            {
                return num;
            }
        }
        for (int j = 0; j < 200; j++)
        {
            NPC nPC = Main.npc[j];
            if (!nPC.CanBeChasedBy(this))
            {
                continue;
            }
            float num3 = Vector2.Distance(shootingSpot, nPC.Center);
            if (!(num3 > shot_range))
            {
                Vector2 vector2 = (nPC.Center - shootingSpot).SafeNormalize(Vector2.UnitY);
                if ((!(Math.Abs(vector2.X) < Math.Abs(vector2.Y) * deadBottomAngle) || !(vector2.Y > 0f)) && (num == -1 || num3 < Vector2.Distance(shootingSpot, Main.npc[num].Center)) && Collision.CanHitLine(shootingSpot, 0, 0, nPC.Center, 0, 0))
                {
                    num = j;
                }
            }
        }
        return num;
    }
References Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Entity.Distance(), Terraria.Main.npc, and Terraria.Entity.whoAmI.