Terraria: Terraria.Projectile.AI_193_Flamethrower
AI_193_Flamethrower()
void Terraria.Projectile.AI_193_Flamethrower () inline private
    {
        localAI[0] += 1f;
        int num = 60;
        int num2 = 12;
        int num3 = num + num2;
        if (localAI[0] >= (float)num3)
        {
            Kill();
        }
        if (localAI[0] >= (float)num)
        {
            velocity *= 0.95f;
        }
        bool flag = ai[0] == 1f;
        int num4 = 50;
        int num5 = num4;
        if (flag)
        {
            num4 = 0;
            num5 = num;
        }
        if (localAI[0] < (float)num5 && Main.rand.NextFloat() < 0.25f)
        {
            short num6 = (short)(flag ? 135 : 6);
            Dust dust = Dust.NewDustDirect(base.Center + Main.rand.NextVector2Circular(60f, 60f) * Utils.Remap(localAI[0], 0f, 72f, 0.5f, 1f), 4, 4, num6, velocity.X * 0.2f, velocity.Y * 0.2f, 100);
            if (Main.rand.Next(4) == 0)
            {
                dust.noGravity = true;
                dust.scale *= 3f;
                dust.velocity.X *= 2f;
                dust.velocity.Y *= 2f;
            }
            else
            {
                dust.scale *= 1.5f;
            }
            dust.scale *= 1.5f;
            dust.velocity *= 1.2f;
            dust.velocity += velocity * 1f * Utils.Remap(localAI[0], 0f, (float)num * 0.75f, 1f, 0.1f) * Utils.Remap(localAI[0], 0f, (float)num * 0.1f, 0.1f, 1f);
            dust.customData = 1;
        }
        if (num4 > 0 && localAI[0] >= (float)num4 && Main.rand.NextFloat() < 0.5f)
        {
            Vector2 center = Main.player[owner].Center;
            Vector2 vector = (base.Center - center).SafeNormalize(Vector2.Zero).RotatedByRandom(0.19634954631328583) * 7f;
            short num7 = 31;
            Dust dust2 = Dust.NewDustDirect(base.Center + Main.rand.NextVector2Circular(50f, 50f) - vector * 2f, 4, 4, num7, 0f, 0f, 150, new Color(80, 80, 80));
            dust2.noGravity = true;
            dust2.velocity = vector;
            dust2.scale *= 1.1f + Main.rand.NextFloat() * 0.2f;
            dust2.customData = -0.3f - 0.15f * Main.rand.NextFloat();
        }
    }
References Terraria.Entity.Center, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, and Terraria.Utils.Remap().