Terraria: Terraria.Projectile.AI_161_RapierStabs
AI_161_RapierStabs()
void Terraria.Projectile.AI_161_RapierStabs () inline private
Definition at line 39450 of file Projectile.cs.
    {
        Player player = Main.player[owner];
        rotation = velocity.ToRotation() + (float)Math.PI / 2f;
        ai[0] += 1f;
        float opacity = Utils.GetLerpValue(0f, 7f, ai[0], clamped: true) * Utils.GetLerpValue(16f, 12f, ai[0], clamped: true);
        Opacity = opacity;
        base.Center = player.RotatedRelativePoint(player.MountedCenter, reverseRotation: false, addGfxOffY: false) + velocity * (ai[0] - 1f);
        spriteDirection = ((!(Vector2.Dot(velocity, Vector2.UnitX) < 0f)) ? 1 : (-1));
        if (ai[0] >= 16f)
        {
            Kill();
        }
        else
        {
            player.heldProj = whoAmI;
        }
    }
References Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Utils.GetLerpValue(), Terraria.Player.MountedCenter, System.Math.PI, Terraria.Main.player, Terraria.Player.RotatedRelativePoint(), and Microsoft.Xna.Framework.Vector2.UnitX.