Terraria: Terraria.Projectile.GetFishingPondState
GetFishingPondState()
static void Terraria.Projectile.GetFishingPondState (int x, int y, out bool lava, out bool honey, out int numWaters, out int chumCount) inline static private
Definition at line 17978 of file Projectile.cs.
    {
        lava = false;
        honey = false;
        numWaters = 0;
        chumCount = 0;
        Point tileCoords = new Point(0, 0);
        GetFishingPondWidth(x, y, out var minX, out var maxX);
        for (int i = minX; i <= maxX; i++)
        {
            int num = y;
            while (Main.tile[i, num] != null && Main.tile[i, num].liquid > 0 && !WorldGen.SolidTile(i, num) && num < Main.maxTilesY - 10)
            {
                numWaters++;
                num++;
                if (Main.tile[i, num].lava())
                {
                    lava = true;
                }
                else if (Main.tile[i, num].honey())
                {
                    honey = true;
                }
                tileCoords.X = i;
                tileCoords.Y = num;
                chumCount += Main.instance.ChumBucketProjectileHelper.GetChumsInLocation(tileCoords);
            }
        }
        if (honey)
        {
            numWaters = (int)((double)numWaters * 1.5);
        }
    }
References Terraria.Main.ChumBucketProjectileHelper, Terraria.GameContent.ChumBucketProjectileHelper.GetChumsInLocation(), Terraria.Projectile.GetFishingPondWidth(), Terraria.Tile.honey(), Terraria.Main.instance, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.WorldGen.SolidTile(), and Terraria.Main.tile.
Referenced by Terraria.Projectile.FishingCheck().