Terraria: Terraria.Projectile.SetDefaults
SetDefaults()
void Terraria.Projectile.SetDefaults (int Type) inline
References Terraria.Entity.active, Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.Projectile.alpha, Terraria.Projectile.appliesImmunityTimeOnSingleHits, Terraria.Projectile.arrow, Terraria.Projectile.bannerIdToRespondTo, Terraria.Projectile.bobber, Terraria.Projectile.coldDamage, Terraria.Projectile.counterweight, Terraria.Projectile.damage, Terraria.Projectile.decidesManualFallThrough, Terraria.Projectile.DefaultToSpray(), Terraria.Projectile.DefaultToWhip(), Terraria.Projectile.extraUpdates, Terraria.Projectile.frame, Terraria.Projectile.frameCounter, Terraria.Projectile.friendly, Terraria.Main.getGoodWorld, Terraria.Projectile.glowMask, Terraria.Entity.height, Terraria.Projectile.hide, Terraria.Projectile.hostile, Terraria.Projectile.identity, Terraria.Projectile.idStaticNPCHitCooldown, Terraria.Projectile.ignoreWater, Terraria.Projectile.isAPreviewDummy, Terraria.Projectile.knockBack, Terraria.Entity.lavaWet, Terraria.Projectile.light, Terraria.Projectile.localAI, Terraria.Projectile.localNPCHitCooldown, Terraria.Projectile.magic, Terraria.Projectile.manualDirectionChange, Terraria.Projectile.maxAI, Terraria.Projectile.maxPenetrate, Terraria.Projectile.MaxUpdates, Terraria.Projectile.melee, Terraria.Projectile.minion, Terraria.Projectile.minionSlots, Terraria.Projectile.miscText, Terraria.Projectile.netImportant, Terraria.Projectile.netSpam, Terraria.Projectile.netUpdate, Terraria.Projectile.netUpdate2, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Projectile.noDropItem, Terraria.Projectile.noEnchantments, Terraria.Projectile.noEnchantmentVisuals, Terraria.Projectile.npcProj, Terraria.Projectile.numHits, Terraria.Projectile.numUpdates, Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Projectile.oldSpriteDirection, Terraria.Projectile.Opacity, Terraria.Projectile.originalDamage, Terraria.Projectile.originatedFromActivableTile, Terraria.Projectile.owner, Terraria.Projectile.ownerHitCheck, Terraria.Projectile.ownerHitCheckDistance, Terraria.Projectile.penetrate, Terraria.Projectile.playerImmune, Terraria.Entity.position, Terraria.Projectile.projUUID, Terraria.Main.rand, Terraria.Projectile.ranged, Terraria.Projectile.reflected, Terraria.Main.remixWorld, Terraria.Projectile.ResetLocalNPCHitImmunity(), Terraria.Projectile.restrikeDelay, Terraria.Projectile.rotation, Terraria.Projectile.scale, Terraria.Projectile.sentry, Terraria.Projectile.shouldFallThrough, Terraria.Projectile.soundDelay, Terraria.Projectile.spriteDirection, Terraria.Projectile.stopsDealingDamageAfterPenetrateHits, Terraria.Projectile.tileCollide, Terraria.Projectile.timeLeft, Terraria.ID.ProjectileID.Sets.TrailCacheLength, Terraria.Projectile.trap, Terraria.Projectile.type, Terraria.Projectile.usesIDStaticNPCImmunity, Terraria.Projectile.usesLocalNPCImmunity, Terraria.Projectile.usesOwnerMeleeHitCD, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.wetCount, and Terraria.Entity.width.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.ID.ContentSamples.Initialize(), Terraria.Projectile.NewProjectile(), and Terraria.GameContent.UI.Elements.UICharacter.PreparePetProjectiles_CreatePetProjectileDummy().