Terraria: Terraria.Projectile.NewProjectile
NewProjectile() [2/2]
static int Terraria.Projectile.NewProjectile (IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner = -1, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f) inline static
Definition at line 9664 of file Projectile.cs.
    {
        return NewProjectile(spawnSource, position.X, position.Y, velocity.X, velocity.Y, Type, Damage, KnockBack, Owner, ai0, ai1, ai2);
    }
References Terraria.Projectile.Damage(), Terraria.Projectile.NewProjectile(), Terraria.Entity.position, and Terraria.Entity.velocity.
Referenced by Terraria.GameContent.PortalHelper.AddPortal(), Terraria.NPC.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_119_Dandelion(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_123_Deerclops_ShootRubbleUp(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.Player.BloodButcherer_TryButchering(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.Player.BuffHandle_SpawnPetIfNeeded(), Terraria.Mount.CastSuperCartLaser(), Terraria.WorldGen.Check2x2(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckSuper(), Terraria.Player.CommandForbiddenStorm(), Terraria.Player.Counterweight(), Terraria.Cinematics.DSTFilm.CreateChester(), Terraria.Projectile.Damage(), Terraria.Player.DashMovement(), Terraria.NPC.DoDeathEvents(), Terraria.Main.DrawWallOfStars(), Terraria.Player.DropTombstone(), Terraria.NPC.DropTombstoneTownNPC(), Terraria.WorldGen.ExplodeMine(), Terraria.Wiring.GeyserTrap(), Terraria.Projectile.ghostHeal(), Terraria.Projectile.ghostHurt(), Terraria.Projectile.HandleMovement(), Terraria.NPC.HaveDryadDoStardewAnimation(), Terraria.NPC.HitEffect(), Terraria.Wiring.HitWireSingle(), Terraria.Player.HorsemansBlade_SpawnPumpkin(), Terraria.Player.Hurt(), Terraria.Player.ItemCheck_EmitHammushProjectiles(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_OwnerOnlyCode(), Terraria.Player.ItemCheck_Shoot(), Terraria.WorldGen.KillTile(), Terraria.Player.LaunchMinecartHook(), Terraria.WorldGen.LaunchRocket(), Terraria.WorldGen.LaunchRocketSmall(), Terraria.Projectile.NewProjectile(), Terraria.Player.OnHit(), Terraria.Player.QuickGrapple(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.ShootFromCannon(), Terraria.WorldGen.SpawnFallingBlockProjectile(), Terraria.Player.SpawnHallucination(), Terraria.Player.SpawnMinionOnCursor(), Terraria.NPC.SpawnPassiveShadowHands(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.SpawnStardustMark_StardustWorm(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.Player.SporeSac(), Terraria.Mount.StartAbilityCharge(), Terraria.NPC.StingerExplosion(), Terraria.Projectile.SummonMonkGhast(), Terraria.Projectile.SummonSuperStarSlash(), Terraria.Player.TentacleSpike_TrySpiking(), Terraria.Player.TileInteractionsUse(), Terraria.Player.TorchAttack(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Player.UpdateAbigailStatus(), Terraria.Player.UpdateArmorSets(), Terraria.Player.UpdateBuffs(), Terraria.Player.UpdateStormTigerStatus(), Terraria.WorldGen.UpdateWorld(), Terraria.Mount.UseAbility(), Terraria.Projectile.vampireHeal(), Terraria.Player.VolatileGelatin(), and Terraria.Player.Volcano_TrySpawningVolcano().