Terraria: Terraria.Projectile.SummonSuperStarSlash
SummonSuperStarSlash()
void Terraria.Projectile.SummonSuperStarSlash (Vector2 target) inline private
Definition at line 13113 of file Projectile.cs.
    {
        Vector2 v = Main.rand.NextVector2CircularEdge(200f, 200f);
        if (v.Y < 0f)
        {
            v.Y *= -1f;
        }
        v.Y += 100f;
        Vector2 vector = v.SafeNormalize(Vector2.UnitY) * 6f;
        NewProjectile(GetProjectileSource_FromThis(), target - vector * 20f, vector, 729, (int)((double)damage * 0.75), 0f, owner, 0f, target.Y);
    }
References Terraria.Projectile.damage, Terraria.Projectile.GetProjectileSource_FromThis(), Terraria.Projectile.NewProjectile(), Terraria.Projectile.owner, Terraria.Main.rand, Microsoft.Xna.Framework.Vector2.UnitY, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.Damage().