Terraria: Terraria.Projectile.AI_179_FairyQueenLance
AI_179_FairyQueenLance()
void Terraria.Projectile.AI_179_FairyQueenLance () inline private
Definition at line 37006 of file Projectile.cs.
    {
        localAI[0] += 1f;
        if (localAI[0] >= 60f)
        {
            velocity = ai[0].ToRotationVector2() * 40f;
            if (Main.rand.Next(3) == 0)
            {
                Dust dust = Dust.NewDustPerfect(base.Center, 267);
                dust.fadeIn = 1f;
                dust.noGravity = true;
                dust.alpha = 100;
                dust.color = Color.Lerp(AI_171_GetColor(), Color.White, Main.rand.NextFloat() * 0.4f);
                dust.noLightEmittence = true;
                dust.scale *= 1.5f;
            }
        }
        if (localAI[0] >= 360f)
        {
            Kill();
            return;
        }
        alpha = (int)MathHelper.Lerp(255f, 0f, Utils.GetLerpValue(0f, 20f, localAI[0], clamped: true));
        rotation = ai[0];
    }
References Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Dust.NewDustPerfect(), Terraria.Main.rand, and Microsoft.Xna.Framework.Color.White.