Terraria: Terraria.Projectile.AI_173_GetColor
AI_173_GetColor()
Color Terraria.Projectile.AI_173_GetColor () inline
Definition at line 37425 of file Projectile.cs.
    {
        if (NPC.ShouldEmpressBeEnraged())
        {
            float lerpValue = Utils.GetLerpValue(0f, 60f, (int)Main.time, clamped: true);
            return Color.Lerp(Color.White, Main.OurFavoriteColor, lerpValue) * Opacity;
        }
        return Main.hslToRgb((ai[1] + 0f) % 1f, 1f, 0.5f) * Opacity;
    }
References Terraria.Utils.GetLerpValue(), Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.OurFavoriteColor, Terraria.NPC.ShouldEmpressBeEnraged(), Terraria.Main.time, and Microsoft.Xna.Framework.Color.White.