Terraria: ReLogic.Content.Sources.ZipContentSource.BuildEntryList
BuildEntryList()
void ReLogic.Content.Sources.ZipContentSource.BuildEntryList () inline private
Definition at line 64 of file ZipContentSource.cs.
    {
        _entries.Clear();
        foreach (ZipEntry item in _zipFile.Entries.Where((ZipEntry entry) => !entry.IsDirectory && entry.FileName.StartsWith(_basePath)))
        {
            string fileName = item.FileName;
            string path = fileName.Substring(_basePath.Length, fileName.Length - _basePath.Length);
            path = AssetPathHelper.CleanPath(path);
            _entries[path] = item;
        }
        SetAssetNames(_entries.Keys);
    }
References ReLogic.Content.Sources.ZipContentSource._basePath, ReLogic.Content.Sources.ZipContentSource._entries, ReLogic.Content.Sources.ZipContentSource._zipFile, ReLogic.Content.AssetPathHelper.CleanPath(), and ReLogic.Content.Sources.ContentSource.SetAssetNames().
Referenced by ReLogic.Content.Sources.ZipContentSource.ZipContentSource(), and ReLogic.Content.Sources.ZipContentSource.ZipContentSource().