Terraria: System.Diagnostics.Tracing.EventPipeEventDispatcher.DispatchEventsToEventListeners
DispatchEventsToEventListeners()
unsafe void System.Diagnostics.Tracing.EventPipeEventDispatcher.DispatchEventsToEventListeners () inline private
Definition at line 130 of file EventPipeEventDispatcher.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out EventPipeEventInstanceData eventPipeEventInstanceData);
        while (!m_stopDispatchTask)
        {
            bool flag = false;
            while (!m_stopDispatchTask && EventPipeInternal.GetNextEvent(m_sessionID, &eventPipeEventInstanceData))
            {
                flag = true;
                if (eventPipeEventInstanceData.ProviderID == m_RuntimeProviderID)
                {
                    ReadOnlySpan<byte> payload = new ReadOnlySpan<byte>((void*)eventPipeEventInstanceData.Payload, (int)eventPipeEventInstanceData.PayloadLength);
                    DateTime timeStamp = TimeStampToDateTime(eventPipeEventInstanceData.TimeStamp);
                    NativeRuntimeEventSource.Log.ProcessEvent(eventPipeEventInstanceData.EventID, eventPipeEventInstanceData.ThreadID, timeStamp, eventPipeEventInstanceData.ActivityId, eventPipeEventInstanceData.ChildActivityId, payload);
                }
            }
            if (!m_stopDispatchTask)
            {
                if (!flag)
                {
                    m_dispatchTaskWaitHandle.WaitOne();
                }
                Thread.Sleep(10);
            }
        }
    }
References System.Diagnostics.Tracing.EventPipeInternal.GetNextEvent(), System.Diagnostics.Tracing.NativeRuntimeEventSource.Log, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_dispatchTaskWaitHandle, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_RuntimeProviderID, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_sessionID, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_stopDispatchTask, System.Threading.Thread.Sleep(), System.Diagnostics.Tracing.EventPipeEventDispatcher.TimeStampToDateTime(), and System.Threading.WaitHandle.WaitOne().
Referenced by System.Diagnostics.Tracing.EventPipeEventDispatcher.StartDispatchTask().