Terraria: System.Diagnostics.Tracing.EventPipeEventDispatcher.CommitDispatchConfiguration
CommitDispatchConfiguration()
unsafe void System.Diagnostics.Tracing.EventPipeEventDispatcher.CommitDispatchConfiguration () inline private
Definition at line 81 of file EventPipeEventDispatcher.cs.
    {
        StopDispatchTask();
        EventPipeInternal.Disable(m_sessionID);
        if (m_subscriptions.Count <= 0)
        {
            return;
        }
        EventKeywords eventKeywords = EventKeywords.None;
        EventLevel eventLevel = EventLevel.LogAlways;
        foreach (EventListenerSubscription value in m_subscriptions.Values)
        {
            eventKeywords |= value.MatchAnyKeywords;
            eventLevel = ((value.Level > eventLevel) ? value.Level : eventLevel);
        }
        EventPipeProviderConfiguration[] providers = new EventPipeProviderConfiguration[1]
        {
            new EventPipeProviderConfiguration("Microsoft-Windows-DotNETRuntime", (ulong)eventKeywords, (uint)eventLevel, null)
        };
        m_sessionID = EventPipeInternal.Enable(null, EventPipeSerializationFormat.NetTrace, 10u, providers);
        System.Runtime.CompilerServices.Unsafe.SkipInit(out EventPipeSessionInfo eventPipeSessionInfo);
        EventPipeInternal.GetSessionInfo(m_sessionID, &eventPipeSessionInfo);
        m_syncTimeUtc = DateTime.FromFileTimeUtc(eventPipeSessionInfo.StartTimeAsUTCFileTime);
        m_syncTimeQPC = eventPipeSessionInfo.StartTimeStamp;
        m_timeQPCFrequency = eventPipeSessionInfo.TimeStampFrequency;
        StartDispatchTask();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Diagnostics.Tracing.EventPipeInternal.Disable(), System.Diagnostics.Tracing.EventPipeInternal.Enable(), System.DateTime.FromFileTimeUtc(), System.Diagnostics.Tracing.EventPipeInternal.GetSessionInfo(), System.Diagnostics.Tracing.EventPipeEventDispatcher.m_sessionID, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_subscriptions, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_syncTimeQPC, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_syncTimeUtc, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_timeQPCFrequency, System.Diagnostics.Tracing.EventPipeEventDispatcher.StartDispatchTask(), System.Diagnostics.Tracing.EventPipeEventDispatcher.StopDispatchTask(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Diagnostics.Tracing.EventPipeEventDispatcher.RemoveEventListener(), and System.Diagnostics.Tracing.EventPipeEventDispatcher.SendCommand().