Terraria: System.Diagnostics.Tracing.EventPipeEventDispatcher.StopDispatchTask
StopDispatchTask()
void System.Diagnostics.Tracing.EventPipeEventDispatcher.StopDispatchTask () inline private
Definition at line 119 of file EventPipeEventDispatcher.cs.
    {
        if (m_dispatchTask != null)
        {
            m_stopDispatchTask = true;
            EventWaitHandle.Set(m_dispatchTaskWaitHandle.SafeWaitHandle);
            m_dispatchTask.Wait();
            m_dispatchTask = null;
        }
    }
References System.Diagnostics.Tracing.EventPipeEventDispatcher.m_dispatchTask, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_dispatchTaskWaitHandle, System.Diagnostics.Tracing.EventPipeEventDispatcher.m_stopDispatchTask, System.Threading.WaitHandle.SafeWaitHandle, System.Threading.EventWaitHandle.Set(), and System.Threading.Tasks.Task< TResult >.Wait().
Referenced by System.Diagnostics.Tracing.EventPipeEventDispatcher.CommitDispatchConfiguration().