Terraria: System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext
MoveNext() [1/2]
void System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext () inline private
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 231 of file BufferedFileStreamStrategy.cs.
        {
            int num = _003C_003E1__state;
            BufferedFileStreamStrategy bufferedFileStreamStrategy = _003C_003E4__this;
            try
            {
                ConfiguredTaskAwaitable.ConfiguredTaskAwaiter awaiter;
                if (num != 0)
                {
                    if ((uint)(num - 1) <= 1u)
                    {
                        goto IL_007c;
                    }
                    awaiter = semaphoreLockTask.ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                    if (!awaiter.IsCompleted)
                    {
                        num = (_003C_003E1__state = 0);
                        _003C_003Eu__1 = awaiter;
                        _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                        return;
                    }
                }
                else
                {
                    awaiter = _003C_003Eu__1;
                    _003C_003Eu__1 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                    num = (_003C_003E1__state = -1);
                }
                awaiter.GetResult();
                goto IL_007c;
                IL_007c:
                try
                {
                    ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter2;
                    if (num == 1)
                    {
                        awaiter2 = _003C_003Eu__2;
                        _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                        num = (_003C_003E1__state = -1);
                        goto IL_01e1;
                    }
                    ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter3;
                    if (num == 2)
                    {
                        awaiter3 = _003C_003Eu__2;
                        _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                        num = (_003C_003E1__state = -1);
                        goto IL_0278;
                    }
                    if (bufferedFileStreamStrategy._writePos == 0)
                    {
                        bufferedFileStreamStrategy.ClearReadBufferBeforeWrite();
                    }
                    if (bufferedFileStreamStrategy._writePos <= 0)
                    {
                        goto IL_01ef;
                    }
                    int num2 = bufferedFileStreamStrategy._bufferSize - bufferedFileStreamStrategy._writePos;
                    if (num2 <= 0)
                    {
                        goto IL_015f;
                    }
                    ReadOnlySpan<byte> readOnlySpan;
                    if (num2 < source.Length)
                    {
                        readOnlySpan = source.Span;
                        readOnlySpan = readOnlySpan.Slice(0, num2);
                        readOnlySpan.CopyTo(bufferedFileStreamStrategy._buffer.AsSpan(bufferedFileStreamStrategy._writePos));
                        bufferedFileStreamStrategy._writePos += num2;
                        source = source.Slice(num2);
                        goto IL_015f;
                    }
                    readOnlySpan = source.Span;
                    readOnlySpan.CopyTo(bufferedFileStreamStrategy._buffer.AsSpan(bufferedFileStreamStrategy._writePos));
                    bufferedFileStreamStrategy._writePos += source.Length;
                    goto end_IL_007c;
                    IL_0278:
                    awaiter3.GetResult();
                    goto end_IL_007c;
                    IL_015f:
                    awaiter2 = bufferedFileStreamStrategy._strategy.WriteAsync(new ReadOnlyMemory<byte>(bufferedFileStreamStrategy._buffer, 0, bufferedFileStreamStrategy._writePos), cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                    if (!awaiter2.IsCompleted)
                    {
                        num = (_003C_003E1__state = 1);
                        _003C_003Eu__2 = awaiter2;
                        _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter2, ref this);
                        return;
                    }
                    goto IL_01e1;
                    IL_01ef:
                    if (source.Length >= bufferedFileStreamStrategy._bufferSize)
                    {
                        awaiter3 = bufferedFileStreamStrategy._strategy.WriteAsync(source, cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                        if (!awaiter3.IsCompleted)
{
                            num = (_003C_003E1__state = 2);
                            _003C_003Eu__2 = awaiter3;
                            _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter3, ref this);
                            return;
                        }
                        goto IL_0278;
                    }
                    if (source.Length != 0)
                    {
                        bufferedFileStreamStrategy.EnsureBufferAllocated();
                        readOnlySpan = source.Span;
                        readOnlySpan.CopyTo(bufferedFileStreamStrategy._buffer.AsSpan(bufferedFileStreamStrategy._writePos));
                        bufferedFileStreamStrategy._writePos = source.Length;
                    }
                    goto end_IL_007c;
                    IL_01e1:
                    awaiter2.GetResult();
                    bufferedFileStreamStrategy._writePos = 0;
                    goto IL_01ef;
                    end_IL_007c:;
                }
                finally
                {
                    if (num < 0)
                    {
                        bufferedFileStreamStrategy._asyncActiveSemaphore.Release();
                    }
                }
            }
            catch (Exception exception)
            {
                _003C_003E1__state = -2;
                _003C_003Et__builder.SetException(exception);
                return;
            }
            _003C_003E1__state = -2;
            _003C_003Et__builder.SetResult();
        }
References System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50._003C_003E1__state, System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50._003C_003E4__this, System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50._003C_003Et__builder, System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50._003C_003Eu__1, System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50._003C_003Eu__2, System.IO.Stream._asyncActiveSemaphore, System.IO.Strategies.BufferedFileStreamStrategy._buffer, System.IO.Strategies.BufferedFileStreamStrategy._bufferSize, System.IO.Strategies.BufferedFileStreamStrategy._strategy, System.IO.Strategies.BufferedFileStreamStrategy._writePos, System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.cancellationToken, System.IO.Strategies.BufferedFileStreamStrategy.ClearReadBufferBeforeWrite(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.ReadOnlySpan< T >.CopyTo(), System.IO.Strategies.BufferedFileStreamStrategy.EnsureBufferAllocated(), System.exception, System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted, System.ReadOnlyMemory< T >.Length, System.Threading.SemaphoreSlim.Release(), System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.semaphoreLockTask, System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.SetException(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.SetResult(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlySpan< T >.Slice(), System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.source, System.ReadOnlyMemory< T >.Span, and System.IO.Stream.WriteAsync().
Referenced by System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext().