Terraria: System.Net.CommandStream.ReceiveCommandResponse
ReceiveCommandResponse()
ResponseDescription System.Net.CommandStream.ReceiveCommandResponse () inline private inherited
Definition at line 429 of file CommandStream.cs.
    {
        ReceiveState receiveState = new ReceiveState(this);
        try
        {
            if (_buffer.Length > 0)
            {
                ReceiveCommandResponseCallback(receiveState, -1);
            }
            else
            {
                try
                {
                    if (_isAsync)
                    {
                        BeginRead(receiveState.Buffer, 0, receiveState.Buffer.Length, s_readCallbackDelegate, receiveState);
                        return null;
                    }
                    int num = Read(receiveState.Buffer, 0, receiveState.Buffer.Length);
                    if (num == 0)
                    {
                        CloseSocket();
                    }
                    ReceiveCommandResponseCallback(receiveState, num);
                }
                catch (IOException)
                {
                    MarkAsRecoverableFailure();
                    throw;
                }
                catch
                {
                    throw;
                }
            }
        }
        catch (Exception ex2)
        {
            if (ex2 is WebException)
            {
                throw;
            }
            throw GenerateException(System.SR.net_ftp_receivefailure, WebExceptionStatus.ReceiveFailure, ex2);
        }
        return receiveState.Resp;
    }
References System.Net.CommandStream._buffer, System.Net.CommandStream._isAsync, System.Net.NetworkStreamWrapper.BeginRead(), System.Net.ReceiveState.Buffer, System.Net.NetworkStreamWrapper.CloseSocket(), System.Net.CommandStream.GenerateException(), System.Net.CommandStream.MarkAsRecoverableFailure(), System.SR.net_ftp_receivefailure, System.IO.Read, System.Net.CommandStream.ReceiveCommandResponseCallback(), System.Net.ReceiveState.Resp, and System.Net.CommandStream.s_readCallbackDelegate.
Referenced by System.Net.CommandStream.PostSendCommandProcessing().