Terraria: System.Net.CommandStream.ReceiveCommandResponseCallback
ReceiveCommandResponseCallback()
void System.Net.CommandStream.ReceiveCommandResponseCallback (ReceiveState state, int bytesRead) inline private inherited
Definition at line 476 of file CommandStream.cs.
    {
        int completeLength = -1;
        while (true)
        {
            int validThrough = state.ValidThrough;
            if (_buffer.Length > 0)
            {
                state.Resp.StatusBuffer.Append(_buffer);
                _buffer = string.Empty;
                if (!CheckValid(state.Resp, ref validThrough, ref completeLength))
                {
                    throw GenerateException(System.SR.net_ftp_protocolerror, WebExceptionStatus.ServerProtocolViolation, null);
                }
            }
            else
            {
                if (bytesRead <= 0)
                {
                    throw GenerateException(System.SR.net_ftp_protocolerror, WebExceptionStatus.ServerProtocolViolation, null);
                }
                char[] array = new char[_decoder.GetCharCount(state.Buffer, 0, bytesRead)];
                int chars = _decoder.GetChars(state.Buffer, 0, bytesRead, array, 0, flush: false);
                string text = new string(array, 0, chars);
                state.Resp.StatusBuffer.Append(text);
                if (!CheckValid(state.Resp, ref validThrough, ref completeLength))
                {
                    throw GenerateException(System.SR.net_ftp_protocolerror, WebExceptionStatus.ServerProtocolViolation, null);
                }
                if (completeLength >= 0)
                {
                    int num = state.Resp.StatusBuffer.Length - completeLength;
                    if (num > 0)
                    {
                        _buffer = text.Substring(text.Length - num, num);
                    }
                }
            }
            if (completeLength >= 0)
            {
                break;
            }
            state.ValidThrough = validThrough;
            try
            {
                if (_isAsync)
                {
                    BeginRead(state.Buffer, 0, state.Buffer.Length, s_readCallbackDelegate, state);
                    return;
                }
                bytesRead = Read(state.Buffer, 0, state.Buffer.Length);
                if (bytesRead == 0)
                {
                    CloseSocket();
                }
            }
            catch (IOException)
            {
                MarkAsRecoverableFailure();
                throw;
            }
            catch
            {
                throw;
            }
        }
        string text2 = state.Resp.StatusBuffer.ToString();
        state.Resp.StatusDescription = text2.Substring(0, completeLength);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"Received response: {text2.Substring(0, completeLength - 2)}", "ReceiveCommandResponseCallback");
        }
        if (_isAsync)
        {
            if (state.Resp != null)
            {
                _currentResponseDescription = state.Resp;
            }
            Stream stream = null;
            if (!PostReadCommandProcessing(ref stream))
            {
                ContinueCommandPipeline();
            }
        }
    }
References System.Net.CommandStream._buffer, System.Net.CommandStream._currentResponseDescription, System.Net.CommandStream._decoder, System.Net.CommandStream._isAsync, System.array, System.Net.NetworkStreamWrapper.BeginRead(), System.chars, System.Net.CommandStream.CheckValid(), System.Net.NetworkStreamWrapper.CloseSocket(), System.Net.CommandStream.ContinueCommandPipeline(), System.Net.CommandStream.GenerateException(), System.Text.Decoder.GetCharCount(), System.Text.Decoder.GetChars(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.CommandStream.MarkAsRecoverableFailure(), System.SR.net_ftp_protocolerror, System.Net.CommandStream.PostReadCommandProcessing(), System.IO.Read, System.Net.CommandStream.s_readCallbackDelegate, System.state, System.stream, and System.text.
Referenced by System.Net.CommandStream.ReadCallback(), and System.Net.CommandStream.ReceiveCommandResponse().