Terraria: System.Net.CommandStream.SubmitRequest
SubmitRequest()
Stream System.Net.CommandStream.SubmitRequest (WebRequest request, bool isAsync, bool readInitalResponseOnConnect) inline package inherited
Definition at line 159 of file CommandStream.cs.
    {
        ClearState();
        PipelineEntry[] commands = BuildCommandsList(request);
        InitCommandPipeline(request, commands, isAsync);
        if (readInitalResponseOnConnect)
        {
            _doSend = false;
            _index = -1;
        }
        return ContinueCommandPipeline();
    }
References System.Net.CommandStream._doSend, System.Net.CommandStream._index, System.Net.CommandStream.BuildCommandsList(), System.Net.CommandStream.ClearState(), System.Net.CommandStream.ContinueCommandPipeline(), and System.Net.CommandStream.InitCommandPipeline().
Referenced by System.Net.FtpWebRequest.TimedSubmitRequestHelper().