Terraria: System.Net.CommandStream.Abort
Abort()
virtual void System.Net.CommandStream.Abort (Exception e) inline package virtual inherited
Definition at line 101 of file CommandStream.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, "closing control Stream", "Abort");
        }
        lock (this)
        {
            if (_aborted)
            {
                return;
            }
            _aborted = true;
        }
        try
        {
            Close(0);
        }
        finally
        {
            if (e != null)
            {
                InvokeRequestCallback(e);
            }
            else
            {
                InvokeRequestCallback(null);
            }
        }
    }
References System.Net.CommandStream._aborted, System.IO.Stream.Close(), System.Net.NetEventSource.Info(), System.Net.CommandStream.InvokeRequestCallback(), and System.Net.NetEventSource.Log.
Referenced by System.Net.FtpWebRequest.Abort(), System.Net.FtpWebRequest.DataStreamClosed(), System.Net.FtpWebRequest.FinishRequestStage(), System.Net.CommandStream.ReadCallback(), and System.Net.CommandStream.WriteCallback().