Terraria: System.Net.CommandStream.PostSendCommandProcessing
PostSendCommandProcessing()
bool System.Net.CommandStream.PostSendCommandProcessing (ref Stream stream) inline private inherited
Definition at line 288 of file CommandStream.cs.
    {
        if (_doRead)
        {
            bool isAsync = _isAsync;
            int index = _index;
            PipelineEntry[] commands = _commands;
            try
            {
                ResponseDescription currentResponseDescription = ReceiveCommandResponse();
                if (isAsync)
                {
                    return true;
                }
                _currentResponseDescription = currentResponseDescription;
            }
            catch
            {
                if (index < 0 || index >= commands.Length || commands[index].Command != "QUIT\r\n")
                {
                    throw;
                }
            }
        }
        return PostReadCommandProcessing(ref stream);
    }
References System.Net.CommandStream._commands, System.Net.CommandStream._currentResponseDescription, System.Net.CommandStream._doRead, System.Net.CommandStream._index, System.Net.CommandStream._isAsync, System.Net.CommandStream.PipelineEntry.Command, System.index, System.Net.CommandStream.PostReadCommandProcessing(), System.Net.CommandStream.ReceiveCommandResponse(), and System.stream.
Referenced by System.Net.CommandStream.ContinueCommandPipeline(), and System.Net.CommandStream.WriteCallback().