Terraria: System.Net.CommandStream.ContinueCommandPipeline
ContinueCommandPipeline()
Stream System.Net.CommandStream.ContinueCommandPipeline () inline protected inherited
Definition at line 222 of file CommandStream.cs.
    {
        bool isAsync = _isAsync;
        while (_index < _commands.Length)
        {
            if (_doSend)
            {
                if (_index < 0)
                {
                    throw new System.Net.InternalException();
                }
                byte[] bytes = Encoding.GetBytes(_commands[_index].Command);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    string text = _commands[_index].Command.Substring(0, _commands[_index].Command.Length - 2);
                    if (_commands[_index].HasFlag(PipelineEntryFlags.DontLogParameter))
                    {
                        int num = text.IndexOf(' ');
                        if (num != -1)
{
                            text = string.Concat(text.AsSpan(0, num), " ********");
                        }
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"Sending command {text}", "ContinueCommandPipeline");
                    }
                }
                try
                {
                    if (isAsync)
                    {
                        BeginWrite(bytes, 0, bytes.Length, s_writeCallbackDelegate, this);
                    }
                    else
                    {
                        Write(bytes, 0, bytes.Length);
                    }
                }
                catch (IOException)
                {
                    MarkAsRecoverableFailure();
                    throw;
                }
                catch
                {
                    throw;
                }
                if (isAsync)
                {
                    return null;
                }
            }
            Stream stream = null;
            if (PostSendCommandProcessing(ref stream))
            {
                return stream;
            }
        }
        lock (this)
        {
            Close();
        }
        return null;
    }
References System.Net.CommandStream._commands, System.Net.CommandStream._doSend, System.Net.CommandStream._index, System.Net.CommandStream._isAsync, System.Net.NetworkStreamWrapper.BeginWrite(), System.bytes, System.IO.Stream.Close(), System.Net.CommandStream.PipelineEntry.Command, System.Text.Encoding.GetBytes(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.CommandStream.MarkAsRecoverableFailure(), System.Net.CommandStream.PostSendCommandProcessing(), System.Net.CommandStream.s_writeCallbackDelegate, System.stream, System.text, and System.IO.Write.
Referenced by System.Net.CommandStream.CheckContinuePipeline(), System.Net.FtpControlStream.PipelineCallback(), System.Net.CommandStream.PostReadCommandProcessing(), System.Net.CommandStream.ReceiveCommandResponseCallback(), System.Net.CommandStream.SubmitRequest(), and System.Net.CommandStream.WriteCallback().