Terraria: System.Net.CommandStream.ReadCallback
ReadCallback()
static void System.Net.CommandStream.ReadCallback (IAsyncResult asyncResult) inline static private inherited
Definition at line 362 of file CommandStream.cs.
    {
        ReceiveState receiveState = (ReceiveState)asyncResult.AsyncState;
        try
        {
            Stream connection = receiveState.Connection;
            int num = 0;
            try
            {
                num = connection.EndRead(asyncResult);
                if (num == 0)
                {
                    receiveState.Connection.CloseSocket();
                }
            }
            catch (IOException)
            {
                receiveState.Connection.MarkAsRecoverableFailure();
                throw;
            }
            catch
            {
                throw;
            }
            receiveState.Connection.ReceiveCommandResponseCallback(receiveState, num);
        }
        catch (Exception e)
        {
            receiveState.Connection.Abort(e);
        }
    }
References System.Net.CommandStream.Abort(), System.asyncResult, System.Net.NetworkStreamWrapper.CloseSocket(), System.Net.ReceiveState.Connection, System.IO.Stream.EndRead(), System.Net.CommandStream.MarkAsRecoverableFailure(), and System.Net.CommandStream.ReceiveCommandResponseCallback().