Terraria: System.Net.CommandStream.PostReadCommandProcessing
PostReadCommandProcessing()
bool System.Net.CommandStream.PostReadCommandProcessing (ref Stream stream) inline private inherited
Definition at line 315 of file CommandStream.cs.
    {
        if (_index >= _commands.Length)
        {
            return false;
        }
        _doSend = false;
        _doRead = false;
        PipelineEntry pipelineEntry = ((_index != -1) ? _commands[_index] : null);
        switch ((_currentResponseDescription == null && pipelineEntry.Command == "QUIT\r\n") ? PipelineInstruction.Advance : PipelineCallback(pipelineEntry, _currentResponseDescription, timeout: false, ref stream))
        {
        case PipelineInstruction.Abort:
        {
            Exception ex = ((!(_abortReason != string.Empty)) ? GenerateException(System.SR.net_ftp_protocolerror, WebExceptionStatus.ServerProtocolViolation, null) : new WebException(_abortReason));
            Abort(ex);
            throw ex;
        }
        case PipelineInstruction.Advance:
            _currentResponseDescription = null;
            _doSend = true;
            _doRead = true;
            _index++;
            break;
        case PipelineInstruction.Pause:
            return true;
        case PipelineInstruction.GiveStream:
            _currentResponseDescription = null;
            _doRead = true;
            if (_isAsync)
            {
                ContinueCommandPipeline();
                InvokeRequestCallback(stream);
            }
            return true;
        case PipelineInstruction.Reread:
            _currentResponseDescription = null;
            _doRead = true;
            break;
        }
        return false;
    }
References System.Net.CommandStream._abortReason, System.Net.CommandStream._commands, System.Net.CommandStream._currentResponseDescription, System.Net.CommandStream._doRead, System.Net.CommandStream._doSend, System.Net.CommandStream._index, System.Net.CommandStream._isAsync, System.Net.CommandStream.Abort, System.Net.CommandStream.PipelineEntry.Command, System.Net.CommandStream.ContinueCommandPipeline(), System.Net.CommandStream.GenerateException(), System.Net.CommandStream.InvokeRequestCallback(), System.SR.net_ftp_protocolerror, System.Net.CommandStream.PipelineCallback(), System.stream, and System.timeout.
Referenced by System.Net.CommandStream.PostSendCommandProcessing(), and System.Net.CommandStream.ReceiveCommandResponseCallback().