Terraria: Terraria.GameContent.TilePaintSystemV2.TreeFoliageVariantKey.Equals
Equals() [2/2]
bool Terraria.GameContent.TilePaintSystemV2.TreeFoliageVariantKey.Equals (TreeFoliageVariantKey other) inline
Definition at line 236 of file TilePaintSystemV2.cs.
        {
            if (TextureIndex == other.TextureIndex && TextureStyle == other.TextureStyle)
            {
                return PaintColor == other.PaintColor;
            }
            return false;
        }
References System.other, Terraria.GameContent.TilePaintSystemV2.TreeFoliageVariantKey.PaintColor, Terraria.GameContent.TilePaintSystemV2.TreeFoliageVariantKey.TextureIndex, and Terraria.GameContent.TilePaintSystemV2.TreeFoliageVariantKey.TextureStyle.
Referenced by Terraria.GameContent.TilePaintSystemV2.TreeFoliageVariantKey.Equals(), Terraria.GameContent.TilePaintSystemV2.TreeFoliageVariantKey.operator!=(), and Terraria.GameContent.TilePaintSystemV2.TreeFoliageVariantKey.operator==().