Terraria: System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetStringCore
TryReadPrimitiveOctetStringCore()
static bool System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetStringCore (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber universalTagNumber, out int? contentLength, out int headerLength, out ReadOnlySpan< byte > contents, out int bytesConsumed) inline static private
Definition at line 1234 of file AsnDecoder.cs.
    {
        Asn1Tag tag = ReadTagAndLength(source, ruleSet, out contentLength, out headerLength);
        CheckExpectedTag(tag, expectedTag, universalTagNumber);
        ReadOnlySpan<byte> readOnlySpan = Slice(source, headerLength, contentLength);
        if (tag.IsConstructed)
        {
            if (ruleSet == AsnEncodingRules.DER)
            {
                throw new AsnContentException(System.SR.ContentException_InvalidUnderDer_TryBerOrCer);
            }
            contents = default(ReadOnlySpan<byte>);
            bytesConsumed = 0;
            return false;
        }
        if (ruleSet == AsnEncodingRules.CER && readOnlySpan.Length > 1000)
        {
            throw new AsnContentException(System.SR.ContentException_InvalidUnderCer_TryBerOrDer);
        }
        contents = readOnlySpan;
        bytesConsumed = headerLength + readOnlySpan.Length;
        return true;
    }
References System.Formats.Asn1.AsnDecoder.CheckExpectedTag(), System.SR.ContentException_InvalidUnderCer_TryBerOrDer, System.SR.ContentException_InvalidUnderDer_TryBerOrCer, System.Formats.Asn1.Asn1Tag.IsConstructed, System.Formats.Asn1.AsnDecoder.ReadTagAndLength(), System.Formats.Asn1.AsnDecoder.Slice(), and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.GetOctetStringContents(), System.Formats.Asn1.AsnDecoder.TryReadCharacterStringBytesCore(), System.Formats.Asn1.AsnDecoder.TryReadOctetString(), System.Formats.Asn1.AsnDecoder.TryReadPrimitiveCharacterStringBytes(), and System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetString().