Terraria: System.Formats.Asn1.AsnDecoder.ProcessConstructedBitString
ProcessConstructedBitString()
static int System.Formats.Asn1.AsnDecoder.ProcessConstructedBitString (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Span< byte > destination, BitStringCopyAction copyAction, bool isIndefinite, out int lastUnusedBitCount, out int bytesRead) inline static private
Definition at line 518 of file AsnDecoder.cs.
    {
        lastUnusedBitCount = 0;
        bytesRead = 0;
        int num = 1000;
        ReadOnlySpan<byte> readOnlySpan = source;
        Stack<(int, int, bool, int)> stack = null;
        int num2 = 0;
        Asn1Tag asn1Tag = Asn1Tag.ConstructedBitString;
        Span<byte> destination2 = destination;
        while (true)
        {
            if (!readOnlySpan.IsEmpty)
            {
                asn1Tag = ReadTagAndLength(readOnlySpan, ruleSet, out var contentsLength, out var bytesRead2);
                if (asn1Tag == Asn1Tag.PrimitiveBitString)
                {
                    if (lastUnusedBitCount != 0)
                    {
                        throw new AsnContentException();
                    }
                    if (ruleSet == AsnEncodingRules.CER && num != 1000)
                    {
                        throw new AsnContentException(System.SR.ContentException_InvalidUnderCer_TryBerOrDer);
                    }
                    ReadOnlySpan<byte> source2 = Slice(readOnlySpan, bytesRead2, contentsLength.Value);
                    ParsePrimitiveBitStringContents(source2, ruleSet, out lastUnusedBitCount, out var value, out var normalizedLastByte);
                    int num3 = bytesRead2 + source2.Length;
                    readOnlySpan = readOnlySpan.Slice(num3);
                    bytesRead += num3;
                    num2 += value.Length;
                    num = source2.Length;
                    if (copyAction != null)
                    {
                        copyAction(value, normalizedLastByte, destination2);
                        destination2 = destination2.Slice(value.Length);
                    }
                    continue;
                }
                if (!(asn1Tag == Asn1Tag.EndOfContents && isIndefinite))
                {
                    if (asn1Tag == Asn1Tag.ConstructedBitString)
                    {
                        if (ruleSet == AsnEncodingRules.CER)
{
                            throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
                        }
                        if (stack == null)
{
                            stack = new Stack<(int, int, bool, int)>();
                        }
                        if (!source.Overlaps(readOnlySpan, out var elementOffset))
{
                            throw new AsnContentException();
                        }
                        stack.Push((elementOffset, readOnlySpan.Length, isIndefinite, bytesRead));
                        readOnlySpan = Slice(readOnlySpan, bytesRead2, contentsLength);
                        bytesRead = bytesRead2;
                        isIndefinite = !contentsLength.HasValue;
                        continue;
                    }
                    throw new AsnContentException();
                }
                ValidateEndOfContents(asn1Tag, contentsLength, bytesRead2);
                bytesRead += bytesRead2;
                if (stack != null && stack.Count > 0)
                {
                    (int, int, bool, int) tuple = stack.Pop();
                    int item = tuple.Item1;
                    int item2 = tuple.Item2;
                    bool item3 = tuple.Item3;
                    int item4 = tuple.Item4;
                    readOnlySpan = source.Slice(item, item2).Slice(bytesRead);
                    bytesRead += item4;
                    isIndefinite = item3;
                    continue;
                }
            }
            if (isIndefinite && asn1Tag != Asn1Tag.EndOfContents)
            {
                throw new AsnContentException();
            }
            if (stack == null || stack.Count <= 0)
            {
                break;
            }
            (int, int, bool, int) tuple2 = stack.Pop();
            int item5 = tuple2.Item1;
            int item6 = tuple2.Item2;
            bool item7 = tuple2.Item3;
            int item8 = tuple2.Item4;
            readOnlySpan = source.Slice(item5, item6).Slice(bytesRead);
            isIndefinite = item7;
            bytesRead += item8;
        }
        return num2;
    }
References System.Formats.Asn1.Asn1Tag.ConstructedBitString, System.SR.ContentException_InvalidUnderCer_TryBerOrDer, System.SR.ContentException_InvalidUnderCerOrDer_TryBer, System.destination, System.Formats.Asn1.Asn1Tag.EndOfContents, System.item, System.Formats.Asn1.AsnDecoder.ParsePrimitiveBitStringContents(), System.Formats.Asn1.Asn1Tag.PrimitiveBitString, System.Formats.Asn1.AsnDecoder.ReadTagAndLength(), System.Formats.Asn1.AsnDecoder.Slice(), System.source, System.Formats.Asn1.AsnDecoder.ValidateEndOfContents(), and System.value.
Referenced by System.Formats.Asn1.AsnDecoder.CopyConstructedBitString(), and System.Formats.Asn1.AsnDecoder.CountConstructedBitString().