Terraria: System.Formats.Asn1.AsnDecoder.ValidateLength
ValidateLength()
static LengthValidity System.Formats.Asn1.AsnDecoder.ValidateLength (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Asn1Tag localTag, int? encodedLength, out int actualLength, out int bytesConsumed) inline static private
Definition at line 229 of file AsnDecoder.cs.
    {
        if (localTag.IsConstructed)
        {
            if (ruleSet == AsnEncodingRules.CER && encodedLength.HasValue)
            {
                actualLength = (bytesConsumed = 0);
                return LengthValidity.CerRequiresIndefinite;
            }
        }
        else if (!encodedLength.HasValue)
        {
            actualLength = (bytesConsumed = 0);
            return LengthValidity.PrimitiveEncodingRequiresDefinite;
        }
        if (encodedLength.HasValue)
        {
            int value = encodedLength.Value;
            int num = value;
            if (num > source.Length)
            {
                actualLength = (bytesConsumed = 0);
                return LengthValidity.LengthExceedsInput;
            }
            actualLength = value;
            bytesConsumed = value;
            return LengthValidity.Valid;
        }
        actualLength = SeekEndOfContents(source, ruleSet);
        bytesConsumed = actualLength + 2;
        return LengthValidity.Valid;
    }
References System.Formats.Asn1.AsnDecoder.SeekEndOfContents(), System.source, and System.value.
Referenced by System.Formats.Asn1.AsnDecoder.ReadEncodedValue(), and System.Formats.Asn1.AsnDecoder.TryReadEncodedValue().