Terraria: System.Formats.Asn1.AsnDecoder.TryReadCharacterStringCore
TryReadCharacterStringCore() [2/2]
static unsafe bool System.Formats.Asn1.AsnDecoder.TryReadCharacterStringCore (ReadOnlySpan< byte > source, Span< char > destination, Encoding encoding, out int charsWritten) inline static private
Definition at line 1691 of file AsnDecoder.cs.
    {
        if (source.Length == 0)
        {
            charsWritten = 0;
            return true;
        }
        fixed (byte* bytes = &MemoryMarshal.GetReference(source))
        {
            fixed (char* chars = &MemoryMarshal.GetReference(destination))
            {
                try
                {
                    int charCount = encoding.GetCharCount(bytes, source.Length);
                    if (charCount > destination.Length)
                    {
                        charsWritten = 0;
                        return false;
                    }
                    charsWritten = encoding.GetChars(bytes, source.Length, chars, destination.Length);
                }
                catch (DecoderFallbackException inner)
                {
                    throw new AsnContentException(System.SR.ContentException_DefaultMessage, inner);
                }
                return true;
            }
        }
    }
References System.bytes, System.charCount, System.chars, System.SR.ContentException_DefaultMessage, System.destination, System.Text.Encoding.GetCharCount(), System.Text.Encoding.GetChars(), and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.TryReadCharacterString(), and System.Formats.Asn1.AsnDecoder.TryReadCharacterStringCore().