Terraria: System.Formats.Asn1.AsnDecoder.ReadBitString
ReadBitString()
static byte[] System.Formats.Asn1.AsnDecoder.ReadBitString (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int unusedBitCount, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 431 of file AsnDecoder.cs.
    {
        if (TryReadPrimitiveBitStringCore(source, ruleSet, expectedTag ?? Asn1Tag.PrimitiveBitString, out var contentsLength, out var headerLength, out var unusedBitCount2, out var value, out var bytesConsumed2, out var normalizedLastByte))
        {
            byte[] array = value.ToArray();
            if (value.Length > 0)
            {
                array[^1] = normalizedLastByte;
            }
            unusedBitCount = unusedBitCount2;
            bytesConsumed = bytesConsumed2;
            return array;
        }
        int minimumLength = contentsLength ?? SeekEndOfContents(source.Slice(headerLength), ruleSet);
        byte[] array2 = System.Security.Cryptography.CryptoPool.Rent(minimumLength);
        if (TryCopyConstructedBitStringValue(Slice(source, headerLength, contentsLength), ruleSet, array2, !contentsLength.HasValue, out unusedBitCount2, out var bytesRead, out var bytesWritten))
        {
            byte[] result = array2.AsSpan(0, bytesWritten).ToArray();
            System.Security.Cryptography.CryptoPool.Return(array2, bytesWritten);
            unusedBitCount = unusedBitCount2;
            bytesConsumed = headerLength + bytesRead;
            return result;
        }
        throw new AsnContentException();
    }
References System.array, System.Formats.Asn1.Asn1Tag.PrimitiveBitString, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Formats.Asn1.AsnDecoder.SeekEndOfContents(), System.Formats.Asn1.AsnDecoder.Slice(), System.source, System.Formats.Asn1.AsnDecoder.TryCopyConstructedBitStringValue(), System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitStringCore(), and System.value.
Referenced by System.Formats.Asn1.AsnReader.ReadBitString(), and System.Formats.Asn1.AsnValueReader.ReadBitString().