Terraria: System.Formats.Asn1.AsnDecoder.CountConstructedOctetString
CountConstructedOctetString()
static int System.Formats.Asn1.AsnDecoder.CountConstructedOctetString (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, bool isIndefinite) inline static private
Definition at line 1265 of file AsnDecoder.cs.
    {
        int bytesRead;
        int num = CopyConstructedOctetString(source, ruleSet, Span<byte>.Empty, write: false, isIndefinite, out bytesRead);
        if (ruleSet == AsnEncodingRules.CER && num <= 1000)
        {
            throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
        }
        return num;
    }
References System.SR.ContentException_InvalidUnderCerOrDer_TryBer, System.Formats.Asn1.AsnDecoder.CopyConstructedOctetString(), and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.GetOctetStringContents(), and System.Formats.Asn1.AsnDecoder.TryCopyConstructedOctetStringContents().