Terraria: System.Formats.Asn1.AsnDecoder.ReadTagAndLength
ReadTagAndLength()
static Asn1Tag System.Formats.Asn1.AsnDecoder.ReadTagAndLength (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int? contentsLength, out int bytesRead) inline static private
Definition at line 198 of file AsnDecoder.cs.
    {
        int bytesConsumed;
        Asn1Tag result = Asn1Tag.Decode(source, out bytesConsumed);
        int bytesConsumed2;
        int? num = ReadLength(source.Slice(bytesConsumed), ruleSet, out bytesConsumed2);
        int num2 = bytesConsumed + bytesConsumed2;
        if (result.IsConstructed)
        {
            if (ruleSet == AsnEncodingRules.CER && num.HasValue)
            {
                throw GetValidityException(LengthValidity.CerRequiresIndefinite);
            }
        }
        else if (!num.HasValue)
        {
            throw GetValidityException(LengthValidity.PrimitiveEncodingRequiresDefinite);
        }
        bytesRead = num2;
        contentsLength = num;
        return result;
    }
References System.Formats.Asn1.Asn1Tag.Decode(), System.Formats.Asn1.AsnDecoder.GetValidityException(), System.Formats.Asn1.Asn1Tag.IsConstructed, System.Formats.Asn1.AsnDecoder.ReadLength(), and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.CopyConstructedOctetString(), System.Formats.Asn1.AsnDecoder.ProcessConstructedBitString(), System.Formats.Asn1.AsnDecoder.ReadSequence(), System.Formats.Asn1.AsnDecoder.ReadSetOf(), System.Formats.Asn1.AsnDecoder.SeekEndOfContents(), System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitStringCore(), and System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetStringCore().