Terraria: System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan
GetPrimitiveContentSpan()
static ReadOnlySpan< byte > System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber tagNumber, out int bytesConsumed) inline static private
Definition at line 78 of file AsnDecoder.cs.
    {
        CheckEncodingRules(ruleSet);
        int bytesConsumed2;
        Asn1Tag tag = Asn1Tag.Decode(source, out bytesConsumed2);
        int bytesConsumed3;
        int? num = ReadLength(source.Slice(bytesConsumed2), ruleSet, out bytesConsumed3);
        int num2 = bytesConsumed2 + bytesConsumed3;
        CheckExpectedTag(tag, expectedTag, tagNumber);
        if (tag.IsConstructed)
        {
            throw new AsnContentException(System.SR.Format(System.SR.ContentException_PrimitiveEncodingRequired, tagNumber));
        }
        if (!num.HasValue)
        {
            throw new AsnContentException();
        }
        ReadOnlySpan<byte> result = Slice(source, num2, num.Value);
        bytesConsumed = num2 + result.Length;
        return result;
    }
References System.Formats.Asn1.AsnDecoder.CheckEncodingRules(), System.Formats.Asn1.AsnDecoder.CheckExpectedTag(), System.SR.ContentException_PrimitiveEncodingRequired, System.Formats.Asn1.Asn1Tag.Decode(), System.SR.Format(), System.Formats.Asn1.Asn1Tag.IsConstructed, System.Formats.Asn1.AsnDecoder.ReadLength(), System.Formats.Asn1.AsnDecoder.Slice(), and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.GetIntegerContents(), System.Formats.Asn1.AsnDecoder.ReadBoolean(), System.Formats.Asn1.AsnDecoder.ReadNull(), and System.Formats.Asn1.AsnDecoder.ReadObjectIdentifier().