Terraria: System.Formats.Asn1.AsnDecoder.ReadCharacterStringCore
ReadCharacterStringCore()
static unsafe string System.Formats.Asn1.AsnDecoder.ReadCharacterStringCore (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber universalTagNumber, Encoding encoding, out int bytesConsumed) inline static private
Definition at line 1721 of file AsnDecoder.cs.
    {
        byte[] rented = null;
        int bytesConsumed2;
        ReadOnlySpan<byte> octetStringContents = GetOctetStringContents(source, ruleSet, expectedTag, universalTagNumber, out bytesConsumed2, ref rented);
        string result;
        if (octetStringContents.Length == 0)
        {
            result = string.Empty;
        }
        else
        {
            fixed (byte* bytes = &MemoryMarshal.GetReference(octetStringContents))
            {
                try
                {
                    result = encoding.GetString(bytes, octetStringContents.Length);
                }
                catch (DecoderFallbackException inner)
                {
                    throw new AsnContentException(System.SR.ContentException_DefaultMessage, inner);
                }
            }
        }
        if (rented != null)
        {
            System.Security.Cryptography.CryptoPool.Return(rented, octetStringContents.Length);
        }
        bytesConsumed = bytesConsumed2;
        return result;
    }
References System.bytes, System.SR.ContentException_DefaultMessage, System.Formats.Asn1.AsnDecoder.GetOctetStringContents(), System.Text.Encoding.GetString(), System.Security.Cryptography.CryptoPool.Return(), and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.ReadCharacterString().