Terraria: System.Formats.Asn1.AsnDecoder.ReadSetOf
ReadSetOf()
static void System.Formats.Asn1.AsnDecoder.ReadSetOf (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int contentOffset, out int contentLength, out int bytesConsumed, bool skipSortOrderValidation = false, Asn1Tag? expectedTag = null) inline static
Definition at line 1573 of file AsnDecoder.cs.
    {
        int? contentsLength;
        int bytesRead;
        Asn1Tag tag = ReadTagAndLength(source, ruleSet, out contentsLength, out bytesRead);
        CheckExpectedTag(tag, expectedTag ?? Asn1Tag.SetOf, UniversalTagNumber.Set);
        if (!tag.IsConstructed)
        {
            throw new AsnContentException(System.SR.Format(System.SR.ContentException_ConstructedEncodingRequired, UniversalTagNumber.Set));
        }
        int num;
        ReadOnlySpan<byte> readOnlySpan;
        if (contentsLength.HasValue)
        {
            num = 0;
            readOnlySpan = Slice(source, bytesRead, contentsLength.Value);
        }
        else
        {
            int length = SeekEndOfContents(source.Slice(bytesRead), ruleSet);
            readOnlySpan = Slice(source, bytesRead, length);
            num = 2;
        }
        if (!skipSortOrderValidation && (ruleSet == AsnEncodingRules.DER || ruleSet == AsnEncodingRules.CER))
        {
            ReadOnlySpan<byte> source2 = readOnlySpan;
            ReadOnlySpan<byte> y = default(ReadOnlySpan<byte>);
            while (!source2.IsEmpty)
            {
                ReadEncodedValue(source2, ruleSet, out var _, out var _, out var bytesConsumed2);
                ReadOnlySpan<byte> readOnlySpan2 = source2.Slice(0, bytesConsumed2);
                source2 = source2.Slice(bytesConsumed2);
                if (SetOfValueComparer.Compare(readOnlySpan2, y) < 0)
                {
                    throw new AsnContentException(System.SR.ContentException_SetOfNotSorted);
                }
                y = readOnlySpan2;
            }
        }
        contentOffset = bytesRead;
        contentLength = readOnlySpan.Length;
        bytesConsumed = bytesRead + readOnlySpan.Length + num;
    }
References System.Formats.Asn1.AsnDecoder.CheckExpectedTag(), System.Formats.Asn1.SetOfValueComparer.Compare(), System.SR.ContentException_ConstructedEncodingRequired, System.SR.ContentException_SetOfNotSorted, System.SR.Format(), System.Formats.Asn1.Asn1Tag.IsConstructed, System.length, System.Formats.Asn1.AsnDecoder.ReadEncodedValue(), System.Formats.Asn1.AsnDecoder.ReadTagAndLength(), System.Formats.Asn1.AsnDecoder.SeekEndOfContents(), System.Formats.Asn1.Asn1Tag.SetOf, System.Formats.Asn1.AsnDecoder.Slice(), and System.source.
Referenced by System.Formats.Asn1.AsnValueReader.ReadSetOf(), and System.Formats.Asn1.AsnReader.ReadSetOf().