Terraria: System.Formats.Asn1.AsnDecoder.ReadIntegerBytes
ReadIntegerBytes()
static ReadOnlySpan< byte > System.Formats.Asn1.AsnDecoder.ReadIntegerBytes (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 936 of file AsnDecoder.cs.
    {
        return GetIntegerContents(source, ruleSet, expectedTag ?? Asn1Tag.Integer, UniversalTagNumber.Integer, out bytesConsumed);
    }
References System.Formats.Asn1.AsnDecoder.GetIntegerContents(), System.Formats.Asn1.Asn1Tag.Integer, and System.source.
Referenced by System.Security.Cryptography.DSAKeyFormatHelper.ReadDsaPrivateKey(), System.Formats.Asn1.AsnDecoder.ReadInteger(), System.Formats.Asn1.AsnReader.ReadIntegerBytes(), and System.Formats.Asn1.AsnValueReader.ReadIntegerBytes().