Terraria: System.Formats.Asn1.AsnDecoder.Slice
Slice() [2/3]
static ReadOnlySpan< byte > System.Formats.Asn1.AsnDecoder.Slice (ReadOnlySpan< byte > source, int offset, int length) inline static private
Definition at line 328 of file AsnDecoder.cs.
    {
        if (length < 0 || source.Length - offset < length)
        {
            throw new AsnContentException(System.SR.ContentException_LengthExceedsPayload);
        }
        return source.Slice(offset, length);
    }
References System.SR.ContentException_LengthExceedsPayload, System.length, System.offset, and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.CopyConstructedOctetString(), System.Formats.Asn1.AsnDecoder.GetOctetStringContents(), System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan(), System.Formats.Asn1.AsnDecoder.ParseNonNegativeIntAndSlice(), System.Formats.Asn1.AsnDecoder.ProcessConstructedBitString(), System.Formats.Asn1.AsnDecoder.ReadBitString(), System.Formats.Asn1.AsnReader.ReadEnumeratedBytes(), System.Formats.Asn1.AsnReader.ReadIntegerBytes(), System.Formats.Asn1.AsnDecoder.ReadSetOf(), System.Formats.Asn1.AsnDecoder.SeekEndOfContents(), System.Formats.Asn1.AsnDecoder.TryReadBitString(), System.Formats.Asn1.AsnDecoder.TryReadCharacterStringBytesCore(), System.Formats.Asn1.AsnDecoder.TryReadOctetString(), System.Formats.Asn1.AsnReader.TryReadPrimitiveBitString(), System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitStringCore(), System.Formats.Asn1.AsnReader.TryReadPrimitiveCharacterStringBytes(), System.Formats.Asn1.AsnReader.TryReadPrimitiveOctetString(), and System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetStringCore().