Terraria: System.Formats.Asn1.AsnDecoder.TryCopyConstructedBitStringValue
TryCopyConstructedBitStringValue()
static bool System.Formats.Asn1.AsnDecoder.TryCopyConstructedBitStringValue (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Span< byte > dest, bool isIndefinite, out int unusedBitCount, out int bytesRead, out int bytesWritten) inline static private
Definition at line 616 of file AsnDecoder.cs.
    {
        int num = CountConstructedBitString(source, ruleSet, isIndefinite);
        if (ruleSet == AsnEncodingRules.CER && num < 1000)
        {
            throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
        }
        if (dest.Length < num)
        {
            unusedBitCount = 0;
            bytesRead = 0;
            bytesWritten = 0;
            return false;
        }
        CopyConstructedBitString(source, ruleSet, dest, isIndefinite, out unusedBitCount, out bytesRead, out bytesWritten);
        return true;
    }
References System.SR.ContentException_InvalidUnderCerOrDer_TryBer, System.Formats.Asn1.AsnDecoder.CopyConstructedBitString(), System.Formats.Asn1.AsnDecoder.CountConstructedBitString(), and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.ReadBitString(), and System.Formats.Asn1.AsnDecoder.TryReadBitString().