Terraria: System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitString
TryReadPrimitiveBitString()
static bool System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitString (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int unusedBitCount, out ReadOnlySpan< byte > value, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 384 of file AsnDecoder.cs.
    {
        if (TryReadPrimitiveBitStringCore(source, ruleSet, expectedTag ?? Asn1Tag.PrimitiveBitString, out var _, out var _, out var unusedBitCount2, out var value2, out var bytesConsumed2, out var normalizedLastByte) && (value2.Length == 0 || normalizedLastByte == value2[value2.Length - 1]))
        {
            unusedBitCount = unusedBitCount2;
            value = value2;
            bytesConsumed = bytesConsumed2;
            return true;
        }
        unusedBitCount = 0;
        value = default(ReadOnlySpan<byte>);
        bytesConsumed = 0;
        return false;
    }
References System.Formats.Asn1.Asn1Tag.PrimitiveBitString, System.source, System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitStringCore(), and System.value.
Referenced by System.Formats.Asn1.AsnReader.TryReadPrimitiveBitString(), and System.Formats.Asn1.AsnValueReader.TryReadPrimitiveBitString().