Terraria: System.Formats.Asn1.AsnDecoder.TryReadEncodedValue
TryReadEncodedValue()
static bool System.Formats.Asn1.AsnDecoder.TryReadEncodedValue (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out Asn1Tag tag, out int contentOffset, out int contentLength, out int bytesConsumed) inline static
Definition at line 34 of file AsnDecoder.cs.
    {
        CheckEncodingRules(ruleSet);
        if (Asn1Tag.TryDecode(source, out var tag2, out var bytesConsumed2) && TryReadLength(source.Slice(bytesConsumed2), ruleSet, out var length, out var bytesRead))
        {
            int num = bytesConsumed2 + bytesRead;
            int actualLength;
            int bytesConsumed3;
            LengthValidity lengthValidity = ValidateLength(source.Slice(num), ruleSet, tag2, length, out actualLength, out bytesConsumed3);
            if (lengthValidity == LengthValidity.Valid)
            {
                tag = tag2;
                contentOffset = num;
                contentLength = actualLength;
                bytesConsumed = num + bytesConsumed3;
                return true;
            }
        }
        tag = default(Asn1Tag);
        contentOffset = (contentLength = (bytesConsumed = 0));
        return false;
    }
References System.Formats.Asn1.AsnDecoder.CheckEncodingRules(), System.length, System.source, System.Formats.Asn1.Asn1Tag.TryDecode(), System.Formats.Asn1.AsnDecoder.TryReadLength(), and System.Formats.Asn1.AsnDecoder.ValidateLength().
Referenced by System.Formats.Asn1.AsnWriter.WriteEncodedValue().