Terraria: System.Formats.Asn1.AsnDecoder.ReadSubIdentifier
ReadSubIdentifier()
static void System.Formats.Asn1.AsnDecoder.ReadSubIdentifier (ReadOnlySpan< byte > source, out int bytesRead, out long? smallValue, out BigInteger? largeValue) inline static private
Definition at line 1421 of file AsnDecoder.cs.
    {
        if (source[0] == 128)
        {
            throw new AsnContentException();
        }
        int num = -1;
        int i;
        for (i = 0; i < source.Length; i++)
        {
            if ((source[i] & 0x80) == 0)
            {
                num = i;
                break;
            }
        }
        if (num < 0)
        {
            throw new AsnContentException();
        }
        bytesRead = num + 1;
        long num2 = 0L;
        if (bytesRead <= 9)
        {
            for (i = 0; i < bytesRead; i++)
            {
                byte b = source[i];
                num2 <<= 7;
                num2 |= (byte)(b & 0x7F);
            }
            largeValue = null;
            smallValue = num2;
            return;
        }
        int num3 = (bytesRead / 8 + 1) * 7;
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(num3);
        Array.Clear(array, 0, array.Length);
        Span<byte> destination = array;
        Span<byte> destination2 = stackalloc byte[8];
        int num4 = bytesRead;
        i = bytesRead - 8;
        while (num4 > 0)
        {
            byte b2 = source[i];
            num2 <<= 7;
            num2 |= (byte)(b2 & 0x7F);
            i++;
            if (i >= num4)
            {
                BinaryPrimitives.WriteInt64LittleEndian(destination2, num2);
                destination2.Slice(0, 7).CopyTo(destination);
                destination = destination.Slice(7);
                num2 = 0L;
                num4 -= 8;
                i = Math.Max(0, num4 - 8);
            }
        }
        int num5 = array.Length - destination.Length;
        int num6 = num3 - num5;
        largeValue = new BigInteger(array);
        smallValue = null;
        System.Security.Cryptography.CryptoPool.Return(array, num5);
    }
References System.array, System.Array.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.destination, System.L, System.Math.Max(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.source, and System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian().
Referenced by System.Formats.Asn1.AsnDecoder.ReadObjectIdentifier().