Terraria: System.Formats.Asn1.AsnDecoder.GetValidityException
GetValidityException()
static AsnContentException System.Formats.Asn1.AsnDecoder.GetValidityException (LengthValidity validity) inline static private
Definition at line 262 of file AsnDecoder.cs.
    {
        return validity switch
        {
            LengthValidity.CerRequiresIndefinite => new AsnContentException(System.SR.ContentException_CerRequiresIndefiniteLength),
            LengthValidity.LengthExceedsInput => new AsnContentException(System.SR.ContentException_LengthExceedsPayload),
            _ => new AsnContentException(),
        };
    }
References System.SR.ContentException_CerRequiresIndefiniteLength, and System.SR.ContentException_LengthExceedsPayload.
Referenced by System.Formats.Asn1.AsnDecoder.ReadEncodedValue(), System.Formats.Asn1.AsnDecoder.ReadSequence(), and System.Formats.Asn1.AsnDecoder.ReadTagAndLength().