Terraria: System.Formats.Asn1.AsnDecoder.TryReadSignedInteger
TryReadSignedInteger()
static bool System.Formats.Asn1.AsnDecoder.TryReadSignedInteger (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, int sizeLimit, Asn1Tag expectedTag, UniversalTagNumber tagNumber, out long value, out int bytesConsumed) inline static private
Definition at line 1017 of file AsnDecoder.cs.
    {
        int bytesConsumed2;
        ReadOnlySpan<byte> integerContents = GetIntegerContents(source, ruleSet, expectedTag, tagNumber, out bytesConsumed2);
        if (integerContents.Length > sizeLimit)
        {
            value = 0L;
            bytesConsumed = 0;
            return false;
        }
        long num = (((integerContents[0] & 0x80u) != 0) ? (-1) : 0);
        for (int i = 0; i < integerContents.Length; i++)
        {
            num <<= 8;
            num |= integerContents[i];
        }
        bytesConsumed = bytesConsumed2;
        value = num;
        return true;
    }
References System.Formats.Asn1.AsnDecoder.GetIntegerContents(), System.L, System.source, and System.value.
Referenced by System.Formats.Asn1.AsnDecoder.ReadEnumeratedValue(), System.Formats.Asn1.AsnDecoder.TryReadInt32(), and System.Formats.Asn1.AsnDecoder.TryReadInt64().