Terraria: System.Formats.Asn1.AsnDecoder.TryReadOctetString
TryReadOctetString()
static bool System.Formats.Asn1.AsnDecoder.TryReadOctetString (ReadOnlySpan< byte > source, Span< byte > destination, AsnEncodingRules ruleSet, out int bytesConsumed, out int bytesWritten, Asn1Tag? expectedTag = null) inline static
Definition at line 1188 of file AsnDecoder.cs.
    {
        if (source.Overlaps(destination))
        {
            throw new ArgumentException(System.SR.Argument_SourceOverlapsDestination, "destination");
        }
        if (TryReadPrimitiveOctetStringCore(source, ruleSet, expectedTag ?? Asn1Tag.PrimitiveOctetString, UniversalTagNumber.OctetString, out var contentLength, out var headerLength, out var contents, out var bytesConsumed2))
        {
            if (contents.Length > destination.Length)
            {
                bytesWritten = 0;
                bytesConsumed = 0;
                return false;
            }
            contents.CopyTo(destination);
            bytesWritten = contents.Length;
            bytesConsumed = bytesConsumed2;
            return true;
        }
        int bytesRead;
        bool flag = TryCopyConstructedOctetStringContents(Slice(source, headerLength, contentLength), ruleSet, destination, !contentLength.HasValue, out bytesRead, out bytesWritten);
        if (flag)
        {
            bytesConsumed = headerLength + bytesRead;
        }
        else
        {
            bytesConsumed = 0;
        }
        return flag;
    }
References System.SR.Argument_SourceOverlapsDestination, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.destination, System.Formats.Asn1.Asn1Tag.PrimitiveOctetString, System.Formats.Asn1.AsnDecoder.Slice(), System.source, System.Formats.Asn1.AsnDecoder.TryCopyConstructedOctetStringContents(), and System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetStringCore().
Referenced by System.Security.Cryptography.PasswordBasedEncryption.ReadIvParameter(), and System.Formats.Asn1.AsnReader.TryReadOctetString().