Terraria: System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitStringCore
TryReadPrimitiveBitStringCore()
static bool System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitStringCore (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, out int? contentsLength, out int headerLength, out int unusedBitCount, out ReadOnlySpan< byte > value, out int bytesConsumed, out byte normalizedLastByte) inline static private
Definition at line 634 of file AsnDecoder.cs.
    {
        Asn1Tag tag = ReadTagAndLength(source, ruleSet, out contentsLength, out headerLength);
        CheckExpectedTag(tag, expectedTag, UniversalTagNumber.BitString);
        ReadOnlySpan<byte> source2 = Slice(source, headerLength, contentsLength);
        if (tag.IsConstructed)
        {
            if (ruleSet == AsnEncodingRules.DER)
            {
                throw new AsnContentException(System.SR.ContentException_InvalidUnderDer_TryBerOrCer);
            }
            unusedBitCount = 0;
            value = default(ReadOnlySpan<byte>);
            normalizedLastByte = 0;
            bytesConsumed = 0;
            return false;
        }
        ParsePrimitiveBitStringContents(source2, ruleSet, out unusedBitCount, out value, out normalizedLastByte);
        bytesConsumed = headerLength + source2.Length;
        return true;
    }
References System.Formats.Asn1.AsnDecoder.CheckExpectedTag(), System.SR.ContentException_InvalidUnderDer_TryBerOrCer, System.Formats.Asn1.Asn1Tag.IsConstructed, System.Formats.Asn1.AsnDecoder.ParsePrimitiveBitStringContents(), System.Formats.Asn1.AsnDecoder.ReadTagAndLength(), System.Formats.Asn1.AsnDecoder.Slice(), System.source, and System.value.
Referenced by System.Formats.Asn1.AsnDecoder.ReadBitString(), System.Formats.Asn1.AsnDecoder.TryReadBitString(), and System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitString().