Terraria: System.Formats.Asn1.AsnDecoder.TryReadCharacterStringBytes
TryReadCharacterStringBytes()
static bool System.Formats.Asn1.AsnDecoder.TryReadCharacterStringBytes (ReadOnlySpan< byte > source, Span< byte > destination, AsnEncodingRules ruleSet, Asn1Tag expectedTag, out int bytesConsumed, out int bytesWritten) inline static
Definition at line 1633 of file AsnDecoder.cs.
    {
        if (source.Overlaps(destination))
        {
            throw new ArgumentException(System.SR.Argument_SourceOverlapsDestination, "destination");
        }
        UniversalTagNumber universalTagNumber = UniversalTagNumber.IA5String;
        if (expectedTag.TagClass == TagClass.Universal)
        {
            universalTagNumber = (UniversalTagNumber)expectedTag.TagValue;
            if (!IsCharacterStringEncodingType(universalTagNumber))
            {
                throw new ArgumentException(System.SR.Argument_Tag_NotCharacterString, "expectedTag");
            }
        }
        return TryReadCharacterStringBytesCore(source, ruleSet, expectedTag, universalTagNumber, destination, out bytesConsumed, out bytesWritten);
    }
References System.SR.Argument_SourceOverlapsDestination, System.SR.Argument_Tag_NotCharacterString, System.destination, System.Formats.Asn1.AsnDecoder.IsCharacterStringEncodingType(), System.source, and System.Formats.Asn1.AsnDecoder.TryReadCharacterStringBytesCore().
Referenced by System.Formats.Asn1.AsnReader.TryReadCharacterStringBytes().