Terraria: System.Formats.Asn1.AsnDecoder.GetOctetStringContents
GetOctetStringContents()
static ReadOnlySpan< byte > System.Formats.Asn1.AsnDecoder.GetOctetStringContents (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber universalTagNumber, out int bytesConsumed, ref byte[] rented, Span< byte > tmpSpace = default(Span<byte>)) inline static private
Definition at line 1390 of file AsnDecoder.cs.
    {
        if (TryReadPrimitiveOctetStringCore(source, ruleSet, expectedTag, universalTagNumber, out var contentLength, out var headerLength, out var contents, out bytesConsumed))
        {
            return contents;
        }
        contents = source.Slice(headerLength);
        int num = contentLength ?? SeekEndOfContents(contents, ruleSet);
        if (tmpSpace.Length > 0 && num > tmpSpace.Length)
        {
            bool isIndefinite = !contentLength.HasValue;
            num = CountConstructedOctetString(contents, ruleSet, isIndefinite);
        }
        if (num > tmpSpace.Length)
        {
            rented = System.Security.Cryptography.CryptoPool.Rent(num);
            tmpSpace = rented;
        }
        if (TryCopyConstructedOctetStringContents(Slice(source, headerLength, contentLength), ruleSet, tmpSpace, !contentLength.HasValue, out var bytesRead, out var bytesWritten))
        {
            bytesConsumed = headerLength + bytesRead;
            return tmpSpace.Slice(0, bytesWritten);
        }
        throw new AsnContentException();
    }
References System.Formats.Asn1.AsnDecoder.CountConstructedOctetString(), System.Security.Cryptography.CryptoPool.Rent(), System.Formats.Asn1.AsnDecoder.SeekEndOfContents(), System.Formats.Asn1.AsnDecoder.Slice(), System.source, System.Formats.Asn1.AsnDecoder.TryCopyConstructedOctetStringContents(), and System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetStringCore().
Referenced by System.Formats.Asn1.AsnDecoder.ReadCharacterStringCore(), System.Formats.Asn1.AsnDecoder.ReadGeneralizedTime(), System.Formats.Asn1.AsnDecoder.ReadOctetString(), System.Formats.Asn1.AsnDecoder.ReadUtcTime(), and System.Formats.Asn1.AsnDecoder.TryReadCharacterStringCore().