Terraria: System.Formats.Asn1.AsnDecoder.ReadInteger
ReadInteger()
static BigInteger System.Formats.Asn1.AsnDecoder.ReadInteger (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 941 of file AsnDecoder.cs.
    {
        int bytesConsumed2;
        ReadOnlySpan<byte> readOnlySpan = ReadIntegerBytes(source, ruleSet, out bytesConsumed2, expectedTag);
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(readOnlySpan.Length);
        BigInteger result;
        try
        {
            byte value = (byte)(((readOnlySpan[0] & 0x80u) != 0) ? byte.MaxValue : 0);
            new Span<byte>(array, readOnlySpan.Length, array.Length - readOnlySpan.Length).Fill(value);
            readOnlySpan.CopyTo(array);
            AsnWriter.Reverse(new Span<byte>(array, 0, readOnlySpan.Length));
            result = new BigInteger(array);
        }
        finally
        {
            System.Security.Cryptography.CryptoPool.Return(array);
        }
        bytesConsumed = bytesConsumed2;
        return result;
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Formats.Asn1.AsnDecoder.ReadIntegerBytes(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Formats.Asn1.AsnWriter.Reverse(), System.source, and System.value.
Referenced by System.Security.Cryptography.DSAKeyFormatHelper.ReadDsaPublicKey(), System.Formats.Asn1.AsnReader.ReadInteger(), and System.Formats.Asn1.AsnValueReader.ReadInteger().