Terraria: System.Formats.Asn1.AsnDecoder.ReadEnumeratedValue
ReadEnumeratedValue()
static Enum System.Formats.Asn1.AsnDecoder.ReadEnumeratedValue (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Type enumType, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 693 of file AsnDecoder.cs.
    {
        if (enumType == null)
        {
            throw new ArgumentNullException("enumType");
        }
        Asn1Tag expectedTag2 = expectedTag ?? Asn1Tag.Enumerated;
        Type enumUnderlyingType = enumType.GetEnumUnderlyingType();
        if (enumType.IsDefined(typeof(FlagsAttribute), inherit: false))
        {
            throw new ArgumentException(System.SR.Argument_EnumeratedValueRequiresNonFlagsEnum, "enumType");
        }
        int sizeLimit = Marshal.SizeOf(enumUnderlyingType);
        if (enumUnderlyingType == typeof(int) || enumUnderlyingType == typeof(long) || enumUnderlyingType == typeof(short) || enumUnderlyingType == typeof(sbyte))
        {
            if (!TryReadSignedInteger(source, ruleSet, sizeLimit, expectedTag2, UniversalTagNumber.Enumerated, out var value, out var bytesConsumed2))
            {
                throw new AsnContentException(System.SR.ContentException_EnumeratedValueTooBig);
            }
            bytesConsumed = bytesConsumed2;
            return (Enum)Enum.ToObject(enumType, value);
        }
        if (enumUnderlyingType == typeof(uint) || enumUnderlyingType == typeof(ulong) || enumUnderlyingType == typeof(ushort) || enumUnderlyingType == typeof(byte))
        {
            if (!TryReadUnsignedInteger(source, ruleSet, sizeLimit, expectedTag2, UniversalTagNumber.Enumerated, out var value2, out var bytesConsumed3))
            {
                throw new AsnContentException(System.SR.ContentException_EnumeratedValueTooBig);
            }
            bytesConsumed = bytesConsumed3;
            return (Enum)Enum.ToObject(enumType, value2);
        }
        throw new AsnContentException(System.SR.Format(System.SR.Argument_EnumeratedValueBackingTypeNotSupported, enumUnderlyingType.FullName));
    }
References System.SR.Argument_EnumeratedValueBackingTypeNotSupported, System.SR.Argument_EnumeratedValueRequiresNonFlagsEnum, System.SR.ContentException_EnumeratedValueTooBig, System.Formats.Asn1.Asn1Tag.Enumerated, System.SR.Format(), System.Runtime.InteropServices.Marshal.SizeOf(), System.source, System.Enum.ToObject(), System.Formats.Asn1.AsnDecoder.TryReadSignedInteger(), System.Formats.Asn1.AsnDecoder.TryReadUnsignedInteger(), and System.value.
Referenced by System.Formats.Asn1.AsnReader.ReadEnumeratedValue(), System.Formats.Asn1.AsnReader.ReadEnumeratedValue< TEnum >(), and System.Formats.Asn1.AsnDecoder.ReadEnumeratedValue< TEnum >().