Terraria: System.Formats.Asn1.AsnDecoder.ReadSequence
ReadSequence()
static void System.Formats.Asn1.AsnDecoder.ReadSequence (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int contentOffset, out int contentLength, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 1545 of file AsnDecoder.cs.
    {
        int? contentsLength;
        int bytesRead;
        Asn1Tag tag = ReadTagAndLength(source, ruleSet, out contentsLength, out bytesRead);
        CheckExpectedTag(tag, expectedTag ?? Asn1Tag.Sequence, UniversalTagNumber.Sequence);
        if (!tag.IsConstructed)
        {
            throw new AsnContentException(System.SR.Format(System.SR.ContentException_ConstructedEncodingRequired, UniversalTagNumber.Sequence));
        }
        if (contentsLength.HasValue)
        {
            if (contentsLength.Value + bytesRead > source.Length)
            {
                throw GetValidityException(LengthValidity.LengthExceedsInput);
            }
            contentLength = contentsLength.Value;
            contentOffset = bytesRead;
            bytesConsumed = contentLength + bytesRead;
        }
        else
        {
            int num = (contentLength = SeekEndOfContents(source.Slice(bytesRead), ruleSet));
            contentOffset = bytesRead;
            bytesConsumed = num + bytesRead + 2;
        }
    }
References System.Formats.Asn1.AsnDecoder.CheckExpectedTag(), System.SR.ContentException_ConstructedEncodingRequired, System.SR.Format(), System.Formats.Asn1.AsnDecoder.GetValidityException(), System.Formats.Asn1.Asn1Tag.IsConstructed, System.Formats.Asn1.AsnDecoder.ReadTagAndLength(), System.Formats.Asn1.AsnDecoder.SeekEndOfContents(), System.Formats.Asn1.Asn1Tag.Sequence, and System.source.
Referenced by System.Formats.Asn1.AsnReader.ReadSequence(), and System.Formats.Asn1.AsnValueReader.ReadSequence().