Terraria: System.Formats.Asn1.AsnDecoder.SeekEndOfContents
SeekEndOfContents()
static int System.Formats.Asn1.AsnDecoder.SeekEndOfContents (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet) inline static private
Definition at line 272 of file AsnDecoder.cs.
    {
        ReadOnlySpan<byte> source2 = source;
        int num = 0;
        int num2 = 1;
        while (!source2.IsEmpty)
        {
            int? contentsLength;
            int bytesRead;
            Asn1Tag asn1Tag = ReadTagAndLength(source2, ruleSet, out contentsLength, out bytesRead);
            if (asn1Tag == Asn1Tag.EndOfContents)
            {
                ValidateEndOfContents(asn1Tag, contentsLength, bytesRead);
                num2--;
                if (num2 == 0)
                {
                    return num;
                }
            }
            if (!contentsLength.HasValue)
            {
                num2++;
                source2 = source2.Slice(bytesRead);
                num += bytesRead;
            }
            else
            {
                ReadOnlySpan<byte> readOnlySpan = Slice(source2, 0, bytesRead + contentsLength.Value);
                source2 = source2.Slice(readOnlySpan.Length);
                num += readOnlySpan.Length;
            }
        }
        throw new AsnContentException();
    }
References System.Formats.Asn1.Asn1Tag.EndOfContents, System.Formats.Asn1.AsnDecoder.ReadTagAndLength(), System.Formats.Asn1.AsnDecoder.Slice(), System.source, and System.Formats.Asn1.AsnDecoder.ValidateEndOfContents().
Referenced by System.Formats.Asn1.AsnDecoder.GetOctetStringContents(), System.Formats.Asn1.AsnDecoder.ReadBitString(), System.Formats.Asn1.AsnDecoder.ReadSequence(), System.Formats.Asn1.AsnDecoder.ReadSetOf(), and System.Formats.Asn1.AsnDecoder.ValidateLength().