Terraria: System.Formats.Asn1.AsnDecoder.ReadBoolean
ReadBoolean()
static bool System.Formats.Asn1.AsnDecoder.ReadBoolean (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 656 of file AsnDecoder.cs.
    {
        int bytesConsumed2;
        ReadOnlySpan<byte> primitiveContentSpan = GetPrimitiveContentSpan(source, ruleSet, expectedTag ?? Asn1Tag.Boolean, UniversalTagNumber.Boolean, out bytesConsumed2);
        if (primitiveContentSpan.Length != 1)
        {
            throw new AsnContentException();
        }
        switch (primitiveContentSpan[0])
        {
        case 0:
            bytesConsumed = bytesConsumed2;
            return false;
        default:
            if (ruleSet == AsnEncodingRules.DER || ruleSet == AsnEncodingRules.CER)
            {
                throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
            }
            break;
        case byte.MaxValue:
            break;
        }
        bytesConsumed = bytesConsumed2;
        return true;
    }
References System.Formats.Asn1.Asn1Tag.Boolean, System.SR.ContentException_InvalidUnderCerOrDer_TryBer, System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan(), and System.source.
Referenced by System.Formats.Asn1.AsnReader.ReadBoolean(), and System.Formats.Asn1.AsnValueReader.ReadBoolean().