Terraria: System.Formats.Asn1.AsnDecoder.ReadEncodedValue
ReadEncodedValue()
static Asn1Tag System.Formats.Asn1.AsnDecoder.ReadEncodedValue (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int contentOffset, out int contentLength, out int bytesConsumed) inline static
Definition at line 57 of file AsnDecoder.cs.
    {
        CheckEncodingRules(ruleSet);
        int bytesConsumed2;
        Asn1Tag asn1Tag = Asn1Tag.Decode(source, out bytesConsumed2);
        int bytesConsumed3;
        int? encodedLength = ReadLength(source.Slice(bytesConsumed2), ruleSet, out bytesConsumed3);
        int num = bytesConsumed2 + bytesConsumed3;
        int actualLength;
        int bytesConsumed4;
        LengthValidity lengthValidity = ValidateLength(source.Slice(num), ruleSet, asn1Tag, encodedLength, out actualLength, out bytesConsumed4);
        if (lengthValidity == LengthValidity.Valid)
        {
            contentOffset = num;
            contentLength = actualLength;
            bytesConsumed = num + bytesConsumed4;
            return asn1Tag;
        }
        throw GetValidityException(lengthValidity);
    }
References System.Formats.Asn1.AsnDecoder.CheckEncodingRules(), System.Formats.Asn1.Asn1Tag.Decode(), System.Formats.Asn1.AsnDecoder.GetValidityException(), System.Formats.Asn1.AsnDecoder.ReadLength(), System.source, and System.Formats.Asn1.AsnDecoder.ValidateLength().
Referenced by System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), System.Security.Cryptography.CngPkcs8.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(), System.Security.Cryptography.RSA.ImportRSAPrivateKey(), System.Security.Cryptography.RSA.ImportRSAPublicKey(), System.Formats.Asn1.AsnReader.PeekContentBytes(), System.Formats.Asn1.AsnReader.PeekEncodedValue(), System.Formats.Asn1.AsnValueReader.PeekEncodedValue(), System.Formats.Asn1.AsnDecoder.ReadNamedBitList(), and System.Formats.Asn1.AsnDecoder.ReadSetOf().