Terraria: System.Formats.Asn1.AsnDecoder.ReadLength
ReadLength()
static ? int System.Formats.Asn1.AsnDecoder.ReadLength (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int bytesConsumed) inline static private
Definition at line 105 of file AsnDecoder.cs.
    {
        int? length;
        switch (DecodeLength(source, ruleSet, out length, out bytesConsumed))
        {
        case LengthDecodeStatus.Success:
            return length;
        case LengthDecodeStatus.LengthTooBig:
            throw new AsnContentException(System.SR.ContentException_LengthTooBig);
        case LengthDecodeStatus.DerIndefinite:
        case LengthDecodeStatus.LaxEncodingProhibited:
            throw new AsnContentException(System.SR.ContentException_LengthRuleSetConstraint);
        default:
            throw new AsnContentException();
        }
    }
References System.SR.ContentException_LengthRuleSetConstraint, System.SR.ContentException_LengthTooBig, System.Formats.Asn1.AsnDecoder.DecodeLength(), System.length, and System.source.
Referenced by System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan(), System.Formats.Asn1.AsnDecoder.ReadEncodedValue(), and System.Formats.Asn1.AsnDecoder.ReadTagAndLength().