Terraria: System.Formats.Asn1.AsnDecoder.CheckExpectedTag
CheckExpectedTag()
static void System.Formats.Asn1.AsnDecoder.CheckExpectedTag (Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber) inline static private
Definition at line 372 of file AsnDecoder.cs.
    {
        if (expectedTag.TagClass == TagClass.Universal && expectedTag.TagValue != (int)tagNumber)
        {
            throw new ArgumentException(System.SR.Argument_UniversalValueIsFixed, "expectedTag");
        }
        if (expectedTag.TagClass != tag.TagClass || expectedTag.TagValue != tag.TagValue)
        {
            throw new AsnContentException(System.SR.Format(System.SR.ContentException_WrongTag, tag.TagClass, tag.TagValue, expectedTag.TagClass, expectedTag.TagValue));
        }
    }
References System.SR.Argument_UniversalValueIsFixed, System.SR.ContentException_WrongTag, System.SR.Format(), System.Formats.Asn1.Asn1Tag.TagClass, and System.Formats.Asn1.Asn1Tag.TagValue.
Referenced by System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan(), System.Formats.Asn1.AsnDecoder.ReadNamedBitList(), System.Formats.Asn1.AsnDecoder.ReadSequence(), System.Formats.Asn1.AsnDecoder.ReadSetOf(), System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitStringCore(), and System.Formats.Asn1.AsnDecoder.TryReadPrimitiveOctetStringCore().