Terraria: System.Formats.Asn1.AsnDecoder.TryReadCharacterStringCore
TryReadCharacterStringCore() [1/2]
static bool System.Formats.Asn1.AsnDecoder.TryReadCharacterStringCore (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber universalTagNumber, Encoding encoding, Span< char > destination, out int bytesConsumed, out int charsWritten) inline static private
Definition at line 1753 of file AsnDecoder.cs.
    {
        byte[] rented = null;
        int bytesConsumed2;
        ReadOnlySpan<byte> octetStringContents = GetOctetStringContents(source, ruleSet, expectedTag, universalTagNumber, out bytesConsumed2, ref rented);
        bool flag = TryReadCharacterStringCore(octetStringContents, destination, encoding, out charsWritten);
        if (rented != null)
        {
            System.Security.Cryptography.CryptoPool.Return(rented, octetStringContents.Length);
        }
        if (flag)
        {
            bytesConsumed = bytesConsumed2;
        }
        else
        {
            bytesConsumed = 0;
        }
        return flag;
    }
References System.destination, System.Formats.Asn1.AsnDecoder.GetOctetStringContents(), System.Security.Cryptography.CryptoPool.Return(), System.source, and System.Formats.Asn1.AsnDecoder.TryReadCharacterStringCore().