Terraria: System.Formats.Asn1.AsnDecoder.TryReadBitString
TryReadBitString()
static bool System.Formats.Asn1.AsnDecoder.TryReadBitString (ReadOnlySpan< byte > source, Span< byte > destination, AsnEncodingRules ruleSet, out int unusedBitCount, out int bytesConsumed, out int bytesWritten, Asn1Tag? expectedTag = null) inline static
Definition at line 399 of file AsnDecoder.cs.
    {
        if (source.Overlaps(destination))
        {
            throw new ArgumentException(System.SR.Argument_SourceOverlapsDestination, "destination");
        }
        if (TryReadPrimitiveBitStringCore(source, ruleSet, expectedTag ?? Asn1Tag.PrimitiveBitString, out var contentsLength, out var headerLength, out var unusedBitCount2, out var value, out var bytesConsumed2, out var normalizedLastByte))
        {
            if (value.Length > destination.Length)
            {
                bytesConsumed = 0;
                bytesWritten = 0;
                unusedBitCount = 0;
                return false;
            }
            CopyBitStringValue(value, normalizedLastByte, destination);
            bytesWritten = value.Length;
            bytesConsumed = bytesConsumed2;
            unusedBitCount = unusedBitCount2;
            return true;
        }
        if (TryCopyConstructedBitStringValue(Slice(source, headerLength, contentsLength), ruleSet, destination, !contentsLength.HasValue, out unusedBitCount2, out var bytesRead, out var bytesWritten2))
        {
            unusedBitCount = unusedBitCount2;
            bytesConsumed = headerLength + bytesRead;
            bytesWritten = bytesWritten2;
            return true;
        }
        bytesWritten = (bytesConsumed = (unusedBitCount = 0));
        return false;
    }
References System.SR.Argument_SourceOverlapsDestination, System.Formats.Asn1.AsnDecoder.CopyBitStringValue(), System.destination, System.Formats.Asn1.Asn1Tag.PrimitiveBitString, System.Formats.Asn1.AsnDecoder.Slice(), System.source, System.Formats.Asn1.AsnDecoder.TryCopyConstructedBitStringValue(), System.Formats.Asn1.AsnDecoder.TryReadPrimitiveBitStringCore(), and System.value.
Referenced by System.Formats.Asn1.AsnDecoder.ReadNamedBitList(), System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue(), and System.Formats.Asn1.AsnReader.TryReadBitString().