Terraria: System.Formats.Asn1.AsnDecoder.ParseGeneralizedTime
ParseGeneralizedTime()
static DateTimeOffset System.Formats.Asn1.AsnDecoder.ParseGeneralizedTime (AsnEncodingRules ruleSet, ReadOnlySpan< byte > contentOctets) inline static private
Definition at line 742 of file AsnDecoder.cs.
    {
        bool flag = ruleSet == AsnEncodingRules.DER || ruleSet == AsnEncodingRules.CER;
        if (flag && contentOctets.Length < 15)
        {
            throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
        }
        if (contentOctets.Length < 10)
        {
            throw new AsnContentException();
        }
        ReadOnlySpan<byte> data = contentOctets;
        int year = ParseNonNegativeIntAndSlice(ref data, 4);
        int month = ParseNonNegativeIntAndSlice(ref data, 2);
        int day = ParseNonNegativeIntAndSlice(ref data, 2);
        int hour = ParseNonNegativeIntAndSlice(ref data, 2);
        int? num = null;
        int? num2 = null;
        ulong value = 0uL;
        ulong num3 = 1uL;
        byte b = byte.MaxValue;
        TimeSpan? timeSpan = null;
        bool flag2 = false;
        byte b2 = 0;
        while (b2 == 0 && data.Length != 0)
        {
            byte? b3 = GetNextState(data[0]);
            if (!b3.HasValue)
            {
                if (!num.HasValue)
                {
                    num = ParseNonNegativeIntAndSlice(ref data, 2);
                    continue;
                }
                if (num2.HasValue)
                {
                    throw new AsnContentException();
                }
                num2 = ParseNonNegativeIntAndSlice(ref data, 2);
            }
            else
            {
                b2 = b3.Value;
            }
        }
        if (b2 == 1)
        {
            switch (data[0])
            {
            case 44:
                if (flag)
                {
                    throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
                }
                break;
            default:
                throw new AsnContentException();
            case 46:
                break;
            }
            data = data.Slice(1);
            if (data.IsEmpty)
            {
                throw new AsnContentException();
            }
            if (!Utf8Parser.TryParse(SliceAtMost(data, 12), out value, out int bytesConsumed, '\0') || bytesConsumed == 0)
            {
                throw new AsnContentException();
            }
            b = (byte)(value % 10);
            for (int i = 0; i < bytesConsumed; i++)
            {
                num3 *= 10;
            }
            data = data.Slice(bytesConsumed);
            uint value2;
            while (Utf8Parser.TryParse(SliceAtMost(data, 9), out value2, out bytesConsumed, '\0'))
            {
                data = data.Slice(bytesConsumed);
                b = (byte)(value2 % 10);
            }
            if (data.Length != 0)
            {
                byte? b4 = GetNextState(data[0]);
                if (!b4.HasValue)
                {
                    throw new AsnContentException();
                }
                b2 = b4.Value;
            }
        }
        if (b2 == 2)
        {
            byte b5 = data[0];
            data = data.Slice(1);
            if (b5 == 90)
            {
                timeSpan = TimeSpan.Zero;
                flag2 = true;
            }
            else
            {
                bool flag3 = b5 switch
                {
                    43 => false,
                    45 => true,
                    _ => throw new AsnContentException(),
                };
                if (data.IsEmpty)
                {
                    throw new AsnContentException();
                }
                int hours = ParseNonNegativeIntAndSlice(ref data, 2);
                int num4 = 0;
                if (data.Length != 0)
                {
                    num4 = ParseNonNegativeIntAndSlice(ref data, 2);
                }
                if (num4 > 59)
                {
                    throw new AsnContentException();
                }
                TimeSpan timeSpan2 = new TimeSpan(hours, num4, 0);
                if (flag3)
                {
                    timeSpan2 = -timeSpan2;
                }
                timeSpan = timeSpan2;
            }
        }
        if (!data.IsEmpty)
        {
            throw new AsnContentException();
        }
        if (flag)
        {
            if (!flag2 || !num2.HasValue)
            {
                throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
            }
            if (b == 0)
            {
                throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
            }
        }
        double num5 = (double)value / (double)num3;
        TimeSpan timeSpan3 = TimeSpan.Zero;
        if (!num.HasValue)
        {
            num = 0;
            num2 = 0;
            if (value != 0L)
            {
                timeSpan3 = new TimeSpan((long)(num5 * 36000000000.0));
            }
        }
        else if (!num2.HasValue)
        {
            num2 = 0;
            if (value != 0L)
            {
                timeSpan3 = new TimeSpan((long)(num5 * 600000000.0));
            }
        }
        else if (value != 0L)
        {
            timeSpan3 = new TimeSpan((long)(num5 * 10000000.0));
        }
        try
        {
            DateTimeOffset dateTimeOffset = (timeSpan.HasValue ? new DateTimeOffset(year, month, day, hour, num.Value, num2.Value, timeSpan.Value) : new DateTimeOffset(new DateTime(year, month, day, hour, num.Value, num2.Value)));
            return dateTimeOffset + timeSpan3;
        }
        catch (Exception inner)
        {
            throw new AsnContentException(System.SR.ContentException_DefaultMessage, inner);
        }
        static byte? GetNextState(byte octet)
        {
            switch (octet)
            {
            case 43:
            case 45:
            case 90:
                return 2;
            case 44:
            case 46:
                return 1;
            default:
                return null;
            }
        }
    }
References System.SR.ContentException_DefaultMessage, System.SR.ContentException_InvalidUnderCerOrDer_TryBer, System.Formats.Asn1.DateTime, System.L, System.Formats.Asn1.AsnDecoder.ParseNonNegativeIntAndSlice(), System.Formats.Asn1.AsnDecoder.SliceAtMost(), System.Buffers.Text.Utf8Parser.TryParse(), System.value, System.year, and System.TimeSpan.Zero.
Referenced by System.Formats.Asn1.AsnDecoder.ReadGeneralizedTime().