Terraria: System.Formats.Asn1.AsnDecoder.ReadUtcTime
ReadUtcTime()
static DateTimeOffset System.Formats.Asn1.AsnDecoder.ReadUtcTime (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int bytesConsumed, int twoDigitYearMax = 2049, Asn1Tag? expectedTag = null) inline static
Definition at line 1795 of file AsnDecoder.cs.
    {
        if (twoDigitYearMax < 1 || twoDigitYearMax > 9999)
        {
            throw new ArgumentOutOfRangeException("twoDigitYearMax");
        }
        Span<byte> tmpSpace = stackalloc byte[17];
        byte[] rented = null;
        int bytesConsumed2;
        ReadOnlySpan<byte> octetStringContents = GetOctetStringContents(source, ruleSet, expectedTag ?? Asn1Tag.UtcTime, UniversalTagNumber.UtcTime, out bytesConsumed2, ref rented, tmpSpace);
        DateTimeOffset result = ParseUtcTime(octetStringContents, ruleSet, twoDigitYearMax);
        if (rented != null)
        {
            System.Security.Cryptography.CryptoPool.Return(rented, octetStringContents.Length);
        }
        bytesConsumed = bytesConsumed2;
        return result;
    }
References System.Formats.Asn1.AsnDecoder.GetOctetStringContents(), System.Formats.Asn1.AsnDecoder.ParseUtcTime(), System.Security.Cryptography.CryptoPool.Return(), System.source, and System.Formats.Asn1.Asn1Tag.UtcTime.
Referenced by System.Formats.Asn1.AsnReader.ReadUtcTime(), System.Formats.Asn1.AsnValueReader.ReadUtcTime(), and System.Formats.Asn1.AsnReader.ReadUtcTime().