Terraria: System.Formats.Asn1.AsnDecoder.ReadNamedBitList
ReadNamedBitList()
static BitArray System.Formats.Asn1.AsnDecoder.ReadNamedBitList (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 1117 of file AsnDecoder.cs.
    {
        int contentOffset;
        int contentLength;
        int bytesConsumed2;
        Asn1Tag tag = ReadEncodedValue(source, ruleSet, out contentOffset, out contentLength, out bytesConsumed2);
        if (expectedTag.HasValue)
        {
            CheckExpectedTag(tag, expectedTag.Value, UniversalTagNumber.BitString);
        }
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(contentLength);
        if (!TryReadBitString(source, array, ruleSet, out var unusedBitCount, out var bytesConsumed3, out var bytesWritten, expectedTag))
        {
            throw new InvalidOperationException();
        }
        int length = checked(bytesWritten * 8 - unusedBitCount);
        Span<byte> value = array.AsSpan(0, bytesWritten);
        ReverseBitsPerByte(value);
        BitArray bitArray = new BitArray(array);
        System.Security.Cryptography.CryptoPool.Return(array, bytesWritten);
        bitArray.Length = length;
        bytesConsumed = bytesConsumed3;
        return bitArray;
    }
References System.array, System.Formats.Asn1.AsnDecoder.CheckExpectedTag(), System.length, System.Formats.Asn1.AsnDecoder.ReadEncodedValue(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Formats.Asn1.AsnDecoder.ReverseBitsPerByte(), System.source, System.Formats.Asn1.AsnDecoder.TryReadBitString(), and System.value.
Referenced by System.Formats.Asn1.AsnReader.ReadNamedBitList().