Terraria: System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue
ReadNamedBitListValue()
static Enum System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue (ReadOnlySpan< byte > source, AsnEncodingRules ruleSet, Type flagsEnumType, out int bytesConsumed, Asn1Tag? expectedTag = null) inline static
Definition at line 1078 of file AsnDecoder.cs.
    {
        if (flagsEnumType == null)
        {
            throw new ArgumentNullException("flagsEnumType");
        }
        Type enumUnderlyingType = flagsEnumType.GetEnumUnderlyingType();
        if (!flagsEnumType.IsDefined(typeof(FlagsAttribute), inherit: false))
        {
            throw new ArgumentException(System.SR.Argument_NamedBitListRequiresFlagsEnum, "flagsEnumType");
        }
        Span<byte> destination = stackalloc byte[8];
        destination = destination[..Marshal.SizeOf(enumUnderlyingType)];
        if (!TryReadBitString(source, destination, ruleSet, out var unusedBitCount, out var bytesConsumed2, out var bytesWritten, expectedTag))
        {
            throw new AsnContentException(System.SR.Format(System.SR.ContentException_NamedBitListValueTooBig, flagsEnumType.Name));
        }
        Enum result;
        if (bytesWritten == 0)
        {
            result = (Enum)Enum.ToObject(flagsEnumType, 0);
            bytesConsumed = bytesConsumed2;
            return result;
        }
        ReadOnlySpan<byte> valueSpan = destination.Slice(0, bytesWritten);
        if (ruleSet == AsnEncodingRules.DER || ruleSet == AsnEncodingRules.CER)
        {
            byte b = valueSpan[bytesWritten - 1];
            byte b2 = (byte)(1 << unusedBitCount);
            if ((b & b2) == 0)
            {
                throw new AsnContentException(System.SR.ContentException_InvalidUnderCerOrDer_TryBer);
            }
        }
        result = (Enum)Enum.ToObject(flagsEnumType, InterpretNamedBitListReversed(valueSpan));
        bytesConsumed = bytesConsumed2;
        return result;
    }
References System.SR.Argument_NamedBitListRequiresFlagsEnum, System.SR.ContentException_InvalidUnderCerOrDer_TryBer, System.SR.ContentException_NamedBitListValueTooBig, System.destination, System.Enum, System.SR.Format(), System.Formats.Asn1.AsnDecoder.InterpretNamedBitListReversed(), System.Runtime.InteropServices.Marshal.SizeOf(), System.source, System.Enum.ToObject(), and System.Formats.Asn1.AsnDecoder.TryReadBitString().
Referenced by System.Formats.Asn1.AsnReader.ReadNamedBitListValue(), System.Formats.Asn1.AsnReader.ReadNamedBitListValue< TFlagsEnum >(), and System.Formats.Asn1.AsnDecoder.ReadNamedBitListValue< TFlagsEnum >().