Terraria: System.IO.File.OpenHandle
OpenHandle()
static SafeFileHandle System.IO.File.OpenHandle (string path, FileMode mode = FileMode::Open, FileAccess access = FileAccess::Read, FileShare share = FileShare::Read, FileOptions options = FileOptions::None, long preallocationSize = 0L) inline static
Definition at line 1009 of file File.cs.
    {
        FileStreamHelpers.ValidateArguments(path, mode, access, share, 0, options, preallocationSize);
        return SafeFileHandle.Open(Path.GetFullPath(path), mode, access, share, options, preallocationSize);
    }
References System.IO.Path.GetFullPath(), Microsoft.Win32.SafeHandles.SafeFileHandle.Open(), System.options, and System.IO.Strategies.FileStreamHelpers.ValidateArguments().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets(), System.Net.Sockets.Socket.OpenFileHandle(), System.IO.File.WriteAllBytes(), and System.IO.File.WriteAllBytesAsync().