Terraria: System.IO.File.Move
Move() [2/2]
static void System.IO.File.Move (string sourceFileName, string destFileName, bool overwrite) inline static
Definition at line 586 of file File.cs.
    {
        if (sourceFileName == null)
        {
            throw new ArgumentNullException("sourceFileName", SR.ArgumentNull_FileName);
        }
        if (destFileName == null)
        {
            throw new ArgumentNullException("destFileName", SR.ArgumentNull_FileName);
        }
        if (sourceFileName.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyFileName, "sourceFileName");
        }
        if (destFileName.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyFileName, "destFileName");
        }
        string fullPath = Path.GetFullPath(sourceFileName);
        string fullPath2 = Path.GetFullPath(destFileName);
        if (!FileSystem.FileExists(fullPath))
        {
            throw new FileNotFoundException(SR.Format(SR.IO_FileNotFound_FileName, fullPath), fullPath);
        }
        FileSystem.MoveFile(fullPath, fullPath2, overwrite);
    }
References System.SR.Argument_EmptyFileName, System.SR.ArgumentNull_FileName, System.IO.FileSystem.FileExists(), System.SR.Format(), System.IO.Path.GetFullPath(), System.SR.IO_FileNotFound_FileName, and System.IO.FileSystem.MoveFile().