Terraria: System.IO.File.Exists
Exists()
static bool System.IO.File.Exists ([NotNullWhen(true)] string? path) inline static
Definition at line 97 of file File.cs.
    {
        try
        {
            if (path == null)
            {
                return false;
            }
            if (path.Length == 0)
            {
                return false;
            }
            path = Path.GetFullPath(path);
            if (path.Length > 0 && PathInternal.IsDirectorySeparator(path[path.Length - 1]))
            {
                return false;
            }
            return FileSystem.FileExists(path);
        }
        catch (ArgumentException)
        {
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
        return false;
    }
References System.IO.FileSystem.FileExists(), System.IO.Path.GetFullPath(), and System.IO.PathInternal.IsDirectorySeparator().
Referenced by Terraria.IO.ResourcePack.ResourcePack(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._readProps(), System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(), Terraria.IO.ResourcePackList.CreatePacksFromSavedJson(), Terraria.Utilities.FileUtilities.Exists(), System.IO.IsolatedStorage.IsolatedStorageFile.FileExists(), System.Resources.FileBasedResourceGroveler.FindResourceFile(), System.Net.Mail.SmtpClient.GetFileMailWriter(), System.ComponentModel.LicFileLicenseProvider.GetLicense(), System.TimeZoneInfo.GetLocalizedNameByMuiNativeResource(), System.Diagnostics.FileVersionInfo.GetVersionInfo(), Terraria.IO.ResourcePack.HasFile(), Terraria.Netplay.IsBanned(), Terraria.IO.Preferences.Load(), System.Xml.Serialization.TempAssembly.LoadAssemblyByPath(), Terraria.Main.LoadDedConfig(), Terraria.Main.LoadSettings(), Terraria.Main.OpenLegacySettings(), Terraria.Main.OpenRecent(), ReLogic.Content.Sources.FileSystemContentSource.OpenStream(), ReLogic.Content.Sources.XnaDirectContentSource.OpenStream(), Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh(), Terraria.Utilities.FileUtilities.RemoveReadOnlyAttribute(), System.Runtime.Loader.AssemblyDependencyResolver.ResolveAssemblyToPath(), System.Runtime.Loader.AssemblyDependencyResolver.ResolveUnmanagedDllToPath(), Terraria.IO.Preferences.Save(), System.Diagnostics.StackTraceSymbols.TryOpenFile(), and Terraria.Social.Base.AWorkshopEntry.TryReadingManifest().