Terraria: System.IO.File.ReadAllBytesUnknownLength
ReadAllBytesUnknownLength()
static byte[] System.IO.File.ReadAllBytesUnknownLength (FileStream fs) inline static private
Definition at line 1015 of file File.cs.
    {
        byte[] array = null;
        Span<byte> span = stackalloc byte[512];
        try
        {
            int num = 0;
            while (true)
            {
                if (num == span.Length)
                {
                    uint num2 = (uint)(span.Length * 2);
                    if (num2 > Array.MaxLength)
                    {
                        num2 = (uint)Math.Max(Array.MaxLength, span.Length + 1);
                    }
                    byte[] array2 = ArrayPool<byte>.Shared.Rent((int)num2);
                    span.CopyTo(array2);
                    byte[] array3 = array;
                    span = (array = array2);
                    if (array3 != null)
                    {
                        ArrayPool<byte>.Shared.Return(array3);
                    }
                }
                int num3 = fs.Read(span.Slice(num));
                if (num3 == 0)
                {
                    break;
                }
                num += num3;
            }
            return span.Slice(0, num).ToArray();
        }
        finally
        {
            if (array != null)
            {
                ArrayPool<byte>.Shared.Return(array);
            }
        }
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Math.Max(), and System.Array.MaxLength.
Referenced by System.IO.File.ReadAllBytes().