Terraria: System.IO.File.WriteAllLinesAsync
WriteAllLinesAsync() [2/2]
static Task System.IO.File.WriteAllLinesAsync (string path, IEnumerable< string > contents, Encoding encoding, CancellationToken cancellationToken = default(CancellationToken)) inline static
Definition at line 881 of file File.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (contents == null)
        {
            throw new ArgumentNullException("contents");
        }
        if (encoding == null)
        {
            throw new ArgumentNullException("encoding");
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyPath, "path");
        }
        if (!cancellationToken.IsCancellationRequested)
        {
            return InternalWriteAllLinesAsync(AsyncStreamWriter(path, encoding, append: false), contents, cancellationToken);
        }
        return Task.FromCanceled(cancellationToken);
    }
References System.SR.Argument_EmptyPath, System.IO.File.AsyncStreamWriter(), System.cancellationToken, System.Threading.Tasks.Task< TResult >.FromCanceled(), and System.IO.File.InternalWriteAllLinesAsync().