Terraria: System.IO.File.GetCreationTime
GetCreationTime()
static DateTime System.IO.File.GetCreationTime (string path) inline static
Definition at line 164 of file File.cs.
    {
        string fullPath = Path.GetFullPath(path);
        return FileSystem.GetCreationTime(fullPath).LocalDateTime;
    }
References System.IO.FileSystem.GetCreationTime(), and System.IO.Path.GetFullPath().
Referenced by Terraria.IO.WorldFileData.FromInvalidWorld(), Terraria.IO.WorldFile.GetAllMetadata(), System.IO.IsolatedStorage.IsolatedStorageFile.GetCreationTime(), System.IO.Directory.GetCreationTime(), and Terraria.IO.WorldFile.LoadWorld().