Terraria: System.IO.File.Copy
Copy() [1/2]
static void System.IO.File.Copy (string sourceFileName, string destFileName) inline static
Definition at line 47 of file File.cs.
    {
        Copy(sourceFileName, destFileName, overwrite: false);
    }
References System.IO.File.Copy().
Referenced by Terraria.Utilities.FileUtilities.Copy(), System.IO.File.Copy(), System.IO.IsolatedStorage.IsolatedStorageFile.CopyFile(), Terraria.Utilities.FileUtilities.CopyFolder(), and Terraria.Map.WorldMap.Load().