Terraria: System.IO.File.ReadAllText
ReadAllText() [1/2]
static string System.IO.File.ReadAllText (string path) inline static
Definition at line 246 of file File.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyPath, "path");
        }
        return InternalReadAllText(path, Encoding.UTF8);
    }
References System.SR.Argument_EmptyPath, System.IO.File.InternalReadAllText(), and System.Text.Encoding.UTF8.
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._readProps(), System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromEncryptedPemFile(), System.Security.Cryptography.X509Certificates.X509Certificate2.CreateFromPemFile(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.ImportFromPemFile(), Terraria.IO.Preferences.Load(), Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh(), and Terraria.Social.Base.AWorkshopEntry.TryReadingManifest().