Terraria: System.IO.File.Create
Create() [1/3]
static FileStream System.IO.File.Create (string path) inline static
Definition at line 73 of file File.cs.
    {
        return Create(path, 4096);
    }
References System.IO.Create.
Referenced by ReLogic.IO.ConsoleOutputMirror.ConsoleOutputMirror(), Terraria.Utilities.FileUtilities.Copy(), System.IO.FileInfo.Create(), Terraria.IO.Preferences.Save(), Terraria.Graphics.Capture.CaptureCamera.SaveImage(), Terraria.Graphics.Capture.CaptureCamera.SaveImage(), and Terraria.Utilities.CrashDump.Write().