Terraria: System.IO.File.WriteAllBytesAsync
WriteAllBytesAsync()
static Task System.IO.File.WriteAllBytesAsync (string path, byte[] bytes, CancellationToken cancellationToken = default(CancellationToken)) inline static
Definition at line 810 of file File.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path", SR.ArgumentNull_Path);
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyPath, "path");
        }
        if (bytes == null)
        {
            throw new ArgumentNullException("bytes");
        }
        if (!cancellationToken.IsCancellationRequested)
        {
            return Core(path, bytes, cancellationToken);
        }
        return Task.FromCanceled(cancellationToken);
        static async Task Core(string path, byte[] bytes, CancellationToken cancellationToken)
        {
            using SafeFileHandle sfh = OpenHandle(path, FileMode.Create, FileAccess.Write, FileShare.Read, FileOptions.Asynchronous | FileOptions.SequentialScan, 0L);
            await RandomAccess.WriteAtOffsetAsync(sfh, bytes, 0L, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.SR.Argument_EmptyPath, System.SR.ArgumentNull_Path, System.bytes, System.cancellationToken, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.L, System.IO.File.OpenHandle(), and System.IO.RandomAccess.WriteAtOffsetAsync().