Terraria: OneFromOptionsDropRule.TryDroppingItem
TryDroppingItem()
ItemDropAttemptResult OneFromOptionsDropRule.TryDroppingItem (DropAttemptInfo info) inline
Implements IItemDropRule.
     {
         ItemDropAttemptResult result;
         if (info.player.RollLuck(chanceDenominator) < chanceNumerator)
         {
             CommonCode.DropItemFromNPC(info.npc, dropIds[info.rng.Next(dropIds.Length)], 1);
             result = default(ItemDropAttemptResult);
             result.State = ItemDropAttemptResultState.Success;
             return result;
         }
         result = default(ItemDropAttemptResult);
         result.State = ItemDropAttemptResultState.FailedRandomRoll;
         return result;
     }
References chanceDenominator, chanceNumerator, dropIds, CommonCode.DropItemFromNPC(), UnifiedRandom.Next(), DropAttemptInfo.npc, DropAttemptInfo.player, DropAttemptInfo.rng, Player.RollLuck(), and ItemDropAttemptResult.State.