Terraria: System.Threading.Thread.StartHelper.RunWorker
RunWorker()
void System.Threading.Thread.StartHelper.RunWorker () inline private
Definition at line 54 of file Thread.cs.
        {
            InitializeCulture();
            Delegate start = _start;
            _start = null;
            if (start is ThreadStart threadStart)
            {
                threadStart();
                return;
            }
            ParameterizedThreadStart parameterizedThreadStart = (ParameterizedThreadStart)start;
            object startArg = _startArg;
            _startArg = null;
            parameterizedThreadStart(startArg);
        }
References System.Threading.Thread.StartHelper._start, System.Threading.Thread.StartHelper._startArg, System.Threading.Thread.StartHelper.InitializeCulture(), System.Threading.ParameterizedThreadStart(), System.start, and System.Threading.ThreadStart().
Referenced by System.Threading.Thread.StartHelper.Run().