Terraria: System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowMissingRequiredMembers
ThrowMissingRequiredMembers()
static void System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowMissingRequiredMembers (object obj, XmlDictionaryString[] memberNames, byte[] expectedElements, byte[] requiredElements) inline static
Definition at line 283 of file XmlObjectSerializerReadContextComplexJson.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        int num = 0;
        for (int i = 0; i < memberNames.Length; i++)
        {
            if (IsBitSet(expectedElements, i) && IsBitSet(requiredElements, i))
            {
                if (stringBuilder.Length != 0)
                {
                    stringBuilder.Append(", ");
                }
                stringBuilder.Append(memberNames[i]);
                num++;
            }
        }
        if (num == 1)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SerializationException(System.SR.Format(System.SR.JsonOneRequiredMemberNotFound, DataContract.GetClrTypeFullName(obj.GetType()), stringBuilder.ToString())));
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SerializationException(System.SR.Format(System.SR.JsonRequiredMembersNotFound, DataContract.GetClrTypeFullName(obj.GetType()), stringBuilder.ToString())));
    }
References System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.IsBitSet(), System.SR.JsonOneRequiredMemberNotFound, System.SR.JsonRequiredMembersNotFound, System.obj, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().