Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteNamespaceDeclarations
WriteNamespaceDeclarations()
void System.Xml.Serialization.XmlSerializationWriter.WriteNamespaceDeclarations (XmlSerializerNamespaces? xmlns) inline protected
Definition at line 1572 of file XmlSerializationWriter.cs.
    {
        if (xmlns != null)
        {
            foreach (XmlQualifiedName namespace2 in xmlns.Namespaces)
            {
                string name = namespace2.Name;
                string @namespace = namespace2.Namespace;
                if (_namespaces != null && _namespaces.TryLookupNamespace(name, out var ns) && ns != null && ns != @namespace)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlDuplicateNs, name, @namespace));
                }
                string text = ((@namespace == null || @namespace.Length == 0) ? null : Writer.LookupPrefix(@namespace));
                if (text == null || text != name)
                {
                    WriteAttribute("xmlns", name, null, @namespace);
                }
            }
        }
        _namespaces = null;
    }
References System.Xml.Serialization.XmlSerializationWriter._namespaces, System.Xml.Dictionary, System.SR.Format(), System.Xml.Schema.Length, System.Xml.Serialization.XmlSerializerNamespaces.Namespaces, System.text, System.Xml.Serialization.XmlSerializerNamespaces.TryLookupNamespace(), and System.SR.XmlDuplicateNs.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteStructMethod().