Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw
WriteElementStringRaw() [7/8]
void System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw (string localName, string? value) inline protected
Definition at line 1196 of file XmlSerializationWriter.cs.
    {
        WriteElementStringRaw(localName, null, value, null);
    }
References System.value, and System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw().
Referenced by System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_boolean(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_byte(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTime(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTimeOffset(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_decimal(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_double(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_float(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_guid(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_int(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_long(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_short(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_TimeSpan(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedByte(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedInt(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedLong(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedShort(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringEncodedRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringEncodedRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringLiteralRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringLiteralRaw(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WritePrimitive().