Terraria: System.Xml.Serialization.XmlSerializationWriter.WritePotentiallyReferencingElement
WritePotentiallyReferencingElement() [4/4]
void System.Xml.Serialization.XmlSerializationWriter.WritePotentiallyReferencingElement (string? n, string? ns, object? o, Type? ambientType, bool suppressReference, bool isNullable) inline protected
Definition at line 1454 of file XmlSerializationWriter.cs.
    {
        if (o == null)
        {
            if (isNullable)
            {
                WriteNullTagEncoded(n, ns);
            }
            return;
        }
        Type type = o.GetType();
        if (Type.GetTypeCode(type) == TypeCode.Object && !(o is Guid) && type != typeof(XmlQualifiedName) && !(o is XmlNode[]) && type != typeof(byte[]))
        {
            if ((suppressReference || _soap12) && !IsIdDefined(o))
            {
                WriteReferencedElement(n, ns, o, ambientType);
            }
            else if (n == null)
            {
                TypeEntry typeEntry = GetTypeEntry(type);
                WriteReferencingElement(typeEntry.typeName, typeEntry.typeNs, o, isNullable);
            }
            else
            {
                WriteReferencingElement(n, ns, o, isNullable);
            }
            return;
        }
        bool flag = type != ambientType && !type.IsEnum;
        TypeEntry typeEntry2 = GetTypeEntry(type);
        if (typeEntry2 != null)
        {
            if (n == null)
            {
                WriteStartElement(typeEntry2.typeName, typeEntry2.typeNs, null, writePrefixed: true);
            }
            else
            {
                WriteStartElement(n, ns, null, writePrefixed: true);
            }
            if (flag)
            {
                WriteXsiType(typeEntry2.typeName, typeEntry2.typeNs);
            }
            typeEntry2.callback(o);
            _w.WriteEndElement();
        }
        else
        {
            WriteTypedPrimitive(n, ns, o, flag);
        }
    }
References System.Xml.Serialization.XmlSerializationWriter._soap12, System.Xml.Serialization.XmlSerializationWriter._w, System.Xml.Dictionary, System.Type.GetTypeCode(), System.Xml.Serialization.XmlSerializationWriter.GetTypeEntry(), System.Xml.Serialization.XmlSerializationWriter.IsIdDefined(), System.type, System.Xml.XmlWriter.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriter.WriteNullTagEncoded(), System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElement(), System.Xml.Serialization.XmlSerializationWriter.WriteReferencingElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(), and System.Xml.Serialization.XmlSerializationWriter.WriteXsiType().