Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteStartDocument
WriteStartDocument()
void System.Xml.Serialization.XmlSerializationWriter.WriteStartDocument () inline protected
Definition at line 1157 of file XmlSerializationWriter.cs.
    {
        if (_w.WriteState == WriteState.Start)
        {
            _w.WriteStartDocument();
        }
    }
References System.Xml.Serialization.XmlSerializationWriter._w, System.Xml.XmlWriter.WriteStartDocument(), and System.Xml.XmlWriter.WriteState.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateMembersElement(), System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_base64Binary(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_boolean(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_byte(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_char(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTime(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTimeOffset(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_decimal(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_double(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_float(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_guid(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_int(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_long(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_QName(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_short(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_string(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_TimeSpan(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedByte(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedInt(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedLong(), and System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedShort().