Terraria: System.Xml.Serialization.XmlSerializationWriter.GetQualifiedName
GetQualifiedName()
string System.Xml.Serialization.XmlSerializationWriter.GetQualifiedName (string name, string ns) inline private
Definition at line 463 of file XmlSerializationWriter.cs.
    {
        if (ns == null || ns.Length == 0)
        {
            return name;
        }
        string text = _w.LookupPrefix(ns);
        if (text == null)
        {
            if (ns == "http://www.w3.org/XML/1998/namespace")
            {
                text = "xml";
            }
            else
            {
                text = NextPrefix();
                WriteAttribute("xmlns", text, null, ns);
            }
        }
        else if (text.Length == 0)
        {
            return name;
        }
        return text + ":" + name;
    }
References System.Xml.Serialization.XmlSerializationWriter._w, System.Xml.XmlWriter.LookupPrefix(), System.Xml.Serialization.XmlSerializationWriter.NextPrefix(), System.text, and System.Xml.Serialization.XmlSerializationWriter.WriteAttribute().
Referenced by System.Xml.Serialization.XmlSerializationWriter.FromXmlQualifiedName(), System.Xml.Serialization.XmlSerializationWriter.WriteArray(), and System.Xml.Serialization.XmlSerializationWriter.WriteXsiType().