Terraria: System.Xml.Serialization.XmlSerializationWriter.GetPrimitiveTypeNameInternal
GetPrimitiveTypeNameInternal()
static XmlQualifiedName System.Xml.Serialization.XmlSerializationWriter.GetPrimitiveTypeNameInternal (Type type) inline static package
Definition at line 197 of file XmlSerializationWriter.cs.
    {
        string ns = "http://www.w3.org/2001/XMLSchema";
        string name;
        switch (Type.GetTypeCode(type))
        {
        case TypeCode.String:
            name = "string";
            break;
        case TypeCode.Int32:
            name = "int";
            break;
        case TypeCode.Boolean:
            name = "boolean";
            break;
        case TypeCode.Int16:
            name = "short";
            break;
        case TypeCode.Int64:
            name = "long";
            break;
        case TypeCode.Single:
            name = "float";
            break;
        case TypeCode.Double:
            name = "double";
            break;
        case TypeCode.Decimal:
            name = "decimal";
            break;
        case TypeCode.DateTime:
            name = "dateTime";
            break;
        case TypeCode.Byte:
            name = "unsignedByte";
            break;
        case TypeCode.SByte:
            name = "byte";
            break;
        case TypeCode.UInt16:
            name = "unsignedShort";
            break;
        case TypeCode.UInt32:
            name = "unsignedInt";
            break;
        case TypeCode.UInt64:
            name = "unsignedLong";
            break;
        case TypeCode.Char:
            name = "char";
            ns = "http://microsoft.com/wsdl/types/";
            break;
        default:
            if (type == typeof(XmlQualifiedName))
            {
                name = "QName";
                break;
            }
            if (type == typeof(byte[]))
            {
                name = "base64Binary";
                break;
            }
            if (type == typeof(Guid))
            {
                name = "guid";
                ns = "http://microsoft.com/wsdl/types/";
                break;
            }
            if (type == typeof(TimeSpan))
            {
                name = "TimeSpan";
                ns = "http://microsoft.com/wsdl/types/";
                break;
            }
            if (type == typeof(DateTimeOffset))
            {
                name = "dateTimeOffset";
                ns = "http://microsoft.com/wsdl/types/";
                break;
            }
            if (type == typeof(XmlNode[]))
            {
                name = "anyType";
                break;
            }
            return null;
        }
        return new XmlQualifiedName(name, ns);
    }
References System.Xml.Dictionary, System.Type.GetTypeCode(), and System.type.
Referenced by System.Xml.Serialization.XmlSerializationWriter.GetPrimitiveTypeName(), and System.Xml.Serialization.XmlSerializationReader.ReadArray().