Terraria: System.Xml.Serialization.XmlSerializationWriter.TopLevelElement
TopLevelElement()
void System.Xml.Serialization.XmlSerializationWriter.TopLevelElement () inline protected
Definition at line 1567 of file XmlSerializationWriter.cs.
    {
        _objectsInUse = new Hashtable();
    }
References System.Xml.Serialization.XmlSerializationWriter._objectsInUse.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateMembersElement(), System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_base64Binary(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_QName(), and System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_string().