Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteXmlAttribute
WriteXmlAttribute() [2/2]
void System.Xml.Serialization.XmlSerializationWriter.WriteXmlAttribute (XmlNode node, object? container) inline protected
Definition at line 1031 of file XmlSerializationWriter.cs.
    {
        if (!(node is XmlAttribute xmlAttribute))
        {
            throw new InvalidOperationException(System.SR.XmlNeedAttributeHere);
        }
        if (xmlAttribute.Value != null)
        {
            if (xmlAttribute.NamespaceURI == "http://schemas.xmlsoap.org/wsdl/" && xmlAttribute.LocalName == "arrayType")
            {
                string dims;
                XmlQualifiedName xmlQualifiedName = TypeScope.ParseWsdlArrayType(xmlAttribute.Value, out dims, (container is XmlSchemaObject) ? ((XmlSchemaObject)container) : null);
                string value = FromXmlQualifiedName(xmlQualifiedName, ignoreEmpty: true) + dims;
                WriteAttribute("arrayType", "http://schemas.xmlsoap.org/wsdl/", value);
            }
            else
            {
                WriteAttribute(xmlAttribute.Name, xmlAttribute.NamespaceURI, xmlAttribute.Value);
            }
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationWriter.FromXmlQualifiedName(), System.Xml.Serialization.TypeScope.ParseWsdlArrayType(), System.value, System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(), and System.SR.XmlNeedAttributeHere.