Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteArray
WriteArray()
void System.Xml.Serialization.XmlSerializationWriter.WriteArray (string name, string ns, object o, Type type) inline private
Definition at line 1310 of file XmlSerializationWriter.cs.
    {
        Type arrayElementType = TypeScope.GetArrayElementType(type, null);
        StringBuilder stringBuilder = new StringBuilder();
        if (!_soap12)
        {
            while ((arrayElementType.IsArray || typeof(IEnumerable).IsAssignableFrom(arrayElementType)) && GetPrimitiveTypeName(arrayElementType, throwIfUnknown: false) == null)
            {
                arrayElementType = TypeScope.GetArrayElementType(arrayElementType, null);
                stringBuilder.Append("[]");
            }
        }
        string text;
        string ns2;
        if (arrayElementType == typeof(object))
        {
            text = "anyType";
            ns2 = "http://www.w3.org/2001/XMLSchema";
        }
        else
        {
            TypeEntry typeEntry = GetTypeEntry(arrayElementType);
            if (typeEntry != null)
            {
                text = typeEntry.typeName;
                ns2 = typeEntry.typeNs;
            }
            else if (_soap12)
            {
                XmlQualifiedName primitiveTypeName = GetPrimitiveTypeName(arrayElementType, throwIfUnknown: false);
                if (primitiveTypeName != null)
                {
                    text = primitiveTypeName.Name;
                    ns2 = primitiveTypeName.Namespace;
                }
                else
                {
                    Type baseType = arrayElementType.BaseType;
                    while (baseType != null)
                    {
                        typeEntry = GetTypeEntry(baseType);
                        if (typeEntry != null)
{
                            break;
                        }
                        baseType = baseType.BaseType;
                    }
                    if (typeEntry != null)
                    {
                        text = typeEntry.typeName;
                        ns2 = typeEntry.typeNs;
                    }
                    else
                    {
                        text = "anyType";
                        ns2 = "http://www.w3.org/2001/XMLSchema";
                    }
                }
            }
            else
            {
                XmlQualifiedName primitiveTypeName2 = GetPrimitiveTypeName(arrayElementType);
                text = primitiveTypeName2.Name;
                ns2 = primitiveTypeName2.Namespace;
            }
        }
        if (stringBuilder.Length > 0)
        {
            text += stringBuilder.ToString();
        }
        if (_soap12 && name != null && name.Length > 0)
        {
            WriteStartElement(name, ns, null, writePrefixed: false);
        }
        else
        {
            WriteStartElement("Array", "http://schemas.xmlsoap.org/soap/encoding/", null, writePrefixed: true);
        }
        WriteId(o, addToReferencesList: false);
        if (type.IsArray)
        {
            Array array = (Array)o;
            int length = array.Length;
            if (_soap12)
            {
                _w.WriteAttributeString("itemType", "http://www.w3.org/2003/05/soap-encoding", GetQualifiedName(text, ns2));
                _w.WriteAttributeString("arraySize", "http://www.w3.org/2003/05/soap-encoding", length.ToString(CultureInfo.InvariantCulture));
            }
            else
            {
                _w.WriteAttributeString("arrayType", "http://schemas.xmlsoap.org/soap/encoding/", $"{GetQualifiedName(text, ns2)}[{length}]");
            }
            for (int i = 0; i < length; i++)
            {
                WritePotentiallyReferencingElement("Item", "", array.GetValue(i), arrayElementType, suppressReference: false, isNullable: true);
            }
        }
        else
        {
            int num = (typeof(ICollection).IsAssignableFrom(type) ? ((ICollection)o).Count : (-1));
            if (_soap12)
            {
                _w.WriteAttributeString("itemType", "http://www.w3.org/2003/05/soap-encoding", GetQualifiedName(text, ns2));
                if (num >= 0)
                {
                    _w.WriteAttributeString("arraySize", "http://www.w3.org/2003/05/soap-encoding", num.ToString(CultureInfo.InvariantCulture));
                }
            }
            else
            {
                string text2 = ((num >= 0) ? ("[" + num + "]") : "[]");
                _w.WriteAttributeString("arrayType", "http://schemas.xmlsoap.org/soap/encoding/", GetQualifiedName(text, ns2) + text2);
            }
            IEnumerator enumerator = ((IEnumerable)o).GetEnumerator();
            if (enumerator != null)
            {
                while (enumerator.MoveNext())
                {
                    WritePotentiallyReferencingElement("Item", "", enumerator.Current, arrayElementType, suppressReference: false, isNullable: true);
                }
            }
        }
        _w.WriteEndElement();
    }
References System.Xml.Serialization.XmlSerializationWriter._soap12, System.Xml.Serialization.XmlSerializationWriter._w, System.array, System.Xml.Serialization.Array, System.Xml.Dictionary, System.Xml.Serialization.TypeScope.GetArrayElementType(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Xml.Serialization.XmlSerializationWriter.GetPrimitiveTypeName(), System.Xml.Serialization.XmlSerializationWriter.GetQualifiedName(), System.Xml.Serialization.XmlSerializationWriter.GetTypeEntry(), System.Globalization.CultureInfo.InvariantCulture, System.length, System.text, System.type, System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriter.WriteId(), System.Xml.Serialization.XmlSerializationWriter.WritePotentiallyReferencingElement(), and System.Xml.Serialization.XmlSerializationWriter.WriteStartElement().
Referenced by System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElement().