Terraria: System.Xml.Serialization.XmlSerializationWriter.GetId
GetId()
string System.Xml.Serialization.XmlSerializationWriter.GetId (object o, bool addToReferencesList) inline private
Definition at line 987 of file XmlSerializationWriter.cs.
    {
        if (_references == null)
        {
            _references = new Hashtable();
            _referencesToWrite = new ArrayList();
        }
        string text = (string)_references[o];
        if (text == null)
        {
            string idBase = _idBase;
            int num = ++_nextId;
            text = idBase + "id" + num.ToString(CultureInfo.InvariantCulture);
            _references.Add(o, text);
            if (addToReferencesList)
            {
                _referencesToWrite.Add(o);
            }
        }
        return text;
    }
References System.Xml.Serialization.XmlSerializationWriter._idBase, System.Xml.Serialization.XmlSerializationWriter._nextId, System.Xml.Serialization.XmlSerializationWriter._references, System.Xml.Serialization.XmlSerializationWriter._referencesToWrite, System.Collections.Hashtable.Add(), System.Collections.ArrayList.Add(), System.Globalization.CultureInfo.InvariantCulture, and System.text.
Referenced by System.Xml.Serialization.XmlSerializationWriter.WriteId(), and System.Xml.Serialization.XmlSerializationWriter.WriteReferencingElement().