Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteNullTagEncoded
WriteNullTagEncoded() [1/2]
void System.Xml.Serialization.XmlSerializationWriter.WriteNullTagEncoded (string? name) inline protected
Definition at line 649 of file XmlSerializationWriter.cs.
    {
        WriteNullTagEncoded(name, null);
    }
References System.Xml.Serialization.XmlSerializationWriter.WriteNullTagEncoded().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateTypeElement(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElement(), System.Xml.Serialization.XmlSerializationWriter.WriteElement(), System.Xml.Serialization.XmlSerializationWriter.WriteElementEncoded(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableQualifiedNameEncoded(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringEncoded(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringEncodedRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteNullableStringEncodedRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteNullTagEncoded(), System.Xml.Serialization.XmlSerializationWriter.WritePotentiallyReferencingElement(), and System.Xml.Serialization.XmlSerializationWriter.WriteReferencingElement().