Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteAttribute
WriteAttribute() [2/5]
void System.Xml.Serialization.XmlSerializationWriter.WriteAttribute (string localName, string ns, byte?[] value) inline protected
Definition at line 1083 of file XmlSerializationWriter.cs.
    {
        if (value == null || !(localName != "xmlns") || localName.StartsWith("xmlns:", StringComparison.Ordinal))
        {
            return;
        }
        int num = localName.IndexOf(':');
        if (num < 0)
        {
            if (ns == "http://www.w3.org/XML/1998/namespace")
            {
                string text = _w.LookupPrefix(ns);
                if (text == null || text.Length == 0)
                {
                    text = "xml";
                }
                _w.WriteStartAttribute("xml", localName, ns);
            }
            else
            {
                _w.WriteStartAttribute(null, localName, ns);
            }
        }
        else
        {
            string prefix = _w.LookupPrefix(ns);
            _w.WriteStartAttribute(prefix, localName.Substring(num + 1), ns);
        }
        XmlCustomFormatter.WriteArrayBase64(_w, value, 0, value.Length);
        _w.WriteEndAttribute();
    }
References System.Xml.Serialization.XmlSerializationWriter._w, System.Xml.XmlWriter.LookupPrefix(), System.prefix, System.text, System.value, System.Xml.Serialization.XmlCustomFormatter.WriteArrayBase64(), System.Xml.XmlWriter.WriteEndAttribute(), and System.Xml.XmlWriter.WriteStartAttribute().