Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteStartElement
WriteStartElement() [6/6]
void System.Xml.Serialization.XmlSerializationWriter.WriteStartElement (string name, string? ns, object? o, bool writePrefixed, XmlSerializerNamespaces? xmlns) inline protected
Definition at line 532 of file XmlSerializationWriter.cs.
    {
        if (o != null && _objectsInUse != null)
        {
            if (_objectsInUse.ContainsKey(o))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlCircularReference, o.GetType().FullName));
            }
            _objectsInUse.Add(o, o);
        }
        string prefix = null;
        bool flag = false;
        if (_namespaces != null)
        {
            _namespaces.TryLookupPrefix(ns, out prefix);
            if (_namespaces.TryLookupNamespace("", out var ns2))
            {
                if (string.IsNullOrEmpty(ns2))
                {
                    flag = true;
                }
                if (ns != ns2)
                {
                    writePrefixed = true;
                }
            }
            _usedPrefixes = ListUsedPrefixes(_namespaces, _aliasBase);
        }
        if (writePrefixed && prefix == null && ns != null && ns.Length > 0)
        {
            prefix = _w.LookupPrefix(ns);
            if (prefix == null || prefix.Length == 0)
            {
                prefix = NextPrefix();
            }
        }
        if (prefix == null)
        {
            xmlns?.TryLookupPrefix(ns, out prefix);
        }
        if (flag && prefix == null && ns != null && ns.Length != 0)
        {
            prefix = NextPrefix();
        }
        _w.WriteStartElement(prefix, name, ns);
        if (_namespaces != null)
        {
            foreach (XmlQualifiedName namespace2 in _namespaces.Namespaces)
            {
                string name2 = namespace2.Name;
                string @namespace = namespace2.Namespace;
                if (name2.Length == 0 && (@namespace == null || @namespace.Length == 0))
                {
                    continue;
                }
                if (@namespace == null || @namespace.Length == 0)
                {
                    if (name2.Length > 0)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidXmlns, name2));
                    }
                    WriteAttribute("xmlns", name2, null, @namespace);
                }
                else if (_w.LookupPrefix(@namespace) == null)
                {
                    if (prefix == null && name2.Length == 0)
                    {
                        break;
                    }
                    WriteAttribute("xmlns", name2, null, @namespace);
                }
            }
        }
        WriteNamespaceDeclarations(xmlns);
    }
References System.Xml.Serialization.XmlSerializationWriter._aliasBase, System.Xml.Serialization.XmlSerializationWriter._namespaces, System.Xml.Serialization.XmlSerializationWriter._objectsInUse, System.Xml.Serialization.XmlSerializationWriter._usedPrefixes, System.Xml.Serialization.XmlSerializationWriter._w, System.Collections.Hashtable.Add(), System.Collections.Hashtable.ContainsKey(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Schema.Length, System.Xml.Serialization.XmlSerializationWriter.ListUsedPrefixes(), System.Xml.XmlWriter.LookupPrefix(), System.Xml.Serialization.XmlSerializerNamespaces.Namespaces, System.Xml.Serialization.XmlSerializationWriter.NextPrefix(), System.prefix, System.Xml.Serialization.XmlSerializerNamespaces.TryLookupNamespace(), System.Xml.Serialization.XmlSerializerNamespaces.TryLookupPrefix(), System.Xml.Serialization.XmlSerializationWriter.WriteNamespaceDeclarations(), System.Xml.XmlWriter.WriteStartElement(), System.SR.XmlCircularReference, and System.SR.XmlInvalidXmlns.