Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteEmptyTag
WriteEmptyTag() [1/2]
void System.Xml.Serialization.XmlSerializationWriter.WriteEmptyTag (string? name) inline protected
Definition at line 679 of file XmlSerializationWriter.cs.
    {
        WriteEmptyTag(name, null);
    }
References System.Xml.Serialization.XmlSerializationWriter.WriteEmptyTag().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_boolean(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_byte(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_char(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTime(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTimeOffset(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_decimal(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_double(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_float(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_guid(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_int(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_long(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_short(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_TimeSpan(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedByte(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedInt(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedLong(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedShort(), and System.Xml.Serialization.XmlSerializationWriter.WriteEmptyTag().