Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElements
WriteReferencedElements()
void System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElements () inline protected
Definition at line 1556 of file XmlSerializationWriter.cs.
    {
        if (_referencesToWrite != null)
        {
            for (int i = 0; i < _referencesToWrite.Count; i++)
            {
                WriteReferencedElement(_referencesToWrite[i], null);
            }
        }
    }
References System.Xml.Serialization.XmlSerializationWriter._referencesToWrite, System.Collections.ArrayList.Count, and System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElement().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateMembersElement(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateTypeElement().