Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteStartElement
WriteStartElement() [1/6]
void System.Xml.Serialization.XmlSerializationWriter.WriteStartElement (string name) inline protected
Definition at line 507 of file XmlSerializationWriter.cs.
    {
        WriteStartElement(name, null, null, writePrefixed: false, null);
    }
References System.Xml.Serialization.XmlSerializationWriter.WriteStartElement().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationWriter.WriteArray(), System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteElement(), System.Xml.Serialization.XmlSerializationWriter.WriteElementQualifiedName(), System.Xml.Serialization.XmlSerializationWriter.WriteEmptyTag(), System.Xml.Serialization.XmlSerializationWriter.WriteNullTagEncoded(), System.Xml.Serialization.XmlSerializationWriter.WriteNullTagLiteral(), System.Xml.Serialization.XmlSerializationWriter.WritePotentiallyReferencingElement(), System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElement(), System.Xml.Serialization.XmlSerializationWriter.WriteReferencingElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), and System.Xml.Serialization.ReflectionXmlSerializationWriter.WriteStructMethod().