Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteAttribute
WriteAttribute() [3/5]
void System.Xml.Serialization.XmlSerializationWriter.WriteAttribute (string localName, string? ns, string? value) inline protected
Definition at line 1053 of file XmlSerializationWriter.cs.
    {
        if (value == null || !(localName != "xmlns") || localName.StartsWith("xmlns:", StringComparison.Ordinal))
        {
            return;
        }
        int num = localName.IndexOf(':');
        if (num < 0)
        {
            if (ns == "http://www.w3.org/XML/1998/namespace")
            {
                string text = _w.LookupPrefix(ns);
                if (text == null || text.Length == 0)
                {
                    text = "xml";
                }
                _w.WriteAttributeString(text, localName, ns, value);
            }
            else
            {
                _w.WriteAttributeString(localName, ns, value);
            }
        }
        else
        {
            string prefix = localName.Substring(0, num);
            _w.WriteAttributeString(prefix, localName.Substring(num + 1), ns, value);
        }
    }
References System.Xml.Serialization.XmlSerializationWriter._w, System.Xml.XmlWriter.LookupPrefix(), System.prefix, System.text, System.value, and System.Xml.XmlWriter.WriteAttributeString().
Referenced by System.Xml.Serialization.XmlSerializationWriter.GetQualifiedName(), System.Xml.Serialization.XmlSerializationWriter.WriteElementQualifiedName(), System.Xml.Serialization.XmlSerializationWriter.WriteXmlAttribute(), and System.Xml.Serialization.XmlSerializationWriter.WriteXsiType().