Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElement
WriteReferencedElement() [2/2]
void System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElement (string name, string ns, object o, Type ambientType) inline private
Definition at line 1514 of file XmlSerializationWriter.cs.
    {
        if (name == null)
        {
            name = string.Empty;
        }
        Type type = o.GetType();
        if (type.IsArray || typeof(IEnumerable).IsAssignableFrom(type))
        {
            WriteArray(name, ns, o, type);
            return;
        }
        TypeEntry typeEntry = GetTypeEntry(type);
        if (typeEntry == null)
        {
            throw CreateUnknownTypeException(type);
        }
        WriteStartElement((name.Length == 0) ? typeEntry.typeName : name, (ns == null) ? typeEntry.typeNs : ns, null, writePrefixed: true);
        WriteId(o, addToReferencesList: false);
        if (ambientType != type)
        {
            WriteXsiType(typeEntry.typeName, typeEntry.typeNs);
        }
        typeEntry.callback(o);
        _w.WriteEndElement();
    }
References System.Xml.Serialization.XmlSerializationWriter._w, System.Xml.Serialization.XmlSerializationWriter.CreateUnknownTypeException(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationWriter.GetTypeEntry(), System.type, System.Xml.Serialization.XmlSerializationWriter.WriteArray(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriter.WriteId(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), and System.Xml.Serialization.XmlSerializationWriter.WriteXsiType().