Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteElement
WriteElement()
void System.Xml.Serialization.XmlSerializationWriter.WriteElement (XmlNode node, string name, string ns, bool isNullable, bool any) inline private
Definition at line 859 of file XmlSerializationWriter.cs.
    {
        if (typeof(XmlAttribute).IsAssignableFrom(node.GetType()))
        {
            throw new InvalidOperationException(System.SR.XmlNoAttributeHere);
        }
        if (node is XmlDocument)
        {
            node = ((XmlDocument)node).DocumentElement;
            if (node == null)
            {
                if (isNullable)
                {
                    WriteNullTagEncoded(name, ns);
                }
                return;
            }
        }
        if (any)
        {
            if (node is XmlElement && name != null && name.Length > 0 && (node.LocalName != name || node.NamespaceURI != ns))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlElementNameMismatch, node.LocalName, node.NamespaceURI, name, ns));
            }
        }
        else
        {
            _w.WriteStartElement(name, ns);
        }
        node.WriteTo(_w);
        if (!any)
        {
            _w.WriteEndElement();
        }
    }
References System.Xml.Serialization.XmlSerializationWriter._w, System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriter.WriteNullTagEncoded(), System.Xml.XmlWriter.WriteStartElement(), System.SR.XmlElementNameMismatch, and System.SR.XmlNoAttributeHere.
Referenced by System.Xml.Serialization.XmlSerializationWriter.WriteElementEncoded(), and System.Xml.Serialization.XmlSerializationWriter.WriteElementLiteral().