Terraria: System.Xml.Serialization.XmlSerializationWriter.WriteElementQualifiedName
WriteElementQualifiedName() [2/4]
void System.Xml.Serialization.XmlSerializationWriter.WriteElementQualifiedName (string localName, string? ns, XmlQualifiedName? value, XmlQualifiedName? xsiType) inline protected
Definition at line 1277 of file XmlSerializationWriter.cs.
    {
        if (!(value == null))
        {
            if (value.Namespace == null || value.Namespace.Length == 0)
            {
                WriteStartElement(localName, ns, null, writePrefixed: true);
                WriteAttribute("xmlns", "");
            }
            else
            {
                _w.WriteStartElement(localName, ns);
            }
            if (xsiType != null)
            {
                WriteXsiType(xsiType.Name, xsiType.Namespace);
            }
            _w.WriteString(FromXmlQualifiedName(value, ignoreEmpty: false));
            _w.WriteEndElement();
        }
    }
References System.Xml.Serialization.XmlSerializationWriter._w, System.Xml.Serialization.XmlSerializationWriter.FromXmlQualifiedName(), System.value, System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Xml.XmlWriter.WriteString(), and System.Xml.Serialization.XmlSerializationWriter.WriteXsiType().