Terraria: System.Net.Http.CreditManager.TryRequestCreditNoLock
TryRequestCreditNoLock()
int System.Net.Http.CreditManager.TryRequestCreditNoLock (int amount) inline private
Definition at line 125 of file CreditManager.cs.
    {
        if (_disposed)
        {
            throw new ObjectDisposedException($"{"CreditManager"}:{_owner.GetType().Name}:{_name}");
        }
        if (_current > 0)
        {
            int num = Math.Min(amount, _current);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                _owner.Trace($"{_name}. requested={amount}, current={_current}, granted={num}", "TryRequestCreditNoLock");
            }
            _current -= num;
            return num;
        }
        return 0;
    }
References System.Net.Http.CreditManager._current, System.Net.Http.CreditManager._disposed, System.Net.Http.CreditManager._owner, System.Net.NetEventSource.Log, System.Math.Min(), and System.Net.Http.IHttpTrace.Trace().
Referenced by System.Net.Http.CreditManager.RequestCreditAsync().