Terraria: System.Net.Http.CreditManager.RequestCreditAsync
RequestCreditAsync()
ValueTask< int > System.Net.Http.CreditManager.RequestCreditAsync (int amount, CancellationToken cancellationToken) inline
Definition at line 33 of file CreditManager.cs.
    {
        lock (SyncObject)
        {
            int num = TryRequestCreditNoLock(amount);
            if (num > 0)
            {
                return new ValueTask<int>(num);
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                _owner.Trace($"{_name}. requested={amount}, no credit available.", "RequestCreditAsync");
            }
            CreditWaiter creditWaiter = new CreditWaiter(cancellationToken);
            creditWaiter.Amount = amount;
            if (_waitersTail == null)
            {
                _waitersTail = (creditWaiter.Next = creditWaiter);
            }
            else
            {
                creditWaiter.Next = _waitersTail.Next;
                _waitersTail.Next = creditWaiter;
                _waitersTail = creditWaiter;
            }
            return creditWaiter.AsValueTask();
        }
    }
References System.Net.Http.CreditManager._owner, System.Net.Http.CreditManager._waitersTail, System.Net.Http.CreditWaiter.AsValueTask(), System.cancellationToken, System.Net.NetEventSource.Log, System.Net.Http.CreditWaiter.Next, System.Net.Http.CreditManager.SyncObject, System.Net.Http.IHttpTrace.Trace(), and System.Net.Http.CreditManager.TryRequestCreditNoLock().
Referenced by System.Net.Http.Http2Connection.SendStreamDataAsync().