Terraria: DataSetUtil.InvalidOperation
InvalidOperation()
static InvalidOperationException DataSetUtil.InvalidOperation (string message) inline static package
Definition at line 59 of file DataSetUtil.cs.
    {
        return TraceExceptionAsReturnValue(new InvalidOperationException(message));
    }
Referenced by System.Data.DataRowComparer< TRow >.Equals(), System.Data.LinqDataView.FindByKey(), System.Data.LinqDataView.FindByKey(), System.Data.LinqDataView.FindRowsByKey(), System.Data.DataRowComparer< TRow >.GetHashCode(), and System.Data.DataTableExtensions.LoadTableFromEnumerable< T >().