Terraria: System.Net.Http.CreditManager.AdjustCredit
AdjustCredit()
void System.Net.Http.CreditManager.AdjustCredit (int amount) inline
Definition at line 62 of file CreditManager.cs.
    {
        lock (SyncObject)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                _owner.Trace($"{_name}. {"amount"}={amount}, current={_current}", "AdjustCredit");
            }
            if (_disposed)
            {
                return;
            }
            checked
            {
                _current += amount;
            }
            while (_current > 0 && _waitersTail != null)
            {
                CreditWaiter next = _waitersTail.Next;
                int num = Math.Min(next.Amount, _current);
                if (next.Next == next)
                {
                    _waitersTail = null;
                }
                else
                {
                    _waitersTail.Next = next.Next;
                }
                next.Next = null;
                if (next.TrySetResult(num))
                {
                    _current -= num;
                }
                next.Dispose();
            }
        }
    }
References System.Net.Http.CreditManager._current, System.Net.Http.CreditManager._disposed, System.Net.Http.CreditManager._owner, System.Net.Http.CreditManager._waitersTail, System.Net.Http.CreditWaiter.Amount, System.Net.Http.CreditWaiter.Dispose(), System.Net.NetEventSource.Log, System.Math.Min(), System.Net.Http.CreditWaiter.Next, System.Net.Http.CreditManager.SyncObject, System.Net.Http.IHttpTrace.Trace(), and System.Net.Http.CreditWaiter.TrySetResult().
Referenced by System.Net.Http.Http2Connection.ProcessWindowUpdateFrame(), and System.Net.Http.Http2Connection.SendStreamDataAsync().