Terraria: Terraria.GameContent.UI.Elements.UIItemIcon.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIItemIcon.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 21 of file UIItemIcon.cs.
    {
        CalculatedStyle dimensions = GetDimensions();
        ItemSlot.DrawItemIcon(_item, 31, spriteBatch, dimensions.Center(), _item.scale, 32f, _blackedOut ? Color.Black : Color.White);
    }
References Terraria.GameContent.UI.Elements.UIItemIcon._blackedOut, Terraria.GameContent.UI.Elements.UIItemIcon._item, Terraria.UI.CalculatedStyle.Center(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.UI.UIElement.GetDimensions(), and Terraria.Item.scale.