Terraria: System.Xml.LineInfo.Set
Set()
void System.Xml.LineInfo.Set (int lineNo, int linePos) inline
Definition at line 15 of file LineInfo.cs.
    {
        this.lineNo = lineNo;
        this.linePos = linePos;
    }
References System.Xml.Dictionary, System.Xml.LineInfo.lineNo, and System.Xml.LineInfo.linePos.
Referenced by System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.InitIncrementalRead(), System.Xml.XmlTextReaderImpl.InitReadContentAsBinary(), System.Xml.XmlTextReaderImpl.InitReadContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinary(), System.Xml.XmlTextReaderImpl.InitReadElementContentAsBinaryAsync(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ReadContentAsBinary(), System.Xml.XmlTextReaderImpl.ReadContentAsBinaryAsync(), System.Xml.DtdParser.ScanLiteral(), System.Xml.DtdParser.ScanLiteralAsync(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo(), System.Xml.XmlTextReaderImpl.NodeData.SetLineInfo2(), and System.Xml.XmlTextReaderImpl.SetupEndEntityNodeInContent().