Terraria: System.Collections.Concurrent.ConcurrentBag.TrySteal
TrySteal()
bool System.Collections.Concurrent.ConcurrentBag< T >.TrySteal ([MaybeNullWhen(false)] out T result, bool take) inline private
Definition at line 487 of file ConcurrentBag.cs.
    {
        if (CDSCollectionETWBCLProvider.Log.IsEnabled())
        {
            if (take)
            {
                CDSCollectionETWBCLProvider.Log.ConcurrentBag_TryTakeSteals();
            }
            else
            {
                CDSCollectionETWBCLProvider.Log.ConcurrentBag_TryPeekSteals();
            }
        }
        while (true)
        {
            long num = Interlocked.Read(ref _emptyToNonEmptyListTransitionCount);
            WorkStealingQueue currentThreadWorkStealingQueue = GetCurrentThreadWorkStealingQueue(forceCreate: false);
            bool num2;
            if (currentThreadWorkStealingQueue != null)
            {
                if (TryStealFromTo(currentThreadWorkStealingQueue._nextQueue, null, out result, take))
                {
                    goto IL_0078;
                }
                num2 = TryStealFromTo(_workStealingQueues, currentThreadWorkStealingQueue, out result, take);
            }
            else
            {
                num2 = TryStealFromTo(_workStealingQueues, null, out result, take);
            }
            if (!num2)
            {
                if (Interlocked.Read(ref _emptyToNonEmptyListTransitionCount) == num)
                {
                    break;
                }
                continue;
            }
            goto IL_0078;
            IL_0078:
            return true;
        }
        return false;
    }
References System.Collections.Concurrent.ConcurrentBag< T >._emptyToNonEmptyListTransitionCount, System.Collections.Concurrent.ConcurrentBag< T >._workStealingQueues, System.Collections.Concurrent.ConcurrentBag< T >.GetCurrentThreadWorkStealingQueue(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.Log, System.Threading.Interlocked.Read(), and System.Collections.Concurrent.ConcurrentBag< T >.TryStealFromTo().
Referenced by System.Collections.Concurrent.ConcurrentBag< T >.TryPeek(), and System.Collections.Concurrent.ConcurrentBag< T >.TryTake().