Terraria: System.Collections.Concurrent.ConcurrentBag.FreezeBag
FreezeBag()
void System.Collections.Concurrent.ConcurrentBag< T >.FreezeBag (ref bool lockTaken) inline private
Definition at line 674 of file ConcurrentBag.cs.
    {
        Monitor.Enter(GlobalQueuesLock, ref lockTaken);
        WorkStealingQueue workStealingQueues = _workStealingQueues;
        for (WorkStealingQueue workStealingQueue = workStealingQueues; workStealingQueue != null; workStealingQueue = workStealingQueue._nextQueue)
        {
            Monitor.Enter(workStealingQueue, ref workStealingQueue._frozen);
        }
        Interlocked.MemoryBarrier();
        for (WorkStealingQueue workStealingQueue2 = workStealingQueues; workStealingQueue2 != null; workStealingQueue2 = workStealingQueue2._nextQueue)
        {
            if (workStealingQueue2._currentOp != 0)
            {
                SpinWait spinWait = default(SpinWait);
                do
                {
                    spinWait.SpinOnce();
                }
                while (workStealingQueue2._currentOp != 0);
            }
        }
    }
References System.Collections.Concurrent.ConcurrentBag< T >._workStealingQueues, System.Threading.Monitor.Enter(), System.Collections.Concurrent.ConcurrentBag< T >.GlobalQueuesLock, and System.Threading.Interlocked.MemoryBarrier().
Referenced by System.Collections.Concurrent.ConcurrentBag< T >.Clear(), System.Collections.Concurrent.ConcurrentBag< T >.CopyTo(), and System.Collections.Concurrent.ConcurrentBag< T >.ToArray().