Terraria: System.Collections.Concurrent.ConcurrentBag.CopyTo
CopyTo() [2/2]
void System.Collections.Concurrent.ConcurrentBag< T >.CopyTo (T[] array, int index) inline
Implements System.Collections.Concurrent.IProducerConsumerCollection< T >.
Definition at line 545 of file ConcurrentBag.cs.
    {
        if (array == null)
        {
            throw new ArgumentNullException("array", System.SR.ConcurrentBag_CopyTo_ArgumentNullException);
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index", System.SR.Collection_CopyTo_ArgumentOutOfRangeException);
        }
        if (_workStealingQueues == null)
        {
            return;
        }
        bool lockTaken = false;
        try
        {
            FreezeBag(ref lockTaken);
            int dangerousCount = DangerousCount;
            if (index > array.Length - dangerousCount)
            {
                throw new ArgumentException(System.SR.Collection_CopyTo_TooManyElems, "index");
            }
            try
            {
                int num = CopyFromEachQueueToArray(array, index);
            }
            catch (ArrayTypeMismatchException ex)
            {
                throw new InvalidCastException(ex.Message, ex);
            }
        }
        finally
        {
            UnfreezeBag(lockTaken);
        }
    }
References System.Collections.Concurrent.ConcurrentBag< T >._workStealingQueues, System.array, System.SR.Collection_CopyTo_ArgumentOutOfRangeException, System.SR.Collection_CopyTo_TooManyElems, System.SR.ConcurrentBag_CopyTo_ArgumentNullException, System.Collections.Concurrent.ConcurrentBag< T >.CopyFromEachQueueToArray(), System.Collections.Concurrent.ConcurrentBag< T >.DangerousCount, System.Collections.Concurrent.ConcurrentBag< T >.FreezeBag(), System.index, and System.Collections.Concurrent.ConcurrentBag< T >.UnfreezeBag().
Referenced by System.Collections.Concurrent.ConcurrentBag< T >.CopyTo().