Terraria: System.Collections.Concurrent.ConcurrentBag.Clear
Clear()
void System.Collections.Concurrent.ConcurrentBag< T >.Clear () inline
Definition at line 631 of file ConcurrentBag.cs.
    {
        if (_workStealingQueues == null)
        {
            return;
        }
        WorkStealingQueue currentThreadWorkStealingQueue = GetCurrentThreadWorkStealingQueue(forceCreate: false);
        if (currentThreadWorkStealingQueue != null)
        {
            currentThreadWorkStealingQueue.LocalClear();
            if (currentThreadWorkStealingQueue._nextQueue == null && currentThreadWorkStealingQueue == _workStealingQueues)
            {
                return;
            }
        }
        bool lockTaken = false;
        try
        {
            FreezeBag(ref lockTaken);
            for (WorkStealingQueue workStealingQueue = _workStealingQueues; workStealingQueue != null; workStealingQueue = workStealingQueue._nextQueue)
            {
                T result;
                while (workStealingQueue.TrySteal(out result, take: true))
                {
                }
            }
        }
        finally
        {
            UnfreezeBag(lockTaken);
        }
    }
References System.Collections.Concurrent.ConcurrentBag< T >._workStealingQueues, System.Collections.Concurrent.ConcurrentBag< T >.FreezeBag(), System.Collections.Concurrent.ConcurrentBag< T >.GetCurrentThreadWorkStealingQueue(), and System.Collections.Concurrent.ConcurrentBag< T >.UnfreezeBag().