Terraria: System.Collections.Concurrent.ConcurrentBag.ToArray
ToArray()
T[] System.Collections.Concurrent.ConcurrentBag< T >.ToArray () inline
Implements System.Collections.Concurrent.IProducerConsumerCollection< T >.
Definition at line 607 of file ConcurrentBag.cs.
    {
        if (_workStealingQueues != null)
        {
            bool lockTaken = false;
            try
            {
                FreezeBag(ref lockTaken);
                int dangerousCount = DangerousCount;
                if (dangerousCount > 0)
                {
                    T[] array = new T[dangerousCount];
                    int num = CopyFromEachQueueToArray(array, 0);
                    return array;
                }
            }
            finally
            {
                UnfreezeBag(lockTaken);
            }
        }
        return Array.Empty<T>();
    }
References System.Collections.Concurrent.ConcurrentBag< T >._workStealingQueues, System.array, System.Collections.Concurrent.ConcurrentBag< T >.CopyFromEachQueueToArray(), System.Collections.Concurrent.ConcurrentBag< T >.DangerousCount, System.Collections.Concurrent.ConcurrentBag< T >.FreezeBag(), and System.Collections.Concurrent.ConcurrentBag< T >.UnfreezeBag().
Referenced by System.Collections.Concurrent.ConcurrentBag< T >.CopyTo(), and System.Collections.Concurrent.ConcurrentBag< T >.GetEnumerator().