Terraria: System.Collections.Concurrent.ConcurrentBag.GetCurrentThreadWorkStealingQueue
GetCurrentThreadWorkStealingQueue()
WorkStealingQueue System.Collections.Concurrent.ConcurrentBag< T >.GetCurrentThreadWorkStealingQueue (bool forceCreate) inline private
Definition at line 445 of file ConcurrentBag.cs.
    {
        WorkStealingQueue workStealingQueue = _locals.Value;
        if (workStealingQueue == null)
        {
            if (!forceCreate)
            {
                return null;
            }
            workStealingQueue = CreateWorkStealingQueueForCurrentThread();
        }
        return workStealingQueue;
    }
References System.Collections.Concurrent.ConcurrentBag< T >._locals, and System.Collections.Concurrent.ConcurrentBag< T >.CreateWorkStealingQueueForCurrentThread().
Referenced by System.Collections.Concurrent.ConcurrentBag< T >.ConcurrentBag(), System.Collections.Concurrent.ConcurrentBag< T >.Add(), System.Collections.Concurrent.ConcurrentBag< T >.Clear(), System.Collections.Concurrent.ConcurrentBag< T >.TryPeek(), System.Collections.Concurrent.ConcurrentBag< T >.TrySteal(), and System.Collections.Concurrent.ConcurrentBag< T >.TryTake().