Terraria: System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.TryGetPropertyStoreItem
TryGetPropertyStoreItem()
bool System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.TryGetPropertyStoreItem (string propertyName, [NotNullWhen(true)] out PropertyStoreItem item) inline package
Definition at line 48 of file ValidationAttributeStore.cs.
        {
            if (string.IsNullOrEmpty(propertyName))
            {
                throw new ArgumentNullException("propertyName");
            }
            if (_propertyStoreItems == null)
            {
                lock (_syncRoot)
                {
                    if (_propertyStoreItems == null)
                    {
                        _propertyStoreItems = CreatePropertyStoreItems();
                    }
                }
            }
            return _propertyStoreItems.TryGetValue(propertyName, out item);
        }
References System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem._propertyStoreItems, System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem._syncRoot, System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.CreatePropertyStoreItems(), System.item, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.GetPropertyStoreItem().