Terraria: System.Net.BufferedReadStream.ReadAsyncResult.Read
Read()
void System.Net.BufferedReadStream.ReadAsyncResult.Read (byte[] buffer, int offset, int count) inline package
Definition at line 23 of file BufferedReadStream.cs.
        {
            if (_parent._storedOffset < _parent._storedLength)
            {
                _read = Math.Min(count, _parent._storedLength - _parent._storedOffset);
                Buffer.BlockCopy(_parent._storedBuffer, _parent._storedOffset, buffer, offset, _read);
                _parent._storedOffset += _read;
                if (_read == count || !_parent._readMore)
                {
                    InvokeCallback();
                    return;
                }
                count -= _read;
                offset += _read;
            }
            IAsyncResult asyncResult = _parent.BaseStream.BeginRead(buffer, offset, count, s_onRead, this);
            if (asyncResult.CompletedSynchronously)
            {
                _read += _parent.BaseStream.EndRead(asyncResult);
                InvokeCallback();
            }
        }
References System.Net.BufferedReadStream.ReadAsyncResult._parent, System.Net.BufferedReadStream.ReadAsyncResult._read, System.Net.BufferedReadStream._readMore, System.Net.BufferedReadStream._storedBuffer, System.Net.BufferedReadStream._storedLength, System.Net.BufferedReadStream._storedOffset, System.asyncResult, System.Net.DelegatedStream.BaseStream, System.IO.Stream.BeginRead(), System.Buffer.BlockCopy(), System.buffer, System.count, System.IO.Stream.EndRead(), System.Net.LazyAsyncResult.InvokeCallback(), System.Math.Min(), System.offset, and System.Net.BufferedReadStream.ReadAsyncResult.s_onRead.
Referenced by System.Net.BufferedReadStream.BeginRead().