Terraria: GameSenseConnection._addGUIDefinedEvents
_addGUIDefinedEvents()
void GameSenseConnection._addGUIDefinedEvents () inline private
     {
         //IL_0038: Unknown result type (might be due to invalid IL or missing references)
         if (GameName == null || GameDisplayName == null || Events == null)
         {
             _logWarning("Incomplete game registration form");
             _setClientState((ClientState)2);
         }
         else
         {
             RegisterGame(GameName, GameDisplayName, IconColor);
             RegisterEvents(Events);
         }
     }
References _logWarning(), _setClientState(), Events, GameDisplayName, GameName, IconColor, RegisterEvents(), and RegisterGame().
Referenced by BeginConnection().