Terraria: System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.CreatePropertyStoreItems
CreatePropertyStoreItems()
Dictionary< string, PropertyStoreItem > System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.CreatePropertyStoreItems () inline private
Definition at line 68 of file ValidationAttributeStore.cs.
        {
            Dictionary<string, PropertyStoreItem> dictionary = new Dictionary<string, PropertyStoreItem>();
            PropertyDescriptorCollection properties = TypeDescriptor.GetProperties(_type);
            foreach (PropertyDescriptor item in properties)
            {
                PropertyStoreItem value = new PropertyStoreItem(item.PropertyType, GetExplicitAttributes(item));
                dictionary[item.Name] = value;
            }
            return dictionary;
        }
References System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem._type, System.dictionary, System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.GetExplicitAttributes(), System.ComponentModel.TypeDescriptor.GetProperties(), System.item, and System.value.
Referenced by System.ComponentModel.DataAnnotations.ValidationAttributeStore.TypeStoreItem.TryGetPropertyStoreItem().