Terraria: GameSenseConnection._getServerPort
_getServerPort()
static string GameSenseConnection._getServerPort () inline static private
     {
         //IL_0014: Unknown result type (might be due to invalid IL or missing references)
         //IL_0031: Unknown result type (might be due to invalid IL or missing references)
         string result = null;
         string text = _readProps();
         if (text != null)
         {
             try
             {
                 JObject jObject = JObject.Parse(text);
                 coreProps coreProps = default(coreProps);
                 coreProps.address = (string)jObject.GetValue("address");
                 string[] array = coreProps.address.Split(':');
                 Convert.ToUInt16(array[1]);
                 result = array[1];
                 return result;
             }
             catch (Exception e)
             {
                 _logException("Cannot parse port information", e);
                 return result;
             }
         }
         return result;
     }
References _logException(), and _readProps().
Referenced by _gamesenseWrk().