Terraria: GameSenseConnection._gamesenseWrk
_gamesenseWrk()
void GameSenseConnection._gamesenseWrk () inline private
     {
         //IL_0089: Expected O, but got Unknown
         //IL_00a5: Expected O, but got Unknown
         //IL_010c: Expected O, but got Unknown
         //IL_0014: Unknown result type (might be due to invalid IL or missing references)
         //IL_0019: Unknown result type (might be due to invalid IL or missing references)
         //IL_001a: Unknown result type (might be due to invalid IL or missing references)
         //IL_002c: Expected I4, but got Unknown
         //IL_0046: Unknown result type (might be due to invalid IL or missing references)
         //IL_004c: Expected O, but got Unknown
         //IL_0053: Unknown result type (might be due to invalid IL or missing references)
         //IL_005d: Expected O, but got Unknown
         QueueMsg queueMsg = null;
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         while (_mGameSenseWrkShouldRun)
         {
             ClientState mClientState = _mClientState;
             switch ((int)mClientState)
             {
             case 0:
             {
                 QueueMsg queueMsg2;
                 while ((queueMsg2 = _mMsgQueue.CDequeue()) == null)
                 {
                     Thread.Sleep(10);
                     if (stopwatch.ElapsedMilliseconds > 1000)
                     {
                         queueMsg2 = (QueueMsg)new QueueMsgSendHeartbeat();
                         queueMsg2.data = (object)new Game(GameName);
                         break;
                     }
                 }
                 try
                 {
                     _sendMsg(queueMsg2);
                     stopwatch.Reset();
                     stopwatch.Start();
                 }
                 catch (ServerDownException val2)
                 {
                     ServerDownException e2 = val2;
                     _logException("Failed connecting to GameSense server", (Exception)(object)e2);
                     queueMsg = queueMsg2;
                     _setClientState((ClientState)1);
                 }
                 catch (CriticalMessageIllFormedException val3)
                 {
                     CriticalMessageIllFormedException e3 = val3;
                     _logException("Message ill-formed", (Exception)(object)e3);
                     _setClientState((ClientState)2);
                 }
                 catch (Exception e4)
                 {
                     _logException("Failed processing msg", e4);
                 }
                 break;
             }
             case 1:
                 _mServerPort = _getServerPort();
                 if (_mServerPort == null)
                 {
                     _logWarning("Failed to obtain GameSense server port. GameSense will not function");
                     _setClientState((ClientState)2);
                     break;
                 }
                 _initializeUris();
                 if (queueMsg != null)
                 {
                     try
                     {
                         _sendMsg(queueMsg);
                         queueMsg = null;
                     }
                     catch (ServerDownException val)
                     {
                         ServerDownException e = val;
                         _logException("Failed connecting to GameSense server", (Exception)(object)e);
                         _logDbgMsg("Retrying in 5 seconds...");
                         Thread.Sleep(5000);
                         break;
                     }
                 }
                 _setClientState((ClientState)0);
                 break;
             case 2:
                 _logDbgMsg("Entering inactive state");
                 _mGameSenseWrkShouldRun = false;
                 break;
             default:
                 _logErrorMsg("Unknown GameSense client state");
                 _setClientState((ClientState)2);
                 break;
             }
         }
         _logDbgMsg("Worker exiting");
     }
References _getServerPort(), _initializeUris(), _logDbgMsg(), _logErrorMsg(), _logException(), _logWarning(), _mClientState, _mGameSenseWrkShouldRun, _mMsgQueue, _mServerPort, _sendMsg(), _setClientState(), Game, and GameName.
Referenced by BeginConnection().