Terraria: GameSenseConnection._readProps
_readProps()
static string GameSenseConnection._readProps () inline static private
     {
         string path = _getPropsPath();
         string result = null;
         try
         {
             if (File.Exists(path))
             {
                 result = File.ReadAllText(path);
                 return result;
             }
             _logErrorMsg("Could not read server props file, because it can't be found");
             return result;
         }
         catch (Exception e)
         {
             _logException("Could not read server props file", e);
             return result;
         }
     }
References _getPropsPath(), _logErrorMsg(), and _logException().
Referenced by _getServerPort().