Terraria: System.Xml.XmlText.SplitText
SplitText()
virtual XmlText System.Xml.XmlText.SplitText (int offset) inline virtual
Definition at line 87 of file XmlText.cs.
    {
        XmlNode xmlNode = ParentNode;
        int length = Length;
        if (offset > length)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (xmlNode == null)
        {
            throw new InvalidOperationException(System.SR.Xdom_TextNode_SplitText);
        }
        int count = length - offset;
        string text = Substring(offset, count);
        DeleteData(offset, count);
        XmlText xmlText = OwnerDocument.CreateTextNode(text);
        xmlNode.InsertAfter(xmlText, this);
        return xmlText;
    }
References System.count, System.Xml.XmlDocument.CreateTextNode(), System.Xml.XmlCharacterData.DeleteData(), System.Xml.Dictionary, System.Xml.XmlNode.InsertAfter(), System.length, System.Xml.XmlCharacterData.Length, System.offset, System.Xml.XmlNode.OwnerDocument, System.Xml.XmlText.ParentNode, System.Xml.XmlCharacterData.Substring(), System.text, and System.SR.Xdom_TextNode_SplitText.