Terraria: Terraria.Player.OpenHerbBag
OpenHerbBag()
void Terraria.Player.OpenHerbBag (int bagType) inline
Definition at line 8616 of file Player.cs.
    {
        IEntitySource itemSource_OpenItem = GetItemSource_OpenItem(bagType);
        int num = Main.rand.Next(2, 5);
        if (Main.rand.Next(3) == 0)
        {
            num++;
        }
        for (int i = 0; i < num; i++)
        {
            int num2 = Main.rand.Next(14);
            if (num2 == 0)
            {
                num2 = 313;
            }
            if (num2 == 1)
            {
                num2 = 314;
            }
            if (num2 == 2)
            {
                num2 = 315;
            }
            if (num2 == 3)
            {
                num2 = 317;
            }
            if (num2 == 4)
            {
                num2 = 316;
            }
            if (num2 == 5)
            {
                num2 = 318;
            }
            if (num2 == 6)
            {
                num2 = 2358;
            }
            if (num2 == 7)
            {
                num2 = 307;
            }
            if (num2 == 8)
            {
                num2 = 308;
            }
            if (num2 == 9)
            {
                num2 = 309;
            }
            if (num2 == 10)
            {
                num2 = 311;
            }
            if (num2 == 11)
            {
                num2 = 310;
            }
            if (num2 == 12)
            {
                num2 = 312;
            }
            if (num2 == 13)
            {
                num2 = 2357;
            }
            int num3 = Main.rand.Next(2, 5);
            if (Main.rand.Next(3) == 0)
            {
                num3 += Main.rand.Next(1, 5);
            }
            int number = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, num2, num3);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
        }
    }
References Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.rand, and Terraria.NetMessage.SendData().
Referenced by Terraria.UI.ItemSlot.TryOpenContainer().