Terraria: Terraria.Player.Spawn_ForceClearArea
Spawn_ForceClearArea()
static void Terraria.Player.Spawn_ForceClearArea (int floorX, int floorY) inline static private
Definition at line 35958 of file Player.cs.
    {
        for (int i = floorX - 1; i < floorX + 2; i++)
        {
            for (int j = floorY - 3; j < floorY; j++)
            {
                if (Main.tile[i, j] != null)
                {
                    if (Main.tile[i, j].nactive() && Main.tileSolid[Main.tile[i, j].type] && !Main.tileSolidTop[Main.tile[i, j].type])
                    {
                        WorldGen.KillTile(i, j);
                    }
                    if (Main.tile[i, j].liquid > 0)
                    {
                        Main.tile[i, j].lava(lava: false);
                        Main.tile[i, j].liquid = 0;
                        WorldGen.SquareTileFrame(i, j);
                    }
                }
            }
        }
    }
References Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.