Terraria: Terraria.Player.GamepadEnableGrappleCooldown
GamepadEnableGrappleCooldown()
void Terraria.Player.GamepadEnableGrappleCooldown () inline
Definition at line 23162 of file Player.cs.
    {
        _quickGrappleCooldown = 3;
    }
Referenced by Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction(), Terraria.DataStructures.TileEntity.BasicOpenCloseInteraction(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEItemFrame.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction(), and Terraria.Player.ToggleInv().