Terraria: Terraria.Player.QuickHeal_GetItemToUse
QuickHeal_GetItemToUse()
Item Terraria.Player.QuickHeal_GetItemToUse () inline
    {
        int num = statLifeMax2 - statLife;
        Item result = null;
        int num2 = -statLifeMax2;
        int num3 = 58;
        if (useVoidBag())
        {
            num3 = 98;
        }
        for (int i = 0; i < num3; i++)
        {
            Item item = ((i >= 58) ? bank4.item[i - 58] : inventory[i]);
            if (item.stack <= 0 || item.type <= 0 || !item.potion || item.healLife <= 0)
            {
                continue;
            }
            int num4 = item.healLife - num;
            if (item.type == 227 && num4 < 0)
            {
                num4 += 30;
                if (num4 > 0)
                {
                    num4 = 0;
                }
            }
            if (num2 < 0)
            {
                if (num4 > num2)
                {
                    result = item;
                    num2 = num4;
                }
            }
            else if (num4 < num2 && num4 >= 0)
            {
                result = item;
                num2 = num4;
            }
        }
        return result;
    }
References Terraria.Player.bank4, Terraria.Item.healLife, Terraria.Player.inventory, Terraria.Chest.item, Terraria.Item.potion, Terraria.Item.stack, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Item.type, and Terraria.Player.useVoidBag().
Referenced by Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.Player.QuickHeal(), and Terraria.GameContent.ChromaHotkeyPainter.Step_QuickHeal().