Terraria: Terraria.Player.QuickBuff_PickBestFoodItem
QuickBuff_PickBestFoodItem()
Item Terraria.Player.QuickBuff_PickBestFoodItem () inline private
Definition at line 4912 of file Player.cs.
    {
        int num = 0;
        Item item = null;
        for (int i = 0; i < maxBuffs; i++)
        {
            if (buffTime[i] >= 1)
            {
                int num2 = QuickBuff_FindFoodPriority(buffType[i]);
                if (num <= num2)
                {
                    num = num2 + 1;
                }
            }
        }
        for (int j = 0; j < 58; j++)
        {
            Item item2 = inventory[j];
            if (!item2.IsAir)
            {
                int num3 = QuickBuff_FindFoodPriority(item2.buffType);
                if (num3 >= num && (item == null || item.buffTime < item2.buffTime || num3 > num))
                {
                    item = item2;
                    num = num3;
                }
            }
        }
        if (useVoidBag())
        {
            for (int k = 0; k < 40; k++)
            {
                Item item3 = bank4.item[k];
                if (!item3.IsAir)
                {
                    int num4 = QuickBuff_FindFoodPriority(item3.buffType);
                    if (num4 >= num && (item == null || item.buffTime < item3.buffTime || num4 > num))
                    {
                        item = item3;
                        num = num4;
                    }
                }
            }
        }
        return item;
    }
References Terraria.Player.bank4, Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.Player.inventory, System.item, Terraria.Chest.item, Terraria.Player.maxBuffs, Terraria.Player.QuickBuff_FindFoodPriority(), and Terraria.Player.useVoidBag().
Referenced by Terraria.Player.QuickBuff().