Terraria: Terraria.Player.SetPlayerDataToOutOfClassFields
SetPlayerDataToOutOfClassFields()
void Terraria.Player.SetPlayerDataToOutOfClassFields () inline
Definition at line 51456 of file Player.cs.
    {
        Item mouseItem = new Item();
        if (_temporaryItemSlots[0] != null)
        {
            mouseItem = _temporaryItemSlots[0].Clone();
        }
        Main.mouseItem = mouseItem;
        mouseItem = new Item();
        if (_temporaryItemSlots[1] != null)
        {
            mouseItem = _temporaryItemSlots[1].Clone();
        }
        Main.CreativeMenu.SetItembyIndex(mouseItem, 0);
        mouseItem = new Item();
        if (_temporaryItemSlots[2] != null)
        {
            mouseItem = _temporaryItemSlots[2].Clone();
        }
        Main.guideItem = mouseItem;
        mouseItem = new Item();
        if (_temporaryItemSlots[3] != null)
        {
            mouseItem = _temporaryItemSlots[3].Clone();
        }
        Main.reforgeItem = mouseItem;
        CreativePowerManager.Instance.ApplyLoadedDataToPlayer(this);
    }
References Terraria.GameContent.Creative.CreativePowerManager.ApplyLoadedDataToPlayer(), Terraria.Item.Clone(), Terraria.Main.CreativeMenu, Terraria.GameContent.Creative.CreativePowerManager.Instance, and Terraria.GameContent.Creative.CreativeUI.SetItembyIndex().