Terraria: Terraria.Player.OpenPresent
OpenPresent()
void Terraria.Player.OpenPresent (int itemType) inline
Definition at line 5965 of file Player.cs.
    {
        IEntitySource itemSource_OpenItem = GetItemSource_OpenItem(itemType);
        if (Main.rand.Next(15) == 0 && Main.hardMode)
        {
            int number = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 602);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
            return;
        }
        if (Main.rand.Next(30) == 0)
        {
            int number2 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1922);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number2, 1f);
            }
            return;
        }
        if (Main.rand.Next(400) == 0)
        {
            int number3 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1927);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number3, 1f);
            }
            return;
        }
        if (Main.rand.Next(150) == 0)
        {
            int number4 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1870);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number4, 1f);
            }
            number4 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 97, Main.rand.Next(30, 61));
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number4, 1f);
            }
            return;
        }
        if (Main.rand.Next(150) == 0)
        {
            int number5 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1909);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number5, 1f);
            }
            return;
        }
        if (Main.rand.Next(150) == 0)
        {
            int number6 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1917);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number6, 1f);
            }
            return;
        }
        if (Main.rand.Next(150) == 0)
        {
            int number7 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1915);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number7, 1f);
            }
            return;
        }
        if (Main.rand.Next(150) == 0)
        {
            int number8 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1918);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number8, 1f);
            }
            return;
        }
        if (Main.rand.Next(150) == 0)
        {
            int number9 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1921);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number9, 1f);
            }
            return;
        }
        if (Main.rand.Next(300) == 0)
        {
            int number10 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1923);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number10, 1f);
            }
            return;
        }
        if (Main.rand.Next(40) == 0)
        {
            int number11 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1907);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number11, 1f);
            }
            return;
        }
        if (Main.rand.Next(10) == 0)
        {
            int number12 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1908);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number12, 1f);
            }
            return;
        }
        if (Main.rand.Next(15) == 0)
        {
            switch (Main.rand.Next(5))
            {
            case 0:
            {
                int number14 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1932);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number14, 1f);
                }
                number14 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1933);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number14, 1f);
                }
                number14 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1934);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number14, 1f);
                }
                break;
            }
            case 1:
            {
                int number16 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1935);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number16, 1f);
                }
                number16 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1936);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number16, 1f);
                }
                number16 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1937);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number16, 1f);
                }
                break;
            }
            case 2:
            {
                int number17 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1940);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number17, 1f);
                }
                number17 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1941);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number17, 1f);
                }
                number17 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1942);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number17, 1f);
                }
                break;
            }
            case 3:
            {
                int number15 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1938);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number15, 1f);
                }
                break;
            }
            case 4:
            {
                int number13 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1939);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number13, 1f);
                }
                break;
            }
            }
            return;
        }
        if (Main.rand.Next(7) == 0)
        {
            int num = Main.rand.Next(3);
            if (num == 0)
            {
                num = 1911;
            }
            if (num == 1)
            {
                num = 1919;
            }
            if (num == 2)
            {
                num = 1920;
            }
            int number18 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, num);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number18, 1f);
            }
            return;
        }
        if (Main.rand.Next(8) == 0)
        {
            int number19 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1912, Main.rand.Next(1, 4));
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number19, 1f);
            }
            return;
        }
        if (Main.rand.Next(9) == 0)
        {
            int number20 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1913, Main.rand.Next(20, 41));
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number20, 1f);
            }
            return;
        }
        switch (Main.rand.Next(3))
        {
        case 0:
        {
            int number22 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1872, Main.rand.Next(20, 50));
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number22, 1f);
            }
            break;
        }
        case 1:
        {
            int number23 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 586, Main.rand.Next(20, 50));
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number23, 1f);
            }
            break;
        }
        default:
        {
            int number21 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 591, Main.rand.Next(20, 50));
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number21, 1f);
            }
            break;
        }
        }
    }
References Terraria.Player.GetItemSource_OpenItem(), Terraria.Main.hardMode, Terraria.Entity.height, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.UI.ItemSlot.TryOpenContainer().