Terraria: Terraria.Player.ToggleCreativeMenu
ToggleCreativeMenu()
void Terraria.Player.ToggleCreativeMenu () inline
Definition at line 4153 of file Player.cs.
    {
        if (dead || difficulty != 3)
        {
            return;
        }
        bool flag = false;
        if (Main.mapFullscreen)
        {
            Main.mapFullscreen = false;
            flag = true;
        }
        if (PlayerInput.InBuildingMode)
        {
            PlayerInput.ExitBuildingMode();
        }
        if (Main.ingameOptionsWindow)
        {
            IngameOptions.Close();
        }
        if (Main.inFancyUI)
        {
            IngameFancyUI.Close();
        }
        if (CaptureManager.Instance.Active)
        {
            CaptureManager.Instance.Active = false;
        }
        if (talkNPC >= 0)
        {
            SetTalkNPC(-1);
            Main.npcChatCornerItem = 0;
            Main.npcChatText = "";
            flag = true;
            if (PlayerInput.UsingGamepad)
            {
                Main.npcChatRelease = false;
            }
        }
        if (sign >= 0)
        {
            sign = -1;
            Main.editSign = false;
            Main.npcChatText = "";
            flag = true;
        }
        else if (Main.clothesWindow)
        {
            Main.CancelClothesWindow();
        }
        if (tileEntityAnchor.InUse)
        {
            Recipe.FindRecipes();
            tileEntityAnchor.Clear();
            flag = true;
        }
        if (flag)
        {
            SoundEngine.PlaySound(11);
        }
        if (!Main.playerInventory)
        {
            OpenInventory();
        }
        Main.CreativeMenu.ToggleMenu();
    }
References Terraria.Graphics.Capture.CaptureManager.Active, Terraria.Main.CancelClothesWindow(), Terraria.DataStructures.PlayerInteractionAnchor.Clear(), Terraria.UI.IngameFancyUI.Close(), Terraria.IngameOptions.Close(), Terraria.Main.clothesWindow, Terraria.Main.CreativeMenu, Terraria.Player.dead, Terraria.Player.difficulty, Terraria.GameInput.PlayerInput.ExitBuildingMode(), Terraria.Recipe.FindRecipes(), Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.Main.inFancyUI, Terraria.Main.ingameOptionsWindow, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.DataStructures.PlayerInteractionAnchor.InUse, Terraria.Main.mapFullscreen, Terraria.Player.OpenInventory(), Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.SetTalkNPC(), Terraria.Player.sign, Terraria.Player.talkNPC, Terraria.Player.tileEntityAnchor, Terraria.GameContent.Creative.CreativeUI.ToggleMenu(), and Terraria.GameInput.PlayerInput.UsingGamepad.