Terraria: Terraria.Player.GetAnglerReward_Decoration
GetAnglerReward_Decoration()
void Terraria.Player.GetAnglerReward_Decoration (IEntitySource source, int questsDone, float rarityReduction, ref GetItemSettings anglerRewardSettings) inline private
Definition at line 53001 of file Player.cs.
    {
        float value = 1f - rarityReduction;
        int num = 100;
        float num2 = MathHelper.Lerp(value, 1f, Math.Min(1f, (float)questsDone / (float)num));
        if (!(num2 >= 1f) && !(Main.rand.NextFloat() <= num2))
        {
            return;
        }
        Item item = new Item();
        item.type = 0;
        item.SetDefaults(Main.rand.Next(19) switch
        {
            1 => 2443,
            2 => 2444,
            3 => 2445,
            4 => 2497,
            5 => 2495,
            6 => 2446,
            7 => 2447,
            8 => 2448,
            9 => 2449,
            10 => 2490,
            11 => 2496,
            12 => 5235,
            13 => 5252,
            14 => 5256,
            15 => 5259,
            16 => 5263,
            17 => 5264,
            18 => 5265,
            _ => 2442,
        });
        item.position = base.Center;
        Item item2 = GetItem(whoAmI, item, GetItemSettings.NPCEntityToPlayerInventorySettings);
        if (item2.stack > 0)
        {
            int number = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
        }
    }
References Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GetItemSettings.NPCEntityToPlayerInventorySettings, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.