Terraria: Terraria.Player.PickAmmo
PickAmmo()
void Terraria.Player.PickAmmo (Item sItem, ref int projToShoot, ref float speed, ref bool canShoot, ref int Damage, ref float KnockBack, out int usedAmmoItemId, bool dontConsume = false) inline
Definition at line 49978 of file Player.cs.
    {
        Item item = new Item();
        bool flag = false;
        usedAmmoItemId = 0;
        if (sItem.useAmmo == AmmoID.Coin)
        {
            for (int i = 0; i < 4; i++)
            {
                int num = 50 + i;
                if (inventory[num].ammo == sItem.useAmmo && inventory[num].stack > 0)
                {
                    item = inventory[num];
                    canShoot = true;
                    flag = true;
                    break;
                }
            }
        }
        for (int j = 54; j < 58; j++)
        {
            if (inventory[j].ammo == sItem.useAmmo && inventory[j].stack > 0)
            {
                item = inventory[j];
                canShoot = true;
                flag = true;
                break;
            }
        }
        if (!flag)
        {
            for (int k = 0; k < 54; k++)
            {
                if (inventory[k].ammo == sItem.useAmmo && inventory[k].stack > 0)
                {
                    item = inventory[k];
                    canShoot = true;
                    break;
                }
            }
        }
        if (!canShoot)
        {
            return;
        }
        usedAmmoItemId = item.type;
        int pickedProjectileId = -1;
        if (PickAmmo_TryFindingSpecificMatches(sItem.type, item.type, out pickedProjectileId))
        {
            projToShoot = pickedProjectileId;
        }
        else if (sItem.type == 1946)
        {
            projToShoot = 338 + item.type - 771;
        }
        else if (sItem.type == 3930)
        {
            projToShoot = 715 + item.type - AmmoID.Rocket;
        }
        else if (sItem.useAmmo == AmmoID.Rocket)
        {
            projToShoot += item.shoot;
        }
        else if (sItem.useAmmo == AmmoID.Solution)
        {
            projToShoot += item.shoot;
        }
        else if (item.shoot > 0)
        {
            projToShoot = item.shoot;
        }
        if (sItem.type == 3019 && projToShoot == 1)
        {
            projToShoot = 485;
        }
        if (sItem.type == 3052)
        {
            projToShoot = 495;
        }
        if (sItem.type == 4953 && projToShoot == 1)
        {
            projToShoot = 932;
        }
        if (sItem.type == 4381)
        {
            projToShoot = 819;
        }
        if (sItem.type == 4058 && projToShoot == 474)
        {
            projToShoot = 117;
        }
        if (projToShoot == 42)
        {
            if (item.type == 370)
            {
                projToShoot = 65;
                Damage += 5;
            }
            else if (item.type == 408)
            {
                projToShoot = 68;
                Damage += 5;
            }
            else if (item.type == 1246)
            {
                projToShoot = 354;
                Damage += 5;
            }
        }
        if (inventory[selectedItem].type == 2888 && projToShoot == 1)
        {
            projToShoot = 469;
        }
        if (hasMoltenQuiver && projToShoot == 1)
        {
            projToShoot = 2;
            Damage += 2;
        }
        speed += item.shootSpeed;
        if (magicQuiver && (sItem.useAmmo == AmmoID.Arrow || sItem.useAmmo == AmmoID.Stake))
        {
            KnockBack *= 1.1f;
            speed *= 1.1f;
        }
        if (item.ranged)
        {
            if (item.damage > 0)
            {
                Damage += (int)((float)item.damage * rangedDamage);
            }
        }
        else
        {
            Damage += item.damage;
        }
        if ((sItem.useAmmo == AmmoID.Arrow || sItem.useAmmo == AmmoID.Stake) && archery)
        {
            if (speed < 20f)
            {
                speed *= 1.2f;
                if (speed > 20f)
                {
                    speed = 20f;
                }
            }
            Damage = (int)((double)Damage * 1.1);
        }
        KnockBack += item.knockBack;
        bool flag2 = dontConsume;
        if (sItem.type == 3475 && Main.rand.Next(3) != 0)
        {
            flag2 = true;
        }
        if (sItem.type == 3930 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (sItem.type == 3540 && Main.rand.Next(3) != 0)
        {
            flag2 = true;
        }
        if (sItem.type == 5134 && Main.rand.Next(3) == 0)
        {
            flag2 = true;
        }
        if (magicQuiver && (sItem.useAmmo == AmmoID.Arrow || sItem.useAmmo == AmmoID.Stake) && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (ammoBox && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (ammoPotion && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (sItem.type == 1782 && Main.rand.Next(3) == 0)
        {
            flag2 = true;
        }
        if (sItem.type == 98 && Main.rand.Next(3) == 0)
        {
            flag2 = true;
        }
        if (sItem.type == 2270 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (sItem.type == 533 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (sItem.type == 1929 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (sItem.type == 1553 && Main.rand.Next(3) != 0)
        {
            flag2 = true;
        }
        if (sItem.type == 434 && !ItemAnimationJustStarted)
        {
            flag2 = true;
        }
        if (sItem.type == 4953 && itemAnimation > sItem.useAnimation - 8)
        {
            flag2 = true;
        }
        if (huntressAmmoCost90 && Main.rand.Next(10) == 0)
        {
            flag2 = true;
        }
        if (chloroAmmoCost80 && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (ammoCost80 && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (ammoCost75 && Main.rand.Next(4) == 0)
        {
            flag2 = true;
        }
        if (Main.remixWorld && sItem.type == 1319 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (projToShoot == 85 && itemAnimation < itemAnimationMax - sItem.useTime)
        {
            flag2 = true;
        }
        if ((sItem.type == 779 || sItem.type == 5134) && itemAnimation < itemAnimationMax - sItem.useTime)
        {
            flag2 = true;
        }
        if (!flag2 && item.consumable)
        {
            item.stack--;
            if (item.stack <= 0)
            {
                item.active = false;
                item.TurnToAir();
            }
        }
    }
References Terraria.ID.AmmoID.Arrow, Terraria.ID.AmmoID.Coin, Terraria.Item.consumable, Terraria.GameContent.Damage, Terraria.Item.damage, Terraria.Item.knockBack, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Item.ranged, Terraria.Main.remixWorld, Terraria.ID.AmmoID.Rocket, Terraria.Item.shoot, Terraria.Item.shootSpeed, Terraria.ID.AmmoID.Solution, Terraria.Item.stack, Terraria.ID.AmmoID.Stake, Terraria.Item.TurnToAir(), Terraria.Item.type, Terraria.Item.useAmmo, Terraria.Item.useAnimation, and Terraria.Item.useTime.
Referenced by Terraria.Projectile.AI_075().