Terraria: Terraria.Player.bank
bank
Chest Terraria.Player.bank = new Chest(bank: true)
Referenced by Terraria.GameContent.UI.CustomCurrencyManager.BuyItem(), Terraria.Player.clientClone(), Terraria.Recipe.CollectItemsToCraftWithFrom(), Terraria.Recipe.Create(), Terraria.UI.ChestUI.DepositAll(), Terraria.Player.Deserialize(), Terraria.UI.ItemSlot.DrawSavings(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), Terraria.UI.ChestUI.DrawSlots(), Terraria.UI.ChestUI.GetContainerUsageInfo(), Terraria.MessageBuffer.GetData(), Terraria.UI.ChestUI.IsBlockedFromTransferIntoChest(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.UI.ChestUI.LootAll(), Terraria.GameContent.Achievements.AchievementsHelper.OnPlayerEnteredWorld(), Terraria.UI.ChestUI.QuickStack(), Terraria.UI.ChestUI.Restock(), Terraria.NetMessage.SendData(), Terraria.Player.Serialize(), and Terraria.UI.ItemSorting.SortChest().