Terraria: Terraria.Player.pantsColor
pantsColor
Color Terraria.Player.pantsColor = new Color(255, 230, 175)
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.Player.CopyVisuals(), Terraria.Player.Deserialize(), Terraria.Initializers.UILinksInitializer.HandleOptionsSpecials(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.NetMessage.SendData(), Terraria.Player.Serialize(), and Terraria.Item.SetDefaults1().