Terraria: Terraria.Player.OpenShadowLockbox
OpenShadowLockbox()
void Terraria.Player.OpenShadowLockbox (int boxType) inline
    {
        bool flag = true;
        IEntitySource itemSource_OpenItem = GetItemSource_OpenItem(boxType);
        while (flag)
        {
            flag = false;
            int type = Main.rand.NextFromList(new short[5] { 274, 220, 112, 218, 3019 });
            if (Main.remixWorld)
            {
                type = Main.rand.NextFromList(new short[5] { 274, 220, 683, 218, 3019 });
            }
            int number = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, type, 1, noBroadcast: false, -1);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
            if (Main.rand.Next(5) == 0)
            {
                number = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 5010, 1, noBroadcast: false, -1);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number, 1f);
                }
            }
        }
    }
References Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.remixWorld, and Terraria.NetMessage.SendData().
Referenced by Terraria.UI.ItemSlot.TryOpenContainer().