Terraria: Terraria.Player.ItemCheckWrapped
ItemCheckWrapped()
void Terraria.Player.ItemCheckWrapped (int i) inline private
Definition at line 29512 of file Player.cs.
    {
        int num;
        if (!controlLeft && !controlRight && !controlUp && !controlDown && PlayerInput.UsingGamepad && Main.SmartCursorIsUsed)
        {
            num = ((PlayerInput.GamepadThumbstickRight.Length() < 0.05f) ? 1 : 0);
            if (num != 0)
            {
                ForceForwardCursor(state: true);
            }
        }
        else
        {
            num = 0;
        }
        int num2;
        if (PlayerInput.smartSelectPointer.ShouldBeUsed())
        {
            num2 = ((!Main.SmartCursorIsUsed) ? 1 : 0);
            if (num2 != 0)
            {
                ForceSmartSelectCursor(state: true);
            }
        }
        else
        {
            num2 = 0;
        }
        LockOnHelper.SetUP();
        int stack = inventory[selectedItem].stack;
        if (Main.ignoreErrors)
        {
            ItemCheck();
        }
        else
        {
            ItemCheck();
        }
        if (stack != inventory[selectedItem].stack)
        {
            Recipe.FindRecipes();
        }
        LockOnHelper.SetDOWN();
        if (num2 != 0)
        {
            ForceSmartSelectCursor(state: false);
        }
        if (num != 0)
        {
            ForceForwardCursor(state: false);
        }
        if (itemAnimation == 0)
        {
            lastVisualizedSelectedItem = HeldItem.Clone();
        }
    }
References Terraria.Item.Clone(), Terraria.Recipe.FindRecipes(), Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.Main.ignoreErrors, Terraria.GameInput.LockOnHelper.SetDOWN(), Terraria.GameInput.LockOnHelper.SetUP(), Terraria.Main.SmartCursorIsUsed, Terraria.GameInput.PlayerInput.smartSelectPointer, Terraria.Item.stack, System.state, and Terraria.GameInput.PlayerInput.UsingGamepad.