Terraria: Terraria.Player.GetAnglerReward_Money
GetAnglerReward_Money()
void Terraria.Player.GetAnglerReward_Money (IEntitySource source, int questsDone, float rarityReduction, ref GetItemSettings anglerRewardSettings) inline private
Definition at line 53101 of file Player.cs.
    {
        Item item = new Item();
        int num = (questsDone + 50) / 2;
        num = (int)((float)(num * Main.rand.Next(50, 201)) * 0.015f);
        num = (int)((double)num * 1.5);
        if (Main.hardMode)
        {
            num *= 2;
        }
        if (Main.expertMode)
        {
            num *= 2;
        }
        if (num > 100)
        {
            num /= 100;
            if (num > 10)
            {
                num = 10;
            }
            if (num < 1)
            {
                num = 1;
            }
            item.SetDefaults(73);
            item.stack = num;
        }
        else
        {
            if (num > 99)
            {
                num = 99;
            }
            if (num < 1)
            {
                num = 1;
            }
            item.SetDefaults(72);
            item.stack = num;
        }
        item.position = base.Center;
        Item item2 = GetItem(whoAmI, item, anglerRewardSettings);
        if (item2.stack > 0)
        {
            int number = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
        }
    }
References Terraria.Main.expertMode, Terraria.Main.hardMode, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.