Terraria: Terraria.Player.TileInteractionsMouseOver
TileInteractionsMouseOver()
void Terraria.Player.TileInteractionsMouseOver (int myX, int myY) inline private
Definition at line 31315 of file Player.cs.
    {
        if (myX != tileTargetX || myY != tileTargetY)
        {
            return;
        }
        if (Main.tile[myX, myY].type == 79)
        {
            if (!IsHoveringOverABottomSideOfABed(myX, myY))
            {
                if (IsWithinSnappngRangeToTile(myX, myY, 96))
                {
                    noThrow = 2;
                    cursorItemIconEnabled = true;
                    cursorItemIconID = 5013;
                }
            }
            else
            {
                noThrow = 2;
                cursorItemIconEnabled = true;
                int num = Main.tile[myX, myY].frameY / 36;
                switch (num)
                {
                case 0:
                    cursorItemIconID = 224;
                    break;
                case 1:
                    cursorItemIconID = 644;
                    break;
                case 2:
                    cursorItemIconID = 645;
                    break;
                case 3:
                    cursorItemIconID = 646;
                    break;
                case 4:
                    cursorItemIconID = 920;
                    break;
                case 5:
                    cursorItemIconID = 1470;
                    break;
                case 6:
                    cursorItemIconID = 1471;
                    break;
                case 7:
                    cursorItemIconID = 1472;
                    break;
                case 8:
                    cursorItemIconID = 1473;
                    break;
                case 9:
                    cursorItemIconID = 1719;
                    break;
                case 10:
                    cursorItemIconID = 1720;
                    break;
                case 11:
                    cursorItemIconID = 1721;
                    break;
                case 12:
                    cursorItemIconID = 1722;
                    break;
                case 13:
                case 14:
                case 15:
                case 16:
                case 17:
                case 18:
                    cursorItemIconID = 2066 + num - 13;
                    break;
                default:
                    if (num >= 19 && num <= 20)
                    {
                        cursorItemIconID = 2139 + num - 19;
                        break;
                    }
                    switch (num)
                    {
                    case 21:
                        cursorItemIconID = 2231;
                        break;
                    case 22:
                        cursorItemIconID = 2520;
                        break;
                    case 23:
                        cursorItemIconID = 2538;
                        break;
                    case 24:
                        cursorItemIconID = 2553;
                        break;
                    case 25:
                        cursorItemIconID = 2568;
                        break;
                    case 26:
                        cursorItemIconID = 2669;
                        break;
                    case 27:
                        cursorItemIconID = 2811;
                        break;
                    case 28:
                        cursorItemIconID = 3162;
                        break;
                    case 29:
                        cursorItemIconID = 3164;
                        break;
                    case 30:
                        cursorItemIconID = 3163;
                        break;
                    case 31:
                        cursorItemIconID = 3897;
                        break;
                    case 32:
                        cursorItemIconID = 3932;
                        break;
                    case 33:
                        cursorItemIconID = 3959;
                        break;
                    case 34:
                        cursorItemIconID = 4146;
                        break;
                    case 35:
                        cursorItemIconID = 4167;
                        break;
                    case 36:
                        cursorItemIconID = 4188;
                        break;
                    case 37:
                        cursorItemIconID = 4209;
                        break;
                    case 38:
                        cursorItemIconID = 4299;
                        break;
                    case 39:
                        cursorItemIconID = 4567;
                        break;
                    case 40:
                        cursorItemIconID = 5149;
                        break;
                    case 41:
                        cursorItemIconID = 5170;
                        break;
                    case 42:
                        cursorItemIconID = 5191;
                        break;
                    default:
                        cursorItemIconID = 646;
                        break;
                    }
                    break;
                }
            }
        }
        if (Main.tile[myX, myY].type == 597)
        {
            int pylonStyleFromTile = TETeleportationPylon.GetPylonStyleFromTile(Main.tile[myX, myY]);
            int pylonItemTypeFromTileStyle = TETeleportationPylon.GetPylonItemTypeFromTileStyle(pylonStyleFromTile);
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = pylonItemTypeFromTileStyle;
            if (pylonStyleFromTile == 1)
            {
                cursorItemIconID = 4875;
            }
            if (pylonStyleFromTile == 2)
            {
                cursorItemIconID = 4916;
            }
            if (pylonStyleFromTile == 3)
            {
                cursorItemIconID = 4917;
            }
            if (pylonStyleFromTile == 4)
            {
                cursorItemIconID = 4918;
            }
            if (pylonStyleFromTile == 5)
            {
                cursorItemIconID = 4919;
            }
            if (pylonStyleFromTile == 6)
            {
                cursorItemIconID = 4920;
            }
            if (pylonStyleFromTile == 7)
            {
                cursorItemIconID = 4921;
            }
            if (pylonStyleFromTile == 8)
            {
                cursorItemIconID = 4951;
            }
        }
        if (Main.tile[myX, myY].type == 621)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3750;
        }
        if (Main.tile[myX, myY].type == 464)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3814;
        }
        if (Main.tile[myX, myY].type == 33)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 105;
            int num2 = Main.tile[myX, myY].frameY / 22;
            if (num2 == 1)
            {
                cursorItemIconID = 1405;
            }
            if (num2 == 2)
            {
                cursorItemIconID = 1406;
            }
            if (num2 == 3)
            {
                cursorItemIconID = 1407;
            }
            if (num2 >= 4 && num2 <= 13)
            {
                cursorItemIconID = 2045 + num2 - 4;
            }
            if (num2 >= 14 && num2 <= 16)
            {
                cursorItemIconID = 2153 + num2 - 14;
            }
            if (num2 == 17)
            {
                cursorItemIconID = 2236;
            }
            if (num2 == 18)
            {
                cursorItemIconID = 2523;
            }
            if (num2 == 19)
            {
                cursorItemIconID = 2542;
            }
            if (num2 == 20)
            {
                cursorItemIconID = 2556;
            }
            if (num2 == 21)
            {
                cursorItemIconID = 2571;
            }
            if (num2 == 22)
            {
                cursorItemIconID = 2648;
            }
            if (num2 == 23)
            {
                cursorItemIconID = 2649;
            }
            if (num2 == 24)
            {
                cursorItemIconID = 2650;
            }
            switch (num2)
            {
            case 25:
                cursorItemIconID = 2651;
                break;
            case 26:
                cursorItemIconID = 2818;
                break;
            case 27:
                cursorItemIconID = 3171;
                break;
            case 28:
                cursorItemIconID = 3173;
                break;
            case 29:
                cursorItemIconID = 3172;
                break;
            case 30:
                cursorItemIconID = 3890;
                break;
            case 31:
                cursorItemIconID = 3936;
                break;
            case 32:
                cursorItemIconID = 3962;
                break;
            case 33:
                cursorItemIconID = 4150;
                break;
            case 34:
                cursorItemIconID = 4171;
                break;
            case 35:
                cursorItemIconID = 4192;
                break;
            case 36:
                cursorItemIconID = 4213;
                break;
            case 37:
                cursorItemIconID = 4303;
                break;
            case 38:
                cursorItemIconID = 4571;
                break;
            case 39:
                cursorItemIconID = 5153;
                break;
            case 40:
                cursorItemIconID = 5174;
                break;
            case 41:
                cursorItemIconID = 5195;
                break;
            }
        }
        if (Main.tile[myX, myY].type == 21)
        {
            TileInteractionsMouseOver_Containers(myX, myY);
        }
        if (Main.tile[myX, myY].type == 467)
        {
            TileInteractionsMouseOver_Containers(myX, myY);
        }
        if (Main.tile[myX, myY].type == 441)
        {
            Tile tile = Main.tile[myX, myY];
            int num3 = myX;
            int num4 = myY;
            if (tile.frameX % 36 != 0)
            {
                num3--;
            }
            if (tile.frameY % 36 != 0)
            {
                num4--;
            }
            cursorItemIconID = -1;
            cursorItemIconID = Chest.chestTypeToIcon[tile.frameX / 36];
            noThrow = 2;
            cursorItemIconEnabled = true;
        }
        if (Main.tile[myX, myY].type == 468)
        {
            Tile tile2 = Main.tile[myX, myY];
            int num5 = myX;
            int num6 = myY;
            if (tile2.frameX % 36 != 0)
            {
                num5--;
            }
            if (tile2.frameY % 36 != 0)
            {
                num6--;
            }
            cursorItemIconID = -1;
            cursorItemIconID = Chest.chestTypeToIcon2[tile2.frameX / 36];
            noThrow = 2;
            cursorItemIconEnabled = true;
        }
        if (Main.tile[myX, myY].type == 88)
        {
            Tile tile3 = Main.tile[myX, myY];
            int num7 = myY;
            int x = myX - tile3.frameX % 54 / 18;
            if (tile3.frameY % 36 != 0)
            {
                num7--;
            }
            int num8 = Chest.FindChest(x, num7);
            cursorItemIconID = -1;
            if (num8 < 0)
            {
                cursorItemIconText = Lang.dresserType[0].Value;
            }
            else
            {
                if (Main.chest[num8].name != "")
                {
                    cursorItemIconText = Main.chest[num8].name;
                }
                else
                {
                    cursorItemIconText = Lang.dresserType[tile3.frameX / 54].Value;
                }
                if (cursorItemIconText == Lang.dresserType[tile3.frameX / 54].Value)
                {
                    cursorItemIconID = Chest.dresserTypeToIcon[tile3.frameX / 54];
                    cursorItemIconText = "";
                }
            }
            noThrow = 2;
            cursorItemIconEnabled = true;
            if (Main.tile[myX, myY].frameY > 0)
            {
                cursorItemIconID = 269;
                cursorItemIconText = "";
            }
        }
        if (Main.tile[myX, myY].type == 10 || Main.tile[myX, myY].type == 11)
        {
            Tile tile4 = Main.tile[myX, myY];
            noThrow = 2;
            cursorItemIconEnabled = true;
            int num9 = tile4.frameY;
            int num10 = 0;
            while (num9 >= 54)
            {
                num9 -= 54;
                num10++;
            }
            if (tile4.type == 10)
            {
                num10 += 36 * (tile4.frameX / 54);
            }
            if (tile4.type == 11)
            {
                num10 += 36 * (tile4.frameX / 72);
            }
            switch (num10)
            {
            case 0:
                cursorItemIconID = 25;
                break;
            case 9:
                cursorItemIconID = 837;
                break;
            case 10:
                cursorItemIconID = 912;
                break;
            case 11:
                cursorItemIconID = 1141;
                break;
            case 12:
                cursorItemIconID = 1137;
                break;
            case 13:
                cursorItemIconID = 1138;
                break;
            case 14:
                cursorItemIconID = 1139;
                break;
            case 15:
                cursorItemIconID = 1140;
                break;
            case 16:
                cursorItemIconID = 1411;
                break;
            case 17:
                cursorItemIconID = 1412;
                break;
            case 18:
                cursorItemIconID = 1413;
                break;
            case 19:
                cursorItemIconID = 1458;
                break;
            case 20:
            case 21:
            case 22:
            case 23:
                cursorItemIconID = 1709 + num10 - 20;
                break;
            default:
                switch (num10)
                {
                case 24:
                    cursorItemIconID = 1793;
                    break;
                case 25:
                    cursorItemIconID = 1815;
                    break;
                case 26:
                    cursorItemIconID = 1924;
                    break;
                case 27:
                    cursorItemIconID = 2044;
                    break;
                case 28:
                    cursorItemIconID = 2265;
                    break;
                case 29:
                    cursorItemIconID = 2528;
                    break;
                case 30:
                    cursorItemIconID = 2561;
                    break;
                case 31:
                    cursorItemIconID = 2576;
                    break;
                case 32:
                    cursorItemIconID = 2815;
                    break;
                case 33:
                    cursorItemIconID = 3129;
                    break;
                case 34:
                    cursorItemIconID = 3131;
                    break;
                case 35:
                    cursorItemIconID = 3130;
                    break;
                case 36:
                    cursorItemIconID = 3888;
                    break;
                case 37:
                    cursorItemIconID = 3941;
                    break;
                case 38:
                    cursorItemIconID = 3967;
                    break;
                case 39:
                    cursorItemIconID = 4155;
                    break;
                case 40:
                    cursorItemIconID = 4176;
                    break;
                case 41:
                    cursorItemIconID = 4197;
                    break;
                case 42:
                    cursorItemIconID = 4218;
                    break;
                case 43:
                    cursorItemIconID = 4307;
                    break;
                case 44:
                    cursorItemIconID = 4415;
                    break;
                case 45:
                    cursorItemIconID = 4576;
                    break;
                case 46:
                    cursorItemIconID = 5158;
                    break;
                case 47:
                    cursorItemIconID = 5179;
                    break;
                case 48:
                    cursorItemIconID = 5200;
                    break;
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                    cursorItemIconID = 812 + num10;
                    break;
                default:
                    cursorItemIconID = 649 + num10;
                    break;
                }
                break;
            }
        }
        if (Main.tile[myX, myY].type == 104)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            switch (Main.tile[myX, myY].frameX / 36)
            {
            case 0:
                cursorItemIconID = 359;
                break;
            case 1:
                cursorItemIconID = 2237;
                break;
            case 2:
                cursorItemIconID = 2238;
                break;
            case 3:
                cursorItemIconID = 2239;
                break;
            case 4:
                cursorItemIconID = 2240;
                break;
            case 5:
                cursorItemIconID = 2241;
                break;
            case 6:
                cursorItemIconID = 2560;
                break;
            case 7:
                cursorItemIconID = 2575;
                break;
            case 8:
                cursorItemIconID = 2591;
                break;
            case 9:
                cursorItemIconID = 2592;
                break;
            case 10:
                cursorItemIconID = 2593;
                break;
            case 11:
                cursorItemIconID = 2594;
                break;
            case 12:
                cursorItemIconID = 2595;
                break;
            case 13:
                cursorItemIconID = 2596;
                break;
            case 14:
                cursorItemIconID = 2597;
                break;
            case 15:
                cursorItemIconID = 2598;
                break;
            case 16:
                cursorItemIconID = 2599;
                break;
            case 17:
                cursorItemIconID = 2600;
                break;
            case 18:
                cursorItemIconID = 2601;
                break;
            case 19:
                cursorItemIconID = 2602;
                break;
            case 20:
                cursorItemIconID = 2603;
                break;
            case 21:
                cursorItemIconID = 2604;
                break;
            case 22:
                cursorItemIconID = 2605;
                break;
            case 23:
                cursorItemIconID = 2606;
                break;
            case 24:
                cursorItemIconID = 2809;
                break;
            case 25:
                cursorItemIconID = 3126;
                break;
            case 26:
                cursorItemIconID = 3128;
                break;
            case 27:
                cursorItemIconID = 3127;
                break;
            case 28:
                cursorItemIconID = 3898;
                break;
            case 29:
                cursorItemIconID = 3899;
                break;
            case 30:
                cursorItemIconID = 3900;
                break;
            case 31:
                cursorItemIconID = 3901;
                break;
            case 32:
                cursorItemIconID = 3902;
                break;
            case 33:
                cursorItemIconID = 3940;
                break;
            case 34:
                cursorItemIconID = 3966;
                break;
            case 35:
                cursorItemIconID = 4154;
                break;
            case 36:
                cursorItemIconID = 4175;
                break;
            case 37:
                cursorItemIconID = 4196;
                break;
            case 38:
                cursorItemIconID = 4217;
                break;
            case 39:
                cursorItemIconID = 4306;
                break;
            case 40:
                cursorItemIconID = 4575;
                break;
            case 41:
                cursorItemIconID = 5157;
                break;
            case 42:
                cursorItemIconID = 5178;
                break;
            case 43:
                cursorItemIconID = 5199;
                break;
            }
        }
        if (Main.tile[myX, myY].type == 356)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3064;
        }
        if (Main.tile[myX, myY].type == 663)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 5381;
        }
        if (Main.tile[myX, myY].type == 377)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3198;
        }
        if (Main.tile[myX, myY].type == 209)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            if (Main.tile[myX, myY].frameX < 72)
            {
                cursorItemIconID = 928;
            }
            else if (Main.tile[myX, myY].frameX < 144)
            {
                cursorItemIconID = 1337;
            }
            else if (Main.tile[myX, myY].frameX < 216)
            {
                cursorItemIconID = 3369;
            }
            else if (Main.tile[myX, myY].frameX < 360)
            {
                cursorItemIconID = 3664;
            }
            int num11;
            for (num11 = Main.tile[myX, myY].frameX / 18; num11 >= 4; num11 -= 4)
            {
            }
            if (num11 < 2)
            {
                cursorItemIconReversed = true;
            }
            else
            {
                cursorItemIconReversed = false;
            }
        }
        if (Main.tile[myX, myY].type == 216)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            int num12 = Main.tile[myX, myY].frameY;
            int num13 = 0;
            while (num12 >= 40)
            {
                num12 -= 40;
                num13++;
            }
            cursorItemIconID = 970 + num13;
        }
        if (Main.tile[myX, myY].type == 387 || Main.tile[myX, myY].type == 386)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            int x2 = 0;
            int y = 0;
            WorldGen.GetTopLeftAndStyles(ref x2, ref y, 2, 1 + (Main.tile[myX, myY].type == 386).ToInt(), 18, 18);
            cursorItemIconID = 3239;
        }
        if (Main.tile[myX, myY].type == 389 || Main.tile[myX, myY].type == 388)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3240;
        }
        if (Main.tile[myX, myY].type == 335)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 2700;
        }
        if (Main.tile[myX, myY].type == 15 && IsWithinSnappngRangeToTile(myX, myY, 40))
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = WorldGen.GetItemDrop_Chair(Main.tile[myX, myY].frameY / 40);
            if (Main.tile[myX, myY].frameX / 18 < 1)
            {
                cursorItemIconReversed = true;
            }
        }
        if (Main.tile[myX, myY].type == 102 && IsWithinSnappngRangeToTile(myX, myY, 40))
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 355;
        }
        if (Main.tile[myX, myY].type == 89 && IsWithinSnappngRangeToTile(myX, myY, 40))
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = WorldGen.GetItemDrop_Benches(Main.tile[myX, myY].frameX / 54);
        }
        if (Main.tile[myX, myY].type == 487 && IsWithinSnappngRangeToTile(myX, myY, 40))
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = WorldGen.GetItemDrop_PicnicTables(Main.tile[myX, myY].frameX / 72);
        }
        if (Main.tile[myX, myY].type == 497 && IsWithinSnappngRangeToTile(myX, myY, 40))
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = WorldGen.GetItemDrop_Toilet(Main.tile[myX, myY].frameY / 40);
            if (Main.tile[myX, myY].frameX / 18 < 1)
            {
                cursorItemIconReversed = true;
            }
        }
        if (Main.tile[myX, myY].type == 410)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3536 + Math.Min(Main.tile[myX, myY].frameX / 36, 3);
        }
        if (Main.tile[myX, myY].type == 480)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 4054;
        }
        if (Main.tile[myX, myY].type == 509)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 4318;
        }
        if (Main.tile[myX, myY].type == 657)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 5345;
        }
        if (Main.tile[myX, myY].type == 658)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 5347;
        }
        if (Main.tile[myX, myY].type == 463)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3813;
        }
        if (Main.tile[myX, myY].type == 491)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 4076;
        }
        if (Main.tile[myX, myY].type == 494)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 4089;
        }
        if (Main.tile[myX, myY].type == 411 && Main.tile[myX, myY].frameX < 36)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3545;
        }
        if (Main.tile[myX, myY].type == 338)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 2738;
        }
        if (Main.tile[myX, myY].type == 455)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3747;
        }
        if ((Main.tile[myX, myY].type == 219 || Main.tile[myX, myY].type == 642) && (inventory[selectedItem].type == 424 || inventory[selectedItem].type == 1103 || inventory[selectedItem].type == 2339 || inventory[selectedItem].type == 2338 || inventory[selectedItem].type == 2337))
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = inventory[selectedItem].type;
        }
        if (Main.tile[myX, myY].type == 212)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 949;
        }
        if (Main.tile[myX, myY].type == 314 && gravDir == 1f)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 2343;
        }
        if (Main.tile[myX, myY].type == 215)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            int num14 = Main.tile[myX, myY].frameX / 54;
            switch (num14)
            {
            case 0:
                cursorItemIconID = 966;
                break;
            case 14:
                cursorItemIconID = 5299;
                break;
            case 15:
                cursorItemIconID = 5357;
                break;
            case 8:
            case 9:
            case 10:
            case 11:
            case 12:
            case 13:
                cursorItemIconID = 4689 + num14 - 8;
                break;
            default:
                switch (num14)
                {
                case 7:
                    cursorItemIconID = 3724;
                    break;
                case 6:
                    cursorItemIconID = 3723;
                    break;
                case 5:
                    cursorItemIconID = 3050;
                    break;
                default:
                    cursorItemIconID = 3046 + num14 - 1;
                    break;
                }
                break;
            }
        }
        if (Main.tile[myX, myY].type == 4)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            int num15 = Main.tile[myX, myY].frameY / 22;
            switch (num15)
            {
            case 0:
                cursorItemIconID = 8;
                break;
            case 8:
                cursorItemIconID = 523;
                break;
            case 9:
                cursorItemIconID = 974;
                break;
            case 10:
                cursorItemIconID = 1245;
                break;
            case 11:
                cursorItemIconID = 1333;
                break;
            case 12:
                cursorItemIconID = 2274;
                break;
            case 13:
                cursorItemIconID = 3004;
                break;
            case 14:
                cursorItemIconID = 3045;
                break;
            case 15:
                cursorItemIconID = 3114;
                break;
            case 16:
                cursorItemIconID = 4383;
                break;
            case 17:
                cursorItemIconID = 4384;
                break;
            case 18:
                cursorItemIconID = 4385;
                break;
            case 19:
                cursorItemIconID = 4386;
                break;
            case 20:
                cursorItemIconID = 4387;
                break;
            case 21:
                cursorItemIconID = 4388;
                break;
            case 22:
                cursorItemIconID = 5293;
                break;
            case 23:
                cursorItemIconID = 5353;
                break;
            default:
                cursorItemIconID = 426 + num15;
                break;
            }
        }
        if (Main.tile[myX, myY].type == 13)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            switch (Main.tile[myX, myY].frameX / 18)
            {
            case 1:
                cursorItemIconID = 28;
                break;
            case 2:
                cursorItemIconID = 110;
                break;
            case 3:
                cursorItemIconID = 350;
                break;
            case 4:
                cursorItemIconID = 351;
                break;
            case 5:
                cursorItemIconID = 2234;
                break;
            case 6:
                cursorItemIconID = 2244;
                break;
            case 7:
                cursorItemIconID = 2257;
                break;
            case 8:
                cursorItemIconID = 2258;
                break;
            default:
                cursorItemIconID = 31;
                break;
            }
        }
        if (Main.tile[myX, myY].type == 29)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 87;
        }
        if (Main.tile[myX, myY].type == 97)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 346;
        }
        if (Main.tile[myX, myY].type == 510)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 4319;
            int num16;
            for (num16 = Main.tile[myX, myY].frameX / 18; num16 >= 2; num16 -= 2)
            {
            }
            if (num16 == 0)
            {
                cursorItemIconReversed = true;
            }
            else
            {
                cursorItemIconReversed = false;
            }
        }
        if (Main.tile[myX, myY].type == 511)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 4320;
            int num17;
            for (num17 = Main.tile[myX, myY].frameX / 18; num17 >= 2; num17 -= 2)
            {
            }
            if (num17 == 0)
            {
                cursorItemIconReversed = true;
            }
            else
            {
                cursorItemIconReversed = false;
            }
        }
        if (Main.tile[myX, myY].type == 49)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 148;
        }
        if (Main.tile[myX, myY].type == 372)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3117;
        }
        if (Main.tile[myX, myY].type == 646)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 5322;
        }
        if (Main.tile[myX, myY].type == 174)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 713;
        }
        if (Main.tile[myX, myY].type == 50)
        {
            noThrow = 2;
            if (Main.tile[myX, myY].frameX == 90)
            {
                cursorItemIconEnabled = true;
                cursorItemIconID = 165;
            }
        }
        if (Main.tile[myX, myY].type == 139)
        {
            noThrow = 2;
            int num18 = 0;
            for (int num19 = Main.tile[myX, myY].frameY / 18; num19 >= 2; num19 -= 2)
            {
                num18++;
            }
            cursorItemIconEnabled = true;
            if (num18 == 28)
            {
                cursorItemIconID = 1963;
            }
            else if (num18 == 29)
            {
                cursorItemIconID = 1964;
            }
            else if (num18 == 30)
            {
                cursorItemIconID = 1965;
            }
            else if (num18 == 31)
            {
                cursorItemIconID = 2742;
            }
            else if (num18 == 32)
            {
                cursorItemIconID = 3044;
            }
            else if (num18 == 33)
            {
                cursorItemIconID = 3235;
            }
            else if (num18 == 34)
            {
                cursorItemIconID = 3236;
            }
            else if (num18 == 35)
            {
                cursorItemIconID = 3237;
            }
            else if (num18 == 36)
            {
                cursorItemIconID = 3370;
            }
            else if (num18 == 37)
            {
                cursorItemIconID = 3371;
            }
            else if (num18 == 38)
            {
                cursorItemIconID = 3796;
            }
            else if (num18 == 39)
            {
                cursorItemIconID = 3869;
            }
            else if (num18 == 40)
            {
                cursorItemIconID = 4082;
            }
            else if (num18 == 41)
            {
                cursorItemIconID = 4078;
            }
            else if (num18 == 42)
            {
                cursorItemIconID = 4079;
            }
            else if (num18 == 43)
            {
                cursorItemIconID = 4077;
            }
            else if (num18 == 44)
            {
                cursorItemIconID = 4080;
            }
            else if (num18 == 45)
            {
                cursorItemIconID = 4081;
            }
            else if (num18 == 46)
            {
                cursorItemIconID = 4237;
            }
            else if (num18 == 47)
            {
                cursorItemIconID = 4356;
            }
            else if (num18 == 48)
            {
                cursorItemIconID = 4357;
            }
            else if (num18 == 49)
            {
                cursorItemIconID = 4358;
            }
            else if (num18 == 50)
            {
                cursorItemIconID = 4421;
            }
            else if (num18 == 51)
            {
                cursorItemIconID = 4606;
            }
            else if (num18 == 52)
            {
                cursorItemIconID = 4979;
            }
            else if (num18 == 53)
            {
                cursorItemIconID = 4985;
            }
            else if (num18 == 54)
            {
                cursorItemIconID = 4990;
            }
            else if (num18 == 55)
            {
                cursorItemIconID = 4991;
            }
            else if (num18 == 56)
            {
                cursorItemIconID = 4992;
            }
            else if (num18 == 57)
            {
                cursorItemIconID = 5006;
            }
            else if (num18 == 58)
            {
                cursorItemIconID = 5014;
            }
            else if (num18 == 59)
            {
                cursorItemIconID = 5015;
            }
            else if (num18 == 60)
            {
                cursorItemIconID = 5016;
            }
            else if (num18 == 61)
            {
                cursorItemIconID = 5017;
            }
            else if (num18 == 62)
            {
                cursorItemIconID = 5018;
            }
            else if (num18 == 63)
            {
                cursorItemIconID = 5019;
            }
            else if (num18 == 64)
            {
                cursorItemIconID = 5020;
            }
            else if (num18 == 65)
            {
                cursorItemIconID = 5021;
            }
            else if (num18 == 66)
            {
                cursorItemIconID = 5022;
            }
            else if (num18 == 67)
            {
                cursorItemIconID = 5023;
            }
            else if (num18 == 68)
            {
                cursorItemIconID = 5024;
            }
            else if (num18 == 69)
            {
                cursorItemIconID = 5025;
            }
            else if (num18 == 70)
            {
                cursorItemIconID = 5026;
            }
            else if (num18 == 71)
            {
                cursorItemIconID = 5027;
            }
            else if (num18 == 72)
            {
                cursorItemIconID = 5028;
            }
            else if (num18 == 73)
            {
                cursorItemIconID = 5029;
            }
            else if (num18 == 74)
            {
                cursorItemIconID = 5030;
            }
            else if (num18 == 75)
            {
                cursorItemIconID = 5031;
            }
            else if (num18 == 76)
            {
                cursorItemIconID = 5032;
            }
            else if (num18 == 77)
            {
                cursorItemIconID = 5033;
            }
            else if (num18 == 78)
            {
                cursorItemIconID = 5034;
            }
            else if (num18 == 79)
            {
                cursorItemIconID = 5035;
            }
            else if (num18 == 80)
            {
                cursorItemIconID = 5036;
            }
            else if (num18 == 81)
            {
                cursorItemIconID = 5037;
            }
            else if (num18 == 82)
            {
                cursorItemIconID = 5038;
            }
            else if (num18 == 83)
            {
                cursorItemIconID = 5039;
            }
            else if (num18 == 84)
            {
                cursorItemIconID = 5040;
            }
            else if (num18 == 85)
            {
                cursorItemIconID = 5044;
            }
            else if (num18 == 86)
            {
                cursorItemIconID = 5112;
            }
            else if (num18 == 87)
            {
                cursorItemIconID = 5362;
            }
            else if (num18 >= 13)
            {
                cursorItemIconID = 1596 + num18 - 13;
            }
            else
            {
                cursorItemIconID = 562 + num18;
            }
        }
        if (Main.tile[myX, myY].type == 207)
        {
            noThrow = 2;
            int num20 = 0;
            for (int num21 = Main.tile[myX, myY].frameX / 18; num21 >= 2; num21 -= 2)
            {
                num20++;
            }
            cursorItemIconEnabled = true;
            switch (num20)
            {
            case 0:
                cursorItemIconID = 909;
                break;
            case 1:
                cursorItemIconID = 910;
                break;
            case 2:
                cursorItemIconID = 940;
                break;
            case 3:
                cursorItemIconID = 941;
                break;
            case 4:
                cursorItemIconID = 942;
                break;
            case 5:
                cursorItemIconID = 943;
                break;
            case 6:
                cursorItemIconID = 944;
                break;
            case 7:
                cursorItemIconID = 945;
                break;
            case 8:
                cursorItemIconID = 4922;
                break;
            case 9:
                cursorItemIconID = 4417;
                break;
            }
        }
        if (Main.tileSign[Main.tile[myX, myY].type])
        {
            noThrow = 2;
            int num22 = Main.tile[myX, myY].frameX / 18;
            int num23 = Main.tile[myX, myY].frameY / 18;
            num22 %= 2;
            int num24 = myX - num22;
            int num25 = myY - num23;
            Main.signBubble = true;
            Main.signX = num24 * 16 + 16;
            Main.signY = num25 * 16;
            int num26 = Sign.ReadSign(num24, num25, CreateIfMissing: false);
            if (num26 != -1)
            {
                Main.signHover = num26;
            }
            if (num26 != -1)
            {
                Main.signHover = num26;
                cursorItemIconEnabled = false;
                cursorItemIconID = -1;
            }
        }
        if (Main.tile[myX, myY].type == 237)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 1293;
        }
        if (Main.tile[myX, myY].type == 466)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3828;
        }
        if (Main.tile[myX, myY].type == 125)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 487;
        }
        if (Main.tile[myX, myY].type == 354)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 2999;
        }
        if (Main.tile[myX, myY].type == 287)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 2177;
        }
        if (Main.tile[myX, myY].type == 132)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 513;
        }
        if (Main.tile[myX, myY].type == 136)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 538;
        }
        if (Main.tile[myX, myY].type == 144)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            int num27 = Main.tile[myX, myY].frameX / 18;
            if (num27 < 3)
            {
                cursorItemIconID = 583 + num27;
            }
            else
            {
                cursorItemIconID = 4484 + (num27 - 3);
            }
        }
        if (Main.tile[myX, myY].type == 440)
        {
            int num28 = Main.tile[myX, myY].frameX / 54;
            int num29 = Main.tile[myX, myY].frameY / 54;
            int num30 = -1;
            switch (num28)
            {
            case 0:
                num30 = 1526;
                break;
            case 1:
                num30 = 1524;
                break;
            case 2:
                num30 = 1525;
                break;
            case 3:
                num30 = 1523;
                break;
            case 4:
                num30 = 1522;
                break;
            case 5:
                num30 = 1527;
                break;
            case 6:
                num30 = 3643;
                break;
            }
            if (num30 != -1 && (num29 == 1 || HasItem(num30)))
            {
                noThrow = 2;
                cursorItemIconEnabled = true;
                cursorItemIconID = num30;
            }
        }
        else if (Main.tile[myX, myY].type == 470)
        {
            noThrow = 2;
            int num31 = Main.tile[myX, myY].frameX % 136 / 34;
            if (num31 < 2)
            {
                cursorItemIconEnabled = true;
                cursorItemIconID = 498;
            }
            else if (num31 < 4)
            {
                cursorItemIconEnabled = true;
                cursorItemIconID = 1989;
            }
        }
        else if (Main.tile[myX, myY].type == 475)
        {
            noThrow = 2;
            cursorItemIconEnabled = true;
            cursorItemIconID = 3977;
        }
        else if (Main.tile[myX, myY].type == 520)
        {
            noThrow = 2;
            int num32 = TEFoodPlatter.Find(myX, myY);
            if (num32 != -1)
            {
                cursorItemIconEnabled = true;
                TEFoodPlatter tEFoodPlatter = (TEFoodPlatter)TileEntity.ByID[num32];
                cursorItemIconID = tEFoodPlatter.item.type;
            }
        }
        else if (Main.tile[myX, myY].type == 395)
        {
            noThrow = 2;
            int num33 = myX;
            int num34 = myY;
            int num35 = Main.tile[myX, myY].frameX;
            int num36 = Main.tile[myX, myY].frameY;
            while (num36 > 0)
            {
                num36 -= 18;
                num34--;
            }
            while (num35 >= 36)
            {
                num35 -= 36;
            }
            while (num35 > 0)
            {
                num35 -= 18;
                num33--;
            }
            int num37 = TEItemFrame.Find(num33, num34);
            if (num37 != -1)
            {
                cursorItemIconEnabled = true;
                TEItemFrame tEItemFrame = (TEItemFrame)TileEntity.ByID[num37];
                cursorItemIconID = tEItemFrame.item.type;
            }
        }
        else if (Main.tile[myX, myY].type == 471)
        {
            noThrow = 2;
            int num38 = myX;
            int num39 = myY;
            int num40 = Main.tile[myX, myY].frameX;
            int num41 = Main.tile[myX, myY].frameY;
            while (num41 > 0)
            {
                num41 -= 18;
                num39--;
            }
            while (num40 >= 54)
            {
                num40 -= 54;
            }
            while (num40 > 0)
            {
                num40 -= 18;
                num38--;
            }
            int num42 = TEWeaponsRack.Find(num38, num39);
            if (num42 != -1)
            {
                cursorItemIconEnabled = true;
                TEWeaponsRack tEWeaponsRack = (TEWeaponsRack)TileEntity.ByID[num42];
                cursorItemIconID = tEWeaponsRack.item.type;
            }
        }
        else if (Main.tile[myX, myY].type == 334)
        {
            noThrow = 2;
        }
        if (PlayerInput.UsingGamepad && cursorItemIconText.Length == 0)
        {
            cursorItemIconEnabled = false;
            cursorItemIconID = 0;
        }
    }
References Terraria.DataStructures.TileEntity.ByID, Terraria.Main.chest, Terraria.Chest.chestTypeToIcon, Terraria.Chest.chestTypeToIcon2, Terraria.Lang.dresserType, Terraria.Chest.dresserTypeToIcon, Terraria.GameContent.Tile_Entities.TEFoodPlatter.Find(), Terraria.GameContent.Tile_Entities.TEItemFrame.Find(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Find(), Terraria.Chest.FindChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemDrop_Benches(), Terraria.WorldGen.GetItemDrop_Chair(), Terraria.WorldGen.GetItemDrop_PicnicTables(), Terraria.WorldGen.GetItemDrop_Toilet(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.GetPylonItemTypeFromTileStyle(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.GetPylonStyleFromTile(), Terraria.WorldGen.GetTopLeftAndStyles(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.item, Terraria.GameContent.Tile_Entities.TEItemFrame.item, Terraria.GameContent.Tile_Entities.TEWeaponsRack.item, Terraria.Chest.name, Terraria.Sign.ReadSign(), Terraria.Main.tile, Terraria.Main.tileSign, Terraria.Item.type, Terraria.Tile.type, Terraria.GameInput.PlayerInput.UsingGamepad, and Terraria.Localization.LocalizedText.Value.