Terraria: Terraria.Player.QuickGrapple_GetItemToUse
QuickGrapple_GetItemToUse()
Item Terraria.Player.QuickGrapple_GetItemToUse () inline
    {
        Item item = null;
        if (Main.projHook[miscEquips[4].shoot])
        {
            item = miscEquips[4];
        }
        if (item == null)
        {
            for (int i = 0; i < 58; i++)
            {
                if (Main.projHook[inventory[i].shoot])
                {
                    item = inventory[i];
                    break;
                }
            }
        }
        return item;
    }
References Terraria.Player.inventory, Terraria.Player.miscEquips, Terraria.Main.projHook, and Terraria.Item.shoot.
Referenced by Terraria.GameInput.PlayerInput.ComposeInstructionsForGamepad(), Terraria.Player.QuickGrapple(), and Terraria.GameContent.ChromaHotkeyPainter.Step_Grapple().