Terraria: Terraria.Player.Hurt
Hurt()
double Terraria.Player.Hurt (PlayerDeathReason damageSource, int Damage, int hitDirection, bool pvp = false, bool quiet = false, bool Crit = false, int cooldownCounter = -1, bool dodgeable = true) inline
Definition at line 36134 of file Player.cs.
    {
        if (shimmering && AllowShimmerDodge(damageSource, cooldownCounter, dodgeable))
        {
            return 0.0;
        }
        if (creativeGodMode)
        {
            return 0.0;
        }
        bool flag = !immune;
        bool flag2 = false;
        int hitContext = cooldownCounter;
        switch (cooldownCounter)
        {
        case 0:
        case 1:
        case 3:
        case 4:
            flag = hurtCooldowns[cooldownCounter] <= 0;
            break;
        case 2:
            flag2 = true;
            cooldownCounter = -1;
            break;
        }
        if (flag)
        {
            if (dodgeable)
            {
                if (whoAmI == Main.myPlayer && blackBelt && Main.rand.Next(10) == 0)
                {
                    NinjaDodge();
                    return 0.0;
                }
                if (whoAmI == Main.myPlayer && brainOfConfusionItem != null && !brainOfConfusionItem.IsAir && Main.rand.Next(6) == 0 && FindBuffIndex(321) == -1)
                {
                    BrainOfConfusionDodge();
                    return 0.0;
                }
                if (whoAmI == Main.myPlayer && shadowDodge)
                {
                    ShadowDodge();
                    return 0.0;
                }
            }
            if (whoAmI == Main.myPlayer && panic)
            {
                AddBuff(63, 480);
            }
            if (whoAmI == Main.myPlayer && setSquireT2)
            {
                AddBuff(205, 300);
            }
            stealth = 1f;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(84, -1, -1, null, whoAmI);
            }
            int num = Damage;
            double num2 = Main.CalculateDamagePlayersTake(num, statDefense);
            if (Crit)
            {
                num *= 2;
            }
            if (num2 >= 1.0)
            {
                if (whoAmI == Main.myPlayer)
                {
                    Main.NotifyOfEvent(GameNotificationType.Damage);
                    if (hasFootball)
                    {
                        for (int i = 0; i < 59; i++)
{
                            if (inventory[i].stack > 0 && inventory[i].type == 4743)
{
                                Projectile.NewProjectile(GetProjectileSource_Misc(12), base.Center, new Vector2(-hitDirection * 4, -6f), 861, 0, 0f, whoAmI, 0f, 1f);
                                inventory[i].SetDefaults();
                                if (i == 58)
{
                                    Main.mouseItem = new Item();
                                }
                            }
                        }
                    }
                }
                if (inventory[selectedItem].type == 4790 || inventory[selectedItem].type == 4788 || inventory[selectedItem].type == 4789)
                {
                    for (int j = 0; j < 1000; j++)
                    {
                        if (Main.projectile[j].active && Main.projectile[j].owner == whoAmI && (Main.projectile[j].type == 879 || Main.projectile[j].type == 877 || Main.projectile[j].type == 878))
{
                            Main.projectile[j].active = false;
                        }
                    }
                }
                if (invis)
                {
                    for (int k = 0; k < maxBuffs; k++)
                    {
                        if (buffType[k] == 10)
{
                            DelBuff(k);
                        }
                    }
                }
                num2 = (int)((double)(1f - endurance) * num2);
                if (num2 < 1.0)
                {
                    num2 = 1.0;
                }
                if (ConsumeSolarFlare())
                {
                    float num3 = 0.2f;
                    num2 = (int)((double)(1f - num3) * num2);
                    if (num2 < 1.0)
                    {
                        num2 = 1.0;
                    }
                    if (whoAmI == Main.myPlayer)
                    {
                        IEntitySource spawnSource = GetProjectileSource_SetBonus(1);
                        Entity entity = null;
                        if (damageSource.TryGetCausingEntity(out entity))
{
                            spawnSource = GetProjectileSource_OnHurt(entity, 1);
                        }
                        int num4 = Projectile.NewProjectile(spawnSource, base.Center.X, base.Center.Y, 0f, 0f, 608, (int)(150f * meleeDamage), 15f, Main.myPlayer);
                        Main.projectile[num4].netUpdate = true;
                        Main.projectile[num4].Kill();
                    }
                }
                if (beetleDefense && beetleOrbs > 0)
                {
                    float num5 = 0.15f * (float)beetleOrbs;
                    num2 = (int)((double)(1f - num5) * num2);
                    beetleOrbs--;
                    for (int l = 0; l < maxBuffs; l++)
                    {
                        if (buffType[l] >= 95 && buffType[l] <= 97)
{
                            DelBuff(l);
                        }
                    }
                    if (beetleOrbs > 0)
                    {
                        AddBuff(95 + beetleOrbs - 1, 5, quiet: false);
                    }
                    beetleCounter = 0f;
                    if (num2 < 1.0)
                    {
                        num2 = 1.0;
                    }
                }
                if (magicCuffs)
                {
                    int num6 = num;
                    statMana += num6;
                    if (statMana > statManaMax2)
                    {
                        statMana = statManaMax2;
                    }
                    ManaEffect(num6);
                }
                if (defendedByPaladin)
                {
                    if (whoAmI != Main.myPlayer)
                    {
                        if (Main.player[Main.myPlayer].hasPaladinShield)
{
                            Player player = Main.player[Main.myPlayer];
                            if (player.team == team && team != 0)
{
                                float num7 = player.Distance(base.Center);
                                bool flag3 = num7 < 800f;
                                if (flag3)
{
                                    for (int m = 0; m < 255; m++)
{
                                        if (m != Main.myPlayer && Main.player[m].active && !Main.player[m].dead && !Main.player[m].immune && Main.player[m].hasPaladinShield && Main.player[m].team == team && (float)Main.player[m].statLife > (float)Main.player[m].statLifeMax2 * 0.25f)
{
                                            float num8 = Main.player[m].Distance(base.Center);
                                            if (num7 > num8 || (num7 == num8 && m < Main.myPlayer))
{
                                                flag3 = false;
                                                break;
                                            }
                                        }
                                    }
                                }
                                if (flag3)
{
                                    int damage = (int)(num2 * 0.25);
                                    num2 = (int)(num2 * 0.75);
                                    player.Hurt(PlayerDeathReason.LegacyEmpty(), damage, 0);
                                }
                            }
                        }
                    }
                    else
                    {
                        bool flag4 = false;
                        for (int n = 0; n < 255; n++)
{
                            if (n != Main.myPlayer && Main.player[n].active && !Main.player[n].dead && !Main.player[n].immune && Main.player[n].hasPaladinShield && Main.player[n].team == team && (float)Main.player[n].statLife > (float)Main.player[n].statLifeMax2 * 0.25f)
{
                                flag4 = true;
                                break;
                            }
                        }
                        if (flag4)
{
                            num2 = (int)(num2 * 0.75);
                        }
                    }
                }
                if (brainOfConfusionItem != null && !brainOfConfusionItem.IsAir && Main.myPlayer == whoAmI)
                {
                    for (int num9 = 0; num9 < 200; num9++)
                    {
                        if (!Main.npc[num9].active || Main.npc[num9].friendly)
{
                            continue;
                        }
                        int num10 = 300;
                        num10 += (int)num2 * 2;
                        if (Main.rand.Next(500) < num10)
{
                            float num11 = (Main.npc[num9].Center - base.Center).Length();
                            float num12 = Main.rand.Next(200 + (int)num2 / 2, 301 + (int)num2 * 2);
                            if (num12 > 500f)
{
                                num12 = 500f + (num12 - 500f) * 0.75f;
                            }
                            if (num12 > 700f)
{
                                num12 = 700f + (num12 - 700f) * 0.5f;
                            }
                            if (num12 > 900f)
{
                                num12 = 900f + (num12 - 900f) * 0.25f;
                            }
                            if (num11 < num12)
{
                                float num13 = Main.rand.Next(90 + (int)num2 / 3, 300 + (int)num2 / 2);
                                Main.npc[num9].AddBuff(31, (int)num13);
                            }
                        }
                    }
                    Projectile.NewProjectile(GetProjectileSource_Accessory(brainOfConfusionItem), base.Center.X + (float)Main.rand.Next(-40, 40), base.Center.Y - (float)Main.rand.Next(20, 60), velocity.X * 0.3f, velocity.Y * 0.3f, 565, 0, 0f, whoAmI);
                }
                if (Main.netMode == 1 && whoAmI == Main.myPlayer && !quiet)
                {
                    if (!noKnockback && hitDirection != 0 && (!mount.Active || !mount.Cart))
                    {
                        NetMessage.SendData(13, -1, -1, null, whoAmI);
                    }
                    NetMessage.SendData(16, -1, -1, null, whoAmI);
                    NetMessage.SendPlayerHurt(whoAmI, damageSource, Damage, hitDirection, Crit, pvp, hitContext);
                }
                Color color = (Crit ? CombatText.DamagedFriendlyCrit : CombatText.DamagedFriendly);
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), color, (int)num2, Crit);
                statLife -= (int)num2;
                switch (cooldownCounter)
                {
                case -1:
                {
                    immune = true;
                    int num14 = 0;
                    num14 = (pvp ? 8 : ((num2 != 1.0) ? (longInvince ? 80 : 40) : (longInvince ? 40 : 20)));
                    immuneTime = num14;
                    break;
                }
                case 0:
                    if (num2 == 1.0)
                    {
                        hurtCooldowns[cooldownCounter] = (longInvince ? 40 : 20);
                    }
                    else
                    {
                        hurtCooldowns[cooldownCounter] = (longInvince ? 80 : 40);
                    }
                    break;
                case 1:
                case 3:
                case 4:
                    if (num2 == 1.0)
                    {
                        hurtCooldowns[cooldownCounter] = (longInvince ? 40 : 20);
                    }
                    else
                    {
                        hurtCooldowns[cooldownCounter] = (longInvince ? 80 : 40);
                    }
                    break;
                }
                lifeRegenTime = 0f;
                int? sourceProjectileType = damageSource.SourceProjectileType;
                if (sourceProjectileType.HasValue && ProjectileID.Sets.DismountsPlayersOnHit.IndexInRange(sourceProjectileType.Value) && ProjectileID.Sets.DismountsPlayersOnHit[sourceProjectileType.Value])
                {
                    mount.Dismount(this);
                }
                if (whoAmI == Main.myPlayer)
                {
                    if (starCloakItem != null && !starCloakItem.IsAir && (cooldownCounter == -1 || cooldownCounter == 1))
                    {
                        for (int num15 = 0; num15 < 3; num15++)
{
                            float x = position.X + (float)Main.rand.Next(-400, 400);
                            float y = position.Y - (float)Main.rand.Next(500, 800);
                            Vector2 vector = new Vector2(x, y);
                            float num16 = position.X + (float)(width / 2) - vector.X;
                            float num17 = position.Y + (float)(height / 2) - vector.Y;
                            num16 += (float)Main.rand.Next(-100, 101);
                            float num18 = (float)Math.Sqrt(num16 * num16 + num17 * num17);
                            num18 = 23f / num18;
                            num16 *= num18;
                            num17 *= num18;
                            int type = 726;
                            Item item = starCloakItem;
                            if (starCloakItem_starVeilOverrideItem != null)
{
                                item = starCloakItem_starVeilOverrideItem;
                                type = 725;
                            }
                            if (starCloakItem_beeCloakOverrideItem != null)
{
                                item = starCloakItem_beeCloakOverrideItem;
                                type = 724;
                            }
                            if (starCloakItem_manaCloakOverrideItem != null)
{
                                item = starCloakItem_manaCloakOverrideItem;
                                type = 723;
                            }
                            int num19 = 75;
                            if (Main.masterMode)
{
                                num19 *= 3;
                            }
                            else if (Main.expertMode)
{
                                num19 *= 2;
                            }
                            Projectile.NewProjectile(GetProjectileSource_Accessory(item), x, y, num16, num17, type, num19, 5f, whoAmI, 0f, position.Y);
                        }
                    }
                    if (honeyCombItem != null && !honeyCombItem.IsAir)
                    {
                        int num20 = 1;
                        if (Main.rand.Next(3) == 0)
{
                            num20++;
                        }
                        if (Main.rand.Next(3) == 0)
{
                            num20++;
                        }
                        if (strongBees && Main.rand.Next(3) == 0)
{
                            num20++;
                        }
                        float num21 = 13f;
                        if (strongBees)
{
                            num21 = 18f;
                        }
                        if (Main.masterMode)
{
                            num21 *= 2f;
                        }
                        else if (Main.expertMode)
{
                            num21 *= 1.5f;
                        }
                        IEntitySource projectileSource_Accessory = GetProjectileSource_Accessory(honeyCombItem);
                        for (int num22 = 0; num22 < num20; num22++)
{
                            float speedX = (float)Main.rand.Next(-35, 36) * 0.02f;
                            float speedY = (float)Main.rand.Next(-35, 36) * 0.02f;
                            Projectile.NewProjectile(projectileSource_Accessory, position.X, position.Y, speedX, speedY, beeType(), beeDamage((int)num21), beeKB(0f), Main.myPlayer);
                        }
                        AddBuff(48, 300);
                    }
                }
                StopVanityActions();
                if (flag2 && hitDirection != 0)
                {
                    if (!mount.Active || !mount.Cart)
                    {
                        float num23 = 10.5f;
                        float y2 = -7.5f;
                        if (noKnockback)
{
                            num23 = 2.5f;
                            y2 = -1.5f;
                        }
                        velocity.X = num23 * (float)hitDirection;
                        velocity.Y = y2;
                        fallStart = (int)(position.Y / 16f);
                    }
                }
                else if (!noKnockback && hitDirection != 0 && (!mount.Active || !mount.Cart))
                {
                    velocity.X = 4.5f * (float)hitDirection;
                    velocity.Y = -3.5f;
                    fallStart = (int)(position.Y / 16f);
                }
                if (stoned)
                {
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                }
                else if (mount.Active && mount.Type == 52)
                {
                    SoundEngine.PlaySound(3, (int)position.X, (int)position.Y, 6);
                }
                else if ((wereWolf || forceWerewolf) && !hideWolf)
                {
                    SoundEngine.PlaySound(3, (int)position.X, (int)position.Y, 6);
                }
                else if (frostArmor)
                {
                    SoundEngine.PlaySound(SoundID.Item27, position);
                }
                else if (boneArmor)
                {
                    SoundEngine.PlaySound(3, (int)position.X, (int)position.Y, 2);
                }
                else if (Main.dontStarveWorld && !Main.remixWorld)
                {
                    SoundEngine.PlaySound(Male ? SoundID.DSTMaleHurt : SoundID.DSTFemaleHurt, position);
                }
                else
                {
                    SoundEngine.PlaySound(Male ? 1 : 20, position);
                }
                eyeHelper.BlinkBecausePlayerGotHurt();
                if (statLife > 0)
                {
                    double num24 = num2 / (double)statLifeMax2 * 100.0;
                    float num25 = 2 * hitDirection;
                    float num26 = 0f;
                    if (flag2)
                    {
                        num24 *= 12.0;
                        num26 = 6f;
                    }
                    for (int num27 = 0; (double)num27 < num24; num27++)
                    {
                        if (stoned)
{
                            Dust.NewDust(position, width, height, 1, num25 + (float)hitDirection * num26 * Main.rand.NextFloat(), -2f);
                        }
                        else if (frostArmor)
{
                            int num28 = Dust.NewDust(position, width, height, 135, num25 + (float)hitDirection * num26 * Main.rand.NextFloat(), -2f);
                            Main.dust[num28].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                        }
                        else if (boneArmor)
{
                            int num29 = Dust.NewDust(position, width, height, 26, num25 + (float)hitDirection * num26 * Main.rand.NextFloat(), -2f);
                            Main.dust[num29].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                        }
                        else
{
                            Dust.NewDust(position, width, height, 5, num25 + (float)hitDirection * num26 * Main.rand.NextFloat(), -2f);
                        }
                    }
                }
                else
                {
                    statLife = 0;
                    if (whoAmI == Main.myPlayer)
                    {
                        KillMe(damageSource, num2, hitDirection, pvp);
                    }
                }
            }
            if (pvp)
            {
                num2 = Main.CalculateDamagePlayersTakeInPVP(num, statDefense);
            }
            return num2;
        }
        return 0.0;
    }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.CalculateDamagePlayersTake(), Terraria.Main.CalculateDamagePlayersTakeInPVP(), Terraria.GameContent.Damage, Terraria.CombatText.DamagedFriendly, Terraria.ID.ProjectileID.Sets.DismountsPlayersOnHit, Terraria.Entity.Distance(), Terraria.Main.dontStarveWorld, Terraria.ID.SoundID.DSTFemaleHurt, Terraria.ID.SoundID.DSTMaleHurt, Terraria.Main.dust, Terraria.Main.expertMode, Terraria.Player.Hurt(), Terraria.Item.IsAir, System.item, Terraria.ID.SoundID.Item27, Terraria.DataStructures.PlayerDeathReason.LegacyEmpty(), Terraria.Main.masterMode, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Projectile.NewProjectile(), Terraria.CombatText.NewText(), Terraria.Main.NotifyOfEvent(), Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.projectile, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendPlayerHurt(), Terraria.Item.SetDefaults(), System.Math.Sqrt(), Terraria.Player.team, and System.type.
Referenced by Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Player.Hurt(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.GameContent.DontStarveDarknessDamageDealer.Update(), and Terraria.Player.UpdateBuffs().