Terraria: Terraria.Player.FillAmmo
FillAmmo()
Item Terraria.Player.FillAmmo (int plr, Item newItem, GetItemSettings settings) inline
    {
        for (int i = 54; i < 58; i++)
        {
            if (inventory[i].type <= 0 || inventory[i].stack >= inventory[i].maxStack || !newItem.IsTheSameAs(inventory[i]))
            {
                continue;
            }
            SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
            if (newItem.stack + inventory[i].stack <= inventory[i].maxStack)
            {
                inventory[i].stack += newItem.stack;
                if (!settings.NoText)
                {
                    PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, newItem.stack);
                }
                DoCoins(i);
                if (plr == Main.myPlayer)
                {
                    Recipe.FindRecipes();
                }
                settings.HandlePostAction(inventory[i]);
                return new Item();
            }
            newItem.stack -= inventory[i].maxStack - inventory[i].stack;
            if (!settings.NoText)
            {
                PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, inventory[i].maxStack - inventory[i].stack);
            }
            inventory[i].stack = inventory[i].maxStack;
            DoCoins(i);
            if (plr == Main.myPlayer)
            {
                Recipe.FindRecipes();
            }
            settings.HandlePostAction(inventory[i]);
        }
        if (newItem.CanFillEmptyAmmoSlot())
        {
            for (int j = 54; j < 58; j++)
            {
                if (inventory[j].type == 0)
                {
                    newItem.shimmered = false;
                    inventory[j] = newItem;
                    if (!settings.NoText)
                    {
                        PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, newItem.stack);
                    }
                    DoCoins(j);
                    SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
                    if (plr == Main.myPlayer)
                    {
                        Recipe.FindRecipes();
                    }
                    settings.HandlePostAction(inventory[j]);
                    return new Item();
                }
            }
        }
        return newItem;
    }
References Terraria.Item.CanFillEmptyAmmoSlot(), Terraria.Recipe.FindRecipes(), Terraria.GetItemSettings.HandlePostAction(), Terraria.Item.IsTheSameAs(), Terraria.Item.maxStack, Terraria.Main.myPlayer, Terraria.PopupText.NewText(), Terraria.GetItemSettings.NoText, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Item.stack.