Terraria: Terraria.Player.TryUsingDiggerCart
TryUsingDiggerCart()
void Terraria.Player.TryUsingDiggerCart () inline private
    {
        if (whoAmI == Main.myPlayer && mount.Active && mount.Type == 39 && velocity.Y == 0f)
        {
            int num = 12;
            int num2 = 20;
            Vector2 vector = new Vector2(0f, gravDir * 10f);
            Vector2 trackWorldPosition = RotatedRelativePoint(base.Center + new Vector2(num * direction, gravDir * (float)num2));
            trackWorldPosition += vector;
            Tile tileSafely = Framing.GetTileSafely(trackWorldPosition);
            if (!tileSafely.active() || tileSafely.type != 314)
            {
                trackWorldPosition = RotatedRelativePoint(base.Center + new Vector2((float)(num * direction) * 0.5f, gravDir * (float)num2));
                trackWorldPosition += vector;
            }
            int digDirectionY = controlDown.ToInt() - controlUp.ToInt();
            if (controlUp.ToInt() + controlDown.ToInt() + controlLeft.ToInt() + controlRight.ToInt() > 0)
            {
                MinecartDiggerHelper.Instance.TryDigging(this, trackWorldPosition, direction, digDirectionY);
            }
        }
    }
References Terraria.Tile.active(), Terraria.Framing.GetTileSafely(), Terraria.GameContent.MinecartDiggerHelper.Instance, Terraria.Main.myPlayer, Terraria.GameContent.MinecartDiggerHelper.TryDigging(), and Terraria.Tile.type.