Terraria: Terraria.Player.bank2
bank2
Chest Terraria.Player.bank2 = new Chest(bank: true)
Definition at line 1265 of file Player.cs.
Referenced by Terraria.GameContent.UI.CustomCurrencyManager.BuyItem(), Terraria.Player.clientClone(), Terraria.Recipe.CollectItemsToCraftWithFrom(), Terraria.UI.ChestUI.DepositAll(), Terraria.UI.ItemSlot.DrawSavings(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), Terraria.UI.ChestUI.DrawSlots(), Terraria.UI.ChestUI.GetContainerUsageInfo(), Terraria.MessageBuffer.GetData(), Terraria.UI.ChestUI.LootAll(), Terraria.GameContent.Achievements.AchievementsHelper.OnPlayerEnteredWorld(), Terraria.UI.ChestUI.QuickStack(), Terraria.UI.ChestUI.Restock(), and Terraria.NetMessage.SendData().