Terraria: Terraria.Player.IsTileTypeInInteractionRange
IsTileTypeInInteractionRange()
bool Terraria.Player.IsTileTypeInInteractionRange (int targetTileType, TileReachCheckSettings settings) inline
Definition at line 33928 of file Player.cs.
    {
        Point point = position.ToTileCoordinates();
        Point point2 = base.BottomRight.ToTileCoordinates();
        settings.GetRanges(this, out var x, out var y);
        int num = Utils.Clamp(point.X - x + 1, 0, Main.maxTilesX - 1);
        int num2 = Utils.Clamp(point2.X + x - 1, 0, Main.maxTilesX - 1);
        int num3 = Utils.Clamp(point.Y - y + 1, 0, Main.maxTilesY - 1);
        int num4 = Utils.Clamp(point2.Y + y - 2, 0, Main.maxTilesY - 1);
        for (int i = num; i <= num2; i++)
        {
            for (int j = num3; j <= num4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile != null && tile.active() && tile.type == targetTileType)
                {
                    return true;
                }
            }
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.DataStructures.TileReachCheckSettings.GetRanges(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.TeleportPylonsSystem.IsPlayerNearAPylon().