Terraria: Terraria.Player.TryDroppingSingleItem
TryDroppingSingleItem()
void Terraria.Player.TryDroppingSingleItem (IEntitySource source, Item theItem) inline
    {
        if (theItem.stack > 0)
        {
            int num = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, theItem.type);
            Item obj = Main.item[num];
            obj.netDefaults(theItem.netID);
            obj.Prefix(theItem.prefix);
            obj.stack = theItem.stack;
            obj.velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
            obj.velocity.X = (float)Main.rand.Next(-20, 21) * 0.2f;
            obj.noGrabDelay = 100;
            obj.newAndShiny = false;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, num);
            }
        }
        theItem.TurnToAir(fullReset: true);
    }
References Terraria.Main.item, Terraria.Item.netDefaults(), Terraria.Item.netID, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.prefix, Terraria.Item.Prefix(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.Item.TurnToAir(), and Terraria.Item.type.
Referenced by Terraria.EquipmentLoadout.TryDroppingItems().