Terraria: Terraria.Player.PlayDroppedItemAnimation
PlayDroppedItemAnimation()
void Terraria.Player.PlayDroppedItemAnimation (int time) inline
Definition at line 4393 of file Player.cs.
    {
        nonTorch = selectedItem;
        int num = 58;
        inventory[num].TurnToAir();
        selectedItem = num;
        JustDroppedAnItem = true;
        SetItemAnimation(time);
        SetItemTime(time);
        DropSelectedItem_InterruptActionsThatUseAnimations();
    }
References Terraria.Player.DropSelectedItem_InterruptActionsThatUseAnimations(), Terraria.Player.inventory, Terraria.Player.JustDroppedAnItem, Terraria.Player.nonTorch, Terraria.Player.selectedItem, Terraria.Player.SetItemAnimation(), Terraria.Player.SetItemTime(), and Terraria.Item.TurnToAir().
Referenced by Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), and Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame().