Terraria: Terraria.Player.GetAnglerReward_Bait
GetAnglerReward_Bait()
void Terraria.Player.GetAnglerReward_Bait (IEntitySource source, int questsDone, float rarityReduction, ref GetItemSettings anglerRewardSettings) inline private
Definition at line 53046 of file Player.cs.
    {
        if (Main.rand.Next((int)(100f * rarityReduction)) > 50)
        {
            return;
        }
        Item item = new Item();
        if (Main.rand.Next((int)(15f * rarityReduction)) == 0)
        {
            item.SetDefaults(2676);
        }
        else if (Main.rand.Next((int)(5f * rarityReduction)) == 0)
        {
            item.SetDefaults(2675);
        }
        else
        {
            item.SetDefaults(2674);
        }
        if (Main.rand.Next(25) <= questsDone)
        {
            item.stack++;
        }
        if (Main.rand.Next(50) <= questsDone)
        {
            item.stack++;
        }
        if (Main.rand.Next(100) <= questsDone)
        {
            item.stack++;
        }
        if (Main.rand.Next(150) <= questsDone)
        {
            item.stack++;
        }
        if (Main.rand.Next(200) <= questsDone)
        {
            item.stack++;
        }
        if (Main.rand.Next(250) <= questsDone)
        {
            item.stack++;
        }
        item.position = base.Center;
        Item item2 = GetItem(whoAmI, item, GetItemSettings.NPCEntityToPlayerInventorySettings);
        if (item2.stack > 0)
        {
            int number = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
        }
    }
References Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GetItemSettings.NPCEntityToPlayerInventorySettings, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.