Terraria: Terraria.Player.OpenLockBox
OpenLockBox()
void Terraria.Player.OpenLockBox (int lockboxItemType) inline
Definition at line 8583 of file Player.cs.
    {
        bool flag = true;
        IEntitySource itemSource_OpenItem = GetItemSource_OpenItem(lockboxItemType);
        while (flag)
        {
            flag = false;
            int num = 0;
            int number = Item.NewItem(Type: Main.rand.Next(7) switch
            {
                1 => 3317,
                2 => 155,
                3 => 156,
                4 => (!Main.remixWorld) ? 157 : 2623,
                5 => 163,
                6 => 113,
                _ => 164,
            }, source: itemSource_OpenItem, X: (int)position.X, Y: (int)position.Y, Width: width, Height: height, Stack: 1, noBroadcast: false, pfix: -1);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
            if (Main.rand.Next(3) == 0)
            {
                int number2 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 329, 1, noBroadcast: false, -1);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number2, 1f);
                }
            }
        }
    }
References Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.remixWorld, and Terraria.NetMessage.SendData().
Referenced by Terraria.UI.ItemSlot.TryOpenContainer().