Terraria: Terraria.Player.QuickMinecartSnap
QuickMinecartSnap()
bool Terraria.Player.QuickMinecartSnap () inline private
Definition at line 5086 of file Player.cs.
    {
        bool result = false;
        List<Point> tilesIn = Collision.GetTilesIn(base.TopLeft - new Vector2(24f), base.BottomRight + new Vector2(24f));
        if (tilesIn.Count > 0)
        {
            Point? point = null;
            _ = base.Hitbox;
            for (int i = 0; i < tilesIn.Count; i++)
            {
                Point point2 = tilesIn[i];
                Tile tileSafely = Framing.GetTileSafely(point2.X, point2.Y);
                if (tileSafely.active() && tileSafely.type == 314)
                {
                    Vector2 vector = tilesIn[i].ToVector2() * 16f + new Vector2(8f);
                    if (!point.HasValue || (Distance(vector) < Distance(point.Value.ToVector2() * 16f + new Vector2(8f)) && Collision.CanHitLine(base.Center, 0, 0, vector, 0, 0)))
                    {
                        point = tilesIn[i];
                    }
                }
            }
            if (point.HasValue)
            {
                LaunchMinecartHook(point.Value.X, point.Value.Y);
                result = true;
            }
        }
        return result;
    }
References Terraria.Collision.CanHitLine(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.Entity.Distance(), Terraria.Framing.GetTileSafely(), Terraria.Collision.GetTilesIn(), Terraria.Player.LaunchMinecartHook(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Player.QuickMount().