Terraria: Terraria.Player.ModifyFlexibleWandPlacementInfo
ModifyFlexibleWandPlacementInfo()
bool Terraria.Player.ModifyFlexibleWandPlacementInfo (ref int tileType, ref int tileStyle, ref int? forcedRandom) inline private
Definition at line 37587 of file Player.cs.
    {
        FlexibleTileWand flexibleTileWand = HeldItem.GetFlexibleTileWand();
        if (flexibleTileWand == null)
        {
            return true;
        }
        if (whoAmI == Main.myPlayer)
        {
            Point point = new Point(tileTargetX, tileTargetY);
            if (FlexibleWandLastPosition != point)
            {
                FlexibleWandLastPosition = point;
                FlexibleWandRandomSeed = Main.rand.Next();
            }
        }
        if (flexibleTileWand.TryGetPlacementOption(this, FlexibleWandRandomSeed, FlexibleWandCycleOffset, out var option, out var _))
        {
            tileType = option.TileIdToPlace;
            tileStyle = option.TileStyleToPlace;
            forcedRandom = FlexibleWandCycleOffset;
            return true;
        }
        return false;
    }
References Terraria.Item.GetFlexibleTileWand(), Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and Terraria.GameContent.FlexibleTileWand.TryGetPlacementOption().