Terraria: Terraria.Player.ItemSpace
ItemSpace()
ItemSpaceStatus Terraria.Player.ItemSpace (Item newItem) inline
Definition at line 36958 of file Player.cs.
    {
        if (ItemID.Sets.IsAPickup[newItem.type])
        {
            return new ItemSpaceStatus(CanTakeItem: true);
        }
        if (newItem.uniqueStack && HasItem(newItem.type))
        {
            return new ItemSpaceStatus(CanTakeItem: false);
        }
        int num = 50;
        if (newItem.IsACoin)
        {
            num = 54;
        }
        for (int i = 0; i < num; i++)
        {
            if (CanItemSlotAccept(inventory[i], newItem))
            {
                return new ItemSpaceStatus(CanTakeItem: true);
            }
        }
        if (newItem.ammo > 0 && !newItem.notAmmo)
        {
            for (int j = 54; j < 58; j++)
            {
                if (CanGoIntoAmmoOnPickup(inventory[j], newItem))
                {
                    return new ItemSpaceStatus(CanTakeItem: true);
                }
            }
        }
        for (int k = 54; k < 58; k++)
        {
            if (inventory[k].type > 0 && inventory[k].stack < inventory[k].maxStack && newItem.IsTheSameAs(inventory[k]))
            {
                return new ItemSpaceStatus(CanTakeItem: true);
            }
        }
        if (ItemSpaceForCofveve(newItem))
        {
            return new ItemSpaceStatus(CanTakeItem: true, ItemIsGoingToVoidVault: true);
        }
        return new ItemSpaceStatus(CanTakeItem: false);
    }
References Terraria.Item.ammo, Terraria.Item.IsACoin, Terraria.ID.ItemID.Sets.IsAPickup, Terraria.Item.IsTheSameAs(), Terraria.Item.notAmmo, Terraria.Item.type, and Terraria.Item.uniqueStack.
Referenced by Terraria.Item.FindOwner(), Terraria.UI.ItemSlot.GetOverrideInstructions(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.UI.ItemSlot.OverrideHover(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.OverrideItemSlotHover(), Terraria.GameContent.Tile_Entities.TEHatRack.OverrideItemSlotHover(), Terraria.UI.ItemSlot.TryEnteringBuildingMode(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryGetItemGamepadOverrideInstructions(), and Terraria.GameContent.Tile_Entities.TEHatRack.TryGetItemGamepadOverrideInstructions().