Terraria: Terraria.Player.GetTileCutIgnorance
GetTileCutIgnorance()
bool[] Terraria.Player.GetTileCutIgnorance (bool allowRegrowth, bool fromTrap) inline
Definition at line 42438 of file Player.cs.
    {
        bool[] result = TileID.Sets.TileCutIgnore.None;
        if (allowRegrowth)
        {
            result = TileID.Sets.TileCutIgnore.Regrowth;
        }
        if (!fromTrap && dontHurtNature)
        {
            result = TileID.Sets.TileCutIgnore.IgnoreDontHurtNature;
        }
        return result;
    }
References Terraria.ID.TileID.Sets.TileCutIgnore.IgnoreDontHurtNature, Terraria.ID.TileID.Sets.TileCutIgnore.None, and Terraria.ID.TileID.Sets.TileCutIgnore.Regrowth.
Referenced by Terraria.Projectile.CutTiles(), Terraria.Projectile.CutTilesAt(), and Terraria.Projectile.HandleMovement().