Terraria: Terraria.Player.GetClosestRollLuck
GetClosestRollLuck() [2/2]
static float Terraria.Player.GetClosestRollLuck (Vector2 position, int range) inline static
    {
        return Main.player[FindClosest(position, 1, 1)].RollLuck(range);
    }
References Terraria.Main.player, and Terraria.Player.RollLuck().
Referenced by Terraria.WorldGen.KillTile_DropBait(), Terraria.WorldGen.ShakeTree(), and Terraria.WorldGen.SpawnThingsFromPot().