Terraria: Terraria.Player.DoQueenSlimeHookTeleport
DoQueenSlimeHookTeleport()
void Terraria.Player.DoQueenSlimeHookTeleport (Vector2 targetPosition) inline
    {
        int num = 150;
        Vector2 vector = position;
        Vector2 vector2 = velocity;
        for (int i = 0; i < num; i++)
        {
            vector2 = (vector + base.Size / 2f).DirectionTo(targetPosition).SafeNormalize(Vector2.Zero) * 12f;
            Vector2 vector3 = Collision.TileCollision(vector, vector2, width, height, fallThrough: true, fall2: true, (int)gravDir);
            vector += vector3;
        }
        int num2 = 10;
        _ = vector - position;
        Teleport(vector, num2);
        NetMessage.SendData(65, -1, -1, null, 0, whoAmI, vector.X, vector.Y, num2);
    }
References Terraria.NetMessage.SendData(), and Terraria.Collision.TileCollision().
Referenced by Terraria.Projectile.AI_007_GrapplingHooks().