Terraria: Terraria.Player.SetTalkNPC
SetTalkNPC()
void Terraria.Player.SetTalkNPC (int npcIndex, bool fromNet = false) inline
Definition at line 3725 of file Player.cs.
    {
        talkNPC = npcIndex;
        if (Main.netMode != 1 && npcIndex >= 0 && npcIndex < 200)
        {
            Main.BestiaryTracker.Chats.RegisterChatStartWith(Main.npc[npcIndex]);
        }
        if (talkNPC == -1)
        {
            currentShoppingSettings = ShoppingSettings.NotInShop;
        }
        else
        {
            currentShoppingSettings = Main.ShopHelper.GetShoppingSettings(this, Main.npc[talkNPC]);
        }
        if (currentShoppingSettings.PriceAdjustment <= 0.8199999928474426)
        {
            AchievementsHelper.HandleSpecialEvent(this, 20);
        }
    }
References Terraria.Main.BestiaryTracker, Terraria.Player.currentShoppingSettings, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Main.netMode, Terraria.ShoppingSettings.NotInShop, Terraria.Main.npc, Terraria.ShoppingSettings.PriceAdjustment, Terraria.Main.ShopHelper, and Terraria.Player.talkNPC.
Referenced by Terraria.DataStructures.TileEntity.SetInteractionAnchor(), Terraria.Player.ToggleCreativeMenu(), and Terraria.Player.ToggleInv().