Terraria: Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag
GetItem_FillEmptyInventorySlot_VoidBag()
bool Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag (int plr, Item[] inv, Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
Definition at line 37323 of file Player.cs.
    {
        if (inv[i].type != 0)
        {
            return false;
        }
        if (newItem.IsACoin)
        {
            SoundEngine.PlaySound(38, (int)position.X, (int)position.Y);
        }
        else
        {
            SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
        }
        returnItem.shimmered = false;
        inv[i] = returnItem;
        if (!settings.NoText)
        {
            PopupText.NewText(PopupTextContext.ItemPickupToVoidContainer, newItem, newItem.stack, noStack: false, settings.LongText);
        }
        DoCoins(i);
        if (plr == Main.myPlayer)
        {
            Recipe.FindRecipes();
        }
        AchievementsHelper.NotifyItemPickup(this, returnItem);
        settings.HandlePostAction(inv[i]);
        return true;
    }
References Terraria.Recipe.FindRecipes(), Terraria.GetItemSettings.HandlePostAction(), Terraria.Item.IsACoin, Terraria.GetItemSettings.LongText, Terraria.Main.myPlayer, Terraria.PopupText.NewText(), Terraria.GetItemSettings.NoText, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Item.stack.