Terraria: Terraria.Player.RollLuck
RollLuck()
int Terraria.Player.RollLuck (int range) inline
    {
        if (luck > 0f && Main.rand.NextFloat() < luck)
        {
            return Main.rand.Next(Main.rand.Next(range / 2, range));
        }
        if (luck < 0f && Main.rand.NextFloat() < 0f - luck)
        {
            return Main.rand.Next(Main.rand.Next(range, range * 2));
        }
        return Main.rand.Next(range);
    }
References Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.rand.
Referenced by Terraria.GameContent.ItemDropRules.Conditions.FrostMoonDropGatingChance.CanDrop(), Terraria.GameContent.ItemDropRules.Conditions.PumpkinMoonDropGatingChance.CanDrop(), Terraria.Player.GetClosestRollLuck(), Terraria.Player.GetClosestRollLuck(), Terraria.Chest.SetupTravelShop(), Terraria.Chest.SetupTravelShop_GetItem(), Terraria.Chest.SetupTravelShop_GetPainting(), Terraria.GameContent.ItemDropRules.CommonDrop.TryDroppingItem(), Terraria.GameContent.ItemDropRules.CommonDropWithRerolls.TryDroppingItem(), Terraria.GameContent.ItemDropRules.DropOneByOne.TryDroppingItem(), Terraria.GameContent.ItemDropRules.MechBossSpawnersDropRule.TryDroppingItem(), and Terraria.GameContent.ItemDropRules.OneFromOptionsDropRule.TryDroppingItem().