Terraria: Terraria.Player.SaveTemporaryItemSlotContents
SaveTemporaryItemSlotContents()
void Terraria.Player.SaveTemporaryItemSlotContents (BinaryWriter writer) inline private
Definition at line 51402 of file Player.cs.
    {
        Item itemByIndex = Main.CreativeMenu.GetItemByIndex(0);
        BitsByte bitsByte = (byte)0;
        bitsByte[0] = !Main.mouseItem.IsAir;
        bitsByte[1] = !itemByIndex.IsAir;
        bitsByte[2] = !Main.guideItem.IsAir;
        bitsByte[3] = !Main.reforgeItem.IsAir;
        ItemSerializationContext context = ItemSerializationContext.SavingAndLoading;
        writer.Write(bitsByte);
        if (bitsByte[0])
        {
            Main.mouseItem.Serialize(writer, context);
        }
        if (bitsByte[1])
        {
            itemByIndex.Serialize(writer, context);
        }
        if (bitsByte[2])
        {
            Main.guideItem.Serialize(writer, context);
        }
        if (bitsByte[3])
        {
            Main.reforgeItem.Serialize(writer, context);
        }
    }
References Terraria.Main.CreativeMenu, Terraria.GameContent.Creative.CreativeUI.GetItemByIndex(), Terraria.Main.guideItem, Terraria.Item.IsAir, Terraria.Main.mouseItem, Terraria.Main.reforgeItem, and Terraria.Item.Serialize().
Referenced by Terraria.Player.Serialize().