Terraria: Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag
GetItem_FillIntoOccupiedSlot_VoidBag()
bool Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag (int plr, Item[] inv, Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
Definition at line 37243 of file Player.cs.
    {
        if (inv[i].type > 0 && inv[i].stack < inv[i].maxStack && returnItem.IsTheSameAs(inv[i]))
        {
            if (newItem.IsACoin)
            {
                SoundEngine.PlaySound(38, (int)position.X, (int)position.Y);
            }
            else
            {
                SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
            }
            if (returnItem.stack + inv[i].stack <= inv[i].maxStack)
            {
                inv[i].stack += returnItem.stack;
                if (!settings.NoText)
                {
                    PopupText.NewText(PopupTextContext.ItemPickupToVoidContainer, newItem, returnItem.stack, noStack: false, settings.LongText);
                }
                AchievementsHelper.NotifyItemPickup(this, returnItem);
                settings.HandlePostAction(inv[i]);
                return true;
            }
            AchievementsHelper.NotifyItemPickup(this, returnItem, inv[i].maxStack - inv[i].stack);
            returnItem.stack -= inv[i].maxStack - inv[i].stack;
            if (!settings.NoText)
            {
                PopupText.NewText(PopupTextContext.ItemPickupToVoidContainer, newItem, inv[i].maxStack - inv[i].stack, noStack: false, settings.LongText);
            }
            inv[i].stack = inv[i].maxStack;
            settings.HandlePostAction(inv[i]);
        }
        return false;
    }
References Terraria.GetItemSettings.HandlePostAction(), Terraria.Item.IsACoin, Terraria.Item.IsTheSameAs(), Terraria.GetItemSettings.LongText, Terraria.Item.maxStack, Terraria.PopupText.NewText(), Terraria.GetItemSettings.NoText, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Item.stack.