Terraria: Terraria.Player.OpenGoodieBag
OpenGoodieBag()
void Terraria.Player.OpenGoodieBag (int itemType) inline
Definition at line 8731 of file Player.cs.
    {
        IEntitySource itemSource_OpenItem = GetItemSource_OpenItem(itemType);
        if (Main.rand.Next(150) == 0)
        {
            int number = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1810);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
            return;
        }
        if (Main.rand.Next(150) == 0)
        {
            int number2 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1800);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number2, 1f);
            }
            return;
        }
        if (Main.rand.Next(4) == 0)
        {
            int number3 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1809, Main.rand.Next(10, 41));
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number3, 1f);
            }
            return;
        }
        if (Main.rand.Next(10) == 0)
        {
            int number4 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, Main.rand.Next(1846, 1851));
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number4, 1f);
            }
            return;
        }
        switch (Main.rand.Next(19))
        {
        case 0:
        {
            int number6 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1749);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number6, 1f);
            }
            number6 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1750);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number6, 1f);
            }
            number6 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1751);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number6, 1f);
            }
            break;
        }
        case 1:
        {
            int number17 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1746);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number17, 1f);
            }
            number17 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1747);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number17, 1f);
            }
            number17 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1748);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number17, 1f);
            }
            break;
        }
        case 2:
        {
            int number18 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1752);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number18, 1f);
            }
            number18 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1753);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number18, 1f);
            }
            break;
        }
        case 3:
        {
            int number19 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1767);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number19, 1f);
            }
            number19 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1768);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number19, 1f);
            }
            number19 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1769);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number19, 1f);
            }
            break;
        }
        case 4:
        {
            int number11 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1770);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number11, 1f);
            }
            number11 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1771);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number11, 1f);
            }
            break;
        }
        case 5:
        {
            int number8 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1772);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number8, 1f);
            }
            number8 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1773);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number8, 1f);
            }
            break;
        }
        case 6:
        {
            int number22 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1754);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number22, 1f);
            }
            number22 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1755);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number22, 1f);
            }
            number22 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1756);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number22, 1f);
            }
            break;
        }
        case 7:
        {
            int number10 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1757);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number10, 1f);
            }
            number10 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1758);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number10, 1f);
            }
            number10 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1759);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number10, 1f);
            }
            break;
        }
        case 8:
        {
            int number12 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1760);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number12, 1f);
            }
            number12 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1761);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number12, 1f);
            }
            number12 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1762);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number12, 1f);
            }
            break;
        }
        case 9:
        {
            int number20 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1763);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number20, 1f);
            }
            number20 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1764);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number20, 1f);
            }
            number20 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1765);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number20, 1f);
            }
            break;
        }
        case 10:
        {
            int number14 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1766);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number14, 1f);
            }
            number14 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1775);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number14, 1f);
            }
            number14 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1776);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number14, 1f);
            }
            break;
        }
        case 11:
        {
            int number7 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1777);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number7, 1f);
            }
            number7 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1778);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number7, 1f);
            }
            break;
        }
        case 12:
        {
            int number16 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1779);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number16, 1f);
            }
            number16 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1780);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number16, 1f);
            }
            number16 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1781);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number16, 1f);
            }
            break;
        }
        case 13:
        {
            int number13 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1819);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number13, 1f);
            }
            number13 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1820);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number13, 1f);
            }
            break;
        }
        case 14:
        {
            int number23 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1821);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number23, 1f);
            }
            number23 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1822);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number23, 1f);
            }
            number23 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1823);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number23, 1f);
            }
            break;
        }
        case 15:
        {
            int number21 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1824);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number21, 1f);
            }
            break;
        }
        case 16:
        {
            int number15 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1838);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number15, 1f);
            }
            number15 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1839);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number15, 1f);
            }
            number15 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1840);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number15, 1f);
            }
            break;
        }
        case 17:
        {
            int number9 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1841);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number9, 1f);
            }
            number9 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1842);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number9, 1f);
            }
            number9 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1843);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number9, 1f);
            }
            break;
        }
        case 18:
        {
            int number5 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1851);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number5, 1f);
            }
            number5 = Item.NewItem(itemSource_OpenItem, (int)position.X, (int)position.Y, width, height, 1852);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number5, 1f);
            }
            break;
        }
        }
    }
References Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.rand, and Terraria.NetMessage.SendData().
Referenced by Terraria.UI.ItemSlot.TryOpenContainer().