Terraria: Terraria.Player.GetAnglerReward_MainReward
GetAnglerReward_MainReward()
void Terraria.Player.GetAnglerReward_MainReward (IEntitySource source, int questsDone, float rarityReduction, int questItemType, ref GetItemSettings anglerRewardSettings) inline private
Definition at line 52803 of file Player.cs.
    {
        Item item = new Item();
        item.type = 0;
        switch (questsDone)
        {
        case 5:
            item.SetDefaults(2428);
            break;
        case 10:
            item.SetDefaults(2367);
            break;
        case 15:
            item.SetDefaults(2368);
            break;
        case 20:
            item.SetDefaults(2369);
            break;
        case 25:
            item.SetDefaults(3031);
            break;
        case 30:
            item.SetDefaults(2294);
            break;
        default:
        {
            if (questItemType == 2451 && Main.hardMode)
            {
                item.SetDefaults((Main.rand.Next(2) == 0) ? 5303 : 5302);
                break;
            }
            if (questItemType == 2451 && !Main.hardMode && Main.rand.Next(2) == 0)
            {
                item.SetDefaults((Main.rand.Next(2) == 0) ? 5303 : 5302);
                break;
            }
            List<int> list = new List<int> { 2373, 2374, 2375, 3120, 3037, 3096, 5139 };
            float num = 1f;
            for (int i = 0; i < 3; i++)
            {
                num *= 1f - 1f / (float)(int)(40f * rarityReduction);
            }
            for (int j = 0; j < 3; j++)
            {
                num *= 1f - 1f / (float)(int)(30f * rarityReduction);
            }
            num *= 1f - 1f / (float)(int)(25f * rarityReduction);
            float num2 = 1f - num;
            num2 *= 0.8f;
            if (questsDone > 75 && Main.rand.Next((int)(250f * rarityReduction)) == 0)
            {
                item.SetDefaults(2294);
                break;
            }
            if (Main.hardMode && questsDone > 25 && Main.rand.Next((int)(100f * rarityReduction)) == 0)
            {
                item.SetDefaults(2422);
                break;
            }
            if (Main.hardMode && questsDone > 10 && Main.rand.Next((int)(70f * rarityReduction)) == 0)
            {
                item.SetDefaults(2494);
                break;
            }
            if (questsDone > 10 && Main.rand.Next((int)(70f * rarityReduction)) == 0)
            {
                item.SetDefaults(3031);
                break;
            }
            if (questsDone > 10 && Main.rand.Next((int)(70f * rarityReduction)) == 0)
            {
                item.SetDefaults(3032);
                break;
            }
            if (Main.rand.Next((int)(80f * rarityReduction)) == 0)
            {
                item.SetDefaults(3183);
                break;
            }
            if (Main.rand.Next((int)(60f * rarityReduction)) == 0)
            {
                item.SetDefaults(2360);
                break;
            }
            if (Main.rand.Next((int)(60f * rarityReduction)) == 0)
            {
                item.SetDefaults(4067);
                break;
            }
            if (Main.rand.Next((int)(80f * rarityReduction)) == 0)
            {
                item.SetDefaults(2417);
                break;
            }
            if (Main.rand.Next((int)(80f * rarityReduction)) == 0)
            {
                item.SetDefaults(2498);
                break;
            }
            if (DropAnglerAccByMissing(list, num2, out var botheredRollingForADrop, out var itemIdToDrop))
            {
                item.SetDefaults(itemIdToDrop);
                break;
            }
            if (!botheredRollingForADrop && Main.rand.NextDouble() < (double)num2)
            {
                int defaults = Utils.SelectRandom(Main.rand, list.ToArray());
                item.SetDefaults(defaults);
                break;
            }
            switch (Main.rand.Next(3))
            {
            case 0:
                item.SetDefaults(2354);
                item.stack = Main.rand.Next(2, 6);
                break;
            case 1:
                item.SetDefaults(2355);
                item.stack = Main.rand.Next(2, 6);
                break;
            default:
                item.SetDefaults(2356);
                item.stack = Main.rand.Next(2, 6);
                break;
            }
            break;
        }
        }
        item.position = base.Center;
        Item item2 = GetItem(whoAmI, item, anglerRewardSettings);
        if (item2.stack > 0)
        {
            int number = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
        }
        if (item.type == 2417)
        {
            Item item3 = new Item();
            Item item4 = new Item();
            item3.SetDefaults(2418);
            item3.position = base.Center;
            item2 = GetItem(whoAmI, item3, anglerRewardSettings);
            if (item2.stack > 0)
            {
                int number2 = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number2, 1f);
                }
            }
            item4.SetDefaults(2419);
            item4.position = base.Center;
            item2 = GetItem(whoAmI, item4, anglerRewardSettings);
            if (item2.stack > 0)
            {
                int number3 = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number3, 1f);
                }
            }
        }
        else
        {
            if (item.type != 2498)
            {
                return;
            }
            Item item5 = new Item();
            Item item6 = new Item();
            item5.SetDefaults(2499);
            item5.position = base.Center;
            item2 = GetItem(whoAmI, item5, anglerRewardSettings);
            if (item2.stack > 0)
            {
                int number4 = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number4, 1f);
                }
            }
            item6.SetDefaults(2500);
            item6.position = base.Center;
            item2 = GetItem(whoAmI, item6, anglerRewardSettings);
            if (item2.stack > 0)
            {
                int number5 = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number5, 1f);
                }
            }
        }
    }
References Terraria.Main.hardMode, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.