Terraria: Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.BuildGrid
BuildGrid()
void Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.BuildGrid () inline private
    {
        int num = 2;
        int num2 = 26 + num;
        int num3 = 0;
        for (int i = 0; i < _sorter.Steps.Count; i++)
        {
            if (!_sorter.Steps[i].HiddenFromSortOptions)
            {
                num3++;
            }
        }
        UIPanel uIPanel = new UIPanel
        {
            Width = new StyleDimension(126f, 0f),
            Height = new StyleDimension(num3 * num2 + 5 + 3, 0f),
            HAlign = 1f,
            VAlign = 0f,
            Left = new StyleDimension(-118f, 0f),
            Top = new StyleDimension(0f, 0f)
        };
        uIPanel.BorderColor = new Color(89, 116, 213, 255) * 0.9f;
        uIPanel.BackgroundColor = new Color(73, 94, 171) * 0.9f;
        uIPanel.SetPadding(0f);
        Append(uIPanel);
        int num4 = 0;
        for (int j = 0; j < _sorter.Steps.Count; j++)
        {
            IBestiarySortStep bestiarySortStep = _sorter.Steps[j];
            if (!bestiarySortStep.HiddenFromSortOptions)
            {
                GroupOptionButton<int> groupOptionButton = new GroupOptionButton<int>(j, Language.GetText(bestiarySortStep.GetDisplayNameKey()), null, Color.White, null, 0.8f)
                {
                    Width = new StyleDimension(114f, 0f),
                    Height = new StyleDimension(num2 - num, 0f),
                    HAlign = 0.5f,
                    Top = new StyleDimension(5 + num2 * num4, 0f)
                };
                groupOptionButton.ShowHighlightWhenSelected = false;
                groupOptionButton.OnLeftClick += ClickOption;
                groupOptionButton.SetSnapPoint("SortSteps", num4);
                uIPanel.Append(groupOptionButton);
                _buttonsBySorting.Add(groupOptionButton);
                num4++;
            }
        }
        foreach (GroupOptionButton<int> item in _buttonsBySorting)
        {
            item.SetCurrentOption(-1);
        }
    }
References Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid._buttonsBySorting, Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid._sorter, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.ClickOption(), Terraria.DataStructures.IEntrySortStep< T >.GetDisplayNameKey(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.Bestiary.IBestiarySortStep.HiddenFromSortOptions, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.DataStructures.EntrySorter< TEntryType, TStepType >.Steps, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.UIBestiarySortingOptionsGrid().