Terraria: System.Linq.Expressions.Compiler.StackSpiller.MemberMemberBindingRewriter.AsExpression
AsExpression()
override Expression System.Linq.Expressions.Compiler.StackSpiller.MemberMemberBindingRewriter.AsExpression (Expression target) inline package
Definition at line 106 of file StackSpiller.cs.
        {
            RequireNoValueProperty();
            Expression expression = MemberExpression.Make(target, _binding.Member);
            Expression expression2 = _spiller.MakeTemp(expression.Type);
            int count = _bindings.Count;
            Expression[] array = new Expression[count + 2];
            array[0] = new AssignBinaryExpression(expression2, expression);
            for (int i = 0; i < count; i++)
            {
                BindingRewriter bindingRewriter = _bindingRewriters[i];
                array[i + 1] = bindingRewriter.AsExpression(expression2);
            }
            if (expression2.Type.IsValueType)
            {
                array[count + 1] = Expression.Block(typeof(void), new AssignBinaryExpression(MemberExpression.Make(target, _binding.Member), expression2));
            }
            else
            {
                array[count + 1] = Utils.Empty;
            }
            return MakeBlock(array);
        }
References System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter._binding, System.Linq.Expressions.Compiler.StackSpiller.MemberMemberBindingRewriter._bindingRewriters, System.Linq.Expressions.Compiler.StackSpiller.MemberMemberBindingRewriter._bindings, System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter._spiller, System.array, System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Utils.Empty, System.Linq.Expressions.MemberExpression.Make(), System.Linq.Expressions.Compiler.StackSpiller.MakeBlock(), System.Linq.Expressions.Compiler.StackSpiller.MakeTemp(), System.Linq.Expressions.MemberBinding.Member, and System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.RequireNoValueProperty().