Terraria: Terraria.GameContent.Golf.FancyGolfPredictionLine.Update
Update()
void Terraria.GameContent.Golf.FancyGolfPredictionLine.Update (Entity golfBall, Vector2 impactVelocity, float roughLandResistance) inline
Definition at line 40 of file FancyGolfPredictionLine.cs.
    {
        bool flag = Main.tileSolid[379];
        Main.tileSolid[379] = false;
        _positions.Clear();
        _time += 1f / 60f;
        _entity.position = golfBall.position;
        _entity.width = golfBall.width;
        _entity.height = golfBall.height;
        GolfHelper.HitGolfBall(_entity, impactVelocity, roughLandResistance);
        _positions.Add(_entity.position);
        float angularVelocity = 0f;
        for (int i = 0; i < _iterations; i++)
        {
            GolfHelper.StepGolfBall(_entity, ref angularVelocity);
            _positions.Add(_entity.position);
        }
        Main.tileSolid[379] = flag;
    }
References Terraria.GameContent.Golf.FancyGolfPredictionLine._entity, Terraria.GameContent.Golf.FancyGolfPredictionLine._iterations, Terraria.GameContent.Golf.FancyGolfPredictionLine._positions, Terraria.GameContent.Golf.FancyGolfPredictionLine._time, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.Golf.GolfHelper.HitGolfBall(), Terraria.Entity.position, Terraria.GameContent.Golf.GolfHelper.StepGolfBall(), and Terraria.Main.tileSolid.