Terraria: CreativePowers.ASharedButtonPower.RequestUse
RequestUse()
void CreativePowers.ASharedButtonPower.RequestUse () inline inherited
         {
             NetPacket packet = NetCreativePowersModule.PreparePacket(PowerId, 0);
             NetManager.Instance.SendToServerOrLoopback(packet);
         }
References NetManager.Instance, CreativePowers.ASharedButtonPower.PowerId, NetCreativePowersModule.PreparePacket(), and NetManager.SendToServerOrLoopback().
Referenced by CreativePowers.ASharedButtonPower.button_OnClick().