Terraria: System.IO.ReadOnlyMemoryStream.ReadBuffer
ReadBuffer()
int System.IO.ReadOnlyMemoryStream.ReadBuffer (Span< byte > buffer) inline private
Definition at line 105 of file ReadOnlyMemoryStream.cs.
    {
        EnsureNotClosed();
        int num = _content.Length - _position;
        if (num <= 0 || buffer.Length == 0)
        {
            return 0;
        }
        ReadOnlySpan<byte> readOnlySpan;
        if (num <= buffer.Length)
        {
            readOnlySpan = _content.Span;
            readOnlySpan = readOnlySpan.Slice(_position);
            readOnlySpan.CopyTo(buffer);
            _position = _content.Length;
            return num;
        }
        readOnlySpan = _content.Span;
        readOnlySpan = readOnlySpan.Slice(_position, buffer.Length);
        readOnlySpan.CopyTo(buffer);
        _position += buffer.Length;
        return buffer.Length;
    }
References System.IO.ReadOnlyMemoryStream._content, System.IO.ReadOnlyMemoryStream._position, System.buffer, System.ReadOnlySpan< T >.CopyTo(), System.IO.ReadOnlyMemoryStream.EnsureNotClosed(), System.ReadOnlyMemory< T >.Length, System.ReadOnlySpan< T >.Slice(), and System.ReadOnlyMemory< T >.Span.
Referenced by System.IO.ReadOnlyMemoryStream.Read(), System.IO.ReadOnlyMemoryStream.Read(), System.IO.ReadOnlyMemoryStream.ReadAsync(), and System.IO.ReadOnlyMemoryStream.ReadAsync().