Terraria: System.IO.ReadOnlyMemoryStream.EnsureNotClosed
EnsureNotClosed()
void System.IO.ReadOnlyMemoryStream.EnsureNotClosed () inline private
Definition at line 53 of file ReadOnlyMemoryStream.cs.
    {
        if (!_isOpen)
        {
            throw new ObjectDisposedException(null, System.SR.ObjectDisposed_StreamClosed);
        }
    }
References System.IO.ReadOnlyMemoryStream._isOpen, and System.SR.ObjectDisposed_StreamClosed.
Referenced by System.IO.ReadOnlyMemoryStream.CopyTo(), System.IO.ReadOnlyMemoryStream.CopyToAsync(), System.IO.ReadOnlyMemoryStream.EndRead(), System.IO.ReadOnlyMemoryStream.ReadAsync(), System.IO.ReadOnlyMemoryStream.ReadAsync(), System.IO.ReadOnlyMemoryStream.ReadBuffer(), System.IO.ReadOnlyMemoryStream.ReadByte(), and System.IO.ReadOnlyMemoryStream.Seek().