Terraria: System.Xml.Xsl.XsltOld.CopyNamespacesAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.CopyNamespacesAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 14 of file CopyNamespacesAction.cs.
    {
        while (processor.CanContinue)
        {
            switch (frame.State)
            {
            default:
                return;
            case 0:
                if (!frame.Node.MoveToFirstNamespace(XPathNamespaceScope.ExcludeXml))
                {
                    frame.Finished();
                    return;
                }
                frame.State = 2;
                goto case 2;
            case 2:
                if (processor.BeginEvent(XPathNodeType.Namespace, null, frame.Node.LocalName, frame.Node.Value, empty: false))
                {
                    frame.State = 4;
                    break;
                }
                return;
            case 4:
                if (processor.EndEvent(XPathNodeType.Namespace))
                {
                    frame.State = 5;
                    break;
                }
                return;
            case 5:
                if (frame.Node.MoveToNextNamespace(XPathNamespaceScope.ExcludeXml))
                {
                    frame.State = 2;
                    break;
                }
                frame.Node.MoveToParent();
                frame.Finished();
                return;
            case 1:
            case 3:
                return;
            }
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveToFirstNamespace(), System.Xml.XPath.XPathNavigator.MoveToNextNamespace(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.Xsl.XsltOld.ActionFrame.Node, System.Xml.Xsl.XsltOld.ActionFrame.State, and System.Xml.XPath.XPathItem.Value.