Terraria: UIBestiarySortingOptionsGrid.ClickOption
ClickOption()
void UIBestiarySortingOptionsGrid.ClickOption (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         int num = ((GroupOptionButton<int>)listeningElement).OptionValue;
         if (num == _currentSelected)
         {
             num = _defaultStepIndex;
         }
         foreach (GroupOptionButton<int> item in _buttonsBySorting)
         {
             bool flag = num == item.OptionValue;
             item.SetCurrentOption(flag ? num : (-1));
             if (flag)
             {
                 item.SetColor(new Color(152, 175, 235), 1f);
             }
             else
             {
                 item.SetColor(Colors.InventoryDefaultColor, 0.7f);
             }
         }
         _currentSelected = num;
         _sorter.SetPrioritizedStepIndex(num);
         if (this.OnClickingOption != null)
         {
             this.OnClickingOption();
         }
     }
References _buttonsBySorting, _currentSelected, _defaultStepIndex, _sorter, Color, Colors.InventoryDefaultColor, OnClickingOption, GroupOptionButton< T >.OptionValue, GroupOptionButton< T >.SetColor(), GroupOptionButton< T >.SetCurrentOption(), and EntrySorter< TEntryType, TStepType >.SetPrioritizedStepIndex().
Referenced by BuildGrid().