Terraria: Modifiers.Blotches.Apply
Apply()
override bool Modifiers.Blotches.Apply (Point origin, int x, int y, params object[] args) inline virtual
Implements GenAction.
         {
             GenBase._random.NextDouble();
             if (GenBase._random.NextDouble() < _chance)
             {
                 bool flag = false;
                 int num = GenBase._random.Next(1 - _minX, 1);
                 int num2 = GenBase._random.Next(0, _maxX);
                 int num3 = GenBase._random.Next(1 - _minY, 1);
                 int num4 = GenBase._random.Next(0, _maxY);
                 for (int i = num; i <= num2; i++)
                 {
                     for (int j = num3; j <= num4; j++)
                     {
                         flag |= !UnitApply(origin, x + i, y + j, args);
                     }
                 }
                 return !flag;
             }
             return UnitApply(origin, x, y, args);
         }
References Modifiers.Blotches._chance, Modifiers.Blotches._maxX, Modifiers.Blotches._maxY, Modifiers.Blotches._minX, Modifiers.Blotches._minY, GenBase._random, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), and GenAction.UnitApply().