Terraria: System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteMembers
ReflectionWriteMembers()
override int System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteMembers (XmlWriterDelegator xmlWriter, object obj, XmlObjectSerializerWriteContext context, ClassDataContract classContract, ClassDataContract derivedMostClassContract, int childElementIndex, XmlDictionaryString[] memberNames) inline protected
Definition at line 9 of file ReflectionJsonClassWriter.cs.
    {
        int num = ((classContract.BaseContract != null) ? ReflectionWriteMembers(xmlWriter, obj, context, classContract.BaseContract, derivedMostClassContract, childElementIndex, memberNames) : 0);
        childElementIndex += num;
        context.IncrementItemCount(classContract.Members.Count);
        int num2 = 0;
        while (num2 < classContract.Members.Count)
        {
            DataMember dataMember = classContract.Members[num2];
            Type memberType = dataMember.MemberType;
            if (dataMember.IsGetOnlyCollection)
            {
                context.StoreIsGetOnlyCollection();
            }
            else
            {
                context.ResetIsGetOnlyCollection();
            }
            bool flag = true;
            object obj2 = null;
            if (!dataMember.EmitDefaultValue)
            {
                obj2 = ReflectionGetMemberValue(obj, dataMember);
                object defaultValue = XmlFormatGeneratorStatics.GetDefaultValue(memberType);
                if ((obj2 == null && defaultValue == null) || (obj2 != null && obj2.Equals(defaultValue)))
                {
                    flag = false;
                    if (dataMember.IsRequired)
                    {
                        XmlObjectSerializerWriteContext.ThrowRequiredMemberMustBeEmitted(dataMember.Name, classContract.UnderlyingType);
                    }
                }
            }
            if (flag)
            {
                if (obj2 == null)
                {
                    obj2 = ReflectionGetMemberValue(obj, dataMember);
                }
                bool flag2 = DataContractJsonSerializer.CheckIfXmlNameRequiresMapping(classContract.MemberNames[num2]);
                PrimitiveDataContract memberPrimitiveContract = dataMember.MemberPrimitiveContract;
                if (flag2 || !ReflectionTryWritePrimitive(xmlWriter, context, memberType, obj2, memberNames[num2 + childElementIndex], null, memberPrimitiveContract))
                {
                    if (flag2)
                    {
                        XmlObjectSerializerWriteContextComplexJson.WriteJsonNameWithMapping(xmlWriter, memberNames, num2 + childElementIndex);
                    }
                    else
                    {
                        ReflectionWriteStartElement(xmlWriter, memberNames[num2 + childElementIndex]);
                    }
                    ReflectionWriteValue(xmlWriter, context, memberType, obj2, writeXsiType: false, null);
                    ReflectionWriteEndElement(xmlWriter);
                }
                if (classContract.HasExtensionData)
                {
                    context.WriteExtensionData(xmlWriter, ((IExtensibleDataObject)obj).ExtensionData, num);
                }
            }
            num2++;
            num++;
        }
        return num;
    }
References System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfXmlNameRequiresMapping(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetDefaultValue(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Type.MemberType, System.obj, System.Runtime.Serialization.ReflectionClassWriter.ReflectionGetMemberValue(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionTryWritePrimitive(), System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteEndElement(), System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteMembers(), System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteStartElement(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResetIsGetOnlyCollection(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.StoreIsGetOnlyCollection(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.ThrowRequiredMemberMustBeEmitted(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionData(), and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteJsonNameWithMapping().
Referenced by System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteMembers().