Terraria: System.Xml.XmlBaseReader.NamespaceManager.AddAttribute
AddAttribute()
void System.Xml.XmlBaseReader.NamespaceManager.AddAttribute () inline private
Definition at line 782 of file XmlBaseReader.cs.
        {
            if (_attributes == null)
            {
                _attributes = new XmlAttribute[1];
            }
            else if (_attributes.Length == _attributeCount)
            {
                XmlAttribute[] array = new XmlAttribute[_attributeCount * 2];
                Array.Copy(_attributes, array, _attributeCount);
                _attributes = array;
            }
            XmlAttribute xmlAttribute = _attributes[_attributeCount];
            if (xmlAttribute == null)
            {
                xmlAttribute = new XmlAttribute();
                _attributes[_attributeCount] = xmlAttribute;
            }
            xmlAttribute.XmlLang = _lang;
            xmlAttribute.XmlSpace = _space;
            xmlAttribute.Depth = _depth;
            _attributeCount++;
        }
References System.Xml.XmlBaseReader.NamespaceManager._attributeCount, System.Xml.XmlBaseReader.NamespaceManager._attributes, System.Xml.XmlBaseReader.NamespaceManager._depth, System.Xml.XmlBaseReader.NamespaceManager._lang, System.Xml.XmlBaseReader.NamespaceManager._space, System.array, System.Array.Copy(), and System.Xml.Dictionary.
Referenced by System.Xml.XmlBaseReader.AddAttribute(), System.Xml.XmlBaseReader.NamespaceManager.AddLangAttribute(), System.Xml.XmlBaseReader.NamespaceManager.AddSpaceAttribute(), System.Xml.XmlBaseReader.AddXmlAttribute(), and System.Xml.XmlBaseReader.AddXmlnsAttribute().