Terraria: System.Xml.XmlBaseReader.NamespaceManager.LookupNamespace
LookupNamespace() [2/3]
Namespace System.Xml.XmlBaseReader.NamespaceManager.LookupNamespace (PrefixHandleType prefix) inline
Definition at line 843 of file XmlBaseReader.cs.
        {
            return _shortPrefixUri[(int)prefix];
        }
References System.Xml.XmlBaseReader.NamespaceManager._shortPrefixUri, and System.prefix.
Referenced by System.Xml.XmlBaseReader.NamespaceManager.LookupNamespace(), System.Xml.XmlBaseReader.NamespaceManager.LookupNamespace(), and System.Xml.XmlBaseReader.ProcessAttributes().