Terraria: UIItemSlot.HandleItemSlotLogic
HandleItemSlotLogic()
void UIItemSlot.HandleItemSlotLogic () inline private
     {
         if (base.IsMouseHovering)
         {
             Main.LocalPlayer.mouseInterface = true;
             Item inv = _itemArray[_itemIndex];
             ItemSlot.OverrideHover(ref inv, _itemSlotContext);
             ItemSlot.LeftClick(ref inv, _itemSlotContext);
             ItemSlot.RightClick(ref inv, _itemSlotContext);
             ItemSlot.MouseHover(ref inv, _itemSlotContext);
             _itemArray[_itemIndex] = inv;
         }
     }
References _itemArray, _itemIndex, _itemSlotContext, ItemSlot.LeftClick(), Main.LocalPlayer, ItemSlot.MouseHover(), Player.mouseInterface, ItemSlot.OverrideHover(), and ItemSlot.RightClick().
Referenced by DrawSelf().