Terraria: UIItemSlot.DrawSelf
DrawSelf()
override void UIItemSlot.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         HandleItemSlotLogic();
         Item inv = _itemArray[_itemIndex];
         Vector2 position = GetDimensions().Center() + new Vector2(52f, 52f) * -0.5f * Main.inventoryScale;
         ItemSlot.Draw(spriteBatch, ref inv, _itemSlotContext, position);
     }
References _itemArray, _itemIndex, _itemSlotContext, CalculatedStyle.Center(), ItemSlot.Draw(), UIElement.GetDimensions(), HandleItemSlotLogic(), and Main.inventoryScale.