Terraria: System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.GetSignatureAlgorithmIdentifier
GetSignatureAlgorithmIdentifier()
override byte[] System.Security.Cryptography.X509Certificates.RSAPkcs1X509SignatureGenerator.GetSignatureAlgorithmIdentifier (HashAlgorithmName hashAlgorithm) inline
Definition at line 33 of file RSAPkcs1X509SignatureGenerator.cs.
    {
        string oidValue;
        if (hashAlgorithm == HashAlgorithmName.SHA256)
        {
            oidValue = "1.2.840.113549.1.1.11";
        }
        else if (hashAlgorithm == HashAlgorithmName.SHA384)
        {
            oidValue = "1.2.840.113549.1.1.12";
        }
        else
        {
            if (!(hashAlgorithm == HashAlgorithmName.SHA512))
            {
                throw new ArgumentOutOfRangeException("hashAlgorithm", hashAlgorithm, System.SR.Format(System.SR.Cryptography_UnknownHashAlgorithm, hashAlgorithm.Name));
            }
            oidValue = "1.2.840.113549.1.1.13";
        }
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.PushSequence();
        asnWriter.WriteObjectIdentifier(oidValue);
        asnWriter.WriteNull();
        asnWriter.PopSequence();
        return asnWriter.Encode();
    }
References System.SR.Cryptography_UnknownHashAlgorithm, System.Formats.Asn1.AsnWriter.Encode(), System.SR.Format(), System.Security.Cryptography.HashAlgorithmName.Name, System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PushSequence(), System.Security.Cryptography.HashAlgorithmName.SHA256, System.Security.Cryptography.HashAlgorithmName.SHA384, System.Security.Cryptography.HashAlgorithmName.SHA512, System.Formats.Asn1.AsnWriter.WriteNull(), and System.Formats.Asn1.AsnWriter.WriteObjectIdentifier().