Terraria: System.Net.Http.FailedProxyCache.CleanupHelper
CleanupHelper()
void System.Net.Http.FailedProxyCache.CleanupHelper () inline private
Definition at line 59 of file FailedProxyCache.cs.
    {
        bool lockTaken = false;
        try
        {
            _flushLock.TryEnter(ref lockTaken);
            if (!lockTaken)
            {
                return;
            }
            long tickCount = Environment.TickCount64;
            foreach (KeyValuePair<Uri, long> failedProxy in _failedProxies)
            {
                if (tickCount >= failedProxy.Value)
                {
                    ((ICollection<KeyValuePair<Uri, long>>)_failedProxies).Remove(failedProxy);
                }
            }
        }
        finally
        {
            if (lockTaken)
            {
                Interlocked.Exchange(ref _nextFlushTicks, Environment.TickCount64 + 300000);
                _flushLock.Exit(useMemoryBarrier: false);
            }
        }
    }
References System.Net.Http.FailedProxyCache._failedProxies, System.Net.Http.FailedProxyCache._flushLock, System.Net.Http.FailedProxyCache._nextFlushTicks, System.Threading.Interlocked.Exchange(), System.Threading.SpinLock.Exit(), System.Environment.TickCount64, and System.Threading.SpinLock.TryEnter().
Referenced by System.Net.Http.FailedProxyCache.Cleanup().