Terraria: System.Net.Http.FailedProxyCache.Cleanup
Cleanup()
void System.Net.Http.FailedProxyCache.Cleanup () inline private
Definition at line 50 of file FailedProxyCache.cs.
    {
        if (_failedProxies.Count > 8 && Environment.TickCount64 >= Interlocked.Read(ref _nextFlushTicks))
        {
            CleanupHelper();
        }
    }
References System.Net.Http.FailedProxyCache._failedProxies, System.Net.Http.FailedProxyCache._nextFlushTicks, System.Net.Http.FailedProxyCache.CleanupHelper(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Interlocked.Read(), and System.Environment.TickCount64.
Referenced by System.Net.Http.FailedProxyCache.GetProxyRenewTicks(), and System.Net.Http.FailedProxyCache.SetProxyFailed().