Terraria: System.Xml.XmlBinaryWriter.SetOutput
SetOutput() [1/3]
void System.Xml.XmlBinaryWriter.SetOutput (Stream stream, IXmlDictionary dictionary, XmlBinaryWriterSession session, bool ownsStream) inline
Definition at line 14 of file XmlBinaryWriter.cs.
    {
        if (stream == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("stream"));
        }
        if (_writer == null)
        {
            _writer = new XmlBinaryNodeWriter();
        }
        _writer.SetOutput(stream, dictionary, session, ownsStream);
        SetOutput(_writer);
    }
References System.Xml.XmlBinaryWriter._writer, System.dictionary, System.Xml.Dictionary, System.Xml.XmlBinaryNodeWriter.SetOutput(), System.Xml.XmlBinaryWriter.SetOutput(), System.stream, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Xml.XmlBinaryWriter.SetOutput().