Terraria: System.Net.NetworkInformation.NetworkChange.AddressChangeListener.AddressChangedCallback
AddressChangedCallback()
static void System.Net.NetworkInformation.NetworkChange.AddressChangeListener.AddressChangedCallback (object stateObject, bool signaled) inline static private
Definition at line 100 of file NetworkChange.cs.
        {
            Dictionary<NetworkAddressChangedEventHandler, ExecutionContext> dictionary = null;
            lock (s_globalLock)
            {
                s_isPending = false;
                if (!s_isListening)
                {
                    return;
                }
                s_isListening = false;
                if (s_addressChangedSubscribers.Count > 0)
                {
                    dictionary = new Dictionary<NetworkAddressChangedEventHandler, ExecutionContext>(s_addressChangedSubscribers);
                }
                try
                {
                    StartHelper(null, captureContext: false, (StartIPOptions)stateObject);
                }
                catch (NetworkInformationException message)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Error(null, message, "AddressChangedCallback");
                    }
                }
            }
            if (dictionary == null)
            {
                return;
            }
            foreach (KeyValuePair<NetworkAddressChangedEventHandler, ExecutionContext> item in dictionary)
            {
                NetworkAddressChangedEventHandler key = item.Key;
                ExecutionContext value = item.Value;
                if (value == null)
                {
                    key(null, EventArgs.Empty);
                }
                else
                {
                    ExecutionContext.Run(value, s_runAddressChangedHandler, key);
                }
            }
        }
References System.dictionary, System.EventArgs.Empty, System.Net.NetEventSource.Error(), System.item, System.key, System.Net.NetEventSource.Log, System.Net.NetworkInformation.NetworkAddressChangedEventHandler(), System.Threading.ExecutionContext.Run(), System.Net.NetworkInformation.NetworkChange.s_addressChangedSubscribers, System.Net.NetworkInformation.NetworkChange.s_globalLock, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.s_isListening, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.s_isPending, System.Net.NetworkInformation.NetworkChange.s_runAddressChangedHandler, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.StartHelper(), and System.value.
Referenced by System.Net.NetworkInformation.NetworkChange.AddressChangeListener.StartHelper().