Terraria: System.Xml.XmlBinaryWriter.UnsafeWriteArray
UnsafeWriteArray() [2/2]
unsafe void System.Xml.XmlBinaryWriter.UnsafeWriteArray (string prefix, XmlDictionaryString localName, XmlDictionaryString namespaceUri, XmlBinaryNodeType nodeType, int count, byte * array, byte * arrayMax) inline private
Definition at line 160 of file XmlBinaryWriter.cs.
    {
        WriteStartArray(prefix, localName, namespaceUri, count);
        _writer.UnsafeWriteArray(nodeType, count, array, arrayMax);
        WriteEndArray();
    }
References System.Xml.XmlBinaryWriter._writer, System.array, System.count, System.Xml.Dictionary, System.prefix, System.Xml.XmlBinaryNodeWriter.UnsafeWriteArray(), System.Xml.XmlBinaryWriter.WriteEndArray(), and System.Xml.XmlBinaryWriter.WriteStartArray().