Terraria: System.Net.NetworkInformation.NetworkChange.AddressChangeListener.StartHelper
StartHelper()
static void System.Net.NetworkInformation.NetworkChange.AddressChangeListener.StartHelper (NetworkAddressChangedEventHandler caller, bool captureContext, StartIPOptions startIPOptions) inline static private
Definition at line 156 of file NetworkChange.cs.
        {
            lock (s_globalLock)
            {
                if (s_ipv4Socket == null)
                {
                    if (Socket.OSSupportsIPv4)
                    {
                        s_ipv4Socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.IP)
{
                            Blocking = false
                        };
                        s_ipv4WaitHandle = new AutoResetEvent(initialState: false);
                    }
                    if (Socket.OSSupportsIPv6)
                    {
                        s_ipv6Socket = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.IP)
{
                            Blocking = false
                        };
                        s_ipv6WaitHandle = new AutoResetEvent(initialState: false);
                    }
                }
                if (caller != null)
                {
                    s_addressChangedSubscribers.TryAdd(caller, captureContext ? ExecutionContext.Capture() : null);
                }
                if (s_isListening || s_addressChangedSubscribers.Count == 0)
                {
                    return;
                }
                if (!s_isPending)
                {
                    if (Socket.OSSupportsIPv4 && (startIPOptions & StartIPOptions.StartIPv4) != 0)
                    {
                        ThreadPool.RegisterWaitForSingleObject(s_ipv4WaitHandle, AddressChangedCallback, StartIPOptions.StartIPv4, -1, executeOnlyOnce: true);
                        if (global::Interop.Winsock.WSAIoctl_Blocking(s_ipv4Socket.SafeHandle, 671088663, null, 0, null, 0, out var _, IntPtr.Zero, IntPtr.Zero) != 0)
{
                            NetworkInformationException ex = new NetworkInformationException();
                            if ((long)ex.ErrorCode != 10035)
{
                                throw ex;
                            }
                        }
                        if (global::Interop.Winsock.WSAEventSelect(s_ipv4Socket.SafeHandle, s_ipv4WaitHandle.GetSafeWaitHandle(), global::Interop.Winsock.AsyncEventBits.FdAddressListChange) != 0)
{
                            throw new NetworkInformationException();
                        }
                    }
                    if (Socket.OSSupportsIPv6 && (startIPOptions & StartIPOptions.StartIPv6) != 0)
                    {
                        ThreadPool.RegisterWaitForSingleObject(s_ipv6WaitHandle, AddressChangedCallback, StartIPOptions.StartIPv6, -1, executeOnlyOnce: true);
                        if (global::Interop.Winsock.WSAIoctl_Blocking(s_ipv6Socket.SafeHandle, 671088663, null, 0, null, 0, out var _, IntPtr.Zero, IntPtr.Zero) != 0)
{
                            NetworkInformationException ex2 = new NetworkInformationException();
                            if ((long)ex2.ErrorCode != 10035)
{
                                throw ex2;
                            }
                        }
                        if (global::Interop.Winsock.WSAEventSelect(s_ipv6Socket.SafeHandle, s_ipv6WaitHandle.GetSafeWaitHandle(), global::Interop.Winsock.AsyncEventBits.FdAddressListChange) != 0)
{
                            throw new NetworkInformationException();
                        }
                    }
                }
                s_isListening = true;
                s_isPending = true;
            }
        }
References System.Net.NetworkInformation.NetworkChange.AddressChangeListener.AddressChangedCallback(), System.Threading.ExecutionContext.Capture(), System.Net.Sockets.Socket.OSSupportsIPv4, System.Net.Sockets.Socket.OSSupportsIPv6, System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Net.NetworkInformation.NetworkChange.s_addressChangedSubscribers, System.Net.NetworkInformation.NetworkChange.s_globalLock, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.s_ipv4Socket, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.s_ipv4WaitHandle, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.s_ipv6Socket, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.s_ipv6WaitHandle, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.s_isListening, System.Net.NetworkInformation.NetworkChange.AddressChangeListener.s_isPending, System.Net.Sockets.Socket, and System.IntPtr.Zero.
Referenced by System.Net.NetworkInformation.NetworkChange.AddressChangeListener.AddressChangedCallback(), System.Net.NetworkInformation.NetworkChange.AddressChangeListener.Start(), and System.Net.NetworkInformation.NetworkChange.AddressChangeListener.UnsafeStart().