Terraria: System.Xml.XmlBinaryWriter.CheckArray
CheckArray()
void System.Xml.XmlBinaryWriter.CheckArray (Array array, int offset, int count) inline private
Definition at line 167 of file XmlBinaryWriter.cs.
    {
        if (array == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("array"));
        }
        if (offset < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative));
        }
        if (offset > array.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, array.Length)));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > array.Length - offset)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, array.Length - offset)));
        }
    }
References System.array, System.count, System.SR.Format(), System.offset, System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.ValueMustBeNonNegative.
Referenced by System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), and System.Xml.XmlBinaryWriter.WriteArray().