Terraria: System.Xml.XmlBinaryWriter.WriteArray
WriteArray() [10/40]
override void System.Xml.XmlBinaryWriter.WriteArray (string prefix, string localName, string namespaceUri, TimeSpan[] array, int offset, int count) inline
Definition at line 403 of file XmlBinaryWriter.cs.
    {
        CheckArray(array, offset, count);
        if (count > 0)
        {
            WriteStartArray(prefix, localName, namespaceUri, count);
            _writer.WriteTimeSpanArray(array, offset, count);
            WriteEndArray();
        }
    }
References System.Xml.XmlBinaryWriter._writer, System.array, System.Xml.XmlBinaryWriter.CheckArray(), System.count, System.offset, System.prefix, System.Xml.XmlBinaryWriter.WriteEndArray(), System.Xml.XmlBinaryWriter.WriteStartArray(), and System.Xml.XmlBinaryNodeWriter.WriteTimeSpanArray().