Terraria: System.Xml.XmlBinaryWriter.WriteStartArray
WriteStartArray() [1/2]
void System.Xml.XmlBinaryWriter.WriteStartArray (string prefix, string localName, string namespaceUri, int count) inline private
Definition at line 132 of file XmlBinaryWriter.cs.
    {
        StartArray(count);
        _writer.WriteArrayNode();
        WriteStartElement(prefix, localName, namespaceUri);
        WriteEndElement();
    }
References System.Xml.XmlBinaryWriter._writer, System.count, System.prefix, System.Xml.XmlBaseWriter.StartArray(), System.Xml.XmlBinaryNodeWriter.WriteArrayNode(), System.Xml.XmlBaseWriter.WriteEndElement(), and System.Xml.XmlBaseWriter.WriteStartElement().
Referenced by System.Xml.XmlBinaryWriter.UnsafeWriteArray(), System.Xml.XmlBinaryWriter.UnsafeWriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), System.Xml.XmlBinaryWriter.WriteArray(), and System.Xml.XmlBinaryWriter.WriteArray().