Terraria: System.Xml.XmlBinaryWriter.WriteTextNode
WriteTextNode()
override void System.Xml.XmlBinaryWriter.WriteTextNode (XmlDictionaryReader reader, bool attribute) inline protected virtual
Reimplemented from System.Xml.XmlDictionaryWriter.
Definition at line 33 of file XmlBinaryWriter.cs.
    {
        Type valueType = reader.ValueType;
        if (valueType == typeof(string))
        {
            if (reader.TryGetValueAsDictionaryString(out XmlDictionaryString value))
            {
                WriteString(value);
            }
            else if (reader.CanReadValueChunk)
            {
                if (_chars == null)
                {
                    _chars = new char[256];
                }
                int count;
                while ((count = reader.ReadValueChunk(_chars, 0, _chars.Length)) > 0)
                {
                    WriteChars(_chars, 0, count);
                }
            }
            else
            {
                WriteString(reader.Value);
            }
            if (!attribute)
            {
                reader.Read();
            }
        }
        else if (valueType == typeof(byte[]))
        {
            if (reader.CanReadBinaryContent)
            {
                if (_bytes == null)
                {
                    _bytes = new byte[384];
                }
                int count2;
                while ((count2 = reader.ReadValueAsBase64(_bytes, 0, _bytes.Length)) > 0)
                {
                    WriteBase64(_bytes, 0, count2);
                }
            }
            else
            {
                WriteString(reader.Value);
            }
            if (!attribute)
            {
                reader.Read();
            }
        }
        else if (valueType == typeof(int))
        {
            WriteValue(reader.ReadContentAsInt());
        }
        else if (valueType == typeof(long))
        {
            WriteValue(reader.ReadContentAsLong());
        }
        else if (valueType == typeof(bool))
        {
            WriteValue(reader.ReadContentAsBoolean());
        }
        else if (valueType == typeof(double))
        {
            WriteValue(reader.ReadContentAsDouble());
        }
        else if (valueType == typeof(DateTime))
        {
            WriteValue(reader.ReadContentAsDateTimeOffset().DateTime);
        }
        else if (valueType == typeof(float))
        {
            WriteValue(reader.ReadContentAsFloat());
        }
        else if (valueType == typeof(decimal))
        {
            WriteValue(reader.ReadContentAsDecimal());
        }
        else if (valueType == typeof(UniqueId))
        {
            WriteValue(reader.ReadContentAsUniqueId());
        }
        else if (valueType == typeof(Guid))
        {
            WriteValue(reader.ReadContentAsGuid());
        }
        else if (valueType == typeof(TimeSpan))
        {
            WriteValue(reader.ReadContentAsTimeSpan());
        }
        else
        {
            WriteValue(reader.ReadContentAsObject());
        }
    }
References System.Xml.XmlBinaryWriter._bytes, System.Xml.XmlBinaryWriter._chars, System.Xml.XmlReader.CanReadBinaryContent, System.Xml.XmlReader.CanReadValueChunk, System.count, System.DateTimeOffset.DateTime, System.Xml.Dictionary, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadContentAsBoolean(), System.Xml.XmlReader.ReadContentAsDateTimeOffset(), System.Xml.XmlDictionaryReader.ReadContentAsDecimal(), System.Xml.XmlReader.ReadContentAsDouble(), System.Xml.XmlDictionaryReader.ReadContentAsFloat(), System.Xml.XmlDictionaryReader.ReadContentAsGuid(), System.Xml.XmlReader.ReadContentAsInt(), System.Xml.XmlReader.ReadContentAsLong(), System.Xml.XmlReader.ReadContentAsObject(), System.Xml.XmlDictionaryReader.ReadContentAsTimeSpan(), System.Xml.XmlDictionaryReader.ReadContentAsUniqueId(), System.Xml.XmlDictionaryReader.ReadValueAsBase64(), System.Xml.XmlReader.ReadValueChunk(), System.Xml.XmlDictionaryReader.TryGetValueAsDictionaryString(), System.value, System.Xml.XmlReader.Value, System.Xml.XmlReader.ValueType, System.Xml.XmlBaseWriter.WriteBase64(), System.Xml.XmlBaseWriter.WriteChars(), System.Xml.XmlBaseWriter.WriteString(), and System.Xml.XmlBaseWriter.WriteValue().