Terraria: System.Collections.Specialized.HybridDictionary.ChangeOver
ChangeOver()
void System.Collections.Specialized.HybridDictionary.ChangeOver () inline private
Definition at line 147 of file HybridDictionary.cs.
    {
        IDictionaryEnumerator enumerator = list.GetEnumerator();
        Hashtable hashtable = ((!caseInsensitive) ? new Hashtable(13) : new Hashtable(13, StringComparer.OrdinalIgnoreCase));
        while (enumerator.MoveNext())
        {
            hashtable.Add(enumerator.Key, enumerator.Value);
        }
        this.hashtable = hashtable;
        list = null;
    }
References System.Collections.Hashtable.Add(), System.Collections.Specialized.HybridDictionary.caseInsensitive, System.Collections.Specialized.ListDictionary.GetEnumerator(), System.Collections.Specialized.HybridDictionary.hashtable, System.Collections.IDictionaryEnumerator.Key, System.Collections.Specialized.HybridDictionary.list, System.Collections.IEnumerator.MoveNext(), System.StringComparer.OrdinalIgnoreCase, and System.Collections.IDictionaryEnumerator.Value.
Referenced by System.Collections.Specialized.HybridDictionary.Add().