Terraria: Mount.UpdateEffects
UpdateEffects()
void Mount.UpdateEffects (Player mountedPlayer) inline
     {
         mountedPlayer.autoJump = AutoJump;
         _shouldSuperCart = MountID.Sets.Cart[_type] && mountedPlayer.UsingSuperCart;
         if (_shouldSuperCart)
         {
             CastSuperCartLaser(mountedPlayer);
             float num = 1f + Math.Abs(mountedPlayer.velocity.X) / RunSpeed * 2.5f;
             mountedPlayer.statDefense += (int)(2f * num);
         }
         switch (_type)
         {
         case 23:
         {
             Vector2 pos3 = mountedPlayer.Center + GetWitchBroomTrinketOriginOffset(mountedPlayer) + (GetWitchBroomTrinketRotation(mountedPlayer) + (float)Math.PI / 2f).ToRotationVector2() * 11f;
             Vector3 rgb = new Vector3(1f, 0.75f, 0.5f) * 0.85f;
             Vector2 vector11 = mountedPlayer.RotatedRelativePoint(pos3);
             Lighting.AddLight(vector11, rgb);
             if (Main.rand.Next(45) == 0)
             {
                 Vector2 vector12 = Main.rand.NextVector2Circular(4f, 4f);
                 Dust dust2 = Dust.NewDustPerfect(vector11 + vector12, 43, Vector2.Zero, 254, new Color(255, 255, 0, 255), 0.3f);
                 if (vector12 != Vector2.Zero)
                 {
                     dust2.velocity = vector11.DirectionTo(dust2.position) * 0.2f;
                 }
                 dust2.fadeIn = 0.3f;
                 dust2.noLightEmittence = true;
                 dust2.customData = mountedPlayer;
                 dust2.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMount, mountedPlayer);
             }
             float num13 = 0.1f;
             num13 += mountedPlayer.velocity.Length() / 30f;
             Vector2 pos4 = mountedPlayer.Center + new Vector2(18f - 20f * Main.rand.NextFloat() * (float)mountedPlayer.direction, 12f);
             Vector2 pos5 = mountedPlayer.Center + new Vector2(52 * mountedPlayer.direction, -6f);
             pos4 = mountedPlayer.RotatedRelativePoint(pos4);
             pos5 = mountedPlayer.RotatedRelativePoint(pos5);
             if (!(Main.rand.NextFloat() <= num13))
             {
                 break;
             }
             float num14 = Main.rand.NextFloat();
             for (float num15 = 0f; num15 < 1f; num15 += 0.125f)
             {
                 if (Main.rand.Next(15) == 0)
                 {
                     Vector2 spinningpoint = ((float)Math.PI * 2f * num15 + num14).ToRotationVector2() * new Vector2(0.5f, 1f) * 4f;
                     spinningpoint = spinningpoint.RotatedBy(mountedPlayer.fullRotation);
                     Dust dust3 = Dust.NewDustPerfect(pos4 + spinningpoint, 43, Vector2.Zero, 254, new Color(255, 255, 0, 255), 0.3f);
                     dust3.velocity = spinningpoint * 0.025f + pos5.DirectionTo(dust3.position) * 0.5f;
                     dust3.fadeIn = 0.3f;
                     dust3.noLightEmittence = true;
                     dust3.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMount, mountedPlayer);
                 }
             }
             break;
         }
         case 25:
             DoGemMinecartEffect(mountedPlayer, 86);
             break;
         case 26:
             DoGemMinecartEffect(mountedPlayer, 87);
             break;
         case 27:
             DoGemMinecartEffect(mountedPlayer, 88);
             break;
         case 28:
             DoGemMinecartEffect(mountedPlayer, 89);
             break;
         case 29:
             DoGemMinecartEffect(mountedPlayer, 90);
             break;
         case 30:
             DoGemMinecartEffect(mountedPlayer, 91);
             break;
         case 31:
             DoGemMinecartEffect(mountedPlayer, 262);
             break;
         case 9:
         case 46:
         {
             if (_type == 46)
             {
                 mountedPlayer.hasJumpOption_Santank = true;
             }
             Vector2 center = mountedPlayer.Center;
             Vector2 vector10 = center;
             bool flag = false;
             float num9 = 1500f;
             float num10 = 850f;
             for (int i = 0; i < 200; i++)
             {
                 NPC nPC = Main.npc[i];
                 if (!nPC.CanBeChasedBy(this))
                 {
                     continue;
                 }
                 Vector2 v = nPC.Center - center;
                 float num11 = v.Length();
                 if (num11 < num10 && ((Vector2.Distance(vector10, center) > num11 && num11 < num9) || !flag))
                 {
                     bool flag2 = true;
                     float num12 = Math.Abs(v.ToRotation());
                     if (mountedPlayer.direction == 1 && (double)num12 > 1.047197594907988)
                     {
                         flag2 = false;
                     }
                     else if (mountedPlayer.direction == -1 && (double)num12 < 2.0943951461045853)
                     {
                         flag2 = false;
                     }
                     if (Collision.CanHitLine(center, 0, 0, nPC.position, nPC.width, nPC.height) && flag2)
                     {
                         num9 = num11;
                         vector10 = nPC.Center;
                         flag = true;
                     }
                 }
             }
             if (flag)
             {
                 bool flag3 = _abilityCooldown == 0;
                 if (_type == 46)
                 {
                     flag3 = _abilityCooldown % 10 == 0;
                 }
                 if (flag3 && mountedPlayer.whoAmI == Main.myPlayer)
                 {
                     AimAbility(mountedPlayer, vector10);
                     if (_abilityCooldown == 0)
                     {
                         StopAbilityCharge();
                     }
                     UseAbility(mountedPlayer, vector10, toggleOn: false);
                 }
                 else
                 {
                     AimAbility(mountedPlayer, vector10);
                     _abilityCharging = true;
                 }
             }
             else
             {
                 _abilityCharging = false;
                 ResetHeadPosition();
             }
             break;
         }
         case 10:
             mountedPlayer.hasJumpOption_Unicorn = true;
             if (Math.Abs(mountedPlayer.velocity.X) > mountedPlayer.mount.DashSpeed - mountedPlayer.mount.RunSpeed / 2f)
             {
                 mountedPlayer.noKnockback = true;
             }
             if (mountedPlayer.itemAnimation > 0 && mountedPlayer.inventory[mountedPlayer.selectedItem].type == 1260)
             {
                 AchievementsHelper.HandleSpecialEvent(mountedPlayer, 5);
             }
             break;
         case 47:
             mountedPlayer.hasJumpOption_WallOfFleshGoat = true;
             if (Math.Abs(mountedPlayer.velocity.X) > mountedPlayer.mount.DashSpeed - mountedPlayer.mount.RunSpeed / 2f)
             {
                 mountedPlayer.noKnockback = true;
             }
             break;
         case 14:
             mountedPlayer.hasJumpOption_Basilisk = true;
             if (Math.Abs(mountedPlayer.velocity.X) > mountedPlayer.mount.DashSpeed - mountedPlayer.mount.RunSpeed / 2f)
             {
                 mountedPlayer.noKnockback = true;
             }
             break;
         case 40:
         case 41:
         case 42:
             if (Math.Abs(mountedPlayer.velocity.X) > mountedPlayer.mount.DashSpeed - mountedPlayer.mount.RunSpeed / 2f)
             {
                 mountedPlayer.noKnockback = true;
             }
             break;
         case 12:
             if (mountedPlayer.MountFishronSpecial)
             {
                 Vector3 vector9 = Colors.CurrentLiquidColor.ToVector3();
                 vector9 *= 0.4f;
                 Point point = (mountedPlayer.Center + Vector2.UnitX * mountedPlayer.direction * 20f + mountedPlayer.velocity * 10f).ToTileCoordinates();
                 if (!WorldGen.SolidTile(point.X, point.Y))
                 {
                     Lighting.AddLight(point.X, point.Y, vector9.X, vector9.Y, vector9.Z);
                 }
                 else
                 {
                     Lighting.AddLight(mountedPlayer.Center + Vector2.UnitX * mountedPlayer.direction * 20f, vector9.X, vector9.Y, vector9.Z);
                 }
                 mountedPlayer.meleeDamage += 0.15f;
                 mountedPlayer.rangedDamage += 0.15f;
                 mountedPlayer.magicDamage += 0.15f;
                 mountedPlayer.minionDamage += 0.15f;
             }
             if (mountedPlayer.statLife <= mountedPlayer.statLifeMax2 / 2)
             {
                 mountedPlayer.MountFishronSpecialCounter = 60f;
             }
             if (mountedPlayer.wet || (Main.raining && WorldGen.InAPlaceWithWind(mountedPlayer.position, mountedPlayer.width, mountedPlayer.height)))
             {
                 mountedPlayer.MountFishronSpecialCounter = 420f;
             }
             break;
         case 8:
             if (mountedPlayer.ownedProjectileCounts[453] < 1)
             {
                 _abilityActive = false;
             }
             break;
         case 11:
         {
             Vector3 vector4 = new Vector3(0.4f, 0.12f, 0.15f);
             float num4 = 1f + Math.Abs(mountedPlayer.velocity.X) / RunSpeed * 2.5f;
             int num5 = Math.Sign(mountedPlayer.velocity.X);
             if (num5 == 0)
             {
                 num5 = mountedPlayer.direction;
             }
             if (Main.netMode == 2)
             {
                 break;
             }
             vector4 *= num4;
             Lighting.AddLight(mountedPlayer.Center, vector4.X, vector4.Y, vector4.Z);
             Lighting.AddLight(mountedPlayer.Top, vector4.X, vector4.Y, vector4.Z);
             Lighting.AddLight(mountedPlayer.Bottom, vector4.X, vector4.Y, vector4.Z);
             Lighting.AddLight(mountedPlayer.Left, vector4.X, vector4.Y, vector4.Z);
             Lighting.AddLight(mountedPlayer.Right, vector4.X, vector4.Y, vector4.Z);
             float num6 = -24f;
             if (mountedPlayer.direction != num5)
             {
                 num6 = -22f;
             }
             if (num5 == -1)
             {
                 num6 += 1f;
             }
             Vector2 vector5 = new Vector2(num6 * (float)num5, -19f).RotatedBy(mountedPlayer.fullRotation);
             Vector2 vector6 = new Vector2(MathHelper.Lerp(0f, -8f, mountedPlayer.fullRotation / ((float)Math.PI / 4f)), MathHelper.Lerp(0f, 2f, Math.Abs(mountedPlayer.fullRotation / ((float)Math.PI / 4f)))).RotatedBy(mountedPlayer.fullRotation);
             if (num5 == Math.Sign(mountedPlayer.fullRotation))
             {
                 vector6 *= MathHelper.Lerp(1f, 0.6f, Math.Abs(mountedPlayer.fullRotation / ((float)Math.PI / 4f)));
             }
             Vector2 vector7 = mountedPlayer.Bottom + vector5 + vector6;
             Vector2 vector8 = mountedPlayer.oldPosition + mountedPlayer.Size * new Vector2(0.5f, 1f) + vector5 + vector6;
             if (Vector2.Distance(vector7, vector8) > 3f)
             {
                 int num7 = (int)Vector2.Distance(vector7, vector8) / 3;
                 if (Vector2.Distance(vector7, vector8) % 3f != 0f)
                 {
                     num7++;
                 }
                 for (float num8 = 1f; num8 <= (float)num7; num8 += 1f)
                 {
                     Dust obj = Main.dust[Dust.NewDust(mountedPlayer.Center, 0, 0, 182)];
                     obj.position = Vector2.Lerp(vector8, vector7, num8 / (float)num7);
                     obj.noGravity = true;
                     obj.velocity = Vector2.Zero;
                     obj.customData = mountedPlayer;
                     obj.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMinecart, mountedPlayer);
                 }
             }
             else
             {
                 Dust obj2 = Main.dust[Dust.NewDust(mountedPlayer.Center, 0, 0, 182)];
                 obj2.position = vector7;
                 obj2.noGravity = true;
                 obj2.velocity = Vector2.Zero;
                 obj2.customData = mountedPlayer;
                 obj2.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMinecart, mountedPlayer);
             }
             break;
         }
         case 22:
         {
             mountedPlayer.lavaMax += 420;
             Vector2 vector = mountedPlayer.Center + new Vector2(20f, 10f) * mountedPlayer.Directions;
             Vector2 pos = vector + mountedPlayer.velocity;
             Vector2 pos2 = vector + new Vector2(-1f, -0.5f) * mountedPlayer.Directions;
             vector = mountedPlayer.RotatedRelativePoint(vector);
             pos = mountedPlayer.RotatedRelativePoint(pos);
             pos2 = mountedPlayer.RotatedRelativePoint(pos2);
             Vector2 value = mountedPlayer.shadowPos[2] - mountedPlayer.position + vector;
             Vector2 vector2 = pos - vector;
             vector += vector2;
             value += vector2;
             Vector2 vector3 = pos - pos2;
             float num2 = MathHelper.Clamp(mountedPlayer.velocity.Length() / 5f, 0f, 1f);
             for (float num3 = 0f; num3 <= 1f; num3 += 0.1f)
             {
                 if (!(Main.rand.NextFloat() < num2))
                 {
                     Dust dust = Dust.NewDustPerfect(Vector2.Lerp(value, vector, num3), 65, Main.rand.NextVector2Circular(0.5f, 0.5f) * num2);
                     dust.scale = 0.6f;
                     dust.fadeIn = 0f;
                     dust.customData = mountedPlayer;
                     dust.velocity *= -1f;
                     dust.noGravity = true;
                     dust.velocity -= vector3;
                     dust.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMinecart, mountedPlayer);
                     if (Main.rand.Next(10) == 0)
                     {
                         dust.fadeIn = 1.3f;
                         dust.velocity = Main.rand.NextVector2Circular(3f, 3f) * num2;
                     }
                 }
             }
             break;
         }
         case 16:
             mountedPlayer.ignoreWater = true;
             break;
         case 24:
             DelegateMethods.v3_1 = new Vector3(0.1f, 0.3f, 1f) * 0.4f;
             Utils.PlotTileLine(mountedPlayer.MountedCenter, mountedPlayer.MountedCenter + mountedPlayer.velocity * 6f, 40f, DelegateMethods.CastLightOpen);
             Utils.PlotTileLine(mountedPlayer.Left, mountedPlayer.Right, 40f, DelegateMethods.CastLightOpen);
             break;
         case 36:
             DoSteamMinecartEffect(mountedPlayer, 303);
             break;
         case 32:
             DoExhaustMinecartEffect(mountedPlayer, 31);
             break;
         case 34:
             DoConfettiMinecartEffect(mountedPlayer);
             break;
         case 37:
             mountedPlayer.canFloatInWater = true;
             mountedPlayer.accFlipper = true;
             break;
         case 13:
         case 15:
         case 17:
         case 18:
         case 19:
         case 20:
         case 21:
         case 33:
         case 35:
         case 38:
         case 39:
         case 43:
         case 44:
         case 45:
             break;
         }
     }
References Player.accFlipper, Lighting.AddLight(), GameShaders.Armor, Player.autoJump, Entity.Bottom, NPC.CanBeChasedBy(), Player.canFloatInWater, Collision.CanHitLine(), MountID.Sets.Cart, DelegateMethods.CastLightOpen(), Entity.Center, Player.cMinecart, Player.cMount, Color, Colors.CurrentLiquidColor, Dust.customData, DashSpeed, Entity.direction, Player.Directions, Main.dust, Dust.fadeIn, Player.fullRotation, ArmorShaderDataSet.GetSecondaryShader(), AchievementsHelper.HandleSpecialEvent(), Player.hasJumpOption_Basilisk, Player.hasJumpOption_Santank, Player.hasJumpOption_Unicorn, Player.hasJumpOption_WallOfFleshGoat, Entity.height, Player.ignoreWater, WorldGen.InAPlaceWithWind(), Player.inventory, Player.itemAnimation, Player.lavaMax, Entity.Left, Player.magicDamage, Player.meleeDamage, Player.minionDamage, Player.mount, Player.MountedCenter, Player.MountFishronSpecial, Player.MountFishronSpecialCounter, Main.myPlayer, Main.netMode, Dust.NewDust(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Player.noKnockback, Dust.noLightEmittence, Main.npc, Entity.oldPosition, Player.ownedProjectileCounts, Utils.PlotTileLine(), Dust.position, Entity.position, Main.raining, Main.rand, Player.rangedDamage, Entity.Right, Player.RotatedRelativePoint(), RunSpeed, Dust.scale, Player.selectedItem, Dust.shader, Player.shadowPos, Entity.Size, WorldGen.SolidTile(), Player.statDefense, Player.statLife, Player.statLifeMax2, Entity.Top, Item.type, Player.UsingSuperCart, DelegateMethods.v3_1, Dust.velocity, Entity.velocity, Entity.wet, Entity.whoAmI, and Entity.width.