Terraria: System.Collections.Specialized.HybridDictionary.Add
Add()
void System.Collections.Specialized.HybridDictionary.Add (object key, object? value) inline
Implements System.Collections.IDictionary.
Definition at line 159 of file HybridDictionary.cs.
    {
        if (hashtable != null)
        {
            hashtable.Add(key, value);
        }
        else if (list == null)
        {
            list = new ListDictionary(caseInsensitive ? StringComparer.OrdinalIgnoreCase : null);
            list.Add(key, value);
        }
        else if (list.Count + 1 >= 9)
        {
            ChangeOver();
            hashtable.Add(key, value);
        }
        else
        {
            list.Add(key, value);
        }
    }
References System.Collections.Specialized.ListDictionary.Add(), System.Collections.Hashtable.Add(), System.Collections.Specialized.HybridDictionary.caseInsensitive, System.Collections.Specialized.HybridDictionary.ChangeOver(), System.Collections.Specialized.ListDictionary.Count, System.Collections.Specialized.HybridDictionary.hashtable, System.key, System.Collections.Specialized.HybridDictionary.list, System.StringComparer.OrdinalIgnoreCase, and System.value.
Referenced by System.Xml.Xsl.XsltOld.Compiler.AddDocumentURI(), System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralElement(), and System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet().