Terraria: System.Transactions.TransactionStateDelegatedAborting.EnterState
EnterState()
override void System.Transactions.TransactionStateDelegatedAborting.EnterState (InternalTransaction tx) inline package
Definition at line 7 of file TransactionStateDelegatedAborting.cs.
    {
        CommonEnterState(tx);
        Monitor.Exit(tx);
        try
        {
            TransactionsEtwProvider log = TransactionsEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.EnlistmentStatus(tx._durableEnlistment, NotificationCall.Rollback);
            }
            tx._durableEnlistment.PromotableSinglePhaseNotification.Rollback(tx._durableEnlistment.SinglePhaseEnlistment);
        }
        finally
        {
            Monitor.Enter(tx);
        }
    }
References System.Transactions.InternalTransaction._durableEnlistment, System.Transactions.TransactionState.CommonEnterState(), System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.InternalEnlistment.PromotableSinglePhaseNotification, System.Transactions.IPromotableSinglePhaseNotification.Rollback(), and System.Transactions.InternalEnlistment.SinglePhaseEnlistment.