Terraria: System.IO.Strategies.FileStreamStrategy.Unlock
Unlock()
void System.IO.Strategies.FileStreamStrategy.Unlock (long position, long length) abstract package
Referenced by System.IO.Strategies.BufferedFileStreamStrategy.Unlock(), System.IO.Strategies.DerivedFileStreamStrategy.Unlock(), and System.IO.FileStream.Unlock().