Terraria: System.Reflection.Metadata.Ecma335.NameEncoder.Name
Name()
void System.Reflection.Metadata.Ecma335.NameEncoder.Name (string name) inline
Definition at line 12 of file NameEncoder.cs.
    {
        if (name == null)
        {
            Throw.ArgumentNull("name");
        }
        if (name.Length == 0)
        {
            Throw.ArgumentEmptyString("name");
        }
        Builder.WriteSerializedString(name);
    }
References System.Reflection.Throw.ArgumentEmptyString(), System.Reflection.Throw.ArgumentNull(), System.Reflection.Metadata.Ecma335.NameEncoder.Builder, and System.Reflection.Metadata.BlobBuilder.WriteSerializedString().