Terraria: System.Reflection.Metadata.MetadataReaderProvider.MetadataReaderProvider
MetadataReaderProvider() [1/2]
System.Reflection.Metadata.MetadataReaderProvider.MetadataReaderProvider (AbstractMemoryBlock metadataBlock) inline package
Definition at line 18 of file MetadataReaderProvider.cs.
    {
        _lazyMetadataBlock = metadataBlock;
    }
References System.Reflection.Metadata.MetadataReaderProvider._lazyMetadataBlock.
Referenced by System.Reflection.Metadata.MetadataReaderProvider.FromMetadataImage(), System.Reflection.Metadata.MetadataReaderProvider.FromMetadataImage(), and System.Reflection.Metadata.MetadataReaderProvider.FromMetadataStream().