Terraria: System.Reflection.Metadata.MetadataReaderProvider.Dispose
Dispose()
void System.Reflection.Metadata.MetadataReaderProvider.Dispose () inline
Implements System.IDisposable.
Definition at line 106 of file MetadataReaderProvider.cs.
    {
        _blockProviderOpt?.Dispose();
        _blockProviderOpt = null;
        _lazyMetadataBlock?.Dispose();
        _lazyMetadataBlock = null;
        _lazyMetadataReader = null;
    }
References System.Reflection.Metadata.MetadataReaderProvider._blockProviderOpt, System.Reflection.Metadata.MetadataReaderProvider._lazyMetadataBlock, System.Reflection.Metadata.MetadataReaderProvider._lazyMetadataReader, System.Reflection.Internal.AbstractMemoryBlock.Dispose(), and System.Reflection.Internal.MemoryBlockProvider.Dispose().
Referenced by System.Reflection.PortableExecutable.PEReader.TryOpenEmbeddedPortablePdb(), and System.Reflection.PortableExecutable.PEReader.TryOpenPortablePdbFile().