Terraria: System.Reflection.Metadata.MetadataReaderProvider.GetMetadataReader
GetMetadataReader()
unsafe MetadataReader System.Reflection.Metadata.MetadataReaderProvider.GetMetadataReader (MetadataReaderOptions options = MetadataReaderOptions::Default, MetadataStringDecoder? utf8Decoder = null) inline
Definition at line 115 of file MetadataReaderProvider.cs.
    {
        MetadataReader lazyMetadataReader = _lazyMetadataReader;
        if (CanReuseReader(lazyMetadataReader, options, utf8Decoder))
        {
            return lazyMetadataReader;
        }
        lock (_metadataReaderGuard)
        {
            lazyMetadataReader = _lazyMetadataReader;
            if (CanReuseReader(lazyMetadataReader, options, utf8Decoder))
            {
                return lazyMetadataReader;
            }
            AbstractMemoryBlock metadataBlock = GetMetadataBlock();
            return _lazyMetadataReader = new MetadataReader(metadataBlock.Pointer, metadataBlock.Size, options, utf8Decoder, this);
        }
    }
References System.Reflection.Metadata.MetadataReaderProvider._lazyMetadataReader, System.Reflection.Metadata.MetadataReaderProvider._metadataReaderGuard, System.Reflection.Metadata.MetadataReaderProvider.CanReuseReader(), System.Reflection.Metadata.MetadataReaderProvider.GetMetadataBlock(), System.options, System.Reflection.Internal.AbstractMemoryBlock.Pointer, and System.Reflection.Internal.AbstractMemoryBlock.Size.
Referenced by System.Reflection.PortableExecutable.PEReader.TryOpenEmbeddedPortablePdb(), and System.Reflection.PortableExecutable.PEReader.TryOpenPortablePdbFile().