Terraria: System.Reflection.Metadata.MetadataReaderProvider.GetMetadataBlock
GetMetadataBlock()
AbstractMemoryBlock System.Reflection.Metadata.MetadataReaderProvider.GetMetadataBlock () inline package
Definition at line 143 of file MetadataReaderProvider.cs.
    {
        if (_lazyMetadataBlock == null)
        {
            if (_blockProviderOpt == null)
            {
                throw new ObjectDisposedException("MetadataReaderProvider");
            }
            AbstractMemoryBlock memoryBlock = _blockProviderOpt.GetMemoryBlock(0, _blockProviderOpt.Size);
            if (Interlocked.CompareExchange(ref _lazyMetadataBlock, memoryBlock, null) != null)
            {
                memoryBlock.Dispose();
            }
        }
        return _lazyMetadataBlock;
    }
References System.Reflection.Metadata.MetadataReaderProvider._blockProviderOpt, System.Reflection.Metadata.MetadataReaderProvider._lazyMetadataBlock, System.Threading.Interlocked.CompareExchange(), System.Reflection.Internal.AbstractMemoryBlock.Dispose(), System.Reflection.Internal.MemoryBlockProvider.GetMemoryBlock(), and System.Reflection.Internal.MemoryBlockProvider.Size.
Referenced by System.Reflection.Metadata.MetadataReaderProvider.GetMetadataReader().