Terraria: System.Reflection.DispatchProxyGenerator.CreateProxyInstance
CreateProxyInstance()
static object System.Reflection.DispatchProxyGenerator.CreateProxyInstance ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] Type baseType, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type interfaceType) inline static package
Definition at line 680 of file DispatchProxyGenerator.cs.
    {
        GeneratedTypeInfo proxyType = GetProxyType(baseType, interfaceType);
        return Activator.CreateInstance(proxyType.GeneratedType, new object[1] { proxyType.MethodInfos });
    }
References System.Activator.CreateInstance(), and System.Reflection.DispatchProxyGenerator.GetProxyType().
Referenced by System.Reflection.DispatchProxy.Create<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] T, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] TProxy >().