Terraria: System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.CreateBuffer
CreateBuffer()
virtual global.Interop.WebSocket.? Buffer System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.CreateBuffer (ArraySegment< byte >? buffer) inline protected virtual
Reimplemented in System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.
Definition at line 155 of file WebSocketBase.cs.
            {
                if (!buffer.HasValue)
                {
                    return null;
                }
                global::Interop.WebSocket.Buffer value = default(global::Interop.WebSocket.Buffer);
                _webSocket._internalBuffer.PinSendBuffer(buffer.Value, out _BufferHasBeenPinned);
                value.Data.BufferData = _webSocket._internalBuffer.ConvertPinnedSendPayloadToNative(buffer.Value);
                value.Data.BufferLength = (uint)buffer.Value.Count;
                return value;
            }
References System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation._BufferHasBeenPinned, System.Net.WebSockets.WebSocketBase._internalBuffer, System.Net.WebSockets.WebSocketBase.WebSocketOperation._webSocket, System.buffer, System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadToNative(), System.Net.WebSockets.WebSocketBuffer.PinSendBuffer(), and System.value.
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.Initialize().