Terraria: UIKeybindingToggleListItem.DrawSelf
DrawSelf()
override void UIKeybindingToggleListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         float num = 6f;
         base.DrawSelf(spriteBatch);
         CalculatedStyle dimensions = GetDimensions();
         float num2 = dimensions.Width + 1f;
         Vector2 vector = new Vector2(dimensions.X, dimensions.Y);
         Vector2 baseScale = new Vector2(0.8f);
         Color value = (false ? Color.Gold : (base.IsMouseHovering ? Color.White : Color.Silver));
         value = Color.Lerp(value, Color.White, base.IsMouseHovering ? 0.5f : 0f);
         Color color = (base.IsMouseHovering ? _color : _color.MultiplyRGBA(new Color(180, 180, 180)));
         Vector2 position = vector;
         Utils.DrawSettingsPanel(spriteBatch, position, num2, color);
         position.X += 8f;
         position.Y += 2f + num;
         ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, _TextDisplayFunction(), position, value, 0f, Vector2.Zero, baseScale, num2);
         position.X -= 17f;
         Rectangle value2 = new Rectangle(_IsOnFunction() ? ((_toggleTexture.Width() - 2) / 2 + 2) : 0, 0, (_toggleTexture.Width() - 2) / 2, _toggleTexture.Height());
         Vector2 vector2 = new Vector2(value2.Width, 0f);
         spriteBatch.Draw(position: new Vector2(dimensions.X + dimensions.Width - vector2.X - 10f, dimensions.Y + 2f + num), texture: _toggleTexture.Value, sourceRectangle: value2, color: Color.White, rotation: 0f, origin: Vector2.Zero, scale: Vector2.One, effects: SpriteEffects.None, layerDepth: 0f);
     }
References _color, _IsOnFunction, _TextDisplayFunction, _toggleTexture, Color, ChatManager.DrawColorCodedStringWithShadow(), Utils.DrawSettingsPanel(), UIElement.GetDimensions(), FontAssets.ItemStack, Asset< T >.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.