Terraria: LegacyAudioSystem.FindReplacementTrack
FindReplacementTrack()
IAudioTrack LegacyAudioSystem.FindReplacementTrack (List< IContentSource > sources, string assetPath) inline private
     {
         IAudioTrack audioTrack = null;
         for (int i = 0; i < sources.Count; i++)
         {
             IContentSource val = sources[i];
             if (!val.HasAsset(assetPath))
             {
                 continue;
             }
             string extension = val.GetExtension(assetPath);
             try
             {
                 IAudioTrack audioTrack2 = null;
                 switch (extension)
                 {
                 case ".ogg":
                     audioTrack2 = new OGGAudioTrack(val.OpenStream(assetPath));
                     break;
                 case ".wav":
                     audioTrack2 = new WAVAudioTrack(val.OpenStream(assetPath));
                     break;
                 case ".mp3":
                     audioTrack2 = new MP3AudioTrack(val.OpenStream(assetPath));
                     break;
                 }
                 if (audioTrack2 != null)
                 {
                     audioTrack?.Dispose();
                     audioTrack = audioTrack2;
                 }
             }
             catch
             {
                 string textToShow = "A resource pack failed to load " + assetPath + "!";
                 Main.IssueReporter.AddReport(textToShow);
                 Main.IssueReporterIndicator.AttemptLettingPlayerKnow();
             }
         }
         return audioTrack;
     }
References GeneralIssueReporter.AddReport(), IssueReportsIndicator.AttemptLettingPlayerKnow(), IContentSource.GetExtension(), IContentSource.HasAsset(), Main.IssueReporter, Main.IssueReporterIndicator, and IContentSource.OpenStream().
Referenced by LoadFromSources().