Terraria: LegacyAudioSystem.UpdateCommonTrack
UpdateCommonTrack()
void LegacyAudioSystem.UpdateCommonTrack (bool active, int i, float totalVolume, ref float tempFade) inline
Implements IAudioSystem.
     {
         if (!WaveBank.IsPrepared)
         {
             return;
         }
         tempFade += 0.005f;
         if (tempFade > 1f)
         {
             tempFade = 1f;
         }
         if (!AudioTracks[i].IsPlaying && active)
         {
             if (MusicReplayDelay == 0)
             {
                 if (Main.SettingMusicReplayDelayEnabled)
                 {
                     MusicReplayDelay = Main.rand.Next(14400, 21601);
                 }
                 AudioTracks[i].Reuse();
                 AudioTracks[i].SetVariable("Volume", totalVolume);
                 AudioTracks[i].Play();
             }
         }
         else
         {
             AudioTracks[i].SetVariable("Volume", totalVolume);
         }
     }
References AudioTracks, MusicReplayDelay, UnifiedRandom.Next(), IAudioTrack.Play(), Main.rand, IAudioTrack.Reuse(), Main.SettingMusicReplayDelayEnabled, IAudioTrack.SetVariable(), and WaveBank.