Terraria: CommonCode.ModifyItemDropFromNPC
ModifyItemDropFromNPC()
static void CommonCode.ModifyItemDropFromNPC (NPC npc, int itemIndex) inline static
     {
         Item item = Main.item[itemIndex];
         switch (item.type)
         {
         case 23:
             if (npc.type == 1 && npc.netID != -1 && npc.netID != -2 && npc.netID != -5 && npc.netID != -6)
             {
                 item.color = npc.color;
                 NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
             }
             if (Main.remixWorld && npc.type == 59)
             {
                 item.color = new Color(255, 127, 0);
                 NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
             }
             break;
         case 319:
             switch (npc.netID)
             {
             case 542:
                 item.color = new Color(189, 148, 96, 255);
                 NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
                 break;
             case 543:
                 item.color = new Color(112, 85, 89, 255);
                 NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
                 break;
             case 544:
                 item.color = new Color(145, 27, 40, 255);
                 NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
                 break;
             case 545:
                 item.color = new Color(158, 113, 164, 255);
                 NetMessage.SendData(88, -1, -1, null, itemIndex, 1f);
                 break;
             }
             break;
         }
     }
References Color, Item.color, NPC.color, Main.item, NPC.netID, Main.remixWorld, NetMessage.SendData(), Item.type, and NPC.type.
Referenced by DropItemForEachInteractingPlayerOnThePlayer(), and DropItemFromNPC().