Terraria: CommonCode.DropItemForEachInteractingPlayerOnThePlayer
DropItemForEachInteractingPlayerOnThePlayer()
static void CommonCode.DropItemForEachInteractingPlayerOnThePlayer (NPC npc, int itemId, UnifiedRandom rng, int chanceNumerator, int chanceDenominator, int stack = 1, bool interactionRequired = true) inline static
     {
         if (itemId <= 0 || itemId >= ItemID.Count)
         {
             return;
         }
         if (Main.netMode == 2)
         {
             for (int i = 0; i < 255; i++)
             {
                 Player player = Main.player[i];
                 if (player.active && (npc.playerInteraction[i] || !interactionRequired) && rng.Next(chanceDenominator) < chanceNumerator)
                 {
                     int itemIndex = Item.NewItem(npc.GetItemSource_Loot(), player.position, player.Size, itemId, stack, noBroadcast: false, -1);
                     ModifyItemDropFromNPC(npc, itemIndex);
                 }
             }
         }
         else if (rng.Next(chanceDenominator) < chanceNumerator)
         {
             DropItemFromNPC(npc, itemId, stack);
         }
         npc.value = 0f;
     }
References Entity.active, ItemID.Count, DropItemFromNPC(), NPC.GetItemSource_Loot(), ModifyItemDropFromNPC(), Main.netMode, Item.NewItem(), UnifiedRandom.Next(), Main.player, NPC.playerInteraction, Entity.position, Entity.Size, and NPC.value.
Referenced by DropPerPlayerOnThePlayer.TryDroppingItem().