Terraria: System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString
WriteQuotedCSharpString() [1/2]
static void System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString (IndentedWriter writer, string value) inline static package
Definition at line 560 of file ReflectionAwareCodeGen.cs.
    {
        if (value == null)
        {
            writer.Write("null");
            return;
        }
        writer.Write("@\"");
        foreach (char c in value)
        {
            if (c < ' ')
            {
                switch (c)
                {
                case '\r':
                    writer.Write("\\r");
                    continue;
                case '\n':
                    writer.Write("\\n");
                    continue;
                case '\t':
                    writer.Write("\\t");
                    continue;
                }
                byte b = (byte)c;
                writer.Write("\\x");
                writer.Write(System.HexConverter.ToCharUpper(b >> 4));
                writer.Write(System.HexConverter.ToCharUpper(b));
            }
            else if (c == '"')
            {
                writer.Write("\"\"");
            }
            else
            {
                writer.Write(c);
            }
        }
        writer.Write("\"");
    }
References System.Xml.Dictionary, System.HexConverter.ToCharUpper(), System.value, and System.writer.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.ExpectedElements(), System.Xml.Serialization.TempAssembly.GenerateSerializerToStream(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteAssemblyInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteDefaultIndexerInit(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteMemberInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteMethodInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteUnknownNode().