Terraria: System.Xml.Serialization.ReflectionAwareCodeGen.WriteMethodInfo
WriteMethodInfo()
string System.Xml.Serialization.ReflectionAwareCodeGen.WriteMethodInfo (string escapedName, string typeVariable, string memberName, bool isNonPublic, params string[] paramTypes) inline private
Definition at line 212 of file ReflectionAwareCodeGen.cs.
    {
        string text = GenerateVariableName("method", memberName);
        _writer.Write("static " + typeof(MethodInfo).FullName + " " + text + " = " + typeVariable + ".GetMethod(");
        WriteQuotedCSharpString(memberName);
        _writer.Write(", ");
        string fullName = typeof(BindingFlags).FullName;
        _writer.Write(fullName);
        _writer.Write(".Public | ");
        _writer.Write(fullName);
        _writer.Write(".Instance | ");
        _writer.Write(fullName);
        _writer.Write(".Static");
        if (isNonPublic)
        {
            _writer.Write(" | ");
            _writer.Write(fullName);
            _writer.Write(".NonPublic");
        }
        _writer.Write(", null, ");
        _writer.Write("new " + typeof(Type).FullName + "[] { ");
        for (int i = 0; i < paramTypes.Length; i++)
        {
            _writer.Write(paramTypes[i]);
            if (i < paramTypes.Length - 1)
            {
                _writer.Write(", ");
            }
        }
        _writer.WriteLine("}, null);");
        _reflectionVariables.Add(memberName + ":" + escapedName, text);
        return text;
    }
References System.Xml.Serialization.ReflectionAwareCodeGen._reflectionVariables, System.Xml.Serialization.ReflectionAwareCodeGen._writer, System.Collections.Hashtable.Add(), System.Xml.Dictionary, System.FullName, System.Xml.Serialization.ReflectionAwareCodeGen.GenerateVariableName(), System.text, System.Xml.Serialization.IndentedWriter.Write(), System.Xml.Serialization.IndentedWriter.WriteLine(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.ReflectionAwareCodeGen.WriteCollectionInfo(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteMappingInfo().