Terraria: System.Xml.Serialization.ReflectionAwareCodeGen.WriteCollectionInfo
WriteCollectionInfo()
void System.Xml.Serialization.ReflectionAwareCodeGen.WriteCollectionInfo (string typeVariable, TypeDesc typeDesc, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicNestedTypes | DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.PublicEvents)] Type type) inline private
Definition at line 145 of file ReflectionAwareCodeGen.cs.
    {
        string cSharpName = CodeIdentifier.GetCSharpName(type);
        string cSharpName2 = typeDesc.ArrayElementTypeDesc.CSharpName;
        bool useReflection = typeDesc.ArrayElementTypeDesc.UseReflection;
        if (typeDesc.IsCollection)
        {
            WriteDefaultIndexerInit(type, cSharpName, typeDesc.UseReflection, useReflection);
        }
        else if (typeDesc.IsEnumerable)
        {
            if (typeDesc.IsGenericInterface)
            {
                WriteMethodInfo(cSharpName, typeVariable, "System.Collections.Generic.IEnumerable*", true);
            }
            else if (!typeDesc.IsPrivateImplementation)
            {
                WriteMethodInfo(cSharpName, typeVariable, "GetEnumerator", true);
            }
        }
        WriteMethodInfo(cSharpName, typeVariable, "Add", false, GetStringForTypeof(cSharpName2, useReflection));
    }
References System.Xml.Dictionary, System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.ReflectionAwareCodeGen.GetStringForTypeof(), System.type, System.Xml.Serialization.ReflectionAwareCodeGen.WriteDefaultIndexerInit(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteMethodInfo().
Referenced by System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo().