Terraria: System.Xml.Serialization.ReflectionAwareCodeGen.WriteMemberInfo
WriteMemberInfo()
string System.Xml.Serialization.ReflectionAwareCodeGen.WriteMemberInfo ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicNestedTypes | DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.PublicEvents)] Type type, string escapedName, string typeVariable, string memberName) inline private
Definition at line 185 of file ReflectionAwareCodeGen.cs.
    {
        MemberInfo[] member = type.GetMember(memberName);
        for (int i = 0; i < member.Length; i++)
        {
            if (member[i] is PropertyInfo)
            {
                string text = GenerateVariableName("prop", memberName);
                _writer.Write("static XSPropInfo " + text + " = new XSPropInfo(" + typeVariable + ", ");
                WriteQuotedCSharpString(memberName);
                _writer.WriteLine(");");
                _reflectionVariables.Add(memberName + ":" + escapedName, text);
                return text;
            }
            if (member[i] is FieldInfo)
            {
                string text2 = GenerateVariableName("field", memberName);
                _writer.Write("static XSFieldInfo " + text2 + " = new XSFieldInfo(" + typeVariable + ", ");
                WriteQuotedCSharpString(memberName);
                _writer.WriteLine(");");
                _reflectionVariables.Add(memberName + ":" + escapedName, text2);
                return text2;
            }
        }
        throw new InvalidOperationException(System.SR.Format(System.SR.XmlSerializerUnsupportedType, member[0]));
    }
References System.Xml.Serialization.ReflectionAwareCodeGen._reflectionVariables, System.Xml.Serialization.ReflectionAwareCodeGen._writer, System.Collections.Hashtable.Add(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.ReflectionAwareCodeGen.GenerateVariableName(), System.text, System.type, System.Xml.Serialization.IndentedWriter.Write(), System.Xml.Serialization.IndentedWriter.WriteLine(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString(), and System.SR.XmlSerializerUnsupportedType.
Referenced by System.Xml.Serialization.ReflectionAwareCodeGen.WriteMappingInfo().