Terraria: System.Xml.Serialization.ReflectionAwareCodeGen.WriteDefaultIndexerInit
WriteDefaultIndexerInit()
string System.Xml.Serialization.ReflectionAwareCodeGen.WriteDefaultIndexerInit ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicNestedTypes | DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.PublicEvents)] Type type, string escapedName, bool collectionUseReflection, bool elementUseReflection) inline private
Definition at line 246 of file ReflectionAwareCodeGen.cs.
    {
        string text = GenerateVariableName("item", escapedName);
        PropertyInfo defaultIndexer = TypeScope.GetDefaultIndexer(type, null);
        _writer.Write("static XSArrayInfo ");
        _writer.Write(text);
        _writer.Write("= new XSArrayInfo(");
        _writer.Write(GetStringForTypeof(CodeIdentifier.GetCSharpName(type), collectionUseReflection));
        _writer.Write(".GetProperty(");
        WriteQuotedCSharpString(defaultIndexer.Name);
        _writer.Write(",");
        _writer.Write(GetStringForTypeof(CodeIdentifier.GetCSharpName(defaultIndexer.PropertyType), elementUseReflection));
        _writer.Write(",new ");
        _writer.Write(typeof(Type[]).FullName);
        _writer.WriteLine("{typeof(int)}));");
        _reflectionVariables.Add("0:" + escapedName, text);
        return text;
    }
References System.Xml.Serialization.ReflectionAwareCodeGen._reflectionVariables, System.Xml.Serialization.ReflectionAwareCodeGen._writer, System.Collections.Hashtable.Add(), System.Xml.Dictionary, System.FullName, System.Xml.Serialization.ReflectionAwareCodeGen.GenerateVariableName(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.TypeScope.GetDefaultIndexer(), System.Xml.Serialization.ReflectionAwareCodeGen.GetStringForTypeof(), System.text, System.type, System.Xml.Serialization.IndentedWriter.Write(), System.Xml.Serialization.IndentedWriter.WriteLine(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.ReflectionAwareCodeGen.InitTheFirstTime(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteCollectionInfo().