Terraria: System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo
WriteTypeInfo()
string System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo (TypeScope scope, TypeDesc typeDesc, Type type) inline private
Definition at line 36 of file ReflectionAwareCodeGen.cs.
    {
        InitTheFirstTime();
        string cSharpName = typeDesc.CSharpName;
        string text = (string)_reflectionVariables[cSharpName];
        if (text != null)
        {
            return text;
        }
        if (type.IsArray)
        {
            text = GenerateVariableName("array", typeDesc.CSharpName);
            TypeDesc arrayElementTypeDesc = typeDesc.ArrayElementTypeDesc;
            if (arrayElementTypeDesc.UseReflection)
            {
                string text2 = WriteTypeInfo(scope, arrayElementTypeDesc, scope.GetTypeFromTypeDesc(arrayElementTypeDesc));
                _writer.WriteLine("static " + typeof(Type).FullName + " " + text + " = " + text2 + ".MakeArrayType();");
            }
            else
            {
                string text3 = WriteAssemblyInfo(type);
                _writer.Write("static " + typeof(Type).FullName + " " + text + " = " + text3 + ".GetType(");
                WriteQuotedCSharpString(type.FullName);
                _writer.WriteLine(");");
            }
        }
        else
        {
            text = GenerateVariableName("type", typeDesc.CSharpName);
            Type underlyingType = Nullable.GetUnderlyingType(type);
            if (underlyingType != null)
            {
                string text4 = WriteTypeInfo(scope, scope.GetTypeDesc(underlyingType), underlyingType);
                _writer.WriteLine("static " + typeof(Type).FullName + " " + text + " = typeof(System.Nullable<>).MakeGenericType(new " + typeof(Type).FullName + "[] {" + text4 + "});");
            }
            else
            {
                string text5 = WriteAssemblyInfo(type);
                _writer.Write("static " + typeof(Type).FullName + " " + text + " = " + text5 + ".GetType(");
                WriteQuotedCSharpString(type.FullName);
                _writer.WriteLine(");");
            }
        }
        _reflectionVariables.Add(cSharpName, text);
        TypeMapping typeMappingFromTypeDesc = scope.GetTypeMappingFromTypeDesc(typeDesc);
        if (typeMappingFromTypeDesc != null)
        {
            WriteMappingInfo(typeMappingFromTypeDesc, text, type);
        }
        if (typeDesc.IsCollection || typeDesc.IsEnumerable)
        {
            TypeDesc arrayElementTypeDesc2 = typeDesc.ArrayElementTypeDesc;
            if (arrayElementTypeDesc2.UseReflection)
            {
                WriteTypeInfo(scope, arrayElementTypeDesc2, scope.GetTypeFromTypeDesc(arrayElementTypeDesc2));
            }
            WriteCollectionInfo(text, typeDesc, type);
        }
        return text;
    }
References System.Xml.Serialization.ReflectionAwareCodeGen._reflectionVariables, System.Xml.Serialization.ReflectionAwareCodeGen._writer, System.Collections.Hashtable.Add(), System.Xml.Serialization.TypeDesc.ArrayElementTypeDesc, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.ReflectionAwareCodeGen.GenerateVariableName(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.TypeScope.GetTypeFromTypeDesc(), System.Xml.Serialization.TypeScope.GetTypeMappingFromTypeDesc(), System.Nullable< T >.GetUnderlyingType(), System.Xml.Serialization.ReflectionAwareCodeGen.InitTheFirstTime(), System.text, System.type, System.Xml.Serialization.IndentedWriter.Write(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteAssemblyInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteCollectionInfo(), System.Xml.Serialization.IndentedWriter.WriteLine(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteMappingInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo().
Referenced by System.Xml.Serialization.ReflectionAwareCodeGen.WriteReflectionInit(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo().