Terraria: System.Xml.Serialization.ReflectionAwareCodeGen.WriteMappingInfo
WriteMappingInfo()
void System.Xml.Serialization.ReflectionAwareCodeGen.WriteMappingInfo (TypeMapping mapping, string typeVariable, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.PublicFields | DynamicallyAccessedMemberTypes.PublicNestedTypes | DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.PublicEvents)] Type type) inline private
Definition at line 108 of file ReflectionAwareCodeGen.cs.
    {
        string cSharpName = mapping.TypeDesc.CSharpName;
        if (mapping is StructMapping)
        {
            StructMapping structMapping = mapping as StructMapping;
            for (int i = 0; i < structMapping.Members.Length; i++)
            {
                MemberMapping memberMapping = structMapping.Members[i];
                string text = WriteMemberInfo(type, cSharpName, typeVariable, memberMapping.Name);
                if (memberMapping.CheckShouldPersist)
                {
                    string memberName = "ShouldSerialize" + memberMapping.Name;
                    text = WriteMethodInfo(cSharpName, typeVariable, memberName, false);
                }
                if (memberMapping.CheckSpecified != 0)
                {
                    string memberName2 = memberMapping.Name + "Specified";
                    text = WriteMemberInfo(type, cSharpName, typeVariable, memberName2);
                }
                if (memberMapping.ChoiceIdentifier != null)
                {
                    string memberName3 = memberMapping.ChoiceIdentifier.MemberName;
                    text = WriteMemberInfo(type, cSharpName, typeVariable, memberName3);
                }
            }
        }
        else if (mapping is EnumMapping)
        {
            FieldInfo[] fields = type.GetFields();
            for (int j = 0; j < fields.Length; j++)
            {
                WriteMemberInfo(type, cSharpName, typeVariable, fields[j].Name);
            }
        }
    }
References System.Xml.Dictionary, System.Xml.Name, System.text, System.type, System.Xml.Serialization.ReflectionAwareCodeGen.WriteMemberInfo(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteMethodInfo().
Referenced by System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo().