Terraria: System.Transactions.TransactionStatePromotedP0Aborting.EnterState
EnterState()
override void System.Transactions.TransactionStatePromotedP0Aborting.EnterState (InternalTransaction tx) inline package
Definition at line 7 of file TransactionStatePromotedP0Aborting.cs.
    {
        CommonEnterState(tx);
        ChangeStatePromotedAborted(tx);
        if (tx._phase0Volatiles.VolatileDemux._preparingEnlistment != null)
        {
            Monitor.Exit(tx);
            try
            {
                tx._phase0Volatiles.VolatileDemux._promotedEnlistment.ForceRollback();
                return;
            }
            finally
            {
                Monitor.Enter(tx);
            }
        }
        tx.PromotedTransaction.Rollback();
    }
References System.Transactions.InternalTransaction._phase0Volatiles, System.Transactions.VolatileDemultiplexer._preparingEnlistment, System.Transactions.VolatileDemultiplexer._promotedEnlistment, System.Transactions.TransactionStatePromotedAborting.ChangeStatePromotedAborted(), System.Transactions.TransactionState.CommonEnterState(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Transactions.IPromotedEnlistment.ForceRollback(), System.Transactions.InternalTransaction.PromotedTransaction, and System.Transactions.VolatileEnlistmentSet.VolatileDemux.