Terraria: UIEmotesMenu.SetupGamepadPoints
SetupGamepadPoints()
void UIEmotesMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
         int num = 3001;
         int num2 = num;
         List<SnapPoint> snapPoints = GetSnapPoints();
         UILinkPointNavigator.SetPosition(num, _backPanel.GetInnerDimensions().ToRectangle().Center.ToVector2());
         UILinkPoint uILinkPoint = UILinkPointNavigator.Points[num2];
         uILinkPoint.Unlink();
         uILinkPoint.Up = num2 + 1;
         UILinkPoint uILinkPoint2 = uILinkPoint;
         num2++;
         float num3 = 1f / Main.UIScale;
         Rectangle clippingRectangle = _container.GetClippingRectangle(spriteBatch);
         Vector2 minimum = clippingRectangle.TopLeft() * num3;
         Vector2 maximum = clippingRectangle.BottomRight() * num3;
         for (int i = 0; i < snapPoints.Count; i++)
         {
             if (!snapPoints[i].Position.Between(minimum, maximum))
             {
                 snapPoints.Remove(snapPoints[i]);
                 i--;
             }
         }
         int num4 = 0;
         int num5 = 0;
         int num6 = 7;
         List<List<SnapPoint>> list = new List<List<SnapPoint>>();
         for (int j = 0; j < num6; j++)
         {
             List<SnapPoint> emoteGroup = GetEmoteGroup(snapPoints, j);
             if (emoteGroup.Count > 0)
             {
                 list.Add(emoteGroup);
             }
         }
         List<SnapPoint>[] array = list.ToArray();
         for (int k = 0; k < array.Length; k++)
         {
             List<SnapPoint> list2 = array[k];
             int num7 = list2.Count / 14;
             if (list2.Count % 14 > 0)
             {
                 num7++;
             }
             int num8 = 14;
             if (list2.Count % 14 != 0)
             {
                 num8 = list2.Count % 14;
             }
             for (int l = 0; l < list2.Count; l++)
             {
                 uILinkPoint = UILinkPointNavigator.Points[num2];
                 uILinkPoint.Unlink();
                 UILinkPointNavigator.SetPosition(num2, list2[l].Position);
                 int num9 = 14;
                 if (l / 14 == num7 - 1 && list2.Count % 14 != 0)
                 {
                     num9 = list2.Count % 14;
                 }
                 int num10 = l % 14;
                 uILinkPoint.Left = num2 - 1;
                 uILinkPoint.Right = num2 + 1;
                 uILinkPoint.Up = num2 - 14;
                 uILinkPoint.Down = num2 + 14;
                 if (num10 == num9 - 1)
                 {
                     uILinkPoint.Right = num2 - num9 + 1;
                 }
                 if (num10 == 0)
                 {
                     uILinkPoint.Left = num2 + num9 - 1;
                 }
                 if (num10 == 0)
                 {
                     uILinkPoint2.Up = num2;
                 }
                 if (l < 14)
                 {
                     if (num4 == 0)
                     {
                         uILinkPoint.Up = -1;
                     }
                     else
                     {
                         uILinkPoint.Up = num2 - 14;
                         if (num10 >= num4)
{
                             uILinkPoint.Up -= 14;
                         }
                         int num11 = k - 1;
                         while (num11 > 0 && array[num11].Count <= num10)
{
                             uILinkPoint.Up -= 14;
                             num11--;
                         }
                     }
                 }
                 int down = num;
                 if (k == array.Length - 1)
                 {
                     if (l / 14 < num7 - 1 && num10 >= list2.Count % 14)
                     {
                         uILinkPoint.Down = down;
                     }
                     if (l / 14 == num7 - 1)
                     {
                         uILinkPoint.Down = down;
                     }
                 }
                 else if (l / 14 == num7 - 1)
                 {
                     uILinkPoint.Down = num2 + 14;
                     for (int m = k + 1; m < array.Length && array[m].Count <= num10; m++)
                     {
                         uILinkPoint.Down += 14;
                     }
                     if (k == array.Length - 1)
                     {
                         uILinkPoint.Down = down;
                     }
                 }
                 else if (num10 >= num8)
                 {
                     uILinkPoint.Down = num2 + 14 + 14;
                     for (int n = k + 1; n < array.Length && array[n].Count <= num10; n++)
                     {
                         uILinkPoint.Down += 14;
                     }
                 }
                 num2++;
             }
             num4 = num8;
             num5 = 14 - num4;
             num2 += num5;
         }
     }
References _backPanel, _container, UILinkPointNavigator.Shortcuts.BackButtonCommand, Count, UILinkPoint.Down, UIElement.GetClippingRectangle(), GetEmoteGroup(), UIElement.GetInnerDimensions(), UIElement.GetSnapPoints(), UILinkPoint.Left, UILinkPointNavigator.Points, UILinkPoint.Right, UILinkPointNavigator.SetPosition(), CalculatedStyle.ToRectangle(), Main.UIScale, UILinkPoint.Unlink(), and UILinkPoint.Up.