Terraria: System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination
CopyFromSourceToDestination()
void System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination () inline
Definition at line 87 of file DeflateStream.cs.
        {
            try
            {
                while (!_deflateStream._inflater.Finished())
                {
                    int num = _deflateStream._inflater.Inflate(_arrayPoolBuffer, 0, _arrayPoolBuffer.Length);
                    if (num > 0)
                    {
                        _destination.Write(_arrayPoolBuffer, 0, num);
                    }
                    else if (_deflateStream._inflater.NeedsInput())
                    {
                        break;
                    }
                }
                _deflateStream._stream.CopyTo(this, _arrayPoolBuffer.Length);
            }
            finally
            {
                ArrayPool<byte>.Shared.Return(_arrayPoolBuffer);
                _arrayPoolBuffer = null;
            }
        }
References System.IO.Compression.DeflateStream.CopyToStream._arrayPoolBuffer, System.IO.Compression.DeflateStream.CopyToStream._deflateStream, System.IO.Compression.DeflateStream.CopyToStream._destination, System.IO.Compression.DeflateStream._inflater, System.IO.Compression.DeflateStream._stream, System.IO.Stream.CopyTo(), System.IO.Compression.Inflater.Finished(), System.IO.Compression.Inflater.Inflate(), System.IO.Compression.Inflater.NeedsInput(), System.Buffers.ArrayPool< T >.Shared, and System.IO.Stream.Write().
Referenced by System.IO.Compression.DeflateStream.CopyTo().