Terraria: System.IO.Compression.DeflateStream.CopyToStream.Write
Write() [1/2]
override void System.IO.Compression.DeflateStream.CopyToStream.Write (byte[] buffer, int offset, int count) inline
Definition at line 149 of file DeflateStream.cs.
        {
            _deflateStream.EnsureNotDisposed();
            if (count <= 0)
            {
                return;
            }
            if (count > buffer.Length - offset)
            {
                throw new InvalidDataException(System.SR.GenericInvalidData);
            }
            _deflateStream._inflater.SetInput(buffer, offset, count);
            while (!_deflateStream._inflater.Finished())
            {
                int num = _deflateStream._inflater.Inflate(new Span<byte>(_arrayPoolBuffer));
                if (num > 0)
                {
                    _destination.Write(_arrayPoolBuffer, 0, num);
                }
                else if (_deflateStream._inflater.NeedsInput())
                {
                    break;
                }
            }
        }
References System.IO.Compression.DeflateStream.CopyToStream._arrayPoolBuffer, System.IO.Compression.DeflateStream.CopyToStream._deflateStream, System.IO.Compression.DeflateStream.CopyToStream._destination, System.IO.Compression.DeflateStream._inflater, System.buffer, System.count, System.IO.Compression.DeflateStream.EnsureNotDisposed(), System.IO.Compression.Inflater.Finished(), System.SR.GenericInvalidData, System.IO.Compression.Inflater.Inflate(), System.IO.Compression.Inflater.NeedsInput(), System.offset, System.IO.Compression.Inflater.SetInput(), and System.IO.Stream.Write().