Terraria: System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync
CopyFromSourceToDestinationAsync()
async Task System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync () inline
Definition at line 60 of file DeflateStream.cs.
        {
            _deflateStream.AsyncOperationStarting();
            try
            {
                while (!_deflateStream._inflater.Finished())
                {
                    int num = _deflateStream._inflater.Inflate(_arrayPoolBuffer, 0, _arrayPoolBuffer.Length);
                    if (num > 0)
                    {
                        await _destination.WriteAsync(new ReadOnlyMemory<byte>(_arrayPoolBuffer, 0, num), _cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    }
                    else if (_deflateStream._inflater.NeedsInput())
                    {
                        break;
                    }
                }
                await _deflateStream._stream.CopyToAsync(this, _arrayPoolBuffer.Length, _cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            finally
            {
                _deflateStream.AsyncOperationCompleting();
                ArrayPool<byte>.Shared.Return(_arrayPoolBuffer);
                _arrayPoolBuffer = null;
            }
        }
References System.IO.Compression.DeflateStream.CopyToStream._arrayPoolBuffer, System.IO.Compression.DeflateStream.CopyToStream._cancellationToken, System.IO.Compression.DeflateStream.CopyToStream._deflateStream, System.IO.Compression.DeflateStream.CopyToStream._destination, System.IO.Compression.DeflateStream._inflater, System.IO.Compression.DeflateStream._stream, System.IO.Compression.DeflateStream.AsyncOperationCompleting(), System.IO.Compression.DeflateStream.AsyncOperationStarting(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.CopyToAsync(), System.IO.Compression.Inflater.Finished(), System.IO.Compression.Inflater.Inflate(), System.IO.Compression.Inflater.NeedsInput(), System.Buffers.ArrayPool< T >.Shared, and System.IO.Stream.WriteAsync().
Referenced by System.IO.Compression.DeflateStream.CopyToAsync().