Terraria: System.IO.Compression.DeflateStream.CopyToStream.WriteAsyncCore
WriteAsyncCore()
async ValueTask System.IO.Compression.DeflateStream.CopyToStream.WriteAsyncCore (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 132 of file DeflateStream.cs.
        {
            _deflateStream._inflater.SetInput(buffer);
            while (!_deflateStream._inflater.Finished())
            {
                int num = _deflateStream._inflater.Inflate(new Span<byte>(_arrayPoolBuffer));
                if (num > 0)
                {
                    await _destination.WriteAsync(new ReadOnlyMemory<byte>(_arrayPoolBuffer, 0, num), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
                else if (_deflateStream._inflater.NeedsInput())
                {
                    break;
                }
            }
        }
References System.IO.Compression.DeflateStream.CopyToStream._arrayPoolBuffer, System.IO.Compression.DeflateStream.CopyToStream._deflateStream, System.IO.Compression.DeflateStream.CopyToStream._destination, System.IO.Compression.DeflateStream._inflater, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Compression.Inflater.Finished(), System.IO.Compression.Inflater.Inflate(), System.IO.Compression.Inflater.NeedsInput(), System.IO.Compression.Inflater.SetInput(), and System.IO.Stream.WriteAsync().
Referenced by System.IO.Compression.DeflateStream.CopyToStream.WriteAsync(), and System.IO.Compression.DeflateStream.CopyToStream.WriteAsync().