Terraria: System.Guid.GuidResult.ToGuid
ToGuid()
readonly Guid System.Guid.GuidResult.ToGuid () inline
Definition at line 80 of file Guid.cs.
        {
            return Unsafe.As<GuidResult, Guid>(ref Unsafe.AsRef(in this));
        }
References System.Guid.GuidResult.GuidResult().
Referenced by System.Guid.Guid(), System.Guid.Parse(), System.Guid.ParseExact(), System.Guid.TryParse(), and System.Guid.TryParseExact().