Terraria: System.Resources.FileBasedResourceGroveler.GrovelForResourceSet
GrovelForResourceSet()
ResourceSet System.Resources.FileBasedResourceGroveler.GrovelForResourceSet (CultureInfo culture, Dictionary< string, ResourceSet > localResourceSets, bool tryParents, bool createIfNotExists) inline
Implements System.Resources.IResourceGroveler.
Definition at line 16 of file FileBasedResourceGroveler.cs.
    {
        ResourceSet result = null;
        string resourceFileName = _mediator.GetResourceFileName(culture);
        string text = FindResourceFile(culture, resourceFileName);
        if (text == null)
        {
            if (tryParents && culture.HasInvariantCultureName)
            {
                string value = ((_mediator.LocationInfo == null) ? "<null>" : _mediator.LocationInfo.FullName);
                throw new MissingManifestResourceException($"{SR.MissingManifestResource_NoNeutralDisk}{"\r\n"}baseName: {_mediator.BaseNameField}  locationInfo: {value}  fileName: {_mediator.GetResourceFileName(culture)}");
            }
        }
        else
        {
            result = CreateResourceSet(text);
        }
        return result;
    }
References System.Resources.FileBasedResourceGroveler._mediator, System.Resources.FileBasedResourceGroveler.CreateResourceSet(), System.culture, System.Resources.FileBasedResourceGroveler.FindResourceFile(), System.Resources.ResourceManager.GetResourceFileName(), System.text, and System.value.