Terraria: System.Net.Security.NegotiateStreamPal.InitializeSecurityContext
InitializeSecurityContext() [4/4]
static System.Net.SecurityStatusPal System.Net.Security.NegotiateStreamPal.InitializeSecurityContext (ref System::Net::Security::SafeFreeCredentials credentialsHandle, ref System::Net::Security::SafeDeleteContext securityContext, string spn, System::Net::ContextFlagsPal requestedContextFlags, byte[] incomingBlob, ChannelBinding channelBinding, ref byte[] resultBlob, ref System::Net::ContextFlagsPal contextFlags) inline static package
Definition at line 42 of file NegotiateStreamPal.cs.
    {
        System.Net.Security.InputSecurityBuffers inputBuffers = default(System.Net.Security.InputSecurityBuffers);
        if (incomingBlob != null)
        {
            inputBuffers.SetNextBuffer(new System.Net.Security.InputSecurityBuffer(incomingBlob, System.Net.Security.SecurityBufferType.SECBUFFER_TOKEN));
        }
        if (channelBinding != null)
        {
            inputBuffers.SetNextBuffer(new System.Net.Security.InputSecurityBuffer(channelBinding));
        }
        System.Net.Security.SecurityBuffer outputBuffer = new System.Net.Security.SecurityBuffer(resultBlob, System.Net.Security.SecurityBufferType.SECBUFFER_TOKEN);
        global::Interop.SspiCli.ContextFlags outFlags = global::Interop.SspiCli.ContextFlags.Zero;
        System.Net.Security.SafeDeleteSslContext context = (System.Net.Security.SafeDeleteSslContext)securityContext;
        global::Interop.SECURITY_STATUS win32SecurityStatus = (global::Interop.SECURITY_STATUS)System.Net.SSPIWrapper.InitializeSecurityContext(System.Net.GlobalSSPI.SSPIAuth, ref credentialsHandle, ref context, spn, System.Net.ContextFlagsAdapterPal.GetInteropFromContextFlagsPal(requestedContextFlags), global::Interop.SspiCli.Endianness.SECURITY_NETWORK_DREP, inputBuffers, ref outputBuffer, ref outFlags);
        securityContext = context;
        resultBlob = outputBuffer.token;
        contextFlags = System.Net.ContextFlagsAdapterPal.GetContextFlagsPalFromInterop(outFlags);
        return System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(win32SecurityStatus);
    }
References System.Net.ContextFlagsAdapterPal.GetContextFlagsPalFromInterop(), System.Net.ContextFlagsAdapterPal.GetInteropFromContextFlagsPal(), System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(), System.Net.SSPIWrapper.InitializeSecurityContext(), System.Net.Security.InputSecurityBuffers.SetNextBuffer(), System.Net.GlobalSSPI.SSPIAuth, and System.Net.Security.SecurityBuffer.token.