Terraria: ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Uninitialize
Uninitialize()
override void ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Uninitialize () inline protected
Definition at line 84 of file CorsairDeviceGroup.cs.
    {
        if (_state == State.Unitialized)
        {
            return;
        }
        try
        {
            _devices.Clear();
            if (_state >= State.DeviceControlGranted)
            {
                NativeMethods.CorsairReleaseControl(CorsairAccessMode.CAM_ExclusiveLightingControl);
            }
            Console.WriteLine("Corsair RGB unitialized.");
        }
        catch (ObjectDisposedException)
        {
        }
        catch (Exception ex2)
        {
            Console.WriteLine("Corsair RGB failed to uninitialize: " + ex2);
        }
        if (_state >= State.HandshakeCompleted)
        {
            _state = State.HandshakeCompleted;
        }
    }
References ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup._devices, ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup._state, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), ReLogic.Peripherals.RGB.Corsair.NativeMethods.CorsairReleaseControl(), and System.Console.WriteLine().
Referenced by ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Initialize().