Terraria: System.Net.Security.NegotiateStreamPal.Encrypt
Encrypt()
static int System.Net.Security.NegotiateStreamPal.Encrypt (SafeDeleteContext securityContext, ReadOnlySpan< byte > buffer, bool isConfidential, bool isNtlm, [NotNull] ref byte[] output, uint sequenceNumber) inline static package
Definition at line 60 of file NegotiateStreamPal.cs.
    {
        SecPkgContext_Sizes attribute = default(SecPkgContext_Sizes);
        bool flag = SSPIWrapper.QueryBlittableContextAttributes(GlobalSSPI.SSPIAuth, securityContext, global::Interop.SspiCli.ContextAttribute.SECPKG_ATTR_SIZES, ref attribute);
        int num = checked(2147483643 - attribute.cbBlockSize - attribute.cbSecurityTrailer);
        if (buffer.Length > num)
        {
            throw new ArgumentOutOfRangeException("Length", System.SR.Format(System.SR.net_io_out_range, num));
        }
        int num2 = buffer.Length + attribute.cbSecurityTrailer + attribute.cbBlockSize;
        if (output == null || output.Length < num2 + 4)
        {
            output = new byte[num2 + 4];
        }
        buffer.CopyTo(output.AsSpan(4 + attribute.cbSecurityTrailer));
        ThreeSecurityBuffers threeSecurityBuffers = default(ThreeSecurityBuffers);
        Span<SecurityBuffer> input = MemoryMarshal.CreateSpan(ref threeSecurityBuffers._item0, 3);
        input[0] = new SecurityBuffer(output, 4, attribute.cbSecurityTrailer, SecurityBufferType.SECBUFFER_TOKEN);
        input[1] = new SecurityBuffer(output, 4 + attribute.cbSecurityTrailer, buffer.Length, SecurityBufferType.SECBUFFER_DATA);
        input[2] = new SecurityBuffer(output, 4 + attribute.cbSecurityTrailer + buffer.Length, attribute.cbBlockSize, SecurityBufferType.SECBUFFER_PADDING);
        int num3;
        if (isConfidential)
        {
            num3 = SSPIWrapper.EncryptMessage(GlobalSSPI.SSPIAuth, securityContext, input, sequenceNumber);
        }
        else
        {
            if (isNtlm)
            {
                input[1].type |= SecurityBufferType.SECBUFFER_READONLY;
            }
            num3 = SSPIWrapper.MakeSignature(GlobalSSPI.SSPIAuth, securityContext, input, 0u);
        }
        if (num3 != 0)
        {
            Exception ex = new Win32Exception(num3);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, ex, "Encrypt");
            }
            throw ex;
        }
        num2 = input[0].size;
        bool flag2 = false;
        if (num2 != attribute.cbSecurityTrailer)
        {
            flag2 = true;
            Buffer.BlockCopy(output, input[1].offset, output, 4 + num2, input[1].size);
        }
        num2 += input[1].size;
        if (input[2].size != 0 && (flag2 || num2 != buffer.Length + attribute.cbSecurityTrailer))
        {
            Buffer.BlockCopy(output, input[2].offset, output, 4 + num2, input[2].size);
        }
        num2 += input[2].size;
        output[0] = (byte)((uint)num2 & 0xFFu);
        output[1] = (byte)((uint)(num2 >> 8) & 0xFFu);
        output[2] = (byte)((uint)(num2 >> 16) & 0xFFu);
        output[3] = (byte)((uint)(num2 >> 24) & 0xFFu);
        return num2 + 4;
    }
References System.Net.Security.ThreeSecurityBuffers._item0, System.Buffer.BlockCopy(), System.buffer, System.Net.SecPkgContext_Sizes.cbBlockSize, System.Net.SecPkgContext_Sizes.cbSecurityTrailer, System.Net.SSPIWrapper.EncryptMessage(), System.Net.NetEventSource.Error(), System.SR.Format(), System.input, System.Net.NetEventSource.Log, System.Net.SSPIWrapper.MakeSignature(), System.SR.net_io_out_range, System.offset, and System.Net.GlobalSSPI.SSPIAuth.
Referenced by System.Net.NTAuthentication.Encrypt().