Terraria: System.Net.Security.NegotiateStreamPal.DecryptNtlm
DecryptNtlm()
static int System.Net.Security.NegotiateStreamPal.DecryptNtlm (SafeDeleteContext securityContext, byte[] buffer, int offset, int count, bool isConfidential, out int newOffset, uint sequenceNumber) inline static private
Definition at line 158 of file NegotiateStreamPal.cs.
    {
        if (count < 16)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        TwoSecurityBuffers twoSecurityBuffers = default(TwoSecurityBuffers);
        Span<SecurityBuffer> input = MemoryMarshal.CreateSpan(ref twoSecurityBuffers._item0, 2);
        input[0] = new SecurityBuffer(buffer, offset, 16, SecurityBufferType.SECBUFFER_TOKEN);
        input[1] = new SecurityBuffer(buffer, offset + 16, count - 16, SecurityBufferType.SECBUFFER_DATA);
        SecurityBufferType securityBufferType = SecurityBufferType.SECBUFFER_DATA;
        int num;
        if (isConfidential)
        {
            num = SSPIWrapper.DecryptMessage(GlobalSSPI.SSPIAuth, securityContext, input, sequenceNumber);
        }
        else
        {
            securityBufferType |= SecurityBufferType.SECBUFFER_READONLY;
            input[1].type = securityBufferType;
            num = SSPIWrapper.VerifySignature(GlobalSSPI.SSPIAuth, securityContext, input, sequenceNumber);
        }
        if (num != 0)
        {
            Exception message = new Win32Exception(num);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, message, "DecryptNtlm");
            }
            throw new Win32Exception(num);
        }
        if (input[1].type != securityBufferType)
        {
            throw new InternalException(input[1].type);
        }
        newOffset = input[1].offset;
        return input[1].size;
    }
References System.Net.Security.TwoSecurityBuffers._item0, System.buffer, System.count, System.Net.SSPIWrapper.DecryptMessage(), System.Net.NetEventSource.Error(), System.input, System.Net.NetEventSource.Log, System.offset, System.Net.GlobalSSPI.SSPIAuth, System.type, and System.Net.SSPIWrapper.VerifySignature().
Referenced by System.Net.Security.NegotiateStreamPal.Decrypt().