Terraria: System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle
AcquireCredentialsHandle() [3/4]
static System.Net.Security.SafeFreeCredentials System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle (string package, bool isServer, NetworkCredential credential) inline static package
Definition at line 20 of file NegotiateStreamPal.cs.
    {
        System.Net.Security.SafeSspiAuthDataHandle authData = null;
        try
        {
            global::Interop.SECURITY_STATUS sECURITY_STATUS = global::Interop.SspiCli.SspiEncodeStringsAsAuthIdentity(credential.UserName, credential.Domain, credential.Password, out authData);
            if (sECURITY_STATUS != 0)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(null, System.SR.Format(System.SR.net_log_operation_failed_with_error, "SspiEncodeStringsAsAuthIdentity", $"0x{sECURITY_STATUS:X}"), "AcquireCredentialsHandle");
                }
                throw new Win32Exception((int)sECURITY_STATUS);
            }
            return System.Net.SSPIWrapper.AcquireCredentialsHandle(System.Net.GlobalSSPI.SSPIAuth, package, isServer ? global::Interop.SspiCli.CredentialUse.SECPKG_CRED_INBOUND : global::Interop.SspiCli.CredentialUse.SECPKG_CRED_OUTBOUND, ref authData);
        }
        finally
        {
            authData?.Dispose();
        }
    }
References System.Net.SSPIWrapper.AcquireCredentialsHandle(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.NetworkCredential.Domain, System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_log_operation_failed_with_error, System.Net.NetworkCredential.Password, System.Net.GlobalSSPI.SSPIAuth, and System.Net.NetworkCredential.UserName.