Terraria: System.Net.Security.NegotiateStreamPal.Decrypt
Decrypt()
static int System.Net.Security.NegotiateStreamPal.Decrypt (SafeDeleteContext securityContext, byte[] buffer, int offset, int count, bool isConfidential, bool isNtlm, out int newOffset, uint sequenceNumber) inline static package
Definition at line 122 of file NegotiateStreamPal.cs.
    {
        if (offset < 0 || offset > ((buffer != null) ? buffer.Length : 0))
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (count < 0 || count > ((buffer != null) ? (buffer.Length - offset) : 0))
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (isNtlm)
        {
            return DecryptNtlm(securityContext, buffer, offset, count, isConfidential, out newOffset, sequenceNumber);
        }
        TwoSecurityBuffers twoSecurityBuffers = default(TwoSecurityBuffers);
        Span<SecurityBuffer> input = MemoryMarshal.CreateSpan(ref twoSecurityBuffers._item0, 2);
        input[0] = new SecurityBuffer(buffer, offset, count, SecurityBufferType.SECBUFFER_STREAM);
        input[1] = new SecurityBuffer(0, SecurityBufferType.SECBUFFER_DATA);
        int num = ((!isConfidential) ? SSPIWrapper.VerifySignature(GlobalSSPI.SSPIAuth, securityContext, input, sequenceNumber) : SSPIWrapper.DecryptMessage(GlobalSSPI.SSPIAuth, securityContext, input, sequenceNumber));
        if (num != 0)
        {
            Exception ex = new Win32Exception(num);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, ex, "Decrypt");
            }
            throw ex;
        }
        if (input[1].type != SecurityBufferType.SECBUFFER_DATA)
        {
            throw new InternalException(input[1].type);
        }
        newOffset = input[1].offset;
        return input[1].size;
    }
References System.Net.Security.TwoSecurityBuffers._item0, System.buffer, System.count, System.Net.SSPIWrapper.DecryptMessage(), System.Net.Security.NegotiateStreamPal.DecryptNtlm(), System.Net.NetEventSource.Error(), System.input, System.Net.NetEventSource.Log, System.offset, System.Net.GlobalSSPI.SSPIAuth, System.type, and System.Net.SSPIWrapper.VerifySignature().
Referenced by System.Net.NTAuthentication.Decrypt().