Terraria: System.Net.Security.NegotiateStreamPal.MakeSignature
MakeSignature()
static int System.Net.Security.NegotiateStreamPal.MakeSignature (System::Net::Security::SafeDeleteContext securityContext, byte[] buffer, int offset, int count, [AllowNull] ref byte[] output) inline static package
Definition at line 127 of file NegotiateStreamPal.cs.
    {
        System.Net.SecPkgContext_Sizes attribute = default(System.Net.SecPkgContext_Sizes);
        bool flag = System.Net.SSPIWrapper.QueryBlittableContextAttributes(System.Net.GlobalSSPI.SSPIAuth, securityContext, global::Interop.SspiCli.ContextAttribute.SECPKG_ATTR_SIZES, ref attribute);
        int num = count + attribute.cbMaxSignature;
        if (output == null || output.Length < num)
        {
            output = new byte[num];
        }
        Buffer.BlockCopy(buffer, offset, output, attribute.cbMaxSignature, count);
        System.Net.Security.TwoSecurityBuffers twoSecurityBuffers = default(System.Net.Security.TwoSecurityBuffers);
        Span<System.Net.Security.SecurityBuffer> input = MemoryMarshal.CreateSpan(ref twoSecurityBuffers._item0, 2);
        input[0] = new System.Net.Security.SecurityBuffer(output, 0, attribute.cbMaxSignature, System.Net.Security.SecurityBufferType.SECBUFFER_TOKEN);
        input[1] = new System.Net.Security.SecurityBuffer(output, attribute.cbMaxSignature, count, System.Net.Security.SecurityBufferType.SECBUFFER_DATA);
        int num2 = System.Net.SSPIWrapper.MakeSignature(System.Net.GlobalSSPI.SSPIAuth, securityContext, input, 0u);
        if (num2 != 0)
        {
            System.Net.NetEventSource.Info($"MakeSignature threw error: {num2:x}", null, "MakeSignature");
            throw new Win32Exception(num2);
        }
        return input[0].size + input[1].size;
    }
References System.Net.Security.TwoSecurityBuffers._item0, System.Buffer.BlockCopy(), System.buffer, System.Net.SecPkgContext_Sizes.cbMaxSignature, System.count, System.Net.NetEventSource.Info(), System.input, System.Net.SSPIWrapper.MakeSignature(), System.offset, and System.Net.GlobalSSPI.SSPIAuth.
Referenced by System.Net.NTAuthentication.MakeSignature().