Terraria: ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Initialize
Initialize()
override void ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Initialize () inline protected
Definition at line 31 of file CorsairDeviceGroup.cs.
    {
        if (_state == State.AnyDevicesAdded || _initializationFailed)
        {
            return;
        }
        if (!NativeLibrary.TryLoad("CUESDK.x64_2019.dll", Assembly.GetEntryAssembly(), DllImportSearchPath.SafeDirectories, out var _))
        {
            _initializationFailed = true;
            return;
        }
        try
        {
            if (_state < State.HandshakeCompleted)
            {
                NativeMethods.CorsairPerformProtocolHandshake();
                CorsairError corsairError = NativeMethods.CorsairGetLastError();
                if (corsairError != 0)
                {
                    throw new DeviceInitializationException("Corsair initialization failed with: " + corsairError);
                }
                _state = State.HandshakeCompleted;
            }
            if (_state < State.DeviceControlGranted)
            {
                NativeMethods.CorsairRequestControl(CorsairAccessMode.CAM_ExclusiveLightingControl);
                _state = State.DeviceControlGranted;
            }
            int num = NativeMethods.CorsairGetDeviceCount();
            for (int i = 0; i < num; i++)
            {
                CorsairDeviceInfo deviceInfo = (CorsairDeviceInfo)Marshal.PtrToStructure(NativeMethods.CorsairGetDeviceInfo(i), typeof(CorsairDeviceInfo));
                AddDeviceIfSupported(i, deviceInfo);
            }
            Console.WriteLine("Corsair RGB intialized.");
            if (_state != State.AnyDevicesAdded)
            {
                Console.WriteLine("No usable Corsair RGB devices found. Shutting down Corsair SDK.");
                Uninitialize();
            }
        }
        catch (DeviceInitializationException)
        {
            Console.WriteLine("Corsair RGB not supported. (Can be disabled via Config.json)");
            Uninitialize();
        }
        catch (Exception ex2)
        {
            Console.WriteLine("Corsair RGB not supported: " + ex2);
            Uninitialize();
        }
    }
References ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup._initializationFailed, ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup._state, ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.AddDeviceIfSupported(), ReLogic.Peripherals.RGB.Corsair.NativeMethods.CorsairGetDeviceCount(), ReLogic.Peripherals.RGB.Corsair.NativeMethods.CorsairGetDeviceInfo(), ReLogic.Peripherals.RGB.Corsair.NativeMethods.CorsairGetLastError(), ReLogic.Peripherals.RGB.Corsair.NativeMethods.CorsairPerformProtocolHandshake(), ReLogic.Peripherals.RGB.Corsair.NativeMethods.CorsairRequestControl(), System.Reflection.Assembly.GetEntryAssembly(), System.Runtime.InteropServices.Marshal.PtrToStructure(), System.Runtime.InteropServices.NativeLibrary.TryLoad(), ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Uninitialize(), and System.Console.WriteLine().