Terraria: System.Net.Security.NegotiateStreamPal.GetIdentity
GetIdentity()
static IIdentity System.Net.Security.NegotiateStreamPal.GetIdentity (NTAuthentication context) inline static package
Definition at line 12 of file NegotiateStreamPal.cs.
    {
        IIdentity identity = null;
        string name = (context.IsServer ? context.AssociatedName : context.Spn);
        string protocolName = context.ProtocolName;
        if (context.IsServer)
        {
            SecurityContextTokenHandle token = null;
            try
            {
                SecurityStatusPal status;
                SafeDeleteContext context2 = context.GetContext(out status);
                if (status.ErrorCode != SecurityStatusPalErrorCode.OK)
                {
                    throw new Win32Exception((int)SecurityStatusAdapterPal.GetInteropFromSecurityStatusPal(status));
                }
                global::Interop.SECURITY_STATUS sECURITY_STATUS = (global::Interop.SECURITY_STATUS)SSPIWrapper.QuerySecurityContextToken(GlobalSSPI.SSPIAuth, context2, out token);
                if (sECURITY_STATUS != 0)
                {
                    throw new Win32Exception((int)sECURITY_STATUS);
                }
                string protocolName2 = context.ProtocolName;
                return new WindowsIdentity(token.DangerousGetHandle(), protocolName2);
            }
            catch (SecurityException)
            {
            }
            finally
            {
                token?.Dispose();
            }
        }
        return new GenericIdentity(name, protocolName);
    }
References System.Runtime.InteropServices.CriticalHandle.Dispose(), System.Net.SecurityStatusPal.ErrorCode, System.Net.NTAuthentication.GetContext(), System.Net.SecurityStatusAdapterPal.GetInteropFromSecurityStatusPal(), System.Net.NTAuthentication.IsServer, System.Net.NTAuthentication.ProtocolName, System.Net.SSPIWrapper.QuerySecurityContextToken(), System.Net.NTAuthentication.Spn, and System.Net.GlobalSSPI.SSPIAuth.