Terraria: System.Xml.XmlBinaryNodeWriter.WriteText
WriteText() [4/4]
override void System.Xml.XmlBinaryNodeWriter.WriteText (XmlDictionaryString value) inline
Definition at line 640 of file XmlBinaryNodeWriter.cs.
    {
        if (_inAttribute)
        {
            _attributeValue.WriteText(value);
            return;
        }
        if (!TryGetKey(value, out var key))
        {
            WriteText(value.Value);
            return;
        }
        WriteTextNode(XmlBinaryNodeType.DictionaryText);
        WriteDictionaryString(value, key);
    }
References System.Xml.XmlBinaryNodeWriter._attributeValue, System.Xml.XmlBinaryNodeWriter._inAttribute, System.Xml.Dictionary, System.key, System.Xml.XmlBinaryNodeWriter.TryGetKey(), System.value, System.Xml.XmlBinaryNodeWriter.WriteDictionaryString(), System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteText(), System.Xml.XmlBinaryNodeWriter.WriteText(), and System.Xml.XmlBinaryNodeWriter.WriteTextNode().
Referenced by System.Xml.XmlBinaryNodeWriter.WriteCData(), System.Xml.XmlBinaryNodeWriter.WriteCharEntity(), System.Xml.XmlBinaryNodeWriter.WriteEscapedText(), System.Xml.XmlBinaryNodeWriter.WriteEscapedText(), System.Xml.XmlBinaryNodeWriter.WriteEscapedText(), System.Xml.XmlBinaryNodeWriter.WriteEscapedText(), System.Xml.XmlBinaryNodeWriter.WriteQualifiedName(), System.Xml.XmlBinaryNodeWriter.WriteText(), and System.Xml.XmlBinaryNodeWriter.WriteUniqueIdText().