Terraria: System.Xml.XmlBinaryNodeWriter.WriteBase64Text
WriteBase64Text()
override void System.Xml.XmlBinaryNodeWriter.WriteBase64Text (byte[] trailBytes, int trailByteCount, byte[] base64Buffer, int base64Offset, int base64Count) inline
Definition at line 608 of file XmlBinaryNodeWriter.cs.
    {
        if (_inAttribute)
        {
            _attributeValue.WriteBase64Text(trailBytes, trailByteCount, base64Buffer, base64Offset, base64Count);
            return;
        }
        int num = trailByteCount + base64Count;
        if (num > 0)
        {
            WriteTextNodeWithLength(XmlBinaryNodeType.Bytes8Text, num);
            if (trailByteCount > 0)
            {
                int offset;
                byte[] buffer = GetBuffer(trailByteCount, out offset);
                for (int i = 0; i < trailByteCount; i++)
                {
                    buffer[offset + i] = trailBytes[i];
                }
                Advance(trailByteCount);
            }
            if (base64Count > 0)
            {
                WriteBytes(base64Buffer, base64Offset, base64Count);
            }
        }
        else
        {
            WriteEmptyText();
        }
    }
References System.Xml.XmlBinaryNodeWriter._attributeValue, System.Xml.XmlBinaryNodeWriter._inAttribute, System.Xml.XmlStreamNodeWriter.Advance(), System.buffer, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteBase64Text(), System.Xml.XmlStreamNodeWriter.WriteBytes(), System.Xml.XmlBinaryNodeWriter.WriteEmptyText(), and System.Xml.XmlBinaryNodeWriter.WriteTextNodeWithLength().