Terraria: System.Xml.XmlBinaryNodeWriter.WriteTextNode
WriteTextNode()
void System.Xml.XmlBinaryNodeWriter.WriteTextNode (XmlBinaryNodeType nodeType) inline private
Definition at line 150 of file XmlBinaryNodeWriter.cs.
    {
        if (_inAttribute)
        {
            WroteAttributeValue();
        }
        WriteByte((byte)nodeType);
        _textNodeOffset = base.BufferOffset - 1;
    }
References System.Xml.XmlBinaryNodeWriter._inAttribute, System.Xml.XmlBinaryNodeWriter._textNodeOffset, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.WriteByte(), and System.Xml.XmlBinaryNodeWriter.WroteAttributeValue().
Referenced by System.Xml.XmlBinaryNodeWriter.UnsafeWriteText(), System.Xml.XmlBinaryNodeWriter.WriteBoolText(), System.Xml.XmlBinaryNodeWriter.WriteEmptyText(), System.Xml.XmlBinaryNodeWriter.WriteInt32Text(), System.Xml.XmlBinaryNodeWriter.WriteQualifiedName(), and System.Xml.XmlBinaryNodeWriter.WriteText().