Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberAssignment
CompileMemberAssignment() [2/2]
void System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberAssignment (bool asVoid, MemberInfo refMember, Expression value, bool forBinding) inline private
Definition at line 440 of file LightCompiler.cs.
    {
        if (refMember is PropertyInfo propertyInfo)
        {
            MethodInfo setMethod = propertyInfo.GetSetMethod(nonPublic: true);
            if (forBinding && setMethod.IsStatic)
            {
                throw Error.InvalidProgram();
            }
            EmitThisForMethodCall(value);
            int count = _instructions.Count;
            if (!asVoid)
            {
                LocalDefinition definition = _locals.DefineLocal(Expression.Parameter(value.Type), count);
                _instructions.EmitAssignLocal(definition.Index);
                _instructions.EmitCall(setMethod);
                _instructions.EmitLoadLocal(definition.Index);
                _locals.UndefineLocal(definition, _instructions.Count);
            }
            else
            {
                _instructions.EmitCall(setMethod);
            }
            return;
        }
        FieldInfo fieldInfo = (FieldInfo)refMember;
        if (fieldInfo.IsLiteral)
        {
            throw Error.NotSupported();
        }
        if (forBinding && fieldInfo.IsStatic)
        {
            _instructions.UnEmit();
        }
        EmitThisForMethodCall(value);
        int count2 = _instructions.Count;
        if (!asVoid)
        {
            LocalDefinition definition2 = _locals.DefineLocal(Expression.Parameter(value.Type), count2);
            _instructions.EmitAssignLocal(definition2.Index);
            _instructions.EmitStoreField(fieldInfo);
            _instructions.EmitLoadLocal(definition2.Index);
            _locals.UndefineLocal(definition2, _instructions.Count);
        }
        else
        {
            _instructions.EmitStoreField(fieldInfo);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Linq.Expressions.Interpreter.InstructionList.Count, System.Linq.count, System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitAssignLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoadLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitStoreField(), System.Linq.Expressions.Interpreter.LightCompiler.EmitThisForMethodCall(), System.Linq.Expressions.Error.InvalidProgram(), System.Linq.Expressions.Error.NotSupported(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.UnEmit(), and System.value.