Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression
CompileSwitchExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression (Expression expr) inline private
Definition at line 1138 of file LightCompiler.cs.
    {
        SwitchExpression switchExpression = (SwitchExpression)expr;
        if (switchExpression.Cases.All((SwitchCase c) => c.TestValues.All((Expression t) => t is ConstantExpression)))
        {
            if (switchExpression.Cases.Count == 0)
            {
                CompileAsVoid(switchExpression.SwitchValue);
                if (switchExpression.DefaultBody != null)
                {
                    Compile(switchExpression.DefaultBody);
                }
                return;
            }
            TypeCode typeCode = switchExpression.SwitchValue.Type.GetTypeCode();
            if (switchExpression.Comparison == null)
            {
                switch (typeCode)
                {
                case TypeCode.Int32:
                    CompileIntSwitchExpression<int>(switchExpression);
                    return;
                case TypeCode.SByte:
                case TypeCode.Byte:
                case TypeCode.Int16:
                case TypeCode.UInt16:
                case TypeCode.UInt32:
                case TypeCode.Int64:
                case TypeCode.UInt64:
                    CompileIntSwitchExpression<object>(switchExpression);
                    return;
                }
            }
            if (typeCode == TypeCode.String)
            {
                MethodInfo methodInfo = CachedReflectionInfo.String_op_Equality_String_String;
                if (methodInfo != null && !methodInfo.IsStatic)
                {
                    methodInfo = null;
                }
                if (object.Equals(switchExpression.Comparison, methodInfo))
                {
                    CompileStringSwitchExpression(switchExpression);
                    return;
                }
            }
        }
        LocalDefinition definition = _locals.DefineLocal(Expression.Parameter(switchExpression.SwitchValue.Type), _instructions.Count);
        Compile(switchExpression.SwitchValue);
        _instructions.EmitStoreLocal(definition.Index);
        LabelTarget target = Expression.Label(switchExpression.Type, "done");
        foreach (SwitchCase @case in switchExpression.Cases)
        {
            foreach (Expression testValue in @case.TestValues)
            {
                CompileConditionalExpression(Expression.Condition(Expression.Equal(definition.Parameter, testValue, liftToNull: false, switchExpression.Comparison), Expression.Goto(target, @case.Body), Utils.Empty), asVoid: true);
            }
        }
        CompileLabelExpression(Expression.Label(target, switchExpression.DefaultBody));
        _locals.UndefineLocal(definition, _instructions.Count);
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConditionalExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLabelExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileStringSwitchExpression(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Interpreter.InstructionList.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitStoreLocal(), System.Linq.Expressions.Utils.Empty, System.Linq.Expressions.Expression< TDelegate >.Equal(), System.Linq.Expressions.Expression< TDelegate >.Goto(), System.Linq.Expressions.Expression< TDelegate >.Label(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.CachedReflectionInfo.String_op_Equality_String_String, System.Linq.Expressions.SwitchCase.TestValues, and System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().