Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodCallExpression
CompileMethodCallExpression() [1/2]
void System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodCallExpression (Expression @ object, MethodInfo method, IArgumentProvider arguments) inline private
Definition at line 1590 of file LightCompiler.cs.
    {
        ParameterInfo[] parametersCached = method.GetParametersCached();
        List<ByRefUpdater> list = null;
        if (!method.IsStatic)
        {
            ByRefUpdater byRefUpdater = CompileAddress(@object, -1);
            if (byRefUpdater != null)
            {
                list = new List<ByRefUpdater> { byRefUpdater };
            }
        }
        int i = 0;
        for (int argumentCount = arguments.ArgumentCount; i < argumentCount; i++)
        {
            Expression argument = arguments.GetArgument(i);
            if (parametersCached[i].ParameterType.IsByRef)
            {
                ByRefUpdater byRefUpdater2 = CompileAddress(argument, i);
                if (byRefUpdater2 != null)
                {
                    if (list == null)
                    {
                        list = new List<ByRefUpdater>();
                    }
                    list.Add(byRefUpdater2);
                }
            }
            else
            {
                Compile(argument);
            }
        }
        if (!method.IsStatic && @object.Type.IsNullableType())
        {
            _instructions.EmitNullableCall(method, parametersCached);
            return;
        }
        if (list == null)
        {
            _instructions.EmitCall(method, parametersCached);
            return;
        }
        _instructions.EmitByRefCall(method, parametersCached, list.ToArray());
        foreach (ByRefUpdater item in list)
        {
            item.UndefineTemps(_instructions, _locals);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAddress(), System.Linq.Expressions.Interpreter.InstructionList.EmitByRefCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitNullableCall(), System.item, and System.list.