Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid
CompileAsVoid()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid (Expression expr) inline private
Definition at line 2215 of file LightCompiler.cs.
    {
        bool flag = TryPushLabelBlock(expr);
        int currentStackDepth = _instructions.CurrentStackDepth;
        switch (expr.NodeType)
        {
        case ExpressionType.Assign:
            CompileAssignBinaryExpression(expr, asVoid: true);
            break;
        case ExpressionType.Block:
            CompileBlockExpression(expr, asVoid: true);
            break;
        case ExpressionType.Throw:
            CompileThrowUnaryExpression(expr, asVoid: true);
            break;
        default:
            CompileNoLabelPush(expr);
            if (expr.Type != typeof(void))
            {
                _instructions.EmitPop();
            }
            break;
        case ExpressionType.Constant:
        case ExpressionType.Parameter:
        case ExpressionType.Default:
            break;
        }
        if (flag)
        {
            PopLabelBlock(_labelBlock.Kind);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._labelBlock, System.Linq.Expressions.Interpreter.LightCompiler.CompileAssignBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(), System.Linq.Expressions.Interpreter.LightCompiler.CompileThrowUnaryExpression(), System.Linq.Expressions.Interpreter.InstructionList.CurrentStackDepth, System.Linq.Expressions.Interpreter.InstructionList.EmitPop(), System.Linq.Expressions.Interpreter.LabelScopeInfo.Kind, System.Linq.Expressions.Expression< TDelegate >.NodeType, System.Linq.Expressions.Interpreter.LightCompiler.PopLabelBlock(), System.Linq.Expressions.Interpreter.LightCompiler.TryPushLabelBlock(), and System.Linq.Expressions.Expression< TDelegate >.Type.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockStart(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLabelExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLoopExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileTryFaultExpression().