Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileVariableAssignment
CompileVariableAssignment()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileVariableAssignment (BinaryExpression node, bool asVoid) inline private
Definition at line 490 of file LightCompiler.cs.
    {
        Compile(node.Right);
        ParameterExpression variable = (ParameterExpression)node.Left;
        CompileSetVariable(variable, asVoid);
    }
References System.Linq.Expressions.Interpreter.LightCompiler.Compile(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileSetVariable().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileAssignBinaryExpression().