Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression
CompileTryExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression (Expression expr) inline private
Definition at line 1473 of file LightCompiler.cs.
    {
        TryExpression tryExpression = (TryExpression)expr;
        if (tryExpression.Fault != null)
        {
            CompileTryFaultExpression(tryExpression);
            return;
        }
        BranchLabel label = _instructions.MakeLabel();
        BranchLabel branchLabel = _instructions.MakeLabel();
        int count = _instructions.Count;
        BranchLabel branchLabel2 = null;
        if (tryExpression.Finally != null)
        {
            branchLabel2 = _instructions.MakeLabel();
            _instructions.EmitEnterTryFinally(branchLabel2);
        }
        else
        {
            _instructions.EmitEnterTryCatch();
        }
        List<ExceptionHandler> list = null;
        EnterTryCatchFinallyInstruction enterTryCatchFinallyInstruction = _instructions.GetInstruction(count) as EnterTryCatchFinallyInstruction;
        PushLabelBlock(LabelScopeKind.Try);
        bool flag = tryExpression.Type != typeof(void);
        Compile(tryExpression.Body, !flag);
        int count2 = _instructions.Count;
        _instructions.MarkLabel(branchLabel);
        _instructions.EmitGoto(label, flag, flag, flag);
        if (tryExpression.Handlers.Count > 0)
        {
            list = new List<ExceptionHandler>();
            foreach (CatchBlock handler in tryExpression.Handlers)
            {
                ParameterExpression parameterExpression = handler.Variable ?? Expression.Parameter(handler.Test);
                LocalDefinition definition = _locals.DefineLocal(parameterExpression, _instructions.Count);
                _exceptionForRethrowStack.Push(parameterExpression);
                ExceptionFilter filter = null;
                if (handler.Filter != null)
                {
                    PushLabelBlock(LabelScopeKind.Filter);
                    _instructions.EmitEnterExceptionFilter();
                    int labelIndex = _instructions.MarkRuntimeLabel();
                    int count3 = _instructions.Count;
                    CompileSetVariable(parameterExpression, isVoid: true);
                    Compile(handler.Filter);
                    CompileGetVariable(parameterExpression);
                    filter = new ExceptionFilter(labelIndex, count3, _instructions.Count);
                    _instructions.EmitLeaveExceptionFilter();
                    PopLabelBlock(LabelScopeKind.Filter);
                }
                PushLabelBlock(LabelScopeKind.Catch);
                if (flag)
                {
                    _instructions.EmitEnterExceptionHandlerNonVoid();
                }
                else
                {
                    _instructions.EmitEnterExceptionHandlerVoid();
                }
                int labelIndex2 = _instructions.MarkRuntimeLabel();
                int count4 = _instructions.Count;
                CompileSetVariable(parameterExpression, isVoid: true);
                Compile(handler.Body, !flag);
                _exceptionForRethrowStack.Pop();
                _instructions.EmitLeaveExceptionHandler(flag, branchLabel);
                list.Add(new ExceptionHandler(labelIndex2, count4, _instructions.Count, handler.Test, filter));
                PopLabelBlock(LabelScopeKind.Catch);
                _locals.UndefineLocal(definition, _instructions.Count);
            }
        }
        if (tryExpression.Finally != null)
        {
            PushLabelBlock(LabelScopeKind.Finally);
            _instructions.MarkLabel(branchLabel2);
            _instructions.EmitEnterFinally(branchLabel2);
            CompileAsVoid(tryExpression.Finally);
            _instructions.EmitLeaveFinally();
            enterTryCatchFinallyInstruction.SetTryHandler(new TryCatchFinallyHandler(count, count2, branchLabel.TargetIndex, branchLabel2.TargetIndex, _instructions.Count, list?.ToArray()));
            PopLabelBlock(LabelScopeKind.Finally);
        }
        else
        {
            enterTryCatchFinallyInstruction.SetTryHandler(new TryCatchFinallyHandler(count, count2, branchLabel.TargetIndex, list.ToArray()));
        }
        _instructions.MarkLabel(label);
        PopLabelBlock(LabelScopeKind.Try);
    }
References System.Linq.Expressions.Interpreter.LightCompiler._exceptionForRethrowStack, System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Expressions.CatchBlock.Body, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(), System.Linq.Expressions.Interpreter.LightCompiler.CompileGetVariable(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSetVariable(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryFaultExpression(), System.Linq.Expressions.Interpreter.InstructionList.Count, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitEnterExceptionFilter(), System.Linq.Expressions.Interpreter.InstructionList.EmitEnterExceptionHandlerNonVoid(), System.Linq.Expressions.Interpreter.InstructionList.EmitEnterExceptionHandlerVoid(), System.Linq.Expressions.Interpreter.InstructionList.EmitEnterFinally(), System.Linq.Expressions.Interpreter.InstructionList.EmitEnterTryCatch(), System.Linq.Expressions.Interpreter.InstructionList.EmitEnterTryFinally(), System.Linq.Expressions.Interpreter.InstructionList.EmitGoto(), System.Linq.Expressions.Interpreter.InstructionList.EmitLeaveExceptionFilter(), System.Linq.Expressions.Interpreter.InstructionList.EmitLeaveExceptionHandler(), System.Linq.Expressions.Interpreter.InstructionList.EmitLeaveFinally(), System.Linq.Expressions.CatchBlock.Filter, System.Linq.Expressions.Interpreter.InstructionList.GetInstruction(), System.list, System.Linq.Expressions.Interpreter.InstructionList.MakeLabel(), System.Linq.Expressions.Interpreter.InstructionList.MarkLabel(), System.Linq.Expressions.Interpreter.InstructionList.MarkRuntimeLabel(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.Linq.Expressions.Interpreter.LightCompiler.PopLabelBlock(), System.Linq.Expressions.Interpreter.LightCompiler.PushLabelBlock(), System.Linq.Expressions.CatchBlock.Test, and System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().