Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileThrowUnaryExpression
CompileThrowUnaryExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileThrowUnaryExpression (Expression expr, bool asVoid) inline private
Definition at line 1443 of file LightCompiler.cs.
    {
        UnaryExpression unaryExpression = (UnaryExpression)expr;
        if (unaryExpression.Operand == null)
        {
            CheckRethrow();
            CompileParameterExpression(_exceptionForRethrowStack.Peek());
            if (asVoid)
            {
                _instructions.EmitRethrowVoid();
            }
            else
            {
                _instructions.EmitRethrow();
            }
        }
        else
        {
            Compile(unaryExpression.Operand);
            if (asVoid)
            {
                _instructions.EmitThrowVoid();
            }
            else
            {
                _instructions.EmitThrow();
            }
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._exceptionForRethrowStack, System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.CheckRethrow(), System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileParameterExpression(), System.Linq.Expressions.Interpreter.InstructionList.EmitRethrow(), System.Linq.Expressions.Interpreter.InstructionList.EmitRethrowVoid(), System.Linq.Expressions.Interpreter.InstructionList.EmitThrow(), and System.Linq.Expressions.Interpreter.InstructionList.EmitThrowVoid().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().