Terraria: System.Xml.XmlBinaryNodeWriter.UnsafeWriteText
UnsafeWriteText()
unsafe void System.Xml.XmlBinaryNodeWriter.UnsafeWriteText (char * chars, int charCount) inline private
Definition at line 700 of file XmlBinaryNodeWriter.cs.
    {
        if (charCount == 1)
        {
            switch (*chars)
            {
            case '0':
                WriteTextNode(XmlBinaryNodeType.MinText);
                return;
            case '1':
                WriteTextNode(XmlBinaryNodeType.OneText);
                return;
            }
        }
        if (charCount <= 85)
        {
            int offset;
            byte[] buffer = GetBuffer(2 + charCount * 3, out offset);
            int num = UnsafeGetUTF8Chars(chars, charCount, buffer, offset + 2);
            if (num / 2 <= charCount)
            {
                buffer[offset] = 152;
            }
            else
            {
                buffer[offset] = 182;
                num = UnsafeGetUnicodeChars(chars, charCount, buffer, offset + 2);
            }
            _textNodeOffset = offset;
            buffer[offset + 1] = (byte)num;
            Advance(2 + num);
        }
        else
        {
            int num2 = UnsafeGetUTF8Length(chars, charCount);
            if (num2 / 2 > charCount)
            {
                WriteTextNodeWithLength(XmlBinaryNodeType.UnicodeChars8Text, charCount * 2);
                UnsafeWriteUnicodeChars(chars, charCount);
            }
            else
            {
                WriteTextNodeWithLength(XmlBinaryNodeType.Chars8Text, num2);
                UnsafeWriteUTF8Chars(chars, charCount);
            }
        }
    }
References System.Xml.XmlBinaryNodeWriter._textNodeOffset, System.Xml.XmlStreamNodeWriter.Advance(), System.buffer, System.charCount, System.chars, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, System.Xml.XmlStreamNodeWriter.UnsafeGetUnicodeChars(), System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Chars(), System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Length(), System.Xml.XmlStreamNodeWriter.UnsafeWriteUnicodeChars(), System.Xml.XmlStreamNodeWriter.UnsafeWriteUTF8Chars(), System.Xml.XmlBinaryNodeWriter.WriteTextNode(), and System.Xml.XmlBinaryNodeWriter.WriteTextNodeWithLength().
Referenced by System.Xml.XmlBinaryNodeWriter.WriteText(), and System.Xml.XmlBinaryNodeWriter.WriteText().