Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileComparison
CompileComparison()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileComparison (BinaryExpression node) inline private
Definition at line 682 of file LightCompiler.cs.
    {
        Expression left = node.Left;
        Expression right = node.Right;
        Compile(left);
        Compile(right);
        switch (node.NodeType)
        {
        case ExpressionType.LessThan:
            _instructions.EmitLessThan(left.Type, node.IsLiftedToNull);
            break;
        case ExpressionType.LessThanOrEqual:
            _instructions.EmitLessThanOrEqual(left.Type, node.IsLiftedToNull);
            break;
        case ExpressionType.GreaterThan:
            _instructions.EmitGreaterThan(left.Type, node.IsLiftedToNull);
            break;
        case ExpressionType.GreaterThanOrEqual:
            _instructions.EmitGreaterThanOrEqual(left.Type, node.IsLiftedToNull);
            break;
        default:
            throw ContractUtils.Unreachable;
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.InstructionList.EmitGreaterThan(), System.Linq.Expressions.Interpreter.InstructionList.EmitGreaterThanOrEqual(), System.Linq.Expressions.Interpreter.InstructionList.EmitLessThan(), System.Linq.Expressions.Interpreter.InstructionList.EmitLessThanOrEqual(), System.Linq.Expressions.Expression< TDelegate >.Type, and System.Dynamic.Utils.ContractUtils.Unreachable.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression().