Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileUnaryExpression
CompileUnaryExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileUnaryExpression (Expression expr) inline private
Definition at line 883 of file LightCompiler.cs.
    {
        UnaryExpression unaryExpression = (UnaryExpression)expr;
        if (unaryExpression.Method != null)
        {
            EmitUnaryMethodCall(unaryExpression);
            return;
        }
        switch (unaryExpression.NodeType)
        {
        case ExpressionType.Not:
        case ExpressionType.OnesComplement:
            CompileNotExpression(unaryExpression);
            break;
        case ExpressionType.TypeAs:
            CompileTypeAsExpression(unaryExpression);
            break;
        case ExpressionType.ArrayLength:
            Compile(unaryExpression.Operand);
            _instructions.EmitArrayLength();
            break;
        case ExpressionType.NegateChecked:
            Compile(unaryExpression.Operand);
            _instructions.EmitNegateChecked(unaryExpression.Type);
            break;
        case ExpressionType.Negate:
            Compile(unaryExpression.Operand);
            _instructions.EmitNegate(unaryExpression.Type);
            break;
        case ExpressionType.Increment:
            Compile(unaryExpression.Operand);
            _instructions.EmitIncrement(unaryExpression.Type);
            break;
        case ExpressionType.Decrement:
            Compile(unaryExpression.Operand);
            _instructions.EmitDecrement(unaryExpression.Type);
            break;
        case ExpressionType.UnaryPlus:
            Compile(unaryExpression.Operand);
            break;
        case ExpressionType.IsTrue:
        case ExpressionType.IsFalse:
            EmitUnaryBoolCheck(unaryExpression);
            break;
        default:
            throw new PlatformNotSupportedException(System.SR.Format(System.SR.UnsupportedExpressionType, unaryExpression.NodeType));
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNotExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeAsExpression(), System.Linq.Expressions.Interpreter.InstructionList.EmitArrayLength(), System.Linq.Expressions.Interpreter.InstructionList.EmitDecrement(), System.Linq.Expressions.Interpreter.InstructionList.EmitIncrement(), System.Linq.Expressions.Interpreter.InstructionList.EmitNegate(), System.Linq.Expressions.Interpreter.InstructionList.EmitNegateChecked(), System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryBoolCheck(), System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryMethodCall(), System.SR.Format(), and System.SR.UnsupportedExpressionType.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().