Terraria: System.Linq.Expressions.Interpreter.LightCompiler.Compile
Compile() [1/2]
void System.Linq.Expressions.Interpreter.LightCompiler.Compile (Expression expr) inline private
Definition at line 2398 of file LightCompiler.cs.
    {
        bool flag = TryPushLabelBlock(expr);
        CompileNoLabelPush(expr);
        if (flag)
        {
            PopLabelBlock(_labelBlock.Kind);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._labelBlock, System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(), System.Linq.Expressions.Interpreter.LabelScopeInfo.Kind, System.Linq.Expressions.Interpreter.LightCompiler.PopLabelBlock(), and System.Linq.Expressions.Interpreter.LightCompiler.TryPushLabelBlock().