Terraria: System.Xml.XmlBinaryNodeWriter.WriteGuidText
WriteGuidText()
override void System.Xml.XmlBinaryNodeWriter.WriteGuidText (Guid guid) inline
Definition at line 879 of file XmlBinaryNodeWriter.cs.
    {
        int offset;
        byte[] textNodeBuffer = GetTextNodeBuffer(17, out offset);
        textNodeBuffer[offset] = 176;
        Buffer.BlockCopy(guid.ToByteArray(), 0, textNodeBuffer, offset + 1, 16);
        Advance(17);
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.Buffer.BlockCopy(), System.Xml.Dictionary, System.Xml.XmlBinaryNodeWriter.GetTextNodeBuffer(), System.offset, and System.Guid.ToByteArray().