Terraria: System.Xml.XmlBinaryNodeWriter.WriteText
WriteText() [2/4]
unsafe override void System.Xml.XmlBinaryNodeWriter.WriteText (char[] chars, int offset, int count) inline
Definition at line 675 of file XmlBinaryNodeWriter.cs.
    {
        if (_inAttribute)
        {
            _attributeValue.WriteText(new string(chars, offset, count));
        }
        else if (count > 0)
        {
            fixed (char* chars2 = &chars[offset])
            {
                UnsafeWriteText(chars2, count);
            }
        }
        else
        {
            WriteEmptyText();
        }
    }
References System.Xml.XmlBinaryNodeWriter._attributeValue, System.Xml.XmlBinaryNodeWriter._inAttribute, System.chars, System.count, System.Xml.Dictionary, System.offset, System.Xml.XmlBinaryNodeWriter.UnsafeWriteText(), System.Xml.XmlBinaryNodeWriter.WriteEmptyText(), and System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteText().