Terraria: System.Xml.XmlBinaryNodeWriter.WroteAttributeValue
WroteAttributeValue()
void System.Xml.XmlBinaryNodeWriter.WroteAttributeValue () inline private
Definition at line 141 of file XmlBinaryNodeWriter.cs.
    {
        if (_wroteAttributeValue && !_inList)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlOnlySingleValue));
        }
        _wroteAttributeValue = true;
    }
References System.Xml.XmlBinaryNodeWriter._inList, System.Xml.XmlBinaryNodeWriter._wroteAttributeValue, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.XmlOnlySingleValue.
Referenced by System.Xml.XmlBinaryNodeWriter.GetTextNodeBuffer(), and System.Xml.XmlBinaryNodeWriter.WriteTextNode().