Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeIsExpression
CompileTypeIsExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeIsExpression (Expression expr) inline private
Definition at line 2170 of file LightCompiler.cs.
    {
        TypeBinaryExpression typeBinaryExpression = (TypeBinaryExpression)expr;
        AnalyzeTypeIsResult analyzeTypeIsResult = ConstantCheck.AnalyzeTypeIs(typeBinaryExpression);
        Compile(typeBinaryExpression.Expression);
        switch (analyzeTypeIsResult)
        {
        case AnalyzeTypeIsResult.KnownFalse:
        case AnalyzeTypeIsResult.KnownTrue:
            if (typeBinaryExpression.Expression.Type != typeof(void))
            {
                _instructions.EmitPop();
            }
            _instructions.EmitLoad(analyzeTypeIsResult == AnalyzeTypeIsResult.KnownTrue);
            break;
        case AnalyzeTypeIsResult.KnownAssignable:
            _instructions.EmitLoad(null);
            _instructions.EmitNotEqual(typeof(object));
            break;
        default:
            if (typeBinaryExpression.TypeOperand.IsValueType)
            {
                _instructions.EmitLoad(typeBinaryExpression.TypeOperand.GetNonNullableType());
                _instructions.EmitTypeEquals();
            }
            else
            {
                _instructions.EmitTypeIs(typeBinaryExpression.TypeOperand);
            }
            break;
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.ConstantCheck.AnalyzeTypeIs(), System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoad(), System.Linq.Expressions.Interpreter.InstructionList.EmitNotEqual(), System.Linq.Expressions.Interpreter.InstructionList.EmitPop(), System.Linq.Expressions.Interpreter.InstructionList.EmitTypeEquals(), and System.Linq.Expressions.Interpreter.InstructionList.EmitTypeIs().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().