Terraria: System.Xml.XmlBinaryNodeWriter.WriteInt64
WriteInt64()
void System.Xml.XmlBinaryNodeWriter.WriteInt64 (long value) inline private
Definition at line 586 of file XmlBinaryNodeWriter.cs.
    {
        int offset;
        byte[] buffer = GetBuffer(8, out offset);
        buffer[offset] = (byte)value;
        value >>= 8;
        buffer[offset + 1] = (byte)value;
        value >>= 8;
        buffer[offset + 2] = (byte)value;
        value >>= 8;
        buffer[offset + 3] = (byte)value;
        value >>= 8;
        buffer[offset + 4] = (byte)value;
        value >>= 8;
        buffer[offset + 5] = (byte)value;
        value >>= 8;
        buffer[offset + 6] = (byte)value;
        value >>= 8;
        buffer[offset + 7] = (byte)value;
        Advance(8);
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.buffer, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, and System.value.
Referenced by System.Xml.XmlBinaryNodeWriter.WriteDateTimeArray(), and System.Xml.XmlBinaryNodeWriter.WriteTimeSpanArray().