Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush
CompileNoLabelPush()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush (Expression expr) inline private
Definition at line 2248 of file LightCompiler.cs.
    {
        if (!_guard.TryEnterOnCurrentStack())
        {
            _guard.RunOnEmptyStack(delegate(LightCompiler @this, Expression e)
            {
                @this.CompileNoLabelPush(e);
            }, this, expr);
            return;
        }
        int currentStackDepth = _instructions.CurrentStackDepth;
        switch (expr.NodeType)
        {
        case ExpressionType.Add:
        case ExpressionType.AddChecked:
        case ExpressionType.And:
        case ExpressionType.ArrayIndex:
        case ExpressionType.Divide:
        case ExpressionType.Equal:
        case ExpressionType.ExclusiveOr:
        case ExpressionType.GreaterThan:
        case ExpressionType.GreaterThanOrEqual:
        case ExpressionType.LeftShift:
        case ExpressionType.LessThan:
        case ExpressionType.LessThanOrEqual:
        case ExpressionType.Modulo:
        case ExpressionType.Multiply:
        case ExpressionType.MultiplyChecked:
        case ExpressionType.NotEqual:
        case ExpressionType.Or:
        case ExpressionType.Power:
        case ExpressionType.RightShift:
        case ExpressionType.Subtract:
        case ExpressionType.SubtractChecked:
            CompileBinaryExpression(expr);
            break;
        case ExpressionType.AndAlso:
            CompileAndAlsoBinaryExpression(expr);
            break;
        case ExpressionType.OrElse:
            CompileOrElseBinaryExpression(expr);
            break;
        case ExpressionType.Coalesce:
            CompileCoalesceBinaryExpression(expr);
            break;
        case ExpressionType.ArrayLength:
        case ExpressionType.Negate:
        case ExpressionType.UnaryPlus:
        case ExpressionType.NegateChecked:
        case ExpressionType.Not:
        case ExpressionType.TypeAs:
        case ExpressionType.Decrement:
        case ExpressionType.Increment:
        case ExpressionType.OnesComplement:
        case ExpressionType.IsTrue:
        case ExpressionType.IsFalse:
            CompileUnaryExpression(expr);
            break;
        case ExpressionType.Convert:
        case ExpressionType.ConvertChecked:
            CompileConvertUnaryExpression(expr);
            break;
        case ExpressionType.Quote:
            CompileQuoteUnaryExpression(expr);
            break;
        case ExpressionType.Throw:
            CompileThrowUnaryExpression(expr, expr.Type == typeof(void));
            break;
        case ExpressionType.Unbox:
            CompileUnboxUnaryExpression(expr);
            break;
        case ExpressionType.Call:
            CompileMethodCallExpression(expr);
            break;
        case ExpressionType.Conditional:
            CompileConditionalExpression(expr, expr.Type == typeof(void));
            break;
        case ExpressionType.Constant:
            CompileConstantExpression(expr);
            break;
        case ExpressionType.Invoke:
            CompileInvocationExpression(expr);
            break;
        case ExpressionType.Lambda:
            CompileLambdaExpression(expr);
            break;
        case ExpressionType.ListInit:
            CompileListInitExpression(expr);
            break;
        case ExpressionType.MemberAccess:
            CompileMemberExpression(expr);
            break;
        case ExpressionType.MemberInit:
            CompileMemberInitExpression(expr);
            break;
        case ExpressionType.New:
            CompileNewExpression(expr);
            break;
        case ExpressionType.NewArrayInit:
        case ExpressionType.NewArrayBounds:
            CompileNewArrayExpression(expr);
            break;
        case ExpressionType.Parameter:
            CompileParameterExpression(expr);
            break;
        case ExpressionType.TypeIs:
            CompileTypeIsExpression(expr);
            break;
        case ExpressionType.TypeEqual:
            CompileTypeEqualExpression(expr);
            break;
        case ExpressionType.Assign:
            CompileAssignBinaryExpression(expr, expr.Type == typeof(void));
            break;
        case ExpressionType.Block:
            CompileBlockExpression(expr, expr.Type == typeof(void));
            break;
        case ExpressionType.DebugInfo:
            CompileDebugInfoExpression(expr);
            break;
        case ExpressionType.Default:
            CompileDefaultExpression(expr);
            break;
        case ExpressionType.Goto:
            CompileGotoExpression(expr);
            break;
        case ExpressionType.Index:
            CompileIndexExpression(expr);
            break;
        case ExpressionType.Label:
            CompileLabelExpression(expr);
            break;
        case ExpressionType.RuntimeVariables:
            CompileRuntimeVariablesExpression(expr);
            break;
        case ExpressionType.Loop:
            CompileLoopExpression(expr);
            break;
        case ExpressionType.Switch:
            CompileSwitchExpression(expr);
            break;
        case ExpressionType.Try:
            CompileTryExpression(expr);
            break;
        default:
            Compile(expr.ReduceAndCheck());
            break;
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._guard, System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAndAlsoBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAssignBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConditionalExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConstantExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileDebugInfoExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileDefaultExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileGotoExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileInvocationExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLabelExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLambdaExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileListInitExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLoopExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberInitExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodCallExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNewArrayExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNewExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(), System.Linq.Expressions.Interpreter.LightCompiler.CompileOrElseBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileParameterExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileQuoteUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileRuntimeVariablesExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileThrowUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeEqualExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeIsExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileUnboxUnaryExpression(), System.Linq.Expressions.Interpreter.InstructionList.CurrentStackDepth, System.Linq.Expressions.Expression< TDelegate >.NodeType, System.Linq.Expressions.Expression< TDelegate >.ReduceAndCheck(), System.Linq.Expressions.StackGuard.TryEnterOnCurrentStack(), and System.Linq.Expressions.Expression< TDelegate >.Type.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().