Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression
CompileConvertUnaryExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression (Expression expr) inline private
Definition at line 742 of file LightCompiler.cs.
    {
        UnaryExpression unaryExpression = (UnaryExpression)expr;
        if (unaryExpression.Method != null)
        {
            BranchLabel label = _instructions.MakeLabel();
            BranchLabel branchLabel = _instructions.MakeLabel();
            MethodInfo method = unaryExpression.Method;
            ParameterInfo[] parametersCached = method.GetParametersCached();
            ParameterInfo parameterInfo = parametersCached[0];
            Expression operand = unaryExpression.Operand;
            Type type = operand.Type;
            LocalDefinition definition = _locals.DefineLocal(Expression.Parameter(type), _instructions.Count);
            ByRefUpdater byRefUpdater = null;
            Type type2 = parameterInfo.ParameterType;
            if (type2.IsByRef)
            {
                if (unaryExpression.IsLifted)
                {
                    Compile(unaryExpression.Operand);
                }
                else
                {
                    byRefUpdater = CompileAddress(unaryExpression.Operand, 0);
                    type2 = type2.GetElementType();
                }
            }
            else
            {
                Compile(unaryExpression.Operand);
            }
            _instructions.EmitStoreLocal(definition.Index);
            if (!type.IsValueType || (type.IsNullableType() && unaryExpression.IsLiftedToNull))
            {
                _instructions.EmitLoadLocal(definition.Index);
                _instructions.EmitLoad(null, typeof(object));
                _instructions.EmitEqual(typeof(object));
                _instructions.EmitBranchTrue(branchLabel);
            }
            _instructions.EmitLoadLocal(definition.Index);
            if (type.IsNullableType() && type2.Equals(type.GetNonNullableType()))
            {
                _instructions.Emit(NullableMethodCallInstruction.CreateGetValue());
            }
            if (byRefUpdater == null)
            {
                _instructions.EmitCall(method);
            }
            else
            {
                _instructions.EmitByRefCall(method, parametersCached, new ByRefUpdater[1] { byRefUpdater });
                byRefUpdater.UndefineTemps(_instructions, _locals);
            }
            _instructions.EmitBranch(label, hasResult: false, hasValue: true);
            _instructions.MarkLabel(branchLabel);
            _instructions.EmitLoad(null, typeof(object));
            _instructions.MarkLabel(label);
            _locals.UndefineLocal(definition, _instructions.Count);
        }
        else if (unaryExpression.Type == typeof(void))
        {
            CompileAsVoid(unaryExpression.Operand);
        }
        else
        {
            Compile(unaryExpression.Operand);
            CompileConvertToType(unaryExpression.Operand.Type, unaryExpression.Type, unaryExpression.NodeType == ExpressionType.ConvertChecked, unaryExpression.IsLiftedToNull);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertToType(), System.Linq.Expressions.Interpreter.InstructionList.Count, System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.CreateGetValue(), System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.Emit(), System.Linq.Expressions.Interpreter.InstructionList.EmitBranch(), System.Linq.Expressions.Interpreter.InstructionList.EmitBranchTrue(), System.Linq.Expressions.Interpreter.InstructionList.EmitByRefCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitEqual(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoad(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoadLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitStoreLocal(), System.Linq.Expressions.Interpreter.InstructionList.MakeLabel(), System.Linq.Expressions.Interpreter.InstructionList.MarkLabel(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.type, and System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().