Terraria: System.Xml.XmlBinaryNodeWriter.WriteFloatText
WriteFloatText()
unsafe override void System.Xml.XmlBinaryNodeWriter.WriteFloatText (float f) inline
Definition at line 783 of file XmlBinaryNodeWriter.cs.
    {
        long value;
        if (f >= -9.223372E+18f && f <= 9.223372E+18f && (float)(value = (long)f) == f)
        {
            WriteInt64Text(value);
            return;
        }
        int offset;
        byte[] textNodeBuffer = GetTextNodeBuffer(5, out offset);
        byte* ptr = (byte*)(&f);
        textNodeBuffer[offset] = 144;
        textNodeBuffer[offset + 1] = *ptr;
        textNodeBuffer[offset + 2] = ptr[1];
        textNodeBuffer[offset + 3] = ptr[2];
        textNodeBuffer[offset + 4] = ptr[3];
        Advance(5);
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.Xml.Dictionary, System.Xml.E, System.Xml.XmlBinaryNodeWriter.GetTextNodeBuffer(), System.offset, System.value, and System.Xml.XmlBinaryNodeWriter.WriteInt64Text().
Referenced by System.Xml.XmlBinaryNodeWriter.WriteDoubleText().