Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberInit
CompileMemberInit()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberInit (ReadOnlyCollection< MemberBinding > bindings) inline private
Definition at line 2075 of file LightCompiler.cs.
    {
        foreach (MemberBinding binding in bindings)
        {
            switch (binding.BindingType)
            {
            case MemberBindingType.Assignment:
                _instructions.EmitDup();
                CompileMemberAssignment(asVoid: true, ((MemberAssignment)binding).Member, ((MemberAssignment)binding).Expression, forBinding: true);
                break;
            case MemberBindingType.ListBinding:
            {
                MemberListBinding memberListBinding = (MemberListBinding)binding;
                _instructions.EmitDup();
                CompileMember(null, memberListBinding.Member, forBinding: true);
                CompileListInit(memberListBinding.Initializers);
                _instructions.EmitPop();
                break;
            }
            case MemberBindingType.MemberBinding:
            {
                MemberMemberBinding memberMemberBinding = (MemberMemberBinding)binding;
                _instructions.EmitDup();
                Type memberType = GetMemberType(memberMemberBinding.Member);
                if (memberMemberBinding.Member is PropertyInfo && memberType.IsValueType)
                {
                    throw Error.CannotAutoInitializeValueTypeMemberThroughProperty(memberMemberBinding.Bindings);
                }
                CompileMember(null, memberMemberBinding.Member, forBinding: true);
                CompileMemberInit(memberMemberBinding.Bindings);
                _instructions.EmitPop();
                break;
            }
            }
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Error.CannotAutoInitializeValueTypeMemberThroughProperty(), System.Linq.Expressions.Interpreter.LightCompiler.CompileListInit(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMember(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberInit(), System.Linq.Expressions.Interpreter.InstructionList.EmitDup(), System.Linq.Expressions.Interpreter.InstructionList.EmitPop(), and System.Linq.Expressions.Interpreter.LightCompiler.GetMemberType().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberInit(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberInitExpression().