Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileStringSwitchExpression
CompileStringSwitchExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileStringSwitchExpression (SwitchExpression node) inline private
Definition at line 1231 of file LightCompiler.cs.
    {
        LabelInfo labelInfo = DefineLabel(null);
        bool flag = node.Type != typeof(void);
        Compile(node.SwitchValue);
        Dictionary<string, int> dictionary = new Dictionary<string, int>();
        int count = _instructions.Count;
        StrongBox<int> strongBox = new StrongBox<int>(1);
        _instructions.EmitStringSwitch(dictionary, strongBox);
        if (node.DefaultBody != null)
        {
            Compile(node.DefaultBody, !flag);
        }
        _instructions.EmitBranch(labelInfo.GetLabel(this), hasResult: false, flag);
        for (int i = 0; i < node.Cases.Count; i++)
        {
            SwitchCase switchCase = node.Cases[i];
            int value = _instructions.Count - count;
            foreach (ConstantExpression testValue in switchCase.TestValues)
            {
                string text = (string)testValue.Value;
                if (text == null)
                {
                    if (strongBox.Value == 1)
                    {
                        strongBox.Value = value;
                    }
                }
                else
                {
                    dictionary.TryAdd(text, value);
                }
            }
            Compile(switchCase.Body, !flag);
            if (i < node.Cases.Count - 1)
            {
                _instructions.EmitBranch(labelInfo.GetLabel(this), hasResult: false, flag);
            }
        }
        _instructions.MarkLabel(labelInfo.GetLabel(this));
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.InstructionList.Count, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Interpreter.LightCompiler.DefineLabel(), System.dictionary, System.Linq.Expressions.Interpreter.InstructionList.EmitBranch(), System.Linq.Expressions.Interpreter.InstructionList.EmitStringSwitch(), System.Linq.Expressions.Interpreter.InstructionList.MarkLabel(), System.text, and System.value.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression().