Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileLoopExpression
CompileLoopExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileLoopExpression (Expression expr) inline private
Definition at line 1125 of file LightCompiler.cs.
    {
        LoopExpression loopExpression = (LoopExpression)expr;
        PushLabelBlock(LabelScopeKind.Statement);
        LabelInfo labelInfo = DefineLabel(loopExpression.BreakLabel);
        LabelInfo labelInfo2 = DefineLabel(loopExpression.ContinueLabel);
        _instructions.MarkLabel(labelInfo2.GetLabel(this));
        CompileAsVoid(loopExpression.Body);
        _instructions.EmitBranch(labelInfo2.GetLabel(this), loopExpression.Type != typeof(void), hasValue: false);
        _instructions.MarkLabel(labelInfo.GetLabel(this));
        PopLabelBlock(LabelScopeKind.Statement);
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(), System.Linq.Expressions.Interpreter.LightCompiler.DefineLabel(), System.Linq.Expressions.Interpreter.InstructionList.EmitBranch(), System.Linq.Expressions.Interpreter.InstructionList.MarkLabel(), System.Linq.Expressions.Interpreter.LightCompiler.PopLabelBlock(), and System.Linq.Expressions.Interpreter.LightCompiler.PushLabelBlock().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().