Terraria: System.Xml.XmlBinaryNodeWriter.GetTextNodeBuffer
GetTextNodeBuffer()
byte[] System.Xml.XmlBinaryNodeWriter.GetTextNodeBuffer (int size, out int offset) inline private
Definition at line 160 of file XmlBinaryNodeWriter.cs.
    {
        if (_inAttribute)
        {
            WroteAttributeValue();
        }
        byte[] buffer = GetBuffer(size, out offset);
        _textNodeOffset = offset;
        return buffer;
    }
References System.Xml.XmlBinaryNodeWriter._inAttribute, System.Xml.XmlBinaryNodeWriter._textNodeOffset, System.buffer, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, and System.Xml.XmlBinaryNodeWriter.WroteAttributeValue().
Referenced by System.Xml.XmlBinaryNodeWriter.WriteDecimalText(), System.Xml.XmlBinaryNodeWriter.WriteDoubleText(), System.Xml.XmlBinaryNodeWriter.WriteFloatText(), System.Xml.XmlBinaryNodeWriter.WriteGuidText(), System.Xml.XmlBinaryNodeWriter.WriteInt32Text(), System.Xml.XmlBinaryNodeWriter.WriteTextNodeWithInt64(), System.Xml.XmlBinaryNodeWriter.WriteTextNodeWithLength(), and System.Xml.XmlBinaryNodeWriter.WriteUniqueIdText().