Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockStart
CompileBlockStart()
LocalDefinition[] System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockStart (BlockExpression node) inline private
Definition at line 325 of file LightCompiler.cs.
    {
        int count = _instructions.Count;
        ReadOnlyCollection<ParameterExpression> variables = node.Variables;
        LocalDefinition[] array;
        if (variables.Count != 0)
        {
            array = new LocalDefinition[variables.Count];
            int num = 0;
            foreach (ParameterExpression item in variables)
            {
                LocalDefinition localDefinition = _locals.DefineLocal(item, count);
                array[num++] = localDefinition;
                _instructions.EmitInitializeLocal(localDefinition.Index, item.Type);
            }
        }
        else
        {
            array = s_emptyLocals;
        }
        for (int i = 0; i < node.Expressions.Count - 1; i++)
        {
            CompileAsVoid(node.Expressions[i]);
        }
        return array;
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.array, System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(), System.Linq.Expressions.Interpreter.InstructionList.Count, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitInitializeLocal(), System.item, and System.Linq.Expressions.Interpreter.LightCompiler.s_emptyLocals.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockExpression().