Terraria: System.Threading.Semaphore.OpenExistingWorker
OpenExistingWorker()
static OpenExistingResult System.Threading.Semaphore.OpenExistingWorker (string name, out Semaphore result) inline static private
Definition at line 92 of file Semaphore.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "name");
        }
        SafeWaitHandle safeWaitHandle = Interop.Kernel32.OpenSemaphore(34603010u, inheritHandle: false, name);
        if (safeWaitHandle.IsInvalid)
        {
            result = null;
            switch (Marshal.GetLastPInvokeError())
            {
            case 2:
            case 123:
                return OpenExistingResult.NameNotFound;
            case 3:
                return OpenExistingResult.PathNotFound;
            case 6:
                return OpenExistingResult.NameInvalid;
            default:
                throw Win32Marshal.GetExceptionForLastWin32Error();
            }
        }
        result = new Semaphore(safeWaitHandle);
        return OpenExistingResult.Success;
    }
References System.Threading.Semaphore.Semaphore(), System.SR.Argument_EmptyName, System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, and Interop.Kernel32.OpenSemaphore().
Referenced by System.Threading.Semaphore.OpenExisting(), and System.Threading.Semaphore.TryOpenExisting().