Terraria: System.Linq.Expressions.Interpreter.LightCompiler.EnsureAvailableForClosure
EnsureAvailableForClosure()
LocalVariable System.Linq.Expressions.Interpreter.LightCompiler.EnsureAvailableForClosure (ParameterExpression expr) inline private
Definition at line 192 of file LightCompiler.cs.
    {
        if (_locals.TryGetLocalOrClosure(expr, out var local))
        {
            if (!local.InClosure && !local.IsBoxed)
            {
                _locals.Box(expr, _instructions);
            }
            return local;
        }
        if (_parent != null)
        {
            _parent.EnsureAvailableForClosure(expr);
            return _locals.AddClosureVariable(expr);
        }
        throw new InvalidOperationException("unbound variable: " + expr);
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Linq.Expressions.Interpreter.LightCompiler._parent, System.Linq.Expressions.Interpreter.LocalVariables.AddClosureVariable(), System.Linq.Expressions.Interpreter.LocalVariables.Box(), System.Linq.Expressions.Interpreter.LightCompiler.EnsureAvailableForClosure(), and System.Linq.Expressions.Interpreter.LocalVariables.TryGetLocalOrClosure().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileLambdaExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileQuoteUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileRuntimeVariablesExpression(), System.Linq.Expressions.Interpreter.LightCompiler.EnsureAvailableForClosure(), and System.Linq.Expressions.Interpreter.LightCompiler.ResolveLocal().