Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertToType
CompileConvertToType()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertToType (Type typeFrom, Type typeTo, bool isChecked, bool isLiftedToNull) inline private
Definition at line 812 of file LightCompiler.cs.
    {
        if (typeTo.Equals(typeFrom) || (typeFrom.IsValueType && typeTo.IsNullableType() && typeTo.GetNonNullableType().Equals(typeFrom)))
        {
            return;
        }
        if (typeTo.IsValueType && typeFrom.IsNullableType() && typeFrom.GetNonNullableType().Equals(typeTo))
        {
            _instructions.Emit(NullableMethodCallInstruction.CreateGetValue());
            return;
        }
        Type type = typeFrom.GetNonNullableType();
        Type type2 = typeTo.GetNonNullableType();
        if ((type.IsNumericOrBool() || type.IsEnum) && (type2.IsNumericOrBool() || type2.IsEnum || type2 == typeof(decimal)))
        {
            Type type3 = null;
            if (type.IsEnum)
            {
                type = Enum.GetUnderlyingType(type);
            }
            if (type2.IsEnum)
            {
                type3 = type2;
                type2 = Enum.GetUnderlyingType(type2);
            }
            TypeCode typeCode = type.GetTypeCode();
            TypeCode typeCode2 = type2.GetTypeCode();
            if (typeCode == typeCode2)
            {
                if ((object)type3 != null)
                {
                    if (typeFrom.IsNullableType() && !typeTo.IsNullableType())
                    {
                        _instructions.Emit(NullableMethodCallInstruction.CreateGetValue());
                    }
                }
                else
                {
                    _instructions.EmitConvertToUnderlying(typeCode2, isLiftedToNull);
                }
            }
            else if (isChecked)
            {
                _instructions.EmitNumericConvertChecked(typeCode, typeCode2, isLiftedToNull);
            }
            else
            {
                _instructions.EmitNumericConvertUnchecked(typeCode, typeCode2, isLiftedToNull);
            }
            if ((object)type3 != null)
            {
                _instructions.EmitCastToEnum(type3);
            }
        }
        else if (typeTo.IsEnum)
        {
            _instructions.Emit(NullCheckInstruction.Instance);
            _instructions.EmitCastReferenceToEnum(typeTo);
        }
        else if (!(typeTo == typeof(object)) && !typeTo.IsAssignableFrom(typeFrom))
        {
            _instructions.EmitCast(typeTo);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.NullableMethodCallInstruction.CreateGetValue(), System.Linq.Expressions.Interpreter.InstructionList.Emit(), System.Linq.Expressions.Interpreter.InstructionList.EmitCast(), System.Linq.Expressions.Interpreter.InstructionList.EmitCastReferenceToEnum(), System.Linq.Expressions.Interpreter.InstructionList.EmitCastToEnum(), System.Linq.Expressions.Interpreter.InstructionList.EmitConvertToUnderlying(), System.Linq.Expressions.Interpreter.InstructionList.EmitNumericConvertChecked(), System.Linq.Expressions.Interpreter.InstructionList.EmitNumericConvertUnchecked(), System.Enum.GetUnderlyingType(), System.Linq.Expressions.Interpreter.NullCheckInstruction.Instance, and System.type.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression().