Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileRuntimeVariablesExpression
CompileRuntimeVariablesExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileRuntimeVariablesExpression (Expression expr) inline private
Definition at line 1944 of file LightCompiler.cs.
    {
        RuntimeVariablesExpression runtimeVariablesExpression = (RuntimeVariablesExpression)expr;
        foreach (ParameterExpression variable in runtimeVariablesExpression.Variables)
        {
            EnsureAvailableForClosure(variable);
            CompileGetBoxedVariable(variable);
        }
        _instructions.EmitNewRuntimeVariables(runtimeVariablesExpression.Variables.Count);
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.CompileGetBoxedVariable(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Interpreter.InstructionList.EmitNewRuntimeVariables(), and System.Linq.Expressions.Interpreter.LightCompiler.EnsureAvailableForClosure().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().