Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileNewArrayExpression
CompileNewArrayExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileNewArrayExpression (Expression expr) inline private
Definition at line 1906 of file LightCompiler.cs.
    {
        NewArrayExpression newArrayExpression = (NewArrayExpression)expr;
        foreach (Expression expression in newArrayExpression.Expressions)
        {
            Compile(expression);
        }
        Type elementType = newArrayExpression.Type.GetElementType();
        int count = newArrayExpression.Expressions.Count;
        if (newArrayExpression.NodeType == ExpressionType.NewArrayInit)
        {
            _instructions.EmitNewArrayInit(elementType, count);
        }
        else if (count == 1)
        {
            _instructions.EmitNewArray(elementType);
        }
        else
        {
            _instructions.EmitNewArrayBounds(elementType, count);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.elementType, System.Linq.Expressions.Interpreter.InstructionList.EmitNewArray(), System.Linq.Expressions.Interpreter.InstructionList.EmitNewArrayBounds(), and System.Linq.Expressions.Interpreter.InstructionList.EmitNewArrayInit().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().