Terraria: System.Xml.XmlBinaryNodeWriter.WriteNode
WriteNode()
void System.Xml.XmlBinaryNodeWriter.WriteNode (XmlBinaryNodeType nodeType) inline private
Definition at line 135 of file XmlBinaryNodeWriter.cs.
    {
        WriteByte((byte)nodeType);
        _textNodeOffset = -1;
    }
References System.Xml.XmlBinaryNodeWriter._textNodeOffset, and System.Xml.XmlStreamNodeWriter.WriteByte().
Referenced by System.Xml.XmlBinaryNodeWriter.WriteArrayInfo(), System.Xml.XmlBinaryNodeWriter.WriteArrayNode(), System.Xml.XmlBinaryNodeWriter.WriteComment(), System.Xml.XmlBinaryNodeWriter.WriteEndElement(), System.Xml.XmlBinaryNodeWriter.WriteEndListText(), System.Xml.XmlBinaryNodeWriter.WritePrefixNode(), System.Xml.XmlBinaryNodeWriter.WriteStartAttribute(), System.Xml.XmlBinaryNodeWriter.WriteStartAttribute(), System.Xml.XmlBinaryNodeWriter.WriteStartElement(), System.Xml.XmlBinaryNodeWriter.WriteStartElement(), System.Xml.XmlBinaryNodeWriter.WriteStartListText(), System.Xml.XmlBinaryNodeWriter.WriteXmlnsAttribute(), and System.Xml.XmlBinaryNodeWriter.WriteXmlnsAttribute().