Terraria: System.Xml.XmlBinaryNodeWriter.UnsafeWriteName
UnsafeWriteName()
unsafe void System.Xml.XmlBinaryNodeWriter.UnsafeWriteName (char * chars, int charCount) inline private
Definition at line 457 of file XmlBinaryNodeWriter.cs.
    {
        if (charCount < 42)
        {
            int offset;
            byte[] buffer = GetBuffer(1 + charCount * 3, out offset);
            int num = UnsafeGetUTF8Chars(chars, charCount, buffer, offset + 1);
            buffer[offset] = (byte)num;
            Advance(1 + num);
        }
        else
        {
            int i = UnsafeGetUTF8Length(chars, charCount);
            WriteMultiByteInt32(i);
            UnsafeWriteUTF8Chars(chars, charCount);
        }
    }
References System.Xml.XmlStreamNodeWriter.Advance(), System.buffer, System.charCount, System.chars, System.Xml.Dictionary, System.Xml.XmlStreamNodeWriter.GetBuffer(), System.offset, System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Chars(), System.Xml.XmlStreamNodeWriter.UnsafeGetUTF8Length(), System.Xml.XmlStreamNodeWriter.UnsafeWriteUTF8Chars(), and System.Xml.XmlBinaryNodeWriter.WriteMultiByteInt32().
Referenced by System.Xml.XmlBinaryNodeWriter.WriteName().