Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodLogicalBinaryExpression
CompileMethodLogicalBinaryExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodLogicalBinaryExpression (BinaryExpression expr, bool andAlso) inline private
Definition at line 1002 of file LightCompiler.cs.
    {
        BranchLabel branchLabel = _instructions.MakeLabel();
        Compile(expr.Left);
        _instructions.EmitDup();
        MethodInfo booleanOperator = TypeUtils.GetBooleanOperator(expr.Method.DeclaringType, andAlso ? "op_False" : "op_True");
        _instructions.EmitCall(booleanOperator);
        _instructions.EmitBranchTrue(branchLabel);
        Compile(expr.Right);
        _instructions.EmitCall(expr.Method);
        _instructions.MarkLabel(branchLabel);
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Reflection.MemberInfo.DeclaringType, System.Linq.Expressions.Interpreter.InstructionList.EmitBranchTrue(), System.Linq.Expressions.Interpreter.InstructionList.EmitCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitDup(), System.Dynamic.Utils.TypeUtils.GetBooleanOperator(), System.Linq.Expressions.BinaryExpression.Left, System.Linq.Expressions.Interpreter.InstructionList.MakeLabel(), System.Linq.Expressions.Interpreter.InstructionList.MarkLabel(), System.Linq.Expressions.BinaryExpression.Method, and System.Linq.Expressions.BinaryExpression.Right.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileLogicalBinaryExpression().