Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileLabelExpression
CompileLabelExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileLabelExpression (Expression expr) inline private
Definition at line 1273 of file LightCompiler.cs.
    {
        LabelExpression labelExpression = (LabelExpression)expr;
        LabelInfo info = null;
        if (_labelBlock.Kind == LabelScopeKind.Block)
        {
            _labelBlock.TryGetLabelInfo(labelExpression.Target, out info);
            if (info == null && _labelBlock.Parent.Kind == LabelScopeKind.Switch)
            {
                _labelBlock.Parent.TryGetLabelInfo(labelExpression.Target, out info);
            }
        }
        if (info == null)
        {
            info = DefineLabel(labelExpression.Target);
        }
        if (labelExpression.DefaultValue != null)
        {
            if (labelExpression.Target.Type == typeof(void))
            {
                CompileAsVoid(labelExpression.DefaultValue);
            }
            else
            {
                Compile(labelExpression.DefaultValue);
            }
        }
        _instructions.MarkLabel(info.GetLabel(this));
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._labelBlock, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid(), System.Linq.Expressions.Interpreter.LightCompiler.DefineLabel(), System.info, System.Linq.Expressions.Interpreter.LabelScopeInfo.Kind, System.Linq.Expressions.Interpreter.InstructionList.MarkLabel(), System.Linq.Expressions.Interpreter.LabelScopeInfo.Parent, and System.Linq.Expressions.Interpreter.LabelScopeInfo.TryGetLabelInfo().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression().