Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileMember
CompileMember()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileMember (Expression from, MemberInfo member, bool forBinding) inline private
Definition at line 1850 of file LightCompiler.cs.
    {
        if (member is FieldInfo fieldInfo)
        {
            if (fieldInfo.IsLiteral)
            {
                _instructions.EmitLoad(fieldInfo.GetValue(null), fieldInfo.FieldType);
            }
            else if (fieldInfo.IsStatic)
            {
                if (forBinding)
                {
                    throw Error.InvalidProgram();
                }
                if (fieldInfo.IsInitOnly)
                {
                    _instructions.EmitLoad(fieldInfo.GetValue(null), fieldInfo.FieldType);
                }
                else
                {
                    _instructions.EmitLoadField(fieldInfo);
                }
            }
            else
            {
                if (from != null)
                {
                    EmitThisForMethodCall(from);
                }
                _instructions.EmitLoadField(fieldInfo);
            }
            return;
        }
        PropertyInfo propertyInfo = (PropertyInfo)member;
        if (propertyInfo != null)
        {
            MethodInfo getMethod = propertyInfo.GetGetMethod(nonPublic: true);
            if (forBinding && getMethod.IsStatic)
            {
                throw Error.InvalidProgram();
            }
            if (from != null)
            {
                EmitThisForMethodCall(from);
            }
            if (!getMethod.IsStatic && from != null && from.Type.IsNullableType())
            {
                _instructions.EmitNullableCall(getMethod, Array.Empty<ParameterInfo>());
            }
            else
            {
                _instructions.EmitCall(getMethod);
            }
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.InstructionList.EmitCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoad(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoadField(), System.Linq.Expressions.Interpreter.InstructionList.EmitNullableCall(), System.Linq.Expressions.Interpreter.LightCompiler.EmitThisForMethodCall(), System.Reflection.PropertyInfo.GetGetMethod(), and System.Linq.Expressions.Error.InvalidProgram().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberExpression(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberInit().