Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression
CompileLiftedLogicalBinaryExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression (BinaryExpression node, bool andAlso) inline private
Definition at line 1015 of file LightCompiler.cs.
    {
        BranchLabel branchLabel = _instructions.MakeLabel();
        BranchLabel branchLabel2 = _instructions.MakeLabel();
        BranchLabel branchLabel3 = _instructions.MakeLabel();
        BranchLabel label = _instructions.MakeLabel();
        LocalDefinition definition = _locals.DefineLocal(Expression.Parameter(node.Left.Type), _instructions.Count);
        LocalDefinition definition2 = _locals.DefineLocal(Expression.Parameter(node.Left.Type), _instructions.Count);
        Compile(node.Left);
        _instructions.EmitStoreLocal(definition2.Index);
        _instructions.EmitLoadLocal(definition2.Index);
        _instructions.EmitLoad(null, typeof(object));
        _instructions.EmitEqual(typeof(object));
        _instructions.EmitBranchTrue(branchLabel);
        _instructions.EmitLoadLocal(definition2.Index);
        if (andAlso)
        {
            _instructions.EmitBranchFalse(branchLabel2);
        }
        else
        {
            _instructions.EmitBranchTrue(branchLabel2);
        }
        _instructions.MarkLabel(branchLabel);
        LocalDefinition definition3 = _locals.DefineLocal(Expression.Parameter(node.Right.Type), _instructions.Count);
        Compile(node.Right);
        _instructions.EmitStoreLocal(definition3.Index);
        _instructions.EmitLoadLocal(definition3.Index);
        _instructions.EmitLoad(null, typeof(object));
        _instructions.EmitEqual(typeof(object));
        _instructions.EmitBranchTrue(branchLabel3);
        _instructions.EmitLoadLocal(definition3.Index);
        if (andAlso)
        {
            _instructions.EmitBranchFalse(branchLabel2);
        }
        else
        {
            _instructions.EmitBranchTrue(branchLabel2);
        }
        _instructions.EmitLoadLocal(definition2.Index);
        _instructions.EmitLoad(null, typeof(object));
        _instructions.EmitEqual(typeof(object));
        _instructions.EmitBranchTrue(branchLabel3);
        _instructions.EmitLoad(andAlso ? Utils.BoxedTrue : Utils.BoxedFalse, typeof(object));
        _instructions.EmitStoreLocal(definition.Index);
        _instructions.EmitBranch(label);
        _instructions.MarkLabel(branchLabel2);
        _instructions.EmitLoad(andAlso ? Utils.BoxedFalse : Utils.BoxedTrue, typeof(object));
        _instructions.EmitStoreLocal(definition.Index);
        _instructions.EmitBranch(label);
        _instructions.MarkLabel(branchLabel3);
        _instructions.EmitLoad(null, typeof(object));
        _instructions.EmitStoreLocal(definition.Index);
        _instructions.MarkLabel(label);
        _instructions.EmitLoadLocal(definition.Index);
        _locals.UndefineLocal(definition2, _instructions.Count);
        _locals.UndefineLocal(definition3, _instructions.Count);
        _locals.UndefineLocal(definition, _instructions.Count);
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Linq.Expressions.Utils.BoxedFalse, System.Linq.Expressions.Utils.BoxedTrue, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.InstructionList.Count, System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitBranch(), System.Linq.Expressions.Interpreter.InstructionList.EmitBranchFalse(), System.Linq.Expressions.Interpreter.InstructionList.EmitBranchTrue(), System.Linq.Expressions.Interpreter.InstructionList.EmitEqual(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoad(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoadLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitStoreLocal(), System.Linq.Expressions.Interpreter.InstructionList.MakeLabel(), System.Linq.Expressions.Interpreter.InstructionList.MarkLabel(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), and System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileLogicalBinaryExpression().