Terraria: System.Linq.Expressions.Interpreter.LightCompiler.ResolveLocal
ResolveLocal()
LocalVariable System.Linq.Expressions.Interpreter.LightCompiler.ResolveLocal (ParameterExpression variable) inline private
Definition at line 210 of file LightCompiler.cs.
    {
        if (!_locals.TryGetLocalOrClosure(variable, out var local))
        {
            return EnsureAvailableForClosure(variable);
        }
        return local;
    }
References System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Linq.Expressions.Interpreter.LightCompiler.EnsureAvailableForClosure(), and System.Linq.Expressions.Interpreter.LocalVariables.TryGetLocalOrClosure().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileGetBoxedVariable(), System.Linq.Expressions.Interpreter.LightCompiler.CompileQuoteUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSetVariable(), and System.Linq.Expressions.Interpreter.LightCompiler.LoadLocalNoValueTypeCopy().