Terraria: System.Linq.Expressions.Interpreter.LightCompiler.TryPushLabelBlock
TryPushLabelBlock()
bool System.Linq.Expressions.Interpreter.LightCompiler.TryPushLabelBlock (Expression node) inline private
Definition at line 1351 of file LightCompiler.cs.
    {
        switch (node.NodeType)
        {
        default:
            if (_labelBlock.Kind != LabelScopeKind.Expression)
            {
                PushLabelBlock(LabelScopeKind.Expression);
                return true;
            }
            return false;
        case ExpressionType.Label:
            if (_labelBlock.Kind == LabelScopeKind.Block)
            {
                LabelTarget target = ((LabelExpression)node).Target;
                if (_labelBlock.ContainsTarget(target))
                {
                    return false;
                }
                if (_labelBlock.Parent.Kind == LabelScopeKind.Switch && _labelBlock.Parent.ContainsTarget(target))
                {
                    return false;
                }
            }
            PushLabelBlock(LabelScopeKind.Statement);
            return true;
        case ExpressionType.Block:
            PushLabelBlock(LabelScopeKind.Block);
            if (_labelBlock.Parent.Kind != LabelScopeKind.Switch)
            {
                DefineBlockLabels(node);
            }
            return true;
        case ExpressionType.Switch:
        {
            PushLabelBlock(LabelScopeKind.Switch);
            SwitchExpression switchExpression = (SwitchExpression)node;
            foreach (SwitchCase @case in switchExpression.Cases)
            {
                DefineBlockLabels(@case.Body);
            }
            DefineBlockLabels(switchExpression.DefaultBody);
            return true;
        }
        case ExpressionType.Convert:
            if (!(node.Type != typeof(void)))
            {
                PushLabelBlock(LabelScopeKind.Statement);
                return true;
            }
            goto default;
        case ExpressionType.Conditional:
        case ExpressionType.Goto:
        case ExpressionType.Loop:
            PushLabelBlock(LabelScopeKind.Statement);
            return true;
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._labelBlock, System.Linq.Expressions.Interpreter.LabelScopeInfo.ContainsTarget(), System.Linq.Expressions.Interpreter.LightCompiler.DefineBlockLabels(), System.Linq.Expressions.Interpreter.LabelScopeInfo.Kind, System.Linq.Expressions.Interpreter.LabelScopeInfo.Parent, and System.Linq.Expressions.Interpreter.LightCompiler.PushLabelBlock().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.Compile(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid().