Terraria: System.Xml.XmlBinaryNodeWriter.SetOutput
SetOutput() [2/2]
void System.Xml.XmlBinaryNodeWriter.SetOutput (Stream stream, IXmlDictionary dictionary, XmlBinaryWriterSession session, bool ownsStream) inline
Definition at line 124 of file XmlBinaryNodeWriter.cs.
    {
        _dictionary = dictionary;
        _session = session;
        _inAttribute = false;
        _inList = false;
        _attributeValue.Clear();
        _textNodeOffset = -1;
        SetOutput(stream, ownsStream, null);
    }
References System.Xml.XmlBinaryNodeWriter._attributeValue, System.Xml.XmlBinaryNodeWriter._dictionary, System.Xml.XmlBinaryNodeWriter._inAttribute, System.Xml.XmlBinaryNodeWriter._inList, System.Xml.XmlBinaryNodeWriter._session, System.Xml.XmlBinaryNodeWriter._textNodeOffset, System.Xml.XmlBinaryNodeWriter.AttributeValue.Clear(), System.dictionary, System.Xml.Dictionary, System.Xml.XmlBinaryNodeWriter.SetOutput(), and System.stream.
Referenced by System.Xml.XmlBinaryNodeWriter.SetOutput(), and System.Xml.XmlBinaryWriter.SetOutput().