Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression
CompileCoalesceBinaryExpression()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression (Expression expr) inline private
Definition at line 1971 of file LightCompiler.cs.
    {
        BinaryExpression binaryExpression = (BinaryExpression)expr;
        bool flag = binaryExpression.Conversion != null;
        bool flag2 = false;
        if (!flag && binaryExpression.Left.Type.IsNullableType())
        {
            Type type = binaryExpression.Left.Type;
            if (!binaryExpression.Type.IsNullableType())
            {
                type = type.GetNonNullableType();
            }
            if (!TypeUtils.AreEquivalent(binaryExpression.Type, type))
            {
                flag2 = true;
                flag = true;
            }
        }
        BranchLabel branchLabel = _instructions.MakeLabel();
        BranchLabel label = null;
        Compile(binaryExpression.Left);
        _instructions.EmitCoalescingBranch(branchLabel);
        _instructions.EmitPop();
        Compile(binaryExpression.Right);
        if (flag)
        {
            label = _instructions.MakeLabel();
            _instructions.EmitBranch(label);
        }
        else if (binaryExpression.Right.Type.IsValueType && !TypeUtils.AreEquivalent(binaryExpression.Type, binaryExpression.Right.Type))
        {
            CompileConvertToType(binaryExpression.Right.Type, binaryExpression.Type, isChecked: true, binaryExpression.Type.IsNullableType());
        }
        _instructions.MarkLabel(branchLabel);
        if (binaryExpression.Conversion != null)
        {
            ParameterExpression parameterExpression = Expression.Parameter(binaryExpression.Left.Type, "temp");
            LocalDefinition definition = _locals.DefineLocal(parameterExpression, _instructions.Count);
            _instructions.EmitStoreLocal(definition.Index);
            LambdaExpression? conversion = binaryExpression.Conversion;
            MethodInfo invokeMethod = binaryExpression.Conversion.Type.GetInvokeMethod();
            Expression[] arguments = new ParameterExpression[1] { parameterExpression };
            CompileMethodCallExpression(Expression.Call(conversion, invokeMethod, arguments));
            _locals.UndefineLocal(definition, _instructions.Count);
        }
        else if (flag2)
        {
            Type nonNullableType = binaryExpression.Left.Type.GetNonNullableType();
            CompileConvertToType(nonNullableType, binaryExpression.Type, isChecked: true, isLiftedToNull: false);
        }
        if (flag)
        {
            _instructions.MarkLabel(label);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertToType(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodCallExpression(), System.Linq.Expressions.Interpreter.InstructionList.Count, System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitBranch(), System.Linq.Expressions.Interpreter.InstructionList.EmitCoalescingBranch(), System.Linq.Expressions.Interpreter.InstructionList.EmitPop(), System.Linq.Expressions.Interpreter.InstructionList.EmitStoreLocal(), System.Linq.Expressions.Interpreter.InstructionList.MakeLabel(), System.Linq.Expressions.Interpreter.InstructionList.MarkLabel(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), System.type, and System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush().