Terraria: System.Xml.XmlBinaryNodeWriter.TryGetKey
TryGetKey()
bool System.Xml.XmlBinaryNodeWriter.TryGetKey (XmlDictionaryString s, out int key) inline private
Definition at line 413 of file XmlBinaryNodeWriter.cs.
    {
        key = -1;
        if (s.Dictionary == _dictionary)
        {
            key = s.Key * 2;
            return true;
        }
        if (_dictionary != null && _dictionary.TryLookup(s, out XmlDictionaryString result))
        {
            key = result.Key * 2;
            return true;
        }
        if (_session == null)
        {
            return false;
        }
        if (!_session.TryLookup(s, out var key2) && !_session.TryAdd(s, out key2))
        {
            return false;
        }
        key = key2 * 2 + 1;
        return true;
    }
References System.Xml.XmlBinaryNodeWriter._dictionary, System.Xml.XmlBinaryNodeWriter._session, System.Xml.Dictionary, System.key, System.s, System.Xml.XmlBinaryWriterSession.TryAdd(), System.Xml.IXmlDictionary.TryLookup(), and System.Xml.XmlBinaryWriterSession.TryLookup().
Referenced by System.Xml.XmlBinaryNodeWriter.WriteQualifiedName(), System.Xml.XmlBinaryNodeWriter.WriteStartAttribute(), System.Xml.XmlBinaryNodeWriter.WriteStartElement(), System.Xml.XmlBinaryNodeWriter.WriteText(), and System.Xml.XmlBinaryNodeWriter.WriteXmlnsAttribute().