Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileSetVariable
CompileSetVariable()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileSetVariable (ParameterExpression variable, bool isVoid) inline private
Definition at line 272 of file LightCompiler.cs.
    {
        LocalVariable localVariable = ResolveLocal(variable);
        if (localVariable.InClosure)
        {
            if (isVoid)
            {
                _instructions.EmitStoreLocalToClosure(localVariable.Index);
            }
            else
            {
                _instructions.EmitAssignLocalToClosure(localVariable.Index);
            }
        }
        else if (localVariable.IsBoxed)
        {
            if (isVoid)
            {
                _instructions.EmitStoreLocalBoxed(localVariable.Index);
            }
            else
            {
                _instructions.EmitAssignLocalBoxed(localVariable.Index);
            }
        }
        else if (isVoid)
        {
            _instructions.EmitStoreLocal(localVariable.Index);
        }
        else
        {
            _instructions.EmitAssignLocal(localVariable.Index);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.InstructionList.EmitAssignLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitAssignLocalBoxed(), System.Linq.Expressions.Interpreter.InstructionList.EmitAssignLocalToClosure(), System.Linq.Expressions.Interpreter.InstructionList.EmitStoreLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitStoreLocalBoxed(), System.Linq.Expressions.Interpreter.InstructionList.EmitStoreLocalToClosure(), and System.Linq.Expressions.Interpreter.LightCompiler.ResolveLocal().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileVariableAssignment().