Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexAssignment
CompileIndexAssignment()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexAssignment (BinaryExpression node, bool asVoid) inline private
Definition at line 391 of file LightCompiler.cs.
    {
        IndexExpression indexExpression = (IndexExpression)node.Left;
        if (indexExpression.Object != null)
        {
            EmitThisForMethodCall(indexExpression.Object);
        }
        int i = 0;
        for (int argumentCount = indexExpression.ArgumentCount; i < argumentCount; i++)
        {
            Compile(indexExpression.GetArgument(i));
        }
        Compile(node.Right);
        LocalDefinition definition = default(LocalDefinition);
        if (!asVoid)
        {
            definition = _locals.DefineLocal(Expression.Parameter(node.Right.Type), _instructions.Count);
            _instructions.EmitAssignLocal(definition.Index);
        }
        if (indexExpression.Indexer != null)
        {
            _instructions.EmitCall(indexExpression.Indexer.GetSetMethod(nonPublic: true));
        }
        else if (indexExpression.ArgumentCount != 1)
        {
            _instructions.EmitCall(TypeUtils.GetArraySetMethod(indexExpression.Object.Type));
        }
        else
        {
            _instructions.EmitSetArrayItem();
        }
        if (!asVoid)
        {
            _instructions.EmitLoadLocal(definition.Index);
            _locals.UndefineLocal(definition, _instructions.Count);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler._locals, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.InstructionList.Count, System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitAssignLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitLoadLocal(), System.Linq.Expressions.Interpreter.InstructionList.EmitSetArrayItem(), System.Linq.Expressions.Interpreter.LightCompiler.EmitThisForMethodCall(), System.Dynamic.Utils.TypeUtils.GetArraySetMethod(), System.Linq.Expressions.Expression< TDelegate >.Parameter(), and System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileAssignBinaryExpression().