Terraria: System.Linq.Expressions.Interpreter.LightCompiler.Compile
Compile() [2/2]
void System.Linq.Expressions.Interpreter.LightCompiler.Compile (Expression expr, bool asVoid) inline private
Definition at line 2203 of file LightCompiler.cs.
    {
        if (asVoid)
        {
            CompileAsVoid(expr);
        }
        else
        {
            Compile(expr);
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler.Compile(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileAsVoid().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileArithmetic(), System.Linq.Expressions.Interpreter.LightCompiler.CompileArrayIndexAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileComparison(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConditionalExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileEqual(), System.Linq.Expressions.Interpreter.LightCompiler.CompileGotoExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIntSwitchExpression< T >(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLabelExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileListInit(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodCallExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMethodLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMultiDimArrayAccess(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNewArrayExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNewExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNotEqual(), System.Linq.Expressions.Interpreter.LightCompiler.CompileNotExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileStringSwitchExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileThrowUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTop(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryFaultExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeAsExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeEqualExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTypeIsExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileUnboxUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileUnliftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileVariableAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryBoolCheck(), and System.Linq.Expressions.Interpreter.LightCompiler.EmitUnaryMethodCall().