Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileArithmetic
CompileArithmetic()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileArithmetic (ExpressionType nodeType, Expression left, Expression right) inline private
Definition at line 707 of file LightCompiler.cs.
    {
        Compile(left);
        Compile(right);
        switch (nodeType)
        {
        case ExpressionType.Add:
            _instructions.EmitAdd(left.Type, @checked: false);
            break;
        case ExpressionType.AddChecked:
            _instructions.EmitAdd(left.Type, @checked: true);
            break;
        case ExpressionType.Subtract:
            _instructions.EmitSub(left.Type, @checked: false);
            break;
        case ExpressionType.SubtractChecked:
            _instructions.EmitSub(left.Type, @checked: true);
            break;
        case ExpressionType.Multiply:
            _instructions.EmitMul(left.Type, @checked: false);
            break;
        case ExpressionType.MultiplyChecked:
            _instructions.EmitMul(left.Type, @checked: true);
            break;
        case ExpressionType.Divide:
            _instructions.EmitDiv(left.Type);
            break;
        case ExpressionType.Modulo:
            _instructions.EmitModulo(left.Type);
            break;
        default:
            throw ContractUtils.Unreachable;
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Linq.Expressions.Interpreter.InstructionList.EmitAdd(), System.Linq.Expressions.Interpreter.InstructionList.EmitDiv(), System.Linq.Expressions.Interpreter.InstructionList.EmitModulo(), System.Linq.Expressions.Interpreter.InstructionList.EmitMul(), System.Linq.Expressions.Interpreter.InstructionList.EmitSub(), System.Linq.Expressions.Expression< TDelegate >.Type, and System.Dynamic.Utils.ContractUtils.Unreachable.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression().