Terraria: System.Xml.XmlBinaryNodeWriter.WriteXmlnsAttribute
WriteXmlnsAttribute() [3/3]
override void System.Xml.XmlBinaryNodeWriter.WriteXmlnsAttribute (string prefix, XmlDictionaryString ns) inline
Definition at line 394 of file XmlBinaryNodeWriter.cs.
    {
        if (!TryGetKey(ns, out var key))
        {
            WriteXmlnsAttribute(prefix, ns.Value);
        }
        else if (string.IsNullOrEmpty(prefix))
        {
            WriteNode(XmlBinaryNodeType.ShortDictionaryXmlnsAttribute);
            WriteDictionaryString(ns, key);
        }
        else
        {
            WriteNode(XmlBinaryNodeType.DictionaryXmlnsAttribute);
            WriteName(prefix);
            WriteDictionaryString(ns, key);
        }
    }
References System.Xml.Dictionary, System.key, System.prefix, System.Xml.XmlBinaryNodeWriter.TryGetKey(), System.Xml.XmlDictionaryString.Value, System.Xml.XmlBinaryNodeWriter.WriteDictionaryString(), System.Xml.XmlBinaryNodeWriter.WriteName(), System.Xml.XmlBinaryNodeWriter.WriteNode(), and System.Xml.XmlBinaryNodeWriter.WriteXmlnsAttribute().