Terraria: System.Linq.Expressions.Interpreter.LightCompiler.CompileListInit
CompileListInit()
void System.Linq.Expressions.Interpreter.LightCompiler.CompileListInit (ReadOnlyCollection< ElementInit > initializers) inline private
Definition at line 2049 of file LightCompiler.cs.
    {
        for (int i = 0; i < initializers.Count; i++)
        {
            ElementInit elementInit = initializers[i];
            _instructions.EmitDup();
            foreach (Expression argument in elementInit.Arguments)
            {
                Compile(argument);
            }
            MethodInfo addMethod = elementInit.AddMethod;
            _instructions.EmitCall(addMethod);
            if (addMethod.ReturnType != typeof(void))
            {
                _instructions.EmitPop();
            }
        }
    }
References System.Linq.Expressions.Interpreter.LightCompiler._instructions, System.Linq.Expressions.Interpreter.LightCompiler.Compile(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Interpreter.InstructionList.EmitCall(), System.Linq.Expressions.Interpreter.InstructionList.EmitDup(), and System.Linq.Expressions.Interpreter.InstructionList.EmitPop().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileListInitExpression(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberInit().