Terraria: System.Xml.Linq.XNodeBuilder.AddString
AddString()
void System.Xml.Linq.XNodeBuilder.AddString (string s) inline private
Definition at line 238 of file XNodeBuilder.cs.
    {
        if (s != null)
        {
            if (_attrValue != null)
            {
                _attrValue += s;
            }
            else if (_parent != null)
            {
                _parent.Add(s);
            }
            else
            {
                Add(s);
            }
        }
    }
References System.Xml.Linq.XNodeBuilder._attrValue, System.Xml.Linq.XNodeBuilder._parent, System.Xml.Linq.XContainer.Add(), System.Xml.Linq.Add, and System.s.
Referenced by System.Xml.Linq.XNodeBuilder.WriteCharEntity(), System.Xml.Linq.XNodeBuilder.WriteChars(), System.Xml.Linq.XNodeBuilder.WriteEntityRef(), System.Xml.Linq.XNodeBuilder.WriteRaw(), System.Xml.Linq.XNodeBuilder.WriteRaw(), System.Xml.Linq.XNodeBuilder.WriteString(), System.Xml.Linq.XNodeBuilder.WriteSurrogateCharEntity(), and System.Xml.Linq.XNodeBuilder.WriteWhitespace().