Terraria: System.Xml.Linq.XNodeBuilder.AddNode
AddNode()
void System.Xml.Linq.XNodeBuilder.AddNode (XNode n) inline private
Definition at line 222 of file XNodeBuilder.cs.
    {
        if (_parent != null)
        {
            _parent.Add(n);
        }
        else
        {
            Add(n);
        }
        if (n is XContainer parent)
        {
            _parent = parent;
        }
    }
References System.Xml.Linq.XNodeBuilder._parent, System.Xml.Linq.XContainer.Add(), and System.Xml.Linq.Add.
Referenced by System.Xml.Linq.XNodeBuilder.WriteCData(), System.Xml.Linq.XNodeBuilder.WriteComment(), System.Xml.Linq.XNodeBuilder.WriteDocType(), System.Xml.Linq.XNodeBuilder.WriteProcessingInstruction(), and System.Xml.Linq.XNodeBuilder.WriteStartElement().