Terraria: System.Xml.Xsl.IlGen.GenerateHelper.Call
Call()
void System.Xml.Xsl.IlGen.GenerateHelper.Call (MethodInfo meth) inline
Definition at line 216 of file GenerateHelper.cs.
    {
        OpCode opcode = ((meth.IsVirtual || meth.IsAbstract) ? OpCodes.Callvirt : OpCodes.Call);
        _ilgen.Emit(opcode, meth);
        if (_lastSourceInfo != null)
        {
            MarkSequencePoint(SourceLineInfo.NoSource);
        }
    }
References System.Xml.Xsl.IlGen.GenerateHelper._ilgen, System.Xml.Xsl.IlGen.GenerateHelper._lastSourceInfo, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.OpCodes.Callvirt, System.Xml.Dictionary, System.Reflection.Emit.ILGenerator.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.MarkSequencePoint(), and System.Xml.Xsl.SourceLineInfo.NoSource.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.ComparePosition(), System.Xml.Xsl.IlGen.XmlILVisitor.CopySequence(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator(), System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSimpleIterator(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureStack(), System.Xml.Xsl.XmlILGenerator.EvaluateGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Xsl.XmlILGenerator.GenerateExecuteFunction(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds(), System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDataSource(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDeref(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitError(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIs(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsType(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNodeProperty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitParent(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRoot(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTextCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitWarning(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXmlContext(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltConvert(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopyOf(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().