Terraria: System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel
MarkLabel()
void System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel (Label lbl) inline
Definition at line 818 of file GenerateHelper.cs.
    {
        if (_lastSourceInfo != null && !_lastSourceInfo.IsNoSource)
        {
            DebugSequencePoint(SourceLineInfo.NoSource);
        }
        _ilgen.MarkLabel(lbl);
    }
References System.Xml.Xsl.IlGen.GenerateHelper._ilgen, System.Xml.Xsl.IlGen.GenerateHelper._lastSourceInfo, System.Xml.Xsl.IlGen.GenerateHelper.DebugSequencePoint(), System.Xml.Dictionary, System.Xml.Xsl.ISourceLineInfo.IsNoSource, System.Reflection.Emit.ILGenerator.MarkLabel(), and System.Xml.Xsl.SourceLineInfo.NoSource.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.BranchAndMark(), System.Xml.Xsl.IlGen.GenerateHelper.ConvBranchToBool(), System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.EndConjunctiveTests(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitOr(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTypeAssert(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound().