Terraria: System.Xml.Xsl.IlGen.GenerateHelper.Emit
Emit() [1/11]
void System.Xml.Xsl.IlGen.GenerateHelper.Emit (OpCode opcode) inline
Definition at line 827 of file GenerateHelper.cs.
    {
        _ilgen.Emit(opcode);
    }
References System.Xml.Xsl.IlGen.GenerateHelper._ilgen, and System.Reflection.Emit.ILGenerator.Emit().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.Compare(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator(), System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSimpleIterator(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Xml.Xsl.IlGen.IteratorDescriptor.DiscardStack(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocal(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.XmlILGenerator.EvaluateGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds(), System.Xml.Xsl.IlGen.IteratorDescriptor.PushValue(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.SyncToNavigator(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDataSource(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDeref(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitError(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralDouble(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralInt64(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralString(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNodeProperty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitParent(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRoot(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().