Terraria: System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel
DefineLabel()
Label System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel () inline
Definition at line 813 of file GenerateHelper.cs.
    {
        return _ilgen.DefineLabel();
    }
References System.Xml.Xsl.IlGen.GenerateHelper._ilgen, and System.Reflection.Emit.ILGenerator.DefineLabel().
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.ConvBranchToBool(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateConcat(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateSimpleIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartConjunctiveTests(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNot(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitOr(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTypeAssert(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound().