Terraria: System.Xml.Xsl.IlGen.GenerateHelper.MarkSequencePoint
MarkSequencePoint()
void System.Xml.Xsl.IlGen.GenerateHelper.MarkSequencePoint (ISourceLineInfo sourceInfo) inline private
Definition at line 804 of file GenerateHelper.cs.
    {
        if (!sourceInfo.IsNoSource || _lastSourceInfo == null || !_lastSourceInfo.IsNoSource)
        {
            string fileName = GetFileName(sourceInfo);
            _lastSourceInfo = sourceInfo;
        }
    }
References System.Xml.Xsl.IlGen.GenerateHelper._lastSourceInfo, System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.GetFileName(), and System.Xml.Xsl.ISourceLineInfo.IsNoSource.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DebugSequencePoint(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), and System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin().