Terraria: System.Xml.Xsl.IlGen.GenerateHelper.CallValueAs
CallValueAs()
void System.Xml.Xsl.IlGen.GenerateHelper.CallValueAs (Type clrType) inline
Definition at line 717 of file GenerateHelper.cs.
    {
        MethodInfo valueAs = XmlILMethods.StorageMethods[clrType].ValueAs;
        if (valueAs == null)
        {
            LoadType(clrType);
            Emit(OpCodes.Ldnull);
            Call(XmlILMethods.ValueAsAny);
            TreatAs(typeof(object), clrType);
        }
        else
        {
            Call(valueAs);
        }
    }
References System.Reflection.Emit.Call, System.Xml.Dictionary, System.Reflection.Emit.OpCodes.Ldnull, System.Xml.Xsl.IlGen.GenerateHelper.LoadType(), System.Xml.Xsl.IlGen.XmlILMethods.StorageMethods, System.Xml.Xsl.IlGen.GenerateHelper.TreatAs(), and System.Xml.Xsl.IlGen.XmlILMethods.ValueAsAny.
Referenced by System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType().