Terraria: System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin
MethodBegin()
void System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin (MethodBase methInfo, ISourceLineInfo sourceInfo, bool initWriters) inline
Definition at line 44 of file GenerateHelper.cs.
    {
        _methInfo = methInfo;
        _ilgen = XmlILModule.DefineMethodBody(methInfo);
        _lastSourceInfo = null;
        if (_isDebug)
        {
            DebugStartScope();
            if (sourceInfo != null)
            {
                MarkSequencePoint(sourceInfo);
                Emit(OpCodes.Nop);
            }
        }
        else if (_module.EmitSymbols && sourceInfo != null)
        {
            MarkSequencePoint(sourceInfo);
            _lastSourceInfo = null;
        }
        _initWriters = false;
        if (initWriters)
        {
            EnsureWriter();
            LoadQueryRuntime();
            Call(XmlILMethods.GetOutput);
            Emit(OpCodes.Stloc, _locXOut);
        }
    }
References System.Xml.Xsl.IlGen.GenerateHelper._ilgen, System.Xml.Xsl.IlGen.GenerateHelper._initWriters, System.Xml.Xsl.IlGen.GenerateHelper._isDebug, System.Xml.Xsl.IlGen.GenerateHelper._lastSourceInfo, System.Xml.Xsl.IlGen.GenerateHelper._locXOut, System.Xml.Xsl.IlGen.GenerateHelper._methInfo, System.Xml.Xsl.IlGen.GenerateHelper._module, System.Reflection.Emit.Call, System.Xml.Xsl.IlGen.GenerateHelper.DebugStartScope(), System.Xml.Xsl.IlGen.XmlILModule.DefineMethodBody(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILModule.EmitSymbols, System.Xml.Xsl.IlGen.GenerateHelper.EnsureWriter(), System.Xml.Xsl.IlGen.XmlILMethods.GetOutput, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.GenerateHelper.MarkSequencePoint(), System.Reflection.Emit.OpCodes.Nop, and System.Reflection.Emit.OpCodes.Stloc.
Referenced by System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.XmlILGenerator.GenerateExecuteFunction(), System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues().