Terraria: System.Xml.Xsl.IlGen.GenerateHelper.DebugEndScope
DebugEndScope()
void System.Xml.Xsl.IlGen.GenerateHelper.DebugEndScope () inline
Definition at line 781 of file GenerateHelper.cs.
    {
        _ilgen.EndScope();
    }
References System.Xml.Xsl.IlGen.GenerateHelper._ilgen, and System.Reflection.Emit.ILGenerator.EndScope().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.EndBinding(), and System.Xml.Xsl.IlGen.GenerateHelper.MethodEnd().