Terraria: System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryOutput
LoadQueryOutput()
void System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryOutput () inline
Definition at line 129 of file GenerateHelper.cs.
    {
        Emit(OpCodes.Ldloc, _locXOut);
    }
References System.Xml.Xsl.IlGen.GenerateHelper._locXOut, and System.Reflection.Emit.OpCodes.Ldloc.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.CallEndTree(), System.Xml.Xsl.IlGen.GenerateHelper.CallStartElementContent(), System.Xml.Xsl.IlGen.GenerateHelper.CallStartTree(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteEndAttribute(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteEndComment(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteEndPI(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteEndRoot(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteStartComment(), System.Xml.Xsl.IlGen.GenerateHelper.CallWriteStartRoot(), System.Xml.Xsl.IlGen.XmlILVisitor.CopySequence(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNamespaceDecl(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitPICtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTextCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopy(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltCopyOf().