Terraria: System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger
LoadInteger()
void System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger (int intVal) inline
Definition at line 91 of file GenerateHelper.cs.
    {
        Emit(OpCodes.Ldc_I4, intVal);
    }
References System.Xml.Dictionary, and System.Reflection.Emit.OpCodes.Ldc_I4.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.CallGetAtomizedName(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetCollation(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetEarlyBoundObject(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetGlobalValue(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetNameFilter(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetTypeFilter(), System.Xml.Xsl.IlGen.GenerateHelper.CallStartTree(), System.Xml.Xsl.IlGen.XmlILVisitor.ComparePosition(), System.Xml.Xsl.IlGen.GenerateHelper.ConstructLiteralDecimal(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureItemStorageType(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.MatchesNodeKinds(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.GenerateHelper.TestAndBranch(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsType(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralInt32(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrParseQName(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().