Terraria: System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch
EmitUnconditionalBranch()
void System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch (OpCode opcode, Label lblTarget) inline
Definition at line 882 of file GenerateHelper.cs.
    {
        if (!opcode.Equals(OpCodes.Br) && !opcode.Equals(OpCodes.Br_S))
        {
            Emit(OpCodes.Ldc_I4_1);
        }
        _ilgen.Emit(opcode, lblTarget);
        if (_lastSourceInfo != null && (opcode.Equals(OpCodes.Br) || opcode.Equals(OpCodes.Br_S)))
        {
            MarkSequencePoint(SourceLineInfo.NoSource);
        }
    }
References System.Xml.Xsl.IlGen.GenerateHelper._ilgen, System.Xml.Xsl.IlGen.GenerateHelper._lastSourceInfo, System.Reflection.Emit.OpCodes.Br, System.Reflection.Emit.OpCodes.Br_S, System.Xml.Dictionary, System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.OpCode.Equals(), System.Reflection.Emit.OpCodes.Ldc_I4_1, System.Xml.Xsl.IlGen.GenerateHelper.MarkSequencePoint(), and System.Xml.Xsl.SourceLineInfo.NoSource.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.BranchAndMark(), System.Xml.Xsl.IlGen.GenerateHelper.ConvBranchToBool(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.GenerateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitChoice(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitFalse(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSortKey(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTrue(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitXPathNodeValue(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltGenerateId().