Terraria: System.Xml.Xsl.IlGen.GenerateHelper.EnsureWriter
EnsureWriter()
void System.Xml.Xsl.IlGen.GenerateHelper.EnsureWriter () inline private
Definition at line 481 of file GenerateHelper.cs.
    {
        if (!_initWriters)
        {
            _locXOut = DeclareLocal("$$$xwrtChk", typeof(XmlQueryOutput));
            _initWriters = true;
        }
    }
References System.Xml.Xsl.IlGen.GenerateHelper._initWriters, System.Xml.Xsl.IlGen.GenerateHelper._locXOut, System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.CallStartRtfConstruction(), System.Xml.Xsl.IlGen.GenerateHelper.CallStartSequenceConstruction(), and System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin().