Terraria: System.Xml.Xsl.IlGen.GenerateHelper.CallStartRtfConstruction
CallStartRtfConstruction()
void System.Xml.Xsl.IlGen.GenerateHelper.CallStartRtfConstruction (string baseUri) inline
Definition at line 387 of file GenerateHelper.cs.
    {
        EnsureWriter();
        LoadQueryRuntime();
        Emit(OpCodes.Ldstr, baseUri);
        Emit(OpCodes.Ldloca, _locXOut);
        Call(XmlILMethods.StartRtfConstr);
    }
References System.Xml.Xsl.IlGen.GenerateHelper._locXOut, System.Reflection.Emit.Call, System.Xml.Xsl.IlGen.GenerateHelper.EnsureWriter(), System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.OpCodes.Ldstr, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), and System.Xml.Xsl.IlGen.XmlILMethods.StartRtfConstr.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor().