Terraria: System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal
DeclareLocal()
LocalBuilder System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal (string name, Type type) inline
Definition at line 107 of file GenerateHelper.cs.
    {
        return _ilgen.DeclareLocal(type);
    }
References System.Xml.Xsl.IlGen.GenerateHelper._ilgen, System.Reflection.Emit.ILGenerator.DeclareLocal(), and System.type.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.CreateAggregator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateContainerIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateFilteredIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSetIterator(), System.Xml.Xsl.IlGen.XmlILVisitor.CreateSimpleIterator(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureLocal(), System.Xml.Xsl.IlGen.IteratorDescriptor.EnsureNoCache(), System.Xml.Xsl.IlGen.GenerateHelper.EnsureWriter(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.Sequence(), System.Xml.Xsl.IlGen.XmlILVisitor.StartForBinding(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDataSource(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitDeref(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitParent(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRoot(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSort(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitStrConcat(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeLateBound().