Terraria: System.Xml.Xsl.IlGen.GenerateHelper.ConstructLiteralDecimal
ConstructLiteralDecimal()
void System.Xml.Xsl.IlGen.GenerateHelper.ConstructLiteralDecimal (decimal dec) inline
Definition at line 272 of file GenerateHelper.cs.
    {
        if (dec >= -2147483648m && dec <= 2147483647m && decimal.Truncate(dec) == dec)
        {
            LoadInteger((int)dec);
            Construct(XmlILConstructors.DecFromInt32);
            return;
        }
        int[] bits = decimal.GetBits(dec);
        LoadInteger(bits[0]);
        LoadInteger(bits[1]);
        LoadInteger(bits[2]);
        LoadBoolean(bits[3] < 0);
        LoadInteger(bits[3] >> 16);
        Construct(XmlILConstructors.DecFromParts);
    }
References System.Xml.Xsl.IlGen.GenerateHelper.Construct(), System.Xml.Xsl.IlGen.XmlILConstructors.DecFromInt32, System.Xml.Xsl.IlGen.XmlILConstructors.DecFromParts, System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.LoadBoolean(), and System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger().
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.VisitLiteralDecimal().