Terraria: System.Xml.Xsl.IlGen.GenerateHelper.BranchAndMark
BranchAndMark()
void System.Xml.Xsl.IlGen.GenerateHelper.BranchAndMark (Label lblBranch, Label lblMark) inline
Definition at line 155 of file GenerateHelper.cs.
    {
        if (!lblBranch.Equals(lblMark))
        {
            EmitUnconditionalBranch(OpCodes.Br, lblBranch);
        }
        MarkLabel(lblMark);
    }
References System.Reflection.Emit.OpCodes.Br, System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), and System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel().
Referenced by System.Xml.Xsl.IlGen.IteratorDescriptor.LoopToEnd().