Terraria: System.Xml.Xsl.IlGen.GenerateHelper.TreatAs
TreatAs()
void System.Xml.Xsl.IlGen.GenerateHelper.TreatAs (Type clrTypeSrc, Type clrTypeDst) inline
Definition at line 252 of file GenerateHelper.cs.
    {
        if (!(clrTypeSrc == clrTypeDst))
        {
            if (clrTypeSrc.IsValueType)
            {
                Emit(OpCodes.Box, clrTypeSrc);
            }
            else if (clrTypeDst.IsValueType)
            {
                Emit(OpCodes.Unbox, clrTypeDst);
                Emit(OpCodes.Ldobj, clrTypeDst);
            }
            else if (clrTypeDst != typeof(object))
            {
                Emit(OpCodes.Castclass, clrTypeDst);
            }
        }
    }
References System.Reflection.Emit.OpCodes.Box, System.Reflection.Emit.OpCodes.Castclass, System.Xml.Dictionary, System.Reflection.Emit.OpCodes.Ldobj, and System.Reflection.Emit.OpCodes.Unbox.
Referenced by System.Xml.Xsl.IlGen.GenerateHelper.CallGetEarlyBoundObject(), System.Xml.Xsl.IlGen.GenerateHelper.CallGetGlobalValue(), System.Xml.Xsl.IlGen.GenerateHelper.CallSetGlobalValue(), System.Xml.Xsl.IlGen.GenerateHelper.CallValueAs(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitXsltInvokeEarlyBound().