Terraria: TrackedProjectileReference.TryReading
TryReading()
void TrackedProjectileReference.TryReading (BinaryReader reader) inline
     {
         int num = reader.ReadInt16();
         if (num == -1)
         {
             Clear();
             return;
         }
         int expectedIdentity = reader.ReadInt16();
         int expectedType = reader.ReadInt16();
         Projectile projectile = FindMatchingProjectile(num, expectedIdentity, expectedType);
         if (projectile == null)
         {
             Clear();
         }
         else
         {
             Set(projectile);
         }
     }
References Clear(), FindMatchingProjectile(), and Set().
Referenced by MessageBuffer.GetData().