Terraria: FancyGolfPredictionLine.Draw
Draw()
void FancyGolfPredictionLine.Draw (Camera camera, SpriteBatch spriteBatch, float chargeProgress) inline
     {
         _drawer.Begin(camera.GameViewMatrix.TransformationMatrix);
         _ = _positions.Count;
         Texture2D value = TextureAssets.Extra[33].Value;
         Vector2 vector = new Vector2(3.5f, 3.5f);
         Vector2 origin = value.Size() / 2f;
         Vector2 vector2 = vector - camera.UnscaledPosition;
         float num = 0f;
         float num2 = 0f;
         for (int i = 0; i < _positions.Count - 1; i++)
         {
             GetSectionLength(i, out var length, out var _);
             if (length != 0f)
             {
                 for (; num < num2 + length; num += 4f)
                 {
                     float num3 = (num - num2) / length + (float)i;
                     Vector2 position = GetPosition((num - num2) / length + (float)i);
                     Color color = GetColor2(num3);
                     color *= MathHelper.Clamp(2f - 2f * num3 / (float)(_positions.Count - 1), 0f, 1f);
                     spriteBatch.Draw(value, position + vector2, null, color, 0f, origin, GetScale(num), SpriteEffects.None, 0f);
                 }
                 num2 += length;
             }
         }
         _drawer.End();
     }
References _drawer, _positions, BasicDebugDrawer.Begin(), Color, BasicDebugDrawer.End(), TextureAssets.Extra, Camera.GameViewMatrix, GetColor2(), GetPosition(), GetScale(), GetSectionLength(), SpriteViewMatrix.TransformationMatrix, Camera.UnscaledPosition, and Asset< T >.Value.
Referenced by GolfHelper.DrawPredictionLine().