Terraria: FancyGolfPredictionLine.Update
Update()
void FancyGolfPredictionLine.Update (Entity golfBall, Vector2 impactVelocity, float roughLandResistance) inline
     {
         bool flag = Main.tileSolid[379];
         Main.tileSolid[379] = false;
         _positions.Clear();
         _time += 1f / 60f;
         _entity.position = golfBall.position;
         _entity.width = golfBall.width;
         _entity.height = golfBall.height;
         GolfHelper.HitGolfBall(_entity, impactVelocity, roughLandResistance);
         _positions.Add(_entity.position);
         float angularVelocity = 0f;
         for (int i = 0; i < _iterations; i++)
         {
             GolfHelper.StepGolfBall(_entity, ref angularVelocity);
             _positions.Add(_entity.position);
         }
         Main.tileSolid[379] = flag;
     }
References _entity, _iterations, _positions, _time, Entity.height, GolfHelper.HitGolfBall(), Entity.position, GolfHelper.StepGolfBall(), Main.tileSolid, and Entity.width.
Referenced by GolfHelper.DrawPredictionLine().