Terraria: System.Security.Principal.IdentityReferenceCollection.Translate
Translate() [1/2]
IdentityReferenceCollection System.Security.Principal.IdentityReferenceCollection.Translate (Type targetType) inline
Definition at line 93 of file IdentityReferenceCollection.cs.
    {
        return Translate(targetType, forceSuccess: false);
    }
References System.Security.Principal.IdentityReferenceCollection.Translate().
Referenced by System.Security.AccessControl.DirectoryObjectSecurity.GetRules(), System.Security.AccessControl.CommonObjectSecurity.GetRules(), and System.Security.Principal.IdentityReferenceCollection.Translate().