Terraria: System.StubHelpers.VBByValStrMarshaler.ConvertToNative
ConvertToNative()
static unsafe IntPtr System.StubHelpers.VBByValStrMarshaler.ConvertToNative (string strManaged, bool fBestFit, bool fThrowOnUnmappableChar, ref int cch) inline static package
Definition at line 7 of file VBByValStrMarshaler.cs.
    {
        if (strManaged == null)
        {
            return IntPtr.Zero;
        }
        cch = strManaged.Length;
        int cb = checked(4 + (cch + 1) * Marshal.SystemMaxDBCSCharSize);
        byte* ptr = (byte*)(void*)Marshal.AllocCoTaskMem(cb);
        int* ptr2 = (int*)ptr;
        ptr += 4;
        if (cch == 0)
        {
            *ptr = 0;
            *ptr2 = 0;
        }
        else
        {
            int cbLength;
            byte[] array = AnsiCharMarshaler.DoAnsiConversion(strManaged, fBestFit, fThrowOnUnmappableChar, out cbLength);
            Buffer.Memmove(ref *ptr, ref MemoryMarshal.GetArrayDataReference(array), (nuint)cbLength);
            ptr[cbLength] = 0;
            *ptr2 = cbLength;
        }
        return new IntPtr(ptr);
    }
References System.Runtime.InteropServices.Marshal.AllocCoTaskMem(), System.array, System.StubHelpers.AnsiCharMarshaler.DoAnsiConversion(), System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.Buffer.Memmove(), System.Runtime.InteropServices.Marshal.SystemMaxDBCSCharSize, and System.IntPtr.Zero.