Terraria: LegacyLighting.ProcessArea
ProcessArea()
void LegacyLighting.ProcessArea (Rectangle area) inline
Implements ILightingEngine.
     {
         _oldSkyColor = _skyColor;
         float num = (float)(int)Main.tileColor.R / 255f;
         float num2 = (float)(int)Main.tileColor.G / 255f;
         float num3 = (float)(int)Main.tileColor.B / 255f;
         _skyColor = (num + num2 + num3) / 3f;
         if (IsColorOrWhiteMode)
         {
             _offScreenTiles2 = 34;
             Lighting.OffScreenTiles = 40;
         }
         else
         {
             _offScreenTiles2 = 18;
             Lighting.OffScreenTiles = 23;
         }
         _requestedRectLeft = area.Left;
         _requestedRectRight = area.Right;
         _requestedRectTop = area.Top;
         _requestedRectBottom = area.Bottom;
         _expandedRectLeft = _requestedRectLeft - Lighting.OffScreenTiles;
         _expandedRectTop = _requestedRectTop - Lighting.OffScreenTiles;
         _expandedRectRight = _requestedRectRight + Lighting.OffScreenTiles;
         _expandedRectBottom = _requestedRectBottom + Lighting.OffScreenTiles;
         Main.renderCount++;
         int maxLightArrayX = (int)_camera.UnscaledSize.X / 16 + Lighting.OffScreenTiles * 2;
         int maxLightArrayY = (int)_camera.UnscaledSize.Y / 16 + Lighting.OffScreenTiles * 2;
         if (Main.renderCount < 3)
         {
             DoColors();
         }
         if (Main.renderCount == 2)
         {
             CopyFullyProcessedDataOver(maxLightArrayX, maxLightArrayY);
         }
         else if (!Main.renderNow)
         {
             ShiftUnProcessedDataOver(maxLightArrayX, maxLightArrayY);
             if (Netplay.Connection.StatusMax > 0)
             {
                 Main.mapTime = 1;
             }
             if (Main.mapDelay > 0)
             {
                 Main.mapDelay--;
             }
             else if (Main.mapTime == 0 && Main.mapEnabled && Main.renderCount == 3)
             {
                 try
                 {
                     TryUpdatingMapWithLight();
                 }
                 catch
                 {
                 }
             }
             if (_oldSkyColor != _skyColor)
             {
                 UpdateLightToSkyColor(num, num2, num3);
             }
         }
         if (Main.renderCount > RenderPhases)
         {
             PreRenderPhase();
         }
     }
References _camera, _expandedRectBottom, _expandedRectLeft, _expandedRectRight, _expandedRectTop, _offScreenTiles2, _oldSkyColor, _requestedRectBottom, _requestedRectLeft, _requestedRectRight, _requestedRectTop, _skyColor, Netplay.Connection, CopyFullyProcessedDataOver(), DoColors(), IsColorOrWhiteMode, Main.mapDelay, Main.mapEnabled, Main.mapTime, Lighting.OffScreenTiles, PreRenderPhase(), Main.renderCount, Main.renderNow, RenderPhases, ShiftUnProcessedDataOver(), RemoteServer.StatusMax, Main.tileColor, TryUpdatingMapWithLight(), Camera.UnscaledSize, and UpdateLightToSkyColor().