Terraria: LegacyLighting.DoColors
DoColors()
void LegacyLighting.DoColors () inline private
     {
         //IL_09bf: Unknown result type (might be due to invalid IL or missing references)
         //IL_09c6: Expected O, but got Unknown
         //IL_09cf: Unknown result type (might be due to invalid IL or missing references)
         //IL_09d6: Expected O, but got Unknown
         //IL_09df: Unknown result type (might be due to invalid IL or missing references)
         //IL_09e6: Expected O, but got Unknown
         //IL_09ef: Unknown result type (might be due to invalid IL or missing references)
         //IL_09f6: Expected O, but got Unknown
         //IL_09ff: Unknown result type (might be due to invalid IL or missing references)
         //IL_0a06: Expected O, but got Unknown
         if (IsColorOrWhiteMode)
         {
             _blueWave += (float)_blueDir * 0.0001f;
             if (_blueWave > 1f)
             {
                 _blueWave = 1f;
                 _blueDir = -1;
             }
             else if (_blueWave < 0.97f)
             {
                 _blueWave = 0.97f;
                 _blueDir = 1;
             }
             if (_rgb)
             {
                 _negLight = 0.91f;
                 _negLight2 = 0.56f;
                 _honeyLightG = 0.7f * _negLight * _blueWave;
                 _honeyLightR = 0.75f * _negLight * _blueWave;
                 _honeyLightB = 0.6f * _negLight * _blueWave;
                 switch (Main.waterStyle)
                 {
                 case 0:
                 case 1:
                 case 7:
                 case 8:
                     _wetLightG = 0.96f * _negLight * _blueWave;
                     _wetLightR = 0.88f * _negLight * _blueWave;
                     _wetLightB = 1.015f * _negLight * _blueWave;
                     break;
                 case 2:
                     _wetLightG = 0.85f * _negLight * _blueWave;
                     _wetLightR = 0.94f * _negLight * _blueWave;
                     _wetLightB = 1.01f * _negLight * _blueWave;
                     break;
                 case 3:
                     _wetLightG = 0.95f * _negLight * _blueWave;
                     _wetLightR = 0.84f * _negLight * _blueWave;
                     _wetLightB = 1.015f * _negLight * _blueWave;
                     break;
                 case 4:
                     _wetLightG = 0.86f * _negLight * _blueWave;
                     _wetLightR = 0.9f * _negLight * _blueWave;
                     _wetLightB = 1.01f * _negLight * _blueWave;
                     break;
                 case 5:
                     _wetLightG = 0.99f * _negLight * _blueWave;
                     _wetLightR = 0.84f * _negLight * _blueWave;
                     _wetLightB = 1.01f * _negLight * _blueWave;
                     break;
                 case 6:
                     _wetLightR = 0.83f * _negLight * _blueWave;
                     _wetLightG = 0.93f * _negLight * _blueWave;
                     _wetLightB = 0.98f * _negLight * _blueWave;
                     break;
                 case 9:
                     _wetLightG = 0.88f * _negLight * _blueWave;
                     _wetLightR = 1f * _negLight * _blueWave;
                     _wetLightB = 0.84f * _negLight * _blueWave;
                     break;
                 case 10:
                     _wetLightG = 1f * _negLight * _blueWave;
                     _wetLightR = 0.83f * _negLight * _blueWave;
                     _wetLightB = 1f * _negLight * _blueWave;
                     break;
                 case 12:
                     _wetLightG = 0.98f * _negLight * _blueWave;
                     _wetLightR = 0.95f * _negLight * _blueWave;
                     _wetLightB = 0.85f * _negLight * _blueWave;
                     break;
                 default:
                     _wetLightG = 0f;
                     _wetLightR = 0f;
                     _wetLightB = 0f;
                     break;
                 }
             }
             else
             {
                 _negLight = 0.9f;
                 _negLight2 = 0.54f;
                 _wetLightR = 0.95f * _negLight * _blueWave;
             }
             if (Main.player[Main.myPlayer].nightVision)
             {
                 _negLight *= 1.03f;
                 _negLight2 *= 1.03f;
             }
             if (Main.player[Main.myPlayer].blind)
             {
                 _negLight *= 0.95f;
                 _negLight2 *= 0.95f;
             }
             if (Main.player[Main.myPlayer].blackout)
             {
                 _negLight *= 0.85f;
                 _negLight2 *= 0.85f;
             }
             if (Main.player[Main.myPlayer].headcovered)
             {
                 _negLight *= 0.85f;
                 _negLight2 *= 0.85f;
             }
         }
         else
         {
             _negLight = 0.04f;
             _negLight2 = 0.16f;
             if (Main.player[Main.myPlayer].nightVision)
             {
                 _negLight -= 0.013f;
                 _negLight2 -= 0.04f;
             }
             if (Main.player[Main.myPlayer].blind)
             {
                 _negLight += 0.03f;
                 _negLight2 += 0.06f;
             }
             if (Main.player[Main.myPlayer].blackout)
             {
                 _negLight += 0.09f;
                 _negLight2 += 0.18f;
             }
             if (Main.player[Main.myPlayer].headcovered)
             {
                 _negLight += 0.09f;
                 _negLight2 += 0.18f;
             }
             _wetLightR = _negLight * 1.2f;
             _wetLightG = _negLight * 1.1f;
         }
         int num;
         int num2;
         switch (Main.renderCount)
         {
         case 0:
             num = 0;
             num2 = 1;
             break;
         case 1:
             num = 1;
             num2 = 3;
             break;
         case 2:
             num = 3;
             num2 = 4;
             break;
         default:
             num = 0;
             num2 = 0;
             break;
         }
         Stopwatch stopwatch = new Stopwatch();
         int left = _expandedArea.Left;
         int top = _expandedArea.Top;
         for (int i = num; i < num2; i++)
         {
             stopwatch.Restart();
             int num3 = 0;
             int num4 = 0;
             switch (i)
             {
             case 0:
                 _swipe.InnerLoop1Start = _minBoundArea.Top - top;
                 _swipe.InnerLoop2Start = _minBoundArea.Bottom - top;
                 _swipe.InnerLoop1End = _requestedArea.Bottom + RenderPhases - top;
                 _swipe.InnerLoop2End = _requestedArea.Top - RenderPhases - top;
                 num3 = _minBoundArea.Left - left;
                 num4 = _minBoundArea.Right - left;
                 _swipe.JaggedArray = _states;
                 break;
             case 1:
                 _swipe.InnerLoop1Start = _expandedArea.Left - left;
                 _swipe.InnerLoop2Start = _expandedArea.Right - left;
                 _swipe.InnerLoop1End = _requestedArea.Right + RenderPhases - left;
                 _swipe.InnerLoop2End = _requestedArea.Left - RenderPhases - left;
                 num3 = _expandedArea.Top - top;
                 num4 = _expandedArea.Bottom - top;
                 _swipe.JaggedArray = _axisFlipStates;
                 break;
             case 2:
                 _swipe.InnerLoop1Start = _offScreenTiles2ExpandedArea.Top - top;
                 _swipe.InnerLoop2Start = _offScreenTiles2ExpandedArea.Bottom - top;
                 _swipe.InnerLoop1End = _requestedArea.Bottom + RenderPhases - top;
                 _swipe.InnerLoop2End = _requestedArea.Top - RenderPhases - top;
                 num3 = _offScreenTiles2ExpandedArea.Left - left;
                 num4 = _offScreenTiles2ExpandedArea.Right - left;
                 _swipe.JaggedArray = _states;
                 break;
             case 3:
                 _swipe.InnerLoop1Start = _offScreenTiles2ExpandedArea.Left - left;
                 _swipe.InnerLoop2Start = _offScreenTiles2ExpandedArea.Right - left;
                 _swipe.InnerLoop1End = _requestedArea.Right + RenderPhases - left;
                 _swipe.InnerLoop2End = _requestedArea.Left - RenderPhases - left;
                 num3 = _offScreenTiles2ExpandedArea.Top - top;
                 num4 = _offScreenTiles2ExpandedArea.Bottom - top;
                 _swipe.JaggedArray = _axisFlipStates;
                 break;
             }
             if (_swipe.InnerLoop1Start > _swipe.InnerLoop1End)
             {
                 _swipe.InnerLoop1Start = _swipe.InnerLoop1End;
             }
             if (_swipe.InnerLoop2Start < _swipe.InnerLoop2End)
             {
                 _swipe.InnerLoop2Start = _swipe.InnerLoop2End;
             }
             if (num3 > num4)
             {
                 num3 = num4;
             }
             FastParallel.For(num3, num4, (ParallelForAction)(Mode switch
             {
                 0 => (object)new ParallelForAction(doColors_Mode0_Swipe),
                 1 => (object)new ParallelForAction(doColors_Mode1_Swipe),
                 2 => (object)new ParallelForAction(doColors_Mode2_Swipe),
                 3 => (object)new ParallelForAction(doColors_Mode3_Swipe),
                 _ => (object)new ParallelForAction(doColors_Mode0_Swipe),
             }), (object)_swipe);
             _swipeRandom.NextSeed();
             TimeLogger.LightingTime(i + 1, stopwatch.Elapsed.TotalMilliseconds);
         }
     }
References _axisFlipStates, _blueDir, _blueWave, _expandedArea, _honeyLightB, _honeyLightG, _honeyLightR, _minBoundArea, _negLight, _negLight2, _offScreenTiles2ExpandedArea, _requestedArea, _rgb, _states, _swipe, _swipeRandom, _wetLightB, _wetLightG, _wetLightR, Player.blackout, Player.blind, LegacyLighting.RectArea.Bottom, doColors_Mode0_Swipe(), doColors_Mode1_Swipe(), doColors_Mode2_Swipe(), doColors_Mode3_Swipe(), FastParallel.For(), Player.headcovered, LegacyLighting.LightingSwipeData.InnerLoop1End, LegacyLighting.LightingSwipeData.InnerLoop1Start, LegacyLighting.LightingSwipeData.InnerLoop2End, LegacyLighting.LightingSwipeData.InnerLoop2Start, IsColorOrWhiteMode, LegacyLighting.LightingSwipeData.JaggedArray, LegacyLighting.RectArea.Left, TimeLogger.LightingTime(), Mode, Main.myPlayer, FastRandom.NextSeed(), Player.nightVision, ParallelForAction(), Main.player, Main.renderCount, RenderPhases, LegacyLighting.RectArea.Right, LegacyLighting.RectArea.Top, and Main.waterStyle.
Referenced by PreRenderPhase(), and ProcessArea().