Terraria: LegacyLighting.doColors_Mode1_Swipe
doColors_Mode1_Swipe()
void LegacyLighting.doColors_Mode1_Swipe (int outerLoopStart, int outerLoopEnd, object context) inline private
     {
         LightingSwipeData lightingSwipeData = context as LightingSwipeData;
         FastRandom fastRandom = default(FastRandom);
         try
         {
             bool flag = true;
             while (true)
             {
                 int num;
                 int num2;
                 int num3;
                 if (flag)
                 {
                     num = 1;
                     num2 = lightingSwipeData.InnerLoop1Start;
                     num3 = lightingSwipeData.InnerLoop1End;
                 }
                 else
                 {
                     num = -1;
                     num2 = lightingSwipeData.InnerLoop2Start;
                     num3 = lightingSwipeData.InnerLoop2End;
                 }
                 for (int i = outerLoopStart; i < outerLoopEnd; i++)
                 {
                     LightingState[] array = lightingSwipeData.JaggedArray[i];
                     float num4 = 0f;
                     for (int j = num2; j != num3; j += num)
                     {
                         LightingState lightingState = array[j];
                         if (lightingState.R2 > num4)
{
                             num4 = lightingState.R2;
                         }
                         else
{
                             if ((double)num4 <= 0.0185)
{
                                 continue;
                             }
                             if (lightingState.R2 < num4)
{
                                 lightingState.R2 = num4;
                             }
                         }
                         if (!(array[j + num].R2 > num4))
{
                             if (lightingState.StopLight)
{
                                 num4 *= _negLight2;
                             }
                             else if (lightingState.WetLight)
{
                                 fastRandom = _swipeRandom.WithModifier((ulong)(i * 1000 + j));
                                 num4 = ((!lightingState.HoneyLight) ? (num4 * (_wetLightR * (float)fastRandom.Next(98, 100) * 0.01f)) : (num4 * (_honeyLightR * (float)fastRandom.Next(98, 100) * 0.01f)));
                             }
                             else
{
                                 num4 *= _negLight;
                             }
                         }
                     }
                 }
                 if (flag)
                 {
                     flag = false;
                     continue;
                 }
                 break;
             }
         }
         catch
         {
         }
     }
References _honeyLightR, _negLight, _negLight2, _swipeRandom, _wetLightR, LegacyLighting.LightingState.HoneyLight, LegacyLighting.LightingSwipeData.InnerLoop1End, LegacyLighting.LightingSwipeData.InnerLoop1Start, LegacyLighting.LightingSwipeData.InnerLoop2End, LegacyLighting.LightingSwipeData.InnerLoop2Start, LegacyLighting.LightingSwipeData.JaggedArray, FastRandom.Next(), LegacyLighting.LightingState.R2, LegacyLighting.LightingState.StopLight, LegacyLighting.LightingState.WetLight, and FastRandom.WithModifier().
Referenced by DoColors().