Terraria: LegacyLighting.TryUpdatingMapWithLight
TryUpdatingMapWithLight()
void LegacyLighting.TryUpdatingMapWithLight () inline private
     {
         Main.mapTime = Main.mapTimeMax;
         Main.updateMap = true;
         int num = 40;
         Vector2 unscaledPosition = _camera.UnscaledPosition;
         float x = _camera.UnscaledSize.X;
         float y = _camera.UnscaledSize.Y;
         x = (int)(x / Main.GameViewMatrix.Zoom.X);
         y = (int)(y / Main.GameViewMatrix.Zoom.Y);
         Vector2 vector = unscaledPosition + Main.GameViewMatrix.Translation;
         int value = (int)Math.Floor(vector.X / 16f);
         int value2 = (int)Math.Floor((vector.X + x) / 16f) + 1;
         int value3 = (int)Math.Floor(vector.Y / 16f);
         int value4 = (int)Math.Floor((vector.Y + y) / 16f) + 1;
         value = Utils.Clamp(value, Lighting.OffScreenTiles, Main.maxTilesX - Lighting.OffScreenTiles);
         value2 = Utils.Clamp(value2, Lighting.OffScreenTiles, Main.maxTilesX - Lighting.OffScreenTiles);
         value3 = Utils.Clamp(value3, Lighting.OffScreenTiles, Main.maxTilesY - Lighting.OffScreenTiles);
         value4 = Utils.Clamp(value4, Lighting.OffScreenTiles, Main.maxTilesY - Lighting.OffScreenTiles);
         Main.mapMinX = Utils.Clamp(_requestedRectLeft, num, Main.maxTilesX - num);
         Main.mapMaxX = Utils.Clamp(_requestedRectRight, num, Main.maxTilesX - num);
         Main.mapMinY = Utils.Clamp(_requestedRectTop, num, Main.maxTilesY - num);
         Main.mapMaxY = Utils.Clamp(_requestedRectBottom, num, Main.maxTilesY - num);
         Main.mapMinX = Utils.Clamp(Main.mapMinX, value, value2);
         Main.mapMaxX = Utils.Clamp(Main.mapMaxX, value, value2);
         Main.mapMinY = Utils.Clamp(Main.mapMinY, value3, value4);
         Main.mapMaxY = Utils.Clamp(Main.mapMaxY, value3, value4);
         int offScreenTiles = Lighting.OffScreenTiles;
         for (int i = Main.mapMinX; i < Main.mapMaxX; i++)
         {
             LightingState[] array = _states[i - _requestedRectLeft + offScreenTiles];
             for (int j = Main.mapMinY; j < Main.mapMaxY; j++)
             {
                 LightingState lightingState = array[j - _requestedRectTop + offScreenTiles];
                 Tile tile = Main.tile[i, j];
                 float num2 = 0f;
                 if (lightingState.R > num2)
                 {
                     num2 = lightingState.R;
                 }
                 if (lightingState.G > num2)
                 {
                     num2 = lightingState.G;
                 }
                 if (lightingState.B > num2)
                 {
                     num2 = lightingState.B;
                 }
                 if (IsColorOrWhiteMode)
                 {
                     num2 *= 1.5f;
                 }
                 byte b = (byte)Math.Min(255f, num2 * 255f);
                 if ((double)j < Main.worldSurface && !tile.active() && tile.wall == 0 && tile.liquid == 0)
                 {
                     b = 22;
                 }
                 if (b > 18 || Main.Map[i, j].Light > 0)
                 {
                     if (b < 22)
                     {
                         b = 22;
                     }
                     Main.Map.UpdateLighting(i, j, b);
                 }
             }
         }
     }
References _camera, _requestedRectBottom, _requestedRectLeft, _requestedRectRight, _requestedRectTop, _states, Tile.active(), LegacyLighting.LightingState.B, LegacyLighting.LightingState.G, Main.GameViewMatrix, IsColorOrWhiteMode, Tile.liquid, Main.Map, Main.mapMaxX, Main.mapMaxY, Main.mapMinX, Main.mapMinY, Main.mapTime, Main.mapTimeMax, Main.maxTilesX, Main.maxTilesY, Lighting.OffScreenTiles, LegacyLighting.LightingState.R, Main.tile, SpriteViewMatrix.Translation, Camera.UnscaledPosition, Camera.UnscaledSize, WorldMap.UpdateLighting(), Main.updateMap, Tile.wall, Main.worldSurface, and SpriteViewMatrix.Zoom.
Referenced by ProcessArea().