Terraria: AmbientSky.FadingSkyEntity.Update
Update()
override void AmbientSky.FadingSkyEntity.Update (int frameCount) inline virtual inherited
Implements AmbientSky.SkyEntity.
Reimplemented in AmbientSky.AirBalloonSkyEntity, AmbientSky.AirshipSkyEntity, AmbientSky.BatsGroupSkyEntity, AmbientSky.HellBatsGoupSkyEntity, AmbientSky.SlimeBalloonGroupSkyEntity, AmbientSky.GastropodGroupSkyEntity, AmbientSky.SeagullsGroupSkyEntity, AmbientSky.BirdsPackSkyEntity, AmbientSky.PixiePosseSkyEntity, AmbientSky.VultureSkyEntity, AmbientSky.PegasusSkyEntity, AmbientSky.LostKiteSkyEntity, and AmbientSky.ButterfliesSkyEntity.
         {
             if (!IsMovementDone(frameCount))
             {
                 UpdateOpacity(frameCount);
                 if ((frameCount + FrameOffset) % FramingSpeed == 0)
                 {
                     NextFrame();
                 }
                 UpdateVelocity(frameCount);
                 Position += Velocity;
             }
         }
References AmbientSky.FadingSkyEntity.FrameOffset, AmbientSky.FadingSkyEntity.FramingSpeed, AmbientSky.FadingSkyEntity.IsMovementDone(), AmbientSky.SkyEntity.NextFrame(), AmbientSky.SkyEntity.Position, AmbientSky.FadingSkyEntity.UpdateOpacity(), AmbientSky.FadingSkyEntity.UpdateVelocity(), and AmbientSky.FadingSkyEntity.Velocity.