Terraria: MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack
AlreadyLeadsIntoWantedTrack()
bool MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack (Point tileCoordsOfFrontWheel, Point tileCoordsWeWantToReach) inline private
     {
         Tile tileSafely = Framing.GetTileSafely(tileCoordsOfFrontWheel);
         Tile tileSafely2 = Framing.GetTileSafely(tileCoordsWeWantToReach);
         if (!tileSafely.active() || tileSafely.type != 314)
         {
             return false;
         }
         if (!tileSafely2.active() || tileSafely2.type != 314)
         {
             return false;
         }
         GetExpectedDirections(tileCoordsOfFrontWheel, tileCoordsWeWantToReach, out var expectedStartLeft, out var expectedStartRight, out var expectedEndLeft, out var expectedEndRight);
         if (!Minecart.GetAreExpectationsForSidesMet(tileCoordsOfFrontWheel, expectedStartLeft, expectedStartRight))
         {
             return false;
         }
         if (!Minecart.GetAreExpectationsForSidesMet(tileCoordsWeWantToReach, expectedEndLeft, expectedEndRight))
         {
             return false;
         }
         return true;
     }
References Tile.active(), Minecart.GetAreExpectationsForSidesMet(), GetExpectedDirections(), Framing.GetTileSafely(), and Tile.type.
Referenced by DoTheTracksConnectProperly(), and TryDigging().