Terraria: System.Net.Mail.SmtpCommands.CRLF
CRLF
readonly byte [] System.Net.Mail.SmtpCommands.CRLF = Encoding.ASCII.GetBytes("\r\n") static package
Definition at line 9 of file SmtpCommands.cs.
Referenced by System.Net.Mail.StartTlsCommand.PrepareCommand(), System.Net.Mail.MailCommand.PrepareCommand(), System.Net.Mail.EHelloCommand.PrepareCommand(), System.Net.Mail.HelloCommand.PrepareCommand(), System.Net.Mail.AuthCommand.PrepareCommand(), System.Net.Mail.RecipientCommand.PrepareCommand(), and System.Net.Mail.AuthCommand.PrepareCommand().