Terraria: System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes
CompileAttributes()
void System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes (Compiler compiler) inline inherited
Definition at line 14 of file CompiledAction.cs.
    {
        NavigatorInput input = compiler.Input;
        string localName = input.LocalName;
        if (!input.MoveToFirstAttribute())
        {
            return;
        }
        do
        {
            if (input.NamespaceURI.Length != 0)
            {
                continue;
            }
            try
            {
                if (!CompileAttribute(compiler))
                {
                    throw XsltException.Create(System.SR.Xslt_InvalidAttribute, input.LocalName, localName);
                }
            }
            catch
            {
                if (!compiler.ForwardCompatibility)
                {
                    throw;
                }
            }
        }
        while (input.MoveToNextAttribute());
        input.ToParent();
    }
References System.Xml.Xsl.XsltOld.CompiledAction.CompileAttribute(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.input, System.Xml.Xsl.XsltOld.NavigatorInput.LocalName, and System.SR.Xslt_InvalidAttribute.
Referenced by System.Xml.Xsl.XsltOld.ApplyTemplatesAction.Compile(), System.Xml.Xsl.XsltOld.AttributeAction.Compile(), System.Xml.Xsl.XsltOld.AttributeSetAction.Compile(), System.Xml.Xsl.XsltOld.CallTemplateAction.Compile(), System.Xml.Xsl.XsltOld.ChooseAction.Compile(), System.Xml.Xsl.XsltOld.CommentAction.Compile(), System.Xml.Xsl.XsltOld.CopyAction.Compile(), System.Xml.Xsl.XsltOld.CopyOfAction.Compile(), System.Xml.Xsl.XsltOld.ElementAction.Compile(), System.Xml.Xsl.XsltOld.ForEachAction.Compile(), System.Xml.Xsl.XsltOld.IfAction.Compile(), System.Xml.Xsl.XsltOld.MessageAction.Compile(), System.Xml.Xsl.XsltOld.NumberAction.Compile(), System.Xml.Xsl.XsltOld.ProcessingInstructionAction.Compile(), System.Xml.Xsl.XsltOld.SortAction.Compile(), System.Xml.Xsl.XsltOld.TemplateAction.Compile(), System.Xml.Xsl.XsltOld.TextAction.Compile(), System.Xml.Xsl.XsltOld.ValueOfAction.Compile(), System.Xml.Xsl.XsltOld.VariableAction.Compile(), System.Xml.Xsl.XsltOld.WithParamAction.Compile(), and System.Xml.Xsl.XsltOld.XsltOutput.Compile().