Terraria: System.Xml.Xsl.XsltOld.ReaderOutput.Read
Read()
override bool System.Xml.Xsl.XsltOld.ReaderOutput.Read () inline
Definition at line 252 of file ReaderOutput.cs.
    {
        if (_state != ReadState.Interactive)
        {
            if (_state != 0)
            {
                return false;
            }
            _state = ReadState.Interactive;
        }
        while (true)
        {
            if (_haveRecord)
            {
                _processor.ResetOutput();
                _haveRecord = false;
            }
            _processor.Execute();
            if (_haveRecord)
            {
                switch (NodeType)
                {
                case XmlNodeType.Text:
                    if (!XmlCharType.IsOnlyWhitespace(Value))
                    {
                        break;
                    }
                    _currentInfo.NodeType = XmlNodeType.Whitespace;
                    goto IL_0075;
                case XmlNodeType.Whitespace:
                    goto IL_0075;
                }
            }
            else
            {
                _state = ReadState.EndOfFile;
                Reset();
            }
            break;
            IL_0075:
            if (Value.Length != 0)
            {
                if (XmlSpace == XmlSpace.Preserve)
                {
                    _currentInfo.NodeType = XmlNodeType.SignificantWhitespace;
                }
                break;
            }
        }
        return _haveRecord;
    }
References System.Xml.Xsl.XsltOld.ReaderOutput._haveRecord, System.Xml.Xsl.XsltOld.ReaderOutput._processor, System.Xml.Xsl.XsltOld.ReaderOutput._state, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Processor.Execute(), System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.Xsl.XsltOld.ReaderOutput.NodeType, System.Xml.Xsl.XsltOld.ReaderOutput.Reset(), System.Xml.Xsl.XsltOld.Processor.ResetOutput(), and System.Xml.Xsl.XsltOld.ReaderOutput.Value.
Referenced by System.Xml.Xsl.XsltOld.ReaderOutput.ReadInnerXml(), System.Xml.Xsl.XsltOld.ReaderOutput.ReadOuterXml(), and System.Xml.Xsl.XsltOld.ReaderOutput.ReadString().