Terraria: System.Transactions.TransactionStateAborted.CreateTransactionAbortedException
CreateTransactionAbortedException()
TransactionException System.Transactions.TransactionStateAborted.CreateTransactionAbortedException (InternalTransaction tx) inline private
Definition at line 96 of file TransactionStateAborted.cs.
    {
        return TransactionAbortedException.Create(System.SR.TransactionAborted, tx._innerException, tx.DistributedTxId);
    }
References System.Transactions.InternalTransaction._innerException, System.Transactions.TransactionAbortedException.Create(), System.Transactions.InternalTransaction.DistributedTxId, and System.SR.TransactionAborted.
Referenced by System.Transactions.TransactionStateAborted.BeginCommit(), System.Transactions.TransactionStateAborted.CheckForFinishedTransaction(), System.Transactions.TransactionStateAborted.CreateAbortingClone(), System.Transactions.TransactionStateAborted.CreateBlockingClone(), and System.Transactions.TransactionStateAborted.EndCommit().