Terraria: System.Transactions.TransactionStateAborted.EnterState
EnterState()
override void System.Transactions.TransactionStateAborted.EnterState (InternalTransaction tx) inline package
Definition at line 5 of file TransactionStateAborted.cs.
    {
        base.EnterState(tx);
        CommonEnterState(tx);
        for (int i = 0; i < tx._phase0Volatiles._volatileEnlistmentCount; i++)
        {
            tx._phase0Volatiles._volatileEnlistments[i]._twoPhaseState.InternalAborted(tx._phase0Volatiles._volatileEnlistments[i]);
        }
        for (int j = 0; j < tx._phase1Volatiles._volatileEnlistmentCount; j++)
        {
            tx._phase1Volatiles._volatileEnlistments[j]._twoPhaseState.InternalAborted(tx._phase1Volatiles._volatileEnlistments[j]);
        }
        if (tx._durableEnlistment != null)
        {
            tx._durableEnlistment.State.InternalAborted(tx._durableEnlistment);
        }
        TransactionManager.TransactionTable.Remove(tx);
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TransactionTimeout(tx.TransactionTraceId);
        }
        tx.FireCompletion();
        if (tx._asyncCommit)
        {
            tx.SignalAsyncCompletion();
        }
    }
References System.Transactions.InternalTransaction._asyncCommit, System.Transactions.InternalTransaction._durableEnlistment, System.Transactions.InternalTransaction._phase0Volatiles, System.Transactions.InternalTransaction._phase1Volatiles, System.Transactions.InternalEnlistment._twoPhaseState, System.Transactions.VolatileEnlistmentSet._volatileEnlistmentCount, System.Transactions.VolatileEnlistmentSet._volatileEnlistments, System.Transactions.TransactionState.CommonEnterState(), System.Transactions.InternalTransaction.FireCompletion(), System.Transactions.EnlistmentState.InternalAborted(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.InternalTransaction.SignalAsyncCompletion(), System.Transactions.InternalEnlistment.State, System.Transactions.TransactionManager.TransactionTable, System.Transactions.TransactionsEtwProvider.TransactionTimeout(), and System.Transactions.InternalTransaction.TransactionTraceId.