Terraria: System.Runtime.Serialization.ReflectionXmlFormatWriter.ReflectionWriteCollection
ReflectionWriteCollection()
void System.Runtime.Serialization.ReflectionXmlFormatWriter.ReflectionWriteCollection (XmlWriterDelegator xmlWriter, object obj, XmlObjectSerializerWriteContext context, CollectionDataContract collectionDataContract) inline
Definition at line 18 of file ReflectionXmlFormatWriter.cs.
    {
        XmlDictionaryString @namespace = collectionDataContract.Namespace;
        XmlDictionaryString collectionItemName = collectionDataContract.CollectionItemName;
        if (collectionDataContract.ChildElementNamespace != null)
        {
            xmlWriter.WriteNamespaceDecl(collectionDataContract.ChildElementNamespace);
        }
        if (collectionDataContract.Kind == CollectionKind.Array)
        {
            context.IncrementArrayCount(xmlWriter, (Array)obj);
            Type itemType = collectionDataContract.ItemType;
            if (!ReflectionTryWritePrimitiveArray(xmlWriter, obj, collectionDataContract.UnderlyingType, itemType, collectionItemName, @namespace))
            {
                Array array = (Array)obj;
                PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(itemType);
                for (int i = 0; i < array.Length; i++)
                {
                    _reflectionClassWriter.ReflectionWriteStartElement(xmlWriter, itemType, @namespace, @namespace.Value, collectionItemName.Value, 0);
                    _reflectionClassWriter.ReflectionWriteValue(xmlWriter, context, itemType, array.GetValue(i), writeXsiType: false, primitiveDataContract);
                    _reflectionClassWriter.ReflectionWriteEndElement(xmlWriter);
                }
            }
            return;
        }
        collectionDataContract.IncrementCollectionCount(xmlWriter, obj, context);
        IEnumerator enumeratorForCollection = collectionDataContract.GetEnumeratorForCollection(obj);
        PrimitiveDataContract primitiveDataContract2 = PrimitiveDataContract.GetPrimitiveDataContract(collectionDataContract.UnderlyingType);
        if (primitiveDataContract2 != null && primitiveDataContract2.UnderlyingType != Globals.TypeOfObject)
        {
            while (enumeratorForCollection.MoveNext())
            {
                object current = enumeratorForCollection.Current;
                context.IncrementItemCount(1);
                primitiveDataContract2.WriteXmlElement(xmlWriter, current, context, collectionItemName, @namespace);
            }
            return;
        }
        Type collectionElementType = collectionDataContract.GetCollectionElementType();
        bool flag = collectionDataContract.Kind == CollectionKind.Dictionary || collectionDataContract.Kind == CollectionKind.GenericDictionary;
        while (enumeratorForCollection.MoveNext())
        {
            object current2 = enumeratorForCollection.Current;
            context.IncrementItemCount(1);
            _reflectionClassWriter.ReflectionWriteStartElement(xmlWriter, collectionElementType, @namespace, @namespace.Value, collectionItemName.Value, 0);
            if (flag)
            {
                collectionDataContract.ItemContract.WriteXmlValue(xmlWriter, current2, context);
            }
            else
            {
                _reflectionClassWriter.ReflectionWriteValue(xmlWriter, context, collectionElementType, current2, writeXsiType: false, null);
            }
            _reflectionClassWriter.ReflectionWriteEndElement(xmlWriter);
        }
    }
References System.array, System.Xml.Array, System.Runtime.Serialization.Dictionary, System.Xml.Dictionary, System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.IncrementArrayCount(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.obj, and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.CreateReflectionXmlFormatCollectionWriterDelegate().