Terraria: System.Data.SortExpressionBuilder.Add
Add()
void System.Data.SortExpressionBuilder< T >.Add (Func< T, object > keySelector, Comparison< object > compare, bool isOrderBy) inline package
Definition at line 17 of file SortExpressionBuilder.cs.
    {
        if (isOrderBy)
        {
            _currentSelector = _selectors.AddFirst(keySelector);
            _currentComparer = _comparers.AddFirst(compare);
        }
        else
        {
            _currentSelector = _selectors.AddAfter(_currentSelector, keySelector);
            _currentComparer = _comparers.AddAfter(_currentComparer, compare);
        }
    }
References System.Data.SortExpressionBuilder< T >._comparers, System.Data.SortExpressionBuilder< T >._currentComparer, System.Data.SortExpressionBuilder< T >._currentSelector, System.Data.SortExpressionBuilder< T >._selectors, System.Collections.Generic.LinkedList< T >.AddAfter(), and System.Collections.Generic.LinkedList< T >.AddFirst().
Referenced by System.Data.EnumerableRowCollection< TRow >.AddSortExpression< TKey >().