Terraria: Microsoft.Xna.Framework.Graphics.SpriteFont.GetIndexForCharacter
GetIndexForCharacter()
int Microsoft.Xna.Framework.Graphics.SpriteFont.GetIndexForCharacter (char character) inline private
Definition at line 277 of file SpriteFont.cs.
    {
        int num = 0;
        int num2 = characterMap.Count - 1;
        while (num <= num2)
        {
            int num3 = num + (num2 - num >> 1);
            char c = characterMap[num3];
            if (c == character)
            {
                return num3;
            }
            if (c < character)
            {
                num = num3 + 1;
            }
            else
            {
                num2 = num3 - 1;
            }
        }
        if (defaultCharacter.HasValue)
        {
            char value = defaultCharacter.Value;
            if (character != value)
            {
                return GetIndexForCharacter(value);
            }
        }
        string message = string.Format(CultureInfo.CurrentCulture, FrameworkResources.CharacterNotInFont, new object[2]
        {
            character,
            (int)character
        });
        throw new ArgumentException(message, "character");
    }
References Microsoft.Xna.Framework.Graphics.SpriteFont.characterMap, Microsoft.Xna.Framework.FrameworkResources.CharacterNotInFont, System.Globalization.CultureInfo.CurrentCulture, Microsoft.Xna.Framework.Graphics.SpriteFont.defaultCharacter, Microsoft.Xna.Framework.Graphics.SpriteFont.GetIndexForCharacter(), and System.value.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteFont.GetIndexForCharacter(), Microsoft.Xna.Framework.Graphics.SpriteFont.InternalDraw(), and Microsoft.Xna.Framework.Graphics.SpriteFont.InternalMeasure().