Terraria: Microsoft.Xna.Framework.Graphics.SpriteFont.InternalMeasure
InternalMeasure()
Vector2 Microsoft.Xna.Framework.Graphics.SpriteFont.InternalMeasure (ref StringProxy text) inline private
Definition at line 152 of file SpriteFont.cs.
    {
        if (text.Length == 0)
        {
            return Vector2.Zero;
        }
        Vector2 zero = Vector2.Zero;
        zero.Y = lineSpacing;
        float val = 0f;
        int num = 0;
        float num2 = 0f;
        bool flag = true;
        for (int i = 0; i < text.Length; i++)
        {
            if (text[i] == '\r')
            {
                continue;
            }
            if (text[i] == '\n')
            {
                zero.X += Math.Max(num2, 0f);
                num2 = 0f;
                val = Math.Max(zero.X, val);
                zero = Vector2.Zero;
                zero.Y = lineSpacing;
                flag = true;
                num++;
                continue;
            }
            Vector3 vector = kerning[GetIndexForCharacter(text[i])];
            if (flag)
            {
                vector.X = Math.Max(vector.X, 0f);
            }
            else
            {
                zero.X += spacing + num2;
            }
            zero.X += vector.X + vector.Y;
            num2 = vector.Z;
            Rectangle rectangle = croppingData[GetIndexForCharacter(text[i])];
            zero.Y = Math.Max(zero.Y, rectangle.Height);
            flag = false;
        }
        zero.X += Math.Max(num2, 0f);
        zero.Y += num * lineSpacing;
        zero.X = Math.Max(zero.X, val);
        return zero;
    }
References Microsoft.Xna.Framework.Graphics.SpriteFont.croppingData, Microsoft.Xna.Framework.Graphics.SpriteFont.GetIndexForCharacter(), Microsoft.Xna.Framework.Graphics.SpriteFont.kerning, Microsoft.Xna.Framework.Graphics.SpriteFont.lineSpacing, System.Math.Max(), Microsoft.Xna.Framework.Graphics.SpriteFont.spacing, System.text, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteFont.InternalDraw(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), and Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString().