Terraria: Microsoft.Xna.Framework.Graphics.SpriteFont.InternalDraw
InternalDraw()
void Microsoft.Xna.Framework.Graphics.SpriteFont.InternalDraw (ref StringProxy text, SpriteBatch spriteBatch, Vector2 textblockPosition, Color color, float rotation, Vector2 origin, ref Vector2 scale, SpriteEffects spriteEffects, float depth) inline package
Definition at line 202 of file SpriteFont.cs.
    {
        Matrix.CreateRotationZ(rotation, out var result);
        Matrix.CreateTranslation((0f - origin.X) * scale.X, (0f - origin.Y) * scale.Y, 0f, out var result2);
        Matrix.Multiply(ref result2, ref result, out result);
        int num = 1;
        float x = 0f;
        Vector2 vector = default(Vector2);
        bool flag = true;
        if ((spriteEffects & SpriteEffects.FlipHorizontally) == SpriteEffects.FlipHorizontally)
        {
            x = InternalMeasure(ref text).X * scale.X;
            num = -1;
        }
        if ((spriteEffects & SpriteEffects.FlipVertically) == SpriteEffects.FlipVertically)
        {
            vector.Y = (InternalMeasure(ref text).Y - (float)lineSpacing) * scale.Y;
        }
        else
        {
            vector.Y = 0f;
        }
        vector.X = x;
        for (int i = 0; i < text.Length; i++)
        {
            char c = text[i];
            switch (c)
            {
            case '\n':
                flag = true;
                vector.X = x;
                if ((spriteEffects & SpriteEffects.FlipVertically) == SpriteEffects.FlipVertically)
                {
                    vector.Y -= (float)lineSpacing * scale.Y;
                }
                else
                {
                    vector.Y += (float)lineSpacing * scale.Y;
                }
                continue;
            case '\r':
                continue;
            }
            int indexForCharacter = GetIndexForCharacter(c);
            Vector3 vector2 = kerning[indexForCharacter];
            if (flag)
            {
                vector2.X = Math.Max(vector2.X, 0f);
            }
            else
            {
                vector.X += spacing * scale.X * (float)num;
            }
            vector.X += vector2.X * scale.X * (float)num;
            Rectangle value = glyphData[indexForCharacter];
            Rectangle rectangle = croppingData[indexForCharacter];
            if ((spriteEffects & SpriteEffects.FlipVertically) == SpriteEffects.FlipVertically)
            {
                rectangle.Y = lineSpacing - value.Height - rectangle.Y;
            }
            if ((spriteEffects & SpriteEffects.FlipHorizontally) == SpriteEffects.FlipHorizontally)
            {
                rectangle.X -= rectangle.Width;
            }
            Vector2 position = vector;
            position.X += (float)rectangle.X * scale.X;
            position.Y += (float)rectangle.Y * scale.Y;
            Vector2.Transform(ref position, ref result, out position);
            position += textblockPosition;
            spriteBatch.Draw(textureValue, position, value, color, rotation, Vector2.Zero, scale, spriteEffects, depth);
            flag = false;
            vector.X += (vector2.Y + vector2.Z) * scale.X * (float)num;
        }
    }
References Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Microsoft.Xna.Framework.Matrix.CreateTranslation(), Microsoft.Xna.Framework.Graphics.SpriteFont.croppingData, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteFont.GetIndexForCharacter(), Microsoft.Xna.Framework.Graphics.SpriteFont.glyphData, Microsoft.Xna.Framework.Graphics.SpriteFont.InternalMeasure(), Microsoft.Xna.Framework.Graphics.SpriteFont.kerning, Microsoft.Xna.Framework.Graphics.SpriteFont.lineSpacing, System.Math.Max(), Microsoft.Xna.Framework.Matrix.Multiply(), Microsoft.Xna.Framework.Graphics.SpriteFont.spacing, System.text, Microsoft.Xna.Framework.Graphics.SpriteFont.textureValue, Microsoft.Xna.Framework.Vector2.Transform(), System.value, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.