Terraria: UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay
UICreativeInfiniteItemsDisplay()
UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay (UIState uiStateThatHoldsThis) inline
     {
         _parentUIState = uiStateThatHoldsThis;
         _itemIdsAvailableTotal = new List<int>();
         _itemIdsAvailableToShow = new List<int>();
         _filterer = new EntryFilterer<Item, IItemEntryFilter>();
         List<IItemEntryFilter> list = new List<IItemEntryFilter>
         {
             new ItemFilters.Weapon(),
             new ItemFilters.Armor(),
             new ItemFilters.Vanity(),
             new ItemFilters.BuildingBlock(),
             new ItemFilters.Furniture(),
             new ItemFilters.Accessories(),
             new ItemFilters.MiscAccessories(),
             new ItemFilters.Consumables(),
             new ItemFilters.Tools(),
             new ItemFilters.Materials()
         };
         List<IItemEntryFilter> list2 = new List<IItemEntryFilter>();
         list2.AddRange(list);
         list2.Add(new ItemFilters.MiscFallback(list));
         _filterer.AddFilters(list2);
         _filterer.SetSearchFilterObject(new ItemFilters.BySearch());
         _sorter = new EntrySorter<int, ICreativeItemSortStep>();
         _sorter.AddSortSteps(new List<ICreativeItemSortStep>
         {
             new SortingSteps.ByCreativeSortingId(),
             new SortingSteps.Alphabetical()
         });
         _itemIdsAvailableTotal.AddRange(CreativeItemSacrificesCatalog.Instance.SacrificeCountNeededByItemId.Keys.ToList());
         BuildPage();
     }
References _filterer, _itemIdsAvailableToShow, _itemIdsAvailableTotal, _parentUIState, _sorter, EntryFilterer< T, U >.AddFilters(), EntrySorter< TEntryType, TStepType >.AddSortSteps(), BuildPage(), CreativeItemSacrificesCatalog.Instance, and CreativeItemSacrificesCatalog.SacrificeCountNeededByItemId.