Terraria: UICreativeInfiniteItemsDisplay.SacrificeWhatYouCan
SacrificeWhatYouCan()
void UICreativeInfiniteItemsDisplay.SacrificeWhatYouCan () inline
     {
         Main.CreativeMenu.GetSacrificeNumbers(out var itemIdChecked, out var amountWeHave, out var amountNeededTotal);
         int amountWeSacrificed;
         switch (Main.CreativeMenu.SacrificeItem(out amountWeSacrificed))
         {
         case CreativeUI.ItemSacrificeResult.SacrificedAndDone:
             _researchComplete = true;
             BeginSacrificeAnimation();
             RememberItemSacrifice(itemIdChecked, amountWeHave + amountWeSacrificed, amountNeededTotal);
             break;
         case CreativeUI.ItemSacrificeResult.SacrificedButNotDone:
             _researchComplete = false;
             BeginSacrificeAnimation();
             RememberItemSacrifice(itemIdChecked, amountWeHave + amountWeSacrificed, amountNeededTotal);
             break;
         }
     }
References _researchComplete, BeginSacrificeAnimation(), Main.CreativeMenu, CreativeUI.GetSacrificeNumbers(), RememberItemSacrifice(), and CreativeUI.SacrificeItem().
Referenced by sacrificeButton_OnClick(), and UICreativePowersMenu.SacrificeWhatsInResearchMenu().