Terraria: UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu
AddCogsForSacrificeMenu()
void UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu (UIElement sacrificesContainer) inline private
     {
         UIElement uIElement = new UIElement();
         uIElement.IgnoresMouseInteraction = true;
         SetBasicSizesForCreativeSacrificeOrInfinitesPanel(uIElement);
         uIElement.VAlign = 0.5f;
         uIElement.Height = new StyleDimension(170f, 0f);
         uIElement.Width = new StyleDimension(280f, 0f);
         uIElement.Top = default(StyleDimension);
         uIElement.SetPadding(0f);
         sacrificesContainer.Append(uIElement);
         Vector2 vector = new Vector2(-10f, -10f);
         AddSymetricalCogsPair(uIElement, new Vector2(22f, 1f) + vector, "Images/UI/Creative/Research_GearC", _sacrificeCogsSmall);
         AddSymetricalCogsPair(uIElement, new Vector2(1f, 28f) + vector, "Images/UI/Creative/Research_GearB", _sacrificeCogsMedium);
         AddSymetricalCogsPair(uIElement, new Vector2(5f, 5f) + vector, "Images/UI/Creative/Research_GearA", _sacrificeCogsBig);
     }
References UIElement.UIElement(), _sacrificeCogsBig, _sacrificeCogsMedium, _sacrificeCogsSmall, AddSymetricalCogsPair(), UIElement.Append(), UIElement.Height, UIElement.IgnoresMouseInteraction, SetBasicSizesForCreativeSacrificeOrInfinitesPanel(), UIElement.SetPadding(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildSacrificeMenuContents().