Terraria: UICreativeInfiniteItemsDisplay.StopPlayingAnimation
StopPlayingAnimation()
void UICreativeInfiniteItemsDisplay.StopPlayingAnimation () inline
     {
         ForgetItemSacrifice();
         _sacrificeAnimationTimeLeft = 0;
         _pistonParticleSystem.ClearParticles();
         UpdateVisualFrame();
     }
References _pistonParticleSystem, _sacrificeAnimationTimeLeft, UIParticleLayer.ClearParticles(), ForgetItemSacrifice(), and UpdateVisualFrame().
Referenced by UICreativePowersMenu.StopPlayingResearchAnimations().