Terraria: UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents
BuildInfinitesMenuContents()
void UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents (UIElement totalContainer) inline private
     {
         UIPanel uIPanel = CreateBasicPanel();
         totalContainer.Append(uIPanel);
         uIPanel.OnUpdate += Hover_OnUpdate;
         uIPanel.OnMouseOver += Hover_OnMouseOver;
         uIPanel.OnMouseOut += Hover_OnMouseOut;
         UIDynamicItemCollection item = (_itemGrid = new UIDynamicItemCollection());
         UIElement uIElement = new UIElement
         {
             Height = new StyleDimension(24f, 0f),
             Width = new StyleDimension(0f, 1f)
         };
         uIElement.SetPadding(0f);
         uIPanel.Append(uIElement);
         AddSearchBar(uIElement);
         _searchBar.SetContents(null, forced: true);
         UIList uIList = new UIList
         {
             Width = new StyleDimension(-25f, 1f),
             Height = new StyleDimension(-28f, 1f),
             VAlign = 1f,
             HAlign = 0f
         };
         uIPanel.Append(uIList);
         float num = 4f;
         UIScrollbar uIScrollbar = new UIScrollbar
         {
             Height = new StyleDimension(-28f - num * 2f, 1f),
             Top = new StyleDimension(0f - num, 0f),
             VAlign = 1f,
             HAlign = 1f
         };
         uIPanel.Append(uIScrollbar);
         uIList.SetScrollbar(uIScrollbar);
         uIList.Add(item);
         UICreativeItemsInfiniteFilteringOptions uICreativeItemsInfiniteFilteringOptions = new UICreativeItemsInfiniteFilteringOptions(_filterer, "CreativeInfinitesFilter");
         uICreativeItemsInfiniteFilteringOptions.OnClickingOption += filtersHelper_OnClickingOption;
         uICreativeItemsInfiniteFilteringOptions.Left = new StyleDimension(20f, 0f);
         totalContainer.Append(uICreativeItemsInfiniteFilteringOptions);
         uICreativeItemsInfiniteFilteringOptions.OnUpdate += Hover_OnUpdate;
         uICreativeItemsInfiniteFilteringOptions.OnMouseOver += Hover_OnMouseOver;
         uICreativeItemsInfiniteFilteringOptions.OnMouseOut += Hover_OnMouseOut;
     }
References _filterer, _itemGrid, _searchBar, UIList.Add(), AddSearchBar(), UIElement.Append(), CreateBasicPanel(), filtersHelper_OnClickingOption(), UIElement.HAlign, UIElement.Height, Hover_OnMouseOut(), Hover_OnMouseOver(), Hover_OnUpdate(), UIElement.Left, UICreativeItemsInfiniteFilteringOptions.OnClickingOption, UIElement.OnMouseOut, UIElement.OnMouseOver, UIElement.OnUpdate, UISearchBar.SetContents(), UIElement.SetPadding(), UIList.SetScrollbar(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().