Terraria: System.Numerics.BitOperations.TrailingZeroCount
TrailingZeroCount() [1/4]
static int System.Numerics.BitOperations.TrailingZeroCount (int value) inline static
Definition at line 298 of file BitOperations.cs.
    {
        return TrailingZeroCount((uint)value);
    }
References System.Numerics.BitOperations.TrailingZeroCount(), and System.value.
Referenced by System.Text.ASCIIUtility.CountNumberOfLeadingAsciiBytesFromUInt32WithSomeNonAsciiData(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeAdvSimd64(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeAdvSimd64(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar_Sse2(), System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2(), System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte(), System.Diagnostics.Tracing.EventProvider.GetSessionInfoCallback(), System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.LocateFirstFoundByte(), System.SpanHelpers.LocateFirstFoundChar(), System.SpanHelpers.SequenceCompareTo(), System.Byte.TrailingZeroCount(), System.Char.TrailingZeroCount(), System.Numerics.BitOperations.TrailingZeroCount(), System.Int32.TrailingZeroCount(), System.Numerics.BitOperations.TrailingZeroCount(), System.Int64.TrailingZeroCount(), System.IntPtr.TrailingZeroCount(), System.UIntPtr.TrailingZeroCount(), System.SByte.TrailingZeroCount(), System.Int16.TrailingZeroCount(), System.UInt32.TrailingZeroCount(), System.Numerics.BitOperations.TrailingZeroCount(), System.UInt64.TrailingZeroCount(), and System.UInt16.TrailingZeroCount().