Terraria: System.Numerics.BitOperations.PopCount
PopCount() [1/2]
static int System.Numerics.BitOperations.PopCount (uint value) inline static
Definition at line 256 of file BitOperations.cs.
    {
        if (Popcnt.IsSupported)
        {
            return (int)Popcnt.PopCount(value);
        }
        if (AdvSimd.Arm64.IsSupported)
        {
        }
        return SoftwareFallback(value);
        static int SoftwareFallback(uint value)
        {
            value -= (value >> 1) & 0x55555555;
            value = (value & 0x33333333) + ((value >> 2) & 0x33333333);
            value = ((value + (value >> 4)) & 0xF0F0F0F) * 16843009 >> 24;
            return (int)value;
        }
    }
References System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Popcnt.IsSupported, System.Runtime.Intrinsics.X86.Popcnt.PopCount(), and System.value.
Referenced by System.Collections.Specialized.BitVector32.CreateSectionHelper(), System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), System.Diagnostics.Tracing.EventProvider.GetSessionInfoCallback(), System.Numerics.BitOperations.Log2Ceiling(), System.Numerics.BitOperations.Log2Ceiling(), System.Byte.PopCount(), System.Char.PopCount(), System.Int32.PopCount(), System.Int64.PopCount(), System.IntPtr.PopCount(), System.UIntPtr.PopCount(), System.SByte.PopCount(), System.Int16.PopCount(), System.UInt32.PopCount(), System.UInt64.PopCount(), and System.UInt16.PopCount().