Terraria: System.Numerics.BitOperations.IsPow2
IsPow2() [1/6]
static bool System.Numerics.BitOperations.IsPow2 (int value) inline static
Definition at line 28 of file BitOperations.cs.
    {
        if ((value & (value - 1)) == 0)
        {
            return value > 0;
        }
        return false;
    }
References System.value.
Referenced by System.Runtime.InteropServices.NativeMemory.AlignedAlloc(), System.Runtime.InteropServices.NativeMemory.AlignedRealloc(), System.SpanHelpers.Fill< T >(), System.Byte.IsPow2(), System.Char.IsPow2(), System.Int32.IsPow2(), System.Int64.IsPow2(), System.IntPtr.IsPow2(), System.UIntPtr.IsPow2(), System.SByte.IsPow2(), System.Int16.IsPow2(), System.UInt32.IsPow2(), System.UInt64.IsPow2(), and System.UInt16.IsPow2().