Terraria: System.Numerics.BitOperations.RotateRight
RotateRight() [1/2]
static uint System.Numerics.BitOperations.RotateRight (uint value, int offset) inline static
Definition at line 374 of file BitOperations.cs.
    {
        return (value >> offset) | (value << 32 - offset);
    }
References System.offset, and System.value.
Referenced by System.Net.WebSockets.ManagedWebSocket.ApplyMask(), System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte(), System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.Int32.RotateRight(), System.Int64.RotateRight(), System.IntPtr.RotateRight(), System.UIntPtr.RotateRight(), System.UInt32.RotateRight(), System.UInt64.RotateRight(), and System.Text.Unicode.Utf8Utility.TranscodeToUtf16().