Terraria: System.Numerics.BitOperations.RotateLeft
RotateLeft() [1/2]
static uint System.Numerics.BitOperations.RotateLeft (uint value, int offset) inline static
Definition at line 360 of file BitOperations.cs.
    {
        return (value << offset) | (value >> 32 - offset);
    }
References System.offset, and System.value.
Referenced by System.Net.WebSockets.ManagedWebSocket.ApplyMask(), System.Marvin.Block(), System.Sha1ForNonSecretPurposes.Drain(), System.Text.Unicode.Utf8Utility.ExtractFourUtf8BytesFromSurrogatePair(), System.String.GetNonRandomizedHashCode(), System.String.GetNonRandomizedHashCodeOrdinalIgnoreCase(), System.Runtime.CompilerServices.CastHelpers.KeyToBucket(), System.HashCode.MixState(), System.Random.XoshiroImpl.NextBytes(), System.Random.XoshiroImpl.NextUInt64(), System.HashCode.QueueRound(), System.Buffers.Binary.BinaryPrimitives.ReverseEndianness(), System.Int32.RotateLeft(), System.Int64.RotateLeft(), System.IntPtr.RotateLeft(), System.UIntPtr.RotateLeft(), System.UInt32.RotateLeft(), System.UInt64.RotateLeft(), and System.HashCode.Round().