Terraria: System.Numerics.BitOperations.Log2
Log2() [2/2]
static int System.Numerics.BitOperations.Log2 (ulong value) inline static
Definition at line 199 of file BitOperations.cs.
    {
        value |= 1;
        if (Lzcnt.X64.IsSupported)
        {
            return 0x3F ^ (int)Lzcnt.X64.LeadingZeroCount(value);
        }
        if (ArmBase.Arm64.IsSupported)
        {
        }
        if (X86Base.X64.IsSupported)
        {
            return (int)X86Base.X64.BitScanReverse(value);
        }
        uint num = (uint)(value >> 32);
        if (num == 0)
        {
            return Log2((uint)value);
        }
        return 32 + Log2(num);
    }
References System.Runtime.Intrinsics.X86.X86Base.X64.BitScanReverse(), System.Runtime.Intrinsics.Arm.ArmBase.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Lzcnt.X64.IsSupported, System.Runtime.Intrinsics.X86.X86Base.X64.IsSupported, System.Runtime.Intrinsics.X86.Lzcnt.X64.LeadingZeroCount(), System.Numerics.BitOperations.Log2(), and System.value.