Terraria: System.Numerics.BitOperations.LeadingZeroCount
LeadingZeroCount() [1/2]
static int System.Numerics.BitOperations.LeadingZeroCount (uint value) inline static
Definition at line 131 of file BitOperations.cs.
    {
        if (Lzcnt.IsSupported)
        {
            return (int)Lzcnt.LeadingZeroCount(value);
        }
        if (ArmBase.IsSupported)
        {
        }
        if (value == 0)
        {
            return 32;
        }
        if (X86Base.IsSupported)
        {
            return (int)(0x1F ^ X86Base.BitScanReverse(value));
        }
        return 0x1F ^ Log2SoftwareFallback(value);
    }
References System.Runtime.Intrinsics.X86.X86Base.BitScanReverse(), System.Runtime.Intrinsics.Arm.ArmBase.IsSupported, System.Runtime.Intrinsics.X86.Lzcnt.IsSupported, System.Runtime.Intrinsics.X86.X86Base.IsSupported, System.Runtime.Intrinsics.X86.Lzcnt.LeadingZeroCount(), System.Numerics.BitOperations.Log2SoftwareFallback(), and System.value.
Referenced by System.Number.BigInteger.CountSignificantBits(), System.Number.BigInteger.CountSignificantBits(), System.Number.BigInteger.DivRem(), System.Numerics.BigInteger.GetBitLength(), System.Byte.LeadingZeroCount(), System.Char.LeadingZeroCount(), System.Int32.LeadingZeroCount(), System.Int64.LeadingZeroCount(), System.IntPtr.LeadingZeroCount(), System.UIntPtr.LeadingZeroCount(), System.SByte.LeadingZeroCount(), System.Int16.LeadingZeroCount(), System.UInt32.LeadingZeroCount(), System.Numerics.BitOperations.LeadingZeroCount(), System.UInt64.LeadingZeroCount(), System.UInt16.LeadingZeroCount(), System.Number.DiyFp.Normalize(), System.Net.Http.QPack.QPackDecoder.OnByte(), System.Net.Http.HPack.HPackDecoder.Parse(), System.Numerics.BitOperations.RoundUpToPowerOf2(), System.Numerics.BitOperations.RoundUpToPowerOf2(), System.Decimal.DecCalc.ScaleResult(), System.Net.Http.HPack.IntegerDecoder.TryDecode(), System.Decimal.DecCalc.VarDecDiv(), and System.Decimal.DecCalc.VarDecModFull().