Terraria: System.Numerics.BitOperations.TrailingZeroCount
TrailingZeroCount() [4/4]
static int System.Numerics.BitOperations.TrailingZeroCount (ulong value) inline static
Definition at line 333 of file BitOperations.cs.
    {
        if (Bmi1.X64.IsSupported)
        {
            return (int)Bmi1.X64.TrailingZeroCount(value);
        }
        if (ArmBase.Arm64.IsSupported)
        {
        }
        if (X86Base.X64.IsSupported)
        {
            if (value != 0L)
            {
                return (int)X86Base.X64.BitScanForward(value);
            }
            return 64;
        }
        uint num = (uint)value;
        if (num == 0)
        {
            return 32 + TrailingZeroCount((uint)(value >> 32));
        }
        return TrailingZeroCount(num);
    }
References System.Runtime.Intrinsics.X86.X86Base.X64.BitScanForward(), System.Runtime.Intrinsics.Arm.ArmBase.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Bmi1.X64.IsSupported, System.Runtime.Intrinsics.X86.X86Base.X64.IsSupported, System.L, System.Numerics.BitOperations.TrailingZeroCount(), System.Runtime.Intrinsics.X86.Bmi1.X64.TrailingZeroCount(), and System.value.