Terraria: System.Numerics.BitOperations.Log2
Log2() [1/2]
static int System.Numerics.BitOperations.Log2 (uint value) inline static
Definition at line 180 of file BitOperations.cs.
    {
        value |= 1u;
        if (Lzcnt.IsSupported)
        {
            return (int)(0x1F ^ Lzcnt.LeadingZeroCount(value));
        }
        if (ArmBase.IsSupported)
        {
        }
        if (X86Base.IsSupported)
        {
            return (int)X86Base.BitScanReverse(value);
        }
        return Log2SoftwareFallback(value);
    }
References System.Runtime.Intrinsics.X86.X86Base.BitScanReverse(), System.Runtime.Intrinsics.Arm.ArmBase.IsSupported, System.Runtime.Intrinsics.X86.Lzcnt.IsSupported, System.Runtime.Intrinsics.X86.X86Base.IsSupported, System.Runtime.Intrinsics.X86.Lzcnt.LeadingZeroCount(), System.Numerics.BitOperations.Log2SoftwareFallback(), and System.value.
Referenced by System.Buffers.Text.FormattingHelpers.CountHexDigits(), System.Number.Dragon4(), System.Number.Dragon4Double(), System.Number.Dragon4Half(), System.Number.Dragon4Single(), System.Text.Encodings.Web.DefaultHtmlEncoder.EscaperImplementation.EncodeUtf16(), System.Text.Encodings.Web.DefaultHtmlEncoder.EscaperImplementation.EncodeUtf8(), System.Array.SorterObjectArray.IntrospectiveSort(), System.Array.SorterGenericArray.IntrospectiveSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntrospectiveSort(), System.Collections.Generic.ArraySortHelper< TKey, TValue >.IntrospectiveSort(), System.SpanHelpers.LocateLastFoundByte(), System.SpanHelpers.LocateLastFoundChar(), System.Byte.Log2(), System.Char.Log2(), System.Int32.Log2(), System.Int64.Log2(), System.IntPtr.Log2(), System.UIntPtr.Log2(), System.SByte.Log2(), System.Int16.Log2(), System.UInt32.Log2(), System.Numerics.BitOperations.Log2(), System.UInt64.Log2(), System.UInt16.Log2(), System.Numerics.BitOperations.Log2Ceiling(), System.Numerics.BitOperations.Log2Ceiling(), System.Buffers.Utilities.SelectBucketIndex(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.Sort(), and System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.Sort().