Terraria: System.Dynamic.ExpandoObject.TryGetValueForKey
TryGetValueForKey()
bool System.Dynamic.ExpandoObject.TryGetValueForKey (string key, out object value) inline private
Definition at line 656 of file ExpandoObject.cs.
    {
        return TryGetValue(null, -1, key, ignoreCase: false, out value);
    }
References System.key, System.Dynamic.ExpandoObject.TryGetValue(), and System.value.
Referenced by System.Dynamic.ExpandoObject.Contains(), and System.Dynamic.ExpandoObject.TryGetValue().