Terraria: System.Dynamic.ExpandoObject.TryDeleteValue
TryDeleteValue()
bool System.Dynamic.ExpandoObject.TryDeleteValue (object indexClass, int index, string name, bool ignoreCase, object deleteValue) inline package
Definition at line 585 of file ExpandoObject.cs.
    {
        ExpandoData data;
        lock (LockObject)
        {
            data = _data;
            if (data.Class != indexClass || ignoreCase)
            {
                index = data.Class.GetValueIndex(name, ignoreCase, this);
                if (index == -2)
                {
                    throw Error.AmbiguousMatchInExpandoObject(name);
                }
            }
            if (index == -1)
            {
                return false;
            }
            object obj = data[index];
            if (obj == Uninitialized)
            {
                return false;
            }
            if (deleteValue != Uninitialized && !object.Equals(obj, deleteValue))
            {
                return false;
            }
            data[index] = Uninitialized;
            _count--;
        }
        _propertyChanged?.Invoke(this, new PropertyChangedEventArgs(data.Class.Keys[index]));
        return true;
    }
References System.Dynamic.ExpandoObject._count, System.Dynamic.ExpandoObject._data, System.Dynamic.ExpandoObject._propertyChanged, System.Linq.Expressions.Error.AmbiguousMatchInExpandoObject(), System.Dynamic.ExpandoObject.ExpandoData.Class, System.Dynamic.ExpandoClass.GetValueIndex(), System.index, System.Dynamic.ExpandoClass.Keys, System.Dynamic.ExpandoObject.LockObject, System.obj, and System.Dynamic.ExpandoObject.Uninitialized.
Referenced by System.Dynamic.ExpandoObject.Remove(), and System.Dynamic.ExpandoObject.Remove().