Terraria: System.Dynamic.ExpandoObject.TryGetValue
TryGetValue() [1/3]
bool System.Dynamic.ExpandoObject.TryGetValue (object indexClass, int index, string name, bool ignoreCase, out object value) inline package
Definition at line 512 of file ExpandoObject.cs.
    {
        ExpandoData data = _data;
        if (data.Class != indexClass || ignoreCase)
        {
            index = data.Class.GetValueIndex(name, ignoreCase, this);
            if (index == -2)
            {
                throw Error.AmbiguousMatchInExpandoObject(name);
            }
        }
        if (index == -1)
        {
            value = null;
            return false;
        }
        object obj = data[index];
        if (obj == Uninitialized)
        {
            value = null;
            return false;
        }
        value = obj;
        return true;
    }
References System.Dynamic.ExpandoObject._data, System.Linq.Expressions.Error.AmbiguousMatchInExpandoObject(), System.Dynamic.ExpandoObject.ExpandoData.Class, System.Dynamic.ExpandoClass.GetValueIndex(), System.index, System.obj, System.Dynamic.ExpandoObject.Uninitialized, and System.value.
Referenced by System.Dynamic.ExpandoObject.TryGetValueForKey().