Terraria: System.Net.Mail.SmtpClient.Dispose
Dispose() [2/2]
virtual void System.Net.Mail.SmtpClient.Dispose (bool disposing) inline protected virtual
Definition at line 927 of file SmtpClient.cs.
    {
        if (disposing && !_disposed)
        {
            if (InCall && !_cancelled)
            {
                _cancelled = true;
                Abort();
            }
            else
            {
                _transport?.ReleaseConnection();
            }
            _timer?.Dispose();
            _disposed = true;
        }
    }
References System.Net.Mail.SmtpClient._cancelled, System.Net.Mail.SmtpClient._disposed, System.Net.Mail.SmtpClient._timer, System.Net.Mail.SmtpClient._transport, System.Net.Mail.SmtpClient.Abort(), System.Threading.Timer.Dispose(), System.Net.Mail.SmtpClient.InCall, and System.Net.Mail.SmtpTransport.ReleaseConnection().