Terraria: System.Net.Mail.SmtpClient.Send
Send() [1/2]
void System.Net.Mail.SmtpClient.Send (MailMessage message) inline
Definition at line 411 of file SmtpClient.cs.
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(GetType().FullName);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"DeliveryMethod={DeliveryMethod}", "Send");
            System.Net.NetEventSource.Associate(this, message, "Send");
        }
        SmtpFailedRecipientException exception = null;
        if (InCall)
        {
            throw new InvalidOperationException(System.SR.net_inasync);
        }
        if (message == null)
        {
            throw new ArgumentNullException("message");
        }
        if (DeliveryMethod == SmtpDeliveryMethod.Network)
        {
            CheckHostAndPort();
        }
        MailAddressCollection mailAddressCollection = new MailAddressCollection();
        if (message.From == null)
        {
            throw new InvalidOperationException(System.SR.SmtpFromRequired);
        }
        if (message.To != null)
        {
            foreach (MailAddress item in message.To)
            {
                mailAddressCollection.Add(item);
            }
        }
        if (message.Bcc != null)
        {
            foreach (MailAddress item2 in message.Bcc)
            {
                mailAddressCollection.Add(item2);
            }
        }
        if (message.CC != null)
        {
            foreach (MailAddress item3 in message.CC)
            {
                mailAddressCollection.Add(item3);
            }
        }
        if (mailAddressCollection.Count == 0)
        {
            throw new InvalidOperationException(System.SR.SmtpRecipientRequired);
        }
        _transport.IdentityRequired = false;
        try
        {
            InCall = true;
            _timedOut = false;
            _timer = new Timer(TimeOutCallback, null, Timeout, Timeout);
            bool flag = false;
            string pickupDirectoryLocation = PickupDirectoryLocation;
            MailWriter mailWriter;
            switch (DeliveryMethod)
            {
            case SmtpDeliveryMethod.PickupDirectoryFromIis:
                throw new NotSupportedException(System.SR.SmtpGetIisPickupDirectoryNotSupported);
            case SmtpDeliveryMethod.SpecifiedPickupDirectory:
                if (EnableSsl)
                {
                    throw new SmtpException(System.SR.SmtpPickupDirectoryDoesnotSupportSsl);
                }
                flag = IsUnicodeSupported();
                ValidateUnicodeRequirement(message, mailAddressCollection, flag);
                mailWriter = GetFileMailWriter(pickupDirectoryLocation);
                break;
            default:
                GetConnection();
                flag = IsUnicodeSupported();
                ValidateUnicodeRequirement(message, mailAddressCollection, flag);
                mailWriter = _transport.SendMail(message.Sender ?? message.From, mailAddressCollection, message.BuildDeliveryStatusNotificationString(), flag, out exception);
                break;
            }
            _message = message;
            message.Send(mailWriter, DeliveryMethod != SmtpDeliveryMethod.Network, flag);
            mailWriter.Close();
            if (DeliveryMethod == SmtpDeliveryMethod.Network && exception != null)
            {
                throw exception;
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex, "Send");
            }
            if (ex is SmtpFailedRecipientException && !((SmtpFailedRecipientException)ex).fatal)
            {
                throw;
            }
            Abort();
            if (_timedOut)
            {
                throw new SmtpException(System.SR.net_timeout);
            }
            if (ex is SecurityException || ex is AuthenticationException || ex is SmtpException)
            {
                throw;
            }
            throw new SmtpException(System.SR.SmtpSendMailFailure, ex);
        }
        finally
        {
            InCall = false;
            if (_timer != null)
            {
                _timer.Dispose();
            }
        }
    }
References System.Net.Mail.SmtpClient._disposed, System.Net.Mail.SmtpClient._message, System.Net.Mail.SmtpClient._timedOut, System.Net.Mail.SmtpClient._timer, System.Net.Mail.SmtpClient._transport, System.Net.Mail.SmtpClient.Abort(), System.Net.Mail.MailAddressCollection.Add(), System.Net.NetEventSource.Associate(), System.Net.Mail.MailMessage.Bcc, System.Net.Mail.MailMessage.BuildDeliveryStatusNotificationString(), System.Net.Mail.MailMessage.CC, System.Net.Mail.SmtpClient.CheckHostAndPort(), System.Net.Mail.MailWriter.Close(), System.Collections.ObjectModel.Collection< T >.Count, System.Net.Mail.SmtpClient.DeliveryMethod, System.Threading.Timer.Dispose(), System.Net.Mail.SmtpClient.EnableSsl, System.Net.NetEventSource.Error(), System.exception, System.Net.Mail.MailMessage.From, System.FullName, System.Net.Mail.SmtpClient.GetConnection(), System.Net.Mail.SmtpClient.GetFileMailWriter(), System.Net.Mail.SmtpClient.InCall, System.Net.NetEventSource.Info(), System.Net.Mail.SmtpClient.IsUnicodeSupported(), System.item, System.Net.NetEventSource.Log, System.SR.net_inasync, System.SR.net_timeout, System.Net.Mail.SmtpClient.PickupDirectoryLocation, System.Net.Mail.MailMessage.Send(), System.Net.Mail.MailMessage.Sender, System.Net.Mail.SmtpTransport.SendMail(), System.SR.SmtpFromRequired, System.SR.SmtpGetIisPickupDirectoryNotSupported, System.SR.SmtpPickupDirectoryDoesnotSupportSsl, System.SR.SmtpRecipientRequired, System.SR.SmtpSendMailFailure, System.Net.Mail.SmtpClient.TimeOutCallback(), System.Net.Mail.MailMessage.To, and System.Net.Mail.SmtpClient.ValidateUnicodeRequirement().