Terraria: System.Net.Mail.SmtpClient.SendMailAsync
SendMailAsync() [2/4]
Task System.Net.Mail.SmtpClient.SendMailAsync (MailMessage message, CancellationToken cancellationToken) inline
Definition at line 695 of file SmtpClient.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled(cancellationToken);
        }
        TaskCompletionSource tcs = new TaskCompletionSource();
        CancellationTokenRegistration ctr = default(CancellationTokenRegistration);
        int state = 0;
        SendCompletedEventHandler handler = null;
        handler = delegate(object sender, AsyncCompletedEventArgs e)
        {
            if (e.UserState == tcs)
            {
                try
                {
                    ((SmtpClient)sender).SendCompleted -= handler;
                    if (Interlocked.Exchange(ref state, 1) != 0)
                    {
                        ctr.Dispose();
                    }
                }
                catch (ObjectDisposedException)
                {
                }
                finally
                {
                    if (e.Error != null)
                    {
                        tcs.TrySetException(e.Error);
                    }
                    else if (e.Cancelled)
                    {
                        tcs.TrySetCanceled();
                    }
                    else
                    {
                        tcs.TrySetResult();
                    }
                }
            }
        };
        SendCompleted += handler;
        try
        {
            SendAsync(message, tcs);
        }
        catch
        {
            SendCompleted -= handler;
            throw;
        }
        ctr = cancellationToken.Register(delegate(object s)
        {
            ((SmtpClient)s).SendAsyncCancel();
        }, this);
        if (Interlocked.Exchange(ref state, 1) != 0)
        {
            ctr.Dispose();
        }
        return tcs.Task;
    }
References System.Net.Mail.SmtpClient.SmtpClient(), System.cancellationToken, System.ComponentModel.AsyncCompletedEventArgs.Cancelled, System.Threading.CancellationTokenRegistration.Dispose(), System.ComponentModel.AsyncCompletedEventArgs.Error, System.Threading.Interlocked.Exchange(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.s, System.Net.Mail.SmtpClient.SendAsync(), System.Net.Mail.SmtpClient.SendCompleted, System.Net.Mail.SendCompletedEventHandler(), System.state, System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetCanceled(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult(), and System.ComponentModel.AsyncCompletedEventArgs.UserState.