Terraria: System.Net.Mail.SmtpClient.ConnectCallback
ConnectCallback()
void System.Net.Mail.SmtpClient.ConnectCallback (IAsyncResult result) inline private
Definition at line 878 of file SmtpClient.cs.
    {
        try
        {
            _transport.EndGetConnection(result);
            if (_cancelled)
            {
                Complete(null, result);
                return;
            }
            bool allowUnicode = IsUnicodeSupported();
            ValidateUnicodeRequirement(_message, _recipients, allowUnicode);
            _transport.BeginSendMail(_message.Sender ?? _message.From, _recipients, _message.BuildDeliveryStatusNotificationString(), allowUnicode, SendMailCallback, result.AsyncState);
        }
        catch (Exception exception)
        {
            Complete(exception, result);
        }
    }
References System.Net.Mail.SmtpClient._cancelled, System.Net.Mail.SmtpClient._message, System.Net.Mail.SmtpClient._recipients, System.Net.Mail.SmtpClient._transport, System.IAsyncResult.AsyncState, System.Net.Mail.SmtpTransport.BeginSendMail(), System.Net.Mail.MailMessage.BuildDeliveryStatusNotificationString(), System.Net.Mail.SmtpClient.Complete(), System.Net.Mail.SmtpTransport.EndGetConnection(), System.exception, System.Net.Mail.MailMessage.From, System.Net.Mail.SmtpClient.IsUnicodeSupported(), System.Net.Mail.MailMessage.Sender, System.Net.Mail.SmtpClient.SendMailCallback(), and System.Net.Mail.SmtpClient.ValidateUnicodeRequirement().
Referenced by System.Net.Mail.SmtpClient.SendAsync().