Terraria: System.Net.Mail.SmtpClient.Initialize
Initialize()
void System.Net.Mail.SmtpClient.Initialize () inline private
Definition at line 290 of file SmtpClient.cs.
    {
        _transport = new SmtpTransport(this);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Associate(this, _transport, "Initialize");
        }
        _onSendCompletedDelegate = SendCompletedWaitCallback;
        if (_host != null && _host.Length != 0)
        {
            _host = _host.Trim();
        }
        if (_port == 0)
        {
            _port = 25;
        }
        if (_targetName == null)
        {
            _targetName = "SMTPSVC/" + _host;
        }
        if (_clientDomain != null)
        {
            return;
        }
        string text = IPGlobalProperties.GetIPGlobalProperties().HostName;
        IdnMapping idnMapping = new IdnMapping();
        try
        {
            text = idnMapping.GetAscii(text);
        }
        catch (ArgumentException)
        {
        }
        StringBuilder stringBuilder = new StringBuilder();
        foreach (char c in text)
        {
            if (c <= '\u007f')
            {
                stringBuilder.Append(c);
            }
        }
        if (stringBuilder.Length > 0)
        {
            _clientDomain = stringBuilder.ToString();
        }
        else
        {
            _clientDomain = "LocalHost";
        }
    }
References System.Net.Mail.SmtpClient._clientDomain, System.Net.Mail.SmtpClient._host, System.Net.Mail.SmtpClient._onSendCompletedDelegate, System.Net.Mail.SmtpClient._port, System.Net.Mail.SmtpClient._targetName, System.Net.Mail.SmtpClient._transport, System.Net.NetEventSource.Associate(), System.Globalization.IdnMapping.GetAscii(), System.Net.NetworkInformation.IPGlobalProperties.GetIPGlobalProperties(), System.Net.NetEventSource.Log, System.Net.Mail.SmtpClient.SendCompletedWaitCallback(), and System.text.
Referenced by System.Net.Mail.SmtpClient.SmtpClient(), System.Net.Mail.SmtpClient.SmtpClient(), and System.Net.Mail.SmtpClient.SmtpClient().