Terraria: System.Net.Mail.SmtpClient.GetFileMailWriter
GetFileMailWriter()
MailWriter System.Net.Mail.SmtpClient.GetFileMailWriter (string pickupDirectory) inline package
Definition at line 370 of file SmtpClient.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, FormattableStringFactory.Create("{0}={1}", "pickupDirectory", pickupDirectory), "GetFileMailWriter");
        }
        if (!Path.IsPathRooted(pickupDirectory))
        {
            throw new SmtpException(System.SR.SmtpNeedAbsolutePickupDirectory);
        }
        string path2;
        do
        {
            string path = $"{Guid.NewGuid()}.eml";
            path2 = Path.Combine(pickupDirectory, path);
        }
        while (File.Exists(path2));
        FileStream stream = new FileStream(path2, FileMode.CreateNew);
        return new MailWriter(stream, encodeForTransport: false);
    }
References System.IO.Path.Combine(), System.Runtime.CompilerServices.FormattableStringFactory.Create(), System.IO.File.Exists(), System.Net.NetEventSource.Info(), System.IO.Path.IsPathRooted(), System.Net.NetEventSource.Log, System.SR.SmtpNeedAbsolutePickupDirectory, and System.stream.
Referenced by System.Net.Mail.SmtpClient.Send(), and System.Net.Mail.SmtpClient.SendAsync().