Terraria: System.Net.Mail.SmtpClient.IsUnicodeSupported
IsUnicodeSupported()
bool System.Net.Mail.SmtpClient.IsUnicodeSupported () inline private
Definition at line 357 of file SmtpClient.cs.
    {
        if (DeliveryMethod == SmtpDeliveryMethod.Network)
        {
            if (ServerSupportsEai)
            {
                return DeliveryFormat == SmtpDeliveryFormat.International;
            }
            return false;
        }
        return DeliveryFormat == SmtpDeliveryFormat.International;
    }
References System.Net.Mail.SmtpClient.DeliveryFormat, System.Net.Mail.SmtpClient.DeliveryMethod, and System.Net.Mail.SmtpClient.ServerSupportsEai.
Referenced by System.Net.Mail.SmtpClient.ConnectCallback(), System.Net.Mail.SmtpClient.Send(), System.Net.Mail.SmtpClient.SendAsync(), and System.Net.Mail.SmtpClient.SendMailCallback().