Terraria: System.Net.Mail.SmtpClient.SendAsync
SendAsync() [1/2]
void System.Net.Mail.SmtpClient.SendAsync (MailMessage message, object? userToken) inline
Definition at line 542 of file SmtpClient.cs.
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(GetType().FullName);
        }
        try
        {
            if (InCall)
            {
                throw new InvalidOperationException(System.SR.net_inasync);
            }
            if (message == null)
            {
                throw new ArgumentNullException("message");
            }
            if (DeliveryMethod == SmtpDeliveryMethod.Network)
            {
                CheckHostAndPort();
            }
            _recipients = new MailAddressCollection();
            if (message.From == null)
            {
                throw new InvalidOperationException(System.SR.SmtpFromRequired);
            }
            if (message.To != null)
            {
                foreach (MailAddress item in message.To)
                {
                    _recipients.Add(item);
                }
            }
            if (message.Bcc != null)
            {
                foreach (MailAddress item2 in message.Bcc)
                {
                    _recipients.Add(item2);
                }
            }
            if (message.CC != null)
            {
                foreach (MailAddress item3 in message.CC)
                {
                    _recipients.Add(item3);
                }
            }
            if (_recipients.Count == 0)
            {
                throw new InvalidOperationException(System.SR.SmtpRecipientRequired);
            }
            InCall = true;
            _cancelled = false;
            _message = message;
            string pickupDirectoryLocation = PickupDirectoryLocation;
            _transport.IdentityRequired = Credentials != null && (Credentials == CredentialCache.DefaultNetworkCredentials || !(Credentials is CredentialCache cache) || IsSystemNetworkCredentialInCache(cache));
            _asyncOp = AsyncOperationManager.CreateOperation(userToken);
            switch (DeliveryMethod)
            {
            case SmtpDeliveryMethod.PickupDirectoryFromIis:
                throw new NotSupportedException(System.SR.SmtpGetIisPickupDirectoryNotSupported);
            case SmtpDeliveryMethod.SpecifiedPickupDirectory:
            {
                if (EnableSsl)
                {
                    throw new SmtpException(System.SR.SmtpPickupDirectoryDoesnotSupportSsl);
                }
                _writer = GetFileMailWriter(pickupDirectoryLocation);
                bool allowUnicode = IsUnicodeSupported();
                ValidateUnicodeRequirement(message, _recipients, allowUnicode);
                message.Send(_writer, sendEnvelope: true, allowUnicode);
                if (_writer != null)
                {
                    _writer.Close();
                }
                AsyncCompletedEventArgs arg = new AsyncCompletedEventArgs(null, cancelled: false, _asyncOp.UserSuppliedState);
                InCall = false;
                _asyncOp.PostOperationCompleted(_onSendCompletedDelegate, arg);
                return;
            }
            }
            _operationCompletedResult = new System.Net.ContextAwareResult(_transport.IdentityRequired, forceCaptureContext: true, null, this, s_contextSafeCompleteCallback);
            lock (_operationCompletedResult.StartPostingAsyncOp())
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"Calling BeginConnect. Transport: {_transport}", "SendAsync");
                }
                _transport.BeginGetConnection(_operationCompletedResult, ConnectCallback, _operationCompletedResult, Host, Port);
                _operationCompletedResult.FinishPostingAsyncOp();
            }
        }
        catch (Exception ex)
        {
            InCall = false;
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex, "SendAsync");
            }
            if (ex is SmtpFailedRecipientException && !((SmtpFailedRecipientException)ex).fatal)
            {
                throw;
            }
            Abort();
            if (ex is SecurityException || ex is AuthenticationException || ex is SmtpException)
            {
                throw;
            }
            throw new SmtpException(System.SR.SmtpSendMailFailure, ex);
        }
    }
References System.Net.Mail.SmtpClient._asyncOp, System.Net.Mail.SmtpClient._cancelled, System.Net.Mail.SmtpClient._disposed, System.Net.Mail.SmtpClient._message, System.Net.Mail.SmtpClient._onSendCompletedDelegate, System.Net.Mail.SmtpClient._operationCompletedResult, System.Net.Mail.SmtpClient._recipients, System.Net.Mail.SmtpClient._transport, System.Net.Mail.SmtpClient._writer, System.Net.Mail.SmtpClient.Abort(), System.Net.Mail.MailAddressCollection.Add(), System.Net.Mail.MailMessage.Bcc, System.Net.Mail.SmtpTransport.BeginGetConnection(), System.Net.Mail.MailMessage.CC, System.Net.Mail.SmtpClient.CheckHostAndPort(), System.Net.Mail.MailWriter.Close(), System.Net.Mail.SmtpClient.ConnectCallback(), System.Collections.ObjectModel.Collection< T >.Count, System.ComponentModel.AsyncOperationManager.CreateOperation(), System.Net.Mail.SmtpClient.Credentials, System.Net.Mail.SmtpClient.DeliveryMethod, System.Net.Mail.SmtpClient.EnableSsl, System.Net.NetEventSource.Error(), System.Net.Mail.MailMessage.From, System.FullName, System.Net.Mail.SmtpClient.GetFileMailWriter(), System.Net.Mail.SmtpClient.Host, System.Net.Mail.SmtpTransport.IdentityRequired, System.Net.Mail.SmtpClient.InCall, System.Net.NetEventSource.Info(), System.Net.Mail.SmtpClient.IsSystemNetworkCredentialInCache(), System.Net.Mail.SmtpClient.IsUnicodeSupported(), System.item, System.Net.NetEventSource.Log, System.SR.net_inasync, System.Net.Mail.SmtpClient.PickupDirectoryLocation, System.Net.Mail.SmtpClient.Port, System.ComponentModel.AsyncOperation.PostOperationCompleted(), System.Net.Mail.SmtpClient.s_contextSafeCompleteCallback, System.Net.Mail.MailMessage.Send(), System.SR.SmtpFromRequired, System.SR.SmtpGetIisPickupDirectoryNotSupported, System.SR.SmtpPickupDirectoryDoesnotSupportSsl, System.SR.SmtpRecipientRequired, System.SR.SmtpSendMailFailure, System.Net.Mail.MailMessage.To, System.ComponentModel.AsyncOperation.UserSuppliedState, and System.Net.Mail.SmtpClient.ValidateUnicodeRequirement().