Terraria: System.Net.Mail.SmtpClient.SendMailCallback
SendMailCallback()
void System.Net.Mail.SmtpClient.SendMailCallback (IAsyncResult result) inline private
Definition at line 848 of file SmtpClient.cs.
    {
        try
        {
            _writer = _transport.EndSendMail(result);
            SendMailAsyncResult sendMailAsyncResult = (SendMailAsyncResult)result;
            _failedRecipientException = sendMailAsyncResult.GetFailedRecipientException();
        }
        catch (Exception exception)
        {
            Complete(exception, result);
            return;
        }
        try
        {
            if (_cancelled)
            {
                Complete(null, result);
            }
            else
            {
                _message.BeginSend(_writer, DeliveryMethod != SmtpDeliveryMethod.Network, IsUnicodeSupported(), SendMessageCallback, result.AsyncState);
            }
        }
        catch (Exception exception2)
        {
            Complete(exception2, result);
        }
    }
References System.Net.Mail.SmtpClient._cancelled, System.Net.Mail.SmtpClient._failedRecipientException, System.Net.Mail.SmtpClient._message, System.Net.Mail.SmtpClient._transport, System.Net.Mail.SmtpClient._writer, System.IAsyncResult.AsyncState, System.Net.Mail.MailMessage.BeginSend(), System.Net.Mail.SmtpClient.Complete(), System.Net.Mail.SmtpClient.DeliveryMethod, System.Net.Mail.SmtpTransport.EndSendMail(), System.exception, System.Net.Mail.SendMailAsyncResult.GetFailedRecipientException(), System.Net.Mail.SmtpClient.IsUnicodeSupported(), and System.Net.Mail.SmtpClient.SendMessageCallback().
Referenced by System.Net.Mail.SmtpClient.ConnectCallback().