Terraria: System.Net.Mail.SmtpClient.Complete
Complete()
void System.Net.Mail.SmtpClient.Complete (Exception exception, IAsyncResult result) inline private
Definition at line 779 of file SmtpClient.cs.
    {
        System.Net.ContextAwareResult contextAwareResult = (System.Net.ContextAwareResult)result.AsyncState;
        try
        {
            if (_cancelled)
            {
                exception = null;
                Abort();
            }
            else if (exception != null && (!(exception is SmtpFailedRecipientException) || ((SmtpFailedRecipientException)exception).fatal))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, exception, "Complete");
                }
                Abort();
                if (!(exception is SmtpException))
                {
                    exception = new SmtpException(System.SR.SmtpSendMailFailure, exception);
                }
            }
            else if (_writer != null)
            {
                try
                {
                    _writer.Close();
                }
                catch (SmtpException ex)
                {
                    exception = ex;
                }
            }
        }
        finally
        {
            contextAwareResult.InvokeCallback(exception);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, "Complete", "Complete");
        }
    }
References System.Net.Mail.SmtpClient._cancelled, System.Net.Mail.SmtpClient._writer, System.Net.Mail.SmtpClient.Abort(), System.IAsyncResult.AsyncState, System.Net.Mail.MailWriter.Close(), System.Net.NetEventSource.Error(), System.exception, System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InvokeCallback(), System.Net.NetEventSource.Log, and System.SR.SmtpSendMailFailure.
Referenced by System.Net.Mail.SmtpClient.ConnectCallback(), System.Net.Mail.SmtpClient.SendMailCallback(), and System.Net.Mail.SmtpClient.SendMessageCallback().