Terraria: System.Xml.XmlNameTable.Add
Add() [1/2]
string System.Xml.XmlNameTable.Add (char[] array, int offset, int length) abstract
Referenced by System.Xml.DocumentSchemaValidator.DocumentSchemaValidator(), System.Xml.Xsl.Runtime.XmlQueryRuntime.XmlQueryRuntime(), System.Xml.XmlSqlBinaryReader.XmlSqlBinaryReader(), System.Xml.XmlSubtreeReader.XmlSubtreeReader(), System.Xml.XmlTextReaderImpl.XmlTextReaderImpl(), System.Xml.XsdValidatingReader.XsdValidatingReader(), System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.AddAttributeNoChecks(), System.Xml.XmlTextReaderImpl.AddDefaultAttributeNonDtd(), System.Xml.XmlSqlBinaryReader.AddName(), System.Xml.DomNameTable.AddName(), System.Xml.XmlSubtreeReader.AddNamespace(), System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlSqlBinaryReader.AddQName(), System.Xml.Serialization.XmlSerializationReader.AddReadCallback(), System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Xsl.Xslt.XsltLoader.AtomizeAttributes(), System.Xml.Xsl.XsltOld.RecordBuilder.BeginEvent(), System.Xml.Xsl.IlGen.XmlILNamespaceAnalyzer.CheckNamespaceInScope(), System.Xml.XmlNodeReaderNavigator.DefaultLookupNamespace(), System.Xml.Serialization.XmlSerializationReader.EnsureCallbackTables(), System.Xml.Xsl.Xslt.XsltInput.FillupRecord(), System.Xml.Xsl.Xslt.XsltInput.FindStylesheetElement(), System.Xml.XmlSqlBinaryReader.GenerateImpliedXmlnsAttrs(), System.Xml.Xsl.XsltOld.OutputScopeManager.GeneratePrefix(), System.Xml.XsdValidatingReader.GetAttributePSVI(), System.Xml.XsdValidatingReader.GetDefaultAttribute(), System.Xml.Schema.XmlSchemaValidator.GetDefaultAttributePrefix(), System.Xml.DocumentSchemaValidator.GetDefaultPrefix(), System.Xml.XmlTextReaderImpl.GetIndexOfAttributeWithPrefix(), System.Xml.DtdParser.GetNameQualified(), System.Xml.XmlNodeReaderNavigator.GetNamespacesInScope(), System.Xml.XmlNode.GetPrefixOfNamespaceStrict(), System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.XmlTextReaderImpl.HandleEntityReference(), System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(), System.Xml.XmlSqlBinaryReader.ImplReadDoctype(), System.Xml.Schema.XmlSchemaValidator.Init(), MS.Internal.Xml.Cache.XPathDocumentBuilder.Initialize(), System.Xml.DtdParser.InitializeFreeFloatingDtd(), System.Xml.Serialization.XmlSerializationReader.InitPrimitiveIDs(), System.Xml.Schema.XdrBuilder.LoadSchema(), System.Xml.Linq.XNodeReader.LookupNamespace(), System.Xml.XmlNodeReader.LookupNamespace(), System.Xml.XmlNodeReaderNavigator.LookupNamespace(), System.Xml.XmlNodeReaderNavigator.LookupPrefix(), System.Xml.XmlTextReaderImpl.OnDefaultNamespaceDecl(), System.Xml.XmlTextReaderImpl.OnNamespaceDecl(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement(), System.Xml.XmlTextReaderImpl.ParseEntityName(), System.Xml.XmlTextReaderImpl.ParseEntityNameAsync(), System.Xml.XmlTextReaderImpl.ParsePI(), System.Xml.XmlTextReaderImpl.ParsePIAsync(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.Xsl.Xslt.XsltInput.ReadAttribute(), System.Xml.XmlSqlBinaryReader.ReadInit(), System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(), System.Xml.XmlSqlBinaryReader.ScanAttributes(), System.Xml.Serialization.XmlSerializationReader.ToXmlQualifiedName(), System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteNamespaceDeclaration(), MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteProcessingInstruction(), MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteStartAttribute(), and MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteStartElement().