Terraria: System.Collections.Stack.Push
Push() [2/2]
virtual void System.Collections.Stack.Push (object? obj) inline virtual inherited
Definition at line 357 of file Stack.cs.
    {
        if (_size == _array.Length)
        {
            object[] array = new object[2 * _array.Length];
            Array.Copy(_array, array, _size);
            _array = array;
        }
        _array[_size++] = obj;
        _version++;
    }
References System.Collections.Stack._array, System.Collections.Stack._size, System.Collections.Stack._version, System.array, System.Array.Copy(), and System.obj.
Referenced by System.Collections.Stack.Stack(), System.Xml.Serialization.CodeGenerator.BeginExceptionBlock(), System.Collections.Stack.SyncStack.Push(), and System.Diagnostics.CorrelationManager.StartLogicalOperation().