Terraria: System.Collections.Stack.Pop
Pop()
virtual ? object System.Collections.Stack.Pop () inline virtual
Reimplemented in System.Collections.Stack.SyncStack, and System.Diagnostics.CorrelationManager.AsyncLocalStackWrapper.
Definition at line 345 of file Stack.cs.
    {
        if (_size == 0)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_EmptyStack);
        }
        _version++;
        object result = _array[--_size];
        _array[_size] = null;
        return result;
    }
References System.Collections.Stack._array, System.Collections.Stack._size, System.Collections.Stack._version, and System.SR.InvalidOperation_EmptyStack.
Referenced by System.Xml.Serialization.CodeGenerator.EndExceptionBlock(), System.Collections.Stack.SyncStack.Pop(), and System.Diagnostics.CorrelationManager.StopLogicalOperation().