Terraria: System.Globalization.TimeSpanParse.TimeSpanRawInfo.ProcessToken
ProcessToken()
bool System.Globalization.TimeSpanParse.TimeSpanRawInfo.ProcessToken (ref TimeSpanToken tok, ref TimeSpanResult result) inline package
Definition at line 342 of file TimeSpanParse.cs.
        {
            switch (tok._ttt)
            {
            case TTT.Num:
                if ((_tokenCount == 0 && !AddSep(default(ReadOnlySpan<char>), ref result)) || !AddNum(tok, ref result))
                {
                    return false;
                }
                break;
            case TTT.Sep:
                if (!AddSep(tok._sep, ref result))
                {
                    return false;
                }
                break;
            case TTT.NumOverflow:
                return result.SetOverflowFailure();
            default:
                return result.SetBadTimeSpanFailure();
            }
            _lastSeenTTT = tok._ttt;
            return true;
        }
References System.Globalization.TimeSpanParse.TimeSpanRawInfo._lastSeenTTT, System.Globalization.TimeSpanParse.TimeSpanRawInfo._tokenCount, System.Globalization.TimeSpanParse.TimeSpanRawInfo.AddNum(), and System.Globalization.TimeSpanParse.TimeSpanRawInfo.AddSep().
Referenced by System.Globalization.TimeSpanParse.TryParseTimeSpan().