Terraria: AmbientSky.ButterfliesSkyEntity.ButterfliesSkyEntity
ButterfliesSkyEntity()
AmbientSky.ButterfliesSkyEntity.ButterfliesSkyEntity (Player player, FastRandom random) inline
         {
             VirtualCamera virtualCamera = new VirtualCamera(player);
             Effects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             int num = 100;
             if (Effects == SpriteEffects.FlipHorizontally)
             {
                 Position.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
             }
             else
             {
                 Position.X = virtualCamera.Position.X - (float)num;
             }
             Position.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 4000f) + 4000f;
             Depth = random.NextFloat() * 3f + 3f;
             SetPositionInWorldBasedOnScreenSpace(Position);
             int num2 = random.Next(2) + 1;
             Texture = Main.Assets.Request<Texture2D>("Images/Backgrounds/Ambience/ButterflySwarm" + num2, (AssetRequestMode)1);
             Frame = new SpriteFrame(1, (byte)((num2 == 2) ? 19u : 17u));
             LifeTime = random.Next(60, 121) * 60;
             OpacityNormalizedTimeToFadeIn = 0.15f;
             OpacityNormalizedTimeToFadeOut = 0.85f;
             BrightnessLerper = 0.2f;
             FinalOpacityMultiplier = 1f;
             FramingSpeed = 5;
         }
References Main.Assets, AmbientSky.FadingSkyEntity.BrightnessLerper, AmbientSky.SkyEntity.Depth, AmbientSky.SkyEntity.Effects, AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, AmbientSky.SkyEntity.Frame, AmbientSky.FadingSkyEntity.FramingSpeed, AmbientSky.FadingSkyEntity.LifeTime, FastRandom.Next(), FastRandom.NextFloat(), AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, AmbientSky.SkyEntity.Position, VirtualCamera.Position, AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), VirtualCamera.Size, AmbientSky.SkyEntity.Texture, Main.WindForVisuals, and Main.worldSurface.