Terraria: FlexibleTileWand.TryGetPlacementOption
TryGetPlacementOption()
bool FlexibleTileWand.TryGetPlacementOption (Player player, int randomSeed, int selectCycleOffset, out PlacementOption option, out Item itemToConsume) inline
     {
         option = null;
         itemToConsume = null;
         Item[] inventory = player.inventory;
         for (int i = 0; i < 58; i++)
         {
             if (i < 50 || i >= 54)
             {
                 Item item = inventory[i];
                 if (!item.IsAir && _options.TryGetValue(item.type, out var value))
                 {
                     _random.SetSeed(randomSeed);
                     option = value.GetOptionWithCycling(selectCycleOffset);
                     itemToConsume = item;
                     return true;
                 }
             }
         }
         return false;
     }
References _options, _random, Player.inventory, Item.IsAir, UnifiedRandom.SetSeed(), and Item.type.
Referenced by Player.ModifyFlexibleWandPlacementInfo(), Player.PlaceThing_Tiles_CheckFlexibleWand(), Player.PlaceThing_Tiles_PlaceIt_ConsumeFlexibleWandMaterial(), and Main.TryGetAmmo().