Terraria: System.Linq.Expressions.Compiler.CompilerScope.EmitNewHoistedLocals
EmitNewHoistedLocals()
void System.Linq.Expressions.Compiler.CompilerScope.EmitNewHoistedLocals (LambdaCompiler lc) inline private
Definition at line 384 of file CompilerScope.cs.
    {
        if (_hoistedLocals == null)
        {
            return;
        }
        lc.IL.EmitPrimitive(_hoistedLocals.Variables.Count);
        lc.IL.Emit(OpCodes.Newarr, typeof(object));
        int num = 0;
        foreach (ParameterExpression variable in _hoistedLocals.Variables)
        {
            lc.IL.Emit(OpCodes.Dup);
            lc.IL.EmitPrimitive(num++);
            Type type = typeof(StrongBox<>).MakeGenericType(variable.Type);
            int index;
            if (IsMethod && (index = lc.Parameters.IndexOf(variable)) >= 0)
            {
                lc.EmitLambdaArgument(index);
                lc.IL.Emit(OpCodes.Newobj, type.GetConstructor(new Type[1] { variable.Type }));
            }
            else if (variable == _hoistedLocals.ParentVariable)
            {
                ResolveVariable(variable, _closureHoistedLocals).EmitLoad();
                lc.IL.Emit(OpCodes.Newobj, type.GetConstructor(new Type[1] { variable.Type }));
            }
            else
            {
                lc.IL.Emit(OpCodes.Newobj, type.GetConstructor(Type.EmptyTypes));
            }
            if (ShouldCache(variable))
            {
                lc.IL.Emit(OpCodes.Dup);
                CacheBoxToLocal(lc, variable);
            }
            lc.IL.Emit(OpCodes.Stelem_Ref);
        }
        EmitSet(_hoistedLocals.SelfVariable);
    }
References System.Linq.Expressions.Compiler.CompilerScope._closureHoistedLocals, System.Linq.Expressions.Compiler.CompilerScope._hoistedLocals, System.Linq.Expressions.Compiler.CompilerScope.CacheBoxToLocal(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Count, System.Reflection.Emit.OpCodes.Dup, System.Linq.Expressions.Compiler.CompilerScope.Storage.EmitLoad(), System.Linq.Expressions.Compiler.CompilerScope.EmitSet(), System.Type.EmptyTypes, System.Linq.index, System.Linq.Expressions.Compiler.CompilerScope.IsMethod, System.Reflection.Emit.OpCodes.Newarr, System.Reflection.Emit.OpCodes.Newobj, System.Linq.Expressions.Compiler.HoistedLocals.ParentVariable, System.Linq.Expressions.Compiler.CompilerScope.ResolveVariable(), System.Linq.Expressions.Compiler.HoistedLocals.SelfVariable, System.Linq.Expressions.Compiler.CompilerScope.ShouldCache(), System.Reflection.Emit.OpCodes.Stelem_Ref, System.type, and System.Linq.Expressions.Compiler.HoistedLocals.Variables.
Referenced by System.Linq.Expressions.Compiler.CompilerScope.Enter().