Terraria: System.Net.Http.HttpRuleParser.GetHostLength
GetHostLength()
static int System.Net.Http.HttpRuleParser.GetHostLength (string input, int startIndex, bool allowToken, out string host) inline static package
Definition at line 140 of file HttpRuleParser.cs.
    {
        host = null;
        if (startIndex >= input.Length)
        {
            return 0;
        }
        int i = startIndex;
        bool flag;
        bool num;
        for (flag = true; i < input.Length; flag = num, i++)
        {
            char c = input[i];
            switch (c)
            {
            case '/':
                return 0;
            default:
                num = flag && IsTokenChar(c);
                continue;
            case '\t':
            case '\r':
            case ' ':
            case ',':
                break;
            }
            break;
        }
        int num2 = i - startIndex;
        if (num2 == 0)
        {
            return 0;
        }
        string text = input.Substring(startIndex, num2);
        if ((!allowToken || !flag) && !IsValidHostName(text))
        {
            return 0;
        }
        host = text;
        return num2;
    }
References System.input, System.Net.Http.HttpRuleParser.IsTokenChar(), System.Net.Http.HttpRuleParser.IsValidHostName(), System.startIndex, and System.text.
Referenced by System.Net.Http.Headers.WarningHeaderValue.CheckAgent(), System.Net.Http.Headers.ViaHeaderValue.CheckReceivedBy(), System.Net.Http.Headers.ViaHeaderValue.GetViaLength(), System.Net.Http.Headers.GenericHeaderParser.ParseHost(), and System.Net.Http.Headers.WarningHeaderValue.TryReadAgent().