Terraria: System.Linq.Expressions.Compiler.CompilerScope.Exit
Exit()
CompilerScope System.Linq.Expressions.Compiler.CompilerScope.Exit () inline package
Definition at line 275 of file CompilerScope.cs.
    {
        if (!IsMethod)
        {
            foreach (Storage value in _locals.Values)
            {
                value.FreeLocal();
            }
        }
        CompilerScope parent = _parent;
        _parent = null;
        _hoistedLocals = null;
        _closureHoistedLocals = null;
        _locals.Clear();
        return parent;
    }
References System.Linq.Expressions.Compiler.CompilerScope._closureHoistedLocals, System.Linq.Expressions.Compiler.CompilerScope._hoistedLocals, System.Linq.Expressions.Compiler.CompilerScope._locals, System.Linq.Expressions.Compiler.CompilerScope._parent, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Linq.Expressions.Compiler.CompilerScope.IsMethod, System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(), and System.Linq.Expressions.Compiler.LambdaCompiler.ExitScope().