Terraria: System.Linq.Expressions.Compiler.CompilerScope.EmitCachedVariables
EmitCachedVariables()
void System.Linq.Expressions.Compiler.CompilerScope.EmitCachedVariables () inline private
Definition at line 423 of file CompilerScope.cs.
    {
        if (ReferenceCount == null)
        {
            return;
        }
        foreach (KeyValuePair<ParameterExpression, int> item in ReferenceCount)
        {
            if (ShouldCache(item.Key, item.Value) && ResolveVariable(item.Key) is ElementBoxStorage elementBoxStorage)
            {
                elementBoxStorage.EmitLoadBox();
                CacheBoxToLocal(elementBoxStorage.Compiler, item.Key);
            }
        }
    }
References System.Linq.Expressions.Compiler.CompilerScope.CacheBoxToLocal(), System.item, System.Linq.Expressions.Compiler.CompilerScope.ReferenceCount, System.Linq.Expressions.Compiler.CompilerScope.ResolveVariable(), and System.Linq.Expressions.Compiler.CompilerScope.ShouldCache().
Referenced by System.Linq.Expressions.Compiler.CompilerScope.Enter().