Terraria: System.Net.Http.HttpRuleParser.GetWhitespaceLength
GetWhitespaceLength()
static int System.Net.Http.HttpRuleParser.GetWhitespaceLength (string input, int startIndex) inline static package
Definition at line 92 of file HttpRuleParser.cs.
    {
        if (startIndex >= input.Length)
        {
            return 0;
        }
        for (int i = startIndex; i < input.Length; i++)
        {
            char c = input[i];
            if (c != ' ' && c != '\t')
            {
                return i - startIndex;
            }
        }
        return input.Length - startIndex;
    }
References System.input, and System.startIndex.
Referenced by System.Net.Http.Headers.AuthenticationHeaderValue.GetAuthenticationLength(), System.Net.Http.Headers.ContentRangeHeaderValue.GetContentRangeLength(), System.Net.Http.Headers.ContentDispositionHeaderValue.GetDispositionTypeLength(), System.Net.Http.Headers.EntityTagHeaderValue.GetEntityTagLength(), System.Net.Http.Headers.MediaTypeHeaderValue.GetMediaTypeExpressionLength(), System.Net.Http.Headers.MediaTypeHeaderValue.GetMediaTypeLength(), System.Net.Http.Headers.NameValueHeaderValue.GetNameValueLength(), System.Net.Http.Headers.NameValueHeaderValue.GetNameValueListLength(), System.Net.Http.Headers.NameValueWithParametersHeaderValue.GetNameValueWithParametersLength(), System.Net.Http.Headers.HeaderUtilities.GetNextNonEmptyOrWhitespaceIndex(), System.Net.Http.Headers.ProductInfoHeaderValue.GetProductInfoLength(), System.Net.Http.Headers.ProductHeaderValue.GetProductLength(), System.Net.Http.Headers.ViaHeaderValue.GetProtocolEndIndex(), System.Net.Http.Headers.RangeItemHeaderValue.GetRangeItemLength(), System.Net.Http.Headers.RangeHeaderValue.GetRangeLength(), System.Net.Http.Headers.RetryConditionHeaderValue.GetRetryConditionLength(), System.Net.Http.Headers.StringWithQualityHeaderValue.GetStringWithQualityLength(), System.Net.Http.Headers.TransferCodingHeaderValue.GetTransferCodingLength(), System.Net.Http.Headers.ViaHeaderValue.GetViaLength(), System.Net.Http.Headers.ContentRangeHeaderValue.TryGetLengthLength(), System.Net.Http.Headers.AuthenticationHeaderValue.TryGetParametersEndIndex(), System.Net.Http.Headers.ContentRangeHeaderValue.TryGetRangeLength(), System.Net.Http.Headers.ProductInfoHeaderParser.TryParseValue(), System.Net.Http.Headers.WarningHeaderValue.TryReadAgent(), System.Net.Http.Headers.WarningHeaderValue.TryReadCode(), System.Net.Http.Headers.WarningHeaderValue.TryReadDate(), System.Net.Http.Headers.StringWithQualityHeaderValue.TryReadQuality(), and System.Net.Http.Headers.AuthenticationHeaderValue.TrySkipFirstBlob().