Terraria: System.Net.Http.HttpRuleParser.ContainsNewLine
ContainsNewLine()
static bool System.Net.Http.HttpRuleParser.ContainsNewLine (string value, int startIndex = 0) inline static package
Definition at line 109 of file HttpRuleParser.cs.
    {
        return value.AsSpan(startIndex).IndexOfAny('\r', '\n') != -1;
    }
References System.startIndex, and System.value.
Referenced by System.Net.Http.Headers.HttpHeaders.CheckContainsNewLine(), System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(), System.Net.Http.Headers.HttpHeaders.ContainsNewLine(), and System.Net.Http.Headers.GenericHeaderParser.ParseWithoutValidation().