Terraria: System.Net.Http.HttpRuleParser.GetExpressionLength
GetExpressionLength()
static HttpParseResult System.Net.Http.HttpRuleParser.GetExpressionLength (string input, int startIndex, char openChar, char closeChar, bool supportsNesting, int nestedCount, out int length) inline static private
Definition at line 207 of file HttpRuleParser.cs.
    {
        length = 0;
        if (input[startIndex] != openChar)
        {
            return HttpParseResult.NotParsed;
        }
        int num = startIndex + 1;
        while (num < input.Length)
        {
            int length2 = 0;
            if (num + 2 < input.Length && GetQuotedPairLength(input, num, out length2) == HttpParseResult.Parsed)
            {
                num += length2;
                continue;
            }
            char c = input[num];
            if (c == '\r' || c == '\n')
            {
                return HttpParseResult.InvalidFormat;
            }
            if (supportsNesting && c == openChar)
            {
                if (nestedCount > 5)
                {
                    return HttpParseResult.InvalidFormat;
                }
                int length3 = 0;
                switch (GetExpressionLength(input, num, openChar, closeChar, supportsNesting, nestedCount + 1, out length3))
                {
                case HttpParseResult.Parsed:
                    num += length3;
                    break;
                case HttpParseResult.InvalidFormat:
                    return HttpParseResult.InvalidFormat;
                }
            }
            else
            {
                if (input[num] == closeChar)
                {
                    length = num - startIndex + 1;
                    return HttpParseResult.Parsed;
                }
                num++;
            }
        }
        return HttpParseResult.InvalidFormat;
    }
References System.Net.Http.HttpRuleParser.GetExpressionLength(), System.Net.Http.HttpRuleParser.GetQuotedPairLength(), System.input, System.length, System.length2, System.length3, and System.startIndex.
Referenced by System.Net.Http.HttpRuleParser.GetCommentLength(), System.Net.Http.HttpRuleParser.GetExpressionLength(), and System.Net.Http.HttpRuleParser.GetQuotedStringLength().