Terraria: System.Linq.Expressions.Compiler.CompilerScope.EmitVariableAccess
EmitVariableAccess()
void System.Linq.Expressions.Compiler.CompilerScope.EmitVariableAccess (LambdaCompiler lc, ReadOnlyCollection< ParameterExpression > vars) inline package
Definition at line 292 of file CompilerScope.cs.
    {
        if (NearestHoistedLocals != null && vars.Count > 0)
        {
            System.Collections.Generic.ArrayBuilder<long> arrayBuilder = new System.Collections.Generic.ArrayBuilder<long>(vars.Count);
            foreach (ParameterExpression var in vars)
            {
                ulong num = 0uL;
                HoistedLocals hoistedLocals = NearestHoistedLocals;
                while (!hoistedLocals.Indexes.ContainsKey(var))
                {
                    num++;
                    hoistedLocals = hoistedLocals.Parent;
                }
                ulong item = (num << 32) | (uint)hoistedLocals.Indexes[var];
                arrayBuilder.UncheckedAdd((long)item);
            }
            EmitGet(NearestHoistedLocals.SelfVariable);
            lc.EmitConstantArray(arrayBuilder.ToArray());
            lc.IL.Emit(OpCodes.Call, CachedReflectionInfo.RuntimeOps_CreateRuntimeVariables_ObjectArray_Int64Array);
        }
        else
        {
            lc.IL.Emit(OpCodes.Call, CachedReflectionInfo.RuntimeOps_CreateRuntimeVariables);
        }
    }
References System.Reflection.Emit.OpCodes.Call, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Compiler.CompilerScope.EmitGet(), System.item, System.Linq.Expressions.Compiler.CompilerScope.NearestHoistedLocals, System.Linq.Expressions.CachedReflectionInfo.RuntimeOps_CreateRuntimeVariables, System.Linq.Expressions.CachedReflectionInfo.RuntimeOps_CreateRuntimeVariables_ObjectArray_Int64Array, and System.Linq.Expressions.Compiler.HoistedLocals.SelfVariable.
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitRuntimeVariablesExpression().