Terraria: System.Net.Http.HttpRuleParser.GetTokenLength
GetTokenLength()
static int System.Net.Http.HttpRuleParser.GetTokenLength (string input, int startIndex) inline static package
Definition at line 47 of file HttpRuleParser.cs.
    {
        if (startIndex >= input.Length)
        {
            return 0;
        }
        for (int i = startIndex; i < input.Length; i++)
        {
            if (!IsTokenChar(input[i]))
            {
                return i - startIndex;
            }
        }
        return input.Length - startIndex;
    }
References System.input, System.Net.Http.HttpRuleParser.IsTokenChar(), and System.startIndex.
Referenced by System.Net.Http.HttpMethod.HttpMethod(), System.Net.Http.Headers.HeaderUtilities.CheckValidToken(), System.Net.Http.Headers.ContentDispositionHeaderValue.EncodeAndQuoteMime(), System.Net.Http.Headers.AuthenticationHeaderValue.GetAuthenticationLength(), System.Net.Http.Headers.ContentRangeHeaderValue.GetContentRangeLength(), System.Net.Http.Headers.ContentDispositionHeaderValue.GetDispositionTypeExpressionLength(), System.Net.Http.Headers.MediaTypeHeaderValue.GetMediaTypeExpressionLength(), System.Net.Http.Headers.NameValueHeaderValue.GetNameValueLength(), System.Net.Http.Headers.AltSvcHeaderParser.GetParsedValueLength(), System.Net.Http.Headers.ProductHeaderValue.GetProductLength(), System.Net.Http.Headers.ViaHeaderValue.GetProtocolEndIndex(), System.Net.Http.Headers.RangeHeaderValue.GetRangeLength(), System.Net.Http.Headers.StringWithQualityHeaderValue.GetStringWithQualityLength(), System.Net.Http.Headers.TransferCodingHeaderValue.GetTransferCodingLength(), System.Net.Http.Headers.NameValueHeaderValue.GetValueLength(), System.Net.Http.Headers.GenericHeaderParser.ParseTokenList(), System.Net.Http.Headers.AuthenticationHeaderValue.TryGetParametersEndIndex(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadPercentEncodedAlpnProtocolName(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadTokenOrQuotedInt32(), System.Net.Http.Headers.CacheControlHeaderValue.TrySetOptionalTokenList(), and System.Net.Http.Headers.AltSvcHeaderParser.TrySkipTokenOrQuoted().