Terraria: System.Net.Http.HttpRuleParser.GetCommentLength
GetCommentLength()
static HttpParseResult System.Net.Http.HttpRuleParser.GetCommentLength (string input, int startIndex, out int length) inline static package
Definition at line 182 of file HttpRuleParser.cs.
    {
        return GetExpressionLength(input, startIndex, '(', ')', supportsNesting: true, 1, out length);
    }
References System.Net.Http.HttpRuleParser.GetExpressionLength(), System.input, System.length, and System.startIndex.
Referenced by System.Net.Http.Headers.HeaderUtilities.CheckValidComment(), System.Net.Http.Headers.ProductInfoHeaderValue.GetProductInfoLength(), and System.Net.Http.Headers.ViaHeaderValue.GetViaLength().