Terraria: System.Net.Http.HttpRuleParser.GetQuotedStringLength
GetQuotedStringLength()
static HttpParseResult System.Net.Http.HttpRuleParser.GetQuotedStringLength (string input, int startIndex, out int length) inline static package
Definition at line 187 of file HttpRuleParser.cs.
    {
        return GetExpressionLength(input, startIndex, '"', '"', supportsNesting: false, 1, out length);
    }
References System.Net.Http.HttpRuleParser.GetExpressionLength(), System.input, System.length, and System.startIndex.
Referenced by System.Net.Http.Headers.EntityTagHeaderValue.EntityTagHeaderValue(), System.Net.Http.Headers.HeaderUtilities.CheckValidQuotedString(), System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(), System.Net.Http.Headers.EntityTagHeaderValue.GetEntityTagLength(), System.Net.Http.Headers.NameValueHeaderValue.GetValueLength(), System.Net.Http.Headers.WarningHeaderValue.GetWarningLength(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadQuotedAltAuthority(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadTokenOrQuotedInt32(), System.Net.Http.Headers.AuthenticationHeaderValue.TrySkipFirstBlob(), and System.Net.Http.Headers.AltSvcHeaderParser.TrySkipTokenOrQuoted().