Terraria: System.Net.Http.HttpRuleParser.IsTokenChar
IsTokenChar()
static bool System.Net.Http.HttpRuleParser.IsTokenChar (char character) inline static package
Definition at line 38 of file HttpRuleParser.cs.
    {
        if (character > '\u007f')
        {
            return false;
        }
        return s_tokenChars[(uint)character];
    }
References System.Net.Http.HttpRuleParser.s_tokenChars.
Referenced by System.Net.Http.Headers.HeaderUtilities.Encode5987(), System.Net.Http.HttpRuleParser.GetHostLength(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.Net.Http.HttpRuleParser.IsToken(), System.Net.Http.HttpRuleParser.IsToken(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadTokenOrQuotedInt32(), and System.Net.Http.Headers.AltSvcHeaderParser.TrySkipTokenOrQuoted().