Terraria: System.Linq.Expressions.Compiler.CompilerScope.ResolveVariable
ResolveVariable() [2/2]
Storage System.Linq.Expressions.Compiler.CompilerScope.ResolveVariable (ParameterExpression variable, HoistedLocals hoistedLocals) inline private
Definition at line 344 of file CompilerScope.cs.
    {
        for (CompilerScope compilerScope = this; compilerScope != null; compilerScope = compilerScope._parent)
        {
            if (compilerScope._locals.TryGetValue(variable, out var value))
            {
                return value;
            }
            if (compilerScope.IsMethod)
            {
                break;
            }
        }
        for (HoistedLocals hoistedLocals2 = hoistedLocals; hoistedLocals2 != null; hoistedLocals2 = hoistedLocals2.Parent)
        {
            if (hoistedLocals2.Indexes.TryGetValue(variable, out var value2))
            {
                return new ElementBoxStorage(ResolveVariable(hoistedLocals2.SelfVariable, hoistedLocals), value2, variable);
            }
        }
        throw Error.UndefinedVariable(variable.Name, variable.Type, CurrentLambdaName);
    }
References System.Linq.Expressions.Compiler.CompilerScope.CurrentLambdaName, System.Linq.Expressions.Compiler.CompilerScope.ResolveVariable(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Linq.Expressions.Error.UndefinedVariable(), and System.value.