Terraria: System.Collections.ArrayList.Add
Add() [2/2]
virtual int System.Collections.ArrayList.Add (object? value) inline virtual inherited
Implements System.Collections.IList.
Definition at line 2302 of file ArrayList.cs.
    {
        if (_size == _items.Length)
        {
            EnsureCapacity(_size + 1);
        }
        _items[_size] = value;
        _version++;
        return _size++;
    }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, System.Collections.ArrayList.EnsureCapacity(), and System.value.
Referenced by System.Xml.Schema.ActiveAxis.ActiveAxis(), System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection.DesignerOptionCollection(), System.ComponentModel.ListSortDescriptionCollection.ListSortDescriptionCollection(), System.Data.NewDiffgramGen.NewDiffgramGen(), System.Data.NewDiffgramGen.NewDiffgramGen(), System.Xml.Xsl.Runtime.WhitespaceRuleLookup.WhitespaceRuleLookup(), System.Data.XmlDataTreeWriter.XmlDataTreeWriter(), System.Data.XmlDataTreeWriter.XmlDataTreeWriter(), System.Net.CookieCollection.Add(), System.Xml.Serialization.WorkItems.Add(), System.Xml.Schema.Positions.Add(), System.Collections.CollectionBase.Add(), System.Collections.ArrayList.SyncArrayList.Add(), System.Xml.Serialization.CodeIdentifiers.Add(), System.Collections.Specialized.StringCollection.Add(), System.Xml.Xsl.XsltOld.ContainerAction.AddAction(), System.Security.SecurityElement.AddAttributeSafe(), System.Data.DataRelationCollection.DataTableRelationCollection.AddCache(), System.Security.SecurityElement.AddChild(), System.Data.DataRelationCollection.DataSetRelationCollection.AddCore(), System.Xml.Xsl.XsltOld.CopyCodeAction.AddEvent(), System.Xml.Serialization.XmlSerializationReader.AddFixup(), System.Xml.Serialization.XmlSerializationReader.AddFixup(), System.Xml.Xsl.XsltOld.Key.AddKey(), System.Xml.Schema.SymbolsDictionary.AddName(), System.Xml.Xsl.XsltOld.Processor.AddSort(), System.Xml.Xsl.XsltOld.Stylesheet.AddSpace(), System.Xml.Xsl.Qil.SubstitutionList.AddSubstitutionPair(), System.Xml.Serialization.XmlSerializationReader.AddTarget(), System.Xml.Xsl.XsltOld.TemplateManager.AddTemplate(), System.Xml.Serialization.TypeScope.AddTypeMapping(), System.Xml.Schema.SymbolsDictionary.AddWildcard(), System.Xml.Xsl.IlGen.XmlILElementAnalyzer.AnalyzeAttributeCtor(), System.Data.ConstraintCollection.ArrayAdd(), System.Data.DataColumnCollection.ArrayAdd(), System.Data.DataTableCollection.ArrayAdd(), System.Collections.Specialized.NameObjectCollectionBase.BaseAdd(), System.Data.ConstraintCollection.BaseGroupSwitch(), System.Data.DataColumnCollection.BaseGroupSwitch(), System.Data.DataTableCollection.BaseGroupSwitch(), System.Xml.Xsl.XsltOld.SequentialOutput.CacheRecord(), System.Data.ConstraintCollection.Clear(), System.Data.DataColumnCollection.Clear(), System.Xml.Schema.FacetsChecker.FacetsCompiler.CompileEnumerationFacet(), System.Xml.Schema.Asttree.CompileXPath(), System.Data.XmlTreeGen.CreateRelations(), System.Data.NewDiffgramGen.CreateTableHierarchy(), System.Data.XmlDataTreeWriter.CreateTablesHierarchy(), System.Data.XMLDiffLoader.CreateTablesHierarchy(), System.Data.XmlTreeGen.CreateTablesHierarchy(), System.Data.XmlDataTreeWriter.CreateToplevelTables(), System.Data.XmlTreeGen.CreateToplevelTables(), System.ComponentModel.TypeDescriptor.FilterMembers(), System.Xml.Schema.FacetsChecker.FacetsCompiler.FinishFacetCompile(), System.Data.XmlTreeGen.GenerateConstraintNames(), System.Xml.Serialization.SchemaObjectCache.GetDependencies(), System.Xml.Serialization.XmlSerializationWriter.GetId(), System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XSDSchema.HandleColumnExpression(), System.Data.XSDSchema.HandleComplexType(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleSimpleContentColumn(), System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn(), System.Data.XSDSchema.InstantiateTable(), System.Net.CookieCollection.InternalAdd(), System.Data.XMLDiffLoader.LoadDiffGram(), System.Xml.Xsl.XsltOld.RecordBuilder.NewAttribute(), System.Xml.Xsl.XsltOld.RecordBuilder.NewNamespace(), System.Xml.XmlDataDocument.OnRowChanging(), System.Xml.Schema.Preprocessor.Preprocess(), System.Xml.Schema.AxisStack.Push(), System.ComponentModel.Design.Serialization.ContextStack.Push(), System.Xml.Schema.SelectorActiveAxis.PushKS(), System.Collections.ArrayList.Repeat(), and System.Data.XmlTreeGen.SchemaTree().