Terraria: System.Collections.ArrayList.Insert
Insert() [2/2]
virtual void System.Collections.ArrayList.Insert (int index, object? value) inline virtual inherited
Implements System.Collections.IList.
Definition at line 2499 of file ArrayList.cs.
    {
        if (index < 0 || index > _size)
        {
            throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_Index);
        }
        if (_size == _items.Length)
        {
            EnsureCapacity(_size + 1);
        }
        if (index < _size)
        {
            Array.Copy(_items, index, _items, index + 1, _size - index);
        }
        _items[index] = value;
        _size++;
        _version++;
    }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, System.SR.ArgumentOutOfRange_Index, System.Array.Copy(), System.Collections.ArrayList.EnsureCapacity(), System.index, and System.value.
Referenced by System.Collections.ArrayList.Range.Add(), System.ComponentModel.Design.Serialization.ContextStack.Append(), System.Data.DataColumnCollection.ArrayAdd(), System.Collections.CollectionBase.Insert(), System.Collections.ArrayList.SyncArrayList.Insert(), System.Collections.ArrayList.Range.Insert(), System.Collections.Specialized.StringCollection.Insert(), System.Data.DataColumnCollection.MoveTo(), System.Collections.CollectionBase.Remove(), and System.Collections.CollectionBase.RemoveAt().