Terraria: System.Collections.ArrayList.SetRange
SetRange()
virtual void System.Collections.ArrayList.SetRange (int index, ICollection c) inline virtual
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 2684 of file ArrayList.cs.
    {
        if (c == null)
        {
            throw new ArgumentNullException("c", SR.ArgumentNull_Collection);
        }
        int count = c.Count;
        if (index < 0 || index > _size - count)
        {
            throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_Index);
        }
        if (count > 0)
        {
            c.CopyTo(_items, index);
            _version++;
        }
    }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, System.SR.ArgumentNull_Collection, System.SR.ArgumentOutOfRange_Index, System.Collections.ICollection.CopyTo(), System.count, System.Collections.ICollection.Count, and System.index.
Referenced by System.Collections.ArrayList.SyncArrayList.SetRange(), System.Collections.ArrayList.FixedSizeArrayList.SetRange(), and System.Collections.ArrayList.Range.SetRange().