Terraria: System.Collections.ArrayList.IndexOf
IndexOf() [4/6]
virtual int System.Collections.ArrayList.IndexOf (object? value) inline virtual inherited
Implements System.Collections.IList.
Definition at line 2472 of file ArrayList.cs.
    {
        return Array.IndexOf(_items, value, 0, _size);
    }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Array.IndexOf(), and System.value.
Referenced by System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection.IndexOf(), System.Collections.CollectionBase.IndexOf(), System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection.IndexOf(), System.Collections.ArrayList.SyncArrayList.IndexOf(), System.Collections.ArrayList.FixedSizeArrayList.IndexOf(), System.Collections.ArrayList.ReadOnlyArrayList.IndexOf(), System.Collections.ArrayList.Range.IndexOf(), System.Collections.ArrayList.SyncArrayList.IndexOf(), System.Collections.ArrayList.FixedSizeArrayList.IndexOf(), System.Collections.ArrayList.ReadOnlyArrayList.IndexOf(), System.Collections.ArrayList.Range.IndexOf(), System.Collections.ArrayList.SyncArrayList.IndexOf(), System.Collections.ArrayList.FixedSizeArrayList.IndexOf(), System.Collections.ArrayList.ReadOnlyArrayList.IndexOf(), System.Collections.ArrayList.Range.IndexOf(), System.Collections.Specialized.StringCollection.IndexOf(), System.Collections.CollectionBase.Remove(), and System.Collections.ArrayList.Remove().