Terraria: System.Collections.ArrayList.ToArray
ToArray() [1/2]
virtual ? object[] System.Collections.ArrayList.ToArray () inline virtual
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 2761 of file ArrayList.cs.
    {
        if (_size == 0)
        {
            return Array.Empty<object>();
        }
        object[] array = new object[_size];
        Array.Copy(_items, array, _size);
        return array;
    }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.array, and System.Array.Copy().
Referenced by System.Collections.ArrayList.SyncArrayList.ToArray(), System.Collections.ArrayList.FixedSizeArrayList.ToArray(), System.Collections.ArrayList.ReadOnlyArrayList.ToArray(), System.Collections.ArrayList.SyncArrayList.ToArray(), System.Collections.ArrayList.FixedSizeArrayList.ToArray(), and System.Collections.ArrayList.ReadOnlyArrayList.ToArray().