Terraria: System.Collections.ArrayList.BinarySearch
BinarySearch() [2/6]
virtual int System.Collections.ArrayList.BinarySearch (int index, int count, object? value, IComparer? comparer) inline virtual inherited
Definition at line 2318 of file ArrayList.cs.
    {
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (_size - index < count)
        {
            throw new ArgumentException(SR.Argument_InvalidOffLen);
        }
        return Array.BinarySearch(_items, index, count, value, comparer);
    }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.SR.Argument_InvalidOffLen, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.Array.BinarySearch(), System.comparer, System.count, System.index, and System.value.
Referenced by System.Collections.ArrayList.SyncArrayList.BinarySearch(), System.Collections.ArrayList.FixedSizeArrayList.BinarySearch(), System.Collections.ArrayList.ReadOnlyArrayList.BinarySearch(), System.Collections.ArrayList.Range.BinarySearch(), System.Collections.ArrayList.SyncArrayList.BinarySearch(), System.Collections.ArrayList.SyncArrayList.BinarySearch(), System.Collections.ArrayList.BinarySearch(), and System.Collections.ArrayList.BinarySearch().