Terraria: System.Collections.ArrayList.GetEnumerator
GetEnumerator() [1/2]
virtual IEnumerator System.Collections.ArrayList.GetEnumerator () inline virtual
Implements System.Collections.IEnumerable.
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 2450 of file ArrayList.cs.
    {
        return new ArrayListEnumeratorSimple(this);
    }
Referenced by System.Security.SecurityElement.Equal(), System.Collections.CollectionBase.GetEnumerator(), System.Collections.ReadOnlyCollectionBase.GetEnumerator(), System.Collections.Specialized.StringCollection.GetEnumerator(), System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection.GetEnumerator(), System.ComponentModel.ListSortDescriptionCollection.GetEnumerator(), System.Data.InternalDataCollectionBase.GetEnumerator(), System.Net.CookieCollection.GetEnumerator(), System.Collections.ArrayList.SyncArrayList.GetEnumerator(), System.Collections.ArrayList.FixedSizeArrayList.GetEnumerator(), System.Collections.ArrayList.ReadOnlyArrayList.GetEnumerator(), System.Collections.ArrayList.SyncArrayList.GetEnumerator(), System.Collections.ArrayList.FixedSizeArrayList.GetEnumerator(), System.Collections.ArrayList.ReadOnlyArrayList.GetEnumerator(), and System.Collections.ArrayList.Range.GetEnumerator().