Terraria: System.Collections.ArrayList.Sort
Sort() [1/4]
virtual void System.Collections.ArrayList.Sort () inline virtual inherited
Reimplemented in System.Collections.ArrayList.SyncArrayList.
Definition at line 2715 of file ArrayList.cs.
    {
        Sort(0, Count, Comparer.Default);
    }
References System.Collections.ArrayList.Count, System.Collections.Comparer.Default, and System.Collections.ArrayList.Sort().
Referenced by System.Xml.Xsl.XsltOld.TemplateManager.ProcessTemplates(), System.Collections.ArrayList.SyncArrayList.Sort(), System.Collections.ArrayList.Sort(), System.Collections.ArrayList.SyncArrayList.Sort(), System.Collections.ArrayList.Sort(), System.Collections.ArrayList.SyncArrayList.Sort(), System.Collections.ArrayList.FixedSizeArrayList.Sort(), and System.Collections.ArrayList.Range.Sort().