Terraria: System.Collections.ArrayList.Contains
Contains() [2/2]
virtual bool System.Collections.ArrayList.Contains (object? item) inline virtual inherited
Implements System.Collections.IList.
Definition at line 2364 of file ArrayList.cs.
    {
        if (item == null)
        {
            for (int i = 0; i < _size; i++)
            {
                if (_items[i] == null)
                {
                    return true;
                }
            }
            return false;
        }
        for (int j = 0; j < _size; j++)
        {
            object obj = _items[j];
            if (obj != null && obj.Equals(item))
            {
                return true;
            }
        }
        return false;
    }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.item, and System.obj.
Referenced by System.Collections.ArrayList.SyncArrayList.Contains(), System.Collections.ArrayList.FixedSizeArrayList.Contains(), System.Collections.ArrayList.ReadOnlyArrayList.Contains(), System.Collections.CollectionBase.Contains(), System.ComponentModel.Design.DesignerOptionService.DesignerOptionCollection.Contains(), System.Collections.Specialized.StringCollection.Contains(), System.Data.XmlTreeGen.CreateRelations(), System.Data.NewDiffgramGen.CreateTableHierarchy(), System.Data.XmlDataTreeWriter.CreateTablesHierarchy(), System.Data.XMLDiffLoader.CreateTablesHierarchy(), System.Data.XmlTreeGen.CreateTablesHierarchy(), System.Data.XmlTreeGen.GenerateConstraintNames(), System.Data.XSDSchema.HandleComplexType(), System.Data.XmlTreeGen.HandleTable(), System.Data.XSDSchema.LoadSchema(), and System.Xml.Schema.Preprocessor.Preprocess().