Terraria: System.Collections.ArrayList.Remove
Remove() [2/2]
virtual void System.Collections.ArrayList.Remove (object? obj) inline virtual inherited
Implements System.Collections.IList.
Definition at line 2593 of file ArrayList.cs.
    {
        int num = IndexOf(obj);
        if (num >= 0)
        {
            RemoveAt(num);
        }
    }
References System.Collections.ArrayList.IndexOf(), System.obj, and System.Collections.ArrayList.RemoveAt().
Referenced by System.Data.ConstraintCollection.ArrayRemove(), System.Data.DataColumnCollection.ArrayRemove(), System.Data.ConstraintCollection.BaseGroupSwitch(), System.Data.DataColumnCollection.BaseGroupSwitch(), System.Data.DataTableCollection.BaseRemove(), System.Data.XSDSchema.HandleComplexType(), System.Data.DataColumnCollection.MoveTo(), System.Collections.ArrayList.SyncArrayList.Remove(), System.Xml.Serialization.CodeIdentifiers.Remove(), and System.Collections.Specialized.StringCollection.Remove().