Terraria: Terraria.GameContent.RGB.BlizzardShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.BlizzardShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 25 of file BlizzardShader.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        if ((int)quality == 0)
        {
            time *= 0.25f;
        }
        for (int i = 0; i < fragment.Count; i++)
        {
            float staticNoise = NoiseHelper.GetStaticNoise(fragment.GetCanvasPositionOfIndex(i) * new Vector2(0.2f, 0.4f) + new Vector2(time * _timeScaleX, time * _timeScaleY));
            Vector4 vector = Vector4.Lerp(_backColor, _frontColor, staticNoise * staticNoise);
            fragment.SetColor(i, vector);
        }
    }
References Terraria.GameContent.RGB.BlizzardShader._backColor, Terraria.GameContent.RGB.BlizzardShader._frontColor, Terraria.GameContent.RGB.BlizzardShader._timeScaleX, Terraria.GameContent.RGB.BlizzardShader._timeScaleY, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Microsoft.Xna.Framework.Vector4.Lerp(), and ReLogic.Peripherals.RGB.Fragment.SetColor().