Terraria: System.Data.DataRelation.CheckStateForProperty
CheckStateForProperty()
void System.Data.DataRelation.CheckStateForProperty () inline protected
Definition at line 512 of file DataRelation.cs.
    {
        try
        {
            CheckState();
        }
        catch (Exception ex) when (ADP.IsCatchableExceptionType(ex))
        {
            throw ExceptionBuilder.BadObjectPropertyAccess(ex.Message);
        }
    }
References System.Data.ExceptionBuilder.BadObjectPropertyAccess(), System.Data.DataRelation.CheckState(), and System.Data.Common.ADP.IsCatchableExceptionType().