Terraria: System.Data.DataRelation.GetParentRow
GetParentRow()
static DataRow System.Data.DataRelation.GetParentRow (DataKey parentKey, DataKey childKey, DataRow childRow, DataRowVersion version) inline static package
Definition at line 403 of file DataRelation.cs.
    {
        if (!childRow.HasVersion((version == DataRowVersion.Original) ? DataRowVersion.Original : DataRowVersion.Current) && childRow._tempRecord == -1)
        {
            return null;
        }
        object[] keyValues = childRow.GetKeyValues(childKey, version);
        if (IsKeyNull(keyValues))
        {
            return null;
        }
        Index sortIndex = parentKey.GetSortIndex((version == DataRowVersion.Original) ? DataViewRowState.OriginalRows : DataViewRowState.CurrentRows);
        Range range = sortIndex.FindRecords(keyValues);
        if (range.IsNull)
        {
            return null;
        }
        if (range.Count > 1)
        {
            throw ExceptionBuilder.MultipleParents();
        }
        return parentKey.Table._recordManager[sortIndex.GetRecord(range.Min)];
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataRelation.IsKeyNull(), and System.Data.ExceptionBuilder.MultipleParents().
Referenced by System.Data.ForeignKeyConstraint.CheckConstraint(), and System.Data.DataRow.GetParentRow().