Terraria: DD2Film.DD2Film
DD2Film()
DD2Film.DD2Film () inline
     {
         AppendKeyFrames(CreateDryad, CreateCritters);
         AppendSequences(120, DryadStand, DryadLookRight);
         AppendSequences(100, DryadLookRight, DryadInteract);
         AddKeyFrame(base.AppendPoint - 20, CreatePortal);
         AppendSequences(30, DryadLookLeft, DryadStand);
         AppendSequences(40, DryadConfusedEmote, DryadStand, DryadLookLeft);
         AppendKeyFrame(CreateOgre);
         AddKeyFrame(base.AppendPoint + 60, SpawnJavalinThrower);
         AddKeyFrame(base.AppendPoint + 120, SpawnGoblin);
         AddKeyFrame(base.AppendPoint + 180, SpawnGoblin);
         AddKeyFrame(base.AppendPoint + 240, SpawnWitherBeast);
         AppendSequences(30, DryadStand, DryadLookLeft);
         AppendSequences(30, DryadLookRight, DryadWalk);
         AppendSequences(300, DryadAttack, DryadLookLeft);
         AppendKeyFrame(RemoveEnemyDamage);
         AppendSequences(60, DryadLookRight, DryadStand, DryadAlertEmote);
         AddSequences(base.AppendPoint - 90, 60, OgreLookLeft, OgreStand);
         AddKeyFrame(base.AppendPoint - 12, OgreSwingSound);
         AddSequences(base.AppendPoint - 30, 50, DryadPortalKnock, DryadStand);
         AppendKeyFrame(RestoreEnemyDamage);
         AppendSequences(40, DryadPortalFade, DryadStand);
         AppendSequence(180, DryadStand);
         AddSequence(0, base.AppendPoint, PerFrameSettings);
     }
References Film.AddKeyFrame(), Film.AddSequence(), Film.AddSequences(), Film.AppendKeyFrame(), Film.AppendKeyFrames(), Film.AppendSequence(), Film.AppendSequences(), CreateCritters(), CreateDryad(), CreateOgre(), CreatePortal(), DryadAlertEmote(), DryadAttack(), DryadConfusedEmote(), DryadInteract(), DryadLookLeft(), DryadLookRight(), DryadPortalFade(), DryadPortalKnock(), DryadStand(), DryadWalk(), OgreLookLeft(), OgreStand(), OgreSwingSound(), PerFrameSettings(), RemoveEnemyDamage(), RestoreEnemyDamage(), SpawnGoblin(), SpawnJavalinThrower(), and SpawnWitherBeast().