Terraria: System.Data.DataRelation.Create
Create()
void System.Data.DataRelation.Create (string relationName, DataColumn[] parentColumns, DataColumn[] childColumns, bool createConstraints) inline private
Definition at line 524 of file DataRelation.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataRelation.Create|INFO> {0}, relationName='{1}', createConstraints={2}", ObjectID, relationName, createConstraints);
        try
        {
            _parentKey = new DataKey(parentColumns, copyColumns: true);
            _childKey = new DataKey(childColumns, copyColumns: true);
            if (parentColumns.Length != childColumns.Length)
            {
                throw ExceptionBuilder.KeyLengthMismatch();
            }
            for (int i = 0; i < parentColumns.Length; i++)
            {
                if (parentColumns[i].Table.DataSet == null || childColumns[i].Table.DataSet == null)
                {
                    throw ExceptionBuilder.ParentOrChildColumnsDoNotHaveDataSet();
                }
            }
            CheckState();
            _relationName = ((relationName == null) ? "" : relationName);
            _createConstraints = createConstraints;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataRelation._childKey, System.Data.DataRelation._createConstraints, System.Data.DataRelation._parentKey, System.Data.DataRelation._relationName, System.Data.DataRelation.CheckState(), System.Data.ExceptionBuilder.KeyLengthMismatch(), System.Data.DataCommonEventSource.Log, System.Data.DataRelation.ObjectID, and System.Data.ExceptionBuilder.ParentOrChildColumnsDoNotHaveDataSet().
Referenced by System.Data.DataRelation.DataRelation(), and System.Data.DataRelation.DataRelation().