Terraria: System.Data.DataRelation.CheckNestedRelations
CheckNestedRelations()
void System.Data.DataRelation.CheckNestedRelations () inline package
Definition at line 446 of file DataRelation.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataRelation.CheckNestedRelations|INFO> {0}", ObjectID);
        if (ChildTable == ParentTable)
        {
            if (string.Compare(ChildTable.TableName, ChildTable.DataSet.DataSetName, ignoreCase: true, ChildTable.DataSet.Locale) == 0)
            {
                throw ExceptionBuilder.SelfnestedDatasetConflictingName(ChildTable.TableName);
            }
            return;
        }
        List<DataTable> list = new List<DataTable>();
        list.Add(ChildTable);
        for (int i = 0; i < list.Count; i++)
        {
            DataRelation[] nestedParentRelations = list[i].NestedParentRelations;
            DataRelation[] array = nestedParentRelations;
            foreach (DataRelation dataRelation in array)
            {
                if (dataRelation.ParentTable == ChildTable && dataRelation.ChildTable != ChildTable)
                {
                    throw ExceptionBuilder.LoopInNestedRelations(ChildTable.TableName);
                }
                if (!list.Contains(dataRelation.ParentTable))
                {
                    list.Add(dataRelation.ParentTable);
                }
            }
        }
    }
References System.array, System.Data.DataRelation.ChildTable, System.list, System.Data.DataCommonEventSource.Log, System.Data.ExceptionBuilder.LoopInNestedRelations(), System.Data.DataRelation.ObjectID, System.Data.DataRelation.ParentTable, and System.Data.ExceptionBuilder.SelfnestedDatasetConflictingName().
Referenced by System.Data.DataRelationCollection.DataSetRelationCollection.AddCore().