Terraria: System.Data.DataRelation.CheckState
CheckState()
void System.Data.DataRelation.CheckState () inline package
Definition at line 487 of file DataRelation.cs.
    {
        if (_dataSet != null)
        {
            return;
        }
        _parentKey.CheckState();
        _childKey.CheckState();
        if (_parentKey.Table.DataSet != _childKey.Table.DataSet)
        {
            throw ExceptionBuilder.RelationDataSetMismatch();
        }
        if (_childKey.ColumnsEqual(_parentKey))
        {
            throw ExceptionBuilder.KeyColumnsIdentical();
        }
        for (int i = 0; i < _parentKey.ColumnsReference.Length; i++)
        {
            if (_parentKey.ColumnsReference[i].DataType != _childKey.ColumnsReference[i].DataType || (_parentKey.ColumnsReference[i].DataType == typeof(DateTime) && _parentKey.ColumnsReference[i].DateTimeMode != _childKey.ColumnsReference[i].DateTimeMode && (_parentKey.ColumnsReference[i].DateTimeMode & _childKey.ColumnsReference[i].DateTimeMode) != DataSetDateTime.Unspecified))
            {
                throw ExceptionBuilder.ColumnsTypeMismatch();
            }
        }
    }
References System.Data.DataRelation._childKey, System.Data.DataRelation._dataSet, System.Data.DataRelation._parentKey, System.Data.DataKey.CheckState(), System.Data.DataKey.ColumnsEqual(), System.Data.DataKey.ColumnsReference, System.Data.ExceptionBuilder.ColumnsTypeMismatch(), System.Data.DataTable.DataSet, System.Data.DataColumn.DataType, System.Data.DataColumn.DateTimeMode, System.Data.ExceptionBuilder.KeyColumnsIdentical(), System.Data.ExceptionBuilder.RelationDataSetMismatch(), and System.Data.DataKey.Table.
Referenced by System.Data.DataRelationCollection.DataSetRelationCollection.AddCore(), System.Data.DataRelationCollection.AddCore(), System.Data.DataRelation.CheckStateForProperty(), and System.Data.DataRelation.Create().