Terraria: System.Data.DataRelation.ValidateMultipleNestedRelations
ValidateMultipleNestedRelations()
void System.Data.DataRelation.ValidateMultipleNestedRelations () inline package
Definition at line 598 of file DataRelation.cs.
    {
        if (!Nested || !CheckMultipleNested || ChildTable.NestedParentRelations.Length == 0)
        {
            return;
        }
        DataColumn[] childColumns = ChildColumns;
        if (childColumns.Length != 1 || !IsAutoGenerated(childColumns[0]))
        {
            throw ExceptionBuilder.TableCantBeNestedInTwoTables(ChildTable.TableName);
        }
        if (!XmlTreeGen.AutoGenerated(this))
        {
            throw ExceptionBuilder.TableCantBeNestedInTwoTables(ChildTable.TableName);
        }
        foreach (Constraint constraint in ChildTable.Constraints)
        {
            if (constraint is ForeignKeyConstraint)
            {
                ForeignKeyConstraint fk = (ForeignKeyConstraint)constraint;
                if (!XmlTreeGen.AutoGenerated(fk, checkRelation: true))
                {
                    throw ExceptionBuilder.TableCantBeNestedInTwoTables(ChildTable.TableName);
                }
            }
            else
            {
                UniqueConstraint unique = (UniqueConstraint)constraint;
                if (!XmlTreeGen.AutoGenerated(unique))
                {
                    throw ExceptionBuilder.TableCantBeNestedInTwoTables(ChildTable.TableName);
                }
            }
        }
    }
References System.Data.XmlTreeGen.AutoGenerated(), System.Data.DataRelation.CheckMultipleNested, System.Data.DataRelation.ChildColumns, System.Data.DataRelation.ChildTable, System.Data.DataRelation.IsAutoGenerated(), System.Data.DataRelation.Nested, and System.Data.ExceptionBuilder.TableCantBeNestedInTwoTables().
Referenced by System.Data.DataRelationCollection.AddCore().