Terraria: System.Runtime.Serialization.XmlSerializableWriter.EndWrite
EndWrite()
void System.Runtime.Serialization.XmlSerializableWriter.EndWrite () inline package
Definition at line 26 of file XmlSerializableWriter.cs.
    {
        if (_depth != 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.IXmlSerializableMissingEndElements, (_obj == null) ? string.Empty : DataContract.GetClrTypeFullName(_obj.GetType()))));
        }
        _obj = null;
    }
References System.Runtime.Serialization.XmlSerializableWriter._depth, System.Runtime.Serialization.XmlSerializableWriter._obj, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.IXmlSerializableMissingEndElements, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().