Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicListener.MsQuicListener
MsQuicListener()
System.Net.Quic.Implementations.MsQuic.MsQuicListener.MsQuicListener (QuicListenerOptions options) inline package
Definition at line 74 of file MsQuicListener.cs.
    {
        if (options.ListenEndPoint == null)
        {
            throw new ArgumentNullException("ListenEndPoint");
        }
        _state = new State(options);
        _stateHandle = GCHandle.Alloc(_state);
        try
        {
            uint status = MsQuicApi.Api.ListenerOpenDelegate(MsQuicApi.Api.Registration, s_listenerDelegate, GCHandle.ToIntPtr(_stateHandle), out _state.Handle);
            QuicExceptionHelpers.ThrowIfFailed(status, "ListenerOpen failed.");
        }
        catch
        {
            _stateHandle.Free();
            throw;
        }
        _state.TraceId = MsQuicTraceHelper.GetTraceId(_state.Handle);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{_state.TraceId} Listener created", ".ctor");
        }
        _listenEndPoint = Start(options);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{_state.TraceId} Listener started", ".ctor");
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicListener._listenEndPoint, System.Net.Quic.Implementations.MsQuic.MsQuicListener._state, System.Net.Quic.Implementations.MsQuic.MsQuicListener._stateHandle, System.Runtime.InteropServices.GCHandle.Alloc(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Runtime.InteropServices.GCHandle.Free(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicTraceHelper.GetTraceId(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.State.Handle, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.options, System.Net.Quic.Implementations.MsQuic.MsQuicListener.s_listenerDelegate, System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start(), System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(), and System.Runtime.InteropServices.GCHandle.ToIntPtr().