Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicListener.NativeCallbackHandler
NativeCallbackHandler()
static unsafe uint System.Net.Quic.Implementations.MsQuic.MsQuicListener.NativeCallbackHandler (IntPtr listener, IntPtr context, ref MsQuicNativeMethods::ListenerEvent evt) inline static private
Definition at line 182 of file MsQuicListener.cs.
    {
        State state = (State)GCHandle.FromIntPtr(context).Target;
        if (evt.Type != 0)
        {
            return 2151743491u;
        }
        SafeMsQuicConnectionHandle safeMsQuicConnectionHandle = null;
        MsQuicConnection msQuicConnection = null;
        try
        {
            ref MsQuicNativeMethods.NewConnectionInfo reference = ref *evt.Data.NewConnection.Info;
            IPEndPoint localEndPoint = MsQuicAddressHelpers.INetToIPEndPoint(ref *(MsQuicNativeMethods.SOCKADDR_INET*)(void*)reference.LocalAddress);
            IPEndPoint remoteEndPoint = MsQuicAddressHelpers.INetToIPEndPoint(ref *(MsQuicNativeMethods.SOCKADDR_INET*)(void*)reference.RemoteAddress);
            string targetHost = string.Empty;
            if (reference.ServerNameLength > 0 && reference.ServerName != IntPtr.Zero)
            {
                targetHost = Marshal.PtrToStringAnsi(reference.ServerName, reference.ServerNameLength);
            }
            SafeMsQuicConfigurationHandle safeMsQuicConfigurationHandle = state.ConnectionConfiguration;
            if (safeMsQuicConfigurationHandle == null)
            {
                try
                {
                    safeMsQuicConfigurationHandle = SafeMsQuicConfigurationHandle.Create(state.ConnectionOptions, state.AuthenticationOptions, targetHost);
                }
                catch (Exception ex)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Error(state, $"[Listener#{state.GetHashCode()}] Exception occurred during creating configuration in connection callback: {ex}", "NativeCallbackHandler");
                    }
                }
                if (safeMsQuicConfigurationHandle == null)
                {
                    return 2151743491u;
                }
            }
            safeMsQuicConnectionHandle = new SafeMsQuicConnectionHandle(evt.Data.NewConnection.Connection);
            uint status = MsQuicApi.Api.ConnectionSetConfigurationDelegate(safeMsQuicConnectionHandle, safeMsQuicConfigurationHandle);
            if (MsQuicStatusHelper.SuccessfulStatusCode(status))
            {
                msQuicConnection = new MsQuicConnection(localEndPoint, remoteEndPoint, state, safeMsQuicConnectionHandle, state.AuthenticationOptions.ClientCertificateRequired, state.AuthenticationOptions.CertificateRevocationCheckMode, state.AuthenticationOptions.RemoteCertificateValidationCallback);
                msQuicConnection.SetNegotiatedAlpn(reference.NegotiatedAlpn, reference.NegotiatedAlpnLength);
                if (!state.PendingConnections.TryAdd(safeMsQuicConnectionHandle.DangerousGetHandle(), msQuicConnection))
                {
                    msQuicConnection.Dispose();
                }
                return 0u;
            }
        }
        catch (Exception ex2)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(state, $"[Listener#{state.GetHashCode()}] Exception occurred during handling {evt.Type} connection callback: {ex2}", "NativeCallbackHandler");
            }
        }
        safeMsQuicConnectionHandle?.SetHandleAsInvalid();
        msQuicConnection?.Dispose();
        return 2151743491u;
    }
References System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.Net.NetEventSource.Error(), System.Runtime.InteropServices.GCHandle.FromIntPtr(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.INetToIPEndPoint(), System.Net.NetEventSource.Log, System.Runtime.InteropServices.Marshal.PtrToStringAnsi(), System.state, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicStatusHelper.SuccessfulStatusCode(), and System.IntPtr.Zero.