Terraria: System.IO.MemoryMappedFiles.MemoryMappedView.CreateView
CreateView()
static MemoryMappedView System.IO.MemoryMappedFiles.MemoryMappedView.CreateView (SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, long offset, long size) inline static
Definition at line 60 of file MemoryMappedView.cs.
    {
        ValidateSizeAndOffset(size, offset, GetSystemPageAllocationGranularity(), out var newSize, out var extraMemNeeded, out var newOffset);
        global::Interop.CheckForAvailableVirtualMemory(newSize);
        SafeMemoryMappedViewHandle safeMemoryMappedViewHandle = global::Interop.MapViewOfFile(memMappedFileHandle, MemoryMappedFile.GetFileMapAccess(access), newOffset, new UIntPtr(newSize));
        if (safeMemoryMappedViewHandle.IsInvalid)
        {
            safeMemoryMappedViewHandle.Dispose();
            throw System.IO.Win32Marshal.GetExceptionForLastWin32Error();
        }
        global::Interop.Kernel32.MEMORY_BASIC_INFORMATION lpBuffer = default(global::Interop.Kernel32.MEMORY_BASIC_INFORMATION);
        global::Interop.Kernel32.VirtualQuery(safeMemoryMappedViewHandle, ref lpBuffer, (UIntPtr)(ulong)Marshal.SizeOf(lpBuffer));
        ulong num = (ulong)lpBuffer.RegionSize;
        if ((lpBuffer.State & 0x2000u) != 0 || num < newSize)
        {
            IntPtr intPtr = global::Interop.VirtualAlloc(safeMemoryMappedViewHandle, (UIntPtr)((newSize != 0L) ? newSize : num), 4096, MemoryMappedFile.GetPageAccess(access));
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            if (safeMemoryMappedViewHandle.IsInvalid)
            {
                safeMemoryMappedViewHandle.Dispose();
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError);
            }
            lpBuffer = default(global::Interop.Kernel32.MEMORY_BASIC_INFORMATION);
            global::Interop.Kernel32.VirtualQuery(safeMemoryMappedViewHandle, ref lpBuffer, (UIntPtr)(ulong)Marshal.SizeOf(lpBuffer));
            num = (ulong)lpBuffer.RegionSize;
        }
        if (size == 0L)
        {
            size = (long)num - extraMemNeeded;
        }
        safeMemoryMappedViewHandle.Initialize((ulong)(size + extraMemNeeded));
        return new MemoryMappedView(safeMemoryMappedViewHandle, extraMemNeeded, size, access);
    }
References System.IO.MemoryMappedFiles.MemoryMappedView.MemoryMappedView(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.IO.MemoryMappedFiles.MemoryMappedFile.GetFileMapAccess(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.IO.MemoryMappedFiles.MemoryMappedFile.GetPageAccess(), System.IO.MemoryMappedFiles.MemoryMappedView.GetSystemPageAllocationGranularity(), System.Runtime.InteropServices.SafeBuffer.Initialize(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.L, System.newSize, System.offset, System.Runtime.InteropServices.Marshal.SizeOf(), and System.IO.MemoryMappedFiles.MemoryMappedView.ValidateSizeAndOffset().
Referenced by System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewAccessor(), and System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream().