Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start
Start()
unsafe IPEndPoint System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start (QuicListenerOptions options) inline private
Definition at line 143 of file MsQuicListener.cs.
    {
        List<SslApplicationProtocol> applicationProtocols = options.ServerAuthenticationOptions.ApplicationProtocols;
        IPEndPoint listenEndPoint = options.ListenEndPoint;
        MsQuicNativeMethods.SOCKADDR_INET localAddress = MsQuicAddressHelpers.IPEndPointToINet(listenEndPoint);
        MemoryHandle[] handles = null;
        MsQuicNativeMethods.QuicBuffer[] buffers = null;
        uint status;
        try
        {
            MsQuicAlpnHelper.Prepare(applicationProtocols, out handles, out buffers);
            status = MsQuicApi.Api.ListenerStartDelegate(_state.Handle, (MsQuicNativeMethods.QuicBuffer*)(void*)Marshal.UnsafeAddrOfPinnedArrayElement(buffers, 0), (uint)applicationProtocols.Count, ref localAddress);
        }
        catch
        {
            _stateHandle.Free();
            throw;
        }
        finally
        {
            MsQuicAlpnHelper.Return(ref handles, ref buffers);
        }
        QuicExceptionHelpers.ThrowIfFailed(status, "ListenerStart failed.");
        MsQuicNativeMethods.SOCKADDR_INET inetAddress = MsQuicParameterHelpers.GetINetParam(MsQuicApi.Api, _state.Handle, QUIC_PARAM_LEVEL.LISTENER, 0u);
        return MsQuicAddressHelpers.INetToIPEndPoint(ref inetAddress);
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicListener._state, System.Net.Quic.Implementations.MsQuic.MsQuicListener._stateHandle, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.buffers, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.InteropServices.GCHandle.Free(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicParameterHelpers.GetINetParam(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.State.Handle, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.INetToIPEndPoint(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.IPEndPointToINet(), System.options, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Prepare(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAlpnHelper.Return(), System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(), and System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement().
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicListener.MsQuicListener().