Terraria: System.Net.WebSockets.WebSocketBase.OnBackgroundTaskException
OnBackgroundTaskException()
void System.Net.WebSockets.WebSocketBase.OnBackgroundTaskException (Exception exception) inline private
Definition at line 1605 of file WebSocketBase.cs.
    {
        if (Interlocked.CompareExchange(ref _pendingException, exception, null) == null)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, exception.ToString(), "OnBackgroundTaskException");
            }
            Abort();
        }
    }
References System.Net.WebSockets.WebSocketBase._pendingException, System.Net.WebSockets.WebSocketBase.Abort(), System.Threading.Interlocked.CompareExchange(), System.Net.NetEventSource.Error(), System.exception, and System.Net.NetEventSource.Log.