Terraria: System.Net.WebSockets.WebSocketBase.StartOnCloseCompleted
StartOnCloseCompleted()
async Task< bool > System.Net.WebSockets.WebSocketBase.StartOnCloseCompleted (bool thisLockTakenSnapshot, bool sessionHandleLockTakenSnapshot, CancellationToken cancellationToken) inline private
Definition at line 1084 of file WebSocketBase.cs.
    {
        if (WebSocket.IsStateTerminal(_state))
        {
            return false;
        }
        _state = WebSocketState.Closed;
        if (_innerStreamAsWebSocketStream != null)
        {
            bool lockTaken = thisLockTakenSnapshot;
            bool sessionHandleLockTaken = sessionHandleLockTakenSnapshot;
            try
            {
                if (_closeNetworkConnectionTask == null)
                {
                    _closeNetworkConnectionTask = _innerStreamAsWebSocketStream.CloseNetworkConnectionAsync(cancellationToken);
                }
                if (lockTaken && sessionHandleLockTaken)
                {
                    ReleaseLocks(ref lockTaken, ref sessionHandleLockTaken);
                }
                else if (lockTaken)
                {
                    ReleaseLock(_thisLock, ref lockTaken);
                }
                await _closeNetworkConnectionTask.SuppressContextFlow();
            }
            catch (Exception ex)
            {
                if (!CanHandleExceptionDuringClose(ex))
                {
                    ThrowIfConvertibleException("StartOnCloseCompleted", ex, cancellationToken, cancellationToken.IsCancellationRequested);
                    throw;
                }
            }
        }
        return true;
    }
References System.Net.WebSockets.WebSocketBase._closeNetworkConnectionTask, System.Net.WebSockets.WebSocketBase._innerStreamAsWebSocketStream, System.Net.WebSockets.WebSocketBase._state, System.Net.WebSockets.WebSocketBase._thisLock, System.cancellationToken, System.Net.WebSockets.WebSocketBase.CanHandleExceptionDuringClose(), System.Net.WebSockets.WebSocketBase.IWebSocketStream.CloseNetworkConnectionAsync(), System.Net.WebSockets.WebSocket.IsStateTerminal(), System.Net.WebSockets.WebSocketBase.ReleaseLock(), System.Net.WebSockets.WebSocketBase.ReleaseLocks(), and System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException().
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), and System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process().