Terraria: System.Net.WebSockets.WebSocketBase.TakeLocks
TakeLocks()
void System.Net.WebSockets.WebSocketBase.TakeLocks (ref bool thisLockTaken, ref bool sessionHandleLockTaken) inline private
Definition at line 1347 of file WebSocketBase.cs.
    {
        Monitor.Enter(SessionHandle, ref sessionHandleLockTaken);
        Monitor.Enter(_thisLock, ref thisLockTaken);
    }
References System.Net.WebSockets.WebSocketBase._thisLock, System.Threading.Monitor.Enter(), and System.Net.WebSockets.WebSocketBase.SessionHandle.
Referenced by System.Net.WebSockets.WebSocketBase.Abort(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.Dispose(), and System.Net.WebSockets.WebSocketBase.ResetFlagsAndTakeLocks().