Terraria: System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore
ReceiveAsyncCore()
async Task< WebSocketReceiveResult > System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore (ArraySegment< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 779 of file WebSocketBase.cs.
    {
        ThrowIfPendingException();
        ThrowIfDisposed();
        WebSocket.ThrowOnInvalidState(State, WebSocketState.Open, WebSocketState.CloseSent);
        bool ownsCancellationTokenSource = false;
        CancellationToken linkedCancellationToken = CancellationToken.None;
        WebSocketReceiveResult webSocketReceiveResult;
        try
        {
            ownsCancellationTokenSource = _receiveOutstandingOperationHelper.TryStartOperation(cancellationToken, out linkedCancellationToken);
            if (!ownsCancellationTokenSource)
            {
                lock (_thisLock)
                {
                    if (_closeAsyncStartedReceive)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.net_WebSockets_ReceiveAsyncDisallowedAfterCloseAsync, "CloseAsync", "CloseOutputAsync"));
                    }
                    throw new InvalidOperationException(System.SR.Format(System.SR.net_Websockets_AlreadyOneOutstandingOperation, "ReceiveAsync"));
                }
            }
            EnsureReceiveOperation();
            webSocketReceiveResult = await _receiveOperation.Process(buffer, linkedCancellationToken).SuppressContextFlow();
            if (System.Net.NetEventSource.Log.IsEnabled() && webSocketReceiveResult.Count > 0)
            {
                System.Net.NetEventSource.DumpBuffer(this, buffer.Array, buffer.Offset, webSocketReceiveResult.Count, "ReceiveAsyncCore");
            }
        }
        catch (Exception exception)
        {
            bool isCancellationRequested = linkedCancellationToken.IsCancellationRequested;
            Abort();
            ThrowIfConvertibleException("ReceiveAsync", exception, cancellationToken, isCancellationRequested);
            throw;
        }
        finally
        {
            _receiveOutstandingOperationHelper.CompleteOperation(ownsCancellationTokenSource);
        }
        return webSocketReceiveResult;
    }
References System.Net.WebSockets.WebSocketBase._closeAsyncStartedReceive, System.Net.WebSockets.WebSocketBase._receiveOperation, System.Net.WebSockets.WebSocketBase._receiveOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._thisLock, System.Net.WebSockets.WebSocketBase.Abort(), System.buffer, System.cancellationToken, System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CompleteOperation(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.NetEventSource.DumpBuffer(), System.Net.WebSockets.WebSocketBase.EnsureReceiveOperation(), System.exception, System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_Websockets_AlreadyOneOutstandingOperation, System.SR.net_WebSockets_ReceiveAsyncDisallowedAfterCloseAsync, System.Threading.CancellationToken.None, System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(), System.Net.WebSockets.WebSocketBase.ThrowIfDisposed(), System.Net.WebSockets.WebSocketBase.ThrowIfPendingException(), System.Net.WebSockets.WebSocket.ThrowOnInvalidState(), and System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.TryStartOperation().
Referenced by System.Net.WebSockets.WebSocketBase.ReceiveAsync().