Terraria: System.Net.WebSockets.WebSocketBase.ThrowIfPendingException
ThrowIfPendingException()
void System.Net.WebSockets.WebSocketBase.ThrowIfPendingException () inline private
Definition at line 1617 of file WebSocketBase.cs.
    {
        Exception ex = Interlocked.Exchange(ref _pendingException, null);
        if (ex != null)
        {
            throw new WebSocketException(WebSocketError.Faulted, ex);
        }
    }
References System.Net.WebSockets.WebSocketBase._pendingException, and System.Threading.Interlocked.Exchange().
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CreateBuffer(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.Initialize(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process(), System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(), System.Net.WebSockets.WebSocketBase.SendAsyncCore(), and System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.ShouldContinue().