Terraria: System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore
CloseOutputAsyncCore()
async Task System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore (WebSocketCloseStatus closeStatus, string statusDescription, CancellationToken cancellationToken) inline private
Definition at line 964 of file WebSocketBase.cs.
    {
        ThrowIfPendingException();
        if (WebSocket.IsStateTerminal(State))
        {
            return;
        }
        ThrowIfDisposed();
        bool thisLockTaken = false;
        bool sessionHandleLockTaken = false;
        bool needToCompleteSendOperation = false;
        bool ownsCloseOutputCancellationTokenSource = false;
        bool ownsSendCancellationTokenSource = false;
        CancellationToken linkedCancellationToken = CancellationToken.None;
        try
        {
            TakeLocks(ref thisLockTaken, ref sessionHandleLockTaken);
            ThrowIfPendingException();
            ThrowIfDisposed();
            if (WebSocket.IsStateTerminal(State))
            {
                return;
            }
            WebSocket.ThrowOnInvalidState(State, WebSocketState.Open, WebSocketState.CloseReceived);
            ownsCloseOutputCancellationTokenSource = _closeOutputOutstandingOperationHelper.TryStartOperation(cancellationToken, out linkedCancellationToken);
            if (!ownsCloseOutputCancellationTokenSource)
            {
                Task closeOutputTask = _closeOutputTask;
                if (closeOutputTask != null)
                {
                    ReleaseLocks(ref thisLockTaken, ref sessionHandleLockTaken);
                    await closeOutputTask.SuppressContextFlow();
                    TakeLocks(ref thisLockTaken, ref sessionHandleLockTaken);
                }
                return;
            }
            needToCompleteSendOperation = true;
            while (true)
            {
                bool flag;
                ownsSendCancellationTokenSource = (flag = _sendOutstandingOperationHelper.TryStartOperation(cancellationToken, out linkedCancellationToken));
                if (flag)
                {
                    break;
                }
                if (_keepAliveTask != null)
                {
                    Task keepAliveTask = _keepAliveTask;
                    ReleaseLocks(ref thisLockTaken, ref sessionHandleLockTaken);
                    await keepAliveTask.SuppressContextFlow();
                    TakeLocks(ref thisLockTaken, ref sessionHandleLockTaken);
                    ThrowIfPendingException();
                    _sendOutstandingOperationHelper.CompleteOperation(ownsSendCancellationTokenSource);
                    continue;
                }
                throw new InvalidOperationException(System.SR.Format(System.SR.net_Websockets_AlreadyOneOutstandingOperation, "SendAsync"));
            }
            EnsureCloseOutputOperation();
            _closeOutputOperation.CloseStatus = closeStatus;
            _closeOutputOperation.CloseReason = statusDescription;
            _closeOutputTask = _closeOutputOperation.Process(null, linkedCancellationToken);
            ReleaseLocks(ref thisLockTaken, ref sessionHandleLockTaken);
            await _closeOutputTask.SuppressContextFlow();
            TakeLocks(ref thisLockTaken, ref sessionHandleLockTaken);
            if (OnCloseOutputCompleted())
            {
                bool flag2;
                try
                {
                    flag2 = await StartOnCloseCompleted(thisLockTaken, sessionHandleLockTaken, linkedCancellationToken).SuppressContextFlow();
                }
                catch (Exception)
                {
                    ResetFlagsAndTakeLocks(ref thisLockTaken, ref sessionHandleLockTaken);
                    throw;
                }
                if (flag2)
                {
                    ResetFlagsAndTakeLocks(ref thisLockTaken, ref sessionHandleLockTaken);
                    FinishOnCloseCompleted();
                }
            }
        }
        catch (Exception exception)
        {
            bool isCancellationRequested = linkedCancellationToken.IsCancellationRequested;
            Abort();
            ThrowIfConvertibleException("CloseOutputAsync", exception, cancellationToken, isCancellationRequested);
            throw;
        }
        finally
        {
            _closeOutputOutstandingOperationHelper.CompleteOperation(ownsCloseOutputCancellationTokenSource);
            if (needToCompleteSendOperation)
            {
                _sendOutstandingOperationHelper.CompleteOperation(ownsSendCancellationTokenSource);
            }
            _closeOutputTask = null;
            ReleaseLocks(ref thisLockTaken, ref sessionHandleLockTaken);
        }
    }
References System.Net.WebSockets.WebSocketBase._closeOutputOperation, System.Net.WebSockets.WebSocketBase._closeOutputOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._closeOutputTask, System.Net.WebSockets.WebSocketBase._keepAliveTask, System.Net.WebSockets.WebSocketBase._sendOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase.Abort(), System.cancellationToken, System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CompleteOperation(), System.Net.WebSockets.WebSocketBase.EnsureCloseOutputOperation(), System.exception, System.Net.WebSockets.WebSocketBase.FinishOnCloseCompleted(), System.SR.Format(), System.Net.WebSockets.WebSocket.IsStateTerminal(), System.SR.net_Websockets_AlreadyOneOutstandingOperation, System.Threading.CancellationToken.None, System.Net.WebSockets.WebSocketBase.OnCloseOutputCompleted(), System.Net.WebSockets.WebSocketBase.ReleaseLocks(), System.Net.WebSockets.WebSocketBase.ResetFlagsAndTakeLocks(), System.Net.WebSockets.WebSocketBase.StartOnCloseCompleted(), System.Net.WebSockets.WebSocketBase.TakeLocks(), System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(), System.Net.WebSockets.WebSocketBase.ThrowIfDisposed(), System.Net.WebSockets.WebSocketBase.ThrowIfPendingException(), System.Net.WebSockets.WebSocket.ThrowOnInvalidState(), and System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.TryStartOperation().
Referenced by System.Net.WebSockets.WebSocketBase.CloseOutputAsync().