Terraria: System.Net.WebSockets.WebSocketBase.ThrowIfDisposed
ThrowIfDisposed()
void System.Net.WebSockets.WebSocketBase.ThrowIfDisposed () inline private
Definition at line 1626 of file WebSocketBase.cs.
    {
        if (_isDisposed)
        {
            throw new ObjectDisposedException(GetType().FullName);
        }
    }
References System.Net.WebSockets.WebSocketBase._isDisposed, and System.FullName.
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CreateBuffer(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.Initialize(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.Initialize(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process(), System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(), System.Net.WebSockets.WebSocketBase.SendAsyncCore(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.ShouldContinue(), and System.Net.WebSockets.WebSocketBase.StartOnCloseReceived().