Terraria: System.Net.WebSockets.WebSocketBase.WebSocketBase
WebSocketBase()
System.Net.WebSockets.WebSocketBase.WebSocketBase (Stream innerStream, string subProtocol, TimeSpan keepAliveInterval, WebSocketBuffer internalBuffer) inline protected
Definition at line 739 of file WebSocketBase.cs.
    {
        HttpWebSocket.ValidateInnerStream(innerStream);
        HttpWebSocket.ValidateOptions(subProtocol, internalBuffer.ReceiveBufferSize, internalBuffer.SendBufferSize, keepAliveInterval);
        _thisLock = new object();
        _innerStream = innerStream;
        _internalBuffer = internalBuffer;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Associate(this, _innerStream, ".ctor");
            System.Net.NetEventSource.Associate(this, _internalBuffer, ".ctor");
        }
        _closeOutstandingOperationHelper = new OutstandingOperationHelper();
        _closeOutputOutstandingOperationHelper = new OutstandingOperationHelper();
        _receiveOutstandingOperationHelper = new OutstandingOperationHelper();
        _sendOutstandingOperationHelper = new OutstandingOperationHelper();
        _state = WebSocketState.Open;
        _subProtocol = subProtocol;
        _sendFrameThrottle = new SemaphoreSlim(1, 1);
        _closeStatus = null;
        _closeStatusDescription = null;
        _innerStreamAsWebSocketStream = innerStream as IWebSocketStream;
        if (_innerStreamAsWebSocketStream != null)
        {
            _innerStreamAsWebSocketStream.SwitchToOpaqueMode(this);
        }
        _keepAliveTracker = KeepAliveTracker.Create(keepAliveInterval);
    }
References System.Net.WebSockets.WebSocketBase._closeOutputOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._closeOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._closeStatus, System.Net.WebSockets.WebSocketBase._closeStatusDescription, System.Net.WebSockets.WebSocketBase._innerStream, System.Net.WebSockets.WebSocketBase._innerStreamAsWebSocketStream, System.Net.WebSockets.WebSocketBase._internalBuffer, System.Net.WebSockets.WebSocketBase._keepAliveTracker, System.Net.WebSockets.WebSocketBase._receiveOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._sendFrameThrottle, System.Net.WebSockets.WebSocketBase._sendOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._state, System.Net.WebSockets.WebSocketBase._subProtocol, System.Net.WebSockets.WebSocketBase._thisLock, System.Net.NetEventSource.Associate(), System.Net.WebSockets.WebSocketBase.KeepAliveTracker.Create(), System.Net.NetEventSource.Log, System.Net.WebSockets.WebSocketBase.IWebSocketStream.SwitchToOpaqueMode(), System.Net.WebSockets.HttpWebSocket.ValidateInnerStream(), and System.Net.WebSockets.HttpWebSocket.ValidateOptions().
Referenced by System.Net.WebSockets.WebSocketBase.OnKeepAlive().