Terraria: System.Net.WebSockets.WebSocketBase.CleanUp
CleanUp()
void System.Net.WebSockets.WebSocketBase.CleanUp () inline private
Definition at line 1552 of file WebSocketBase.cs.
    {
        if (_cleanedUp)
        {
            return;
        }
        _cleanedUp = true;
        if (SessionHandle != null)
        {
            SessionHandle.Dispose();
        }
        if (_internalBuffer != null)
        {
            _internalBuffer.Dispose(State);
        }
        if (_receiveOutstandingOperationHelper != null)
        {
            _receiveOutstandingOperationHelper.Dispose();
        }
        if (_sendOutstandingOperationHelper != null)
        {
            _sendOutstandingOperationHelper.Dispose();
        }
        if (_closeOutputOutstandingOperationHelper != null)
        {
            _closeOutputOutstandingOperationHelper.Dispose();
        }
        if (_closeOutstandingOperationHelper != null)
        {
            _closeOutstandingOperationHelper.Dispose();
        }
        if (_innerStream != null)
        {
            try
            {
                _innerStream.Close();
            }
            catch (ObjectDisposedException)
            {
            }
            catch (IOException)
            {
            }
            catch (SocketException)
            {
            }
            catch (HttpListenerException)
            {
            }
        }
        _keepAliveTracker.Dispose();
    }
References System.Net.WebSockets.WebSocketBase._cleanedUp, System.Net.WebSockets.WebSocketBase._closeOutputOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._closeOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._innerStream, System.Net.WebSockets.WebSocketBase._internalBuffer, System.Net.WebSockets.WebSocketBase._keepAliveTracker, System.Net.WebSockets.WebSocketBase._receiveOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._sendOutstandingOperationHelper, System.IO.Stream.Close(), System.Net.WebSockets.WebSocketBase.KeepAliveTracker.Dispose(), System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.Dispose(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.WebSockets.WebSocketBuffer.Dispose(), and System.Net.WebSockets.WebSocketBase.SessionHandle.
Referenced by System.Net.WebSockets.WebSocketBase.Abort(), System.Net.WebSockets.WebSocketBase.Dispose(), and System.Net.WebSockets.WebSocketBase.FinishOnCloseCompleted().