Terraria: System.Net.WebSockets.WebSocketBase.SendFrameAsync
SendFrameAsync()
async Task System.Net.WebSockets.WebSocketBase.SendFrameAsync (IList< ArraySegment< byte > > sendBuffers, CancellationToken cancellationToken) inline private
Definition at line 889 of file WebSocketBase.cs.
    {
        bool sendFrameLockTaken = false;
        try
        {
            await _sendFrameThrottle.WaitAsync(cancellationToken).SuppressContextFlow();
            sendFrameLockTaken = true;
            if (sendBuffers.Count > 1 && _innerStreamAsWebSocketStream != null && _innerStreamAsWebSocketStream.SupportsMultipleWrite)
            {
                await _innerStreamAsWebSocketStream.MultipleWriteAsync(sendBuffers, cancellationToken).SuppressContextFlow();
                return;
            }
            foreach (ArraySegment<byte> sendBuffer in sendBuffers)
            {
                await _innerStream.WriteAsync(sendBuffer.Array, sendBuffer.Offset, sendBuffer.Count, cancellationToken).SuppressContextFlow();
            }
        }
        catch (ObjectDisposedException innerException)
        {
            throw new WebSocketException(WebSocketError.ConnectionClosedPrematurely, innerException);
        }
        catch (NotSupportedException innerException2)
        {
            throw new WebSocketException(WebSocketError.ConnectionClosedPrematurely, innerException2);
        }
        finally
        {
            if (sendFrameLockTaken)
            {
                _sendFrameThrottle.Release();
            }
        }
    }
References System.Net.WebSockets.WebSocketBase._innerStream, System.Net.WebSockets.WebSocketBase._innerStreamAsWebSocketStream, System.Net.WebSockets.WebSocketBase._sendFrameThrottle, System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.WebSockets.WebSocketBase.IWebSocketStream.MultipleWriteAsync(), System.Threading.SemaphoreSlim.Release(), System.Net.WebSockets.WebSocketBase.IWebSocketStream.SupportsMultipleWrite, System.Threading.SemaphoreSlim.WaitAsync(), and System.IO.Stream.WriteAsync().
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process().