Terraria: System.Net.WebSockets.WebSocketBase.OnKeepAlive
OnKeepAlive()
static async void System.Net.WebSockets.WebSocketBase.OnKeepAlive (object sender) inline static private
Definition at line 1674 of file WebSocketBase.cs.
    {
        WebSocketBase thisPtr = sender as WebSocketBase;
        bool lockTaken = false;
        CancellationToken linkedCancellationToken = CancellationToken.None;
        try
        {
            Monitor.Enter(thisPtr.SessionHandle, ref lockTaken);
            if (thisPtr._isDisposed || thisPtr._state != WebSocketState.Open || thisPtr._closeOutputTask != null || !thisPtr._keepAliveTracker.ShouldSendKeepAlive())
            {
                return;
            }
            bool ownsCancellationTokenSource = false;
            try
            {
                ownsCancellationTokenSource = thisPtr._sendOutstandingOperationHelper.TryStartOperation(CancellationToken.None, out linkedCancellationToken);
                if (ownsCancellationTokenSource)
                {
                    thisPtr.EnsureKeepAliveOperation();
                    thisPtr._keepAliveTask = thisPtr._keepAliveOperation.Process(null, linkedCancellationToken);
                    ReleaseLock(thisPtr.SessionHandle, ref lockTaken);
                    await thisPtr._keepAliveTask.SuppressContextFlow();
                }
            }
            finally
            {
                if (!lockTaken)
                {
                    Monitor.Enter(thisPtr.SessionHandle, ref lockTaken);
                }
                thisPtr._sendOutstandingOperationHelper.CompleteOperation(ownsCancellationTokenSource);
                thisPtr._keepAliveTask = null;
            }
            thisPtr._keepAliveTracker.ResetTimer();
        }
        catch (Exception exception)
        {
            try
            {
                thisPtr.ThrowIfConvertibleException("OnKeepAlive", exception, CancellationToken.None, linkedCancellationToken.IsCancellationRequested);
                throw;
            }
            catch (Exception exception2)
            {
                thisPtr.OnBackgroundTaskException(exception2);
            }
        }
        finally
        {
            ReleaseLock(thisPtr.SessionHandle, ref lockTaken);
        }
    }
References System.Net.WebSockets.WebSocketBase.WebSocketBase(), System.Threading.Monitor.Enter(), System.exception, System.Threading.CancellationToken.None, and System.Net.WebSockets.WebSocketBase.ReleaseLock().