Terraria: System.Net.WebSockets.WebSocketBase.SendAsyncCore
SendAsyncCore()
async Task System.Net.WebSockets.WebSocketBase.SendAsyncCore (ArraySegment< byte > buffer, WebSocketMessageType messageType, bool endOfMessage, CancellationToken cancellationToken) inline private
Definition at line 832 of file WebSocketBase.cs.
    {
        ThrowIfPendingException();
        ThrowIfDisposed();
        WebSocket.ThrowOnInvalidState(State, WebSocketState.Open, WebSocketState.CloseReceived);
        bool ownsCancellationTokenSource = false;
        CancellationToken linkedCancellationToken = CancellationToken.None;
        try
        {
            while (true)
            {
                bool flag;
                ownsCancellationTokenSource = (flag = _sendOutstandingOperationHelper.TryStartOperation(cancellationToken, out linkedCancellationToken));
                if (flag)
                {
                    break;
                }
                Task keepAliveTask;
                lock (SessionHandle)
                {
                    keepAliveTask = _keepAliveTask;
                    if (keepAliveTask == null)
                    {
                        _sendOutstandingOperationHelper.CompleteOperation(ownsCancellationTokenSource);
                        ownsCancellationTokenSource = (flag = _sendOutstandingOperationHelper.TryStartOperation(cancellationToken, out linkedCancellationToken));
                        if (flag)
{
                            break;
                        }
                        throw new InvalidOperationException(System.SR.Format(System.SR.net_Websockets_AlreadyOneOutstandingOperation, "SendAsync"));
                    }
                }
                await keepAliveTask.SuppressContextFlow();
                ThrowIfPendingException();
                _sendOutstandingOperationHelper.CompleteOperation(ownsCancellationTokenSource);
            }
            if (System.Net.NetEventSource.Log.IsEnabled() && buffer.Count > 0)
            {
                System.Net.NetEventSource.DumpBuffer(this, buffer.Array, buffer.Offset, buffer.Count, "SendAsyncCore");
            }
            EnsureSendOperation();
            _sendOperation.BufferType = GetBufferType(messageType, endOfMessage);
            await _sendOperation.Process(buffer, linkedCancellationToken).SuppressContextFlow();
        }
        catch (Exception exception)
        {
            bool isCancellationRequested = linkedCancellationToken.IsCancellationRequested;
            Abort();
            ThrowIfConvertibleException("SendAsync", exception, cancellationToken, isCancellationRequested);
            throw;
        }
        finally
        {
            _sendOutstandingOperationHelper.CompleteOperation(ownsCancellationTokenSource);
        }
    }
References System.Net.WebSockets.WebSocketBase._keepAliveTask, System.Net.WebSockets.WebSocketBase._sendOperation, System.Net.WebSockets.WebSocketBase._sendOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase.Abort(), System.buffer, System.cancellationToken, System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CompleteOperation(), System.Net.NetEventSource.DumpBuffer(), System.Net.WebSockets.WebSocketBase.EnsureSendOperation(), System.exception, System.SR.Format(), System.Net.WebSockets.WebSocketBase.GetBufferType(), System.Net.NetEventSource.Log, System.SR.net_Websockets_AlreadyOneOutstandingOperation, System.Threading.CancellationToken.None, System.Net.WebSockets.WebSocketBase.SessionHandle, System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(), System.Net.WebSockets.WebSocketBase.ThrowIfDisposed(), System.Net.WebSockets.WebSocketBase.ThrowIfPendingException(), System.Net.WebSockets.WebSocket.ThrowOnInvalidState(), and System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.TryStartOperation().
Referenced by System.Net.WebSockets.WebSocketBase.SendAsync().
0.0