Terraria: System.Net.WebSockets.WebSocketBase.SendAsync
SendAsync() [1/3]
override Task System.Net.WebSockets.WebSocketBase.SendAsync (ArraySegment< byte > buffer, WebSocketMessageType messageType, bool endOfMessage, CancellationToken cancellationToken) inline
Definition at line 822 of file WebSocketBase.cs.
    {
        if (messageType != WebSocketMessageType.Binary && messageType != 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_WebSockets_Argument_InvalidMessageType, messageType, "SendAsync", WebSocketMessageType.Binary, WebSocketMessageType.Text, "CloseOutputAsync"), "messageType");
        }
        System.Net.WebSockets.WebSocketValidate.ValidateArraySegment(buffer, "buffer");
        return SendAsyncCore(buffer, messageType, endOfMessage, cancellationToken);
    }
References System.buffer, System.cancellationToken, System.SR.Format(), System.SR.net_WebSockets_Argument_InvalidMessageType, System.Net.WebSockets.WebSocketBase.SendAsyncCore(), and System.Net.WebSockets.WebSocketValidate.ValidateArraySegment().