Terraria: System.Net.WebSockets.WebSocketBase.CloseAsyncCore
CloseAsyncCore()
async Task System.Net.WebSockets.WebSocketBase.CloseAsyncCore (WebSocketCloseStatus closeStatus, string statusDescription, CancellationToken cancellationToken) inline private
Definition at line 1134 of file WebSocketBase.cs.
    {
        ThrowIfPendingException();
        if (WebSocket.IsStateTerminal(State))
        {
            return;
        }
        ThrowIfDisposed();
        bool lockTaken = false;
        Monitor.Enter(_thisLock, ref lockTaken);
        bool ownsCloseCancellationTokenSource = false;
        CancellationToken linkedCancellationToken = CancellationToken.None;
        try
        {
            ThrowIfPendingException();
            if (WebSocket.IsStateTerminal(State))
            {
                return;
            }
            ThrowIfDisposed();
            WebSocket.ThrowOnInvalidState(State, WebSocketState.Open, WebSocketState.CloseReceived, WebSocketState.CloseSent);
            ownsCloseCancellationTokenSource = _closeOutstandingOperationHelper.TryStartOperation(cancellationToken, out linkedCancellationToken);
            Task task;
            if (ownsCloseCancellationTokenSource)
            {
                task = _closeOutputTask;
                if (task == null && State != WebSocketState.CloseSent)
                {
                    if (_closeReceivedTaskCompletionSource == null)
                    {
                        _closeReceivedTaskCompletionSource = new TaskCompletionSource();
                    }
                    task = CloseOutputAsync(closeStatus, statusDescription, linkedCancellationToken);
                }
            }
            else
            {
                task = _closeReceivedTaskCompletionSource.Task;
            }
            if (task != null)
            {
                ReleaseLock(_thisLock, ref lockTaken);
                try
                {
                    await task.SuppressContextFlow();
                }
                catch (Exception ex)
                {
                    Monitor.Enter(_thisLock, ref lockTaken);
                    if (!CanHandleExceptionDuringClose(ex))
                    {
                        ThrowIfConvertibleException("CloseOutputAsync", ex, cancellationToken, linkedCancellationToken.IsCancellationRequested);
                        throw;
                    }
                }
                if (!lockTaken)
                {
                    Monitor.Enter(_thisLock, ref lockTaken);
                }
            }
            if (OnCloseOutputCompleted())
            {
                bool flag;
                try
                {
                    flag = await StartOnCloseCompleted(lockTaken, sessionHandleLockTakenSnapshot: false, linkedCancellationToken).SuppressContextFlow();
                }
                catch (Exception)
                {
                    ResetFlagAndTakeLock(_thisLock, ref lockTaken);
                    throw;
                }
                if (flag)
                {
                    ResetFlagAndTakeLock(_thisLock, ref lockTaken);
                    FinishOnCloseCompleted();
                }
            }
            if (WebSocket.IsStateTerminal(State))
            {
                return;
            }
            linkedCancellationToken = CancellationToken.None;
            bool flag2 = _receiveOutstandingOperationHelper.TryStartOperation(cancellationToken, out linkedCancellationToken);
            if (flag2)
            {
                _closeAsyncStartedReceive = true;
                ArraySegment<byte> closeMessageBuffer = new ArraySegment<byte>(new byte[256]);
                EnsureReceiveOperation();
                Task<WebSocketReceiveResult> task2 = _receiveOperation.Process(closeMessageBuffer, linkedCancellationToken);
                ReleaseLock(_thisLock, ref lockTaken);
                WebSocketReceiveResult receiveResult = null;
                try
                {
                    receiveResult = await task2.SuppressContextFlow();
                }
                catch (Exception ex3)
                {
                    Monitor.Enter(_thisLock, ref lockTaken);
                    if (!CanHandleExceptionDuringClose(ex3))
                    {
                        ThrowIfConvertibleException("CloseAsync", ex3, cancellationToken, linkedCancellationToken.IsCancellationRequested);
                        throw;
                    }
                }
                if (receiveResult != null)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled() && receiveResult.Count > 0)
                    {
                        System.Net.NetEventSource.DumpBuffer(this, closeMessageBuffer.Array, closeMessageBuffer.Offset, receiveResult.Count, "CloseAsyncCore");
                    }
                    if (receiveResult.MessageType != WebSocketMessageType.Close)
                    {
                        throw new WebSocketException(WebSocketError.InvalidMessageType, System.SR.Format(System.SR.net_WebSockets_InvalidMessageType, "WebSocket.CloseAsync", "WebSocket.CloseOutputAsync", receiveResult.MessageType));
                    }
                }
            }
            else
            {
                _receiveOutstandingOperationHelper.CompleteOperation(flag2);
                ReleaseLock(_thisLock, ref lockTaken);
                await _closeReceivedTaskCompletionSource.Task.SuppressContextFlow();
            }
            if (!lockTaken)
            {
                Monitor.Enter(_thisLock, ref lockTaken);
            }
            if (WebSocket.IsStateTerminal(State))
            {
                return;
            }
            bool ownsSendCancellationSource = false;
            try
            {
                ownsSendCancellationSource = _sendOutstandingOperationHelper.TryStartOperation(cancellationToken, out linkedCancellationToken);
                bool flag3;
                try
                {
                    flag3 = await StartOnCloseCompleted(lockTaken, sessionHandleLockTakenSnapshot: false, linkedCancellationToken).SuppressContextFlow();
                }
                catch (Exception)
                {
                    ResetFlagAndTakeLock(_thisLock, ref lockTaken);
                    throw;
                }
                if (flag3)
                {
                    ResetFlagAndTakeLock(_thisLock, ref lockTaken);
                    FinishOnCloseCompleted();
                }
            }
            finally
            {
                _sendOutstandingOperationHelper.CompleteOperation(ownsSendCancellationSource);
            }
        }
        catch (Exception exception)
        {
            bool isCancellationRequested = linkedCancellationToken.IsCancellationRequested;
            Abort();
            ThrowIfConvertibleException("CloseAsync", exception, cancellationToken, isCancellationRequested);
            throw;
        }
        finally
        {
            _closeOutstandingOperationHelper.CompleteOperation(ownsCloseCancellationTokenSource);
            ReleaseLock(_thisLock, ref lockTaken);
        }
    }
References System.Net.WebSockets.WebSocketBase._closeAsyncStartedReceive, System.Net.WebSockets.WebSocketBase._closeOutputTask, System.Net.WebSockets.WebSocketBase._closeOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._closeReceivedTaskCompletionSource, System.Net.WebSockets.WebSocketBase._receiveOperation, System.Net.WebSockets.WebSocketBase._receiveOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._sendOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._thisLock, System.Net.WebSockets.WebSocketBase.Abort(), System.cancellationToken, System.Net.WebSockets.WebSocketBase.CanHandleExceptionDuringClose(), System.Net.WebSockets.WebSocketBase.CloseOutputAsync(), System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CompleteOperation(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.NetEventSource.DumpBuffer(), System.Net.WebSockets.WebSocketBase.EnsureReceiveOperation(), System.Threading.Monitor.Enter(), System.exception, System.Net.WebSockets.WebSocketBase.FinishOnCloseCompleted(), System.SR.Format(), System.Net.WebSockets.WebSocket.IsStateTerminal(), System.Net.NetEventSource.Log, System.SR.net_WebSockets_InvalidMessageType, System.Threading.CancellationToken.None, System.Net.WebSockets.WebSocketBase.OnCloseOutputCompleted(), System.Net.WebSockets.WebSocketBase.ReleaseLock(), System.Net.WebSockets.WebSocketBase.ResetFlagAndTakeLock(), System.Net.WebSockets.WebSocketBase.StartOnCloseCompleted(), System.task, System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(), System.Net.WebSockets.WebSocketBase.ThrowIfDisposed(), System.Net.WebSockets.WebSocketBase.ThrowIfPendingException(), System.Net.WebSockets.WebSocket.ThrowOnInvalidState(), and System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.TryStartOperation().
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsync().