Terraria: System.Net.WebSockets.WebSocketBase.Abort
Abort()
override void System.Net.WebSockets.WebSocketBase.Abort () inline
Definition at line 923 of file WebSocketBase.cs.
    {
        bool thisLockTaken = false;
        bool sessionHandleLockTaken = false;
        try
        {
            if (WebSocket.IsStateTerminal(State))
            {
                return;
            }
            TakeLocks(ref thisLockTaken, ref sessionHandleLockTaken);
            if (!WebSocket.IsStateTerminal(State))
            {
                _state = WebSocketState.Aborted;
                if (SessionHandle != null && !SessionHandle.IsClosed && !SessionHandle.IsInvalid)
                {
                    WebSocketProtocolComponent.WebSocketAbortHandle(SessionHandle);
                }
                _receiveOutstandingOperationHelper.CancelIO();
                _sendOutstandingOperationHelper.CancelIO();
                _closeOutputOutstandingOperationHelper.CancelIO();
                _closeOutstandingOperationHelper.CancelIO();
                if (_innerStreamAsWebSocketStream != null)
                {
                    _innerStreamAsWebSocketStream.Abort();
                }
                CleanUp();
            }
        }
        finally
        {
            ReleaseLocks(ref thisLockTaken, ref sessionHandleLockTaken);
        }
    }
References System.Net.WebSockets.WebSocketBase._closeOutputOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._closeOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._innerStreamAsWebSocketStream, System.Net.WebSockets.WebSocketBase._receiveOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._sendOutstandingOperationHelper, System.Net.WebSockets.WebSocketBase._state, System.Net.WebSockets.WebSocketBase.IWebSocketStream.Abort(), System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CancelIO(), System.Net.WebSockets.WebSocketBase.CleanUp(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.Runtime.InteropServices.SafeHandle.IsInvalid, System.Net.WebSockets.WebSocket.IsStateTerminal(), System.Net.WebSockets.WebSocketBase.ReleaseLocks(), System.Net.WebSockets.WebSocketBase.SessionHandle, System.Net.WebSockets.WebSocketBase.TakeLocks(), and System.Net.WebSockets.WebSocketProtocolComponent.WebSocketAbortHandle().
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.Dispose(), System.Net.WebSockets.WebSocketBase.OnBackgroundTaskException(), System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(), and System.Net.WebSockets.WebSocketBase.SendAsyncCore().