Terraria: System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException
ThrowIfConvertibleException()
void System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException (string methodName, Exception exception, CancellationToken cancellationToken, bool aborted) inline private
Definition at line 1498 of file WebSocketBase.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled() && !string.IsNullOrEmpty(methodName))
        {
            System.Net.NetEventSource.Error(this, $"methodName: {methodName}, exception: {exception}", "ThrowIfConvertibleException");
        }
        if (exception is OperationCanceledException)
        {
            if (cancellationToken.IsCancellationRequested || !aborted)
            {
                return;
            }
            ThrowIfAborted(aborted, exception);
        }
        WebSocketException ex2 = exception as WebSocketException;
        if (ex2 != null)
        {
            cancellationToken.ThrowIfCancellationRequested();
            ThrowIfAborted(aborted, ex2);
            return;
        }
        if (exception is SocketException ex3)
        {
            ex2 = new WebSocketException(ex3.NativeErrorCode, ex3);
        }
        if (exception is HttpListenerException ex4)
        {
            ex2 = new WebSocketException(ex4.ErrorCode, ex4);
        }
        if (exception is IOException innerException && exception.InnerException is SocketException ex5)
        {
            ex2 = new WebSocketException(ex5.NativeErrorCode, innerException);
        }
        if (ex2 != null)
        {
            cancellationToken.ThrowIfCancellationRequested();
            ThrowIfAborted(aborted, ex2);
            throw ex2;
        }
        if (!(exception is AggregateException ex6))
        {
            return;
        }
        ReadOnlyCollection<Exception> innerExceptions = ex6.Flatten().InnerExceptions;
        if (innerExceptions.Count == 0)
        {
            return;
        }
        foreach (Exception item in innerExceptions)
        {
            ThrowIfConvertibleException(null, item, cancellationToken, aborted);
        }
    }
References System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.NetEventSource.Error(), System.exception, System.item, System.Net.NetEventSource.Log, System.Net.WebSockets.WebSocketBase.ThrowIfAborted(), and System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException().
Referenced by System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.WebSockets.WebSocketBase.CloseOutputAsyncCore(), System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(), System.Net.WebSockets.WebSocketBase.SendAsyncCore(), System.Net.WebSockets.WebSocketBase.StartOnCloseCompleted(), and System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException().