Terraria: System.Net.WebSockets.WebSocketBase.StartOnCloseReceived
StartOnCloseReceived()
bool System.Net.WebSockets.WebSocketBase.StartOnCloseReceived (ref bool thisLockTaken) inline private
Definition at line 1639 of file WebSocketBase.cs.
    {
        ThrowIfDisposed();
        if (WebSocket.IsStateTerminal(State) || State == WebSocketState.CloseReceived)
        {
            return false;
        }
        Monitor.Enter(_thisLock, ref thisLockTaken);
        if (WebSocket.IsStateTerminal(State) || State == WebSocketState.CloseReceived)
        {
            return false;
        }
        if (State == WebSocketState.Open)
        {
            _state = WebSocketState.CloseReceived;
            if (_closeReceivedTaskCompletionSource == null)
            {
                _closeReceivedTaskCompletionSource = new TaskCompletionSource();
            }
            return false;
        }
        return true;
    }
References System.Net.WebSockets.WebSocketBase._closeReceivedTaskCompletionSource, System.Net.WebSockets.WebSocketBase._state, System.Net.WebSockets.WebSocketBase._thisLock, System.Threading.Monitor.Enter(), System.Net.WebSockets.WebSocket.IsStateTerminal(), and System.Net.WebSockets.WebSocketBase.ThrowIfDisposed().
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process().