Terraria: Terraria.Social.WeGame.CoreSocialModule.ProcessRailSystemStateChange
ProcessRailSystemStateChange()
static void Terraria.Social.WeGame.CoreSocialModule.ProcessRailSystemStateChange (RailSystemState state) inline static private
Definition at line 108 of file CoreSocialModule.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Invalid comparison between Unknown and I4
        //IL_0004: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Invalid comparison between Unknown and I4
        if ((int)state == 2 || (int)state == 3)
        {
            MessageBox.Show("检测到WeGame异常，游戏将自动保存进度并退出游戏", "Terraria--WeGame Error");
            WorldGen.SaveAndQuit(SaveAndQuitCallBack);
        }
    }
References Terraria.WorldGen.SaveAndQuit(), and Terraria.Social.WeGame.CoreSocialModule.SaveAndQuitCallBack().
Referenced by Terraria.Social.WeGame.CoreSocialModule.RailEventCallBack().