Terraria: System.Diagnostics.Tracing.EnumerableTypeInfo.WriteData
WriteData()
override void System.Diagnostics.Tracing.EnumerableTypeInfo.WriteData (PropertyValue value) inline
Definition at line 25 of file EnumerableTypeInfo.cs.
    {
        int bookmark = TraceLoggingDataCollector.BeginBufferedArray();
        int num = 0;
        IEnumerable enumerable = (IEnumerable)value.ReferenceValue;
        if (enumerable != null)
        {
            foreach (object item in enumerable)
            {
                elementInfo.WriteData(elementInfo.PropertyValueFactory(item));
                num++;
            }
        }
        TraceLoggingDataCollector.EndBufferedArray(bookmark, num);
    }
References System.Diagnostics.Tracing.TraceLoggingDataCollector.BeginBufferedArray(), System.Diagnostics.Tracing.EnumerableTypeInfo.elementInfo, System.Diagnostics.Tracing.TraceLoggingDataCollector.EndBufferedArray(), System.item, System.Diagnostics.Tracing.TraceLoggingTypeInfo.PropertyValueFactory, System.value, and System.Diagnostics.Tracing.TraceLoggingTypeInfo.WriteData().