Terraria: System.ComponentModel.DataAnnotations.CustomValidationAttribute.ValidateMethodParameter
ValidateMethodParameter()
string System.ComponentModel.DataAnnotations.CustomValidationAttribute.ValidateMethodParameter () inline private
Definition at line 110 of file CustomValidationAttribute.cs.
    {
        if (string.IsNullOrEmpty(Method))
        {
            return System.SR.CustomValidationAttribute_Method_Required;
        }
        MethodInfo methodInfo = ValidatorType.GetMethods(BindingFlags.Static | BindingFlags.Public).SingleOrDefault((MethodInfo m) => string.Equals(m.Name, Method, StringComparison.Ordinal));
        if (methodInfo == null)
        {
            return System.SR.Format(System.SR.CustomValidationAttribute_Method_Not_Found, Method, ValidatorType.Name);
        }
        if (!typeof(ValidationResult).IsAssignableFrom(methodInfo.ReturnType))
        {
            return System.SR.Format(System.SR.CustomValidationAttribute_Method_Must_Return_ValidationResult, Method, ValidatorType.Name);
        }
        ParameterInfo[] parameters = methodInfo.GetParameters();
        if (parameters.Length == 0 || parameters[0].ParameterType.IsByRef)
        {
            return System.SR.Format(System.SR.CustomValidationAttribute_Method_Signature, Method, ValidatorType.Name);
        }
        _isSingleArgumentMethod = parameters.Length == 1;
        if (!_isSingleArgumentMethod && (parameters.Length != 2 || parameters[1].ParameterType != typeof(ValidationContext)))
        {
            return System.SR.Format(System.SR.CustomValidationAttribute_Method_Signature, Method, ValidatorType.Name);
        }
        _methodInfo = methodInfo;
        _firstParameterType = parameters[0].ParameterType;
        return null;
    }
References System.ComponentModel.DataAnnotations.CustomValidationAttribute._firstParameterType, System.ComponentModel.DataAnnotations.CustomValidationAttribute._isSingleArgumentMethod, System.ComponentModel.DataAnnotations.CustomValidationAttribute._methodInfo, System.SR.CustomValidationAttribute_Method_Must_Return_ValidationResult, System.SR.CustomValidationAttribute_Method_Not_Found, System.SR.CustomValidationAttribute_Method_Required, System.SR.CustomValidationAttribute_Method_Signature, System.Attribute.Equals(), System.SR.Format(), System.Type.GetMethods(), System.Reflection.MethodBase.GetParameters(), System.Type.IsByRef, System.ComponentModel.DataAnnotations.CustomValidationAttribute.Method, System.Reflection.MemberInfo.Name, System.Reflection.ParameterInfo.ParameterType, System.Reflection.MethodInfo.ReturnType, and System.ComponentModel.DataAnnotations.CustomValidationAttribute.ValidatorType.
Referenced by System.ComponentModel.DataAnnotations.CustomValidationAttribute.CheckAttributeWellFormed().