Terraria: System.ComponentModel.DataAnnotations.CustomValidationAttribute.TryConvertValue
TryConvertValue()
bool System.ComponentModel.DataAnnotations.CustomValidationAttribute.TryConvertValue (object value, out object convertedValue) inline private
Definition at line 149 of file CustomValidationAttribute.cs.
    {
        convertedValue = null;
        Type firstParameterType = _firstParameterType;
        if (value == null)
        {
            if (firstParameterType.IsValueType && (!firstParameterType.IsGenericType || firstParameterType.GetGenericTypeDefinition() != typeof(Nullable<>)))
            {
                return false;
            }
            return true;
        }
        if (firstParameterType.IsInstanceOfType(value))
        {
            convertedValue = value;
            return true;
        }
        try
        {
            convertedValue = Convert.ChangeType(value, firstParameterType, CultureInfo.CurrentCulture);
            return true;
        }
        catch (FormatException)
        {
            return false;
        }
        catch (InvalidCastException)
        {
            return false;
        }
        catch (NotSupportedException)
        {
            return false;
        }
    }
References System.ComponentModel.DataAnnotations.CustomValidationAttribute._firstParameterType, System.Convert.ChangeType(), System.Globalization.CultureInfo.CurrentCulture, System.Type.GetGenericTypeDefinition(), System.Type.IsGenericType, System.Type.IsInstanceOfType(), System.Type.IsValueType, and System.value.
Referenced by System.ComponentModel.DataAnnotations.CustomValidationAttribute.IsValid().