Terraria: System.ComponentModel.DataAnnotations.CustomValidationAttribute.IsValid
IsValid() [2/2]
override? ValidationResult System.ComponentModel.DataAnnotations.CustomValidationAttribute.IsValid (object? value, ValidationContext validationContext) inline protected virtual
Reimplemented from System.ComponentModel.DataAnnotations.ValidationAttribute.
Definition at line 57 of file CustomValidationAttribute.cs.
    {
        ThrowIfAttributeNotWellFormed();
        MethodInfo methodInfo = _methodInfo;
        if (!TryConvertValue(value, out var convertedValue))
        {
            return new ValidationResult(System.SR.Format(System.SR.CustomValidationAttribute_Type_Conversion_Failed, (value != null) ? value.GetType().ToString() : "null", _firstParameterType, ValidatorType, Method));
        }
        try
        {
            object[] parameters = ((!_isSingleArgumentMethod) ? new object[2] { convertedValue, validationContext } : new object[1] { convertedValue });
            ValidationResult validationResult = (ValidationResult)methodInfo.Invoke(null, parameters);
            _lastMessage = null;
            if (validationResult != null)
            {
                _lastMessage = validationResult.ErrorMessage;
            }
            return validationResult;
        }
        catch (TargetInvocationException ex)
        {
            throw ex.InnerException;
        }
    }
References System.ComponentModel.DataAnnotations.CustomValidationAttribute._firstParameterType, System.ComponentModel.DataAnnotations.CustomValidationAttribute._isSingleArgumentMethod, System.ComponentModel.DataAnnotations.CustomValidationAttribute._lastMessage, System.ComponentModel.DataAnnotations.CustomValidationAttribute._methodInfo, System.SR.CustomValidationAttribute_Type_Conversion_Failed, System.ComponentModel.DataAnnotations.ValidationResult.ErrorMessage, System.SR.Format(), System.Exception.InnerException, System.Reflection.MethodBase.Invoke(), System.ComponentModel.DataAnnotations.CustomValidationAttribute.Method, System.ComponentModel.DataAnnotations.CustomValidationAttribute.ThrowIfAttributeNotWellFormed(), System.ComponentModel.DataAnnotations.CustomValidationAttribute.TryConvertValue(), System.ComponentModel.DataAnnotations.CustomValidationAttribute.ValidatorType, and System.value.