Terraria: System.Numerics.NumericsHelpers.DangerousMakeTwosComplement
DangerousMakeTwosComplement()
static void System.Numerics.NumericsHelpers.DangerousMakeTwosComplement (Span< uint > d) inline static
Definition at line 78 of file NumericsHelpers.cs.
    {
        if (d != null && d.Length > 0)
        {
            d[0] = ~d[0] + 1;
            int i;
            for (i = 1; d[i - 1] == 0 && i < d.Length; i++)
            {
                d[i] = ~d[i] + 1;
            }
            for (; i < d.Length; i++)
            {
                d[i] = ~d[i];
            }
        }
    }
References System.Span< T >.Length.
Referenced by System.Numerics.BigInteger.BigInteger(), System.Numerics.BigInteger.BigInteger(), System.Numerics.BigNumber.HexNumberToBigInteger(), System.Numerics.BigInteger.operator>>(), and System.Numerics.BigInteger.ToUInt32Span().