Terraria: Terraria.Graphics.FlameLashDrawer.Draw
Draw()
void Terraria.Graphics.FlameLashDrawer.Draw (Projectile proj) inline
Definition at line 12 of file FlameLashDrawer.cs.
    {
        transitToDark = Utils.GetLerpValue(0f, 6f, proj.localAI[0], clamped: true);
        MiscShaderData miscShaderData = GameShaders.Misc["FlameLash"];
        miscShaderData.UseSaturation(-2f);
        miscShaderData.UseOpacity(MathHelper.Lerp(4f, 8f, transitToDark));
        miscShaderData.Apply();
        _vertexStrip.PrepareStripWithProceduralPadding(proj.oldPos, proj.oldRot, StripColors, StripWidth, -Main.screenPosition + proj.Size / 2f);
        _vertexStrip.DrawTrail();
        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
    }
References Terraria.Graphics.FlameLashDrawer._vertexStrip, Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Projectile.localAI, Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Main.pixelShader, Terraria.Main.screenPosition, Terraria.Entity.Size, Terraria.Graphics.FlameLashDrawer.StripColors(), Terraria.Graphics.FlameLashDrawer.StripWidth(), Terraria.Graphics.FlameLashDrawer.transitToDark, Terraria.Graphics.Shaders.MiscShaderData.UseOpacity(), and Terraria.Graphics.Shaders.MiscShaderData.UseSaturation().