Terraria: System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync
ReadAsync() [3/3]
override async ValueTask< int > System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken) inline virtual
Reimplemented from System.Net.Http.HttpBaseStream.
Definition at line 561 of file HttpConnection.cs.
        {
            CancellationHelper.ThrowIfCancellationRequested(cancellationToken);
            if (_connection == null || buffer.Length == 0)
            {
                return 0;
            }
            if ((ulong)buffer.Length > _contentBytesRemaining)
            {
                buffer = buffer.Slice(0, (int)_contentBytesRemaining);
            }
            ValueTask<int> valueTask = _connection.ReadAsync(buffer);
            int num;
            if (valueTask.IsCompletedSuccessfully)
            {
                num = valueTask.Result;
            }
            else
            {
                CancellationTokenRegistration ctr = _connection.RegisterCancellation(cancellationToken);
                try
                {
                    num = await valueTask.ConfigureAwait(continueOnCapturedContext: false);
                }
                catch (Exception ex) when (CancellationHelper.ShouldWrapInOperationCanceledException(ex, cancellationToken))
                {
                    throw CancellationHelper.CreateOperationCanceledException(ex, cancellationToken);
                }
                finally
                {
                    ctr.Dispose();
                }
            }
            if (num <= 0)
            {
                CancellationHelper.ThrowIfCancellationRequested(cancellationToken);
                throw new IOException(System.SR.Format(System.SR.net_http_invalid_response_premature_eof_bytecount, _contentBytesRemaining));
            }
            _contentBytesRemaining -= (ulong)num;
            if (_contentBytesRemaining == 0L)
            {
                _connection.CompleteResponse();
                _connection = null;
            }
            return num;
        }
References System.Net.Http.HttpContentStream._connection, System.Net.Http.HttpConnection.ContentLengthReadStream._contentBytesRemaining, System.buffer, System.cancellationToken, System.Net.Http.HttpConnection.CompleteResponse(), System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.SR.Format(), System.L, System.SR.net_http_invalid_response_premature_eof_bytecount, System.Net.Http.HttpConnection.ReadAsync(), System.Net.Http.HttpConnection.RegisterCancellation(), System.Net.Http.CancellationHelper.ShouldWrapInOperationCanceledException(), and System.Net.Http.CancellationHelper.ThrowIfCancellationRequested().