Terraria: System.Net.Http.HttpConnection.ContentLengthReadStream.ReadFromConnectionBuffer
ReadFromConnectionBuffer()
ReadOnlyMemory< byte > System.Net.Http.HttpConnection.ContentLengthReadStream.ReadFromConnectionBuffer (int maxBytesToRead) inline private
Definition at line 653 of file HttpConnection.cs.
        {
            ReadOnlyMemory<byte> remainingBuffer = _connection.RemainingBuffer;
            if (remainingBuffer.Length == 0)
            {
                return default(ReadOnlyMemory<byte>);
            }
            int num = Math.Min(maxBytesToRead, (int)Math.Min((ulong)remainingBuffer.Length, _contentBytesRemaining));
            _connection.ConsumeFromRemainingBuffer(num);
            _contentBytesRemaining -= (ulong)num;
            return remainingBuffer.Slice(0, num);
        }
References System.Net.Http.HttpContentStream._connection, System.Net.Http.HttpConnection.ContentLengthReadStream._contentBytesRemaining, System.Net.Http.HttpConnection.ConsumeFromRemainingBuffer(), System.Math.Min(), and System.Net.Http.HttpConnection.RemainingBuffer.
Referenced by System.Net.Http.HttpConnection.ContentLengthReadStream.DrainAsync().