Terraria: System.Net.Http.HttpConnection.ContentLengthReadStream.DrainAsync
DrainAsync()
override async ValueTask< bool > System.Net.Http.HttpConnection.ContentLengthReadStream.DrainAsync (int maxDrainBytes) inline virtual
Reimplemented from System.Net.Http.HttpConnection.HttpContentReadStream.
Definition at line 666 of file HttpConnection.cs.
        {
            ReadFromConnectionBuffer(int.MaxValue);
            if (_contentBytesRemaining == 0L)
            {
                Finish();
                return true;
            }
            if (_contentBytesRemaining > (ulong)maxDrainBytes)
            {
                return false;
            }
            CancellationTokenSource cts = null;
            CancellationTokenRegistration ctr = default(CancellationTokenRegistration);
            TimeSpan maxResponseDrainTime = _connection._pool.Settings._maxResponseDrainTime;
            if (maxResponseDrainTime == TimeSpan.Zero)
            {
                return false;
            }
            if (maxResponseDrainTime != Timeout.InfiniteTimeSpan)
            {
                cts = new CancellationTokenSource((int)maxResponseDrainTime.TotalMilliseconds);
                ctr = cts.Token.Register(delegate(object s)
                {
                    ((HttpConnection)s).Dispose();
                }, _connection);
            }
            try
            {
                do
                {
                    await _connection.FillAsync(async: true).ConfigureAwait(continueOnCapturedContext: false);
                    ReadFromConnectionBuffer(int.MaxValue);
                }
                while (_contentBytesRemaining != 0L);
                ctr.Dispose();
                CancellationHelper.ThrowIfCancellationRequested(ctr.Token);
                Finish();
                return true;
            }
            finally
            {
                ctr.Dispose();
                cts?.Dispose();
            }
        }
References System.Net.Http.HttpConnection.HttpConnection(), System.Net.Http.HttpContentStream._connection, System.Net.Http.HttpConnection.ContentLengthReadStream._contentBytesRemaining, System.Net.Http.HttpConnectionSettings._maxResponseDrainTime, System.Net.Http.HttpConnection._pool, System.Net.Http.HttpConnection.FillAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.Finish(), System.Threading.Timeout.InfiniteTimeSpan, System.L, System.Net.Http.HttpConnection.ContentLengthReadStream.ReadFromConnectionBuffer(), System.s, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.CancellationHelper.ThrowIfCancellationRequested(), and System.TimeSpan.Zero.