Terraria: System.Net.Http.HttpConnection.ContentLengthReadStream.CopyToAsync
CopyToAsync() [4/4]
override Task System.Net.Http.HttpConnection.ContentLengthReadStream.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 608 of file HttpConnection.cs.
        {
            Stream.ValidateCopyToArguments(destination, bufferSize);
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCanceled(cancellationToken);
            }
            if (_connection == null)
            {
                return Task.CompletedTask;
            }
            Task task = _connection.CopyToContentLengthAsync(destination, async: true, _contentBytesRemaining, bufferSize, cancellationToken);
            if (task.IsCompletedSuccessfully)
            {
                Finish();
                return Task.CompletedTask;
            }
            return CompleteCopyToAsync(task, cancellationToken);
        }
References System.Net.Http.HttpContentStream._connection, System.Net.Http.HttpConnection.ContentLengthReadStream._contentBytesRemaining, System.cancellationToken, System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(), System.Threading.Tasks.Task< TResult >.CompletedTask, System.Net.Http.HttpConnection.CopyToContentLengthAsync(), System.destination, System.Net.Http.HttpConnection.ContentLengthReadStream.Finish(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.task, and System.IO.Stream.ValidateCopyToArguments().