Terraria: System.Net.Http.HttpConnection.ContentLengthReadStream.Read
Read() [2/2]
override int System.Net.Http.HttpConnection.ContentLengthReadStream.Read (Span< byte > buffer) inline virtual
Reimplemented from System.Net.Http.HttpBaseStream.
Definition at line 537 of file HttpConnection.cs.
        {
            if (_connection == null || buffer.Length == 0)
            {
                return 0;
            }
            if ((ulong)buffer.Length > _contentBytesRemaining)
            {
                buffer = buffer.Slice(0, (int)_contentBytesRemaining);
            }
            int num = _connection.Read(buffer);
            if (num <= 0)
            {
                throw new IOException(System.SR.Format(System.SR.net_http_invalid_response_premature_eof_bytecount, _contentBytesRemaining));
            }
            _contentBytesRemaining -= (ulong)num;
            if (_contentBytesRemaining == 0L)
            {
                _connection.CompleteResponse();
                _connection = null;
            }
            return num;
        }
References System.Net.Http.HttpContentStream._connection, System.Net.Http.HttpConnection.ContentLengthReadStream._contentBytesRemaining, System.buffer, System.Net.Http.HttpConnection.CompleteResponse(), System.SR.Format(), System.L, System.SR.net_http_invalid_response_premature_eof_bytecount, and System.Net.Http.HttpConnection.Read().