Terraria: System.Diagnostics.PerformanceCounterLib.PerformanceMonitor.GetData
GetData()
byte[] System.Diagnostics.PerformanceCounterLib.PerformanceMonitor.GetData (string item) inline package
Definition at line 39 of file PerformanceCounterLib.cs.
        {
            int num = 17;
            int num2 = 0;
            byte[] array = null;
            int num3 = 0;
            while (num > 0)
            {
                try
                {
                    return (byte[])_perfDataKey.GetValue(item);
                }
                catch (IOException ex)
                {
                    num3 = ex.HResult;
                    if (num3 <= 167)
                    {
                        if (num3 == 6)
{
                            goto IL_0078;
                        }
                        if (num3 == 21 || num3 == 167)
{
                            goto IL_007e;
                        }
                    }
                    else if (num3 <= 258)
                    {
                        if (num3 == 170 || num3 == 258)
{
                            goto IL_007e;
                        }
                    }
                    else if (num3 == 1722 || num3 == 1726)
                    {
                        goto IL_0078;
                    }
                    throw new Win32Exception(num3);
                    IL_007e:
                    num--;
                    if (num2 == 0)
                    {
                        num2 = 10;
                        continue;
                    }
                    Thread.Sleep(num2);
                    num2 *= 2;
                    goto end_IL_0029;
                    IL_0078:
                    Init();
                    goto IL_007e;
                    end_IL_0029:;
                }
                catch (InvalidCastException innerException)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.CounterDataCorrupt, _perfDataKey.ToString()), innerException);
                }
            }
            throw new Win32Exception(num3);
        }
References System.Diagnostics.PerformanceCounterLib.PerformanceMonitor._perfDataKey, System.array, System.SR.CounterDataCorrupt, System.SR.Format(), System.Diagnostics.PerformanceCounterLib.PerformanceMonitor.Init(), System.item, and System.Threading.Thread.Sleep().
Referenced by System.Diagnostics.PerformanceCounterLib.GetPerformanceData().