Terraria: Terraria.GameContent.UI.Elements.AWorldListItem.GetIconElement
GetIconElement()
UIElement Terraria.GameContent.UI.Elements.AWorldListItem.GetIconElement () inline protected inherited
    {
        if (_data.DrunkWorld && _data.RemixWorld)
        {
            Asset<Texture2D> obj = Main.Assets.Request<Texture2D>("Images/UI/IconEverythingAnimated", (AssetRequestMode)1);
            UIImageFramed uIImageFramed = new UIImageFramed(obj, obj.Frame(7, 16));
            uIImageFramed.Left = new StyleDimension(4f, 0f);
            uIImageFramed.OnUpdate += UpdateGlitchAnimation;
            return uIImageFramed;
        }
        return new UIImage(GetIcon())
        {
            Left = new StyleDimension(4f, 0f)
        };
    }
References Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.Main.Assets, Terraria.IO.WorldFileData.DrunkWorld, Terraria.GameContent.UI.Elements.AWorldListItem.GetIcon(), Terraria.UI.UIElement.Left, Terraria.IO.WorldFileData.RemixWorld, and Terraria.GameContent.UI.Elements.AWorldListItem.UpdateGlitchAnimation().
Referenced by Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), and Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem().