Terraria: Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.OffsetLibraryByPages
OffsetLibraryByPages()
void Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.OffsetLibraryByPages (int howManyPages) inline
Definition at line 105 of file UIBestiaryEntryGrid.cs.
    {
        GetEntriesToShow(out var _, out var _, out var maxEntriesToHave);
        OffsetLibrary(howManyPages * maxEntriesToHave);
    }
References Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetEntriesToShow(), and Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.OffsetLibrary().
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.MakeButtonGoByOffset(), and Terraria.GameContent.UI.States.UIBestiaryTest.TryMovingPages().