Terraria: Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetEntriesToShow
GetEntriesToShow()
void Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetEntriesToShow (out int maxEntriesWidth, out int maxEntriesHeight, out int maxEntriesToHave) inline
    {
        Rectangle rectangle = GetDimensions().ToRectangle();
        maxEntriesWidth = rectangle.Width / 72;
        maxEntriesHeight = rectangle.Height / 72;
        int num = 0;
        maxEntriesToHave = maxEntriesWidth * maxEntriesHeight - num;
    }
References Terraria.UI.UIElement.GetDimensions(), and Terraria.UI.CalculatedStyle.ToRectangle().
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetRangeText(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.OffsetLibrary(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.OffsetLibraryByPages(), and Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForEntryGrid().