Terraria: Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetRangeText
GetRangeText()
string Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetRangeText () inline
Definition at line 88 of file UIBestiaryEntryGrid.cs.
    {
        GetEntriesToShow(out var _, out var _, out var maxEntriesToHave);
        int atEntryIndex = _atEntryIndex;
        int num = Math.Min(_lastEntry, atEntryIndex + maxEntriesToHave);
        int num2 = Math.Min(atEntryIndex + 1, num);
        return $"{num2}-{num} ({_lastEntry})";
    }
References Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid._atEntryIndex, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid._lastEntry, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetEntriesToShow(), and System.Math.Min().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryGridRange().