Terraria: UIBestiaryEntryInfoPage.CheckScrollBar
CheckScrollBar()
void UIBestiaryEntryInfoPage.CheckScrollBar () inline private
     {
         if (_scrollbar != null)
         {
             bool canScroll = _scrollbar.CanScroll;
             canScroll = true;
             if (_isScrollbarAttached && !canScroll)
             {
                 RemoveChild(_scrollbar);
                 _isScrollbarAttached = false;
                 _list.Width.Set(0f, 1f);
             }
             else if (!_isScrollbarAttached && canScroll)
             {
                 Append(_scrollbar);
                 _isScrollbarAttached = true;
                 _list.Width.Set(-20f, 1f);
             }
         }
     }
References _isScrollbarAttached, _list, _scrollbar, UIElement.Append(), UIScrollbar.CanScroll, UIElement.RemoveChild(), StyleDimension.Set(), and UIElement.Width.
Referenced by UIBestiaryEntryInfoPage(), and Recalculate().