Terraria: UIBestiaryEntryInfoPage.FillInfoForEntry
FillInfoForEntry()
void UIBestiaryEntryInfoPage.FillInfoForEntry (BestiaryEntry entry, ExtraBestiaryInfoPageInformation extraInfo) inline
     {
         _list.Clear();
         if (entry != null)
         {
             AddInfoToList(entry, extraInfo);
             Recalculate();
         }
     }
References _list, AddInfoToList(), UIList.Clear(), and Recalculate().
Referenced by UIBestiaryTest.DeselectEntryButton(), and UIBestiaryTest.SelectEntryButton().