Terraria: System.Net.Http.Headers.ViaHeaderValue.ToString
ToString()
override string System.Net.Http.Headers.ViaHeaderValue.ToString () inline
Definition at line 61 of file ViaHeaderValue.cs.
    {
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        if (!string.IsNullOrEmpty(_protocolName))
        {
            stringBuilder.Append(_protocolName);
            stringBuilder.Append('/');
        }
        stringBuilder.Append(_protocolVersion);
        stringBuilder.Append(' ');
        stringBuilder.Append(_receivedBy);
        if (!string.IsNullOrEmpty(_comment))
        {
            stringBuilder.Append(' ');
            stringBuilder.Append(_comment);
        }
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Net.Http.Headers.ViaHeaderValue._comment, System.Net.Http.Headers.ViaHeaderValue._protocolName, System.Net.Http.Headers.ViaHeaderValue._protocolVersion, System.Net.Http.Headers.ViaHeaderValue._receivedBy, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), and System.Text.StringBuilderCache.GetStringAndRelease().