Terraria: MS.Internal.Xml.XPath.BooleanFunctions.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.BooleanFunctions.Evaluate (XPathNodeIterator nodeIterator) inline
Definition at line 36 of file BooleanFunctions.cs.
    {
        return _funcType switch
        {
            Function.FunctionType.FuncBoolean => toBoolean(nodeIterator),
            Function.FunctionType.FuncNot => Not(nodeIterator),
            Function.FunctionType.FuncTrue => true,
            Function.FunctionType.FuncFalse => false,
            Function.FunctionType.FuncLang => Lang(nodeIterator),
            _ => false,
        };
    }
References MS.Internal.Xml.XPath.BooleanFunctions._funcType, MS.Internal.Xml.XPath.BooleanFunctions.Lang(), MS.Internal.Xml.XPath.BooleanFunctions.Not(), and MS.Internal.Xml.XPath.BooleanFunctions.toBoolean().