Terraria: System.Net.Http.Headers.ViaHeaderValue.GetViaLength
GetViaLength()
static int System.Net.Http.Headers.ViaHeaderValue.GetViaLength (string input, int startIndex, out object parsedValue) inline static package
Definition at line 125 of file ViaHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int protocolEndIndex = GetProtocolEndIndex(input, startIndex, out var protocolName, out var protocolVersion);
        if (protocolEndIndex == startIndex || protocolEndIndex == input.Length)
        {
            return 0;
        }
        string host;
        int hostLength = HttpRuleParser.GetHostLength(input, protocolEndIndex, allowToken: true, out host);
        if (hostLength == 0)
        {
            return 0;
        }
        protocolEndIndex += hostLength;
        protocolEndIndex += HttpRuleParser.GetWhitespaceLength(input, protocolEndIndex);
        string comment = null;
        if (protocolEndIndex < input.Length && input[protocolEndIndex] == '(')
        {
            int length = 0;
            if (HttpRuleParser.GetCommentLength(input, protocolEndIndex, out length) != 0)
            {
                return 0;
            }
            comment = input.Substring(protocolEndIndex, length);
            protocolEndIndex += length;
            protocolEndIndex += HttpRuleParser.GetWhitespaceLength(input, protocolEndIndex);
        }
        parsedValue = new ViaHeaderValue(protocolVersion, host, protocolName, comment);
        return protocolEndIndex - startIndex;
    }
References System.Net.Http.Headers.ViaHeaderValue.ViaHeaderValue(), System.Net.Http.HttpRuleParser.GetCommentLength(), System.Net.Http.HttpRuleParser.GetHostLength(), System.Net.Http.Headers.ViaHeaderValue.GetProtocolEndIndex(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, System.length, and System.startIndex.