Terraria: DontStarveDarknessDamageDealer.IsPlayerSafe
IsPlayerSafe()
static bool DontStarveDarknessDamageDealer.IsPlayerSafe (Player player) inline static private
     {
         Vector3 vector = Lighting.GetColor((int)player.Center.X / 16, (int)player.Center.Y / 16).ToVector3();
         bool flag = true;
         if (Main.LocalGolfState != null && (Main.LocalGolfState.ShouldCameraTrackBallLastKnownLocation || Main.LocalGolfState.IsTrackingBall))
         {
             return lastFrameWasTooBright;
         }
         if (Main.DroneCameraTracker != null && Main.DroneCameraTracker.IsInUse())
         {
             return lastFrameWasTooBright;
         }
         return vector.Length() >= 0.1f;
     }
References Entity.Center, Main.DroneCameraTracker, Lighting.GetColor(), DroneCameraTracker.IsInUse(), GolfState.IsTrackingBall, lastFrameWasTooBright, Main.LocalGolfState, and GolfState.ShouldCameraTrackBallLastKnownLocation.
Referenced by UpdateDarknessState().