Terraria: DontStarveDarknessDamageDealer.Update
Update()
static void DontStarveDarknessDamageDealer.Update (Player player) inline static
     {
         if (player.DeadOrGhost || Main.gameInactive || player.shimmering)
         {
             ResetTimer();
             return;
         }
         UpdateDarknessState(player);
         int darknessTimeBeforeStartingHits = GetDarknessTimeBeforeStartingHits();
         if (darknessTimer >= darknessTimeBeforeStartingHits)
         {
             darknessTimer = darknessTimeBeforeStartingHits;
             darknessHitTimer++;
             if (darknessHitTimer > 60 && !player.immune)
             {
                 int darknessDamagePerHit = GetDarknessDamagePerHit();
                 SoundEngine.PlaySound(SoundID.Item1, player.Center);
                 player.Hurt(PlayerDeathReason.ByOther(17), darknessDamagePerHit, 0);
                 darknessHitTimer = 0;
             }
         }
     }
References PlayerDeathReason.ByOther(), Entity.Center, darknessHitTimer, darknessTimer, Player.DeadOrGhost, Main.gameInactive, GetDarknessDamagePerHit(), GetDarknessTimeBeforeStartingHits(), Player.Hurt(), Player.immune, SoundID.Item1, SoundEngine.PlaySound(), ResetTimer(), Player.shimmering, and UpdateDarknessState().
Referenced by Player.Update().