Terraria: System.TimeZoneInfo.AdjustmentRule.AdjustmentRule
AdjustmentRule() [1/2]
System.TimeZoneInfo.AdjustmentRule.AdjustmentRule (DateTime dateStart, DateTime dateEnd, TimeSpan daylightDelta, TransitionTime daylightTransitionStart, TransitionTime daylightTransitionEnd, TimeSpan baseUtcOffsetDelta, bool noDaylightTransitions) inline private
Definition at line 83 of file TimeZoneInfo.cs.
        {
            ValidateAdjustmentRule(dateStart, dateEnd, daylightDelta, daylightTransitionStart, daylightTransitionEnd, noDaylightTransitions);
            _dateStart = dateStart;
            _dateEnd = dateEnd;
            _daylightDelta = daylightDelta;
            _daylightTransitionStart = daylightTransitionStart;
            _daylightTransitionEnd = daylightTransitionEnd;
            _baseUtcOffsetDelta = baseUtcOffsetDelta;
            _noDaylightTransitions = noDaylightTransitions;
        }
References System.TimeZoneInfo.AdjustmentRule._baseUtcOffsetDelta, System.TimeZoneInfo.AdjustmentRule._dateEnd, System.TimeZoneInfo.AdjustmentRule._dateStart, System.TimeZoneInfo.AdjustmentRule._daylightDelta, System.TimeZoneInfo.AdjustmentRule._daylightTransitionEnd, System.TimeZoneInfo.AdjustmentRule._daylightTransitionStart, System.TimeZoneInfo.AdjustmentRule._noDaylightTransitions, System.Runtime.Serialization.Dictionary, and System.TimeZoneInfo.AdjustmentRule.ValidateAdjustmentRule().
Referenced by System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(), System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(), and System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule().