Terraria: System.Net.Http.Headers.RetryConditionHeaderValue.GetRetryConditionLength
GetRetryConditionLength()
static int System.Net.Http.Headers.RetryConditionHeaderValue.GetRetryConditionLength (string input, int startIndex, out object parsedValue) inline static package
Definition at line 93 of file RetryConditionHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int num = startIndex;
        DateTimeOffset result = DateTimeOffset.MinValue;
        int result2 = -1;
        char c = input[num];
        if (c >= '0' && c <= '9')
        {
            int offset = num;
            int numberLength = HttpRuleParser.GetNumberLength(input, num, allowDecimal: false);
            if (numberLength == 0 || numberLength > 10)
            {
                return 0;
            }
            num += numberLength;
            num += HttpRuleParser.GetWhitespaceLength(input, num);
            if (num != input.Length)
            {
                return 0;
            }
            if (!HeaderUtilities.TryParseInt32(input, offset, numberLength, out result2))
            {
                return 0;
            }
        }
        else
        {
            if (!HttpDateParser.TryParse(input.AsSpan(num), out result))
            {
                return 0;
            }
            num = input.Length;
        }
        if (result2 == -1)
        {
            parsedValue = new RetryConditionHeaderValue(result);
        }
        else
        {
            parsedValue = new RetryConditionHeaderValue(new TimeSpan(0, 0, result2));
        }
        return num - startIndex;
    }
References System.Net.Http.Headers.RetryConditionHeaderValue.RetryConditionHeaderValue(), System.Net.Http.HttpRuleParser.GetNumberLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, System.DateTimeOffset.MinValue, System.offset, System.startIndex, System.Net.HttpDateParser.TryParse(), and System.Net.Http.Headers.HeaderUtilities.TryParseInt32().