Terraria: System.Xml.Schema.XmlUnionConverter.ChangeType
ChangeType() [8/9]
override object System.Xml.Schema.XmlUnionConverter.ChangeType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 39 of file XmlUnionConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        Type type = value.GetType();
        if (type == XmlBaseConverter.XmlAtomicValueType && _hasAtomicMember)
        {
            return ((XmlAtomicValue)value).ValueAs(destinationType, nsResolver);
        }
        if (type == XmlBaseConverter.XmlAtomicValueArrayType && _hasListMember)
        {
            return XmlAnyListConverter.ItemList.ChangeType(value, destinationType, nsResolver);
        }
        if (type == XmlBaseConverter.StringType)
        {
            if (destinationType == XmlBaseConverter.StringType)
            {
                return value;
            }
            XsdSimpleValue xsdSimpleValue = (XsdSimpleValue)base.SchemaType.Datatype.ParseValue((string)value, new NameTable(), nsResolver, createAtomicValue: true);
            return xsdSimpleValue.XmlType.ValueConverter.ChangeType((string)value, destinationType, nsResolver);
        }
        throw CreateInvalidClrMappingException(type, destinationType);
    }
References System.Xml.Schema.XmlUnionConverter._hasAtomicMember, System.Xml.Schema.XmlUnionConverter._hasListMember, System.Xml.Schema.XmlValueConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.CreateInvalidClrMappingException(), System.Xml.Dictionary, System.Type.GetType(), System.Xml.Schema.XmlAnyListConverter.ItemList, System.Xml.Schema.XmlBaseConverter.StringType, System.type, System.value, System.Xml.Schema.XmlSchemaType.ValueConverter, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueArrayType, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XsdSimpleValue.XmlType.