Terraria: System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal
UndefineLocal()
void System.Linq.Expressions.Interpreter.LocalVariables.UndefineLocal (LocalDefinition definition, int end) inline
Definition at line 62 of file LocalVariables.cs.
    {
        VariableScope variableScope = _variables[definition.Parameter];
        variableScope.Stop = end;
        if (variableScope.Parent != null)
        {
            _variables[definition.Parameter] = variableScope.Parent;
        }
        else
        {
            _variables.Remove(definition.Parameter);
        }
        _localCount--;
    }
References System.Linq.Expressions.Interpreter.LocalVariables._localCount, System.Linq.Expressions.Interpreter.LocalVariables._variables, and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockEnd(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression(), System.Linq.Expressions.Interpreter.ArrayByRefUpdater.UndefineTemps(), System.Linq.Expressions.Interpreter.FieldByRefUpdater.UndefineTemps(), System.Linq.Expressions.Interpreter.IndexMethodByRefUpdater.UndefineTemps(), and System.Linq.Expressions.Interpreter.PropertyByRefUpdater.UndefineTemps().