Terraria: System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal
DefineLocal()
LocalDefinition System.Linq.Expressions.Interpreter.LocalVariables.DefineLocal (ParameterExpression variable, int start) inline
Definition at line 40 of file LocalVariables.cs.
    {
        LocalVariable localVariable = new LocalVariable(_localCount++, closure: false);
        _maxLocalCount = Math.Max(_localCount, _maxLocalCount);
        VariableScope variableScope;
        if (_variables.TryGetValue(variable, out var value))
        {
            variableScope = new VariableScope(localVariable, start, value);
            if (value.ChildScopes == null)
            {
                value.ChildScopes = new List<VariableScope>();
            }
            value.ChildScopes.Add(variableScope);
        }
        else
        {
            variableScope = new VariableScope(localVariable, start, null);
        }
        _variables[variable] = variableScope;
        return new LocalDefinition(localVariable.Index, variable);
    }
References System.Linq.Expressions.Interpreter.LocalVariables._localCount, System.Linq.Expressions.Interpreter.LocalVariables._maxLocalCount, System.Linq.Expressions.Interpreter.LocalVariables._variables, System.Math.Max(), System.start, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileArrayIndexAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBlockStart(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMultiDimArrayAccess(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTop(), and System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression().