Terraria: System.Data.RBTree.GetIndexOfPageWithFreeSlot
GetIndexOfPageWithFreeSlot()
int System.Data.RBTree< K >.GetIndexOfPageWithFreeSlot (bool allocatedPage) inline private
Definition at line 342 of file RBTree.cs.
    {
        int i = _nextFreePageLine;
        int result = -1;
        for (; i < _pageTableMap.Length; i++)
        {
            if ((uint)_pageTableMap[i] >= uint.MaxValue)
            {
                continue;
            }
            uint num = (uint)_pageTableMap[i];
            while ((num ^ 0xFFFFFFFFu) != 0)
            {
                uint num2 = ~num & (num + 1);
                if ((_pageTableMap[i] & num2) != 0L)
                {
                    throw ExceptionBuilder.InternalRBTreeError(RBTreeError.PagePositionInSlotInUse);
                }
                result = i * 32 + GetIntValueFromBitMap(num2);
                if (allocatedPage)
                {
                    if (_pageTable[result] != null)
                    {
                        return result;
                    }
                }
                else if (_pageTable[result] == null)
                {
                    return result;
                }
                result = -1;
                num |= num2;
            }
        }
        if (_nextFreePageLine != 0)
        {
            _nextFreePageLine = 0;
            result = GetIndexOfPageWithFreeSlot(allocatedPage);
        }
        return result;
    }
References System.Data.RBTree< K >._nextFreePageLine, System.Data.RBTree< K >._pageTable, System.Data.RBTree< K >._pageTableMap, System.Data.RBTree< K >.GetIndexOfPageWithFreeSlot(), System.Data.RBTree< K >.GetIntValueFromBitMap(), System.Data.ExceptionBuilder.InternalRBTreeError(), and System.L.
Referenced by System.Data.RBTree< K >.AllocPage(), System.Data.RBTree< K >.GetIndexOfPageWithFreeSlot(), and System.Data.RBTree< K >.GetNewNode().