Terraria: System.Data.RBTree.Key
Key()
K System.Data.RBTree< K >.Key (int nodeId) inline
Definition at line 1407 of file RBTree.cs.
    {
        return _pageTable[nodeId >> 16]._slots[nodeId & 0xFFFF]._keyOfNode;
    }
References System.Data.RBTree< K >.Node._keyOfNode, System.Data.RBTree< K >._pageTable, and System.Data.RBTree< K >.TreePage._slots.
Referenced by System.Data.RBTree< K >.CopyTo(), System.Data.RBTree< K >.CopyTo(), System.Data.RBTree< K >.DeleteByIndex(), System.Data.Index.FindNodeByKey(), System.Data.Index.FindNodeByKeyRecord(), System.Data.Index.FindNodeByKeys(), System.Data.Index.FindRecords< TKey, TRow >(), System.Data.RBTree< K >.GetIndexByNode(), System.Data.RBTree< K >.GetNodeByKey(), System.Data.Index.GetUniqueKeyValues(), System.Data.RBTree< K >.IndexOf(), System.Data.RBTree< K >.LeftRotate(), System.Data.RBTree< K >.RBDeleteX(), System.Data.RBTree< K >.RBInsert(), System.Data.RBTree< K >.RightRotate(), System.Data.RBTree< K >.Search(), and System.Data.RBTree< K >.SearchSubTree().