Terraria: System.Data.RBTree.GetIndexByNode
GetIndexByNode()
int System.Data.RBTree< K >.GetIndexByNode (int node) inline
Definition at line 1087 of file RBTree.cs.
    {
        if (_inUseSatelliteTreeCount == 0)
        {
            return ComputeIndexByNode(node);
        }
        if (Next(node) != 0)
        {
            return ComputeIndexWithSatelliteByNode(node);
        }
        int num = SearchSubTree(0, Key(node));
        if (num == node)
        {
            return ComputeIndexWithSatelliteByNode(node);
        }
        return ComputeIndexWithSatelliteByNode(num) + ComputeIndexByNode(node);
    }
References System.Data.RBTree< K >._inUseSatelliteTreeCount, System.Data.RBTree< K >.ComputeIndexByNode(), System.Data.RBTree< K >.ComputeIndexWithSatelliteByNode(), System.Data.RBTree< K >.Key(), System.Data.RBTree< K >.Next(), and System.Data.RBTree< K >.SearchSubTree().
Referenced by System.Data.Index.FindRecord(), System.Data.Index.FindRecordByKey(), System.Data.Index.FindRecordByKey(), System.Data.Index.GetRangeFromNode(), System.Data.RBTree< K >.IndexOf(), and System.Data.Index.InsertRecord().