Terraria: System.Data.RBTree.Successor
Successor() [1/2]
int System.Data.RBTree< K >.Successor (int x_id) inline private
Definition at line 400 of file RBTree.cs.
    {
        if (Right(x_id) != 0)
        {
            return Minimum(Right(x_id));
        }
        int num = Parent(x_id);
        while (num != 0 && x_id == Right(num))
        {
            x_id = num;
            num = Parent(num);
        }
        return num;
    }
References System.Data.RBTree< K >.Minimum(), System.Data.Parent, and System.Data.Right.
Referenced by System.Data.RBTree< K >.CopyTo(), System.Data.RBTree< K >.CopyTo(), System.Data.RBTree< K >.RBDeleteX(), and System.Data.RBTree< K >.Successor().