Terraria: System.Data.RBTree.Search
Search()
int System.Data.RBTree< K >.Search (K key) inline
Definition at line 1047 of file RBTree.cs.
    {
        int num = root;
        while (num != 0)
        {
            int num2 = CompareNode(key, Key(num));
            if (num2 == 0)
            {
                break;
            }
            num = ((num2 >= 0) ? Right(num) : Left(num));
        }
        return num;
    }
References System.Data.RBTree< K >.CompareNode(), System.Data.RBTree< K >.Key(), System.key, System.Collections.Generic.Left, System.Data.Right, and System.Data.RBTree< K >.root.
Referenced by System.Data.Index.FindRecord().