Terraria: System.Data.RBTree.ComputeNodeByIndex
ComputeNodeByIndex() [1/2]
int System.Data.RBTree< K >.ComputeNodeByIndex (int index, out int satelliteRootId) inline private
Definition at line 1172 of file RBTree.cs.
    {
        index++;
        satelliteRootId = 0;
        int num = root;
        int num2 = -1;
        while (num != 0 && ((num2 = SubTreeSize(Left(num)) + 1) != index || Next(num) != 0))
        {
            if (index < num2)
            {
                num = Left(num);
                continue;
            }
            if (Next(num) != 0 && index >= num2 && index <= num2 + SubTreeSize(Next(num)) - 1)
            {
                satelliteRootId = num;
                index = index - num2 + 1;
                return ComputeNodeByIndex(Next(num), index);
            }
            index = ((Next(num) != 0) ? (index - (num2 + SubTreeSize(Next(num)) - 1)) : (index - num2));
            num = Right(num);
        }
        return num;
    }
References System.Data.RBTree< K >.ComputeNodeByIndex(), System.index, System.Collections.Generic.Left, System.Data.RBTree< K >.Next(), System.Data.Right, System.Data.RBTree< K >.root, and System.Data.RBTree< K >.SubTreeSize().
Referenced by System.Data.RBTree< K >.ComputeNodeByIndex(), and System.Data.RBTree< K >.GetNodeByIndex().