Terraria: System.Data.RBTree.CopyTo
CopyTo() [2/2]
void System.Data.RBTree< K >.CopyTo (K[] array, int index) inline
Definition at line 1303 of file RBTree.cs.
    {
        if (array == null)
        {
            throw ExceptionBuilder.ArgumentNull("array");
        }
        if (index < 0)
        {
            throw ExceptionBuilder.ArgumentOutOfRange("index");
        }
        int count = Count;
        if (array.Length - index < Count)
        {
            throw ExceptionBuilder.InvalidOffsetLength();
        }
        int num = Minimum(root);
        for (int i = 0; i < count; i++)
        {
            array[index + i] = Key(num);
            num = Successor(num);
        }
    }
References System.Data.ExceptionBuilder.ArgumentNull(), System.Data.ExceptionBuilder.ArgumentOutOfRange(), System.array, System.Data.RBTree< K >.Count, System.count, System.index, System.Data.ExceptionBuilder.InvalidOffsetLength(), System.Data.RBTree< K >.Key(), System.Data.RBTree< K >.Minimum(), System.Data.RBTree< K >.root, and System.Data.RBTree< K >.Successor().