Terraria: System.Data.RBTree.LeftRotate
LeftRotate()
int System.Data.RBTree< K >.LeftRotate (int root_id, int x_id, int mainTreeNode) inline private
Definition at line 456 of file RBTree.cs.
    {
        int num = Right(x_id);
        SetRight(x_id, Left(num));
        if (Left(num) != 0)
        {
            SetParent(Left(num), x_id);
        }
        SetParent(num, Parent(x_id));
        if (Parent(x_id) == 0)
        {
            if (root_id == 0)
            {
                root = num;
            }
            else
            {
                SetNext(mainTreeNode, num);
                SetKey(mainTreeNode, Key(num));
                root_id = num;
            }
        }
        else if (x_id == Left(Parent(x_id)))
        {
            SetLeft(Parent(x_id), num);
        }
        else
        {
            SetRight(Parent(x_id), num);
        }
        SetLeft(num, x_id);
        SetParent(x_id, num);
        if (x_id != 0)
        {
            SetSubTreeSize(x_id, SubTreeSize(Left(x_id)) + SubTreeSize(Right(x_id)) + ((Next(x_id) == 0) ? 1 : SubTreeSize(Next(x_id))));
        }
        if (num != 0)
        {
            SetSubTreeSize(num, SubTreeSize(Left(num)) + SubTreeSize(Right(num)) + ((Next(num) == 0) ? 1 : SubTreeSize(Next(num))));
        }
        return root_id;
    }
References System.Data.RBTree< K >.Key(), System.Collections.Generic.Left, System.Data.RBTree< K >.Next(), System.Data.Parent, System.Data.Right, System.Data.RBTree< K >.root, System.Data.RBTree< K >.SetKey(), System.Data.RBTree< K >.SetLeft(), System.Data.RBTree< K >.SetNext(), System.Data.RBTree< K >.SetParent(), System.Data.RBTree< K >.SetRight(), System.Data.RBTree< K >.SetSubTreeSize(), and System.Data.RBTree< K >.SubTreeSize().
Referenced by System.Data.RBTree< K >.RBDeleteFixup(), and System.Data.RBTree< K >.RBInsert().