Terraria: System.Data.RBTree.GetNodeByIndex
GetNodeByIndex()
NodePath System.Data.RBTree< K >.GetNodeByIndex (int userIndex) inline private
Definition at line 1148 of file RBTree.cs.
    {
        int num;
        int satelliteRootId;
        if (_inUseSatelliteTreeCount == 0)
        {
            num = ComputeNodeByIndex(root, userIndex + 1);
            satelliteRootId = 0;
        }
        else
        {
            num = ComputeNodeByIndex(userIndex, out satelliteRootId);
        }
        if (num == 0)
        {
            if (TreeAccessMethod.INDEX_ONLY == _accessMethod)
            {
                throw ExceptionBuilder.RowOutOfRange(userIndex);
            }
            throw ExceptionBuilder.InternalRBTreeError(RBTreeError.IndexOutOFRangeinGetNodeByIndex);
        }
        return new NodePath(num, satelliteRootId);
    }
References System.Data.RBTree< K >._accessMethod, System.Data.RBTree< K >._inUseSatelliteTreeCount, System.Data.RBTree< K >.ComputeNodeByIndex(), System.Data.ExceptionBuilder.InternalRBTreeError(), System.Data.RBTree< K >.root, and System.Data.ExceptionBuilder.RowOutOfRange().
Referenced by System.Data.RBTree< K >.DeleteByIndex().