Terraria: System.Data.RBTree.GetNodeByKey
GetNodeByKey()
NodePath System.Data.RBTree< K >.GetNodeByKey (K key) inline private
Definition at line 1062 of file RBTree.cs.
    {
        int num = SearchSubTree(0, key);
        if (Next(num) != 0)
        {
            return new NodePath(SearchSubTree(Next(num), key), num);
        }
        if (!Key(num).Equals(key))
        {
            num = 0;
        }
        return new NodePath(num, 0);
    }
References System.Data.RBTree< K >.Key(), System.key, System.Data.RBTree< K >.Next(), and System.Data.RBTree< K >.SearchSubTree().
Referenced by System.Data.RBTree< K >.GetIndexByKey(), and System.Data.RBTree< K >.UpdateNodeKey().