Terraria: System.Data.RBTree.DeleteByIndex
DeleteByIndex()
K System.Data.RBTree< K >.DeleteByIndex (int i) inline
Definition at line 746 of file RBTree.cs.
    {
        NodePath nodeByIndex = GetNodeByIndex(i);
        K result = Key(nodeByIndex._nodeID);
        RBDeleteX(0, nodeByIndex._nodeID, nodeByIndex._mainTreeNodeID);
        return result;
    }
References System.Data.RBTree< K >.GetNodeByIndex(), System.Data.RBTree< K >.Key(), and System.Data.RBTree< K >.RBDeleteX().
Referenced by System.Data.Index.DeleteRecord(), System.Data.Index.RecordStateChanged(), and System.Data.RBTree< K >.RemoveAt().