Terraria: System.Data.RBTree.RBInsert
RBInsert()
int System.Data.RBTree< K >.RBInsert (int root_id, int x_id, int mainTreeNodeID, int position, bool append) inline private
Definition at line 542 of file RBTree.cs.
    {
        _version++;
        int num = 0;
        int num2 = ((root_id == 0) ? root : root_id);
        if (_accessMethod == TreeAccessMethod.KEY_SEARCH_AND_INDEX && !append)
        {
            while (num2 != 0)
            {
                IncreaseSize(num2);
                num = num2;
                int num3 = ((root_id == 0) ? CompareNode(Key(x_id), Key(num2)) : CompareSateliteTreeNode(Key(x_id), Key(num2)));
                if (num3 < 0)
                {
                    num2 = Left(num2);
                    continue;
                }
                if (num3 > 0)
                {
                    num2 = Right(num2);
                    continue;
                }
                if (root_id != 0)
                {
                    throw ExceptionBuilder.InternalRBTreeError(RBTreeError.InvalidStateinInsert);
                }
                if (Next(num2) != 0)
                {
                    root_id = RBInsert(Next(num2), x_id, num2, -1, append: false);
                    SetKey(num2, Key(Next(num2)));
                }
                else
                {
                    int num4 = 0;
                    num4 = GetNewNode(Key(num2));
                    _inUseSatelliteTreeCount++;
                    SetNext(num4, num2);
                    SetColor(num4, color(num2));
                    SetParent(num4, Parent(num2));
                    SetLeft(num4, Left(num2));
                    SetRight(num4, Right(num2));
                    if (Left(Parent(num2)) == num2)
                    {
                        SetLeft(Parent(num2), num4);
                    }
                    else if (Right(Parent(num2)) == num2)
                    {
                        SetRight(Parent(num2), num4);
                    }
                    if (Left(num2) != 0)
                    {
                        SetParent(Left(num2), num4);
                    }
                    if (Right(num2) != 0)
                    {
                        SetParent(Right(num2), num4);
                    }
                    if (root == num2)
                    {
                        root = num4;
                    }
                    SetColor(num2, NodeColor.black);
                    SetParent(num2, 0);
                    SetLeft(num2, 0);
                    SetRight(num2, 0);
                    int size = SubTreeSize(num2);
                    SetSubTreeSize(num2, 1);
                    root_id = RBInsert(num2, x_id, num4, -1, append: false);
                    SetSubTreeSize(num4, size);
                }
                return root_id;
            }
        }
        else
        {
            if (!(_accessMethod == TreeAccessMethod.INDEX_ONLY || append))
            {
                throw ExceptionBuilder.InternalRBTreeError(RBTreeError.UnsupportedAccessMethod1);
            }
            if (position == -1)
            {
                position = SubTreeSize(root);
            }
            while (num2 != 0)
            {
                IncreaseSize(num2);
                num = num2;
                int num5 = position - SubTreeSize(Left(num));
                if (num5 <= 0)
                {
                    num2 = Left(num2);
                    continue;
                }
                num2 = Right(num2);
                if (num2 != 0)
                {
                    position = num5 - 1;
                }
            }
        }
        SetParent(x_id, num);
        if (num == 0)
        {
            if (root_id == 0)
            {
                root = x_id;
            }
            else
            {
                SetNext(mainTreeNodeID, x_id);
                SetKey(mainTreeNodeID, Key(x_id));
                root_id = x_id;
            }
        }
        else
        {
            int num6 = 0;
            if (_accessMethod == TreeAccessMethod.KEY_SEARCH_AND_INDEX)
            {
                num6 = ((root_id == 0) ? CompareNode(Key(x_id), Key(num)) : CompareSateliteTreeNode(Key(x_id), Key(num)));
            }
            else
            {
                if (_accessMethod != TreeAccessMethod.INDEX_ONLY)
                {
                    throw ExceptionBuilder.InternalRBTreeError(RBTreeError.UnsupportedAccessMethod2);
                }
                num6 = ((position > 0) ? 1 : (-1));
            }
            if (num6 < 0)
            {
                SetLeft(num, x_id);
            }
            else
            {
                SetRight(num, x_id);
            }
        }
        SetLeft(x_id, 0);
        SetRight(x_id, 0);
        SetColor(x_id, NodeColor.red);
        num2 = x_id;
        while (color(Parent(x_id)) == NodeColor.red)
        {
            if (Parent(x_id) == Left(Parent(Parent(x_id))))
            {
                num = Right(Parent(Parent(x_id)));
                if (color(num) == NodeColor.red)
                {
                    SetColor(Parent(x_id), NodeColor.black);
                    SetColor(num, NodeColor.black);
                    SetColor(Parent(Parent(x_id)), NodeColor.red);
                    x_id = Parent(Parent(x_id));
                    continue;
                }
                if (x_id == Right(Parent(x_id)))
                {
                    x_id = Parent(x_id);
                    root_id = LeftRotate(root_id, x_id, mainTreeNodeID);
                }
                SetColor(Parent(x_id), NodeColor.black);
                SetColor(Parent(Parent(x_id)), NodeColor.red);
                root_id = RightRotate(root_id, Parent(Parent(x_id)), mainTreeNodeID);
                continue;
            }
            num = Left(Parent(Parent(x_id)));
            if (color(num) == NodeColor.red)
            {
                SetColor(Parent(x_id), NodeColor.black);
                SetColor(num, NodeColor.black);
                SetColor(Parent(Parent(x_id)), NodeColor.red);
                x_id = Parent(Parent(x_id));
                continue;
            }
            if (x_id == Left(Parent(x_id)))
            {
                x_id = Parent(x_id);
                root_id = RightRotate(root_id, x_id, mainTreeNodeID);
            }
            SetColor(Parent(x_id), NodeColor.black);
            SetColor(Parent(Parent(x_id)), NodeColor.red);
            root_id = LeftRotate(root_id, Parent(Parent(x_id)), mainTreeNodeID);
        }
        if (root_id == 0)
        {
            SetColor(root, NodeColor.black);
        }
        else
        {
            SetColor(root_id, NodeColor.black);
        }
        return root_id;
    }
References System.Data.RBTree< K >._accessMethod, System.Data.RBTree< K >._inUseSatelliteTreeCount, System.Data.RBTree< K >._version, System.Data.RBTree< K >.color(), System.Data.RBTree< K >.CompareNode(), System.Data.RBTree< K >.CompareSateliteTreeNode(), System.Data.RBTree< K >.GetNewNode(), System.Data.RBTree< K >.IncreaseSize(), System.Data.ExceptionBuilder.InternalRBTreeError(), System.Data.RBTree< K >.Key(), System.Collections.Generic.Left, System.Data.RBTree< K >.LeftRotate(), System.Data.RBTree< K >.Next(), System.Data.Parent, System.Data.RBTree< K >.RBInsert(), System.Data.Right, System.Data.RBTree< K >.RightRotate(), System.Data.RBTree< K >.root, System.Data.RBTree< K >.SetColor(), System.Data.RBTree< K >.SetKey(), System.Data.RBTree< K >.SetLeft(), System.Data.RBTree< K >.SetNext(), System.Data.RBTree< K >.SetParent(), System.Data.RBTree< K >.SetRight(), System.Data.RBTree< K >.SetSubTreeSize(), and System.Data.RBTree< K >.SubTreeSize().
Referenced by System.Data.RBTree< K >.Add(), System.Data.RBTree< K >.Insert(), System.Data.RBTree< K >.InsertAt(), and System.Data.RBTree< K >.RBInsert().