Terraria: System.Data.RBTree.ComputeIndexWithSatelliteByNode
ComputeIndexWithSatelliteByNode()
int System.Data.RBTree< K >.ComputeIndexWithSatelliteByNode (int nodeId) inline private
Definition at line 1133 of file RBTree.cs.
    {
        int num = SubTreeSize(Left(nodeId));
        while (nodeId != 0)
        {
            int num2 = Parent(nodeId);
            if (nodeId == Right(num2))
            {
                num += SubTreeSize(Left(num2)) + ((Next(num2) == 0) ? 1 : SubTreeSize(Next(num2)));
            }
            nodeId = num2;
        }
        return num;
    }
References System.Collections.Generic.Left, System.Data.RBTree< K >.Next(), System.Data.Parent, System.Data.Right, and System.Data.RBTree< K >.SubTreeSize().
Referenced by System.Data.RBTree< K >.GetIndexByNode(), and System.Data.RBTree< K >.GetIndexByNodePath().