Terraria: System.Data.RBTree.Left
Left()
int System.Data.RBTree< K >.Left (int nodeId) inline
Definition at line 1382 of file RBTree.cs.
    {
        return _pageTable[nodeId >> 16]._slots[nodeId & 0xFFFF]._leftId;
    }
References System.Data.RBTree< K >.Node._leftId, System.Data.RBTree< K >._pageTable, and System.Data.RBTree< K >.TreePage._slots.
Referenced by System.Data.Index.FindNodeByKey(), System.Data.Index.FindNodeByKeyRecord(), System.Data.Index.FindNodeByKeys(), System.Data.Index.FindRecords< TKey, TRow >(), and System.Data.Index.GetUniqueKeyValues().