Terraria: System.Data.RBTree.IndexOf
IndexOf()
int System.Data.RBTree< K >.IndexOf (int nodeId, K item) inline
Definition at line 1237 of file RBTree.cs.
    {
        int result = -1;
        if (nodeId != 0)
        {
            if ((object)Key(nodeId) == (object)item)
            {
                return GetIndexByNode(nodeId);
            }
            if ((result = IndexOf(Left(nodeId), item)) != -1)
            {
                return result;
            }
            result = IndexOf(Right(nodeId), item);
            _ = -1;
            return result;
        }
        return result;
    }
References System.Data.RBTree< K >.GetIndexByNode(), System.Data.RBTree< K >.IndexOf(), System.item, System.Data.RBTree< K >.Key(), System.Collections.Generic.Left, and System.Data.Right.
Referenced by System.Data.DataRowCollection.IndexOf(), and System.Data.RBTree< K >.IndexOf().