Terraria: System.Data.RBTree.InitTree
InitTree()
void System.Data.RBTree< K >.InitTree () inline private
Definition at line 237 of file RBTree.cs.
    {
        root = 0;
        _pageTable = new TreePage[32];
        _pageTableMap = new int[(_pageTable.Length + 32 - 1) / 32];
        _inUsePageCount = 0;
        _nextFreePageLine = 0;
        AllocPage(32);
        _pageTable[0]._slots[0]._nodeColor = NodeColor.black;
        _pageTable[0]._slotMap[0] = 1;
        _pageTable[0].InUseCount = 1;
        _inUseNodeCount = 1;
        _inUseSatelliteTreeCount = 0;
    }
References System.Data.RBTree< K >._inUseNodeCount, System.Data.RBTree< K >._inUsePageCount, System.Data.RBTree< K >._inUseSatelliteTreeCount, System.Data.RBTree< K >._nextFreePageLine, System.Data.RBTree< K >.Node._nodeColor, System.Data.RBTree< K >._pageTable, System.Data.RBTree< K >._pageTableMap, System.Data.RBTree< K >.TreePage._slotMap, System.Data.RBTree< K >.TreePage._slots, System.Data.RBTree< K >.AllocPage(), System.Data.RBTree< K >.TreePage.InUseCount, and System.Data.RBTree< K >.root.
Referenced by System.Data.RBTree< K >.RBTree(), and System.Data.RBTree< K >.Clear().