Terraria: System.Data.RBTree.Successor
Successor() [2/2]
bool System.Data.RBTree< K >.Successor (ref int nodeId, ref int mainTreeNodeId) inline private
Definition at line 415 of file RBTree.cs.
    {
        if (nodeId == 0)
        {
            nodeId = Minimum(mainTreeNodeId);
            mainTreeNodeId = 0;
        }
        else
        {
            nodeId = Successor(nodeId);
            if (nodeId == 0 && mainTreeNodeId != 0)
            {
                nodeId = Successor(mainTreeNodeId);
                mainTreeNodeId = 0;
            }
        }
        if (nodeId != 0)
        {
            if (Next(nodeId) != 0)
            {
                if (mainTreeNodeId != 0)
                {
                    throw ExceptionBuilder.InternalRBTreeError(RBTreeError.NestedSatelliteTreeEnumerator);
                }
                mainTreeNodeId = nodeId;
                nodeId = Minimum(Next(nodeId));
            }
            return true;
        }
        return false;
    }
References System.Data.ExceptionBuilder.InternalRBTreeError(), System.Data.RBTree< K >.Minimum(), System.Data.RBTree< K >.Next(), and System.Data.RBTree< K >.Successor().