Terraria: Interop.Winsock.EnsureInitialized
EnsureInitialized() [3/3]
static void Interop.Winsock.EnsureInitialized () inline static package
Definition at line 337 of file Interop.cs.
        {
            if (s_initialized == 0)
            {
                Initialize();
            }
            unsafe static void Initialize()
            {
                Unsafe.SkipInit(out WSAData wSAData);
                SocketError socketError = WSAStartup(514, &wSAData);
                if (socketError != 0)
                {
                    throw new SocketException((int)socketError);
                }
                if (Interlocked.CompareExchange(ref s_initialized, 1, 0) != 0)
                {
                    socketError = WSACleanup();
                }
            }
        }
References System.Threading.Interlocked.CompareExchange(), Interop.Winsock.s_initialized, Interop.Winsock.WSACleanup(), and Interop.Winsock.WSAStartup().