Terraria: MS.Internal.Xml.XPath.VariableQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.VariableQuery.Evaluate (XPathNodeIterator nodeIterator) inline
Definition at line 56 of file VariableQuery.cs.
    {
        if (xsltContext == null)
        {
            throw XPathException.Create(System.SR.Xp_NoContext);
        }
        return ProcessResult(_variable.Evaluate(xsltContext));
    }
References MS.Internal.Xml.XPath.VariableQuery._variable, System.Xml.XPath.XPathException.Create(), System.Xml.Xsl.IXsltContextVariable.Evaluate(), MS.Internal.Xml.XPath.ExtensionQuery.ProcessResult(), System.SR.Xp_NoContext, and MS.Internal.Xml.XPath.ExtensionQuery.xsltContext.