Terraria: SnapPoint.Calculate
Calculate()
void SnapPoint.Calculate (UIElement element) inline
     {
         CalculatedStyle dimensions = element.GetDimensions();
         Position = dimensions.Position() + _offset + _anchor * new Vector2(dimensions.Width, dimensions.Height);
     }
References _anchor, _offset, UIElement.GetDimensions(), CalculatedStyle.Height, CalculatedStyle.Position(), Position, and CalculatedStyle.Width.
Referenced by UIElement.GetSnapPoint(), and UIDynamicItemCollection.GetSnapPoints().