Terraria: System.Xml.XmlElement.SetAttribute
SetAttribute() [2/2]
virtual void System.Xml.XmlElement.SetAttribute (string name, string? value) inline virtual
Definition at line 292 of file XmlElement.cs.
    {
        XmlAttribute attributeNode = GetAttributeNode(name);
        if (attributeNode == null)
        {
            attributeNode = OwnerDocument.CreateAttribute(name);
            attributeNode.Value = value;
            Attributes.InternalAppendAttribute(attributeNode);
        }
        else
        {
            attributeNode.Value = value;
        }
    }
References System.Xml.XmlElement.Attributes, System.Xml.XmlDocument.CreateAttribute(), System.Xml.Dictionary, System.Xml.XmlElement.GetAttributeNode(), System.Xml.XmlAttributeCollection.InternalAppendAttribute(), System.Xml.XmlElement.OwnerDocument, and System.value.
Referenced by System.Data.XmlTreeGen.AddColumnProperties(), System.Data.XmlTreeGen.AddXdoProperty(), System.Data.XmlTreeGen.FillDataSetElement(), System.Data.XmlTreeGen.GetSchema(), System.Data.XmlTreeGen.HandleColumn(), System.Data.XmlTreeGen.HandleColumnType(), System.Data.XmlTreeGen.HandleRelation(), System.Data.XmlTreeGen.HandleTable(), System.Data.XmlTreeGen.SchemaTree(), System.Data.XmlTreeGen.SetMSDataAttribute(), and System.Data.SimpleType.ToNode().