Terraria: System.Xml.XmlElement.WriteTo
WriteTo()
override void System.Xml.XmlElement.WriteTo (XmlWriter w) inline
Definition at line 425 of file XmlElement.cs.
    {
        if (GetType() == typeof(XmlElement))
        {
            WriteElementTo(w, this);
            return;
        }
        WriteStartElement(w);
        if (IsEmpty)
        {
            w.WriteEndElement();
            return;
        }
        WriteContentTo(w);
        w.WriteFullEndElement();
    }
References System.Xml.Dictionary, System.Xml.XmlElement.IsEmpty, System.Xml.XmlElement.WriteContentTo(), System.Xml.XmlElement.WriteElementTo(), and System.Xml.XmlElement.WriteStartElement().