Terraria: System.Xml.XmlElement.CloneNode
CloneNode()
override XmlNode System.Xml.XmlElement.CloneNode (bool deep) inline
Definition at line 198 of file XmlElement.cs.
    {
        XmlDocument ownerDocument = OwnerDocument;
        bool isLoading = ownerDocument.IsLoading;
        ownerDocument.IsLoading = true;
        XmlElement xmlElement = ownerDocument.CreateElement(Prefix, LocalName, NamespaceURI);
        ownerDocument.IsLoading = isLoading;
        if (xmlElement.IsEmpty != IsEmpty)
        {
            xmlElement.IsEmpty = IsEmpty;
        }
        if (HasAttributes)
        {
            foreach (XmlAttribute attribute in Attributes)
            {
                XmlAttribute xmlAttribute2 = (XmlAttribute)attribute.CloneNode(deep: true);
                if (xmlAttribute2 is XmlUnspecifiedAttribute xmlUnspecifiedAttribute && !attribute.Specified)
                {
                    xmlUnspecifiedAttribute.SetSpecified(f: false);
                }
                xmlElement.Attributes.InternalAppendAttribute(xmlAttribute2);
            }
        }
        if (deep)
        {
            xmlElement.CopyChildren(ownerDocument, this, deep);
        }
        return xmlElement;
    }
References System.Xml.XmlElement.Attributes, System.Xml.XmlNode.Attributes, System.Xml.XmlAttribute.CloneNode(), System.Xml.XmlNode.CopyChildren(), System.Xml.Dictionary, System.Xml.XmlElement.HasAttributes, System.Xml.XmlAttributeCollection.InternalAppendAttribute(), System.Xml.XmlElement.IsEmpty, System.Xml.XmlDocument.IsLoading, System.Xml.XmlElement.LocalName, System.Xml.XmlElement.NamespaceURI, System.Xml.XmlElement.OwnerDocument, System.Xml.XmlElement.Prefix, and System.Xml.XmlUnspecifiedAttribute.Specified.