Terraria: System.Xml.XmlElement.AppendChildForLoad
AppendChildForLoad()
override XmlNode System.Xml.XmlElement.AppendChildForLoad (XmlNode newChild, XmlDocument doc) inline package virtual
Reimplemented from System.Xml.XmlNode.
Definition at line 228 of file XmlElement.cs.
    {
        XmlNodeChangedEventArgs insertEventArgsForLoad = doc.GetInsertEventArgsForLoad(newChild, this);
        if (insertEventArgsForLoad != null)
        {
            doc.BeforeEvent(insertEventArgsForLoad);
        }
        XmlLinkedNode xmlLinkedNode = (XmlLinkedNode)newChild;
        if (_lastChild == null || _lastChild == this)
        {
            xmlLinkedNode.next = xmlLinkedNode;
            _lastChild = xmlLinkedNode;
            xmlLinkedNode.SetParentForLoad(this);
        }
        else
        {
            XmlLinkedNode lastChild = _lastChild;
            xmlLinkedNode.next = lastChild.next;
            lastChild.next = xmlLinkedNode;
            _lastChild = xmlLinkedNode;
            if (lastChild.IsText && xmlLinkedNode.IsText)
            {
                XmlNode.NestTextNodes(lastChild, xmlLinkedNode);
            }
            else
            {
                xmlLinkedNode.SetParentForLoad(this);
            }
        }
        if (insertEventArgsForLoad != null)
        {
            doc.AfterEvent(insertEventArgsForLoad);
        }
        return xmlLinkedNode;
    }
References System.Xml.XmlLinkedNode.XmlLinkedNode(), System.Xml.XmlElement._lastChild, System.Xml.Dictionary, System.Xml.XmlNode.NestTextNodes(), System.Xml.XmlLinkedNode.next, and System.Xml.XmlNode.SetParentForLoad().