Terraria: System.Net.Mail.CheckCommand.BeginSend
BeginSend()
static IAsyncResult System.Net.Mail.CheckCommand.BeginSend (SmtpConnection conn, AsyncCallback callback, object state) inline static package
Definition at line 12 of file CheckCommand.cs.
    {
        MultiAsyncResult multiAsyncResult = new MultiAsyncResult(conn, callback, state);
        multiAsyncResult.Enter();
        IAsyncResult asyncResult = conn.BeginFlush(s_onWrite, multiAsyncResult);
        if (asyncResult.CompletedSynchronously)
        {
            conn.EndFlush(asyncResult);
            multiAsyncResult.Leave();
        }
        SmtpReplyReader nextReplyReader = conn.Reader.GetNextReplyReader();
        multiAsyncResult.Enter();
        IAsyncResult asyncResult2 = nextReplyReader.BeginReadLine(s_onReadLine, multiAsyncResult);
        if (asyncResult2.CompletedSynchronously)
        {
            LineInfo lineInfo = nextReplyReader.EndReadLine(asyncResult2);
            if (!(multiAsyncResult.Result is Exception))
            {
                multiAsyncResult.Result = lineInfo;
            }
            multiAsyncResult.Leave();
        }
        multiAsyncResult.CompleteSequence();
        return multiAsyncResult;
    }
References System.asyncResult, System.Net.Mail.SmtpConnection.BeginFlush(), System.Net.Mail.SmtpReplyReader.BeginReadLine(), System.IAsyncResult.CompletedSynchronously, System.Net.Mime.MultiAsyncResult.CompleteSequence(), System.Net.Mail.SmtpConnection.EndFlush(), System.Net.Mail.SmtpReplyReader.EndReadLine(), System.Net.Mime.MultiAsyncResult.Enter(), System.Net.Mail.SmtpReplyReaderFactory.GetNextReplyReader(), System.Net.Mime.MultiAsyncResult.Leave(), System.Net.Mail.SmtpConnection.Reader, System.Net.LazyAsyncResult.Result, System.Net.Mail.CheckCommand.s_onReadLine, System.Net.Mail.CheckCommand.s_onWrite, and System.state.
Referenced by System.Net.Mail.DataCommand.BeginSend(), System.Net.Mail.StartTlsCommand.BeginSend(), System.Net.Mail.MailCommand.BeginSend(), System.Net.Mail.HelloCommand.BeginSend(), and System.Net.Mail.RecipientCommand.BeginSend().