Terraria: System.Net.Mail.CheckCommand.Send
Send()
static SmtpStatusCode System.Net.Mail.CheckCommand.Send (SmtpConnection conn, out string response) inline static package
Definition at line 91 of file CheckCommand.cs.
    {
        conn.Flush();
        SmtpReplyReader nextReplyReader = conn.Reader.GetNextReplyReader();
        LineInfo lineInfo = nextReplyReader.ReadLine();
        response = lineInfo.Line;
        nextReplyReader.Close();
        return lineInfo.StatusCode;
    }
References System.Net.Mail.SmtpReplyReader.Close(), System.Net.Mail.SmtpConnection.Flush(), System.Net.Mail.SmtpReplyReaderFactory.GetNextReplyReader(), System.Net.Mail.LineInfo.Line, System.Net.Mail.SmtpConnection.Reader, System.Net.Mail.SmtpReplyReader.ReadLine(), and System.Net.Mail.LineInfo.StatusCode.
Referenced by System.Net.Mail.DataCommand.Send(), System.Net.Mail.DataStopCommand.Send(), System.Net.Mail.StartTlsCommand.Send(), System.Net.Mail.MailCommand.Send(), System.Net.Mail.HelloCommand.Send(), and System.Net.Mail.RecipientCommand.Send().