Terraria: Microsoft.Xna.Framework.Graphics.VertexBuffer.CreateBuffer
CreateBuffer()
unsafe void Microsoft.Xna.Framework.Graphics.VertexBuffer.CreateBuffer (VertexDeclaration vertexDeclaration, uint dwVertexCount, uint usage, _D3DPOOL pool) inline protected
Definition at line 436 of file VertexBuffer.cs.
    {
        isDisposed = false;
        if (vertexDeclaration.isDisposed)
        {
            throw new ObjectDisposedException(typeof(VertexDeclaration).Name);
        }
        GraphicsDevice parent = ((GraphicsResource)vertexDeclaration)._parent;
        GraphicsDevice parent2 = _parent;
        if (parent != parent2)
        {
            vertexDeclaration.Bind(parent2);
        }
        uint num = (uint)vertexDeclaration._vertexStride * dwVertexCount;
        int maxVertexBufferSize = _parent._profileCapabilities.MaxVertexBufferSize;
        if (num > (uint)maxVertexBufferSize)
        {
            _parent._profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileTooBig, typeof(VertexBuffer).Name, maxVertexBufferSize);
        }
        fixed (IDirect3DVertexBuffer9** ptr = &pComPtr)
        {
            int num2 = *(int*)_parent.pComPtr + 104;
            int num3 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, uint, _D3DPOOL, IDirect3DVertexBuffer9**, void**, int>)(int)(*(uint*)num2))((nint)_parent.pComPtr, num, _parent.GetBufferUsage(usage), 0u, pool, ptr, null);
            if (num3 < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num3);
            }
            _usage = usage;
            _size = num;
            _pool = (uint)pool;
            _vertexCount = dwVertexCount;
            _vertexDeclaration = vertexDeclaration;
            if ((usage & 8) == 8 && pool == (_D3DPOOL)1 && (pBufferData = _003CModule_003E.new_005B_005D(num)) == null)
            {
                throw new InsufficientMemoryException();
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsResource(), Microsoft.Xna.Framework.Graphics.GraphicsDevice._parent, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.VertexBuffer._pool, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.VertexBuffer._size, Microsoft.Xna.Framework.Graphics.VertexBuffer._usage, Microsoft.Xna.Framework.Graphics.VertexBuffer._vertexCount, Microsoft.Xna.Framework.Graphics.VertexBuffer._vertexDeclaration, Microsoft.Xna.Framework.Graphics.VertexDeclaration._vertexStride, Microsoft.Xna.Framework.Graphics.VertexDeclaration.Bind(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBufferUsage(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVertexBufferSize, Microsoft.Xna.Framework.Graphics.GraphicsResource.Name, Microsoft.Xna.Framework.Graphics.VertexBuffer.pBufferData, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.VertexBuffer.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileTooBig, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException().
Referenced by Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.DynamicVertexBuffer(), Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.DynamicVertexBuffer(), Microsoft.Xna.Framework.Graphics.VertexBuffer.VertexBuffer(), and Microsoft.Xna.Framework.Graphics.VertexBuffer.VertexBuffer().