Terraria: Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryDepthFormat
QueryDepthFormat()
unsafe DepthFormat Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryDepthFormat (DepthFormat depthFormat, SurfaceFormat surfaceFormat, _D3DDEVTYPE deviceType, ProfileCapabilities profileCapabilities) inline private
Definition at line 567 of file GraphicsAdapter.cs.
    {
        if (IsValidDepthFormat(depthFormat, surfaceFormat, deviceType, profileCapabilities))
        {
            return depthFormat;
        }
        int num = 0;
        if (System.Runtime.CompilerServices.Unsafe.As<_0024ArrayType_0024_0024_0024BY03W4DepthFormat_0040Graphics_0040Framework_0040Xna_0040Microsoft_0040_0040, int>(ref _003CModule_003E._003FA0x49afb68d_002E_003FfallbackFormats_0040_003F4_003F_003FQueryDepthFormat_0040GraphicsAdapter_0040Graphics_0040Framework_0040Xna_0040Microsoft_0040_0040A_0024AAM_003FAW4DepthFormat_00403456_0040W473456_0040W4SurfaceFormat_00403456_0040W4_D3DDEVTYPE_0040_0040P_0024AAVProfileCapabilities_00403456_0040_0040Z_00404PAW473456_0040A) != 0)
        {
            do
            {
                int num2 = *(int*)((ref *(_003F*)(sizeof(DepthFormat) * num)) + (ref System.Runtime.CompilerServices.Unsafe.As<_0024ArrayType_0024_0024_0024BY03W4DepthFormat_0040Graphics_0040Framework_0040Xna_0040Microsoft_0040_0040, _003F>(ref _003CModule_003E._003FA0x49afb68d_002E_003FfallbackFormats_0040_003F4_003F_003FQueryDepthFormat_0040GraphicsAdapter_0040Graphics_0040Framework_0040Xna_0040Microsoft_0040_0040A_0024AAM_003FAW4DepthFormat_00403456_0040W473456_0040W4SurfaceFormat_00403456_0040W4_D3DDEVTYPE_0040_0040P_0024AAVProfileCapabilities_00403456_0040_0040Z_00404PAW473456_0040A)));
                if (num2 != (int)depthFormat)
                {
                    DepthFormat depthFormat2 = (DepthFormat)num2;
                    if (depthFormat2 != 0)
                    {
                        if (!profileCapabilities.ValidDepthFormats.Contains(depthFormat2))
{
                            goto IL_007f;
                        }
                        if (deviceType != (_D3DDEVTYPE)4)
{
                            int num3 = *(int*)pComPtr + 48;
                            if (((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DDEVTYPE, _D3DFORMAT, _D3DFORMAT, _D3DFORMAT, int>)(int)(*(uint*)num3))((nint)pComPtr, adapter, deviceType, ProfileChecker.IRRELEVANT_ADAPTER_FORMAT, _003CModule_003E.ConvertXnaFormatToWindows(surfaceFormat), _003CModule_003E.ConvertXnaFormatToWindows(depthFormat2)) < 0)
{
                                goto IL_007f;
                            }
                        }
                    }
                    return *(DepthFormat*)((ref *(_003F*)(sizeof(DepthFormat) * num)) + (ref System.Runtime.CompilerServices.Unsafe.As<_0024ArrayType_0024_0024_0024BY03W4DepthFormat_0040Graphics_0040Framework_0040Xna_0040Microsoft_0040_0040, _003F>(ref _003CModule_003E._003FA0x49afb68d_002E_003FfallbackFormats_0040_003F4_003F_003FQueryDepthFormat_0040GraphicsAdapter_0040Graphics_0040Framework_0040Xna_0040Microsoft_0040_0040A_0024AAM_003FAW4DepthFormat_00403456_0040W473456_0040W4SurfaceFormat_00403456_0040W4_D3DDEVTYPE_0040_0040P_0024AAVProfileCapabilities_00403456_0040_0040Z_00404PAW473456_0040A)));
                }
                goto IL_007f;
                IL_007f:
                num++;
            }
            while (*(int*)((ref *(_003F*)(sizeof(DepthFormat) * num)) + (ref System.Runtime.CompilerServices.Unsafe.As<_0024ArrayType_0024_0024_0024BY03W4DepthFormat_0040Graphics_0040Framework_0040Xna_0040Microsoft_0040_0040, _003F>(ref _003CModule_003E._003FA0x49afb68d_002E_003FfallbackFormats_0040_003F4_003F_003FQueryDepthFormat_0040GraphicsAdapter_0040Graphics_0040Framework_0040Xna_0040Microsoft_0040_0040A_0024AAM_003FAW4DepthFormat_00403456_0040W473456_0040W4SurfaceFormat_00403456_0040W4_D3DDEVTYPE_0040_0040P_0024AAVProfileCapabilities_00403456_0040_0040Z_00404PAW473456_0040A))) != 0);
        }
        throw new InvalidOperationException(FrameworkResources.DriverError);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsAdapter.adapter, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), Microsoft.Xna.Framework.FrameworkResources.DriverError, Microsoft.Xna.Framework.Graphics.ProfileChecker.IRRELEVANT_ADAPTER_FORMAT, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.IsValidDepthFormat(), and Microsoft.Xna.Framework.Graphics.GraphicsAdapter.pComPtr.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryFormat().