Terraria: Terraria.GameContent.RGB.CultistShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.CultistShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 24 of file CultistShader.cs.
    {
        time *= 2f;
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Vector4 backgroundColor = _backgroundColor;
            float num = time * 0.5f + canvasPositionOfIndex.X + canvasPositionOfIndex.Y;
            float value = (float)Math.Cos(num) * 2f + 2f;
            value = MathHelper.Clamp(value, 0f, 1f);
            num = (num + (float)Math.PI) % ((float)Math.PI * 6f);
            Vector4 value2;
            if (num < (float)Math.PI * 2f)
            {
                float staticNoise = NoiseHelper.GetStaticNoise(canvasPositionOfIndex * 0.3f + new Vector2(12.5f, time * 0.2f));
                staticNoise = Math.Max(0f, 1f - staticNoise * staticNoise * 4f * staticNoise);
                staticNoise = MathHelper.Clamp(staticNoise, 0f, 1f);
                value2 = Vector4.Lerp(_fireDarkColor, _fireBrightColor, staticNoise);
            }
            else if (num < (float)Math.PI * 4f)
            {
                float dynamicNoise = NoiseHelper.GetDynamicNoise(new Vector2((canvasPositionOfIndex.X + canvasPositionOfIndex.Y) * 0.2f, 0f), time / 5f);
                dynamicNoise = Math.Max(0f, 1f - dynamicNoise * 1.5f);
                value2 = Vector4.Lerp(_iceDarkColor, _iceBrightColor, dynamicNoise);
            }
            else
            {
                float dynamicNoise2 = NoiseHelper.GetDynamicNoise(canvasPositionOfIndex * 0.15f, time * 0.05f);
                dynamicNoise2 = (float)Math.Sin(dynamicNoise2 * 15f) * 0.5f + 0.5f;
                dynamicNoise2 = Math.Max(0f, 1f - 5f * dynamicNoise2);
                value2 = Vector4.Lerp(_lightningDarkColor, _lightningBrightColor, dynamicNoise2);
            }
            backgroundColor = Vector4.Lerp(backgroundColor, value2, value);
            fragment.SetColor(i, backgroundColor);
        }
    }
References Terraria.GameContent.RGB.CultistShader._backgroundColor, Terraria.GameContent.RGB.CultistShader._fireBrightColor, Terraria.GameContent.RGB.CultistShader._fireDarkColor, Terraria.GameContent.RGB.CultistShader._iceBrightColor, Terraria.GameContent.RGB.CultistShader._iceDarkColor, Terraria.GameContent.RGB.CultistShader._lightningBrightColor, Terraria.GameContent.RGB.CultistShader._lightningDarkColor, Microsoft.Xna.Framework.MathHelper.Clamp(), System.Math.Cos(), ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), System.Math.PI, ReLogic.Peripherals.RGB.Fragment.SetColor(), System.Math.Sin(), System.value, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.