Terraria: Microsoft.Xna.Framework.Graphics.VertexBuffer.CopyData< T >
CopyData< T >()
unsafe void Microsoft.Xna.Framework.Graphics.VertexBuffer.CopyData< T > (int offsetInBytes, T[] data, int startIndex, int elementCount, int vertexStride, uint options, [MarshalAs(UnmanagedType.U1)] bool isSetting) inline package
Type Constraints
T : struct
Definition at line 139 of file VertexBuffer.cs.
                                                                                                                                                                                          : struct
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (data != null)
        {
            int num = data.Length;
            if (num != 0)
            {
                int num2 = -2147467259;
                if ((options & 0x3010) == 0)
                {
                    int num3 = 0;
                    GraphicsDevice parent = _parent;
                    int currentVertexBufferCount = parent.currentVertexBufferCount;
                    if (0 < currentVertexBufferCount)
                    {
                        VertexBufferBinding[] currentVertexBuffers = parent.currentVertexBuffers;
                        do
{
                            if (currentVertexBuffers[num3]._vertexBuffer != this)
{
                                num3++;
                                continue;
                            }
                            throw GraphicsHelpers.GetExceptionFromResult(2147500036u);
                        }
                        while (num3 < currentVertexBufferCount);
                    }
                }
                if (!isSetting && (_usage & 8) == 8)
                {
                    throw new NotSupportedException(FrameworkResources.WriteOnlyGetNotSupported);
                }
                Helpers.ValidateCopyParameters(num, startIndex, elementCount);
                try
                {
                    uint num4 = (uint)System.Runtime.CompilerServices.Unsafe.SizeOf<T>();
                    uint num5 = num4 * (uint)elementCount;
                    int num6;
                    if (vertexStride != 0)
                    {
                        num6 = vertexStride - (int)num4;
                        if (num6 < 0)
{
                            throw new ArgumentOutOfRangeException("vertexStride", FrameworkResources.VertexStrideTooSmall);
                        }
                        if (elementCount > 1)
{
                            num5 = (uint)((elementCount - 1) * num6) + num5;
                        }
                    }
                    else
                    {
                        num6 = 0;
                    }
                    if ((uint)((int)num5 + offsetInBytes) > _size)
                    {
                        throw new InvalidOperationException(FrameworkResources.ResourceDataMustBeCorrectSize);
                    }
                    if (_parent.IsDeviceLost)
                    {
                        if (isSetting)
{
                            return;
                        }
                        fixed (T* ptr = &data[startIndex])
{
                            try
{
                                // IL initblk instruction
                                System.Runtime.CompilerServices.Unsafe.InitBlock(ptr, 0, num5);
                            }
                            catch
{
                                //try-fault
                                ptr = null;
                                throw;
                            }
                        }
                        return;
                    }
                    void* ptr2 = null;
                    byte* ptr3 = (byte*)pBufferData;
                    if (IsWriteOnly && _pool == 1)
                    {
                        ptr3 = offsetInBytes + ptr3;
                    }
                    IDirect3DVertexBuffer9* ptr4 = pComPtr;
                    num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, void**, uint, int>)(int)(*(uint*)(*(int*)ptr4 + 44)))((nint)ptr4, (uint)offsetInBytes, num5, &ptr2, options);
                    if (num2 >= 0)
                    {
                        if (num6 == 0)
{
                            fixed (T* ptr5 = &data[startIndex])
{
                                try
{
                                    if (isSetting)
{
                                        _003CModule_003E.memcpy_s(ptr2, _size - (uint)offsetInBytes, ptr5, num5);
                                        if (IsWriteOnly && _pool == 1)
{
                                            _003CModule_003E.memcpy_s(ptr3, _size - (uint)offsetInBytes, ptr5, num5);
                                        }
                                    }
                                    else
{
                                        _003CModule_003E.memcpy_s(ptr5, num5, ptr2, num5);
                                    }
                                }
                                catch
{
                                    //try-fault
                                    ptr5 = null;
                                    throw;
                                }
                            }
                        }
                        else
{
                            byte* ptr6 = (byte*)ptr2;
                            byte* ptr7 = ptr3;
                            for (int i = 0; i < elementCount; i++)
{
                                fixed (T* ptr8 = &data[i + startIndex])
{
                                    try
{
                                        if (isSetting)
{
                                            _003CModule_003E.memcpy_s(ptr6, _size - (uint)offsetInBytes, ptr8, (uint)System.Runtime.CompilerServices.Unsafe.SizeOf<T>());
                                            if (IsWriteOnly && _pool == 1)
{
                                                _003CModule_003E.memcpy_s(ptr7, _size - (uint)offsetInBytes, ptr8, (uint)System.Runtime.CompilerServices.Unsafe.SizeOf<T>());
                                            }
                                        }
                                        else
{
                                            _003CModule_003E.memcpy_s(ptr8, num5, ptr6, (uint)System.Runtime.CompilerServices.Unsafe.SizeOf<T>());
                                        }
                                        ptr6 = vertexStride + ptr6;
                                        if (IsWriteOnly && _pool == 1)
{
                                            ptr7 = vertexStride + ptr7;
                                        }
                                    }
                                    catch
{
                                        //try-fault
                                        ptr8 = null;
                                        throw;
                                    }
                                }
                            }
                        }
                    }
                }
                finally
                {
                    if (num2 >= 0)
                    {
                        IDirect3DVertexBuffer9* intPtr2 = pComPtr;
                        num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, int>)(int)(*(uint*)(*(int*)intPtr2 + 48)))((nint)intPtr2);
                    }
                }
                if (num2 < 0)
                {
                    throw GraphicsHelpers.GetExceptionFromResult((uint)num2);
                }
                if (isSetting && this is IDynamicGraphicsResource dynamicGraphicsResource)
                {
                    dynamicGraphicsResource.SetContentLost(isContentLost: false);
                }
                return;
            }
        }
        throw new ArgumentNullException("data", FrameworkResources.NullNotAllowed);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.VertexBuffer._pool, Microsoft.Xna.Framework.Graphics.VertexBuffer._size, Microsoft.Xna.Framework.Graphics.VertexBuffer._usage, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBufferCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.currentVertexBuffers, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), System.Runtime.CompilerServices.Unsafe.InitBlock(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.IsDeviceLost, Microsoft.Xna.Framework.Graphics.VertexBuffer.IsWriteOnly, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, System.options, Microsoft.Xna.Framework.Graphics.VertexBuffer.pBufferData, Microsoft.Xna.Framework.Graphics.VertexBuffer.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ResourceDataMustBeCorrectSize, System.startIndex, Microsoft.Xna.Framework.Helpers.ValidateCopyParameters(), Microsoft.Xna.Framework.FrameworkResources.VertexStrideTooSmall, and Microsoft.Xna.Framework.FrameworkResources.WriteOnlyGetNotSupported.