Terraria: Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose
Dispose() [2/2]
override void Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose ([MarshalAs(UnmanagedType.U1)] bool P_0) inline protected virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.GraphicsResource.
Definition at line 516 of file VertexBuffer.cs.
    {
        if (P_0)
        {
            try
            {
                _007EVertexBuffer();
                return;
            }
            finally
            {
                base.Dispose(true);
            }
        }
        try
        {
            _0021VertexBuffer();
        }
        finally
        {
            base.Dispose(false);
        }
    }
References Microsoft.Xna.Framework.Graphics.VertexBuffer._0021VertexBuffer(), and Microsoft.Xna.Framework.Graphics.VertexBuffer._007EVertexBuffer().
Referenced by Terraria.DataStructures.SpriteDrawBuffer.CreateBuffers(), Terraria.Graphics.TileBatch.Dispose(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.DisposePlatformData().