Terraria: Microsoft.Xna.Framework.Graphics.GraphicsAdapter.InitializeAdapterList
InitializeAdapterList()
static unsafe void Microsoft.Xna.Framework.Graphics.GraphicsAdapter.InitializeAdapterList () inline static private
Definition at line 271 of file GraphicsAdapter.cs.
    {
        List<GraphicsAdapter> list = new List<GraphicsAdapter>();
        int num = *(int*)pComPtr + 16;
        uint num2 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)num))((nint)pComPtr);
        uint num3 = 0u;
        if (0 < num2)
        {
            do
            {
                list.Add(new GraphicsAdapter(num3));
                num3++;
            }
            while (num3 < num2);
        }
        pAdapterList = new ReadOnlyCollection<GraphicsAdapter>(list);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsAdapter.GraphicsAdapter(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.list, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.pAdapterList, and Microsoft.Xna.Framework.Graphics.GraphicsAdapter.pComPtr.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsAdapter.GraphicsAdapter().