Terraria: Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryFormat
QueryFormat()
bool Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryFormat ([MarshalAs(UnmanagedType.U1)] bool isBackBuffer, _D3DDEVTYPE deviceType, GraphicsProfile graphicsProfile, SurfaceFormat format, DepthFormat depthFormat, int multiSampleCount, out SurfaceFormat selectedFormat, out DepthFormat selectedDepthFormat, out int selectedMultiSampleCount) inline package
Definition at line 321 of file GraphicsAdapter.cs.
    {
        ProfileCapabilities instance = ProfileCapabilities.GetInstance(graphicsProfile);
        selectedDepthFormat = QueryDepthFormat(depthFormat, selectedFormat = QuerySurfaceFormat(format, isBackBuffer, deviceType, instance), deviceType, instance);
        int num = (selectedMultiSampleCount = QueryMultiSampleCount(multiSampleCount, selectedFormat, deviceType));
        int num2 = ((selectedFormat == format && selectedDepthFormat == depthFormat && num == multiSampleCount) ? 1 : 0);
        return (byte)num2 != 0;
    }
References System.format, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.GetInstance(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryDepthFormat(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryMultiSampleCount(), and Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QuerySurfaceFormat().
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.ConvertPresentationParametersToNative(), Microsoft.Xna.Framework.Graphics.RenderTargetCube.CreateRenderTarget(), Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget(), Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryBackBufferFormat(), and Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryRenderTargetFormat().