Terraria: Microsoft.Xna.Framework.Graphics.VertexBuffer._0021VertexBuffer
_0021VertexBuffer()
unsafe void Microsoft.Xna.Framework.Graphics.VertexBuffer._0021VertexBuffer () inline private
Definition at line 496 of file VertexBuffer.cs.
    {
        if (!isDisposed)
        {
            ReleaseNativeObject(disposeManagedResource: true);
            void* ptr = pBufferData;
            if (ptr != null)
            {
                _003CModule_003E.delete_005B_005D(ptr);
                pBufferData = null;
            }
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.VertexBuffer.pBufferData, and Microsoft.Xna.Framework.Graphics.VertexBuffer.ReleaseNativeObject().
Referenced by Microsoft.Xna.Framework.Graphics.VertexBuffer._007EVertexBuffer(), and Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose().