Terraria: System.Drawing.RectangleF.RectangleF
RectangleF() [1/3]
System.Drawing.RectangleF.RectangleF (float x, float y, float width, float height) inline
Definition at line 123 of file RectangleF.cs.
    {
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
    }
References System.Drawing.RectangleF.height, System.Drawing.RectangleF.width, System.Drawing.RectangleF.x, and System.Drawing.RectangleF.y.
Referenced by System.Drawing.RectangleF.FromLTRB(), System.Drawing.RectangleF.Intersect(), System.Drawing.RectangleF.operator RectangleF(), System.Drawing.RectangleF.operator RectangleF(), and System.Drawing.RectangleF.Union().