Terraria: System.Drawing.RectangleF.Intersect
Intersect() [1/2]
static RectangleF System.Drawing.RectangleF.Intersect (RectangleF a, RectangleF b) inline static
Definition at line 252 of file RectangleF.cs.
    {
        float num = Math.Max(a.X, b.X);
        float num2 = Math.Min(a.X + a.Width, b.X + b.Width);
        float num3 = Math.Max(a.Y, b.Y);
        float num4 = Math.Min(a.Y + a.Height, b.Y + b.Height);
        if (num2 >= num && num4 >= num3)
        {
            return new RectangleF(num, num3, num2 - num, num4 - num3);
        }
        return Empty;
    }
References System.Drawing.RectangleF.RectangleF(), System.Drawing.RectangleF.Empty, System.Drawing.RectangleF.Height, System.Math.Max(), System.Math.Min(), System.Drawing.RectangleF.Width, System.Drawing.RectangleF.X, and System.Drawing.RectangleF.Y.