Terraria: DunesBiome.Place
Place()
override bool DunesBiome.Place (Point origin, StructureMap structures) inline virtual
Implements GenStructure.
     {
         int height = (int)((double)GenBase._random.Next(60, 100) * _heightScale);
         int height2 = (int)((double)GenBase._random.Next(60, 100) * _heightScale);
         int random = _singleDunesWidth.GetRandom(GenBase._random);
         int random2 = _singleDunesWidth.GetRandom(GenBase._random);
         DunesDescription description = DunesDescription.CreateFromPlacement(new Point(origin.X - random / 2 + 30, origin.Y), random, height);
         DunesDescription description2 = DunesDescription.CreateFromPlacement(new Point(origin.X + random2 / 2 - 30, origin.Y), random2, height2);
         PlaceSingle(description, structures);
         PlaceSingle(description2, structures);
         return true;
     }
References _heightScale, GenBase._random, _singleDunesWidth, DunesBiome.DunesDescription.CreateFromPlacement(), WorldGenRange.GetRandom(), UnifiedRandom.Next(), and PlaceSingle().