Terraria: System.Security.Cryptography.RSA.VerifyData
VerifyData() [2/4]
virtual bool System.Security.Cryptography.RSA.VerifyData (byte[] data, int offset, int count, byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) inline virtual inherited
Definition at line 253 of file RSA.cs.
    {
        if (data == null)
        {
            throw new ArgumentNullException("data");
        }
        if (offset < 0 || offset > data.Length)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (count < 0 || count > data.Length - offset)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (signature == null)
        {
            throw new ArgumentNullException("signature");
        }
        if (string.IsNullOrEmpty(hashAlgorithm.Name))
        {
            throw HashAlgorithmNameNullOrEmpty();
        }
        if (padding == null)
        {
            throw new ArgumentNullException("padding");
        }
        byte[] hash = HashData(data, offset, count, hashAlgorithm);
        return VerifyHash(hash, signature, hashAlgorithm, padding);
    }
References System.count, System.Security.Cryptography.RSA.HashAlgorithmNameNullOrEmpty(), System.Security.Cryptography.RSA.HashData(), System.Security.Cryptography.HashAlgorithmName.Name, System.offset, and System.Security.Cryptography.RSA.VerifyHash().