Terraria: System.Security.Cryptography.RSA.WritePkcs8PrivateKey
WritePkcs8PrivateKey()
unsafe AsnWriter System.Security.Cryptography.RSA.WritePkcs8PrivateKey () inline private inherited
Definition at line 393 of file RSA.cs.
    {
        int num = checked(5 * KeySize) / 8;
        while (true)
        {
            byte[] array = System.Security.Cryptography.CryptoPool.Rent(num);
            num = array.Length;
            int bytesWritten = 0;
            fixed (byte* ptr = array)
            {
                try
                {
                    if (!TryExportRSAPrivateKey(array, out bytesWritten))
                    {
                        num = checked(num * 2);
                        continue;
                    }
                    return RSAKeyFormatHelper.WritePkcs8PrivateKey(new ReadOnlySpan<byte>(array, 0, bytesWritten));
                }
                finally
                {
                    System.Security.Cryptography.CryptoPool.Return(array, bytesWritten);
                }
            }
        }
    }
References System.array, System.Security.Cryptography.AsymmetricAlgorithm.KeySize, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Security.Cryptography.RSA.TryExportRSAPrivateKey(), and System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs8PrivateKey().
Referenced by System.Security.Cryptography.RSA.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.RSA.TryExportEncryptedPkcs8PrivateKey(), and System.Security.Cryptography.RSA.TryExportPkcs8PrivateKey().