Terraria: System.Security.Cryptography.RSA.TryHashData
TryHashData()
virtual bool System.Security.Cryptography.RSA.TryHashData (ReadOnlySpan< byte > data, Span< byte > destination, HashAlgorithmName hashAlgorithm, out int bytesWritten) inline protected virtual inherited
Reimplemented in System.Security.Cryptography.RSAImplementation.RSACng, and System.Security.Cryptography.RSACng.
Definition at line 116 of file RSA.cs.
    {
        byte[] array = ArrayPool<byte>.Shared.Rent(data.Length);
        byte[] array2;
        try
        {
            data.CopyTo(array);
            array2 = HashData(array, 0, data.Length, hashAlgorithm);
        }
        finally
        {
            Array.Clear(array, 0, data.Length);
            ArrayPool<byte>.Shared.Return(array);
        }
        if (destination.Length >= array2.Length)
        {
            new ReadOnlySpan<byte>(array2).CopyTo(destination);
            bytesWritten = array2.Length;
            return true;
        }
        bytesWritten = 0;
        return false;
    }
References System.array, System.Array.Clear(), System.ReadOnlySpan< T >.CopyTo(), System.destination, System.Security.Cryptography.RSA.HashData(), System.ReadOnlySpan< T >.Length, and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.Security.Cryptography.RSA.TrySignData(), and System.Security.Cryptography.RSA.VerifyData().