Terraria: System.Security.Cryptography.RSA.SignHash
SignHash()
virtual byte[] System.Security.Cryptography.RSA.SignHash (byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) inline virtual
Reimplemented in System.Security.Cryptography.RSAImplementation.RSACng, System.Security.Cryptography.RSACng, System.Security.Cryptography.RSACryptoServiceProvider, and System.Security.Cryptography.RSAOpenSsl.
Definition at line 70 of file RSA.cs.
    {
        throw DerivedClassMustOverride();
    }
References System.Security.Cryptography.RSA.DerivedClassMustOverride().
Referenced by System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature(), System.Security.Cryptography.RSA.SignData(), System.Security.Cryptography.RSA.SignData(), and System.Security.Cryptography.RSA.TrySignHash().