Terraria: System.Security.Cryptography.RSA.WritePkcs1PrivateKey
WritePkcs1PrivateKey()
unsafe AsnWriter System.Security.Cryptography.RSA.WritePkcs1PrivateKey () inline private inherited
Definition at line 450 of file RSA.cs.
    {
        RSAParameters rsaParameters = ExportParameters(includePrivateParameters: true);
        fixed (byte* ptr6 = rsaParameters.D)
        {
            fixed (byte* ptr5 = rsaParameters.P)
            {
                fixed (byte* ptr4 = rsaParameters.Q)
                {
                    fixed (byte* ptr3 = rsaParameters.DP)
                    {
                        fixed (byte* ptr2 = rsaParameters.DQ)
{
                            fixed (byte* ptr = rsaParameters.InverseQ)
{
                                try
{
                                    return RSAKeyFormatHelper.WritePkcs1PrivateKey(in rsaParameters);
                                }
                                finally
{
                                    ClearPrivateParameters(in rsaParameters);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
References System.Security.Cryptography.RSA.ClearPrivateParameters(), System.Security.Cryptography.RSAParameters.D, System.Security.Cryptography.RSAParameters.DP, System.Security.Cryptography.RSAParameters.DQ, System.Security.Cryptography.RSA.ExportParameters(), System.Security.Cryptography.RSAParameters.InverseQ, System.Security.Cryptography.RSAParameters.P, System.Security.Cryptography.RSAParameters.Q, and System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs1PrivateKey().
Referenced by System.Security.Cryptography.RSA.ExportRSAPrivateKey(), and System.Security.Cryptography.RSA.TryExportRSAPrivateKey().