Terraria: System.Security.Cryptography.RSA.ImportRSAPrivateKey
ImportRSAPrivateKey()
virtual unsafe void System.Security.Cryptography.RSA.ImportRSAPrivateKey (ReadOnlySpan< byte > source, out int bytesRead) inline virtual inherited
Definition at line 511 of file RSA.cs.
    {
        try
        {
            AsnDecoder.ReadEncodedValue(source, AsnEncodingRules.BER, out var _, out var _, out var bytesConsumed);
            fixed (byte* pointer = &MemoryMarshal.GetReference(source))
            {
                using MemoryManager<byte> memoryManager = new PointerMemoryManager<byte>(pointer, bytesConsumed);
                ReadOnlyMemory<byte> keyData = memoryManager.Memory;
                int length = keyData.Length;
                AlgorithmIdentifierAsn algId = default(AlgorithmIdentifierAsn);
                RSAKeyFormatHelper.FromPkcs1PrivateKey(keyData, in algId, out var ret);
                fixed (byte* ptr6 = ret.D)
                {
                    fixed (byte* ptr5 = ret.P)
                    {
                        fixed (byte* ptr4 = ret.Q)
{
                            fixed (byte* ptr3 = ret.DP)
{
                                fixed (byte* ptr2 = ret.DQ)
{
                                    fixed (byte* ptr = ret.InverseQ)
{
                                        try
{
                                            ImportParameters(ret);
                                        }
                                        finally
{
                                            ClearPrivateParameters(in ret);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                bytesRead = length;
            }
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
    }
References System.Security.Cryptography.RSA.ClearPrivateParameters(), System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.RSAKeyFormatHelper.FromPkcs1PrivateKey(), System.Security.Cryptography.RSA.ImportParameters(), System.length, System.ReadOnlyMemory< T >.Length, System.pointer, System.Formats.Asn1.AsnDecoder.ReadEncodedValue(), and System.source.
Referenced by System.Security.Cryptography.RSA.ImportPkcs8PrivateKey().