Terraria: System.Security.Cryptography.RSA.ClearPrivateParameters
ClearPrivateParameters()
static void System.Security.Cryptography.RSA.ClearPrivateParameters (in RSAParameters rsaParameters) inline static private inherited
Definition at line 662 of file RSA.cs.
    {
        CryptographicOperations.ZeroMemory(rsaParameters.D);
        CryptographicOperations.ZeroMemory(rsaParameters.P);
        CryptographicOperations.ZeroMemory(rsaParameters.Q);
        CryptographicOperations.ZeroMemory(rsaParameters.DP);
        CryptographicOperations.ZeroMemory(rsaParameters.DQ);
        CryptographicOperations.ZeroMemory(rsaParameters.InverseQ);
    }
References System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.RSA.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.RSA.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.RSA.ImportRSAPrivateKey(), and System.Security.Cryptography.RSA.WritePkcs1PrivateKey().