Terraria: System.Security.Cryptography.RSA.TryExportEncryptedPkcs8PrivateKey
TryExportEncryptedPkcs8PrivateKey() [1/2]
override bool System.Security.Cryptography.RSA.TryExportEncryptedPkcs8PrivateKey (ReadOnlySpan< byte > passwordBytes, PbeParameters pbeParameters, Span< byte > destination, out int bytesWritten) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Reimplemented in System.Security.Cryptography.RSAImplementation.RSACng, and System.Security.Cryptography.RSACng.
Definition at line 432 of file RSA.cs.
    {
        if (pbeParameters == null)
        {
            throw new ArgumentNullException("pbeParameters");
        }
        PasswordBasedEncryption.ValidatePbeParameters(pbeParameters, ReadOnlySpan<char>.Empty, passwordBytes);
        AsnWriter pkcs8Writer = WritePkcs8PrivateKey();
        AsnWriter asnWriter = KeyFormatHelper.WriteEncryptedPkcs8(passwordBytes, pkcs8Writer, pbeParameters);
        return asnWriter.TryEncode(destination, out bytesWritten);
    }
References System.destination, System.Formats.Asn1.AsnWriter.TryEncode(), System.Security.Cryptography.PasswordBasedEncryption.ValidatePbeParameters(), System.Security.Cryptography.KeyFormatHelper.WriteEncryptedPkcs8(), and System.Security.Cryptography.RSA.WritePkcs8PrivateKey().