Terraria: System.Security.Cryptography.RSA.Create
Create() [3/4]
static RSA System.Security.Cryptography.RSA.Create (RSAParameters parameters) inline static inherited
Definition at line 41 of file RSA.cs.
    {
        RSA rSA = Create();
        try
        {
            rSA.ImportParameters(parameters);
            return rSA;
        }
        catch
        {
            rSA.Dispose();
            throw;
        }
    }
References System.Security.Cryptography.RSA.Create(), System.Security.Cryptography.AsymmetricAlgorithm.Dispose(), and System.Security.Cryptography.RSA.ImportParameters().