Terraria: System.Security.Cryptography.RSA.Encrypt
Encrypt()
virtual byte[] System.Security.Cryptography.RSA.Encrypt (byte[] data, RSAEncryptionPadding padding) inline virtual
Reimplemented in System.Security.Cryptography.RSAImplementation.RSACng, System.Security.Cryptography.RSACng, System.Security.Cryptography.RSACryptoServiceProvider, and System.Security.Cryptography.RSAOpenSsl.
Definition at line 60 of file RSA.cs.
    {
        throw DerivedClassMustOverride();
    }
References System.Security.Cryptography.RSA.DerivedClassMustOverride().
Referenced by System.Security.Cryptography.RSAOAEPKeyExchangeFormatter.CreateKeyExchange(), System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter.CreateKeyExchange(), and System.Security.Cryptography.RSA.TryEncrypt().