Terraria: System.Security.Cryptography.RSA.ImportFromPem
ImportFromPem()
override void System.Security.Cryptography.RSA.ImportFromPem (ReadOnlySpan< char > input) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 632 of file RSA.cs.
    {
        PemKeyImportHelpers.ImportPem(input, delegate(ReadOnlySpan<char> label)
        {
            if (label.SequenceEqual("RSA PRIVATE KEY"))
            {
                return ImportRSAPrivateKey;
            }
            if (label.SequenceEqual("PRIVATE KEY"))
            {
                return ImportPkcs8PrivateKey;
            }
            if (label.SequenceEqual("RSA PUBLIC KEY"))
            {
                return ImportRSAPublicKey;
            }
            return label.SequenceEqual("PUBLIC KEY") ? new PemKeyImportHelpers.ImportKeyAction(ImportSubjectPublicKeyInfo) : null;
        });
    }
References Internal.Cryptography.PemKeyImportHelpers.ImportKeyAction(), Internal.Cryptography.PemKeyImportHelpers.ImportPem(), System.Security.Cryptography.RSA.ImportSubjectPublicKeyInfo(), and System.input.