Terraria: System.Security.Cryptography.RSA.VerifyHash
VerifyHash() [1/2]
virtual bool System.Security.Cryptography.RSA.VerifyHash (byte[] hash, byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) inline virtual
Reimplemented in System.Security.Cryptography.RSAImplementation.RSACng, System.Security.Cryptography.RSACng, System.Security.Cryptography.RSACryptoServiceProvider, and System.Security.Cryptography.RSAOpenSsl.
Definition at line 75 of file RSA.cs.
    {
        throw DerivedClassMustOverride();
    }
References System.Security.Cryptography.RSA.DerivedClassMustOverride().
Referenced by System.Security.Cryptography.RSA.VerifyData(), System.Security.Cryptography.RSA.VerifyData(), System.Security.Cryptography.RSA.VerifyData(), System.Security.Cryptography.RSA.VerifyHash(), and System.Security.Cryptography.RSAPKCS1SignatureDeformatter.VerifySignature().