Terraria: System.Security.Cryptography.RSA.TryExportSubjectPublicKeyInfo
TryExportSubjectPublicKeyInfo()
unsafe override bool System.Security.Cryptography.RSA.TryExportSubjectPublicKeyInfo (Span< byte > destination, out int bytesWritten) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 359 of file RSA.cs.
    {
        int num = KeySize / 4;
        while (true)
        {
            byte[] array = System.Security.Cryptography.CryptoPool.Rent(num);
            num = array.Length;
            int bytesWritten2 = 0;
            fixed (byte* ptr = array)
            {
                try
                {
                    if (!TryExportRSAPublicKey(array, out bytesWritten2))
                    {
                        num = checked(num * 2);
                        continue;
                    }
                    AsnWriter asnWriter = RSAKeyFormatHelper.WriteSubjectPublicKeyInfo(array.AsSpan(0, bytesWritten2));
                    return asnWriter.TryEncode(destination, out bytesWritten);
                }
                finally
                {
                    System.Security.Cryptography.CryptoPool.Return(array, bytesWritten2);
                }
            }
        }
    }
References System.array, System.destination, System.Security.Cryptography.AsymmetricAlgorithm.KeySize, System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), System.Formats.Asn1.AsnWriter.TryEncode(), System.Security.Cryptography.RSA.TryExportRSAPublicKey(), and System.Security.Cryptography.RSAKeyFormatHelper.WriteSubjectPublicKeyInfo().