Terraria: System.Security.Cryptography.RSA.ImportSubjectPublicKeyInfo
ImportSubjectPublicKeyInfo()
unsafe override void System.Security.Cryptography.RSA.ImportSubjectPublicKeyInfo (ReadOnlySpan< byte > source, out int bytesRead) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 481 of file RSA.cs.
    {
        fixed (byte* pointer = &MemoryMarshal.GetReference(source))
        {
            using MemoryManager<byte> memoryManager = new PointerMemoryManager<byte>(pointer, source.Length);
            ImportRSAPublicKey(RSAKeyFormatHelper.ReadSubjectPublicKeyInfo(memoryManager.Memory, out var bytesRead2).Span, out var _);
            bytesRead = bytesRead2;
        }
    }
References System.Security.Cryptography.RSA.ImportRSAPublicKey(), System.pointer, System.Security.Cryptography.RSAKeyFormatHelper.ReadSubjectPublicKeyInfo(), and System.source.
Referenced by System.Security.Cryptography.X509Certificates.PublicKey.GetRSAPublicKey(), and System.Security.Cryptography.RSA.ImportFromPem().