Terraria: System.CSharpHelpers.IsValidTypeNameOrIdentifier
IsValidTypeNameOrIdentifier()
static bool System.CSharpHelpers.IsValidTypeNameOrIdentifier (string value, bool isTypeName) inline static package
Definition at line 53 of file CSharpHelpers.cs.
    {
        bool nextMustBeStartChar = true;
        if (string.IsNullOrEmpty(value))
        {
            return false;
        }
        foreach (char c in value)
        {
            switch (CharUnicodeInfo.GetUnicodeCategory(c))
            {
            case UnicodeCategory.UppercaseLetter:
            case UnicodeCategory.LowercaseLetter:
            case UnicodeCategory.TitlecaseLetter:
            case UnicodeCategory.ModifierLetter:
            case UnicodeCategory.OtherLetter:
            case UnicodeCategory.LetterNumber:
                nextMustBeStartChar = false;
                break;
            case UnicodeCategory.NonSpacingMark:
            case UnicodeCategory.SpacingCombiningMark:
            case UnicodeCategory.DecimalDigitNumber:
            case UnicodeCategory.ConnectorPunctuation:
                if (nextMustBeStartChar && c != '_')
                {
                    return false;
                }
                nextMustBeStartChar = false;
                break;
            default:
                if (!isTypeName || !IsSpecialTypeChar(c, ref nextMustBeStartChar))
                {
                    return false;
                }
                break;
            }
        }
        return true;
    }
References System.Globalization.CharUnicodeInfo.GetUnicodeCategory(), System.CSharpHelpers.IsSpecialTypeChar(), and System.value.
Referenced by System.CSharpHelpers.IsValidLanguageIndependentIdentifier().