Terraria: Terraria.GameContent.Items.ItemVariants.GetEntry
GetEntry()
static VariantEntry Terraria.GameContent.Items.ItemVariants.GetEntry (int itemId, ItemVariant variant) inline static private
Definition at line 62 of file ItemVariants.cs.
    {
        return GetVariants(itemId).SingleOrDefault((VariantEntry v) => v.Variant == variant);
    }
References Terraria.GameContent.Items.ItemVariants.GetVariants(), and Terraria.GameContent.Items.ItemVariants.VariantEntry.Variant.
Referenced by Terraria.GameContent.Items.ItemVariants.AddVariant(), and Terraria.GameContent.Items.ItemVariants.HasVariant().