Terraria: Terraria.GameContent.Items.ItemVariants.SelectVariant
SelectVariant()
static ItemVariant Terraria.GameContent.Items.ItemVariants.SelectVariant (int itemId) inline static
    {
        if (!_variants.IndexInRange(itemId))
        {
            return null;
        }
        List<VariantEntry> list = _variants[itemId];
        if (list == null)
        {
            return null;
        }
        foreach (VariantEntry item in list)
        {
            if (item.AnyConditionMet())
            {
                return item.Variant;
            }
        }
        return null;
    }
References Terraria.GameContent.Items.ItemVariants._variants, Terraria.GameContent.Items.ItemVariants.VariantEntry.AnyConditionMet(), and Terraria.GameContent.Items.ItemVariants.VariantEntry.Variant.
Referenced by Terraria.Item.Refresh(), and Terraria.Item.SetDefaults().