Terraria: System.Xml.XmlCharType.IsNameSingleChar
IsNameSingleChar()
static bool System.Xml.XmlCharType.IsNameSingleChar (char ch) inline static
Definition at line 6585 of file XmlCharType.cs.
    {
        if (!IsNCNameSingleChar(ch))
        {
            return ch == ':';
        }
        return true;
    }
References System.ch, and System.Xml.XmlCharType.IsNCNameSingleChar().
Referenced by System.Xml.ValidateNames.ParseNmtokenNoNamespaces(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.DtdParser.ScanCondSection1(), and System.Xml.DtdParser.ScanCondSection1Async().