Terraria: System.Xml.XmlCharType.IsDigit
IsDigit()
static bool System.Xml.XmlCharType.IsDigit (char ch) inline static
Definition at line 6654 of file XmlCharType.cs.
    {
        return InRange(ch, 48, 57);
    }
References System.ch, and System.Xml.XmlCharType.InRange().
Referenced by System.Xml.XmlCharType.IsOnlyDigits(), MS.Internal.Xml.XPath.XPathScanner.NextLex(), MS.Internal.Xml.XPath.XPathScanner.ScanFraction(), and MS.Internal.Xml.XPath.XPathScanner.ScanNumber().