Terraria: System.Xml.XmlCharType.IsOnlyWhitespaceWithPos
IsOnlyWhitespaceWithPos()
static int System.Xml.XmlCharType.IsOnlyWhitespaceWithPos (string str) inline static package
Definition at line 6691 of file XmlCharType.cs.
    {
        if (str != null)
        {
            for (int i = 0; i < str.Length; i++)
            {
                if ((GetCharProperties(str[i]) & 1) == 0)
                {
                    return i;
                }
            }
        }
        return -1;
    }
References System.Xml.XmlCharType.GetCharProperties(), and System.str.
Referenced by System.Xml.XmlCharCheckingReader.CheckWhitespace(), System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.XmlConvert.VerifyWhitespace(), System.Xml.XmlCharCheckingWriter.WriteWhitespace(), and System.Xml.XmlCharCheckingWriter.WriteWhitespaceAsync().