Terraria: System.Xml.XmlCharType.IsCharData
IsCharData()
static bool System.Xml.XmlCharType.IsCharData (char ch) inline static
Definition at line 6595 of file XmlCharType.cs.
    {
        return (GetCharProperties(ch) & 0x10) != 0;
    }
References System.ch, System.Xml.Dictionary, and System.Xml.XmlCharType.GetCharProperties().
Referenced by System.Xml.XmlSqlBinaryReader.CheckText(), System.Xml.XmlConvert.IsXmlChar(), System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace(), System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespaceAsync(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntity(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntity(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntityAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntityAsync(), and System.Xml.XmlTextEncoder.WriteRawWithSurrogateChecking().