Terraria: System.Xml.XmlCharType.IsSurrogate
IsSurrogate()
static bool System.Xml.XmlCharType.IsSurrogate (int ch) inline static package
Definition at line 6669 of file XmlCharType.cs.
    {
        return InRange(ch, 55296, 57343);
    }
References System.ch, and System.Xml.XmlCharType.InRange().
Referenced by System.Xml.XmlUtf8RawTextWriter.CharToUTF8(), System.Xml.XmlUtf8RawTextWriter.EncodeChar(), System.Xml.XmlEncodedRawTextWriter.EncodeChar(), System.Xml.Ucs4Decoder1234.GetFullChars(), System.Xml.Ucs4Decoder2143.GetFullChars(), System.Xml.Ucs4Decoder3412.GetFullChars(), System.Xml.Ucs4Decoder4321.GetFullChars(), System.Xml.XmlEncodedRawTextWriter.RawText(), System.Xml.XmlUtf8RawTextWriter.RawText(), System.Xml.XmlEncodedRawTextWriter.RawTextNoFlush(), System.Xml.XmlUtf8RawTextWriter.RawTextNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSection(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSection(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlTextEncoder.WriteCharEntity(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPi(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPi(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharChecking(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingNoFlush(), and System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush().