Terraria: System.Xml.XmlCharType.IsNCNameSingleChar
IsNCNameSingleChar()
static bool System.Xml.XmlCharType.IsNCNameSingleChar (char ch) inline static
Definition at line 6573 of file XmlCharType.cs.
    {
        return (GetCharProperties(ch) & 8) != 0;
    }
References System.ch, and System.Xml.XmlCharType.GetCharProperties().
Referenced by System.Xml.XmlWellFormedWriter.CheckNCName(), System.Xml.ValidateNames.GetInvalidNameException(), System.Xml.XmlCharType.IsNameSingleChar(), System.Xml.XmlConvert.IsNCNameChar(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync(), System.Xml.XmlTextReaderImpl.ParseEndElement(), System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckEndTag(), System.Xml.ValidateNames.ParseNameNoNamespaces(), System.Xml.ValidateNames.ParseNCName(), System.Xml.ValidateNames.ParseNmtoken(), System.Xml.XmlTextReaderImpl.ParseQName(), System.Xml.XmlTextReaderImpl.ParseQNameAsync(), System.Xml.XmlTextReaderImpl.ParseUnexpectedToken(), System.Xml.DtdParser.ParseUnexpectedToken(), MS.Internal.Xml.XPath.XPathScanner.ScanName(), System.Xml.Xsl.XPath.XPathScanner.ScanNCName(), System.Xml.DtdParser.ScanNmtoken(), System.Xml.DtdParser.ScanNmtokenAsync(), System.Xml.DtdParser.ScanQName(), System.Xml.DtdParser.ScanQNameAsync(), and System.Xml.ValidateNames.ThrowInvalidName().