Terraria: System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi
MsQuicApi() [1/2]
unsafe System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi (MsQuicNativeMethods::NativeApi * vtable) inline private
Definition at line 70 of file MsQuicApi.cs.
    {
        SetParamDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.SetParamDelegate>(vtable->SetParam);
        GetParamDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.GetParamDelegate>(vtable->GetParam);
        SetCallbackHandlerDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.SetCallbackHandlerDelegate>(vtable->SetCallbackHandler);
        RegistrationOpenDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.RegistrationOpenDelegate>(vtable->RegistrationOpen);
        RegistrationCloseDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.RegistrationCloseDelegate>(vtable->RegistrationClose);
        ConfigurationOpenDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ConfigurationOpenDelegate>(vtable->ConfigurationOpen);
        ConfigurationCloseDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ConfigurationCloseDelegate>(vtable->ConfigurationClose);
        ConfigurationLoadCredentialDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ConfigurationLoadCredentialDelegate>(vtable->ConfigurationLoadCredential);
        ListenerOpenDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ListenerOpenDelegate>(vtable->ListenerOpen);
        ListenerCloseDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ListenerCloseDelegate>(vtable->ListenerClose);
        ListenerStartDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ListenerStartDelegate>(vtable->ListenerStart);
        ListenerStopDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ListenerStopDelegate>(vtable->ListenerStop);
        ConnectionOpenDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ConnectionOpenDelegate>(vtable->ConnectionOpen);
        ConnectionCloseDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ConnectionCloseDelegate>(vtable->ConnectionClose);
        ConnectionSetConfigurationDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ConnectionSetConfigurationDelegate>(vtable->ConnectionSetConfiguration);
        ConnectionShutdownDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ConnectionShutdownDelegate>(vtable->ConnectionShutdown);
        ConnectionStartDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.ConnectionStartDelegate>(vtable->ConnectionStart);
        StreamOpenDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.StreamOpenDelegate>(vtable->StreamOpen);
        StreamCloseDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.StreamCloseDelegate>(vtable->StreamClose);
        StreamStartDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.StreamStartDelegate>(vtable->StreamStart);
        StreamShutdownDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.StreamShutdownDelegate>(vtable->StreamShutdown);
        StreamSendDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.StreamSendDelegate>(vtable->StreamSend);
        StreamReceiveCompleteDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.StreamReceiveCompleteDelegate>(vtable->StreamReceiveComplete);
        StreamReceiveSetEnabledDelegate = Marshal.GetDelegateForFunctionPointer<MsQuicNativeMethods.StreamReceiveSetEnabledDelegate>(vtable->StreamReceiveSetEnabled);
        MsQuicNativeMethods.RegistrationConfig config = new MsQuicNativeMethods.RegistrationConfig
        {
            AppName = ".NET",
            ExecutionProfile = QUIC_EXECUTION_PROFILE.QUIC_EXECUTION_PROFILE_LOW_LATENCY
        };
        SafeMsQuicRegistrationHandle registrationContext;
        uint status = RegistrationOpenDelegate(ref config, out registrationContext);
        QuicExceptionHelpers.ThrowIfFailed(status, "RegistrationOpen failed.");
        Registration = registrationContext;
    }
References System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ConfigurationCloseDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ConfigurationCloseDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ConfigurationLoadCredentialDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ConfigurationLoadCredentialDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ConfigurationOpenDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ConfigurationOpenDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ConnectionCloseDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ConnectionCloseDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ConnectionOpenDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ConnectionOpenDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ConnectionSetConfigurationDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ConnectionSetConfigurationDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ConnectionShutdownDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ConnectionShutdownDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ConnectionStartDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ConnectionStartDelegate(), System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.GetParamDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.GetParamDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ListenerCloseDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ListenerCloseDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ListenerOpenDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ListenerOpenDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ListenerStartDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ListenerStartDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.ListenerStopDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.ListenerStopDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Registration, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.RegistrationCloseDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.RegistrationCloseDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.RegistrationOpenDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.RegistrationOpenDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.SetCallbackHandlerDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.SetCallbackHandlerDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.SetParamDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.SetParamDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.StreamCloseDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.StreamCloseDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.StreamOpenDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.StreamOpenDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.StreamReceiveCompleteDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.StreamReceiveCompleteDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.StreamReceiveSetEnabledDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.StreamReceiveSetEnabledDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.StreamSendDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.StreamSendDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.StreamShutdownDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.StreamShutdownDelegate(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.StreamStartDelegate, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicNativeMethods.StreamStartDelegate(), and System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed().