Terraria: System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi
MsQuicApi() [2/2]
static unsafe System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi () inline static private
Definition at line 107 of file MsQuicApi.cs.
    {
        MinWindowsVersion = new Version(10, 0, 20145, 1000);
        Api = null;
        if (OperatingSystem.IsWindows() && !IsWindowsVersionSupported())
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(null, $"Current Windows version ({Environment.OSVersion}) is not supported by QUIC. Minimal supported version is {MinWindowsVersion}", ".cctor");
            }
        }
        else
        {
            if (!NativeLibrary.TryLoad("msquic.dll", typeof(MsQuicApi).Assembly, DllImportSearchPath.AssemblyDirectory, out var handle))
            {
                return;
            }
            try
            {
                if (NativeLibrary.TryGetExport(handle, "MsQuicOpenVersion", out var address))
                {
                    Unsafe.SkipInit(out MsQuicNativeMethods.NativeApi* vtable);
                    uint status = ((delegate* unmanaged[Cdecl]<uint, out MsQuicNativeMethods.NativeApi*, uint>)(void*)address)(1u, out vtable);
                    if (MsQuicStatusHelper.SuccessfulStatusCode(status))
                    {
                        IsQuicSupported = true;
                        Api = new MsQuicApi(vtable);
                    }
                }
            }
            finally
            {
                if (!IsQuicSupported)
                {
                    NativeLibrary.Free(handle);
                }
            }
        }
    }
References System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Assembly, System.Runtime.InteropServices.Cdecl, System.Runtime.InteropServices.NativeLibrary.Free(), System.handle, System.Net.NetEventSource.Info(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.IsQuicSupported, System.OperatingSystem.IsWindows(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.IsWindowsVersionSupported(), System.Net.NetEventSource.Log, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MinWindowsVersion, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicStatusHelper.SuccessfulStatusCode(), System.Runtime.InteropServices.NativeLibrary.TryGetExport(), System.Runtime.InteropServices.NativeLibrary.TryLoad(), and System.Net.Version.
Referenced by System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi().