Terraria: System.Xml.XmlCharType.IsLowSurrogate
IsLowSurrogate()
static bool System.Xml.XmlCharType.IsLowSurrogate (int ch) inline static package
Definition at line 6664 of file XmlCharType.cs.
    {
        return InRange(ch, 56320, 57343);
    }
References System.ch, and System.Xml.XmlCharType.InRange().
Referenced by System.Xml.XmlSqlBinaryReader.CheckText(), System.Xml.XmlConvert.EncodeName(), System.Xml.XmlCharType.IsOnlyCharData(), System.Xml.XmlConvert.IsXmlSurrogatePair(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseCDataOrCommentTupleAsync(), System.Xml.XmlTextReaderImpl.ParseNumericCharRefInline(), System.Xml.XmlTextReaderImpl.ParsePIValue(), System.Xml.XmlTextReaderImpl.ParsePIValueAsync(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync_Surrogate(), System.Xml.DtdParser.ScanCondSection3(), System.Xml.DtdParser.ScanCondSection3Async(), System.Xml.DtdParser.ScanLiteral(), System.Xml.DtdParser.ScanLiteralAsync(), System.Xml.XmlTextReaderImpl.SkipUntil(), System.Xml.XmlTextReaderImpl.SkipUntilAsync(), System.Xml.XmlEncodedRawTextWriter.ValidateContentChars(), System.Xml.XmlUtf8RawTextWriter.ValidateContentChars(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlTextEncoder.Write(), System.Xml.XmlTextEncoder.Write(), System.Xml.XmlTextEncoder.WriteRawWithSurrogateChecking(), System.Xml.XmlTextEncoder.WriteSurrogateChar(), and System.Xml.XmlTextEncoder.WriteSurrogateCharEntity().