Terraria: System.Xml.XmlCharType.IsAttributeValueChar
IsAttributeValueChar()
static bool System.Xml.XmlCharType.IsAttributeValueChar (char ch) inline static package
Definition at line 6617 of file XmlCharType.cs.
    {
        return (GetCharProperties(ch) & 0x80) != 0;
    }
References System.ch, System.Xml.Dictionary, and System.Xml.XmlCharType.GetCharProperties().
Referenced by System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(), System.Xml.XmlTextReaderImpl.ParseAttributeValueSlowAsync(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.DtdParser.ScanLiteral(), System.Xml.DtdParser.ScanLiteralAsync(), System.Xml.XmlTextReaderImpl.SkipUntil(), System.Xml.XmlTextReaderImpl.SkipUntilAsync(), System.Xml.XmlTextEncoder.Write(), System.Xml.XmlTextEncoder.Write(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlockNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSection(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSection(), System.Xml.XmlEncodedRawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCDataSectionNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(), System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlockNoFlush(), System.Xml.HtmlEncodedRawTextWriter.WriteHtmlAttributeText(), System.Xml.HtmlUtf8RawTextWriter.WriteHtmlAttributeText(), System.Xml.HtmlEncodedRawTextWriter.WriteUriAttributeText(), and System.Xml.HtmlUtf8RawTextWriter.WriteUriAttributeText().