Terraria: System.Xml.XmlCharType.IsTextChar
IsTextChar()
static bool System.Xml.XmlCharType.IsTextChar (char ch) inline static package
Definition at line 6611 of file XmlCharType.cs.
    {
        return (GetCharProperties(ch) & 0x40) != 0;
    }
References System.ch, System.Xml.Dictionary, and System.Xml.XmlCharType.GetCharProperties().
Referenced by System.Xml.XmlTextReaderImpl.ParseCDataOrComment(), System.Xml.XmlTextReaderImpl.ParseCDataOrCommentTupleAsync(), System.Xml.XmlTextReaderImpl.ParsePIValue(), System.Xml.XmlTextReaderImpl.ParsePIValueAsync(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync(), System.Xml.DtdParser.ScanCondSection3(), System.Xml.DtdParser.ScanCondSection3Async(), System.Xml.XmlEncodedRawTextWriter.ValidateContentChars(), System.Xml.XmlUtf8RawTextWriter.ValidateContentChars(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPi(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPi(), System.Xml.XmlEncodedRawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlUtf8RawTextWriter.WriteCommentOrPiNoFlush(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharChecking(), System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(), System.Xml.XmlEncodedRawTextWriter.WriteRawWithCharCheckingNoFlush(), and System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharCheckingNoFlush().