Terraria: System.Xml.XmlCharType.IsOnlyWhitespace
IsOnlyWhitespace()
static bool System.Xml.XmlCharType.IsOnlyWhitespace (string str) inline static package
Definition at line 6686 of file XmlCharType.cs.
    {
        return IsOnlyWhitespaceWithPos(str) == -1;
    }
References System.Xml.XmlCharType.IsOnlyWhitespaceWithPos(), and System.str.
Referenced by System.Xml.Xsl.XsltOld.Compiler.AddBooleanQuery(), System.Xml.Xsl.XsltOld.Compiler.AddStringQuery(), System.Xml.XmlCharacterData.CheckOnData(), System.Xml.Xsl.XsltOld.SequentialOutput.DecideDefaultOutput(), System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.Xsl.Runtime.WhitespaceRuleReader.Read(), System.Xml.Xsl.XsltOld.ReaderOutput.Read(), System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes(), System.Xml.XmlAutoDetectWriter.TextBlockCreatesWriter(), System.Xml.XmlEncodedRawTextWriter.ValidateContentChars(), System.Xml.XmlUtf8RawTextWriter.ValidateContentChars(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), System.Xml.XmlWellFormedWriter.WriteWhitespace(), and System.Xml.XmlWellFormedWriter.WriteWhitespaceAsync().