Terraria: System.Xml.XmlCharType.IsPublicId
IsPublicId()
static int System.Xml.XmlCharType.IsPublicId (string str) inline static package
Definition at line 6737 of file XmlCharType.cs.
    {
        if (str != null)
        {
            for (int i = 0; i < str.Length; i++)
            {
                if (!IsPubidChar(str[i]))
                {
                    return i;
                }
            }
        }
        return -1;
    }
References System.Xml.XmlCharType.IsPubidChar(), and System.str.
Referenced by System.Xml.DtdParser.InitializeFreeFloatingDtd(), System.Xml.DtdParser.ParseExternalId(), System.Xml.DtdParser.ParseExternalIdAsync(), System.Xml.XmlCharCheckingReader.Read(), System.Xml.XmlCharCheckingReader.ReadAsync(), System.Xml.XmlConvert.VerifyPublicId(), System.Xml.XmlCharCheckingWriter.WriteDocType(), System.Xml.XmlWellFormedWriter.WriteDocType(), System.Xml.XmlCharCheckingWriter.WriteDocTypeAsync(), and System.Xml.XmlWellFormedWriter.WriteDocTypeAsync().