Terraria: System.Xml.XmlCharType.IsWhiteSpace
IsWhiteSpace()
static bool System.Xml.XmlCharType.IsWhiteSpace (char ch) inline static
Definition at line 6567 of file XmlCharType.cs.
    {
        return (GetCharProperties(ch) & 1) != 0;
    }
References System.ch, and System.Xml.XmlCharType.GetCharProperties().
Referenced by System.Xml.Xsl.XslLoadException.AppendLineInfoMessage(), System.Xml.XmlSqlBinaryReader.CheckText(), System.Xml.Base64Decoder.Decode(), System.Xml.BinHexDecoder.Decode(), System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.Xsl.XsltOld.ProcessingInstructionAction.IsProcessingInstructionName(), System.Xml.XmlConvert.IsWhitespaceChar(), System.Xml.XmlComplianceUtil.NonCDataNormalize(), MS.Internal.Xml.XPath.StringFunctions.Normalize(), System.Xml.Xsl.Runtime.XsltFunctions.NormalizeSpace(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseAttributeValueChunk(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement(), System.Xml.XmlTextReaderImpl.ParseEndElement(), System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckEndTag(), System.Xml.XmlTextReaderImpl.ParseText(), System.Xml.XmlTextReaderImpl.ParseTextAsync_ParseEntity(), MS.Internal.Xml.XPath.XPathScanner.SkipKnownSpace(), MS.Internal.Xml.XPath.XPathScanner.SkipSpace(), System.Xml.Xsl.XPath.XPathScanner.SkipSpace(), and System.Xml.XmlWellFormedWriter.AttributeValueCache.Trim().