Terraria: System.Xml.XmlCharType.CombineSurrogateChar
CombineSurrogateChar()
static int System.Xml.XmlCharType.CombineSurrogateChar (int lowChar, int highChar) inline static package
Definition at line 6674 of file XmlCharType.cs.
    {
        return (lowChar - 56320) | ((highChar - 55296 << 10) + 65536);
    }
References System.Xml.Dictionary.
Referenced by System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlConvert.EncodeName(), System.Xml.XmlUtf8RawTextWriter.EncodeSurrogate(), System.Xml.CharEntityEncoderFallbackBuffer.SurrogateCharToUtf32(), System.Xml.XmlEncodedRawTextWriter.WriteSurrogateCharEntity(), System.Xml.XmlTextEncoder.WriteSurrogateCharEntity(), System.Xml.XmlUtf8RawTextWriter.WriteSurrogateCharEntity(), System.Xml.XmlEncodedRawTextWriter.WriteSurrogateCharEntityAsync(), and System.Xml.XmlUtf8RawTextWriter.WriteSurrogateCharEntityAsync().