Terraria: System.Xml.XmlCharType.GetCharProperties
GetCharProperties()
static uint System.Xml.XmlCharType.GetCharProperties (char ch) inline static private
Definition at line 6758 of file XmlCharType.cs.
    {
        return Unsafe.Add(ref MemoryMarshal.GetReference(CharProperties), (int)ch);
    }
References System.ch, System.Xml.XmlCharType.CharProperties, and System.Xml.Dictionary.
Referenced by System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlCharType.IsCharData(), System.Xml.XmlCharType.IsLetter(), System.Xml.XmlCharType.IsNCNameCharXml4e(), System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsOnlyCharData(), System.Xml.XmlCharType.IsOnlyWhitespaceWithPos(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.Xml.XmlCharType.IsTextChar(), and System.Xml.XmlCharType.IsWhiteSpace().