Terraria: System.Xml.XmlCharType.IsStartNCNameSingleChar
IsStartNCNameSingleChar()
static bool System.Xml.XmlCharType.IsStartNCNameSingleChar (char ch) inline static
Definition at line 6579 of file XmlCharType.cs.
    {
        return (GetCharProperties(ch) & 4) != 0;
    }
References System.ch, and System.Xml.XmlCharType.GetCharProperties().
Referenced by System.Xml.XmlWellFormedWriter.CheckNCName(), System.Xml.ValidateNames.GetInvalidNameException(), System.Xml.XmlConvert.IsStartNCNameChar(), MS.Internal.Xml.XPath.XPathScanner.NextLex(), System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.XmlTextReaderImpl.ParseAttributes(), System.Xml.XmlTextReaderImpl.ParseAttributesAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync(), System.Xml.ValidateNames.ParseNameNoNamespaces(), System.Xml.ValidateNames.ParseNCName(), System.Xml.XmlTextReaderImpl.ParseQName(), System.Xml.XmlTextReaderImpl.ParseQNameAsync(), System.Xml.DtdParser.ScanQName(), System.Xml.DtdParser.ScanQNameAsync(), and System.Xml.ValidateNames.ThrowInvalidName().