Terraria: System.Numerics.Complex.Tan
Tan()
static Complex System.Numerics.Complex.Tan (Complex value) inline static
Definition at line 423 of file Complex.cs.
    {
        double num = 2.0 * value.m_real;
        double num2 = 2.0 * value.m_imaginary;
        double num3 = Math.Exp(num2);
        double num4 = 1.0 / num3;
        double num5 = (num3 + num4) * 0.5;
        if (Math.Abs(value.m_imaginary) <= 4.0)
        {
            double num6 = (num3 - num4) * 0.5;
            double num7 = Math.Cos(num) + num5;
            return new Complex(Math.Sin(num) / num7, num6 / num7);
        }
        double num8 = 1.0 + Math.Cos(num) / num5;
        return new Complex(Math.Sin(num) / num5 / num8, Math.Tanh(num2) / num8);
    }
References System.Numerics.Complex.Complex(), System.Math.Abs(), System.Math.Cos(), System.Math.Exp(), System.Math.Sin(), System.Math.Tanh(), and System.value.
Referenced by System.Numerics.Complex.Tanh().