Terraria: System.Numerics.Complex.Pow
Pow() [1/2]
static Complex System.Numerics.Complex.Pow (Complex value, Complex power) inline static
Definition at line 613 of file Complex.cs.
    {
        if (power == Zero)
        {
            return One;
        }
        if (value == Zero)
        {
            return Zero;
        }
        double real = value.m_real;
        double imaginary = value.m_imaginary;
        double real2 = power.m_real;
        double imaginary2 = power.m_imaginary;
        double num = Abs(value);
        double num2 = Math.Atan2(imaginary, real);
        double num3 = real2 * num2 + imaginary2 * Math.Log(num);
        double num4 = Math.Pow(num, real2) * Math.Pow(Math.E, (0.0 - imaginary2) * num2);
        return new Complex(num4 * Math.Cos(num3), num4 * Math.Sin(num3));
    }
References System.Numerics.Complex.Complex(), System.Numerics.Complex.Abs(), System.Math.Atan2(), System.Math.Cos(), System.Math.E, System.Math.Log(), System.Numerics.Complex.m_imaginary, System.Numerics.Complex.m_real, System.Numerics.Complex.One, System.Math.Pow(), System.Math.Sin(), System.value, and System.Numerics.Complex.Zero.
Referenced by System.Numerics.Complex.Pow().