Terraria: System.Numerics.Complex.Complex
Complex()
System.Numerics.Complex.Complex (double real, double imaginary) inline
Definition at line 38 of file Complex.cs.
    {
        m_real = real;
        m_imaginary = imaginary;
    }
References System.Numerics.Complex.m_imaginary, and System.Numerics.Complex.m_real.
Referenced by System.Numerics.Complex.Acos(), System.Numerics.Complex.Asin(), System.Numerics.Complex.Atan(), System.Numerics.Complex.Conjugate(), System.Numerics.Complex.Cos(), System.Numerics.Complex.Cosh(), System.Numerics.Complex.Exp(), System.Numerics.Complex.FromPolarCoordinates(), System.Numerics.Complex.Log(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator Complex(), System.Numerics.Complex.operator*(), System.Numerics.Complex.operator*(), System.Numerics.Complex.operator*(), System.Numerics.Complex.operator+(), System.Numerics.Complex.operator+(), System.Numerics.Complex.operator+(), System.Numerics.Complex.operator-(), System.Numerics.Complex.operator-(), System.Numerics.Complex.operator-(), System.Numerics.Complex.operator-(), System.Numerics.Complex.operator/(), System.Numerics.Complex.operator/(), System.Numerics.Complex.operator/(), System.Numerics.Complex.Pow(), System.Numerics.Complex.Pow(), System.Numerics.Complex.Scale(), System.Numerics.Complex.Sin(), System.Numerics.Complex.Sinh(), System.Numerics.Complex.Sqrt(), System.Numerics.Complex.Tan(), and System.Numerics.Complex.Tanh().