Terraria: System.Numerics.Complex.Asin_Internal
Asin_Internal()
static void System.Numerics.Complex.Asin_Internal (double x, double y, out double b, out double bPrime, out double v) inline static private
Definition at line 452 of file Complex.cs.
    {
        if (x > s_asinOverflowThreshold || y > s_asinOverflowThreshold)
        {
            b = -1.0;
            bPrime = x / y;
            double num;
            double num2;
            if (x < y)
            {
                num = x;
                num2 = y;
            }
            else
            {
                num = y;
                num2 = x;
            }
            double num3 = num / num2;
            v = s_log2 + Math.Log(num2) + 0.5 * Log1P(num3 * num3);
            return;
        }
        double num4 = Hypot(x + 1.0, y);
        double num5 = Hypot(x - 1.0, y);
        double num6 = (num4 + num5) * 0.5;
        b = x / num6;
        if (b > 0.75)
        {
            if (x <= 1.0)
            {
                double num7 = (y * y / (num4 + (x + 1.0)) + (num5 + (1.0 - x))) * 0.5;
                bPrime = x / Math.Sqrt((num6 + x) * num7);
            }
            else
            {
                double num8 = (1.0 / (num4 + (x + 1.0)) + 1.0 / (num5 + (x - 1.0))) * 0.5;
                bPrime = x / y / Math.Sqrt((num6 + x) * num8);
            }
        }
        else
        {
            bPrime = -1.0;
        }
        if (num6 < 1.5)
        {
            if (x < 1.0)
            {
                double num9 = (1.0 / (num4 + (x + 1.0)) + 1.0 / (num5 + (1.0 - x))) * 0.5;
                double num10 = y * y * num9;
                v = Log1P(num10 + y * Math.Sqrt(num9 * (num6 + 1.0)));
            }
            else
            {
                double num11 = (y * y / (num4 + (x + 1.0)) + (num5 + (x - 1.0))) * 0.5;
                v = Log1P(num11 + Math.Sqrt(num11 * (num6 + 1.0)));
            }
        }
        else
        {
            v = Math.Log(num6 + Math.Sqrt((num6 - 1.0) * (num6 + 1.0)));
        }
    }
References System.Numerics.Complex.Hypot(), System.Math.Log(), System.Numerics.Complex.Log1P(), System.Numerics.Complex.s_asinOverflowThreshold, System.Numerics.Complex.s_log2, and System.Math.Sqrt().
Referenced by System.Numerics.Complex.Acos(), and System.Numerics.Complex.Asin().