Terraria: System.Numerics.Complex.Hypot
Hypot()
static double System.Numerics.Complex.Hypot (double a, double b) inline static private
Definition at line 244 of file Complex.cs.
    {
        a = Math.Abs(a);
        b = Math.Abs(b);
        double num;
        double num2;
        if (a < b)
        {
            num = a;
            num2 = b;
        }
        else
        {
            num = b;
            num2 = a;
        }
        if (num == 0.0)
        {
            return num2;
        }
        if (double.IsPositiveInfinity(num2) && !double.IsNaN(num))
        {
            return double.PositiveInfinity;
        }
        double num3 = num / num2;
        return num2 * Math.Sqrt(1.0 + num3 * num3);
    }
References System.Math.Abs(), System.Numerics.Complex.IsNaN(), and System.Math.Sqrt().
Referenced by System.Numerics.Complex.Abs(), System.Numerics.Complex.Asin_Internal(), and System.Numerics.Complex.Sqrt().