Terraria: System.Collections.Generic.PriorityQueue.EnqueueRange
EnqueueRange() [2/2]
void System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueRange (IEnumerable<(TElement Element, TPriority Priority)> items) inline
Definition at line 285 of file PriorityQueue.cs.
    {
        if (items == null)
        {
            throw new ArgumentNullException("items");
        }
        int num = 0;
        ICollection<(TElement, TPriority)> collection = items as ICollection<(TElement, TPriority)>;
        if (collection != null && (num = collection.Count) > _nodes.Length - _size)
        {
            Grow(_size + num);
        }
        if (_size == 0)
        {
            if (collection != null)
            {
                collection.CopyTo(_nodes, 0);
                _size = num;
            }
            else
            {
                int num2 = 0;
                (TElement, TPriority)[] nodes = _nodes;
                foreach (var (item, item2) in items)
                {
                    if (nodes.Length == num2)
                    {
                        Grow(num2 + 1);
                        nodes = _nodes;
                    }
                    nodes[num2++] = (item, item2);
                }
                _size = num2;
            }
            _version++;
            if (_size > 1)
            {
                Heapify();
            }
            return;
        }
        foreach (var (element, priority) in items)
        {
            Enqueue(element, priority);
        }
    }
References System.Collections.Generic.PriorityQueue< TElement, TPriority >._nodes, System.Collections.Generic.PriorityQueue< TElement, TPriority >._size, System.Collections.Generic.PriorityQueue< TElement, TPriority >._version, System.collection, System.Collections.Generic.PriorityQueue< TElement, TPriority >.Enqueue(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.Grow(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.Heapify(), and System.item.