Terraria: System.Collections.Generic.PriorityQueue.Grow
Grow()
void System.Collections.Generic.PriorityQueue< TElement, TPriority >.Grow (int minCapacity) inline private
Definition at line 407 of file PriorityQueue.cs.
    {
        int num = 2 * _nodes.Length;
        if ((uint)num > Array.MaxLength)
        {
            num = Array.MaxLength;
        }
        num = Math.Max(num, _nodes.Length + 4);
        if (num < minCapacity)
        {
            num = minCapacity;
        }
        Array.Resize(ref _nodes, num);
    }
References System.Collections.Generic.PriorityQueue< TElement, TPriority >._nodes, System.Math.Max(), and System.Array.MaxLength.
Referenced by System.Collections.Generic.PriorityQueue< TElement, TPriority >.Enqueue(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueRange(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueRange(), and System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnsureCapacity().