Terraria: System.Collections.Generic.PriorityQueue.MoveDownDefaultComparer
MoveDownDefaultComparer()
void System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveDownDefaultComparer ((TElement Element, TPriority Priority) node, int nodeIndex) inline private
Definition at line 509 of file PriorityQueue.cs.
    {
        (TElement, TPriority)[] nodes = _nodes;
        int size = _size;
        int num;
        while ((num = GetFirstChildIndex(nodeIndex)) < size)
        {
            (TElement, TPriority) tuple = nodes[num];
            int num2 = num;
            int num3 = Math.Min(num + 4, size);
            while (++num < num3)
            {
                (TElement, TPriority) tuple2 = nodes[num];
                if (Comparer<TPriority>.Default.Compare(tuple2.Item2, tuple.Item2) < 0)
                {
                    tuple = tuple2;
                    num2 = num;
                }
            }
            if (Comparer<TPriority>.Default.Compare(node.Priority, tuple.Item2) <= 0)
            {
                break;
            }
            nodes[nodeIndex] = tuple;
            nodeIndex = num2;
        }
        nodes[nodeIndex] = node;
    }
References System.Collections.Generic.PriorityQueue< TElement, TPriority >._nodes, System.Collections.Generic.PriorityQueue< TElement, TPriority >._size, System.Default, System.Collections.Generic.PriorityQueue< TElement, TPriority >.GetFirstChildIndex(), and System.Math.Min().
Referenced by System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueDequeue(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.Heapify(), and System.Collections.Generic.PriorityQueue< TElement, TPriority >.RemoveRootNode().