Terraria: System.Collections.Generic.PriorityQueue.Enqueue
Enqueue()
void System.Collections.Generic.PriorityQueue< TElement, TPriority >.Enqueue (TElement element, TPriority priority) inline
Definition at line 198 of file PriorityQueue.cs.
    {
        int num = _size++;
        _version++;
        if (_nodes.Length == num)
        {
            Grow(num + 1);
        }
        if (_comparer == null)
        {
            MoveUpDefaultComparer((Element: element, Priority: priority), num);
        }
        else
        {
            MoveUpCustomComparer((Element: element, Priority: priority), num);
        }
    }
References System.Collections.Generic.PriorityQueue< TElement, TPriority >._comparer, System.Collections.Generic.PriorityQueue< TElement, TPriority >._nodes, System.Collections.Generic.PriorityQueue< TElement, TPriority >._size, System.Collections.Generic.PriorityQueue< TElement, TPriority >._version, System.Collections.Generic.PriorityQueue< TElement, TPriority >.Element, System.Collections.Generic.PriorityQueue< TElement, TPriority >.Grow(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveUpCustomComparer(), and System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveUpDefaultComparer().
Referenced by System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueRange(), and System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueRange().