Terraria: System.Collections.Generic.PriorityQueue.EnqueueDequeue
EnqueueDequeue()
TElement System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueDequeue (TElement element, TPriority priority) inline
Definition at line 261 of file PriorityQueue.cs.
    {
        if (_size != 0)
        {
            (TElement, TPriority) tuple = _nodes[0];
            if (_comparer == null)
            {
                if (Comparer<TPriority>.Default.Compare(priority, tuple.Item2) > 0)
                {
                    MoveDownDefaultComparer((Element: element, Priority: priority), 0);
                    _version++;
                    return tuple.Item1;
                }
            }
            else if (_comparer.Compare(priority, tuple.Item2) > 0)
            {
                MoveDownCustomComparer((Element: element, Priority: priority), 0);
                _version++;
                return tuple.Item1;
            }
        }
        return element;
    }
References System.Collections.Generic.PriorityQueue< TElement, TPriority >._comparer, System.Collections.Generic.PriorityQueue< TElement, TPriority >._nodes, System.Collections.Generic.PriorityQueue< TElement, TPriority >._size, System.Collections.Generic.PriorityQueue< TElement, TPriority >._version, System.Collections.Generic.IComparer< in T >.Compare(), System.Default, System.Collections.Generic.PriorityQueue< TElement, TPriority >.Element, System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveDownCustomComparer(), and System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveDownDefaultComparer().