Terraria: System.Collections.Generic.PriorityQueue.EnqueueRange
EnqueueRange() [1/2]
void System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueRange (IEnumerable< TElement > elements, TPriority priority) inline
Definition at line 332 of file PriorityQueue.cs.
    {
        if (elements == null)
        {
            throw new ArgumentNullException("elements");
        }
        if (elements is ICollection<(TElement, TPriority)> { Count: var count })
        {
            int num = count;
            if (count > _nodes.Length - _size)
            {
                Grow(_size + num);
            }
        }
        if (_size == 0)
        {
            int num2 = 0;
            (TElement, TPriority)[] nodes = _nodes;
            foreach (TElement element in elements)
            {
                if (nodes.Length == num2)
                {
                    Grow(num2 + 1);
                    nodes = _nodes;
                }
                nodes[num2++] = (element, priority);
            }
            _size = num2;
            _version++;
            if (num2 > 1)
            {
                Heapify();
            }
            return;
        }
        foreach (TElement element2 in elements)
        {
            Enqueue(element2, priority);
        }
    }
References System.Collections.Generic.PriorityQueue< TElement, TPriority >._nodes, System.Collections.Generic.PriorityQueue< TElement, TPriority >._size, System.Collections.Generic.PriorityQueue< TElement, TPriority >._version, System.Collections.Generic.PriorityQueue< TElement, TPriority >.Count, System.count, System.Collections.Generic.PriorityQueue< TElement, TPriority >.Enqueue(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.Grow(), and System.Collections.Generic.PriorityQueue< TElement, TPriority >.Heapify().