Terraria: System.Collections.Generic.PriorityQueue.Heapify
Heapify()
void System.Collections.Generic.PriorityQueue< TElement, TPriority >.Heapify () inline private
Definition at line 454 of file PriorityQueue.cs.
    {
        (TElement, TPriority)[] nodes = _nodes;
        int parentIndex = GetParentIndex(_size - 1);
        if (_comparer == null)
        {
            for (int num = parentIndex; num >= 0; num--)
            {
                MoveDownDefaultComparer(nodes[num], num);
            }
        }
        else
        {
            for (int num2 = parentIndex; num2 >= 0; num2--)
            {
                MoveDownCustomComparer(nodes[num2], num2);
            }
        }
    }
References System.Collections.Generic.PriorityQueue< TElement, TPriority >._comparer, System.Collections.Generic.PriorityQueue< TElement, TPriority >._nodes, System.Collections.Generic.PriorityQueue< TElement, TPriority >._size, System.Collections.Generic.PriorityQueue< TElement, TPriority >.GetParentIndex(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveDownCustomComparer(), and System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveDownDefaultComparer().
Referenced by System.Collections.Generic.PriorityQueue< TElement, TPriority >.PriorityQueue(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueRange(), and System.Collections.Generic.PriorityQueue< TElement, TPriority >.EnqueueRange().