Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget.TryCleanupAndComplete
TryCleanupAndComplete()
bool System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.TryCleanupAndComplete (ReceiveCoreByLinkingCleanupReason reason) inline package
Definition at line 513 of file DataflowBlock.cs.
        {
            if (Volatile.Read(ref _cleanupReserved))
            {
                return false;
            }
            lock (IncomingLock)
            {
                if (_cleanupReserved)
                {
                    return false;
                }
                _cleanupReserved = true;
            }
            CleanupAndComplete(reason);
            return true;
        }
References System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >._cleanupReserved, System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.CleanupAndComplete(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.IncomingLock, and System.Threading.Volatile.Read().
Referenced by System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.Complete().