Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget.CleanupAndComplete
CleanupAndComplete()
void System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.CleanupAndComplete (ReceiveCoreByLinkingCleanupReason reason) inline private
Definition at line 531 of file DataflowBlock.cs.
        {
            IDisposable unlink = _unlink;
            if (reason != ReceiveCoreByLinkingCleanupReason.SourceCompletion && unlink != null)
            {
                IDisposable disposable = Interlocked.CompareExchange(ref _unlink, null, unlink);
                if (disposable != null)
                {
                    try
                    {
                        disposable.Dispose();
                    }
                    catch (Exception receivedException)
                    {
                        _receivedException = receivedException;
                        reason = ReceiveCoreByLinkingCleanupReason.SourceProtocolError;
                    }
                }
            }
            if (_timer != null)
            {
                _timer.Dispose();
            }
            if (reason != ReceiveCoreByLinkingCleanupReason.Cancellation)
            {
                if (reason == ReceiveCoreByLinkingCleanupReason.SourceCompletion && (_externalCancellationToken.IsCancellationRequested || _cts.IsCancellationRequested))
                {
                    reason = ReceiveCoreByLinkingCleanupReason.Cancellation;
                }
                _cts.Cancel();
            }
            _regFromExternalCancellationToken.Dispose();
            switch (reason)
            {
            case ReceiveCoreByLinkingCleanupReason.Success:
                System.Threading.Tasks.Task.Factory.StartNew(delegate(object state)
                {
                    ReceiveTarget<T> receiveTarget2 = (ReceiveTarget<T>)state;
                    try
                    {
                        receiveTarget2.TrySetResult(receiveTarget2._receivedValue);
                    }
                    catch (ObjectDisposedException)
                    {
                    }
                }, this, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default);
                return;
            default:
                System.Threading.Tasks.Task.Factory.StartNew(delegate(object state)
                {
                    ReceiveTarget<T> receiveTarget3 = (ReceiveTarget<T>)state;
                    try
                    {
                        receiveTarget3.TrySetCanceled();
                    }
                    catch (ObjectDisposedException)
                    {
                    }
                }, this, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default);
                return;
            case ReceiveCoreByLinkingCleanupReason.SourceCompletion:
                if (_receivedException == null)
                {
                    _receivedException = CreateExceptionForSourceCompletion();
                }
                break;
            case ReceiveCoreByLinkingCleanupReason.Timer:
                if (_receivedException == null)
                {
                    _receivedException = CreateExceptionForTimeout();
                }
                break;
            case ReceiveCoreByLinkingCleanupReason.SourceProtocolError:
            case ReceiveCoreByLinkingCleanupReason.ErrorDuringCleanup:
                break;
            }
            System.Threading.Tasks.Task.Factory.StartNew(delegate(object state)
            {
                ReceiveTarget<T> receiveTarget = (ReceiveTarget<T>)state;
                try
                {
                    receiveTarget.TrySetException(receiveTarget._receivedException ?? new InvalidOperationException(System.SR.InvalidOperation_ErrorDuringCleanup));
                }
                catch (ObjectDisposedException)
                {
                }
            }, this, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default);
        }
References System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >._cts, System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >._externalCancellationToken, System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >._receivedException, System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >._regFromExternalCancellationToken, System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >._timer, System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >._unlink, System.Threading.CancellationTokenSource.Cancel(), System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.CreateExceptionForSourceCompletion(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.CreateExceptionForTimeout(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.CancellationTokenRegistration.Dispose(), System.Threading.Timer.Dispose(), System.Threading.Tasks.Task< TResult >.Factory, System.SR.InvalidOperation_ErrorDuringCleanup, System.Threading.CancellationToken.IsCancellationRequested, System.Threading.CancellationTokenSource.IsCancellationRequested, System.Threading.CancellationToken.None, and System.state.
Referenced by System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.OfferMessage(), and System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.TryCleanupAndComplete().