Terraria: System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace
SetCurrentStackTrace()
static Exception System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace (Exception source) inline static
Definition at line 45 of file ExceptionDispatchInfo.cs.
    {
        if (source == null)
        {
            throw new ArgumentNullException("source");
        }
        source.SetCurrentStackTrace();
        return source;
    }
References System.source.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortRead(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.AbortWrite(), System.IO.StreamBuffer.ResettableValueTaskSource.CancelWaiter(), System.Net.Quic.Implementations.Mock.MockConnection.StreamLimit.CloseWaiters(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.CopyTo(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.CopyToAsync(), System.Net.Http.HttpConnectionPool.CreateConnectTimeoutException(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(), System.Net.Http.CreditWaiter.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose(), System.Net.Sockets.Socket.GetException(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventPeerRecvAborted(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventPeerSendAborted(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventSendComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteStartState(), System.Net.NameResolutionPal.ProcessResult(), System.IO.File.ReadAllBytesAsync(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.ReadAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync(), System.Net.Http.CreditWaiter.RegisterCancellation(), System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(), System.Net.Http.MessageProcessingHandler.SendAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ShutdownCompleted(), System.Threading.PeriodicTimer.State.Signal(), System.Net.FtpWebRequest.SubmitRequest(), System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync(), System.Net.Http.Http2Connection.Http2Stream.WaitForDataAsync(), System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync(), System.IO.Pipes.PipeStream.WriteAsyncCore(), and System.Net.Security.SslStream.WriteSingleChunk< TIOAdapter >().