Terraria: Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.categoryButton_OnUpdate
categoryButton_OnUpdate()
void Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.categoryButton_OnUpdate (UIElement affectedElement) inline private inherited
Definition at line 321 of file CreativePowers.cs.
        {
            if (affectedElement.IsMouseHovering)
            {
                GroupOptionButton<int> groupOptionButton = affectedElement as GroupOptionButton<int>;
                string originalText = Language.GetTextValue(_powerNameKey + (groupOptionButton.IsSelected ? "_Opened" : "_Closed"));
                CreativePowersHelper.AddDescriptionIfNeeded(ref originalText, _powerNameKey + "_Description");
                CreativePowersHelper.AddUnlockTextIfNeeded(ref originalText, GetIsUnlocked(), _powerNameKey + "_Unlock");
                CreativePowersHelper.AddPermissionTextIfNeeded(this, ref originalText);
                Main.instance.MouseTextNoOverride(originalText, 0, 0);
            }
            AttemptPushingChange();
        }
References Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower._powerNameKey, Terraria.GameContent.Creative.CreativePowersHelper.AddDescriptionIfNeeded(), Terraria.GameContent.Creative.CreativePowersHelper.AddPermissionTextIfNeeded(), Terraria.GameContent.Creative.CreativePowersHelper.AddUnlockTextIfNeeded(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.AttemptPushingChange(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.GetIsUnlocked(), Terraria.Localization.Language.GetTextValue(), and Terraria.Main.instance.
Referenced by Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.GetOptionButton().