Terraria: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture
Capture()
static ExceptionDispatchInfo System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture (Exception source) inline static
Definition at line 20 of file ExceptionDispatchInfo.cs.
    {
        if (source == null)
        {
            throw new ArgumentNullException("source");
        }
        return new ExceptionDispatchInfo(source);
    }
References System.Runtime.ExceptionServices.ExceptionDispatchInfo.ExceptionDispatchInfo(), and System.source.
Referenced by System.LazyHelper.LazyHelper(), System.Threading.Tasks.TaskExceptionHolder.AddFaultException(), System.Net.Security.SslStream.CompleteHandshake(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.TcpClient.Connect(), System.Text.Json.WriteStack.DisposeCompletedAsyncDisposables(), System.Text.Json.WriteStack.DisposePendingDisposablesOnException(), System.Text.Json.WriteStack.DisposePendingDisposablesOnExceptionAsync(), System.Diagnostics.AsyncStreamReader.FlushMessageQueue(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeContinuationWithContext(), System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(), System.Threading.ExecutionContext.RunInternal(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Threading.Tasks.TaskExceptionHolder.SetCancellationException(), System.Net.Security.SslStream.SetException(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetException(), System.Net.Security.NegotiateStream.SetFailed(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(), System.Threading.Tasks.Dataflow.Internal.Common.ThrowAsync(), System.Threading.Tasks.Task< TResult >.ThrowAsync(), System.Reflection.PortableExecutable.PEReader.TryOpenAssociatedPortablePdb(), System.Threading.Channels.AsyncOperation< TResult >.TrySetCanceled(), and System.Threading.Channels.AsyncOperation< TResult >.TrySetException().