Terraria: Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.PushChangeAndSetSlider
PushChangeAndSetSlider()
void Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.PushChangeAndSetSlider (float value) inline inherited
Definition at line 301 of file CreativePowers.cs.
        {
            if (CreativePowersHelper.IsAvailableForPlayer(this, Main.myPlayer))
            {
                value = MathHelper.Clamp(value, 0f, 1f);
                _sliderCurrentValueCache = value;
                _currentTargetValue = value;
                PushChange(value);
            }
        }
References Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower._currentTargetValue, Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower._sliderCurrentValueCache, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.GameContent.Creative.CreativePowersHelper.IsAvailableForPlayer(), Terraria.Main.myPlayer, Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.PushChange(), and System.value.
Referenced by Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.ApplyLoadedDataToOutOfPlayerFields().