Terraria: System.ComponentModel.PropertyDescriptorCollection.EnsurePropsOwned
EnsurePropsOwned()
void System.ComponentModel.PropertyDescriptorCollection.EnsurePropsOwned () inline private
Definition at line 277 of file PropertyDescriptorCollection.cs.
    {
        if (!_propsOwned)
        {
            _propsOwned = true;
            if (_properties != null)
            {
                PropertyDescriptor[] array = new PropertyDescriptor[Count];
                Array.Copy(_properties, array, Count);
                _properties = array;
            }
        }
        if (_needSort)
        {
            _needSort = false;
            InternalSort(_namedSort);
        }
    }
References System.ComponentModel.PropertyDescriptorCollection._namedSort, System.ComponentModel.PropertyDescriptorCollection._needSort, System.ComponentModel.PropertyDescriptorCollection._properties, System.ComponentModel.PropertyDescriptorCollection._propsOwned, System.array, System.Array.Copy(), System.ComponentModel.PropertyDescriptorCollection.Count, and System.ComponentModel.PropertyDescriptorCollection.InternalSort().
Referenced by System.ComponentModel.PropertyDescriptorCollection.CopyTo(), System.ComponentModel.PropertyDescriptorCollection.EnsureSize(), and System.ComponentModel.PropertyDescriptorCollection.GetEnumerator().