Terraria: System.ComponentModel.PropertyDescriptorCollection.Sort
Sort() [1/4]
virtual PropertyDescriptorCollection System.ComponentModel.PropertyDescriptorCollection.Sort () inline virtual
Definition at line 405 of file PropertyDescriptorCollection.cs.
    {
        return new PropertyDescriptorCollection(_properties, Count, _namedSort, _comparer);
    }
References System.ComponentModel.PropertyDescriptorCollection.PropertyDescriptorCollection(), System.ComponentModel.PropertyDescriptorCollection._comparer, System.ComponentModel.PropertyDescriptorCollection._namedSort, System.ComponentModel.PropertyDescriptorCollection._properties, and System.ComponentModel.PropertyDescriptorCollection.Count.
Referenced by System.Drawing.SizeConverter.GetProperties(), System.Drawing.SizeFConverter.GetProperties(), System.Drawing.PointConverter.GetProperties(), System.Drawing.RectangleConverter.GetProperties(), and System.ComponentModel.TypeConverter.SortProperties().