Terraria: System.Xml.Schema.XmlBaseConverter.DoubleType
DoubleType
readonly Type System.Xml.Schema.XmlBaseConverter.DoubleType = typeof(double) static protected inherited
Definition at line 52 of file XmlBaseConverter.cs.
Referenced by System.Xml.Schema.XmlListConverter.ChangeListType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.SupportsType(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlAnyConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlNumeric2Converter.ToDouble(), System.Xml.Schema.XmlUntypedConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlNumeric2Converter.ToSingle(), System.Xml.Schema.XmlNumeric2Converter.ToString(), and System.Xml.Schema.XmlUntypedConverter.ToString().