Terraria: System.Xml.Schema.XmlBaseConverter.StringType
StringType
readonly Type System.Xml.Schema.XmlBaseConverter.StringType = typeof(string) static protected inherited
Definition at line 32 of file XmlBaseConverter.cs.
Referenced by System.Xml.Schema.XmlListConverter.ChangeListType(), System.Xml.Schema.XmlUntypedConverter.ChangeListType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlAnyListConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlStringConverter.ChangeType(), System.Xml.Schema.XmlUnionConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlStringConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlListConverter.IsListType(), System.Xml.Schema.XmlBooleanConverter.ToBoolean(), System.Xml.Schema.XmlUntypedConverter.ToBoolean(), System.Xml.Schema.XmlDateTimeConverter.ToDateTime(), System.Xml.Schema.XmlUntypedConverter.ToDateTime(), System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset(), System.Xml.Schema.XmlUntypedConverter.ToDateTimeOffset(), System.Xml.Schema.XmlNumeric10Converter.ToDecimal(), System.Xml.Schema.XmlUntypedConverter.ToDecimal(), System.Xml.Schema.XmlNumeric2Converter.ToDouble(), System.Xml.Schema.XmlUntypedConverter.ToDouble(), System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.Xml.Schema.XmlUntypedConverter.ToInt32(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), System.Xml.Schema.XmlUntypedConverter.ToInt64(), System.Xml.Schema.XmlNumeric2Converter.ToSingle(), System.Xml.Schema.XmlUntypedConverter.ToSingle(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBooleanConverter.ToString(), System.Xml.Schema.XmlDateTimeConverter.ToString(), System.Xml.Schema.XmlMiscConverter.ToString(), System.Xml.Schema.XmlNumeric10Converter.ToString(), System.Xml.Schema.XmlNumeric2Converter.ToString(), System.Xml.Schema.XmlStringConverter.ToString(), and System.Xml.Schema.XmlUntypedConverter.ToString().