Terraria: System.Xml.Schema.XmlBaseConverter.ChangeListType
ChangeListType()
virtual object System.Xml.Schema.XmlBaseConverter.ChangeListType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline protected virtual inherited
Reimplemented in System.Xml.Schema.XmlListConverter, and System.Xml.Schema.XmlUntypedConverter.
Definition at line 474 of file XmlBaseConverter.cs.
    {
        throw CreateInvalidClrMappingException(value.GetType(), destinationType);
    }
References System.Xml.Schema.XmlBaseConverter.CreateInvalidClrMappingException(), System.Xml.Dictionary, and System.value.
Referenced by System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlStringConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlStringConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlAnyConverter.ChangeTypeWildcardSource(), System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardSource(), System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardSource(), System.Xml.Schema.XmlBooleanConverter.ToBoolean(), System.Xml.Schema.XmlDateTimeConverter.ToDateTime(), System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset(), System.Xml.Schema.XmlNumeric2Converter.ToDouble(), System.Xml.Schema.XmlNumeric2Converter.ToSingle(), System.Xml.Schema.XmlBooleanConverter.ToString(), System.Xml.Schema.XmlDateTimeConverter.ToString(), System.Xml.Schema.XmlNumeric2Converter.ToString(), and System.Xml.Schema.XmlStringConverter.ToString().