Terraria: System.ComponentModel.PropertyDescriptorCollection.Add
Add() [3/5]
int System.ComponentModel.PropertyDescriptorCollection.Add (PropertyDescriptor value) inline
Definition at line 245 of file PropertyDescriptorCollection.cs.
    {
        if (_readOnly)
        {
            throw new NotSupportedException();
        }
        EnsureSize(Count + 1);
        _properties[Count++] = value;
        return Count - 1;
    }
References System.ComponentModel.PropertyDescriptorCollection._properties, System.ComponentModel.PropertyDescriptorCollection._readOnly, System.ComponentModel.PropertyDescriptorCollection.Count, System.ComponentModel.PropertyDescriptorCollection.EnsureSize(), and System.value.
Referenced by MS.Internal.Xml.Linq.ComponentModel.XTypeDescriptor< T >.GetProperties(), and System.ComponentModel.Design.DesignerOptionService.DesignerOptionConverter.GetProperties().