Terraria: System.Xml.Schema.XmlBaseConverter.ChangeType
ChangeType() [1/9]
override object System.Xml.Schema.XmlBaseConverter.ChangeType (bool value, Type destinationType) inline inherited
Definition at line 395 of file XmlBaseConverter.cs.
    {
        return ChangeType(value, destinationType, null);
    }
References System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Dictionary, and System.value.
Referenced by System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.ChangeType(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToDateTime(), System.Xml.Schema.XmlBaseConverter.ToDateTime(), System.Xml.Schema.XmlBaseConverter.ToDateTime(), System.Xml.Schema.XmlBaseConverter.ToDateTime(), System.Xml.Schema.XmlBaseConverter.ToDateTime(), System.Xml.Schema.XmlBaseConverter.ToDateTime(), System.Xml.Schema.XmlBaseConverter.ToDateTime(), System.Xml.Schema.XmlBaseConverter.ToDateTimeOffset(), System.Xml.Schema.XmlBaseConverter.ToDateTimeOffset(), System.Xml.Schema.XmlBaseConverter.ToDateTimeOffset(), System.Xml.Schema.XmlBaseConverter.ToDecimal(), System.Xml.Schema.XmlBaseConverter.ToDecimal(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToDouble(), System.Xml.Schema.XmlBaseConverter.ToInt32(), System.Xml.Schema.XmlBaseConverter.ToInt32(), System.Xml.Schema.XmlBaseConverter.ToInt32(), System.Xml.Schema.XmlBaseConverter.ToInt32(), System.Xml.Schema.XmlBaseConverter.ToInt32(), System.Xml.Schema.XmlBaseConverter.ToInt32(), System.Xml.Schema.XmlBaseConverter.ToInt64(), System.Xml.Schema.XmlBaseConverter.ToInt64(), System.Xml.Schema.XmlBaseConverter.ToInt64(), System.Xml.Schema.XmlBaseConverter.ToInt64(), System.Xml.Schema.XmlBaseConverter.ToInt64(), System.Xml.Schema.XmlBaseConverter.ToInt64(), System.Xml.Schema.XmlBaseConverter.ToSingle(), System.Xml.Schema.XmlBaseConverter.ToSingle(), System.Xml.Schema.XmlBaseConverter.ToSingle(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), System.Xml.Schema.XmlBaseConverter.ToString(), and System.Xml.Schema.XmlBaseConverter.ToString().