Terraria: System.ComponentModel.PropertyDescriptorCollection.PropertyDescriptorCollection
PropertyDescriptorCollection() [1/3]
System.ComponentModel.PropertyDescriptorCollection.PropertyDescriptorCollection (PropertyDescriptor?[] properties) inline
Definition at line 211 of file PropertyDescriptorCollection.cs.
    {
        if (properties == null)
        {
            _properties = Array.Empty<PropertyDescriptor>();
            Count = 0;
        }
        else
        {
            _properties = properties;
            Count = properties.Length;
        }
        _propsOwned = true;
    }
References System.ComponentModel.PropertyDescriptorCollection._properties, System.ComponentModel.PropertyDescriptorCollection._propsOwned, and System.ComponentModel.PropertyDescriptorCollection.Count.
Referenced by System.ComponentModel.PropertyDescriptorCollection.Sort(), System.ComponentModel.PropertyDescriptorCollection.Sort(), System.ComponentModel.PropertyDescriptorCollection.Sort(), and System.ComponentModel.PropertyDescriptorCollection.Sort().