Terraria: System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType
XmlAtomicValueType
readonly Type System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType = typeof(XmlAtomicValue) static protected inherited
Definition at line 34 of file XmlBaseConverter.cs.
Referenced by System.Xml.Schema.XmlBaseConverter.XmlBaseConverter(), System.Xml.Schema.XmlListConverter.ChangeListType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlStringConverter.ChangeType(), System.Xml.Schema.XmlUnionConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlDateTimeConverter.ChangeType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric2Converter.ChangeType(), System.Xml.Schema.XmlStringConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlAnyConverter.ChangeTypeWildcardSource(), System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardSource(), System.Xml.Schema.XmlUntypedConverter.ChangeTypeWildcardSource(), System.Xml.Schema.XmlAnyConverter.ToBoolean(), System.Xml.Schema.XmlBooleanConverter.ToBoolean(), System.Xml.Schema.XmlAnyConverter.ToDateTime(), System.Xml.Schema.XmlDateTimeConverter.ToDateTime(), System.Xml.Schema.XmlAnyConverter.ToDateTimeOffset(), System.Xml.Schema.XmlDateTimeConverter.ToDateTimeOffset(), System.Xml.Schema.XmlAnyConverter.ToDecimal(), System.Xml.Schema.XmlNumeric10Converter.ToDecimal(), System.Xml.Schema.XmlAnyConverter.ToDouble(), System.Xml.Schema.XmlNumeric2Converter.ToDouble(), System.Xml.Schema.XmlAnyConverter.ToInt32(), System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.Xml.Schema.XmlAnyConverter.ToInt64(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), System.Xml.Schema.XmlAnyConverter.ToSingle(), System.Xml.Schema.XmlNumeric2Converter.ToSingle(), System.Xml.Schema.XmlBooleanConverter.ToString(), System.Xml.Schema.XmlDateTimeConverter.ToString(), System.Xml.Schema.XmlNumeric10Converter.ToString(), System.Xml.Schema.XmlNumeric2Converter.ToString(), System.Xml.Schema.XmlStringConverter.ToString(), and System.Xml.Schema.XmlUntypedConverter.ToString().