Terraria: System.Xml.Schema.XmlBaseConverter.BooleanType
BooleanType
readonly Type System.Xml.Schema.XmlBaseConverter.BooleanType = typeof(bool) static protected inherited
Definition at line 60 of file XmlBaseConverter.cs.
Referenced by System.Xml.Schema.XmlListConverter.ChangeListType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlAnyConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.SupportsType(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlAnyConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBooleanConverter.ToBoolean(), System.Xml.Schema.XmlUntypedConverter.ToBoolean(), System.Xml.Schema.XmlBaseConverter.ToBoolean(), System.Xml.Schema.XmlBooleanConverter.ToString(), and System.Xml.Schema.XmlUntypedConverter.ToString().