Terraria: System.ComponentModel.PropertyDescriptorCollection.EnsureSize
EnsureSize()
void System.ComponentModel.PropertyDescriptorCollection.EnsureSize (int sizeNeeded) inline private
Definition at line 296 of file PropertyDescriptorCollection.cs.
    {
        if (sizeNeeded > _properties.Length)
        {
            if (_properties.Length == 0)
            {
                Count = 0;
                _properties = new PropertyDescriptor[sizeNeeded];
                return;
            }
            EnsurePropsOwned();
            int num = Math.Max(sizeNeeded, _properties.Length * 2);
            PropertyDescriptor[] array = new PropertyDescriptor[num];
            Array.Copy(_properties, array, Count);
            _properties = array;
        }
    }
References System.ComponentModel.PropertyDescriptorCollection._properties, System.array, System.Array.Copy(), System.ComponentModel.PropertyDescriptorCollection.Count, System.ComponentModel.PropertyDescriptorCollection.EnsurePropsOwned(), and System.Math.Max().
Referenced by System.ComponentModel.PropertyDescriptorCollection.Add(), and System.ComponentModel.PropertyDescriptorCollection.Insert().