Terraria: System.ComponentModel.PropertyDescriptorCollection.Find
Find()
virtual ? PropertyDescriptor System.ComponentModel.PropertyDescriptorCollection.Find (string name, bool ignoreCase) inline virtual
Definition at line 314 of file PropertyDescriptorCollection.cs.
    {
        lock (_internalSyncObject)
        {
            PropertyDescriptor result = null;
            if (_cachedFoundProperties == null || _cachedIgnoreCase != ignoreCase)
            {
                _cachedIgnoreCase = ignoreCase;
                if (ignoreCase)
                {
                    _cachedFoundProperties = new Hashtable(StringComparer.OrdinalIgnoreCase);
                }
                else
                {
                    _cachedFoundProperties = new Hashtable();
                }
            }
            object obj = _cachedFoundProperties[name];
            if (obj != null)
            {
                return (PropertyDescriptor)obj;
            }
            for (int i = 0; i < Count; i++)
            {
                if (ignoreCase)
                {
                    if (string.Equals(_properties[i].Name, name, StringComparison.OrdinalIgnoreCase))
                    {
                        _cachedFoundProperties[name] = _properties[i];
                        result = _properties[i];
                        break;
                    }
                }
                else if (_properties[i].Name.Equals(name))
                {
                    _cachedFoundProperties[name] = _properties[i];
                    result = _properties[i];
                    break;
                }
            }
            return result;
        }
    }
References System.ComponentModel.PropertyDescriptorCollection._cachedFoundProperties, System.ComponentModel.PropertyDescriptorCollection._cachedIgnoreCase, System.ComponentModel.PropertyDescriptorCollection._internalSyncObject, System.ComponentModel.PropertyDescriptorCollection._properties, System.ComponentModel.PropertyDescriptorCollection.Count, System.ComponentModel.PropertyDescriptor.Equals(), System.Name, System.obj, and System.StringComparer.OrdinalIgnoreCase.
Referenced by System.ComponentModel.BindingList< T >.Child_PropertyChanged(), Terraria.Localization.LocalizedText.FormatWith(), and Terraria.Utils.FormatWith().