Terraria: System.Xml.Xsl.Xslt.DecimalFormatDecl.Default
Default
DecimalFormatDecl System.Xml.Xsl.Xslt.DecimalFormatDecl.Default = new DecimalFormatDecl(new XmlQualifiedName(), "Infinity", "NaN", ".,%‰0#;-") static
Definition at line 13 of file DecimalFormatDecl.cs.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileInitializationCode(), and System.Xml.Xsl.Xslt.XsltLoader.LoadDecimalFormat().