Terraria: WaterfallManager.TrySparkling
TrySparkling()
static void WaterfallManager.TrySparkling (int x, int y, int direction, Color aColor2) inline static private
     {
         if (aColor2.R > 20 || aColor2.B > 20 || aColor2.G > 20)
         {
             float num = (int)aColor2.R;
             if ((float)(int)aColor2.G > num)
             {
                 num = (int)aColor2.G;
             }
             if ((float)(int)aColor2.B > num)
             {
                 num = (int)aColor2.B;
             }
             if ((float)Main.rand.Next(20000) < num / 30f)
             {
                 int num2 = Dust.NewDust(new Vector2(x * 16 - direction * 7, y * 16 + 6), 10, 8, 43, 0f, 0f, 254, Color.White, 0.5f);
                 Main.dust[num2].velocity *= 0f;
             }
         }
     }
References Color, Main.dust, Dust.NewDust(), UnifiedRandom.Next(), Main.rand, and Dust.velocity.
Referenced by DrawWaterfall().