Terraria: WaterfallManager.DrawWaterfall
DrawWaterfall() [2/2]
void WaterfallManager.DrawWaterfall (int waterfallType, int x, int y, float opacity, Vector2 position, Rectangle sourceRect, Color color, SpriteEffects effects) inline private
     {
         Texture2D value = waterfallTexture[waterfallType].Value;
         if (waterfallType == 25)
         {
             Lighting.GetCornerColors(x, y, out var vertices);
             LiquidRenderer.SetShimmerVertexColors(ref vertices, opacity, x, y);
             Main.tileBatch.Draw(value, position + new Vector2(0f, 0f), sourceRect, vertices, default(Vector2), 1f, effects);
             sourceRect.Y += 42;
             LiquidRenderer.SetShimmerVertexColors_Sparkle(ref vertices, opacity, x, y, top: true);
             Main.tileBatch.Draw(value, position + new Vector2(0f, 0f), sourceRect, vertices, default(Vector2), 1f, effects);
         }
         else
         {
             Main.spriteBatch.Draw(value, position, sourceRect, color, 0f, default(Vector2), 1f, effects, 0f);
         }
     }
References TileBatch.Draw(), Lighting.GetCornerColors(), LiquidRenderer.SetShimmerVertexColors(), LiquidRenderer.SetShimmerVertexColors_Sparkle(), Main.spriteBatch, Main.tileBatch, Asset< T >.Value, and waterfallTexture.