Terraria: PopupText.NewText
NewText() [3/3]
static int PopupText.NewText (PopupTextContext context, Item newItem, int stack, bool noStack = false, bool longText = false) inline static
     {
         if (!Main.showItemText)
         {
             return -1;
         }
         if (newItem.Name == null || !newItem.active)
         {
             return -1;
         }
         if (Main.netMode == 2)
         {
             return -1;
         }
         bool flag = newItem.type >= 71 && newItem.type <= 74;
         for (int i = 0; i < 20; i++)
         {
             PopupText popupText = Main.popupText[i];
             if (!popupText.active || popupText.notActuallyAnItem || (!(popupText.name == newItem.AffixName()) && (!flag || !popupText.coinText)) || popupText.NoStack || noStack)
             {
                 continue;
             }
             string text = newItem.Name + " (" + (popupText.stack + stack) + ")";
             string text2 = newItem.Name;
             if (popupText.stack > 1)
             {
                 text2 = text2 + " (" + popupText.stack + ")";
             }
             Vector2 vector = FontAssets.MouseText.Value.MeasureString(text2);
             vector = FontAssets.MouseText.Value.MeasureString(text);
             if (popupText.lifeTime < 0)
             {
                 popupText.scale = 1f;
             }
             if (popupText.lifeTime < 60)
             {
                 popupText.lifeTime = 60;
             }
             if (flag && popupText.coinText)
             {
                 long num = 0L;
                 if (newItem.type == 71)
                 {
                     num += stack;
                 }
                 else if (newItem.type == 72)
                 {
                     num += 100 * stack;
                 }
                 else if (newItem.type == 73)
                 {
                     num += 10000 * stack;
                 }
                 else if (newItem.type == 74)
                 {
                     num += 1000000 * stack;
                 }
                 popupText.AddToCoinValue(num);
                 text = ValueToName(popupText.coinValue);
                 vector = FontAssets.MouseText.Value.MeasureString(text);
                 popupText.name = text;
                 if (popupText.coinValue >= 1000000)
                 {
                     if (popupText.lifeTime < 300)
                     {
                         popupText.lifeTime = 300;
                     }
                     popupText.color = new Color(220, 220, 198);
                 }
                 else if (popupText.coinValue >= 10000)
                 {
                     if (popupText.lifeTime < 240)
                     {
                         popupText.lifeTime = 240;
                     }
                     popupText.color = new Color(224, 201, 92);
                 }
                 else if (popupText.coinValue >= 100)
                 {
                     if (popupText.lifeTime < 180)
                     {
                         popupText.lifeTime = 180;
                     }
                     popupText.color = new Color(181, 192, 193);
                 }
                 else if (popupText.coinValue >= 1)
                 {
                     if (popupText.lifeTime < 120)
                     {
                         popupText.lifeTime = 120;
                     }
                     popupText.color = new Color(246, 138, 96);
                 }
             }
             popupText.stack += stack;
             popupText.scale = 0f;
             popupText.rotation = 0f;
             popupText.position.X = newItem.position.X + (float)newItem.width * 0.5f - vector.X * 0.5f;
             popupText.position.Y = newItem.position.Y + (float)newItem.height * 0.25f - vector.Y * 0.5f;
             popupText.velocity.Y = -7f;
             popupText.context = context;
             popupText.npcNetID = 0;
             if (popupText.coinText)
             {
                 popupText.stack = 1L;
             }
             return i;
         }
         int num2 = FindNextItemTextSlot();
         if (num2 >= 0)
         {
             string text3 = newItem.AffixName();
             if (stack > 1)
             {
                 text3 = text3 + " (" + stack + ")";
             }
             Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(text3);
             PopupText popupText2 = Main.popupText[num2];
             ResetText(popupText2);
             popupText2.active = true;
             popupText2.position.X = newItem.position.X + (float)newItem.width * 0.5f - vector2.X * 0.5f;
             popupText2.position.Y = newItem.position.Y + (float)newItem.height * 0.25f - vector2.Y * 0.5f;
             popupText2.color = Color.White;
             if (newItem.rare == 1)
             {
                 popupText2.color = new Color(150, 150, 255);
             }
             else if (newItem.rare == 2)
             {
                 popupText2.color = new Color(150, 255, 150);
             }
             else if (newItem.rare == 3)
             {
                 popupText2.color = new Color(255, 200, 150);
             }
             else if (newItem.rare == 4)
             {
                 popupText2.color = new Color(255, 150, 150);
             }
             else if (newItem.rare == 5)
             {
                 popupText2.color = new Color(255, 150, 255);
             }
             else if (newItem.rare == -13)
             {
                 popupText2.master = true;
             }
             else if (newItem.rare == -11)
             {
                 popupText2.color = new Color(255, 175, 0);
             }
             else if (newItem.rare == -1)
             {
                 popupText2.color = new Color(130, 130, 130);
             }
             else if (newItem.rare == 6)
             {
                 popupText2.color = new Color(210, 160, 255);
             }
             else if (newItem.rare == 7)
             {
                 popupText2.color = new Color(150, 255, 10);
             }
             else if (newItem.rare == 8)
             {
                 popupText2.color = new Color(255, 255, 10);
             }
             else if (newItem.rare == 9)
             {
                 popupText2.color = new Color(5, 200, 255);
             }
             else if (newItem.rare == 10)
             {
                 popupText2.color = new Color(255, 40, 100);
             }
             else if (newItem.rare >= 11)
             {
                 popupText2.color = new Color(180, 40, 255);
             }
             popupText2.expert = newItem.expert;
             popupText2.name = newItem.AffixName();
             popupText2.stack = stack;
             popupText2.velocity.Y = -7f;
             popupText2.lifeTime = 60;
             popupText2.context = context;
             if (longText)
             {
                 popupText2.lifeTime *= 5;
             }
             popupText2.coinValue = 0L;
             popupText2.coinText = newItem.type >= 71 && newItem.type <= 74;
             if (popupText2.coinText)
             {
                 long num3 = 0L;
                 if (newItem.type == 71)
                 {
                     num3 += popupText2.stack;
                 }
                 else if (newItem.type == 72)
                 {
                     num3 += 100 * popupText2.stack;
                 }
                 else if (newItem.type == 73)
                 {
                     num3 += 10000 * popupText2.stack;
                 }
                 else if (newItem.type == 74)
                 {
                     num3 += 1000000 * popupText2.stack;
                 }
                 popupText2.AddToCoinValue(num3);
                 popupText2.ValueToName();
                 popupText2.stack = 1L;
                 if (popupText2.coinValue >= 1000000)
                 {
                     if (popupText2.lifeTime < 300)
                     {
                         popupText2.lifeTime = 300;
                     }
                     popupText2.color = new Color(220, 220, 198);
                 }
                 else if (popupText2.coinValue >= 10000)
                 {
                     if (popupText2.lifeTime < 240)
                     {
                         popupText2.lifeTime = 240;
                     }
                     popupText2.color = new Color(224, 201, 92);
                 }
                 else if (popupText2.coinValue >= 100)
                 {
                     if (popupText2.lifeTime < 180)
                     {
                         popupText2.lifeTime = 180;
                     }
                     popupText2.color = new Color(181, 192, 193);
                 }
                 else if (popupText2.coinValue >= 1)
                 {
                     if (popupText2.lifeTime < 120)
                     {
                         popupText2.lifeTime = 120;
                     }
                     popupText2.color = new Color(246, 138, 96);
                 }
             }
         }
         return num2;
     }
References Entity.active, active, AddToCoinValue(), Item.AffixName(), coinText, coinValue, Color, color, context, Item.expert, expert, FindNextItemTextSlot(), Entity.height, L, lifeTime, master, FontAssets.MouseText, Item.Name, name, Main.netMode, NoStack, notActuallyAnItem, npcNetID, Main.popupText, Entity.position, position, Item.rare, ResetText(), rotation, scale, Main.showItemText, stack, Item.type, Asset< T >.Value, ValueToName(), velocity, and Entity.width.