Terraria: System.Xml.Schema.XmlSchema.DeepClone
DeepClone()
XmlSchema System.Xml.Schema.XmlSchema.DeepClone () inline package
Definition at line 599 of file XmlSchema.cs.
    {
        XmlSchema xmlSchema = new XmlSchema();
        xmlSchema._attributeFormDefault = _attributeFormDefault;
        xmlSchema._elementFormDefault = _elementFormDefault;
        xmlSchema._blockDefault = _blockDefault;
        xmlSchema._finalDefault = _finalDefault;
        xmlSchema._targetNs = _targetNs;
        xmlSchema._version = _version;
        xmlSchema._isPreprocessed = _isPreprocessed;
        for (int i = 0; i < _items.Count; i++)
        {
            XmlSchemaObject item = ((_items[i] is XmlSchemaComplexType xmlSchemaComplexType) ? xmlSchemaComplexType.Clone(this) : ((_items[i] is XmlSchemaElement xmlSchemaElement) ? xmlSchemaElement.Clone(this) : ((!(_items[i] is XmlSchemaGroup xmlSchemaGroup)) ? _items[i].Clone() : xmlSchemaGroup.Clone(this))));
            xmlSchema.Items.Add(item);
        }
        for (int j = 0; j < _includes.Count; j++)
        {
            XmlSchemaExternal item2 = (XmlSchemaExternal)_includes[j].Clone();
            xmlSchema.Includes.Add(item2);
        }
        xmlSchema.Namespaces = base.Namespaces;
        xmlSchema.BaseUri = BaseUri;
        return xmlSchema;
    }
References System.Xml.Schema.XmlSchema._attributeFormDefault, System.Xml.Schema.XmlSchema._blockDefault, System.Xml.Schema.XmlSchema._elementFormDefault, System.Xml.Schema.XmlSchema._finalDefault, System.Xml.Schema.XmlSchema._includes, System.Xml.Schema.XmlSchema._isPreprocessed, System.Xml.Schema.XmlSchema._items, System.Xml.Schema.XmlSchema._targetNs, System.Xml.Schema.XmlSchema._version, System.Xml.Schema.XmlSchemaObjectCollection.Add(), System.Xml.Schema.XmlSchema.BaseUri, System.Xml.Schema.XmlSchema.Clone(), System.Xml.Schema.XmlSchemaObjectCollection.Clone(), System.Collections.CollectionBase.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchema.Includes, and System.item.