Terraria: System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForTypeV2
GetMetadataLengthForTypeV2()
static bool System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForTypeV2 (TraceLoggingTypeInfo typeInfo, out uint size) inline static private
Definition at line 330 of file EventParameterInfo.cs.
    {
        size = 0u;
        if (typeInfo == null)
        {
            return false;
        }
        if (typeInfo is InvokeTypeInfo invokeTypeInfo)
        {
            size += 8u;
            PropertyAnalysis[] properties = invokeTypeInfo.properties;
            if (properties != null)
            {
                PropertyAnalysis[] array = properties;
                foreach (PropertyAnalysis propertyAnalysis in array)
                {
                    if (!GetMetadataLengthForNamedTypeV2(propertyAnalysis.name, propertyAnalysis.typeInfo, out var size2))
                    {
                        return false;
                    }
                    size += size2;
                }
            }
        }
        else if (typeInfo is EnumerableTypeInfo enumerableTypeInfo)
        {
            size += 4u;
            if (!GetMetadataLengthForTypeV2(enumerableTypeInfo.ElementInfo, out var size3))
            {
                return false;
            }
            size += size3;
        }
        else if (typeInfo is ScalarArrayTypeInfo scalarArrayTypeInfo)
        {
            if (!scalarArrayTypeInfo.DataType.HasElementType || !GetTypeInfoFromType(scalarArrayTypeInfo.DataType.GetElementType(), out var typeInfo2))
            {
                return false;
            }
            size += 4u;
            if (!GetMetadataLengthForTypeV2(typeInfo2, out var size4))
            {
                return false;
            }
            size += size4;
        }
        else
        {
            size += 4u;
        }
        return true;
    }
References System.array, System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForNamedTypeV2(), System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForTypeV2(), System.Diagnostics.Tracing.EventParameterInfo.GetTypeInfoFromType(), System.Diagnostics.Tracing.PropertyAnalysis.name, and System.Diagnostics.Tracing.PropertyAnalysis.typeInfo.
Referenced by System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForNamedTypeV2(), and System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForTypeV2().