Terraria: System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadata
GenerateMetadata()
unsafe bool System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadata (byte * pMetadataBlob, ref uint offset, uint blobSize) inline package
Definition at line 18 of file EventParameterInfo.cs.
    {
        TypeCode typeCodeExtended = GetTypeCodeExtended(ParameterType);
        if (typeCodeExtended == TypeCode.Object)
        {
            EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, 1u);
            if (!(TypeInfo is InvokeTypeInfo { properties: var properties }))
            {
                return false;
            }
            if (properties != null)
            {
                EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, (uint)properties.Length);
                PropertyAnalysis[] array = properties;
                foreach (PropertyAnalysis property in array)
                {
                    if (!GenerateMetadataForProperty(property, pMetadataBlob, ref offset, blobSize))
                    {
                        return false;
                    }
                }
            }
            else
            {
                EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, 0u);
            }
            EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, '\0');
        }
        else
        {
            EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, (uint)typeCodeExtended);
            fixed (char* src = ParameterName)
            {
                EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, (byte*)src, (uint)((ParameterName.Length + 1) * 2));
            }
        }
        return true;
    }
References System.array, System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadataForProperty(), System.Diagnostics.Tracing.EventParameterInfo.GetTypeCodeExtended(), System.offset, System.Diagnostics.Tracing.EventParameterInfo.ParameterName, System.Diagnostics.Tracing.EventParameterInfo.ParameterType, System.Diagnostics.Tracing.EventParameterInfo.TypeInfo, and System.Diagnostics.Tracing.EventPipeMetadataGenerator.WriteToBuffer().
Referenced by System.Diagnostics.Tracing.EventPipeMetadataGenerator.GenerateMetadata().