Terraria: System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForProperty
GetMetadataLengthForProperty()
static uint System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForProperty (PropertyAnalysis property) inline static private
Definition at line 286 of file EventParameterInfo.cs.
    {
        uint num = 0u;
        if (property.typeInfo is InvokeTypeInfo invokeTypeInfo)
        {
            num += 8;
            PropertyAnalysis[] properties = invokeTypeInfo.properties;
            if (properties != null)
            {
                PropertyAnalysis[] array = properties;
                foreach (PropertyAnalysis property2 in array)
                {
                    num += GetMetadataLengthForProperty(property2);
                }
            }
            return num + (uint)((property.name.Length + 1) * 2);
        }
        return num + (uint)(4 + (property.name.Length + 1) * 2);
    }
References System.array, System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForProperty(), System.Diagnostics.Tracing.PropertyAnalysis.name, and System.Diagnostics.Tracing.PropertyAnalysis.typeInfo.
Referenced by System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLength(), and System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForProperty().