Terraria: System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForNamedTypeV2
GetMetadataLengthForNamedTypeV2()
static bool System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForNamedTypeV2 (string name, TraceLoggingTypeInfo typeInfo, out uint size) inline static private
Definition at line 383 of file EventParameterInfo.cs.
    {
        size = (uint)(4 + (name.Length + 1) * 2);
        if (!GetMetadataLengthForTypeV2(typeInfo, out var size2))
        {
            return false;
        }
        size += size2;
        return true;
    }
References System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForTypeV2().
Referenced by System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadataForNamedTypeV2(), System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForTypeV2(), and System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthV2().