Terraria: System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadataForTypeV2
GenerateMetadataForTypeV2()
static unsafe bool System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadataForTypeV2 (TraceLoggingTypeInfo typeInfo, byte * pMetadataBlob, ref uint offset, uint blobSize) inline static private
Definition at line 123 of file EventParameterInfo.cs.
    {
        if (typeInfo is InvokeTypeInfo invokeTypeInfo)
        {
            EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, 1u);
            PropertyAnalysis[] properties = invokeTypeInfo.properties;
            if (properties != null)
            {
                EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, (uint)properties.Length);
                PropertyAnalysis[] array = properties;
                foreach (PropertyAnalysis propertyAnalysis in array)
                {
                    if (!GenerateMetadataForNamedTypeV2(propertyAnalysis.name, propertyAnalysis.typeInfo, pMetadataBlob, ref offset, blobSize))
                    {
                        return false;
                    }
                }
            }
            else
            {
                EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, 0u);
            }
        }
        else if (typeInfo is EnumerableTypeInfo enumerableTypeInfo)
        {
            EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, 19);
            GenerateMetadataForTypeV2(enumerableTypeInfo.ElementInfo, pMetadataBlob, ref offset, blobSize);
        }
        else if (typeInfo is ScalarArrayTypeInfo scalarArrayTypeInfo)
        {
            if (!scalarArrayTypeInfo.DataType.HasElementType)
            {
                return false;
            }
            if (!GetTypeInfoFromType(scalarArrayTypeInfo.DataType.GetElementType(), out var typeInfo2))
            {
                return false;
            }
            EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, 19);
            GenerateMetadataForTypeV2(typeInfo2, pMetadataBlob, ref offset, blobSize);
        }
        else
        {
            TypeCode typeCodeExtended = GetTypeCodeExtended(typeInfo.DataType);
            if (typeCodeExtended == TypeCode.Object)
            {
                return false;
            }
            EventPipeMetadataGenerator.WriteToBuffer(pMetadataBlob, blobSize, ref offset, (uint)typeCodeExtended);
        }
        return true;
    }
References System.array, System.Diagnostics.Tracing.TraceLoggingTypeInfo.DataType, System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadataForNamedTypeV2(), System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadataForTypeV2(), System.Diagnostics.Tracing.EventParameterInfo.GetTypeCodeExtended(), System.Diagnostics.Tracing.EventParameterInfo.GetTypeInfoFromType(), System.Diagnostics.Tracing.PropertyAnalysis.name, System.offset, System.Diagnostics.Tracing.PropertyAnalysis.typeInfo, and System.Diagnostics.Tracing.EventPipeMetadataGenerator.WriteToBuffer().
Referenced by System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadataForNamedTypeV2(), and System.Diagnostics.Tracing.EventParameterInfo.GenerateMetadataForTypeV2().