Terraria: System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLength
GetMetadataLength()
bool System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLength (out uint size) inline package
Definition at line 257 of file EventParameterInfo.cs.
    {
        size = 0u;
        TypeCode typeCodeExtended = GetTypeCodeExtended(ParameterType);
        if (typeCodeExtended == TypeCode.Object)
        {
            if (!(TypeInfo is InvokeTypeInfo invokeTypeInfo))
            {
                return false;
            }
            size += 8u;
            PropertyAnalysis[] properties = invokeTypeInfo.properties;
            if (properties != null)
            {
                PropertyAnalysis[] array = properties;
                foreach (PropertyAnalysis property in array)
                {
                    size += GetMetadataLengthForProperty(property);
                }
            }
            size += 2u;
        }
        else
        {
            size += (uint)(4 + (ParameterName.Length + 1) * 2);
        }
        return true;
    }
References System.array, System.Diagnostics.Tracing.EventParameterInfo.GetMetadataLengthForProperty(), System.Diagnostics.Tracing.EventParameterInfo.GetTypeCodeExtended(), System.Diagnostics.Tracing.EventParameterInfo.ParameterName, System.Diagnostics.Tracing.EventParameterInfo.ParameterType, and System.Diagnostics.Tracing.EventParameterInfo.TypeInfo.
Referenced by System.Diagnostics.Tracing.EventPipeMetadataGenerator.GenerateMetadata().