Terraria: UIScrollbar.GetHandleRectangle
GetHandleRectangle()
Rectangle UIScrollbar.GetHandleRectangle () inline private
     {
         CalculatedStyle innerDimensions = GetInnerDimensions();
         if (_maxViewSize == 0f && _viewSize == 0f)
         {
             _viewSize = 1f;
             _maxViewSize = 1f;
         }
         return new Rectangle((int)innerDimensions.X, (int)(innerDimensions.Y + innerDimensions.Height * (_viewPosition / _maxViewSize)) - 3, 20, (int)(innerDimensions.Height * (_viewSize / _maxViewSize)) + 7);
     }
References _maxViewSize, _viewPosition, _viewSize, UIElement.GetInnerDimensions(), CalculatedStyle.Height, CalculatedStyle.X, and CalculatedStyle.Y.
Referenced by DrawSelf(), and LeftMouseDown().