Terraria: Microsoft.Xna.Framework.Graphics.EffectPass.SyncEffectState
SyncEffectState()
void Microsoft.Xna.Framework.Graphics.EffectPass.SyncEffectState () inline private
Definition at line 141 of file EffectPass.cs.
    {
        GraphicsDevice graphicsDevice = _technique._parent.GraphicsDevice;
        if (graphicsDevice == null)
        {
            throw new ArgumentNullException("graphicsDevice", FrameworkResources.DeviceCannotBeNullOnResourceCreate);
        }
        if ((_stateFlags & EffectStateFlags.Blend) != 0)
        {
            graphicsDevice.ClearBlendState();
        }
        if ((_stateFlags & EffectStateFlags.DepthStencil) != 0)
        {
            graphicsDevice.ClearDepthStencilState();
        }
        if ((_stateFlags & EffectStateFlags.Rasterizer) != 0)
        {
            graphicsDevice.ClearRasterizerState();
        }
        if ((_stateFlags & EffectStateFlags.AllSamplers) != 0)
        {
            int num = 0;
            do
            {
                if (((uint)_stateFlags & (uint)(8 << num)) != 0)
                {
                    graphicsDevice.SamplerStates.ClearState(num);
                }
                num++;
            }
            while (num < 16);
        }
        if ((_stateFlags & EffectStateFlags.AllVertexSamplers) == 0)
        {
            return;
        }
        int num2 = 0;
        do
        {
            if (((uint)_stateFlags & (uint)(524288 << num2)) != 0)
            {
                graphicsDevice.VertexSamplerStates.ClearState(num2);
            }
            num2++;
        }
        while (num2 < 4);
    }
References Microsoft.Xna.Framework.Graphics.EffectTechnique._parent, Microsoft.Xna.Framework.Graphics.EffectPass._stateFlags, Microsoft.Xna.Framework.Graphics.EffectPass._technique, Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearBlendState(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearDepthStencilState(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.ClearRasterizerState(), Microsoft.Xna.Framework.Graphics.SamplerStateCollection.ClearState(), Microsoft.Xna.Framework.FrameworkResources.DeviceCannotBeNullOnResourceCreate, Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsDevice, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VertexSamplerStates.
Referenced by Microsoft.Xna.Framework.Graphics.EffectPass.Apply().