Terraria: System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments
VisitArguments()
static Expression[] System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments (ExpressionVisitor visitor, IArgumentProvider nodes) inline static
Definition at line 57 of file ExpressionVisitorUtils.cs.
    {
        Expression[] array = null;
        int i = 0;
        for (int argumentCount = nodes.ArgumentCount; i < argumentCount; i++)
        {
            Expression argument = nodes.GetArgument(i);
            Expression expression = visitor.Visit(argument);
            if (array != null)
            {
                array[i] = expression;
            }
            else if (expression != argument)
            {
                array = new Expression[argumentCount];
                for (int j = 0; j < i; j++)
                {
                    array[j] = nodes.GetArgument(j);
                }
                array[i] = expression;
            }
        }
        return array;
    }
References System.Linq.Expressions.IArgumentProvider.ArgumentCount, System.array, System.Linq.Expressions.IArgumentProvider.GetArgument(), and System.Linq.Expressions.ExpressionVisitor.Visit().
Referenced by System.Linq.Expressions.ExpressionVisitor.VisitArguments(), and System.Linq.Expressions.DynamicExpressionVisitor.VisitDynamic().