Terraria: InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea
DrawInNotificationsArea()
void InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea (SpriteBatch spriteBatch, Rectangle area, ref int gamepadPointLocalIndexTouse) inline
Implements IInGameNotification.
         {
             string userWrapperText = _request.GetUserWrapperText();
             string text = _request.UserDisplayName;
             Utils.TrimTextIfNeeded(ref text, FontAssets.MouseText.Value, 0.9f, area.Width / 4);
             string text2 = Utils.FormatWith(userWrapperText, new
             {
                 DisplayName = text,
                 FullId = _request.UserFullIdentifier
             });
             Vector2 mouseScreen = Main.MouseScreen;
             Color c = (area.Contains(mouseScreen.ToPoint()) ? (new Color(64, 109, 164) * 0.75f) : (new Color(64, 109, 164) * 0.5f));
             Utils.DrawInvBG(spriteBatch, area, c);
             Vector2 pos = new Vector2(area.Left, area.Center.Y);
             pos.X += 32f;
             Texture2D value = Main.Assets.Request<Texture2D>("Images/UI/ButtonPlay", (AssetRequestMode)1).Value;
             Vector2 vector = new Vector2(area.Left + 7, MathHelper.Lerp(area.Top, area.Bottom, 0.5f) - (float)(value.Height / 2) - 1f);
             bool flag = Utils.CenteredRectangle(vector + new Vector2(value.Width / 2, 0f), value.Size()).Contains(mouseScreen.ToPoint());
             spriteBatch.Draw(value, vector, null, Color.White * (flag ? 1f : 0.5f), 0f, new Vector2(0f, 0.5f) * value.Size(), 1f, SpriteEffects.None, 0f);
             if (flag)
             {
                 OnMouseOver();
             }
             value = Main.Assets.Request<Texture2D>("Images/UI/ButtonDelete", (AssetRequestMode)1).Value;
             vector = new Vector2(area.Left + 7, MathHelper.Lerp(area.Top, area.Bottom, 0.5f) + (float)(value.Height / 2) + 1f);
             flag = Utils.CenteredRectangle(vector + new Vector2(value.Width / 2, 0f), value.Size()).Contains(mouseScreen.ToPoint());
             spriteBatch.Draw(value, vector, null, Color.White * (flag ? 1f : 0.5f), 0f, new Vector2(0f, 0.5f) * value.Size(), 1f, SpriteEffects.None, 0f);
             if (flag)
             {
                 OnMouseOver(reject: true);
             }
             pos.X += 6f;
             Utils.DrawBorderString(color: new Color(Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor / 5, Main.mouseTextColor), sb: spriteBatch, text: text2, pos: pos, scale: 0.9f, anchorx: 0f, anchory: 0.4f);
         }
References InGamePopups.PlayerWantsToJoinGamePopup._request, Main.Assets, Utils.CenteredRectangle(), Color, Utils.DrawBorderString(), Utils.DrawInvBG(), Utils.FormatWith(), UserJoinToServerRequest.GetUserWrapperText(), Main.MouseScreen, FontAssets.MouseText, Main.mouseTextColor, InGamePopups.PlayerWantsToJoinGamePopup.OnMouseOver(), Utils.TrimTextIfNeeded(), UserJoinToServerRequest.UserDisplayName, UserJoinToServerRequest.UserFullIdentifier, and Asset< T >.Value.