Terraria: InGamePopups.PlayerWantsToJoinGamePopup.OnMouseOver
OnMouseOver()
void InGamePopups.PlayerWantsToJoinGamePopup.OnMouseOver (bool reject = false) inline private
         {
             if (PlayerInput.IgnoreMouseInterface)
             {
                 return;
             }
             Main.player[Main.myPlayer].mouseInterface = true;
             if (Main.mouseLeft && Main.mouseLeftRelease)
             {
                 Main.mouseLeftRelease = false;
                 _timeLeft = 0;
                 if (reject)
                 {
                     _request.Reject();
                 }
                 else
                 {
                     _request.Accept();
                 }
             }
         }
References InGamePopups.PlayerWantsToJoinGamePopup._request, InGamePopups.PlayerWantsToJoinGamePopup._timeLeft, UserJoinToServerRequest.Accept(), PlayerInput.IgnoreMouseInterface, Player.mouseInterface, Main.mouseLeft, Main.mouseLeftRelease, Main.myPlayer, Main.player, and UserJoinToServerRequest.Reject().
Referenced by InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), and InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea().