Terraria: System.Linq.Expressions.Expression.ValidateNewArgs
ValidateNewArgs()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateNewArgs (ConstructorInfo constructor, ref ReadOnlyCollection< Expression< TDelegate > > arguments, ref ReadOnlyCollection< MemberInfo > members) inline static private inherited
Definition at line 4527 of file Expression.cs.
    {
        ParameterInfo[] parametersCached;
        if ((parametersCached = constructor.GetParametersCached()).Length != 0)
        {
            if (arguments.Count != parametersCached.Length)
            {
                throw Error.IncorrectNumberOfConstructorArguments();
            }
            if (arguments.Count != members.Count)
            {
                throw Error.IncorrectNumberOfArgumentsForMembers();
            }
            Expression[] array = null;
            MemberInfo[] array2 = null;
            int i = 0;
            for (int count = arguments.Count; i < count; i++)
            {
                Expression argument = arguments[i];
                ExpressionUtils.RequiresCanRead(argument, "arguments", i);
                MemberInfo member = members[i];
                ContractUtils.RequiresNotNull(member, "members", i);
                if (!TypeUtils.AreEquivalent(member.DeclaringType, constructor.DeclaringType))
                {
                    throw Error.ArgumentMemberNotDeclOnType(member.Name, constructor.DeclaringType.Name, "members", i);
                }
                ValidateAnonymousTypeMember(ref member, out var memberType, "members", i);
                if (!TypeUtils.AreReferenceAssignable(memberType, argument.Type) && !TryQuote(memberType, ref argument))
                {
                    throw Error.ArgumentTypeDoesNotMatchMember(argument.Type, memberType, "arguments", i);
                }
                ParameterInfo parameterInfo = parametersCached[i];
                Type type = parameterInfo.ParameterType;
                if (type.IsByRef)
                {
                    type = type.GetElementType();
                }
                if (!TypeUtils.AreReferenceAssignable(type, argument.Type) && !TryQuote(type, ref argument))
                {
                    throw Error.ExpressionTypeDoesNotMatchConstructorParameter(argument.Type, type, "arguments", i);
                }
                if (array == null && argument != arguments[i])
                {
                    array = new Expression[arguments.Count];
                    for (int j = 0; j < i; j++)
                    {
                        array[j] = arguments[j];
                    }
                }
                if (array != null)
                {
                    array[i] = argument;
                }
                if (array2 == null && member != members[i])
                {
                    array2 = new MemberInfo[members.Count];
                    for (int k = 0; k < i; k++)
                    {
                        array2[k] = members[k];
                    }
                }
                if (array2 != null)
                {
                    array2[i] = member;
                }
            }
            if (array != null)
            {
                arguments = new TrueReadOnlyCollection<Expression>(array);
            }
            if (array2 != null)
            {
                members = new TrueReadOnlyCollection<MemberInfo>(array2);
            }
        }
        else
        {
            if (arguments != null && arguments.Count > 0)
            {
                throw Error.IncorrectNumberOfConstructorArguments();
            }
            if (members != null && members.Count > 0)
            {
                throw Error.IncorrectNumberOfMembersForGivenConstructor();
            }
        }
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Error.ArgumentMemberNotDeclOnType(), System.Linq.Expressions.Error.ArgumentTypeDoesNotMatchMember(), System.array, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.MemberInfo.DeclaringType, System.Linq.Expressions.Error.ExpressionTypeDoesNotMatchConstructorParameter(), System.Linq.Expressions.Error.IncorrectNumberOfArgumentsForMembers(), System.Linq.Expressions.Error.IncorrectNumberOfConstructorArguments(), System.Linq.Expressions.Error.IncorrectNumberOfMembersForGivenConstructor(), System.Reflection.MemberInfo.Name, System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Expression< TDelegate >.TryQuote(), System.type, and System.Linq.Expressions.Expression< TDelegate >.ValidateAnonymousTypeMember().
Referenced by System.Linq.Expressions.Expression< TDelegate >.New().