Terraria: System.Linq.Expressions.Expression.MakeMemberAccess
MakeMemberAccess()
static MemberExpression System.Linq.Expressions.Expression< TDelegate >.MakeMemberAccess (Expression< TDelegate >? expression, MemberInfo member) inline static inherited
Definition at line 3851 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(member, "member");
        if (member is FieldInfo field)
        {
            return Field(expression, field);
        }
        if (member is PropertyInfo property)
        {
            return Property(expression, property);
        }
        throw Error.MemberNotFieldOrProperty(member, "member");
    }
References System.Field, System.Linq.Expressions.Error.MemberNotFieldOrProperty(), System.Property, and System.Dynamic.Utils.ContractUtils.RequiresNotNull().
Referenced by System.Linq.Expressions.BinaryExpression.ReduceMember(), System.Linq.Expressions.UnaryExpression.ReduceMember(), System.Linq.Expressions.MemberInitExpression.ReduceMemberBinding(), and System.Linq.Expressions.MemberExpression.Update().