Terraria: System.Linq.Expressions.Expression.ValidateSettableFieldOrPropertyMember
ValidateSettableFieldOrPropertyMember()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateSettableFieldOrPropertyMember (MemberInfo member, out Type memberType) inline static private inherited
Definition at line 3632 of file Expression.cs.
    {
        Type declaringType = member.DeclaringType;
        if (declaringType == null)
        {
            throw Error.NotAMemberOfAnyType(member, "member");
        }
        TypeUtils.ValidateType(declaringType, null);
        if (!(member is PropertyInfo propertyInfo))
        {
            if (!(member is FieldInfo fieldInfo))
            {
                throw Error.ArgumentMustBeFieldInfoOrPropertyInfo("member");
            }
            memberType = fieldInfo.FieldType;
        }
        else
        {
            if (!propertyInfo.CanWrite)
            {
                throw Error.PropertyDoesNotHaveSetter(propertyInfo, "member");
            }
            memberType = propertyInfo.PropertyType;
        }
    }
References System.Linq.Expressions.Error.ArgumentMustBeFieldInfoOrPropertyInfo(), System.Reflection.MemberInfo.DeclaringType, System.Linq.Expressions.Error.NotAMemberOfAnyType(), System.Linq.Expressions.Error.PropertyDoesNotHaveSetter(), and System.Dynamic.Utils.TypeUtils.ValidateType().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Bind().