Terraria: System.Linq.Expressions.Expression.IsCompatible
IsCompatible() [1/2]
static bool System.Linq.Expressions.Expression< TDelegate >.IsCompatible (MethodBase m, Expression< TDelegate >[] arguments) inline static private inherited
Definition at line 4310 of file Expression.cs.
    {
        ParameterInfo[] parametersCached = m.GetParametersCached();
        if (parametersCached.Length != arguments.Length)
        {
            return false;
        }
        for (int i = 0; i < arguments.Length; i++)
        {
            Expression expression = arguments[i];
            ContractUtils.RequiresNotNull(expression, "arguments");
            Type type = expression.Type;
            Type type2 = parametersCached[i].ParameterType;
            if (type2.IsByRef)
            {
                type2 = type2.GetElementType();
            }
            if (!TypeUtils.AreReferenceAssignable(type2, type) && (!TypeUtils.IsSameOrSubclass(typeof(LambdaExpression), type2) || !type2.IsAssignableFrom(expression.GetType())))
            {
                return false;
            }
        }
        return true;
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Dynamic.Utils.TypeUtils.IsSameOrSubclass(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), and System.type.