Terraria: System.Linq.Expressions.Expression.GetFuncType
GetFuncType()
static Type System.Linq.Expressions.Expression< TDelegate >.GetFuncType (params Type?[] typeArgs) inline static inherited
Definition at line 3466 of file Expression.cs.
    {
        switch (ValidateTryGetFuncActionArgs(typeArgs))
        {
        case TryGetFuncActionArgsResult.ArgumentNull:
            throw new ArgumentNullException("typeArgs");
        case TryGetFuncActionArgsResult.ByRef:
            throw Error.TypeMustNotBeByRef("typeArgs");
        default:
        {
            Type funcType = System.Linq.Expressions.Compiler.DelegateHelpers.GetFuncType(typeArgs);
            if (funcType == null)
            {
                throw Error.IncorrectNumberOfTypeArgsForFunc("typeArgs");
            }
            return funcType;
        }
        }
    }
References System.Linq.Expressions.Compiler.DelegateHelpers.GetFuncType(), System.Linq.Expressions.Error.IncorrectNumberOfTypeArgsForFunc(), System.Linq.Expressions.Error.TypeMustNotBeByRef(), and System.Linq.Expressions.Expression< TDelegate >.ValidateTryGetFuncActionArgs().