Terraria: System.Linq.Expressions.Expression.ValidateListInitArgs
ValidateListInitArgs()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateListInitArgs (Type listType, ReadOnlyCollection< ElementInit > initializers, string listTypeParamName) inline static private inherited
Definition at line 3908 of file Expression.cs.
    {
        if (!typeof(IEnumerable).IsAssignableFrom(listType))
        {
            throw Error.TypeNotIEnumerable(listType, listTypeParamName);
        }
        int i = 0;
        for (int count = initializers.Count; i < count; i++)
        {
            ElementInit elementInit = initializers[i];
            ContractUtils.RequiresNotNull(elementInit, "initializers", i);
            ValidateCallInstanceType(listType, elementInit.AddMethod);
        }
    }
References System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Error.TypeNotIEnumerable(), and System.Linq.Expressions.Expression< TDelegate >.ValidateCallInstanceType().
Referenced by System.Linq.Expressions.Expression< TDelegate >.ListBind(), and System.Linq.Expressions.Expression< TDelegate >.ListInit().