Terraria: System.Linq.Expressions.Expression.Block
Block() [1/12]
static BlockExpression System.Linq.Expressions.Expression< TDelegate >.Block (Expression< TDelegate > arg0, Expression< TDelegate > arg1) inline static inherited
Definition at line 2099 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(arg0, "arg0");
        ExpressionUtils.RequiresCanRead(arg1, "arg1");
        return new Block2(arg0, arg1);
    }
References System.Dynamic.Utils.ExpressionUtils.RequiresCanRead().
Referenced by System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer(), System.Linq.Expressions.Compiler.StackSpiller.MemberMemberBindingRewriter.AsExpression(), System.Linq.Expressions.Compiler.StackSpiller.ListBindingRewriter.AsExpression(), System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember(), System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Linq.Expressions.TypeBinaryExpression.ByValParameterTypeEqual(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodReturnLast< TBinder >(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomNoMatchDelegate(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Dynamic.BindingRestrictions.InstanceRestriction.GetExpression(), System.Linq.Expressions.BinaryExpression.ReduceIndex(), System.Linq.Expressions.UnaryExpression.ReduceIndex(), System.Linq.Expressions.MemberInitExpression.ReduceListInit(), System.Linq.Expressions.BinaryExpression.ReduceMember(), System.Linq.Expressions.UnaryExpression.ReduceMember(), System.Linq.Expressions.MemberInitExpression.ReduceMemberInit(), System.Linq.Expressions.TypeBinaryExpression.ReduceTypeEqual(), System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted(), System.Linq.Expressions.UnaryExpression.ReduceVariable(), System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign(), System.Linq.Expressions.Compiler.StackSpiller.Rewrite< T >(), System.Runtime.CompilerServices.CallSiteBinder.Stitch< T >(), System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch(), System.Linq.Expressions.BlockExpression.Update(), and System.Linq.EnumerableRewriter.VisitBlock().