Terraria: System.Linq.Expressions.Expression.LeftShift
LeftShift() [2/2]
static BinaryExpression System.Linq.Expressions.Expression< TDelegate >.LeftShift (Expression< TDelegate > left, Expression< TDelegate > right, MethodInfo? method) inline static inherited
Definition at line 1770 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(left, "left");
        ExpressionUtils.RequiresCanRead(right, "right");
        if (method == null)
        {
            if (IsSimpleShift(left.Type, right.Type))
            {
                Type resultTypeOfShift = GetResultTypeOfShift(left.Type, right.Type);
                return new SimpleBinaryExpression(ExpressionType.LeftShift, left, right, resultTypeOfShift);
            }
            return GetUserDefinedBinaryOperatorOrThrow(ExpressionType.LeftShift, "op_LeftShift", left, right, liftToNull: true);
        }
        return GetMethodBasedBinaryOperator(ExpressionType.LeftShift, left, right, method, liftToNull: true);
    }
References System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedBinaryOperator(), System.Linq.Expressions.Expression< TDelegate >.GetResultTypeOfShift(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperatorOrThrow(), System.Linq.Expressions.Expression< TDelegate >.IsSimpleShift(), and System.Dynamic.Utils.ExpressionUtils.RequiresCanRead().