Terraria: System.Linq.Expressions.Expression.ValidateArgumentCount
ValidateArgumentCount()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateArgumentCount (MethodBase method, ExpressionType nodeKind, int count, ParameterInfo[] pis) inline static private inherited
Definition at line 4254 of file Expression.cs.
    {
        ExpressionUtils.ValidateArgumentCount(method, nodeKind, count, pis);
    }
References System.Linq.count, and System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), and System.Linq.Expressions.Expression< TDelegate >.Invoke().