Terraria: System.Linq.Expressions.Expression.New
New() [1/6]
static NewExpression System.Linq.Expressions.Expression< TDelegate >.New ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)] Type type) inline static inherited
Definition at line 4506 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(type, "type");
        if (type == typeof(void))
        {
            throw Error.ArgumentCannotBeOfTypeVoid("type");
        }
        TypeUtils.ValidateType(type, "type");
        ConstructorInfo constructorInfo = type.GetConstructors(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic).SingleOrDefault((ConstructorInfo c) => c.GetParametersCached().Length == 0);
        if (constructorInfo != null)
        {
            return New(constructorInfo);
        }
        if (!type.IsValueType)
        {
            throw Error.TypeMissingDefaultConstructor(type, "type");
        }
        return new NewValueTypeExpression(type, EmptyReadOnlyCollection<Expression>.Instance, null);
    }
References System.Linq.Expressions.Error.ArgumentCannotBeOfTypeVoid(), System.Reflection.Instance, System.Linq.Expressions.New, System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.type, System.Linq.Expressions.Error.TypeMissingDefaultConstructor(), and System.Dynamic.Utils.TypeUtils.ValidateType().