Terraria: System.Linq.Expressions.Expression.MakeOpAssignUnary
MakeOpAssignUnary()
static UnaryExpression System.Linq.Expressions.Expression< TDelegate >.MakeOpAssignUnary (ExpressionType kind, Expression< TDelegate > expression, MethodInfo method) inline static private inherited
Definition at line 5458 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(expression, "expression");
        RequiresCanWrite(expression, "expression");
        UnaryExpression unaryExpression;
        if (method == null)
        {
            if (expression.Type.IsArithmetic())
            {
                return new UnaryExpression(kind, expression, expression.Type, null);
            }
            string name = ((kind != ExpressionType.PreIncrementAssign && kind != ExpressionType.PostIncrementAssign) ? "op_Decrement" : "op_Increment");
            unaryExpression = GetUserDefinedUnaryOperatorOrThrow(kind, name, expression);
        }
        else
        {
            unaryExpression = GetMethodBasedUnaryOperator(kind, expression, method);
        }
        if (!TypeUtils.AreReferenceAssignable(expression.Type, unaryExpression.Type))
        {
            throw Error.UserDefinedOpMustHaveValidReturnType(kind, method.Name);
        }
        return unaryExpression;
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedUnaryOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedUnaryOperatorOrThrow(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Linq.Expressions.Expression< TDelegate >.RequiresCanWrite(), and System.Linq.Expressions.Error.UserDefinedOpMustHaveValidReturnType().
Referenced by System.Linq.Expressions.Expression< TDelegate >.PostDecrementAssign(), System.Linq.Expressions.Expression< TDelegate >.PostDecrementAssign(), System.Linq.Expressions.Expression< TDelegate >.PostIncrementAssign(), System.Linq.Expressions.Expression< TDelegate >.PostIncrementAssign(), System.Linq.Expressions.Expression< TDelegate >.PreDecrementAssign(), System.Linq.Expressions.Expression< TDelegate >.PreDecrementAssign(), System.Linq.Expressions.Expression< TDelegate >.PreIncrementAssign(), and System.Linq.Expressions.Expression< TDelegate >.PreIncrementAssign().