Terraria: System.Linq.Expressions.Expression.Condition
Condition() [1/2]
static ConditionalExpression System.Linq.Expressions.Expression< TDelegate >.Condition (Expression< TDelegate > test, Expression< TDelegate > ifTrue, Expression< TDelegate > ifFalse) inline static inherited
Definition at line 2325 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(test, "test");
        ExpressionUtils.RequiresCanRead(ifTrue, "ifTrue");
        ExpressionUtils.RequiresCanRead(ifFalse, "ifFalse");
        if (test.Type != typeof(bool))
        {
            throw Error.ArgumentMustBeBoolean("test");
        }
        if (!TypeUtils.AreEquivalent(ifTrue.Type, ifFalse.Type))
        {
            throw Error.ArgumentTypesMustMatch();
        }
        return ConditionalExpression.Make(test, ifTrue, ifFalse, ifTrue.Type);
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Linq.Expressions.Error.ArgumentMustBeBoolean(), System.Linq.Expressions.Error.ArgumentTypesMustMatch(), System.Linq.Expressions.ConditionalExpression.Make(), and System.Dynamic.Utils.ExpressionUtils.RequiresCanRead().
Referenced by System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer(), System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember(), System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodReturnLast< TBinder >(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), System.Linq.Expressions.Expression< TDelegate >.IfThen(), System.Linq.Expressions.Expression< TDelegate >.IfThenElse(), System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted(), System.Runtime.CompilerServices.CallSiteBinder.Stitch< T >(), System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch(), System.Linq.Expressions.ConditionalExpression.Update(), and System.Linq.EnumerableRewriter.VisitConditional().