Terraria: System.Linq.Expressions.Expression.Lambda
Lambda() [4/12]
static LambdaExpression System.Linq.Expressions.Expression< TDelegate >.Lambda (Expression< TDelegate > body, params ParameterExpression< TDelegate >?[] parameters) inline static inherited
Definition at line 3297 of file Expression.cs.
    {
        return Lambda(body, tailCall: false, (IEnumerable<ParameterExpression>?)parameters);
    }
References System.Linq.Expressions.Lambda.
Referenced by System.Runtime.CompilerServices.CallSite< T >.CreateCustomNoMatchDelegate(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Linq.EnumerableExecutor< T >.Execute(), System.Linq.EnumerableQuery< T >.GetEnumerator(), System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType< TObj, TParam >(), System.Linq.Expressions.Expression< TDelegate >.Lambda< TDelegate >(), System.Linq.Expressions.Expression< TDelegate >.Lambda< TDelegate >(), System.Linq.Expressions.Expression0< TDelegate >.Rewrite(), System.Linq.Expressions.Expression1< TDelegate >.Rewrite(), System.Linq.Expressions.Expression2< TDelegate >.Rewrite(), System.Linq.Expressions.Expression3< TDelegate >.Rewrite(), System.Linq.Expressions.ExpressionN< TDelegate >.Rewrite(), System.Runtime.CompilerServices.CallSiteBinder.Stitch< T >(), and System.Linq.Expressions.Expression< TDelegate >.Update().