Terraria: System.Linq.Expressions.Expression.GetOptimizedBlockExpression
GetOptimizedBlockExpression()
static BlockExpression System.Linq.Expressions.Expression< TDelegate >.GetOptimizedBlockExpression (IReadOnlyList< Expression< TDelegate > > expressions) inline static private inherited
Definition at line 2257 of file Expression.cs.
    {
        switch (expressions.Count)
        {
        case 0:
            return BlockCore(typeof(void), EmptyReadOnlyCollection<ParameterExpression>.Instance, EmptyReadOnlyCollection<Expression>.Instance);
        case 2:
            return new Block2(expressions[0], expressions[1]);
        case 3:
            return new Block3(expressions[0], expressions[1], expressions[2]);
        case 4:
            return new Block4(expressions[0], expressions[1], expressions[2], expressions[3]);
        case 5:
            return new Block5(expressions[0], expressions[1], expressions[2], expressions[3], expressions[4]);
        default:
        {
            IReadOnlyList<Expression> readOnlyList = expressions as ReadOnlyCollection<Expression>;
            return new BlockN(readOnlyList ?? expressions.ToArray());
        }
        }
    }
References System.Linq.Expressions.Expression< TDelegate >.BlockCore(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Reflection.Instance.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Block(), and System.Linq.Expressions.Expression< TDelegate >.Block().