Terraria: System.Linq.Expressions.Expression.Power
Power() [2/2]
static BinaryExpression System.Linq.Expressions.Expression< TDelegate >.Power (Expression< TDelegate > left, Expression< TDelegate > right, MethodInfo? method) inline static inherited
Definition at line 2024 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(left, "left");
        ExpressionUtils.RequiresCanRead(right, "right");
        if (method == null)
        {
            if (!(left.Type == right.Type) || !left.Type.IsArithmetic())
            {
                string name = "op_Exponent";
                BinaryExpression userDefinedBinaryOperator = GetUserDefinedBinaryOperator(ExpressionType.Power, name, left, right, liftToNull: true);
                if (userDefinedBinaryOperator == null)
                {
                    name = "op_Exponentiation";
                    userDefinedBinaryOperator = GetUserDefinedBinaryOperator(ExpressionType.Power, name, left, right, liftToNull: true);
                    if (userDefinedBinaryOperator == null)
                    {
                        throw Error.BinaryOperatorNotDefined(ExpressionType.Power, left.Type, right.Type);
                    }
                }
                ParameterInfo[] parametersCached = userDefinedBinaryOperator.Method.GetParametersCached();
                ValidateParamswithOperandsOrThrow(parametersCached[0].ParameterType, left.Type, ExpressionType.Power, name);
                ValidateParamswithOperandsOrThrow(parametersCached[1].ParameterType, right.Type, ExpressionType.Power, name);
                return userDefinedBinaryOperator;
            }
            method = CachedReflectionInfo.Math_Pow_Double_Double;
        }
        return GetMethodBasedBinaryOperator(ExpressionType.Power, left, right, method, liftToNull: true);
    }
References System.Linq.Expressions.Error.BinaryOperatorNotDefined(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedBinaryOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperator(), System.Linq.Expressions.CachedReflectionInfo.Math_Pow_Double_Double, System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), and System.Linq.Expressions.Expression< TDelegate >.ValidateParamswithOperandsOrThrow().