Terraria: System.Linq.Expressions.Expression.Block
Block() [10/12]
static BlockExpression System.Linq.Expressions.Expression< TDelegate >.Block (Type type, IEnumerable< ParameterExpression< TDelegate > >? variables, IEnumerable< Expression< TDelegate > > expressions) inline static inherited
Definition at line 2181 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(type, "type");
        ContractUtils.RequiresNotNull(expressions, "expressions");
        ReadOnlyCollection<Expression> readOnlyCollection = expressions.ToReadOnly();
        RequiresCanRead(readOnlyCollection, "expressions");
        ReadOnlyCollection<ParameterExpression> readOnlyCollection2 = variables.ToReadOnly();
        if (readOnlyCollection2.Count == 0 && readOnlyCollection.Count != 0)
        {
            int count = readOnlyCollection.Count;
            if (count != 0)
            {
                Expression expression = readOnlyCollection[count - 1];
                if (expression.Type == type)
                {
                    return GetOptimizedBlockExpression(readOnlyCollection);
                }
            }
        }
        return BlockCore(type, readOnlyCollection2, readOnlyCollection);
    }
References System.Linq.Expressions.Expression< TDelegate >.BlockCore(), System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Expression< TDelegate >.GetOptimizedBlockExpression(), System.Linq.Expressions.Expression< TDelegate >.RequiresCanRead(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), and System.type.