Terraria: System.Linq.Expressions.Expression.Call
Call() [7/16]
static MethodCallExpression System.Linq.Expressions.Expression< TDelegate >.Call (Expression< TDelegate >? instance, MethodInfo method, IEnumerable< Expression< TDelegate > >? arguments) inline static inherited
Definition at line 4171 of file Expression.cs.
    {
        IReadOnlyList<Expression> readOnlyList = (arguments as IReadOnlyList<Expression>) ?? arguments.ToReadOnly();
        int count = readOnlyList.Count;
        switch (count)
        {
        case 0:
            return Call(instance, method);
        case 1:
            return Call(instance, method, readOnlyList[0]);
        case 2:
            return Call(instance, method, readOnlyList[0], readOnlyList[1]);
        case 3:
            return Call(instance, method, readOnlyList[0], readOnlyList[1], readOnlyList[2]);
        default:
        {
            if (instance == null)
            {
                switch (count)
                {
                case 4:
                    return Call(method, readOnlyList[0], readOnlyList[1], readOnlyList[2], readOnlyList[3]);
                case 5:
                    return Call(method, readOnlyList[0], readOnlyList[1], readOnlyList[2], readOnlyList[3], readOnlyList[4]);
                }
            }
            ContractUtils.RequiresNotNull(method, "method");
            ReadOnlyCollection<Expression> arguments2 = readOnlyList.ToReadOnly();
            ValidateMethodInfo(method, "method");
            ValidateStaticOrInstanceMethod(instance, method);
            ValidateArgumentTypes(method, ExpressionType.Call, ref arguments2, "method");
            if (instance == null)
            {
                return new MethodCallExpressionN(method, arguments2);
            }
            return new InstanceMethodCallExpressionN(method, instance, arguments2);
        }
        }
    }
References System.Linq.Expressions.Call, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Expression< TDelegate >.ValidateArgumentTypes(), System.Linq.Expressions.Expression< TDelegate >.ValidateMethodInfo(), and System.Linq.Expressions.Expression< TDelegate >.ValidateStaticOrInstanceMethod().