Terraria: System.Linq.Expressions.Expression.TypeIs
TypeIs()
static TypeBinaryExpression System.Linq.Expressions.Expression< TDelegate >.TypeIs (Expression< TDelegate > expression, Type type) inline static inherited
Definition at line 4966 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(expression, "expression");
        ContractUtils.RequiresNotNull(type, "type");
        if (type.IsByRef)
        {
            throw Error.TypeMustNotBeByRef("type");
        }
        return new TypeBinaryExpression(expression, type, ExpressionType.TypeIs);
    }
References System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.type, and System.Linq.Expressions.Error.TypeMustNotBeByRef().
Referenced by System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), and System.Linq.Expressions.TypeBinaryExpression.Update().