Terraria: System.Linq.Expressions.Expression.Call
Call() [2/16]
static MethodCallExpression System.Linq.Expressions.Expression< TDelegate >.Call (Expression< TDelegate > instance, MethodInfo method, Expression< TDelegate > arg0) inline static package inherited
Definition at line 4097 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(method, "method");
        ContractUtils.RequiresNotNull(arg0, "arg0");
        ParameterInfo[] array = ValidateMethodAndGetParameters(instance, method);
        ValidateArgumentCount(method, ExpressionType.Call, 1, array);
        arg0 = ValidateOneArgument(method, ExpressionType.Call, arg0, array[0], "method", "arg0");
        if (instance != null)
        {
            return new InstanceMethodCallExpression1(method, instance, arg0);
        }
        return new MethodCallExpression1(method, arg0);
    }
References System.array, System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Expression< TDelegate >.ValidateArgumentCount(), System.Linq.Expressions.Expression< TDelegate >.ValidateMethodAndGetParameters(), and System.Linq.Expressions.Expression< TDelegate >.ValidateOneArgument().