Terraria: System.Linq.Expressions.Expression.GetUserDefinedUnaryOperatorOrThrow
GetUserDefinedUnaryOperatorOrThrow()
static UnaryExpression System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedUnaryOperatorOrThrow (ExpressionType unaryType, string name, Expression< TDelegate > operand) inline static private inherited
Definition at line 5021 of file Expression.cs.
    {
        UnaryExpression userDefinedUnaryOperator = GetUserDefinedUnaryOperator(unaryType, name, operand);
        if (userDefinedUnaryOperator != null)
        {
            ValidateParamswithOperandsOrThrow(userDefinedUnaryOperator.Method.GetParametersCached()[0].ParameterType, operand.Type, unaryType, name);
            return userDefinedUnaryOperator;
        }
        throw Error.UnaryOperatorNotDefined(unaryType, operand.Type);
    }
References System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedUnaryOperator(), System.Linq.Expressions.Error.UnaryOperatorNotDefined(), and System.Linq.Expressions.Expression< TDelegate >.ValidateParamswithOperandsOrThrow().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Decrement(), System.Linq.Expressions.Expression< TDelegate >.Increment(), System.Linq.Expressions.Expression< TDelegate >.IsFalse(), System.Linq.Expressions.Expression< TDelegate >.IsTrue(), System.Linq.Expressions.Expression< TDelegate >.MakeOpAssignUnary(), System.Linq.Expressions.Expression< TDelegate >.Negate(), System.Linq.Expressions.Expression< TDelegate >.NegateChecked(), System.Linq.Expressions.Expression< TDelegate >.Not(), System.Linq.Expressions.Expression< TDelegate >.OnesComplement(), and System.Linq.Expressions.Expression< TDelegate >.UnaryPlus().