Terraria: System.Linq.Expressions.Expression.Return
Return() [1/4]
static GotoExpression System.Linq.Expressions.Expression< TDelegate >.Return (LabelTarget target) inline static inherited
Definition at line 2712 of file Expression.cs.
    {
        return MakeGoto(GotoExpressionKind.Return, target, null, typeof(void));
    }
References System.Linq.Expressions.Expression< TDelegate >.MakeGoto().
Referenced by System.Dynamic.DynamicMetaObjectBinder.Bind(), and System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate().