Terraria: System.Linq.Expressions.Expression.GetMethodBasedUnaryOperator
GetMethodBasedUnaryOperator()
static UnaryExpression System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedUnaryOperator (ExpressionType unaryType, Expression< TDelegate > operand, MethodInfo method) inline static private inherited
Definition at line 5055 of file Expression.cs.
    {
        ValidateOperator(method);
        ParameterInfo[] parametersCached = method.GetParametersCached();
        if (parametersCached.Length != 1)
        {
            throw Error.IncorrectNumberOfMethodCallArguments(method, "method");
        }
        if (ParameterIsAssignable(parametersCached[0], operand.Type))
        {
            ValidateParamswithOperandsOrThrow(parametersCached[0].ParameterType, operand.Type, unaryType, method.Name);
            return new UnaryExpression(unaryType, operand, method.ReturnType, method);
        }
        if (operand.Type.IsNullableType() && ParameterIsAssignable(parametersCached[0], operand.Type.GetNonNullableType()) && method.ReturnType.IsValueType && !method.ReturnType.IsNullableType())
        {
            return new UnaryExpression(unaryType, operand, method.ReturnType.GetNullableType(), method);
        }
        throw Error.OperandTypesDoNotMatchParameters(unaryType, method.Name);
    }
References System.Linq.Expressions.Error.IncorrectNumberOfMethodCallArguments(), System.Linq.Expressions.Error.OperandTypesDoNotMatchParameters(), System.Linq.Expressions.Expression< TDelegate >.ParameterIsAssignable(), System.Linq.Expressions.Expression< TDelegate >.ValidateOperator(), and System.Linq.Expressions.Expression< TDelegate >.ValidateParamswithOperandsOrThrow().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Decrement(), System.Linq.Expressions.Expression< TDelegate >.Increment(), System.Linq.Expressions.Expression< TDelegate >.IsFalse(), System.Linq.Expressions.Expression< TDelegate >.IsTrue(), System.Linq.Expressions.Expression< TDelegate >.MakeOpAssignUnary(), System.Linq.Expressions.Expression< TDelegate >.Negate(), System.Linq.Expressions.Expression< TDelegate >.NegateChecked(), System.Linq.Expressions.Expression< TDelegate >.Not(), System.Linq.Expressions.Expression< TDelegate >.OnesComplement(), and System.Linq.Expressions.Expression< TDelegate >.UnaryPlus().