Terraria: System.Linq.Expressions.Expression.GetUserDefinedBinaryOperator
GetUserDefinedBinaryOperator() [1/2]
static BinaryExpression System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperator (ExpressionType binaryType, string name, Expression< TDelegate > left, Expression< TDelegate > right, bool liftToNull) inline static private inherited
Definition at line 719 of file Expression.cs.
    {
        MethodInfo userDefinedBinaryOperator = GetUserDefinedBinaryOperator(binaryType, left.Type, right.Type, name);
        if (userDefinedBinaryOperator != null)
        {
            return new MethodBinaryExpression(binaryType, left, right, userDefinedBinaryOperator.ReturnType, userDefinedBinaryOperator);
        }
        if (left.Type.IsNullableType() && right.Type.IsNullableType())
        {
            Type nonNullableType = left.Type.GetNonNullableType();
            Type nonNullableType2 = right.Type.GetNonNullableType();
            userDefinedBinaryOperator = GetUserDefinedBinaryOperator(binaryType, nonNullableType, nonNullableType2, name);
            if (userDefinedBinaryOperator != null && userDefinedBinaryOperator.ReturnType.IsValueType && !userDefinedBinaryOperator.ReturnType.IsNullableType())
            {
                if (userDefinedBinaryOperator.ReturnType != typeof(bool) || liftToNull)
                {
                    return new MethodBinaryExpression(binaryType, left, right, userDefinedBinaryOperator.ReturnType.GetNullableType(), userDefinedBinaryOperator);
                }
                return new MethodBinaryExpression(binaryType, left, right, typeof(bool), userDefinedBinaryOperator);
            }
        }
        return null;
    }
References System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperator().
Referenced by System.Linq.Expressions.Expression< TDelegate >.AndAlso(), System.Linq.Expressions.Expression< TDelegate >.GetEqualityComparisonOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperatorOrThrow(), System.Linq.Expressions.Expression< TDelegate >.OrElse(), and System.Linq.Expressions.Expression< TDelegate >.Power().