Terraria: System.Linq.Expressions.Expression.ArrayLength
ArrayLength()
static UnaryExpression System.Linq.Expressions.Expression< TDelegate >.ArrayLength (Expression< TDelegate > array) inline static inherited
Definition at line 5326 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(array, "array");
        if (!array.Type.IsSZArray)
        {
            if (!array.Type.IsArray || !typeof(Array).IsAssignableFrom(array.Type))
            {
                throw Error.ArgumentMustBeArray("array");
            }
            throw Error.ArgumentMustBeSingleDimensionalArrayType("array");
        }
        return new UnaryExpression(ExpressionType.ArrayLength, array, typeof(int), null);
    }
References System.Linq.Expressions.Error.ArgumentMustBeArray(), System.Linq.Expressions.Error.ArgumentMustBeSingleDimensionalArrayType(), System.array, and System.Dynamic.Utils.ExpressionUtils.RequiresCanRead().
Referenced by System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate().