Terraria: System.Linq.Expressions.Expression.Constant
Constant() [1/2]
static ConstantExpression System.Linq.Expressions.Expression< TDelegate >.Constant (object? value) inline static inherited
Definition at line 2368 of file Expression.cs.
    {
        return new ConstantExpression(value);
    }
References System.value.
Referenced by System.Linq.EnumerableQuery< T >.EnumerableQuery(), System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer(), System.Linq.Queryable.Aggregate< TSource, TAccumulate >(), System.Linq.Queryable.Aggregate< TSource, TAccumulate, TResult >(), System.Linq.Queryable.Append< TSource >(), System.Dynamic.ExpandoObject.MetaExpando.BindDeleteMember(), System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember(), System.Dynamic.ExpandoObject.MetaExpando.BindSetMember(), System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Linq.Expressions.TypeBinaryExpression.ByValParameterTypeEqual(), System.Linq.Queryable.Chunk< TSource >(), System.Linq.Expressions.Utils.Constant(), System.Dynamic.DynamicObject.MetaDynamic.Constant< TBinder >(), System.Linq.Queryable.Contains< TSource >(), System.Linq.Queryable.Contains< TSource >(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Linq.Expressions.Compiler.LambdaCompiler.CreateLazyInitializedField< T >(), System.Linq.Queryable.DefaultIfEmpty< TSource >(), System.Linq.Queryable.Distinct< TSource >(), System.Linq.Queryable.DistinctBy< TSource, TKey >(), System.Linq.Queryable.ElementAt< TSource >(), System.Linq.Queryable.ElementAt< TSource >(), System.Linq.Queryable.ElementAtOrDefault< TSource >(), System.Linq.Queryable.ElementAtOrDefault< TSource >(), System.Linq.Queryable.Except< TSource >(), System.Linq.Queryable.ExceptBy< TSource, TKey >(), System.Linq.Queryable.FirstOrDefault< TSource >(), System.Linq.Queryable.FirstOrDefault< TSource >(), System.Dynamic.BindingRestrictions.InstanceRestriction.GetExpression(), System.Linq.Queryable.GetSourceExpression< TSource >(), System.Linq.Queryable.GroupBy< TSource, TKey >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement, TResult >(), System.Linq.Queryable.GroupBy< TSource, TKey, TResult >(), System.Linq.Queryable.GroupJoin< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.Intersect< TSource >(), System.Linq.Queryable.IntersectBy< TSource, TKey >(), System.Linq.Queryable.Join< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.LastOrDefault< TSource >(), System.Linq.Queryable.LastOrDefault< TSource >(), System.Linq.Queryable.Max< TSource >(), System.Linq.Queryable.MaxBy< TSource, TKey >(), System.Linq.Queryable.Min< TSource >(), System.Linq.Queryable.MinBy< TSource, TKey >(), System.Linq.Queryable.OrderBy< TSource, TKey >(), System.Linq.Queryable.OrderByDescending< TSource, TKey >(), System.Linq.Queryable.Prepend< TSource >(), System.Linq.Expressions.DynamicExpression.Reduce(), System.Linq.Expressions.TypeBinaryExpression.ReduceTypeEqual(), System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted(), System.Linq.Queryable.SequenceEqual< TSource >(), System.Linq.Queryable.SingleOrDefault< TSource >(), System.Linq.Queryable.SingleOrDefault< TSource >(), System.Linq.Queryable.Skip< TSource >(), System.Linq.Queryable.SkipLast< TSource >(), System.Linq.Queryable.Take< TSource >(), System.Linq.Queryable.Take< TSource >(), System.Linq.Queryable.TakeLast< TSource >(), System.Linq.Queryable.ThenBy< TSource, TKey >(), System.Linq.Queryable.ThenByDescending< TSource, TKey >(), System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch(), System.Linq.Queryable.Union< TSource >(), System.Linq.Queryable.UnionBy< TSource, TKey >(), System.Linq.EnumerableRewriter.VisitConstant(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitParameter(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitParameter(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitRuntimeVariables(), and System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitRuntimeVariables().