Terraria: System.Linq.Expressions.Expression.ParameterIsAssignable
ParameterIsAssignable()
static bool System.Linq.Expressions.Expression< TDelegate >.ParameterIsAssignable (ParameterInfo pi, Type argType) inline static package inherited
Definition at line 848 of file Expression.cs.
    {
        Type type = pi.ParameterType;
        if (type.IsByRef)
        {
            type = type.GetElementType();
        }
        return TypeUtils.AreReferenceAssignable(type, argType);
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), and System.type.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Coalesce(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedBinaryOperator(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedCoercionOperator(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedUnaryOperator(), System.Linq.Expressions.Expression< TDelegate >.Switch(), System.Linq.Expressions.Expression< TDelegate >.ValidateUserDefinedConditionalLogicOperator(), and System.Linq.Expressions.Expression< TDelegate >.VerifyOpTrueFalse().