Terraria: System.Linq.Expressions.Expression.ValidateMethodAndGetParameters
ValidateMethodAndGetParameters()
static ParameterInfo[] System.Linq.Expressions.Expression< TDelegate >.ValidateMethodAndGetParameters (Expression< TDelegate > instance, MethodInfo method) inline static private inherited
Definition at line 4211 of file Expression.cs.
    {
        ValidateMethodInfo(method, "method");
        ValidateStaticOrInstanceMethod(instance, method);
        return GetParametersForValidation(method, ExpressionType.Call);
    }
References System.Linq.Expressions.Expression< TDelegate >.GetParametersForValidation(), System.Linq.Expressions.Expression< TDelegate >.ValidateMethodInfo(), and System.Linq.Expressions.Expression< TDelegate >.ValidateStaticOrInstanceMethod().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), and System.Linq.Expressions.Expression< TDelegate >.Call().