Terraria: System.Linq.Expressions.Expression.Quote
Quote()
static UnaryExpression System.Linq.Expressions.Expression< TDelegate >.Quote (Expression< TDelegate > expression) inline static inherited
Definition at line 5340 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(expression, "expression");
        if (!(expression is LambdaExpression lambdaExpression))
        {
            throw Error.QuotedExpressionMustBeLambda("expression");
        }
        return new UnaryExpression(ExpressionType.Quote, lambdaExpression, lambdaExpression.PublicType, null);
    }
References System.Linq.Expressions.Error.QuotedExpressionMustBeLambda(), and System.Dynamic.Utils.ExpressionUtils.RequiresCanRead().
Referenced by System.Linq.Queryable.Aggregate< TSource >(), System.Linq.Queryable.Aggregate< TSource, TAccumulate >(), System.Linq.Queryable.Aggregate< TSource, TAccumulate, TResult >(), System.Linq.Queryable.All< TSource >(), System.Linq.Queryable.Any< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Count< TSource >(), System.Linq.Queryable.DistinctBy< TSource, TKey >(), System.Linq.Queryable.DistinctBy< TSource, TKey >(), System.Linq.Queryable.ExceptBy< TSource, TKey >(), System.Linq.Queryable.ExceptBy< TSource, TKey >(), System.Linq.Queryable.First< TSource >(), System.Linq.Queryable.FirstOrDefault< TSource >(), System.Linq.Queryable.FirstOrDefault< TSource >(), System.Linq.Queryable.GroupBy< TSource, TKey >(), System.Linq.Queryable.GroupBy< TSource, TKey >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement, TResult >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement, TResult >(), System.Linq.Queryable.GroupBy< TSource, TKey, TResult >(), System.Linq.Queryable.GroupBy< TSource, TKey, TResult >(), System.Linq.Queryable.GroupJoin< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.GroupJoin< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.IntersectBy< TSource, TKey >(), System.Linq.Queryable.IntersectBy< TSource, TKey >(), System.Linq.Queryable.Join< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.Join< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.Last< TSource >(), System.Linq.Queryable.LastOrDefault< TSource >(), System.Linq.Queryable.LastOrDefault< TSource >(), System.Linq.Queryable.LongCount< TSource >(), System.Linq.Queryable.Max< TSource, TResult >(), System.Linq.Queryable.MaxBy< TSource, TKey >(), System.Linq.Queryable.MaxBy< TSource, TKey >(), System.Linq.Queryable.Min< TSource, TResult >(), System.Linq.Queryable.MinBy< TSource, TKey >(), System.Linq.Queryable.MinBy< TSource, TKey >(), System.Linq.Queryable.OrderBy< TSource, TKey >(), System.Linq.Queryable.OrderBy< TSource, TKey >(), System.Linq.Queryable.OrderByDescending< TSource, TKey >(), System.Linq.Queryable.OrderByDescending< TSource, TKey >(), System.Linq.Queryable.Select< TSource, TResult >(), System.Linq.Queryable.Select< TSource, TResult >(), System.Linq.Queryable.SelectMany< TSource, TCollection, TResult >(), System.Linq.Queryable.SelectMany< TSource, TCollection, TResult >(), System.Linq.Queryable.SelectMany< TSource, TResult >(), System.Linq.Queryable.SelectMany< TSource, TResult >(), System.Linq.Queryable.Single< TSource >(), System.Linq.Queryable.SingleOrDefault< TSource >(), System.Linq.Queryable.SingleOrDefault< TSource >(), System.Linq.Queryable.SkipWhile< TSource >(), System.Linq.Queryable.SkipWhile< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.TakeWhile< TSource >(), System.Linq.Queryable.TakeWhile< TSource >(), System.Linq.Queryable.ThenBy< TSource, TKey >(), System.Linq.Queryable.ThenBy< TSource, TKey >(), System.Linq.Queryable.ThenByDescending< TSource, TKey >(), System.Linq.Queryable.ThenByDescending< TSource, TKey >(), System.Dynamic.Utils.ExpressionUtils.TryQuote(), System.Linq.Queryable.UnionBy< TSource, TKey >(), System.Linq.Queryable.UnionBy< TSource, TKey >(), System.Linq.Queryable.Where< TSource >(), System.Linq.Queryable.Where< TSource >(), and System.Linq.Queryable.Zip< TFirst, TSecond, TResult >().