Terraria: System.Linq.Expressions.Expression.AddAssignChecked
AddAssignChecked() [3/3]
static BinaryExpression System.Linq.Expressions.Expression< TDelegate >.AddAssignChecked (Expression< TDelegate > left, Expression< TDelegate > right, MethodInfo? method, LambdaExpression< TDelegate >? conversion) inline static inherited
Definition at line 1407 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(left, "left");
        RequiresCanWrite(left, "left");
        ExpressionUtils.RequiresCanRead(right, "right");
        if (method == null)
        {
            if (left.Type == right.Type && left.Type.IsArithmetic())
            {
                if (conversion != null)
                {
                    throw Error.ConversionIsNotSupportedForArithmeticTypes();
                }
                return new SimpleBinaryExpression(ExpressionType.AddAssignChecked, left, right, left.Type);
            }
            return GetUserDefinedAssignOperatorOrThrow(ExpressionType.AddAssignChecked, "op_Addition", left, right, conversion, liftToNull: true);
        }
        return GetMethodBasedAssignOperator(ExpressionType.AddAssignChecked, left, right, method, conversion, liftToNull: true);
    }
References System.Linq.Expressions.Error.ConversionIsNotSupportedForArithmeticTypes(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedAssignOperator(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedAssignOperatorOrThrow(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), and System.Linq.Expressions.Expression< TDelegate >.RequiresCanWrite().