Terraria: System.Linq.Expressions.Expression.ValidateTryAndCatchHaveSameType
ValidateTryAndCatchHaveSameType()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateTryAndCatchHaveSameType (Type type, Expression< TDelegate > tryBody, ReadOnlyCollection< CatchBlock > handlers) inline static private inherited
Definition at line 4922 of file Expression.cs.
    {
        if (type != null)
        {
            if (!(type != typeof(void)))
            {
                return;
            }
            if (!TypeUtils.AreReferenceAssignable(type, tryBody.Type))
            {
                throw Error.ArgumentTypesMustMatch();
            }
            {
                foreach (CatchBlock handler in handlers)
                {
                    if (!TypeUtils.AreReferenceAssignable(type, handler.Body.Type))
                    {
                        throw Error.ArgumentTypesMustMatch();
                    }
                }
                return;
            }
        }
        if (tryBody.Type == typeof(void))
        {
            foreach (CatchBlock handler2 in handlers)
            {
                if (handler2.Body.Type != typeof(void))
                {
                    throw Error.BodyOfCatchMustHaveSameTypeAsBodyOfTry();
                }
            }
            return;
        }
        type = tryBody.Type;
        foreach (CatchBlock handler3 in handlers)
        {
            if (!TypeUtils.AreEquivalent(handler3.Body.Type, type))
            {
                throw Error.BodyOfCatchMustHaveSameTypeAsBodyOfTry();
            }
        }
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Error.ArgumentTypesMustMatch(), System.Linq.Expressions.CatchBlock.Body, System.Linq.Expressions.Error.BodyOfCatchMustHaveSameTypeAsBodyOfTry(), System.Linq.Expressions.Expression< TDelegate >.Type, and System.type.
Referenced by System.Linq.Expressions.Expression< TDelegate >.MakeTry().