Terraria: System.Linq.Expressions.Expression.ValidateMemberInitArgs
ValidateMemberInitArgs()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateMemberInitArgs (Type type, ReadOnlyCollection< MemberBinding > bindings) inline static private inherited
Definition at line 3977 of file Expression.cs.
    {
        int i = 0;
        for (int count = bindings.Count; i < count; i++)
        {
            MemberBinding memberBinding = bindings[i];
            ContractUtils.RequiresNotNull(memberBinding, "bindings");
            memberBinding.ValidateAsDefinedHere(i);
            if (!memberBinding.Member.DeclaringType.IsAssignableFrom(type))
            {
                throw Error.NotAMemberOfType(memberBinding.Member.Name, type, "bindings", i);
            }
        }
    }
References System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Error.NotAMemberOfType(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), and System.type.
Referenced by System.Linq.Expressions.Expression< TDelegate >.MemberBind(), and System.Linq.Expressions.Expression< TDelegate >.MemberInit().