Terraria: System.Linq.Expressions.Expression.GetMethodBasedBinaryOperator
GetMethodBasedBinaryOperator()
static BinaryExpression System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedBinaryOperator (ExpressionType binaryType, Expression< TDelegate > left, Expression< TDelegate > right, MethodInfo method, bool liftToNull) inline static private inherited
Definition at line 743 of file Expression.cs.
    {
        ValidateOperator(method);
        ParameterInfo[] parametersCached = method.GetParametersCached();
        if (parametersCached.Length != 2)
        {
            throw Error.IncorrectNumberOfMethodCallArguments(method, "method");
        }
        if (ParameterIsAssignable(parametersCached[0], left.Type) && ParameterIsAssignable(parametersCached[1], right.Type))
        {
            ValidateParamswithOperandsOrThrow(parametersCached[0].ParameterType, left.Type, binaryType, method.Name);
            ValidateParamswithOperandsOrThrow(parametersCached[1].ParameterType, right.Type, binaryType, method.Name);
            return new MethodBinaryExpression(binaryType, left, right, method.ReturnType, method);
        }
        if (left.Type.IsNullableType() && right.Type.IsNullableType() && ParameterIsAssignable(parametersCached[0], left.Type.GetNonNullableType()) && ParameterIsAssignable(parametersCached[1], right.Type.GetNonNullableType()) && method.ReturnType.IsValueType && !method.ReturnType.IsNullableType())
        {
            if (method.ReturnType != typeof(bool) || liftToNull)
            {
                return new MethodBinaryExpression(binaryType, left, right, method.ReturnType.GetNullableType(), method);
            }
            return new MethodBinaryExpression(binaryType, left, right, typeof(bool), method);
        }
        throw Error.OperandTypesDoNotMatchParameters(binaryType, method.Name);
    }
References System.Linq.Expressions.Error.IncorrectNumberOfMethodCallArguments(), System.Linq.Expressions.Error.OperandTypesDoNotMatchParameters(), System.Linq.Expressions.Expression< TDelegate >.ParameterIsAssignable(), System.Linq.Expressions.Expression< TDelegate >.ValidateOperator(), and System.Linq.Expressions.Expression< TDelegate >.ValidateParamswithOperandsOrThrow().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Add(), System.Linq.Expressions.Expression< TDelegate >.AddChecked(), System.Linq.Expressions.Expression< TDelegate >.And(), System.Linq.Expressions.Expression< TDelegate >.Divide(), System.Linq.Expressions.Expression< TDelegate >.Equal(), System.Linq.Expressions.Expression< TDelegate >.ExclusiveOr(), System.Linq.Expressions.Expression< TDelegate >.GetMethodBasedAssignOperator(), System.Linq.Expressions.Expression< TDelegate >.GreaterThan(), System.Linq.Expressions.Expression< TDelegate >.GreaterThanOrEqual(), System.Linq.Expressions.Expression< TDelegate >.LeftShift(), System.Linq.Expressions.Expression< TDelegate >.LessThan(), System.Linq.Expressions.Expression< TDelegate >.LessThanOrEqual(), System.Linq.Expressions.Expression< TDelegate >.Modulo(), System.Linq.Expressions.Expression< TDelegate >.Multiply(), System.Linq.Expressions.Expression< TDelegate >.MultiplyChecked(), System.Linq.Expressions.Expression< TDelegate >.NotEqual(), System.Linq.Expressions.Expression< TDelegate >.Or(), System.Linq.Expressions.Expression< TDelegate >.Power(), System.Linq.Expressions.Expression< TDelegate >.RightShift(), System.Linq.Expressions.Expression< TDelegate >.Subtract(), and System.Linq.Expressions.Expression< TDelegate >.SubtractChecked().