Terraria: System.Linq.Expressions.Expression.Lambda
Lambda() [5/12]
static LambdaExpression System.Linq.Expressions.Expression< TDelegate >.Lambda (Expression< TDelegate > body, string? name, bool tailCall, IEnumerable< ParameterExpression< TDelegate > >? parameters) inline static inherited
Definition at line 3342 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(body, "body");
        ReadOnlyCollection<ParameterExpression> readOnlyCollection = parameters.ToReadOnly();
        int count = readOnlyCollection.Count;
        Type[] array = new Type[count + 1];
        if (count > 0)
        {
            HashSet<ParameterExpression> hashSet = new HashSet<ParameterExpression>();
            for (int i = 0; i < count; i++)
            {
                ParameterExpression parameterExpression = readOnlyCollection[i];
                ContractUtils.RequiresNotNull(parameterExpression, "parameter");
                array[i] = (parameterExpression.IsByRef ? parameterExpression.Type.MakeByRefType() : parameterExpression.Type);
                if (!hashSet.Add(parameterExpression))
                {
                    throw Error.DuplicateVariable(parameterExpression, "parameters", i);
                }
            }
        }
        array[count] = body.Type;
        Type delegateType = System.Linq.Expressions.Compiler.DelegateHelpers.MakeDelegateType(array);
        return CreateLambda(delegateType, body, name, tailCall, readOnlyCollection);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Expression< TDelegate >.CreateLambda(), System.Linq.Expressions.Error.DuplicateVariable(), System.Linq.Expressions.Compiler.DelegateHelpers.MakeDelegateType(), and System.Dynamic.Utils.ContractUtils.RequiresNotNull().