Terraria: System.Linq.Expressions.Expression.CreateLambda
CreateLambda()
static LambdaExpression System.Linq.Expressions.Expression< TDelegate >.CreateLambda (Type delegateType, Expression< TDelegate > body, string name, bool tailCall, ReadOnlyCollection< ParameterExpression< TDelegate > > parameters) inline static package inherited
Definition at line 3246 of file Expression.cs.
    {
        CacheDict<Type, Func<Expression, string, bool, ReadOnlyCollection<ParameterExpression>, LambdaExpression>> cacheDict = s_lambdaFactories;
        if (cacheDict == null)
        {
            cacheDict = (s_lambdaFactories = new CacheDict<Type, Func<Expression, string, bool, ReadOnlyCollection<ParameterExpression>, LambdaExpression>>(50));
        }
        if (!cacheDict.TryGetValue(delegateType, out var value))
        {
            MethodInfo method = typeof(Expression<>).MakeGenericType(delegateType).GetMethod("Create", BindingFlags.Static | BindingFlags.NonPublic);
            if (delegateType.IsCollectible)
            {
                return (LambdaExpression)method.Invoke(null, new object[4] { body, name, tailCall, parameters });
            }
            value = (cacheDict[delegateType] = (Func<Expression, string, bool, ReadOnlyCollection<ParameterExpression>, LambdaExpression>)method.CreateDelegate(typeof(Func<Expression, string, bool, ReadOnlyCollection<ParameterExpression>, LambdaExpression>)));
        }
        return value(body, name, tailCall, parameters);
    }
References System.Linq.Expressions.Expression< TDelegate >.s_lambdaFactories, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Lambda(), System.Linq.Expressions.Expression< TDelegate >.Lambda(), and System.Linq.Expressions.Expression< TDelegate >.Lambda().