Terraria: System.Linq.Expressions.Expression.MakeGoto
MakeGoto()
static GotoExpression System.Linq.Expressions.Expression< TDelegate >.MakeGoto (GotoExpressionKind kind, LabelTarget target, Expression< TDelegate >? value, Type type) inline static inherited
Definition at line 2752 of file Expression.cs.
    {
        ValidateGoto(target, ref value, "target", "value", type);
        return new GotoExpression(kind, target, value, type);
    }
References System.type, System.Linq.Expressions.Expression< TDelegate >.ValidateGoto(), and System.value.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Break(), System.Linq.Expressions.Expression< TDelegate >.Break(), System.Linq.Expressions.Expression< TDelegate >.Break(), System.Linq.Expressions.Expression< TDelegate >.Break(), System.Linq.Expressions.Expression< TDelegate >.Continue(), System.Linq.Expressions.Expression< TDelegate >.Continue(), System.Linq.Expressions.Expression< TDelegate >.Goto(), System.Linq.Expressions.Expression< TDelegate >.Goto(), System.Linq.Expressions.Expression< TDelegate >.Goto(), System.Linq.Expressions.Expression< TDelegate >.Goto(), System.Linq.Expressions.Expression< TDelegate >.Return(), System.Linq.Expressions.Expression< TDelegate >.Return(), System.Linq.Expressions.Expression< TDelegate >.Return(), System.Linq.Expressions.Expression< TDelegate >.Return(), System.Linq.Expressions.Compiler.StackSpiller.RewriteGotoExpression(), System.Linq.Expressions.GotoExpression.Update(), and System.Linq.EnumerableRewriter.VisitGoto().