Terraria: System.Linq.Expressions.Expression.FindMethod
FindMethod()
static MethodInfo System.Linq.Expressions.Expression< TDelegate >.FindMethod ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)] Type type, string methodName, Type[] typeArgs, Expression< TDelegate >[] args, BindingFlags flags) inline static private inherited
Definition at line 4270 of file Expression.cs.
    {
        int num = 0;
        MethodInfo methodInfo = null;
        MethodInfo[] methods = type.GetMethods(flags);
        foreach (MethodInfo methodInfo2 in methods)
        {
            if (!methodInfo2.Name.Equals(methodName, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }
            MethodInfo methodInfo3 = ApplyTypeArgs(methodInfo2, typeArgs);
            if (methodInfo3 != null && IsCompatible(methodInfo3, args))
            {
                if (methodInfo == null || (!methodInfo.IsPublic && methodInfo3.IsPublic))
                {
                    methodInfo = methodInfo3;
                    num = 1;
                }
                else if (methodInfo.IsPublic == methodInfo3.IsPublic)
                {
                    num++;
                }
            }
        }
        if (num == 0)
        {
            if (typeArgs != null && typeArgs.Length != 0)
            {
                throw Error.GenericMethodWithArgsDoesNotExistOnType(methodName, type);
            }
            throw Error.MethodWithArgsDoesNotExistOnType(methodName, type);
        }
        if (num > 1)
        {
            throw Error.MethodWithMoreThanOneMatch(methodName, type);
        }
        return methodInfo;
    }
References System.Linq.Expressions.Expression< TDelegate >.ApplyTypeArgs(), System.Linq.Expressions.Error.GenericMethodWithArgsDoesNotExistOnType(), System.Linq.Expressions.Expression< TDelegate >.IsCompatible(), System.Linq.Expressions.Error.MethodWithArgsDoesNotExistOnType(), System.Linq.Expressions.Error.MethodWithMoreThanOneMatch(), and System.type.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Call(), System.Linq.Expressions.Expression< TDelegate >.Call(), and System.Linq.Expressions.Expression< TDelegate >.ListInit().