Terraria: System.Linq.Expressions.Expression.BlockCore
BlockCore()
static BlockExpression System.Linq.Expressions.Expression< TDelegate >.BlockCore (Type type, ReadOnlyCollection< ParameterExpression< TDelegate > > variables, ReadOnlyCollection< Expression< TDelegate > > expressions) inline static private inherited
Definition at line 2203 of file Expression.cs.
    {
        ValidateVariables(variables, "variables");
        if (type != null)
        {
            if (expressions.Count == 0)
            {
                if (type != typeof(void))
                {
                    throw Error.ArgumentTypesMustMatch();
                }
                return new ScopeWithType(variables, expressions, type);
            }
            Expression expression = expressions[^1];
            if (type != typeof(void) && !TypeUtils.AreReferenceAssignable(type, expression.Type))
            {
                throw Error.ArgumentTypesMustMatch();
            }
            if (!TypeUtils.AreEquivalent(type, expression.Type))
            {
                return new ScopeWithType(variables, expressions, type);
            }
        }
        return expressions.Count switch
        {
            0 => new ScopeWithType(variables, expressions, typeof(void)),
            1 => new Scope1(variables, expressions[0]),
            _ => new ScopeN(variables, expressions),
        };
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Error.ArgumentTypesMustMatch(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.type, and System.Linq.Expressions.Expression< TDelegate >.ValidateVariables().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Block(), and System.Linq.Expressions.Expression< TDelegate >.GetOptimizedBlockExpression().