Terraria: System.Linq.Expressions.Expression.NewArrayInit
NewArrayInit() [1/2]
static NewArrayExpression System.Linq.Expressions.Expression< TDelegate >.NewArrayInit (Type type, IEnumerable< Expression< TDelegate > > initializers) inline static inherited
Definition at line 4390 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(type, "type");
        ContractUtils.RequiresNotNull(initializers, "initializers");
        if (type == typeof(void))
        {
            throw Error.ArgumentCannotBeOfTypeVoid("type");
        }
        TypeUtils.ValidateType(type, "type");
        ReadOnlyCollection<Expression> readOnlyCollection = initializers.ToReadOnly();
        Expression[] array = null;
        int i = 0;
        for (int count = readOnlyCollection.Count; i < count; i++)
        {
            Expression argument = readOnlyCollection[i];
            ExpressionUtils.RequiresCanRead(argument, "initializers", i);
            if (!TypeUtils.AreReferenceAssignable(type, argument.Type))
            {
                if (!TryQuote(type, ref argument))
                {
                    throw Error.ExpressionTypeCannotInitializeArrayType(argument.Type, type);
                }
                if (array == null)
                {
                    array = new Expression[readOnlyCollection.Count];
                    for (int j = 0; j < i; j++)
                    {
                        array[j] = readOnlyCollection[j];
                    }
                }
            }
            if (array != null)
            {
                array[i] = argument;
            }
        }
        if (array != null)
        {
            readOnlyCollection = new TrueReadOnlyCollection<Expression>(array);
        }
        return NewArrayExpression.Make(ExpressionType.NewArrayInit, type.MakeArrayType(), readOnlyCollection);
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Error.ArgumentCannotBeOfTypeVoid(), System.array, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Error.ExpressionTypeCannotInitializeArrayType(), System.Linq.Expressions.NewArrayExpression.Make(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Expression< TDelegate >.TryQuote(), System.type, and System.Dynamic.Utils.TypeUtils.ValidateType().