Terraria: System.Linq.Expressions.Expression.MakeTry
MakeTry()
static TryExpression System.Linq.Expressions.Expression< TDelegate >.MakeTry (Type? type, Expression< TDelegate > body, Expression< TDelegate >? @ finally, Expression< TDelegate >? fault, IEnumerable< CatchBlock >? handlers) inline static inherited
Definition at line 4897 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(body, "body");
        ReadOnlyCollection<CatchBlock> readOnlyCollection = handlers.ToReadOnly();
        ContractUtils.RequiresNotNullItems(readOnlyCollection, "handlers");
        ValidateTryAndCatchHaveSameType(type, body, readOnlyCollection);
        if (fault != null)
        {
            if (@finally != null || readOnlyCollection.Count > 0)
            {
                throw Error.FaultCannotHaveCatchOrFinally("fault");
            }
            ExpressionUtils.RequiresCanRead(fault, "fault");
        }
        else if (@finally != null)
        {
            ExpressionUtils.RequiresCanRead(@finally, "finally");
        }
        else if (readOnlyCollection.Count == 0)
        {
            throw Error.TryMustHaveCatchFinallyOrFault();
        }
        return new TryExpression(type ?? body.Type, body, @finally, fault, readOnlyCollection);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Error.FaultCannotHaveCatchOrFinally(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Linq.Expressions.Error.TryMustHaveCatchFinallyOrFault(), System.type, and System.Linq.Expressions.Expression< TDelegate >.ValidateTryAndCatchHaveSameType().
Referenced by System.Linq.Expressions.Expression< TDelegate >.TryCatch(), System.Linq.Expressions.Expression< TDelegate >.TryCatchFinally(), System.Linq.Expressions.Expression< TDelegate >.TryFault(), System.Linq.Expressions.Expression< TDelegate >.TryFinally(), and System.Linq.Expressions.TryExpression.Update().