Terraria: System.Linq.Expressions.Expression.ValidateVariables
ValidateVariables()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateVariables (ReadOnlyCollection< ParameterExpression< TDelegate > > varList, string collectionName) inline static package inherited
Definition at line 2234 of file Expression.cs.
    {
        int count = varList.Count;
        if (count == 0)
        {
            return;
        }
        HashSet<ParameterExpression> hashSet = new HashSet<ParameterExpression>();
        for (int i = 0; i < count; i++)
        {
            ParameterExpression parameterExpression = varList[i];
            ContractUtils.RequiresNotNull(parameterExpression, collectionName, i);
            if (parameterExpression.IsByRef)
            {
                throw Error.VariableMustNotBeByRef(parameterExpression, parameterExpression.Type, collectionName, i);
            }
            if (!hashSet.Add(parameterExpression))
            {
                throw Error.DuplicateVariable(parameterExpression, collectionName, i);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Error.DuplicateVariable(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), and System.Linq.Expressions.Error.VariableMustNotBeByRef().
Referenced by System.Linq.Expressions.Expression< TDelegate >.BlockCore(), System.Linq.Expressions.ScopeExpression.ReuseOrValidateVariables(), System.Linq.Expressions.Scope1.Rewrite(), System.Linq.Expressions.ScopeN.Rewrite(), and System.Linq.Expressions.ScopeWithType.Rewrite().