Terraria: System.Linq.Expressions.Expression.ReduceAndCheck
ReduceAndCheck()
Expression System.Linq.Expressions.Expression< TDelegate >.ReduceAndCheck () inline inherited
Definition at line 2539 of file Expression.cs.
    {
        if (!CanReduce)
        {
            throw Error.MustBeReducible();
        }
        Expression expression = Reduce();
        if (expression == null || expression == this)
        {
            throw Error.MustReduceToDifferent();
        }
        if (!TypeUtils.AreReferenceAssignable(Type, expression.Type))
        {
            throw Error.ReducedNotCompatible();
        }
        return expression;
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Expression< TDelegate >.CanReduce, System.Linq.Expressions.Error.MustBeReducible(), System.Linq.Expressions.Error.MustReduceToDifferent(), System.Linq.Expressions.Expression< TDelegate >.Reduce(), and System.Linq.Expressions.Error.ReducedNotCompatible().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileNoLabelPush(), and System.Linq.Expressions.Expression< TDelegate >.VisitChildren().