Terraria: System.Linq.Expressions.Expression.ReferenceEqual
ReferenceEqual()
static BinaryExpression System.Linq.Expressions.Expression< TDelegate >.ReferenceEqual (Expression< TDelegate > left, Expression< TDelegate > right) inline static inherited
Definition at line 1051 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(left, "left");
        ExpressionUtils.RequiresCanRead(right, "right");
        if (TypeUtils.HasReferenceEquality(left.Type, right.Type))
        {
            return new LogicalBinaryExpression(ExpressionType.Equal, left, right);
        }
        throw Error.ReferenceEqualityNotDefined(left.Type, right.Type);
    }
References System.Dynamic.Utils.TypeUtils.HasReferenceEquality(), System.Linq.Expressions.Error.ReferenceEqualityNotDefined(), and System.Dynamic.Utils.ExpressionUtils.RequiresCanRead().
Referenced by System.Linq.Expressions.TypeBinaryExpression.ByValParameterTypeEqual(), and System.Linq.Expressions.BinaryExpression.Update().