Terraria: System.Linq.Expressions.Expression.Invoke
Invoke() [1/8]
static InvocationExpression System.Linq.Expressions.Expression< TDelegate >.Invoke (Expression< TDelegate > expression) inline static package inherited
Definition at line 3096 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(expression, "expression");
        MethodInfo invokeMethod = GetInvokeMethod(expression);
        ParameterInfo[] parametersForValidation = GetParametersForValidation(invokeMethod, ExpressionType.Invoke);
        ValidateArgumentCount(invokeMethod, ExpressionType.Invoke, 0, parametersForValidation);
        return new InvocationExpression0(expression, invokeMethod.ReturnType);
    }
References System.Linq.Expressions.Expression< TDelegate >.GetInvokeMethod(), System.Linq.Expressions.Expression< TDelegate >.GetParametersForValidation(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), and System.Linq.Expressions.Expression< TDelegate >.ValidateArgumentCount().
Referenced by System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Linq.Expressions.DynamicExpression.Reduce(), System.Linq.Expressions.BinaryExpression.ReduceIndex(), System.Linq.Expressions.BinaryExpression.ReduceMember(), System.Linq.Expressions.BinaryExpression.ReduceVariable(), System.Linq.Expressions.InvocationExpression0.Rewrite(), System.Linq.Expressions.InvocationExpression1.Rewrite(), System.Linq.Expressions.InvocationExpression2.Rewrite(), System.Linq.Expressions.InvocationExpression3.Rewrite(), System.Linq.Expressions.InvocationExpression4.Rewrite(), System.Linq.Expressions.InvocationExpression5.Rewrite(), System.Linq.Expressions.InvocationExpressionN.Rewrite(), System.Runtime.CompilerServices.CallSiteBinder.Stitch< T >(), System.Linq.Expressions.InvocationExpression.Update(), and System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitRuntimeVariables().