Terraria: System.Linq.Expressions.Expression.Compile
Compile() [1/3]
new TDelegate System.Linq.Expressions.Expression< TDelegate >.Compile () inline inherited
Definition at line 5494 of file Expression.cs.
    {
        return (TDelegate)(object)LambdaCompiler.Compile(this);
    }
References System.Linq.Expressions.Compiler.LambdaCompiler.Compile().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Compile(), and System.Linq.Expressions.Expression< TDelegate >.Compile().