Terraria: System.Linq.Expressions.Expression.FindProperty
FindProperty()
static PropertyInfo System.Linq.Expressions.Expression< TDelegate >.FindProperty ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.NonPublicProperties)] Type type, string propertyName, Expression< TDelegate >[] arguments, BindingFlags flags) inline static private inherited
Definition at line 2870 of file Expression.cs.
    {
        PropertyInfo propertyInfo = null;
        PropertyInfo[] properties = type.GetProperties(flags);
        foreach (PropertyInfo propertyInfo2 in properties)
        {
            if (propertyInfo2.Name.Equals(propertyName, StringComparison.OrdinalIgnoreCase) && IsCompatible(propertyInfo2, arguments))
            {
                if (!(propertyInfo == null))
                {
                    throw Error.PropertyWithMoreThanOneMatch(propertyName, type);
                }
                propertyInfo = propertyInfo2;
            }
        }
        return propertyInfo;
    }
References System.Linq.Expressions.Expression< TDelegate >.IsCompatible(), System.Linq.Expressions.Error.PropertyWithMoreThanOneMatch(), and System.type.
Referenced by System.Linq.Expressions.Expression< TDelegate >.FindInstanceProperty().