Terraria: System.Linq.Expressions.Expression.Field
Field() [3/3]
static MemberExpression System.Linq.Expressions.Expression< TDelegate >.Field (Expression< TDelegate >? expression, FieldInfo field) inline static inherited
Definition at line 3658 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(field, "field");
        if (field.IsStatic)
        {
            if (expression != null)
            {
                throw Error.OnlyStaticFieldsHaveNullInstance("expression");
            }
        }
        else
        {
            if (expression == null)
            {
                throw Error.OnlyStaticFieldsHaveNullInstance("field");
            }
            ExpressionUtils.RequiresCanRead(expression, "expression");
            if (!TypeUtils.AreReferenceAssignable(field.DeclaringType, expression.Type))
            {
                throw Error.FieldInfoNotDefinedForType(field.DeclaringType, field.Name, expression.Type);
            }
        }
        return MemberExpression.Make(expression, field);
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Error.FieldInfoNotDefinedForType(), System.Linq.Expressions.MemberExpression.Make(), System.Linq.Expressions.Error.OnlyStaticFieldsHaveNullInstance(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), and System.Dynamic.Utils.ContractUtils.RequiresNotNull().
Referenced by System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType< TObj, TParam >(), System.Linq.Expressions.Utils.GetStrongBoxValueField(), and System.Linq.Expressions.DynamicExpression.Reduce().