Terraria: System.Linq.Expressions.Expression.GetInvokeMethod
GetInvokeMethod()
static MethodInfo System.Linq.Expressions.Expression< TDelegate >.GetInvokeMethod (Expression< TDelegate > expression) inline static package inherited
Definition at line 3198 of file Expression.cs.
    {
        Type delegateType = expression.Type;
        if (!expression.Type.IsSubclassOf(typeof(MulticastDelegate)))
        {
            Type type = TypeUtils.FindGenericType(typeof(Expression<>), expression.Type);
            if (type == null)
            {
                throw Error.ExpressionTypeNotInvocable(expression.Type, "expression");
            }
            delegateType = type.GetGenericArguments()[0];
        }
        return delegateType.GetInvokeMethod();
    }
References System.Linq.Expressions.Error.ExpressionTypeNotInvocable(), System.Dynamic.Utils.TypeUtils.FindGenericType(), and System.type.
Referenced by System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), and System.Linq.Expressions.Compiler.StackSpiller.RewriteInvocationExpression().