Terraria: System.Linq.Expressions.Expression.Goto
Goto() [1/4]
static GotoExpression System.Linq.Expressions.Expression< TDelegate >.Goto (LabelTarget target) inline static inherited
Definition at line 2732 of file Expression.cs.
    {
        return MakeGoto(GotoExpressionKind.Goto, target, null, typeof(void));
    }
References System.Linq.Expressions.Expression< TDelegate >.MakeGoto().
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), and System.Dynamic.DynamicMetaObjectBinder.GetUpdateExpression().