Terraria: System.Linq.Expressions.Expression.GetUserDefinedBinaryOperator
GetUserDefinedBinaryOperator() [2/2]
static MethodInfo System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperator (ExpressionType binaryType, Type leftType, Type rightType, string name) inline static private inherited
Definition at line 818 of file Expression.cs.
    {
        Type[] types = new Type[2] { leftType, rightType };
        Type nonNullableType = leftType.GetNonNullableType();
        Type nonNullableType2 = rightType.GetNonNullableType();
        MethodInfo methodInfo = nonNullableType.GetAnyStaticMethodValidated(name, types);
        if (methodInfo == null && !TypeUtils.AreEquivalent(leftType, rightType))
        {
            methodInfo = nonNullableType2.GetAnyStaticMethodValidated(name, types);
        }
        if (IsLiftingConditionalLogicalOperator(leftType, rightType, methodInfo, binaryType))
        {
            methodInfo = GetUserDefinedBinaryOperator(binaryType, nonNullableType, nonNullableType2, name);
        }
        return methodInfo;
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Linq.Expressions.Expression< TDelegate >.GetUserDefinedBinaryOperator(), and System.Linq.Expressions.Expression< TDelegate >.IsLiftingConditionalLogicalOperator().