Terraria: System.Linq.Expressions.Expression.IsCompatible
IsCompatible() [2/2]
static bool System.Linq.Expressions.Expression< TDelegate >.IsCompatible (PropertyInfo pi, Expression< TDelegate >[] args) inline static private inherited
Definition at line 2888 of file Expression.cs.
    {
        MethodInfo getMethod = pi.GetGetMethod(nonPublic: true);
        ParameterInfo[] array;
        if (getMethod != null)
        {
            array = getMethod.GetParametersCached();
        }
        else
        {
            getMethod = pi.GetSetMethod(nonPublic: true);
            if (getMethod == null)
            {
                return false;
            }
            array = getMethod.GetParametersCached();
            if (array.Length == 0)
            {
                return false;
            }
            array = array.RemoveLast();
        }
        if (args == null)
        {
            return array.Length == 0;
        }
        if (array.Length != args.Length)
        {
            return false;
        }
        for (int i = 0; i < args.Length; i++)
        {
            if (args[i] == null)
            {
                return false;
            }
            if (!TypeUtils.AreReferenceAssignable(array[i].ParameterType, args[i].Type))
            {
                return false;
            }
        }
        return true;
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), and System.array.
Referenced by System.Linq.Expressions.Expression< TDelegate >.FindMethod(), and System.Linq.Expressions.Expression< TDelegate >.FindProperty().