Terraria: System.Linq.Expressions.Expression.RequiresCanRead
RequiresCanRead()
static void System.Linq.Expressions.Expression< TDelegate >.RequiresCanRead (IReadOnlyList< Expression< TDelegate > > items, string paramName) inline static private inherited
Definition at line 2572 of file Expression.cs.
    {
        int i = 0;
        for (int count = items.Count; i < count; i++)
        {
            ExpressionUtils.RequiresCanRead(items[i], paramName, i);
        }
    }
References System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Dynamic.Utils.ExpressionUtils.RequiresCanRead().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.ElementInit(), and System.Linq.Expressions.Expression< TDelegate >.SwitchCase().