Terraria: System.Linq.Expressions.Expression.Call
Call() [9/16]
static MethodCallExpression System.Linq.Expressions.Expression< TDelegate >.Call (MethodInfo method) inline static package inherited
Definition at line 3992 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(method, "method");
        ParameterInfo[] pis = ValidateMethodAndGetParameters(null, method);
        ValidateArgumentCount(method, ExpressionType.Call, 0, pis);
        return new MethodCallExpression0(method);
    }
References System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Expression< TDelegate >.ValidateArgumentCount(), and System.Linq.Expressions.Expression< TDelegate >.ValidateMethodAndGetParameters().
Referenced by System.Dynamic.ExpandoObject.MetaExpando.AddDynamicTestAndDefer(), System.Linq.Queryable.Aggregate< TSource >(), System.Linq.Queryable.Aggregate< TSource, TAccumulate >(), System.Linq.Queryable.Aggregate< TSource, TAccumulate, TResult >(), System.Linq.Queryable.All< TSource >(), System.Linq.Queryable.Any< TSource >(), System.Linq.Queryable.Any< TSource >(), System.Linq.Queryable.Append< TSource >(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Linq.Queryable.Average< TSource >(), System.Dynamic.ExpandoObject.MetaExpando.BindDeleteMember(), System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember(), System.Dynamic.ExpandoObject.MetaExpando.BindSetMember(), System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Linq.Expressions.TypeBinaryExpression.ByValParameterTypeEqual(), System.Linq.Expressions.BinaryExpression.CallGetValueOrDefault(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodReturnLast< TBinder >(), System.Linq.Expressions.Compiler.LambdaCompiler.CallTryGetValue(), System.Linq.Queryable.Cast< TResult >(), System.Linq.Queryable.Chunk< TSource >(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileInvocationExpression(), System.Linq.Queryable.Concat< TSource >(), System.Linq.Queryable.Contains< TSource >(), System.Linq.Queryable.Contains< TSource >(), System.Linq.Queryable.Count< TSource >(), System.Linq.Queryable.Count< TSource >(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomNoMatchDelegate(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Linq.Queryable.DefaultIfEmpty< TSource >(), System.Linq.Queryable.DefaultIfEmpty< TSource >(), System.Linq.Queryable.Distinct< TSource >(), System.Linq.Queryable.Distinct< TSource >(), System.Linq.Queryable.DistinctBy< TSource, TKey >(), System.Linq.Queryable.DistinctBy< TSource, TKey >(), System.Linq.Queryable.ElementAt< TSource >(), System.Linq.Queryable.ElementAt< TSource >(), System.Linq.Queryable.ElementAtOrDefault< TSource >(), System.Linq.Queryable.ElementAtOrDefault< TSource >(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinaryMethod(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvert(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitInvocationExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryMethod(), System.Linq.Queryable.Except< TSource >(), System.Linq.Queryable.Except< TSource >(), System.Linq.Queryable.ExceptBy< TSource, TKey >(), System.Linq.Queryable.ExceptBy< TSource, TKey >(), System.Linq.Queryable.First< TSource >(), System.Linq.Queryable.First< TSource >(), System.Linq.Queryable.FirstOrDefault< TSource >(), System.Linq.Queryable.FirstOrDefault< TSource >(), System.Linq.Queryable.FirstOrDefault< TSource >(), System.Linq.Queryable.FirstOrDefault< TSource >(), System.Linq.Queryable.GroupBy< TSource, TKey >(), System.Linq.Queryable.GroupBy< TSource, TKey >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement, TResult >(), System.Linq.Queryable.GroupBy< TSource, TKey, TElement, TResult >(), System.Linq.Queryable.GroupBy< TSource, TKey, TResult >(), System.Linq.Queryable.GroupBy< TSource, TKey, TResult >(), System.Linq.Queryable.GroupJoin< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.GroupJoin< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.Intersect< TSource >(), System.Linq.Queryable.Intersect< TSource >(), System.Linq.Queryable.IntersectBy< TSource, TKey >(), System.Linq.Queryable.IntersectBy< TSource, TKey >(), System.Linq.Queryable.Join< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.Join< TOuter, TInner, TKey, TResult >(), System.Linq.Queryable.Last< TSource >(), System.Linq.Queryable.Last< TSource >(), System.Linq.Queryable.LastOrDefault< TSource >(), System.Linq.Queryable.LastOrDefault< TSource >(), System.Linq.Queryable.LastOrDefault< TSource >(), System.Linq.Queryable.LastOrDefault< TSource >(), System.Linq.Queryable.LongCount< TSource >(), System.Linq.Queryable.LongCount< TSource >(), System.Linq.Queryable.Max< TSource >(), System.Linq.Queryable.Max< TSource >(), System.Linq.Queryable.Max< TSource, TResult >(), System.Linq.Queryable.MaxBy< TSource, TKey >(), System.Linq.Queryable.MaxBy< TSource, TKey >(), System.Linq.Queryable.Min< TSource >(), System.Linq.Queryable.Min< TSource >(), System.Linq.Queryable.Min< TSource, TResult >(), System.Linq.Queryable.MinBy< TSource, TKey >(), System.Linq.Queryable.MinBy< TSource, TKey >(), System.Linq.Queryable.OfType< TResult >(), System.Linq.Queryable.OrderBy< TSource, TKey >(), System.Linq.Queryable.OrderBy< TSource, TKey >(), System.Linq.Queryable.OrderByDescending< TSource, TKey >(), System.Linq.Queryable.OrderByDescending< TSource, TKey >(), System.Linq.Queryable.Prepend< TSource >(), System.Linq.Expressions.MemberInitExpression.ReduceListInit(), System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted(), System.Linq.Queryable.Reverse< TSource >(), System.Linq.Expressions.InstanceMethodCallExpression0.Rewrite(), System.Linq.Expressions.InstanceMethodCallExpression1.Rewrite(), System.Linq.Expressions.InstanceMethodCallExpression2.Rewrite(), System.Linq.Expressions.InstanceMethodCallExpression3.Rewrite(), System.Linq.Expressions.InstanceMethodCallExpressionN.Rewrite(), System.Linq.Expressions.MethodCallExpression0.Rewrite(), System.Linq.Expressions.MethodCallExpression1.Rewrite(), System.Linq.Expressions.MethodCallExpression2.Rewrite(), System.Linq.Expressions.MethodCallExpression3.Rewrite(), System.Linq.Expressions.MethodCallExpression4.Rewrite(), System.Linq.Expressions.MethodCallExpression5.Rewrite(), System.Linq.Expressions.MethodCallExpressionN.Rewrite(), System.Linq.Queryable.Select< TSource, TResult >(), System.Linq.Queryable.Select< TSource, TResult >(), System.Linq.Queryable.SelectMany< TSource, TCollection, TResult >(), System.Linq.Queryable.SelectMany< TSource, TCollection, TResult >(), System.Linq.Queryable.SelectMany< TSource, TResult >(), System.Linq.Queryable.SelectMany< TSource, TResult >(), System.Linq.Queryable.SequenceEqual< TSource >(), System.Linq.Queryable.SequenceEqual< TSource >(), System.Linq.Queryable.Single< TSource >(), System.Linq.Queryable.Single< TSource >(), System.Linq.Queryable.SingleOrDefault< TSource >(), System.Linq.Queryable.SingleOrDefault< TSource >(), System.Linq.Queryable.SingleOrDefault< TSource >(), System.Linq.Queryable.SingleOrDefault< TSource >(), System.Linq.Queryable.Skip< TSource >(), System.Linq.Queryable.SkipLast< TSource >(), System.Linq.Queryable.SkipWhile< TSource >(), System.Linq.Queryable.SkipWhile< TSource >(), System.Runtime.CompilerServices.CallSiteBinder.Stitch< T >(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Sum< TSource >(), System.Linq.Queryable.Take< TSource >(), System.Linq.Queryable.Take< TSource >(), System.Linq.Queryable.TakeLast< TSource >(), System.Linq.Queryable.TakeWhile< TSource >(), System.Linq.Queryable.TakeWhile< TSource >(), System.Linq.Queryable.ThenBy< TSource, TKey >(), System.Linq.Queryable.ThenBy< TSource, TKey >(), System.Linq.Queryable.ThenByDescending< TSource, TKey >(), System.Linq.Queryable.ThenByDescending< TSource, TKey >(), System.Linq.Queryable.Union< TSource >(), System.Linq.Queryable.Union< TSource >(), System.Linq.Queryable.UnionBy< TSource, TKey >(), System.Linq.Queryable.UnionBy< TSource, TKey >(), System.Linq.Expressions.MethodCallExpression.Update(), System.Linq.EnumerableRewriter.VisitMethodCall(), System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitRuntimeVariables(), System.Linq.Queryable.Where< TSource >(), System.Linq.Queryable.Where< TSource >(), System.Linq.Queryable.Zip< TFirst, TSecond >(), System.Linq.Queryable.Zip< TFirst, TSecond, TResult >(), and System.Linq.Queryable.Zip< TFirst, TSecond, TThird >().