Terraria: System.Linq.Expressions.Expression.Convert
Convert() [1/2]
static UnaryExpression System.Linq.Expressions.Expression< TDelegate >.Convert (Expression< TDelegate > expression, Type type) inline static inherited
Definition at line 5280 of file Expression.cs.
    {
        return Convert(expression, type, null);
    }
References System.Linq.Expressions.Convert, and System.type.
Referenced by System.Dynamic.ExpandoObject.MetaExpando.BindSetMember(), System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodReturnLast< TBinder >(), System.Runtime.CompilerServices.CallSite< T >.Convert(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvert(), System.Dynamic.DynamicObject.MetaDynamic.GetConvertedArgs(), System.Dynamic.BindingRestrictions.InstanceRestriction.GetExpression(), System.Dynamic.DynamicObject.MetaDynamic.GetLimitedSelf(), System.Dynamic.ExpandoObject.MetaExpando.GetLimitedSelf(), System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted(), System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign(), System.Runtime.CompilerServices.CallSiteBinder.Stitch< T >(), and System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitParameter().