Terraria: System.Linq.Expressions.Expression.ValidateAccessor
ValidateAccessor()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateAccessor (Expression< TDelegate > instance, MethodInfo method, ParameterInfo[] indexes, ref ReadOnlyCollection< Expression< TDelegate > > arguments, string paramName) inline static private inherited
Definition at line 3020 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(arguments, "arguments");
        ValidateMethodInfo(method, "method");
        if ((method.CallingConvention & CallingConventions.VarArgs) != 0)
        {
            throw Error.AccessorsCannotHaveVarArgs(paramName);
        }
        if (method.IsStatic)
        {
            if (instance != null)
            {
                throw Error.OnlyStaticPropertiesHaveNullInstance("instance");
            }
        }
        else
        {
            if (instance == null)
            {
                throw Error.OnlyStaticPropertiesHaveNullInstance("instance");
            }
            ExpressionUtils.RequiresCanRead(instance, "instance");
            ValidateCallInstanceType(instance.Type, method);
        }
        ValidateAccessorArgumentTypes(method, indexes, ref arguments, paramName);
    }
References System.Linq.Expressions.Error.AccessorsCannotHaveVarArgs(), System.Linq.Expressions.Error.OnlyStaticPropertiesHaveNullInstance(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Expression< TDelegate >.ValidateAccessorArgumentTypes(), System.Linq.Expressions.Expression< TDelegate >.ValidateCallInstanceType(), and System.Linq.Expressions.Expression< TDelegate >.ValidateMethodInfo().
Referenced by System.Linq.Expressions.Expression< TDelegate >.ValidateIndexedProperty().