Terraria: System.Linq.Expressions.Expression.ValidateUserDefinedConditionalLogicOperator
ValidateUserDefinedConditionalLogicOperator()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateUserDefinedConditionalLogicOperator (ExpressionType nodeType, Type left, Type right, MethodInfo method) inline static private inherited
Definition at line 913 of file Expression.cs.
    {
        ValidateOperator(method);
        ParameterInfo[] parametersCached = method.GetParametersCached();
        if (parametersCached.Length != 2)
        {
            throw Error.IncorrectNumberOfMethodCallArguments(method, "method");
        }
        if (!ParameterIsAssignable(parametersCached[0], left) && (!left.IsNullableType() || !ParameterIsAssignable(parametersCached[0], left.GetNonNullableType())))
        {
            throw Error.OperandTypesDoNotMatchParameters(nodeType, method.Name);
        }
        if (!ParameterIsAssignable(parametersCached[1], right) && (!right.IsNullableType() || !ParameterIsAssignable(parametersCached[1], right.GetNonNullableType())))
        {
            throw Error.OperandTypesDoNotMatchParameters(nodeType, method.Name);
        }
        if (parametersCached[0].ParameterType != parametersCached[1].ParameterType)
        {
            throw Error.UserDefinedOpMustHaveConsistentTypes(nodeType, method.Name);
        }
        if (method.ReturnType != parametersCached[0].ParameterType)
        {
            throw Error.UserDefinedOpMustHaveConsistentTypes(nodeType, method.Name);
        }
        if (IsValidLiftedConditionalLogicalOperator(left, right, parametersCached))
        {
            left = left.GetNonNullableType();
        }
        Type declaringType = method.DeclaringType;
        if (declaringType == null)
        {
            throw Error.LogicalOperatorMustHaveBooleanOperators(nodeType, method.Name);
        }
        MethodInfo booleanOperator = TypeUtils.GetBooleanOperator(declaringType, "op_True");
        MethodInfo booleanOperator2 = TypeUtils.GetBooleanOperator(declaringType, "op_False");
        if (booleanOperator == null || booleanOperator.ReturnType != typeof(bool) || booleanOperator2 == null || booleanOperator2.ReturnType != typeof(bool))
        {
            throw Error.LogicalOperatorMustHaveBooleanOperators(nodeType, method.Name);
        }
        VerifyOpTrueFalse(nodeType, left, booleanOperator2, "method");
        VerifyOpTrueFalse(nodeType, left, booleanOperator, "method");
    }
References System.Dynamic.Utils.TypeUtils.GetBooleanOperator(), System.Linq.Expressions.Error.IncorrectNumberOfMethodCallArguments(), System.Linq.Expressions.Expression< TDelegate >.IsValidLiftedConditionalLogicalOperator(), System.Linq.Expressions.Error.LogicalOperatorMustHaveBooleanOperators(), System.Linq.Expressions.Error.OperandTypesDoNotMatchParameters(), System.Linq.Expressions.Expression< TDelegate >.ParameterIsAssignable(), System.Linq.Expressions.Error.UserDefinedOpMustHaveConsistentTypes(), System.Linq.Expressions.Expression< TDelegate >.ValidateOperator(), and System.Linq.Expressions.Expression< TDelegate >.VerifyOpTrueFalse().
Referenced by System.Linq.Expressions.Expression< TDelegate >.AndAlso(), and System.Linq.Expressions.Expression< TDelegate >.OrElse().