Terraria: System.Linq.Expressions.Expression.Bind
Bind() [1/2]
static MemberAssignment System.Linq.Expressions.Expression< TDelegate >.Bind (MemberInfo member, Expression< TDelegate > expression) inline static inherited
Definition at line 3611 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(member, "member");
        ExpressionUtils.RequiresCanRead(expression, "expression");
        ValidateSettableFieldOrPropertyMember(member, out var memberType);
        if (!memberType.IsAssignableFrom(expression.Type))
        {
            throw Error.ArgumentTypesMustMatch();
        }
        return new MemberAssignment(member, expression);
    }
References System.Linq.Expressions.Error.ArgumentTypesMustMatch(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), and System.Linq.Expressions.Expression< TDelegate >.ValidateSettableFieldOrPropertyMember().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Bind(), and System.Linq.Expressions.MemberAssignment.Update().