Terraria: System.Linq.Expressions.Expression.RequiresCanWrite
RequiresCanWrite()
static void System.Linq.Expressions.Expression< TDelegate >.RequiresCanWrite (Expression< TDelegate > expression, string paramName) inline static private inherited
Definition at line 2581 of file Expression.cs.
    {
        if (expression == null)
        {
            throw new ArgumentNullException(paramName);
        }
        switch (expression.NodeType)
        {
        case ExpressionType.Index:
        {
            PropertyInfo indexer = ((IndexExpression)expression).Indexer;
            if (indexer == null || indexer.CanWrite)
            {
                return;
            }
            break;
        }
        case ExpressionType.MemberAccess:
        {
            MemberInfo member = ((MemberExpression)expression).Member;
            if (member is PropertyInfo propertyInfo)
            {
                if (propertyInfo.CanWrite)
                {
                    return;
                }
                break;
            }
            FieldInfo fieldInfo = (FieldInfo)member;
            if (!fieldInfo.IsInitOnly && !fieldInfo.IsLiteral)
            {
                return;
            }
            break;
        }
        case ExpressionType.Parameter:
            return;
        }
        throw Error.ExpressionMustBeWriteable(paramName);
    }
References System.Linq.Expressions.Error.ExpressionMustBeWriteable().
Referenced by System.Linq.Expressions.Expression< TDelegate >.AddAssign(), System.Linq.Expressions.Expression< TDelegate >.AddAssignChecked(), System.Linq.Expressions.Expression< TDelegate >.AndAssign(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.DivideAssign(), System.Linq.Expressions.Expression< TDelegate >.ExclusiveOrAssign(), System.Linq.Expressions.Expression< TDelegate >.LeftShiftAssign(), System.Linq.Expressions.Expression< TDelegate >.MakeOpAssignUnary(), System.Linq.Expressions.Expression< TDelegate >.ModuloAssign(), System.Linq.Expressions.Expression< TDelegate >.MultiplyAssign(), System.Linq.Expressions.Expression< TDelegate >.MultiplyAssignChecked(), System.Linq.Expressions.Expression< TDelegate >.OrAssign(), System.Linq.Expressions.Expression< TDelegate >.PowerAssign(), System.Linq.Expressions.Expression< TDelegate >.RightShiftAssign(), System.Linq.Expressions.Expression< TDelegate >.SubtractAssign(), and System.Linq.Expressions.Expression< TDelegate >.SubtractAssignChecked().