Terraria: System.Linq.Expressions.Expression.MakeCatchBlock
MakeCatchBlock()
static CatchBlock System.Linq.Expressions.Expression< TDelegate >.MakeCatchBlock (Type type, ParameterExpression< TDelegate >? variable, Expression< TDelegate > body, Expression< TDelegate >? filter) inline static inherited
Definition at line 2301 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(type, "type");
        ContractUtils.Requires(variable == null || TypeUtils.AreEquivalent(variable.Type, type), "variable");
        if (variable == null)
        {
            TypeUtils.ValidateType(type, "type");
        }
        else if (variable.IsByRef)
        {
            throw Error.VariableMustNotBeByRef(variable, variable.Type, "variable");
        }
        ExpressionUtils.RequiresCanRead(body, "body");
        if (filter != null)
        {
            ExpressionUtils.RequiresCanRead(filter, "filter");
            if (filter.Type != typeof(bool))
            {
                throw Error.ArgumentMustBeBoolean("filter");
            }
        }
        return new CatchBlock(type, variable, body, filter);
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Linq.Expressions.Error.ArgumentMustBeBoolean(), System.Dynamic.Utils.ContractUtils.Requires(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.type, System.Dynamic.Utils.TypeUtils.ValidateType(), and System.Linq.Expressions.Error.VariableMustNotBeByRef().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Catch(), System.Linq.Expressions.Expression< TDelegate >.Catch(), System.Linq.Expressions.Expression< TDelegate >.Catch(), System.Linq.Expressions.Expression< TDelegate >.Catch(), System.Linq.Expressions.Compiler.StackSpiller.RewriteTryExpression(), System.Linq.Expressions.CatchBlock.Update(), System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitCatchBlock(), and System.Runtime.CompilerServices.RuntimeOps.ExpressionQuoter.VisitCatchBlock().