Terraria: System.Linq.Expressions.Expression.Coalesce
Coalesce() [2/2]
static BinaryExpression System.Linq.Expressions.Expression< TDelegate >.Coalesce (Expression< TDelegate > left, Expression< TDelegate > right, LambdaExpression< TDelegate >? conversion) inline static inherited
Definition at line 1271 of file Expression.cs.
    {
        ExpressionUtils.RequiresCanRead(left, "left");
        ExpressionUtils.RequiresCanRead(right, "right");
        if (conversion == null)
        {
            Type type = ValidateCoalesceArgTypes(left.Type, right.Type);
            return new SimpleBinaryExpression(ExpressionType.Coalesce, left, right, type);
        }
        if (left.Type.IsValueType && !left.Type.IsNullableType())
        {
            throw Error.CoalesceUsedOnNonNullType();
        }
        Type type2 = conversion.Type;
        MethodInfo invokeMethod = type2.GetInvokeMethod();
        if (invokeMethod.ReturnType == typeof(void))
        {
            throw Error.UserDefinedOperatorMustNotBeVoid(conversion, "conversion");
        }
        ParameterInfo[] parametersCached = invokeMethod.GetParametersCached();
        if (parametersCached.Length != 1)
        {
            throw Error.IncorrectNumberOfMethodCallArguments(conversion, "conversion");
        }
        if (!TypeUtils.AreEquivalent(invokeMethod.ReturnType, right.Type))
        {
            throw Error.OperandTypesDoNotMatchParameters(ExpressionType.Coalesce, conversion.ToString());
        }
        if (!ParameterIsAssignable(parametersCached[0], left.Type.GetNonNullableType()) && !ParameterIsAssignable(parametersCached[0], left.Type))
        {
            throw Error.OperandTypesDoNotMatchParameters(ExpressionType.Coalesce, conversion.ToString());
        }
        return new CoalesceConversionBinaryExpression(left, right, conversion);
    }
References System.Dynamic.Utils.TypeUtils.AreEquivalent(), System.Linq.Expressions.Error.CoalesceUsedOnNonNullType(), System.Linq.Expressions.Error.IncorrectNumberOfMethodCallArguments(), System.Linq.Expressions.Error.OperandTypesDoNotMatchParameters(), System.Linq.Expressions.Expression< TDelegate >.ParameterIsAssignable(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.type, System.Linq.Expressions.Error.UserDefinedOperatorMustNotBeVoid(), and System.Linq.Expressions.Expression< TDelegate >.ValidateCoalesceArgTypes().