Terraria: System.Linq.Expressions.Expression.Parameter
Parameter() [1/2]
static ParameterExpression System.Linq.Expressions.Expression< TDelegate >.Parameter (Type type) inline static inherited
Definition at line 4660 of file Expression.cs.
    {
        return Parameter(type, null);
    }
References System.Linq.Expressions.Parameter, and System.type.
Referenced by System.Runtime.CompilerServices.CallSiteBinder.LambdaSignature< T >.LambdaSignature(), System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember(), System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Linq.Expressions.TypeBinaryExpression.ByValParameterTypeEqual(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodReturnLast< TBinder >(), System.Linq.Expressions.Interpreter.LightCompiler.CompileAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileArrayIndexAddress(), System.Linq.Expressions.Interpreter.LightCompiler.CompileBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileCoalesceBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConvertUnaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileIndexAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileLiftedLogicalBinaryExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMemberAssignment(), System.Linq.Expressions.Interpreter.LightCompiler.CompileMultiDimArrayAccess(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileTryExpression(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomNoMatchDelegate(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchExpression(), System.Dynamic.BindingRestrictions.InstanceRestriction.GetExpression(), System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType< TObj, TParam >(), System.Linq.Expressions.UnaryExpression.ReduceIndex(), System.Linq.Expressions.UnaryExpression.ReduceMember(), System.Linq.Expressions.TypeBinaryExpression.ReduceTypeEqual(), System.Linq.Expressions.BinaryExpression.ReduceUserdefinedLifted(), System.Linq.Expressions.UnaryExpression.ReduceVariable(), and System.Runtime.CompilerServices.CallSiteBinder.Stitch< T >().