Terraria: System.Linq.Expressions.Expression.ValidateIndexedProperty
ValidateIndexedProperty()
static void System.Linq.Expressions.Expression< TDelegate >.ValidateIndexedProperty (Expression< TDelegate > instance, PropertyInfo indexer, string paramName, ref ReadOnlyCollection< Expression< TDelegate > > argList) inline static private inherited
Definition at line 2948 of file Expression.cs.
    {
        ContractUtils.RequiresNotNull(indexer, paramName);
        if (indexer.PropertyType.IsByRef)
        {
            throw Error.PropertyCannotHaveRefType(paramName);
        }
        if (indexer.PropertyType == typeof(void))
        {
            throw Error.PropertyTypeCannotBeVoid(paramName);
        }
        ParameterInfo[] array = null;
        MethodInfo getMethod = indexer.GetGetMethod(nonPublic: true);
        if (getMethod != null)
        {
            if (getMethod.ReturnType != indexer.PropertyType)
            {
                throw Error.PropertyTypeMustMatchGetter(paramName);
            }
            array = getMethod.GetParametersCached();
            ValidateAccessor(instance, getMethod, array, ref argList, paramName);
        }
        MethodInfo setMethod = indexer.GetSetMethod(nonPublic: true);
        if (setMethod != null)
        {
            ParameterInfo[] parametersCached = setMethod.GetParametersCached();
            if (parametersCached.Length == 0)
            {
                throw Error.SetterHasNoParams(paramName);
            }
            Type parameterType = parametersCached[^1].ParameterType;
            if (parameterType.IsByRef)
            {
                throw Error.PropertyCannotHaveRefType(paramName);
            }
            if (setMethod.ReturnType != typeof(void))
            {
                throw Error.SetterMustBeVoid(paramName);
            }
            if (indexer.PropertyType != parameterType)
            {
                throw Error.PropertyTypeMustMatchSetter(paramName);
            }
            if (getMethod != null)
            {
                if (getMethod.IsStatic ^ setMethod.IsStatic)
                {
                    throw Error.BothAccessorsMustBeStatic(paramName);
                }
                if (array.Length != parametersCached.Length - 1)
                {
                    throw Error.IndexesOfSetGetMustMatch(paramName);
                }
                for (int i = 0; i < array.Length; i++)
                {
                    if (array[i].ParameterType != parametersCached[i].ParameterType)
                    {
                        throw Error.IndexesOfSetGetMustMatch(paramName);
                    }
                }
            }
            else
            {
                ValidateAccessor(instance, setMethod, parametersCached.RemoveLast(), ref argList, paramName);
            }
        }
        else if (getMethod == null)
        {
            throw Error.PropertyDoesNotHaveAccessor(indexer, paramName);
        }
    }
References System.array, System.Linq.Expressions.Error.BothAccessorsMustBeStatic(), System.Linq.Expressions.Error.IndexesOfSetGetMustMatch(), System.Linq.Expressions.Error.PropertyCannotHaveRefType(), System.Linq.Expressions.Error.PropertyDoesNotHaveAccessor(), System.Linq.Expressions.Error.PropertyTypeCannotBeVoid(), System.Linq.Expressions.Error.PropertyTypeMustMatchGetter(), System.Linq.Expressions.Error.PropertyTypeMustMatchSetter(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Linq.Expressions.Error.SetterHasNoParams(), System.Linq.Expressions.Error.SetterMustBeVoid(), and System.Linq.Expressions.Expression< TDelegate >.ValidateAccessor().
Referenced by System.Linq.Expressions.Expression< TDelegate >.MakeIndexProperty().