Terraria: System.Linq.Expressions.Expression.ValidateTryGetFuncActionArgs
ValidateTryGetFuncActionArgs()
static TryGetFuncActionArgsResult System.Linq.Expressions.Expression< TDelegate >.ValidateTryGetFuncActionArgs (Type[] typeArgs) inline static private inherited
Definition at line 3442 of file Expression.cs.
    {
        if (typeArgs == null)
        {
            return TryGetFuncActionArgsResult.ArgumentNull;
        }
        foreach (Type type in typeArgs)
        {
            if (type == null)
            {
                return TryGetFuncActionArgsResult.ArgumentNull;
            }
            if (type.IsByRef)
            {
                return TryGetFuncActionArgsResult.ByRef;
            }
            if (type == typeof(void) || type.IsPointer)
            {
                return TryGetFuncActionArgsResult.PointerOrVoid;
            }
        }
        return TryGetFuncActionArgsResult.Valid;
    }
References System.type.
Referenced by System.Linq.Expressions.Expression< TDelegate >.GetActionType(), System.Linq.Expressions.Expression< TDelegate >.GetFuncType(), System.Linq.Expressions.Expression< TDelegate >.TryGetActionType(), and System.Linq.Expressions.Expression< TDelegate >.TryGetFuncType().