Terraria: Terraria.GameContent.PotionOfReturnGateHelper.DrawToDrawData
DrawToDrawData()
void Terraria.GameContent.PotionOfReturnGateHelper.DrawToDrawData (List< DrawData > drawDataList, int selectionMode) inline
    {
        short num = (short)((_gateType == GateType.EntryPoint) ? 183 : 184);
        Asset<Texture2D> val = TextureAssets.Extra[num];
        Rectangle rectangle = val.Frame(1, 8, 0, _frameNumber);
        Color color = Lighting.GetColor(_position.ToTileCoordinates());
        color = Color.Lerp(color, Color.White, 0.5f);
        color *= _opacity;
        DrawData drawData = new DrawData(val.Value, _position - Main.screenPosition, rectangle, color, 0f, rectangle.Size() / 2f, 1f, SpriteEffects.None);
        drawDataList.Add(drawData);
        for (float num2 = 0f; num2 < 1f; num2 += 0.34f)
        {
            DrawData item = drawData;
            item.color = new Color(127, 50, 127, 0) * _opacity;
            item.scale *= 1.1f;
            float x = (Main.GlobalTimeWrappedHourly / 5f * ((float)Math.PI * 2f)).ToRotationVector2().X;
            item.color *= x * 0.1f + 0.3f;
            item.position += ((Main.GlobalTimeWrappedHourly / 5f + num2) * ((float)Math.PI * 2f)).ToRotationVector2() * (x * 1f + 2f);
            drawDataList.Add(item);
        }
        if (selectionMode != 0)
        {
            int num3 = (color.R + color.G + color.B) / 3;
            if (num3 > 10)
            {
                Color selectionGlowColor = Colors.GetSelectionGlowColor(selectionMode == 2, num3);
                Texture2D value = TextureAssets.Extra[242].Value;
                Rectangle value2 = value.Frame(1, 8, 0, _frameNumber);
                drawData = new DrawData(value, _position - Main.screenPosition, value2, selectionGlowColor, 0f, rectangle.Size() / 2f, 1f, SpriteEffects.None);
                drawDataList.Add(drawData);
            }
        }
    }
References Terraria.GameContent.PotionOfReturnGateHelper._frameNumber, Terraria.GameContent.PotionOfReturnGateHelper._gateType, Terraria.GameContent.PotionOfReturnGateHelper._opacity, Terraria.GameContent.PotionOfReturnGateHelper._position, Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Terraria.ID.Colors.GetSelectionGlowColor(), Terraria.Main.screenPosition, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld().