Terraria: System.Linq.EnumerableQuery.CreateQuery
CreateQuery()
IQueryable IQueryProvider. System.Linq.EnumerableQuery< T >.CreateQuery (Expression expression) inline private
Implements System.Linq.IQueryProvider.
Definition at line 62 of file EnumerableQuery.cs.
    {
        if (expression == null)
        {
            throw Error.ArgumentNull("expression");
        }
        Type type = TypeHelper.FindGenericType(typeof(IQueryable<>), expression.Type);
        if (type == null)
        {
            throw Error.ArgumentNotValid("expression");
        }
        return EnumerableQuery.Create(type.GetGenericArguments()[0], expression);
    }
References System.Linq.Error.ArgumentNotValid(), System.Linq.Error.ArgumentNull(), System.Linq.EnumerableQuery< T >.Create(), System.Linq.TypeHelper.FindGenericType(), and System.type.