Terraria: System.Net.WebClient.PostProgressChanged
PostProgressChanged()
void System.Net.WebClient.PostProgressChanged (AsyncOperation asyncOp, ProgressData progress) inline private
Definition at line 2146 of file WebClient.cs.
    {
        if (asyncOp == null || (progress.BytesSent <= 0 && progress.BytesReceived <= 0))
        {
            return;
        }
        if (progress.HasUploadPhase)
        {
            if (this.UploadProgressChanged != null)
            {
                int progressPercentage = (int)((progress.TotalBytesToReceive >= 0 || progress.BytesReceived != 0L) ? ((progress.TotalBytesToSend < 0) ? 50 : ((progress.TotalBytesToReceive == 0L) ? 100 : (50 * progress.BytesReceived / progress.TotalBytesToReceive + 50))) : ((progress.TotalBytesToSend >= 0) ? ((progress.TotalBytesToSend == 0L) ? 50 : (50 * progress.BytesSent / progress.TotalBytesToSend)) : 0));
                asyncOp.Post(_reportUploadProgressChanged, new UploadProgressChangedEventArgs(progressPercentage, asyncOp.UserSuppliedState, progress.BytesSent, progress.TotalBytesToSend, progress.BytesReceived, progress.TotalBytesToReceive));
            }
        }
        else if (this.DownloadProgressChanged != null)
        {
            int progressPercentage = (int)((progress.TotalBytesToReceive >= 0) ? ((progress.TotalBytesToReceive == 0L) ? 100 : (100 * progress.BytesReceived / progress.TotalBytesToReceive)) : 0);
            asyncOp.Post(_reportDownloadProgressChanged, new DownloadProgressChangedEventArgs(progressPercentage, asyncOp.UserSuppliedState, progress.BytesReceived, progress.TotalBytesToReceive));
        }
    }
References System.Net.WebClient._reportDownloadProgressChanged, System.Net.WebClient._reportUploadProgressChanged, System.Net.WebClient.ProgressData.BytesReceived, System.Net.WebClient.ProgressData.BytesSent, System.Net.WebClient.ProgressData.HasUploadPhase, System.L, System.ComponentModel.AsyncOperation.Post(), System.Net.WebClient.ProgressData.TotalBytesToReceive, System.Net.WebClient.ProgressData.TotalBytesToSend, and System.ComponentModel.AsyncOperation.UserSuppliedState.
Referenced by System.Net.WebClient.DownloadBitsAsync(), and System.Net.WebClient.UploadBitsAsync().