Terraria: CreditsRollComposer.PlaySegment_Grox_SkeletonMerchantSearchesThroughBones
PlaySegment_Grox_SkeletonMerchantSearchesThroughBones()
SegmentInforReport CreditsRollComposer.PlaySegment_Grox_SkeletonMerchantSearchesThroughBones (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         int num2 = 30;
         sceneAnchorPosition.X += num2;
         int num3 = 100;
         Asset<Texture2D> val = TextureAssets.Extra[220];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
             .Then(new Actions.Sprites.Wait(60));
         _segments.Add(animationSegmentWithActions);
         int num4 = 10;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 453, sceneAnchorPosition + new Vector2(num4, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 60));
         Asset<Texture2D> val2 = TextureAssets.Extra[227];
         DrawData data2 = new DrawData(val2.Value, Vector2.Zero, null, Color.White, 0f, val2.Size() * new Vector2(0.5f, 1f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions3 = new Segments.SpriteSegment(val2, startTime, data2, sceneAnchorPosition + new Vector2(num3, 2f)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51)).Then(new Actions.Sprites.Wait(60));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         int num5 = 90;
         Segments.EmoteSegment item = new Segments.EmoteSegment(87, num, num5, sceneAnchorPosition + new Vector2(60 + num4, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions3.Then(new Actions.Sprites.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         Asset<Texture2D> val3 = TextureAssets.Extra[228];
         Rectangle rectangle2 = val3.Frame(1, 14);
         DrawData data3 = new DrawData(val3.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, SpriteEffects.FlipHorizontally);
         Segments.SpriteSegment spriteSegment = new Segments.SpriteSegment(val3, num, data3, sceneAnchorPosition + new Vector2(num3 - 10, 4f));
         spriteSegment.Then(new Actions.Sprites.SetFrameSequence(new Point[4]
         {
             new Point(0, 1),
             new Point(0, 2),
             new Point(0, 3),
             new Point(0, 4)
         }, 5, 0, 0));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(20)).With(new Actions.NPCs.Fade(255));
         animationSegmentWithActions3.Then(new Actions.Sprites.Wait(20));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(20));
         num += 20;
         int num6 = 10;
         Main.instance.LoadItem(154);
         Asset<Texture2D> val4 = TextureAssets.Item[154];
         DrawData drawData = new DrawData(val4.Value, Vector2.Zero, null, Color.White, 0f, val4.Size() / 2f, 1f, SpriteEffects.None);
         Main.instance.LoadItem(1274);
         Asset<Texture2D> val5 = TextureAssets.Item[1274];
         DrawData drawData2 = new DrawData(val5.Value, Vector2.Zero, null, Color.White, 0f, val5.Size() / 2f, 1f, SpriteEffects.None);
         Vector2 anchorOffset = sceneAnchorPosition + new Vector2(num3, -8f);
         for (int i = 0; i < num6; i++)
         {
             Vector2 initialVelocity = Vector2.UnitY * -5f + Main.rand.NextVector2Circular(2.5f, 0.3f + Main.rand.NextFloat() * 0.2f).RotatedBy((float)(i - num6 / 2) * ((float)Math.PI * 2f) * 0.1f);
             Vector2 gravityPerFrame = Vector2.UnitY * 0.1f;
             int targetTime = num + i * 10;
             DrawData data4 = drawData;
             Asset<Texture2D> asset = val4;
             if (i == num6 - 3)
             {
                 data4 = drawData2;
                 asset = val5;
             }
             Segments.AnimationSegmentWithActions<Segments.LooseSprite> item2 = new Segments.SpriteSegment(asset, targetTime, data4, anchorOffset).Then(new Actions.Sprites.SimulateGravity(initialVelocity, gravityPerFrame, Main.rand.NextFloatDirection() * 0.2f, 60)).With(new Actions.Sprites.Fade(0f, 60));
             _segments.Add(item2);
         }
         int num7 = 30 + num6 * 10;
         spriteSegment.Then(new Actions.Sprites.SetFrameSequence(num7, new Point[4]
         {
             new Point(0, 5),
             new Point(0, 6),
             new Point(0, 7),
             new Point(0, 8)
         }, 5, 0, 0));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num7));
         animationSegmentWithActions3.Then(new Actions.Sprites.Wait(num7));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num7));
         num += num7;
         Segments.EmoteSegment item3 = new Segments.EmoteSegment(3, num, num5, sceneAnchorPosition + new Vector2(80 + num4, 4f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         spriteSegment.Then(new Actions.Sprites.Wait(num5)).With(new Actions.Sprites.SetFrame(0, 5, 0, 0));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions3.Then(new Actions.Sprites.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         spriteSegment.Then(new Actions.Sprites.SetFrameSequence(new Point[4]
         {
             new Point(0, 9),
             new Point(0, 10),
             new Point(0, 11),
             new Point(0, 13)
         }, 5, 0, 0));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(20));
         animationSegmentWithActions3.Then(new Actions.Sprites.Wait(20));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(20));
         num += 20;
         int num8 = 90;
         spriteSegment.Then(new Actions.Sprites.Fade(0f));
         animationSegmentWithActions2.Then(new Actions.NPCs.ShowItem(num8, 3258)).With(new Actions.NPCs.Fade(-255)).With(new Actions.NPCs.LookAt(-1));
         animationSegmentWithActions3.Then(new Actions.Sprites.Wait(num8));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num8));
         num += num8;
         Segments.EmoteSegment item4 = new Segments.EmoteSegment(136, num, num5, sceneAnchorPosition + new Vector2(60 + num4, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None, new Vector2(-1f, 0f));
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), num5));
         animationSegmentWithActions3.Then(new Actions.Sprites.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions3.Then(new Actions.Sprites.Fade(0f, 127));
         animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
         num += 187;
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(spriteSegment);
         _segments.Add(item);
         _segments.Add(item3);
         _segments.Add(item4);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References _backgroundOffset, _emoteBubbleOffsetWhenOnLeft, _emoteBubbleOffsetWhenOnRight, _originAtBottom, _segments, Color, TextureAssets.Extra, GetSceneFixVector(), Main.instance, TextureAssets.Item, Main.LoadItem(), Main.rand, Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().