Terraria: System.Net.WebClient.UploadFile
UploadFile() [4/4]
byte[] System.Net.WebClient.UploadFile (Uri address, string? method, string fileName) inline
Definition at line 757 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        ArgumentNullException.ThrowIfNull(fileName, "fileName");
        if (method == null)
        {
            method = MapToDefaultMethod(address);
        }
        FileStream fs = null;
        WebRequest request = null;
        StartOperation();
        try
        {
            _method = method;
            byte[] formHeaderBytes = null;
            byte[] boundaryBytes = null;
            Uri uri = GetUri(address);
            bool needsHeaderAndBoundary = uri.Scheme != Uri.UriSchemeFile;
            OpenFileInternal(needsHeaderAndBoundary, fileName, out fs, out var buffer, ref formHeaderBytes, ref boundaryBytes);
            request = (_webRequest = GetWebRequest(uri));
            return UploadBits(request, fs, buffer, 0, formHeaderBytes, boundaryBytes);
        }
        catch (Exception ex)
        {
            fs?.Close();
            if (ex is OutOfMemoryException)
            {
                throw;
            }
            AbortRequest(request);
            if (ex is WebException || ex is SecurityException)
            {
                throw;
            }
            throw new WebException(System.SR.net_webclient, ex);
        }
        finally
        {
            EndOperation();
        }
    }
References System.Net.WebClient._method, System.Net.WebClient._webRequest, System.Net.WebClient.AbortRequest(), System.buffer, System.IO.Stream.Close(), System.Net.WebClient.EndOperation(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetWebRequest(), System.Net.WebClient.MapToDefaultMethod(), System.SR.net_webclient, System.Net.WebClient.OpenFileInternal(), System.Net.WebClient.StartOperation(), System.ArgumentNullException.ThrowIfNull(), System.Net.WebClient.UploadBits(), and System.Uri.UriSchemeFile.