Terraria: System.Net.WebClient.DownloadBitsAsync
DownloadBitsAsync()
async void System.Net.WebClient.DownloadBitsAsync (WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action< byte[], Exception, AsyncOperation > completionDelegate) inline private
Definition at line 1074 of file WebClient.cs.
    {
        Exception exception = null;
        try
        {
            WebResponse webResponse = (_webResponse = await GetWebResponseTaskAsync(request).ConfigureAwait(continueOnCapturedContext: false));
            long contentLength = webResponse.ContentLength;
            byte[] copyBuffer = new byte[(contentLength == -1 || contentLength > 65536) ? 65536 : contentLength];
            if (writeStream is ChunkedMemoryStream)
            {
                if (contentLength > int.MaxValue)
                {
                    throw new WebException(System.SR.net_webstatus_MessageLengthLimitExceeded, WebExceptionStatus.MessageLengthLimitExceeded);
                }
                writeStream.SetLength(copyBuffer.Length);
            }
            if (contentLength >= 0)
            {
                _progress.TotalBytesToReceive = contentLength;
            }
            using (writeStream)
            {
                using Stream readStream = webResponse.GetResponseStream();
                if (readStream != null)
                {
                    while (true)
                    {
                        int num = await readStream.ReadAsync(new Memory<byte>(copyBuffer)).ConfigureAwait(continueOnCapturedContext: false);
                        if (num == 0)
{
                            break;
                        }
                        _progress.BytesReceived += num;
                        if (_progress.BytesReceived != _progress.TotalBytesToReceive)
{
                            PostProgressChanged(asyncOp, _progress);
                        }
                        await writeStream.WriteAsync(new ReadOnlyMemory<byte>(copyBuffer, 0, num)).ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
                if (_progress.TotalBytesToReceive < 0)
                {
                    _progress.TotalBytesToReceive = _progress.BytesReceived;
                }
                PostProgressChanged(asyncOp, _progress);
            }
            completionDelegate((writeStream as ChunkedMemoryStream)?.ToArray(), null, asyncOp);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            exception = GetExceptionToPropagate(ex);
            AbortRequest(request);
            writeStream?.Close();
        }
        finally
        {
            if (exception != null)
            {
                completionDelegate(null, exception, asyncOp);
            }
        }
    }
References System.Net.WebClient._progress, System.Net.WebClient._webResponse, System.Net.WebClient.AbortRequest(), System.Net.WebClient.ProgressData.BytesReceived, System.IO.Stream.Close(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.WebResponse.ContentLength, System.exception, System.Net.WebClient.GetExceptionToPropagate(), System.Net.WebResponse.GetResponseStream(), System.Net.WebClient.GetWebResponseTaskAsync(), System.SR.net_webstatus_MessageLengthLimitExceeded, System.Net.WebClient.PostProgressChanged(), System.IO.Stream.ReadAsync(), System.IO.Stream.SetLength(), System.Net.WebClient.ProgressData.TotalBytesToReceive, and System.IO.Stream.WriteAsync().
Referenced by System.Net.WebClient.DownloadDataAsync(), System.Net.WebClient.DownloadFileAsync(), System.Net.WebClient.DownloadStringAsync(), and System.Net.WebClient.UploadBitsAsync().