Terraria: System.Net.WebClient.GetStringUsingEncoding
GetStringUsingEncoding()
string System.Net.WebClient.GetStringUsingEncoding (WebRequest request, byte[] data) inline private
Definition at line 1290 of file WebClient.cs.
    {
        Encoding encoding = null;
        int num = -1;
        string text;
        try
        {
            text = request.ContentType;
        }
        catch (Exception ex) when (ex is NotImplementedException || ex is NotSupportedException)
        {
            text = null;
        }
        if (text != null)
        {
            text = text.ToLowerInvariant();
            string[] array = text.Split(s_parseContentTypeSeparators);
            bool flag = false;
            string[] array2 = array;
            foreach (string text2 in array2)
            {
                if (text2 == "charset")
                {
                    flag = true;
                }
                else if (flag)
                {
                    try
                    {
                        encoding = System.Text.Encoding.GetEncoding(text2);
                    }
                    catch (ArgumentException)
                    {
                        break;
                    }
                }
            }
        }
        if (encoding == null)
        {
            Encoding[] array3 = s_knownEncodings;
            for (int j = 0; j < array3.Length; j++)
            {
                byte[] preamble = array3[j].GetPreamble();
                if (ByteArrayHasPrefix(preamble, data))
                {
                    encoding = array3[j];
                    num = preamble.Length;
                    break;
                }
            }
        }
        if (encoding == null)
        {
            encoding = Encoding;
        }
        if (num == -1)
        {
            byte[] preamble2 = encoding.GetPreamble();
            num = (ByteArrayHasPrefix(preamble2, data) ? preamble2.Length : 0);
        }
        return encoding.GetString(data, num, data.Length - num);
    }
References System.array, System.Net.WebClient.ByteArrayHasPrefix(), System.Net.WebRequest.ContentType, System.Net.WebClient.Encoding, System.Text.Encoding.GetEncoding(), System.Text.Encoding.GetPreamble(), System.Text.Encoding.GetString(), System.Net.WebClient.s_knownEncodings, System.Net.WebClient.s_parseContentTypeSeparators, and System.text.
Referenced by System.Net.WebClient.DownloadString(), System.Net.WebClient.DownloadStringAsyncCallback(), System.Net.WebClient.UploadString(), and System.Net.WebClient.UploadStringAsync().