Terraria: System.Net.WebClient.OpenWriteAsync
OpenWriteAsync() [3/3]
void System.Net.WebClient.OpenWriteAsync (Uri address, string? method, object? userToken) inline
Definition at line 1492 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        if (method == null)
        {
            method = MapToDefaultMethod(address);
        }
        AsyncOperation asyncOp = StartAsyncOperation(userToken);
        try
        {
            _method = method;
            WebRequest request = (_webRequest = GetWebRequest(GetUri(address)));
            request.BeginGetRequestStream(delegate(IAsyncResult iar)
            {
                WebClientWriteStream result = null;
                Exception exception = null;
                try
                {
                    result = new WebClientWriteStream(request.EndGetRequestStream(iar), request, this);
                }
                catch (Exception ex2) when (!(ex2 is OutOfMemoryException))
                {
                    exception = GetExceptionToPropagate(ex2);
                }
                InvokeOperationCompleted(asyncOp, _openWriteOperationCompleted, new OpenWriteCompletedEventArgs(result, exception, _canceled, asyncOp.UserSuppliedState));
            }, null);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            OpenWriteCompletedEventArgs eventArgs = new OpenWriteCompletedEventArgs(null, GetExceptionToPropagate(ex), _canceled, asyncOp.UserSuppliedState);
            InvokeOperationCompleted(asyncOp, _openWriteOperationCompleted, eventArgs);
        }
    }
References System.Net.WebClient._canceled, System.Net.WebClient._method, System.Net.WebClient._openWriteOperationCompleted, System.Net.WebClient._webRequest, System.Net.WebRequest.BeginGetRequestStream(), System.Net.WebRequest.EndGetRequestStream(), System.exception, System.Net.WebClient.GetExceptionToPropagate(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetWebRequest(), System.Net.WebClient.InvokeOperationCompleted(), System.Net.WebClient.MapToDefaultMethod(), System.Net.WebClient.StartAsyncOperation(), System.ArgumentNullException.ThrowIfNull(), and System.ComponentModel.AsyncOperation.UserSuppliedState.