Terraria: System.Net.WebClient.AbortRequest
AbortRequest()
static void System.Net.WebClient.AbortRequest (WebRequest request) inline static private
Definition at line 929 of file WebClient.cs.
    {
        try
        {
            request?.Abort();
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
        }
    }
References System.Net.WebRequest.Abort().
Referenced by System.Net.WebClient.CancelAsync(), System.Net.WebClient.DownloadBits(), System.Net.WebClient.DownloadBitsAsync(), System.Net.WebClient.DownloadDataInternal(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.UploadBits(), System.Net.WebClient.UploadBitsAsync(), System.Net.WebClient.UploadDataInternal(), System.Net.WebClient.UploadFile(), and System.Net.WebClient.UploadValues().