Terraria: System.Net.WebClient.UploadDataAsync
UploadDataAsync() [3/3]
void System.Net.WebClient.UploadDataAsync (Uri address, string? method, byte[] data, object? userToken) inline
Definition at line 1678 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        ArgumentNullException.ThrowIfNull(data, "data");
        if (method == null)
        {
            method = MapToDefaultMethod(address);
        }
        AsyncOperation asyncOp = StartAsyncOperation(userToken);
        try
        {
            _method = method;
            _contentLength = data.Length;
            WebRequest request = (_webRequest = GetWebRequest(GetUri(address)));
            int chunkSize = 0;
            if (this.UploadProgressChanged != null)
            {
                chunkSize = (int)Math.Min(8192L, data.Length);
            }
            UploadBitsAsync(request, null, data, chunkSize, null, null, asyncOp, delegate(byte[] result, Exception error, AsyncOperation uploadAsyncOp)
            {
                InvokeOperationCompleted(asyncOp, _uploadDataOperationCompleted, new UploadDataCompletedEventArgs(result, error, _canceled, uploadAsyncOp.UserSuppliedState));
            });
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            UploadDataCompletedEventArgs eventArgs = new UploadDataCompletedEventArgs(null, GetExceptionToPropagate(ex), _canceled, asyncOp.UserSuppliedState);
            InvokeOperationCompleted(asyncOp, _uploadDataOperationCompleted, eventArgs);
        }
    }
References System.Net.WebClient._canceled, System.Net.WebClient._contentLength, System.Net.WebClient._method, System.Net.WebClient._uploadDataOperationCompleted, System.Net.WebClient._webRequest, System.Net.WebClient.GetExceptionToPropagate(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetWebRequest(), System.Net.WebClient.InvokeOperationCompleted(), System.L, System.Net.WebClient.MapToDefaultMethod(), System.Math.Min(), System.Net.WebClient.StartAsyncOperation(), System.ArgumentNullException.ThrowIfNull(), System.Net.WebClient.UploadBitsAsync(), and System.ComponentModel.AsyncOperation.UserSuppliedState.