Terraria: System.Net.WebClient.InvokeOperationCompleted
InvokeOperationCompleted()
void System.Net.WebClient.InvokeOperationCompleted (AsyncOperation asyncOp, SendOrPostCallback callback, AsyncCompletedEventArgs eventArgs) inline private
Definition at line 1440 of file WebClient.cs.
    {
        if (Interlocked.CompareExchange(ref _asyncOp, null, asyncOp) == asyncOp)
        {
            EndOperation();
            asyncOp.PostOperationCompleted(callback, eventArgs);
        }
    }
References System.Net.WebClient._asyncOp, System.Threading.Interlocked.CompareExchange(), System.Net.WebClient.EndOperation(), and System.ComponentModel.AsyncOperation.PostOperationCompleted().
Referenced by System.Net.WebClient.DownloadDataAsyncCallback(), System.Net.WebClient.DownloadFileAsyncCallback(), System.Net.WebClient.DownloadStringAsyncCallback(), System.Net.WebClient.OpenReadAsync(), System.Net.WebClient.OpenWriteAsync(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadStringAsync(), and System.Net.WebClient.UploadValuesAsync().