Terraria: System.Net.WebClient.UploadBits
UploadBits()
byte[] System.Net.WebClient.UploadBits (WebRequest request, Stream readStream, byte[] buffer, int chunkSize, byte[] header, byte[] footer) inline private
Definition at line 1137 of file WebClient.cs.
    {
        try
        {
            if (request.RequestUri.Scheme == Uri.UriSchemeFile)
            {
                header = (footer = null);
            }
            using (Stream stream = request.GetRequestStream())
            {
                if (header != null)
                {
                    stream.Write(header, 0, header.Length);
                }
                if (readStream != null)
                {
                    using (readStream)
                    {
                        while (true)
{
                            int num = readStream.Read(buffer, 0, buffer.Length);
                            if (num > 0)
{
                                stream.Write(buffer, 0, num);
                                continue;
                            }
                            break;
                        }
                    }
                }
                else
                {
                    int num2;
                    for (int i = 0; i < buffer.Length; i += num2)
                    {
                        num2 = buffer.Length - i;
                        if (chunkSize != 0 && num2 > chunkSize)
{
                            num2 = chunkSize;
                        }
                        stream.Write(buffer, i, num2);
                    }
                }
                if (footer != null)
                {
                    stream.Write(footer, 0, footer.Length);
                }
            }
            return DownloadBits(request, new ChunkedMemoryStream());
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            AbortRequest(request);
            if (ex is WebException || ex is SecurityException)
            {
                throw;
            }
            throw new WebException(System.SR.net_webclient, ex);
        }
    }
References System.Net.WebClient.AbortRequest(), System.buffer, System.Net.WebClient.DownloadBits(), System.Net.WebRequest.GetRequestStream(), System.SR.net_webclient, System.IO.Stream.Read(), System.Net.WebRequest.RequestUri, System.Uri.Scheme, System.stream, and System.Uri.UriSchemeFile.
Referenced by System.Net.WebClient.UploadDataInternal(), System.Net.WebClient.UploadFile(), and System.Net.WebClient.UploadValues().