Terraria: System.Net.WebClient.DownloadFile
DownloadFile() [2/2]
void System.Net.WebClient.DownloadFile (Uri address, string fileName) inline
Definition at line 519 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        ArgumentNullException.ThrowIfNull(fileName, "fileName");
        WebRequest request = null;
        FileStream fileStream = null;
        bool flag = false;
        StartOperation();
        try
        {
            fileStream = new FileStream(fileName, FileMode.Create, FileAccess.Write);
            request = (_webRequest = GetWebRequest(GetUri(address)));
            DownloadBits(request, fileStream);
            flag = true;
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            AbortRequest(request);
            if (ex is WebException || ex is SecurityException)
            {
                throw;
            }
            throw new WebException(System.SR.net_webclient, ex);
        }
        finally
        {
            if (fileStream != null)
            {
                fileStream.Close();
                if (!flag)
                {
                    File.Delete(fileName);
                }
            }
            EndOperation();
        }
    }
References System.Net.WebClient._webRequest, System.Net.WebClient.AbortRequest(), System.IO.Stream.Close(), System.IO.File.Delete(), System.Net.WebClient.DownloadBits(), System.Net.WebClient.EndOperation(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetWebRequest(), System.SR.net_webclient, System.Net.WebClient.StartOperation(), and System.ArgumentNullException.ThrowIfNull().