Terraria: CreditsRollComposer.PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk
PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk()
SegmentInforReport CreditsRollComposer.PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         int num2 = 40;
         sceneAnchorPosition.X += num2;
         int num3 = 62;
         Asset<Texture2D> val = TextureAssets.Extra[223];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
             .Then(new Actions.Sprites.Wait(60));
         _segments.Add(animationSegmentWithActions);
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 17, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Wait(60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 368, sceneAnchorPosition + new Vector2(num3, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Wait(60));
         Asset<Texture2D> val2 = TextureAssets.Extra[239];
         Rectangle rectangle2 = val2.Frame(1, 8);
         DrawData data2 = new DrawData(val2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, SpriteEffects.FlipHorizontally);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions4 = new Segments.SpriteSegment(val2, num, data2, sceneAnchorPosition + new Vector2(num2 - 128, 4f)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         int num4 = 90;
         int num5 = 60;
         animationSegmentWithActions2.Then(new Actions.NPCs.ShowItem(num5, 8));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         Segments.EmoteSegment item = new Segments.EmoteSegment(11, num, num4, sceneAnchorPosition + new Vector2(num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions3.Then(new Actions.NPCs.ShowItem(num5, 2242));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         Segments.EmoteSegment item2 = new Segments.EmoteSegment(11, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         animationSegmentWithActions2.Then(new Actions.NPCs.ShowItem(num5, 88));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         Segments.EmoteSegment item3 = new Segments.EmoteSegment(11, num, num4, sceneAnchorPosition + new Vector2(num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions3.Then(new Actions.NPCs.ShowItem(num5, 4761));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         Segments.EmoteSegment item4 = new Segments.EmoteSegment(11, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         int num6 = num5 + 30;
         animationSegmentWithActions2.Then(new Actions.NPCs.ShowItem(num6, 2));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
         num += num6;
         Segments.EmoteSegment item5 = new Segments.EmoteSegment(10, num, num4, sceneAnchorPosition + new Vector2(num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions3.Then(new Actions.NPCs.ShowItem(num6, 52));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
         num += num6;
         Segments.EmoteSegment item6 = new Segments.EmoteSegment(85, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item7 = new Segments.EmoteSegment(85, num, num4, sceneAnchorPosition + new Vector2(num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         animationSegmentWithActions4.Then(new Actions.Sprites.SetFrameSequence(num - startTime, new Point[8]
         {
             new Point(0, 0),
             new Point(0, 1),
             new Point(0, 2),
             new Point(0, 3),
             new Point(0, 4),
             new Point(0, 5),
             new Point(0, 6),
             new Point(0, 7)
         }, 5, 0, 0));
         animationSegmentWithActions2.Then(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions3.Then(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions4.Then(new Actions.Sprites.Fade(0f, 127));
         animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
         num += 187;
         _segments.Add(animationSegmentWithActions4);
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(item);
         _segments.Add(item2);
         _segments.Add(item3);
         _segments.Add(item4);
         _segments.Add(item5);
         _segments.Add(item6);
         _segments.Add(item7);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References _backgroundOffset, _emoteBubbleOffsetWhenOnLeft, _emoteBubbleOffsetWhenOnRight, _originAtBottom, _segments, Color, TextureAssets.Extra, GetSceneFixVector(), Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().