Terraria: CreditsRollComposer.PlaySegment_SantaItemExample
PlaySegment_SantaItemExample()
SegmentInforReport CreditsRollComposer.PlaySegment_SantaItemExample (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = 0;
         for (int i = 0; i < num; i++)
         {
             int num2 = Main.rand.NextFromList(new short[4] { 599, 1958, 3749, 1869 });
             Main.instance.LoadItem(num2);
             Asset<Texture2D> val = TextureAssets.Item[num2];
             DrawData data = new DrawData(val.Value, Vector2.Zero, null, Color.White, 0f, val.Size() / 2f, 1f, SpriteEffects.None);
             Vector2 initialVelocity = Vector2.UnitY * -12f + Main.rand.NextVector2Circular(6f, 3f).RotatedBy((float)(i - num / 2) * ((float)Math.PI * 2f) * 0.1f);
             Vector2 gravityPerFrame = Vector2.UnitY * 0.2f;
             Segments.AnimationSegmentWithActions<Segments.LooseSprite> item = new Segments.SpriteSegment(val, startTime, data, sceneAnchorPosition).Then(new Actions.Sprites.SimulateGravity(initialVelocity, gravityPerFrame, Main.rand.NextFloatDirection() * 0.2f, 60)).With(new Actions.Sprites.Fade(0f, 60));
             _segments.Add(item);
         }
         Segments.AnimationSegmentWithActions<NPC> item2 = new Segments.NPCSegment(startTime, 142, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.ShowItem(30, 267)).Then(new Actions.NPCs.Wait(10)).Then(new Actions.NPCs.ShowItem(30, 600))
             .Then(new Actions.NPCs.Wait(10))
             .Then(new Actions.NPCs.ShowItem(30, 2))
             .Then(new Actions.NPCs.Wait(10));
         _segments.Add(item2);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = 170;
         return result;
     }
References _originAtBottom, _segments, Color, GetSceneFixVector(), Main.instance, TextureAssets.Item, Main.LoadItem(), Main.rand, Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, and Asset< T >.Value.