Terraria: System.Net.WebClient.OpenRead
OpenRead() [2/2]
Stream System.Net.WebClient.OpenRead (Uri address) inline
Definition at line 562 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        WebRequest request = null;
        StartOperation();
        try
        {
            request = (_webRequest = GetWebRequest(GetUri(address)));
            return (_webResponse = GetWebResponse(request)).GetResponseStream();
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            AbortRequest(request);
            if (ex is WebException || ex is SecurityException)
            {
                throw;
            }
            throw new WebException(System.SR.net_webclient, ex);
        }
        finally
        {
            EndOperation();
        }
    }
References System.Net.WebClient._webRequest, System.Net.WebClient._webResponse, System.Net.WebClient.AbortRequest(), System.Net.WebClient.EndOperation(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetWebRequest(), System.Net.WebClient.GetWebResponse(), System.SR.net_webclient, System.Net.WebClient.StartOperation(), and System.ArgumentNullException.ThrowIfNull().