Terraria: System.Net.WebClient.UploadBitsAsync
UploadBitsAsync()
async void System.Net.WebClient.UploadBitsAsync (WebRequest request, Stream readStream, byte[] buffer, int chunkSize, byte[] header, byte[] footer, AsyncOperation asyncOp, Action< byte[], Exception, AsyncOperation > completionDelegate) inline private
Definition at line 1198 of file WebClient.cs.
    {
        _progress.HasUploadPhase = true;
        Exception exception = null;
        try
        {
            if (request.RequestUri.Scheme == Uri.UriSchemeFile)
            {
                byte[] array;
                footer = (array = null);
                header = array;
            }
            using (Stream writeStream = await request.GetRequestStreamAsync().ConfigureAwait(continueOnCapturedContext: false))
            {
                if (header != null)
                {
                    await writeStream.WriteAsync(new ReadOnlyMemory<byte>(header)).ConfigureAwait(continueOnCapturedContext: false);
                    _progress.BytesSent += header.Length;
                    PostProgressChanged(asyncOp, _progress);
                }
                if (readStream != null)
                {
                    using (readStream)
                    {
                        while (true)
{
                            int bytesRead2 = await readStream.ReadAsync(new Memory<byte>(buffer)).ConfigureAwait(continueOnCapturedContext: false);
                            if (bytesRead2 <= 0)
{
                                break;
                            }
                            await writeStream.WriteAsync(new ReadOnlyMemory<byte>(buffer, 0, bytesRead2)).ConfigureAwait(continueOnCapturedContext: false);
                            _progress.BytesSent += bytesRead2;
                            PostProgressChanged(asyncOp, _progress);
                        }
                    }
                }
                else
                {
                    int bytesRead2 = 0;
                    while (bytesRead2 < buffer.Length)
                    {
                        int toWrite = buffer.Length - bytesRead2;
                        if (chunkSize != 0 && toWrite > chunkSize)
{
                            toWrite = chunkSize;
                        }
                        await writeStream.WriteAsync(new ReadOnlyMemory<byte>(buffer, bytesRead2, toWrite)).ConfigureAwait(continueOnCapturedContext: false);
                        bytesRead2 += toWrite;
                        _progress.BytesSent += toWrite;
                        PostProgressChanged(asyncOp, _progress);
                    }
                }
                if (footer != null)
                {
                    await writeStream.WriteAsync(new ReadOnlyMemory<byte>(footer)).ConfigureAwait(continueOnCapturedContext: false);
                    _progress.BytesSent += footer.Length;
                    PostProgressChanged(asyncOp, _progress);
                }
            }
            DownloadBitsAsync(request, new ChunkedMemoryStream(), asyncOp, completionDelegate);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            exception = GetExceptionToPropagate(ex);
            AbortRequest(request);
        }
        finally
        {
            if (exception != null)
            {
                completionDelegate(null, exception, asyncOp);
            }
        }
    }
References System.Net.WebClient._progress, System.Net.WebClient.AbortRequest(), System.array, System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.WebClient.DownloadBitsAsync(), System.exception, System.Net.WebClient.GetExceptionToPropagate(), System.Net.WebRequest.GetRequestStreamAsync(), System.Net.WebClient.PostProgressChanged(), System.IO.Stream.ReadAsync(), System.Net.WebRequest.RequestUri, System.Uri.Scheme, System.Uri.UriSchemeFile, and System.IO.Stream.WriteAsync().
Referenced by System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadStringAsync(), and System.Net.WebClient.UploadValuesAsync().