Terraria: CreditsRollComposer.PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes
PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes()
SegmentInforReport CreditsRollComposer.PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         int num2 = -30;
         sceneAnchorPosition.X += num2;
         Asset<Texture2D> val = TextureAssets.Extra[234];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
             .Then(new Actions.Sprites.Wait(120));
         _segments.Add(animationSegmentWithActions);
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 38, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 60))
             .Then(new Actions.NPCs.Wait(60));
         int num3 = 90;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 19, sceneAnchorPosition + new Vector2(120 + num3, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60))
             .Then(new Actions.NPCs.Wait(60));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         int num4 = 90 * 4;
         int num5 = 90;
         int num6 = 90 / 2;
         int num7 = 90 + 90 / 2;
         int num8 = 90 * 2;
         Segments.EmoteSegment item = new Segments.EmoteSegment(81, num, num5, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item2 = new Segments.EmoteSegment(82, num + num6, num5, sceneAnchorPosition + new Vector2(60 + num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         Segments.EmoteSegment item3 = new Segments.EmoteSegment(135, num + num7, num5, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item4 = new Segments.EmoteSegment(135, num + num8, num5, sceneAnchorPosition + new Vector2(60 + num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         int num9 = num3 - 30;
         int num10 = 120;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions4 = new Segments.NPCSegment(num - num10, 18, sceneAnchorPosition + new Vector2(120 + num9, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60))
             .Then(new Actions.NPCs.Wait(20));
         int num11 = (int)animationSegmentWithActions4.DedicatedTimeNeeded - num10;
         num += num11;
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num11));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num11));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num11));
         animationSegmentWithActions4.Then(new Actions.NPCs.LookAt(-1));
         Segments.EmoteSegment item5 = new Segments.EmoteSegment(77, num, num5, sceneAnchorPosition + new Vector2(60 + num9, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item6 = new Segments.EmoteSegment(15, num + num5, num5, sceneAnchorPosition + new Vector2(60 + num9, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         animationSegmentWithActions4.Then(new Actions.NPCs.LookAt(1));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         Segments.EmoteSegment item7 = new Segments.EmoteSegment(10, num, num5, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item8 = new Segments.EmoteSegment(10, num, num5, sceneAnchorPosition + new Vector2(60 + num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         Vector2 vector = new Vector2(-1f, 0f);
         Segments.EmoteSegment item9 = new Segments.EmoteSegment(77, num, num5, sceneAnchorPosition + new Vector2(60 + num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None, vector);
         Segments.EmoteSegment item10 = new Segments.EmoteSegment(77, num + num5 / 2, num5, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None, vector);
         int num12 = num5 + num5 / 2;
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(vector, num12));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5 / 2)).Then(new Actions.NPCs.Move(vector, num5));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num5 / 2 + 20)).Then(new Actions.NPCs.Move(vector, num5 - 20));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num12));
         num += num12;
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
         num += 187;
         _segments.Add(animationSegmentWithActions4);
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(item);
         _segments.Add(item2);
         _segments.Add(item3);
         _segments.Add(item4);
         _segments.Add(item5);
         _segments.Add(item6);
         _segments.Add(item7);
         _segments.Add(item8);
         _segments.Add(item10);
         _segments.Add(item9);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References Color, TextureAssets.Extra, Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().