Terraria: CreditsRollComposer.PlaySegment_DryadTurningToTree
PlaySegment_DryadTurningToTree()
SegmentInforReport CreditsRollComposer.PlaySegment_DryadTurningToTree (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         Asset<Texture2D> val = TextureAssets.Extra[217];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(0f, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 20, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 60))
             .Then(new Actions.NPCs.Wait(10))
             .Then(new Actions.NPCs.Fade(0));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         Asset<Texture2D> val2 = TextureAssets.Extra[215];
         Rectangle rectangle2 = val2.Frame(1, 9);
         DrawData data2 = new DrawData(val2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, SpriteEffects.FlipHorizontally);
         Vector2 vector = new Vector2(1f, 0f) * 60f + new Vector2(2f, 4f);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions3 = new Segments.SpriteSegment(val2, num, data2, sceneAnchorPosition + vector).Then(new Actions.Sprites.SetFrameSequence(new Point[9]
         {
             new Point(0, 0),
             new Point(0, 1),
             new Point(0, 2),
             new Point(0, 3),
             new Point(0, 4),
             new Point(0, 5),
             new Point(0, 6),
             new Point(0, 7),
             new Point(0, 8)
         }, 8, 0, 0)).Then(new Actions.Sprites.Wait(30));
         num += (int)animationSegmentWithActions3.DedicatedTimeNeeded;
         Segments.AnimationSegmentWithActions<NPC> item = new Segments.NPCSegment(num, 46, sceneAnchorPosition + new Vector2(-100f, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 60))
             .Then(new Actions.NPCs.Wait(90))
             .Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 120))
             .With(new Actions.NPCs.Fade(3, 85));
         Segments.AnimationSegmentWithActions<NPC> item2 = new Segments.NPCSegment(num + 60, 299, sceneAnchorPosition + new Vector2(170f, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60))
             .Then(new Actions.NPCs.Wait(60))
             .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 90))
             .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 85))
             .With(new Actions.NPCs.Fade(3, 85));
         float x = 1.5f;
         Segments.AnimationSegmentWithActions<NPC> item3 = new Segments.NPCSegment(num + 45, 74, sceneAnchorPosition + new Vector2(-80f, -70f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(x, 0f), 85))
             .With(new Actions.NPCs.MoveWithRotor(new Vector2(10f, 0f), (float)Math.PI * 2f / 85f, new Vector2(0f, 1f), 85))
             .Then(new Actions.NPCs.Move(new Vector2(x, 0f), 85))
             .With(new Actions.NPCs.MoveWithRotor(new Vector2(4f, 0f), (float)Math.PI * 2f / 85f, new Vector2(0f, 1f), 85))
             .With(new Actions.NPCs.Fade(3, 85));
         Segments.AnimationSegmentWithActions<NPC> item4 = new Segments.NPCSegment(num + 180, 656, sceneAnchorPosition + new Vector2(20f, 0f), _originAtBottom).Then(new Actions.NPCs.Variant(1)).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255))
             .With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Wait(60))
             .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 60))
             .Then(new Actions.NPCs.Wait(60))
             .Then(new Actions.NPCs.DoBunnyRestAnimation(90))
             .Then(new Actions.NPCs.Wait(90))
             .With(new Actions.NPCs.Fade(3, 120));
         Segments.EmoteSegment item5 = new Segments.EmoteSegment(0, num + 360, 60, sceneAnchorPosition + new Vector2(36f, -10f), SpriteEffects.FlipHorizontally, Vector2.Zero);
         animationSegmentWithActions3.Then(new Actions.Sprites.Wait(420)).Then(new Actions.Sprites.Fade(0f, 120));
         num += 620;
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num - startTime - 180)).Then(new Actions.Sprites.Fade(0f, 120));
         _segments.Add(animationSegmentWithActions);
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(item);
         _segments.Add(item2);
         _segments.Add(item3);
         _segments.Add(item4);
         _segments.Add(item5);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References _backgroundOffset, _originAtBottom, _segments, Color, TextureAssets.Extra, GetSceneFixVector(), Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().