Terraria: System.Net.WebClient.DownloadBits
DownloadBits()
byte[] System.Net.WebClient.DownloadBits (WebRequest request, Stream writeStream) inline private
Definition at line 1034 of file WebClient.cs.
    {
        try
        {
            WebResponse webResponse = (_webResponse = GetWebResponse(request));
            long contentLength = webResponse.ContentLength;
            byte[] array = new byte[(contentLength == -1 || contentLength > 65536) ? 65536 : contentLength];
            if (writeStream is ChunkedMemoryStream)
            {
                if (contentLength > int.MaxValue)
                {
                    throw new WebException(System.SR.net_webstatus_MessageLengthLimitExceeded, WebExceptionStatus.MessageLengthLimitExceeded);
                }
                writeStream.SetLength(array.Length);
            }
            using (Stream stream = webResponse.GetResponseStream())
            {
                if (stream != null)
                {
                    int count;
                    while ((count = stream.Read(array, 0, array.Length)) != 0)
                    {
                        writeStream.Write(array, 0, count);
                    }
                }
            }
            return (writeStream as ChunkedMemoryStream)?.ToArray();
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            writeStream?.Close();
            AbortRequest(request);
            if (ex is WebException || ex is SecurityException)
            {
                throw;
            }
            throw new WebException(System.SR.net_webclient, ex);
        }
    }
References System.Net.WebClient._webResponse, System.Net.WebClient.AbortRequest(), System.array, System.IO.Stream.Close(), System.Net.WebResponse.ContentLength, System.count, System.Net.WebResponse.GetResponseStream(), System.Net.WebClient.GetWebResponse(), System.SR.net_webclient, System.SR.net_webstatus_MessageLengthLimitExceeded, System.IO.Stream.SetLength(), System.stream, and System.IO.Stream.Write().
Referenced by System.Net.WebClient.DownloadDataInternal(), System.Net.WebClient.DownloadFile(), and System.Net.WebClient.UploadBits().