Terraria: System.Net.WebClient.UploadFileAsync
UploadFileAsync() [3/3]
void System.Net.WebClient.UploadFileAsync (Uri address, string? method, string fileName, object? userToken) inline
Definition at line 1719 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        ArgumentNullException.ThrowIfNull(fileName, "fileName");
        if (method == null)
        {
            method = MapToDefaultMethod(address);
        }
        FileStream fs = null;
        AsyncOperation asyncOp = StartAsyncOperation(userToken);
        try
        {
            _method = method;
            byte[] formHeaderBytes = null;
            byte[] boundaryBytes = null;
            byte[] buffer = null;
            Uri uri = GetUri(address);
            bool needsHeaderAndBoundary = uri.Scheme != Uri.UriSchemeFile;
            OpenFileInternal(needsHeaderAndBoundary, fileName, out fs, out buffer, ref formHeaderBytes, ref boundaryBytes);
            UploadBitsAsync(_webRequest = GetWebRequest(uri), fs, buffer, 0, formHeaderBytes, boundaryBytes, asyncOp, delegate(byte[] result, Exception error, AsyncOperation uploadAsyncOp)
            {
                InvokeOperationCompleted(asyncOp, _uploadFileOperationCompleted, new UploadFileCompletedEventArgs(result, error, _canceled, uploadAsyncOp.UserSuppliedState));
            });
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            fs?.Close();
            UploadFileCompletedEventArgs eventArgs = new UploadFileCompletedEventArgs(null, GetExceptionToPropagate(ex), _canceled, asyncOp.UserSuppliedState);
            InvokeOperationCompleted(asyncOp, _uploadFileOperationCompleted, eventArgs);
        }
    }
References System.Net.WebClient._canceled, System.Net.WebClient._method, System.Net.WebClient._uploadFileOperationCompleted, System.Net.WebClient._webRequest, System.buffer, System.IO.Stream.Close(), System.Net.WebClient.GetExceptionToPropagate(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetWebRequest(), System.Net.WebClient.InvokeOperationCompleted(), System.Net.WebClient.MapToDefaultMethod(), System.Net.WebClient.OpenFileInternal(), System.Net.WebClient.StartAsyncOperation(), System.ArgumentNullException.ThrowIfNull(), System.Net.WebClient.UploadBitsAsync(), System.Uri.UriSchemeFile, and System.ComponentModel.AsyncOperation.UserSuppliedState.