Terraria: System.Net.WebClient.UploadStringAsync
UploadStringAsync() [3/3]
void System.Net.WebClient.UploadStringAsync (Uri address, string? method, string data, object? userToken) inline
Definition at line 1630 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        ArgumentNullException.ThrowIfNull(data, "data");
        if (method == null)
        {
            method = MapToDefaultMethod(address);
        }
        AsyncOperation asyncOperation = StartAsyncOperation(userToken);
        try
        {
            byte[] bytes = Encoding.GetBytes(data);
            _method = method;
            _contentLength = bytes.Length;
            UploadBitsAsync(_webRequest = GetWebRequest(GetUri(address)), null, bytes, 0, null, null, asyncOperation, delegate(byte[] bytesResult, Exception error, AsyncOperation uploadAsyncOp)
            {
                string result = null;
                if (error == null && bytesResult != null)
                {
                    try
                    {
                        result = GetStringUsingEncoding(_webRequest, bytesResult);
                    }
                    catch (Exception ex2) when (!(ex2 is OutOfMemoryException))
                    {
                        error = GetExceptionToPropagate(ex2);
                    }
                }
                InvokeOperationCompleted(uploadAsyncOp, _uploadStringOperationCompleted, new UploadStringCompletedEventArgs(result, error, _canceled, uploadAsyncOp.UserSuppliedState));
            });
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            UploadStringCompletedEventArgs eventArgs = new UploadStringCompletedEventArgs(null, GetExceptionToPropagate(ex), _canceled, asyncOperation.UserSuppliedState);
            InvokeOperationCompleted(asyncOperation, _uploadStringOperationCompleted, eventArgs);
        }
    }
References System.Net.WebClient._canceled, System.Net.WebClient._contentLength, System.Net.WebClient._method, System.Net.WebClient._uploadStringOperationCompleted, System.Net.WebClient._webRequest, System.bytes, System.Text.Encoding.GetBytes(), System.Net.WebClient.GetExceptionToPropagate(), System.Net.WebClient.GetStringUsingEncoding(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetWebRequest(), System.Net.WebClient.InvokeOperationCompleted(), System.Net.WebClient.MapToDefaultMethod(), System.Net.WebClient.StartAsyncOperation(), System.ArgumentNullException.ThrowIfNull(), System.Net.WebClient.UploadBitsAsync(), and System.ComponentModel.AsyncOperation.UserSuppliedState.