Terraria: CreditsRollComposer.PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer
PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer()
SegmentInforReport CreditsRollComposer.PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         int num2 = -28;
         sceneAnchorPosition.X += num2;
         int num3 = 40;
         Asset<Texture2D> val = TextureAssets.Extra[224];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
             .Then(new Actions.Sprites.Wait(60));
         _segments.Add(animationSegmentWithActions);
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 633, sceneAnchorPosition + new Vector2(-60f, 0f), _originAtBottom).Then(new Actions.NPCs.ForceAltTexture(3)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 656, sceneAnchorPosition + new Vector2(num3 - 60, 0f), _originAtBottom).Then(new Actions.NPCs.Variant(3)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions4 = new Segments.NPCSegment(startTime, 638, sceneAnchorPosition + new Vector2(num3 * 2 - 60, 0f), _originAtBottom).Then(new Actions.NPCs.Variant(2)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions5 = new Segments.NPCSegment(startTime, 637, sceneAnchorPosition + new Vector2(num3 * 3 - 60, 0f), _originAtBottom).Then(new Actions.NPCs.Variant(4)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 60));
         Main.instance.LoadProjectile(748);
         Asset<Texture2D> val2 = TextureAssets.Projectile[748];
         DrawData data2 = new DrawData(val2.Value, Vector2.Zero, null, Color.White, 0f, val2.Size() / 2f, 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions6 = new Segments.SpriteSegment(val2, startTime, data2, sceneAnchorPosition + new Vector2(num3 * 3 - 20, 0f)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51)).Then(new Actions.Sprites.Wait(60));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         int num4 = 90;
         float num5 = 0.5f;
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(1f * num5, 0f), num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(0.5f * num5, 0f), num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(0.6f * num5, 0f), num4));
         animationSegmentWithActions5.Then(new Actions.NPCs.Move(new Vector2(0.8f * num5, 0f), num4));
         animationSegmentWithActions6.Then(new Actions.Sprites.SimulateGravity(new Vector2(0.82f * num5, 0f), Vector2.Zero, 0.07f, num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions7 = new Segments.NPCSegment(num, 588, sceneAnchorPosition + new Vector2(-70f, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(0.7f * num5, 0f), 60));
         int num6 = (int)animationSegmentWithActions7.DedicatedTimeNeeded;
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(1f * num5, 0f), num6));
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(0.85f * num5, 0f), num6));
         animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(0.7f * num5, 0f), num6));
         animationSegmentWithActions5.Then(new Actions.NPCs.Move(new Vector2(0.65f * num5, 0f), num6));
         animationSegmentWithActions6.Then(new Actions.Sprites.SimulateGravity(new Vector2(1f * num5, 0f), Vector2.Zero, 0.07f, num6));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
         num += num6;
         int num7 = 90;
         int num8 = num7 * 2 + num7 / 2;
         Segments.EmoteSegment item = new Segments.EmoteSegment(1, num, num7, sceneAnchorPosition + new Vector2(-70f + 42f * num5, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally, new Vector2(1f * num5, 0f));
         Segments.EmoteSegment item2 = new Segments.EmoteSegment(15, num + num7 / 2, num7, sceneAnchorPosition + new Vector2((float)(80 + num6) * num5, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally, new Vector2(1f * num5, 0f));
         animationSegmentWithActions7.Then(new Actions.NPCs.Move(new Vector2(1f * num5, 0f), num8));
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(1f * num5, 0f), num8));
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(0.72f * num5, 0f), num8));
         animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(0.7f * num5, 0f), num8));
         animationSegmentWithActions5.Then(new Actions.NPCs.Move(new Vector2(0.8f * num5, 0f), num8));
         animationSegmentWithActions6.Then(new Actions.Sprites.SimulateGravity(new Vector2(0.85f * num5, 0f), Vector2.Zero, 0.07f, num8));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num8));
         num += num8;
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(0.5f * num5, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions7.Then(new Actions.NPCs.Move(new Vector2(0.5f * num5, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(0.6f * num5, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(0.7f * num5, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions5.Then(new Actions.NPCs.Move(new Vector2(0.6f * num5, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions6.Then(new Actions.Sprites.SimulateGravity(new Vector2(0.5f * num5, 0f), Vector2.Zero, 0.05f, 120)).With(new Actions.Sprites.Fade(0f, 127));
         animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
         num += 187;
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(animationSegmentWithActions7);
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(animationSegmentWithActions4);
         _segments.Add(animationSegmentWithActions5);
         _segments.Add(animationSegmentWithActions6);
         _segments.Add(item2);
         _segments.Add(item);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References _backgroundOffset, _emoteBubbleOffsetWhenOnLeft, _originAtBottom, _segments, Color, TextureAssets.Extra, GetSceneFixVector(), Main.instance, Main.LoadProjectile(), TextureAssets.Projectile, Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().