Terraria: System.Net.WebClient.GetUri
GetUri() [1/2]
Uri System.Net.WebClient.GetUri (string address) inline private
Definition at line 990 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        Uri result;
        if (_baseAddress != null)
        {
            if (!Uri.TryCreate(_baseAddress, address, out result))
            {
                return new Uri(Path.GetFullPath(address));
            }
        }
        else if (!Uri.TryCreate(address, UriKind.Absolute, out result))
        {
            return new Uri(Path.GetFullPath(address));
        }
        return GetUri(result);
    }
References System.Net.WebClient._baseAddress, System.IO.Path.GetFullPath(), System.Net.WebClient.GetUri(), System.ArgumentNullException.ThrowIfNull(), and System.Uri.TryCreate().
Referenced by System.Net.WebClient.DownloadData(), System.Net.WebClient.DownloadDataAsync(), System.Net.WebClient.DownloadDataInternal(), System.Net.WebClient.DownloadDataTaskAsync(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadFileAsync(), System.Net.WebClient.DownloadFileTaskAsync(), System.Net.WebClient.DownloadString(), System.Net.WebClient.DownloadStringAsync(), System.Net.WebClient.DownloadStringTaskAsync(), System.Net.WebClient.GetUri(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenReadAsync(), System.Net.WebClient.OpenReadTaskAsync(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWriteAsync(), System.Net.WebClient.OpenWriteTaskAsync(), System.Net.WebClient.OpenWriteTaskAsync(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadDataInternal(), System.Net.WebClient.UploadDataTaskAsync(), System.Net.WebClient.UploadDataTaskAsync(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadFileTaskAsync(), System.Net.WebClient.UploadFileTaskAsync(), System.Net.WebClient.UploadString(), System.Net.WebClient.UploadString(), System.Net.WebClient.UploadStringAsync(), System.Net.WebClient.UploadStringTaskAsync(), System.Net.WebClient.UploadValues(), System.Net.WebClient.UploadValues(), System.Net.WebClient.UploadValues(), System.Net.WebClient.UploadValuesAsync(), System.Net.WebClient.UploadValuesTaskAsync(), and System.Net.WebClient.UploadValuesTaskAsync().