Terraria: System.Net.WebClient.DownloadStringAsync
DownloadStringAsync() [2/2]
void System.Net.WebClient.DownloadStringAsync (Uri address, object? userToken) inline
Definition at line 1550 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        AsyncOperation asyncOperation = StartAsyncOperation(userToken);
        try
        {
            DownloadBitsAsync(_webRequest = GetWebRequest(GetUri(address)), new ChunkedMemoryStream(), asyncOperation, DownloadStringAsyncCallback);
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            DownloadStringAsyncCallback(null, GetExceptionToPropagate(ex), asyncOperation);
        }
    }
References System.Net.WebClient._webRequest, System.Net.WebClient.DownloadBitsAsync(), System.Net.WebClient.DownloadStringAsyncCallback(), System.Net.WebClient.GetExceptionToPropagate(), System.Net.WebClient.GetUri(), System.Net.WebClient.GetWebRequest(), System.Net.WebClient.StartAsyncOperation(), and System.ArgumentNullException.ThrowIfNull().