Terraria: System.Net.WebClient.DownloadStringAsyncCallback
DownloadStringAsyncCallback()
void System.Net.WebClient.DownloadStringAsyncCallback (byte[] returnBytes, Exception exception, object state) inline private
Definition at line 1526 of file WebClient.cs.
    {
        AsyncOperation asyncOperation = (AsyncOperation)state;
        string result = null;
        try
        {
            if (returnBytes != null)
            {
                result = GetStringUsingEncoding(_webRequest, returnBytes);
            }
        }
        catch (Exception ex) when (!(ex is OutOfMemoryException))
        {
            exception = GetExceptionToPropagate(ex);
        }
        DownloadStringCompletedEventArgs eventArgs = new DownloadStringCompletedEventArgs(result, exception, _canceled, asyncOperation.UserSuppliedState);
        InvokeOperationCompleted(asyncOperation, _downloadStringOperationCompleted, eventArgs);
    }
References System.Net.WebClient._canceled, System.Net.WebClient._downloadStringOperationCompleted, System.Net.WebClient._webRequest, System.exception, System.Net.WebClient.GetExceptionToPropagate(), System.Net.WebClient.GetStringUsingEncoding(), System.Net.WebClient.InvokeOperationCompleted(), System.state, and System.ComponentModel.AsyncOperation.UserSuppliedState.
Referenced by System.Net.WebClient.DownloadStringAsync().