Terraria: CreditsRollComposer.PlaySegment_Grox_WitchDoctorGoingToHisPeople
PlaySegment_Grox_WitchDoctorGoingToHisPeople()
SegmentInforReport CreditsRollComposer.PlaySegment_Grox_WitchDoctorGoingToHisPeople (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         int num2 = 0;
         sceneAnchorPosition.X += num2;
         int num3 = 60;
         Asset<Texture2D> val = TextureAssets.Extra[231];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, startTime, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
             .Then(new Actions.Sprites.Wait(120));
         _segments.Add(animationSegmentWithActions);
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 228, sceneAnchorPosition + new Vector2(-60f, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 120));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 663, sceneAnchorPosition + new Vector2(-110f, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 120));
         Point[] frameIndices = new Point[5]
         {
             new Point(0, 3),
             new Point(0, 4),
             new Point(0, 5),
             new Point(0, 6),
             new Point(0, 7)
         };
         Point[] frameIndices2 = new Point[4]
         {
             new Point(0, 3),
             new Point(0, 2),
             new Point(0, 1),
             new Point(0, 0)
         };
         Main.instance.LoadNPC(199);
         Asset<Texture2D> val2 = TextureAssets.Npc[199];
         Rectangle rectangle2 = val2.Frame(1, Main.npcFrameCount[199]);
         DrawData data2 = new DrawData(val2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, SpriteEffects.None);
         new DrawData(val2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, SpriteEffects.FlipHorizontally);
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions4 = new Segments.NPCSegment(startTime, 198, sceneAnchorPosition + new Vector2(num3 * 2, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Wait(120));
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions5 = new Segments.SpriteSegment(val2, startTime, data2, sceneAnchorPosition + new Vector2(num3 * 3 - 20 + 120, 4f)).Then(new Actions.Sprites.SetFrame(0, 3, 0, 0)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 25))
             .Then(new Actions.Sprites.SimulateGravity(new Vector2(-1f, 0f), Vector2.Zero, 0f, 120))
             .With(new Actions.Sprites.SetFrameSequence(120, frameIndices, 6, 0, 0));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         int num4 = 120;
         Segments.EmoteSegment item = new Segments.EmoteSegment(10, num, num4, sceneAnchorPosition + new Vector2(0f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         int num5 = 6;
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions5.Then(new Actions.Sprites.SetFrameSequence(frameIndices2, num5, 0, 0));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         int durationInFrames = num4 - num5 * 4;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions6 = new Segments.NPCSegment(num - num4 + num5 * 4, 198, sceneAnchorPosition + new Vector2(num3 * 3 - 20, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Wait(durationInFrames));
         Segments.EmoteSegment item2 = new Segments.EmoteSegment(92, num, num4, sceneAnchorPosition + new Vector2(-50f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions2.Then(new Actions.NPCs.LookAt(-1));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         int num6 = 60;
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), num6));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
         num += num6;
         Segments.EmoteSegment item3 = new Segments.EmoteSegment(87, num, num4, sceneAnchorPosition + new Vector2(num3 * 2, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4)).Then(new Actions.NPCs.LookAt(-1));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4)).Then(new Actions.NPCs.LookAt(-1));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         Segments.EmoteSegment item4 = new Segments.EmoteSegment(49, num, num4, sceneAnchorPosition + new Vector2(30f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         int num7 = num4 + num4 / 2;
         Segments.EmoteSegment item5 = new Segments.EmoteSegment(10, num, num4, sceneAnchorPosition + new Vector2(num3 * 2, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         Segments.EmoteSegment item6 = new Segments.EmoteSegment(0, num + num4 / 2, num4, sceneAnchorPosition + new Vector2(num3 * 3 - 20, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num7));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num7));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num7));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num7));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num7));
         num += num7;
         Segments.EmoteSegment item7 = new Segments.EmoteSegment(17, num, num4, sceneAnchorPosition + new Vector2(-50f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item8 = new Segments.EmoteSegment(3, num, num4, sceneAnchorPosition + new Vector2(30f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(-0.4f, 0f), 160)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 160)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(-0.8f, 0f), 160)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions6.Then(new Actions.NPCs.Move(new Vector2(-0.8f, 0f), 160)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
         num += 187;
         _segments.Add(animationSegmentWithActions4);
         _segments.Add(animationSegmentWithActions6);
         _segments.Add(animationSegmentWithActions5);
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(item);
         _segments.Add(item2);
         _segments.Add(item3);
         _segments.Add(item4);
         _segments.Add(item5);
         _segments.Add(item6);
         _segments.Add(item8);
         _segments.Add(item7);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References _backgroundOffset, _emoteBubbleOffsetWhenOnLeft, _emoteBubbleOffsetWhenOnRight, _originAtBottom, _segments, Color, TextureAssets.Extra, GetSceneFixVector(), Main.instance, Main.LoadNPC(), TextureAssets.Npc, Main.npcFrameCount, Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().