Terraria: System.Net.WebClient.MapToDefaultMethod
MapToDefaultMethod()
string System.Net.WebClient.MapToDefaultMethod (Uri address) inline private
Definition at line 1354 of file WebClient.cs.
    {
        Uri uri = ((!address.IsAbsoluteUri && _baseAddress != null) ? new Uri(_baseAddress, address) : address);
        if (!string.Equals(uri.Scheme, Uri.UriSchemeFtp, StringComparison.Ordinal))
        {
            return "POST";
        }
        return "STOR";
    }
References System.Net.WebClient._baseAddress, System.Net.Equals, System.Uri.Scheme, and System.Uri.UriSchemeFtp.
Referenced by System.Net.WebClient.OpenWrite(), System.Net.WebClient.OpenWriteAsync(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadString(), System.Net.WebClient.UploadStringAsync(), System.Net.WebClient.UploadValues(), and System.Net.WebClient.UploadValuesAsync().