Terraria: System.Net.WebClient.OpenFileInternal
OpenFileInternal()
void System.Net.WebClient.OpenFileInternal (bool needsHeaderAndBoundary, string fileName, out FileStream fs, out byte[] buffer, ref byte[] formHeaderBytes, ref byte[] boundaryBytes) inline private
Definition at line 691 of file WebClient.cs.
    {
        fileName = Path.GetFullPath(fileName);
        WebHeaderCollection headers = Headers;
        string text = headers["Content-Type"];
        if (text == null)
        {
            text = "application/octet-stream";
        }
        else if (text.StartsWith("multipart/", StringComparison.OrdinalIgnoreCase))
        {
            throw new WebException(System.SR.net_webclient_Multipart);
        }
        fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
        int num = 8192;
        _contentLength = -1L;
        if (string.Equals(_method, "POST", StringComparison.Ordinal))
        {
            if (needsHeaderAndBoundary)
            {
                string text2 = $"---------------------{DateTime.Now.Ticks:x}";
                headers["Content-Type"] = "multipart/form-data; boundary=" + text2;
                string s = "--" + text2 + "\r\nContent-Disposition: form-data; name=\"file\"; filename=\"" + Path.GetFileName(fileName) + "\"\r\nContent-Type: " + text + "\r\n\r\n";
                formHeaderBytes = System.Text.Encoding.UTF8.GetBytes(s);
                boundaryBytes = System.Text.Encoding.ASCII.GetBytes("\r\n--" + text2 + "--\r\n");
            }
            else
            {
                formHeaderBytes = Array.Empty<byte>();
                boundaryBytes = Array.Empty<byte>();
            }
            if (fs.CanSeek)
            {
                _contentLength = fs.Length + formHeaderBytes.Length + boundaryBytes.Length;
                num = (int)Math.Min(8192L, fs.Length);
            }
        }
        else
        {
            headers["Content-Type"] = text;
            formHeaderBytes = null;
            boundaryBytes = null;
            if (fs.CanSeek)
            {
                _contentLength = fs.Length;
                num = (int)Math.Min(8192L, fs.Length);
            }
        }
        buffer = new byte[num];
    }
References System.Net.WebClient._contentLength, System.Net.WebClient._method, System.Text.Encoding.ASCII, System.buffer, System.Net.Equals, System.IO.Path.GetFileName(), System.IO.Path.GetFullPath(), System.Net.WebClient.Headers, System.L, System.Math.Min(), System.SR.net_webclient_Multipart, System.s, System.text, and System.Text.Encoding.UTF8.
Referenced by System.Net.WebClient.UploadFile(), and System.Net.WebClient.UploadFileAsync().