Terraria: System.Net.WebClient.GetExceptionToPropagate
GetExceptionToPropagate()
static Exception System.Net.WebClient.GetExceptionToPropagate (Exception e) inline static private
Definition at line 1792 of file WebClient.cs.
    {
        if (!(e is WebException) && !(e is SecurityException))
        {
            return new WebException(System.SR.net_webclient, e);
        }
        return e;
    }
References System.SR.net_webclient.
Referenced by System.Net.WebClient.DownloadBitsAsync(), System.Net.WebClient.DownloadDataAsync(), System.Net.WebClient.DownloadFileAsync(), System.Net.WebClient.DownloadStringAsync(), System.Net.WebClient.DownloadStringAsyncCallback(), System.Net.WebClient.OpenReadAsync(), System.Net.WebClient.OpenWriteAsync(), System.Net.WebClient.UploadBitsAsync(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadStringAsync(), and System.Net.WebClient.UploadValuesAsync().