Terraria: System.Net.WebClient.StartOperation
StartOperation()
void System.Net.WebClient.StartOperation () inline private
Definition at line 351 of file WebClient.cs.
    {
        if (Interlocked.Increment(ref _callNesting) > 1)
        {
            EndOperation();
            throw new NotSupportedException(System.SR.net_webclient_no_concurrent_io_allowed);
        }
        _contentLength = -1L;
        _webResponse = null;
        _webRequest = null;
        _method = null;
        _canceled = false;
        _progress?.Reset();
    }
References System.Net.WebClient._callNesting, System.Net.WebClient._canceled, System.Net.WebClient._contentLength, System.Net.WebClient._method, System.Net.WebClient._progress, System.Net.WebClient._webRequest, System.Net.WebClient._webResponse, System.Net.WebClient.EndOperation(), System.Threading.Interlocked.Increment(), System.L, System.SR.net_webclient_no_concurrent_io_allowed, and System.Net.WebClient.ProgressData.Reset().
Referenced by System.Net.WebClient.DownloadData(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadString(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.StartAsyncOperation(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadString(), and System.Net.WebClient.UploadValues().