Terraria: System.Net.WebClient.StartAsyncOperation
StartAsyncOperation()
AsyncOperation System.Net.WebClient.StartAsyncOperation (object userToken) inline private
Definition at line 366 of file WebClient.cs.
    {
        if (!_initWebClientAsync)
        {
            _openReadOperationCompleted = delegate(object arg)
            {
                OnOpenReadCompleted((OpenReadCompletedEventArgs)arg);
            };
            _openWriteOperationCompleted = delegate(object arg)
            {
                OnOpenWriteCompleted((OpenWriteCompletedEventArgs)arg);
            };
            _downloadStringOperationCompleted = delegate(object arg)
            {
                OnDownloadStringCompleted((DownloadStringCompletedEventArgs)arg);
            };
            _downloadDataOperationCompleted = delegate(object arg)
            {
                OnDownloadDataCompleted((DownloadDataCompletedEventArgs)arg);
            };
            _downloadFileOperationCompleted = delegate(object arg)
            {
                OnDownloadFileCompleted((AsyncCompletedEventArgs)arg);
            };
            _uploadStringOperationCompleted = delegate(object arg)
            {
                OnUploadStringCompleted((UploadStringCompletedEventArgs)arg);
            };
            _uploadDataOperationCompleted = delegate(object arg)
            {
                OnUploadDataCompleted((UploadDataCompletedEventArgs)arg);
            };
            _uploadFileOperationCompleted = delegate(object arg)
            {
                OnUploadFileCompleted((UploadFileCompletedEventArgs)arg);
            };
            _uploadValuesOperationCompleted = delegate(object arg)
            {
                OnUploadValuesCompleted((UploadValuesCompletedEventArgs)arg);
            };
            _reportDownloadProgressChanged = delegate(object arg)
            {
                OnDownloadProgressChanged((DownloadProgressChangedEventArgs)arg);
            };
            _reportUploadProgressChanged = delegate(object arg)
            {
                OnUploadProgressChanged((UploadProgressChangedEventArgs)arg);
            };
            _progress = new ProgressData();
            _initWebClientAsync = true;
        }
        AsyncOperation asyncOperation = AsyncOperationManager.CreateOperation(userToken);
        StartOperation();
        _asyncOp = asyncOperation;
        return asyncOperation;
    }
References System.Net.WebClient._asyncOp, System.Net.WebClient._downloadDataOperationCompleted, System.Net.WebClient._downloadFileOperationCompleted, System.Net.WebClient._downloadStringOperationCompleted, System.Net.WebClient._initWebClientAsync, System.Net.WebClient._openReadOperationCompleted, System.Net.WebClient._openWriteOperationCompleted, System.Net.WebClient._progress, System.Net.WebClient._reportDownloadProgressChanged, System.Net.WebClient._reportUploadProgressChanged, System.Net.WebClient._uploadDataOperationCompleted, System.Net.WebClient._uploadFileOperationCompleted, System.Net.WebClient._uploadStringOperationCompleted, System.Net.WebClient._uploadValuesOperationCompleted, System.ComponentModel.AsyncOperationManager.CreateOperation(), System.Net.WebClient.OnDownloadDataCompleted(), System.Net.WebClient.OnDownloadFileCompleted(), System.Net.WebClient.OnDownloadProgressChanged(), System.Net.WebClient.OnDownloadStringCompleted(), System.Net.WebClient.OnOpenReadCompleted(), System.Net.WebClient.OnOpenWriteCompleted(), System.Net.WebClient.OnUploadDataCompleted(), System.Net.WebClient.OnUploadFileCompleted(), System.Net.WebClient.OnUploadProgressChanged(), System.Net.WebClient.OnUploadStringCompleted(), System.Net.WebClient.OnUploadValuesCompleted(), and System.Net.WebClient.StartOperation().
Referenced by System.Net.WebClient.DownloadDataAsync(), System.Net.WebClient.DownloadFileAsync(), System.Net.WebClient.DownloadStringAsync(), System.Net.WebClient.OpenReadAsync(), System.Net.WebClient.OpenWriteAsync(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadFileAsync(), System.Net.WebClient.UploadStringAsync(), and System.Net.WebClient.UploadValuesAsync().