Terraria: System.Net.WebClient.GetValuesToUpload
GetValuesToUpload()
byte[] System.Net.WebClient.GetValuesToUpload (NameValueCollection data) inline private
Definition at line 799 of file WebClient.cs.
    {
        WebHeaderCollection headers = Headers;
        string text = headers["Content-Type"];
        if (text != null && !string.Equals(text, "application/x-www-form-urlencoded", StringComparison.OrdinalIgnoreCase))
        {
            throw new WebException(System.SR.net_webclient_ContentType);
        }
        headers["Content-Type"] = "application/x-www-form-urlencoded";
        string value = string.Empty;
        StringBuilder stringBuilder = new StringBuilder();
        string[] allKeys = data.AllKeys;
        foreach (string text2 in allKeys)
        {
            stringBuilder.Append(value);
            stringBuilder.Append(UrlEncode(text2));
            stringBuilder.Append('=');
            stringBuilder.Append(UrlEncode(data[text2]));
            value = "&";
        }
        byte[] bytes = System.Text.Encoding.ASCII.GetBytes(stringBuilder.ToString());
        _contentLength = bytes.Length;
        return bytes;
    }
References System.Net.WebClient._contentLength, System.Collections.Specialized.NameValueCollection.AllKeys, System.Text.Encoding.ASCII, System.bytes, System.Net.Equals, System.Net.WebClient.Headers, System.SR.net_webclient_ContentType, System.text, System.Net.WebClient.UrlEncode(), and System.value.
Referenced by System.Net.WebClient.UploadValues(), and System.Net.WebClient.UploadValuesAsync().