Terraria: System.Net.WebClient.EndOperation
EndOperation()
void System.Net.WebClient.EndOperation () inline private
Definition at line 423 of file WebClient.cs.
    {
        Interlocked.Decrement(ref _callNesting);
    }
References System.Net.WebClient._callNesting, and System.Threading.Interlocked.Decrement().
Referenced by System.Net.WebClient.DownloadData(), System.Net.WebClient.DownloadFile(), System.Net.WebClient.DownloadString(), System.Net.WebClient.InvokeOperationCompleted(), System.Net.WebClient.OpenRead(), System.Net.WebClient.OpenWrite(), System.Net.WebClient.StartOperation(), System.Net.WebClient.UploadData(), System.Net.WebClient.UploadFile(), System.Net.WebClient.UploadString(), and System.Net.WebClient.UploadValues().