Terraria: System.Net.WebClient.GetUri
GetUri() [2/2]
Uri System.Net.WebClient.GetUri (Uri address) inline private
Definition at line 1008 of file WebClient.cs.
    {
        ArgumentNullException.ThrowIfNull(address, "address");
        Uri result = address;
        if (!address.IsAbsoluteUri && _baseAddress != null && !Uri.TryCreate(_baseAddress, address, out result))
        {
            return address;
        }
        if (string.IsNullOrEmpty(result.Query) && _requestParameters != null)
        {
            StringBuilder stringBuilder = new StringBuilder();
            string value = string.Empty;
            for (int i = 0; i < _requestParameters.Count; i++)
            {
                stringBuilder.Append(value).Append(_requestParameters.AllKeys[i]).Append('=')
                    .Append(_requestParameters[i]);
                value = "&";
            }
            result = new UriBuilder(result)
            {
                Query = stringBuilder.ToString()
            }.Uri;
        }
        return result;
    }
References System.Net.WebClient._baseAddress, System.Net.WebClient._requestParameters, System.Collections.Specialized.NameValueCollection.AllKeys, System.Text.StringBuilder.Append(), System.Collections.Specialized.NameObjectCollectionBase.Count, System.Uri.IsAbsoluteUri, System.Uri.Query, System.Query, System.ArgumentNullException.ThrowIfNull(), System.Text.StringBuilder.ToString(), System.Uri.TryCreate(), and System.value.