Terraria: System.Xml.XsdCachingReader.ReadAsync
ReadAsync()
override async Task< bool > System.Xml.XsdCachingReader.ReadAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 558 of file XsdCachingReader.cs.
    {
        switch (_cacheState)
        {
        case CachingReaderState.Init:
            _cacheState = CachingReaderState.Record;
            goto case CachingReaderState.Record;
        case CachingReaderState.Record:
        {
            ValidatingReaderNodeData recordedNode = null;
            if (await _coreReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false))
            {
                switch (_coreReader.NodeType)
                {
                case XmlNodeType.Element:
                    _cacheState = CachingReaderState.ReaderClosed;
                    return false;
                case XmlNodeType.EndElement:
                    recordedNode = AddContent(_coreReader.NodeType);
                    recordedNode.SetItemData(_coreReader.LocalName, _coreReader.Prefix, _coreReader.NamespaceURI, _coreReader.Depth);
                    recordedNode.SetLineInfo(_lineInfo);
                    break;
                case XmlNodeType.Text:
                case XmlNodeType.CDATA:
                case XmlNodeType.ProcessingInstruction:
                case XmlNodeType.Comment:
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                {
                    recordedNode = AddContent(_coreReader.NodeType);
                    ValidatingReaderNodeData validatingReaderNodeData = recordedNode;
                    validatingReaderNodeData.SetItemData(await _coreReader.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false));
                    recordedNode.SetLineInfo(_lineInfo);
                    recordedNode.Depth = _coreReader.Depth;
                    break;
                }
                }
                _cachedNode = recordedNode;
                return true;
            }
            _cacheState = CachingReaderState.ReaderClosed;
            return false;
        }
        case CachingReaderState.Replay:
            if (_currentContentIndex >= _contentIndex)
            {
                _cacheState = CachingReaderState.ReaderClosed;
                _cacheHandler(this);
                if (_coreReader.NodeType != XmlNodeType.Element || _readAhead)
                {
                    return await _coreReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                return true;
            }
            _cachedNode = _contentEvents[_currentContentIndex];
            if (_currentContentIndex > 0)
            {
                ClearAttributesInfo();
            }
            _currentContentIndex++;
            return true;
        default:
            return false;
        }
    }
References System.Xml.XsdCachingReader._cachedNode, System.Xml.XsdCachingReader._cacheHandler, System.Xml.XsdCachingReader._cacheState, System.Xml.XsdCachingReader._contentEvents, System.Xml.XsdCachingReader._contentIndex, System.Xml.XsdCachingReader._coreReader, System.Xml.XsdCachingReader._currentContentIndex, System.Xml.XsdCachingReader._lineInfo, System.Xml.XsdCachingReader._readAhead, System.Xml.XsdCachingReader.AddContent(), System.Xml.XsdCachingReader.ClearAttributesInfo(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.GetValueAsync(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.ReadAsync(), and System.Xml.ValidatingReaderNodeData.SetItemData().
Referenced by System.Xml.XsdCachingReader.SetToReplayModeAsync(), and System.Xml.XsdCachingReader.SkipAsync().