Terraria: System.Xml.XsdCachingReader.AddContent
AddContent()
ValidatingReaderNodeData System.Xml.XsdCachingReader.AddContent (XmlNodeType nodeType) inline private
Definition at line 458 of file XsdCachingReader.cs.
    {
        ValidatingReaderNodeData validatingReaderNodeData = _contentEvents[_contentIndex];
        if (validatingReaderNodeData != null)
        {
            validatingReaderNodeData.Clear(nodeType);
            _contentIndex++;
            return validatingReaderNodeData;
        }
        if (_contentIndex >= _contentEvents.Length - 1)
        {
            ValidatingReaderNodeData[] array = new ValidatingReaderNodeData[_contentEvents.Length * 2];
            Array.Copy(_contentEvents, array, _contentEvents.Length);
            _contentEvents = array;
        }
        validatingReaderNodeData = _contentEvents[_contentIndex];
        if (validatingReaderNodeData == null)
        {
            validatingReaderNodeData = new ValidatingReaderNodeData(nodeType);
            _contentEvents[_contentIndex] = validatingReaderNodeData;
        }
        _contentIndex++;
        return validatingReaderNodeData;
    }
References System.Xml.XsdCachingReader._contentEvents, System.Xml.XsdCachingReader._contentIndex, System.array, System.Xml.ValidatingReaderNodeData.Clear(), System.Array.Copy(), and System.Xml.Dictionary.
Referenced by System.Xml.XsdCachingReader.Init(), System.Xml.XsdCachingReader.Read(), System.Xml.XsdCachingReader.ReadAsync(), System.Xml.XsdCachingReader.RecordEndElementNode(), and System.Xml.XsdCachingReader.RecordTextNode().