Terraria: System.Xml.XsdCachingReader.SwitchTextNodeAndEndElement
SwitchTextNodeAndEndElement()
void System.Xml.XsdCachingReader.SwitchTextNodeAndEndElement (string textValue, string originalStringValue) inline package
Definition at line 328 of file XsdCachingReader.cs.
    {
        ValidatingReaderNodeData validatingReaderNodeData = RecordTextNode(textValue, originalStringValue, _coreReader.Depth + 1, 0, 0);
        int num = _contentIndex - 2;
        ValidatingReaderNodeData validatingReaderNodeData2 = _contentEvents[num];
        _contentEvents[num] = validatingReaderNodeData;
        _contentEvents[_contentIndex - 1] = validatingReaderNodeData2;
    }
References System.Xml.XsdCachingReader._contentEvents, System.Xml.XsdCachingReader._contentIndex, System.Xml.XsdCachingReader._coreReader, System.Xml.XmlReader.Depth, System.Xml.Dictionary, and System.Xml.XsdCachingReader.RecordTextNode().
Referenced by System.Xml.XsdValidatingReader.GetIsDefault(), and System.Xml.XsdValidatingReader.ReadAheadForMemberType().