Terraria: System.Xml.XsdCachingReader.Read
Read()
override bool System.Xml.XsdCachingReader.Read () inline
Definition at line 256 of file XsdCachingReader.cs.
    {
        switch (_cacheState)
        {
        case CachingReaderState.Init:
            _cacheState = CachingReaderState.Record;
            goto case CachingReaderState.Record;
        case CachingReaderState.Record:
        {
            ValidatingReaderNodeData validatingReaderNodeData = null;
            if (_coreReader.Read())
            {
                switch (_coreReader.NodeType)
                {
                case XmlNodeType.Element:
                    _cacheState = CachingReaderState.ReaderClosed;
                    return false;
                case XmlNodeType.EndElement:
                    validatingReaderNodeData = AddContent(_coreReader.NodeType);
                    validatingReaderNodeData.SetItemData(_coreReader.LocalName, _coreReader.Prefix, _coreReader.NamespaceURI, _coreReader.Depth);
                    validatingReaderNodeData.SetLineInfo(_lineInfo);
                    break;
                case XmlNodeType.Text:
                case XmlNodeType.CDATA:
                case XmlNodeType.ProcessingInstruction:
                case XmlNodeType.Comment:
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                    validatingReaderNodeData = AddContent(_coreReader.NodeType);
                    validatingReaderNodeData.SetItemData(_coreReader.Value);
                    validatingReaderNodeData.SetLineInfo(_lineInfo);
                    validatingReaderNodeData.Depth = _coreReader.Depth;
                    break;
                }
                _cachedNode = validatingReaderNodeData;
                return true;
            }
            _cacheState = CachingReaderState.ReaderClosed;
            return false;
        }
        case CachingReaderState.Replay:
            if (_currentContentIndex >= _contentIndex)
            {
                _cacheState = CachingReaderState.ReaderClosed;
                _cacheHandler(this);
                if (_coreReader.NodeType != XmlNodeType.Element || _readAhead)
                {
                    return _coreReader.Read();
                }
                return true;
            }
            _cachedNode = _contentEvents[_currentContentIndex];
            if (_currentContentIndex > 0)
            {
                ClearAttributesInfo();
            }
            _currentContentIndex++;
            return true;
        default:
            return false;
        }
    }
References System.Xml.XsdCachingReader._cachedNode, System.Xml.XsdCachingReader._cacheHandler, System.Xml.XsdCachingReader._cacheState, System.Xml.XsdCachingReader._contentEvents, System.Xml.XsdCachingReader._contentIndex, System.Xml.XsdCachingReader._coreReader, System.Xml.XsdCachingReader._currentContentIndex, System.Xml.XsdCachingReader._lineInfo, System.Xml.XsdCachingReader._readAhead, System.Xml.XsdCachingReader.AddContent(), System.Xml.XsdCachingReader.ClearAttributesInfo(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.XsdCachingReader.MoveToElement(), System.Xml.XsdCachingReader.SetToReplayMode(), and System.Xml.XsdCachingReader.Skip().