Terraria: System.Xml.XsdCachingReader.AddAttribute
AddAttribute()
ValidatingReaderNodeData System.Xml.XsdCachingReader.AddAttribute (int attIndex) inline private
Definition at line 435 of file XsdCachingReader.cs.
    {
        ValidatingReaderNodeData validatingReaderNodeData = _attributeEvents[attIndex];
        if (validatingReaderNodeData != null)
        {
            validatingReaderNodeData.Clear(XmlNodeType.Attribute);
            return validatingReaderNodeData;
        }
        if (attIndex >= _attributeEvents.Length - 1)
        {
            ValidatingReaderNodeData[] array = new ValidatingReaderNodeData[_attributeEvents.Length * 2];
            Array.Copy(_attributeEvents, array, _attributeEvents.Length);
            _attributeEvents = array;
        }
        validatingReaderNodeData = _attributeEvents[attIndex];
        if (validatingReaderNodeData == null)
        {
            validatingReaderNodeData = new ValidatingReaderNodeData(XmlNodeType.Attribute);
            _attributeEvents[attIndex] = validatingReaderNodeData;
        }
        return validatingReaderNodeData;
    }
References System.Xml.XsdCachingReader._attributeEvents, System.array, System.Xml.ValidatingReaderNodeData.Clear(), System.Array.Copy(), and System.Xml.Dictionary.
Referenced by System.Xml.XsdCachingReader.RecordAttributes().