Terraria: System.Xml.XsdCachingReader.RecordAttributes
RecordAttributes()
void System.Xml.XsdCachingReader.RecordAttributes () inline private
Definition at line 483 of file XsdCachingReader.cs.
    {
        _attributeCount = _coreReader.AttributeCount;
        if (_coreReader.MoveToFirstAttribute())
        {
            int num = 0;
            do
            {
                ValidatingReaderNodeData validatingReaderNodeData = AddAttribute(num);
                validatingReaderNodeData.SetItemData(_coreReader.LocalName, _coreReader.Prefix, _coreReader.NamespaceURI, _coreReader.Depth);
                validatingReaderNodeData.SetLineInfo(_lineInfo);
                validatingReaderNodeData.RawValue = _coreReader.Value;
                num++;
            }
            while (_coreReader.MoveToNextAttribute());
            _coreReader.MoveToElement();
        }
    }
References System.Xml.XsdCachingReader._attributeCount, System.Xml.XsdCachingReader._coreReader, System.Xml.XsdCachingReader._lineInfo, System.Xml.XsdCachingReader.AddAttribute(), System.Xml.XmlReader.AttributeCount, System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.Prefix, and System.Xml.XmlReader.Value.
Referenced by System.Xml.XsdCachingReader.Init().