Terraria: System.Xml.XsdCachingReader.MoveToElement
MoveToElement()
override bool System.Xml.XsdCachingReader.MoveToElement () inline
Definition at line 244 of file XsdCachingReader.cs.
    {
        if (_cacheState != CachingReaderState.Replay || _cachedNode.NodeType != XmlNodeType.Attribute)
        {
            return false;
        }
        _currentContentIndex = 0;
        _currentAttrIndex = -1;
        Read();
        return true;
    }
References System.Xml.XsdCachingReader._cachedNode, System.Xml.XsdCachingReader._cacheState, System.Xml.XsdCachingReader._currentAttrIndex, System.Xml.XsdCachingReader._currentContentIndex, System.Xml.ValidatingReaderNodeData.NodeType, and System.Xml.XsdCachingReader.Read().
Referenced by System.Xml.XsdCachingReader.Skip(), and System.Xml.XsdCachingReader.SkipAsync().