Terraria: System.Xml.XsdCachingReader.RecordEndElementNode
RecordEndElementNode()
void System.Xml.XsdCachingReader.RecordEndElementNode () inline package
Definition at line 337 of file XsdCachingReader.cs.
    {
        ValidatingReaderNodeData validatingReaderNodeData = AddContent(XmlNodeType.EndElement);
        validatingReaderNodeData.SetItemData(_coreReader.LocalName, _coreReader.Prefix, _coreReader.NamespaceURI, _coreReader.Depth);
        validatingReaderNodeData.SetLineInfo(_coreReader as IXmlLineInfo);
        if (_coreReader.IsEmptyElement)
        {
            _readAhead = true;
        }
    }
References System.Xml.XsdCachingReader._coreReader, System.Xml.XsdCachingReader._readAhead, System.Xml.XsdCachingReader.AddContent(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, and System.Xml.XmlReader.Prefix.
Referenced by System.Xml.XsdValidatingReader.ProcessEndElementEvent(), and System.Xml.XsdValidatingReader.ProcessEndElementEventAsync().