Terraria: System.Xml.XsdCachingReader.SetToReplayMode
SetToReplayMode()
void System.Xml.XsdCachingReader.SetToReplayMode () inline package
Definition at line 411 of file XsdCachingReader.cs.
    {
        _cacheState = CachingReaderState.Replay;
        _currentContentIndex = 0;
        _currentAttrIndex = -1;
        Read();
    }
References System.Xml.XsdCachingReader._cacheState, System.Xml.XsdCachingReader._currentAttrIndex, System.Xml.XsdCachingReader._currentContentIndex, and System.Xml.XsdCachingReader.Read().
Referenced by System.Xml.XsdValidatingReader.GetIsDefault(), System.Xml.XsdValidatingReader.GetMemberType(), and System.Xml.XsdValidatingReader.ProcessEndElementEvent().