Terraria: System.Xml.XsdCachingReader.SkipAsync
SkipAsync()
override async Task System.Xml.XsdCachingReader.SkipAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 624 of file XsdCachingReader.cs.
    {
        XmlNodeType nodeType = _cachedNode.NodeType;
        if (nodeType != XmlNodeType.Element)
        {
            if (nodeType != XmlNodeType.Attribute)
            {
                await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
                return;
            }
            MoveToElement();
        }
        if (_coreReader.NodeType != XmlNodeType.EndElement && !_readAhead)
        {
            int startDepth = _coreReader.Depth - 1;
            while (await _coreReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false) && _coreReader.Depth > startDepth)
            {
            }
        }
        await _coreReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
        _cacheState = CachingReaderState.ReaderClosed;
        _cacheHandler(this);
    }
References System.Xml.XsdCachingReader._cachedNode, System.Xml.XsdCachingReader._cacheHandler, System.Xml.XsdCachingReader._cacheState, System.Xml.XsdCachingReader._coreReader, System.Xml.XsdCachingReader._readAhead, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XsdCachingReader.MoveToElement(), System.Xml.ValidatingReaderNodeData.NodeType, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAsync(), and System.Xml.XsdCachingReader.ReadAsync().