Terraria: System.Xml.XsdCachingReader.Skip
Skip()
override void System.Xml.XsdCachingReader.Skip () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 362 of file XsdCachingReader.cs.
    {
        XmlNodeType nodeType = _cachedNode.NodeType;
        if (nodeType != XmlNodeType.Element)
        {
            if (nodeType != XmlNodeType.Attribute)
            {
                Read();
                return;
            }
            MoveToElement();
        }
        if (_coreReader.NodeType != XmlNodeType.EndElement && !_readAhead)
        {
            int num = _coreReader.Depth - 1;
            while (_coreReader.Read() && _coreReader.Depth > num)
            {
            }
        }
        _coreReader.Read();
        _cacheState = CachingReaderState.ReaderClosed;
        _cacheHandler(this);
    }
References System.Xml.XsdCachingReader._cachedNode, System.Xml.XsdCachingReader._cacheHandler, System.Xml.XsdCachingReader._cacheState, System.Xml.XsdCachingReader._coreReader, System.Xml.XsdCachingReader._readAhead, System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XsdCachingReader.MoveToElement(), System.Xml.ValidatingReaderNodeData.NodeType, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), and System.Xml.XsdCachingReader.Read().