Terraria: System.Xml.XsdCachingReader.Init
Init()
void System.Xml.XsdCachingReader.Init () inline private
Definition at line 125 of file XsdCachingReader.cs.
    {
        _coreReaderNameTable = _coreReader.NameTable;
        _cacheState = CachingReaderState.Init;
        _contentIndex = 0;
        _currentAttrIndex = -1;
        _currentContentIndex = -1;
        _attributeCount = 0;
        _cachedNode = null;
        _readAhead = false;
        if (_coreReader.NodeType == XmlNodeType.Element)
        {
            ValidatingReaderNodeData validatingReaderNodeData = AddContent(_coreReader.NodeType);
            validatingReaderNodeData.SetItemData(_coreReader.LocalName, _coreReader.Prefix, _coreReader.NamespaceURI, _coreReader.Depth);
            validatingReaderNodeData.SetLineInfo(_lineInfo);
            RecordAttributes();
        }
    }
References System.Xml.XsdCachingReader._attributeCount, System.Xml.XsdCachingReader._cachedNode, System.Xml.XsdCachingReader._cacheState, System.Xml.XsdCachingReader._contentIndex, System.Xml.XsdCachingReader._coreReader, System.Xml.XsdCachingReader._coreReaderNameTable, System.Xml.XsdCachingReader._currentAttrIndex, System.Xml.XsdCachingReader._currentContentIndex, System.Xml.XsdCachingReader._lineInfo, System.Xml.XsdCachingReader._readAhead, System.Xml.XsdCachingReader.AddContent(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NameTable, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, and System.Xml.XsdCachingReader.RecordAttributes().
Referenced by System.Xml.XsdCachingReader.XsdCachingReader(), and System.Xml.XsdCachingReader.Reset().