Terraria: System.Reflection.Emit.ParameterBuilder.SetCustomAttribute
SetCustomAttribute() [1/2]
void System.Reflection.Emit.ParameterBuilder.SetCustomAttribute (ConstructorInfo con, byte[] binaryAttribute) inline
Definition at line 34 of file ParameterBuilder.cs.
    {
        if (con == null)
        {
            throw new ArgumentNullException("con");
        }
        if (binaryAttribute == null)
        {
            throw new ArgumentNullException("binaryAttribute");
        }
        TypeBuilder.DefineCustomAttribute(_methodBuilder.GetModuleBuilder(), _token, ((ModuleBuilder)_methodBuilder.GetModule()).GetConstructorToken(con), binaryAttribute);
    }
References System.Reflection.Emit.ParameterBuilder._methodBuilder, System.Reflection.Emit.ParameterBuilder._token, System.Reflection.Emit.TypeBuilder.DefineCustomAttribute(), System.Reflection.Emit.MethodBuilder.GetModule(), and System.Reflection.Emit.MethodBuilder.GetModuleBuilder().