Terraria: System.Runtime.InteropServices.StandardOleMarshalObject.GetStdMarshaler
GetStdMarshaler()
IntPtr System.Runtime.InteropServices.StandardOleMarshalObject.GetStdMarshaler (ref Guid riid, int dwDestContext, int mshlflags) inline private
Definition at line 17 of file StandardOleMarshalObject.cs.
    {
        IntPtr iUnknownForObject = Marshal.GetIUnknownForObject(this);
        if (iUnknownForObject != IntPtr.Zero)
        {
            try
            {
                IntPtr ppMarshal = IntPtr.Zero;
                if (Interop.Ole32.CoGetStandardMarshal(ref riid, iUnknownForObject, dwDestContext, IntPtr.Zero, mshlflags, out ppMarshal) == 0)
                {
                    return ppMarshal;
                }
            }
            finally
            {
                Marshal.Release(iUnknownForObject);
            }
        }
        throw new InvalidOperationException(SR.Format(SR.StandardOleMarshalObjectGetMarshalerFailed, riid));
    }
References Interop.Ole32.CoGetStandardMarshal(), System.SR.Format(), System.Runtime.InteropServices.Marshal.GetIUnknownForObject(), System.Runtime.InteropServices.Marshal.Release(), System.SR.StandardOleMarshalObjectGetMarshalerFailed, and System.IntPtr.Zero.
Referenced by System.Runtime.InteropServices.StandardOleMarshalObject.GetMarshalSizeMax(), and System.Runtime.InteropServices.StandardOleMarshalObject.MarshalInterface().