Terraria: System.Net.Http.HttpConnection.ChunkedEncodingReadStream.Read
Read() [2/2]
override int System.Net.Http.HttpConnection.ChunkedEncodingReadStream.Read (Span< byte > buffer) inline virtual
Reimplemented from System.Net.Http.HttpBaseStream.
Definition at line 43 of file HttpConnection.cs.
        {
            if (_connection == null || buffer.Length == 0)
            {
                return 0;
            }
            int num = ReadChunksFromConnectionBuffer(buffer, default(CancellationTokenRegistration));
            if (num > 0)
            {
                return num;
            }
            int num2;
            do
            {
                if (_connection == null)
                {
                    return 0;
                }
                if (_state == ParsingState.ExpectChunkData && buffer.Length >= _connection.ReadBufferSize && _chunkBytesRemaining >= (ulong)_connection.ReadBufferSize)
                {
                    num = _connection.Read(buffer.Slice(0, (int)Math.Min((ulong)buffer.Length, _chunkBytesRemaining)));
                    if (num == 0)
                    {
                        throw new IOException(System.SR.Format(System.SR.net_http_invalid_response_premature_eof_bytecount, _chunkBytesRemaining));
                    }
                    _chunkBytesRemaining -= (ulong)num;
                    if (_chunkBytesRemaining == 0L)
                    {
                        _state = ParsingState.ExpectChunkTerminator;
                    }
                    return num;
                }
                _connection.Fill();
                num2 = ReadChunksFromConnectionBuffer(buffer, default(CancellationTokenRegistration));
            }
            while (num2 <= 0);
            return num2;
        }
References System.Net.Http.HttpConnection.ChunkedEncodingReadStream._chunkBytesRemaining, System.Net.Http.HttpContentStream._connection, System.Net.Http.HttpConnection.ChunkedEncodingReadStream._state, System.buffer, System.Net.Http.HttpConnection.Fill(), System.SR.Format(), System.L, System.Math.Min(), System.SR.net_http_invalid_response_premature_eof_bytecount, System.Net.Http.HttpConnection.Read(), System.Net.Http.HttpConnection.ReadBufferSize, and System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunksFromConnectionBuffer().