Terraria: System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken) inline virtual
Reimplemented from System.Net.Http.HttpBaseStream.
Definition at line 82 of file HttpConnection.cs.
        {
            if (cancellationToken.IsCancellationRequested)
            {
                return ValueTask.FromCanceled<int>(cancellationToken);
            }
            if (_connection == null || buffer.Length == 0)
            {
                return new ValueTask<int>(0);
            }
            int num = ReadChunksFromConnectionBuffer(buffer.Span, default(CancellationTokenRegistration));
            if (num > 0)
            {
                return new ValueTask<int>(num);
            }
            if (_connection == null)
            {
                return new ValueTask<int>(0);
            }
            return ReadAsyncCore(buffer, cancellationToken);
        }
References System.Net.Http.HttpContentStream._connection, System.buffer, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(), and System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunksFromConnectionBuffer().