Terraria: System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ValidateChunkExtension
ValidateChunkExtension()
static void System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ValidateChunkExtension (ReadOnlySpan< byte > lineAfterChunkSize) inline static private
Definition at line 305 of file HttpConnection.cs.
        {
            for (int i = 0; i < lineAfterChunkSize.Length; i++)
            {
                switch (lineAfterChunkSize[i])
                {
                case 9:
                case 32:
                    continue;
                case 59:
                    return;
                }
                throw new IOException(System.SR.Format(System.SR.net_http_invalid_response_chunk_extension_invalid, BitConverter.ToString(lineAfterChunkSize.ToArray())));
            }
        }
References System.SR.Format(), System.SR.net_http_invalid_response_chunk_extension_invalid, and System.BitConverter.ToString().
Referenced by System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer().