Terraria: System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer
ReadChunkFromConnectionBuffer()
ReadOnlyMemory< byte > System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer (int maxBytesToRead, CancellationTokenRegistration cancellationRegistration) inline private
Definition at line 207 of file HttpConnection.cs.
        {
            try
            {
                ReadOnlySpan<byte> line;
                switch (_state)
                {
                case ParsingState.ExpectChunkHeader:
                {
                    _connection._allowedReadLineBytes = 16384;
                    if (!_connection.TryReadNextLine(out line))
                    {
                        return default(ReadOnlyMemory<byte>);
                    }
                    if (!Utf8Parser.TryParse(line, out ulong value, out int bytesConsumed, 'X'))
                    {
                        throw new IOException(System.SR.Format(System.SR.net_http_invalid_response_chunk_header_invalid, BitConverter.ToString(line.ToArray())));
                    }
                    _chunkBytesRemaining = value;
                    if (bytesConsumed != line.Length)
                    {
                        ValidateChunkExtension(line.Slice(bytesConsumed));
                    }
                    if (value != 0)
                    {
                        _state = ParsingState.ExpectChunkData;
                        goto case ParsingState.ExpectChunkData;
                    }
                    _state = ParsingState.ConsumeTrailers;
                    goto case ParsingState.ConsumeTrailers;
                }
                case ParsingState.ExpectChunkData:
                {
                    ReadOnlyMemory<byte> remainingBuffer = _connection.RemainingBuffer;
                    if (remainingBuffer.Length == 0)
                    {
                        return default(ReadOnlyMemory<byte>);
                    }
                    int num = Math.Min(maxBytesToRead, (int)Math.Min((ulong)remainingBuffer.Length, _chunkBytesRemaining));
                    _connection.ConsumeFromRemainingBuffer(num);
                    _chunkBytesRemaining -= (ulong)num;
                    if (_chunkBytesRemaining == 0L)
                    {
                        _state = ParsingState.ExpectChunkTerminator;
                    }
                    return remainingBuffer.Slice(0, num);
                }
                case ParsingState.ExpectChunkTerminator:
                    _connection._allowedReadLineBytes = 16384;
                    if (!_connection.TryReadNextLine(out line))
                    {
                        return default(ReadOnlyMemory<byte>);
                    }
                    if (line.Length != 0)
                    {
                        throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_chunk_terminator_invalid, Encoding.ASCII.GetString(line)));
                    }
                    _state = ParsingState.ExpectChunkHeader;
                    goto case ParsingState.ExpectChunkHeader;
                case ParsingState.ConsumeTrailers:
                    while (true)
                    {
                        _connection._allowedReadLineBytes = 16384;
                        if (!_connection.TryReadNextLine(out line))
{
                            break;
                        }
                        if (line.IsEmpty)
{
                            cancellationRegistration.Dispose();
                            CancellationHelper.ThrowIfCancellationRequested(cancellationRegistration.Token);
                            _state = ParsingState.Done;
                            _connection.CompleteResponse();
                            _connection = null;
                            break;
                        }
                        if (!base.IsDisposed)
{
                            ParseHeaderNameValue(_connection, line, _response, isFromTrailer: true);
                        }
                    }
                    return default(ReadOnlyMemory<byte>);
                default:
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Error(this, $"Unexpected state: {_state}", "ReadChunkFromConnectionBuffer");
                    }
                    return default(ReadOnlyMemory<byte>);
                }
            }
            catch (Exception)
            {
                _connection.Dispose();
                _connection = null;
                throw;
            }
        }
References System.Net.Http.HttpConnection.ChunkedEncodingReadStream._chunkBytesRemaining, System.Net.Http.HttpContentStream._connection, System.Net.Http.HttpConnection.ChunkedEncodingReadStream._response, System.Net.Http.HttpConnection.ChunkedEncodingReadStream._state, System.Text.Encoding.ASCII, System.Net.Http.HttpConnection.CompleteResponse(), System.Net.Http.HttpConnection.ConsumeFromRemainingBuffer(), System.Net.Http.HttpConnection.Dispose(), System.Net.NetEventSource.Error(), System.SR.Format(), System.L, System.Net.NetEventSource.Log, System.Math.Min(), System.SR.net_http_invalid_response_chunk_header_invalid, System.SR.net_http_invalid_response_chunk_terminator_invalid, System.Net.Http.HttpConnection.ParseHeaderNameValue(), System.Net.Http.HttpConnection.RemainingBuffer, System.Net.Http.CancellationHelper.ThrowIfCancellationRequested(), System.BitConverter.ToString(), System.Buffers.Text.Utf8Parser.TryParse(), System.Net.Http.HttpConnection.TryReadNextLine(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ValidateChunkExtension(), and System.value.
Referenced by System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.DrainAsync(), and System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunksFromConnectionBuffer().