Terraria: System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore
ReadAsyncCore()
async ValueTask< int > System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore (Memory< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 104 of file HttpConnection.cs.
        {
            CancellationTokenRegistration ctr = _connection.RegisterCancellation(cancellationToken);
            try
            {
                int num2;
                do
                {
                    if (_connection == null)
                    {
                        return 0;
                    }
                    if (_state == ParsingState.ExpectChunkData && buffer.Length >= _connection.ReadBufferSize && _chunkBytesRemaining >= (ulong)_connection.ReadBufferSize)
                    {
                        int num = await _connection.ReadAsync(buffer.Slice(0, (int)Math.Min((ulong)buffer.Length, _chunkBytesRemaining))).ConfigureAwait(continueOnCapturedContext: false);
                        if (num == 0)
{
                            throw new IOException(System.SR.Format(System.SR.net_http_invalid_response_premature_eof_bytecount, _chunkBytesRemaining));
                        }
                        _chunkBytesRemaining -= (ulong)num;
                        if (_chunkBytesRemaining == 0L)
{
                            _state = ParsingState.ExpectChunkTerminator;
                        }
                        return num;
                    }
                    await _connection.FillAsync(async: true).ConfigureAwait(continueOnCapturedContext: false);
                    num2 = ReadChunksFromConnectionBuffer(buffer.Span, ctr);
                }
                while (num2 <= 0);
                return num2;
            }
            catch (Exception ex) when (CancellationHelper.ShouldWrapInOperationCanceledException(ex, cancellationToken))
            {
                throw CancellationHelper.CreateOperationCanceledException(ex, cancellationToken);
            }
            finally
            {
                ctr.Dispose();
            }
        }
References System.Net.Http.HttpConnection.ChunkedEncodingReadStream._chunkBytesRemaining, System.Net.Http.HttpContentStream._connection, System.Net.Http.HttpConnection.ChunkedEncodingReadStream._state, System.buffer, System.cancellationToken, System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.Net.Http.HttpConnection.FillAsync(), System.SR.Format(), System.L, System.Math.Min(), System.SR.net_http_invalid_response_premature_eof_bytecount, System.Net.Http.HttpConnection.ReadAsync(), System.Net.Http.HttpConnection.ReadBufferSize, System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunksFromConnectionBuffer(), System.Net.Http.HttpConnection.RegisterCancellation(), and System.Net.Http.CancellationHelper.ShouldWrapInOperationCanceledException().
Referenced by System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsync().