Terraria: System.Runtime.InteropServices.StandardOleMarshalObject.MarshalInterface
MarshalInterface()
unsafe int IMarshal. System.Runtime.InteropServices.StandardOleMarshalObject.MarshalInterface (IntPtr pStm, ref Guid riid, IntPtr pv, int dwDestContext, IntPtr pvDestContext, int mshlflags) inline private
Implements System.Runtime.InteropServices.IMarshal.
Definition at line 60 of file StandardOleMarshalObject.cs.
    {
        IntPtr stdMarshaler = GetStdMarshaler(ref riid, dwDestContext, mshlflags);
        try
        {
            IntPtr intPtr = *(IntPtr*)stdMarshaler.ToPointer();
            IntPtr ptr = *(IntPtr*)((byte*)intPtr.ToPointer() + (nint)5 * (nint)sizeof(IntPtr));
            MarshalInterfaceDelegate marshalInterfaceDelegate = (MarshalInterfaceDelegate)Marshal.GetDelegateForFunctionPointer(ptr, typeof(MarshalInterfaceDelegate));
            return marshalInterfaceDelegate(stdMarshaler, pStm, ref riid, pv, dwDestContext, pvDestContext, mshlflags);
        }
        finally
        {
            Marshal.Release(stdMarshaler);
        }
    }
References System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(), System.Runtime.InteropServices.StandardOleMarshalObject.GetStdMarshaler(), System.Runtime.InteropServices.StandardOleMarshalObject.MarshalInterfaceDelegate(), System.Runtime.InteropServices.Marshal.Release(), and System.IntPtr.ToPointer().