Terraria: System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore
CopyToAsyncCore()
async Task System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore (Stream destination, CancellationToken cancellationToken) inline private
Definition at line 160 of file HttpConnection.cs.
        {
            CancellationTokenRegistration ctr = _connection.RegisterCancellation(cancellationToken);
            try
            {
                while (true)
                {
                    ReadOnlyMemory<byte> buffer = ReadChunkFromConnectionBuffer(int.MaxValue, ctr);
                    if (buffer.Length != 0)
                    {
                        await destination.WriteAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        continue;
                    }
                    if (_connection == null)
                    {
                        break;
                    }
                    await _connection.FillAsync(async: true).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            catch (Exception ex) when (CancellationHelper.ShouldWrapInOperationCanceledException(ex, cancellationToken))
            {
                throw CancellationHelper.CreateOperationCanceledException(ex, cancellationToken);
            }
            finally
            {
                ctr.Dispose();
            }
        }
References System.Net.Http.HttpContentStream._connection, System.buffer, System.cancellationToken, System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.destination, System.Net.Http.HttpConnection.FillAsync(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer(), System.Net.Http.HttpConnection.RegisterCancellation(), and System.Net.Http.CancellationHelper.ShouldWrapInOperationCanceledException().
Referenced by System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsync().