Terraria: ItemTagHandler.Parse
Parse()
TextSnippet ITagHandler. ItemTagHandler.Parse (string text, Color baseColor, string options) inline private
Implements ITagHandler.
     {
         Item item = new Item();
         if (int.TryParse(text, out var result))
         {
             item.netDefaults(result);
         }
         if (item.type <= 0)
         {
             return new TextSnippet(text);
         }
         item.stack = 1;
         if (options != null)
         {
             string[] array = options.Split(',');
             for (int i = 0; i < array.Length; i++)
             {
                 if (array[i].Length == 0)
                 {
                     continue;
                 }
                 switch (array[i][0])
                 {
                 case 's':
                 case 'x':
                 {
                     if (int.TryParse(array[i].Substring(1), out var result3))
                     {
                         item.stack = Utils.Clamp(result3, 1, item.maxStack);
                     }
                     break;
                 }
                 case 'p':
                 {
                     if (int.TryParse(array[i].Substring(1), out var result2))
                     {
                         item.Prefix((byte)Utils.Clamp(result2, 0, PrefixID.Count));
                     }
                     break;
                 }
                 }
             }
         }
         string text2 = "";
         if (item.stack > 1)
         {
             text2 = " (" + item.stack + ")";
         }
         return new ItemSnippet(item)
         {
             Text = "[" + item.AffixName() + text2 + "]",
             CheckForHover = true,
             DeleteWhole = true
         };
     }
References Item.AffixName(), PrefixID.Count, Item.maxStack, Item.netDefaults(), Item.Prefix(), Item.stack, and Item.type.