Terraria: PartyChatCommand.SendNoTeamError
SendNoTeamError()
void PartyChatCommand.SendNoTeamError (byte clientId) inline private
     {
         ChatHelper.SendChatMessageToClient(Lang.mp[10].ToNetworkText(), ERROR_COLOR, clientId);
     }
References ERROR_COLOR, Lang.mp, ChatHelper.SendChatMessageToClient(), and LocalizedText.ToNetworkText().
Referenced by ProcessIncomingMessage().