Terraria: System.Net.Base64Stream.ReadAsyncResult.CompleteRead
CompleteRead()
bool System.Net.Base64Stream.ReadAsyncResult.CompleteRead (IAsyncResult result) inline private
Definition at line 32 of file Base64Stream.cs.
        {
            _read = _parent.BaseStream.EndRead(result);
            if (_read == 0)
            {
                InvokeCallback();
                return true;
            }
            _read = _parent.DecodeBytes(_buffer, _offset, _read);
            if (_read > 0)
            {
                InvokeCallback();
                return true;
            }
            return false;
        }
References System.Net.Base64Stream.ReadAsyncResult._buffer, System.Net.Base64Stream.ReadAsyncResult._offset, System.Net.Base64Stream.ReadAsyncResult._parent, System.Net.Base64Stream.ReadAsyncResult._read, System.Net.DelegatedStream.BaseStream, System.Net.Base64Stream.DecodeBytes(), System.IO.Stream.EndRead(), and System.Net.LazyAsyncResult.InvokeCallback().
Referenced by System.Net.Base64Stream.ReadAsyncResult.OnRead(), and System.Net.Base64Stream.ReadAsyncResult.Read().