Terraria: UICreativePowersMenu.CreateMainPowerStrip
CreateMainPowerStrip()
List<UIElement> UICreativePowersMenu.CreateMainPowerStrip () inline private
     {
         MenuTree<OpenMainSubCategory> mainCategory = _mainCategory;
         mainCategory.Buttons.Clear();
         List<UIElement> list = new List<UIElement>();
         CreativePowerUIElementRequestInfo creativePowerUIElementRequestInfo = default(CreativePowerUIElementRequestInfo);
         creativePowerUIElementRequestInfo.PreferredButtonWidth = 40;
         creativePowerUIElementRequestInfo.PreferredButtonHeight = 40;
         CreativePowerUIElementRequestInfo request = creativePowerUIElementRequestInfo;
         GroupOptionButton<int> groupOptionButton = CreativePowersHelper.CreateCategoryButton(request, 1, 0);
         groupOptionButton.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.ItemDuplication));
         groupOptionButton.OnLeftClick += MainCategoryButtonClick;
         groupOptionButton.OnUpdate += itemsWindowButton_OnUpdate;
         mainCategory.Buttons.Add(1, groupOptionButton);
         list.Add(groupOptionButton);
         GroupOptionButton<int> groupOptionButton2 = CreativePowersHelper.CreateCategoryButton(request, 2, 0);
         groupOptionButton2.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.ItemResearch));
         groupOptionButton2.OnLeftClick += MainCategoryButtonClick;
         groupOptionButton2.OnUpdate += researchWindowButton_OnUpdate;
         mainCategory.Buttons.Add(2, groupOptionButton2);
         list.Add(groupOptionButton2);
         GroupOptionButton<int> groupOptionButton3 = CreativePowersHelper.CreateCategoryButton(request, 3, 0);
         groupOptionButton3.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.TimeCategory));
         groupOptionButton3.OnLeftClick += MainCategoryButtonClick;
         groupOptionButton3.OnUpdate += timeCategoryButton_OnUpdate;
         mainCategory.Buttons.Add(3, groupOptionButton3);
         list.Add(groupOptionButton3);
         GroupOptionButton<int> groupOptionButton4 = CreativePowersHelper.CreateCategoryButton(request, 4, 0);
         groupOptionButton4.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.WeatherCategory));
         groupOptionButton4.OnLeftClick += MainCategoryButtonClick;
         groupOptionButton4.OnUpdate += weatherCategoryButton_OnUpdate;
         mainCategory.Buttons.Add(4, groupOptionButton4);
         list.Add(groupOptionButton4);
         GroupOptionButton<int> groupOptionButton5 = CreativePowersHelper.CreateCategoryButton(request, 6, 0);
         groupOptionButton5.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.PersonalCategory));
         groupOptionButton5.OnLeftClick += MainCategoryButtonClick;
         groupOptionButton5.OnUpdate += personalCategoryButton_OnUpdate;
         mainCategory.Buttons.Add(6, groupOptionButton5);
         list.Add(groupOptionButton5);
         CreativePowerManager.Instance.GetPower<CreativePowers.StopBiomeSpreadPower>().ProvidePowerButtons(request, list);
         GroupOptionButton<int> groupOptionButton6 = CreateSubcategoryButton<CreativePowers.DifficultySliderPower>(ref request, 1, "strip 1", 5, 0, mainCategory.Buttons, mainCategory.Sliders);
         groupOptionButton6.OnLeftClick += MainCategoryButtonClick;
         list.Add(groupOptionButton6);
         return list;
     }
References _mainCategory, UIElement.Append(), UICreativePowersMenu.MenuTree< TEnum >.Buttons, CreativePowersHelper.GetIconImage(), CreativePowerManager.Instance, CreativePowersHelper.CreativePowerIconLocations.ItemDuplication, CreativePowersHelper.CreativePowerIconLocations.ItemResearch, itemsWindowButton_OnUpdate(), MainCategoryButtonClick(), UIElement.OnLeftClick, UIElement.OnUpdate, CreativePowersHelper.CreativePowerIconLocations.PersonalCategory, personalCategoryButton_OnUpdate(), CreativePowerUIElementRequestInfo.PreferredButtonHeight, CreativePowerUIElementRequestInfo.PreferredButtonWidth, researchWindowButton_OnUpdate(), UICreativePowersMenu.MenuTree< TEnum >.Sliders, CreativePowersHelper.CreativePowerIconLocations.TimeCategory, timeCategoryButton_OnUpdate(), CreativePowersHelper.CreativePowerIconLocations.WeatherCategory, and weatherCategoryButton_OnUpdate().
Referenced by InitializePage().