Terraria: UICreativePowersMenu.PersonalCategoryButtonClick
PersonalCategoryButtonClick()
void UICreativePowersMenu.PersonalCategoryButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         GroupOptionButton<int> groupOptionButton = listeningElement as GroupOptionButton<int>;
         int optionValue = groupOptionButton.OptionValue;
         if (optionValue != 1 || CreativePowerManager.Instance.GetPower<CreativePowers.SpawnRateSliderPerPlayerPower>().GetIsUnlocked())
         {
             TogglePersonalCategory(groupOptionButton.OptionValue);
             RefreshElementsOrder();
         }
     }
References CreativePowers.SpawnRateSliderPerPlayerPower.GetIsUnlocked(), CreativePowerManager.Instance, GroupOptionButton< T >.OptionValue, RefreshElementsOrder(), and TogglePersonalCategory().
Referenced by CreatePersonalPowerStrip().