Terraria: UICreativePowersMenu.CategoryButton_OnUpdate_DisplayTooltips
CategoryButton_OnUpdate_DisplayTooltips()
static void UICreativePowersMenu.CategoryButton_OnUpdate_DisplayTooltips (UIElement affectedElement, string categoryNameKey) inline static private
     {
         GroupOptionButton<int> groupOptionButton = affectedElement as GroupOptionButton<int>;
         if (affectedElement.IsMouseHovering)
         {
             string originalText = Language.GetTextValue(groupOptionButton.IsSelected ? (categoryNameKey + "Opened") : (categoryNameKey + "Closed"));
             CreativePowersHelper.AddDescriptionIfNeeded(ref originalText, categoryNameKey);
             Main.instance.MouseTextNoOverride(originalText, 0, 0);
         }
     }
References CreativePowersHelper.AddDescriptionIfNeeded(), Language.GetTextValue(), Main.instance, UIElement.IsMouseHovering, GroupOptionButton< T >.IsSelected, and Main.MouseTextNoOverride().
Referenced by itemsWindowButton_OnUpdate(), personalCategoryButton_OnUpdate(), researchWindowButton_OnUpdate(), timeCategoryButton_OnUpdate(), and weatherCategoryButton_OnUpdate().