Terraria: UICreativePowersMenu.RefreshElementsOrder
RefreshElementsOrder()
void UICreativePowersMenu.RefreshElementsOrder () inline private
     {
         _container.RemoveAllChildren();
         _container.Append(_mainPowerStrip);
         UIElement value = null;
         MenuTree<OpenMainSubCategory> mainCategory = _mainCategory;
         if (mainCategory.Sliders.TryGetValue(mainCategory.CurrentOption, out value))
         {
             _container.Append(value);
         }
         if (mainCategory.CurrentOption == 1)
         {
             _infiniteItemsWindow.SetPageTypeToShow(UICreativeInfiniteItemsDisplay.InfiniteItemsDisplayPage.InfiniteItemsPickup);
             _container.Append(_infiniteItemsWindow);
         }
         if (mainCategory.CurrentOption == 2)
         {
             _infiniteItemsWindow.SetPageTypeToShow(UICreativeInfiniteItemsDisplay.InfiniteItemsDisplayPage.InfiniteItemsResearch);
             _container.Append(_infiniteItemsWindow);
         }
         if (mainCategory.CurrentOption == 3)
         {
             _container.Append(_timePowersStrip);
             MenuTree<TimeSubcategory> timeCategory = _timeCategory;
             if (timeCategory.Sliders.TryGetValue(timeCategory.CurrentOption, out value))
             {
                 _container.Append(value);
             }
         }
         if (mainCategory.CurrentOption == 4)
         {
             _container.Append(_weatherPowersStrip);
             MenuTree<WeatherSubcategory> weatherCategory = _weatherCategory;
             if (weatherCategory.Sliders.TryGetValue(weatherCategory.CurrentOption, out value))
             {
                 _container.Append(value);
             }
         }
         if (mainCategory.CurrentOption == 6)
         {
             _container.Append(_personalPowersStrip);
             MenuTree<PersonalSubcategory> personalCategory = _personalCategory;
             if (personalCategory.Sliders.TryGetValue(personalCategory.CurrentOption, out value))
             {
                 _container.Append(value);
             }
         }
     }
References _container, _infiniteItemsWindow, _mainCategory, _mainPowerStrip, _personalCategory, _personalPowersStrip, _timeCategory, _timePowersStrip, _weatherCategory, _weatherPowersStrip, UIElement.Append(), UICreativePowersMenu.MenuTree< TEnum >.CurrentOption, UIElement.RemoveAllChildren(), UICreativeInfiniteItemsDisplay.SetPageTypeToShow(), and UICreativePowersMenu.MenuTree< TEnum >.Sliders.
Referenced by InitializePage(), MainCategoryButtonClick(), PersonalCategoryButtonClick(), TimeCategoryButtonClick(), and WeatherCategoryButtonClick().