Terraria: System.Data.SqlTypes.SqlBinary.ReadXml
ReadXml()
void IXmlSerializable. System.Data.SqlTypes.SqlBinary.ReadXml (XmlReader reader) inline
Implements System.Xml.Serialization.IXmlSerializable.
Definition at line 337 of file SqlBinary.cs.
    {
        string attribute = reader.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance");
        if (attribute != null && XmlConvert.ToBoolean(attribute))
        {
            reader.ReadElementString();
            _value = null;
            return;
        }
        string text = reader.ReadElementString();
        if (text == null)
        {
            _value = Array.Empty<byte>();
            return;
        }
        text = text.Trim();
        if (text.Length == 0)
        {
            _value = Array.Empty<byte>();
        }
        else
        {
            _value = Convert.FromBase64String(text);
        }
    }
References System.Data.SqlTypes.SqlBinary._value, System.Xml.Dictionary, System.Convert.FromBase64String(), System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.ReadElementString(), System.text, and System.Xml.XmlConvert.ToBoolean().