Terraria: System.Security.Cryptography.X509Certificates.X509Certificate2Collection.ImportFromPem
ImportFromPem()
void System.Security.Cryptography.X509Certificates.X509Certificate2Collection.ImportFromPem (ReadOnlySpan< char > certPem) inline
Definition at line 283 of file X509Certificate2Collection.cs.
    {
        int num = 0;
        try
        {
            PemEnumerator.Enumerator enumerator = new PemEnumerator(certPem).GetEnumerator();
            while (enumerator.MoveNext())
            {
                enumerator.Current.Deconstruct(out var contents, out var pemFields);
                ReadOnlySpan<char> readOnlySpan = contents;
                PemFields pemFields2 = pemFields;
                contents = readOnlySpan;
                ReadOnlySpan<char> span = contents[pemFields2.Label];
                if (span.SequenceEqual("CERTIFICATE"))
                {
                    byte[] array = GC.AllocateUninitializedArray<byte>(pemFields2.DecodedDataLength);
                    contents = readOnlySpan;
                    if (!Convert.TryFromBase64Chars(contents[pemFields2.Base64Data], array, out var bytesWritten) || bytesWritten != pemFields2.DecodedDataLength)
                    {
                        throw new CryptographicException(System.SR.Cryptography_X509_NoPemCertificate);
                    }
                    try
                    {
                        CertificateAsn.Decode(array, AsnEncodingRules.DER);
                    }
                    catch (CryptographicException)
                    {
                        throw new CryptographicException(System.SR.Cryptography_X509_NoPemCertificate);
                    }
                    Import(array);
                    num++;
                }
            }
        }
        catch
        {
            for (int i = 0; i < num; i++)
            {
                RemoveAt(base.Count - 1);
            }
            throw;
        }
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.Cryptography_X509_NoPemCertificate, System.Security.Cryptography.X509Certificates.Asn1.CertificateAsn.Decode(), Internal.Cryptography.PemEnumerator.GetEnumerator(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(), System.Collections.CollectionBase.RemoveAt(), and System.Convert.TryFromBase64Chars().
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate2Collection.ImportFromPemFile().