Terraria: System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Remove
Remove() [3/3]
void System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Remove (X509Certificate2 certificate) inline
Definition at line 216 of file X509Certificate2Collection.cs.
    {
        if (certificate == null)
        {
            throw new ArgumentNullException("certificate");
        }
        Remove((X509Certificate)certificate);
    }
References System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Remove().
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate2Collection.AddRange(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.AddRange(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Remove(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.RemoveRange(), and System.Security.Cryptography.X509Certificates.X509Certificate2Collection.RemoveRange().