Terraria: MountID.Sets.Cart
Cart
bool [] MountID.Sets.Cart = Factory.CreateBoolSet(6, 11, 13, 15, 16, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 38, 39, 51, 53) static
Referenced by Mount.DoSpawnDust(), ContentSamples.CreativeHelper.GetItemGroup(), Player.GrappleMovement(), Player.JumpMovement(), ItemSlot.PickItemMovementAction(), Player.QuickMount_GetItemToUse(), Player.StickyMovement(), ItemSlot.SwapEquip(), Player.TryInteractingWithMinecartTrackInNearbyArea(), and Mount.UpdateEffects().