Terraria: BestiaryUnlocksTracker.ValidateWorld
ValidateWorld()
void BestiaryUnlocksTracker.ValidateWorld (BinaryReader reader, int gameVersionSaveWasMadeOn) inline
Implements IPersistentPerWorldContent.
     {
         Kills.ValidateWorld(reader, gameVersionSaveWasMadeOn);
         Sights.ValidateWorld(reader, gameVersionSaveWasMadeOn);
         Chats.ValidateWorld(reader, gameVersionSaveWasMadeOn);
     }
References Chats, Kills, Sights, NPCKillsTracker.ValidateWorld(), NPCWasChatWithTracker.ValidateWorld(), and NPCWasNearPlayerTracker.ValidateWorld().
Referenced by WorldFile.ValidateWorld().