Terraria: Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions
UICreativeItemsInfiniteFilteringOptions()
Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions (EntryFilterer< Item, IItemEntryFilter > filterer, string snapPointsName) inline
Definition at line 28 of file UICreativeItemsInfiniteFilteringOptions.cs.
    {
        _filterer = filterer;
        int num = 40;
        int count = _filterer.AvailableFilters.Count;
        int num2 = num * count;
        Height = new StyleDimension(num, 0f);
        Width = new StyleDimension(num2, 0f);
        Top = new StyleDimension(4f, 0f);
        SetPadding(0f);
        Asset<Texture2D> val = Main.Assets.Request<Texture2D>("Images/UI/Creative/Infinite_Tabs_B", (AssetRequestMode)1);
        for (int i = 0; i < _filterer.AvailableFilters.Count; i++)
        {
            IItemEntryFilter itemEntryFilter = _filterer.AvailableFilters[i];
            val.Frame(2, 4).OffsetSize(-2, -2);
            UIImageFramed uIImageFramed = new UIImageFramed(val, val.Frame(2, 4).OffsetSize(-2, -2));
            uIImageFramed.Left.Set(num * i, 0f);
            uIImageFramed.OnLeftClick += singleFilterButtonClick;
            uIImageFramed.OnMouseOver += button_OnMouseOver;
            uIImageFramed.SetPadding(0f);
            uIImageFramed.SetSnapPoint(snapPointsName, i);
            AddOnHover(itemEntryFilter, uIImageFramed, i);
            UIElement image = itemEntryFilter.GetImage();
            image.IgnoresMouseInteraction = true;
            image.Left = new StyleDimension(6f, 0f);
            image.HAlign = 0f;
            uIImageFramed.Append(image);
            _filtersByButtons[uIImageFramed] = itemEntryFilter;
            _iconsByButtons[uIImageFramed] = image;
            Append(uIImageFramed);
            UpdateVisuals(uIImageFramed, i);
        }
    }
References Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions._filterer, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions._filtersByButtons, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions._iconsByButtons, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.AddOnHover(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.button_OnMouseOver(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.singleFilterButtonClick(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UpdateVisuals(), and Terraria.UI.UIElement.Width.