Terraria: System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes
ImportKnownTypeAttributes() [2/2]
static void System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes (Type type, Dictionary< Type, Type > typesChecked, ref Dictionary< XmlQualifiedName, DataContract > knownDataContracts) inline static private inherited
Definition at line 2278 of file DataContract.cs.
    {
        while (type != null && IsTypeSerializable(type) && !typesChecked.ContainsKey(type))
        {
            typesChecked.Add(type, type);
            object[] array = type.GetCustomAttributes(Globals.TypeOfKnownTypeAttribute, inherit: false).ToArray();
            if (array != null)
            {
                bool flag = false;
                bool flag2 = false;
                for (int i = 0; i < array.Length; i++)
                {
                    KnownTypeAttribute knownTypeAttribute = (KnownTypeAttribute)array[i];
                    if (knownTypeAttribute.Type != null)
                    {
                        if (flag)
{
                            ThrowInvalidDataContractException(System.SR.Format(System.SR.KnownTypeAttributeOneScheme, GetClrTypeFullName(type)), type);
                        }
                        CheckAndAdd(knownTypeAttribute.Type, typesChecked, ref knownDataContracts);
                        flag2 = true;
                        continue;
                    }
                    if (flag || flag2)
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.KnownTypeAttributeOneScheme, GetClrTypeFullName(type)), type);
                    }
                    string methodName = knownTypeAttribute.MethodName;
                    if (methodName == null)
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.KnownTypeAttributeNoData, GetClrTypeFullName(type)), type);
                    }
                    if (methodName.Length == 0)
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.KnownTypeAttributeEmptyString, GetClrTypeFullName(type)), type);
                    }
                    MethodInfo method = type.GetMethod(methodName, BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    if (method == null)
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.KnownTypeAttributeUnknownMethod, methodName, GetClrTypeFullName(type)), type);
                    }
                    if (!Globals.TypeOfTypeEnumerable.IsAssignableFrom(method.ReturnType))
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.KnownTypeAttributeReturnType, GetClrTypeFullName(type), methodName), type);
                    }
                    object obj = method.Invoke(null, Array.Empty<object>());
                    if (obj == null)
                    {
                        ThrowInvalidDataContractException(System.SR.Format(System.SR.KnownTypeAttributeMethodNull, GetClrTypeFullName(type)), type);
                    }
                    foreach (Type item in (IEnumerable<Type>)obj)
                    {
                        if (item == null)
{
                            ThrowInvalidDataContractException(System.SR.Format(System.SR.KnownTypeAttributeValidMethodTypes, GetClrTypeFullName(type)), type);
                        }
                        CheckAndAdd(item, typesChecked, ref knownDataContracts);
                    }
                    flag = true;
                }
            }
            try
            {
                if (GetDataContract(type) is CollectionDataContract { IsDictionary: not false } collectionDataContract && collectionDataContract.ItemType.GetGenericTypeDefinition() == Globals.TypeOfKeyValue)
                {
                    DataContract dataContract = GetDataContract(Globals.TypeOfKeyValuePair.MakeGenericType(collectionDataContract.ItemType.GetGenericArguments()));
                    if (knownDataContracts == null)
                    {
                        knownDataContracts = new Dictionary<XmlQualifiedName, DataContract>();
                    }
                    knownDataContracts.TryAdd(dataContract.StableName, dataContract);
                }
            }
            catch (InvalidDataContractException)
            {
            }
            type = type.BaseType;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Runtime.Serialization.DataContract.CheckAndAdd(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Runtime.Serialization.Dictionary, System.Type.EmptyTypes, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetDataContract(), System.Text.RegularExpressions.i, System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.item, System.SR.KnownTypeAttributeEmptyString, System.SR.KnownTypeAttributeMethodNull, System.SR.KnownTypeAttributeNoData, System.SR.KnownTypeAttributeOneScheme, System.SR.KnownTypeAttributeReturnType, System.SR.KnownTypeAttributeUnknownMethod, System.SR.KnownTypeAttributeValidMethodTypes, System.obj, System.Runtime.Serialization.DataContract.ThrowInvalidDataContractException(), System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd(), System.type, System.Runtime.Serialization.Globals.TypeOfKeyValue, System.Runtime.Serialization.Globals.TypeOfKeyValuePair, System.Runtime.Serialization.Globals.TypeOfKnownTypeAttribute, and System.Runtime.Serialization.Globals.TypeOfTypeEnumerable.