Terraria: System.Runtime.Serialization.DataContract.CheckAndAdd
CheckAndAdd()
static void System.Runtime.Serialization.DataContract.CheckAndAdd (Type type, Dictionary< Type, Type > typesChecked, [NotNullIfNotNull("nameToDataContractTable")] ref Dictionary< XmlQualifiedName, DataContract > nameToDataContractTable) inline static package inherited
Definition at line 2359 of file DataContract.cs.
    {
        type = UnwrapNullableType(type);
        DataContract dataContract = GetDataContract(type);
        DataContract value;
        if (nameToDataContractTable == null)
        {
            nameToDataContractTable = new Dictionary<XmlQualifiedName, DataContract>();
        }
        else if (nameToDataContractTable.TryGetValue(dataContract.StableName, out value))
        {
            if (DataContractCriticalHelper.GetDataContractAdapterType(value.UnderlyingType) != DataContractCriticalHelper.GetDataContractAdapterType(type) && (!(value is ClassDataContract) || !((ClassDataContract)value).IsKeyValuePairAdapter))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.Format(System.SR.DupContractInKnownTypes, type, value.UnderlyingType, dataContract.StableName.Namespace, dataContract.StableName.Name)));
            }
            return;
        }
        nameToDataContractTable.Add(dataContract.StableName, dataContract);
        ImportKnownTypeAttributes(type, typesChecked, ref nameToDataContractTable);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, System.SR.DupContractInKnownTypes, System.SR.Format(), System.Runtime.Serialization.DataContract.GetDataContract(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractAdapterType(), System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, System.Runtime.Serialization.DataContract.UnwrapNullableType(), and System.value.
Referenced by System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContractsForKnownTypes(), and System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes().