Terraria: System.Runtime.Serialization.DataContract.ReadXmlElement
ReadXmlElement()
virtual object System.Runtime.Serialization.DataContract.ReadXmlElement (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context) inline virtual inherited
Definition at line 1399 of file DataContract.cs.
    {
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.UnexpectedContractType, GetClrTypeFullName(GetType()), GetClrTypeFullName(UnderlyingType))));
    }
References System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.DataContract.UnderlyingType, and System.SR.UnexpectedContractType.