Terraria: System.Runtime.Serialization.DataContract.ExpandGenericParameters
ExpandGenericParameters() [1/2]
static string System.Runtime.Serialization.DataContract.ExpandGenericParameters (string format, IGenericNameProvider genericNameProvider) inline static package inherited
Definition at line 2202 of file DataContract.cs.
    {
        string text = null;
        StringBuilder stringBuilder = new StringBuilder();
        IList<int> nestedParameterCounts = genericNameProvider.GetNestedParameterCounts();
        for (int i = 0; i < format.Length; i++)
        {
            char c = format[i];
            if (c == '{')
            {
                i++;
                int num = i;
                for (; i < format.Length && format[i] != '}'; i++)
                {
                }
                if (i == format.Length)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.GenericNameBraceMismatch, format, genericNameProvider.GetGenericTypeName())));
                }
                if (format[num] == '#' && i == num + 1)
                {
                    if (nestedParameterCounts.Count <= 1 && genericNameProvider.ParametersFromBuiltInNamespaces)
                    {
                        continue;
                    }
                    if (text == null)
                    {
                        StringBuilder stringBuilder2 = new StringBuilder(genericNameProvider.GetNamespaces());
                        foreach (int item in nestedParameterCounts)
{
                            stringBuilder2.Insert(0, item.ToString(CultureInfo.InvariantCulture)).Insert(0, " ");
                        }
                        text = GetNamespacesDigest(stringBuilder2.ToString());
                    }
                    stringBuilder.Append(text);
                }
                else
                {
                    if (!int.TryParse(format.AsSpan(num, i - num), out var result) || result < 0 || result >= genericNameProvider.GetParameterCount())
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.GenericParameterNotValid, format.Substring(num, i - num), genericNameProvider.GetGenericTypeName(), genericNameProvider.GetParameterCount() - 1)));
                    }
                    stringBuilder.Append(genericNameProvider.GetParameterName(result));
                }
            }
            else
            {
                stringBuilder.Append(c);
            }
        }
        return stringBuilder.ToString();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.format, System.SR.GenericNameBraceMismatch, System.SR.GenericParameterNotValid, System.Runtime.Serialization.DataContract.GetNamespacesDigest(), System.Text.RegularExpressions.i, System.Globalization.CultureInfo.InvariantCulture, System.item, System.text, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().