Terraria: System.Runtime.Serialization.DataContract.GetGlobalDataContractNamespace
GetGlobalDataContractNamespace()
static string System.Runtime.Serialization.DataContract.GetGlobalDataContractNamespace (string clrNs, object[] nsAttributes) inline static private inherited
Definition at line 2037 of file DataContract.cs.
    {
        string text = null;
        for (int i = 0; i < nsAttributes.Length; i++)
        {
            ContractNamespaceAttribute contractNamespaceAttribute = (ContractNamespaceAttribute)nsAttributes[i];
            string text2 = contractNamespaceAttribute.ClrNamespace;
            if (text2 == null)
            {
                text2 = string.Empty;
            }
            if (text2 == clrNs)
            {
                if (contractNamespaceAttribute.ContractNamespace == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidGlobalDataContractNamespace, clrNs)));
                }
                if (text != null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.DataContractNamespaceAlreadySet, text, contractNamespaceAttribute.ContractNamespace, clrNs)));
                }
                text = contractNamespaceAttribute.ContractNamespace;
            }
        }
        return text;
    }
References System.SR.DataContractNamespaceAlreadySet, System.SR.Format(), System.Text.RegularExpressions.i, System.SR.InvalidGlobalDataContractNamespace, System.text, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.DataContract.GetDefaultDataContractNamespace().