Terraria: System.Runtime.Serialization.DataContract.GetDefaultStableName
GetDefaultStableName() [1/3]
static void System.Runtime.Serialization.DataContract.GetDefaultStableName (CodeTypeReference typeReference, out string localName, out string ns) inline static private inherited
Definition at line 1934 of file DataContract.cs.
    {
        string baseType = typeReference.BaseType;
        DataContract builtInDataContract = GetBuiltInDataContract(baseType);
        if (builtInDataContract != null)
        {
            localName = builtInDataContract.StableName.Name;
            ns = builtInDataContract.StableName.Namespace;
            return;
        }
        GetClrNameAndNamespace(baseType, out localName, out ns);
        if (typeReference.TypeArguments.Count > 0)
        {
            StringBuilder stringBuilder = new StringBuilder();
            StringBuilder stringBuilder2 = new StringBuilder();
            bool flag = true;
            List<int> dataContractNameForGenericName = GetDataContractNameForGenericName(localName, stringBuilder);
            foreach (CodeTypeReference typeArgument in typeReference.TypeArguments)
            {
                GetDefaultStableName(typeArgument, out var localName2, out var ns2);
                stringBuilder.Append(localName2);
                stringBuilder2.Append(' ').Append(ns2);
                if (flag)
                {
                    flag = IsBuiltInNamespace(ns2);
                }
            }
            if (dataContractNameForGenericName.Count > 1 || !flag)
            {
                foreach (int item in dataContractNameForGenericName)
                {
                    stringBuilder2.Insert(0, item).Insert(0, ' ');
                }
                stringBuilder.Append(GetNamespacesDigest(stringBuilder2.ToString()));
            }
            localName = stringBuilder.ToString();
        }
        localName = EncodeLocalName(localName);
        ns = GetDefaultStableNamespace(ns);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.DataContract.EncodeLocalName(), System.Runtime.Serialization.DataContract.GetBuiltInDataContract(), System.Runtime.Serialization.DataContract.GetClrNameAndNamespace(), System.Runtime.Serialization.DataContract.GetDataContractNameForGenericName(), System.Runtime.Serialization.DataContract.GetDefaultStableName(), System.Runtime.Serialization.DataContract.GetDefaultStableNamespace(), System.Runtime.Serialization.DataContract.GetNamespacesDigest(), System.Runtime.Serialization.DataContract.IsBuiltInNamespace(), and System.item.