Terraria: System.Runtime.Serialization.DataContract.IsAsciiLocalName
IsAsciiLocalName()
static bool System.Runtime.Serialization.DataContract.IsAsciiLocalName (string localName) inline static private inherited
Definition at line 1514 of file DataContract.cs.
    {
        if (localName.Length == 0)
        {
            return false;
        }
        if (!IsAlpha(localName[0]))
        {
            return false;
        }
        for (int i = 1; i < localName.Length; i++)
        {
            char ch = localName[i];
            if (!IsAlpha(ch) && !IsDigit(ch))
            {
                return false;
            }
        }
        return true;
    }
References System.ch, System.Text.RegularExpressions.i, System.Runtime.Serialization.DataContract.IsAlpha(), and System.Runtime.Serialization.DataContract.IsDigit().
Referenced by System.Runtime.Serialization.DataContract.EncodeLocalName().