Terraria: System.Runtime.Serialization.DataContract.SanitizeTypeName
SanitizeTypeName()
static string System.Runtime.Serialization.DataContract.SanitizeTypeName (string typeName) inline static package inherited
Definition at line 2484 of file DataContract.cs.
    {
        return typeName.Replace('.', '_');
    }
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateClassWriter(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter().