Terraria: System.Runtime.Serialization.DataContract.GetDataContractNameForGenericName
GetDataContractNameForGenericName()
static List< int > System.Runtime.Serialization.DataContract.GetDataContractNameForGenericName (string typeName, StringBuilder localName) inline static package inherited
Definition at line 1860 of file DataContract.cs.
    {
        List<int> list = new List<int>();
        int num = 0;
        while (true)
        {
            int num2 = typeName.IndexOf('`', num);
            if (num2 < 0)
            {
                localName?.Append(typeName.AsSpan(num));
                list.Add(0);
                break;
            }
            if (localName != null)
            {
                string text = typeName.Substring(num, num2 - num);
                localName.Append(text.Equals("KeyValuePairAdapter") ? "KeyValuePair" : text);
            }
            while ((num = typeName.IndexOf('.', num + 1, num2 - num - 1)) >= 0)
            {
                list.Add(0);
            }
            num = typeName.IndexOf('.', num2);
            if (num < 0)
            {
                list.Add(int.Parse(typeName.AsSpan(num2 + 1), NumberStyles.Integer, CultureInfo.InvariantCulture));
                break;
            }
            list.Add(int.Parse(typeName.AsSpan(num2 + 1, num - num2 - 1), NumberStyles.Integer, CultureInfo.InvariantCulture));
        }
        localName?.Append("Of");
        return list;
    }
References System.Text.StringBuilder.Append(), System.Globalization.CultureInfo.InvariantCulture, System.list, System.Xml.Parse, and System.text.
Referenced by System.Runtime.Serialization.GenericNameProvider.GenericNameProvider(), System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), System.Runtime.Serialization.DataContract.GetDefaultStableLocalName(), and System.Runtime.Serialization.DataContract.GetDefaultStableName().