Terraria: System.Runtime.Serialization.DataContract.GetId
GetId()
static int System.Runtime.Serialization.DataContract.GetId (RuntimeTypeHandle typeHandle) inline static package inherited
Definition at line 1342 of file DataContract.cs.
    {
        return DataContractCriticalHelper.GetId(typeHandle);
    }
References System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetId().
Referenced by System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), System.Runtime.Serialization.DataContract.GetDataContract(), System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetIdForInitialization(), System.Runtime.Serialization.DataContractSet.GetMemberTypeDataContract(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.ReflectionReader.ReflectionInternalDeserialize(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionInternalSerialize(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType().