Terraria: System.Runtime.Serialization.DataContract.IsValidNCName
IsValidNCName()
static bool System.Runtime.Serialization.DataContract.IsValidNCName (string name) inline static package inherited
Definition at line 1548 of file DataContract.cs.
    {
        try
        {
            XmlConvert.VerifyNCName(name);
            return true;
        }
        catch (XmlException)
        {
            return false;
        }
        catch (Exception)
        {
            return false;
        }
    }
References System.Text.RegularExpressions.name, and System.Xml.XmlConvert.VerifyNCName().
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfJsonNameRequiresMapping(), and System.Runtime.Serialization.DataContract.EncodeLocalName().