Terraria: System.Runtime.Serialization.DataContract.GetCollectionStableName
GetCollectionStableName()
static XmlQualifiedName System.Runtime.Serialization.DataContract.GetCollectionStableName (Type type, Type itemType, out CollectionDataContractAttribute collectionContractAttribute) inline static package inherited
Definition at line 1680 of file DataContract.cs.
    {
        object[] array = type.GetCustomAttributes(Globals.TypeOfCollectionDataContractAttribute, inherit: false).ToArray();
        string text;
        string text2;
        if (array != null && array.Length != 0)
        {
            collectionContractAttribute = (CollectionDataContractAttribute)array[0];
            if (collectionContractAttribute.IsNameSetExplicitly)
            {
                text = collectionContractAttribute.Name;
                if (text == null || text.Length == 0)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidCollectionContractName, GetClrTypeFullName(type))));
                }
                if (type.IsGenericType && !type.IsGenericTypeDefinition)
                {
                    text = ExpandGenericParameters(text, type);
                }
                text = EncodeLocalName(text);
            }
            else
            {
                text = GetDefaultStableLocalName(type);
            }
            if (collectionContractAttribute.IsNamespaceSetExplicitly)
            {
                text2 = collectionContractAttribute.Namespace;
                if (text2 == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidCollectionContractNamespace, GetClrTypeFullName(type))));
                }
                CheckExplicitDataContractNamespaceUri(text2, type);
            }
            else
            {
                text2 = GetDefaultDataContractNamespace(type);
            }
        }
        else
        {
            collectionContractAttribute = null;
            string text3 = "ArrayOf" + GetArrayPrefix(ref itemType);
            XmlQualifiedName stableName = GetStableName(itemType);
            text = text3 + stableName.Name;
            text2 = GetCollectionNamespace(stableName.Namespace);
        }
        return CreateQualifiedName(text, text2);
    }
References System.array, System.Runtime.Serialization.DataContract.CheckExplicitDataContractNamespaceUri(), System.Runtime.Serialization.DataContract.CreateQualifiedName(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.EncodeLocalName(), System.Runtime.Serialization.DataContract.ExpandGenericParameters(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetArrayPrefix(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetCollectionNamespace(), System.Runtime.Serialization.DataContract.GetDefaultDataContractNamespace(), System.Runtime.Serialization.DataContract.GetDefaultStableLocalName(), System.Runtime.Serialization.DataContract.GetStableName(), System.SR.InvalidCollectionContractName, System.SR.InvalidCollectionContractNamespace, System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, and System.Runtime.Serialization.Globals.TypeOfCollectionDataContractAttribute.
Referenced by System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.DataContract.GetNonDCTypeStableName(), and System.Runtime.Serialization.DataContract.TryGetBuiltInXmlAndArrayTypeStableName().