Terraria: System.Runtime.Serialization.DataContract.IsTypeSerializable
IsTypeSerializable() [1/2]
static bool System.Runtime.Serialization.DataContract.IsTypeSerializable (Type type) inline static package inherited
Definition at line 1432 of file DataContract.cs.
    {
        return IsTypeSerializable(type, new HashSet<Type>());
    }
References System.Runtime.Serialization.DataContract.IsTypeSerializable(), and System.type.
Referenced by System.Runtime.Serialization.XsdDataContractExporter.CheckAndAddType(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.CheckIfTypeSerializable(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.CheckIfTypeSerializable(), System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(), System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.Runtime.Serialization.ReflectionReader.ReadItemOfPrimitiveType(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().