Terraria: System.Runtime.Serialization.DataContract.IsTypeVisible
IsTypeVisible()
static bool System.Runtime.Serialization.DataContract.IsTypeVisible (Type t) inline static package inherited
Definition at line 2380 of file DataContract.cs.
    {
        if (!t.IsVisible && !IsTypeVisibleInSerializationModule(t))
        {
            return false;
        }
        Type[] genericArguments = t.GetGenericArguments();
        foreach (Type type in genericArguments)
        {
            if (!type.IsGenericParameter && !IsTypeVisible(type))
            {
                return false;
            }
        }
        return true;
    }
References System.Type.GetGenericArguments(), System.Runtime.Serialization.DataContract.IsTypeVisible(), System.Runtime.Serialization.DataContract.IsTypeVisibleInSerializationModule(), System.Type.IsVisible, and System.type.
Referenced by System.Runtime.Serialization.DataContract.IsMemberVisibleInSerializationModule(), System.Runtime.Serialization.DataContract.IsTypeVisible(), System.Runtime.Serialization.XmlDataContract.RequiresMemberAccessForCreate(), System.Runtime.Serialization.DataMember.RequiresMemberAccessForGet(), System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForRead(), System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForRead(), System.Runtime.Serialization.DataMember.RequiresMemberAccessForSet(), System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForWrite(), and System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForWrite().