Terraria: System.Runtime.Serialization.DataContract.GetDefaultDataContractNamespace
GetDefaultDataContractNamespace()
static string System.Runtime.Serialization.DataContract.GetDefaultDataContractNamespace (Type type) inline static private inherited
Definition at line 1833 of file DataContract.cs.
    {
        string text = type.Namespace;
        if (text == null)
        {
            text = string.Empty;
        }
        string clrNs = text;
        object[] nsAttributes = type.Module.GetCustomAttributes(typeof(ContractNamespaceAttribute)).ToArray();
        string text2 = GetGlobalDataContractNamespace(clrNs, nsAttributes);
        if (text2 == null)
        {
            string clrNs2 = text;
            nsAttributes = type.Assembly.GetCustomAttributes(typeof(ContractNamespaceAttribute)).ToArray();
            text2 = GetGlobalDataContractNamespace(clrNs2, nsAttributes);
        }
        if (text2 == null)
        {
            text2 = GetDefaultStableNamespace(type);
        }
        else
        {
            CheckExplicitDataContractNamespaceUri(text2, type);
        }
        return text2;
    }
References System.Runtime.Serialization.DataContract.CheckExplicitDataContractNamespaceUri(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetDefaultStableNamespace(), System.Runtime.Serialization.DataContract.GetGlobalDataContractNamespace(), System.text, and System.type.
Referenced by System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.DataContract.GetDCTypeStableName(), and System.Runtime.Serialization.DataContract.GetNonDCTypeStableName().