Terraria: System.Runtime.Serialization.DataContract.GetDefaultStableLocalName
GetDefaultStableLocalName()
static string System.Runtime.Serialization.DataContract.GetDefaultStableLocalName (Type type) inline static private inherited
Definition at line 1758 of file DataContract.cs.
    {
        if (type.IsGenericParameter)
        {
            return "{" + type.GenericParameterPosition + "}";
        }
        string text = null;
        if (type.IsArray)
        {
            text = GetArrayPrefix(ref type);
        }
        string text2;
        if (type.DeclaringType == null)
        {
            text2 = type.Name;
        }
        else
        {
            int num = ((type.Namespace != null) ? type.Namespace.Length : 0);
            if (num > 0)
            {
                num++;
            }
            text2 = GetClrTypeFullName(type).Substring(num).Replace('+', '.');
        }
        if (text != null)
        {
            text2 = text + text2;
        }
        if (type.IsGenericType)
        {
            StringBuilder stringBuilder = new StringBuilder();
            StringBuilder stringBuilder2 = new StringBuilder();
            bool flag = true;
            int num2 = text2.IndexOf('[');
            if (num2 >= 0)
            {
                text2 = text2.Substring(0, num2);
            }
            IList<int> dataContractNameForGenericName = GetDataContractNameForGenericName(text2, stringBuilder);
            bool isGenericTypeDefinition = type.IsGenericTypeDefinition;
            Type[] genericArguments = type.GetGenericArguments();
            for (int i = 0; i < genericArguments.Length; i++)
            {
                Type type2 = genericArguments[i];
                if (isGenericTypeDefinition)
                {
                    stringBuilder.Append('{').Append(i).Append('}');
                    continue;
                }
                XmlQualifiedName stableName = GetStableName(type2);
                stringBuilder.Append(stableName.Name);
                stringBuilder2.Append(' ').Append(stableName.Namespace);
                if (flag)
                {
                    flag = IsBuiltInNamespace(stableName.Namespace);
                }
            }
            if (isGenericTypeDefinition)
            {
                stringBuilder.Append("{#}");
            }
            else if (dataContractNameForGenericName.Count > 1 || !flag)
            {
                foreach (int item in dataContractNameForGenericName)
                {
                    stringBuilder2.Insert(0, item.ToString(CultureInfo.InvariantCulture)).Insert(0, " ");
                }
                stringBuilder.Append(GetNamespacesDigest(stringBuilder2.ToString()));
            }
            text2 = stringBuilder.ToString();
        }
        return EncodeLocalName(text2);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.EncodeLocalName(), System.Runtime.Serialization.DataContract.GetArrayPrefix(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetDataContractNameForGenericName(), System.Runtime.Serialization.DataContract.GetNamespacesDigest(), System.Runtime.Serialization.DataContract.GetStableName(), System.Text.RegularExpressions.i, System.Globalization.CultureInfo.InvariantCulture, System.Runtime.Serialization.DataContract.IsBuiltInNamespace(), System.item, System.text, and System.type.
Referenced by System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.DataContract.GetDCTypeStableName(), System.Runtime.Serialization.DataContract.GetDefaultStableName(), and System.Runtime.Serialization.DataContract.GetNonDCTypeStableName().