Terraria: System.Runtime.Serialization.DataContract.ValidatePreviousCollectionTypes
ValidatePreviousCollectionTypes()
static void System.Runtime.Serialization.DataContract.ValidatePreviousCollectionTypes (Type collectionType, Type itemType, HashSet< Type > previousCollectionTypes) inline static private inherited
Definition at line 1459 of file DataContract.cs.
    {
        previousCollectionTypes.Add(collectionType);
        while (itemType.IsArray)
        {
            itemType = itemType.GetElementType();
        }
        if (previousCollectionTypes.Contains(itemType))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.RecursiveCollectionType, GetClrTypeFullName(itemType))));
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.RecursiveCollectionType, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.DataContract.IsTypeSerializable().