Terraria: System.Runtime.Serialization.DataContract.IsMemberVisibleInSerializationModule
IsMemberVisibleInSerializationModule()
static bool System.Runtime.Serialization.DataContract.IsMemberVisibleInSerializationModule (MemberInfo member) inline static private inherited
Definition at line 2433 of file DataContract.cs.
    {
        if (!IsTypeVisibleInSerializationModule(member.DeclaringType))
        {
            return false;
        }
        if (member is MethodInfo)
        {
            MethodInfo methodInfo = (MethodInfo)member;
            if (!methodInfo.IsAssembly)
            {
                return methodInfo.IsFamilyOrAssembly;
            }
            return true;
        }
        if (member is FieldInfo)
        {
            FieldInfo fieldInfo = (FieldInfo)member;
            if (fieldInfo.IsAssembly || fieldInfo.IsFamilyOrAssembly)
            {
                return IsTypeVisible(fieldInfo.FieldType);
            }
            return false;
        }
        if (member is ConstructorInfo)
        {
            ConstructorInfo constructorInfo = (ConstructorInfo)member;
            if (!constructorInfo.IsAssembly)
            {
                return constructorInfo.IsFamilyOrAssembly;
            }
            return true;
        }
        return false;
    }
References System.Reflection.MemberInfo.DeclaringType, System.Runtime.Serialization.DataContract.IsTypeVisible(), and System.Runtime.Serialization.DataContract.IsTypeVisibleInSerializationModule().
Referenced by System.Runtime.Serialization.DataContract.ConstructorRequiresMemberAccess(), System.Runtime.Serialization.DataContract.FieldRequiresMemberAccess(), and System.Runtime.Serialization.DataContract.MethodRequiresMemberAccess().