Terraria: System.Runtime.Serialization.DataContract.GetStableName
GetStableName() [1/2]
static XmlQualifiedName System.Runtime.Serialization.DataContract.GetStableName (Type type) inline static package inherited
Definition at line 1566 of file DataContract.cs.
    {
        bool hasDataContract;
        return GetStableName(type, out hasDataContract);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetStableName(), and System.type.
Referenced by System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.EnumDataContractCriticalHelper(), System.Runtime.Serialization.GenericParameterDataContract.GenericParameterDataContractCriticalHelper.GenericParameterDataContractCriticalHelper(), System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.DataContract.GetDefaultStableLocalName(), System.Runtime.Serialization.GenericNameProvider.GetStableName(), System.Runtime.Serialization.DataContract.GetStableName(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetStableNameAndSetHasDataContract(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Init(), and System.Runtime.Serialization.ClassDataContract.UpdateNamespaceAndMembers().