Terraria: System.Runtime.Serialization.DataContract.GetStableName
GetStableName() [2/2]
static XmlQualifiedName System.Runtime.Serialization.DataContract.GetStableName (Type type, out bool hasDataContract) inline static package inherited
Definition at line 1573 of file DataContract.cs.
    {
        type = UnwrapRedundantNullableType(type);
        DataContractAttribute dataContractAttribute;
        if (TryGetBuiltInXmlAndArrayTypeStableName(type, out var stableName))
        {
            hasDataContract = false;
        }
        else if (TryGetDCAttribute(type, out dataContractAttribute))
        {
            stableName = GetDCTypeStableName(type, dataContractAttribute);
            hasDataContract = true;
        }
        else
        {
            stableName = GetNonDCTypeStableName(type);
            hasDataContract = false;
        }
        return stableName;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetDCTypeStableName(), System.Runtime.Serialization.DataContract.GetNonDCTypeStableName(), System.Runtime.Serialization.DataContract.TryGetBuiltInXmlAndArrayTypeStableName(), System.Runtime.Serialization.DataContract.TryGetDCAttribute(), System.type, and System.Runtime.Serialization.DataContract.UnwrapRedundantNullableType().