Terraria: System.Runtime.Serialization.DataContract.EncodeLocalName
EncodeLocalName()
static string System.Runtime.Serialization.DataContract.EncodeLocalName (string localName) inline static package inherited
Definition at line 1535 of file DataContract.cs.
    {
        if (IsAsciiLocalName(localName))
        {
            return localName;
        }
        if (IsValidNCName(localName))
        {
            return localName;
        }
        return XmlConvert.EncodeLocalName(localName);
    }
References System.Xml.XmlConvert.EncodeLocalName(), System.Runtime.Serialization.DataContract.IsAsciiLocalName(), and System.Runtime.Serialization.DataContract.IsValidNCName().
Referenced by System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper.XmlDataContractCriticalHelper(), System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.DataContract.GetDCTypeStableName(), System.Runtime.Serialization.DataContract.GetDefaultStableLocalName(), System.Runtime.Serialization.DataContract.GetDefaultStableName(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Init(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteSerializationInfo().