Terraria: System.Runtime.Serialization.DataContract.GetGetOnlyCollectionDataContract
GetGetOnlyCollectionDataContract()
static DataContract System.Runtime.Serialization.DataContract.GetGetOnlyCollectionDataContract (int id, RuntimeTypeHandle typeHandle, Type type, SerializationMode mode) inline static package inherited
Definition at line 1315 of file DataContract.cs.
    {
        DataContract getOnlyCollectionDataContractSkipValidation = GetGetOnlyCollectionDataContractSkipValidation(id, typeHandle, type);
        getOnlyCollectionDataContractSkipValidation = getOnlyCollectionDataContractSkipValidation.GetValidContract(mode);
        if (getOnlyCollectionDataContractSkipValidation is ClassDataContract)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SerializationException(System.SR.Format(System.SR.ErrorDeserializing, System.SR.Format(System.SR.ErrorTypeInfo, GetClrTypeFullName(getOnlyCollectionDataContractSkipValidation.UnderlyingType)), System.SR.Format(System.SR.NoSetMethodForProperty, string.Empty, string.Empty))));
        }
        return getOnlyCollectionDataContractSkipValidation;
    }
References System.Runtime.Serialization.Dictionary, System.SR.ErrorDeserializing, System.SR.ErrorTypeInfo, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetGetOnlyCollectionDataContractSkipValidation(), System.SR.NoSetMethodForProperty, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.type.
Referenced by System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), and System.Runtime.Serialization.DataContractSet.GetMemberTypeDataContract().