Terraria: System.Runtime.Serialization.DataContract.TryGetBuiltInXmlAndArrayTypeStableName
TryGetBuiltInXmlAndArrayTypeStableName()
static bool System.Runtime.Serialization.DataContract.TryGetBuiltInXmlAndArrayTypeStableName (Type type, [NotNullWhen(true)] out XmlQualifiedName stableName) inline static private inherited
Definition at line 1648 of file DataContract.cs.
    {
        stableName = null;
        DataContract builtInDataContract = GetBuiltInDataContract(type);
        if (builtInDataContract != null)
        {
            stableName = builtInDataContract.StableName;
        }
        else if (Globals.TypeOfIXmlSerializable.IsAssignableFrom(type))
        {
            SchemaExporter.GetXmlTypeInfo(type, out var stableName2, out var _, out var _);
            stableName = stableName2;
        }
        else if (type.IsArray)
        {
            stableName = GetCollectionStableName(type, type.GetElementType(), out var _);
        }
        return stableName != null;
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetBuiltInDataContract(), System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo(), System.type, and System.Runtime.Serialization.Globals.TypeOfIXmlSerializable.
Referenced by System.Runtime.Serialization.DataContract.GetStableName().