Terraria: System.Runtime.Serialization.DataContract.GetDCTypeStableName
GetDCTypeStableName()
static XmlQualifiedName System.Runtime.Serialization.DataContract.GetDCTypeStableName (Type type, DataContractAttribute dataContractAttribute) inline static private inherited
Definition at line 1595 of file DataContract.cs.
    {
        string text = null;
        string text2 = null;
        if (dataContractAttribute.IsNameSetExplicitly)
        {
            text = dataContractAttribute.Name;
            if (text == null || text.Length == 0)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidDataContractName, GetClrTypeFullName(type))));
            }
            if (type.IsGenericType && !type.IsGenericTypeDefinition)
            {
                text = ExpandGenericParameters(text, type);
            }
            text = EncodeLocalName(text);
        }
        else
        {
            text = GetDefaultStableLocalName(type);
        }
        if (dataContractAttribute.IsNamespaceSetExplicitly)
        {
            text2 = dataContractAttribute.Namespace;
            if (text2 == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidDataContractNamespace, GetClrTypeFullName(type))));
            }
            CheckExplicitDataContractNamespaceUri(text2, type);
        }
        else
        {
            text2 = GetDefaultDataContractNamespace(type);
        }
        return CreateQualifiedName(text, text2);
    }
References System.Runtime.Serialization.DataContract.CheckExplicitDataContractNamespaceUri(), System.Runtime.Serialization.DataContract.CreateQualifiedName(), System.Runtime.Serialization.DataContract.EncodeLocalName(), System.Runtime.Serialization.DataContract.ExpandGenericParameters(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetDefaultDataContractNamespace(), System.Runtime.Serialization.DataContract.GetDefaultStableLocalName(), System.SR.InvalidDataContractName, System.SR.InvalidDataContractNamespace, System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.type.
Referenced by System.Runtime.Serialization.DataContract.GetStableName().