Terraria: System.Runtime.Serialization.DataContract.CheckExplicitDataContractNamespaceUri
CheckExplicitDataContractNamespaceUri()
static void System.Runtime.Serialization.DataContract.CheckExplicitDataContractNamespaceUri (string dataContractNs, Type type) inline static private inherited
Definition at line 1975 of file DataContract.cs.
    {
        if (dataContractNs.Length > 0)
        {
            string text = dataContractNs.Trim();
            if (text.Length == 0 || text.IndexOf("##", StringComparison.Ordinal) != -1)
            {
                ThrowInvalidDataContractException(System.SR.Format(System.SR.DataContractNamespaceIsNotValid, dataContractNs), type);
            }
            dataContractNs = text;
        }
        if (Uri.TryCreate(dataContractNs, UriKind.RelativeOrAbsolute, out Uri result))
        {
            if (result.ToString() == "http://schemas.microsoft.com/2003/10/Serialization/")
            {
                ThrowInvalidDataContractException(System.SR.Format(System.SR.DataContractNamespaceReserved, "http://schemas.microsoft.com/2003/10/Serialization/"), type);
            }
        }
        else
        {
            ThrowInvalidDataContractException(System.SR.Format(System.SR.DataContractNamespaceIsNotValid, dataContractNs), type);
        }
    }
References System.SR.DataContractNamespaceIsNotValid, System.SR.DataContractNamespaceReserved, System.SR.Format(), System.text, System.Runtime.Serialization.DataContract.ThrowInvalidDataContractException(), System.Uri.TryCreate(), and System.type.
Referenced by System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.DataContract.GetDCTypeStableName(), and System.Runtime.Serialization.DataContract.GetDefaultDataContractNamespace().