Terraria: System.Runtime.Serialization.DataContract.WriteXmlValue
WriteXmlValue()
virtual void System.Runtime.Serialization.DataContract.WriteXmlValue (XmlWriterDelegator xmlWriter, object obj, XmlObjectSerializerWriteContext context) inline virtual inherited
Reimplemented in System.Runtime.Serialization.BooleanDataContract, System.Runtime.Serialization.ByteArrayDataContract, System.Runtime.Serialization.CharDataContract, System.Runtime.Serialization.DateTimeDataContract, System.Runtime.Serialization.DecimalDataContract, System.Runtime.Serialization.DoubleDataContract, System.Runtime.Serialization.FloatDataContract, System.Runtime.Serialization.GuidDataContract, System.Runtime.Serialization.IntDataContract, System.Runtime.Serialization.LongDataContract, System.Runtime.Serialization.NullPrimitiveDataContract, System.Runtime.Serialization.ObjectDataContract, System.Runtime.Serialization.QNameDataContract, System.Runtime.Serialization.ShortDataContract, System.Runtime.Serialization.SignedByteDataContract, System.Runtime.Serialization.StringDataContract, System.Runtime.Serialization.TimeSpanDataContract, System.Runtime.Serialization.UnsignedByteDataContract, System.Runtime.Serialization.UnsignedIntDataContract, System.Runtime.Serialization.UnsignedLongDataContract, System.Runtime.Serialization.UnsignedShortDataContract, System.Runtime.Serialization.UriDataContract, System.Runtime.Serialization.ClassDataContract, System.Runtime.Serialization.CollectionDataContract, System.Runtime.Serialization.EnumDataContract, System.Runtime.Serialization.PrimitiveDataContract, System.Runtime.Serialization.SurrogateDataContract, and System.Runtime.Serialization.XmlDataContract.
Definition at line 1382 of file DataContract.cs.
    {
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.UnexpectedContractType, GetClrTypeFullName(GetType()), GetClrTypeFullName(UnderlyingType))));
    }
References System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.DataContract.UnderlyingType, and System.SR.UnexpectedContractType.
Referenced by System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValueCore().