Terraria: System.Runtime.Serialization.DataContract.GetClrTypeFullName
GetClrTypeFullName()
static string System.Runtime.Serialization.DataContract.GetClrTypeFullName (Type type) inline static package inherited
Definition at line 1999 of file DataContract.cs.
    {
        if (type.IsGenericTypeDefinition || !type.ContainsGenericParameters)
        {
            return type.FullName;
        }
        return type.Namespace + "." + type.Name;
    }
References System.Runtime.Serialization.Dictionary, and System.type.
Referenced by System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ClassDataContractCriticalHelper(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionDataContractCriticalHelper(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.EnumDataContractCriticalHelper(), System.Runtime.Serialization.SurrogateDataContract.SurrogateDataContractCriticalHelper.SurrogateDataContractCriticalHelper(), System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper.XmlDataContractCriticalHelper(), System.Runtime.Serialization.ClassDataContract.CheckAndAddMember(), System.Runtime.Serialization.CollectionDataContract.CheckConstructor(), System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfTypeIsReference(), System.Runtime.Serialization.Json.JsonClassDataContract.JsonClassDataContractCriticalHelper.CopyMembersAndCheckDuplicateNames(), System.Runtime.Serialization.FastInvokerBuilder.CreateGetter(), System.Runtime.Serialization.XmlReaderDelegator.CreateInvalidPrimitiveTypeException(), System.Runtime.Serialization.XmlWriterDelegator.CreateInvalidPrimitiveTypeException(), System.Runtime.Serialization.FastInvokerBuilder.CreateSetter(), System.Runtime.Serialization.XmlSerializableWriter.EndWrite(), System.Runtime.Serialization.XmlObjectSerializerReadContext.EnsureArraySize< T >(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureIsReferenceImported(), System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract(), System.Runtime.Serialization.XmlDataContract.GenerateCreateXmlSerializableDelegate(), System.Runtime.Serialization.ReflectionReader.GetCollectionSetItemDelegate< T >(), System.Runtime.Serialization.DataContract.GetCollectionStableName(), System.Runtime.Serialization.XmlDataContract.GetConstructor(), System.Runtime.Serialization.DataContract.GetDCTypeStableName(), System.Runtime.Serialization.DataContract.GetDefaultStableLocalName(), System.Runtime.Serialization.DataContract.GetGetOnlyCollectionDataContract(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetISerializableConstructor(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetNonAttributedTypeConstructor(), System.Runtime.Serialization.CollectionDataContract.GetReadOnlyCollectionExceptionMessages(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.GetSurrogatedType(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.GetSurrogatedType(), System.Runtime.Serialization.XmlObjectSerializer.GetTypeInfoError(), System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo(), System.Runtime.Serialization.CollectionDataContract.HandleIfInvalidCollection(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers(), System.Runtime.Serialization.DataContract.ImportKnownTypeAttributes(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Init(), System.Runtime.Serialization.DataContractSet.InternalAdd(), System.Runtime.Serialization.CodeGenerator.InternalConvert(), System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(), System.Runtime.Serialization.SchemaExporter.InvokeGetSchemaMethod(), System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod(), System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidCallback(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.IsValidExtensionDataSetMethod(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldelem(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleReference(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.ReflectionReader.ReadItemOfPrimitiveType(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.Json.ReflectionJsonReader.ReadSimpleDictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.DataContract.ReadXmlElement(), System.Runtime.Serialization.ClassDataContract.ReadXmlValue(), System.Runtime.Serialization.DataContract.ReadXmlValue(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject(), System.Runtime.Serialization.XmlDataContract.RequiresMemberAccessForCreate(), System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForRead(), System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForRead(), System.Runtime.Serialization.ClassDataContract.RequiresMemberAccessForWrite(), System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForWrite(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(), System.Runtime.Serialization.CodeGenerator.Stelem(), System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowArrayExceededSizeException(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowDuplicateMemberException(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowMissingRequiredMembers(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowNullValueReturnedForGetOnlyCollectionException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef(), System.Runtime.Serialization.DataContract.ValidatePreviousCollectionTypes(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyType(), System.Runtime.Serialization.XmlSerializableWriter.WriteEndElement(), System.Runtime.Serialization.EnumDataContract.WriteEnumValue(), System.Runtime.Serialization.XmlSerializableWriter.WriteFullEndElement(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteISerializable(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteIXmlSerializable(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteJsonISerializable(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteSerializationInfo(), System.Runtime.Serialization.DataContract.WriteXmlElement(), System.Runtime.Serialization.ClassDataContract.WriteXmlValue(), and System.Runtime.Serialization.DataContract.WriteXmlValue().