Terraria: System.Runtime.Serialization.DataContract.GetNamespacesDigest
GetNamespacesDigest()
static string System.Runtime.Serialization.DataContract.GetNamespacesDigest (string namespaces) inline static private inherited
Definition at line 2064 of file DataContract.cs.
    {
        byte[] bytes = Encoding.UTF8.GetBytes(namespaces);
        byte[] inArray = ComputeHash(bytes);
        char[] array = new char[24];
        int num = Convert.ToBase64CharArray(inArray, 0, 6, array, 0);
        StringBuilder stringBuilder = new StringBuilder();
        for (int i = 0; i < num; i++)
        {
            char c = array[i];
            switch (c)
            {
            case '/':
                stringBuilder.Append("_S");
                break;
            case '+':
                stringBuilder.Append("_P");
                break;
            default:
                stringBuilder.Append(c);
                break;
            case '=':
                break;
            }
        }
        return stringBuilder.ToString();
    }
References System.array, System.bytes, System.Runtime.Serialization.DataContract.ComputeHash(), System.Text.RegularExpressions.i, System.Convert.ToBase64CharArray(), and System.Text.Encoding.UTF8.
Referenced by System.Runtime.Serialization.DataContract.ExpandGenericParameters(), System.Runtime.Serialization.DataContract.GetDefaultStableLocalName(), and System.Runtime.Serialization.DataContract.GetDefaultStableName().