Terraria: CreativeUI.DrawToggleButton
DrawToggleButton()
void CreativeUI.DrawToggleButton (SpriteBatch spritebatch, Vector2 location) inline private
     {
         Vector2 vector = _buttonTexture.Size();
         Rectangle rectangle = Utils.CenteredRectangle(location + vector / 2f, vector);
         UILinkPointNavigator.SetPosition(311, rectangle.Center.ToVector2());
         spritebatch.Draw(_buttonTexture.Value, location, null, Color.White, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
         Main.LocalPlayer.creativeInterface = false;
         if (rectangle.Contains(Main.MouseScreen.ToPoint()))
         {
             Main.LocalPlayer.creativeInterface = true;
             Main.LocalPlayer.mouseInterface = true;
             if (Enabled)
             {
                 Main.instance.MouseText(Language.GetTextValue("CreativePowers.PowersMenuOpen"), 0, 0);
             }
             else
             {
                 Main.instance.MouseText(Language.GetTextValue("CreativePowers.PowersMenuClosed"), 0, 0);
             }
             spritebatch.Draw(_buttonBorderTexture.Value, location, null, Color.White, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
             if (Main.mouseLeft && Main.mouseLeftRelease)
             {
                 ToggleMenu();
             }
         }
     }
References _buttonBorderTexture, _buttonTexture, Utils.CenteredRectangle(), Color, Player.creativeInterface, Enabled, Language.GetTextValue(), Main.instance, Main.LocalPlayer, Player.mouseInterface, Main.mouseLeft, Main.mouseLeftRelease, Main.MouseScreen, Main.MouseText(), UILinkPointNavigator.SetPosition(), ToggleMenu(), and Asset< T >.Value.
Referenced by Draw().