Terraria: Lighting.AddLight
AddLight() [5/5]
static void Lighting.AddLight (Vector2 position, Vector3 rgb) inline static
Referenced by WaterfallManager.AddLight(), AddLight(), NPC.AI(), Projectile.AI_001(), NPC.AI_001_Slimes(), NPC.AI_002_FloatingEye(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), Projectile.AI_007_GrapplingHooks(), NPC.AI_007_TownEntities(), Projectile.AI_019_Spears(), Projectile.AI_026(), NPC.AI_026_Unicorns(), NPC.AI_037_Destroyer(), Projectile.AI_062(), NPC.AI_065_Butterflies(), Projectile.AI_067_FreakingPirates(), Projectile.AI_075(), Projectile.AI_100_Medusa(), NPC.AI_112_FairyCritter(), NPC.AI_117_BloodNautilus(), NPC.AI_120_HallowBoss(), Projectile.AI_120_StardustGuardian(), NPC.AI_121_QueenSlime(), Projectile.AI_130_FlameBurstTower(), Projectile.AI_138_ExplosiveTrap(), Projectile.AI_140_MonkStaffT1(), Projectile.AI_142_MonkStaffT2And3(), Projectile.AI_147_Celeb2Rocket(), Projectile.AI_157_SharpTears(), Projectile.AI_165_Whip(), Projectile.AI_166_Dove(), Projectile.AI_167_SparkleGuitar(), Projectile.AI_182_FinalFractal(), Projectile.AI_190_NightsEdge(), Projectile.AI_191_TrueNightsEdge(), Projectile.AI_195_JimsDrone(), Mount.AimAbility(), Player.ApplyEquipFunctional(), DelegateMethods.CastLight(), DelegateMethods.CastLightOpen(), DelegateMethods.CastLightOpen_StopForSolids(), DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Main.DrawProjDirect(), TileDrawing.DrawTrees(), Mount.Hover(), Player.ItemCheck_EmitHeldItemLight(), Player.ItemCheck_EmitUseVisuals(), Player.PlayerFrame(), Projectile.ProjLight(), DelegateMethods.SpreadLightOpen_StopForSolids(), PotionOfReturnGateHelper.Update(), VoidLensHelper.Update(), Gore.Update(), Player.Update(), GasParticle.Update(), Player.UpdateArmorLights(), Player.UpdateArmorSets(), Player.UpdateBuffs(), Dust.UpdateDust(), Mount.UpdateEffects(), Mount.UpdateFrame(), Item.UpdateItem(), Item.UpdateItem_VisualEffects(), Gore.UpdateLightningBunnySparks(), NPC.UpdateNPC_BuffApplyVFX(), NPC.UpdateNPC_CastLights(), NPC.UpdateNPC_UpdateTrails(), and Player.WingFrame().