Terraria: Lighting.GetCornerColors
GetCornerColors()
static void Lighting.GetCornerColors (int centerX, int centerY, out VertexColors vertices, float scale = 1f) inline static
     {
         vertices = default(VertexColors);
         Vector3 color = _activeEngine.GetColor(centerX, centerY);
         Vector3 color2 = _activeEngine.GetColor(centerX, centerY - 1);
         Vector3 color3 = _activeEngine.GetColor(centerX, centerY + 1);
         Vector3 color4 = _activeEngine.GetColor(centerX - 1, centerY);
         Vector3 color5 = _activeEngine.GetColor(centerX + 1, centerY);
         Vector3 color6 = _activeEngine.GetColor(centerX - 1, centerY - 1);
         Vector3 color7 = _activeEngine.GetColor(centerX + 1, centerY - 1);
         Vector3 color8 = _activeEngine.GetColor(centerX - 1, centerY + 1);
         Vector3 color9 = _activeEngine.GetColor(centerX + 1, centerY + 1);
         float num = GlobalBrightness * scale * 63.75f;
         int num2 = (int)((color2.X + color6.X + color4.X + color.X) * num);
         int num3 = (int)((color2.Y + color6.Y + color4.Y + color.Y) * num);
         int num4 = (int)((color2.Z + color6.Z + color4.Z + color.Z) * num);
         if (num2 > 255)
         {
             num2 = 255;
         }
         if (num3 > 255)
         {
             num3 = 255;
         }
         if (num4 > 255)
         {
             num4 = 255;
         }
         num3 <<= 8;
         num4 <<= 16;
         vertices.TopLeftColor.PackedValue = (uint)(num2 | num3 | num4) | 0xFF000000u;
         num2 = (int)((color2.X + color7.X + color5.X + color.X) * num);
         num3 = (int)((color2.Y + color7.Y + color5.Y + color.Y) * num);
         num4 = (int)((color2.Z + color7.Z + color5.Z + color.Z) * num);
         if (num2 > 255)
         {
             num2 = 255;
         }
         if (num3 > 255)
         {
             num3 = 255;
         }
         if (num4 > 255)
         {
             num4 = 255;
         }
         num3 <<= 8;
         num4 <<= 16;
         vertices.TopRightColor.PackedValue = (uint)(num2 | num3 | num4) | 0xFF000000u;
         num2 = (int)((color3.X + color8.X + color4.X + color.X) * num);
         num3 = (int)((color3.Y + color8.Y + color4.Y + color.Y) * num);
         num4 = (int)((color3.Z + color8.Z + color4.Z + color.Z) * num);
         if (num2 > 255)
         {
             num2 = 255;
         }
         if (num3 > 255)
         {
             num3 = 255;
         }
         if (num4 > 255)
         {
             num4 = 255;
         }
         num3 <<= 8;
         num4 <<= 16;
         vertices.BottomLeftColor.PackedValue = (uint)(num2 | num3 | num4) | 0xFF000000u;
         num2 = (int)((color3.X + color9.X + color5.X + color.X) * num);
         num3 = (int)((color3.Y + color9.Y + color5.Y + color.Y) * num);
         num4 = (int)((color3.Z + color9.Z + color5.Z + color.Z) * num);
         if (num2 > 255)
         {
             num2 = 255;
         }
         if (num3 > 255)
         {
             num3 = 255;
         }
         if (num4 > 255)
         {
             num4 = 255;
         }
         num3 <<= 8;
         num4 <<= 16;
         vertices.BottomRightColor.PackedValue = (uint)(num2 | num3 | num4) | 0xFF000000u;
     }
References _activeEngine, ILightingEngine.GetColor(), and GlobalBrightness.
Referenced by Main.DrawBackground(), LiquidRenderer.DrawNormalLiquids(), LiquidRenderer.DrawShimmer(), TileDrawing.DrawTile_LiquidBehindTile(), WallDrawing.DrawWalls(), WaterfallManager.DrawWaterfall(), and Main.OldDrawBackground().