Terraria: Lighting.GetColor
GetColor() [3/4]
static Color Lighting.GetColor (Point tileCoords) inline static
References _activeEngine, Color, Main.gameMenu, ILightingEngine.GetColor(), and GlobalBrightness.
Referenced by Projectile.AI_067_FreakingPirates(), PlayerDrawSet.BoringSetup(), GasParticle.Draw(), LittleFlyingCritterParticle.Draw(), TileDrawing.DrawAnyDirectionalGrass(), Main.DrawBackground(), Main.DrawDust(), HitTile.DrawFreshAnimations(), LegacyPlayerRenderer.DrawGhost(), Main.DrawGore(), Main.DrawGoreBehind(), TileDrawing.DrawGrass(), Main.DrawItem(), Main.DrawKite(), TileDrawing.DrawMasterTrophies(), Main.DrawMultisegmentPet(), TileDrawing.DrawMultiTileGrassInWind(), TileDrawing.DrawMultiTileVinesInWind(), Main.DrawNPCDirect(), Main.DrawNPCHousesInWorld(), Main.DrawNPCs(), PlayerDrawLayers.DrawPlayer_27_HeldItem(), PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud(), LegacyPlayerRenderer.DrawPlayerStoned(), Main.DrawProj_Excalibur(), Main.DrawProj_FishingLine(), Main.DrawProj_FlailChains(), Main.DrawProj_FlailChains_Old(), Main.DrawProj_NightsEdge(), Main.DrawProj_PiercingStarlight(), Main.DrawProj_TerraBlade2(), Main.DrawProj_TerraBlade2Shot(), Main.DrawProj_TheHorsemansBlade(), Main.DrawProj_TrueExcalibur(), Main.DrawProj_TrueNightsEdge(), Main.DrawProjDirect(), Main.DrawRain(), TileDrawing.DrawRisingVineStrip(), TileDrawing.DrawSingleTile(), Main.DrawSmartCursor(), Main.DrawSmartInteract(), TileDrawing.DrawSpecialTilesLegacy(), Main.DrawStar(), TileDrawing.DrawTeleportationPylons(), Main.DrawTileCracks(), Main.DrawTileInWater(), PotionOfReturnGateHelper.DrawToDrawData(), VoidLensHelper.DrawToDrawData(), TileDrawing.DrawTrees(), Main.DrawTwinsPet(), TileDrawing.DrawVineStrip(), Main.DrawWallOfFish(), WallDrawing.DrawWalls(), WaterfallManager.DrawWaterfall(), Main.DrawWhip(), Main.DrawWhip_BoneWhip(), Main.DrawWhip_CoolWhip(), Main.DrawWhip_FireWhip(), Main.DrawWhip_RainbowWhip(), Main.DrawWhip_ThornWhip(), Main.DrawWhip_WhipBland(), Main.DrawWhip_WhipMace(), Main.DrawWhip_WhipScythe(), Main.DrawWhip_WhipSword(), Main.DrawWires(), Main.DrawWOFBody(), Main.DrawWOFRopeToTheHungry(), Main.DrawWOFTongueToPlayer(), TileDrawing.DrawXmasTree(), Player.GetHairColor(), MoonlordDeathDrama.MoonlordPiece.GetLight(), TileDrawing.GetTileDrawData(), DontStarveDarknessDamageDealer.IsPlayerSafe(), DyeInitializer.LoadLegacyHairdyes(), Main.OldDrawBackground(), Main.oldDrawWater(), Dust.UpdateDust(), and NPC.UpdateNPC_CastLights().