Terraria: Lighting.GetColor4Slice
GetColor4Slice() [1/2]
static void Lighting.GetColor4Slice (int centerX, int centerY, ref Color[] slices) inline static
     {
         Vector3 color = _activeEngine.GetColor(centerX, centerY - 1);
         Vector3 color2 = _activeEngine.GetColor(centerX, centerY + 1);
         Vector3 color3 = _activeEngine.GetColor(centerX - 1, centerY);
         Vector3 color4 = _activeEngine.GetColor(centerX + 1, centerY);
         float num = color.X + color.Y + color.Z;
         float num2 = color2.X + color2.Y + color2.Z;
         float num3 = color4.X + color4.Y + color4.Z;
         float num4 = color3.X + color3.Y + color3.Z;
         if (num >= num4)
         {
             int num5 = (int)(255f * color3.X * GlobalBrightness);
             int num6 = (int)(255f * color3.Y * GlobalBrightness);
             int num7 = (int)(255f * color3.Z * GlobalBrightness);
             if (num5 > 255)
             {
                 num5 = 255;
             }
             if (num6 > 255)
             {
                 num6 = 255;
             }
             if (num7 > 255)
             {
                 num7 = 255;
             }
             slices[0] = new Color((byte)num5, (byte)num6, (byte)num7, 255);
         }
         else
         {
             int num8 = (int)(255f * color.X * GlobalBrightness);
             int num9 = (int)(255f * color.Y * GlobalBrightness);
             int num10 = (int)(255f * color.Z * GlobalBrightness);
             if (num8 > 255)
             {
                 num8 = 255;
             }
             if (num9 > 255)
             {
                 num9 = 255;
             }
             if (num10 > 255)
             {
                 num10 = 255;
             }
             slices[0] = new Color((byte)num8, (byte)num9, (byte)num10, 255);
         }
         if (num >= num3)
         {
             int num11 = (int)(255f * color4.X * GlobalBrightness);
             int num12 = (int)(255f * color4.Y * GlobalBrightness);
             int num13 = (int)(255f * color4.Z * GlobalBrightness);
             if (num11 > 255)
             {
                 num11 = 255;
             }
             if (num12 > 255)
             {
                 num12 = 255;
             }
             if (num13 > 255)
             {
                 num13 = 255;
             }
             slices[1] = new Color((byte)num11, (byte)num12, (byte)num13, 255);
         }
         else
         {
             int num14 = (int)(255f * color.X * GlobalBrightness);
             int num15 = (int)(255f * color.Y * GlobalBrightness);
             int num16 = (int)(255f * color.Z * GlobalBrightness);
             if (num14 > 255)
             {
                 num14 = 255;
             }
             if (num15 > 255)
             {
                 num15 = 255;
             }
             if (num16 > 255)
             {
                 num16 = 255;
             }
             slices[1] = new Color((byte)num14, (byte)num15, (byte)num16, 255);
         }
         if (num2 >= num4)
         {
             int num17 = (int)(255f * color3.X * GlobalBrightness);
             int num18 = (int)(255f * color3.Y * GlobalBrightness);
             int num19 = (int)(255f * color3.Z * GlobalBrightness);
             if (num17 > 255)
             {
                 num17 = 255;
             }
             if (num18 > 255)
             {
                 num18 = 255;
             }
             if (num19 > 255)
             {
                 num19 = 255;
             }
             slices[2] = new Color((byte)num17, (byte)num18, (byte)num19, 255);
         }
         else
         {
             int num20 = (int)(255f * color2.X * GlobalBrightness);
             int num21 = (int)(255f * color2.Y * GlobalBrightness);
             int num22 = (int)(255f * color2.Z * GlobalBrightness);
             if (num20 > 255)
             {
                 num20 = 255;
             }
             if (num21 > 255)
             {
                 num21 = 255;
             }
             if (num22 > 255)
             {
                 num22 = 255;
             }
             slices[2] = new Color((byte)num20, (byte)num21, (byte)num22, 255);
         }
         if (num2 >= num3)
         {
             int num23 = (int)(255f * color4.X * GlobalBrightness);
             int num24 = (int)(255f * color4.Y * GlobalBrightness);
             int num25 = (int)(255f * color4.Z * GlobalBrightness);
             if (num23 > 255)
             {
                 num23 = 255;
             }
             if (num24 > 255)
             {
                 num24 = 255;
             }
             if (num25 > 255)
             {
                 num25 = 255;
             }
             slices[3] = new Color((byte)num23, (byte)num24, (byte)num25, 255);
         }
         else
         {
             int num26 = (int)(255f * color2.X * GlobalBrightness);
             int num27 = (int)(255f * color2.Y * GlobalBrightness);
             int num28 = (int)(255f * color2.Z * GlobalBrightness);
             if (num26 > 255)
             {
                 num26 = 255;
             }
             if (num27 > 255)
             {
                 num27 = 255;
             }
             if (num28 > 255)
             {
                 num28 = 255;
             }
             slices[3] = new Color((byte)num26, (byte)num27, (byte)num28, 255);
         }
     }
References _activeEngine, Color, ILightingEngine.GetColor(), and GlobalBrightness.
Referenced by Main.DrawBackground(), TileDrawing.DrawSingleTile_SlicedBlock(), and Main.OldDrawBackground().