Terraria: NetClientSocialModule.LazyCreateWeGameMsgServer
LazyCreateWeGameMsgServer()
void NetClientSocialModule.LazyCreateWeGameMsgServer () inline private
     {
         if (_msgServer == null)
         {
             _msgServer = new MessageDispatcherServer();
             _msgServer.Init("WeGame.Terraria.Message.Server");
             _msgServer.OnMessage += OnWegameMessage;
             _msgServer.OnIPCClientAccess += OnIPCClientAccess;
             CoreSocialModule.OnTick += _msgServer.Tick;
             _msgServer.Start();
         }
     }
References _msgServer, MessageDispatcherServer.Init(), MessageDispatcherServer.OnIPCClientAccess, OnIPCClientAccess(), MessageDispatcherServer.OnMessage, CoreSocialModule.OnTick, OnWegameMessage(), MessageDispatcherServer.Start(), and MessageDispatcherServer.Tick().
Referenced by LaunchLocalServer().