Terraria: NetClientSocialModule.Initialize
Initialize() [2/2]
override void NetClientSocialModule.Initialize () inline virtual
Implements NetSocialModule.
     {
         base.Initialize();
         RegisterRailEvent();
         AsyncGetFriendsInfo();
         _reader.SetReadEvent(OnPacketRead);
         _reader.SetLocalPeer(GetLocalPeer());
         _writer.SetLocalPeer(GetLocalPeer());
         Main.OnEngineLoad += CheckParameters;
     }
References NetSocialModule._reader, NetSocialModule._writer, AsyncGetFriendsInfo(), CheckParameters(), NetSocialModule.GetLocalPeer(), Main.OnEngineLoad, OnPacketRead(), RegisterRailEvent(), and SteamP2PReader.SetReadEvent().