Terraria: NetClientSocialModule.AsyncSetMyMetaData
AsyncSetMyMetaData()
void NetClientSocialModule.AsyncSetMyMetaData (string key, string value) inline private
     {
         //IL_0006: Unknown result type (might be due to invalid IL or missing references)
         //IL_000c: Expected O, but got Unknown
         //IL_0031: Unknown result type (might be due to invalid IL or missing references)
         List<RailKeyValue> list = new List<RailKeyValue>();
         RailKeyValue val = new RailKeyValue();
         val.key = key;
         val.value = value;
         list.Add(val);
         rail_api.RailFactory().RailFriends().AsyncSetMyMetadata(list, "");
     }
Referenced by LaunchLocalServer(), OnAuthSuccess(), and OnReportServerID().