Terraria: System.Net.Mail.QuotedStringFormatReader.TryReadReverseUnQuoted
TryReadReverseUnQuoted()
static bool System.Net.Mail.QuotedStringFormatReader.TryReadReverseUnQuoted (string data, int index, bool permitUnicode, bool expectCommaDelimiter, out int outIndex, bool throwExceptionIfFail) inline static package
Definition at line 56 of file QuotedStringFormatReader.cs.
    {
        do
        {
            if (!WhitespaceReader.TryReadFwsReverse(data, index, out index, throwExceptionIfFail))
            {
                outIndex = 0;
                return false;
            }
            if (index < 0)
            {
                break;
            }
            if (!QuotedPairReader.TryCountQuotedChars(data, index, permitUnicode, out var outIndex2, throwExceptionIfFail))
            {
                outIndex = 0;
                return false;
            }
            if (outIndex2 > 0)
            {
                index -= outIndex2;
                continue;
            }
            if (expectCommaDelimiter && data[index] == ',')
            {
                break;
            }
            if (!IsValidQtext(permitUnicode, data[index]))
            {
                if (throwExceptionIfFail)
                {
                    throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, data[index]));
                }
                outIndex = 0;
                return false;
            }
            index--;
        }
        while (index >= 0);
        outIndex = index;
        return true;
    }
References System.SR.Format(), System.index, System.Net.Mail.QuotedStringFormatReader.IsValidQtext(), System.SR.MailHeaderFieldInvalidCharacter, System.Net.Mail.QuotedPairReader.TryCountQuotedChars(), and System.Net.Mail.WhitespaceReader.TryReadFwsReverse().
Referenced by System.Net.Mail.MailAddressParser.TryParseDisplayName().