Terraria: NetClientSocialModule.OnAuthSuccess
OnAuthSuccess()
void NetClientSocialModule.OnAuthSuccess (RailID remote_peer) inline private
     {
         if (_connectionStateMap.ContainsKey(remote_peer))
         {
             _connectionStateMap[remote_peer] = ConnectionState.Connected;
             AsyncSetPlayWith(_inviter_id);
             AsyncSetMyMetaData("status", Language.GetTextValue("Social.StatusInGame"));
             AsyncSetMyMetaData(_serverIDMedataKey, ((RailComparableID)remote_peer).id_.ToString());
             Main.clrInput();
             Netplay.ServerPassword = "";
             Main.GetInputText("");
             Main.autoPass = false;
             Main.netMode = 1;
             Netplay.OnConnectedToSocialServer(new SocialSocket(new WeGameAddress(remote_peer, GetFriendNickname(_inviter_id))));
             WeGameHelper.WriteDebugString("OnConnectToSocialServer server:" + ((RailComparableID)remote_peer).id_);
         }
     }
References NetSocialModule._connectionStateMap, _inviter_id, _serverIDMedataKey, AsyncSetMyMetaData(), AsyncSetPlayWith(), Main.autoPass, Main.clrInput(), GetFriendNickname(), Main.GetInputText(), Language.GetTextValue(), Main.netMode, Netplay.OnConnectedToSocialServer(), Netplay.ServerPassword, and WeGameHelper.WriteDebugString().
Referenced by OnPacketRead().