Terraria: Netplay.ClientLoopSetup
ClientLoopSetup()
static void Netplay.ClientLoopSetup (RemoteAddress address) inline static private
     {
         Connection.ResetSpecialFlags();
         ResetNetDiag();
         Main.ServerSideCharacter = false;
         if (Main.rand == null)
         {
             Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
         }
         Main.player[Main.myPlayer].hostile = false;
         Main.clientPlayer = Main.player[Main.myPlayer].clientClone();
         for (int i = 0; i < 255; i++)
         {
             if (i != Main.myPlayer)
             {
                 Main.player[i] = new Player();
             }
         }
         Main.netMode = 1;
         Main.menuMode = 14;
         if (!Main.autoPass)
         {
             Main.statusText = Language.GetTextValue("Net.ConnectingTo", address.GetFriendlyName());
         }
         Disconnect = false;
         Connection = new RemoteServer();
         Connection.ReadBuffer = new byte[1024];
     }
References Main.autoPass, Player.clientClone(), Main.clientPlayer, Connection, Disconnect, RemoteAddress.GetFriendlyName(), Language.GetTextValue(), Player.hostile, Main.menuMode, Main.myPlayer, Main.netMode, Player, Main.player, Main.rand, RemoteServer.ReadBuffer, ResetNetDiag(), RemoteServer.ResetSpecialFlags(), Main.ServerSideCharacter, and Main.statusText.
Referenced by SocialClientLoop(), and TcpClientLoop().