Terraria: Netplay.InitializeServer
InitializeServer()
static void Netplay.InitializeServer () inline static private
     {
         Connection.ResetSpecialFlags();
         ResetNetDiag();
         if (Main.rand == null)
         {
             Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
         }
         Main.myPlayer = 255;
         ServerIP = IPAddress.Any;
         Main.menuMode = 14;
         Main.statusText = Lang.menu[8].Value;
         Main.netMode = 2;
         Disconnect = false;
         for (int i = 0; i < 256; i++)
         {
             Clients[i] = new RemoteClient();
             Clients[i].Reset();
             Clients[i].Id = i;
             Clients[i].ReadBuffer = new byte[1024];
         }
         TcpListener = new TcpSocket();
         if (!Disconnect)
         {
             if (!StartListening())
             {
                 Main.statusText = Language.GetTextValue("Error.TriedToRunServerTwice");
                 SaveOnServerExit = false;
                 Disconnect = true;
             }
             Main.statusText = Language.GetTextValue("CLI.ServerStarted");
         }
         if (!UseUPNP)
         {
             return;
         }
         try
         {
             OpenPort(ListenPort);
         }
         catch (Exception)
         {
         }
     }
References Clients, Connection, Disconnect, Language.GetTextValue(), RemoteClient.Id, ListenPort, Lang.menu, Main.menuMode, Main.myPlayer, Main.netMode, OpenPort(), Main.rand, RemoteClient.ReadBuffer, RemoteClient.Reset(), ResetNetDiag(), RemoteServer.ResetSpecialFlags(), SaveOnServerExit, ServerIP, StartListening(), Main.statusText, TcpListener, UseUPNP, and LocalizedText.Value.
Referenced by StartServer().