Terraria: ReLogic.Content.AssetRepository.CreateUntracked< T >
CreateUntracked< T >()
Asset< T > ReLogic.Content.AssetRepository.CreateUntracked< T > (Stream stream, string name, AssetRequestMode mode = AssetRequestMode::ImmediateLoad) inline
Implements ReLogic.Content.IAssetRepository.
Type Constraints
T : class
Definition at line 361 of file AssetRepository.cs.
                                                                                                                                   : class
    {
        string ext = Path.GetExtension(name);
        if (!_readers.TryGetReader(ext, out var reader))
        {
            throw AssetLoadException.FromMissingReader(ext);
        }
        int length = ext.Length;
        Asset<T> asset = new Asset<T>(name.Substring(0, name.Length - length));
        Task loadTask = LoadUntracked(stream, reader, asset, mode);
        asset.Wait = delegate
        {
            SafelyWaitForLoad(asset, loadTask, tracked: false);
        };
        if (mode == AssetRequestMode.ImmediateLoad)
        {
            asset.Wait();
        }
        return asset;
    }
References ReLogic.Content.AssetRepository._readers, ReLogic.Content.AssetLoadException.FromMissingReader(), System.IO.Path.GetExtension(), System.length, System.stream, and ReLogic.Content.AssetReaderCollection.TryGetReader().