Terraria: Netplay.AddCurrentServerToRecentList
AddCurrentServerToRecentList()
static void Netplay.AddCurrentServerToRecentList () inline static
     {
         if (Connection.Socket.GetRemoteAddress().Type != 0)
         {
             return;
         }
         for (int i = 0; i < Main.maxMP; i++)
         {
             if (Main.recentIP[i].ToLower() == ServerIPText.ToLower() && Main.recentPort[i] == ListenPort)
             {
                 for (int j = i; j < Main.maxMP - 1; j++)
                 {
                     Main.recentIP[j] = Main.recentIP[j + 1];
                     Main.recentPort[j] = Main.recentPort[j + 1];
                     Main.recentWorld[j] = Main.recentWorld[j + 1];
                 }
             }
         }
         for (int num = Main.maxMP - 1; num > 0; num--)
         {
             Main.recentIP[num] = Main.recentIP[num - 1];
             Main.recentPort[num] = Main.recentPort[num - 1];
             Main.recentWorld[num] = Main.recentWorld[num - 1];
         }
         Main.recentIP[0] = ServerIPText;
         Main.recentPort[0] = ListenPort;
         Main.recentWorld[0] = Main.worldName;
         Main.SaveRecent();
     }
References Connection, ISocket.GetRemoteAddress(), ListenPort, Main.maxMP, Main.recentIP, Main.recentPort, Main.recentWorld, Main.SaveRecent(), ServerIPText, RemoteServer.Socket, RemoteAddress.Type, and Main.worldName.
Referenced by Player.Spawn().