Terraria: Netplay.TcpClientLoop
TcpClientLoop()
static void Netplay.TcpClientLoop () inline static
     {
         ClientLoopSetup(new TcpAddress(ServerIP, ListenPort));
         Main.menuMode = 14;
         bool flag = true;
         while (flag)
         {
             flag = false;
             try
             {
                 Connection.Socket.Connect(new TcpAddress(ServerIP, ListenPort));
                 flag = false;
             }
             catch
             {
                 if (Platform.IsOSX)
                 {
                     Thread.Sleep(200);
                     Connection.Socket.Close();
                     Connection.Socket = new TcpSocket();
                 }
                 if (!Disconnect && Main.gameMenu)
                 {
                     flag = true;
                 }
             }
         }
         InnerClientLoop();
     }
References ClientLoopSetup(), ISocket.Close(), ISocket.Connect(), Connection, Disconnect, Main.gameMenu, InnerClientLoop(), Platform.IsOSX, ListenPort, Main.menuMode, ServerIP, and RemoteServer.Socket.
Referenced by StartTcpClient().