Terraria: Terraria.IO.PlayerFileData.CreateAndSave
CreateAndSave()
static PlayerFileData Terraria.IO.PlayerFileData.CreateAndSave (Player player) inline static
Definition at line 48 of file PlayerFileData.cs.
    {
        PlayerFileData playerFileData = new PlayerFileData();
        playerFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.Player);
        playerFileData.Player = player;
        playerFileData._isCloudSave = SocialAPI.Cloud != null && SocialAPI.Cloud.EnabledByDefault;
        playerFileData._path = Main.GetPlayerPathFromName(player.name, playerFileData.IsCloudSave);
        (playerFileData.IsCloudSave ? Main.CloudFavoritesData : Main.LocalFavoriteData).ClearEntry(playerFileData);
        Player.SavePlayer(playerFileData, skipMapSave: true);
        return playerFileData;
    }
References Terraria.IO.PlayerFileData.PlayerFileData(), Terraria.Social.SocialAPI.Cloud, Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.Main.GetPlayerPathFromName(), Terraria.IO.FileData.IsCloudSave, Terraria.Main.LocalFavoriteData, Terraria.Player.name, and Terraria.Player.SavePlayer().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.FinishCreatingCharacter(), and Terraria.Main.OnCharacterNamed().