Terraria: Netplay.StartListening
StartListening()
static bool Netplay.StartListening () inline static private
     {
         if (SocialAPI.Network != null)
         {
             SocialAPI.Network.StartListening(OnConnectionAccepted);
         }
         return TcpListener.StartListening(OnConnectionAccepted);
     }
References SocialAPI.Network, OnConnectionAccepted(), ISocket.StartListening(), NetSocialModule.StartListening(), and TcpListener.
Referenced by InitializeServer(), and StartListeningIfNeeded().