Terraria: ReLogic.Content.AssetRepository.SetSources
SetSources()
virtual void ReLogic.Content.AssetRepository.SetSources (IEnumerable< IContentSource > sources, AssetRequestMode mode = AssetRequestMode::ImmediateLoad) inline virtual
Implements ReLogic.Content.IAssetRepository.
Definition at line 133 of file AssetRepository.cs.
    {
        ThrowIfDisposed();
        ThrowIfNotMainThread();
        lock (_requestLock)
        {
            TransferAllAssets();
            _sources = sources.ToArray();
            ReloadAssetsIfSourceChanged(mode);
            if (mode == AssetRequestMode.ImmediateLoad && _Remaining > 0)
            {
                throw new Exception("Some assets loaded asynchronously, despite AssetRequestMode.ImmediateLoad on main thread");
            }
        }
    }
References ReLogic.Content.AssetRepository._Remaining, ReLogic.Content.AssetRepository._requestLock, ReLogic.Content.AssetRepository._sources, ReLogic.Content.AssetRepository.ReloadAssetsIfSourceChanged(), ReLogic.Content.AssetRepository.ThrowIfDisposed(), ReLogic.Content.AssetRepository.ThrowIfNotMainThread(), and ReLogic.Content.AssetRepository.TransferAllAssets().