Terraria: NetClientSocialModule.CheckParameters
CheckParameters() [2/2]
void NetClientSocialModule.CheckParameters () inline private
     {
         //IL_000e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0018: Expected O, but got Unknown
         RailID server_id = new RailID();
         if (!GetRailConnectIDFromCmdLine(server_id))
         {
             return;
         }
         if (((RailComparableID)server_id).IsValid())
         {
             Main.OpenPlayerSelect(delegate(PlayerFileData playerData)
             {
                 Main.ServerSideCharacter = false;
                 playerData.SetAsActive();
                 Main.menuMode = 882;
                 Main.statusText = Language.GetTextValue("Social.Joining");
                 WeGameHelper.WriteDebugString(" CheckParameters， lobby.join");
                 JoinServer(server_id);
             });
         }
         else
         {
             WeGameHelper.WriteDebugString("Invalid RailID passed to +connect_lobby");
         }
     }
References GetRailConnectIDFromCmdLine(), Language.GetTextValue(), JoinServer(), Main.menuMode, Main.OpenPlayerSelect(), Main.ServerSideCharacter, PlayerFileData.SetAsActive(), Main.statusText, and WeGameHelper.WriteDebugString().