Terraria: Netplay.UpdateClientInMainThread
UpdateClientInMainThread()
static void Netplay.UpdateClientInMainThread () inline static private
     {
         if (Main.netMode == 1 && Connection.Socket.IsConnected() && !Connection.ServerWantsToRunCheckBytesInClientLoopThread && NetMessage.buffer[256].checkBytes)
         {
             NetMessage.CheckBytes();
         }
     }
References NetMessage.buffer, MessageBuffer.checkBytes, NetMessage.CheckBytes(), Connection, ISocket.IsConnected(), Main.netMode, RemoteServer.ServerWantsToRunCheckBytesInClientLoopThread, and RemoteServer.Socket.
Referenced by UpdateInMainThread().