Terraria: NetClientSocialModule.OnGetFriendMetaData
OnGetFriendMetaData()
void NetClientSocialModule.OnGetFriendMetaData (RailFriendsGetMetadataResult data) inline private
     {
         //IL_0001: Unknown result type (might be due to invalid IL or missing references)
         //IL_005c: Unknown result type (might be due to invalid IL or missing references)
         //IL_0062: Expected O, but got Unknown
         if ((int)((EventBase)data).result != 0 || data.friend_kvs.Count <= 0)
         {
             return;
         }
         WeGameHelper.WriteDebugString("OnGetFriendMetaData - " + DumpMataDataString(data.friend_kvs));
         string valueByKey = GetValueByKey(_serverIDMedataKey, data.friend_kvs);
         if (valueByKey == null)
         {
             return;
         }
         if (valueByKey.Length > 0)
         {
             RailID val = new RailID();
             ((RailComparableID)val).id_ = ulong.Parse(valueByKey);
             if (((RailComparableID)val).IsValid())
             {
                 JoinServer(val);
             }
             else
             {
                 WeGameHelper.WriteDebugString("JoinServer failed, invalid server id");
             }
         }
         else
         {
             WeGameHelper.WriteDebugString("can not find server id key");
         }
     }
References _serverIDMedataKey, DumpMataDataString(), GetValueByKey(), JoinServer(), and WeGameHelper.WriteDebugString().
Referenced by OnRailEvent().