Terraria: Terraria.IO.PlayerFileData.SetAsActive
SetAsActive()
override void Terraria.IO.PlayerFileData.SetAsActive () inline
Definition at line 60 of file PlayerFileData.cs.
    {
        Main.ActivePlayerFileData = this;
        Main.player[Main.myPlayer] = Player;
    }
References Terraria.Main.myPlayer, Terraria.IO.PlayerFileData.Player, and Terraria.Main.player.
Referenced by Terraria.Social.WeGame.NetClientSocialModule.CheckParameters(), Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), Terraria.Social.WeGame.NetClientSocialModule.OnRailRespondInvation(), and Terraria.Main.SelectPlayer().