Terraria: ReLogic.Content.AssetRepository.Request< T >
Request< T >() [2/2]
virtual Asset< T > ReLogic.Content.AssetRepository.Request< T > (string assetName, AssetRequestMode mode = AssetRequestMode::AsyncLoad) inline virtual
Implements ReLogic.Content.IAssetRepository.
Type Constraints
T : class
Definition at line 154 of file AssetRepository.cs.
                                                                                                                     : class
    {
        if (_readers == null)
        {
            mode = AssetRequestMode.DoNotLoad;
        }
        ThrowIfDisposed();
        assetName = AssetPathHelper.CleanPath(assetName);
        Asset<T> asset = null;
        lock (_requestLock)
        {
            if (_assets.TryGetValue(assetName, out var value))
            {
                asset = value as Asset<T>;
            }
            if (asset == null)
            {
                asset = new Asset<T>(assetName);
                _assets[assetName] = asset;
            }
            if (asset.State == AssetState.NotLoaded)
            {
                EnsureReloadActionExistsForType<T>();
                LoadAsset(asset, mode);
            }
        }
        if (mode == AssetRequestMode.ImmediateLoad)
        {
            asset.Wait();
        }
        return asset;
    }
References ReLogic.Content.AssetRepository._assets, ReLogic.Content.AssetRepository._readers, ReLogic.Content.AssetRepository._requestLock, ReLogic.Content.AssetPathHelper.CleanPath(), ReLogic.Content.AssetRepository.EnsureReloadActionExistsForType< T >(), ReLogic.Content.Asset< T >.State, ReLogic.Content.AssetRepository.ThrowIfDisposed(), and ReLogic.Content.Asset< T >.Wait.