Terraria: NetClientSocialModule.OnRailRespondInvation
OnRailRespondInvation()
void NetClientSocialModule.OnRailRespondInvation (RailUsersRespondInvitation data) inline private
     {
         WeGameHelper.WriteDebugString(" request join game");
         if (_lobby.State != 0)
         {
             _lobby.Leave();
         }
         _inviter_id = data.inviter_id;
         Main.OpenPlayerSelect(delegate(PlayerFileData playerData)
         {
             Main.ServerSideCharacter = false;
             playerData.SetAsActive();
             Main.menuMode = 882;
             Main.statusText = Language.GetTextValue("Social.JoiningFriend", GetFriendNickname(data.inviter_id));
             AsyncGetServerIDByOwener(data.inviter_id);
             WeGameHelper.WriteDebugString("inviter_id: " + ((RailComparableID)data.inviter_id).id_);
         });
     }
References _inviter_id, NetSocialModule._lobby, AsyncGetServerIDByOwener(), GetFriendNickname(), Language.GetTextValue(), Lobby.Leave(), Main.menuMode, Main.OpenPlayerSelect(), Main.ServerSideCharacter, PlayerFileData.SetAsActive(), Lobby.State, Main.statusText, and WeGameHelper.WriteDebugString().
Referenced by OnRailEvent().