Terraria: System.Xml.Xsl.Xslt.SingletonFocus.GetCurrent
GetCurrent()
QilNode System.Xml.Xsl.Xslt.SingletonFocus.GetCurrent () inline
Implements System.Xml.Xsl.XPath.IFocus.
Definition at line 40 of file SingletonFocus.cs.
    {
        return _focusType switch
        {
            SingletonFocusType.InitialDocumentNode => _f.Root(_f.XmlContext()),
            SingletonFocusType.InitialContextNode => _f.XmlContext(),
            _ => _current,
        };
    }
References System.Xml.Xsl.Xslt.SingletonFocus._current, System.Xml.Xsl.Xslt.SingletonFocus._f, System.Xml.Xsl.Xslt.SingletonFocus._focusType, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Root(), and System.Xml.Xsl.Qil.QilPatternFactory.XmlContext().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.GetCurrentNode().