Terraria: System.ComponentModel.Design.DesigntimeLicenseContextSerializer.Deserialize
Deserialize()
static void System.ComponentModel.Design.DesigntimeLicenseContextSerializer.Deserialize (Stream o, string cryptoKey, RuntimeLicenseContext context) inline static package
Definition at line 135 of file DesigntimeLicenseContextSerializer.cs.
    {
        StreamWrapper streamWrapper = new StreamWrapper(o);
        if (StreamIsBinaryFormatted(streamWrapper))
        {
            DeserializeUsingBinaryFormatter(streamWrapper, cryptoKey, context);
            return;
        }
        using BinaryReader binaryReader = new BinaryReader(streamWrapper, Encoding.UTF8, leaveOpen: true);
        byte firstByte = streamWrapper._firstByte;
        string text = binaryReader.ReadString();
        int num = binaryReader.ReadInt32();
        if (text == cryptoKey)
        {
            context._savedLicenseKeys.Clear();
            for (int i = 0; i < num; i++)
            {
                string key = binaryReader.ReadString();
                string value = binaryReader.ReadString();
                context._savedLicenseKeys.Add(key, value);
            }
        }
    }
References System.ComponentModel.Design.RuntimeLicenseContext._savedLicenseKeys, System.Collections.Hashtable.Add(), System.Collections.Hashtable.Clear(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.DeserializeUsingBinaryFormatter(), System.Runtime.Serialization.Dictionary, System.key, System.IO.BinaryReader.ReadString(), System.ComponentModel.Design.DesigntimeLicenseContextSerializer.StreamIsBinaryFormatted(), System.text, System.Text.Encoding.UTF8, and System.value.
Referenced by System.ComponentModel.Design.RuntimeLicenseContext.GetSavedLicenseKey().