Terraria: UnlockableNPCEntryIcon.Update
Update()
void UnlockableNPCEntryIcon.Update (BestiaryUICollectionInfo providedInfo, Rectangle hitbox, EntryIconDrawSettings settings) inline
Implements IEntryIcon.
     {
         Vector2 positionOffsetCache = default(Vector2);
         int? num = null;
         int? num2 = null;
         int? num3 = null;
         bool wet = false;
         float num4 = 0f;
         Asset<Texture2D> val = null;
         if (NPCID.Sets.NPCBestiaryDrawOffset.TryGetValue(_npcNetId, out var value))
         {
             _npcCache.rotation = value.Rotation;
             _npcCache.scale = value.Scale;
             if (value.PortraitScale.HasValue && settings.IsPortrait)
             {
                 _npcCache.scale = value.PortraitScale.Value;
             }
             positionOffsetCache = value.Position;
             num = value.Frame;
             num2 = value.Direction;
             num3 = value.SpriteDirection;
             num4 = value.Velocity;
             wet = value.IsWet;
             if (value.PortraitPositionXOverride.HasValue && settings.IsPortrait)
             {
                 positionOffsetCache.X = value.PortraitPositionXOverride.Value;
             }
             if (value.PortraitPositionYOverride.HasValue && settings.IsPortrait)
             {
                 positionOffsetCache.Y = value.PortraitPositionYOverride.Value;
             }
             if (value.CustomTexturePath != null)
             {
                 val = Main.Assets.Request<Texture2D>(value.CustomTexturePath, (AssetRequestMode)1);
             }
             if (val != null && val.IsLoaded)
             {
                 _customTexture = val;
             }
         }
         _positionOffsetCache = positionOffsetCache;
         UpdatePosition(settings);
         if (NPCID.Sets.TrailingMode[_npcCache.type] != -1)
         {
             for (int i = 0; i < _npcCache.oldPos.Length; i++)
             {
                 _npcCache.oldPos[i] = _npcCache.position;
             }
         }
         _npcCache.direction = (_npcCache.spriteDirection = (num2.HasValue ? num2.Value : (-1)));
         if (num3.HasValue)
         {
             _npcCache.spriteDirection = num3.Value;
         }
         _npcCache.wet = wet;
         AdjustSpecialSpawnRulesForVisuals(settings);
         SimulateFirstHover(num4);
         if (!num.HasValue && (settings.IsPortrait || settings.IsHovered))
         {
             _npcCache.velocity.X = (float)_npcCache.direction * num4;
             _npcCache.FindFrame();
         }
         else if (num.HasValue)
         {
             _npcCache.FindFrame();
             _npcCache.frame.Y = _npcCache.frame.Height * num.Value;
         }
     }
References _customTexture, _npcCache, _npcNetId, _positionOffsetCache, AdjustSpecialSpawnRulesForVisuals(), Main.Assets, Entity.direction, NPC.FindFrame(), NPC.frame, EntryIconDrawSettings.IsHovered, Asset< T >.IsLoaded, EntryIconDrawSettings.IsPortrait, NPCID.Sets.NPCBestiaryDrawOffset, NPC.oldPos, Entity.position, NPC.rotation, NPC.scale, SimulateFirstHover(), NPC.spriteDirection, NPCID.Sets.TrailingMode, NPC.type, UpdatePosition(), Entity.velocity, and Entity.wet.