Terraria: UnlockableNPCEntryIcon.SimulateFirstHover
SimulateFirstHover()
void UnlockableNPCEntryIcon.SimulateFirstHover (float velocity) inline private
     {
         if (!_firstUpdateDone)
         {
             _firstUpdateDone = true;
             _npcCache.SetFrameSize();
             _npcCache.velocity.X = (float)_npcCache.direction * velocity;
             for (int i = 0; i < 1; i++)
             {
                 _npcCache.FindFrame();
             }
         }
     }
References _firstUpdateDone, _npcCache, Entity.direction, NPC.FindFrame(), NPC.SetFrameSize(), and Entity.velocity.
Referenced by Update().