Terraria: UnlockableNPCEntryIcon.Draw
Draw()
void UnlockableNPCEntryIcon.Draw (BestiaryUICollectionInfo providedInfo, SpriteBatch spriteBatch, EntryIconDrawSettings settings) inline
Implements IEntryIcon.
     {
         UpdatePosition(settings);
         if (_customTexture != null)
         {
             spriteBatch.Draw(_customTexture.Value, _npcCache.Center, null, Color.White, 0f, _customTexture.Size() / 2f, _npcCache.scale, SpriteEffects.None, 0f);
             return;
         }
         if (_npcCache.townNPC && TownNPCProfiles.Instance.GetProfile(_npcCache.type, out var profile))
         {
             TextureAssets.Npc[_npcCache.type] = profile.GetTextureNPCShouldUse(_npcCache);
         }
         Main.instance.DrawNPCDirect(spriteBatch, _npcCache, _npcCache.behindTiles, Vector2.Zero);
     }
References _customTexture, _npcCache, NPC.behindTiles, Entity.Center, Color, Main.DrawNPCDirect(), TownNPCProfiles.GetProfile(), TownNPCProfiles.Instance, Main.instance, TextureAssets.Npc, NPC.scale, NPC.townNPC, NPC.type, UpdatePosition(), and Asset< T >.Value.