Terraria: System.Diagnostics.ActivityTagsCollection._list
_list
List<KeyValuePair<string, object> > System.Diagnostics.ActivityTagsCollection._list = new List<KeyValuePair<string, object>>() private
Definition at line 37 of file ActivityTagsCollection.cs.
Referenced by System.Diagnostics.ActivityTagsCollection.Add(), System.Diagnostics.ActivityTagsCollection.Add(), System.Diagnostics.ActivityTagsCollection.Clear(), System.Diagnostics.ActivityTagsCollection.Contains(), System.Diagnostics.ActivityTagsCollection.CopyTo(), System.Diagnostics.ActivityTagsCollection.FindIndex(), System.Diagnostics.ActivityTagsCollection.GetEnumerator(), System.Diagnostics.ActivityTagsCollection.Remove(), System.Diagnostics.ActivityTagsCollection.Remove(), and System.Diagnostics.ActivityTagsCollection.TryGetValue().