Terraria: System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor.VisitLoop
VisitLoop()
override QilNode System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor.VisitLoop (QilLoop n) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 37 of file KeyMatchBuilder.cs.
        {
            if (n.Variable.Binding.NodeType == QilNodeType.Root || n.Variable.Binding.NodeType == QilNodeType.Deref)
            {
                return n;
            }
            if (n.Variable.Binding.NodeType == QilNodeType.Content)
            {
                QilUnary qilUnary = (QilUnary)n.Variable.Binding;
                QilIterator variable = (QilIterator)(qilUnary.Child = f.For(f.DescendantOrSelf(f.Root(_fixup))));
                n.Variable.Binding = f.Loop(variable, qilUnary);
                return n;
            }
            n.Variable.Binding = Visit(n.Variable.Binding);
            return n;
        }
References System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor._fixup, System.Xml.Xsl.Qil.QilPatternFactory.DescendantOrSelf(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor.f, System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.Root(), and System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor.Visit().
Referenced by System.Xml.Xsl.Xslt.KeyMatchBuilder.PathConvertor.VisitFilter().