Terraria: System.Net.HttpListenerRequestUriBuilder.EmptyDecodeAndAppendRawOctetsList
EmptyDecodeAndAppendRawOctetsList()
bool System.Net.HttpListenerRequestUriBuilder.EmptyDecodeAndAppendRawOctetsList (Encoding encoding) inline private
Definition at line 222 of file HttpListenerRequestUriBuilder.cs.
    {
        if (_rawOctets.Count == 0)
        {
            return true;
        }
        string text = null;
        try
        {
            text = encoding.GetString(_rawOctets.ToArray());
            if (encoding == s_utf8Encoding)
            {
                AppendOctetsPercentEncoded(_requestUriString, _rawOctets.ToArray());
            }
            else
            {
                AppendOctetsPercentEncoded(_requestUriString, s_utf8Encoding.GetBytes(text));
            }
            _rawOctets.Clear();
            return true;
        }
        catch (DecoderFallbackException ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_log_listener_cant_convert_bytes, GetOctetsAsString(_rawOctets), ex.Message), "EmptyDecodeAndAppendRawOctetsList");
            }
        }
        catch (EncoderFallbackException ex2)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_log_listener_cant_convert_to_utf8, text, ex2.Message), "EmptyDecodeAndAppendRawOctetsList");
            }
        }
        return false;
    }
References System.Net.HttpListenerRequestUriBuilder._rawOctets, System.Net.HttpListenerRequestUriBuilder._requestUriString, System.Net.HttpListenerRequestUriBuilder.AppendOctetsPercentEncoded(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.HttpListenerRequestUriBuilder.GetOctetsAsString(), System.Text.Encoding.GetString(), System.Net.NetEventSource.Log, System.SR.net_log_listener_cant_convert_bytes, System.SR.net_log_listener_cant_convert_to_utf8, System.Net.HttpListenerRequestUriBuilder.s_utf8Encoding, System.text, and System.Collections.Generic.List< T >.ToArray().
Referenced by System.Net.HttpListenerRequestUriBuilder.ParseRawPath().