Terraria: System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingCookedPath
BuildRequestUriUsingCookedPath()
void System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingCookedPath () inline private
Definition at line 69 of file HttpListenerRequestUriBuilder.cs.
    {
        if (!Uri.TryCreate(_cookedUriScheme + Uri.SchemeDelimiter + _cookedUriHost + _cookedUriPath + _cookedUriQuery, UriKind.Absolute, out _requestUri) && System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_log_listener_cant_create_uri, _cookedUriScheme, _cookedUriHost, _cookedUriPath, _cookedUriQuery), "BuildRequestUriUsingCookedPath");
        }
    }
References System.Net.HttpListenerRequestUriBuilder._cookedUriHost, System.Net.HttpListenerRequestUriBuilder._cookedUriPath, System.Net.HttpListenerRequestUriBuilder._cookedUriQuery, System.Net.HttpListenerRequestUriBuilder._cookedUriScheme, System.Net.HttpListenerRequestUriBuilder._requestUri, System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_log_listener_cant_create_uri, System.Uri.SchemeDelimiter, and System.Uri.TryCreate().
Referenced by System.Net.HttpListenerRequestUriBuilder.Build().