Terraria: System.Net.HttpListenerRequestUriBuilder.ParseRawPath
ParseRawPath()
ParsingResult System.Net.HttpListenerRequestUriBuilder.ParseRawPath (Encoding encoding) inline private
Definition at line 125 of file HttpListenerRequestUriBuilder.cs.
    {
        int num = 0;
        char c = '\0';
        while (num < _rawPath.Length)
        {
            c = _rawPath[num];
            if (c == '%')
            {
                num++;
                c = _rawPath[num];
                if (c == 'u' || c == 'U')
                {
                    if (!EmptyDecodeAndAppendRawOctetsList(encoding))
                    {
                        return ParsingResult.EncodingError;
                    }
                    if (!AppendUnicodeCodePointValuePercentEncoded(_rawPath.Substring(num + 1, 4)))
                    {
                        return ParsingResult.InvalidString;
                    }
                    num += 5;
                }
                else
                {
                    if (!AddPercentEncodedOctetToRawOctetsList(encoding, _rawPath.Substring(num, 2)))
                    {
                        return ParsingResult.InvalidString;
                    }
                    num += 2;
                }
            }
            else
            {
                if (!EmptyDecodeAndAppendRawOctetsList(encoding))
                {
                    return ParsingResult.EncodingError;
                }
                _requestUriString.Append(c);
                num++;
            }
        }
        if (!EmptyDecodeAndAppendRawOctetsList(encoding))
        {
            return ParsingResult.EncodingError;
        }
        return ParsingResult.Success;
    }
References System.Net.HttpListenerRequestUriBuilder._rawPath, System.Net.HttpListenerRequestUriBuilder._requestUriString, System.Net.HttpListenerRequestUriBuilder.AddPercentEncodedOctetToRawOctetsList(), System.Text.StringBuilder.Append(), System.Net.HttpListenerRequestUriBuilder.AppendUnicodeCodePointValuePercentEncoded(), and System.Net.HttpListenerRequestUriBuilder.EmptyDecodeAndAppendRawOctetsList().
Referenced by System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath().