Terraria: System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath
BuildRequestUriUsingRawPath() [1/2]
void System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath () inline private
Definition at line 77 of file HttpListenerRequestUriBuilder.cs.
    {
        bool flag = false;
        _rawPath = GetPath(_rawUri);
        ParsingResult parsingResult = BuildRequestUriUsingRawPath(GetEncoding(EncodingType.Primary));
        if (parsingResult == ParsingResult.EncodingError)
        {
            Encoding encoding = GetEncoding(EncodingType.Secondary);
            parsingResult = BuildRequestUriUsingRawPath(encoding);
        }
        if (parsingResult != 0 && 0 == 0 && System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_log_listener_cant_create_uri, _cookedUriScheme, _cookedUriHost, _rawPath, _cookedUriQuery), "BuildRequestUriUsingRawPath");
        }
    }
References System.Net.HttpListenerRequestUriBuilder._cookedUriHost, System.Net.HttpListenerRequestUriBuilder._cookedUriQuery, System.Net.HttpListenerRequestUriBuilder._cookedUriScheme, System.Net.HttpListenerRequestUriBuilder._rawPath, System.Net.HttpListenerRequestUriBuilder._rawUri, System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath(), System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.HttpListenerRequestUriBuilder.GetEncoding(), System.Net.HttpListenerRequestUriBuilder.GetPath(), System.Net.NetEventSource.Log, and System.SR.net_log_listener_cant_create_uri.
Referenced by System.Net.HttpListenerRequestUriBuilder.Build(), and System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath().