Terraria: System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath
BuildRequestUriUsingRawPath() [2/2]
ParsingResult System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath (Encoding encoding) inline private
Definition at line 102 of file HttpListenerRequestUriBuilder.cs.
    {
        _rawOctets = new List<byte>();
        _requestUriString = new StringBuilder();
        _requestUriString.Append(_cookedUriScheme);
        _requestUriString.Append(Uri.SchemeDelimiter);
        _requestUriString.Append(_cookedUriHost);
        ParsingResult parsingResult = ParseRawPath(encoding);
        if (parsingResult == ParsingResult.Success)
        {
            _requestUriString.Append(_cookedUriQuery);
            if (!Uri.TryCreate(_requestUriString.ToString(), UriKind.Absolute, out _requestUri))
            {
                parsingResult = ParsingResult.InvalidString;
            }
        }
        if (parsingResult != 0 && System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Error(this, System.SR.Format(System.SR.net_log_listener_cant_convert_raw_path, _rawPath, encoding.EncodingName), "BuildRequestUriUsingRawPath");
        }
        return parsingResult;
    }
References System.Net.HttpListenerRequestUriBuilder._cookedUriHost, System.Net.HttpListenerRequestUriBuilder._cookedUriQuery, System.Net.HttpListenerRequestUriBuilder._cookedUriScheme, System.Net.HttpListenerRequestUriBuilder._rawOctets, System.Net.HttpListenerRequestUriBuilder._rawPath, System.Net.HttpListenerRequestUriBuilder._requestUri, System.Net.HttpListenerRequestUriBuilder._requestUriString, System.Text.StringBuilder.Append(), System.Text.Encoding.EncodingName, System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_log_listener_cant_convert_raw_path, System.Net.HttpListenerRequestUriBuilder.ParseRawPath(), System.Uri.SchemeDelimiter, System.Text.StringBuilder.ToString(), and System.Uri.TryCreate().