Terraria: System.Security.Cryptography.SymmetricAlgorithm.CheckInitializationVectorSize
CheckInitializationVectorSize()
void System.Security.Cryptography.SymmetricAlgorithm.CheckInitializationVectorSize (ReadOnlySpan< byte > iv) inline private inherited
Definition at line 634 of file SymmetricAlgorithm.cs.
    {
        if (iv.Length != BlockSize >> 3)
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidIVSize, "iv");
        }
    }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSize, System.SR.Cryptography_InvalidIVSize, and System.ReadOnlySpan< T >.Length.
Referenced by System.Security.Cryptography.SymmetricAlgorithm.DecryptCbc(), System.Security.Cryptography.SymmetricAlgorithm.DecryptCbc(), System.Security.Cryptography.SymmetricAlgorithm.DecryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.DecryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.EncryptCbc(), System.Security.Cryptography.SymmetricAlgorithm.EncryptCbc(), System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCbc(), System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.TryEncryptCbc(), and System.Security.Cryptography.SymmetricAlgorithm.TryEncryptCfb().