Terraria: System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCfbCore
TryDecryptCfbCore()
virtual bool System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCfbCore (ReadOnlySpan< byte > ciphertext, ReadOnlySpan< byte > iv, Span< byte > destination, PaddingMode paddingMode, int feedbackSizeInBits, out int bytesWritten) inline protected virtual inherited
Reimplemented in Internal.Cryptography.AesImplementation, Internal.Cryptography.DesImplementation, Internal.Cryptography.RC2Implementation, Internal.Cryptography.TripleDesImplementation, System.Security.Cryptography.AesCng, and System.Security.Cryptography.TripleDESCng.
Definition at line 616 of file SymmetricAlgorithm.cs.
    {
        throw new NotSupportedException(System.SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Security.Cryptography.SymmetricAlgorithm.DecryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.DecryptCfb(), and System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCfb().