Terraria: System.Security.Cryptography.SymmetricAlgorithm.TryEncryptEcbCore
TryEncryptEcbCore()
virtual bool System.Security.Cryptography.SymmetricAlgorithm.TryEncryptEcbCore (ReadOnlySpan< byte > plaintext, Span< byte > destination, PaddingMode paddingMode, out int bytesWritten) inline protected virtual inherited
Reimplemented in Internal.Cryptography.AesImplementation, Internal.Cryptography.DesImplementation, Internal.Cryptography.RC2Implementation, Internal.Cryptography.TripleDesImplementation, System.Security.Cryptography.AesCng, and System.Security.Cryptography.TripleDESCng.
Definition at line 596 of file SymmetricAlgorithm.cs.
    {
        throw new NotSupportedException(System.SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Security.Cryptography.SymmetricAlgorithm.EncryptEcb(), System.Security.Cryptography.SymmetricAlgorithm.EncryptEcb(), and System.Security.Cryptography.SymmetricAlgorithm.TryEncryptEcb().