Terraria: System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb
EncryptCfb() [3/3]
int System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb (ReadOnlySpan< byte > plaintext, ReadOnlySpan< byte > iv, Span< byte > destination, PaddingMode paddingMode = PaddingMode::None, int feedbackSizeInBits = 8) inline inherited
Definition at line 576 of file SymmetricAlgorithm.cs.
    {
        CheckPaddingMode(paddingMode);
        CheckInitializationVectorSize(iv);
        CheckFeedbackSize(feedbackSizeInBits);
        if (!TryEncryptCfbCore(plaintext, iv, destination, paddingMode, feedbackSizeInBits, out var bytesWritten))
        {
            throw new ArgumentException(System.SR.Argument_DestinationTooShort, "destination");
        }
        return bytesWritten;
    }
References System.SR.Argument_DestinationTooShort, System.Security.Cryptography.SymmetricAlgorithm.CheckFeedbackSize(), System.Security.Cryptography.SymmetricAlgorithm.CheckInitializationVectorSize(), System.Security.Cryptography.SymmetricAlgorithm.CheckPaddingMode(), System.destination, and System.Security.Cryptography.SymmetricAlgorithm.TryEncryptCfbCore().