Terraria: System.Security.Cryptography.SymmetricAlgorithm.GetCiphertextLengthBlockAligned
GetCiphertextLengthBlockAligned()
int System.Security.Cryptography.SymmetricAlgorithm.GetCiphertextLengthBlockAligned (int plaintextLength, PaddingMode paddingMode) inline private inherited
Definition at line 252 of file SymmetricAlgorithm.cs.
    {
        if (plaintextLength < 0)
        {
            throw new ArgumentOutOfRangeException("plaintextLength", System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        int blockSize = BlockSize;
        if (blockSize <= 0 || ((uint)blockSize & 7u) != 0)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_UnsupportedBlockSize);
        }
        int num = blockSize >> 3;
        int result;
        int num2 = Math.DivRem(plaintextLength, num, out result) * num;
        switch (paddingMode)
        {
        case PaddingMode.None:
            if (result != 0)
            {
                throw new ArgumentException(System.SR.Cryptography_MatchBlockSize, "plaintextLength");
            }
            goto IL_0077;
        case PaddingMode.Zeros:
            if (result == 0)
            {
                goto IL_0077;
            }
            goto case PaddingMode.PKCS7;
        case PaddingMode.PKCS7:
        case PaddingMode.ANSIX923:
        case PaddingMode.ISO10126:
            if (int.MaxValue - num2 < num)
            {
                throw new ArgumentOutOfRangeException("plaintextLength", System.SR.Cryptography_PlaintextTooLarge);
            }
            return num2 + num;
        default:
            {
                throw new ArgumentOutOfRangeException("paddingMode", System.SR.Cryptography_InvalidPaddingMode);
            }
            IL_0077:
            return plaintextLength;
        }
    }
References System.SR.ArgumentOutOfRange_NeedNonNegNum, System.Security.Cryptography.SymmetricAlgorithm.BlockSize, System.SR.Cryptography_InvalidPaddingMode, System.SR.Cryptography_MatchBlockSize, System.SR.Cryptography_PlaintextTooLarge, System.Math.DivRem(), and System.SR.InvalidOperation_UnsupportedBlockSize.
Referenced by System.Security.Cryptography.SymmetricAlgorithm.GetCiphertextLengthCbc(), and System.Security.Cryptography.SymmetricAlgorithm.GetCiphertextLengthEcb().