Terraria: System.Security.Cryptography.SymmetricAlgorithm.CheckFeedbackSize
CheckFeedbackSize()
void System.Security.Cryptography.SymmetricAlgorithm.CheckFeedbackSize (int feedbackSizeInBits) inline private inherited
Definition at line 642 of file SymmetricAlgorithm.cs.
    {
        if (feedbackSizeInBits < 8 || ((uint)feedbackSizeInBits & 7u) != 0 || feedbackSizeInBits > BlockSize)
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidFeedbackSize, "feedbackSizeInBits");
        }
    }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSize, and System.SR.Cryptography_InvalidFeedbackSize.
Referenced by System.Security.Cryptography.SymmetricAlgorithm.DecryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.DecryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCfb(), and System.Security.Cryptography.SymmetricAlgorithm.TryEncryptCfb().