Terraria: System.Security.Cryptography.SymmetricAlgorithm.CreateDecryptor
CreateDecryptor() [1/2]
virtual ICryptoTransform System.Security.Cryptography.SymmetricAlgorithm.CreateDecryptor () inline virtual inherited
Reimplemented in Internal.Cryptography.AesImplementation, Internal.Cryptography.DesImplementation, Internal.Cryptography.RC2Implementation, Internal.Cryptography.RijndaelImplementation, Internal.Cryptography.TripleDesImplementation, System.Security.Cryptography.AesManaged, System.Security.Cryptography.RijndaelManaged, System.Security.Cryptography.AesCng, System.Security.Cryptography.TripleDESCng, System.Security.Cryptography.AesCryptoServiceProvider, System.Security.Cryptography.DESCryptoServiceProvider, and System.Security.Cryptography.TripleDESCryptoServiceProvider.
Definition at line 186 of file SymmetricAlgorithm.cs.
    {
        return CreateDecryptor(Key, IV);
    }
References System.Security.Cryptography.SymmetricAlgorithm.CreateDecryptor(), System.Security.Cryptography.SymmetricAlgorithm.IV, and System.Security.Cryptography.SymmetricAlgorithm.Key.
Referenced by Internal.Cryptography.RijndaelImplementation.CreateDecryptor(), System.Security.Cryptography.AesManaged.CreateDecryptor(), System.Security.Cryptography.RijndaelManaged.CreateDecryptor(), System.Security.Cryptography.AesCryptoServiceProvider.CreateDecryptor(), System.Security.Cryptography.TripleDESCryptoServiceProvider.CreateDecryptor(), System.Security.Cryptography.SymmetricAlgorithm.CreateDecryptor(), Internal.Cryptography.RijndaelImplementation.CreateDecryptor(), System.Security.Cryptography.AesManaged.CreateDecryptor(), System.Security.Cryptography.RijndaelManaged.CreateDecryptor(), System.Security.Cryptography.AesCryptoServiceProvider.CreateDecryptor(), System.Security.Cryptography.TripleDESCryptoServiceProvider.CreateDecryptor(), and System.Security.Cryptography.PasswordBasedEncryption.Decrypt().