Terraria: System.Security.Cryptography.SymmetricAlgorithm.TryDecryptEcbCore
TryDecryptEcbCore()
virtual bool System.Security.Cryptography.SymmetricAlgorithm.TryDecryptEcbCore (ReadOnlySpan< byte > ciphertext, Span< byte > destination, PaddingMode paddingMode, out int bytesWritten) inline protected virtual inherited
Reimplemented in Internal.Cryptography.AesImplementation, Internal.Cryptography.DesImplementation, Internal.Cryptography.RC2Implementation, Internal.Cryptography.TripleDesImplementation, System.Security.Cryptography.AesCng, and System.Security.Cryptography.TripleDESCng.
Definition at line 601 of file SymmetricAlgorithm.cs.
    {
        throw new NotSupportedException(System.SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Security.Cryptography.SymmetricAlgorithm.DecryptEcb(), System.Security.Cryptography.SymmetricAlgorithm.DecryptEcb(), and System.Security.Cryptography.SymmetricAlgorithm.TryDecryptEcb().