Terraria: System.Security.Cryptography.SymmetricAlgorithm.TryEncryptCfbCore
TryEncryptCfbCore()
virtual bool System.Security.Cryptography.SymmetricAlgorithm.TryEncryptCfbCore (ReadOnlySpan< byte > plaintext, ReadOnlySpan< byte > iv, Span< byte > destination, PaddingMode paddingMode, int feedbackSizeInBits, out int bytesWritten) inline protected virtual inherited
Reimplemented in Internal.Cryptography.AesImplementation, Internal.Cryptography.DesImplementation, Internal.Cryptography.RC2Implementation, Internal.Cryptography.TripleDesImplementation, System.Security.Cryptography.AesCng, and System.Security.Cryptography.TripleDESCng.
Definition at line 621 of file SymmetricAlgorithm.cs.
    {
        throw new NotSupportedException(System.SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb(), System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb(), and System.Security.Cryptography.SymmetricAlgorithm.TryEncryptCfb().