Terraria: System.Security.Cryptography.SymmetricAlgorithm.EncryptEcb
EncryptEcb() [2/3]
byte[] System.Security.Cryptography.SymmetricAlgorithm.EncryptEcb (ReadOnlySpan< byte > plaintext, PaddingMode paddingMode) inline inherited
Definition at line 391 of file SymmetricAlgorithm.cs.
    {
        CheckPaddingMode(paddingMode);
        int ciphertextLengthEcb = GetCiphertextLengthEcb(plaintext.Length, paddingMode);
        byte[] array = GC.AllocateUninitializedArray<byte>(ciphertextLengthEcb);
        if (!TryEncryptEcbCore(plaintext, array, paddingMode, out var bytesWritten) || bytesWritten != ciphertextLengthEcb)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_EncryptedIncorrectLength, "TryEncryptEcbCore"));
        }
        return array;
    }
References System.array, System.Security.Cryptography.SymmetricAlgorithm.CheckPaddingMode(), System.SR.Cryptography_EncryptedIncorrectLength, System.SR.Format(), System.Security.Cryptography.SymmetricAlgorithm.GetCiphertextLengthEcb(), System.ReadOnlySpan< T >.Length, and System.Security.Cryptography.SymmetricAlgorithm.TryEncryptEcbCore().