Terraria: System.Security.Cryptography.SymmetricAlgorithm.CreateEncryptor
CreateEncryptor() [1/2]
virtual ICryptoTransform System.Security.Cryptography.SymmetricAlgorithm.CreateEncryptor () inline virtual inherited
Reimplemented in Internal.Cryptography.AesImplementation, Internal.Cryptography.DesImplementation, Internal.Cryptography.RC2Implementation, Internal.Cryptography.RijndaelImplementation, Internal.Cryptography.TripleDesImplementation, System.Security.Cryptography.AesManaged, System.Security.Cryptography.RijndaelManaged, System.Security.Cryptography.AesCng, System.Security.Cryptography.TripleDESCng, System.Security.Cryptography.AesCryptoServiceProvider, System.Security.Cryptography.DESCryptoServiceProvider, and System.Security.Cryptography.TripleDESCryptoServiceProvider.
Definition at line 193 of file SymmetricAlgorithm.cs.
    {
        return CreateEncryptor(Key, IV);
    }
References System.Security.Cryptography.SymmetricAlgorithm.CreateEncryptor(), System.Security.Cryptography.SymmetricAlgorithm.IV, and System.Security.Cryptography.SymmetricAlgorithm.Key.
Referenced by Internal.Cryptography.RijndaelImplementation.CreateEncryptor(), System.Security.Cryptography.AesManaged.CreateEncryptor(), System.Security.Cryptography.RijndaelManaged.CreateEncryptor(), System.Security.Cryptography.AesCryptoServiceProvider.CreateEncryptor(), System.Security.Cryptography.TripleDESCryptoServiceProvider.CreateEncryptor(), System.Security.Cryptography.SymmetricAlgorithm.CreateEncryptor(), Internal.Cryptography.RijndaelImplementation.CreateEncryptor(), System.Security.Cryptography.AesManaged.CreateEncryptor(), System.Security.Cryptography.RijndaelManaged.CreateEncryptor(), System.Security.Cryptography.AesCryptoServiceProvider.CreateEncryptor(), System.Security.Cryptography.TripleDESCryptoServiceProvider.CreateEncryptor(), and System.Security.Cryptography.PasswordBasedEncryption.Encrypt().