Terraria: System.Security.Cryptography.SymmetricAlgorithm.Dispose
Dispose() [1/2]
void System.Security.Cryptography.SymmetricAlgorithm.Dispose () inline inherited
Implements System.IDisposable.
Definition at line 200 of file SymmetricAlgorithm.cs.
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
References System.Security.Cryptography.SymmetricAlgorithm.Dispose(), and System.GC.SuppressFinalize().
Referenced by System.Security.Cryptography.SymmetricAlgorithm.Dispose(), Internal.Cryptography.RijndaelImplementation.Dispose(), System.Security.Cryptography.AesManaged.Dispose(), System.Security.Cryptography.RijndaelManaged.Dispose(), System.Security.Cryptography.AesCryptoServiceProvider.Dispose(), and System.Security.Cryptography.TripleDESCryptoServiceProvider.Dispose().