Terraria: System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb
EncryptCfb() [2/3]
byte[] System.Security.Cryptography.SymmetricAlgorithm.EncryptCfb (ReadOnlySpan< byte > plaintext, ReadOnlySpan< byte > iv, PaddingMode paddingMode = PaddingMode::None, int feedbackSizeInBits = 8) inline inherited
Definition at line 562 of file SymmetricAlgorithm.cs.
    {
        CheckPaddingMode(paddingMode);
        CheckInitializationVectorSize(iv);
        CheckFeedbackSize(feedbackSizeInBits);
        int ciphertextLengthCfb = GetCiphertextLengthCfb(plaintext.Length, paddingMode, feedbackSizeInBits);
        byte[] array = GC.AllocateUninitializedArray<byte>(ciphertextLengthCfb);
        if (!TryEncryptCfbCore(plaintext, iv, array, paddingMode, feedbackSizeInBits, out var bytesWritten) || bytesWritten != ciphertextLengthCfb)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_EncryptedIncorrectLength, "TryEncryptCfbCore"));
        }
        return array;
    }
References System.array, System.Security.Cryptography.SymmetricAlgorithm.CheckFeedbackSize(), System.Security.Cryptography.SymmetricAlgorithm.CheckInitializationVectorSize(), System.Security.Cryptography.SymmetricAlgorithm.CheckPaddingMode(), System.SR.Cryptography_EncryptedIncorrectLength, System.SR.Format(), System.Security.Cryptography.SymmetricAlgorithm.GetCiphertextLengthCfb(), System.ReadOnlySpan< T >.Length, and System.Security.Cryptography.SymmetricAlgorithm.TryEncryptCfbCore().