Terraria: System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCbcCore
TryDecryptCbcCore()
virtual bool System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCbcCore (ReadOnlySpan< byte > ciphertext, ReadOnlySpan< byte > iv, Span< byte > destination, PaddingMode paddingMode, out int bytesWritten) inline protected virtual inherited
Reimplemented in Internal.Cryptography.AesImplementation, Internal.Cryptography.DesImplementation, Internal.Cryptography.RC2Implementation, Internal.Cryptography.TripleDesImplementation, System.Security.Cryptography.AesCng, and System.Security.Cryptography.TripleDESCng.
Definition at line 611 of file SymmetricAlgorithm.cs.
    {
        throw new NotSupportedException(System.SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Security.Cryptography.SymmetricAlgorithm.DecryptCbc(), System.Security.Cryptography.SymmetricAlgorithm.DecryptCbc(), and System.Security.Cryptography.SymmetricAlgorithm.TryDecryptCbc().