Terraria: System.Text.EncoderFallbackBufferHelper.InternalGetNextChar
InternalGetNextChar()
char System.Text.EncoderFallbackBufferHelper.InternalGetNextChar () inline package
Definition at line 49 of file EncoderFallbackBufferHelper.cs.
    {
        char nextChar = _fallbackBuffer.GetNextChar();
        bFallingBack = nextChar != '\0';
        if (nextChar == '\0')
        {
            iRecursionCount = 0;
        }
        return nextChar;
    }
References System.Text.EncoderFallbackBufferHelper._fallbackBuffer, System.Text.EncoderFallbackBufferHelper.bFallingBack, System.Text.EncoderFallbackBuffer.GetNextChar(), and System.Text.EncoderFallbackBufferHelper.iRecursionCount.
Referenced by System.Text.DBCSCodePageEncoding.GetByteCount(), System.Text.SBCSCodePageEncoding.GetByteCount(), System.Text.DBCSCodePageEncoding.GetBytes(), System.Text.SBCSCodePageEncoding.GetBytes(), and System.Text.EncodingByteBuffer.GetNextChar().