Terraria: System.Text.EncoderFallbackBufferHelper.InternalFallback
InternalFallback()
unsafe bool System.Text.EncoderFallbackBufferHelper.InternalFallback (char ch, ref char * chars) inline package
Definition at line 60 of file EncoderFallbackBufferHelper.cs.
    {
        int index = (int)(chars - charStart) - 1;
        if (char.IsHighSurrogate(ch))
        {
            if (chars >= charEnd)
            {
                if (encoder != null && !encoder.MustFlush)
                {
                    if (setEncoder)
                    {
                        bUsedEncoder = true;
                        encoder.charLeftOver = ch;
                    }
                    bFallingBack = false;
                    return false;
                }
            }
            else
            {
                char c = *chars;
                if (char.IsLowSurrogate(c))
                {
                    if (bFallingBack && iRecursionCount++ > 250)
                    {
                        ThrowLastCharRecursive(char.ConvertToUtf32(ch, c));
                    }
                    chars++;
                    bFallingBack = _fallbackBuffer.Fallback(ch, c, index);
                    return bFallingBack;
                }
            }
        }
        if (bFallingBack && iRecursionCount++ > 250)
        {
            ThrowLastCharRecursive(ch);
        }
        bFallingBack = _fallbackBuffer.Fallback(ch, index);
        return bFallingBack;
    }
References System.Text.EncoderFallbackBufferHelper._fallbackBuffer, System.Text.EncoderFallbackBufferHelper.bFallingBack, System.Text.EncoderFallbackBufferHelper.bUsedEncoder, System.ch, System.Text.EncoderFallbackBufferHelper.charEnd, System.chars, System.Text.EncoderFallbackBufferHelper.charStart, System.Text.EncoderFallbackBufferHelper.encoder, System.Text.EncoderFallbackBuffer.Fallback(), System.index, System.Text.EncoderFallbackBufferHelper.iRecursionCount, System.Text.EncoderFallbackBufferHelper.setEncoder, and System.Text.EncoderFallbackBufferHelper.ThrowLastCharRecursive().
Referenced by System.Text.EncodingByteBuffer.Fallback(), System.Text.DBCSCodePageEncoding.GetByteCount(), System.Text.SBCSCodePageEncoding.GetByteCount(), System.Text.DBCSCodePageEncoding.GetBytes(), and System.Text.SBCSCodePageEncoding.GetBytes().