Terraria: System.ComponentModel.LicenseManager.ValidateInternalRecursive
ValidateInternalRecursive()
static bool System.ComponentModel.LicenseManager.ValidateInternalRecursive (LicenseContext context, Type type, object instance, bool allowExceptions, out License license, out string licenseKey) inline static private
Definition at line 294 of file LicenseManager.cs.
    {
        LicenseProvider licenseProvider = GetCachedProvider(type);
        if (licenseProvider == null && !GetCachedNoLicenseProvider(type))
        {
            LicenseProviderAttribute licenseProviderAttribute = (LicenseProviderAttribute)Attribute.GetCustomAttribute(type, typeof(LicenseProviderAttribute), inherit: false);
            if (licenseProviderAttribute != null)
            {
                Type licenseProvider2 = licenseProviderAttribute.LicenseProvider;
                licenseProvider = GetCachedProviderInstance(licenseProvider2) ?? ((LicenseProvider)Activator.CreateInstance(licenseProvider2));
            }
            CacheProvider(type, licenseProvider);
        }
        license = null;
        bool flag = true;
        licenseKey = null;
        if (licenseProvider != null)
        {
            license = licenseProvider.GetLicense(context, type, instance, allowExceptions);
            if (license == null)
            {
                flag = false;
            }
            else
            {
                licenseKey = license.LicenseKey;
            }
        }
        if (flag && instance == null)
        {
            Type baseType = type.BaseType;
            if (baseType != typeof(object) && baseType != null)
            {
                if (license != null)
                {
                    license.Dispose();
                    license = null;
                }
                flag = ValidateInternalRecursive(context, baseType, null, allowExceptions, out license, out var _);
                if (license != null)
                {
                    license.Dispose();
                    license = null;
                }
            }
        }
        return flag;
    }
References System.Type.BaseType, System.ComponentModel.LicenseManager.CacheProvider(), System.Activator.CreateInstance(), System.ComponentModel.LicenseManager.GetCachedNoLicenseProvider(), System.ComponentModel.LicenseManager.GetCachedProvider(), System.ComponentModel.LicenseManager.GetCachedProviderInstance(), System.Attribute.GetCustomAttribute(), System.ComponentModel.LicenseProvider.GetLicense(), System.ComponentModel.LicenseProviderAttribute.LicenseProvider, System.type, and System.ComponentModel.LicenseManager.ValidateInternalRecursive().
Referenced by System.ComponentModel.LicenseManager.LicenseInteropHelper.ValidateAndRetrieveLicenseDetails(), System.ComponentModel.LicenseManager.ValidateInternal(), and System.ComponentModel.LicenseManager.ValidateInternalRecursive().