Terraria: System.ComponentModel.LicenseManager.CreateWithContext
CreateWithContext() [2/2]
static ? object System.ComponentModel.LicenseManager.CreateWithContext ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type type, LicenseContext creationContext, object[] args) inline static
Definition at line 189 of file LicenseManager.cs.
    {
        object obj = null;
        lock (s_internalSyncObject)
        {
            LicenseContext currentContext = CurrentContext;
            try
            {
                CurrentContext = creationContext;
                LockContext(s_selfLock);
                try
                {
                    return Activator.CreateInstance(type, args);
                }
                catch (TargetInvocationException ex)
                {
                    throw ex.InnerException;
                }
            }
            finally
            {
                UnlockContext(s_selfLock);
                CurrentContext = currentContext;
            }
        }
    }
References System.Activator.CreateInstance(), System.ComponentModel.LicenseManager.CurrentContext, System.Exception.InnerException, System.ComponentModel.LicenseManager.LockContext(), System.obj, System.ComponentModel.LicenseManager.s_internalSyncObject, System.ComponentModel.LicenseManager.s_selfLock, System.type, and System.ComponentModel.LicenseManager.UnlockContext().