Terraria: System.Security.Cryptography.X509Certificates.Asn1.ValidityAsn.DecodeCore
DecodeCore()
static void System.Security.Cryptography.X509Certificates.Asn1.ValidityAsn.DecodeCore (ref System::Formats::Asn1::AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out ValidityAsn decoded) inline static private
Definition at line 41 of file ValidityAsn.cs.
    {
        decoded = default(ValidityAsn);
        System.Formats.Asn1.AsnValueReader reader2 = reader.ReadSequence(expectedTag);
        TimeAsn.Decode(ref reader2, rebind, out decoded.NotBefore);
        TimeAsn.Decode(ref reader2, rebind, out decoded.NotAfter);
        reader2.ThrowIfNotEmpty();
    }
References System.Security.Cryptography.X509Certificates.Asn1.TimeAsn.Decode(), System.Formats.Asn1.AsnValueReader.ReadSequence(), and System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty().
Referenced by System.Security.Cryptography.X509Certificates.Asn1.ValidityAsn.Decode().