Terraria: NPCStatsReportInfoElement.ShowStats_Knockback
ShowStats_Knockback()
void NPCStatsReportInfoElement.ShowStats_Knockback (UIElement element) inline private
     {
         if (element.IsMouseHovering)
         {
             Main.instance.MouseText(Language.GetTextValue("BestiaryInfo.Knockback"), 0, 0);
         }
     }
References Language.GetTextValue(), Main.instance, UIElement.IsMouseHovering, and Main.MouseText().
Referenced by ProvideUIElement().