Terraria: System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeaderAndDataIfNeeded
WriteLocalFileHeaderAndDataIfNeeded()
void System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeaderAndDataIfNeeded () inline private
Definition at line 885 of file ZipArchiveEntry.cs.
    {
        if (_storedUncompressedData != null || _compressedBytes != null)
        {
            if (_storedUncompressedData != null)
            {
                _uncompressedSize = _storedUncompressedData.Length;
                using Stream destination = new DirectToArchiveWriterStream(GetDataCompressor(_archive.ArchiveStream, leaveBackingStreamOpen: true, null), this);
                _storedUncompressedData.Seek(0L, SeekOrigin.Begin);
                _storedUncompressedData.CopyTo(destination);
                _storedUncompressedData.Dispose();
                _storedUncompressedData = null;
                return;
            }
            if (_uncompressedSize == 0L)
            {
                _compressedSize = 0L;
            }
            WriteLocalFileHeader(_uncompressedSize == 0);
            if (_uncompressedSize != 0L)
            {
                byte[][] compressedBytes = _compressedBytes;
                foreach (byte[] array in compressedBytes)
                {
                    _archive.ArchiveStream.Write(array, 0, array.Length);
                }
            }
        }
        else if (_archive.Mode == ZipArchiveMode.Update || !_everOpenedForWrite)
        {
            _everOpenedForWrite = true;
            WriteLocalFileHeader(isEmptyFile: true);
        }
    }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._compressedBytes, System.IO.Compression.ZipArchiveEntry._compressedSize, System.IO.Compression.ZipArchiveEntry._everOpenedForWrite, System.IO.Compression.ZipArchiveEntry._storedUncompressedData, System.IO.Compression.ZipArchiveEntry._uncompressedSize, System.IO.Compression.ZipArchive.ArchiveStream, System.array, System.IO.MemoryStream.CopyTo(), System.destination, System.IO.MemoryStream.Dispose(), System.IO.Compression.ZipArchiveEntry.GetDataCompressor(), System.L, System.IO.MemoryStream.Length, System.IO.Compression.ZipArchive.Mode, System.IO.MemoryStream.Seek(), System.IO.Stream.Write(), and System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeader().
Referenced by System.IO.Compression.ZipArchiveEntry.WriteAndFinishLocalEntry().