Terraria: System.IO.Compression.ZipArchiveEntry.IsOpenable
IsOpenable()
bool System.IO.Compression.ZipArchiveEntry.IsOpenable (bool needToUncompress, bool needToLoadIntoMemory, out string message) inline private
Definition at line 755 of file ZipArchiveEntry.cs.
    {
        message = null;
        if (_originallyInArchive)
        {
            if (needToUncompress && CompressionMethod != 0 && CompressionMethod != CompressionMethodValues.Deflate && CompressionMethod != CompressionMethodValues.Deflate64)
            {
                CompressionMethodValues compressionMethod = CompressionMethod;
                if (compressionMethod == CompressionMethodValues.BZip2 || compressionMethod == CompressionMethodValues.LZMA)
                {
                    message = System.SR.Format(System.SR.UnsupportedCompressionMethod, CompressionMethod.ToString());
                }
                else
                {
                    message = System.SR.UnsupportedCompression;
                }
                return false;
            }
            if (_diskNumberStart != _archive.NumberOfThisDisk)
            {
                message = System.SR.SplitSpanned;
                return false;
            }
            if (_offsetOfLocalHeader > _archive.ArchiveStream.Length)
            {
                message = System.SR.LocalFileHeaderCorrupt;
                return false;
            }
            _archive.ArchiveStream.Seek(_offsetOfLocalHeader, SeekOrigin.Begin);
            if (!ZipLocalFileHeader.TrySkipBlock(_archive.ArchiveReader))
            {
                message = System.SR.LocalFileHeaderCorrupt;
                return false;
            }
            if (OffsetOfCompressedData + _compressedSize > _archive.ArchiveStream.Length)
            {
                message = System.SR.LocalFileHeaderCorrupt;
                return false;
            }
            if (needToLoadIntoMemory && _compressedSize > int.MaxValue && !s_allowLargeZipArchiveEntriesInUpdateMode)
            {
                message = System.SR.EntryTooLarge;
                return false;
            }
        }
        return true;
    }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._compressedSize, System.IO.Compression.ZipArchiveEntry._diskNumberStart, System.IO.Compression.ZipArchiveEntry._offsetOfLocalHeader, System.IO.Compression.ZipArchiveEntry._originallyInArchive, System.IO.Compression.ZipArchive.ArchiveReader, System.IO.Compression.ZipArchive.ArchiveStream, System.IO.Compression.ZipArchiveEntry.CompressionMethod, System.SR.EntryTooLarge, System.SR.Format(), System.IO.Stream.Length, System.SR.LocalFileHeaderCorrupt, System.IO.Compression.ZipArchive.NumberOfThisDisk, System.IO.Compression.ZipArchiveEntry.OffsetOfCompressedData, System.IO.Compression.ZipArchiveEntry.s_allowLargeZipArchiveEntriesInUpdateMode, System.IO.Stream.Seek(), System.SR.SplitSpanned, System.IO.Compression.ZipLocalFileHeader.TrySkipBlock(), System.SR.UnsupportedCompression, and System.SR.UnsupportedCompressionMethod.
Referenced by System.IO.Compression.ZipArchiveEntry.ThrowIfNotOpenable().