Terraria: System.IO.Compression.ZipArchiveEntry.SizesTooLarge
SizesTooLarge()
bool System.IO.Compression.ZipArchiveEntry.SizesTooLarge () inline private
Definition at line 803 of file ZipArchiveEntry.cs.
    {
        if (_compressedSize <= uint.MaxValue)
        {
            return _uncompressedSize > uint.MaxValue;
        }
        return true;
    }
References System.IO.Compression.ZipArchiveEntry._compressedSize, and System.IO.Compression.ZipArchiveEntry._uncompressedSize.
Referenced by System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader(), System.IO.Compression.ZipArchiveEntry.WriteCrcAndSizesInLocalHeader(), System.IO.Compression.ZipArchiveEntry.WriteDataDescriptor(), and System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeader().