Terraria: System.IO.Compression.ZipArchiveEntry.Open
Open()
Stream System.IO.Compression.ZipArchiveEntry.Open () inline
Definition at line 529 of file ZipArchiveEntry.cs.
    {
        ThrowIfInvalidArchive();
        return _archive.Mode switch
        {
            ZipArchiveMode.Read => OpenInReadMode(checkOpenable: true),
            ZipArchiveMode.Create => OpenInWriteMode(),
            _ => OpenInUpdateMode(),
        };
    }
References System.IO.Compression.ZipArchiveEntry.OpenInReadMode(), System.IO.Compression.ZipArchiveEntry.OpenInUpdateMode(), System.IO.Compression.ZipArchiveEntry.OpenInWriteMode(), and System.IO.Compression.ZipArchiveEntry.ThrowIfInvalidArchive().