Terraria: System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader
WriteCentralDirectoryFileHeader()
void System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader () inline package
Definition at line 565 of file ZipArchiveEntry.cs.
    {
        BinaryWriter binaryWriter = new BinaryWriter(_archive.ArchiveStream);
        Zip64ExtraField zip64ExtraField = default(Zip64ExtraField);
        bool flag = false;
        uint value;
        uint value2;
        if (SizesTooLarge())
        {
            flag = true;
            value = uint.MaxValue;
            value2 = uint.MaxValue;
            zip64ExtraField.CompressedSize = _compressedSize;
            zip64ExtraField.UncompressedSize = _uncompressedSize;
        }
        else
        {
            value = (uint)_compressedSize;
            value2 = (uint)_uncompressedSize;
        }
        uint value3;
        if (_offsetOfLocalHeader > uint.MaxValue)
        {
            flag = true;
            value3 = uint.MaxValue;
            zip64ExtraField.LocalHeaderOffset = _offsetOfLocalHeader;
        }
        else
        {
            value3 = (uint)_offsetOfLocalHeader;
        }
        if (flag)
        {
            VersionToExtractAtLeast(ZipVersionNeededValues.Zip64);
        }
        int num = (flag ? zip64ExtraField.TotalSize : 0) + ((_cdUnknownExtraFields != null) ? ZipGenericExtraField.TotalSize(_cdUnknownExtraFields) : 0);
        ushort value4;
        if (num > 65535)
        {
            value4 = (ushort)(flag ? zip64ExtraField.TotalSize : 0);
            _cdUnknownExtraFields = null;
        }
        else
        {
            value4 = (ushort)num;
        }
        binaryWriter.Write(33639248u);
        binaryWriter.Write((byte)_versionMadeBySpecification);
        binaryWriter.Write((byte)0);
        binaryWriter.Write((ushort)_versionToExtract);
        binaryWriter.Write((ushort)_generalPurposeBitFlag);
        binaryWriter.Write((ushort)CompressionMethod);
        binaryWriter.Write(ZipHelper.DateTimeToDosTime(_lastModified.DateTime));
        binaryWriter.Write(_crc32);
        binaryWriter.Write(value);
        binaryWriter.Write(value2);
        binaryWriter.Write((ushort)_storedEntryNameBytes.Length);
        binaryWriter.Write(value4);
        binaryWriter.Write((ushort)((_fileComment != null) ? ((ushort)_fileComment.Length) : 0));
        binaryWriter.Write((ushort)0);
        binaryWriter.Write((ushort)0);
        binaryWriter.Write(_externalFileAttr);
        binaryWriter.Write(value3);
        binaryWriter.Write(_storedEntryNameBytes);
        if (flag)
        {
            zip64ExtraField.WriteBlock(_archive.ArchiveStream);
        }
        if (_cdUnknownExtraFields != null)
        {
            ZipGenericExtraField.WriteAllBlocks(_cdUnknownExtraFields, _archive.ArchiveStream);
        }
        if (_fileComment != null)
        {
            binaryWriter.Write(_fileComment);
        }
    }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._cdUnknownExtraFields, System.IO.Compression.ZipArchiveEntry._compressedSize, System.IO.Compression.ZipArchiveEntry._crc32, System.IO.Compression.ZipArchiveEntry._externalFileAttr, System.IO.Compression.ZipArchiveEntry._fileComment, System.IO.Compression.ZipArchiveEntry._generalPurposeBitFlag, System.IO.Compression.ZipArchiveEntry._lastModified, System.IO.Compression.ZipArchiveEntry._offsetOfLocalHeader, System.IO.Compression.ZipArchiveEntry._storedEntryNameBytes, System.IO.Compression.ZipArchiveEntry._uncompressedSize, System.IO.Compression.ZipArchiveEntry._versionMadeBySpecification, System.IO.Compression.ZipArchiveEntry._versionToExtract, System.IO.Compression.ZipArchive.ArchiveStream, System.IO.Compression.ZipArchiveEntry.CompressionMethod, System.DateTimeOffset.DateTime, System.IO.Compression.ZipHelper.DateTimeToDosTime(), System.IO.Compression.ZipArchiveEntry.SizesTooLarge(), System.IO.Compression.ZipGenericExtraField.TotalSize(), System.value, System.IO.Compression.ZipArchiveEntry.VersionToExtractAtLeast(), and System.IO.Compression.ZipGenericExtraField.WriteAllBlocks().