Terraria: System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeader
WriteLocalFileHeader()
bool System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeader (bool isEmptyFile) inline private
Definition at line 812 of file ZipArchiveEntry.cs.
    {
        BinaryWriter binaryWriter = new BinaryWriter(_archive.ArchiveStream);
        Zip64ExtraField zip64ExtraField = default(Zip64ExtraField);
        bool flag = false;
        uint value;
        uint value2;
        if (isEmptyFile)
        {
            CompressionMethod = CompressionMethodValues.Stored;
            value = 0u;
            value2 = 0u;
        }
        else if (_archive.Mode == ZipArchiveMode.Create && !_archive.ArchiveStream.CanSeek && !isEmptyFile)
        {
            _generalPurposeBitFlag |= BitFlagValues.DataDescriptor;
            flag = false;
            value = 0u;
            value2 = 0u;
        }
        else
        {
            _generalPurposeBitFlag &= ~BitFlagValues.DataDescriptor;
            if (SizesTooLarge())
            {
                flag = true;
                value = uint.MaxValue;
                value2 = uint.MaxValue;
                zip64ExtraField.CompressedSize = _compressedSize;
                zip64ExtraField.UncompressedSize = _uncompressedSize;
                VersionToExtractAtLeast(ZipVersionNeededValues.Zip64);
            }
            else
            {
                flag = false;
                value = (uint)_compressedSize;
                value2 = (uint)_uncompressedSize;
            }
        }
        _offsetOfLocalHeader = binaryWriter.BaseStream.Position;
        int num = (flag ? zip64ExtraField.TotalSize : 0) + ((_lhUnknownExtraFields != null) ? ZipGenericExtraField.TotalSize(_lhUnknownExtraFields) : 0);
        ushort value3;
        if (num > 65535)
        {
            value3 = (ushort)(flag ? zip64ExtraField.TotalSize : 0);
            _lhUnknownExtraFields = null;
        }
        else
        {
            value3 = (ushort)num;
        }
        binaryWriter.Write(67324752u);
        binaryWriter.Write((ushort)_versionToExtract);
        binaryWriter.Write((ushort)_generalPurposeBitFlag);
        binaryWriter.Write((ushort)CompressionMethod);
        binaryWriter.Write(ZipHelper.DateTimeToDosTime(_lastModified.DateTime));
        binaryWriter.Write(_crc32);
        binaryWriter.Write(value);
        binaryWriter.Write(value2);
        binaryWriter.Write((ushort)_storedEntryNameBytes.Length);
        binaryWriter.Write(value3);
        binaryWriter.Write(_storedEntryNameBytes);
        if (flag)
        {
            zip64ExtraField.WriteBlock(_archive.ArchiveStream);
        }
        if (_lhUnknownExtraFields != null)
        {
            ZipGenericExtraField.WriteAllBlocks(_lhUnknownExtraFields, _archive.ArchiveStream);
        }
        return flag;
    }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._compressedSize, System.IO.Compression.ZipArchiveEntry._crc32, System.IO.Compression.ZipArchiveEntry._generalPurposeBitFlag, System.IO.Compression.ZipArchiveEntry._lastModified, System.IO.Compression.ZipArchiveEntry._lhUnknownExtraFields, System.IO.Compression.ZipArchiveEntry._offsetOfLocalHeader, System.IO.Compression.ZipArchiveEntry._storedEntryNameBytes, System.IO.Compression.ZipArchiveEntry._uncompressedSize, System.IO.Compression.ZipArchiveEntry._versionToExtract, System.IO.Compression.ZipArchive.ArchiveStream, System.IO.Stream.CanSeek, System.IO.Compression.ZipArchiveEntry.CompressionMethod, System.DateTimeOffset.DateTime, System.IO.Compression.ZipHelper.DateTimeToDosTime(), System.IO.Compression.ZipArchive.Mode, System.IO.Compression.ZipArchiveEntry.SizesTooLarge(), System.IO.Compression.ZipGenericExtraField.TotalSize(), System.value, System.IO.Compression.ZipArchiveEntry.VersionToExtractAtLeast(), and System.IO.Compression.ZipGenericExtraField.WriteAllBlocks().
Referenced by System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Dispose(), System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write(), System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Write(), System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.WriteAsync(), and System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeaderAndDataIfNeeded().