Terraria: System.IO.Compression.ZipArchiveEntry.Delete
Delete()
void System.IO.Compression.ZipArchiveEntry.Delete () inline
Definition at line 510 of file ZipArchiveEntry.cs.
    {
        if (_archive != null)
        {
            if (_currentlyOpenForWrite)
            {
                throw new IOException(System.SR.DeleteOpenEntry);
            }
            if (_archive.Mode != ZipArchiveMode.Update)
            {
                throw new NotSupportedException(System.SR.DeleteOnlyInUpdate);
            }
            _archive.ThrowIfDisposed();
            _archive.RemoveEntry(this);
            _archive = null;
            UnloadStreams();
        }
    }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._currentlyOpenForWrite, System.SR.DeleteOnlyInUpdate, System.SR.DeleteOpenEntry, System.IO.Compression.ZipArchive.Mode, System.IO.Compression.ZipArchive.RemoveEntry(), System.IO.Compression.ZipArchive.ThrowIfDisposed(), and System.IO.Compression.ZipArchiveEntry.UnloadStreams().