Terraria: System.IO.Compression.ZipArchiveEntry.OpenInWriteMode
OpenInWriteMode()
Stream System.IO.Compression.ZipArchiveEntry.OpenInWriteMode () inline private
Definition at line 722 of file ZipArchiveEntry.cs.
    {
        if (_everOpenedForWrite)
        {
            throw new IOException(System.SR.CreateModeWriteOnceAndOneEntryAtATime);
        }
        _everOpenedForWrite = true;
        CheckSumAndSizeWriteStream dataCompressor = GetDataCompressor(_archive.ArchiveStream, leaveBackingStreamOpen: true, delegate(object o, EventArgs e)
        {
            ZipArchiveEntry zipArchiveEntry = (ZipArchiveEntry)o;
            zipArchiveEntry._archive.ReleaseArchiveStream(zipArchiveEntry);
            zipArchiveEntry._outstandingWriteStream = null;
        });
        _outstandingWriteStream = new DirectToArchiveWriterStream(dataCompressor, this);
        return new WrappedStream(_outstandingWriteStream, closeBaseStream: true);
    }
References System.IO.Compression.ZipArchiveEntry.ZipArchiveEntry(), System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._everOpenedForWrite, System.IO.Compression.ZipArchiveEntry._outstandingWriteStream, System.IO.Compression.ZipArchive.ArchiveStream, System.SR.CreateModeWriteOnceAndOneEntryAtATime, and System.IO.Compression.ZipArchiveEntry.GetDataCompressor().
Referenced by System.IO.Compression.ZipArchiveEntry.Open().