Terraria: System.IO.Compression.ZipArchiveEntry.ZipArchiveEntry
ZipArchiveEntry() [1/3]
System.IO.Compression.ZipArchiveEntry.ZipArchiveEntry (ZipArchive archive, ZipCentralDirectoryFileHeader cd) inline package
Definition at line 434 of file ZipArchiveEntry.cs.
    {
        _archive = archive;
        _originallyInArchive = true;
        _diskNumberStart = cd.DiskNumberStart;
        _versionMadeByPlatform = (ZipVersionMadeByPlatform)cd.VersionMadeByCompatibility;
        _versionMadeBySpecification = (ZipVersionNeededValues)cd.VersionMadeBySpecification;
        _versionToExtract = (ZipVersionNeededValues)cd.VersionNeededToExtract;
        _generalPurposeBitFlag = (BitFlagValues)cd.GeneralPurposeBitFlag;
        CompressionMethod = (CompressionMethodValues)cd.CompressionMethod;
        _lastModified = new DateTimeOffset(ZipHelper.DosTimeToDateTime(cd.LastModified));
        _compressedSize = cd.CompressedSize;
        _uncompressedSize = cd.UncompressedSize;
        _externalFileAttr = cd.ExternalFileAttributes;
        _offsetOfLocalHeader = cd.RelativeOffsetOfLocalHeader;
        _storedOffsetOfCompressedData = null;
        _crc32 = cd.Crc32;
        _compressedBytes = null;
        _storedUncompressedData = null;
        _currentlyOpenForWrite = false;
        _everOpenedForWrite = false;
        _outstandingWriteStream = null;
        FullName = DecodeEntryName(cd.Filename);
        _lhUnknownExtraFields = null;
        _cdUnknownExtraFields = cd.ExtraFields;
        _fileComment = cd.FileComment;
        _compressionLevel = null;
    }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._cdUnknownExtraFields, System.IO.Compression.ZipArchiveEntry._compressedBytes, System.IO.Compression.ZipArchiveEntry._compressedSize, System.IO.Compression.ZipArchiveEntry._compressionLevel, System.IO.Compression.ZipArchiveEntry._crc32, System.IO.Compression.ZipArchiveEntry._currentlyOpenForWrite, System.IO.Compression.ZipArchiveEntry._diskNumberStart, System.IO.Compression.ZipArchiveEntry._everOpenedForWrite, System.IO.Compression.ZipArchiveEntry._externalFileAttr, System.IO.Compression.ZipArchiveEntry._fileComment, System.IO.Compression.ZipArchiveEntry._generalPurposeBitFlag, System.IO.Compression.ZipArchiveEntry._lastModified, System.IO.Compression.ZipArchiveEntry._lhUnknownExtraFields, System.IO.Compression.ZipArchiveEntry._offsetOfLocalHeader, System.IO.Compression.ZipArchiveEntry._originallyInArchive, System.IO.Compression.ZipArchiveEntry._outstandingWriteStream, System.IO.Compression.ZipArchiveEntry._storedOffsetOfCompressedData, System.IO.Compression.ZipArchiveEntry._storedUncompressedData, System.IO.Compression.ZipArchiveEntry._uncompressedSize, System.IO.Compression.ZipArchiveEntry._versionMadeByPlatform, System.IO.Compression.ZipArchiveEntry._versionMadeBySpecification, System.IO.Compression.ZipArchiveEntry._versionToExtract, System.IO.Compression.ZipArchiveEntry.CompressionMethod, System.IO.Compression.ZipArchiveEntry.DecodeEntryName(), System.IO.Compression.ZipHelper.DosTimeToDateTime(), and System.IO.Compression.ZipArchiveEntry.FullName.
Referenced by System.IO.Compression.ZipArchiveEntry.OpenInWriteMode().