Terraria: System.IO.Compression.ZipArchiveEntry.WriteCrcAndSizesInLocalHeader
WriteCrcAndSizesInLocalHeader()
void System.IO.Compression.ZipArchiveEntry.WriteCrcAndSizesInLocalHeader (bool zip64HeaderUsed) inline private
Definition at line 920 of file ZipArchiveEntry.cs.
    {
        long position = _archive.ArchiveStream.Position;
        BinaryWriter binaryWriter = new BinaryWriter(_archive.ArchiveStream);
        bool flag = SizesTooLarge();
        bool flag2 = flag && !zip64HeaderUsed;
        uint value = (uint)(flag ? uint.MaxValue : _compressedSize);
        uint value2 = (uint)(flag ? uint.MaxValue : _uncompressedSize);
        if (flag2)
        {
            VersionToExtractAtLeast(ZipVersionNeededValues.Zip64);
            _generalPurposeBitFlag |= BitFlagValues.DataDescriptor;
            _archive.ArchiveStream.Seek(_offsetOfLocalHeader + 4, SeekOrigin.Begin);
            binaryWriter.Write((ushort)_versionToExtract);
            binaryWriter.Write((ushort)_generalPurposeBitFlag);
        }
        _archive.ArchiveStream.Seek(_offsetOfLocalHeader + 14, SeekOrigin.Begin);
        if (!flag2)
        {
            binaryWriter.Write(_crc32);
            binaryWriter.Write(value);
            binaryWriter.Write(value2);
        }
        else
        {
            binaryWriter.Write(0u);
            binaryWriter.Write(0u);
            binaryWriter.Write(0u);
        }
        if (zip64HeaderUsed)
        {
            _archive.ArchiveStream.Seek(_offsetOfLocalHeader + 30 + _storedEntryNameBytes.Length + 4, SeekOrigin.Begin);
            binaryWriter.Write(_uncompressedSize);
            binaryWriter.Write(_compressedSize);
        }
        _archive.ArchiveStream.Seek(position, SeekOrigin.Begin);
        if (flag2)
        {
            binaryWriter.Write(_crc32);
            binaryWriter.Write(_compressedSize);
            binaryWriter.Write(_uncompressedSize);
        }
    }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._compressedSize, System.IO.Compression.ZipArchiveEntry._crc32, System.IO.Compression.ZipArchiveEntry._generalPurposeBitFlag, System.IO.Compression.ZipArchiveEntry._offsetOfLocalHeader, System.IO.Compression.ZipArchiveEntry._storedEntryNameBytes, System.IO.Compression.ZipArchiveEntry._uncompressedSize, System.IO.Compression.ZipArchiveEntry._versionToExtract, System.IO.Compression.ZipArchive.ArchiveStream, System.IO.Stream.Position, System.IO.Stream.Seek(), System.IO.Compression.ZipArchiveEntry.SizesTooLarge(), System.value, and System.IO.Compression.ZipArchiveEntry.VersionToExtractAtLeast().
Referenced by System.IO.Compression.ZipArchiveEntry.DirectToArchiveWriterStream.Dispose().