Terraria: System.IO.Compression.ZipArchiveEntry.LoadLocalHeaderExtraFieldAndCompressedBytesIfNeeded
LoadLocalHeaderExtraFieldAndCompressedBytesIfNeeded()
bool System.IO.Compression.ZipArchiveEntry.LoadLocalHeaderExtraFieldAndCompressedBytesIfNeeded () inline package
Definition at line 643 of file ZipArchiveEntry.cs.
    {
        if (_originallyInArchive)
        {
            _archive.ArchiveStream.Seek(_offsetOfLocalHeader, SeekOrigin.Begin);
            _lhUnknownExtraFields = ZipLocalFileHeader.GetExtraFields(_archive.ArchiveReader);
        }
        if (!_everOpenedForWrite && _originallyInArchive)
        {
            int maxLength = Array.MaxLength;
            _compressedBytes = new byte[_compressedSize / maxLength + 1][];
            for (int i = 0; i < _compressedBytes.Length - 1; i++)
            {
                _compressedBytes[i] = new byte[maxLength];
            }
            _compressedBytes[_compressedBytes.Length - 1] = new byte[_compressedSize % maxLength];
            _archive.ArchiveStream.Seek(OffsetOfCompressedData, SeekOrigin.Begin);
            for (int j = 0; j < _compressedBytes.Length - 1; j++)
            {
                ZipHelper.ReadBytes(_archive.ArchiveStream, _compressedBytes[j], maxLength);
            }
            ZipHelper.ReadBytes(_archive.ArchiveStream, _compressedBytes[_compressedBytes.Length - 1], (int)(_compressedSize % maxLength));
        }
        return true;
    }
References System.IO.Compression.ZipArchiveEntry._archive, System.IO.Compression.ZipArchiveEntry._compressedBytes, System.IO.Compression.ZipArchiveEntry._compressedSize, System.IO.Compression.ZipArchiveEntry._everOpenedForWrite, System.IO.Compression.ZipArchiveEntry._lhUnknownExtraFields, System.IO.Compression.ZipArchiveEntry._offsetOfLocalHeader, System.IO.Compression.ZipArchiveEntry._originallyInArchive, System.IO.Compression.ZipArchive.ArchiveReader, System.IO.Compression.ZipArchive.ArchiveStream, System.IO.Compression.ZipLocalFileHeader.GetExtraFields(), System.Array.MaxLength, System.IO.Compression.ZipArchiveEntry.OffsetOfCompressedData, System.IO.Compression.ZipHelper.ReadBytes(), and System.IO.Stream.Seek().