Terraria: System.IO.Compression.ZipArchiveEntry.VersionToExtractAtLeast
VersionToExtractAtLeast()
void System.IO.Compression.ZipArchiveEntry.VersionToExtractAtLeast (ZipVersionNeededValues value) inline private
Definition at line 999 of file ZipArchiveEntry.cs.
    {
        if ((int)_versionToExtract < (int)value)
        {
            _versionToExtract = value;
        }
        if ((int)_versionMadeBySpecification < (int)value)
        {
            _versionMadeBySpecification = value;
        }
    }
References System.IO.Compression.ZipArchiveEntry._versionMadeBySpecification, System.IO.Compression.ZipArchiveEntry._versionToExtract, and System.value.
Referenced by System.IO.Compression.ZipArchiveEntry.WriteCentralDirectoryFileHeader(), System.IO.Compression.ZipArchiveEntry.WriteCrcAndSizesInLocalHeader(), and System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeader().