Terraria: System.IO.Compression.ZipArchiveEntry.OpenInUpdateMode
OpenInUpdateMode()
Stream System.IO.Compression.ZipArchiveEntry.OpenInUpdateMode () inline private
Definition at line 739 of file ZipArchiveEntry.cs.
    {
        if (_currentlyOpenForWrite)
        {
            throw new IOException(System.SR.UpdateModeOneStream);
        }
        ThrowIfNotOpenable(needToUncompress: true, needToLoadIntoMemory: true);
        _everOpenedForWrite = true;
        _currentlyOpenForWrite = true;
        UncompressedData.Seek(0L, SeekOrigin.Begin);
        return new WrappedStream(UncompressedData, this, delegate(ZipArchiveEntry thisRef)
        {
            thisRef._currentlyOpenForWrite = false;
        });
    }
References System.IO.Compression.ZipArchiveEntry._currentlyOpenForWrite, System.IO.Compression.ZipArchiveEntry._everOpenedForWrite, System.L, System.IO.MemoryStream.Seek(), System.IO.Compression.ZipArchiveEntry.ThrowIfNotOpenable(), System.IO.Compression.ZipArchiveEntry.UncompressedData, and System.SR.UpdateModeOneStream.
Referenced by System.IO.Compression.ZipArchiveEntry.Open().