Terraria: System.IO.StreamReader.Peek
Peek()
override int System.IO.StreamReader.Peek () inline virtual
Reimplemented from System.IO.TextReader.
Reimplemented in System.IO.StreamReader.NullStreamReader.
Definition at line 303 of file StreamReader.cs.
    {
        ThrowIfDisposed();
        CheckAsyncTaskInProgress();
        if (_charPos == _charLen && (_isBlocked || ReadBuffer() == 0))
        {
            return -1;
        }
        return _charBuffer[_charPos];
    }
References System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.IO.StreamReader._isBlocked, System.IO.StreamReader.CheckAsyncTaskInProgress(), System.IO.StreamReader.ReadBuffer(), and System.IO.StreamReader.ThrowIfDisposed().