Terraria: System.IO.StreamReader.Close
Close()
override void System.IO.StreamReader.Close () inline virtual inherited
Reimplemented from System.IO.TextReader.
Definition at line 259 of file StreamReader.cs.
    {
        Dispose(disposing: true);
    }
References System.IO.TextReader.Dispose().
Referenced by System.Diagnostics.Process.Close(), and System.ComponentModel.LicFileLicenseProvider.GetLicense().