Terraria: System.IO.StreamReader.ReadBufferAsync
ReadBufferAsync()
async ValueTask< int > System.IO.StreamReader.ReadBufferAsync (CancellationToken cancellationToken) inline private inherited
Definition at line 994 of file StreamReader.cs.
    {
        _charLen = 0;
        _charPos = 0;
        byte[] tmpByteBuffer = _byteBuffer;
        Stream tmpStream = _stream;
        if (!_checkPreamble)
        {
            _byteLen = 0;
        }
        do
        {
            if (_checkPreamble)
            {
                int bytePos = _bytePos;
                int num = await tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer, bytePos, tmpByteBuffer.Length - bytePos), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                if (num == 0)
                {
                    if (_byteLen > 0)
                    {
                        _charLen += _decoder.GetChars(tmpByteBuffer, 0, _byteLen, _charBuffer, _charLen);
                        _bytePos = 0;
                        _byteLen = 0;
                    }
                    return _charLen;
                }
                _byteLen += num;
            }
            else
            {
                _byteLen = await tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                if (_byteLen == 0)
                {
                    return _charLen;
                }
            }
            _isBlocked = _byteLen < tmpByteBuffer.Length;
            if (!IsPreamble())
            {
                if (_detectEncoding && _byteLen >= 2)
                {
                    DetectEncoding();
                }
                _charLen += _decoder.GetChars(tmpByteBuffer, 0, _byteLen, _charBuffer, _charLen);
            }
        }
        while (_charLen == 0);
        return _charLen;
    }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._bytePos, System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._decoder, System.IO.StreamReader._detectEncoding, System.IO.StreamReader._isBlocked, System.IO.StreamReader._stream, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.StreamReader.DetectEncoding(), System.Text.Decoder.GetChars(), System.IO.StreamReader.IsPreamble(), and System.IO.Stream.ReadAsync().
Referenced by System.IO.StreamReader.ReadAsyncInternal(), System.IO.StreamReader.ReadLineAsyncInternal(), and System.IO.StreamReader.ReadToEndAsyncInternal().