Terraria: System.IO.StreamReader.CheckAsyncTaskInProgress
CheckAsyncTaskInProgress()
void System.IO.StreamReader.CheckAsyncTaskInProgress () inline private inherited
Definition at line 102 of file StreamReader.cs.
    {
        if (!_asyncReadTask.IsCompleted)
        {
            ThrowAsyncIOInProgress();
        }
    }
References System.IO.StreamReader._asyncReadTask, System.Threading.Tasks.Task< TResult >.IsCompleted, and System.IO.StreamReader.ThrowAsyncIOInProgress().
Referenced by System.IO.StreamReader.DiscardBufferedData(), System.IO.StreamReader.Peek(), System.IO.StreamReader.Read(), System.IO.StreamReader.ReadAsync(), System.IO.StreamReader.ReadAsync(), System.IO.StreamReader.ReadBlock(), System.IO.StreamReader.ReadBlockAsync(), System.IO.StreamReader.ReadBlockAsync(), System.IO.StreamReader.ReadLine(), System.IO.StreamReader.ReadLineAsync(), System.IO.StreamReader.ReadSpan(), System.IO.StreamReader.ReadToEnd(), and System.IO.StreamReader.ReadToEndAsync().