Terraria: System.IO.StreamReader.IsPreamble
IsPreamble()
bool System.IO.StreamReader.IsPreamble () inline private inherited
Definition at line 504 of file StreamReader.cs.
    {
        if (!_checkPreamble)
        {
            return _checkPreamble;
        }
        ReadOnlySpan<byte> preamble = _encoding.Preamble;
        int num = ((_byteLen >= preamble.Length) ? (preamble.Length - _bytePos) : (_byteLen - _bytePos));
        int num2 = 0;
        while (num2 < num)
        {
            if (_byteBuffer[_bytePos] != preamble[_bytePos])
            {
                _bytePos = 0;
                _checkPreamble = false;
                break;
            }
            num2++;
            _bytePos++;
        }
        if (_checkPreamble && _bytePos == preamble.Length)
        {
            CompressBuffer(preamble.Length);
            _bytePos = 0;
            _checkPreamble = false;
            _detectEncoding = false;
        }
        return _checkPreamble;
    }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._bytePos, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._detectEncoding, System.IO.StreamReader._encoding, System.IO.StreamReader.CompressBuffer(), System.ReadOnlySpan< T >.Length, and System.Text.Encoding.Preamble.
Referenced by System.IO.StreamReader.ReadAsyncInternal(), System.IO.StreamReader.ReadBuffer(), System.IO.StreamReader.ReadBuffer(), and System.IO.StreamReader.ReadBufferAsync().