Terraria: System.IO.StreamReader.ThrowIfDisposed
ThrowIfDisposed()
void System.IO.StreamReader.ThrowIfDisposed () inline private inherited
Definition at line 1044 of file StreamReader.cs.
    {
        if (_disposed)
        {
            ThrowObjectDisposedException();
        }
        void ThrowObjectDisposedException()
        {
            throw new ObjectDisposedException(GetType().Name, SR.ObjectDisposed_ReaderClosed);
        }
    }
References System.IO.StreamReader._disposed, System.Name, and System.SR.ObjectDisposed_ReaderClosed.
Referenced by System.IO.StreamReader.Peek(), System.IO.StreamReader.Read(), System.IO.StreamReader.ReadAsync(), System.IO.StreamReader.ReadAsync(), System.IO.StreamReader.ReadBlock(), System.IO.StreamReader.ReadBlockAsync(), System.IO.StreamReader.ReadBlockAsync(), System.IO.StreamReader.ReadLine(), System.IO.StreamReader.ReadLineAsync(), System.IO.StreamReader.ReadSpan(), System.IO.StreamReader.ReadToEnd(), and System.IO.StreamReader.ReadToEndAsync().