Terraria: System.IO.StreamReader.ReadBuffer
ReadBuffer() [1/2]
virtual int System.IO.StreamReader.ReadBuffer () inline package virtual
Reimplemented in System.IO.StreamReader.NullStreamReader.
Definition at line 534 of file StreamReader.cs.
    {
        _charLen = 0;
        _charPos = 0;
        if (!_checkPreamble)
        {
            _byteLen = 0;
        }
        do
        {
            if (_checkPreamble)
            {
                int num = _stream.Read(_byteBuffer, _bytePos, _byteBuffer.Length - _bytePos);
                if (num == 0)
                {
                    if (_byteLen > 0)
                    {
                        _charLen += _decoder.GetChars(_byteBuffer, 0, _byteLen, _charBuffer, _charLen);
                        _bytePos = (_byteLen = 0);
                    }
                    return _charLen;
                }
                _byteLen += num;
            }
            else
            {
                _byteLen = _stream.Read(_byteBuffer, 0, _byteBuffer.Length);
                if (_byteLen == 0)
                {
                    return _charLen;
                }
            }
            _isBlocked = _byteLen < _byteBuffer.Length;
            if (!IsPreamble())
            {
                if (_detectEncoding && _byteLen >= 2)
                {
                    DetectEncoding();
                }
                _charLen += _decoder.GetChars(_byteBuffer, 0, _byteLen, _charBuffer, _charLen);
            }
        }
        while (_charLen == 0);
        return _charLen;
    }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._bytePos, System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._decoder, System.IO.StreamReader._detectEncoding, System.IO.StreamReader._isBlocked, System.IO.StreamReader._stream, System.IO.StreamReader.DetectEncoding(), System.Text.Decoder.GetChars(), System.IO.StreamReader.IsPreamble(), and System.IO.Stream.Read().
Referenced by System.IO.StreamReader.Peek(), System.IO.StreamReader.Read(), System.IO.StreamReader.ReadLine(), System.IO.StreamReader.ReadSpan(), and System.IO.StreamReader.ReadToEnd().