Terraria: Microsoft.Xna.Framework.Graphics.Texture.GetAndValidateRect
GetAndValidateRect()
static unsafe void Microsoft.Xna.Framework.Graphics.Texture.GetAndValidateRect (_D3DSURFACE_DESC * __unnamed000, uint * pdwLockWidth, uint * pdwLockHeight, Rectangle? rect) inline static package inherited
Definition at line 221 of file Texture.cs.
    {
        if (__unnamed000 == null || pdwLockHeight == null || pdwLockWidth == null)
        {
            return;
        }
        *pdwLockWidth = *(uint*)((byte*)__unnamed000 + 24);
        *pdwLockHeight = *(uint*)((byte*)__unnamed000 + 28);
        if (!rect.HasValue)
        {
            return;
        }
        if (rect.Value.X >= 0 && rect.Value.Width > 0 && rect.Value.Y >= 0 && rect.Value.Height > 0)
        {
            Rectangle value = rect.Value;
            Rectangle value2 = rect.Value;
            if ((uint)(value.Left + value2.Width) <= (uint)(*(int*)((byte*)__unnamed000 + 24)))
            {
                Rectangle value3 = rect.Value;
                Rectangle value4 = rect.Value;
                if ((uint)(value3.Top + value4.Height) <= (uint)(*(int*)((byte*)__unnamed000 + 28)))
                {
                    *pdwLockWidth = (uint)rect.Value.Width;
                    *pdwLockHeight = (uint)rect.Value.Height;
                    return;
                }
            }
            throw new ArgumentException(FrameworkResources.InvalidRectangle, "rect");
        }
        throw new ArgumentException(FrameworkResources.InvalidRectangle, "rect");
    }
References Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.FrameworkResources.InvalidRectangle, System.value, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Microsoft.Xna.Framework.Graphics.TextureCube.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyData< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >().