Terraria: Microsoft.Xna.Framework.Graphics.Texture.InitializeDescription
InitializeDescription() [1/2]
unsafe void Microsoft.Xna.Framework.Graphics.Texture.InitializeDescription (SurfaceFormat format) inline protected inherited
Definition at line 39 of file Texture.cs.
    {
        _format = format;
        IDirect3DBaseTexture9* comPtr = GetComPtr();
        _levelCount = (int)((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint>)(int)(*(uint*)(*(int*)comPtr + 52)))((nint)comPtr);
        int num = CreateStateWrapper();
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
    }
References Microsoft.Xna.Framework.Graphics.Texture._format, Microsoft.Xna.Framework.Graphics.Texture._levelCount, Microsoft.Xna.Framework.Graphics.Texture.CreateStateWrapper(), System.format, Microsoft.Xna.Framework.Graphics.Texture.GetComPtr(), and Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult().