Terraria: Microsoft.Xna.Framework.Graphics.Texture.GetExpectedByteSizeFromFormat
GetExpectedByteSizeFromFormat()
static byte Microsoft.Xna.Framework.Graphics.Texture.GetExpectedByteSizeFromFormat (_D3DFORMAT format) inline static package inherited
Definition at line 72 of file Texture.cs.
    {
        if (format <= (_D3DFORMAT)827606349)
        {
            if (format == (_D3DFORMAT)827606349)
            {
                return 4;
            }
            switch (format - 20)
            {
            case (_D3DFORMAT)0:
                return 3;
            case (_D3DFORMAT)1:
                return 4;
            case (_D3DFORMAT)2:
                return 4;
            case (_D3DFORMAT)15:
                return 4;
            case (_D3DFORMAT)12:
                return 4;
            case (_D3DFORMAT)13:
                return 4;
            case (_D3DFORMAT)11:
                return 4;
            case (_D3DFORMAT)14:
                return 4;
            case (_D3DFORMAT)16:
                return 8;
            case (_D3DFORMAT)3:
                return 2;
            case (_D3DFORMAT)5:
                return 2;
            case (_D3DFORMAT)4:
                return 2;
            case (_D3DFORMAT)6:
                return 2;
            case (_D3DFORMAT)10:
                return 2;
            case (_D3DFORMAT)9:
                return 2;
            case (_D3DFORMAT)8:
                return 1;
            case (_D3DFORMAT)7:
                return 1;
            case (_D3DFORMAT)40:
                return 2;
            case (_D3DFORMAT)43:
                return 4;
            case (_D3DFORMAT)44:
                return 4;
            case (_D3DFORMAT)90:
                return 8;
            case (_D3DFORMAT)94:
                return 4;
            case (_D3DFORMAT)95:
                return 8;
            case (_D3DFORMAT)96:
                return 16;
            case (_D3DFORMAT)91:
                return 2;
            case (_D3DFORMAT)92:
                return 4;
            case (_D3DFORMAT)93:
                return 8;
            case (_D3DFORMAT)30:
                return 1;
            case (_D3DFORMAT)61:
                return 2;
            case (_D3DFORMAT)32:
                return 1;
            case (_D3DFORMAT)31:
                return 2;
            case (_D3DFORMAT)21:
                return 1;
            case (_D3DFORMAT)20:
                return 2;
            case (_D3DFORMAT)41:
                return 2;
            case (_D3DFORMAT)42:
                return 4;
            case (_D3DFORMAT)47:
                return 4;
            case (_D3DFORMAT)97:
                return 2;
            case (_D3DFORMAT)55:
                return 4;
            case (_D3DFORMAT)63:
                return 4;
            case (_D3DFORMAT)59:
                return 4;
            case (_D3DFORMAT)57:
                return 4;
            case (_D3DFORMAT)51:
                return 4;
            case (_D3DFORMAT)60:
                return 2;
            case (_D3DFORMAT)53:
                return 2;
            }
        }
        else
        {
            switch (format)
            {
            case (_D3DFORMAT)844388420:
                return 1;
            case (_D3DFORMAT)827611204:
                return 1;
            case (_D3DFORMAT)844715353:
                return 2;
            case (_D3DFORMAT)861165636:
                return 1;
            case (_D3DFORMAT)877942852:
                return 1;
            case (_D3DFORMAT)1111970375:
                return 2;
            case (_D3DFORMAT)894720068:
                return 1;
            case (_D3DFORMAT)1195525970:
                return 2;
            case (_D3DFORMAT)1498831189:
                return 2;
            }
        }
        throw new InvalidOperationException();
    }
References System.format.
Referenced by Microsoft.Xna.Framework.Graphics.RenderTargetHelper.RenderTargetHelper(), Microsoft.Xna.Framework.Graphics.Texture.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyOrRestoreData(), Microsoft.Xna.Framework.Graphics.Texture3D.CopyOrRestoreData(), Microsoft.Xna.Framework.Graphics.TextureCube.CopyOrRestoreData(), Microsoft.Xna.Framework.Graphics.Texture.GetAndValidateSizes< T >(), and Microsoft.Xna.Framework.Graphics.Texture3D.GetAndValidateSizes< T >().