Terraria: Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar.ValidateAndCollectNecessaryInfo
ValidateAndCollectNecessaryInfo()
bool Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar.ValidateAndCollectNecessaryInfo (ref BigProgressBarInfo info) inline
Implements Terraria.GameContent.UI.BigProgressBar.IBigProgressBar.
Definition at line 21 of file PirateShipBigProgressBar.cs.
    {
        if (info.npcIndexToAimAt < 0 || info.npcIndexToAimAt > 200)
        {
            return false;
        }
        NPC nPC = Main.npc[info.npcIndexToAimAt];
        if (!nPC.active || nPC.type != 491)
        {
            if (!TryFindingAnotherPirateShipPiece(ref info))
            {
                return false;
            }
            nPC = Main.npc[info.npcIndexToAimAt];
        }
        int num = 0;
        _referenceDummy.SetDefaults(492, nPC.GetMatchingSpawnParams());
        num += _referenceDummy.lifeMax * 4;
        float num2 = 0f;
        for (int i = 0; i < 4; i++)
        {
            int num3 = (int)nPC.ai[i];
            if (Main.npc.IndexInRange(num3))
            {
                NPC nPC2 = Main.npc[num3];
                if (nPC2.active && nPC2.type == 492)
                {
                    num2 += (float)nPC2.life;
                }
            }
        }
        _cache.SetLife(num2, num);
        return true;
    }
References Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar._cache, Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar._referenceDummy, Terraria.Main.npc, Terraria.NPC.SetDefaults(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.SetLife(), and Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar.TryFindingAnotherPirateShipPiece().