Terraria: Microsoft.Xna.Framework.Graphics.Texture.CreateStateWrapper
CreateStateWrapper()
unsafe int Microsoft.Xna.Framework.Graphics.Texture.CreateStateWrapper () inline protected inherited
Definition at line 51 of file Texture.cs.
    {
        ProfileCapabilities profileCapabilities = _parent._profileCapabilities;
        bool flag = profileCapabilities.ValidVertexTextureFormats.Contains(_format);
        bool flag2 = profileCapabilities.InvalidFilterFormats.Contains(_format);
        StateTrackerTexture* ptr = (StateTrackerTexture*)_003CModule_003E.@new(28u, (nothrow_t*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref _003CModule_003E.std_002Enothrow));
        StateTrackerTexture* ptr2;
        try
        {
            ptr2 = ((ptr == null) ? null : _003CModule_003E.Microsoft_002EXna_002EFramework_002EGraphics_002EStateTrackerTexture_002E_007Bctor_007D(ptr, GetComPtr(), (uint)_format, flag, flag2, MustClamp));
        }
        catch
        {
            //try-fault
            _003CModule_003E.delete(ptr, (nothrow_t*)System.Runtime.CompilerServices.Unsafe.AsPointer(ref _003CModule_003E.std_002Enothrow));
            throw;
        }
        pStateTracker = ptr2;
        return (ptr2 == null) ? (-2147024882) : 0;
    }
References Microsoft.Xna.Framework.Graphics.Texture._format, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, System.Collections.Generic.List< T >.Contains(), Microsoft.Xna.Framework.Graphics.Texture.GetComPtr(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.InvalidFilterFormats, Microsoft.Xna.Framework.Graphics.Texture.MustClamp, Microsoft.Xna.Framework.Graphics.Texture.pStateTracker, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidVertexTextureFormats.
Referenced by Microsoft.Xna.Framework.Graphics.Texture.InitializeDescription(), Microsoft.Xna.Framework.Graphics.Texture2D.RecreateAndPopulateObject(), Microsoft.Xna.Framework.Graphics.Texture3D.RecreateAndPopulateObject(), and Microsoft.Xna.Framework.Graphics.TextureCube.RecreateAndPopulateObject().