Terraria: Microsoft.Xna.Framework.Graphics.Texture.ValidateTotalSize
ValidateTotalSize() [1/2]
static unsafe void Microsoft.Xna.Framework.Graphics.Texture.ValidateTotalSize (_D3DSURFACE_DESC * __unnamed000, uint dwLockWidth, uint dwLockHeight, uint dwFormatSize, uint dwElementSize, uint elementCount) inline static package inherited
Definition at line 253 of file Texture.cs.
    {
        int num = *(int*)__unnamed000;
        _D3DFORMAT d3DFORMAT = (_D3DFORMAT)num;
        int num2 = ((d3DFORMAT == (_D3DFORMAT)827611204 || d3DFORMAT == (_D3DFORMAT)844388420 || d3DFORMAT == (_D3DFORMAT)861165636 || d3DFORMAT == (_D3DFORMAT)877942852 || d3DFORMAT == (_D3DFORMAT)894720068) ? 1 : 0);
        if ((byte)num2 != 0)
        {
            dwLockWidth = dwLockWidth + 3 >> 2;
            dwLockHeight = dwLockHeight + 3 >> 2;
            dwFormatSize = ((num == 827611204) ? 8u : 16u);
        }
        uint num3 = dwLockWidth * dwLockHeight * dwFormatSize;
        if (dwElementSize * elementCount != num3)
        {
            throw new ArgumentException(FrameworkResources.InvalidTotalSize);
        }
    }
References Microsoft.Xna.Framework.FrameworkResources.InvalidTotalSize.
Referenced by Microsoft.Xna.Framework.Graphics.TextureCube.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyData< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >().