Terraria: System.Linq.Parallel.OrderPreservingSpoolingTask.Spool
Spool()
static void System.Linq.Parallel.OrderPreservingSpoolingTask< TInputOutput, TKey >.Spool (QueryTaskGroupState groupState, PartitionedStream< TInputOutput, TKey > partitions, Shared< TInputOutput[]> results, TaskScheduler taskScheduler) inline static package
Definition at line 18 of file OrderPreservingSpoolingTask.cs.
    {
        int maxToRunInParallel = partitions.PartitionCount - 1;
        SortHelper<TInputOutput, TKey>[] sortHelpers = SortHelper<TInputOutput, TKey>.GenerateSortHelpers(partitions, groupState);
        Task task = new Task(delegate
        {
            for (int j = 0; j < maxToRunInParallel; j++)
            {
                QueryTask queryTask = new OrderPreservingSpoolingTask<TInputOutput, TKey>(j, groupState, results, sortHelpers[j]);
                queryTask.RunAsynchronously(taskScheduler);
            }
            QueryTask queryTask2 = new OrderPreservingSpoolingTask<TInputOutput, TKey>(maxToRunInParallel, groupState, results, sortHelpers[maxToRunInParallel]);
            queryTask2.RunSynchronously(taskScheduler);
        });
        groupState.QueryBegin(task);
        task.RunSynchronously(taskScheduler);
        for (int i = 0; i < sortHelpers.Length; i++)
        {
            sortHelpers[i].Dispose();
        }
        groupState.QueryEnd(userInitiatedDispose: false);
    }
References System.Linq.Parallel.SortHelper< TInputOutput, TKey >.Dispose(), System.Linq.Parallel.SortHelper< TInputOutput, TKey >.GenerateSortHelpers(), System.Linq.Parallel.QueryTaskGroupState.QueryBegin(), System.Linq.Parallel.QueryTaskGroupState.QueryEnd(), System.Linq.Parallel.QueryTask.RunAsynchronously(), System.Linq.Parallel.QueryTask.RunSynchronously(), and System.task.