Terraria: System.Net.HttpWebRequest.SendRequest
SendRequest()
async Task< WebResponse > System.Net.HttpWebRequest.SendRequest (bool async) inline private
Definition at line 954 of file HttpWebRequest.cs.
    {
        if (RequestSubmitted)
        {
            throw new InvalidOperationException(System.SR.net_reqsubmitted);
        }
        HttpRequestMessage httpRequestMessage = new HttpRequestMessage(new HttpMethod(_originVerb), _requestUri);
        bool disposeRequired = false;
        HttpClient client = null;
        try
        {
            client = GetCachedOrCreateHttpClient(async, out disposeRequired);
            if (_requestStream != null)
            {
                ArraySegment<byte> buffer = _requestStream.GetBuffer();
                httpRequestMessage.Content = new ByteArrayContent(buffer.Array, buffer.Offset, buffer.Count);
            }
            if (_hostUri != null)
            {
                httpRequestMessage.Headers.Host = Host;
            }
            foreach (string item in _webHeaderCollection)
            {
                if (IsWellKnownContentHeader(item))
                {
                    if (httpRequestMessage.Content == null)
                    {
                        httpRequestMessage.Content = new ByteArrayContent(Array.Empty<byte>());
                    }
                    httpRequestMessage.Content.Headers.TryAddWithoutValidation(item, _webHeaderCollection[item]);
                }
                else
                {
                    httpRequestMessage.Headers.TryAddWithoutValidation(item, _webHeaderCollection[item]);
                }
            }
            httpRequestMessage.Headers.TransferEncodingChunked = SendChunked;
            if (KeepAlive)
            {
                httpRequestMessage.Headers.Connection.Add("Keep-Alive");
            }
            else
            {
                httpRequestMessage.Headers.ConnectionClose = true;
            }
            httpRequestMessage.Version = ProtocolVersion;
            _sendRequestTask = (Task<HttpResponseMessage>)(async ? ((Task)client.SendAsync(httpRequestMessage, (!_allowReadStreamBuffering) ? HttpCompletionOption.ResponseHeadersRead : HttpCompletionOption.ResponseContentRead, _sendRequestCts.Token)) : ((Task)Task.FromResult(client.Send(httpRequestMessage, (!_allowReadStreamBuffering) ? HttpCompletionOption.ResponseHeadersRead : HttpCompletionOption.ResponseContentRead, _sendRequestCts.Token))));
            HttpWebResponse httpWebResponse = new HttpWebResponse(await _sendRequestTask.ConfigureAwait(continueOnCapturedContext: false), _requestUri, _cookieContainer);
            int num = (AllowAutoRedirect ? 299 : 399);
            if ((int)httpWebResponse.StatusCode > num || httpWebResponse.StatusCode < HttpStatusCode.OK)
            {
                throw new WebException(System.SR.Format(System.SR.net_servererror, (int)httpWebResponse.StatusCode, httpWebResponse.StatusDescription), null, WebExceptionStatus.ProtocolError, httpWebResponse);
            }
            return httpWebResponse;
        }
        finally
        {
            if (disposeRequired)
            {
                client?.Dispose();
            }
        }
    }
References System.Net.HttpWebRequest._allowReadStreamBuffering, System.Net.HttpWebRequest._cookieContainer, System.Net.HttpWebRequest._hostUri, System.Net.HttpWebRequest._originVerb, System.Net.HttpWebRequest._requestStream, System.Net.HttpWebRequest._requestUri, System.Net.HttpWebRequest._sendRequestCts, System.Net.HttpWebRequest._sendRequestTask, System.Net.HttpWebRequest._webHeaderCollection, System.Net.HttpWebRequest.AllowAutoRedirect, System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Net.RequestStream.GetBuffer(), System.Net.HttpWebRequest.GetCachedOrCreateHttpClient(), System.Net.HttpWebRequest.Host, System.Net.HttpWebRequest.IsWellKnownContentHeader(), System.item, System.Net.HttpWebRequest.KeepAlive, System.SR.net_reqsubmitted, System.SR.net_servererror, System.Net.HttpWebRequest.ProtocolVersion, System.Net.HttpWebRequest.RequestSubmitted, System.Net.HttpWebRequest.SendChunked, and System.Threading.CancellationTokenSource.Token.
Referenced by System.Net.HttpWebRequest.BeginGetResponse(), and System.Net.HttpWebRequest.GetResponse().