Terraria: System.Net.HttpWebRequest.EndGetResponse
EndGetResponse()
override WebResponse System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 1031 of file HttpWebRequest.cs.
    {
        CheckAbort();
        if (asyncResult == null || !(asyncResult is Task<WebResponse>))
        {
            throw new ArgumentException(System.SR.net_io_invalidasyncresult, "asyncResult");
        }
        if (Interlocked.Exchange(ref _endGetResponseCalled, 1) != 0)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_io_invalidendcall, "EndGetResponse"));
        }
        try
        {
            return ((Task<WebResponse>)asyncResult).GetAwaiter().GetResult();
        }
        catch (Exception exception)
        {
            throw WebException.CreateCompatibleException(exception);
        }
    }
References System.Net.HttpWebRequest._endGetResponseCalled, System.asyncResult, System.Net.HttpWebRequest.CheckAbort(), System.Net.WebException.CreateCompatibleException(), System.Runtime.Serialization.Dictionary, System.exception, System.Threading.Interlocked.Exchange(), System.SR.Format(), System.SR.net_io_invalidasyncresult, and System.SR.net_io_invalidendcall.