Terraria: System.Net.HttpWebRequest.BeginGetRequestStream
BeginGetRequestStream()
override IAsyncResult System.Net.HttpWebRequest.BeginGetRequestStream (AsyncCallback? callback, object? state) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 921 of file HttpWebRequest.cs.
    {
        CheckAbort();
        if (Interlocked.Exchange(ref _beginGetRequestStreamCalled, 1) != 0)
        {
            throw new InvalidOperationException(System.SR.net_repcall);
        }
        _requestStreamCallback = callback;
        _requestStreamOperation = InternalGetRequestStream().ToApm(callback, state);
        return _requestStreamOperation.Task;
    }
References System.Net.HttpWebRequest._beginGetRequestStreamCalled, System.Net.HttpWebRequest._requestStreamCallback, System.Net.HttpWebRequest._requestStreamOperation, System.Net.HttpWebRequest.CheckAbort(), System.Runtime.Serialization.Dictionary, System.Threading.Interlocked.Exchange(), System.Net.HttpWebRequest.InternalGetRequestStream(), System.SR.net_repcall, System.state, and System.Threading.Tasks.TaskCompletionSource< TResult >.Task.