Terraria: System.Net.HttpWebRequest.InternalGetRequestStream
InternalGetRequestStream()
Task< Stream > System.Net.HttpWebRequest.InternalGetRequestStream () inline private
Definition at line 894 of file HttpWebRequest.cs.
    {
        CheckAbort();
        if (string.Equals(HttpMethod.Get.Method, _originVerb, StringComparison.OrdinalIgnoreCase) || string.Equals(HttpMethod.Head.Method, _originVerb, StringComparison.OrdinalIgnoreCase) || string.Equals("CONNECT", _originVerb, StringComparison.OrdinalIgnoreCase))
        {
            throw new ProtocolViolationException(System.SR.net_nouploadonget);
        }
        if (RequestSubmitted)
        {
            throw new InvalidOperationException(System.SR.net_reqsubmitted);
        }
        _requestStream = new RequestStream();
        return Task.FromResult((Stream)_requestStream);
    }
References System.Net.HttpWebRequest._originVerb, System.Net.HttpWebRequest._requestStream, System.Net.HttpWebRequest.CheckAbort(), System.Net.Equals, System.Net.Http.HttpMethod.Get, System.Net.Http.HttpMethod.Head, System.SR.net_nouploadonget, System.SR.net_reqsubmitted, and System.Net.HttpWebRequest.RequestSubmitted.
Referenced by System.Net.HttpWebRequest.BeginGetRequestStream(), and System.Net.HttpWebRequest.GetRequestStream().