Terraria: HitTile.HitTileObject.Clear
Clear()
void HitTile.HitTileObject.Clear () inline
         {
             X = 0;
             Y = 0;
             damage = 0;
             type = 0;
             timeToLive = 0;
             if (rand == null)
             {
                 rand = new UnifiedRandom((int)DateTime.Now.Ticks);
             }
             for (crackStyle = rand.Next(4); crackStyle == lastCrack; crackStyle = rand.Next(4))
             {
             }
             lastCrack = crackStyle;
         }
References HitTile.HitTileObject.crackStyle, HitTile.HitTileObject.damage, HitTile.lastCrack, UnifiedRandom.Next(), HitTile.rand, HitTile.HitTileObject.timeToLive, HitTile.HitTileObject.type, HitTile.HitTileObject.X, and HitTile.HitTileObject.Y.
Referenced by HitTile.HitTileObject.HitTileObject(), HitTile.Clear(), HitTile.Prune(), and HitTile.SortSlots().