Terraria: System.Net.HttpWebRequest.BeginGetResponse
BeginGetResponse()
override IAsyncResult System.Net.HttpWebRequest.BeginGetResponse (AsyncCallback? callback, object? state) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 1018 of file HttpWebRequest.cs.
    {
        CheckAbort();
        if (Interlocked.Exchange(ref _beginGetResponseCalled, 1) != 0)
        {
            throw new InvalidOperationException(System.SR.net_repcall);
        }
        _sendRequestCts = new CancellationTokenSource();
        _responseCallback = callback;
        _responseOperation = SendRequest(async: true).ToApm(callback, state);
        return _responseOperation.Task;
    }
References System.Net.HttpWebRequest._beginGetResponseCalled, System.Net.HttpWebRequest._responseCallback, System.Net.HttpWebRequest._responseOperation, System.Net.HttpWebRequest._sendRequestCts, System.Net.HttpWebRequest.CheckAbort(), System.Runtime.Serialization.Dictionary, System.Threading.Interlocked.Exchange(), System.SR.net_repcall, System.Net.HttpWebRequest.SendRequest(), and System.state.