Terraria: System.Net.HttpWebRequest.CreateHttpClient
CreateHttpClient()
static HttpClient System.Net.HttpWebRequest.CreateHttpClient (HttpClientParameters parameters, HttpWebRequest request) inline static private
Definition at line 1226 of file HttpWebRequest.cs.
    {
        HttpClient httpClient = null;
        try
        {
            SocketsHttpHandler socketsHttpHandler = new SocketsHttpHandler();
            httpClient = new HttpClient(socketsHttpHandler);
            socketsHttpHandler.AutomaticDecompression = parameters.AutomaticDecompression;
            socketsHttpHandler.Credentials = parameters.Credentials;
            socketsHttpHandler.AllowAutoRedirect = parameters.AllowAutoRedirect;
            socketsHttpHandler.MaxAutomaticRedirections = parameters.MaximumAutomaticRedirections;
            socketsHttpHandler.MaxResponseHeadersLength = parameters.MaximumResponseHeadersLength;
            socketsHttpHandler.PreAuthenticate = parameters.PreAuthenticate;
            httpClient.Timeout = parameters.Timeout;
            if (parameters.CookieContainer != null)
            {
                socketsHttpHandler.CookieContainer = parameters.CookieContainer;
            }
            else
            {
                socketsHttpHandler.UseCookies = false;
            }
            if (parameters.Proxy == null)
            {
                socketsHttpHandler.UseProxy = false;
            }
            else if (parameters.Proxy != WebRequest.GetSystemWebProxy())
            {
                socketsHttpHandler.Proxy = parameters.Proxy;
            }
            else
            {
                socketsHttpHandler.DefaultProxyCredentials = parameters.Proxy.Credentials;
            }
            if (parameters.ClientCertificates != null)
            {
                socketsHttpHandler.SslOptions.ClientCertificates = new X509CertificateCollection(parameters.ClientCertificates);
            }
            socketsHttpHandler.SslOptions.EnabledSslProtocols = (SslProtocols)parameters.SslProtocols;
            socketsHttpHandler.SslOptions.CertificateRevocationCheckMode = (parameters.CheckCertificateRevocationList ? X509RevocationMode.Online : X509RevocationMode.NoCheck);
            RemoteCertificateValidationCallback rcvc = parameters.ServerCertificateValidationCallback;
            if (rcvc != null)
            {
                socketsHttpHandler.SslOptions.RemoteCertificateValidationCallback = (object message, X509Certificate cert, X509Chain chain, SslPolicyErrors errors) => rcvc(request, cert, chain, errors);
            }
            socketsHttpHandler.ConnectCallback = async delegate(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
            {
                Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
                try
                {
                    socket.NoDelay = true;
                    if (parameters.Async)
                    {
                        await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    }
                    else
                    {
                        using (cancellationToken.UnsafeRegister(delegate(object s)
{
                            ((Socket)s).Dispose();
                        }, socket))
{
                            socket.Connect(context.DnsEndPoint);
                        }
                        cancellationToken.ThrowIfCancellationRequested();
                    }
                    if (parameters.ReadWriteTimeout > 0)
                    {
                        int sendTimeout = (socket.ReceiveTimeout = parameters.ReadWriteTimeout);
                        socket.SendTimeout = sendTimeout;
                    }
                }
                catch
                {
                    socket.Dispose();
                    throw;
                }
                return new NetworkStream(socket, ownsSocket: true);
            };
            return httpClient;
        }
        catch
        {
            httpClient?.Dispose();
            throw;
        }
    }
References System.Net.HttpWebRequest.HttpClientParameters.AllowAutoRedirect, System.Net.HttpWebRequest.HttpClientParameters.Async, System.Net.HttpWebRequest.HttpClientParameters.AutomaticDecompression, System.cancellationToken, System.Net.HttpWebRequest.HttpClientParameters.ClientCertificates, System.Net.HttpWebRequest.HttpClientParameters.CookieContainer, System.Net.IWebProxy.Credentials, System.Net.HttpWebRequest.HttpClientParameters.Credentials, System.Runtime.Serialization.Dictionary, System.Net.Sockets.NetworkStream.Dispose(), System.Net.Http.SocketsHttpConnectionContext.DnsEndPoint, System.Net.WebRequest.GetSystemWebProxy(), System.Net.HttpWebRequest.HttpClientParameters.MaximumAutomaticRedirections, System.Net.HttpWebRequest.HttpClientParameters.MaximumResponseHeadersLength, System.Net.HttpWebRequest.HttpClientParameters.PreAuthenticate, System.Net.HttpWebRequest.HttpClientParameters.Proxy, System.Net.HttpWebRequest.HttpClientParameters.ReadWriteTimeout, System.s, System.Net.HttpWebRequest.HttpClientParameters.ServerCertificateValidationCallback, System.Net.Sockets.Socket, System.Net.HttpWebRequest.HttpClientParameters.SslProtocols, and System.Net.HttpWebRequest.HttpClientParameters.Timeout.
Referenced by System.Net.HttpWebRequest.GetCachedOrCreateHttpClient().