Terraria: System.Net.HttpWebRequest.Abort
Abort()
override void System.Net.HttpWebRequest.Abort () inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 856 of file HttpWebRequest.cs.
    {
        if (Interlocked.Exchange(ref _abortCalled, 1) != 0)
        {
            return;
        }
        if (_responseOperation != null)
        {
            if (_responseOperation.TrySetCanceled() && _responseCallback != null)
            {
                _responseCallback(_responseOperation.Task);
            }
            _sendRequestCts.Cancel();
        }
        else if (_requestStreamOperation != null && _requestStreamOperation.TrySetCanceled() && _requestStreamCallback != null)
        {
            _requestStreamCallback(_requestStreamOperation.Task);
        }
    }
References System.Net.HttpWebRequest._abortCalled, System.Net.HttpWebRequest._requestStreamCallback, System.Net.HttpWebRequest._requestStreamOperation, System.Net.HttpWebRequest._responseCallback, System.Net.HttpWebRequest._responseOperation, System.Net.HttpWebRequest._sendRequestCts, System.Threading.CancellationTokenSource.Cancel(), System.Runtime.Serialization.Dictionary, System.Threading.Interlocked.Exchange(), System.Threading.Tasks.TaskCompletionSource< TResult >.Task, and System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetCanceled().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.EndConnection().