Terraria: System.Xml.Schema.DtdValidator.Validate
Validate()
override void System.Xml.Schema.DtdValidator.Validate () inline virtual
Reimplemented from System.Xml.Schema.BaseValidator.
Definition at line 64 of file DtdValidator.cs.
    {
        if (schemaInfo.SchemaType == SchemaType.DTD)
        {
            switch (reader.NodeType)
            {
            case XmlNodeType.Element:
                ValidateElement();
                if (reader.IsEmptyElement)
                {
                    goto case XmlNodeType.EndElement;
                }
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                if (MeetsStandAloneConstraint())
                {
                    ValidateWhitespace();
                }
                break;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
                ValidatePIComment();
                break;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
                ValidateText();
                break;
            case XmlNodeType.EntityReference:
                if (!GenEntity(new XmlQualifiedName(reader.LocalName, reader.Prefix)))
                {
                    ValidateText();
                }
                break;
            case XmlNodeType.EndElement:
                ValidateEndElement();
                break;
            case XmlNodeType.Attribute:
            case XmlNodeType.Entity:
            case XmlNodeType.Document:
            case XmlNodeType.DocumentType:
            case XmlNodeType.DocumentFragment:
            case XmlNodeType.Notation:
                break;
            }
        }
        else if (reader.Depth == 0 && reader.NodeType == XmlNodeType.Element)
        {
            SendValidationEvent(System.SR.Xml_NoDTDPresent, _name.ToString(), XmlSeverityType.Warning);
        }
    }
References System.Xml.Schema.DtdValidator._name, System.Xml.XmlValidatingReaderImpl.Depth, System.Xml.Schema.DtdValidator.GenEntity(), System.Xml.XmlValidatingReaderImpl.IsEmptyElement, System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.Schema.DtdValidator.MeetsStandAloneConstraint(), System.Xml.XmlValidatingReaderImpl.NodeType, System.Xml.XmlValidatingReaderImpl.Prefix, System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.SchemaInfo.SchemaType, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.XmlQualifiedName.ToString(), System.Xml.Schema.DtdValidator.ValidateElement(), System.Xml.Schema.DtdValidator.ValidateEndElement(), System.Xml.Schema.DtdValidator.ValidatePIComment(), System.Xml.Schema.BaseValidator.ValidateText(), System.Xml.Schema.BaseValidator.ValidateWhitespace(), and System.SR.Xml_NoDTDPresent.