Terraria: System.Xml.Schema.DtdValidator.Pop
Pop()
bool System.Xml.Schema.DtdValidator.Pop () inline private
Definition at line 486 of file DtdValidator.cs.
    {
        if (_validationStack.Length > 1)
        {
            _validationStack.Pop();
            context = (ValidationState)_validationStack.Peek();
            return true;
        }
        return false;
    }
References System.Xml.Schema.DtdValidator._validationStack, System.Xml.Schema.BaseValidator.context, System.Xml.HWStack.Length, System.Xml.HWStack.Peek(), and System.Xml.HWStack.Pop().
Referenced by System.Xml.Schema.DtdValidator.CompleteValidation(), and System.Xml.Schema.DtdValidator.ValidateEndElement().