Terraria: System.Threading.Tasks.Dataflow.BatchBlock.BatchBlockTargetCore.RetrievePostponedItemsGreedyBounded
RetrievePostponedItemsGreedyBounded()
void System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.RetrievePostponedItemsGreedyBounded (bool allowFewerThanBatchSize) inline private
Definition at line 552 of file BatchBlock.cs.
        {
            QueuedMap<ISourceBlock<T>, DataflowMessageHeader> postponedMessages = _nonGreedyState.PostponedMessages;
            KeyValuePair<ISourceBlock<T>, DataflowMessageHeader>[] postponedMessagesTemp = _nonGreedyState.PostponedMessagesTemp;
            List<KeyValuePair<ISourceBlock<T>, KeyValuePair<DataflowMessageHeader, T>>> reservedSourcesTemp = _nonGreedyState.ReservedSourcesTemp;
            reservedSourcesTemp.Clear();
            int num;
            int num2;
            lock (IncomingLock)
            {
                int boundedCapacityAvailable = BoundedCapacityAvailable;
                num = _batchSize - _messages.Count;
                if (_decliningPermanently || postponedMessages.Count == 0 || boundedCapacityAvailable <= 0)
                {
                    return;
                }
                if (boundedCapacityAvailable < num)
                {
                    num = boundedCapacityAvailable;
                }
                num2 = postponedMessages.PopRange(postponedMessagesTemp, 0, num);
            }
            for (int i = 0; i < num2; i++)
            {
                KeyValuePair<ISourceBlock<T>, DataflowMessageHeader> keyValuePair = postponedMessagesTemp[i];
                KeyValuePair<DataflowMessageHeader, T> value = new KeyValuePair<DataflowMessageHeader, T>(keyValuePair.Value, default(T));
                KeyValuePair<ISourceBlock<T>, KeyValuePair<DataflowMessageHeader, T>> item = new KeyValuePair<ISourceBlock<T>, KeyValuePair<DataflowMessageHeader, T>>(keyValuePair.Key, value);
                reservedSourcesTemp.Add(item);
            }
            Array.Clear(postponedMessagesTemp, 0, postponedMessagesTemp.Length);
            while (reservedSourcesTemp.Count < num)
            {
                KeyValuePair<ISourceBlock<T>, DataflowMessageHeader> item2;
                lock (IncomingLock)
                {
                    if (!postponedMessages.TryPop(out item2))
                    {
                        break;
                    }
                }
                KeyValuePair<DataflowMessageHeader, T> value2 = new KeyValuePair<DataflowMessageHeader, T>(item2.Value, default(T));
                KeyValuePair<ISourceBlock<T>, KeyValuePair<DataflowMessageHeader, T>> item3 = new KeyValuePair<ISourceBlock<T>, KeyValuePair<DataflowMessageHeader, T>>(item2.Key, value2);
                reservedSourcesTemp.Add(item3);
            }
            if (reservedSourcesTemp.Count > 0)
            {
                bool flag = true;
                if (allowFewerThanBatchSize)
                {
                    lock (IncomingLock)
                    {
                        if (!_decliningPermanently && _batchesCompleted + 1 >= _dataflowBlockOptions.ActualMaxNumberOfGroups)
{
                            flag = !_decliningPermanently;
                            _decliningPermanently = true;
                        }
                    }
                }
                if (flag)
                {
                    ConsumeReservedMessagesGreedyBounded();
                }
            }
            reservedSourcesTemp.Clear();
        }
References System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._batchesCompleted, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._batchSize, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._dataflowBlockOptions, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._decliningPermanently, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._messages, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._nonGreedyState, System.Threading.Tasks.Dataflow.GroupingDataflowBlockOptions.ActualMaxNumberOfGroups, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.BoundedCapacityAvailable, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Array.Clear(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ConsumeReservedMessagesGreedyBounded(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.IncomingLock, System.item, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.NonGreedyState.PostponedMessages, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.NonGreedyState.PostponedMessagesTemp, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.NonGreedyState.ReservedSourcesTemp, and System.value.
Referenced by System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessMessagesLoopCore().