Terraria: System.Xml.Schema.DtdValidator.SetDefaultTypedValue
SetDefaultTypedValue()
static void System.Xml.Schema.DtdValidator.SetDefaultTypedValue (SchemaAttDef attdef, IDtdParserAdapter readerAdapter) inline static
Definition at line 497 of file DtdValidator.cs.
    {
        try
        {
            string text = attdef.DefaultValueExpanded;
            XmlSchemaDatatype datatype = attdef.Datatype;
            if (datatype != null)
            {
                if (datatype.TokenizedType != 0)
                {
                    text = text.Trim();
                }
                attdef.DefaultValueTyped = datatype.ParseValue(text, readerAdapter.NameTable, readerAdapter.NamespaceResolver);
            }
        }
        catch (Exception)
        {
            IValidationEventHandling validationEventHandling = ((IDtdParserAdapterWithValidation)readerAdapter).ValidationEventHandling;
            if (validationEventHandling != null)
            {
                XmlSchemaException exception = new XmlSchemaException(System.SR.Sch_AttributeDefaultDataType, attdef.Name.ToString());
                validationEventHandling.SendEvent(exception, XmlSeverityType.Error);
            }
        }
    }
References System.Xml.Dictionary, System.exception, System.Xml.Schema.XmlSchemaDatatype.ParseValue(), System.SR.Sch_AttributeDefaultDataType, System.text, and System.Xml.Schema.XmlSchemaDatatype.TokenizedType.
Referenced by System.Xml.DtdParser.ParseAttlistDefault(), and System.Xml.DtdParser.ParseAttlistDefaultAsync().