Terraria: System.Threading.Tasks.Dataflow.BatchBlock.BatchBlockTargetCore.ProcessAsyncIfNecessary_Slow
ProcessAsyncIfNecessary_Slow()
void System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessAsyncIfNecessary_Slow (bool isReplacementReplica) inline private
Definition at line 395 of file BatchBlock.cs.
        {
            _nonGreedyState.TaskForInputProcessing = new Task(delegate(object thisBatchTarget)
            {
                ((BatchBlockTargetCore)thisBatchTarget).ProcessMessagesLoopCore();
            }, this, Common.GetCreationOptionsForTask(isReplacementReplica));
            DataflowEtwProvider log = DataflowEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.TaskLaunchedForMessageHandling(_owningBatch, _nonGreedyState.TaskForInputProcessing, DataflowEtwProvider.TaskLaunchedReason.ProcessingInputMessages, _messages.Count + _nonGreedyState.PostponedMessages.Count);
            }
            Exception ex = Common.StartTaskSafe(_nonGreedyState.TaskForInputProcessing, _dataflowBlockOptions.TaskScheduler);
            if (ex != null)
            {
                Task.Factory.StartNew(delegate(object exc)
                {
                    Complete((Exception)exc, dropPendingMessages: true, releaseReservedMessages: true, revertProcessingState: true);
                }, ex, CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
            }
        }
References System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.BatchBlockTargetCore(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._dataflowBlockOptions, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._messages, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._nonGreedyState, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._owningBatch, System.Threading.Tasks.Dataflow.BatchBlock< T >.Complete(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.NonGreedyState.PostponedMessages, System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.NonGreedyState.TaskForInputProcessing, and System.Threading.Tasks.Dataflow.DataflowBlockOptions.TaskScheduler.
Referenced by System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessAsyncIfNecessary().