Terraria: System.Threading.Tasks.Dataflow.BatchBlock.BatchBlockTargetCore.Complete
Complete()
void System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.Complete (Exception exception, bool dropPendingMessages, bool releaseReservedMessages, bool revertProcessingState = false) inline package
Definition at line 317 of file BatchBlock.cs.
        {
            lock (IncomingLock)
            {
                if (exception != null && (!_decliningPermanently || releaseReservedMessages))
                {
                    _owningBatch._source.AddException(exception);
                }
                if (dropPendingMessages)
                {
                    _messages.Clear();
                }
            }
            if (releaseReservedMessages)
            {
                try
                {
                    ReleaseReservedMessages(throwOnFirstException: false);
                }
                catch (Exception exception2)
                {
                    _owningBatch._source.AddException(exception2);
                }
            }
            lock (IncomingLock)
            {
                if (revertProcessingState)
                {
                    _nonGreedyState.TaskForInputProcessing = null;
                }
                _decliningPermanently = true;
                CompleteBlockIfPossible();
            }
        }
References System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._decliningPermanently, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._messages, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._owningBatch, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.CompleteBlockIfPossible(), System.exception, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.IncomingLock, and System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ReleaseReservedMessages().
Referenced by System.Threading.Tasks.Dataflow.BatchBlock< T >.Complete(), and System.Threading.Tasks.Dataflow.BatchBlock< T >.Fault().