Terraria: System.Xml.Schema.DtdValidator.CheckValue
CheckValue()
void System.Xml.Schema.DtdValidator.CheckValue (string value, SchemaAttDef attdef) inline private
Definition at line 323 of file DtdValidator.cs.
    {
        try
        {
            reader.TypedValueObject = null;
            bool flag = attdef != null;
            XmlSchemaDatatype xmlSchemaDatatype = (flag ? attdef.Datatype : context.ElementDecl.Datatype);
            if (xmlSchemaDatatype == null)
            {
                return;
            }
            if (xmlSchemaDatatype.TokenizedType != 0)
            {
                value = value.Trim();
            }
            object obj = xmlSchemaDatatype.ParseValue(value, base.NameTable, s_namespaceManager);
            reader.TypedValueObject = obj;
            XmlTokenizedType tokenizedType = xmlSchemaDatatype.TokenizedType;
            if (tokenizedType == XmlTokenizedType.ENTITY || tokenizedType == XmlTokenizedType.ID || tokenizedType == XmlTokenizedType.IDREF)
            {
                if (xmlSchemaDatatype.Variety == XmlSchemaDatatypeVariety.List)
                {
                    string[] array = (string[])obj;
                    for (int i = 0; i < array.Length; i++)
                    {
                        ProcessTokenizedType(xmlSchemaDatatype.TokenizedType, array[i]);
                    }
                }
                else
                {
                    ProcessTokenizedType(xmlSchemaDatatype.TokenizedType, (string)obj);
                }
            }
            SchemaDeclBase schemaDeclBase = (flag ? ((SchemaDeclBase)attdef) : ((SchemaDeclBase)context.ElementDecl));
            if (schemaDeclBase.Values != null && !schemaDeclBase.CheckEnumeration(obj))
            {
                if (xmlSchemaDatatype.TokenizedType == XmlTokenizedType.NOTATION)
                {
                    SendValidationEvent(System.SR.Sch_NotationValue, obj.ToString());
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_EnumerationValue, obj.ToString());
                }
            }
            if (!schemaDeclBase.CheckValue(obj))
            {
                if (flag)
                {
                    SendValidationEvent(System.SR.Sch_FixedAttributeValue, attdef.Name.ToString());
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_FixedElementValue, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
                }
            }
        }
        catch (XmlSchemaException)
        {
            if (attdef != null)
            {
                SendValidationEvent(System.SR.Sch_AttributeValueDataType, attdef.Name.ToString());
            }
            else
            {
                SendValidationEvent(System.SR.Sch_ElementValueDataType, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
            }
        }
    }
References System.array, System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.Datatype, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.obj, System.Xml.Schema.XmlSchemaDatatype.ParseValue(), System.Xml.Schema.DtdValidator.ProcessTokenizedType(), System.Xml.Schema.XmlSchemaValidator.QNameString(), System.Xml.Schema.DtdValidator.s_namespaceManager, System.SR.Sch_AttributeValueDataType, System.SR.Sch_ElementValueDataType, System.SR.Sch_EnumerationValue, System.SR.Sch_FixedAttributeValue, System.SR.Sch_FixedElementValue, System.SR.Sch_NotationValue, System.Xml.Schema.BaseValidator.SendValidationEvent(), and System.value.
Referenced by System.Xml.Schema.DtdValidator.ValidateEndElement(), and System.Xml.Schema.DtdValidator.ValidateStartElement().