Terraria: System.Threading.Tasks.Dataflow.BatchBlock.BatchBlockTargetCore.ProcessMessagesLoopCore
ProcessMessagesLoopCore()
void System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessMessagesLoopCore () inline private
Definition at line 416 of file BatchBlock.cs.
        {
            try
            {
                int actualMaxMessagesPerTask = _dataflowBlockOptions.ActualMaxMessagesPerTask;
                int num = 0;
                bool flag2;
                do
                {
                    bool flag = Volatile.Read(ref _nonGreedyState.AcceptFewerThanBatchSize);
                    if (!_dataflowBlockOptions.Greedy)
                    {
                        RetrievePostponedItemsNonGreedy(flag);
                    }
                    else
                    {
                        RetrievePostponedItemsGreedyBounded(flag);
                    }
                    lock (IncomingLock)
                    {
                        flag2 = MakeBatchIfPossible(flag);
                        if (flag2 || flag)
{
                            _nonGreedyState.AcceptFewerThanBatchSize = false;
                        }
                    }
                    num++;
                }
                while (flag2 && num < actualMaxMessagesPerTask);
            }
            catch (Exception exception)
            {
                Complete(exception, dropPendingMessages: false, releaseReservedMessages: true);
            }
            finally
            {
                lock (IncomingLock)
                {
                    _nonGreedyState.TaskForInputProcessing = null;
                    ProcessAsyncIfNecessary(isReplacementReplica: true);
                    CompleteBlockIfPossible();
                }
            }
        }
References System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._dataflowBlockOptions, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._nonGreedyState, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.NonGreedyState.AcceptFewerThanBatchSize, System.Threading.Tasks.Dataflow.DataflowBlockOptions.ActualMaxMessagesPerTask, System.Threading.Tasks.Dataflow.BatchBlock< T >.Complete(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.CompleteBlockIfPossible(), System.exception, System.Threading.Tasks.Dataflow.GroupingDataflowBlockOptions.Greedy, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.IncomingLock, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.MakeBatchIfPossible(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessAsyncIfNecessary(), System.Threading.Volatile.Read(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.RetrievePostponedItemsGreedyBounded(), and System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.RetrievePostponedItemsNonGreedy().