Terraria: System.Xml.Schema.DtdValidator.ValidateStartElement
ValidateStartElement()
void System.Xml.Schema.DtdValidator.ValidateStartElement () inline private
Definition at line 161 of file DtdValidator.cs.
    {
        if (context.ElementDecl != null)
        {
            base.Reader.SchemaTypeObject = context.ElementDecl.SchemaType;
            if (base.Reader.IsEmptyElement && context.ElementDecl.DefaultValueTyped != null)
            {
                base.Reader.TypedValueObject = context.ElementDecl.DefaultValueTyped;
                context.IsNill = true;
            }
            if (context.ElementDecl.HasRequiredAttribute)
            {
                _attPresence.Clear();
            }
        }
        if (!base.Reader.MoveToFirstAttribute())
        {
            return;
        }
        do
        {
            try
            {
                reader.SchemaTypeObject = null;
                SchemaAttDef attDef = context.ElementDecl.GetAttDef(new XmlQualifiedName(reader.LocalName, reader.Prefix));
                if (attDef != null)
                {
                    if (context.ElementDecl != null && context.ElementDecl.HasRequiredAttribute)
                    {
                        _attPresence.Add(attDef.Name, attDef);
                    }
                    base.Reader.SchemaTypeObject = attDef.SchemaType;
                    if (attDef.Datatype != null && !reader.IsDefault)
                    {
                        CheckValue(base.Reader.Value, attDef);
                    }
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_UndeclaredAttribute, reader.Name);
                }
            }
            catch (XmlSchemaException ex)
            {
                ex.SetSource(base.Reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition);
                SendValidationEvent(ex);
            }
        }
        while (base.Reader.MoveToNextAttribute());
        base.Reader.MoveToElement();
    }
References System.Xml.Schema.DtdValidator._attPresence, System.Collections.Hashtable.Add(), System.Xml.Schema.DtdValidator.CheckValue(), System.Collections.Hashtable.Clear(), System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.DefaultValueTyped, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.SchemaElementDecl.GetAttDef(), System.Xml.Schema.SchemaElementDecl.HasRequiredAttribute, System.Xml.XmlValidatingReaderImpl.IsDefault, System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.Name, System.Xml.XmlValidatingReaderImpl.Prefix, System.Xml.Schema.BaseValidator.reader, System.SR.Sch_UndeclaredAttribute, System.Xml.Schema.SchemaDeclBase.SchemaType, and System.Xml.Schema.BaseValidator.SendValidationEvent().
Referenced by System.Xml.Schema.DtdValidator.ProcessElement().