Terraria: System.Xml.Schema.DtdValidator.ProcessElement
ProcessElement()
void System.Xml.Schema.DtdValidator.ProcessElement () inline private
Definition at line 236 of file DtdValidator.cs.
    {
        SchemaElementDecl elementDecl = schemaInfo.GetElementDecl(elementName);
        Push(elementName);
        if (elementDecl != null)
        {
            context.ElementDecl = elementDecl;
            ValidateStartElement();
            ValidateEndStartElement();
            context.NeedValidateChildren = true;
            elementDecl.ContentValidator.InitValidation(context);
        }
        else
        {
            SendValidationEvent(System.SR.Sch_UndeclaredElement, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
            context.ElementDecl = null;
        }
    }
References System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.BaseValidator.elementName, System.Xml.Schema.SchemaInfo.GetElementDecl(), System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.DtdValidator.Push(), System.Xml.Schema.XmlSchemaValidator.QNameString(), System.SR.Sch_UndeclaredElement, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.DtdValidator.ValidateEndStartElement(), and System.Xml.Schema.DtdValidator.ValidateStartElement().
Referenced by System.Xml.Schema.DtdValidator.ValidateElement().