Terraria: System.Threading.Tasks.Dataflow.BatchBlock.BatchBlockTargetCore.CompleteBlockIfPossible
CompleteBlockIfPossible()
void System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.CompleteBlockIfPossible () inline private
Definition at line 352 of file BatchBlock.cs.
        {
            if (_completionReserved)
            {
                return;
            }
            bool flag = _nonGreedyState != null && _nonGreedyState.TaskForInputProcessing != null;
            bool flag2 = _batchesCompleted >= _dataflowBlockOptions.ActualMaxNumberOfGroups;
            bool flag3 = _decliningPermanently && _messages.Count < _batchSize;
            if (flag || (!(flag2 || flag3) && !CanceledOrFaulted))
            {
                return;
            }
            _completionReserved = true;
            _decliningPermanently = true;
            if (_messages.Count > 0)
            {
                MakeBatchIfPossible(evenIfFewerThanBatchSize: true);
            }
            Task.Factory.StartNew(delegate(object thisTargetCore)
            {
                BatchBlockTargetCore batchBlockTargetCore = (BatchBlockTargetCore)thisTargetCore;
                List<Exception> exceptions = null;
                if (batchBlockTargetCore._nonGreedyState != null)
                {
                    Common.ReleaseAllPostponedMessages(batchBlockTargetCore._owningBatch, batchBlockTargetCore._nonGreedyState.PostponedMessages, ref exceptions);
                }
                if (exceptions != null)
                {
                    batchBlockTargetCore._owningBatch._source.AddExceptions(exceptions);
                }
                batchBlockTargetCore._completionTask.TrySetResult(default(VoidResult));
            }, this, CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
        }
References System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.BatchBlockTargetCore(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._batchesCompleted, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._batchSize, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._completionReserved, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._dataflowBlockOptions, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._decliningPermanently, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._messages, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore._nonGreedyState, System.Threading.Tasks.Dataflow.GroupingDataflowBlockOptions.ActualMaxNumberOfGroups, System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.CanceledOrFaulted, System.Threading.Tasks.TaskScheduler.Default, System.exceptions, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.MakeBatchIfPossible(), and System.Threading.CancellationToken.None.
Referenced by System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.Complete(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.OfferMessage(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.OnItemsRemoved(), System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.ProcessMessagesLoopCore(), and System.Threading.Tasks.Dataflow.BatchBlock< T >.BatchBlockTargetCore.TriggerBatch().