Terraria: System.Xml.Schema.DtdValidator.GenEntity
GenEntity()
bool System.Xml.Schema.DtdValidator.GenEntity (XmlQualifiedName qname) inline private
Definition at line 411 of file DtdValidator.cs.
    {
        string name = qname.Name;
        if (name[0] == '#')
        {
            return false;
        }
        if (SchemaEntity.IsPredefinedEntity(name))
        {
            return false;
        }
        SchemaEntity entity = GetEntity(qname, fParameterEntity: false);
        if (entity == null)
        {
            throw new XmlException(System.SR.Xml_UndeclaredEntity, name);
        }
        if (!entity.NData.IsEmpty)
        {
            throw new XmlException(System.SR.Xml_UnparsedEntityRef, name);
        }
        if (reader.StandAlone && entity.DeclaredInExternal)
        {
            SendValidationEvent(System.SR.Sch_StandAlone);
        }
        return true;
    }
References System.Xml.Schema.SchemaEntity.DeclaredInExternal, System.Xml.Dictionary, System.Xml.Schema.DtdValidator.GetEntity(), System.Xml.XmlQualifiedName.IsEmpty, System.Xml.Schema.SchemaEntity.IsPredefinedEntity(), System.Xml.XmlQualifiedName.Name, System.Xml.Schema.SchemaEntity.NData, System.Xml.Schema.BaseValidator.reader, System.SR.Sch_StandAlone, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.XmlValidatingReaderImpl.StandAlone, System.SR.Xml_UndeclaredEntity, System.SR.Xml_UnparsedEntityRef, and System.Xml.XmlException.
Referenced by System.Xml.Schema.DtdValidator.Validate().