Terraria: System.Xml.Schema.DtdValidator.ValidateElement
ValidateElement()
void System.Xml.Schema.DtdValidator.ValidateElement () inline private
Definition at line 134 of file DtdValidator.cs.
    {
        elementName.Init(reader.LocalName, reader.Prefix);
        if (reader.Depth == 0 && !schemaInfo.DocTypeName.IsEmpty && !schemaInfo.DocTypeName.Equals(elementName))
        {
            SendValidationEvent(System.SR.Sch_RootMatchDocType);
        }
        else
        {
            ValidateChildElement();
        }
        ProcessElement();
    }
References System.Xml.XmlValidatingReaderImpl.Depth, System.Xml.Schema.SchemaInfo.DocTypeName, System.Xml.Schema.BaseValidator.elementName, System.Xml.XmlQualifiedName.Equals(), System.Xml.XmlQualifiedName.Init(), System.Xml.XmlQualifiedName.IsEmpty, System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.Prefix, System.Xml.Schema.DtdValidator.ProcessElement(), System.Xml.Schema.BaseValidator.reader, System.SR.Sch_RootMatchDocType, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.BaseValidator.SendValidationEvent(), and System.Xml.Schema.DtdValidator.ValidateChildElement().
Referenced by System.Xml.Schema.DtdValidator.Validate().