Terraria: System.Numerics.VectorMath.ConditionalSelectBitwise
ConditionalSelectBitwise() [1/2]
static Vector128< double > System.Numerics.VectorMath.ConditionalSelectBitwise (Vector128< double > selector, Vector128< double > ifTrue, Vector128< double > ifFalse) inline static
Definition at line 24 of file VectorMath.cs.
    {
        if (AdvSimd.IsSupported)
        {
        }
        if (Sse2.IsSupported)
        {
            return Sse2.Or(Sse2.And(ifTrue, selector), Sse2.AndNot(selector, ifFalse));
        }
        throw new PlatformNotSupportedException();
    }
References System.Runtime.Intrinsics.X86.Sse2.And(), System.Runtime.Intrinsics.X86.Sse2.AndNot(), System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, and System.Runtime.Intrinsics.X86.Sse2.Or().