Terraria: System.Numerics.VectorMath.ConditionalSelectBitwise
ConditionalSelectBitwise() [2/2]
static Vector128< float > System.Numerics.VectorMath.ConditionalSelectBitwise (Vector128< float > selector, Vector128< float > ifTrue, Vector128< float > ifFalse) inline static
Definition at line 11 of file VectorMath.cs.
    {
        if (AdvSimd.IsSupported)
        {
        }
        if (Sse.IsSupported)
        {
            return Sse.Or(Sse.And(ifTrue, selector), Sse.AndNot(selector, ifFalse));
        }
        throw new PlatformNotSupportedException();
    }
References System.Runtime.Intrinsics.X86.Sse.And(), System.Runtime.Intrinsics.X86.Sse.AndNot(), System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse.IsSupported, and System.Runtime.Intrinsics.X86.Sse.Or().
Referenced by System.Math.CopySign(), and System.MathF.CopySign().