Terraria: System.Reflection.MethodBase.CheckArguments
CheckArguments()
Span< object > System.Reflection.MethodBase.CheckArguments (ref StackAllocedArguments stackArgs, ReadOnlySpan< object > parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig) inline protected inherited
Definition at line 161 of file MethodBase.cs.
    {
        Span<object> result = ((parameters.Length <= 4) ? MemoryMarshal.CreateSpan(ref stackArgs._arg0, parameters.Length) : new Span<object>(new object[parameters.Length]));
        ParameterInfo[] array = null;
        for (int i = 0; i < parameters.Length; i++)
        {
            object obj = parameters[i];
            RuntimeType runtimeType = sig.Arguments[i];
            if (obj == Type.Missing)
            {
                if (array == null)
                {
                    array = GetParametersNoCopy();
                }
                if (array[i].DefaultValue == DBNull.Value)
                {
                    throw new ArgumentException(SR.Arg_VarMissNull, "parameters");
                }
                obj = array[i].DefaultValue;
            }
            result[i] = runtimeType.CheckValue(obj, binder, culture, invokeAttr);
        }
        return result;
    }
References System.SR.Arg_VarMissNull, System.Signature.Arguments, System.array, System.RuntimeType.CheckValue(), System.culture, System.Reflection.MethodBase.GetParametersNoCopy(), System.ReadOnlySpan< T >.Length, System.Type.Missing, System.obj, and System.DBNull.Value.
Referenced by System.Reflection.RuntimeConstructorInfo.Invoke(), System.Reflection.RuntimeConstructorInfo.Invoke(), System.Reflection.RuntimeMethodInfo.Invoke(), System.Reflection.Emit.DynamicMethod.Invoke(), and System.Reflection.RuntimeMethodInfo.InvokeOneParameter().