Terraria: System.Reflection.MethodBase.GetParameters
GetParameters()
ParameterInfo[] System.Reflection.MethodBase.GetParameters () abstract inherited
Referenced by System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.AppDomain.ExecuteAssembly(), System.Delegate.GetMethodImpl(), System.Reflection.Emit.ConstructorBuilder.GetParameters(), System.Reflection.Emit.ConstructorOnTypeBuilderInstantiation.GetParameters(), System.Reflection.Emit.MethodBuilder.GetParameters(), System.Reflection.Emit.MethodOnTypeBuilderInstantiation.GetParameters(), System.Dynamic.Utils.TypeExtensions.GetParametersCached(), System.Reflection.MethodBase.GetParametersNoCopy(), System.Runtime.InteropServices.ComEventsMethod.DelegateWrapper.PreProcessSignature(), and System.ComponentModel.DataAnnotations.CustomValidationAttribute.ValidateMethodParameter().