Terraria: System.Reflection.MethodBase.AppendParameters
AppendParameters()
static void System.Reflection.MethodBase.AppendParameters (ref ValueStringBuilder sbParamList, Type[] parameterTypes, CallingConventions callingConvention) inline static package inherited
Definition at line 243 of file MethodBase.cs.
    {
        string s = "";
        foreach (Type type in parameterTypes)
        {
            sbParamList.Append(s);
            string text = type.FormatTypeName();
            if (type.IsByRef)
            {
                sbParamList.Append(text.AsSpan().TrimEnd('&'));
                sbParamList.Append(" ByRef");
            }
            else
            {
                sbParamList.Append(text);
            }
            s = ", ";
        }
        if ((callingConvention & CallingConventions.VarArgs) == CallingConventions.VarArgs)
        {
            sbParamList.Append(s);
            sbParamList.Append("...");
        }
    }
References System.s, System.text, and System.type.
Referenced by System.Reflection.Emit.DynamicMethod.RTDynamicMethod.ToString(), System.Reflection.RuntimeConstructorInfo.ToString(), System.Reflection.RuntimeMethodInfo.ToString(), and System.Reflection.RuntimePropertyInfo.ToString().