Terraria: System.Reflection.MethodBase.Invoke
Invoke() [3/3]
object? System.Reflection.MethodBase.Invoke (object? obj, object??[] parameters) inline inherited
Definition at line 203 of file MethodBase.cs.
    {
        return Invoke(obj, BindingFlags.Default, null, parameters, null);
    }
References System.Reflection.MethodBase.Invoke(), and System.obj.
Referenced by System.Reflection.CustomAttribute.AddCustomAttributes(), System.ComponentModel.ReflectEventDescriptor.AddEventHandler(), System.Reflection.EventInfo.AddEventHandler(), Internal.Runtime.InteropServices.LicenseInteropProxy.AllocateAndValidateLicense(), System.StartupHookProvider.CallStartupHook(), System.ComponentModel.ReflectPropertyDescriptor.CanResetValue(), System.AppDomain.ExecuteAssembly(), System.Xml.Serialization.XmlSchemaExporter.ExportDefaultValue(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderCanResetValue(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderGetValue(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderResetValue(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderSetValue(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderShouldSerializeValue(), Internal.Runtime.InteropServices.LicenseInteropProxy.GetCurrentContextInfo(), Internal.Runtime.InteropServices.LicenseInteropProxy.GetLicInfo(), System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.GetSourceConstructFlags(), System.Xml.Xsl.Runtime.XmlExtensionFunction.Invoke(), System.Reflection.MethodBase.Invoke(), System.Xml.Xsl.XsltOld.XsltCompileContext.FuncExtension.Invoke(), System.ComponentModel.DataAnnotations.CustomValidationAttribute.IsValid(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(), System.ComponentModel.ReflectEventDescriptor.RemoveEventHandler(), System.Reflection.EventInfo.RemoveEventHandler(), Internal.Runtime.InteropServices.LicenseInteropProxy.RequestLicKey(), System.Xml.Serialization.SerializableMapping.RetrieveSerializableSchema(), System.Linq.Expressions.Interpreter.ByRefMethodInfoCallInstruction.Run(), System.Linq.Expressions.Interpreter.MethodInfoCallInstruction.Run(), Internal.Runtime.InteropServices.LicenseInteropProxy.SaveKeyInCurrentContext(), and System.Linq.Expressions.Interpreter.IndexMethodByRefUpdater.Update().