Terraria: System.Reflection.MethodBase.GetParameterTypes
GetParameterTypes()
virtual Type[] System.Reflection.MethodBase.GetParameterTypes () inline package virtual inherited
Reimplemented in System.Reflection.Emit.ConstructorBuilder, System.Reflection.Emit.ConstructorOnTypeBuilderInstantiation, System.Reflection.Emit.MethodBuilder, System.Reflection.Emit.MethodBuilderInstantiation, System.Reflection.Emit.MethodOnTypeBuilderInstantiation, and System.Reflection.Emit.SymbolMethod.
Definition at line 150 of file MethodBase.cs.
    {
        ParameterInfo[] parametersNoCopy = GetParametersNoCopy();
        Type[] array = new Type[parametersNoCopy.Length];
        for (int i = 0; i < parametersNoCopy.Length; i++)
        {
            array[i] = parametersNoCopy[i].ParameterType;
        }
        return array;
    }
References System.array, System.Reflection.MethodBase.GetParametersNoCopy(), and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.EmitCall(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Reflection.Emit.ConstructorOnTypeBuilderInstantiation.GetParameterTypes(), System.Reflection.Emit.MethodBuilderInstantiation.GetParameterTypes(), System.Reflection.Emit.MethodOnTypeBuilderInstantiation.GetParameterTypes(), System.Reflection.Emit.DynamicMethod.RTDynamicMethod.ToString(), System.Reflection.RuntimeConstructorInfo.ToString(), and System.Reflection.RuntimeMethodInfo.ToString().