Terraria: Terraria.GameContent.Tile_Entities.TETeleportationPylon.Place
Place()
static int Terraria.GameContent.Tile_Entities.TETeleportationPylon.Place (int x, int y) inline static
    {
        TETeleportationPylon tETeleportationPylon = new TETeleportationPylon();
        tETeleportationPylon.Position = new Point16(x, y);
        tETeleportationPylon.ID = TileEntity.AssignNewID();
        tETeleportationPylon.type = _myEntityID;
        lock (TileEntity.EntityCreationLock)
        {
            TileEntity.ByID[tETeleportationPylon.ID] = tETeleportationPylon;
            TileEntity.ByPosition[tETeleportationPylon.Position] = tETeleportationPylon;
        }
        Main.PylonSystem.RequestImmediateUpdate();
        return tETeleportationPylon.ID;
    }
References Terraria.GameContent.Tile_Entities.TETeleportationPylon._myEntityID, Terraria.DataStructures.TileEntity.AssignNewID(), Terraria.DataStructures.TileEntity.ByID, Terraria.DataStructures.TileEntity.ByPosition, Terraria.DataStructures.TileEntity.EntityCreationLock, Terraria.DataStructures.TileEntity.ID, Terraria.DataStructures.TileEntity.Position, and Terraria.Main.PylonSystem.
Referenced by Terraria.GameContent.Tile_Entities.TETeleportationPylon.NetPlaceEntityAttempt(), and Terraria.GameContent.Tile_Entities.TETeleportationPylon.PlacementPreviewHook_AfterPlacement().