Terraria: Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile
Framing_CheckTile()
static void Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile (int callX, int callY) inline static
    {
        if (WorldGen.destroyObject)
        {
            return;
        }
        int num = callX;
        int num2 = callY;
        Tile tileSafely = Framing.GetTileSafely(callX, callY);
        num -= tileSafely.frameX / 18 % 3;
        num2 -= tileSafely.frameY / 18 % 4;
        int pylonStyleFromTile = GetPylonStyleFromTile(tileSafely);
        bool flag = false;
        for (int i = num; i < num + 3; i++)
        {
            for (int j = num2; j < num2 + 4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (!tile.active() || tile.type != 597)
                {
                    flag = true;
                }
            }
        }
        if (!WorldGen.SolidTileAllowBottomSlope(num, num2 + 4) || !WorldGen.SolidTileAllowBottomSlope(num + 1, num2 + 4) || !WorldGen.SolidTileAllowBottomSlope(num + 2, num2 + 4))
        {
            flag = true;
        }
        if (!flag)
        {
            return;
        }
        Kill(num, num2);
        int pylonItemTypeFromTileStyle = GetPylonItemTypeFromTileStyle(pylonStyleFromTile);
        Item.NewItem(new EntitySource_TileBreak(num, num2), num * 16, num2 * 16, 48, 64, pylonItemTypeFromTileStyle);
        WorldGen.destroyObject = true;
        for (int k = num; k < num + 3; k++)
        {
            for (int l = num2; l < num2 + 4; l++)
            {
                if (Main.tile[k, l].active() && Main.tile[k, l].type == 597)
                {
                    WorldGen.KillTile(k, l);
                }
            }
        }
        WorldGen.destroyObject = false;
    }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.GameContent.Tile_Entities.TETeleportationPylon.GetPylonItemTypeFromTileStyle(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.GetPylonStyleFromTile(), Terraria.Framing.GetTileSafely(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Kill(), Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrame().