Terraria: System.Transactions.TransactionInterop.GetTransactionFromExportCookie
GetTransactionFromExportCookie()
static Transaction System.Transactions.TransactionInterop.GetTransactionFromExportCookie (byte[] cookie) inline static
Definition at line 57 of file TransactionInterop.cs.
    {
        if (cookie == null)
        {
            throw new ArgumentNullException("cookie");
        }
        if (cookie.Length < 32)
        {
            throw new ArgumentException(System.SR.InvalidArgument, "cookie");
        }
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceDistributed, "TransactionInterop.GetTransactionFromExportCookie");
        }
        byte[] array = new byte[cookie.Length];
        Buffer.BlockCopy(cookie, 0, array, 0, cookie.Length);
        cookie = array;
        Guid guid = new Guid(cookie.AsSpan(16, 16));
        Transaction transaction = TransactionManager.FindPromotedTransaction(guid);
        if (transaction != null)
        {
            if (log.IsEnabled())
            {
                log.MethodExit(TraceSourceType.TraceSourceDistributed, "TransactionInterop.GetTransactionFromExportCookie");
            }
            return transaction;
        }
        DistributedTransaction transactionFromExportCookie = DistributedTransactionManager.GetTransactionFromExportCookie(array, guid);
        transaction = TransactionManager.FindOrCreatePromotedTransaction(guid, transactionFromExportCookie);
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceDistributed, "TransactionInterop.GetTransactionFromExportCookie");
        }
        return transaction;
    }
References System.array, System.Buffer.BlockCopy(), System.Transactions.TransactionManager.FindOrCreatePromotedTransaction(), System.Transactions.TransactionManager.FindPromotedTransaction(), System.Transactions.Distributed.DistributedTransactionManager.GetTransactionFromExportCookie(), System.SR.InvalidArgument, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), and System.Transactions.TransactionsEtwProvider.MethodExit().