Terraria: System.Transactions.TransactionInterop.ConvertToDistributedTransaction
ConvertToDistributedTransaction()
static DistributedTransaction System.Transactions.TransactionInterop.ConvertToDistributedTransaction (Transaction transaction) inline static package
Definition at line 9 of file TransactionInterop.cs.
    {
        if (null == transaction)
        {
            throw new ArgumentNullException("transaction");
        }
        if (transaction.Disposed)
        {
            throw new ObjectDisposedException("Transaction");
        }
        if (transaction._complete)
        {
            throw TransactionException.CreateTransactionCompletedException(transaction.DistributedTxId);
        }
        DistributedTransaction distributedTransaction = transaction.Promote();
        if (distributedTransaction == null)
        {
            throw DistributedTransaction.NotSupported();
        }
        return distributedTransaction;
    }
References System.Transactions.Transaction._complete, System.Transactions.TransactionException.CreateTransactionCompletedException(), System.Transactions.Transaction.Disposed, System.Transactions.Transaction.DistributedTxId, System.Transactions.Distributed.DistributedTransaction.NotSupported(), and System.Transactions.Transaction.Promote().
Referenced by System.Transactions.TransactionInterop.GetDtcTransaction(), System.Transactions.TransactionInterop.GetExportCookie(), and System.Transactions.TransactionInterop.GetTransmitterPropagationToken().