Terraria: System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken
GetDistributedTransactionFromTransmitterPropagationToken()
static DistributedTransaction System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken (byte[] propagationToken) inline static package
Definition at line 203 of file TransactionInterop.cs.
    {
        if (propagationToken == null)
        {
            throw new ArgumentNullException("propagationToken");
        }
        if (propagationToken.Length < 24)
        {
            throw new ArgumentException(System.SR.InvalidArgument, "propagationToken");
        }
        byte[] array = new byte[propagationToken.Length];
        Array.Copy(propagationToken, array, propagationToken.Length);
        return DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(array);
    }
References System.array, System.Array.Copy(), System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(), and System.SR.InvalidArgument.
Referenced by System.Transactions.TransactionInterop.GetTransactionFromTransmitterPropagationToken(), and System.Transactions.TransactionStatePSPEOperation.PSPEPromote().