Terraria: System.Transactions.TransactionInterop.GetTransmitterPropagationToken
GetTransmitterPropagationToken()
static byte[] System.Transactions.TransactionInterop.GetTransmitterPropagationToken (Transaction transaction) inline static
Definition at line 94 of file TransactionInterop.cs.
    {
        if (null == transaction)
        {
            throw new ArgumentNullException("transaction");
        }
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceDistributed, "TransactionInterop.GetTransmitterPropagationToken");
        }
        DistributedTransaction distributedTransaction = ConvertToDistributedTransaction(transaction);
        byte[] transmitterPropagationToken = distributedTransaction.GetTransmitterPropagationToken();
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceDistributed, "TransactionInterop.GetTransmitterPropagationToken");
        }
        return transmitterPropagationToken;
    }
References System.Transactions.TransactionInterop.ConvertToDistributedTransaction(), System.Transactions.Distributed.DistributedTransaction.GetTransmitterPropagationToken(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), and System.Transactions.TransactionsEtwProvider.MethodExit().