Terraria: System.Transactions.TransactionInterop.GetExportCookie
GetExportCookie()
static byte[] System.Transactions.TransactionInterop.GetExportCookie (Transaction transaction, byte[] whereabouts) inline static
Definition at line 31 of file TransactionInterop.cs.
    {
        if (null == transaction)
        {
            throw new ArgumentNullException("transaction");
        }
        if (whereabouts == null)
        {
            throw new ArgumentNullException("whereabouts");
        }
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceDistributed, "TransactionInterop.GetExportCookie");
        }
        byte[] array = new byte[whereabouts.Length];
        Buffer.BlockCopy(whereabouts, 0, array, 0, whereabouts.Length);
        DistributedTransaction distributedTransaction = ConvertToDistributedTransaction(transaction);
        byte[] exportCookie = distributedTransaction.GetExportCookie(array);
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceDistributed, "TransactionInterop.GetExportCookie");
        }
        return exportCookie;
    }
References System.array, System.Buffer.BlockCopy(), System.Transactions.TransactionInterop.ConvertToDistributedTransaction(), System.Transactions.Distributed.DistributedTransaction.GetExportCookie(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionsEtwProvider.MethodEnter(), and System.Transactions.TransactionsEtwProvider.MethodExit().