Terraria: Terraria.Cinematics.DSTFilm.FindFloorAt
FindFloorAt()
static void Terraria.Cinematics.DSTFilm.FindFloorAt (Vector2 position, out int x, out int y) inline static private
Definition at line 168 of file DSTFilm.cs.
    {
        x = (int)position.X;
        y = (int)position.Y;
        int i = x / 16;
        int j;
        for (j = y / 16; !WorldGen.SolidTile(i, j); j++)
        {
        }
        y = j * 16;
    }
References Terraria.WorldGen.SolidTile().
Referenced by Terraria.Cinematics.DSTFilm.ControlPlayer(), Terraria.Cinematics.DSTFilm.CreateChester(), and Terraria.Cinematics.DSTFilm.PlaceNPCOnGround().