Terraria: Terraria.Cinematics.DSTFilm.BuildSequence
BuildSequence()
void Terraria.Cinematics.DSTFilm.BuildSequence () inline private
Definition at line 35 of file DSTFilm.cs.
    {
        AppendKeyFrames(EquipDSTShaderItem);
        AppendEmptySequence(60);
        AppendKeyFrames(CreateDeerclops, CreateChester, ControlPlayer);
        AppendEmptySequence(60);
        AppendEmptySequence(187);
        AppendKeyFrames(StopBeforeCliff);
        AppendEmptySequence(20);
        AppendKeyFrames(TurnPlayerToTheLeft);
        AppendEmptySequence(20);
        AppendKeyFrames(DeerclopsAttack);
        AppendEmptySequence(60);
        AppendKeyFrames(RemoveDSTShaderItem);
    }
References Terraria.Cinematics.Film.AppendEmptySequence(), Terraria.Cinematics.Film.AppendKeyFrames(), Terraria.Cinematics.DSTFilm.ControlPlayer(), Terraria.Cinematics.DSTFilm.CreateChester(), Terraria.Cinematics.DSTFilm.CreateDeerclops(), Terraria.Cinematics.DSTFilm.DeerclopsAttack(), Terraria.Cinematics.DSTFilm.EquipDSTShaderItem(), Terraria.Cinematics.DSTFilm.RemoveDSTShaderItem(), Terraria.Cinematics.DSTFilm.StopBeforeCliff(), and Terraria.Cinematics.DSTFilm.TurnPlayerToTheLeft().
Referenced by Terraria.Cinematics.DSTFilm.DSTFilm().