Terraria: System.Transactions.Transaction.Rollback
Rollback() [1/2]
void System.Transactions.Transaction.Rollback () inline inherited
Definition at line 400 of file Transaction.cs.
    {
        TransactionsEtwProvider log = TransactionsEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.MethodEnter(TraceSourceType.TraceSourceLtm, this, "Rollback");
            log.TransactionRollback(this, "Transaction");
        }
        if (Disposed)
        {
            throw new ObjectDisposedException("Transaction");
        }
        lock (_internalTransaction)
        {
            _internalTransaction.State.Rollback(_internalTransaction, null);
        }
        if (log.IsEnabled())
        {
            log.MethodExit(TraceSourceType.TraceSourceLtm, this, "Rollback");
        }
    }
References System.Transactions.Transaction._internalTransaction, System.Runtime.Serialization.Dictionary, System.Transactions.Transaction.Disposed, System.Transactions.TransactionsEtwProvider.Log, System.Transactions.TransactionState.Rollback(), and System.Transactions.InternalTransaction.State.
Referenced by System.Transactions.TransactionScope.Dispose(), System.Transactions.TransactionScope.InternalDispose(), and System.Transactions.TransactionScope.Timeout().