Terraria: System.Transactions.Transaction.FastGetTransaction
FastGetTransaction()
static Transaction System.Transactions.Transaction.FastGetTransaction (TransactionScope currentScope, ContextData contextData, out Transaction contextTransaction) inline static package inherited
Definition at line 196 of file Transaction.cs.
    {
        Transaction transaction = null;
        contextTransaction = null;
        contextTransaction = contextData.CurrentTransaction;
        switch (InteropMode(currentScope))
        {
        case EnterpriseServicesInteropOption.None:
            transaction = contextTransaction;
            if (transaction == null && currentScope == null)
            {
                transaction = ((!TransactionManager.s_currentDelegateSet) ? EnterpriseServices.GetContextTransaction(contextData) : TransactionManager.s_currentDelegate());
            }
            break;
        case EnterpriseServicesInteropOption.Full:
            transaction = EnterpriseServices.GetContextTransaction(contextData);
            break;
        case EnterpriseServicesInteropOption.Automatic:
            if (EnterpriseServices.UseServiceDomainForCurrent())
            {
            }
            transaction = contextData.CurrentTransaction;
            break;
        }
        return transaction;
    }
References System.Runtime.Serialization.Dictionary, System.Transactions.EnterpriseServices.GetContextTransaction(), System.Transactions.Transaction.InteropMode(), System.Transactions.TransactionManager.s_currentDelegate, System.Transactions.TransactionManager.s_currentDelegateSet, and System.Transactions.EnterpriseServices.UseServiceDomainForCurrent().
Referenced by System.Transactions.TransactionScope.Dispose(), and System.Transactions.Transaction.GetCurrentTransactionAndScope().