Terraria: System.Transactions.Transaction.Equals
Equals()
override bool System.Transactions.Transaction.Equals ([NotNullWhen(true)] object? obj) inline inherited
Definition at line 280 of file Transaction.cs.
    {
        if (obj is Transaction transaction)
        {
            return _internalTransaction.TransactionHash == transaction._internalTransaction.TransactionHash;
        }
        return false;
    }
References System.Runtime.Serialization.Dictionary, and System.obj.
Referenced by System.Transactions.TransactionScope.Dispose(), System.Transactions.Transaction.operator!=(), and System.Transactions.Transaction.operator==().