Terraria: System.Transactions.Transaction.Promote
Promote()
DistributedTransaction System.Transactions.Transaction.Promote () inline package inherited
Definition at line 720 of file Transaction.cs.
    {
        lock (_internalTransaction)
        {
            _internalTransaction.ThrowIfPromoterTypeIsNotMSDTC();
            _internalTransaction.State.Promote(_internalTransaction);
            return _internalTransaction.PromotedTransaction;
        }
    }
References System.Transactions.Transaction._internalTransaction, System.Runtime.Serialization.Dictionary, System.Transactions.TransactionState.Promote(), System.Transactions.InternalTransaction.PromotedTransaction, System.Transactions.InternalTransaction.State, and System.Transactions.InternalTransaction.ThrowIfPromoterTypeIsNotMSDTC().
Referenced by System.Transactions.TransactionInterop.ConvertToDistributedTransaction().