Terraria: IItemDropRuleCondition.CanDrop
CanDrop()
bool IItemDropRuleCondition.CanDrop (DropAttemptInfo info)
Implemented in Conditions.DontStarveIsNotUp, Conditions.DontStarveIsUp, Conditions.TenthAnniversaryIsNotUp, Conditions.TenthAnniversaryIsUp, Conditions.NotRemixSeed, Conditions.RemixSeed, Conditions.RemixSeedHardmode, Conditions.RemixSeedEasymode, Conditions.WindyEnoughForKiteDrops, Conditions.YoyosHelFire, Conditions.YoyosKraken, Conditions.YoyosYelets, Conditions.YoyosAmarok, Conditions.YoyoCascade, Conditions.BeatAnyMechBoss, Conditions.DesertKeyCondition, Conditions.FrozenKeyCondition, Conditions.CrimsonKeyCondition, Conditions.CorruptKeyCondition, Conditions.JungleKeyCondition, Conditions.HallowKeyCondition, Conditions.NamedNPC, Conditions.LivingFlames, Conditions.XmasPresentDrop, Conditions.HalloweenGoodieBagDrop, Conditions.NotFromStatue, Conditions.SoulOfLight, Conditions.SoulOfNight, Conditions.HalloweenWeapons, Conditions.IsCorruptionAndNotExpert, Conditions.IsCrimsonAndNotExpert, Conditions.IsCorruption, Conditions.IsCrimson, Conditions.IsMasterMode, Conditions.IsExpert, Conditions.LegacyHack_IsABoss, Conditions.LegacyHack_IsBossAndNotExpert, Conditions.LegacyHack_IsBossAndExpert, Conditions.MechdusaKill, Conditions.PlayerNeedsHealing, Conditions.EmpressOfLightIsGenuinelyEnraged, Conditions.MissingTwin, Conditions.NotMasterMode, Conditions.NotExpert, Conditions.IsChristmas, Conditions.PirateMap, Conditions.MechanicalBossesDummyCondition, Conditions.FirstTimeKillingPlantera, Conditions.IsHardmode, Conditions.DownedPlantera, Conditions.DownedAllMechBosses, Conditions.IsBloodMoonAndNotFromStatue, Conditions.FromCertainWaveAndAbove, Conditions.IsPumpkinMoon, Conditions.PumpkinMoonDropGateForTrophies, Conditions.FrostMoonDropGateForTrophies, Conditions.PumpkinMoonDropGatingChance, Conditions.FrostMoonDropGatingChance, Conditions.IsUsingSpecificAIValues, and Conditions.NeverTrue.
Referenced by DropLocalPerClientAndResetsNPCMoneyTo0.CanDrop(), DropPerPlayerOnThePlayer.CanDrop(), ItemDropWithConditionRule.CanDrop(), and LeadingConditionRule.CanDrop().