Terraria: System.Linq.CachingComparerWithChild.Compare
Compare()
override int System.Linq.CachingComparerWithChild< TElement, TKey >.Compare (TElement element, bool cacheLower) inline package
Definition at line 15 of file CachingComparerWithChild.cs.
    {
        TKey val = _keySelector(element);
        int num = (_descending ? _comparer.Compare(_lastKey, val) : _comparer.Compare(val, _lastKey));
        if (num == 0)
        {
            return _child.Compare(element, cacheLower);
        }
        if (cacheLower == num < 0)
        {
            _lastKey = val;
            _child.SetElement(element);
        }
        return num;
    }
References System.Linq.CachingComparerWithChild< TElement, TKey >._child, System.Linq.CachingComparer< TElement, TKey >._comparer, System.Linq.CachingComparer< TElement, TKey >._descending, System.Linq.CachingComparer< TElement, TKey >._keySelector, System.Linq.CachingComparer< TElement, TKey >._lastKey, System.Collections.Generic.IComparer< in T >.Compare(), System.Linq.CachingComparer< TElement, TKey >.Compare(), and System.Linq.CachingComparer< TElement, TKey >.SetElement().