Terraria: System.Reflection.Emit.ILGenerator.GetExceptions
GetExceptions()
__ExceptionInfo[] System.Reflection.Emit.ILGenerator.GetExceptions () inline package
Definition at line 180 of file ILGenerator.cs.
    {
        if (m_currExcStackCount != 0)
        {
            throw new NotSupportedException(SR.Argument_UnclosedExceptionBlock);
        }
        if (m_exceptionCount == 0)
        {
            return null;
        }
        __ExceptionInfo[] array = new __ExceptionInfo[m_exceptionCount];
        Array.Copy(m_exceptions, array, m_exceptionCount);
        SortExceptions(array);
        return array;
    }
References System.SR.Argument_UnclosedExceptionBlock, System.array, System.Array.Copy(), System.Reflection.Emit.ILGenerator.m_currExcStackCount, System.Reflection.Emit.ILGenerator.m_exceptionCount, System.Reflection.Emit.ILGenerator.m_exceptions, and System.Reflection.Emit.ILGenerator.SortExceptions().
Referenced by System.Reflection.Emit.DynamicResolver.DynamicResolver(), and System.Reflection.Emit.MethodBuilder.CreateMethodBodyHelper().