Terraria: System.Reflection.Emit.ILGenerator.BakeByteArray
BakeByteArray()
byte[] System.Reflection.Emit.ILGenerator.BakeByteArray () inline package
Definition at line 148 of file ILGenerator.cs.
    {
        if (m_currExcStackCount != 0)
        {
            throw new ArgumentException(SR.Argument_UnclosedExceptionBlock);
        }
        if (m_length == 0)
        {
            return null;
        }
        byte[] array = new byte[m_length];
        Array.Copy(m_ILStream, array, m_length);
        for (int i = 0; i < m_fixupCount; i++)
        {
            __FixupData _FixupData = m_fixupData[i];
            int num = GetLabelPos(_FixupData.m_fixupLabel) - (_FixupData.m_fixupPos + _FixupData.m_fixupInstSize);
            if (_FixupData.m_fixupInstSize == 1)
            {
                if (num < -128 || num > 127)
                {
                    throw new NotSupportedException(SR.Format(SR.NotSupported_IllegalOneByteBranch, _FixupData.m_fixupPos, num));
                }
                array[_FixupData.m_fixupPos] = (byte)num;
            }
            else
            {
                BinaryPrimitives.WriteInt32LittleEndian(array.AsSpan(_FixupData.m_fixupPos), num);
            }
        }
        return array;
    }
References System.SR.Argument_UnclosedExceptionBlock, System.array, System.Array.Copy(), System.SR.Format(), System.Reflection.Emit.ILGenerator.GetLabelPos(), System.Reflection.Emit.ILGenerator.m_currExcStackCount, System.Reflection.Emit.ILGenerator.m_fixupCount, System.Reflection.Emit.ILGenerator.m_fixupData, System.Reflection.Emit.__FixupData.m_fixupInstSize, System.Reflection.Emit.__FixupData.m_fixupLabel, System.Reflection.Emit.__FixupData.m_fixupPos, System.Reflection.Emit.ILGenerator.m_ILStream, System.Reflection.Emit.ILGenerator.m_length, System.SR.NotSupported_IllegalOneByteBranch, and System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian().
Referenced by System.Reflection.Emit.DynamicResolver.DynamicResolver(), and System.Reflection.Emit.MethodBuilder.CreateMethodBodyHelper().