Terraria: System.Reflection.Emit.ILGenerator.EnsureCapacity
EnsureCapacity()
void System.Reflection.Emit.ILGenerator.EnsureCapacity (int size) inline package
Definition at line 196 of file ILGenerator.cs.
    {
        if (m_length + size >= m_ILStream.Length)
        {
            IncreaseCapacity(size);
        }
    }
References System.Reflection.Emit.ILGenerator.IncreaseCapacity(), System.Reflection.Emit.ILGenerator.m_ILStream, and System.Reflection.Emit.ILGenerator.m_length.
Referenced by System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.EmitCall(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Reflection.Emit.DynamicILGenerator.EmitCalli(), System.Reflection.Emit.ILGenerator.EmitCalli(), System.Reflection.Emit.DynamicILGenerator.EmitCalli(), and System.Reflection.Emit.ILGenerator.EmitCalli().