Terraria: System.Reflection.Emit.ILGenerator.UsingNamespace
UsingNamespace()
virtual void System.Reflection.Emit.ILGenerator.UsingNamespace (string usingNamespace) inline virtual
Reimplemented in System.Reflection.Emit.DynamicILGenerator.
Definition at line 1026 of file ILGenerator.cs.
    {
        if (usingNamespace == null)
        {
            throw new ArgumentNullException("usingNamespace");
        }
        if (usingNamespace.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyName, "usingNamespace");
        }
        MethodBuilder methodBuilder = m_methodBuilder as MethodBuilder;
        if (methodBuilder == null)
        {
            throw new NotSupportedException();
        }
        int currentActiveScopeIndex = methodBuilder.GetILGenerator().m_ScopeTree.GetCurrentActiveScopeIndex();
        if (currentActiveScopeIndex == -1)
        {
            methodBuilder.m_localSymInfo.AddUsingNamespace(usingNamespace);
        }
        else
        {
            m_ScopeTree.AddUsingNamespaceToCurrentScope(usingNamespace);
        }
    }
References System.Reflection.Emit.LocalSymInfo.AddUsingNamespace(), System.Reflection.Emit.ScopeTree.AddUsingNamespaceToCurrentScope(), System.SR.Argument_EmptyName, System.Reflection.Emit.ScopeTree.GetCurrentActiveScopeIndex(), System.Reflection.Emit.MethodBuilder.GetILGenerator(), System.Reflection.Emit.MethodBuilder.m_localSymInfo, System.Reflection.Emit.ILGenerator.m_methodBuilder, and System.Reflection.Emit.ILGenerator.m_ScopeTree.