Terraria: System.Reflection.Emit.ILGenerator.RecordTokenFixup
RecordTokenFixup()
virtual void System.Reflection.Emit.ILGenerator.RecordTokenFixup () inline package virtual
Reimplemented in System.Reflection.Emit.DynamicILGenerator.
Definition at line 80 of file ILGenerator.cs.
    {
        if (m_RelocFixupList == null)
        {
            m_RelocFixupList = new int[8];
        }
        else if (m_RelocFixupList.Length <= m_RelocFixupCount)
        {
            m_RelocFixupList = EnlargeArray(m_RelocFixupList);
        }
        m_RelocFixupList[m_RelocFixupCount++] = m_length;
    }
References System.Reflection.Emit.ILGenerator.m_length, System.Reflection.Emit.ILGenerator.m_RelocFixupCount, and System.Reflection.Emit.ILGenerator.m_RelocFixupList.
Referenced by System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Reflection.Emit.ILGenerator.EmitCalli(), and System.Reflection.Emit.ILGenerator.EmitCalli().