Terraria: System.Reflection.Emit.ILGenerator.EndExceptionBlock
EndExceptionBlock()
virtual void System.Reflection.Emit.ILGenerator.EndExceptionBlock () inline virtual
Definition at line 783 of file ILGenerator.cs.
    {
        if (m_currExcStackCount == 0)
        {
            throw new NotSupportedException(SR.Argument_NotInExceptionBlock);
        }
        __ExceptionInfo _ExceptionInfo = m_currExcStack[m_currExcStackCount - 1];
        m_currExcStack[--m_currExcStackCount] = null;
        Label endLabel = _ExceptionInfo.GetEndLabel();
        switch (_ExceptionInfo.GetCurrentState())
        {
        case 0:
        case 1:
            throw new InvalidOperationException(SR.Argument_BadExceptionCodeGen);
        case 2:
            Emit(OpCodes.Leave, endLabel);
            break;
        case 3:
        case 4:
            Emit(OpCodes.Endfinally);
            break;
        }
        Label loc = ((m_labelList[endLabel.GetLabelValue()] != -1) ? _ExceptionInfo.m_finallyEndLabel : endLabel);
        MarkLabel(loc);
        _ExceptionInfo.Done(m_length);
    }
References System.SR.Argument_BadExceptionCodeGen, System.SR.Argument_NotInExceptionBlock, System.Reflection.Emit.__ExceptionInfo.Done(), System.Reflection.Emit.OpCodes.Endfinally, System.Reflection.Emit.__ExceptionInfo.GetCurrentState(), System.Reflection.Emit.__ExceptionInfo.GetEndLabel(), System.Reflection.Emit.Label.GetLabelValue(), System.Reflection.Emit.OpCodes.Leave, System.Reflection.Emit.ILGenerator.m_currExcStack, System.Reflection.Emit.ILGenerator.m_currExcStackCount, System.Reflection.Emit.__ExceptionInfo.m_finallyEndLabel, System.Reflection.Emit.ILGenerator.m_labelList, System.Reflection.Emit.ILGenerator.m_length, and System.Reflection.Emit.ILGenerator.MarkLabel().
Referenced by System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression(), and System.Xml.Serialization.CodeGenerator.EndExceptionBlock().