Terraria: System.Reflection.Emit.ILGenerator.Emit
Emit() [3/17]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode, ConstructorInfo con) inline virtual
Reimplemented in System.Reflection.Emit.DynamicILGenerator.
Definition at line 562 of file ILGenerator.cs.
    {
        if (con == null)
        {
            throw new ArgumentNullException("con");
        }
        int num = 0;
        int methodToken = GetMethodToken(con, null, useMethodDef: true);
        EnsureCapacity(7);
        InternalEmit(opcode);
        if (opcode.StackBehaviourPush == StackBehaviour.Varpush)
        {
            num++;
        }
        if (opcode.StackBehaviourPop == StackBehaviour.Varpop)
        {
            Type[] parameterTypes = con.GetParameterTypes();
            if (parameterTypes != null)
            {
                num -= parameterTypes.Length;
            }
        }
        UpdateStackSize(opcode, num);
        RecordTokenFixup();
        PutInteger4(methodToken);
    }
References System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.ILGenerator.GetMethodToken(), System.Reflection.MethodBase.GetParameterTypes(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.Reflection.Emit.ILGenerator.PutInteger4(), System.Reflection.Emit.ILGenerator.RecordTokenFixup(), System.Reflection.Emit.OpCode.StackBehaviourPop, System.Reflection.Emit.OpCode.StackBehaviourPush, and System.Reflection.Emit.ILGenerator.UpdateStackSize().