Terraria: System.Reflection.Emit.ILGenerator.BeginExceptFilterBlock
BeginExceptFilterBlock()
virtual void System.Reflection.Emit.ILGenerator.BeginExceptFilterBlock () inline virtual
Reimplemented in System.Reflection.Emit.DynamicILGenerator.
Definition at line 810 of file ILGenerator.cs.
    {
        if (m_currExcStackCount == 0)
        {
            throw new NotSupportedException(SR.Argument_NotInExceptionBlock);
        }
        __ExceptionInfo _ExceptionInfo = m_currExcStack[m_currExcStackCount - 1];
        Emit(OpCodes.Leave, _ExceptionInfo.GetEndLabel());
        _ExceptionInfo.MarkFilterAddr(m_length);
    }
References System.SR.Argument_NotInExceptionBlock, System.Reflection.Emit.__ExceptionInfo.GetEndLabel(), System.Reflection.Emit.OpCodes.Leave, System.Reflection.Emit.ILGenerator.m_currExcStack, System.Reflection.Emit.ILGenerator.m_currExcStackCount, System.Reflection.Emit.ILGenerator.m_length, and System.Reflection.Emit.__ExceptionInfo.MarkFilterAddr().
Referenced by System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression().