Terraria: System.Reflection.Emit.ILGenerator.MarkLabel
MarkLabel()
virtual void System.Reflection.Emit.ILGenerator.MarkLabel (Label loc) inline virtual
Definition at line 898 of file ILGenerator.cs.
    {
        int labelValue = loc.GetLabelValue();
        if (m_labelList == null || labelValue < 0 || labelValue >= m_labelList.Length)
        {
            throw new ArgumentException(SR.Argument_InvalidLabel);
        }
        if (m_labelList[labelValue] != -1)
        {
            throw new ArgumentException(SR.Argument_RedefinedLabel);
        }
        m_labelList[labelValue] = m_length;
    }
References System.SR.Argument_InvalidLabel, System.SR.Argument_RedefinedLabel, System.Reflection.Emit.Label.GetLabelValue(), System.Reflection.Emit.ILGenerator.m_labelList, and System.Reflection.Emit.ILGenerator.m_length.
Referenced by System.Reflection.Emit.ILGenerator.BeginFinallyBlock(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConditionalExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanOr(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedToNullRelational(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBucket(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchCases(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedOrElse(), System.Reflection.Emit.ILGenerator.EndExceptionBlock(), System.Xml.Serialization.CodeGenerator.EndExceptionBlock(), System.Text.RegularExpressions.RegexCompiler.MarkLabel(), System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), and System.Linq.Expressions.Compiler.LabelInfo.MarkWithEmptyStack().