Terraria: System.Reflection.Emit.ILGenerator.IncreaseCapacity
IncreaseCapacity()
void System.Reflection.Emit.ILGenerator.IncreaseCapacity (int size) inline private
Definition at line 204 of file ILGenerator.cs.
    {
        byte[] array = new byte[Math.Max(m_ILStream.Length * 2, m_length + size)];
        Array.Copy(m_ILStream, array, m_ILStream.Length);
        m_ILStream = array;
    }
References System.array, System.Array.Copy(), System.Reflection.Emit.ILGenerator.m_ILStream, System.Reflection.Emit.ILGenerator.m_length, and System.Math.Max().
Referenced by System.Reflection.Emit.ILGenerator.EnsureCapacity().