Terraria: System.Reflection.Emit.ILGenerator.UpdateStackSize
UpdateStackSize()
void System.Reflection.Emit.ILGenerator.UpdateStackSize (OpCode opcode, int stackchange) inline package
Definition at line 109 of file ILGenerator.cs.
    {
        m_maxMidStackCur += stackchange;
        if (m_maxMidStackCur > m_maxMidStack)
        {
            m_maxMidStack = m_maxMidStackCur;
        }
        else if (m_maxMidStackCur < 0)
        {
            m_maxMidStackCur = 0;
        }
        if (opcode.EndsUncondJmpBlk())
        {
            m_maxStackSize += m_maxMidStack;
            m_maxMidStack = 0;
            m_maxMidStackCur = 0;
        }
    }
References System.Reflection.Emit.OpCode.EndsUncondJmpBlk(), System.Reflection.Emit.ILGenerator.m_maxMidStack, System.Reflection.Emit.ILGenerator.m_maxMidStackCur, and System.Reflection.Emit.ILGenerator.m_maxStackSize.
Referenced by System.Reflection.Emit.DynamicILGenerator.BeginCatchBlock(), System.Reflection.Emit.DynamicILGenerator.BeginExceptFilterBlock(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.EmitCall(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Reflection.Emit.DynamicILGenerator.EmitCalli(), System.Reflection.Emit.ILGenerator.EmitCalli(), System.Reflection.Emit.DynamicILGenerator.EmitCalli(), System.Reflection.Emit.ILGenerator.EmitCalli(), and System.Reflection.Emit.ILGenerator.InternalEmit().