Terraria: System.Reflection.Emit.ILGenerator.EmitCalli
EmitCalli() [1/2]
virtual void System.Reflection.Emit.ILGenerator.EmitCalli (OpCode opcode, CallingConvention unmanagedCallConv, Type? returnType, Type?[] parameterTypes) inline virtual
Definition at line 471 of file ILGenerator.cs.
    {
        int num = 0;
        int num2 = 0;
        ModuleBuilder moduleBuilder = (ModuleBuilder)m_methodBuilder.Module;
        if (parameterTypes != null)
        {
            num2 = parameterTypes.Length;
        }
        SignatureHelper methodSigHelper = SignatureHelper.GetMethodSigHelper(moduleBuilder, unmanagedCallConv, returnType);
        if (parameterTypes != null)
        {
            for (int i = 0; i < num2; i++)
            {
                methodSigHelper.AddArgument(parameterTypes[i]);
            }
        }
        if (returnType != typeof(void))
        {
            num++;
        }
        if (parameterTypes != null)
        {
            num -= num2;
        }
        num--;
        UpdateStackSize(OpCodes.Calli, num);
        EnsureCapacity(7);
        Emit(OpCodes.Calli);
        RecordTokenFixup();
        PutInteger4(moduleBuilder.GetSignatureToken(methodSigHelper));
    }
References System.Reflection.Emit.SignatureHelper.AddArgument(), System.Reflection.Emit.OpCodes.Calli, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.ModuleBuilder.GetSignatureToken(), System.Reflection.Emit.ILGenerator.m_methodBuilder, System.Reflection.MemberInfo.Module, System.Reflection.Emit.ILGenerator.PutInteger4(), System.Reflection.Emit.ILGenerator.RecordTokenFixup(), and System.Reflection.Emit.ILGenerator.UpdateStackSize().