Terraria: System.Reflection.Emit.ILGenerator.Emit
Emit() [7/17]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode, int arg) inline virtual
Definition at line 313 of file ILGenerator.cs.
    {
        if (opcode.Equals(OpCodes.Ldc_I4))
        {
            OpCode opCode;
            switch (arg)
            {
            case -1:
                opCode = OpCodes.Ldc_I4_M1;
                goto IL_009b;
            case 0:
                opCode = OpCodes.Ldc_I4_0;
                goto IL_009b;
            case 1:
                opCode = OpCodes.Ldc_I4_1;
                goto IL_009b;
            case 2:
                opCode = OpCodes.Ldc_I4_2;
                goto IL_009b;
            case 3:
                opCode = OpCodes.Ldc_I4_3;
                goto IL_009b;
            case 4:
                opCode = OpCodes.Ldc_I4_4;
                goto IL_009b;
            case 5:
                opCode = OpCodes.Ldc_I4_5;
                goto IL_009b;
            case 6:
                opCode = OpCodes.Ldc_I4_6;
                goto IL_009b;
            case 7:
                opCode = OpCodes.Ldc_I4_7;
                goto IL_009b;
            case 8:
                {
                    opCode = OpCodes.Ldc_I4_8;
                    goto IL_009b;
                }
                IL_009b:
                opcode = opCode;
                Emit(opcode);
                return;
            }
            if (arg >= -128 && arg <= 127)
            {
                Emit(OpCodes.Ldc_I4_S, (sbyte)arg);
                return;
            }
        }
        else if (opcode.Equals(OpCodes.Ldarg))
        {
            if ((uint)arg <= 3u)
            {
                Emit(arg switch
                {
                    0 => OpCodes.Ldarg_0,
                    1 => OpCodes.Ldarg_1,
                    2 => OpCodes.Ldarg_2,
                    _ => OpCodes.Ldarg_3,
                });
                return;
            }
            if ((uint)arg <= 255u)
            {
                Emit(OpCodes.Ldarg_S, (byte)arg);
                return;
            }
            if ((uint)arg <= 65535u)
            {
                Emit(OpCodes.Ldarg, (short)arg);
                return;
            }
        }
        else if (opcode.Equals(OpCodes.Ldarga))
        {
            if ((uint)arg <= 255u)
            {
                Emit(OpCodes.Ldarga_S, (byte)arg);
                return;
            }
            if ((uint)arg <= 65535u)
            {
                Emit(OpCodes.Ldarga, (short)arg);
                return;
            }
        }
        else if (opcode.Equals(OpCodes.Starg))
        {
            if ((uint)arg <= 255u)
            {
                Emit(OpCodes.Starg_S, (byte)arg);
                return;
            }
            if ((uint)arg <= 65535u)
            {
                Emit(OpCodes.Starg, (short)arg);
                return;
            }
        }
        EnsureCapacity(7);
        InternalEmit(opcode);
        PutInteger4(arg);
    }
References System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.OpCode.Equals(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.Reflection.Emit.OpCodes.Ldarg, System.Reflection.Emit.OpCodes.Ldarg_0, System.Reflection.Emit.OpCodes.Ldarg_1, System.Reflection.Emit.OpCodes.Ldarg_2, System.Reflection.Emit.OpCodes.Ldarg_3, System.Reflection.Emit.OpCodes.Ldarg_S, System.Reflection.Emit.OpCodes.Ldarga, System.Reflection.Emit.OpCodes.Ldarga_S, System.Reflection.Emit.OpCodes.Ldc_I4, System.Reflection.Emit.OpCodes.Ldc_I4_0, System.Reflection.Emit.OpCodes.Ldc_I4_1, System.Reflection.Emit.OpCodes.Ldc_I4_2, System.Reflection.Emit.OpCodes.Ldc_I4_3, System.Reflection.Emit.OpCodes.Ldc_I4_4, System.Reflection.Emit.OpCodes.Ldc_I4_5, System.Reflection.Emit.OpCodes.Ldc_I4_6, System.Reflection.Emit.OpCodes.Ldc_I4_7, System.Reflection.Emit.OpCodes.Ldc_I4_8, System.Reflection.Emit.OpCodes.Ldc_I4_M1, System.Reflection.Emit.OpCodes.Ldc_I4_S, System.Reflection.Emit.ILGenerator.PutInteger4(), System.Reflection.Emit.OpCodes.Starg, and System.Reflection.Emit.OpCodes.Starg_S.