Terraria: System.Reflection.Emit.ILGenerator.DeclareLocal
DeclareLocal() [1/2]
virtual LocalBuilder System.Reflection.Emit.ILGenerator.DeclareLocal (Type localType) inline virtual
Definition at line 998 of file ILGenerator.cs.
    {
        return DeclareLocal(localType, pinned: false);
    }
References System.Reflection.Emit.ILGenerator.DeclareLocal().
Referenced by System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Text.RegularExpressions.RegexCompiler.DeclareInt32(), System.Text.RegularExpressions.RegexCompiler.DeclareInt32Array(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Reflection.Emit.ILGenerator.DeclareLocal(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Text.RegularExpressions.RegexCompiler.DeclareReadOnlySpanChar(), System.Text.RegularExpressions.RegexCompiler.DeclareString(), System.Text.RegularExpressions.RegexCompiler.DeclareTextInfo(), System.Linq.Expressions.Compiler.LabelInfo.EnsureLabelAndValue(), and System.Linq.Expressions.Compiler.LambdaCompiler.GetLocal().