Terraria: System.Reflection.Emit.ILGenerator.Emit
Emit() [10/17]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode, LocalBuilder local) inline virtual
Definition at line 676 of file ILGenerator.cs.
    {
        if (local == null)
        {
            throw new ArgumentNullException("local");
        }
        int localIndex = local.GetLocalIndex();
        if (local.GetMethodBuilder() != m_methodBuilder)
        {
            throw new ArgumentException(SR.Argument_UnmatchedMethodForLocal, "local");
        }
        if (opcode.Equals(OpCodes.Ldloc))
        {
            switch (localIndex)
            {
            case 0:
                opcode = OpCodes.Ldloc_0;
                break;
            case 1:
                opcode = OpCodes.Ldloc_1;
                break;
            case 2:
                opcode = OpCodes.Ldloc_2;
                break;
            case 3:
                opcode = OpCodes.Ldloc_3;
                break;
            default:
                if (localIndex <= 255)
                {
                    opcode = OpCodes.Ldloc_S;
                }
                break;
            }
        }
        else if (opcode.Equals(OpCodes.Stloc))
        {
            switch (localIndex)
            {
            case 0:
                opcode = OpCodes.Stloc_0;
                break;
            case 1:
                opcode = OpCodes.Stloc_1;
                break;
            case 2:
                opcode = OpCodes.Stloc_2;
                break;
            case 3:
                opcode = OpCodes.Stloc_3;
                break;
            default:
                if (localIndex <= 255)
                {
                    opcode = OpCodes.Stloc_S;
                }
                break;
            }
        }
        else if (opcode.Equals(OpCodes.Ldloca) && localIndex <= 255)
        {
            opcode = OpCodes.Ldloca_S;
        }
        EnsureCapacity(7);
        InternalEmit(opcode);
        if (opcode.OperandType == OperandType.InlineNone)
        {
            return;
        }
        if (!OpCodes.TakesSingleByteArgument(opcode))
        {
            BinaryPrimitives.WriteInt16LittleEndian(m_ILStream.AsSpan(m_length), (short)localIndex);
            m_length += 2;
            return;
        }
        if (localIndex > 255)
        {
            throw new InvalidOperationException(SR.InvalidOperation_BadInstructionOrIndexOutOfBound);
        }
        m_ILStream[m_length++] = (byte)localIndex;
    }
References System.SR.Argument_UnmatchedMethodForLocal, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.OpCode.Equals(), System.Reflection.Emit.LocalBuilder.GetLocalIndex(), System.Reflection.Emit.LocalBuilder.GetMethodBuilder(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.SR.InvalidOperation_BadInstructionOrIndexOutOfBound, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldloc_0, System.Reflection.Emit.OpCodes.Ldloc_1, System.Reflection.Emit.OpCodes.Ldloc_2, System.Reflection.Emit.OpCodes.Ldloc_3, System.Reflection.Emit.OpCodes.Ldloc_S, System.Reflection.Emit.OpCodes.Ldloca, System.Reflection.Emit.OpCodes.Ldloca_S, System.Reflection.Emit.ILGenerator.m_ILStream, System.Reflection.Emit.ILGenerator.m_length, System.Reflection.Emit.ILGenerator.m_methodBuilder, System.Reflection.Emit.OpCode.OperandType, System.Reflection.Emit.OpCodes.Stloc, System.Reflection.Emit.OpCodes.Stloc_0, System.Reflection.Emit.OpCodes.Stloc_1, System.Reflection.Emit.OpCodes.Stloc_2, System.Reflection.Emit.OpCodes.Stloc_3, System.Reflection.Emit.OpCodes.Stloc_S, System.Reflection.Emit.OpCodes.TakesSingleByteArgument(), and System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian().