Terraria: System.Reflection.Emit.ILGenerator.EmitCall
EmitCall()
virtual void System.Reflection.Emit.ILGenerator.EmitCall (OpCode opcode, MethodInfo methodInfo, Type?[] optionalParameterTypes) inline virtual
Definition at line 504 of file ILGenerator.cs.
    {
        if (methodInfo == null)
        {
            throw new ArgumentNullException("methodInfo");
        }
        if (!opcode.Equals(OpCodes.Call) && !opcode.Equals(OpCodes.Callvirt) && !opcode.Equals(OpCodes.Newobj))
        {
            throw new ArgumentException(SR.Argument_NotMethodCallOpcode, "opcode");
        }
        int num = 0;
        int methodToken = GetMethodToken(methodInfo, optionalParameterTypes, useMethodDef: false);
        EnsureCapacity(7);
        InternalEmit(opcode);
        if (methodInfo.ReturnType != typeof(void))
        {
            num++;
        }
        Type[] parameterTypes = methodInfo.GetParameterTypes();
        if (parameterTypes != null)
        {
            num -= parameterTypes.Length;
        }
        if (!(methodInfo is SymbolMethod) && !methodInfo.IsStatic && !opcode.Equals(OpCodes.Newobj))
        {
            num--;
        }
        if (optionalParameterTypes != null)
        {
            num -= optionalParameterTypes.Length;
        }
        UpdateStackSize(opcode, num);
        RecordTokenFixup();
        PutInteger4(methodToken);
    }
References System.SR.Argument_NotMethodCallOpcode, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.OpCodes.Callvirt, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.OpCode.Equals(), System.Reflection.Emit.ILGenerator.GetMethodToken(), System.Reflection.MethodBase.GetParameterTypes(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.Reflection.MethodBase.IsStatic, System.Reflection.Emit.OpCodes.Newobj, System.Reflection.Emit.ILGenerator.PutInteger4(), System.Reflection.Emit.ILGenerator.RecordTokenFixup(), System.Reflection.MethodInfo.ReturnType, and System.Reflection.Emit.ILGenerator.UpdateStackSize().
Referenced by System.Reflection.Emit.ILGenerator.Emit(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall().