Terraria: System.Reflection.Emit.ILGenerator.Emit
Emit() [1/17]
virtual void System.Reflection.Emit.ILGenerator.Emit (OpCode opcode) inline virtual
Definition at line 284 of file ILGenerator.cs.
    {
        EnsureCapacity(3);
        InternalEmit(opcode);
    }
References System.Reflection.Emit.ILGenerator.EnsureCapacity(), and System.Reflection.Emit.ILGenerator.InternalEmit().
Referenced by System.Runtime.Serialization.CodeGenerator.Add(), System.Xml.Serialization.CodeGenerator.Add(), System.Text.RegularExpressions.RegexCompiler.Add(), System.Text.RegularExpressions.RegexCompiler.Add(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOf(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Linq.Expressions.Compiler.LambdaCompiler.AddressOfWriteBackCore(), System.Reflection.Emit.IgnoreAccessChecksToAttributeBuilder.AddToModule(), System.Runtime.Serialization.CodeGenerator.And(), System.Text.RegularExpressions.RegexCompiler.And(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray.BeginSet(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.BeginSet(), System.Text.RegularExpressions.RegexCompiler.Beq(), System.Xml.Serialization.CodeGenerator.Beq(), System.Text.RegularExpressions.RegexCompiler.BeqFar(), System.Text.RegularExpressions.RegexCompiler.Bge(), System.Text.RegularExpressions.RegexCompiler.BgeFar(), System.Text.RegularExpressions.RegexCompiler.BgeUn(), System.Text.RegularExpressions.RegexCompiler.BgeUnFar(), System.Text.RegularExpressions.RegexCompiler.Bgt(), System.Text.RegularExpressions.RegexCompiler.BgtFar(), System.Text.RegularExpressions.RegexCompiler.BgtUn(), System.Text.RegularExpressions.RegexCompiler.Ble(), System.Xml.Serialization.CodeGenerator.Ble(), System.Text.RegularExpressions.RegexCompiler.BleFar(), System.Text.RegularExpressions.RegexCompiler.Blt(), System.Runtime.Serialization.CodeGenerator.Blt(), System.Xml.Serialization.CodeGenerator.Blt(), System.Text.RegularExpressions.RegexCompiler.BltFar(), System.Text.RegularExpressions.RegexCompiler.BltUnFar(), System.Text.RegularExpressions.RegexCompiler.Bne(), System.Xml.Serialization.CodeGenerator.Bne(), System.Text.RegularExpressions.RegexCompiler.BneFar(), System.Runtime.Serialization.CodeGenerator.Box(), System.Xml.Serialization.CodeGenerator.Box(), System.Text.RegularExpressions.RegexCompiler.Br(), System.Runtime.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Br_S(), System.Text.RegularExpressions.RegexCompiler.Brfalse(), System.Runtime.Serialization.CodeGenerator.Brfalse(), System.Xml.Serialization.CodeGenerator.Brfalse(), System.Text.RegularExpressions.RegexCompiler.BrfalseFar(), System.Text.RegularExpressions.RegexCompiler.BrFar(), System.Text.RegularExpressions.RegexCompiler.Brtrue(), System.Runtime.Serialization.CodeGenerator.Brtrue(), System.Xml.Serialization.CodeGenerator.Brtrue(), System.Text.RegularExpressions.RegexCompiler.BrtrueFar(), System.Runtime.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Call(), System.Text.RegularExpressions.RegexCompiler.Call(), System.Text.RegularExpressions.RegexCompiler.Callvirt(), System.Runtime.Serialization.CodeGenerator.Castclass(), System.Xml.Serialization.CodeGenerator.Castclass(), System.Runtime.Serialization.CodeGenerator.Ceq(), System.Xml.Serialization.CodeGenerator.Ceq(), System.Text.RegularExpressions.RegexCompiler.Ceq(), System.Text.RegularExpressions.RegexCompiler.CgtUn(), System.Xml.Serialization.CodeGenerator.Clt(), System.Text.RegularExpressions.RegexCompiler.CltUn(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Runtime.Serialization.CodeGenerator.Dup(), System.Xml.Serialization.CodeGenerator.Dup(), System.Text.RegularExpressions.RegexCompiler.Dup(), System.Runtime.Serialization.CodeGenerator.ElseIf(), System.Runtime.Serialization.CodeGenerator.ElseIfIsEmptyString(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Linq.Expressions.Compiler.ILGen.Emit(), System.Linq.Expressions.Compiler.ILGen.EmitArray(), System.Linq.Expressions.Compiler.ILGen.EmitArray(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchComparison(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitBranchOp(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCall(), System.Linq.Expressions.Compiler.ILGen.EmitCastToType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitCatchStart(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConditionalExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConstantOne(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitConvertArithmeticResult(), System.Linq.Expressions.Compiler.ILGen.EmitDecimal(), System.Linq.Expressions.Compiler.ILGen.EmitDefault(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDelegateConstruction(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitDynamicExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpressionAsVoid(), System.Linq.Expressions.Compiler.ILGen.EmitFieldAddress(), System.Linq.Expressions.Compiler.ILGen.EmitFieldGet(), System.Linq.Expressions.Compiler.ILGen.EmitFieldSet(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitGetArrayElement(), System.Linq.Expressions.Compiler.ILGen.EmitGetValue(), System.Linq.Expressions.Compiler.ILGen.EmitGetValueOrDefault(), System.Linq.Expressions.Compiler.ILGen.EmitHasValue(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitIndexAssignment(), System.Linq.Expressions.Compiler.LabelInfo.EmitJump(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaReferenceCoalesce(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLift(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBinaryArithmetic(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanAnd(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedBooleanOr(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedRelational(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLiftedToNullRelational(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitListInit(), System.Linq.Expressions.Compiler.ILGen.EmitLoadArg(), System.Linq.Expressions.Compiler.ILGen.EmitLoadArgAddress(), System.Linq.Expressions.Compiler.ILGen.EmitLoadElement(), System.Linq.Expressions.Compiler.ILGen.EmitLoadValueIndirect(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitLoopExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAddress(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodCall(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitMethodOrElse(), System.Linq.Expressions.Compiler.ILGen.EmitNew(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewArrayExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNewExpression(), System.Linq.Expressions.Compiler.ILGen.EmitNonNullableToNullableConversion(), System.Linq.Expressions.Compiler.ILGen.EmitNull(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullableCoalesce(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNonNullableStructConversion(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToNullableConversion(), System.Linq.Expressions.Compiler.ILGen.EmitNullableToReferenceConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitNullEquality(), System.Linq.Expressions.Compiler.ILGen.EmitNumericConversion(), System.Linq.Expressions.Compiler.ILGen.EmitPrimitive(), System.Linq.Expressions.Compiler.ILGen.EmitPrimitive(), System.Linq.Expressions.Compiler.ILGen.EmitPrimitive(), System.Linq.Expressions.Compiler.ILGen.EmitPrimitive(), System.Linq.Expressions.Compiler.ILGen.EmitPrimitive(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitQuote(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitReferenceCoalesceWithoutConversion(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSaveExceptionOrPop(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSetArrayElement(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitShiftMask(), System.Linq.Expressions.Compiler.ILGen.EmitStoreArg(), System.Linq.Expressions.Compiler.ILGen.EmitStoreElement(), System.Linq.Expressions.Compiler.ILGen.EmitStoreValueIndirect(), System.Linq.Expressions.Compiler.ILGen.EmitString(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBucket(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchBuckets(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitSwitchCases(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitThrow(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression(), System.Linq.Expressions.Compiler.ILGen.EmitType(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitTypeBinaryExpression(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnary(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnaryOperator(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnboxUnaryExpression(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedAndAlso(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedBinaryOp(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitUnliftedOrElse(), System.Linq.Expressions.Compiler.LambdaCompiler.EmitVariableAssignment(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.EndSet(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.ParametersArray.Get(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.Get(), System.Runtime.Serialization.CodeGenerator.If(), System.Xml.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.InitObj(), System.Xml.Serialization.CodeGenerator.InitObj(), System.Runtime.Serialization.CodeGenerator.InternalBreakFor(), System.Runtime.Serialization.CodeGenerator.InternalConvert(), System.Xml.Serialization.CodeGenerator.InternalConvert(), System.Xml.Serialization.CodeGenerator.IsInst(), System.Runtime.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Runtime.Serialization.CodeGenerator.Ldarga(), System.Xml.Serialization.CodeGenerator.Ldarga(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Text.RegularExpressions.RegexCompiler.LdcI8(), System.Runtime.Serialization.CodeGenerator.Ldelem(), System.Xml.Serialization.CodeGenerator.Ldelem(), System.Runtime.Serialization.CodeGenerator.Ldelema(), System.Xml.Serialization.CodeGenerator.Ldelema(), System.Text.RegularExpressions.RegexCompiler.LdelemI4(), System.Text.RegularExpressions.RegexCompiler.Ldfld(), System.Text.RegularExpressions.RegexCompiler.LdindI4(), System.Text.RegularExpressions.RegexCompiler.LdindI8(), System.Text.RegularExpressions.RegexCompiler.LdindU2(), System.Runtime.Serialization.CodeGenerator.Ldlen(), System.Xml.Serialization.CodeGenerator.Ldlen(), System.Text.RegularExpressions.RegexCompiler.Ldlen(), System.Runtime.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Text.RegularExpressions.RegexCompiler.Ldloc(), System.Runtime.Serialization.CodeGenerator.Ldloca(), System.Xml.Serialization.CodeGenerator.Ldloca(), System.Text.RegularExpressions.RegexCompiler.Ldloca(), System.Runtime.Serialization.CodeGenerator.Ldobj(), System.Xml.Serialization.CodeGenerator.Ldobj(), System.Text.RegularExpressions.RegexCompiler.Ldstr(), System.Runtime.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Text.RegularExpressions.RegexCompiler.Ldthis(), System.Runtime.Serialization.CodeGenerator.Ldtoken(), System.Xml.Serialization.CodeGenerator.Ldtoken(), System.Xml.Serialization.CodeGenerator.Leave(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.GenericArray< T >.Load(), System.Runtime.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.LoadMemberAddress(), System.Linq.Expressions.Compiler.LabelInfo.Mark(), System.Linq.Expressions.Compiler.LabelInfo.MarkWithEmptyStack(), System.Text.RegularExpressions.RegexCompiler.Mul(), System.Text.RegularExpressions.RegexCompiler.Neg(), System.Runtime.Serialization.CodeGenerator.New(), System.Xml.Serialization.CodeGenerator.New(), System.Runtime.Serialization.CodeGenerator.NewArray(), System.Xml.Serialization.CodeGenerator.NewArray(), System.Xml.Serialization.CodeGenerator.Nop(), System.Runtime.Serialization.CodeGenerator.Not(), System.Runtime.Serialization.CodeGenerator.Or(), System.Text.RegularExpressions.RegexCompiler.Or(), System.Runtime.Serialization.CodeGenerator.Pop(), System.Xml.Serialization.CodeGenerator.Pop(), System.Text.RegularExpressions.RegexCompiler.Pop(), System.Text.RegularExpressions.RegexCompiler.RemUn(), System.Runtime.Serialization.CodeGenerator.Ret(), System.Xml.Serialization.CodeGenerator.Ret(), System.Text.RegularExpressions.RegexCompiler.Ret(), System.Text.RegularExpressions.RegexCompiler.Shl(), System.Text.RegularExpressions.RegexCompiler.Shr(), System.Runtime.Serialization.CodeGenerator.Starg(), System.Runtime.Serialization.CodeGenerator.Stelem(), System.Xml.Serialization.CodeGenerator.Stelem(), System.Text.RegularExpressions.RegexCompiler.StelemI4(), System.Text.RegularExpressions.RegexCompiler.Stfld(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.CodeGenerator.Stloc(), System.Text.RegularExpressions.RegexCompiler.Stloc(), System.Runtime.Serialization.CodeGenerator.Stobj(), System.Xml.Serialization.CodeGenerator.Stobj(), System.Runtime.Serialization.CodeGenerator.StoreMember(), System.Xml.Serialization.CodeGenerator.StoreMember(), System.Linq.Expressions.Compiler.LabelInfo.StoreValue(), System.Text.RegularExpressions.RegexCompiler.Sub(), System.Text.RegularExpressions.RegexCompiler.Sub(), System.Runtime.Serialization.CodeGenerator.Subtract(), System.Runtime.Serialization.CodeGenerator.Switch(), System.Text.RegularExpressions.RegexCompiler.Switch(), System.Runtime.Serialization.CodeGenerator.Throw(), System.Xml.Serialization.CodeGenerator.Throw(), System.Linq.Expressions.Compiler.ILGen.TryEmitConstant(), System.Linq.Expressions.Compiler.ILGen.TryEmitILConstant(), System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitSwitchInstruction(), System.Text.RegularExpressions.RegexCompiler.Unaligned(), System.Runtime.Serialization.CodeGenerator.Unbox(), and System.Xml.Serialization.CodeGenerator.Unbox().