Terraria: System.Reflection.Emit.ILGenerator.BeginExceptionBlock
BeginExceptionBlock()
virtual Label System.Reflection.Emit.ILGenerator.BeginExceptionBlock () inline virtual
Definition at line 758 of file ILGenerator.cs.
    {
        if (m_exceptions == null)
        {
            m_exceptions = new __ExceptionInfo[2];
        }
        if (m_currExcStack == null)
        {
            m_currExcStack = new __ExceptionInfo[2];
        }
        if (m_exceptionCount >= m_exceptions.Length)
        {
            m_exceptions = EnlargeArray(m_exceptions);
        }
        if (m_currExcStackCount >= m_currExcStack.Length)
        {
            m_currExcStack = EnlargeArray(m_currExcStack);
        }
        Label label = DefineLabel();
        __ExceptionInfo _ExceptionInfo = new __ExceptionInfo(m_length, label);
        m_exceptions[m_exceptionCount++] = _ExceptionInfo;
        m_currExcStack[m_currExcStackCount++] = _ExceptionInfo;
        return label;
    }
References System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.m_currExcStack, System.Reflection.Emit.ILGenerator.m_currExcStackCount, System.Reflection.Emit.ILGenerator.m_exceptionCount, System.Reflection.Emit.ILGenerator.m_exceptions, and System.Reflection.Emit.ILGenerator.m_length.
Referenced by System.Xml.Serialization.CodeGenerator.BeginExceptionBlock(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression().