Terraria: System.Reflection.Emit.ILGenerator.BeginFinallyBlock
BeginFinallyBlock()
virtual void System.Reflection.Emit.ILGenerator.BeginFinallyBlock () inline virtual
Definition at line 858 of file ILGenerator.cs.
    {
        if (m_currExcStackCount == 0)
        {
            throw new NotSupportedException(SR.Argument_NotInExceptionBlock);
        }
        __ExceptionInfo _ExceptionInfo = m_currExcStack[m_currExcStackCount - 1];
        int currentState = _ExceptionInfo.GetCurrentState();
        Label endLabel = _ExceptionInfo.GetEndLabel();
        int num = 0;
        if (currentState != 0)
        {
            Emit(OpCodes.Leave, endLabel);
            num = m_length;
        }
        MarkLabel(endLabel);
        Label label = DefineLabel();
        _ExceptionInfo.SetFinallyEndLabel(label);
        Emit(OpCodes.Leave, label);
        if (num == 0)
        {
            num = m_length;
        }
        _ExceptionInfo.MarkFinallyAddr(m_length, num);
    }
References System.SR.Argument_NotInExceptionBlock, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.__ExceptionInfo.GetCurrentState(), System.Reflection.Emit.__ExceptionInfo.GetEndLabel(), System.Reflection.Emit.OpCodes.Leave, System.Reflection.Emit.ILGenerator.m_currExcStack, System.Reflection.Emit.ILGenerator.m_currExcStackCount, System.Reflection.Emit.ILGenerator.m_length, System.Reflection.Emit.__ExceptionInfo.MarkFinallyAddr(), System.Reflection.Emit.ILGenerator.MarkLabel(), and System.Reflection.Emit.__ExceptionInfo.SetFinallyEndLabel().
Referenced by System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitTryExpression().