Terraria: PlayerInput.FixDerpedRebinds
FixDerpedRebinds()
static void PlayerInput.FixDerpedRebinds () inline static private
     {
         List<string> list = new List<string> { "MouseLeft", "MouseRight", "Inventory" };
         foreach (InputMode value in Enum.GetValues(typeof(InputMode)))
         {
             if (value == InputMode.Mouse)
             {
                 continue;
             }
             FixKeysConflict(value, list);
             foreach (string item in list)
             {
                 if (CurrentProfile.InputModes[value].KeyStatus[item].Count < 1)
                 {
                     ResetKeyBinding(value, item);
                 }
             }
         }
     }
References CurrentProfile, FixKeysConflict(), PlayerInputProfile.InputModes, and ResetKeyBinding().
Referenced by CheckRebindingProcessGamepad(), and CheckRebindingProcessKeyboard().