Terraria: PlayerInput.ComposeInstructionsForGamepad
ComposeInstructionsForGamepad()
static string PlayerInput.ComposeInstructionsForGamepad () inline static
     {
         string empty = string.Empty;
         InputMode inputMode = InputMode.XBoxGamepad;
         if (Main.gameMenu || UILinkPointNavigator.Available)
         {
             inputMode = InputMode.XBoxGamepadUI;
         }
         if (InBuildingMode && !Main.gameMenu)
         {
             inputMode = InputMode.XBoxGamepad;
         }
         KeyConfiguration keyConfiguration = CurrentProfile.InputModes[inputMode];
         if (Main.mapFullscreen && !Main.gameMenu)
         {
             empty += "          ";
             empty += BuildCommand(Lang.misc[56].Value, false, ProfileGamepadUI.KeyStatus["Inventory"]);
             empty += BuildCommand(Lang.inter[118].Value, false, ProfileGamepadUI.KeyStatus["HotbarPlus"]);
             empty += BuildCommand(Lang.inter[119].Value, false, ProfileGamepadUI.KeyStatus["HotbarMinus"]);
             if (Main.netMode == 1 && Main.player[Main.myPlayer].HasItem(2997))
             {
                 empty += BuildCommand(Lang.inter[120].Value, false, ProfileGamepadUI.KeyStatus["MouseRight"]);
             }
         }
         else if (inputMode == InputMode.XBoxGamepadUI && !InBuildingMode)
         {
             empty = UILinkPointNavigator.GetInstructions();
         }
         else
         {
             empty += BuildCommand(Lang.misc[58].Value, false, keyConfiguration.KeyStatus["Jump"]);
             empty += BuildCommand(Lang.misc[59].Value, false, keyConfiguration.KeyStatus["HotbarMinus"], keyConfiguration.KeyStatus["HotbarPlus"]);
             if (InBuildingMode)
             {
                 empty += BuildCommand(Lang.menu[6].Value, false, keyConfiguration.KeyStatus["Inventory"], keyConfiguration.KeyStatus["MouseRight"]);
             }
             if (WiresUI.Open)
             {
                 empty += BuildCommand(Lang.misc[53].Value, false, keyConfiguration.KeyStatus["MouseLeft"]);
                 empty += BuildCommand(Lang.misc[56].Value, false, keyConfiguration.KeyStatus["MouseRight"]);
             }
             else
             {
                 Item item = Main.player[Main.myPlayer].inventory[Main.player[Main.myPlayer].selectedItem];
                 empty = ((item.damage > 0 && item.ammo == 0) ? (empty + BuildCommand(Lang.misc[60].Value, false, keyConfiguration.KeyStatus["MouseLeft"])) : ((item.createTile < 0 && item.createWall <= 0) ? (empty + BuildCommand(Lang.misc[63].Value, false, keyConfiguration.KeyStatus["MouseLeft"])) : (empty + BuildCommand(Lang.misc[61].Value, false, keyConfiguration.KeyStatus["MouseLeft"]))));
                 bool flag = true;
                 bool flag2 = Main.SmartInteractProj != -1 || Main.HasInteractibleObjectThatIsNotATile;
                 bool flag3 = !Main.SmartInteractShowingGenuine && Main.SmartInteractShowingFake;
                 if (Main.SmartInteractShowingGenuine || Main.SmartInteractShowingFake || flag2)
                 {
                     if (Main.SmartInteractNPC != -1)
                     {
                         if (flag3)
{
                             flag = false;
                         }
                         empty += BuildCommand(Lang.misc[80].Value, false, keyConfiguration.KeyStatus["MouseRight"]);
                     }
                     else if (flag2)
                     {
                         if (flag3)
{
                             flag = false;
                         }
                         empty += BuildCommand(Lang.misc[79].Value, false, keyConfiguration.KeyStatus["MouseRight"]);
                     }
                     else if (Main.SmartInteractX != -1 && Main.SmartInteractY != -1)
                     {
                         if (flag3)
{
                             flag = false;
                         }
                         Tile tile = Main.tile[Main.SmartInteractX, Main.SmartInteractY];
                         empty = ((!TileID.Sets.TileInteractRead[tile.type]) ? (empty + BuildCommand(Lang.misc[79].Value, false, keyConfiguration.KeyStatus["MouseRight"])) : (empty + BuildCommand(Lang.misc[81].Value, false, keyConfiguration.KeyStatus["MouseRight"])));
                     }
                 }
                 else if (WiresUI.Settings.DrawToolModeUI)
                 {
                     empty += BuildCommand(Lang.misc[89].Value, false, keyConfiguration.KeyStatus["MouseRight"]);
                 }
                 if ((!GrappleAndInteractAreShared || (!WiresUI.Settings.DrawToolModeUI && (!Main.SmartInteractShowingGenuine || !Main.HasSmartInteractTarget) && (!Main.SmartInteractShowingFake || flag))) && Main.LocalPlayer.QuickGrapple_GetItemToUse() != null)
                 {
                     empty += BuildCommand(Lang.misc[57].Value, false, keyConfiguration.KeyStatus["Grapple"]);
                 }
             }
         }
         return empty;
     }
References Item.ammo, UILinkPointNavigator.Available, BuildCommand(), Item.createTile, Item.createWall, CurrentProfile, Item.damage, WiresUI.Settings.DrawToolModeUI, Main.gameMenu, UILinkPointNavigator.GetInstructions(), GrappleAndInteractAreShared, Main.HasInteractibleObjectThatIsNotATile, Player.HasItem(), Main.HasSmartInteractTarget, InBuildingMode, PlayerInputProfile.InputModes, Lang.inter, Player.inventory, KeyConfiguration.KeyStatus, Main.LocalPlayer, Main.mapFullscreen, Lang.menu, Lang.misc, Main.myPlayer, Main.netMode, WiresUI.Open, Main.player, ProfileGamepadUI, Player.QuickGrapple_GetItemToUse(), Player.selectedItem, Main.SmartInteractNPC, Main.SmartInteractProj, Main.SmartInteractShowingFake, Main.SmartInteractShowingGenuine, Main.SmartInteractX, Main.SmartInteractY, Main.tile, TileID.Sets.TileInteractRead, Tile.type, and LocalizedText.Value.
Referenced by Main.DrawGamepadInstructions(), and Main.HackForGamepadInputHell().