Terraria: PlayerInput.GamePadInput
GamePadInput()
static bool PlayerInput.GamePadInput () inline static private
     {
         bool flag = false;
         ScrollWheelValue += GamepadScrollValue;
         GamePadState gamePadState = default(GamePadState);
         bool flag2 = false;
         for (int i = 0; i < 4; i++)
         {
             GamePadState state = GamePad.GetState((PlayerIndex)i);
             if (state.IsConnected)
             {
                 flag2 = true;
                 gamePadState = state;
                 break;
             }
         }
         if (Main.SettingBlockGamepadsEntirely)
         {
             return false;
         }
         if (!flag2)
         {
             return false;
         }
         if (!Main.instance.IsActive && !Main.AllowUnfocusedInputOnGamepad)
         {
             return false;
         }
         Player player = Main.player[Main.myPlayer];
         bool flag3 = UILinkPointNavigator.Available && !InBuildingMode;
         InputMode inputMode = InputMode.XBoxGamepad;
         if (Main.gameMenu || flag3 || player.talkNPC != -1 || player.sign != -1 || IngameFancyUI.CanCover())
         {
             inputMode = InputMode.XBoxGamepadUI;
         }
         if (!Main.gameMenu && InBuildingMode)
         {
             inputMode = InputMode.XBoxGamepad;
         }
         if (CurrentInputMode == InputMode.XBoxGamepad && inputMode == InputMode.XBoxGamepadUI)
         {
             flag = true;
         }
         if (CurrentInputMode == InputMode.XBoxGamepadUI && inputMode == InputMode.XBoxGamepad)
         {
             flag = true;
         }
         if (flag)
         {
             CurrentInputMode = inputMode;
         }
         KeyConfiguration keyConfiguration = CurrentProfile.InputModes[inputMode];
         int num = 2145386496;
         for (int j = 0; j < ButtonsGamepad.Length; j++)
         {
             if ((int)((uint)num & (uint)ButtonsGamepad[j]) > 0)
             {
                 continue;
             }
             string text = ButtonsGamepad[j].ToString();
             bool flag4 = _buttonsLocked.Contains(text);
             if (gamePadState.IsButtonDown(ButtonsGamepad[j]))
             {
                 if (!flag4)
                 {
                     if (CheckRebindingProcessGamepad(text))
                     {
                         return false;
                     }
                     keyConfiguration.Processkey(Triggers.Current, text, inputMode);
                     flag = true;
                 }
             }
             else
             {
                 _buttonsLocked.Remove(text);
             }
         }
         GamepadThumbstickLeft = gamePadState.ThumbSticks.Left * new Vector2(1f, -1f) * new Vector2(CurrentProfile.LeftThumbstickInvertX.ToDirectionInt() * -1, CurrentProfile.LeftThumbstickInvertY.ToDirectionInt() * -1);
         GamepadThumbstickRight = gamePadState.ThumbSticks.Right * new Vector2(1f, -1f) * new Vector2(CurrentProfile.RightThumbstickInvertX.ToDirectionInt() * -1, CurrentProfile.RightThumbstickInvertY.ToDirectionInt() * -1);
         Vector2 gamepadThumbstickRight = GamepadThumbstickRight;
         Vector2 gamepadThumbstickLeft = GamepadThumbstickLeft;
         Vector2 vector = gamepadThumbstickRight;
         if (vector != Vector2.Zero)
         {
             vector.Normalize();
         }
         Vector2 vector2 = gamepadThumbstickLeft;
         if (vector2 != Vector2.Zero)
         {
             vector2.Normalize();
         }
         float num2 = 0.6f;
         float triggersDeadzone = CurrentProfile.TriggersDeadzone;
         if (inputMode == InputMode.XBoxGamepadUI)
         {
             num2 = 0.4f;
             if (GamepadAllowScrolling)
             {
                 GamepadScrollValue -= (int)(gamepadThumbstickRight.Y * 16f);
             }
             GamepadAllowScrolling = false;
         }
         if (Vector2.Dot(-Vector2.UnitX, vector2) >= num2 && gamepadThumbstickLeft.X < 0f - CurrentProfile.LeftThumbstickDeadzoneX)
         {
             if (CheckRebindingProcessGamepad(Buttons.LeftThumbstickLeft.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.LeftThumbstickLeft.ToString(), inputMode);
             flag = true;
         }
         if (Vector2.Dot(Vector2.UnitX, vector2) >= num2 && gamepadThumbstickLeft.X > CurrentProfile.LeftThumbstickDeadzoneX)
         {
             if (CheckRebindingProcessGamepad(Buttons.LeftThumbstickRight.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.LeftThumbstickRight.ToString(), inputMode);
             flag = true;
         }
         if (Vector2.Dot(-Vector2.UnitY, vector2) >= num2 && gamepadThumbstickLeft.Y < 0f - CurrentProfile.LeftThumbstickDeadzoneY)
         {
             if (CheckRebindingProcessGamepad(Buttons.LeftThumbstickUp.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.LeftThumbstickUp.ToString(), inputMode);
             flag = true;
         }
         if (Vector2.Dot(Vector2.UnitY, vector2) >= num2 && gamepadThumbstickLeft.Y > CurrentProfile.LeftThumbstickDeadzoneY)
         {
             if (CheckRebindingProcessGamepad(Buttons.LeftThumbstickDown.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.LeftThumbstickDown.ToString(), inputMode);
             flag = true;
         }
         if (Vector2.Dot(-Vector2.UnitX, vector) >= num2 && gamepadThumbstickRight.X < 0f - CurrentProfile.RightThumbstickDeadzoneX)
         {
             if (CheckRebindingProcessGamepad(Buttons.RightThumbstickLeft.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.RightThumbstickLeft.ToString(), inputMode);
             flag = true;
         }
         if (Vector2.Dot(Vector2.UnitX, vector) >= num2 && gamepadThumbstickRight.X > CurrentProfile.RightThumbstickDeadzoneX)
         {
             if (CheckRebindingProcessGamepad(Buttons.RightThumbstickRight.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.RightThumbstickRight.ToString(), inputMode);
             flag = true;
         }
         if (Vector2.Dot(-Vector2.UnitY, vector) >= num2 && gamepadThumbstickRight.Y < 0f - CurrentProfile.RightThumbstickDeadzoneY)
         {
             if (CheckRebindingProcessGamepad(Buttons.RightThumbstickUp.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.RightThumbstickUp.ToString(), inputMode);
             flag = true;
         }
         if (Vector2.Dot(Vector2.UnitY, vector) >= num2 && gamepadThumbstickRight.Y > CurrentProfile.RightThumbstickDeadzoneY)
         {
             if (CheckRebindingProcessGamepad(Buttons.RightThumbstickDown.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.RightThumbstickDown.ToString(), inputMode);
             flag = true;
         }
         if (gamePadState.Triggers.Left > triggersDeadzone)
         {
             if (CheckRebindingProcessGamepad(Buttons.LeftTrigger.ToString()))
             {
                 return false;
             }
             keyConfiguration.Processkey(Triggers.Current, Buttons.LeftTrigger.ToString(), inputMode);
             flag = true;
         }
         if (gamePadState.Triggers.Right > triggersDeadzone)
         {
             string newKey = Buttons.RightTrigger.ToString();
             if (CheckRebindingProcessGamepad(newKey))
             {
                 return false;
             }
             if (inputMode == InputMode.XBoxGamepadUI && SteamDeckIsUsed && SettingsForUI.CurrentCursorMode == CursorMode.Mouse)
             {
                 Triggers.Current.MouseLeft = true;
             }
             else
             {
                 keyConfiguration.Processkey(Triggers.Current, newKey, inputMode);
                 flag = true;
             }
         }
         bool flag5 = ItemID.Sets.GamepadWholeScreenUseRange[player.inventory[player.selectedItem].type] || player.scope;
         Item item = player.inventory[player.selectedItem];
         int num3 = item.tileBoost + ItemID.Sets.GamepadExtraRange[item.type];
         if (player.yoyoString && ItemID.Sets.Yoyo[item.type])
         {
             num3 += 5;
         }
         else if (item.createTile < 0 && item.createWall <= 0 && item.shoot > 0)
         {
             num3 += 10;
         }
         else if (player.controlTorch)
         {
             num3++;
         }
         if (item.createWall > 0 || item.createTile > 0 || item.tileWand > 0)
         {
             num3 += player.blockRange;
         }
         if (flag5)
         {
             num3 += 30;
         }
         if (player.mount.Active && player.mount.Type == 8)
         {
             num3 = 10;
         }
         bool flag6 = false;
         bool flag7 = !Main.gameMenu && !flag3 && Main.SmartCursorWanted;
         if (!CursorIsBusy)
         {
             bool flag8 = Main.mapFullscreen || (!Main.gameMenu && !flag3);
             int num4 = Main.screenWidth / 2;
             int num5 = Main.screenHeight / 2;
             if (!Main.mapFullscreen && flag8 && !flag5)
             {
                 Point point = Main.ReverseGravitySupport(player.Center - Main.screenPosition).ToPoint();
                 num4 = point.X;
                 num5 = point.Y;
             }
             if (player.velocity == Vector2.Zero && gamepadThumbstickLeft == Vector2.Zero && gamepadThumbstickRight == Vector2.Zero && flag7)
             {
                 num4 += player.direction * 10;
             }
             float m = Main.GameViewMatrix.ZoomMatrix.M11;
             smartSelectPointer.UpdateSize(new Vector2(Player.tileRangeX * 16 + num3 * 16, Player.tileRangeY * 16 + num3 * 16) * m);
             if (flag5)
             {
                 smartSelectPointer.UpdateSize(new Vector2(Math.Max(Main.screenWidth, Main.screenHeight) / 2));
             }
             smartSelectPointer.UpdateCenter(new Vector2(num4, num5));
             if (gamepadThumbstickRight != Vector2.Zero && flag8)
             {
                 Vector2 vector3 = new Vector2(8f);
                 if (!Main.gameMenu && Main.mapFullscreen)
                 {
                     vector3 = new Vector2(16f);
                 }
                 if (flag7)
                 {
                     vector3 = new Vector2(Player.tileRangeX * 16, Player.tileRangeY * 16);
                     if (num3 != 0)
                     {
                         vector3 += new Vector2(num3 * 16, num3 * 16);
                     }
                     if (flag5)
                     {
                         vector3 = new Vector2(Math.Max(Main.screenWidth, Main.screenHeight) / 2);
                     }
                 }
                 else if (!Main.mapFullscreen)
                 {
                     if (player.inventory[player.selectedItem].mech)
                     {
                         vector3 += Vector2.Zero;
                     }
                     else
                     {
                         vector3 += new Vector2(num3) / 4f;
                     }
                 }
                 float m2 = Main.GameViewMatrix.ZoomMatrix.M11;
                 Vector2 vector4 = gamepadThumbstickRight * vector3 * m2;
                 int num6 = MouseX - num4;
                 int num7 = MouseY - num5;
                 if (flag7)
                 {
                     num6 = 0;
                     num7 = 0;
                 }
                 num6 += (int)vector4.X;
                 num7 += (int)vector4.Y;
                 MouseX = num6 + num4;
                 MouseY = num7 + num5;
                 flag = true;
                 flag6 = true;
                 SettingsForUI.SetCursorMode(CursorMode.Gamepad);
             }
             bool allowSecondaryGamepadAim = SettingsForUI.AllowSecondaryGamepadAim;
             if (gamepadThumbstickLeft != Vector2.Zero && flag8)
             {
                 float num8 = 8f;
                 if (!Main.gameMenu && Main.mapFullscreen)
                 {
                     num8 = 3f;
                 }
                 if (Main.mapFullscreen)
                 {
                     Vector2 vector5 = gamepadThumbstickLeft * num8;
                     Main.mapFullscreenPos += vector5 * num8 * (1f / Main.mapFullscreenScale);
                     flag = true;
                 }
                 else if (!flag6 && Main.SmartCursorWanted && allowSecondaryGamepadAim)
                 {
                     float m3 = Main.GameViewMatrix.ZoomMatrix.M11;
                     Vector2 vector6 = gamepadThumbstickLeft * new Vector2(Player.tileRangeX * 16, Player.tileRangeY * 16) * m3;
                     if (num3 != 0)
                     {
                         vector6 = gamepadThumbstickLeft * new Vector2((Player.tileRangeX + num3) * 16, (Player.tileRangeY + num3) * 16) * m3;
                     }
                     if (flag5)
                     {
                         vector6 = new Vector2(Math.Max(Main.screenWidth, Main.screenHeight) / 2) * gamepadThumbstickLeft;
                     }
                     int num9 = (int)vector6.X;
                     int num10 = (int)vector6.Y;
                     MouseX = num9 + num4;
                     MouseY = num10 + num5;
                     flag6 = true;
                 }
                 flag = true;
             }
             if (CurrentInputMode == InputMode.XBoxGamepad)
             {
                 HandleDpadSnap();
                 if (SettingsForUI.AllowSecondaryGamepadAim)
                 {
                     int num11 = MouseX - num4;
                     int num12 = MouseY - num5;
                     if (!Main.gameMenu && !flag3)
                     {
                         if (flag5 && !Main.mapFullscreen)
{
                             float num13 = 1f;
                             int num14 = Main.screenWidth / 2;
                             int num15 = Main.screenHeight / 2;
                             num11 = (int)Utils.Clamp(num11, (float)(-num14) * num13, (float)num14 * num13);
                             num12 = (int)Utils.Clamp(num12, (float)(-num15) * num13, (float)num15 * num13);
                         }
                         else
{
                             float num16 = 0f;
                             if (player.HeldItem.createTile >= 0 || player.HeldItem.createWall > 0 || player.HeldItem.tileWand >= 0)
{
                                 num16 = 0.5f;
                             }
                             float m4 = Main.GameViewMatrix.ZoomMatrix.M11;
                             float num17 = (0f - ((float)(Player.tileRangeY + num3) - num16)) * 16f * m4;
                             float max = ((float)(Player.tileRangeY + num3) - num16) * 16f * m4;
                             num17 -= (float)(player.height / 16 / 2 * 16);
                             num11 = (int)Utils.Clamp(num11, (0f - ((float)(Player.tileRangeX + num3) - num16)) * 16f * m4, ((float)(Player.tileRangeX + num3) - num16) * 16f * m4);
                             num12 = (int)Utils.Clamp(num12, num17, max);
                         }
                         if (flag7 && (!flag || flag5))
{
                             float num18 = 0.81f;
                             if (flag5)
{
                                 num18 = 0.95f;
                             }
                             num11 = (int)((float)num11 * num18);
                             num12 = (int)((float)num12 * num18);
                         }
                     }
                     else
                     {
                         num11 = Utils.Clamp(num11, -num4 + 10, num4 - 10);
                         num12 = Utils.Clamp(num12, -num5 + 10, num5 - 10);
                     }
                     MouseX = num11 + num4;
                     MouseY = num12 + num5;
                 }
             }
         }
         if (flag)
         {
             CurrentInputMode = inputMode;
         }
         if (CurrentInputMode == InputMode.XBoxGamepad)
         {
             Main.SetCameraGamepadLerp(0.1f);
         }
         if (CurrentInputMode != InputMode.XBoxGamepadUI && flag)
         {
             PreventCursorModeSwappingToGamepad = true;
         }
         if (!flag)
         {
             PreventCursorModeSwappingToGamepad = false;
         }
         if (CurrentInputMode == InputMode.XBoxGamepadUI && flag && !PreventCursorModeSwappingToGamepad)
         {
             SettingsForUI.SetCursorMode(CursorMode.Gamepad);
         }
         return flag;
     }
References _buttonsLocked, Mount.Active, PlayerInput.SettingsForUI.AllowSecondaryGamepadAim, Main.AllowUnfocusedInputOnGamepad, UILinkPointNavigator.Available, Player.blockRange, ButtonsGamepad, IngameFancyUI.CanCover(), Entity.Center, CheckRebindingProcessGamepad(), Player.controlTorch, Item.createTile, Item.createWall, TriggersPack.Current, PlayerInput.SettingsForUI.CurrentCursorMode, CurrentInputMode, CurrentProfile, CursorIsBusy, Entity.direction, Main.gameMenu, GamepadAllowScrolling, ItemID.Sets.GamepadExtraRange, GamepadScrollValue, GamepadThumbstickLeft, GamepadThumbstickRight, ItemID.Sets.GamepadWholeScreenUseRange, Main.GameViewMatrix, HandleDpadSnap(), Entity.height, Player.HeldItem, InBuildingMode, PlayerInputProfile.InputModes, Main.instance, Player.inventory, Game.IsActive, PlayerInputProfile.LeftThumbstickDeadzoneX, PlayerInputProfile.LeftThumbstickDeadzoneY, PlayerInputProfile.LeftThumbstickInvertX, PlayerInputProfile.LeftThumbstickInvertY, Main.mapFullscreen, Main.mapFullscreenPos, Main.mapFullscreenScale, Item.mech, Player.mount, TriggersSet.MouseLeft, MouseX, MouseY, Main.myPlayer, Main.player, PreventCursorModeSwappingToGamepad, KeyConfiguration.Processkey(), Main.ReverseGravitySupport(), PlayerInputProfile.RightThumbstickDeadzoneX, PlayerInputProfile.RightThumbstickDeadzoneY, PlayerInputProfile.RightThumbstickInvertX, PlayerInputProfile.RightThumbstickInvertY, Player.scope, Main.screenHeight, Main.screenPosition, Main.screenWidth, ScrollWheelValue, Player.selectedItem, Main.SetCameraGamepadLerp(), PlayerInput.SettingsForUI.SetCursorMode(), Main.SettingBlockGamepadsEntirely, Item.shoot, Player.sign, Main.SmartCursorWanted, smartSelectPointer, SteamDeckIsUsed, Player.talkNPC, Item.tileBoost, Player.tileRangeX, Player.tileRangeY, Item.tileWand, Triggers, PlayerInputProfile.TriggersDeadzone, Item.type, Mount.Type, SmartSelectGamepadPointer.UpdateCenter(), SmartSelectGamepadPointer.UpdateSize(), Entity.velocity, ItemID.Sets.Yoyo, Player.yoyoString, and SpriteViewMatrix.ZoomMatrix.
Referenced by UpdateInput().