Terraria: PlayerInput.SetZoom_Context
SetZoom_Context()
static void PlayerInput.SetZoom_Context () inline static
     {
         switch (_currentWantedZoom)
         {
         case ZoomContext.Unscaled:
             SetZoom_Unscaled();
             Main.SetRecommendedZoomContext(Matrix.Identity);
             break;
         case ZoomContext.Unscaled_MouseInWorld:
             SetZoom_Unscaled();
             SetZoom_MouseInWorld();
             Main.SetRecommendedZoomContext(Main.GameViewMatrix.ZoomMatrix);
             break;
         case ZoomContext.UI:
             SetZoom_UI();
             Main.SetRecommendedZoomContext(Main.UIScaleMatrix);
             break;
         case ZoomContext.World:
             SetZoom_World();
             Main.SetRecommendedZoomContext(Main.GameViewMatrix.ZoomMatrix);
             break;
         }
     }
References _currentWantedZoom, Main.GameViewMatrix, Main.SetRecommendedZoomContext(), SetZoom_MouseInWorld(), SetZoom_UI(), SetZoom_Unscaled(), SetZoom_World(), Main.UIScaleMatrix, and SpriteViewMatrix.ZoomMatrix.
Referenced by CaptureInterface.ModeEdgeSelection.Draw(), CaptureInterface.ModeDragBounds.Draw(), CaptureInterface.ModeChangeSettings.Draw(), CaptureInterface.ModeEdgeSelection.Update(), and CaptureInterface.ModeDragBounds.Update().