Terraria: PlayerInput.HandleDpadSnap
HandleDpadSnap()
static void PlayerInput.HandleDpadSnap () inline static private
     {
         Vector2 zero = Vector2.Zero;
         Player player = Main.player[Main.myPlayer];
         for (int i = 0; i < 4; i++)
         {
             bool flag = false;
             Vector2 vector = Vector2.Zero;
             if (Main.gameMenu || (UILinkPointNavigator.Available && !InBuildingMode))
             {
                 return;
             }
             switch (i)
             {
             case 0:
                 flag = Triggers.Current.DpadMouseSnap1;
                 vector = -Vector2.UnitY;
                 break;
             case 1:
                 flag = Triggers.Current.DpadMouseSnap2;
                 vector = Vector2.UnitX;
                 break;
             case 2:
                 flag = Triggers.Current.DpadMouseSnap3;
                 vector = Vector2.UnitY;
                 break;
             case 3:
                 flag = Triggers.Current.DpadMouseSnap4;
                 vector = -Vector2.UnitX;
                 break;
             }
             if (DpadSnapCooldown[i] > 0)
             {
                 DpadSnapCooldown[i]--;
             }
             if (flag)
             {
                 if (DpadSnapCooldown[i] == 0)
                 {
                     int num = 6;
                     if (ItemSlot.IsABuildingItem(player.inventory[player.selectedItem]))
                     {
                         num = player.inventory[player.selectedItem].useTime;
                     }
                     DpadSnapCooldown[i] = num;
                     zero += vector;
                 }
             }
             else
             {
                 DpadSnapCooldown[i] = 0;
             }
         }
         if (zero != Vector2.Zero)
         {
             Main.SmartCursorWanted_GamePad = false;
             Matrix zoomMatrix = Main.GameViewMatrix.ZoomMatrix;
             Matrix matrix = Matrix.Invert(zoomMatrix);
             Vector2 mouseScreen = Main.MouseScreen;
             Vector2.Transform(Main.screenPosition, matrix);
             Vector2 vector2 = Vector2.Transform((Vector2.Transform(mouseScreen, matrix) + zero * new Vector2(16f) + Main.screenPosition).ToTileCoordinates().ToWorldCoordinates() - Main.screenPosition, zoomMatrix);
             MouseX = (int)vector2.X;
             MouseY = (int)vector2.Y;
             SettingsForUI.SetCursorMode(CursorMode.Gamepad);
         }
     }
References UILinkPointNavigator.Available, TriggersPack.Current, TriggersSet.DpadMouseSnap1, TriggersSet.DpadMouseSnap2, TriggersSet.DpadMouseSnap3, TriggersSet.DpadMouseSnap4, DpadSnapCooldown, Main.gameMenu, Main.GameViewMatrix, InBuildingMode, Player.inventory, ItemSlot.IsABuildingItem(), Main.MouseScreen, MouseX, MouseY, Main.myPlayer, Main.player, Main.screenPosition, Player.selectedItem, PlayerInput.SettingsForUI.SetCursorMode(), Main.SmartCursorWanted_GamePad, Triggers, Item.useTime, and SpriteViewMatrix.ZoomMatrix.
Referenced by GamePadInput().