Terraria: PlayerInput.KeyboardInput
KeyboardInput()
static bool PlayerInput.KeyboardInput () inline static private
     {
         bool flag = false;
         bool flag2 = false;
         List<Keys> pressedKeys = GetPressedKeys();
         DebugKeys(pressedKeys);
         if (pressedKeys.Count == 0 && MouseKeys.Count == 0)
         {
             Main.blockKey = Keys.None.ToString();
             return false;
         }
         for (int i = 0; i < pressedKeys.Count; i++)
         {
             if (pressedKeys[i] == Keys.LeftShift || pressedKeys[i] == Keys.RightShift)
             {
                 flag = true;
             }
             else if (pressedKeys[i] == Keys.LeftAlt || pressedKeys[i] == Keys.RightAlt)
             {
                 flag2 = true;
             }
             Main.ChromaPainter.PressKey(pressedKeys[i]);
         }
         if (Main.blockKey != Keys.None.ToString())
         {
             bool flag3 = false;
             for (int j = 0; j < pressedKeys.Count; j++)
             {
                 if (pressedKeys[j].ToString() == Main.blockKey)
                 {
                     pressedKeys[j] = Keys.None;
                     flag3 = true;
                 }
             }
             if (!flag3)
             {
                 Main.blockKey = Keys.None.ToString();
             }
         }
         KeyConfiguration keyConfiguration = CurrentProfile.InputModes[InputMode.Keyboard];
         if (Main.gameMenu && !WritingText)
         {
             keyConfiguration = CurrentProfile.InputModes[InputMode.KeyboardUI];
         }
         List<string> list = new List<string>(pressedKeys.Count);
         for (int k = 0; k < pressedKeys.Count; k++)
         {
             list.Add(pressedKeys[k].ToString());
         }
         if (WritingText)
         {
             list.Clear();
         }
         int count = list.Count;
         list.AddRange(MouseKeys);
         bool flag4 = false;
         for (int l = 0; l < list.Count; l++)
         {
             if (l < count && pressedKeys[l] == Keys.None)
             {
                 continue;
             }
             string newKey = list[l];
             if (!(list[l] == Keys.Tab.ToString()) || !((flag && SocialAPI.Mode == SocialMode.Steam) || flag2))
             {
                 if (CheckRebindingProcessKeyboard(newKey))
                 {
                     return false;
                 }
                 _ = Main.oldKeyState;
                 if (l >= count || !Main.oldKeyState.IsKeyDown(pressedKeys[l]))
                 {
                     keyConfiguration.Processkey(Triggers.Current, newKey, InputMode.Keyboard);
                 }
                 else
                 {
                     keyConfiguration.CopyKeyState(Triggers.Old, Triggers.Current, newKey);
                 }
                 if (l >= count || pressedKeys[l] != 0)
                 {
                     flag4 = true;
                 }
             }
         }
         if (flag4)
         {
             CurrentInputMode = InputMode.Keyboard;
         }
         return flag4;
     }
References Main.blockKey, CheckRebindingProcessKeyboard(), Main.ChromaPainter, KeyConfiguration.CopyKeyState(), TriggersPack.Current, CurrentInputMode, CurrentProfile, DebugKeys(), Main.gameMenu, GetPressedKeys(), PlayerInputProfile.InputModes, SocialAPI.Mode, MouseKeys, TriggersPack.Old, Main.oldKeyState, ChromaHotkeyPainter.PressKey(), KeyConfiguration.Processkey(), Triggers, and WritingText.
Referenced by UpdateInput().