Terraria: System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CopyToAsync
CopyToAsync() [4/4]
override Task System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 299 of file DecompressionHandler.cs.
            {
                Stream.ValidateCopyToArguments(destination, bufferSize);
                return Core(destination, bufferSize, cancellationToken);
                async Task Core(Stream destination, int bufferSize, CancellationToken cancellationToken)
                {
                    if (_decompressionStream == null)
                    {
                        _decompressionStream = CreateDecompressionStream(await _stream.PeekFirstByteAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false), _stream);
                    }
                    await _decompressionStream.CopyToAsync(destination, bufferSize, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
References System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream._decompressionStream, System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream._stream, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.CopyToAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CreateDecompressionStream(), System.destination, System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.PeekFirstByteAsync(), and System.IO.Stream.ValidateCopyToArguments().