Terraria: System.Net.Internals.SocketAddress.SocketAddress
SocketAddress() [7/9]
System.Net.Internals.SocketAddress.SocketAddress (IPAddress ipAddress) inline package
Definition at line 59 of file SocketAddress.cs.
        : this(ipAddress.AddressFamily, (ipAddress.AddressFamily == AddressFamily.InterNetwork) ? IPv4AddressSize : IPv6AddressSize)
    {
        System.Net.SocketAddressPal.SetPort(Buffer, 0);
        if (ipAddress.AddressFamily == AddressFamily.InterNetworkV6)
        {
            Span<byte> span = stackalloc byte[16];
            ipAddress.TryWriteBytes(span, out var _);
            System.Net.SocketAddressPal.SetIPv6Address(Buffer, span, (uint)ipAddress.ScopeId);
        }
        else
        {
            uint address = (uint)ipAddress.Address;
            System.Net.SocketAddressPal.SetIPv4Address(Buffer, address);
        }
    }
References System.Net.IPAddress.Address, System.Net.IPAddress.AddressFamily, System.Net.IPAddress.ScopeId, System.Net.SocketAddressPal.SetIPv4Address(), System.Net.SocketAddressPal.SetIPv6Address(), System.Net.SocketAddressPal.SetPort(), and System.Net.IPAddress.TryWriteBytes().