Terraria: System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.AddPairwise
AddPairwise() [1/10]
static Vector128< byte > System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.AddPairwise (Vector128< byte > left, Vector128< byte > right) inline static inherited
Definition at line 239 of file AdvSimd.cs.
        {
            throw new PlatformNotSupportedException();
        }
Referenced by System.Collections.BitArray.BitArray(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeAdvSimd64(), and System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeAdvSimd64().