Terraria: System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CreateDecompressionStream
CreateDecompressionStream()
static Stream System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CreateDecompressionStream (int firstByte, Stream stream) inline static private
Definition at line 313 of file DecompressionHandler.cs.
            {
                if ((firstByte & 0xF) != 8)
                {
                    return new DeflateStream(stream, CompressionMode.Decompress);
                }
                return new ZLibStream(stream, CompressionMode.Decompress);
            }
References System.stream.
Referenced by System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CopyToAsync(), System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.Read(), and System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.ReadAsync().