Terraria: System.Collections.Specialized.ListDictionary.Add
Add()
void System.Collections.Specialized.ListDictionary.Add (object key, object? value) inline
Implements System.Collections.IDictionary.
Definition at line 327 of file ListDictionary.cs.
    {
        if (key == null)
        {
            throw new ArgumentNullException("key");
        }
        version++;
        DictionaryNode dictionaryNode = null;
        for (DictionaryNode next = head; next != null; next = next.next)
        {
            object key2 = next.key;
            if ((comparer == null) ? key2.Equals(key) : (comparer.Compare(key2, key) == 0))
            {
                throw new ArgumentException(System.SR.Format(System.SR.Argument_AddingDuplicate, key));
            }
            dictionaryNode = next;
        }
        DictionaryNode dictionaryNode2 = new DictionaryNode();
        dictionaryNode2.key = key;
        dictionaryNode2.value = value;
        if (dictionaryNode != null)
        {
            dictionaryNode.next = dictionaryNode2;
        }
        else
        {
            head = dictionaryNode2;
        }
        count++;
    }
References System.SR.Argument_AddingDuplicate, System.Collections.IComparer.Compare(), System.Collections.Specialized.ListDictionary.comparer, System.Collections.Specialized.ListDictionary.count, System.SR.Format(), System.Collections.Specialized.ListDictionary.head, System.Collections.Specialized.ListDictionary.DictionaryNode.key, System.key, System.Collections.Specialized.ListDictionary.DictionaryNode.next, System.value, and System.Collections.Specialized.ListDictionary.version.
Referenced by System.Collections.Specialized.HybridDictionary.Add().