Terraria: System.Variant.ToObject
ToObject()
object System.Variant.ToObject () inline
Definition at line 308 of file Variant.cs.
    {
        return CVType switch
        {
            0 => null,
            2 => (int)_data != 0,
            4 => (sbyte)_data,
            5 => (byte)_data,
            3 => (char)_data,
            6 => (short)_data,
            7 => (ushort)_data,
            8 => (int)_data,
            9 => (uint)_data,
            10 => _data,
            11 => (ulong)_data,
            12 => BitConverter.UInt32BitsToSingle((uint)_data),
            13 => BitConverter.Int64BitsToDouble(_data),
            16 => new DateTime(_data),
            17 => new TimeSpan(_data),
            21 => BoxEnum(),
            22 => Type.Missing,
            23 => System.DBNull.Value,
            _ => _objref,
        };
    }
References System.Variant._data, System.Variant._objref, System.Variant.BoxEnum(), System.Variant.CVType, System.DateTime, System.BitConverter.Int64BitsToDouble(), System.Type.Missing, System.BitConverter.UInt32BitsToSingle(), and System.DBNull.Value.