Terraria: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted< T >
AppendFormatted< T >() [1/4]
void System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted< T > (T value) inline
Definition at line 126 of file DefaultInterpolatedStringHandler.cs.
    {
        if (_hasCustomFormatter)
        {
            AppendCustomFormatter(value, null);
            return;
        }
        string text;
        if (value is IFormattable)
        {
            if (value is ISpanFormattable)
            {
                int charsWritten;
                while (!((ISpanFormattable)(object)value).TryFormat(_chars.Slice(_pos), out charsWritten, default(ReadOnlySpan<char>), _provider))
                {
                    Grow();
                }
                _pos += charsWritten;
                return;
            }
            text = ((IFormattable)(object)value).ToString(null, _provider);
        }
        else
        {
            text = value?.ToString();
        }
        if (text != null)
        {
            AppendStringDirect(text);
        }
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._chars, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._hasCustomFormatter, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._pos, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._provider, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendStringDirect(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.Grow(), System.Span< T >.Slice(), System.text, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.ToString(), and System.value.