Terraria: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted
AppendFormatted() [2/5]
void System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted (ReadOnlySpan< char > value) inline
Definition at line 210 of file DefaultInterpolatedStringHandler.cs.
    {
        if (value.TryCopyTo(_chars.Slice(_pos)))
        {
            _pos += value.Length;
        }
        else
        {
            GrowThenCopySpan(value);
        }
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._chars, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._pos, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.GrowThenCopySpan(), System.Span< T >.Slice(), and System.value.
Referenced by System.Net.Http.Http3Connection.Http3Connection(), System.Net.WebProxy.WebProxy(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted< T >(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted< T >(), System.Xml.CharEntityEncoderFallbackBuffer.Fallback(), System.Xml.CharEntityEncoderFallbackBuffer.Fallback(), System.Xml.Xsl.Runtime.XmlQueryRuntime.GenerateId(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.XmlWellFormedWriter.GeneratePrefix(), System.Xml.XmlBaseWriter.GeneratePrefix(), System.Diagnostics.FileVersionInfo.GetVersionInfoForCodePage(), System.IO.IsolatedStorage.IsolatedStorage.InitStore(), System.Net.WebProxy.IsMatchInBypassList(), System.Xml.Serialization.XmlSerializationReaderCodeGen.NextIdName(), System.Xml.Serialization.XmlSerializationReaderILGen.NextIdName(), System.Xml.Serialization.XmlSerializationReaderCodeGen.NextMethodName(), System.Xml.Serialization.XmlSerializationReaderILGen.NextMethodName(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleIsReference(), System.Collections.Generic.KeyValuePair< TKey, TValue >.PairToString(), System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(), System.Linq.Expressions.Interpreter.LoadCachedObjectInstruction.ToDebugString(), System.Linq.Expressions.Interpreter.DebugInfo.ToString(), System.Linq.Expressions.Interpreter.ExceptionHandler.ToString(), System.Linq.Expressions.Interpreter.LocalVariable.ToString(), System.Linq.Expressions.Interpreter.RuntimeLabel.ToString(), System.Net.Http.Headers.RangeItemHeaderValue.ToString(), System.Net.Http.Headers.StringWithQualityHeaderValue.ToString(), System.Net.CredentialHostKey.ToString(), System.Net.CredentialKey.ToString(), System.Diagnostics.TraceListener.TraceTransfer(), System.Runtime.Serialization.XmlObjectSerializer.TryAddLineInfo(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAddCollectionFixup(), System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTimeInDefaultFormat(), System.Diagnostics.TraceListener.WriteFooter(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHashtable(), System.Diagnostics.TraceListener.WriteHeader(), and System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute().