Terraria: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendOrInsertAlignmentIfNeeded
AppendOrInsertAlignmentIfNeeded()
void System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendOrInsertAlignmentIfNeeded (int startingPos, int alignment) inline private
Definition at line 314 of file DefaultInterpolatedStringHandler.cs.
    {
        int num = _pos - startingPos;
        bool flag = false;
        if (alignment < 0)
        {
            flag = true;
            alignment = -alignment;
        }
        int num2 = alignment - num;
        if (num2 > 0)
        {
            EnsureCapacityForAdditionalChars(num2);
            if (flag)
            {
                _chars.Slice(_pos, num2).Fill(' ');
            }
            else
            {
                _chars.Slice(startingPos, num).CopyTo(_chars.Slice(startingPos + num2));
                _chars.Slice(startingPos, num2).Fill(' ');
            }
            _pos += num2;
        }
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._chars, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._pos, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.EnsureCapacityForAdditionalChars(), and System.Span< T >.Slice().
Referenced by System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted< T >(), and System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted< T >().