Terraria: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted
AppendFormatted() [3/5]
void System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted (ReadOnlySpan< char > value, int alignment = 0, string? format = null) inline
Definition at line 222 of file DefaultInterpolatedStringHandler.cs.
    {
        bool flag = false;
        if (alignment < 0)
        {
            flag = true;
            alignment = -alignment;
        }
        int num = alignment - value.Length;
        if (num <= 0)
        {
            AppendFormatted(value);
            return;
        }
        EnsureCapacityForAdditionalChars(value.Length + num);
        if (flag)
        {
            value.CopyTo(_chars.Slice(_pos));
            _pos += value.Length;
            _chars.Slice(_pos, num).Fill(' ');
            _pos += num;
        }
        else
        {
            _chars.Slice(_pos, num).Fill(' ');
            _pos += num;
            value.CopyTo(_chars.Slice(_pos));
            _pos += value.Length;
        }
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._chars, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._pos, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.EnsureCapacityForAdditionalChars(), System.Span< T >.Slice(), and System.value.