Terraria: System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.GrowCore
GrowCore()
void System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.GrowCore (uint requiredMinCapacity) inline private
Definition at line 378 of file DefaultInterpolatedStringHandler.cs.
    {
        uint value = Math.Max(requiredMinCapacity, Math.Min((uint)(_chars.Length * 2), 1073741791u));
        int minimumLength = (int)Math.Clamp(value, 256u, 2147483647u);
        char[] array = ArrayPool<char>.Shared.Rent(minimumLength);
        _chars.Slice(0, _pos).CopyTo(array);
        char[] arrayToReturnToPool = _arrayToReturnToPool;
        _chars = (_arrayToReturnToPool = array);
        if (arrayToReturnToPool != null)
        {
            ArrayPool<char>.Shared.Return(arrayToReturnToPool);
        }
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._arrayToReturnToPool, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._chars, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler._pos, System.array, System.Math.Clamp(), System.Span< T >.Length, System.Math.Max(), System.Math.Min(), System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), and System.value.
Referenced by System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.Grow(), and System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.Grow().