Terraria: ResourcePackContentValidator.ValidateResourePack
ValidateResourePack()
void ResourcePackContentValidator.ValidateResourePack (ResourcePack pack) inline
     {
         //IL_0019: Unknown result type (might be due to invalid IL or missing references)
         if ((int)(AssetReaderCollection)Main.instance.Services.GetService(typeof(AssetReaderCollection)) != 0)
         {
             pack.GetContentSource().GetAllAssetsStartingWith("Images" + Path.DirectorySeparatorChar);
             VanillaContentValidator.Instance.GetValidImageFilePaths();
         }
     }
References IContentSource.GetAllAssetsStartingWith(), ResourcePack.GetContentSource(), VanillaContentValidator.GetValidImageFilePaths(), VanillaContentValidator.Instance, Main.instance, and Game.Services.