Terraria: System.Net.Http.HttpClient.PrepareCancellationTokenSource
PrepareCancellationTokenSource()
CancellationTokenSource bool CancellationTokenSource PendingRequestsCts System.Net.Http.HttpClient.PrepareCancellationTokenSource (CancellationToken cancellationToken) inline private
Definition at line 762 of file HttpClient.cs.
    {
        CancellationTokenSource pendingRequestsCts = _pendingRequestsCts;
        bool flag = _timeout != s_infiniteTimeout;
        if (flag || cancellationToken.CanBeCanceled)
        {
            CancellationTokenSource cancellationTokenSource = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, pendingRequestsCts.Token);
            if (flag)
            {
                cancellationTokenSource.CancelAfter(_timeout);
            }
            return (TokenSource: cancellationTokenSource, DisposeTokenSource: true, PendingRequestsCts: pendingRequestsCts);
        }
        return (TokenSource: pendingRequestsCts, DisposeTokenSource: false, PendingRequestsCts: pendingRequestsCts);
    }
Referenced by System.Net.Http.HttpClient.GetByteArrayAsyncCore(), System.Net.Http.HttpClient.GetStreamAsyncCore(), System.Net.Http.HttpClient.GetStringAsyncCore(), System.Net.Http.HttpClient.Send(), and System.Net.Http.HttpClient.SendAsync().