Terraria: System.Net.Http.HttpClient.CreateRequestMessage
CreateRequestMessage()
HttpRequestMessage System.Net.Http.HttpClient.CreateRequestMessage (HttpMethod method, Uri uri) inline private
Definition at line 787 of file HttpClient.cs.
    {
        return new HttpRequestMessage(method, uri)
        {
            Version = _defaultRequestVersion,
            VersionPolicy = _defaultVersionPolicy
        };
    }
References System.Net.Http.HttpClient._defaultRequestVersion, and System.Net.Http.HttpClient._defaultVersionPolicy.
Referenced by System.Net.Http.HttpClient.DeleteAsync(), System.Net.Http.HttpClient.GetAsync(), System.Net.Http.HttpClient.GetByteArrayAsync(), System.Net.Http.HttpClient.GetStreamAsync(), System.Net.Http.HttpClient.GetStringAsync(), System.Net.Http.HttpClient.PatchAsync(), System.Net.Http.HttpClient.PostAsync(), and System.Net.Http.HttpClient.PutAsync().