Terraria: System.Net.Http.HttpClient.GetStringAsyncCore
GetStringAsyncCore()
async Task< string > System.Net.Http.HttpClient.GetStringAsyncCore (HttpRequestMessage request, CancellationToken cancellationToken) inline private
Definition at line 178 of file HttpClient.cs.
    {
        bool telemetryStarted = StartSend(request);
        bool responseContentTelemetryStarted = false;
        (CancellationTokenSource, bool, CancellationTokenSource) tuple = PrepareCancellationTokenSource(cancellationToken);
        CancellationTokenSource cts = tuple.Item1;
        bool disposeCts = tuple.Item2;
        CancellationTokenSource pendingRequestsCts = tuple.Item3;
        HttpResponseMessage response = null;
        try
        {
            response = await base.SendAsync(request, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
            ThrowForNullResponse(response);
            response.EnsureSuccessStatusCode();
            HttpContent c = response.Content;
            if (HttpTelemetry.Log.IsEnabled() && telemetryStarted)
            {
                HttpTelemetry.Log.ResponseContentStart();
                responseContentTelemetryStarted = true;
            }
            Stream stream = c.TryReadAsStream();
            Stream stream2 = stream;
            if (stream2 == null)
            {
                stream2 = await c.ReadAsStreamAsync(cts.Token).ConfigureAwait(continueOnCapturedContext: false);
            }
            using Stream responseStream = stream2;
            using HttpContent.LimitArrayPoolWriteStream buffer = new HttpContent.LimitArrayPoolWriteStream(_maxResponseContentBufferSize, (int)c.Headers.ContentLength.GetValueOrDefault());
            _ = 2;
            try
            {
                await responseStream.CopyToAsync(buffer, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch (Exception e) when (HttpContent.StreamCopyExceptionNeedsWrapping(e))
            {
                throw HttpContent.WrapStreamCopyException(e);
            }
            if (buffer.Length > 0)
            {
                return HttpContent.ReadBufferAsString(buffer.GetBuffer(), c.Headers);
            }
            return string.Empty;
        }
        catch (Exception e2)
        {
            HandleFailure(e2, telemetryStarted, response, cts, cancellationToken, pendingRequestsCts);
            throw;
        }
        finally
        {
            FinishSend(cts, disposeCts, telemetryStarted, responseContentTelemetryStarted);
        }
    }
References System.Net.Http.HttpClient._maxResponseContentBufferSize, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.HttpResponseMessage.Content, System.Net.Http.Headers.HttpContentHeaders.ContentLength, System.IO.Stream.CopyToAsync(), System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode(), System.Net.Http.HttpClient.FinishSend(), System.Net.Http.HttpClient.HandleFailure(), System.Net.Http.HttpContent.Headers, System.Net.Http.HttpTelemetry.Log, System.Net.Http.HttpClient.PrepareCancellationTokenSource(), System.Net.Http.HttpContent.ReadAsStreamAsync(), System.Net.Http.HttpContent.ReadBufferAsString(), System.Net.Http.HttpClient.StartSend(), System.stream, System.Net.Http.HttpContent.StreamCopyExceptionNeedsWrapping(), System.Net.Http.HttpClient.ThrowForNullResponse(), System.Threading.CancellationTokenSource.Token, System.Net.Http.HttpContent.TryReadAsStream(), and System.Net.Http.HttpContent.WrapStreamCopyException().
Referenced by System.Net.Http.HttpClient.GetStringAsync().