Terraria: System.Net.Http.HttpClient.SendAsync
SendAsync() [1/4]
Task< HttpResponseMessage > System.Net.Http.HttpClient.SendAsync (HttpRequestMessage request) inline
Definition at line 541 of file HttpClient.cs.
    {
        return SendAsync(request, HttpCompletionOption.ResponseContentRead, CancellationToken.None);
    }
References System.Threading.CancellationToken.None, and System.Net.Http.HttpClient.SendAsync().
Referenced by System.Net.Http.HttpClient.DeleteAsync(), System.Net.Http.HttpClient.GetAsync(), System.Net.Http.HttpClient.PatchAsync(), System.Net.Http.HttpClient.PostAsync(), System.Net.Http.HttpClient.PutAsync(), System.Net.Http.HttpClient.SendAsync(), System.Net.Http.HttpClient.SendAsync(), and System.Net.Http.HttpClient.SendAsync().