Terraria: System.Net.Http.HttpClient.Send
Send() [4/4]
HttpResponseMessage System.Net.Http.HttpClient.Send (HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken) inline
Definition at line 505 of file HttpClient.cs.
    {
        CheckRequestBeforeSend(request);
        (CancellationTokenSource TokenSource, bool DisposeTokenSource, CancellationTokenSource PendingRequestsCts) tuple = PrepareCancellationTokenSource(cancellationToken);
        CancellationTokenSource item = tuple.TokenSource;
        bool item2 = tuple.DisposeTokenSource;
        CancellationTokenSource item3 = tuple.PendingRequestsCts;
        bool flag = StartSend(request);
        bool responseContentTelemetryStarted = false;
        HttpResponseMessage httpResponseMessage = null;
        try
        {
            httpResponseMessage = base.Send(request, item.Token);
            ThrowForNullResponse(httpResponseMessage);
            if (ShouldBufferResponse(completionOption, request))
            {
                if (HttpTelemetry.Log.IsEnabled() && flag)
                {
                    HttpTelemetry.Log.ResponseContentStart();
                    responseContentTelemetryStarted = true;
                }
                httpResponseMessage.Content.LoadIntoBuffer(_maxResponseContentBufferSize, item.Token);
            }
            return httpResponseMessage;
        }
        catch (Exception e)
        {
            HandleFailure(e, flag, httpResponseMessage, item, cancellationToken, item3);
            throw;
        }
        finally
        {
            FinishSend(item, item2, flag, responseContentTelemetryStarted);
        }
    }
References System.Net.Http.HttpClient._maxResponseContentBufferSize, System.cancellationToken, System.Net.Http.HttpClient.CheckRequestBeforeSend(), System.Net.Http.HttpResponseMessage.Content, System.Net.Http.HttpClient.DisposeTokenSource, System.Net.Http.HttpClient.FinishSend(), System.Net.Http.HttpClient.HandleFailure(), System.item, System.Net.Http.HttpContent.LoadIntoBuffer(), System.Net.Http.HttpTelemetry.Log, System.Net.Http.HttpClient.PrepareCancellationTokenSource(), System.Net.Http.HttpClient.ShouldBufferResponse(), System.Net.Http.HttpClient.StartSend(), System.Net.Http.HttpClient.ThrowForNullResponse(), and System.Net.Http.HttpClient.TokenSource.