Terraria: System.Net.Http.HttpClient.CheckRequestBeforeSend
CheckRequestBeforeSend()
void System.Net.Http.HttpClient.CheckRequestBeforeSend (HttpRequestMessage request) inline private
Definition at line 593 of file HttpClient.cs.
    {
        if (request == null)
        {
            throw new ArgumentNullException("request", System.SR.net_http_handler_norequest);
        }
        CheckDisposed();
        CheckRequestMessage(request);
        SetOperationStarted();
        PrepareRequestMessage(request);
    }
References System.Net.Http.HttpClient.CheckDisposed(), System.Net.Http.HttpClient.CheckRequestMessage(), System.SR.net_http_handler_norequest, System.Net.Http.HttpClient.PrepareRequestMessage(), and System.Net.Http.HttpClient.SetOperationStarted().
Referenced by System.Net.Http.HttpClient.GetByteArrayAsync(), System.Net.Http.HttpClient.GetStreamAsync(), System.Net.Http.HttpClient.GetStringAsync(), System.Net.Http.HttpClient.Send(), and System.Net.Http.HttpClient.SendAsync().