Terraria: System.Net.Http.HttpClient.GetStreamAsyncCore
GetStreamAsyncCore()
async Task< Stream > System.Net.Http.HttpClient.GetStreamAsyncCore (HttpRequestMessage request, CancellationToken cancellationToken) inline private
Definition at line 327 of file HttpClient.cs.
    {
        bool telemetryStarted = StartSend(request);
        (CancellationTokenSource, bool, CancellationTokenSource) tuple = PrepareCancellationTokenSource(cancellationToken);
        CancellationTokenSource cts = tuple.Item1;
        bool disposeCts = tuple.Item2;
        CancellationTokenSource pendingRequestsCts = tuple.Item3;
        HttpResponseMessage response = null;
        try
        {
            response = await base.SendAsync(request, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
            ThrowForNullResponse(response);
            response.EnsureSuccessStatusCode();
            HttpContent content = response.Content;
            Stream stream = content.TryReadAsStream();
            Stream stream2 = stream;
            if (stream2 == null)
            {
                stream2 = await content.ReadAsStreamAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            return stream2;
        }
        catch (Exception e)
        {
            HandleFailure(e, telemetryStarted, response, cts, cancellationToken, pendingRequestsCts);
            throw;
        }
        finally
        {
            FinishSend(cts, disposeCts, telemetryStarted, responseContentTelemetryStarted: false);
        }
    }
References System.cancellationToken, System.Net.Http.HttpResponseMessage.Content, System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode(), System.Net.Http.HttpClient.FinishSend(), System.Net.Http.HttpClient.HandleFailure(), System.Net.Http.HttpClient.PrepareCancellationTokenSource(), System.Net.Http.HttpContent.ReadAsStreamAsync(), System.Net.Http.HttpClient.StartSend(), System.stream, System.Net.Http.HttpClient.ThrowForNullResponse(), System.Threading.CancellationTokenSource.Token, and System.Net.Http.HttpContent.TryReadAsStream().
Referenced by System.Net.Http.HttpClient.GetStreamAsync().