Terraria: System.Net.Http.HttpClient.CheckDisposed
CheckDisposed()
void System.Net.Http.HttpClient.CheckDisposed () inline private
Definition at line 717 of file HttpClient.cs.
    {
        if (_disposed)
        {
            throw new ObjectDisposedException(GetType().ToString());
        }
    }
References System.Net.Http.HttpClient._disposed, and System.ToString.
Referenced by System.Net.Http.HttpClient.CancelPendingRequests(), System.Net.Http.HttpClient.CheckDisposedOrStarted(), and System.Net.Http.HttpClient.CheckRequestBeforeSend().