Terraria: System.Net.Http.HttpClient.CreateUri
CreateUri()
Uri System.Net.Http.HttpClient.CreateUri (string uri) inline private
Definition at line 778 of file HttpClient.cs.
    {
        if (!string.IsNullOrEmpty(uri))
        {
            return new Uri(uri, UriKind.RelativeOrAbsolute);
        }
        return null;
    }
Referenced by System.Net.Http.HttpClient.DeleteAsync(), System.Net.Http.HttpClient.DeleteAsync(), System.Net.Http.HttpClient.GetAsync(), System.Net.Http.HttpClient.GetAsync(), System.Net.Http.HttpClient.GetAsync(), System.Net.Http.HttpClient.GetAsync(), System.Net.Http.HttpClient.GetByteArrayAsync(), System.Net.Http.HttpClient.GetByteArrayAsync(), System.Net.Http.HttpClient.GetStreamAsync(), System.Net.Http.HttpClient.GetStreamAsync(), System.Net.Http.HttpClient.GetStringAsync(), System.Net.Http.HttpClient.GetStringAsync(), System.Net.Http.HttpClient.PatchAsync(), System.Net.Http.HttpClient.PatchAsync(), System.Net.Http.HttpClient.PostAsync(), System.Net.Http.HttpClient.PostAsync(), System.Net.Http.HttpClient.PutAsync(), and System.Net.Http.HttpClient.PutAsync().