Terraria: System.Net.Http.HttpClient.SendAsync
SendAsync() [4/4]
Task< HttpResponseMessage > System.Net.Http.HttpClient.SendAsync (HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken) inline
Definition at line 556 of file HttpClient.cs.
    {
        CheckRequestBeforeSend(request);
        var (cts2, disposeCts2, pendingRequestsCts2) = PrepareCancellationTokenSource(cancellationToken);
        return Core(request, completionOption, cts2, disposeCts2, pendingRequestsCts2, cancellationToken);
        async Task<HttpResponseMessage> Core(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, bool disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        {
            bool telemetryStarted = StartSend(request);
            bool responseContentTelemetryStarted = false;
            HttpResponseMessage response = null;
            try
            {
                response = await base.SendAsync(request, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
                ThrowForNullResponse(response);
                if (ShouldBufferResponse(completionOption, request))
                {
                    if (HttpTelemetry.Log.IsEnabled() && telemetryStarted)
                    {
                        HttpTelemetry.Log.ResponseContentStart();
                        responseContentTelemetryStarted = true;
                    }
                    await response.Content.LoadIntoBufferAsync(_maxResponseContentBufferSize, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
                }
                return response;
            }
            catch (Exception e)
            {
                HandleFailure(e, telemetryStarted, response, cts, originalCancellationToken, pendingRequestsCts);
                throw;
            }
            finally
            {
                FinishSend(cts, disposeCts, telemetryStarted, responseContentTelemetryStarted);
            }
        }
    }
References System.Net.Http.HttpClient._maxResponseContentBufferSize, System.cancellationToken, System.Net.Http.HttpClient.CheckRequestBeforeSend(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.HttpResponseMessage.Content, System.Net.Http.HttpClient.FinishSend(), System.Net.Http.HttpClient.HandleFailure(), System.Net.Http.HttpContent.LoadIntoBufferAsync(), System.Net.Http.HttpTelemetry.Log, System.Net.Http.HttpClient.PrepareCancellationTokenSource(), System.Net.Http.HttpClient.ShouldBufferResponse(), System.Net.Http.HttpClient.StartSend(), System.Net.Http.HttpClient.ThrowForNullResponse(), and System.Threading.CancellationTokenSource.Token.