Terraria: System.Threading.Channels.BoundedChannel.BoundedChannelWriter.TryWrite
TryWrite()
override bool System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter.TryWrite (T item) inline
Definition at line 221 of file BoundedChannel.cs.
        {
            AsyncOperation<T> asyncOperation = null;
            AsyncOperation<bool> listTail = null;
            BoundedChannel<T> parent = _parent;
            bool lockTaken = false;
            try
            {
                Monitor.Enter(parent.SyncObj, ref lockTaken);
                if (parent._doneWriting != null)
                {
                    return false;
                }
                int count = parent._items.Count;
                if (count != 0)
                {
                    if (count < parent._bufferedCapacity)
                    {
                        parent._items.EnqueueTail(item);
                        return true;
                    }
                    if (parent._mode == BoundedChannelFullMode.Wait)
                    {
                        return false;
                    }
                    if (parent._mode == BoundedChannelFullMode.DropWrite)
                    {
                        Monitor.Exit(parent.SyncObj);
                        lockTaken = false;
                        parent._itemDropped?.Invoke(item);
                        return true;
                    }
                    T obj = ((parent._mode == BoundedChannelFullMode.DropNewest) ? parent._items.DequeueTail() : parent._items.DequeueHead());
                    parent._items.EnqueueTail(item);
                    Monitor.Exit(parent.SyncObj);
                    lockTaken = false;
                    parent._itemDropped?.Invoke(obj);
                    return true;
                }
                while (!parent._blockedReaders.IsEmpty)
                {
                    AsyncOperation<T> asyncOperation2 = parent._blockedReaders.DequeueHead();
                    if (asyncOperation2.UnregisterCancellation())
                    {
                        asyncOperation = asyncOperation2;
                        break;
                    }
                }
                if (asyncOperation == null)
                {
                    parent._items.EnqueueTail(item);
                    listTail = parent._waitingReadersTail;
                    if (listTail == null)
                    {
                        return true;
                    }
                    parent._waitingReadersTail = null;
                }
            }
            finally
            {
                if (lockTaken)
                {
                    Monitor.Exit(parent.SyncObj);
                }
            }
            if (asyncOperation != null)
            {
                bool flag = asyncOperation.TrySetResult(item);
            }
            else
            {
                ChannelUtilities.WakeUpWaiters(ref listTail, result: true);
            }
            return true;
        }
References System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter._parent, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.item, System.obj, and System.Threading.Channels.ChannelUtilities.WakeUpWaiters().