Terraria: System.Net.Http.HttpClient.HandleFailure
HandleFailure()
void System.Net.Http.HttpClient.HandleFailure (Exception e, bool telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) inline private
Definition at line 622 of file HttpClient.cs.
    {
        HttpMessageInvoker.LogRequestFailed(telemetryStarted);
        response?.Dispose();
        Exception ex = null;
        if (e is OperationCanceledException ex2)
        {
            if (cancellationToken.IsCancellationRequested)
            {
                if (ex2.CancellationToken != cancellationToken)
                {
                    e = (ex = new TaskCanceledException(ex2.Message, ex2.InnerException, cancellationToken));
                }
            }
            else if (!pendingRequestsCts.IsCancellationRequested)
            {
                e = (ex = new TaskCanceledException(System.SR.Format(System.SR.net_http_request_timedout, _timeout.TotalSeconds), new TimeoutException(e.Message, e), ex2.CancellationToken));
            }
        }
        else if (e is HttpRequestException && cts.IsCancellationRequested)
        {
            e = (ex = new OperationCanceledException(cancellationToken.IsCancellationRequested ? cancellationToken : cts.Token));
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Error(this, e, "HandleFailure");
        }
        if (ex != null)
        {
            throw ex;
        }
    }
References System.Net.Http.HttpClient._timeout, System.cancellationToken, System.Net.Http.HttpResponseMessage.Dispose(), System.Net.NetEventSource.Error(), System.SR.Format(), System.Threading.CancellationTokenSource.IsCancellationRequested, System.Net.NetEventSource.Log, System.Net.Http.HttpMessageInvoker.LogRequestFailed(), System.Exception.Message, System.SR.net_http_request_timedout, System.Threading.CancellationTokenSource.Token, and System.TimeSpan.TotalSeconds.
Referenced by System.Net.Http.HttpClient.GetByteArrayAsyncCore(), System.Net.Http.HttpClient.GetStreamAsyncCore(), System.Net.Http.HttpClient.GetStringAsyncCore(), System.Net.Http.HttpClient.Send(), and System.Net.Http.HttpClient.SendAsync().