Terraria: Terraria.ID.Colors.InventoryDefaultColor
InventoryDefaultColor
readonly Color Terraria.ID.Colors.InventoryDefaultColor = new Color(63, 65, 151, 255) static
Referenced by Terraria.GameContent.UI.Elements.GroupOptionButton< T >.GroupOptionButton(), Terraria.GameContent.UI.Elements.UIIconTextButton.UIIconTextButton(), Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.ClickOption(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ClickTagOption(), Terraria.GameContent.Creative.CreativePowersHelper.CreateCategoryButton< T >(), Terraria.GameContent.Creative.CreativePowersHelper.CreateSimpleButton(), Terraria.GameContent.Creative.CreativePowersHelper.CreateToggleButton(), Terraria.GameContent.UI.Elements.UIIconTextButton.MouseOut(), Terraria.GameContent.UI.Elements.UIIconTextButton.MouseOver(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetTagsFromFoundEntry(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateButtonSelections(), and Terraria.GameContent.Creative.CreativePowersHelper.UpdateUnlockStateByPowerInternal().