Terraria: System.Net.Http.HttpClient.GetByteArrayAsyncCore
GetByteArrayAsyncCore()
async Task< byte[]> System.Net.Http.HttpClient.GetByteArrayAsyncCore (HttpRequestMessage request, CancellationToken cancellationToken) inline private
Definition at line 254 of file HttpClient.cs.
    {
        bool telemetryStarted = StartSend(request);
        bool responseContentTelemetryStarted = false;
        (CancellationTokenSource, bool, CancellationTokenSource) tuple = PrepareCancellationTokenSource(cancellationToken);
        CancellationTokenSource cts = tuple.Item1;
        bool disposeCts = tuple.Item2;
        CancellationTokenSource pendingRequestsCts = tuple.Item3;
        HttpResponseMessage response = null;
        try
        {
            response = await base.SendAsync(request, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
            ThrowForNullResponse(response);
            response.EnsureSuccessStatusCode();
            HttpContent content = response.Content;
            if (HttpTelemetry.Log.IsEnabled() && telemetryStarted)
            {
                HttpTelemetry.Log.ResponseContentStart();
                responseContentTelemetryStarted = true;
            }
            long? contentLength = content.Headers.ContentLength;
            using Stream buffer = (contentLength.HasValue ? ((Stream)new HttpContent.LimitMemoryStream(_maxResponseContentBufferSize, (int)contentLength.GetValueOrDefault())) : ((Stream)new HttpContent.LimitArrayPoolWriteStream(_maxResponseContentBufferSize)));
            Stream stream = content.TryReadAsStream();
            Stream stream2 = stream;
            if (stream2 == null)
            {
                stream2 = await content.ReadAsStreamAsync(cts.Token).ConfigureAwait(continueOnCapturedContext: false);
            }
            using Stream responseStream = stream2;
            _ = 2;
            try
            {
                await responseStream.CopyToAsync(buffer, cts.Token).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch (Exception e) when (HttpContent.StreamCopyExceptionNeedsWrapping(e))
            {
                throw HttpContent.WrapStreamCopyException(e);
            }
            return (buffer.Length == 0L) ? Array.Empty<byte>() : ((buffer is HttpContent.LimitMemoryStream limitMemoryStream) ? limitMemoryStream.GetSizedBuffer() : ((HttpContent.LimitArrayPoolWriteStream)buffer).ToArray());
        }
        catch (Exception e2)
        {
            HandleFailure(e2, telemetryStarted, response, cts, cancellationToken, pendingRequestsCts);
            throw;
        }
        finally
        {
            FinishSend(cts, disposeCts, telemetryStarted, responseContentTelemetryStarted);
        }
    }
References System.Net.Http.HttpClient._maxResponseContentBufferSize, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.HttpResponseMessage.Content, System.Net.Http.Headers.HttpContentHeaders.ContentLength, System.IO.Stream.CopyToAsync(), System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode(), System.Net.Http.HttpClient.FinishSend(), System.Net.Http.HttpClient.HandleFailure(), System.Net.Http.HttpContent.Headers, System.L, System.Net.Http.HttpTelemetry.Log, System.Net.Http.HttpClient.PrepareCancellationTokenSource(), System.Net.Http.HttpContent.ReadAsStreamAsync(), System.Net.Http.HttpClient.StartSend(), System.stream, System.Net.Http.HttpContent.StreamCopyExceptionNeedsWrapping(), System.Net.Http.HttpClient.ThrowForNullResponse(), System.Threading.CancellationTokenSource.Token, System.Net.Http.HttpContent.TryReadAsStream(), and System.Net.Http.HttpContent.WrapStreamCopyException().
Referenced by System.Net.Http.HttpClient.GetByteArrayAsync().