Terraria: System.Threading.Channels.BoundedChannel.BoundedChannelWriter.TryComplete
TryComplete() [1/2]
override bool System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter.TryComplete (Exception error) inline
Definition at line 197 of file BoundedChannel.cs.
        {
            BoundedChannel<T> parent = _parent;
            bool isEmpty;
            lock (parent.SyncObj)
            {
                if (parent._doneWriting != null)
                {
                    return false;
                }
                parent._doneWriting = error ?? ChannelUtilities.s_doneWritingSentinel;
                isEmpty = parent._items.IsEmpty;
            }
            if (isEmpty)
            {
                ChannelUtilities.Complete(parent._completion, error);
            }
            ChannelUtilities.FailOperations<AsyncOperation<T>, T>(parent._blockedReaders, ChannelUtilities.CreateInvalidCompletionException(error));
            ChannelUtilities.FailOperations<VoidAsyncOperationWithData<T>, VoidResult>(parent._blockedWriters, ChannelUtilities.CreateInvalidCompletionException(error));
            ChannelUtilities.WakeUpWaiters(ref parent._waitingReadersTail, result: false, error);
            ChannelUtilities.WakeUpWaiters(ref parent._waitingWritersTail, result: false, error);
            return true;
        }
References System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter._parent, System.Threading.Channels.ChannelUtilities.Complete(), System.Threading.Channels.ChannelUtilities.CreateInvalidCompletionException(), System.Threading.Channels.ChannelUtilities.s_doneWritingSentinel, and System.Threading.Channels.ChannelUtilities.WakeUpWaiters().