Terraria: System.Text.Json.JsonElement.EnumerateObject
EnumerateObject()
ObjectEnumerator System.Text.Json.JsonElement.EnumerateObject () inline
Definition at line 582 of file JsonElement.cs.
    {
        CheckValidInstance();
        JsonTokenType tokenType = TokenType;
        if (tokenType != JsonTokenType.StartObject)
        {
            throw ThrowHelper.GetJsonElementWrongTypeException(JsonTokenType.StartObject, tokenType);
        }
        return new ObjectEnumerator(this);
    }
References System.Text.Json.JsonElement.CheckValidInstance(), System.Text.Json.ThrowHelper.GetJsonElementWrongTypeException(), and System.Text.Json.JsonElement.TokenType.
Referenced by System.Text.Json.Nodes.JsonObject.InitializeIfRequired(), and System.Text.Json.JsonSerializer.TryGetReferenceFromJsonElement().