Terraria: System.Text.Json.JsonElement.CheckValidInstance
CheckValidInstance()
void System.Text.Json.JsonElement.CheckValidInstance () inline private
Definition at line 625 of file JsonElement.cs.
    {
        if (_parent == null)
        {
            throw new InvalidOperationException();
        }
    }
References System.Text.Json.JsonElement._parent.
Referenced by System.Text.Json.JsonElement.Clone(), System.Text.Json.JsonElement.EnumerateArray(), System.Text.Json.JsonElement.EnumerateObject(), System.Text.Json.JsonElement.GetArrayLength(), System.Text.Json.JsonElement.GetPropertyName(), System.Text.Json.JsonElement.GetPropertyRawText(), System.Text.Json.JsonElement.GetRawText(), System.Text.Json.JsonElement.GetRawValue(), System.Text.Json.JsonElement.GetString(), System.Text.Json.JsonElement.TextEqualsHelper(), System.Text.Json.JsonElement.TextEqualsHelper(), System.Text.Json.JsonElement.TryGetByte(), System.Text.Json.JsonElement.TryGetBytesFromBase64(), System.Text.Json.JsonElement.TryGetDateTime(), System.Text.Json.JsonElement.TryGetDateTimeOffset(), System.Text.Json.JsonElement.TryGetDecimal(), System.Text.Json.JsonElement.TryGetDouble(), System.Text.Json.JsonElement.TryGetGuid(), System.Text.Json.JsonElement.TryGetInt16(), System.Text.Json.JsonElement.TryGetInt32(), System.Text.Json.JsonElement.TryGetInt64(), System.Text.Json.JsonElement.TryGetProperty(), System.Text.Json.JsonElement.TryGetProperty(), System.Text.Json.JsonElement.TryGetSByte(), System.Text.Json.JsonElement.TryGetSingle(), System.Text.Json.JsonElement.TryGetUInt16(), System.Text.Json.JsonElement.TryGetUInt32(), System.Text.Json.JsonElement.TryGetUInt64(), and System.Text.Json.JsonElement.WriteTo().