Terraria: System.Transactions.CallContextCurrentData.ClearCurrentData
ClearCurrentData()
static void System.Transactions.CallContextCurrentData.ClearCurrentData (ContextKey contextKey, bool removeContextData) inline static
Definition at line 19 of file CallContextCurrentData.cs.
    {
        ContextKey value = s_currentTransaction.Value;
        if (contextKey != null || value != null)
        {
            if (removeContextData)
            {
                s_contextDataTable.Remove(contextKey ?? value);
            }
            if (value != null)
            {
                s_currentTransaction.Value = null;
            }
        }
    }
References System.Transactions.CallContextCurrentData.s_contextDataTable, System.Transactions.CallContextCurrentData.s_currentTransaction, and System.value.
Referenced by System.Transactions.ContextData.LookupContextData(), System.Transactions.TransactionScope.PopScope(), and System.Transactions.TransactionScope.PushScope().