Terraria: InGamePopups.AchievementUnlockedPopup.DrawInGame
DrawInGame()
void InGamePopups.AchievementUnlockedPopup.DrawInGame (SpriteBatch sb, Vector2 bottomAnchorPosition) inline
Implements IInGameNotification.
         {
             float opacity = Opacity;
             if (opacity > 0f)
             {
                 float num = Scale * 1.1f;
                 Vector2 size = (FontAssets.ItemStack.Value.MeasureString(_title) + new Vector2(58f, 10f)) * num;
                 Rectangle r = Utils.CenteredRectangle(bottomAnchorPosition + new Vector2(0f, (0f - size.Y) * 0.5f), size);
                 Vector2 mouseScreen = Main.MouseScreen;
                 bool num2 = r.Contains(mouseScreen.ToPoint());
                 Utils.DrawInvBG(c: num2 ? (new Color(64, 109, 164) * 0.75f) : (new Color(64, 109, 164) * 0.5f), sb: sb, R: r);
                 float num3 = num * 0.3f;
                 Vector2 vector = r.Right() - Vector2.UnitX * num * (12f + num3 * (float)_achievementIconFrame.Width);
                 sb.Draw(_achievementTexture.Value, vector, _achievementIconFrame, Color.White * opacity, 0f, new Vector2(0f, _achievementIconFrame.Height / 2), num3, SpriteEffects.None, 0f);
                 sb.Draw(_achievementBorderTexture.Value, vector, null, Color.White * opacity, 0f, new Vector2(0f, _achievementIconFrame.Height / 2), num3, SpriteEffects.None, 0f);
                 Utils.DrawBorderString(color: new Color(Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor / 5, Main.mouseTextColor) * opacity, sb: sb, text: _title, pos: vector - Vector2.UnitX * 10f, scale: num * 0.9f, anchorx: 1f, anchory: 0.4f);
                 if (num2)
                 {
                     OnMouseOver();
                 }
             }
         }
References InGamePopups.AchievementUnlockedPopup._achievementBorderTexture, InGamePopups.AchievementUnlockedPopup._achievementIconFrame, InGamePopups.AchievementUnlockedPopup._achievementTexture, InGamePopups.AchievementUnlockedPopup._title, Utils.CenteredRectangle(), Color, Utils.DrawBorderString(), Utils.DrawInvBG(), FontAssets.ItemStack, Main.MouseScreen, Main.mouseTextColor, InGamePopups.AchievementUnlockedPopup.OnMouseOver(), InGamePopups.AchievementUnlockedPopup.Opacity, R, InGamePopups.AchievementUnlockedPopup.Scale, and Asset< T >.Value.