Terraria: System.Linq.Parallel.SpoolingTask.SpoolStopAndGo< TInputOutput, TIgnoreKey >
SpoolStopAndGo< TInputOutput, TIgnoreKey >()
static void System.Linq.Parallel.SpoolingTask.SpoolStopAndGo< TInputOutput, TIgnoreKey > (QueryTaskGroupState groupState, PartitionedStream< TInputOutput, TIgnoreKey > partitions, SynchronousChannel< TInputOutput >[] channels, TaskScheduler taskScheduler) inline static package
Definition at line 7 of file SpoolingTask.cs.
    {
        Task task = new Task(delegate
        {
            int num = partitions.PartitionCount - 1;
            for (int i = 0; i < num; i++)
            {
                QueryTask queryTask = new StopAndGoSpoolingTask<TInputOutput, TIgnoreKey>(i, groupState, partitions[i], channels[i]);
                queryTask.RunAsynchronously(taskScheduler);
            }
            QueryTask queryTask2 = new StopAndGoSpoolingTask<TInputOutput, TIgnoreKey>(num, groupState, partitions[num], channels[num]);
            queryTask2.RunSynchronously(taskScheduler);
        });
        groupState.QueryBegin(task);
        task.RunSynchronously(taskScheduler);
        groupState.QueryEnd(userInitiatedDispose: false);
    }
References System.Linq.Parallel.QueryTaskGroupState.QueryBegin(), System.Linq.Parallel.QueryTaskGroupState.QueryEnd(), System.Linq.Parallel.QueryTask.RunAsynchronously(), System.Linq.Parallel.QueryTask.RunSynchronously(), and System.task.