Terraria: System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetParent
GetParent()
EntityHandle System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetParent (CustomAttributeHandle handle) inline package
Definition at line 45 of file CustomAttributeTableReader.cs.
    {
        int num = (handle.RowId - 1) * RowSize;
        return HasCustomAttributeTag.ConvertToHandle(Block.PeekTaggedReference(num + _ParentOffset, _IsHasCustomAttributeRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._IsHasCustomAttributeRefSizeSmall, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._ParentOffset, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.Block, System.Reflection.Metadata.Ecma335.HasCustomAttributeTag.ConvertToHandle(), System.Reflection.Internal.MemoryBlock.PeekTaggedReference(), and System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.RowSize.
Referenced by System.Reflection.Metadata.MetadataReader.CalculateCustomAttributeValueTreatment().