Terraria: System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetValue
GetValue()
BlobHandle System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetValue (CustomAttributeHandle handle) inline package
Definition at line 57 of file CustomAttributeTableReader.cs.
    {
        int num = (handle.RowId - 1) * RowSize;
        return BlobHandle.FromOffset(Block.PeekHeapReference(num + _ValueOffset, _IsBlobHeapRefSizeSmall));
    }
References System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._IsBlobHeapRefSizeSmall, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._ValueOffset, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.Block, System.Reflection.Metadata.BlobHandle.FromOffset(), System.Reflection.Internal.MemoryBlock.PeekHeapReference(), and System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.RowSize.
Referenced by System.Reflection.Metadata.CustomAttribute.GetProjectedValue(), and System.Reflection.Metadata.CustomAttribute.GetProjectedValue().