Terraria: System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.CustomAttributeTableReader
CustomAttributeTableReader()
System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.CustomAttributeTableReader (int numberOfRows, bool declaredSorted, int hasCustomAttributeRefSize, int customAttributeTypeRefSize, int blobHeapRefSize, MemoryBlock containingBlock, int containingBlockOffset) inline package
Definition at line 27 of file CustomAttributeTableReader.cs.
    {
        NumberOfRows = numberOfRows;
        _IsHasCustomAttributeRefSizeSmall = hasCustomAttributeRefSize == 2;
        _IsCustomAttributeTypeRefSizeSmall = customAttributeTypeRefSize == 2;
        _IsBlobHeapRefSizeSmall = blobHeapRefSize == 2;
        _ParentOffset = 0;
        _TypeOffset = _ParentOffset + hasCustomAttributeRefSize;
        _ValueOffset = _TypeOffset + customAttributeTypeRefSize;
        RowSize = _ValueOffset + blobHeapRefSize;
        Block = containingBlock.GetMemoryBlockAt(containingBlockOffset, RowSize * numberOfRows);
        PtrTable = null;
        if (!declaredSorted && !CheckSorted())
        {
            PtrTable = Block.BuildPtrTable(numberOfRows, RowSize, _ParentOffset, _IsHasCustomAttributeRefSizeSmall);
        }
    }
References System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._IsBlobHeapRefSizeSmall, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._IsCustomAttributeTypeRefSizeSmall, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._IsHasCustomAttributeRefSizeSmall, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._ParentOffset, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._TypeOffset, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader._ValueOffset, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.Block, System.Reflection.Internal.MemoryBlock.BuildPtrTable(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.CheckSorted(), System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.PtrTable, and System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.RowSize.