Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber
CompileFormatNumber()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber (QilNode value, QilNode formatPicture, QilNode formatName) inline private
Definition at line 2600 of file QilGenerator.cs.
    {
        XmlQualifiedName xmlQualifiedName;
        if (formatName != null)
        {
            xmlQualifiedName = ((formatName.NodeType != QilNodeType.LiteralString) ? null : ResolveQNameThrow(ignoreDefaultNs: true, formatName));
        }
        else
        {
            xmlQualifiedName = new XmlQualifiedName();
            formatName = _f.String(string.Empty);
        }
        if (xmlQualifiedName != null)
        {
            DecimalFormatDecl format;
            if (_compiler.DecimalFormats.Contains(xmlQualifiedName))
            {
                format = _compiler.DecimalFormats[xmlQualifiedName];
            }
            else
            {
                if (xmlQualifiedName != DecimalFormatDecl.Default.Name)
                {
                    throw new XslLoadException(System.SR.Xslt_NoDecimalFormat, (QilLiteral)formatName);
                }
                format = DecimalFormatDecl.Default;
            }
            if (formatPicture.NodeType == QilNodeType.LiteralString)
            {
                QilIterator qilIterator = _f.Let(_f.InvokeRegisterDecimalFormatter(formatPicture, format));
                qilIterator.DebugName = _f.QName("formatter" + _formatterCnt++, "urn:schemas-microsoft-com:xslt-debug").ToString();
                _gloVars.Add(qilIterator);
                return _f.InvokeFormatNumberStatic(value, qilIterator);
            }
            _formatNumberDynamicUsed = true;
            QilNode decimalFormatName = _f.QName(xmlQualifiedName.Name, xmlQualifiedName.Namespace);
            return _f.InvokeFormatNumberDynamic(value, formatPicture, decimalFormatName, formatName);
        }
        _formatNumberDynamicUsed = true;
        QilIterator qilIterator2 = _f.Let(formatName);
        QilNode decimalFormatName2 = ResolveQNameDynamic(ignoreDefaultNs: true, qilIterator2);
        return _f.Loop(qilIterator2, _f.InvokeFormatNumberDynamic(value, formatPicture, decimalFormatName2, qilIterator2));
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._formatNumberDynamicUsed, System.Xml.Xsl.Xslt.QilGenerator._formatterCnt, System.Xml.Xsl.Xslt.QilGenerator._gloVars, System.Xml.Xsl.Qil.QilNode.Add(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Contains(), System.Xml.Xsl.Xslt.Compiler.DecimalFormats, System.Xml.Xsl.Xslt.DecimalFormatDecl.Default, System.Xml.Dictionary, System.format, System.Xml.Xsl.Xslt.XsltQilFactory.InvokeFormatNumberDynamic(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeFormatNumberStatic(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeRegisterDecimalFormatter(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameThrow(), System.Xml.Xsl.Qil.QilPatternFactory.String(), System.Xml.Xsl.Qil.QilName.ToString(), System.value, and System.SR.Xslt_NoDecimalFormat.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().