Terraria: System.Xml.Xsl.Xslt.QilGenerator.InvokeOnCurrentNodeChanged
InvokeOnCurrentNodeChanged()
QilNode System.Xml.Xsl.Xslt.QilGenerator.InvokeOnCurrentNodeChanged () inline private
Definition at line 281 of file QilGenerator.cs.
    {
        QilIterator qilIterator;
        return _f.Loop(qilIterator = _f.Let(_f.InvokeOnCurrentNodeChanged(_curLoop.GetCurrent())), _f.Sequence());
    }
References System.Xml.Xsl.Xslt.QilGenerator._curLoop, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Dictionary, System.Xml.Xsl.Xslt.LoopFocus.GetCurrent(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeOnCurrentNodeChanged(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), and System.Xml.Xsl.Qil.QilPatternFactory.Sequence().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction(), and System.Xml.Xsl.Xslt.QilGenerator.WrapLoopBody().