Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileMatchPattern
CompileMatchPattern()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileMatchPattern (string pttrn) inline private
Definition at line 1854 of file QilGenerator.cs.
    {
        SetEnvironmentFlags(allowVariables: false, allowCurrent: false, allowKey: true);
        QilNode qilNode;
        try
        {
            XPathScanner scanner = new XPathScanner(pttrn);
            qilNode = _ptrnParser.Parse(scanner, _ptrnBuilder);
        }
        catch (XslLoadException ex)
        {
            if (_xslVersion != XslVersion.ForwardsCompatible)
            {
                ReportErrorInXPath(ex);
            }
            qilNode = _f.Loop(_f.For(_ptrnBuilder.FixupNode), _f.Error(_f.String(ex.Message)));
            XPathPatternBuilder.SetPriority(qilNode, 0.5);
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._ptrnBuilder, System.Xml.Xsl.Xslt.QilGenerator._ptrnParser, System.Xml.Xsl.Xslt.QilGenerator._xslVersion, System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Xslt.XPathPatternBuilder.FixupNode, System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Xslt.XPathPatternParser.Parse(), System.Xml.Xsl.Xslt.QilGenerator.ReportErrorInXPath(), System.Xml.Xsl.Xslt.QilGenerator.SetEnvironmentFlags(), System.Xml.Xsl.Xslt.XPathPatternBuilder.SetPriority(), and System.Xml.Xsl.Qil.QilPatternFactory.String().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAndSortMatches().