Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileKeyUse
CompileKeyUse()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileKeyUse (Key key) inline private
Definition at line 1919 of file QilGenerator.cs.
    {
        string use = key.Use;
        SetEnvironmentFlags(allowVariables: false, allowCurrent: true, allowKey: false);
        QilNode qilNode;
        if (use == null)
        {
            qilNode = _f.Error(_f.String(XslLoadException.CreateMessage(key.SourceLine, System.SR.Xslt_MissingAttribute, "use")));
        }
        else
        {
            try
            {
                XPathScanner scanner = new XPathScanner(use);
                qilNode = _xpathParser.Parse(scanner, _xpathBuilder, LexKind.Eof);
            }
            catch (XslLoadException ex)
            {
                if (_xslVersion != XslVersion.ForwardsCompatible)
                {
                    ReportErrorInXPath(ex);
                }
                qilNode = _f.Error(_f.String(ex.Message));
            }
        }
        if (qilNode is QilIterator)
        {
            qilNode = _f.Nop(qilNode);
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._xpathBuilder, System.Xml.Xsl.Xslt.QilGenerator._xpathParser, System.Xml.Xsl.Xslt.QilGenerator._xslVersion, System.Xml.Xsl.XslLoadException.CreateMessage(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.key, System.Xml.Xsl.Qil.QilPatternFactory.Nop(), System.Xml.Xsl.XPath.XPathParser< Node >.Parse(), System.Xml.Xsl.Xslt.QilGenerator.ReportErrorInXPath(), System.Xml.Xsl.Xslt.QilGenerator.SetEnvironmentFlags(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.SR.Xslt_MissingAttribute.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileKeys().