Terraria: System.Xml.Xsl.Xslt.QilGenerator.ExtractText
ExtractText()
QilNode System.Xml.Xsl.Xslt.QilGenerator.ExtractText (string source, ref int pos) inline private
Definition at line 855 of file QilGenerator.cs.
    {
        int num = pos;
        _unescapedText.Length = 0;
        int i;
        for (i = pos; i < source.Length; i++)
        {
            char c = source[i];
            if (c != '{' && c != '}')
            {
                continue;
            }
            if (i + 1 < source.Length && source[i + 1] == c)
            {
                i++;
                _unescapedText.Append(source, num, i - num);
                num = i + 1;
                continue;
            }
            if (c == '{')
            {
                break;
            }
            pos = source.Length;
            if (_xslVersion != XslVersion.ForwardsCompatible)
            {
                ReportError(System.SR.Xslt_SingleRightBraceInAvt, source);
                return null;
            }
            return _f.Error(_lastScope.SourceLine, System.SR.Xslt_SingleRightBraceInAvt, source);
        }
        pos = i;
        if (_unescapedText.Length == 0)
        {
            if (i <= num)
            {
                return null;
            }
            return _f.String(source.Substring(num, i - num));
        }
        _unescapedText.Append(source, num, i - num);
        return _f.String(_unescapedText.ToString());
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Xslt.QilGenerator._unescapedText, System.Xml.Xsl.Xslt.QilGenerator._xslVersion, System.Text.StringBuilder.Append(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Text.StringBuilder.Length, System.Xml.Xsl.Xslt.QilGenerator.ReportError(), System.source, System.Xml.Xsl.Xslt.XslNode.SourceLine, System.Xml.Xsl.Qil.QilPatternFactory.String(), System.Text.StringBuilder.ToString(), and System.SR.Xslt_SingleRightBraceInAvt.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAvt().