Terraria: System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefix
ResolvePrefix() [1/2]
string System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefix (bool ignoreDefaultNs, string prefix) inline private
Definition at line 2132 of file QilGenerator.cs.
    {
        if (ignoreDefaultNs && prefix.Length == 0)
        {
            return string.Empty;
        }
        string text = _scope.LookupNamespace(prefix);
        if (text == null)
        {
            if (prefix.Length == 0)
            {
                text = string.Empty;
            }
            else
            {
                ReportError(System.SR.Xslt_InvalidPrefix, prefix);
                text = _compiler.CreatePhantomNamespace();
            }
        }
        return text;
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Xslt.Compiler.CreatePhantomNamespace(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.LookupNamespace(), System.prefix, System.Xml.Xsl.Xslt.QilGenerator.ReportError(), System.text, and System.SR.Xslt_InvalidPrefix.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), and System.Xml.Xsl.Xslt.QilGenerator.CompileElement().