Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileProtoTemplate
CompileProtoTemplate()
void System.Xml.Xsl.Xslt.QilGenerator.CompileProtoTemplate (ProtoTemplate tmpl) inline private
Definition at line 584 of file QilGenerator.cs.
    {
        EnterScope(tmpl);
        _funcFocus.StartFocus(tmpl.Function.Arguments, (!IsDebug) ? tmpl.Flags : XslFlags.FocusFilter);
        foreach (QilParameter argument in tmpl.Function.Arguments)
        {
            if (argument.Name.NamespaceUri != "urn:schemas-microsoft-com:xslt-debug")
            {
                if (IsDebug)
                {
                    VarPar node = (VarPar)argument.Annotation;
                    QilList nsList = EnterScope(node);
                    argument.DefaultValue = CompileVarParValue(node);
                    ExitScope();
                    argument.DefaultValue = SetDebugNs(argument.DefaultValue, nsList);
                }
                _scope.AddVariable(argument.Name, argument);
            }
        }
        tmpl.Function.Definition = CompileInstructions(tmpl.Content);
        _funcFocus.StopFocus();
        ExitScope();
    }
References System.Xml.Xsl.Xslt.QilGenerator._funcFocus, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddVariable(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.EnterScope(), System.Xml.Xsl.Xslt.QilGenerator.ExitScope(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs(), System.Xml.Xsl.Xslt.FunctionFocus.StartFocus(), and System.Xml.Xsl.Xslt.FunctionFocus.StopFocus().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.Compile().