Terraria: System.Xml.Xsl.Xslt.QilGenerator.InstructionList
InstructionList()
QilList System.Xml.Xsl.Xslt.QilGenerator.InstructionList () inline private
Definition at line 608 of file QilGenerator.cs.
    {
        return _f.BaseFactory.Sequence();
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, and System.Xml.Xsl.Qil.QilFactory.Sequence().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileChoose(), System.Xml.Xsl.Xslt.QilGenerator.CompileCopy(), System.Xml.Xsl.Xslt.QilGenerator.CompileIf(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralElement(), System.Xml.Xsl.Xslt.QilGenerator.CompileTextAvt(), and System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue().