Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralElement
CompileLiteralElement()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralElement (XslNode node) inline private
Definition at line 712 of file QilGenerator.cs.
    {
        bool flag = true;
        while (true)
        {
            _prefixesInUse.Clear();
            QilName name = node.Name;
            string prefix = name.Prefix;
            string nsUri = name.NamespaceUri;
            _compiler.ApplyNsAliases(ref prefix, ref nsUri);
            if (flag)
            {
                _prefixesInUse.Add(prefix, nsUri);
            }
            else
            {
                prefix = name.Prefix;
            }
            _outputScope.PushScope();
            QilList content = InstructionList();
            CompilerScopeManager<QilIterator>.NamespaceEnumerator enumerator = _scope.GetEnumerator();
            while (true)
            {
                if (enumerator.MoveNext())
                {
                    CompilerScopeManager<QilIterator>.ScopeRecord current = enumerator.Current;
                    string prefix2 = current.ncName;
                    string nsUri2 = current.nsUri;
                    if (!(nsUri2 != "http://www.w3.org/1999/XSL/Transform") || _scope.IsExNamespace(nsUri2))
                    {
                        continue;
                    }
                    _compiler.ApplyNsAliases(ref prefix2, ref nsUri2);
                    if (flag)
                    {
                        if (_prefixesInUse.Contains(prefix2))
{
                            if ((string)_prefixesInUse[prefix2] != nsUri2)
{
                                break;
                            }
                        }
                        else
{
                            _prefixesInUse.Add(prefix2, nsUri2);
                        }
                    }
                    else
                    {
                        prefix2 = current.ncName;
                    }
                    AddNsDecl(content, prefix2, nsUri2);
                    continue;
                }
                QilNode content2 = CompileInstructions(node.Content, content);
                _outputScope.PopScope();
                name.Prefix = prefix;
                name.NamespaceUri = nsUri;
                return _f.ElementCtor(name, content2);
            }
            _outputScope.PopScope();
            flag = false;
        }
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._outputScope, System.Xml.Xsl.Xslt.QilGenerator._prefixesInUse, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Collections.Specialized.HybridDictionary.Add(), System.Xml.Xsl.Xslt.QilGenerator.AddNsDecl(), System.Xml.Xsl.Xslt.Compiler.ApplyNsAliases(), System.Collections.Specialized.HybridDictionary.Clear(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Collections.Specialized.HybridDictionary.Contains(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.ElementCtor(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.GetEnumerator(), System.Xml.Xsl.Xslt.QilGenerator.InstructionList(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.IsExNamespace(), System.Xml.Xsl.Xslt.OutputScopeManager.PopScope(), System.prefix, and System.Xml.Xsl.Xslt.OutputScopeManager.PushScope().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().