Terraria: System.Xml.Xsl.Xslt.QilGenerator.QilGenerator
QilGenerator()
System.Xml.Xsl.Xslt.QilGenerator.QilGenerator (bool debug) inline private
Definition at line 182 of file QilGenerator.cs.
    {
        _scope = new CompilerScopeManager<QilIterator>();
        _outputScope = new OutputScopeManager();
        _prefixesInUse = new HybridDictionary();
        _f = new XsltQilFactory(new QilFactory(), debug);
        _xpathBuilder = new XPathBuilder(this);
        _xpathParser = new XPathParser<QilNode>();
        _ptrnBuilder = new XPathPatternBuilder(this);
        _ptrnParser = new XPathPatternParser();
        _refReplacer = new ReferenceReplacer(_f.BaseFactory);
        _invkGen = new InvokeGenerator(_f, debug);
        _matcherBuilder = new MatcherBuilder(_f, _refReplacer, _invkGen);
        _singlFocus = new SingletonFocus(_f);
        _funcFocus = default(FunctionFocus);
        _curLoop = new LoopFocus(_f);
        _strConcat = new QilStrConcatenator(_f);
        _varHelper = new VariableHelper(_f);
        _elementOrDocumentType = XmlQueryTypeFactory.DocumentOrElement;
        _textOrAttributeType = XmlQueryTypeFactory.NodeChoice(XmlNodeKindFlags.Attribute | XmlNodeKindFlags.Text);
        _nameCurrent = _f.QName("current", "urn:schemas-microsoft-com:xslt-debug");
        _namePosition = _f.QName("position", "urn:schemas-microsoft-com:xslt-debug");
        _nameLast = _f.QName("last", "urn:schemas-microsoft-com:xslt-debug");
        _nameNamespaces = _f.QName("namespaces", "urn:schemas-microsoft-com:xslt-debug");
        _nameInit = _f.QName("init", "urn:schemas-microsoft-com:xslt-debug");
        _formatterCnt = 0;
    }
References System.Xml.Xsl.Xslt.QilGenerator._curLoop, System.Xml.Xsl.Xslt.QilGenerator._elementOrDocumentType, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._formatterCnt, System.Xml.Xsl.Xslt.QilGenerator._funcFocus, System.Xml.Xsl.Xslt.QilGenerator._invkGen, System.Xml.Xsl.Xslt.QilGenerator._matcherBuilder, System.Xml.Xsl.Xslt.QilGenerator._nameCurrent, System.Xml.Xsl.Xslt.QilGenerator._nameInit, System.Xml.Xsl.Xslt.QilGenerator._nameLast, System.Xml.Xsl.Xslt.QilGenerator._nameNamespaces, System.Xml.Xsl.Xslt.QilGenerator._namePosition, System.Xml.Xsl.Xslt.QilGenerator._outputScope, System.Xml.Xsl.Xslt.QilGenerator._prefixesInUse, System.Xml.Xsl.Xslt.QilGenerator._ptrnBuilder, System.Xml.Xsl.Xslt.QilGenerator._ptrnParser, System.Xml.Xsl.Xslt.QilGenerator._refReplacer, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Xslt.QilGenerator._singlFocus, System.Xml.Xsl.Xslt.QilGenerator._strConcat, System.Xml.Xsl.Xslt.QilGenerator._textOrAttributeType, System.Xml.Xsl.Xslt.QilGenerator._varHelper, System.Xml.Xsl.Xslt.QilGenerator._xpathBuilder, System.Xml.Xsl.Xslt.QilGenerator._xpathParser, System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.XmlQueryTypeFactory.DocumentOrElement, System.Xml.Xsl.XmlQueryTypeFactory.NodeChoice(), and System.Xml.Xsl.Qil.QilPatternFactory.QName().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileStylesheet().