Terraria: System.Xml.Xsl.Xslt.QilGenerator.AddDebugVariable
AddDebugVariable()
QilNode System.Xml.Xsl.Xslt.QilGenerator.AddDebugVariable (QilName name, QilNode value, QilNode content) inline private
Definition at line 2171 of file QilGenerator.cs.
    {
        QilIterator qilIterator = _f.Let(value);
        qilIterator.DebugName = name.ToString();
        return _f.Loop(qilIterator, content);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), and System.value.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.AddCurrentPositionLast(), and System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs().