Terraria: System.Xml.Xsl.Xslt.QilGenerator.Compile
Compile()
QilExpression System.Xml.Xsl.Xslt.QilGenerator.Compile (Compiler compiler) inline private
Definition at line 210 of file QilGenerator.cs.
    {
        _compiler = compiler;
        _functions = _f.FunctionList();
        _extPars = _f.GlobalParameterList();
        _gloVars = _f.GlobalVariableList();
        _nsVars = _f.GlobalVariableList();
        new XslAstRewriter().Rewrite(compiler);
        if (!IsDebug)
        {
            new XslAstAnalyzer().Analyze(compiler);
        }
        CreateGlobalVarPars();
        try
        {
            CompileKeys();
            CompileAndSortMatches(compiler.Root.Imports[0]);
            PrecompileProtoTemplatesHeaders();
            CompileGlobalVariables();
            foreach (ProtoTemplate allTemplate in compiler.AllTemplates)
            {
                CompileProtoTemplate(allTemplate);
            }
        }
        catch (XslLoadException ex)
        {
            ex.SetSourceLineInfo(_lastScope.SourceLine);
            throw;
        }
        catch (Exception ex2)
        {
            if (!XmlException.IsCatchableException(ex2))
            {
                throw;
            }
            throw new XslLoadException(ex2, _lastScope.SourceLine);
        }
        CompileInitializationCode();
        QilNode root = CompileRootExpression(compiler.StartApplyTemplates);
        foreach (ProtoTemplate allTemplate2 in compiler.AllTemplates)
        {
            foreach (QilParameter argument in allTemplate2.Function.Arguments)
            {
                if (!IsDebug || argument.Name.Equals(_nameNamespaces))
                {
                    argument.DefaultValue = null;
                }
            }
        }
        Scripts.TrimSafeDictionary scriptClasses = compiler.Scripts.ScriptClasses;
        List<EarlyBoundInfo> list = new List<EarlyBoundInfo>(scriptClasses.Count);
        foreach (string key in scriptClasses.Keys)
        {
            Type type = scriptClasses[key];
            if (type != null)
            {
                list.Add(new EarlyBoundInfo(key, type));
            }
        }
        QilExpression qilExpression = _f.QilExpression(root, _f.BaseFactory);
        qilExpression.EarlyBoundTypes = list;
        qilExpression.FunctionList = _functions;
        qilExpression.GlobalParameterList = _extPars;
        qilExpression.GlobalVariableList = _gloVars;
        qilExpression.WhitespaceRules = compiler.WhitespaceRules;
        qilExpression.IsDebug = IsDebug;
        qilExpression.DefaultWriterSettings = compiler.Output.Settings;
        QilDepthChecker.Check(qilExpression);
        return qilExpression;
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._extPars, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._functions, System.Xml.Xsl.Xslt.QilGenerator._gloVars, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Xslt.QilGenerator._nameNamespaces, System.Xml.Xsl.Xslt.QilGenerator._nsVars, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.XslAstAnalyzer.Analyze(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.Qil.QilDepthChecker.Check(), System.Xml.Xsl.Xslt.QilGenerator.CompileAndSortMatches(), System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVariables(), System.Xml.Xsl.Xslt.QilGenerator.CompileInitializationCode(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.Xslt.QilGenerator.CompileProtoTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileRootExpression(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Xslt.QilGenerator.CreateGlobalVarPars(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.FunctionList(), System.Xml.Xsl.Qil.QilPatternFactory.GlobalParameterList(), System.Xml.Xsl.Qil.QilPatternFactory.GlobalVariableList(), System.Xml.XmlException.IsCatchableException(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.list, System.Xml.Xsl.Xslt.QilGenerator.PrecompileProtoTemplatesHeaders(), System.Xml.Xsl.Qil.QilPatternFactory.QilExpression(), System.Xml.Xsl.Xslt.XslAstRewriter.Rewrite(), System.Xml.Xsl.Xslt.XslNode.SourceLine, and System.type.