Terraria: System.Xml.Xsl.Xslt.QilGenerator.EnterScope
EnterScope()
QilList System.Xml.Xsl.Xslt.QilGenerator.EnterScope (XslNode node) inline private
Definition at line 331 of file QilGenerator.cs.
    {
        _lastScope = node;
        _xslVersion = node.XslVersion;
        if (_scope.EnterScope(node.Namespaces))
        {
            return BuildDebuggerNamespaces();
        }
        return null;
    }
References System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Xslt.QilGenerator._xslVersion, System.Xml.Xsl.Xslt.QilGenerator.BuildDebuggerNamespaces(), System.Xml.Dictionary, and System.Xml.Xsl.Xslt.CompilerScopeManager< V >.EnterScope().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAndSortMatches(), System.Xml.Xsl.Xslt.QilGenerator.CompileChoose(), System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVarPar(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.Xslt.QilGenerator.CompileProtoTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileSort(), System.Xml.Xsl.Xslt.QilGenerator.CompileWithParam(), and System.Xml.Xsl.Xslt.QilGenerator.PrecompileProtoTemplatesHeaders().