Terraria: System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs
SetDebugNs()
QilNode System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs (QilNode n, QilList nsList) inline private
Definition at line 2178 of file QilGenerator.cs.
    {
        if (n != null && nsList != null)
        {
            QilNode qilNode = GetNsVar(nsList);
            if (qilNode.XmlType.Cardinality == XmlQueryCardinality.One)
            {
                qilNode = _f.TypeAssert(qilNode, XmlQueryTypeFactory.NamespaceS);
            }
            n = AddDebugVariable(CloneName(_nameNamespaces), qilNode, n);
        }
        return n;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._nameNamespaces, System.Xml.Xsl.Xslt.QilGenerator.AddDebugVariable(), System.Xml.Xsl.Xslt.QilGenerator.CloneName(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.GetNsVar(), System.Xml.Xsl.XmlQueryTypeFactory.NamespaceS, System.Xml.Xsl.XmlQueryCardinality.One, and System.Xml.Xsl.Qil.QilPatternFactory.TypeAssert().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileChoose(), System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVarPar(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileProtoTemplate(), and System.Xml.Xsl.Xslt.QilGenerator.CompileWithParam().