Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileNumber
CompileNumber()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileNumber (Number num) inline private
Definition at line 1637 of file QilGenerator.cs.
    {
        QilNode value;
        if (num.Value != null)
        {
            value = _f.ConvertToNumber(CompileXPathExpression(num.Value));
        }
        else
        {
            QilNode countPattern = ((num.Count != null) ? CompileNumberPattern(num.Count) : null);
            QilNode fromPattern = ((num.From != null) ? CompileNumberPattern(num.From) : null);
            value = num.Level switch
            {
                NumberLevel.Single => PlaceMarker(countPattern, fromPattern, multiple: false),
                NumberLevel.Multiple => PlaceMarker(countPattern, fromPattern, multiple: true),
                _ => PlaceMarkerAny(countPattern, fromPattern),
            };
        }
        bool forwardsCompatible = num.ForwardsCompatible;
        return _f.TextCtor(_f.InvokeNumberFormat(value, CompileStringAvt(num.Format), CompileLangAttributeToLcid(num.Lang, forwardsCompatible), CompileLetterValueAttribute(num.LetterValue, forwardsCompatible), CompileGroupingSeparatorAttribute(num.GroupingSeparator, forwardsCompatible), CompileGroupingSizeAttribute(num.GroupingSize, forwardsCompatible)));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSeparatorAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSizeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttributeToLcid(), System.Xml.Xsl.Xslt.QilGenerator.CompileLetterValueAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileNumberPattern(), System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Xsl.Xslt.Number.Count, System.Xml.Dictionary, System.Xml.Xsl.Xslt.Number.Format, System.Xml.Xsl.Xslt.XslNode.ForwardsCompatible, System.Xml.Xsl.Xslt.Number.From, System.Xml.Xsl.Xslt.Number.GroupingSeparator, System.Xml.Xsl.Xslt.Number.GroupingSize, System.Xml.Xsl.Xslt.XsltQilFactory.InvokeNumberFormat(), System.Xml.Xsl.Xslt.Number.Lang, System.Xml.Xsl.Xslt.Number.LetterValue, System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker(), System.Xml.Xsl.Xslt.QilGenerator.PlaceMarkerAny(), System.Xml.Xsl.Qil.QilPatternFactory.TextCtor(), System.value, and System.Xml.Xsl.Xslt.Number.Value.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().