Terraria: System.Xml.Xsl.Xslt.QilGenerator.MatchPattern
MatchPattern()
QilNode System.Xml.Xsl.Xslt.QilGenerator.MatchPattern (QilNode pattern, QilIterator testNode) inline private
Definition at line 1459 of file QilGenerator.cs.
    {
        if (pattern.NodeType == QilNodeType.Error)
        {
            return pattern;
        }
        QilList qilList;
        if (pattern.NodeType == QilNodeType.Sequence)
        {
            qilList = (QilList)pattern;
        }
        else
        {
            qilList = _f.BaseFactory.Sequence();
            qilList.Add(pattern);
        }
        QilNode qilNode = _f.False();
        int num = qilList.Count - 1;
        while (0 <= num)
        {
            QilLoop qilLoop = (QilLoop)qilList[num];
            qilNode = _f.Or(_refReplacer.Replace(qilLoop.Body, qilLoop.Variable, testNode), qilNode);
            num--;
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._refReplacer, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.False(), System.Xml.Xsl.Qil.QilPatternFactory.Or(), System.Xml.Xsl.Xslt.ReferenceReplacer.Replace(), and System.Xml.Xsl.Qil.QilFactory.Sequence().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.MatchCountPattern(), System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker(), and System.Xml.Xsl.Xslt.QilGenerator.PlaceMarkerAny().