Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey
CompileSingleKey() [3/3]
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey (QilNode name, QilNode key, IFocus env) inline private
Definition at line 2498 of file QilGenerator.cs.
    {
        if (name.NodeType == QilNodeType.LiteralString)
        {
            string text = (QilLiteral)name;
            _compiler.ParseQName(text, out var prefix, out var localName, default(ThrowErrorHelper));
            string uri = ResolvePrefixThrow(ignoreDefaultNs: true, prefix);
            QilName key2 = _f.QName(localName, uri, prefix);
            if (!_compiler.Keys.Contains(key2))
            {
                throw new XslLoadException(System.SR.Xslt_UndefinedKey, text);
            }
            return CompileSingleKey(_compiler.Keys[key2], key, env);
        }
        if (_generalKey == null)
        {
            _generalKey = CreateGeneralKeyFunction();
        }
        QilIterator qilIterator = _f.Let(name);
        QilNode qilNode = ResolveQNameDynamic(ignoreDefaultNs: true, qilIterator);
        QilNode body = _f.Invoke(_generalKey, _f.ActualParameterList(qilIterator, qilNode, key, env.GetCurrent()));
        return _f.Loop(qilIterator, body);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._generalKey, System.Xml.Xsl.Qil.QilPatternFactory.ActualParameterList(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Contains(), System.Xml.Xsl.Xslt.QilGenerator.CreateGeneralKeyFunction(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Invoke(), System.key, System.Xml.Xsl.Xslt.Compiler.Keys, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Xslt.Compiler.ParseQName(), System.prefix, System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefixThrow(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic(), System.text, and System.SR.Xslt_UndefinedKey.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey(), and System.Xml.Xsl.Xslt.QilGenerator.CreateGeneralKeyFunction().