Terraria: System.Xml.Xsl.Xslt.QilGenerator.AddRemoveImplicitArgs
AddRemoveImplicitArgs()
IList< XslNode > System.Xml.Xsl.Xslt.QilGenerator.AddRemoveImplicitArgs (IList< XslNode > args, XslFlags flags) inline private
Definition at line 1996 of file QilGenerator.cs.
    {
        if (IsDebug)
        {
            flags = XslFlags.FocusFilter;
        }
        if ((flags & XslFlags.FocusFilter) != 0)
        {
            if (args == null || args.IsReadOnly)
            {
                args = new List<XslNode>(3);
            }
            int num = 0;
            if ((flags & XslFlags.Current) != 0)
            {
                SetArg(args, num++, _nameCurrent, GetCurrentNode());
            }
            if ((flags & XslFlags.Position) != 0)
            {
                SetArg(args, num++, _namePosition, GetCurrentPosition());
            }
            if ((flags & XslFlags.Last) != 0)
            {
                SetArg(args, num++, _nameLast, GetLastPosition());
            }
        }
        return args;
    }
References System.Xml.Xsl.Xslt.QilGenerator._nameCurrent, System.Xml.Xsl.Xslt.QilGenerator._nameLast, System.Xml.Xsl.Xslt.QilGenerator._namePosition, System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.GetCurrentNode(), System.Xml.Xsl.Xslt.QilGenerator.GetCurrentPosition(), System.Xml.Xsl.Xslt.QilGenerator.GetLastPosition(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Collections.Generic.Dictionary< TKey, TValue >.IsReadOnly, and System.Xml.Xsl.Xslt.QilGenerator.SetArg().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileUseAttributeSet(), and System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction().