Terraria: System.Xml.Xsl.Xslt.QilGenerator.GetCurrentNode
GetCurrentNode()
QilNode System.Xml.Xsl.Xslt.QilGenerator.GetCurrentNode () inline private
Definition at line 363 of file QilGenerator.cs.
    {
        if (_curLoop.IsFocusSet)
        {
            return _curLoop.GetCurrent();
        }
        if (_funcFocus.IsFocusSet)
        {
            return _funcFocus.GetCurrent();
        }
        return _singlFocus.GetCurrent();
    }
References System.Xml.Xsl.Xslt.QilGenerator._curLoop, System.Xml.Xsl.Xslt.QilGenerator._funcFocus, System.Xml.Xsl.Xslt.QilGenerator._singlFocus, System.Xml.Xsl.Xslt.FunctionFocus.GetCurrent(), System.Xml.Xsl.Xslt.LoopFocus.GetCurrent(), System.Xml.Xsl.Xslt.SingletonFocus.GetCurrent(), System.Xml.Xsl.Xslt.FunctionFocus.IsFocusSet, and System.Xml.Xsl.Xslt.LoopFocus.IsFocusSet.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.AddCurrentPositionLast(), System.Xml.Xsl.Xslt.QilGenerator.AddRemoveImplicitArgs(), System.Xml.Xsl.Xslt.QilGenerator.CompileCopy(), System.Xml.Xsl.Xslt.QilGenerator.GetCurrent(), System.Xml.Xsl.Xslt.QilGenerator.MatchCountPattern(), System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker(), and System.Xml.Xsl.Xslt.QilGenerator.PlaceMarkerAny().