Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileInitializationCode
CompileInitializationCode()
void System.Xml.Xsl.Xslt.QilGenerator.CompileInitializationCode () inline private
Definition at line 287 of file QilGenerator.cs.
    {
        QilNode qilNode = _f.Int32(0);
        if (_formatNumberDynamicUsed || IsDebug)
        {
            bool flag = false;
            foreach (DecimalFormatDecl decimalFormat in _compiler.DecimalFormats)
            {
                qilNode = _f.Add(qilNode, _f.InvokeRegisterDecimalFormat(decimalFormat));
                flag |= decimalFormat.Name == DecimalFormatDecl.Default.Name;
            }
            if (!flag)
            {
                qilNode = _f.Add(qilNode, _f.InvokeRegisterDecimalFormat(DecimalFormatDecl.Default));
            }
        }
        foreach (string key in _compiler.Scripts.ScriptClasses.Keys)
        {
            qilNode = _f.Add(qilNode, _f.InvokeCheckScriptNamespace(key));
        }
        if (qilNode.NodeType == QilNodeType.Add)
        {
            QilFunction qilFunction = _f.Function(_f.FormalParameterList(), qilNode, _f.True());
            qilFunction.DebugName = "Init";
            _functions.Add(qilFunction);
            QilNode qilNode2 = _f.Invoke(qilFunction, _f.ActualParameterList());
            if (IsDebug)
            {
                qilNode2 = _f.TypeAssert(qilNode2, XmlQueryTypeFactory.ItemS);
            }
            QilIterator qilIterator = _f.Let(qilNode2);
            qilIterator.DebugName = _nameInit.ToString();
            _gloVars.Insert(0, qilIterator);
        }
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._formatNumberDynamicUsed, System.Xml.Xsl.Xslt.QilGenerator._functions, System.Xml.Xsl.Xslt.QilGenerator._gloVars, System.Xml.Xsl.Xslt.QilGenerator._nameInit, System.Xml.Xsl.Qil.QilPatternFactory.ActualParameterList(), System.Xml.Xsl.Qil.QilPatternFactory.Add(), System.Xml.Xsl.Qil.QilNode.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.Compiler.DecimalFormats, System.Xml.Xsl.Xslt.DecimalFormatDecl.Default, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.FormalParameterList(), System.Xml.Xsl.Qil.QilPatternFactory.Function(), System.Xml.Xsl.Qil.QilList.Insert(), System.Xml.Xsl.Qil.QilPatternFactory.Int32(), System.Xml.Xsl.Qil.QilPatternFactory.Invoke(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeCheckScriptNamespace(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeRegisterDecimalFormat(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.XmlQueryTypeFactory.ItemS, System.key, System.Xml.Xsl.Xslt.Scripts.TrimSafeDictionary.Keys, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Xslt.Scripts.ScriptClasses, System.Xml.Xsl.Xslt.Compiler.Scripts, System.Xml.Xsl.Qil.QilName.ToString(), System.Xml.Xsl.Qil.QilPatternFactory.True(), and System.Xml.Xsl.Qil.QilPatternFactory.TypeAssert().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.Compile().