Terraria: System.Xml.Xsl.Xslt.QilGenerator.WrapLoopBody
WrapLoopBody()
QilNode System.Xml.Xsl.Xslt.QilGenerator.WrapLoopBody (ISourceLineInfo before, QilNode expr, ISourceLineInfo after) inline private
Definition at line 989 of file QilGenerator.cs.
    {
        if (IsDebug)
        {
            return _f.Sequence(SetLineInfo(InvokeOnCurrentNodeChanged(), before), expr, SetLineInfo(_f.Nop(_f.Sequence()), after));
        }
        return expr;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator.InvokeOnCurrentNodeChanged(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.Qil.QilPatternFactory.Nop(), System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), and System.Xml.Xsl.Xslt.QilGenerator.SetLineInfo().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), and System.Xml.Xsl.Xslt.QilGenerator.CompileForEach().