Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey
CompileSingleKey() [2/3]
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey (List< Key > defList, QilNode key, IFocus env) inline private
Definition at line 2522 of file QilGenerator.cs.
    {
        if (defList.Count == 1)
        {
            return _f.Invoke(defList[0].Function, _f.ActualParameterList(env.GetCurrent(), key));
        }
        QilIterator qilIterator = _f.Let(key);
        QilNode qilNode = _f.Sequence();
        foreach (Key def in defList)
        {
            qilNode.Add(_f.Invoke(def.Function, _f.ActualParameterList(env.GetCurrent(), qilIterator)));
        }
        return _f.Loop(qilIterator, qilNode);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Qil.QilPatternFactory.ActualParameterList(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Qil.Function, System.Xml.Xsl.Qil.QilPatternFactory.Invoke(), System.key, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), and System.Xml.Xsl.Qil.QilPatternFactory.Sequence().