Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileTextAvt
CompileTextAvt()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileTextAvt (string avt) inline private
Definition at line 938 of file QilGenerator.cs.
    {
        if (avt.IndexOfAny(s_curlyBraces) == -1)
        {
            return _f.TextCtor(_f.String(avt));
        }
        QilNode qilNode = CompileAvt(avt);
        if (qilNode.NodeType == QilNodeType.Sequence)
        {
            QilList qilList = InstructionList();
            {
                foreach (QilNode item in qilNode)
                {
                    qilList.Add(_f.TextCtor(item));
                }
                return qilList;
            }
        }
        return _f.TextCtor(qilNode);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.QilGenerator.CompileAvt(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.InstructionList(), System.item, System.Xml.Xsl.Xslt.QilGenerator.s_curlyBraces, System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Xml.Xsl.Qil.QilPatternFactory.TextCtor().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralAttribute().