Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileElementAvailable
CompileElementAvailable()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileElementAvailable (QilNode name) inline private
Definition at line 2690 of file QilGenerator.cs.
    {
        if (name.NodeType == QilNodeType.LiteralString)
        {
            XmlQualifiedName xmlQualifiedName = ResolveQNameThrow(ignoreDefaultNs: false, name);
            if (EvaluateFuncCalls)
            {
                return _f.Boolean(IsElementAvailable(xmlQualifiedName));
            }
            name = _f.QName(xmlQualifiedName.Name, xmlQualifiedName.Namespace);
        }
        else
        {
            name = ResolveQNameDynamic(ignoreDefaultNs: false, name);
        }
        return _f.InvokeElementAvailable(name);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Qil.QilPatternFactory.Boolean(), System.Xml.Xsl.Xslt.QilGenerator.EvaluateFuncCalls, System.Xml.Xsl.Xslt.XsltQilFactory.InvokeElementAvailable(), System.Xml.Xsl.Xslt.QilGenerator.IsElementAvailable(), System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameThrow().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().