Terraria: System.Xml.Xsl.Xslt.QilGenerator.ResolveVariable
ResolveVariable()
QilNode IXPathEnvironment. System.Xml.Xsl.Xslt.QilGenerator.ResolveVariable (string prefix, string name) inline private
Implements System.Xml.Xsl.XPath.IXPathEnvironment.
Definition at line 2235 of file QilGenerator.cs.
    {
        if (!_allowVariables)
        {
            throw new XslLoadException(System.SR.Xslt_VariablesNotAllowed);
        }
        string uri = ResolvePrefixThrow(ignoreDefaultNs: true, prefix);
        QilNode qilNode = _scope.LookupVariable(name, uri);
        if (qilNode == null)
        {
            throw new XslLoadException(System.SR.Xslt_InvalidVariable, Compiler.ConstructQName(prefix, name));
        }
        XmlQueryType xmlType = qilNode.XmlType;
        if (qilNode.NodeType == QilNodeType.Parameter && xmlType.IsNode && xmlType.IsNotRtf && xmlType.MaybeMany && !xmlType.IsDod)
        {
            qilNode = _f.TypeAssert(qilNode, XmlQueryTypeFactory.NodeSDod);
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._allowVariables, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Xslt.Compiler.ConstructQName(), System.Xml.Dictionary, System.Xml.Xsl.XmlQueryType.IsDod, System.Xml.Xsl.XmlQueryType.IsNode, System.Xml.Xsl.XmlQueryType.IsNotRtf, System.Xml.Xsl.Xslt.CompilerScopeManager< V >.LookupVariable(), System.Xml.Xsl.XmlQueryType.MaybeMany, System.Xml.Xsl.XmlQueryTypeFactory.NodeSDod, System.prefix, System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefixThrow(), System.Xml.Xsl.Qil.QilPatternFactory.TypeAssert(), System.SR.Xslt_InvalidVariable, and System.SR.Xslt_VariablesNotAllowed.