Terraria: System.Xml.Xsl.Xslt.QilGenerator.ReportErrorInXPath
ReportErrorInXPath()
void System.Xml.Xsl.Xslt.QilGenerator.ReportErrorInXPath (XslLoadException e) inline private
Definition at line 1766 of file QilGenerator.cs.
    {
        string text = ((e is XPathCompileException ex) ? ex.FormatDetailedMessage() : e.Message);
        _compiler.ReportError(_lastScope.SourceLine, System.SR.Xml_UserException, text);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Dictionary, System.Xml.Xsl.XsltException.Message, System.Xml.Xsl.Xslt.Compiler.ReportError(), System.Xml.Xsl.Xslt.XslNode.SourceLine, System.text, and System.SR.Xml_UserException.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileKeyMatch(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeyUse(), System.Xml.Xsl.Xslt.QilGenerator.CompileMatchPattern(), System.Xml.Xsl.Xslt.QilGenerator.CompileNodeSetExpression(), System.Xml.Xsl.Xslt.QilGenerator.CompileNumberPattern(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), and System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpressionWithinAvt().