Terraria: System.Xml.Xsl.Xslt.QilGenerator.GetLastPosition
GetLastPosition()
QilNode System.Xml.Xsl.Xslt.QilGenerator.GetLastPosition () inline private
Definition at line 389 of file QilGenerator.cs.
    {
        if (_curLoop.IsFocusSet)
        {
            return _curLoop.GetLast();
        }
        if (_funcFocus.IsFocusSet)
        {
            return _funcFocus.GetLast();
        }
        return _singlFocus.GetLast();
    }
References System.Xml.Xsl.Xslt.QilGenerator._curLoop, System.Xml.Xsl.Xslt.QilGenerator._funcFocus, System.Xml.Xsl.Xslt.QilGenerator._singlFocus, System.Xml.Xsl.Xslt.FunctionFocus.GetLast(), System.Xml.Xsl.Xslt.LoopFocus.GetLast(), System.Xml.Xsl.Xslt.SingletonFocus.GetLast(), System.Xml.Xsl.Xslt.FunctionFocus.IsFocusSet, and System.Xml.Xsl.Xslt.LoopFocus.IsFocusSet.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.AddCurrentPositionLast(), System.Xml.Xsl.Xslt.QilGenerator.AddRemoveImplicitArgs(), and System.Xml.Xsl.Xslt.QilGenerator.GetLast().