Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSeparatorAttribute
CompileGroupingSeparatorAttribute()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSeparatorAttribute (string attValue, bool fwdCompat) inline private
Definition at line 1589 of file QilGenerator.cs.
    {
        QilNode qilNode = CompileStringAvt(attValue);
        if (qilNode == null)
        {
            qilNode = _f.String(string.Empty);
        }
        else if (qilNode.NodeType == QilNodeType.LiteralString)
        {
            string text = (QilLiteral)qilNode;
            if (text.Length != 1)
            {
                if (!fwdCompat)
                {
                    ReportError(System.SR.Xslt_CharAttribute, "grouping-separator");
                }
                qilNode = _f.String(string.Empty);
            }
        }
        else
        {
            QilIterator qilIterator = _f.Let(qilNode);
            qilNode = _f.Loop(qilIterator, _f.Conditional(_f.Eq(_f.StrLength(qilIterator), _f.Int32(1)), qilIterator, fwdCompat ? _f.String(string.Empty) : _f.Error(_lastScope.SourceLine, System.SR.Xslt_CharAttribute, "grouping-separator")));
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Qil.QilPatternFactory.Int32(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Xslt.QilGenerator.ReportError(), System.Xml.Xsl.Xslt.XslNode.SourceLine, System.Xml.Xsl.Qil.QilPatternFactory.String(), System.Xml.Xsl.Qil.QilPatternFactory.StrLength(), System.text, and System.SR.Xslt_CharAttribute.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileNumber().