Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt
CompileStringAvt()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt (string avt) inline private
Definition at line 925 of file QilGenerator.cs.
    {
        if (avt == null)
        {
            return null;
        }
        if (avt.IndexOfAny(s_curlyBraces) == -1)
        {
            return _f.String(avt);
        }
        return _f.StrConcat(CompileAvt(avt));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator.CompileAvt(), System.Xml.Xsl.Xslt.QilGenerator.s_curlyBraces, System.Xml.Xsl.Qil.QilPatternFactory.StrConcat(), and System.Xml.Xsl.Qil.QilPatternFactory.String().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileElement(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSeparatorAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSizeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttributeToLcid(), System.Xml.Xsl.Xslt.QilGenerator.CompileLetterValueAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileOrderAttribute(), and System.Xml.Xsl.Xslt.QilGenerator.CompilePI().