Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileSort
CompileSort()
void System.Xml.Xsl.Xslt.QilGenerator.CompileSort (Sort sort, QilList keyList, ref LoopFocus parentLoop) inline private
Definition at line 1405 of file QilGenerator.cs.
    {
        EnterScope(sort);
        bool forwardsCompatible = sort.ForwardsCompatible;
        QilNode select = CompileXPathExpression(sort.Select);
        QilNode value;
        QilNode select2;
        QilNode qilNode;
        QilNode qilNode2;
        if (sort.Lang != null || sort.DataType != null || sort.Order != null || sort.CaseOrder != null)
        {
            LoopFocus curLoop = _curLoop;
            _curLoop = parentLoop;
            value = CompileLangAttribute(sort.Lang, forwardsCompatible);
            CompileDataTypeAttribute(sort.DataType, forwardsCompatible, ref select, out select2);
            qilNode = CompileOrderAttribute("order", sort.Order, "ascending", "descending", forwardsCompatible);
            qilNode2 = CompileOrderAttribute("case-order", sort.CaseOrder, "lower-first", "upper-first", forwardsCompatible);
            _curLoop = curLoop;
        }
        else
        {
            select = _f.ConvertToString(select);
            select2 = (value = (qilNode = (qilNode2 = null)));
        }
        _strConcat.Reset();
        _strConcat.Append("http://collations.microsoft.com");
        _strConcat.Append('/');
        _strConcat.Append(value);
        char value2 = '?';
        if (qilNode != null)
        {
            _strConcat.Append(value2);
            _strConcat.Append("descendingOrder=");
            _strConcat.Append(qilNode);
            value2 = '&';
        }
        if (qilNode2 != null)
        {
            _strConcat.Append(value2);
            _strConcat.Append("upperFirst=");
            _strConcat.Append(qilNode2);
            value2 = '&';
        }
        QilNode qilNode3 = _strConcat.ToQil();
        QilSortKey node = _f.SortKey(select, qilNode3);
        keyList.Add(node);
        if (select2 != null)
        {
            node = _f.SortKey(select2, qilNode3.DeepClone(_f.BaseFactory));
            keyList.Add(node);
        }
        ExitScope();
    }
References System.Xml.Xsl.Xslt.QilGenerator._curLoop, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._strConcat, System.Xml.Xsl.Qil.QilNode.Add(), System.Xml.Xsl.Xslt.QilStrConcatenator.Append(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileOrderAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.EnterScope(), System.Xml.Xsl.Xslt.QilGenerator.ExitScope(), System.Xml.Xsl.Xslt.QilStrConcatenator.Reset(), System.Xml.Xsl.Qil.QilPatternFactory.SortKey(), System.Xml.Xsl.Xslt.QilStrConcatenator.ToQil(), and System.value.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileSorts().