Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttribute
CompileLangAttribute()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttribute (string attValue, bool fwdCompat) inline private
Definition at line 1296 of file QilGenerator.cs.
    {
        QilNode qilNode = CompileStringAvt(attValue);
        if (qilNode != null)
        {
            if (qilNode.NodeType == QilNodeType.LiteralString)
            {
                string lang = (QilLiteral)qilNode;
                string text = XsltLibrary.LangToNameInternal(lang, fwdCompat, this);
                if (text == "")
                {
                    qilNode = null;
                }
            }
            else
            {
                QilIterator qilIterator;
                qilNode = _f.Loop(qilIterator = _f.Let(qilNode), _f.Conditional(_f.Eq(_f.InvokeLangToLcid(qilIterator, fwdCompat), _f.Int32(127)), _f.String(string.Empty), qilIterator));
            }
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.Qil.QilPatternFactory.Int32(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeLangToLcid(), System.Xml.Xsl.Runtime.XsltLibrary.LangToNameInternal(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.text.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileSort().