Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument
CompileFnDocument()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument (QilNode uris, QilNode baseNode) inline private
Definition at line 2570 of file QilGenerator.cs.
    {
        if (!_compiler.Settings.EnableDocumentFunction)
        {
            ReportWarning(System.SR.Xslt_DocumentFuncProhibited);
            return _f.Error(_lastScope.SourceLine, System.SR.Xslt_DocumentFuncProhibited);
        }
        QilIterator qilIterator;
        if (uris.XmlType.IsNode)
        {
            return _f.DocOrderDistinct(_f.Loop(qilIterator = _f.For(uris), CompileSingleDocument(_f.ConvertToString(qilIterator), baseNode ?? qilIterator)));
        }
        if (uris.XmlType.IsAtomicValue)
        {
            return CompileSingleDocument(_f.ConvertToString(uris), baseNode);
        }
        QilIterator qilIterator2 = _f.Let(uris);
        QilIterator qilIterator3 = ((baseNode != null) ? _f.Let(baseNode) : null);
        QilNode qilNode = _f.Conditional(_f.Not(_f.IsType(qilIterator2, XmlQueryTypeFactory.AnyAtomicType)), _f.DocOrderDistinct(_f.Loop(qilIterator = _f.For(_f.TypeAssert(qilIterator2, XmlQueryTypeFactory.NodeS)), CompileSingleDocument(_f.ConvertToString(qilIterator), qilIterator3 ?? qilIterator))), CompileSingleDocument(_f.XsltConvert(qilIterator2, XmlQueryTypeFactory.StringX), qilIterator3));
        qilNode = ((baseNode != null) ? _f.Loop(qilIterator3, qilNode) : qilNode);
        return _f.Loop(qilIterator2, qilNode);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.XmlQueryTypeFactory.AnyAtomicType, System.Xml.Xsl.Xslt.QilGenerator.CompileSingleDocument(), System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.DocOrderDistinct(), System.Xml.Xsl.XsltSettings.EnableDocumentFunction, System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.IsType(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.XmlQueryTypeFactory.NodeS, System.Xml.Xsl.Qil.QilPatternFactory.Not(), System.Xml.Xsl.Xslt.QilGenerator.ReportWarning(), System.Xml.Xsl.Xslt.Compiler.Settings, System.Xml.Xsl.Xslt.XslNode.SourceLine, System.Xml.Xsl.XmlQueryTypeFactory.StringX, System.Xml.Xsl.Qil.QilPatternFactory.TypeAssert(), System.SR.Xslt_DocumentFuncProhibited, and System.Xml.Xsl.Qil.QilPatternFactory.XsltConvert().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().