Terraria: System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefixThrow
ResolvePrefixThrow()
string System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefixThrow (bool ignoreDefaultNs, string prefix) inline private
Definition at line 2383 of file QilGenerator.cs.
    {
        if (ignoreDefaultNs && prefix.Length == 0)
        {
            return string.Empty;
        }
        string text = _scope.LookupNamespace(prefix);
        if (text == null)
        {
            if (prefix.Length != 0)
            {
                throw new XslLoadException(System.SR.Xslt_InvalidPrefix, prefix);
            }
            text = string.Empty;
        }
        return text;
    }
References System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Xslt.CompilerScopeManager< V >.LookupNamespace(), System.prefix, System.text, and System.SR.Xslt_InvalidPrefix.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey(), System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction(), System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefix(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameThrow(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveVariable().