Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpressionWithinAvt
CompileXPathExpressionWithinAvt()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpressionWithinAvt (string expr, ref int pos) inline private
Definition at line 1828 of file QilGenerator.cs.
    {
        SetEnvironmentFlags(allowVariables: true, allowCurrent: true, allowKey: true);
        QilNode qilNode;
        try
        {
            XPathScanner xPathScanner = new XPathScanner(expr, pos);
            qilNode = _xpathParser.Parse(xPathScanner, _xpathBuilder, LexKind.RBrace);
            pos = xPathScanner.LexStart + 1;
        }
        catch (XslLoadException ex)
        {
            if (_xslVersion != XslVersion.ForwardsCompatible)
            {
                ReportErrorInXPath(ex);
            }
            qilNode = _f.Error(_f.String(ex.Message));
            pos = expr.Length;
        }
        if (qilNode is QilIterator)
        {
            qilNode = _f.Nop(qilNode);
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._xpathBuilder, System.Xml.Xsl.Xslt.QilGenerator._xpathParser, System.Xml.Xsl.Xslt.QilGenerator._xslVersion, System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Qil.QilPatternFactory.Nop(), System.Xml.Xsl.XPath.XPathParser< Node >.Parse(), System.Xml.Xsl.Xslt.QilGenerator.ReportErrorInXPath(), System.Xml.Xsl.Xslt.QilGenerator.SetEnvironmentFlags(), and System.Xml.Xsl.Qil.QilPatternFactory.String().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAvt().