Terraria: System.Xml.Xsl.Xslt.QilGenerator.IsFunctionAvailable
IsFunctionAvailable()
static bool System.Xml.Xsl.Xslt.QilGenerator.IsFunctionAvailable (string localName, string nsUri) inline static
Definition at line 2416 of file QilGenerator.cs.
    {
        if (XPathBuilder.IsFunctionAvailable(localName, nsUri))
        {
            return true;
        }
        if (nsUri.Length == 0)
        {
            if (FunctionTable.ContainsKey(localName))
            {
                return localName != "unparsed-entity-uri";
            }
            return false;
        }
        if (nsUri == "urn:schemas-microsoft-com:xslt")
        {
            switch (localName)
            {
            default:
                return localName == "utc";
            case "node-set":
            case "format-date":
            case "format-time":
            case "local-name":
            case "namespace-uri":
            case "number":
            case "string-compare":
                return true;
            }
        }
        if (nsUri == "http://exslt.org/common")
        {
            if (!(localName == "node-set"))
            {
                return localName == "object-type";
            }
            return true;
        }
        return false;
    }
References System.Xml.Xsl.Xslt.QilGenerator.FunctionTable, and System.Xml.Xsl.XPath.XPathBuilder.IsFunctionAvailable().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileFunctionAvailable(), and System.Xml.Xsl.Runtime.XsltLibrary.FunctionAvailableHelper().