Terraria: System.Xml.Xsl.Xslt.QilGenerator.FunctionTable
FunctionTable
Dictionary<string, XPathBuilder.FunctionInfo<FuncId> > System.Xml.Xsl.Xslt.QilGenerator.FunctionTable = CreateFunctionTable() static
Definition at line 167 of file QilGenerator.cs.
Referenced by System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.Function(), System.Xml.Xsl.Xslt.QilGenerator.IsFunctionAvailable(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().