Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileText
CompileText()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileText (Text node) inline private
Definition at line 959 of file QilGenerator.cs.
    {
        if (node.Hints == SerializationHints.None)
        {
            return _f.TextCtor(_f.String(node.Select));
        }
        return _f.RawTextCtor(_f.String(node.Select));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Qil.QilPatternFactory.RawTextCtor(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Xml.Xsl.Qil.QilPatternFactory.TextCtor().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().