Terraria: System.Xml.Xsl.Xslt.QilGenerator.EXslObjectType
EXslObjectType()
QilNode System.Xml.Xsl.Xslt.QilGenerator.EXslObjectType (QilNode n) inline private
Definition at line 2735 of file QilGenerator.cs.
    {
        if (EvaluateFuncCalls)
        {
            switch (n.XmlType.TypeCode)
            {
            case XmlTypeCode.Boolean:
                return _f.String("boolean");
            case XmlTypeCode.Double:
                return _f.String("number");
            case XmlTypeCode.String:
                return _f.String("string");
            }
            if (n.XmlType.IsNode && n.XmlType.IsNotRtf)
            {
                return _f.String("node-set");
            }
        }
        return _f.InvokeEXslObjectType(n);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator.EvaluateFuncCalls, System.Xml.Xsl.Xslt.XsltQilFactory.InvokeEXslObjectType(), and System.Xml.Xsl.Qil.QilPatternFactory.String().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().