Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileMessage
CompileMessage()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileMessage (XslNode node) inline private
Definition at line 1211 of file QilGenerator.cs.
    {
        string uri = _lastScope.SourceLine.Uri;
        QilNode n = _f.RtfCtor(CompileInstructions(node.Content), _f.String(uri));
        n = _f.InvokeOuterXml(n);
        if (!(bool)node.Arg)
        {
            return _f.Warning(n);
        }
        QilIterator text;
        return _f.Loop(text = _f.Let(n), _f.Sequence(_f.Warning(text), _f.Error(text)));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeOuterXml(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.RtfCtor(), System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), System.Xml.Xsl.Xslt.XslNode.SourceLine, System.Xml.Xsl.Qil.QilPatternFactory.String(), System.text, System.Xml.Xsl.ISourceLineInfo.Uri, and System.Xml.Xsl.Qil.QilPatternFactory.Warning().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().