Terraria: System.Xml.Xsl.Xslt.QilGenerator.GenerateApply
GenerateApply()
QilNode System.Xml.Xsl.Xslt.QilGenerator.GenerateApply (StylesheetLevel sheet, XslNode node) inline private
Definition at line 1972 of file QilGenerator.cs.
    {
        if (_compiler.Settings.CheckOnly)
        {
            return _f.Sequence();
        }
        return InvokeApplyFunction(sheet, node.Name, node.Content);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.XsltSettings.CheckOnly, System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction(), System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), and System.Xml.Xsl.Xslt.Compiler.Settings.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyImports(), System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), and System.Xml.Xsl.Xslt.QilGenerator.CompileRootExpression().