Terraria: System.Xml.Xsl.Xslt.QilGenerator.AddNsDecl
AddNsDecl()
void System.Xml.Xsl.Xslt.QilGenerator.AddNsDecl (QilList content, string prefix, string nsUri) inline private
Definition at line 703 of file QilGenerator.cs.
    {
        if (!(_outputScope.LookupNamespace(prefix) == nsUri))
        {
            _outputScope.AddNamespace(prefix, nsUri);
            content.Add(_f.NamespaceDecl(_f.String(prefix), _f.String(nsUri)));
        }
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._outputScope, System.Xml.Xsl.Qil.QilNode.Add(), System.Xml.Xsl.Xslt.OutputScopeManager.AddNamespace(), System.Xml.Xsl.Xslt.OutputScopeManager.LookupNamespace(), System.Xml.Xsl.Qil.QilPatternFactory.NamespaceDecl(), System.prefix, and System.Xml.Xsl.Qil.QilPatternFactory.String().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralElement().