Terraria: System.Xml.Xsl.Xslt.QilGenerator.BuildDebuggerNamespaces
BuildDebuggerNamespaces()
QilList System.Xml.Xsl.Xslt.QilGenerator.BuildDebuggerNamespaces () inline private
Definition at line 347 of file QilGenerator.cs.
    {
        if (IsDebug)
        {
            QilList qilList = _f.BaseFactory.Sequence();
            CompilerScopeManager<QilIterator>.NamespaceEnumerator enumerator = _scope.GetEnumerator();
            while (enumerator.MoveNext())
            {
                CompilerScopeManager<QilIterator>.ScopeRecord current = enumerator.Current;
                qilList.Add(_f.NamespaceDecl(_f.String(current.ncName), _f.String(current.nsUri)));
            }
            return qilList;
        }
        return null;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Dictionary, System.Xml.Xsl.Xslt.CompilerScopeManager< V >.GetEnumerator(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.Qil.QilPatternFactory.NamespaceDecl(), System.Xml.Xsl.Qil.QilFactory.Sequence(), and System.Xml.Xsl.Qil.QilPatternFactory.String().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.EnterScope().