Terraria: System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction
ResolveFunction()
QilNode IXPathEnvironment. System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction (string prefix, string name, IList< QilNode > args, IFocus env) inline private
Implements System.Xml.Xsl.XPath.IXPathEnvironment.
Definition at line 2256 of file QilGenerator.cs.
    {
        if (prefix.Length == 0)
        {
            if (FunctionTable.TryGetValue(name, out var value))
            {
                value.CastArguments(args, name, _f);
                switch (value.id)
                {
                case FuncId.Current:
                    if (!_allowCurrent)
                    {
                        throw new XslLoadException(System.SR.Xslt_CurrentNotAllowed);
                    }
                    return ((IFocus)this).GetCurrent();
                case FuncId.Key:
                    if (!_allowKey)
                    {
                        throw new XslLoadException(System.SR.Xslt_KeyNotAllowed);
                    }
                    return CompileFnKey(args[0], args[1], env);
                case FuncId.Document:
                    return CompileFnDocument(args[0], (args.Count > 1) ? args[1] : null);
                case FuncId.FormatNumber:
                    return CompileFormatNumber(args[0], args[1], (args.Count > 2) ? args[2] : null);
                case FuncId.UnparsedEntityUri:
                    return CompileUnparsedEntityUri(args[0]);
                case FuncId.GenerateId:
                    return CompileGenerateId((args.Count > 0) ? args[0] : env.GetCurrent());
                case FuncId.SystemProperty:
                    return CompileSystemProperty(args[0]);
                case FuncId.ElementAvailable:
                    return CompileElementAvailable(args[0]);
                case FuncId.FunctionAvailable:
                    return CompileFunctionAvailable(args[0]);
                default:
                    return null;
                }
            }
            throw new XslLoadException(System.SR.Xslt_UnknownXsltFunction, Compiler.ConstructQName(prefix, name));
        }
        string text = ResolvePrefixThrow(ignoreDefaultNs: true, prefix);
        if (text == "urn:schemas-microsoft-com:xslt")
        {
            switch (name)
            {
            case "node-set":
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(1, 1, name, args.Count);
                return CompileMsNodeSet(args[0]);
            case "string-compare":
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(2, 4, name, args.Count);
                return _f.InvokeMsStringCompare(_f.ConvertToString(args[0]), _f.ConvertToString(args[1]), (2 < args.Count) ? _f.ConvertToString(args[2]) : _f.String(string.Empty), (3 < args.Count) ? _f.ConvertToString(args[3]) : _f.String(string.Empty));
            case "utc":
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(1, 1, name, args.Count);
                return _f.InvokeMsUtc(_f.ConvertToString(args[0]));
            case "format-date":
            case "format-time":
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(1, 3, name, args.Count);
                return _f.InvokeMsFormatDateTime(_f.ConvertToString(args[0]), (1 < args.Count) ? _f.ConvertToString(args[1]) : _f.String(string.Empty), (2 < args.Count) ? _f.ConvertToString(args[2]) : _f.String(string.Empty), _f.Boolean(name == "format-date"));
            case "local-name":
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(1, 1, name, args.Count);
                return _f.InvokeMsLocalName(_f.ConvertToString(args[0]));
            case "namespace-uri":
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(1, 1, name, args.Count);
                return _f.InvokeMsNamespaceUri(_f.ConvertToString(args[0]), env.GetCurrent());
            case "number":
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(1, 1, name, args.Count);
                return _f.InvokeMsNumber(args[0]);
            }
        }
        if (text == "http://exslt.org/common")
        {
            if (name == "node-set")
            {
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(1, 1, name, args.Count);
                return CompileMsNodeSet(args[0]);
            }
            if (name == "object-type")
            {
                XPathBuilder.FunctionInfo<FuncId>.CheckArity(1, 1, name, args.Count);
                return EXslObjectType(args[0]);
            }
        }
        for (int i = 0; i < args.Count; i++)
        {
            args[i] = _f.SafeDocOrderDistinct(args[i]);
        }
        if (_compiler.Settings.EnableScript)
        {
            XmlExtensionFunction xmlExtensionFunction = _compiler.Scripts.ResolveFunction(name, text, args.Count, this);
            if (xmlExtensionFunction != null)
            {
                return GenerateScriptCall(_f.QName(name, text, prefix), xmlExtensionFunction, args);
            }
        }
        else if (_compiler.Scripts.ScriptClasses.ContainsKey(text))
        {
            ReportWarning(System.SR.Xslt_ScriptsProhibited);
            return _f.Error(_lastScope.SourceLine, System.SR.Xslt_ScriptsProhibited);
        }
        return _f.XsltInvokeLateBound(_f.QName(name, text, prefix), args);
    }
References System.Xml.Xsl.Xslt.QilGenerator._allowCurrent, System.Xml.Xsl.Xslt.QilGenerator._allowKey, System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Qil.QilPatternFactory.Boolean(), System.Xml.Xsl.XPath.XPathBuilder.FunctionInfo< T >.CheckArity(), System.Xml.Xsl.Xslt.QilGenerator.CompileElementAvailable(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), System.Xml.Xsl.Xslt.QilGenerator.CompileFnKey(), System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileFunctionAvailable(), System.Xml.Xsl.Xslt.QilGenerator.CompileGenerateId(), System.Xml.Xsl.Xslt.QilGenerator.CompileMsNodeSet(), System.Xml.Xsl.Xslt.QilGenerator.CompileSystemProperty(), System.Xml.Xsl.Xslt.QilGenerator.CompileUnparsedEntityUri(), System.Xml.Xsl.Xslt.Compiler.ConstructQName(), System.Xml.Xsl.Xslt.Scripts.TrimSafeDictionary.ContainsKey(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.XsltSettings.EnableScript, System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Xslt.QilGenerator.EXslObjectType(), System.Xml.Xsl.Xslt.QilGenerator.FunctionTable, System.Xml.Xsl.Xslt.QilGenerator.GenerateScriptCall(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsFormatDateTime(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsLocalName(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsNamespaceUri(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsNumber(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsStringCompare(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeMsUtc(), System.prefix, System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Xslt.QilGenerator.ReportWarning(), System.Xml.Xsl.Xslt.Scripts.ResolveFunction(), System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefixThrow(), System.Xml.Xsl.XPath.XPathQilFactory.SafeDocOrderDistinct(), System.Xml.Xsl.Xslt.Scripts.ScriptClasses, System.Xml.Xsl.Xslt.Compiler.Scripts, System.Xml.Xsl.Xslt.Compiler.Settings, System.Xml.Xsl.Xslt.XslNode.SourceLine, System.Xml.Xsl.Qil.QilPatternFactory.String(), System.text, System.value, System.SR.Xslt_CurrentNotAllowed, System.SR.Xslt_KeyNotAllowed, System.SR.Xslt_ScriptsProhibited, System.SR.Xslt_UnknownXsltFunction, and System.Xml.Xsl.Qil.QilPatternFactory.XsltInvokeLateBound().