Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileElement
CompileElement()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileElement (NodeCtor node) inline private
Definition at line 777 of file QilGenerator.cs.
    {
        QilNode qilNode = CompileStringAvt(node.NsAvt);
        QilNode qilNode2 = CompileStringAvt(node.NameAvt);
        QilNode name;
        if (qilNode2.NodeType != QilNodeType.LiteralString || (qilNode != null && qilNode.NodeType != QilNodeType.LiteralString))
        {
            name = ((qilNode == null) ? ResolveQNameDynamic(ignoreDefaultNs: false, qilNode2) : _f.StrParseQName(qilNode2, qilNode));
        }
        else
        {
            string qname = (QilLiteral)qilNode2;
            string prefix;
            string localName;
            bool flag = _compiler.ParseQName(qname, out prefix, out localName, this);
            string uri = ((qilNode != null) ? ((string)(QilLiteral)qilNode) : (flag ? ResolvePrefix(ignoreDefaultNs: false, prefix) : _compiler.CreatePhantomNamespace()));
            name = _f.QName(localName, uri, prefix);
        }
        _outputScope.PushScope();
        _outputScope.InvalidateAllPrefixes();
        QilNode content = CompileInstructions(node.Content);
        _outputScope.PopScope();
        return _f.ElementCtor(name, content);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._outputScope, System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.Xslt.Compiler.CreatePhantomNamespace(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.ElementCtor(), System.Xml.Xsl.Xslt.OutputScopeManager.InvalidateAllPrefixes(), System.Xml.Xsl.Xslt.Compiler.ParseQName(), System.Xml.Xsl.Xslt.OutputScopeManager.PopScope(), System.prefix, System.Xml.Xsl.Xslt.OutputScopeManager.PushScope(), System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefix(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic(), and System.Xml.Xsl.Qil.QilPatternFactory.StrParseQName().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().