Terraria: System.Xml.Xsl.Xslt.QilGenerator.CreateGlobalVarPar
CreateGlobalVarPar()
void System.Xml.Xsl.Xslt.QilGenerator.CreateGlobalVarPar (VarPar varPar) inline private
Definition at line 1728 of file QilGenerator.cs.
    {
        XmlQueryType t = ChooseBestType(varPar);
        QilIterator qilIterator = ((varPar.NodeType != XslNodeType.Variable) ? _f.Parameter(null, varPar.Name, t) : _f.Let(_f.Unknown(t)));
        qilIterator.DebugName = varPar.Name.ToString();
        varPar.Value = qilIterator;
        SetLineInfo(qilIterator, varPar.SourceLine);
        _scope.AddVariable(varPar.Name, qilIterator);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddVariable(), System.Xml.Xsl.Xslt.QilGenerator.ChooseBestType(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Parameter(), System.Xml.Xsl.Xslt.QilGenerator.SetLineInfo(), and System.Xml.Xsl.Qil.QilPatternFactory.Unknown().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CreateGlobalVarPars().