Terraria: System.Xml.Xsl.Xslt.QilGenerator.GenerateScriptCall
GenerateScriptCall()
QilNode System.Xml.Xsl.Xslt.QilGenerator.GenerateScriptCall (QilName name, XmlExtensionFunction scrFunc, IList< QilNode > args) inline private
Definition at line 2359 of file QilGenerator.cs.
    {
        for (int i = 0; i < args.Count; i++)
        {
            XmlQueryType xmlArgumentType = scrFunc.GetXmlArgumentType(i);
            switch (xmlArgumentType.TypeCode)
            {
            case XmlTypeCode.Boolean:
                args[i] = _f.ConvertToBoolean(args[i]);
                break;
            case XmlTypeCode.Double:
                args[i] = _f.ConvertToNumber(args[i]);
                break;
            case XmlTypeCode.String:
                args[i] = _f.ConvertToString(args[i]);
                break;
            case XmlTypeCode.Node:
                args[i] = (xmlArgumentType.IsSingleton ? _f.ConvertToNode(args[i]) : _f.ConvertToNodeSet(args[i]));
                break;
            }
        }
        return _f.XsltInvokeEarlyBound(name, scrFunc.Method, scrFunc.XmlReturnType, args);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNode(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNodeSet(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, and System.Xml.Xsl.Qil.QilPatternFactory.XsltInvokeEarlyBound().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().