Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileUseAttributeSet
CompileUseAttributeSet()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileUseAttributeSet (XslNode node) inline private
Definition at line 1094 of file QilGenerator.cs.
    {
        _outputScope.InvalidateAllPrefixes();
        if (_compiler.AttributeSets.TryGetValue(node.Name, out var value))
        {
            return _invkGen.GenerateInvoke(value.Function, AddRemoveImplicitArgs(node.Content, value.Flags));
        }
        if (!_compiler.IsPhantomName(node.Name))
        {
            _compiler.ReportError(node.SourceLine, System.SR.Xslt_NoAttributeSet, node.Name.QualifiedName);
        }
        return _f.Sequence();
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._invkGen, System.Xml.Xsl.Xslt.QilGenerator._outputScope, System.Xml.Xsl.Xslt.QilGenerator.AddRemoveImplicitArgs(), System.Xml.Xsl.Xslt.Compiler.AttributeSets, System.Xml.Xsl.Xslt.InvokeGenerator.GenerateInvoke(), System.Xml.Xsl.Xslt.OutputScopeManager.InvalidateAllPrefixes(), System.Xml.Xsl.Xslt.Compiler.IsPhantomName(), System.Xml.Xsl.Xslt.Compiler.ReportError(), System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, and System.SR.Xslt_NoAttributeSet.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().