Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileKeys
CompileKeys()
void System.Xml.Xsl.Xslt.QilGenerator.CompileKeys () inline private
Definition at line 1691 of file QilGenerator.cs.
    {
        for (int i = 0; i < _compiler.Keys.Count; i++)
        {
            foreach (Key item in _compiler.Keys[i])
            {
                EnterScope(item);
                QilParameter qilParameter = _f.Parameter(XmlQueryTypeFactory.NodeNotRtf);
                _singlFocus.SetFocus(qilParameter);
                QilIterator qilIterator = _f.For(_f.OptimizeBarrier(CompileKeyMatch(item.Match)));
                _singlFocus.SetFocus(qilIterator);
                QilIterator qilIterator2 = _f.For(CompileKeyUse(item));
                qilIterator2 = _f.For(_f.OptimizeBarrier(_f.Loop(qilIterator2, _f.ConvertToString(qilIterator2))));
                QilParameter qilParameter2 = _f.Parameter(XmlQueryTypeFactory.StringX);
                QilFunction qilFunction = _f.Function(_f.FormalParameterList(qilParameter, qilParameter2), _f.Filter(qilIterator, _f.Not(_f.IsEmpty(_f.Filter(qilIterator2, _f.Eq(qilIterator2, qilParameter2))))), _f.False());
                qilFunction.DebugName = item.GetDebugName();
                SetLineInfo(qilFunction, item.SourceLine);
                item.Function = qilFunction;
                _functions.Add(qilFunction);
                ExitScope();
            }
        }
        _singlFocus.SetFocus(null);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._functions, System.Xml.Xsl.Xslt.QilGenerator._singlFocus, System.Xml.Xsl.Qil.QilNode.Add(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeyMatch(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeyUse(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.EnterScope(), System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.Xslt.QilGenerator.ExitScope(), System.Xml.Xsl.Qil.QilPatternFactory.False(), System.Xml.Xsl.Qil.QilPatternFactory.Filter(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.FormalParameterList(), System.Xml.Xsl.Qil.QilPatternFactory.Function(), System.Xml.Xsl.Qil.QilPatternFactory.IsEmpty(), System.item, System.Xml.Xsl.Xslt.Compiler.Keys, System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.XmlQueryTypeFactory.NodeNotRtf, System.Xml.Xsl.Qil.QilPatternFactory.Not(), System.Xml.Xsl.Qil.QilPatternFactory.OptimizeBarrier(), System.Xml.Xsl.Qil.QilPatternFactory.Parameter(), System.Xml.Xsl.Xslt.SingletonFocus.SetFocus(), System.Xml.Xsl.Xslt.QilGenerator.SetLineInfo(), and System.Xml.Xsl.XmlQueryTypeFactory.StringX.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.Compile().