Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileGenerateId
CompileGenerateId()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileGenerateId (QilNode n) inline private
Definition at line 2649 of file QilGenerator.cs.
    {
        if (n.XmlType.IsSingleton)
        {
            return _f.XsltGenerateId(n);
        }
        QilIterator expr;
        return _f.StrConcat(_f.Loop(expr = _f.FirstNode(n), _f.XsltGenerateId(expr)));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.XPath.XPathQilFactory.FirstNode(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.StrConcat(), and System.Xml.Xsl.Qil.QilPatternFactory.XsltGenerateId().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().