Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate
CompileCallTemplate()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate (XslNodeEx node) inline private
Definition at line 1053 of file QilGenerator.cs.
    {
        int varScope = _varHelper.StartVariables();
        IList<XslNode> content = node.Content;
        foreach (VarPar item in content)
        {
            CompileWithParam(item);
            if (IsDebug)
            {
                QilNode value = item.Value;
                QilIterator qilIterator = _f.Let(value);
                qilIterator.DebugName = _f.QName("with-param " + item.Name.QualifiedName, "urn:schemas-microsoft-com:xslt-debug").ToString();
                _varHelper.AddVariable(qilIterator);
                item.Value = qilIterator;
            }
        }
        QilNode qilNode;
        if (_compiler.NamedTemplates.TryGetValue(node.Name, out var value2))
        {
            qilNode = _invkGen.GenerateInvoke(value2.Function, AddRemoveImplicitArgs(node.Content, value2.Flags));
        }
        else
        {
            if (!_compiler.IsPhantomName(node.Name))
            {
                _compiler.ReportError(node.SourceLine, System.SR.Xslt_InvalidCallTemplate, node.Name.QualifiedName);
            }
            qilNode = _f.Sequence();
        }
        if (content.Count > 0)
        {
            qilNode = SetLineInfo(qilNode, node.ElemNameLi);
        }
        qilNode = _varHelper.FinishVariables(qilNode, varScope);
        if (IsDebug)
        {
            return _f.Nop(qilNode);
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._invkGen, System.Xml.Xsl.Xslt.QilGenerator._varHelper, System.Xml.Xsl.Xslt.QilGenerator.AddRemoveImplicitArgs(), System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.AddVariable(), System.Xml.Xsl.Xslt.QilGenerator.CompileWithParam(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.FinishVariables(), System.Xml.Xsl.Xslt.InvokeGenerator.GenerateInvoke(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.Xslt.Compiler.IsPhantomName(), System.item, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Xslt.Compiler.NamedTemplates, System.Xml.Xsl.Qil.QilPatternFactory.Nop(), System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Xslt.Compiler.ReportError(), System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), System.Xml.Xsl.Xslt.QilGenerator.SetLineInfo(), System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.StartVariables(), System.Xml.Xsl.Qil.QilName.ToString(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, and System.SR.Xslt_InvalidCallTemplate.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().