Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVarPar
CompileGlobalVarPar()
QilIterator System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVarPar (VarPar varPar) inline private
Definition at line 1752 of file QilGenerator.cs.
    {
        QilIterator qilIterator = (QilIterator)varPar.Value;
        QilList nsList = EnterScope(varPar);
        QilNode qilNode = CompileVarParValue(varPar);
        SetLineInfo(qilNode, qilIterator.SourceLine);
        qilNode = AddCurrentPositionLast(qilNode);
        qilNode = SetDebugNs(qilNode, nsList);
        qilIterator.SourceLine = SourceLineInfo.NoSource;
        qilIterator.Binding = qilNode;
        ExitScope();
        return qilIterator;
    }
References System.Xml.Xsl.Xslt.QilGenerator.AddCurrentPositionLast(), System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.EnterScope(), System.Xml.Xsl.Xslt.QilGenerator.ExitScope(), System.Xml.Xsl.SourceLineInfo.NoSource, System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs(), and System.Xml.Xsl.Xslt.QilGenerator.SetLineInfo().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVariables().