Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileNodeSetExpression
CompileNodeSetExpression()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileNodeSetExpression (string expr) inline private
Definition at line 1813 of file QilGenerator.cs.
    {
        QilNode qilNode = _f.TryEnsureNodeSet(CompileXPathExpression(expr));
        if (qilNode == null)
        {
            XPathCompileException ex = new XPathCompileException(expr, 0, expr.Length, System.SR.XPath_NodeSetExpected, (string[])null);
            if (_xslVersion != XslVersion.ForwardsCompatible)
            {
                ReportErrorInXPath(ex);
            }
            qilNode = _f.Error(_f.String(ex.Message));
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._xslVersion, System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Xslt.QilGenerator.ReportErrorInXPath(), System.Xml.Xsl.Qil.QilPatternFactory.String(), System.Xml.Xsl.XPath.XPathQilFactory.TryEnsureNodeSet(), and System.SR.XPath_NodeSetExpected.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), and System.Xml.Xsl.Xslt.QilGenerator.CompileForEach().