Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileWithParam
CompileWithParam()
void System.Xml.Xsl.Xslt.QilGenerator.CompileWithParam (VarPar withParam) inline private
Definition at line 1263 of file QilGenerator.cs.
    {
        QilList nsList = EnterScope(withParam);
        QilNode n = CompileVarParValue(withParam);
        ExitScope();
        SetLineInfo(n, withParam.SourceLine);
        n = SetDebugNs(n, nsList);
        withParam.Value = n;
    }
References System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.EnterScope(), System.Xml.Xsl.Xslt.QilGenerator.ExitScope(), System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs(), and System.Xml.Xsl.Xslt.QilGenerator.SetLineInfo().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), and System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate().