Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSizeAttribute
CompileGroupingSizeAttribute()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileGroupingSizeAttribute (string attValue, bool fwdCompat) inline private
Definition at line 1616 of file QilGenerator.cs.
    {
        QilNode qilNode = CompileStringAvt(attValue);
        if (qilNode == null)
        {
            return _f.Double(0.0);
        }
        if (qilNode.NodeType == QilNodeType.LiteralString)
        {
            string s = (QilLiteral)qilNode;
            double num = XsltFunctions.Round(XPathConvert.StringToDouble(s));
            if (0.0 <= num && num <= 2147483647.0)
            {
                return _f.Double(num);
            }
            return _f.Double(0.0);
        }
        QilIterator qilIterator = _f.Let(_f.ConvertToNumber(qilNode));
        return _f.Loop(qilIterator, _f.Conditional(_f.And(_f.Lt(_f.Double(0.0), qilIterator), _f.Lt(qilIterator, _f.Double(2147483647.0))), qilIterator, _f.Double(0.0)));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Qil.QilPatternFactory.And(), System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Xsl.Qil.QilPatternFactory.Double(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Qil.QilPatternFactory.Lt(), System.Xml.Xsl.Runtime.XsltFunctions.Round(), System.s, and System.Xml.Xsl.XPathConvert.StringToDouble().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileNumber().