Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions
CompileInstructions() [3/4]
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions (IList< XslNode > instructions, int from, QilList content) inline private
Definition at line 628 of file QilGenerator.cs.
    {
        for (int i = from; i < instructions.Count; i++)
        {
            XslNode xslNode = instructions[i];
            XslNodeType nodeType = xslNode.NodeType;
            if (nodeType == XslNodeType.Param)
            {
                continue;
            }
            QilList nsList = EnterScope(xslNode);
            QilNode qilNode = nodeType switch
            {
                XslNodeType.ApplyImports => CompileApplyImports(xslNode),
                XslNodeType.ApplyTemplates => CompileApplyTemplates((XslNodeEx)xslNode),
                XslNodeType.Attribute => CompileAttribute((NodeCtor)xslNode),
                XslNodeType.CallTemplate => CompileCallTemplate((XslNodeEx)xslNode),
                XslNodeType.Choose => CompileChoose(xslNode),
                XslNodeType.Comment => CompileComment(xslNode),
                XslNodeType.Copy => CompileCopy(xslNode),
                XslNodeType.CopyOf => CompileCopyOf(xslNode),
                XslNodeType.Element => CompileElement((NodeCtor)xslNode),
                XslNodeType.Error => CompileError(xslNode),
                XslNodeType.ForEach => CompileForEach((XslNodeEx)xslNode),
                XslNodeType.If => CompileIf(xslNode),
                XslNodeType.List => CompileList(xslNode),
                XslNodeType.LiteralAttribute => CompileLiteralAttribute(xslNode),
                XslNodeType.LiteralElement => CompileLiteralElement(xslNode),
                XslNodeType.Message => CompileMessage(xslNode),
                XslNodeType.Nop => CompileNop(xslNode),
                XslNodeType.Number => CompileNumber((Number)xslNode),
                XslNodeType.PI => CompilePI(xslNode),
                XslNodeType.Text => CompileText((Text)xslNode),
                XslNodeType.UseAttributeSet => CompileUseAttributeSet(xslNode),
                XslNodeType.ValueOf => CompileValueOf(xslNode),
                XslNodeType.ValueOfDoe => CompileValueOfDoe(xslNode),
                XslNodeType.Variable => CompileVariable(xslNode),
                _ => null,
            };
            ExitScope();
            if (qilNode.NodeType != QilNodeType.Sequence || qilNode.Count != 0)
            {
                if (nodeType != XslNodeType.LiteralAttribute && nodeType != XslNodeType.UseAttributeSet)
                {
                    SetLineInfoCheck(qilNode, xslNode.SourceLine);
                }
                qilNode = SetDebugNs(qilNode, nsList);
                if (nodeType == XslNodeType.Variable)
                {
                    QilIterator qilIterator = _f.Let(qilNode);
                    qilIterator.DebugName = xslNode.Name.ToString();
                    _scope.AddVariable(xslNode.Name, qilIterator);
                    qilNode = _f.Loop(qilIterator, CompileInstructions(instructions, i + 1));
                    i = instructions.Count;
                }
                content.Add(qilNode);
            }
        }
        if (!IsDebug && content.Count == 1)
        {
            return content[0];
        }
        return content;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Qil.QilNode.Add(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.AddVariable(), System.Xml.Xsl.Xslt.QilGenerator.CompileApplyImports(), System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), System.Xml.Xsl.Xslt.QilGenerator.CompileAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileChoose(), System.Xml.Xsl.Xslt.QilGenerator.CompileComment(), System.Xml.Xsl.Xslt.QilGenerator.CompileCopy(), System.Xml.Xsl.Xslt.QilGenerator.CompileCopyOf(), System.Xml.Xsl.Xslt.QilGenerator.CompileElement(), System.Xml.Xsl.Xslt.QilGenerator.CompileError(), System.Xml.Xsl.Xslt.QilGenerator.CompileForEach(), System.Xml.Xsl.Xslt.QilGenerator.CompileIf(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileList(), System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralElement(), System.Xml.Xsl.Xslt.QilGenerator.CompileMessage(), System.Xml.Xsl.Xslt.QilGenerator.CompileNop(), System.Xml.Xsl.Xslt.QilGenerator.CompileNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompilePI(), System.Xml.Xsl.Xslt.QilGenerator.CompileText(), System.Xml.Xsl.Xslt.QilGenerator.CompileUseAttributeSet(), System.Xml.Xsl.Xslt.QilGenerator.CompileValueOf(), System.Xml.Xsl.Xslt.QilGenerator.CompileValueOfDoe(), System.Xml.Xsl.Xslt.QilGenerator.CompileVariable(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Qil.QilList.Count, System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.EnterScope(), System.Xml.Xsl.Xslt.QilGenerator.ExitScope(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs(), and System.Xml.Xsl.Xslt.QilGenerator.SetLineInfoCheck().