Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileCopy
CompileCopy()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileCopy (XslNode copy) inline private
Definition at line 1108 of file QilGenerator.cs.
    {
        QilNode currentNode = GetCurrentNode();
        if ((currentNode.XmlType.NodeKinds & (XmlNodeKindFlags.Attribute | XmlNodeKindFlags.Namespace)) != 0)
        {
            _outputScope.InvalidateAllPrefixes();
        }
        if (currentNode.XmlType.NodeKinds == XmlNodeKindFlags.Element)
        {
            QilList qilList = InstructionList();
            qilList.Add(_f.XPathNamespace(currentNode));
            _outputScope.PushScope();
            _outputScope.InvalidateAllPrefixes();
            QilNode content = CompileInstructions(copy.Content, qilList);
            _outputScope.PopScope();
            return _f.ElementCtor(_f.NameOf(currentNode), content);
        }
        if (currentNode.XmlType.NodeKinds == XmlNodeKindFlags.Document)
        {
            return CompileInstructions(copy.Content);
        }
        if ((currentNode.XmlType.NodeKinds & (XmlNodeKindFlags.Document | XmlNodeKindFlags.Element)) == 0)
        {
            return currentNode;
        }
        return _f.XsltCopy(currentNode, CompileInstructions(copy.Content));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._outputScope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Qil.QilPatternFactory.ElementCtor(), System.Xml.Xsl.Xslt.QilGenerator.GetCurrentNode(), System.Xml.Xsl.Xslt.QilGenerator.InstructionList(), System.Xml.Xsl.Xslt.OutputScopeManager.InvalidateAllPrefixes(), System.Xml.Xsl.Qil.QilPatternFactory.NameOf(), System.Xml.Xsl.Xslt.OutputScopeManager.PopScope(), System.Xml.Xsl.Xslt.OutputScopeManager.PushScope(), System.Xml.Xsl.Qil.QilNode.XmlType, System.Xml.Xsl.Qil.QilPatternFactory.XPathNamespace(), and System.Xml.Xsl.Qil.QilPatternFactory.XsltCopy().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().