Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute
CompileDataTypeAttribute()
void System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute (string attValue, bool fwdCompat, ref QilNode select, out QilNode select2) inline private
Definition at line 1337 of file QilGenerator.cs.
    {
        QilNode qilNode = CompileStringAvt(attValue);
        if (qilNode != null)
        {
            if (qilNode.NodeType != QilNodeType.LiteralString)
            {
                QilIterator qilIterator;
                QilIterator qilIterator2;
                qilNode = _f.Loop(qilIterator = _f.Let(qilNode), _f.Conditional(_f.Eq(qilIterator, _f.String("number")), _f.False(), _f.Conditional(_f.Eq(qilIterator, _f.String("text")), _f.True(), fwdCompat ? _f.True() : _f.Loop(qilIterator2 = _f.Let(ResolveQNameDynamic(ignoreDefaultNs: true, qilIterator)), _f.Error(_lastScope.SourceLine, System.SR.Xslt_BistateAttribute, "data-type", "text", "number")))));
                QilIterator qilIterator3 = _f.Let(qilNode);
                _varHelper.AddVariable(qilIterator3);
                select2 = select.DeepClone(_f.BaseFactory);
                select = _f.Conditional(qilIterator3, _f.ConvertToString(select), _f.String(string.Empty));
                select2 = _f.Conditional(qilIterator3, _f.Double(0.0), _f.ConvertToNumber(select2));
                return;
            }
            string text = (QilLiteral)qilNode;
            if (text == "number")
            {
                select = _f.ConvertToNumber(select);
                select2 = null;
                return;
            }
            if (!(text == "text") && !fwdCompat)
            {
                string prefix;
                string localName;
                string text2 = (_compiler.ParseQName(text, out prefix, out localName, this) ? ResolvePrefix(ignoreDefaultNs: true, prefix) : _compiler.CreatePhantomNamespace());
                _ = text2.Length;
                ReportError(System.SR.Xslt_BistateAttribute, "data-type", "text", "number");
            }
        }
        select = _f.ConvertToString(select);
        select2 = null;
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Xslt.QilGenerator._varHelper, System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.AddVariable(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToNumber(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Xml.Xsl.Xslt.Compiler.CreatePhantomNamespace(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.Double(), System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.XPath.XPathQilFactory.Error(), System.Xml.Xsl.Qil.QilPatternFactory.False(), System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Xslt.Compiler.ParseQName(), System.prefix, System.Xml.Xsl.Xslt.QilGenerator.ReportError(), System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefix(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic(), System.Xml.Xsl.Xslt.XslNode.SourceLine, System.Xml.Xsl.Qil.QilPatternFactory.String(), System.text, System.Xml.Xsl.Qil.QilPatternFactory.True(), and System.SR.Xslt_BistateAttribute.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileSort().