Terraria: System.Xml.Xsl.Xslt.QilGenerator.AddCurrentPositionLast
AddCurrentPositionLast()
QilNode System.Xml.Xsl.Xslt.QilGenerator.AddCurrentPositionLast (QilNode content) inline private
Definition at line 2192 of file QilGenerator.cs.
    {
        if (IsDebug)
        {
            content = AddDebugVariable(CloneName(_nameLast), GetLastPosition(), content);
            content = AddDebugVariable(CloneName(_namePosition), GetCurrentPosition(), content);
            content = AddDebugVariable(CloneName(_nameCurrent), GetCurrentNode(), content);
        }
        return content;
    }
References System.Xml.Xsl.Xslt.QilGenerator._nameCurrent, System.Xml.Xsl.Xslt.QilGenerator._nameLast, System.Xml.Xsl.Xslt.QilGenerator._namePosition, System.Xml.Xsl.Xslt.QilGenerator.AddDebugVariable(), System.Xml.Xsl.Xslt.QilGenerator.CloneName(), System.Xml.Xsl.Xslt.QilGenerator.GetCurrentNode(), System.Xml.Xsl.Xslt.QilGenerator.GetCurrentPosition(), System.Xml.Xsl.Xslt.QilGenerator.GetLastPosition(), and System.Xml.Xsl.Xslt.QilGenerator.IsDebug.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates(), System.Xml.Xsl.Xslt.QilGenerator.CompileForEach(), and System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVarPar().