Terraria: System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction
InvokeApplyFunction()
QilNode System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction (StylesheetLevel sheet, QilName mode, IList< XslNode > actualArgs) inline private
Definition at line 2061 of file QilGenerator.cs.
    {
        if (!sheet.ModeFlags.TryGetValue(mode, out var value))
        {
            value = XslFlags.None;
        }
        value |= XslFlags.Current;
        actualArgs = AddRemoveImplicitArgs(actualArgs, value);
        QilList qilList = _f.ActualParameterList();
        QilFunction qilFunction = null;
        if (!sheet.ApplyFunctions.TryGetValue(mode, out var value2))
        {
            List<QilFunction> list2 = (sheet.ApplyFunctions[mode] = new List<QilFunction>());
            value2 = list2;
        }
        foreach (QilFunction item in value2)
        {
            if (FillupInvokeArgs(item.Arguments, actualArgs, qilList))
            {
                qilFunction = item;
                break;
            }
        }
        if (qilFunction == null)
        {
            qilList.Clear();
            QilList qilList2 = _f.FormalParameterList();
            for (int i = 0; i < actualArgs.Count; i++)
            {
                VarPar varPar = (VarPar)actualArgs[i];
                qilList.Add(varPar.Value);
                QilParameter qilParameter = _f.Parameter((i == 0) ? XmlQueryTypeFactory.NodeNotRtf : varPar.Value.XmlType);
                qilParameter.Name = CloneName(varPar.Name);
                qilList2.Add(qilParameter);
                varPar.Value = qilParameter;
            }
            qilFunction = _f.Function(qilList2, _f.Boolean((value & XslFlags.SideEffects) != 0), XmlQueryTypeFactory.NodeNotRtfS);
            string text = ((mode.LocalName.Length == 0) ? string.Empty : (" mode=\"" + mode.QualifiedName + "\""));
            qilFunction.DebugName = ((sheet is RootLevel) ? "<xsl:apply-templates" : "<xsl:apply-imports") + text + ">";
            value2.Add(qilFunction);
            _functions.Add(qilFunction);
            QilIterator qilIterator = (QilIterator)qilList2[0];
            QilIterator qilIterator2 = _f.For(_f.Content(qilIterator));
            QilNode qilNode = _f.Filter(qilIterator2, _f.IsType(qilIterator2, XmlQueryTypeFactory.Content));
            qilNode.XmlType = XmlQueryTypeFactory.ContentS;
            LoopFocus curLoop = _curLoop;
            _curLoop.SetFocus(_f.For(qilNode));
            QilNode qilNode2 = InvokeApplyFunction(_compiler.Root, mode, null);
            if (IsDebug)
            {
                qilNode2 = _f.Sequence(InvokeOnCurrentNodeChanged(), qilNode2);
            }
            QilLoop center = _curLoop.ConstructLoop(qilNode2);
            _curLoop = curLoop;
            QilTernary otherwise = _f.BaseFactory.Conditional(_f.IsType(qilIterator, _elementOrDocumentType), center, _f.Conditional(_f.IsType(qilIterator, _textOrAttributeType), _f.TextCtor(_f.XPathNodeValue(qilIterator)), _f.Sequence()));
            _matcherBuilder.CollectPatterns(sheet, mode);
            qilFunction.Definition = _matcherBuilder.BuildMatcher(qilIterator, actualArgs, otherwise);
        }
        return _f.Invoke(qilFunction, qilList);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._curLoop, System.Xml.Xsl.Xslt.QilGenerator._elementOrDocumentType, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._functions, System.Xml.Xsl.Xslt.QilGenerator._matcherBuilder, System.Xml.Xsl.Xslt.QilGenerator._textOrAttributeType, System.Xml.Xsl.Qil.QilPatternFactory.ActualParameterList(), System.Xml.Xsl.Qil.QilNode.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.QilGenerator.AddRemoveImplicitArgs(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.Qil.QilPatternFactory.Boolean(), System.Xml.Xsl.Xslt.MatcherBuilder.BuildMatcher(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.Xsl.Xslt.QilGenerator.CloneName(), System.Xml.Xsl.Xslt.MatcherBuilder.CollectPatterns(), System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), System.Xml.Xsl.Qil.QilFactory.Conditional(), System.Xml.Xsl.Xslt.LoopFocus.ConstructLoop(), System.Xml.Xsl.Qil.QilPatternFactory.Content(), System.Xml.Xsl.XmlQueryTypeFactory.Content, System.Xml.Xsl.XmlQueryTypeFactory.ContentS, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.FillupInvokeArgs(), System.Xml.Xsl.Qil.QilPatternFactory.Filter(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Qil.QilPatternFactory.FormalParameterList(), System.Xml.Xsl.Qil.QilPatternFactory.Function(), System.Xml.Xsl.Qil.QilPatternFactory.Invoke(), System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction(), System.Xml.Xsl.Xslt.QilGenerator.InvokeOnCurrentNodeChanged(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.Qil.QilPatternFactory.IsType(), System.item, System.Xml.Xsl.XmlQueryTypeFactory.NodeNotRtfS, System.Xml.Xsl.Qil.QilPatternFactory.Parameter(), System.Xml.Xsl.Xslt.Compiler.Root, System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), System.Xml.Xsl.Xslt.LoopFocus.SetFocus(), System.text, System.Xml.Xsl.Qil.QilPatternFactory.TextCtor(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, and System.Xml.Xsl.Qil.QilPatternFactory.XPathNodeValue().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.GenerateApply(), and System.Xml.Xsl.Xslt.QilGenerator.InvokeApplyFunction().