Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates
CompileApplyTemplates()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileApplyTemplates (XslNodeEx node) inline private
Definition at line 1015 of file QilGenerator.cs.
    {
        IList<XslNode> content = node.Content;
        int varScope = _varHelper.StartVariables();
        QilIterator qilIterator = _f.Let(CompileNodeSetExpression(node.Select));
        _varHelper.AddVariable(qilIterator);
        for (int i = 0; i < content.Count; i++)
        {
            if (content[i] is VarPar varPar)
            {
                CompileWithParam(varPar);
                QilNode value = varPar.Value;
                if (IsDebug || (!(value is QilIterator) && !(value is QilLiteral)))
                {
                    QilIterator qilIterator2 = _f.Let(value);
                    qilIterator2.DebugName = _f.QName("with-param " + varPar.Name.QualifiedName, "urn:schemas-microsoft-com:xslt-debug").ToString();
                    _varHelper.AddVariable(qilIterator2);
                    varPar.Value = qilIterator2;
                }
            }
        }
        LoopFocus parentLoop = _curLoop;
        QilIterator focus = _f.For(qilIterator);
        _curLoop.SetFocus(focus);
        _curLoop.Sort(CompileSorts(content, ref parentLoop));
        QilNode expr = GenerateApply(_compiler.Root, node);
        expr = WrapLoopBody(node.ElemNameLi, expr, node.EndTagLi);
        expr = AddCurrentPositionLast(expr);
        expr = _curLoop.ConstructLoop(expr);
        _curLoop = parentLoop;
        return _varHelper.FinishVariables(expr, varScope);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._curLoop, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._varHelper, System.Xml.Xsl.Xslt.QilGenerator.AddCurrentPositionLast(), System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.AddVariable(), System.Xml.Xsl.Xslt.QilGenerator.CompileNodeSetExpression(), System.Xml.Xsl.Xslt.QilGenerator.CompileSorts(), System.Xml.Xsl.Xslt.QilGenerator.CompileWithParam(), System.Xml.Xsl.Xslt.LoopFocus.ConstructLoop(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.FinishVariables(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Xslt.QilGenerator.GenerateApply(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Xslt.Compiler.Root, System.Xml.Xsl.Xslt.LoopFocus.SetFocus(), System.Xml.Xsl.Xslt.LoopFocus.Sort(), System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.StartVariables(), System.Xml.Xsl.Qil.QilName.ToString(), System.value, and System.Xml.Xsl.Xslt.QilGenerator.WrapLoopBody().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().