Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileRootExpression
CompileRootExpression()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileRootExpression (XslNode applyTmpls) inline private
Definition at line 323 of file QilGenerator.cs.
    {
        _singlFocus.SetFocus(SingletonFocusType.InitialContextNode);
        QilNode child = GenerateApply(_compiler.Root, applyTmpls);
        _singlFocus.SetFocus(null);
        return _f.DocumentCtor(child);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._singlFocus, System.Xml.Xsl.Qil.QilPatternFactory.DocumentCtor(), System.Xml.Xsl.Xslt.QilGenerator.GenerateApply(), System.Xml.Xsl.Xslt.Compiler.Root, and System.Xml.Xsl.Xslt.SingletonFocus.SetFocus().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.Compile().