Terraria: System.Xml.Xsl.Xslt.QilGenerator.MatchCountPattern
MatchCountPattern()
QilNode System.Xml.Xsl.Xslt.QilGenerator.MatchCountPattern (QilNode countPattern, QilIterator testNode) inline private
Definition at line 1486 of file QilGenerator.cs.
    {
        if (countPattern != null)
        {
            return MatchPattern(countPattern, testNode);
        }
        QilNode currentNode = GetCurrentNode();
        XmlNodeKindFlags nodeKinds = currentNode.XmlType.NodeKinds;
        if ((nodeKinds & (nodeKinds - 1)) != 0)
        {
            return _f.InvokeIsSameNodeSort(testNode, currentNode);
        }
        QilNode left;
        switch (nodeKinds)
        {
        case XmlNodeKindFlags.Document:
            return _f.IsType(testNode, XmlQueryTypeFactory.Document);
        case XmlNodeKindFlags.Element:
            left = _f.IsType(testNode, XmlQueryTypeFactory.Element);
            break;
        case XmlNodeKindFlags.Attribute:
            left = _f.IsType(testNode, XmlQueryTypeFactory.Attribute);
            break;
        case XmlNodeKindFlags.Text:
            return _f.IsType(testNode, XmlQueryTypeFactory.Text);
        case XmlNodeKindFlags.Comment:
            return _f.IsType(testNode, XmlQueryTypeFactory.Comment);
        case XmlNodeKindFlags.PI:
            return _f.And(_f.IsType(testNode, XmlQueryTypeFactory.PI), _f.Eq(_f.LocalNameOf(testNode), _f.LocalNameOf(currentNode)));
        case XmlNodeKindFlags.Namespace:
            return _f.And(_f.IsType(testNode, XmlQueryTypeFactory.Namespace), _f.Eq(_f.LocalNameOf(testNode), _f.LocalNameOf(currentNode)));
        default:
            return _f.False();
        }
        return _f.And(left, _f.And(_f.Eq(_f.LocalNameOf(testNode), _f.LocalNameOf(currentNode)), _f.Eq(_f.NamespaceUriOf(testNode), _f.NamespaceUriOf(GetCurrentNode()))));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Qil.QilPatternFactory.And(), System.Xml.Xsl.XmlQueryTypeFactory.Attribute, System.Xml.Xsl.XmlQueryTypeFactory.Comment, System.Xml.Xsl.XmlQueryTypeFactory.Document, System.Xml.Xsl.XmlQueryTypeFactory.Element, System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.Qil.QilPatternFactory.False(), System.Xml.Xsl.Xslt.QilGenerator.GetCurrentNode(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeIsSameNodeSort(), System.Xml.Xsl.Qil.QilPatternFactory.IsType(), System.Xml.Xsl.Qil.QilPatternFactory.LocalNameOf(), System.Xml.Xsl.Xslt.QilGenerator.MatchPattern(), System.Xml.Xsl.XmlQueryTypeFactory.Namespace, System.Xml.Xsl.Qil.QilPatternFactory.NamespaceUriOf(), System.Xml.Xsl.XmlQueryTypeFactory.PI, System.Xml.Xsl.XmlQueryTypeFactory.Text, and System.Xml.Xsl.Qil.QilNode.XmlType.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker(), and System.Xml.Xsl.Xslt.QilGenerator.PlaceMarkerAny().