Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileLangToLcid
CompileLangToLcid()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileLangToLcid (QilNode lang, bool fwdCompat) inline private
Definition at line 1324 of file QilGenerator.cs.
    {
        if (lang == null)
        {
            return _f.Double(127.0);
        }
        if (lang.NodeType == QilNodeType.LiteralString)
        {
            return _f.String(XsltLibrary.LangToNameInternal((QilLiteral)lang, fwdCompat, this));
        }
        return _f.XsltConvert(_f.InvokeLangToLcid(lang, fwdCompat), XmlQueryTypeFactory.DoubleX);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Qil.QilPatternFactory.Double(), System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.Xslt.XsltQilFactory.InvokeLangToLcid(), System.Xml.Xsl.Runtime.XsltLibrary.LangToNameInternal(), System.Xml.Xsl.Qil.QilNode.NodeType, System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Xml.Xsl.Qil.QilPatternFactory.XsltConvert().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileLangAttributeToLcid().