Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileVariable
CompileVariable()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileVariable (XslNode node) inline private
Definition at line 1224 of file QilGenerator.cs.
    {
        if (_scope.IsLocalVariable(node.Name.LocalName, node.Name.NamespaceUri))
        {
            ReportError(System.SR.Xslt_DupLocalVariable, node.Name.QualifiedName);
        }
        return CompileVarParValue(node);
    }
References System.Xml.Xsl.Xslt.QilGenerator._scope, System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue(), System.Xml.Xsl.Xslt.CompilerScopeManager< V >.IsLocalVariable(), System.Xml.Xsl.Xslt.QilGenerator.ReportError(), and System.SR.Xslt_DupLocalVariable.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().