Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralAttribute
CompileLiteralAttribute()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileLiteralAttribute (XslNode node) inline private
Definition at line 802 of file QilGenerator.cs.
    {
        QilName name = node.Name;
        string prefix = name.Prefix;
        string nsUri = name.NamespaceUri;
        if (prefix.Length != 0)
        {
            _compiler.ApplyNsAliases(ref prefix, ref nsUri);
        }
        name.Prefix = prefix;
        name.NamespaceUri = nsUri;
        return _f.AttributeCtor(name, CompileTextAvt(node.Select));
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.Compiler.ApplyNsAliases(), System.Xml.Xsl.Qil.QilPatternFactory.AttributeCtor(), System.Xml.Xsl.Xslt.QilGenerator.CompileTextAvt(), System.Xml.Dictionary, and System.prefix.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().