Terraria: System.Xml.Xsl.Xslt.QilGenerator.SetLineInfo
SetLineInfo()
static QilNode System.Xml.Xsl.Xslt.QilGenerator.SetLineInfo (QilNode n, ISourceLineInfo lineInfo) inline static private
Definition at line 2162 of file QilGenerator.cs.
    {
        if (lineInfo != null && 0 < lineInfo.Start.Line && lineInfo.Start.LessOrEqual(lineInfo.End))
        {
            n.SourceLine = lineInfo;
        }
        return n;
    }
References System.Xml.Dictionary, System.Xml.Xsl.ISourceLineInfo.End, System.Xml.Xsl.Location.LessOrEqual(), System.Xml.Xsl.Location.Line, and System.Xml.Xsl.ISourceLineInfo.Start.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVarPar(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeys(), System.Xml.Xsl.Xslt.QilGenerator.CompileWithParam(), System.Xml.Xsl.Xslt.QilGenerator.CreateGlobalVarPar(), System.Xml.Xsl.Xslt.QilGenerator.PrecompileProtoTemplatesHeaders(), System.Xml.Xsl.Xslt.QilGenerator.SetLineInfoCheck(), and System.Xml.Xsl.Xslt.QilGenerator.WrapLoopBody().