Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue
CompileVarParValue()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileVarParValue (XslNode node) inline private
Definition at line 1233 of file QilGenerator.cs.
    {
        string uri = _lastScope.SourceLine.Uri;
        IList<XslNode> content = node.Content;
        string select = node.Select;
        QilNode qilNode;
        if (select != null)
        {
            QilList qilList = InstructionList();
            qilList.Add(CompileXPathExpression(select));
            qilNode = CompileInstructions(content, qilList);
        }
        else if (content.Count != 0)
        {
            _outputScope.PushScope();
            _outputScope.InvalidateAllPrefixes();
            qilNode = _f.RtfCtor(CompileInstructions(content), _f.String(uri));
            _outputScope.PopScope();
        }
        else
        {
            qilNode = _f.String(string.Empty);
        }
        if (IsDebug)
        {
            qilNode = _f.TypeAssert(qilNode, XmlQueryTypeFactory.ItemS);
        }
        return qilNode;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Xslt.QilGenerator._outputScope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.InstructionList(), System.Xml.Xsl.Xslt.OutputScopeManager.InvalidateAllPrefixes(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.XmlQueryTypeFactory.ItemS, System.Xml.Xsl.Xslt.OutputScopeManager.PopScope(), System.Xml.Xsl.Xslt.OutputScopeManager.PushScope(), System.Xml.Xsl.Qil.QilPatternFactory.RtfCtor(), System.Xml.Xsl.Xslt.XslNode.SourceLine, System.Xml.Xsl.Qil.QilPatternFactory.String(), System.Xml.Xsl.Qil.QilPatternFactory.TypeAssert(), and System.Xml.Xsl.ISourceLineInfo.Uri.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVarPar(), System.Xml.Xsl.Xslt.QilGenerator.CompileProtoTemplate(), System.Xml.Xsl.Xslt.QilGenerator.CompileVariable(), System.Xml.Xsl.Xslt.QilGenerator.CompileWithParam(), and System.Xml.Xsl.Xslt.QilGenerator.PrecompileProtoTemplatesHeaders().