Terraria: System.Xml.Xsl.Xslt.QilGenerator.ReportWarning
ReportWarning()
void System.Xml.Xsl.Xslt.QilGenerator.ReportWarning (string res, params string[] args) inline
Definition at line 2127 of file QilGenerator.cs.
    {
        _compiler.ReportWarning(_lastScope.SourceLine, res, args);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Xslt.Compiler.ReportWarning(), and System.Xml.Xsl.Xslt.XslNode.SourceLine.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().