Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileWhen
CompileWhen()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileWhen (XslNode whenNode, QilNode otherwise) inline private
Definition at line 1175 of file QilGenerator.cs.
    {
        return _f.Conditional(_f.ConvertToBoolean(CompileXPathExpression(whenNode.Select)), CompileInstructions(whenNode.Content), otherwise);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), System.Xml.Xsl.Qil.QilPatternFactory.Conditional(), and System.Xml.Xsl.XPath.XPathQilFactory.ConvertToBoolean().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileChoose(), and System.Xml.Xsl.Xslt.QilGenerator.CompileIf().