Terraria: System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameThrow
ResolveQNameThrow()
XmlQualifiedName System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameThrow (bool ignoreDefaultNs, QilNode qilName) inline private
Definition at line 2659 of file QilGenerator.cs.
    {
        string qname = (QilLiteral)qilName;
        _compiler.ParseQName(qname, out var prefix, out var localName, default(ThrowErrorHelper));
        string ns = ResolvePrefixThrow(ignoreDefaultNs, prefix);
        return new XmlQualifiedName(localName, ns);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.Compiler.ParseQName(), System.prefix, and System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefixThrow().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileElementAvailable(), System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileFunctionAvailable(), and System.Xml.Xsl.Xslt.QilGenerator.CompileSystemProperty().