Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileAvt
CompileAvt()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileAvt (string source) inline private
Definition at line 899 of file QilGenerator.cs.
    {
        QilList qilList = _f.BaseFactory.Sequence();
        int pos = 0;
        while (pos < source.Length)
        {
            QilNode qilNode = ExtractText(source, ref pos);
            if (qilNode != null)
            {
                qilList.Add(qilNode);
            }
            if (pos < source.Length)
            {
                pos++;
                QilNode n = CompileXPathExpressionWithinAvt(source, ref pos);
                qilList.Add(_f.ConvertToString(n));
            }
        }
        if (qilList.Count == 1)
        {
            return qilList[0];
        }
        return qilList;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpressionWithinAvt(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.ExtractText(), System.Xml.Xsl.Qil.QilFactory.Sequence(), and System.source.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), and System.Xml.Xsl.Xslt.QilGenerator.CompileTextAvt().