Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileChoose
CompileChoose()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileChoose (XslNode node) inline private
Definition at line 1185 of file QilGenerator.cs.
    {
        IList<XslNode> content = node.Content;
        QilNode qilNode = null;
        int num = content.Count - 1;
        while (0 <= num)
        {
            XslNode xslNode = content[num];
            QilList nsList = EnterScope(xslNode);
            qilNode = ((xslNode.NodeType != XslNodeType.Otherwise) ? CompileWhen(xslNode, qilNode ?? InstructionList()) : CompileInstructions(xslNode.Content));
            ExitScope();
            SetLineInfoCheck(qilNode, xslNode.SourceLine);
            qilNode = SetDebugNs(qilNode, nsList);
            num--;
        }
        if (qilNode == null)
        {
            return _f.Sequence();
        }
        if (!IsDebug)
        {
            return qilNode;
        }
        return _f.Sequence(qilNode);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileWhen(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.EnterScope(), System.Xml.Xsl.Xslt.QilGenerator.ExitScope(), System.Xml.Xsl.Xslt.QilGenerator.InstructionList(), System.Xml.Xsl.Xslt.QilGenerator.IsDebug, System.Xml.Xsl.Qil.QilPatternFactory.Sequence(), System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs(), and System.Xml.Xsl.Xslt.QilGenerator.SetLineInfoCheck().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().