Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileAttribute
CompileAttribute()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileAttribute (NodeCtor node) inline private
Definition at line 816 of file QilGenerator.cs.
    {
        QilNode qilNode = CompileStringAvt(node.NsAvt);
        QilNode qilNode2 = CompileStringAvt(node.NameAvt);
        bool flag = false;
        QilNode name;
        if (qilNode2.NodeType != QilNodeType.LiteralString || (qilNode != null && qilNode.NodeType != QilNodeType.LiteralString))
        {
            name = ((qilNode == null) ? ResolveQNameDynamic(ignoreDefaultNs: true, qilNode2) : _f.StrParseQName(qilNode2, qilNode));
        }
        else
        {
            string text = (QilLiteral)qilNode2;
            string prefix;
            string localName;
            bool flag2 = _compiler.ParseQName(text, out prefix, out localName, this);
            string text2;
            if (qilNode == null)
            {
                text2 = (flag2 ? ResolvePrefix(ignoreDefaultNs: true, prefix) : _compiler.CreatePhantomNamespace());
            }
            else
            {
                text2 = (QilLiteral)qilNode;
                flag = true;
            }
            if (text == "xmlns" || (localName == "xmlns" && text2.Length == 0))
            {
                ReportError(System.SR.Xslt_XmlnsAttr, "name", text);
            }
            name = _f.QName(localName, text2, prefix);
        }
        if (flag)
        {
            _outputScope.InvalidateNonDefaultPrefixes();
        }
        return _f.AttributeCtor(name, CompileInstructions(node.Content));
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._outputScope, System.Xml.Xsl.Qil.QilPatternFactory.AttributeCtor(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileStringAvt(), System.Xml.Xsl.Xslt.Compiler.CreatePhantomNamespace(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.OutputScopeManager.InvalidateNonDefaultPrefixes(), System.Xml.Xsl.Xslt.Compiler.ParseQName(), System.prefix, System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Xml.Xsl.Xslt.QilGenerator.ReportError(), System.Xml.Xsl.Xslt.QilGenerator.ResolvePrefix(), System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic(), System.Xml.Xsl.Qil.QilPatternFactory.StrParseQName(), System.text, and System.SR.Xslt_XmlnsAttr.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().