Terraria: System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker
PlaceMarker()
QilNode System.Xml.Xsl.Xslt.QilGenerator.PlaceMarker (QilNode countPattern, QilNode fromPattern, bool multiple) inline private
Definition at line 1523 of file QilGenerator.cs.
    {
        QilNode countPattern2 = countPattern?.DeepClone(_f.BaseFactory);
        QilIterator testNode;
        QilNode qilNode = _f.Filter(testNode = _f.For(_f.AncestorOrSelf(GetCurrentNode())), MatchCountPattern(countPattern, testNode));
        QilNode qilNode2 = ((!multiple) ? _f.Filter(testNode = _f.For(qilNode), _f.Eq(_f.PositionOf(testNode), _f.Int32(1))) : _f.DocOrderDistinct(qilNode));
        QilNode binding;
        QilIterator right;
        if (fromPattern == null)
        {
            binding = qilNode2;
        }
        else
        {
            QilNode binding2 = _f.Filter(testNode = _f.For(_f.AncestorOrSelf(GetCurrentNode())), MatchPattern(fromPattern, testNode));
            QilNode binding3 = _f.Filter(testNode = _f.For(binding2), _f.Eq(_f.PositionOf(testNode), _f.Int32(1)));
            binding = _f.Loop(testNode = _f.For(binding3), _f.Filter(right = _f.For(qilNode2), _f.Before(testNode, right)));
        }
        return _f.Loop(right = _f.For(binding), _f.Add(_f.Int32(1), _f.Length(_f.Filter(testNode = _f.For(_f.PrecedingSibling(right)), MatchCountPattern(countPattern2, testNode)))));
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Qil.QilPatternFactory.Add(), System.Xml.Xsl.Qil.QilPatternFactory.AncestorOrSelf(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.Qil.QilPatternFactory.Before(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilPatternFactory.DocOrderDistinct(), System.Xml.Xsl.Qil.QilPatternFactory.Eq(), System.Xml.Xsl.Qil.QilPatternFactory.Filter(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Xslt.QilGenerator.GetCurrentNode(), System.Xml.Xsl.Qil.QilPatternFactory.Int32(), System.Xml.Xsl.Qil.QilPatternFactory.Length(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Xslt.QilGenerator.MatchCountPattern(), System.Xml.Xsl.Xslt.QilGenerator.MatchPattern(), System.Xml.Xsl.Qil.QilPatternFactory.PositionOf(), and System.Xml.Xsl.Qil.QilPatternFactory.PrecedingSibling().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileNumber().