Terraria: System.Xml.Xsl.Xslt.QilGenerator.GetNsVar
GetNsVar()
QilIterator System.Xml.Xsl.Xslt.QilGenerator.GetNsVar (QilList nsList) inline private
Definition at line 424 of file QilGenerator.cs.
    {
        foreach (QilIterator nsVar in _nsVars)
        {
            QilList qilList = (QilList)nsVar.Binding;
            if (qilList.Count != nsList.Count)
            {
                continue;
            }
            bool flag = true;
            for (int i = 0; i < nsList.Count; i++)
            {
                if (((QilLiteral)((QilBinary)nsList[i]).Right).Value != ((QilLiteral)((QilBinary)qilList[i]).Right).Value || ((QilLiteral)((QilBinary)nsList[i]).Left).Value != ((QilLiteral)((QilBinary)qilList[i]).Left).Value)
                {
                    flag = false;
                    break;
                }
            }
            if (flag)
            {
                return nsVar;
            }
        }
        QilIterator qilIterator2 = _f.Let(nsList);
        qilIterator2.DebugName = _f.QName("ns" + _nsVars.Count, "urn:schemas-microsoft-com:xslt-debug").ToString();
        _gloVars.Add(qilIterator2);
        _nsVars.Add(qilIterator2);
        return qilIterator2;
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._gloVars, System.Xml.Xsl.Xslt.QilGenerator._nsVars, System.Xml.Xsl.Qil.QilNode.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Qil.QilList.Count, System.Xml.Dictionary, System.Collections.Generic.Left, System.Xml.Xsl.Qil.QilPatternFactory.Let(), System.Xml.Xsl.Qil.QilPatternFactory.QName(), System.Collections.Generic.Right, and System.Xml.Xsl.Qil.QilName.ToString().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.PrecompileProtoTemplatesHeaders(), and System.Xml.Xsl.Xslt.QilGenerator.SetDebugNs().