Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileForEach
CompileForEach()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileForEach (XslNodeEx node) inline private
Definition at line 998 of file QilGenerator.cs.
    {
        IList<XslNode> content = node.Content;
        LoopFocus parentLoop = _curLoop;
        QilIterator focus = _f.For(CompileNodeSetExpression(node.Select));
        _curLoop.SetFocus(focus);
        int varScope = _varHelper.StartVariables();
        _curLoop.Sort(CompileSorts(content, ref parentLoop));
        QilNode expr = CompileInstructions(content);
        expr = WrapLoopBody(node.ElemNameLi, expr, node.EndTagLi);
        expr = AddCurrentPositionLast(expr);
        expr = _curLoop.ConstructLoop(expr);
        expr = _varHelper.FinishVariables(expr, varScope);
        _curLoop = parentLoop;
        return expr;
    }
References System.Xml.Xsl.Xslt.QilGenerator._curLoop, System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._varHelper, System.Xml.Xsl.Xslt.QilGenerator.AddCurrentPositionLast(), System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions(), System.Xml.Xsl.Xslt.QilGenerator.CompileNodeSetExpression(), System.Xml.Xsl.Xslt.QilGenerator.CompileSorts(), System.Xml.Xsl.Xslt.LoopFocus.ConstructLoop(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.FinishVariables(), System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.Xslt.LoopFocus.SetFocus(), System.Xml.Xsl.Xslt.LoopFocus.Sort(), System.Xml.Xsl.Xslt.QilGenerator.VariableHelper.StartVariables(), and System.Xml.Xsl.Xslt.QilGenerator.WrapLoopBody().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileInstructions().