Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileSingleDocument
CompileSingleDocument()
QilNode System.Xml.Xsl.Xslt.QilGenerator.CompileSingleDocument (QilNode uri, QilNode baseNode) inline private
Definition at line 2593 of file QilGenerator.cs.
    {
        QilIterator n;
        QilNode baseUri = ((baseNode == null) ? _f.String(_lastScope.SourceLine.Uri) : ((!baseNode.XmlType.IsSingleton) ? _f.StrConcat(_f.Loop(n = _f.FirstNode(baseNode), _f.InvokeBaseUri(n))) : _f.InvokeBaseUri(baseNode)));
        return _f.DataSource(uri, baseUri);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._lastScope, System.Xml.Xsl.Qil.QilPatternFactory.DataSource(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathQilFactory.FirstNode(), System.Xml.Xsl.Xslt.XsltQilFactory.InvokeBaseUri(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Xml.Xsl.Xslt.XslNode.SourceLine, System.Xml.Xsl.Qil.QilPatternFactory.StrConcat(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Xml.Xsl.ISourceLineInfo.Uri.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileFnDocument().