Terraria: System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic
ResolveQNameDynamic()
QilNode System.Xml.Xsl.Xslt.QilGenerator.ResolveQNameDynamic (bool ignoreDefaultNs, QilNode qilName) inline private
Definition at line 1951 of file QilGenerator.cs.
    {
        QilList qilList = _f.BaseFactory.Sequence();
        if (ignoreDefaultNs)
        {
            qilList.Add(_f.NamespaceDecl(_f.String(string.Empty), _f.String(string.Empty)));
        }
        CompilerScopeManager<QilIterator>.NamespaceEnumerator enumerator = _scope.GetEnumerator();
        while (enumerator.MoveNext())
        {
            CompilerScopeManager<QilIterator>.ScopeRecord current = enumerator.Current;
            string ncName = current.ncName;
            string nsUri = current.nsUri;
            if (!ignoreDefaultNs || ncName.Length != 0)
            {
                qilList.Add(_f.NamespaceDecl(_f.String(ncName), _f.String(nsUri)));
            }
        }
        return _f.StrParseQName(qilName, qilList);
    }
References System.Xml.Xsl.Xslt.QilGenerator._f, System.Xml.Xsl.Xslt.QilGenerator._scope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Xsl.Xslt.CompilerScopeManager< V >.GetEnumerator(), System.Xml.Xsl.Qil.QilPatternFactory.NamespaceDecl(), System.Xml.Xsl.Qil.QilFactory.Sequence(), System.Xml.Xsl.Qil.QilPatternFactory.String(), and System.Xml.Xsl.Qil.QilPatternFactory.StrParseQName().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.CompileAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileDataTypeAttribute(), System.Xml.Xsl.Xslt.QilGenerator.CompileElement(), System.Xml.Xsl.Xslt.QilGenerator.CompileElementAvailable(), System.Xml.Xsl.Xslt.QilGenerator.CompileFormatNumber(), System.Xml.Xsl.Xslt.QilGenerator.CompileFunctionAvailable(), System.Xml.Xsl.Xslt.QilGenerator.CompileSingleKey(), and System.Xml.Xsl.Xslt.QilGenerator.CompileSystemProperty().