Terraria: System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVariables
CompileGlobalVariables()
void System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVariables () inline private
Definition at line 1738 of file QilGenerator.cs.
    {
        _singlFocus.SetFocus(SingletonFocusType.InitialDocumentNode);
        foreach (VarPar externalPar in _compiler.ExternalPars)
        {
            _extPars.Add(CompileGlobalVarPar(externalPar));
        }
        foreach (VarPar globalVar in _compiler.GlobalVars)
        {
            _gloVars.Add(CompileGlobalVarPar(globalVar));
        }
        _singlFocus.SetFocus(null);
    }
References System.Xml.Xsl.Xslt.QilGenerator._compiler, System.Xml.Xsl.Xslt.QilGenerator._extPars, System.Xml.Xsl.Xslt.QilGenerator._gloVars, System.Xml.Xsl.Xslt.QilGenerator._singlFocus, System.Xml.Xsl.Qil.QilNode.Add(), System.Xml.Xsl.Xslt.QilGenerator.CompileGlobalVarPar(), System.Xml.Xsl.Xslt.Compiler.ExternalPars, System.Xml.Xsl.Xslt.Compiler.GlobalVars, and System.Xml.Xsl.Xslt.SingletonFocus.SetFocus().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.Compile().