Terraria: System.Reflection.Metadata.Ecma335.BlobEncoder.MethodSignature
MethodSignature()
MethodSignatureEncoder System.Reflection.Metadata.Ecma335.BlobEncoder.MethodSignature (SignatureCallingConvention convention = SignatureCallingConvention::Default, int genericParameterCount = 0, bool isInstanceMethod = false) inline
Definition at line 33 of file BlobEncoder.cs.
    {
        if ((uint)genericParameterCount > 65535u)
        {
            Throw.ArgumentOutOfRange("genericParameterCount");
        }
        SignatureAttributes attributes = ((genericParameterCount != 0) ? SignatureAttributes.Generic : SignatureAttributes.None) | (isInstanceMethod ? SignatureAttributes.Instance : SignatureAttributes.None);
        Builder.WriteByte(new SignatureHeader(SignatureKind.Method, convention, attributes).RawValue);
        if (genericParameterCount != 0)
        {
            Builder.WriteCompressedInteger(genericParameterCount);
        }
        return new MethodSignatureEncoder(Builder, convention == SignatureCallingConvention.VarArgs);
    }
References System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.Ecma335.BlobEncoder.Builder, System.Reflection.Metadata.SignatureHeader.RawValue, System.Reflection.Metadata.BlobBuilder.WriteByte(), and System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger().