Terraria: AchievementsHelper.NotifyNPCKilled
NotifyNPCKilled()
static void AchievementsHelper.NotifyNPCKilled (NPC npc) inline static
     {
         if (Main.netMode == 0)
         {
             if (npc.playerInteraction[Main.myPlayer])
             {
                 NotifyNPCKilledDirect(Main.player[Main.myPlayer], npc.netID);
             }
             return;
         }
         for (int i = 0; i < 255; i++)
         {
             if (npc.playerInteraction[i])
             {
                 NetMessage.SendData(97, i, -1, null, npc.netID);
             }
         }
     }
References Main.myPlayer, NPC.netID, Main.netMode, NotifyNPCKilledDirect(), Main.player, NPC.playerInteraction, and NetMessage.SendData().
Referenced by NPC.CountKillForAchievements().