Terraria: AchievementsHelper.HandleSpecialEvent
HandleSpecialEvent()
static void AchievementsHelper.HandleSpecialEvent (Player player, int eventID) inline static
     {
         if (player.whoAmI != Main.myPlayer)
         {
             return;
         }
         switch (eventID)
         {
         case 1:
             Main.Achievements.GetCondition("STAR_POWER", "Use").Complete();
             if (player.statLifeMax == 500 && player.statManaMax == 200)
             {
                 Main.Achievements.GetCondition("TOPPED_OFF", "Use").Complete();
             }
             break;
         case 2:
             Main.Achievements.GetCondition("GET_A_LIFE", "Use").Complete();
             if (player.statLifeMax == 500 && player.statManaMax == 200)
             {
                 Main.Achievements.GetCondition("TOPPED_OFF", "Use").Complete();
             }
             break;
         case 3:
             Main.Achievements.GetCondition("NOT_THE_BEES", "Use").Complete();
             break;
         case 4:
             Main.Achievements.GetCondition("WATCH_YOUR_STEP", "Hit").Complete();
             break;
         case 6:
             Main.Achievements.GetCondition("YOU_AND_WHAT_ARMY", "Spawn").Complete();
             break;
         case 5:
             Main.Achievements.GetCondition("RAINBOWS_AND_UNICORNS", "Use").Complete();
             break;
         case 7:
             Main.Achievements.GetCondition("THROWING_LINES", "Use").Complete();
             break;
         case 17:
             Main.Achievements.GetCondition("FLY_A_KITE_ON_A_WINDY_DAY", "Use").Complete();
             break;
         case 8:
             Main.Achievements.GetCondition("LUCKY_BREAK", "Hit").Complete();
             break;
         case 9:
             Main.Achievements.GetCondition("VEHICULAR_MANSLAUGHTER", "Hit").Complete();
             break;
         case 10:
             Main.Achievements.GetCondition("ROCK_BOTTOM", "Reach").Complete();
             break;
         case 11:
             Main.Achievements.GetCondition("INTO_ORBIT", "Reach").Complete();
             break;
         case 12:
             Main.Achievements.GetCondition("WHERES_MY_HONEY", "Reach").Complete();
             break;
         case 13:
             Main.Achievements.GetCondition("JEEPERS_CREEPERS", "Reach").Complete();
             break;
         case 14:
             Main.Achievements.GetCondition("ITS_GETTING_HOT_IN_HERE", "Reach").Complete();
             break;
         case 15:
             Main.Achievements.GetCondition("FUNKYTOWN", "Reach").Complete();
             break;
         case 16:
             Main.Achievements.GetCondition("I_AM_LOOT", "Peek").Complete();
             break;
         case 18:
             Main.Achievements.GetCondition("FOUND_GRAVEYARD", "Reach").Complete();
             break;
         case 19:
             Main.Achievements.GetCondition("GO_LAVA_FISHING", "Do").Complete();
             break;
         case 20:
             Main.Achievements.GetCondition("TALK_TO_NPC_AT_MAX_HAPPINESS", "Do").Complete();
             break;
         case 21:
             Main.Achievements.GetCondition("PET_THE_PET", "Do").Complete();
             break;
         case 22:
             Main.Achievements.GetCondition("FIND_A_FAIRY", "Do").Complete();
             break;
         case 23:
             Main.Achievements.GetCondition("DIE_TO_DEAD_MANS_CHEST", "Do").Complete();
             break;
         case 24:
             Main.Achievements.GetCondition("GAIN_TORCH_GODS_FAVOR", "Use").Complete();
             break;
         case 25:
             Main.Achievements.GetCondition("DRINK_BOTTLED_WATER_WHILE_DROWNING", "Use").Complete();
             break;
         case 26:
             Main.Achievements.GetCondition("PLAY_ON_A_SPECIAL_SEED", "Do").Complete();
             break;
         case 27:
             Main.Achievements.GetCondition("PURIFY_ENTIRE_WORLD", "Do").Complete();
             break;
         }
     }
References Main.Achievements, AchievementCondition.Complete(), AchievementManager.GetCondition(), Main.myPlayer, Player.statLifeMax, Player.statManaMax, and Entity.whoAmI.
Referenced by NPC.AI_112_FairyCritter(), Projectile.BombsHurtPlayers(), Player.BordersMovement(), Projectile.Damage(), Projectile.FishingCheck(), Player.FreeUpPetsAndMinions(), MessageBuffer.GetData(), Main.GUIChatDrawInner(), Player.ItemCheck(), Player.ItemCheck_Shoot(), Player.ItemCheck_UseLifeCrystal(), Player.ItemCheck_UseLifeFruit(), Player.ItemCheck_UseManaCrystal(), Player.ItemCheck_UseTorchGodsFavor(), Player.KillMe(), Player.PetAnimal(), Player.QuickHeal(), Player.SetTalkNPC(), Player.TileInteractionsUse(), Player.Update(), Player.UpdateArmorSets(), Player.UpdateBiomes(), and Mount.UpdateEffects().