Terraria: System.Exception.CanSetRemoteStackTrace
CanSetRemoteStackTrace()
bool System.Exception.CanSetRemoteStackTrace () inline private inherited
Definition at line 295 of file Exception.cs.
    {
        if (IsImmutableAgileException(this))
        {
            return false;
        }
        if (_stackTrace != null || _stackTraceString != null || _remoteStackTraceString != null)
        {
            ThrowHelper.ThrowInvalidOperationException();
        }
        return true;
    }
References System.Exception._remoteStackTraceString, System.Exception._stackTrace, System.Exception._stackTraceString, System.Exception.IsImmutableAgileException(), and System.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Exception.SetCurrentStackTrace(), and System.Exception.SetRemoteStackTrace().