Terraria: System.Exception.RestoreDispatchState
RestoreDispatchState()
void System.Exception.RestoreDispatchState (in DispatchState dispatchState) inline package inherited
Definition at line 264 of file Exception.cs.
    {
        if (!IsImmutableAgileException(this))
        {
            byte[] currentStackTrace = (byte[])dispatchState.StackTrace?.Clone();
            object[] dynamicMethodArray = (object[])dispatchState.DynamicMethods?.Clone();
            _watsonBuckets = dispatchState.WatsonBuckets;
            _ipForWatsonBuckets = dispatchState.IpForWatsonBuckets;
            _remoteStackTraceString = dispatchState.RemoteStackTrace;
            SaveStackTracesFromDeepCopy(this, currentStackTrace, dynamicMethodArray);
            _stackTraceString = null;
            PrepareForForeignExceptionRaise();
        }
    }
References System.Exception._ipForWatsonBuckets, System.Exception._remoteStackTraceString, System.Exception._stackTraceString, System.Exception._watsonBuckets, System.Runtime.Serialization.Dictionary, System.Exception.IsImmutableAgileException(), System.Exception.PrepareForForeignExceptionRaise(), and System.Exception.SaveStackTracesFromDeepCopy().
Referenced by System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().