Terraria: System.Exception.GetType
GetType()
new Type System.Exception.GetType () inline inherited
Definition at line 437 of file Exception.cs.
    {
        return base.GetType();
    }
References System.Runtime.Serialization.Dictionary, and System.Type.GetType().
Referenced by Internal.Runtime.InteropServices.LicenseInteropProxy.AllocateAndValidateLicense(), Terraria.Utilities.FileUtilities.Copy(), System.AggregateException.Flatten(), System.Exception.GetClassName(), System.ComponentModel.ReflectPropertyDescriptor.GetValue(), DataSetUtil.IsCatchableExceptionType(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.Common.ADP.IsCatchableOrSecurityExceptionType(), System.IO.FileLoadException.ToString(), System.IO.FileNotFoundException.ToString(), System.Runtime.InteropServices.COMException.ToString(), System.BadImageFormatException.ToString(), and System.Xml.Xsl.XslTransformException.ToString().