Terraria: System.Exception.InternalPreserveStackTrace
InternalPreserveStackTrace()
void System.Exception.InternalPreserveStackTrace () inline package inherited
Definition at line 240 of file Exception.cs.
    {
        _ = Source;
        string stackTrace = StackTrace;
        if (!string.IsNullOrEmpty(stackTrace))
        {
            _remoteStackTraceString = stackTrace + "\r\n";
        }
        _stackTrace = null;
        _stackTraceString = null;
    }
References System.Exception._remoteStackTraceString, System.Exception._stackTrace, System.Exception._stackTraceString, System.Runtime.Serialization.Dictionary, System.Exception.Source, and System.Exception.StackTrace.
Referenced by System.StubHelpers.StubHelpers.GetCOMHRExceptionObject(), System.StubHelpers.StubHelpers.GetHRExceptionObject(), and System.StubHelpers.StubHelpers.GetPendingExceptionObject().