Terraria: System.Exception.ToString
ToString()
override string System.Exception.ToString () inline inherited
Definition at line 384 of file Exception.cs.
    {
        string className = GetClassName();
        string message = Message;
        string text = _innerException?.ToString() ?? "";
        string exception_EndOfInnerExceptionStack = SR.Exception_EndOfInnerExceptionStack;
        string stackTrace = StackTrace;
        int num = className.Length;
        checked
        {
            if (!string.IsNullOrEmpty(message))
            {
                num += 2 + message.Length;
            }
            if (_innerException != null)
            {
                num += "\r\n".Length + " ---> ".Length + text.Length + "\r\n".Length + 3 + exception_EndOfInnerExceptionStack.Length;
            }
            if (stackTrace != null)
            {
                num += "\r\n".Length + stackTrace.Length;
            }
            string text2 = string.FastAllocateString(num);
            Span<char> dest2 = new Span<char>(ref text2.GetRawStringData(), text2.Length);
            Write(className, ref dest2);
            if (!string.IsNullOrEmpty(message))
            {
                Write(": ", ref dest2);
                Write(message, ref dest2);
            }
            if (_innerException != null)
            {
                Write("\r\n", ref dest2);
                Write(" ---> ", ref dest2);
                Write(text, ref dest2);
                Write("\r\n", ref dest2);
                Write("   ", ref dest2);
                Write(exception_EndOfInnerExceptionStack, ref dest2);
            }
            if (stackTrace != null)
            {
                Write("\r\n", ref dest2);
                Write(stackTrace, ref dest2);
            }
            return text2;
        }
        static void Write(string source, ref Span<char> dest)
        {
            source.CopyTo(dest);
            dest = dest.Slice(source.Length);
        }
    }
References System.Exception._innerException, System.Runtime.Serialization.Dictionary, System.SR.Exception_EndOfInnerExceptionStack, System.Exception.GetClassName(), System.Exception.Message, System.source, System.Exception.StackTrace, System.text, and System.Exception.ToString().
Referenced by System.Net.HttpRequestStream.BeginReadCore(), System.Net.HttpResponseStream.BeginWriteCore(), System.Transactions.TransactionState.ChangeStateTransactionAborted(), System.Reflection.ReflectionTypeLoadException.CreateString(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCompleted(), Terraria.Program.DisplayException(), System.Net.HttpResponseStream.DisposeCore(), Terraria.TimeLogger.DrawException(), ReLogic.Content.ContentRejectionAssetReaderException.GetReason(), System.Exception.GetStackTrace(), System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.LogError(), System.Diagnostics.Metrics.MetricsEventSource.CommandHandler.OnEventCommand(), Terraria.Utilities.CrashWatcher.PrintException(), System.Net.HttpRequestStream.ReadCore(), System.Transactions.TransactionManager.Reenlist(), System.Exception.SetCurrentStackTrace(), System.Runtime.InteropServices.ExternalException.ToString(), System.Exception.ToString(), and System.Net.HttpResponseStream.WriteCore().