Terraria: System.Exception.SetCurrentStackTrace
SetCurrentStackTrace()
void System.Exception.SetCurrentStackTrace () inline package inherited
Definition at line 458 of file Exception.cs.
    {
        if (CanSetRemoteStackTrace())
        {
            StringBuilder stringBuilder = new StringBuilder(256);
            new StackTrace(fNeedFileInfo: true).ToString(System.Diagnostics.StackTrace.TraceFormat.TrailingNewLine, stringBuilder);
            stringBuilder.AppendLine(SR.Exception_EndStackTraceFromPreviousThrow);
            _remoteStackTraceString = stringBuilder.ToString();
        }
    }
References System.Exception._remoteStackTraceString, System.Exception.CanSetRemoteStackTrace(), System.Runtime.Serialization.Dictionary, System.SR.Exception_EndStackTraceFromPreviousThrow, System.Exception.StackTrace, and System.Exception.ToString().
Referenced by System.Threading.TimerQueueTimer.CloseAsync(), and System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.CompleteCallback().