Terraria: Terraria.GameContent.ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents
PrepareARenderTarget_AndListenToEvents()
void Terraria.GameContent.ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents (ref RenderTarget2D target, GraphicsDevice device, int neededWidth, int neededHeight, RenderTargetUsage usage) inline protected inherited
Definition at line 38 of file ARenderTargetContentByRequest.cs.
    {
        if (target == null || target.IsDisposed || target.Width != neededWidth || target.Height != neededHeight)
        {
            if (target != null)
            {
                target.ContentLost -= target_ContentLost;
                target.Disposing -= target_Disposing;
            }
            target = new RenderTarget2D(device, neededWidth, neededHeight, mipMap: false, device.PresentationParameters.BackBufferFormat, DepthFormat.None, 0, usage);
            target.ContentLost += target_ContentLost;
            target.Disposing += target_Disposing;
        }
    }
References Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferFormat, Microsoft.Xna.Framework.Graphics.GraphicsDevice.PresentationParameters, Terraria.GameContent.ARenderTargetContentByRequest.target_ContentLost(), and Terraria.GameContent.ARenderTargetContentByRequest.target_Disposing().
Referenced by Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseReqest(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseReqest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseReqest(), and Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseReqest().