Terraria: System.Collections.Generic.LinkedList.ValidateNewNode
ValidateNewNode()
void System.Collections.Generic.LinkedList< T >.ValidateNewNode (LinkedListNode< T > node) inline package
Definition at line 498 of file LinkedList.cs.
    {
        if (node == null)
        {
            throw new ArgumentNullException("node");
        }
        if (node.list != null)
        {
            throw new InvalidOperationException(System.SR.LinkedListNodeIsAttached);
        }
    }
References System.SR.LinkedListNodeIsAttached.
Referenced by System.Collections.Generic.LinkedList< T >.AddAfter(), System.Collections.Generic.LinkedList< T >.AddBefore(), System.Collections.Generic.LinkedList< T >.AddFirst(), and System.Collections.Generic.LinkedList< T >.AddLast().