Terraria: System.Collections.Generic.LinkedList.OnDeserialization
OnDeserialization()
virtual void System.Collections.Generic.LinkedList< T >.OnDeserialization (object? sender) inline virtual
Implements System.Runtime.Serialization.IDeserializationCallback.
Definition at line 432 of file LinkedList.cs.
    {
        if (_siInfo == null)
        {
            return;
        }
        int @int = _siInfo.GetInt32("Version");
        if (_siInfo.GetInt32("Count") != 0)
        {
            T[] array = (T[])_siInfo.GetValue("Data", typeof(T[]));
            if (array == null)
            {
                throw new SerializationException(System.SR.Serialization_MissingValues);
            }
            for (int i = 0; i < array.Length; i++)
            {
                AddLast(array[i]);
            }
        }
        else
        {
            head = null;
        }
        version = @int;
        _siInfo = null;
    }
References System.Collections.Generic.LinkedList< T >._siInfo, System.Collections.Generic.LinkedList< T >.AddLast(), System.array, System.Runtime.Serialization.SerializationInfo.GetInt32(), System.Runtime.Serialization.SerializationInfo.GetValue(), System.Collections.Generic.LinkedList< T >.head, System.SR.Serialization_MissingValues, and System.Collections.Generic.LinkedList< T >.version.