Terraria: System.Collections.Generic.LinkedList.InternalInsertNodeToEmptyList
InternalInsertNodeToEmptyList()
void System.Collections.Generic.LinkedList< T >.InternalInsertNodeToEmptyList (LinkedListNode< T > newNode) inline private
Definition at line 469 of file LinkedList.cs.
    {
        newNode.next = newNode;
        newNode.prev = newNode;
        head = newNode;
        version++;
        count++;
    }
References System.Collections.Generic.LinkedList< T >.count, System.Runtime.Serialization.Dictionary, System.Collections.Generic.LinkedList< T >.head, and System.Collections.Generic.LinkedList< T >.version.
Referenced by System.Collections.Generic.LinkedList< T >.AddFirst(), System.Collections.Generic.LinkedList< T >.AddFirst(), System.Collections.Generic.LinkedList< T >.AddLast(), and System.Collections.Generic.LinkedList< T >.AddLast().