Terraria: System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.FormatItem
FormatItem()
string System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.FormatItem (object value) inline package
Definition at line 71 of file NumberAction.cs.
        {
            double num;
            if (value is int)
            {
                num = (int)value;
            }
            else
            {
                num = XmlConvert.ToXPathDouble(value);
                if (!(0.5 <= num) || double.IsPositiveInfinity(num))
                {
                    return XmlConvert.ToXPathString(value);
                }
                num = XmlConvert.XPathRound(num);
            }
            switch (_seq)
            {
            case NumberingSequence.FirstAlpha:
            case NumberingSequence.LCLetter:
                if (num <= 2147483647.0)
                {
                    StringBuilder stringBuilder2 = new StringBuilder();
                    NumberFormatterBase.ConvertToAlphabetic(stringBuilder2, num, (_seq == NumberingSequence.FirstAlpha) ? 'A' : 'a', 26);
                    return stringBuilder2.ToString();
                }
                break;
            case NumberingSequence.FirstSpecial:
            case NumberingSequence.LCRoman:
                if (num <= 32767.0)
                {
                    StringBuilder stringBuilder = new StringBuilder();
                    NumberFormatterBase.ConvertToRoman(stringBuilder, num, _seq == NumberingSequence.FirstSpecial);
                    return stringBuilder.ToString();
                }
                break;
            }
            return ConvertToArabic(num, _cMinLen, _sizeGroup, _separator);
        }
References System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat._cMinLen, System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat._separator, System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat._seq, System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat._sizeGroup, System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToAlphabetic(), System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.ConvertToArabic(), System.Xml.Xsl.Runtime.NumberFormatterBase.ConvertToRoman(), System.Xml.XmlConvert.ToXPathDouble(), System.Xml.XmlConvert.ToXPathString(), System.value, and System.Xml.XmlConvert.XPathRound().