Terraria: NetServerSocialModule.CloseAndUpdateUserState
CloseAndUpdateUserState()
void NetServerSocialModule.CloseAndUpdateUserState (RailID remote_peer) inline private
     {
         if (_connectionStateMap.ContainsKey(remote_peer))
         {
             WeGameHelper.WriteDebugString("CloseAndUpdateUserState, remote:{0}", ((RailComparableID)remote_peer).id_);
             TerminateRemotePlayerSession(remote_peer);
             CloseNetWorkSession(remote_peer);
             _connectionStateMap[remote_peer] = ConnectionState.Inactive;
             _reader.ClearUser(remote_peer);
             _writer.ClearUser(remote_peer);
         }
     }
References NetSocialModule._connectionStateMap, NetSocialModule._reader, NetSocialModule._writer, SteamP2PReader.ClearUser(), SteamP2PWriter.ClearUser(), CloseNetWorkSession(), TerminateRemotePlayerSession(), and WeGameHelper.WriteDebugString().
Referenced by Close(), OnCreateSessionFailed(), OnPacketRead(), and UpdateUserStateBySessionAuthResult().