Terraria: System.Diagnostics.Stopwatch.GetTimestamp
GetTimestamp()
static long System.Diagnostics.Stopwatch.GetTimestamp () inline static
Definition at line 77 of file Stopwatch.cs.
    {
        return QueryPerformanceCounter();
    }
References System.Diagnostics.Stopwatch.QueryPerformanceCounter().
Referenced by System.Threading.PortableThreadPool.AdjustMaxWorkersActive(), System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindowDynamic(), Microsoft.Extensions.Internal.ValueStopwatch.GetElapsedTime(), System.Diagnostics.Stopwatch.GetRawElapsedTicks(), ReLogic.Threading.ThreadUtilities.HighPrecisionSleep(), System.Net.Http.Http2Connection.RttEstimator.OnDataOrHeadersReceived(), System.Net.Http.Http2Connection.RttEstimator.OnInitialSettingsSent(), System.Threading.ProcessorIdCache.ProcessorNumberSpeedCheck(), System.Net.Http.Http2Connection.RttEstimator.RefreshRtt(), System.Diagnostics.Stopwatch.Restart(), System.Net.Http.DiagnosticsHandler.SendAsyncCore(), System.Net.Http.Http2Connection.Http2StreamWindowManager.Start(), System.Diagnostics.Stopwatch.Start(), Microsoft.Extensions.Internal.ValueStopwatch.StartNew(), and System.Diagnostics.Stopwatch.Stop().