Terraria: System.Diagnostics.Stopwatch.Start
Start()
void System.Diagnostics.Stopwatch.Start () inline
Definition at line 32 of file Stopwatch.cs.
    {
        if (!_isRunning)
        {
            _startTimeStamp = GetTimestamp();
            _isRunning = true;
        }
    }
References System.Diagnostics.Stopwatch._isRunning, System.Diagnostics.Stopwatch._startTimeStamp, and System.Diagnostics.Stopwatch.GetTimestamp().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gamesenseWrk(), Terraria.Main.DedServ(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.WorldSections.GetNextMapDraw(), Terraria.Map.MapHelper.InternalSaveMap(), Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.Graphics.Light.LightingEngine.ProcessArea(), ReLogic.Utilities.MultiTimer.Record(), ReLogic.Utilities.MultiTimer.Start(), System.Diagnostics.Stopwatch.StartNew(), Terraria.IO.PlayerFileData.StartPlayTimer(), Terraria.IO.PlayerFileData.UpdatePlayTimerAndKeepState(), and Terraria.IO.WorldFile.ValidateWorld().