Terraria: ItemDropWithConditionRule.ReportDroprates
ReportDroprates()
override void ItemDropWithConditionRule.ReportDroprates (List< DropRateInfo > drops, DropRateInfoChainFeed ratesInfo) inline virtual
Reimplemented from CommonDrop.
     {
         DropRateInfoChainFeed ratesInfo2 = ratesInfo.With(1f);
         ratesInfo2.AddCondition(condition);
         float num = (float)chanceNumerator / (float)chanceDenominator;
         float dropRate = num * ratesInfo2.parentDroprateChance;
         drops.Add(new DropRateInfo(itemId, amountDroppedMinimum, amountDroppedMaximum, dropRate, ratesInfo2.conditions));
         Chains.ReportDroprates(base.ChainedRules, num, drops, ratesInfo2);
     }
References DropRateInfoChainFeed.AddCondition(), CommonDrop.amountDroppedMaximum, CommonDrop.amountDroppedMinimum, CommonDrop.chanceDenominator, CommonDrop.chanceNumerator, condition, DropRateInfoChainFeed.conditions, CommonDrop.itemId, DropRateInfoChainFeed.parentDroprateChance, Chains.ReportDroprates(), and DropRateInfoChainFeed.With().