Terraria: System.Collections.Concurrent.Partitioner.Create
Create() [3/4]
static OrderablePartitioner< Tuple< long, long > > System.Collections.Concurrent.Partitioner< TSource >.Create (long fromInclusive, long toExclusive) inline static inherited
Definition at line 812 of file Partitioner.cs.
    {
        if (toExclusive <= fromInclusive)
        {
            throw new ArgumentOutOfRangeException("toExclusive");
        }
        decimal num = (decimal)toExclusive - (decimal)fromInclusive;
        long num2 = (long)(num / (decimal)(Environment.ProcessorCount * 3));
        if (num2 == 0L)
        {
            num2 = 1L;
        }
        return Create(CreateRanges(fromInclusive, toExclusive, num2), EnumerablePartitionerOptions.NoBuffering);
    }
References System.Collections.Concurrent.Partitioner< TSource >.Create(), System.Collections.Concurrent.Partitioner< TSource >.CreateRanges(), and System.L.
Referenced by System.Collections.Concurrent.Partitioner< TSource >.Create(), System.Collections.Concurrent.Partitioner< TSource >.Create(), System.Collections.Concurrent.Partitioner< TSource >.Create(), System.Collections.Concurrent.Partitioner< TSource >.Create(), System.Collections.Concurrent.Partitioner< TSource >.Create< TSource >(), and System.Threading.Tasks.Parallel.ForEachWorker< TSource, TLocal >().