Terraria: System.Collections.Concurrent.Partitioner.CreateRanges
CreateRanges() [2/2]
static IEnumerable< Tuple< long, long > > System.Collections.Concurrent.Partitioner< TSource >.CreateRanges (long fromInclusive, long toExclusive, long rangeSize) inline static private inherited
Definition at line 840 of file Partitioner.cs.
    {
        bool shouldQuit = false;
        for (long i = fromInclusive; i < toExclusive; i += rangeSize)
        {
            if (shouldQuit)
            {
                break;
            }
            long item = i;
            long num;
            try
            {
                num = checked(i + rangeSize);
            }
            catch (OverflowException)
            {
                num = toExclusive;
                shouldQuit = true;
            }
            if (num > toExclusive)
            {
                num = toExclusive;
            }
            yield return new Tuple<long, long>(item, num);
        }
    }
References System.item.
Referenced by System.Collections.Concurrent.Partitioner< TSource >.Create(), System.Collections.Concurrent.Partitioner< TSource >.Create(), System.Collections.Concurrent.Partitioner< TSource >.Create(), and System.Collections.Concurrent.Partitioner< TSource >.Create().