Terraria: KeyConfiguration.KeyStatus
KeyStatus
Dictionary<string, List<string> > KeyConfiguration.KeyStatus = new Dictionary<string, List<string>>()
Referenced by PlayerInput.ComposeInstructionsForGamepad(), CopyKeyState(), UILinksInitializer.FancyUISpecialInstructions(), ItemSlot.GetGamepadInstructions(), UILinksInitializer.Load(), PlayerInput.LockGamepadButtons(), Processkey(), ReadPreferences(), PlayerInput.Reset(), SetupKeys(), Lang.SupportGlyphs(), ItemSlot.TryEnteringBuildingMode(), ItemSlot.TryEnteringFastUseMode(), and WritePreferences().