Terraria: System.Xml.Xsl.Xslt.InvokeGenerator.GenerateInvoke
GenerateInvoke()
QilNode System.Xml.Xsl.Xslt.InvokeGenerator.GenerateInvoke (QilFunction func, IList< XslNode > actualArgs) inline
Definition at line 28 of file InvokeGenerator.cs.
    {
        _iterStack.Clear();
        _formalArgs = func.Arguments;
        _invokeArgs = _fac.ActualParameterList();
        for (_curArg = 0; _curArg < _formalArgs.Count; _curArg++)
        {
            QilParameter qilParameter = (QilParameter)_formalArgs[_curArg];
            QilNode qilNode = FindActualArg(qilParameter, actualArgs);
            if (qilNode == null)
            {
                qilNode = ((!_debug) ? Clone(qilParameter.DefaultValue) : ((!(qilParameter.Name.NamespaceUri == "urn:schemas-microsoft-com:xslt-debug")) ? _fac.DefaultValueMarker() : Clone(qilParameter.DefaultValue)));
            }
            XmlQueryType xmlType = qilParameter.XmlType;
            XmlQueryType xmlType2 = qilNode.XmlType;
            if (!xmlType2.IsSubtypeOf(xmlType))
            {
                qilNode = _fac.TypeAssert(qilNode, xmlType);
            }
            _invokeArgs.Add(qilNode);
        }
        QilNode qilNode2 = _fac.Invoke(func, _invokeArgs);
        while (_iterStack.Count != 0)
        {
            qilNode2 = _fac.Loop(_iterStack.Pop(), qilNode2);
        }
        return qilNode2;
    }
References System.Xml.Xsl.Xslt.InvokeGenerator._curArg, System.Xml.Xsl.Xslt.InvokeGenerator._debug, System.Xml.Xsl.Xslt.InvokeGenerator._fac, System.Xml.Xsl.Xslt.InvokeGenerator._formalArgs, System.Xml.Xsl.Xslt.InvokeGenerator._invokeArgs, System.Xml.Xsl.Xslt.InvokeGenerator._iterStack, System.Xml.Xsl.Qil.QilPatternFactory.ActualParameterList(), System.Xml.Xsl.Qil.QilNode.Add(), System.Collections.Generic.Stack< T >.Clear(), System.Xml.Xsl.Qil.QilCloneVisitor.Clone(), System.Collections.Generic.Stack< T >.Count, System.Xml.Xsl.Qil.QilList.Count, System.Xml.Xsl.Xslt.XsltQilFactory.DefaultValueMarker(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.InvokeGenerator.FindActualArg(), System.Xml.Xsl.Qil.QilPatternFactory.Invoke(), System.Xml.Xsl.Qil.QilPatternFactory.Loop(), System.Collections.Generic.Stack< T >.Pop(), and System.Xml.Xsl.Qil.QilPatternFactory.TypeAssert().
Referenced by System.Xml.Xsl.Xslt.MatcherBuilder.BuildMatcher(), System.Xml.Xsl.Xslt.QilGenerator.CompileCallTemplate(), and System.Xml.Xsl.Xslt.QilGenerator.CompileUseAttributeSet().