Terraria: System.Net.Http.DecompressionHandler.SendAsync
SendAsync() [1/2]
override async ValueTask< HttpResponseMessage > System.Net.Http.DecompressionHandler.SendAsync (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline package
Definition at line 381 of file DecompressionHandler.cs.
    {
        if (GZipEnabled && !EncodingExists(request.Headers.AcceptEncoding, "gzip"))
        {
            request.Headers.AcceptEncoding.Add(s_gzipHeaderValue);
        }
        if (DeflateEnabled && !EncodingExists(request.Headers.AcceptEncoding, "deflate"))
        {
            request.Headers.AcceptEncoding.Add(s_deflateHeaderValue);
        }
        if (BrotliEnabled && !EncodingExists(request.Headers.AcceptEncoding, "br"))
        {
            request.Headers.AcceptEncoding.Add(s_brotliHeaderValue);
        }
        HttpResponseMessage httpResponseMessage = await _innerHandler.SendAsync(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        ICollection<string> contentEncoding = httpResponseMessage.Content.Headers.ContentEncoding;
        if (contentEncoding.Count > 0)
        {
            string text = null;
            foreach (string item in contentEncoding)
            {
                text = item;
            }
            if (GZipEnabled && text == "gzip")
            {
                httpResponseMessage.Content = new GZipDecompressedContent(httpResponseMessage.Content);
            }
            else if (DeflateEnabled && text == "deflate")
            {
                httpResponseMessage.Content = new DeflateDecompressedContent(httpResponseMessage.Content);
            }
            else if (BrotliEnabled && text == "br")
            {
                httpResponseMessage.Content = new BrotliDecompressedContent(httpResponseMessage.Content);
            }
        }
        return httpResponseMessage;
    }
References System.Net.Http.DecompressionHandler._innerHandler, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.DecompressionHandler.BrotliEnabled, System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Http.DecompressionHandler.DeflateEnabled, System.Net.Http.DecompressionHandler.EncodingExists(), System.Net.Http.DecompressionHandler.GZipEnabled, System.item, System.Net.Http.DecompressionHandler.s_brotliHeaderValue, System.Net.Http.DecompressionHandler.s_deflateHeaderValue, System.Net.Http.DecompressionHandler.s_gzipHeaderValue, System.Net.Http.HttpMessageHandlerStage.SendAsync(), and System.text.