Terraria: System.Xml.Xsl.IlGen.UniqueList.Add
Add()
int System.Xml.Xsl.IlGen.UniqueList< T >.Add (T value) inline
Definition at line 11 of file UniqueList.cs.
    {
        int num;
        if (!_lookup.ContainsKey(value))
        {
            num = _list.Count;
            _lookup.Add(value, num);
            _list.Add(value);
        }
        else
        {
            num = _lookup[value];
        }
        return num;
    }
References System.Xml.Xsl.IlGen.UniqueList< T >._list, System.Xml.Xsl.IlGen.UniqueList< T >._lookup, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), and System.value.
Referenced by System.Xml.Xsl.IlGen.StaticDataManager.DeclareCollation(), System.Xml.Xsl.IlGen.StaticDataManager.DeclareEarlyBound(), and System.Xml.Xsl.IlGen.StaticDataManager.DeclareName().