Terraria: System.Xml.Xsl.Xslt.InvokeGenerator.VisitReference
VisitReference()
override QilNode System.Xml.Xsl.Xslt.InvokeGenerator.VisitReference (QilNode n) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilCloneVisitor.
Definition at line 70 of file InvokeGenerator.cs.
    {
        QilNode qilNode = FindClonedReference(n);
        if (qilNode != null)
        {
            return qilNode;
        }
        for (int i = 0; i < _curArg; i++)
        {
            if (n == _formalArgs[i])
            {
                if (_invokeArgs[i] is QilLiteral)
                {
                    return _invokeArgs[i].ShallowClone(_fac.BaseFactory);
                }
                if (!(_invokeArgs[i] is QilIterator))
                {
                    QilIterator qilIterator = _fac.BaseFactory.Let(_invokeArgs[i]);
                    _iterStack.Push(qilIterator);
                    _invokeArgs[i] = qilIterator;
                }
                return _invokeArgs[i];
            }
        }
        return n;
    }
References System.Xml.Xsl.Xslt.InvokeGenerator._curArg, System.Xml.Xsl.Xslt.InvokeGenerator._fac, System.Xml.Xsl.Xslt.InvokeGenerator._formalArgs, System.Xml.Xsl.Xslt.InvokeGenerator._invokeArgs, System.Xml.Xsl.Xslt.InvokeGenerator._iterStack, System.Xml.Xsl.Qil.QilPatternFactory.BaseFactory, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilCloneVisitor.FindClonedReference(), System.Xml.Xsl.Qil.QilFactory.Let(), System.Collections.Generic.Stack< T >.Push(), and System.Xml.Xsl.Qil.QilList.ShallowClone().