Terraria: System.Net.Http.HPack.IntegerDecoder.TryDecode
TryDecode()
bool System.Net.Http.HPack.IntegerDecoder.TryDecode (byte b, out int result) inline
Definition at line 24 of file IntegerDecoder.cs.
    {
        if (BitOperations.LeadingZeroCount(b) <= _m)
        {
            throw new HPackDecodingException(System.SR.net_http_hpack_bad_integer);
        }
        _i += (b & 0x7F) << _m;
        if (_i < 0)
        {
            throw new HPackDecodingException(System.SR.net_http_hpack_bad_integer);
        }
        _m += 7;
        if ((b & 0x80) == 0)
        {
            if (b == 0 && _m / 7 > 1)
            {
                throw new HPackDecodingException(System.SR.net_http_hpack_bad_integer);
            }
            result = _i;
            return true;
        }
        result = 0;
        return false;
    }
References System.Net.Http.HPack.IntegerDecoder._i, System.Net.Http.HPack.IntegerDecoder._m, System.Numerics.BitOperations.LeadingZeroCount(), and System.SR.net_http_hpack_bad_integer.
Referenced by System.Net.Http.QPack.QPackDecoder.OnByte(), and System.Net.Http.HPack.HPackDecoder.TryDecodeInteger().