Terraria: System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore
TryEnterUpgradeableReadLockCore()
bool System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore (TimeoutTracker timeout) inline private
Definition at line 744 of file ReaderWriterLockSlim.cs.
    {
        if (_fDisposed)
        {
            throw new ObjectDisposedException(null);
        }
        int currentManagedThreadId = Environment.CurrentManagedThreadId;
        ReaderWriterCount threadRWCount;
        if (!_fIsReentrant)
        {
            if (currentManagedThreadId == _upgradeLockOwnerId)
            {
                throw new LockRecursionException(SR.LockRecursionException_RecursiveUpgradeNotAllowed);
            }
            if (currentManagedThreadId == _writeLockOwnerId)
            {
                throw new LockRecursionException(SR.LockRecursionException_UpgradeAfterWriteNotAllowed);
            }
            _spinLock.Enter(EnterSpinLockReason.EnterAnyRead);
            threadRWCount = GetThreadRWCount(dontAllocate: true);
            if (threadRWCount != null && threadRWCount.readercount > 0)
            {
                _spinLock.Exit();
                throw new LockRecursionException(SR.LockRecursionException_UpgradeAfterReadNotAllowed);
            }
        }
        else
        {
            _spinLock.Enter(EnterSpinLockReason.EnterAnyRead);
            threadRWCount = GetThreadRWCount(dontAllocate: false);
            if (currentManagedThreadId == _upgradeLockOwnerId)
            {
                threadRWCount.upgradecount++;
                _spinLock.Exit();
                return true;
            }
            if (currentManagedThreadId == _writeLockOwnerId)
            {
                _owners++;
                _upgradeLockOwnerId = currentManagedThreadId;
                threadRWCount.upgradecount++;
                if (threadRWCount.readercount > 0)
                {
                    _fUpgradeThreadHoldingRead = true;
                }
                _spinLock.Exit();
                return true;
            }
            if (threadRWCount.readercount > 0)
            {
                _spinLock.Exit();
                throw new LockRecursionException(SR.LockRecursionException_UpgradeAfterReadNotAllowed);
            }
        }
        bool flag = true;
        int num = 0;
        while (true)
        {
            if (_upgradeLockOwnerId == -1 && _owners < 268435454)
            {
                _owners++;
                _upgradeLockOwnerId = currentManagedThreadId;
                if (_fIsReentrant)
                {
                    if (IsRwHashEntryChanged(threadRWCount))
                    {
                        threadRWCount = GetThreadRWCount(dontAllocate: false);
                    }
                    threadRWCount.upgradecount++;
                }
                break;
            }
            if (timeout.IsExpired)
            {
                _spinLock.Exit();
                return false;
            }
            if (num < 20 && ShouldSpinForEnterAnyRead())
            {
                _spinLock.Exit();
                num++;
                SpinWait(num);
                _spinLock.Enter(EnterSpinLockReason.EnterAnyRead);
            }
            else if (_upgradeEvent == null)
            {
                LazyCreateEvent(ref _upgradeEvent, EnterLockType.UpgradeableRead);
            }
            else if (!WaitOnEvent(_upgradeEvent, ref _numUpgradeWaiters, timeout, EnterLockType.UpgradeableRead))
            {
                return false;
            }
        }
        _spinLock.Exit();
        return true;
    }
References System.Threading.ReaderWriterLockSlim._fDisposed, System.Threading.ReaderWriterLockSlim._fIsReentrant, System.Threading.ReaderWriterLockSlim._fUpgradeThreadHoldingRead, System.Threading.ReaderWriterLockSlim._numUpgradeWaiters, System.Threading.ReaderWriterLockSlim._owners, System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.ReaderWriterLockSlim._upgradeEvent, System.Threading.ReaderWriterLockSlim._upgradeLockOwnerId, System.Threading.ReaderWriterLockSlim._writeLockOwnerId, System.Environment.CurrentManagedThreadId, System.Threading.ReaderWriterLockSlim.SpinLock.Enter(), System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.ReaderWriterLockSlim.GetThreadRWCount(), System.Threading.ReaderWriterLockSlim.IsRwHashEntryChanged(), System.Threading.ReaderWriterLockSlim.LazyCreateEvent(), System.SR.LockRecursionException_RecursiveUpgradeNotAllowed, System.SR.LockRecursionException_UpgradeAfterReadNotAllowed, System.SR.LockRecursionException_UpgradeAfterWriteNotAllowed, System.Threading.ReaderWriterCount.readercount, System.Threading.ReaderWriterLockSlim.ShouldSpinForEnterAnyRead(), System.Threading.ReaderWriterLockSlim.SpinWait(), System.timeout, System.Threading.ReaderWriterCount.upgradecount, and System.Threading.ReaderWriterLockSlim.WaitOnEvent().
Referenced by System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLock().