Terraria: System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore
TryEnterReadLockCore()
bool System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore (TimeoutTracker timeout) inline private
Definition at line 469 of file ReaderWriterLockSlim.cs.
    {
        if (_fDisposed)
        {
            throw new ObjectDisposedException(null);
        }
        int currentManagedThreadId = Environment.CurrentManagedThreadId;
        ReaderWriterCount threadRWCount;
        if (!_fIsReentrant)
        {
            if (currentManagedThreadId == _writeLockOwnerId)
            {
                throw new LockRecursionException(SR.LockRecursionException_ReadAfterWriteNotAllowed);
            }
            _spinLock.Enter(EnterSpinLockReason.EnterAnyRead);
            threadRWCount = GetThreadRWCount(dontAllocate: false);
            if (threadRWCount.readercount > 0)
            {
                _spinLock.Exit();
                throw new LockRecursionException(SR.LockRecursionException_RecursiveReadNotAllowed);
            }
            if (currentManagedThreadId == _upgradeLockOwnerId)
            {
                threadRWCount.readercount++;
                _owners++;
                _spinLock.Exit();
                return true;
            }
        }
        else
        {
            _spinLock.Enter(EnterSpinLockReason.EnterAnyRead);
            threadRWCount = GetThreadRWCount(dontAllocate: false);
            if (threadRWCount.readercount > 0)
            {
                threadRWCount.readercount++;
                _spinLock.Exit();
                return true;
            }
            if (currentManagedThreadId == _upgradeLockOwnerId)
            {
                threadRWCount.readercount++;
                _owners++;
                _spinLock.Exit();
                _fUpgradeThreadHoldingRead = true;
                return true;
            }
            if (currentManagedThreadId == _writeLockOwnerId)
            {
                threadRWCount.readercount++;
                _owners++;
                _spinLock.Exit();
                return true;
            }
        }
        bool flag = true;
        int num = 0;
        while (true)
        {
            if (_owners < 268435454)
            {
                _owners++;
                threadRWCount.readercount++;
                _spinLock.Exit();
                return flag;
            }
            if (timeout.IsExpired)
            {
                _spinLock.Exit();
                return false;
            }
            if (num < 20 && ShouldSpinForEnterAnyRead())
            {
                _spinLock.Exit();
                num++;
                SpinWait(num);
                _spinLock.Enter(EnterSpinLockReason.EnterAnyRead);
                if (IsRwHashEntryChanged(threadRWCount))
                {
                    threadRWCount = GetThreadRWCount(dontAllocate: false);
                }
            }
            else if (_readEvent == null)
            {
                LazyCreateEvent(ref _readEvent, EnterLockType.Read);
                if (IsRwHashEntryChanged(threadRWCount))
                {
                    threadRWCount = GetThreadRWCount(dontAllocate: false);
                }
            }
            else
            {
                flag = WaitOnEvent(_readEvent, ref _numReadWaiters, timeout, EnterLockType.Read);
                if (!flag)
                {
                    break;
                }
                if (IsRwHashEntryChanged(threadRWCount))
                {
                    threadRWCount = GetThreadRWCount(dontAllocate: false);
                }
            }
        }
        return false;
    }
References System.Threading.ReaderWriterLockSlim._fDisposed, System.Threading.ReaderWriterLockSlim._fIsReentrant, System.Threading.ReaderWriterLockSlim._fUpgradeThreadHoldingRead, System.Threading.ReaderWriterLockSlim._numReadWaiters, System.Threading.ReaderWriterLockSlim._owners, System.Threading.ReaderWriterLockSlim._readEvent, System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.ReaderWriterLockSlim._upgradeLockOwnerId, System.Threading.ReaderWriterLockSlim._writeLockOwnerId, System.Environment.CurrentManagedThreadId, System.Threading.ReaderWriterLockSlim.SpinLock.Enter(), System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.ReaderWriterLockSlim.GetThreadRWCount(), System.Threading.ReaderWriterLockSlim.IsRwHashEntryChanged(), System.Threading.ReaderWriterLockSlim.LazyCreateEvent(), System.SR.LockRecursionException_ReadAfterWriteNotAllowed, System.SR.LockRecursionException_RecursiveReadNotAllowed, System.Threading.ReaderWriterCount.readercount, System.Threading.ReaderWriterLockSlim.ShouldSpinForEnterAnyRead(), System.Threading.ReaderWriterLockSlim.SpinWait(), System.timeout, and System.Threading.ReaderWriterLockSlim.WaitOnEvent().
Referenced by System.Threading.ReaderWriterLockSlim.TryEnterReadLock().