Terraria: System.Threading.ReaderWriterLockSlim.EnterWriteLock
EnterWriteLock()
void System.Threading.ReaderWriterLockSlim.EnterWriteLock () inline
Definition at line 575 of file ReaderWriterLockSlim.cs.
    {
        TryEnterWriteLock(-1);
    }
References System.Threading.ReaderWriterLockSlim.TryEnterWriteLock().
Referenced by System.Data.Index.AddRef(), System.Text.CodePagesEncodingProvider.GetEncoding(), System.Data.Index.RemoveRef(), and System.Security.AccessControl.ObjectSecurity< T >.WriteLock().