Terraria: System.Threading.ReaderWriterLockSlim.LazyCreateEvent
LazyCreateEvent()
void System.Threading.ReaderWriterLockSlim.LazyCreateEvent ([NotNull] ref EventWaitHandle waitEvent, EnterLockType enterLockType) inline private
Definition at line 941 of file ReaderWriterLockSlim.cs.
    {
        _spinLock.Exit();
        EventWaitHandle eventWaitHandle = new EventWaitHandle(initialState: false, (enterLockType == EnterLockType.Read) ? EventResetMode.ManualReset : EventResetMode.AutoReset);
        EnterSpinLockReason reason;
        switch (enterLockType)
        {
        case EnterLockType.Read:
        case EnterLockType.UpgradeableRead:
            reason = EnterSpinLockReason.Wait;
            break;
        case EnterLockType.Write:
            reason = (EnterSpinLockReason)10;
            break;
        default:
            reason = (EnterSpinLockReason)11;
            break;
        }
        _spinLock.Enter(reason);
        if (waitEvent == null)
        {
            waitEvent = eventWaitHandle;
        }
        else
        {
            eventWaitHandle.Dispose();
        }
    }
References System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.WaitHandle.Dispose(), System.Threading.ReaderWriterLockSlim.SpinLock.Enter(), and System.Threading.ReaderWriterLockSlim.SpinLock.Exit().
Referenced by System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(), System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore(), and System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore().