Terraria: System.Threading.ReaderWriterLockSlim.ExitReadLock
ExitReadLock()
void System.Threading.ReaderWriterLockSlim.ExitReadLock () inline
Definition at line 841 of file ReaderWriterLockSlim.cs.
    {
        _spinLock.Enter(EnterSpinLockReason.ExitAnyRead);
        ReaderWriterCount threadRWCount = GetThreadRWCount(dontAllocate: true);
        if (threadRWCount == null || threadRWCount.readercount < 1)
        {
            _spinLock.Exit();
            throw new SynchronizationLockException(SR.SynchronizationLockException_MisMatchedRead);
        }
        if (_fIsReentrant)
        {
            if (threadRWCount.readercount > 1)
            {
                threadRWCount.readercount--;
                _spinLock.Exit();
                return;
            }
            if (Environment.CurrentManagedThreadId == _upgradeLockOwnerId)
            {
                _fUpgradeThreadHoldingRead = false;
            }
        }
        _owners--;
        threadRWCount.readercount--;
        ExitAndWakeUpAppropriateWaiters();
    }
References System.Threading.ReaderWriterLockSlim._fIsReentrant, System.Threading.ReaderWriterLockSlim._fUpgradeThreadHoldingRead, System.Threading.ReaderWriterLockSlim._owners, System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.ReaderWriterLockSlim._upgradeLockOwnerId, System.Environment.CurrentManagedThreadId, System.Threading.ReaderWriterLockSlim.SpinLock.Enter(), System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateWaiters(), System.Threading.ReaderWriterLockSlim.GetThreadRWCount(), System.Threading.ReaderWriterCount.readercount, and System.SR.SynchronizationLockException_MisMatchedRead.
Referenced by System.Security.AccessControl.ObjectSecurity< T >.ReadUnlock().