Terraria: System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateReadWaiters
ExitAndWakeUpAppropriateReadWaiters()
void System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateReadWaiters () inline private
Definition at line 1090 of file ReaderWriterLockSlim.cs.
    {
        if (_numWriteWaiters != 0 || _numWriteUpgradeWaiters != 0 || HasNoWaiters)
        {
            _spinLock.Exit();
            return;
        }
        bool flag = _numReadWaiters != 0;
        bool flag2 = _numUpgradeWaiters != 0 && _upgradeLockOwnerId == -1;
        if (flag2)
        {
            if ((_waiterStates & WaiterStates.UpgradeableReadWaiterSignaled) == 0)
            {
                _waiterStates |= WaiterStates.UpgradeableReadWaiterSignaled;
            }
            else
            {
                flag2 = false;
            }
        }
        _spinLock.Exit();
        if (flag)
        {
            _readEvent.Set();
        }
        if (flag2)
        {
            _upgradeEvent.Set();
        }
    }
References System.Threading.ReaderWriterLockSlim._numReadWaiters, System.Threading.ReaderWriterLockSlim._numUpgradeWaiters, System.Threading.ReaderWriterLockSlim._numWriteUpgradeWaiters, System.Threading.ReaderWriterLockSlim._numWriteWaiters, System.Threading.ReaderWriterLockSlim._readEvent, System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.ReaderWriterLockSlim._upgradeEvent, System.Threading.ReaderWriterLockSlim._upgradeLockOwnerId, System.Threading.ReaderWriterLockSlim._waiterStates, System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.ReaderWriterLockSlim.HasNoWaiters, and System.Threading.EventWaitHandle.Set().
Referenced by System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateWaitersPreferringWriters(), and System.Threading.ReaderWriterLockSlim.WaitOnEvent().