Terraria: System.Threading.ReaderWriterLockSlim.ExitWriteLock
ExitWriteLock()
void System.Threading.ReaderWriterLockSlim.ExitWriteLock () inline
Definition at line 868 of file ReaderWriterLockSlim.cs.
    {
        if (!_fIsReentrant)
        {
            if (Environment.CurrentManagedThreadId != _writeLockOwnerId)
            {
                throw new SynchronizationLockException(SR.SynchronizationLockException_MisMatchedWrite);
            }
            _spinLock.Enter(EnterSpinLockReason.ExitAnyWrite);
        }
        else
        {
            _spinLock.Enter(EnterSpinLockReason.ExitAnyWrite);
            ReaderWriterCount threadRWCount = GetThreadRWCount(dontAllocate: false);
            if (threadRWCount == null)
            {
                _spinLock.Exit();
                throw new SynchronizationLockException(SR.SynchronizationLockException_MisMatchedWrite);
            }
            if (threadRWCount.writercount < 1)
            {
                _spinLock.Exit();
                throw new SynchronizationLockException(SR.SynchronizationLockException_MisMatchedWrite);
            }
            threadRWCount.writercount--;
            if (threadRWCount.writercount > 0)
            {
                _spinLock.Exit();
                return;
            }
        }
        ClearWriterAcquired();
        _writeLockOwnerId = -1;
        ExitAndWakeUpAppropriateWaiters();
    }
References System.Threading.ReaderWriterLockSlim._fIsReentrant, System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.ReaderWriterLockSlim._writeLockOwnerId, System.Threading.ReaderWriterLockSlim.ClearWriterAcquired(), System.Environment.CurrentManagedThreadId, System.Threading.ReaderWriterLockSlim.SpinLock.Enter(), System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateWaiters(), System.Threading.ReaderWriterLockSlim.GetThreadRWCount(), System.SR.SynchronizationLockException_MisMatchedWrite, and System.Threading.ReaderWriterCount.writercount.
Referenced by System.Data.Index.AddRef(), System.Text.CodePagesEncodingProvider.GetEncoding(), System.Data.Index.RemoveRef(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().