Terraria: System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateWaitersPreferringWriters
ExitAndWakeUpAppropriateWaitersPreferringWriters()
void System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateWaitersPreferringWriters () inline private
Definition at line 1058 of file ReaderWriterLockSlim.cs.
    {
        uint numReaders = GetNumReaders();
        if (_fIsReentrant && _numWriteUpgradeWaiters != 0 && _fUpgradeThreadHoldingRead && numReaders == 2)
        {
            _spinLock.Exit();
            _waitUpgradeEvent.Set();
        }
        else if (numReaders == 1 && _numWriteUpgradeWaiters != 0)
        {
            _spinLock.Exit();
            _waitUpgradeEvent.Set();
        }
        else if (numReaders == 0 && _numWriteWaiters != 0)
        {
            WaiterStates waiterStates = _waiterStates & WaiterStates.WriteWaiterSignaled;
            if (waiterStates == WaiterStates.None)
            {
                _waiterStates |= WaiterStates.WriteWaiterSignaled;
            }
            _spinLock.Exit();
            if (waiterStates == WaiterStates.None)
            {
                _writeEvent.Set();
            }
        }
        else
        {
            ExitAndWakeUpAppropriateReadWaiters();
        }
    }
References System.Threading.ReaderWriterLockSlim._fIsReentrant, System.Threading.ReaderWriterLockSlim._fUpgradeThreadHoldingRead, System.Threading.ReaderWriterLockSlim._numWriteUpgradeWaiters, System.Threading.ReaderWriterLockSlim._numWriteWaiters, System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.ReaderWriterLockSlim._waiterStates, System.Threading.ReaderWriterLockSlim._waitUpgradeEvent, System.Threading.ReaderWriterLockSlim._writeEvent, System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateReadWaiters(), System.Threading.ReaderWriterLockSlim.GetNumReaders(), and System.Threading.EventWaitHandle.Set().
Referenced by System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateWaiters().