Terraria: System.Threading.ReaderWriterLockSlim.WaitOnEvent
WaitOnEvent()
bool System.Threading.ReaderWriterLockSlim.WaitOnEvent (EventWaitHandle waitEvent, ref uint numWaiters, TimeoutTracker timeout, EnterLockType enterLockType) inline private
Definition at line 970 of file ReaderWriterLockSlim.cs.
    {
        WaiterStates waiterStates = WaiterStates.None;
        EnterSpinLockReason reason;
        switch (enterLockType)
        {
        case EnterLockType.UpgradeableRead:
            waiterStates = WaiterStates.UpgradeableReadWaiterSignaled;
            goto case EnterLockType.Read;
        case EnterLockType.Read:
            reason = EnterSpinLockReason.EnterAnyRead;
            break;
        case EnterLockType.Write:
            waiterStates = WaiterStates.WriteWaiterSignaled;
            reason = EnterSpinLockReason.EnterWrite;
            break;
        default:
            reason = EnterSpinLockReason.UpgradeToWrite;
            break;
        }
        if (waiterStates != 0 && (_waiterStates & waiterStates) != 0)
        {
            _waiterStates &= (WaiterStates)(byte)(~(int)waiterStates);
        }
        waitEvent.Reset();
        numWaiters++;
        HasNoWaiters = false;
        if (_numWriteWaiters == 1)
        {
            SetWritersWaiting();
        }
        if (_numWriteUpgradeWaiters == 1)
        {
            SetUpgraderWaiting();
        }
        bool flag = false;
        _spinLock.Exit();
        try
        {
            flag = waitEvent.WaitOne(timeout.RemainingMilliseconds);
        }
        finally
        {
            _spinLock.Enter(reason);
            numWaiters--;
            if (flag && waiterStates != 0 && (_waiterStates & waiterStates) != 0)
            {
                _waiterStates &= (WaiterStates)(byte)(~(int)waiterStates);
            }
            if (_numWriteWaiters == 0 && _numWriteUpgradeWaiters == 0 && _numUpgradeWaiters == 0 && _numReadWaiters == 0)
            {
                HasNoWaiters = true;
            }
            if (_numWriteWaiters == 0)
            {
                ClearWritersWaiting();
            }
            if (_numWriteUpgradeWaiters == 0)
            {
                ClearUpgraderWaiting();
            }
            if (!flag)
            {
                if (enterLockType >= EnterLockType.Write)
                {
                    ExitAndWakeUpAppropriateReadWaiters();
                }
                else
                {
                    _spinLock.Exit();
                }
            }
        }
        return flag;
    }
References System.Threading.ReaderWriterLockSlim._numReadWaiters, System.Threading.ReaderWriterLockSlim._numUpgradeWaiters, System.Threading.ReaderWriterLockSlim._numWriteUpgradeWaiters, System.Threading.ReaderWriterLockSlim._numWriteWaiters, System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.ReaderWriterLockSlim._waiterStates, System.Threading.ReaderWriterLockSlim.ClearUpgraderWaiting(), System.Threading.ReaderWriterLockSlim.ClearWritersWaiting(), System.Threading.ReaderWriterLockSlim.SpinLock.Enter(), System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateReadWaiters(), System.Threading.ReaderWriterLockSlim.HasNoWaiters, System.Threading.EventWaitHandle.Reset(), System.Threading.ReaderWriterLockSlim.SetUpgraderWaiting(), System.Threading.ReaderWriterLockSlim.SetWritersWaiting(), System.timeout, and System.Threading.WaitHandle.WaitOne().
Referenced by System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(), System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore(), and System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore().