Terraria: System.Threading.ReaderWriterLockSlim.ExitUpgradeableReadLock
ExitUpgradeableReadLock()
void System.Threading.ReaderWriterLockSlim.ExitUpgradeableReadLock () inline
Definition at line 904 of file ReaderWriterLockSlim.cs.
    {
        if (!_fIsReentrant)
        {
            if (Environment.CurrentManagedThreadId != _upgradeLockOwnerId)
            {
                throw new SynchronizationLockException(SR.SynchronizationLockException_MisMatchedUpgrade);
            }
            _spinLock.Enter(EnterSpinLockReason.ExitAnyRead);
        }
        else
        {
            _spinLock.Enter(EnterSpinLockReason.ExitAnyRead);
            ReaderWriterCount threadRWCount = GetThreadRWCount(dontAllocate: true);
            if (threadRWCount == null)
            {
                _spinLock.Exit();
                throw new SynchronizationLockException(SR.SynchronizationLockException_MisMatchedUpgrade);
            }
            if (threadRWCount.upgradecount < 1)
            {
                _spinLock.Exit();
                throw new SynchronizationLockException(SR.SynchronizationLockException_MisMatchedUpgrade);
            }
            threadRWCount.upgradecount--;
            if (threadRWCount.upgradecount > 0)
            {
                _spinLock.Exit();
                return;
            }
            _fUpgradeThreadHoldingRead = false;
        }
        _owners--;
        _upgradeLockOwnerId = -1;
        ExitAndWakeUpAppropriateWaiters();
    }
References System.Threading.ReaderWriterLockSlim._fIsReentrant, System.Threading.ReaderWriterLockSlim._fUpgradeThreadHoldingRead, System.Threading.ReaderWriterLockSlim._owners, System.Threading.ReaderWriterLockSlim._spinLock, System.Threading.ReaderWriterLockSlim._upgradeLockOwnerId, System.Environment.CurrentManagedThreadId, System.Threading.ReaderWriterLockSlim.SpinLock.Enter(), System.Threading.ReaderWriterLockSlim.SpinLock.Exit(), System.Threading.ReaderWriterLockSlim.ExitAndWakeUpAppropriateWaiters(), System.Threading.ReaderWriterLockSlim.GetThreadRWCount(), System.SR.SynchronizationLockException_MisMatchedUpgrade, and System.Threading.ReaderWriterCount.upgradecount.
Referenced by System.Text.CodePagesEncodingProvider.GetEncoding(), and System.Data.DataTable.GetIndex().