Terraria: System.Reflection.Throw.InvalidOperation_TableNotSorted
InvalidOperation_TableNotSorted()
static void System.Reflection.Throw.InvalidOperation_TableNotSorted (TableIndex tableIndex) inline static package
Definition at line 257 of file Throw.cs.
    {
        throw new InvalidOperationException(System.SR.Format(System.SR.MetadataTableNotSorted, tableIndex));
    }
References System.SR.Format(), and System.SR.MetadataTableNotSorted.
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateClassLayoutTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateFieldLayoutTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateFieldRvaTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateGenericParamConstaintTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateGenericParamTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateImplMapTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateInterfaceImplTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateLocalScopeTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateMethodImplTable(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateNestedClassTable(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.ValidateStateMachineMethodTable().