Terraria: System.Reflection.Throw.InvalidOperation
InvalidOperation()
static void System.Reflection.Throw.InvalidOperation (string message) inline static package
Definition at line 68 of file Throw.cs.
    {
        throw new InvalidOperationException(message);
    }
Referenced by System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.Add(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddAssembly(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddModule(), and System.Reflection.Metadata.Ecma335.ControlFlowBuilder.SerializeExceptionTable().