Terraria: System.Reflection.Throw.InvalidArgument_UnexpectedHandleKind
InvalidArgument_UnexpectedHandleKind()
static Exception System.Reflection.Throw.InvalidArgument_UnexpectedHandleKind (HandleKind kind) inline static package
Definition at line 33 of file Throw.cs.
    {
        throw new ArgumentException(System.SR.Format(System.SR.UnexpectedHandleKind, kind));
    }
References System.SR.Format(), and System.SR.UnexpectedHandleKind.
Referenced by System.Reflection.Metadata.Ecma335.MetadataTokens.MapVirtualHandleRowId(), System.Reflection.Metadata.Ecma335.CodedIndex.ToCustomAttributeTypeTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToHasConstantTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToHasCustomAttributeTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToHasCustomDebugInformationTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToHasDeclSecurityTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToHasFieldMarshalTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToHasSemanticsTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToImplementationTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToMemberForwardedTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToMemberRefParentTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToMethodDefOrRefTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToResolutionScopeTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToTypeDefOrRefOrSpecTag(), System.Reflection.Metadata.Ecma335.CodedIndex.ToTypeDefOrRefTag(), and System.Reflection.Metadata.Ecma335.CodedIndex.ToTypeOrMethodDefTag().