Terraria: System.Reflection.Internal.ByteSequenceComparer.Equals
Equals() [4/7]
static bool System.Reflection.Internal.ByteSequenceComparer.Equals (ImmutableArray< byte > x, ImmutableArray< byte > y) inline static package
Definition at line 14 of file ByteSequenceComparer.cs.
    {
        if (x == y)
        {
            return true;
        }
        if (x.IsDefault || y.IsDefault || x.Length != y.Length)
        {
            return false;
        }
        for (int i = 0; i < x.Length; i++)
        {
            if (x[i] != y[i])
            {
                return false;
            }
        }
        return true;
    }
Referenced by System.Reflection.Metadata.BlobBuilder.ContentEquals(), System.Reflection.Metadata.BlobWriter.ContentEquals(), System.Reflection.Internal.ByteSequenceComparer.Equals(), and System.Reflection.Internal.ByteSequenceComparer.Equals().