Terraria: System.Reflection.Throw.TableNotSorted
TableNotSorted()
static void System.Reflection.Throw.TableNotSorted (TableIndex tableIndex) inline static package
Definition at line 250 of file Throw.cs.
    {
        throw new BadImageFormatException(System.SR.Format(System.SR.MetadataTableNotSorted, tableIndex));
    }
References System.SR.Format(), and System.SR.MetadataTableNotSorted.
Referenced by System.Reflection.Metadata.Ecma335.ClassLayoutTableReader.ClassLayoutTableReader(), System.Reflection.Metadata.Ecma335.ConstantTableReader.ConstantTableReader(), System.Reflection.Metadata.Ecma335.CustomDebugInformationTableReader.CustomDebugInformationTableReader(), System.Reflection.Metadata.Ecma335.DeclSecurityTableReader.DeclSecurityTableReader(), System.Reflection.Metadata.Ecma335.FieldLayoutTableReader.FieldLayoutTableReader(), System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.FieldMarshalTableReader(), System.Reflection.Metadata.Ecma335.FieldRVATableReader.FieldRVATableReader(), System.Reflection.Metadata.Ecma335.GenericParamConstraintTableReader.GenericParamConstraintTableReader(), System.Reflection.Metadata.Ecma335.GenericParamTableReader.GenericParamTableReader(), System.Reflection.Metadata.Ecma335.ImplMapTableReader.ImplMapTableReader(), System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.InterfaceImplTableReader(), System.Reflection.Metadata.Ecma335.LocalScopeTableReader.LocalScopeTableReader(), System.Reflection.Metadata.Ecma335.MethodImplTableReader.MethodImplTableReader(), System.Reflection.Metadata.Ecma335.MethodSemanticsTableReader.MethodSemanticsTableReader(), System.Reflection.Metadata.Ecma335.NestedClassTableReader.NestedClassTableReader(), and System.Reflection.Metadata.Ecma335.StateMachineMethodTableReader.StateMachineMethodTableReader().