Terraria: System.Reflection.Throw.ArgumentOutOfRange
ArgumentOutOfRange() [1/2]
static void System.Reflection.Throw.ArgumentOutOfRange (string parameterName) inline static package
Definition at line 145 of file Throw.cs.
    {
        throw new ArgumentOutOfRangeException(parameterName);
    }
Referenced by System.Reflection.Metadata.BlobBuilder.BlobBuilder(), System.Reflection.PortableExecutable.ManagedPEBuilder.ManagedPEBuilder(), System.Reflection.Metadata.Ecma335.MetadataBuilder.MetadataBuilder(), System.Reflection.Metadata.MetadataReader.MetadataReader(), System.Reflection.PortableExecutable.PEHeaderBuilder.PEHeaderBuilder(), System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.Add(), System.Reflection.PortableExecutable.DebugDirectoryBuilder.AddCodeViewEntry(), System.Reflection.PortableExecutable.DebugDirectoryBuilder.AddEmbeddedPortablePdbEntry(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddFieldRelativeVirtualAddress(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddGenericParameter(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddLocalVariable(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddMethodDefinition(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddModule(), System.Reflection.Metadata.Ecma335.MetadataBuilder.AddParameter(), System.Reflection.Metadata.Ecma335.CustomAttributeNamedArgumentsEncoder.Count(), System.Reflection.Metadata.Ecma335.VectorEncoder.Count(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.FunctionPointer(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericInstantiation(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericMethodTypeParameter(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericTypeParameter(), System.Reflection.Metadata.Ecma335.MetadataSizes.GetAlignedHeapSize(), System.Reflection.PortableExecutable.PEReader.GetSectionData(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgument(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgumentAddress(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadLocal(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadLocalAddress(), System.Reflection.Metadata.Ecma335.BlobEncoder.LocalVariableSignature(), System.Reflection.Metadata.Ecma335.BlobEncoder.MethodSignature(), System.Reflection.Metadata.Ecma335.BlobEncoder.MethodSpecificationSignature(), System.Reflection.Metadata.Ecma335.MethodSignatureEncoder.Parameters(), System.Reflection.Metadata.Ecma335.BlobEncoder.PermissionSetArguments(), System.Reflection.Metadata.Ecma335.BlobEncoder.PermissionSetBlob(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.PrimitiveType(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.PrimitiveType(), System.Reflection.Metadata.BlobBuilder.ReserveBytes(), System.Reflection.Metadata.Ecma335.MetadataBuilder.ReserveUserString(), System.Reflection.Metadata.Ecma335.MetadataRootBuilder.Serialize(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SetCapacity(), System.Reflection.Metadata.Ecma335.MetadataBuilder.SetCapacity(), System.Reflection.Metadata.Ecma335.ArrayShapeEncoder.Shape(), System.Reflection.Metadata.Ecma335.InstructionEncoder.StoreArgument(), System.Reflection.Metadata.Ecma335.InstructionEncoder.StoreLocal(), System.Reflection.BlobUtilities.ValidateRange(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobWriter.WriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobWriter.WriteBytes(), and System.Reflection.Metadata.BlobWriter.WriteBytes().