Terraria: System.Reflection.Throw.InvalidArgument
InvalidArgument()
static void System.Reflection.Throw.InvalidArgument (string message, string parameterName) inline static package
Definition at line 19 of file Throw.cs.
    {
        throw new ArgumentException(message, parameterName);
    }
Referenced by System.Reflection.Metadata.MetadataReader.MetadataReader(), System.Reflection.Metadata.Ecma335.MetadataRootBuilder.MetadataRootBuilder(), System.Reflection.PortableExecutable.DebugDirectoryBuilder.AddCodeViewEntry(), System.Reflection.PortableExecutable.PEReader.ReadCodeViewDebugDirectoryData(), System.Reflection.PortableExecutable.PEReader.ReadEmbeddedPortablePdbDebugDirectoryData(), and System.Reflection.PortableExecutable.PEReader.ReadPdbChecksumDebugDirectoryData().