Terraria: System.Reflection.Throw.InvalidCast
InvalidCast()
static void System.Reflection.Throw.InvalidCast () inline static package
Definition at line 12 of file Throw.cs.
    {
        throw new InvalidCastException();
    }
Referenced by System.Reflection.Metadata.AssemblyDefinitionHandle.operator AssemblyDefinitionHandle(), System.Reflection.Metadata.AssemblyDefinitionHandle.operator AssemblyDefinitionHandle(), System.Reflection.Metadata.AssemblyFileHandle.operator AssemblyFileHandle(), System.Reflection.Metadata.AssemblyFileHandle.operator AssemblyFileHandle(), System.Reflection.Metadata.AssemblyReferenceHandle.operator AssemblyReferenceHandle(), System.Reflection.Metadata.AssemblyReferenceHandle.operator AssemblyReferenceHandle(), System.Reflection.Metadata.BlobHandle.operator BlobHandle(), System.Reflection.Metadata.ConstantHandle.operator ConstantHandle(), System.Reflection.Metadata.ConstantHandle.operator ConstantHandle(), System.Reflection.Metadata.CustomAttributeHandle.operator CustomAttributeHandle(), System.Reflection.Metadata.CustomAttributeHandle.operator CustomAttributeHandle(), System.Reflection.Metadata.CustomDebugInformationHandle.operator CustomDebugInformationHandle(), System.Reflection.Metadata.CustomDebugInformationHandle.operator CustomDebugInformationHandle(), System.Reflection.Metadata.DeclarativeSecurityAttributeHandle.operator DeclarativeSecurityAttributeHandle(), System.Reflection.Metadata.DeclarativeSecurityAttributeHandle.operator DeclarativeSecurityAttributeHandle(), System.Reflection.Metadata.DocumentHandle.operator DocumentHandle(), System.Reflection.Metadata.DocumentHandle.operator DocumentHandle(), System.Reflection.Metadata.DocumentNameBlobHandle.operator DocumentNameBlobHandle(), System.Reflection.Metadata.EntityHandle.operator EntityHandle(), System.Reflection.Metadata.EventDefinitionHandle.operator EventDefinitionHandle(), System.Reflection.Metadata.EventDefinitionHandle.operator EventDefinitionHandle(), System.Reflection.Metadata.ExportedTypeHandle.operator ExportedTypeHandle(), System.Reflection.Metadata.ExportedTypeHandle.operator ExportedTypeHandle(), System.Reflection.Metadata.FieldDefinitionHandle.operator FieldDefinitionHandle(), System.Reflection.Metadata.FieldDefinitionHandle.operator FieldDefinitionHandle(), System.Reflection.Metadata.GenericParameterConstraintHandle.operator GenericParameterConstraintHandle(), System.Reflection.Metadata.GenericParameterConstraintHandle.operator GenericParameterConstraintHandle(), System.Reflection.Metadata.GenericParameterHandle.operator GenericParameterHandle(), System.Reflection.Metadata.GenericParameterHandle.operator GenericParameterHandle(), System.Reflection.Metadata.GuidHandle.operator GuidHandle(), System.Reflection.Metadata.ImportScopeHandle.operator ImportScopeHandle(), System.Reflection.Metadata.ImportScopeHandle.operator ImportScopeHandle(), System.Reflection.Metadata.InterfaceImplementationHandle.operator InterfaceImplementationHandle(), System.Reflection.Metadata.InterfaceImplementationHandle.operator InterfaceImplementationHandle(), System.Reflection.Metadata.LocalConstantHandle.operator LocalConstantHandle(), System.Reflection.Metadata.LocalConstantHandle.operator LocalConstantHandle(), System.Reflection.Metadata.LocalScopeHandle.operator LocalScopeHandle(), System.Reflection.Metadata.LocalScopeHandle.operator LocalScopeHandle(), System.Reflection.Metadata.LocalVariableHandle.operator LocalVariableHandle(), System.Reflection.Metadata.LocalVariableHandle.operator LocalVariableHandle(), System.Reflection.Metadata.ManifestResourceHandle.operator ManifestResourceHandle(), System.Reflection.Metadata.ManifestResourceHandle.operator ManifestResourceHandle(), System.Reflection.Metadata.MemberReferenceHandle.operator MemberReferenceHandle(), System.Reflection.Metadata.MemberReferenceHandle.operator MemberReferenceHandle(), System.Reflection.Metadata.MethodDebugInformationHandle.operator MethodDebugInformationHandle(), System.Reflection.Metadata.MethodDebugInformationHandle.operator MethodDebugInformationHandle(), System.Reflection.Metadata.MethodDefinitionHandle.operator MethodDefinitionHandle(), System.Reflection.Metadata.MethodDefinitionHandle.operator MethodDefinitionHandle(), System.Reflection.Metadata.MethodImplementationHandle.operator MethodImplementationHandle(), System.Reflection.Metadata.MethodImplementationHandle.operator MethodImplementationHandle(), System.Reflection.Metadata.MethodSpecificationHandle.operator MethodSpecificationHandle(), System.Reflection.Metadata.MethodSpecificationHandle.operator MethodSpecificationHandle(), System.Reflection.Metadata.ModuleDefinitionHandle.operator ModuleDefinitionHandle(), System.Reflection.Metadata.ModuleDefinitionHandle.operator ModuleDefinitionHandle(), System.Reflection.Metadata.ModuleReferenceHandle.operator ModuleReferenceHandle(), System.Reflection.Metadata.ModuleReferenceHandle.operator ModuleReferenceHandle(), System.Reflection.Metadata.NamespaceDefinitionHandle.operator NamespaceDefinitionHandle(), System.Reflection.Metadata.ParameterHandle.operator ParameterHandle(), System.Reflection.Metadata.ParameterHandle.operator ParameterHandle(), System.Reflection.Metadata.PropertyDefinitionHandle.operator PropertyDefinitionHandle(), System.Reflection.Metadata.PropertyDefinitionHandle.operator PropertyDefinitionHandle(), System.Reflection.Metadata.StandaloneSignatureHandle.operator StandaloneSignatureHandle(), System.Reflection.Metadata.StandaloneSignatureHandle.operator StandaloneSignatureHandle(), System.Reflection.Metadata.StringHandle.operator StringHandle(), System.Reflection.Metadata.TypeDefinitionHandle.operator TypeDefinitionHandle(), System.Reflection.Metadata.TypeDefinitionHandle.operator TypeDefinitionHandle(), System.Reflection.Metadata.TypeReferenceHandle.operator TypeReferenceHandle(), System.Reflection.Metadata.TypeReferenceHandle.operator TypeReferenceHandle(), System.Reflection.Metadata.TypeSpecificationHandle.operator TypeSpecificationHandle(), System.Reflection.Metadata.TypeSpecificationHandle.operator TypeSpecificationHandle(), and System.Reflection.Metadata.UserStringHandle.operator UserStringHandle().