Terraria: System.Reflection.Throw.InvalidCodedIndex
InvalidCodedIndex()
static void System.Reflection.Throw.InvalidCodedIndex () inline static package
Definition at line 201 of file Throw.cs.
    {
        throw new BadImageFormatException(System.SR.InvalidCodedIndex);
    }
References System.SR.InvalidCodedIndex.
Referenced by System.Reflection.Metadata.Ecma335.CustomAttributeTypeTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.HasConstantTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.HasCustomAttributeTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.HasDeclSecurityTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.HasFieldMarshalTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.HasSemanticsTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.ImplementationTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.MemberForwardedTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.MemberRefParentTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.MethodDefOrRefTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.ResolutionScopeTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.HasCustomDebugInformationTag.ConvertToHandle(), System.Reflection.Metadata.Ecma335.TypeDefOrRefTag.ConvertToHandle(), and System.Reflection.Metadata.Ecma335.TypeOrMethodDefTag.ConvertToHandle().