Terraria: System.Text.Json.JsonPropertyDictionary.Clear
Clear()
void System.Text.Json.JsonPropertyDictionary< T >.Clear () inline
Definition at line 219 of file JsonPropertyDictionary.cs.
    {
        if (IsReadOnly)
        {
            ThrowHelper.ThrowNotSupportedException_NodeCollectionIsReadOnly();
        }
        _propertyList.Clear();
        _propertyDictionary?.Clear();
    }
References System.Text.Json.JsonPropertyDictionary< T >._propertyDictionary, System.Text.Json.JsonPropertyDictionary< T >._propertyList, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.List< T >.Clear(), System.Text.Json.JsonPropertyDictionary< T >.IsReadOnly, and System.Text.Json.ThrowHelper.ThrowNotSupportedException_NodeCollectionIsReadOnly().