Terraria: System.Text.Json.JsonPropertyDictionary.ContainsProperty
ContainsProperty()
bool System.Text.Json.JsonPropertyDictionary< T >.ContainsProperty (string propertyName) inline private
Definition at line 420 of file JsonPropertyDictionary.cs.
    {
        if (_propertyDictionary != null)
        {
            return _propertyDictionary.ContainsKey(propertyName);
        }
        foreach (KeyValuePair<string, T> property in _propertyList)
        {
            if (_stringComparer.Equals(propertyName, property.Key))
            {
                return true;
            }
        }
        return false;
    }
References System.Text.Json.JsonPropertyDictionary< T >._propertyDictionary, System.Text.Json.JsonPropertyDictionary< T >._propertyList, System.Text.Json.JsonPropertyDictionary< T >._stringComparer, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), and System.StringComparer.Equals().
Referenced by System.Text.Json.JsonPropertyDictionary< T >.ContainsKey(), and System.Text.Json.JsonPropertyDictionary< T >.TryAddValue().