Terraria: System.Text.Json.JsonPropertyDictionary.TryAddValue
TryAddValue()
bool System.Text.Json.JsonPropertyDictionary< T >.TryAddValue (string propertyName, T value) inline private
Definition at line 362 of file JsonPropertyDictionary.cs.
    {
        if (IsReadOnly)
        {
            ThrowHelper.ThrowNotSupportedException_NodeCollectionIsReadOnly();
        }
        CreateDictionaryIfThresholdMet();
        if (_propertyDictionary == null)
        {
            if (ContainsProperty(propertyName))
            {
                return false;
            }
        }
        else if (!_propertyDictionary.TryAdd(in propertyName, in value))
        {
            return false;
        }
        _propertyList.Add(new KeyValuePair<string, T>(propertyName, value));
        return true;
    }
References System.Text.Json.JsonPropertyDictionary< T >._propertyDictionary, System.Text.Json.JsonPropertyDictionary< T >._propertyList, System.Collections.Generic.List< T >.Add(), System.Text.Json.JsonPropertyDictionary< T >.ContainsProperty(), System.Text.Json.JsonPropertyDictionary< T >.CreateDictionaryIfThresholdMet(), System.Text.Json.JsonPropertyDictionary< T >.IsReadOnly, System.Text.Json.ThrowHelper.ThrowNotSupportedException_NodeCollectionIsReadOnly(), System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd(), and System.value.
Referenced by System.Text.Json.JsonPropertyDictionary< T >.AddValue(), and System.Text.Json.JsonPropertyDictionary< T >.TryAdd().