Terraria: System.Text.Json.JsonPropertyDictionary.SetValue
SetValue()
T System.Text.Json.JsonPropertyDictionary< T >.SetValue (string propertyName, T value, Action assignParent = null) inline
Definition at line 300 of file JsonPropertyDictionary.cs.
    {
        if (IsReadOnly)
        {
            ThrowHelper.ThrowNotSupportedException_NodeCollectionIsReadOnly();
        }
        if (propertyName == null)
        {
            throw new ArgumentNullException("propertyName");
        }
        CreateDictionaryIfThresholdMet();
        T val = null;
        if (_propertyDictionary != null)
        {
            if (_propertyDictionary.TryAdd(in propertyName, in value))
            {
                assignParent?.Invoke();
                _propertyList.Add(new KeyValuePair<string, T>(propertyName, value));
                return null;
            }
            val = _propertyDictionary[propertyName];
            if (val == value)
            {
                return null;
            }
        }
        int num = FindValueIndex(propertyName);
        if (num >= 0)
        {
            if (_propertyDictionary != null)
            {
                _propertyDictionary[propertyName] = value;
            }
            else
            {
                KeyValuePair<string, T> keyValuePair = _propertyList[num];
                if (keyValuePair.Value == value)
                {
                    return null;
                }
                val = keyValuePair.Value;
            }
            assignParent?.Invoke();
            _propertyList[num] = new KeyValuePair<string, T>(propertyName, value);
        }
        else
        {
            assignParent?.Invoke();
            _propertyDictionary?.Add(propertyName, value);
            _propertyList.Add(new KeyValuePair<string, T>(propertyName, value));
        }
        return val;
    }
References System.Text.Json.JsonPropertyDictionary< T >._propertyDictionary, System.Text.Json.JsonPropertyDictionary< T >._propertyList, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Text.Json.JsonPropertyDictionary< T >.CreateDictionaryIfThresholdMet(), System.Text.Json.Dictionary, System.Text.Json.JsonPropertyDictionary< T >.FindValueIndex(), System.Text.Json.JsonPropertyDictionary< T >.IsReadOnly, System.Text.Json.ThrowHelper.ThrowNotSupportedException_NodeCollectionIsReadOnly(), System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd(), and System.value.