Terraria: Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyle
RandomizeTreeStyle()
void Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyle (UnifiedRandom rand, int areaId) inline
Definition at line 145 of file TreeTopsInfo.cs.
    {
        int num = _variations[areaId];
        bool flag = false;
        while (_variations[areaId] == num)
        {
            switch (areaId)
            {
            case 0:
            case 1:
            case 2:
            case 3:
                _variations[areaId] = rand.Next(6);
                break;
            case 4:
                _variations[areaId] = rand.Next(5);
                break;
            case 5:
                _variations[areaId] = rand.Next(6);
                break;
            case 6:
                _variations[areaId] = rand.NextFromList<int>(0, 1, 2, 21, 22, 3, 31, 32, 4, 41, 42, 5, 6, 7);
                break;
            case 7:
                _variations[areaId] = rand.Next(5);
                break;
            case 8:
                _variations[areaId] = rand.Next(6);
                break;
            case 9:
                _variations[areaId] = rand.Next(5);
                break;
            case 10:
                _variations[areaId] = rand.Next(6);
                break;
            case 11:
                _variations[areaId] = rand.Next(4);
                break;
            case 12:
                _variations[areaId] = rand.Next(6);
                break;
            default:
                flag = true;
                break;
            }
            if (flag)
            {
                break;
            }
        }
        if (num != _variations[areaId])
        {
            if (Main.netMode == 2)
            {
                NetMessage.SendData(7);
            }
            else
            {
                DoTreeFX(areaId);
            }
        }
    }
References Terraria.GameContent.TreeTopsInfo._variations, Terraria.GameContent.TreeTopsInfo.DoTreeFX(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), and Terraria.NetMessage.SendData().
Referenced by Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition().