Terraria: SteamP2PWriter.ClearUser
ClearUser()
void SteamP2PWriter.ClearUser (CSteamID user) inline
     {
         //IL_0017: Unknown result type (might be due to invalid IL or missing references)
         //IL_0053: Unknown result type (might be due to invalid IL or missing references)
         //IL_0025: Unknown result type (might be due to invalid IL or missing references)
         //IL_0061: Unknown result type (might be due to invalid IL or missing references)
         lock (_lock)
         {
             if (_pendingSendData.ContainsKey(user))
             {
                 Queue<WriteInformation> queue = _pendingSendData[user];
                 while (queue.Count > 0)
                 {
                     _bufferPool.Enqueue(queue.Dequeue().Data);
                 }
             }
             if (_pendingSendDataSwap.ContainsKey(user))
             {
                 Queue<WriteInformation> queue2 = _pendingSendDataSwap[user];
                 while (queue2.Count > 0)
                 {
                     _bufferPool.Enqueue(queue2.Dequeue().Data);
                 }
             }
         }
     }
References _bufferPool, _lock, _pendingSendData, and _pendingSendDataSwap.
Referenced by NetClientSocialModule.Close(), NetServerSocialModule.Close(), and NetServerSocialModule.CloseAndUpdateUserState().