Terraria: UICreativeItemsInfiniteFilteringOptions.AddOnHover
AddOnHover()
void UICreativeItemsInfiniteFilteringOptions.AddOnHover (IItemEntryFilter filter, UIElement button, int indexOfFilter) inline private
     {
         button.OnUpdate += delegate(UIElement element)
         {
             ShowButtonName(element, filter, indexOfFilter);
         };
         button.OnUpdate += delegate
         {
             UpdateVisuals(button as UIImageFramed, indexOfFilter);
         };
     }
References UIElement.OnUpdate, ShowButtonName(), and UpdateVisuals().
Referenced by UICreativeItemsInfiniteFilteringOptions().