Terraria: UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions
UICreativeItemsInfiniteFilteringOptions()
UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions (EntryFilterer< Item, IItemEntryFilter > filterer, string snapPointsName) inline
     {
         _filterer = filterer;
         int num = 40;
         int count = _filterer.AvailableFilters.Count;
         int num2 = num * count;
         Height = new StyleDimension(num, 0f);
         Width = new StyleDimension(num2, 0f);
         Top = new StyleDimension(4f, 0f);
         SetPadding(0f);
         Asset<Texture2D> val = Main.Assets.Request<Texture2D>("Images/UI/Creative/Infinite_Tabs_B", (AssetRequestMode)1);
         for (int i = 0; i < _filterer.AvailableFilters.Count; i++)
         {
             IItemEntryFilter itemEntryFilter = _filterer.AvailableFilters[i];
             val.Frame(2, 4).OffsetSize(-2, -2);
             UIImageFramed uIImageFramed = new UIImageFramed(val, val.Frame(2, 4).OffsetSize(-2, -2));
             uIImageFramed.Left.Set(num * i, 0f);
             uIImageFramed.OnLeftClick += singleFilterButtonClick;
             uIImageFramed.OnMouseOver += button_OnMouseOver;
             uIImageFramed.SetPadding(0f);
             uIImageFramed.SetSnapPoint(snapPointsName, i);
             AddOnHover(itemEntryFilter, uIImageFramed, i);
             UIElement image = itemEntryFilter.GetImage();
             image.IgnoresMouseInteraction = true;
             image.Left = new StyleDimension(6f, 0f);
             image.HAlign = 0f;
             uIImageFramed.Append(image);
             _filtersByButtons[uIImageFramed] = itemEntryFilter;
             _iconsByButtons[uIImageFramed] = image;
             Append(uIImageFramed);
             UpdateVisuals(uIImageFramed, i);
         }
     }
References _filterer, _filtersByButtons, _iconsByButtons, AddOnHover(), UIElement.Append(), Main.Assets, EntryFilterer< T, U >.AvailableFilters, button_OnMouseOver(), IEntryFilter< T >.GetImage(), UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, UIElement.Left, UIElement.OnLeftClick, UIElement.OnMouseOver, StyleDimension.Set(), UIElement.SetPadding(), UIElement.SetSnapPoint(), singleFilterButtonClick(), UIElement.Top, UpdateVisuals(), and UIElement.Width.