Terraria: System.Text.RegularExpressions.RegexCompiler.GenerateOneCode
GenerateOneCode()
void System.Text.RegularExpressions.RegexCompiler.GenerateOneCode () inline private inherited
Definition at line 2692 of file RegexCompiler.cs.
    {
        if (_hasTimeout)
        {
            Ldthis();
            Call(s_checkTimeoutMethod);
        }
        switch (_regexopcode)
        {
        case 40:
            Mvlocfld(_runtextposLocal, s_runtextposField);
            Ret();
            break;
        case 22:
            Back();
            break;
        case 46:
            Ldloc(_runtrackLocal);
            Dup();
            Ldlen();
            Ldc(1);
            Sub();
            Ldloc(_runtextposLocal);
            StelemI4();
            break;
        case 38:
            Goto(Operand(0));
            break;
        case 37:
            Ldthis();
            Ldc(Operand(0));
            Call(s_isMatchedMethod);
            BrfalseFar(_backtrack);
            break;
        case 23:
            PushTrack(_runtextposLocal);
            Track();
            break;
        case 151:
            PopTrack();
            Stloc(_runtextposLocal);
            Goto(Operand(0));
            break;
        case 30:
            ReadyPushStack();
            Ldc(-1);
            DoPush();
            TrackUnique(0);
            break;
        case 31:
            PushStack(_runtextposLocal);
            TrackUnique(0);
            break;
        case 158:
        case 159:
            PopDiscardStack();
            Back();
            break;
        case 33:
            ReadyPushTrack();
            PopStack();
            Stloc(_runtextposLocal);
            Ldloc(_runtextposLocal);
            DoPush();
            Track();
            break;
        case 161:
            ReadyPushStack();
            PopTrack();
            DoPush();
            Back();
            break;
        case 32:
        {
            if (Operand(1) != -1)
            {
                Ldthis();
                Ldc(Operand(1));
                Call(s_isMatchedMethod);
                BrfalseFar(_backtrack);
            }
            using (RentedLocalBuilder rentedLocalBuilder20 = RentInt32Local())
            {
                PopStack();
                Stloc(rentedLocalBuilder20);
                if (Operand(1) != -1)
                {
                    Ldthis();
                    Ldc(Operand(0));
                    Ldc(Operand(1));
                    Ldloc(rentedLocalBuilder20);
                    Ldloc(_runtextposLocal);
                    Call(s_transferCaptureMethod);
                }
                else
                {
                    Ldthis();
                    Ldc(Operand(0));
                    Ldloc(rentedLocalBuilder20);
                    Ldloc(_runtextposLocal);
                    Call(s_captureMethod);
                }
                PushTrack(rentedLocalBuilder20);
            }
            TrackUnique((Operand(0) != -1 && Operand(1) != -1) ? 4 : 3);
            break;
        }
        case 160:
            ReadyPushStack();
            PopTrack();
            DoPush();
            Ldthis();
            Call(s_uncaptureMethod);
            if (Operand(0) != -1 && Operand(1) != -1)
            {
                Ldthis();
                Call(s_uncaptureMethod);
            }
            Back();
            break;
        case 24:
        {
            Label l19 = DefineLabel();
            PopStack();
            using (RentedLocalBuilder rentedLocalBuilder18 = RentInt32Local())
            {
                Stloc(rentedLocalBuilder18);
                PushTrack(rentedLocalBuilder18);
                Ldloc(rentedLocalBuilder18);
            }
            Ldloc(_runtextposLocal);
            Beq(l19);
            PushTrack(_runtextposLocal);
            PushStack(_runtextposLocal);
            Track();
            Goto(Operand(0));
            MarkLabel(l19);
            TrackUnique2(5);
            break;
        }
        case 152:
            PopTrack();
            Stloc(_runtextposLocal);
            PopStack();
            Pop();
            TrackUnique2(5);
            Advance();
            break;
        case 280:
            ReadyPushStack();
            PopTrack();
            DoPush();
            Back();
            break;
        case 25:
        {
            using (RentedLocalBuilder rentedLocalBuilder17 = RentInt32Local())
            {
                PopStack();
                Stloc(rentedLocalBuilder17);
                Label l16 = DefineLabel();
                Label l17 = DefineLabel();
                Ldloc(rentedLocalBuilder17);
                Ldc(-1);
                Beq(l16);
                PushTrack(rentedLocalBuilder17);
                Br(l17);
                MarkLabel(l16);
                PushTrack(_runtextposLocal);
                MarkLabel(l17);
                Label l18 = DefineLabel();
                Ldloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder17);
                Beq(l18);
                PushTrack(_runtextposLocal);
                Track();
                Br(AdvanceLabel());
                MarkLabel(l18);
                ReadyPushStack();
                Ldloc(rentedLocalBuilder17);
            }
            DoPush();
            TrackUnique2(6);
            break;
        }
        case 153:
            PopTrack();
            Stloc(_runtextposLocal);
            PushStack(_runtextposLocal);
            TrackUnique2(6);
            Goto(Operand(0));
            break;
        case 281:
            ReadyReplaceStack(0);
            PopTrack();
            DoReplace();
            Back();
            break;
        case 26:
            ReadyPushStack();
            Ldc(-1);
            DoPush();
            ReadyPushStack();
            Ldc(Operand(0));
            DoPush();
            TrackUnique(1);
            break;
        case 27:
            PushStack(_runtextposLocal);
            ReadyPushStack();
            Ldc(Operand(0));
            DoPush();
            TrackUnique(1);
            break;
        case 154:
        case 155:
            PopDiscardStack(2);
            Back();
            break;
        case 28:
        {
            using (RentedLocalBuilder rentedLocalBuilder15 = RentInt32Local())
            {
                PopStack();
                Stloc(rentedLocalBuilder15);
                PopStack();
                using (RentedLocalBuilder rentedLocalBuilder16 = RentInt32Local())
                {
                    Stloc(rentedLocalBuilder16);
                    PushTrack(rentedLocalBuilder16);
                    Ldloc(rentedLocalBuilder16);
                }
                Label l14 = DefineLabel();
                Label l15 = DefineLabel();
                Ldloc(_runtextposLocal);
                Bne(l14);
                Ldloc(rentedLocalBuilder15);
                Ldc(0);
                Bge(l15);
                MarkLabel(l14);
                Ldloc(rentedLocalBuilder15);
                Ldc(Operand(1));
                Bge(l15);
                PushStack(_runtextposLocal);
                ReadyPushStack();
                Ldloc(rentedLocalBuilder15);
                Ldc(1);
                Add();
                DoPush();
                Track();
                Goto(Operand(0));
                MarkLabel(l15);
                PushTrack(rentedLocalBuilder15);
            }
            TrackUnique2(7);
            break;
        }
        case 156:
        {
            using (RentedLocalBuilder rentedLocalBuilder11 = RentInt32Local())
            {
                Label l12 = DefineLabel();
                PopStack();
                Ldc(1);
                Sub();
                Stloc(rentedLocalBuilder11);
                Ldloc(rentedLocalBuilder11);
                Ldc(0);
                Blt(l12);
                PopStack();
                Stloc(_runtextposLocal);
                PushTrack(rentedLocalBuilder11);
                TrackUnique2(7);
                Advance();
                MarkLabel(l12);
                ReadyReplaceStack(0);
                PopTrack();
                DoReplace();
                PushStack(rentedLocalBuilder11);
            }
            Back();
            break;
        }
        case 284:
        {
            PopTrack();
            using (RentedLocalBuilder rentedLocalBuilder12 = RentInt32Local())
            {
                Stloc(rentedLocalBuilder12);
                ReadyPushStack();
                PopTrack();
                DoPush();
                PushStack(rentedLocalBuilder12);
            }
            Back();
            break;
        }
        case 29:
        {
            PopStack();
            using (RentedLocalBuilder rentedLocalBuilder8 = RentInt32Local())
            {
                Stloc(rentedLocalBuilder8);
                PopStack();
                using (RentedLocalBuilder rentedLocalBuilder9 = RentInt32Local())
                {
                    Stloc(rentedLocalBuilder9);
                    Label l10 = DefineLabel();
                    Ldloc(rentedLocalBuilder8);
                    Ldc(0);
                    Bge(l10);
                    PushTrack(rentedLocalBuilder9);
                    PushStack(_runtextposLocal);
                    ReadyPushStack();
                    Ldloc(rentedLocalBuilder8);
                    Ldc(1);
                    Add();
                    DoPush();
                    TrackUnique2(8);
                    Goto(Operand(0));
                    MarkLabel(l10);
                    PushTrack(rentedLocalBuilder9);
                }
                PushTrack(rentedLocalBuilder8);
            }
            PushTrack(_runtextposLocal);
            Track();
            break;
        }
        case 157:
        {
            using (RentedLocalBuilder rentedLocalBuilder4 = RentInt32Local())
            {
                Label l4 = DefineLabel();
                PopTrack();
                Stloc(_runtextposLocal);
                PopTrack();
                Stloc(rentedLocalBuilder4);
                Ldloc(rentedLocalBuilder4);
                Ldc(Operand(1));
                Bge(l4);
                Ldloc(_runtextposLocal);
                TopTrack();
                Beq(l4);
                PushStack(_runtextposLocal);
                ReadyPushStack();
                Ldloc(rentedLocalBuilder4);
                Ldc(1);
                Add();
                DoPush();
                TrackUnique2(8);
                Goto(Operand(0));
                MarkLabel(l4);
                ReadyPushStack();
                PopTrack();
                DoPush();
                PushStack(rentedLocalBuilder4);
            }
            Back();
            break;
        }
        case 285:
            ReadyReplaceStack(1);
            PopTrack();
            DoReplace();
            ReadyReplaceStack(0);
            TopStack();
            Ldc(1);
            Sub();
            DoReplace();
            Back();
            break;
        case 34:
            ReadyPushStack();
            Ldthisfld(s_runtrackField);
            Ldlen();
            Ldloc(_runtrackposLocal);
            Sub();
            DoPush();
            ReadyPushStack();
            Ldthis();
            Call(s_crawlposMethod);
            DoPush();
            TrackUnique(1);
            break;
        case 162:
            PopDiscardStack(2);
            Back();
            break;
        case 35:
        {
            Label l = DefineLabel();
            Label l2 = DefineLabel();
            using (RentedLocalBuilder rentedLocalBuilder2 = RentInt32Local())
            {
                PopStack();
                Stloc(rentedLocalBuilder2);
                Ldthisfld(s_runtrackField);
                Ldlen();
                PopStack();
                Sub();
                Stloc(_runtrackposLocal);
                MarkLabel(l);
                Ldthis();
                Call(s_crawlposMethod);
                Ldloc(rentedLocalBuilder2);
                Beq(l2);
                Ldthis();
                Call(s_uncaptureMethod);
                Br(l);
            }
            MarkLabel(l2);
            Back();
            break;
        }
        case 36:
        {
            PopStack();
            using (RentedLocalBuilder rentedLocalBuilder21 = RentInt32Local())
            {
                Stloc(rentedLocalBuilder21);
                Ldthisfld(s_runtrackField);
                Ldlen();
                PopStack();
                Sub();
                Stloc(_runtrackposLocal);
                PushTrack(rentedLocalBuilder21);
            }
            TrackUnique(9);
            break;
        }
        case 164:
        {
            Label l22 = DefineLabel();
            Label l23 = DefineLabel();
            using (RentedLocalBuilder rentedLocalBuilder19 = RentInt32Local())
            {
                PopTrack();
                Stloc(rentedLocalBuilder19);
                MarkLabel(l22);
                Ldthis();
                Call(s_crawlposMethod);
                Ldloc(rentedLocalBuilder19);
                Beq(l23);
                Ldthis();
                Call(s_uncaptureMethod);
                Br(l22);
            }
            MarkLabel(l23);
            Back();
            break;
        }
        case 14:
        {
            Label l21 = _labels[NextCodepos()];
            Ldloc(_runtextposLocal);
            Ldloc(_runtextbegLocal);
            Ble(l21);
            Leftchar();
            Ldc(10);
            BneFar(_backtrack);
            break;
        }
        case 15:
        {
            Label l20 = _labels[NextCodepos()];
            Ldloc(_runtextposLocal);
            Ldloc(_runtextendLocal);
            Bge(l20);
            Rightchar();
            Ldc(10);
            BneFar(_backtrack);
            break;
        }
        case 16:
        case 17:
            Ldthis();
            Ldloc(_runtextposLocal);
            Ldloc(_runtextbegLocal);
            Ldloc(_runtextendLocal);
            Call(s_isBoundaryMethod);
            if (Code() == 16)
            {
                BrfalseFar(_backtrack);
            }
            else
            {
                BrtrueFar(_backtrack);
            }
            break;
        case 41:
        case 42:
            Ldthis();
            Ldloc(_runtextposLocal);
            Ldloc(_runtextbegLocal);
            Ldloc(_runtextendLocal);
            Call(s_isECMABoundaryMethod);
            if (Code() == 41)
            {
                BrfalseFar(_backtrack);
            }
            else
            {
                BrtrueFar(_backtrack);
            }
            break;
        case 18:
            Ldloc(_runtextposLocal);
            Ldloc(_runtextbegLocal);
            BgtFar(_backtrack);
            break;
        case 19:
            Ldloc(_runtextposLocal);
            Ldthisfld(s_runtextstartField);
            BneFar(_backtrack);
            break;
        case 20:
            Ldloc(_runtextposLocal);
            Ldloc(_runtextendLocal);
            Ldc(1);
            Sub();
            BltFar(_backtrack);
            Ldloc(_runtextposLocal);
            Ldloc(_runtextendLocal);
            Bge(_labels[NextCodepos()]);
            Rightchar();
            Ldc(10);
            BneFar(_backtrack);
            break;
        case 21:
            Ldloc(_runtextposLocal);
            Ldloc(_runtextendLocal);
            BltFar(_backtrack);
            break;
        case 9:
        case 10:
        case 11:
        case 73:
        case 74:
        case 75:
        case 521:
        case 522:
        case 523:
        case 585:
        case 586:
        case 587:
            Ldloc(_runtextposLocal);
            if (!IsRightToLeft())
            {
                Ldloc(_runtextendLocal);
                BgeFar(_backtrack);
                Rightcharnext();
            }
            else
            {
                Ldloc(_runtextbegLocal);
                BleFar(_backtrack);
                Leftcharnext();
            }
            if (Code() == 11)
            {
                EmitMatchCharacterClass(_strings[Operand(0)], IsCaseInsensitive());
                BrfalseFar(_backtrack);
                break;
            }
            if (IsCaseInsensitive() && ParticipatesInCaseConversion(Operand(0)))
            {
                CallToLower();
            }
            Ldc(Operand(0));
            if (Code() == 9)
            {
                BneFar(_backtrack);
            }
            else
            {
                BeqFar(_backtrack);
            }
            break;
        case 12:
        case 524:
        {
            string text3 = _strings[Operand(0)];
            Ldc(text3.Length);
            Ldloc(_runtextendLocal);
            Ldloc(_runtextposLocal);
            Sub();
            BgtFar(_backtrack);
            for (int i = 0; i < text3.Length; i++)
            {
                Ldloc(_runtextLocal);
                Ldloc(_runtextposLocal);
                if (i != 0)
                {
                    Ldc(i);
                    Add();
                }
                Call(s_stringGetCharsMethod);
                if (IsCaseInsensitive() && ParticipatesInCaseConversion(text3[i]))
                {
                    CallToLower();
                }
                Ldc(text3[i]);
                BneFar(_backtrack);
            }
            Ldloc(_runtextposLocal);
            Ldc(text3.Length);
            Add();
            Stloc(_runtextposLocal);
            break;
        }
        case 76:
        case 588:
        {
            string text2 = _strings[Operand(0)];
            Ldc(text2.Length);
            Ldloc(_runtextposLocal);
            Ldloc(_runtextbegLocal);
            Sub();
            BgtFar(_backtrack);
            int num4 = text2.Length;
            while (num4 > 0)
            {
                num4--;
                Ldloc(_runtextLocal);
                Ldloc(_runtextposLocal);
                Ldc(text2.Length - num4);
                Sub();
                Call(s_stringGetCharsMethod);
                if (IsCaseInsensitive() && ParticipatesInCaseConversion(text2[num4]))
                {
                    CallToLower();
                }
                Ldc(text2[num4]);
                BneFar(_backtrack);
            }
            Ldloc(_runtextposLocal);
            Ldc(text2.Length);
            Sub();
            Stloc(_runtextposLocal);
            break;
        }
        case 13:
        case 77:
        case 525:
        case 589:
        {
            using RentedLocalBuilder rentedLocalBuilder13 = RentInt32Local();
            using RentedLocalBuilder rentedLocalBuilder14 = RentInt32Local();
            Label l13 = DefineLabel();
            Ldthis();
            Ldc(Operand(0));
            Call(s_isMatchedMethod);
            if ((_options & RegexOptions.ECMAScript) != 0)
            {
                Brfalse(AdvanceLabel());
            }
            else
            {
                BrfalseFar(_backtrack);
            }
            Ldthis();
            Ldc(Operand(0));
            Call(s_matchLengthMethod);
            Stloc(rentedLocalBuilder13);
            Ldloc(rentedLocalBuilder13);
            if (!IsRightToLeft())
            {
                Ldloc(_runtextendLocal);
                Ldloc(_runtextposLocal);
            }
            else
            {
                Ldloc(_runtextposLocal);
                Ldloc(_runtextbegLocal);
            }
            Sub();
            BgtFar(_backtrack);
            Ldthis();
            Ldc(Operand(0));
            Call(s_matchIndexMethod);
            if (!IsRightToLeft())
            {
                Ldloc(rentedLocalBuilder13);
                Add(IsRightToLeft());
            }
            Stloc(rentedLocalBuilder14);
            Ldloc(_runtextposLocal);
            Ldloc(rentedLocalBuilder13);
            Add(IsRightToLeft());
            Stloc(_runtextposLocal);
            MarkLabel(l13);
            Ldloc(rentedLocalBuilder13);
            Ldc(0);
            Ble(AdvanceLabel());
            Ldloc(_runtextLocal);
            Ldloc(rentedLocalBuilder14);
            Ldloc(rentedLocalBuilder13);
            if (IsRightToLeft())
            {
                Ldc(1);
                Sub();
                Stloc(rentedLocalBuilder13);
                Ldloc(rentedLocalBuilder13);
            }
            Sub(IsRightToLeft());
            Call(s_stringGetCharsMethod);
            if (IsCaseInsensitive())
            {
                CallToLower();
            }
            Ldloc(_runtextLocal);
            Ldloc(_runtextposLocal);
            Ldloc(rentedLocalBuilder13);
            if (!IsRightToLeft())
            {
                Ldloc(rentedLocalBuilder13);
                Ldc(1);
                Sub();
                Stloc(rentedLocalBuilder13);
            }
            Sub(IsRightToLeft());
            Call(s_stringGetCharsMethod);
            if (IsCaseInsensitive())
            {
                CallToLower();
            }
            Beq(l13);
            Back();
            break;
        }
        case 0:
        case 1:
        case 2:
        case 64:
        case 65:
        case 66:
        case 512:
        case 513:
        case 514:
        case 576:
        case 577:
        case 578:
        {
            int num3 = Operand(1);
            if (num3 == 0)
            {
                break;
            }
            Ldc(num3);
            if (!IsRightToLeft())
            {
                Ldloc(_runtextendLocal);
                Ldloc(_runtextposLocal);
            }
            else
            {
                Ldloc(_runtextposLocal);
                Ldloc(_runtextbegLocal);
            }
            Sub();
            BgtFar(_backtrack);
            Ldloc(_runtextposLocal);
            Ldc(num3);
            Add(IsRightToLeft());
            Stloc(_runtextposLocal);
            using RentedLocalBuilder rentedLocalBuilder10 = RentInt32Local();
            Label l11 = DefineLabel();
            Ldc(num3);
            Stloc(rentedLocalBuilder10);
            MarkLabel(l11);
            Ldloc(_runtextLocal);
            Ldloc(_runtextposLocal);
            Ldloc(rentedLocalBuilder10);
            if (IsRightToLeft())
            {
                Ldc(1);
                Sub();
                Stloc(rentedLocalBuilder10);
                Ldloc(rentedLocalBuilder10);
                Add();
            }
            else
            {
                Ldloc(rentedLocalBuilder10);
                Ldc(1);
                Sub();
                Stloc(rentedLocalBuilder10);
                Sub();
            }
            Call(s_stringGetCharsMethod);
            if (Code() == 2)
            {
                EmitTimeoutCheck();
                EmitMatchCharacterClass(_strings[Operand(0)], IsCaseInsensitive());
                BrfalseFar(_backtrack);
            }
            else
            {
                if (IsCaseInsensitive() && ParticipatesInCaseConversion(Operand(0)))
                {
                    CallToLower();
                }
                Ldc(Operand(0));
                if (Code() == 0)
                {
                    BneFar(_backtrack);
                }
                else
                {
                    BeqFar(_backtrack);
                }
            }
            Ldloc(rentedLocalBuilder10);
            Ldc(0);
            if (Code() == 2)
            {
                BgtFar(l11);
            }
            else
            {
                Bgt(l11);
            }
            break;
        }
        case 3:
        case 4:
        case 5:
        case 43:
        case 44:
        case 45:
        case 67:
        case 68:
        case 69:
        case 107:
        case 108:
        case 109:
        case 515:
        case 516:
        case 517:
        case 555:
        case 556:
        case 557:
        case 579:
        case 580:
        case 581:
        case 619:
        case 620:
        case 621:
        {
            int num2 = Operand(1);
            if (num2 == 0)
            {
                break;
            }
            using RentedLocalBuilder rentedLocalBuilder6 = RentInt32Local();
            using RentedLocalBuilder rentedLocalBuilder7 = RentInt32Local();
            if (!IsRightToLeft())
            {
                Ldloc(_runtextendLocal);
                Ldloc(_runtextposLocal);
            }
            else
            {
                Ldloc(_runtextposLocal);
                Ldloc(_runtextbegLocal);
            }
            Sub();
            Stloc(rentedLocalBuilder6);
            if (num2 != int.MaxValue)
            {
                Label l5 = DefineLabel();
                Ldloc(rentedLocalBuilder6);
                Ldc(num2);
                Blt(l5);
                Ldc(num2);
                Stloc(rentedLocalBuilder6);
                MarkLabel(l5);
            }
            Label l6 = DefineLabel();
            string text = ((Code() == 5 || Code() == 45) ? _strings[Operand(0)] : null);
            Span<char> chars = stackalloc char[3];
            int setChars;
            if ((Code() == 4 || Code() == 44) && !IsRightToLeft() && (!IsCaseInsensitive() || !ParticipatesInCaseConversion(Operand(0))))
            {
                Ldloc(_runtextLocal);
                Ldloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder6);
                Call(s_stringAsSpanIntIntMethod);
                Ldc(Operand(0));
                Call(s_spanIndexOf);
                Stloc(rentedLocalBuilder7);
                Label l7 = DefineLabel();
                Ldloc(rentedLocalBuilder7);
                Ldc(-1);
                Bne(l7);
                Ldloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder6);
                Add();
                Stloc(_runtextposLocal);
                Ldc(0);
                Stloc(rentedLocalBuilder7);
                BrFar(l6);
                MarkLabel(l7);
                Ldloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder7);
                Add();
                Stloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder6);
                Ldloc(rentedLocalBuilder7);
                Sub();
                Stloc(rentedLocalBuilder7);
                BrFar(l6);
            }
            else if ((Code() == 5 || Code() == 45) && !IsRightToLeft() && !IsCaseInsensitive() && (setChars = RegexCharClass.GetSetChars(text, chars)) > 1 && RegexCharClass.IsNegated(text))
            {
                Ldloc(_runtextLocal);
                Ldloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder6);
                Call(s_stringAsSpanIntIntMethod);
                Ldc(chars[0]);
                Ldc(chars[1]);
                if (setChars == 2)
                {
                    Call(s_spanIndexOfAnyCharChar);
                }
                else
                {
                    Ldc(chars[2]);
                    Call(s_spanIndexOfAnyCharCharChar);
                }
                Stloc(rentedLocalBuilder7);
                Label l8 = DefineLabel();
                Ldloc(rentedLocalBuilder7);
                Ldc(-1);
                Bne(l8);
                Ldloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder6);
                Add();
                Stloc(_runtextposLocal);
                Ldc(0);
                Stloc(rentedLocalBuilder7);
                BrFar(l6);
                MarkLabel(l8);
                Ldloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder7);
                Add();
                Stloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder6);
                Ldloc(rentedLocalBuilder7);
                Sub();
                Stloc(rentedLocalBuilder7);
                BrFar(l6);
            }
            else if ((Code() == 5 || Code() == 45) && !IsRightToLeft() && text == "\0\u0001\0\0")
            {
                Ldloc(_runtextposLocal);
                Ldloc(rentedLocalBuilder6);
                Add();
                Stloc(_runtextposLocal);
                Ldc(0);
                Stloc(rentedLocalBuilder7);
                BrFar(l6);
            }
            else
            {
                Ldloc(rentedLocalBuilder6);
                Ldc(1);
                Add();
                Stloc(rentedLocalBuilder7);
                Label l9 = DefineLabel();
                MarkLabel(l9);
                Ldloc(rentedLocalBuilder7);
                Ldc(1);
                Sub();
                Stloc(rentedLocalBuilder7);
                Ldloc(rentedLocalBuilder7);
                Ldc(0);
                if (Code() == 5 || Code() == 45)
                {
                    BleFar(l6);
                }
                else
                {
                    Ble(l6);
                }
                if (IsRightToLeft())
                {
                    Leftcharnext();
                }
                else
                {
                    Rightcharnext();
                }
                if (Code() == 5 || Code() == 45)
                {
                    EmitTimeoutCheck();
                    EmitMatchCharacterClass(_strings[Operand(0)], IsCaseInsensitive());
                    BrtrueFar(l9);
                }
                else
                {
                    if (IsCaseInsensitive() && ParticipatesInCaseConversion(Operand(0)))
                    {
                        CallToLower();
                    }
                    Ldc(Operand(0));
                    if (Code() == 3 || Code() == 43)
                    {
                        Beq(l9);
                    }
                    else
                    {
                        Bne(l9);
                    }
                }
                Ldloc(_runtextposLocal);
                Ldc(1);
                Sub(IsRightToLeft());
                Stloc(_runtextposLocal);
            }
            MarkLabel(l6);
            if (Code() != 43 && Code() != 44 && Code() != 45)
            {
                Ldloc(rentedLocalBuilder6);
                Ldloc(rentedLocalBuilder7);
                Ble(AdvanceLabel());
                ReadyPushTrack();
                Ldloc(rentedLocalBuilder6);
                Ldloc(rentedLocalBuilder7);
                Sub();
                Ldc(1);
                Sub();
                DoPush();
                ReadyPushTrack();
                Ldloc(_runtextposLocal);
                Ldc(1);
                Sub(IsRightToLeft());
                DoPush();
                Track();
            }
            break;
        }
        case 131:
        case 132:
        case 133:
        case 195:
        case 196:
        case 197:
        case 643:
        case 644:
        case 645:
        case 707:
        case 708:
        case 709:
        {
            PopTrack();
            Stloc(_runtextposLocal);
            PopTrack();
            using (RentedLocalBuilder rentedLocalBuilder5 = RentInt32Local())
            {
                Stloc(rentedLocalBuilder5);
                Ldloc(rentedLocalBuilder5);
                Ldc(0);
                BleFar(AdvanceLabel());
                ReadyPushTrack();
                Ldloc(rentedLocalBuilder5);
            }
            Ldc(1);
            Sub();
            DoPush();
            ReadyPushTrack();
            Ldloc(_runtextposLocal);
            Ldc(1);
            Sub(IsRightToLeft());
            DoPush();
            Trackagain();
            Advance();
            break;
        }
        case 6:
        case 7:
        case 8:
        case 70:
        case 71:
        case 72:
        case 518:
        case 519:
        case 520:
        case 582:
        case 583:
        case 584:
        {
            int num = Operand(1);
            if (num == 0)
            {
                break;
            }
            if (!IsRightToLeft())
            {
                Ldloc(_runtextendLocal);
                Ldloc(_runtextposLocal);
            }
            else
            {
                Ldloc(_runtextposLocal);
                Ldloc(_runtextbegLocal);
            }
            Sub();
            using (RentedLocalBuilder rentedLocalBuilder3 = RentInt32Local())
            {
                Stloc(rentedLocalBuilder3);
                if (num != int.MaxValue)
                {
                    Label l3 = DefineLabel();
                    Ldloc(rentedLocalBuilder3);
                    Ldc(num);
                    Blt(l3);
                    Ldc(num);
                    Stloc(rentedLocalBuilder3);
                    MarkLabel(l3);
                }
                Ldloc(rentedLocalBuilder3);
                Ldc(0);
                Ble(AdvanceLabel());
                ReadyPushTrack();
                Ldloc(rentedLocalBuilder3);
            }
            Ldc(1);
            Sub();
            DoPush();
            PushTrack(_runtextposLocal);
            Track();
            break;
        }
        case 134:
        case 135:
        case 136:
        case 198:
        case 199:
        case 200:
        case 646:
        case 647:
        case 648:
        case 710:
        case 711:
        case 712:
        {
            PopTrack();
            Stloc(_runtextposLocal);
            PopTrack();
            using (RentedLocalBuilder rentedLocalBuilder = RentInt32Local())
            {
                Stloc(rentedLocalBuilder);
                if (!IsRightToLeft())
                {
                    Rightcharnext();
                }
                else
                {
                    Leftcharnext();
                }
                if (Code() == 8)
                {
                    EmitMatchCharacterClass(_strings[Operand(0)], IsCaseInsensitive());
                    BrfalseFar(_backtrack);
                }
                else
                {
                    if (IsCaseInsensitive() && ParticipatesInCaseConversion(Operand(0)))
                    {
                        CallToLower();
                    }
                    Ldc(Operand(0));
                    if (Code() == 6)
                    {
                        BneFar(_backtrack);
                    }
                    else
                    {
                        BeqFar(_backtrack);
                    }
                }
                Ldloc(rentedLocalBuilder);
                Ldc(0);
                BleFar(AdvanceLabel());
                ReadyPushTrack();
                Ldloc(rentedLocalBuilder);
            }
            Ldc(1);
            Sub();
            DoPush();
            PushTrack(_runtextposLocal);
            Trackagain();
            Advance();
            break;
        }
        }
    }
References System.Text.RegularExpressions.RegexCompiler._backtrack, System.Text.RegularExpressions.RegexCompiler._hasTimeout, System.Text.RegularExpressions.RegexCompiler._labels, System.Text.RegularExpressions.RegexCompiler._options, System.Text.RegularExpressions.RegexCompiler._regexopcode, System.Text.RegularExpressions.RegexCompiler._runtextbegLocal, System.Text.RegularExpressions.RegexCompiler._runtextendLocal, System.Text.RegularExpressions.RegexCompiler._runtextLocal, System.Text.RegularExpressions.RegexCompiler._runtextposLocal, System.Text.RegularExpressions.RegexCompiler._runtrackLocal, System.Text.RegularExpressions.RegexCompiler._runtrackposLocal, System.Text.RegularExpressions.RegexCompiler._strings, System.Text.RegularExpressions.RegexCompiler.Add(), System.Text.RegularExpressions.RegexCompiler.Advance(), System.Text.RegularExpressions.RegexCompiler.AdvanceLabel(), System.Text.RegularExpressions.RegexCompiler.Back(), System.Reflection.Emit.Beq, System.Text.RegularExpressions.RegexCompiler.BeqFar(), System.Reflection.Emit.Bge, System.Text.RegularExpressions.RegexCompiler.BgeFar(), System.Reflection.Emit.Bgt, System.Text.RegularExpressions.RegexCompiler.BgtFar(), System.Reflection.Emit.Ble, System.Text.RegularExpressions.RegexCompiler.BleFar(), System.Reflection.Emit.Blt, System.Text.RegularExpressions.RegexCompiler.BltFar(), System.Text.RegularExpressions.RegexCompiler.Bne(), System.Text.RegularExpressions.RegexCompiler.BneFar(), System.Reflection.Emit.Br, System.Reflection.Emit.Brfalse, System.Text.RegularExpressions.RegexCompiler.BrfalseFar(), System.Text.RegularExpressions.RegexCompiler.BrFar(), System.Text.RegularExpressions.RegexCompiler.BrtrueFar(), System.Reflection.Emit.Call, System.Text.RegularExpressions.RegexCompiler.CallToLower(), System.chars, System.Text.RegularExpressions.RegexCompiler.Code(), System.Text.RegularExpressions.RegexCompiler.DefineLabel(), System.Text.RegularExpressions.RegexCompiler.DoPush(), System.Text.RegularExpressions.RegexCompiler.DoReplace(), System.Text.RegularExpressions.RegexCompiler.Dup(), System.Text.RegularExpressions.RegexCompiler.EmitMatchCharacterClass(), System.Text.RegularExpressions.RegexCompiler.EmitTimeoutCheck(), System.Text.RegularExpressions.RegexCharClass.GetSetChars(), System.Text.RegularExpressions.RegexCompiler.Goto(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexCompiler.IsCaseInsensitive(), System.Text.RegularExpressions.RegexCharClass.IsNegated(), System.Text.RegularExpressions.RegexCompiler.IsRightToLeft(), System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Text.RegularExpressions.RegexCompiler.Ldlen(), System.Reflection.Emit.Ldloc, System.Text.RegularExpressions.RegexCompiler.Ldthis(), System.Text.RegularExpressions.RegexCompiler.Ldthisfld(), System.Text.RegularExpressions.RegexCompiler.Leftchar(), System.Text.RegularExpressions.RegexCompiler.Leftcharnext(), System.Text.RegularExpressions.RegexCompiler.MarkLabel(), System.Reflection.MaxValue, System.Text.RegularExpressions.RegexCompiler.Mvlocfld(), System.Text.RegularExpressions.RegexCompiler.NextCodepos(), System.Text.RegularExpressions.RegexCompiler.Operand(), System.Text.RegularExpressions.RegexCompiler.ParticipatesInCaseConversion(), System.Text.RegularExpressions.RegexCompiler.Pop(), System.Text.RegularExpressions.RegexCompiler.PopDiscardStack(), System.Text.RegularExpressions.RegexCompiler.PopStack(), System.Text.RegularExpressions.RegexCompiler.PopTrack(), System.Text.RegularExpressions.RegexCompiler.PushStack(), System.Text.RegularExpressions.RegexCompiler.PushTrack(), System.Text.RegularExpressions.RegexCompiler.ReadyPushStack(), System.Text.RegularExpressions.RegexCompiler.ReadyPushTrack(), System.Text.RegularExpressions.RegexCompiler.ReadyReplaceStack(), System.Text.RegularExpressions.RegexCompiler.RentInt32Local(), System.Text.RegularExpressions.RegexCompiler.Ret(), System.Text.RegularExpressions.RegexCompiler.Rightchar(), System.Text.RegularExpressions.RegexCompiler.Rightcharnext(), System.Text.RegularExpressions.RegexCompiler.s_captureMethod, System.Text.RegularExpressions.RegexCompiler.s_checkTimeoutMethod, System.Text.RegularExpressions.RegexCompiler.s_crawlposMethod, System.Text.RegularExpressions.RegexCompiler.s_isBoundaryMethod, System.Text.RegularExpressions.RegexCompiler.s_isECMABoundaryMethod, System.Text.RegularExpressions.RegexCompiler.s_isMatchedMethod, System.Text.RegularExpressions.RegexCompiler.s_matchIndexMethod, System.Text.RegularExpressions.RegexCompiler.s_matchLengthMethod, System.Text.RegularExpressions.RegexCompiler.s_runtextposField, System.Text.RegularExpressions.RegexCompiler.s_runtextstartField, System.Text.RegularExpressions.RegexCompiler.s_runtrackField, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOf, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOfAnyCharChar, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOfAnyCharCharChar, System.Text.RegularExpressions.RegexCompiler.s_stringAsSpanIntIntMethod, System.Text.RegularExpressions.RegexCompiler.s_stringGetCharsMethod, System.Text.RegularExpressions.RegexCompiler.s_transferCaptureMethod, System.Text.RegularExpressions.RegexCompiler.s_uncaptureMethod, System.Text.RegularExpressions.RegexCompiler.StelemI4(), System.Reflection.Emit.Stloc, System.Text.RegularExpressions.RegexCompiler.Sub(), System.text, System.Text.RegularExpressions.RegexCompiler.TopStack(), System.Text.RegularExpressions.RegexCompiler.TopTrack(), System.Text.RegularExpressions.RegexCompiler.Track(), System.Text.RegularExpressions.RegexCompiler.Trackagain(), System.Text.RegularExpressions.RegexCompiler.TrackUnique(), and System.Text.RegularExpressions.RegexCompiler.TrackUnique2().
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateBacktrackSection(), and System.Text.RegularExpressions.RegexCompiler.GenerateForwardSection().