Terraria: System.Text.RegularExpressions.RegexCompiler.RentInt32Local
RentInt32Local()
RentedLocalBuilder System.Text.RegularExpressions.RegexCompiler.RentInt32Local () inline private inherited
Definition at line 677 of file RegexCompiler.cs.
    {
        LocalBuilder result;
        return new RentedLocalBuilder(_int32LocalsPool ?? (_int32LocalsPool = new Stack<LocalBuilder>()), _int32LocalsPool.TryPop(out result) ? result : DeclareInt32());
    }
References System.Text.RegularExpressions.RegexCompiler._int32LocalsPool, System.Text.RegularExpressions.RegexCompiler.DeclareInt32(), and System.Collections.Generic.Stack< T >.TryPop().
Referenced by System.Text.RegularExpressions.RegexCompiler.CallToLower(), System.Text.RegularExpressions.RegexCompiler.EmitMatchCharacterClass(), System.Text.RegularExpressions.RegexCompiler.GenerateFindFirstChar(), System.Text.RegularExpressions.RegexCompiler.GenerateMiddleSection(), System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), System.Text.RegularExpressions.RegexCompiler.PopStack(), System.Text.RegularExpressions.RegexCompiler.PopTrack(), and System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo().