Terraria: System.Text.RegularExpressions.RegexCompiler.InitializeCultureForGoIfNecessary
InitializeCultureForGoIfNecessary()
void System.Text.RegularExpressions.RegexCompiler.InitializeCultureForGoIfNecessary () inline private inherited
Definition at line 2666 of file RegexCompiler.cs.
    {
        _textInfoLocal = null;
        if ((_options & RegexOptions.CultureInvariant) != 0)
        {
            return;
        }
        bool flag = (_options & RegexOptions.IgnoreCase) != 0;
        if (!flag)
        {
            for (int i = 0; i < _codes.Length; i += RegexCode.OpcodeSize(_codes[i]))
            {
                if ((_codes[i] & 0x200) == 512)
                {
                    flag = true;
                    break;
                }
            }
        }
        if (flag)
        {
            _textInfoLocal = DeclareTextInfo();
            InitLocalCultureInfo();
        }
    }
References System.Text.RegularExpressions.RegexCompiler._codes, System.Text.RegularExpressions.RegexCompiler._options, System.Text.RegularExpressions.RegexCompiler._textInfoLocal, System.Text.RegularExpressions.RegexCompiler.DeclareTextInfo(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexCompiler.InitLocalCultureInfo(), and System.Text.RegularExpressions.RegexCode.OpcodeSize().
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateGo(), and System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo().