Terraria: System.Text.RegularExpressions.RegexCompiler.DefineLabel
DefineLabel()
Label System.Text.RegularExpressions.RegexCompiler.DefineLabel () inline private inherited
Definition at line 313 of file RegexCompiler.cs.
    {
        return _ilg.DefineLabel();
    }
References System.Text.RegularExpressions.RegexCompiler._ilg, and System.Reflection.Emit.ILGenerator.DefineLabel().
Referenced by System.Text.RegularExpressions.RegexCompiler.AddTrack(), System.Text.RegularExpressions.RegexCompiler.EmitMatchCharacterClass(), System.Text.RegularExpressions.RegexCompiler.EmitTimeoutCheck(), System.Text.RegularExpressions.RegexCompiler.GenerateFindFirstChar(), System.Text.RegularExpressions.RegexCompiler.GenerateForwardSection(), System.Text.RegularExpressions.RegexCompiler.GenerateGo(), System.Text.RegularExpressions.RegexCompiler.GenerateMiddleSection(), System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), System.Text.RegularExpressions.RegexCompiler.Goto(), and System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo().