Terraria: System.Text.RegularExpressions.RegexCompiler.GenerateMiddleSection
GenerateMiddleSection()
void System.Text.RegularExpressions.RegexCompiler.GenerateMiddleSection () inline private inherited
Definition at line 981 of file RegexCompiler.cs.
    {
        using RentedLocalBuilder rentedLocalBuilder = RentInt32Local();
        Label l = DefineLabel();
        Label l2 = DefineLabel();
        MarkLabel(_backtrack);
        Ldthisfld(s_runtrackcountField);
        Ldc(4);
        Mul();
        Stloc(rentedLocalBuilder);
        Ldloc(_runstackposLocal);
        Ldloc(rentedLocalBuilder);
        Bge(l);
        Mvlocfld(_runstackposLocal, s_runstackposField);
        Ldthis();
        Call(s_doubleStackMethod);
        Mvfldloc(s_runstackposField, _runstackposLocal);
        Mvfldloc(s_runstackField, _runstackLocal);
        MarkLabel(l);
        Ldloc(_runtrackposLocal);
        Ldloc(rentedLocalBuilder);
        Bge(l2);
        Mvlocfld(_runtrackposLocal, s_runtrackposField);
        Ldthis();
        Call(s_doubleTrackMethod);
        Mvfldloc(s_runtrackposField, _runtrackposLocal);
        Mvfldloc(s_runtrackField, _runtrackLocal);
        MarkLabel(l2);
        PopTrack();
        Label[] array = new Label[_notecount];
        for (int i = 0; i < _notecount; i++)
        {
            array[i] = _notes[i]._label;
        }
        Switch(array);
    }
References System.Text.RegularExpressions.RegexCompiler._backtrack, System.Text.RegularExpressions.RegexCompiler.BacktrackNote._label, System.Text.RegularExpressions.RegexCompiler._notecount, System.Text.RegularExpressions.RegexCompiler._notes, System.Text.RegularExpressions.RegexCompiler._runstackLocal, System.Text.RegularExpressions.RegexCompiler._runstackposLocal, System.Text.RegularExpressions.RegexCompiler._runtrackLocal, System.Text.RegularExpressions.RegexCompiler._runtrackposLocal, System.Text.RegularExpressions.array, System.Reflection.Emit.Bge, System.Reflection.Emit.Call, System.Text.RegularExpressions.RegexCompiler.DefineLabel(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Reflection.Emit.Ldloc, System.Text.RegularExpressions.RegexCompiler.Ldthis(), System.Text.RegularExpressions.RegexCompiler.Ldthisfld(), System.Text.RegularExpressions.RegexCompiler.MarkLabel(), System.Text.RegularExpressions.RegexCompiler.Mul(), System.Text.RegularExpressions.RegexCompiler.Mvfldloc(), System.Text.RegularExpressions.RegexCompiler.Mvlocfld(), System.Text.RegularExpressions.RegexCompiler.PopTrack(), System.Text.RegularExpressions.RegexCompiler.RentInt32Local(), System.Text.RegularExpressions.RegexCompiler.s_doubleStackMethod, System.Text.RegularExpressions.RegexCompiler.s_doubleTrackMethod, System.Text.RegularExpressions.RegexCompiler.s_runstackField, System.Text.RegularExpressions.RegexCompiler.s_runstackposField, System.Text.RegularExpressions.RegexCompiler.s_runtrackcountField, System.Text.RegularExpressions.RegexCompiler.s_runtrackField, System.Text.RegularExpressions.RegexCompiler.s_runtrackposField, System.Reflection.Emit.Stloc, and System.Reflection.Emit.Switch.
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateGo().