Terraria: System.Text.RegularExpressions.RegexCompiler.CallToLower
CallToLower()
void System.Text.RegularExpressions.RegexCompiler.CallToLower () inline private inherited
Definition at line 915 of file RegexCompiler.cs.
    {
        if (UseToLowerInvariant)
        {
            Call(s_charToLowerInvariantMethod);
            return;
        }
        using RentedLocalBuilder rentedLocalBuilder = RentInt32Local();
        Stloc(rentedLocalBuilder);
        Ldloc(_textInfoLocal);
        Ldloc(rentedLocalBuilder);
        Callvirt(s_textInfoToLowerMethod);
    }
References System.Text.RegularExpressions.RegexCompiler._textInfoLocal, System.Reflection.Emit.Call, System.Reflection.Emit.Callvirt, System.Reflection.Emit.Ldloc, System.Text.RegularExpressions.RegexCompiler.RentInt32Local(), System.Text.RegularExpressions.RegexCompiler.s_charToLowerInvariantMethod, System.Text.RegularExpressions.RegexCompiler.s_textInfoToLowerMethod, System.Reflection.Emit.Stloc, and System.Text.RegularExpressions.RegexCompiler.UseToLowerInvariant.
Referenced by System.Text.RegularExpressions.RegexCompiler.EmitMatchCharacterClass(), System.Text.RegularExpressions.RegexCompiler.GenerateFindFirstChar(), System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), and System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo().