Terraria: System.Text.RegularExpressions.RegexCompiler.GenerateFindFirstChar
GenerateFindFirstChar()
void System.Text.RegularExpressions.RegexCompiler.GenerateFindFirstChar () inline protected inherited
Definition at line 1034 of file RegexCompiler.cs.
    {
        _int32LocalsPool?.Clear();
        _readOnlySpanCharLocalsPool?.Clear();
        _runtextposLocal = DeclareInt32();
        _runtextendLocal = DeclareInt32();
        if (_code.RightToLeft)
        {
            _runtextbegLocal = DeclareInt32();
        }
        _runtextLocal = DeclareString();
        _textInfoLocal = null;
        if (!_options.HasFlag(RegexOptions.CultureInvariant))
        {
            bool flag = _options.HasFlag(RegexOptions.IgnoreCase) || (_boyerMoorePrefix?.CaseInsensitive ?? false);
            if (!flag && _leadingCharClasses != null)
            {
                for (int i = 0; i < _leadingCharClasses.Length; i++)
                {
                    if (_leadingCharClasses[i].CaseInsensitive)
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                _textInfoLocal = DeclareTextInfo();
                InitLocalCultureInfo();
            }
        }
        Mvfldloc(s_runtextposField, _runtextposLocal);
        Mvfldloc(s_runtextendField, _runtextendLocal);
        if (_code.RightToLeft)
        {
            Mvfldloc(s_runtextbegField, _runtextbegLocal);
        }
        int minRequiredLength = _code.Tree.MinRequiredLength;
        Label l = DefineLabel();
        Label l2 = DefineLabel();
        if (!_code.RightToLeft)
        {
            Ldloc(_runtextposLocal);
            Ldloc(_runtextendLocal);
            if (minRequiredLength > 0)
            {
                Ldc(minRequiredLength);
                Sub();
            }
            Ble(l2);
            MarkLabel(l);
            Ldthis();
            Ldloc(_runtextendLocal);
        }
        else
        {
            Ldloc(_runtextposLocal);
            if (minRequiredLength > 0)
            {
                Ldc(minRequiredLength);
                Sub();
            }
            Ldloc(_runtextbegLocal);
            Bge(l2);
            MarkLabel(l);
            Ldthis();
            Ldloc(_runtextbegLocal);
        }
        Stfld(s_runtextposField);
        Ldc(0);
        Ret();
        MarkLabel(l2);
        if (((uint)_leadingAnchor & 0x37u) != 0)
        {
            switch (_leadingAnchor)
            {
            case 1:
            {
                Label l5 = DefineLabel();
                Ldloc(_runtextposLocal);
                if (!_code.RightToLeft)
                {
                    Ldthisfld(s_runtextbegField);
                    Ble(l5);
                    Br(l);
                }
                else
                {
                    Ldloc(_runtextbegLocal);
                    Ble(l5);
                    Ldthis();
                    Ldloc(_runtextbegLocal);
                    Stfld(s_runtextposField);
                }
                MarkLabel(l5);
                Ldc(1);
                Ret();
                return;
            }
            case 4:
            {
                Label l4 = DefineLabel();
                Ldloc(_runtextposLocal);
                Ldthisfld(s_runtextstartField);
                if (!_code.RightToLeft)
                {
                    Ble(l4);
                }
                else
                {
                    Bge(l4);
                }
                Br(l);
                MarkLabel(l4);
                Ldc(1);
                Ret();
                return;
            }
            case 16:
            {
                Label l7 = DefineLabel();
                if (!_code.RightToLeft)
                {
                    Ldloc(_runtextposLocal);
                    Ldloc(_runtextendLocal);
                    Ldc(1);
                    Sub();
                    Bge(l7);
                    Ldthis();
                    Ldloc(_runtextendLocal);
                    Ldc(1);
                    Sub();
                    Stfld(s_runtextposField);
                    MarkLabel(l7);
                }
                else
                {
                    Label l8 = DefineLabel();
                    Ldloc(_runtextposLocal);
                    Ldloc(_runtextendLocal);
                    Ldc(1);
                    Sub();
                    Blt(l7);
                    Ldloc(_runtextposLocal);
                    Ldloc(_runtextendLocal);
                    Beq(l8);
                    Ldthisfld(s_runtextField);
                    Ldloc(_runtextposLocal);
                    Call(s_stringGetCharsMethod);
                    Ldc(10);
                    Beq(l8);
                    MarkLabel(l7);
                    BrFar(l);
                    MarkLabel(l8);
                }
                Ldc(1);
                Ret();
                return;
            }
            case 32:
                if (minRequiredLength == 0)
                {
                    Label l6 = DefineLabel();
                    Ldloc(_runtextposLocal);
                    Ldloc(_runtextendLocal);
                    if (!_code.RightToLeft)
                    {
                        Bge(l6);
                        Ldthis();
                        Ldloc(_runtextendLocal);
                        Stfld(s_runtextposField);
                    }
                    else
                    {
                        Bge(l6);
                        Br(l);
                    }
                    MarkLabel(l6);
                    Ldc(1);
                    Ret();
                    return;
                }
                break;
            case 2:
                if (!_code.RightToLeft)
                {
                    Label l3 = DefineLabel();
                    Ldloc(_runtextposLocal);
                    Ldthisfld(s_runtextbegField);
                    Ble(l3);
                    Ldthisfld(s_runtextField);
                    Ldloc(_runtextposLocal);
                    Ldc(1);
                    Sub();
                    Call(s_stringGetCharsMethod);
                    Ldc(10);
                    Beq(l3);
                    Ldthisfld(s_runtextField);
                    Ldc(10);
                    Ldloc(_runtextposLocal);
                    Call(s_stringIndexOfCharInt);
                    using (RentedLocalBuilder rentedLocalBuilder = RentInt32Local())
                    {
                        Stloc(rentedLocalBuilder);
                        Ldloc(rentedLocalBuilder);
                        Ldc(-1);
                        Beq(l);
                        Ldloc(rentedLocalBuilder);
                        Ldc(1);
                        Add();
                        Ldloc(_runtextendLocal);
                        Bgt(l);
                        Ldloc(rentedLocalBuilder);
                        Ldc(1);
                        Add();
                        Stloc(_runtextposLocal);
                    }
                    MarkLabel(l3);
                }
                break;
            }
        }
        if (_boyerMoorePrefix != null && _boyerMoorePrefix.NegativeUnicode == null)
        {
            LocalBuilder lt;
            int num;
            int index;
            if (!_code.RightToLeft)
            {
                lt = _runtextendLocal;
                num = -1;
                index = _boyerMoorePrefix.Pattern.Length - 1;
            }
            else
            {
                lt = _runtextbegLocal;
                num = _boyerMoorePrefix.Pattern.Length;
                index = 0;
            }
            int i2 = _boyerMoorePrefix.Pattern[index];
            Mvfldloc(s_runtextField, _runtextLocal);
            Ldloc(_runtextposLocal);
            if (!_code.RightToLeft)
            {
                Ldc(_boyerMoorePrefix.Pattern.Length - 1);
                Add();
            }
            else
            {
                Ldc(_boyerMoorePrefix.Pattern.Length);
                Sub();
            }
            Stloc(_runtextposLocal);
            Label l9 = DefineLabel();
            Br(l9);
            Label l10 = DefineLabel();
            MarkLabel(l10);
            Ldc(_code.RightToLeft ? (-_boyerMoorePrefix.Pattern.Length) : _boyerMoorePrefix.Pattern.Length);
            Label l11 = DefineLabel();
            MarkLabel(l11);
            Ldloc(_runtextposLocal);
            Add();
            Stloc(_runtextposLocal);
            MarkLabel(l9);
            Ldloc(_runtextposLocal);
            Ldloc(lt);
            if (!_code.RightToLeft)
            {
                BgeFar(l);
            }
            else
            {
                BltFar(l);
            }
            Rightchar();
            if (_boyerMoorePrefix.CaseInsensitive)
            {
                CallToLower();
            }
            Label l12 = DefineLabel();
            using (RentedLocalBuilder rentedLocalBuilder2 = RentInt32Local())
            {
                Stloc(rentedLocalBuilder2);
                Ldloc(rentedLocalBuilder2);
                Ldc(i2);
                BeqFar(l12);
                Ldloc(rentedLocalBuilder2);
                Ldc(_boyerMoorePrefix.LowASCII);
                Sub();
                Stloc(rentedLocalBuilder2);
                Ldloc(rentedLocalBuilder2);
                Ldc(_boyerMoorePrefix.HighASCII - _boyerMoorePrefix.LowASCII);
                BgtUn(l10);
                int num2 = _boyerMoorePrefix.HighASCII - _boyerMoorePrefix.LowASCII + 1;
                if (num2 > 1)
                {
                    string str = string.Create(num2, (this, num), delegate(Span<char> span, (RegexCompiler thisRef, int beforefirst) state)
                    {
                        for (int k = 0; k < span.Length; k++)
{
                            int num8 = state.thisRef._boyerMoorePrefix.NegativeASCII[k + state.thisRef._boyerMoorePrefix.LowASCII];
                            if (num8 == state.beforefirst)
{
                                num8 = state.thisRef._boyerMoorePrefix.Pattern.Length;
                            }
                            else if (state.thisRef._code.RightToLeft)
{
                                num8 = -num8;
                            }
                            span[k] = (char)num8;
                        }
                    });
                    Ldstr(str);
                    Ldloc(rentedLocalBuilder2);
                    Call(s_stringGetCharsMethod);
                    if (_code.RightToLeft)
                    {
                        Neg();
                    }
                }
                else
                {
                    int num3 = _boyerMoorePrefix.NegativeASCII[_boyerMoorePrefix.LowASCII];
                    if (num3 == num)
                    {
                        num3 = (_code.RightToLeft ? (-_boyerMoorePrefix.Pattern.Length) : _boyerMoorePrefix.Pattern.Length);
                    }
                    Ldc(num3);
                }
                BrFar(l11);
            }
            MarkLabel(l12);
            Ldloc(_runtextposLocal);
            using RentedLocalBuilder rentedLocalBuilder3 = RentInt32Local();
            Stloc(rentedLocalBuilder3);
            int num4 = int.MaxValue;
            Label l13 = default(Label);
            for (int num5 = _boyerMoorePrefix.Pattern.Length - 2; num5 >= 0; num5--)
            {
                int num6 = (_code.RightToLeft ? (_boyerMoorePrefix.Pattern.Length - 1 - num5) : num5);
                Ldloc(_runtextLocal);
                Ldloc(rentedLocalBuilder3);
                Ldc(1);
                Sub(_code.RightToLeft);
                Stloc(rentedLocalBuilder3);
                Ldloc(rentedLocalBuilder3);
                Call(s_stringGetCharsMethod);
                if (_boyerMoorePrefix.CaseInsensitive && ParticipatesInCaseConversion(_boyerMoorePrefix.Pattern[num6]))
                {
                    CallToLower();
                }
                Ldc(_boyerMoorePrefix.Pattern[num6]);
                if (num4 == _boyerMoorePrefix.Positive[num6])
                {
                    BneFar(l13);
                }
                else
                {
                    Label l14 = DefineLabel();
                    Beq(l14);
                    l13 = DefineLabel();
                    num4 = _boyerMoorePrefix.Positive[num6];
                    MarkLabel(l13);
                    Ldc(num4);
                    BrFar(l11);
                    MarkLabel(l14);
                }
            }
            Ldthis();
            Ldloc(rentedLocalBuilder3);
            if (_code.RightToLeft)
            {
                Ldc(1);
                Add();
            }
            Stfld(s_runtextposField);
            Ldc(1);
            Ret();
            return;
        }
        if (_leadingCharClasses == null)
        {
            Ldc(1);
            Ret();
            return;
        }
        if (_code.RightToLeft)
        {
            using (RentedLocalBuilder rentedLocalBuilder4 = RentInt32Local())
            {
                Label l15 = DefineLabel();
                Label l16 = DefineLabel();
                Label l17 = DefineLabel();
                Label l18 = DefineLabel();
                Label l19 = DefineLabel();
                Mvfldloc(s_runtextField, _runtextLocal);
                Ldloc(_runtextposLocal);
                Ldloc(_runtextbegLocal);
                Sub();
                Stloc(rentedLocalBuilder4);
                if (minRequiredLength == 0)
                {
                    Ldloc(rentedLocalBuilder4);
                    Ldc(0);
                    BleFar(l18);
                }
                MarkLabel(l15);
                Ldloc(rentedLocalBuilder4);
                Ldc(1);
                Sub();
                Stloc(rentedLocalBuilder4);
                Leftcharnext();
                if (!RegexCharClass.IsSingleton(_leadingCharClasses[0].CharClass))
                {
                    EmitMatchCharacterClass(_leadingCharClasses[0].CharClass, _leadingCharClasses[0].CaseInsensitive);
                    Brtrue(l16);
                }
                else
                {
                    Ldc(RegexCharClass.SingletonChar(_leadingCharClasses[0].CharClass));
                    Beq(l16);
                }
                MarkLabel(l19);
                Ldloc(rentedLocalBuilder4);
                Ldc(0);
                if (!RegexCharClass.IsSingleton(_leadingCharClasses[0].CharClass))
                {
                    BgtFar(l15);
                }
                else
                {
                    Bgt(l15);
                }
                Ldc(0);
                Br(l17);
                MarkLabel(l16);
                Ldloc(_runtextposLocal);
                Ldc(1);
                Sub(_code.RightToLeft);
                Stloc(_runtextposLocal);
                Ldc(1);
                MarkLabel(l17);
                Mvlocfld(_runtextposLocal, s_runtextposField);
                Ret();
                MarkLabel(l18);
                Ldc(0);
                Ret();
                return;
            }
        }
        if (minRequiredLength < _leadingCharClasses.Length)
        {
            Ldloc(_runtextendLocal);
            if (_leadingCharClasses.Length > 1)
            {
                Ldc(_leadingCharClasses.Length - 1);
                Sub();
            }
            Ldloc(_runtextposLocal);
            BleFar(l);
        }
        using RentedLocalBuilder rentedLocalBuilder6 = RentInt32Local();
        using RentedLocalBuilder rentedLocalBuilder5 = RentReadOnlySpanCharLocal();
        Ldthisfld(s_runtextField);
        Ldloc(_runtextposLocal);
        Ldloc(_runtextendLocal);
        Ldloc(_runtextposLocal);
        Sub();
        Call(s_stringAsSpanIntIntMethod);
        Stloc(rentedLocalBuilder5);
        Span<char> chars = stackalloc char[3];
        int num7 = 0;
        int j = 0;
        bool flag2 = !_leadingCharClasses[0].CaseInsensitive && (num7 = RegexCharClass.GetSetChars(_leadingCharClasses[0].CharClass, chars)) > 0 && !RegexCharClass.IsNegated(_leadingCharClasses[0].CharClass);
        bool flag3 = !flag2 || _leadingCharClasses.Length > 1;
        Label l20 = default(Label);
        Label l21 = default(Label);
        Label l22 = default(Label);
        if (flag3)
        {
            l20 = DefineLabel();
            l21 = DefineLabel();
            l22 = DefineLabel();
            Ldc(0);
            Stloc(rentedLocalBuilder6);
            BrFar(l20);
            MarkLabel(l22);
        }
        if (flag2)
        {
            j = 1;
            if (flag3)
            {
                Ldloca(rentedLocalBuilder5);
                Ldloc(rentedLocalBuilder6);
                Call(s_spanSliceIntMethod);
            }
            else
            {
                Ldloc(rentedLocalBuilder5);
            }
            switch (num7)
            {
            case 1:
                Ldc(chars[0]);
                Call(s_spanIndexOf);
                break;
            case 2:
                Ldc(chars[0]);
                Ldc(chars[1]);
                Call(s_spanIndexOfAnyCharChar);
                break;
            default:
                Ldc(chars[0]);
                Ldc(chars[1]);
                Ldc(chars[2]);
                Call(s_spanIndexOfAnyCharCharChar);
                break;
            }
            if (flag3)
            {
                using RentedLocalBuilder rentedLocalBuilder7 = RentInt32Local();
                Stloc(rentedLocalBuilder7);
                Ldloc(rentedLocalBuilder6);
                Ldloc(rentedLocalBuilder7);
                Add();
                Stloc(rentedLocalBuilder6);
                Ldloc(rentedLocalBuilder7);
                Ldc(0);
                BltFar(l);
            }
            else
            {
                Stloc(rentedLocalBuilder6);
                Ldloc(rentedLocalBuilder6);
                Ldc(0);
                BltFar(l);
            }
            if (_leadingCharClasses.Length > 1)
            {
                Ldloca(rentedLocalBuilder5);
                Call(s_spanGetLengthMethod);
                Ldc(_leadingCharClasses.Length - 1);
                Sub();
                Ldloc(rentedLocalBuilder6);
                BleFar(l);
            }
        }
        for (; j < _leadingCharClasses.Length; j++)
        {
            Ldloca(rentedLocalBuilder5);
            Ldloc(rentedLocalBuilder6);
            if (j > 0)
            {
                Ldc(j);
                Add();
            }
            Call(s_spanGetItemMethod);
            LdindU2();
            EmitMatchCharacterClass(_leadingCharClasses[j].CharClass, _leadingCharClasses[j].CaseInsensitive);
            BrfalseFar(l21);
        }
        Ldthis();
        Ldloc(_runtextposLocal);
        Ldloc(rentedLocalBuilder6);
        Add();
        Stfld(s_runtextposField);
        Ldc(1);
        Ret();
        if (flag3)
        {
            MarkLabel(l21);
            Ldloc(rentedLocalBuilder6);
            Ldc(1);
            Add();
            Stloc(rentedLocalBuilder6);
            MarkLabel(l20);
            Ldloc(rentedLocalBuilder6);
            Ldloca(rentedLocalBuilder5);
            Call(s_spanGetLengthMethod);
            if (_leadingCharClasses.Length > 1)
            {
                Ldc(_leadingCharClasses.Length - 1);
                Sub();
            }
            BltFar(l22);
            BrFar(l);
        }
    }
References System.Text.RegularExpressions.RegexCompiler._boyerMoorePrefix, System.Text.RegularExpressions.RegexCompiler._code, System.Text.RegularExpressions.RegexCompiler._int32LocalsPool, System.Text.RegularExpressions.RegexCompiler._leadingAnchor, System.Text.RegularExpressions.RegexCompiler._leadingCharClasses, System.Text.RegularExpressions.RegexCompiler._options, System.Text.RegularExpressions.RegexCompiler._readOnlySpanCharLocalsPool, System.Text.RegularExpressions.RegexCompiler._runtextbegLocal, System.Text.RegularExpressions.RegexCompiler._runtextendLocal, System.Text.RegularExpressions.RegexCompiler._runtextLocal, System.Text.RegularExpressions.RegexCompiler._runtextposLocal, System.Text.RegularExpressions.RegexCompiler._textInfoLocal, System.Text.RegularExpressions.RegexCompiler.Add(), System.Reflection.Emit.Beq, System.Text.RegularExpressions.RegexCompiler.BeqFar(), System.Reflection.Emit.Bge, System.Text.RegularExpressions.RegexCompiler.BgeFar(), System.Reflection.Emit.Bgt, System.Text.RegularExpressions.RegexCompiler.BgtFar(), System.Text.RegularExpressions.RegexCompiler.BgtUn(), System.Reflection.Emit.Ble, System.Text.RegularExpressions.RegexCompiler.BleFar(), System.Reflection.Emit.Blt, System.Text.RegularExpressions.RegexCompiler.BltFar(), System.Text.RegularExpressions.RegexCompiler.BneFar(), System.Reflection.Emit.Br, System.Text.RegularExpressions.RegexCompiler.BrfalseFar(), System.Text.RegularExpressions.RegexCompiler.BrFar(), System.Reflection.Emit.Brtrue, System.Reflection.Emit.Call, System.Text.RegularExpressions.RegexCompiler.CallToLower(), System.Text.RegularExpressions.RegexBoyerMoore.CaseInsensitive, System.Text.RegularExpressions.RegexCompiler.CharClass, System.chars, System.Collections.Generic.Stack< T >.Clear(), System.Text.RegularExpressions.RegexCompiler.DeclareInt32(), System.Text.RegularExpressions.RegexCompiler.DeclareString(), System.Text.RegularExpressions.RegexCompiler.DeclareTextInfo(), System.Text.RegularExpressions.RegexCompiler.DefineLabel(), System.Text.RegularExpressions.RegexCompiler.EmitMatchCharacterClass(), System.Text.RegularExpressions.RegexCharClass.GetSetChars(), System.Text.RegularExpressions.RegexBoyerMoore.HighASCII, System.Text.RegularExpressions.i, System.index, System.Text.RegularExpressions.RegexCompiler.InitLocalCultureInfo(), System.Text.RegularExpressions.RegexCharClass.IsNegated(), System.Text.RegularExpressions.RegexCharClass.IsSingleton(), System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Text.RegularExpressions.RegexCompiler.LdindU2(), System.Reflection.Emit.Ldloc, System.Reflection.Emit.Ldloca, System.Reflection.Emit.Ldstr, System.Text.RegularExpressions.RegexCompiler.Ldthis(), System.Text.RegularExpressions.RegexCompiler.Ldthisfld(), System.Text.RegularExpressions.RegexCompiler.Leftcharnext(), System.Text.RegularExpressions.RegexBoyerMoore.LowASCII, System.Text.RegularExpressions.RegexCompiler.MarkLabel(), System.Text.RegularExpressions.RegexTree.MinRequiredLength, System.Text.RegularExpressions.RegexCompiler.Mvfldloc(), System.Text.RegularExpressions.RegexCompiler.Mvlocfld(), System.Text.RegularExpressions.RegexCompiler.Neg(), System.Text.RegularExpressions.RegexBoyerMoore.NegativeASCII, System.Text.RegularExpressions.RegexBoyerMoore.NegativeUnicode, System.Text.RegularExpressions.RegexCompiler.ParticipatesInCaseConversion(), System.Text.RegularExpressions.RegexBoyerMoore.Pattern, System.Text.RegularExpressions.RegexBoyerMoore.Positive, System.Text.RegularExpressions.RegexCompiler.RentInt32Local(), System.Text.RegularExpressions.RegexCompiler.RentReadOnlySpanCharLocal(), System.Text.RegularExpressions.RegexCompiler.Ret(), System.Text.RegularExpressions.RegexCompiler.Rightchar(), System.Text.RegularExpressions.RegexCode.RightToLeft, System.Text.RegularExpressions.RegexCompiler.s_runtextbegField, System.Text.RegularExpressions.RegexCompiler.s_runtextendField, System.Text.RegularExpressions.RegexCompiler.s_runtextField, System.Text.RegularExpressions.RegexCompiler.s_runtextposField, System.Text.RegularExpressions.RegexCompiler.s_runtextstartField, System.Text.RegularExpressions.RegexCompiler.s_spanGetItemMethod, System.Text.RegularExpressions.RegexCompiler.s_spanGetLengthMethod, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOf, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOfAnyCharChar, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOfAnyCharCharChar, System.Text.RegularExpressions.RegexCompiler.s_spanSliceIntMethod, System.Text.RegularExpressions.RegexCompiler.s_stringAsSpanIntIntMethod, System.Text.RegularExpressions.RegexCompiler.s_stringGetCharsMethod, System.Text.RegularExpressions.RegexCompiler.s_stringIndexOfCharInt, System.Text.RegularExpressions.RegexCharClass.SingletonChar(), System.state, System.Reflection.Emit.Stfld, System.Reflection.Emit.Stloc, System.Text.RegularExpressions.str, System.Text.RegularExpressions.RegexCompiler.Sub(), and System.Text.RegularExpressions.RegexCode.Tree.
Referenced by System.Text.RegularExpressions.RegexLWCGCompiler.FactoryInstanceFromCode().