Terraria: System.Text.RegularExpressions.RegexCompiler.Goto
Goto()
void System.Text.RegularExpressions.RegexCompiler.Goto (int i) inline private inherited
Definition at line 870 of file RegexCompiler.cs.
    {
        if (i < _codepos)
        {
            Label l = DefineLabel();
            Ldloc(_runtrackposLocal);
            Ldc(_trackcount * 4);
            Ble(l);
            Ldloc(_runstackposLocal);
            Ldc(_trackcount * 3);
            BgtFar(_labels[i]);
            MarkLabel(l);
            ReadyPushTrack();
            Ldc(AddGoto(i));
            DoPush();
            BrFar(_backtrack);
        }
        else
        {
            BrFar(_labels[i]);
        }
    }
References System.Text.RegularExpressions.RegexCompiler._backtrack, System.Text.RegularExpressions.RegexCompiler._codepos, System.Text.RegularExpressions.RegexCompiler._labels, System.Text.RegularExpressions.RegexCompiler._runstackposLocal, System.Text.RegularExpressions.RegexCompiler._runtrackposLocal, System.Text.RegularExpressions.RegexCompiler._trackcount, System.Text.RegularExpressions.RegexCompiler.AddGoto(), System.Text.RegularExpressions.RegexCompiler.BgtFar(), System.Reflection.Emit.Ble, System.Text.RegularExpressions.RegexCompiler.BrFar(), System.Text.RegularExpressions.RegexCompiler.DefineLabel(), System.Text.RegularExpressions.RegexCompiler.DoPush(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Reflection.Emit.Ldloc, System.Text.RegularExpressions.RegexCompiler.MarkLabel(), and System.Text.RegularExpressions.RegexCompiler.ReadyPushTrack().
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateOneCode().