Terraria: Terraria.WorldBuilding.Shapes.Circle.Perform
Perform()
override bool Terraria.WorldBuilding.Shapes.Circle.Perform (Point origin, GenAction action) inline
Definition at line 33 of file Shapes.cs.
        {
            int num = (_horizontalRadius + 1) * (_horizontalRadius + 1);
            for (int i = origin.Y - _verticalRadius; i <= origin.Y + _verticalRadius; i++)
            {
                double num2 = (double)_horizontalRadius / (double)_verticalRadius * (double)(i - origin.Y);
                int num3 = Math.Min(_horizontalRadius, (int)Math.Sqrt((double)num - num2 * num2));
                for (int j = origin.X - num3; j <= origin.X + num3; j++)
                {
                    if (!UnitApply(action, origin, j, i) && _quitOnFail)
                    {
                        return false;
                    }
                }
            }
            return true;
        }
References Terraria.WorldBuilding.Shapes.Circle._horizontalRadius, Terraria.WorldBuilding.GenShape._quitOnFail, Terraria.WorldBuilding.Shapes.Circle._verticalRadius, System.action, System.Math.Min(), System.Math.Sqrt(), Terraria.WorldBuilding.GenShape.UnitApply(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.