Terraria: System.Text.RegularExpressions.RegexCompiler.ReadyPushTrack
ReadyPushTrack()
void System.Text.RegularExpressions.RegexCompiler.ReadyPushTrack () inline private inherited
Definition at line 762 of file RegexCompiler.cs.
    {
        Ldloc(_runtrackposLocal);
        Ldc(1);
        Sub();
        Stloc(_runtrackposLocal);
        Ldloc(_runtrackLocal);
        Ldloc(_runtrackposLocal);
    }
References System.Text.RegularExpressions.RegexCompiler._runtrackLocal, System.Text.RegularExpressions.RegexCompiler._runtrackposLocal, System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Reflection.Emit.Ldloc, System.Reflection.Emit.Stloc, and System.Text.RegularExpressions.RegexCompiler.Sub().
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), System.Text.RegularExpressions.RegexCompiler.Goto(), System.Text.RegularExpressions.RegexCompiler.PushTrack(), System.Text.RegularExpressions.RegexCompiler.Track(), System.Text.RegularExpressions.RegexCompiler.Trackagain(), System.Text.RegularExpressions.RegexCompiler.TrackUnique(), and System.Text.RegularExpressions.RegexCompiler.TrackUnique2().