Terraria: System.Text.RegularExpressions.RegexCompiler.Ldc
Ldc()
void System.Text.RegularExpressions.RegexCompiler.Ldc (int i) inline protected inherited
Definition at line 348 of file RegexCompiler.cs.
    {
        _ilg.Emit(OpCodes.Ldc_I4, i);
    }
References System.Text.RegularExpressions.RegexCompiler._ilg, System.Reflection.Emit.ILGenerator.Emit(), System.Text.RegularExpressions.i, and System.Reflection.Emit.OpCodes.Ldc_I4.
Referenced by System.Text.RegularExpressions.RegexCompiler.EmitMatchCharacterClass(), System.Text.RegularExpressions.RegexCompiler.EmitTimeoutCheck(), System.Text.RegularExpressions.RegexCompiler.GenerateFindFirstChar(), System.Text.RegularExpressions.RegexCompiler.GenerateMiddleSection(), System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), System.Text.RegularExpressions.RegexCompiler.Goto(), System.Text.RegularExpressions.RegexCompiler.Leftchar(), System.Text.RegularExpressions.RegexCompiler.Leftcharnext(), System.Text.RegularExpressions.RegexCompiler.PopDiscardStack(), System.Text.RegularExpressions.RegexCompiler.PopStack(), System.Text.RegularExpressions.RegexCompiler.PopTrack(), System.Text.RegularExpressions.RegexCompiler.ReadyPushStack(), System.Text.RegularExpressions.RegexCompiler.ReadyPushTrack(), System.Text.RegularExpressions.RegexCompiler.ReadyReplaceStack(), System.Text.RegularExpressions.RegexCompiler.Rightcharnext(), System.Text.RegularExpressions.RegexCompiler.Track(), System.Text.RegularExpressions.RegexCompiler.Trackagain(), System.Text.RegularExpressions.RegexCompiler.TrackUnique(), System.Text.RegularExpressions.RegexCompiler.TrackUnique2(), and System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo().