Terraria: System.Text.RegularExpressions.RegexCompiler.GenerateForwardSection
GenerateForwardSection()
void System.Text.RegularExpressions.RegexCompiler.GenerateForwardSection () inline private inherited
Definition at line 952 of file RegexCompiler.cs.
    {
        _uniquenote = new int[10];
        _labels = new Label[_codes.Length];
        _goto = new int[_codes.Length];
        Array.Fill(_uniquenote, -1);
        for (int i = 0; i < _codes.Length; i += RegexCode.OpcodeSize(_codes[i]))
        {
            _goto[i] = -1;
            _labels[i] = DefineLabel();
        }
        Mvfldloc(s_runtextField, _runtextLocal);
        Mvfldloc(s_runtextbegField, _runtextbegLocal);
        Mvfldloc(s_runtextendField, _runtextendLocal);
        Mvfldloc(s_runtextposField, _runtextposLocal);
        Mvfldloc(s_runtrackField, _runtrackLocal);
        Mvfldloc(s_runtrackposField, _runtrackposLocal);
        Mvfldloc(s_runstackField, _runstackLocal);
        Mvfldloc(s_runstackposField, _runstackposLocal);
        _backpos = -1;
        for (int j = 0; j < _codes.Length; j += RegexCode.OpcodeSize(_codes[j]))
        {
            MarkLabel(_labels[j]);
            _codepos = j;
            _regexopcode = _codes[j];
            GenerateOneCode();
        }
    }
References System.Text.RegularExpressions.RegexCompiler._backpos, System.Text.RegularExpressions.RegexCompiler._codepos, System.Text.RegularExpressions.RegexCompiler._codes, System.Text.RegularExpressions.RegexCompiler._goto, System.Text.RegularExpressions.RegexCompiler._labels, System.Text.RegularExpressions.RegexCompiler._regexopcode, System.Text.RegularExpressions.RegexCompiler._runstackLocal, System.Text.RegularExpressions.RegexCompiler._runstackposLocal, System.Text.RegularExpressions.RegexCompiler._runtextbegLocal, System.Text.RegularExpressions.RegexCompiler._runtextendLocal, System.Text.RegularExpressions.RegexCompiler._runtextLocal, System.Text.RegularExpressions.RegexCompiler._runtextposLocal, System.Text.RegularExpressions.RegexCompiler._runtrackLocal, System.Text.RegularExpressions.RegexCompiler._runtrackposLocal, System.Text.RegularExpressions.RegexCompiler._uniquenote, System.Text.RegularExpressions.RegexCompiler.DefineLabel(), System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexCompiler.MarkLabel(), System.Text.RegularExpressions.RegexCompiler.Mvfldloc(), System.Text.RegularExpressions.RegexCode.OpcodeSize(), System.Text.RegularExpressions.RegexCompiler.s_runstackField, System.Text.RegularExpressions.RegexCompiler.s_runstackposField, System.Text.RegularExpressions.RegexCompiler.s_runtextbegField, System.Text.RegularExpressions.RegexCompiler.s_runtextendField, System.Text.RegularExpressions.RegexCompiler.s_runtextField, System.Text.RegularExpressions.RegexCompiler.s_runtextposField, System.Text.RegularExpressions.RegexCompiler.s_runtrackField, and System.Text.RegularExpressions.RegexCompiler.s_runtrackposField.
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateGo().