Terraria: System.Lazy.CreateValue
CreateValue()
T System.Lazy< T, TMetadata >.CreateValue () inline private
Definition at line 180 of file Lazy.cs.
    {
        LazyHelper state = _state;
        if (state != null)
        {
            switch (state.State)
            {
            case LazyState.NoneViaConstructor:
                ViaConstructor();
                break;
            case LazyState.NoneViaFactory:
                ViaFactory(LazyThreadSafetyMode.None);
                break;
            case LazyState.PublicationOnlyViaConstructor:
                PublicationOnlyViaConstructor(state);
                break;
            case LazyState.PublicationOnlyViaFactory:
                PublicationOnlyViaFactory(state);
                break;
            case LazyState.PublicationOnlyWait:
                PublicationOnlyWaitForOtherThreadToPublish();
                break;
            case LazyState.ExecutionAndPublicationViaConstructor:
                ExecutionAndPublication(state, useDefaultConstructor: true);
                break;
            case LazyState.ExecutionAndPublicationViaFactory:
                ExecutionAndPublication(state, useDefaultConstructor: false);
                break;
            default:
                state.ThrowException();
                break;
            }
        }
        return Value;
    }
References System.Lazy< T, TMetadata >._state, System.Threading.ExecutionAndPublication, System.LazyHelper.NoneViaConstructor, System.PublicationOnlyViaConstructor, System.PublicationOnlyViaFactory, System.Lazy< T, TMetadata >.PublicationOnlyWaitForOtherThreadToPublish(), System.state, System.Lazy< T, TMetadata >.Value, System.Lazy< T, TMetadata >.ViaConstructor(), and System.Lazy< T, TMetadata >.ViaFactory().