Terraria: System.Text.RegularExpressions.RegexCompiler.GenerateBacktrackSection
GenerateBacktrackSection()
void System.Text.RegularExpressions.RegexCompiler.GenerateBacktrackSection () inline private inherited
Definition at line 1018 of file RegexCompiler.cs.
    {
        for (int i = 0; i < _notecount; i++)
        {
            BacktrackNote backtrackNote = _notes[i];
            if (backtrackNote._flags != 0)
            {
                MarkLabel(backtrackNote._label);
                _codepos = backtrackNote._codepos;
                _backpos = i;
                _regexopcode = _codes[backtrackNote._codepos] | backtrackNote._flags;
                GenerateOneCode();
            }
        }
    }
References System.Text.RegularExpressions.RegexCompiler._backpos, System.Text.RegularExpressions.RegexCompiler._codepos, System.Text.RegularExpressions.RegexCompiler._codes, System.Text.RegularExpressions.RegexCompiler._notecount, System.Text.RegularExpressions.RegexCompiler._notes, System.Text.RegularExpressions.RegexCompiler._regexopcode, System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), System.Text.RegularExpressions.i, and System.Text.RegularExpressions.RegexCompiler.MarkLabel().
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateGo().