Terraria: System.Text.RegularExpressions.RegexCompiler.ParticipatesInCaseConversion
ParticipatesInCaseConversion()
static bool System.Text.RegularExpressions.RegexCompiler.ParticipatesInCaseConversion (int comparison) inline static private inherited
Definition at line 929 of file RegexCompiler.cs.
    {
        switch (char.GetUnicodeCategory((char)comparison))
        {
        case UnicodeCategory.DecimalDigitNumber:
        case UnicodeCategory.OtherNumber:
        case UnicodeCategory.SpaceSeparator:
        case UnicodeCategory.LineSeparator:
        case UnicodeCategory.ParagraphSeparator:
        case UnicodeCategory.Control:
        case UnicodeCategory.ConnectorPunctuation:
        case UnicodeCategory.DashPunctuation:
        case UnicodeCategory.OpenPunctuation:
        case UnicodeCategory.ClosePunctuation:
        case UnicodeCategory.InitialQuotePunctuation:
        case UnicodeCategory.FinalQuotePunctuation:
        case UnicodeCategory.OtherPunctuation:
            return false;
        default:
            return true;
        }
    }
References System.comparison.
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateFindFirstChar(), System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), and System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo().