Terraria: System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo
TryGenerateNonBacktrackingGo()
bool System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo (RegexNode node) inline private inherited
Definition at line 1625 of file RegexCompiler.cs.
    {
        if ((node.Options & RegexOptions.RightToLeft) != 0)
        {
            return false;
        }
        node = node.Child(0);
        if (!NodeSupportsNonBacktrackingImplementation(node, 20))
        {
            return false;
        }
        LocalBuilder runtextLocal = DeclareString();
        LocalBuilder lt = DeclareInt32();
        LocalBuilder runtextposLocal = DeclareInt32();
        LocalBuilder textSpanLocal = DeclareReadOnlySpanChar();
        LocalBuilder runtextendLocal = DeclareInt32();
        Label l = DefineLabel();
        Label doneLabel = DefineLabel();
        if (_hasTimeout)
        {
            _loopTimeoutCounterLocal = DeclareInt32();
        }
        InitializeCultureForGoIfNecessary();
        Mvfldloc(s_runtextField, runtextLocal);
        Mvfldloc(s_runtextendField, runtextendLocal);
        Ldthisfld(s_runtextposField);
        Stloc(runtextposLocal);
        Ldloc(runtextposLocal);
        Stloc(lt);
        int textSpanPos = 0;
        LoadTextSpanLocal();
        EmitNode(node);
        MarkLabel(l);
        Ldthis();
        Ldloc(runtextposLocal);
        if (textSpanPos > 0)
        {
            Ldc(textSpanPos);
            Add();
            Stloc(runtextposLocal);
            Ldloc(runtextposLocal);
        }
        Stfld(s_runtextposField);
        Ldthis();
        Ldc(0);
        Ldloc(lt);
        Ldloc(runtextposLocal);
        Call(s_captureMethod);
        if (((uint)node.Options & 0x80000000u) != 0)
        {
            Label l2 = DefineLabel();
            Br(l2);
            MarkLabel(doneLabel);
            Label l3 = DefineLabel();
            Label l4 = DefineLabel();
            Br(l3);
            MarkLabel(l4);
            Ldthis();
            Call(s_uncaptureMethod);
            MarkLabel(l3);
            Ldthis();
            Call(s_crawlposMethod);
            Brtrue(l4);
            MarkLabel(l2);
        }
        else
        {
            MarkLabel(doneLabel);
        }
        Ret();
        return true;
        void EmitAnchors(RegexNode node)
        {
            switch (node.Type)
            {
            default:
                return;
            case 18:
            case 19:
                if (textSpanPos > 0)
                {
                    BrFar(doneLabel);
                }
                else
                {
                    Ldloc(runtextposLocal);
                    Ldthisfld((node.Type == 18) ? s_runtextbegField : s_runtextstartField);
                    BneFar(doneLabel);
                }
                return;
            case 14:
                if (textSpanPos > 0)
                {
                    Ldloca(textSpanLocal);
                    Ldc(textSpanPos - 1);
                    Call(s_spanGetItemMethod);
                    LdindU2();
                    Ldc(10);
                    BneFar(doneLabel);
                }
                else
                {
                    Label l5 = DefineLabel();
                    Ldloc(runtextposLocal);
                    Ldthisfld(s_runtextbegField);
                    Ble(l5);
                    Ldthisfld(s_runtextField);
                    Ldloc(runtextposLocal);
                    Ldc(1);
                    Sub();
                    Call(s_stringGetCharsMethod);
                    Ldc(10);
                    BneFar(doneLabel);
                    MarkLabel(l5);
                }
                return;
            case 21:
                Ldc(textSpanPos);
                Ldloca(textSpanLocal);
                Call(s_spanGetLengthMethod);
                BltUnFar(doneLabel);
                return;
            case 20:
                Ldc(textSpanPos);
                Ldloca(textSpanLocal);
                Call(s_spanGetLengthMethod);
                Ldc(1);
                Sub();
                BltFar(doneLabel);
                break;
            case 15:
                break;
            case 16:
            case 17:
                return;
            }
            Label l6 = DefineLabel();
            Ldc(textSpanPos);
            Ldloca(textSpanLocal);
            Call(s_spanGetLengthMethod);
            BgeUn(l6);
            Ldloca(textSpanLocal);
            Ldc(textSpanPos);
            Call(s_spanGetItemMethod);
            LdindU2();
            Ldc(10);
            BneFar(doneLabel);
            MarkLabel(l6);
        }
        void EmitAtomicAlternate(RegexNode node)
        {
            using RentedLocalBuilder rentedLocalBuilder5 = RentInt32Local();
            Ldloc(runtextposLocal);
            Stloc(rentedLocalBuilder5);
            int num2 = textSpanPos;
            RentedLocalBuilder? rentedLocalBuilder6 = null;
            if (((uint)node.Options & 0x80000000u) != 0)
            {
                rentedLocalBuilder6 = RentInt32Local();
                Ldthis();
                Call(s_crawlposMethod);
                RentedLocalBuilder? rentedLocalBuilder7 = rentedLocalBuilder6;
                Stloc(rentedLocalBuilder7.HasValue ? ((LocalBuilder)rentedLocalBuilder7.GetValueOrDefault()) : null);
            }
            Label l17 = DefineLabel();
            Label label4 = doneLabel;
            int num3 = node.ChildCount();
            for (int j = 0; j < num3 - 1; j++)
            {
                Label l18 = (doneLabel = DefineLabel());
                EmitNode(node.Child(j));
                TransferTextSpanPosToRunTextPos();
                BrFar(l17);
                MarkLabel(l18);
                Ldloc(rentedLocalBuilder5);
                Stloc(runtextposLocal);
                LoadTextSpanLocal();
                textSpanPos = num2;
                if (rentedLocalBuilder6.HasValue)
                {
                    RentedLocalBuilder? rentedLocalBuilder7 = rentedLocalBuilder6;
                    EmitUncaptureUntil(rentedLocalBuilder7.HasValue ? ((LocalBuilder)rentedLocalBuilder7.GetValueOrDefault()) : null);
                }
            }
            if (rentedLocalBuilder6.HasValue)
            {
                Label l19 = (doneLabel = DefineLabel());
                EmitNode(node.Child(num3 - 1));
                doneLabel = label4;
                TransferTextSpanPosToRunTextPos();
                Br(l17);
                MarkLabel(l19);
                RentedLocalBuilder? rentedLocalBuilder7 = rentedLocalBuilder6;
                EmitUncaptureUntil(rentedLocalBuilder7.HasValue ? ((LocalBuilder)rentedLocalBuilder7.GetValueOrDefault()) : null);
                BrFar(doneLabel);
            }
            else
            {
                doneLabel = label4;
                EmitNode(node.Child(num3 - 1));
                TransferTextSpanPosToRunTextPos();
            }
            MarkLabel(l17);
            rentedLocalBuilder6?.Dispose();
        }
        void EmitAtomicNodeLoop(RegexNode node)
        {
            if (node.M == node.N)
            {
                EmitNodeRepeater(node);
                return;
            }
            using RentedLocalBuilder rentedLocalBuilder2 = RentInt32Local();
            using RentedLocalBuilder rentedLocalBuilder3 = RentInt32Local();
            Label label2 = doneLabel;
            doneLabel = DefineLabel();
            TransferTextSpanPosToRunTextPos();
            Label l10 = DefineLabel();
            Label l11 = DefineLabel();
            int m2 = node.M;
            int n2 = node.N;
            Ldc(0);
            Stloc(rentedLocalBuilder2);
            BrFar(l10);
            MarkLabel(l11);
            EmitTimeoutCheck();
            Label l12 = DefineLabel();
            Label label3 = doneLabel;
            doneLabel = DefineLabel();
            Ldloc(runtextposLocal);
            Stloc(rentedLocalBuilder3);
            EmitNode(node.Child(0));
            TransferTextSpanPosToRunTextPos();
            Br(l12);
            MarkLabel(doneLabel);
            doneLabel = label3;
            Ldloc(rentedLocalBuilder3);
            Stloc(runtextposLocal);
            BrFar(doneLabel);
            MarkLabel(l12);
            Ldloc(rentedLocalBuilder2);
            Ldc(1);
            Add();
            Stloc(rentedLocalBuilder2);
            MarkLabel(l10);
            if (n2 != int.MaxValue)
            {
                Ldloc(rentedLocalBuilder2);
                Ldc(n2);
                BltFar(l11);
            }
            else
            {
                BrFar(l11);
            }
            MarkLabel(doneLabel);
            doneLabel = label2;
            if (m2 > 0)
            {
                Ldloc(rentedLocalBuilder2);
                Ldc(m2);
                BltFar(doneLabel);
            }
        }
        void EmitAtomicSingleCharZeroOrOne(RegexNode node)
        {
            Label l7 = DefineLabel();
            Ldc(textSpanPos);
            Ldloca(textSpanLocal);
            Call(s_spanGetLengthMethod);
            BgeUnFar(l7);
            Ldloca(textSpanLocal);
            Ldc(textSpanPos);
            Call(s_spanGetItemMethod);
            LdindU2();
            switch (node.Type)
            {
            case 43:
                if (IsCaseInsensitive(node) && ParticipatesInCaseConversion(node.Ch))
                {
                    CallToLower();
                }
                Ldc(node.Ch);
                BneFar(l7);
                break;
            case 44:
                if (IsCaseInsensitive(node) && ParticipatesInCaseConversion(node.Ch))
                {
                    CallToLower();
                }
                Ldc(node.Ch);
                BeqFar(l7);
                break;
            case 45:
                EmitMatchCharacterClass(node.Str, IsCaseInsensitive(node));
                BrfalseFar(l7);
                break;
            }
            Ldloca(textSpanLocal);
            Ldc(1);
            Call(s_spanSliceIntMethod);
            Stloc(textSpanLocal);
            Ldloc(runtextposLocal);
            Ldc(1);
            Add();
            Stloc(runtextposLocal);
            MarkLabel(l7);
        }
        void EmitBoundary(RegexNode node)
        {
            Ldthis();
            Ldloc(runtextposLocal);
            if (textSpanPos > 0)
            {
                Ldc(textSpanPos);
                Add();
            }
            Ldthisfld(s_runtextbegField);
            Ldloc(runtextendLocal);
            switch (node.Type)
            {
            case 16:
                Call(s_isBoundaryMethod);
                BrfalseFar(doneLabel);
                break;
            case 17:
                Call(s_isBoundaryMethod);
                BrtrueFar(doneLabel);
                break;
            case 41:
                Call(s_isECMABoundaryMethod);
                BrfalseFar(doneLabel);
                break;
            default:
                Call(s_isECMABoundaryMethod);
                BrtrueFar(doneLabel);
                break;
            }
        }
        void EmitCapture(RegexNode node)
        {
            using RentedLocalBuilder rentedLocalBuilder10 = RentInt32Local();
            int num5 = node.M;
            if (num5 != -1 && _code.Caps != null)
            {
                num5 = (int)_code.Caps[num5];
            }
            TransferTextSpanPosToRunTextPos();
            Ldloc(runtextposLocal);
            Stloc(rentedLocalBuilder10);
            EmitNode(node.Child(0));
            TransferTextSpanPosToRunTextPos();
            Ldthis();
            Ldc(num5);
            Ldloc(rentedLocalBuilder10);
            Ldloc(runtextposLocal);
            Call(s_captureMethod);
        }
        void EmitMultiChar(RegexNode node)
        {
            bool flag = IsCaseInsensitive(node);
            if (!flag && node.Str.Length > 64)
            {
                Ldloca(textSpanLocal);
                Ldc(textSpanPos);
                Call(s_spanSliceIntMethod);
                Ldstr(node.Str);
                Call(s_stringAsSpanMethod);
                Call(s_spanStartsWith);
                BrfalseFar(doneLabel);
                textSpanPos += node.Str.Length;
            }
            else
            {
                ReadOnlySpan<char> span = node.Str;
                EmitSpanLengthCheck(span.Length);
                if (!flag && !_persistsAssembly)
                {
                    if (IntPtr.Size == 8)
                    {
                        while (span.Length >= 4)
{
                            EmitTextSpanOffset();
                            Unaligned(1);
                            LdindI8();
                            LdcI8(MemoryMarshal.Read<long>(MemoryMarshal.AsBytes(span)));
                            BneFar(doneLabel);
                            textSpanPos += 4;
                            span = span.Slice(4);
                        }
                    }
                    while (span.Length >= 2)
                    {
                        EmitTextSpanOffset();
                        Unaligned(1);
                        LdindI4();
                        Ldc(MemoryMarshal.Read<int>(MemoryMarshal.AsBytes(span)));
                        BneFar(doneLabel);
                        textSpanPos += 2;
                        span = span.Slice(2);
                    }
                }
                for (int i = 0; i < span.Length; i++)
                {
                    EmitTextSpanOffset();
                    textSpanPos++;
                    LdindU2();
                    if (flag && ParticipatesInCaseConversion(span[i]))
                    {
                        CallToLower();
                    }
                    Ldc(span[i]);
                    BneFar(doneLabel);
                }
            }
        }
        void EmitNegativeLookaheadAssertion(RegexNode node)
        {
            using RentedLocalBuilder rentedLocalBuilder12 = RentInt32Local();
            Ldloc(runtextposLocal);
            Stloc(rentedLocalBuilder12);
            int num7 = textSpanPos;
            Label label5 = doneLabel;
            doneLabel = DefineLabel();
            EmitNode(node.Child(0));
            BrFar(label5);
            MarkLabel(doneLabel);
            doneLabel = label5;
            Ldloc(rentedLocalBuilder12);
            Stloc(runtextposLocal);
            LoadTextSpanLocal();
            textSpanPos = num7;
        }
        void EmitNode(RegexNode node)
        {
            switch (node.Type)
            {
            case 9:
            case 10:
            case 11:
                EmitSingleChar(node);
                break;
            case 16:
            case 17:
            case 41:
            case 42:
                EmitBoundary(node);
                break;
            case 14:
            case 15:
            case 18:
            case 19:
            case 20:
            case 21:
                EmitAnchors(node);
                break;
            case 12:
                EmitMultiChar(node);
                break;
            case 43:
            case 44:
            case 45:
                EmitSingleCharAtomicLoop(node);
                break;
            case 26:
                EmitAtomicNodeLoop(node);
                break;
            case 27:
                if (node.M > 0)
                {
                    EmitNodeRepeater(node);
                }
                break;
            case 32:
                EmitNode(node.Child(0));
                break;
            case 24:
                EmitAtomicAlternate(node);
                break;
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
                EmitSingleCharRepeater(node);
                break;
            case 25:
            {
                int num8 = node.ChildCount();
                for (int num9 = 0; num9 < num8; num9++)
                {
                    EmitNode(node.Child(num9));
                }
                break;
            }
            case 28:
                EmitCapture(node);
                break;
            case 30:
                EmitPositiveLookaheadAssertion(node);
                break;
            case 31:
                EmitNegativeLookaheadAssertion(node);
                break;
            case 22:
                BrFar(doneLabel);
                break;
            case 46:
                EmitUpdateBumpalong();
                break;
            case 13:
            case 23:
            case 29:
            case 33:
            case 34:
            case 35:
            case 36:
            case 37:
            case 38:
            case 39:
            case 40:
                break;
            }
        }
        void EmitNodeRepeater(RegexNode node)
        {
            int m3 = node.M;
            if (m3 == 1)
            {
                EmitNode(node.Child(0));
                return;
            }
            TransferTextSpanPosToRunTextPos();
            Label l13 = DefineLabel();
            Label l14 = DefineLabel();
            using RentedLocalBuilder rentedLocalBuilder4 = RentInt32Local();
            Ldc(0);
            Stloc(rentedLocalBuilder4);
            BrFar(l13);
            MarkLabel(l14);
            EmitTimeoutCheck();
            EmitNode(node.Child(0));
            TransferTextSpanPosToRunTextPos();
            Ldloc(rentedLocalBuilder4);
            Ldc(1);
            Add();
            Stloc(rentedLocalBuilder4);
            MarkLabel(l13);
            Ldloc(rentedLocalBuilder4);
            Ldc(m3);
            BltFar(l14);
        }
        void EmitPositiveLookaheadAssertion(RegexNode node)
        {
            using RentedLocalBuilder rentedLocalBuilder11 = RentInt32Local();
            Ldloc(runtextposLocal);
            Stloc(rentedLocalBuilder11);
            int num6 = textSpanPos;
            EmitNode(node.Child(0));
            Ldloc(rentedLocalBuilder11);
            Stloc(runtextposLocal);
            LoadTextSpanLocal();
            textSpanPos = num6;
        }
        void EmitSingleChar(RegexNode node, bool emitLengthCheck = true, LocalBuilder offset = null)
        {
            if (emitLengthCheck)
            {
                EmitSpanLengthCheck(1, offset);
            }
            Ldloca(textSpanLocal);
            EmitSum(textSpanPos, offset);
            Call(s_spanGetItemMethod);
            LdindU2();
            switch (node.Type)
            {
            case 5:
            case 8:
            case 11:
            case 45:
                EmitMatchCharacterClass(node.Str, IsCaseInsensitive(node));
                BrfalseFar(doneLabel);
                break;
            case 3:
            case 6:
            case 9:
            case 43:
                if (IsCaseInsensitive(node) && ParticipatesInCaseConversion(node.Ch))
                {
                    CallToLower();
                }
                Ldc(node.Ch);
                BneFar(doneLabel);
                break;
            default:
                if (IsCaseInsensitive(node) && ParticipatesInCaseConversion(node.Ch))
                {
                    CallToLower();
                }
                Ldc(node.Ch);
                BeqFar(doneLabel);
                break;
            }
            textSpanPos++;
        }
        void EmitSingleCharAtomicLoop(RegexNode node)
        {
            if (node.M == node.N)
            {
                EmitSingleCharRepeater(node);
            }
            else
            {
                if (node.M != 0 || node.N != 1)
                {
                    int m = node.M;
                    int n = node.N;
                    using RentedLocalBuilder rentedLocalBuilder = RentInt32Local();
                    Label label = doneLabel;
                    doneLabel = DefineLabel();
                    Span<char> chars = stackalloc char[3];
                    int num = 0;
                    if (node.Type == 44 && n == int.MaxValue && (!IsCaseInsensitive(node) || !ParticipatesInCaseConversion(node.Ch)))
                    {
                        if (textSpanPos > 0)
{
                            Ldloca(textSpanLocal);
                            Ldc(textSpanPos);
                            Call(s_spanSliceIntMethod);
                        }
                        else
{
                            Ldloc(textSpanLocal);
                        }
                        Ldc(node.Ch);
                        Call(s_spanIndexOf);
                        Stloc(rentedLocalBuilder);
                        Ldloc(rentedLocalBuilder);
                        Ldc(-1);
                        BneFar(doneLabel);
                        Ldloca(textSpanLocal);
                        Call(s_spanGetLengthMethod);
                        if (textSpanPos > 0)
{
                            Ldc(textSpanPos);
                            Sub();
                        }
                        Stloc(rentedLocalBuilder);
                    }
                    else if (node.Type == 45 && n == int.MaxValue && !IsCaseInsensitive(node) && (num = RegexCharClass.GetSetChars(node.Str, chars)) > 1 && RegexCharClass.IsNegated(node.Str))
                    {
                        if (textSpanPos > 0)
{
                            Ldloca(textSpanLocal);
                            Ldc(textSpanPos);
                            Call(s_spanSliceIntMethod);
                        }
                        else
{
                            Ldloc(textSpanLocal);
                        }
                        Ldc(chars[0]);
                        Ldc(chars[1]);
                        if (num == 2)
{
                            Call(s_spanIndexOfAnyCharChar);
                        }
                        else
{
                            Ldc(chars[2]);
                            Call(s_spanIndexOfAnyCharCharChar);
                        }
                        Stloc(rentedLocalBuilder);
                        Ldloc(rentedLocalBuilder);
                        Ldc(-1);
                        BneFar(doneLabel);
                        Ldloca(textSpanLocal);
                        Call(s_spanGetLengthMethod);
                        if (textSpanPos > 0)
{
                            Ldc(textSpanPos);
                            Sub();
                        }
                        Stloc(rentedLocalBuilder);
                    }
                    else if (node.Type == 45 && n == int.MaxValue && node.Str == "\0\u0001\0\0")
                    {
                        TransferTextSpanPosToRunTextPos();
                        Ldloc(runtextendLocal);
                        Ldloc(runtextposLocal);
                        Sub();
                        Stloc(rentedLocalBuilder);
                    }
                    else
                    {
                        TransferTextSpanPosToRunTextPos();
                        Label l8 = DefineLabel();
                        Label l9 = DefineLabel();
                        Ldc(0);
                        Stloc(rentedLocalBuilder);
                        BrFar(l8);
                        MarkLabel(l9);
                        EmitTimeoutCheck();
                        Ldloc(rentedLocalBuilder);
                        Ldloca(textSpanLocal);
                        Call(s_spanGetLengthMethod);
                        BgeUnFar(doneLabel);
                        Ldloca(textSpanLocal);
                        Ldloc(rentedLocalBuilder);
                        Call(s_spanGetItemMethod);
                        LdindU2();
                        switch (node.Type)
{
                        case 43:
                            if (IsCaseInsensitive(node) && ParticipatesInCaseConversion(node.Ch))
{
                                CallToLower();
                            }
                            Ldc(node.Ch);
                            BneFar(doneLabel);
                            break;
                        case 44:
                            if (IsCaseInsensitive(node) && ParticipatesInCaseConversion(node.Ch))
{
                                CallToLower();
                            }
                            Ldc(node.Ch);
                            BeqFar(doneLabel);
                            break;
                        case 45:
                            EmitMatchCharacterClass(node.Str, IsCaseInsensitive(node));
                            BrfalseFar(doneLabel);
                            break;
                        }
                        Ldloc(rentedLocalBuilder);
                        Ldc(1);
                        Add();
                        Stloc(rentedLocalBuilder);
                        MarkLabel(l8);
                        if (n != int.MaxValue)
{
                            Ldloc(rentedLocalBuilder);
                            Ldc(n);
                            BltFar(l9);
                        }
                        else
{
                            BrFar(l9);
                        }
                    }
                    MarkLabel(doneLabel);
                    doneLabel = label;
                    if (m > 0)
                    {
                        Ldloc(rentedLocalBuilder);
                        Ldc(m);
                        BltFar(doneLabel);
                    }
                    Ldloca(textSpanLocal);
                    Ldloc(rentedLocalBuilder);
                    Call(s_spanSliceIntMethod);
                    Stloc(textSpanLocal);
                    Ldloc(runtextposLocal);
                    Ldloc(rentedLocalBuilder);
                    Add();
                    Stloc(runtextposLocal);
                    return;
                }
                EmitAtomicSingleCharZeroOrOne(node);
            }
        }
        void EmitSingleCharRepeater(RegexNode node)
        {
            int m4 = node.M;
            if (m4 != 0)
            {
                EmitSpanLengthCheck(m4);
                if (m4 > 16)
                {
                    Label l20 = DefineLabel();
                    Label l21 = DefineLabel();
                    using RentedLocalBuilder rentedLocalBuilder8 = RentReadOnlySpanCharLocal();
                    Ldloca(textSpanLocal);
                    Ldc(textSpanPos);
                    Ldc(m4);
                    Call(s_spanSliceIntIntMethod);
                    Stloc(rentedLocalBuilder8);
                    using RentedLocalBuilder rentedLocalBuilder9 = RentInt32Local();
                    Ldc(0);
                    Stloc(rentedLocalBuilder9);
                    BrFar(l20);
                    MarkLabel(l21);
                    EmitTimeoutCheck();
                    LocalBuilder localBuilder = textSpanLocal;
                    int num4 = textSpanPos;
                    textSpanLocal = rentedLocalBuilder8;
                    textSpanPos = 0;
                    EmitSingleChar(node, emitLengthCheck: false, rentedLocalBuilder9);
                    textSpanLocal = localBuilder;
                    textSpanPos = num4;
                    Ldloc(rentedLocalBuilder9);
                    Ldc(1);
                    Add();
                    Stloc(rentedLocalBuilder9);
                    MarkLabel(l20);
                    Ldloc(rentedLocalBuilder9);
                    Ldloca(rentedLocalBuilder8);
                    Call(s_spanGetLengthMethod);
                    BltFar(l21);
                    textSpanPos += m4;
                    return;
                }
                for (int k = 0; k < m4; k++)
                {
                    EmitSingleChar(node, emitLengthCheck: false);
                }
            }
        }
        void EmitSpanLengthCheck(int requiredLength, LocalBuilder dynamicRequiredLength = null)
        {
            EmitSum(textSpanPos + requiredLength - 1, dynamicRequiredLength);
            Ldloca(textSpanLocal);
            Call(s_spanGetLengthMethod);
            BgeUnFar(doneLabel);
        }
        void EmitSum(int constant, LocalBuilder local)
        {
            if (local == null)
            {
                Ldc(constant);
            }
            else if (constant == 0)
            {
                Ldloc(local);
            }
            else
            {
                Ldloc(local);
                Ldc(constant);
                Add();
            }
        }
        void EmitTextSpanOffset()
        {
            Ldloc(textSpanLocal);
            Call(s_memoryMarshalGetReference);
            if (textSpanPos > 0)
            {
                Ldc(textSpanPos * 2);
                Add();
            }
        }
        void EmitUncaptureUntil(LocalBuilder startingCrawlpos)
        {
            Label l15 = DefineLabel();
            Label l16 = DefineLabel();
            Br(l15);
            MarkLabel(l16);
            Ldthis();
            Call(s_uncaptureMethod);
            MarkLabel(l15);
            Ldthis();
            Call(s_crawlposMethod);
            Ldloc(startingCrawlpos);
            Bne(l16);
        }
        void EmitUpdateBumpalong()
        {
            TransferTextSpanPosToRunTextPos();
            Ldthis();
            Ldloc(runtextposLocal);
            Stfld(s_runtextposField);
        }
        static bool IsCaseInsensitive(RegexNode node)
        {
            return (node.Options & RegexOptions.IgnoreCase) != 0;
        }
        void LoadTextSpanLocal()
        {
            Ldloc(runtextLocal);
            Ldloc(runtextposLocal);
            Ldloc(runtextendLocal);
            Ldloc(runtextposLocal);
            Sub();
            Call(s_stringAsSpanIntIntMethod);
            Stloc(textSpanLocal);
        }
        static bool NodeSupportsNonBacktrackingImplementation(RegexNode node, int maxDepth)
        {
            bool flag2 = false;
            if ((node.Options & RegexOptions.RightToLeft) == 0 && maxDepth > 0)
            {
                int num10 = node.ChildCount();
                switch (node.Type)
                {
                case 9:
                case 10:
                case 11:
                case 12:
                case 14:
                case 15:
                case 16:
                case 17:
                case 18:
                case 19:
                case 20:
                case 21:
                case 22:
                case 23:
                case 41:
                case 42:
                case 43:
                case 44:
                case 45:
                case 46:
                    flag2 = true;
                    break;
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                    flag2 = node.M == node.N || (node.Next != null && node.Next.Type == 32);
                    break;
                case 26:
                case 27:
                    flag2 = (node.M == node.N || (node.Next != null && node.Next.Type == 32)) && NodeSupportsNonBacktrackingImplementation(node.Child(0), maxDepth - 1);
                    break;
                case 30:
                case 31:
                case 32:
                    flag2 = NodeSupportsNonBacktrackingImplementation(node.Child(0), maxDepth - 1);
                    break;
                case 24:
                    if (node.Next == null || (!node.IsAtomicByParent() && (node.Next.Type != 28 || node.Next.Next != null)))
                    {
                        break;
                    }
                    goto case 25;
                case 25:
                {
                    flag2 = true;
                    for (int num11 = 0; num11 < num10; num11++)
                    {
                        if (flag2 && !NodeSupportsNonBacktrackingImplementation(node.Child(num11), maxDepth - 1))
{
                            flag2 = false;
                            break;
                        }
                    }
                    break;
                }
                case 28:
                    flag2 = node.N == -1;
                    if (flag2)
                    {
                        RegexNode regexNode = node.Next;
                        while (regexNode != null)
{
                            switch (regexNode.Type)
{
                            case 24:
                            case 25:
                            case 28:
                            case 30:
                            case 32:
                                regexNode = regexNode.Next;
                                break;
                            default:
                                regexNode = null;
                                flag2 = false;
                                break;
                            }
                        }
                        if (flag2)
{
                            flag2 = NodeSupportsNonBacktrackingImplementation(node.Child(0), maxDepth - 1);
                            if (flag2)
{
                                regexNode = node;
                                while (regexNode != null && (regexNode.Options & (RegexOptions)(-2147483648)) == 0)
{
                                    regexNode.Options |= (RegexOptions)(-2147483648);
                                    regexNode = regexNode.Next;
                                }
                            }
                        }
                    }
                    break;
                }
            }
            return flag2;
        }
        void TransferTextSpanPosToRunTextPos()
        {
            if (textSpanPos > 0)
            {
                Ldloc(runtextposLocal);
                Ldc(textSpanPos);
                Add();
                Stloc(runtextposLocal);
                Ldloca(textSpanLocal);
                Ldc(textSpanPos);
                Call(s_spanSliceIntMethod);
                Stloc(textSpanLocal);
                textSpanPos = 0;
            }
        }
    }
References System.Text.RegularExpressions.RegexCompiler._code, System.Text.RegularExpressions.RegexCompiler._hasTimeout, System.Text.RegularExpressions.RegexCompiler._loopTimeoutCounterLocal, System.Text.RegularExpressions.RegexCompiler._persistsAssembly, System.Text.RegularExpressions.RegexCompiler.Add(), System.Text.RegularExpressions.RegexCompiler.BeqFar(), System.Text.RegularExpressions.RegexCompiler.BgeUn(), System.Text.RegularExpressions.RegexCompiler.BgeUnFar(), System.Reflection.Emit.Ble, System.Text.RegularExpressions.RegexCompiler.BltFar(), System.Text.RegularExpressions.RegexCompiler.BltUnFar(), System.Text.RegularExpressions.RegexCompiler.Bne(), System.Text.RegularExpressions.RegexCompiler.BneFar(), System.Reflection.Emit.Br, System.Text.RegularExpressions.RegexCompiler.BrfalseFar(), System.Text.RegularExpressions.RegexCompiler.BrFar(), System.Reflection.Emit.Brtrue, System.Text.RegularExpressions.RegexCompiler.BrtrueFar(), System.Reflection.Emit.Call, System.Text.RegularExpressions.RegexCompiler.CallToLower(), System.Text.RegularExpressions.RegexCode.Caps, System.chars, System.Text.RegularExpressions.RegexCompiler.DeclareInt32(), System.Text.RegularExpressions.RegexCompiler.DeclareReadOnlySpanChar(), System.Text.RegularExpressions.RegexCompiler.DeclareString(), System.Text.RegularExpressions.RegexCompiler.DefineLabel(), System.Text.RegularExpressions.RegexCompiler.EmitMatchCharacterClass(), System.Text.RegularExpressions.RegexCompiler.EmitTimeoutCheck(), System.Text.RegularExpressions.RegexCharClass.GetSetChars(), System.Text.RegularExpressions.i, System.Text.RegularExpressions.RegexCompiler.InitializeCultureForGoIfNecessary(), System.Text.RegularExpressions.RegexCompiler.IsCaseInsensitive(), System.Text.RegularExpressions.RegexCharClass.IsNegated(), System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Text.RegularExpressions.RegexCompiler.LdcI8(), System.Text.RegularExpressions.RegexCompiler.LdindI4(), System.Text.RegularExpressions.RegexCompiler.LdindI8(), System.Text.RegularExpressions.RegexCompiler.LdindU2(), System.Reflection.Emit.Ldloc, System.Reflection.Emit.Ldloca, System.Reflection.Emit.Ldstr, System.Text.RegularExpressions.RegexCompiler.Ldthis(), System.Text.RegularExpressions.RegexCompiler.Ldthisfld(), System.Text.RegularExpressions.RegexCompiler.MarkLabel(), System.Reflection.MaxValue, System.Text.RegularExpressions.RegexCompiler.Mvfldloc(), System.offset, System.Text.RegularExpressions.RegexCompiler.ParticipatesInCaseConversion(), System.Text.RegularExpressions.RegexCompiler.RentInt32Local(), System.Text.RegularExpressions.RegexCompiler.RentReadOnlySpanCharLocal(), System.Text.RegularExpressions.RegexCompiler.Ret(), System.Text.RegularExpressions.RegexCompiler.s_captureMethod, System.Text.RegularExpressions.RegexCompiler.s_crawlposMethod, System.Text.RegularExpressions.RegexCompiler.s_isBoundaryMethod, System.Text.RegularExpressions.RegexCompiler.s_isECMABoundaryMethod, System.Text.RegularExpressions.RegexCompiler.s_memoryMarshalGetReference, System.Text.RegularExpressions.RegexCompiler.s_runtextbegField, System.Text.RegularExpressions.RegexCompiler.s_runtextendField, System.Text.RegularExpressions.RegexCompiler.s_runtextField, System.Text.RegularExpressions.RegexCompiler.s_runtextposField, System.Text.RegularExpressions.RegexCompiler.s_runtextstartField, System.Text.RegularExpressions.RegexCompiler.s_spanGetItemMethod, System.Text.RegularExpressions.RegexCompiler.s_spanGetLengthMethod, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOf, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOfAnyCharChar, System.Text.RegularExpressions.RegexCompiler.s_spanIndexOfAnyCharCharChar, System.Text.RegularExpressions.RegexCompiler.s_spanSliceIntIntMethod, System.Text.RegularExpressions.RegexCompiler.s_spanSliceIntMethod, System.Text.RegularExpressions.RegexCompiler.s_spanStartsWith, System.Text.RegularExpressions.RegexCompiler.s_stringAsSpanIntIntMethod, System.Text.RegularExpressions.RegexCompiler.s_stringAsSpanMethod, System.Text.RegularExpressions.RegexCompiler.s_stringGetCharsMethod, System.Text.RegularExpressions.RegexCompiler.s_uncaptureMethod, System.IntPtr.Size, System.Reflection.Emit.Stfld, System.Reflection.Emit.Stloc, System.Text.RegularExpressions.RegexCompiler.Sub(), and System.Text.RegularExpressions.RegexCompiler.Unaligned().
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateGo().