Terraria: System.Text.RegularExpressions.RegexCompiler.GenerateGo
GenerateGo()
void System.Text.RegularExpressions.RegexCompiler.GenerateGo () inline protected inherited
Definition at line 2637 of file RegexCompiler.cs.
    {
        _int32LocalsPool?.Clear();
        _readOnlySpanCharLocalsPool?.Clear();
        if (!TryGenerateNonBacktrackingGo(_code.Tree.Root))
        {
            _runtextposLocal = DeclareInt32();
            _runtextLocal = DeclareString();
            _runtrackposLocal = DeclareInt32();
            _runtrackLocal = DeclareInt32Array();
            _runstackposLocal = DeclareInt32();
            _runstackLocal = DeclareInt32Array();
            if (_hasTimeout)
            {
                _loopTimeoutCounterLocal = DeclareInt32();
            }
            _runtextbegLocal = DeclareInt32();
            _runtextendLocal = DeclareInt32();
            InitializeCultureForGoIfNecessary();
            _labels = null;
            _notes = null;
            _notecount = 0;
            _backtrack = DefineLabel();
            GenerateForwardSection();
            GenerateMiddleSection();
            GenerateBacktrackSection();
        }
    }
References System.Text.RegularExpressions.RegexCompiler._backtrack, System.Text.RegularExpressions.RegexCompiler._code, System.Text.RegularExpressions.RegexCompiler._hasTimeout, System.Text.RegularExpressions.RegexCompiler._int32LocalsPool, System.Text.RegularExpressions.RegexCompiler._labels, System.Text.RegularExpressions.RegexCompiler._loopTimeoutCounterLocal, System.Text.RegularExpressions.RegexCompiler._notecount, System.Text.RegularExpressions.RegexCompiler._notes, System.Text.RegularExpressions.RegexCompiler._readOnlySpanCharLocalsPool, System.Text.RegularExpressions.RegexCompiler._runstackLocal, System.Text.RegularExpressions.RegexCompiler._runstackposLocal, System.Text.RegularExpressions.RegexCompiler._runtextbegLocal, System.Text.RegularExpressions.RegexCompiler._runtextendLocal, System.Text.RegularExpressions.RegexCompiler._runtextLocal, System.Text.RegularExpressions.RegexCompiler._runtextposLocal, System.Text.RegularExpressions.RegexCompiler._runtrackLocal, System.Text.RegularExpressions.RegexCompiler._runtrackposLocal, System.Collections.Generic.Stack< T >.Clear(), System.Text.RegularExpressions.RegexCompiler.DeclareInt32(), System.Text.RegularExpressions.RegexCompiler.DeclareInt32Array(), System.Text.RegularExpressions.RegexCompiler.DeclareString(), System.Text.RegularExpressions.RegexCompiler.DefineLabel(), System.Text.RegularExpressions.RegexCompiler.GenerateBacktrackSection(), System.Text.RegularExpressions.RegexCompiler.GenerateForwardSection(), System.Text.RegularExpressions.RegexCompiler.GenerateMiddleSection(), System.Text.RegularExpressions.RegexCompiler.InitializeCultureForGoIfNecessary(), System.Text.RegularExpressions.RegexTree.Root, System.Text.RegularExpressions.RegexCode.Tree, and System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo().
Referenced by System.Text.RegularExpressions.RegexLWCGCompiler.FactoryInstanceFromCode().