Terraria: System.Text.RegularExpressions.RegexCompiler.EmitTimeoutCheck
EmitTimeoutCheck()
void System.Text.RegularExpressions.RegexCompiler.EmitTimeoutCheck () inline private inherited
Definition at line 4095 of file RegexCompiler.cs.
    {
        if (_hasTimeout)
        {
            Ldloc(_loopTimeoutCounterLocal);
            Ldc(1);
            Add();
            Stloc(_loopTimeoutCounterLocal);
            Label l = DefineLabel();
            Ldloc(_loopTimeoutCounterLocal);
            Ldc(2048);
            RemUn();
            Brtrue(l);
            Ldthis();
            Call(s_checkTimeoutMethod);
            MarkLabel(l);
        }
    }
References System.Text.RegularExpressions.RegexCompiler._hasTimeout, System.Text.RegularExpressions.RegexCompiler._loopTimeoutCounterLocal, System.Text.RegularExpressions.RegexCompiler.Add(), System.Reflection.Emit.Brtrue, System.Reflection.Emit.Call, System.Text.RegularExpressions.RegexCompiler.DefineLabel(), System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Reflection.Emit.Ldloc, System.Text.RegularExpressions.RegexCompiler.Ldthis(), System.Text.RegularExpressions.RegexCompiler.MarkLabel(), System.Text.RegularExpressions.RegexCompiler.RemUn(), System.Text.RegularExpressions.RegexCompiler.s_checkTimeoutMethod, and System.Reflection.Emit.Stloc.
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), and System.Text.RegularExpressions.RegexCompiler.TryGenerateNonBacktrackingGo().