Terraria: System.Lazy.ViaConstructor
ViaConstructor()
void System.Lazy< T, TMetadata >.ViaConstructor () inline private
Definition at line 98 of file Lazy.cs.
    {
        _value = CreateViaDefaultConstructor();
        _state = null;
    }
References System.Lazy< T, TMetadata >._state, System.Lazy< T, TMetadata >._value, and System.Lazy< T, TMetadata >.CreateViaDefaultConstructor().
Referenced by System.Lazy< T, TMetadata >.CreateValue(), and System.Lazy< T, TMetadata >.ExecutionAndPublication().