Terraria: System.Text.RegularExpressions.RegexCompiler.ReadyPushStack
ReadyPushStack()
void System.Text.RegularExpressions.RegexCompiler.ReadyPushStack () inline private inherited
Definition at line 811 of file RegexCompiler.cs.
    {
        Ldloc(_runstackposLocal);
        Ldc(1);
        Sub();
        Stloc(_runstackposLocal);
        Ldloc(_runstackLocal);
        Ldloc(_runstackposLocal);
    }
References System.Text.RegularExpressions.RegexCompiler._runstackLocal, System.Text.RegularExpressions.RegexCompiler._runstackposLocal, System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Reflection.Emit.Ldloc, System.Reflection.Emit.Stloc, and System.Text.RegularExpressions.RegexCompiler.Sub().
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateOneCode(), and System.Text.RegularExpressions.RegexCompiler.PushStack().