Terraria: System.Text.RegularExpressions.RegexCompiler.Leftchar
Leftchar()
void System.Text.RegularExpressions.RegexCompiler.Leftchar () inline private inherited
Definition at line 707 of file RegexCompiler.cs.
    {
        Ldloc(_runtextLocal);
        Ldloc(_runtextposLocal);
        Ldc(1);
        Sub();
        Call(s_stringGetCharsMethod);
    }
References System.Text.RegularExpressions.RegexCompiler._runtextLocal, System.Text.RegularExpressions.RegexCompiler._runtextposLocal, System.Reflection.Emit.Call, System.Text.RegularExpressions.RegexCompiler.Ldc(), System.Reflection.Emit.Ldloc, System.Text.RegularExpressions.RegexCompiler.s_stringGetCharsMethod, and System.Text.RegularExpressions.RegexCompiler.Sub().
Referenced by System.Text.RegularExpressions.RegexCompiler.GenerateOneCode().