Terraria: Terraria.RemoteClient.TryRead
TryRead()
void Terraria.RemoteClient.TryRead () inline private
    {
        if (_isReading)
        {
            return;
        }
        try
        {
            if (Socket.IsDataAvailable())
            {
                _isReading = true;
                Socket.AsyncReceive(ReadBuffer, 0, ReadBuffer.Length, ServerReadCallBack);
            }
        }
        catch
        {
            PendingTermination = true;
        }
    }
References Terraria.RemoteClient._isReading, Terraria.Net.Sockets.ISocket.AsyncReceive(), Terraria.Net.Sockets.ISocket.IsDataAvailable(), Terraria.RemoteClient.PendingTermination, Terraria.RemoteClient.ReadBuffer, Terraria.RemoteClient.ServerReadCallBack(), and Terraria.RemoteClient.Socket.
Referenced by Terraria.RemoteClient.Update().