Terraria: System.Threading.Interlocked.Add
Add() [1/4]
static int System.Threading.Interlocked.Add (ref int location1, int value) inline static
Definition at line 78 of file Interlocked.cs.
    {
        return ExchangeAdd(ref location1, value) + value;
    }
References System.Threading.Interlocked.ExchangeAdd(), and System.value.
Referenced by System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Runtime.MemoryFailPoint.AddMemoryFailPointReservation(), System.Runtime.MemoryFailPoint.AddToLastKnownFreeAddressSpace(), System.Net.Sockets.SocketsTelemetry.BytesReceived(), System.Net.Sockets.SocketsTelemetry.BytesSent(), System.Threading.SpinLock.ContinueTryEnter(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.EnsureFrozenForEnqueues(), System.Threading.ReaderWriterLockSlim.SpinLock.EnterSpin(), System.Threading.Tasks.RangeWorker.FindNewWork(), System.Threading.LowLevelLifoSemaphore.Counts.InterlockedDecrementWaiterCount(), System.IO.Strategies.OSFileStreamStrategy.OnIncompleteOperation(), System.IO.Strategies.OSFileStreamStrategy.ReadAsync(), System.Threading.ReaderWriterLock.ReleaseEvents(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.TryCopyFromFillBuffer(), System.Threading.LowLevelLock.WaitAndAcquire(), and System.IO.Strategies.OSFileStreamStrategy.WriteAsync().