Terraria: System.Threading.Interlocked.MemoryBarrier
MemoryBarrier()
static void System.Threading.Interlocked.MemoryBarrier ()
Referenced by System.Transactions.Bucket.Add(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.AddMessage(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.AddMessages(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.EnsureMethodsImported(), System.Collections.Concurrent.ConcurrentBag< T >.FreezeBag(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers(), System.Runtime.Serialization.EnumDataContract.EnumDataContractCriticalHelper.ImportDataMembers(), System.Threading.Thread.MemoryBarrier(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.OfferMessage_Slow(), System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferMessagesLoopCore(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.Post(), System.Transactions.Bucket.TimeoutTransactions(), and System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryPeek().