Terraria: System.Threading.Interlocked.Decrement
Decrement() [1/4]
static int System.Threading.Interlocked.Decrement (ref int location) inline static
Definition at line 20 of file Interlocked.cs.
    {
        return Add(ref location, -1);
    }
References System.Add.
Referenced by System.Net.NameResolutionTelemetry.AfterResolution(), System.Net.Security.NetSecurityTelemetry.ConnectionClosed(), System.Net.Mime.MultiAsyncResult.Decrement(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerator.Dispose(), System.Linq.Parallel.PartitionedDataSource< T >.ContiguousChunkLazyEnumerator.Dispose(), System.Threading.Tasks.Task< TResult >.DisregardChild(), System.Net.WebClient.EndOperation(), System.Threading.AsyncMutex.EnterAsync(), System.Transactions.CheapUnfairReaderWriterLock.EnterReadLock(), System.Threading.SpinLock.Exit(), System.Threading.SpinLock.ExitSlowPath(), System.Threading.Tasks.Task< TResult >.FinishSlow(), System.IO.RandomAccess.CallbackResetEvent.FreeNativeOverlapped(), System.Threading.PortableThreadPool.GateThread.GateThreadStart(), System.Net.Http.HttpTelemetry.Http11ConnectionClosed(), System.Net.Http.HttpTelemetry.Http20ConnectionClosed(), System.Threading.PortableThreadPool.ThreadCounts.InterlockedDecrementNumProcessingWork(), System.Transactions.CommittableTransaction.InternalDispose(), System.Transactions.Transaction.InternalDispose(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke(), System.Threading.Tasks.Task< TResult >.SetOnCountdownMres.Invoke(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.Invoke(), System.Threading.Tasks.Task< TResult >.WhenAllPromise< T >.Invoke(), ReLogic.Content.AssetRepository.LoadAssetWithPotentialAsync< T >(), System.Threading.Tasks.Task< TResult >.ProcessChildCompletion(), System.IO.Compression.DeflateManagedStream.ReadAsyncCore(), System.IO.Compression.DeflateManagedStream.ReadAsyncInternal(), System.Threading.LowLevelLock.Release(), System.Runtime.InteropServices.HandleCollector.Remove(), System.Threading.CountdownEvent.Signal(), System.Threading.Tasks.Parallel.ForEachAsyncState< TSource >.SignalWorkerCompletedIterating(), System.Threading.LowLevelSpinWaiter.SpinWaitForCondition(), System.Collections.Concurrent.BlockingCollection< T >.TryAddWithNoTimeValidation(), and System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.TryCopyFromFillBuffer().