Terraria: System.Threading.Interlocked.Exchange
Exchange() [4/8]
static int System.Threading.Interlocked.Exchange (ref int location1, int value)
Referenced by System.Net.HttpWebRequest.Abort(), System.Net.Sockets.Socket.AcceptAsync(), System.IO.Compression.BrotliStream.AsyncOperationStarting(), System.IO.Compression.DeflateStream.AsyncOperationStarting(), System.Net.Security.NegotiateStream.AuthenticateAsync< TAdapter >(), System.Net.HttpWebRequest.BeginGetRequestStream(), System.Net.HttpWebRequest.BeginGetResponse(), System.Net.Security.SSPIHandleCache.CacheCredential(), System.Net.Security.SSPIHandleCache.CacheCredential(), System.Net.TimerThread.InfiniteTimer.Cancel(), System.Threading.Tasks.Task< TResult >.CancellationCleanupLogic(), System.Net.Http.HttpClient.CancelPendingRequests(), System.IO.StreamBuffer.ResettableValueTaskSource.CancelWaiter(), System.Net.Http.FailedProxyCache.CleanupHelper(), System.IO.Enumeration.FileSystemEnumerator< TResult >.CloseDirectoryHandle(), System.Net.Security.SslStream.CloseInternal(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Complete(), System.Net.Sockets.TcpClient.Connect(), System.Net.Sockets.Socket.ConnectAsync(), System.Threading.PortableThreadPool.GateThread.CreateGateThread(), System.Net.Sockets.Socket.DisconnectAsync(), System.Diagnostics.DiagnosticListener.Dispose(), System.Net.WebSockets.ClientWebSocket.Dispose(), System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Enumerator.Dispose(), System.Text.Json.JsonDocument.MetadataDb.Dispose(), System.Text.Json.JsonDocument.Dispose(), System.IO.Pipes.NamedPipeServerStream.Dispose(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.Dispose(), System.Net.Http.Http2Connection.Http2Stream.Http2WriteStream.Dispose(), System.Net.Http.Http3RequestStream.Http3ReadStream.Dispose(), System.Net.Http.HttpConnection.HttpContentReadStream.Dispose(), System.Net.Http.HttpConnection.Dispose(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.Dispose(), System.Net.RequestContextBase.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose(), System.Net.Sockets.NetworkStream.Dispose(), System.Threading.CancellationTokenSource.Dispose(), System.Reflection.Internal.ByteArrayMemoryProvider.Dispose(), System.Reflection.Internal.StreamMemoryBlockProvider.Dispose(), System.Net.Http.Http3RequestStream.Http3ReadStream.DisposeAsync(), System.Net.Sockets.Socket.DisposeCachedTaskSocketAsyncEventArgs(), System.IO.Pipes.PipeStream.DisposeCore(), System.Net.Http.Http3RequestStream.DisposeSyncHelper(), System.Net.HttpWebRequest.EndGetRequestStream(), System.Net.HttpWebRequest.EndGetResponse(), System.Linq.Parallel.AsynchronousChannel< T >.EnqueueChunk(), System.Net.WebProxy.EnsureNetworkChangeRegistration(), System.Threading.PortableThreadPool.GateThread.EnsureRunningSlow(), System.Threading.CancellationTokenSource.Registrations.EnterLock(), System.Threading.Interlocked.Exchange(), System.Threading.Interlocked.Exchange(), System.Threading.Interlocked.Exchange(), System.Threading.Interlocked.Exchange< T >(), System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(), System.Threading.Tasks.Task< TResult >.ExecuteEntryCancellationRequestedOrCanceled(), System.Threading.SpinLock.ExitSlowPath(), System.Net.Http.Http2Connection.FinalTeardown(), System.Threading.Tasks.RangeWorker.FindNewWork(), System.Threading.Tasks.Task< TResult >.FinishContinuations(), System.IO.Pipes.PipeStream.PipeValueTaskSource.FinishedScheduling(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.FinishedScheduling(), System.Threading.Tasks.Task< TResult >.FinishStageTwo(), System.Diagnostics.Tracing.EventCounter.Flush(), System.Net.Security.SslStream.ForceAuthenticationAsync< TIOAdapter >(), System.Runtime.InteropServices.GCHandle.Free(), System.IO.Enumeration.FileSystemEnumerable< TResult >.GetEnumerator(), System.Runtime.CompilerServices.CallSite< T >.GetMatchmaker(), Microsoft.Win32.SafeHandles.SafeFileHandle.GetOverlappedValueTaskSource(), System.Diagnostics.NtProcessInfoHelper.GetProcessInfos(), Microsoft.Win32.SafeHandles.SafeFileHandle.GetThreadPoolValueTaskSource(), System.Net.Http.Http3RequestStream.GoAway(), System.Net.HttpListener.DisconnectAsyncResult.HandleDisconnect(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.InitializeTlsBucketsAndTrimming(), System.Collections.Immutable.ImmutableInterlocked.InterlockedExchange< T >(), System.Linq.Parallel.AsynchronousChannel< T >.InternalDequeueChunk(), System.Transactions.CommittableTransaction.InternalDispose(), System.Transactions.Transaction.InternalDispose(), System.Threading.Tasks.Task< TResult >.TwoTaskWhenAnyPromise< TTask >.Invoke(), System.Threading.Tasks.TaskFactory< TResult >.CompleteOnInvokePromise.Invoke(), System.IO.Pipes.PipeStream.PipeValueTaskSource.IOCallback(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.IOCallback(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.IOCallback(), System.Net.HttpListener.DisconnectAsyncResult.IOCompleted(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPopCore(), System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.LocalPush(), ReLogic.Content.RunOnceAction.OnlyRunnableOnce(), System.Net.WebSockets.WebSocketBuffer.PinSendBuffer(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ProcessMessagesLoopCore(), System.Net.Http.Http3Connection.ProcessServerStreamAsync(), System.Linq.Parallel.QueryTaskGroupState.QueryEnd(), System.Runtime.Loader.AssemblyLoadContext.RaiseUnloadEvent(), System.Net.Sockets.SocketAsyncEventArgs.MultiConnectSocketAsyncEventArgs.ReachedCoordinationPointFirst(), System.Net.Security.NegotiateStream.ReadAsync< TAdapter >(), System.IO.Pipes.PipeStream.ReadAsyncCore(), System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter >(), System.Net.Security.SslStream.ReadByte(), System.IO.UnmanagedMemoryStream.ReadByte(), System.IO.UnmanagedMemoryStream.ReadCore(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveFromAsync(), System.Net.Sockets.Socket.ReceiveMessageFromAsync(), System.Net.Http.Http2Connection.RttEstimator.RefreshRtt(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.RegisterForCancellation(), System.Reflection.Internal.MemoryMappedFileBlock.DisposableData.Release(), System.Reflection.Internal.NativeHeapMemoryBlock.DisposableData.Release(), System.Reflection.Internal.PinnedObject.Release(), System.Reflection.Metadata.Ecma335.VirtualHeap.Release(), Microsoft.Win32.SafeHandles.SafeFileHandle.ReleaseHandle(), System.Net.WebSockets.WebSocketBuffer.ReleasePinnedSendBuffer(), System.Net.Security.SslStream.RenegotiateAsync< TIOAdapter >(), System.Threading.RegisteredWaitHandle.RentEvent(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >.RentFromCache(), System.Text.RegularExpressions.Regex.RentRunner(), System.IO.UnmanagedMemoryStream.Seek(), System.Net.Http.Http3RequestStream.SendAsync(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.Socket.SendAsyncForNetworkStream(), System.Net.Sockets.Socket.SendFileAsync(), System.Net.Mail.SmtpClient.SendMailAsync(), System.Net.Sockets.Socket.SendToAsync(), System.IO.UnmanagedMemoryStream.SetLength(), System.Diagnostics.Debug.SetProvider(), System.IO.StreamBuffer.ResettableValueTaskSource.SignalWaiter(), System.Net.WebSockets.WebSocketBase.ThrowIfPendingException(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Trim(), System.Linq.Parallel.AsynchronousChannel< T >.TryDequeueChunk(), System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.TryLocalPop(), System.Threading.Tasks.Task< TResult >.TrySetResult(), System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.TrySteal(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.TrySteal(), System.Net.WebSockets.WebSocketBase.UpdateReceiveState(), System.IO.Pipes.NamedPipeServerStream.WaitForConnectionCoreAsync(), System.Linq.Parallel.AsynchronousChannel< T >.WaitUntilNonFull(), System.Net.Security.NegotiateStream.WriteAsync< TAdapter >(), System.IO.Pipes.PipeStream.WriteAsyncCore(), System.Net.Security.SslStream.WriteAsyncInternal< TIOAdapter >(), System.IO.UnmanagedMemoryStream.WriteByte(), and System.IO.UnmanagedMemoryStream.WriteCore().