Terraria: Terraria.GameContent.Skies.AmbientSky.WyvernSkyEntity.WyvernSkyEntity
WyvernSkyEntity()
Terraria.GameContent.Skies.AmbientSky.WyvernSkyEntity.WyvernSkyEntity (Player player, FastRandom random) inline
Definition at line 1026 of file AmbientSky.cs.
        {
            VirtualCamera virtualCamera = new VirtualCamera(player);
            Effects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
            int num = 100;
            if (Effects == SpriteEffects.FlipHorizontally)
            {
                Position.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
            }
            else
            {
                Position.X = virtualCamera.Position.X - (float)num;
            }
            Position.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 1600f - 2400f) + 2400f;
            Depth = random.NextFloat() * 3f + 3f;
            SetPositionInWorldBasedOnScreenSpace(Position);
            Texture = Main.Assets.Request<Texture2D>("Images/Backgrounds/Ambience/Wyvern", (AssetRequestMode)1);
            Frame = new SpriteFrame(1, 5);
            LifeTime = random.Next(40, 71) * 60;
            OpacityNormalizedTimeToFadeIn = 0.15f;
            OpacityNormalizedTimeToFadeOut = 0.85f;
            BrightnessLerper = 0.2f;
            FinalOpacityMultiplier = 1f;
            FramingSpeed = 4;
        }
References Terraria.Main.Assets, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.BrightnessLerper, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Depth, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Frame, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FramingSpeed, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.LifeTime, Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextFloat(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, Terraria.GameContent.Skies.AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), and Terraria.Main.worldSurface.