Terraria: System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback
ExecuteCallback()
void System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback () inline
Definition at line 252 of file CancellationTokenSource.cs.
        {
            ExecutionContext executionContext = ExecutionContext;
            if (executionContext == null)
            {
                Invoke(Callback, CallbackState, Registrations.Source);
                return;
            }
            ExecutionContext.RunInternal(executionContext, delegate(object s)
            {
                CallbackNode callbackNode = (CallbackNode)s;
                Invoke(callbackNode.Callback, callbackNode.CallbackState, callbackNode.Registrations.Source);
            }, this);
        }
References System.Threading.CancellationTokenSource.CallbackNode.CallbackNode(), System.Threading.CancellationTokenSource.CallbackNode.CallbackState, System.Threading.CancellationTokenSource.CallbackNode.ExecutionContext, System.Threading.CancellationTokenSource.Invoke(), System.Threading.ExecutionContext.RunInternal(), System.s, and System.Threading.CancellationTokenSource.Registrations.Source.