Terraria: System.Threading.Interlocked.CompareExchange
CompareExchange() [3/8]
static int System.Threading.Interlocked.CompareExchange (ref int location1, int value, int comparand)
Referenced by System.Linq.Expressions.Expression< TDelegate >.Expression(), System.Net.Http.Http3Connection.Abort(), System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Transactions.Bucket.Add(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Add(), System.Diagnostics.Activity.AddBaggage(), System.Diagnostics.Activity.AddEvent(), System.Threading.Tasks.Task< TResult >.AddException(), System.Transactions.TransactionTable.AddIter(), System.Diagnostics.ActivitySource.AddListener(), System.Collections.Immutable.ImmutableInterlocked.AddOrUpdate< TKey, TValue >(), System.Collections.Immutable.ImmutableInterlocked.AddOrUpdate< TKey, TValue >(), System.Text.EncodingProvider.AddProvider(), System.Threading.DeferredDisposableLifetime< T >.AddRef(), System.Diagnostics.Activity.AddTag(), System.Threading.Tasks.Task< TResult >.AddTaskContinuation(), System.Threading.Tasks.Task< TResult >.AddTaskContinuationComplex(), System.Threading.Tasks.Task< TResult >.AddToActiveTasks(), System.Threading.Tasks.TaskScheduler.AddToActiveTaskSchedulers(), System.Reflection.Internal.ObjectPool< T >.Allocate(), System.IO.Strategies.BufferedFileStreamStrategy.AllocateBuffer(), System.Threading.Interlocked.And(), System.Threading.Interlocked.And(), System.Threading.Tasks.ParallelLoopStateFlags.AtomicLoopStateUpdate(), System.Threading.Tasks.Task< TResult >.AtomicStateUpdate(), System.Threading.Tasks.Task< TResult >.AtomicStateUpdate(), System.Threading.Tasks.Task< TResult >.AtomicStateUpdateSlow(), System.Threading.Tasks.Dataflow.DataflowBlock.OutputAvailableAsyncTarget< T >.AttemptThreadSafeUnlink(), System.Threading.Tasks.ParallelLoopState.Break(), System.Threading.Tasks.ParallelLoopState.Break(), System.Xml.Schema.XmlSchemaValidator.BuildXsiAttributes(), System.ComponentModel.LicenseManager.CacheProvider(), System.Threading.CancellationTokenSource.CancelAfter(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CancellationHandler(), System.Text.RegularExpressions.RegexCharClass.CharInClass(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.CleanupAndComplete(), System.Net.Security.SslStream.CloseInternal(), System.Threading.SpinLock.CompareExchange(), System.Threading.Interlocked.CompareExchange(), System.Threading.Interlocked.CompareExchange(), System.Threading.Interlocked.CompareExchange(), System.Threading.Interlocked.CompareExchange< T >(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompareExchangeCurrentOverlappedOwner(), System.Collections.Concurrent.BlockingCollection< T >.CompleteAdding(), System.Threading.Tasks.Dataflow.WriteOnceBlock< T >.CompleteBlock(), System.Net.WebSockets.ClientWebSocket.ConnectAsync(), System.Net.WebSockets.WebSocketHandle.ConnectAsync(), System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.ConsumeMessage(), System.Net.Http.HttpConnection.ConsumeReadAheadTask(), System.Net.Sockets.DynamicWinsockMethods.CreateDelegate< T >(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.CreatePerCoreLockedStacks(), System.Uri.CreateUriInfo(), System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Threading.SpinLock.DecrementWaiters(), System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Dispose(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.Dispose(), System.Net.Sockets.SocketAsyncEventArgs.Dispose(), System.Threading.Tasks.Dataflow.Internal.Disposables.Disposable< T1, T2, T3 >.Dispose(), System.Net.Sockets.Socket.Dispose(), System.Net.Sockets.TcpClient.Dispose(), System.Threading.DeferredDisposableLifetime< T >.Dispose(), System.Net.WebSockets.WebSocketBuffer.Dispose(), System.Threading.ReaderWriterLock.DowngradeFromWriterLock(), System.Diagnostics.Tracing.EventCounter.Enqueue(), System.Collections.Immutable.ImmutableInterlocked.Enqueue< T >(), System.IO.Stream.EnsureAsyncActiveSemaphoreInitialized(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.EnsureCompletionStateInitialized(), System.Threading.Tasks.Task< TResult >.EnsureContingentPropertiesInitialized(), Interop.Winsock.EnsureInitialized(), System.Threading.LazyInitializer.EnsureInitializedCore< T >(), System.Threading.LazyInitializer.EnsureInitializedCore<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] T >(), System.Threading.LazyInitializer.EnsureLockInitialized(), System.Threading.ManualResetEventSlim.EnsureLockObjectCreated(), System.Xml.Linq.XNamespace.EnsureNamespace(), System.Threading.Thread.LocalDataStore.EnsureNameToSlotMap(), System.Threading.ThreadPoolWorkQueue.EnsureThreadRequested(), Internal.Cryptography.Pbkdf2Implementation.FillKeyDerivation(), System.Threading.Tasks.RangeWorker.FindNewWork(), System.Net.HttpListener.DisconnectAsyncResult.FinishOwningDisconnectHandling(), System.Xml.Linq.XNamespace.Get(), System.Diagnostics.Metrics.AggregatorStore< TAggregator >.GetAggregator(), System.Xml.Schema.Preprocessor.GetBuildInSchema(), Internal.Cryptography.BCryptAeadHandleCache.GetCachedAlgorithmHandle(), System.Text.EncodingTable.GetCodePageDataItem(), System.Reflection.PortableExecutable.PEReader.GetEntireImageBlock(), System.Diagnostics.Metrics.MultiSizeLabelNameDictionary< TAggregator >.GetFixedSizeLabelNameDictionary< TStringSequence, TObjectSequence >(), System.RuntimeType.RuntimeTypeCache.GetGenericMethodInfo(), Microsoft.Win32.SafeHandles.SafeHandleCache< T >.GetInvalidHandle(), System.Diagnostics.Metrics.AggregatorStore< TAggregator >.GetLabelValuesDictionary< TStringSequence, TObjectSequence >(), System.RuntimeType.RuntimeTypeCache.GetMemberCache< T >(), System.Reflection.Metadata.MetadataReaderProvider.GetMetadataBlock(), System.Reflection.PortableExecutable.PEReader.GetMetadataBlock(), System.Diagnostics.Metrics.MultiSizeLabelNameDictionary< TAggregator >.GetNoLabelAggregator(), System.Diagnostics.Tracing.ConcurrentSet< KeyType, ItemType >.GetOrAdd(), System.Collections.Immutable.ImmutableInterlocked.GetOrAdd< TKey, TValue >(), System.Threading.ReaderWriterLock.GetOrCreateReaderEvent(), System.Reflection.Metadata.Ecma335.VirtualHeap.GetOrCreateVirtualHeap(), System.Threading.ReaderWriterLock.GetOrCreateWriterEvent(), System.Reflection.PortableExecutable.PEReader.GetPESectionBlock(), System.Runtime.CompilerServices.CallSiteBinder.GetRuleCache< T >(), System.Xml.XPath.XNodeNavigator.GetXmlNamespaceDeclaration(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumeratorForIndexRange_Abstract< TSource, TSourceReader >.GrabNextChunk(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.Initialize(), System.Resources.ResourceReader.InitializeBinaryFormatter(), System.RuntimeType.InitializeCache(), System.Reflection.PortableExecutable.PEReader.InitializePEHeaders(), System.Diagnostics.StackFrameHelper.InitializeSourceInfo(), System.Globalization.CultureInfo.InitializeUserDefaultCulture(), System.Globalization.CultureInfo.InitializeUserDefaultUICulture(), System.Diagnostics.Tracing.SimpleEventTypes< T >.InitInstance(), System.Threading.LowLevelLifoSemaphore.Counts.InterlockedCompareExchange(), System.Threading.PortableThreadPool.CountsOfThreadsProcessingUserCallbacks.InterlockedCompareExchange(), System.Threading.PortableThreadPool.ThreadCounts.InterlockedCompareExchange(), System.Collections.Immutable.ImmutableInterlocked.InterlockedCompareExchange< T >(), System.Runtime.InteropServices.SafeHandle.InternalRelease(), System.Threading.Tasks.Task< TResult >.InternalRunSynchronously(), System.Net.WebClient.InvokeOperationCompleted(), System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.IOCallback(), System.Net.LazyAsyncResult.LazilyCreateEvent(), System.Threading.ManualResetEventSlim.LazyInitializeEvent(), System.Net.Http.HttpRequestMessage.MarkAsSent(), System.Threading.ThreadPoolWorkQueue.MarkThreadRequestSatisfied(), System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.Morph(), System.Threading.Tasks.RendezvousAwaitable< TResult >.NotifyAwaiter(), System.Threading.CancellationTokenSource.NotifyCancellation(), System.Net.WebSockets.WebSocketBase.OnBackgroundTaskException(), System.Threading.Tasks.RendezvousAwaitable< TResult >.OnCompleted(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(), System.Threading.Channels.AsyncOperation< TResult >.OnCompleted(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(), System.Diagnostics.Tracing.ActivityTracker.OnStop(), System.Threading.Interlocked.Or(), System.Threading.Interlocked.Or(), System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync(), System.Threading.Tasks.Task< TResult >.ProcessChildCompletion(), System.Net.TimerThread.Prod(), System.Lazy< T, TMetadata >.PublicationOnly(), System.Collections.Concurrent.ConcurrentStack< T >.Push(), System.Collections.Immutable.ImmutableInterlocked.Push< T >(), System.Collections.Concurrent.ConcurrentStack< T >.PushCore(), System.Collections.Concurrent.ConcurrentStack< T >.PushRange(), System.Threading.Interlocked.Read(), System.Threading.Interlocked.Read(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveCoreByLinking< TOutput >(), System.Threading.CancellationTokenSource.Register(), System.IO.Strategies.Net5CompatFileStreamStrategy.CompletionSource.RegisterForCancellation(), System.Runtime.InteropServices.ComWrappers.RegisterForMarshalling(), System.Runtime.InteropServices.ComWrappers.RegisterForTrackerSupport(), System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.Release(), System.Threading.DeferredDisposableLifetime< T >.Release(), System.Threading.ReaderWriterLock.ReleaseReaderLock(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.ReleaseReservation(), System.Threading.ReaderWriterLock.ReleaseWriterLock(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueueList.Remove(), System.Threading.Tasks.Task< TResult >.RemoveContinuation(), System.Diagnostics.Tracing.NameInfo.ReserveEventIDsBelow(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.ReserveMessage(), System.Xml.Linq.XHashtable< TValue >.XHashtableState.Resize(), System.Threading.ReaderWriterLock.RestoreLock(), System.Threading.RegisteredWaitHandle.ReturnEvent(), System.Dynamic.Utils.ExpressionUtils.ReturnReadOnly(), System.Dynamic.Utils.ExpressionUtils.ReturnReadOnly(), System.Dynamic.Utils.ExpressionUtils.ReturnReadOnly< T >(), System.Linq.Expressions.BlockExpression.ReturnReadOnlyExpressions(), System.Net.Sockets.Socket.ReturnSocketAsyncEventArgs(), System.Threading.Tasks.Dataflow.Internal.SpscTargetCore< TInput >.ScheduleConsumerIfNecessary(), System.Diagnostics.Activity.SetBaggage(), System.Runtime.Loader.AssemblyLoadContext.SetCurrentContextualReflectionContext(), System.Threading.Barrier.SetCurrentTotal(), System.Diagnostics.Activity.SetCustomProperty(), System.AppContext.SetData(), System.Runtime.InteropServices.NativeLibrary.SetDllImportResolver(), System.AppContext.SetSwitch(), System.Diagnostics.Activity.SetTag(), System.AppDomain.SetThreadPrincipal(), System.Net.Http.SocketsHttpHandler.SetupHandlerChain(), System.Threading.CountdownEvent.Signal(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SignalCompletion(), System.Threading.Channels.AsyncOperation< TResult >.SignalCompletion(), System.Threading.Tasks.Task< TResult >.Start(), System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring(), System.Net.Http.HttpConnectionPoolManager.StartMonitoringNetworkChanges(), System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.StartOperationCommon(), System.Net.HttpListener.DisconnectAsyncResult.StartOwningDisconnectHandling(), System.Diagnostics.DiagnosticListener.SubscribeInternal(), System.Threading.PortableThreadPool.WorkerThread.TakeActiveRequest(), System.Net.TimerThread.ThreadProc(), System.Transactions.TransactionTable.ThreadTimer(), System.Threading.LowLevelLock.TryAcquire(), System.Threading.LowLevelLock.TryAcquire_NoFastPath(), System.Xml.Linq.XHashtable< TValue >.XHashtableState.TryAdd(), System.Collections.Immutable.ImmutableInterlocked.TryAdd< TKey, TValue >(), System.Threading.CountdownEvent.TryAddCount(), System.Collections.Concurrent.BlockingCollection< T >.TryAddWithNoTimeValidation(), System.Reflection.Internal.StreamMemoryBlockProvider.TryCreateMemoryMappedFileBlock(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryDequeue(), System.Collections.Immutable.ImmutableInterlocked.TryDequeue< T >(), System.Collections.Concurrent.ConcurrentQueueSegment< T >.TryEnqueue(), System.Threading.ReaderWriterLockSlim.SpinLock.TryEnter(), System.Threading.Channels.AsyncOperation< TResult >.TryOwnAndReset(), System.Net.Sockets.SafeSocketHandle.TryOwnClose(), System.Collections.Concurrent.ConcurrentStack< T >.TryPop(), System.Collections.Immutable.ImmutableInterlocked.TryPop< T >(), System.Collections.Concurrent.ConcurrentStack< T >.TryPopCore(), System.Collections.Immutable.ImmutableInterlocked.TryRemove< TKey, TValue >(), System.Threading.Channels.AsyncOperation< TResult >.TryReserveCompletionIfCancelable(), System.MulticastDelegate.TrySetSlot(), Microsoft.Win32.SafeHandles.SafeFileHandle.TryToReuse(), System.IO.Pipes.NamedPipeServerStream.TryToReuse(), System.IO.Pipes.PipeStream.TryToReuse(), System.Collections.Immutable.ImmutableInterlocked.TryUpdate< TKey, TValue >(), System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.UnsafeOnCompleted(), System.Collections.Immutable.ImmutableInterlocked.Update< T >(), System.Collections.Immutable.ImmutableInterlocked.Update< T >(), System.Collections.Immutable.ImmutableInterlocked.Update< T, TArg >(), System.Collections.Immutable.ImmutableInterlocked.Update< T, TArg >(), System.Threading.ManualResetEventSlim.UpdateStateAtomically(), System.Threading.ReaderWriterLock.UpgradeToWriterLock(), System.Threading.LowLevelLock.WaitAndAcquire(), and System.Diagnostics.Tracing.EventSource.WriteEventString().