Terraria: System.Threading.Interlocked.Increment
Increment() [1/4]
static int System.Threading.Interlocked.Increment (ref int location) inline static
Definition at line 10 of file Interlocked.cs.
    {
        return Add(ref location, 1);
    }
References System.Add.
Referenced by System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerator.InternalPartitionEnumerator(), System.Linq.Expressions.Compiler.LambdaCompiler.LambdaCompiler(), System.Net.Quic.Implementations.Mock.MockListener.MockListener(), System.Diagnostics.Tracing.NameInfo.NameInfo(), System.Threading.ReaderWriterLock.ReaderWriterLock(), System.Threading.ReaderWriterLockSlim.ReaderWriterLockSlim(), System.Transactions.Transaction.Transaction(), System.Transactions.Transaction.Transaction(), System.Net.FileWebRequest.Abort(), System.Runtime.InteropServices.HandleCollector.Add(), System.Transactions.Bucket.Add(), System.Threading.Tasks.Task< TResult >.AddNewChild(), System.Net.Sockets.SocketsTelemetry.AfterAccept(), System.Net.Sockets.SocketsTelemetry.AfterConnect(), System.Net.NameResolutionTelemetry.BeforeResolution(), System.Net.Security.SSPIHandleCache.CacheCredential(), System.Net.Security.SSPIHandleCache.CacheCredential(), System.Net.ClosableStream.Close(), System.Xml.Xsl.IlGen.XmlILModule.CreateAssemblyName(), System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(), System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.CreateOverflowGuid(), System.Reflection.DispatchProxyGenerator.ProxyAssembly.CreateProxy(), System.Net.Sockets.SocketsTelemetry.DatagramReceived(), System.Net.Sockets.SocketsTelemetry.DatagramSent(), System.Linq.Expressions.Compiler.AssemblyGen.DefineType(), System.Threading.AsyncMutex.EnterAsync(), System.Transactions.CheapUnfairReaderWriterLock.EnterReadLock(), System.Data.DataCommonEventSource.EnterScope(), System.Threading.AsyncMutex.Exit(), System.Transactions.CheapUnfairReaderWriterLock.ExitReadLock(), System.Text.RegularExpressions.RegexLWCGCompiler.FactoryInstanceFromCode(), System.Threading.Tasks.Parallel.ForWorker64< TLocal >(), System.Threading.Tasks.Parallel.ForWorker< TLocal >(), System.Diagnostics.Activity.GenerateHierarchicalId(), System.Diagnostics.Activity.GenerateRootId(), System.ComponentModel.TypeDescriptor.GetExtenderCollisionSuffix(), System.Net.Mime.MimeMultiPart.GetNextBoundary(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetObjectInfo(), System.Net.Security.NetSecurityTelemetry.HandshakeCompleted(), System.Net.Security.NetSecurityTelemetry.HandshakeFailed(), System.Net.Security.NetSecurityTelemetry.HandshakeStart(), System.Net.Http.HttpTelemetry.Http11ConnectionEstablished(), System.Net.Http.HttpTelemetry.Http20ConnectionEstablished(), System.Net.Mime.MultiAsyncResult.Increment(), System.Net.LazyAsyncResult.InternalCleanup(), System.Threading.Tasks.Parallel.Invoke(), ReLogic.Content.AssetRepository.LoadAssetWithPotentialAsync< T >(), System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.LocalPush(), System.Linq.Parallel.SingleQueryOperator< TSource >.SingleQueryOperatorEnumerator< TKey >.MoveNext(), System.Linq.Parallel.DefaultIfEmptyQueryOperator< TSource >.DefaultIfEmptyQueryOperatorEnumerator< TKey >.MoveNext(), System.Collections.Immutable.SecureObjectPool< T, TCaller >.NewId(), System.Threading.Tasks.Task< TResult >.NewId(), System.Linq.Parallel.PlinqEtwProvider.NextQueryId(), System.Diagnostics.Tracing.ActivityTracker.OnStart(), System.Threading.Tasks.Parallel.PartitionerForEachWorker< TSource, TLocal >(), System.Net.LazyAsyncResult.ProtectedInvokeCallback(), System.Threading.Tasks.Parallel.ForEachAsyncState< TSource >.QueueWorkerIfDopAvailable(), System.IO.Compression.DeflateManagedStream.ReadAsyncInternal(), System.ComponentModel.TypeDescriptor.Refresh(), System.ComponentModel.TypeDescriptor.Refresh(), System.Threading.Tasks.RangeManager.RegisterNewWorker(), System.Net.Security.SecurityContextTokenHandle.ReleaseHandle(), System.Net.Http.HttpTelemetry.RequestFailed(), System.Net.Http.HttpTelemetry.RequestStart(), System.Net.Http.HttpTelemetry.RequestStop(), System.Threading.PortableThreadPool.RequestWorker(), System.Threading.LowLevelSpinWaiter.SpinWaitForCondition(), System.Net.WebClient.StartOperation(), System.IO.FileSystemWatcher.StartRaisingEvents(), System.IO.FileSystemWatcher.StopRaisingEvents(), System.Xml.Linq.XHashtable< TValue >.XHashtableState.TryAdd(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.TryCopyFromFillBuffer(), and System.Net.Http.Http2Connection.VerifyKeepAlive().