Terraria: Terraria.RemoteClient.CheckSection
CheckSection()
static void Terraria.RemoteClient.CheckSection (int playerIndex, Vector2 position, int fluff = 1) inline static
Definition at line 123 of file RemoteClient.cs.
    {
        int sectionX = Netplay.GetSectionX((int)(position.X / 16f));
        int sectionY = Netplay.GetSectionY((int)(position.Y / 16f));
        int num = 0;
        for (int i = sectionX - fluff; i < sectionX + fluff + 1; i++)
        {
            for (int j = sectionY - fluff; j < sectionY + fluff + 1; j++)
            {
                if (i >= 0 && i < Main.maxSectionsX && j >= 0 && j < Main.maxSectionsY && !Netplay.Clients[playerIndex].TileSections[i, j])
                {
                    num++;
                }
            }
        }
        if (num <= 0)
        {
            return;
        }
        int num2 = num;
        NetMessage.SendData(9, playerIndex, -1, Lang.inter[44].ToNetworkText(), num2);
        Netplay.Clients[playerIndex].StatusText2 = Language.GetTextValue("Net.IsReceivingTileData");
        Netplay.Clients[playerIndex].StatusMax += num2;
        for (int k = sectionX - fluff; k < sectionX + fluff + 1; k++)
        {
            for (int l = sectionY - fluff; l < sectionY + fluff + 1; l++)
            {
                NetMessage.SendSection(playerIndex, k, l);
            }
        }
    }
References Terraria.Netplay.Clients, Terraria.Netplay.GetSectionX(), Terraria.Netplay.GetSectionY(), Terraria.Localization.Language.GetTextValue(), Terraria.Lang.inter, Terraria.Main.maxSectionsY, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendSection(), Terraria.RemoteClient.StatusMax, Terraria.RemoteClient.StatusText2, Terraria.RemoteClient.TileSections, and Terraria.Localization.LocalizedText.ToNetworkText().
Referenced by Terraria.Projectile.AI_149_GolfBall(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Player.DemonConch(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.Player.MagicConch(), Terraria.Player.Shellphone_Spawn(), Terraria.GameContent.PortalHelper.SyncPortalSections(), Terraria.Wiring.Teleport(), Terraria.Player.TeleportationPotion(), and Terraria.Main.UpdateServer().