Terraria: System.Threading.Interlocked.Read
Read() [1/2]
static long System.Threading.Interlocked.Read (ref long location) inline static
Definition at line 95 of file Interlocked.cs.
    {
        return CompareExchange(ref location, 0L, 0L);
    }
References System.Threading.Interlocked.CompareExchange(), and System.L.
Referenced by System.Net.Http.FailedProxyCache.Cleanup(), System.Net.Http.HttpTelemetry.OnEventCommand(), System.Net.NameResolutionTelemetry.OnEventCommand(), System.Net.Security.NetSecurityTelemetry.OnEventCommand(), System.Net.Sockets.SocketsTelemetry.OnEventCommand(), System.Net.Http.Http2Connection.ProcessPingAck(), System.IO.UnmanagedMemoryStream.ReadByte(), System.IO.UnmanagedMemoryStream.ReadCore(), System.IO.UnmanagedMemoryStream.Seek(), System.IO.UnmanagedMemoryStream.SetLength(), System.Collections.Concurrent.ConcurrentBag< T >.TrySteal(), System.IO.UnmanagedMemoryStream.WriteByte(), and System.IO.UnmanagedMemoryStream.WriteCore().