Terraria: System.IO.BinaryReader.InternalRead
InternalRead()
ReadOnlySpan< byte > System.IO.BinaryReader.InternalRead (int numBytes) inline private inherited
Definition at line 470 of file BinaryReader.cs.
    {
        if (_isMemoryStream)
        {
            return ((MemoryStream)_stream).InternalReadSpan(numBytes);
        }
        ThrowIfDisposed();
        int num = 0;
        do
        {
            int num2 = _stream.Read(_buffer, num, numBytes - num);
            if (num2 == 0)
            {
                ThrowHelper.ThrowEndOfFileException();
            }
            num += num2;
        }
        while (num < numBytes);
        return _buffer;
    }
References System.IO.BinaryReader._buffer, System.IO.BinaryReader._isMemoryStream, System.IO.BinaryReader._stream, System.IO.Stream.Read(), System.ThrowHelper.ThrowEndOfFileException(), and System.IO.BinaryReader.ThrowIfDisposed().
Referenced by System.IO.BinaryReader.ReadDecimal(), System.IO.BinaryReader.ReadDouble(), System.IO.BinaryReader.ReadHalf(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), and System.IO.BinaryReader.ReadUInt64().