Terraria: System.IO.BinaryReader.ReadSingle
ReadSingle()
virtual float System.IO.BinaryReader.ReadSingle () inline virtual inherited
Definition at line 240 of file BinaryReader.cs.
    {
        return BitConverter.Int32BitsToSingle(BinaryPrimitives.ReadInt32LittleEndian(InternalRead(4)));
    }
References System.BitConverter.Int32BitsToSingle(), System.IO.BinaryReader.InternalRead(), and System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian().
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), Terraria.GameContent.CoinLossRevengeSystem.AddMarkerFromReader(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DeserializeNetMessage(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.Load(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Load(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.Load(), Terraria.IO.WorldFile.LoadHeader(), Terraria.IO.WorldFile.LoadNPCs(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadSingle(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.ValidateWorld(), and Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.ValidateWorld().