Terraria: System.IO.BinaryReader.ReadUInt16
ReadUInt16()
virtual ushort System.IO.BinaryReader.ReadUInt16 () inline virtual inherited
Definition at line 208 of file BinaryReader.cs.
    {
        return BinaryPrimitives.ReadUInt16LittleEndian(InternalRead(2));
    }
References System.IO.BinaryReader.InternalRead(), and System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian().
Referenced by Terraria.Audio.WAVAudioTrack.WAVAudioTrack(), System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), Terraria.GameContent.NetModules.NetBestiaryModule.Deserialize(), Terraria.GameContent.NetModules.NetCreativePowerPermissionsModule.Deserialize(), Terraria.GameContent.NetModules.NetCreativePowersModule.Deserialize(), Terraria.GameContent.NetModules.NetCreativeUnlocksModule.Deserialize(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.Deserialize(), Terraria.GameContent.NetModules.NetLiquidModule.Deserialize(), Terraria.MessageBuffer.GetData(), System.IO.Compression.ZipLocalFileHeader.GetExtraFields(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.GameContent.Creative.CreativePowerManager.LoadFromWorld(), Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.GameContent.Creative.CreativePowerManager.LoadToPlayer(), Terraria.Net.NetManager.Read(), Terraria.MessageBuffer.ReadAccessoryVisibility(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadItem(), Terraria.GameContent.Tile_Entities.TEHatRack.ReadItem(), System.Reflection.PortableExecutable.PEBinaryReader.ReadUInt16(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadUInt16(), Internal.NativeCrypto.CapiHelper.ToRSAParameters(), System.IO.Compression.ZipCentralDirectoryFileHeader.TryReadBlock(), System.IO.Compression.ZipGenericExtraField.TryReadBlock(), System.IO.Compression.Zip64EndOfCentralDirectoryRecord.TryReadBlock(), System.IO.Compression.ZipEndOfCentralDirectoryBlock.TryReadBlock(), System.IO.Compression.ZipLocalFileHeader.TrySkipBlock(), and Terraria.GameContent.Creative.CreativePowerManager.ValidateWorld().