Terraria: System.IO.BinaryReader.InternalReadChars
InternalReadChars()
int System.IO.BinaryReader.InternalReadChars (Span< char > buffer) inline private inherited
Definition at line 337 of file BinaryReader.cs.
    {
        int num = 0;
        while (!buffer.IsEmpty)
        {
            int num2 = buffer.Length;
            if (_2BytesPerChar)
            {
                num2 <<= 1;
            }
            if (num2 > 1 && !(_decoder is DecoderNLS { HasState: false }))
            {
                num2--;
                if (_2BytesPerChar && num2 > 2)
                {
                    num2 -= 2;
                }
            }
            ReadOnlySpan<byte> bytes;
            if (_isMemoryStream)
            {
                MemoryStream memoryStream = (MemoryStream)_stream;
                int start = memoryStream.InternalGetPosition();
                num2 = memoryStream.InternalEmulateRead(num2);
                bytes = new ReadOnlySpan<byte>(memoryStream.InternalGetBuffer(), start, num2);
            }
            else
            {
                if (_charBytes == null)
                {
                    _charBytes = new byte[128];
                }
                if (num2 > 128)
                {
                    num2 = 128;
                }
                num2 = _stream.Read(_charBytes, 0, num2);
                bytes = new ReadOnlySpan<byte>(_charBytes, 0, num2);
            }
            if (bytes.IsEmpty)
            {
                break;
            }
            int chars = _decoder.GetChars(bytes, buffer, flush: false);
            buffer = buffer.Slice(chars);
            num += chars;
        }
        return num;
    }
References System.IO.BinaryReader._2BytesPerChar, System.IO.BinaryReader._charBytes, System.IO.BinaryReader._decoder, System.IO.BinaryReader._isMemoryStream, System.IO.BinaryReader._stream, System.buffer, System.bytes, System.chars, System.Text.Decoder.GetChars(), System.IO.MemoryStream.InternalEmulateRead(), System.IO.MemoryStream.InternalGetBuffer(), System.IO.MemoryStream.InternalGetPosition(), System.IO.Stream.Read(), and System.start.
Referenced by System.IO.BinaryReader.Read(), System.IO.BinaryReader.Read(), and System.IO.BinaryReader.ReadChars().