Terraria: System.IO.BinaryReader.Read
Read() [1/5]
virtual int System.IO.BinaryReader.Read () inline virtual inherited
Definition at line 112 of file BinaryReader.cs.
    {
        ThrowIfDisposed();
        int num = 0;
        long num2 = 0L;
        if (_stream.CanSeek)
        {
            num2 = _stream.Position;
        }
        if (_charBytes == null)
        {
            _charBytes = new byte[128];
        }
        Span<char> chars = stackalloc char[1];
        while (num == 0)
        {
            int num3 = ((!_2BytesPerChar) ? 1 : 2);
            int num4 = _stream.ReadByte();
            _charBytes[0] = (byte)num4;
            if (num4 == -1)
            {
                num3 = 0;
            }
            if (num3 == 2)
            {
                num4 = _stream.ReadByte();
                _charBytes[1] = (byte)num4;
                if (num4 == -1)
                {
                    num3 = 1;
                }
            }
            if (num3 == 0)
            {
                return -1;
            }
            try
            {
                num = _decoder.GetChars(new ReadOnlySpan<byte>(_charBytes, 0, num3), chars, flush: false);
            }
            catch
            {
                if (_stream.CanSeek)
                {
                    _stream.Seek(num2 - _stream.Position, SeekOrigin.Current);
                }
                throw;
            }
        }
        return chars[0];
    }
References System.IO.BinaryReader._2BytesPerChar, System.IO.BinaryReader._charBytes, System.IO.BinaryReader._decoder, System.IO.BinaryReader._stream, System.IO.Stream.CanSeek, System.chars, System.Text.Decoder.GetChars(), System.L, System.IO.Stream.Position, System.IO.Stream.ReadByte(), System.IO.Stream.Seek(), and System.IO.BinaryReader.ThrowIfDisposed().
Referenced by System.Resources.ResourceReader.AllocateStringForNameIndex(), System.Resources.ResourceReader.CompareStringEqualsName(), System.IO.BinaryReader.PeekChar(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadBytes(), and System.IO.BinaryReader.ReadChar().