Terraria: System.IO.BinaryReader.ReadBytes
ReadBytes()
virtual byte[] System.IO.BinaryReader.ReadBytes (int count) inline virtual inherited
Definition at line 437 of file BinaryReader.cs.
    {
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        ThrowIfDisposed();
        if (count == 0)
        {
            return Array.Empty<byte>();
        }
        byte[] array = new byte[count];
        int num = 0;
        do
        {
            int num2 = _stream.Read(array, num, count);
            if (num2 == 0)
            {
                break;
            }
            num += num2;
            count -= num2;
        }
        while (count > 0);
        if (num != array.Length)
        {
            byte[] array2 = new byte[num];
            Buffer.BlockCopy(array, 0, array2, 0, num);
            array = array2;
        }
        return array;
    }
References System.IO.BinaryReader._stream, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.array, System.Buffer.BlockCopy(), System.count, System.IO.Stream.Read(), and System.IO.BinaryReader.ThrowIfDisposed().
Referenced by System.Security.Claims.Claim.Claim(), System.Security.Claims.ClaimsPrincipal.ClaimsPrincipal(), System.Resources.ResourceReader._LoadObjectV2(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone(), Terraria.MessageBuffer.GetData(), System.Resources.ResourceReader.GetResourceData(), System.Security.Claims.ClaimsIdentity.Initialize(), Terraria.IO.WorldFile.LoadHeader(), System.Reflection.PortableExecutable.PEBinaryReader.ReadBytes(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadBytes(), Internal.NativeCrypto.CapiHelper.ReadReversed(), System.Transactions.TransactionManager.Reenlist(), Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsImage(), Terraria.Audio.WAVAudioTrack.SkipJunk(), System.IO.Compression.ZipCentralDirectoryFileHeader.TryReadBlock(), System.IO.Compression.ZipGenericExtraField.TryReadBlock(), and System.IO.Compression.ZipEndOfCentralDirectoryBlock.TryReadBlock().