Terraria: System.IO.BinaryReader.Read7BitEncodedInt
Read7BitEncodedInt()
int System.IO.BinaryReader.Read7BitEncodedInt () inline inherited
Definition at line 522 of file BinaryReader.cs.
    {
        uint num = 0u;
        byte b;
        for (int i = 0; i < 28; i += 7)
        {
            b = ReadByte();
            num |= (uint)((b & 0x7F) << i);
            if ((uint)b <= 127u)
            {
                return (int)num;
            }
        }
        b = ReadByte();
        if ((uint)b > 15u)
        {
            throw new FormatException(SR.Format_Bad7BitInt);
        }
        return (int)num | (b << 28);
    }
References System.SR.Format_Bad7BitInt, and System.IO.BinaryReader.ReadByte().
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader._LoadObjectV2(), System.Resources.ResourceReader.AllocateStringForNameIndex(), System.Resources.ResourceReader.CompareStringEqualsName(), System.Resources.ResourceReader.GetResourceData(), System.Resources.ResourceReader.LoadString(), System.IO.BinaryReader.ReadString(), and System.Resources.ResourceReader.SkipString().