Terraria: System.IO.BinaryReader.BinaryReader
BinaryReader() [3/3]
System.IO.BinaryReader.BinaryReader (Stream input, Encoding encoding, bool leaveOpen) inline
Definition at line 41 of file BinaryReader.cs.
    {
        if (input == null)
        {
            throw new ArgumentNullException("input");
        }
        if (encoding == null)
        {
            throw new ArgumentNullException("encoding");
        }
        if (!input.CanRead)
        {
            throw new ArgumentException(SR.Argument_StreamNotReadable);
        }
        _stream = input;
        _decoder = encoding.GetDecoder();
        _maxCharsSize = encoding.GetMaxCharCount(128);
        int num = encoding.GetMaxByteCount(1);
        if (num < 16)
        {
            num = 16;
        }
        _buffer = new byte[num];
        _2BytesPerChar = encoding is UnicodeEncoding;
        _isMemoryStream = _stream.GetType() == typeof(MemoryStream);
        _leaveOpen = leaveOpen;
    }
References System.IO.BinaryReader._2BytesPerChar, System.IO.BinaryReader._buffer, System.IO.BinaryReader._decoder, System.IO.BinaryReader._isMemoryStream, System.IO.BinaryReader._leaveOpen, System.IO.BinaryReader._maxCharsSize, System.IO.BinaryReader._stream, System.SR.Argument_StreamNotReadable, System.Text.Encoding.GetDecoder(), System.Text.Encoding.GetMaxByteCount(), System.Text.Encoding.GetMaxCharCount(), and System.input.