Terraria: System.Text.Json.Nodes.JsonValueTrimmable.WriteTo
WriteTo() [1/2]
override void System.Text.Json.Nodes.JsonValueTrimmable< TValue >.WriteTo (Utf8JsonWriter writer, JsonSerializerOptions options = null) inline
Definition at line 24 of file JsonValueTrimmable.cs.
    {
        if (writer == null)
        {
            throw new ArgumentNullException("writer");
        }
        if (_converter != null)
        {
            if (options == null)
            {
                options = JsonSerializerOptions.s_defaultOptions;
            }
            if (_converter.IsInternalConverterForNumberType)
            {
                _converter.WriteNumberWithCustomHandling(writer, _value, options.NumberHandling);
            }
            else
            {
                _converter.Write(writer, _value, options);
            }
        }
        else
        {
            JsonSerializer.Serialize(writer, _value, _jsonTypeInfo);
        }
    }
References System.Text.Json.Nodes.JsonValueTrimmable< TValue >._converter, System.Text.Json.Nodes.JsonValueTrimmable< TValue >._jsonTypeInfo, System.Text.Json.Nodes.JsonValue< TValue >._value, System.Text.Json.Serialization.JsonConverter< T >.IsInternalConverterForNumberType, System.options, System.Text.Json.JsonSerializerOptions.s_defaultOptions, System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.Serialization.JsonConverter< T >.Write(), System.Text.Json.Serialization.JsonConverter< T >.WriteNumberWithCustomHandling(), and System.writer.