Terraria: System.Runtime.Loader.AssemblyDependencyResolver.AssemblyDependencyResolver
AssemblyDependencyResolver()
System.Runtime.Loader.AssemblyDependencyResolver.AssemblyDependencyResolver (string componentAssemblyPath) inline
Definition at line 24 of file AssemblyDependencyResolver.cs.
    {
        if (componentAssemblyPath == null)
        {
            throw new ArgumentNullException("componentAssemblyPath");
        }
        string assemblyPathsList = null;
        string nativeSearchPathsList = null;
        string resourceSearchPathsList = null;
        int num = 0;
        StringBuilder errorMessage = new StringBuilder();
        try
        {
            Interop.HostPolicy.corehost_error_writer_fn corehost_error_writer_fn = delegate(string message)
            {
                errorMessage.AppendLine(message);
            };
            IntPtr functionPointerForDelegate = Marshal.GetFunctionPointerForDelegate(corehost_error_writer_fn);
            IntPtr errorWriter = Interop.HostPolicy.corehost_set_error_writer(functionPointerForDelegate);
            try
            {
                num = Interop.HostPolicy.corehost_resolve_component_dependencies(componentAssemblyPath, delegate(string assemblyPaths, string nativeSearchPaths, string resourceSearchPaths)
                {
                    assemblyPathsList = assemblyPaths;
                    nativeSearchPathsList = nativeSearchPaths;
                    resourceSearchPathsList = resourceSearchPaths;
                });
            }
            finally
            {
                Interop.HostPolicy.corehost_set_error_writer(errorWriter);
                GC.KeepAlive(corehost_error_writer_fn);
            }
        }
        catch (EntryPointNotFoundException innerException)
        {
            throw new InvalidOperationException(SR.AssemblyDependencyResolver_FailedToLoadHostpolicy, innerException);
        }
        catch (DllNotFoundException innerException2)
        {
            throw new InvalidOperationException(SR.AssemblyDependencyResolver_FailedToLoadHostpolicy, innerException2);
        }
        if (num != 0)
        {
            throw new InvalidOperationException(SR.Format(SR.AssemblyDependencyResolver_FailedToResolveDependencies, componentAssemblyPath, num, errorMessage));
        }
        string[] array = SplitPathsList(assemblyPathsList);
        _assemblyPaths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        string[] array2 = array;
        foreach (string text in array2)
        {
            _assemblyPaths.TryAdd(Path.GetFileNameWithoutExtension(text), text);
        }
        _nativeSearchPaths = SplitPathsList(nativeSearchPathsList);
        _resourceSearchPaths = SplitPathsList(resourceSearchPathsList);
        _assemblyDirectorySearchPaths = new string[1] { Path.GetDirectoryName(componentAssemblyPath) };
    }
References System.Runtime.Loader.AssemblyDependencyResolver._assemblyDirectorySearchPaths, System.Runtime.Loader.AssemblyDependencyResolver._assemblyPaths, System.Runtime.Loader.AssemblyDependencyResolver._nativeSearchPaths, System.Runtime.Loader.AssemblyDependencyResolver._resourceSearchPaths, System.array, System.SR.AssemblyDependencyResolver_FailedToLoadHostpolicy, System.SR.AssemblyDependencyResolver_FailedToResolveDependencies, Interop.HostPolicy.corehost_resolve_component_dependencies(), Interop.HostPolicy.corehost_set_error_writer(), System.SR.Format(), System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileNameWithoutExtension(), System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(), System.GC.KeepAlive(), System.StringComparer.OrdinalIgnoreCase, System.Runtime.Loader.AssemblyDependencyResolver.SplitPathsList(), System.text, and System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd().