Terraria: System.Runtime.Loader.AssemblyDependencyResolver.ResolveAssemblyToPath
ResolveAssemblyToPath()
string? System.Runtime.Loader.AssemblyDependencyResolver.ResolveAssemblyToPath (AssemblyName assemblyName) inline
Definition at line 82 of file AssemblyDependencyResolver.cs.
    {
        if (assemblyName == null)
        {
            throw new ArgumentNullException("assemblyName");
        }
        string value;
        if (!string.IsNullOrEmpty(assemblyName.CultureName) && !string.Equals(assemblyName.CultureName, "neutral", StringComparison.OrdinalIgnoreCase))
        {
            string[] resourceSearchPaths = _resourceSearchPaths;
            foreach (string path in resourceSearchPaths)
            {
                string text = Path.Combine(path, assemblyName.CultureName, assemblyName.Name + ".dll");
                if (File.Exists(text))
                {
                    return text;
                }
            }
        }
        else if (assemblyName.Name != null && _assemblyPaths.TryGetValue(assemblyName.Name, out value) && File.Exists(value))
        {
            return value;
        }
        return null;
    }
References System.Runtime.Loader.AssemblyDependencyResolver._assemblyPaths, System.Runtime.Loader.AssemblyDependencyResolver._resourceSearchPaths, System.IO.Path.Combine(), System.IO.File.Exists(), System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by Internal.Runtime.InteropServices.IsolatedComponentLoadContext.Load().