Terraria: System.Runtime.Loader.AssemblyDependencyResolver.ResolveUnmanagedDllToPath
ResolveUnmanagedDllToPath()
string? System.Runtime.Loader.AssemblyDependencyResolver.ResolveUnmanagedDllToPath (string unmanagedDllName) inline
Definition at line 108 of file AssemblyDependencyResolver.cs.
    {
        if (unmanagedDllName == null)
        {
            throw new ArgumentNullException("unmanagedDllName");
        }
        string[] array = ((!unmanagedDllName.Contains(Path.DirectorySeparatorChar)) ? _nativeSearchPaths : _assemblyDirectorySearchPaths);
        bool isRelativePath = !Path.IsPathFullyQualified(unmanagedDllName);
        foreach (LibraryNameVariation item in LibraryNameVariation.DetermineLibraryNameVariations(unmanagedDllName, isRelativePath))
        {
            string path = item.Prefix + unmanagedDllName + item.Suffix;
            string[] array2 = array;
            foreach (string path2 in array2)
            {
                string text = Path.Combine(path2, path);
                if (File.Exists(text))
                {
                    return text;
                }
            }
        }
        return null;
    }
References System.Runtime.Loader.AssemblyDependencyResolver._assemblyDirectorySearchPaths, System.Runtime.Loader.AssemblyDependencyResolver._nativeSearchPaths, System.array, System.IO.Path.Combine(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Runtime.Loader.LibraryNameVariation.DetermineLibraryNameVariations(), System.IO.Path.DirectorySeparatorChar, System.IO.File.Exists(), System.IO.Path.IsPathFullyQualified(), System.item, and System.text.
Referenced by Internal.Runtime.InteropServices.IsolatedComponentLoadContext.LoadUnmanagedDll().