Terraria: System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionWriteCollection
ReflectionWriteCollection()
void System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionWriteCollection (XmlWriterDelegator xmlWriter, object obj, XmlObjectSerializerWriteContextComplexJson context, CollectionDataContract collectionContract) inline
Definition at line 18 of file ReflectionJsonFormatWriter.cs.
    {
        if (!(xmlWriter is JsonWriterDelegator jsonWriterDelegator))
        {
            throw new ArgumentException("xmlWriter");
        }
        XmlDictionaryString collectionItemName = context.CollectionItemName;
        if (collectionContract.Kind == CollectionKind.Array)
        {
            context.IncrementArrayCount(jsonWriterDelegator, (Array)obj);
            Type itemType = collectionContract.ItemType;
            if (!ReflectionTryWritePrimitiveArray(jsonWriterDelegator, obj, collectionContract.UnderlyingType, itemType, collectionItemName))
            {
                ReflectionWriteArrayAttribute(jsonWriterDelegator);
                Array array = (Array)obj;
                PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(itemType);
                for (int i = 0; i < array.Length; i++)
                {
                    _reflectionClassWriter.ReflectionWriteStartElement(jsonWriterDelegator, collectionItemName);
                    _reflectionClassWriter.ReflectionWriteValue(jsonWriterDelegator, context, itemType, array.GetValue(i), writeXsiType: false, primitiveDataContract);
                    _reflectionClassWriter.ReflectionWriteEndElement(jsonWriterDelegator);
                }
            }
            return;
        }
        collectionContract.IncrementCollectionCount(jsonWriterDelegator, obj, context);
        IEnumerator enumeratorForCollection = collectionContract.GetEnumeratorForCollection(obj);
        bool flag = collectionContract.Kind == CollectionKind.GenericDictionary || collectionContract.Kind == CollectionKind.Dictionary;
        bool useSimpleDictionaryFormat = context.UseSimpleDictionaryFormat;
        if (flag && useSimpleDictionaryFormat)
        {
            ReflectionWriteObjectAttribute(jsonWriterDelegator);
            Type[] genericArguments = collectionContract.ItemType.GetGenericArguments();
            Type type = ((genericArguments.Length == 2) ? genericArguments[1] : null);
            while (enumeratorForCollection.MoveNext())
            {
                object current = enumeratorForCollection.Current;
                object key = ((IKeyValue)current).Key;
                object value = ((IKeyValue)current).Value;
                _reflectionClassWriter.ReflectionWriteStartElement(jsonWriterDelegator, key.ToString());
                _reflectionClassWriter.ReflectionWriteValue(jsonWriterDelegator, context, type ?? value.GetType(), value, writeXsiType: false, null);
                _reflectionClassWriter.ReflectionWriteEndElement(jsonWriterDelegator);
            }
            return;
        }
        ReflectionWriteArrayAttribute(jsonWriterDelegator);
        PrimitiveDataContract primitiveDataContract2 = PrimitiveDataContract.GetPrimitiveDataContract(collectionContract.UnderlyingType);
        if (primitiveDataContract2 != null && primitiveDataContract2.UnderlyingType != Globals.TypeOfObject)
        {
            while (enumeratorForCollection.MoveNext())
            {
                object current2 = enumeratorForCollection.Current;
                context.IncrementItemCount(1);
                primitiveDataContract2.WriteXmlElement(jsonWriterDelegator, current2, context, collectionItemName, null);
            }
            return;
        }
        Type collectionElementType = collectionContract.GetCollectionElementType();
        bool flag2 = collectionContract.Kind == CollectionKind.Dictionary || collectionContract.Kind == CollectionKind.GenericDictionary;
        DataContract dataContract = null;
        JsonDataContract jsonDataContract = null;
        if (flag2)
        {
            dataContract = XmlObjectSerializerWriteContextComplexJson.GetRevisedItemContract(collectionContract.ItemContract);
            jsonDataContract = JsonDataContract.GetJsonDataContract(dataContract);
        }
        while (enumeratorForCollection.MoveNext())
        {
            object current3 = enumeratorForCollection.Current;
            context.IncrementItemCount(1);
            _reflectionClassWriter.ReflectionWriteStartElement(jsonWriterDelegator, collectionItemName);
            if (flag2)
            {
                jsonDataContract.WriteJsonValue(jsonWriterDelegator, current3, context, collectionContract.ItemType.TypeHandle);
            }
            else
            {
                _reflectionClassWriter.ReflectionWriteValue(jsonWriterDelegator, context, collectionElementType, current3, writeXsiType: false, null);
            }
            _reflectionClassWriter.ReflectionWriteEndElement(jsonWriterDelegator);
        }
    }
References System.Runtime.Serialization.Json.ReflectionJsonFormatWriter._reflectionClassWriter, System.Xml.ArgumentException, System.array, System.Runtime.Serialization.Array, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.CollectionItemName, System.Runtime.Serialization.Dictionary, System.Type.GetGenericArguments(), System.Runtime.Serialization.Json.JsonDataContract.GetJsonDataContract(), System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.GetRevisedItemContract(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.IncrementArrayCount(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.key, System.obj, System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionTryWritePrimitiveArray(), System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionWriteArrayAttribute(), System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteEndElement(), System.Runtime.Serialization.Json.ReflectionJsonFormatWriter.ReflectionWriteObjectAttribute(), System.Runtime.Serialization.Json.ReflectionJsonClassWriter.ReflectionWriteStartElement(), System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(), System.type, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.UseSimpleDictionaryFormat, and System.value.