Terraria: LucyAxeMessage.GiveIdleMessageCooldown
GiveIdleMessageCooldown()
static void LucyAxeMessage.GiveIdleMessageCooldown () inline static private
     {
         PutMessageTypeOnCooldown(MessageSource.Idle, Main.rand.Next(7200, 14400));
     }
References UnifiedRandom.Next(), PutMessageTypeOnCooldown(), and Main.rand.
Referenced by Create(), and Hooks_OnEnterWorld().