Terraria: System.Linq.Parallel.HashLookup.Find
Find()
bool System.Linq.Parallel.HashLookup< TKey, TValue >.Find (TKey key, bool add, bool set, [MaybeNullWhen(false)] ref TValue value) inline private
Definition at line 78 of file HashLookup.cs.
    {
        int keyHashCode = GetKeyHashCode(key);
        for (int num = buckets[keyHashCode % buckets.Length] - 1; num >= 0; num = slots[num].next)
        {
            if (slots[num].hashCode == keyHashCode && AreKeysEqual(slots[num].key, key))
            {
                if (set)
                {
                    slots[num].value = value;
                    return true;
                }
                value = slots[num].value;
                return true;
            }
        }
        if (add)
        {
            int num2;
            if (freeList >= 0)
            {
                num2 = freeList;
                freeList = slots[num2].next;
            }
            else
            {
                if (count == slots.Length)
                {
                    Resize();
                }
                num2 = count;
                count++;
            }
            int num3 = keyHashCode % buckets.Length;
            slots[num2].hashCode = keyHashCode;
            slots[num2].key = key;
            slots[num2].value = value;
            slots[num2].next = buckets[num3] - 1;
            buckets[num3] = num2 + 1;
        }
        return false;
    }
References System.Linq.Parallel.HashLookup< TKey, TValue >.AreKeysEqual(), System.Linq.Parallel.HashLookup< TKey, TValue >.buckets, System.Linq.Parallel.HashLookup< TKey, TValue >.count, System.Linq.Parallel.HashLookup< TKey, TValue >.freeList, System.Linq.Parallel.HashLookup< TKey, TValue >.GetKeyHashCode(), System.Linq.Parallel.HashLookup< TKey, TValue >.Slot.hashCode, System.Linq.Parallel.HashLookup< TKey, TValue >.Slot.key, System.key, System.Linq.Parallel.HashLookup< TKey, TValue >.Slot.next, System.Linq.Parallel.HashLookup< TKey, TValue >.Resize(), System.Linq.Parallel.HashLookup< TKey, TValue >.slots, System.Linq.Parallel.HashLookup< TKey, TValue >.Slot.value, and System.value.
Referenced by System.Linq.Parallel.HashLookup< TKey, TValue >.Add(), and System.Linq.Parallel.HashLookup< TKey, TValue >.TryGetValue().