Terraria: System.Data.Common.DataTableMappingCollection.ValidateType
ValidateType()
void System.Data.Common.DataTableMappingCollection.ValidateType ([NotNull] object value) inline private
Definition at line 357 of file DataTableMappingCollection.cs.
    {
        if (value == null)
        {
            throw ADP.TablesAddNullAttempt("value");
        }
        if (!ItemType.IsInstanceOfType(value))
        {
            throw ADP.NotADataTableMapping(value);
        }
    }
References System.Data.Common.ADP.NotADataTableMapping(), System.Data.Common.ADP.TablesAddNullAttempt(), and System.value.
Referenced by System.Data.Common.DataTableMappingCollection.Add(), System.Data.Common.DataTableMappingCollection.AddEnumerableRange(), System.Data.Common.DataTableMappingCollection.IndexOf(), System.Data.Common.DataTableMappingCollection.Insert(), and System.Data.Common.DataTableMappingCollection.Remove().