Terraria: System.Data.Common.DataTableMappingCollection.Validate
Validate()
void System.Data.Common.DataTableMappingCollection.Validate (int index, [NotNull] DataTableMapping value) inline private
Definition at line 369 of file DataTableMappingCollection.cs.
    {
        if (value == null)
        {
            throw ADP.TablesAddNullAttempt("value");
        }
        if (value.Parent != null)
        {
            if (this != value.Parent)
            {
                throw ADP.TablesIsNotParent(this);
            }
            if (index != IndexOf(value))
            {
                throw ADP.TablesIsParent(this);
            }
        }
        string sourceTable = value.SourceTable;
        if (string.IsNullOrEmpty(sourceTable))
        {
            index = 1;
            do
            {
                sourceTable = "SourceTable" + index.ToString(CultureInfo.InvariantCulture);
                index++;
            }
            while (-1 != IndexOf(sourceTable));
            value.SourceTable = sourceTable;
        }
        else
        {
            ValidateSourceTable(index, sourceTable);
        }
    }
References System.index, System.Data.Common.DataTableMappingCollection.IndexOf(), System.Globalization.CultureInfo.InvariantCulture, System.Data.Common.ADP.TablesAddNullAttempt(), System.Data.Common.ADP.TablesIsNotParent(), System.Data.Common.ADP.TablesIsParent(), System.Data.Common.DataTableMappingCollection.ValidateSourceTable(), and System.value.
Referenced by System.Data.Common.DataTableMappingCollection.AddWithoutEvents(), System.Data.Common.DataTableMappingCollection.Insert(), and System.Data.Common.DataTableMappingCollection.Replace().