Terraria: System.Data.Common.DataTableMappingCollection.AddEnumerableRange
AddEnumerableRange()
void System.Data.Common.DataTableMappingCollection.AddEnumerableRange (IEnumerable values, bool doClone) inline private
Definition at line 130 of file DataTableMappingCollection.cs.
    {
        if (values == null)
        {
            throw ADP.ArgumentNull("values");
        }
        foreach (object value2 in values)
        {
            ValidateType(value2);
        }
        if (doClone)
        {
            foreach (ICloneable value3 in values)
            {
                AddWithoutEvents(value3.Clone() as DataTableMapping);
            }
            return;
        }
        foreach (DataTableMapping value4 in values)
        {
            AddWithoutEvents(value4);
        }
    }
References System.Data.Common.DataTableMappingCollection.AddWithoutEvents(), System.Data.Common.ADP.ArgumentNull(), System.Data.Common.DataTableMappingCollection.ValidateType(), and System.values.
Referenced by System.Data.Common.DataTableMappingCollection.AddRange(), and System.Data.Common.DataTableMappingCollection.AddRange().