Terraria: System.Data.Common.DataTableMappingCollection.GetTableMappingBySchemaAction
GetTableMappingBySchemaAction()
static ? DataTableMapping System.Data.Common.DataTableMappingCollection.GetTableMappingBySchemaAction (DataTableMappingCollection? tableMappings, string sourceTable, string dataSetTable, MissingMappingAction mappingAction) inline static
Definition at line 414 of file DataTableMappingCollection.cs.
    {
        if (tableMappings != null)
        {
            int num = tableMappings.IndexOf(sourceTable);
            if (-1 != num)
            {
                return tableMappings._items[num];
            }
        }
        if (string.IsNullOrEmpty(sourceTable))
        {
            throw ADP.InvalidSourceTable("sourceTable");
        }
        return mappingAction switch
        {
            MissingMappingAction.Passthrough => new DataTableMapping(sourceTable, dataSetTable),
            MissingMappingAction.Ignore => null,
            MissingMappingAction.Error => throw ADP.MissingTableMapping(sourceTable),
            _ => throw ADP.InvalidMissingMappingAction(mappingAction),
        };
    }
References System.Data.Common.ADP.InvalidMissingMappingAction(), System.Data.Common.ADP.InvalidSourceTable(), and System.Data.Common.ADP.MissingTableMapping().
Referenced by System.Data.ProviderBase.SchemaMapping.SchemaMapping(), and System.Data.Common.DataAdapter.GetTableMappingBySchemaAction().