Terraria: System.Data.Common.DataTableMappingCollection.AddWithoutEvents
AddWithoutEvents()
void System.Data.Common.DataTableMappingCollection.AddWithoutEvents (DataTableMapping value) inline private
Definition at line 159 of file DataTableMappingCollection.cs.
    {
        Validate(-1, value);
        value.Parent = this;
        ArrayList().Add(value);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.Common.DataTableMappingCollection.ArrayList(), System.Data.Common.DataTableMappingCollection.Validate(), and System.value.
Referenced by System.Data.Common.DataTableMappingCollection.Add(), and System.Data.Common.DataTableMappingCollection.AddEnumerableRange().