Terraria: System.Xml.XmlUTF8TextReader.ReadWhitespace
ReadWhitespace() [1/2]
void System.Xml.XmlUTF8TextReader.ReadWhitespace () inline private
Definition at line 680 of file XmlUTF8TextReader.cs.
    {
        int offset;
        int offsetMax;
        int num;
        if (_buffered)
        {
            byte[] buffer = base.BufferReader.GetBuffer(out offset, out offsetMax);
            num = ReadWhitespace(buffer, offset, offsetMax);
        }
        else
        {
            byte[] buffer = base.BufferReader.GetBuffer(2048, out offset, out offsetMax);
            num = ReadWhitespace(buffer, offset, offsetMax);
            num = BreakText(buffer, offset, num);
        }
        base.BufferReader.Advance(num);
        MoveToWhitespaceText().Value.SetValue(ValueHandleType.UTF8, offset, num);
    }
References System.Xml.XmlUTF8TextReader._buffered, System.Xml.XmlUTF8TextReader.BreakText(), System.buffer, System.Xml.Dictionary, System.Xml.XmlBaseReader.MoveToWhitespaceText(), System.offset, System.Xml.XmlUTF8TextReader.ReadWhitespace(), System.Xml.ValueHandle.SetValue(), and System.Xml.XmlBaseReader.XmlNode.Value.
Referenced by System.Xml.XmlUTF8TextReader.Read(), and System.Xml.XmlUTF8TextReader.ReadWhitespace().