Terraria: System.Xml.XmlUTF8TextReader.ReadCData
ReadCData()
void System.Xml.XmlUTF8TextReader.ReadCData () inline private
Definition at line 628 of file XmlUTF8TextReader.cs.
    {
        byte[] buffer = base.BufferReader.GetBuffer(7, out var offset);
        if (buffer[offset] != 91 || buffer[offset + 1] != 67 || buffer[offset + 2] != 68 || buffer[offset + 3] != 65 || buffer[offset + 4] != 84 || buffer[offset + 5] != 65 || buffer[offset + 6] != 91)
        {
            XmlExceptionHelper.ThrowTokenExpected(this, "[CDATA[", Encoding.UTF8.GetString(buffer, offset, 7));
        }
        base.BufferReader.Advance(7);
        int offset2 = base.BufferReader.Offset;
        while (true)
        {
            switch (base.BufferReader.GetByte())
            {
            case 239:
                ReadNonFFFE();
                break;
            default:
                base.BufferReader.SkipByte();
                break;
            case 93:
            {
                buffer = base.BufferReader.GetBuffer(3, out offset);
                if (buffer[offset] != 93 || buffer[offset + 1] != 93 || buffer[offset + 2] != 62)
                {
                    base.BufferReader.SkipByte();
                    break;
                }
                int length = base.BufferReader.Offset - offset2;
                MoveToCData().Value.SetValue(ValueHandleType.UTF8, offset2, length);
                base.BufferReader.Advance(3);
                return;
            }
            }
        }
    }
References System.buffer, System.Xml.Dictionary, System.length, System.Xml.XmlBaseReader.MoveToCData(), System.offset, System.Xml.XmlUTF8TextReader.ReadNonFFFE(), System.Xml.ValueHandle.SetValue(), System.Xml.XmlExceptionHelper.ThrowTokenExpected(), System.Text.Encoding.UTF8, and System.Xml.XmlBaseReader.XmlNode.Value.
Referenced by System.Xml.XmlUTF8TextReader.Read().