Terraria: System.Xml.XmlUTF8TextReader.ReadText
ReadText() [1/2]
void System.Xml.XmlUTF8TextReader.ReadText (bool hasLeadingByteOf0xEF) inline private
Definition at line 787 of file XmlUTF8TextReader.cs.
    {
        byte[] buffer;
        int offset;
        int offsetMax;
        int num;
        if (_buffered)
        {
            buffer = base.BufferReader.GetBuffer(out offset, out offsetMax);
            num = ((!hasLeadingByteOf0xEF) ? ReadText(buffer, offset, offsetMax) : ReadTextAndWatchForInvalidCharacters(buffer, offset, offsetMax));
        }
        else
        {
            buffer = base.BufferReader.GetBuffer(2048, out offset, out offsetMax);
            num = BreakText(length: (!hasLeadingByteOf0xEF) ? ReadText(buffer, offset, offsetMax) : ReadTextAndWatchForInvalidCharacters(buffer, offset, offsetMax), buffer: buffer, offset: offset);
        }
        base.BufferReader.Advance(num);
        if (offset < offsetMax - 1 - num && buffer[offset + num] == 60 && buffer[offset + num + 1] != 33)
        {
            MoveToAtomicText().Value.SetValue(ValueHandleType.UTF8, offset, num);
        }
        else
        {
            MoveToComplexText().Value.SetValue(ValueHandleType.UTF8, offset, num);
        }
    }
References System.Xml.XmlUTF8TextReader._buffered, System.Xml.XmlUTF8TextReader.BreakText(), System.buffer, System.Xml.Dictionary, System.length, System.Xml.XmlBaseReader.MoveToAtomicText(), System.Xml.XmlBaseReader.MoveToComplexText(), System.offset, System.Xml.XmlUTF8TextReader.ReadText(), System.Xml.XmlUTF8TextReader.ReadTextAndWatchForInvalidCharacters(), System.Xml.ValueHandle.SetValue(), and System.Xml.XmlBaseReader.XmlNode.Value.