Terraria: System.Xml.XmlUTF8TextReader.ReadAttributes
ReadAttributes()
void System.Xml.XmlUTF8TextReader.ReadAttributes () inline private
Definition at line 322 of file XmlUTF8TextReader.cs.
    {
        int num = 0;
        if (_buffered)
        {
            num = base.BufferReader.Offset;
        }
        while (true)
        {
            ReadQualifiedName(_prefix, _localName);
            if (base.BufferReader.GetByte() != 61)
            {
                SkipWhitespace();
                if (base.BufferReader.GetByte() != 61)
                {
                    XmlExceptionHelper.ThrowTokenExpected(this, "=", (char)base.BufferReader.GetByte());
                }
            }
            base.BufferReader.SkipByte();
            byte @byte = base.BufferReader.GetByte();
            if (@byte != 34 && @byte != 39)
            {
                SkipWhitespace();
                @byte = base.BufferReader.GetByte();
                if (@byte != 34 && @byte != 39)
                {
                    XmlExceptionHelper.ThrowTokenExpected(this, "\"", (char)base.BufferReader.GetByte());
                }
            }
            base.BufferReader.SkipByte();
            bool flag = false;
            int offset = base.BufferReader.Offset;
            byte byte2;
            while (true)
            {
                int offset2;
                int offsetMax;
                byte[] buffer = base.BufferReader.GetBuffer(out offset2, out offsetMax);
                int count = ReadAttributeText(buffer, offset2, offsetMax);
                base.BufferReader.Advance(count);
                byte2 = base.BufferReader.GetByte();
                if (byte2 == @byte)
                {
                    break;
                }
                switch (byte2)
                {
                case 38:
                    ReadCharRef();
                    flag = true;
                    break;
                case 34:
                case 39:
                    base.BufferReader.SkipByte();
                    break;
                case 9:
                case 10:
                case 13:
                    base.BufferReader.SkipByte();
                    flag = true;
                    break;
                case 239:
                    ReadNonFFFE();
                    break;
                default:
                {
                    char c = (char)@byte;
                    XmlExceptionHelper.ThrowTokenExpected(this, c.ToString(), (char)byte2);
                    break;
                }
                }
            }
            int length = base.BufferReader.Offset - offset;
            XmlAttributeNode xmlAttributeNode;
            if (_prefix.IsXmlns)
            {
                Namespace @namespace = AddNamespace();
                _localName.ToPrefixHandle(@namespace.Prefix);
                @namespace.Uri.SetValue(offset, length, flag);
                xmlAttributeNode = AddXmlnsAttribute(@namespace);
            }
            else if (_prefix.IsEmpty && _localName.IsXmlns)
            {
                Namespace namespace2 = AddNamespace();
                namespace2.Prefix.SetValue(PrefixHandleType.Empty);
                namespace2.Uri.SetValue(offset, length, flag);
                xmlAttributeNode = AddXmlnsAttribute(namespace2);
            }
            else if (_prefix.IsXml)
            {
                xmlAttributeNode = AddXmlAttribute();
                xmlAttributeNode.Prefix.SetValue(_prefix);
                xmlAttributeNode.LocalName.SetValue(_localName);
                xmlAttributeNode.Value.SetValue(flag ? ValueHandleType.EscapedUTF8 : ValueHandleType.UTF8, offset, length);
                FixXmlAttribute(xmlAttributeNode);
            }
            else
            {
                xmlAttributeNode = AddAttribute();
                xmlAttributeNode.Prefix.SetValue(_prefix);
                xmlAttributeNode.LocalName.SetValue(_localName);
                xmlAttributeNode.Value.SetValue(flag ? ValueHandleType.EscapedUTF8 : ValueHandleType.UTF8, offset, length);
            }
            xmlAttributeNode.QuoteChar = (char)@byte;
            base.BufferReader.SkipByte();
            byte2 = base.BufferReader.GetByte();
            bool flag2 = false;
            while ((s_charType[byte2] & 4u) != 0)
            {
                flag2 = true;
                base.BufferReader.SkipByte();
                byte2 = base.BufferReader.GetByte();
            }
            if (byte2 == 62 || byte2 == 47 || byte2 == 63)
            {
                break;
            }
            if (!flag2)
            {
                XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlSpaceBetweenAttributes));
            }
        }
        if (_buffered && base.BufferReader.Offset - num > _maxBytesPerRead)
        {
            XmlExceptionHelper.ThrowMaxBytesPerReadExceeded(this, _maxBytesPerRead);
        }
        ProcessAttributes();
    }
References System.Xml.XmlUTF8TextReader._buffered, System.Xml.XmlBaseReader._localName, System.Xml.XmlUTF8TextReader._localName, System.Xml.XmlUTF8TextReader._maxBytesPerRead, System.Xml.XmlUTF8TextReader._prefix, System.Xml.XmlBaseReader.AddAttribute(), System.Xml.XmlBaseReader.AddNamespace(), System.Xml.XmlBaseReader.AddXmlAttribute(), System.Xml.XmlBaseReader.AddXmlnsAttribute(), System.buffer, System.count, System.Xml.Dictionary, System.Xml.XmlBaseReader.FixXmlAttribute(), System.Xml.PrefixHandle.IsEmpty, System.Xml.PrefixHandle.IsXml, System.Xml.PrefixHandle.IsXmlns, System.Xml.StringHandle.IsXmlns, System.length, System.offset, System.Xml.XmlBaseReader.Prefix, System.Xml.XmlBaseReader.ProcessAttributes(), System.Xml.XmlUTF8TextReader.ReadAttributeText(), System.Xml.XmlUTF8TextReader.ReadCharRef(), System.Xml.XmlUTF8TextReader.ReadNonFFFE(), System.Xml.XmlUTF8TextReader.ReadQualifiedName(), System.Xml.XmlUTF8TextReader.s_charType, System.Xml.XmlUTF8TextReader.SkipWhitespace(), System.Xml.XmlExceptionHelper.ThrowMaxBytesPerReadExceeded(), System.Xml.XmlExceptionHelper.ThrowTokenExpected(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlException, and System.SR.XmlSpaceBetweenAttributes.
Referenced by System.Xml.XmlUTF8TextReader.ReadDeclaration(), and System.Xml.XmlUTF8TextReader.ReadStartElement().