Terraria: System.Xml.XmlUTF8TextReader.ReadEndElement
ReadEndElement()
new void System.Xml.XmlUTF8TextReader.ReadEndElement () inline private virtual
Reimplemented from System.Xml.XmlBaseReader.
Definition at line 551 of file XmlUTF8TextReader.cs.
    {
        base.BufferReader.SkipByte();
        XmlElementNode elementNode = base.ElementNode;
        int nameOffset = elementNode.NameOffset;
        int nameLength = elementNode.NameLength;
        int offset;
        byte[] buffer = base.BufferReader.GetBuffer(nameLength, out offset);
        for (int i = 0; i < nameLength; i++)
        {
            if (buffer[offset + i] != buffer[nameOffset + i])
            {
                ReadQualifiedName(_prefix, _localName);
                XmlExceptionHelper.ThrowTagMismatch(this, elementNode.Prefix.GetString(), elementNode.LocalName.GetString(), _prefix.GetString(), _localName.GetString());
            }
        }
        base.BufferReader.Advance(nameLength);
        if (base.BufferReader.GetByte() != 62)
        {
            SkipWhitespace();
            if (base.BufferReader.GetByte() != 62)
            {
                XmlExceptionHelper.ThrowTokenExpected(this, ">", (char)base.BufferReader.GetByte());
            }
        }
        base.BufferReader.SkipByte();
        MoveToEndElement();
    }
References System.Xml.XmlUTF8TextReader._localName, System.Xml.XmlUTF8TextReader._prefix, System.buffer, System.Xml.Dictionary, System.Xml.PrefixHandle.GetString(), System.Xml.StringHandle.GetString(), System.Xml.XmlBaseReader.MoveToEndElement(), System.Xml.XmlBaseReader.XmlElementNode.NameOffset, System.offset, System.Xml.XmlUTF8TextReader.ReadQualifiedName(), System.Xml.XmlUTF8TextReader.SkipWhitespace(), System.Xml.XmlExceptionHelper.ThrowTagMismatch(), and System.Xml.XmlExceptionHelper.ThrowTokenExpected().
Referenced by System.Xml.XmlUTF8TextReader.Read().