Terraria: System.Xml.XmlUTF8TextReader.ReadTextAndWatchForInvalidCharacters
ReadTextAndWatchForInvalidCharacters()
int System.Xml.XmlUTF8TextReader.ReadTextAndWatchForInvalidCharacters (byte[] buffer, int offset, int offsetMax) inline private
Definition at line 722 of file XmlUTF8TextReader.cs.
    {
        byte[] array = s_charType;
        int num = offset;
        while (offset < offsetMax && ((array[buffer[offset]] & 8u) != 0 || buffer[offset] == 239))
        {
            if (buffer[offset] != 239)
            {
                offset++;
                continue;
            }
            if (offset + 2 < offsetMax)
            {
                if (IsNextCharacterNonFFFE(buffer, offset))
                {
                    offset += 3;
                }
                else
                {
                    XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlInvalidFFFE));
                }
                continue;
            }
            if (base.BufferReader.Offset < offset)
            {
                break;
            }
            base.BufferReader.GetBuffer(3, out var _);
        }
        return offset - num;
    }
References System.array, System.buffer, System.Xml.Dictionary, System.Xml.XmlUTF8TextReader.IsNextCharacterNonFFFE(), System.offset, System.Xml.XmlUTF8TextReader.s_charType, System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlException, and System.SR.XmlInvalidFFFE.
Referenced by System.Xml.XmlUTF8TextReader.ReadText().