Terraria: System.Xml.XmlUTF8TextReader.ReadEscapedText
ReadEscapedText()
void System.Xml.XmlUTF8TextReader.ReadEscapedText () inline private
Definition at line 814 of file XmlUTF8TextReader.cs.
    {
        int num = ReadCharRef();
        if (num < 256 && (s_charType[num] & 4u) != 0)
        {
            MoveToWhitespaceText().Value.SetCharValue(num);
        }
        else
        {
            MoveToComplexText().Value.SetCharValue(num);
        }
    }
References System.Xml.Dictionary, System.Xml.XmlBaseReader.MoveToComplexText(), System.Xml.XmlBaseReader.MoveToWhitespaceText(), System.Xml.XmlUTF8TextReader.ReadCharRef(), System.Xml.XmlUTF8TextReader.s_charType, System.Xml.ValueHandle.SetCharValue(), and System.Xml.XmlBaseReader.XmlNode.Value.
Referenced by System.Xml.XmlUTF8TextReader.Read().