Terraria: System.Xml.XmlUTF8TextReader.ReadComment
ReadComment()
void System.Xml.XmlUTF8TextReader.ReadComment () inline private
Definition at line 580 of file XmlUTF8TextReader.cs.
    {
        base.BufferReader.SkipByte();
        if (base.BufferReader.GetByte() != 45)
        {
            XmlExceptionHelper.ThrowTokenExpected(this, "--", (char)base.BufferReader.GetByte());
        }
        base.BufferReader.SkipByte();
        int offset = base.BufferReader.Offset;
        while (true)
        {
            byte @byte = base.BufferReader.GetByte();
            if (@byte != 45)
            {
                if ((s_charType[@byte] & 0x40) == 0)
                {
                    if (@byte == 239)
                    {
                        ReadNonFFFE();
                    }
                    else
                    {
                        XmlExceptionHelper.ThrowInvalidXml(this, @byte);
                    }
                }
                else
                {
                    base.BufferReader.SkipByte();
                }
                continue;
            }
            int offset2;
            byte[] buffer = base.BufferReader.GetBuffer(3, out offset2);
            if (buffer[offset2] == 45 && buffer[offset2 + 1] == 45)
            {
                if (buffer[offset2 + 2] == 62)
                {
                    break;
                }
                XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlInvalidCommentChars));
            }
            base.BufferReader.SkipByte();
        }
        int length = base.BufferReader.Offset - offset;
        MoveToComment().Value.SetValue(ValueHandleType.UTF8, offset, length);
        base.BufferReader.Advance(3);
    }
References System.buffer, System.Xml.Dictionary, System.length, System.Xml.XmlBaseReader.MoveToComment(), System.offset, System.Xml.XmlUTF8TextReader.ReadNonFFFE(), System.Xml.XmlUTF8TextReader.s_charType, System.Xml.ValueHandle.SetValue(), System.Xml.XmlExceptionHelper.ThrowInvalidXml(), System.Xml.XmlExceptionHelper.ThrowTokenExpected(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlBaseReader.XmlNode.Value, System.Xml.XmlException, and System.SR.XmlInvalidCommentChars.
Referenced by System.Xml.XmlUTF8TextReader.Read().