Terraria: System.Xml.XmlUTF8TextReader.ReadStartElement
ReadStartElement() [1/4]
new void System.Xml.XmlUTF8TextReader.ReadStartElement () inline private virtual
Reimplemented from System.Xml.XmlBaseReader.
Definition at line 513 of file XmlUTF8TextReader.cs.
    {
        if (!_buffered)
        {
            BufferElement();
        }
        XmlElementNode xmlElementNode = EnterScope();
        xmlElementNode.NameOffset = base.BufferReader.Offset;
        ReadQualifiedName(xmlElementNode.Prefix, xmlElementNode.LocalName);
        xmlElementNode.NameLength = base.BufferReader.Offset - xmlElementNode.NameOffset;
        byte @byte = base.BufferReader.GetByte();
        while ((s_charType[@byte] & 4u) != 0)
        {
            base.BufferReader.SkipByte();
            @byte = base.BufferReader.GetByte();
        }
        if (@byte != 62 && @byte != 47)
        {
            ReadAttributes();
            @byte = base.BufferReader.GetByte();
        }
        xmlElementNode.Namespace = LookupNamespace(xmlElementNode.Prefix);
        bool flag = false;
        if (@byte == 47)
        {
            flag = true;
            base.BufferReader.SkipByte();
        }
        xmlElementNode.IsEmptyElement = flag;
        xmlElementNode.ExitScope = flag;
        if (base.BufferReader.GetByte() != 62)
        {
            XmlExceptionHelper.ThrowTokenExpected(this, ">", (char)base.BufferReader.GetByte());
        }
        base.BufferReader.SkipByte();
        xmlElementNode.BufferOffset = base.BufferReader.Offset;
    }
References System.Xml.XmlUTF8TextReader._buffered, System.Xml.XmlUTF8TextReader.BufferElement(), System.Xml.Dictionary, System.Xml.XmlBaseReader.EnterScope(), System.Xml.XmlBaseReader.LookupNamespace(), System.Xml.XmlUTF8TextReader.ReadAttributes(), System.Xml.XmlUTF8TextReader.ReadQualifiedName(), System.Xml.XmlUTF8TextReader.s_charType, and System.Xml.XmlExceptionHelper.ThrowTokenExpected().
Referenced by System.Xml.XmlUTF8TextReader.Read().