Terraria: System.Xml.XmlUTF8TextReader.ReadQualifiedName
ReadQualifiedName()
void System.Xml.XmlUTF8TextReader.ReadQualifiedName (PrefixHandle prefix, StringHandle localName) inline private
Definition at line 223 of file XmlUTF8TextReader.cs.
    {
        int i;
        int offsetMax;
        byte[] buffer = base.BufferReader.GetBuffer(out i, out offsetMax);
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        int num4 = i;
        if (i < offsetMax)
        {
            num = buffer[i];
            num3 = num;
            if ((s_charType[num] & 1) == 0)
            {
                num2 |= 0x80;
            }
            num2 |= num;
            for (i++; i < offsetMax; i++)
            {
                num = buffer[i];
                if ((s_charType[num] & 2) == 0)
                {
                    break;
                }
                num2 |= num;
            }
        }
        else
        {
            num2 |= 0x80;
            num = 0;
        }
        if (num == 58)
        {
            int num5 = i - num4;
            if (num5 == 1 && num3 >= 97 && num3 <= 122)
            {
                prefix.SetValue(PrefixHandle.GetAlphaPrefix(num3 - 97));
            }
            else
            {
                prefix.SetValue(num4, num5);
            }
            i++;
            int num6 = i;
            if (i < offsetMax)
            {
                num = buffer[i];
                if ((s_charType[num] & 1) == 0)
                {
                    num2 |= 0x80;
                }
                num2 |= num;
                for (i++; i < offsetMax; i++)
                {
                    num = buffer[i];
                    if ((s_charType[num] & 2) == 0)
                    {
                        break;
                    }
                    num2 |= num;
                }
            }
            else
            {
                num2 |= 0x80;
                num = 0;
            }
            localName.SetValue(num6, i - num6);
            if (num2 >= 128)
            {
                VerifyNCName(prefix.GetString());
                VerifyNCName(localName.GetString());
            }
        }
        else
        {
            prefix.SetValue(PrefixHandleType.Empty);
            localName.SetValue(num4, i - num4);
            if (num2 >= 128)
            {
                VerifyNCName(localName.GetString());
            }
        }
        base.BufferReader.Advance(i - num4);
    }
References System.buffer, System.Xml.Dictionary, System.Xml.PrefixHandle.GetAlphaPrefix(), System.Xml.StringHandle.GetString(), System.prefix, System.Xml.XmlUTF8TextReader.s_charType, System.Xml.StringHandle.SetValue(), and System.Xml.XmlUTF8TextReader.VerifyNCName().
Referenced by System.Xml.XmlUTF8TextReader.ReadAttributes(), System.Xml.XmlUTF8TextReader.ReadEndElement(), and System.Xml.XmlUTF8TextReader.ReadStartElement().