Terraria: System.Xml.XmlUTF8TextReader.Read
Read()
override bool System.Xml.XmlUTF8TextReader.Read () inline
Definition at line 827 of file XmlUTF8TextReader.cs.
    {
        if (base.Node.ReadState == ReadState.Closed)
        {
            return false;
        }
        if (base.Node.CanMoveToElement)
        {
            MoveToElement();
        }
        SignNode();
        if (base.Node.ExitScope)
        {
            ExitScope();
        }
        if (!_buffered)
        {
            base.BufferReader.SetWindow(base.ElementNode.BufferOffset, _maxBytesPerRead);
        }
        if (base.BufferReader.EndOfFile)
        {
            MoveToEndOfFile();
            return false;
        }
        byte @byte = base.BufferReader.GetByte();
        if (@byte == 60)
        {
            base.BufferReader.SkipByte();
            switch (base.BufferReader.GetByte())
            {
            case 47:
                ReadEndElement();
                break;
            case 33:
                base.BufferReader.SkipByte();
                @byte = base.BufferReader.GetByte();
                if (@byte == 45)
                {
                    ReadComment();
                    break;
                }
                if (base.OutsideRootElement)
                {
                    XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlCDATAInvalidAtTopLevel));
                }
                ReadCData();
                break;
            case 63:
                ReadDeclaration();
                break;
            default:
                ReadStartElement();
                break;
            }
        }
        else if ((s_charType[@byte] & 0x20u) != 0)
        {
            ReadWhitespace();
        }
        else if (base.OutsideRootElement && @byte != 13)
        {
            XmlExceptionHelper.ThrowInvalidRootData(this);
        }
        else if ((s_charType[@byte] & 8u) != 0)
        {
            ReadText(hasLeadingByteOf0xEF: false);
        }
        else
        {
            switch (@byte)
            {
            case 38:
                ReadEscapedText();
                break;
            case 13:
                base.BufferReader.SkipByte();
                if (!base.BufferReader.EndOfFile && base.BufferReader.GetByte() == 10)
                {
                    ReadWhitespace();
                }
                else
                {
                    MoveToComplexText().Value.SetCharValue(10);
                }
                break;
            case 93:
            {
                int offset;
                byte[] buffer = base.BufferReader.GetBuffer(3, out offset);
                if (buffer[offset] == 93 && buffer[offset + 1] == 93 && buffer[offset + 2] == 62)
                {
                    XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.XmlCloseCData));
                }
                base.BufferReader.SkipByte();
                MoveToComplexText().Value.SetCharValue(93);
                break;
            }
            case 239:
                ReadText(hasLeadingByteOf0xEF: true);
                break;
            default:
                XmlExceptionHelper.ThrowInvalidXml(this, @byte);
                break;
            }
        }
        return true;
    }
References System.Xml.XmlUTF8TextReader._buffered, System.Xml.XmlUTF8TextReader._maxBytesPerRead, System.buffer, System.Xml.Dictionary, System.Xml.XmlBaseReader.ExitScope(), System.Xml.XmlBaseReader.MoveToComplexText(), System.Xml.XmlBaseReader.MoveToElement(), System.Xml.XmlBaseReader.MoveToEndOfFile(), System.offset, System.Xml.XmlUTF8TextReader.ReadCData(), System.Xml.XmlUTF8TextReader.ReadComment(), System.Xml.XmlUTF8TextReader.ReadDeclaration(), System.Xml.XmlUTF8TextReader.ReadEndElement(), System.Xml.XmlUTF8TextReader.ReadEscapedText(), System.Xml.XmlUTF8TextReader.ReadStartElement(), System.Xml.XmlUTF8TextReader.ReadText(), System.Xml.XmlUTF8TextReader.ReadWhitespace(), System.Xml.XmlUTF8TextReader.s_charType, System.Xml.ValueHandle.SetCharValue(), System.Xml.XmlBaseReader.SignNode(), System.Xml.XmlExceptionHelper.ThrowInvalidRootData(), System.Xml.XmlExceptionHelper.ThrowInvalidXml(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Xml.XmlBaseReader.XmlNode.Value, System.SR.XmlCDATAInvalidAtTopLevel, System.SR.XmlCloseCData, and System.Xml.XmlException.