Terraria: System.Xml.XmlUTF8TextReader.ReadDeclaration
ReadDeclaration()
void System.Xml.XmlUTF8TextReader.ReadDeclaration () inline private
Definition at line 170 of file XmlUTF8TextReader.cs.
    {
        if (!_buffered)
        {
            BufferElement();
        }
        byte[] buffer = base.BufferReader.GetBuffer(5, out var offset);
        if (buffer[offset] != 63 || buffer[offset + 1] != 120 || buffer[offset + 2] != 109 || buffer[offset + 3] != 108 || (s_charType[buffer[offset + 4]] & 4) == 0)
        {
            XmlExceptionHelper.ThrowProcessingInstructionNotSupported(this);
        }
        if (base.Node.ReadState != 0)
        {
            XmlExceptionHelper.ThrowDeclarationNotFirst(this);
        }
        base.BufferReader.Advance(5);
        int offset2 = offset + 1;
        int length = 3;
        int offset3 = base.BufferReader.Offset;
        SkipWhitespace();
        ReadAttributes();
        int num;
        for (num = base.BufferReader.Offset - offset3; num > 0; num--)
        {
            byte @byte = base.BufferReader.GetByte(offset3 + num - 1);
            if ((s_charType[@byte] & 4) == 0)
            {
                break;
            }
        }
        buffer = base.BufferReader.GetBuffer(2, out offset);
        if (buffer[offset] != 63 || buffer[offset + 1] != 62)
        {
            XmlExceptionHelper.ThrowTokenExpected(this, "?>", Encoding.UTF8.GetString(buffer, offset, 2));
        }
        base.BufferReader.Advance(2);
        XmlDeclarationNode xmlDeclarationNode = MoveToDeclaration();
        xmlDeclarationNode.LocalName.SetValue(offset2, length);
        xmlDeclarationNode.Value.SetValue(ValueHandleType.UTF8, offset3, num);
    }
References System.Xml.XmlUTF8TextReader._buffered, System.buffer, System.Xml.XmlUTF8TextReader.BufferElement(), System.Xml.Dictionary, System.length, System.Xml.XmlBaseReader.MoveToDeclaration(), System.offset, System.Xml.XmlUTF8TextReader.ReadAttributes(), System.Xml.XmlUTF8TextReader.s_charType, System.Xml.XmlUTF8TextReader.SkipWhitespace(), System.Xml.XmlExceptionHelper.ThrowDeclarationNotFirst(), System.Xml.XmlExceptionHelper.ThrowProcessingInstructionNotSupported(), System.Xml.XmlExceptionHelper.ThrowTokenExpected(), and System.Text.Encoding.UTF8.
Referenced by System.Xml.XmlUTF8TextReader.Read().