Terraria: Terraria.Collision.CanHit
CanHit() [1/4]
static bool Terraria.Collision.CanHit (Entity source, Entity target) inline static
Definition at line 344 of file Collision.cs.
    {
        return CanHit(source.position, source.width, source.height, target.position, target.width, target.height);
    }
References Terraria.Collision.CanHit(), Terraria.Entity.height, Terraria.Entity.position, and Terraria.Entity.width.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_002_FloatingEye(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_015_Flails_Old(), Terraria.Projectile.AI_016(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_099_1(), Terraria.Projectile.AI_099_2(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_121_QueenSlime_FlyMovement(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Player.CanHit(), Terraria.Collision.CanHit(), Terraria.Collision.CanHit(), Terraria.Collision.CanHit(), Terraria.Projectile.CanHitWithMeleeWeapon(), Terraria.Projectile.CanHitWithOwnBody(), Terraria.Player.CanSnapToPosition(), Terraria.Player.CollideWithNPCs(), Terraria.Projectile.Colliding(), Terraria.Projectile.Damage(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.NPC.FindFrame(), Terraria.Projectile.FindTargetWithLineOfSight(), Terraria.Projectile.ghostHurt(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.JumpMovement(), Terraria.WorldGen.MakeDungeon_Lights(), Terraria.Utilities.NPCUtils.SearchForTarget(), Terraria.NPC.SpawnOnPlayer(), Terraria.Player.SporeSac(), Terraria.NPC.TargetClosestUpgraded(), Terraria.Player.TryAllowingSnappingToPosition(), Terraria.NPC.TryTrackingTarget(), Terraria.GameInput.LockOnHelper.Update(), and Terraria.Player.VolatileGelatin().