Terraria: Terraria.Collision.DistFromSeg
DistFromSeg()
static double Terraria.Collision.DistFromSeg (Vector2 p, Vector2 q0, Vector2 q1, double radius, ref float u) inline static private
Definition at line 93 of file Collision.cs.
    {
        double num = q1.X - q0.X;
        double num2 = q1.Y - q0.Y;
        double num3 = q0.X - p.X;
        double num4 = q0.Y - p.Y;
        double num5 = Math.Sqrt(num * num + num2 * num2);
        if (num5 < (double)Epsilon)
        {
            throw new Exception("Expected line segment, not point.");
        }
        return Math.Abs(num * num4 - num3 * num2) / num5;
    }
References System.Math.Abs(), Terraria.Collision.Epsilon, System.Math.Sqrt(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Collision.PointOnLine().