Terraria: Terraria.Collision.EmptyTile
EmptyTile()
static bool Terraria.Collision.EmptyTile (int i, int j, bool ignoreTiles = false) inline static
Definition at line 1149 of file Collision.cs.
    {
        Rectangle rectangle = new Rectangle(i * 16, j * 16, 16, 16);
        if (Main.tile[i, j].active() && !ignoreTiles)
        {
            return false;
        }
        for (int k = 0; k < 255; k++)
        {
            if (Main.player[k].active && !Main.player[k].dead && !Main.player[k].ghost && rectangle.Intersects(new Rectangle((int)Main.player[k].position.X, (int)Main.player[k].position.Y, Main.player[k].width, Main.player[k].height)))
            {
                return false;
            }
        }
        for (int l = 0; l < 200; l++)
        {
            if (Main.npc[l].active && rectangle.Intersects(new Rectangle((int)Main.npc[l].position.X, (int)Main.npc[l].position.Y, Main.npc[l].width, Main.npc[l].height)))
            {
                return false;
            }
        }
        return true;
    }
References Terraria.Main.npc, Terraria.Main.player, and Terraria.Main.tile.
Referenced by Terraria.WorldGen.CloseDoor(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.ShiftTallGate(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), and Terraria.GameContent.SmartCursorHelper.Step_ClayPots().