Terraria: Terraria.Collision.TupleHitLine
TupleHitLine()
static bool Terraria.Collision.TupleHitLine (int x1, int y1, int x2, int y2, int ignoreX, int ignoreY, List< Tuple< int, int > > ignoreTargets, out Tuple< int, int > col) inline static
Definition at line 743 of file Collision.cs.
    {
        int value = x1;
        int value2 = y1;
        int value3 = x2;
        int value4 = y2;
        value = Utils.Clamp(value, 1, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 1, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 1, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 1, Main.maxTilesY - 1);
        float num = Math.Abs(value - value3);
        float num2 = Math.Abs(value2 - value4);
        if (num == 0f && num2 == 0f)
        {
            col = new Tuple<int, int>(value, value2);
            return true;
        }
        float num3 = 1f;
        float num4 = 1f;
        if (num == 0f || num2 == 0f)
        {
            if (num == 0f)
            {
                num3 = 0f;
            }
            if (num2 == 0f)
            {
                num4 = 0f;
            }
        }
        else if (num > num2)
        {
            num3 = num / num2;
        }
        else
        {
            num4 = num2 / num;
        }
        float num5 = 0f;
        float num6 = 0f;
        int num7 = 1;
        if (value2 < value4)
        {
            num7 = 2;
        }
        int num8 = (int)num;
        int num9 = (int)num2;
        int num10 = Math.Sign(value3 - value);
        int num11 = Math.Sign(value4 - value2);
        bool flag = false;
        bool flag2 = false;
        try
        {
            do
            {
                switch (num7)
                {
                case 2:
                {
                    num5 += num3;
                    int num13 = (int)num5;
                    num5 %= 1f;
                    for (int j = 0; j < num13; j++)
                    {
                        if (Main.tile[value, value2 - 1] == null)
{
                            col = new Tuple<int, int>(value, value2 - 1);
                            return false;
                        }
                        if (Main.tile[value, value2 + 1] == null)
{
                            col = new Tuple<int, int>(value, value2 + 1);
                            return false;
                        }
                        Tile tile4 = Main.tile[value, value2 - 1];
                        Tile tile5 = Main.tile[value, value2 + 1];
                        Tile tile6 = Main.tile[value, value2];
                        if (!ignoreTargets.Contains(new Tuple<int, int>(value, value2)) && !ignoreTargets.Contains(new Tuple<int, int>(value, value2 - 1)) && !ignoreTargets.Contains(new Tuple<int, int>(value, value2 + 1)))
{
                            if (ignoreY != -1 && num11 < 0 && !tile4.inActive() && tile4.active() && Main.tileSolid[tile4.type] && !Main.tileSolidTop[tile4.type])
{
                                col = new Tuple<int, int>(value, value2 - 1);
                                return true;
                            }
                            if (ignoreY != 1 && num11 > 0 && !tile5.inActive() && tile5.active() && Main.tileSolid[tile5.type] && !Main.tileSolidTop[tile5.type])
{
                                col = new Tuple<int, int>(value, value2 + 1);
                                return true;
                            }
                            if (!tile6.inActive() && tile6.active() && Main.tileSolid[tile6.type] && !Main.tileSolidTop[tile6.type])
{
                                col = new Tuple<int, int>(value, value2);
                                return true;
                            }
                        }
                        if (num8 == 0 && num9 == 0)
{
                            flag = true;
                            break;
                        }
                        value += num10;
                        num8--;
                        if (num8 == 0 && num9 == 0 && num13 == 1)
{
                            flag2 = true;
                        }
                    }
                    if (num9 != 0)
                    {
                        num7 = 1;
                    }
                    break;
                }
                case 1:
                {
                    num6 += num4;
                    int num12 = (int)num6;
                    num6 %= 1f;
                    for (int i = 0; i < num12; i++)
                    {
                        if (Main.tile[value - 1, value2] == null)
{
                            col = new Tuple<int, int>(value - 1, value2);
                            return false;
                        }
                        if (Main.tile[value + 1, value2] == null)
{
                            col = new Tuple<int, int>(value + 1, value2);
                            return false;
                        }
                        Tile tile = Main.tile[value - 1, value2];
                        Tile tile2 = Main.tile[value + 1, value2];
                        Tile tile3 = Main.tile[value, value2];
                        if (!ignoreTargets.Contains(new Tuple<int, int>(value, value2)) && !ignoreTargets.Contains(new Tuple<int, int>(value - 1, value2)) && !ignoreTargets.Contains(new Tuple<int, int>(value + 1, value2)))
{
                            if (ignoreX != -1 && num10 < 0 && !tile.inActive() && tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
{
                                col = new Tuple<int, int>(value - 1, value2);
                                return true;
                            }
                            if (ignoreX != 1 && num10 > 0 && !tile2.inActive() && tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type])
{
                                col = new Tuple<int, int>(value + 1, value2);
                                return true;
                            }
                            if (!tile3.inActive() && tile3.active() && Main.tileSolid[tile3.type] && !Main.tileSolidTop[tile3.type])
{
                                col = new Tuple<int, int>(value, value2);
                                return true;
                            }
                        }
                        if (num8 == 0 && num9 == 0)
{
                            flag = true;
                            break;
                        }
                        value2 += num11;
                        num9--;
                        if (num8 == 0 && num9 == 0 && num12 == 1)
{
                            flag2 = true;
                        }
                    }
                    if (num8 != 0)
                    {
                        num7 = 2;
                    }
                    break;
                }
                }
                if (Main.tile[value, value2] == null)
                {
                    col = new Tuple<int, int>(value, value2);
                    return false;
                }
                Tile tile7 = Main.tile[value, value2];
                if (!ignoreTargets.Contains(new Tuple<int, int>(value, value2)) && !tile7.inActive() && tile7.active() && Main.tileSolid[tile7.type] && !Main.tileSolidTop[tile7.type])
                {
                    col = new Tuple<int, int>(value, value2);
                    return true;
                }
            }
            while (!(flag || flag2));
            col = new Tuple<int, int>(value, value2);
            return true;
        }
        catch
        {
            col = new Tuple<int, int>(x1, y1);
            return false;
        }
    }
References System.Math.Abs(), Terraria.Tile.active(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), Terraria.Tile.inActive(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Sign(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and System.value.
Referenced by Terraria.Collision.LaserScan(), and Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids().