Terraria: Terraria.Collision.GetWaterLine
GetWaterLine() [2/2]
static bool Terraria.Collision.GetWaterLine (Point pt, out float waterLineHeight) inline static
    {
        return GetWaterLine(pt.X, pt.Y, out waterLineHeight);
    }
References Terraria.Collision.GetWaterLine().
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_116_WaterStriders(), Terraria.Collision.GetWaterLine(), and Terraria.Player.TryFloatingInFluid().