Terraria: Terraria.Collision.TupleHitLineWall
TupleHitLineWall()
static Tuple< int, int > Terraria.Collision.TupleHitLineWall (int x1, int y1, int x2, int y2) inline static
Definition at line 936 of file Collision.cs.
    {
        int num = x1;
        int num2 = y1;
        int num3 = x2;
        int num4 = y2;
        if (num <= 1)
        {
            num = 1;
        }
        if (num >= Main.maxTilesX)
        {
            num = Main.maxTilesX - 1;
        }
        if (num3 <= 1)
        {
            num3 = 1;
        }
        if (num3 >= Main.maxTilesX)
        {
            num3 = Main.maxTilesX - 1;
        }
        if (num2 <= 1)
        {
            num2 = 1;
        }
        if (num2 >= Main.maxTilesY)
        {
            num2 = Main.maxTilesY - 1;
        }
        if (num4 <= 1)
        {
            num4 = 1;
        }
        if (num4 >= Main.maxTilesY)
        {
            num4 = Main.maxTilesY - 1;
        }
        float num5 = Math.Abs(num - num3);
        float num6 = Math.Abs(num2 - num4);
        if (num5 == 0f && num6 == 0f)
        {
            return new Tuple<int, int>(num, num2);
        }
        float num7 = 1f;
        float num8 = 1f;
        if (num5 == 0f || num6 == 0f)
        {
            if (num5 == 0f)
            {
                num7 = 0f;
            }
            if (num6 == 0f)
            {
                num8 = 0f;
            }
        }
        else if (num5 > num6)
        {
            num7 = num5 / num6;
        }
        else
        {
            num8 = num6 / num5;
        }
        float num9 = 0f;
        float num10 = 0f;
        int num11 = 1;
        if (num2 < num4)
        {
            num11 = 2;
        }
        int num12 = (int)num5;
        int num13 = (int)num6;
        int num14 = Math.Sign(num3 - num);
        int num15 = Math.Sign(num4 - num2);
        bool flag = false;
        bool flag2 = false;
        try
        {
            do
            {
                switch (num11)
                {
                case 2:
                {
                    num9 += num7;
                    int num17 = (int)num9;
                    num9 %= 1f;
                    for (int j = 0; j < num17; j++)
                    {
                        _ = Main.tile[num, num2];
                        if (HitWallSubstep(num, num2))
{
                            return new Tuple<int, int>(num, num2);
                        }
                        if (num12 == 0 && num13 == 0)
{
                            flag = true;
                            break;
                        }
                        num += num14;
                        num12--;
                        if (num12 == 0 && num13 == 0 && num17 == 1)
{
                            flag2 = true;
                        }
                    }
                    if (num13 != 0)
                    {
                        num11 = 1;
                    }
                    break;
                }
                case 1:
                {
                    num10 += num8;
                    int num16 = (int)num10;
                    num10 %= 1f;
                    for (int i = 0; i < num16; i++)
                    {
                        _ = Main.tile[num, num2];
                        if (HitWallSubstep(num, num2))
{
                            return new Tuple<int, int>(num, num2);
                        }
                        if (num12 == 0 && num13 == 0)
{
                            flag = true;
                            break;
                        }
                        num2 += num15;
                        num13--;
                        if (num12 == 0 && num13 == 0 && num16 == 1)
{
                            flag2 = true;
                        }
                    }
                    if (num12 != 0)
                    {
                        num11 = 2;
                    }
                    break;
                }
                }
                if (Main.tile[num, num2] == null)
                {
                    return new Tuple<int, int>(-1, -1);
                }
                _ = Main.tile[num, num2];
                if (HitWallSubstep(num, num2))
                {
                    return new Tuple<int, int>(num, num2);
                }
            }
            while (!(flag || flag2));
            return new Tuple<int, int>(num, num2);
        }
        catch
        {
            return new Tuple<int, int>(-1, -1);
        }
    }
References System.Math.Abs(), Terraria.Collision.HitWallSubstep(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Sign(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.SmartCursorHelper.Step_Hammers().