Terraria: Terraria.Collision.ExpandVertically
ExpandVertically()
static void Terraria.Collision.ExpandVertically (int startX, int startY, out int topY, out int bottomY, int maxExpandUp = 100, int maxExpandDown = 100) inline static
Definition at line 3519 of file Collision.cs.
    {
        topY = startY;
        bottomY = startY;
        if (!WorldGen.InWorld(startX, startY, 10))
        {
            return;
        }
        for (int i = 0; i < maxExpandUp; i++)
        {
            if (topY <= 0)
            {
                break;
            }
            if (topY < 10)
            {
                break;
            }
            if (Main.tile[startX, topY] == null)
            {
                break;
            }
            if (WorldGen.SolidTile3(startX, topY))
            {
                break;
            }
            topY--;
        }
        for (int j = 0; j < maxExpandDown; j++)
        {
            if (bottomY >= Main.maxTilesY - 10)
            {
                break;
            }
            if (bottomY > Main.maxTilesY - 10)
            {
                break;
            }
            if (Main.tile[startX, bottomY] == null)
            {
                break;
            }
            if (WorldGen.SolidTile3(startX, bottomY))
            {
                break;
            }
            bottomY++;
        }
    }
References Terraria.WorldGen.InWorld(), Terraria.Main.maxTilesY, Terraria.WorldGen.SolidTile3(), and Terraria.Main.tile.
Referenced by Terraria.NPC.AI(), Terraria.StrayMethods.CanSpawnSandstormFriendly(), Terraria.StrayMethods.CanSpawnSandstormHostile(), Terraria.StrayMethods.CheckArenaScore(), Terraria.Main.DrawProjDirect(), and Terraria.StrayMethods.SendWalker().