Terraria: Terraria.Collision.OneDimensionalIntersection
OneDimensionalIntersection()
static Vector2[] Terraria.Collision.OneDimensionalIntersection (Vector2 a1, Vector2 a2, Vector2 b1, Vector2 b2) inline static private
Definition at line 113 of file Collision.cs.
    {
        float num = a2.X - a1.X;
        float num2 = a2.Y - a1.Y;
        float relativePoint;
        float relativePoint2;
        if (Math.Abs(num) > Math.Abs(num2))
        {
            relativePoint = (b1.X - a1.X) / num;
            relativePoint2 = (b2.X - a1.X) / num;
        }
        else
        {
            relativePoint = (b1.Y - a1.Y) / num2;
            relativePoint2 = (b2.Y - a1.Y) / num2;
        }
        List<Vector2> list = new List<Vector2>();
        float[] array = FindOverlapPoints(relativePoint, relativePoint2);
        foreach (float num3 in array)
        {
            float x = a2.X * num3 + a1.X * (1f - num3);
            float y = a2.Y * num3 + a1.Y * (1f - num3);
            list.Add(new Vector2(x, y));
        }
        return list.ToArray();
    }
References System.Math.Abs(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, Terraria.Collision.FindOverlapPoints(), and System.list.
Referenced by Terraria.Collision.CheckLinevLine().