Terraria: Terraria.Collision.AnyCollision
AnyCollision()
static Vector2 Terraria.Collision.AnyCollision (Vector2 Position, Vector2 Velocity, int Width, int Height, bool evenActuated = false) inline static
    {
        Vector2 result = Velocity;
        Vector2 vector = Velocity;
        Vector2 vector2 = Position + Velocity;
        Vector2 vector3 = Position;
        int num = (int)(Position.X / 16f) - 1;
        int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int num3 = (int)(Position.Y / 16f) - 1;
        int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num5 = -1;
        int num6 = -1;
        int num7 = -1;
        int num8 = -1;
        if (num < 0)
        {
            num = 0;
        }
        if (num2 > Main.maxTilesX)
        {
            num2 = Main.maxTilesX;
        }
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesY)
        {
            num4 = Main.maxTilesY;
        }
        Vector2 vector4 = default(Vector2);
        for (int i = num; i < num2; i++)
        {
            for (int j = num3; j < num4; j++)
            {
                if (Main.tile[i, j] == null || !Main.tile[i, j].active() || (!evenActuated && Main.tile[i, j].inActive()))
                {
                    continue;
                }
                vector4.X = i * 16;
                vector4.Y = j * 16;
                int num9 = 16;
                if (Main.tile[i, j].halfBrick())
                {
                    vector4.Y += 8f;
                    num9 -= 8;
                }
                if (!(vector2.X + (float)Width > vector4.X) || !(vector2.X < vector4.X + 16f) || !(vector2.Y + (float)Height > vector4.Y) || !(vector2.Y < vector4.Y + (float)num9))
                {
                    continue;
                }
                if (vector3.Y + (float)Height <= vector4.Y)
                {
                    num7 = i;
                    num8 = j;
                    if (num7 != num5)
                    {
                        result.Y = vector4.Y - (vector3.Y + (float)Height);
                    }
                }
                else if (vector3.X + (float)Width <= vector4.X && !Main.tileSolidTop[Main.tile[i, j].type])
                {
                    num5 = i;
                    num6 = j;
                    if (num6 != num8)
                    {
                        result.X = vector4.X - (vector3.X + (float)Width);
                    }
                    if (num7 == num5)
                    {
                        result.Y = vector.Y;
                    }
                }
                else if (vector3.X >= vector4.X + 16f && !Main.tileSolidTop[Main.tile[i, j].type])
                {
                    num5 = i;
                    num6 = j;
                    if (num6 != num8)
                    {
                        result.X = vector4.X + 16f - vector3.X;
                    }
                    if (num7 == num5)
                    {
                        result.Y = vector.Y;
                    }
                }
                else if (vector3.Y >= vector4.Y + (float)num9 && !Main.tileSolidTop[Main.tile[i, j].type])
                {
                    num7 = i;
                    num8 = j;
                    result.Y = vector4.Y + (float)num9 - vector3.Y + 0.01f;
                    if (num8 == num6)
                    {
                        result.X = vector.X + 0.01f;
                    }
                }
            }
        }
        return result;
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolidTop, and Terraria.Tile.type.