Terraria: System.Security.Cryptography.ThrowHelper.ValidateTransformBlock
ValidateTransformBlock()
static void System.Security.Cryptography.ThrowHelper.ValidateTransformBlock (byte[] inputBuffer, int inputOffset, int inputCount) inline static
Definition at line 17 of file ThrowHelper.cs.
    {
        if (inputBuffer == null)
        {
            ThrowArgumentNull(ExceptionArgument.inputBuffer);
        }
        if ((uint)inputCount > inputBuffer.Length)
        {
            ThrowArgumentOutOfRange(ExceptionArgument.inputCount);
        }
        if (inputOffset < 0)
        {
            ThrowArgumentOutOfRange(ExceptionArgument.inputOffset);
        }
        if (inputBuffer.Length - inputCount < inputOffset)
        {
            ThrowInvalidOffLen();
        }
    }
References System.Security.Cryptography.ThrowHelper.inputBuffer, System.Security.Cryptography.ThrowHelper.inputCount, System.Security.Cryptography.ThrowHelper.inputOffset, System.Security.Cryptography.ThrowHelper.ThrowArgumentNull(), System.Security.Cryptography.ThrowHelper.ThrowArgumentOutOfRange(), and System.Security.Cryptography.ThrowHelper.ThrowInvalidOffLen().
Referenced by System.Security.Cryptography.FromBase64Transform.TransformBlock(), System.Security.Cryptography.ToBase64Transform.TransformBlock(), System.Security.Cryptography.FromBase64Transform.TransformFinalBlock(), and System.Security.Cryptography.ToBase64Transform.TransformFinalBlock().