Terraria: System.Reflection.CerHashtable.Table.Insert
Insert()
void System.Reflection.CerHashtable< K, V >.Table.Insert (K key, V value) inline package
Definition at line 23 of file CerHashtable.cs.
        {
            int num = CerHashtable<K, V>.GetHashCodeHelper(key);
            if (num < 0)
            {
                num = ~num;
            }
            K[] keys = m_keys;
            int num2 = num % keys.Length;
            while (true)
            {
                K val = keys[num2];
                if (val == null)
                {
                    break;
                }
                num2++;
                if (num2 >= keys.Length)
                {
                    num2 -= keys.Length;
                }
            }
            m_count++;
            m_values[num2] = value;
            Volatile.Write(ref keys[num2], key);
        }
References System.Reflection.CerHashtable< K, V >.GetHashCodeHelper(), System.key, System.keys, System.Reflection.CerHashtable< K, V >.Table.m_count, System.Reflection.CerHashtable< K, V >.Table.m_keys, System.Reflection.CerHashtable< K, V >.Table.m_values, System.value, and System.Threading.Volatile.Write().
Referenced by System.Reflection.CerHashtable< K, V >.Rehash().