Terraria: System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexing
EncodeLiteralHeaderFieldWithoutIndexing() [2/2]
static bool System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexing (int index, string value, Encoding valueEncoding, Span< byte > destination, out int bytesWritten) inline static
Definition at line 18 of file HPackEncoder.cs.
    {
        if ((uint)destination.Length >= 2u)
        {
            destination[0] = 0;
            if (IntegerEncoder.Encode(index, 4, destination, out var bytesWritten2) && EncodeStringLiteral(value, valueEncoding, destination.Slice(bytesWritten2), out var bytesWritten3))
            {
                bytesWritten = bytesWritten2 + bytesWritten3;
                return true;
            }
        }
        bytesWritten = 0;
        return false;
    }
References System.destination, System.Net.Http.HPack.IntegerEncoder.Encode(), System.Net.Http.HPack.HPackEncoder.EncodeStringLiteral(), System.index, and System.value.
Referenced by System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray(), System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray(), and System.Net.Http.Http2Connection.WriteIndexedHeader().