Terraria: System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray
EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray() [1/2]
static byte[] System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray (int index) inline static
Definition at line 220 of file HPackEncoder.cs.
    {
        Span<byte> destination = stackalloc byte[256];
        int bytesWritten;
        bool flag = EncodeLiteralHeaderFieldWithoutIndexing(index, destination, out bytesWritten);
        return destination.Slice(0, bytesWritten).ToArray();
    }
References System.destination, System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexing(), and System.index.
Referenced by System.Net.Http.HttpConnectionPool.HttpConnectionPool(), and System.Net.Http.Headers.KnownHeader.Initialize().