Terraria: System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderName
EncodeLiteralHeaderName()
static bool System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderName (string value, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 78 of file HPackEncoder.cs.
    {
        if (destination.Length != 0)
        {
            destination[0] = 0;
            if (IntegerEncoder.Encode(value.Length, 7, destination, out var bytesWritten2))
            {
                destination = destination.Slice(bytesWritten2);
                if (value.Length <= destination.Length)
                {
                    for (int i = 0; i < value.Length; i++)
                    {
                        char c = value[i];
                        destination[i] = (byte)(((uint)(c - 65) <= 25u) ? (c | 0x20u) : c);
                    }
                    bytesWritten = bytesWritten2 + value.Length;
                    return true;
                }
            }
        }
        bytesWritten = 0;
        return false;
    }
References System.destination, System.Net.Http.HPack.IntegerEncoder.Encode(), and System.value.
Referenced by System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewName(), and System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewName().