Terraria: System.Net.Http.HPack.HPackEncoder.EncodeStringLiteral
EncodeStringLiteral()
static bool System.Net.Http.HPack.HPackEncoder.EncodeStringLiteral (string value, Encoding valueEncoding, Span< byte > destination, out int bytesWritten) inline static
Definition at line 115 of file HPackEncoder.cs.
    {
        if (destination.Length != 0)
        {
            destination[0] = 0;
            int num = ((valueEncoding == null || valueEncoding == Encoding.Latin1) ? value.Length : valueEncoding.GetByteCount(value));
            if (IntegerEncoder.Encode(num, 7, destination, out var bytesWritten2))
            {
                destination = destination.Slice(bytesWritten2);
                if (num <= destination.Length)
                {
                    if (valueEncoding == null)
                    {
                        EncodeValueStringPart(value, destination);
                    }
                    else
                    {
                        int bytes = valueEncoding.GetBytes(value, destination);
                    }
                    bytesWritten = bytesWritten2 + num;
                    return true;
                }
            }
        }
        bytesWritten = 0;
        return false;
    }
References System.bytes, System.destination, System.Net.Http.HPack.IntegerEncoder.Encode(), System.Net.Http.HPack.HPackEncoder.EncodeValueStringPart(), System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.Text.Encoding.Latin1, and System.value.
Referenced by System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexing(), System.Net.Http.HPack.HPackEncoder.EncodeStringLiterals(), and System.Net.Http.Http2Connection.WriteLiteralHeaderValue().