Terraria: System.Net.Http.HPack.HPackEncoder.EncodeStringLiterals
EncodeStringLiterals()
static bool System.Net.Http.HPack.HPackEncoder.EncodeStringLiterals (ReadOnlySpan< string > values, string separator, Encoding valueEncoding, Span< byte > destination, out int bytesWritten) inline static
Definition at line 143 of file HPackEncoder.cs.
    {
        bytesWritten = 0;
        if (values.Length == 0)
        {
            return EncodeStringLiteral("", null, destination, out bytesWritten);
        }
        if (values.Length == 1)
        {
            return EncodeStringLiteral(values[0], valueEncoding, destination, out bytesWritten);
        }
        if (destination.Length != 0)
        {
            int num;
            checked
            {
                if (valueEncoding == null || valueEncoding == Encoding.Latin1)
                {
                    num = (values.Length - 1) * separator.Length;
                    ReadOnlySpan<string> readOnlySpan = values;
                    for (int i = 0; i < readOnlySpan.Length; i = unchecked(i + 1))
                    {
                        string text = readOnlySpan[i];
                        num += text.Length;
                    }
                }
                else
                {
                    num = (values.Length - 1) * valueEncoding.GetByteCount(separator);
                    ReadOnlySpan<string> readOnlySpan2 = values;
                    for (int j = 0; j < readOnlySpan2.Length; j = unchecked(j + 1))
                    {
                        string s = readOnlySpan2[j];
                        num += valueEncoding.GetByteCount(s);
                    }
                }
                destination[0] = 0;
            }
            if (IntegerEncoder.Encode(num, 7, destination, out var bytesWritten2))
            {
                destination = destination.Slice(bytesWritten2);
                if (destination.Length >= num)
                {
                    if (valueEncoding == null)
                    {
                        string text2 = values[0];
                        EncodeValueStringPart(text2, destination);
                        destination = destination.Slice(text2.Length);
                        for (int k = 1; k < values.Length; k++)
{
                            EncodeValueStringPart(separator, destination);
                            destination = destination.Slice(separator.Length);
                            text2 = values[k];
                            EncodeValueStringPart(text2, destination);
                            destination = destination.Slice(text2.Length);
                        }
                    }
                    else
                    {
                        int bytes = valueEncoding.GetBytes(values[0], destination);
                        destination = destination.Slice(bytes);
                        for (int l = 1; l < values.Length; l++)
{
                            bytes = valueEncoding.GetBytes(separator, destination);
                            destination = destination.Slice(bytes);
                            bytes = valueEncoding.GetBytes(values[l], destination);
                            destination = destination.Slice(bytes);
                        }
                    }
                    bytesWritten = bytesWritten2 + num;
                    return true;
                }
            }
        }
        return false;
    }
References System.bytes, System.destination, System.Net.Http.HPack.IntegerEncoder.Encode(), System.Net.Http.HPack.HPackEncoder.EncodeStringLiteral(), System.Net.Http.HPack.HPackEncoder.EncodeValueStringPart(), System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), System.Text.Encoding.Latin1, System.ReadOnlySpan< T >.Length, System.s, System.text, and System.values.
Referenced by System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewName(), and System.Net.Http.Http2Connection.WriteLiteralHeaderValues().