Terraria: System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewName
EncodeLiteralHeaderFieldWithoutIndexingNewName() [1/2]
static bool System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewName (string name, ReadOnlySpan< string > values, string separator, Encoding valueEncoding, Span< byte > destination, out int bytesWritten) inline static
Definition at line 48 of file HPackEncoder.cs.
    {
        if ((uint)destination.Length >= 3u)
        {
            destination[0] = 0;
            if (EncodeLiteralHeaderName(name, destination.Slice(1), out var bytesWritten2) && EncodeStringLiterals(values, separator, valueEncoding, destination.Slice(1 + bytesWritten2), out var bytesWritten3))
            {
                bytesWritten = 1 + bytesWritten2 + bytesWritten3;
                return true;
            }
        }
        bytesWritten = 0;
        return false;
    }
References System.destination, System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderName(), System.Net.Http.HPack.HPackEncoder.EncodeStringLiterals(), and System.values.
Referenced by System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewNameToAllocatedArray(), and System.Net.Http.Http2Connection.WriteLiteralHeader().