Terraria: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.SacrificeWhatYouCan
SacrificeWhatYouCan()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.SacrificeWhatYouCan () inline
Definition at line 473 of file UICreativeInfiniteItemsDisplay.cs.
    {
        Main.CreativeMenu.GetSacrificeNumbers(out var itemIdChecked, out var amountWeHave, out var amountNeededTotal);
        int amountWeSacrificed;
        switch (Main.CreativeMenu.SacrificeItem(out amountWeSacrificed))
        {
        case CreativeUI.ItemSacrificeResult.SacrificedAndDone:
            _researchComplete = true;
            BeginSacrificeAnimation();
            RememberItemSacrifice(itemIdChecked, amountWeHave + amountWeSacrificed, amountNeededTotal);
            break;
        case CreativeUI.ItemSacrificeResult.SacrificedButNotDone:
            _researchComplete = false;
            BeginSacrificeAnimation();
            RememberItemSacrifice(itemIdChecked, amountWeHave + amountWeSacrificed, amountNeededTotal);
            break;
        }
    }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._researchComplete, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BeginSacrificeAnimation(), Terraria.Main.CreativeMenu, and Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.RememberItemSacrifice().
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.sacrificeButton_OnClick(), and Terraria.GameContent.UI.States.UICreativePowersMenu.SacrificeWhatsInResearchMenu().