Terraria: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildPage
BuildPage()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildPage () inline private
Definition at line 125 of file UICreativeInfiniteItemsDisplay.cs.
    {
        _lastCheckedVersionForEdits = -1;
        RemoveAllChildren();
        SetPadding(0f);
        UIElement uIElement = new UIElement
        {
            Width = StyleDimension.Fill,
            Height = StyleDimension.Fill
        };
        uIElement.SetPadding(0f);
        _containerInfinites = uIElement;
        UIElement uIElement2 = new UIElement
        {
            Width = StyleDimension.Fill,
            Height = StyleDimension.Fill
        };
        uIElement2.SetPadding(0f);
        _containerSacrifice = uIElement2;
        BuildInfinitesMenuContents(uIElement);
        BuildSacrificeMenuContents(uIElement2);
        UpdateContents();
        base.OnUpdate += UICreativeInfiniteItemsDisplay_OnUpdate;
    }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._containerInfinites, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._containerSacrifice, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._lastCheckedVersionForEdits, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents(), Terraria.UI.StyleDimension.Fill, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.RemoveAllChildren(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay_OnUpdate(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UpdateContents(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay().