Terraria: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OnFinishedSettingName
OnFinishedSettingName()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OnFinishedSettingName (string name) inline private
Definition at line 736 of file UICreativeInfiniteItemsDisplay.cs.
    {
        string contents = name.Trim();
        _searchBar.SetContents(contents);
        GoBackHere();
    }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._searchBar, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GoBackHere(), and Terraria.GameContent.UI.Elements.UISearchBar.SetContents().
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OpenVirtualKeyboardWhenNeeded().