Terraria: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UpdateVisualFrame
UpdateVisualFrame()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UpdateVisualFrame () inline private
Definition at line 356 of file UICreativeInfiniteItemsDisplay.cs.
    {
        float num = 0.05f;
        float sacrificeAnimationProgress = GetSacrificeAnimationProgress();
        float lerpValue = Utils.GetLerpValue(1f, 0.7f, sacrificeAnimationProgress, clamped: true);
        float num2 = lerpValue * lerpValue;
        num2 *= 2f;
        float num3 = 1f + num2;
        num *= num3;
        float num4 = 1.1428572f;
        float num5 = 1f;
        OffsetRotationsForCogs(2f * num, _sacrificeCogsSmall);
        OffsetRotationsForCogs(num4 * num, _sacrificeCogsMedium);
        OffsetRotationsForCogs((0f - num5) * num, _sacrificeCogsBig);
        int frameY = 0;
        if (_sacrificeAnimationTimeLeft != 0)
        {
            float num6 = 0.1f;
            float num7 = 1f / 15f;
            frameY = ((sacrificeAnimationProgress >= 1f - num6) ? 8 : ((sacrificeAnimationProgress >= 1f - num6 * 2f) ? 7 : ((sacrificeAnimationProgress >= 1f - num6 * 3f) ? 6 : ((sacrificeAnimationProgress >= num7 * 4f) ? 5 : ((sacrificeAnimationProgress >= num7 * 3f) ? 4 : ((sacrificeAnimationProgress >= num7 * 2f) ? 3 : ((!(sacrificeAnimationProgress >= num7)) ? 1 : 2)))))));
            if (_sacrificeAnimationTimeLeft == 56)
            {
                SoundEngine.PlaySound(63);
                Vector2 accelerationPerFrame = new Vector2(0f, 0.16350001f);
                for (int i = 0; i < 15; i++)
                {
                    Vector2 initialVelocity = Main.rand.NextVector2Circular(4f, 3f);
                    if (initialVelocity.Y > 0f)
                    {
                        initialVelocity.Y = 0f - initialVelocity.Y;
                    }
                    initialVelocity.Y -= 2f;
                    _pistonParticleSystem.AddParticle(new CreativeSacrificeParticle(_pistonParticleAsset, null, initialVelocity, Vector2.Zero)
                    {
                        AccelerationPerFrame = accelerationPerFrame,
                        ScaleOffsetPerFrame = -1f / 60f
                    });
                }
            }
            if (_sacrificeAnimationTimeLeft == 40 && _researchComplete)
            {
                _researchComplete = false;
                SoundEngine.PlaySound(64);
            }
        }
        _sacrificePistons.SetFrame(1, 9, 0, frameY, 0, 0);
    }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._pistonParticleAsset, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._pistonParticleSystem, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._researchComplete, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sacrificeAnimationTimeLeft, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sacrificeCogsBig, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sacrificeCogsMedium, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sacrificeCogsSmall, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sacrificePistons, Terraria.GameContent.UI.Elements.UIParticleLayer.AddParticle(), Terraria.Utils.GetLerpValue(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GetSacrificeAnimationProgress(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OffsetRotationsForCogs(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.GameContent.UI.Elements.UIImageFramed.SetFrame(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.sacrificeWindow_OnUpdate(), and Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.StopPlayingAnimation().