Terraria: DrawData.Draw
Draw() [1/2]
void DrawData.Draw (SpriteBatch sb) inline
     {
         if (useDestinationRectangle)
         {
             sb.Draw(texture, destinationRectangle, sourceRect, color, rotation, origin, effect, 0f);
         }
         else
         {
             sb.Draw(texture, position, sourceRect, color, rotation, origin, scale, effect, 0f);
         }
     }
References color, destinationRectangle, effect, origin, position, rotation, scale, sourceRect, texture, and useDestinationRectangle.
Referenced by Segments.SpriteSegment.Draw(), FlameParticle.Draw(), Main.DrawNPCDirect(), Main.DrawNPCDirect_HallowBoss(), PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), PlayerDrawLayers.DrawPlayer_RenderAllLayers(), PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow(), ReturnGatePlayerRenderer.DrawReturnGateInWorld(), TileDrawing.DrawVoidLenses(), Main.EntitySpriteDraw(), PlayerQueenSlimeMountTextureContent.HandleUseReqest(), PlayerRainbowWingsTextureContent.HandleUseReqest(), PlayerTitaniumStormBuffTextureContent.HandleUseReqest(), and MapHeadRenderer.RenderDrawData().