Terraria: System.Security.Cryptography.TripleDES.Create
Create() [1/2]
static new TripleDES System.Security.Cryptography.TripleDES.Create () inline static inherited
Definition at line 59 of file TripleDES.cs.
    {
        return new TripleDesImplementation();
    }
Referenced by System.Security.Cryptography.TripleDESCryptoServiceProvider.TripleDESCryptoServiceProvider(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.InitiateEncryption(), System.Security.Cryptography.PasswordBasedEncryption.OpenCipher(), and System.Security.Cryptography.PasswordBasedEncryption.OpenCipher().