Terraria: System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddArray
AddArray()
void System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddArray (string name, TraceLoggingDataType type) inline
Definition at line 165 of file TraceLoggingMetadataCollector.cs.
    {
        switch (type & (TraceLoggingDataType)31)
        {
        default:
            throw new ArgumentOutOfRangeException("type");
        case TraceLoggingDataType.Int8:
        case TraceLoggingDataType.UInt8:
        case TraceLoggingDataType.Int16:
        case TraceLoggingDataType.UInt16:
        case TraceLoggingDataType.Int32:
        case TraceLoggingDataType.UInt32:
        case TraceLoggingDataType.Int64:
        case TraceLoggingDataType.UInt64:
        case TraceLoggingDataType.Float:
        case TraceLoggingDataType.Double:
        case TraceLoggingDataType.Boolean32:
        case TraceLoggingDataType.Guid:
        case TraceLoggingDataType.FileTime:
        case TraceLoggingDataType.HexInt32:
        case TraceLoggingDataType.HexInt64:
        case TraceLoggingDataType.Char8:
        case TraceLoggingDataType.Char16:
            if (BeginningBufferedArray)
            {
                throw new NotSupportedException(SR.EventSource_NotSupportedNestedArraysEnums);
            }
            impl.AddScalar(2);
            impl.AddNonscalar();
            AddField(new FieldMetadata(name, type, Tags, variableCount: true));
            break;
        }
    }
References System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddField(), System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.AddNonscalar(), System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.AddScalar(), System.Diagnostics.Tracing.TraceLoggingMetadataCollector.BeginningBufferedArray, System.SR.EventSource_NotSupportedNestedArraysEnums, System.Diagnostics.Tracing.TraceLoggingMetadataCollector.impl, System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Tags, and System.type.
Referenced by System.Diagnostics.Tracing.ScalarArrayTypeInfo.WriteMetadata().