Terraria: System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddField
AddField()
void System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddField (FieldMetadata fieldMetadata) inline private
Definition at line 227 of file TraceLoggingMetadataCollector.cs.
    {
        Tags = EventFieldTags.None;
        bufferedArrayFieldCount++;
        impl.fields.Add(fieldMetadata);
        if (currentGroup != null)
        {
            currentGroup.IncrementStructFieldCount();
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Diagnostics.Tracing.TraceLoggingMetadataCollector.bufferedArrayFieldCount, System.Diagnostics.Tracing.TraceLoggingMetadataCollector.currentGroup, System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Impl.fields, System.Diagnostics.Tracing.TraceLoggingMetadataCollector.impl, System.Diagnostics.Tracing.FieldMetadata.IncrementStructFieldCount(), and System.Diagnostics.Tracing.TraceLoggingMetadataCollector.Tags.
Referenced by System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddArray(), System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddGroup(), System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddNullTerminatedString(), and System.Diagnostics.Tracing.TraceLoggingMetadataCollector.AddScalar().