Terraria: System.Net.Http.Headers.TransferCodingHeaderValue.ToString
ToString()
override string System.Net.Http.Headers.TransferCodingHeaderValue.ToString () inline inherited
Definition at line 86 of file TransferCodingHeaderValue.cs.
    {
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        stringBuilder.Append(_value);
        NameValueHeaderValue.ToString(_parameters, ';', leadingSeparator: true, stringBuilder);
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Net.Http.Headers.TransferCodingHeaderValue._parameters, System.Net.Http.Headers.TransferCodingHeaderValue._value, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilderCache.GetStringAndRelease(), and System.Net.Http.Headers.NameValueHeaderValue.ToString().