Terraria: System.Net.Http.Headers.TransferCodingHeaderValue.GetTransferCodingLength
GetTransferCodingLength()
static int System.Net.Http.Headers.TransferCodingHeaderValue.GetTransferCodingLength (string input, int startIndex, Func< TransferCodingHeaderValue > transferCodingCreator, out TransferCodingHeaderValue parsedValue) inline static package inherited
Definition at line 51 of file TransferCodingHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int tokenLength = HttpRuleParser.GetTokenLength(input, startIndex);
        if (tokenLength == 0)
        {
            return 0;
        }
        string value = input.Substring(startIndex, tokenLength);
        int num = startIndex + tokenLength;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        TransferCodingHeaderValue transferCodingHeaderValue;
        if (num < input.Length && input[num] == ';')
        {
            transferCodingHeaderValue = transferCodingCreator();
            transferCodingHeaderValue._value = value;
            num++;
            int nameValueListLength = NameValueHeaderValue.GetNameValueListLength(input, num, ';', (ObjectCollection<NameValueHeaderValue>)transferCodingHeaderValue.Parameters);
            if (nameValueListLength == 0)
            {
                return 0;
            }
            parsedValue = transferCodingHeaderValue;
            return num + nameValueListLength - startIndex;
        }
        transferCodingHeaderValue = transferCodingCreator();
        transferCodingHeaderValue._value = value;
        parsedValue = transferCodingHeaderValue;
        return num - startIndex;
    }
References System.Net.Http.Headers.NameValueHeaderValue.GetNameValueListLength(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, System.startIndex, and System.value.
Referenced by System.Net.Http.Headers.TransferCodingHeaderParser.GetParsedValueLength().