Terraria: System.Net.Mail.SmtpTransport.GetConnection
GetConnection()
void System.Net.Mail.SmtpTransport.GetConnection (string host, int port) inline package
Definition at line 103 of file SmtpTransport.cs.
    {
        lock (this)
        {
            _connection = new SmtpConnection(this, _client, _credentials, _authenticationModules);
            if (_shouldAbort)
            {
                _connection.Abort();
            }
            _shouldAbort = false;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Associate(this, _connection, "GetConnection");
        }
        if (EnableSsl)
        {
            _connection.EnableSsl = true;
            _connection.ClientCertificates = ClientCertificates;
        }
        _connection.GetConnection(host, port);
    }
References System.Net.Mail.SmtpTransport._authenticationModules, System.Net.Mail.SmtpTransport._client, System.Net.Mail.SmtpTransport._connection, System.Net.Mail.SmtpTransport._credentials, System.Net.Mail.SmtpTransport._shouldAbort, System.Net.Mail.SmtpConnection.Abort(), System.Net.NetEventSource.Associate(), System.Net.Mail.SmtpTransport.ClientCertificates, System.Net.Mail.SmtpTransport.EnableSsl, System.Net.Mail.SmtpConnection.GetConnection(), and System.Net.NetEventSource.Log.
Referenced by System.Net.Mail.SmtpClient.GetConnection().