Terraria: System.Net.Mail.SmtpTransport.SendMail
SendMail()
MailWriter System.Net.Mail.SmtpTransport.SendMail (MailAddress sender, MailAddressCollection recipients, string deliveryNotify, bool allowUnicode, out SmtpFailedRecipientException exception) inline package
Definition at line 199 of file SmtpTransport.cs.
    {
        if (sender == null)
        {
            throw new ArgumentNullException("sender");
        }
        if (recipients == null)
        {
            throw new ArgumentNullException("recipients");
        }
        MailCommand.Send(_connection, SmtpCommands.Mail, sender, allowUnicode);
        _failedRecipientExceptions.Clear();
        exception = null;
        foreach (MailAddress recipient in recipients)
        {
            string smtpAddress = recipient.GetSmtpAddress(allowUnicode);
            string to = smtpAddress + (_connection.DSNEnabled ? deliveryNotify : string.Empty);
            if (!RecipientCommand.Send(_connection, to, out var response))
            {
                _failedRecipientExceptions.Add(new SmtpFailedRecipientException(_connection.Reader.StatusCode, smtpAddress, response));
            }
        }
        if (_failedRecipientExceptions.Count > 0)
        {
            if (_failedRecipientExceptions.Count == 1)
            {
                exception = _failedRecipientExceptions[0];
            }
            else
            {
                exception = new SmtpFailedRecipientsException(_failedRecipientExceptions, _failedRecipientExceptions.Count == recipients.Count);
            }
            if (_failedRecipientExceptions.Count == recipients.Count)
            {
                exception.fatal = true;
                throw exception;
            }
        }
        DataCommand.Send(_connection);
        return new MailWriter(_connection.GetClosableStream(), encodeForTransport: true);
    }
References System.Net.Mail.SmtpTransport._connection, System.Net.Mail.SmtpTransport._failedRecipientExceptions, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.exception, System.Net.Mail.SmtpConnection.GetClosableStream(), System.Net.Mail.SmtpCommands.Mail, System.Net.Mail.SmtpConnection.Reader, System.Net.Mail.DataCommand.Send(), System.Net.Mail.MailCommand.Send(), System.Net.Mail.RecipientCommand.Send(), and System.Net.Mail.SmtpReplyReaderFactory.StatusCode.
Referenced by System.Net.Mail.SmtpClient.Send().