Terraria: System.Net.Mail.SmtpTransport.BeginGetConnection
BeginGetConnection()
IAsyncResult System.Net.Mail.SmtpTransport.BeginGetConnection (System::Net::ContextAwareResult outerResult, AsyncCallback callback, object state, string host, int port) inline package
Definition at line 126 of file SmtpTransport.cs.
    {
        IAsyncResult asyncResult = null;
        try
        {
            _connection = new SmtpConnection(this, _client, _credentials, _authenticationModules);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Associate(this, _connection, "BeginGetConnection");
            }
            if (EnableSsl)
            {
                _connection.EnableSsl = true;
                _connection.ClientCertificates = ClientCertificates;
            }
            asyncResult = _connection.BeginGetConnection(outerResult, callback, state, host, port);
        }
        catch (Exception innerException)
        {
            throw new SmtpException(System.SR.MailHostNotFound, innerException);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, "Sync completion", "BeginGetConnection");
        }
        return asyncResult;
    }
References System.Net.Mail.SmtpTransport._authenticationModules, System.Net.Mail.SmtpTransport._client, System.Net.Mail.SmtpTransport._connection, System.Net.Mail.SmtpTransport._credentials, System.Net.NetEventSource.Associate(), System.asyncResult, System.Net.Mail.SmtpConnection.BeginGetConnection(), System.Net.Mail.SmtpTransport.ClientCertificates, System.Net.Mail.SmtpTransport.EnableSsl, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.MailHostNotFound, and System.state.
Referenced by System.Net.Mail.SmtpClient.SendAsync().