Terraria: System.Delegate.Combine
Combine() [1/2]
static ? Delegate System.Delegate.Combine (Delegate? a, Delegate? b) inline static inherited
Definition at line 379 of file Delegate.cs.
    {
        if ((object)a == null)
        {
            return b;
        }
        return a.CombineImpl(b);
    }
References System.Runtime.Serialization.Dictionary.
Referenced by ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.SteelSeriesDeviceGroup(), System.Runtime.InteropServices.ComEventsMethod.AddDelegate(), System.ComponentModel.ReflectEventDescriptor.AddEventHandler(), System.ComponentModel.EventHandlerList.AddHandler(), System.Xml.XmlValidatingReaderImpl.ValidationEventHandling.AddHandler(), System.Runtime.Serialization.SerializationEvents.AddOnDelegate(), System.Runtime.Serialization.ObjectManager.AddOnDeserialization(), System.Transactions.ActiveStates.AddOutcomeRegistrant(), System.Transactions.TransactionStatePromotedBase.AddOutcomeRegistrant(), System.Transactions.TransactionStatePromotedNonMSDTCBase.AddOutcomeRegistrant(), System.ComponentModel.PropertyDescriptor.AddValueChanged(), System.Delegate.Combine(), and Terraria.Social.WeGame.NetServerSocialModule.OnLobbyCreated().