Terraria: System.Delegate.Remove
Remove()
static ? Delegate System.Delegate.Remove (Delegate? source, Delegate? value) inline static inherited
Definition at line 463 of file Delegate.cs.
    {
        if ((object)source == null)
        {
            return null;
        }
        if ((object)value == null)
        {
            return source;
        }
        if (!InternalEqualTypes(source, value))
        {
            throw new ArgumentException(SR.Arg_DlgtTypeMis);
        }
        return source.RemoveImpl(value);
    }
References System.SR.Arg_DlgtTypeMis, System.Delegate.InternalEqualTypes(), System.source, and System.value.
Referenced by System.Delegate.RemoveAll(), System.Runtime.InteropServices.ComEventsMethod.RemoveDelegate(), System.ComponentModel.ReflectEventDescriptor.RemoveEventHandler(), System.ComponentModel.EventHandlerList.RemoveHandler(), System.Xml.XmlValidatingReaderImpl.ValidationEventHandling.RemoveHandler(), and System.ComponentModel.PropertyDescriptor.RemoveValueChanged().