Terraria: System.Delegate.GetMethodImpl
GetMethodImpl()
virtual MethodInfo System.Delegate.GetMethodImpl () inline protected virtual
Reimplemented in System.MulticastDelegate.
Definition at line 118 of file Delegate.cs.
    {
        if (_methodBase == null || !(_methodBase is MethodInfo))
        {
            IRuntimeMethodInfo runtimeMethodInfo = FindMethodHandle();
            RuntimeType runtimeType = RuntimeMethodHandle.GetDeclaringType(runtimeMethodInfo);
            if ((RuntimeTypeHandle.IsGenericTypeDefinition(runtimeType) || RuntimeTypeHandle.HasInstantiation(runtimeType)) && (RuntimeMethodHandle.GetAttributes(runtimeMethodInfo) & MethodAttributes.Static) == 0)
            {
                if (_methodPtrAux == IntPtr.Zero)
                {
                    Type type = _target.GetType();
                    Type genericTypeDefinition = runtimeType.GetGenericTypeDefinition();
                    while (type != null)
                    {
                        if (type.IsGenericType && type.GetGenericTypeDefinition() == genericTypeDefinition)
{
                            runtimeType = type as RuntimeType;
                            break;
                        }
                        type = type.BaseType;
                    }
                }
                else
                {
                    MethodInfo method = GetType().GetMethod("Invoke");
                    runtimeType = (RuntimeType)method.GetParameters()[0].ParameterType;
                }
            }
            _methodBase = (MethodInfo)RuntimeType.GetMethodBase(runtimeType, runtimeMethodInfo);
        }
        return (MethodInfo)_methodBase;
    }
References System.Delegate._methodBase, System.Delegate._methodPtrAux, System.Delegate._target, System.RuntimeType.BaseType, System.Runtime.Serialization.Dictionary, System.Delegate.FindMethodHandle(), System.RuntimeMethodHandle.GetAttributes(), System.RuntimeMethodHandle.GetDeclaringType(), System.Type.GetGenericTypeDefinition(), System.RuntimeType.GetMethodBase(), System.Reflection.MethodBase.GetParameters(), System.RuntimeTypeHandle.HasInstantiation(), System.RuntimeTypeHandle.IsGenericTypeDefinition(), System.Reflection.ParameterInfo.ParameterType, System.type, and System.IntPtr.Zero.