Terraria: System.Delegate.CreateDelegate
CreateDelegate() [8/10]
static ? Delegate System.Delegate.CreateDelegate (Type type, object target, string method, bool ignoreCase, bool throwOnBindFailure) inline static inherited
Definition at line 152 of file Delegate.cs.
    {
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        if (target == null)
        {
            throw new ArgumentNullException("target");
        }
        if (method == null)
        {
            throw new ArgumentNullException("method");
        }
        if (!(type is RuntimeType runtimeType))
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeType, "type");
        }
        if (!runtimeType.IsDelegate())
        {
            throw new ArgumentException(SR.Arg_MustBeDelegate, "type");
        }
        Delegate @delegate = InternalAlloc(runtimeType);
        if (!@delegate.BindToMethodName(target, (RuntimeType)target.GetType(), method, (DelegateBindingFlags)26 | (ignoreCase ? DelegateBindingFlags.CaselessMatching : ((DelegateBindingFlags)0))))
        {
            if (throwOnBindFailure)
            {
                throw new ArgumentException(SR.Arg_DlgtTargMeth);
            }
            return null;
        }
        return @delegate;
    }
References System.SR.Arg_DlgtTargMeth, System.SR.Arg_MustBeDelegate, System.SR.Argument_MustBeRuntimeType, System.Runtime.Serialization.Dictionary, System.Delegate.InternalAlloc(), and System.type.
Referenced by ReLogic.Peripherals.RGB.ChromaShader.BindProcessors(), System.Data.DataRowExtensions.UnboxT< T >.Create(), System.Xml.Xsl.IlGen.XmlILModule.CreateDelegate(), System.Delegate.CreateDelegate(), System.Delegate.CreateDelegate(), System.Delegate.CreateDelegate(), System.Delegate.CreateDelegate(), System.Delegate.CreateDelegate(), System.Delegate.CreateDelegate(), System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.CreateDelegate< TDelegate >(), System.Resources.ResourceReader.CreateUntypedDelegate< TInstance >(), and Internal.Runtime.InteropServices.ComponentActivator.InternalGetFunctionPointer().