Terraria: System.Net.Sockets.SocketsTelemetry.Log
Log
readonly SocketsTelemetry System.Net.Sockets.SocketsTelemetry.Log = new SocketsTelemetry() static
Definition at line 10 of file SocketsTelemetry.cs.
Referenced by System.Net.Sockets.Socket.Accept(), System.Net.Sockets.Socket.AcceptAsync(), System.Net.Sockets.SocketAsyncEventArgs.AfterConnectAcceptTelemetry(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), System.Net.Sockets.Socket.DoConnect(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSync(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(), System.Net.Sockets.SocketAsyncEventArgs.LogBytesTransferEvents(), System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.SendTo(), System.Net.Sockets.Socket.SendTo(), and System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon().