Terraria: System.Net.Http.Headers.AuthenticationHeaderValue.TrySkipFirstBlob
TrySkipFirstBlob()
static bool System.Net.Http.Headers.AuthenticationHeaderValue.TrySkipFirstBlob (string input, ref int current, ref int parameterEndIndex) inline static private
Definition at line 144 of file AuthenticationHeaderValue.cs.
    {
        while (current < input.Length && input[current] != ',')
        {
            if (input[current] == '"')
            {
                int length = 0;
                if (HttpRuleParser.GetQuotedStringLength(input, current, out length) != 0)
                {
                    return false;
                }
                current += length;
                parameterEndIndex = current - 1;
            }
            else
            {
                int whitespaceLength = HttpRuleParser.GetWhitespaceLength(input, current);
                if (whitespaceLength == 0)
                {
                    parameterEndIndex = current;
                    current++;
                }
                else
                {
                    current += whitespaceLength;
                }
            }
        }
        return true;
    }
References System.Net.Http.HttpRuleParser.GetQuotedStringLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, and System.length.
Referenced by System.Net.Http.Headers.AuthenticationHeaderValue.GetAuthenticationLength().