Terraria: System.Net.Http.Headers.AuthenticationHeaderValue.TryGetParametersEndIndex
TryGetParametersEndIndex()
static bool System.Net.Http.Headers.AuthenticationHeaderValue.TryGetParametersEndIndex (string input, ref int parseEndIndex, ref int parameterEndIndex) inline static private
Definition at line 175 of file AuthenticationHeaderValue.cs.
    {
        int num = parseEndIndex;
        do
        {
            num++;
            bool separatorFound = false;
            num = HeaderUtilities.GetNextNonEmptyOrWhitespaceIndex(input, num, skipEmptyValues: true, out separatorFound);
            if (num == input.Length)
            {
                return true;
            }
            int tokenLength = HttpRuleParser.GetTokenLength(input, num);
            if (tokenLength == 0)
            {
                return false;
            }
            num += tokenLength;
            num += HttpRuleParser.GetWhitespaceLength(input, num);
            if (num == input.Length || input[num] != '=')
            {
                return true;
            }
            num++;
            num += HttpRuleParser.GetWhitespaceLength(input, num);
            int valueLength = NameValueHeaderValue.GetValueLength(input, num);
            if (valueLength == 0)
            {
                return false;
            }
            num += valueLength;
            parameterEndIndex = num - 1;
            num = (parseEndIndex = num + HttpRuleParser.GetWhitespaceLength(input, num));
        }
        while (num < input.Length && input[num] == ',');
        return true;
    }
References System.Net.Http.Headers.HeaderUtilities.GetNextNonEmptyOrWhitespaceIndex(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.Net.Http.Headers.NameValueHeaderValue.GetValueLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), and System.input.
Referenced by System.Net.Http.Headers.AuthenticationHeaderValue.GetAuthenticationLength().