Terraria: System.Net.WebSockets.Compression.WebSocketDeflater.CreateDeflater
CreateDeflater()
ZLibNative.ZLibStreamHandle System.Net.WebSockets.Compression.WebSocketDeflater.CreateDeflater () inline private
Definition at line 154 of file WebSocketDeflater.cs.
    {
        ZLibNative.ErrorCode errorCode;
        ZLibNative.ZLibStreamHandle zLibStreamHandle;
        try
        {
            errorCode = ZLibNative.CreateZLibStreamForDeflate(out zLibStreamHandle, ZLibNative.CompressionLevel.DefaultCompression, _windowBits, 8, ZLibNative.CompressionStrategy.DefaultStrategy);
        }
        catch (Exception innerException)
        {
            throw new WebSocketException(System.SR.ZLibErrorDLLLoadError, innerException);
        }
        if (errorCode == ZLibNative.ErrorCode.Ok)
        {
            return zLibStreamHandle;
        }
        zLibStreamHandle.Dispose();
        string message = ((errorCode == ZLibNative.ErrorCode.MemError) ? System.SR.ZLibErrorNotEnoughMemory : string.Format(System.SR.ZLibErrorUnexpected, (int)errorCode));
        throw new WebSocketException(message);
    }
References System.Net.WebSockets.Compression.WebSocketDeflater._windowBits, System.IO.Compression.ZLibNative.CreateZLibStreamForDeflate(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.SR.ZLibErrorDLLLoadError, System.SR.ZLibErrorNotEnoughMemory, and System.SR.ZLibErrorUnexpected.
Referenced by System.Net.WebSockets.Compression.WebSocketDeflater.DeflatePrivate().