Terraria: System.Net.WebSockets.Compression.WebSocketDeflater.DeflatePrivate
DeflatePrivate()
void System.Net.WebSockets.Compression.WebSocketDeflater.DeflatePrivate (ReadOnlySpan< byte > payload, Span< byte > output, bool endOfMessage, out int consumed, out int written, out bool needsMoreOutput) inline private
Definition at line 63 of file WebSocketDeflater.cs.
    {
        if (_stream == null)
        {
            _stream = CreateDeflater();
        }
        if (payload.Length == 0)
        {
            consumed = 0;
            written = 0;
        }
        else
        {
            UnsafeDeflate(payload, output, out consumed, out written, out needsMoreOutput);
            if (needsMoreOutput)
            {
                return;
            }
        }
        written += UnsafeFlush(output.Slice(written), out needsMoreOutput);
        if (!needsMoreOutput)
        {
            if (endOfMessage)
            {
                written -= 4;
            }
            if (endOfMessage && !_persisted)
            {
                _stream.Dispose();
                _stream = null;
            }
        }
    }
References System.Net.WebSockets.Compression.WebSocketDeflater._persisted, System.Net.WebSockets.Compression.WebSocketDeflater._stream, System.Net.WebSockets.Compression.WebSocketDeflater.CreateDeflater(), System.ReadOnlySpan< T >.Length, System.Span< T >.Slice(), System.Net.WebSockets.Compression.WebSocketDeflater.UnsafeDeflate(), and System.Net.WebSockets.Compression.WebSocketDeflater.UnsafeFlush().
Referenced by System.Net.WebSockets.Compression.WebSocketDeflater.Deflate().