Terraria: System.Net.WebSockets.Compression.WebSocketDeflater.Deflate
Deflate() [1/2]
ReadOnlySpan< byte > System.Net.WebSockets.Compression.WebSocketDeflater.Deflate (ReadOnlySpan< byte > payload, bool endOfMessage) inline
Definition at line 41 of file WebSocketDeflater.cs.
    {
        _buffer = ArrayPool<byte>.Shared.Rent(Math.Max(payload.Length, 4096));
        int num = 0;
        while (true)
        {
            DeflatePrivate(payload, _buffer.AsSpan(num), endOfMessage, out var consumed, out var written, out var needsMoreOutput);
            num += written;
            if (!needsMoreOutput)
            {
                break;
            }
            payload = payload.Slice(consumed);
            byte[] array = ArrayPool<byte>.Shared.Rent((int)((double)_buffer.Length * 1.3));
            _buffer.AsSpan(0, num).CopyTo(array);
            byte[] buffer = _buffer;
            _buffer = array;
            ArrayPool<byte>.Shared.Return(buffer);
        }
        return new ReadOnlySpan<byte>(_buffer, 0, num);
    }
References System.Net.WebSockets.Compression.WebSocketDeflater._buffer, System.array, System.buffer, System.Net.WebSockets.Compression.WebSocketDeflater.DeflatePrivate(), System.ReadOnlySpan< T >.Length, System.Math.Max(), System.Buffers.ArrayPool< T >.Shared, and System.ReadOnlySpan< T >.Slice().
Referenced by System.Net.WebSockets.ManagedWebSocket.WriteFrameToSendBuffer().