Terraria: System.IO.Compression.BrotliEncoder.SetQuality
SetQuality()
void System.IO.Compression.BrotliEncoder.SetQuality (int quality) inline package
Definition at line 58 of file BrotliEncoder.cs.
    {
        EnsureNotDisposed();
        if (_state == null || _state.IsInvalid || _state.IsClosed)
        {
            InitializeEncoder();
        }
        if (quality < 0 || quality > 11)
        {
            throw new ArgumentOutOfRangeException("quality", System.SR.Format(System.SR.BrotliEncoder_Quality, quality, 0, 11));
        }
        if (global::Interop.Brotli.BrotliEncoderSetParameter(_state, BrotliEncoderParameter.Quality, (uint)quality) == global::Interop.BOOL.FALSE)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.BrotliEncoder_InvalidSetParameter, "Quality"));
        }
    }
References System.IO.Compression.BrotliEncoder._state, System.SR.BrotliEncoder_InvalidSetParameter, System.SR.BrotliEncoder_Quality, System.IO.Compression.BrotliEncoder.EnsureNotDisposed(), System.SR.Format(), System.IO.Compression.BrotliEncoder.InitializeEncoder(), System.Runtime.InteropServices.SafeHandle.IsClosed, and Microsoft.Win32.SafeHandles.SafeBrotliEncoderHandle.IsInvalid.
Referenced by System.IO.Compression.BrotliEncoder.BrotliEncoder(), and System.IO.Compression.BrotliStream.BrotliStream().