Terraria: NPCKillsTracker.RegisterKill
RegisterKill()
void NPCKillsTracker.RegisterKill (NPC npc) inline
     {
         string bestiaryCreditId = npc.GetBestiaryCreditId();
         _killCountsByNpcId.TryGetValue(bestiaryCreditId, out var value);
         value++;
         lock (_entryCreationLock)
         {
             _killCountsByNpcId[bestiaryCreditId] = Utils.Clamp(value, 0, 999999999);
         }
         if (Main.netMode == 2)
         {
             NetManager.Instance.Broadcast(NetBestiaryModule.SerializeKillCount(npc.netID, value));
         }
     }
References _entryCreationLock, _killCountsByNpcId, NetManager.Broadcast(), NPC.GetBestiaryCreditId(), NetManager.Instance, NPC.netID, Main.netMode, and NetBestiaryModule.SerializeKillCount().
Referenced by NPC.AI_003_Fighters(), Item.CheckLavaDeath(), MessageBuffer.GetData(), Player.ItemCheck_UseTorchGodsFavor(), NPC.NPCLoot(), and Player.Spawn().