Terraria: System.Xml.DtdParser.ParseAttlistDefault
ParseAttlistDefault()
void System.Xml.DtdParser.ParseAttlistDefault (SchemaAttDef attrDef, bool ignoreErrors) inline private
Definition at line 734 of file DtdParser.cs.
    {
        switch (GetToken(needWhiteSpace: true))
        {
        case Token.REQUIRED:
            attrDef.Presence = SchemaDeclBase.Use.Required;
            return;
        case Token.IMPLIED:
            attrDef.Presence = SchemaDeclBase.Use.Implied;
            return;
        case Token.FIXED:
            attrDef.Presence = SchemaDeclBase.Use.Fixed;
            if (GetToken(needWhiteSpace: true) != Token.Literal)
            {
                break;
            }
            goto case Token.Literal;
        case Token.Literal:
            if (_validate && attrDef.Datatype.TokenizedType == XmlTokenizedType.ID && !ignoreErrors)
            {
                SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_AttListPresence, string.Empty);
            }
            if (attrDef.TokenizedType != 0)
            {
                attrDef.DefaultValueExpanded = GetValueWithStrippedSpaces();
            }
            else
            {
                attrDef.DefaultValueExpanded = GetValue();
            }
            attrDef.ValueLineNumber = _literalLineInfo.lineNo;
            attrDef.ValueLinePosition = _literalLineInfo.linePos + 1;
            DtdValidator.SetDefaultTypedValue(attrDef, _readerAdapter);
            return;
        }
        OnUnexpectedError();
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._literalLineInfo, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._validate, System.Xml.Dictionary, System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.GetValue(), System.Xml.DtdParser.GetValueWithStrippedSpaces(), System.Xml.LineInfo.lineNo, System.Xml.DtdParser.OnUnexpectedError(), System.SR.Sch_AttListPresence, System.Xml.DtdParser.SendValidationEvent(), and System.Xml.Schema.DtdValidator.SetDefaultTypedValue().
Referenced by System.Xml.DtdParser.ParseAttlistDecl().