Terraria: System.Xml.DtdParser.ParseInDocumentDtdAsync
ParseInDocumentDtdAsync()
async Task System.Xml.DtdParser.ParseInDocumentDtdAsync (bool saveInternalSubset) inline private
Definition at line 3202 of file DtdParser.cs.
    {
        LoadParsingBuffer();
        _scanningFunction = ScanningFunction.QName;
        _nextScaningFunction = ScanningFunction.Doctype1;
        if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) != Token.QName)
        {
            OnUnexpectedError();
        }
        _schemaInfo.DocTypeName = GetNameQualified(canHavePrefix: true);
        Token token = await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false);
        if (token == Token.SYSTEM || token == Token.PUBLIC)
        {
            (string, string) tuple = await ParseExternalIdAsync(token, Token.DOCTYPE).ConfigureAwait(continueOnCapturedContext: false);
            _publicId = tuple.Item1;
            _systemId = tuple.Item2;
            token = await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false);
        }
        switch (token)
        {
        case Token.LeftBracket:
            if (saveInternalSubset)
            {
                SaveParsingBuffer();
                _internalSubsetValueSb = new StringBuilder();
            }
            await ParseInternalSubsetAsync().ConfigureAwait(continueOnCapturedContext: false);
            break;
        default:
            OnUnexpectedError();
            break;
        case Token.GreaterThan:
            break;
        }
        SaveParsingBuffer();
        if (_systemId != null && _systemId.Length > 0)
        {
            await ParseExternalSubsetAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.DtdParser._internalSubsetValueSb, System.Xml.DtdParser._nextScaningFunction, System.Xml.DtdParser._publicId, System.Xml.DtdParser._scanningFunction, System.Xml.DtdParser._systemId, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseExternalIdAsync(), System.Xml.DtdParser.ParseExternalSubsetAsync(), System.Xml.DtdParser.ParseInternalSubsetAsync(), and System.Xml.DtdParser.SaveParsingBuffer().
Referenced by System.Xml.DtdParser.ParseAsync().