Terraria: Terraria.UI.ItemSorting.SortChest
SortChest()
static void Terraria.UI.ItemSorting.SortChest () inline static
    {
        int chest = Main.player[Main.myPlayer].chest;
        if (chest == -1)
        {
            return;
        }
        Item[] item = Main.player[Main.myPlayer].bank.item;
        if (chest == -3)
        {
            item = Main.player[Main.myPlayer].bank2.item;
        }
        if (chest == -4)
        {
            item = Main.player[Main.myPlayer].bank3.item;
        }
        if (chest == -5)
        {
            item = Main.player[Main.myPlayer].bank4.item;
        }
        if (chest > -1)
        {
            item = Main.chest[chest].item;
        }
        Tuple<int, int, int>[] array = new Tuple<int, int, int>[40];
        for (int i = 0; i < 40; i++)
        {
            array[i] = Tuple.Create(item[i].netID, item[i].stack, (int)item[i].prefix);
        }
        Sort(item);
        Tuple<int, int, int>[] array2 = new Tuple<int, int, int>[40];
        for (int j = 0; j < 40; j++)
        {
            array2[j] = Tuple.Create(item[j].netID, item[j].stack, (int)item[j].prefix);
        }
        if (Main.netMode != 1 || Main.player[Main.myPlayer].chest <= -1)
        {
            return;
        }
        for (int k = 0; k < 40; k++)
        {
            if (array2[k] != array[k])
            {
                NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, k);
            }
        }
    }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Main.chest, Terraria.Player.chest, Terraria.Chest.item, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.NetMessage.SendData(), and Terraria.UI.ItemSorting.Sort().
Referenced by Terraria.UI.ChestUI.DrawButton().