Terraria: System.Security.Cryptography.CngPkcs8.RewritePkcs8ECPrivateKeyWithZeroPublicKey
RewritePkcs8ECPrivateKeyWithZeroPublicKey() [2/2]
static unsafe AsnWriter System.Security.Cryptography.CngPkcs8.RewritePkcs8ECPrivateKeyWithZeroPublicKey (ReadOnlySpan< byte > source) inline static private
Definition at line 279 of file CngPkcs8.cs.
    {
        fixed (byte* pointer = &MemoryMarshal.GetReference(source))
        {
            using MemoryManager<byte> memoryManager = new System.Buffers.PointerMemoryManager<byte>(pointer, source.Length);
            System.Security.Cryptography.Asn1.PrivateKeyInfoAsn privateKeyInfoAsn = System.Security.Cryptography.Asn1.PrivateKeyInfoAsn.Decode(memoryManager.Memory, AsnEncodingRules.BER);
            System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn algId = privateKeyInfoAsn.PrivateKeyAlgorithm;
            if (algId.Algorithm != "1.2.840.10045.2.1")
            {
                return null;
            }
            System.Security.Cryptography.Asn1.ECPrivateKey key = System.Security.Cryptography.Asn1.ECPrivateKey.Decode(privateKeyInfoAsn.PrivateKey, AsnEncodingRules.BER);
            System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(key, in algId, out var ret);
            fixed (byte* ptr = ret.D)
            {
                try
                {
                    if (!ret.Curve.IsExplicit || ret.Q.X != null || ret.Q.Y != null)
                    {
                        return null;
                    }
                    byte[] array = new byte[ret.D.Length];
                    ret.Q.Y = array;
                    ret.Q.X = array;
                    return System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey(ret, privateKeyInfoAsn.Attributes);
                }
                finally
                {
                    Array.Clear(ret.D);
                }
            }
        }
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Algorithm, System.array, System.Array.Clear(), System.Security.Cryptography.Asn1.ECPrivateKey.Decode(), System.Security.Cryptography.Asn1.PrivateKeyInfoAsn.Decode(), System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), System.key, System.pointer, System.source, and System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey().