Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.GetExtendedProperties
GetExtendedProperties()
PropertyDescriptorCollection System.ComponentModel.ReflectTypeDescriptionProvider.GetExtendedProperties (object instance) inline package
Definition at line 687 of file ReflectTypeDescriptionProvider.cs.
    {
        Type type = instance.GetType();
        IExtenderProvider[] extenderProviders = GetExtenderProviders(instance);
        IDictionary cache = TypeDescriptor.GetCache(instance);
        if (extenderProviders.Length == 0)
        {
            return PropertyDescriptorCollection.Empty;
        }
        PropertyDescriptorCollection propertyDescriptorCollection = null;
        if (cache != null)
        {
            propertyDescriptorCollection = cache[s_extenderPropertiesKey] as PropertyDescriptorCollection;
        }
        if (propertyDescriptorCollection != null)
        {
            return propertyDescriptorCollection;
        }
        List<PropertyDescriptor> list = null;
        for (int i = 0; i < extenderProviders.Length; i++)
        {
            PropertyDescriptor[] array = ReflectGetExtendedProperties(extenderProviders[i]);
            if (list == null)
            {
                list = new List<PropertyDescriptor>(array.Length * extenderProviders.Length);
            }
            foreach (PropertyDescriptor propertyDescriptor in array)
            {
                if (propertyDescriptor.Attributes[typeof(ExtenderProvidedPropertyAttribute)] is ExtenderProvidedPropertyAttribute extenderProvidedPropertyAttribute)
                {
                    Type receiverType = extenderProvidedPropertyAttribute.ReceiverType;
                    if (receiverType != null && receiverType.IsAssignableFrom(type))
                    {
                        list.Add(propertyDescriptor);
                    }
                }
            }
        }
        if (list != null)
        {
            PropertyDescriptor[] array2 = new PropertyDescriptor[list.Count];
            list.CopyTo(array2, 0);
            propertyDescriptorCollection = new PropertyDescriptorCollection(array2, readOnly: true);
        }
        else
        {
            propertyDescriptorCollection = PropertyDescriptorCollection.Empty;
        }
        if (cache != null)
        {
            cache[s_extenderPropertiesKey] = propertyDescriptorCollection;
        }
        return propertyDescriptorCollection;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.ComponentModel.PropertyDescriptorCollection.Empty, System.ComponentModel.TypeDescriptor.GetCache(), System.ComponentModel.ReflectTypeDescriptionProvider.GetExtenderProviders(), System.list, System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetExtendedProperties(), System.ComponentModel.ReflectTypeDescriptionProvider.s_extenderPropertiesKey, and System.type.