Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetExtendedProperties
ReflectGetExtendedProperties()
static PropertyDescriptor[] System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetExtendedProperties (IExtenderProvider provider) inline static private
Definition at line 1055 of file ReflectTypeDescriptionProvider.cs.
    {
        IDictionary cache = TypeDescriptor.GetCache(provider);
        if (cache != null && cache[s_extenderProviderPropertiesKey] is PropertyDescriptor[] result)
        {
            return result;
        }
        Type type = provider.GetType();
        Hashtable extendedPropertyCache = ExtendedPropertyCache;
        ReflectPropertyDescriptor[] array = (ReflectPropertyDescriptor[])extendedPropertyCache[type];
        if (array == null)
        {
            lock (s_internalSyncObject)
            {
                array = (ReflectPropertyDescriptor[])extendedPropertyCache[type];
                if (array == null)
                {
                    AttributeCollection attributes = TypeDescriptor.GetAttributes(type);
                    List<ReflectPropertyDescriptor> list = new List<ReflectPropertyDescriptor>(attributes.Count);
                    foreach (Attribute item in attributes)
                    {
                        if (!(item is ProvidePropertyAttribute providePropertyAttribute))
{
                            continue;
                        }
                        Type typeFromName = GetTypeFromName(providePropertyAttribute.ReceiverTypeName);
                        if (!(typeFromName != null))
{
                            continue;
                        }
                        MethodInfo method = type.GetMethod("Get" + providePropertyAttribute.PropertyName, new Type[1] { typeFromName });
                        if (method != null && !method.IsStatic && method.IsPublic)
{
                            MethodInfo methodInfo = type.GetMethod("Set" + providePropertyAttribute.PropertyName, new Type[2] { typeFromName, method.ReturnType });
                            if (methodInfo != null && (methodInfo.IsStatic || !methodInfo.IsPublic))
{
                                methodInfo = null;
                            }
                            list.Add(new ReflectPropertyDescriptor(type, providePropertyAttribute.PropertyName, method.ReturnType, typeFromName, method, methodInfo, null));
                        }
                    }
                    array = new ReflectPropertyDescriptor[list.Count];
                    list.CopyTo(array, 0);
                    extendedPropertyCache[type] = array;
                }
            }
        }
        PropertyDescriptor[] array2 = new PropertyDescriptor[array.Length];
        for (int i = 0; i < array.Length; i++)
        {
            ReflectPropertyDescriptor reflectPropertyDescriptor = array[i];
            array2[i] = new ExtendedPropertyDescriptor(reflectPropertyDescriptor, reflectPropertyDescriptor.ExtenderGetReceiverType(), provider, null);
        }
        if (cache != null)
        {
            cache[s_extenderProviderPropertiesKey] = array2;
        }
        return array2;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.ComponentModel.AttributeCollection.Count, System.ComponentModel.ReflectTypeDescriptionProvider.ExtendedPropertyCache, System.ComponentModel.TypeDescriptor.GetAttributes(), System.ComponentModel.TypeDescriptor.GetCache(), System.ComponentModel.ReflectTypeDescriptionProvider.GetTypeFromName(), System.item, System.list, System.ComponentModel.ReflectTypeDescriptionProvider.s_extenderProviderPropertiesKey, System.ComponentModel.ReflectTypeDescriptionProvider.s_internalSyncObject, and System.type.
Referenced by System.ComponentModel.ReflectTypeDescriptionProvider.GetExtendedProperties().