Terraria: System.Xml.DtdParser.ParsePIAsync
ParsePIAsync()
async Task System.Xml.DtdParser.ParsePIAsync () inline private
Definition at line 3996 of file DtdParser.cs.
    {
        SaveParsingBuffer();
        if (!SaveInternalSubsetValue)
        {
            await _readerAdapter.ParsePIAsync(null).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            await _readerAdapter.ParsePIAsync(_internalSubsetValueSb).ConfigureAwait(continueOnCapturedContext: false);
            _internalSubsetValueSb.Append("?>");
        }
        LoadParsingBuffer();
    }
References System.Xml.DtdParser._internalSubsetValueSb, System.Xml.DtdParser._readerAdapter, System.Text.StringBuilder.Append(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.IDtdParserAdapter.ParsePIAsync(), System.Xml.DtdParser.SaveInternalSubsetValue, and System.Xml.DtdParser.SaveParsingBuffer().
Referenced by System.Xml.DtdParser.ParseSubsetAsync().