Terraria: System.Security.Cryptography.CngPkcs8.ImportEncryptedPkcs8PrivateKey
ImportEncryptedPkcs8PrivateKey() [4/4]
static unsafe Pkcs8Response System.Security.Cryptography.CngPkcs8.ImportEncryptedPkcs8PrivateKey (ReadOnlySpan< char > password, ReadOnlySpan< byte > source, out int bytesRead) inline static package
Definition at line 176 of file CngPkcs8.cs.
    {
        try
        {
            AsnDecoder.ReadEncodedValue(source, AsnEncodingRules.BER, out var _, out var _, out var bytesConsumed);
            source = source.Slice(0, bytesConsumed);
            fixed (byte* pointer = &MemoryMarshal.GetReference(source))
            {
                using MemoryManager<byte> memoryManager = new System.Buffers.PointerMemoryManager<byte>(pointer, source.Length);
                try
                {
                    bytesRead = bytesConsumed;
                    return ImportPkcs8(source, password);
                }
                catch (CryptographicException)
                {
                }
                int bytesRead2;
                ArraySegment<byte> arraySegment = System.Security.Cryptography.KeyFormatHelper.DecryptPkcs8(password, memoryManager.Memory.Slice(0, bytesConsumed), out bytesRead2);
                Span<byte> span = arraySegment;
                try
                {
                    if (bytesRead2 != bytesConsumed)
                    {
                        throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
                    }
                    bytesRead = bytesConsumed;
                    return ImportPkcs8(span);
                }
                catch (CryptographicException inner)
                {
                    AsnWriter asnWriter = RewritePkcs8ECPrivateKeyWithZeroPublicKey(span);
                    if (asnWriter == null)
                    {
                        throw new CryptographicException(System.SR.Cryptography_Pkcs8_EncryptedReadFailed, inner);
                    }
                    try
                    {
                        bytesRead = bytesConsumed;
                        return ImportPkcs8(asnWriter);
                    }
                    catch (CryptographicException)
                    {
                        throw new CryptographicException(System.SR.Cryptography_Pkcs8_EncryptedReadFailed, inner);
                    }
                }
                finally
                {
                    System.Security.Cryptography.CryptoPool.Return(arraySegment);
                }
            }
        }
        catch (AsnContentException inner2)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner2);
        }
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_Pkcs8_EncryptedReadFailed, System.Security.Cryptography.KeyFormatHelper.DecryptPkcs8(), System.Security.Cryptography.CngPkcs8.ImportPkcs8(), System.pointer, System.Formats.Asn1.AsnDecoder.ReadEncodedValue(), System.Security.Cryptography.CryptoPool.Return(), System.Security.Cryptography.CngPkcs8.RewritePkcs8ECPrivateKeyWithZeroPublicKey(), and System.source.