Terraria: System.Xml.DtdParser.ScanLiteralAsync
ScanLiteralAsync()
async Task< Token > System.Xml.DtdParser.ScanLiteralAsync (LiteralType literalType) inline private
Definition at line 4791 of file DtdParser.cs.
    {
        char quoteChar = _chars[_curPos];
        char replaceChar = ((literalType == LiteralType.AttributeValue) ? ' ' : '\n');
        int startQuoteEntityId = _currentEntityId;
        _literalLineInfo.Set(LineNo, LinePos);
        _curPos++;
        _tokenStartPos = _curPos;
        _stringBuilder.Length = 0;
        while (true)
        {
            if (XmlCharType.IsAttributeValueChar(_chars[_curPos]) && _chars[_curPos] != '%')
            {
                _curPos++;
                continue;
            }
            if (_chars[_curPos] == quoteChar && _currentEntityId == startQuoteEntityId)
            {
                break;
            }
            int num = _curPos - _tokenStartPos;
            if (num > 0)
            {
                _stringBuilder.Append(_chars, _tokenStartPos, num);
                _tokenStartPos = _curPos;
            }
            switch (_chars[_curPos])
            {
            case '"':
            case '\'':
            case '>':
                _curPos++;
                continue;
            case '\n':
                _curPos++;
                if (Normalize)
                {
                    _stringBuilder.Append(replaceChar);
                    _tokenStartPos = _curPos;
                }
                _readerAdapter.OnNewLine(_curPos);
                continue;
            case '\r':
                if (_chars[_curPos + 1] == '\n')
                {
                    if (Normalize)
                    {
                        if (literalType == LiteralType.AttributeValue)
{
                            _stringBuilder.Append(_readerAdapter.IsEntityEolNormalized ? "  " : " ");
                        }
                        else
{
                            _stringBuilder.Append(_readerAdapter.IsEntityEolNormalized ? "\r\n" : "\n");
                        }
                        _tokenStartPos = _curPos + 2;
                        SaveParsingBuffer();
                        _readerAdapter.CurrentPosition++;
                    }
                    _curPos += 2;
                }
                else
                {
                    if (_curPos + 1 == _charsUsed)
                    {
                        break;
                    }
                    _curPos++;
                    if (Normalize)
                    {
                        _stringBuilder.Append(replaceChar);
                        _tokenStartPos = _curPos;
                    }
                }
                _readerAdapter.OnNewLine(_curPos);
                continue;
            case '\t':
                if (literalType == LiteralType.AttributeValue && Normalize)
                {
                    _stringBuilder.Append(' ');
                    _tokenStartPos++;
                }
                _curPos++;
                continue;
            case '<':
                if (literalType == LiteralType.AttributeValue)
                {
                    Throw(_curPos, System.SR.Xml_BadAttributeChar, XmlException.BuildCharExceptionArgs('<', '\0'));
                }
                _curPos++;
                continue;
            case '%':
                if (literalType != LiteralType.EntityReplText)
                {
                    _curPos++;
                    continue;
                }
                await HandleEntityReferenceAsync(paramEntity: true, inLiteral: true, literalType == LiteralType.AttributeValue).ConfigureAwait(continueOnCapturedContext: false);
                _tokenStartPos = _curPos;
                continue;
            case '&':
            {
                if (literalType == LiteralType.SystemOrPublicID)
                {
                    _curPos++;
                    continue;
                }
                if (_curPos + 1 == _charsUsed)
                {
                    break;
                }
                if (_chars[_curPos + 1] == '#')
                {
                    SaveParsingBuffer();
                    int num2 = await _readerAdapter.ParseNumericCharRefAsync(SaveInternalSubsetValue ? _internalSubsetValueSb : null).ConfigureAwait(continueOnCapturedContext: false);
                    LoadParsingBuffer();
                    _stringBuilder.Append(_chars, _curPos, num2 - _curPos);
                    _readerAdapter.CurrentPosition = num2;
                    _tokenStartPos = num2;
                    _curPos = num2;
                    continue;
                }
                SaveParsingBuffer();
                if (literalType == LiteralType.AttributeValue)
                {
                    int num3 = await _readerAdapter.ParseNamedCharRefAsync(expand: true, SaveInternalSubsetValue ? _internalSubsetValueSb : null).ConfigureAwait(continueOnCapturedContext: false);
                    LoadParsingBuffer();
                    if (num3 >= 0)
                    {
                        _stringBuilder.Append(_chars, _curPos, num3 - _curPos);
                        _readerAdapter.CurrentPosition = num3;
                        _tokenStartPos = num3;
                        _curPos = num3;
                    }
                    else
                    {
                        await HandleEntityReferenceAsync(paramEntity: false, inLiteral: true, inAttribute: true).ConfigureAwait(continueOnCapturedContext: false);
                        _tokenStartPos = _curPos;
                    }
                    continue;
                }
                int num4 = await _readerAdapter.ParseNamedCharRefAsync(expand: false, null).ConfigureAwait(continueOnCapturedContext: false);
                LoadParsingBuffer();
                if (num4 >= 0)
                {
                    _tokenStartPos = _curPos;
                    _curPos = num4;
                    continue;
                }
                _stringBuilder.Append('&');
                _curPos++;
                _tokenStartPos = _curPos;
                XmlQualifiedName entityName = ScanEntityName();
                VerifyEntityReference(entityName, paramEntity: false, mustBeDeclared: false, inAttribute: false);
                continue;
            }
            default:
            {
                if (_curPos == _charsUsed)
                {
                    break;
                }
                char ch = _chars[_curPos];
                if (XmlCharType.IsHighSurrogate(ch))
                {
                    if (_curPos + 1 == _charsUsed)
                    {
                        break;
                    }
                    _curPos++;
                    if (XmlCharType.IsLowSurrogate(_chars[_curPos]))
                    {
                        _curPos++;
                        continue;
                    }
                }
                ThrowInvalidChar(_chars, _charsUsed, _curPos);
                return Token.None;
            }
            }
            bool isEof = _readerAdapter.IsEof;
            bool flag = isEof;
            if (!flag)
            {
                flag = await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0;
            }
            if (flag && (literalType == LiteralType.SystemOrPublicID || !HandleEntityEnd(inLiteral: true)))
            {
                Throw(_curPos, System.SR.Xml_UnclosedQuote);
            }
            _tokenStartPos = _curPos;
        }
        if (_stringBuilder.Length > 0)
        {
            _stringBuilder.Append(_chars, _tokenStartPos, _curPos - _tokenStartPos);
        }
        _curPos++;
        _literalQuoteChar = quoteChar;
        return Token.Literal;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._internalSubsetValueSb, System.Xml.DtdParser._literalLineInfo, System.Xml.DtdParser._literalQuoteChar, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._stringBuilder, System.Xml.DtdParser._tokenStartPos, System.Text.StringBuilder.Append(), System.Xml.XmlException.BuildCharExceptionArgs(), System.ch, System.Xml.IDtdParserAdapter.CurrentPosition, System.Xml.Dictionary, System.Xml.DtdParser.HandleEntityEnd(), System.Xml.DtdParser.HandleEntityReferenceAsync(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.IDtdParserAdapter.IsEntityEolNormalized, System.Xml.IDtdParserAdapter.IsEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Text.StringBuilder.Length, System.Xml.DtdParser.LineNo, System.Xml.DtdParser.LinePos, System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.DtdParser.Normalize, System.Xml.IDtdParserAdapter.OnNewLine(), System.Xml.IDtdParserAdapter.ParseNamedCharRefAsync(), System.Xml.IDtdParserAdapter.ParseNumericCharRefAsync(), System.Xml.DtdParser.ReadDataAsync(), System.Xml.DtdParser.SaveInternalSubsetValue, System.Xml.DtdParser.SaveParsingBuffer(), System.Xml.DtdParser.ScanEntityName(), System.Xml.LineInfo.Set(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowInvalidChar(), System.Xml.DtdParser.VerifyEntityReference(), System.SR.Xml_BadAttributeChar, and System.SR.Xml_UnclosedQuote.
Referenced by System.Xml.DtdParser.ScanAttlist6Async(), System.Xml.DtdParser.ScanEntity2Async(), System.Xml.DtdParser.ScanPublicId1Async(), System.Xml.DtdParser.ScanPublicId2Async(), and System.Xml.DtdParser.ScanSystemIdAsync().