Terraria: System.Xml.DtdParser.GetToken
GetToken()
Token System.Xml.DtdParser.GetToken (bool needWhiteSpace) inline private
Definition at line 1318 of file DtdParser.cs.
    {
        _whitespaceSeen = false;
        while (true)
        {
            switch (_chars[_curPos])
            {
            case '\0':
                if (_curPos != _charsUsed)
                {
                    ThrowInvalidChar(_chars, _charsUsed, _curPos);
                }
                break;
            case '\n':
                _whitespaceSeen = true;
                _curPos++;
                _readerAdapter.OnNewLine(_curPos);
                continue;
            case '\r':
                _whitespaceSeen = true;
                if (_chars[_curPos + 1] == '\n')
                {
                    if (Normalize)
                    {
                        SaveParsingBuffer();
                        _readerAdapter.CurrentPosition++;
                    }
                    _curPos += 2;
                }
                else
                {
                    if (_curPos + 1 >= _charsUsed && !_readerAdapter.IsEof)
                    {
                        break;
                    }
                    _chars[_curPos] = '\n';
                    _curPos++;
                }
                _readerAdapter.OnNewLine(_curPos);
                continue;
            case '\t':
            case ' ':
                _whitespaceSeen = true;
                _curPos++;
                continue;
            case '%':
                if (_charsUsed - _curPos < 2)
                {
                    break;
                }
                if (!XmlCharType.IsWhiteSpace(_chars[_curPos + 1]))
                {
                    if (IgnoreEntityReferences)
                    {
                        _curPos++;
                    }
                    else
                    {
                        HandleEntityReference(paramEntity: true, inLiteral: false, inAttribute: false);
                    }
                    continue;
                }
                goto default;
            default:
                if (needWhiteSpace && !_whitespaceSeen && _scanningFunction != ScanningFunction.ParamEntitySpace)
                {
                    Throw(_curPos, System.SR.Xml_ExpectingWhiteSpace, ParseUnexpectedToken(_curPos));
                }
                _tokenStartPos = _curPos;
                while (true)
                {
                    switch (_scanningFunction)
                    {
                    case ScanningFunction.Name:
                        return ScanNameExpected();
                    case ScanningFunction.QName:
                        return ScanQNameExpected();
                    case ScanningFunction.Nmtoken:
                        return ScanNmtokenExpected();
                    case ScanningFunction.SubsetContent:
                        return ScanSubsetContent();
                    case ScanningFunction.Doctype1:
                        return ScanDoctype1();
                    case ScanningFunction.Doctype2:
                        return ScanDoctype2();
                    case ScanningFunction.Element1:
                        return ScanElement1();
                    case ScanningFunction.Element2:
                        return ScanElement2();
                    case ScanningFunction.Element3:
                        return ScanElement3();
                    case ScanningFunction.Element4:
                        return ScanElement4();
                    case ScanningFunction.Element5:
                        return ScanElement5();
                    case ScanningFunction.Element6:
                        return ScanElement6();
                    case ScanningFunction.Element7:
                        return ScanElement7();
                    case ScanningFunction.Attlist1:
                        return ScanAttlist1();
                    case ScanningFunction.Attlist2:
                        return ScanAttlist2();
                    case ScanningFunction.Attlist3:
                        return ScanAttlist3();
                    case ScanningFunction.Attlist4:
                        return ScanAttlist4();
                    case ScanningFunction.Attlist5:
                        return ScanAttlist5();
                    case ScanningFunction.Attlist6:
                        return ScanAttlist6();
                    case ScanningFunction.Attlist7:
                        return ScanAttlist7();
                    case ScanningFunction.Notation1:
                        return ScanNotation1();
                    case ScanningFunction.SystemId:
                        return ScanSystemId();
                    case ScanningFunction.PublicId1:
                        return ScanPublicId1();
                    case ScanningFunction.PublicId2:
                        return ScanPublicId2();
                    case ScanningFunction.Entity1:
                        return ScanEntity1();
                    case ScanningFunction.Entity2:
                        return ScanEntity2();
                    case ScanningFunction.Entity3:
                        return ScanEntity3();
                    case ScanningFunction.CondSection1:
                        return ScanCondSection1();
                    case ScanningFunction.CondSection2:
                        return ScanCondSection2();
                    case ScanningFunction.CondSection3:
                        return ScanCondSection3();
                    case ScanningFunction.ClosingTag:
                        return ScanClosingTag();
                    case ScanningFunction.ParamEntitySpace:
                        break;
                    default:
                        return Token.None;
                    }
                    _whitespaceSeen = true;
                    _scanningFunction = _savedScanningFunction;
                }
            }
            if ((_readerAdapter.IsEof || ReadData() == 0) && !HandleEntityEnd(inLiteral: false))
            {
                if (_scanningFunction == ScanningFunction.SubsetContent)
                {
                    break;
                }
                Throw(_curPos, System.SR.Xml_IncompleteDtdContent);
            }
        }
        return Token.Eof;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._savedScanningFunction, System.Xml.DtdParser._scanningFunction, System.Xml.DtdParser._tokenStartPos, System.Xml.DtdParser._whitespaceSeen, System.Xml.IDtdParserAdapter.CurrentPosition, System.Xml.Dictionary, System.Xml.DtdParser.HandleEntityEnd(), System.Xml.DtdParser.HandleEntityReference(), System.Xml.DtdParser.IgnoreEntityReferences, System.Xml.IDtdParserAdapter.IsEof, System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.DtdParser.Normalize, System.Xml.IDtdParserAdapter.OnNewLine(), System.Xml.DtdParser.ParseUnexpectedToken(), System.Xml.DtdParser.ReadData(), System.Xml.DtdParser.SaveParsingBuffer(), System.Xml.DtdParser.ScanAttlist1(), System.Xml.DtdParser.ScanAttlist2(), System.Xml.DtdParser.ScanAttlist3(), System.Xml.DtdParser.ScanAttlist4(), System.Xml.DtdParser.ScanAttlist5(), System.Xml.DtdParser.ScanAttlist6(), System.Xml.DtdParser.ScanAttlist7(), System.Xml.DtdParser.ScanClosingTag(), System.Xml.DtdParser.ScanCondSection1(), System.Xml.DtdParser.ScanCondSection2(), System.Xml.DtdParser.ScanCondSection3(), System.Xml.DtdParser.ScanDoctype1(), System.Xml.DtdParser.ScanDoctype2(), System.Xml.DtdParser.ScanElement1(), System.Xml.DtdParser.ScanElement2(), System.Xml.DtdParser.ScanElement3(), System.Xml.DtdParser.ScanElement4(), System.Xml.DtdParser.ScanElement5(), System.Xml.DtdParser.ScanElement6(), System.Xml.DtdParser.ScanElement7(), System.Xml.DtdParser.ScanEntity1(), System.Xml.DtdParser.ScanEntity2(), System.Xml.DtdParser.ScanEntity3(), System.Xml.DtdParser.ScanNameExpected(), System.Xml.DtdParser.ScanNmtokenExpected(), System.Xml.DtdParser.ScanNotation1(), System.Xml.DtdParser.ScanPublicId1(), System.Xml.DtdParser.ScanPublicId2(), System.Xml.DtdParser.ScanQNameExpected(), System.Xml.DtdParser.ScanSubsetContent(), System.Xml.DtdParser.ScanSystemId(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowInvalidChar(), System.SR.Xml_ExpectingWhiteSpace, and System.SR.Xml_IncompleteDtdContent.
Referenced by System.Xml.DtdParser.ParseAttlistDecl(), System.Xml.DtdParser.ParseAttlistDefault(), System.Xml.DtdParser.ParseAttlistType(), System.Xml.DtdParser.ParseCondSection(), System.Xml.DtdParser.ParseElementDecl(), System.Xml.DtdParser.ParseElementMixedContent(), System.Xml.DtdParser.ParseElementOnlyContent(), System.Xml.DtdParser.ParseEntityDecl(), System.Xml.DtdParser.ParseExternalId(), System.Xml.DtdParser.ParseHowMany(), System.Xml.DtdParser.ParseInDocumentDtd(), System.Xml.DtdParser.ParseNotationDecl(), and System.Xml.DtdParser.ParseSubset().