Terraria: System.Xml.DtdParser.ParseAttlistType
ParseAttlistType()
void System.Xml.DtdParser.ParseAttlistType (SchemaAttDef attrDef, SchemaElementDecl elementDecl, bool ignoreErrors) inline private
Definition at line 629 of file DtdParser.cs.
    {
        Token token = GetToken(needWhiteSpace: true);
        if (token != 0)
        {
            elementDecl.HasNonCDataAttribute = true;
        }
        if (IsAttributeValueType(token))
        {
            attrDef.TokenizedType = (XmlTokenizedType)token;
            attrDef.SchemaType = XmlSchemaType.GetBuiltInSimpleType(attrDef.Datatype.TypeCode);
            switch (token)
            {
            default:
                return;
            case Token.ID:
                if (_validate && elementDecl.IsIdDeclared)
                {
                    SchemaAttDef attDef = elementDecl.GetAttDef(attrDef.Name);
                    if ((attDef == null || attDef.Datatype.TokenizedType != XmlTokenizedType.ID) && !ignoreErrors)
                    {
                        SendValidationEvent(XmlSeverityType.Error, System.SR.Sch_IdAttrDeclared, elementDecl.Name.ToString());
                    }
                }
                elementDecl.IsIdDeclared = true;
                return;
            case Token.NOTATION:
                break;
            }
            if (_validate)
            {
                if (elementDecl.IsNotationDeclared && !ignoreErrors)
                {
                    SendValidationEvent(_curPos - 8, XmlSeverityType.Error, System.SR.Sch_DupNotationAttribute, elementDecl.Name.ToString());
                }
                else
                {
                    if (elementDecl.ContentValidator != null && elementDecl.ContentValidator.ContentType == XmlSchemaContentType.Empty && !ignoreErrors)
                    {
                        SendValidationEvent(_curPos - 8, XmlSeverityType.Error, System.SR.Sch_NotationAttributeOnEmptyElement, elementDecl.Name.ToString());
                    }
                    elementDecl.IsNotationDeclared = true;
                }
            }
            if (GetToken(needWhiteSpace: true) == Token.LeftParen && GetToken(needWhiteSpace: false) == Token.Name)
            {
                do
                {
                    string nameString = GetNameString();
                    if (!_schemaInfo.Notations.ContainsKey(nameString))
                    {
                        AddUndeclaredNotation(nameString);
                    }
                    if (_validate && !_v1Compat && attrDef.Values != null && attrDef.Values.Contains(nameString) && !ignoreErrors)
                    {
                        SendValidationEvent(XmlSeverityType.Error, new XmlSchemaException(System.SR.Xml_AttlistDuplNotationValue, nameString, BaseUriStr, LineNo, LinePos));
                    }
                    attrDef.AddValue(nameString);
                    switch (GetToken(needWhiteSpace: false))
                    {
                    case Token.Or:
                        continue;
                    case Token.RightParen:
                        return;
                    }
                    break;
                }
                while (GetToken(needWhiteSpace: false) == Token.Name);
            }
        }
        else if (token == Token.LeftParen)
        {
            attrDef.TokenizedType = XmlTokenizedType.ENUMERATION;
            attrDef.SchemaType = XmlSchemaType.GetBuiltInSimpleType(attrDef.Datatype.TypeCode);
            if (GetToken(needWhiteSpace: false) == Token.Nmtoken)
            {
                attrDef.AddValue(GetNameString());
                while (true)
                {
                    string nmtokenString;
                    switch (GetToken(needWhiteSpace: false))
                    {
                    case Token.Or:
                        if (GetToken(needWhiteSpace: false) == Token.Nmtoken)
{
                            nmtokenString = GetNmtokenString();
                            if (_validate && !_v1Compat && attrDef.Values != null && attrDef.Values.Contains(nmtokenString) && !ignoreErrors)
{
                                SendValidationEvent(XmlSeverityType.Error, new XmlSchemaException(System.SR.Xml_AttlistDuplEnumValue, nmtokenString, BaseUriStr, LineNo, LinePos));
                            }
                            goto IL_0278;
                        }
                        break;
                    case Token.RightParen:
                        return;
                    }
                    break;
                    IL_0278:
                    attrDef.AddValue(nmtokenString);
                }
            }
        }
        OnUnexpectedError();
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._v1Compat, System.Xml.DtdParser._validate, System.Xml.DtdParser.AddUndeclaredNotation(), System.Xml.DtdParser.BaseUriStr, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaType.GetBuiltInSimpleType(), System.Xml.DtdParser.GetNameString(), System.Xml.DtdParser.GetNmtokenString(), System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.IsAttributeValueType(), System.Xml.DtdParser.LineNo, System.Xml.DtdParser.LinePos, System.Xml.Schema.SchemaInfo.Notations, System.Xml.DtdParser.OnUnexpectedError(), System.SR.Sch_DupNotationAttribute, System.SR.Sch_IdAttrDeclared, System.SR.Sch_NotationAttributeOnEmptyElement, System.Xml.DtdParser.SendValidationEvent(), System.Collections.Generic.Dictionary< TKey, TValue >.Values, System.SR.Xml_AttlistDuplEnumValue, and System.SR.Xml_AttlistDuplNotationValue.
Referenced by System.Xml.DtdParser.ParseAttlistDecl().