Terraria: System.Xml.DtdParser.ParseEntityDeclAsync
ParseEntityDeclAsync()
async Task System.Xml.DtdParser.ParseEntityDeclAsync () inline private
Definition at line 3841 of file DtdParser.cs.
    {
        bool isParamEntity = false;
        Token token = await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false);
        if (token == Token.Name)
        {
            goto IL_013a;
        }
        if (token == Token.Percent)
        {
            isParamEntity = true;
            if (await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false) == Token.Name)
            {
                goto IL_013a;
            }
        }
        goto IL_0552;
        IL_013a:
        XmlQualifiedName nameQualified = GetNameQualified(canHavePrefix: false);
        SchemaEntity entity = new SchemaEntity(nameQualified, isParamEntity)
        {
            BaseURI = BaseUriStr,
            DeclaredURI = ((_externalDtdBaseUri.Length == 0) ? _documentBaseUri : _externalDtdBaseUri)
        };
        if (isParamEntity)
        {
            if (!_schemaInfo.ParameterEntities.ContainsKey(nameQualified))
            {
                _schemaInfo.ParameterEntities.Add(nameQualified, entity);
            }
        }
        else if (!_schemaInfo.GeneralEntities.ContainsKey(nameQualified))
        {
            _schemaInfo.GeneralEntities.Add(nameQualified, entity);
        }
        entity.DeclaredInExternal = !ParsingInternalSubset;
        entity.ParsingInProgress = true;
        Token token2 = await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false);
        if ((uint)(token2 - 33) > 1u)
        {
            if (token2 != Token.Literal)
            {
                goto IL_0552;
            }
            entity.Text = GetValue();
            entity.Line = _literalLineInfo.lineNo;
            entity.Pos = _literalLineInfo.linePos;
        }
        else
        {
            (string, string) tuple = await ParseExternalIdAsync(token2, Token.EntityDecl).ConfigureAwait(continueOnCapturedContext: false);
            string item = tuple.Item1;
            string item2 = tuple.Item2;
            entity.IsExternal = true;
            entity.Url = item2;
            entity.Pubid = item;
            if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) == Token.NData)
            {
                if (isParamEntity)
                {
                    ThrowUnexpectedToken(_curPos - 5, ">");
                }
                if (!_whitespaceSeen)
                {
                    Throw(_curPos - 5, System.SR.Xml_ExpectingWhiteSpace, "NDATA");
                }
                if (await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false) != Token.Name)
                {
                    goto IL_0552;
                }
                entity.NData = GetNameQualified(canHavePrefix: false);
                string name = entity.NData.Name;
                if (!_schemaInfo.Notations.ContainsKey(name))
                {
                    AddUndeclaredNotation(name);
                }
            }
        }
        if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) == Token.GreaterThan)
        {
            entity.ParsingInProgress = false;
            return;
        }
        goto IL_0552;
        IL_0552:
        OnUnexpectedError();
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._documentBaseUri, System.Xml.DtdParser._externalDtdBaseUri, System.Xml.DtdParser._literalLineInfo, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._whitespaceSeen, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.DtdParser.AddUndeclaredNotation(), System.Xml.DtdParser.BaseUriStr, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Dictionary, System.Xml.Schema.SchemaInfo.GeneralEntities, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.GetValue(), System.item, System.Xml.LineInfo.lineNo, System.Xml.LineInfo.linePos, System.Xml.Schema.SchemaInfo.Notations, System.Xml.DtdParser.OnUnexpectedError(), System.Xml.Schema.SchemaInfo.ParameterEntities, System.Xml.DtdParser.ParseExternalIdAsync(), System.Xml.DtdParser.ParsingInternalSubset, System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowUnexpectedToken(), and System.SR.Xml_ExpectingWhiteSpace.
Referenced by System.Xml.DtdParser.ParseSubsetAsync().