Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.GetExtenderProviders
GetExtenderProviders()
override IExtenderProvider[] System.ComponentModel.ReflectTypeDescriptionProvider.GetExtenderProviders (object instance) inline package virtual
Reimplemented from System.ComponentModel.TypeDescriptionProvider.
Definition at line 742 of file ReflectTypeDescriptionProvider.cs.
    {
        if (instance == null)
        {
            throw new ArgumentNullException("instance");
        }
        if (instance is IComponent { Site: not null } component)
        {
            IExtenderListService extenderListService = component.Site.GetService(typeof(IExtenderListService)) as IExtenderListService;
            IDictionary cache = TypeDescriptor.GetCache(instance);
            if (extenderListService != null)
            {
                return GetExtenders(extenderListService.GetExtenderProviders(), instance, cache);
            }
        }
        return Array.Empty<IExtenderProvider>();
    }
References System.ComponentModel.TypeDescriptor.GetCache(), and System.ComponentModel.ReflectTypeDescriptionProvider.GetExtenders().
Referenced by System.ComponentModel.ReflectTypeDescriptionProvider.GetExtendedProperties().