Terraria: System.Xml.DtdParser.ScanQName
ScanQName() [2/2]
void System.Xml.DtdParser.ScanQName (bool isQName) inline private
Definition at line 2662 of file DtdParser.cs.
    {
        _tokenStartPos = _curPos;
        int num = -1;
        while (true)
        {
            if (XmlCharType.IsStartNCNameSingleChar(_chars[_curPos]) || _chars[_curPos] == ':')
            {
                _curPos++;
            }
            else if (_curPos + 1 >= _charsUsed)
            {
                if (ReadDataInName())
                {
                    continue;
                }
                Throw(_curPos, System.SR.Xml_UnexpectedEOF, "Name");
            }
            else
            {
                Throw(_curPos, System.SR.Xml_BadStartNameChar, XmlException.BuildCharExceptionArgs(_chars, _charsUsed, _curPos));
            }
            while (true)
            {
                if (XmlCharType.IsNCNameSingleChar(_chars[_curPos]))
                {
                    _curPos++;
                    continue;
                }
                if (_chars[_curPos] == ':')
                {
                    if (isQName)
                    {
                        break;
                    }
                    _curPos++;
                    continue;
                }
                if (_curPos == _charsUsed)
                {
                    if (ReadDataInName())
                    {
                        continue;
                    }
                    if (_tokenStartPos == _curPos)
                    {
                        Throw(_curPos, System.SR.Xml_UnexpectedEOF, "Name");
                    }
                }
                _colonPos = ((num == -1) ? (-1) : (_tokenStartPos + num));
                return;
            }
            if (num != -1)
            {
                Throw(_curPos, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(':', '\0'));
            }
            num = _curPos - _tokenStartPos;
            _curPos++;
        }
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._colonPos, System.Xml.DtdParser._curPos, System.Xml.DtdParser._tokenStartPos, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), System.Xml.DtdParser.ReadDataInName(), System.Xml.DtdParser.Throw(), System.SR.Xml_BadNameChar, System.SR.Xml_BadStartNameChar, and System.SR.Xml_UnexpectedEOF.