Terraria: System.Xml.DtdParser.GetNameQualified
GetNameQualified()
XmlQualifiedName System.Xml.DtdParser.GetNameQualified (bool canHavePrefix) inline private
Definition at line 2803 of file DtdParser.cs.
    {
        if (_colonPos == -1)
        {
            return new XmlQualifiedName(_nameTable.Add(_chars, _tokenStartPos, _curPos - _tokenStartPos));
        }
        if (canHavePrefix)
        {
            return new XmlQualifiedName(_nameTable.Add(_chars, _colonPos + 1, _curPos - _colonPos - 1), _nameTable.Add(_chars, _tokenStartPos, _colonPos - _tokenStartPos));
        }
        Throw(_tokenStartPos, System.SR.Xml_ColonInLocalName, GetNameString());
        return null;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._colonPos, System.Xml.DtdParser._curPos, System.Xml.DtdParser._nameTable, System.Xml.DtdParser._tokenStartPos, System.Xml.XmlNameTable.Add(), System.Xml.DtdParser.GetNameString(), System.Xml.DtdParser.Throw(), and System.SR.Xml_ColonInLocalName.
Referenced by System.Xml.DtdParser.ParseAttlistDecl(), System.Xml.DtdParser.ParseAttlistDeclAsync(), System.Xml.DtdParser.ParseElementDecl(), System.Xml.DtdParser.ParseElementDeclAsync(), System.Xml.DtdParser.ParseElementMixedContent(), System.Xml.DtdParser.ParseElementMixedContentAsync(), System.Xml.DtdParser.ParseElementOnlyContent(), System.Xml.DtdParser.ParseElementOnlyContentAsync(), System.Xml.DtdParser.ParseEntityDecl(), System.Xml.DtdParser.ParseEntityDeclAsync(), System.Xml.DtdParser.ParseInDocumentDtd(), System.Xml.DtdParser.ParseInDocumentDtdAsync(), System.Xml.DtdParser.ParseNotationDecl(), System.Xml.DtdParser.ParseNotationDeclAsync(), and System.Xml.DtdParser.ScanEntityName().