Terraria: System.Xml.DtdParser.ParseExternalSubset
ParseExternalSubset()
void System.Xml.DtdParser.ParseExternalSubset () inline private
Definition at line 436 of file DtdParser.cs.
    {
        if (_readerAdapter.PushExternalSubset(_systemId, _publicId))
        {
            Uri baseUri = _readerAdapter.BaseUri;
            if (baseUri != null)
            {
                _externalDtdBaseUri = baseUri.ToString();
            }
            _externalEntitiesDepth++;
            LoadParsingBuffer();
            ParseSubset();
        }
    }
References System.Xml.DtdParser._externalDtdBaseUri, System.Xml.DtdParser._externalEntitiesDepth, System.Xml.DtdParser._publicId, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._systemId, System.Xml.IDtdParserAdapter.BaseUri, System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.DtdParser.ParseSubset(), System.Xml.IDtdParserAdapter.PushExternalSubset(), and System.Uri.ToString().
Referenced by System.Xml.DtdParser.ParseFreeFloatingDtd(), and System.Xml.DtdParser.ParseInDocumentDtd().