Terraria: System.Xml.DtdParser.ParseComment
ParseComment()
void System.Xml.DtdParser.ParseComment () inline private
Definition at line 1158 of file DtdParser.cs.
    {
        SaveParsingBuffer();
        try
        {
            if (SaveInternalSubsetValue)
            {
                _readerAdapter.ParseComment(_internalSubsetValueSb);
                _internalSubsetValueSb.Append("-->");
            }
            else
            {
                _readerAdapter.ParseComment(null);
            }
        }
        catch (XmlException ex)
        {
            if (!(ex.ResString == System.SR.Xml_UnexpectedEOF) || _currentEntityId == 0)
            {
                throw;
            }
            SendValidationEvent(XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, null);
        }
        LoadParsingBuffer();
    }
References System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._internalSubsetValueSb, System.Xml.DtdParser._readerAdapter, System.Text.StringBuilder.Append(), System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.IDtdParserAdapter.ParseComment(), System.Xml.DtdParser.SaveInternalSubsetValue, System.Xml.DtdParser.SaveParsingBuffer(), System.SR.Sch_ParEntityRefNesting, System.Xml.DtdParser.SendValidationEvent(), and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.DtdParser.ParseSubset().