Terraria: System.Xml.DtdParser.ScanSubsetContentAsync
ScanSubsetContentAsync()
async Task< Token > System.Xml.DtdParser.ScanSubsetContentAsync () inline private
Definition at line 4295 of file DtdParser.cs.
    {
        while (true)
        {
            char c = _chars[_curPos];
            if (c != '<')
            {
                if (c != ']')
                {
                    goto IL_0548;
                }
                if (_charsUsed - _curPos >= 2 || _readerAdapter.IsEof)
                {
                    if (_chars[_curPos + 1] != ']')
                    {
                        _curPos++;
                        _scanningFunction = ScanningFunction.ClosingTag;
                        return Token.RightBracket;
                    }
                    if (_charsUsed - _curPos >= 3 || _readerAdapter.IsEof)
                    {
                        if (_chars[_curPos + 1] == ']' && _chars[_curPos + 2] == '>')
{
                            break;
                        }
                        goto IL_0548;
                    }
                }
            }
            else
            {
                switch (_chars[_curPos + 1])
                {
                case '!':
                    switch (_chars[_curPos + 2])
                    {
                    case 'E':
                        if (_chars[_curPos + 3] == 'L')
{
                            if (_charsUsed - _curPos >= 9)
{
                                if (_chars[_curPos + 4] != 'E' || _chars[_curPos + 5] != 'M' || _chars[_curPos + 6] != 'E' || _chars[_curPos + 7] != 'N' || _chars[_curPos + 8] != 'T')
{
                                    Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                                }
                                _curPos += 9;
                                _scanningFunction = ScanningFunction.QName;
                                _nextScaningFunction = ScanningFunction.Element1;
                                return Token.ElementDecl;
                            }
                        }
                        else if (_chars[_curPos + 3] == 'N')
{
                            if (_charsUsed - _curPos >= 8)
{
                                if (_chars[_curPos + 4] != 'T' || _chars[_curPos + 5] != 'I' || _chars[_curPos + 6] != 'T' || _chars[_curPos + 7] != 'Y')
{
                                    Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                                }
                                _curPos += 8;
                                _scanningFunction = ScanningFunction.Entity1;
                                return Token.EntityDecl;
                            }
                        }
                        else if (_charsUsed - _curPos >= 4)
{
                            Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                            return Token.None;
                        }
                        break;
                    case 'A':
                        if (_charsUsed - _curPos >= 9)
{
                            if (_chars[_curPos + 3] != 'T' || _chars[_curPos + 4] != 'T' || _chars[_curPos + 5] != 'L' || _chars[_curPos + 6] != 'I' || _chars[_curPos + 7] != 'S' || _chars[_curPos + 8] != 'T')
{
                                Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                            }
                            _curPos += 9;
                            _scanningFunction = ScanningFunction.QName;
                            _nextScaningFunction = ScanningFunction.Attlist1;
                            return Token.AttlistDecl;
                        }
                        break;
                    case 'N':
                        if (_charsUsed - _curPos >= 10)
{
                            if (_chars[_curPos + 3] != 'O' || _chars[_curPos + 4] != 'T' || _chars[_curPos + 5] != 'A' || _chars[_curPos + 6] != 'T' || _chars[_curPos + 7] != 'I' || _chars[_curPos + 8] != 'O' || _chars[_curPos + 9] != 'N')
{
                                Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                            }
                            _curPos += 10;
                            _scanningFunction = ScanningFunction.Name;
                            _nextScaningFunction = ScanningFunction.Notation1;
                            return Token.NotationDecl;
                        }
                        break;
                    case '[':
                        _curPos += 3;
                        _scanningFunction = ScanningFunction.CondSection1;
                        return Token.CondSectionStart;
                    case '-':
                        if (_chars[_curPos + 3] == '-')
{
                            _curPos += 4;
                            return Token.Comment;
                        }
                        if (_charsUsed - _curPos >= 4)
{
                            Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                        }
                        break;
                    default:
                        if (_charsUsed - _curPos >= 3)
{
                            Throw(_curPos + 2, System.SR.Xml_ExpectDtdMarkup);
                        }
                        break;
                    }
                    break;
                case '?':
                    _curPos += 2;
                    return Token.PI;
                default:
                    if (_charsUsed - _curPos >= 2)
                    {
                        Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                        return Token.None;
                    }
                    break;
                }
            }
            goto IL_0568;
            IL_0568:
            if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
            {
                Throw(_charsUsed, System.SR.Xml_IncompleteDtdContent);
            }
            continue;
            IL_0548:
            if (_charsUsed - _curPos != 0)
            {
                Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
            }
            goto IL_0568;
        }
        _curPos += 3;
        return Token.CondSectionEnd;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._nextScaningFunction, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._scanningFunction, System.Xml.Dictionary, System.Xml.IDtdParserAdapter.IsEof, System.Xml.DtdParser.ReadDataAsync(), System.Xml.DtdParser.Throw(), System.SR.Xml_ExpectDtdMarkup, and System.SR.Xml_IncompleteDtdContent.
Referenced by System.Xml.DtdParser.GetTokenAsync().