Terraria: System.Xml.DtdParser.ParseCommentAsync
ParseCommentAsync()
async Task System.Xml.DtdParser.ParseCommentAsync () inline private
Definition at line 3970 of file DtdParser.cs.
    {
        SaveParsingBuffer();
        try
        {
            if (!SaveInternalSubsetValue)
            {
                await _readerAdapter.ParseCommentAsync(null).ConfigureAwait(continueOnCapturedContext: false);
            }
            else
            {
                await _readerAdapter.ParseCommentAsync(_internalSubsetValueSb).ConfigureAwait(continueOnCapturedContext: false);
                _internalSubsetValueSb.Append("-->");
            }
        }
        catch (XmlException ex)
        {
            if (!(ex.ResString == System.SR.Xml_UnexpectedEOF) || _currentEntityId == 0)
            {
                throw;
            }
            SendValidationEvent(XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, null);
        }
        LoadParsingBuffer();
    }
References System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._internalSubsetValueSb, System.Xml.DtdParser._readerAdapter, System.Text.StringBuilder.Append(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.IDtdParserAdapter.ParseCommentAsync(), System.Xml.DtdParser.SaveInternalSubsetValue, System.Xml.DtdParser.SaveParsingBuffer(), System.SR.Sch_ParEntityRefNesting, System.Xml.DtdParser.SendValidationEvent(), and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.DtdParser.ParseSubsetAsync().