Terraria: System.Xml.DtdParser.ParseExternalSubsetAsync
ParseExternalSubsetAsync()
async Task System.Xml.DtdParser.ParseExternalSubsetAsync () inline private
Definition at line 3262 of file DtdParser.cs.
    {
        if (await _readerAdapter.PushExternalSubsetAsync(_systemId, _publicId).ConfigureAwait(continueOnCapturedContext: false))
        {
            Uri baseUri = _readerAdapter.BaseUri;
            if (baseUri != null)
            {
                _externalDtdBaseUri = baseUri.ToString();
            }
            _externalEntitiesDepth++;
            LoadParsingBuffer();
            await ParseSubsetAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.DtdParser._externalDtdBaseUri, System.Xml.DtdParser._externalEntitiesDepth, System.Xml.DtdParser._publicId, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._systemId, System.Xml.IDtdParserAdapter.BaseUri, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.DtdParser.ParseSubsetAsync(), System.Xml.IDtdParserAdapter.PushExternalSubsetAsync(), and System.Uri.ToString().
Referenced by System.Xml.DtdParser.ParseFreeFloatingDtdAsync(), and System.Xml.DtdParser.ParseInDocumentDtdAsync().