Terraria: System.Xml.DtdParser.ParseSubsetAsync
ParseSubsetAsync()
async Task System.Xml.DtdParser.ParseSubsetAsync () inline private
Definition at line 3277 of file DtdParser.cs.
    {
        while (true)
        {
            Token token = await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false);
            int startTagEntityId = _currentEntityId;
            switch (token)
            {
            case Token.AttlistDecl:
                await ParseAttlistDeclAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case Token.ElementDecl:
                await ParseElementDeclAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case Token.EntityDecl:
                await ParseEntityDeclAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case Token.NotationDecl:
                await ParseNotationDeclAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case Token.Comment:
                await ParseCommentAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case Token.PI:
                await ParsePIAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            case Token.CondSectionStart:
                if (ParsingInternalSubset)
                {
                    Throw(_curPos - 3, System.SR.Xml_InvalidConditionalSection);
                }
                await ParseCondSectionAsync().ConfigureAwait(continueOnCapturedContext: false);
                startTagEntityId = _currentEntityId;
                break;
            case Token.CondSectionEnd:
                if (_condSectionDepth > 0)
                {
                    _condSectionDepth--;
                    if (_validate && _currentEntityId != _condSectionEntityIds[_condSectionDepth])
                    {
                        SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                    }
                }
                else
                {
                    Throw(_curPos - 3, System.SR.Xml_UnexpectedCDataEnd);
                }
                break;
            case Token.RightBracket:
                if (ParsingInternalSubset)
                {
                    if (_condSectionDepth != 0)
                    {
                        Throw(_curPos, System.SR.Xml_UnclosedConditionalSection);
                    }
                    if (_internalSubsetValueSb != null)
                    {
                        SaveParsingBuffer(_curPos - 1);
                        _schemaInfo.InternalDtdSubset = _internalSubsetValueSb.ToString();
                        _internalSubsetValueSb = null;
                    }
                    if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) != Token.GreaterThan)
                    {
                        ThrowUnexpectedToken(_curPos, ">");
                    }
                }
                else
                {
                    Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                }
                return;
            case Token.Eof:
                if (ParsingInternalSubset && !_freeFloatingDtd)
                {
                    Throw(_curPos, System.SR.Xml_IncompleteDtdContent);
                }
                if (_condSectionDepth != 0)
                {
                    Throw(_curPos, System.SR.Xml_UnclosedConditionalSection);
                }
                return;
            }
            if (_currentEntityId != startTagEntityId)
            {
                if (_validate)
                {
                    SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                }
                else if (!_v1Compat)
                {
                    Throw(_curPos, System.SR.Sch_ParEntityRefNesting);
                }
            }
        }
    }
References System.Xml.DtdParser._condSectionDepth, System.Xml.DtdParser._condSectionEntityIds, System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._freeFloatingDtd, System.Xml.DtdParser._internalSubsetValueSb, System.Xml.DtdParser._v1Compat, System.Xml.DtdParser._validate, System.Xml.Dictionary, System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.ParseAttlistDeclAsync(), System.Xml.DtdParser.ParseCommentAsync(), System.Xml.DtdParser.ParseCondSectionAsync(), System.Xml.DtdParser.ParseElementDeclAsync(), System.Xml.DtdParser.ParseEntityDeclAsync(), System.Xml.DtdParser.ParseNotationDeclAsync(), System.Xml.DtdParser.ParsePIAsync(), System.Xml.DtdParser.ParsingInternalSubset, System.Xml.DtdParser.SaveParsingBuffer(), System.SR.Sch_ParEntityRefNesting, System.Xml.DtdParser.SendValidationEvent(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowUnexpectedToken(), System.Text.StringBuilder.ToString(), System.SR.Xml_ExpectDtdMarkup, System.SR.Xml_IncompleteDtdContent, System.SR.Xml_InvalidConditionalSection, System.SR.Xml_UnclosedConditionalSection, and System.SR.Xml_UnexpectedCDataEnd.
Referenced by System.Xml.DtdParser.ParseExternalSubsetAsync(), and System.Xml.DtdParser.ParseInternalSubsetAsync().