Terraria: System.Xml.DtdParser.GetValueWithStrippedSpaces
GetValueWithStrippedSpaces()
string System.Xml.DtdParser.GetValueWithStrippedSpaces () inline private
Definition at line 2836 of file DtdParser.cs.
    {
        string value = ((_stringBuilder.Length == 0) ? new string(_chars, _tokenStartPos, _curPos - _tokenStartPos - 1) : _stringBuilder.ToString());
        return StripSpaces(value);
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._curPos, System.Xml.DtdParser._stringBuilder, System.Xml.DtdParser._tokenStartPos, System.Xml.Dictionary, System.Xml.DtdParser.StripSpaces(), System.Text.StringBuilder.ToString(), and System.value.
Referenced by System.Xml.DtdParser.ParseAttlistDefault(), and System.Xml.DtdParser.ParseAttlistDefaultAsync().