Terraria: System.Xml.DtdParser.InitializeFreeFloatingDtd
InitializeFreeFloatingDtd()
void System.Xml.DtdParser.InitializeFreeFloatingDtd (string baseUri, string docTypeName, string publicId, string systemId, string internalSubset, IDtdParserAdapter adapter) inline private
Definition at line 292 of file DtdParser.cs.
    {
        Initialize(adapter);
        if (docTypeName == null || docTypeName.Length == 0)
        {
            throw XmlConvert.CreateInvalidNameArgumentException(docTypeName, "docTypeName");
        }
        XmlConvert.VerifyName(docTypeName);
        int num = docTypeName.IndexOf(':');
        if (num == -1)
        {
            _schemaInfo.DocTypeName = new XmlQualifiedName(_nameTable.Add(docTypeName));
        }
        else
        {
            _schemaInfo.DocTypeName = new XmlQualifiedName(_nameTable.Add(docTypeName.Substring(0, num)), _nameTable.Add(docTypeName.Substring(num + 1)));
        }
        if (systemId != null && systemId.Length > 0)
        {
            int invCharPos;
            if ((invCharPos = XmlCharType.IsOnlyCharData(systemId)) >= 0)
            {
                ThrowInvalidChar(_curPos, systemId, invCharPos);
            }
            _systemId = systemId;
        }
        if (publicId != null && publicId.Length > 0)
        {
            int invCharPos;
            if ((invCharPos = XmlCharType.IsPublicId(publicId)) >= 0)
            {
                ThrowInvalidChar(_curPos, publicId, invCharPos);
            }
            _publicId = publicId;
        }
        if (internalSubset != null && internalSubset.Length > 0)
        {
            _readerAdapter.PushInternalDtd(baseUri, internalSubset);
            _hasFreeFloatingInternalSubset = true;
        }
        Uri baseUri2 = _readerAdapter.BaseUri;
        if (baseUri2 != null)
        {
            _documentBaseUri = baseUri2.ToString();
        }
        _freeFloatingDtd = true;
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._documentBaseUri, System.Xml.DtdParser._freeFloatingDtd, System.Xml.DtdParser._hasFreeFloatingInternalSubset, System.Xml.DtdParser._nameTable, System.Xml.DtdParser._publicId, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._systemId, System.Xml.XmlNameTable.Add(), System.Xml.IDtdParserAdapter.BaseUri, System.Xml.XmlConvert.CreateInvalidNameArgumentException(), System.Xml.Dictionary, System.Xml.DtdParser.Initialize(), System.Xml.XmlCharType.IsOnlyCharData(), System.Xml.XmlCharType.IsPublicId(), System.Xml.IDtdParserAdapter.PushInternalDtd(), System.Xml.DtdParser.ThrowInvalidChar(), and System.Xml.XmlConvert.VerifyName().
Referenced by System.Xml.DtdParser.ParseFreeFloatingDtd(), and System.Xml.DtdParser.ParseFreeFloatingDtdAsync().