Terraria: System.Xml.DtdParser.ParseExternalIdAsync
ParseExternalIdAsync()
async Task<(string, string)> System.Xml.DtdParser.ParseExternalIdAsync (Token idTokenType, Token declType) inline private
Definition at line 4064 of file DtdParser.cs.
    {
        LineInfo keywordLineInfo = new LineInfo(LineNo, LinePos - 6);
        string publicId = null;
        string systemId = null;
        if (await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false) != Token.Literal)
        {
            ThrowUnexpectedToken(_curPos, "\"", "'");
        }
        if (idTokenType == Token.SYSTEM)
        {
            systemId = GetValue();
            if (systemId.Contains('#'))
            {
                Throw(_curPos - systemId.Length - 1, System.SR.Xml_FragmentId, new string[2]
                {
                    systemId.Substring(systemId.IndexOf('#')),
                    systemId
                });
            }
            if (declType == Token.DOCTYPE && !_freeFloatingDtd)
            {
                _literalLineInfo.linePos++;
                _readerAdapter.OnSystemId(systemId, keywordLineInfo, _literalLineInfo);
            }
        }
        else
        {
            publicId = GetValue();
            int num;
            if ((num = XmlCharType.IsPublicId(publicId)) >= 0)
            {
                ThrowInvalidChar(_curPos - 1 - publicId.Length + num, publicId, num);
            }
            if (declType == Token.DOCTYPE && !_freeFloatingDtd)
            {
                _literalLineInfo.linePos++;
                _readerAdapter.OnPublicId(publicId, keywordLineInfo, _literalLineInfo);
                if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) == Token.Literal)
                {
                    if (!_whitespaceSeen)
                    {
                        Throw(System.SR.Xml_ExpectingWhiteSpace, char.ToString(_literalQuoteChar), _literalLineInfo.lineNo, _literalLineInfo.linePos);
                    }
                    systemId = GetValue();
                    _literalLineInfo.linePos++;
                    _readerAdapter.OnSystemId(systemId, keywordLineInfo, _literalLineInfo);
                }
                else
                {
                    ThrowUnexpectedToken(_curPos, "\"", "'");
                }
            }
            else if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) == Token.Literal)
            {
                if (!_whitespaceSeen)
                {
                    Throw(System.SR.Xml_ExpectingWhiteSpace, char.ToString(_literalQuoteChar), _literalLineInfo.lineNo, _literalLineInfo.linePos);
                }
                systemId = GetValue();
            }
            else if (declType != Token.NOTATION)
            {
                ThrowUnexpectedToken(_curPos, "\"", "'");
            }
        }
        return (publicId, systemId);
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._freeFloatingDtd, System.Xml.DtdParser._literalLineInfo, System.Xml.DtdParser._literalQuoteChar, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._whitespaceSeen, System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.GetValue(), System.Xml.XmlCharType.IsPublicId(), System.Xml.DtdParser.LineNo, System.Xml.LineInfo.lineNo, System.Xml.DtdParser.LinePos, System.Xml.LineInfo.linePos, System.Xml.IDtdParserAdapter.OnPublicId(), System.Xml.IDtdParserAdapter.OnSystemId(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowInvalidChar(), System.Xml.DtdParser.ThrowUnexpectedToken(), System.SR.Xml_ExpectingWhiteSpace, and System.SR.Xml_FragmentId.
Referenced by System.Xml.DtdParser.ParseEntityDeclAsync(), System.Xml.DtdParser.ParseInDocumentDtdAsync(), and System.Xml.DtdParser.ParseNotationDeclAsync().