Terraria: System.Xml.DtdParser.ParseAttlistDecl
ParseAttlistDecl()
void System.Xml.DtdParser.ParseAttlistDecl () inline private
Definition at line 547 of file DtdParser.cs.
    {
        if (GetToken(needWhiteSpace: true) == Token.QName)
        {
            XmlQualifiedName nameQualified = GetNameQualified(canHavePrefix: true);
            if (!_schemaInfo.ElementDecls.TryGetValue(nameQualified, out var value) && !_schemaInfo.UndeclaredElementDecls.TryGetValue(nameQualified, out value))
            {
                value = new SchemaElementDecl(nameQualified, nameQualified.Namespace);
                _schemaInfo.UndeclaredElementDecls.Add(nameQualified, value);
            }
            SchemaAttDef schemaAttDef = null;
            while (true)
            {
                switch (GetToken(needWhiteSpace: false))
                {
                case Token.QName:
                {
                    XmlQualifiedName nameQualified2 = GetNameQualified(canHavePrefix: true);
                    schemaAttDef = new SchemaAttDef(nameQualified2, nameQualified2.Namespace);
                    schemaAttDef.IsDeclaredInExternal = !ParsingInternalSubset;
                    schemaAttDef.LineNumber = LineNo;
                    schemaAttDef.LinePosition = LinePos - (_curPos - _tokenStartPos);
                    bool flag = value.GetAttDef(schemaAttDef.Name) != null;
                    ParseAttlistType(schemaAttDef, value, flag);
                    ParseAttlistDefault(schemaAttDef, flag);
                    if (schemaAttDef.Prefix.Length > 0 && schemaAttDef.Prefix.Equals("xml"))
                    {
                        if (schemaAttDef.Name.Name == "space")
{
                            if (_v1Compat)
{
                                string text = schemaAttDef.DefaultValueExpanded.Trim();
                                if (text.Equals("preserve") || text.Equals("default"))
{
                                    schemaAttDef.Reserved = SchemaAttDef.Reserve.XmlSpace;
                                }
                            }
                            else
{
                                schemaAttDef.Reserved = SchemaAttDef.Reserve.XmlSpace;
                                if (schemaAttDef.TokenizedType != XmlTokenizedType.ENUMERATION)
{
                                    Throw(System.SR.Xml_EnumerationRequired, string.Empty, schemaAttDef.LineNumber, schemaAttDef.LinePosition);
                                }
                                if (_validate)
{
                                    schemaAttDef.CheckXmlSpace(_readerAdapterWithValidation.ValidationEventHandling);
                                }
                            }
                        }
                        else if (schemaAttDef.Name.Name == "lang")
{
                            schemaAttDef.Reserved = SchemaAttDef.Reserve.XmlLang;
                        }
                    }
                    if (!flag)
                    {
                        value.AddAttDef(schemaAttDef);
                    }
                    continue;
                }
                case Token.GreaterThan:
                    if (_v1Compat && schemaAttDef != null && schemaAttDef.Prefix.Length > 0 && schemaAttDef.Prefix.Equals("xml") && schemaAttDef.Name.Name == "space")
                    {
                        schemaAttDef.Reserved = SchemaAttDef.Reserve.XmlSpace;
                        if (schemaAttDef.Datatype.TokenizedType != XmlTokenizedType.ENUMERATION)
{
                            Throw(System.SR.Xml_EnumerationRequired, string.Empty, schemaAttDef.LineNumber, schemaAttDef.LinePosition);
                        }
                        if (_validate)
{
                            schemaAttDef.CheckXmlSpace(_readerAdapterWithValidation.ValidationEventHandling);
                        }
                    }
                    return;
                }
                break;
            }
        }
        OnUnexpectedError();
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._readerAdapterWithValidation, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._tokenStartPos, System.Xml.DtdParser._v1Compat, System.Xml.DtdParser._validate, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Schema.SchemaInfo.ElementDecls, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.LineNo, System.Xml.DtdParser.LinePos, System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseAttlistDefault(), System.Xml.DtdParser.ParseAttlistType(), System.Xml.DtdParser.ParsingInternalSubset, System.text, System.Xml.DtdParser.Throw(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Xml.Schema.SchemaInfo.UndeclaredElementDecls, System.Xml.IDtdParserAdapterWithValidation.ValidationEventHandling, System.value, and System.SR.Xml_EnumerationRequired.
Referenced by System.Xml.DtdParser.ParseSubset().