Terraria: System.Security.Cryptography.CngPkcs8.ImportPkcs8
ImportPkcs8() [2/6]
static Pkcs8Response System.Security.Cryptography.CngPkcs8.ImportPkcs8 (AsnWriter pkcs8Writer) inline static private
Definition at line 123 of file CngPkcs8.cs.
    {
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(pkcs8Writer.GetEncodedLength());
        if (!pkcs8Writer.TryEncode(array, out var bytesWritten))
        {
            throw new CryptographicException();
        }
        Pkcs8Response result = ImportPkcs8(array.AsSpan(0, bytesWritten));
        System.Security.Cryptography.CryptoPool.Return(array, bytesWritten);
        return result;
    }
References System.array, System.Formats.Asn1.AsnWriter.GetEncodedLength(), System.Security.Cryptography.CngPkcs8.ImportPkcs8(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), and System.Formats.Asn1.AsnWriter.TryEncode().