Terraria: System.Xml.DtdParser.ParseSubset
ParseSubset()
void System.Xml.DtdParser.ParseSubset () inline private
Definition at line 451 of file DtdParser.cs.
    {
        while (true)
        {
            Token token = GetToken(needWhiteSpace: false);
            int currentEntityId = _currentEntityId;
            switch (token)
            {
            case Token.AttlistDecl:
                ParseAttlistDecl();
                break;
            case Token.ElementDecl:
                ParseElementDecl();
                break;
            case Token.EntityDecl:
                ParseEntityDecl();
                break;
            case Token.NotationDecl:
                ParseNotationDecl();
                break;
            case Token.Comment:
                ParseComment();
                break;
            case Token.PI:
                ParsePI();
                break;
            case Token.CondSectionStart:
                if (ParsingInternalSubset)
                {
                    Throw(_curPos - 3, System.SR.Xml_InvalidConditionalSection);
                }
                ParseCondSection();
                currentEntityId = _currentEntityId;
                break;
            case Token.CondSectionEnd:
                if (_condSectionDepth > 0)
                {
                    _condSectionDepth--;
                    if (_validate && _currentEntityId != _condSectionEntityIds[_condSectionDepth])
                    {
                        SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                    }
                }
                else
                {
                    Throw(_curPos - 3, System.SR.Xml_UnexpectedCDataEnd);
                }
                break;
            case Token.RightBracket:
                if (ParsingInternalSubset)
                {
                    if (_condSectionDepth != 0)
                    {
                        Throw(_curPos, System.SR.Xml_UnclosedConditionalSection);
                    }
                    if (_internalSubsetValueSb != null)
                    {
                        SaveParsingBuffer(_curPos - 1);
                        _schemaInfo.InternalDtdSubset = _internalSubsetValueSb.ToString();
                        _internalSubsetValueSb = null;
                    }
                    if (GetToken(needWhiteSpace: false) != Token.GreaterThan)
                    {
                        ThrowUnexpectedToken(_curPos, ">");
                    }
                }
                else
                {
                    Throw(_curPos, System.SR.Xml_ExpectDtdMarkup);
                }
                return;
            case Token.Eof:
                if (ParsingInternalSubset && !_freeFloatingDtd)
                {
                    Throw(_curPos, System.SR.Xml_IncompleteDtdContent);
                }
                if (_condSectionDepth != 0)
                {
                    Throw(_curPos, System.SR.Xml_UnclosedConditionalSection);
                }
                return;
            }
            if (_currentEntityId != currentEntityId)
            {
                if (_validate)
                {
                    SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                }
                else if (!_v1Compat)
                {
                    Throw(_curPos, System.SR.Sch_ParEntityRefNesting);
                }
            }
        }
    }
References System.Xml.DtdParser._condSectionDepth, System.Xml.DtdParser._condSectionEntityIds, System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._freeFloatingDtd, System.Xml.DtdParser._internalSubsetValueSb, System.Xml.DtdParser._v1Compat, System.Xml.DtdParser._validate, System.Xml.Dictionary, System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.ParseAttlistDecl(), System.Xml.DtdParser.ParseComment(), System.Xml.DtdParser.ParseCondSection(), System.Xml.DtdParser.ParseElementDecl(), System.Xml.DtdParser.ParseEntityDecl(), System.Xml.DtdParser.ParseNotationDecl(), System.Xml.DtdParser.ParsePI(), System.Xml.DtdParser.ParsingInternalSubset, System.Xml.DtdParser.SaveParsingBuffer(), System.SR.Sch_ParEntityRefNesting, System.Xml.DtdParser.SendValidationEvent(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowUnexpectedToken(), System.Text.StringBuilder.ToString(), System.SR.Xml_ExpectDtdMarkup, System.SR.Xml_IncompleteDtdContent, System.SR.Xml_InvalidConditionalSection, System.SR.Xml_UnclosedConditionalSection, and System.SR.Xml_UnexpectedCDataEnd.
Referenced by System.Xml.DtdParser.ParseExternalSubset(), and System.Xml.DtdParser.ParseInternalSubset().