Terraria: System.Xml.DtdParser.ScanEntity2
ScanEntity2()
Token System.Xml.DtdParser.ScanEntity2 () inline private
Definition at line 2410 of file DtdParser.cs.
    {
        switch (_chars[_curPos])
        {
        case 'P':
            if (!EatPublicKeyword())
            {
                Throw(_curPos, System.SR.Xml_ExpectExternalOrClose);
            }
            _nextScaningFunction = ScanningFunction.Entity3;
            _scanningFunction = ScanningFunction.PublicId1;
            return Token.PUBLIC;
        case 'S':
            if (!EatSystemKeyword())
            {
                Throw(_curPos, System.SR.Xml_ExpectExternalOrClose);
            }
            _nextScaningFunction = ScanningFunction.Entity3;
            _scanningFunction = ScanningFunction.SystemId;
            return Token.SYSTEM;
        case '"':
        case '\'':
            ScanLiteral(LiteralType.EntityReplText);
            _scanningFunction = ScanningFunction.ClosingTag;
            return Token.Literal;
        default:
            Throw(_curPos, System.SR.Xml_ExpectExternalIdOrEntityValue);
            return Token.None;
        }
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._curPos, System.Xml.DtdParser._nextScaningFunction, System.Xml.DtdParser._scanningFunction, System.Xml.DtdParser.EatPublicKeyword(), System.Xml.DtdParser.EatSystemKeyword(), System.Xml.DtdParser.ScanLiteral(), System.Xml.DtdParser.Throw(), System.SR.Xml_ExpectExternalIdOrEntityValue, and System.SR.Xml_ExpectExternalOrClose.
Referenced by System.Xml.DtdParser.GetToken().