Terraria: System.Xml.DtdParser.ReadDataAsync
ReadDataAsync()
async Task< int > System.Xml.DtdParser.ReadDataAsync () inline private
Definition at line 5431 of file DtdParser.cs.
    {
        SaveParsingBuffer();
        int result = await _readerAdapter.ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false);
        LoadParsingBuffer();
        return result;
    }
References System.Xml.DtdParser._readerAdapter, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.IDtdParserAdapter.ReadDataAsync(), and System.Xml.DtdParser.SaveParsingBuffer().
Referenced by System.Xml.DtdParser.EatPublicKeywordAsync(), System.Xml.DtdParser.EatSystemKeywordAsync(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.ReadDataInNameAsync(), System.Xml.DtdParser.ScanAttlist2Async(), System.Xml.DtdParser.ScanAttlist6Async(), System.Xml.DtdParser.ScanCondSection1Async(), System.Xml.DtdParser.ScanCondSection3Async(), System.Xml.DtdParser.ScanElement1Async(), System.Xml.DtdParser.ScanElement2Async(), System.Xml.DtdParser.ScanEntity3Async(), System.Xml.DtdParser.ScanLiteralAsync(), System.Xml.DtdParser.ScanNmtokenAsync(), and System.Xml.DtdParser.ScanSubsetContentAsync().