Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetAttributes
ReflectGetAttributes() [2/2]
static Attribute[] System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetAttributes (Type type) inline static package
Definition at line 980 of file ReflectTypeDescriptionProvider.cs.
    {
        Hashtable attributeCache = AttributeCache;
        Attribute[] array = (Attribute[])attributeCache[type];
        if (array != null)
        {
            return array;
        }
        lock (s_internalSyncObject)
        {
            array = (Attribute[])attributeCache[type];
            if (array == null)
            {
                array = (Attribute[])(attributeCache[type] = type.GetCustomAttributes(typeof(Attribute), inherit: false).OfType<Attribute>().ToArray());
            }
        }
        return array;
    }
References System.array, System.ComponentModel.ReflectTypeDescriptionProvider.AttributeCache, System.ComponentModel.ReflectTypeDescriptionProvider.s_internalSyncObject, and System.type.
Referenced by System.ComponentModel.ReflectPropertyDescriptor.FillAttributes(), System.ComponentModel.ReflectEventDescriptor.FillEventInfoAttribute(), System.ComponentModel.ReflectEventDescriptor.FillSingleMethodAttribute(), and System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetAttributes().