Terraria: System.Xml.DtdParser.VerifyEntityReference
VerifyEntityReference()
SchemaEntity System.Xml.DtdParser.VerifyEntityReference (XmlQualifiedName entityName, bool paramEntity, bool mustBeDeclared, bool inAttribute) inline private
Definition at line 2955 of file DtdParser.cs.
    {
        SchemaEntity value;
        if (paramEntity)
        {
            _schemaInfo.ParameterEntities.TryGetValue(entityName, out value);
        }
        else
        {
            _schemaInfo.GeneralEntities.TryGetValue(entityName, out value);
        }
        if (value == null)
        {
            if (paramEntity)
            {
                if (_validate)
                {
                    SendValidationEvent(_curPos - entityName.Name.Length - 1, XmlSeverityType.Error, System.SR.Xml_UndeclaredParEntity, entityName.Name);
                }
            }
            else if (mustBeDeclared)
            {
                if (!ParsingInternalSubset)
                {
                    if (_validate)
                    {
                        SendValidationEvent(_curPos - entityName.Name.Length - 1, XmlSeverityType.Error, System.SR.Xml_UndeclaredEntity, entityName.Name);
                    }
                }
                else
                {
                    Throw(_curPos - entityName.Name.Length - 1, System.SR.Xml_UndeclaredEntity, entityName.Name);
                }
            }
            return null;
        }
        if (!value.NData.IsEmpty)
        {
            Throw(_curPos - entityName.Name.Length - 1, System.SR.Xml_UnparsedEntityRef, entityName.Name);
        }
        if (inAttribute && value.IsExternal)
        {
            Throw(_curPos - entityName.Name.Length - 1, System.SR.Xml_ExternalEntityInAttValue, entityName.Name);
        }
        return value;
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._validate, System.Xml.Schema.SchemaInfo.GeneralEntities, System.Xml.Schema.SchemaInfo.ParameterEntities, System.Xml.DtdParser.ParsingInternalSubset, System.Xml.DtdParser.SendValidationEvent(), System.Xml.DtdParser.Throw(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, System.SR.Xml_ExternalEntityInAttValue, System.SR.Xml_UndeclaredEntity, System.SR.Xml_UndeclaredParEntity, and System.SR.Xml_UnparsedEntityRef.
Referenced by System.Xml.DtdParser.HandleEntityReference(), System.Xml.DtdParser.HandleEntityReferenceAsync(), System.Xml.DtdParser.ScanLiteral(), and System.Xml.DtdParser.ScanLiteralAsync().