Terraria: System.Xml.DtdParser.LoadParsingBuffer
LoadParsingBuffer()
void System.Xml.DtdParser.LoadParsingBuffer () inline private
Definition at line 2850 of file DtdParser.cs.
    {
        _chars = _readerAdapter.ParsingBuffer;
        _charsUsed = _readerAdapter.ParsingBufferLength;
        _curPos = _readerAdapter.CurrentPosition;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._readerAdapter, System.Xml.IDtdParserAdapter.CurrentPosition, System.Xml.IDtdParserAdapter.ParsingBuffer, and System.Xml.IDtdParserAdapter.ParsingBufferLength.
Referenced by System.Xml.DtdParser.HandleEntityEnd(), System.Xml.DtdParser.HandleEntityReference(), System.Xml.DtdParser.HandleEntityReferenceAsync(), System.Xml.DtdParser.ParseComment(), System.Xml.DtdParser.ParseCommentAsync(), System.Xml.DtdParser.ParseExternalSubset(), System.Xml.DtdParser.ParseExternalSubsetAsync(), System.Xml.DtdParser.ParseFreeFloatingDtd(), System.Xml.DtdParser.ParseFreeFloatingDtdAsync(), System.Xml.DtdParser.ParseInDocumentDtd(), System.Xml.DtdParser.ParseInDocumentDtdAsync(), System.Xml.DtdParser.ParsePI(), System.Xml.DtdParser.ParsePIAsync(), System.Xml.DtdParser.ReadData(), System.Xml.DtdParser.ReadDataAsync(), System.Xml.DtdParser.ScanLiteral(), and System.Xml.DtdParser.ScanLiteralAsync().