Terraria: System.Xml.DtdParser.GetTokenAsync
GetTokenAsync()
async Task< Token > System.Xml.DtdParser.GetTokenAsync (bool needWhiteSpace) inline private
Definition at line 4133 of file DtdParser.cs.
    {
        _whitespaceSeen = false;
        while (true)
        {
            switch (_chars[_curPos])
            {
            case '\0':
                if (_curPos != _charsUsed)
                {
                    ThrowInvalidChar(_chars, _charsUsed, _curPos);
                }
                break;
            case '\n':
                _whitespaceSeen = true;
                _curPos++;
                _readerAdapter.OnNewLine(_curPos);
                continue;
            case '\r':
                _whitespaceSeen = true;
                if (_chars[_curPos + 1] == '\n')
                {
                    if (Normalize)
                    {
                        SaveParsingBuffer();
                        _readerAdapter.CurrentPosition++;
                    }
                    _curPos += 2;
                }
                else
                {
                    if (_curPos + 1 >= _charsUsed && !_readerAdapter.IsEof)
                    {
                        break;
                    }
                    _chars[_curPos] = '\n';
                    _curPos++;
                }
                _readerAdapter.OnNewLine(_curPos);
                continue;
            case '\t':
            case ' ':
                _whitespaceSeen = true;
                _curPos++;
                continue;
            case '%':
                if (_charsUsed - _curPos < 2)
                {
                    break;
                }
                if (!XmlCharType.IsWhiteSpace(_chars[_curPos + 1]))
                {
                    if (IgnoreEntityReferences)
                    {
                        _curPos++;
                    }
                    else
                    {
                        await HandleEntityReferenceAsync(paramEntity: true, inLiteral: false, inAttribute: false).ConfigureAwait(continueOnCapturedContext: false);
                    }
                    continue;
                }
                goto default;
            default:
                if (needWhiteSpace && !_whitespaceSeen && _scanningFunction != ScanningFunction.ParamEntitySpace)
                {
                    Throw(_curPos, System.SR.Xml_ExpectingWhiteSpace, ParseUnexpectedToken(_curPos));
                }
                _tokenStartPos = _curPos;
                while (true)
                {
                    switch (_scanningFunction)
                    {
                    case ScanningFunction.Name:
                        return await ScanNameExpectedAsync().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.QName:
                        return await ScanQNameExpectedAsync().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Nmtoken:
                        return await ScanNmtokenExpectedAsync().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.SubsetContent:
                        return await ScanSubsetContentAsync().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Doctype1:
                        return await ScanDoctype1Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Doctype2:
                        return ScanDoctype2();
                    case ScanningFunction.Element1:
                        return await ScanElement1Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Element2:
                        return await ScanElement2Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Element3:
                        return await ScanElement3Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Element4:
                        return ScanElement4();
                    case ScanningFunction.Element5:
                        return ScanElement5();
                    case ScanningFunction.Element6:
                        return ScanElement6();
                    case ScanningFunction.Element7:
                        return ScanElement7();
                    case ScanningFunction.Attlist1:
                        return await ScanAttlist1Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Attlist2:
                        return await ScanAttlist2Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Attlist3:
                        return ScanAttlist3();
                    case ScanningFunction.Attlist4:
                        return ScanAttlist4();
                    case ScanningFunction.Attlist5:
                        return ScanAttlist5();
                    case ScanningFunction.Attlist6:
                        return await ScanAttlist6Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Attlist7:
                        return ScanAttlist7();
                    case ScanningFunction.Notation1:
                        return await ScanNotation1Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.SystemId:
                        return await ScanSystemIdAsync().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.PublicId1:
                        return await ScanPublicId1Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.PublicId2:
                        return await ScanPublicId2Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Entity1:
                        return await ScanEntity1Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Entity2:
                        return await ScanEntity2Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.Entity3:
                        return await ScanEntity3Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.CondSection1:
                        return await ScanCondSection1Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.CondSection2:
                        return ScanCondSection2();
                    case ScanningFunction.CondSection3:
                        return await ScanCondSection3Async().ConfigureAwait(continueOnCapturedContext: false);
                    case ScanningFunction.ClosingTag:
                        return ScanClosingTag();
                    case ScanningFunction.ParamEntitySpace:
                        break;
                    default:
                        return Token.None;
                    }
                    _whitespaceSeen = true;
                    _scanningFunction = _savedScanningFunction;
                }
            }
            bool isEof = _readerAdapter.IsEof;
            bool flag = isEof;
            if (!flag)
            {
                flag = await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0;
            }
            if (flag && !HandleEntityEnd(inLiteral: false))
            {
                if (_scanningFunction == ScanningFunction.SubsetContent)
                {
                    break;
                }
                Throw(_curPos, System.SR.Xml_IncompleteDtdContent);
            }
        }
        return Token.Eof;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._savedScanningFunction, System.Xml.DtdParser._scanningFunction, System.Xml.DtdParser._tokenStartPos, System.Xml.DtdParser._whitespaceSeen, System.Xml.IDtdParserAdapter.CurrentPosition, System.Xml.Dictionary, System.Xml.DtdParser.HandleEntityEnd(), System.Xml.DtdParser.HandleEntityReferenceAsync(), System.Xml.DtdParser.IgnoreEntityReferences, System.Xml.IDtdParserAdapter.IsEof, System.Xml.XmlCharType.IsWhiteSpace(), System.Xml.DtdParser.Normalize, System.Xml.IDtdParserAdapter.OnNewLine(), System.Xml.DtdParser.ParseUnexpectedToken(), System.Xml.DtdParser.ReadDataAsync(), System.Xml.DtdParser.SaveParsingBuffer(), System.Xml.DtdParser.ScanAttlist1Async(), System.Xml.DtdParser.ScanAttlist2Async(), System.Xml.DtdParser.ScanAttlist3(), System.Xml.DtdParser.ScanAttlist4(), System.Xml.DtdParser.ScanAttlist5(), System.Xml.DtdParser.ScanAttlist6Async(), System.Xml.DtdParser.ScanAttlist7(), System.Xml.DtdParser.ScanClosingTag(), System.Xml.DtdParser.ScanCondSection1Async(), System.Xml.DtdParser.ScanCondSection2(), System.Xml.DtdParser.ScanCondSection3Async(), System.Xml.DtdParser.ScanDoctype1Async(), System.Xml.DtdParser.ScanDoctype2(), System.Xml.DtdParser.ScanElement1Async(), System.Xml.DtdParser.ScanElement2Async(), System.Xml.DtdParser.ScanElement3Async(), System.Xml.DtdParser.ScanElement4(), System.Xml.DtdParser.ScanElement5(), System.Xml.DtdParser.ScanElement6(), System.Xml.DtdParser.ScanElement7(), System.Xml.DtdParser.ScanEntity1Async(), System.Xml.DtdParser.ScanEntity2Async(), System.Xml.DtdParser.ScanEntity3Async(), System.Xml.DtdParser.ScanNameExpectedAsync(), System.Xml.DtdParser.ScanNmtokenExpectedAsync(), System.Xml.DtdParser.ScanNotation1Async(), System.Xml.DtdParser.ScanPublicId1Async(), System.Xml.DtdParser.ScanPublicId2Async(), System.Xml.DtdParser.ScanQNameExpectedAsync(), System.Xml.DtdParser.ScanSubsetContentAsync(), System.Xml.DtdParser.ScanSystemIdAsync(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowInvalidChar(), System.SR.Xml_ExpectingWhiteSpace, and System.SR.Xml_IncompleteDtdContent.
Referenced by System.Xml.DtdParser.ParseAttlistDeclAsync(), System.Xml.DtdParser.ParseAttlistDefaultAsync(), System.Xml.DtdParser.ParseAttlistTypeAsync(), System.Xml.DtdParser.ParseCondSectionAsync(), System.Xml.DtdParser.ParseElementDeclAsync(), System.Xml.DtdParser.ParseElementMixedContentAsync(), System.Xml.DtdParser.ParseElementOnlyContentAsync(), System.Xml.DtdParser.ParseEntityDeclAsync(), System.Xml.DtdParser.ParseExternalIdAsync(), System.Xml.DtdParser.ParseHowManyAsync(), System.Xml.DtdParser.ParseInDocumentDtdAsync(), System.Xml.DtdParser.ParseNotationDeclAsync(), and System.Xml.DtdParser.ParseSubsetAsync().