Terraria: System.Xml.DtdParser.ParseFreeFloatingDtdAsync
ParseFreeFloatingDtdAsync() [1/2]
async Task System.Xml.DtdParser.ParseFreeFloatingDtdAsync () inline private
Definition at line 3243 of file DtdParser.cs.
    {
        if (_hasFreeFloatingInternalSubset)
        {
            LoadParsingBuffer();
            await ParseInternalSubsetAsync().ConfigureAwait(continueOnCapturedContext: false);
            SaveParsingBuffer();
        }
        if (_systemId != null && _systemId.Length > 0)
        {
            await ParseExternalSubsetAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Xml.DtdParser._hasFreeFloatingInternalSubset, System.Xml.DtdParser._systemId, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.DtdParser.ParseExternalSubsetAsync(), System.Xml.DtdParser.ParseInternalSubsetAsync(), and System.Xml.DtdParser.SaveParsingBuffer().
Referenced by System.Xml.DtdParser.ParseAsync().