Terraria: System.Security.Cryptography.CngPkcs8.ExportEncryptedPkcs8PrivateKey
ExportEncryptedPkcs8PrivateKey() [2/4]
static byte[] System.Security.Cryptography.CngPkcs8.ExportEncryptedPkcs8PrivateKey (AsymmetricAlgorithm key, ReadOnlySpan< byte > passwordBytes, PbeParameters pbeParameters) inline static package
Definition at line 54 of file CngPkcs8.cs.
    {
        if (pbeParameters == null)
        {
            throw new ArgumentNullException("pbeParameters");
        }
        System.Security.Cryptography.PasswordBasedEncryption.ValidatePbeParameters(pbeParameters, ReadOnlySpan<char>.Empty, passwordBytes);
        if (passwordBytes.Length == 0)
        {
            return key.ExportEncryptedPkcs8PrivateKey(ReadOnlySpan<char>.Empty, pbeParameters);
        }
        AsnWriter asnWriter = RewriteEncryptedPkcs8PrivateKey(key, passwordBytes, pbeParameters);
        return asnWriter.Encode();
    }
References System.Formats.Asn1.AsnWriter.Encode(), System.key, System.ReadOnlySpan< T >.Length, System.Security.Cryptography.CngPkcs8.RewriteEncryptedPkcs8PrivateKey(), and System.Security.Cryptography.PasswordBasedEncryption.ValidatePbeParameters().