Terraria: System.Xml.DtdParser.ParseElementDecl
ParseElementDecl()
void System.Xml.DtdParser.ParseElementDecl () inline private
Definition at line 772 of file DtdParser.cs.
    {
        if (GetToken(needWhiteSpace: true) == Token.QName)
        {
            SchemaElementDecl value = null;
            XmlQualifiedName nameQualified = GetNameQualified(canHavePrefix: true);
            if (_schemaInfo.ElementDecls.TryGetValue(nameQualified, out value))
            {
                if (_validate)
                {
                    SendValidationEvent(_curPos - nameQualified.Name.Length, XmlSeverityType.Error, System.SR.Sch_DupElementDecl, GetNameString());
                }
            }
            else
            {
                if (_schemaInfo.UndeclaredElementDecls.TryGetValue(nameQualified, out value))
                {
                    _schemaInfo.UndeclaredElementDecls.Remove(nameQualified);
                }
                else
                {
                    value = new SchemaElementDecl(nameQualified, nameQualified.Namespace);
                }
                _schemaInfo.ElementDecls.Add(nameQualified, value);
            }
            value.IsDeclaredInExternal = !ParsingInternalSubset;
            Token token = GetToken(needWhiteSpace: true);
            if (token != Token.LeftParen)
            {
                if (token != Token.ANY)
                {
                    if (token != Token.EMPTY)
                    {
                        goto IL_0181;
                    }
                    value.ContentValidator = ContentValidator.Empty;
                }
                else
                {
                    value.ContentValidator = ContentValidator.Any;
                }
            }
            else
            {
                int currentEntityId = _currentEntityId;
                Token token2 = GetToken(needWhiteSpace: false);
                if (token2 != Token.None)
                {
                    if (token2 != Token.PCDATA)
                    {
                        goto IL_0181;
                    }
                    ParticleContentValidator particleContentValidator = new ParticleContentValidator(XmlSchemaContentType.Mixed);
                    particleContentValidator.Start();
                    particleContentValidator.OpenGroup();
                    ParseElementMixedContent(particleContentValidator, currentEntityId);
                    value.ContentValidator = particleContentValidator.Finish(useDFA: true);
                }
                else
                {
                    ParticleContentValidator particleContentValidator2 = null;
                    particleContentValidator2 = new ParticleContentValidator(XmlSchemaContentType.ElementOnly);
                    particleContentValidator2.Start();
                    particleContentValidator2.OpenGroup();
                    ParseElementOnlyContent(particleContentValidator2, currentEntityId);
                    value.ContentValidator = particleContentValidator2.Finish(useDFA: true);
                }
            }
            if (GetToken(needWhiteSpace: false) != Token.GreaterThan)
            {
                ThrowUnexpectedToken(_curPos, ">");
            }
            return;
        }
        goto IL_0181;
        IL_0181:
        OnUnexpectedError();
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._validate, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.ContentValidator.Any, System.Xml.Dictionary, System.Xml.Schema.SchemaInfo.ElementDecls, System.Xml.Schema.ContentValidator.Empty, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetNameString(), System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseElementMixedContent(), System.Xml.DtdParser.ParseElementOnlyContent(), System.Xml.DtdParser.ParsingInternalSubset, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.SR.Sch_DupElementDecl, System.Xml.DtdParser.SendValidationEvent(), System.Xml.DtdParser.ThrowUnexpectedToken(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Xml.Schema.SchemaInfo.UndeclaredElementDecls, and System.value.
Referenced by System.Xml.DtdParser.ParseSubset().