Terraria: System.Security.Cryptography.CngPkcs8.RewriteEncryptedPkcs8PrivateKey
RewriteEncryptedPkcs8PrivateKey() [4/4]
static AsnWriter System.Security.Cryptography.CngPkcs8.RewriteEncryptedPkcs8PrivateKey (AsymmetricAlgorithm key, ReadOnlySpan< char > password, PbeParameters pbeParameters) inline static private
Definition at line 258 of file CngPkcs8.cs.
    {
        byte[] array = System.Security.Cryptography.CryptoPool.Rent(key.KeySize);
        int bytesWritten = 0;
        try
        {
            while (!key.TryExportEncryptedPkcs8PrivateKey(password, s_platformParameters, array, out bytesWritten))
            {
                int num = array.Length;
                byte[] array2 = array;
                array = System.Security.Cryptography.CryptoPool.Rent(checked(num * 2));
                System.Security.Cryptography.CryptoPool.Return(array2, bytesWritten);
            }
            return System.Security.Cryptography.KeyFormatHelper.ReencryptPkcs8(password, array.AsMemory(0, bytesWritten), password, pbeParameters);
        }
        finally
        {
            System.Security.Cryptography.CryptoPool.Return(array, bytesWritten);
        }
    }
References System.array, System.key, System.Security.Cryptography.KeyFormatHelper.ReencryptPkcs8(), System.Security.Cryptography.CryptoPool.Rent(), System.Security.Cryptography.CryptoPool.Return(), and System.Security.Cryptography.CngPkcs8.s_platformParameters.