Terraria: System.Xml.DtdParser.ReadData
ReadData()
int System.Xml.DtdParser.ReadData () inline private
Definition at line 2842 of file DtdParser.cs.
    {
        SaveParsingBuffer();
        int result = _readerAdapter.ReadData();
        LoadParsingBuffer();
        return result;
    }
References System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.IDtdParserAdapter.ReadData(), and System.Xml.DtdParser.SaveParsingBuffer().
Referenced by System.Xml.DtdParser.EatPublicKeyword(), System.Xml.DtdParser.EatSystemKeyword(), System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.ReadDataInName(), System.Xml.DtdParser.ScanAttlist2(), System.Xml.DtdParser.ScanAttlist6(), System.Xml.DtdParser.ScanCondSection1(), System.Xml.DtdParser.ScanCondSection3(), System.Xml.DtdParser.ScanElement1(), System.Xml.DtdParser.ScanElement2(), System.Xml.DtdParser.ScanEntity3(), System.Xml.DtdParser.ScanLiteral(), System.Xml.DtdParser.ScanNmtoken(), and System.Xml.DtdParser.ScanSubsetContent().