Terraria: System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey
ImportPkcs8PrivateKey() [2/2]
static Pkcs8Response System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey (ReadOnlySpan< byte > source, out int bytesRead) inline static package
Definition at line 91 of file CngPkcs8.cs.
    {
        int bytesConsumed;
        try
        {
            AsnDecoder.ReadEncodedValue(source, AsnEncodingRules.BER, out var _, out var _, out bytesConsumed);
        }
        catch (AsnContentException inner)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner);
        }
        bytesRead = bytesConsumed;
        ReadOnlySpan<byte> readOnlySpan = source.Slice(0, bytesConsumed);
        try
        {
            return ImportPkcs8(readOnlySpan);
        }
        catch (CryptographicException)
        {
            AsnWriter asnWriter = RewritePkcs8ECPrivateKeyWithZeroPublicKey(readOnlySpan);
            if (asnWriter == null)
            {
                throw;
            }
            return ImportPkcs8(asnWriter);
        }
        catch (AsnContentException inner2)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding, inner2);
        }
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.CngPkcs8.ImportPkcs8(), System.Formats.Asn1.AsnDecoder.ReadEncodedValue(), System.Security.Cryptography.CngPkcs8.RewritePkcs8ECPrivateKeyWithZeroPublicKey(), System.ReadOnlySpan< T >.Slice(), and System.source.