Terraria: System.Xml.DtdParser.ParseAsync
ParseAsync()
async Task System.Xml.DtdParser.ParseAsync (bool saveInternalSubset) inline private
Definition at line 3178 of file DtdParser.cs.
    {
        if (!_freeFloatingDtd)
        {
            await ParseInDocumentDtdAsync(saveInternalSubset).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            await ParseFreeFloatingDtdAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        _schemaInfo.Finish();
        if (!_validate || _undeclaredNotations == null)
        {
            return;
        }
        foreach (UndeclaredNotation value in _undeclaredNotations.Values)
        {
            for (UndeclaredNotation undeclaredNotation = value; undeclaredNotation != null; undeclaredNotation = undeclaredNotation.next)
            {
                SendValidationEvent(XmlSeverityType.Error, new XmlSchemaException(System.SR.Sch_UndeclaredNotation, value.name, BaseUriStr, value.lineNo, value.linePos));
            }
        }
    }
References System.Xml.DtdParser._freeFloatingDtd, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._undeclaredNotations, System.Xml.DtdParser._validate, System.Xml.DtdParser.BaseUriStr, System.Xml.Schema.SchemaInfo.Finish(), System.Xml.DtdParser.ParseFreeFloatingDtdAsync(), System.Xml.DtdParser.ParseInDocumentDtdAsync(), System.SR.Sch_UndeclaredNotation, System.Xml.DtdParser.SendValidationEvent(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.DtdParser.ParseFreeFloatingDtdAsync(), and System.Xml.DtdParser.ParseInternalDtdAsync().