Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetProperties
ReflectGetProperties()
static PropertyDescriptor[] System.ComponentModel.ReflectTypeDescriptionProvider.ReflectGetProperties ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type) inline static private
Definition at line 1116 of file ReflectTypeDescriptionProvider.cs.
    {
        Hashtable propertyCache = PropertyCache;
        PropertyDescriptor[] array = (PropertyDescriptor[])propertyCache[type];
        if (array != null)
        {
            return array;
        }
        lock (s_internalSyncObject)
        {
            array = (PropertyDescriptor[])propertyCache[type];
            if (array == null)
            {
                BindingFlags bindingAttr = BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public;
                PropertyInfo[] properties = type.GetProperties(bindingAttr);
                array = new PropertyDescriptor[properties.Length];
                int num = 0;
                foreach (PropertyInfo propertyInfo in properties)
                {
                    if (propertyInfo.GetIndexParameters().Length == 0)
                    {
                        MethodInfo getMethod = propertyInfo.GetGetMethod(nonPublic: false);
                        MethodInfo setMethod = propertyInfo.GetSetMethod(nonPublic: false);
                        string name = propertyInfo.Name;
                        if (getMethod != null)
{
                            array[num++] = new ReflectPropertyDescriptor(type, name, propertyInfo.PropertyType, propertyInfo, getMethod, setMethod, null);
                        }
                    }
                }
                if (num != array.Length)
                {
                    PropertyDescriptor[] array2 = new PropertyDescriptor[num];
                    Array.Copy(array, array2, num);
                    array = array2;
                }
                propertyCache[type] = array;
            }
        }
        return array;
    }
References System.array, System.Array.Copy(), System.Reflection.PropertyInfo.GetGetMethod(), System.Reflection.PropertyInfo.GetIndexParameters(), System.Reflection.PropertyInfo.GetSetMethod(), System.Reflection.MemberInfo.Name, System.ComponentModel.ReflectTypeDescriptionProvider.PropertyCache, System.Reflection.PropertyInfo.PropertyType, System.ComponentModel.ReflectTypeDescriptionProvider.s_internalSyncObject, and System.type.
Referenced by System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetProperties().