Terraria: System.Xml.DtdParser.ParseCondSectionAsync
ParseCondSectionAsync()
async Task System.Xml.DtdParser.ParseCondSectionAsync () inline private
Definition at line 4011 of file DtdParser.cs.
    {
        int csEntityId = _currentEntityId;
        switch (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false))
        {
        case Token.INCLUDE:
            if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) == Token.LeftBracket)
            {
                if (_validate && csEntityId != _currentEntityId)
                {
                    SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                }
                if (_validate)
                {
                    if (_condSectionEntityIds == null)
                    {
                        _condSectionEntityIds = new int[2];
                    }
                    else if (_condSectionEntityIds.Length == _condSectionDepth)
                    {
                        int[] array = new int[_condSectionEntityIds.Length * 2];
                        Array.Copy(_condSectionEntityIds, array, _condSectionEntityIds.Length);
                        _condSectionEntityIds = array;
                    }
                    _condSectionEntityIds[_condSectionDepth] = csEntityId;
                }
                _condSectionDepth++;
                break;
            }
            goto default;
        case Token.IGNORE:
            if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) == Token.LeftBracket)
            {
                if (_validate && csEntityId != _currentEntityId)
                {
                    SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                }
                if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) == Token.CondSectionEnd)
                {
                    if (_validate && csEntityId != _currentEntityId)
                    {
                        SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                    }
                    break;
                }
            }
            goto default;
        default:
            OnUnexpectedError();
            break;
        }
    }
References System.Xml.DtdParser._condSectionDepth, System.Xml.DtdParser._condSectionEntityIds, System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._validate, System.array, System.Array.Copy(), System.Xml.Dictionary, System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.OnUnexpectedError(), System.SR.Sch_ParEntityRefNesting, and System.Xml.DtdParser.SendValidationEvent().
Referenced by System.Xml.DtdParser.ParseSubsetAsync().