Terraria: System.Xml.DtdParser.ScanAttlist6Async
ScanAttlist6Async()
async Task< Token > System.Xml.DtdParser.ScanAttlist6Async () inline private
Definition at line 4725 of file DtdParser.cs.
    {
        while (true)
        {
            switch (_chars[_curPos])
            {
            case '"':
            case '\'':
                await ScanLiteralAsync(LiteralType.AttributeValue).ConfigureAwait(continueOnCapturedContext: false);
                _scanningFunction = ScanningFunction.Attlist1;
                return Token.Literal;
            case '#':
                if (_charsUsed - _curPos < 6)
                {
                    break;
                }
                switch (_chars[_curPos + 1])
                {
                case 'R':
                    if (_charsUsed - _curPos >= 9)
                    {
                        if (_chars[_curPos + 2] != 'E' || _chars[_curPos + 3] != 'Q' || _chars[_curPos + 4] != 'U' || _chars[_curPos + 5] != 'I' || _chars[_curPos + 6] != 'R' || _chars[_curPos + 7] != 'E' || _chars[_curPos + 8] != 'D')
{
                            Throw(_curPos, System.SR.Xml_ExpectAttType);
                        }
                        _curPos += 9;
                        _scanningFunction = ScanningFunction.Attlist1;
                        return Token.REQUIRED;
                    }
                    break;
                case 'I':
                    if (_charsUsed - _curPos >= 8)
                    {
                        if (_chars[_curPos + 2] != 'M' || _chars[_curPos + 3] != 'P' || _chars[_curPos + 4] != 'L' || _chars[_curPos + 5] != 'I' || _chars[_curPos + 6] != 'E' || _chars[_curPos + 7] != 'D')
{
                            Throw(_curPos, System.SR.Xml_ExpectAttType);
                        }
                        _curPos += 8;
                        _scanningFunction = ScanningFunction.Attlist1;
                        return Token.IMPLIED;
                    }
                    break;
                case 'F':
                    if (_chars[_curPos + 2] != 'I' || _chars[_curPos + 3] != 'X' || _chars[_curPos + 4] != 'E' || _chars[_curPos + 5] != 'D')
                    {
                        Throw(_curPos, System.SR.Xml_ExpectAttType);
                    }
                    _curPos += 6;
                    _scanningFunction = ScanningFunction.Attlist7;
                    return Token.FIXED;
                default:
                    Throw(_curPos, System.SR.Xml_ExpectAttType);
                    break;
                }
                break;
            default:
                Throw(_curPos, System.SR.Xml_ExpectAttType);
                break;
            }
            if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
            {
                Throw(_curPos, System.SR.Xml_IncompleteDtdContent);
            }
        }
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._scanningFunction, System.Xml.DtdParser.ReadDataAsync(), System.Xml.DtdParser.ScanLiteralAsync(), System.Xml.DtdParser.Throw(), System.SR.Xml_ExpectAttType, and System.SR.Xml_IncompleteDtdContent.
Referenced by System.Xml.DtdParser.GetTokenAsync().