Terraria: System.Xml.DtdParser.Initialize
Initialize()
void System.Xml.DtdParser.Initialize (IDtdParserAdapter readerAdapter) inline private
Definition at line 266 of file DtdParser.cs.
    {
        _readerAdapter = readerAdapter;
        _readerAdapterWithValidation = readerAdapter as IDtdParserAdapterWithValidation;
        _nameTable = readerAdapter.NameTable;
        if (readerAdapter is IDtdParserAdapterWithValidation dtdParserAdapterWithValidation)
        {
            _validate = dtdParserAdapterWithValidation.DtdValidation;
        }
        if (readerAdapter is IDtdParserAdapterV1 dtdParserAdapterV)
        {
            _v1Compat = dtdParserAdapterV.V1CompatibilityMode;
            _normalize = dtdParserAdapterV.Normalization;
            _supportNamespaces = dtdParserAdapterV.Namespaces;
        }
        _schemaInfo = new SchemaInfo();
        _schemaInfo.SchemaType = SchemaType.DTD;
        _stringBuilder = new StringBuilder();
        Uri baseUri = readerAdapter.BaseUri;
        if (baseUri != null)
        {
            _documentBaseUri = baseUri.ToString();
        }
        _freeFloatingDtd = false;
    }
References System.Xml.DtdParser._documentBaseUri, System.Xml.DtdParser._freeFloatingDtd, System.Xml.DtdParser._nameTable, System.Xml.DtdParser._normalize, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._readerAdapterWithValidation, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._stringBuilder, System.Xml.DtdParser._supportNamespaces, System.Xml.DtdParser._v1Compat, System.Xml.DtdParser._validate, System.Xml.Dictionary, and System.Uri.ToString().
Referenced by System.Xml.DtdParser.InitializeFreeFloatingDtd(), System.Xml.DtdParser.ParseInternalDtd(), and System.Xml.DtdParser.ParseInternalDtdAsync().