Terraria: System.Xml.DtdParser.ParseInDocumentDtd
ParseInDocumentDtd()
void System.Xml.DtdParser.ParseInDocumentDtd (bool saveInternalSubset) inline private
Definition at line 378 of file DtdParser.cs.
    {
        LoadParsingBuffer();
        _scanningFunction = ScanningFunction.QName;
        _nextScaningFunction = ScanningFunction.Doctype1;
        if (GetToken(needWhiteSpace: false) != Token.QName)
        {
            OnUnexpectedError();
        }
        _schemaInfo.DocTypeName = GetNameQualified(canHavePrefix: true);
        Token token = GetToken(needWhiteSpace: false);
        if (token == Token.SYSTEM || token == Token.PUBLIC)
        {
            ParseExternalId(token, Token.DOCTYPE, out _publicId, out _systemId);
            token = GetToken(needWhiteSpace: false);
        }
        switch (token)
        {
        case Token.LeftBracket:
            if (saveInternalSubset)
            {
                SaveParsingBuffer();
                _internalSubsetValueSb = new StringBuilder();
            }
            ParseInternalSubset();
            break;
        default:
            OnUnexpectedError();
            break;
        case Token.GreaterThan:
            break;
        }
        SaveParsingBuffer();
        if (_systemId != null && _systemId.Length > 0)
        {
            ParseExternalSubset();
        }
    }
References System.Xml.DtdParser._internalSubsetValueSb, System.Xml.DtdParser._nextScaningFunction, System.Xml.DtdParser._publicId, System.Xml.DtdParser._scanningFunction, System.Xml.DtdParser._systemId, System.Xml.Dictionary, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseExternalId(), System.Xml.DtdParser.ParseExternalSubset(), System.Xml.DtdParser.ParseInternalSubset(), and System.Xml.DtdParser.SaveParsingBuffer().
Referenced by System.Xml.DtdParser.Parse().