Terraria: System.Xml.DtdParser.SaveParsingBuffer
SaveParsingBuffer() [1/2]
void System.Xml.DtdParser.SaveParsingBuffer () inline private
Definition at line 2857 of file DtdParser.cs.
    {
        SaveParsingBuffer(_curPos);
    }
References System.Xml.DtdParser._curPos, and System.Xml.DtdParser.SaveParsingBuffer().
Referenced by System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.HandleEntityEnd(), System.Xml.DtdParser.HandleEntityReference(), System.Xml.DtdParser.HandleEntityReferenceAsync(), System.Xml.DtdParser.ParseComment(), System.Xml.DtdParser.ParseCommentAsync(), System.Xml.DtdParser.ParseFreeFloatingDtd(), System.Xml.DtdParser.ParseFreeFloatingDtdAsync(), System.Xml.DtdParser.ParseInDocumentDtd(), System.Xml.DtdParser.ParseInDocumentDtdAsync(), System.Xml.DtdParser.ParsePI(), System.Xml.DtdParser.ParsePIAsync(), System.Xml.DtdParser.ParseSubset(), System.Xml.DtdParser.ParseSubsetAsync(), System.Xml.DtdParser.ReadData(), System.Xml.DtdParser.ReadDataAsync(), System.Xml.DtdParser.SaveParsingBuffer(), System.Xml.DtdParser.ScanLiteral(), and System.Xml.DtdParser.ScanLiteralAsync().