Terraria: System.Xml.DtdParser.ScanEntityName
ScanEntityName()
XmlQualifiedName System.Xml.DtdParser.ScanEntityName () inline private
Definition at line 2340 of file DtdParser.cs.
    {
        try
        {
            ScanName();
        }
        catch (XmlException ex)
        {
            Throw(System.SR.Xml_ErrorParsingEntityName, string.Empty, ex.LineNumber, ex.LinePosition);
        }
        if (_chars[_curPos] != ';')
        {
            ThrowUnexpectedToken(_curPos, ";");
        }
        XmlQualifiedName nameQualified = GetNameQualified(canHavePrefix: false);
        _curPos++;
        return nameQualified;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._curPos, System.Xml.Dictionary, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.ScanName(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowUnexpectedToken(), and System.SR.Xml_ErrorParsingEntityName.
Referenced by System.Xml.DtdParser.HandleEntityReference(), System.Xml.DtdParser.HandleEntityReferenceAsync(), System.Xml.DtdParser.ScanLiteral(), and System.Xml.DtdParser.ScanLiteralAsync().