Terraria: System.Xml.DtdParser.ParseElementOnlyContent
ParseElementOnlyContent()
void System.Xml.DtdParser.ParseElementOnlyContent (ParticleContentValidator pcv, int startParenEntityId) inline private
Definition at line 851 of file DtdParser.cs.
    {
        Stack<ParseElementOnlyContent_LocalFrame> stack = new Stack<ParseElementOnlyContent_LocalFrame>();
        ParseElementOnlyContent_LocalFrame parseElementOnlyContent_LocalFrame = new ParseElementOnlyContent_LocalFrame(startParenEntityId);
        stack.Push(parseElementOnlyContent_LocalFrame);
        while (true)
        {
            Token token = GetToken(needWhiteSpace: false);
            if (token != Token.QName)
            {
                if (token != Token.LeftParen)
                {
                    if (token != Token.GreaterThan)
                    {
                        goto IL_0148;
                    }
                    Throw(_curPos, System.SR.Xml_InvalidContentModel);
                    goto IL_014e;
                }
                pcv.OpenGroup();
                parseElementOnlyContent_LocalFrame = new ParseElementOnlyContent_LocalFrame(_currentEntityId);
                stack.Push(parseElementOnlyContent_LocalFrame);
                continue;
            }
            pcv.AddName(GetNameQualified(canHavePrefix: true), null);
            ParseHowMany(pcv);
            goto IL_0078;
            IL_0148:
            OnUnexpectedError();
            goto IL_014e;
            IL_00f9:
            pcv.CloseGroup();
            if (_validate && _currentEntityId != parseElementOnlyContent_LocalFrame.startParenEntityId)
            {
                SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
            }
            ParseHowMany(pcv);
            goto IL_014e;
            IL_00cb:
            if (parseElementOnlyContent_LocalFrame.parsingSchema == Token.Comma)
            {
                Throw(_curPos, System.SR.Xml_InvalidContentModel);
            }
            pcv.AddChoice();
            parseElementOnlyContent_LocalFrame.parsingSchema = Token.Or;
            continue;
            IL_014e:
            stack.Pop();
            if (stack.Count > 0)
            {
                parseElementOnlyContent_LocalFrame = stack.Peek();
                goto IL_0078;
            }
            break;
            IL_0135:
            Throw(_curPos, System.SR.Xml_InvalidContentModel);
            goto IL_014e;
            IL_0078:
            switch (GetToken(needWhiteSpace: false))
            {
            case Token.Comma:
                break;
            case Token.Or:
                goto IL_00cb;
            case Token.RightParen:
                goto IL_00f9;
            case Token.GreaterThan:
                goto IL_0135;
            default:
                goto IL_0148;
            }
            if (parseElementOnlyContent_LocalFrame.parsingSchema == Token.Or)
            {
                Throw(_curPos, System.SR.Xml_InvalidContentModel);
            }
            pcv.AddSequence();
            parseElementOnlyContent_LocalFrame.parsingSchema = Token.Comma;
        }
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._validate, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseHowMany(), System.SR.Sch_ParEntityRefNesting, System.Xml.DtdParser.SendValidationEvent(), System.Xml.DtdParser.Throw(), and System.SR.Xml_InvalidContentModel.
Referenced by System.Xml.DtdParser.ParseElementDecl().