Terraria: System.Xml.DtdParser.ScanCondSection3Async
ScanCondSection3Async()
async Task< Token > System.Xml.DtdParser.ScanCondSection3Async () inline private
Definition at line 5169 of file DtdParser.cs.
    {
        int ignoreSectionDepth = 0;
        while (true)
        {
            if (XmlCharType.IsTextChar(_chars[_curPos]) && _chars[_curPos] != ']')
            {
                _curPos++;
                continue;
            }
            switch (_chars[_curPos])
            {
            case '\t':
            case '"':
            case '&':
            case '\'':
                _curPos++;
                continue;
            case '\n':
                _curPos++;
                _readerAdapter.OnNewLine(_curPos);
                continue;
            case '\r':
                if (_chars[_curPos + 1] == '\n')
                {
                    _curPos += 2;
                }
                else
                {
                    if (_curPos + 1 >= _charsUsed && !_readerAdapter.IsEof)
                    {
                        break;
                    }
                    _curPos++;
                }
                _readerAdapter.OnNewLine(_curPos);
                continue;
            case '<':
                if (_charsUsed - _curPos >= 3)
                {
                    if (_chars[_curPos + 1] != '!' || _chars[_curPos + 2] != '[')
                    {
                        _curPos++;
                        continue;
                    }
                    ignoreSectionDepth++;
                    _curPos += 3;
                    continue;
                }
                break;
            case ']':
                if (_charsUsed - _curPos < 3)
                {
                    break;
                }
                if (_chars[_curPos + 1] != ']' || _chars[_curPos + 2] != '>')
                {
                    _curPos++;
                    continue;
                }
                if (ignoreSectionDepth > 0)
                {
                    ignoreSectionDepth--;
                    _curPos += 3;
                    continue;
                }
                _curPos += 3;
                _scanningFunction = ScanningFunction.SubsetContent;
                return Token.CondSectionEnd;
            default:
            {
                if (_curPos == _charsUsed)
                {
                    break;
                }
                char ch = _chars[_curPos];
                if (XmlCharType.IsHighSurrogate(ch))
                {
                    if (_curPos + 1 == _charsUsed)
                    {
                        break;
                    }
                    _curPos++;
                    if (XmlCharType.IsLowSurrogate(_chars[_curPos]))
                    {
                        _curPos++;
                        continue;
                    }
                }
                ThrowInvalidChar(_chars, _charsUsed, _curPos);
                return Token.None;
            }
            }
            bool isEof = _readerAdapter.IsEof;
            bool flag = isEof;
            if (!flag)
            {
                flag = await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0;
            }
            if (flag)
            {
                if (HandleEntityEnd(inLiteral: false))
                {
                    continue;
                }
                Throw(_curPos, System.SR.Xml_UnclosedConditionalSection);
            }
            _tokenStartPos = _curPos;
        }
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._scanningFunction, System.Xml.DtdParser._tokenStartPos, System.ch, System.Xml.DtdParser.HandleEntityEnd(), System.Xml.IDtdParserAdapter.IsEof, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.IsTextChar(), System.Xml.IDtdParserAdapter.OnNewLine(), System.Xml.DtdParser.ReadDataAsync(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowInvalidChar(), and System.SR.Xml_UnclosedConditionalSection.
Referenced by System.Xml.DtdParser.GetTokenAsync().