Terraria: System.Xml.DtdParser.ScanAttlist2Async
ScanAttlist2Async()
async Task< Token > System.Xml.DtdParser.ScanAttlist2Async () inline private
Definition at line 4609 of file DtdParser.cs.
    {
        while (true)
        {
            switch (_chars[_curPos])
            {
            case '(':
                _curPos++;
                _scanningFunction = ScanningFunction.Nmtoken;
                _nextScaningFunction = ScanningFunction.Attlist5;
                return Token.LeftParen;
            case 'C':
                if (_charsUsed - _curPos >= 5)
                {
                    if (_chars[_curPos + 1] != 'D' || _chars[_curPos + 2] != 'A' || _chars[_curPos + 3] != 'T' || _chars[_curPos + 4] != 'A')
                    {
                        Throw(_curPos, System.SR.Xml_InvalidAttributeType1);
                    }
                    _curPos += 5;
                    _scanningFunction = ScanningFunction.Attlist6;
                    return Token.CDATA;
                }
                break;
            case 'E':
                if (_charsUsed - _curPos < 9)
                {
                    break;
                }
                _scanningFunction = ScanningFunction.Attlist6;
                if (_chars[_curPos + 1] != 'N' || _chars[_curPos + 2] != 'T' || _chars[_curPos + 3] != 'I' || _chars[_curPos + 4] != 'T')
                {
                    Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                }
                switch (_chars[_curPos + 5])
                {
                case 'I':
                    if (_chars[_curPos + 6] != 'E' || _chars[_curPos + 7] != 'S')
                    {
                        Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                    }
                    _curPos += 8;
                    return Token.ENTITIES;
                case 'Y':
                    _curPos += 6;
                    return Token.ENTITY;
                }
                Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                break;
            case 'I':
                if (_charsUsed - _curPos >= 6)
                {
                    _scanningFunction = ScanningFunction.Attlist6;
                    if (_chars[_curPos + 1] != 'D')
                    {
                        Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                    }
                    if (_chars[_curPos + 2] != 'R')
                    {
                        _curPos += 2;
                        return Token.ID;
                    }
                    if (_chars[_curPos + 3] != 'E' || _chars[_curPos + 4] != 'F')
                    {
                        Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                    }
                    if (_chars[_curPos + 5] != 'S')
                    {
                        _curPos += 5;
                        return Token.IDREF;
                    }
                    _curPos += 6;
                    return Token.IDREFS;
                }
                break;
            case 'N':
                if (_charsUsed - _curPos < 8 && !_readerAdapter.IsEof)
                {
                    break;
                }
                switch (_chars[_curPos + 1])
                {
                case 'O':
                    if (_chars[_curPos + 2] != 'T' || _chars[_curPos + 3] != 'A' || _chars[_curPos + 4] != 'T' || _chars[_curPos + 5] != 'I' || _chars[_curPos + 6] != 'O' || _chars[_curPos + 7] != 'N')
                    {
                        Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                    }
                    _curPos += 8;
                    _scanningFunction = ScanningFunction.Attlist3;
                    return Token.NOTATION;
                case 'M':
                    if (_chars[_curPos + 2] != 'T' || _chars[_curPos + 3] != 'O' || _chars[_curPos + 4] != 'K' || _chars[_curPos + 5] != 'E' || _chars[_curPos + 6] != 'N')
                    {
                        Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                    }
                    _scanningFunction = ScanningFunction.Attlist6;
                    if (_chars[_curPos + 7] == 'S')
                    {
                        _curPos += 8;
                        return Token.NMTOKENS;
                    }
                    _curPos += 7;
                    return Token.NMTOKEN;
                }
                Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                break;
            default:
                Throw(_curPos, System.SR.Xml_InvalidAttributeType);
                break;
            }
            if (await ReadDataAsync().ConfigureAwait(continueOnCapturedContext: false) == 0)
            {
                Throw(_curPos, System.SR.Xml_IncompleteDtdContent);
            }
        }
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._nextScaningFunction, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._scanningFunction, System.Xml.IDtdParserAdapter.IsEof, System.Xml.DtdParser.ReadDataAsync(), System.Xml.DtdParser.Throw(), System.SR.Xml_IncompleteDtdContent, System.SR.Xml_InvalidAttributeType, and System.SR.Xml_InvalidAttributeType1.
Referenced by System.Xml.DtdParser.GetTokenAsync().