Terraria: System.Xml.DtdParser.ParseNotationDeclAsync
ParseNotationDeclAsync()
async Task System.Xml.DtdParser.ParseNotationDeclAsync () inline private
Definition at line 3929 of file DtdParser.cs.
    {
        if (await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false) != Token.Name)
        {
            OnUnexpectedError();
        }
        XmlQualifiedName nameQualified = GetNameQualified(canHavePrefix: false);
        SchemaNotation notation = null;
        if (!_schemaInfo.Notations.ContainsKey(nameQualified.Name))
        {
            if (_undeclaredNotations != null)
            {
                _undeclaredNotations.Remove(nameQualified.Name);
            }
            notation = new SchemaNotation(nameQualified);
            _schemaInfo.Notations.Add(notation.Name.Name, notation);
        }
        else if (_validate)
        {
            SendValidationEvent(_curPos - nameQualified.Name.Length, XmlSeverityType.Error, System.SR.Sch_DupNotation, nameQualified.Name);
        }
        Token token = await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false);
        if (token == Token.SYSTEM || token == Token.PUBLIC)
        {
            var (pubid, systemLiteral) = await ParseExternalIdAsync(token, Token.NOTATION).ConfigureAwait(continueOnCapturedContext: false);
            if (notation != null)
            {
                notation.SystemLiteral = systemLiteral;
                notation.Pubid = pubid;
            }
        }
        else
        {
            OnUnexpectedError();
        }
        if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) != Token.GreaterThan)
        {
            OnUnexpectedError();
        }
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._undeclaredNotations, System.Xml.DtdParser._validate, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Dictionary, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.Schema.SchemaInfo.Notations, System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseExternalIdAsync(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.SR.Sch_DupNotation, and System.Xml.DtdParser.SendValidationEvent().
Referenced by System.Xml.DtdParser.ParseSubsetAsync().