Terraria: System.Xml.DtdParser.ParseInternalSubsetAsync
ParseInternalSubsetAsync()
Task System.Xml.DtdParser.ParseInternalSubsetAsync () inline private
Definition at line 3257 of file DtdParser.cs.
    {
        return ParseSubsetAsync();
    }
References System.Xml.DtdParser.ParseSubsetAsync().
Referenced by System.Xml.DtdParser.ParseFreeFloatingDtdAsync(), and System.Xml.DtdParser.ParseInDocumentDtdAsync().