Terraria: System.Xml.DtdParser.HandleEntityReferenceAsync
HandleEntityReferenceAsync() [2/2]
async Task< bool > System.Xml.DtdParser.HandleEntityReferenceAsync (XmlQualifiedName entityName, bool paramEntity, bool inLiteral, bool inAttribute) inline private
Definition at line 5445 of file DtdParser.cs.
    {
        SaveParsingBuffer();
        if (paramEntity && ParsingInternalSubset && !ParsingTopLevelMarkup)
        {
            Throw(_curPos - entityName.Name.Length - 1, System.SR.Xml_InvalidParEntityRef);
        }
        SchemaEntity schemaEntity = VerifyEntityReference(entityName, paramEntity, mustBeDeclared: true, inAttribute);
        if (schemaEntity == null)
        {
            return false;
        }
        if (schemaEntity.ParsingInProgress)
        {
            Throw(_curPos - entityName.Name.Length - 1, paramEntity ? System.SR.Xml_RecursiveParEntity : System.SR.Xml_RecursiveGenEntity, entityName.Name);
        }
        int currentEntityId;
        if (schemaEntity.IsExternal)
        {
            (int, bool) tuple = await _readerAdapter.PushEntityAsync(schemaEntity).ConfigureAwait(continueOnCapturedContext: false);
            (currentEntityId, _) = tuple;
            if (!tuple.Item2)
            {
                return false;
            }
            _externalEntitiesDepth++;
        }
        else
        {
            if (schemaEntity.Text.Length == 0)
            {
                return false;
            }
            (int, bool) tuple3 = await _readerAdapter.PushEntityAsync(schemaEntity).ConfigureAwait(continueOnCapturedContext: false);
            (currentEntityId, _) = tuple3;
            if (!tuple3.Item2)
            {
                return false;
            }
        }
        _currentEntityId = currentEntityId;
        if (paramEntity && !inLiteral && _scanningFunction != ScanningFunction.ParamEntitySpace)
        {
            _savedScanningFunction = _scanningFunction;
            _scanningFunction = ScanningFunction.ParamEntitySpace;
        }
        LoadParsingBuffer();
        return true;
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._externalEntitiesDepth, System.Xml.DtdParser._readerAdapter, System.Xml.DtdParser._savedScanningFunction, System.Xml.DtdParser._scanningFunction, System.Xml.Dictionary, System.Xml.DtdParser.LoadParsingBuffer(), System.Xml.DtdParser.ParsingInternalSubset, System.Xml.DtdParser.ParsingTopLevelMarkup, System.Xml.IDtdParserAdapter.PushEntityAsync(), System.Xml.DtdParser.SaveParsingBuffer(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.VerifyEntityReference(), System.SR.Xml_InvalidParEntityRef, System.SR.Xml_RecursiveGenEntity, and System.SR.Xml_RecursiveParEntity.