Terraria: System.Xml.DtdParser.ScanNmtoken
ScanNmtoken()
void System.Xml.DtdParser.ScanNmtoken () inline private
Definition at line 2733 of file DtdParser.cs.
    {
        _tokenStartPos = _curPos;
        int num;
        while (true)
        {
            if (XmlCharType.IsNCNameSingleChar(_chars[_curPos]) || _chars[_curPos] == ':')
            {
                _curPos++;
                continue;
            }
            if (_curPos < _charsUsed)
            {
                if (_curPos - _tokenStartPos == 0)
                {
                    Throw(_curPos, System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(_chars, _charsUsed, _curPos));
                }
                return;
            }
            num = _curPos - _tokenStartPos;
            _curPos = _tokenStartPos;
            if (ReadData() == 0)
            {
                if (num > 0)
                {
                    break;
                }
                Throw(_curPos, System.SR.Xml_UnexpectedEOF, "NmToken");
            }
            _tokenStartPos = _curPos;
            _curPos += num;
        }
        _tokenStartPos = _curPos;
        _curPos += num;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._tokenStartPos, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlCharType.IsNCNameSingleChar(), System.Xml.DtdParser.ReadData(), System.Xml.DtdParser.Throw(), System.SR.Xml_BadNameChar, and System.SR.Xml_UnexpectedEOF.
Referenced by System.Xml.DtdParser.ScanNmtokenExpected().