Terraria: System.Xml.DtdParser.ThrowUnexpectedToken
ThrowUnexpectedToken() [1/2]
void System.Xml.DtdParser.ThrowUnexpectedToken (int pos, string expectedToken) inline private
Definition at line 3069 of file DtdParser.cs.
    {
        ThrowUnexpectedToken(pos, expectedToken, null);
    }
References System.Xml.DtdParser.ThrowUnexpectedToken().
Referenced by System.Xml.DtdParser.ParseElementDecl(), System.Xml.DtdParser.ParseElementDeclAsync(), System.Xml.DtdParser.ParseElementMixedContent(), System.Xml.DtdParser.ParseElementMixedContentAsync(), System.Xml.DtdParser.ParseEntityDecl(), System.Xml.DtdParser.ParseEntityDeclAsync(), System.Xml.DtdParser.ParseExternalId(), System.Xml.DtdParser.ParseExternalIdAsync(), System.Xml.DtdParser.ParseSubset(), System.Xml.DtdParser.ParseSubsetAsync(), System.Xml.DtdParser.ScanAttlist3(), System.Xml.DtdParser.ScanAttlist4(), System.Xml.DtdParser.ScanAttlist5(), System.Xml.DtdParser.ScanAttlist7(), System.Xml.DtdParser.ScanClosingTag(), System.Xml.DtdParser.ScanCondSection2(), System.Xml.DtdParser.ScanElement6(), System.Xml.DtdParser.ScanEntityName(), System.Xml.DtdParser.ScanPublicId1(), System.Xml.DtdParser.ScanPublicId1Async(), System.Xml.DtdParser.ScanSystemId(), System.Xml.DtdParser.ScanSystemIdAsync(), and System.Xml.DtdParser.ThrowUnexpectedToken().