Terraria: System.Xml.DtdParser.ParseAttlistDeclAsync
ParseAttlistDeclAsync()
async Task System.Xml.DtdParser.ParseAttlistDeclAsync () inline private
Definition at line 3373 of file DtdParser.cs.
    {
        if (await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false) == Token.QName)
        {
            XmlQualifiedName nameQualified = GetNameQualified(canHavePrefix: true);
            if (!_schemaInfo.ElementDecls.TryGetValue(nameQualified, out var elementDecl) && !_schemaInfo.UndeclaredElementDecls.TryGetValue(nameQualified, out elementDecl))
            {
                elementDecl = new SchemaElementDecl(nameQualified, nameQualified.Namespace);
                _schemaInfo.UndeclaredElementDecls.Add(nameQualified, elementDecl);
            }
            SchemaAttDef attrDef = null;
            while (true)
            {
                switch (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false))
                {
                case Token.QName:
                {
                    XmlQualifiedName nameQualified2 = GetNameQualified(canHavePrefix: true);
                    attrDef = new SchemaAttDef(nameQualified2, nameQualified2.Namespace)
                    {
                        IsDeclaredInExternal = !ParsingInternalSubset,
                        LineNumber = LineNo,
                        LinePosition = LinePos - (_curPos - _tokenStartPos)
                    };
                    bool attrDefAlreadyExists = elementDecl.GetAttDef(attrDef.Name) != null;
                    await ParseAttlistTypeAsync(attrDef, elementDecl, attrDefAlreadyExists).ConfigureAwait(continueOnCapturedContext: false);
                    await ParseAttlistDefaultAsync(attrDef, attrDefAlreadyExists).ConfigureAwait(continueOnCapturedContext: false);
                    if (attrDef.Prefix.Length > 0 && attrDef.Prefix.Equals("xml"))
                    {
                        if (attrDef.Name.Name == "space")
{
                            if (_v1Compat)
{
                                string text = attrDef.DefaultValueExpanded.Trim();
                                if (text.Equals("preserve") || text.Equals("default"))
{
                                    attrDef.Reserved = SchemaAttDef.Reserve.XmlSpace;
                                }
                            }
                            else
{
                                attrDef.Reserved = SchemaAttDef.Reserve.XmlSpace;
                                if (attrDef.TokenizedType != XmlTokenizedType.ENUMERATION)
{
                                    Throw(System.SR.Xml_EnumerationRequired, string.Empty, attrDef.LineNumber, attrDef.LinePosition);
                                }
                                if (_validate)
{
                                    attrDef.CheckXmlSpace(_readerAdapterWithValidation.ValidationEventHandling);
                                }
                            }
                        }
                        else if (attrDef.Name.Name == "lang")
{
                            attrDef.Reserved = SchemaAttDef.Reserve.XmlLang;
                        }
                    }
                    if (!attrDefAlreadyExists)
                    {
                        elementDecl.AddAttDef(attrDef);
                    }
                    continue;
                }
                case Token.GreaterThan:
                    if (_v1Compat && attrDef != null && attrDef.Prefix.Length > 0 && attrDef.Prefix.Equals("xml") && attrDef.Name.Name == "space")
                    {
                        attrDef.Reserved = SchemaAttDef.Reserve.XmlSpace;
                        if (attrDef.Datatype.TokenizedType != XmlTokenizedType.ENUMERATION)
{
                            Throw(System.SR.Xml_EnumerationRequired, string.Empty, attrDef.LineNumber, attrDef.LinePosition);
                        }
                        if (_validate)
{
                            attrDef.CheckXmlSpace(_readerAdapterWithValidation.ValidationEventHandling);
                        }
                    }
                    return;
                }
                break;
            }
        }
        OnUnexpectedError();
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._readerAdapterWithValidation, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._tokenStartPos, System.Xml.DtdParser._v1Compat, System.Xml.DtdParser._validate, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Schema.SchemaInfo.ElementDecls, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.LineNo, System.Xml.DtdParser.LinePos, System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseAttlistDefaultAsync(), System.Xml.DtdParser.ParseAttlistTypeAsync(), System.Xml.DtdParser.ParsingInternalSubset, System.text, System.Xml.DtdParser.Throw(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Xml.Schema.SchemaInfo.UndeclaredElementDecls, System.Xml.IDtdParserAdapterWithValidation.ValidationEventHandling, and System.SR.Xml_EnumerationRequired.
Referenced by System.Xml.DtdParser.ParseSubsetAsync().