Terraria: System.Xml.DtdParser.ParseElementMixedContentAsync
ParseElementMixedContentAsync()
async Task System.Xml.DtdParser.ParseElementMixedContentAsync (ParticleContentValidator pcv, int startParenEntityId) inline private
Definition at line 3774 of file DtdParser.cs.
    {
        bool hasNames = false;
        int connectorEntityId = -1;
        int contentEntityId = _currentEntityId;
        while (true)
        {
            switch (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false))
            {
            case Token.RightParen:
                pcv.CloseGroup();
                if (_validate && _currentEntityId != startParenEntityId)
                {
                    SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                }
                if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) == Token.Star && hasNames)
                {
                    pcv.AddStar();
                }
                else if (hasNames)
                {
                    ThrowUnexpectedToken(_curPos, "*");
                }
                return;
            case Token.Or:
            {
                if (!hasNames)
                {
                    hasNames = true;
                }
                else
                {
                    pcv.AddChoice();
                }
                if (_validate)
                {
                    connectorEntityId = _currentEntityId;
                    if (contentEntityId < connectorEntityId)
                    {
                        SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                    }
                }
                if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) != Token.QName)
                {
                    break;
                }
                XmlQualifiedName nameQualified = GetNameQualified(canHavePrefix: true);
                if (pcv.Exists(nameQualified) && _validate)
                {
                    SendValidationEvent(XmlSeverityType.Error, System.SR.Sch_DupElement, nameQualified.ToString());
                }
                pcv.AddName(nameQualified, null);
                if (_validate)
                {
                    contentEntityId = _currentEntityId;
                    if (contentEntityId < connectorEntityId)
                    {
                        SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
                    }
                }
                continue;
            }
            }
            OnUnexpectedError();
        }
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._validate, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.OnUnexpectedError(), System.SR.Sch_DupElement, System.SR.Sch_ParEntityRefNesting, System.Xml.DtdParser.SendValidationEvent(), and System.Xml.DtdParser.ThrowUnexpectedToken().
Referenced by System.Xml.DtdParser.ParseElementDeclAsync().