Terraria: Terraria.UI.ItemSorting.Sort
Sort()
static void Terraria.UI.ItemSorting.Sort (Item[] inv, params int[] ignoreSlots) inline static private
Definition at line 1060 of file ItemSorting.cs.
    {
        SetupSortingPriorities();
        List<int> list = new List<int>();
        for (int i = 0; i < inv.Length; i++)
        {
            if (!ignoreSlots.Contains(i))
            {
                Item item = inv[i];
                if (item != null && item.stack != 0 && item.type != 0 && !item.favorited)
                {
                    list.Add(i);
                }
            }
        }
        for (int j = 0; j < list.Count; j++)
        {
            Item item2 = inv[list[j]];
            if (item2.stack >= item2.maxStack)
            {
                continue;
            }
            int num = item2.maxStack - item2.stack;
            for (int k = j; k < list.Count; k++)
            {
                if (j == k)
                {
                    continue;
                }
                Item item3 = inv[list[k]];
                if (item2.type == item3.type && item3.stack != item3.maxStack)
                {
                    int num2 = item3.stack;
                    if (num < num2)
                    {
                        num2 = num;
                    }
                    item2.stack += num2;
                    item3.stack -= num2;
                    num -= num2;
                    if (item3.stack == 0)
                    {
                        inv[list[k]] = new Item();
                        list.Remove(list[k]);
                        j--;
                        k--;
                        break;
                    }
                    if (num == 0)
                    {
                        break;
                    }
                }
            }
        }
        List<int> list2 = new List<int>(list);
        for (int l = 0; l < inv.Length; l++)
        {
            if (!ignoreSlots.Contains(l) && !list2.Contains(l))
            {
                Item item4 = inv[l];
                if (item4 == null || item4.stack == 0 || item4.type == 0)
                {
                    list2.Add(l);
                }
            }
        }
        list2.Sort();
        List<int> list3 = new List<int>();
        List<int> list4 = new List<int>();
        foreach (ItemSortingLayer layer in _layerList)
        {
            List<int> list5 = layer.SortingMethod(layer, inv, list);
            if (list5.Count > 0)
            {
                list4.Add(list5.Count);
            }
            list3.AddRange(list5);
        }
        list3.AddRange(list);
        List<Item> list6 = new List<Item>();
        foreach (int item5 in list3)
        {
            list6.Add(inv[item5]);
            inv[item5] = new Item();
        }
        float num3 = 1f / (float)list4.Count;
        float num4 = num3 / 2f;
        for (int m = 0; m < list6.Count; m++)
        {
            int num5 = list2[0];
            ItemSlot.SetGlow(num5, num4, Main.player[Main.myPlayer].chest != -1);
            list4[0]--;
            if (list4[0] == 0)
            {
                list4.RemoveAt(0);
                num4 += num3;
            }
            inv[num5] = list6[m];
            list2.Remove(num5);
        }
    }
References Terraria.UI.ItemSorting._layerList, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.item, System.list, Terraria.Main.myPlayer, Terraria.Main.player, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), Terraria.UI.ItemSlot.SetGlow(), and Terraria.UI.ItemSorting.SetupSortingPriorities().
Referenced by Terraria.UI.ItemSorting.SortChest(), and Terraria.UI.ItemSorting.SortInventory().