Terraria: System.Xml.DtdParser.Throw
Throw() [1/4]
void System.Xml.DtdParser.Throw (int curPos, string res) inline private
Definition at line 3031 of file DtdParser.cs.
    {
        Throw(curPos, res, string.Empty);
    }
References System.Xml.DtdParser.Throw().
Referenced by System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.HandleEntityReference(), System.Xml.DtdParser.HandleEntityReferenceAsync(), System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseAttlistDecl(), System.Xml.DtdParser.ParseAttlistDeclAsync(), System.Xml.DtdParser.ParseElementOnlyContent(), System.Xml.DtdParser.ParseElementOnlyContentAsync(), System.Xml.DtdParser.ParseEntityDecl(), System.Xml.DtdParser.ParseEntityDeclAsync(), System.Xml.DtdParser.ParseExternalId(), System.Xml.DtdParser.ParseExternalIdAsync(), System.Xml.DtdParser.ParseSubset(), System.Xml.DtdParser.ParseSubsetAsync(), System.Xml.DtdParser.ScanAttlist1(), System.Xml.DtdParser.ScanAttlist1Async(), System.Xml.DtdParser.ScanAttlist2(), System.Xml.DtdParser.ScanAttlist2Async(), System.Xml.DtdParser.ScanAttlist6(), System.Xml.DtdParser.ScanAttlist6Async(), System.Xml.DtdParser.ScanCondSection1(), System.Xml.DtdParser.ScanCondSection1Async(), System.Xml.DtdParser.ScanCondSection3(), System.Xml.DtdParser.ScanCondSection3Async(), System.Xml.DtdParser.ScanDoctype1(), System.Xml.DtdParser.ScanDoctype1Async(), System.Xml.DtdParser.ScanDoctype2(), System.Xml.DtdParser.ScanElement1(), System.Xml.DtdParser.ScanElement1Async(), System.Xml.DtdParser.ScanElement2(), System.Xml.DtdParser.ScanElement2Async(), System.Xml.DtdParser.ScanElement4(), System.Xml.DtdParser.ScanElement5(), System.Xml.DtdParser.ScanEntity2(), System.Xml.DtdParser.ScanEntity2Async(), System.Xml.DtdParser.ScanEntityName(), System.Xml.DtdParser.ScanLiteral(), System.Xml.DtdParser.ScanLiteralAsync(), System.Xml.DtdParser.ScanNmtoken(), System.Xml.DtdParser.ScanNmtokenAsync(), System.Xml.DtdParser.ScanNotation1(), System.Xml.DtdParser.ScanNotation1Async(), System.Xml.DtdParser.ScanQName(), System.Xml.DtdParser.ScanQNameAsync(), System.Xml.DtdParser.ScanSubsetContent(), System.Xml.DtdParser.ScanSubsetContentAsync(), System.Xml.DtdParser.Throw(), System.Xml.DtdParser.ThrowInvalidChar(), System.Xml.DtdParser.ThrowInvalidChar(), System.Xml.DtdParser.ThrowUnexpectedToken(), and System.Xml.DtdParser.VerifyEntityReference().