Terraria: System.Xml.DtdParser.ParseUnexpectedToken
ParseUnexpectedToken()
string System.Xml.DtdParser.ParseUnexpectedToken (int startPos) inline private
Definition at line 3087 of file DtdParser.cs.
    {
        if (XmlCharType.IsNCNameSingleChar(_chars[startPos]))
        {
            int i;
            for (i = startPos; XmlCharType.IsNCNameSingleChar(_chars[i]); i++)
            {
            }
            int num = i - startPos;
            return new string(_chars, startPos, (num <= 0) ? 1 : num);
        }
        return new string(_chars, startPos, 1);
    }
References System.Xml.DtdParser._chars, System.Xml.Dictionary, and System.Xml.XmlCharType.IsNCNameSingleChar().
Referenced by System.Xml.DtdParser.GetToken(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.ScanAttlist1(), System.Xml.DtdParser.ScanAttlist1Async(), and System.Xml.DtdParser.ThrowUnexpectedToken().