Terraria: System.Xml.DtdParser.ScanDoctype1
ScanDoctype1()
Token System.Xml.DtdParser.ScanDoctype1 () inline private
Definition at line 1644 of file DtdParser.cs.
    {
        switch (_chars[_curPos])
        {
        case 'P':
            if (!EatPublicKeyword())
            {
                Throw(_curPos, System.SR.Xml_ExpectExternalOrClose);
            }
            _nextScaningFunction = ScanningFunction.Doctype2;
            _scanningFunction = ScanningFunction.PublicId1;
            return Token.PUBLIC;
        case 'S':
            if (!EatSystemKeyword())
            {
                Throw(_curPos, System.SR.Xml_ExpectExternalOrClose);
            }
            _nextScaningFunction = ScanningFunction.Doctype2;
            _scanningFunction = ScanningFunction.SystemId;
            return Token.SYSTEM;
        case '[':
            _curPos++;
            _scanningFunction = ScanningFunction.SubsetContent;
            return Token.LeftBracket;
        case '>':
            _curPos++;
            _scanningFunction = ScanningFunction.SubsetContent;
            return Token.GreaterThan;
        default:
            Throw(_curPos, System.SR.Xml_ExpectExternalOrClose);
            return Token.None;
        }
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._curPos, System.Xml.DtdParser._nextScaningFunction, System.Xml.DtdParser._scanningFunction, System.Xml.DtdParser.EatPublicKeyword(), System.Xml.DtdParser.EatSystemKeyword(), System.Xml.DtdParser.Throw(), and System.SR.Xml_ExpectExternalOrClose.
Referenced by System.Xml.DtdParser.GetToken().