Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.GetIntrinsicTypeEditor
GetIntrinsicTypeEditor()
static object System.ComponentModel.ReflectTypeDescriptionProvider.GetIntrinsicTypeEditor (Hashtable table, Type callingType) inline static private
Definition at line 1165 of file ReflectTypeDescriptionProvider.cs.
    {
        object obj = null;
        lock (table)
        {
            Type type = callingType;
            while (type != null && type != typeof(object))
            {
                obj = table[type];
                if (obj is string typeName)
                {
                    obj = Type.GetType(typeName);
                    if (obj != null)
                    {
                        table[type] = obj;
                    }
                }
                if (obj != null)
                {
                    break;
                }
                type = type.BaseType;
            }
            if (obj == null)
            {
                IDictionaryEnumerator enumerator = table.GetEnumerator();
                while (enumerator.MoveNext())
                {
                    DictionaryEntry entry = enumerator.Entry;
                    Type type2 = entry.Key as Type;
                    if (!(type2 != null) || !type2.IsInterface || !type2.IsAssignableFrom(callingType))
                    {
                        continue;
                    }
                    obj = entry.Value;
                    if (obj is string typeName2)
                    {
                        obj = Type.GetType(typeName2);
                        if (obj != null)
{
                            table[callingType] = obj;
                        }
                    }
                    if (obj != null)
                    {
                        break;
                    }
                }
            }
            if (obj == null)
            {
                if (callingType.IsGenericType && callingType.GetGenericTypeDefinition() == typeof(Nullable<>))
                {
                    obj = table[s_intrinsicNullableKey];
                }
                else if (callingType.IsInterface)
                {
                    obj = table[s_intrinsicReferenceKey];
                }
            }
            if (obj == null)
            {
                obj = table[typeof(object)];
            }
            Type type3 = obj as Type;
            if (type3 != null)
            {
                obj = CreateInstance(type3, callingType);
                if (type3.GetConstructor(s_typeConstructor) == null)
                {
                    table[callingType] = obj;
                }
            }
        }
        return obj;
    }
References System.Reflection.CreateInstance, System.Collections.Hashtable.GetEnumerator(), System.Type.GetType(), System.obj, System.ComponentModel.ReflectTypeDescriptionProvider.s_intrinsicNullableKey, System.ComponentModel.ReflectTypeDescriptionProvider.s_intrinsicReferenceKey, System.ComponentModel.ReflectTypeDescriptionProvider.s_typeConstructor, System.Reflection.Type, and System.type.
Referenced by System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetEditor().