Terraria: System.Xml.DtdParser.ParseElementDeclAsync
ParseElementDeclAsync()
async Task System.Xml.DtdParser.ParseElementDeclAsync () inline private
Definition at line 3600 of file DtdParser.cs.
    {
        if (await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false) == Token.QName)
        {
            SchemaElementDecl elementDecl = null;
            XmlQualifiedName nameQualified = GetNameQualified(canHavePrefix: true);
            if (_schemaInfo.ElementDecls.TryGetValue(nameQualified, out elementDecl))
            {
                if (_validate)
                {
                    SendValidationEvent(_curPos - nameQualified.Name.Length, XmlSeverityType.Error, System.SR.Sch_DupElementDecl, GetNameString());
                }
            }
            else
            {
                if (_schemaInfo.UndeclaredElementDecls.TryGetValue(nameQualified, out elementDecl))
                {
                    _schemaInfo.UndeclaredElementDecls.Remove(nameQualified);
                }
                else
                {
                    elementDecl = new SchemaElementDecl(nameQualified, nameQualified.Namespace);
                }
                _schemaInfo.ElementDecls.Add(nameQualified, elementDecl);
            }
            elementDecl.IsDeclaredInExternal = !ParsingInternalSubset;
            Token token = await GetTokenAsync(needWhiteSpace: true).ConfigureAwait(continueOnCapturedContext: false);
            if (token != Token.LeftParen)
            {
                if (token != Token.ANY)
                {
                    if (token != Token.EMPTY)
                    {
                        goto IL_0483;
                    }
                    elementDecl.ContentValidator = ContentValidator.Empty;
                }
                else
                {
                    elementDecl.ContentValidator = ContentValidator.Any;
                }
            }
            else
            {
                int startParenEntityId = _currentEntityId;
                Token token2 = await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false);
                if (token2 != Token.None)
                {
                    if (token2 != Token.PCDATA)
                    {
                        goto IL_0483;
                    }
                    ParticleContentValidator pcv = new ParticleContentValidator(XmlSchemaContentType.Mixed);
                    pcv.Start();
                    pcv.OpenGroup();
                    await ParseElementMixedContentAsync(pcv, startParenEntityId).ConfigureAwait(continueOnCapturedContext: false);
                    elementDecl.ContentValidator = pcv.Finish(useDFA: true);
                }
                else
                {
                    ParticleContentValidator pcv = new ParticleContentValidator(XmlSchemaContentType.ElementOnly);
                    pcv.Start();
                    pcv.OpenGroup();
                    await ParseElementOnlyContentAsync(pcv, startParenEntityId).ConfigureAwait(continueOnCapturedContext: false);
                    elementDecl.ContentValidator = pcv.Finish(useDFA: true);
                }
            }
            if (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false) != Token.GreaterThan)
            {
                ThrowUnexpectedToken(_curPos, ">");
            }
            return;
        }
        goto IL_0483;
        IL_0483:
        OnUnexpectedError();
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._schemaInfo, System.Xml.DtdParser._validate, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.ContentValidator.Any, System.Xml.Dictionary, System.Xml.Schema.SchemaInfo.ElementDecls, System.Xml.Schema.ContentValidator.Empty, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetNameString(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseElementMixedContentAsync(), System.Xml.DtdParser.ParseElementOnlyContentAsync(), System.Xml.DtdParser.ParsingInternalSubset, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.SR.Sch_DupElementDecl, System.Xml.DtdParser.SendValidationEvent(), System.Xml.DtdParser.ThrowUnexpectedToken(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.Xml.Schema.SchemaInfo.UndeclaredElementDecls.
Referenced by System.Xml.DtdParser.ParseSubsetAsync().