Terraria: System.Xml.DtdParser.ParseElementOnlyContentAsync
ParseElementOnlyContentAsync()
async Task System.Xml.DtdParser.ParseElementOnlyContentAsync (ParticleContentValidator pcv, int startParenEntityId) inline private
Definition at line 3678 of file DtdParser.cs.
    {
        Stack<ParseElementOnlyContent_LocalFrame> localFrames = new Stack<ParseElementOnlyContent_LocalFrame>();
        ParseElementOnlyContent_LocalFrame currentFrame = new ParseElementOnlyContent_LocalFrame(startParenEntityId);
        localFrames.Push(currentFrame);
        while (true)
        {
            Token token = await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false);
            if (token != Token.QName)
            {
                if (token != Token.LeftParen)
                {
                    if (token != Token.GreaterThan)
                    {
                        goto IL_036a;
                    }
                    Throw(_curPos, System.SR.Xml_InvalidContentModel);
                    goto IL_0370;
                }
                pcv.OpenGroup();
                currentFrame = new ParseElementOnlyContent_LocalFrame(_currentEntityId);
                localFrames.Push(currentFrame);
                continue;
            }
            pcv.AddName(GetNameQualified(canHavePrefix: true), null);
            await ParseHowManyAsync(pcv).ConfigureAwait(continueOnCapturedContext: false);
            goto IL_01a2;
            IL_036a:
            OnUnexpectedError();
            goto IL_0370;
            IL_02aa:
            pcv.CloseGroup();
            if (_validate && _currentEntityId != currentFrame.startParenEntityId)
            {
                SendValidationEvent(_curPos, XmlSeverityType.Error, System.SR.Sch_ParEntityRefNesting, string.Empty);
            }
            await ParseHowManyAsync(pcv).ConfigureAwait(continueOnCapturedContext: false);
            goto IL_0370;
            IL_026d:
            if (currentFrame.parsingSchema == Token.Comma)
            {
                Throw(_curPos, System.SR.Xml_InvalidContentModel);
            }
            pcv.AddChoice();
            currentFrame.parsingSchema = Token.Or;
            continue;
            IL_0370:
            localFrames.Pop();
            if (localFrames.Count > 0)
            {
                currentFrame = localFrames.Peek();
                goto IL_01a2;
            }
            break;
            IL_0357:
            Throw(_curPos, System.SR.Xml_InvalidContentModel);
            goto IL_0370;
            IL_01a2:
            switch (await GetTokenAsync(needWhiteSpace: false).ConfigureAwait(continueOnCapturedContext: false))
            {
            case Token.Comma:
                break;
            case Token.Or:
                goto IL_026d;
            case Token.RightParen:
                goto IL_02aa;
            case Token.GreaterThan:
                goto IL_0357;
            default:
                goto IL_036a;
            }
            if (currentFrame.parsingSchema == Token.Or)
            {
                Throw(_curPos, System.SR.Xml_InvalidContentModel);
            }
            pcv.AddSequence();
            currentFrame.parsingSchema = Token.Comma;
        }
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser._currentEntityId, System.Xml.DtdParser._validate, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.DtdParser.GetNameQualified(), System.Xml.DtdParser.GetTokenAsync(), System.Xml.DtdParser.OnUnexpectedError(), System.Xml.DtdParser.ParseHowManyAsync(), System.Xml.DtdParser.ParseElementOnlyContent_LocalFrame.parsingSchema, System.SR.Sch_ParEntityRefNesting, System.Xml.DtdParser.SendValidationEvent(), System.Xml.DtdParser.ParseElementOnlyContent_LocalFrame.startParenEntityId, System.Xml.DtdParser.Throw(), and System.SR.Xml_InvalidContentModel.
Referenced by System.Xml.DtdParser.ParseElementDeclAsync().