Terraria: System.Xml.DtdParser.ScanElement1
ScanElement1()
Token System.Xml.DtdParser.ScanElement1 () inline private
Definition at line 1707 of file DtdParser.cs.
    {
        while (true)
        {
            char c = _chars[_curPos];
            if (c != '(')
            {
                if (c != 'A')
                {
                    if (c == 'E')
                    {
                        if (_charsUsed - _curPos < 5)
{
                            goto IL_011b;
                        }
                        if (_chars[_curPos + 1] == 'M' && _chars[_curPos + 2] == 'P' && _chars[_curPos + 3] == 'T' && _chars[_curPos + 4] == 'Y')
{
                            _curPos += 5;
                            _scanningFunction = ScanningFunction.ClosingTag;
                            return Token.EMPTY;
                        }
                    }
                }
                else
                {
                    if (_charsUsed - _curPos < 3)
                    {
                        goto IL_011b;
                    }
                    if (_chars[_curPos + 1] == 'N' && _chars[_curPos + 2] == 'Y')
                    {
                        break;
                    }
                }
                Throw(_curPos, System.SR.Xml_InvalidContentModel);
                goto IL_011b;
            }
            _scanningFunction = ScanningFunction.Element2;
            _curPos++;
            return Token.LeftParen;
            IL_011b:
            if (ReadData() == 0)
            {
                Throw(_curPos, System.SR.Xml_IncompleteDtdContent);
            }
        }
        _curPos += 3;
        _scanningFunction = ScanningFunction.ClosingTag;
        return Token.ANY;
    }
References System.Xml.DtdParser._chars, System.Xml.DtdParser._charsUsed, System.Xml.DtdParser._curPos, System.Xml.DtdParser._scanningFunction, System.Xml.Dictionary, System.Xml.DtdParser.ReadData(), System.Xml.DtdParser.Throw(), System.SR.Xml_IncompleteDtdContent, and System.SR.Xml_InvalidContentModel.
Referenced by System.Xml.DtdParser.GetToken().