Terraria: System.ComponentModel.ReflectTypeDescriptionProvider.GetTypeData
GetTypeData()
ReflectedTypeData System.ComponentModel.ReflectTypeDescriptionProvider.GetTypeData ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type, bool createIfNeeded) inline private
Definition at line 924 of file ReflectTypeDescriptionProvider.cs.
    {
        ReflectedTypeData reflectedTypeData = null;
        if (_typeData != null)
        {
            reflectedTypeData = (ReflectedTypeData)_typeData[type];
            if (reflectedTypeData != null)
            {
                return reflectedTypeData;
            }
        }
        lock (s_internalSyncObject)
        {
            if (_typeData != null)
            {
                reflectedTypeData = (ReflectedTypeData)_typeData[type];
            }
            if (reflectedTypeData == null && createIfNeeded)
            {
                reflectedTypeData = new ReflectedTypeData(type);
                if (_typeData == null)
                {
                    _typeData = new Hashtable();
                }
                _typeData[type] = reflectedTypeData;
            }
        }
        return reflectedTypeData;
    }
References System.ComponentModel.ReflectTypeDescriptionProvider._typeData, System.ComponentModel.ReflectTypeDescriptionProvider.s_internalSyncObject, and System.type.
Referenced by System.ComponentModel.ReflectTypeDescriptionProvider.GetAttributes(), System.ComponentModel.ReflectTypeDescriptionProvider.GetClassName(), System.ComponentModel.ReflectTypeDescriptionProvider.GetComponentName(), System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(), System.ComponentModel.ReflectTypeDescriptionProvider.GetDefaultEvent(), System.ComponentModel.ReflectTypeDescriptionProvider.GetDefaultProperty(), System.ComponentModel.ReflectTypeDescriptionProvider.GetEditor(), System.ComponentModel.ReflectTypeDescriptionProvider.GetEvents(), System.ComponentModel.ReflectTypeDescriptionProvider.GetProperties(), System.ComponentModel.ReflectTypeDescriptionProvider.IsPopulated(), and System.ComponentModel.ReflectTypeDescriptionProvider.Refresh().