Terraria: System.Xml.DtdParser.SendValidationEvent
SendValidationEvent() [1/3]
void System.Xml.DtdParser.SendValidationEvent (int pos, XmlSeverityType severity, string code, string arg) inline private
Definition at line 3002 of file DtdParser.cs.
    {
        SendValidationEvent(severity, new XmlSchemaException(code, arg, BaseUriStr, LineNo, LinePos + (pos - _curPos)));
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser.BaseUriStr, System.Xml.DtdParser.LineNo, System.Xml.DtdParser.LinePos, and System.Xml.DtdParser.SendValidationEvent().
Referenced by System.Xml.DtdParser.Parse(), System.Xml.DtdParser.ParseAsync(), System.Xml.DtdParser.ParseAttlistDefault(), System.Xml.DtdParser.ParseAttlistDefaultAsync(), System.Xml.DtdParser.ParseAttlistType(), System.Xml.DtdParser.ParseAttlistTypeAsync(), System.Xml.DtdParser.ParseComment(), System.Xml.DtdParser.ParseCommentAsync(), System.Xml.DtdParser.ParseCondSection(), System.Xml.DtdParser.ParseCondSectionAsync(), System.Xml.DtdParser.ParseElementDecl(), System.Xml.DtdParser.ParseElementDeclAsync(), System.Xml.DtdParser.ParseElementMixedContent(), System.Xml.DtdParser.ParseElementMixedContentAsync(), System.Xml.DtdParser.ParseElementOnlyContent(), System.Xml.DtdParser.ParseElementOnlyContentAsync(), System.Xml.DtdParser.ParseNotationDecl(), System.Xml.DtdParser.ParseNotationDeclAsync(), System.Xml.DtdParser.ParseSubset(), System.Xml.DtdParser.ParseSubsetAsync(), System.Xml.DtdParser.SendValidationEvent(), System.Xml.DtdParser.SendValidationEvent(), and System.Xml.DtdParser.VerifyEntityReference().