Terraria: System.Xml.DtdParser.OnUnexpectedError
OnUnexpectedError()
void System.Xml.DtdParser.OnUnexpectedError () inline private
Definition at line 3026 of file DtdParser.cs.
    {
        Throw(_curPos, System.SR.Xml_InternalError);
    }
References System.Xml.DtdParser._curPos, System.Xml.DtdParser.Throw(), and System.SR.Xml_InternalError.
Referenced by System.Xml.DtdParser.ParseAttlistDecl(), System.Xml.DtdParser.ParseAttlistDeclAsync(), System.Xml.DtdParser.ParseAttlistDefault(), System.Xml.DtdParser.ParseAttlistDefaultAsync(), System.Xml.DtdParser.ParseAttlistType(), System.Xml.DtdParser.ParseAttlistTypeAsync(), System.Xml.DtdParser.ParseCondSection(), System.Xml.DtdParser.ParseCondSectionAsync(), System.Xml.DtdParser.ParseElementDecl(), System.Xml.DtdParser.ParseElementDeclAsync(), System.Xml.DtdParser.ParseElementMixedContent(), System.Xml.DtdParser.ParseElementMixedContentAsync(), System.Xml.DtdParser.ParseElementOnlyContent(), System.Xml.DtdParser.ParseElementOnlyContentAsync(), System.Xml.DtdParser.ParseEntityDecl(), System.Xml.DtdParser.ParseEntityDeclAsync(), System.Xml.DtdParser.ParseInDocumentDtd(), System.Xml.DtdParser.ParseInDocumentDtdAsync(), System.Xml.DtdParser.ParseNotationDecl(), and System.Xml.DtdParser.ParseNotationDeclAsync().