Terraria: System.Dynamic.Utils.ExpressionUtils.ReturnReadOnly
ReturnReadOnly() [2/2]
static ReadOnlyCollection< ParameterExpression > System.Dynamic.Utils.ExpressionUtils.ReturnReadOnly (IParameterProvider provider, ref object collection) inline static
Definition at line 12 of file ExpressionUtils.cs.
    {
        if (collection is ParameterExpression parameterExpression)
        {
            Interlocked.CompareExchange(ref collection, new ReadOnlyCollection<ParameterExpression>(new ListParameterProvider(provider, parameterExpression)), parameterExpression);
        }
        return (ReadOnlyCollection<ParameterExpression>)collection;
    }
References System.collection, and System.Threading.Interlocked.CompareExchange().
Referenced by System.Linq.Expressions.DynamicExpression1.GetOrMakeArguments(), System.Linq.Expressions.DynamicExpression2.GetOrMakeArguments(), System.Linq.Expressions.DynamicExpression3.GetOrMakeArguments(), System.Linq.Expressions.DynamicExpression4.GetOrMakeArguments(), System.Linq.Expressions.DynamicExpressionN.GetOrMakeArguments(), System.Linq.Expressions.InstanceMethodCallExpression1.GetOrMakeArguments(), System.Linq.Expressions.InstanceMethodCallExpression2.GetOrMakeArguments(), System.Linq.Expressions.InstanceMethodCallExpression3.GetOrMakeArguments(), System.Linq.Expressions.InstanceMethodCallExpressionN.GetOrMakeArguments(), System.Linq.Expressions.InvocationExpression1.GetOrMakeArguments(), System.Linq.Expressions.InvocationExpression2.GetOrMakeArguments(), System.Linq.Expressions.InvocationExpression3.GetOrMakeArguments(), System.Linq.Expressions.InvocationExpression4.GetOrMakeArguments(), System.Linq.Expressions.InvocationExpression5.GetOrMakeArguments(), System.Linq.Expressions.InvocationExpressionN.GetOrMakeArguments(), System.Linq.Expressions.MethodCallExpression1.GetOrMakeArguments(), System.Linq.Expressions.MethodCallExpression2.GetOrMakeArguments(), System.Linq.Expressions.MethodCallExpression3.GetOrMakeArguments(), System.Linq.Expressions.MethodCallExpression4.GetOrMakeArguments(), System.Linq.Expressions.MethodCallExpression5.GetOrMakeArguments(), System.Linq.Expressions.MethodCallExpressionN.GetOrMakeArguments(), System.Linq.Expressions.BlockN.GetOrMakeExpressions(), System.Linq.Expressions.ScopeN.GetOrMakeExpressions(), System.Linq.Expressions.Expression1< TDelegate >.GetOrMakeParameters(), System.Linq.Expressions.Expression2< TDelegate >.GetOrMakeParameters(), System.Linq.Expressions.Expression3< TDelegate >.GetOrMakeParameters(), System.Linq.Expressions.ExpressionN< TDelegate >.GetOrMakeParameters(), and System.Linq.Expressions.ScopeExpression.GetOrMakeVariables().