Terraria: System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount
ValidateArgumentCount() [1/2]
static void System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount (MethodBase method, ExpressionType nodeKind, int count, ParameterInfo[] pis) inline static
Definition at line 80 of file ExpressionUtils.cs.
    {
        if (pis.Length != count)
        {
            switch (nodeKind)
            {
            case ExpressionType.New:
                throw Error.IncorrectNumberOfConstructorArguments();
            case ExpressionType.Invoke:
                throw Error.IncorrectNumberOfLambdaArguments();
            case ExpressionType.Call:
            case ExpressionType.Dynamic:
                throw Error.IncorrectNumberOfMethodCallArguments(method, "method");
            default:
                throw ContractUtils.Unreachable;
            }
        }
    }
References System.count, System.Linq.Expressions.Error.IncorrectNumberOfConstructorArguments(), System.Linq.Expressions.Error.IncorrectNumberOfLambdaArguments(), System.Linq.Expressions.Error.IncorrectNumberOfMethodCallArguments(), and System.Dynamic.Utils.ContractUtils.Unreachable.
Referenced by System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.Expression< TDelegate >.ValidateArgumentCount(), and System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes().