Terraria: System.Dynamic.Utils.ExpressionUtils.RequiresCanRead
RequiresCanRead() [1/2]
static void System.Dynamic.Utils.ExpressionUtils.RequiresCanRead (Expression expression, string paramName) inline static
Definition at line 126 of file ExpressionUtils.cs.
    {
        RequiresCanRead(expression, paramName, -1);
    }
References System.Dynamic.Utils.ExpressionUtils.RequiresCanRead().
Referenced by System.Linq.Expressions.Expression< TDelegate >.Add(), System.Linq.Expressions.Expression< TDelegate >.AddAssign(), System.Linq.Expressions.Expression< TDelegate >.AddAssignChecked(), System.Linq.Expressions.Expression< TDelegate >.AddChecked(), System.Linq.Expressions.Expression< TDelegate >.And(), System.Linq.Expressions.Expression< TDelegate >.AndAlso(), System.Linq.Expressions.Expression< TDelegate >.AndAssign(), System.Linq.Expressions.Expression< TDelegate >.ArrayAccess(), System.Linq.Expressions.Expression< TDelegate >.ArrayIndex(), System.Linq.Expressions.Expression< TDelegate >.ArrayIndex(), System.Linq.Expressions.Expression< TDelegate >.ArrayLength(), System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Bind(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.Expressions.Expression< TDelegate >.Coalesce(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Expression< TDelegate >.Condition(), System.Linq.Expressions.Expression< TDelegate >.Convert(), System.Linq.Expressions.Expression< TDelegate >.ConvertChecked(), System.Linq.Expressions.Expression< TDelegate >.Decrement(), System.Linq.Expressions.Expression< TDelegate >.Divide(), System.Linq.Expressions.Expression< TDelegate >.DivideAssign(), System.Linq.Expressions.Expression< TDelegate >.Equal(), System.Linq.Expressions.Expression< TDelegate >.ExclusiveOr(), System.Linq.Expressions.Expression< TDelegate >.ExclusiveOrAssign(), System.Linq.Expressions.Expression< TDelegate >.Field(), System.Linq.Expressions.Expression< TDelegate >.Field(), System.Linq.Expressions.Expression< TDelegate >.GreaterThan(), System.Linq.Expressions.Expression< TDelegate >.GreaterThanOrEqual(), System.Linq.Expressions.Expression< TDelegate >.Increment(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.Linq.Expressions.Expression< TDelegate >.IsFalse(), System.Linq.Expressions.Expression< TDelegate >.IsTrue(), System.Linq.Expressions.Expression< TDelegate >.LeftShift(), System.Linq.Expressions.Expression< TDelegate >.LeftShiftAssign(), System.Linq.Expressions.Expression< TDelegate >.LessThan(), System.Linq.Expressions.Expression< TDelegate >.LessThanOrEqual(), System.Linq.Expressions.Expression< TDelegate >.Loop(), System.Linq.Expressions.Expression< TDelegate >.MakeCatchBlock(), System.Linq.Expressions.Expression< TDelegate >.MakeOpAssignUnary(), System.Linq.Expressions.Expression< TDelegate >.MakeTry(), System.Linq.Expressions.Expression< TDelegate >.Modulo(), System.Linq.Expressions.Expression< TDelegate >.ModuloAssign(), System.Linq.Expressions.Expression< TDelegate >.Multiply(), System.Linq.Expressions.Expression< TDelegate >.MultiplyAssign(), System.Linq.Expressions.Expression< TDelegate >.MultiplyAssignChecked(), System.Linq.Expressions.Expression< TDelegate >.MultiplyChecked(), System.Linq.Expressions.Expression< TDelegate >.Negate(), System.Linq.Expressions.Expression< TDelegate >.NegateChecked(), System.Linq.Expressions.Expression< TDelegate >.NewArrayBounds(), System.Linq.Expressions.Expression< TDelegate >.NewArrayInit(), System.Linq.Expressions.Expression< TDelegate >.Not(), System.Linq.Expressions.Expression< TDelegate >.NotEqual(), System.Linq.Expressions.Expression< TDelegate >.OnesComplement(), System.Linq.Expressions.Expression< TDelegate >.Or(), System.Linq.Expressions.Expression< TDelegate >.OrAssign(), System.Linq.Expressions.Expression< TDelegate >.OrElse(), System.Linq.Expressions.Expression< TDelegate >.Power(), System.Linq.Expressions.Expression< TDelegate >.PowerAssign(), System.Linq.Expressions.Expression< TDelegate >.Property(), System.Linq.Expressions.Expression< TDelegate >.Property(), System.Linq.Expressions.Expression< TDelegate >.Property(), System.Linq.Expressions.Expression< TDelegate >.PropertyOrField(), System.Linq.Expressions.Expression< TDelegate >.Quote(), System.Linq.Expressions.Expression< TDelegate >.ReferenceEqual(), System.Linq.Expressions.Expression< TDelegate >.ReferenceNotEqual(), System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Linq.Expressions.Expression< TDelegate >.RequiresCanRead(), System.Linq.Expressions.Expression< TDelegate >.RightShift(), System.Linq.Expressions.Expression< TDelegate >.RightShiftAssign(), System.Linq.Expressions.Expression< TDelegate >.Subtract(), System.Linq.Expressions.Expression< TDelegate >.SubtractAssign(), System.Linq.Expressions.Expression< TDelegate >.SubtractAssignChecked(), System.Linq.Expressions.Expression< TDelegate >.SubtractChecked(), System.Linq.Expressions.Expression< TDelegate >.Switch(), System.Linq.Expressions.Expression< TDelegate >.SwitchCase(), System.Linq.Expressions.Expression< TDelegate >.Throw(), System.Linq.Expressions.Expression< TDelegate >.TypeAs(), System.Linq.Expressions.Expression< TDelegate >.TypeEqual(), System.Linq.Expressions.Expression< TDelegate >.TypeIs(), System.Linq.Expressions.Expression< TDelegate >.UnaryPlus(), System.Linq.Expressions.Expression< TDelegate >.Unbox(), System.Linq.Expressions.Expression< TDelegate >.ValidateAccessor(), System.Linq.Expressions.Expression< TDelegate >.ValidateAccessorArgumentTypes(), System.Linq.Expressions.ExpressionExtension.ValidateDynamicArgument(), System.Linq.Expressions.Expression< TDelegate >.ValidateGotoType(), System.Linq.Expressions.Expression< TDelegate >.ValidateLambdaArgs(), System.Linq.Expressions.Expression< TDelegate >.ValidateNewArgs(), System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(), and System.Linq.Expressions.Expression< TDelegate >.ValidateStaticOrInstanceMethod().