Terraria: System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes
ValidateArgumentTypes()
static void System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes (MethodBase method, ExpressionType nodeKind, ref ReadOnlyCollection< Expression > arguments, string methodParamName) inline static
Definition at line 50 of file ExpressionUtils.cs.
    {
        ParameterInfo[] parametersForValidation = GetParametersForValidation(method, nodeKind);
        ValidateArgumentCount(method, nodeKind, arguments.Count, parametersForValidation);
        Expression[] array = null;
        int i = 0;
        for (int num = parametersForValidation.Length; i < num; i++)
        {
            Expression arguments2 = arguments[i];
            ParameterInfo pi = parametersForValidation[i];
            arguments2 = ValidateOneArgument(method, nodeKind, arguments2, pi, methodParamName, "arguments", i);
            if (array == null && arguments2 != arguments[i])
            {
                array = new Expression[arguments.Count];
                for (int j = 0; j < i; j++)
                {
                    array[j] = arguments[j];
                }
            }
            if (array != null)
            {
                array[i] = arguments2;
            }
        }
        if (array != null)
        {
            arguments = new TrueReadOnlyCollection<Expression>(array);
        }
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Dynamic.Utils.ExpressionUtils.GetParametersForValidation(), System.Dynamic.Utils.ExpressionUtils.ValidateArgumentCount(), and System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument().
Referenced by System.Linq.Expressions.ExpressionExtension.MakeDynamic(), and System.Linq.Expressions.Expression< TDelegate >.ValidateArgumentTypes().