Terraria: System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument
ValidateOneArgument()
static Expression System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument (MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, string methodParamName, string argumentParamName, int index = -1) inline static
Definition at line 99 of file ExpressionUtils.cs.
    {
        RequiresCanRead(arguments, argumentParamName, index);
        Type type = pi.ParameterType;
        if (type.IsByRef)
        {
            type = type.GetElementType();
        }
        TypeUtils.ValidateType(type, methodParamName, allowByRef: true, allowPointer: true);
        if (!TypeUtils.AreReferenceAssignable(type, arguments.Type) && !TryQuote(type, ref arguments))
        {
            switch (nodeKind)
            {
            case ExpressionType.New:
                throw Error.ExpressionTypeDoesNotMatchConstructorParameter(arguments.Type, type, argumentParamName, index);
            case ExpressionType.Invoke:
                throw Error.ExpressionTypeDoesNotMatchParameter(arguments.Type, type, argumentParamName, index);
            case ExpressionType.Call:
            case ExpressionType.Dynamic:
                throw Error.ExpressionTypeDoesNotMatchMethodParameter(arguments.Type, type, method, argumentParamName, index);
            default:
                throw ContractUtils.Unreachable;
            }
        }
        return arguments;
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Linq.Expressions.Error.ExpressionTypeDoesNotMatchConstructorParameter(), System.Linq.Expressions.Error.ExpressionTypeDoesNotMatchMethodParameter(), System.Linq.Expressions.Error.ExpressionTypeDoesNotMatchParameter(), System.index, System.Dynamic.Utils.ExpressionUtils.RequiresCanRead(), System.Dynamic.Utils.ExpressionUtils.TryQuote(), System.type, System.Dynamic.Utils.ContractUtils.Unreachable, and System.Dynamic.Utils.TypeUtils.ValidateType().
Referenced by System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Linq.Expressions.ExpressionExtension.MakeDynamic(), System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(), and System.Linq.Expressions.Expression< TDelegate >.ValidateOneArgument().