Terraria: System.ArgIterator.GetNextArg
GetNextArg() [2/2]
unsafe TypedReference System.ArgIterator.GetNextArg (RuntimeTypeHandle rth) inline
Definition at line 46 of file ArgIterator.cs.
    {
        if (sigPtr != IntPtr.Zero)
        {
            return GetNextArg();
        }
        if (ArgPtr == IntPtr.Zero)
        {
            throw new ArgumentNullException();
        }
        TypedReference result = default(TypedReference);
        InternalGetNextArg(&result, rth.GetRuntimeType());
        return result;
    }
References System.ArgIterator.ArgPtr, System.ArgIterator.GetNextArg(), System.RuntimeTypeHandle.GetRuntimeType(), System.ArgIterator.InternalGetNextArg(), System.ArgIterator.sigPtr, and System.IntPtr.Zero.