Terraria: System.Linq.Enumerable.DistinctIterator.MoveNext
MoveNext()
override bool System.Linq.Enumerable.DistinctIterator< TSource >.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 805 of file Enumerable.cs.
        {
            int state = _state;
            TSource current;
            if (state != 1)
            {
                if (state == 2)
                {
                    while (_enumerator.MoveNext())
                    {
                        current = _enumerator.Current;
                        if (_set.Add(current))
{
                            _current = current;
                            return true;
                        }
                    }
                }
                Dispose();
                return false;
            }
            _enumerator = _source.GetEnumerator();
            if (!_enumerator.MoveNext())
            {
                Dispose();
                return false;
            }
            current = _enumerator.Current;
            _set = new HashSet<TSource>(7, _comparer);
            _set.Add(current);
            _current = current;
            _state = 2;
            return true;
        }
References System.Linq.Enumerable.DistinctIterator< TSource >._comparer, System.Linq.Enumerable.Iterator< TSource >._current, System.Linq.Enumerable.DistinctIterator< TSource >._enumerator, System.Linq.Enumerable.DistinctIterator< TSource >._set, System.Linq.Enumerable.DistinctIterator< TSource >._source, System.Linq.Enumerable.Iterator< TSource >._state, System.Collections.Generic.HashSet< T >.Add(), System.Collections.IEnumerator.Current, System.Linq.Enumerable.DistinctIterator< TSource >.Dispose(), System.Collections.IEnumerable.GetEnumerator(), System.Collections.IEnumerator.MoveNext(), and System.state.