Terraria: System.Linq.Expressions.Interpreter.CastInstruction.Create
Create()
static Instruction System.Linq.Expressions.Interpreter.CastInstruction.Create (Type t) inline static inherited
Definition at line 123 of file CastInstruction.cs.
    {
        return t.GetTypeCode() switch
        {
            TypeCode.Boolean => s_Boolean ?? (s_Boolean = new CastInstructionT<bool>()),
            TypeCode.Byte => s_Byte ?? (s_Byte = new CastInstructionT<byte>()),
            TypeCode.Char => s_Char ?? (s_Char = new CastInstructionT<char>()),
            TypeCode.DateTime => s_DateTime ?? (s_DateTime = new CastInstructionT<DateTime>()),
            TypeCode.Decimal => s_Decimal ?? (s_Decimal = new CastInstructionT<decimal>()),
            TypeCode.Double => s_Double ?? (s_Double = new CastInstructionT<double>()),
            TypeCode.Int16 => s_Int16 ?? (s_Int16 = new CastInstructionT<short>()),
            TypeCode.Int32 => s_Int32 ?? (s_Int32 = new CastInstructionT<int>()),
            TypeCode.Int64 => s_Int64 ?? (s_Int64 = new CastInstructionT<long>()),
            TypeCode.SByte => s_SByte ?? (s_SByte = new CastInstructionT<sbyte>()),
            TypeCode.Single => s_Single ?? (s_Single = new CastInstructionT<float>()),
            TypeCode.String => s_String ?? (s_String = new CastInstructionT<string>()),
            TypeCode.UInt16 => s_UInt16 ?? (s_UInt16 = new CastInstructionT<ushort>()),
            TypeCode.UInt32 => s_UInt32 ?? (s_UInt32 = new CastInstructionT<uint>()),
            TypeCode.UInt64 => s_UInt64 ?? (s_UInt64 = new CastInstructionT<ulong>()),
            _ => CastInstructionNoT.Create(t),
        };
    }
References System.Linq.Expressions.Interpreter.CastInstruction.CastInstructionNoT.Create(), System.Type.GetTypeCode(), System.Linq.Expressions.Interpreter.CastInstruction.s_Boolean, System.Linq.Expressions.Interpreter.CastInstruction.s_Byte, System.Linq.Expressions.Interpreter.CastInstruction.s_Char, System.Linq.Expressions.Interpreter.CastInstruction.s_DateTime, System.Linq.Expressions.Interpreter.CastInstruction.s_Decimal, System.Linq.Expressions.Interpreter.CastInstruction.s_Double, System.Linq.Expressions.Interpreter.CastInstruction.s_Int16, System.Linq.Expressions.Interpreter.CastInstruction.s_Int32, System.Linq.Expressions.Interpreter.CastInstruction.s_Int64, System.Linq.Expressions.Interpreter.CastInstruction.s_SByte, System.Linq.Expressions.Interpreter.CastInstruction.s_Single, System.Linq.Expressions.Interpreter.CastInstruction.s_String, System.Linq.Expressions.Interpreter.CastInstruction.s_UInt16, System.Linq.Expressions.Interpreter.CastInstruction.s_UInt32, and System.Linq.Expressions.Interpreter.CastInstruction.s_UInt64.
Referenced by System.Linq.Expressions.Interpreter.InstructionList.EmitCast().