Terraria: Terraria.GameContent.Animations.Segments.LocalizedTextSegment.Draw
Draw()
void Terraria.GameContent.Animations.Segments.LocalizedTextSegment.Draw (ref GameAnimationSegment info) inline
Implements Terraria.GameContent.Animations.IAnimationSegment.
Definition at line 40 of file Segments.cs.
        {
            float num = 250f;
            float num2 = 250f;
            int timeInAnimation = info.TimeInAnimation;
            float num3 = Utils.GetLerpValue(_timeToShowPeak - num, _timeToShowPeak, timeInAnimation, clamped: true) * Utils.GetLerpValue(_timeToShowPeak + num2, _timeToShowPeak, timeInAnimation, clamped: true);
            if (!(num3 <= 0f))
            {
                float num4 = _timeToShowPeak - (float)timeInAnimation;
                Vector2 position = info.AnchorPositionOnScreen + new Vector2(0f, num4 * 0.5f);
                position += _anchorOffset;
                Vector2 baseScale = new Vector2(0.7f);
                float num5 = Main.GlobalTimeWrappedHourly * 0.02f % 1f;
                if (num5 < 0f)
                {
                    num5 += 1f;
                }
                Color color = Main.hslToRgb(num5, 1f, 0.5f);
                string value = _text.Value;
                Vector2 origin = FontAssets.DeathText.Value.MeasureString(value);
                origin *= 0.5f;
                float num6 = 1f - (1f - num3) * (1f - num3);
                ChatManager.DrawColorCodedStringShadow(info.SpriteBatch, FontAssets.DeathText.Value, value, position, color * num6 * num6 * 0.25f * info.DisplayOpacity, 0f, origin, baseScale);
                ChatManager.DrawColorCodedString(info.SpriteBatch, FontAssets.DeathText.Value, value, position, Color.White * num6 * info.DisplayOpacity, 0f, origin, baseScale);
            }
        }
References Terraria.GameContent.Animations.Segments.LocalizedTextSegment._anchorOffset, Terraria.GameContent.Animations.Segments.LocalizedTextSegment._text, Terraria.GameContent.Animations.Segments.LocalizedTextSegment._timeToShowPeak, Terraria.GameContent.FontAssets.DeathText, Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.Utils.GetLerpValue(), Terraria.Main.hslToRgb(), ReLogic.Content.Asset< T >.Value, and Terraria.Localization.LocalizedText.Value.