Terraria: System.Drawing.KnownColorTable.ArgbToKnownColor
ArgbToKnownColor()
static Color System.Drawing.KnownColorTable.ArgbToKnownColor (uint argb) inline static package
Definition at line 49 of file KnownColorTable.cs.
    {
        for (int i = 1; i < s_colorValueTable.Length; i++)
        {
            if (ColorKindTable[i] == 1 && s_colorValueTable[i] == argb)
            {
                return Color.FromKnownColor((KnownColor)i);
            }
        }
        return Color.FromArgb((int)argb);
    }
References System.Drawing.KnownColorTable.ColorKindTable, System.Drawing.Color.FromArgb(), System.Drawing.Color.FromKnownColor(), and System.Drawing.KnownColorTable.s_colorValueTable.
Referenced by System.Drawing.ColorTranslator.FromOle().