Terraria: Terraria.Mount.GetWitchBroomTrinketRotation
GetWitchBroomTrinketRotation()
float Terraria.Mount.GetWitchBroomTrinketRotation (Player player) inline private
Definition at line 3003 of file Mount.cs.
    {
        float num = Utils.Clamp(player.velocity.X / 10f, -1f, 1f);
        float num2 = 0f;
        Point point = player.Center.ToTileCoordinates();
        float num3 = 0.5f;
        if (WorldGen.InAPlaceWithWind(point.X, point.Y, 1, 1))
        {
            num3 = 1f;
        }
        num2 = (float)Math.Sin((float)player.miscCounter / 300f * ((float)Math.PI * 2f) * 3f) * ((float)Math.PI / 4f) * Math.Abs(Main.WindForVisuals) * 0.5f + (float)Math.PI / 4f * (0f - Main.WindForVisuals) * 0.5f;
        num2 *= num3;
        return num * (float)Math.Sin((float)player.miscCounter / 150f * ((float)Math.PI * 2f) * 3f) * ((float)Math.PI / 4f) * 0.5f + num * ((float)Math.PI / 4f) * 0.5f + num2;
    }
References System.Math.Abs(), Terraria.Entity.Center, Terraria.WorldGen.InAPlaceWithWind(), System.Math.PI, System.Math.Sin(), Terraria.Entity.velocity, Terraria.Main.WindForVisuals, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Mount.Draw(), and Terraria.Mount.UpdateEffects().