Terraria: Terraria.Mount.DrillSmartCursor_Walls
DrillSmartCursor_Walls()
Point16 Terraria.Mount.DrillSmartCursor_Walls (Player mountedPlayer, DrillMountData data) inline private
    {
        Vector2 vector = ((mountedPlayer.whoAmI != Main.myPlayer) ? data.crosshairPosition : (Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY)));
        Vector2 center = mountedPlayer.Center;
        Vector2 vector2 = vector - center;
        float num = vector2.Length();
        if (num > 224f)
        {
            num = 224f;
        }
        num += 32f;
        num += 16f;
        vector2.Normalize();
        Vector2 end = center + vector2 * num;
        Point16 tilePoint = new Point16(-1, -1);
        if (!Utils.PlotTileLine(center, end, 97.6f, delegate(int x, int y)
        {
            tilePoint = new Point16(x, y);
            for (int i = 0; i < data.beams.Length; i++)
            {
                if (data.beams[i].curTileTarget == tilePoint && data.beams[i].lastPurpose == 1)
                {
                    return true;
                }
            }
            Tile tile = Main.tile[x, y];
            if (tile == null)
            {
                return false;
            }
            return (tile.wall <= 0 || !Player.CanPlayerSmashWall(x, y)) ? true : false;
        }))
        {
            return tilePoint;
        }
        return new Point16(-1, -1);
    }
References Terraria.Mount.DrillMountData.beams, Terraria.Player.CanPlayerSmashWall(), Terraria.Mount.DrillMountData.crosshairPosition, Terraria.Mount.DrillBeam.curTileTarget, Terraria.Mount.DrillBeam.lastPurpose, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Utils.PlotTileLine(), Terraria.Main.tile, and Terraria.Tile.wall.
Referenced by Terraria.Mount.UseDrill().