Terraria: Terraria.Mount.GetMinecartMechPoint
GetMinecartMechPoint()
static Vector2 Terraria.Mount.GetMinecartMechPoint (Player mountedPlayer, int offX, int offY) inline static
Definition at line 4445 of file Mount.cs.
    {
        int num = Math.Sign(mountedPlayer.velocity.X);
        if (num == 0)
        {
            num = mountedPlayer.direction;
        }
        float num2 = offX;
        int num3 = Math.Sign(offX);
        if (mountedPlayer.direction != num)
        {
            num2 -= (float)num3;
        }
        if (num == -1)
        {
            num2 -= (float)num3;
        }
        Vector2 vector = new Vector2(num2 * (float)num, offY).RotatedBy(mountedPlayer.fullRotation);
        Vector2 vector2 = new Vector2(MathHelper.Lerp(0f, -8f, mountedPlayer.fullRotation / ((float)Math.PI / 4f)), MathHelper.Lerp(0f, 2f, Math.Abs(mountedPlayer.fullRotation / ((float)Math.PI / 4f)))).RotatedBy(mountedPlayer.fullRotation);
        if (num == Math.Sign(mountedPlayer.fullRotation))
        {
            vector2 *= MathHelper.Lerp(1f, 0.6f, Math.Abs(mountedPlayer.fullRotation / ((float)Math.PI / 4f)));
        }
        return mountedPlayer.Bottom + vector + vector2;
    }
References System.Math.Abs(), Microsoft.Xna.Framework.MathHelper.Lerp(), System.Math.PI, System.Math.Sign(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Mount.CastSuperCartLaser().