Terraria: System.Xml.Xsl.IlGen.OptimizerPatterns.Read
Read()
static OptimizerPatterns System.Xml.Xsl.IlGen.OptimizerPatterns.Read (QilNode nd) inline static
Definition at line 25 of file OptimizerPatterns.cs.
    {
        OptimizerPatterns optimizerPatterns = ((nd.Annotation is XmlILAnnotation xmlILAnnotation) ? xmlILAnnotation.Patterns : null);
        if (optimizerPatterns == null)
        {
            if (!nd.XmlType.MaybeMany)
            {
                if (s_zeroOrOneDefault == null)
                {
                    optimizerPatterns = new OptimizerPatterns();
                    optimizerPatterns.AddPattern(OptimizerPatternName.IsDocOrderDistinct);
                    optimizerPatterns.AddPattern(OptimizerPatternName.SameDepth);
                    optimizerPatterns._isReadOnly = true;
                    s_zeroOrOneDefault = optimizerPatterns;
                }
                else
                {
                    optimizerPatterns = s_zeroOrOneDefault;
                }
            }
            else if (nd.XmlType.IsDod)
            {
                if (s_dodDefault == null)
                {
                    optimizerPatterns = new OptimizerPatterns();
                    optimizerPatterns.AddPattern(OptimizerPatternName.IsDocOrderDistinct);
                    optimizerPatterns._isReadOnly = true;
                    s_dodDefault = optimizerPatterns;
                }
                else
                {
                    optimizerPatterns = s_dodDefault;
                }
            }
            else if (s_maybeManyDefault == null)
            {
                optimizerPatterns = new OptimizerPatterns();
                optimizerPatterns._isReadOnly = true;
                s_maybeManyDefault = optimizerPatterns;
            }
            else
            {
                optimizerPatterns = s_maybeManyDefault;
            }
        }
        return optimizerPatterns;
    }
References System.Xml.Dictionary, System.Xml.Xsl.IlGen.OptimizerPatterns.s_dodDefault, System.Xml.Xsl.IlGen.OptimizerPatterns.s_maybeManyDefault, and System.Xml.Xsl.IlGen.OptimizerPatterns.s_zeroOrOneDefault.
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowDodReverse(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AllowJoinAndDod(), System.Xml.Xsl.IlGen.XmlILVisitor.CachesResult(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.EliminateUnusedGlobals(), System.Xml.Xsl.XmlILGenerator.EvaluateGlobalValues(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleDodPatterns(), System.Xml.Xsl.IlGen.XmlILVisitor.HandleFilterPatterns(), System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.IsStepPattern(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Xsl.IlGen.XmlILVisitor.StartBinding(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsType(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitLength(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitRtfCtor(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitUnion().