Terraria: System.Xml.Xsl.IlGen.OptimizerPatterns.Write
Write()
static OptimizerPatterns System.Xml.Xsl.IlGen.OptimizerPatterns.Write (QilNode nd) inline static
Definition at line 73 of file OptimizerPatterns.cs.
    {
        XmlILAnnotation xmlILAnnotation = XmlILAnnotation.Write(nd);
        OptimizerPatterns optimizerPatterns = xmlILAnnotation.Patterns;
        if (optimizerPatterns == null || optimizerPatterns._isReadOnly)
        {
            optimizerPatterns = (xmlILAnnotation.Patterns = new OptimizerPatterns());
            if (!nd.XmlType.MaybeMany)
            {
                optimizerPatterns.AddPattern(OptimizerPatternName.IsDocOrderDistinct);
                optimizerPatterns.AddPattern(OptimizerPatternName.SameDepth);
            }
            else if (nd.XmlType.IsDod)
            {
                optimizerPatterns.AddPattern(OptimizerPatternName.IsDocOrderDistinct);
            }
        }
        return optimizerPatterns;
    }
References System.Xml.Xsl.IlGen.OptimizerPatterns.AddPattern(), System.Xml.Dictionary, and System.Xml.Xsl.IlGen.XmlILAnnotation.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.AddStepPattern(), System.Xml.Xsl.IlGen.TailCallAnalyzer.AnalyzeDefinition(), System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.NoReplace(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAncestor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAncestorOrSelf(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAttribute(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitContent(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDescendant(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDescendantOrSelf(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDifference(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFollowingSibling(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFunction(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitGe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitGt(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIntersection(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLt(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNe(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNodeRange(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitParent(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitPositionOf(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitPreceding(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitPrecedingSibling(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitReference(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitRoot(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitRtfCtor(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitUnion(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXPathFollowing(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXPathNamespace(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitXPathPreceding().