Terraria: Terraria.Mount.TryLanding
TryLanding()
void Terraria.Mount.TryLanding (Player mountedPlayer) inline
Definition at line 3811 of file Mount.cs.
    {
        if ((_frameState == 3 || _frameState == 2) && !mountedPlayer.controlUp && !mountedPlayer.controlDown && !mountedPlayer.controlJump)
        {
            Vector2 velocity = Vector2.UnitY * mountedPlayer.gravDir * 4f;
            if (Collision.TileCollision(mountedPlayer.position, velocity, mountedPlayer.width, mountedPlayer.height, fallThrough: false, fall2: false, (int)mountedPlayer.gravDir).Y == 0f)
            {
                UpdateFrame(mountedPlayer, GetIntendedGroundedFrame(mountedPlayer), mountedPlayer.velocity);
            }
        }
    }
References Terraria.Mount._frameState, Terraria.Mount.GetIntendedGroundedFrame(), Terraria.Collision.TileCollision(), and Terraria.Mount.UpdateFrame().