Terraria: System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit
Inherit()
static void System.Xml.Xsl.IlGen.OptimizerPatterns.Inherit (QilNode ndSrc, QilNode ndDst, OptimizerPatternName pattern) inline static
Definition at line 93 of file OptimizerPatterns.cs.
    {
        OptimizerPatterns optimizerPatterns = Read(ndSrc);
        if (optimizerPatterns.MatchesPattern(pattern))
        {
            OptimizerPatterns optimizerPatterns2 = Write(ndDst);
            optimizerPatterns2.AddPattern(pattern);
            switch (pattern)
            {
            case OptimizerPatternName.Step:
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.StepNode, optimizerPatterns.GetArgument(OptimizerPatternArgument.StepNode));
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.StepInput, optimizerPatterns.GetArgument(OptimizerPatternArgument.StepInput));
                break;
            case OptimizerPatternName.FilterElements:
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.ElementQName, optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName));
                break;
            case OptimizerPatternName.FilterContentKind:
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.ElementQName, optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName));
                break;
            case OptimizerPatternName.EqualityIndex:
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.StepNode, optimizerPatterns.GetArgument(OptimizerPatternArgument.StepNode));
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.StepInput, optimizerPatterns.GetArgument(OptimizerPatternArgument.StepInput));
                break;
            case OptimizerPatternName.DodReverse:
            case OptimizerPatternName.JoinAndDod:
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.ElementQName, optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName));
                break;
            case OptimizerPatternName.MaxPosition:
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.ElementQName, optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName));
                break;
            case OptimizerPatternName.SingleTextRtf:
                optimizerPatterns2.AddArgument(OptimizerPatternArgument.ElementQName, optimizerPatterns.GetArgument(OptimizerPatternArgument.ElementQName));
                break;
            case OptimizerPatternName.FilterAttributeKind:
            case OptimizerPatternName.IsDocOrderDistinct:
            case OptimizerPatternName.IsPositional:
            case OptimizerPatternName.SameDepth:
                break;
            }
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), and System.Xml.Xsl.IlGen.OptimizerPatterns.Write().
Referenced by System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLet(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitOptimizeBarrier().