Terraria: Terraria.Mount.TryBeginningFlight
TryBeginningFlight()
void Terraria.Mount.TryBeginningFlight (Player mountedPlayer, int state) inline
    {
        if (_frameState == state || (state != 2 && state != 3) || !CanHover() || mountedPlayer.controlUp || mountedPlayer.controlDown || mountedPlayer.controlJump)
        {
            return;
        }
        Vector2 velocity = Vector2.UnitY * mountedPlayer.gravDir;
        if (Collision.TileCollision(mountedPlayer.position + new Vector2(0f, -0.001f), velocity, mountedPlayer.width, mountedPlayer.height, fallThrough: false, fall2: false, (int)mountedPlayer.gravDir).Y != 0f)
        {
            if (DoesHoverIgnoresFatigue())
            {
                mountedPlayer.position.Y += -0.001f;
                return;
            }
            float num = mountedPlayer.gravity * mountedPlayer.gravDir;
            mountedPlayer.position.Y -= mountedPlayer.velocity.Y;
            mountedPlayer.velocity.Y -= num;
        }
    }
References Terraria.Mount._frameState, Terraria.Mount.CanHover(), Terraria.Mount.DoesHoverIgnoresFatigue(), and Terraria.Collision.TileCollision().