Terraria: Terraria.Mount.ClampToDeadZone
ClampToDeadZone()
Vector2 Terraria.Mount.ClampToDeadZone (Player mountedPlayer, Vector2 position) inline private
Definition at line 4509 of file Mount.cs.
    {
        int num;
        int num2;
        switch (_type)
        {
        case 9:
            num = (int)scutlixTextureSize.Y;
            num2 = (int)scutlixTextureSize.X;
            break;
        case 46:
            num = (int)santankTextureSize.Y;
            num2 = (int)santankTextureSize.X;
            break;
        case 8:
            num = (int)drillTextureSize.Y;
            num2 = (int)drillTextureSize.X;
            break;
        default:
            return position;
        }
        Vector2 center = mountedPlayer.Center;
        position -= center;
        if (position.X > (float)(-num2) && position.X < (float)num2 && position.Y > (float)(-num) && position.Y < (float)num)
        {
            float num3 = (float)num2 / Math.Abs(position.X);
            float num4 = (float)num / Math.Abs(position.Y);
            if (num3 > num4)
            {
                position *= num4;
            }
            else
            {
                position *= num3;
            }
        }
        return position + center;
    }
References Terraria.Mount._type, System.Math.Abs(), Terraria.Mount.drillTextureSize, Terraria.Mount.santankTextureSize, Terraria.Mount.scutlixTextureSize, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Mount.AimAbility(), and Terraria.Mount.UseAbility().