Terraria: System.Net.Http.Headers.AltSvcHeaderParser.TryReadTokenOrQuotedInt32
TryReadTokenOrQuotedInt32()
static bool System.Net.Http.Headers.AltSvcHeaderParser.TryReadTokenOrQuotedInt32 (string value, int startIndex, out int result, out int readLength) inline static private
Definition at line 309 of file AltSvcHeaderParser.cs.
    {
        if (startIndex >= value.Length)
        {
            result = 0;
            readLength = 0;
            return false;
        }
        if (HttpRuleParser.IsTokenChar(value[startIndex]))
        {
            return HeaderUtilities.TryParseInt32(value, startIndex, readLength = HttpRuleParser.GetTokenLength(value, startIndex), out result);
        }
        if (HttpRuleParser.GetQuotedStringLength(value, startIndex, out var length) == HttpParseResult.Parsed)
        {
            readLength = length;
            return TryReadQuotedInt32Value(value.AsSpan(1, length - 2), out result);
        }
        result = 0;
        readLength = 0;
        return false;
    }
References System.Net.Http.HttpRuleParser.GetQuotedStringLength(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.Net.Http.HttpRuleParser.IsTokenChar(), System.length, System.startIndex, System.Net.Http.Headers.HeaderUtilities.TryParseInt32(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadQuotedInt32Value(), and System.value.
Referenced by System.Net.Http.Headers.AltSvcHeaderParser.GetParsedValueLength().