Terraria: System.Net.Http.Headers.AltSvcHeaderParser.GetParsedValueLength
GetParsedValueLength()
override int System.Net.Http.Headers.AltSvcHeaderParser.GetParsedValueLength (string value, int startIndex, object storeValue, out object parsedValue) inline protected
Definition at line 16 of file AltSvcHeaderParser.cs.
    {
        if (string.IsNullOrEmpty(value))
        {
            parsedValue = null;
            return 0;
        }
        int num = startIndex;
        if (!TryReadPercentEncodedAlpnProtocolName(value, num, out var result, out var readLength))
        {
            parsedValue = null;
            return 0;
        }
        num += readLength;
        if (result == "clear")
        {
            if (num != value.Length)
            {
                parsedValue = null;
                return 0;
            }
            parsedValue = AltSvcHeaderValue.Clear;
            return num - startIndex;
        }
        if (num == value.Length || value[num++] != '=')
        {
            parsedValue = null;
            return 0;
        }
        if (!TryReadQuotedAltAuthority(value, num, out var host, out var port, out var readLength2))
        {
            parsedValue = null;
            return 0;
        }
        num += readLength2;
        int? num2 = null;
        bool persist = false;
        while (num != value.Length)
        {
            for (; num != value.Length && IsOptionalWhiteSpace(value[num]); num++)
            {
            }
            if (num == value.Length)
            {
                parsedValue = null;
                return 0;
            }
            switch (value[num])
            {
            default:
                parsedValue = null;
                return 0;
            case ';':
            {
                for (num++; num != value.Length && IsOptionalWhiteSpace(value[num]); num++)
                {
                }
                int tokenLength = HttpRuleParser.GetTokenLength(value, num);
                if (tokenLength == 0)
                {
                    parsedValue = null;
                    return 0;
                }
                if (num + tokenLength >= value.Length || value[num + tokenLength] != '=')
                {
                    parsedValue = null;
                    return 0;
                }
                if (tokenLength == 2 && value[num] == 'm' && value[num + 1] == 'a')
                {
                    num += 3;
                    if (!TryReadTokenOrQuotedInt32(value, num, out var result2, out var readLength3))
                    {
                        parsedValue = null;
                        return 0;
                    }
                    num2 = (num2.HasValue ? new int?(Math.Min(num2.GetValueOrDefault(), result2)) : new int?(result2));
                    num += readLength3;
                }
                else if (value.AsSpan(num).StartsWith("persist="))
                {
                    num += 8;
                    if (TryReadTokenOrQuotedInt32(value, num, out var result3, out var readLength4))
                    {
                        persist = result3 == 1;
                    }
                    else if (!TrySkipTokenOrQuoted(value, num, out readLength4))
                    {
                        parsedValue = null;
                        return 0;
                    }
                    num += readLength4;
                }
                else
                {
                    num += tokenLength + 1;
                    if (!TrySkipTokenOrQuoted(value, num, out var readLength5))
                    {
                        parsedValue = null;
                        return 0;
                    }
                    num += readLength5;
                }
                continue;
            }
            case ',':
                break;
            }
            break;
        }
        TimeSpan maxAge = TimeSpan.FromTicks(((long?)num2 * 10000000L) ?? 864000000000L);
        parsedValue = new AltSvcHeaderValue(result, host, port, maxAge, persist);
        return num - startIndex;
    }
References System.Net.Http.Headers.AltSvcHeaderValue.Clear, System.TimeSpan.FromTicks(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.Net.Http.Headers.AltSvcHeaderParser.IsOptionalWhiteSpace(), System.L, System.Math.Min(), System.startIndex, System.Net.Http.Headers.AltSvcHeaderParser.TryReadPercentEncodedAlpnProtocolName(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadQuotedAltAuthority(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadTokenOrQuotedInt32(), System.Net.Http.Headers.AltSvcHeaderParser.TrySkipTokenOrQuoted(), and System.value.