Terraria: System.Net.Http.Headers.AltSvcHeaderParser.TryReadUnknownPercentEncodedAlpnProtocolName
TryReadUnknownPercentEncodedAlpnProtocolName()
static bool System.Net.Http.Headers.AltSvcHeaderParser.TryReadUnknownPercentEncodedAlpnProtocolName (ReadOnlySpan< char > value, [NotNullWhen(true)] out string result) inline static private
Definition at line 200 of file AltSvcHeaderParser.cs.
    {
        int num = value.IndexOf('%');
        if (num == -1)
        {
            result = new string(value);
            return true;
        }
        Span<char> initialBuffer = ((value.Length > 128) ? ((Span<char>)new char[value.Length]) : stackalloc char[128]);
        System.Text.ValueStringBuilder valueStringBuilder = new System.Text.ValueStringBuilder(initialBuffer);
        do
        {
            if (num != 0)
            {
                valueStringBuilder.Append(value.Slice(0, num));
            }
            if (value.Length - num < 3 || !TryReadAlpnHexDigit(value[1], out var nibble) || !TryReadAlpnHexDigit(value[2], out var nibble2))
            {
                result = null;
                return false;
            }
            valueStringBuilder.Append((char)((nibble << 8) | nibble2));
            value = value.Slice(num + 3);
            num = value.IndexOf('%');
        }
        while (num != -1);
        if (value.Length != 0)
        {
            valueStringBuilder.Append(value);
        }
        result = valueStringBuilder.ToString();
        return true;
    }
References System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.ToString(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadAlpnHexDigit(), and System.value.
Referenced by System.Net.Http.Headers.AltSvcHeaderParser.TryReadPercentEncodedAlpnProtocolName().