Terraria: System.Net.Http.Headers.AltSvcHeaderParser.TryReadPercentEncodedAlpnProtocolName
TryReadPercentEncodedAlpnProtocolName()
static bool System.Net.Http.Headers.AltSvcHeaderParser.TryReadPercentEncodedAlpnProtocolName (string value, int startIndex, [NotNullWhen(true)] out string result, out int readLength) inline static private
Definition at line 140 of file AltSvcHeaderParser.cs.
    {
        int tokenLength = HttpRuleParser.GetTokenLength(value, startIndex);
        if (tokenLength == 0)
        {
            result = null;
            readLength = 0;
            return false;
        }
        ReadOnlySpan<char> readOnlySpan = value.AsSpan(startIndex, tokenLength);
        readLength = tokenLength;
        switch (readOnlySpan.Length)
        {
        case 2:
            if (readOnlySpan[0] == 'h')
            {
                switch (readOnlySpan[1])
                {
                case '3':
                    result = "h3";
                    return true;
                case '2':
                    result = "h2";
                    return true;
                }
            }
            break;
        case 3:
            if (readOnlySpan[0] == 'h' && readOnlySpan[1] == '2' && readOnlySpan[2] == 'c')
            {
                result = "h2c";
                readLength = 3;
                return true;
            }
            break;
        case 5:
            if (readOnlySpan.SequenceEqual("clear"))
            {
                result = "clear";
                return true;
            }
            break;
        case 10:
            if (readOnlySpan.StartsWith("http%2F1."))
            {
                switch (readOnlySpan[9])
                {
                case '1':
                    result = "http/1.1";
                    return true;
                case '0':
                    result = "http/1.0";
                    return true;
                }
            }
            break;
        }
        return TryReadUnknownPercentEncodedAlpnProtocolName(readOnlySpan, out result);
    }
References System.Net.Http.HttpRuleParser.GetTokenLength(), System.ReadOnlySpan< T >.Length, System.startIndex, System.Net.Http.Headers.AltSvcHeaderParser.TryReadUnknownPercentEncodedAlpnProtocolName(), and System.value.
Referenced by System.Net.Http.Headers.AltSvcHeaderParser.GetParsedValueLength().