Terraria: System.Net.Http.Headers.AltSvcHeaderParser.TryReadQuotedValue
TryReadQuotedValue()
static bool System.Net.Http.Headers.AltSvcHeaderParser.TryReadQuotedValue (ReadOnlySpan< char > value, out string result) inline static private
Definition at line 274 of file AltSvcHeaderParser.cs.
    {
        int num = value.IndexOf('\\');
        if (num == -1)
        {
            result = ((value.Length != 0) ? new string(value) : null);
            return true;
        }
        Span<char> initialBuffer = stackalloc char[128];
        System.Text.ValueStringBuilder valueStringBuilder = new System.Text.ValueStringBuilder(initialBuffer);
        do
        {
            if (num + 1 == value.Length)
            {
                valueStringBuilder.Dispose();
                result = null;
                return false;
            }
            if (num != 0)
            {
                valueStringBuilder.Append(value.Slice(0, num));
            }
            valueStringBuilder.Append(value[num + 1]);
            value = value.Slice(num + 2);
            num = value.IndexOf('\\');
        }
        while (num != -1);
        if (value.Length != 0)
        {
            valueStringBuilder.Append(value);
        }
        result = valueStringBuilder.ToString();
        return true;
    }
References System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.Dispose(), System.Text.ValueStringBuilder.ToString(), and System.value.
Referenced by System.Net.Http.Headers.AltSvcHeaderParser.TryReadQuotedAltAuthority().