Terraria: System.Xml.Schema.XdrBuilder.ProcessElement
ProcessElement()
override bool System.Xml.Schema.XdrBuilder.ProcessElement (string prefix, string name, string ns) inline package
Definition at line 371 of file XdrBuilder.cs.
    {
        XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(name, XmlSchemaDatatype.XdrCanonizeUri(ns, _NameTable, _SchemaNames));
        if (GetNextState(xmlQualifiedName))
        {
            Push();
            if (_CurState._InitFunc != null)
            {
                _CurState._InitFunc(this, xmlQualifiedName);
            }
            return true;
        }
        if (!IsSkipableElement(xmlQualifiedName))
        {
            SendValidationEvent(System.SR.Sch_UnsupportedElement, XmlQualifiedName.ToString(name, prefix));
        }
        return false;
    }
References System.Xml.Schema.XdrBuilder._CurState, System.Xml.Schema.XdrBuilder.XdrEntry._InitFunc, System.Xml.Schema.XdrBuilder._NameTable, System.Xml.Schema.XdrBuilder._SchemaNames, System.Xml.Schema.XdrBuilder.GetNextState(), System.Xml.Schema.XdrBuilder.IsSkipableElement(), System.prefix, System.Xml.Schema.XdrBuilder.Push(), System.SR.Sch_UnsupportedElement, System.Xml.Schema.XdrBuilder.SendValidationEvent(), System.Xml.XmlQualifiedName.ToString(), and System.Xml.Schema.XmlSchemaDatatype.XdrCanonizeUri().