Terraria: System.Xml.Schema.XdrBuilder.CheckDatatype
CheckDatatype()
XmlSchemaDatatype System.Xml.Schema.XdrBuilder.CheckDatatype (string str) inline private
Definition at line 1513 of file XdrBuilder.cs.
    {
        XmlSchemaDatatype xmlSchemaDatatype = XmlSchemaDatatype.FromXdrName(str);
        if (xmlSchemaDatatype == null)
        {
            SendValidationEvent(System.SR.Sch_UnknownDtType, str);
        }
        else if (xmlSchemaDatatype.TokenizedType == XmlTokenizedType.ID && !_AttributeDef._Global)
        {
            if (_ElementDef._ElementDecl.IsIdDeclared)
            {
                SendValidationEvent(System.SR.Sch_IdAttrDeclared, XmlQualifiedName.ToString(_ElementDef._ElementDecl.Name.Name, _ElementDef._ElementDecl.Prefix));
            }
            _ElementDef._ElementDecl.IsIdDeclared = true;
        }
        return xmlSchemaDatatype;
    }
References System.Xml.Schema.XdrBuilder._AttributeDef, System.Xml.Schema.XdrBuilder.ElementContent._ElementDecl, System.Xml.Schema.XdrBuilder._ElementDef, System.Xml.Schema.XdrBuilder.AttributeContent._Global, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaDatatype.FromXdrName(), System.Xml.Schema.SchemaElementDecl.IsIdDeclared, System.Xml.Schema.SchemaDeclBase.Name, System.Xml.XmlQualifiedName.Name, System.Xml.Schema.SchemaElementDecl.Prefix, System.SR.Sch_IdAttrDeclared, System.SR.Sch_UnknownDtType, System.Xml.Schema.XdrBuilder.SendValidationEvent(), System.str, and System.Xml.XmlQualifiedName.ToString().