Terraria: System.Xml.Schema.XdrBuilder.LoadSchema
LoadSchema()
bool System.Xml.Schema.XdrBuilder.LoadSchema (string uri) inline private
Definition at line 432 of file XdrBuilder.cs.
    {
        if (_xmlResolver == null)
        {
            return false;
        }
        uri = _NameTable.Add(uri);
        if (_SchemaInfo.TargetNamespaces.ContainsKey(uri))
        {
            return false;
        }
        SchemaInfo schemaInfo = null;
        Uri baseUri = _xmlResolver.ResolveUri(null, _reader.BaseURI);
        XmlReader xmlReader = null;
        try
        {
            Uri uri2 = _xmlResolver.ResolveUri(baseUri, uri.Substring("x-schema:".Length));
            Stream input = (Stream)_xmlResolver.GetEntity(uri2, null, null);
            xmlReader = new XmlTextReader(uri2.ToString(), input, _NameTable);
            schemaInfo = new SchemaInfo();
            Parser parser = new Parser(SchemaType.XDR, _NameTable, _SchemaNames, _validationEventHandler);
            parser.XmlResolver = _xmlResolver;
            parser.Parse(xmlReader, uri);
            schemaInfo = parser.XdrSchema;
        }
        catch (XmlException ex)
        {
            SendValidationEvent(System.SR.Sch_CannotLoadSchema, new string[2] { uri, ex.Message }, XmlSeverityType.Warning);
            schemaInfo = null;
        }
        finally
        {
            xmlReader?.Close();
        }
        if (schemaInfo != null && schemaInfo.ErrorCount == 0)
        {
            _SchemaInfo.Add(schemaInfo, _validationEventHandler);
            return true;
        }
        return false;
    }
References System.Xml.Schema.XdrBuilder._NameTable, System.Xml.Schema.XdrBuilder._reader, System.Xml.Schema.XdrBuilder._SchemaInfo, System.Xml.Schema.XdrBuilder._SchemaNames, System.Xml.Schema.XdrBuilder._validationEventHandler, System.Xml.Schema.XdrBuilder._xmlResolver, System.Xml.XmlNameTable.Add(), System.Xml.Schema.SchemaInfo.Add(), System.Xml.XmlReader.BaseURI, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.Dictionary, System.Xml.Schema.SchemaInfo.ErrorCount, System.Xml.XmlResolver.GetEntity(), System.input, System.Xml.XmlResolver.ResolveUri(), System.SR.Sch_CannotLoadSchema, System.Xml.Schema.XdrBuilder.SendValidationEvent(), and System.Xml.Schema.SchemaInfo.TargetNamespaces.
Referenced by System.Xml.Schema.XdrBuilder.ProcessAttribute().