Terraria: System.Xml.Schema.XdrBuilder.ParseDtMinLength
ParseDtMinLength()
static void System.Xml.Schema.XdrBuilder.ParseDtMinLength (ref uint cVal, object obj, XdrBuilder builder) inline static private
Definition at line 1403 of file XdrBuilder.cs.
    {
        if (-1 != (int)cVal)
        {
            builder.SendValidationEvent(System.SR.Sch_DupDtMinLength);
        }
        if (!ParseInteger((string)obj, ref cVal) || cVal < 0)
        {
            builder.SendValidationEvent(System.SR.Sch_DtMinLengthInvalid, obj.ToString());
        }
    }
References System.obj, System.Xml.Schema.XdrBuilder.ParseInteger(), System.SR.Sch_DtMinLengthInvalid, and System.SR.Sch_DupDtMinLength.
Referenced by System.Xml.Schema.XdrBuilder.XDR_BuildAttributeType_DtMinLength(), and System.Xml.Schema.XdrBuilder.XDR_BuildElementType_DtMinLength().