Terraria: System.Xml.Schema.XdrBuilder.ParseInteger
ParseInteger()
static bool System.Xml.Schema.XdrBuilder.ParseInteger (string str, ref uint n) inline static private
Definition at line 1423 of file XdrBuilder.cs.
    {
        return uint.TryParse(str, NumberStyles.AllowLeadingWhite | NumberStyles.AllowTrailingWhite, NumberFormatInfo.InvariantInfo, out n);
    }
References System.Globalization.NumberFormatInfo.InvariantInfo, and System.str.
Referenced by System.Xml.Schema.XdrBuilder.ParseDtMaxLength(), System.Xml.Schema.XdrBuilder.ParseDtMinLength(), System.Xml.Schema.XdrBuilder.ParseMaxOccurs(), and System.Xml.Schema.XdrBuilder.ParseMinOccurs().