Terraria: System.Xml.Schema.XdrBuilder.SendValidationEvent
SendValidationEvent() [3/4]
void System.Xml.Schema.XdrBuilder.SendValidationEvent (string code, string[] args, XmlSeverityType severity) inline private
Definition at line 1542 of file XdrBuilder.cs.
    {
        SendValidationEvent(new XmlSchemaException(code, args, _reader.BaseURI, _positionInfo.LineNumber, _positionInfo.LinePosition), severity);
    }
References System.Xml.Schema.XdrBuilder._positionInfo, System.Xml.Schema.XdrBuilder._reader, System.Xml.XmlReader.BaseURI, System.Xml.PositionInfo.LineNumber, System.Xml.PositionInfo.LinePosition, and System.Xml.Schema.XdrBuilder.SendValidationEvent().
Referenced by System.Xml.Schema.XdrBuilder.CheckDatatype(), System.Xml.Schema.XdrBuilder.GetContent(), System.Xml.Schema.XdrBuilder.GetModel(), System.Xml.Schema.XdrBuilder.GetOrder(), System.Xml.Schema.XdrBuilder.LoadSchema(), System.Xml.Schema.XdrBuilder.ProcessAttribute(), System.Xml.Schema.XdrBuilder.ProcessCData(), System.Xml.Schema.XdrBuilder.ProcessElement(), System.Xml.Schema.XdrBuilder.SendValidationEvent(), System.Xml.Schema.XdrBuilder.SendValidationEvent(), and System.Xml.Schema.XdrBuilder.SendValidationEvent().