Terraria: System.Xml.Schema.XdrBuilder.ParseDtMaxLength
ParseDtMaxLength()
static void System.Xml.Schema.XdrBuilder.ParseDtMaxLength (ref uint cVal, object obj, XdrBuilder builder) inline static private
Definition at line 1391 of file XdrBuilder.cs.
    {
        if (-1 != (int)cVal)
        {
            builder.SendValidationEvent(System.SR.Sch_DupDtMaxLength);
        }
        if (!ParseInteger((string)obj, ref cVal) || cVal < 0)
        {
            builder.SendValidationEvent(System.SR.Sch_DtMaxLengthInvalid, obj.ToString());
        }
    }
References System.obj, System.Xml.Schema.XdrBuilder.ParseInteger(), System.SR.Sch_DtMaxLengthInvalid, and System.SR.Sch_DupDtMaxLength.
Referenced by System.Xml.Schema.XdrBuilder.XDR_BuildAttributeType_DtMaxLength(), and System.Xml.Schema.XdrBuilder.XDR_BuildElementType_DtMaxLength().