Terraria: System.Xml.Schema.XdrBuilder.ProcessAttribute
ProcessAttribute()
override void System.Xml.Schema.XdrBuilder.ProcessAttribute (string prefix, string name, string ns, string value) inline package
Definition at line 390 of file XdrBuilder.cs.
    {
        XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(name, XmlSchemaDatatype.XdrCanonizeUri(ns, _NameTable, _SchemaNames));
        for (int i = 0; i < _CurState._Attributes.Length; i++)
        {
            XdrAttributeEntry xdrAttributeEntry = _CurState._Attributes[i];
            if (!_SchemaNames.TokenToQName[(int)xdrAttributeEntry._Attribute].Equals(xmlQualifiedName))
            {
                continue;
            }
            XdrBuildFunction buildFunc = xdrAttributeEntry._BuildFunc;
            if (xdrAttributeEntry._Datatype.TokenizedType == XmlTokenizedType.QName)
            {
                string prefix2;
                XmlQualifiedName xmlQualifiedName2 = XmlQualifiedName.Parse(value, _CurNsMgr, out prefix2);
                xmlQualifiedName2.Atomize(_NameTable);
                if (prefix2.Length == 0)
                {
                    xmlQualifiedName2 = ((!IsGlobal(xdrAttributeEntry._SchemaFlags)) ? new XmlQualifiedName(xmlQualifiedName2.Name) : new XmlQualifiedName(xmlQualifiedName2.Name, _TargetNamespace));
                }
                else if (xdrAttributeEntry._Attribute != SchemaNames.Token.SchemaType)
                {
                    throw new XmlException(System.SR.Xml_UnexpectedToken, "NAME");
                }
                buildFunc(this, xmlQualifiedName2, prefix2);
            }
            else
            {
                buildFunc(this, xdrAttributeEntry._Datatype.ParseValue(value, _NameTable, _CurNsMgr), string.Empty);
            }
            return;
        }
        if ((object)ns == _SchemaNames.NsXmlNs && IsXdrSchema(value))
        {
            LoadSchema(value);
        }
        else if (!IsSkipableAttribute(xmlQualifiedName))
        {
            SendValidationEvent(System.SR.Sch_UnsupportedAttribute, XmlQualifiedName.ToString(xmlQualifiedName.Name, prefix));
        }
    }
References System.Xml.Schema.XdrBuilder.XdrEntry._Attributes, System.Xml.Schema.XdrBuilder._CurNsMgr, System.Xml.Schema.XdrBuilder._CurState, System.Xml.Schema.XdrBuilder._NameTable, System.Xml.Schema.XdrBuilder._SchemaNames, System.Xml.Schema.XdrBuilder._TargetNamespace, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Equals(), System.Xml.Schema.XdrBuilder.IsGlobal(), System.Xml.Schema.XdrBuilder.IsSkipableAttribute(), System.Xml.Schema.XdrBuilder.IsXdrSchema(), System.Xml.Schema.XdrBuilder.LoadSchema(), System.Xml.Schema.SchemaNames.NsXmlNs, System.Xml.XmlQualifiedName.Parse(), System.prefix, System.SR.Sch_UnsupportedAttribute, System.Xml.Schema.XdrBuilder.SendValidationEvent(), System.Xml.Schema.SchemaNames.TokenToQName, System.Xml.XmlQualifiedName.ToString(), System.value, System.Xml.Schema.XmlSchemaDatatype.XdrCanonizeUri(), System.SR.Xml_UnexpectedToken, and System.Xml.XmlException.