Terraria: WorkshopSocialModule.Initialize
Initialize() [2/2]
override void WorkshopSocialModule.Initialize () inline
Implements ISocialModule.
     {
         base.Branding = new WorkshopBranding
         {
             ResourcePackBrand = ResourcePack.BrandingType.SteamWorkshop
         };
         _publisherInstances = new List<WorkshopHelper.UGCBased.APublisherInstance>();
         base.ProgressReporter = new WorkshopProgressReporter(_publisherInstances);
         base.SupportedTags = new SupportedWorkshopTags();
         _contentBaseFolder = Main.SavePath + Path.DirectorySeparatorChar + "Workshop";
         _downloader = WorkshopHelper.UGCBased.Downloader.Create();
         _publishedItems = WorkshopHelper.UGCBased.PublishedItemsFinder.Create();
         WorkshopIssueReporter workshopIssueReporter = new WorkshopIssueReporter();
         workshopIssueReporter.OnNeedToOpenUI += _issueReporter_OnNeedToOpenUI;
         workshopIssueReporter.OnNeedToNotifyUI += _issueReporter_OnNeedToNotifyUI;
         base.IssueReporter = workshopIssueReporter;
         UIWorkshopHub.OnWorkshopHubMenuOpened += RefreshSubscriptionsAndPublishings;
     }
References _contentBaseFolder, _downloader, _issueReporter_OnNeedToNotifyUI(), _issueReporter_OnNeedToOpenUI(), _publishedItems, _publisherInstances, WorkshopHelper.UGCBased.Downloader.Create(), WorkshopHelper.UGCBased.PublishedItemsFinder.Create(), WorkshopIssueReporter.OnNeedToNotifyUI, WorkshopIssueReporter.OnNeedToOpenUI, UIWorkshopHub.OnWorkshopHubMenuOpened, RefreshSubscriptionsAndPublishings(), and Main.SavePath.