Terraria: System.ComponentModel.EnumConverter.GetStandardValues
GetStandardValues() [2/2]
override StandardValuesCollection System.ComponentModel.EnumConverter.GetStandardValues (ITypeDescriptorContext? context) inline virtual
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 177 of file EnumConverter.cs.
    {
        if (Values == null)
        {
            Type type = TypeDescriptor.GetReflectionType(EnumType) ?? EnumType;
            FieldInfo[] fields = type.GetFields(BindingFlags.Static | BindingFlags.Public);
            ArrayList arrayList = null;
            if (fields != null && fields.Length != 0)
            {
                arrayList = new ArrayList(fields.Length);
            }
            if (arrayList != null)
            {
                FieldInfo[] array = fields;
                foreach (FieldInfo fieldInfo in array)
                {
                    BrowsableAttribute browsableAttribute = null;
                    object[] customAttributes = fieldInfo.GetCustomAttributes(typeof(BrowsableAttribute), inherit: false);
                    for (int j = 0; j < customAttributes.Length; j++)
                    {
                        Attribute attribute = (Attribute)customAttributes[j];
                        browsableAttribute = attribute as BrowsableAttribute;
                    }
                    if (browsableAttribute != null && !browsableAttribute.Browsable)
                    {
                        continue;
                    }
                    object obj = null;
                    try
                    {
                        if (fieldInfo.Name != null)
{
                            obj = Enum.Parse(EnumType, fieldInfo.Name);
                        }
                    }
                    catch (ArgumentException)
                    {
                    }
                    if (obj != null)
                    {
                        arrayList.Add(obj);
                    }
                }
                IComparer comparer = Comparer;
                if (comparer != null)
                {
                    arrayList.Sort(comparer);
                }
            }
            Array values = arrayList?.ToArray();
            Values = new StandardValuesCollection(values);
        }
        return Values;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.ComponentModel.EnumConverter.Comparer, System.comparer, System.ComponentModel.EnumConverter.EnumType, System.ComponentModel.TypeDescriptor.GetReflectionType(), System.obj, System.Enum.Parse(), System.type, System.ComponentModel.EnumConverter.Values, and System.values.