Terraria: System.ComponentModel.EnumConverter.ConvertTo
ConvertTo() [1/2]
override? object System.ComponentModel.EnumConverter.ConvertTo (ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType) inline virtual
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 90 of file EnumConverter.cs.
    {
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        if (destinationType == typeof(string) && value != null)
        {
            if (!EnumType.IsDefined(typeof(FlagsAttribute), inherit: false) && !Enum.IsDefined(EnumType, value))
            {
                throw new ArgumentException(System.SR.Format(System.SR.EnumConverterInvalidValue, value, EnumType.Name));
            }
            return Enum.Format(EnumType, value, "G");
        }
        if (destinationType == typeof(InstanceDescriptor) && value != null)
        {
            string text = ConvertToInvariantString(context, value);
            if (EnumType.IsDefined(typeof(FlagsAttribute), inherit: false) && text.Contains(','))
            {
                Type underlyingType = Enum.GetUnderlyingType(EnumType);
                if (value is IConvertible)
                {
                    object obj = ((IConvertible)value).ToType(underlyingType, culture);
                    MethodInfo method = typeof(Enum).GetMethod("ToObject", new Type[2]
                    {
                        typeof(Type),
                        underlyingType
                    });
                    if (method != null)
                    {
                        return new InstanceDescriptor(method, new object[2] { EnumType, obj });
                    }
                }
            }
            else
            {
                FieldInfo field = EnumType.GetField(text);
                if (field != null)
                {
                    return new InstanceDescriptor(field, null);
                }
            }
        }
        if (destinationType == typeof(Enum[]) && value != null)
        {
            if (EnumType.IsDefined(typeof(FlagsAttribute), inherit: false))
            {
                bool isUnderlyingTypeUInt = Enum.GetUnderlyingType(EnumType) == typeof(ulong);
                List<Enum> list = new List<Enum>();
                Array values = Enum.GetValues(EnumType);
                long[] array = new long[values.Length];
                for (int i = 0; i < values.Length; i++)
                {
                    array[i] = GetEnumValue(isUnderlyingTypeUInt, (Enum)values.GetValue(i), culture);
                }
                long num = GetEnumValue(isUnderlyingTypeUInt, (Enum)value, culture);
                bool flag = true;
                while (flag)
                {
                    flag = false;
                    long[] array2 = array;
                    foreach (long num2 in array2)
                    {
                        if ((num2 != 0L && (num2 & num) == num2) || num2 == num)
{
                            list.Add((Enum)Enum.ToObject(EnumType, num2));
                            flag = true;
                            num &= ~num2;
                            break;
                        }
                    }
                    if (num == 0L)
                    {
                        break;
                    }
                }
                if (!flag && num != 0L)
                {
                    list.Add((Enum)Enum.ToObject(EnumType, num));
                }
                return list.ToArray();
            }
            return new Enum[1] { (Enum)Enum.ToObject(EnumType, value) };
        }
        return base.ConvertTo(context, culture, value, destinationType);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.ComponentModel.TypeConverter.ConvertToInvariantString(), System.culture, System.Enum, System.SR.EnumConverterInvalidValue, System.ComponentModel.EnumConverter.EnumType, System.SR.Format(), System.Enum.Format(), System.ComponentModel.EnumConverter.GetEnumValue(), System.Type.GetField(), System.Enum.GetUnderlyingType(), System.Enum.GetValues(), System.Reflection.MemberInfo.IsDefined(), System.Enum.IsDefined(), System.L, System.list, System.Reflection.MemberInfo.Name, System.obj, System.text, System.Enum.ToObject(), System.value, and System.values.