Terraria: System.ComponentModel.EnumConverter.ConvertFrom
ConvertFrom() [1/2]
override? object System.ComponentModel.EnumConverter.ConvertFrom (ITypeDescriptorContext? context, CultureInfo? culture, object value) inline virtual
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 51 of file EnumConverter.cs.
    {
        if (value is string text)
        {
            try
            {
                if (text.Contains(','))
                {
                    bool isUnderlyingTypeUInt = Enum.GetUnderlyingType(EnumType) == typeof(ulong);
                    long num = 0L;
                    string[] array = text.Split(',');
                    string[] array2 = array;
                    foreach (string value2 in array2)
                    {
                        num |= GetEnumValue(isUnderlyingTypeUInt, (Enum)Enum.Parse(EnumType, value2, ignoreCase: true), culture);
                    }
                    return Enum.ToObject(EnumType, num);
                }
                return Enum.Parse(EnumType, text, ignoreCase: true);
            }
            catch (Exception innerException)
            {
                throw new FormatException(System.SR.Format(System.SR.ConvertInvalidPrimitive, (string)value, EnumType.Name), innerException);
            }
        }
        if (value is Enum[])
        {
            bool isUnderlyingTypeUInt2 = Enum.GetUnderlyingType(EnumType) == typeof(ulong);
            long num2 = 0L;
            Enum[] array3 = (Enum[])value;
            foreach (Enum enumVal in array3)
            {
                num2 |= GetEnumValue(isUnderlyingTypeUInt2, enumVal, culture);
            }
            return Enum.ToObject(EnumType, num2);
        }
        return base.ConvertFrom(context, culture, value);
    }
References System.array, System.SR.ConvertInvalidPrimitive, System.culture, System.ComponentModel.EnumConverter.EnumType, System.SR.Format(), System.ComponentModel.EnumConverter.GetEnumValue(), System.Enum.GetUnderlyingType(), System.L, System.Reflection.MemberInfo.Name, System.Enum.Parse(), System.text, System.Enum.ToObject(), and System.value.