Terraria: System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63.MoveNext
MoveNext() [1/2]
void System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext () inline private
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 94 of file ManagedWebSocket.cs.
        {
            int num = _003C_003E1__state;
            ManagedWebSocket managedWebSocket = _003C_003E4__this;
            TResult receiveResult;
            try
            {
                if ((uint)num > 7u)
                {
                    _003Cregistration_003E5__2 = cancellationToken.Register(delegate(object s)
                    {
                        ((ManagedWebSocket)s).Abort();
                    }, managedWebSocket);
                }
                try
                {
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter awaiter;
                    if (num != 0)
                    {
                        if ((uint)(num - 1) <= 6u)
{
                            goto IL_00be;
                        }
                        awaiter = managedWebSocket._receiveMutex.EnterAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                        if (!awaiter.IsCompleted)
{
                            num = (_003C_003E1__state = 0);
                            _003C_003Eu__1 = awaiter;
                            _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        awaiter = _003C_003Eu__1;
                        _003C_003Eu__1 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num = (_003C_003E1__state = -1);
                    }
                    awaiter.GetResult();
                    goto IL_00be;
                    IL_00be:
                    try
                    {
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter8;
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter7;
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter6;
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter5;
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter4;
                        ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter awaiter3;
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter awaiter2;
                        Span<byte> span;
                        int result;
                        int num2;
                        long num4;
                        string text;
                        switch (num)
{
                        default:
                            _003Cheader_003E5__3 = managedWebSocket._lastReceiveHeader;
                            if (_003Cheader_003E5__3.Processed)
{
                                if (managedWebSocket._receiveBufferCount < (managedWebSocket._isServer ? 14 : 10))
{
                                    if (managedWebSocket._receiveBufferCount < 2)
{
                                        awaiter8 = managedWebSocket.EnsureBufferContainsAsync(2, cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                                        if (!awaiter8.IsCompleted)
{
                                            num = (_003C_003E1__state = 1);
                                            _003C_003Eu__2 = awaiter8;
                                            _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter8, ref this);
                                            return;
                                        }
                                        goto IL_018d;
                                    }
                                    goto IL_0194;
                                }
                                goto IL_0264;
                            }
                            goto IL_0323;
                        case 1:
                            awaiter8 = _003C_003Eu__2;
                            _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (_003C_003E1__state = -1);
                            goto IL_018d;
                        case 2:
                            awaiter7 = _003C_003Eu__2;
                            _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (_003C_003E1__state = -1);
                            goto IL_025d;
                        case 3:
                            awaiter6 = _003C_003Eu__2;
                            _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (_003C_003E1__state = -1);
                            goto IL_02e4;
                        case 4:
                            awaiter5 = _003C_003Eu__2;
                            _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (_003C_003E1__state = -1);
                            goto IL_03b2;
                        case 5:
                            awaiter4 = _003C_003Eu__2;
                            _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (_003C_003E1__state = -1);
                            goto IL_0440;
                        case 6:
                            awaiter3 = _003C_003Eu__3;
                            _003C_003Eu__3 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                            num = (_003C_003E1__state = -1);
                            goto IL_06b5;
                        case 7:
{
                                awaiter2 = _003C_003Eu__2;
                                _003C_003Eu__2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                                num = (_003C_003E1__state = -1);
                                goto IL_08c1;
                            }
                            IL_06f0:
                            if (managedWebSocket._isServer)
{
                                Span<byte> toMask;
                                if (!_003Cheader_003E5__3.Compressed)
{
                                    span = payloadBuffer.Span;
                                    toMask = span.Slice(0, _003CtotalBytesReceived_003E5__4);
                                }
                                else
{
                                    span = managedWebSocket._inflater.Span;
                                    toMask = span.Slice(0, _003CtotalBytesReceived_003E5__4);
                                }
                                managedWebSocket._receivedMaskOffsetOffset = ApplyMask(toMask, _003Cheader_003E5__3.Mask, managedWebSocket._receivedMaskOffsetOffset);
                            }
                            _003Cheader_003E5__3.PayloadLength -= _003CtotalBytesReceived_003E5__4;
                            if (_003Cheader_003E5__3.Compressed)
{
                                managedWebSocket._inflater.AddBytes(_003CtotalBytesReceived_003E5__4, _003Cheader_003E5__3.Fin && _003Cheader_003E5__3.PayloadLength == 0);
                            }
                            goto IL_07ac;
                            IL_06b5:
                            result = awaiter3.GetResult();
                            num2 = result;
                            if (num2 <= 0)
{
                                managedWebSocket.ThrowIfEOFUnexpected(throwOnPrematureClosure: true);
                                goto IL_06f0;
                            }
                            _003CtotalBytesReceived_003E5__4 += num2;
                            goto IL_06df;
                            IL_0323:
                            if (_003Cheader_003E5__3.Opcode == MessageOpcode.Ping || _003Cheader_003E5__3.Opcode == MessageOpcode.Pong)
{
                                awaiter5 = managedWebSocket.HandleReceivedPingPongAsync(_003Cheader_003E5__3, cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                                if (!awaiter5.IsCompleted)
{
                                    num = (_003C_003E1__state = 4);
                                    _003C_003Eu__2 = awaiter5;
                                    _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter5, ref this);
                                    return;
                                }
                                goto IL_03b2;
                            }
                            if (_003Cheader_003E5__3.Opcode == MessageOpcode.Close)
{
                                awaiter4 = managedWebSocket.HandleReceivedCloseAsync(_003Cheader_003E5__3, cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                                if (!awaiter4.IsCompleted)
{
                                    num = (_003C_003E1__state = 5);
                                    _003C_003Eu__2 = awaiter4;
                                    _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter4, ref this);
                                    return;
                                }
                                goto IL_0440;
                            }
                            if (_003Cheader_003E5__3.Opcode == MessageOpcode.Continuation)
{
                                _003Cheader_003E5__3.Opcode = managedWebSocket._lastReceiveHeader.Opcode;
                                _003Cheader_003E5__3.Compressed = managedWebSocket._lastReceiveHeader.Compressed;
                            }
                            if (!_003Cheader_003E5__3.Processed && payloadBuffer.Length != 0)
{
                                _003CtotalBytesReceived_003E5__4 = 0;
                                if (_003Cheader_003E5__3.PayloadLength > 0)
{
                                    if (_003Cheader_003E5__3.Compressed)
{
                                        managedWebSocket._inflater.Prepare(_003Cheader_003E5__3.PayloadLength, payloadBuffer.Length);
                                    }
                                    int length;
                                    if (!_003Cheader_003E5__3.Compressed)
{
                                        length = payloadBuffer.Length;
                                    }
                                    else
{
                                        span = managedWebSocket._inflater.Span;
                                        length = span.Length;
                                    }
                                    _003Climit_003E5__5 = (int)Math.Min(length, _003Cheader_003E5__3.PayloadLength);
                                    if (managedWebSocket._receiveBufferCount > 0)
{
                                        int num3 = Math.Min(_003Climit_003E5__5, managedWebSocket._receiveBufferCount);
                                        span = managedWebSocket._receiveBuffer.Span;
                                        span = span.Slice(managedWebSocket._receiveBufferOffset, num3);
                                        span.CopyTo(_003Cheader_003E5__3.Compressed ? managedWebSocket._inflater.Span : payloadBuffer.Span);
                                        managedWebSocket.ConsumeFromBuffer(num3);
                                        _003CtotalBytesReceived_003E5__4 += num3;
                                    }
                                    goto IL_06df;
                                }
                                goto IL_07ac;
                            }
                            managedWebSocket._lastReceiveHeader = _003Cheader_003E5__3;
                            receiveResult = managedWebSocket.GetReceiveResult<TResult>(0, (_003Cheader_003E5__3.Opcode != MessageOpcode.Text) ? WebSocketMessageType.Binary : WebSocketMessageType.Text, _003Cheader_003E5__3.EndOfMessage);
                            goto end_IL_00be;
                            IL_07ac:
                            if (_003Cheader_003E5__3.Compressed)
{
                                _003Cheader_003E5__3.Processed = managedWebSocket._inflater.Inflate(payloadBuffer.Span, out _003CtotalBytesReceived_003E5__4) && _003Cheader_003E5__3.PayloadLength == 0;
                            }
                            else
{
                                _003Cheader_003E5__3.Processed = _003Cheader_003E5__3.PayloadLength == 0;
                            }
                            if (_003Cheader_003E5__3.Opcode != MessageOpcode.Text)
{
                                break;
                            }
                            span = payloadBuffer.Span;
                            if (TryValidateUtf8(span.Slice(0, _003CtotalBytesReceived_003E5__4), _003Cheader_003E5__3.EndOfMessage, managedWebSocket._utf8TextState))
{
                                break;
                            }
                            awaiter2 = managedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus.InvalidPayloadData, WebSocketError.Faulted).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                            if (!awaiter2.IsCompleted)
{
                                num = (_003C_003E1__state = 7);
                                _003C_003Eu__2 = awaiter2;
                                _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter2, ref this);
                                return;
                            }
                            goto IL_08c1;
                            IL_06df:
                            if (_003CtotalBytesReceived_003E5__4 < _003Climit_003E5__5)
{
                                awaiter3 = managedWebSocket._stream.ReadAsync(_003Cheader_003E5__3.Compressed ? managedWebSocket._inflater.Memory.Slice(_003CtotalBytesReceived_003E5__4, _003Climit_003E5__5 - _003CtotalBytesReceived_003E5__4) : payloadBuffer.Slice(_003CtotalBytesReceived_003E5__4, _003Climit_003E5__5 - _003CtotalBytesReceived_003E5__4), cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                                if (!awaiter3.IsCompleted)
{
                                    num = (_003C_003E1__state = 6);
                                    _003C_003Eu__3 = awaiter3;
                                    _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter3, ref this);
                                    return;
                                }
                                goto IL_06b5;
                            }
                            goto IL_06f0;
                            IL_03b2:
                            awaiter5.GetResult();
                            goto default;
                            IL_025d:
                            awaiter7.GetResult();
                            goto IL_0264;
                            IL_018d:
                            awaiter8.GetResult();
                            goto IL_0194;
                            IL_0194:
                            span = managedWebSocket._receiveBuffer.Span;
                            num4 = span[managedWebSocket._receiveBufferOffset + 1] & 0x7F;
                            if (managedWebSocket._isServer || num4 > 125)
{
                                int minimumRequiredBytes = 2 + (managedWebSocket._isServer ? 4 : 0) + ((num4 > 125) ? ((num4 == 126) ? 2 : 8) : 0);
                                awaiter7 = managedWebSocket.EnsureBufferContainsAsync(minimumRequiredBytes, cancellationToken).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                                if (!awaiter7.IsCompleted)
{
                                    num = (_003C_003E1__state = 2);
                                    _003C_003Eu__2 = awaiter7;
                                    _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter7, ref this);
                                    return;
                                }
                                goto IL_025d;
                            }
                            goto IL_0264;
                            IL_08c1:
                            awaiter2.GetResult();
                            break;
                            IL_0264:
                            text = managedWebSocket.TryParseMessageHeaderFromReceiveBuffer(out _003Cheader_003E5__3);
                            if (text != null)
{
                                awaiter6 = managedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus.ProtocolError, WebSocketError.Faulted, text).ConfigureAwait(continueOnCapturedContext: false).GetAwaiter();
                                if (!awaiter6.IsCompleted)
{
                                    num = (_003C_003E1__state = 3);
                                    _003C_003Eu__2 = awaiter6;
                                    _003C_003Et__builder.AwaitUnsafeOnCompleted(ref awaiter6, ref this);
                                    return;
                                }
                                goto IL_02e4;
                            }
                            goto IL_02eb;
                            IL_02e4:
                            awaiter6.GetResult();
                            goto IL_02eb;
                            IL_02eb:
                            managedWebSocket._receivedMaskOffsetOffset = 0;
                            if (_003Cheader_003E5__3.PayloadLength == 0L && _003Cheader_003E5__3.Compressed)
{
                                managedWebSocket._inflater.AddBytes(0, _003Cheader_003E5__3.Fin);
                            }
                            goto IL_0323;
                            IL_0440:
                            awaiter4.GetResult();
                            receiveResult = managedWebSocket.GetReceiveResult<TResult>(0, WebSocketMessageType.Close, endOfMessage: true);
                            goto end_IL_00be;
                        }
                        managedWebSocket._lastReceiveHeader = _003Cheader_003E5__3;
                        receiveResult = managedWebSocket.GetReceiveResult<TResult>(_003CtotalBytesReceived_003E5__4, (_003Cheader_003E5__3.Opcode != MessageOpcode.Text) ? WebSocketMessageType.Binary : WebSocketMessageType.Text, _003Cheader_003E5__3.EndOfMessage);
                        end_IL_00be:;
                    }
                    finally
                    {
                        if (num < 0)
{
                            managedWebSocket._receiveMutex.Exit();
                        }
                    }
                }
                catch (Exception ex) when (!(ex is OperationCanceledException))
                {
                    if (managedWebSocket._state == WebSocketState.Aborted)
                    {
                        throw new OperationCanceledException("Aborted", ex);
                    }
                    managedWebSocket.OnAborted();
                    if (ex is WebSocketException)
                    {
                        throw;
                    }
                    throw new WebSocketException(WebSocketError.ConnectionClosedPrematurely, ex);
                }
                finally
                {
                    if (num < 0)
                    {
                        _003Cregistration_003E5__2.Dispose();
                    }
                }
            }
            catch (Exception exception)
            {
                _003C_003E1__state = -2;
                _003Cregistration_003E5__2 = default(CancellationTokenRegistration);
                _003C_003Et__builder.SetException(exception);
                return;
            }
            _003C_003E1__state = -2;
            _003Cregistration_003E5__2 = default(CancellationTokenRegistration);
            _003C_003Et__builder.SetResult(receiveResult);
        }
References System.Net.WebSockets.ManagedWebSocket.ManagedWebSocket(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003C_003E1__state, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003C_003E4__this, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003C_003Et__builder, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003C_003Eu__1, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003C_003Eu__2, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003C_003Eu__3, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003Cheader_003E5__3, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003Climit_003E5__5, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003Cregistration_003E5__2, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >._003CtotalBytesReceived_003E5__4, System.Net.WebSockets.ManagedWebSocket._inflater, System.Net.WebSockets.ManagedWebSocket._isServer, System.Net.WebSockets.ManagedWebSocket._lastReceiveHeader, System.Net.WebSockets.ManagedWebSocket._receiveBuffer, System.Net.WebSockets.ManagedWebSocket._receiveBufferCount, System.Net.WebSockets.ManagedWebSocket._receiveBufferOffset, System.Net.WebSockets.ManagedWebSocket._receivedMaskOffsetOffset, System.Net.WebSockets.ManagedWebSocket._receiveMutex, System.Net.WebSockets.ManagedWebSocket._state, System.Net.WebSockets.ManagedWebSocket._stream, System.Net.WebSockets.ManagedWebSocket._utf8TextState, System.Net.WebSockets.Compression.WebSocketInflater.AddBytes(), System.Net.WebSockets.ManagedWebSocket.ApplyMask(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.cancellationToken, System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.Compressed, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.WebSockets.ManagedWebSocket.ConsumeFromBuffer(), System.Span< T >.CopyTo(), System.Threading.CancellationTokenRegistration.Dispose(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.EndOfMessage, System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(), System.Threading.AsyncMutex.EnterAsync(), System.exception, System.Threading.AsyncMutex.Exit(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.Fin, System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(), System.Net.WebSockets.ManagedWebSocket.HandleReceivedPingPongAsync(), System.Net.WebSockets.Compression.WebSocketInflater.Inflate(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted, System.L, System.length, System.Memory< T >.Length, System.Span< T >.Length, System.Net.WebSockets.ManagedWebSocket.MessageHeader.Mask, System.Net.WebSockets.Compression.WebSocketInflater.Memory, System.Math.Min(), System.Net.WebSockets.ManagedWebSocket.OnAborted(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.Opcode, System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.payloadBuffer, System.Net.WebSockets.ManagedWebSocket.MessageHeader.PayloadLength, System.Net.WebSockets.Compression.WebSocketInflater.Prepare(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.Processed, System.IO.Stream.ReadAsync(), System.Threading.CancellationToken.Register(), System.s, System.Memory< T >.Slice(), System.Span< T >.Slice(), System.Net.WebSockets.Compression.WebSocketInflater.Span, System.Memory< T >.Span, System.text, System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(), System.Net.WebSockets.ManagedWebSocket.TryParseMessageHeaderFromReceiveBuffer(), and System.Net.WebSockets.ManagedWebSocket.TryValidateUtf8().
Referenced by System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext().