Terraria: System.Net.Mail.SmtpConnection.BeginFlush
BeginFlush()
IAsyncResult System.Net.Mail.SmtpConnection.BeginFlush (AsyncCallback callback, object state) inline package
Definition at line 614 of file SmtpConnection.cs.
    {
        return _networkStream.BeginWrite(_bufferBuilder.GetBuffer(), 0, _bufferBuilder.Length, callback, state);
    }
References System.Net.Mail.SmtpConnection._bufferBuilder, System.Net.Mail.SmtpConnection._networkStream, System.Net.Sockets.NetworkStream.BeginWrite(), System.Net.Mail.BufferBuilder.GetBuffer(), System.Net.Mail.BufferBuilder.Length, and System.state.
Referenced by System.Net.Mail.CheckCommand.BeginSend(), and System.Net.Mail.ReadLinesCommand.BeginSend().