Terraria: System.Net.Mail.SmtpConnection.ParseExtensions
ParseExtensions()
void System.Net.Mail.SmtpConnection.ParseExtensions (string[] extensions) inline package
Definition at line 814 of file SmtpConnection.cs.
    {
        _supportedAuth = SupportedAuth.None;
        foreach (string text in extensions)
        {
            if (string.Compare(text, 0, "auth", 0, 4, StringComparison.OrdinalIgnoreCase) == 0)
            {
                string[] array = text.Remove(0, 4).Split(s_authExtensionSplitters, StringSplitOptions.RemoveEmptyEntries);
                string[] array2 = array;
                foreach (string a in array2)
                {
                    if (string.Equals(a, "login", StringComparison.OrdinalIgnoreCase))
                    {
                        _supportedAuth |= SupportedAuth.Login;
                    }
                    else if (string.Equals(a, "ntlm", StringComparison.OrdinalIgnoreCase))
                    {
                        _supportedAuth |= SupportedAuth.NTLM;
                    }
                    else if (string.Equals(a, "gssapi", StringComparison.OrdinalIgnoreCase))
                    {
                        _supportedAuth |= SupportedAuth.GSSAPI;
                    }
                }
            }
            else if (string.Compare(text, 0, "dsn ", 0, 3, StringComparison.OrdinalIgnoreCase) == 0)
            {
                _dsnEnabled = true;
            }
            else if (string.Compare(text, 0, "STARTTLS", 0, 8, StringComparison.OrdinalIgnoreCase) == 0)
            {
                _serverSupportsStartTls = true;
            }
            else if (string.Compare(text, 0, "SMTPUTF8", 0, 8, StringComparison.OrdinalIgnoreCase) == 0)
            {
                _serverSupportsEai = true;
            }
        }
    }
References System.Net.Mail.SmtpConnection._dsnEnabled, System.Net.Mail.SmtpConnection._serverSupportsEai, System.Net.Mail.SmtpConnection._serverSupportsStartTls, System.Net.Mail.SmtpConnection._supportedAuth, System.array, System.Net.Equals, System.Net.Mail.SmtpConnection.s_authExtensionSplitters, and System.text.
Referenced by System.Net.Mail.SmtpConnection.GetConnection(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHello(), and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendEHelloCallback().