Terraria: System.Net.Mail.SmtpConnection.Flush
Flush()
void System.Net.Mail.SmtpConnection.Flush () inline package
Definition at line 625 of file SmtpConnection.cs.
    {
        _networkStream.Write(_bufferBuilder.GetBuffer(), 0, _bufferBuilder.Length);
        _bufferBuilder.Reset();
    }
References System.Net.Mail.SmtpConnection._bufferBuilder, System.Net.Mail.SmtpConnection._networkStream, System.Net.Mail.BufferBuilder.GetBuffer(), System.Net.Mail.BufferBuilder.Length, System.Net.Mail.BufferBuilder.Reset(), and System.Net.Sockets.NetworkStream.Write().
Referenced by System.Net.Mail.QuitCommand.Send(), System.Net.Mail.ReadLinesCommand.Send(), and System.Net.Mail.CheckCommand.Send().