Terraria: System.Net.Mail.SmtpConnection.EndInitializeConnection
EndInitializeConnection()
void System.Net.Mail.SmtpConnection.EndInitializeConnection (IAsyncResult result) inline package
Definition at line 601 of file SmtpConnection.cs.
    {
        _tcpClient.EndConnect(result);
        _networkStream = _tcpClient.GetStream();
    }
References System.Net.Mail.SmtpConnection._networkStream, System.Net.Mail.SmtpConnection._tcpClient, System.Net.Sockets.TcpClient.EndConnect(), and System.Net.Sockets.TcpClient.GetStream().
Referenced by System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnection(), and System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback().