Terraria: System.Net.Mail.SmtpConnection.GetConnection
GetConnection()
void System.Net.Mail.SmtpConnection.GetConnection (string host, int port) inline package
Definition at line 682 of file SmtpConnection.cs.
    {
        if (_isConnected)
        {
            throw new InvalidOperationException(System.SR.SmtpAlreadyConnected);
        }
        InitializeConnection(host, port);
        _responseReader = new SmtpReplyReaderFactory(_networkStream);
        LineInfo lineInfo = _responseReader.GetNextReplyReader().ReadLine();
        SmtpStatusCode statusCode = lineInfo.StatusCode;
        if (statusCode != SmtpStatusCode.ServiceReady)
        {
            throw new SmtpException(lineInfo.StatusCode, lineInfo.Line, serverResponse: true);
        }
        try
        {
            _extensions = EHelloCommand.Send(this, _client._clientDomain);
            ParseExtensions(_extensions);
        }
        catch (SmtpException ex)
        {
            if (ex.StatusCode != SmtpStatusCode.CommandUnrecognized && ex.StatusCode != SmtpStatusCode.CommandNotImplemented)
            {
                throw;
            }
            HelloCommand.Send(this, _client._clientDomain);
            _supportedAuth = SupportedAuth.Login;
        }
        if (_enableSsl)
        {
            if (!_serverSupportsStartTls && !(_networkStream is System.Net.TlsStream))
            {
                throw new SmtpException(System.SR.MailServerDoesNotSupportStartTls);
            }
            StartTlsCommand.Send(this);
            System.Net.TlsStream tlsStream = new System.Net.TlsStream(_networkStream, _tcpClient.Client, host, _clientCertificates);
            tlsStream.AuthenticateAsClient();
            _networkStream = tlsStream;
            _responseReader = new SmtpReplyReaderFactory(_networkStream);
            _extensions = EHelloCommand.Send(this, _client._clientDomain);
            ParseExtensions(_extensions);
        }
        if (_credentials != null)
        {
            for (int i = 0; i < _authenticationModules.Length; i++)
            {
                if (!AuthSupported(_authenticationModules[i]))
                {
                    continue;
                }
                NetworkCredential credential = _credentials.GetCredential(host, port, _authenticationModules[i].AuthenticationType);
                if (credential == null)
                {
                    continue;
                }
                Authorization authorization = SetContextAndTryAuthenticate(_authenticationModules[i], credential, null);
                if (authorization == null || authorization.Message == null)
                {
                    continue;
                }
                lineInfo = AuthCommand.Send(this, _authenticationModules[i].AuthenticationType, authorization.Message);
                if (lineInfo.StatusCode == SmtpStatusCode.CommandParameterNotImplemented)
                {
                    continue;
                }
                while (lineInfo.StatusCode == (SmtpStatusCode)334)
                {
                    authorization = _authenticationModules[i].Authenticate(lineInfo.Line, null, this, _client.TargetName, null);
                    if (authorization == null)
                    {
                        throw new SmtpException(System.SR.SmtpAuthenticationFailed);
                    }
                    lineInfo = AuthCommand.Send(this, authorization.Message);
                    if (lineInfo.StatusCode == (SmtpStatusCode)235)
                    {
                        _authenticationModules[i].CloseContext(this);
                        _isConnected = true;
                        return;
                    }
                }
            }
        }
        _isConnected = true;
    }
References System.Net.Mail.SmtpConnection._authenticationModules, System.Net.Mail.SmtpConnection._client, System.Net.Mail.SmtpConnection._clientCertificates, System.Net.Mail.SmtpClient._clientDomain, System.Net.Mail.SmtpConnection._credentials, System.Net.Mail.SmtpConnection._enableSsl, System.Net.Mail.SmtpConnection._extensions, System.Net.Mail.SmtpConnection._isConnected, System.Net.Mail.SmtpConnection._networkStream, System.Net.Mail.SmtpConnection._responseReader, System.Net.Mail.SmtpConnection._serverSupportsStartTls, System.Net.Mail.SmtpConnection._supportedAuth, System.Net.Mail.SmtpConnection._tcpClient, System.Net.Mail.ISmtpAuthenticationModule.Authenticate(), System.Net.TlsStream.AuthenticateAsClient(), System.Net.Mail.SmtpConnection.AuthSupported(), System.Net.Sockets.TcpClient.Client, System.Net.Mail.ISmtpAuthenticationModule.CloseContext(), System.Net.ICredentialsByHost.GetCredential(), System.Net.Mail.SmtpReplyReaderFactory.GetNextReplyReader(), System.Net.Mail.SmtpConnection.InitializeConnection(), System.Net.Mail.LineInfo.Line, System.SR.MailServerDoesNotSupportStartTls, System.Net.Authorization.Message, System.Net.Mail.SmtpConnection.ParseExtensions(), System.Net.Mail.SmtpReplyReader.ReadLine(), System.Net.Mail.StartTlsCommand.Send(), System.Net.Mail.EHelloCommand.Send(), System.Net.Mail.HelloCommand.Send(), System.Net.Mail.AuthCommand.Send(), System.Net.Mail.SmtpConnection.SetContextAndTryAuthenticate(), System.SR.SmtpAlreadyConnected, System.SR.SmtpAuthenticationFailed, System.Net.Mail.LineInfo.StatusCode, System.Net.Mail.SmtpException.StatusCode, and System.Net.Mail.SmtpClient.TargetName.
Referenced by System.Net.Mail.SmtpTransport.GetConnection().