Terraria: System.Net.Mail.SmtpConnection.ShutdownConnection
ShutdownConnection()
void System.Net.Mail.SmtpConnection.ShutdownConnection (bool isAbort) inline private
Definition at line 631 of file SmtpConnection.cs.
    {
        if (!_isClosed)
        {
            lock (this)
            {
                if (!_isClosed && _tcpClient != null)
                {
                    try
                    {
                        try
{
                            if (isAbort)
{
                                _tcpClient.LingerState = new LingerOption(enable: true, 0);
                            }
                            else
{
                                _tcpClient.Client.Blocking = false;
                                QuitCommand.Send(this);
                            }
                        }
                        finally
{
                            _networkStream?.Close();
                            _tcpClient.Dispose();
                        }
                    }
                    catch (IOException)
                    {
                    }
                    catch (ObjectDisposedException)
                    {
                    }
                }
                _isClosed = true;
            }
        }
        _isConnected = false;
    }
References System.Net.Mail.SmtpConnection._isClosed, System.Net.Mail.SmtpConnection._isConnected, System.Net.Mail.SmtpConnection._networkStream, System.Net.Mail.SmtpConnection._tcpClient, System.Net.Sockets.NetworkStream.Close(), System.Net.Sockets.TcpClient.Dispose(), and System.Net.Mail.QuitCommand.Send().
Referenced by System.Net.Mail.SmtpConnection.Abort(), and System.Net.Mail.SmtpConnection.ReleaseConnection().