Terraria: System.Net.Mail.SmtpConnection.SetContextAndTryAuthenticate
SetContextAndTryAuthenticate()
Authorization System.Net.Mail.SmtpConnection.SetContextAndTryAuthenticate (ISmtpAuthenticationModule module, NetworkCredential credential, System::Net::ContextAwareResult context) inline private
Definition at line 767 of file SmtpConnection.cs.
    {
        if (credential == CredentialCache.DefaultNetworkCredentials)
        {
            try
            {
                ExecutionContext executionContext = context?.ContextCopy;
                if (executionContext != null)
                {
                    AuthenticateCallbackContext authenticateCallbackContext = new AuthenticateCallbackContext(this, module, credential, _client.TargetName, null);
                    ExecutionContext.Run(executionContext, s_AuthenticateCallback, authenticateCallbackContext);
                    return authenticateCallbackContext._result;
                }
                return module.Authenticate(null, credential, this, _client.TargetName, null);
            }
            catch
            {
                throw;
            }
        }
        return module.Authenticate(null, credential, this, _client.TargetName, null);
    }
References System.Net.Mail.SmtpConnection._client, System.Net.Mail.SmtpConnection.AuthenticateCallbackContext._result, System.Net.Mail.ISmtpAuthenticationModule.Authenticate(), System.Net.CredentialCache.DefaultNetworkCredentials, System.Threading.ExecutionContext.Run(), System.Net.Mail.SmtpConnection.s_AuthenticateCallback, and System.Net.Mail.SmtpClient.TargetName.
Referenced by System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.Authenticate(), and System.Net.Mail.SmtpConnection.GetConnection().