Terraria: System.Xml.Xsl.XmlQueryTypeFactory.SequenceType.Create
Create() [2/2]
static XmlQueryType System.Xml.Xsl.XmlQueryTypeFactory.SequenceType.Create (XmlQueryType prime, XmlQueryCardinality card) inline static
Definition at line 463 of file XmlQueryTypeFactory.cs.
        {
            if (prime.TypeCode == XmlTypeCode.None)
            {
                if (!(XmlQueryCardinality.Zero <= card))
                {
                    return None;
                }
                return Zero;
            }
            if (card == XmlQueryCardinality.None)
            {
                return None;
            }
            if (card == XmlQueryCardinality.Zero)
            {
                return Zero;
            }
            if (card == XmlQueryCardinality.One)
            {
                return prime;
            }
            return new SequenceType(prime, card);
        }
References System.Xml.Dictionary, System.Xml.Xsl.XmlQueryCardinality.None, System.Xml.Xsl.XmlQueryType.None, System.Xml.Xsl.XmlQueryCardinality.One, System.Xml.Xsl.XmlQueryCardinality.Zero, and System.Xml.Xsl.XmlQueryTypeFactory.SequenceType.Zero.
Referenced by System.Xml.Xsl.XmlQueryTypeFactory.Choice(), System.Xml.Xsl.XmlQueryTypeFactory.Choice(), System.Xml.Xsl.XmlQueryTypeFactory.Deserialize(), System.Xml.Xsl.XmlQueryTypeFactory.PrimeProduct(), and System.Xml.Xsl.XmlQueryTypeFactory.Sequence().