Terraria: System.Xml.Xsl.Runtime.XPathPrecedingIterator.Create
Create()
void System.Xml.Xsl.Runtime.XPathPrecedingIterator.Create (XPathNavigator context, XmlNavigatorFilter filter) inline
Definition at line 15 of file XPathPrecedingIterator.cs.
    {
        XPathPrecedingDocOrderIterator xPathPrecedingDocOrderIterator = default(XPathPrecedingDocOrderIterator);
        xPathPrecedingDocOrderIterator.Create(context, filter);
        _stack.Reset();
        while (xPathPrecedingDocOrderIterator.MoveNext())
        {
            _stack.Push(xPathPrecedingDocOrderIterator.Current.Clone());
        }
    }
References System.Xml.Xsl.Runtime.XPathPrecedingIterator._stack, System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.Create(), System.Xml.Dictionary, System.Xml.Xsl.Runtime.XmlNavigatorStack.Push(), and System.Xml.Xsl.Runtime.XmlNavigatorStack.Reset().