Terraria: System.Security.AccessControl.SystemAcl.AddAudit
AddAudit() [1/3]
void System.Security.AccessControl.SystemAcl.AddAudit (AuditFlags auditFlags, SecurityIdentifier sid, int accessMask, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags) inline
Definition at line 27 of file SystemAcl.cs.
    {
        CheckFlags(inheritanceFlags, propagationFlags);
        AddQualifiedAce(sid, AceQualifier.SystemAudit, accessMask, GenericAce.AceFlagsFromAuditFlags(auditFlags) | GenericAce.AceFlagsFromInheritanceFlags(inheritanceFlags, propagationFlags), ObjectAceFlags.None, Guid.Empty, Guid.Empty);
    }
References System.Security.AccessControl.GenericAce.AceFlagsFromAuditFlags(), System.Security.AccessControl.GenericAce.AceFlagsFromInheritanceFlags(), System.Security.AccessControl.CommonAcl.AddQualifiedAce(), System.Security.AccessControl.CommonAcl.CheckFlags(), and System.Guid.Empty.
Referenced by System.Security.AccessControl.SystemAcl.AddAudit(), and System.Security.AccessControl.CommonObjectSecurity.ModifyAudit().