Terraria: Internal.Cryptography.AesImplementation.CreateTransformCore
CreateTransformCore()
static UniversalCryptoTransform Internal.Cryptography.AesImplementation.CreateTransformCore (CipherMode cipherMode, PaddingMode paddingMode, byte[] key, byte[] iv, int blockSize, int paddingSize, int feedbackSize, bool encrypting) inline static private
Definition at line 134 of file AesImplementation.cs.
    {
        SafeAlgorithmHandle sharedHandle = AesBCryptModes.GetSharedHandle(cipherMode, feedbackSize);
        BasicSymmetricCipher cipher = new BasicSymmetricCipherBCrypt(sharedHandle, cipherMode, blockSize, paddingSize, key, ownsParentHandle: false, iv, encrypting);
        return UniversalCryptoTransform.Create(paddingMode, cipher, encrypting);
    }
References Internal.Cryptography.UniversalCryptoTransform.Create(), Internal.Cryptography.AesBCryptModes.GetSharedHandle(), and System.key.
Referenced by Internal.Cryptography.AesImplementation.CreateTransform(), Internal.Cryptography.AesImplementation.TryDecryptCbcCore(), Internal.Cryptography.AesImplementation.TryDecryptCfbCore(), Internal.Cryptography.AesImplementation.TryDecryptEcbCore(), Internal.Cryptography.AesImplementation.TryEncryptCbcCore(), Internal.Cryptography.AesImplementation.TryEncryptCfbCore(), and Internal.Cryptography.AesImplementation.TryEncryptEcbCore().