Terraria: System.Security.AccessControl.SystemAcl.RemoveAudit
RemoveAudit() [2/3]
bool System.Security.AccessControl.SystemAcl.RemoveAudit (AuditFlags auditFlags, SecurityIdentifier sid, int accessMask, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags, ObjectAceFlags objectFlags, Guid objectType, Guid inheritedObjectType) inline
Definition at line 84 of file SystemAcl.cs.
    {
        if (!base.IsDS)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_OnlyValidForDS);
        }
        return RemoveQualifiedAces(sid, AceQualifier.SystemAudit, accessMask, GenericAce.AceFlagsFromAuditFlags(auditFlags) | GenericAce.AceFlagsFromInheritanceFlags(inheritanceFlags, propagationFlags), saclSemantics: true, objectFlags, objectType, inheritedObjectType);
    }
References System.Security.AccessControl.GenericAce.AceFlagsFromAuditFlags(), System.Security.AccessControl.GenericAce.AceFlagsFromInheritanceFlags(), System.SR.InvalidOperation_OnlyValidForDS, and System.Security.AccessControl.CommonAcl.RemoveQualifiedAces().