Terraria: Internal.Cryptography.AesImplementation.CreateTransform
CreateTransform()
ICryptoTransform Internal.Cryptography.AesImplementation.CreateTransform (byte[] rgbKey, byte[] rgbIV, bool encrypting) inline private
Definition at line 100 of file AesImplementation.cs.
    {
        if (rgbKey == null)
        {
            throw new ArgumentNullException("rgbKey");
        }
        long num = (long)rgbKey.Length * 8L;
        if (num > int.MaxValue || !((int)num).IsLegalSize(LegalKeySizes))
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidKeySize, "rgbKey");
        }
        if (rgbIV != null)
        {
            long num2 = (long)rgbIV.Length * 8L;
            if (num2 != BlockSize)
            {
                throw new ArgumentException(System.SR.Cryptography_InvalidIVSize, "rgbIV");
            }
        }
        if (Mode == CipherMode.CFB)
        {
            ValidateCFBFeedbackSize(FeedbackSize);
        }
        return CreateTransformCore(Mode, Padding, rgbKey, rgbIV, BlockSize / 8, this.GetPaddingSize(Mode, FeedbackSize), FeedbackSize / 8, encrypting);
    }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSize, Internal.Cryptography.AesImplementation.CreateTransformCore(), System.SR.Cryptography_InvalidIVSize, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.SymmetricAlgorithm.FeedbackSize, System.L, System.Security.Cryptography.SymmetricAlgorithm.LegalKeySizes, System.Security.Cryptography.SymmetricAlgorithm.Padding, and Internal.Cryptography.AesImplementation.ValidateCFBFeedbackSize().
Referenced by Internal.Cryptography.AesImplementation.CreateDecryptor(), Internal.Cryptography.AesImplementation.CreateDecryptor(), Internal.Cryptography.AesImplementation.CreateEncryptor(), and Internal.Cryptography.AesImplementation.CreateEncryptor().