Terraria: System.Reflection.Metadata.BlobBuilder.LinkPrefix
LinkPrefix()
void System.Reflection.Metadata.BlobBuilder.LinkPrefix (BlobBuilder prefix) inline inherited
Definition at line 377 of file BlobBuilder.cs.
    {
        if (prefix == null)
        {
            Throw.ArgumentNull("prefix");
        }
        if (!prefix.IsHead || !IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        if (prefix.Count != 0)
        {
            PreviousLength += prefix.Count;
            prefix._length = prefix.FrozenLength;
            BlobBuilder firstChunk = FirstChunk;
            BlobBuilder firstChunk2 = prefix.FirstChunk;
            BlobBuilder nextOrPrevious = _nextOrPrevious;
            BlobBuilder nextOrPrevious2 = prefix._nextOrPrevious;
            _nextOrPrevious = ((nextOrPrevious != this) ? nextOrPrevious : prefix);
            prefix._nextOrPrevious = ((firstChunk != this) ? firstChunk : ((firstChunk2 != prefix) ? firstChunk2 : prefix));
            if (nextOrPrevious != this)
            {
                nextOrPrevious._nextOrPrevious = ((firstChunk2 != prefix) ? firstChunk2 : prefix);
            }
            if (nextOrPrevious2 != prefix)
            {
                nextOrPrevious2._nextOrPrevious = prefix;
            }
            prefix.CheckInvariants();
            CheckInvariants();
        }
    }
References System.Reflection.Metadata.BlobBuilder._nextOrPrevious, System.Reflection.Throw.ArgumentNull(), System.Reflection.Metadata.BlobBuilder.CheckInvariants(), System.Reflection.Metadata.BlobBuilder.FirstChunk, System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, System.prefix, and System.Reflection.Metadata.BlobBuilder.PreviousLength.