Terraria: System.Reflection.Metadata.BlobBuilder.WriteUTF8
WriteUTF8() [1/2]
unsafe void System.Reflection.Metadata.BlobBuilder.WriteUTF8 (string str, int start, int length, bool allowUnpairedSurrogates, bool prependSize) inline package inherited
Definition at line 860 of file BlobBuilder.cs.
    {
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        fixed (char* ptr = str)
        {
            char* ptr2 = ptr + start;
            int byteLimit = FreeBytes - (prependSize ? 4 : 0);
            char* remainder;
            int uTF8ByteCount = BlobUtilities.GetUTF8ByteCount(ptr2, length, byteLimit, out remainder);
            int num = (int)(remainder - ptr2);
            int charCount = length - num;
            int uTF8ByteCount2 = BlobUtilities.GetUTF8ByteCount(remainder, charCount);
            if (prependSize)
            {
                WriteCompressedInteger(uTF8ByteCount + uTF8ByteCount2);
            }
            _buffer.WriteUTF8(Length, ptr2, num, uTF8ByteCount, allowUnpairedSurrogates);
            AddLength(uTF8ByteCount);
            if (uTF8ByteCount2 > 0)
            {
                Expand(uTF8ByteCount2);
                _buffer.WriteUTF8(0, remainder, charCount, uTF8ByteCount2, allowUnpairedSurrogates);
                AddLength(uTF8ByteCount2);
            }
        }
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.Reflection.Metadata.BlobBuilder.AddLength(), System.charCount, System.Reflection.Metadata.BlobBuilder.Expand(), System.Reflection.Metadata.BlobBuilder.FreeBytes, System.Reflection.BlobUtilities.GetUTF8ByteCount(), System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, System.length, System.Reflection.Metadata.BlobBuilder.Length, System.start, System.str, and System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger().