Terraria: System.Reflection.Metadata.BlobBuilder.WriteByte
WriteByte()
void System.Reflection.Metadata.BlobBuilder.WriteByte (byte value) inline inherited
Definition at line 669 of file BlobBuilder.cs.
    {
        int start = ReserveBytesPrimitive(1);
        _buffer.WriteByte(start, value);
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.Reflection.Metadata.BlobBuilder.ReserveBytesPrimitive(), System.start, and System.value.
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.MetadataBuilder(), System.Reflection.Metadata.Ecma335.NamedArgumentsEncoder.AddArgument(), System.Reflection.Metadata.Ecma335.CustomModifiersEncoder.AddModifier(), System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.AddUnchecked(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Array(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.ClassOrValue(), System.Reflection.Metadata.Ecma335.CustomAttributeArrayTypeEncoder.ElementType(), System.Reflection.Metadata.Ecma335.BlobEncoder.FieldSignature(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.FunctionPointer(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericInstantiation(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericMethodTypeParameter(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericTypeParameter(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddDocumentName(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgument(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgumentAddress(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadLocal(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadLocalAddress(), System.Reflection.Metadata.Ecma335.BlobEncoder.LocalVariableSignature(), System.Reflection.Metadata.Ecma335.BlobEncoder.MethodSignature(), System.Reflection.Metadata.Ecma335.BlobEncoder.MethodSpecificationSignature(), System.Reflection.Metadata.Ecma335.NamedArgumentTypeEncoder.Object(), System.Reflection.Metadata.Ecma335.CustomAttributeArrayTypeEncoder.ObjectArray(), System.Reflection.Metadata.Ecma335.InstructionEncoder.OpCode(), System.Reflection.Metadata.Ecma335.BlobEncoder.PermissionSetBlob(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Pointer(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.PrimitiveType(), System.Reflection.Metadata.Ecma335.BlobEncoder.PropertySignature(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.SerializeHeader(), System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.SerializeTableHeader(), System.Reflection.Metadata.Ecma335.ParametersEncoder.StartVarArgs(), System.Reflection.Metadata.Ecma335.InstructionEncoder.StoreArgument(), System.Reflection.Metadata.Ecma335.InstructionEncoder.StoreLocal(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.SZArray(), System.Reflection.Metadata.Ecma335.ParameterTypeEncoder.Type(), System.Reflection.Metadata.Ecma335.ReturnTypeEncoder.Type(), System.Reflection.Metadata.Ecma335.LocalVariableTypeEncoder.Type(), System.Reflection.Metadata.Ecma335.LocalVariableTypeEncoder.TypedReference(), System.Reflection.Metadata.Ecma335.ParameterTypeEncoder.TypedReference(), System.Reflection.Metadata.Ecma335.ReturnTypeEncoder.TypedReference(), System.Reflection.Metadata.Ecma335.ReturnTypeEncoder.Void(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.VoidPointer(), System.Reflection.Metadata.BlobBuilder.WriteBoolean(), System.Reflection.PortableExecutable.ManagedTextSection.WriteRuntimeStartupStub(), System.Reflection.Metadata.BlobBuilder.WriteSByte(), System.Reflection.Metadata.BlobBuilder.WriteSerializedString(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.WriteTypeCode(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.WriteTypeCode(), and System.Reflection.Metadata.BlobBuilder.WriteUserString().