Terraria: System.Reflection.Metadata.BlobBuilder.TryWriteBytes
TryWriteBytes()
int System.Reflection.Metadata.BlobBuilder.TryWriteBytes (Stream source, int byteCount) inline inherited
Definition at line 582 of file BlobBuilder.cs.
    {
        if (source == null)
        {
            throw new ArgumentNullException("source");
        }
        if (byteCount < 0)
        {
            throw new ArgumentOutOfRangeException("byteCount");
        }
        if (byteCount == 0)
        {
            return 0;
        }
        int num = 0;
        int num2 = Math.Min(FreeBytes, byteCount);
        if (num2 > 0)
        {
            num = source.TryReadAll(_buffer, Length, num2);
            AddLength(num);
            if (num != num2)
            {
                return num;
            }
        }
        int num3 = byteCount - num2;
        if (num3 > 0)
        {
            Expand(num3);
            num = source.TryReadAll(_buffer, 0, num3);
            AddLength(num);
            num += num2;
        }
        return num;
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.Reflection.Metadata.BlobBuilder.AddLength(), System.byteCount, System.Reflection.Metadata.BlobBuilder.Expand(), System.Reflection.Metadata.BlobBuilder.FreeBytes, System.Reflection.Metadata.BlobBuilder.Length, System.Math.Min(), and System.source.