Terraria: System.Reflection.Metadata.BlobBuilder.GetChunks
GetChunks()
Chunks System.Reflection.Metadata.BlobBuilder.GetChunks () inline package inherited
Definition at line 229 of file BlobBuilder.cs.
    {
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        return new Chunks(this);
    }
References System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), and System.Reflection.Metadata.BlobBuilder.IsHead.
Referenced by System.Reflection.Metadata.BlobBuilder.Clear(), System.Reflection.Metadata.BlobBuilder.ContentEquals(), System.Reflection.Metadata.BlobBuilder.GetDebuggerDisplay(), System.Reflection.Metadata.BlobBuilder.ToArray(), System.Reflection.Metadata.BlobBuilder.WriteContentTo(), System.Reflection.Metadata.BlobBuilder.WriteContentTo(), and System.Reflection.Metadata.BlobBuilder.WriteContentTo().