Terraria: System.Reflection.Metadata.BlobBuilder.WriteBytes
WriteBytes() [1/6]
unsafe void System.Reflection.Metadata.BlobBuilder.WriteBytes (byte * buffer, int byteCount) inline inherited
Definition at line 551 of file BlobBuilder.cs.
    {
        if (buffer == null)
        {
            Throw.ArgumentNull("buffer");
        }
        if (byteCount < 0)
        {
            Throw.ArgumentOutOfRange("byteCount");
        }
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        WriteBytesUnchecked(buffer, byteCount);
    }
References System.Reflection.Throw.ArgumentNull(), System.Reflection.Throw.ArgumentOutOfRange(), System.buffer, System.byteCount, System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, and System.Reflection.Metadata.BlobBuilder.WriteBytesUnchecked().