Terraria: System.Reflection.Metadata.BlobBuilder.ContentEquals
ContentEquals()
bool System.Reflection.Metadata.BlobBuilder.ContentEquals (BlobBuilder other) inline inherited
Definition at line 247 of file BlobBuilder.cs.
    {
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        if (this == other)
        {
            return true;
        }
        if (other == null)
        {
            return false;
        }
        if (!other.IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        if (Count != other.Count)
        {
            return false;
        }
        Chunks chunks = GetChunks();
        Chunks chunks2 = other.GetChunks();
        int num = 0;
        int num2 = 0;
        bool flag = chunks.MoveNext();
        bool flag2 = chunks2.MoveNext();
        while (flag && flag2)
        {
            BlobBuilder current = chunks.Current;
            BlobBuilder current2 = chunks2.Current;
            int num3 = Math.Min(current.Length - num, current2.Length - num2);
            if (!ByteSequenceComparer.Equals(current._buffer, num, current2._buffer, num2, num3))
            {
                return false;
            }
            num += num3;
            num2 += num3;
            if (num == current.Length)
            {
                flag = chunks.MoveNext();
                num = 0;
            }
            if (num2 == current2.Length)
            {
                flag2 = chunks2.MoveNext();
                num2 = 0;
            }
        }
        return flag == flag2;
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.Internal.ByteSequenceComparer.Equals(), System.Reflection.Metadata.BlobBuilder.GetChunks(), System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, System.Reflection.Metadata.BlobBuilder.Length, System.Math.Min(), and System.other.