Terraria: System.Reflection.Metadata.BlobBuilder.WriteBytes
WriteBytes() [2/6]
void System.Reflection.Metadata.BlobBuilder.WriteBytes (byte value, int byteCount) inline inherited
Definition at line 529 of file BlobBuilder.cs.
    {
        if (byteCount < 0)
        {
            Throw.ArgumentOutOfRange("byteCount");
        }
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        int num = Math.Min(FreeBytes, byteCount);
        _buffer.WriteBytes(Length, value, num);
        AddLength(num);
        int num2 = byteCount - num;
        if (num2 > 0)
        {
            Expand(num2);
            _buffer.WriteBytes(0, value, num2);
            AddLength(num2);
        }
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.Reflection.Metadata.BlobBuilder.AddLength(), System.Reflection.Throw.ArgumentOutOfRange(), System.byteCount, System.Reflection.Metadata.BlobBuilder.Expand(), System.Reflection.Metadata.BlobBuilder.FreeBytes, System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, System.Reflection.Metadata.BlobBuilder.Length, System.Math.Min(), and System.value.
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.MetadataBuilder(), System.Reflection.Metadata.Ecma335.PermissionSetEncoder.AddPermission(), System.Reflection.Metadata.BlobBuilder.Align(), System.Reflection.Metadata.BlobBuilder.PadTo(), System.Reflection.Metadata.Ecma335.MetadataBuilder.WriteAligned(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), and System.Reflection.PortableExecutable.ManagedTextSection.WriteImportTable().