Terraria: System.Reflection.Metadata.BlobBuilder.Clear
Clear()
void System.Reflection.Metadata.BlobBuilder.Clear () inline inherited
Definition at line 187 of file BlobBuilder.cs.
    {
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        BlobBuilder firstChunk = FirstChunk;
        if (firstChunk != this)
        {
            byte[] buffer = firstChunk._buffer;
            firstChunk._length = FrozenLength;
            firstChunk._buffer = _buffer;
            _buffer = buffer;
        }
        foreach (BlobBuilder chunk in GetChunks())
        {
            if (chunk != this)
            {
                chunk.ClearChunk();
                chunk.FreeChunk();
            }
        }
        ClearChunk();
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.buffer, System.Reflection.Metadata.BlobBuilder.ClearChunk(), System.Reflection.Metadata.BlobBuilder.FirstChunk, System.Reflection.Metadata.BlobBuilder.FrozenLength, System.Reflection.Metadata.BlobBuilder.GetChunks(), System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), and System.Reflection.Metadata.BlobBuilder.IsHead.
Referenced by System.Reflection.Metadata.BlobBuilder.Free().