Terraria: System.Reflection.Metadata.BlobBuilder.WriteBytesUnchecked
WriteBytesUnchecked()
unsafe void System.Reflection.Metadata.BlobBuilder.WriteBytesUnchecked (byte * buffer, int byteCount) inline private inherited
Definition at line 568 of file BlobBuilder.cs.
    {
        int num = Math.Min(FreeBytes, byteCount);
        Marshal.Copy((IntPtr)buffer, _buffer, Length, num);
        AddLength(num);
        int num2 = byteCount - num;
        if (num2 > 0)
        {
            Expand(num2);
            Marshal.Copy((IntPtr)(buffer + num), _buffer, 0, num2);
            AddLength(num2);
        }
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.Reflection.Metadata.BlobBuilder.AddLength(), System.buffer, System.byteCount, System.Runtime.InteropServices.Marshal.Copy(), System.Reflection.Metadata.BlobBuilder.Expand(), System.Reflection.Metadata.BlobBuilder.FreeBytes, System.Reflection.Metadata.BlobBuilder.Length, and System.Math.Min().
Referenced by System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteUTF16(), and System.Reflection.Metadata.BlobBuilder.WriteUTF16().