Terraria: System.Reflection.Metadata.BlobBuilder.LinkSuffix
LinkSuffix()
void System.Reflection.Metadata.BlobBuilder.LinkSuffix (BlobBuilder suffix) inline inherited
Definition at line 410 of file BlobBuilder.cs.
    {
        if (suffix == null)
        {
            throw new ArgumentNullException("suffix");
        }
        if (!IsHead || !suffix.IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        if (suffix.Count == 0)
        {
            return;
        }
        bool flag = Count == 0;
        byte[] buffer = suffix._buffer;
        uint length = suffix._length;
        int previousLength = suffix.PreviousLength;
        int length2 = suffix.Length;
        suffix._buffer = _buffer;
        suffix._length = FrozenLength;
        _buffer = buffer;
        _length = length;
        PreviousLength += suffix.Length + previousLength;
        suffix._previousLengthOrFrozenSuffixLengthDelta = previousLength + length2 - suffix.Length;
        if (!flag)
        {
            BlobBuilder firstChunk = FirstChunk;
            BlobBuilder firstChunk2 = suffix.FirstChunk;
            BlobBuilder nextOrPrevious = _nextOrPrevious;
            BlobBuilder blobBuilder = (_nextOrPrevious = suffix._nextOrPrevious);
            suffix._nextOrPrevious = ((firstChunk2 != suffix) ? firstChunk2 : ((firstChunk != this) ? firstChunk : suffix));
            if (nextOrPrevious != this)
            {
                nextOrPrevious._nextOrPrevious = suffix;
            }
            if (blobBuilder != suffix)
            {
                blobBuilder._nextOrPrevious = ((firstChunk != this) ? firstChunk : suffix);
            }
        }
        CheckInvariants();
        suffix.CheckInvariants();
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.Reflection.Metadata.BlobBuilder._length, System.Reflection.Metadata.BlobBuilder._nextOrPrevious, System.buffer, System.Reflection.Metadata.BlobBuilder.CheckInvariants(), System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.Metadata.BlobBuilder.FirstChunk, System.Reflection.Metadata.BlobBuilder.FrozenLength, System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, System.length, System.length2, System.Reflection.Metadata.BlobBuilder.PreviousLength, and System.suffix.
Referenced by System.Reflection.PortableExecutable.ManagedTextSection.Serialize(), and System.Reflection.Metadata.Ecma335.MetadataBuilder.WriteAligned().