Terraria: System.Reflection.Metadata.BlobBuilder.WriteInt32
WriteInt32()
void System.Reflection.Metadata.BlobBuilder.WriteInt32 (int value) inline inherited
Definition at line 725 of file BlobBuilder.cs.
    {
        WriteUInt32((uint)value);
    }
References System.value, and System.Reflection.Metadata.BlobBuilder.WriteUInt32().
Referenced by System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.AddUnchecked(), System.Reflection.Metadata.Ecma335.InstructionEncoder.Branch(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgument(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadArgumentAddress(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadConstantI4(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadLocal(), System.Reflection.Metadata.Ecma335.InstructionEncoder.LoadLocalAddress(), System.Reflection.Metadata.Ecma335.ScalarEncoder.NullArray(), System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.SerializeHeader(), System.Reflection.Metadata.Ecma335.InstructionEncoder.StoreArgument(), System.Reflection.Metadata.Ecma335.InstructionEncoder.StoreLocal(), System.Reflection.Metadata.Ecma335.InstructionEncoder.Token(), and System.Reflection.Metadata.BlobBuilder.WriteReference().