Terraria: System.Reflection.Metadata.BlobBuilder.ToArray
ToArray() [2/2]
byte[] System.Reflection.Metadata.BlobBuilder.ToArray (int start, int byteCount) inline inherited
Definition at line 305 of file BlobBuilder.cs.
    {
        BlobUtilities.ValidateRange(Count, start, byteCount, "byteCount");
        byte[] array = new byte[byteCount];
        int num = 0;
        int num2 = start;
        int num3 = start + byteCount;
        foreach (BlobBuilder chunk in GetChunks())
        {
            int num4 = num + chunk.Length;
            if (num4 > num2)
            {
                int num5 = Math.Min(num3, num4) - num2;
                Array.Copy(chunk._buffer, num2 - num, array, num2 - start, num5);
                num2 += num5;
                if (num2 == num3)
                {
                    break;
                }
            }
            num = num4;
        }
        return array;
    }
References System.array, System.byteCount, System.Array.Copy(), System.Reflection.Metadata.BlobBuilder.Count, System.Reflection.Metadata.BlobBuilder.GetChunks(), System.Math.Min(), System.start, and System.Reflection.BlobUtilities.ValidateRange().