Terraria: System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger
WriteCompressedInteger()
void System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger (int value) inline inherited
Definition at line 895 of file BlobBuilder.cs.
    {
        BlobWriterImpl.WriteCompressedInteger(this, (uint)value);
    }
References System.value, and System.Reflection.Metadata.BlobWriterImpl.WriteCompressedInteger().
Referenced by System.Reflection.Metadata.Ecma335.CustomModifiersEncoder.AddModifier(), System.Reflection.Metadata.Ecma335.PermissionSetEncoder.AddPermission(), System.Reflection.Metadata.Ecma335.PermissionSetEncoder.AddPermission(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.FunctionPointer(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericInstantiation(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericMethodTypeParameter(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.GenericTypeParameter(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddDocumentName(), System.Reflection.Metadata.Ecma335.BlobEncoder.LocalVariableSignature(), System.Reflection.Metadata.Ecma335.BlobEncoder.MethodSignature(), System.Reflection.Metadata.Ecma335.BlobEncoder.MethodSpecificationSignature(), System.Reflection.Metadata.Ecma335.MethodSignatureEncoder.Parameters(), System.Reflection.Metadata.Ecma335.BlobEncoder.PermissionSetArguments(), System.Reflection.Metadata.Ecma335.BlobEncoder.PermissionSetBlob(), System.Reflection.Metadata.Ecma335.ArrayShapeEncoder.Shape(), System.Reflection.Metadata.Ecma335.SignatureTypeEncoder.Type(), System.Reflection.Metadata.BlobBuilder.WriteUserString(), and System.Reflection.Metadata.BlobBuilder.WriteUTF8().