Terraria: System.Reflection.Metadata.BlobBuilder.Expand
Expand()
void System.Reflection.Metadata.BlobBuilder.Expand (int newLength) inline private inherited
Definition at line 461 of file BlobBuilder.cs.
    {
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        BlobBuilder blobBuilder = AllocateChunk(Math.Max(newLength, 16));
        if (blobBuilder.ChunkCapacity < newLength)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.ReturnedBuilderSizeTooSmall, GetType(), "AllocateChunk"));
        }
        byte[] buffer = blobBuilder._buffer;
        if (_length == 0)
        {
            blobBuilder._buffer = _buffer;
            _buffer = buffer;
        }
        else
        {
            BlobBuilder nextOrPrevious = _nextOrPrevious;
            BlobBuilder firstChunk = FirstChunk;
            if (nextOrPrevious == this)
            {
                _nextOrPrevious = blobBuilder;
            }
            else
            {
                blobBuilder._nextOrPrevious = firstChunk;
                nextOrPrevious._nextOrPrevious = blobBuilder;
                _nextOrPrevious = blobBuilder;
            }
            blobBuilder._buffer = _buffer;
            blobBuilder._length = FrozenLength;
            blobBuilder._previousLengthOrFrozenSuffixLengthDelta = PreviousLength;
            _buffer = buffer;
            PreviousLength += Length;
            _length = 0u;
        }
        CheckInvariants();
    }
References System.Reflection.Metadata.BlobBuilder._buffer, System.Reflection.Metadata.BlobBuilder._length, System.Reflection.Metadata.BlobBuilder._nextOrPrevious, System.Reflection.Metadata.BlobBuilder.AllocateChunk(), System.buffer, System.Reflection.Metadata.BlobBuilder.CheckInvariants(), System.Reflection.Metadata.BlobBuilder.FirstChunk, System.SR.Format(), System.Reflection.Metadata.BlobBuilder.FrozenLength, System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, System.Reflection.Metadata.BlobBuilder.Length, System.Math.Max(), System.Reflection.Metadata.BlobBuilder.PreviousLength, and System.SR.ReturnedBuilderSizeTooSmall.
Referenced by System.Reflection.Metadata.BlobBuilder.ReserveBytesImpl(), System.Reflection.Metadata.BlobBuilder.TryWriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteBytesUnchecked(), and System.Reflection.Metadata.BlobBuilder.WriteUTF8().