Terraria: System.Reflection.Metadata.BlobBuilder.WriteUTF8
WriteUTF8() [2/2]
void System.Reflection.Metadata.BlobBuilder.WriteUTF8 (string value, bool allowUnpairedSurrogates = true) inline inherited
Definition at line 851 of file BlobBuilder.cs.
    {
        if (value == null)
        {
            Throw.ArgumentNull("value");
        }
        WriteUTF8(value, 0, value.Length, allowUnpairedSurrogates, prependSize: false);
    }
References System.Reflection.Throw.ArgumentNull(), System.value, and System.Reflection.Metadata.BlobBuilder.WriteUTF8().
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddBlobUTF8(), System.Reflection.Metadata.BlobBuilder.WriteSerializedString(), and System.Reflection.Metadata.BlobBuilder.WriteUTF8().