Terraria: System.Reflection.Metadata.BlobBuilder.ReserveBytesPrimitive
ReserveBytesPrimitive()
int System.Reflection.Metadata.BlobBuilder.ReserveBytesPrimitive (int byteCount) inline private inherited
Definition at line 524 of file BlobBuilder.cs.
    {
        return ReserveBytesImpl(byteCount);
    }
References System.byteCount, and System.Reflection.Metadata.BlobBuilder.ReserveBytesImpl().
Referenced by System.Reflection.Metadata.BlobBuilder.WriteByte(), System.Reflection.Metadata.BlobBuilder.WriteDecimal(), System.Reflection.Metadata.BlobBuilder.WriteDouble(), System.Reflection.Metadata.BlobBuilder.WriteGuid(), System.Reflection.Metadata.BlobBuilder.WriteSingle(), System.Reflection.Metadata.BlobBuilder.WriteUInt16(), System.Reflection.Metadata.BlobBuilder.WriteUInt16BE(), System.Reflection.Metadata.BlobBuilder.WriteUInt32(), System.Reflection.Metadata.BlobBuilder.WriteUInt32BE(), and System.Reflection.Metadata.BlobBuilder.WriteUInt64().