Terraria: System.Reflection.Metadata.BlobBuilder.WriteBytes
WriteBytes() [4/6]
unsafe void System.Reflection.Metadata.BlobBuilder.WriteBytes (byte[] buffer, int start, int byteCount) inline inherited
Definition at line 633 of file BlobBuilder.cs.
    {
        if (buffer == null)
        {
            Throw.ArgumentNull("buffer");
        }
        BlobUtilities.ValidateRange(buffer.Length, start, byteCount, "byteCount");
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        if (buffer.Length != 0)
        {
            fixed (byte* ptr = &buffer[0])
            {
                WriteBytesUnchecked(ptr + start, byteCount);
            }
        }
    }
References System.Reflection.Throw.ArgumentNull(), System.buffer, System.byteCount, System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, System.start, System.Reflection.BlobUtilities.ValidateRange(), and System.Reflection.Metadata.BlobBuilder.WriteBytesUnchecked().