Terraria: System.Reflection.Metadata.BlobBuilder.WriteUTF16
WriteUTF16() [1/2]
unsafe void System.Reflection.Metadata.BlobBuilder.WriteUTF16 (char[] value) inline inherited
Definition at line 776 of file BlobBuilder.cs.
    {
        if (value == null)
        {
            Throw.ArgumentNull("value");
        }
        if (!IsHead)
        {
            Throw.InvalidOperationBuilderAlreadyLinked();
        }
        if (value.Length == 0)
        {
            return;
        }
        if (BitConverter.IsLittleEndian)
        {
            fixed (char* buffer = &value[0])
            {
                WriteBytesUnchecked((byte*)buffer, value.Length * 2);
            }
            return;
        }
        for (int i = 0; i < value.Length; i++)
        {
            WriteUInt16(value[i]);
        }
    }
References System.Reflection.Throw.ArgumentNull(), System.buffer, System.Reflection.Throw.InvalidOperationBuilderAlreadyLinked(), System.Reflection.Metadata.BlobBuilder.IsHead, System.BitConverter.IsLittleEndian, System.value, System.Reflection.Metadata.BlobBuilder.WriteBytesUnchecked(), and System.Reflection.Metadata.BlobBuilder.WriteUInt16().
Referenced by System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddBlobUTF16(), and System.Reflection.Metadata.BlobBuilder.WriteUserString().