Terraria: UIWorkshopHub.HandleBackButtonUsage
HandleBackButtonUsage()
void UIWorkshopHub.HandleBackButtonUsage () inline
Implements IHaveBackButtonCommand.
     {
         if (_previousUIState == null)
         {
             Main.menuMode = 0;
             return;
         }
         Main.menuMode = 888;
         Main.MenuUI.SetState(_previousUIState);
         SoundEngine.PlaySound(11);
     }
References _previousUIState, Main.menuMode, Main.MenuUI, SoundEngine.PlaySound(), and UserInterface.SetState().
Referenced by GoBackClick().