Terraria: UIWorkshopHub.MakeButton_OpenWorkshopWorldsImportMenu
MakeButton_OpenWorkshopWorldsImportMenu()
UIElement UIWorkshopHub.MakeButton_OpenWorkshopWorldsImportMenu () inline private
     {
         UIElement uIElement = MakeFancyButton("Images/UI/Workshop/HubWorlds", "Workshop.HubWorlds");
         uIElement.OnLeftClick += Click_OpenWorldImportMenu;
         _buttonImportWorlds = uIElement;
         return uIElement;
     }
References _buttonImportWorlds, Click_OpenWorldImportMenu(), MakeFancyButton(), and UIElement.OnLeftClick.
Referenced by OnInitialize().