Terraria: UIWorkshopHub.ClearOptionDescription
ClearOptionDescription()
void UIWorkshopHub.ClearOptionDescription (UIMouseEvent evt, UIElement listeningElement) inline
     {
         _descriptionText.SetText(Language.GetText("Workshop.HubDescriptionDefault"));
     }
References _descriptionText, Language.GetText(), and UIText.SetText().
Referenced by MakeFancyButton().