Terraria: UIWorkshopHub.OnInitialize
OnInitialize()
override void UIWorkshopHub.OnInitialize () inline virtual
Reimplemented from UIElement.
     {
         base.OnInitialize();
         int num = 20;
         int num2 = 250;
         int num3 = 50 + num * 2;
         int num4 = 600;
         int num5 = num4 - num2 - num3;
         UIElement uIElement = new UIElement();
         uIElement.Width.Set(600f, 0f);
         uIElement.Top.Set(num2, 0f);
         uIElement.Height.Set(num4 - num2, 0f);
         uIElement.HAlign = 0.5f;
         int num6 = 154;
         UIPanel uIPanel = new UIPanel();
         uIPanel.Width.Set(0f, 1f);
         uIPanel.Height.Set(num5, 0f);
         uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
         UIElement uIElement2 = new UIElement();
         uIElement2.Width.Set(0f, 1f);
         uIElement2.Height.Set(num6, 0f);
         uIElement2.SetPadding(0f);
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.WorkshopHub"), 0.8f, large: true);
         uITextPanel.HAlign = 0.5f;
         uITextPanel.Top.Set(-46f, 0f);
         uITextPanel.SetPadding(15f);
         uITextPanel.BackgroundColor = new Color(73, 94, 171);
         UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true);
         uITextPanel2.Width.Set(-10f, 0.5f);
         uITextPanel2.Height.Set(50f, 0f);
         uITextPanel2.VAlign = 1f;
         uITextPanel2.HAlign = 0f;
         uITextPanel2.Top.Set(-num, 0f);
         uITextPanel2.OnMouseOver += FadedMouseOver;
         uITextPanel2.OnMouseOut += FadedMouseOut;
         uITextPanel2.OnLeftClick += GoBackClick;
         uITextPanel2.SetSnapPoint("Back", 0);
         uIElement.Append(uITextPanel2);
         _buttonBack = uITextPanel2;
         UITextPanel<LocalizedText> uITextPanel3 = new UITextPanel<LocalizedText>(Language.GetText("Workshop.ReportLogsButton"), 0.7f, large: true);
         uITextPanel3.Width.Set(-10f, 0.5f);
         uITextPanel3.Height.Set(50f, 0f);
         uITextPanel3.VAlign = 1f;
         uITextPanel3.HAlign = 1f;
         uITextPanel3.Top.Set(-num, 0f);
         uITextPanel3.OnMouseOver += FadedMouseOver;
         uITextPanel3.OnMouseOut += FadedMouseOut;
         uITextPanel3.OnLeftClick += GoLogsClick;
         uITextPanel3.SetSnapPoint("Logs", 0);
         uIElement.Append(uITextPanel3);
         _buttonLogs = uITextPanel3;
         UIElement uIElement3 = MakeButton_OpenWorkshopWorldsImportMenu();
         uIElement3.HAlign = 0f;
         uIElement3.VAlign = 0f;
         uIElement2.Append(uIElement3);
         uIElement3 = MakeButton_OpenUseResourcePacksMenu();
         uIElement3.HAlign = 1f;
         uIElement3.VAlign = 0f;
         uIElement2.Append(uIElement3);
         uIElement3 = MakeButton_OpenPublishWorldsMenu();
         uIElement3.HAlign = 0f;
         uIElement3.VAlign = 1f;
         uIElement2.Append(uIElement3);
         uIElement3 = MakeButton_OpenPublishResourcePacksMenu();
         uIElement3.HAlign = 1f;
         uIElement3.VAlign = 1f;
         uIElement2.Append(uIElement3);
         AddHorizontalSeparator(uIPanel, num6 + 6 + 6);
         AddDescriptionPanel(uIPanel, num6 + 8 + 6 + 6, num5 - num6 - 12 - 12 - 8, "desc");
         uIPanel.Append(uIElement2);
         uIElement.Append(uIPanel);
         uIElement.Append(uITextPanel);
         Append(uIElement);
     }
References UIElement.UIElement(), _buttonBack, _buttonLogs, AddDescriptionPanel(), AddHorizontalSeparator(), UIElement.Append(), UIPanel.BackgroundColor, Color, FadedMouseOut(), FadedMouseOver(), Language.GetText(), GoBackClick(), GoLogsClick(), UIElement.HAlign, UIElement.Height, MakeButton_OpenPublishResourcePacksMenu(), MakeButton_OpenPublishWorldsMenu(), MakeButton_OpenUseResourcePacksMenu(), MakeButton_OpenWorkshopWorldsImportMenu(), StyleDimension.Set(), UIElement.SetPadding(), UIElement.Top, UIElement.VAlign, and UIElement.Width.