Terraria: UIWorkshopHub.MakeFancyButton
MakeFancyButton()
UIElement UIWorkshopHub.MakeFancyButton (string iconImagePath, string textKey) inline private
     {
         UIPanel uIPanel = new UIPanel();
         int num = -3;
         int num2 = -3;
         uIPanel.Width = StyleDimension.FromPixelsAndPercent(num, 0.5f);
         uIPanel.Height = StyleDimension.FromPixelsAndPercent(num2, 0.5f);
         uIPanel.OnMouseOver += SetColorsToHovered;
         uIPanel.OnMouseOut += SetColorsToNotHovered;
         uIPanel.BackgroundColor = new Color(63, 82, 151) * 0.7f;
         uIPanel.BorderColor = new Color(89, 116, 213) * 0.7f;
         uIPanel.SetPadding(6f);
         UIImage uIImage = new UIImage(Main.Assets.Request<Texture2D>(iconImagePath, (AssetRequestMode)1))
         {
             IgnoresMouseInteraction = true,
             VAlign = 0.5f
         };
         uIImage.Left.Set(2f, 0f);
         uIPanel.Append(uIImage);
         uIPanel.OnMouseOver += ShowOptionDescription;
         uIPanel.OnMouseOut += ClearOptionDescription;
         UIText uIText = new UIText(Language.GetText(textKey), 0.45f, large: true)
         {
             HAlign = 0f,
             VAlign = 0.5f,
             Width = StyleDimension.FromPixelsAndPercent(-80f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Top = StyleDimension.FromPixelsAndPercent(5f, 0f),
             Left = StyleDimension.FromPixels(80f),
             IgnoresMouseInteraction = true,
             TextOriginX = 0f,
             TextOriginY = 0f
         };
         uIText.PaddingLeft = 0f;
         uIText.PaddingRight = 20f;
         uIText.PaddingTop = 10f;
         uIText.IsWrapped = true;
         uIPanel.Append(uIText);
         uIPanel.SetSnapPoint("Button", 0);
         return uIPanel;
     }
References UIElement.Append(), Main.Assets, UIPanel.BackgroundColor, UIPanel.BorderColor, ClearOptionDescription(), Color, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), Language.GetText(), UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, UIText.IsWrapped, UIElement.Left, UIElement.OnMouseOut, UIElement.OnMouseOver, UIElement.PaddingLeft, UIElement.PaddingRight, UIElement.PaddingTop, StyleDimension.Set(), SetColorsToHovered(), SetColorsToNotHovered(), UIElement.SetPadding(), UIElement.SetSnapPoint(), ShowOptionDescription(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by MakeButton_OpenPublishResourcePacksMenu(), MakeButton_OpenPublishWorldsMenu(), MakeButton_OpenUseResourcePacksMenu(), and MakeButton_OpenWorkshopWorldsImportMenu().