Terraria: Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.UIBestiaryEntryButton
UIBestiaryEntryButton()
Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.UIBestiaryEntryButton (BestiaryEntry entry, bool isAPrettyPortrait) inline
    {
        Entry = entry;
        Height.Set(72f, 0f);
        Width.Set(72f, 0f);
        SetPadding(0f);
        UIElement uIElement = new UIElement
        {
            Width = new StyleDimension(-4f, 1f),
            Height = new StyleDimension(-4f, 1f),
            IgnoresMouseInteraction = true,
            OverflowHidden = true,
            HAlign = 0.5f,
            VAlign = 0.5f
        };
        uIElement.SetPadding(0f);
        uIElement.Append(new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Slot_Back", (AssetRequestMode)1))
        {
            VAlign = 0.5f,
            HAlign = 0.5f
        });
        if (isAPrettyPortrait)
        {
            Asset<Texture2D> val = TryGettingBackgroundImageProvider(entry);
            if (val != null)
            {
                uIElement.Append(new UIImage(val)
                {
                    HAlign = 0.5f,
                    VAlign = 0.5f
                });
            }
        }
        UIBestiaryEntryIcon uIBestiaryEntryIcon = new UIBestiaryEntryIcon(entry, isAPrettyPortrait);
        uIElement.Append(uIBestiaryEntryIcon);
        Append(uIElement);
        _icon = uIBestiaryEntryIcon;
        int? num = TryGettingDisplayIndex(entry);
        if (num.HasValue)
        {
            UIText element = new UIText(num.Value.ToString(), 0.9f)
            {
                Top = new StyleDimension(10f, 0f),
                Left = new StyleDimension(10f, 0f),
                IgnoresMouseInteraction = true
            };
            Append(element);
        }
        _bordersGlow = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Slot_Selection", (AssetRequestMode)1))
        {
            VAlign = 0.5f,
            HAlign = 0.5f,
            IgnoresMouseInteraction = true
        };
        _bordersOverlay = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Slot_Overlay", (AssetRequestMode)1))
        {
            VAlign = 0.5f,
            HAlign = 0.5f,
            IgnoresMouseInteraction = true,
            Color = Color.White * 0.6f
        };
        Append(_bordersOverlay);
        UIImage uIImage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Slot_Front", (AssetRequestMode)1))
        {
            VAlign = 0.5f,
            HAlign = 0.5f,
            IgnoresMouseInteraction = true
        };
        Append(uIImage);
        _borders = uIImage;
        if (isAPrettyPortrait)
        {
            RemoveChild(_bordersOverlay);
        }
        if (!isAPrettyPortrait)
        {
            base.OnMouseOver += MouseOver;
            base.OnMouseOut += MouseOut;
        }
    }
References Terraria.GameContent.UI.Elements.UIBestiaryEntryButton._borders, Terraria.GameContent.UI.Elements.UIBestiaryEntryButton._bordersGlow, Terraria.GameContent.UI.Elements.UIBestiaryEntryButton._bordersOverlay, Terraria.GameContent.UI.Elements.UIBestiaryEntryButton._icon, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.Entry, Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.MouseOut(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.MouseOver(), Terraria.UI.UIElement.OverflowHidden, Terraria.UI.UIElement.RemoveChild(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.TryGettingBackgroundImageProvider(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.TryGettingDisplayIndex(), Terraria.UI.UIElement.VAlign, ReLogic.Content.Asset< T >.Value, and Terraria.UI.UIElement.Width.