Terraria: PlayerDrawHelper.SetShaderForData
SetShaderForData()
static void PlayerDrawHelper.SetShaderForData (Player player, int cHead, ref DrawData cdd) inline static
     {
         UnpackShader(cdd.shader, out var localShaderIndex, out var shaderType);
         switch (shaderType)
         {
         case ShaderConfiguration.ArmorShader:
             GameShaders.Hair.Apply(0, player, cdd);
             GameShaders.Armor.Apply(localShaderIndex, player, cdd);
             break;
         case ShaderConfiguration.HairShader:
             if (player.head == 0)
             {
                 GameShaders.Hair.Apply(0, player, cdd);
                 GameShaders.Armor.Apply(cHead, player, cdd);
             }
             else
             {
                 GameShaders.Armor.Apply(0, player, cdd);
                 GameShaders.Hair.Apply((short)localShaderIndex, player, cdd);
             }
             break;
         case ShaderConfiguration.TileShader:
             Main.tileShader.CurrentTechnique.Passes[localShaderIndex].Apply();
             break;
         case ShaderConfiguration.TilePaintID:
         {
             int index = Main.ConvertPaintIdToTileShaderIndex(localShaderIndex, isUsedForPaintingGrass: false, useWallShaderHacks: false);
             Main.tileShader.CurrentTechnique.Passes[index].Apply();
             break;
         }
         }
     }
References ArmorShaderDataSet.Apply(), HairShaderDataSet.Apply(), GameShaders.Armor, Main.ConvertPaintIdToTileShaderIndex(), GameShaders.Hair, Player.head, Main.tileShader, and UnpackShader().
Referenced by FlameParticle.Draw(), PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), PlayerDrawLayers.DrawPlayer_RenderAllLayers(), PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow(), and MapHeadRenderer.RenderDrawData().