Terraria: System.Net.Dns.Resolve
Resolve()
static IPHostEntry System.Net.Dns.Resolve (string hostName) inline static
Definition at line 287 of file Dns.cs.
    {
        if (hostName == null)
        {
            throw new ArgumentNullException("hostName");
        }
        IPHostEntry iPHostEntry;
        if (IPAddress.TryParse(hostName, out IPAddress address) && (address.AddressFamily != AddressFamily.InterNetworkV6 || SocketProtocolSupportPal.OSSupportsIPv6))
        {
            try
            {
                iPHostEntry = GetHostEntryCore(address, AddressFamily.Unspecified);
            }
            catch (SocketException message)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(hostName, message, "Resolve");
                }
                iPHostEntry = CreateHostEntryForAddress(address);
            }
        }
        else
        {
            iPHostEntry = GetHostEntryCore(hostName, AddressFamily.Unspecified);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(hostName, iPHostEntry, "Resolve");
        }
        return iPHostEntry;
    }
References System.Net.Dns.CreateHostEntryForAddress(), System.Net.NetEventSource.Error(), System.Net.Dns.GetHostEntryCore(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.SocketProtocolSupportPal.OSSupportsIPv6, and System.Net.IPAddress.TryParse().