Terraria: System.Net.Dns.GetHostEntryOrAddressesCoreAsync
GetHostEntryOrAddressesCoreAsync()
static Task System.Net.Dns.GetHostEntryOrAddressesCoreAsync (string hostName, bool justReturnParsedIp, bool throwOnIIPAny, bool justAddresses, AddressFamily family, CancellationToken cancellationToken) inline static private
Definition at line 472 of file Dns.cs.
    {
        if (hostName == null)
        {
            throw new ArgumentNullException("hostName");
        }
        if (cancellationToken.IsCancellationRequested)
        {
            if (!justAddresses)
            {
                return Task.FromCanceled<IPHostEntry>(cancellationToken);
            }
            return Task.FromCanceled<IPAddress[]>(cancellationToken);
        }
        object key;
        if (IPAddress.TryParse(hostName, out IPAddress address))
        {
            if (throwOnIIPAny && (address.Equals(IPAddress.Any) || address.Equals(IPAddress.IPv6Any)))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(hostName, $"Invalid address '{address}'", "GetHostEntryOrAddressesCoreAsync");
                }
                throw new ArgumentException(System.SR.net_invalid_ip_addr, "hostName");
            }
            if (justReturnParsedIp)
            {
                if (!justAddresses)
                {
                    return Task.FromResult(CreateHostEntryForAddress(address));
                }
                return Task.FromResult((family != 0 && address.AddressFamily != family) ? Array.Empty<IPAddress>() : new IPAddress[1] { address });
            }
            key = ((family == AddressFamily.Unspecified) ? address : ((object)new KeyValuePair<IPAddress, AddressFamily>(address, family)));
        }
        else
        {
            if (NameResolutionPal.SupportsGetAddrInfoAsync)
            {
                ValidateHostName(hostName);
                Task task = ((!NameResolutionTelemetry.Log.IsEnabled()) ? NameResolutionPal.GetAddrInfoAsync(hostName, justAddresses, family, cancellationToken) : (justAddresses ? ((Task)GetAddrInfoWithTelemetryAsync<IPAddress[]>(hostName, justAddresses, family, cancellationToken)) : ((Task)GetAddrInfoWithTelemetryAsync<IPHostEntry>(hostName, justAddresses, family, cancellationToken))));
                if (task != null)
                {
                    return task;
                }
            }
            key = ((family == AddressFamily.Unspecified) ? hostName : ((object)new KeyValuePair<string, AddressFamily>(hostName, family)));
        }
        if (justAddresses)
        {
            return RunAsync(delegate(object s, ValueStopwatch stopwatch)
            {
                if (s is string hostName3)
                {
                    return GetHostAddressesCore(hostName3, AddressFamily.Unspecified, stopwatch);
                }
                if (s is KeyValuePair<string, AddressFamily> keyValuePair3)
                {
                    return GetHostAddressesCore(keyValuePair3.Key, keyValuePair3.Value, stopwatch);
                }
                if (s is IPAddress address3)
                {
                    return GetHostAddressesCore(address3, AddressFamily.Unspecified, stopwatch);
                }
                return (s is KeyValuePair<IPAddress, AddressFamily> keyValuePair4) ? GetHostAddressesCore(keyValuePair4.Key, keyValuePair4.Value, stopwatch) : null;
            }, key, cancellationToken);
        }
        return RunAsync(delegate(object s, ValueStopwatch stopwatch)
        {
            if (s is string hostName2)
            {
                return GetHostEntryCore(hostName2, AddressFamily.Unspecified, stopwatch);
            }
            if (s is KeyValuePair<string, AddressFamily> keyValuePair)
            {
                return GetHostEntryCore(keyValuePair.Key, keyValuePair.Value, stopwatch);
            }
            if (s is IPAddress address2)
            {
                return GetHostEntryCore(address2, AddressFamily.Unspecified, stopwatch);
            }
            return (s is KeyValuePair<IPAddress, AddressFamily> keyValuePair2) ? GetHostEntryCore(keyValuePair2.Key, keyValuePair2.Value, stopwatch) : null;
        }, key, cancellationToken);
    }
References System.Net.IPAddress.Any, System.cancellationToken, System.Net.Dns.CreateHostEntryForAddress(), System.Net.NetEventSource.Error(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Net.NameResolutionPal.GetAddrInfoAsync(), System.Net.Dns.GetHostAddressesCore(), System.Net.Dns.GetHostEntryCore(), System.Net.IPAddress.IPv6Any, System.key, System.Net.NetEventSource.Log, System.Net.NameResolutionTelemetry.Log, System.SR.net_invalid_ip_addr, System.s, System.Net.NameResolutionPal.SupportsGetAddrInfoAsync, System.task, System.Net.IPAddress.TryParse(), and System.Net.Dns.ValidateHostName().
Referenced by System.Net.Dns.GetHostAddressesAsync(), System.Net.Dns.GetHostAddressesAsync(), System.Net.Dns.GetHostAddressesAsync(), and System.Net.Dns.GetHostEntryCoreAsync().