Terraria: System.Net.Dns.GetHostAddresses
GetHostAddresses() [1/2]
static IPAddress[] System.Net.Dns.GetHostAddresses (string hostNameOrAddress) inline static
Definition at line 170 of file Dns.cs.
    {
        return GetHostAddresses(hostNameOrAddress, AddressFamily.Unspecified);
    }
References System.Net.Dns.GetHostAddresses().
Referenced by System.Net.Sockets.Socket.Connect(), System.Net.Sockets.TcpClient.Connect(), System.Net.Sockets.UdpClient.Connect(), System.Net.Http.SocksHelper.EstablishSocks4TunnelAsync(), System.Net.NetworkInformation.Ping.GetAddressAndSend(), System.Net.Sockets.UdpClient.GetEndpoint(), and System.Net.Dns.GetHostAddresses().