Terraria: System.Net.Dns.GetHostEntryAsync
GetHostEntryAsync() [3/4]
static Task< IPHostEntry > System.Net.Dns.GetHostEntryAsync (string hostNameOrAddress, AddressFamily family, CancellationToken cancellationToken = default(CancellationToken)) inline static
Definition at line 103 of file Dns.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Task<IPHostEntry> hostEntryCoreAsync = GetHostEntryCoreAsync(hostNameOrAddress, justReturnParsedIp: false, throwOnIIPAny: true, family, cancellationToken);
            hostEntryCoreAsync.ContinueWith(delegate(Task<IPHostEntry> t, object s)
            {
                string text = (string)s;
                if (t.Status == TaskStatus.RanToCompletion)
                {
                    System.Net.NetEventSource.Info(text, $"{t.Result} with {t.Result.AddressList.Length} entries", "GetHostEntryAsync");
                }
                Exception ex = t.Exception?.InnerException;
                if (ex is SocketException ex2)
                {
                    System.Net.NetEventSource.Error(text, $"{text} DNS lookup failed with {((ExternalException)(object)ex2).ErrorCode}", "GetHostEntryAsync");
                }
                else if (ex is OperationCanceledException)
                {
                    System.Net.NetEventSource.Error(text, $"{text} DNS lookup was canceled", "GetHostEntryAsync");
                }
            }, hostNameOrAddress, CancellationToken.None, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
            return hostEntryCoreAsync;
        }
        return GetHostEntryCoreAsync(hostNameOrAddress, justReturnParsedIp: false, throwOnIIPAny: true, family, cancellationToken);
    }
References System.cancellationToken, System.Threading.Tasks.TaskScheduler.Default, System.Net.NetEventSource.Error(), System.Net.Dns.GetHostEntryCoreAsync(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Threading.CancellationToken.None, System.s, and System.text.