Terraria: System.Net.Dns.CreateHostEntryForAddress
CreateHostEntryForAddress()
static IPHostEntry System.Net.Dns.CreateHostEntryForAddress (IPAddress address) inline static private
Definition at line 582 of file Dns.cs.
    {
        IPHostEntry iPHostEntry = new IPHostEntry();
        iPHostEntry.HostName = address.ToString();
        iPHostEntry.Aliases = Array.Empty<string>();
        iPHostEntry.AddressList = new IPAddress[1] { address };
        return iPHostEntry;
    }
References System.Net.IPAddress.ToString().
Referenced by System.Net.Dns.EndResolve(), System.Net.Dns.GetHostByName(), System.Net.Dns.GetHostEntryOrAddressesCoreAsync(), and System.Net.Dns.Resolve().