Terraria: System.Net.Dns.EndResolve
EndResolve()
static IPHostEntry System.Net.Dns.EndResolve (IAsyncResult asyncResult) inline static
Definition at line 327 of file Dns.cs.
    {
        IPHostEntry iPHostEntry;
        try
        {
            iPHostEntry = System.Threading.Tasks.TaskToApm.End<IPHostEntry>(asyncResult);
        }
        catch (SocketException message)
        {
            object obj = ((asyncResult is Task task) ? task.AsyncState : ((!(asyncResult is System.Threading.Tasks.TaskToApm.TaskAsyncResult taskAsyncResult)) ? null : taskAsyncResult._task.AsyncState));
            object obj2 = obj;
            IPAddress iPAddress2 = ((obj2 is IPAddress iPAddress) ? iPAddress : ((!(obj2 is KeyValuePair<IPAddress, AddressFamily> keyValuePair)) ? null : keyValuePair.Key));
            IPAddress iPAddress3 = iPAddress2;
            if (iPAddress3 == null)
            {
                throw;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, message, "EndResolve");
            }
            iPHostEntry = CreateHostEntryForAddress(iPAddress3);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(null, iPHostEntry, "EndResolve");
        }
        return iPHostEntry;
    }
References System.asyncResult, System.Net.Dns.CreateHostEntryForAddress(), System.Threading.Tasks.TaskToApm.End(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.obj, and System.task.