Terraria: System.Net.Dns.GetHostEntryOrAddressesCore
GetHostEntryOrAddressesCore() [2/2]
static object System.Net.Dns.GetHostEntryOrAddressesCore (string hostName, bool justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch) inline static private
Definition at line 367 of file Dns.cs.
    {
        ValidateHostName(hostName);
        if (!stopwatch.IsActive)
        {
            stopwatch = NameResolutionTelemetry.Log.BeforeResolution(hostName);
        }
        object result;
        try
        {
            string hostName2;
            string[] aliases;
            IPAddress[] addresses;
            int nativeErrorCode;
            SocketError socketError = NameResolutionPal.TryGetAddrInfo(hostName, justAddresses, addressFamily, out hostName2, out aliases, out addresses, out nativeErrorCode);
            if (socketError != 0)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(hostName, $"{hostName} DNS lookup failed with {socketError}", "GetHostEntryOrAddressesCore");
                }
                throw SocketExceptionFactory.CreateSocketException(socketError, nativeErrorCode);
            }
            result = (justAddresses ? ((object)addresses) : ((object)new IPHostEntry
            {
                AddressList = addresses,
                HostName = hostName2,
                Aliases = aliases
            }));
        }
        catch when (LogFailure(stopwatch))
        {
            throw;
        }
        NameResolutionTelemetry.Log.AfterResolution(stopwatch, successful: true);
        return result;
    }
References System.Net.Internals.SocketExceptionFactory.CreateSocketException(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, System.Net.NameResolutionTelemetry.Log, System.Net.Dns.LogFailure(), System.Net.NameResolutionPal.TryGetAddrInfo(), and System.Net.Dns.ValidateHostName().
Referenced by System.Net.Dns.GetHostAddressesCore(), System.Net.Dns.GetHostAddressesCore(), System.Net.Dns.GetHostEntryCore(), and System.Net.Dns.GetHostEntryCore().