Terraria: System.Net.Dns.GetHostAddresses
GetHostAddresses() [2/2]
static IPAddress[] System.Net.Dns.GetHostAddresses (string hostNameOrAddress, AddressFamily family) inline static
Definition at line 175 of file Dns.cs.
    {
        if (hostNameOrAddress == null)
        {
            throw new ArgumentNullException("hostNameOrAddress");
        }
        IPAddress[] array;
        if (IPAddress.TryParse(hostNameOrAddress, out IPAddress address))
        {
            if (address.Equals(IPAddress.Any) || address.Equals(IPAddress.IPv6Any))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(address, $"Invalid address '{address}'", "GetHostAddresses");
                }
                throw new ArgumentException(System.SR.Format(System.SR.net_invalid_ip_addr, "hostNameOrAddress"));
            }
            array = ((family != 0 && address.AddressFamily != family) ? Array.Empty<IPAddress>() : new IPAddress[1] { address });
        }
        else
        {
            array = GetHostAddressesCore(hostNameOrAddress, family);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(hostNameOrAddress, array, "GetHostAddresses");
        }
        return array;
    }
References System.Net.IPAddress.Any, System.array, System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.Dns.GetHostAddressesCore(), System.Net.NetEventSource.Info(), System.Net.IPAddress.IPv6Any, System.Net.NetEventSource.Log, System.SR.net_invalid_ip_addr, and System.Net.IPAddress.TryParse().