Terraria: IssueReportsIndicator.OpenUI
OpenUI()
void IssueReportsIndicator.OpenUI () inline private
     {
         Setup();
         Main.OpenReportsMenu();
     }
References Main.OpenReportsMenu(), and Setup().
Referenced by Draw().