Terraria: System.Linq.Expressions.Compiler.VariableBinder.Reference
Reference()
void System.Linq.Expressions.Compiler.VariableBinder.Reference (ParameterExpression node, VariableStorageKind storage) inline private
Definition at line 212 of file VariableBinder.cs.
    {
        CompilerScope compilerScope = null;
        foreach (CompilerScope scope in _scopes)
        {
            if (scope.Definitions.ContainsKey(node))
            {
                compilerScope = scope;
                break;
            }
            scope.NeedsClosure = true;
            if (scope.IsMethod)
            {
                storage = VariableStorageKind.Hoisted;
            }
        }
        if (compilerScope == null)
        {
            throw Error.UndefinedVariable(node.Name, node.Type, CurrentLambdaName);
        }
        if (storage == VariableStorageKind.Hoisted)
        {
            if (node.IsByRef)
            {
                throw Error.CannotCloseOverByRef(node.Name, CurrentLambdaName);
            }
            compilerScope.Definitions[node] = VariableStorageKind.Hoisted;
        }
    }
References System.Linq.Expressions.Compiler.VariableBinder._scopes, System.Linq.Expressions.Error.CannotCloseOverByRef(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Linq.Expressions.Compiler.VariableBinder.CurrentLambdaName, System.Linq.Expressions.Compiler.CompilerScope.Definitions, System.Linq.Expressions.Compiler.CompilerScope.IsMethod, and System.Linq.Expressions.Error.UndefinedVariable().
Referenced by System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(), and System.Linq.Expressions.Compiler.VariableBinder.VisitRuntimeVariables().