Terraria: System.Linq.Expressions.Compiler.VariableBinder.MergeScopes
MergeScopes()
ReadOnlyCollection< Expression > System.Linq.Expressions.Compiler.VariableBinder.MergeScopes (Expression node) inline private
Definition at line 152 of file VariableBinder.cs.
    {
        ReadOnlyCollection<Expression> readOnlyCollection = ((!(node is LambdaExpression lambdaExpression)) ? ((BlockExpression)node).Expressions : new ReadOnlyCollection<Expression>(new Expression[1] { lambdaExpression.Body }));
        CompilerScope compilerScope = _scopes.Peek();
        while (readOnlyCollection.Count == 1 && readOnlyCollection[0].NodeType == ExpressionType.Block)
        {
            BlockExpression blockExpression = (BlockExpression)readOnlyCollection[0];
            if (blockExpression.Variables.Count > 0)
            {
                foreach (ParameterExpression variable in blockExpression.Variables)
                {
                    if (compilerScope.Definitions.ContainsKey(variable))
                    {
                        return readOnlyCollection;
                    }
                }
                if (compilerScope.MergedScopes == null)
                {
                    compilerScope.MergedScopes = new HashSet<BlockExpression>(ReferenceEqualityComparer.Instance);
                }
                compilerScope.MergedScopes.Add(blockExpression);
                foreach (ParameterExpression variable2 in blockExpression.Variables)
                {
                    compilerScope.Definitions.Add(variable2, VariableStorageKind.Local);
                }
            }
            readOnlyCollection = blockExpression.Expressions;
        }
        return readOnlyCollection;
    }
References System.Linq.Expressions.Compiler.VariableBinder._scopes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Collections.Generic.ReferenceEqualityComparer.Instance.
Referenced by System.Linq.Expressions.Compiler.VariableBinder.VisitBlock(), System.Linq.Expressions.Compiler.VariableBinder.VisitInvocation(), and System.Linq.Expressions.Compiler.VariableBinder.VisitLambda< T >().