Terraria: System.Security.AccessControl.Win32.GetSecurityInfo
GetSecurityInfo()
static int System.Security.AccessControl.Win32.GetSecurityInfo (ResourceType resourceType, string name, SafeHandle handle, AccessControlSections accessControlSections, out RawSecurityDescriptor resultSd) inline static package
Definition at line 26 of file Win32.cs.
    {
        resultSd = null;
        SecurityInfos securityInfos = (SecurityInfos)0;
        Privilege privilege = null;
        if ((accessControlSections & AccessControlSections.Owner) != 0)
        {
            securityInfos |= SecurityInfos.Owner;
        }
        if ((accessControlSections & AccessControlSections.Group) != 0)
        {
            securityInfos |= SecurityInfos.Group;
        }
        if ((accessControlSections & AccessControlSections.Access) != 0)
        {
            securityInfos |= SecurityInfos.DiscretionaryAcl;
        }
        if ((accessControlSections & AccessControlSections.Audit) != 0)
        {
            securityInfos |= SecurityInfos.SystemAcl;
            privilege = new Privilege("SeSecurityPrivilege");
        }
        int num;
        IntPtr securityDescriptor;
        try
        {
            if (privilege != null)
            {
                try
                {
                    privilege.Enable();
                }
                catch (PrivilegeNotHeldException)
                {
                }
            }
            IntPtr sidOwner;
            IntPtr sidGroup;
            IntPtr dacl;
            IntPtr sacl;
            if (name != null)
            {
                num = (int)global::Interop.Advapi32.GetSecurityInfoByName(name, (uint)resourceType, (uint)securityInfos, out sidOwner, out sidGroup, out dacl, out sacl, out securityDescriptor);
            }
            else
            {
                if (handle == null)
                {
                    throw new ArgumentException();
                }
                if (handle.IsInvalid)
                {
                    throw new ArgumentException(System.SR.Argument_InvalidSafeHandle, "handle");
                }
                num = (int)global::Interop.Advapi32.GetSecurityInfoByHandle(handle, (uint)resourceType, (uint)securityInfos, out sidOwner, out sidGroup, out dacl, out sacl, out securityDescriptor);
            }
            if (num == 0 && IntPtr.Zero.Equals(securityDescriptor))
            {
                throw new InvalidOperationException(System.SR.InvalidOperation_NoSecurityDescriptor);
            }
            switch (num)
            {
            case 1300:
            case 1314:
                throw new PrivilegeNotHeldException("SeSecurityPrivilege");
            case 5:
            case 1347:
                throw new UnauthorizedAccessException();
            case 0:
                break;
            default:
                goto IL_013f;
            }
        }
        catch
        {
            privilege?.Revert();
            throw;
        }
        finally
        {
            privilege?.Revert();
        }
        uint securityDescriptorLength = global::Interop.Advapi32.GetSecurityDescriptorLength(securityDescriptor);
        byte[] array = new byte[securityDescriptorLength];
        Marshal.Copy(securityDescriptor, array, 0, (int)securityDescriptorLength);
        Marshal.FreeHGlobal(securityDescriptor);
        resultSd = new RawSecurityDescriptor(array, 0);
        return 0;
        IL_013f:
        if (num == 8)
        {
            throw new OutOfMemoryException();
        }
        return num;
    }
References System.SR.Argument_InvalidSafeHandle, System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Security.AccessControl.Privilege.Enable(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.handle, System.SR.InvalidOperation_NoSecurityDescriptor, System.Security.AccessControl.Privilege.Revert(), and System.IntPtr.Zero.
Referenced by System.Security.AccessControl.NativeObjectSecurity.CreateInternal().