Terraria: System.Security.AccessControl.Win32.SetSecurityInfo
SetSecurityInfo()
static int System.Security.AccessControl.Win32.SetSecurityInfo (ResourceType type, string name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl) inline static package
Definition at line 123 of file Win32.cs.
    {
        byte[] array = null;
        byte[] array2 = null;
        byte[] array3 = null;
        byte[] array4 = null;
        Privilege privilege = null;
        if (owner != null)
        {
            int binaryLength = owner.BinaryLength;
            array = new byte[binaryLength];
            owner.GetBinaryForm(array, 0);
        }
        if (group != null)
        {
            int binaryLength = group.BinaryLength;
            array2 = new byte[binaryLength];
            group.GetBinaryForm(array2, 0);
        }
        if (dacl != null)
        {
            int binaryLength = dacl.BinaryLength;
            array4 = new byte[binaryLength];
            dacl.GetBinaryForm(array4, 0);
        }
        if (sacl != null)
        {
            int binaryLength = sacl.BinaryLength;
            array3 = new byte[binaryLength];
            sacl.GetBinaryForm(array3, 0);
        }
        if ((securityInformation & SecurityInfos.SystemAcl) != 0)
        {
            privilege = new Privilege("SeSecurityPrivilege");
        }
        int num;
        try
        {
            if (privilege != null)
            {
                try
                {
                    privilege.Enable();
                }
                catch (PrivilegeNotHeldException)
                {
                }
            }
            if (name != null)
            {
                num = (int)global::Interop.Advapi32.SetSecurityInfoByName(name, (uint)type, (uint)securityInformation, array, array2, array4, array3);
            }
            else
            {
                if (handle == null)
                {
                    throw new ArgumentException();
                }
                if (handle.IsInvalid)
                {
                    throw new ArgumentException(System.SR.Argument_InvalidSafeHandle, "handle");
                }
                num = (int)global::Interop.Advapi32.SetSecurityInfoByHandle(handle, (uint)type, (uint)securityInformation, array, array2, array4, array3);
            }
            switch (num)
            {
            case 1300:
            case 1314:
                throw new PrivilegeNotHeldException("SeSecurityPrivilege");
            case 5:
            case 1347:
                throw new UnauthorizedAccessException();
            case 0:
                break;
            default:
                goto IL_0145;
            }
        }
        catch
        {
            privilege?.Revert();
            throw;
        }
        finally
        {
            privilege?.Revert();
        }
        return 0;
        IL_0145:
        if (num == 8)
        {
            throw new OutOfMemoryException();
        }
        return num;
    }
References System.SR.Argument_InvalidSafeHandle, System.array, System.Security.AccessControl.GenericAcl.BinaryLength, System.Security.Principal.SecurityIdentifier.BinaryLength, System.Security.AccessControl.Privilege.Enable(), System.Security.AccessControl.GenericAcl.GetBinaryForm(), System.Security.Principal.SecurityIdentifier.GetBinaryForm(), System.handle, System.Security.AccessControl.Privilege.Revert(), and System.type.
Referenced by System.Security.AccessControl.NativeObjectSecurity.Persist().