Terraria: System.Security.AccessControl.Win32.ConvertSdToSddl
ConvertSdToSddl()
static int System.Security.AccessControl.Win32.ConvertSdToSddl (byte[] binaryForm, int requestedRevision, SecurityInfos si, out string resultSddl) inline static package
Definition at line 8 of file Win32.cs.
    {
        uint resultStringLength = 0u;
        if (!global::Interop.Advapi32.ConvertSdToStringSd(binaryForm, (uint)requestedRevision, (uint)si, out var resultString, ref resultStringLength))
        {
            int lastWin32Error = Marshal.GetLastWin32Error();
            resultSddl = null;
            if (lastWin32Error == 8)
            {
                throw new OutOfMemoryException();
            }
            return lastWin32Error;
        }
        resultSddl = Marshal.PtrToStringUni(resultString);
        Marshal.FreeHGlobal(resultString);
        return 0;
    }
References System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), and System.Runtime.InteropServices.Marshal.PtrToStringUni().
Referenced by System.Security.AccessControl.GenericSecurityDescriptor.GetSddlForm().