Terraria: System.Linq.Expressions.Compiler.VariableBinder._tree
_tree
readonly AnalyzedTree System.Linq.Expressions.Compiler.VariableBinder._tree = new AnalyzedTree() private
Definition at line 10 of file VariableBinder.cs.
Referenced by System.Linq.Expressions.Compiler.VariableBinder.VisitBlock(), System.Linq.Expressions.Compiler.VariableBinder.VisitCatchBlock(), System.Linq.Expressions.Compiler.VariableBinder.VisitInvocation(), and System.Linq.Expressions.Compiler.VariableBinder.VisitLambda< T >().