Terraria: GenCondition.AreaOr
AreaOr()
GenCondition GenCondition.AreaOr (int width, int height) inline
     {
         _areaType = AreaType.Or;
         _width = width;
         _height = height;
         return this;
     }
References _areaType, _height, and _width.
Referenced by HouseBuilder.FindSideExit(), HouseBuilder.FindVerticalExit(), EnchantedSwordBiome.Place(), and MahoganyTreeBiome.Place().