Terraria: System.Runtime.CompilerServices.Unsafe.CopyBlock
CopyBlock() [2/2]
static unsafe void System.Runtime.CompilerServices.Unsafe.CopyBlock (void * destination, void * source, uint byteCount) inline static
Definition at line 85 of file Unsafe.cs.
    {
        // IL cpblk instruction
        Unsafe.CopyBlock(destination, source, byteCount);
    }
References System.byteCount, System.Runtime.CompilerServices.Unsafe.CopyBlock(), System.destination, and System.source.
Referenced by System.Runtime.CompilerServices.Unsafe.CopyBlock(), System.Runtime.CompilerServices.Unsafe.CopyBlock(), and Microsoft.Xna.Framework.Graphics.GuideRenderer.ReplayDrawingCommands().