Terraria: System.Runtime.CompilerServices.Unsafe.InitBlock
InitBlock() [2/2]
static unsafe void System.Runtime.CompilerServices.Unsafe.InitBlock (void * startAddress, byte value, uint byteCount) inline static
Definition at line 117 of file Unsafe.cs.
    {
        // IL initblk instruction
        Unsafe.InitBlock(startAddress, value, byteCount);
    }
References System.byteCount, System.Runtime.CompilerServices.Unsafe.InitBlock(), and System.value.
Referenced by Microsoft.Xna.Framework.Graphics.TextureCube.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyData< T >(), Microsoft.Xna.Framework.Graphics.VertexBuffer.CopyData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.CopyData< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDevice(), System.Runtime.CompilerServices.Unsafe.InitBlock(), System.Runtime.CompilerServices.Unsafe.InitBlock(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AsciiPreescapedData.PopulatePreescapedData(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset().