Terraria: System.Xml.Xsl.IlGen.XmlILConstructInfo.Read
Read()
static XmlILConstructInfo System.Xml.Xsl.IlGen.XmlILConstructInfo.Read (QilNode nd) inline static
Definition at line 238 of file XmlILConstructInfo.cs.
    {
        XmlILConstructInfo xmlILConstructInfo = ((nd.Annotation is XmlILAnnotation xmlILAnnotation) ? xmlILAnnotation.ConstructInfo : null);
        if (xmlILConstructInfo == null)
        {
            if (s_default == null)
            {
                xmlILConstructInfo = new XmlILConstructInfo(QilNodeType.Unknown);
                xmlILConstructInfo._isReadOnly = true;
                s_default = xmlILConstructInfo;
            }
            else
            {
                xmlILConstructInfo = s_default;
            }
        }
        return xmlILConstructInfo;
    }
References System.Xml.Xsl.IlGen.XmlILConstructInfo.XmlILConstructInfo(), System.Xml.Dictionary, and System.Xml.Xsl.IlGen.XmlILConstructInfo.s_default.
Referenced by System.Xml.Xsl.IlGen.XmlILVisitor.AfterEndChecks(), System.Xml.Xsl.IlGen.TailCallAnalyzer.Analyze(), System.Xml.Xsl.IlGen.TailCallAnalyzer.AnalyzeDefinition(), System.Xml.Xsl.IlGen.XmlILVisitor.BeforeStartChecks(), System.Xml.Xsl.XmlILGenerator.CreateFunctionMetadata(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.EliminateUnusedGlobals(), System.Xml.Xsl.IlGen.XmlILVisitor.EndWriterLoop(), System.Xml.Xsl.IlGen.XmlILVisitor.Function(), System.Xml.Xsl.IlGen.XmlILVisitor.NestedVisit(), System.Xml.Xsl.IlGen.XmlILVisitor.StartWriterLoop(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Visit(), System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitAttributeCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitConditional(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitElementCtor(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitError(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitInvoke(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNamespaceDecl(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitNamespaceDecl(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitSequence(), System.Xml.Xsl.IlGen.XmlILVisitor.VisitTextCtor(), and System.Xml.Xsl.IlGen.XmlILVisitor.VisitWarning().