Terraria: System.Xml.Int32ArrayHelperWithString.Instance
Instance
readonly Int32ArrayHelperWithString System.Xml.Int32ArrayHelperWithString.Instance = new Int32ArrayHelperWithString() static
Definition at line 5 of file Int32ArrayHelperWithString.cs.
Referenced by System.Xml.XmlBaseReader.ReadInt32Array(), System.Xml.XmlDictionaryReader.ReadInt32Array(), and System.Xml.XmlDictionaryWriter.WriteArrayNode().