Terraria: System.Net.Security.NetSecurityTelemetry.HandshakeFailed
HandshakeFailed() [2/2]
void System.Net.Security.NetSecurityTelemetry.HandshakeFailed (bool isServer, ValueStopwatch stopwatch, string exceptionMessage) inline
Definition at line 196 of file NetSecurityTelemetry.cs.
    {
        Interlocked.Increment(ref _finishedTlsHandshakes);
        Interlocked.Increment(ref _failedTlsHandshakes);
        if (IsEnabled(EventLevel.Error, EventKeywords.None))
        {
            HandshakeFailed(isServer, stopwatch.GetElapsedTime().TotalMilliseconds, exceptionMessage);
        }
        HandshakeStop(SslProtocols.None);
    }
References System.Net.Security.NetSecurityTelemetry._failedTlsHandshakes, System.Net.Security.NetSecurityTelemetry._finishedTlsHandshakes, Microsoft.Extensions.Internal.ValueStopwatch.GetElapsedTime(), System.Net.Security.NetSecurityTelemetry.HandshakeFailed(), System.Net.Security.NetSecurityTelemetry.HandshakeStop(), System.Threading.Interlocked.Increment(), and System.Diagnostics.Tracing.EventSource.IsEnabled().