Terraria: System.Net.Security.NetSecurityTelemetry.HandshakeCompleted
HandshakeCompleted()
void System.Net.Security.NetSecurityTelemetry.HandshakeCompleted (SslProtocols protocol, ValueStopwatch stopwatch, bool connectionOpen) inline
Definition at line 208 of file NetSecurityTelemetry.cs.
    {
        Interlocked.Increment(ref _finishedTlsHandshakes);
        long num = 0L;
        ref long location = ref num;
        EventCounter eventCounter = null;
        switch (protocol)
        {
        case SslProtocols.Tls:
            location = ref _sessionsOpenTls10;
            eventCounter = _handshakeDurationTls10Counter;
            break;
        case SslProtocols.Tls11:
            location = ref _sessionsOpenTls11;
            eventCounter = _handshakeDurationTls11Counter;
            break;
        case SslProtocols.Tls12:
            location = ref _sessionsOpenTls12;
            eventCounter = _handshakeDurationTls12Counter;
            break;
        case SslProtocols.Tls13:
            location = ref _sessionsOpenTls13;
            eventCounter = _handshakeDurationTls13Counter;
            break;
        }
        if (connectionOpen)
        {
            Interlocked.Increment(ref location);
            Interlocked.Increment(ref _sessionsOpen);
        }
        double totalMilliseconds = stopwatch.GetElapsedTime().TotalMilliseconds;
        eventCounter?.WriteMetric(totalMilliseconds);
        _handshakeDurationCounter.WriteMetric(totalMilliseconds);
        HandshakeStop(protocol);
    }
References System.Net.Security.NetSecurityTelemetry._finishedTlsHandshakes, System.Net.Security.NetSecurityTelemetry._handshakeDurationCounter, System.Net.Security.NetSecurityTelemetry._handshakeDurationTls10Counter, System.Net.Security.NetSecurityTelemetry._handshakeDurationTls11Counter, System.Net.Security.NetSecurityTelemetry._handshakeDurationTls12Counter, System.Net.Security.NetSecurityTelemetry._handshakeDurationTls13Counter, System.Net.Security.NetSecurityTelemetry._sessionsOpen, System.Net.Security.NetSecurityTelemetry._sessionsOpenTls10, System.Net.Security.NetSecurityTelemetry._sessionsOpenTls11, System.Net.Security.NetSecurityTelemetry._sessionsOpenTls12, System.Net.Security.NetSecurityTelemetry._sessionsOpenTls13, Microsoft.Extensions.Internal.ValueStopwatch.GetElapsedTime(), System.Net.Security.NetSecurityTelemetry.HandshakeStop(), System.Threading.Interlocked.Increment(), System.L, and System.Diagnostics.Tracing.EventCounter.WriteMetric().