Terraria: System.Net.Security.NetSecurityTelemetry.HandshakeStart
HandshakeStart()
void System.Net.Security.NetSecurityTelemetry.HandshakeStart (bool isServer, string targetHost) inline
Definition at line 171 of file NetSecurityTelemetry.cs.
    {
        Interlocked.Increment(ref _startedTlsHandshakes);
        if (IsEnabled(EventLevel.Informational, EventKeywords.None))
        {
            WriteEvent(1, isServer, targetHost);
        }
    }
References System.Net.Security.NetSecurityTelemetry._startedTlsHandshakes, System.Threading.Interlocked.Increment(), System.Diagnostics.Tracing.EventSource.IsEnabled(), and System.Net.Security.NetSecurityTelemetry.WriteEvent().