Terraria: System.HashCode.Round
Round()
static uint System.HashCode.Round (uint hash, uint input) inline static private
Definition at line 180 of file HashCode.cs.
    {
        return BitOperations.RotateLeft(hash + (uint)((int)input * -2048144777), 13) * 2654435761u;
    }
References System.input, and System.Numerics.BitOperations.RotateLeft().
Referenced by System.HashCode.Add(), System.HashCode.Combine< T1, T2, T3, T4 >(), System.HashCode.Combine< T1, T2, T3, T4, T5 >(), System.HashCode.Combine< T1, T2, T3, T4, T5, T6 >(), System.HashCode.Combine< T1, T2, T3, T4, T5, T6, T7 >(), and System.HashCode.Combine< T1, T2, T3, T4, T5, T6, T7, T8 >().