Terraria: System.HashCode.Combine< T1, T2, T3, T4, T5, T6 >
Combine< T1, T2, T3, T4, T5, T6 >()
static int System.HashCode.Combine< T1, T2, T3, T4, T5, T6 > (T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, T6 value6) inline static
Definition at line 104 of file HashCode.cs.
    {
        uint input = (uint)(value1?.GetHashCode() ?? 0);
        uint input2 = (uint)(value2?.GetHashCode() ?? 0);
        uint input3 = (uint)(value3?.GetHashCode() ?? 0);
        uint input4 = (uint)(value4?.GetHashCode() ?? 0);
        uint queuedValue = (uint)(value5?.GetHashCode() ?? 0);
        uint queuedValue2 = (uint)(value6?.GetHashCode() ?? 0);
        Initialize(out var v, out var v2, out var v3, out var v4);
        v = Round(v, input);
        v2 = Round(v2, input2);
        v3 = Round(v3, input3);
        v4 = Round(v4, input4);
        uint num = MixState(v, v2, v3, v4);
        num += 24;
        num = QueueRound(num, queuedValue);
        num = QueueRound(num, queuedValue2);
        return (int)MixFinal(num);
    }
References System.HashCode.GetHashCode(), System.HashCode.Initialize(), System.input, System.HashCode.MixFinal(), System.HashCode.MixState(), System.HashCode.QueueRound(), and System.HashCode.Round().