Terraria: System.HashCode.ToHashCode
ToHashCode()
int System.HashCode.ToHashCode () inline
Definition at line 264 of file HashCode.cs.
    {
        uint length = _length;
        uint num = length % 4;
        uint num2 = ((length < 4) ? MixEmptyState() : MixState(_v1, _v2, _v3, _v4));
        num2 += length * 4;
        if (num != 0)
        {
            num2 = QueueRound(num2, _queue1);
            if (num > 1)
            {
                num2 = QueueRound(num2, _queue2);
                if (num > 2)
                {
                    num2 = QueueRound(num2, _queue3);
                }
            }
        }
        return (int)MixFinal(num2);
    }
References System.HashCode._length, System.HashCode._queue1, System.HashCode._queue2, System.HashCode._queue3, System.HashCode._v1, System.HashCode._v2, System.HashCode._v3, System.HashCode._v4, System.length, System.HashCode.MixEmptyState(), System.HashCode.MixFinal(), System.HashCode.MixState(), and System.HashCode.QueueRound().
Referenced by System.Diagnostics.Metrics.ObjectSequenceMany.GetHashCode(), System.Diagnostics.Metrics.StringSequenceMany.GetHashCode(), System.Diagnostics.ActivityLink.GetHashCode(), System.Numerics.Matrix4x4.GetHashCode(), and System.Array.GetHashCode().