Terraria: System.HashCode.Combine< T1, T2 >
Combine< T1, T2 >()
static int System.HashCode.Combine< T1, T2 > (T1 value1, T2 value2) inline static
Definition at line 46 of file HashCode.cs.
    {
        uint queuedValue = (uint)(value1?.GetHashCode() ?? 0);
        uint queuedValue2 = (uint)(value2?.GetHashCode() ?? 0);
        uint num = MixEmptyState();
        num += 8;
        num = QueueRound(num, queuedValue);
        num = QueueRound(num, queuedValue2);
        return (int)MixFinal(num);
    }
References System.HashCode.GetHashCode(), System.HashCode.MixEmptyState(), System.HashCode.MixFinal(), and System.HashCode.QueueRound().