Terraria: System.HashCode.Add
Add()
void System.HashCode.Add (int value) inline private
Definition at line 239 of file HashCode.cs.
    {
        uint num = _length++;
        switch (num % 4)
        {
        case 0u:
            _queue1 = (uint)value;
            return;
        case 1u:
            _queue2 = (uint)value;
            return;
        case 2u:
            _queue3 = (uint)value;
            return;
        }
        if (num == 3)
        {
            Initialize(out _v1, out _v2, out _v3, out _v4);
        }
        _v1 = Round(_v1, _queue1);
        _v2 = Round(_v2, _queue2);
        _v3 = Round(_v3, _queue3);
        _v4 = Round(_v4, (uint)value);
    }
References System.HashCode._length, System.HashCode._queue1, System.HashCode._queue2, System.HashCode._queue3, System.HashCode._v1, System.HashCode._v2, System.HashCode._v3, System.HashCode._v4, System.HashCode.Initialize(), System.HashCode.Round(), and System.value.
Referenced by System.Diagnostics.Metrics.ObjectSequenceMany.GetHashCode(), System.Diagnostics.Metrics.StringSequenceMany.GetHashCode(), System.Diagnostics.ActivityLink.GetHashCode(), System.Numerics.Matrix4x4.GetHashCode(), System.Numerics.Vector< T >.GetHashCode(), System.Runtime.Intrinsics.Vector128< T >.GetHashCode(), System.Runtime.Intrinsics.Vector256< T >.GetHashCode(), System.Runtime.Intrinsics.Vector64< T >.GetHashCode(), and System.Array.GetHashCode().