Terraria: Terraria.GameContent.Creative.CreativeUI.DrawToggleButton
DrawToggleButton()
void Terraria.GameContent.Creative.CreativeUI.DrawToggleButton (SpriteBatch spritebatch, Vector2 location) inline private
Definition at line 142 of file CreativeUI.cs.
    {
        Vector2 vector = _buttonTexture.Size();
        Rectangle rectangle = Utils.CenteredRectangle(location + vector / 2f, vector);
        UILinkPointNavigator.SetPosition(311, rectangle.Center.ToVector2());
        spritebatch.Draw(_buttonTexture.Value, location, null, Color.White, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
        Main.LocalPlayer.creativeInterface = false;
        if (rectangle.Contains(Main.MouseScreen.ToPoint()))
        {
            Main.LocalPlayer.creativeInterface = true;
            Main.LocalPlayer.mouseInterface = true;
            if (Enabled)
            {
                Main.instance.MouseText(Language.GetTextValue("CreativePowers.PowersMenuOpen"), 0, 0);
            }
            else
            {
                Main.instance.MouseText(Language.GetTextValue("CreativePowers.PowersMenuClosed"), 0, 0);
            }
            spritebatch.Draw(_buttonBorderTexture.Value, location, null, Color.White, 0f, Vector2.Zero, 1f, SpriteEffects.None, 0f);
            if (Main.mouseLeft && Main.mouseLeftRelease)
            {
                ToggleMenu();
            }
        }
    }
References Terraria.GameContent.Creative.CreativeUI._buttonBorderTexture, Terraria.GameContent.Creative.CreativeUI._buttonTexture, Terraria.Utils.CenteredRectangle(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), Terraria.GameContent.Creative.CreativeUI.Enabled, Terraria.Localization.Language.GetTextValue(), Terraria.Main.instance, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.GameContent.Creative.CreativeUI.ToggleMenu(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Creative.CreativeUI.Draw().