Terraria: Terraria.GameContent.Creative.CreativeUI.SacrificeItem
SacrificeItem()
ItemSacrificeResult Terraria.GameContent.Creative.CreativeUI.SacrificeItem (out int amountWeSacrificed) inline
Definition at line 267 of file CreativeUI.cs.
    {
        int amountNeededTotal = 0;
        int amountWeHave = 0;
        amountWeSacrificed = 0;
        Item item = _itemSlotsForUI[0];
        if (!Main.LocalPlayerCreativeTracker.ItemSacrifices.TryGetSacrificeNumbers(item.type, out amountWeHave, out amountNeededTotal))
        {
            return ItemSacrificeResult.CannotSacrifice;
        }
        int num = Utils.Clamp(amountNeededTotal - amountWeHave, 0, amountNeededTotal);
        if (num == 0)
        {
            return ItemSacrificeResult.CannotSacrifice;
        }
        int num2 = Math.Min(num, item.stack);
        if (!Main.ServerSideCharacter)
        {
            Main.LocalPlayerCreativeTracker.ItemSacrifices.RegisterItemSacrifice(item.type, num2);
        }
        else
        {
            NetPacket packet = NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(item.type, num2);
            NetManager.Instance.SendToServerOrLoopback(packet);
        }
        bool num3 = num2 == num;
        item.stack -= num2;
        if (item.stack <= 0)
        {
            item.TurnToAir();
        }
        amountWeSacrificed = num2;
        RefreshAvailableInfiniteItemsList();
        if (item.stack > 0)
        {
            item.position.X = Main.player[Main.myPlayer].Center.X - (float)(item.width / 2);
            item.position.Y = Main.player[Main.myPlayer].Center.Y - (float)(item.height / 2);
            _itemSlotsForUI[0] = Main.LocalPlayer.GetItem(Main.myPlayer, item, GetItemSettings.InventoryUIToInventorySettings);
        }
        if (!num3)
        {
            return ItemSacrificeResult.SacrificedButNotDone;
        }
        return ItemSacrificeResult.SacrificedAndDone;
    }
References Terraria.GameContent.Creative.CreativeUI._itemSlotsForUI, Terraria.Net.NetManager.Instance, Terraria.GetItemSettings.InventoryUIToInventorySettings, System.item, Terraria.Main.LocalPlayer, Terraria.Main.LocalPlayerCreativeTracker, System.Math.Min(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.GameContent.Creative.CreativeUI.RefreshAvailableInfiniteItemsList(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(), and Terraria.Main.ServerSideCharacter.