Terraria: Terraria.GameContent.Creative.CreativeUI.Draw
Draw()
void Terraria.GameContent.Creative.CreativeUI.Draw (SpriteBatch spriteBatch) inline
Definition at line 88 of file CreativeUI.cs.
    {
        if (!_initialized)
        {
            Initialize();
        }
        if (Main.LocalPlayer.difficulty != 3)
        {
            Enabled = false;
        }
        else if (!Blocked)
        {
            Vector2 location = new Vector2(28f, 267f);
            Vector2 vector = new Vector2(353f, 258f);
            new Vector2(40f, 267f);
            _ = vector + new Vector2(50f, 50f);
            if (Main.screenHeight < 650 && Enabled)
            {
                location.X += 52f * Main.inventoryScale;
            }
            DrawToggleButton(spriteBatch, location);
            if (Enabled)
            {
                _powersUI.Draw(spriteBatch, Main.gameTimeCache);
            }
        }
    }
References Terraria.GameContent.Creative.CreativeUI._initialized, Terraria.GameContent.Creative.CreativeUI._powersUI, Terraria.GameContent.Creative.CreativeUI.Blocked, Terraria.UI.UserInterface.Draw(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.GameContent.Creative.CreativeUI.Enabled, Terraria.Main.gameTimeCache, Terraria.GameContent.Creative.CreativeUI.Initialize(), Terraria.Main.inventoryScale, Terraria.Main.LocalPlayer, and Terraria.Main.screenHeight.