Terraria: System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.PropertyFetch.FetcherForProperty
FetcherForProperty()
static PropertyFetch System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.PropertyFetch.FetcherForProperty (Type type, string propertyName) inline static inherited
Definition at line 701 of file DiagnosticSourceEventSource.cs.
                {
                    if (propertyName == null)
                    {
                        return new PropertyFetch(type);
                    }
                    if (propertyName == "*Activity")
                    {
                        return new CurrentActivityPropertyFetch();
                    }
                    TypeInfo typeInfo = type.GetTypeInfo();
                    if (propertyName == "*Enumerate")
                    {
                        Type[] interfaces = typeInfo.GetInterfaces();
                        foreach (Type type2 in interfaces)
{
                            TypeInfo typeInfo2 = type2.GetTypeInfo();
                            if (typeInfo2.IsGenericType && !(typeInfo2.GetGenericTypeDefinition() != typeof(IEnumerable<>)))
{
                                Type type3 = typeInfo2.GetGenericArguments()[0];
                                Type type4 = typeof(EnumeratePropertyFetch<>).GetTypeInfo().MakeGenericType(type3);
                                return (PropertyFetch)Activator.CreateInstance(type4, type);
                            }
                        }
                        Log.Message($"*Enumerate applied to non-enumerable type {type}");
                        return new PropertyFetch(type);
                    }
                    PropertyInfo propertyInfo = typeInfo.GetDeclaredProperty(propertyName);
                    if (propertyInfo == null)
                    {
                        PropertyInfo[] properties = typeInfo.GetProperties(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
                        foreach (PropertyInfo propertyInfo2 in properties)
{
                            if (propertyInfo2.Name == propertyName)
{
                                propertyInfo = propertyInfo2;
                                break;
                            }
                        }
                    }
                    if (propertyInfo == null)
                    {
                        Log.Message($"Property {propertyName} not found on {type}. Ensure the name is spelled correctly. If you published the application with PublishTrimmed=true, ensure the property was not trimmed away.");
                        return new PropertyFetch(type);
                    }
                    MethodInfo? getMethod = propertyInfo.GetMethod;
                    if ((object)getMethod == null || !getMethod.IsStatic)
                    {
                        MethodInfo? setMethod = propertyInfo.SetMethod;
                        if ((object)setMethod == null || !setMethod.IsStatic)
{
                            Type type5 = (typeInfo.IsValueType ? typeof(ValueTypedFetchProperty<, >) : typeof(RefTypedFetchProperty<, >));
                            Type type6 = type5.GetTypeInfo().MakeGenericType(propertyInfo.DeclaringType, propertyInfo.PropertyType);
                            return (PropertyFetch)Activator.CreateInstance(type6, type, propertyInfo);
                        }
                    }
                    Log.Message("Property " + propertyName + " is static.");
                    return new PropertyFetch(type);
                }
References System.Activator.CreateInstance(), System.Reflection.MemberInfo.DeclaringType, System.Reflection.TypeInfo.GetDeclaredProperty(), System.Type.GetInterfaces(), System.Reflection.PropertyInfo.GetMethod, System.Type.GetProperties(), System.Reflection.PropertyInfo.PropertyType, System.Reflection.PropertyInfo.SetMethod, and System.type.
Referenced by System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.Fetch().