Terraria: System.Xml.DocumentXPathNavigator.DeleteAttribute
DeleteAttribute()
static void System.Xml.DocumentXPathNavigator.DeleteAttribute (XmlAttribute attribute, int index) inline static private
Definition at line 1580 of file DocumentXPathNavigator.cs.
    {
        if (!CheckAttributePosition(attribute, out var attributes, index) && !ResetAttributePosition(attribute, attributes, out index))
        {
            throw new InvalidOperationException(System.SR.Xpn_MissingParent);
        }
        if (attribute.IsReadOnly)
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Modify_ReadOnly);
        }
        attributes.RemoveAt(index);
    }
References System.Xml.DocumentXPathNavigator.CheckAttributePosition(), System.index, System.Collections.Generic.Dictionary< TKey, TValue >.IsReadOnly, System.Xml.DocumentXPathNavigator.ResetAttributePosition(), System.SR.Xdom_Node_Modify_ReadOnly, and System.SR.Xpn_MissingParent.
Referenced by System.Xml.DocumentXPathNavigator.DeleteRange(), and System.Xml.DocumentXPathNavigator.DeleteSelf().