Terraria: System.Xml.DocumentXPathNavigator.ParentNode
ParentNode()
XmlNode System.Xml.DocumentXPathNavigator.ParentNode (XmlNode node) inline private
Definition at line 1704 of file DocumentXPathNavigator.cs.
    {
        XmlNode parentNode = node.ParentNode;
        if (!_document.HasEntityReferences)
        {
            return parentNode;
        }
        return ParentNodeTail(parentNode);
    }
References System.Xml.DocumentXPathNavigator._document, System.Xml.XmlDocument.HasEntityReferences, and System.Xml.DocumentXPathNavigator.ParentNodeTail().
Referenced by System.Xml.DocumentXPathNavigator.MoveToFirst(), System.Xml.DocumentXPathNavigator.MoveToNext(), System.Xml.DocumentXPathNavigator.MoveToParent(), and System.Xml.DocumentXPathNavigator.MoveToPrevious().