Terraria: System.Xml.DocumentXPathNavigator.FirstChild
FirstChild()
XmlNode System.Xml.DocumentXPathNavigator.FirstChild (XmlNode node) inline private
Definition at line 1723 of file DocumentXPathNavigator.cs.
    {
        XmlNode firstChild = node.FirstChild;
        if (!_document.HasEntityReferences)
        {
            return firstChild;
        }
        return FirstChildTail(firstChild);
    }
References System.Xml.DocumentXPathNavigator._document, System.Xml.Dictionary, System.Xml.DocumentXPathNavigator.FirstChildTail(), and System.Xml.XmlDocument.HasEntityReferences.
Referenced by System.Xml.DocumentXPathNavigator.MoveToChild(), System.Xml.DocumentXPathNavigator.MoveToChild(), System.Xml.DocumentXPathNavigator.MoveToFirst(), and System.Xml.DocumentXPathNavigator.MoveToFirstChild().