Terraria: System.Xml.DocumentXPathNavigator.SetValue
SetValue()
override void System.Xml.DocumentXPathNavigator.SetValue (string value) inline virtual
Reimplemented from System.Xml.XPath.XPathNavigator.
Definition at line 246 of file DocumentXPathNavigator.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        XmlNode source = _source;
        switch (source.NodeType)
        {
        case XmlNodeType.Attribute:
            if (!((XmlAttribute)source).IsNamespace)
            {
                source.InnerText = value;
                return;
            }
            break;
        case XmlNodeType.Text:
        case XmlNodeType.CDATA:
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
        {
            CalibrateText();
            source = _source;
            XmlNode xmlNode = TextEnd(source);
            if (source != xmlNode)
            {
                if (source.IsReadOnly)
                {
                    throw new InvalidOperationException(System.SR.Xdom_Node_Modify_ReadOnly);
                }
                DeleteToFollowingSibling(source.NextSibling, xmlNode);
            }
            goto case XmlNodeType.Element;
        }
        case XmlNodeType.Element:
        case XmlNodeType.ProcessingInstruction:
        case XmlNodeType.Comment:
            source.InnerText = value;
            return;
        }
        throw new InvalidOperationException(System.SR.Xpn_BadPosition);
    }
References System.Xml.DocumentXPathNavigator._source, System.Xml.DocumentXPathNavigator.CalibrateText(), System.Xml.DocumentXPathNavigator.DeleteToFollowingSibling(), System.Xml.Dictionary, System.source, System.Xml.DocumentXPathNavigator.TextEnd(), System.value, System.SR.Xdom_Node_Modify_ReadOnly, and System.SR.Xpn_BadPosition.