Terraria: System.Xml.DocumentXPathNavigator.DeleteSelf
DeleteSelf()
override void System.Xml.DocumentXPathNavigator.DeleteSelf () inline virtual
Reimplemented from System.Xml.XPath.XPathNavigator.
Definition at line 1534 of file DocumentXPathNavigator.cs.
    {
        XmlNode source = _source;
        XmlNode end = source;
        switch (source.NodeType)
        {
        case XmlNodeType.Attribute:
        {
            XmlAttribute xmlAttribute = (XmlAttribute)source;
            if (!xmlAttribute.IsNamespace)
            {
                XmlNode xmlNode = OwnerNode(xmlAttribute);
                DeleteAttribute(xmlAttribute, _attributeIndex);
                if (xmlNode != null)
                {
                    ResetPosition(xmlNode);
                }
                break;
            }
            goto default;
        }
        case XmlNodeType.Text:
        case XmlNodeType.CDATA:
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            CalibrateText();
            source = _source;
            end = TextEnd(source);
            goto case XmlNodeType.Element;
        case XmlNodeType.Element:
        case XmlNodeType.ProcessingInstruction:
        case XmlNodeType.Comment:
        {
            XmlNode xmlNode = OwnerNode(source);
            DeleteToFollowingSibling(source, end);
            if (xmlNode != null)
            {
                ResetPosition(xmlNode);
            }
            break;
        }
        default:
            throw new InvalidOperationException(System.SR.Xpn_BadPosition);
        }
    }
References System.Xml.DocumentXPathNavigator._attributeIndex, System.Xml.DocumentXPathNavigator._source, System.Xml.DocumentXPathNavigator.CalibrateText(), System.Xml.DocumentXPathNavigator.DeleteAttribute(), System.Xml.DocumentXPathNavigator.DeleteToFollowingSibling(), System.Xml.DocumentXPathNavigator.OwnerNode(), System.Xml.DocumentXPathNavigator.ResetPosition(), System.source, System.Xml.DocumentXPathNavigator.TextEnd(), and System.SR.Xpn_BadPosition.