Terraria: System.Xml.DocumentXPathNavigator.DeleteToFollowingSibling
DeleteToFollowingSibling()
static void System.Xml.DocumentXPathNavigator.DeleteToFollowingSibling (XmlNode node, XmlNode end) inline static package
Definition at line 1593 of file DocumentXPathNavigator.cs.
    {
        XmlNode parentNode = node.ParentNode;
        if (parentNode == null)
        {
            throw new InvalidOperationException(System.SR.Xpn_MissingParent);
        }
        if (node.IsReadOnly || end.IsReadOnly)
        {
            throw new InvalidOperationException(System.SR.Xdom_Node_Modify_ReadOnly);
        }
        while (node != end)
        {
            XmlNode oldChild = node;
            node = node.NextSibling;
            parentNode.RemoveChild(oldChild);
        }
        parentNode.RemoveChild(node);
    }
References System.Xml.Dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.IsReadOnly, System.Xml.XmlNode.IsReadOnly, System.Xml.XmlNode.RemoveChild(), System.SR.Xdom_Node_Modify_ReadOnly, and System.SR.Xpn_MissingParent.
Referenced by System.Xml.DocumentXmlWriter.CloseWithReplaceToFollowingSibling(), System.Xml.DocumentXPathNavigator.DeleteRange(), System.Xml.DocumentXPathNavigator.DeleteSelf(), and System.Xml.DocumentXPathNavigator.SetValue().