Terraria: System.Xml.DocumentXPathNavigator.ComparePosition
ComparePosition() [1/2]
override XmlNodeOrder System.Xml.DocumentXPathNavigator.ComparePosition (XPathNavigator other) inline
Definition at line 1216 of file DocumentXPathNavigator.cs.
    {
        if (!(other is DocumentXPathNavigator documentXPathNavigator))
        {
            return XmlNodeOrder.Unknown;
        }
        CalibrateText();
        documentXPathNavigator.CalibrateText();
        if (_source == documentXPathNavigator._source && _namespaceParent == documentXPathNavigator._namespaceParent)
        {
            return XmlNodeOrder.Same;
        }
        if (_namespaceParent != null || documentXPathNavigator._namespaceParent != null)
        {
            return base.ComparePosition(other);
        }
        XmlNode xmlNode = _source;
        XmlNode xmlNode2 = documentXPathNavigator._source;
        XmlNode xmlNode3 = OwnerNode(xmlNode);
        XmlNode xmlNode4 = OwnerNode(xmlNode2);
        if (xmlNode3 == xmlNode4)
        {
            if (xmlNode3 == null)
            {
                return XmlNodeOrder.Unknown;
            }
            return Compare(xmlNode, xmlNode2);
        }
        int num = GetDepth(xmlNode);
        int num2 = GetDepth(xmlNode2);
        if (num2 > num)
        {
            while (xmlNode2 != null && num2 > num)
            {
                xmlNode2 = OwnerNode(xmlNode2);
                num2--;
            }
            if (xmlNode == xmlNode2)
            {
                return XmlNodeOrder.Before;
            }
            xmlNode4 = OwnerNode(xmlNode2);
        }
        else if (num > num2)
        {
            while (xmlNode != null && num > num2)
            {
                xmlNode = OwnerNode(xmlNode);
                num--;
            }
            if (xmlNode == xmlNode2)
            {
                return XmlNodeOrder.After;
            }
            xmlNode3 = OwnerNode(xmlNode);
        }
        while (xmlNode3 != null && xmlNode4 != null)
        {
            if (xmlNode3 == xmlNode4)
            {
                return Compare(xmlNode, xmlNode2);
            }
            xmlNode = xmlNode3;
            xmlNode2 = xmlNode4;
            xmlNode3 = OwnerNode(xmlNode);
            xmlNode4 = OwnerNode(xmlNode2);
        }
        return XmlNodeOrder.Unknown;
    }
References System.Xml.DocumentXPathNavigator._namespaceParent, System.Xml.DocumentXPathNavigator._source, System.Xml.DocumentXPathNavigator.CalibrateText(), System.Xml.DocumentXPathNavigator.Compare(), System.Xml.Dictionary, System.Xml.DocumentXPathNavigator.GetDepth(), System.other, and System.Xml.DocumentXPathNavigator.OwnerNode().