Terraria: System.Xml.DocumentXPathNavigator.MoveToFollowing
MoveToFollowing() [5/6]
override bool System.Xml.DocumentXPathNavigator.MoveToFollowing (XPathNodeType type, XPathNavigator end) inline
Definition at line 964 of file DocumentXPathNavigator.cs.
    {
        XmlNode xmlNode = null;
        DocumentXPathNavigator documentXPathNavigator = end as DocumentXPathNavigator;
        if (documentXPathNavigator != null)
        {
            if (_document != documentXPathNavigator._document)
            {
                return false;
            }
            XmlNodeType nodeType = documentXPathNavigator._source.NodeType;
            if (nodeType == XmlNodeType.Attribute)
            {
                documentXPathNavigator = (DocumentXPathNavigator)documentXPathNavigator.Clone();
                if (!documentXPathNavigator.MoveToNonDescendant())
                {
                    return false;
                }
            }
            xmlNode = documentXPathNavigator._source;
        }
        int contentKindMask = XPathNavigator.GetContentKindMask(type);
        if (contentKindMask == 0)
        {
            return false;
        }
        XmlNode xmlNode2 = _source;
        switch (xmlNode2.NodeType)
        {
        case XmlNodeType.Attribute:
            xmlNode2 = ((XmlAttribute)xmlNode2).OwnerElement;
            if (xmlNode2 == null)
            {
                return false;
            }
            break;
        case XmlNodeType.Text:
        case XmlNodeType.CDATA:
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            xmlNode2 = TextEnd(xmlNode2);
            break;
        }
        do
        {
            XmlNode firstChild = xmlNode2.FirstChild;
            if (firstChild != null)
            {
                xmlNode2 = firstChild;
            }
            else
            {
                XmlNode nextSibling;
                while (true)
                {
                    nextSibling = xmlNode2.NextSibling;
                    if (nextSibling != null)
                    {
                        break;
                    }
                    XmlNode parentNode = xmlNode2.ParentNode;
                    if (parentNode != null)
                    {
                        xmlNode2 = parentNode;
                        continue;
                    }
                    return false;
                }
                xmlNode2 = nextSibling;
            }
            if (xmlNode2 == xmlNode)
            {
                return false;
            }
        }
        while (((1 << (int)xmlNode2.XPNodeType) & contentKindMask) == 0);
        _source = xmlNode2;
        return true;
    }
References System.Xml.DocumentXPathNavigator.DocumentXPathNavigator(), System.Xml.DocumentXPathNavigator._document, System.Xml.DocumentXPathNavigator._source, System.Xml.Dictionary, System.Xml.XPath.XPathNavigator.GetContentKindMask(), System.Xml.DocumentXPathNavigator.TextEnd(), and System.type.