Terraria: System.Xml.DocumentXPathNavigator.CalibrateText
CalibrateText()
void System.Xml.DocumentXPathNavigator.CalibrateText () inline private
Definition at line 1696 of file DocumentXPathNavigator.cs.
    {
        for (XmlNode xmlNode = PreviousText(_source); xmlNode != null; xmlNode = PreviousText(xmlNode))
        {
            ResetPosition(xmlNode);
        }
    }
References System.Xml.DocumentXPathNavigator._source, System.Xml.DocumentXPathNavigator.PreviousText(), and System.Xml.DocumentXPathNavigator.ResetPosition().
Referenced by System.Xml.DocumentXPathNavigator.ComparePosition(), System.Xml.DocumentXPathNavigator.DeleteRange(), System.Xml.DocumentXPathNavigator.DeleteSelf(), System.Xml.DocumentXPathNavigator.InsertBefore(), System.Xml.DocumentXPathNavigator.IsSamePosition(), System.Xml.DocumentXPathNavigator.ReplaceRange(), and System.Xml.DocumentXPathNavigator.SetValue().