Terraria: System.Xml.DocumentXPathNavigator.GetNamespaceManager
GetNamespaceManager()
static XmlNamespaceManager System.Xml.DocumentXPathNavigator.GetNamespaceManager (XmlNode node, XmlDocument document) inline static private
Definition at line 1613 of file DocumentXPathNavigator.cs.
    {
        XmlNamespaceManager xmlNamespaceManager = new XmlNamespaceManager(document.NameTable);
        List<XmlElement> list = new List<XmlElement>();
        while (node != null)
        {
            if (node is XmlElement { HasAttributes: not false } xmlElement)
            {
                list.Add(xmlElement);
            }
            node = node.ParentNode;
        }
        for (int num = list.Count - 1; num >= 0; num--)
        {
            xmlNamespaceManager.PushScope();
            XmlAttributeCollection attributes = list[num].Attributes;
            for (int i = 0; i < attributes.Count; i++)
            {
                XmlAttribute xmlAttribute = attributes[i];
                if (xmlAttribute.IsNamespace)
                {
                    string prefix = ((xmlAttribute.Prefix.Length == 0) ? string.Empty : xmlAttribute.LocalName);
                    xmlNamespaceManager.AddNamespace(prefix, xmlAttribute.Value);
                }
            }
        }
        return xmlNamespaceManager;
    }
References System.Xml.XmlAttributeCollection.Count, System.Xml.Dictionary, System.Xml.DocumentXPathNavigator.HasAttributes, System.list, and System.prefix.
Referenced by System.Xml.DocumentXPathNavigator.AppendChild(), System.Xml.DocumentXPathNavigator.CreateAttributes(), System.Xml.DocumentXPathNavigator.InsertAfter(), System.Xml.DocumentXPathNavigator.InsertBefore(), System.Xml.DocumentXPathNavigator.PrependChild(), and System.Xml.DocumentXPathNavigator.ReplaceRange().