Terraria: System.Xml.DocumentXPathNavigator.Clone
Clone()
override XPathNavigator System.Xml.DocumentXPathNavigator.Clone () inline
Implements System.ICloneable.
Definition at line 241 of file DocumentXPathNavigator.cs.
    {
        return new DocumentXPathNavigator(this);
    }
References System.Xml.DocumentXPathNavigator.DocumentXPathNavigator().
Referenced by System.Xml.DocumentXPathNodeIterator_ElemDescendants.DocumentXPathNodeIterator_ElemDescendants(), System.Xml.DocumentXPathNodeIterator_ElemDescendants.DocumentXPathNodeIterator_ElemDescendants(), and System.Xml.DocumentXPathNodeIterator_Empty.DocumentXPathNodeIterator_Empty().