Terraria: System.Xml.DocumentXPathNavigator.MoveToFirstNamespace
MoveToFirstNamespace() [2/2]
override bool System.Xml.DocumentXPathNavigator.MoveToFirstNamespace (XPathNamespaceScope scope) inline
Definition at line 426 of file DocumentXPathNavigator.cs.
    {
        if (!(_source is XmlElement xmlElement))
        {
            return false;
        }
        int index = int.MaxValue;
        switch (scope)
        {
        case XPathNamespaceScope.Local:
        {
            if (!xmlElement.HasAttributes)
            {
                return false;
            }
            XmlAttributeCollection attributes = xmlElement.Attributes;
            if (!MoveToFirstNamespaceLocal(attributes, ref index))
            {
                return false;
            }
            _source = attributes[index];
            _attributeIndex = index;
            _namespaceParent = xmlElement;
            break;
        }
        case XPathNamespaceScope.ExcludeXml:
        {
            XmlAttributeCollection attributes = xmlElement.Attributes;
            if (!MoveToFirstNamespaceGlobal(ref attributes, ref index))
            {
                return false;
            }
            XmlAttribute xmlAttribute = attributes[index];
            while (Ref.Equal(xmlAttribute.LocalName, _document.strXml))
            {
                if (!MoveToNextNamespaceGlobal(ref attributes, ref index))
                {
                    return false;
                }
                xmlAttribute = attributes[index];
            }
            _source = xmlAttribute;
            _attributeIndex = index;
            _namespaceParent = xmlElement;
            break;
        }
        case XPathNamespaceScope.All:
        {
            XmlAttributeCollection attributes = xmlElement.Attributes;
            if (!MoveToFirstNamespaceGlobal(ref attributes, ref index))
            {
                _source = _document.NamespaceXml;
            }
            else
            {
                _source = attributes[index];
                _attributeIndex = index;
            }
            _namespaceParent = xmlElement;
            break;
        }
        default:
            return false;
        }
        return true;
    }
References System.Xml.DocumentXPathNavigator._attributeIndex, System.Xml.DocumentXPathNavigator._document, System.Xml.DocumentXPathNavigator._namespaceParent, System.Xml.DocumentXPathNavigator._source, System.Xml.Dictionary, System.Xml.Ref.Equal(), System.index, System.Xml.DocumentXPathNavigator.MoveToFirstNamespaceGlobal(), System.Xml.DocumentXPathNavigator.MoveToFirstNamespaceLocal(), System.Xml.DocumentXPathNavigator.MoveToNextNamespaceGlobal(), System.Xml.XmlDocument.NamespaceXml, and System.Xml.XmlDocument.strXml.