Terraria: System.Xml.DocumentXPathNavigator.ResetPosition
ResetPosition()
void System.Xml.DocumentXPathNavigator.ResetPosition (XmlNode node) inline package
Definition at line 1643 of file DocumentXPathNavigator.cs.
    {
        _source = node;
        if (!(node is XmlAttribute xmlAttribute))
        {
            return;
        }
        XmlElement ownerElement = xmlAttribute.OwnerElement;
        if (ownerElement != null)
        {
            ResetAttributePosition(xmlAttribute, ownerElement.Attributes, out _attributeIndex);
            if (xmlAttribute.IsNamespace)
            {
                _namespaceParent = ownerElement;
            }
        }
    }
References System.Xml.DocumentXPathNavigator._attributeIndex, System.Xml.DocumentXPathNavigator._namespaceParent, System.Xml.DocumentXPathNavigator._source, System.Xml.Dictionary, and System.Xml.DocumentXPathNavigator.ResetAttributePosition().
Referenced by System.Xml.DocumentXPathNavigator.DocumentXPathNavigator(), System.Xml.DocumentXPathNavigator.CalibrateText(), System.Xml.DocumentXmlWriter.CloseWithReplaceToFollowingSibling(), System.Xml.DocumentXPathNavigator.DeleteRange(), and System.Xml.DocumentXPathNavigator.DeleteSelf().