Terraria: System.Xml.DocumentXPathNavigator.NextSibling
NextSibling()
XmlNode System.Xml.DocumentXPathNavigator.NextSibling (XmlNode node) inline private
Definition at line 1742 of file DocumentXPathNavigator.cs.
    {
        XmlNode nextSibling = node.NextSibling;
        if (!_document.HasEntityReferences)
        {
            return nextSibling;
        }
        return NextSiblingTail(node, nextSibling);
    }
References System.Xml.DocumentXPathNavigator._document, System.Xml.Dictionary, System.Xml.XmlDocument.HasEntityReferences, and System.Xml.DocumentXPathNavigator.NextSiblingTail().
Referenced by System.Xml.DocumentXPathNavigator.MoveToChild(), System.Xml.DocumentXPathNavigator.MoveToChild(), System.Xml.DocumentXPathNavigator.MoveToFirst(), System.Xml.DocumentXPathNavigator.MoveToFirstChild(), System.Xml.DocumentXPathNavigator.MoveToNext(), System.Xml.DocumentXPathNavigator.MoveToNext(), System.Xml.DocumentXPathNavigator.MoveToNext(), and System.Xml.DocumentXPathNavigator.TextEnd().