Terraria: System.Xml.DocumentXPathNavigator.IsValidChild
IsValidChild()
static bool System.Xml.DocumentXPathNavigator.IsValidChild (XmlNode parent, XmlNode child) inline static private
Definition at line 1894 of file DocumentXPathNavigator.cs.
    {
        switch (parent.NodeType)
        {
        case XmlNodeType.Element:
            return true;
        case XmlNodeType.DocumentFragment:
            switch (child.NodeType)
            {
            case XmlNodeType.Element:
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                return true;
            }
            break;
        case XmlNodeType.Document:
        {
            XmlNodeType nodeType = child.NodeType;
            if (nodeType == XmlNodeType.Element || (uint)(nodeType - 7) <= 1u)
            {
                return true;
            }
            break;
        }
        }
        return false;
    }
References System.Xml.XmlNode.NodeType.
Referenced by System.Xml.DocumentXPathNavigator.MoveToFirst(), System.Xml.DocumentXPathNavigator.MoveToFirstChild(), System.Xml.DocumentXPathNavigator.MoveToNext(), and System.Xml.DocumentXPathNavigator.MoveToPrevious().