Terraria: System.Xml.DocumentXPathNavigator.DeleteRange
DeleteRange()
override void System.Xml.DocumentXPathNavigator.DeleteRange (XPathNavigator lastSiblingToDelete) inline virtual
Reimplemented from System.Xml.XPath.XPathNavigator.
Definition at line 1460 of file DocumentXPathNavigator.cs.
    {
        if (!(lastSiblingToDelete is DocumentXPathNavigator documentXPathNavigator))
        {
            if (lastSiblingToDelete == null)
            {
                throw new ArgumentNullException("lastSiblingToDelete");
            }
            throw new NotSupportedException();
        }
        CalibrateText();
        documentXPathNavigator.CalibrateText();
        XmlNode source = _source;
        XmlNode xmlNode = documentXPathNavigator._source;
        if (source == xmlNode)
        {
            switch (source.NodeType)
            {
            case XmlNodeType.Attribute:
            {
                XmlAttribute xmlAttribute = (XmlAttribute)source;
                if (!xmlAttribute.IsNamespace)
                {
                    XmlNode xmlNode2 = OwnerNode(xmlAttribute);
                    DeleteAttribute(xmlAttribute, _attributeIndex);
                    if (xmlNode2 != null)
                    {
                        ResetPosition(xmlNode2);
                    }
                    break;
                }
                goto default;
            }
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                xmlNode = documentXPathNavigator.TextEnd(xmlNode);
                goto case XmlNodeType.Element;
            case XmlNodeType.Element:
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
            {
                XmlNode xmlNode2 = OwnerNode(source);
                DeleteToFollowingSibling(source, xmlNode);
                if (xmlNode2 != null)
                {
                    ResetPosition(xmlNode2);
                }
                break;
            }
            default:
                throw new InvalidOperationException(System.SR.Xpn_BadPosition);
            }
        }
        else
        {
            if (xmlNode.IsText)
            {
                xmlNode = documentXPathNavigator.TextEnd(xmlNode);
            }
            if (!IsFollowingSibling(source, xmlNode))
            {
                throw new InvalidOperationException(System.SR.Xpn_BadPosition);
            }
            XmlNode xmlNode3 = OwnerNode(source);
            DeleteToFollowingSibling(source, xmlNode);
            if (xmlNode3 != null)
            {
                ResetPosition(xmlNode3);
            }
        }
    }
References System.Xml.DocumentXPathNavigator._attributeIndex, System.Xml.DocumentXPathNavigator._source, System.Xml.DocumentXPathNavigator.CalibrateText(), System.Xml.DocumentXPathNavigator.DeleteAttribute(), System.Xml.DocumentXPathNavigator.DeleteToFollowingSibling(), System.Xml.DocumentXPathNavigator.IsFollowingSibling(), System.Xml.DocumentXPathNavigator.OwnerNode(), System.Xml.DocumentXPathNavigator.ResetPosition(), System.source, and System.SR.Xpn_BadPosition.