Terraria: System.Xml.DocumentXPathNavigator.MoveToNextNamespaceGlobal
MoveToNextNamespaceGlobal()
static bool System.Xml.DocumentXPathNavigator.MoveToNextNamespaceGlobal (ref XmlAttributeCollection attributes, ref int index) inline static private
Definition at line 611 of file DocumentXPathNavigator.cs.
    {
        if (MoveToNextNamespaceLocal(attributes, ref index))
        {
            return true;
        }
        for (XmlElement xmlElement = attributes.parent.ParentNode as XmlElement; xmlElement != null; xmlElement = xmlElement.ParentNode as XmlElement)
        {
            if (xmlElement.HasAttributes)
            {
                attributes = xmlElement.Attributes;
                if (MoveToFirstNamespaceLocal(attributes, ref index))
                {
                    return true;
                }
            }
        }
        return false;
    }
References System.Xml.Dictionary, System.index, System.Xml.DocumentXPathNavigator.MoveToFirstNamespaceLocal(), and System.Xml.DocumentXPathNavigator.MoveToNextNamespaceLocal().
Referenced by System.Xml.DocumentXPathNavigator.MoveToFirstNamespace(), and System.Xml.DocumentXPathNavigator.MoveToNextNamespace().