Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.Close
Close()
override void System.Runtime.Serialization.Json.XmlJsonWriter.Close () inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 200 of file XmlJsonWriter.cs.
    {
        if (!IsClosed)
        {
            try
            {
                WriteEndDocument();
            }
            finally
            {
                try
                {
                    _nodeWriter.Flush();
                    _nodeWriter.Close();
                }
                finally
                {
                    _writeState = WriteState.Closed;
                    if (_depth != 0)
                    {
                        _depth = 0;
                    }
                }
            }
        }
        base.Close();
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._depth, System.Runtime.Serialization.Json.XmlJsonWriter._nodeWriter, System.Runtime.Serialization.Json.XmlJsonWriter._writeState, System.Xml.XmlStreamNodeWriter.Close(), System.Runtime.Serialization.Dictionary, System.Xml.XmlStreamNodeWriter.Flush(), System.Runtime.Serialization.Json.XmlJsonWriter.IsClosed, and System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndDocument().