Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteBinHex
WriteBinHex()
override void System.Runtime.Serialization.Json.XmlJsonWriter.WriteBinHex (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlWriter.
Definition at line 406 of file XmlJsonWriter.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index", System.SR.ValueMustBeNonNegative);
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative);
        }
        if (count > buffer.Length - index)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.JsonSizeExceedsRemainingBufferSpace, buffer.Length - index));
        }
        StartText();
        WriteEscapedJsonString(BinHexEncoding.GetString(buffer, index, count));
    }
References System.buffer, System.count, System.SR.Format(), System.Text.Encoding.GetString(), System.index, System.SR.JsonSizeExceedsRemainingBufferSpace, System.Runtime.Serialization.Json.XmlJsonWriter.StartText(), System.SR.ValueMustBeNonNegative, and System.Runtime.Serialization.Json.XmlJsonWriter.WriteEscapedJsonString().