Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndElement
WriteEndElement()
override void System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndElement () inline
Definition at line 560 of file XmlJsonWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (_depth == 0)
        {
            throw new XmlException(System.SR.JsonEndElementNoOpenNodes);
        }
        if (HasOpenAttribute)
        {
            throw new XmlException(System.SR.Format(System.SR.JsonOpenAttributeMustBeClosedFirst, "WriteEndElement"));
        }
        _endElementBuffer = false;
        JsonNodeType jsonNodeType = ExitScope();
        if (jsonNodeType == JsonNodeType.Collection)
        {
            _indentLevel--;
            if (_indent)
            {
                if (_nodeType == JsonNodeType.Element)
                {
                    _nodeWriter.WriteText(32);
                }
                else
                {
                    WriteNewLine();
                    WriteIndent();
                }
            }
            _nodeWriter.WriteText(93);
            jsonNodeType = ExitScope();
        }
        else if (_nodeType == JsonNodeType.QuotedText)
        {
            WriteJsonQuote();
        }
        else if (_nodeType == JsonNodeType.Element)
        {
            if (_dataType == JsonDataType.None && _serverTypeValue != null)
            {
                throw new XmlException(System.SR.Format(System.SR.JsonMustSpecifyDataType, "type", "object", "__type"));
            }
            if (IsWritingNameWithMapping && !WrittenNameWithMapping)
            {
                throw new XmlException(System.SR.Format(System.SR.JsonMustSpecifyDataType, "item", string.Empty, "item"));
            }
            if (_dataType == JsonDataType.None || _dataType == JsonDataType.String)
            {
                _nodeWriter.WriteText(34);
                _nodeWriter.WriteText(34);
            }
        }
        if (_depth != 0)
        {
            switch (jsonNodeType)
            {
            case JsonNodeType.Element:
                _endElementBuffer = true;
                break;
            case JsonNodeType.Object:
                _indentLevel--;
                if (_indent)
                {
                    if (_nodeType == JsonNodeType.Element)
                    {
                        _nodeWriter.WriteText(32);
                    }
                    else
                    {
                        WriteNewLine();
                        WriteIndent();
                    }
                }
                _nodeWriter.WriteText(125);
                if (_depth > 0 && _scopes[_depth] == JsonNodeType.Element)
                {
                    ExitScope();
                    _endElementBuffer = true;
                }
                break;
            }
        }
        _dataType = JsonDataType.None;
        _nodeType = JsonNodeType.EndElement;
        _nameState = NameState.None;
        _wroteServerTypeAttribute = false;
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._dataType, System.Runtime.Serialization.Json.XmlJsonWriter._depth, System.Runtime.Serialization.Json.XmlJsonWriter._endElementBuffer, System.Runtime.Serialization.Json.XmlJsonWriter._indent, System.Runtime.Serialization.Json.XmlJsonWriter._indentLevel, System.Runtime.Serialization.Json.XmlJsonWriter._nameState, System.Runtime.Serialization.Json.XmlJsonWriter._nodeType, System.Runtime.Serialization.Json.XmlJsonWriter._nodeWriter, System.Runtime.Serialization.Json.XmlJsonWriter._scopes, System.Runtime.Serialization.Json.XmlJsonWriter._serverTypeValue, System.Runtime.Serialization.Json.XmlJsonWriter._wroteServerTypeAttribute, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlJsonWriter.ExitScope(), System.SR.Format(), System.Runtime.Serialization.Json.XmlJsonWriter.HasOpenAttribute, System.Runtime.Serialization.Json.XmlJsonWriter.IsClosed, System.Runtime.Serialization.Json.XmlJsonWriter.IsWritingNameWithMapping, System.SR.JsonEndElementNoOpenNodes, System.SR.JsonMustSpecifyDataType, System.SR.JsonOpenAttributeMustBeClosedFirst, System.Runtime.Serialization.Json.XmlJsonWriter.ThrowClosed(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteIndent(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonQuote(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteNewLine(), System.Xml.XmlUTF8NodeWriter.WriteText(), System.Runtime.Serialization.Json.XmlJsonWriter.WrittenNameWithMapping, and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndDocument(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteFullEndElement(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteServerTypeAttribute().