Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteEscapedJsonString
WriteEscapedJsonString()
unsafe void System.Runtime.Serialization.Json.XmlJsonWriter.WriteEscapedJsonString (string str) inline private
Definition at line 1272 of file XmlJsonWriter.cs.
    {
        fixed (char* ptr = str)
        {
            int num = 0;
            int i;
            for (i = 0; i < str.Length; i++)
            {
                char c = ptr[i];
                if (c <= '/')
                {
                    if (c == '/' || c == '"')
                    {
                        _nodeWriter.WriteChars(ptr + num, i - num);
                        _nodeWriter.WriteText(92);
                        _nodeWriter.WriteText(c);
                        num = i + 1;
                    }
                    else if (c < ' ')
                    {
                        _nodeWriter.WriteChars(ptr + num, i - num);
                        _nodeWriter.WriteText(s_escapedJsonStringTable[(uint)c]);
                        num = i + 1;
                    }
                }
                else if (c == '\\')
                {
                    _nodeWriter.WriteChars(ptr + num, i - num);
                    _nodeWriter.WriteText(92);
                    _nodeWriter.WriteText(c);
                    num = i + 1;
                }
                else if ((c >= '\ud800' && (c <= '\udfff' || c >= '\ufffe')) || IsUnicodeNewlineCharacter(c))
                {
                    _nodeWriter.WriteChars(ptr + num, i - num);
                    _nodeWriter.WriteText(92);
                    _nodeWriter.WriteText(117);
                    _nodeWriter.WriteText($"{c:x4}");
                    num = i + 1;
                }
            }
            if (num < i)
            {
                _nodeWriter.WriteChars(ptr + num, i - num);
            }
        }
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._nodeWriter, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlJsonWriter.IsUnicodeNewlineCharacter(), System.Runtime.Serialization.Json.XmlJsonWriter.s_escapedJsonStringTable, System.str, System.Runtime.Serialization.Json.XmlJsonWriter.JsonNodeWriter.WriteChars(), and System.Xml.XmlUTF8NodeWriter.WriteText().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteBinHex(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonElementName(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteString().