Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteBase64
WriteBase64()
override void System.Runtime.Serialization.Json.XmlJsonWriter.WriteBase64 (byte[] buffer, int index, int count) inline
Definition at line 384 of file XmlJsonWriter.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index", System.SR.ValueMustBeNonNegative);
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative);
        }
        if (count > buffer.Length - index)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.JsonSizeExceedsRemainingBufferSpace, buffer.Length - index));
        }
        StartText();
        _nodeWriter.WriteBase64Text(buffer, 0, buffer, index, count);
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._nodeWriter, System.buffer, System.count, System.SR.Format(), System.index, System.SR.JsonSizeExceedsRemainingBufferSpace, System.Runtime.Serialization.Json.XmlJsonWriter.StartText(), System.SR.ValueMustBeNonNegative, and System.Xml.XmlUTF8NodeWriter.WriteBase64Text().