Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteStartElement
WriteStartElement() [3/6]
override void System.Runtime.Serialization.Json.XmlJsonWriter.WriteStartElement (string prefix, string localName, string ns) inline
Definition at line 830 of file XmlJsonWriter.cs.
    {
        if (localName == null)
        {
            throw new ArgumentNullException("localName");
        }
        if (localName.Length == 0)
        {
            throw new ArgumentException(System.SR.JsonInvalidLocalNameEmpty, "localName");
        }
        if (!string.IsNullOrEmpty(prefix) && (string.IsNullOrEmpty(ns) || !TrySetWritingNameWithMapping(localName, ns)))
        {
            throw new ArgumentException(System.SR.Format(System.SR.JsonPrefixMustBeNullOrEmpty, prefix), "prefix");
        }
        if (!string.IsNullOrEmpty(ns) && !TrySetWritingNameWithMapping(localName, ns))
        {
            throw new ArgumentException(System.SR.Format(System.SR.JsonNamespaceMustBeEmpty, ns), "ns");
        }
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (HasOpenAttribute)
        {
            throw new XmlException(System.SR.Format(System.SR.JsonOpenAttributeMustBeClosedFirst, "WriteStartElement"));
        }
        if (_nodeType != 0 && _depth == 0)
        {
            throw new XmlException(System.SR.JsonMultipleRootElementsNotAllowedOnWriter);
        }
        switch (_nodeType)
        {
        case JsonNodeType.None:
            if (!localName.Equals("root"))
            {
                throw new XmlException(System.SR.Format(System.SR.JsonInvalidRootElementName, localName, "root"));
            }
            EnterScope(JsonNodeType.Element);
            break;
        case JsonNodeType.Element:
            if (_dataType != JsonDataType.Array && _dataType != JsonDataType.Object)
            {
                throw new XmlException(System.SR.JsonNodeTypeArrayOrObjectNotSpecified);
            }
            if (_indent)
            {
                WriteNewLine();
                WriteIndent();
            }
            if (!IsWritingCollection)
            {
                if (_nameState != NameState.IsWritingNameWithMapping)
                {
                    WriteJsonElementName(localName);
                }
            }
            else if (!localName.Equals("item"))
            {
                throw new XmlException(System.SR.Format(System.SR.JsonInvalidItemNameForArrayElement, localName, "item"));
            }
            EnterScope(JsonNodeType.Element);
            break;
        case JsonNodeType.EndElement:
            if (_endElementBuffer)
            {
                _nodeWriter.WriteText(44);
            }
            if (_indent)
            {
                WriteNewLine();
                WriteIndent();
            }
            if (!IsWritingCollection)
            {
                if (_nameState != NameState.IsWritingNameWithMapping)
                {
                    WriteJsonElementName(localName);
                }
            }
            else if (!localName.Equals("item"))
            {
                throw new XmlException(System.SR.Format(System.SR.JsonInvalidItemNameForArrayElement, localName, "item"));
            }
            EnterScope(JsonNodeType.Element);
            break;
        default:
            throw new XmlException(System.SR.JsonInvalidStartElementCall);
        }
        _isWritingDataTypeAttribute = false;
        _isWritingServerTypeAttribute = false;
        _isWritingXmlnsAttribute = false;
        _wroteServerTypeAttribute = false;
        _serverTypeValue = null;
        _dataType = JsonDataType.None;
        _nodeType = JsonNodeType.Element;
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._dataType, System.Runtime.Serialization.Json.XmlJsonWriter._depth, System.Runtime.Serialization.Json.XmlJsonWriter._endElementBuffer, System.Runtime.Serialization.Json.XmlJsonWriter._indent, System.Runtime.Serialization.Json.XmlJsonWriter._isWritingDataTypeAttribute, System.Runtime.Serialization.Json.XmlJsonWriter._isWritingServerTypeAttribute, System.Runtime.Serialization.Json.XmlJsonWriter._isWritingXmlnsAttribute, System.Runtime.Serialization.Json.XmlJsonWriter._nameState, System.Runtime.Serialization.Json.XmlJsonWriter._nodeType, System.Runtime.Serialization.Json.XmlJsonWriter._nodeWriter, System.Runtime.Serialization.Json.XmlJsonWriter._serverTypeValue, System.Runtime.Serialization.Json.XmlJsonWriter._wroteServerTypeAttribute, System.Xml.ArgumentException, System.Runtime.Serialization.Json.XmlJsonWriter.EnterScope(), System.SR.Format(), System.Runtime.Serialization.Json.XmlJsonWriter.HasOpenAttribute, System.Runtime.Serialization.Json.XmlJsonWriter.IsClosed, System.Runtime.Serialization.Json.XmlJsonWriter.IsWritingCollection, System.SR.JsonInvalidItemNameForArrayElement, System.SR.JsonInvalidLocalNameEmpty, System.SR.JsonInvalidRootElementName, System.SR.JsonInvalidStartElementCall, System.SR.JsonMultipleRootElementsNotAllowedOnWriter, System.SR.JsonNamespaceMustBeEmpty, System.SR.JsonNodeTypeArrayOrObjectNotSpecified, System.SR.JsonOpenAttributeMustBeClosedFirst, System.SR.JsonPrefixMustBeNullOrEmpty, System.prefix, System.Runtime.Serialization.Json.XmlJsonWriter.ThrowClosed(), System.Runtime.Serialization.Json.XmlJsonWriter.TrySetWritingNameWithMapping(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteIndent(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonElementName(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteNewLine(), System.Xml.XmlUTF8NodeWriter.WriteText(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteServerTypeAttribute().