Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteString
WriteString() [1/3]
override void System.Runtime.Serialization.Json.XmlJsonWriter.WriteString (string text) inline
Definition at line 927 of file XmlJsonWriter.cs.
    {
        if (HasOpenAttribute && text != null)
        {
            _attributeText += text;
            return;
        }
        if (text == null)
        {
            text = string.Empty;
        }
        if ((_dataType != JsonDataType.Array && _dataType != JsonDataType.Object && _nodeType != JsonNodeType.EndElement) || !XmlConverter.IsWhitespace(text))
        {
            StartText();
            WriteEscapedJsonString(text);
        }
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._attributeText, System.Runtime.Serialization.Json.XmlJsonWriter._dataType, System.Runtime.Serialization.Json.XmlJsonWriter._nodeType, System.Runtime.Serialization.Json.XmlJsonWriter.HasOpenAttribute, System.Xml.XmlConverter.IsWhitespace(), System.Runtime.Serialization.Json.XmlJsonWriter.StartText(), System.text, and System.Runtime.Serialization.Json.XmlJsonWriter.WriteEscapedJsonString().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteCData(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteCharEntity(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteChars(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteRaw(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteRaw(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteSurrogateCharEntity(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteWhitespace().