Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteDataTypeServerType
WriteDataTypeServerType()
void System.Runtime.Serialization.Json.XmlJsonWriter.WriteDataTypeServerType () inline private
Definition at line 1245 of file XmlJsonWriter.cs.
    {
        if (_dataType != 0)
        {
            switch (_dataType)
            {
            case JsonDataType.Array:
                EnterScope(JsonNodeType.Collection);
                _nodeWriter.WriteText(91);
                _indentLevel++;
                break;
            case JsonDataType.Object:
                EnterScope(JsonNodeType.Object);
                _nodeWriter.WriteText(123);
                _indentLevel++;
                break;
            case JsonDataType.Null:
                _nodeWriter.WriteText("null");
                break;
            }
            if (_serverTypeValue != null)
            {
                WriteServerTypeAttribute();
            }
        }
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._dataType, System.Runtime.Serialization.Json.XmlJsonWriter._indentLevel, System.Runtime.Serialization.Json.XmlJsonWriter._nodeWriter, System.Runtime.Serialization.Json.XmlJsonWriter._serverTypeValue, System.Runtime.Serialization.Json.XmlJsonWriter.EnterScope(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteServerTypeAttribute(), and System.Xml.XmlUTF8NodeWriter.WriteText().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndAttribute().