Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.StartText
StartText()
void System.Runtime.Serialization.Json.XmlJsonWriter.StartText () inline private
Definition at line 1184 of file XmlJsonWriter.cs.
    {
        if (HasOpenAttribute)
        {
            throw new InvalidOperationException(System.SR.JsonMustUseWriteStringForWritingAttributeValues);
        }
        if (_dataType == JsonDataType.None && _serverTypeValue != null)
        {
            throw new XmlException(System.SR.Format(System.SR.JsonMustSpecifyDataType, "type", "object", "__type"));
        }
        if (IsWritingNameWithMapping && !WrittenNameWithMapping)
        {
            throw new XmlException(System.SR.Format(System.SR.JsonMustSpecifyDataType, "item", string.Empty, "item"));
        }
        if (_dataType == JsonDataType.String || _dataType == JsonDataType.None)
        {
            CheckText(JsonNodeType.QuotedText);
            if (_nodeType != JsonNodeType.QuotedText)
            {
                WriteJsonQuote();
            }
            _nodeType = JsonNodeType.QuotedText;
        }
        else if (_dataType == JsonDataType.Number || _dataType == JsonDataType.Boolean)
        {
            CheckText(JsonNodeType.StandaloneText);
            _nodeType = JsonNodeType.StandaloneText;
        }
        else
        {
            ThrowInvalidAttributeContent();
        }
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._dataType, System.Runtime.Serialization.Json.XmlJsonWriter._nodeType, System.Runtime.Serialization.Json.XmlJsonWriter._serverTypeValue, System.Runtime.Serialization.Json.XmlJsonWriter.CheckText(), System.SR.Format(), System.Runtime.Serialization.Json.XmlJsonWriter.HasOpenAttribute, System.Runtime.Serialization.Json.XmlJsonWriter.IsWritingNameWithMapping, System.SR.JsonMustSpecifyDataType, System.SR.JsonMustUseWriteStringForWritingAttributeValues, System.Runtime.Serialization.Json.XmlJsonWriter.ThrowInvalidAttributeContent(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonQuote(), System.Runtime.Serialization.Json.XmlJsonWriter.WrittenNameWithMapping, and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteBase64(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteBinHex(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteString(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue().