Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonElementName
WriteJsonElementName()
void System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonElementName (string localName) inline private
Definition at line 1334 of file XmlJsonWriter.cs.
    {
        WriteJsonQuote();
        WriteEscapedJsonString(localName);
        WriteJsonQuote();
        _nodeWriter.WriteText(58);
        if (_indent)
        {
            _nodeWriter.WriteText(32);
        }
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._indent, System.Runtime.Serialization.Json.XmlJsonWriter._nodeWriter, System.Runtime.Serialization.Json.XmlJsonWriter.WriteEscapedJsonString(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonQuote(), and System.Xml.XmlUTF8NodeWriter.WriteText().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndAttribute(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteStartElement().