Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndAttribute
WriteEndAttribute()
override void System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndAttribute () inline
Definition at line 469 of file XmlJsonWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (!HasOpenAttribute)
        {
            throw new XmlException(System.SR.JsonNoMatchingStartAttribute);
        }
        if (_isWritingDataTypeAttribute)
        {
            switch (_attributeText)
            {
            case "number":
                ThrowIfServerTypeWritten("number");
                _dataType = JsonDataType.Number;
                break;
            case "string":
                ThrowIfServerTypeWritten("string");
                _dataType = JsonDataType.String;
                break;
            case "array":
                ThrowIfServerTypeWritten("array");
                _dataType = JsonDataType.Array;
                break;
            case "object":
                _dataType = JsonDataType.Object;
                break;
            case "null":
                ThrowIfServerTypeWritten("null");
                _dataType = JsonDataType.Null;
                break;
            case "boolean":
                ThrowIfServerTypeWritten("boolean");
                _dataType = JsonDataType.Boolean;
                break;
            default:
                throw new XmlException(System.SR.Format(System.SR.JsonUnexpectedAttributeValue, _attributeText));
            }
            _attributeText = null;
            _isWritingDataTypeAttribute = false;
            if (!IsWritingNameWithMapping || WrittenNameWithMapping)
            {
                WriteDataTypeServerType();
            }
        }
        else if (_isWritingServerTypeAttribute)
        {
            _serverTypeValue = _attributeText;
            _attributeText = null;
            _isWritingServerTypeAttribute = false;
            if ((!IsWritingNameWithMapping || WrittenNameWithMapping) && _dataType == JsonDataType.Object)
            {
                WriteServerTypeAttribute();
            }
        }
        else if (IsWritingNameAttribute)
        {
            WriteJsonElementName(_attributeText);
            _attributeText = null;
            _nameState = NameState.IsWritingNameWithMapping | NameState.WrittenNameWithMapping;
            WriteDataTypeServerType();
        }
        else if (_isWritingXmlnsAttribute)
        {
            if (!string.IsNullOrEmpty(_attributeText) && _isWritingXmlnsAttributeDefaultNs)
            {
                throw new ArgumentException(System.SR.Format(System.SR.JsonNamespaceMustBeEmpty, _attributeText));
            }
            _attributeText = null;
            _isWritingXmlnsAttribute = false;
            _isWritingXmlnsAttributeDefaultNs = false;
        }
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._attributeText, System.Runtime.Serialization.Json.XmlJsonWriter._dataType, System.Runtime.Serialization.Json.XmlJsonWriter._isWritingDataTypeAttribute, System.Runtime.Serialization.Json.XmlJsonWriter._isWritingServerTypeAttribute, System.Runtime.Serialization.Json.XmlJsonWriter._isWritingXmlnsAttribute, System.Runtime.Serialization.Json.XmlJsonWriter._isWritingXmlnsAttributeDefaultNs, System.Runtime.Serialization.Json.XmlJsonWriter._nameState, System.Runtime.Serialization.Json.XmlJsonWriter._serverTypeValue, System.Xml.ArgumentException, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Json.XmlJsonWriter.HasOpenAttribute, System.Runtime.Serialization.Json.XmlJsonWriter.IsClosed, System.Runtime.Serialization.Json.XmlJsonWriter.IsWritingNameAttribute, System.Runtime.Serialization.Json.XmlJsonWriter.IsWritingNameWithMapping, System.SR.JsonNamespaceMustBeEmpty, System.SR.JsonNoMatchingStartAttribute, System.SR.JsonUnexpectedAttributeValue, System.Runtime.Serialization.Json.XmlJsonWriter.ThrowClosed(), System.Runtime.Serialization.Json.XmlJsonWriter.ThrowIfServerTypeWritten(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteDataTypeServerType(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteJsonElementName(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteServerTypeAttribute(), System.Runtime.Serialization.Json.XmlJsonWriter.WrittenNameWithMapping, and System.Xml.XmlException.