Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue
WriteValue() [1/18]
void System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue (Array array) inline private
Definition at line 1452 of file XmlJsonWriter.cs.
    {
        JsonDataType dataType = _dataType;
        _dataType = JsonDataType.String;
        StartText();
        for (int i = 0; i < array.Length; i++)
        {
            if (i != 0)
            {
                _nodeWriter.WriteText(32);
            }
            WritePrimitiveValue(array.GetValue(i));
        }
        _dataType = dataType;
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._dataType, System.Runtime.Serialization.Json.XmlJsonWriter._nodeWriter, System.array, System.Runtime.Serialization.Json.XmlJsonWriter.StartText(), System.Runtime.Serialization.Json.XmlJsonWriter.WritePrimitiveValue(), and System.Xml.XmlUTF8NodeWriter.WriteText().