Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WriteServerTypeAttribute
WriteServerTypeAttribute()
void System.Runtime.Serialization.Json.XmlJsonWriter.WriteServerTypeAttribute () inline private
Definition at line 1433 of file XmlJsonWriter.cs.
    {
        string serverTypeValue = _serverTypeValue;
        JsonDataType dataType = _dataType;
        NameState nameState = _nameState;
        WriteStartElement("__type");
        WriteValue(serverTypeValue);
        WriteEndElement();
        _dataType = dataType;
        _nameState = nameState;
        _wroteServerTypeAttribute = true;
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._dataType, System.Runtime.Serialization.Json.XmlJsonWriter._nameState, System.Runtime.Serialization.Json.XmlJsonWriter._serverTypeValue, System.Runtime.Serialization.Json.XmlJsonWriter._wroteServerTypeAttribute, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndElement(), System.Runtime.Serialization.Json.XmlJsonWriter.WriteStartElement(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteDataTypeServerType(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteEndAttribute().