Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.EnterScope
EnterScope()
void System.Runtime.Serialization.Json.XmlJsonWriter.EnterScope (JsonNodeType currentNodeType) inline private
Definition at line 1129 of file XmlJsonWriter.cs.
    {
        _depth++;
        if (_scopes == null)
        {
            _scopes = new JsonNodeType[4];
        }
        else if (_scopes.Length == _depth)
        {
            JsonNodeType[] array = new JsonNodeType[_depth * 2];
            Array.Copy(_scopes, array, _depth);
            _scopes = array;
        }
        _scopes[_depth] = currentNodeType;
    }
References System.Runtime.Serialization.Json.XmlJsonWriter._depth, System.Runtime.Serialization.Json.XmlJsonWriter._scopes, System.array, System.Array.Copy(), and System.Runtime.Serialization.Dictionary.
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteDataTypeServerType(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteStartElement().