Terraria: System.Runtime.Serialization.Json.XmlJsonWriter.WritePrimitiveValue
WritePrimitiveValue()
void System.Runtime.Serialization.Json.XmlJsonWriter.WritePrimitiveValue (object value) inline private
Definition at line 1351 of file XmlJsonWriter.cs.
    {
        if (IsClosed)
        {
            ThrowClosed();
        }
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (value is ulong)
        {
            WriteValue((ulong)value);
            return;
        }
        if (value is string)
        {
            WriteValue((string)value);
            return;
        }
        if (value is int)
        {
            WriteValue((int)value);
            return;
        }
        if (value is long)
        {
            WriteValue((long)value);
            return;
        }
        if (value is bool)
        {
            WriteValue((bool)value);
            return;
        }
        if (value is double)
        {
            WriteValue((double)value);
            return;
        }
        if (value is DateTime)
        {
            WriteValue((DateTime)value);
            return;
        }
        if (value is float)
        {
            WriteValue((float)value);
            return;
        }
        if (value is decimal)
        {
            WriteValue((decimal)value);
            return;
        }
        if (value is XmlDictionaryString)
        {
            WriteValue((XmlDictionaryString)value);
            return;
        }
        if (value is UniqueId)
        {
            WriteValue((UniqueId)value);
            return;
        }
        if (value is Guid)
        {
            WriteValue((Guid)value);
            return;
        }
        if (value is TimeSpan)
        {
            WriteValue((TimeSpan)value);
            return;
        }
        if (value.GetType().IsArray)
        {
            throw new ArgumentException(System.SR.JsonNestedArraysNotSupported, "value");
        }
        base.WriteValue(value);
    }
References System.Xml.ArgumentException, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlJsonWriter.IsClosed, System.SR.JsonNestedArraysNotSupported, System.Runtime.Serialization.Json.XmlJsonWriter.ThrowClosed(), System.value, and System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue().
Referenced by System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue(), and System.Runtime.Serialization.Json.XmlJsonWriter.WriteValue().