Terraria: System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayJsonHelperWithString.ReadArray
ReadArray() [1/3]
override int System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayJsonHelperWithString.ReadArray (XmlDictionaryReader reader, string localName, string namespaceUri, DateTime[] array, int offset, int count) inline protected
Definition at line 18 of file JsonReaderDelegator.cs.
        {
            XmlJsonReader.CheckArray(array, offset, count);
            int i;
            for (i = 0; i < count; i++)
            {
                if (!reader.IsStartElement("item", string.Empty))
                {
                    break;
                }
                array[offset + i] = ParseJsonDate(reader.ReadElementContentAsString(), _dateTimeFormat);
            }
            return i;
        }
References System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayJsonHelperWithString._dateTimeFormat, System.array, System.Runtime.Serialization.Json.XmlJsonReader.CheckArray(), System.count, System.Xml.XmlReader.IsStartElement(), System.offset, System.Runtime.Serialization.Json.JsonReaderDelegator.ParseJsonDate(), System.Xml.XmlReader.ReadElementContentAsString(), and System.Runtime.Serialization.XmlReaderDelegator.reader.
Referenced by System.Runtime.Serialization.Json.JsonReaderDelegator.TryReadJsonDateTimeArray().