Terraria: Terraria.GameContent.LucyAxeMessage.Create
Create()
static void Terraria.GameContent.LucyAxeMessage.Create (MessageSource source, Vector2 position, Vector2 velocity) inline static
    {
        if (Main.netMode != 2)
        {
            GiveIdleMessageCooldown();
            SpawnPopupText(source, _variation, position, velocity);
            PlaySound(source, position);
            SpawnEmoteBubble();
            if (Main.netMode == 1)
            {
                NetMessage.SendData(141, -1, -1, null, (int)source, (int)_variation, velocity.X, velocity.Y, (int)position.X, (int)position.Y);
            }
            _variation++;
        }
    }
References Terraria.GameContent.LucyAxeMessage._variation, Terraria.GameContent.LucyAxeMessage.GiveIdleMessageCooldown(), Terraria.Main.netMode, Terraria.GameContent.LucyAxeMessage.PlaySound(), Terraria.NetMessage.SendData(), Terraria.GameContent.LucyAxeMessage.SpawnEmoteBubble(), and Terraria.GameContent.LucyAxeMessage.SpawnPopupText().
Referenced by Terraria.Player.DropSelectedItem(), Terraria.Player.GetItem_FillEmptyInventorySlot(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.GameContent.LucyAxeMessage.ItemSlot_OnItemTransferred(), Terraria.GameContent.LucyAxeMessage.TryCreatingMessageWithCooldown(), and Terraria.GameContent.LucyAxeMessage.TryPlayingIdleMessage().