Terraria: MS.Internal.Xml.XPath.ClonableStack.Push
Push()
void MS.Internal.Xml.XPath.ClonableStack< T >.Push (T value) inline
Definition at line 16 of file ClonableStack.cs.
    {
        Add(value);
    }
References System.Collections.Generic.List< T >.Add().
Referenced by MS.Internal.Xml.XPath.FollSiblingQuery.Advance(), MS.Internal.Xml.XPath.PrecedingQuery.Advance(), and MS.Internal.Xml.XPath.CacheChildrenQuery.DecideNextNode().