Terraria: Terraria.GameContent.LucyAxeMessage.ItemSlot_OnItemTransferred
ItemSlot_OnItemTransferred()
static void Terraria.GameContent.LucyAxeMessage.ItemSlot_OnItemTransferred (ItemSlot::ItemTransferInfo info) inline static private
    {
        if (info.ItemType != 5095)
        {
            return;
        }
        bool flag = CountsAsStorage(info.FromContenxt);
        bool flag2 = CountsAsStorage(info.ToContext);
        if (flag != flag2)
        {
            MessageSource messageSource = ((!flag) ? MessageSource.Storage : MessageSource.PickedUp);
            if (_messageCooldownsByType[(int)messageSource] <= 0)
            {
                PutMessageTypeOnCooldown(messageSource, 420);
                Player localPlayer = Main.LocalPlayer;
                Create(messageSource, localPlayer.Top, new Vector2(localPlayer.direction * 7, -2f));
            }
        }
    }
References Terraria.GameContent.LucyAxeMessage._messageCooldownsByType, Terraria.GameContent.LucyAxeMessage.CountsAsStorage(), Terraria.GameContent.LucyAxeMessage.Create(), Terraria.Entity.direction, Terraria.Main.LocalPlayer, Terraria.GameContent.LucyAxeMessage.PutMessageTypeOnCooldown(), and Terraria.Entity.Top.
Referenced by Terraria.GameContent.LucyAxeMessage.Initialize().