Terraria: Terraria.GameContent.LucyAxeMessage.GetTextForVariation
GetTextForVariation()
static string Terraria.GameContent.LucyAxeMessage.GetTextForVariation (MessageSource source, int variationUnwrapped) inline static private
    {
        string categoryName = GetCategoryName(source);
        return LanguageManager.Instance.IndexedFromCategory(categoryName, variationUnwrapped).Value;
    }
References Terraria.GameContent.LucyAxeMessage.GetCategoryName(), Terraria.Localization.LanguageManager.IndexedFromCategory(), Terraria.Localization.LanguageManager.Instance, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.LucyAxeMessage.SpawnPopupText().