Terraria: System.IO.Compression.DeflateStream.FlushAsync
FlushAsync() [2/2]
override Task System.IO.Compression.DeflateStream.FlushAsync (CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 383 of file DeflateStream.cs.
    {
        EnsureNoActiveAsyncOperation();
        EnsureNotDisposed();
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled(cancellationToken);
        }
        if (_mode == CompressionMode.Compress)
        {
            return Core(cancellationToken);
        }
        return Task.CompletedTask;
        async Task Core(CancellationToken cancellationToken)
        {
            AsyncOperationStarting();
            try
            {
                await WriteDeflaterOutputAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                bool flushSuccessful;
                do
                {
                    flushSuccessful = _deflater.Flush(_buffer, out var bytesRead);
                    if (flushSuccessful)
                    {
                        await _stream.WriteAsync(new ReadOnlyMemory<byte>(_buffer, 0, bytesRead), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
                while (flushSuccessful);
                await _stream.FlushAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            finally
            {
                AsyncOperationCompleting();
            }
        }
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._mode, System.IO.Compression.DeflateStream._stream, System.IO.Compression.DeflateStream.AsyncOperationCompleting(), System.IO.Compression.DeflateStream.AsyncOperationStarting(), System.cancellationToken, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.IO.Compression.DeflateStream.EnsureNoActiveAsyncOperation(), System.IO.Compression.DeflateStream.EnsureNotDisposed(), System.IO.Compression.Deflater.Flush(), System.IO.Stream.FlushAsync(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.IO.Stream.WriteAsync(), and System.IO.Compression.DeflateStream.WriteDeflaterOutputAsync().
Referenced by System.IO.Compression.GZipStream.FlushAsync(), and System.IO.Compression.ZLibStream.FlushAsync().