Terraria: System.IO.Compression.DeflateStream.EnsureNotDisposed
EnsureNotDisposed()
void System.IO.Compression.DeflateStream.EnsureNotDisposed () inline private
Definition at line 491 of file DeflateStream.cs.
    {
        if (_stream == null)
        {
            ThrowStreamClosedException();
        }
        static void ThrowStreamClosedException()
        {
            throw new ObjectDisposedException("DeflateStream", System.SR.ObjectDisposed_StreamClosed);
        }
    }
References System.IO.Compression.DeflateStream._stream, and System.SR.ObjectDisposed_StreamClosed.
Referenced by System.IO.Compression.DeflateStream.CopyTo(), System.IO.Compression.DeflateStream.CopyToAsync(), System.IO.Compression.DeflateStream.EndRead(), System.IO.Compression.DeflateStream.EndWrite(), System.IO.Compression.DeflateStream.Flush(), System.IO.Compression.DeflateStream.FlushAsync(), System.IO.Compression.DeflateStream.ReadAsyncMemory(), System.IO.Compression.DeflateStream.ReadByte(), System.IO.Compression.DeflateStream.ReadCore(), System.IO.Compression.DeflateStream.CopyToStream.Write(), System.IO.Compression.DeflateStream.CopyToStream.WriteAsync(), System.IO.Compression.DeflateStream.CopyToStream.WriteAsync(), System.IO.Compression.DeflateStream.WriteAsyncMemory(), and System.IO.Compression.DeflateStream.WriteCore().