Terraria: System.IO.Compression.DeflateStream.ReadByte
ReadByte()
override int System.IO.Compression.DeflateStream.ReadByte () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 431 of file DeflateStream.cs.
    {
        EnsureDecompressionMode();
        EnsureNotDisposed();
        if (!_inflater.Inflate(out var b))
        {
            return base.ReadByte();
        }
        return b;
    }
References System.IO.Compression.DeflateStream._inflater, System.IO.Compression.DeflateStream.EnsureDecompressionMode(), System.IO.Compression.DeflateStream.EnsureNotDisposed(), and System.IO.Compression.Inflater.Inflate().
Referenced by System.Reflection.PortableExecutable.PEReader.DecodeEmbeddedPortablePdbDebugDirectoryData(), System.IO.Compression.GZipStream.ReadByte(), and System.IO.Compression.ZLibStream.ReadByte().