Terraria: System.IO.Compression.DeflateStream.Dispose
Dispose() [2/2]
override void System.IO.Compression.DeflateStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 730 of file DeflateStream.cs.
    {
        try
        {
            PurgeBuffers(disposing);
        }
        finally
        {
            try
            {
                if (disposing && !_leaveOpen)
                {
                    _stream?.Dispose();
                }
            }
            finally
            {
                _stream = null;
                try
                {
                    _deflater?.Dispose();
                    _inflater?.Dispose();
                }
                finally
                {
                    _deflater = null;
                    _inflater = null;
                    byte[] buffer = _buffer;
                    if (buffer != null)
                    {
                        _buffer = null;
                        if (!AsyncOperationIsActive)
{
                            ArrayPool<byte>.Shared.Return(buffer);
                        }
                    }
                    base.Dispose(disposing);
                }
            }
        }
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._inflater, System.IO.Compression.DeflateStream._leaveOpen, System.IO.Compression.DeflateStream._stream, System.IO.Compression.DeflateStream.AsyncOperationIsActive, System.buffer, System.IO.Compression.Deflater.Dispose(), System.IO.Stream.Dispose(), System.IO.Compression.Inflater.Dispose(), System.IO.Compression.DeflateStream.PurgeBuffers(), and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.IO.Compression.GZipStream.Dispose(), and System.IO.Compression.ZLibStream.Dispose().