Terraria: System.IO.Compression.DeflateStream.WriteDeflaterOutput
WriteDeflaterOutput()
void System.IO.Compression.DeflateStream.WriteDeflaterOutput () inline private
Definition at line 641 of file DeflateStream.cs.
    {
        while (!_deflater.NeedsInput())
        {
            int deflateOutput = _deflater.GetDeflateOutput(_buffer);
            if (deflateOutput > 0)
            {
                _stream.Write(_buffer, 0, deflateOutput);
            }
        }
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._stream, System.IO.Compression.Deflater.GetDeflateOutput(), System.IO.Compression.Deflater.NeedsInput(), and System.IO.Stream.Write().
Referenced by System.IO.Compression.DeflateStream.FlushBuffers(), System.IO.Compression.DeflateStream.PurgeBuffers(), and System.IO.Compression.DeflateStream.WriteCore().