Terraria: System.IO.Compression.DeflateStream.WriteCore
WriteCore()
unsafe void System.IO.Compression.DeflateStream.WriteCore (ReadOnlySpan< byte > buffer) inline package
Definition at line 628 of file DeflateStream.cs.
    {
        EnsureCompressionMode();
        EnsureNotDisposed();
        WriteDeflaterOutput();
        fixed (byte* inputBufferPtr = &MemoryMarshal.GetReference(buffer))
        {
            _deflater.SetInput(inputBufferPtr, buffer.Length);
            WriteDeflaterOutput();
            _wroteBytes = true;
        }
    }
References System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._wroteBytes, System.buffer, System.IO.Compression.DeflateStream.EnsureCompressionMode(), System.IO.Compression.DeflateStream.EnsureNotDisposed(), System.IO.Compression.Deflater.SetInput(), and System.IO.Compression.DeflateStream.WriteDeflaterOutput().
Referenced by System.IO.Compression.DeflateStream.Write(), System.IO.Compression.DeflateStream.Write(), System.IO.Compression.GZipStream.Write(), and System.IO.Compression.ZLibStream.Write().