Terraria: System.IO.Compression.DeflateStream.Flush
Flush()
override void System.IO.Compression.DeflateStream.Flush () inline
Definition at line 374 of file DeflateStream.cs.
    {
        EnsureNotDisposed();
        if (_mode == CompressionMode.Compress)
        {
            FlushBuffers();
        }
    }
References System.IO.Compression.DeflateStream._mode, System.IO.Compression.DeflateStream.EnsureNotDisposed(), and System.IO.Compression.DeflateStream.FlushBuffers().
Referenced by System.IO.Compression.GZipStream.Flush(), and System.IO.Compression.ZLibStream.Flush().