Terraria: System.IO.Compression.DeflateStream.ReadCore
ReadCore()
int System.IO.Compression.DeflateStream.ReadCore (Span< byte > buffer) inline package
Definition at line 457 of file DeflateStream.cs.
    {
        EnsureDecompressionMode();
        EnsureNotDisposed();
        EnsureBufferInitialized();
        int num;
        do
        {
            num = _inflater.Inflate(buffer);
            if (num != 0 || InflatorIsFinished)
            {
                break;
            }
            if (_inflater.NeedsInput())
            {
                int num2 = _stream.Read(_buffer, 0, _buffer.Length);
                if (num2 <= 0)
                {
                    break;
                }
                if (num2 > _buffer.Length)
                {
                    ThrowGenericInvalidData();
                }
                else
                {
                    _inflater.SetInput(_buffer, 0, num2);
                }
            }
        }
        while (!buffer.IsEmpty);
        return num;
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._inflater, System.IO.Compression.DeflateStream._stream, System.buffer, System.IO.Compression.DeflateStream.EnsureBufferInitialized(), System.IO.Compression.DeflateStream.EnsureDecompressionMode(), System.IO.Compression.DeflateStream.EnsureNotDisposed(), System.IO.Compression.Inflater.Inflate(), System.IO.Compression.DeflateStream.InflatorIsFinished, System.IO.Compression.Inflater.NeedsInput(), System.IO.Stream.Read(), System.IO.Compression.Inflater.SetInput(), and System.IO.Compression.DeflateStream.ThrowGenericInvalidData().
Referenced by System.IO.Compression.DeflateStream.Read(), System.IO.Compression.DeflateStream.Read(), System.IO.Compression.GZipStream.Read(), and System.IO.Compression.ZLibStream.Read().