Terraria: System.IO.Compression.DeflateStream.DisposeAsync
DisposeAsync()
override ValueTask System.IO.Compression.DeflateStream.DisposeAsync () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 772 of file DeflateStream.cs.
    {
        if (!(GetType() == typeof(DeflateStream)))
        {
            return base.DisposeAsync();
        }
        return Core();
        async ValueTask Core()
        {
            try
            {
                await PurgeBuffersAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            finally
            {
                Stream stream = _stream;
                _stream = null;
                try
                {
                    if (!_leaveOpen && stream != null)
                    {
                        await stream.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
                finally
                {
                    try
                    {
                        _deflater?.Dispose();
                        _inflater?.Dispose();
                    }
                    finally
                    {
                        _deflater = null;
                        _inflater = null;
                        byte[] buffer = _buffer;
                        if (buffer != null)
{
                            _buffer = null;
                            if (!AsyncOperationIsActive)
{
                                ArrayPool<byte>.Shared.Return(buffer);
                            }
                        }
                    }
                }
            }
        }
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._inflater, System.IO.Compression.DeflateStream._leaveOpen, System.IO.Compression.DeflateStream._stream, System.IO.Compression.DeflateStream.AsyncOperationIsActive, System.buffer, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.IO.Compression.Deflater.Dispose(), System.IO.Compression.Inflater.Dispose(), System.IO.Stream.DisposeAsync(), System.IO.Compression.DeflateStream.PurgeBuffersAsync(), System.Buffers.ArrayPool< T >.Shared, and System.stream.
Referenced by System.IO.Compression.GZipStream.DisposeAsync(), and System.IO.Compression.ZLibStream.DisposeAsync().