Terraria: System.IO.Compression.DeflateStream.InitializeDeflater
InitializeDeflater()
void System.IO.Compression.DeflateStream.InitializeDeflater (Stream stream, bool leaveOpen, int windowBits, CompressionLevel compressionLevel) inline package
Definition at line 346 of file DeflateStream.cs.
    {
        if (!stream.CanWrite)
        {
            throw new ArgumentException(System.SR.NotSupported_UnwritableStream, "stream");
        }
        _deflater = new Deflater(compressionLevel, windowBits);
        _stream = stream;
        _mode = CompressionMode.Compress;
        _leaveOpen = leaveOpen;
        InitializeBuffer();
    }
References System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._leaveOpen, System.IO.Compression.DeflateStream._mode, System.IO.Compression.DeflateStream._stream, System.IO.Compression.DeflateStream.InitializeBuffer(), System.SR.NotSupported_UnwritableStream, and System.stream.
Referenced by System.IO.Compression.DeflateStream.DeflateStream(), and System.IO.Compression.DeflateStream.DeflateStream().