Terraria: System.IO.Compression.DeflateStream.AsyncOperationStarting
AsyncOperationStarting()
void System.IO.Compression.DeflateStream.AsyncOperationStarting () inline private
Definition at line 923 of file DeflateStream.cs.
    {
        if (Interlocked.Exchange(ref _activeAsyncOperation, 1) != 0)
        {
            ThrowInvalidBeginCall();
        }
    }
References System.IO.Compression.DeflateStream._activeAsyncOperation, System.Threading.Interlocked.Exchange(), and System.IO.Compression.DeflateStream.ThrowInvalidBeginCall().
Referenced by System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync(), System.IO.Compression.DeflateStream.FlushAsync(), System.IO.Compression.DeflateStream.ReadAsyncMemory(), and System.IO.Compression.DeflateStream.WriteAsyncMemory().