Terraria: System.IO.Compression.DeflateStream.WriteDeflaterOutputAsync
WriteDeflaterOutputAsync()
async ValueTask System.IO.Compression.DeflateStream.WriteDeflaterOutputAsync (CancellationToken cancellationToken) inline private
Definition at line 876 of file DeflateStream.cs.
    {
        while (!_deflater.NeedsInput())
        {
            int deflateOutput = _deflater.GetDeflateOutput(_buffer);
            if (deflateOutput > 0)
            {
                await _stream.WriteAsync(new ReadOnlyMemory<byte>(_buffer, 0, deflateOutput), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._stream, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Compression.Deflater.GetDeflateOutput(), System.IO.Compression.Deflater.NeedsInput(), and System.IO.Stream.WriteAsync().
Referenced by System.IO.Compression.DeflateStream.FlushAsync(), System.IO.Compression.DeflateStream.PurgeBuffersAsync(), and System.IO.Compression.DeflateStream.WriteAsyncMemory().