Terraria: System.IO.Compression.DeflateStream.ReadAsyncMemory
ReadAsyncMemory()
ValueTask< int > System.IO.Compression.DeflateStream.ReadAsyncMemory (Memory< byte > buffer, CancellationToken cancellationToken) inline package
Definition at line 559 of file DeflateStream.cs.
    {
        EnsureDecompressionMode();
        EnsureNoActiveAsyncOperation();
        EnsureNotDisposed();
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled<int>(cancellationToken);
        }
        EnsureBufferInitialized();
        return Core(buffer, cancellationToken);
        async ValueTask<int> Core(Memory<byte> buffer, CancellationToken cancellationToken)
        {
            AsyncOperationStarting();
            try
            {
                int bytesRead;
                do
                {
                    bytesRead = _inflater.Inflate(buffer.Span);
                    if (bytesRead != 0 || InflatorIsFinished)
                    {
                        break;
                    }
                    if (_inflater.NeedsInput())
                    {
                        int num = await _stream.ReadAsync(new Memory<byte>(_buffer, 0, _buffer.Length), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        if (num <= 0)
{
                            break;
                        }
                        if (num > _buffer.Length)
{
                            ThrowGenericInvalidData();
                        }
                        else
{
                            _inflater.SetInput(_buffer, 0, num);
                        }
                    }
                }
                while (!buffer.IsEmpty);
                return bytesRead;
            }
            finally
            {
                AsyncOperationCompleting();
            }
        }
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._inflater, System.IO.Compression.DeflateStream._stream, System.IO.Compression.DeflateStream.AsyncOperationCompleting(), System.IO.Compression.DeflateStream.AsyncOperationStarting(), System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Compression.DeflateStream.EnsureBufferInitialized(), System.IO.Compression.DeflateStream.EnsureDecompressionMode(), System.IO.Compression.DeflateStream.EnsureNoActiveAsyncOperation(), System.IO.Compression.DeflateStream.EnsureNotDisposed(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.IO.Compression.Inflater.Inflate(), System.IO.Compression.DeflateStream.InflatorIsFinished, System.IO.Compression.Inflater.NeedsInput(), System.IO.Stream.ReadAsync(), System.IO.Compression.Inflater.SetInput(), and System.IO.Compression.DeflateStream.ThrowGenericInvalidData().
Referenced by System.IO.Compression.DeflateStream.ReadAsync(), System.IO.Compression.DeflateStream.ReadAsync(), System.IO.Compression.GZipStream.ReadAsync(), and System.IO.Compression.ZLibStream.ReadAsync().