Terraria: System.IO.Compression.DeflateStream.FlushBuffers
FlushBuffers()
void System.IO.Compression.DeflateStream.FlushBuffers () inline private
Definition at line 653 of file DeflateStream.cs.
    {
        if (_wroteBytes)
        {
            WriteDeflaterOutput();
            bool flag;
            do
            {
                flag = _deflater.Flush(_buffer, out var bytesRead);
                if (flag)
                {
                    _stream.Write(_buffer, 0, bytesRead);
                }
            }
            while (flag);
        }
        _stream.Flush();
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._stream, System.IO.Compression.DeflateStream._wroteBytes, System.IO.Stream.Flush(), System.IO.Compression.Deflater.Flush(), System.IO.Stream.Write(), and System.IO.Compression.DeflateStream.WriteDeflaterOutput().
Referenced by System.IO.Compression.DeflateStream.Flush().