Terraria: System.IO.Compression.DeflateStream.PurgeBuffers
PurgeBuffers()
void System.IO.Compression.DeflateStream.PurgeBuffers (bool disposing) inline private
Definition at line 672 of file DeflateStream.cs.
    {
        if (!disposing || _stream == null || _mode != CompressionMode.Compress)
        {
            return;
        }
        if (_wroteBytes)
        {
            WriteDeflaterOutput();
            bool flag;
            do
            {
                flag = _deflater.Finish(_buffer, out var bytesRead);
                if (bytesRead > 0)
                {
                    _stream.Write(_buffer, 0, bytesRead);
                }
            }
            while (!flag);
        }
        else
        {
            int bytesRead2;
            while (!_deflater.Finish(_buffer, out bytesRead2))
            {
            }
        }
    }
References System.IO.Compression.DeflateStream._buffer, System.IO.Compression.DeflateStream._deflater, System.IO.Compression.DeflateStream._mode, System.IO.Compression.DeflateStream._stream, System.IO.Compression.DeflateStream._wroteBytes, System.IO.Compression.Deflater.Finish(), System.IO.Stream.Write(), and System.IO.Compression.DeflateStream.WriteDeflaterOutput().
Referenced by System.IO.Compression.DeflateStream.Dispose().