Terraria: System.IO.Compression.DeflateStream.Read
Read() [1/2]
override int System.IO.Compression.DeflateStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 442 of file DeflateStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        return ReadCore(new Span<byte>(buffer, offset, count));
    }
References System.buffer, System.count, System.offset, System.IO.Compression.DeflateStream.ReadCore(), and System.IO.Stream.ValidateBufferArguments().
Referenced by System.IO.Compression.GZipStream.Read(), and System.IO.Compression.ZLibStream.Read().