Terraria: System.Security.Principal.NTAccount.TranslateToSids
TranslateToSids()
static IdentityReferenceCollection System.Security.Principal.NTAccount.TranslateToSids (IdentityReferenceCollection sourceAccounts, out bool someFailed) inline static private
Definition at line 157 of file NTAccount.cs.
    {
        if (sourceAccounts == null)
        {
            throw new ArgumentNullException("sourceAccounts");
        }
        if (sourceAccounts.Count == 0)
        {
            throw new ArgumentException(System.SR.Arg_EmptyCollection, "sourceAccounts");
        }
        SafeLsaPolicyHandle safeLsaPolicyHandle = null;
        SafeLsaMemoryHandle referencedDomains = null;
        SafeLsaMemoryHandle sids = null;
        try
        {
            global::Interop.Advapi32.MARSHALLED_UNICODE_STRING[] array = new global::Interop.Advapi32.MARSHALLED_UNICODE_STRING[sourceAccounts.Count];
            int num = 0;
            foreach (IdentityReference sourceAccount in sourceAccounts)
            {
                if (!(sourceAccount is NTAccount nTAccount))
                {
                    throw new ArgumentException(System.SR.Argument_ImproperType, "sourceAccounts");
                }
                array[num].Buffer = nTAccount.ToString();
                if (array[num].Buffer.Length * 2 + 2 > 65535)
                {
                    throw new InvalidOperationException();
                }
                array[num].Length = (ushort)(array[num].Buffer.Length * 2);
                array[num].MaximumLength = (ushort)(array[num].Length + 2);
                num++;
            }
            safeLsaPolicyHandle = Win32.LsaOpenPolicy(null, PolicyRights.POLICY_LOOKUP_NAMES);
            someFailed = false;
            uint num2 = global::Interop.Advapi32.LsaLookupNames2(safeLsaPolicyHandle, 0, sourceAccounts.Count, array, out referencedDomains, out sids);
            switch (num2)
            {
            case 3221225495u:
            case 3221225626u:
                throw new OutOfMemoryException();
            case 3221225506u:
                throw new UnauthorizedAccessException();
            case 3221225587u:
            case 263u:
                someFailed = true;
                break;
            default:
            {
                uint error = global::Interop.Advapi32.LsaNtStatusToWinError(num2);
                _ = 1789;
                throw new Win32Exception((int)error);
            }
            case 0u:
                break;
            }
            IdentityReferenceCollection identityReferenceCollection = new IdentityReferenceCollection(sourceAccounts.Count);
            if (num2 == 0 || num2 == 263)
            {
                sids.Initialize((uint)sourceAccounts.Count, (uint)Marshal.SizeOf<global::Interop.LSA_TRANSLATED_SID2>());
                Win32.InitializeReferencedDomainsPointer(referencedDomains);
                global::Interop.LSA_TRANSLATED_SID2[] array2 = new global::Interop.LSA_TRANSLATED_SID2[sourceAccounts.Count];
                sids.ReadArray(0uL, array2, 0, array2.Length);
                for (int i = 0; i < sourceAccounts.Count; i++)
                {
                    global::Interop.LSA_TRANSLATED_SID2 lSA_TRANSLATED_SID = array2[i];
                    switch ((SidNameUse)lSA_TRANSLATED_SID.Use)
                    {
                    case SidNameUse.User:
                    case SidNameUse.Group:
                    case SidNameUse.Alias:
                    case SidNameUse.WellKnownGroup:
                    case SidNameUse.Computer:
                        identityReferenceCollection.Add(new SecurityIdentifier(lSA_TRANSLATED_SID.Sid));
                        break;
                    default:
                        someFailed = true;
                        identityReferenceCollection.Add(sourceAccounts[i]);
                        break;
                    }
                }
            }
            else
            {
                for (int j = 0; j < sourceAccounts.Count; j++)
                {
                    identityReferenceCollection.Add(sourceAccounts[j]);
                }
            }
            return identityReferenceCollection;
        }
        finally
        {
            safeLsaPolicyHandle?.Dispose();
            referencedDomains?.Dispose();
            sids?.Dispose();
        }
    }
References System.Security.Principal.IdentityReferenceCollection.Add(), System.SR.Arg_EmptyCollection, System.SR.Argument_ImproperType, System.array, System.Security.Principal.IdentityReferenceCollection.Count, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Security.Principal.Win32.InitializeReferencedDomainsPointer(), System.Security.Principal.Win32.LsaOpenPolicy(), and System.Runtime.InteropServices.Marshal.SizeOf().
Referenced by System.Security.Principal.NTAccount.Translate().