Terraria: System.Security.Cryptography.DSA.TrySignDataCore
TrySignDataCore()
virtual bool System.Security.Cryptography.DSA.TrySignDataCore (ReadOnlySpan< byte > data, Span< byte > destination, HashAlgorithmName hashAlgorithm, DSASignatureFormat signatureFormat, out int bytesWritten) inline protected virtual inherited
Definition at line 364 of file DSA.cs.
    {
        Span<byte> tmp = stackalloc byte[128];
        ReadOnlySpan<byte> hash = HashSpanToTmp(data, hashAlgorithm, tmp);
        return TryCreateSignatureCore(hash, destination, signatureFormat, out bytesWritten);
    }
References System.destination, System.Security.Cryptography.DSA.HashSpanToTmp(), and System.Security.Cryptography.DSA.TryCreateSignatureCore().
Referenced by System.Security.Cryptography.DSA.SignDataCore(), and System.Security.Cryptography.DSA.TrySignData().