Terraria: System.Security.Cryptography.DSA.VerifySignatureCore
VerifySignatureCore()
virtual bool System.Security.Cryptography.DSA.VerifySignatureCore (ReadOnlySpan< byte > hash, ReadOnlySpan< byte > signature, DSASignatureFormat signatureFormat) inline protected virtual inherited
Reimplemented in System.Security.Cryptography.DSAImplementation.DSACng.
Definition at line 479 of file DSA.cs.
    {
        byte[] array = this.ConvertSignatureToIeeeP1363(signatureFormat, signature);
        if (array == null)
        {
            return false;
        }
        return VerifySignature(hash, array);
    }
References System.array, and System.Security.Cryptography.DSA.VerifySignature().
Referenced by System.Security.Cryptography.DSA.VerifyDataCore(), System.Security.Cryptography.DSA.VerifyDataCore(), System.Security.Cryptography.DSA.VerifySignature(), and System.Security.Cryptography.DSA.VerifySignature().