Terraria: System.Security.Cryptography.DSA.ImportEncryptedPkcs8PrivateKey
ImportEncryptedPkcs8PrivateKey() [2/2]
unsafe override void System.Security.Cryptography.DSA.ImportEncryptedPkcs8PrivateKey (ReadOnlySpan< char > password, ReadOnlySpan< byte > source, out int bytesRead) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Reimplemented in System.Security.Cryptography.DSAImplementation.DSACng, System.Security.Cryptography.DSACng, and System.Security.Cryptography.DSACryptoServiceProvider.
Definition at line 604 of file DSA.cs.
    {
        DSAKeyFormatHelper.ReadEncryptedPkcs8(source, password, out var bytesRead2, out var key);
        fixed (byte* ptr = key.X)
        {
            try
            {
                ImportParameters(key);
            }
            finally
            {
                CryptographicOperations.ZeroMemory(key.X);
            }
        }
        bytesRead = bytesRead2;
    }
References System.Security.Cryptography.DSA.ImportParameters(), System.key, System.Security.Cryptography.DSAKeyFormatHelper.ReadEncryptedPkcs8(), System.source, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().