Terraria: System.Security.Cryptography.DSA.WritePkcs8
WritePkcs8()
unsafe AsnWriter System.Security.Cryptography.DSA.WritePkcs8 () inline private inherited
Definition at line 565 of file DSA.cs.
    {
        DSAParameters dsaParameters = ExportParameters(includePrivateParameters: true);
        fixed (byte* ptr = dsaParameters.X)
        {
            try
            {
                return DSAKeyFormatHelper.WritePkcs8(in dsaParameters);
            }
            finally
            {
                CryptographicOperations.ZeroMemory(dsaParameters.X);
            }
        }
    }
References System.Security.Cryptography.DSA.ExportParameters(), System.Security.Cryptography.DSAKeyFormatHelper.WritePkcs8(), System.Security.Cryptography.DSAParameters.X, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.DSA.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.DSA.TryExportEncryptedPkcs8PrivateKey(), and System.Security.Cryptography.DSA.TryExportPkcs8PrivateKey().