Terraria: System.Security.Cryptography.DSA.ReadRequiredElement
ReadRequiredElement()
static byte[] System.Security.Cryptography.DSA.ReadRequiredElement (ref XmlKeyHelper::ParseState state, string name, int sizeHint = -1) inline static private inherited
Definition at line 678 of file DSA.cs.
    {
        byte[] array = XmlKeyHelper.ReadCryptoBinary(ref state, name, sizeHint);
        if (array == null)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_InvalidFromXmlString, "DSA", name));
        }
        return array;
    }
References System.array, System.SR.Cryptography_InvalidFromXmlString, System.SR.Format(), System.Security.Cryptography.XmlKeyHelper.ReadCryptoBinary(), and System.state.
Referenced by System.Security.Cryptography.DSA.FromXmlString().