Terraria: System.Security.Cryptography.DSA.VerifyData
VerifyData() [2/8]
bool System.Security.Cryptography.DSA.VerifyData (byte[] data, byte[] signature, HashAlgorithmName hashAlgorithm, DSASignatureFormat signatureFormat) inline inherited
Definition at line 380 of file DSA.cs.
    {
        if (data == null)
        {
            throw new ArgumentNullException("data");
        }
        if (signature == null)
        {
            throw new ArgumentNullException("signature");
        }
        if (string.IsNullOrEmpty(hashAlgorithm.Name))
        {
            throw HashAlgorithmNameNullOrEmpty();
        }
        if (!signatureFormat.IsKnownValue())
        {
            throw DSASignatureFormatHelpers.CreateUnknownValueException(signatureFormat);
        }
        return VerifyDataCore(data, signature, hashAlgorithm, signatureFormat);
    }
References System.Security.Cryptography.DSASignatureFormatHelpers.CreateUnknownValueException(), System.Security.Cryptography.DSA.HashAlgorithmNameNullOrEmpty(), System.Security.Cryptography.HashAlgorithmName.Name, and System.Security.Cryptography.DSA.VerifyDataCore().