Terraria: System.Security.Cryptography.DSA.ImportSubjectPublicKeyInfo
ImportSubjectPublicKeyInfo()
override void System.Security.Cryptography.DSA.ImportSubjectPublicKeyInfo (ReadOnlySpan< byte > source, out int bytesRead) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 638 of file DSA.cs.
    {
        DSAKeyFormatHelper.ReadSubjectPublicKeyInfo(source, out var bytesRead2, out var key);
        ImportParameters(key);
        bytesRead = bytesRead2;
    }
References System.Security.Cryptography.DSA.ImportParameters(), System.key, System.Security.Cryptography.DSAKeyFormatHelper.ReadSubjectPublicKeyInfo(), and System.source.
Referenced by System.Security.Cryptography.X509Certificates.PublicKey.GetDSAPublicKey(), and System.Security.Cryptography.DSA.ImportFromPem().