Terraria: System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.FilterAndTransform
FilterAndTransform() [1/2]
System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.FilterAndTransform (string filterAndPayloadSpec, int startIdx, int endIdx, DiagnosticSourceEventSource eventSource, FilterAndTransform next) inline
Definition at line 123 of file DiagnosticSourceEventSource.cs.
        {
            FilterAndTransform filterAndTransform = this;
            Next = next;
            _eventSource = eventSource;
            string listenerNameFilter = null;
            string eventNameFilter = null;
            string text = null;
            int num = startIdx;
            int num2 = endIdx;
            int num3 = filterAndPayloadSpec.IndexOf(':', startIdx, endIdx - startIdx);
            if (0 <= num3)
            {
                num2 = num3;
                num = num3 + 1;
            }
            int num4 = filterAndPayloadSpec.IndexOf('/', startIdx, num2 - startIdx);
            if (0 <= num4)
            {
                listenerNameFilter = filterAndPayloadSpec.Substring(startIdx, num4 - startIdx);
                int num5 = filterAndPayloadSpec.IndexOf('@', num4 + 1, num2 - num4 - 1);
                if (0 <= num5)
                {
                    text = filterAndPayloadSpec.Substring(num5 + 1, num2 - num5 - 1);
                    eventNameFilter = filterAndPayloadSpec.Substring(num4 + 1, num5 - num4 - 1);
                }
                else
                {
                    eventNameFilter = filterAndPayloadSpec.Substring(num4 + 1, num2 - num4 - 1);
                }
            }
            else if (startIdx < num2)
            {
                listenerNameFilter = filterAndPayloadSpec.Substring(startIdx, num2 - startIdx);
            }
            _eventSource.Message("DiagnosticSource: Enabling '" + (listenerNameFilter ?? "*") + "/" + (eventNameFilter ?? "*") + "'");
            if (num < endIdx && filterAndPayloadSpec[num] == '-')
            {
                _eventSource.Message("DiagnosticSource: suppressing implicit transforms.");
                _noImplicitTransforms = true;
                num++;
            }
            if (num < endIdx)
            {
                while (true)
                {
                    int num6 = num;
                    int num7 = filterAndPayloadSpec.LastIndexOf(';', endIdx - 1, endIdx - num);
                    if (0 <= num7)
                    {
                        num6 = num7 + 1;
                    }
                    if (num6 < endIdx)
                    {
                        if (_eventSource.IsEnabled(EventLevel.Informational, (EventKeywords)1L))
{
                            _eventSource.Message("DiagnosticSource: Parsing Explicit Transform '" + filterAndPayloadSpec.Substring(num6, endIdx - num6) + "'");
                        }
                        _explicitTransforms = new TransformSpec(filterAndPayloadSpec, num6, endIdx, _explicitTransforms);
                    }
                    if (num == num6)
                    {
                        break;
                    }
                    endIdx = num7;
                }
            }
            Action<string, string, IEnumerable<KeyValuePair<string, string>>> writeEvent = null;
            if (text != null && text.Contains("Activity"))
            {
                writeEvent = text switch
                {
                    "Activity1Start" => _eventSource.Activity1Start,
                    "Activity1Stop" => _eventSource.Activity1Stop,
                    "Activity2Start" => _eventSource.Activity2Start,
                    "Activity2Stop" => _eventSource.Activity2Stop,
                    "RecursiveActivity1Start" => _eventSource.RecursiveActivity1Start,
                    "RecursiveActivity1Stop" => _eventSource.RecursiveActivity1Stop,
                    _ => null,
                };
                if (writeEvent == null)
                {
                    _eventSource.Message("DiagnosticSource: Could not find Event to log Activity " + text);
                }
            }
            if (writeEvent == null)
            {
                writeEvent = _eventSource.Event;
            }
            _diagnosticsListenersSubscription = DiagnosticListener.AllListeners.Subscribe(new CallbackObserver<DiagnosticListener>(delegate(DiagnosticListener newListener)
            {
                if (listenerNameFilter == null || listenerNameFilter == newListener.Name)
                {
                    filterAndTransform._eventSource.NewDiagnosticListener(newListener.Name);
                    Predicate<string> isEnabled = null;
                    if (eventNameFilter != null)
                    {
                        isEnabled = (string eventName) => eventNameFilter == eventName;
                    }
                    IDisposable subscription = newListener.Subscribe(new CallbackObserver<KeyValuePair<string, object>>(OnEventWritten), isEnabled);
                    filterAndTransform._liveSubscriptions = new Subscriptions(subscription, filterAndTransform._liveSubscriptions);
                }
                [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "DiagnosticSource.Write is marked with RequiresUnreferencedCode.")]
                void OnEventWritten(KeyValuePair<string, object> evnt)
                {
                    if (eventNameFilter == null || !(eventNameFilter != evnt.Key))
                    {
                        List<KeyValuePair<string, string>> arg = filterAndTransform.Morph(evnt.Value);
                        string key = evnt.Key;
                        writeEvent(newListener.Name, key, arg);
                    }
                }
            }));
        }
References System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform._diagnosticsListenersSubscription, System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform._eventSource, System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform._explicitTransforms, System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform._noImplicitTransforms, System.Diagnostics.DiagnosticSourceEventSource.Activity1Start(), System.Diagnostics.DiagnosticSourceEventSource.Activity1Stop(), System.Diagnostics.DiagnosticSourceEventSource.Activity2Start(), System.Diagnostics.DiagnosticSourceEventSource.Activity2Stop(), System.Diagnostics.DiagnosticListener.AllListeners, System.Diagnostics.DiagnosticSourceEventSource.Event(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.key, System.L, System.Diagnostics.DiagnosticSourceEventSource.Message(), System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.Next, System.Diagnostics.DiagnosticSourceEventSource.RecursiveActivity1Start(), System.Diagnostics.DiagnosticSourceEventSource.RecursiveActivity1Stop(), and System.text.
Referenced by System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.CreateFilterAndTransformList().