Terraria: Terraria.UI.NetDiagnosticsUI.DrawCounter
DrawCounter()
void Terraria.UI.NetDiagnosticsUI.DrawCounter (SpriteBatch spriteBatch, ref CounterForMessage counter, string title, Vector2 position) inline private
Definition at line 117 of file NetDiagnosticsUI.cs.
    {
        if (!counter.exemptFromBadScoreTest)
        {
            if (_highestFoundReadCount < counter.timesReceived)
            {
                _highestFoundReadCount = counter.timesReceived;
            }
            if (_highestFoundReadBytes < counter.bytesReceived)
            {
                _highestFoundReadBytes = counter.bytesReceived;
            }
        }
        Vector2 pos = position;
        string text = title + ": ";
        float num = Utils.Remap(counter.bytesReceived, 0f, _highestFoundReadBytes, 0f, 1f);
        Color color = Main.hslToRgb(0.3f * (1f - num), 1f, 0.5f);
        if (counter.exemptFromBadScoreTest)
        {
            color = Color.White;
        }
        string text2 = "";
        text2 = text;
        DrawText(spriteBatch, text2, pos, color);
        pos.X += 30f;
        text2 = "rx:" + $"{counter.timesReceived}";
        DrawText(spriteBatch, text2, pos, color);
        pos.X += 70f;
        text2 = $"{counter.bytesReceived}";
        DrawText(spriteBatch, text2, pos, color);
        pos.X += 70f;
        text2 = text;
        DrawText(spriteBatch, text2, pos, color);
        pos.X += 30f;
        text2 = "tx:" + $"{counter.timesSent}";
        DrawText(spriteBatch, text2, pos, color);
        pos.X += 70f;
        text2 = $"{counter.bytesSent}";
        DrawText(spriteBatch, text2, pos, color);
    }
References Terraria.UI.NetDiagnosticsUI._highestFoundReadBytes, Terraria.UI.NetDiagnosticsUI._highestFoundReadCount, Terraria.UI.NetDiagnosticsUI.DrawText(), Terraria.Main.hslToRgb(), Terraria.Utils.Remap(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.UI.NetDiagnosticsUI.Draw().