Terraria: TriggersSet.CopyInto
CopyInto()
void TriggersSet.CopyInto (Player p) inline
     {
         if (PlayerInput.CurrentInputMode != InputMode.XBoxGamepadUI && !PlayerInput.CursorIsBusy)
         {
             p.controlUp = Up;
             p.controlDown = Down;
             p.controlLeft = Left;
             p.controlRight = Right;
             p.controlJump = Jump;
             p.controlHook = Grapple;
             p.controlTorch = SmartSelect;
             p.controlSmart = SmartCursor;
             p.controlMount = QuickMount;
             p.controlQuickHeal = QuickHeal;
             p.controlQuickMana = QuickMana;
             p.controlCreativeMenu = OpenCreativePowersMenu;
             if (QuickBuff)
             {
                 p.QuickBuff();
             }
             if (Loadout1)
             {
                 p.TrySwitchingLoadout(0);
             }
             if (Loadout2)
             {
                 p.TrySwitchingLoadout(1);
             }
             if (Loadout3)
             {
                 p.TrySwitchingLoadout(2);
             }
         }
         p.controlInv = Inventory;
         p.controlThrow = Throw;
         p.mapZoomIn = MapZoomIn;
         p.mapZoomOut = MapZoomOut;
         p.mapAlphaUp = MapAlphaUp;
         p.mapAlphaDown = MapAlphaDown;
         p.mapFullScreen = MapFull;
         p.mapStyle = MapStyle;
         if (MouseLeft)
         {
             if (!Main.blockMouse && !p.mouseInterface)
             {
                 p.controlUseItem = true;
             }
         }
         else
         {
             Main.blockMouse = false;
         }
         if (!MouseRight && !Main.playerInventory)
         {
             PlayerInput.LockGamepadTileUseButton = false;
         }
         if (MouseRight && !p.mouseInterface && !Main.blockMouse && !ShouldLockTileUsage() && !PlayerInput.InBuildingMode)
         {
             p.controlUseTile = true;
         }
         if (PlayerInput.InBuildingMode && MouseRight)
         {
             p.controlInv = true;
         }
         if (SmartSelect && LatestInputMode.TryGetValue("SmartSelect", out var value) && IsInputFromGamepad(value))
         {
             PlayerInput.SettingsForUI.SetCursorMode(CursorMode.Gamepad);
         }
         bool flag = PlayerInput.Triggers.Current.HotbarPlus || PlayerInput.Triggers.Current.HotbarMinus;
         if (flag)
         {
             HotbarHoldTime++;
         }
         else
         {
             HotbarHoldTime = 0;
         }
         if (HotbarScrollCD > 0 && (!(HotbarScrollCD == 1 && flag) || PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired <= 0))
         {
             HotbarScrollCD--;
         }
     }
References Main.blockMouse, Player.controlCreativeMenu, Player.controlDown, Player.controlHook, Player.controlInv, Player.controlJump, Player.controlLeft, Player.controlMount, Player.controlQuickHeal, Player.controlQuickMana, Player.controlRight, Player.controlSmart, Player.controlThrow, Player.controlTorch, Player.controlUp, Player.controlUseItem, Player.controlUseTile, TriggersPack.Current, PlayerInput.CurrentInputMode, PlayerInput.CurrentProfile, PlayerInput.CursorIsBusy, Down, Grapple, HotbarHoldTime, HotbarMinus, HotbarPlus, PlayerInputProfile.HotbarRadialHoldTimeRequired, HotbarScrollCD, PlayerInput.InBuildingMode, Inventory, IsInputFromGamepad(), Jump, LatestInputMode, Left, Loadout1, Loadout2, Loadout3, PlayerInput.LockGamepadTileUseButton, MapAlphaDown, Player.mapAlphaDown, MapAlphaUp, Player.mapAlphaUp, MapFull, Player.mapFullScreen, MapStyle, Player.mapStyle, MapZoomIn, Player.mapZoomIn, MapZoomOut, Player.mapZoomOut, Player.mouseInterface, MouseLeft, MouseRight, OpenCreativePowersMenu, Main.playerInventory, QuickBuff, Player.QuickBuff(), QuickHeal, QuickMana, QuickMount, Right, PlayerInput.SettingsForUI.SetCursorMode(), ShouldLockTileUsage(), SmartCursor, SmartSelect, Throw, PlayerInput.Triggers, Player.TrySwitchingLoadout(), and Up.
Referenced by Player.Ghost(), Player.Update(), and Player.UpdateDead().