Terraria: System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.CreateFilterAndTransformList
CreateFilterAndTransformList()
static void System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.CreateFilterAndTransformList (ref FilterAndTransform specList, string filterAndPayloadSpecs, DiagnosticSourceEventSource eventSource) inline static
Definition at line 64 of file DiagnosticSourceEventSource.cs.
        {
            DestroyFilterAndTransformList(ref specList, eventSource);
            if (filterAndPayloadSpecs == null)
            {
                filterAndPayloadSpecs = "";
            }
            int num = filterAndPayloadSpecs.Length;
            while (true)
            {
                if (0 < num && char.IsWhiteSpace(filterAndPayloadSpecs[num - 1]))
                {
                    num--;
                    continue;
                }
                int num2 = filterAndPayloadSpecs.LastIndexOf('\n', num - 1, num);
                int i = 0;
                if (0 <= num2)
                {
                    i = num2 + 1;
                }
                for (; i < num && char.IsWhiteSpace(filterAndPayloadSpecs[i]); i++)
                {
                }
                if (IsActivitySourceEntry(filterAndPayloadSpecs, i, num))
                {
                    AddNewActivitySourceTransform(filterAndPayloadSpecs, i, num, eventSource);
                }
                else
                {
                    specList = new FilterAndTransform(filterAndPayloadSpecs, i, num, eventSource, specList);
                }
                num = num2;
                if (num < 0)
                {
                    break;
                }
            }
            if (eventSource._activitySourceSpecs != null)
            {
                NormalizeActivitySourceSpecsList(eventSource);
                CreateActivityListener(eventSource);
            }
        }
References System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.FilterAndTransform(), System.Diagnostics.DiagnosticSourceEventSource._activitySourceSpecs, System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.AddNewActivitySourceTransform(), System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.CreateActivityListener(), System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.DestroyFilterAndTransformList(), System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.IsActivitySourceEntry(), and System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.NormalizeActivitySourceSpecsList().
Referenced by System.Diagnostics.DiagnosticSourceEventSource.OnEventCommand().