Terraria: System.IO.Strategies.OSFileStreamStrategy.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.IO.Strategies.OSFileStreamStrategy.ReadAsync (Memory< byte > destination, CancellationToken cancellationToken) inline sealed virtual inherited
Reimplemented from System.IO.Stream.
Definition at line 350 of file OSFileStreamStrategy.cs.
    {
        if (!CanSeek)
        {
            return RandomAccess.ReadAtOffsetAsync(_fileHandle, destination, -1L, cancellationToken);
        }
        if (LengthCachingSupported && _length >= 0 && Volatile.Read(ref _filePosition) >= _length)
        {
            return ValueTask.FromResult(0);
        }
        long fileOffset = Interlocked.Add(ref _filePosition, destination.Length) - destination.Length;
        return RandomAccess.ReadAtOffsetAsync(_fileHandle, destination, fileOffset, cancellationToken, this);
    }
References System.IO.Strategies.OSFileStreamStrategy._fileHandle, System.IO.Strategies.OSFileStreamStrategy._filePosition, System.IO.Strategies.OSFileStreamStrategy._length, System.Threading.Interlocked.Add(), System.cancellationToken, System.IO.Strategies.OSFileStreamStrategy.CanSeek, System.destination, System.L, System.IO.Strategies.OSFileStreamStrategy.LengthCachingSupported, System.Threading.Volatile.Read(), and System.IO.RandomAccess.ReadAtOffsetAsync().