Terraria: System.IO.Strategies.OSFileStreamStrategy.Write
Write() [2/2]
override void System.IO.Strategies.OSFileStreamStrategy.Write (ReadOnlySpan< byte > buffer) inline sealed virtual inherited
Reimplemented from System.IO.Stream.
Definition at line 300 of file OSFileStreamStrategy.cs.
    {
        if (_fileHandle.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
        else if ((_access & FileAccess.Write) == 0)
        {
            ThrowHelper.ThrowNotSupportedException_UnwritableStream();
        }
        RandomAccess.WriteAtOffset(_fileHandle, buffer, _filePosition);
        _filePosition += buffer.Length;
    }
References System.IO.Strategies.OSFileStreamStrategy._access, System.IO.Strategies.OSFileStreamStrategy._fileHandle, System.IO.Strategies.OSFileStreamStrategy._filePosition, System.buffer, System.Runtime.InteropServices.SafeHandle.IsClosed, System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), System.ThrowHelper.ThrowObjectDisposedException_FileClosed(), and System.IO.RandomAccess.WriteAtOffset().