Terraria: System.IO.Strategies.OSFileStreamStrategy.OnIncompleteOperation
OnIncompleteOperation()
void System.IO.Strategies.OSFileStreamStrategy.OnIncompleteOperation (int expectedBytesTransferred, int actualBytesTransferred) inline package inherited
Definition at line 145 of file OSFileStreamStrategy.cs.
    {
        Interlocked.Add(ref _filePosition, actualBytesTransferred - expectedBytesTransferred);
    }
References System.IO.Strategies.OSFileStreamStrategy._filePosition, and System.Threading.Interlocked.Add().
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.Complete(), and Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal().