Terraria: System.IO.Strategies.OSFileStreamStrategy.OSFileStreamStrategy
OSFileStreamStrategy() [2/2]
System.IO.Strategies.OSFileStreamStrategy.OSFileStreamStrategy (string path, FileMode mode, FileAccess access, FileShare share, FileOptions options, long preallocationSize) inline package
Definition at line 120 of file OSFileStreamStrategy.cs.
    {
        string fullPath = Path.GetFullPath(path);
        _access = access;
        _lengthCanBeCached = (share & FileShare.Write) == 0 && (access & FileAccess.Write) == 0;
        _fileHandle = SafeFileHandle.Open(fullPath, mode, access, share, options, preallocationSize);
        try
        {
            if (mode == FileMode.Append && CanSeek)
            {
                _appendStart = (_filePosition = Length);
            }
            else
            {
                _appendStart = -1L;
            }
        }
        catch
        {
            _fileHandle.Dispose();
            _fileHandle = null;
            throw;
        }
    }
References System.IO.Strategies.OSFileStreamStrategy._access, System.IO.Strategies.OSFileStreamStrategy._appendStart, System.IO.Strategies.OSFileStreamStrategy._fileHandle, System.IO.Strategies.OSFileStreamStrategy._filePosition, System.IO.Strategies.OSFileStreamStrategy._lengthCanBeCached, System.IO.Strategies.OSFileStreamStrategy.CanSeek, System.Runtime.InteropServices.SafeHandle.Dispose(), System.IO.Path.GetFullPath(), System.L, System.IO.Strategies.OSFileStreamStrategy.Length, Microsoft.Win32.SafeHandles.SafeFileHandle.Open(), and System.options.