Terraria: System.IO.Strategies.OSFileStreamStrategy.Seek
Seek()
override long System.IO.Strategies.OSFileStreamStrategy.Seek (long offset, SeekOrigin origin) inline sealed inherited
Definition at line 191 of file OSFileStreamStrategy.cs.
    {
        if (origin < SeekOrigin.Begin || origin > SeekOrigin.End)
        {
            throw new ArgumentException(SR.Argument_InvalidSeekOrigin, "origin");
        }
        if (_fileHandle.IsClosed)
        {
            ThrowHelper.ThrowObjectDisposedException_FileClosed();
        }
        if (!CanSeek)
        {
            ThrowHelper.ThrowNotSupportedException_UnseekableStream();
        }
        long filePosition = _filePosition;
        long num = origin switch
        {
            SeekOrigin.Begin => offset,
            SeekOrigin.End => Length + offset,
            _ => _filePosition + offset,
        };
        if (num >= 0)
        {
            _filePosition = num;
        }
        else
        {
            FileStreamHelpers.ThrowInvalidArgument(_fileHandle);
        }
        if (_appendStart != -1 && num < _appendStart)
        {
            _filePosition = filePosition;
            throw new IOException(SR.IO_SeekAppendOverwrite);
        }
        return num;
    }
References System.IO.Strategies.OSFileStreamStrategy._appendStart, System.IO.Strategies.OSFileStreamStrategy._fileHandle, System.IO.Strategies.OSFileStreamStrategy._filePosition, System.SR.Argument_InvalidSeekOrigin, System.IO.Strategies.OSFileStreamStrategy.CanSeek, System.SR.IO_SeekAppendOverwrite, System.Runtime.InteropServices.SafeHandle.IsClosed, System.IO.Strategies.OSFileStreamStrategy.Length, System.offset, System.IO.Strategies.FileStreamHelpers.ThrowInvalidArgument(), System.ThrowHelper.ThrowNotSupportedException_UnseekableStream(), and System.ThrowHelper.ThrowObjectDisposedException_FileClosed().