Terraria: System.Collections.Specialized.NameValueCollection.Set
Set()
virtual void System.Collections.Specialized.NameValueCollection.Set (string? name, string? value) inline virtual inherited
Definition at line 248 of file NameValueCollection.cs.
    {
        if (base.IsReadOnly)
        {
            throw new NotSupportedException(System.SR.CollectionReadOnly);
        }
        InvalidateCachedArrays();
        ArrayList arrayList = new ArrayList(1);
        arrayList.Add(value);
        BaseSet(name, arrayList);
    }
References System.Collections.Specialized.NameObjectCollectionBase.BaseSet(), System.SR.CollectionReadOnly, System.Runtime.Serialization.Dictionary, System.Collections.Specialized.NameValueCollection.InvalidateCachedArrays(), and System.value.
Referenced by System.Net.WebHeaderCollection.Set().