Terraria: System.Collections.Specialized.NameValueCollection.Clear
Clear()
virtual void System.Collections.Specialized.NameValueCollection.Clear () inline virtual inherited
Reimplemented in System.Net.WebHeaderCollection.
Definition at line 155 of file NameValueCollection.cs.
    {
        if (base.IsReadOnly)
        {
            throw new NotSupportedException(System.SR.CollectionReadOnly);
        }
        InvalidateCachedArrays();
        BaseClear();
    }
References System.Collections.Specialized.NameObjectCollectionBase.BaseClear(), System.SR.CollectionReadOnly, System.Runtime.Serialization.Dictionary, and System.Collections.Specialized.NameValueCollection.InvalidateCachedArrays().
Referenced by System.Net.WebHeaderCollection.Clear().