Terraria: System.Net.Http.Headers.NameValueWithParametersHeaderValue.ToString
ToString() [1/2]
override string System.Net.Http.Headers.NameValueWithParametersHeaderValue.ToString () inline
Definition at line 53 of file NameValueWithParametersHeaderValue.cs.
    {
        string value = base.ToString();
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        stringBuilder.Append(value);
        NameValueHeaderValue.ToString(_parameters, ';', leadingSeparator: true, stringBuilder);
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Net.Http.Headers.NameValueWithParametersHeaderValue._parameters, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilderCache.GetStringAndRelease(), System.Net.Http.Headers.NameValueHeaderValue.ToString(), and System.value.