Terraria: System.ComponentModel.Design.DesignerTransaction.Dispose
Dispose() [1/2]
void IDisposable. System.ComponentModel.Design.DesignerTransaction.Dispose () inline private
Implements System.IDisposable.
Definition at line 54 of file DesignerTransaction.cs.
    {
        Dispose(disposing: true);
        if (!_suppressedFinalization)
        {
            GC.SuppressFinalize(this);
        }
    }
References System.ComponentModel.Design.DesignerTransaction._suppressedFinalization, System.ComponentModel.Design.DesignerTransaction.Dispose(), and System.GC.SuppressFinalize().
Referenced by System.ComponentModel.Design.DesignerTransaction.~DesignerTransaction(), and System.ComponentModel.Design.DesignerTransaction.Dispose().