Terraria: System.Collections.Specialized.NameValueCollection.Add
Add() [2/2]
virtual void System.Collections.Specialized.NameValueCollection.Add (string? name, string? value) inline virtual inherited
Definition at line 213 of file NameValueCollection.cs.
    {
        if (base.IsReadOnly)
        {
            throw new NotSupportedException(System.SR.CollectionReadOnly);
        }
        InvalidateCachedArrays();
        ArrayList arrayList = (ArrayList)BaseGet(name);
        if (arrayList == null)
        {
            arrayList = new ArrayList(1);
            if (value != null)
            {
                arrayList.Add(value);
            }
            BaseAdd(name, arrayList);
        }
        else if (value != null)
        {
            arrayList.Add(value);
        }
    }
References System.Collections.Specialized.NameObjectCollectionBase.BaseAdd(), System.Collections.Specialized.NameObjectCollectionBase.BaseGet(), System.SR.CollectionReadOnly, System.Runtime.Serialization.Dictionary, System.Collections.Specialized.NameValueCollection.InvalidateCachedArrays(), and System.value.