Terraria: System.ComponentModel.Design.DesignerTransaction.Cancel
Cancel()
void System.ComponentModel.Design.DesignerTransaction.Cancel () inline
Definition at line 23 of file DesignerTransaction.cs.
    {
        if (!Canceled && !Committed)
        {
            Canceled = true;
            GC.SuppressFinalize(this);
            _suppressedFinalization = true;
            OnCancel();
        }
    }
References System.ComponentModel.Design.DesignerTransaction._suppressedFinalization, System.ComponentModel.Design.DesignerTransaction.Canceled, System.ComponentModel.Design.DesignerTransaction.Committed, System.ComponentModel.Design.DesignerTransaction.OnCancel(), and System.GC.SuppressFinalize().
Referenced by System.ComponentModel.Design.DesignerTransaction.Dispose().