Terraria: System.Xml.Xsl.Runtime.AncestorIterator.Create
Create()
void System.Xml.Xsl.Runtime.AncestorIterator.Create (XPathNavigator context, XmlNavigatorFilter filter, bool orSelf) inline
Definition at line 17 of file AncestorIterator.cs.
    {
        _filter = filter;
        _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, context);
        _haveCurrent = orSelf && !_filter.IsFiltered(_navCurrent);
    }
References System.Xml.Xsl.Runtime.AncestorIterator._filter, System.Xml.Xsl.Runtime.AncestorIterator._haveCurrent, System.Xml.Xsl.Runtime.AncestorIterator._navCurrent, System.Xml.Dictionary, System.Xml.Xsl.Runtime.XmlNavigatorFilter.IsFiltered(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator().
Referenced by System.Xml.Xsl.Runtime.AncestorDocOrderIterator.Create().