Terraria: System.Transactions.DurableEnlistmentCommitting.EnterState
EnterState()
override void System.Transactions.DurableEnlistmentCommitting.EnterState (InternalEnlistment enlistment) inline package
Definition at line 7 of file DurableEnlistmentCommitting.cs.
    {
        bool flag = false;
        enlistment.State = this;
        Monitor.Exit(enlistment.Transaction);
        try
        {
            TransactionsEtwProvider log = TransactionsEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.EnlistmentStatus(enlistment, NotificationCall.SinglePhaseCommit);
            }
            if (enlistment.SinglePhaseNotification != null)
            {
                enlistment.SinglePhaseNotification.SinglePhaseCommit(enlistment.SinglePhaseEnlistment);
            }
            else
            {
                enlistment.PromotableSinglePhaseNotification.SinglePhaseCommit(enlistment.SinglePhaseEnlistment);
            }
            flag = true;
        }
        finally
        {
            if (!flag)
            {
                enlistment.SinglePhaseEnlistment.InDoubt();
            }
            Monitor.Enter(enlistment.Transaction);
        }
    }
References System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Transactions.SinglePhaseEnlistment.InDoubt(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.InternalEnlistment.PromotableSinglePhaseNotification, System.Transactions.IPromotableSinglePhaseNotification.SinglePhaseCommit(), System.Transactions.ISinglePhaseNotification.SinglePhaseCommit(), System.Transactions.InternalEnlistment.SinglePhaseEnlistment, System.Transactions.InternalEnlistment.SinglePhaseNotification, and System.Transactions.InternalEnlistment.Transaction.