Terraria: MS.Internal.Xml.XPath.StringFunctions.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.StringFunctions.Evaluate (XPathNodeIterator nodeIterator) inline
Definition at line 60 of file StringFunctions.cs.
    {
        return _funcType switch
        {
            Function.FunctionType.FuncString => toString(nodeIterator),
            Function.FunctionType.FuncConcat => Concat(nodeIterator),
            Function.FunctionType.FuncStartsWith => StartsWith(nodeIterator),
            Function.FunctionType.FuncContains => Contains(nodeIterator),
            Function.FunctionType.FuncSubstringBefore => SubstringBefore(nodeIterator),
            Function.FunctionType.FuncSubstringAfter => SubstringAfter(nodeIterator),
            Function.FunctionType.FuncSubstring => Substring(nodeIterator),
            Function.FunctionType.FuncStringLength => StringLength(nodeIterator),
            Function.FunctionType.FuncNormalize => Normalize(nodeIterator),
            Function.FunctionType.FuncTranslate => Translate(nodeIterator),
            _ => string.Empty,
        };
    }
References MS.Internal.Xml.XPath.StringFunctions._funcType, MS.Internal.Xml.XPath.StringFunctions.Concat(), MS.Internal.Xml.XPath.StringFunctions.Contains(), System.Xml.Dictionary, MS.Internal.Xml.XPath.StringFunctions.Normalize(), MS.Internal.Xml.XPath.StringFunctions.StartsWith(), MS.Internal.Xml.XPath.StringFunctions.StringLength(), MS.Internal.Xml.XPath.StringFunctions.Substring(), MS.Internal.Xml.XPath.StringFunctions.SubstringAfter(), MS.Internal.Xml.XPath.StringFunctions.SubstringBefore(), MS.Internal.Xml.XPath.StringFunctions.toString(), and MS.Internal.Xml.XPath.StringFunctions.Translate().
Referenced by MS.Internal.Xml.XPath.StringFunctions.Concat().