Terraria: MS.Internal.Xml.XPath.StringFunctions.Substring
Substring()
string MS.Internal.Xml.XPath.StringFunctions.Substring (XPathNodeIterator nodeIterator) inline private
Definition at line 186 of file StringFunctions.cs.
    {
        string text = _argList[0].Evaluate(nodeIterator).ToString();
        double num = XmlConvert.XPathRound(XmlConvert.ToXPathDouble(_argList[1].Evaluate(nodeIterator))) - 1.0;
        if (double.IsNaN(num) || (double)text.Length <= num)
        {
            return string.Empty;
        }
        if (_argList.Count == 3)
        {
            double num2 = XmlConvert.XPathRound(XmlConvert.ToXPathDouble(_argList[2].Evaluate(nodeIterator)));
            if (double.IsNaN(num2))
            {
                return string.Empty;
            }
            if (num < 0.0 || num2 < 0.0)
            {
                num2 = num + num2;
                if (!(num2 > 0.0))
                {
                    return string.Empty;
                }
                num = 0.0;
            }
            double num3 = (double)text.Length - num;
            if (num2 > num3)
            {
                num2 = num3;
            }
            return text.Substring((int)num, (int)num2);
        }
        if (num < 0.0)
        {
            num = 0.0;
        }
        return text.Substring((int)num);
    }
References MS.Internal.Xml.XPath.StringFunctions._argList, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.XmlConvert.ToXPathDouble(), and System.Xml.XmlConvert.XPathRound().
Referenced by MS.Internal.Xml.XPath.StringFunctions.Evaluate().