Terraria: MS.Internal.Xml.XPath.FilterQuery.MatchNode
MatchNode()
override XPathNavigator MS.Internal.Xml.XPath.FilterQuery.MatchNode (XPathNavigator current) inline virtual
Reimplemented from MS.Internal.Xml.XPath.Query.
Definition at line 81 of file FilterQuery.cs.
    {
        if (current == null)
        {
            return null;
        }
        XPathNavigator xPathNavigator = qyInput.MatchNode(current);
        if (xPathNavigator != null)
        {
            switch (_cond.StaticType)
            {
            case XPathResultType.Number:
            {
                if (!(_cond is OperandQuery operandQuery))
                {
                    break;
                }
                double num = (double)operandQuery.val;
                if (qyInput is ChildrenQuery childrenQuery)
                {
                    XPathNavigator xPathNavigator2 = current.Clone();
                    xPathNavigator2.MoveToParent();
                    int num2 = 0;
                    xPathNavigator2.MoveToFirstChild();
                    do
                    {
                        if (!childrenQuery.matches(xPathNavigator2))
{
                            continue;
                        }
                        num2++;
                        if (current.IsSamePosition(xPathNavigator2))
{
                            if (num != (double)num2)
{
                                return null;
                            }
                            return xPathNavigator;
                        }
                    }
                    while (xPathNavigator2.MoveToNext());
                    return null;
                }
                if (!(qyInput is AttributeQuery attributeQuery))
                {
                    break;
                }
                XPathNavigator xPathNavigator3 = current.Clone();
                xPathNavigator3.MoveToParent();
                int num3 = 0;
                xPathNavigator3.MoveToFirstAttribute();
                do
                {
                    if (!attributeQuery.matches(xPathNavigator3))
                    {
                        continue;
                    }
                    num3++;
                    if (current.IsSamePosition(xPathNavigator3))
                    {
                        if (num != (double)num3)
{
                            return null;
                        }
                        return xPathNavigator;
                    }
                }
                while (xPathNavigator3.MoveToNextAttribute());
                return null;
            }
            case XPathResultType.NodeSet:
                _cond.Evaluate(new XPathSingletonIterator(current, moved: true));
                if (_cond.Advance() == null)
                {
                    return null;
                }
                return xPathNavigator;
            case XPathResultType.Boolean:
                if (_noPosition)
                {
                    if (!(bool)_cond.Evaluate(new XPathSingletonIterator(current, moved: true)))
                    {
                        return null;
                    }
                    return xPathNavigator;
                }
                break;
            case XPathResultType.String:
                if (_noPosition)
                {
                    if (((string)_cond.Evaluate(new XPathSingletonIterator(current, moved: true))).Length == 0)
                    {
                        return null;
                    }
                    return xPathNavigator;
                }
                break;
            case (XPathResultType)4:
                return xPathNavigator;
            default:
                return null;
            }
            Evaluate(new XPathSingletonIterator(xPathNavigator, moved: true));
            XPathNavigator xPathNavigator4;
            while ((xPathNavigator4 = Advance()) != null)
            {
                if (xPathNavigator4.IsSamePosition(current))
                {
                    return xPathNavigator;
                }
            }
        }
        return null;
    }
References MS.Internal.Xml.XPath.FilterQuery._cond, MS.Internal.Xml.XPath.FilterQuery._noPosition, MS.Internal.Xml.XPath.FilterQuery.Advance(), MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.BaseAxisQuery.Evaluate(), MS.Internal.Xml.XPath.Query.Evaluate(), System.Xml.XPath.XPathNavigator.IsSamePosition(), MS.Internal.Xml.XPath.Query.MatchNode(), System.Xml.XPath.XPathNavigator.MoveToFirstAttribute(), System.Xml.XPath.XPathNavigator.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToNextAttribute(), System.Xml.XPath.XPathNavigator.MoveToParent(), MS.Internal.Xml.XPath.BaseAxisQuery.qyInput, and MS.Internal.Xml.XPath.Query.StaticType.