Terraria: MS.Internal.Xml.XPath.FilterQuery.Advance
Advance()
override XPathNavigator MS.Internal.Xml.XPath.FilterQuery.Advance () inline
Definition at line 46 of file FilterQuery.cs.
    {
        while ((currentNode = qyInput.Advance()) != null)
        {
            if (EvaluatePredicate())
            {
                position++;
                return currentNode;
            }
        }
        return null;
    }
References MS.Internal.Xml.XPath.Query.Advance(), MS.Internal.Xml.XPath.BaseAxisQuery.currentNode, MS.Internal.Xml.XPath.FilterQuery.EvaluatePredicate(), MS.Internal.Xml.XPath.BaseAxisQuery.position, and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.
Referenced by MS.Internal.Xml.XPath.FilterQuery.MatchNode().