Terraria: MS.Internal.Xml.XPath.FilterQuery.EvaluatePredicate
EvaluatePredicate()
bool MS.Internal.Xml.XPath.FilterQuery.EvaluatePredicate () inline package
Definition at line 59 of file FilterQuery.cs.
    {
        object obj = _cond.Evaluate(qyInput);
        if (obj is XPathNodeIterator)
        {
            return _cond.Advance() != null;
        }
        if (obj is string)
        {
            return ((string)obj).Length != 0;
        }
        if (obj is double)
        {
            return (double)obj == (double)qyInput.CurrentPosition;
        }
        if (obj is bool)
        {
            return (bool)obj;
        }
        return true;
    }
References MS.Internal.Xml.XPath.FilterQuery._cond, MS.Internal.Xml.XPath.Query.Advance(), MS.Internal.Xml.XPath.ResetableIterator.CurrentPosition, MS.Internal.Xml.XPath.Query.Evaluate(), and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.
Referenced by MS.Internal.Xml.XPath.FilterQuery.Advance().