Terraria: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.OnCompleted
OnCompleted()
void System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted (Action< object?> continuation, object? state, short token, ValueTaskSourceOnCompletedFlags flags) inline
Definition at line 92 of file ManualResetValueTaskSourceCore.cs.
    {
        if (continuation == null)
        {
            throw new ArgumentNullException("continuation");
        }
        ValidateToken(token);
        if ((flags & ValueTaskSourceOnCompletedFlags.FlowExecutionContext) != 0)
        {
            _executionContext = ExecutionContext.Capture();
        }
        if ((flags & ValueTaskSourceOnCompletedFlags.UseSchedulingContext) != 0)
        {
            SynchronizationContext current = SynchronizationContext.Current;
            if (current != null && current.GetType() != typeof(SynchronizationContext))
            {
                _capturedContext = current;
            }
            else
            {
                TaskScheduler current2 = TaskScheduler.Current;
                if (current2 != TaskScheduler.Default)
                {
                    _capturedContext = current2;
                }
            }
        }
        object obj = _continuation;
        if (obj == null)
        {
            _continuationState = state;
            obj = Interlocked.CompareExchange(ref _continuation, continuation, null);
        }
        if (obj == null)
        {
            return;
        }
        if (obj != ManualResetValueTaskSourceCoreShared.s_sentinel)
        {
            ThrowHelper.ThrowInvalidOperationException();
        }
        object capturedContext = _capturedContext;
        if (capturedContext != null)
        {
            if (!(capturedContext is SynchronizationContext synchronizationContext))
            {
                if (capturedContext is TaskScheduler scheduler)
                {
                    Task.Factory.StartNew(continuation, state, CancellationToken.None, TaskCreationOptions.DenyChildAttach, scheduler);
                }
            }
            else
            {
                synchronizationContext.Post(delegate(object s)
                {
                    TupleSlim<Action<object>, object> tupleSlim = (TupleSlim<Action<object>, object>)s;
                    tupleSlim.Item1(tupleSlim.Item2);
                }, new TupleSlim<Action<object>, object>(continuation, state));
            }
        }
        else if (_executionContext != null)
        {
            ThreadPool.QueueUserWorkItem<object>(continuation, state, preferLocal: true);
        }
        else
        {
            ThreadPool.UnsafeQueueUserWorkItem<object>(continuation, state, preferLocal: true);
        }
    }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._capturedContext, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuation, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuationState, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._executionContext, System.Threading.ExecutionContext.Capture(), System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.TaskScheduler.Current, System.Threading.SynchronizationContext.Current, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.TupleSlim< T1, T2, T3, T4 >.Item1, System.TupleSlim< T1, T2, T3, T4 >.Item2, System.Threading.CancellationToken.None, System.obj, System.Threading.ThreadPool.QueueUserWorkItem(), System.s, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.s_sentinel, System.scheduler, System.state, System.ThrowHelper.ThrowInvalidOperationException(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.ValidateToken().
Referenced by System.IO.Pipes.PipeStream.PipeValueTaskSource.OnCompleted(), System.Net.Http.CreditWaiter.OnCompleted(), System.Net.Http.Http2Connection.Http2Stream.OnCompleted(), System.IO.StreamBuffer.ResettableValueTaskSource.OnCompleted(), System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource< T >.OnCompleted(), System.Net.Sockets.SocketAsyncEventArgs.MultiConnectSocketAsyncEventArgs.OnCompleted(), Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.OnCompleted(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.OnCompleted(), and System.Threading.PeriodicTimer.State.OnCompleted().