Terraria: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.InvokeContinuationWithContext
InvokeContinuationWithContext()
void System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeContinuationWithContext () inline private
Definition at line 205 of file ManualResetValueTaskSourceCore.cs.
    {
        ExecutionContext executionContext = ExecutionContext.CaptureForRestore();
        ExecutionContext.Restore(_executionContext);
        if (_capturedContext == null)
        {
            if (RunContinuationsAsynchronously)
            {
                try
                {
                    ThreadPool.QueueUserWorkItem(_continuation, _continuationState, preferLocal: true);
                    return;
                }
                finally
                {
                    ExecutionContext.RestoreInternal(executionContext);
                }
            }
            ExceptionDispatchInfo exceptionDispatchInfo = null;
            SynchronizationContext current = SynchronizationContext.Current;
            try
            {
                _continuation(_continuationState);
            }
            catch (Exception source)
            {
                exceptionDispatchInfo = ExceptionDispatchInfo.Capture(source);
            }
            finally
            {
                SynchronizationContext.SetSynchronizationContext(current);
                ExecutionContext.RestoreInternal(executionContext);
            }
            exceptionDispatchInfo?.Throw();
            return;
        }
        try
        {
            InvokeSchedulerContinuation();
        }
        finally
        {
            ExecutionContext.RestoreInternal(executionContext);
        }
    }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._capturedContext, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuation, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuationState, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._executionContext, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Threading.ExecutionContext.CaptureForRestore(), System.Threading.SynchronizationContext.Current, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeSchedulerContinuation(), System.Threading.ThreadPool.QueueUserWorkItem(), System.Threading.ExecutionContext.Restore(), System.Threading.ExecutionContext.RestoreInternal(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.RunContinuationsAsynchronously, System.Threading.SynchronizationContext.SetSynchronizationContext(), System.source, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SignalCompletion().