Terraria: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.SetResult
SetResult()
void System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult (TResult result) inline
Definition at line 42 of file ManualResetValueTaskSourceCore.cs.
    {
        _result = result;
        SignalCompletion();
    }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._result, and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SignalCompletion().
Referenced by System.Net.Http.Http2Connection.Http2Stream.Cancel(), System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource< T >.Complete(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.Complete(), System.IO.Pipes.PipeStream.ReadWriteValueTaskSource.CompleteCore(), System.IO.Pipes.PipeStream.ConnectionValueTaskSource.CompleteCore(), Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal(), System.Net.Sockets.SocketAsyncEventArgs.MultiConnectSocketAsyncEventArgs.OnCompleted(), System.Net.Http.Http2Connection.Http2Stream.OnHeadersComplete(), System.Net.Http.Http2Connection.Http2Stream.OnResponseData(), System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(), System.Threading.PeriodicTimer.State.Signal(), System.IO.StreamBuffer.ResettableValueTaskSource.SignalWaiter(), and System.Net.Http.CreditWaiter.TrySetResult().