Terraria: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.Reset
Reset()
void System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Reset () inline
Definition at line 30 of file ManualResetValueTaskSourceCore.cs.
    {
        _version++;
        _completed = false;
        _result = default(TResult);
        _error = null;
        _executionContext = null;
        _capturedContext = null;
        _continuation = null;
        _continuationState = null;
    }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._capturedContext, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._completed, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuation, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuationState, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._error, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._executionContext, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._result, and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._version.
Referenced by System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource< T >.GetResult(), Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(), System.Threading.PeriodicTimer.State.GetResult(), System.IO.StreamBuffer.ResettableValueTaskSource.Reset(), System.Net.Sockets.SocketAsyncEventArgs.MultiConnectSocketAsyncEventArgs.Reset(), System.Net.Http.CreditWaiter.ResetForAwait(), System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders(), and System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer().