Terraria: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.GetStatus
GetStatus()
ValueTaskSourceStatus System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.GetStatus (short token) inline
Definition at line 54 of file ManualResetValueTaskSourceCore.cs.
    {
        ValidateToken(token);
        if (_continuation != null && _completed)
        {
            if (_error != null)
            {
                if (!(_error.SourceException is OperationCanceledException))
                {
                    return ValueTaskSourceStatus.Faulted;
                }
                return ValueTaskSourceStatus.Canceled;
            }
            return ValueTaskSourceStatus.Succeeded;
        }
        return ValueTaskSourceStatus.Pending;
    }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._completed, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuation, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._error, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SourceException, and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.ValidateToken().
Referenced by System.IO.Pipes.PipeStream.PipeValueTaskSource.GetStatus(), System.Net.Http.CreditWaiter.GetStatus(), System.Net.Http.Http2Connection.Http2Stream.GetStatus(), System.IO.StreamBuffer.ResettableValueTaskSource.GetStatus(), System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource< T >.GetStatus(), System.Net.Sockets.SocketAsyncEventArgs.MultiConnectSocketAsyncEventArgs.GetStatus(), Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetStatus(), Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.GetStatus(), and System.Threading.PeriodicTimer.State.GetStatus().