Terraria: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.ValidateToken
ValidateToken()
void System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.ValidateToken (short token) inline private
Definition at line 162 of file ManualResetValueTaskSourceCore.cs.
    {
        if (token != _version)
        {
            ThrowHelper.ThrowInvalidOperationException();
        }
    }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._version, and System.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.GetStatus(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted().