Terraria: System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore.SignalCompletion
SignalCompletion()
void System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SignalCompletion () inline private
Definition at line 170 of file ManualResetValueTaskSourceCore.cs.
    {
        if (_completed)
        {
            ThrowHelper.ThrowInvalidOperationException();
        }
        _completed = true;
        if (_continuation == null && Interlocked.CompareExchange(ref _continuation, ManualResetValueTaskSourceCoreShared.s_sentinel, null) == null)
        {
            return;
        }
        if (_executionContext == null)
        {
            if (_capturedContext == null)
            {
                if (RunContinuationsAsynchronously)
                {
                    ThreadPool.UnsafeQueueUserWorkItem(_continuation, _continuationState, preferLocal: true);
                }
                else
                {
                    _continuation(_continuationState);
                }
            }
            else
            {
                InvokeSchedulerContinuation();
            }
        }
        else
        {
            InvokeContinuationWithContext();
        }
    }
References System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._capturedContext, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._completed, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuation, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._continuationState, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >._executionContext, System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeContinuationWithContext(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeSchedulerContinuation(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.RunContinuationsAsynchronously, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCoreShared.s_sentinel, System.ThrowHelper.ThrowInvalidOperationException(), and System.Threading.ThreadPool.UnsafeQueueUserWorkItem().
Referenced by System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetException(), and System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult().