Terraria: System.Security.Principal.SecurityIdentifier.CreateFromParts
CreateFromParts()
void System.Security.Principal.SecurityIdentifier.CreateFromParts (IdentifierAuthority identifierAuthority, ReadOnlySpan< int > subAuthorities) inline private
Definition at line 53 of file SecurityIdentifier.cs.
    {
        if (subAuthorities.Length > 15)
        {
            throw new ArgumentOutOfRangeException("subAuthorities.Length", subAuthorities.Length, System.SR.Format(System.SR.IdentityReference_InvalidNumberOfSubauthorities, 15));
        }
        if (identifierAuthority < IdentifierAuthority.NullAuthority || identifierAuthority > (IdentifierAuthority)281474976710655L)
        {
            throw new ArgumentOutOfRangeException("identifierAuthority", identifierAuthority, System.SR.IdentityReference_IdentifierAuthorityTooLarge);
        }
        _identifierAuthority = identifierAuthority;
        _subAuthorities = subAuthorities.ToArray();
        _binaryForm = new byte[8 + 4 * _subAuthorities.Length];
        _binaryForm[0] = Revision;
        _binaryForm[1] = (byte)_subAuthorities.Length;
        for (int i = 0; i < 6; i++)
        {
            _binaryForm[2 + i] = (byte)(((ulong)_identifierAuthority >> (5 - i) * 8) & 0xFF);
        }
        for (int j = 0; j < _subAuthorities.Length; j++)
        {
            for (byte b = 0; b < 4; b++)
            {
                _binaryForm[8 + 4 * j + b] = (byte)((ulong)_subAuthorities[j] >> b * 8);
            }
        }
    }
References System.Security.Principal.SecurityIdentifier._binaryForm, System.Security.Principal.SecurityIdentifier._identifierAuthority, System.Security.Principal.SecurityIdentifier._subAuthorities, System.SR.Format(), System.SR.IdentityReference_IdentifierAuthorityTooLarge, System.SR.IdentityReference_InvalidNumberOfSubauthorities, System.L, System.ReadOnlySpan< T >.Length, System.Security.Principal.SecurityIdentifier.Revision, and System.ReadOnlySpan< T >.ToArray().
Referenced by System.Security.Principal.SecurityIdentifier.SecurityIdentifier(), and System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm().