Terraria: System.Security.Principal.SecurityIdentifier.SecurityIdentifier
SecurityIdentifier() [1/5]
System.Security.Principal.SecurityIdentifier.SecurityIdentifier (string sddlForm) inline
Definition at line 120 of file SecurityIdentifier.cs.
    {
        if (sddlForm == null)
        {
            throw new ArgumentNullException("sddlForm");
        }
        byte[] resultSid;
        int num = Win32.CreateSidFromString(sddlForm, out resultSid);
        switch (num)
        {
        case 1337:
            throw new ArgumentException(System.SR.Argument_InvalidValue, "sddlForm");
        case 8:
            throw new OutOfMemoryException();
        default:
            throw new Win32Exception(num);
        case 0:
            CreateFromBinaryForm(resultSid, 0);
            break;
        }
    }
References System.SR.Argument_InvalidValue, System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm(), and System.Security.Principal.Win32.CreateSidFromString().
Referenced by System.Security.Principal.SecurityIdentifier.Equals().