Terraria: System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts
TranslateToNTAccounts()
static IdentityReferenceCollection System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts (IdentityReferenceCollection sourceSids, out bool someFailed) inline static private
Definition at line 485 of file SecurityIdentifier.cs.
    {
        if (sourceSids == null)
        {
            throw new ArgumentNullException("sourceSids");
        }
        if (sourceSids.Count == 0)
        {
            throw new ArgumentException(System.SR.Arg_EmptyCollection, "sourceSids");
        }
        IntPtr[] array = new IntPtr[sourceSids.Count];
        GCHandle[] array2 = new GCHandle[sourceSids.Count];
        SafeLsaPolicyHandle safeLsaPolicyHandle = null;
        SafeLsaMemoryHandle referencedDomains = null;
        SafeLsaMemoryHandle names = null;
        try
        {
            int num = 0;
            foreach (IdentityReference sourceSid in sourceSids)
            {
                if (!(sourceSid is SecurityIdentifier securityIdentifier))
                {
                    throw new ArgumentException(System.SR.Argument_ImproperType, "sourceSids");
                }
                array2[num] = GCHandle.Alloc(securityIdentifier.BinaryForm, GCHandleType.Pinned);
                array[num] = array2[num].AddrOfPinnedObject();
                num++;
            }
            safeLsaPolicyHandle = Win32.LsaOpenPolicy(null, PolicyRights.POLICY_LOOKUP_NAMES);
            someFailed = false;
            uint num2 = global::Interop.Advapi32.LsaLookupSids(safeLsaPolicyHandle, sourceSids.Count, array, out referencedDomains, out names);
            switch (num2)
            {
            case 3221225495u:
            case 3221225626u:
                throw new OutOfMemoryException();
            case 3221225506u:
                throw new UnauthorizedAccessException();
            case 3221225587u:
            case 263u:
                someFailed = true;
                break;
            default:
            {
                uint error = global::Interop.Advapi32.LsaNtStatusToWinError(num2);
                throw new Win32Exception((int)error);
            }
            case 0u:
                break;
            }
            names.Initialize((uint)sourceSids.Count, (uint)Marshal.SizeOf<global::Interop.LSA_TRANSLATED_NAME>());
            Win32.InitializeReferencedDomainsPointer(referencedDomains);
            IdentityReferenceCollection identityReferenceCollection = new IdentityReferenceCollection(sourceSids.Count);
            if (num2 == 0 || num2 == 263)
            {
                global::Interop.LSA_REFERENCED_DOMAIN_LIST lSA_REFERENCED_DOMAIN_LIST = referencedDomains.Read<global::Interop.LSA_REFERENCED_DOMAIN_LIST>(0uL);
                string[] array3 = new string[lSA_REFERENCED_DOMAIN_LIST.Entries];
                for (int i = 0; i < lSA_REFERENCED_DOMAIN_LIST.Entries; i++)
                {
                    global::Interop.LSA_TRUST_INFORMATION lSA_TRUST_INFORMATION = Marshal.PtrToStructure<global::Interop.LSA_TRUST_INFORMATION>(new IntPtr((long)lSA_REFERENCED_DOMAIN_LIST.Domains + i * Marshal.SizeOf<global::Interop.LSA_TRUST_INFORMATION>()));
                    array3[i] = Marshal.PtrToStringUni(lSA_TRUST_INFORMATION.Name.Buffer, lSA_TRUST_INFORMATION.Name.Length / 2);
                }
                global::Interop.LSA_TRANSLATED_NAME[] array4 = new global::Interop.LSA_TRANSLATED_NAME[sourceSids.Count];
                names.ReadArray(0uL, array4, 0, array4.Length);
                for (int j = 0; j < sourceSids.Count; j++)
                {
                    global::Interop.LSA_TRANSLATED_NAME lSA_TRANSLATED_NAME = array4[j];
                    switch ((SidNameUse)lSA_TRANSLATED_NAME.Use)
                    {
                    case SidNameUse.User:
                    case SidNameUse.Group:
                    case SidNameUse.Alias:
                    case SidNameUse.WellKnownGroup:
                    case SidNameUse.Computer:
                    {
                        string accountName = Marshal.PtrToStringUni(lSA_TRANSLATED_NAME.Name.Buffer, lSA_TRANSLATED_NAME.Name.Length / 2);
                        string domainName = array3[lSA_TRANSLATED_NAME.DomainIndex];
                        identityReferenceCollection.Add(new NTAccount(domainName, accountName));
                        break;
                    }
                    default:
                        someFailed = true;
                        identityReferenceCollection.Add(sourceSids[j]);
                        break;
                    }
                }
            }
            else
            {
                for (int k = 0; k < sourceSids.Count; k++)
                {
                    identityReferenceCollection.Add(sourceSids[k]);
                }
            }
            return identityReferenceCollection;
        }
        finally
        {
            for (int l = 0; l < sourceSids.Count; l++)
            {
                if (array2[l].IsAllocated)
                {
                    array2[l].Free();
                }
            }
            safeLsaPolicyHandle?.Dispose();
            referencedDomains?.Dispose();
            names?.Dispose();
        }
    }
References System.Security.Principal.IdentityReferenceCollection.Add(), System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject(), System.Runtime.InteropServices.GCHandle.Alloc(), System.SR.Arg_EmptyCollection, System.SR.Argument_ImproperType, System.array, System.Security.Principal.IdentityReferenceCollection.Count, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Runtime.InteropServices.GCHandle.Free(), System.Security.Principal.Win32.InitializeReferencedDomainsPointer(), System.Security.Principal.Win32.LsaOpenPolicy(), System.Runtime.InteropServices.Marshal.PtrToStringUni(), System.Runtime.InteropServices.Marshal.PtrToStructure(), and System.Runtime.InteropServices.Marshal.SizeOf().
Referenced by System.Security.Principal.SecurityIdentifier.Translate().