Terraria: System.Security.Principal.SecurityIdentifier.SecurityIdentifier
SecurityIdentifier() [4/5]
System.Security.Principal.SecurityIdentifier.SecurityIdentifier (WellKnownSidType sidType, SecurityIdentifier? domainSid) inline
Definition at line 156 of file SecurityIdentifier.cs.
    {
        int windowsAccountDomainSid;
        switch (sidType)
        {
        case WellKnownSidType.LogonIdsSid:
            throw new ArgumentException(System.SR.IdentityReference_CannotCreateLogonIdsSid, "sidType");
        default:
            throw new ArgumentException(System.SR.Argument_InvalidValue, "sidType");
        case WellKnownSidType.AccountAdministratorSid:
        case WellKnownSidType.AccountGuestSid:
        case WellKnownSidType.AccountKrbtgtSid:
        case WellKnownSidType.AccountDomainAdminsSid:
        case WellKnownSidType.AccountDomainUsersSid:
        case WellKnownSidType.AccountDomainGuestsSid:
        case WellKnownSidType.AccountComputersSid:
        case WellKnownSidType.AccountControllersSid:
        case WellKnownSidType.AccountCertAdminsSid:
        case WellKnownSidType.AccountSchemaAdminsSid:
        case WellKnownSidType.AccountEnterpriseAdminsSid:
        case WellKnownSidType.AccountPolicyAdminsSid:
        case WellKnownSidType.AccountRasAndIasServersSid:
        {
            if (domainSid == null)
            {
                throw new ArgumentNullException("domainSid", System.SR.Format(System.SR.IdentityReference_DomainSidRequired, sidType));
            }
            windowsAccountDomainSid = Win32.GetWindowsAccountDomainSid(domainSid, out var resultSid);
            switch (windowsAccountDomainSid)
            {
            case 122:
                throw new OutOfMemoryException();
            case 1257:
                throw new ArgumentException(System.SR.IdentityReference_NotAWindowsDomain, "domainSid");
            default:
                throw new Win32Exception(windowsAccountDomainSid);
            case 0:
                break;
            }
            if (resultSid != domainSid)
            {
                throw new ArgumentException(System.SR.IdentityReference_NotAWindowsDomain, "domainSid");
            }
            break;
        }
        case WellKnownSidType.NullSid:
        case WellKnownSidType.WorldSid:
        case WellKnownSidType.LocalSid:
        case WellKnownSidType.CreatorOwnerSid:
        case WellKnownSidType.CreatorGroupSid:
        case WellKnownSidType.CreatorOwnerServerSid:
        case WellKnownSidType.CreatorGroupServerSid:
        case WellKnownSidType.NTAuthoritySid:
        case WellKnownSidType.DialupSid:
        case WellKnownSidType.NetworkSid:
        case WellKnownSidType.BatchSid:
        case WellKnownSidType.InteractiveSid:
        case WellKnownSidType.ServiceSid:
        case WellKnownSidType.AnonymousSid:
        case WellKnownSidType.ProxySid:
        case WellKnownSidType.EnterpriseControllersSid:
        case WellKnownSidType.SelfSid:
        case WellKnownSidType.AuthenticatedUserSid:
        case WellKnownSidType.RestrictedCodeSid:
        case WellKnownSidType.TerminalServerSid:
        case WellKnownSidType.RemoteLogonIdSid:
        case WellKnownSidType.LocalSystemSid:
        case WellKnownSidType.LocalServiceSid:
        case WellKnownSidType.NetworkServiceSid:
        case WellKnownSidType.BuiltinDomainSid:
        case WellKnownSidType.BuiltinAdministratorsSid:
        case WellKnownSidType.BuiltinUsersSid:
        case WellKnownSidType.BuiltinGuestsSid:
        case WellKnownSidType.BuiltinPowerUsersSid:
        case WellKnownSidType.BuiltinAccountOperatorsSid:
        case WellKnownSidType.BuiltinSystemOperatorsSid:
        case WellKnownSidType.BuiltinPrintOperatorsSid:
        case WellKnownSidType.BuiltinBackupOperatorsSid:
        case WellKnownSidType.BuiltinReplicatorSid:
        case WellKnownSidType.BuiltinPreWindows2000CompatibleAccessSid:
        case WellKnownSidType.BuiltinRemoteDesktopUsersSid:
        case WellKnownSidType.BuiltinNetworkConfigurationOperatorsSid:
        case WellKnownSidType.NtlmAuthenticationSid:
        case WellKnownSidType.DigestAuthenticationSid:
        case WellKnownSidType.SChannelAuthenticationSid:
        case WellKnownSidType.ThisOrganizationSid:
        case WellKnownSidType.OtherOrganizationSid:
        case WellKnownSidType.BuiltinIncomingForestTrustBuildersSid:
        case WellKnownSidType.BuiltinPerformanceMonitoringUsersSid:
        case WellKnownSidType.BuiltinPerformanceLoggingUsersSid:
        case WellKnownSidType.BuiltinAuthorizationAccessSid:
        case WellKnownSidType.WinBuiltinTerminalServerLicenseServersSid:
        case WellKnownSidType.WinBuiltinDCOMUsersSid:
        case WellKnownSidType.WinBuiltinIUsersSid:
        case WellKnownSidType.WinIUserSid:
        case WellKnownSidType.WinBuiltinCryptoOperatorsSid:
        case WellKnownSidType.WinUntrustedLabelSid:
        case WellKnownSidType.WinLowLabelSid:
        case WellKnownSidType.WinMediumLabelSid:
        case WellKnownSidType.WinHighLabelSid:
        case WellKnownSidType.WinSystemLabelSid:
        case WellKnownSidType.WinWriteRestrictedCodeSid:
        case WellKnownSidType.WinCreatorOwnerRightsSid:
        case WellKnownSidType.WinCacheablePrincipalsGroupSid:
        case WellKnownSidType.WinNonCacheablePrincipalsGroupSid:
        case WellKnownSidType.WinEnterpriseReadonlyControllersSid:
        case WellKnownSidType.WinAccountReadonlyControllersSid:
        case WellKnownSidType.WinBuiltinEventLogReadersGroup:
        case WellKnownSidType.WinNewEnterpriseReadonlyControllersSid:
        case WellKnownSidType.WinBuiltinCertSvcDComAccessGroup:
        case WellKnownSidType.WinMediumPlusLabelSid:
        case WellKnownSidType.WinLocalLogonSid:
        case WellKnownSidType.WinConsoleLogonSid:
        case WellKnownSidType.WinThisOrganizationCertificateSid:
        case WellKnownSidType.WinApplicationPackageAuthoritySid:
        case WellKnownSidType.WinBuiltinAnyPackageSid:
        case WellKnownSidType.WinCapabilityInternetClientSid:
        case WellKnownSidType.WinCapabilityInternetClientServerSid:
        case WellKnownSidType.WinCapabilityPrivateNetworkClientServerSid:
        case WellKnownSidType.WinCapabilityPicturesLibrarySid:
        case WellKnownSidType.WinCapabilityVideosLibrarySid:
        case WellKnownSidType.WinCapabilityMusicLibrarySid:
        case WellKnownSidType.WinCapabilityDocumentsLibrarySid:
        case WellKnownSidType.WinCapabilitySharedUserCertificatesSid:
        case WellKnownSidType.WinCapabilityEnterpriseAuthenticationSid:
        case WellKnownSidType.WinCapabilityRemovableStorageSid:
            break;
        }
        windowsAccountDomainSid = Win32.CreateWellKnownSid(sidType, domainSid, out var resultSid2);
        switch (windowsAccountDomainSid)
        {
        case 87:
            throw new ArgumentException(new Win32Exception(windowsAccountDomainSid).Message, "sidType/domainSid");
        default:
            throw new Win32Exception(windowsAccountDomainSid);
        case 0:
            CreateFromBinaryForm(resultSid2, 0);
            break;
        }
    }
References System.SR.Argument_InvalidValue, System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm(), System.Security.Principal.Win32.CreateWellKnownSid(), System.SR.Format(), System.Security.Principal.Win32.GetWindowsAccountDomainSid(), System.SR.IdentityReference_CannotCreateLogonIdsSid, System.SR.IdentityReference_DomainSidRequired, and System.SR.IdentityReference_NotAWindowsDomain.