Terraria: Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.Update
Update()
override void Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.Update (int frameCount) inline inherited
Definition at line 120 of file AmbientSky.cs.
        {
            if (!IsMovementDone(frameCount))
            {
                UpdateOpacity(frameCount);
                if ((frameCount + FrameOffset) % FramingSpeed == 0)
                {
                    NextFrame();
                }
                UpdateVelocity(frameCount);
                Position += Velocity;
            }
        }
References Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FrameOffset, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FramingSpeed, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.IsMovementDone(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.NextFrame(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.UpdateOpacity(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.UpdateVelocity(), and Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.Velocity.