Terraria: Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.StartFadingOut
StartFadingOut()
void Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.StartFadingOut (int currentFrameCount) inline inherited
Definition at line 170 of file AmbientSky.cs.
        {
            int num = (int)((float)LifeTime * OpacityNormalizedTimeToFadeOut);
            int num2 = currentFrameCount - num;
            if (num2 < TimeEntitySpawnedIn)
            {
                TimeEntitySpawnedIn = num2;
            }
        }
References Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.LifeTime, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, and Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.TimeEntitySpawnedIn.
Referenced by Terraria.GameContent.Skies.AmbientSky.ButterfliesSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.LostKiteSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.PegasusSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.VultureSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.PixiePosseSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.BirdsPackSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.Update(), Terraria.GameContent.Skies.AmbientSky.AirshipSkyEntity.Update(), and Terraria.GameContent.Skies.AmbientSky.AirBalloonSkyEntity.Update().