Terraria: System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm
CreateFromBinaryForm()
void System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm (byte[] binaryForm, int offset) inline private
Definition at line 83 of file SecurityIdentifier.cs.
    {
        if (binaryForm == null)
        {
            throw new ArgumentNullException("binaryForm");
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset", offset, System.SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (binaryForm.Length - offset < MinBinaryLength)
        {
            throw new ArgumentOutOfRangeException("binaryForm", System.SR.ArgumentOutOfRange_ArrayTooSmall);
        }
        if (binaryForm[offset] != Revision)
        {
            throw new ArgumentException(System.SR.IdentityReference_InvalidSidRevision, "binaryForm");
        }
        int num = binaryForm[offset + 1];
        if (num > 15)
        {
            throw new ArgumentException(System.SR.Format(System.SR.IdentityReference_InvalidNumberOfSubauthorities, 15), "binaryForm");
        }
        int num2 = 8 + 4 * num;
        if (binaryForm.Length - offset < num2)
        {
            throw new ArgumentException(System.SR.ArgumentOutOfRange_ArrayTooSmall, "binaryForm");
        }
        Span<int> span = stackalloc int[15];
        IdentifierAuthority identifierAuthority = (IdentifierAuthority)(((ulong)binaryForm[offset + 2] << 40) + ((ulong)binaryForm[offset + 3] << 32) + ((ulong)binaryForm[offset + 4] << 24) + ((ulong)binaryForm[offset + 5] << 16) + ((ulong)binaryForm[offset + 6] << 8) + binaryForm[offset + 7]);
        for (int i = 0; i < num; i++)
        {
            span[i] = binaryForm[offset + 8 + 4 * i] + (binaryForm[offset + 8 + 4 * i + 1] << 8) + (binaryForm[offset + 8 + 4 * i + 2] << 16) + (binaryForm[offset + 8 + 4 * i + 3] << 24);
        }
        CreateFromParts(identifierAuthority, span.Slice(0, num));
    }
References System.SR.ArgumentOutOfRange_ArrayTooSmall, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.Security.Principal.SecurityIdentifier.CreateFromParts(), System.SR.Format(), System.Security.Principal.SecurityIdentifier.IdentifierAuthority, System.SR.IdentityReference_InvalidNumberOfSubauthorities, System.SR.IdentityReference_InvalidSidRevision, System.Security.Principal.SecurityIdentifier.MinBinaryLength, System.offset, System.Security.Principal.SecurityIdentifier.Revision, and System.Span< T >.Slice().
Referenced by System.Security.Principal.SecurityIdentifier.SecurityIdentifier(), System.Security.Principal.SecurityIdentifier.SecurityIdentifier(), and System.Security.Principal.SecurityIdentifier.SecurityIdentifier().