Terraria: WorldFile.LoadWorldTiles
LoadWorldTiles()
static void WorldFile.LoadWorldTiles (BinaryReader reader, bool[] importance) inline static
     {
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             float num = (float)i / (float)Main.maxTilesX;
             Main.statusText = Lang.gen[51].Value + " " + (int)((double)num * 100.0 + 1.0) + "%";
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 int num2 = -1;
                 byte b2;
                 byte b;
                 byte b3 = (b2 = (b = 0));
                 Tile tile = Main.tile[i, j];
                 byte b4 = reader.ReadByte();
                 bool flag = false;
                 if ((b4 & 1) == 1)
                 {
                     flag = true;
                     b3 = reader.ReadByte();
                 }
                 bool flag2 = false;
                 if (flag && (b3 & 1) == 1)
                 {
                     flag2 = true;
                     b2 = reader.ReadByte();
                 }
                 if (flag2 && (b2 & 1) == 1)
                 {
                     b = reader.ReadByte();
                 }
                 byte b5;
                 if ((b4 & 2) == 2)
                 {
                     tile.active(active: true);
                     if ((b4 & 0x20) == 32)
                     {
                         b5 = reader.ReadByte();
                         num2 = reader.ReadByte();
                         num2 = (num2 << 8) | b5;
                     }
                     else
                     {
                         num2 = reader.ReadByte();
                     }
                     tile.type = (ushort)num2;
                     if (importance[num2])
                     {
                         tile.frameX = reader.ReadInt16();
                         tile.frameY = reader.ReadInt16();
                         if (tile.type == 144)
{
                             tile.frameY = 0;
                         }
                     }
                     else
                     {
                         tile.frameX = -1;
                         tile.frameY = -1;
                     }
                     if ((b2 & 8) == 8)
                     {
                         tile.color(reader.ReadByte());
                     }
                 }
                 if ((b4 & 4) == 4)
                 {
                     tile.wall = reader.ReadByte();
                     if (tile.wall >= WallID.Count)
                     {
                         tile.wall = 0;
                     }
                     if ((b2 & 0x10) == 16)
                     {
                         tile.wallColor(reader.ReadByte());
                     }
                 }
                 b5 = (byte)((b4 & 0x18) >> 3);
                 if (b5 != 0)
                 {
                     tile.liquid = reader.ReadByte();
                     if ((b2 & 0x80) == 128)
                     {
                         tile.shimmer(shimmer: true);
                     }
                     else if (b5 > 1)
                     {
                         if (b5 == 2)
{
                             tile.lava(lava: true);
                         }
                         else
{
                             tile.honey(honey: true);
                         }
                     }
                 }
                 if (b3 > 1)
                 {
                     if ((b3 & 2) == 2)
                     {
                         tile.wire(wire: true);
                     }
                     if ((b3 & 4) == 4)
                     {
                         tile.wire2(wire2: true);
                     }
                     if ((b3 & 8) == 8)
                     {
                         tile.wire3(wire3: true);
                     }
                     b5 = (byte)((b3 & 0x70) >> 4);
                     if (b5 != 0 && (Main.tileSolid[tile.type] || TileID.Sets.NonSolidSaveSlopes[tile.type]))
                     {
                         if (b5 == 1)
{
                             tile.halfBrick(halfBrick: true);
                         }
                         else
{
                             tile.slope((byte)(b5 - 1));
                         }
                     }
                 }
                 if (b2 > 1)
                 {
                     if ((b2 & 2) == 2)
                     {
                         tile.actuator(actuator: true);
                     }
                     if ((b2 & 4) == 4)
                     {
                         tile.inActive(inActive: true);
                     }
                     if ((b2 & 0x20) == 32)
                     {
                         tile.wire4(wire4: true);
                     }
                     if ((b2 & 0x40) == 64)
                     {
                         b5 = reader.ReadByte();
                         tile.wall = (ushort)((b5 << 8) | tile.wall);
                         if (tile.wall >= WallID.Count)
{
                             tile.wall = 0;
                         }
                     }
                 }
                 if (b > 1)
                 {
                     if ((b & 2) == 2)
                     {
                         tile.invisibleBlock(invisibleBlock: true);
                     }
                     if ((b & 4) == 4)
                     {
                         tile.invisibleWall(invisibleWall: true);
                     }
                     if ((b & 8) == 8)
                     {
                         tile.fullbrightBlock(fullbrightBlock: true);
                     }
                     if ((b & 0x10) == 16)
                     {
                         tile.fullbrightWall(fullbrightWall: true);
                     }
                 }
                 int num3 = (byte)((b4 & 0xC0) >> 6) switch
                 {
                     0 => 0,
                     1 => reader.ReadByte(),
                     _ => reader.ReadInt16(),
                 };
                 if (num2 != -1)
                 {
                     if ((double)j <= Main.worldSurface)
                     {
                         if ((double)(j + num3) <= Main.worldSurface)
{
                             WorldGen.tileCounts[num2] += (num3 + 1) * 5;
                         }
                         else
{
                             int num4 = (int)(Main.worldSurface - (double)j + 1.0);
                             int num5 = num3 + 1 - num4;
                             WorldGen.tileCounts[num2] += num4 * 5 + num5;
                         }
                     }
                     else
                     {
                         WorldGen.tileCounts[num2] += num3 + 1;
                     }
                 }
                 while (num3 > 0)
                 {
                     j++;
                     Main.tile[i, j].CopyFrom(tile);
                     num3--;
                 }
             }
         }
         WorldGen.AddUpAlignmentCounts(clearCounts: true);
         if (_versionNumber < 105)
         {
             WorldGen.FixHearts();
         }
     }
References _versionNumber, Tile.active(), Tile.actuator(), WorldGen.AddUpAlignmentCounts(), Tile.color(), Tile.CopyFrom(), WallID.Count, WorldGen.FixHearts(), Tile.frameX, Tile.frameY, Tile.fullbrightBlock(), Tile.fullbrightWall(), Lang.gen, Tile.halfBrick(), Tile.honey(), Tile.inActive(), Tile.invisibleBlock(), Tile.invisibleWall(), Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, TileID.Sets.NonSolidSaveSlopes, Tile.shimmer(), Tile.slope(), Main.statusText, Main.tile, WorldGen.tileCounts, Main.tileSolid, Tile.type, LocalizedText.Value, Tile.wall, Tile.wallColor(), Tile.wire(), Tile.wire2(), Tile.wire3(), Tile.wire4(), and Main.worldSurface.
Referenced by LoadWorld_Version2().