Terraria: WorldFile.LoadWorld_Version1_Old_BeforeRelease88
LoadWorld_Version1_Old_BeforeRelease88()
static int WorldFile.LoadWorld_Version1_Old_BeforeRelease88 (BinaryReader fileIO) inline static private
     {
         Main.WorldFileMetadata = FileMetadata.FromCurrentSettings(FileType.World);
         int versionNumber = _versionNumber;
         if (versionNumber > 279)
         {
             return 1;
         }
         Main.worldName = fileIO.ReadString();
         Main.worldID = fileIO.ReadInt32();
         Main.leftWorld = fileIO.ReadInt32();
         Main.rightWorld = fileIO.ReadInt32();
         Main.topWorld = fileIO.ReadInt32();
         Main.bottomWorld = fileIO.ReadInt32();
         Main.maxTilesY = fileIO.ReadInt32();
         Main.maxTilesX = fileIO.ReadInt32();
         if (versionNumber >= 112)
         {
             Main.GameMode = (fileIO.ReadBoolean() ? 1 : 0);
         }
         else
         {
             Main.GameMode = 0;
         }
         if (versionNumber >= 63)
         {
             Main.moonType = fileIO.ReadByte();
         }
         else
         {
             WorldGen.RandomizeMoonState(WorldGen.genRand);
         }
         WorldGen.clearWorld();
         if (versionNumber >= 44)
         {
             Main.treeX[0] = fileIO.ReadInt32();
             Main.treeX[1] = fileIO.ReadInt32();
             Main.treeX[2] = fileIO.ReadInt32();
             Main.treeStyle[0] = fileIO.ReadInt32();
             Main.treeStyle[1] = fileIO.ReadInt32();
             Main.treeStyle[2] = fileIO.ReadInt32();
             Main.treeStyle[3] = fileIO.ReadInt32();
         }
         if (versionNumber >= 60)
         {
             Main.caveBackX[0] = fileIO.ReadInt32();
             Main.caveBackX[1] = fileIO.ReadInt32();
             Main.caveBackX[2] = fileIO.ReadInt32();
             Main.caveBackStyle[0] = fileIO.ReadInt32();
             Main.caveBackStyle[1] = fileIO.ReadInt32();
             Main.caveBackStyle[2] = fileIO.ReadInt32();
             Main.caveBackStyle[3] = fileIO.ReadInt32();
             Main.iceBackStyle = fileIO.ReadInt32();
             if (versionNumber >= 61)
             {
                 Main.jungleBackStyle = fileIO.ReadInt32();
                 Main.hellBackStyle = fileIO.ReadInt32();
             }
         }
         else
         {
             WorldGen.RandomizeCaveBackgrounds();
         }
         Main.spawnTileX = fileIO.ReadInt32();
         Main.spawnTileY = fileIO.ReadInt32();
         Main.worldSurface = fileIO.ReadDouble();
         Main.rockLayer = fileIO.ReadDouble();
         _tempTime = fileIO.ReadDouble();
         _tempDayTime = fileIO.ReadBoolean();
         _tempMoonPhase = fileIO.ReadInt32();
         _tempBloodMoon = fileIO.ReadBoolean();
         if (versionNumber >= 70)
         {
             _tempEclipse = fileIO.ReadBoolean();
             Main.eclipse = _tempEclipse;
         }
         Main.dungeonX = fileIO.ReadInt32();
         Main.dungeonY = fileIO.ReadInt32();
         if (versionNumber >= 56)
         {
             WorldGen.crimson = fileIO.ReadBoolean();
         }
         else
         {
             WorldGen.crimson = false;
         }
         NPC.downedBoss1 = fileIO.ReadBoolean();
         NPC.downedBoss2 = fileIO.ReadBoolean();
         NPC.downedBoss3 = fileIO.ReadBoolean();
         if (versionNumber >= 66)
         {
             NPC.downedQueenBee = fileIO.ReadBoolean();
         }
         if (versionNumber >= 44)
         {
             NPC.downedMechBoss1 = fileIO.ReadBoolean();
             NPC.downedMechBoss2 = fileIO.ReadBoolean();
             NPC.downedMechBoss3 = fileIO.ReadBoolean();
             NPC.downedMechBossAny = fileIO.ReadBoolean();
         }
         if (versionNumber >= 64)
         {
             NPC.downedPlantBoss = fileIO.ReadBoolean();
             NPC.downedGolemBoss = fileIO.ReadBoolean();
         }
         if (versionNumber >= 29)
         {
             NPC.savedGoblin = fileIO.ReadBoolean();
             NPC.savedWizard = fileIO.ReadBoolean();
             if (versionNumber >= 34)
             {
                 NPC.savedMech = fileIO.ReadBoolean();
                 if (versionNumber >= 80)
                 {
                     NPC.savedStylist = fileIO.ReadBoolean();
                 }
             }
             if (versionNumber >= 129)
             {
                 NPC.savedTaxCollector = fileIO.ReadBoolean();
             }
             if (versionNumber >= 201)
             {
                 NPC.savedGolfer = fileIO.ReadBoolean();
             }
             NPC.downedGoblins = fileIO.ReadBoolean();
         }
         if (versionNumber >= 32)
         {
             NPC.downedClown = fileIO.ReadBoolean();
         }
         if (versionNumber >= 37)
         {
             NPC.downedFrost = fileIO.ReadBoolean();
         }
         if (versionNumber >= 56)
         {
             NPC.downedPirates = fileIO.ReadBoolean();
         }
         WorldGen.shadowOrbSmashed = fileIO.ReadBoolean();
         WorldGen.spawnMeteor = fileIO.ReadBoolean();
         WorldGen.shadowOrbCount = fileIO.ReadByte();
         if (versionNumber >= 23)
         {
             WorldGen.altarCount = fileIO.ReadInt32();
             Main.hardMode = fileIO.ReadBoolean();
         }
         Main.invasionDelay = fileIO.ReadInt32();
         Main.invasionSize = fileIO.ReadInt32();
         Main.invasionType = fileIO.ReadInt32();
         Main.invasionX = fileIO.ReadDouble();
         if (versionNumber >= 113)
         {
             Main.sundialCooldown = fileIO.ReadByte();
         }
         if (versionNumber >= 53)
         {
             _tempRaining = fileIO.ReadBoolean();
             _tempRainTime = fileIO.ReadInt32();
             _tempMaxRain = fileIO.ReadSingle();
         }
         if (versionNumber >= 54)
         {
             WorldGen.SavedOreTiers.Cobalt = fileIO.ReadInt32();
             WorldGen.SavedOreTiers.Mythril = fileIO.ReadInt32();
             WorldGen.SavedOreTiers.Adamantite = fileIO.ReadInt32();
         }
         else if (versionNumber >= 23 && WorldGen.altarCount == 0)
         {
             WorldGen.SavedOreTiers.Cobalt = -1;
             WorldGen.SavedOreTiers.Mythril = -1;
             WorldGen.SavedOreTiers.Adamantite = -1;
         }
         else
         {
             WorldGen.SavedOreTiers.Cobalt = 107;
             WorldGen.SavedOreTiers.Mythril = 108;
             WorldGen.SavedOreTiers.Adamantite = 111;
         }
         int style = 0;
         int style2 = 0;
         int style3 = 0;
         int style4 = 0;
         int style5 = 0;
         int style6 = 0;
         int style7 = 0;
         int style8 = 0;
         int style9 = 0;
         int style10 = 0;
         if (versionNumber >= 55)
         {
             style = fileIO.ReadByte();
             style2 = fileIO.ReadByte();
             style3 = fileIO.ReadByte();
         }
         if (versionNumber >= 60)
         {
             style4 = fileIO.ReadByte();
             style5 = fileIO.ReadByte();
             style6 = fileIO.ReadByte();
             style7 = fileIO.ReadByte();
             style8 = fileIO.ReadByte();
         }
         WorldGen.setBG(0, style);
         WorldGen.setBG(1, style2);
         WorldGen.setBG(2, style3);
         WorldGen.setBG(3, style4);
         WorldGen.setBG(4, style5);
         WorldGen.setBG(5, style6);
         WorldGen.setBG(6, style7);
         WorldGen.setBG(7, style8);
         WorldGen.setBG(8, style9);
         WorldGen.setBG(9, style10);
         WorldGen.setBG(10, style);
         WorldGen.setBG(11, style);
         WorldGen.setBG(12, style);
         if (versionNumber >= 60)
         {
             Main.cloudBGActive = fileIO.ReadInt32();
             if (Main.cloudBGActive >= 1f)
             {
                 Main.cloudBGAlpha = 1f;
             }
             else
             {
                 Main.cloudBGAlpha = 0f;
             }
         }
         else
         {
             Main.cloudBGActive = -WorldGen.genRand.Next(8640, 86400);
         }
         if (versionNumber >= 62)
         {
             Main.numClouds = fileIO.ReadInt16();
             Main.windSpeedTarget = fileIO.ReadSingle();
             Main.windSpeedCurrent = Main.windSpeedTarget;
         }
         else
         {
             WorldGen.RandomizeWeather();
         }
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             float num = (float)i / (float)Main.maxTilesX;
             Main.statusText = Lang.gen[51].Value + " " + (int)(num * 100f + 1f) + "%";
             for (int j = 0; j < Main.maxTilesY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 int num2 = -1;
                 tile.active(fileIO.ReadBoolean());
                 if (tile.active())
                 {
                     num2 = ((versionNumber <= 77) ? fileIO.ReadByte() : fileIO.ReadUInt16());
                     tile.type = (ushort)num2;
                     if (tile.type == 127 || tile.type == 504)
                     {
                         tile.active(active: false);
                     }
                     if (versionNumber < 72 && (tile.type == 35 || tile.type == 36 || tile.type == 170 || tile.type == 171 || tile.type == 172))
                     {
                         tile.frameX = fileIO.ReadInt16();
                         tile.frameY = fileIO.ReadInt16();
                     }
                     else if (Main.tileFrameImportant[num2])
                     {
                         if (versionNumber < 28 && num2 == 4)
{
                             tile.frameX = 0;
                             tile.frameY = 0;
                         }
                         else if (versionNumber < 40 && tile.type == 19)
{
                             tile.frameX = 0;
                             tile.frameY = 0;
                         }
                         else if (versionNumber < 195 && tile.type == 49)
{
                             tile.frameX = 0;
                             tile.frameY = 0;
                         }
                         else
{
                             tile.frameX = fileIO.ReadInt16();
                             tile.frameY = fileIO.ReadInt16();
                             if (tile.type == 144)
{
                                 tile.frameY = 0;
                             }
                         }
                     }
                     else
                     {
                         tile.frameX = -1;
                         tile.frameY = -1;
                     }
                     if (versionNumber >= 48 && fileIO.ReadBoolean())
                     {
                         tile.color(fileIO.ReadByte());
                     }
                 }
                 if (versionNumber <= 25)
                 {
                     fileIO.ReadBoolean();
                 }
                 if (fileIO.ReadBoolean())
                 {
                     tile.wall = fileIO.ReadByte();
                     if (tile.wall >= WallID.Count)
                     {
                         tile.wall = 0;
                     }
                     if (versionNumber >= 48 && fileIO.ReadBoolean())
                     {
                         tile.wallColor(fileIO.ReadByte());
                     }
                 }
                 if (fileIO.ReadBoolean())
                 {
                     tile.liquid = fileIO.ReadByte();
                     tile.lava(fileIO.ReadBoolean());
                     if (versionNumber >= 51)
                     {
                         tile.honey(fileIO.ReadBoolean());
                     }
                 }
                 if (versionNumber >= 33)
                 {
                     tile.wire(fileIO.ReadBoolean());
                 }
                 if (versionNumber >= 43)
                 {
                     tile.wire2(fileIO.ReadBoolean());
                     tile.wire3(fileIO.ReadBoolean());
                 }
                 if (versionNumber >= 41)
                 {
                     tile.halfBrick(fileIO.ReadBoolean());
                     if (!Main.tileSolid[tile.type] && !TileID.Sets.NonSolidSaveSlopes[tile.type])
                     {
                         tile.halfBrick(halfBrick: false);
                     }
                     if (versionNumber >= 49)
                     {
                         tile.slope(fileIO.ReadByte());
                         if (!Main.tileSolid[tile.type] && !TileID.Sets.NonSolidSaveSlopes[tile.type])
{
                             tile.slope(0);
                         }
                     }
                 }
                 if (versionNumber >= 42)
                 {
                     tile.actuator(fileIO.ReadBoolean());
                     tile.inActive(fileIO.ReadBoolean());
                 }
                 int num3 = 0;
                 if (versionNumber >= 25)
                 {
                     num3 = fileIO.ReadInt16();
                 }
                 if (num2 != -1)
                 {
                     if ((double)j <= Main.worldSurface)
                     {
                         if ((double)(j + num3) <= Main.worldSurface)
{
                             WorldGen.tileCounts[num2] += (num3 + 1) * 5;
                         }
                         else
{
                             int num4 = (int)(Main.worldSurface - (double)j + 1.0);
                             int num5 = num3 + 1 - num4;
                             WorldGen.tileCounts[num2] += num4 * 5 + num5;
                         }
                     }
                     else
                     {
                         WorldGen.tileCounts[num2] += num3 + 1;
                     }
                 }
                 if (num3 > 0)
                 {
                     for (int k = j + 1; k < j + num3 + 1; k++)
                     {
                         Main.tile[i, k].CopyFrom(Main.tile[i, j]);
                     }
                     j += num3;
                 }
             }
         }
         WorldGen.AddUpAlignmentCounts(clearCounts: true);
         if (versionNumber < 67)
         {
             WorldGen.FixSunflowers();
         }
         if (versionNumber < 72)
         {
             WorldGen.FixChands();
         }
         int num6 = 40;
         if (versionNumber < 58)
         {
             num6 = 20;
         }
         int num7 = 1000;
         for (int l = 0; l < num7; l++)
         {
             if (!fileIO.ReadBoolean())
             {
                 continue;
             }
             Main.chest[l] = new Chest();
             Main.chest[l].x = fileIO.ReadInt32();
             Main.chest[l].y = fileIO.ReadInt32();
             if (versionNumber >= 85)
             {
                 string text = fileIO.ReadString();
                 if (text.Length > 20)
                 {
                     text = text.Substring(0, 20);
                 }
                 Main.chest[l].name = text;
             }
             for (int m = 0; m < 40; m++)
             {
                 Main.chest[l].item[m] = new Item();
                 if (m >= num6)
                 {
                     continue;
                 }
                 int num8 = 0;
                 num8 = ((versionNumber < 59) ? fileIO.ReadByte() : fileIO.ReadInt16());
                 if (num8 > 0)
                 {
                     if (versionNumber >= 38)
                     {
                         Main.chest[l].item[m].netDefaults(fileIO.ReadInt32());
                     }
                     else
                     {
                         short defaults = ItemID.FromLegacyName(fileIO.ReadString(), versionNumber);
                         Main.chest[l].item[m].SetDefaults(defaults);
                     }
                     Main.chest[l].item[m].stack = num8;
                     if (versionNumber >= 36)
                     {
                         Main.chest[l].item[m].Prefix(fileIO.ReadByte());
                     }
                 }
             }
         }
         for (int n = 0; n < 1000; n++)
         {
             if (fileIO.ReadBoolean())
             {
                 string text2 = fileIO.ReadString();
                 int num9 = fileIO.ReadInt32();
                 int num10 = fileIO.ReadInt32();
                 if (Main.tile[num9, num10].active() && (Main.tile[num9, num10].type == 55 || Main.tile[num9, num10].type == 85))
                 {
                     Main.sign[n] = new Sign();
                     Main.sign[n].x = num9;
                     Main.sign[n].y = num10;
                     Main.sign[n].text = text2;
                 }
             }
         }
         bool flag = fileIO.ReadBoolean();
         int num11 = 0;
         while (flag)
         {
             if (versionNumber >= 190)
             {
                 Main.npc[num11].SetDefaults(fileIO.ReadInt32());
             }
             else
             {
                 Main.npc[num11].SetDefaults(NPCID.FromLegacyName(fileIO.ReadString()));
             }
             if (versionNumber >= 83)
             {
                 Main.npc[num11].GivenName = fileIO.ReadString();
             }
             Main.npc[num11].position.X = fileIO.ReadSingle();
             Main.npc[num11].position.Y = fileIO.ReadSingle();
             Main.npc[num11].homeless = fileIO.ReadBoolean();
             Main.npc[num11].homeTileX = fileIO.ReadInt32();
             Main.npc[num11].homeTileY = fileIO.ReadInt32();
             flag = fileIO.ReadBoolean();
             num11++;
         }
         if (versionNumber >= 31 && versionNumber <= 83)
         {
             NPC.setNPCName(fileIO.ReadString(), 17, resetExtras: true);
             NPC.setNPCName(fileIO.ReadString(), 18, resetExtras: true);
             NPC.setNPCName(fileIO.ReadString(), 19, resetExtras: true);
             NPC.setNPCName(fileIO.ReadString(), 20, resetExtras: true);
             NPC.setNPCName(fileIO.ReadString(), 22, resetExtras: true);
             NPC.setNPCName(fileIO.ReadString(), 54, resetExtras: true);
             NPC.setNPCName(fileIO.ReadString(), 38, resetExtras: true);
             NPC.setNPCName(fileIO.ReadString(), 107, resetExtras: true);
             NPC.setNPCName(fileIO.ReadString(), 108, resetExtras: true);
             if (versionNumber >= 35)
             {
                 NPC.setNPCName(fileIO.ReadString(), 124, resetExtras: true);
                 if (versionNumber >= 65)
                 {
                     NPC.setNPCName(fileIO.ReadString(), 160, resetExtras: true);
                     NPC.setNPCName(fileIO.ReadString(), 178, resetExtras: true);
                     NPC.setNPCName(fileIO.ReadString(), 207, resetExtras: true);
                     NPC.setNPCName(fileIO.ReadString(), 208, resetExtras: true);
                     NPC.setNPCName(fileIO.ReadString(), 209, resetExtras: true);
                     NPC.setNPCName(fileIO.ReadString(), 227, resetExtras: true);
                     NPC.setNPCName(fileIO.ReadString(), 228, resetExtras: true);
                     NPC.setNPCName(fileIO.ReadString(), 229, resetExtras: true);
                     if (versionNumber >= 79)
                     {
                         NPC.setNPCName(fileIO.ReadString(), 353, resetExtras: true);
                     }
                 }
             }
         }
         if (Main.invasionType > 0 && Main.invasionSize > 0)
         {
             Main.FakeLoadInvasionStart();
         }
         if (versionNumber >= 7)
         {
             bool num12 = fileIO.ReadBoolean();
             string text3 = fileIO.ReadString();
             int num13 = fileIO.ReadInt32();
             if (num12 && (text3 == Main.worldName || num13 == Main.worldID))
             {
                 return 0;
             }
             return 2;
         }
         return 0;
     }
References _tempBloodMoon, _tempDayTime, _tempEclipse, _tempMaxRain, _tempMoonPhase, _tempRaining, _tempRainTime, _tempTime, _versionNumber, Tile.active(), Tile.actuator(), WorldGen.SavedOreTiers.Adamantite, WorldGen.AddUpAlignmentCounts(), WorldGen.altarCount, Main.bottomWorld, Main.caveBackStyle, Main.caveBackX, Main.chest, WorldGen.clearWorld(), Main.cloudBGActive, Main.cloudBGAlpha, WorldGen.SavedOreTiers.Cobalt, Tile.color(), Tile.CopyFrom(), WallID.Count, WorldGen.crimson, NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedClown, NPC.downedFrost, NPC.downedGoblins, NPC.downedGolemBoss, NPC.downedMechBoss1, NPC.downedMechBoss2, NPC.downedMechBoss3, NPC.downedMechBossAny, NPC.downedPirates, NPC.downedPlantBoss, NPC.downedQueenBee, Main.dungeonX, Main.dungeonY, Main.eclipse, Main.FakeLoadInvasionStart(), WorldGen.FixChands(), WorldGen.FixSunflowers(), Tile.frameX, Tile.frameY, FileMetadata.FromCurrentSettings(), NPCID.FromLegacyName(), ItemID.FromLegacyName(), Main.GameMode, Lang.gen, WorldGen.genRand, NPC.GivenName, Tile.halfBrick(), Main.hardMode, Main.hellBackStyle, NPC.homeless, NPC.homeTileX, NPC.homeTileY, Tile.honey(), Main.iceBackStyle, Tile.inActive(), Main.invasionDelay, Main.invasionSize, Main.invasionType, Main.invasionX, Chest.item, Main.jungleBackStyle, Tile.lava(), Main.leftWorld, Tile.liquid, Main.maxTilesX, Main.maxTilesY, Main.moonType, WorldGen.SavedOreTiers.Mythril, Chest.name, Item.netDefaults(), UnifiedRandom.Next(), TileID.Sets.NonSolidSaveSlopes, Main.npc, Main.numClouds, Entity.position, Item.Prefix(), WorldGen.RandomizeCaveBackgrounds(), WorldGen.RandomizeMoonState(), WorldGen.RandomizeWeather(), Main.rightWorld, Main.rockLayer, NPC.savedGoblin, NPC.savedGolfer, NPC.savedMech, NPC.savedStylist, NPC.savedTaxCollector, NPC.savedWizard, WorldGen.setBG(), NPC.SetDefaults(), Item.SetDefaults(), NPC.setNPCName(), WorldGen.shadowOrbCount, WorldGen.shadowOrbSmashed, Main.sign, Tile.slope(), WorldGen.spawnMeteor, Main.spawnTileX, Main.spawnTileY, Item.stack, Main.statusText, Main.sundialCooldown, Sign.text, Main.tile, WorldGen.tileCounts, Main.tileFrameImportant, Main.tileSolid, Main.topWorld, Main.treeStyle, Main.treeX, Tile.type, LocalizedText.Value, Tile.wall, Tile.wallColor(), Main.windSpeedCurrent, Main.windSpeedTarget, Tile.wire(), Tile.wire2(), Tile.wire3(), Main.WorldFileMetadata, Main.worldID, Main.worldName, Main.worldSurface, Chest.x, Sign.x, Chest.y, and Sign.y.
Referenced by LoadWorld().