Terraria: WorldFile.LoadWorld_Version2
LoadWorld_Version2()
static int WorldFile.LoadWorld_Version2 (BinaryReader reader) inline static
     {
         reader.BaseStream.Position = 0L;
         if (!LoadFileFormatHeader(reader, out var importance, out var positions))
         {
             return 5;
         }
         if (reader.BaseStream.Position != positions[0])
         {
             return 5;
         }
         LoadHeader(reader);
         if (reader.BaseStream.Position != positions[1])
         {
             return 5;
         }
         LoadWorldTiles(reader, importance);
         if (reader.BaseStream.Position != positions[2])
         {
             return 5;
         }
         LoadChests(reader);
         if (reader.BaseStream.Position != positions[3])
         {
             return 5;
         }
         LoadSigns(reader);
         if (reader.BaseStream.Position != positions[4])
         {
             return 5;
         }
         LoadNPCs(reader);
         if (reader.BaseStream.Position != positions[5])
         {
             return 5;
         }
         if (_versionNumber >= 116)
         {
             if (_versionNumber < 122)
             {
                 LoadDummies(reader);
                 if (reader.BaseStream.Position != positions[6])
                 {
                     return 5;
                 }
             }
             else
             {
                 LoadTileEntities(reader);
                 if (reader.BaseStream.Position != positions[6])
                 {
                     return 5;
                 }
             }
         }
         if (_versionNumber >= 170)
         {
             LoadWeightedPressurePlates(reader);
             if (reader.BaseStream.Position != positions[7])
             {
                 return 5;
             }
         }
         if (_versionNumber >= 189)
         {
             LoadTownManager(reader);
             if (reader.BaseStream.Position != positions[8])
             {
                 return 5;
             }
         }
         if (_versionNumber >= 210)
         {
             LoadBestiary(reader, _versionNumber);
             if (reader.BaseStream.Position != positions[9])
             {
                 return 5;
             }
         }
         else
         {
             LoadBestiaryForVersionsBefore210();
         }
         if (_versionNumber >= 220)
         {
             LoadCreativePowers(reader, _versionNumber);
             if (reader.BaseStream.Position != positions[10])
             {
                 return 5;
             }
         }
         LoadWorld_LastMinuteFixes();
         return LoadFooter(reader);
     }
References _versionNumber, L, LoadBestiary(), LoadBestiaryForVersionsBefore210(), LoadChests(), LoadCreativePowers(), LoadDummies(), LoadFileFormatHeader(), LoadFooter(), LoadHeader(), LoadNPCs(), LoadSigns(), LoadTileEntities(), LoadTownManager(), LoadWeightedPressurePlates(), LoadWorld_LastMinuteFixes(), and LoadWorldTiles().
Referenced by LoadWorld().