Terraria: WorldFile.InternalSaveWorld
InternalSaveWorld()
static void WorldFile.InternalSaveWorld (bool useCloudSaving, bool resetTime) inline static private
     {
         Utils.TryCreatingDirectory(Main.WorldPath);
         if (Main.skipMenu)
         {
             return;
         }
         if (_hasCache)
         {
             SetTempToCache();
         }
         else
         {
             SetTempToOngoing();
         }
         if (resetTime)
         {
             ResetTempsToDayTime();
         }
         if (Main.worldPathName == null)
         {
             return;
         }
         new Stopwatch().Start();
         int num;
         byte[] array;
         using (MemoryStream memoryStream = new MemoryStream(7000000))
         {
             using (BinaryWriter writer = new BinaryWriter(memoryStream))
             {
                 SaveWorld_Version2(writer);
             }
             array = memoryStream.ToArray();
             num = array.Length;
         }
         byte[] array2 = null;
         if (FileUtilities.Exists(Main.worldPathName, useCloudSaving))
         {
             array2 = FileUtilities.ReadAllBytes(Main.worldPathName, useCloudSaving);
         }
         FileUtilities.Write(Main.worldPathName, array, num, useCloudSaving);
         array = FileUtilities.ReadAllBytes(Main.worldPathName, useCloudSaving);
         string text = null;
         using (MemoryStream input = new MemoryStream(array, 0, num, writable: false))
         {
             using BinaryReader fileIO = new BinaryReader(input);
             if (!Main.validateSaves || ValidateWorld(fileIO))
             {
                 if (array2 != null)
                 {
                     text = Main.worldPathName + ".bak";
                     Main.statusText = Lang.gen[50].Value;
                 }
                 DoRollingBackups(text);
             }
             else
             {
                 text = Main.worldPathName;
             }
         }
         if (text != null && array2 != null)
         {
             FileUtilities.WriteAllBytes(text, array2, useCloudSaving);
         }
     }
References _hasCache, DoRollingBackups(), FileUtilities.Exists(), Lang.gen, FileUtilities.ReadAllBytes(), ResetTempsToDayTime(), SaveWorld_Version2(), SetTempToCache(), SetTempToOngoing(), Main.skipMenu, Main.statusText, Utils.TryCreatingDirectory(), Main.validateSaves, ValidateWorld(), LocalizedText.Value, Main.WorldPath, Main.worldPathName, FileUtilities.Write(), and FileUtilities.WriteAllBytes().
Referenced by SaveWorld().