Terraria: WorldFile.LoadChests
LoadChests()
static void WorldFile.LoadChests (BinaryReader reader) inline static
     {
         int num = reader.ReadInt16();
         int num2 = reader.ReadInt16();
         int num3;
         int num4;
         if (num2 < 40)
         {
             num3 = num2;
             num4 = 0;
         }
         else
         {
             num3 = 40;
             num4 = num2 - 40;
         }
         int i;
         for (i = 0; i < num; i++)
         {
             Chest chest = new Chest();
             chest.x = reader.ReadInt32();
             chest.y = reader.ReadInt32();
             chest.name = reader.ReadString();
             for (int j = 0; j < num3; j++)
             {
                 short num5 = reader.ReadInt16();
                 Item item = new Item();
                 if (num5 > 0)
                 {
                     item.netDefaults(reader.ReadInt32());
                     item.stack = num5;
                     item.Prefix(reader.ReadByte());
                 }
                 else if (num5 < 0)
                 {
                     item.netDefaults(reader.ReadInt32());
                     item.Prefix(reader.ReadByte());
                     item.stack = 1;
                 }
                 chest.item[j] = item;
             }
             for (int k = 0; k < num4; k++)
             {
                 short num5 = reader.ReadInt16();
                 if (num5 > 0)
                 {
                     reader.ReadInt32();
                     reader.ReadByte();
                 }
             }
             Main.chest[i] = chest;
         }
         List<Point16> list = new List<Point16>();
         for (int l = 0; l < i; l++)
         {
             if (Main.chest[l] != null)
             {
                 Point16 item2 = new Point16(Main.chest[l].x, Main.chest[l].y);
                 if (list.Contains(item2))
                 {
                     Main.chest[l] = null;
                 }
                 else
                 {
                     list.Add(item2);
                 }
             }
         }
         for (; i < 8000; i++)
         {
             Main.chest[i] = null;
         }
         if (_versionNumber < 115)
         {
             FixDresserChests();
         }
     }
References _versionNumber, Main.chest, FixDresserChests(), Chest.item, Chest.name, Item.netDefaults(), Item.Prefix(), Item.stack, Chest.x, and Chest.y.
Referenced by LoadWorld_Version2().