Terraria: WorldFile.SaveWorldTiles
SaveWorldTiles()
static int WorldFile.SaveWorldTiles (BinaryWriter writer) inline static
     {
         byte[] array = new byte[16];
         for (int i = 0; i < Main.maxTilesX; i++)
         {
             float num = (float)i / (float)Main.maxTilesX;
             Main.statusText = Lang.gen[49].Value + " " + (int)(num * 100f + 1f) + "%";
             int num2;
             for (num2 = 0; num2 < Main.maxTilesY; num2++)
             {
                 Tile tile = Main.tile[i, num2];
                 int num3 = 4;
                 byte b2;
                 byte b;
                 byte b3;
                 byte b4 = (b3 = (b2 = (b = 0)));
                 bool flag = false;
                 if (tile.active())
                 {
                     flag = true;
                 }
                 if (flag)
                 {
                     b4 = (byte)(b4 | 2u);
                     array[num3] = (byte)tile.type;
                     num3++;
                     if (tile.type > 255)
                     {
                         array[num3] = (byte)(tile.type >> 8);
                         num3++;
                         b4 = (byte)(b4 | 0x20u);
                     }
                     if (Main.tileFrameImportant[tile.type])
                     {
                         array[num3] = (byte)((uint)tile.frameX & 0xFFu);
                         num3++;
                         array[num3] = (byte)((tile.frameX & 0xFF00) >> 8);
                         num3++;
                         array[num3] = (byte)((uint)tile.frameY & 0xFFu);
                         num3++;
                         array[num3] = (byte)((tile.frameY & 0xFF00) >> 8);
                         num3++;
                     }
                     if (tile.color() != 0)
                     {
                         b2 = (byte)(b2 | 8u);
                         array[num3] = tile.color();
                         num3++;
                     }
                 }
                 if (tile.wall != 0)
                 {
                     b4 = (byte)(b4 | 4u);
                     array[num3] = (byte)tile.wall;
                     num3++;
                     if (tile.wallColor() != 0)
                     {
                         b2 = (byte)(b2 | 0x10u);
                         array[num3] = tile.wallColor();
                         num3++;
                     }
                 }
                 if (tile.liquid != 0)
                 {
                     if (!tile.shimmer())
                     {
                         b4 = (tile.lava() ? ((byte)(b4 | 0x10u)) : ((!tile.honey()) ? ((byte)(b4 | 8u)) : ((byte)(b4 | 0x18u))));
                     }
                     else
                     {
                         b2 = (byte)(b2 | 0x80u);
                         b4 = (byte)(b4 | 8u);
                     }
                     array[num3] = tile.liquid;
                     num3++;
                 }
                 if (tile.wire())
                 {
                     b3 = (byte)(b3 | 2u);
                 }
                 if (tile.wire2())
                 {
                     b3 = (byte)(b3 | 4u);
                 }
                 if (tile.wire3())
                 {
                     b3 = (byte)(b3 | 8u);
                 }
                 int num4 = (tile.halfBrick() ? 16 : ((tile.slope() != 0) ? (tile.slope() + 1 << 4) : 0));
                 b3 |= (byte)num4;
                 if (tile.actuator())
                 {
                     b2 = (byte)(b2 | 2u);
                 }
                 if (tile.inActive())
                 {
                     b2 = (byte)(b2 | 4u);
                 }
                 if (tile.wire4())
                 {
                     b2 = (byte)(b2 | 0x20u);
                 }
                 if (tile.wall > 255)
                 {
                     array[num3] = (byte)(tile.wall >> 8);
                     num3++;
                     b2 = (byte)(b2 | 0x40u);
                 }
                 if (tile.invisibleBlock())
                 {
                     b = (byte)(b | 2u);
                 }
                 if (tile.invisibleWall())
                 {
                     b = (byte)(b | 4u);
                 }
                 if (tile.fullbrightBlock())
                 {
                     b = (byte)(b | 8u);
                 }
                 if (tile.fullbrightWall())
                 {
                     b = (byte)(b | 0x10u);
                 }
                 int num5 = 3;
                 if (b != 0)
                 {
                     b2 = (byte)(b2 | 1u);
                     array[num5] = b;
                     num5--;
                 }
                 if (b2 != 0)
                 {
                     b3 = (byte)(b3 | 1u);
                     array[num5] = b2;
                     num5--;
                 }
                 if (b3 != 0)
                 {
                     b4 = (byte)(b4 | 1u);
                     array[num5] = b3;
                     num5--;
                 }
                 short num6 = 0;
                 int num7 = num2 + 1;
                 int num8 = Main.maxTilesY - num2 - 1;
                 while (num8 > 0 && tile.isTheSameAs(Main.tile[i, num7]) && TileID.Sets.AllowsSaveCompressionBatching[tile.type])
                 {
                     num6++;
                     num8--;
                     num7++;
                 }
                 num2 += num6;
                 if (num6 > 0)
                 {
                     array[num3] = (byte)((uint)num6 & 0xFFu);
                     num3++;
                     if (num6 > 255)
                     {
                         b4 = (byte)(b4 | 0x80u);
                         array[num3] = (byte)((num6 & 0xFF00) >> 8);
                         num3++;
                     }
                     else
                     {
                         b4 = (byte)(b4 | 0x40u);
                     }
                 }
                 array[num5] = b4;
                 writer.Write(array, num5, num3 - num5);
             }
         }
         return (int)writer.BaseStream.Position;
     }
References Tile.active(), Tile.actuator(), TileID.Sets.AllowsSaveCompressionBatching, Tile.color(), Tile.frameX, Tile.frameY, Tile.fullbrightBlock(), Tile.fullbrightWall(), Lang.gen, Tile.halfBrick(), Tile.honey(), Tile.inActive(), Tile.invisibleBlock(), Tile.invisibleWall(), Tile.isTheSameAs(), Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.shimmer(), Tile.slope(), Main.statusText, Main.tile, Main.tileFrameImportant, Tile.type, LocalizedText.Value, Tile.wall, Tile.wallColor(), Tile.wire(), Tile.wire2(), Tile.wire3(), and Tile.wire4().
Referenced by SaveWorld_Version2().