Terraria: WorldFile.SaveWorldHeader
SaveWorldHeader()
static int WorldFile.SaveWorldHeader (BinaryWriter writer) inline static
     {
         writer.Write(Main.worldName);
         writer.Write(Main.ActiveWorldFileData.SeedText);
         writer.Write(Main.ActiveWorldFileData.WorldGeneratorVersion);
         writer.Write(Main.ActiveWorldFileData.UniqueId.ToByteArray());
         writer.Write(Main.worldID);
         writer.Write((int)Main.leftWorld);
         writer.Write((int)Main.rightWorld);
         writer.Write((int)Main.topWorld);
         writer.Write((int)Main.bottomWorld);
         writer.Write(Main.maxTilesY);
         writer.Write(Main.maxTilesX);
         writer.Write(Main.GameMode);
         writer.Write(Main.drunkWorld);
         writer.Write(Main.getGoodWorld);
         writer.Write(Main.tenthAnniversaryWorld);
         writer.Write(Main.dontStarveWorld);
         writer.Write(Main.notTheBeesWorld);
         writer.Write(Main.remixWorld);
         writer.Write(Main.noTrapsWorld);
         writer.Write(Main.zenithWorld);
         writer.Write(Main.ActiveWorldFileData.CreationTime.ToBinary());
         writer.Write((byte)Main.moonType);
         writer.Write(Main.treeX[0]);
         writer.Write(Main.treeX[1]);
         writer.Write(Main.treeX[2]);
         writer.Write(Main.treeStyle[0]);
         writer.Write(Main.treeStyle[1]);
         writer.Write(Main.treeStyle[2]);
         writer.Write(Main.treeStyle[3]);
         writer.Write(Main.caveBackX[0]);
         writer.Write(Main.caveBackX[1]);
         writer.Write(Main.caveBackX[2]);
         writer.Write(Main.caveBackStyle[0]);
         writer.Write(Main.caveBackStyle[1]);
         writer.Write(Main.caveBackStyle[2]);
         writer.Write(Main.caveBackStyle[3]);
         writer.Write(Main.iceBackStyle);
         writer.Write(Main.jungleBackStyle);
         writer.Write(Main.hellBackStyle);
         writer.Write(Main.spawnTileX);
         writer.Write(Main.spawnTileY);
         writer.Write(Main.worldSurface);
         writer.Write(Main.rockLayer);
         writer.Write(_tempTime);
         writer.Write(_tempDayTime);
         writer.Write(_tempMoonPhase);
         writer.Write(_tempBloodMoon);
         writer.Write(_tempEclipse);
         writer.Write(Main.dungeonX);
         writer.Write(Main.dungeonY);
         writer.Write(WorldGen.crimson);
         writer.Write(NPC.downedBoss1);
         writer.Write(NPC.downedBoss2);
         writer.Write(NPC.downedBoss3);
         writer.Write(NPC.downedQueenBee);
         writer.Write(NPC.downedMechBoss1);
         writer.Write(NPC.downedMechBoss2);
         writer.Write(NPC.downedMechBoss3);
         writer.Write(NPC.downedMechBossAny);
         writer.Write(NPC.downedPlantBoss);
         writer.Write(NPC.downedGolemBoss);
         writer.Write(NPC.downedSlimeKing);
         writer.Write(NPC.savedGoblin);
         writer.Write(NPC.savedWizard);
         writer.Write(NPC.savedMech);
         writer.Write(NPC.downedGoblins);
         writer.Write(NPC.downedClown);
         writer.Write(NPC.downedFrost);
         writer.Write(NPC.downedPirates);
         writer.Write(WorldGen.shadowOrbSmashed);
         writer.Write(WorldGen.spawnMeteor);
         writer.Write((byte)WorldGen.shadowOrbCount);
         writer.Write(WorldGen.altarCount);
         writer.Write(Main.hardMode);
         writer.Write(Main.afterPartyOfDoom);
         writer.Write(Main.invasionDelay);
         writer.Write(Main.invasionSize);
         writer.Write(Main.invasionType);
         writer.Write(Main.invasionX);
         writer.Write(Main.slimeRainTime);
         writer.Write((byte)Main.sundialCooldown);
         writer.Write(_tempRaining);
         writer.Write(_tempRainTime);
         writer.Write(_tempMaxRain);
         writer.Write(WorldGen.SavedOreTiers.Cobalt);
         writer.Write(WorldGen.SavedOreTiers.Mythril);
         writer.Write(WorldGen.SavedOreTiers.Adamantite);
         writer.Write((byte)WorldGen.treeBG1);
         writer.Write((byte)WorldGen.corruptBG);
         writer.Write((byte)WorldGen.jungleBG);
         writer.Write((byte)WorldGen.snowBG);
         writer.Write((byte)WorldGen.hallowBG);
         writer.Write((byte)WorldGen.crimsonBG);
         writer.Write((byte)WorldGen.desertBG);
         writer.Write((byte)WorldGen.oceanBG);
         writer.Write((int)Main.cloudBGActive);
         writer.Write((short)Main.numClouds);
         writer.Write(Main.windSpeedTarget);
         writer.Write(Main.anglerWhoFinishedToday.Count);
         for (int i = 0; i < Main.anglerWhoFinishedToday.Count; i++)
         {
             writer.Write(Main.anglerWhoFinishedToday[i]);
         }
         writer.Write(NPC.savedAngler);
         writer.Write(Main.anglerQuest);
         writer.Write(NPC.savedStylist);
         writer.Write(NPC.savedTaxCollector);
         writer.Write(NPC.savedGolfer);
         writer.Write(Main.invasionSizeStart);
         writer.Write(_tempCultistDelay);
         writer.Write(NPCID.Count);
         for (int j = 0; j < NPCID.Count; j++)
         {
             writer.Write(NPC.killCount[j]);
         }
         writer.Write(Main.fastForwardTimeToDawn);
         writer.Write(NPC.downedFishron);
         writer.Write(NPC.downedMartians);
         writer.Write(NPC.downedAncientCultist);
         writer.Write(NPC.downedMoonlord);
         writer.Write(NPC.downedHalloweenKing);
         writer.Write(NPC.downedHalloweenTree);
         writer.Write(NPC.downedChristmasIceQueen);
         writer.Write(NPC.downedChristmasSantank);
         writer.Write(NPC.downedChristmasTree);
         writer.Write(NPC.downedTowerSolar);
         writer.Write(NPC.downedTowerVortex);
         writer.Write(NPC.downedTowerNebula);
         writer.Write(NPC.downedTowerStardust);
         writer.Write(NPC.TowerActiveSolar);
         writer.Write(NPC.TowerActiveVortex);
         writer.Write(NPC.TowerActiveNebula);
         writer.Write(NPC.TowerActiveStardust);
         writer.Write(NPC.LunarApocalypseIsUp);
         writer.Write(_tempPartyManual);
         writer.Write(_tempPartyGenuine);
         writer.Write(_tempPartyCooldown);
         writer.Write(TempPartyCelebratingNPCs.Count);
         for (int k = 0; k < TempPartyCelebratingNPCs.Count; k++)
         {
             writer.Write(TempPartyCelebratingNPCs[k]);
         }
         writer.Write(_tempSandstormHappening);
         writer.Write(_tempSandstormTimeLeft);
         writer.Write(_tempSandstormSeverity);
         writer.Write(_tempSandstormIntendedSeverity);
         writer.Write(NPC.savedBartender);
         DD2Event.Save(writer);
         writer.Write((byte)WorldGen.mushroomBG);
         writer.Write((byte)WorldGen.underworldBG);
         writer.Write((byte)WorldGen.treeBG2);
         writer.Write((byte)WorldGen.treeBG3);
         writer.Write((byte)WorldGen.treeBG4);
         writer.Write(NPC.combatBookWasUsed);
         writer.Write(_tempLanternNightCooldown);
         writer.Write(_tempLanternNightGenuine);
         writer.Write(_tempLanternNightManual);
         writer.Write(_tempLanternNightNextNightIsGenuine);
         WorldGen.TreeTops.Save(writer);
         writer.Write(Main.forceHalloweenForToday);
         writer.Write(Main.forceXMasForToday);
         writer.Write(WorldGen.SavedOreTiers.Copper);
         writer.Write(WorldGen.SavedOreTiers.Iron);
         writer.Write(WorldGen.SavedOreTiers.Silver);
         writer.Write(WorldGen.SavedOreTiers.Gold);
         writer.Write(NPC.boughtCat);
         writer.Write(NPC.boughtDog);
         writer.Write(NPC.boughtBunny);
         writer.Write(NPC.downedEmpressOfLight);
         writer.Write(NPC.downedQueenSlime);
         writer.Write(NPC.downedDeerclops);
         writer.Write(NPC.unlockedSlimeBlueSpawn);
         writer.Write(NPC.unlockedMerchantSpawn);
         writer.Write(NPC.unlockedDemolitionistSpawn);
         writer.Write(NPC.unlockedPartyGirlSpawn);
         writer.Write(NPC.unlockedDyeTraderSpawn);
         writer.Write(NPC.unlockedTruffleSpawn);
         writer.Write(NPC.unlockedArmsDealerSpawn);
         writer.Write(NPC.unlockedNurseSpawn);
         writer.Write(NPC.unlockedPrincessSpawn);
         writer.Write(NPC.combatBookVolumeTwoWasUsed);
         writer.Write(NPC.peddlersSatchelWasUsed);
         writer.Write(NPC.unlockedSlimeGreenSpawn);
         writer.Write(NPC.unlockedSlimeOldSpawn);
         writer.Write(NPC.unlockedSlimePurpleSpawn);
         writer.Write(NPC.unlockedSlimeRainbowSpawn);
         writer.Write(NPC.unlockedSlimeRedSpawn);
         writer.Write(NPC.unlockedSlimeYellowSpawn);
         writer.Write(NPC.unlockedSlimeCopperSpawn);
         writer.Write(Main.fastForwardTimeToDusk);
         writer.Write((byte)Main.moondialCooldown);
         return (int)writer.BaseStream.Position;
     }
References _tempBloodMoon, _tempCultistDelay, _tempDayTime, _tempEclipse, _tempLanternNightCooldown, _tempLanternNightGenuine, _tempLanternNightManual, _tempLanternNightNextNightIsGenuine, _tempMaxRain, _tempMoonPhase, _tempPartyCooldown, _tempPartyGenuine, _tempPartyManual, _tempRaining, _tempRainTime, _tempSandstormHappening, _tempSandstormIntendedSeverity, _tempSandstormSeverity, _tempSandstormTimeLeft, _tempTime, Main.ActiveWorldFileData, WorldGen.SavedOreTiers.Adamantite, Main.afterPartyOfDoom, WorldGen.altarCount, Main.anglerQuest, Main.anglerWhoFinishedToday, Main.bottomWorld, NPC.boughtBunny, NPC.boughtCat, NPC.boughtDog, Main.caveBackStyle, Main.caveBackX, Main.cloudBGActive, WorldGen.SavedOreTiers.Cobalt, NPC.combatBookVolumeTwoWasUsed, NPC.combatBookWasUsed, WorldGen.SavedOreTiers.Copper, WorldGen.corruptBG, NPCID.Count, WorldFileData.CreationTime, WorldGen.crimson, WorldGen.crimsonBG, WorldGen.desertBG, Main.dontStarveWorld, NPC.downedAncientCultist, NPC.downedBoss1, NPC.downedBoss2, NPC.downedBoss3, NPC.downedChristmasIceQueen, NPC.downedChristmasSantank, NPC.downedChristmasTree, NPC.downedClown, NPC.downedDeerclops, NPC.downedEmpressOfLight, NPC.downedFishron, NPC.downedFrost, NPC.downedGoblins, NPC.downedGolemBoss, NPC.downedHalloweenKing, NPC.downedHalloweenTree, NPC.downedMartians, NPC.downedMechBoss1, NPC.downedMechBoss2, NPC.downedMechBoss3, NPC.downedMechBossAny, NPC.downedMoonlord, NPC.downedPirates, NPC.downedPlantBoss, NPC.downedQueenBee, NPC.downedQueenSlime, NPC.downedSlimeKing, NPC.downedTowerNebula, NPC.downedTowerSolar, NPC.downedTowerStardust, NPC.downedTowerVortex, Main.drunkWorld, Main.dungeonX, Main.dungeonY, Main.fastForwardTimeToDawn, Main.fastForwardTimeToDusk, Main.forceHalloweenForToday, Main.forceXMasForToday, Main.GameMode, Main.getGoodWorld, WorldGen.SavedOreTiers.Gold, WorldGen.hallowBG, Main.hardMode, Main.hellBackStyle, Main.iceBackStyle, Main.invasionDelay, Main.invasionSize, Main.invasionSizeStart, Main.invasionType, Main.invasionX, WorldGen.SavedOreTiers.Iron, Main.jungleBackStyle, WorldGen.jungleBG, NPC.killCount, Main.leftWorld, NPC.LunarApocalypseIsUp, Main.maxTilesX, Main.maxTilesY, Main.moondialCooldown, Main.moonType, WorldGen.mushroomBG, WorldGen.SavedOreTiers.Mythril, Main.noTrapsWorld, Main.notTheBeesWorld, Main.numClouds, WorldGen.oceanBG, NPC.peddlersSatchelWasUsed, Main.remixWorld, Main.rightWorld, Main.rockLayer, DD2Event.Save(), TreeTopsInfo.Save(), NPC.savedAngler, NPC.savedBartender, NPC.savedGoblin, NPC.savedGolfer, NPC.savedMech, NPC.savedStylist, NPC.savedTaxCollector, NPC.savedWizard, WorldFileData.SeedText, WorldGen.shadowOrbCount, WorldGen.shadowOrbSmashed, WorldGen.SavedOreTiers.Silver, Main.slimeRainTime, WorldGen.snowBG, WorldGen.spawnMeteor, Main.spawnTileX, Main.spawnTileY, Main.sundialCooldown, TempPartyCelebratingNPCs, Main.tenthAnniversaryWorld, Main.topWorld, NPC.TowerActiveNebula, NPC.TowerActiveSolar, NPC.TowerActiveStardust, NPC.TowerActiveVortex, WorldGen.treeBG1, WorldGen.treeBG2, WorldGen.treeBG3, WorldGen.treeBG4, Main.treeStyle, WorldGen.TreeTops, Main.treeX, WorldGen.underworldBG, WorldFileData.UniqueId, NPC.unlockedArmsDealerSpawn, NPC.unlockedDemolitionistSpawn, NPC.unlockedDyeTraderSpawn, NPC.unlockedMerchantSpawn, NPC.unlockedNurseSpawn, NPC.unlockedPartyGirlSpawn, NPC.unlockedPrincessSpawn, NPC.unlockedSlimeBlueSpawn, NPC.unlockedSlimeCopperSpawn, NPC.unlockedSlimeGreenSpawn, NPC.unlockedSlimeOldSpawn, NPC.unlockedSlimePurpleSpawn, NPC.unlockedSlimeRainbowSpawn, NPC.unlockedSlimeRedSpawn, NPC.unlockedSlimeYellowSpawn, NPC.unlockedTruffleSpawn, Main.windSpeedTarget, WorldFileData.WorldGeneratorVersion, Main.worldID, Main.worldName, Main.worldSurface, and Main.zenithWorld.
Referenced by SaveWorld_Version2().