Terraria: WorldFile.SaveWorld
SaveWorld() [1/2]
static void WorldFile.SaveWorld () inline static
     {
         try
         {
             SaveWorld(_isWorldOnCloud);
         }
         catch (Exception exception)
         {
             FancyErrorPrinter.ShowFileSavingFailError(exception, Main.WorldPath);
             throw;
         }
     }
References _isWorldOnCloud, FancyErrorPrinter.ShowFileSavingFailError(), and Main.WorldPath.
Referenced by Main.DedServ(), LoadWorld(), WorldGen.RenameWorldCallBack(), WorldGen.saveAndPlayCallBack(), WorldGen.SaveAndQuitCallBack(), Main.startDedInputCallBack(), and WorldGen.worldGenCallback().