Terraria: WorldFile.LoadTileEntities
LoadTileEntities()
static void WorldFile.LoadTileEntities (BinaryReader reader) inline static
     {
         TileEntity.ByID.Clear();
         TileEntity.ByPosition.Clear();
         int num = reader.ReadInt32();
         int num2 = 0;
         for (int i = 0; i < num; i++)
         {
             TileEntity tileEntity = TileEntity.Read(reader);
             tileEntity.ID = num2++;
             TileEntity.ByID[tileEntity.ID] = tileEntity;
             if (TileEntity.ByPosition.TryGetValue(tileEntity.Position, out var value))
             {
                 TileEntity.ByID.Remove(value.ID);
             }
             TileEntity.ByPosition[tileEntity.Position] = tileEntity;
         }
         TileEntity.TileEntitiesNextID = num;
         List<Point16> list = new List<Point16>();
         foreach (KeyValuePair<Point16, TileEntity> item in TileEntity.ByPosition)
         {
             if (!WorldGen.InWorld(item.Value.Position.X, item.Value.Position.Y, 1))
             {
                 list.Add(item.Value.Position);
             }
             else if (!TileEntity.manager.CheckValidTile(item.Value.type, item.Value.Position.X, item.Value.Position.Y))
             {
                 list.Add(item.Value.Position);
             }
         }
         try
         {
             foreach (Point16 item2 in list)
             {
                 TileEntity tileEntity2 = TileEntity.ByPosition[item2];
                 if (TileEntity.ByID.ContainsKey(tileEntity2.ID))
                 {
                     TileEntity.ByID.Remove(tileEntity2.ID);
                 }
                 if (TileEntity.ByPosition.ContainsKey(item2))
                 {
                     TileEntity.ByPosition.Remove(item2);
                 }
             }
         }
         catch
         {
         }
     }
References TileEntity.ByID, TileEntity.ByPosition, TileEntitiesManager.CheckValidTile(), TileEntity.ID, WorldGen.InWorld(), TileEntity.manager, TileEntity.Position, TileEntity.Read(), and TileEntity.TileEntitiesNextID.
Referenced by LoadWorld_Version2().