Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ConnectAsync
ConnectAsync()
unsafe override ValueTask System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ConnectAsync (CancellationToken cancellationToken = default(CancellationToken)) inline package
Definition at line 510 of file MsQuicConnection.cs.
    {
        ThrowIfDisposed();
        if (_configuration == null)
        {
            throw new InvalidOperationException("ConnectAsync must not be called on a connection obtained from a listener.");
        }
        QUIC_ADDRESS_FAMILY family = _remoteEndPoint.AddressFamily switch
        {
            AddressFamily.Unspecified => QUIC_ADDRESS_FAMILY.UNSPEC,
            AddressFamily.InterNetwork => QUIC_ADDRESS_FAMILY.INET,
            AddressFamily.InterNetworkV6 => QUIC_ADDRESS_FAMILY.INET6,
            _ => throw new ArgumentException(System.SR.Format(System.SR.net_quic_unsupported_address_family, _remoteEndPoint.AddressFamily)),
        };
        _state.Connection = this;
        string serverName;
        int port;
        if (_remoteEndPoint is IPEndPoint)
        {
            MsQuicNativeMethods.SOCKADDR_INET sOCKADDR_INET = MsQuicAddressHelpers.IPEndPointToINet((IPEndPoint)_remoteEndPoint);
            uint status = MsQuicApi.Api.SetParamDelegate(_state.Handle, QUIC_PARAM_LEVEL.CONNECTION, 2u, (uint)sizeof(MsQuicNativeMethods.SOCKADDR_INET), (byte*)(&sOCKADDR_INET));
            QuicExceptionHelpers.ThrowIfFailed(status, "Failed to connect to peer.");
            serverName = _state.TargetHost ?? ((IPEndPoint)_remoteEndPoint).Address.ToString();
            port = ((IPEndPoint)_remoteEndPoint).Port;
        }
        else
        {
            if (!(_remoteEndPoint is DnsEndPoint))
            {
                throw new ArgumentException($"Unsupported remote endpoint type '{_remoteEndPoint.GetType()}'.");
            }
            port = ((DnsEndPoint)_remoteEndPoint).Port;
            string host = ((DnsEndPoint)_remoteEndPoint).Host;
            if (!string.IsNullOrEmpty(_state.TargetHost) && !host.Equals(_state.TargetHost, StringComparison.InvariantCultureIgnoreCase) && IPAddress.TryParse(host, out IPAddress address))
            {
                MsQuicNativeMethods.SOCKADDR_INET sOCKADDR_INET2 = MsQuicAddressHelpers.IPEndPointToINet(new IPEndPoint(address, port));
                uint status = MsQuicApi.Api.SetParamDelegate(_state.Handle, QUIC_PARAM_LEVEL.CONNECTION, 2u, (uint)sizeof(MsQuicNativeMethods.SOCKADDR_INET), (byte*)(&sOCKADDR_INET2));
                QuicExceptionHelpers.ThrowIfFailed(status, "Failed to connect to peer.");
                serverName = _state.TargetHost;
            }
            else
            {
                serverName = host;
            }
        }
        TaskCompletionSource<uint> taskCompletionSource = (_state.ConnectTcs = new TaskCompletionSource<uint>(TaskCreationOptions.RunContinuationsAsynchronously));
        try
        {
            uint status = MsQuicApi.Api.ConnectionStartDelegate(_state.Handle, _configuration, family, serverName, (ushort)port);
            QuicExceptionHelpers.ThrowIfFailed(status, "Failed to connect to peer.");
            _configuration.Dispose();
            _configuration = null;
        }
        catch
        {
            _state.StateGCHandle.Free();
            _state.Connection = null;
            throw;
        }
        return new ValueTask(taskCompletionSource.Task);
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicConnection._configuration, System.Net.Quic.Implementations.MsQuic.MsQuicConnection._remoteEndPoint, System.Net.Quic.Implementations.MsQuic.MsQuicConnection._state, System.Net.EndPoint.AddressFamily, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Runtime.InteropServices.SafeHandle.Dispose(), System.SR.Format(), System.Runtime.InteropServices.GCHandle.Free(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.Handle, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.IPEndPointToINet(), System.SR.net_quic_unsupported_address_family, System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.StateGCHandle, System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.TargetHost, System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ThrowIfDisposed(), System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(), and System.Net.IPAddress.TryParse().