Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicConnection.MsQuicConnection
MsQuicConnection() [2/2]
System.Net.Quic.Implementations.MsQuic.MsQuicConnection.MsQuicConnection (QuicClientConnectionOptions options) inline
Definition at line 173 of file MsQuicConnection.cs.
    {
        if (options.RemoteEndPoint == null)
        {
            throw new ArgumentNullException("RemoteEndPoint");
        }
        _remoteEndPoint = options.RemoteEndPoint;
        _configuration = SafeMsQuicConfigurationHandle.Create(options);
        _state.RemoteCertificateRequired = true;
        if (options.ClientAuthenticationOptions != null)
        {
            _state.RevocationMode = options.ClientAuthenticationOptions.CertificateRevocationCheckMode;
            _state.RemoteCertificateValidationCallback = options.ClientAuthenticationOptions.RemoteCertificateValidationCallback;
            _state.TargetHost = options.ClientAuthenticationOptions.TargetHost;
        }
        _state.StateGCHandle = GCHandle.Alloc(_state);
        try
        {
            uint status = MsQuicApi.Api.ConnectionOpenDelegate(MsQuicApi.Api.Registration, s_connectionDelegate, GCHandle.ToIntPtr(_state.StateGCHandle), out _state.Handle);
            QuicExceptionHelpers.ThrowIfFailed(status, "Could not open the connection.");
        }
        catch
        {
            _state.StateGCHandle.Free();
            throw;
        }
        _state.TraceId = MsQuicTraceHelper.GetTraceId(_state.Handle);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{TraceId()} Outbound connection created", ".ctor");
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicConnection._configuration, System.Net.Quic.Implementations.MsQuic.MsQuicConnection._remoteEndPoint, System.Net.Quic.Implementations.MsQuic.MsQuicConnection._state, System.Runtime.InteropServices.GCHandle.Alloc(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.Runtime.InteropServices.GCHandle.Free(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicTraceHelper.GetTraceId(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.Handle, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.options, System.Net.Quic.Implementations.MsQuic.MsQuicConnection.s_connectionDelegate, System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.StateGCHandle, System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(), and System.Runtime.InteropServices.GCHandle.ToIntPtr().