Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicConnection.Dispose
Dispose() [2/2]
void System.Net.Quic.Implementations.MsQuic.MsQuicConnection.Dispose (bool disposing) inline private
Definition at line 662 of file MsQuicConnection.cs.
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0)
        {
            return;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(_state, $"{TraceId()} Connection disposing {disposing}", "Dispose");
        }
        if (_state.Handle != null && !_state.Handle.IsInvalid && !_state.Handle.IsClosed)
        {
            MsQuicApi.Api.ConnectionShutdownDelegate(_state.Handle, QUIC_CONNECTION_SHUTDOWN_FLAGS.SILENT, 0L);
        }
        bool flag = false;
        lock (_state)
        {
            _state.Connection = null;
            if (_state.StreamCount == 0)
            {
                flag = true;
            }
            else
            {
                _state.SetClosing();
            }
        }
        FlushAcceptQueue().GetAwaiter().GetResult();
        _configuration?.Dispose();
        if (flag)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(_state, $"{TraceId()} Connection releasing handle", "Dispose");
            }
            _state.Handle?.Dispose();
        }
    }
References System.Net.Quic.Implementations.MsQuic.MsQuicConnection._configuration, System.Net.Quic.Implementations.MsQuic.MsQuicConnection._disposed, System.Net.Quic.Implementations.MsQuic.MsQuicConnection._state, System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.Api, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Threading.Interlocked.Exchange(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.FlushAcceptQueue(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.Handle, System.Net.NetEventSource.Info(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConnectionHandle.IsInvalid, System.L, System.Net.NetEventSource.Log, System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.SetClosing(), and System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.StreamCount.