Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventPeerCertificateReceived
HandleEventPeerCertificateReceived()
static unsafe uint System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventPeerCertificateReceived (State state, ref MsQuicNativeMethods::ConnectionEvent connectionEvent) inline static private
Definition at line 319 of file MsQuicConnection.cs.
    {
        SslPolicyErrors sslPolicyErrors = SslPolicyErrors.None;
        X509Chain x509Chain = null;
        X509Certificate2 x509Certificate = null;
        X509Certificate2Collection x509Certificate2Collection = null;
        try
        {
            if (connectionEvent.Data.PeerCertificateReceived.PlatformCertificateHandle != IntPtr.Zero)
            {
                if (OperatingSystem.IsWindows())
                {
                    x509Certificate = new X509Certificate2(connectionEvent.Data.PeerCertificateReceived.PlatformCertificateHandle);
                }
                else
                {
                    ReadOnlySpan<MsQuicNativeMethods.QuicBuffer> readOnlySpan = new ReadOnlySpan<MsQuicNativeMethods.QuicBuffer>((void*)connectionEvent.Data.PeerCertificateReceived.PlatformCertificateHandle, sizeof(MsQuicNativeMethods.QuicBuffer));
                    x509Certificate = new X509Certificate2(new ReadOnlySpan<byte>(readOnlySpan[0].Buffer, (int)readOnlySpan[0].Length));
                    if (connectionEvent.Data.PeerCertificateReceived.PlatformCertificateChainHandle != IntPtr.Zero)
                    {
                        readOnlySpan = new ReadOnlySpan<MsQuicNativeMethods.QuicBuffer>((void*)connectionEvent.Data.PeerCertificateReceived.PlatformCertificateChainHandle, sizeof(MsQuicNativeMethods.QuicBuffer));
                        if (readOnlySpan[0].Length != 0 && readOnlySpan[0].Buffer != null)
{
                            x509Certificate2Collection = new X509Certificate2Collection();
                            x509Certificate2Collection.Import(new ReadOnlySpan<byte>(readOnlySpan[0].Buffer, (int)readOnlySpan[0].Length));
                        }
                    }
                }
            }
            if (x509Certificate == null)
            {
                if (System.Net.NetEventSource.Log.IsEnabled() && state.RemoteCertificateRequired)
                {
                    System.Net.NetEventSource.Error(state, $"{state.TraceId} Remote certificate required, but no remote certificate received", "HandleEventPeerCertificateReceived");
                }
                sslPolicyErrors |= SslPolicyErrors.RemoteCertificateNotAvailable;
            }
            else
            {
                x509Chain = new X509Chain();
                x509Chain.ChainPolicy.RevocationMode = state.RevocationMode;
                x509Chain.ChainPolicy.RevocationFlag = X509RevocationFlag.ExcludeRoot;
                x509Chain.ChainPolicy.ApplicationPolicy.Add(state.IsServer ? s_clientAuthOid : s_serverAuthOid);
                if (x509Certificate2Collection != null && x509Certificate2Collection.Count > 1)
                {
                    x509Chain.ChainPolicy.ExtraStore.AddRange(x509Certificate2Collection);
                }
                sslPolicyErrors |= System.Net.CertificateValidation.BuildChainAndVerifyProperties(x509Chain, x509Certificate, checkCertName: true, state.IsServer, state.TargetHost);
            }
            if (!state.RemoteCertificateRequired)
            {
                sslPolicyErrors &= ~SslPolicyErrors.RemoteCertificateNotAvailable;
            }
            state.RemoteCertificate = x509Certificate;
            if (state.RemoteCertificateValidationCallback != null)
            {
                bool success = state.RemoteCertificateValidationCallback(state, x509Certificate, x509Chain, sslPolicyErrors);
                state.RemoteCertificateValidationCallback = (object _, X509Certificate _, X509Chain _, SslPolicyErrors _) => success;
                if (!success && System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(state, $"{state.TraceId} Remote certificate rejected by verification callback", "HandleEventPeerCertificateReceived");
                }
                if (!success)
                {
                    if (state.IsServer)
                    {
                        return 2151743490u;
                    }
                    throw new AuthenticationException(System.SR.net_quic_cert_custom_validation);
                }
                return 0u;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(state, $"{state.TraceId} Certificate validation for '${x509Certificate?.Subject}' finished with ${sslPolicyErrors}", "HandleEventPeerCertificateReceived");
            }
            if (sslPolicyErrors != 0)
            {
                if (state.IsServer)
                {
                    return 2151743488u;
                }
                throw new AuthenticationException(System.SR.Format(System.SR.net_quic_cert_chain_validation, sslPolicyErrors));
            }
            return 0u;
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(state, $"{state.TraceId} Certificate validation failed ${ex.Message}", "HandleEventPeerCertificateReceived");
            }
            throw;
        }
    }
References System.Security.Cryptography.OidCollection.Add(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.AddRange(), System.Security.Cryptography.X509Certificates.X509ChainPolicy.ApplicationPolicy, System.Net.CertificateValidation.BuildChainAndVerifyProperties(), System.Security.Cryptography.X509Certificates.X509Chain.ChainPolicy, System.Collections.CollectionBase.Count, System.Net.NetEventSource.Error(), System.Security.Cryptography.X509Certificates.X509ChainPolicy.ExtraStore, System.SR.Format(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(), System.Net.NetEventSource.Info(), System.OperatingSystem.IsWindows(), System.Net.NetEventSource.Log, System.SR.net_quic_cert_chain_validation, System.SR.net_quic_cert_custom_validation, System.Net.Quic.Implementations.MsQuic.MsQuicConnection.s_clientAuthOid, System.Net.Quic.Implementations.MsQuic.MsQuicConnection.s_serverAuthOid, System.state, and System.IntPtr.Zero.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler().