Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler
NativeCallbackHandler()
static uint System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler (IntPtr connection, IntPtr context, ref MsQuicNativeMethods::ConnectionEvent connectionEvent) inline static private
Definition at line 597 of file MsQuicConnection.cs.
    {
        State state = (State)GCHandle.FromIntPtr(context).Target;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(state, $"{state.TraceId} Connection received event {connectionEvent.Type}", "NativeCallbackHandler");
        }
        try
        {
            return connectionEvent.Type switch
            {
                QUIC_CONNECTION_EVENT_TYPE.CONNECTED => HandleEventConnected(state, ref connectionEvent),
                QUIC_CONNECTION_EVENT_TYPE.SHUTDOWN_INITIATED_BY_TRANSPORT => HandleEventShutdownInitiatedByTransport(state, ref connectionEvent),
                QUIC_CONNECTION_EVENT_TYPE.SHUTDOWN_INITIATED_BY_PEER => HandleEventShutdownInitiatedByPeer(state, ref connectionEvent),
                QUIC_CONNECTION_EVENT_TYPE.SHUTDOWN_COMPLETE => HandleEventShutdownComplete(state, ref connectionEvent),
                QUIC_CONNECTION_EVENT_TYPE.PEER_STREAM_STARTED => HandleEventNewStream(state, ref connectionEvent),
                QUIC_CONNECTION_EVENT_TYPE.STREAMS_AVAILABLE => HandleEventStreamsAvailable(state, ref connectionEvent),
                QUIC_CONNECTION_EVENT_TYPE.PEER_CERTIFICATE_RECEIVED => HandleEventPeerCertificateReceived(state, ref connectionEvent),
                _ => 0u,
            };
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(state, $"{state.TraceId} Exception occurred during handling {connectionEvent.Type} connection callback: {ex}", "NativeCallbackHandler");
            }
            if (state.ConnectTcs != null)
            {
                state.ConnectTcs.TrySetException(ex);
                state.Connection = null;
                state.ConnectTcs = null;
            }
            return 2151743491u;
        }
    }
References System.Net.NetEventSource.Error(), System.Runtime.InteropServices.GCHandle.FromIntPtr(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventConnected(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventNewStream(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventPeerCertificateReceived(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownComplete(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByPeer(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventStreamsAvailable(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.state.