Terraria: System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport
HandleEventShutdownInitiatedByTransport()
static uint System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport (State state, ref MsQuicNativeMethods::ConnectionEvent connectionEvent) inline static private
Definition at line 237 of file MsQuicConnection.cs.
    {
        if (!state.Connected && state.ConnectTcs != null)
        {
            state.Connection = null;
            uint status = connectionEvent.Data.ShutdownInitiatedByTransport.Status;
            Exception currentStackTrace = QuicExceptionHelpers.CreateExceptionForHResult(status, "Connection has been shutdown by transport.");
            state.ConnectTcs.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(currentStackTrace));
            state.ConnectTcs = null;
        }
        state.AbortErrorCode = 0L;
        state.AcceptQueue.Writer.TryComplete();
        return 0u;
    }
References System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.CreateExceptionForHResult(), System.L, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), and System.state.
Referenced by System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler().