Terraria: Microsoft.Xna.Framework.Plane.Normalize
Normalize() [1/3]
void Microsoft.Xna.Framework.Plane.Normalize () inline
Definition at line 94 of file Plane.cs.
    {
        float num = Normal.X * Normal.X + Normal.Y * Normal.Y + Normal.Z * Normal.Z;
        if (!(Math.Abs(num - 1f) < 1.1920929E-07f))
        {
            float num2 = 1f / (float)Math.Sqrt(num);
            Normal.X *= num2;
            Normal.Y *= num2;
            Normal.Z *= num2;
            D *= num2;
        }
    }
References System.Math.Abs(), Microsoft.Xna.Framework.Plane.D, Microsoft.Xna.Framework.Plane.Normal, System.Math.Sqrt(), and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.Matrix.CreateReflection(), Microsoft.Xna.Framework.Matrix.CreateShadow(), and Microsoft.Xna.Framework.Matrix.CreateShadow().