Terraria: LegacySoundStyle.LegacySoundStyle
LegacySoundStyle() [1/3]
LegacySoundStyle.LegacySoundStyle (int soundId, int style, SoundType type = SoundType.Sound) inline
         : base(type)
     {
         _style = style;
         Variations = 1;
         SoundId = soundId;
     }
References _style, SoundId, and Variations.
Referenced by AsAmbient(), AsMusic(), AsSound(), WithPitchVariance(), and WithVolume().