Terraria: System.Xml.XPath.XPathNavigatorReader.MoveToAttribute
MoveToAttribute() [3/4]
override bool System.Xml.XPath.XPathNavigatorReader.MoveToAttribute (string name) inline
Definition at line 705 of file XPathNavigatorReader.cs.
    {
        int depth;
        XPathNavigator elemNav = GetElemNav(out depth);
        if (elemNav == null)
        {
            return false;
        }
        ValidateNames.SplitQName(name, out var prefix, out var lname);
        bool flag = false;
        if ((flag = prefix.Length == 0 && lname == "xmlns") || prefix == "xmlns")
        {
            if (flag)
            {
                lname = string.Empty;
            }
            if (!elemNav.MoveToFirstNamespace(XPathNamespaceScope.Local))
            {
                goto IL_00b3;
            }
            while (!(elemNav.LocalName == lname))
            {
                if (elemNav.MoveToNextNamespace(XPathNamespaceScope.Local))
                {
                    continue;
                }
                goto IL_00b3;
            }
        }
        else if (prefix.Length == 0)
        {
            if (!elemNav.MoveToAttribute(lname, string.Empty))
            {
                goto IL_00b3;
            }
        }
        else
        {
            if (!elemNav.MoveToFirstAttribute())
            {
                goto IL_00b3;
            }
            while (!(elemNav.LocalName == lname) || !(elemNav.Prefix == prefix))
            {
                if (elemNav.MoveToNextAttribute())
                {
                    continue;
                }
                goto IL_00b3;
            }
        }
        if (_state == State.InReadBinary)
        {
            _readBinaryHelper.Finish();
            _state = _savedState;
        }
        MoveToAttr(elemNav, depth + 1);
        return true;
        IL_00b3:
        return false;
    }
References System.Xml.XPath.XPathNavigatorReader._readBinaryHelper, System.Xml.XPath.XPathNavigatorReader._savedState, System.Xml.XPath.XPathNavigatorReader._state, System.Xml.Dictionary, System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XPath.XPathNavigatorReader.GetElemNav(), System.Xml.XPath.XPathNavigatorReader.MoveToAttr(), System.prefix, and System.Xml.ValidateNames.SplitQName().