Terraria: System.Xml.XPath.XPathNavigatorReader.MoveToAttribute
MoveToAttribute() [2/4]
override bool System.Xml.XPath.XPathNavigatorReader.MoveToAttribute (string localName, string namespaceName) inline
Definition at line 551 of file XPathNavigatorReader.cs.
    {
        if (localName == null)
        {
            throw new ArgumentNullException("localName");
        }
        int depth = _depth;
        XPathNavigator elemNav = GetElemNav(out depth);
        if (elemNav != null)
        {
            if (namespaceName == "http://www.w3.org/2000/xmlns/")
            {
                if (localName == "xmlns")
                {
                    localName = string.Empty;
                }
                if (!elemNav.MoveToFirstNamespace(XPathNamespaceScope.Local))
                {
                    goto IL_0078;
                }
                while (!(elemNav.LocalName == localName))
                {
                    if (elemNav.MoveToNextNamespace(XPathNamespaceScope.Local))
                    {
                        continue;
                    }
                    goto IL_0078;
                }
            }
            else
            {
                if (namespaceName == null)
                {
                    namespaceName = string.Empty;
                }
                if (!elemNav.MoveToAttribute(localName, namespaceName))
                {
                    goto IL_0078;
                }
            }
            if (_state == State.InReadBinary)
            {
                _readBinaryHelper.Finish();
                _state = _savedState;
            }
            MoveToAttr(elemNav, depth + 1);
            return true;
        }
        goto IL_0078;
        IL_0078:
        return false;
    }
References System.Xml.XPath.XPathNavigatorReader._depth, System.Xml.XPath.XPathNavigatorReader._readBinaryHelper, System.Xml.XPath.XPathNavigatorReader._savedState, System.Xml.XPath.XPathNavigatorReader._state, System.Xml.Dictionary, System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XPath.XPathNavigatorReader.GetElemNav(), and System.Xml.XPath.XPathNavigatorReader.MoveToAttr().