Terraria: System.Xml.XPath.XPathNavigatorReader.MoveToFirstAttribute
MoveToFirstAttribute()
override bool System.Xml.XPath.XPathNavigatorReader.MoveToFirstAttribute () inline
Definition at line 604 of file XPathNavigatorReader.cs.
    {
        int depth;
        XPathNavigator elemNav = GetElemNav(out depth);
        if (elemNav != null)
        {
            if (elemNav.MoveToFirstNamespace(XPathNamespaceScope.Local))
            {
                while (elemNav.MoveToNextNamespace(XPathNamespaceScope.Local))
                {
                }
            }
            else if (!elemNav.MoveToFirstAttribute())
            {
                goto IL_0028;
            }
            if (_state == State.InReadBinary)
            {
                _readBinaryHelper.Finish();
                _state = _savedState;
            }
            MoveToAttr(elemNav, depth + 1);
            return true;
        }
        goto IL_0028;
        IL_0028:
        return false;
    }
References System.Xml.XPath.XPathNavigatorReader._readBinaryHelper, System.Xml.XPath.XPathNavigatorReader._savedState, System.Xml.XPath.XPathNavigatorReader._state, System.Xml.Dictionary, System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XPath.XPathNavigatorReader.GetElemNav(), and System.Xml.XPath.XPathNavigatorReader.MoveToAttr().
Referenced by System.Xml.XPath.XPathNavigatorReader.MoveToNextAttribute().