Terraria: System.Xml.XPath.XPathNavigatorReader.Read
Read()
override bool System.Xml.XPath.XPathNavigatorReader.Read () inline
Definition at line 897 of file XPathNavigatorReader.cs.
    {
        _attrCount = -1;
        switch (_state)
        {
        case State.EOF:
        case State.Closed:
        case State.Error:
            return false;
        case State.Initial:
            _nav = _navToRead;
            _state = State.Content;
            if (_nav.NodeType == XPathNodeType.Root)
            {
                if (!_nav.MoveToFirstChild())
                {
                    SetEOF();
                    return false;
                }
                _readEntireDocument = true;
            }
            else if (XPathNodeType.Attribute == _nav.NodeType)
            {
                _state = State.Attribute;
            }
            _nodeType = ToXmlNodeType(_nav.NodeType);
            break;
        case State.Content:
            if (_nav.MoveToFirstChild())
            {
                _nodeType = ToXmlNodeType(_nav.NodeType);
                _depth++;
                _state = State.Content;
                break;
            }
            if (_nodeType == XmlNodeType.Element && !_nav.IsEmptyElement)
            {
                _nodeType = XmlNodeType.EndElement;
                _state = State.EndElement;
                break;
            }
            goto case State.EndElement;
        case State.EndElement:
            if (_depth == 0 && !_readEntireDocument)
            {
                SetEOF();
                return false;
            }
            if (_nav.MoveToNext())
            {
                _nodeType = ToXmlNodeType(_nav.NodeType);
                _state = State.Content;
                break;
            }
            if (_depth > 0 && _nav.MoveToParent())
            {
                _nodeType = XmlNodeType.EndElement;
                _state = State.EndElement;
                _depth--;
                break;
            }
            SetEOF();
            return false;
        case State.Attribute:
        case State.AttrVal:
            if (!_nav.MoveToParent())
            {
                SetEOF();
                return false;
            }
            _nodeType = ToXmlNodeType(_nav.NodeType);
            _depth--;
            if (_state == State.AttrVal)
            {
                _depth--;
            }
            goto case State.Content;
        case State.InReadBinary:
            _state = _savedState;
            _readBinaryHelper.Finish();
            return Read();
        }
        return true;
    }
References System.Xml.XPath.XPathNavigatorReader._attrCount, System.Xml.XPath.XPathNavigatorReader._depth, System.Xml.XPath.XPathNavigatorReader._nav, System.Xml.XPath.XPathNavigatorReader._navToRead, System.Xml.XPath.XPathNavigatorReader._nodeType, System.Xml.XPath.XPathNavigatorReader._readBinaryHelper, System.Xml.XPath.XPathNavigatorReader._readEntireDocument, System.Xml.XPath.XPathNavigatorReader._savedState, System.Xml.XPath.XPathNavigatorReader._state, System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XPath.XPathNavigator.IsEmptyElement, System.Xml.XPath.XPathNavigator.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.XPath.XPathNavigator.NodeType, System.Xml.XPath.XPathNavigatorReader.Read(), System.Xml.XPath.XPathNavigatorReader.SetEOF(), and System.Xml.XPath.XPathNavigatorReader.ToXmlNodeType().
Referenced by System.Xml.XPath.XPathNavigatorReader.Read().