Terraria: System.Xml.XPath.XPathNavigatorReader.GetNamespaceByIndex
GetNamespaceByIndex()
static string System.Xml.XPath.XPathNavigatorReader.GetNamespaceByIndex (XPathNavigator nav, int index, out int count) inline static private
Definition at line 496 of file XPathNavigatorReader.cs.
    {
        string value = nav.Value;
        string result = null;
        if (nav.MoveToNextNamespace(XPathNamespaceScope.Local))
        {
            result = GetNamespaceByIndex(nav, index, out count);
        }
        else
        {
            count = 0;
        }
        if (count == index)
        {
            result = value;
        }
        count++;
        return result;
    }
References System.count, System.Xml.XPath.XPathNavigatorReader.GetNamespaceByIndex(), System.index, System.Xml.XPath.XPathNavigator.MoveToNextNamespace(), System.value, and System.Xml.XPath.XPathItem.Value.
Referenced by System.Xml.XPath.XPathNavigatorReader.GetAttribute(), and System.Xml.XPath.XPathNavigatorReader.GetNamespaceByIndex().