Terraria: System.Xml.XPath.XPathNavigatorReader.MoveToAttr
MoveToAttr()
void System.Xml.XPath.XPathNavigatorReader.MoveToAttr (XPathNavigator nav, int depth) inline private
Definition at line 386 of file XPathNavigatorReader.cs.
    {
        _nav.MoveTo(nav);
        _depth = depth;
        _nodeType = XmlNodeType.Attribute;
        _state = State.Attribute;
    }
References System.Xml.XPath.XPathNavigatorReader._depth, System.Xml.XPath.XPathNavigatorReader._nav, System.Xml.XPath.XPathNavigatorReader._nodeType, System.Xml.XPath.XPathNavigatorReader._state, and System.Xml.XPath.XPathNavigator.MoveTo().
Referenced by System.Xml.XPath.XPathNavigatorReader.MoveToAttribute(), System.Xml.XPath.XPathNavigatorReader.MoveToAttribute(), and System.Xml.XPath.XPathNavigatorReader.MoveToFirstAttribute().