Terraria: System.Xml.XPath.XPathNavigatorReader.MoveToNextAttribute
MoveToNextAttribute()
override bool System.Xml.XPath.XPathNavigatorReader.MoveToNextAttribute () inline
Definition at line 633 of file XPathNavigatorReader.cs.
    {
        switch (_state)
        {
        case State.Content:
            return MoveToFirstAttribute();
        case State.Attribute:
        {
            if (XPathNodeType.Attribute == _nav.NodeType)
            {
                return _nav.MoveToNextAttribute();
            }
            XPathNavigator xPathNavigator = _nav.Clone();
            if (!xPathNavigator.MoveToParent())
            {
                return false;
            }
            if (!xPathNavigator.MoveToFirstNamespace(XPathNamespaceScope.Local))
            {
                return false;
            }
            if (xPathNavigator.IsSamePosition(_nav))
            {
                xPathNavigator.MoveToParent();
                if (!xPathNavigator.MoveToFirstAttribute())
                {
                    return false;
                }
                _nav.MoveTo(xPathNavigator);
                return true;
            }
            XPathNavigator xPathNavigator2 = xPathNavigator.Clone();
            while (true)
            {
                if (!xPathNavigator.MoveToNextNamespace(XPathNamespaceScope.Local))
                {
                    return false;
                }
                if (xPathNavigator.IsSamePosition(_nav))
                {
                    break;
                }
                xPathNavigator2.MoveTo(xPathNavigator);
            }
            _nav.MoveTo(xPathNavigator2);
            return true;
        }
        case State.AttrVal:
            _depth--;
            _state = State.Attribute;
            if (!MoveToNextAttribute())
            {
                _depth++;
                _state = State.AttrVal;
                return false;
            }
            _nodeType = XmlNodeType.Attribute;
            return true;
        case State.InReadBinary:
            _state = _savedState;
            if (!MoveToNextAttribute())
            {
                _state = State.InReadBinary;
                return false;
            }
            _readBinaryHelper.Finish();
            return true;
        default:
            return false;
        }
    }
References System.Xml.XPath.XPathNavigatorReader._depth, System.Xml.XPath.XPathNavigatorReader._nav, System.Xml.XPath.XPathNavigatorReader._nodeType, System.Xml.XPath.XPathNavigatorReader._readBinaryHelper, System.Xml.XPath.XPathNavigatorReader._savedState, System.Xml.XPath.XPathNavigatorReader._state, System.Xml.XPath.XPathNavigator.Clone(), System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XPath.XPathNavigator.MoveTo(), System.Xml.XPath.XPathNavigatorReader.MoveToFirstAttribute(), System.Xml.XPath.XPathNavigator.MoveToNextAttribute(), System.Xml.XPath.XPathNavigatorReader.MoveToNextAttribute(), and System.Xml.XPath.XPathNavigator.NodeType.
Referenced by System.Xml.XPath.XPathNavigatorReader.MoveToNextAttribute().