Terraria: System.Security.Claims.ClaimsIdentity.Initialize
Initialize()
void System.Security.Claims.ClaimsIdentity.Initialize (BinaryReader reader) inline private inherited
Definition at line 454 of file ClaimsIdentity.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        SerializationMask serializationMask = (SerializationMask)reader.ReadInt32();
        int num = 0;
        int num2 = reader.ReadInt32();
        if ((serializationMask & SerializationMask.AuthenticationType) == SerializationMask.AuthenticationType)
        {
            _authenticationType = reader.ReadString();
            num++;
        }
        if ((serializationMask & SerializationMask.BootstrapConext) == SerializationMask.BootstrapConext)
        {
            _bootstrapContext = reader.ReadString();
            num++;
        }
        if ((serializationMask & SerializationMask.NameClaimType) == SerializationMask.NameClaimType)
        {
            _nameClaimType = reader.ReadString();
            num++;
        }
        else
        {
            _nameClaimType = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name";
        }
        if ((serializationMask & SerializationMask.RoleClaimType) == SerializationMask.RoleClaimType)
        {
            _roleClaimType = reader.ReadString();
            num++;
        }
        else
        {
            _roleClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role";
        }
        if ((serializationMask & SerializationMask.HasLabel) == SerializationMask.HasLabel)
        {
            _label = reader.ReadString();
            num++;
        }
        if ((serializationMask & SerializationMask.HasClaims) == SerializationMask.HasClaims)
        {
            int num3 = reader.ReadInt32();
            for (int i = 0; i < num3; i++)
            {
                _instanceClaims.Add(CreateClaim(reader));
            }
            num++;
        }
        if ((serializationMask & SerializationMask.Actor) == SerializationMask.Actor)
        {
            _actor = new ClaimsIdentity(reader);
            num++;
        }
        if ((serializationMask & SerializationMask.UserData) == SerializationMask.UserData)
        {
            int count = reader.ReadInt32();
            _userSerializationData = reader.ReadBytes(count);
            num++;
        }
        for (int j = num; j < num2; j++)
        {
            reader.ReadString();
        }
    }
References System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), System.Security.Claims.ClaimsIdentity._actor, System.Security.Claims.ClaimsIdentity._authenticationType, System.Security.Claims.ClaimsIdentity._bootstrapContext, System.Security.Claims.ClaimsIdentity._instanceClaims, System.Security.Claims.ClaimsIdentity._label, System.Security.Claims.ClaimsIdentity._nameClaimType, System.Security.Claims.ClaimsIdentity._roleClaimType, System.Security.Claims.ClaimsIdentity._userSerializationData, System.Collections.Generic.List< T >.Add(), System.count, System.Security.Claims.ClaimsIdentity.CreateClaim(), System.Runtime.Serialization.Dictionary, System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt32(), and System.IO.BinaryReader.ReadString().
Referenced by System.Security.Claims.ClaimsIdentity.ClaimsIdentity().