Terraria: System.Security.Claims.ClaimsIdentity.ClaimsIdentity
ClaimsIdentity() [9/13]
System.Security.Claims.ClaimsIdentity.ClaimsIdentity (IIdentity? identity, IEnumerable< Claim >? claims, string? authenticationType, string? nameType, string? roleType) inline
Definition at line 163 of file ClaimsIdentity.cs.
    {
        ClaimsIdentity claimsIdentity = identity as ClaimsIdentity;
        _authenticationType = ((identity != null && string.IsNullOrEmpty(authenticationType)) ? identity.AuthenticationType : authenticationType);
        _nameClaimType = ((!string.IsNullOrEmpty(nameType)) ? nameType : ((claimsIdentity != null) ? claimsIdentity._nameClaimType : "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"));
        _roleClaimType = ((!string.IsNullOrEmpty(roleType)) ? roleType : ((claimsIdentity != null) ? claimsIdentity._roleClaimType : "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"));
        if (claimsIdentity != null)
        {
            _label = claimsIdentity._label;
            _bootstrapContext = claimsIdentity._bootstrapContext;
            if (claimsIdentity.Actor != null)
            {
                if (IsCircular(claimsIdentity.Actor))
                {
                    throw new InvalidOperationException(System.SR.InvalidOperationException_ActorGraphCircular);
                }
                _actor = claimsIdentity.Actor;
            }
            SafeAddClaims(claimsIdentity._instanceClaims);
        }
        else if (identity != null && !string.IsNullOrEmpty(identity.Name))
        {
            SafeAddClaim(new Claim(_nameClaimType, identity.Name, "http://www.w3.org/2001/XMLSchema#string", "LOCAL AUTHORITY", "LOCAL AUTHORITY", this));
        }
        if (claims != null)
        {
            SafeAddClaims(claims);
        }
    }
References System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), System.Security.Claims.ClaimsIdentity._actor, System.Security.Claims.ClaimsIdentity._authenticationType, System.Security.Claims.ClaimsIdentity._bootstrapContext, System.Security.Claims.ClaimsIdentity._label, System.Security.Claims.ClaimsIdentity._nameClaimType, System.Security.Claims.ClaimsIdentity._roleClaimType, System.Security.Principal.IIdentity.AuthenticationType, System.Runtime.Serialization.Dictionary, System.SR.InvalidOperationException_ActorGraphCircular, System.Security.Claims.ClaimsIdentity.IsCircular(), System.Security.Principal.IIdentity.Name, System.Security.Claims.ClaimsIdentity.SafeAddClaim(), and System.Security.Claims.ClaimsIdentity.SafeAddClaims().