Terraria: UIAchievementsMenu.OnActivate
OnActivate()
override void UIAchievementsMenu.OnActivate () inline virtual
Reimplemented from UIElement.
     {
         InitializePage();
         if (Main.gameMenu)
         {
             _outerContainer.Top.Set(220f, 0f);
             _outerContainer.Height.Set(-220f, 1f);
         }
         else
         {
             _outerContainer.Top.Set(120f, 0f);
             _outerContainer.Height.Set(-120f, 1f);
         }
         _achievementsList.UpdateOrder();
         if (PlayerInput.UsingGamepadUI)
         {
             UILinkPointNavigator.ChangePoint(3002);
         }
     }
References _achievementsList, _outerContainer, UILinkPointNavigator.ChangePoint(), Main.gameMenu, UIElement.Height, InitializePage(), StyleDimension.Set(), UIElement.Top, UIList.UpdateOrder(), and PlayerInput.UsingGamepadUI.