Terraria: UIAchievementsMenu.InitializePage
InitializePage()
void UIAchievementsMenu.InitializePage () inline
     {
         RemoveAllChildren();
         _categoryButtons.Clear();
         _achievementElements.Clear();
         _achievementsList = null;
         bool flag = true;
         int num = flag.ToInt() * 100;
         UIElement uIElement = new UIElement();
         uIElement.Width.Set(0f, 0.8f);
         uIElement.MaxWidth.Set(800f + (float)num, 0f);
         uIElement.MinWidth.Set(600f + (float)num, 0f);
         uIElement.Top.Set(220f, 0f);
         uIElement.Height.Set(-220f, 1f);
         uIElement.HAlign = 0.5f;
         _outerContainer = uIElement;
         Append(uIElement);
         UIPanel uIPanel = new UIPanel();
         uIPanel.Width.Set(0f, 1f);
         uIPanel.Height.Set(-110f, 1f);
         uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
         uIPanel.PaddingTop = 0f;
         uIElement.Append(uIPanel);
         _achievementsList = new UIList();
         _achievementsList.Width.Set(-25f, 1f);
         _achievementsList.Height.Set(-50f, 1f);
         _achievementsList.Top.Set(50f, 0f);
         _achievementsList.ListPadding = 5f;
         uIPanel.Append(_achievementsList);
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Achievements"), 1f, large: true);
         uITextPanel.HAlign = 0.5f;
         uITextPanel.Top.Set(-33f, 0f);
         uITextPanel.SetPadding(13f);
         uITextPanel.BackgroundColor = new Color(73, 94, 171);
         uIElement.Append(uITextPanel);
         UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true);
         uITextPanel2.Width.Set(-10f, 0.5f);
         uITextPanel2.Height.Set(50f, 0f);
         uITextPanel2.VAlign = 1f;
         uITextPanel2.HAlign = 0.5f;
         uITextPanel2.Top.Set(-45f, 0f);
         uITextPanel2.OnMouseOver += FadedMouseOver;
         uITextPanel2.OnMouseOut += FadedMouseOut;
         uITextPanel2.OnLeftClick += GoBackClick;
         uIElement.Append(uITextPanel2);
         _backpanel = uITextPanel2;
         List<Achievement> list = Main.Achievements.CreateAchievementsList();
         for (int i = 0; i < list.Count; i++)
         {
             UIAchievementListItem item = new UIAchievementListItem(list[i], flag);
             _achievementsList.Add(item);
             _achievementElements.Add(item);
         }
         UIScrollbar uIScrollbar = new UIScrollbar();
         uIScrollbar.SetView(100f, 1000f);
         uIScrollbar.Height.Set(-50f, 1f);
         uIScrollbar.Top.Set(50f, 0f);
         uIScrollbar.HAlign = 1f;
         uIPanel.Append(uIScrollbar);
         _achievementsList.SetScrollbar(uIScrollbar);
         UIElement uIElement2 = new UIElement();
         uIElement2.Width.Set(0f, 1f);
         uIElement2.Height.Set(32f, 0f);
         uIElement2.Top.Set(10f, 0f);
         Asset<Texture2D> texture = Main.Assets.Request<Texture2D>("Images/UI/Achievement_Categories", (AssetRequestMode)1);
         for (int j = 0; j < 4; j++)
         {
             UIToggleImage uIToggleImage = new UIToggleImage(texture, 32, 32, new Point(34 * j, 0), new Point(34 * j, 34));
             uIToggleImage.Left.Set(j * 36 + 8, 0f);
             uIToggleImage.SetState(value: true);
             uIToggleImage.OnLeftClick += FilterList;
             _categoryButtons.Add(uIToggleImage);
             uIElement2.Append(uIToggleImage);
         }
         uIPanel.Append(uIElement2);
     }
References UIElement.UIElement(), _achievementElements, _achievementsList, _backpanel, _categoryButtons, _outerContainer, Main.Achievements, UIList.Add(), UIElement.Append(), Main.Assets, UIPanel.BackgroundColor, Color, AchievementManager.CreateAchievementsList(), FadedMouseOut(), FadedMouseOver(), FilterList(), Language.GetText(), GoBackClick(), UIElement.HAlign, UIElement.Height, UIElement.Left, UIList.ListPadding, UIElement.MaxWidth, UIElement.MinWidth, UIElement.OnLeftClick, UIElement.PaddingTop, UIElement.RemoveAllChildren(), StyleDimension.Set(), UIList.SetScrollbar(), UIToggleImage.SetState(), UIScrollbar.SetView(), UIElement.Top, and UIElement.Width.
Referenced by OnActivate().