Terraria: System.Threading.ManualResetEventSlim.Wait
Wait() [1/6]
void System.Threading.ManualResetEventSlim.Wait () inline inherited
Definition at line 171 of file ManualResetEventSlim.cs.
    {
        Wait(-1, CancellationToken.None);
    }
References System.Threading.CancellationToken.None, and System.Threading.ManualResetEventSlim.Wait().
Referenced by System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.Barrier.AddParticipants(), System.Net.FileWebRequest.CreateResponse(), System.Threading.Barrier.DiscontinuousWait(), System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >.MoveNextSlowPath(), System.Net.NetworkInformation.Ping.SendAsyncCancel(), System.Threading.ManualResetEventSlim.Wait(), System.Threading.ManualResetEventSlim.Wait(), System.Threading.ManualResetEventSlim.Wait(), System.Threading.CountdownEvent.Wait(), System.Threading.ManualResetEventSlim.Wait(), System.Threading.ManualResetEventSlim.Wait(), and System.Linq.Parallel.AsynchronousChannel< T >.WaitUntilNonFull().