Terraria: System.Xml.Schema.XsdDateTime.Parser.ParseTime
ParseTime()
bool System.Xml.Schema.XsdDateTime.Parser.ParseTime (ref int start) inline private
Definition at line 186 of file XsdDateTime.cs.
        {
            if (Parse2Dig(start, ref hour) && hour < 24 && ParseChar(start + s_lzHH, ':') && Parse2Dig(start + s_lzHH_, ref minute) && minute < 60 && ParseChar(start + s_lzHH_mm, ':') && Parse2Dig(start + s_lzHH_mm_, ref second) && second < 60)
            {
                start += s_lzHH_mm_ss;
                if (ParseChar(start, '.'))
                {
                    fraction = 0;
                    int num = 0;
                    int num2 = 0;
                    while (++start < _length)
                    {
                        int num3 = _text[start] - 48;
                        if (9u < (uint)num3)
{
                            break;
                        }
                        if (num < 7)
{
                            fraction = fraction * 10 + num3;
                        }
                        else if (num == 7)
{
                            if (5 < num3)
{
                                num2 = 1;
                            }
                            else if (num3 == 5)
{
                                num2 = -1;
                            }
                        }
                        else if (num2 < 0 && num3 != 0)
{
                            num2 = 1;
                        }
                        num++;
                    }
                    if (num < 7)
                    {
                        if (num == 0)
{
                            return false;
                        }
                        fraction *= s_power10[7 - num];
                    }
                    else
                    {
                        if (num2 < 0)
{
                            num2 = fraction & 1;
                        }
                        fraction += num2;
                    }
                }
                return true;
            }
            hour = 0;
            return false;
        }
References System.Xml.Schema.XsdDateTime.Parser._length, System.Xml.Schema.XsdDateTime.Parser._text, System.Xml.Dictionary, System.Xml.Schema.XsdDateTime.Parser.fraction, System.Xml.Schema.XsdDateTime.Parser.hour, System.Xml.Schema.XsdDateTime.Parser.minute, System.Xml.Schema.XsdDateTime.Parser.Parse2Dig(), System.Xml.Schema.XsdDateTime.Parser.ParseChar(), System.Xml.Schema.XsdDateTime.s_lzHH, System.Xml.Schema.XsdDateTime.s_lzHH_, System.Xml.Schema.XsdDateTime.s_lzHH_mm, System.Xml.Schema.XsdDateTime.s_lzHH_mm_, System.Xml.Schema.XsdDateTime.s_lzHH_mm_ss, System.Xml.Schema.XsdDateTime.Parser.s_power10, System.Xml.Schema.XsdDateTime.Parser.second, and System.start.
Referenced by System.Xml.Schema.XsdDateTime.Parser.ParseTimeAndWhitespace(), and System.Xml.Schema.XsdDateTime.Parser.ParseTimeAndZoneAndWhitespace().