Terraria: System.Xml.Schema.XsdDateTime.Parser.ParseTimeAndZoneAndWhitespace
ParseTimeAndZoneAndWhitespace()
bool System.Xml.Schema.XsdDateTime.Parser.ParseTimeAndZoneAndWhitespace (int start) inline private
Definition at line 164 of file XsdDateTime.cs.
        {
            if (ParseTime(ref start) && ParseZoneAndWhitespace(start))
            {
                return true;
            }
            return false;
        }
References System.Xml.Dictionary, System.Xml.Schema.XsdDateTime.Parser.ParseTime(), System.Xml.Schema.XsdDateTime.Parser.ParseZoneAndWhitespace(), and System.start.
Referenced by System.Xml.Schema.XsdDateTime.Parser.Parse().