Terraria: System.Xml.Schema.XsdDateTime.Parser.ParseZoneAndWhitespace
ParseZoneAndWhitespace()
bool System.Xml.Schema.XsdDateTime.Parser.ParseZoneAndWhitespace (int start) inline private
Definition at line 247 of file XsdDateTime.cs.
        {
            if (start < _length)
            {
                char c = _text[start];
                if (c == 'Z' || c == 'z')
                {
                    kind = XsdDateTimeKind.Zulu;
                    start++;
                }
                else if (start + 5 < _length && Parse2Dig(start + s_Lz_, ref zoneHour) && zoneHour <= 99 && ParseChar(start + s_lz_zz, ':') && Parse2Dig(start + s_lz_zz_, ref zoneMinute) && zoneMinute <= 99)
                {
                    switch (c)
                    {
                    case '-':
                        kind = XsdDateTimeKind.LocalWestOfZulu;
                        start += s_lz_zz_zz;
                        break;
                    case '+':
                        kind = XsdDateTimeKind.LocalEastOfZulu;
                        start += s_lz_zz_zz;
                        break;
                    }
                }
            }
            while (start < _length && char.IsWhiteSpace(_text[start]))
            {
                start++;
            }
            return start == _length;
        }
References System.Xml.Schema.XsdDateTime.Parser._length, System.Xml.Schema.XsdDateTime.Parser._text, System.Xml.Dictionary, System.Xml.Schema.XsdDateTime.Parser.kind, System.Xml.Schema.XsdDateTime.Parser.Parse2Dig(), System.Xml.Schema.XsdDateTime.Parser.ParseChar(), System.Xml.Schema.XsdDateTime.s_Lz_, System.Xml.Schema.XsdDateTime.s_lz_zz, System.Xml.Schema.XsdDateTime.s_lz_zz_, System.Xml.Schema.XsdDateTime.s_lz_zz_zz, System.start, System.Xml.Schema.XsdDateTime.Parser.zoneHour, and System.Xml.Schema.XsdDateTime.Parser.zoneMinute.
Referenced by System.Xml.Schema.XsdDateTime.Parser.Parse(), and System.Xml.Schema.XsdDateTime.Parser.ParseTimeAndZoneAndWhitespace().