Terraria: HouseBuilder.PlaceChests
PlaceChests()
void HouseBuilder.PlaceChests () inline private inherited
     {
         if (_random.NextDouble() > ChestChance)
         {
             return;
         }
         bool flag = false;
         foreach (Rectangle room in Rooms)
         {
             int num = room.Height - 1 + room.Y;
             bool num2 = num > (int)Main.worldSurface;
             ushort chestTileType = (ushort)((num2 && UsesContainers2) ? 467 : 21);
             int style = (num2 ? ChestStyle : 0);
             for (int i = 0; i < 10; i++)
             {
                 if (flag = WorldGen.AddBuriedChest(_random.Next(2, room.Width - 2) + room.X, num, 0, notNearOtherChests: false, style, trySlope: false, chestTileType))
                 {
                     break;
                 }
             }
             if (flag)
             {
                 break;
             }
             for (int j = room.X + 2; j <= room.X + room.Width - 2; j++)
             {
                 if (flag = WorldGen.AddBuriedChest(j, num, 0, notNearOtherChests: false, style, trySlope: false, chestTileType))
                 {
                     break;
                 }
             }
             if (flag)
             {
                 break;
             }
         }
         if (!flag)
         {
             foreach (Rectangle room2 in Rooms)
             {
                 int num3 = room2.Y - 1;
                 bool num4 = num3 > (int)Main.worldSurface;
                 ushort chestTileType2 = (ushort)((num4 && UsesContainers2) ? 467 : 21);
                 int style2 = (num4 ? ChestStyle : 0);
                 for (int k = 0; k < 10; k++)
                 {
                     if (flag = WorldGen.AddBuriedChest(_random.Next(2, room2.Width - 2) + room2.X, num3, 0, notNearOtherChests: false, style2, trySlope: false, chestTileType2))
                     {
                         break;
                     }
                 }
                 if (flag)
                 {
                     break;
                 }
                 for (int l = room2.X + 2; l <= room2.X + room2.Width - 2; l++)
                 {
                     if (flag = WorldGen.AddBuriedChest(l, num3, 0, notNearOtherChests: false, style2, trySlope: false, chestTileType2))
                     {
                         break;
                     }
                 }
                 if (flag)
                 {
                     break;
                 }
             }
         }
         if (flag)
         {
             return;
         }
         for (int m = 0; m < 1000; m++)
         {
             int i2 = _random.Next(Rooms[0].X - 30, Rooms[0].X + 30);
             int num5 = _random.Next(Rooms[0].Y - 30, Rooms[0].Y + 30);
             bool num6 = num5 > (int)Main.worldSurface;
             ushort chestTileType3 = (ushort)((num6 && UsesContainers2) ? 467 : 21);
             int style3 = (num6 ? ChestStyle : 0);
             if (flag = WorldGen.AddBuriedChest(i2, num5, 0, notNearOtherChests: false, style3, trySlope: false, chestTileType3))
             {
                 break;
             }
         }
     }
References HouseBuilder._random, WorldGen.AddBuriedChest(), HouseBuilder.ChestChance, HouseBuilder.ChestStyle, UnifiedRandom.Next(), UnifiedRandom.NextDouble(), HouseBuilder.Rooms, HouseBuilder.UsesContainers2, Main.worldSurface, X, and Y.
Referenced by HouseBuilder.Place().