Terraria: HouseBuilder.FillRooms
FillRooms()
void HouseBuilder.FillRooms () inline private inherited
     {
         int x = 14;
         if (UsesTables2)
         {
             x = 469;
         }
         Point[] choices = new Point[7]
         {
             new Point(x, TableStyle),
             new Point(16, 0),
             new Point(18, WorkbenchStyle),
             new Point(86, 0),
             new Point(87, PianoStyle),
             new Point(94, 0),
             new Point(101, BookcaseStyle)
         };
         foreach (Rectangle room in Rooms)
         {
             int num = room.Width / 8;
             int num2 = room.Width / (num + 1);
             int num3 = _random.Next(2);
             for (int i = 0; i < num; i++)
             {
                 int num4 = (i + 1) * num2 + room.X;
                 switch (i + num3 % 2)
                 {
                 case 0:
                 {
                     int num5 = room.Y + Math.Min(room.Height / 2, room.Height - 5);
                     PaintingEntry paintingEntry = ((Type == HouseType.Desert) ? WorldGen.RandHousePictureDesert() : WorldGen.RandHousePicture());
                     WorldGen.PlaceTile(num4, num5, paintingEntry.tileType, mute: true, forced: false, -1, paintingEntry.style);
                     break;
                 }
                 case 1:
                 {
                     int num5 = room.Y + 1;
                     WorldGen.PlaceTile(num4, num5, 34, mute: true, forced: false, -1, _random.Next(6));
                     for (int j = -1; j < 2; j++)
                     {
                         for (int k = 0; k < 3; k++)
{
                             _tiles[j + num4, k + num5].frameX += 54;
                         }
                     }
                     break;
                 }
                 }
             }
             int num6 = room.Width / 8 + 3;
             WorldGen.SetupStatueList();
             while (num6 > 0)
             {
                 int num7 = _random.Next(room.Width - 3) + 1 + room.X;
                 int num8 = room.Y + room.Height - 2;
                 switch (_random.Next(4))
                 {
                 case 0:
                     WorldGen.PlaceSmallPile(num7, num8, _random.Next(31, 34), 1, 185);
                     break;
                 case 1:
                     WorldGen.PlaceTile(num7, num8, 186, mute: true, forced: false, -1, _random.Next(22, 26));
                     break;
                 case 2:
                 {
                     int num9 = _random.Next(2, GenVars.statueList.Length);
                     WorldGen.PlaceTile(num7, num8, GenVars.statueList[num9].X, mute: true, forced: false, -1, GenVars.statueList[num9].Y);
                     if (GenVars.StatuesWithTraps.Contains(num9))
                     {
                         WorldGen.PlaceStatueTrap(num7, num8);
                     }
                     break;
                 }
                 case 3:
                 {
                     Point point = Utils.SelectRandom(_random, choices);
                     WorldGen.PlaceTile(num7, num8, point.X, mute: true, forced: false, -1, point.Y);
                     break;
                 }
                 }
                 num6--;
             }
         }
     }
References HouseBuilder._random, HouseBuilder._tiles, HouseBuilder.BookcaseStyle, Tile.frameX, UnifiedRandom.Next(), HouseBuilder.PianoStyle, WorldGen.PlaceSmallPile(), WorldGen.PlaceStatueTrap(), WorldGen.PlaceTile(), WorldGen.RandHousePicture(), WorldGen.RandHousePictureDesert(), HouseBuilder.Rooms, WorldGen.SetupStatueList(), GenVars.statueList, GenVars.StatuesWithTraps, PaintingEntry.style, HouseBuilder.TableStyle, PaintingEntry.tileType, HouseBuilder.Type, HouseBuilder.UsesTables2, HouseBuilder.WorkbenchStyle, Point16.X, and Point16.Y.
Referenced by HouseBuilder.Place().