Terraria: System.Formats.Asn1.AsnWriter.Scope.Dispose
Dispose()
void System.Formats.Asn1.AsnWriter.Scope.Dispose () inline
Implements System.IDisposable.
Definition at line 106 of file AsnWriter.cs.
        {
            if (_writer == null || _writer._nestingStack.Count == 0)
            {
                return;
            }
            if (_writer._nestingStack.Peek() == _frame)
            {
                switch (_frame.ItemType)
                {
                case UniversalTagNumber.Set:
                    _writer.PopSetOf(_frame.Tag);
                    break;
                case UniversalTagNumber.Sequence:
                    _writer.PopSequence(_frame.Tag);
                    break;
                case UniversalTagNumber.OctetString:
                    _writer.PopOctetString(_frame.Tag);
                    break;
                default:
                    throw new InvalidOperationException();
                }
            }
            else if (_writer._nestingStack.Count > _depth && _writer._nestingStack.Contains(_frame))
            {
                throw new InvalidOperationException(System.SR.AsnWriter_PopWrongTag);
            }
        }
References System.Formats.Asn1.AsnWriter.Scope._depth, System.Formats.Asn1.AsnWriter.Scope._frame, System.Formats.Asn1.AsnWriter._nestingStack, System.Formats.Asn1.AsnWriter.Scope._writer, System.SR.AsnWriter_PopWrongTag, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Formats.Asn1.AsnWriter.StackFrame.ItemType, System.Formats.Asn1.AsnWriter.PopOctetString(), System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PopSetOf(), and System.Formats.Asn1.AsnWriter.StackFrame.Tag.