Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin
WriteSourceBegin()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin (string source) inline private
Definition at line 2238 of file XmlSerializationReaderILGen.cs.
    {
        if (ilg.TryGetVariable(source, out var variable))
        {
            Type variableType = ilg.GetVariableType(variable);
            if (CodeGenerator.IsNullableGenericType(variableType))
            {
                ilg.LoadAddress(variable);
            }
            return;
        }
        if (source.StartsWith("o.@", StringComparison.Ordinal))
        {
            ilg.LdlocAddress(ilg.GetLocal("o"));
            return;
        }
        Regex regex = XmlSerializationILGen.NewRegex("(?<locA1>[^ ]+) = .+EnsureArrayIndex[(](?<locA2>[^,]+), (?<locI1>[^,]+),[^;]+;(?<locA3>[^[]+)[[](?<locI2>[^+]+)[+][+][]]");
        Match match = regex.Match(source);
        if (match.Success)
        {
            LocalBuilder local = ilg.GetLocal(match.Groups["locA1"].Value);
            LocalBuilder local2 = ilg.GetLocal(match.Groups["locI1"].Value);
            Type elementType = local.LocalType.GetElementType();
            MethodInfo method = typeof(XmlSerializationReader).GetMethod("EnsureArrayIndex", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[3]
            {
                typeof(Array),
                typeof(int),
                typeof(Type)
            });
            ilg.Ldarg(0);
            ilg.Ldloc(local);
            ilg.Ldloc(local2);
            ilg.Ldc(elementType);
            ilg.Call(method);
            ilg.Castclass(local.LocalType);
            ilg.Stloc(local);
            ilg.Ldloc(local);
            ilg.Ldloc(local2);
            ilg.Dup();
            ilg.Ldc(1);
            ilg.Add();
            ilg.Stloc(local2);
            if (CodeGenerator.IsNullableGenericType(elementType) || elementType.IsValueType)
            {
                ilg.Ldelema(elementType);
            }
        }
        else if (source.EndsWith(".Add(", StringComparison.Ordinal))
        {
            int length = source.LastIndexOf(".Add(", StringComparison.Ordinal);
            LocalBuilder local3 = ilg.GetLocal(source.Substring(0, length));
            ilg.LdlocAddress(local3);
        }
        else
        {
            regex = XmlSerializationILGen.NewRegex("(?<a>[^[]+)[[](?<ia>.+)[]]");
            match = regex.Match(source);
            if (!match.Success)
            {
                throw Globals.NotSupported("Unexpected: " + source);
            }
            ilg.Load(ilg.GetVariable(match.Groups["a"].Value));
            ilg.Load(ilg.GetVariable(match.Groups["ia"].Value));
        }
    }
References System.Xml.Serialization.CodeGenerator.Add(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Castclass(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.Dup(), System.elementType, System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.CodeGenerator.GetVariable(), System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.IsNullableGenericType(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldelema(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.LdlocAddress(), System.length, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.LoadAddress(), System.match, System.Xml.Serialization.XmlSerializationILGen.NewRegex(), System.Xml.Serialization.Globals.NotSupported(), System.source, System.Xml.Serialization.CodeGenerator.Stloc(), and System.Xml.Serialization.CodeGenerator.TryGetVariable().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBeginTyped(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteText().