Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteText
WriteText()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteText (Member member) inline private
Definition at line 1920 of file XmlSerializationReaderILGen.cs.
    {
        TextAccessor text = member.Mapping.Text;
        if (text.Mapping is SpecialMapping)
        {
            SpecialMapping specialMapping = (SpecialMapping)text.Mapping;
            WriteSourceBeginTyped(member.ArraySource, specialMapping.TypeDesc);
            TypeKind kind = specialMapping.TypeDesc.Kind;
            if (kind == TypeKind.Node)
            {
                MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method2 = typeof(XmlReader).GetMethod("ReadContentAsString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method3 = typeof(XmlSerializationReader).GetMethod("get_Document", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method4 = typeof(XmlDocument).GetMethod("CreateTextNode", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                ilg.Ldarg(0);
                ilg.Call(method3);
                ilg.Ldarg(0);
                ilg.Call(method);
                ilg.Call(method2);
                ilg.Call(method4);
                WriteSourceEnd(member.ArraySource, specialMapping.TypeDesc.Type);
                return;
            }
            throw new InvalidOperationException(System.SR.XmlInternalError);
        }
        if (member.IsArrayLike)
        {
            WriteSourceBegin(member.ArraySource);
            if (text.Mapping.TypeDesc.CollapseWhitespace)
            {
                ilg.Ldarg(0);
            }
            MethodInfo method5 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            MethodInfo method6 = typeof(XmlReader).GetMethod("ReadContentAsString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldarg(0);
            ilg.Call(method5);
            ilg.Call(method6);
            if (text.Mapping.TypeDesc.CollapseWhitespace)
            {
                MethodInfo method7 = typeof(XmlSerializationReader).GetMethod("CollapseWhitespace", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                ilg.Call(method7);
            }
        }
        else if (text.Mapping.TypeDesc == base.StringTypeDesc || text.Mapping.TypeDesc.FormatterName == "String")
        {
            LocalBuilder local = ilg.GetLocal("tmp");
            MethodInfo method8 = typeof(XmlSerializationReader).GetMethod("ReadString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
            {
                typeof(string),
                typeof(bool)
            });
            ilg.Ldarg(0);
            ilg.Ldloc(local);
            ilg.Ldc(text.Mapping.TypeDesc.CollapseWhitespace);
            ilg.Call(method8);
            ilg.Stloc(local);
            WriteSourceBegin(member.ArraySource);
            ilg.Ldloc(local);
        }
        else
        {
            WriteSourceBegin(member.ArraySource);
            WritePrimitive(text.Mapping, "Reader.ReadString()");
        }
        WriteSourceEnd(member.ArraySource, text.Mapping.TypeDesc.Type);
    }
References System.Xml.Serialization.XmlSerializationReaderILGen.Member.ArraySource, System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationReaderILGen.Member.IsArrayLike, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.Mapping, System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.Xml.Serialization.AccessorMapping.Text, System.Xml.Serialization.XmlSerializationReaderILGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBeginTyped(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText().