Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf
WriteMemberElementsIf()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf (Member[] members, Member anyElement, string elementElseString) inline private
Definition at line 2022 of file XmlSerializationReaderILGen.cs.
    {
        int num = 0;
        bool flag = IsSequence(members);
        int num2 = 0;
        foreach (Member member in members)
        {
            if (member.Mapping.Xmlns != null || member.Mapping.Ignore || (flag && (member.Mapping.IsText || member.Mapping.IsAttribute)))
            {
                continue;
            }
            bool flag2 = true;
            ChoiceIdentifierAccessor choiceIdentifier = member.Mapping.ChoiceIdentifier;
            ElementAccessor[] elements = member.Mapping.Elements;
            for (int j = 0; j < elements.Length; j++)
            {
                ElementAccessor elementAccessor = elements[j];
                string ns = ((elementAccessor.Form == XmlSchemaForm.Qualified) ? elementAccessor.Namespace : "");
                if (!flag && elementAccessor.Any && (elementAccessor.Name == null || elementAccessor.Name.Length == 0))
                {
                    continue;
                }
                if (!flag2 || (!flag && num > 0))
                {
                    ilg.InitElseIf();
                }
                else if (flag)
                {
                    if (num2 > 0)
                    {
                        ilg.InitElseIf();
                    }
                    else
                    {
                        ilg.InitIf();
                    }
                    ilg.Ldloc("state");
                    ilg.Ldc(num2);
                    ilg.AndIf(Cmp.EqualTo);
                    ilg.InitIf();
                }
                else
                {
                    ilg.InitIf();
                }
                num++;
                flag2 = false;
                if (member.ParamsReadSource != null)
                {
                    ILGenParamsReadSource(member.ParamsReadSource);
                    ilg.Ldc(boolVar: false);
                    ilg.AndIf(Cmp.EqualTo);
                }
                Label label = ilg.DefineLabel();
                Label label2 = ilg.DefineLabel();
                if (member.Mapping.IsReturnValue)
                {
                    MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_IsReturnValue", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldarg(0);
                    ilg.Call(method);
                    ilg.Brtrue(label);
                }
                if (flag && elementAccessor.Any && elementAccessor.AnyNamespaces == null)
                {
                    ilg.Ldc(boolVar: true);
                }
                else
                {
                    WriteXmlNodeEqual("Reader", elementAccessor.Name, ns, doAndIf: false);
                }
                if (member.Mapping.IsReturnValue)
                {
                    ilg.Br_S(label2);
                    ilg.MarkLabel(label);
                    ilg.Ldc(boolVar: true);
                    ilg.MarkLabel(label2);
                }
                ilg.AndIf();
                WriteElement(member.ArraySource, member.ArrayName, member.ChoiceArraySource, elementAccessor, choiceIdentifier, (member.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite) ? member.CheckSpecifiedSource : null, member.IsList && member.Mapping.TypeDesc.IsNullable, member.Mapping.ReadOnly, member.FixupIndex, j);
                if (member.Mapping.IsReturnValue)
                {
                    MethodInfo method2 = typeof(XmlSerializationReader).GetMethod("set_IsReturnValue", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(bool) });
                    ilg.Ldarg(0);
                    ilg.Ldc(boolVar: false);
                    ilg.Call(method2);
                }
                if (member.ParamsReadSource != null)
                {
                    ILGenParamsReadSource(member.ParamsReadSource, value: true);
                }
            }
            if (flag)
            {
                if (member.IsArrayLike)
                {
                    ilg.Else();
                }
                else
                {
                    ilg.EndIf();
                }
                num2++;
                ilg.Ldc(num2);
                ilg.Stloc(ilg.GetLocal("state"));
                if (member.IsArrayLike)
                {
                    ilg.EndIf();
                }
            }
        }
        if (num > 0)
        {
            ilg.Else();
        }
        WriteMemberElementsElse(anyElement, elementElseString);
        if (num > 0)
        {
            ilg.EndIf();
        }
    }
References System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.ArrayName, System.Xml.Serialization.XmlSerializationReaderILGen.Member.ArraySource, System.Xml.Serialization.CodeGenerator.Br_S(), System.Xml.Serialization.CodeGenerator.Brtrue(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.MemberMapping.CheckSpecified, System.Xml.Serialization.XmlSerializationReaderILGen.Member.CheckSpecifiedSource, System.Xml.Serialization.XmlSerializationReaderILGen.Member.ChoiceArraySource, System.Xml.Serialization.AccessorMapping.ChoiceIdentifier, System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Xml.Serialization.AccessorMapping.Elements, System.Xml.Serialization.CodeGenerator.Else(), System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.FixupIndex, System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.AccessorMapping.Ignore, System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationReaderILGen.ILGenParamsReadSource(), System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Serialization.CodeGenerator.InitIf(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.IsArrayLike, System.Xml.Serialization.AccessorMapping.IsAttribute, System.Xml.Serialization.TypeDesc.IsNullable, System.Xml.Serialization.MemberMapping.IsReturnValue, System.Xml.Serialization.XmlSerializationReaderILGen.IsSequence(), System.Xml.Serialization.AccessorMapping.IsText, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.Mapping, System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.ParamsReadSource, System.Xml.Serialization.MemberMapping.ReadOnly, System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.AccessorMapping.TypeDesc, System.value, System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsElse(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual(), and System.Xml.Serialization.AccessorMapping.Xmlns.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements().