Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod
WriteNullableMethod()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod (NullableMapping nullableMapping) inline private
Definition at line 1089 of file XmlSerializationReaderILGen.cs.
    {
        base.MethodNames.TryGetValue(nullableMapping, out var value);
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(nullableMapping.TypeDesc.Type, GetMethodBuilder(value), new Type[1] { typeof(bool) }, new string[1] { "checkType" }, MethodAttributes.Private | MethodAttributes.HideBySig);
        LocalBuilder localBuilder = ilg.DeclareLocal(nullableMapping.TypeDesc.Type, "o");
        ilg.LoadAddress(localBuilder);
        ilg.InitObj(nullableMapping.TypeDesc.Type);
        MethodInfo method = typeof(XmlSerializationReader).GetMethod("ReadNull", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.If();
        ilg.Ldloc(localBuilder);
        ilg.Stloc(ilg.ReturnLocal);
        ilg.Br(ilg.ReturnLabel);
        ilg.EndIf();
        ElementAccessor elementAccessor = new ElementAccessor();
        elementAccessor.Mapping = nullableMapping.BaseMapping;
        elementAccessor.Any = false;
        elementAccessor.IsNullable = nullableMapping.BaseMapping.TypeDesc.IsNullable;
        WriteElement("o", null, null, elementAccessor, null, null, checkForNull: false, readOnly: false, -1, -1);
        ilg.Ldloc(localBuilder);
        ilg.Stloc(ilg.ReturnLocal);
        ilg.Br(ilg.ReturnLabel);
        ilg.MarkLabel(ilg.ReturnLabel);
        ilg.Ldloc(ilg.ReturnLocal);
        ilg.EndMethod();
    }
References System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.XmlSerializationILGen.GetMethodBuilder(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.InitObj(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.LoadAddress(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.ReturnLabel, System.Xml.Serialization.CodeGenerator.ReturnLocal, System.Xml.Serialization.CodeGenerator.Stloc(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.value, and System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateMethod().