Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.InitializeValueTypes
InitializeValueTypes()
void System.Xml.Serialization.XmlSerializationReaderILGen.InitializeValueTypes (string arrayName, MemberMapping[] mappings) inline private
Definition at line 573 of file XmlSerializationReaderILGen.cs.
    {
        for (int i = 0; i < mappings.Length; i++)
        {
            if (mappings[i].TypeDesc.IsValueType)
            {
                LocalBuilder local = ilg.GetLocal(arrayName);
                ilg.Ldloc(local);
                ilg.Ldc(i);
                base.RaCodeGen.ILGenForCreateInstance(ilg, mappings[i].TypeDesc.Type, ctorInaccessible: false, cast: false);
                ilg.ConvertValue(mappings[i].TypeDesc.Type, typeof(object));
                ilg.Stelem(local.LocalType.GetElementType());
            }
        }
    }
References System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.GetLocal(), System.Text.RegularExpressions.i, System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.TypeDesc.IsValueType, System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Stelem(), and System.Xml.Serialization.TypeDesc.Type.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement().