Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual
WriteXmlNodeEqual() [2/2]
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual (string source, string name, string ns, bool doAndIf) inline private
Definition at line 1457 of file XmlSerializationReaderILGen.cs.
    {
        bool flag = string.IsNullOrEmpty(name);
        if (!flag)
        {
            WriteID(name);
        }
        WriteID(ns);
        MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_" + source, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method2 = typeof(XmlReader).GetMethod("get_LocalName", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method3 = typeof(XmlReader).GetMethod("get_NamespaceURI", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        Label label = ilg.DefineLabel();
        Label label2 = ilg.DefineLabel();
        if (!flag)
        {
            ilg.Ldarg(0);
            ilg.Call(method);
            ilg.Call(method2);
            ilg.Ldarg(0);
            ilg.LoadMember(_idNameFields[name ?? string.Empty]);
            ilg.Bne(label);
        }
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.Call(method3);
        ilg.Ldarg(0);
        ilg.LoadMember(_idNameFields[ns ?? string.Empty]);
        ilg.Ceq();
        if (!flag)
        {
            ilg.Br_S(label2);
            ilg.MarkLabel(label);
            ilg.Ldc(boolVar: false);
            ilg.MarkLabel(label2);
        }
        if (doAndIf)
        {
            ilg.AndIf();
        }
    }
References System.Xml.Serialization.XmlSerializationReaderILGen._idNameFields, System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.Bne(), System.Xml.Serialization.CodeGenerator.Br_S(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Ceq(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Text.RegularExpressions.name, System.source, and System.Xml.Serialization.XmlSerializationReaderILGen.WriteID().