Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes
WriteAttributes()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes (Member[] members, Member anyAttribute, string elseCall, LocalBuilder firstParam) inline private
Definition at line 1513 of file XmlSerializationReaderILGen.cs.
    {
        int num = 0;
        Member member = null;
        List<AttributeAccessor> list = new List<AttributeAccessor>();
        MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method2 = typeof(XmlReader).GetMethod("MoveToNextAttribute", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.WhileBegin();
        foreach (Member member2 in members)
        {
            if (member2.Mapping.Xmlns != null)
            {
                member = member2;
            }
            else
            {
                if (member2.Mapping.Ignore)
                {
                    continue;
                }
                AttributeAccessor attribute = member2.Mapping.Attribute;
                if (attribute != null && !attribute.Any)
                {
                    list.Add(attribute);
                    if (num++ > 0)
                    {
                        ilg.InitElseIf();
                    }
                    else
                    {
                        ilg.InitIf();
                    }
                    if (member2.ParamsReadSource != null)
                    {
                        ILGenParamsReadSource(member2.ParamsReadSource);
                        ilg.Ldc(boolVar: false);
                        ilg.AndIf(Cmp.EqualTo);
                    }
                    if (attribute.IsSpecialXmlNamespace)
                    {
                        WriteXmlNodeEqual("Reader", attribute.Name, "http://www.w3.org/XML/1998/namespace");
                    }
                    else
                    {
                        WriteXmlNodeEqual("Reader", attribute.Name, (attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : "");
                    }
                    WriteAttribute(member2);
                }
            }
        }
        if (num > 0)
        {
            ilg.InitElseIf();
        }
        else
        {
            ilg.InitIf();
        }
        if (member != null)
        {
            MethodInfo method3 = typeof(XmlSerializationReader).GetMethod("IsXmlnsAttribute", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
            MethodInfo method4 = typeof(XmlReader).GetMethod("get_Name", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            MethodInfo method5 = typeof(XmlReader).GetMethod("get_LocalName", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            MethodInfo method6 = typeof(XmlReader).GetMethod("get_Value", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldarg(0);
            ilg.Ldarg(0);
            ilg.Call(method);
            ilg.Call(method4);
            ilg.Call(method3);
            ilg.Ldc(boolVar: true);
            ilg.AndIf(Cmp.EqualTo);
            ILGenLoad(member.Source);
            ilg.Load(null);
            ilg.If(Cmp.EqualTo);
            WriteSourceBegin(member.Source);
            ConstructorInfo constructor = member.Mapping.TypeDesc.Type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.New(constructor);
            WriteSourceEnd(member.Source, member.Mapping.TypeDesc.Type);
            ilg.EndIf();
            Label label = ilg.DefineLabel();
            Label label2 = ilg.DefineLabel();
            MethodInfo method7 = member.Mapping.TypeDesc.Type.GetMethod("Add", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
            {
                typeof(string),
                typeof(string)
            });
            MethodInfo method8 = typeof(string).GetMethod("get_Length", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ILGenLoad(member.ArraySource, member.Mapping.TypeDesc.Type);
            ilg.Ldarg(0);
            ilg.Call(method);
            ilg.Call(method4);
            ilg.Call(method8);
            ilg.Ldc(5);
            ilg.Beq(label);
            ilg.Ldarg(0);
            ilg.Call(method);
            ilg.Call(method5);
            ilg.Br(label2);
            ilg.MarkLabel(label);
            ilg.Ldstr(string.Empty);
            ilg.MarkLabel(label2);
            ilg.Ldarg(0);
            ilg.Call(method);
            ilg.Call(method6);
            ilg.Call(method7);
            ilg.Else();
        }
        else
        {
            MethodInfo method9 = typeof(XmlSerializationReader).GetMethod("IsXmlnsAttribute", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
            MethodInfo method10 = typeof(XmlReader).GetMethod("get_Name", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldarg(0);
            ilg.Ldarg(0);
            ilg.Call(method);
            ilg.Call(method10);
            ilg.Call(method9);
            ilg.Ldc(boolVar: false);
            ilg.AndIf(Cmp.EqualTo);
        }
        if (anyAttribute != null)
        {
            LocalBuilder localBuilder = ilg.DeclareOrGetLocal(typeof(XmlAttribute), "attr");
            MethodInfo method11 = typeof(XmlSerializationReader).GetMethod("get_Document", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            MethodInfo method12 = typeof(XmlDocument).GetMethod("ReadNode", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(XmlReader) });
            ilg.Ldarg(0);
            ilg.Call(method11);
            ilg.Ldarg(0);
            ilg.Call(method);
            ilg.Call(method12);
            ilg.ConvertValue(method12.ReturnType, localBuilder.LocalType);
            ilg.Stloc(localBuilder);
            MethodInfo method13 = typeof(XmlSerializationReader).GetMethod("ParseWsdlArrayType", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { localBuilder.LocalType });
            ilg.Ldarg(0);
            ilg.Ldloc(localBuilder);
            ilg.Call(method13);
            WriteAttribute(anyAttribute);
        }
        else
        {
            List<Type> list2 = new List<Type>();
            ilg.Ldarg(0);
            list2.Add(typeof(object));
            ilg.Ldloc(firstParam);
            ilg.ConvertValue(firstParam.LocalType, typeof(object));
            if (list.Count > 0)
            {
                string text = "";
                for (int j = 0; j < list.Count; j++)
                {
                    AttributeAccessor attributeAccessor = list[j];
                    if (j > 0)
                    {
                        text += ", ";
                    }
                    text += (attributeAccessor.IsSpecialXmlNamespace ? "http://www.w3.org/XML/1998/namespace" : (((attributeAccessor.Form == XmlSchemaForm.Qualified) ? attributeAccessor.Namespace : "") + ":" + attributeAccessor.Name));
                }
                list2.Add(typeof(string));
                ilg.Ldstr(text);
            }
            MethodInfo method14 = typeof(XmlSerializationReader).GetMethod(elseCall, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, list2.ToArray());
            ilg.Call(method14);
        }
        ilg.EndIf();
        ilg.WhileBeginCondition();
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.Call(method2);
        ilg.WhileEndCondition();
        ilg.WhileEnd();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.Beq(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.CodeGenerator.DeclareOrGetLocal(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.Else(), System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationILGen.ILGenLoad(), System.Xml.Serialization.XmlSerializationReaderILGen.ILGenParamsReadSource(), System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Serialization.CodeGenerator.InitIf(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.list, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.New(), System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.Xml.Serialization.CodeGenerator.WhileBegin(), System.Xml.Serialization.CodeGenerator.WhileBeginCondition(), System.Xml.Serialization.CodeGenerator.WhileEnd(), System.Xml.Serialization.CodeGenerator.WhileEndCondition(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod().