Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements
WriteMemberElements()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements (Member[] members, string elementElseString, string elseString, Member anyElement, Member anyText) inline private
Definition at line 1852 of file XmlSerializationReaderILGen.cs.
    {
        if (anyText != null)
        {
            ilg.Load(null);
            ilg.Stloc(typeof(string), "tmp");
        }
        MethodInfo method = typeof(XmlReader).GetMethod("get_NodeType", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method2 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        int intVar = 1;
        ilg.Ldarg(0);
        ilg.Call(method2);
        ilg.Call(method);
        ilg.Ldc(intVar);
        ilg.If(Cmp.EqualTo);
        WriteMemberElementsIf(members, anyElement, elementElseString);
        if (anyText != null)
        {
            WriteMemberText(anyText, elseString);
        }
        ilg.Else();
        ILGenElseString(elseString);
        ilg.EndIf();
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.Else(), System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationReaderILGen.ILGenElseString(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod().