Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.ILGenElseString
ILGenElseString()
void System.Xml.Serialization.XmlSerializationReaderILGen.ILGenElseString (string elseString) inline private
Definition at line 2865 of file XmlSerializationReaderILGen.cs.
    {
        MethodInfo method = typeof(XmlSerializationReader).GetMethod("UnknownNode", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(object) });
        MethodInfo method2 = typeof(XmlSerializationReader).GetMethod("UnknownNode", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
        {
            typeof(object),
            typeof(string)
        });
        Regex regex = XmlSerializationILGen.NewRegex("UnknownNode[(]null, @[\"](?<qnames>[^\"]*)[\"][)];");
        Match match = regex.Match(elseString);
        if (match.Success)
        {
            ilg.Ldarg(0);
            ilg.Load(null);
            ilg.Ldstr(match.Groups["qnames"].Value);
            ilg.Call(method2);
            return;
        }
        regex = XmlSerializationILGen.NewRegex("UnknownNode[(][(]object[)](?<o>[^,]+), @[\"](?<qnames>[^\"]*)[\"][)];");
        match = regex.Match(elseString);
        if (match.Success)
        {
            ilg.Ldarg(0);
            LocalBuilder local = ilg.GetLocal(match.Groups["o"].Value);
            ilg.Ldloc(local);
            ilg.ConvertValue(local.LocalType, typeof(object));
            ilg.Ldstr(match.Groups["qnames"].Value);
            ilg.Call(method2);
            return;
        }
        regex = XmlSerializationILGen.NewRegex("UnknownNode[(][(]object[)](?<o>[^,]+), null[)];");
        match = regex.Match(elseString);
        if (match.Success)
        {
            ilg.Ldarg(0);
            LocalBuilder local2 = ilg.GetLocal(match.Groups["o"].Value);
            ilg.Ldloc(local2);
            ilg.ConvertValue(local2.LocalType, typeof(object));
            ilg.Load(null);
            ilg.Call(method2);
            return;
        }
        regex = XmlSerializationILGen.NewRegex("UnknownNode[(][(]object[)](?<o>[^)]+)[)];");
        match = regex.Match(elseString);
        if (match.Success)
        {
            ilg.Ldarg(0);
            LocalBuilder local3 = ilg.GetLocal(match.Groups["o"].Value);
            ilg.Ldloc(local3);
            ilg.ConvertValue(local3.LocalType, typeof(object));
            ilg.Call(method);
            return;
        }
        throw Globals.NotSupported("Unexpected: " + elseString);
    }
References System.Xml.Dictionary, System.match, System.Xml.Serialization.XmlSerializationILGen.NewRegex(), and System.Xml.Serialization.Globals.NotSupported().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements().