Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.NextIdName
NextIdName()
string System.Xml.Serialization.XmlSerializationReaderILGen.NextIdName (string name) inline private
Definition at line 633 of file XmlSerializationReaderILGen.cs.
    {
        IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
        DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(3, 2, invariantCulture);
        handler.AppendLiteral("id");
        handler.AppendFormatted(++_nextIdNumber);
        handler.AppendLiteral("_");
        handler.AppendFormatted(CodeIdentifier.MakeValidInternal(name));
        return string.Create(invariantCulture, ref handler);
    }
References System.Xml.Serialization.XmlSerializationReaderILGen._nextIdNumber, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.CodeIdentifier.MakeValidInternal(), and System.Text.RegularExpressions.name.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteID().