Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.GenerateMethod
GenerateMethod()
override void System.Xml.Serialization.XmlSerializationReaderILGen.GenerateMethod (TypeMapping mapping) inline package virtual
Reimplemented from System.Xml.Serialization.XmlSerializationILGen.
Definition at line 222 of file XmlSerializationReaderILGen.cs.
    {
        if (base.GeneratedMethods.Add(mapping))
        {
            if (mapping is StructMapping)
            {
                WriteStructMethod((StructMapping)mapping);
            }
            else if (mapping is EnumMapping)
            {
                WriteEnumMethod((EnumMapping)mapping);
            }
            else if (mapping is NullableMapping)
            {
                WriteNullableMethod((NullableMapping)mapping);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteStructMethod().