Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteID
WriteID()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteID (string name) inline private
Definition at line 1498 of file XmlSerializationReaderILGen.cs.
    {
        if (name == null)
        {
            name = "";
        }
        if (!_idNames.TryGetValue(name, out var value))
        {
            value = NextIdName(name);
            _idNames.Add(name, value);
            _idNameFields.Add(name, typeBuilder.DefineField(value, typeof(string), FieldAttributes.Private));
        }
    }
References System.Xml.Serialization.XmlSerializationReaderILGen._idNameFields, System.Xml.Serialization.XmlSerializationReaderILGen._idNames, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Emit.TypeBuilder.DefineField(), System.Text.RegularExpressions.name, System.Xml.Serialization.XmlSerializationReaderILGen.NextIdName(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Xml.Serialization.XmlSerializationILGen.typeBuilder, and System.value.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteIsStartTag(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual().