Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute
WriteAttribute()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute (Member member) inline private
Definition at line 1685 of file XmlSerializationReaderILGen.cs.
    {
        AttributeAccessor attribute = member.Mapping.Attribute;
        if (attribute.Mapping is SpecialMapping)
        {
            SpecialMapping specialMapping = (SpecialMapping)attribute.Mapping;
            if (specialMapping.TypeDesc.Kind == TypeKind.Attribute)
            {
                WriteSourceBegin(member.ArraySource);
                ilg.Ldloc("attr");
                WriteSourceEnd(member.ArraySource, member.Mapping.TypeDesc.IsArrayLike ? member.Mapping.TypeDesc.ArrayElementTypeDesc.Type : member.Mapping.TypeDesc.Type);
            }
            else
            {
                if (!specialMapping.TypeDesc.CanBeAttributeValue)
                {
                    throw new InvalidOperationException(System.SR.XmlInternalError);
                }
                LocalBuilder local = ilg.GetLocal("attr");
                ilg.Ldloc(local);
                if (local.LocalType == typeof(XmlAttribute))
                {
                    ilg.Load(null);
                    ilg.Cne();
                }
                else
                {
                    ilg.IsInst(typeof(XmlAttribute));
                }
                ilg.If();
                WriteSourceBegin(member.ArraySource);
                ilg.Ldloc(local);
                ilg.ConvertValue(local.LocalType, typeof(XmlAttribute));
                WriteSourceEnd(member.ArraySource, member.Mapping.TypeDesc.IsArrayLike ? member.Mapping.TypeDesc.ArrayElementTypeDesc.Type : member.Mapping.TypeDesc.Type);
                ilg.EndIf();
            }
        }
        else if (attribute.IsList)
        {
            LocalBuilder localBuilder = ilg.DeclareOrGetLocal(typeof(string), "listValues");
            LocalBuilder localBuilder2 = ilg.DeclareOrGetLocal(typeof(string[]), "vals");
            MethodInfo method = typeof(string).GetMethod("Split", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(char[]) });
            MethodInfo method2 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            MethodInfo method3 = typeof(XmlReader).GetMethod("get_Value", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldarg(0);
            ilg.Call(method2);
            ilg.Call(method3);
            ilg.Stloc(localBuilder);
            ilg.Ldloc(localBuilder);
            ilg.Load(null);
            ilg.Call(method);
            ilg.Stloc(localBuilder2);
            LocalBuilder local2 = ilg.DeclareOrGetLocal(typeof(int), "i");
            ilg.For(local2, 0, localBuilder2);
            string arraySource = GetArraySource(member.Mapping.TypeDesc, member.ArrayName);
            WriteSourceBegin(arraySource);
            WritePrimitive(attribute.Mapping, "vals[i]");
            WriteSourceEnd(arraySource, member.Mapping.TypeDesc.ArrayElementTypeDesc.Type);
            ilg.EndFor();
        }
        else
        {
            WriteSourceBegin(member.ArraySource);
            WritePrimitive(attribute.Mapping, attribute.IsList ? "vals[i]" : "Reader.Value");
            WriteSourceEnd(member.ArraySource, member.Mapping.TypeDesc.IsArrayLike ? member.Mapping.TypeDesc.ArrayElementTypeDesc.Type : member.Mapping.TypeDesc.Type);
        }
        if (member.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite && member.CheckSpecifiedSource != null && member.CheckSpecifiedSource.Length > 0)
        {
            ILGenSet(member.CheckSpecifiedSource, true);
        }
        if (member.ParamsReadSource != null)
        {
            ILGenParamsReadSource(member.ParamsReadSource, value: true);
        }
    }
References System.Xml.Serialization.TypeDesc.ArrayElementTypeDesc, System.Xml.Serialization.XmlSerializationReaderILGen.Member.ArrayName, System.Xml.Serialization.XmlSerializationReaderILGen.Member.ArraySource, System.Xml.Serialization.AccessorMapping.Attribute, System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.MemberMapping.CheckSpecified, System.Xml.Serialization.XmlSerializationReaderILGen.Member.CheckSpecifiedSource, System.Xml.Serialization.CodeGenerator.Cne(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Serialization.CodeGenerator.DeclareOrGetLocal(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndFor(), System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.For(), System.Xml.Serialization.XmlSerializationReaderILGen.GetArraySource(), System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationReaderILGen.ILGenParamsReadSource(), System.Xml.Serialization.XmlSerializationReaderILGen.ILGenSet(), System.Xml.Serialization.TypeDesc.IsArrayLike, System.Xml.Serialization.CodeGenerator.IsInst(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.Mapping, System.Xml.Serialization.XmlSerializationReaderILGen.Member.ParamsReadSource, System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.TypeDesc.Type, System.Xml.Serialization.AccessorMapping.TypeDesc, System.value, System.Xml.Serialization.XmlSerializationReaderILGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes().