Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes
WriteDerivedTypes()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes (StructMapping mapping, bool isTypedReturn, string returnTypeName) inline private
Definition at line 981 of file XmlSerializationReaderILGen.cs.
    {
        for (StructMapping structMapping = mapping.DerivedMappings; structMapping != null; structMapping = structMapping.NextDerivedMapping)
        {
            ilg.InitElseIf();
            WriteQNameEqual("xsiType", structMapping.TypeName, structMapping.Namespace);
            ilg.AndIf();
            string methodName = ReferenceMapping(structMapping);
            List<Type> list = new List<Type>();
            ilg.Ldarg(0);
            if (structMapping.TypeDesc.IsNullable)
            {
                ilg.Ldarg("isNullable");
                list.Add(typeof(bool));
            }
            ilg.Ldc(boolVar: false);
            list.Add(typeof(bool));
            MethodBuilder methodBuilder = EnsureMethodBuilder(typeBuilder, methodName, MethodAttributes.Private | MethodAttributes.HideBySig, structMapping.TypeDesc.Type, list.ToArray());
            ilg.Call(methodBuilder);
            ilg.ConvertValue(methodBuilder.ReturnType, ilg.ReturnLocal.LocalType);
            ilg.Stloc(ilg.ReturnLocal);
            ilg.Br(ilg.ReturnLabel);
            WriteDerivedTypes(structMapping, isTypedReturn, returnTypeName);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationILGen.EnsureMethodBuilder(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.list, System.Reflection.Emit.LocalBuilder.LocalType, System.Xml.Serialization.XmlSerializationILGen.ReferenceMapping(), System.Xml.Serialization.CodeGenerator.ReturnLabel, System.Xml.Serialization.CodeGenerator.ReturnLocal, System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod().