Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.ExpectedElements
ExpectedElements()
string System.Xml.Serialization.XmlSerializationReaderILGen.ExpectedElements (Member[] members) inline private
Definition at line 1819 of file XmlSerializationReaderILGen.cs.
    {
        if (IsSequence(members))
        {
            return "null";
        }
        string text = string.Empty;
        bool flag = true;
        foreach (Member member in members)
        {
            if (member.Mapping.Xmlns != null || member.Mapping.Ignore || member.Mapping.IsText || member.Mapping.IsAttribute)
            {
                continue;
            }
            ElementAccessor[] elements = member.Mapping.Elements;
            foreach (ElementAccessor elementAccessor in elements)
            {
                string text2 = ((elementAccessor.Form == XmlSchemaForm.Qualified) ? elementAccessor.Namespace : "");
                if (!elementAccessor.Any || (elementAccessor.Name != null && elementAccessor.Name.Length != 0))
                {
                    if (!flag)
                    {
                        text += ", ";
                    }
                    text = text + text2 + ":" + elementAccessor.Name;
                    flag = false;
                }
            }
        }
        return ReflectionAwareILGen.GetQuotedCSharpString(text);
    }
References System.Xml.Dictionary, System.Xml.Serialization.AccessorMapping.Elements, System.Xml.Serialization.ReflectionAwareILGen.GetQuotedCSharpString(), System.Xml.Serialization.AccessorMapping.Ignore, System.Xml.Serialization.AccessorMapping.IsAttribute, System.Xml.Serialization.XmlSerializationReaderILGen.IsSequence(), System.Xml.Serialization.AccessorMapping.IsText, System.Xml.Serialization.XmlSerializationReaderILGen.Member.Mapping, System.text, and System.Xml.Serialization.AccessorMapping.Xmlns.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod().