Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement
GenerateTypeElement()
string System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement (XmlTypeMapping xmlTypeMapping) inline private
Definition at line 590 of file XmlSerializationReaderILGen.cs.
    {
        ElementAccessor accessor = xmlTypeMapping.Accessor;
        TypeMapping mapping = accessor.Mapping;
        string text = NextMethodName(accessor.Name);
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(object), text, Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Public | MethodAttributes.HideBySig);
        LocalBuilder localBuilder = ilg.DeclareLocal(typeof(object), "o");
        ilg.Load(null);
        ilg.Stloc(localBuilder);
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.TypeDesc = mapping.TypeDesc;
        memberMapping.Elements = new ElementAccessor[1] { accessor };
        Member[] array = new Member[1]
        {
            new Member(this, "o", "o", "a", 0, memberMapping)
        };
        MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method2 = typeof(XmlReader).GetMethod("MoveToContent", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.Call(method2);
        ilg.Pop();
        string elseString = "UnknownNode(null, " + ExpectedElements(array) + ");";
        WriteMemberElements(array, "throw CreateUnknownNodeException();", elseString, accessor.Any ? array[0] : null, null);
        ilg.Ldloc(localBuilder);
        ilg.Stloc(ilg.ReturnLocal);
        ilg.Ldloc(ilg.ReturnLocal);
        ilg.EndMethod();
        return text;
    }
References System.array, System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.ExpectedElements(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.XmlSerializationReaderILGen.NextMethodName(), System.Xml.Serialization.CodeGenerator.Pop(), System.Xml.Serialization.CodeGenerator.ReturnLocal, System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.Xml.Serialization.XmlSerializationILGen.typeBuilder, and System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateElement().