Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText
WriteMemberText()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText (Member anyText, string elseString) inline private
Definition at line 1878 of file XmlSerializationReaderILGen.cs.
    {
        ilg.InitElseIf();
        Label label = ilg.DefineLabel();
        Label label2 = ilg.DefineLabel();
        MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method2 = typeof(XmlReader).GetMethod("get_NodeType", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.Call(method2);
        ilg.Ldc(XmlNodeType.Text);
        ilg.Ceq();
        ilg.Brtrue(label);
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.Call(method2);
        ilg.Ldc(XmlNodeType.CDATA);
        ilg.Ceq();
        ilg.Brtrue(label);
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.Call(method2);
        ilg.Ldc(XmlNodeType.Whitespace);
        ilg.Ceq();
        ilg.Brtrue(label);
        ilg.Ldarg(0);
        ilg.Call(method);
        ilg.Call(method2);
        ilg.Ldc(XmlNodeType.SignificantWhitespace);
        ilg.Ceq();
        ilg.Br(label2);
        ilg.MarkLabel(label);
        ilg.Ldc(boolVar: true);
        ilg.MarkLabel(label2);
        ilg.AndIf();
        if (anyText != null)
        {
            WriteText(anyText);
        }
    }
References System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Brtrue(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Ceq(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.MarkLabel(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteText().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements().