Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes
WriteEnumAndArrayTypes()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes () inline private
Definition at line 1008 of file XmlSerializationReaderILGen.cs.
    {
        TypeScope[] scopes = base.Scopes;
        foreach (TypeScope typeScope in scopes)
        {
            foreach (Mapping typeMapping in typeScope.TypeMappings)
            {
                if (typeMapping is EnumMapping)
                {
                    EnumMapping enumMapping = (EnumMapping)typeMapping;
                    ilg.InitElseIf();
                    WriteQNameEqual("xsiType", enumMapping.TypeName, enumMapping.Namespace);
                    ilg.AndIf();
                    MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    MethodInfo method2 = typeof(XmlReader).GetMethod("ReadStartElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldarg(0);
                    ilg.Call(method);
                    ilg.Call(method2);
                    string methodName = ReferenceMapping(enumMapping);
                    LocalBuilder localBuilder = ilg.DeclareOrGetLocal(typeof(object), "e");
                    MethodBuilder methodBuilder = EnsureMethodBuilder(typeBuilder, methodName, MethodAttributes.Private | MethodAttributes.HideBySig, enumMapping.TypeDesc.Type, new Type[1] { typeof(string) });
                    MethodInfo method3 = typeof(XmlSerializationReader).GetMethod("CollapseWhitespace", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                    MethodInfo method4 = typeof(XmlReader).GetMethod("ReadContentAsString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldarg(0);
                    ilg.Ldarg(0);
                    ilg.Ldarg(0);
                    ilg.Call(method);
                    ilg.Call(method4);
                    ilg.Call(method3);
                    ilg.Call(methodBuilder);
                    ilg.ConvertValue(methodBuilder.ReturnType, localBuilder.LocalType);
                    ilg.Stloc(localBuilder);
                    MethodInfo method5 = typeof(XmlSerializationReader).GetMethod("ReadEndElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.Ldarg(0);
                    ilg.Call(method5);
                    ilg.Ldloc(localBuilder);
                    ilg.Stloc(ilg.ReturnLocal);
                    ilg.Br(ilg.ReturnLabel);
                }
                else
                {
                    if (!(typeMapping is ArrayMapping))
                    {
                        continue;
                    }
                    ArrayMapping arrayMapping = (ArrayMapping)typeMapping;
                    if (arrayMapping.TypeDesc.HasDefaultConstructor)
                    {
                        ilg.InitElseIf();
                        WriteQNameEqual("xsiType", arrayMapping.TypeName, arrayMapping.Namespace);
                        ilg.AndIf();
                        ilg.EnterScope();
                        MemberMapping memberMapping = new MemberMapping();
                        memberMapping.TypeDesc = arrayMapping.TypeDesc;
                        memberMapping.Elements = arrayMapping.Elements;
                        string text = "a";
                        string arrayName = "z";
                        Member member = new Member(this, text, arrayName, 0, memberMapping);
                        TypeDesc typeDesc = arrayMapping.TypeDesc;
                        LocalBuilder localBuilder2 = ilg.DeclareLocal(arrayMapping.TypeDesc.Type, text);
                        if (arrayMapping.TypeDesc.IsValueType)
{
                            base.RaCodeGen.ILGenForCreateInstance(ilg, typeDesc.Type, ctorInaccessible: false, cast: false);
                        }
                        else
{
                            ilg.Load(null);
                        }
                        ilg.Stloc(localBuilder2);
                        WriteArray(member.Source, member.ArrayName, arrayMapping, readOnly: false, isNullable: false, -1, 0);
                        ilg.Ldloc(localBuilder2);
                        ilg.Stloc(ilg.ReturnLocal);
                        ilg.Br(ilg.ReturnLabel);
                        ilg.ExitScope();
                    }
                }
            }
        }
    }
References System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.ArrayName, System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Serialization.CodeGenerator.DeclareOrGetLocal(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.XmlSerializationILGen.EnsureMethodBuilder(), System.Xml.Serialization.CodeGenerator.EnterScope(), System.Xml.Serialization.CodeGenerator.ExitScope(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.InitElseIf(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.XmlSerializationILGen.ReferenceMapping(), System.Xml.Serialization.CodeGenerator.ReturnLabel, System.Xml.Serialization.CodeGenerator.ReturnLocal, System.Xml.Serialization.XmlSerializationReaderILGen.Member.Source, System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.Xml.Serialization.XmlSerializationReaderILGen.WriteArray(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod().