Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd
WriteSourceEnd() [2/2]
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd (string source, Type elementType, Type stackType) inline private
Definition at line 2311 of file XmlSerializationReaderILGen.cs.
    {
        if (ilg.TryGetVariable(source, out var variable))
        {
            Type variableType = ilg.GetVariableType(variable);
            if (CodeGenerator.IsNullableGenericType(variableType))
            {
                ilg.Call(variableType.GetConstructor(variableType.GetGenericArguments()));
                return;
            }
            ilg.ConvertValue(stackType, elementType);
            ilg.ConvertValue(elementType, variableType);
            ilg.Stloc((LocalBuilder)variable);
            return;
        }
        if (source.StartsWith("o.@", StringComparison.Ordinal))
        {
            MemberInfo memberInfo = memberInfos[source.Substring(3)];
            ilg.ConvertValue(stackType, (memberInfo is FieldInfo) ? ((FieldInfo)memberInfo).FieldType : ((PropertyInfo)memberInfo).PropertyType);
            ilg.StoreMember(memberInfo);
            return;
        }
        Regex regex = XmlSerializationILGen.NewRegex("(?<locA1>[^ ]+) = .+EnsureArrayIndex[(](?<locA2>[^,]+), (?<locI1>[^,]+),[^;]+;(?<locA3>[^[]+)[[](?<locI2>[^+]+)[+][+][]]");
        Match match = regex.Match(source);
        if (match.Success)
        {
            object variable2 = ilg.GetVariable(match.Groups["locA1"].Value);
            Type elementType2 = ilg.GetVariableType(variable2).GetElementType();
            ilg.ConvertValue(elementType, elementType2);
            if (CodeGenerator.IsNullableGenericType(elementType2) || elementType2.IsValueType)
            {
                ilg.Stobj(elementType2);
            }
            else
            {
                ilg.Stelem(elementType2);
            }
        }
        else if (source.EndsWith(".Add(", StringComparison.Ordinal))
        {
            int length = source.LastIndexOf(".Add(", StringComparison.Ordinal);
            LocalBuilder local = ilg.GetLocal(source.Substring(0, length));
            MethodInfo method = local.LocalType.GetMethod("Add", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { elementType });
            Type parameterType = method.GetParameters()[0].ParameterType;
            ilg.ConvertValue(stackType, parameterType);
            ilg.Call(method);
            if (method.ReturnType != typeof(void))
            {
                ilg.Pop();
            }
        }
        else
        {
            regex = XmlSerializationILGen.NewRegex("(?<a>[^[]+)[[](?<ia>.+)[]]");
            match = regex.Match(source);
            if (!match.Success)
            {
                throw Globals.NotSupported("Unexpected: " + source);
            }
            Type variableType2 = ilg.GetVariableType(ilg.GetVariable(match.Groups["a"].Value));
            Type elementType3 = variableType2.GetElementType();
            ilg.ConvertValue(stackType, elementType3);
            ilg.Stelem(elementType3);
        }
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.elementType, System.Type.GetElementType(), System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.CodeGenerator.GetVariable(), System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.IsNullableGenericType(), System.length, System.match, System.Xml.Serialization.XmlSerializationILGen.memberInfos, System.Xml.Serialization.XmlSerializationILGen.NewRegex(), System.Xml.Serialization.CodeGenerator.Pop(), System.source, System.Xml.Serialization.CodeGenerator.Stelem(), System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.CodeGenerator.Stobj(), System.Xml.Serialization.CodeGenerator.StoreMember(), and System.Xml.Serialization.CodeGenerator.TryGetVariable().