Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual
WriteQNameEqual()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual (string source, string name, string ns) inline private
Definition at line 1425 of file XmlSerializationReaderILGen.cs.
    {
        WriteID(name);
        WriteID(ns);
        MethodInfo method = typeof(XmlQualifiedName).GetMethod("get_Name", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method2 = typeof(XmlQualifiedName).GetMethod("get_Namespace", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        Label label = ilg.DefineLabel();
        Label label2 = ilg.DefineLabel();
        LocalBuilder local = ilg.GetLocal(source);
        ilg.Ldloc(local);
        ilg.Call(method);
        ilg.Ldarg(0);
        ilg.LoadMember(_idNameFields[name ?? string.Empty]);
        ilg.Bne(label2);
        ilg.Ldloc(local);
        ilg.Call(method2);
        ilg.Ldarg(0);
        ilg.LoadMember(_idNameFields[ns ?? string.Empty]);
        ilg.Ceq();
        ilg.Br_S(label);
        ilg.MarkLabel(label2);
        ilg.Ldc(boolVar: false);
        ilg.MarkLabel(label);
    }
References System.Xml.Serialization.XmlSerializationReaderILGen._idNameFields, System.Xml.Serialization.CodeGenerator.Bne(), System.Xml.Serialization.CodeGenerator.Br_S(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Ceq(), System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Text.RegularExpressions.name, System.source, and System.Xml.Serialization.XmlSerializationReaderILGen.WriteID().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod().