Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable
WriteHashtable()
string System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable (EnumMapping mapping, string typeName, out MethodBuilder get_TableName) inline private
Definition at line 835 of file XmlSerializationReaderILGen.cs.
    {
        get_TableName = null;
        CodeIdentifier.CheckValidIdentifier(typeName);
        string text = MakeUnique(mapping, typeName + "Values");
        if (text == null)
        {
            return CodeIdentifier.GetCSharpName(typeName);
        }
        string fieldName = MakeUnique(mapping, "_" + text);
        text = CodeIdentifier.GetCSharpName(text);
        FieldBuilder memberInfo = typeBuilder.DefineField(fieldName, typeof(Hashtable), FieldAttributes.Private);
        PropertyBuilder propertyBuilder = typeBuilder.DefineProperty(text, PropertyAttributes.None, CallingConventions.HasThis, typeof(Hashtable), null, null, null, null, null);
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(Hashtable), "get_" + text, Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Assembly | MethodAttributes.HideBySig | MethodAttributes.SpecialName);
        ilg.Ldarg(0);
        ilg.LoadMember(memberInfo);
        ilg.Load(null);
        ilg.If(Cmp.EqualTo);
        ConstructorInfo constructor = typeof(Hashtable).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        LocalBuilder localBuilder = ilg.DeclareLocal(typeof(Hashtable), "h");
        ilg.New(constructor);
        ilg.Stloc(localBuilder);
        ConstantMapping[] constants = mapping.Constants;
        MethodInfo method = typeof(Hashtable).GetMethod("Add", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
        {
            typeof(object),
            typeof(object)
        });
        for (int i = 0; i < constants.Length; i++)
        {
            ilg.Ldloc(localBuilder);
            ilg.Ldstr(GetCSharpString(constants[i].XmlName));
            ilg.Ldc(Enum.ToObject(mapping.TypeDesc.Type, constants[i].Value));
            ilg.ConvertValue(mapping.TypeDesc.Type, typeof(long));
            ilg.ConvertValue(typeof(long), typeof(object));
            ilg.Call(method);
        }
        ilg.Ldarg(0);
        ilg.Ldloc(localBuilder);
        ilg.StoreMember(memberInfo);
        ilg.EndIf();
        ilg.Ldarg(0);
        ilg.LoadMember(memberInfo);
        get_TableName = ilg.EndMethod();
        propertyBuilder.SetGetMethod(get_TableName);
        return text;
    }
References System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Reflection.Emit.TypeBuilder.DefineField(), System.Reflection.Emit.TypeBuilder.DefineProperty(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Text.RegularExpressions.i, System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.XmlSerializationReaderILGen.MakeUnique(), System.Xml.Serialization.CodeGenerator.New(), System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.CodeGenerator.StoreMember(), System.text, System.Enum.ToObject(), and System.Xml.Serialization.XmlSerializationILGen.typeBuilder.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod().