Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode
WriteUnknownNode()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode (string func, string node, ElementAccessor e, bool anyIfs) inline private
Definition at line 311 of file XmlSerializationReaderILGen.cs.
    {
        if (anyIfs)
        {
            ilg.Else();
        }
        List<Type> list = new List<Type>();
        ilg.Ldarg(0);
        if (node == "null")
        {
            ilg.Load(null);
        }
        else
        {
            object variable = ilg.GetVariable("p");
            ilg.Load(variable);
            ilg.ConvertValue(ilg.GetVariableType(variable), typeof(object));
        }
        list.Add(typeof(object));
        if (e != null)
        {
            string text = ((e.Form == XmlSchemaForm.Qualified) ? e.Namespace : "");
            text += ":";
            text += e.Name;
            ilg.Ldstr(ReflectionAwareILGen.GetCSharpString(text));
            list.Add(typeof(string));
        }
        MethodInfo method = typeof(XmlSerializationReader).GetMethod(func, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, list.ToArray());
        ilg.Call(method);
        if (anyIfs)
        {
            ilg.EndIf();
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.Else(), System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.ReflectionAwareILGen.GetCSharpString(), System.Xml.Serialization.CodeGenerator.GetVariable(), System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.list, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.Accessor.Name, System.Xml.Serialization.Accessor.Namespace, and System.text.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement().