Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberEnd
WriteMemberEnd() [2/2]
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberEnd (Member[] members, bool soapRefs) inline private
Definition at line 2179 of file XmlSerializationReaderILGen.cs.
    {
        foreach (Member member in members)
        {
            if (!member.IsArrayLike)
            {
                continue;
            }
            TypeDesc typeDesc = member.Mapping.TypeDesc;
            if (typeDesc.IsArray)
            {
                WriteSourceBegin(member.Source);
                string arrayName = member.ArrayName;
                string name = "c" + arrayName;
                MethodInfo method = typeof(XmlSerializationReader).GetMethod("ShrinkArray", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[4]
                {
                    typeof(Array),
                    typeof(int),
                    typeof(Type),
                    typeof(bool)
                });
                ilg.Ldarg(0);
                ilg.Ldloc(ilg.GetLocal(arrayName));
                ilg.Ldloc(ilg.GetLocal(name));
                ilg.Ldc(typeDesc.ArrayElementTypeDesc.Type);
                ilg.Ldc(member.IsNullable);
                ilg.Call(method);
                ilg.ConvertValue(method.ReturnType, typeDesc.Type);
                WriteSourceEnd(member.Source, typeDesc.Type);
                if (member.Mapping.ChoiceIdentifier != null)
                {
                    WriteSourceBegin(member.ChoiceSource);
                    arrayName = member.ChoiceArrayName;
                    name = "c" + arrayName;
                    ilg.Ldarg(0);
                    ilg.Ldloc(ilg.GetLocal(arrayName));
                    ilg.Ldloc(ilg.GetLocal(name));
                    ilg.Ldc(member.Mapping.ChoiceIdentifier.Mapping.TypeDesc.Type);
                    ilg.Ldc(member.IsNullable);
                    ilg.Call(method);
                    ilg.ConvertValue(method.ReturnType, member.Mapping.ChoiceIdentifier.Mapping.TypeDesc.Type.MakeArrayType());
                    WriteSourceEnd(member.ChoiceSource, member.Mapping.ChoiceIdentifier.Mapping.TypeDesc.Type.MakeArrayType());
                }
            }
            else if (typeDesc.IsValueType)
            {
                LocalBuilder local = ilg.GetLocal(member.ArrayName);
                WriteSourceBegin(member.Source);
                ilg.Ldloc(local);
                WriteSourceEnd(member.Source, local.LocalType);
            }
        }
    }
References System.Xml.Serialization.XmlSerializationReaderILGen.Member.ArrayName, System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.ChoiceArrayName, System.Xml.Serialization.AccessorMapping.ChoiceIdentifier, System.Xml.Serialization.XmlSerializationReaderILGen.Member.ChoiceSource, System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationReaderILGen.Member.IsArrayLike, System.Xml.Serialization.XmlSerializationReaderILGen.Member.IsNullable, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Type.MakeArrayType(), System.Xml.Serialization.Accessor.Mapping, System.Xml.Serialization.XmlSerializationReaderILGen.Member.Mapping, System.Text.RegularExpressions.name, System.Xml.Serialization.XmlSerializationReaderILGen.Member.Source, System.Xml.Serialization.TypeDesc.Type, System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd().