Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WritePrimitive
WritePrimitive()
void System.Xml.Serialization.XmlSerializationReaderILGen.WritePrimitive (TypeMapping mapping, string source) inline private
Definition at line 645 of file XmlSerializationReaderILGen.cs.
    {
        if (mapping is EnumMapping)
        {
            string text = ReferenceMapping(mapping);
            if (text == null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlMissingMethodEnum, mapping.TypeDesc.Name));
            }
            MethodBuilder methodInfo = EnsureMethodBuilder(typeBuilder, text, MethodAttributes.Private | MethodAttributes.HideBySig, mapping.TypeDesc.Type, new Type[1] { typeof(string) });
            ilg.Ldarg(0);
            switch (source)
            {
            case "Reader.ReadElementString()":
            case "Reader.ReadString()":
            {
                MethodInfo method3 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method4 = typeof(XmlReader).GetMethod((source == "Reader.ReadElementString()") ? "ReadElementContentAsString" : "ReadContentAsString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                ilg.Ldarg(0);
                ilg.Call(method3);
                ilg.Call(method4);
                break;
            }
            case "Reader.Value":
            {
                MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method2 = typeof(XmlReader).GetMethod("get_Value", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                ilg.Ldarg(0);
                ilg.Call(method);
                ilg.Call(method2);
                break;
            }
            case "vals[i]":
            {
                LocalBuilder local = ilg.GetLocal("vals");
                LocalBuilder local2 = ilg.GetLocal("i");
                ilg.LoadArrayElement(local, local2);
                break;
            }
            case "false":
                ilg.Ldc(boolVar: false);
                break;
            default:
                throw Globals.NotSupported("Unexpected: " + source);
            }
            ilg.Call(methodInfo);
            return;
        }
        if (mapping.TypeDesc == base.StringTypeDesc)
        {
            switch (source)
            {
            case "Reader.ReadElementString()":
            case "Reader.ReadString()":
            {
                MethodInfo method7 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method8 = typeof(XmlReader).GetMethod((source == "Reader.ReadElementString()") ? "ReadElementContentAsString" : "ReadContentAsString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                ilg.Ldarg(0);
                ilg.Call(method7);
                ilg.Call(method8);
                break;
            }
            case "Reader.Value":
            {
                MethodInfo method5 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                MethodInfo method6 = typeof(XmlReader).GetMethod("get_Value", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                ilg.Ldarg(0);
                ilg.Call(method5);
                ilg.Call(method6);
                break;
            }
            case "vals[i]":
            {
                LocalBuilder local3 = ilg.GetLocal("vals");
                LocalBuilder local4 = ilg.GetLocal("i");
                ilg.LoadArrayElement(local3, local4);
                break;
            }
            default:
                throw Globals.NotSupported("Unexpected: " + source);
            }
            return;
        }
        if (mapping.TypeDesc.FormatterName == "String")
        {
            if (source == "vals[i]")
            {
                if (mapping.TypeDesc.CollapseWhitespace)
                {
                    ilg.Ldarg(0);
                }
                LocalBuilder local5 = ilg.GetLocal("vals");
                LocalBuilder local6 = ilg.GetLocal("i");
                ilg.LoadArrayElement(local5, local6);
                if (mapping.TypeDesc.CollapseWhitespace)
                {
                    MethodInfo method9 = typeof(XmlSerializationReader).GetMethod("CollapseWhitespace", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[1] { typeof(string) }, null);
                    ilg.Call(method9);
                }
                return;
            }
            MethodInfo method10 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            MethodInfo method11 = typeof(XmlReader).GetMethod((source == "Reader.Value") ? "get_Value" : "ReadElementContentAsString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            if (mapping.TypeDesc.CollapseWhitespace)
            {
                ilg.Ldarg(0);
            }
            ilg.Ldarg(0);
            ilg.Call(method10);
            ilg.Call(method11);
            if (mapping.TypeDesc.CollapseWhitespace)
            {
                MethodInfo method12 = typeof(XmlSerializationReader).GetMethod("CollapseWhitespace", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                ilg.Call(method12);
            }
            return;
        }
        Type type = ((source == "false") ? typeof(bool) : typeof(string));
        MethodInfo method13;
        if (mapping.TypeDesc.HasCustomFormatter)
        {
            BindingFlags bindingAttr = BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic;
            if ((mapping.TypeDesc.FormatterName == "ByteArrayBase64" && source == "false") || (mapping.TypeDesc.FormatterName == "ByteArrayHex" && source == "false") || mapping.TypeDesc.FormatterName == "XmlQualifiedName")
            {
                bindingAttr = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
                ilg.Ldarg(0);
            }
            method13 = typeof(XmlSerializationReader).GetMethod("To" + mapping.TypeDesc.FormatterName, bindingAttr, new Type[1] { type });
        }
        else
        {
            method13 = typeof(XmlConvert).GetMethod("To" + mapping.TypeDesc.FormatterName, BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { type });
        }
        switch (source)
        {
        case "Reader.ReadElementString()":
        case "Reader.ReadString()":
        {
            MethodInfo method16 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            MethodInfo method17 = typeof(XmlReader).GetMethod((source == "Reader.ReadElementString()") ? "ReadElementContentAsString" : "ReadContentAsString", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldarg(0);
            ilg.Call(method16);
            ilg.Call(method17);
            break;
        }
        case "Reader.Value":
        {
            MethodInfo method14 = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            MethodInfo method15 = typeof(XmlReader).GetMethod("get_Value", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldarg(0);
            ilg.Call(method14);
            ilg.Call(method15);
            break;
        }
        case "vals[i]":
        {
            LocalBuilder local7 = ilg.GetLocal("vals");
            LocalBuilder local8 = ilg.GetLocal("i");
            ilg.LoadArrayElement(local7, local8);
            break;
        }
        default:
            ilg.Ldc(boolVar: false);
            break;
        }
        ilg.Call(method13);
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.XmlSerializationILGen.EnsureMethodBuilder(), System.SR.Format(), System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.LoadArrayElement(), System.Xml.Serialization.Globals.NotSupported(), System.Xml.Serialization.XmlSerializationILGen.ReferenceMapping(), System.source, System.text, System.type, System.Xml.Serialization.XmlSerializationILGen.typeBuilder, and System.SR.XmlMissingMethodEnum.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteText().