Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod
WriteEnumMethod()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod (EnumMapping mapping) inline private
Definition at line 885 of file XmlSerializationReaderILGen.cs.
    {
        MethodBuilder get_TableName = null;
        if (mapping.IsFlags)
        {
            WriteHashtable(mapping, mapping.TypeDesc.Name, out get_TableName);
        }
        base.MethodNames.TryGetValue(mapping, out var value);
        string cSharpName = mapping.TypeDesc.CSharpName;
        List<Type> list = new List<Type>();
        List<string> list2 = new List<string>();
        Type type = mapping.TypeDesc.Type;
        Type underlyingType = Enum.GetUnderlyingType(type);
        list.Add(typeof(string));
        list2.Add("s");
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(type, GetMethodBuilder(value), list.ToArray(), list2.ToArray(), MethodAttributes.Private | MethodAttributes.HideBySig);
        ConstantMapping[] constants = mapping.Constants;
        if (mapping.IsFlags)
        {
            MethodInfo method = typeof(XmlSerializationReader).GetMethod("ToEnum", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[3]
            {
                typeof(string),
                typeof(Hashtable),
                typeof(string)
            });
            ilg.Ldarg("s");
            ilg.Ldarg(0);
            ilg.Call(get_TableName);
            ilg.Ldstr(GetCSharpString(cSharpName));
            ilg.Call(method);
            if (underlyingType != typeof(long))
            {
                ilg.ConvertValue(typeof(long), underlyingType);
            }
            ilg.Stloc(ilg.ReturnLocal);
            ilg.Br(ilg.ReturnLabel);
        }
        else
        {
            List<Label> list3 = new List<Label>();
            List<object> list4 = new List<object>();
            Label label = ilg.DefineLabel();
            Label label2 = ilg.DefineLabel();
            LocalBuilder tempLocal = ilg.GetTempLocal(typeof(string));
            ilg.Ldarg("s");
            ilg.Stloc(tempLocal);
            ilg.Ldloc(tempLocal);
            ilg.Brfalse(label);
            HashSet<string> hashSet = new HashSet<string>();
            foreach (ConstantMapping constantMapping in constants)
            {
                CodeIdentifier.CheckValidIdentifier(constantMapping.Name);
                if (hashSet.Add(constantMapping.XmlName))
                {
                    Label label3 = ilg.DefineLabel();
                    ilg.Ldloc(tempLocal);
                    ilg.Ldstr(GetCSharpString(constantMapping.XmlName));
                    MethodInfo method2 = typeof(string).GetMethod("op_Equality", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
                    {
                        typeof(string),
                        typeof(string)
                    });
                    ilg.Call(method2);
                    ilg.Brtrue(label3);
                    list3.Add(label3);
                    list4.Add(Enum.ToObject(mapping.TypeDesc.Type, constantMapping.Value));
                }
            }
            ilg.Br(label);
            for (int j = 0; j < list3.Count; j++)
            {
                ilg.MarkLabel(list3[j]);
                ilg.Ldc(list4[j]);
                ilg.Stloc(ilg.ReturnLocal);
                ilg.Br(ilg.ReturnLabel);
            }
            MethodInfo method3 = typeof(XmlSerializationReader).GetMethod("CreateUnknownConstantException", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
            {
                typeof(string),
                typeof(Type)
            });
            ilg.MarkLabel(label);
            ilg.Ldarg(0);
            ilg.Ldarg("s");
            ilg.Ldc(mapping.TypeDesc.Type);
            ilg.Call(method3);
            ilg.Throw();
            ilg.MarkLabel(label2);
        }
        ilg.MarkLabel(ilg.ReturnLabel);
        ilg.Ldloc(ilg.ReturnLocal);
        ilg.EndMethod();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Brfalse(), System.Xml.Serialization.CodeGenerator.Brtrue(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.XmlSerializationILGen.GetMethodBuilder(), System.Xml.Serialization.CodeGenerator.GetTempLocal(), System.Enum.GetUnderlyingType(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.list, System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.ReturnLabel, System.Xml.Serialization.CodeGenerator.ReturnLocal, System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.CodeGenerator.Throw(), System.Enum.ToObject(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, System.Xml.Serialization.XmlSerializationILGen.typeBuilder, System.value, and System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateMethod().