Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd
GenerateEnd()
void System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd (string[] methods, XmlMapping[] xmlMappings, Type[] types) inline package
Definition at line 242 of file XmlSerializationReaderILGen.cs.
    {
        GenerateReferencedMethods();
        GenerateInitCallbacksMethod();
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(void), "InitIDs", Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Family | MethodAttributes.Virtual | MethodAttributes.HideBySig);
        MethodInfo method = typeof(XmlSerializationReader).GetMethod("get_Reader", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method2 = typeof(XmlReader).GetMethod("get_NameTable", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        MethodInfo method3 = typeof(XmlNameTable).GetMethod("Add", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
        foreach (string key in _idNames.Keys)
        {
            ilg.Ldarg(0);
            ilg.Ldarg(0);
            ilg.Call(method);
            ilg.Call(method2);
            ilg.Ldstr(GetCSharpString(key));
            ilg.Call(method3);
            ilg.StoreMember(_idNameFields[key]);
        }
        ilg.EndMethod();
        typeBuilder.DefineDefaultConstructor(MethodAttributes.Public | MethodAttributes.HideBySig);
        Type type = typeBuilder.CreateTypeInfo().AsType();
        CreatedTypes.Add(type.Name, type);
    }
References System.Xml.Serialization.XmlSerializationReaderILGen._idNameFields, System.Xml.Serialization.XmlSerializationReaderILGen._idNames, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.TypeInfo.AsType(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.XmlSerializationILGen.CreatedTypes, System.Reflection.Emit.TypeBuilder.CreateTypeInfo(), System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationILGen.GenerateReferencedMethods(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeGenerator.StoreMember(), System.type, and System.Xml.Serialization.XmlSerializationILGen.typeBuilder.