Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin
WriteMemberBegin()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin (Member[] members) inline private
Definition at line 1762 of file XmlSerializationReaderILGen.cs.
    {
        foreach (Member member in members)
        {
            if (!member.IsArrayLike)
            {
                continue;
            }
            string arrayName = member.ArrayName;
            string name = "c" + arrayName;
            TypeDesc typeDesc = member.Mapping.TypeDesc;
            if (member.Mapping.TypeDesc.IsArray)
            {
                WriteArrayLocalDecl(typeDesc.CSharpName, arrayName, "null", typeDesc);
                ilg.Ldc(0);
                ilg.Stloc(typeof(int), name);
                if (member.Mapping.ChoiceIdentifier != null)
                {
                    WriteArrayLocalDecl(member.Mapping.ChoiceIdentifier.Mapping.TypeDesc.CSharpName + "[]", member.ChoiceArrayName, "null", member.Mapping.ChoiceIdentifier.Mapping.TypeDesc);
                    ilg.Ldc(0);
                    ilg.Stloc(typeof(int), "c" + member.ChoiceArrayName);
                }
                continue;
            }
            if (member.Source[member.Source.Length - 1] == '(' || member.Source[member.Source.Length - 1] == '{')
            {
                WriteCreateInstance(arrayName, typeDesc.CannotNew, typeDesc.Type);
                WriteSourceBegin(member.Source);
                ilg.Ldloc(ilg.GetLocal(arrayName));
                WriteSourceEnd(member.Source, typeDesc.Type);
                continue;
            }
            if (member.IsList && !member.Mapping.ReadOnly && member.Mapping.TypeDesc.IsNullable)
            {
                ILGenLoad(member.Source, typeof(object));
                ilg.Load(null);
                ilg.If(Cmp.EqualTo);
                if (!member.Mapping.TypeDesc.HasDefaultConstructor)
                {
                    MethodInfo method = typeof(XmlSerializationReader).GetMethod("CreateReadOnlyCollectionException", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(string) });
                    ilg.Ldarg(0);
                    ilg.Ldstr(GetCSharpString(member.Mapping.TypeDesc.CSharpName));
                    ilg.Call(method);
                    ilg.Throw();
                }
                else
                {
                    WriteSourceBegin(member.Source);
                    base.RaCodeGen.ILGenForCreateInstance(ilg, member.Mapping.TypeDesc.Type, typeDesc.CannotNew, cast: true);
                    WriteSourceEnd(member.Source, member.Mapping.TypeDesc.Type);
                }
                ilg.EndIf();
            }
            WriteLocalDecl(arrayName, new SourceInfo(member.Source, member.Source, member.Mapping.MemberInfo, member.Mapping.TypeDesc.Type, ilg));
        }
    }
References System.Xml.Serialization.XmlSerializationReaderILGen.Member.ArrayName, System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.XmlSerializationReaderILGen.Member.ChoiceArrayName, System.Xml.Serialization.AccessorMapping.ChoiceIdentifier, System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.CodeGenerator.GetLocal(), System.Xml.Serialization.TypeDesc.HasDefaultConstructor, System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.XmlSerializationILGen.ILGenLoad(), System.Xml.Serialization.TypeDesc.IsArray, System.Xml.Serialization.XmlSerializationReaderILGen.Member.IsArrayLike, System.Xml.Serialization.XmlSerializationReaderILGen.Member.IsList, System.Xml.Serialization.TypeDesc.IsNullable, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.Accessor.Mapping, System.Xml.Serialization.XmlSerializationReaderILGen.Member.Mapping, System.Xml.Serialization.MemberMapping.MemberInfo, System.Text.RegularExpressions.name, System.Xml.Serialization.MemberMapping.ReadOnly, System.Xml.Serialization.XmlSerializationReaderILGen.Member.Source, System.Xml.Serialization.CodeGenerator.Stloc(), System.Xml.Serialization.CodeGenerator.Throw(), System.Xml.Serialization.TypeDesc.Type, System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReaderILGen.WriteArrayLocalDecl(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteCreateInstance(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLocalDecl(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod().