Terraria: System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsElse
WriteMemberElementsElse()
void System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsElse (Member anyElement, string elementElseString) inline private
Definition at line 1988 of file XmlSerializationReaderILGen.cs.
    {
        if (anyElement != null)
        {
            ElementAccessor[] elements = anyElement.Mapping.Elements;
            for (int i = 0; i < elements.Length; i++)
            {
                ElementAccessor elementAccessor = elements[i];
                if (elementAccessor.Any && elementAccessor.Name.Length == 0)
                {
                    WriteElement(anyElement.ArraySource, anyElement.ArrayName, anyElement.ChoiceArraySource, elementAccessor, anyElement.Mapping.ChoiceIdentifier, (anyElement.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite) ? anyElement.CheckSpecifiedSource : null, checkForNull: false, readOnly: false, -1, i);
                    break;
                }
            }
        }
        else
        {
            ILGenElementElseString(elementElseString);
        }
    }
References System.Xml.Dictionary, System.Text.RegularExpressions.i, System.Xml.Serialization.XmlSerializationReaderILGen.ILGenElementElseString(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteElement().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf().