Terraria: ReLogic.Content.Sources.ContentSource.SetAssetNames
SetAssetNames()
void ReLogic.Content.Sources.ContentSource.SetAssetNames (IEnumerable< string > paths) inline protected inherited
Definition at line 19 of file ContentSource.cs.
    {
        assetPaths = paths.ToArray();
        assetExtensions.Clear();
        string[] array = assetPaths;
        foreach (string obj in array)
        {
            string ext = Path.GetExtension(obj);
            string text = obj;
            int length = ext.Length;
            string name = AssetPathHelper.CleanPath(text.Substring(0, text.Length - length));
            if (assetExtensions.TryGetValue(name, out var ext2))
            {
                throw new Exception($"Multiple extensions for asset {name}, ({ext}, {ext2})");
            }
            assetExtensions[name] = ext;
        }
    }
References System.array, ReLogic.Content.Sources.ContentSource.assetExtensions, ReLogic.Content.Sources.ContentSource.assetPaths, ReLogic.Content.AssetPathHelper.CleanPath(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.IO.Path.GetExtension(), System.length, System.obj, System.text, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by ReLogic.Content.Sources.FileSystemContentSource.FileSystemContentSource(), ReLogic.Content.Sources.XnaDirectContentSource.XnaDirectContentSource(), and ReLogic.Content.Sources.ZipContentSource.BuildEntryList().