Terraria: WallDrawing.FullTile
FullTile()
bool WallDrawing.FullTile (int x, int y) inline protected
     {
         if (_tileArray[x - 1, y] == null || _tileArray[x - 1, y].blockType() != 0 || _tileArray[x + 1, y] == null || _tileArray[x + 1, y].blockType() != 0)
         {
             return false;
         }
         Tile tile = _tileArray[x, y];
         if (tile == null)
         {
             return false;
         }
         if (tile.active())
         {
             if (tile.type < TileID.Sets.DrawsWalls.Length && TileID.Sets.DrawsWalls[tile.type])
             {
                 return false;
             }
             if (tile.invisibleBlock() && !_shouldShowInvisibleWalls)
             {
                 return false;
             }
             if (Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
             {
                 int frameX = tile.frameX;
                 int frameY = tile.frameY;
                 if (Main.tileLargeFrames[tile.type] > 0)
                 {
                     if (frameY == 18 || frameY == 108)
                     {
                         if (frameX >= 18 && frameX <= 54)
{
                             return true;
                         }
                         if (frameX >= 108 && frameX <= 144)
{
                             return true;
                         }
                     }
                 }
                 else if (frameY == 18)
                 {
                     if (frameX >= 18 && frameX <= 54)
                     {
                         return true;
                     }
                     if (frameX >= 108 && frameX <= 144)
                     {
                         return true;
                     }
                 }
                 else if (frameY >= 90 && frameY <= 196)
                 {
                     if (frameX <= 70)
                     {
                         return true;
                     }
                     if (frameX >= 144 && frameX <= 232)
                     {
                         return true;
                     }
                 }
             }
         }
         return false;
     }
References _shouldShowInvisibleWalls, _tileArray, Tile.active(), TileID.Sets.DrawsWalls, Tile.frameX, Tile.frameY, Tile.invisibleBlock(), Main.tileLargeFrames, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by DrawWalls().