Terraria: System.Threading.Channels.ChannelUtilities.CreateInvalidCompletionException
CreateInvalidCompletionException()
static Exception System.Threading.Channels.ChannelUtilities.CreateInvalidCompletionException (Exception inner = null) inline static package
Definition at line 80 of file ChannelUtilities.cs.
    {
        if (!(inner is OperationCanceledException))
        {
            if (inner == null || inner == s_doneWritingSentinel)
            {
                return new ChannelClosedException();
            }
            return new ChannelClosedException(inner);
        }
        return inner;
    }
References System.Threading.Channels.ChannelUtilities.s_doneWritingSentinel.
Referenced by System.Threading.Channels.ChannelWriter< T >.Complete(), System.Threading.Channels.ChannelUtilities.GetInvalidCompletionValueTask< T >(), System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter.TryComplete(), System.Threading.Channels.SingleConsumerUnboundedChannel< T >.UnboundedChannelWriter.TryComplete(), System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelWriter.TryComplete(), System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter.WriteAsync(), System.Threading.Channels.SingleConsumerUnboundedChannel< T >.UnboundedChannelWriter.WriteAsync(), System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelWriter.WriteAsync(), and System.Threading.Channels.ChannelWriter< T >.WriteAsyncCore().