Terraria: System.Threading.Channels.ChannelUtilities.GetInvalidCompletionValueTask< T >
GetInvalidCompletionValueTask< T >()
static ValueTask< T > System.Threading.Channels.ChannelUtilities.GetInvalidCompletionValueTask< T > (Exception error) inline static package
Definition at line 32 of file ChannelUtilities.cs.
    {
        Task<T> task = ((error == s_doneWritingSentinel) ? Task.FromException<T>(CreateInvalidCompletionException()) : ((error is OperationCanceledException { CancellationToken: var cancellationToken } ex) ? Task.FromCanceled<T>(cancellationToken.IsCancellationRequested ? ex.CancellationToken : new CancellationToken(canceled: true)) : Task.FromException<T>(CreateInvalidCompletionException(error))));
        return new ValueTask<T>(task);
    }
References System.cancellationToken, System.Threading.Channels.ChannelUtilities.CreateInvalidCompletionException(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.Channels.ChannelUtilities.s_doneWritingSentinel, and System.task.