Terraria: System.Diagnostics.DefaultTraceListener.WriteToLogFile
WriteToLogFile()
void System.Diagnostics.DefaultTraceListener.WriteToLogFile (string message) inline private
Definition at line 130 of file DefaultTraceListener.cs.
    {
        try
        {
            File.AppendAllText(LogFileName, message);
        }
        catch (Exception p)
        {
            WriteLine(System.SR.Format(System.SR.ExceptionOccurred, LogFileName, p), useLogFile: false);
        }
    }
References System.IO.File.AppendAllText(), System.SR.ExceptionOccurred, System.SR.Format(), System.Diagnostics.DefaultTraceListener.LogFileName, and System.Diagnostics.DefaultTraceListener.WriteLine().
Referenced by System.Diagnostics.DefaultTraceListener.Write().