Terraria: System.Diagnostics.DefaultTraceListener.Write
Write() [3/5]
void System.Diagnostics.DefaultTraceListener.Write (string message, bool useLogFile) inline private
Definition at line 113 of file DefaultTraceListener.cs.
    {
        if (message == null)
        {
            message = string.Empty;
        }
        if (base.NeedIndent && message.Length != 0)
        {
            WriteIndent();
        }
        DebugProvider.WriteCore(message);
        if (useLogFile && !string.IsNullOrEmpty(LogFileName))
        {
            WriteToLogFile(message);
        }
    }
References System.Diagnostics.DefaultTraceListener.LogFileName, System.Diagnostics.DebugProvider.WriteCore(), System.Diagnostics.TraceListener.WriteIndent(), and System.Diagnostics.DefaultTraceListener.WriteToLogFile().