Terraria: System.IServiceProvider.GetService
GetService()
object? System.IServiceProvider.GetService (Type serviceType) inherited
Implemented in System.ComponentModel.Container.Site, System.ComponentModel.MarshalByValueComponent, System.ComponentModel.NestedContainer.Site, System.ComponentModel.DataAnnotations.ValidationContext, System.ComponentModel.Design.ServiceContainer, and System.ComponentModel.LicenseContext.
Referenced by System.ComponentModel.ReflectEventDescriptor.AddEventHandler(), System.ComponentModel.ReferenceConverter.ConvertFrom(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderResetValue(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderSetValue(), System.ComponentModel.TypeDescriptor.GetAssociation(), System.ComponentModel.Component.GetService(), System.ComponentModel.MarshalByValueComponent.GetService(), System.ComponentModel.Design.ServiceContainer.GetService(), System.ComponentModel.ReferenceConverter.GetStandardValues(), System.ComponentModel.TypeDescriptor.PipelineFilter(), System.ComponentModel.ReflectEventDescriptor.RemoveEventHandler(), System.ComponentModel.ReflectPropertyDescriptor.ResetValue(), and System.ComponentModel.ReflectPropertyDescriptor.SetValue().