Terraria: Terraria.GameContent.Shaders.SepiaScreenShaderData.Update
Update()
override void Terraria.GameContent.Shaders.SepiaScreenShaderData.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.Graphics.Shaders.ScreenShaderData.
Definition at line 14 of file SepiaScreenShaderData.cs.
    {
        float x = (Main.screenPosition.Y + (float)(Main.screenHeight / 2)) / 16f;
        float num = 1f - Utils.SmoothStep((float)Main.worldSurface, (float)Main.worldSurface + 30f, x);
        Vector3 value;
        Vector3 vector = (value = new Vector3(0.191f, -0.054f, -0.221f));
        Vector3 value2 = vector * 0.5f;
        Vector3 value3 = new Vector3(0f, -0.03f, 0.15f);
        Vector3 value4 = new Vector3(-0.11f, 0.01f, 0.16f);
        float cloudAlpha = Main.cloudAlpha;
        GetDaylightPowers(out var nightlightPower, out var daylightPower, out var moonPower, out var dawnPower);
        float num2 = nightlightPower * 0.13f;
        if (Main.starGame)
        {
            float num3 = (float)Main.starGameMath() - 1f;
            nightlightPower = num3;
            daylightPower = 1f - num3;
            moonPower = num3;
            dawnPower = 1f - num3;
            num2 = nightlightPower * 0.13f;
        }
        else if (!Main.dayTime)
        {
            if (Main.GetMoonPhase() == MoonPhase.Full)
            {
                value = new Vector3(-0.19f, 0.01f, 0.22f);
                num2 += 0.07f * moonPower;
            }
            if (Main.bloodMoon)
            {
                value = new Vector3(0.2f, -0.1f, -0.221f);
                num2 = 0.2f;
            }
        }
        nightlightPower *= num;
        daylightPower *= num;
        moonPower *= num;
        dawnPower *= num;
        UseOpacity(1f);
        UseIntensity(1.4f - daylightPower * 0.2f);
        float value5 = 0.3f - num2 * nightlightPower;
        value5 = MathHelper.Lerp(value5, 0.1f, cloudAlpha);
        float value6 = 0.2f;
        value5 = MathHelper.Lerp(value5, value6, 1f - num);
        UseProgress(value5);
        Vector3 value7 = Vector3.Lerp(vector, value, moonPower);
        value7 = Vector3.Lerp(value7, value3, dawnPower);
        value7 = Vector3.Lerp(value7, value4, cloudAlpha);
        value7 = Vector3.Lerp(value7, value2, 1f - num);
        UseColor(value7);
    }
References Terraria.Main.bloodMoon, Terraria.Main.cloudAlpha, Terraria.Main.dayTime, Terraria.GameContent.Shaders.SepiaScreenShaderData.GetDaylightPowers(), Terraria.Main.GetMoonPhase(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector3.Lerp(), Terraria.Main.screenHeight, Terraria.Utils.SmoothStep(), Terraria.Main.starGame, Terraria.Main.starGameMath(), Terraria.Graphics.Shaders.ScreenShaderData.UseColor(), Terraria.Graphics.Shaders.ScreenShaderData.UseIntensity(), Terraria.Graphics.Shaders.ScreenShaderData.UseOpacity(), Terraria.Graphics.Shaders.ScreenShaderData.UseProgress(), and Terraria.Main.worldSurface.