Terraria: ReLogic.Content.AssetLoadException.AssetLoadException
AssetLoadException()
ReLogic.Content.AssetLoadException.AssetLoadException (string text, Exception innerException) inline private
Definition at line 8 of file AssetLoadException.cs.
        : base(text, innerException)
    {
    }
Referenced by ReLogic.Content.AssetLoadException.FromInvalidReader< TReaderType, TAssetType >(), ReLogic.Content.AssetLoadException.FromMissingAsset(), and ReLogic.Content.AssetLoadException.FromMissingReader().