Terraria: Microsoft.Xna.Framework.Graphics.SpriteBatch.PlatformRenderBatch
PlatformRenderBatch()
unsafe void Microsoft.Xna.Framework.Graphics.SpriteBatch.PlatformRenderBatch (Texture2D texture, SpriteInfo[] sprites, int offset, int count) inline private
Definition at line 208 of file SpriteBatch.cs.
    {
        float num = 1f / (float)texture.Width;
        float num2 = 1f / (float)texture.Height;
        while (count > 0)
        {
            SetDataOptions options = SetDataOptions.NoOverwrite;
            int num3 = count;
            if (num3 > 2048 - vertexBufferPosition)
            {
                num3 = 2048 - vertexBufferPosition;
                if (num3 < 256)
                {
                    vertexBufferPosition = 0;
                    options = SetDataOptions.Discard;
                    num3 = count;
                    if (num3 > 2048)
                    {
                        num3 = 2048;
                    }
                }
            }
            fixed (SpriteInfo* ptr = &sprites[offset])
            {
                fixed (VertexPositionColorTexture* ptr3 = &outputVertices[0])
                {
                    SpriteInfo* ptr2 = ptr;
                    VertexPositionColorTexture* ptr4 = ptr3;
                    for (int i = 0; i < num3; i++)
                    {
                        float num4;
                        float num5;
                        if (ptr2->Rotation != 0f)
{
                            num4 = (float)Math.Cos(ptr2->Rotation);
                            num5 = (float)Math.Sin(ptr2->Rotation);
                        }
                        else
{
                            num4 = 1f;
                            num5 = 0f;
                        }
                        float num6 = ((ptr2->Source.Z != 0f) ? (ptr2->Origin.X / ptr2->Source.Z) : (ptr2->Origin.X * 2E+32f));
                        float num7 = ((ptr2->Source.W != 0f) ? (ptr2->Origin.Y / ptr2->Source.W) : (ptr2->Origin.Y * 2E+32f));
                        for (int j = 0; j < 4; j++)
{
                            float num8 = xCornerOffsets[j];
                            float num9 = yCornerOffsets[j];
                            float num10 = (num8 - num6) * ptr2->Destination.Z;
                            float num11 = (num9 - num7) * ptr2->Destination.W;
                            float x = ptr2->Destination.X + num10 * num4 - num11 * num5;
                            float y = ptr2->Destination.Y + num10 * num5 + num11 * num4;
                            if ((ptr2->Effects & SpriteEffects.FlipHorizontally) != 0)
{
                                num8 = 1f - num8;
                            }
                            if ((ptr2->Effects & SpriteEffects.FlipVertically) != 0)
{
                                num9 = 1f - num9;
                            }
                            ptr4->Position.X = x;
                            ptr4->Position.Y = y;
                            ptr4->Position.Z = ptr2->Depth;
                            ptr4->Color = ptr2->Color;
                            ptr4->TextureCoordinate.X = (ptr2->Source.X + num8 * ptr2->Source.Z) * num;
                            ptr4->TextureCoordinate.Y = (ptr2->Source.Y + num9 * ptr2->Source.W) * num2;
                            ptr4++;
                        }
                        ptr2++;
                    }
                }
            }
            int num12 = sizeof(VertexPositionColorTexture);
            int offsetInBytes = vertexBufferPosition * num12 * 4;
            vertexBuffer.SetData(offsetInBytes, outputVertices, 0, num3 * 4, num12, options);
            int minVertexIndex = vertexBufferPosition * 4;
            int numVertices = num3 * 4;
            int startIndex = vertexBufferPosition * 6;
            int primitiveCount = num3 * 2;
            _parent.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, minVertexIndex, numVertices, startIndex, primitiveCount);
            vertexBufferPosition += num3;
            offset += num3;
            count -= num3;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, System.Math.Cos(), System.count, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), System.E, Microsoft.Xna.Framework.Graphics.Texture2D.Height, System.offset, System.options, Microsoft.Xna.Framework.Graphics.SpriteBatch.outputVertices, System.Math.Sin(), System.startIndex, Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexBuffer, Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexBufferPosition, Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Graphics.SpriteBatch.xCornerOffsets, and Microsoft.Xna.Framework.Graphics.SpriteBatch.yCornerOffsets.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.RenderBatch().