Terraria: Microsoft.Xna.Framework.Graphics.SpriteBatch.AllocateBuffers
AllocateBuffers()
void Microsoft.Xna.Framework.Graphics.SpriteBatch.AllocateBuffers () inline private
Definition at line 164 of file SpriteBatch.cs.
    {
        if (vertexBuffer == null || vertexBuffer.IsDisposed)
        {
            vertexBuffer = new DynamicVertexBuffer(_parent, typeof(VertexPositionColorTexture), 8192, BufferUsage.WriteOnly);
            vertexBufferPosition = 0;
            vertexBuffer.ContentLost += delegate
            {
                vertexBufferPosition = 0;
            };
        }
        if (indexBuffer == null || indexBuffer.IsDisposed)
        {
            indexBuffer = new DynamicIndexBuffer(_parent, typeof(short), 12288, BufferUsage.WriteOnly);
            indexBuffer.SetData(CreateIndexData());
            indexBuffer.ContentLost += delegate
            {
                indexBuffer.SetData(CreateIndexData());
            };
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.SpriteBatch.CreateIndexData(), Microsoft.Xna.Framework.Graphics.SpriteBatch.indexBuffer, Microsoft.Xna.Framework.Graphics.GraphicsResource.IsDisposed, Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexBuffer, and Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexBufferPosition.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.ConstructPlatformData(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.SetPlatformRenderState().