Terraria: System.Xml.Schema.XmlSchemaObjectCollection.Add
Add() [2/3]
int System.Xml.Schema.XmlSchemaObjectCollection.Add (XmlSchemaObject item) inline
Definition at line 35 of file XmlSchemaObjectCollection.cs.
    {
        return base.List.Add(item);
    }
References System.Xml.Dictionary, and System.item.
Referenced by System.Xml.Schema.XmlSchema.AddAnnotation(), System.Xml.Schema.XmlSchemaRedefine.AddAnnotation(), System.Xml.Schema.XmlSchemaInference.AddAttribute(), System.Xml.Schema.XsdBuilder.AddAttribute(), System.Xml.Schema.XmlSchemaInference.AddElement(), System.Runtime.Serialization.SchemaExporter.AddReferenceAttributes(), System.Data.XSDSchema.CollectElementsAnnotations(), System.Xml.Schema.XmlSchema.DeepClone(), System.Xml.Serialization.XmlSchemaExporter.ExportAnyType(), System.Xml.Serialization.XmlSchemaExporter.ExportAttributeAccessor(), System.Xml.Schema.XmlSchemaInference.FindMatchingElement(), System.Xml.Schema.XmlSchemaInference.MoveAttributes(), and System.Xml.Schema.XmlSchemaInference.ProcessAttributes().