Terraria: Microsoft.Xna.Framework.Graphics.SpriteBatch.DisposePlatformData
DisposePlatformData()
void Microsoft.Xna.Framework.Graphics.SpriteBatch.DisposePlatformData () inline private
Definition at line 152 of file SpriteBatch.cs.
    {
        if (vertexBuffer != null)
        {
            vertexBuffer.Dispose();
        }
        if (indexBuffer != null)
        {
            indexBuffer.Dispose();
        }
    }
References Microsoft.Xna.Framework.Graphics.IndexBuffer.Dispose(), Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose(), Microsoft.Xna.Framework.Graphics.SpriteBatch.indexBuffer, and Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexBuffer.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.Dispose().