Terraria: Microsoft.Xna.Framework.Graphics.SpriteBatch.InternalDraw
InternalDraw()
unsafe void Microsoft.Xna.Framework.Graphics.SpriteBatch.InternalDraw (Texture2D texture, ref Vector4 destination, bool scaleDestination, ref Rectangle? sourceRectangle, Color color, float rotation, ref Vector2 origin, SpriteEffects effects, float depth) inline private
Definition at line 559 of file SpriteBatch.cs.
    {
        if (texture == null)
        {
            throw new ArgumentNullException("texture", FrameworkResources.NullNotAllowed);
        }
        if (!inBeginEndPair)
        {
            throw new InvalidOperationException(FrameworkResources.BeginMustBeCalledBeforeDraw);
        }
        if (spriteQueueCount >= spriteQueue.Length)
        {
            Array.Resize(ref spriteQueue, spriteQueue.Length * 2);
        }
        fixed (SpriteInfo* ptr = &spriteQueue[spriteQueueCount])
        {
            float num = destination.Z;
            float num2 = destination.W;
            if (sourceRectangle.HasValue)
            {
                Rectangle value = sourceRectangle.Value;
                ptr->Source.X = value.X;
                ptr->Source.Y = value.Y;
                ptr->Source.Z = value.Width;
                ptr->Source.W = value.Height;
                if (scaleDestination)
                {
                    num *= (float)value.Width;
                    num2 *= (float)value.Height;
                }
            }
            else
            {
                float num3 = texture.Width;
                float num4 = texture.Height;
                ptr->Source.X = 0f;
                ptr->Source.Y = 0f;
                ptr->Source.Z = num3;
                ptr->Source.W = num4;
                if (scaleDestination)
                {
                    num *= num3;
                    num2 *= num4;
                }
            }
            ptr->Destination.X = destination.X;
            ptr->Destination.Y = destination.Y;
            ptr->Destination.Z = num;
            ptr->Destination.W = num2;
            ptr->Origin.X = origin.X;
            ptr->Origin.Y = origin.Y;
            ptr->Rotation = rotation;
            ptr->Depth = depth;
            ptr->Effects = effects;
            ptr->Color = color;
        }
        if (spriteSortMode == SpriteSortMode.Immediate)
        {
            RenderBatch(texture, spriteQueue, 0, 1);
            return;
        }
        if (spriteTextures == null || spriteTextures.Length != spriteQueue.Length)
        {
            Array.Resize(ref spriteTextures, spriteQueue.Length);
        }
        spriteTextures[spriteQueueCount] = texture;
        spriteQueueCount++;
    }
References Microsoft.Xna.Framework.FrameworkResources.BeginMustBeCalledBeforeDraw, System.destination, Microsoft.Xna.Framework.Graphics.Texture2D.Height, Microsoft.Xna.Framework.Graphics.SpriteBatch.inBeginEndPair, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, Microsoft.Xna.Framework.Graphics.SpriteBatch.RenderBatch(), Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteQueue, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteQueueCount, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteSortMode, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteTextures, System.value, and Microsoft.Xna.Framework.Graphics.Texture2D.Width.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw().