Terraria: Microsoft.Xna.Framework.Graphics.SpriteBatch.Flush
Flush()
void Microsoft.Xna.Framework.Graphics.SpriteBatch.Flush () inline private
Definition at line 628 of file SpriteBatch.cs.
    {
        SpriteInfo[] array;
        if (spriteSortMode == SpriteSortMode.Deferred)
        {
            array = spriteQueue;
        }
        else
        {
            SortSprites();
            array = sortedSprites;
        }
        int num = 0;
        Texture2D texture2D = null;
        for (int i = 0; i < spriteQueueCount; i++)
        {
            Texture2D texture2D2;
            if (spriteSortMode == SpriteSortMode.Deferred)
            {
                texture2D2 = spriteTextures[i];
            }
            else
            {
                int num2 = sortIndices[i];
                ref SpriteInfo reference = ref array[i];
                reference = spriteQueue[num2];
                texture2D2 = spriteTextures[num2];
            }
            if (texture2D2 != texture2D)
            {
                if (i > num)
                {
                    RenderBatch(texture2D, array, num, i - num);
                }
                num = i;
                texture2D = texture2D2;
            }
        }
        RenderBatch(texture2D, array, num, spriteQueueCount - num);
        Array.Clear(spriteTextures, 0, spriteQueueCount);
        spriteQueueCount = 0;
    }
References System.array, System.Array.Clear(), Microsoft.Xna.Framework.Graphics.SpriteBatch.RenderBatch(), Microsoft.Xna.Framework.Graphics.SpriteBatch.sortedSprites, Microsoft.Xna.Framework.Graphics.SpriteBatch.sortIndices, Microsoft.Xna.Framework.Graphics.SpriteBatch.SortSprites(), Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteQueue, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteQueueCount, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteSortMode, and Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteTextures.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.End().