Terraria: Microsoft.Xna.Framework.Graphics.SpriteBatch.SetRenderState
SetRenderState()
void Microsoft.Xna.Framework.Graphics.SpriteBatch.SetRenderState () inline private
Definition at line 731 of file SpriteBatch.cs.
    {
        if (blendState != null)
        {
            _parent.BlendState = blendState;
        }
        else
        {
            _parent.BlendState = BlendState.AlphaBlend;
        }
        if (depthStencilState != null)
        {
            _parent.DepthStencilState = depthStencilState;
        }
        else
        {
            _parent.DepthStencilState = DepthStencilState.None;
        }
        if (rasterizerState != null)
        {
            _parent.RasterizerState = rasterizerState;
        }
        else
        {
            _parent.RasterizerState = RasterizerState.CullCounterClockwise;
        }
        if (samplerState != null)
        {
            _parent.SamplerStates[0] = samplerState;
        }
        else
        {
            _parent.SamplerStates[0] = SamplerState.LinearClamp;
        }
        Viewport viewport = _parent.Viewport;
        float num = ((viewport.Width > 0) ? (1f / (float)viewport.Width) : 0f);
        float num2 = ((viewport.Height > 0) ? (-1f / (float)viewport.Height) : 0f);
        Matrix matrix = default(Matrix);
        matrix.M11 = num * 2f;
        matrix.M22 = num2 * 2f;
        matrix.M33 = 1f;
        matrix.M44 = 1f;
        matrix.M41 = -1f;
        matrix.M42 = 1f;
        matrix.M41 -= num;
        matrix.M42 -= num2;
        effectMatrixTransform.SetValue(transformMatrix * matrix);
        spriteEffect.CurrentTechnique.Passes[0].Apply();
        SetPlatformRenderState();
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.blendState, Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.SpriteBatch.depthStencilState, Microsoft.Xna.Framework.Graphics.SpriteBatch.effectMatrixTransform, Microsoft.Xna.Framework.Graphics.Viewport.Height, Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Microsoft.Xna.Framework.Graphics.SpriteBatch.rasterizerState, Microsoft.Xna.Framework.Graphics.SpriteBatch.samplerState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, Microsoft.Xna.Framework.Graphics.SpriteBatch.SetPlatformRenderState(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteEffect, Microsoft.Xna.Framework.Graphics.SpriteBatch.transformMatrix, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Viewport, and Microsoft.Xna.Framework.Graphics.Viewport.Width.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.End().