Terraria: ArmorShaderDataSet.GetSecondaryShader
GetSecondaryShader()
ArmorShaderData ArmorShaderDataSet.GetSecondaryShader (int id, Player player) inline
     {
         if (id != 0 && id <= _shaderDataCount && _shaderData[id - 1] != null)
         {
             return _shaderData[id - 1].GetSecondaryShader(player);
         }
         return null;
     }
References _shaderData, and _shaderDataCount.
Referenced by Projectile.AI_026(), Projectile.AI_067_FreakingPirates(), Projectile.AI_120_StardustGuardian(), Player.DashMovement(), Mount.DoConfettiMinecartEffect(), Mount.DoExhaustMinecartEffect(), Mount.DoGemMinecartEffect(), Mount.DoSteamMinecartEffect(), Player.DoubleJumpVisuals(), PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles(), Player.Hurt(), Player.JumpMovement(), Projectile.Kill(), Player.KillMe(), Player.NinjaDodge(), Player.PlayerFrame(), Player.RocketBootVisuals(), ParticleOrchestrator.Spawn_FlameWaders(), ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames(), Player.SpawnFastRunParticles(), Player.Update(), Player.UpdateArmorSets(), Mount.UpdateEffects(), Mount.UpdateFrame(), Player.UpdateMinionTarget(), Player.WallslideMovement(), Player.WingAirVisuals(), Player.WingFrame(), and Player.Yoraiz0rEye().