Terraria: Microsoft.Xna.Framework.Graphics.SpriteBatch.End
End()
void Microsoft.Xna.Framework.Graphics.SpriteBatch.End () inline
Definition at line 375 of file SpriteBatch.cs.
    {
        if (!inBeginEndPair)
        {
            throw new InvalidOperationException(FrameworkResources.BeginMustBeCalledBeforeEnd);
        }
        if (spriteSortMode != SpriteSortMode.Immediate)
        {
            SetRenderState();
        }
        else
        {
            _parent.spriteImmediateBeginCount--;
        }
        if (spriteQueueCount > 0)
        {
            Flush();
        }
        inBeginEndPair = false;
        _parent.spriteBeginCount--;
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.FrameworkResources.BeginMustBeCalledBeforeEnd, Microsoft.Xna.Framework.Graphics.SpriteBatch.Flush(), Microsoft.Xna.Framework.Graphics.SpriteBatch.inBeginEndPair, Microsoft.Xna.Framework.Graphics.SpriteBatch.SetRenderState(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.spriteBeginCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.spriteImmediateBeginCount, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteQueueCount, and Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteSortMode.
Referenced by Terraria.Graphics.TileBatch.Begin(), Terraria.Graphics.TileBatch.Begin(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw(), Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.UI.UIElement.Draw(), Terraria.Graphics.Effects.OverlayManager.Draw(), Terraria.GameContent.UI.Elements.UICharacter.DrawPets(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), ReLogic.Graphics.BasicDebugDrawer.End(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseReqest(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseReqest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseReqest(), and Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseReqest().