Terraria: System.Xml.DataPointer.MoveToOwnerElement
MoveToOwnerElement()
bool System.Xml.DataPointer.MoveToOwnerElement () inline package
Definition at line 531 of file DataPointer.cs.
    {
        RealFoliate();
        if (_node != null)
        {
            if (_column != null)
            {
                if (_fOnValue || _doc.IsTextOnly(_column) || _column.ColumnMapping != MappingType.Attribute)
                {
                    return false;
                }
                MoveTo(_node, null, fOnValue: false);
                return true;
            }
            if (_node.NodeType == XmlNodeType.Attribute)
            {
                XmlNode ownerElement = ((XmlAttribute)_node).OwnerElement;
                if (ownerElement != null)
                {
                    MoveTo(ownerElement, null, fOnValue: false);
                    return true;
                }
            }
        }
        return false;
    }
References System.Xml.DataPointer._column, System.Xml.DataPointer._doc, System.Xml.DataPointer._fOnValue, System.Xml.DataPointer._node, System.Data.DataColumn.ColumnMapping, System.Xml.Dictionary, System.Xml.XmlDataDocument.IsTextOnly(), System.Xml.DataPointer.MoveTo(), System.Xml.XmlNode.NodeType, and System.Xml.DataPointer.RealFoliate().