Terraria: System.Xml.DataPointer.MoveToAttribute
MoveToAttribute()
bool System.Xml.DataPointer.MoveToAttribute (int i) inline package
Definition at line 558 of file DataPointer.cs.
    {
        RealFoliate();
        if (i < 0)
        {
            return false;
        }
        if (_node != null && (_column == null || _column.ColumnMapping == MappingType.Attribute) && _node.NodeType == XmlNodeType.Element)
        {
            if (!IsFoliated(_node))
            {
                DataColumn dataColumn = NthColumn(Row, fAttribute: true, i, fNulls: false);
                if (dataColumn != null)
                {
                    MoveTo(_node, dataColumn, fOnValue: false);
                    return true;
                }
            }
            else
            {
                XmlNode xmlNode = _node.Attributes.Item(i);
                if (xmlNode != null)
                {
                    MoveTo(xmlNode, null, fOnValue: false);
                    return true;
                }
            }
        }
        return false;
    }
References System.Xml.DataPointer._column, System.Xml.DataPointer._node, System.Xml.XmlNode.Attributes, System.Data.DataColumn.ColumnMapping, System.Xml.Dictionary, System.Xml.DataPointer.IsFoliated(), System.Xml.XmlNamedNodeMap.Item(), System.Xml.DataPointer.MoveTo(), System.Xml.XmlNode.NodeType, System.Xml.DataPointer.NthColumn(), System.Xml.DataPointer.RealFoliate(), and System.Xml.DataPointer.Row.