Terraria: System.Xml.DataPointer.MoveToFirstChild
MoveToFirstChild()
bool System.Xml.DataPointer.MoveToFirstChild () inline package
Definition at line 429 of file DataPointer.cs.
    {
        RealFoliate();
        if (_node == null)
        {
            return false;
        }
        if (_column != null)
        {
            if (_fOnValue)
            {
                return false;
            }
            _fOnValue = true;
            return true;
        }
        if (!IsFoliated(_node))
        {
            DataColumn dataColumn = NextColumn(Row, null, fAttribute: false, fNulls: false);
            if (dataColumn != null)
            {
                MoveTo(_node, dataColumn, _doc.IsTextOnly(dataColumn));
                return true;
            }
        }
        XmlNode xmlNode = _doc.SafeFirstChild(_node);
        if (xmlNode != null)
        {
            MoveTo(xmlNode);
            return true;
        }
        return false;
    }
References System.Xml.DataPointer._column, System.Xml.DataPointer._doc, System.Xml.DataPointer._fOnValue, System.Xml.DataPointer._node, System.Xml.Dictionary, System.Xml.DataPointer.IsFoliated(), System.Xml.XmlDataDocument.IsTextOnly(), System.Xml.DataPointer.MoveTo(), System.Xml.DataPointer.NextColumn(), System.Xml.DataPointer.RealFoliate(), System.Xml.DataPointer.Row, and System.Xml.XmlDataDocument.SafeFirstChild().