Terraria: System.Xml.DataPointer.RealFoliate
RealFoliate()
void System.Xml.DataPointer.RealFoliate () inline package
Definition at line 637 of file DataPointer.cs.
    {
        if (!_bNeedFoliate)
        {
            return;
        }
        XmlNode xmlNode = null;
        if (_doc.IsTextOnly(_column))
        {
            xmlNode = _node.FirstChild;
        }
        else
        {
            if (_column.ColumnMapping == MappingType.Attribute)
            {
                xmlNode = _node.Attributes.GetNamedItem(_column.EncodedColumnName, _column.Namespace);
            }
            else
            {
                xmlNode = _node.FirstChild;
                while (xmlNode != null && (!(xmlNode.LocalName == _column.EncodedColumnName) || !(xmlNode.NamespaceURI == _column.Namespace)))
                {
                    xmlNode = xmlNode.NextSibling;
                }
            }
            if (xmlNode != null && _fOnValue)
            {
                xmlNode = xmlNode.FirstChild;
            }
        }
        if (xmlNode == null)
        {
            throw new InvalidOperationException(System.SR.DataDom_Foliation);
        }
        _node = xmlNode;
        _column = null;
        _fOnValue = false;
        _bNeedFoliate = false;
    }
References System.Xml.DataPointer._bNeedFoliate, System.Xml.DataPointer._column, System.Xml.DataPointer._doc, System.Xml.DataPointer._fOnValue, System.Xml.DataPointer._node, System.Xml.XmlNode.Attributes, System.Data.DataColumn.ColumnMapping, System.SR.DataDom_Foliation, System.Xml.Dictionary, System.Data.DataColumn.EncodedColumnName, System.Xml.XmlNode.FirstChild, System.Xml.XmlNamedNodeMap.GetNamedItem(), System.Xml.XmlDataDocument.IsTextOnly(), System.Data.DataColumn.Namespace, and System.Xml.XmlNode.NextSibling.
Referenced by System.Xml.DataPointer.IsOnNode(), System.Xml.DataPointer.MoveToAttribute(), System.Xml.DataPointer.MoveToFirstChild(), System.Xml.DataPointer.MoveToNextSibling(), System.Xml.DataPointer.MoveToOwnerElement(), and System.Xml.DataPointer.MoveToParent().