Terraria: System.Xml.DataPointer.MoveToNextSibling
MoveToNextSibling()
bool System.Xml.DataPointer.MoveToNextSibling () inline package
Definition at line 463 of file DataPointer.cs.
    {
        RealFoliate();
        if (_node != null)
        {
            if (_column != null)
            {
                if (_fOnValue && !_doc.IsTextOnly(_column))
                {
                    return false;
                }
                DataColumn dataColumn = NextColumn(Row, _column, fAttribute: false, fNulls: false);
                if (dataColumn != null)
                {
                    MoveTo(_node, dataColumn, fOnValue: false);
                    return true;
                }
                XmlNode xmlNode = _doc.SafeFirstChild(_node);
                if (xmlNode != null)
                {
                    MoveTo(xmlNode);
                    return true;
                }
            }
            else
            {
                XmlNode xmlNode2 = _doc.SafeNextSibling(_node);
                if (xmlNode2 != null)
                {
                    MoveTo(xmlNode2);
                    return true;
                }
            }
        }
        return false;
    }
References System.Xml.DataPointer._column, System.Xml.DataPointer._doc, System.Xml.DataPointer._fOnValue, System.Xml.DataPointer._node, System.Xml.Dictionary, System.Xml.XmlDataDocument.IsTextOnly(), System.Xml.DataPointer.MoveTo(), System.Xml.DataPointer.NextColumn(), System.Xml.DataPointer.RealFoliate(), System.Xml.DataPointer.Row, System.Xml.XmlDataDocument.SafeFirstChild(), and System.Xml.XmlDataDocument.SafeNextSibling().