Terraria: System.Xml.XmlWellFormedWriter.ElementScope.Set
Set()
void System.Xml.XmlWellFormedWriter.ElementScope.Set (string prefix, string localName, string namespaceUri, int prevNSTop) inline package
Definition at line 107 of file XmlWellFormedWriter.cs.
        {
            this.prevNSTop = prevNSTop;
            this.prefix = prefix;
            this.namespaceUri = namespaceUri;
            this.localName = localName;
            xmlSpace = (XmlSpace)(-1);
            xmlLang = null;
        }
References System.Xml.Dictionary, System.Xml.XmlWellFormedWriter.ElementScope.localName, System.Xml.XmlWellFormedWriter.ElementScope.namespaceUri, System.Xml.XmlWellFormedWriter.ElementScope.prefix, System.Xml.XmlWellFormedWriter.ElementScope.prevNSTop, System.Xml.XmlWellFormedWriter.ElementScope.xmlLang, System.Xml.XmlWellFormedWriter.ElementScope.xmlSpace, and System.Xml.XmlWellFormedWriter.XmlSpace.
Referenced by System.Xml.XmlWellFormedWriter.XmlWellFormedWriter(), System.Xml.XmlWellFormedWriter.WriteStartElement(), and System.Xml.XmlWellFormedWriter.WriteStartElementAsync_FinishWrite().