Terraria: CreditsRollComposer.PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies
PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies()
SegmentInforReport CreditsRollComposer.PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         int num2 = -35;
         sceneAnchorPosition.X += num2;
         int num3 = 34;
         Asset<Texture2D> val = TextureAssets.Extra[221];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
             .Then(new Actions.Sprites.Wait(60));
         _segments.Add(animationSegmentWithActions);
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 227, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255))
             .With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Wait(60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 108, sceneAnchorPosition + new Vector2(num3, 0f), _originAtBottom).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255))
             .With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Wait(60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions4 = new Segments.NPCSegment(startTime, 207, sceneAnchorPosition + new Vector2(num3 * 2 + 60, 0f), _originAtBottom).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255))
             .With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions5 = new Segments.NPCSegment(startTime, 656, sceneAnchorPosition + new Vector2(num3 * 2, 0f), _originAtBottom).Then(new Actions.NPCs.Variant(1)).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(1))
             .Then(new Actions.NPCs.Fade(255))
             .With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions6 = new Segments.NPCSegment(startTime, 540, sceneAnchorPosition + new Vector2(num3 * 4 + 100, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60));
         Asset<Texture2D> val2 = TextureAssets.Extra[238];
         Rectangle rectangle2 = val2.Frame(1, 4);
         DrawData data2 = new DrawData(val2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, SpriteEffects.FlipHorizontally);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions7 = new Segments.SpriteSegment(val2, num, data2, sceneAnchorPosition + new Vector2(60f, 2f)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51));
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions8 = new Segments.SpriteSegment(val2, num, data2, sceneAnchorPosition + new Vector2(150f, 2f)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         int num4 = 90;
         int num5 = num4 * 4;
         Segments.EmoteSegment item = new Segments.EmoteSegment(127, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item2 = new Segments.EmoteSegment(6, num + num4, num4, sceneAnchorPosition + new Vector2(num3, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         Segments.EmoteSegment item3 = new Segments.EmoteSegment(136, num + num4 * 2, num4, sceneAnchorPosition + new Vector2(num3 * 2, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         Segments.EmoteSegment item4 = new Segments.EmoteSegment(129, num + num4 * 3, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4 * 2)).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Wait(num4))
             .Then(new Actions.NPCs.LookAt(-1))
             .Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
         animationSegmentWithActions6.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), num5 / 3)).Then(new Actions.NPCs.Wait(num5 / 3)).Then(new Actions.NPCs.Move(new Vector2(0.4f, 0f), num5 / 3));
         animationSegmentWithActions5.Then(new Actions.NPCs.Move(new Vector2(-0.6f, 0f), num5 / 3)).Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), num5 / 3)).Then(new Actions.NPCs.Wait(num5 / 3));
         num += num5;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions9 = new Segments.NPCSegment(num - 60, 208, sceneAnchorPosition + new Vector2(num3 * 5 + 100, 0f), _originAtBottom).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255))
             .With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60));
         int num6 = (int)animationSegmentWithActions9.DedicatedTimeNeeded - 60;
         num += num6;
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions5.Then(new Actions.NPCs.Wait(num6));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
         Segments.EmoteSegment item5 = new Segments.EmoteSegment(128, num, num4, sceneAnchorPosition + new Vector2(num3 * 5 + 40, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         num += num4;
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions5.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions9.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         Segments.EmoteSegment item6 = new Segments.EmoteSegment(128, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item7 = new Segments.EmoteSegment(128, num, num4, sceneAnchorPosition + new Vector2(num3, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item8 = new Segments.EmoteSegment(128, num, num4, sceneAnchorPosition + new Vector2(num3 * 2, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item9 = new Segments.EmoteSegment(3, num, num4, sceneAnchorPosition + new Vector2(num3 * 5 - 10, 24f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item10 = new Segments.EmoteSegment(0, num, num4, sceneAnchorPosition + new Vector2(num3 * 4 - 20, 24f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions5.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions9.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         animationSegmentWithActions7.Then(new Actions.Sprites.SetFrameSequence(num - startTime, new Point[4]
         {
             new Point(0, 0),
             new Point(0, 1),
             new Point(0, 2),
             new Point(0, 3)
         }, 10, 0, 0));
         animationSegmentWithActions8.Then(new Actions.Sprites.SetFrameSequence(num - startTime, new Point[4]
         {
             new Point(0, 2),
             new Point(0, 3),
             new Point(0, 0),
             new Point(0, 1)
         }, 10, 0, 0));
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions6.Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions5.Then(new Actions.NPCs.Move(new Vector2(0.75f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions9.Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions7.Then(new Actions.Sprites.Fade(0f, 127));
         animationSegmentWithActions8.Then(new Actions.Sprites.Fade(0f, 127));
         animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
         num += 187;
         _segments.Add(animationSegmentWithActions7);
         _segments.Add(animationSegmentWithActions8);
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(animationSegmentWithActions4);
         _segments.Add(animationSegmentWithActions6);
         _segments.Add(animationSegmentWithActions5);
         _segments.Add(animationSegmentWithActions9);
         _segments.Add(item);
         _segments.Add(item2);
         _segments.Add(item3);
         _segments.Add(item4);
         _segments.Add(item5);
         _segments.Add(item6);
         _segments.Add(item7);
         _segments.Add(item8);
         _segments.Add(item9);
         _segments.Add(item10);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References _backgroundOffset, _emoteBubbleOffsetWhenOnLeft, _emoteBubbleOffsetWhenOnRight, _originAtBottom, _segments, Color, TextureAssets.Extra, GetSceneFixVector(), Segments.AnimationSegmentWithActions< T >.Then(), Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().