Terraria: CreditsRollComposer.PlaySegment_PrincessAndEveryoneThanksPlayer
PlaySegment_PrincessAndEveryoneThanksPlayer()
SegmentInforReport CreditsRollComposer.PlaySegment_PrincessAndEveryoneThanksPlayer (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition.Y += 40f;
         int num = -2;
         int num2 = 2;
         List<int> list = new List<int> { 228, 178, 550, 208, 160, 209 };
         List<int> list2 = new List<int> { 353, 633, 207, 588, 227, 368 };
         List<int> list3 = new List<int> { 22, 19, 18, 17, 38, 54, 108 };
         List<int> list4 = new List<int> { 663, 20, 441, 107, 124, 229, 369 };
         List<SimplifiedNPCInfo> list5 = new List<SimplifiedNPCInfo>();
         for (int i = 0; i < list.Count; i++)
         {
             int npcType = list[i];
             list5.Add(new SimplifiedNPCInfo(npcType, new Vector2(num - i, -1f)));
         }
         for (int j = 0; j < list3.Count; j++)
         {
             int npcType2 = list3[j];
             list5.Add(new SimplifiedNPCInfo(npcType2, new Vector2((float)(num - j) + 0.5f, 0f)));
         }
         for (int k = 0; k < list2.Count; k++)
         {
             int npcType3 = list2[k];
             list5.Add(new SimplifiedNPCInfo(npcType3, new Vector2(num2 + k, -1f)));
         }
         for (int l = 0; l < list4.Count; l++)
         {
             int npcType4 = list4[l];
             list5.Add(new SimplifiedNPCInfo(npcType4, new Vector2((float)(num2 + l) - 0.5f, 0f)));
         }
         int num3 = 240;
         int num4 = 400;
         int num5 = num4 + num3;
         Asset<Texture2D> val = TextureAssets.Extra[241];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(0f, -92f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> item = new Segments.SpriteSegment(val, startTime, data, sceneAnchorPosition).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51)).Then(new Actions.Sprites.Wait(num5))
             .Then(new Actions.Sprites.Fade(0f, 85));
         _segments.Add(item);
         foreach (SimplifiedNPCInfo item3 in list5)
         {
             item3.SpawnNPC(AddWavingNPC, sceneAnchorPosition, startTime, num5);
         }
         float num6 = 3f;
         float num7 = -0.05f;
         int num8 = 60;
         float num9 = num6 * (float)num8 + num7 * ((float)(num8 * num8) * 0.5f);
         int num10 = startTime + num3;
         int num11 = 51;
         Segments.AnimationSegmentWithActions<Player> item2 = new Segments.PlayerSegment(num10 - num8 + num11, sceneAnchorPosition + new Vector2(0f, 0f - num9), _originAtBottom).UseShaderEffect(new Segments.PlayerSegment.ImmediateSpritebatchForPlayerDyesEffect()).Then(new Actions.Players.Fade(0f)).With(new Actions.Players.LookAt(1))
             .With(new Actions.Players.Fade(1f, num8))
             .Then(new Actions.Players.Wait(num4 / 2))
             .With(new Actions.Players.MoveWithAcceleration(new Vector2(0f, num6), new Vector2(0f, num7), num8))
             .Then(new Actions.Players.Wait(num4 / 2 - 60))
             .With(new Actions.Players.LookAt(-1))
             .Then(new Actions.Players.Wait(120))
             .With(new Actions.Players.LookAt(1))
             .Then(new Actions.Players.Fade(0f, 85));
         _segments.Add(item2);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num5 + 85 + 60;
         return result;
     }
References _originAtBottom, _segments, AddWavingNPC(), Color, TextureAssets.Extra, CreditsRollComposer.SimplifiedNPCInfo.SpawnNPC(), Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.PlayerSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments(), and FillSegments_Test().