Terraria: CreditsRollComposer.AddWavingNPC
AddWavingNPC()
void CreditsRollComposer.AddWavingNPC (int npcType, Vector2 sceneAnchoePosition, int lookDirection, int fromTime, int duration, int timeToJumpAt) inline private
     {
         int num = 0;
         float num2 = 4f;
         float num3 = 0.2f;
         float num4 = num2 * 2f / num3;
         int num5 = NPCID.Sets.AttackType[npcType] * 6 + npcType % 13 * 2 + 20;
         int num6 = 0;
         if (npcType % 7 != 0)
         {
             num6 = 0;
         }
         bool num7 = npcType == 663 || npcType == 108;
         bool flag = false;
         if (num7)
         {
             num6 = 180;
         }
         int num8 = 240;
         int num9 = lookDirection;
         int num10 = -1;
         int duration2 = 0;
         switch (npcType)
         {
         case 54:
         case 107:
         case 227:
         case 229:
         case 353:
         case 550:
         case 663:
             num9 *= -1;
             break;
         }
         if ((uint)(npcType - 207) <= 2u || npcType == 228 || (uint)(npcType - 368) <= 1u)
         {
             flag = true;
         }
         switch (npcType)
         {
         case 107:
             num10 = 0;
             break;
         case 208:
             num10 = 127;
             break;
         case 353:
             num10 = 136;
             break;
         case 54:
             num10 = 126;
             break;
         case 368:
             num10 = 15;
             break;
         case 229:
             num10 = 85;
             break;
         }
         if (num10 != -1)
         {
             duration2 = npcType % 6 * 20 + 60;
         }
         int num11 = duration - timeToJumpAt - num - num8;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions = new Segments.NPCSegment(fromTime, npcType, sceneAnchoePosition, _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).With(new Actions.NPCs.LookAt(num9));
         if (flag)
         {
             animationSegmentWithActions.With(new Actions.NPCs.PartyHard());
         }
         animationSegmentWithActions.Then(new Actions.NPCs.Wait(num8)).Then(new Actions.NPCs.LookAt(lookDirection)).Then(new Actions.NPCs.Wait(timeToJumpAt))
             .Then(new Actions.NPCs.MoveWithAcceleration(new Vector2(0f, 0f - num2), new Vector2(0f, num3), (int)num4))
             .With(new Actions.NPCs.Move(new Vector2(0f, 1E-05f), (int)num4))
             .Then(new Actions.NPCs.Wait(num11 - 90 + num5))
             .Then(new Actions.NPCs.Wait(90 - num5));
         if (num6 > 0)
         {
             animationSegmentWithActions.With(new Actions.NPCs.Blink(num6));
         }
         animationSegmentWithActions.Then(new Actions.NPCs.Fade(3, 85));
         if (npcType == 663)
         {
             AddEmote(sceneAnchoePosition, fromTime, duration, num5, 17, lookDirection);
         }
         if (num10 != -1)
         {
             AddEmote(sceneAnchoePosition, fromTime, duration2, 0, num10, num9);
         }
         _segments.Add(animationSegmentWithActions);
     }
References _originAtBottom, _segments, AddEmote(), NPCID.Sets.AttackType, E, and Segments.AnimationSegmentWithActions< T >.Then().
Referenced by PlaySegment_PrincessAndEveryoneThanksPlayer().