Terraria: CreditsRollComposer.PlaySegment_Grox_GuideRunningFromZombie
PlaySegment_Grox_GuideRunningFromZombie()
SegmentInforReport CreditsRollComposer.PlaySegment_Grox_GuideRunningFromZombie (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         int num2 = 12;
         sceneAnchorPosition.X += num2;
         int num3 = 24;
         Asset<Texture2D> val = TextureAssets.Extra[218];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60));
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 3, sceneAnchorPosition + new Vector2(num3 + 60, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 60));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait((int)animationSegmentWithActions2.DedicatedTimeNeeded));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         animationSegmentWithActions2.Then(new Actions.NPCs.ZombieKnockOnDoor(60));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(60));
         num += 60;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(num, 22, sceneAnchorPosition + new Vector2(-30f, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 60));
         animationSegmentWithActions2.Then(new Actions.NPCs.ZombieKnockOnDoor((int)animationSegmentWithActions3.DedicatedTimeNeeded));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait((int)animationSegmentWithActions3.DedicatedTimeNeeded));
         num += (int)animationSegmentWithActions3.DedicatedTimeNeeded;
         int num4 = 90;
         Segments.EmoteSegment item = new Segments.EmoteSegment(87, num, num4, sceneAnchorPosition + new Vector2(-4f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
         animationSegmentWithActions2.Then(new Actions.NPCs.ZombieKnockOnDoor(num4));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4 - 1));
         num += num4;
         int num5 = 50;
         Segments.EmoteSegment item2 = new Segments.EmoteSegment(3, num, num5, sceneAnchorPosition + new Vector2(-4f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         val = TextureAssets.Extra[219];
         rectangle = val.Frame();
         data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(num2, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions4 = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(1f));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num5));
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.4f, 0f), num5));
         animationSegmentWithActions4.Then(new Actions.Sprites.Wait(num5));
         num += num5;
         Segments.EmoteSegment item3 = new Segments.EmoteSegment(134, num, num4, sceneAnchorPosition + new Vector2(0f, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None, new Vector2(-0.6f, 0f));
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(-0.6f, 0f), num4));
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.4f, 0f), num4));
         animationSegmentWithActions4.Then(new Actions.Sprites.Wait(num4));
         num += num4;
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(-0.6f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.4f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions4.Then(new Actions.Sprites.Fade(0f, 127));
         num += 187;
         _segments.Add(animationSegmentWithActions);
         _segments.Add(animationSegmentWithActions4);
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(item);
         _segments.Add(item2);
         _segments.Add(item3);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References _backgroundOffset, _emoteBubbleOffsetWhenOnLeft, _emoteBubbleOffsetWhenOnRight, _originAtBottom, _segments, Color, TextureAssets.Extra, GetSceneFixVector(), Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().