Terraria: CreditsRollComposer.PlaySegment_TinkererAndMechanic
PlaySegment_TinkererAndMechanic()
SegmentInforReport CreditsRollComposer.PlaySegment_TinkererAndMechanic (int startTime, Vector2 sceneAnchorPosition) inline private
     {
         sceneAnchorPosition += GetSceneFixVector();
         int num = startTime;
         Asset<Texture2D> val = TextureAssets.Extra[237];
         Rectangle rectangle = val.Frame();
         DrawData data = new DrawData(val.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(0f, -42f), 1f, SpriteEffects.None);
         Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(val, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60));
         _segments.Add(animationSegmentWithActions);
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 107, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 60))
             .Then(new Actions.NPCs.Wait(60));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait((int)animationSegmentWithActions2.DedicatedTimeNeeded));
         num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
         int num2 = 24;
         Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(num, 124, sceneAnchorPosition + new Vector2(120 + num2, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
             .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60));
         num += (int)animationSegmentWithActions3.DedicatedTimeNeeded;
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait((int)animationSegmentWithActions3.DedicatedTimeNeeded));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait((int)animationSegmentWithActions3.DedicatedTimeNeeded));
         int num3 = 120;
         Segments.EmoteSegment item = new Segments.EmoteSegment(0, num, num3, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnLeft, SpriteEffects.FlipHorizontally);
         Segments.EmoteSegment item2 = new Segments.EmoteSegment(0, num, num3, sceneAnchorPosition + new Vector2(60 + num2, 0f) + _emoteBubbleOffsetWhenOnRight, SpriteEffects.None);
         animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num3));
         animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num3));
         animationSegmentWithActions.Then(new Actions.Sprites.Wait(num3));
         num += num3;
         animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
         animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
         num += 187;
         _segments.Add(animationSegmentWithActions2);
         _segments.Add(animationSegmentWithActions3);
         _segments.Add(item);
         _segments.Add(item2);
         SegmentInforReport result = default(SegmentInforReport);
         result.totalTime = num - startTime;
         return result;
     }
References Color, Segments.AnimationSegmentWithActions< T >.DedicatedTimeNeeded, TextureAssets.Extra, Segments.AnimationSegmentWithActions< T >.Then(), SegmentInforReport.totalTime, Segments.SpriteSegment.UseShaderEffect(), and Asset< T >.Value.
Referenced by FillSegments().