Terraria: CreditsRollComposer.FillSegments
FillSegments()
void CreditsRollComposer.FillSegments (List< IAnimationSegment > segmentsList, out int endTime, bool inGame) inline
     {
         _segments = segmentsList;
         int num = 0;
         int num2 = 80;
         Vector2 vector = Vector2.UnitY * -1f * num2;
         int num3 = 210;
         Vector2 vector2 = vector + Vector2.UnitX * 200f;
         Vector2 vector3 = vector2;
         if (!inGame)
         {
             vector3 = (vector2 = Vector2.UnitY * 80f);
         }
         int num4 = num3 * 3;
         int num5 = num3 * 3;
         int num6 = num4 - num5;
         if (!inGame)
         {
             num5 = 180;
             num6 = num4 - num5;
         }
         num += num5;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Creator", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_GuideRunningFromZombie(num, vector2).totalTime;
         num += num3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_ExecutiveProducer", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk(num, vector2).totalTime;
         num += num3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Designer", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes(num, vector2).totalTime;
         num += num3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Programming", vector2).totalTime;
         num += num3;
         num += PlaySegment_TinkererAndMechanic(num, vector2).totalTime;
         num += num3;
         vector2.X *= 0f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Graphics", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_DryadSayingByeToTavernKeep(num, vector2).totalTime;
         num += num3;
         vector2 = vector3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Music", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies(num, vector2).totalTime;
         num += num3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Sound", vector2).totalTime;
         num += num3;
         num += PlaySegment_ClothierChasingTruffle(num, vector2).totalTime;
         num += num3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Dialog", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_AnglerAndPirateTalkAboutFish(num, vector2).totalTime;
         num += num3;
         vector2.X *= 0f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_QualityAssurance", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer(num, vector2).totalTime;
         num += num3;
         vector2 = vector3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_BusinessDevelopment", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_SkeletonMerchantSearchesThroughBones(num, vector2).totalTime;
         num += num3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Marketing", vector2).totalTime;
         num += num3;
         num += PlaySegment_DryadTurningToTree(num, vector2).totalTime;
         num += num3;
         vector2.X *= -1f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_PublicRelations", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_SteampunkerRepairingCyborg(num, vector2).totalTime;
         num += num3;
         vector2.X *= 0f;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Webmaster", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_SantaAndTaxCollectorThrowingPresents(num, vector2).totalTime;
         num += num3;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_Playtesting", vector2).totalTime;
         num += num3;
         num += PlaySegment_Grox_WitchDoctorGoingToHisPeople(num, vector2).totalTime;
         num += num3;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_SpecialThanksto", vector2).totalTime;
         num += num3;
         num += PlaySegment_PrincessAndEveryoneThanksPlayer(num, vector2).totalTime;
         num += num3;
         num += PlaySegment_TextRoll(num, "CreditsRollCategory_EndingNotes", vector2).totalTime;
         num += num6;
         _endTime = num + 10;
         endTime = _endTime;
     }
References _endTime, _segments, PlaySegment_ClothierChasingTruffle(), PlaySegment_DryadTurningToTree(), PlaySegment_Grox_AnglerAndPirateTalkAboutFish(), PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes(), PlaySegment_Grox_DryadSayingByeToTavernKeep(), PlaySegment_Grox_GuideRunningFromZombie(), PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk(), PlaySegment_Grox_SantaAndTaxCollectorThrowingPresents(), PlaySegment_Grox_SkeletonMerchantSearchesThroughBones(), PlaySegment_Grox_SteampunkerRepairingCyborg(), PlaySegment_Grox_WitchDoctorGoingToHisPeople(), PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies(), PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer(), PlaySegment_PrincessAndEveryoneThanksPlayer(), PlaySegment_TextRoll(), PlaySegment_TinkererAndMechanic(), and SegmentInforReport.totalTime.
Referenced by CreditsRollSky.EnsureSegmentsAreMade().