Terraria: GraniteBiome.PlaceDecorations
PlaceDecorations()
void GraniteBiome.PlaceDecorations (Point tileOrigin, Rectangle magmaMapArea) inline private
     {
         FastRandom fastRandom = new FastRandom(Main.ActiveWorldFileData.Seed).WithModifier(65440uL);
         for (int i = magmaMapArea.Left; i < magmaMapArea.Right; i++)
         {
             for (int j = magmaMapArea.Top; j < magmaMapArea.Bottom; j++)
             {
                 Magma magma = _sourceMagmaMap[i, j];
                 int num = i + tileOrigin.X;
                 int num2 = j + tileOrigin.Y;
                 if (!magma.IsActive)
                 {
                     continue;
                 }
                 WorldUtils.TileFrame(num, num2);
                 WorldGen.SquareWallFrame(num, num2);
                 FastRandom fastRandom2 = fastRandom.WithModifier(num, num2);
                 if (fastRandom2.Next(8) == 0 && GenBase._tiles[num, num2].active())
                 {
                     if (!GenBase._tiles[num, num2 + 1].active())
                     {
                         WorldGen.PlaceUncheckedStalactite(num, num2 + 1, fastRandom2.Next(2) == 0, fastRandom2.Next(3), spiders: false);
                     }
                     if (!GenBase._tiles[num, num2 - 1].active())
                     {
                         WorldGen.PlaceUncheckedStalactite(num, num2 - 1, fastRandom2.Next(2) == 0, fastRandom2.Next(3), spiders: false);
                     }
                 }
                 if (fastRandom2.Next(2) == 0)
                 {
                     Tile.SmoothSlope(num, num2);
                 }
             }
         }
     }
References _sourceMagmaMap, GenBase._tiles, Tile.active(), Main.ActiveWorldFileData, GraniteBiome.Magma.IsActive, FastRandom.Next(), WorldGen.PlaceUncheckedStalactite(), WorldFileData.Seed, Tile.SmoothSlope(), WorldGen.SquareWallFrame(), WorldUtils.TileFrame(), and FastRandom.WithModifier().
Referenced by Place().