Terraria: GraniteBiome.PlaceGranite
PlaceGranite()
void GraniteBiome.PlaceGranite (Point tileOrigin, Rectangle magmaMapArea) inline private
     {
         bool flag = ShouldUseLava(tileOrigin);
         ushort type = 368;
         ushort wall = 180;
         if (WorldGen.drunkWorldGen)
         {
             type = 367;
             wall = 178;
         }
         for (int i = magmaMapArea.Left; i < magmaMapArea.Right; i++)
         {
             for (int j = magmaMapArea.Top; j < magmaMapArea.Bottom; j++)
             {
                 Magma magma = _sourceMagmaMap[i, j];
                 if (!magma.IsActive)
                 {
                     continue;
                 }
                 Tile tile = GenBase._tiles[tileOrigin.X + i, tileOrigin.Y + j];
                 double num = Math.Sin((double)(tileOrigin.Y + j) * 0.4) * 0.7 + 1.2;
                 double num2 = 0.2 + 0.5 / Math.Sqrt(Math.Max(0.0, magma.Pressure - magma.Resistance));
                 if (Math.Max(1.0 - Math.Max(0.0, num * num2), magma.Pressure / 15.0) > 0.35 + (WorldGen.SolidTile(tileOrigin.X + i, tileOrigin.Y + j) ? 0.0 : 0.5))
                 {
                     if (TileID.Sets.Ore[tile.type])
                     {
                         tile.ResetToType(tile.type);
                     }
                     else
                     {
                         tile.ResetToType(type);
                     }
                     tile.wall = wall;
                 }
                 else if (magma.Resistance < 0.01)
                 {
                     WorldUtils.ClearTile(tileOrigin.X + i, tileOrigin.Y + j);
                     tile.wall = wall;
                 }
                 if (tile.liquid > 0 && flag)
                 {
                     tile.liquidType(1);
                 }
             }
         }
     }
References _sourceMagmaMap, GenBase._tiles, WorldUtils.ClearTile(), WorldGen.drunkWorldGen, GraniteBiome.Magma.IsActive, Tile.liquid, Tile.liquidType(), TileID.Sets.Ore, GraniteBiome.Magma.Pressure, Tile.ResetToType(), GraniteBiome.Magma.Resistance, ShouldUseLava(), WorldGen.SolidTile(), Tile.type, and Tile.wall.
Referenced by Place().