Terraria: System.Globalization.GregorianCalendar.GetDefaultInstance
GetDefaultInstance()
static Calendar System.Globalization.GregorianCalendar.GetDefaultInstance () inline static package
Definition at line 71 of file GregorianCalendar.cs.
    {
        return s_defaultInstance ?? (s_defaultInstance = new GregorianCalendar());
    }
References System.Globalization.GregorianCalendar.GregorianCalendar(), and System.Globalization.GregorianCalendar.s_defaultInstance.
Referenced by System.DateTimeParse.CheckDefaultDateTime(), System.DateTimeParse.ConfigureFormatOS(), System.DateTimeParse.ConfigureFormatR(), System.DateTimeFormat.ExpandPredefinedFormat(), System.DateTimeParse.ExpandPredefinedFormat(), System.Globalization.GregorianCalendarHelper.GetWeekOfYear(), System.Globalization.EastAsianLunisolarCalendar.LunarToTime(), System.DateTimeParse.ParseISO8601(), and System.Globalization.EastAsianLunisolarCalendar.TimeToLunar().