Terraria: GraniteBiome.Place
Place()
override bool GraniteBiome.Place (Point origin, StructureMap structures) inline virtual
Implements GenStructure.
     {
         if (GenBase._tiles[origin.X, origin.Y].active())
         {
             return false;
         }
         origin.X -= _sourceMagmaMap.GetLength(0) / 2;
         origin.Y -= _sourceMagmaMap.GetLength(1) / 2;
         BuildMagmaMap(origin);
         SimulatePressure(out var effectedMapArea);
         PlaceGranite(origin, effectedMapArea);
         CleanupTiles(origin, effectedMapArea);
         PlaceDecorations(origin, effectedMapArea);
         structures.AddStructure(effectedMapArea, 8);
         return true;
     }
References _sourceMagmaMap, GenBase._tiles, Tile.active(), StructureMap.AddStructure(), BuildMagmaMap(), CleanupTiles(), PlaceDecorations(), PlaceGranite(), and SimulatePressure().