Terraria: Terraria.GameContent.Golf.GolfState.Update
Update()
void Terraria.GameContent.Golf.GolfState.Update () inline
Definition at line 123 of file GolfState.cs.
    {
        UpdateScoreTime();
        Projectile lastHitBall = GetLastHitBall();
        if (lastHitBall == null)
        {
            _waitingForBallToSettle = false;
            return;
        }
        if (_waitingForBallToSettle)
        {
            _waitingForBallToSettle = (int)lastHitBall.localAI[1] == 1;
        }
        bool flag = false;
        int type = Main.LocalPlayer.HeldItem.type;
        if (type == 3611)
        {
            flag = true;
        }
        if (!Item.IsAGolfingItem(Main.LocalPlayer.HeldItem) && !flag)
        {
            _waitingForBallToSettle = false;
        }
    }
References Terraria.GameContent.Golf.GolfState._waitingForBallToSettle, Terraria.GameContent.Golf.GolfState.GetLastHitBall(), Terraria.Player.HeldItem, Terraria.Item.IsAGolfingItem(), Terraria.Projectile.localAI, Terraria.Main.LocalPlayer, Terraria.Item.type, and Terraria.GameContent.Golf.GolfState.UpdateScoreTime().