Terraria: IPCBase.ProcessDataArriveEvent
ProcessDataArriveEvent()
virtual void IPCBase.ProcessDataArriveEvent () inline virtual inherited
     {
         if (!HaveDataToRead())
         {
             return;
         }
         List<List<byte>> packList = GetPackList();
         if (packList == null || _onDataArrive == null)
         {
             return;
         }
         foreach (List<byte> item in packList)
         {
             _onDataArrive(item.ToArray());
         }
     }
References IPCBase._onDataArrive, IPCBase.GetPackList(), and IPCBase.HaveDataToRead().
Referenced by IPCClient.CheckFlagAndFireEvent(), and CheckFlagAndFireEvent().