Terraria: System.Diagnostics.Tracing.RuntimeEventSource.OnEventCommand
OnEventCommand()
override void System.Diagnostics.Tracing.RuntimeEventSource.OnEventCommand (EventCommandEventArgs command) inline protected virtual
Reimplemented from System.Diagnostics.Tracing.EventSource.
Definition at line 95 of file RuntimeEventSource.cs.
    {
        if (command.Command != EventCommand.Enable)
        {
            return;
        }
        if (_cpuTimeCounter == null)
        {
            _cpuTimeCounter = new PollingCounter("cpu-usage", this, () => RuntimeEventSourceHelper.GetCpuUsage())
            {
                DisplayName = "CPU Usage",
                DisplayUnits = "%"
            };
        }
        if (_workingSetCounter == null)
        {
            _workingSetCounter = new PollingCounter("working-set", this, () => Environment.WorkingSet / 1000000)
            {
                DisplayName = "Working Set",
                DisplayUnits = "MB"
            };
        }
        if (_gcHeapSizeCounter == null)
        {
            _gcHeapSizeCounter = new PollingCounter("gc-heap-size", this, () => GC.GetTotalMemory(forceFullCollection: false) / 1000000)
            {
                DisplayName = "GC Heap Size",
                DisplayUnits = "MB"
            };
        }
        if (_gen0GCCounter == null)
        {
            _gen0GCCounter = new IncrementingPollingCounter("gen-0-gc-count", this, () => GC.CollectionCount(0))
            {
                DisplayName = "Gen 0 GC Count",
                DisplayRateTimeScale = new TimeSpan(0, 1, 0)
            };
        }
        if (_gen1GCCounter == null)
        {
            _gen1GCCounter = new IncrementingPollingCounter("gen-1-gc-count", this, () => GC.CollectionCount(1))
            {
                DisplayName = "Gen 1 GC Count",
                DisplayRateTimeScale = new TimeSpan(0, 1, 0)
            };
        }
        if (_gen2GCCounter == null)
        {
            _gen2GCCounter = new IncrementingPollingCounter("gen-2-gc-count", this, () => GC.CollectionCount(2))
            {
                DisplayName = "Gen 2 GC Count",
                DisplayRateTimeScale = new TimeSpan(0, 1, 0)
            };
        }
        if (_threadPoolThreadCounter == null)
        {
            _threadPoolThreadCounter = new PollingCounter("threadpool-thread-count", this, () => ThreadPool.ThreadCount)
            {
                DisplayName = "ThreadPool Thread Count"
            };
        }
        if (_monitorContentionCounter == null)
        {
            _monitorContentionCounter = new IncrementingPollingCounter("monitor-lock-contention-count", this, () => Monitor.LockContentionCount)
            {
                DisplayName = "Monitor Lock Contention Count",
                DisplayRateTimeScale = new TimeSpan(0, 0, 1)
            };
        }
        if (_threadPoolQueueCounter == null)
        {
            _threadPoolQueueCounter = new PollingCounter("threadpool-queue-length", this, () => ThreadPool.PendingWorkItemCount)
            {
                DisplayName = "ThreadPool Queue Length"
            };
        }
        if (_completedItemsCounter == null)
        {
            _completedItemsCounter = new IncrementingPollingCounter("threadpool-completed-items-count", this, () => ThreadPool.CompletedWorkItemCount)
            {
                DisplayName = "ThreadPool Completed Work Item Count",
                DisplayRateTimeScale = new TimeSpan(0, 0, 1)
            };
        }
        if (_allocRateCounter == null)
        {
            _allocRateCounter = new IncrementingPollingCounter("alloc-rate", this, () => GC.GetTotalAllocatedBytes())
            {
                DisplayName = "Allocation Rate",
                DisplayUnits = "B",
                DisplayRateTimeScale = new TimeSpan(0, 0, 1)
            };
        }
        if (_timerCounter == null)
        {
            _timerCounter = new PollingCounter("active-timer-count", this, () => Timer.ActiveCount)
            {
                DisplayName = "Number of Active Timers"
            };
        }
        if (_fragmentationCounter == null)
        {
            _fragmentationCounter = new PollingCounter("gc-fragmentation", this, delegate
            {
                GCMemoryInfo gCMemoryInfo = GC.GetGCMemoryInfo();
                return (gCMemoryInfo.HeapSizeBytes == 0L) ? 0.0 : ((double)gCMemoryInfo.FragmentedBytes * 100.0 / (double)gCMemoryInfo.HeapSizeBytes);
            })
            {
                DisplayName = "GC Fragmentation",
                DisplayUnits = "%"
            };
        }
        if (_committedCounter == null)
        {
            _committedCounter = new PollingCounter("gc-committed", this, () => GC.GetGCMemoryInfo().TotalCommittedBytes / 1000000)
            {
                DisplayName = "GC Committed Bytes",
                DisplayUnits = "MB"
            };
        }
        if (_exceptionCounter == null)
        {
            _exceptionCounter = new IncrementingPollingCounter("exception-count", this, () => Exception.GetExceptionCount())
            {
                DisplayName = "Exception Count",
                DisplayRateTimeScale = new TimeSpan(0, 0, 1)
            };
        }
        if (_gcTimeCounter == null)
        {
            _gcTimeCounter = new PollingCounter("time-in-gc", this, () => GC.GetLastGCPercentTimeInGC())
            {
                DisplayName = "% Time in GC since last GC",
                DisplayUnits = "%"
            };
        }
        if (_gen0SizeCounter == null)
        {
            _gen0SizeCounter = new PollingCounter("gen-0-size", this, () => GC.GetGenerationSize(0))
            {
                DisplayName = "Gen 0 Size",
                DisplayUnits = "B"
            };
        }
        if (_gen1SizeCounter == null)
        {
            _gen1SizeCounter = new PollingCounter("gen-1-size", this, () => GC.GetGenerationSize(1))
            {
                DisplayName = "Gen 1 Size",
                DisplayUnits = "B"
            };
        }
        if (_gen2SizeCounter == null)
        {
            _gen2SizeCounter = new PollingCounter("gen-2-size", this, () => GC.GetGenerationSize(2))
            {
                DisplayName = "Gen 2 Size",
                DisplayUnits = "B"
            };
        }
        if (_lohSizeCounter == null)
        {
            _lohSizeCounter = new PollingCounter("loh-size", this, () => GC.GetGenerationSize(3))
            {
                DisplayName = "LOH Size",
                DisplayUnits = "B"
            };
        }
        if (_pohSizeCounter == null)
        {
            _pohSizeCounter = new PollingCounter("poh-size", this, () => GC.GetGenerationSize(4))
            {
                DisplayName = "POH (Pinned Object Heap) Size",
                DisplayUnits = "B"
            };
        }
        if (_assemblyCounter == null)
        {
            _assemblyCounter = new PollingCounter("assembly-count", this, () => Assembly.GetAssemblyCount())
            {
                DisplayName = "Number of Assemblies Loaded"
            };
        }
        if (_ilBytesJittedCounter == null)
        {
            _ilBytesJittedCounter = new PollingCounter("il-bytes-jitted", this, () => JitInfo.GetCompiledILBytes())
            {
                DisplayName = "IL Bytes Jitted",
                DisplayUnits = "B"
            };
        }
        if (_methodsJittedCounter == null)
        {
            _methodsJittedCounter = new PollingCounter("methods-jitted-count", this, () => JitInfo.GetCompiledMethodCount())
            {
                DisplayName = "Number of Methods Jitted"
            };
        }
        if (_jitTimeCounter == null)
        {
            _jitTimeCounter = new IncrementingPollingCounter("time-in-jit", this, () => JitInfo.GetCompilationTime().TotalMilliseconds)
            {
                DisplayName = "Time spent in JIT",
                DisplayUnits = "ms",
                DisplayRateTimeScale = new TimeSpan(0, 0, 1)
            };
        }
        AppContext.LogSwitchValues(this);
    }
References System.Diagnostics.Tracing.RuntimeEventSource._allocRateCounter, System.Diagnostics.Tracing.RuntimeEventSource._assemblyCounter, System.Diagnostics.Tracing.RuntimeEventSource._committedCounter, System.Diagnostics.Tracing.RuntimeEventSource._completedItemsCounter, System.Diagnostics.Tracing.RuntimeEventSource._cpuTimeCounter, System.Diagnostics.Tracing.RuntimeEventSource._exceptionCounter, System.Diagnostics.Tracing.RuntimeEventSource._fragmentationCounter, System.Diagnostics.Tracing.RuntimeEventSource._gcHeapSizeCounter, System.Diagnostics.Tracing.RuntimeEventSource._gcTimeCounter, System.Diagnostics.Tracing.RuntimeEventSource._gen0GCCounter, System.Diagnostics.Tracing.RuntimeEventSource._gen0SizeCounter, System.Diagnostics.Tracing.RuntimeEventSource._gen1GCCounter, System.Diagnostics.Tracing.RuntimeEventSource._gen1SizeCounter, System.Diagnostics.Tracing.RuntimeEventSource._gen2GCCounter, System.Diagnostics.Tracing.RuntimeEventSource._gen2SizeCounter, System.Diagnostics.Tracing.RuntimeEventSource._ilBytesJittedCounter, System.Diagnostics.Tracing.RuntimeEventSource._jitTimeCounter, System.Diagnostics.Tracing.RuntimeEventSource._lohSizeCounter, System.Diagnostics.Tracing.RuntimeEventSource._methodsJittedCounter, System.Diagnostics.Tracing.RuntimeEventSource._monitorContentionCounter, System.Diagnostics.Tracing.RuntimeEventSource._pohSizeCounter, System.Diagnostics.Tracing.RuntimeEventSource._threadPoolQueueCounter, System.Diagnostics.Tracing.RuntimeEventSource._threadPoolThreadCounter, System.Diagnostics.Tracing.RuntimeEventSource._timerCounter, System.Diagnostics.Tracing.RuntimeEventSource._workingSetCounter, System.Threading.Timer.ActiveCount, System.GC.CollectionCount(), System.Diagnostics.Tracing.EventCommandEventArgs.Command, System.Threading.ThreadPool.CompletedWorkItemCount, System.GCMemoryInfo.FragmentedBytes, System.Reflection.Assembly.GetAssemblyCount(), System.Runtime.JitInfo.GetCompilationTime(), System.Runtime.JitInfo.GetCompiledILBytes(), System.Runtime.JitInfo.GetCompiledMethodCount(), System.Diagnostics.Tracing.RuntimeEventSourceHelper.GetCpuUsage(), System.Exception.GetExceptionCount(), System.GC.GetGCMemoryInfo(), System.GC.GetGenerationSize(), System.GC.GetLastGCPercentTimeInGC(), System.GC.GetTotalAllocatedBytes(), System.GC.GetTotalMemory(), System.GCMemoryInfo.HeapSizeBytes, System.L, System.Threading.Monitor.LockContentionCount, System.AppContext.LogSwitchValues(), System.Threading.ThreadPool.PendingWorkItemCount, System.Threading.ThreadPool.ThreadCount, and System.Environment.WorkingSet.