Terraria: System.Threading.PortableThreadPool.BlockingConfig.BlockingConfig
BlockingConfig()
static System.Threading.PortableThreadPool.BlockingConfig.BlockingConfig () inline static private
Definition at line 56 of file PortableThreadPool.cs.
        {
            IsCooperativeBlockingEnabled = AppContextConfigHelper.GetBooleanConfig("System.Threading.ThreadPool.Blocking.CooperativeBlocking", defaultValue: true);
            int int32Config = AppContextConfigHelper.GetInt32Config("System.Threading.ThreadPool.Blocking.ThreadsToAddWithoutDelay_ProcCountFactor", 1, allowNegative: false);
            int int32Config2 = AppContextConfigHelper.GetInt32Config("System.Threading.ThreadPool.Blocking.ThreadsPerDelayStep_ProcCountFactor", 1, allowNegative: false);
            DelayStepMs = (uint)AppContextConfigHelper.GetInt32Config("System.Threading.ThreadPool.Blocking.DelayStepMs", 25, allowNegative: false);
            MaxDelayMs = (uint)AppContextConfigHelper.GetInt32Config("System.Threading.ThreadPool.Blocking.MaxDelayMs", 250, allowNegative: false);
            int processorCount = Environment.ProcessorCount;
            ThreadsToAddWithoutDelay = (short)(processorCount * int32Config);
            if (ThreadsToAddWithoutDelay > short.MaxValue || ThreadsToAddWithoutDelay / processorCount != int32Config)
            {
                ThreadsToAddWithoutDelay = short.MaxValue;
            }
            int32Config2 = Math.Max(1, int32Config2);
            short num = (short)(32767 - ThreadsToAddWithoutDelay);
            ThreadsPerDelayStep = (short)(processorCount * int32Config2);
            if (ThreadsPerDelayStep > num || ThreadsPerDelayStep / processorCount != int32Config2)
            {
                ThreadsPerDelayStep = num;
            }
            MaxDelayMs = Math.Max(1u, Math.Min(MaxDelayMs, 500u));
            DelayStepMs = Math.Max(1u, Math.Min(DelayStepMs, MaxDelayMs));
        }
References System.Threading.PortableThreadPool.BlockingConfig.DelayStepMs, System.AppContextConfigHelper.GetBooleanConfig(), System.AppContextConfigHelper.GetInt32Config(), System.Threading.PortableThreadPool.BlockingConfig.IsCooperativeBlockingEnabled, System.Math.Max(), System.Threading.PortableThreadPool.BlockingConfig.MaxDelayMs, System.Math.Min(), System.Environment.ProcessorCount, System.Threading.PortableThreadPool.BlockingConfig.ThreadsPerDelayStep, and System.Threading.PortableThreadPool.BlockingConfig.ThreadsToAddWithoutDelay.