Terraria: System.Transactions.VolatileEnlistmentAborting.EnterState
EnterState()
override void System.Transactions.VolatileEnlistmentAborting.EnterState (InternalEnlistment enlistment) inline package
Definition at line 7 of file VolatileEnlistmentAborting.cs.
    {
        enlistment.State = this;
        Monitor.Exit(enlistment.Transaction);
        try
        {
            TransactionsEtwProvider log = TransactionsEtwProvider.Log;
            if (log.IsEnabled())
            {
                log.EnlistmentStatus(enlistment, NotificationCall.Rollback);
            }
            enlistment.EnlistmentNotification.Rollback(enlistment.SinglePhaseEnlistment);
        }
        finally
        {
            Monitor.Enter(enlistment.Transaction);
        }
    }
References System.Transactions.InternalEnlistment.EnlistmentNotification, System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.IEnlistmentNotification.Rollback(), System.Transactions.InternalEnlistment.SinglePhaseEnlistment, and System.Transactions.InternalEnlistment.Transaction.