Terraria: System.IO.DirectoryInfo.CreateSubdirectory
CreateSubdirectory()
DirectoryInfo System.IO.DirectoryInfo.CreateSubdirectory (string path) inline
Definition at line 45 of file DirectoryInfo.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (PathInternal.IsEffectivelyEmpty(path.AsSpan()))
        {
            throw new ArgumentException(SR.Argument_PathEmpty, "path");
        }
        if (Path.IsPathRooted(path))
        {
            throw new ArgumentException(SR.Arg_Path2IsRooted, "path");
        }
        string fullPath = Path.GetFullPath(Path.Combine(FullPath, path));
        ReadOnlySpan<char> span = Path.TrimEndingDirectorySeparator(fullPath.AsSpan());
        ReadOnlySpan<char> value = Path.TrimEndingDirectorySeparator(FullPath.AsSpan());
        if (span.StartsWith(value, PathInternal.StringComparison) && (span.Length == value.Length || PathInternal.IsDirectorySeparator(fullPath[value.Length])))
        {
            FileSystem.CreateDirectory(fullPath);
            return new DirectoryInfo(fullPath);
        }
        throw new ArgumentException(SR.Format(SR.Argument_InvalidSubPath, path, FullPath), "path");
    }
References System.IO.DirectoryInfo.DirectoryInfo(), System.SR.Arg_Path2IsRooted, System.SR.Argument_InvalidSubPath, System.SR.Argument_PathEmpty, System.IO.Path.Combine(), System.IO.FileSystem.CreateDirectory(), System.SR.Format(), System.IO.FileSystemInfo.FullPath, System.IO.Path.GetFullPath(), System.IO.PathInternal.IsDirectorySeparator(), System.IO.PathInternal.IsEffectivelyEmpty(), System.IO.Path.IsPathRooted(), System.IO.PathInternal.StringComparison, System.IO.Path.TrimEndingDirectorySeparator(), and System.value.