Terraria: System.IO.DirectoryInfo.InternalEnumerateInfos
InternalEnumerateInfos()
IEnumerable< FileSystemInfo > System.IO.DirectoryInfo.InternalEnumerateInfos (string path, string searchPattern, SearchTarget searchTarget, EnumerationOptions options) inline private
Definition at line 196 of file DirectoryInfo.cs.
    {
        if (searchPattern == null)
        {
            throw new ArgumentNullException("searchPattern");
        }
        _isNormalized &= FileSystemEnumerableFactory.NormalizeInputs(ref path, ref searchPattern, options.MatchType);
        return searchTarget switch
        {
            SearchTarget.Directories => FileSystemEnumerableFactory.DirectoryInfos(path, searchPattern, options, _isNormalized),
            SearchTarget.Files => FileSystemEnumerableFactory.FileInfos(path, searchPattern, options, _isNormalized),
            SearchTarget.Both => FileSystemEnumerableFactory.FileSystemInfos(path, searchPattern, options, _isNormalized),
            _ => throw new ArgumentException(SR.ArgumentOutOfRange_Enum, "searchTarget"),
        };
    }
References System.IO.DirectoryInfo._isNormalized, System.SR.ArgumentOutOfRange_Enum, System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(), and System.options.
Referenced by System.IO.DirectoryInfo.EnumerateDirectories(), System.IO.DirectoryInfo.EnumerateFiles(), System.IO.DirectoryInfo.EnumerateFileSystemInfos(), System.IO.DirectoryInfo.GetDirectories(), System.IO.DirectoryInfo.GetFiles(), and System.IO.DirectoryInfo.GetFileSystemInfos().