Terraria: System.IO.DirectoryInfo.Init
Init() [2/2]
void System.IO.DirectoryInfo.Init (string originalPath, string fullPath = null, string fileName = null, bool isNormalized = false) inline private
Definition at line 35 of file DirectoryInfo.cs.
    {
        OriginalPath = originalPath ?? throw new ArgumentNullException("originalPath");
        fullPath = fullPath ?? originalPath;
        fullPath = (isNormalized ? fullPath : Path.GetFullPath(fullPath));
        _name = fileName ?? (PathInternal.IsRoot(fullPath.AsSpan()) ? fullPath.AsSpan() : Path.GetFileName(Path.TrimEndingDirectorySeparator(fullPath.AsSpan()))).ToString();
        FullPath = fullPath;
        _isNormalized = isNormalized;
    }
References System.IO.DirectoryInfo._isNormalized, System.IO.FileSystemInfo._name, System.IO.FileSystemInfo.FullPath, System.IO.Path.GetFileName(), System.IO.Path.GetFullPath(), System.IO.PathInternal.IsRoot(), System.IO.FileSystemInfo.OriginalPath, and System.IO.Path.TrimEndingDirectorySeparator().
Referenced by System.IO.DirectoryInfo.DirectoryInfo(), System.IO.DirectoryInfo.DirectoryInfo(), and System.IO.DirectoryInfo.MoveTo().