Terraria: System.Diagnostics.Tracing.DataCollector.AddArray
AddArray()
unsafe void System.Diagnostics.Tracing.DataCollector.AddArray (Array value, int length, int itemSize) inline package
Definition at line 126 of file DataCollector.cs.
    {
        if (length > 65535)
        {
            length = 65535;
        }
        int num = length * itemSize;
        if (bufferNesting != 0)
        {
            EnsureBuffer(num + 2);
        }
        AddScalar(&length, 2);
        checked
        {
            if (length != 0)
            {
                if (bufferNesting == 0)
                {
                    ScalarsEnd();
                    PinArray(value, num);
                    return;
                }
                int dstOffset = bufferPos;
                bufferPos += num;
                EnsureBuffer();
                Buffer.BlockCopy(value, 0, buffer, dstOffset, num);
            }
        }
    }
References System.Diagnostics.Tracing.DataCollector.AddScalar(), System.Buffer.BlockCopy(), System.Diagnostics.Tracing.DataCollector.buffer, System.Diagnostics.Tracing.DataCollector.bufferNesting, System.Diagnostics.Tracing.DataCollector.bufferPos, System.Diagnostics.Tracing.DataCollector.EnsureBuffer(), System.length, System.Diagnostics.Tracing.DataCollector.PinArray(), System.Diagnostics.Tracing.DataCollector.ScalarsEnd(), and System.value.