Terraria: System.Diagnostics.Tracing.DataCollector.AddScalar
AddScalar()
unsafe void System.Diagnostics.Tracing.DataCollector.AddScalar (void * value, int size) inline package
Definition at line 55 of file DataCollector.cs.
    {
        if (bufferNesting == 0)
        {
            byte* ptr = scratch;
            byte* ptr2 = ptr + size;
            if (scratchEnd < ptr2)
            {
                throw new IndexOutOfRangeException(SR.EventSource_AddScalarOutOfRange);
            }
            ScalarsBegin();
            scratch = ptr2;
            for (int i = 0; i != size; i++)
            {
                ptr[i] = ((byte*)value)[i];
            }
        }
        else
        {
            int num = bufferPos;
            int num2;
            checked
            {
                bufferPos += size;
                EnsureBuffer();
                num2 = 0;
            }
            while (num2 != size)
            {
                buffer[num] = ((byte*)value)[num2];
                num2++;
                num++;
            }
        }
    }
References System.Diagnostics.Tracing.DataCollector.buffer, System.Diagnostics.Tracing.DataCollector.bufferNesting, System.Diagnostics.Tracing.DataCollector.bufferPos, System.Diagnostics.Tracing.DataCollector.EnsureBuffer(), System.SR.EventSource_AddScalarOutOfRange, System.Diagnostics.Tracing.DataCollector.ScalarsBegin(), System.Diagnostics.Tracing.DataCollector.scratch, System.Diagnostics.Tracing.DataCollector.scratchEnd, and System.value.
Referenced by System.Diagnostics.Tracing.DataCollector.AddArray().