Terraria: System.Diagnostics.Tracing.DataCollector.PinArray
PinArray()
unsafe void System.Diagnostics.Tracing.DataCollector.PinArray (object value, int size) inline private
Definition at line 218 of file DataCollector.cs.
    {
        GCHandle* ptr = pins;
        if (pinsEnd <= ptr)
        {
            throw new IndexOutOfRangeException(SR.EventSource_PinArrayOutOfRange);
        }
        EventSource.EventData* ptr2 = datas;
        if (datasEnd <= ptr2)
        {
            throw new IndexOutOfRangeException(SR.EventSource_DataDescriptorsOutOfRange);
        }
        pins = ptr + 1;
        datas = ptr2 + 1;
        *ptr = GCHandle.Alloc(value, GCHandleType.Pinned);
        ptr2->DataPointer = ptr->AddrOfPinnedObject();
        ptr2->m_Size = size;
    }
References System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject(), System.Runtime.InteropServices.GCHandle.Alloc(), System.Diagnostics.Tracing.DataCollector.datas, System.Diagnostics.Tracing.DataCollector.datasEnd, System.SR.EventSource_DataDescriptorsOutOfRange, System.SR.EventSource_PinArrayOutOfRange, System.Diagnostics.Tracing.DataCollector.pins, System.Diagnostics.Tracing.DataCollector.pinsEnd, and System.value.
Referenced by System.Diagnostics.Tracing.DataCollector.AddArray(), System.Diagnostics.Tracing.DataCollector.AddNullTerminatedString(), and System.Diagnostics.Tracing.DataCollector.EndBuffered().