Terraria: System.Diagnostics.Tracing.DataCollector.AddNullTerminatedString
AddNullTerminatedString()
unsafe void System.Diagnostics.Tracing.DataCollector.AddNullTerminatedString (string value) inline package
Definition at line 91 of file DataCollector.cs.
    {
        if (value == null)
        {
            value = string.Empty;
        }
        int num = value.IndexOf('\0');
        if (num < 0)
        {
            num = value.Length;
        }
        int num2 = (num + 1) * 2;
        if (bufferNesting != 0)
        {
            EnsureBuffer(num2);
        }
        if (bufferNesting == 0)
        {
            ScalarsEnd();
            PinArray(value, num2);
            return;
        }
        int startIndex = bufferPos;
        checked
        {
            bufferPos += num2;
            EnsureBuffer();
            fixed (char* ptr = value)
            {
                void* ptr2 = ptr;
                Marshal.Copy((IntPtr)ptr2, buffer, startIndex, num2);
            }
        }
    }
References System.Diagnostics.Tracing.DataCollector.buffer, System.Diagnostics.Tracing.DataCollector.bufferNesting, System.Diagnostics.Tracing.DataCollector.bufferPos, System.Runtime.InteropServices.Marshal.Copy(), System.Diagnostics.Tracing.DataCollector.EnsureBuffer(), System.Diagnostics.Tracing.DataCollector.PinArray(), System.Diagnostics.Tracing.DataCollector.ScalarsEnd(), System.startIndex, and System.value.