Terraria: System.Xml.Xsl.XslTransformException.ToString
ToString()
override string System.Xml.Xsl.XslTransformException.ToString () inline inherited
Definition at line 70 of file XslTransformException.cs.
    {
        string text = GetType().FullName;
        string text2 = FormatDetailedMessage();
        if (text2 != null && text2.Length > 0)
        {
            text = text + ": " + text2;
        }
        if (base.InnerException != null)
        {
            text = text + " ---> " + base.InnerException.ToString() + Environment.NewLine + "   " + CreateMessage(System.SR.Xml_EndOfInnerExceptionStack);
        }
        if (StackTrace != null)
        {
            text = text + Environment.NewLine + StackTrace;
        }
        return text;
    }
References System.Xml.Xsl.XslTransformException.CreateMessage(), System.Xml.Dictionary, System.Xml.Xsl.XslTransformException.FormatDetailedMessage(), System.Type.FullName, System.Exception.GetType(), System.Exception.StackTrace, System.text, and System.SR.Xml_EndOfInnerExceptionStack.