Terraria: Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawBareBonesBar
DrawBareBonesBar()
static void Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawBareBonesBar (SpriteBatch spriteBatch, float lifePercent) inline static
Definition at line 12 of file BigProgressBarHelper.cs.
    {
        Rectangle rectangle = Utils.CenteredRectangle(Main.ScreenSize.ToVector2() * new Vector2(0.5f, 1f) + new Vector2(0f, -50f), new Vector2(400f, 20f));
        Rectangle destinationRectangle = rectangle;
        destinationRectangle.Inflate(2, 2);
        Texture2D value = TextureAssets.MagicPixel.Value;
        Rectangle value2 = new Rectangle(0, 0, 1, 1);
        Rectangle destinationRectangle2 = rectangle;
        destinationRectangle2.Width = (int)((float)destinationRectangle2.Width * lifePercent);
        spriteBatch.Draw(value, destinationRectangle, value2, Color.White * 0.6f);
        spriteBatch.Draw(value, rectangle, value2, Color.Black * 0.6f);
        spriteBatch.Draw(value, destinationRectangle2, value2, Color.LimeGreen * 0.5f);
    }
References Microsoft.Xna.Framework.Color.Black, Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Color.LimeGreen, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.ScreenSize, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.