Terraria: Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText
DrawHealthText()
static void Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText (SpriteBatch spriteBatch, Rectangle area, float current, float max) inline static private
Definition at line 62 of file BigProgressBarHelper.cs.
    {
        DynamicSpriteFont value = FontAssets.ItemStack.Value;
        Vector2 vector = area.Center.ToVector2();
        vector.Y += 1f;
        string text = "/";
        Vector2 vector2 = value.MeasureString(text);
        Utils.DrawBorderStringFourWay(spriteBatch, value, text, vector.X, vector.Y, Color.White, Color.Black, vector2 * 0.5f);
        text = ((int)current).ToString();
        vector2 = value.MeasureString(text);
        Utils.DrawBorderStringFourWay(spriteBatch, value, text, vector.X - 5f, vector.Y, Color.White, Color.Black, vector2 * new Vector2(1f, 0.5f));
        text = ((int)max).ToString();
        vector2 = value.MeasureString(text);
        Utils.DrawBorderStringFourWay(spriteBatch, value, text, vector.X + 5f, vector.Y, Color.White, Color.Black, vector2 * new Vector2(0f, 0.5f));
    }
References Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Rectangle.Center, Terraria.Utils.DrawBorderStringFourWay(), Terraria.GameContent.FontAssets.ItemStack, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar(), and Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar().