Terraria: System.Data.Operators.ToString
ToString()
static string System.Data.Operators.ToString (int op) inline static package
Definition at line 58 of file Operators.cs.
    {
        if (op <= s_looks.Length)
        {
            return s_looks[op];
        }
        return "Unknown op";
    }
References System.Data.Operators.s_looks.
Referenced by System.Data.ExprException.AmbiguousBinop(), System.Data.ExprException.MissingOperand(), System.Data.ExpressionParser.Parse(), System.Data.ExprException.TypeMismatchInBinop(), and System.Data.ExprException.UnsupportedOperator().