Terraria: Terraria.GameContent.UI.Elements.UIItemSlot.HandleItemSlotLogic
HandleItemSlotLogic()
void Terraria.GameContent.UI.Elements.UIItemSlot.HandleItemSlotLogic () inline private
    {
        if (base.IsMouseHovering)
        {
            Main.LocalPlayer.mouseInterface = true;
            Item inv = _itemArray[_itemIndex];
            ItemSlot.OverrideHover(ref inv, _itemSlotContext);
            ItemSlot.LeftClick(ref inv, _itemSlotContext);
            ItemSlot.RightClick(ref inv, _itemSlotContext);
            ItemSlot.MouseHover(ref inv, _itemSlotContext);
            _itemArray[_itemIndex] = inv;
        }
    }
References Terraria.GameContent.UI.Elements.UIItemSlot._itemArray, Terraria.GameContent.UI.Elements.UIItemSlot._itemIndex, Terraria.GameContent.UI.Elements.UIItemSlot._itemSlotContext, Terraria.UI.ItemSlot.LeftClick(), Terraria.UI.ItemSlot.MouseHover(), Terraria.UI.ItemSlot.OverrideHover(), and Terraria.UI.ItemSlot.RightClick().
Referenced by Terraria.GameContent.UI.Elements.UIItemSlot.DrawSelf().