Terraria: Terraria.GameContent.UI.Elements.UIItemSlot.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIItemSlot.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 38 of file UIItemSlot.cs.
    {
        HandleItemSlotLogic();
        Item inv = _itemArray[_itemIndex];
        Vector2 position = GetDimensions().Center() + new Vector2(52f, 52f) * -0.5f * Main.inventoryScale;
        ItemSlot.Draw(spriteBatch, ref inv, _itemSlotContext, position);
    }
References Terraria.GameContent.UI.Elements.UIItemSlot._itemArray, Terraria.GameContent.UI.Elements.UIItemSlot._itemIndex, Terraria.GameContent.UI.Elements.UIItemSlot._itemSlotContext, Terraria.UI.CalculatedStyle.Center(), Terraria.UI.ItemSlot.Draw(), Terraria.UI.UIElement.GetDimensions(), Terraria.GameContent.UI.Elements.UIItemSlot.HandleItemSlotLogic(), and Terraria.Main.inventoryScale.