Terraria: System.Xml.Serialization.CodeGenerator.StoreArrayElement
StoreArrayElement()
void System.Xml.Serialization.CodeGenerator.StoreArrayElement (object obj, object arrayIndex, object value) inline package
Definition at line 516 of file CodeGenerator.cs.
    {
        Type variableType = GetVariableType(obj);
        if (variableType == typeof(Array))
        {
            Load(obj);
            Call(typeof(Array).GetMethod("SetValue", new Type[2]
            {
                typeof(object),
                typeof(int)
            }));
            return;
        }
        Type elementType = variableType.GetElementType();
        Load(obj);
        Load(arrayIndex);
        if (IsStruct(elementType))
        {
            Ldelema(elementType);
        }
        Load(value);
        ConvertValue(GetVariableType(value), elementType);
        if (IsStruct(elementType))
        {
            Stobj(elementType);
        }
        else
        {
            Stelem(elementType);
        }
    }
References System.arrayIndex, System.Reflection.Emit.Call, System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.elementType, System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.CodeGenerator.IsStruct(), System.Reflection.Emit.Ldelema, System.Xml.Serialization.CodeGenerator.Load(), System.obj, System.Reflection.Emit.Stelem, System.Reflection.Emit.Stobj, and System.value.