Terraria: System.Xml.Serialization.CodeGenerator.TryDequeueLocal
TryDequeueLocal()
bool System.Xml.Serialization.CodeGenerator.TryDequeueLocal (Type type, string name, [NotNullWhen(true)] out LocalBuilder local) inline private
Definition at line 315 of file CodeGenerator.cs.
    {
        (Type, string) key = (type, name);
        if (_freeLocals.TryGetValue(key, out var value))
        {
            local = value.Dequeue();
            if (value.Count == 0)
            {
                _freeLocals.Remove(key);
            }
            return true;
        }
        local = null;
        return false;
    }
References System.Xml.Serialization.CodeGenerator._freeLocals, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.type, System.Xml.Serialization.Type, and System.value.
Referenced by System.Xml.Serialization.CodeGenerator.DeclareLocal().