Terraria: System.Xml.Serialization.CodeGenerator.Load
Load()
void System.Xml.Serialization.CodeGenerator.Load (object obj) inline package
Definition at line 692 of file CodeGenerator.cs.
    {
        if (obj == null)
        {
            _ilGen.Emit(OpCodes.Ldnull);
        }
        else if (obj is ArgBuilder)
        {
            Ldarg((ArgBuilder)obj);
        }
        else if (obj is LocalBuilder)
        {
            Ldloc((LocalBuilder)obj);
        }
        else
        {
            Ldc(obj);
        }
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.Ldarg, System.Xml.Serialization.CodeGenerator.Ldc(), System.Reflection.Emit.Ldloc, System.Reflection.Emit.OpCodes.Ldnull, and System.obj.
Referenced by System.Xml.Serialization.CodeGenerator.EndFor(), System.Xml.Serialization.CodeGenerator.For(), System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.SourceInfo.InternalLoad(), System.Xml.Serialization.CodeGenerator.LoadAddress(), System.Xml.Serialization.CodeGenerator.LoadArrayElement(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.NewArray(), System.Xml.Serialization.CodeGenerator.StoreArrayElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.ReflectionAwareILGen.WriteInstanceOf(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteTag(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode().