Terraria: System.Xml.Serialization.CodeGenerator.LoadAddress
LoadAddress()
void System.Xml.Serialization.CodeGenerator.LoadAddress (object obj) inline package
Definition at line 712 of file CodeGenerator.cs.
    {
        if (obj is ArgBuilder)
        {
            LdargAddress((ArgBuilder)obj);
        }
        else if (obj is LocalBuilder)
        {
            LdlocAddress((LocalBuilder)obj);
        }
        else
        {
            Load(obj);
        }
    }
References System.Xml.Serialization.CodeGenerator.LdargAddress(), System.Xml.Serialization.CodeGenerator.LdlocAddress(), System.Xml.Serialization.CodeGenerator.Load(), and System.obj.
Referenced by System.Xml.Serialization.SourceInfo.InternalLoad(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin().