Terraria: System.Xml.Serialization.CodeGenerator.LoadMember
LoadMember() [2/2]
Type System.Xml.Serialization.CodeGenerator.LoadMember (object obj, MemberInfo memberInfo) inline package
Definition at line 558 of file CodeGenerator.cs.
    {
        if (GetVariableType(obj).IsValueType)
        {
            LoadAddress(obj);
        }
        else
        {
            Load(obj);
        }
        return LoadMember(memberInfo);
    }
References System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.LoadAddress(), System.Xml.Serialization.CodeGenerator.LoadMember(), and System.obj.
Referenced by System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetEnd(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.XmlSerializationILGen.ILGenLoad(), System.Xml.Serialization.SourceInfo.InternalLoad(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteIsStartTag(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual().