Terraria: System.Xml.Serialization.CodeGenerator.InitILGeneration
InitILGeneration()
void System.Xml.Serialization.CodeGenerator.InitILGeneration (Type[] argTypes, string[] argNames, bool isStatic) inline private
Definition at line 202 of file CodeGenerator.cs.
    {
        _methodEndLabel = _ilGen.DefineLabel();
        retLabel = _ilGen.DefineLabel();
        _blockStack = new Stack<object>();
        _whileStack = new Stack<WhileState>();
        _currentScope = new LocalScope();
        _freeLocals = new Dictionary<(Type, string), Queue<LocalBuilder>>();
        _argList = new Dictionary<string, ArgBuilder>();
        if (!isStatic)
        {
            _argList.Add("this", new ArgBuilder("this", 0, _typeBuilder.BaseType));
        }
        for (int i = 0; i < argTypes.Length; i++)
        {
            ArgBuilder argBuilder = new ArgBuilder(argNames[i], _argList.Count, argTypes[i]);
            _argList.Add(argBuilder.Name, argBuilder);
            _methodBuilder.DefineParameter(argBuilder.Index, ParameterAttributes.None, argBuilder.Name);
        }
    }
References System.Xml.Serialization.CodeGenerator._argList, System.Xml.Serialization.CodeGenerator._blockStack, System.Xml.Serialization.CodeGenerator._currentScope, System.Xml.Serialization.CodeGenerator._freeLocals, System.Xml.Serialization.CodeGenerator._ilGen, System.Xml.Serialization.CodeGenerator._methodBuilder, System.Xml.Serialization.CodeGenerator._methodEndLabel, System.Xml.Serialization.CodeGenerator._typeBuilder, System.Xml.Serialization.CodeGenerator._whileStack, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Emit.TypeBuilder.BaseType, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.MethodBuilder.DefineParameter(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.retLabel, and System.Xml.Serialization.Type.
Referenced by System.Xml.Serialization.CodeGenerator.BeginMethod(), and System.Xml.Serialization.CodeGenerator.BeginMethod().