Terraria: System.Xml.Serialization.CodeGenerator.ConvertValue
ConvertValue()
void System.Xml.Serialization.CodeGenerator.ConvertValue (Type source, Type target) inline package
Definition at line 733 of file CodeGenerator.cs.
    {
        InternalConvert(source, target, isAddress: false);
    }
References System.Xml.Serialization.CodeGenerator.InternalConvert(), and System.source.
Referenced by System.Xml.Serialization.SourceInfo.Convert(), System.Xml.Serialization.SourceInfo.ConvertNullableValue(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForEnumLongValue(), System.Xml.Serialization.XmlSerializationILGen.ILGenLoad(), System.Xml.Serialization.XmlSerializationReaderILGen.InitializeValueTypes(), System.Xml.Serialization.SourceInfo.InternalLoad(), System.Xml.Serialization.CodeGenerator.StoreArrayElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode().