Terraria: System.Xml.Serialization.CodeGenerator.For
For()
object System.Xml.Serialization.CodeGenerator.For (LocalBuilder local, object start, object end) inline package
Definition at line 350 of file CodeGenerator.cs.
    {
        ForState forState = new ForState(local, DefineLabel(), DefineLabel(), end);
        if (forState.Index != null)
        {
            Load(start);
            Stloc(forState.Index);
            Br(forState.TestLabel);
        }
        MarkLabel(forState.BeginLabel);
        _blockStack.Push(forState);
        return forState;
    }
References System.Xml.Serialization.CodeGenerator._blockStack, System.Reflection.Emit.Br, System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Collections.Generic.Stack< T >.Push(), System.start, and System.Reflection.Emit.Stloc.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember().