Terraria: System.Xml.Serialization.CodeGenerator.GetVariable
GetVariable()
object System.Xml.Serialization.CodeGenerator.GetVariable (string name) inline package
Definition at line 273 of file CodeGenerator.cs.
    {
        if (TryGetVariable(name, out var variable))
        {
            return variable;
        }
        return null;
    }
References System.Xml.Dictionary, and System.Xml.Serialization.CodeGenerator.TryGetVariable().
Referenced by System.Xml.Serialization.XmlSerializationILGen.ILGenLoad(), System.Xml.Serialization.SourceInfo.InternalLoad(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode().