Terraria: System.Xml.Serialization.CodeGenerator.Br
Br()
void System.Xml.Serialization.CodeGenerator.Br (Label label) inline package
Definition at line 1112 of file CodeGenerator.cs.
    {
        _ilGen.Emit(OpCodes.Br, label);
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.OpCodes.Br, and System.Reflection.Emit.ILGenerator.Emit().
Referenced by System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod().