Terraria: System.Xml.Serialization.CodeGenerator.BeginMethod
BeginMethod() [2/2]
void System.Xml.Serialization.CodeGenerator.BeginMethod (Type returnType, string methodName, Type[] argTypes, string[] argNames, MethodAttributes methodAttributes) inline package
Definition at line 188 of file CodeGenerator.cs.
    {
        _methodBuilder = _typeBuilder.DefineMethod(methodName, methodAttributes, returnType, argTypes);
        _ilGen = _methodBuilder.GetILGenerator();
        InitILGeneration(argTypes, argNames, (_methodBuilder.Attributes & MethodAttributes.Static) == MethodAttributes.Static);
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Xml.Serialization.CodeGenerator._methodBuilder, System.Xml.Serialization.CodeGenerator._typeBuilder, System.Reflection.Emit.MethodBuilder.Attributes, System.Reflection.Emit.TypeBuilder.DefineMethod(), System.Reflection.Emit.MethodBuilder.GetILGenerator(), and System.Xml.Serialization.CodeGenerator.InitILGeneration().
Referenced by System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(), System.Xml.Serialization.XmlSerializationILGen.GenerateSupportedTypes(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().