Terraria: System.Xml.Serialization.CodeGenerator.Throw
Throw()
void System.Xml.Serialization.CodeGenerator.Throw () inline package
Definition at line 798 of file CodeGenerator.cs.
    {
        _ilGen.Emit(OpCodes.Throw);
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.ILGenerator.Emit(), and System.Reflection.Emit.OpCodes.Throw.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().