Terraria: System.Xml.Serialization.CodeGenerator.Else
Else()
void System.Xml.Serialization.CodeGenerator.Else () inline package
Definition at line 426 of file CodeGenerator.cs.
    {
        IfState ifState = PopIfState();
        Br(ifState.EndIf);
        MarkLabel(ifState.ElseBegin);
        ifState.ElseBegin = ifState.EndIf;
        _blockStack.Push(ifState);
    }
References System.Xml.Serialization.CodeGenerator._blockStack, System.Reflection.Emit.Br, System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.PopIfState(), and System.Collections.Generic.Stack< T >.Push().
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode().