Terraria: System.Xml.Serialization.CodeGenerator.EndFor
EndFor()
void System.Xml.Serialization.CodeGenerator.EndFor () inline package
Definition at line 364 of file CodeGenerator.cs.
    {
        object obj = _blockStack.Pop();
        ForState forState = obj as ForState;
        if (forState.Index != null)
        {
            Ldloc(forState.Index);
            Ldc(1);
            Add();
            Stloc(forState.Index);
            MarkLabel(forState.TestLabel);
            Ldloc(forState.Index);
            Load(forState.End);
            Type variableType = GetVariableType(forState.End);
            if (variableType.IsArray)
            {
                Ldlen();
            }
            else
            {
                MethodInfo method = typeof(ICollection).GetMethod("get_Count", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                Call(method);
            }
            Blt(forState.BeginLabel);
        }
        else
        {
            Br(forState.BeginLabel);
        }
    }
References System.Xml.Serialization.CodeGenerator._blockStack, System.Xml.Serialization.CodeGenerator.Add(), System.Reflection.Emit.Blt, System.Reflection.Emit.Br, System.Reflection.Emit.Call, System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldlen(), System.Reflection.Emit.Ldloc, System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.obj, System.Collections.Generic.Stack< T >.Pop(), and System.Reflection.Emit.Stloc.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember().