Terraria: System.Xml.Serialization.CodeGenerator.InternalIf
InternalIf()
void System.Xml.Serialization.CodeGenerator.InternalIf (bool negate) inline private
Definition at line 1147 of file CodeGenerator.cs.
    {
        IfState ifState = new IfState();
        ifState.EndIf = DefineLabel();
        ifState.ElseBegin = DefineLabel();
        if (negate)
        {
            Brtrue(ifState.ElseBegin);
        }
        else
        {
            Brfalse(ifState.ElseBegin);
        }
        _blockStack.Push(ifState);
    }
References System.Xml.Serialization.CodeGenerator._blockStack, System.Reflection.Emit.Brfalse, System.Reflection.Emit.Brtrue, System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, and System.Collections.Generic.Stack< T >.Push().
Referenced by System.Xml.Serialization.CodeGenerator.If(), and System.Xml.Serialization.CodeGenerator.IfNot().