Terraria: System.Xml.Serialization.CodeGenerator.Ldstr
Ldstr()
void System.Xml.Serialization.CodeGenerator.Ldstr (string strVar) inline package
Definition at line 937 of file CodeGenerator.cs.
    {
        if (strVar == null)
        {
            _ilGen.Emit(OpCodes.Ldnull);
        }
        else
        {
            _ilGen.Emit(OpCodes.Ldstr, strVar);
        }
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.OpCodes.Ldnull, and System.Reflection.Emit.OpCodes.Ldstr.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationILGen.GeneratePublicMethods(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializers(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElementCall(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteQualifiedNameElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteTag(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteTag(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode().