Terraria: System.Xml.Serialization.CodeGenerator.PopIfState
PopIfState()
IfState System.Xml.Serialization.CodeGenerator.PopIfState () inline private
Definition at line 1221 of file CodeGenerator.cs.
    {
        object obj = _blockStack.Pop();
        return obj as IfState;
    }
References System.Xml.Serialization.CodeGenerator._blockStack, System.obj, and System.Collections.Generic.Stack< T >.Pop().
Referenced by System.Xml.Serialization.CodeGenerator.Else(), and System.Xml.Serialization.CodeGenerator.EndIf().