Terraria: System.Xml.Serialization.CodeGenerator.EndExceptionBlock
EndExceptionBlock()
void System.Xml.Serialization.CodeGenerator.EndExceptionBlock () inline package
Definition at line 456 of file CodeGenerator.cs.
    {
        _ilGen.EndExceptionBlock();
        _ilGen.MarkLabel(_leaveLabels.Pop());
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Xml.Serialization.CodeGenerator._leaveLabels, System.Reflection.Emit.ILGenerator.EndExceptionBlock(), System.Reflection.Emit.ILGenerator.MarkLabel(), and System.Collections.Stack.Pop().