Terraria: System.Xml.Serialization.CodeGenerator.GetVariableType
GetVariableType()
Type System.Xml.Serialization.CodeGenerator.GetVariableType (object var) inline package
Definition at line 260 of file CodeGenerator.cs.
    {
        if (var is ArgBuilder)
        {
            return ((ArgBuilder)var).ArgType;
        }
        if (var is LocalBuilder)
        {
            return ((LocalBuilder)var).LocalType;
        }
        return var.GetType();
    }
Referenced by System.Xml.Serialization.CodeGenerator.EndFor(), System.Xml.Serialization.SourceInfo.InternalLoad(), System.Xml.Serialization.CodeGenerator.LoadArrayElement(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.StoreArrayElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode().