Terraria: System.Xml.Serialization.CodeGenerator.EndMethod
EndMethod()
MethodBuilder System.Xml.Serialization.CodeGenerator.EndMethod () inline package
Definition at line 223 of file CodeGenerator.cs.
    {
        MarkLabel(_methodEndLabel);
        Ret();
        MethodBuilder methodBuilder = null;
        methodBuilder = _methodBuilder;
        _methodBuilder = null;
        _ilGen = null;
        _freeLocals = null;
        _blockStack = null;
        _whileStack = null;
        _argList = null;
        _currentScope = null;
        retLocal = null;
        return methodBuilder;
    }
References System.Xml.Serialization.CodeGenerator._argList, System.Xml.Serialization.CodeGenerator._blockStack, System.Xml.Serialization.CodeGenerator._currentScope, System.Xml.Serialization.CodeGenerator._freeLocals, System.Xml.Serialization.CodeGenerator._ilGen, System.Xml.Serialization.CodeGenerator._methodBuilder, System.Xml.Serialization.CodeGenerator._methodEndLabel, System.Xml.Serialization.CodeGenerator._whileStack, System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.Ret(), and System.Xml.Serialization.CodeGenerator.retLocal.
Referenced by System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(), System.Xml.Serialization.XmlSerializationILGen.GenerateSupportedTypes(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().