Terraria: System.Xml.Serialization.CodeGenerator.Ldelem
Ldelem()
void System.Xml.Serialization.CodeGenerator.Ldelem (Type arrayElementType) inline package
Definition at line 1046 of file CodeGenerator.cs.
    {
        if (arrayElementType.IsEnum)
        {
            Ldelem(Enum.GetUnderlyingType(arrayElementType));
            return;
        }
        OpCode ldelemOpCode = GetLdelemOpCode(Type.GetTypeCode(arrayElementType));
        if (ldelemOpCode.Equals(OpCodes.Nop))
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.ArrayTypeIsNotSupported, arrayElementType.AssemblyQualifiedName));
        }
        _ilGen.Emit(ldelemOpCode);
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.SR.ArrayTypeIsNotSupported, System.Reflection.Emit.ILGenerator.Emit(), System.SR.Format(), System.Xml.Serialization.CodeGenerator.GetLdelemOpCode(), System.Type.GetTypeCode(), System.Enum.GetUnderlyingType(), System.Reflection.Emit.Ldelem, and System.Reflection.Emit.OpCodes.Nop.
Referenced by System.Xml.Serialization.SourceInfo.InternalLoad().