Terraria: System.Xml.Serialization.CodeGenerator.GetArg
GetArg()
ArgBuilder System.Xml.Serialization.CodeGenerator.GetArg (string name) inline package
Definition at line 240 of file CodeGenerator.cs.
    {
        return _argList[name];
    }
References System.Xml.Serialization.CodeGenerator._argList.
Referenced by System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForEnumLongValue(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteAttribute(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().