Terraria: System.Xml.Serialization.CodeGenerator.Brtrue
Brtrue()
void System.Xml.Serialization.CodeGenerator.Brtrue (Label label) inline package
Definition at line 1132 of file CodeGenerator.cs.
    {
        _ilGen.Emit(OpCodes.Brtrue, label);
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.OpCodes.Brtrue, and System.Reflection.Emit.ILGenerator.Emit().
Referenced by System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText().