Terraria: System.Xml.Serialization.CodeGenerator.Ldc
Ldc() [6/6]
void System.Xml.Serialization.CodeGenerator.Ldc (object o) inline package
Definition at line 808 of file CodeGenerator.cs.
    {
        Type type = o.GetType();
        if (o is Type)
        {
            Ldtoken((Type)o);
            Call(typeof(Type).GetMethod("GetTypeFromHandle", BindingFlags.Static | BindingFlags.Public, new Type[1] { typeof(RuntimeTypeHandle) }));
            return;
        }
        if (type.IsEnum)
        {
            Ldc(Convert.ChangeType(o, Enum.GetUnderlyingType(type), null));
            return;
        }
        switch (Type.GetTypeCode(type))
        {
        case TypeCode.Boolean:
            Ldc((bool)o);
            return;
        case TypeCode.Char:
            throw new NotSupportedException(System.SR.XmlInvalidCharSchemaPrimitive);
        case TypeCode.SByte:
        case TypeCode.Byte:
        case TypeCode.Int16:
        case TypeCode.UInt16:
            Ldc(Convert.ToInt32(o, CultureInfo.InvariantCulture));
            return;
        case TypeCode.Int32:
            Ldc((int)o);
            return;
        case TypeCode.UInt32:
            Ldc((int)(uint)o);
            return;
        case TypeCode.UInt64:
            Ldc((long)(ulong)o);
            return;
        case TypeCode.Int64:
            Ldc((long)o);
            return;
        case TypeCode.Single:
            Ldc((float)o);
            return;
        case TypeCode.Double:
            Ldc((double)o);
            return;
        case TypeCode.String:
            Ldstr((string)o);
            return;
        case TypeCode.Decimal:
        {
            ConstructorInfo constructor2 = typeof(decimal).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[5]
            {
                typeof(int),
                typeof(int),
                typeof(int),
                typeof(bool),
                typeof(byte)
            });
            int[] bits = decimal.GetBits((decimal)o);
            Ldc(bits[0]);
            Ldc(bits[1]);
            Ldc(bits[2]);
            Ldc((bits[3] & 0x80000000u) == 2147483648u);
            Ldc((byte)((bits[3] >> 16) & 0xFF));
            New(constructor2);
            return;
        }
        case TypeCode.DateTime:
        {
            ConstructorInfo constructor = typeof(DateTime).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(long) });
            Ldc(((DateTime)o).Ticks);
            New(constructor);
            return;
        }
        }
        if (type == typeof(TimeSpan))
        {
            ConstructorInfo constructor3 = typeof(TimeSpan).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[1] { typeof(long) }, null);
            Ldc(((TimeSpan)o).Ticks);
            New(constructor3);
            return;
        }
        if (type == typeof(DateTimeOffset))
        {
            ConstructorInfo constructor4 = typeof(DateTimeOffset).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, new Type[2]
            {
                typeof(long),
                typeof(TimeSpan)
            }, null);
            Ldc(((DateTimeOffset)o).Ticks);
            Ldc(((DateTimeOffset)o).Offset);
            New(constructor4);
            return;
        }
        throw new NotSupportedException(System.SR.Format(System.SR.UnknownConstantType, type.AssemblyQualifiedName));
    }
References System.Reflection.Emit.Call, System.Convert.ChangeType(), System.Xml.Dictionary, System.SR.Format(), System.Type.GetTypeCode(), System.Enum.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.CodeGenerator.Ldc(), System.Reflection.Emit.Ldstr, System.Reflection.Emit.Ldtoken, System.Xml.Serialization.CodeGenerator.New(), System.Convert.ToInt32(), System.type, System.SR.UnknownConstantType, and System.SR.XmlInvalidCharSchemaPrimitive.
Referenced by System.Xml.Serialization.CodeGenerator.Cne(), System.Xml.Serialization.CodeGenerator.EndFor(), System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationILGen.GenerateSupportedTypes(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForEnumMember(), System.Xml.Serialization.XmlSerializationReaderILGen.InitializeValueTypes(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.WhileBegin(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), System.Xml.Serialization.ReflectionAwareILGen.WriteArrayTypeCompare(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElementCall(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText(), System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderILGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteTag(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteText(), System.Xml.Serialization.ReflectionAwareILGen.WriteTypeCompare(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual().