Terraria: System.Xml.Serialization.CodeGenerator.NewArray
NewArray()
void System.Xml.Serialization.CodeGenerator.NewArray (Type elementType, object len) inline package
Definition at line 494 of file CodeGenerator.cs.
    {
        Load(len);
        _ilGen.Emit(OpCodes.Newarr, elementType);
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.elementType, System.Reflection.Emit.ILGenerator.Emit(), System.len, System.Xml.Serialization.CodeGenerator.Load(), and System.Reflection.Emit.OpCodes.Newarr.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod().