Terraria: System.Xml.Serialization.CodeGenerator.GotoMethodEnd
GotoMethodEnd()
void System.Xml.Serialization.CodeGenerator.GotoMethodEnd () inline package
Definition at line 1315 of file CodeGenerator.cs.
    {
        Br(_methodEndLabel);
    }
References System.Xml.Serialization.CodeGenerator._methodEndLabel, and System.Reflection.Emit.Br.
Referenced by System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetEnd(), System.Xml.Serialization.XmlSerializationILGen.GenerateSupportedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().