Terraria: System.Xml.Serialization.CodeGenerator.LoadArrayElement
LoadArrayElement()
void System.Xml.Serialization.CodeGenerator.LoadArrayElement (object obj, object arrayIndex) inline package
Definition at line 500 of file CodeGenerator.cs.
    {
        Type elementType = GetVariableType(obj).GetElementType();
        Load(obj);
        Load(arrayIndex);
        if (IsStruct(elementType))
        {
            Ldelema(elementType);
            Ldobj(elementType);
        }
        else
        {
            Ldelem(elementType);
        }
    }
References System.arrayIndex, System.elementType, System.Type.GetElementType(), System.Xml.Serialization.CodeGenerator.GetVariableType(), System.Xml.Serialization.CodeGenerator.IsStruct(), System.Reflection.Emit.Ldelem, System.Reflection.Emit.Ldelema, System.Reflection.Emit.Ldobj, System.Xml.Serialization.CodeGenerator.Load(), and System.obj.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.WritePrimitive().