Terraria: System.Xml.Serialization.CodeGenerator.Call
Call() [2/2]
void System.Xml.Serialization.CodeGenerator.Call (MethodInfo methodInfo) inline package
Definition at line 467 of file CodeGenerator.cs.
    {
        if (methodInfo.IsVirtual && !methodInfo.DeclaringType.IsValueType)
        {
            _ilGen.Emit(OpCodes.Callvirt, methodInfo);
        }
        else
        {
            _ilGen.Emit(OpCodes.Call, methodInfo);
        }
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.OpCodes.Callvirt, and System.Reflection.Emit.ILGenerator.Emit().
Referenced by System.Xml.Serialization.SourceInfo.ConvertNullableValue(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationILGen.GeneratePublicMethods(), System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializers(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.SourceInfo.InternalLoad(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElementCall(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEndElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumValue(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteIsStartTag(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderILGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitiveValue(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteQualifiedNameElement(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteTag(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteTag(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteText(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteText(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteUnknownNode(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual().