Terraria: System.Xml.Serialization.CodeGenerator.AndIf
AndIf() [1/2]
void System.Xml.Serialization.CodeGenerator.AndIf () inline package
Definition at line 1279 of file CodeGenerator.cs.
    {
        if (_initIfStack == _blockStack.Count)
        {
            _initIfStack = -1;
            If();
        }
        else if (_initElseIfStack == _blockStack.Count)
        {
            _initElseIfStack = -1;
            _elseIfState.ElseBegin = DefineLabel();
            Brfalse(_elseIfState.ElseBegin);
            _blockStack.Push(_elseIfState);
        }
        else
        {
            IfState ifState = (IfState)_blockStack.Peek();
            Brfalse(ifState.ElseBegin);
        }
    }
References System.Xml.Serialization.CodeGenerator._blockStack, System.Xml.Serialization.CodeGenerator._elseIfState, System.Xml.Serialization.CodeGenerator._initElseIfStack, System.Xml.Serialization.CodeGenerator._initIfStack, System.Reflection.Emit.Brfalse, System.Collections.Generic.Stack< T >.Count, System.Xml.Serialization.CodeGenerator.DefineLabel(), System.Xml.Dictionary, System.Xml.Serialization.IfState.ElseBegin, System.Xml.Serialization.CodeGenerator.If(), System.Collections.Generic.Stack< T >.Peek(), and System.Collections.Generic.Stack< T >.Push().