Terraria: System.Xml.Serialization.CodeGenerator.InternalConvert
InternalConvert()
void System.Xml.Serialization.CodeGenerator.InternalConvert (Type source, Type target, bool isAddress) inline private
Definition at line 1168 of file CodeGenerator.cs.
    {
        if (target == source)
        {
            return;
        }
        if (target.IsValueType)
        {
            if (source.IsValueType)
            {
                OpCode convOpCode = GetConvOpCode(Type.GetTypeCode(target));
                if (convOpCode.Equals(OpCodes.Nop))
                {
                    throw new CodeGeneratorConversionException(source, target, isAddress, "NoConversionPossibleTo");
                }
                _ilGen.Emit(convOpCode);
                return;
            }
            if (!source.IsAssignableFrom(target))
            {
                throw new CodeGeneratorConversionException(source, target, isAddress, "IsNotAssignableFrom");
            }
            Unbox(target);
            if (!isAddress)
            {
                Ldobj(target);
            }
        }
        else if (target.IsAssignableFrom(source))
        {
            if (source.IsValueType)
            {
                if (isAddress)
                {
                    Ldobj(source);
                }
                Box(source);
            }
        }
        else if (source.IsAssignableFrom(target))
        {
            Castclass(target);
        }
        else
        {
            if (!target.IsInterface && !source.IsInterface)
            {
                throw new CodeGeneratorConversionException(source, target, isAddress, "IsNotAssignableFrom");
            }
            Castclass(target);
        }
    }
References System.Xml.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.Box, System.Reflection.Emit.Castclass, System.Reflection.Emit.ILGenerator.Emit(), System.Xml.Serialization.CodeGenerator.GetConvOpCode(), System.Type.GetTypeCode(), System.Type.IsAssignableFrom(), System.Type.IsInterface, System.Type.IsValueType, System.Reflection.Emit.Ldobj, System.Reflection.Emit.OpCodes.Nop, System.source, and System.Reflection.Emit.Unbox.
Referenced by System.Xml.Serialization.CodeGenerator.ConvertAddress(), and System.Xml.Serialization.CodeGenerator.ConvertValue().