Terraria: System.Xml.Serialization.CodeGenerator.Stloc
Stloc() [2/2]
void System.Xml.Serialization.CodeGenerator.Stloc (Type type, string name) inline package
Definition at line 972 of file CodeGenerator.cs.
    {
        LocalBuilder value = null;
        if (!_currentScope.TryGetValue(name, out value))
        {
            value = DeclareLocal(type, name);
        }
        Stloc(value);
    }
References System.Xml.Serialization.CodeGenerator._currentScope, System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Reflection.Emit.Stloc, System.Xml.Serialization.LocalScope.TryGetValue(), System.type, and System.value.
Referenced by System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateTypeElement(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.SourceInfo.InternalLoad(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.ReflectionAwareILGen.WriteCreateInstance(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteText().