Terraria: System.Xml.Serialization.CodeGenerator.DeclareOrGetLocal
DeclareOrGetLocal()
LocalBuilder System.Xml.Serialization.CodeGenerator.DeclareOrGetLocal (Type type, string name) inline package
Definition at line 341 of file CodeGenerator.cs.
    {
        if (!_currentScope.TryGetValue(name, out var value))
        {
            return DeclareLocal(type, name);
        }
        return value;
    }
References System.Xml.Serialization.CodeGenerator._currentScope, System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Serialization.LocalScope.TryGetValue(), System.type, and System.value.
Referenced by System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.ReflectionAwareILGen.WriteCreateInstance(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumAndArrayTypes(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember().