Terraria: System.Xml.Serialization.CodeGenerator.DefineLabel
DefineLabel()
Label System.Xml.Serialization.CodeGenerator.DefineLabel () inline package
Definition at line 1087 of file CodeGenerator.cs.
    {
        return _ilGen.DefineLabel();
    }
References System.Xml.Serialization.CodeGenerator._ilGen, and System.Reflection.Emit.ILGenerator.DefineLabel().
Referenced by System.Xml.Serialization.CodeGenerator.WhileState.WhileState(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.BeginExceptionBlock(), System.Xml.Serialization.CodeGenerator.For(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.CodeGenerator.InternalIf(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElementsIf(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberText(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteQNameEqual(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteXmlNodeEqual().