Terraria: System.Xml.Serialization.CodeGenerator.GetPropertyMethodFromBaseType
GetPropertyMethodFromBaseType()
static MethodInfo System.Xml.Serialization.CodeGenerator.GetPropertyMethodFromBaseType (PropertyInfo propertyInfo, bool isGetter) inline static private
Definition at line 572 of file CodeGenerator.cs.
    {
        Type baseType = propertyInfo.DeclaringType.BaseType;
        string name = propertyInfo.Name;
        MethodInfo methodInfo = null;
        while (baseType != null)
        {
            PropertyInfo property = baseType.GetProperty(name);
            if (property != null)
            {
                methodInfo = ((!isGetter) ? property.SetMethod : property.GetMethod);
                if (methodInfo != null)
                {
                    break;
                }
            }
            baseType = baseType.BaseType;
        }
        return methodInfo;
    }
References System.Type.BaseType, System.Reflection.MemberInfo.DeclaringType, System.Xml.Dictionary, and System.Reflection.MemberInfo.Name.
Referenced by System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.LoadMemberAddress(), and System.Xml.Serialization.CodeGenerator.StoreMember().