Terraria: System.Xml.Serialization.CodeGenerator.WhileBegin
WhileBegin()
void System.Xml.Serialization.CodeGenerator.WhileBegin () inline package
Definition at line 1320 of file CodeGenerator.cs.
    {
        WhileState whileState = new WhileState(this);
        Ldc(boolVar: true);
        Brtrue(whileState.CondLabel);
        MarkLabel(whileState.StartLabel);
        _whileStack.Push(whileState);
    }
References System.Xml.Serialization.CodeGenerator._whileStack, System.Reflection.Emit.Brtrue, System.Xml.Serialization.CodeGenerator.Ldc(), and System.Xml.Serialization.CodeGenerator.MarkLabel().
Referenced by System.Xml.Serialization.ReflectionAwareILGen.ILGenForCreateInstance(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes().