Terraria: System.Xml.Serialization.CodeGenerator.If
If() [1/3]
void System.Xml.Serialization.CodeGenerator.If () inline package
Definition at line 395 of file CodeGenerator.cs.
    {
        InternalIf(negate: false);
    }
References System.Xml.Serialization.CodeGenerator.InternalIf().
Referenced by System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.CodeGenerator.AndIf(), System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetEnd(), System.Xml.Serialization.XmlSerializationReaderILGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateMembersElement(), System.Xml.Serialization.XmlSerializationILGen.GenerateSupportedTypes(), System.Xml.Serialization.XmlSerializationWriterILGen.GenerateTypeElement(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteHashtable(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteIsStartTag(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteLiteralStructMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WriteMember(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteNullableMethod(), System.Xml.Serialization.XmlSerializationWriterILGen.WritePrimitive(), and System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod().