Terraria: System.Xml.Xsl.Runtime.ContentMergeIterator.MoveNext
MoveNext() [2/2]
IteratorResult System.Xml.Xsl.Runtime.ContentMergeIterator.MoveNext (XPathNavigator input, bool isContent) inline package
Definition at line 41 of file ContentMergeIterator.cs.
    {
        switch (_state)
        {
        case IteratorState.NeedCurrent:
            if (input == null)
            {
                return IteratorResult.NoMoreNodes;
            }
            _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, input);
            if (isContent ? _filter.MoveToContent(_navCurrent) : _filter.MoveToFollowingSibling(_navCurrent))
            {
                _state = IteratorState.HaveCurrentNeedNext;
            }
            return IteratorResult.NeedInputNode;
        case IteratorState.HaveCurrentNeedNext:
            if (input == null)
            {
                _state = IteratorState.HaveCurrentNoNext;
                return IteratorResult.HaveCurrentNode;
            }
            _navNext = XmlQueryRuntime.SyncToNavigator(_navNext, input);
            if (isContent ? _filter.MoveToContent(_navNext) : _filter.MoveToFollowingSibling(_navNext))
            {
                _state = IteratorState.HaveCurrentHaveNext;
                return DocOrderMerge();
            }
            return IteratorResult.NeedInputNode;
        case IteratorState.HaveCurrentNoNext:
        case IteratorState.HaveCurrentHaveNext:
            if (isContent ? (!_filter.MoveToNextContent(_navCurrent)) : (!_filter.MoveToFollowingSibling(_navCurrent)))
            {
                if (_navStack.IsEmpty)
                {
                    if (_state == IteratorState.HaveCurrentNoNext)
                    {
                        return IteratorResult.NoMoreNodes;
                    }
                    _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, _navNext);
                    _state = IteratorState.HaveCurrentNeedNext;
                    return IteratorResult.NeedInputNode;
                }
                _navCurrent = _navStack.Pop();
            }
            if (_state == IteratorState.HaveCurrentNoNext)
            {
                return IteratorResult.HaveCurrentNode;
            }
            return DocOrderMerge();
        default:
            return IteratorResult.NoMoreNodes;
        }
    }
References System.Xml.Xsl.Runtime.ContentMergeIterator._filter, System.Xml.Xsl.Runtime.ContentMergeIterator._navCurrent, System.Xml.Xsl.Runtime.ContentMergeIterator._navNext, System.Xml.Xsl.Runtime.ContentMergeIterator._navStack, System.Xml.Xsl.Runtime.ContentMergeIterator._state, System.Xml.Dictionary, System.Xml.Xsl.Runtime.ContentMergeIterator.DocOrderMerge(), System.input, System.Xml.Xsl.Runtime.XmlNavigatorStack.IsEmpty, System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToContent(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToFollowingSibling(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToNextContent(), System.Xml.Xsl.Runtime.XmlNavigatorStack.Pop(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator().