Terraria: System.Xml.Xsl.Runtime.ContentMergeIterator.DocOrderMerge
DocOrderMerge()
IteratorResult System.Xml.Xsl.Runtime.ContentMergeIterator.DocOrderMerge () inline private
Definition at line 95 of file ContentMergeIterator.cs.
    {
        switch (_navCurrent.ComparePosition(_navNext))
        {
        case XmlNodeOrder.Before:
        case XmlNodeOrder.Unknown:
            return IteratorResult.HaveCurrentNode;
        case XmlNodeOrder.After:
            _navStack.Push(_navCurrent);
            _navCurrent = _navNext;
            _navNext = null;
            break;
        }
        _state = IteratorState.HaveCurrentNeedNext;
        return IteratorResult.NeedInputNode;
    }
References System.Xml.Xsl.Runtime.ContentMergeIterator._navCurrent, System.Xml.Xsl.Runtime.ContentMergeIterator._navNext, System.Xml.Xsl.Runtime.ContentMergeIterator._navStack, System.Xml.Xsl.Runtime.ContentMergeIterator._state, System.Xml.XPath.XPathNavigator.ComparePosition(), and System.Xml.Xsl.Runtime.XmlNavigatorStack.Push().
Referenced by System.Xml.Xsl.Runtime.ContentMergeIterator.MoveNext().