Terraria: HelpCommand.ComposeMessage
ComposeMessage()
static NetworkText HelpCommand.ComposeMessage (Dictionary< string, List< LocalizedText >> aliases) inline static private
     {
         string text = "";
         for (int i = 0; i < aliases.Count; i++)
         {
             text = text + "{" + i + "}\n";
         }
         List<NetworkText> list = new List<NetworkText>();
         foreach (KeyValuePair<string, List<LocalizedText>> alias in aliases)
         {
             list.Add(Language.GetText("ChatCommandDescription." + alias.Key).ToNetworkText());
         }
         string text2 = text;
         object[] substitutions = list.ToArray();
         return NetworkText.FromFormattable(text2, substitutions);
     }
References NetworkText.FromFormattable(), Language.GetText(), and LocalizedText.ToNetworkText().
Referenced by ProcessIncomingMessage().