Terraria: HelpCommand.GetCommandAliasesByID
GetCommandAliasesByID()
static Dictionary<string, List<LocalizedText> > HelpCommand.GetCommandAliasesByID () inline static private
     {
         object substitutions = Lang.CreateDialogSubstitutionObject();
         LocalizedText[] array = Language.FindAll(Lang.CreateDialogFilter("ChatCommandDescription.", substitutions));
         Dictionary<string, List<LocalizedText>> dictionary = new Dictionary<string, List<LocalizedText>>();
         LocalizedText[] array2 = array;
         foreach (LocalizedText localizedText in array2)
         {
             string key = localizedText.Key;
             key = key.Replace("ChatCommandDescription.", "");
             int num = key.IndexOf('_');
             if (num != -1)
             {
                 key = key.Substring(0, num);
             }
             if (!dictionary.TryGetValue(key, out var value))
             {
                 value = (dictionary[key] = new List<LocalizedText>());
             }
             value.Add(localizedText);
         }
         return dictionary;
     }
References Lang.CreateDialogFilter(), Lang.CreateDialogSubstitutionObject(), Language.FindAll(), and LocalizedText.Key.
Referenced by ProcessIncomingMessage().