Terraria: System.Net.NetworkInformation.SystemNetworkInterface.GetNetworkInterfaces
GetNetworkInterfaces()
static NetworkInterface[] System.Net.NetworkInformation.SystemNetworkInterface.GetNetworkInterfaces () inline static package
Definition at line 90 of file SystemNetworkInterface.cs.
    {
        AddressFamily family = AddressFamily.Unspecified;
        uint outBufLen = 0u;
        ref readonly global::Interop.IpHlpApi.FIXED_INFO fixedInfo = ref System.Net.NetworkInformation.HostInformationPal.FixedInfo;
        List<SystemNetworkInterface> list = new List<SystemNetworkInterface>();
        global::Interop.IpHlpApi.GetAdaptersAddressesFlags flags = global::Interop.IpHlpApi.GetAdaptersAddressesFlags.IncludeWins | global::Interop.IpHlpApi.GetAdaptersAddressesFlags.IncludeGateways;
        uint adaptersAddresses = global::Interop.IpHlpApi.GetAdaptersAddresses(family, (uint)flags, IntPtr.Zero, IntPtr.Zero, ref outBufLen);
        while (true)
        {
            switch (adaptersAddresses)
            {
            case 111u:
            {
                IntPtr intPtr = Marshal.AllocHGlobal((int)outBufLen);
                try
                {
                    adaptersAddresses = global::Interop.IpHlpApi.GetAdaptersAddresses(family, (uint)flags, IntPtr.Zero, intPtr, ref outBufLen);
                    if (adaptersAddresses == 0)
                    {
                        IntPtr intPtr2 = intPtr;
                        while (intPtr2 != IntPtr.Zero)
{
                            global::Interop.IpHlpApi.IpAdapterAddresses ipAdapterAddresses = Marshal.PtrToStructure<global::Interop.IpHlpApi.IpAdapterAddresses>(intPtr2);
                            list.Add(new SystemNetworkInterface(in fixedInfo, in ipAdapterAddresses));
                            intPtr2 = ipAdapterAddresses.next;
                        }
                    }
                }
                finally
                {
                    Marshal.FreeHGlobal(intPtr);
                }
                break;
            }
            case 87u:
            case 232u:
                return Array.Empty<SystemNetworkInterface>();
            default:
                throw new NetworkInformationException((int)adaptersAddresses);
            case 0u:
                return list.ToArray();
            }
        }
    }
References System.Net.NetworkInformation.SystemNetworkInterface.SystemNetworkInterface(), System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Net.NetworkInformation.HostInformationPal.FixedInfo, System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.list, System.Runtime.InteropServices.Marshal.PtrToStructure(), and System.IntPtr.Zero.
Referenced by System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces(), and System.Net.NetworkInformation.SystemNetworkInterface.InternalGetIsNetworkAvailable().