Terraria: System.Net.Http.HttpConnection.InitialFillAsync
InitialFillAsync()
async ValueTask System.Net.Http.HttpConnection.InitialFillAsync (bool async) inline private
Definition at line 2279 of file HttpConnection.cs.
    {
        _readOffset = 0;
        int readLength = ((!async) ? _stream.Read(_readBuffer) : (await _stream.ReadAsync(_readBuffer).ConfigureAwait(continueOnCapturedContext: false)));
        _readLength = readLength;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"Received {_readLength} bytes.", "InitialFillAsync");
        }
    }
References System.Net.Http.HttpConnection._readBuffer, System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.Net.Http.HttpConnection._stream, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.NetEventSource.Log, System.IO.Stream.Read(), System.IO.Stream.ReadAsync(), and System.Net.Http.HttpConnection.Trace().
Referenced by System.Net.Http.HttpConnection.SendAsyncCore().