Terraria: System.Net.Http.HttpConnection.CopyToUntilEofWithExistingBufferedDataAsync
CopyToUntilEofWithExistingBufferedDataAsync()
async Task System.Net.Http.HttpConnection.CopyToUntilEofWithExistingBufferedDataAsync (Stream destination, bool async, int bufferSize, CancellationToken cancellationToken) inline private
Definition at line 2464 of file HttpConnection.cs.
    {
        int count = _readLength - _readOffset;
        await CopyFromBufferAsync(destination, async, count, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        _readLength = (_readOffset = 0);
        if (async)
        {
            await _stream.CopyToAsync(destination, bufferSize, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            _stream.CopyTo(destination, bufferSize);
        }
    }
References System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.Net.Http.HttpConnection._stream, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Http.HttpConnection.CopyFromBufferAsync(), System.IO.Stream.CopyTo(), System.IO.Stream.CopyToAsync(), System.count, and System.destination.
Referenced by System.Net.Http.HttpConnection.CopyToUntilEofAsync().