Terraria: System.Net.Http.HttpConnection.MapSendException
MapSendException()
bool System.Net.Http.HttpConnection.MapSendException (Exception exception, CancellationToken cancellationToken, out Exception mappedException) inline private
Definition at line 1674 of file HttpConnection.cs.
    {
        if (CancellationHelper.ShouldWrapInOperationCanceledException(exception, cancellationToken))
        {
            mappedException = CancellationHelper.CreateOperationCanceledException(exception, cancellationToken);
            return true;
        }
        if (exception is InvalidOperationException)
        {
            mappedException = new HttpRequestException(System.SR.net_http_client_execution_error, exception);
            return true;
        }
        if (exception is IOException inner)
        {
            mappedException = new HttpRequestException(System.SR.net_http_client_execution_error, inner, _canRetry ? RequestRetryType.RetryOnConnectionFailure : RequestRetryType.NoRetry);
            return true;
        }
        mappedException = exception;
        return false;
    }
References System.Net.Http.HttpConnection._canRetry, System.cancellationToken, System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.exception, System.SR.net_http_client_execution_error, and System.Net.Http.CancellationHelper.ShouldWrapInOperationCanceledException().
Referenced by System.Net.Http.HttpConnection.SendAsyncCore().