Terraria: System.Net.Http.HttpConnection.SendRequestContentAsync
SendRequestContentAsync()
async ValueTask System.Net.Http.HttpConnection.SendRequestContentAsync (HttpRequestMessage request, HttpContentWriteStream stream, bool async, CancellationToken cancellationToken) inline private
Definition at line 1721 of file HttpConnection.cs.
    {
        _startedSendingRequestBody = true;
        if (HttpTelemetry.Log.IsEnabled())
        {
            HttpTelemetry.Log.RequestContentStart();
        }
        if (async)
        {
            await request.Content.CopyToAsync(stream, _transportContext, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            request.Content.CopyTo(stream, _transportContext, cancellationToken);
        }
        await stream.FinishAsync(async).ConfigureAwait(continueOnCapturedContext: false);
        await FlushAsync(async).ConfigureAwait(continueOnCapturedContext: false);
        if (HttpTelemetry.Log.IsEnabled())
        {
            HttpTelemetry.Log.RequestContentStop(stream.BytesWritten);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("Finished sending request content.", "SendRequestContentAsync");
        }
    }
References System.Net.Http.HttpConnection._startedSendingRequestBody, System.Net.Http.HttpConnection._transportContext, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Net.Http.HttpConnection.FlushAsync(), System.Net.Http.HttpTelemetry.Log, System.Net.NetEventSource.Log, System.stream, and System.Net.Http.HttpConnection.Trace().
Referenced by System.Net.Http.HttpConnection.SendAsyncCore(), and System.Net.Http.HttpConnection.SendRequestContentWithExpect100ContinueAsync().