Terraria: System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync
ReadNextResponseHeaderLineAsync()
async ValueTask< ReadOnlyMemory< byte > > System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync (bool async, bool foldedHeadersAllowed = false) inline private
Definition at line 2202 of file HttpConnection.cs.
    {
        int previouslyScannedBytes = 0;
        int num;
        int num2;
        int readOffset;
        int num3;
        while (true)
        {
            num = _readOffset + previouslyScannedBytes;
            num2 = Array.IndexOf(_readBuffer, (byte)10, num, _readLength - num);
            if (num2 >= 0)
            {
                readOffset = _readOffset;
                num3 = num2 - readOffset;
                if (num2 > 0 && _readBuffer[num2 - 1] == 13)
                {
                    num3--;
                }
                if (!foldedHeadersAllowed || num3 <= 0)
                {
                    break;
                }
                if (num2 + 1 == _readLength)
                {
                    int num4 = ((_readBuffer[num2 - 1] == 13) ? (num2 - 2) : (num2 - 1));
                    previouslyScannedBytes = num4 - _readOffset;
                    _allowedReadLineBytes -= num4 - num;
                    ThrowIfExceededAllowedReadLineBytes();
                    await FillAsync(async).ConfigureAwait(continueOnCapturedContext: false);
                    continue;
                }
                char c = (char)_readBuffer[num2 + 1];
                if (c != ' ' && c != '\t')
                {
                    break;
                }
                if (Array.IndexOf(_readBuffer, (byte)58, _readOffset, num2 - _readOffset) == -1)
                {
                    throw new HttpRequestException(System.SR.net_http_invalid_response_header_folder);
                }
                _readBuffer[num2] = 32;
                if (_readBuffer[num2 - 1] == 13)
                {
                    _readBuffer[num2 - 1] = 32;
                }
                previouslyScannedBytes = num2 + 1 - _readOffset;
                _allowedReadLineBytes -= num2 + 1 - num;
                ThrowIfExceededAllowedReadLineBytes();
            }
            else
            {
                previouslyScannedBytes = _readLength - _readOffset;
                _allowedReadLineBytes -= _readLength - num;
                ThrowIfExceededAllowedReadLineBytes();
                await FillAsync(async).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        _allowedReadLineBytes -= num2 + 1 - num;
        ThrowIfExceededAllowedReadLineBytes();
        _readOffset = num2 + 1;
        return new ReadOnlyMemory<byte>(_readBuffer, readOffset, num3);
    }
References System.Net.Http.HttpConnection._allowedReadLineBytes, System.Net.Http.HttpConnection._readBuffer, System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.Net.Http.HttpConnection.FillAsync(), System.Array.IndexOf(), System.SR.net_http_invalid_response_header_folder, and System.Net.Http.HttpConnection.ThrowIfExceededAllowedReadLineBytes().
Referenced by System.Net.Http.HttpConnection.SendAsyncCore().