Terraria: System.Net.Http.HttpConnection.FlushThenWriteWithoutBufferingAsync
FlushThenWriteWithoutBufferingAsync()
async ValueTask System.Net.Http.HttpConnection.FlushThenWriteWithoutBufferingAsync (ReadOnlyMemory< byte > source, bool async) inline private
Definition at line 1986 of file HttpConnection.cs.
    {
        await FlushAsync(async).ConfigureAwait(continueOnCapturedContext: false);
        await WriteToStreamAsync(source, async).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Http.HttpConnection.FlushAsync(), System.source, and System.Net.Http.HttpConnection.WriteToStreamAsync().
Referenced by System.Net.Http.HttpConnection.WriteWithoutBufferingAsync().