Terraria: System.Net.Http.HttpConnection.FillAsync
FillAsync()
async ValueTask System.Net.Http.HttpConnection.FillAsync (bool async) inline private
Definition at line 2290 of file HttpConnection.cs.
    {
        int num = _readLength - _readOffset;
        if (num == 0)
        {
            _readOffset = (_readLength = 0);
        }
        else if (_readOffset > 0)
        {
            Buffer.BlockCopy(_readBuffer, _readOffset, _readBuffer, 0, num);
            _readOffset = 0;
            _readLength = num;
        }
        else if (num == _readBuffer.Length)
        {
            byte[] array = new byte[_readBuffer.Length * 2];
            Buffer.BlockCopy(_readBuffer, 0, array, 0, num);
            _readBuffer = array;
            _readOffset = 0;
            _readLength = num;
        }
        int num2 = ((!async) ? _stream.Read(_readBuffer, _readLength, _readBuffer.Length - _readLength) : (await _stream.ReadAsync(new Memory<byte>(_readBuffer, _readLength, _readBuffer.Length - _readLength)).ConfigureAwait(continueOnCapturedContext: false)));
        int num3 = num2;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"Received {num3} bytes.", "FillAsync");
        }
        if (num3 == 0)
        {
            throw new IOException(System.SR.net_http_invalid_response_premature_eof);
        }
        _readLength += num3;
    }
References System.Net.Http.HttpConnection._readBuffer, System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.Net.Http.HttpConnection._stream, System.array, System.Buffer.BlockCopy(), System.Net.NetEventSource.Log, System.SR.net_http_invalid_response_premature_eof, System.IO.Stream.Read(), System.IO.Stream.ReadAsync(), and System.Net.Http.HttpConnection.Trace().
Referenced by System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(), System.Net.Http.HttpConnection.CopyToContentLengthAsync(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.DrainAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.DrainAsync(), System.Net.Http.HttpConnection.Fill(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(), and System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync().