Terraria: System.Net.Http.HttpConnection.CompleteResponse
CompleteResponse()
void System.Net.Http.HttpConnection.CompleteResponse () inline private
Definition at line 2556 of file HttpConnection.cs.
    {
        _currentRequest = null;
        if (_readLength != _readOffset)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("Unexpected data on connection after response read.", "CompleteResponse");
            }
            _readOffset = (_readLength = 0);
            _connectionClose = true;
        }
        if (!_inUse)
        {
            ReturnConnectionToPool();
        }
    }
References System.Net.Http.HttpConnection._connectionClose, System.Net.Http.HttpConnection._currentRequest, System.Net.Http.HttpConnection._inUse, System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.Net.NetEventSource.Log, System.Net.Http.HttpConnection.ReturnConnectionToPool(), and System.Net.Http.HttpConnection.Trace().
Referenced by System.Net.Http.HttpConnection.ContentLengthReadStream.Finish(), System.Net.Http.HttpConnection.ContentLengthReadStream.Read(), System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer(), and System.Net.Http.HttpConnection.SendAsyncCore().