Terraria: System.Net.Http.HttpConnection.CopyToContentLengthAsync
CopyToContentLengthAsync()
async Task System.Net.Http.HttpConnection.CopyToContentLengthAsync (Stream destination, bool async, ulong length, int bufferSize, CancellationToken cancellationToken) inline private
Definition at line 2479 of file HttpConnection.cs.
    {
        int remaining = _readLength - _readOffset;
        if (remaining > 0)
        {
            if ((ulong)remaining > length)
            {
                remaining = (int)length;
            }
            await CopyFromBufferAsync(destination, async, remaining, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            length -= (ulong)remaining;
            if (length == 0L)
            {
                return;
            }
        }
        byte[] origReadBuffer = null;
        try
        {
            while (true)
            {
                await FillAsync(async).ConfigureAwait(continueOnCapturedContext: false);
                remaining = (((ulong)_readLength < length) ? _readLength : ((int)length));
                await CopyFromBufferAsync(destination, async, remaining, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                length -= (ulong)remaining;
                if (length == 0L)
                {
                    break;
                }
                if (origReadBuffer != null)
                {
                    continue;
                }
                byte[] readBuffer = _readBuffer;
                if (remaining == readBuffer.Length)
                {
                    int num = (int)Math.Min((ulong)bufferSize, length);
                    if (num > readBuffer.Length)
                    {
                        origReadBuffer = readBuffer;
                        _readBuffer = ArrayPool<byte>.Shared.Rent(num);
                    }
                }
            }
        }
        finally
        {
            if (origReadBuffer != null)
            {
                byte[] readBuffer2 = _readBuffer;
                _readBuffer = origReadBuffer;
                ArrayPool<byte>.Shared.Return(readBuffer2);
                _readLength = ((_readOffset < _readLength) ? 1 : 0);
                _readOffset = 0;
            }
        }
    }
References System.Net.Http.HttpConnection._readBuffer, System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Http.HttpConnection.CopyFromBufferAsync(), System.destination, System.Net.Http.HttpConnection.FillAsync(), System.L, System.length, and System.Math.Min().
Referenced by System.Net.Http.HttpConnection.ContentLengthReadStream.CopyToAsync().