Terraria: System.Net.Http.HttpConnection.ReadAsync
ReadAsync()
async ValueTask< int > System.Net.Http.HttpConnection.ReadAsync (Memory< byte > destination) inline private
Definition at line 2351 of file HttpConnection.cs.
    {
        int num = _readLength - _readOffset;
        if (num > 0)
        {
            if (destination.Length <= num)
            {
                ReadFromBuffer(destination.Span);
                return destination.Length;
            }
            ReadFromBuffer(destination.Span.Slice(0, num));
            return num;
        }
        int num2 = await _stream.ReadAsync(destination).ConfigureAwait(continueOnCapturedContext: false);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"Received {num2} bytes.", "ReadAsync");
        }
        return num2;
    }
References System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.Net.Http.HttpConnection._stream, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.destination, System.Net.NetEventSource.Log, System.IO.Stream.ReadAsync(), System.Net.Http.HttpConnection.ReadFromBuffer(), and System.Net.Http.HttpConnection.Trace().
Referenced by System.Net.Http.HttpConnection.ConnectionCloseReadStream.ReadAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(), and System.Net.Http.HttpConnection.ReadBufferedAsync().