Terraria: System.Net.Http.HttpConnection.ParseStatusLine
ParseStatusLine()
static void System.Net.Http.HttpConnection.ParseStatusLine (ReadOnlySpan< byte > line, HttpResponseMessage response) inline static private
Definition at line 1775 of file HttpConnection.cs.
    {
        if (line.Length < 12 || line[8] != 32)
        {
            throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_status_line, Encoding.ASCII.GetString(line)));
        }
        ulong num = BitConverter.ToUInt64(line);
        if (num == s_http11Bytes)
        {
            response.SetVersionWithoutValidation(HttpVersion.Version11);
        }
        else if (num == s_http10Bytes)
        {
            response.SetVersionWithoutValidation(HttpVersion.Version10);
        }
        else
        {
            byte b = line[7];
            if (!HttpConnectionBase.IsDigit(b) || !line.Slice(0, 7).SequenceEqual(s_http1DotBytes))
            {
                throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_status_line, Encoding.ASCII.GetString(line)));
            }
            response.SetVersionWithoutValidation(new Version(1, b - 48));
        }
        byte b2 = line[9];
        byte b3 = line[10];
        byte b4 = line[11];
        if (!HttpConnectionBase.IsDigit(b2) || !HttpConnectionBase.IsDigit(b3) || !HttpConnectionBase.IsDigit(b4))
        {
            throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_status_code, Encoding.ASCII.GetString(line.Slice(9, 3))));
        }
        response.SetStatusCodeWithoutValidation((HttpStatusCode)(100 * (b2 - 48) + 10 * (b3 - 48) + (b4 - 48)));
        if (line.Length == 12)
        {
            response.SetReasonPhraseWithoutValidation(string.Empty);
            return;
        }
        if (line[12] == 32)
        {
            ReadOnlySpan<byte> readOnlySpan = line.Slice(13);
            string text = HttpStatusDescription.Get(response.StatusCode);
            if (text != null && EqualsOrdinal(text, readOnlySpan))
            {
                response.SetReasonPhraseWithoutValidation(text);
                return;
            }
            try
            {
                response.ReasonPhrase = HttpRuleParser.DefaultHttpEncoding.GetString(readOnlySpan);
                return;
            }
            catch (FormatException inner)
            {
                throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_status_reason, Encoding.ASCII.GetString(readOnlySpan.ToArray())), inner);
            }
        }
        throw new HttpRequestException(System.SR.Format(System.SR.net_http_invalid_response_status_line, Encoding.ASCII.GetString(line)));
    }
References System.Text.Encoding.ASCII, System.Net.Http.HttpRuleParser.DefaultHttpEncoding, System.Net.Http.HttpConnection.EqualsOrdinal(), System.SR.Format(), System.Net.HttpStatusDescription.Get(), System.Net.Http.HttpConnectionBase.IsDigit(), System.SR.net_http_invalid_response_status_code, System.SR.net_http_invalid_response_status_line, System.SR.net_http_invalid_response_status_reason, System.Net.Http.HttpConnection.s_http10Bytes, System.Net.Http.HttpConnection.s_http11Bytes, System.Net.Http.HttpConnection.s_http1DotBytes, System.text, System.BitConverter.ToUInt64(), System.Net.Version, System.Net.HttpVersion.Version10, and System.Net.HttpVersion.Version11.
Referenced by System.Net.Http.HttpConnection.SendAsyncCore().