Terraria: System.Net.Http.HttpConnection.ConsumeReadAheadTask
ConsumeReadAheadTask()
ValueTask< int >? System.Net.Http.HttpConnection.ConsumeReadAheadTask () inline private
Definition at line 1235 of file HttpConnection.cs.
    {
        if (Interlocked.CompareExchange(ref _readAheadTaskLock, 1, 0) == 0)
        {
            ValueTask<int>? readAheadTask = _readAheadTask;
            _readAheadTask = null;
            Volatile.Write(ref _readAheadTaskLock, 0);
            return readAheadTask;
        }
        return null;
    }
References System.Net.Http.HttpConnection._readAheadTask, System.Net.Http.HttpConnection._readAheadTaskLock, System.Threading.Interlocked.CompareExchange(), and System.Threading.Volatile.Write().
Referenced by System.Net.Http.HttpConnection.Dispose(), and System.Net.Http.HttpConnection.SendAsyncCore().