Terraria: System.Net.Http.HttpConnection.ThrowIfExceededAllowedReadLineBytes
ThrowIfExceededAllowedReadLineBytes()
void System.Net.Http.HttpConnection.ThrowIfExceededAllowedReadLineBytes () inline private
Definition at line 2266 of file HttpConnection.cs.
    {
        if (_allowedReadLineBytes < 0)
        {
            throw new HttpRequestException(System.SR.Format(System.SR.net_http_response_headers_exceeded_length, (long)_pool.Settings._maxResponseHeadersLength * 1024L));
        }
    }
References System.Net.Http.HttpConnection._allowedReadLineBytes, System.Net.Http.HttpConnectionSettings._maxResponseHeadersLength, System.Net.Http.HttpConnection._pool, System.SR.Format(), System.L, System.SR.net_http_response_headers_exceeded_length, and System.Net.Http.HttpConnectionPool.Settings.
Referenced by System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(), and System.Net.Http.HttpConnection.TryReadNextLine().