Terraria: System.Net.Http.HttpConnection.HttpConnection
HttpConnection()
System.Net.Http.HttpConnection.HttpConnection (HttpConnectionPool pool, Socket socket, Stream stream, TransportContext transportContext) inline
Definition at line 1125 of file HttpConnection.cs.
    {
        _pool = pool;
        _stream = stream;
        _socket = socket;
        _transportContext = transportContext;
        _writeBuffer = new byte[4096];
        _readBuffer = new byte[4096];
        _weakThisRef = new WeakReference<HttpConnection>(this);
        _idleSinceTickCount = Environment.TickCount64;
        if (HttpTelemetry.Log.IsEnabled())
        {
            HttpTelemetry.Log.Http11ConnectionEstablished();
            _disposed = 2;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            TraceConnection(_stream);
        }
    }
References System.Net.Http.HttpConnection._disposed, System.Net.Http.HttpConnection._idleSinceTickCount, System.Net.Http.HttpConnection._pool, System.Net.Http.HttpConnection._readBuffer, System.Net.Http.HttpConnection._socket, System.Net.Http.HttpConnection._stream, System.Net.Http.HttpConnection._transportContext, System.Net.Http.HttpConnection._weakThisRef, System.Net.Http.HttpConnection._writeBuffer, System.Net.Http.HttpTelemetry.Log, System.Net.NetEventSource.Log, System.stream, System.Environment.TickCount64, and System.Net.Http.HttpConnectionBase.TraceConnection().
Referenced by System.Net.Http.HttpConnection.ChunkedEncodingReadStream.DrainAsync(), and System.Net.Http.HttpConnection.ContentLengthReadStream.DrainAsync().