Terraria: System.Net.Http.HttpConnection.TryReadNextLine
TryReadNextLine()
bool System.Net.Http.HttpConnection.TryReadNextLine (out ReadOnlySpan< byte > line) inline private
Definition at line 2181 of file HttpConnection.cs.
    {
        ReadOnlySpan<byte> span = new ReadOnlySpan<byte>(_readBuffer, _readOffset, _readLength - _readOffset);
        int num = span.IndexOf<byte>(10);
        if (num < 0)
        {
            if (_allowedReadLineBytes < span.Length)
            {
                throw new HttpRequestException(System.SR.Format(System.SR.net_http_response_headers_exceeded_length, (long)_pool.Settings._maxResponseHeadersLength * 1024L));
            }
            line = default(ReadOnlySpan<byte>);
            return false;
        }
        int num2 = num + 1;
        _readOffset += num2;
        _allowedReadLineBytes -= num2;
        ThrowIfExceededAllowedReadLineBytes();
        line = span.Slice(0, (num > 0 && span[num - 1] == 13) ? (num - 1) : num);
        return true;
    }
References System.Net.Http.HttpConnection._allowedReadLineBytes, System.Net.Http.HttpConnectionSettings._maxResponseHeadersLength, System.Net.Http.HttpConnection._pool, System.Net.Http.HttpConnection._readBuffer, System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.SR.Format(), System.L, System.SR.net_http_response_headers_exceeded_length, System.Net.Http.HttpConnectionPool.Settings, and System.Net.Http.HttpConnection.ThrowIfExceededAllowedReadLineBytes().
Referenced by System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer().