Terraria: System.Net.Http.HttpConnection.WriteToStream
WriteToStream()
void System.Net.Http.HttpConnection.WriteToStream (ReadOnlySpan< byte > source) inline private
Definition at line 2158 of file HttpConnection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"Writing {source.Length} bytes.", "WriteToStream");
        }
        _stream.Write(source);
    }
References System.Net.Http.HttpConnection._stream, System.Net.NetEventSource.Log, System.source, System.Net.Http.HttpConnection.Trace(), and System.IO.Stream.Write().
Referenced by System.Net.Http.HttpConnection.Flush(), System.Net.Http.HttpConnection.Write(), and System.Net.Http.HttpConnection.WriteWithoutBuffering().