Terraria: System.Net.Http.HttpConnection.WriteBytesSlowAsync
WriteBytesSlowAsync()
async Task System.Net.Http.HttpConnection.WriteBytesSlowAsync (byte[] bytes, int length, bool async) inline private
Definition at line 2038 of file HttpConnection.cs.
    {
        int offset = 0;
        while (true)
        {
            int val = length - offset;
            int num = Math.Min(val, _writeBuffer.Length - _writeOffset);
            Buffer.BlockCopy(bytes, offset, _writeBuffer, _writeOffset, num);
            _writeOffset += num;
            offset += num;
            if (offset != length)
            {
                if (_writeOffset == _writeBuffer.Length)
                {
                    await WriteToStreamAsync(_writeBuffer, async).ConfigureAwait(continueOnCapturedContext: false);
                    _writeOffset = 0;
                }
                continue;
            }
            break;
        }
    }
References System.Net.Http.HttpConnection._writeBuffer, System.Net.Http.HttpConnection._writeOffset, System.Buffer.BlockCopy(), System.bytes, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.length, System.Math.Min(), System.offset, and System.Net.Http.HttpConnection.WriteToStreamAsync().
Referenced by System.Net.Http.HttpConnection.WriteBytesAsync(), and System.Net.Http.HttpConnection.WriteStringWithEncodingAsyncSlow().