Terraria: System.Net.Http.HttpConnection.Trace
Trace()
override void System.Net.Http.HttpConnection.Trace (string message, [CallerMemberName] string memberName = null) inline sealed
Implements System.Net.Http.IHttpTrace.
Definition at line 2626 of file HttpConnection.cs.
    {
        System.Net.NetEventSource.Log.HandlerMessage(_pool?.GetHashCode() ?? 0, GetHashCode(), _currentRequest?.GetHashCode() ?? 0, memberName, message);
    }
References System.Net.Http.HttpConnection._currentRequest, System.Net.Http.HttpConnection._pool, and System.Net.NetEventSource.Log.
Referenced by System.Net.Http.HttpConnection.CompleteResponse(), System.Net.Http.HttpConnection.CopyFromBufferAsync(), System.Net.Http.HttpConnection.Dispose(), System.Net.Http.HttpConnection.HttpContentReadStream.DrainOnDisposeAsync(), System.Net.Http.HttpConnection.FillAsync(), System.Net.Http.HttpConnection.InitialFillAsync(), System.Net.Http.HttpConnection.ParseHeaderNameValue(), System.Net.Http.HttpConnection.PrepareForReuse(), System.Net.Http.HttpConnection.Read(), System.Net.Http.HttpConnection.ReadAsync(), System.Net.Http.HttpConnection.ReadBuffered(), System.Net.Http.HttpConnection.ReadBufferedAsyncCore(), System.Net.Http.HttpConnection.ReturnConnectionToPool(), System.Net.Http.HttpConnectionPool.ReturnHttp11Connection(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.Http.HttpConnection.SendRequestContentAsync(), System.Net.Http.HttpConnection.SendRequestContentWithExpect100ContinueAsync(), System.Net.Http.HttpConnection.WriteToStream(), and System.Net.Http.HttpConnection.WriteToStreamAsync().