Terraria: System.Net.Http.HttpConnection.WriteHexInt32Async
WriteHexInt32Async()
Task System.Net.Http.HttpConnection.WriteHexInt32Async (int value, bool async) inline private
Definition at line 1349 of file HttpConnection.cs.
    {
        if (Utf8Formatter.TryFormat(value, new Span<byte>(_writeBuffer, _writeOffset, _writeBuffer.Length - _writeOffset), out var bytesWritten, 'X'))
        {
            _writeOffset += bytesWritten;
            return Task.CompletedTask;
        }
        return WriteAsciiStringAsync(value.ToString("X", CultureInfo.InvariantCulture), async);
    }
References System.Net.Http.HttpConnection._writeBuffer, System.Net.Http.HttpConnection._writeOffset, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Globalization.CultureInfo.InvariantCulture, System.Buffers.Text.Utf8Formatter.TryFormat(), System.value, and System.Net.Http.HttpConnection.WriteAsciiStringAsync().
Referenced by System.Net.Http.HttpConnection.ChunkedEncodingWriteStream.WriteAsync().