Terraria: System.Net.Http.HttpConnection.CopyToUntilEofAsync
CopyToUntilEofAsync()
Task System.Net.Http.HttpConnection.CopyToUntilEofAsync (Stream destination, bool async, int bufferSize, CancellationToken cancellationToken) inline private
Definition at line 2449 of file HttpConnection.cs.
    {
        int num = _readLength - _readOffset;
        if (num > 0)
        {
            return CopyToUntilEofWithExistingBufferedDataAsync(destination, async, bufferSize, cancellationToken);
        }
        if (async)
        {
            return _stream.CopyToAsync(destination, bufferSize, cancellationToken);
        }
        _stream.CopyTo(destination, bufferSize);
        return Task.CompletedTask;
    }
References System.Net.Http.HttpConnection._readLength, System.Net.Http.HttpConnection._readOffset, System.Net.Http.HttpConnection._stream, System.cancellationToken, System.Threading.Tasks.Task< TResult >.CompletedTask, System.IO.Stream.CopyTo(), System.IO.Stream.CopyToAsync(), System.Net.Http.HttpConnection.CopyToUntilEofWithExistingBufferedDataAsync(), and System.destination.
Referenced by System.Net.Http.HttpConnection.ConnectionCloseReadStream.CopyToAsync(), and System.Net.Http.HttpConnection.RawConnectionStream.CopyToAsync().