Terraria: System.Net.Http.HttpConnection.WriteHeadersAsync
WriteHeadersAsync()
async ValueTask System.Net.Http.HttpConnection.WriteHeadersAsync (HttpHeaders headers, string cookiesFromContainer, bool async) inline private
Definition at line 1257 of file HttpConnection.cs.
    {
        if (headers.HeaderStore != null)
        {
            foreach (KeyValuePair<HeaderDescriptor, object> header in headers.HeaderStore)
            {
                if (header.Key.KnownHeader == null)
                {
                    await WriteAsciiStringAsync(header.Key.Name, async).ConfigureAwait(continueOnCapturedContext: false);
                    await WriteTwoBytesAsync(58, 32, async).ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    await WriteBytesAsync(header.Key.KnownHeader.AsciiBytesWithColonSpace, async).ConfigureAwait(continueOnCapturedContext: false);
                }
                int headerValuesCount = HttpHeaders.GetStoreValuesIntoStringArray(header.Key, header.Value, ref _headerValues);
                if (headerValuesCount > 0)
                {
                    Encoding valueEncoding = _pool.Settings._requestHeaderEncodingSelector?.Invoke(header.Key.Name, _currentRequest);
                    await WriteStringAsync(_headerValues[0], async, valueEncoding).ConfigureAwait(continueOnCapturedContext: false);
                    if (cookiesFromContainer != null && header.Key.KnownHeader == KnownHeaders.Cookie)
                    {
                        await WriteTwoBytesAsync(59, 32, async).ConfigureAwait(continueOnCapturedContext: false);
                        await WriteStringAsync(cookiesFromContainer, async, valueEncoding).ConfigureAwait(continueOnCapturedContext: false);
                        cookiesFromContainer = null;
                    }
                    if (headerValuesCount > 1)
                    {
                        HttpHeaderParser parser = header.Key.Parser;
                        string separator = ", ";
                        if (parser != null && parser.SupportsMultipleValues)
{
                            separator = parser.Separator;
                        }
                        for (int i = 1; i < headerValuesCount; i++)
{
                            await WriteAsciiStringAsync(separator, async).ConfigureAwait(continueOnCapturedContext: false);
                            await WriteStringAsync(_headerValues[i], async, valueEncoding).ConfigureAwait(continueOnCapturedContext: false);
                        }
                    }
                }
                await WriteTwoBytesAsync(13, 10, async).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        if (cookiesFromContainer != null)
        {
            await WriteAsciiStringAsync("Cookie", async).ConfigureAwait(continueOnCapturedContext: false);
            await WriteTwoBytesAsync(58, 32, async).ConfigureAwait(continueOnCapturedContext: false);
            Encoding encoding = _pool.Settings._requestHeaderEncodingSelector?.Invoke("Cookie", _currentRequest);
            await WriteStringAsync(cookiesFromContainer, async, encoding).ConfigureAwait(continueOnCapturedContext: false);
            await WriteTwoBytesAsync(13, 10, async).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Net.Http.HttpConnection._currentRequest, System.Net.Http.HttpConnection._headerValues, System.Net.Http.HttpConnection._pool, System.Net.Http.HttpConnectionSettings._requestHeaderEncodingSelector, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.Headers.KnownHeaders.Cookie, System.Net.Http.Headers.HttpHeaders.GetStoreValuesIntoStringArray(), System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.HttpConnection.WriteAsciiStringAsync(), System.Net.Http.HttpConnection.WriteBytesAsync(), System.Net.Http.HttpConnection.WriteStringAsync(), and System.Net.Http.HttpConnection.WriteTwoBytesAsync().
Referenced by System.Net.Http.HttpConnection.SendAsyncCore().