Terraria: System.Net.Http.HttpConnection.WriteHostHeaderAsync
WriteHostHeaderAsync()
async ValueTask System.Net.Http.HttpConnection.WriteHostHeaderAsync (Uri uri, bool async) inline private
Definition at line 1311 of file HttpConnection.cs.
    {
        await WriteBytesAsync(KnownHeaders.Host.AsciiBytesWithColonSpace, async).ConfigureAwait(continueOnCapturedContext: false);
        if (_pool.HostHeaderValueBytes != null)
        {
            await WriteBytesAsync(_pool.HostHeaderValueBytes, async).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            if (uri.HostNameType != UriHostNameType.IPv6)
            {
                await WriteAsciiStringAsync(uri.IdnHost, async).ConfigureAwait(continueOnCapturedContext: false);
            }
            else
            {
                await WriteByteAsync(91, async).ConfigureAwait(continueOnCapturedContext: false);
                await WriteAsciiStringAsync(uri.IdnHost, async).ConfigureAwait(continueOnCapturedContext: false);
                await WriteByteAsync(93, async).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (!uri.IsDefaultPort)
            {
                await WriteByteAsync(58, async).ConfigureAwait(continueOnCapturedContext: false);
                await WriteDecimalInt32Async(uri.Port, async).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        await WriteTwoBytesAsync(13, 10, async).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Net.Http.HttpConnection._pool, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.Headers.KnownHeaders.Host, System.Net.Http.HttpConnectionPool.HostHeaderValueBytes, System.Uri.HostNameType, System.Uri.IdnHost, System.Uri.IsDefaultPort, System.Uri.Port, System.Net.Http.HttpConnection.WriteAsciiStringAsync(), System.Net.Http.HttpConnection.WriteByteAsync(), System.Net.Http.HttpConnection.WriteBytesAsync(), System.Net.Http.HttpConnection.WriteDecimalInt32Async(), and System.Net.Http.HttpConnection.WriteTwoBytesAsync().
Referenced by System.Net.Http.HttpConnection.SendAsyncCore().