Terraria: System.Net.Http.HttpConnection.ReadBufferedAsync
ReadBufferedAsync()
ValueTask< int > System.Net.Http.HttpConnection.ReadBufferedAsync (Memory< byte > destination) inline private
Definition at line 2398 of file HttpConnection.cs.
    {
        if (destination.Length < _readBuffer.Length)
        {
            return ReadBufferedAsyncCore(destination);
        }
        return ReadAsync(destination);
    }
References System.Net.Http.HttpConnection._readBuffer, System.destination, System.Net.Http.HttpConnection.ReadAsync(), and System.Net.Http.HttpConnection.ReadBufferedAsyncCore().
Referenced by System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync().