Terraria: System.Net.HttpValidationHelpers.CheckBadHeaderNameChars
CheckBadHeaderNameChars()
static string System.Net.HttpValidationHelpers.CheckBadHeaderNameChars (string name) inline static package
Definition at line 7 of file HttpValidationHelpers.cs.
    {
        if (IsInvalidMethodOrHeaderString(name))
        {
            throw new ArgumentException(System.SR.net_WebHeaderInvalidHeaderChars, "name");
        }
        if (ContainsNonAsciiChars(name))
        {
            throw new ArgumentException(System.SR.net_WebHeaderInvalidHeaderChars, "name");
        }
        return name;
    }
References System.Net.HttpValidationHelpers.ContainsNonAsciiChars(), System.Net.HttpValidationHelpers.IsInvalidMethodOrHeaderString(), and System.SR.net_WebHeaderInvalidHeaderChars.
Referenced by System.Net.WebHeaderCollection.Add(), System.Net.WebHeaderCollection.Add(), System.Net.WebHeaderCollection.AddWithoutValidate(), System.Net.WebHeaderCollection.IsRestricted(), System.Net.WebHeaderCollection.Remove(), and System.Net.WebHeaderCollection.Set().