Terraria: System.Net.Http.HttpConnection.SendRequestContentWithExpect100ContinueAsync
SendRequestContentWithExpect100ContinueAsync()
async Task System.Net.Http.HttpConnection.SendRequestContentWithExpect100ContinueAsync (HttpRequestMessage request, Task< bool > allowExpect100ToContinueTask, HttpContentWriteStream stream, Timer expect100Timer, bool async, CancellationToken cancellationToken) inline private
Definition at line 1748 of file HttpConnection.cs.
    {
        bool flag = await allowExpect100ToContinueTask.ConfigureAwait(continueOnCapturedContext: false);
        expect100Timer.Dispose();
        if (flag)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("Sending request content for Expect: 100-continue.", "SendRequestContentWithExpect100ContinueAsync");
            }
            try
            {
                await SendRequestContentAsync(request, stream, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                return;
            }
            catch
            {
                Dispose();
                throw;
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("Canceling request content for Expect: 100-continue.", "SendRequestContentWithExpect100ContinueAsync");
        }
    }
References System.cancellationToken, System.Net.Http.HttpConnection.Dispose(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnection.SendRequestContentAsync(), System.stream, and System.Net.Http.HttpConnection.Trace().
Referenced by System.Net.Http.HttpConnection.SendAsyncCore().