Terraria: System.Net.Http.HttpConnection.ReturnConnectionToPool
ReturnConnectionToPool()
void System.Net.Http.HttpConnection.ReturnConnectionToPool () inline private
Definition at line 2588 of file HttpConnection.cs.
    {
        if (_connectionClose)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("Connection will not be reused.", "ReturnConnectionToPool");
            }
            Dispose();
        }
        else
        {
            _idleSinceTickCount = Environment.TickCount64;
            _pool.ReturnHttp11Connection(this);
        }
    }
References System.Net.Http.HttpConnection._connectionClose, System.Net.Http.HttpConnection._idleSinceTickCount, System.Net.Http.HttpConnection._pool, System.Net.Http.HttpConnection.Dispose(), System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionPool.ReturnHttp11Connection(), System.Environment.TickCount64, and System.Net.Http.HttpConnection.Trace().
Referenced by System.Net.Http.HttpConnection.CompleteResponse(), and System.Net.Http.HttpConnection.Release().