Terraria: System.Net.Http.HttpConnection.WriteStringAsyncSlow
WriteStringAsyncSlow()
async Task System.Net.Http.HttpConnection.WriteStringAsyncSlow (string s, bool async) inline private
Definition at line 2126 of file HttpConnection.cs.
    {
        foreach (char c in s)
        {
            if ((c & 0xFF80u) != 0)
            {
                throw new HttpRequestException(System.SR.net_http_request_invalid_char_encoding);
            }
            await WriteByteAsync((byte)c, async).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.SR.net_http_request_invalid_char_encoding, System.s, and System.Net.Http.HttpConnection.WriteByteAsync().
Referenced by System.Net.Http.HttpConnection.WriteAsciiStringAsync(), and System.Net.Http.HttpConnection.WriteStringAsync().