Terraria: System.Net.Http.HttpConnection.WriteTwoBytesAsync
WriteTwoBytesAsync()
Task System.Net.Http.HttpConnection.WriteTwoBytesAsync (byte b1, byte b2, bool async) inline private
Definition at line 2009 of file HttpConnection.cs.
    {
        if (_writeOffset <= _writeBuffer.Length - 2)
        {
            byte[] writeBuffer = _writeBuffer;
            writeBuffer[_writeOffset++] = b1;
            writeBuffer[_writeOffset++] = b2;
            return Task.CompletedTask;
        }
        return WriteTwoBytesSlowAsync(b1, b2, async);
    }
References System.Net.Http.HttpConnection._writeBuffer, System.Net.Http.HttpConnection._writeOffset, System.Threading.Tasks.Task< TResult >.CompletedTask, and System.Net.Http.HttpConnection.WriteTwoBytesSlowAsync().
Referenced by System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.Http.HttpConnection.ChunkedEncodingWriteStream.WriteAsync(), System.Net.Http.HttpConnection.WriteHeadersAsync(), and System.Net.Http.HttpConnection.WriteHostHeaderAsync().