Terraria: System.Net.Http.HttpConnection.Dispose
Dispose() [2/2]
void System.Net.Http.HttpConnection.Dispose (bool disposing) inline private
Definition at line 1156 of file HttpConnection.cs.
    {
        int num = Interlocked.Exchange(ref _disposed, 1);
        if (num == 1)
        {
            return;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("Connection closing.", "Dispose");
        }
        if (HttpTelemetry.Log.IsEnabled() && num == 2)
        {
            HttpTelemetry.Log.Http11ConnectionClosed();
        }
        if (!_detachedFromPool)
        {
            _pool.InvalidateHttp11Connection(this, disposing);
        }
        if (disposing)
        {
            GC.SuppressFinalize(this);
            _stream.Dispose();
            ValueTask<int>? valueTask = ConsumeReadAheadTask();
            if (valueTask.HasValue)
            {
                HttpConnectionBase.IgnoreExceptions(valueTask.GetValueOrDefault());
            }
        }
    }
References System.Net.Http.HttpConnection._detachedFromPool, System.Net.Http.HttpConnection._disposed, System.Net.Http.HttpConnection._pool, System.Net.Http.HttpConnection._stream, System.Net.Http.HttpConnection.ConsumeReadAheadTask(), System.IO.Stream.Dispose(), System.Threading.Interlocked.Exchange(), System.Net.Http.HttpConnectionBase.IgnoreExceptions(), System.Net.Http.HttpConnectionPool.InvalidateHttp11Connection(), System.Net.Http.HttpTelemetry.Log, System.Net.NetEventSource.Log, System.GC.SuppressFinalize(), and System.Net.Http.HttpConnection.Trace().