Terraria: System.ComponentModel.LicFileLicenseProvider.GetLicense
GetLicense()
override? License System.ComponentModel.LicFileLicenseProvider.GetLicense (LicenseContext context, Type type, object? instance, bool allowExceptions) inline
Definition at line 39 of file LicFileLicenseProvider.cs.
    {
        LicFileLicense licFileLicense = null;
        if (context != null)
        {
            if (context.UsageMode == LicenseUsageMode.Runtime)
            {
                string savedLicenseKey = context.GetSavedLicenseKey(type, null);
                if (savedLicenseKey != null && IsKeyValid(savedLicenseKey, type))
                {
                    licFileLicense = new LicFileLicense(this, savedLicenseKey);
                }
            }
            if (licFileLicense == null)
            {
                string text = null;
                if (context != null)
                {
                    ITypeResolutionService typeResolutionService = (ITypeResolutionService)context.GetService(typeof(ITypeResolutionService));
                    if (typeResolutionService != null)
                    {
                        text = typeResolutionService.GetPathOfAssembly(type.Assembly.GetName());
                    }
                }
                if (type.Assembly.Location.Length != 0)
                {
                    if (text == null)
                    {
                        text = type.Module.FullyQualifiedName;
                    }
                    string directoryName = Path.GetDirectoryName(text);
                    string path = directoryName + "\\" + type.FullName + ".lic";
                    if (File.Exists(path))
                    {
                        Stream stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
                        StreamReader streamReader = new StreamReader(stream);
                        string key = streamReader.ReadLine();
                        streamReader.Close();
                        if (IsKeyValid(key, type))
{
                            licFileLicense = new LicFileLicense(this, GetKey(type));
                        }
                    }
                    if (licFileLicense != null)
                    {
                        context.SetSavedLicenseKey(type, licFileLicense.LicenseKey);
                    }
                }
            }
        }
        return licFileLicense;
    }
References System.IO.StreamReader.Close(), System.IO.File.Exists(), System.IO.Path.GetDirectoryName(), System.ComponentModel.LicFileLicenseProvider.GetKey(), System.ComponentModel.Design.ITypeResolutionService.GetPathOfAssembly(), System.ComponentModel.LicenseContext.GetSavedLicenseKey(), System.ComponentModel.LicenseContext.GetService(), System.ComponentModel.LicFileLicenseProvider.IsKeyValid(), System.key, System.ComponentModel.LicFileLicenseProvider.LicFileLicense.LicenseKey, System.IO.StreamReader.ReadLine(), System.ComponentModel.LicenseContext.SetSavedLicenseKey(), System.stream, System.text, System.type, and System.ComponentModel.LicenseContext.UsageMode.