Terraria: System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.FindFieldMarshalRowId
FindFieldMarshalRowId()
int System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.FindFieldMarshalRowId (EntityHandle handle) inline package
Definition at line 48 of file FieldMarshalTableReader.cs.
    {
        int num = Block.BinarySearchReference(NumberOfRows, RowSize, _ParentOffset, HasFieldMarshalTag.ConvertToTag(handle), _IsHasFieldMarshalRefSizeSmall);
        return num + 1;
    }
References System.Reflection.Metadata.Ecma335.FieldMarshalTableReader._IsHasFieldMarshalRefSizeSmall, System.Reflection.Metadata.Ecma335.FieldMarshalTableReader._ParentOffset, System.Reflection.Internal.MemoryBlock.BinarySearchReference(), System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.Block, System.Reflection.Metadata.Ecma335.HasFieldMarshalTag.ConvertToTag(), System.handle, System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.NumberOfRows, and System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.RowSize.
Referenced by System.Reflection.Metadata.FieldDefinition.GetMarshallingDescriptor().