Terraria: FilterManager.EndCapture
EndCapture()
void FilterManager.EndCapture (RenderTarget2D finalTexture, RenderTarget2D screenTarget1, RenderTarget2D screenTarget2, Color clearColor) inline
     {
         if (!_captureThisFrame)
         {
             return;
         }
         LinkedListNode<Filter> linkedListNode = _activeFilters.First;
         _ = _activeFilters.Count;
         Filter filter = null;
         RenderTarget2D renderTarget2D = null;
         RenderTarget2D renderTarget2D2 = screenTarget1;
         GraphicsDevice graphicsDevice = Main.instance.GraphicsDevice;
         int num = 0;
         if (Main.player[Main.myPlayer].gravDir == -1f)
         {
             renderTarget2D = screenTarget2;
             graphicsDevice.SetRenderTarget(renderTarget2D);
             graphicsDevice.Clear(clearColor);
             Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Matrix.Invert(Main.GameViewMatrix.EffectMatrix));
             Main.spriteBatch.Draw(renderTarget2D2, Vector2.Zero, Color.White);
             Main.spriteBatch.End();
             renderTarget2D2 = screenTarget2;
         }
         while (linkedListNode != null)
         {
             Filter value = linkedListNode.Value;
             LinkedListNode<Filter> next = linkedListNode.Next;
             if (value.Priority >= _priorityThreshold)
             {
                 num++;
                 if (num > _activeFilterCount - _filterLimit && value.IsVisible())
                 {
                     if (filter != null)
                     {
                         renderTarget2D = ((renderTarget2D2 != screenTarget1) ? screenTarget1 : screenTarget2);
                         graphicsDevice.SetRenderTarget(renderTarget2D);
                         graphicsDevice.Clear(clearColor);
                         Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
                         filter.Apply();
                         Main.spriteBatch.Draw(renderTarget2D2, Vector2.Zero, Main.ColorOfTheSkies);
                         Main.spriteBatch.End();
                         renderTarget2D2 = ((renderTarget2D2 != screenTarget1) ? screenTarget1 : screenTarget2);
                     }
                     filter = value;
                 }
             }
             linkedListNode = next;
         }
         graphicsDevice.SetRenderTarget(finalTexture);
         graphicsDevice.Clear(clearColor);
         if (Main.player[Main.myPlayer].gravDir == -1f)
         {
             Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Main.GameViewMatrix.EffectMatrix);
         }
         else
         {
             Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
         }
         if (filter != null)
         {
             filter.Apply();
             Main.spriteBatch.Draw(renderTarget2D2, Vector2.Zero, Main.ColorOfTheSkies);
         }
         else
         {
             Main.spriteBatch.Draw(renderTarget2D2, Vector2.Zero, Color.White);
         }
         Main.spriteBatch.End();
         for (int i = 0; i < 8; i++)
         {
             graphicsDevice.Textures[i] = null;
         }
         if (this.OnPostDraw != null)
         {
             this.OnPostDraw();
         }
     }
References _activeFilterCount, _activeFilters, _captureThisFrame, _filterLimit, _priorityThreshold, Filter.Apply(), Color, Main.ColorOfTheSkies, SpriteViewMatrix.EffectMatrix, Main.GameViewMatrix, Game.GraphicsDevice, Player.gravDir, Main.instance, Filter.IsVisible(), Main.myPlayer, OnPostDraw, Main.player, GameEffect.Priority, and Main.spriteBatch.
Referenced by CaptureCamera.DrawTick().