Terraria: VoidLensHelper.DrawToDrawData
DrawToDrawData()
void VoidLensHelper.DrawToDrawData (List< DrawData > drawDataList, int selectionMode) inline
     {
         Main.instance.LoadProjectile(734);
         Asset<Texture2D> val = TextureAssets.Projectile[734];
         Rectangle rectangle = val.Frame(1, 8, 0, _frameNumber);
         Color color = Lighting.GetColor(_position.ToTileCoordinates());
         color = Color.Lerp(color, Color.White, 0.5f);
         color *= _opacity;
         DrawData drawData = new DrawData(val.Value, _position - Main.screenPosition, rectangle, color, 0f, rectangle.Size() / 2f, 1f, SpriteEffects.None);
         drawDataList.Add(drawData);
         for (float num = 0f; num < 1f; num += 0.34f)
         {
             DrawData item = drawData;
             item.color = new Color(127, 50, 127, 0) * _opacity;
             item.scale *= 1.1f;
             float x = (Main.GlobalTimeWrappedHourly / 5f * ((float)Math.PI * 2f)).ToRotationVector2().X;
             item.color *= x * 0.1f + 0.3f;
             item.position += ((Main.GlobalTimeWrappedHourly / 5f + num) * ((float)Math.PI * 2f)).ToRotationVector2() * (x * 1f + 2f);
             drawDataList.Add(item);
         }
         if (selectionMode != 0)
         {
             int num2 = (color.R + color.G + color.B) / 3;
             if (num2 > 10)
             {
                 Color selectionGlowColor = Colors.GetSelectionGlowColor(selectionMode == 2, num2);
                 drawData = new DrawData(TextureAssets.Extra[93].Value, _position - Main.screenPosition, rectangle, selectionGlowColor, 0f, rectangle.Size() / 2f, 1f, SpriteEffects.None);
                 drawDataList.Add(drawData);
             }
         }
     }
References _frameNumber, _opacity, _position, DrawData.color, Color, TextureAssets.Extra, Lighting.GetColor(), Colors.GetSelectionGlowColor(), Main.GlobalTimeWrappedHourly, Main.instance, Main.LoadProjectile(), DrawData.position, TextureAssets.Projectile, DrawData.scale, Main.screenPosition, and Asset< T >.Value.
Referenced by Main.DrawProjDirect(), and TileDrawing.DrawVoidLenses().