Terraria: Internal.Cryptography.HashProviderDispenser.OneShotHashProvider.HashData
HashData()
static int Internal.Cryptography.HashProviderDispenser.OneShotHashProvider.HashData (string hashAlgorithmId, ReadOnlySpan< byte > source, Span< byte > destination) inline static
Definition at line 29 of file HashProviderDispenser.cs.
        {
            int hashSizeInBytes;
            if (global::Interop.BCrypt.PseudoHandlesSupported)
            {
                HashDataUsingPseudoHandle(hashAlgorithmId, source, default(ReadOnlySpan<byte>), isHmac: false, destination, out hashSizeInBytes);
                return hashSizeInBytes;
            }
            SafeBCryptAlgorithmHandle cachedBCryptAlgorithmHandle = global::Interop.BCrypt.BCryptAlgorithmCache.GetCachedBCryptAlgorithmHandle(hashAlgorithmId, global::Interop.BCrypt.BCryptOpenAlgorithmProviderFlags.None, out hashSizeInBytes);
            if (destination.Length < hashSizeInBytes)
            {
                throw new CryptographicException();
            }
            HashUpdateAndFinish(cachedBCryptAlgorithmHandle, hashSizeInBytes, default(ReadOnlySpan<byte>), source, destination);
            return hashSizeInBytes;
        }
References System.destination, Internal.Cryptography.HashProviderDispenser.OneShotHashProvider.HashDataUsingPseudoHandle(), Internal.Cryptography.HashProviderDispenser.OneShotHashProvider.HashUpdateAndFinish(), and System.source.
Referenced by System.Security.Cryptography.MD5.TryHashData(), System.Security.Cryptography.SHA1.TryHashData(), System.Security.Cryptography.SHA256.TryHashData(), System.Security.Cryptography.SHA384.TryHashData(), and System.Security.Cryptography.SHA512.TryHashData().