Terraria: ReLogic.Content.Sources.XnaDirectContentSource.OpenStream
OpenStream()
override Stream ReLogic.Content.Sources.XnaDirectContentSource.OpenStream (string fullAssetName) inline
Must be threadsafe!
Implements ReLogic.Content.Sources.IContentSource.
Definition at line 19 of file XnaDirectContentSource.cs.
    {
        try
        {
            return File.OpenRead(_rootDirectories.Select((string rootDir) => Path.Combine(rootDir, assetName)).First(File.Exists));
        }
        catch (Exception innerException)
        {
            throw AssetLoadException.FromMissingAsset(assetName, innerException);
        }
    }
References ReLogic.Content.Sources.XnaDirectContentSource._rootDirectories, System.IO.Path.Combine(), System.IO.File.Exists(), ReLogic.Content.AssetLoadException.FromMissingAsset(), and System.IO.File.OpenRead().