Terraria: System.Runtime.InteropServices.ComEventsSink.Invoke
Invoke()
unsafe void IDispatch. System.Runtime.InteropServices.ComEventsSink.Invoke (int dispid, ref Guid riid, int lcid, InvokeFlags wFlags, ref DISPPARAMS pDispParams, IntPtr pVarResult, IntPtr pExcepInfo, IntPtr puArgErr) inline private
Implements System.Runtime.InteropServices.IDispatch.
Definition at line 120 of file ComEventsSink.cs.
    {
        ComEventsMethod comEventsMethod = FindMethod(dispid);
        if (comEventsMethod == null)
        {
            return;
        }
        object[] array = new object[pDispParams.cArgs];
        int[] array2 = new int[pDispParams.cArgs];
        bool[] array3 = new bool[pDispParams.cArgs];
        int length = pDispParams.cNamedArgs + pDispParams.cArgs;
        Span<Variant> span = new Span<Variant>(pDispParams.rgvarg.ToPointer(), length);
        Span<int> span2 = new Span<int>(pDispParams.rgdispidNamedArgs.ToPointer(), length);
        int num;
        int i;
        for (i = 0; i < pDispParams.cNamedArgs; i++)
        {
            num = span2[i];
            ref Variant variant = ref GetVariant(ref span[i]);
            array[num] = variant.ToObject();
            array3[num] = true;
            int num2 = -1;
            if (variant.IsByRef)
            {
                num2 = i;
            }
            array2[num] = num2;
        }
        num = 0;
        for (; i < pDispParams.cArgs; i++)
        {
            for (; array3[num]; num++)
            {
            }
            ref Variant variant2 = ref GetVariant(ref span[pDispParams.cArgs - 1 - i]);
            array[num] = variant2.ToObject();
            int num3 = -1;
            if (variant2.IsByRef)
            {
                num3 = pDispParams.cArgs - 1 - i;
            }
            array2[num] = num3;
            num++;
        }
        object obj = comEventsMethod.Invoke(array);
        if (pVarResult != IntPtr.Zero)
        {
            Marshal.GetNativeVariantForObject(obj, pVarResult);
        }
        for (i = 0; i < pDispParams.cArgs; i++)
        {
            int num4 = array2[i];
            if (num4 != -1)
            {
                GetVariant(ref span[num4]).CopyFromIndirect(array[i]);
            }
        }
    }
References System.array, System.Runtime.InteropServices.ComEventsSink.FindMethod(), System.Runtime.InteropServices.Marshal.GetNativeVariantForObject(), System.Runtime.InteropServices.ComEventsSink.GetVariant(), System.Runtime.InteropServices.ComEventsMethod.Invoke(), System.length, System.obj, and System.IntPtr.Zero.