Terraria: MS.Internal.Xml.XPath.NumericExpr.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.NumericExpr.Evaluate (XPathNodeIterator nodeIterator) inline
Definition at line 46 of file NumericExpr.cs.
    {
        return GetValue(_op, XmlConvert.ToXPathDouble(_opnd1.Evaluate(nodeIterator)), XmlConvert.ToXPathDouble(_opnd2.Evaluate(nodeIterator)));
    }
References MS.Internal.Xml.XPath.NumericExpr._op, MS.Internal.Xml.XPath.NumericExpr._opnd1, MS.Internal.Xml.XPath.NumericExpr._opnd2, System.Xml.Dictionary, MS.Internal.Xml.XPath.Query.Evaluate(), MS.Internal.Xml.XPath.NumericExpr.GetValue(), and System.Xml.XmlConvert.ToXPathDouble().