Terraria: System.ComponentModel.BackgroundWorker.WorkerThreadStart
WorkerThreadStart()
void System.ComponentModel.BackgroundWorker.WorkerThreadStart (object argument) inline private
Definition at line 140 of file BackgroundWorker.cs.
    {
        object result = null;
        Exception error = null;
        bool cancelled = false;
        try
        {
            DoWorkEventArgs doWorkEventArgs = new DoWorkEventArgs(argument);
            OnDoWork(doWorkEventArgs);
            if (doWorkEventArgs.Cancel)
            {
                cancelled = true;
            }
            else
            {
                result = doWorkEventArgs.Result;
            }
        }
        catch (Exception ex)
        {
            error = ex;
        }
        RunWorkerCompletedEventArgs arg = new RunWorkerCompletedEventArgs(result, error, cancelled);
        _asyncOperation.PostOperationCompleted(_operationCompleted, arg);
    }
References System.ComponentModel.BackgroundWorker._asyncOperation, System.ComponentModel.BackgroundWorker._operationCompleted, System.ComponentModel.CancelEventArgs.Cancel, System.ComponentModel.BackgroundWorker.OnDoWork(), System.ComponentModel.AsyncOperation.PostOperationCompleted(), and System.ComponentModel.DoWorkEventArgs.Result.
Referenced by System.ComponentModel.BackgroundWorker.RunWorkerAsync().