Terraria: SayChatCommand.ProcessIncomingMessage
ProcessIncomingMessage()
void SayChatCommand.ProcessIncomingMessage (string text, byte clientId) inline
Implements IChatCommand.
     {
         ChatHelper.BroadcastChatMessageAs(clientId, NetworkText.FromLiteral(text), Main.player[clientId].ChatColor());
         if (Main.dedServ)
         {
             Console.WriteLine("<{0}> {1}", Main.player[clientId].name, text);
         }
     }
References ChatHelper.BroadcastChatMessageAs(), Player.ChatColor(), Main.dedServ, NetworkText.FromLiteral(), Player.name, and Main.player.