Terraria: Terraria.GameContent.UI.Elements.UIImage.SetImage
SetImage() [1/2]
void Terraria.GameContent.UI.Elements.UIImage.SetImage (Asset< Texture2D > texture) inline inherited
Definition at line 38 of file UIImage.cs.
    {
        _texture = texture;
        _nonReloadingTexture = null;
        if (AllowResizingDimensions)
        {
            Width.Set(_texture.Width(), 0f);
            Height.Set(_texture.Height(), 0f);
        }
    }
References Terraria.GameContent.UI.Elements.UIImage._nonReloadingTexture, Terraria.GameContent.UI.Elements.UIImage._texture, Terraria.GameContent.UI.Elements.UIImage.AllowResizingDimensions, Terraria.UI.UIElement.Height, Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UIImage.UIImage(), Terraria.GameContent.UI.Elements.UIImage.UIImage(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview().