Terraria: System.ComponentModel.Design.IComponentChangeService.OnComponentChanged
OnComponentChanged()
void System.ComponentModel.Design.IComponentChangeService.OnComponentChanged (object component, MemberDescriptor? member, object? oldValue, object? newValue)
Referenced by System.ComponentModel.ReflectEventDescriptor.AddEventHandler(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderResetValue(), System.ComponentModel.ReflectPropertyDescriptor.ExtenderSetValue(), System.ComponentModel.ReflectEventDescriptor.RemoveEventHandler(), System.ComponentModel.ReflectPropertyDescriptor.ResetValue(), and System.ComponentModel.ReflectPropertyDescriptor.SetValue().