Terraria: Terraria.Social.WeGame.NetClientSocialModule.SendFriendListToLocalServer
SendFriendListToLocalServer()
bool Terraria.Social.WeGame.NetClientSocialModule.SendFriendListToLocalServer () inline private
    {
        bool result = false;
        if (_hasLocalHost)
        {
            List<RailFriendInfo> list = new List<RailFriendInfo>();
            if (GetRailFriendList(list))
            {
                WeGameFriendListInfo t = new WeGameFriendListInfo
                {
                    _friendList = list
                };
                IPCMessage iPCMessage = new IPCMessage();
                iPCMessage.Build(IPCMessageType.IPCMessageTypeNotifyFriendList, t);
                result = _msgServer.SendMessage(iPCMessage);
                WeGameHelper.WriteDebugString("NotifyFriendListToServer: " + result);
            }
        }
        return result;
    }
References Terraria.Social.WeGame.NetClientSocialModule._hasLocalHost, Terraria.Social.WeGame.NetClientSocialModule._msgServer, Terraria.Social.WeGame.NetClientSocialModule.GetRailFriendList(), Terraria.Social.WeGame.MessageDispatcherServer.SendMessage(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.OnFriendlistChange(), and Terraria.Social.WeGame.NetClientSocialModule.OnIPCClientAccess().