Terraria: Terraria.GameContent.UI.States.UIWorldCreation.FinishCreatingWorld
FinishCreatingWorld()
void Terraria.GameContent.UI.States.UIWorldCreation.FinishCreatingWorld () inline private
Definition at line 660 of file UIWorldCreation.cs.
    {
        ProcessSeed(out var processedSeed);
        switch (_optionSize)
        {
        case WorldSizeId.Small:
            Main.maxTilesX = 4200;
            Main.maxTilesY = 1200;
            break;
        case WorldSizeId.Medium:
            Main.maxTilesX = 6400;
            Main.maxTilesY = 1800;
            break;
        case WorldSizeId.Large:
            Main.maxTilesX = 8400;
            Main.maxTilesY = 2400;
            break;
        }
        WorldGen.setWorldSize();
        switch (_optionDifficulty)
        {
        case WorldDifficultyId.Creative:
            Main.GameMode = 3;
            break;
        case WorldDifficultyId.Normal:
            Main.GameMode = 0;
            break;
        case WorldDifficultyId.Expert:
            Main.GameMode = 1;
            break;
        case WorldDifficultyId.Master:
            Main.GameMode = 2;
            break;
        }
        switch (_optionEvil)
        {
        case WorldEvilId.Random:
            WorldGen.WorldGenParam_Evil = -1;
            break;
        case WorldEvilId.Corruption:
            WorldGen.WorldGenParam_Evil = 0;
            break;
        case WorldEvilId.Crimson:
            WorldGen.WorldGenParam_Evil = 1;
            break;
        }
        Main.ActiveWorldFileData = WorldFile.CreateMetadata(Main.worldName = _optionwWorldName.Trim(), SocialAPI.Cloud != null && SocialAPI.Cloud.EnabledByDefault, Main.GameMode);
        if (processedSeed.Length == 0)
        {
            Main.ActiveWorldFileData.SetSeedToRandom();
        }
        else
        {
            Main.ActiveWorldFileData.SetSeed(processedSeed);
        }
        Main.menuMode = 10;
        WorldGen.CreateNewWorld();
    }
References Terraria.GameContent.UI.States.UIWorldCreation._optionDifficulty, Terraria.GameContent.UI.States.UIWorldCreation._optionEvil, Terraria.GameContent.UI.States.UIWorldCreation._optionSize, Terraria.GameContent.UI.States.UIWorldCreation._optionwWorldName, Terraria.Main.ActiveWorldFileData, Terraria.Social.SocialAPI.Cloud, Terraria.IO.WorldFile.CreateMetadata(), Terraria.WorldGen.CreateNewWorld(), Terraria.Main.GameMode, Terraria.GameContent.UI.States.UIWorldCreation.ProcessSeed(), Terraria.WorldGen.setWorldSize(), and Terraria.Main.worldName.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.Click_NamingAndCreating(), and Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedNamingAndCreating().