Terraria: Terraria.Social.WeGame.NetClientSocialModule.CheckParameters
CheckParameters()
void Terraria.Social.WeGame.NetClientSocialModule.CheckParameters () inline private
Definition at line 178 of file NetClientSocialModule.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Expected O, but got Unknown
        RailID server_id = new RailID();
        if (!GetRailConnectIDFromCmdLine(server_id))
        {
            return;
        }
        if (((RailComparableID)server_id).IsValid())
        {
            Main.OpenPlayerSelect(delegate(PlayerFileData playerData)
            {
                Main.ServerSideCharacter = false;
                playerData.SetAsActive();
                Main.menuMode = 882;
                Main.statusText = Language.GetTextValue("Social.Joining");
                WeGameHelper.WriteDebugString(" CheckParameters， lobby.join");
                JoinServer(server_id);
            });
        }
        else
        {
            WeGameHelper.WriteDebugString("Invalid RailID passed to +connect_lobby");
        }
    }
References Terraria.Social.WeGame.NetClientSocialModule.GetRailConnectIDFromCmdLine(), Terraria.Localization.Language.GetTextValue(), Terraria.Social.WeGame.NetClientSocialModule.JoinServer(), Terraria.Main.OpenPlayerSelect(), Terraria.IO.PlayerFileData.SetAsActive(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.Initialize().