Terraria: Terraria.GameContent.UI.States.UIWorldCreation.MakeBackAndCreatebuttons
MakeBackAndCreatebuttons()
void Terraria.GameContent.UI.States.UIWorldCreation.MakeBackAndCreatebuttons (UIElement outerContainer) inline private
Definition at line 535 of file UIWorldCreation.cs.
    {
        UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true)
        {
            Width = StyleDimension.FromPixelsAndPercent(-10f, 0.5f),
            Height = StyleDimension.FromPixels(50f),
            VAlign = 1f,
            HAlign = 0f,
            Top = StyleDimension.FromPixels(-45f)
        };
        uITextPanel.OnMouseOver += FadedMouseOver;
        uITextPanel.OnMouseOut += FadedMouseOut;
        uITextPanel.OnLeftMouseDown += Click_GoBack;
        uITextPanel.SetSnapPoint("Back", 0);
        outerContainer.Append(uITextPanel);
        UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Create"), 0.7f, large: true)
        {
            Width = StyleDimension.FromPixelsAndPercent(-10f, 0.5f),
            Height = StyleDimension.FromPixels(50f),
            VAlign = 1f,
            HAlign = 1f,
            Top = StyleDimension.FromPixels(-45f)
        };
        uITextPanel2.OnMouseOver += FadedMouseOver;
        uITextPanel2.OnMouseOut += FadedMouseOut;
        uITextPanel2.OnLeftMouseDown += Click_NamingAndCreating;
        uITextPanel2.SetSnapPoint("Create", 0);
        outerContainer.Append(uITextPanel2);
    }
References Terraria.GameContent.UI.States.UIWorldCreation.Click_GoBack(), Terraria.GameContent.UI.States.UIWorldCreation.Click_NamingAndCreating(), Terraria.GameContent.UI.States.UIWorldCreation.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorldCreation.FadedMouseOver(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.BuildPage().