Terraria: Terraria.GameContent.UI.States.UIWorldCreation.EstablishUpDownRelationship
EstablishUpDownRelationship()
void Terraria.GameContent.UI.States.UIWorldCreation.EstablishUpDownRelationship (UILinkPoint[] topSide, UILinkPoint[] bottomSide) inline private
Definition at line 995 of file UIWorldCreation.cs.
    {
        int num = Math.Max(topSide.Length, bottomSide.Length);
        for (int i = 0; i < num; i++)
        {
            int num2 = Math.Min(i, topSide.Length - 1);
            int num3 = Math.Min(i, bottomSide.Length - 1);
            topSide[num2].Down = bottomSide[num3].ID;
            bottomSide[num3].Up = topSide[num2].ID;
        }
    }
References System.Math.Max(), and System.Math.Min().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.SetupGamepadPoints().