Terraria: System.Security.Cryptography.ToBase64Transform.TransformBlock
TransformBlock()
int System.Security.Cryptography.ToBase64Transform.TransformBlock (byte[] inputBuffer, int inputOffset, int inputCount, byte[] outputBuffer, int outputOffset) inline
Implements System.Security.Cryptography.ICryptoTransform.
Definition at line 16 of file ToBase64Transform.cs.
    {
        ThrowHelper.ValidateTransformBlock(inputBuffer, inputOffset, inputCount);
        int result;
        int num = Math.DivRem(inputCount, InputBlockSize, out result);
        if (num == 0)
        {
            ThrowHelper.ThrowArgumentOutOfRange(ThrowHelper.ExceptionArgument.inputCount);
        }
        if (outputBuffer == null)
        {
            ThrowHelper.ThrowArgumentNull(ThrowHelper.ExceptionArgument.outputBuffer);
        }
        if (result != 0)
        {
            ThrowHelper.ThrowArgumentOutOfRange(ThrowHelper.ExceptionArgument.inputCount);
        }
        int num2 = checked(num * OutputBlockSize);
        if (num2 > outputBuffer.Length - outputOffset)
        {
            ThrowHelper.ThrowArgumentOutOfRange(ThrowHelper.ExceptionArgument.outputBuffer);
        }
        Span<byte> span = inputBuffer.AsSpan(inputOffset, inputCount);
        Span<byte> utf = outputBuffer.AsSpan(outputOffset, num2);
        int bytesConsumed;
        int bytesWritten;
        OperationStatus operationStatus = Base64.EncodeToUtf8(span, utf, out bytesConsumed, out bytesWritten, isFinalBlock: false);
        return bytesWritten;
    }
References System.Math.DivRem(), System.Buffers.Text.Base64.EncodeToUtf8(), System.Security.Cryptography.ToBase64Transform.InputBlockSize, System.Security.Cryptography.ToBase64Transform.OutputBlockSize, System.Security.Cryptography.ThrowHelper.ThrowArgumentNull(), System.Security.Cryptography.ThrowHelper.ThrowArgumentOutOfRange(), and System.Security.Cryptography.ThrowHelper.ValidateTransformBlock().