Terraria: Terraria.Social.WeGame.NetClientSocialModule.OnDisconnect
OnDisconnect()
void Terraria.Social.WeGame.NetClientSocialModule.OnDisconnect () inline private
Definition at line 651 of file NetClientSocialModule.cs.
    {
        CleanMyMetaData();
        _hasLocalHost = false;
        Netplay.OnDisconnect -= OnDisconnect;
    }
References Terraria.Social.WeGame.NetClientSocialModule._hasLocalHost, Terraria.Social.WeGame.NetClientSocialModule.CleanMyMetaData(), and Terraria.Social.WeGame.NetClientSocialModule.OnDisconnect().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.LaunchLocalServer(), and Terraria.Social.WeGame.NetClientSocialModule.OnDisconnect().