Terraria: Terraria.GameContent.UI.States.UIWorldCreation.ClearOptionDescription
ClearOptionDescription()
void Terraria.GameContent.UI.States.UIWorldCreation.ClearOptionDescription (UIMouseEvent evt, UIElement listeningElement) inline
Definition at line 530 of file UIWorldCreation.cs.
    {
        _descriptionText.SetText(Language.GetText("UI.WorldDescriptionDefault"));
    }
References Terraria.GameContent.UI.States.UIWorldCreation._descriptionText, Terraria.Localization.Language.GetText(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions(), and Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu().