Terraria: Terraria.GameContent.UI.States.UIWorldCreation.BuildPage
BuildPage()
void Terraria.GameContent.UI.States.UIWorldCreation.BuildPage () inline private
    {
        int num = 18;
        RemoveAllChildren();
        UIElement uIElement = new UIElement
        {
            Width = StyleDimension.FromPixels(500f),
            Height = StyleDimension.FromPixels(434f + (float)num),
            Top = StyleDimension.FromPixels(170f - (float)num),
            HAlign = 0.5f,
            VAlign = 0f
        };
        uIElement.SetPadding(0f);
        Append(uIElement);
        UIPanel uIPanel = new UIPanel
        {
            Width = StyleDimension.FromPercent(1f),
            Height = StyleDimension.FromPixels(280 + num),
            Top = StyleDimension.FromPixels(50f),
            BackgroundColor = new Color(33, 43, 79) * 0.8f
        };
        uIPanel.SetPadding(0f);
        uIElement.Append(uIPanel);
        MakeBackAndCreatebuttons(uIElement);
        UIElement uIElement2 = new UIElement
        {
            Top = StyleDimension.FromPixelsAndPercent(0f, 0f),
            Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
            HAlign = 1f
        };
        uIElement2.SetPadding(0f);
        uIElement2.PaddingTop = 8f;
        uIElement2.PaddingBottom = 12f;
        uIPanel.Append(uIElement2);
        MakeInfoMenu(uIElement2);
    }
References Terraria.UI.UIElement.Append(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIWorldCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu(), Terraria.UI.UIElement.RemoveAllChildren(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.UIWorldCreation().