Terraria: Terraria.GameContent.UI.States.UIWorldCreation.Click_SetName
Click_SetName()
void Terraria.GameContent.UI.States.UIWorldCreation.Click_SetName (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 584 of file UIWorldCreation.cs.
    {
        SoundEngine.PlaySound(10);
        Main.clrInput();
        UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Lang.menu[48].Value, "", OnFinishedSettingName, GoBackHere, 0, allowEmpty: true);
        uIVirtualKeyboard.SetMaxInputLength(27);
        Main.MenuUI.SetState(uIVirtualKeyboard);
    }
References Terraria.Main.clrInput(), Terraria.GameContent.UI.States.UIWorldCreation.GoBackHere(), Terraria.Lang.menu, Terraria.Main.MenuUI, Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingName(), Terraria.Audio.SoundEngine.PlaySound(), and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu().