Terraria: Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions
AddWorldSizeOptions()
void Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions (UIElement container, float accumualtedHeight, MouseEvent clickEvent, string tagGroup, float usableWidthPercent) inline private
Definition at line 286 of file UIWorldCreation.cs.
    {
        WorldSizeId[] array = new WorldSizeId[3]
        {
            WorldSizeId.Small,
            WorldSizeId.Medium,
            WorldSizeId.Large
        };
        LocalizedText[] array2 = new LocalizedText[3]
        {
            Lang.menu[92],
            Lang.menu[93],
            Lang.menu[94]
        };
        LocalizedText[] array3 = new LocalizedText[3]
        {
            Language.GetText("UI.WorldDescriptionSizeSmall"),
            Language.GetText("UI.WorldDescriptionSizeMedium"),
            Language.GetText("UI.WorldDescriptionSizeLarge")
        };
        Color[] array4 = new Color[3]
        {
            Color.Cyan,
            Color.Lerp(Color.Cyan, Color.LimeGreen, 0.5f),
            Color.LimeGreen
        };
        string[] array5 = new string[3] { "Images/UI/WorldCreation/IconSizeSmall", "Images/UI/WorldCreation/IconSizeMedium", "Images/UI/WorldCreation/IconSizeLarge" };
        GroupOptionButton<WorldSizeId>[] array6 = new GroupOptionButton<WorldSizeId>[array.Length];
        for (int i = 0; i < array6.Length; i++)
        {
            GroupOptionButton<WorldSizeId> groupOptionButton = new GroupOptionButton<WorldSizeId>(array[i], array2[i], array3[i], array4[i], array5[i], 1f, 1f, 16f);
            groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(-4 * (array6.Length - 1), 1f / (float)array6.Length * usableWidthPercent);
            groupOptionButton.Left = StyleDimension.FromPercent(1f - usableWidthPercent);
            groupOptionButton.HAlign = (float)i / (float)(array6.Length - 1);
            groupOptionButton.Top.Set(accumualtedHeight, 0f);
            groupOptionButton.OnLeftMouseDown += clickEvent;
            groupOptionButton.OnMouseOver += ShowOptionDescription;
            groupOptionButton.OnMouseOut += ClearOptionDescription;
            groupOptionButton.SetSnapPoint(tagGroup, i);
            container.Append(groupOptionButton);
            array6[i] = groupOptionButton;
        }
        _sizeButtons = array6;
    }
References Terraria.GameContent.UI.States.UIWorldCreation._sizeButtons, Terraria.UI.UIElement.Append(), System.array, Terraria.GameContent.UI.States.UIWorldCreation.ClearOptionDescription(), Microsoft.Xna.Framework.Color.Cyan, Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Color.LimeGreen, Terraria.Lang.menu, and Terraria.GameContent.UI.States.UIWorldCreation.ShowOptionDescription().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu().