Terraria: Terraria.Social.WeGame.NetClientSocialModule.OnRailEvent
OnRailEvent()
void Terraria.Social.WeGame.NetClientSocialModule.OnRailEvent (RAILEventID id, EventBase data) inline
Definition at line 337 of file NetClientSocialModule.cs.
    {
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Invalid comparison between Unknown and I4
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Invalid comparison between Unknown and I4
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Invalid comparison between Unknown and I4
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Invalid comparison between Unknown and I4
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Invalid comparison between Unknown and I4
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Expected O, but got Unknown
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Invalid comparison between Unknown and I4
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Expected O, but got Unknown
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Invalid comparison between Unknown and I4
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Expected O, but got Unknown
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Invalid comparison between Unknown and I4
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Expected O, but got Unknown
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Invalid comparison between Unknown and I4
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Expected O, but got Unknown
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Expected O, but got Unknown
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Expected O, but got Unknown
        WeGameHelper.WriteDebugString("OnRailEvent,id=" + ((object)(RAILEventID)(ref id)).ToString() + " ,result=" + ((object)(RailResult)(ref data.result)).ToString());
        if ((int)id <= 12010)
        {
            if ((int)id != 12002)
            {
                if ((int)id != 12003)
                {
                    if ((int)id == 12010)
                    {
                        OnFriendlistChange((RailFriendsListChanged)data);
                    }
                }
                else
                {
                    OnGetFriendMetaData((RailFriendsGetMetadataResult)data);
                }
            }
            else
            {
                OnRailSetMetaData((RailFriendsSetMetadataResult)data);
            }
        }
        else if ((int)id <= 13503)
        {
            if ((int)id != 13501)
            {
                if ((int)id == 13503)
                {
                    OnRailRespondInvation((RailUsersRespondInvitation)data);
                }
            }
            else
            {
                OnRailGetUsersInfo((RailUsersInfoData)data);
            }
        }
        else if ((int)id != 16001)
        {
            if ((int)id == 16002)
            {
                OnRailCreateSessionFailed((CreateSessionFailed)data);
            }
        }
        else
        {
            OnRailCreateSessionRequest((CreateSessionRequest)data);
        }
    }
References Terraria.Social.WeGame.NetClientSocialModule.OnFriendlistChange(), Terraria.Social.WeGame.NetClientSocialModule.OnGetFriendMetaData(), Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionFailed(), Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionRequest(), Terraria.Social.WeGame.NetClientSocialModule.OnRailGetUsersInfo(), Terraria.Social.WeGame.NetClientSocialModule.OnRailRespondInvation(), Terraria.Social.WeGame.NetClientSocialModule.OnRailSetMetaData(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.RegisterRailEvent().