Terraria: Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields
UpdateInputFields()
void Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields () inline private
Definition at line 626 of file UIWorldCreation.cs.
    {
        _namePlate.SetContents(_optionwWorldName);
        _namePlate.Recalculate();
        _namePlate.TrimDisplayIfOverElementDimensions(27);
        _namePlate.Recalculate();
        _seedPlate.SetContents(_optionSeed);
        _seedPlate.Recalculate();
        _seedPlate.TrimDisplayIfOverElementDimensions(40);
        _seedPlate.Recalculate();
    }
References Terraria.GameContent.UI.States.UIWorldCreation._namePlate, Terraria.GameContent.UI.States.UIWorldCreation._optionSeed, Terraria.GameContent.UI.States.UIWorldCreation._optionwWorldName, Terraria.GameContent.UI.States.UIWorldCreation._seedPlate, Terraria.UI.UIElement.Recalculate(), Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents(), and Terraria.GameContent.UI.Elements.UICharacterNameButton.TrimDisplayIfOverElementDimensions().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.ClickRandomizeName(), Terraria.GameContent.UI.States.UIWorldCreation.ClickRandomizeSeed(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingName(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed(), and Terraria.GameContent.UI.States.UIWorldCreation.SetDefaultOptions().