Terraria: Terraria.Social.WeGame.NetClientSocialModule.OnRailRespondInvation
OnRailRespondInvation()
void Terraria.Social.WeGame.NetClientSocialModule.OnRailRespondInvation (RailUsersRespondInvitation data) inline private
    {
        WeGameHelper.WriteDebugString(" request join game");
        if (_lobby.State != 0)
        {
            _lobby.Leave();
        }
        _inviter_id = data.inviter_id;
        Main.OpenPlayerSelect(delegate(PlayerFileData playerData)
        {
            Main.ServerSideCharacter = false;
            playerData.SetAsActive();
            Main.menuMode = 882;
            Main.statusText = Language.GetTextValue("Social.JoiningFriend", GetFriendNickname(data.inviter_id));
            AsyncGetServerIDByOwener(data.inviter_id);
            WeGameHelper.WriteDebugString("inviter_id: " + ((RailComparableID)data.inviter_id).id_);
        });
    }
References Terraria.Social.WeGame.NetClientSocialModule._inviter_id, Terraria.Social.WeGame.NetSocialModule._lobby, Terraria.Social.WeGame.NetClientSocialModule.AsyncGetServerIDByOwener(), Terraria.Social.WeGame.NetClientSocialModule.GetFriendNickname(), Terraria.Localization.Language.GetTextValue(), Terraria.Social.WeGame.Lobby.Leave(), Terraria.Main.OpenPlayerSelect(), Terraria.IO.PlayerFileData.SetAsActive(), Terraria.Social.WeGame.Lobby.State, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.OnRailEvent().