Terraria: Terraria.Social.WeGame.NetClientSocialModule.Close
Close() [1/2]
void Terraria.Social.WeGame.NetClientSocialModule.Close (RailID remote_peer) inline private
Definition at line 284 of file NetClientSocialModule.cs.
    {
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        if (_connectionStateMap.ContainsKey(remote_peer))
        {
            WeGameHelper.WriteDebugString("CloseRemotePeer, remote:{0}", ((RailComparableID)remote_peer).id_);
            rail_api.RailFactory().RailNetworkHelper().CloseSession(GetLocalPeer(), remote_peer);
            _connectionStateMap[remote_peer] = ConnectionState.Inactive;
            _lobby.Leave();
            _reader.ClearUser(remote_peer);
            _writer.ClearUser(remote_peer);
        }
    }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, Terraria.Social.WeGame.NetSocialModule._lobby, Terraria.Social.WeGame.NetSocialModule._reader, Terraria.Social.WeGame.NetSocialModule._writer, Terraria.Social.WeGame.WeGameP2PReader.ClearUser(), Terraria.Social.WeGame.WeGameP2PWriter.ClearUser(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ContainsKey(), Terraria.Social.WeGame.NetSocialModule.GetLocalPeer(), Terraria.Social.WeGame.Lobby.Leave(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().