Terraria: Terraria.Social.WeGame.NetClientSocialModule.Close
Close() [2/2]
override void Terraria.Social.WeGame.NetClientSocialModule.Close (RemoteAddress address) inline
Definition at line 263 of file NetClientSocialModule.cs.
    {
        CleanMyMetaData();
        RailID remote_peer = RemoteAddressToRailId(address);
        Close(remote_peer);
    }
References Terraria.Social.WeGame.NetClientSocialModule.CleanMyMetaData(), Terraria.Social.WeGame.NetClientSocialModule.Close(), and Terraria.Social.WeGame.NetSocialModule.RemoteAddressToRailId().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.Close(), Terraria.Social.WeGame.NetClientSocialModule.OnPacketRead(), and Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionFailed().