Terraria: System.Security.Cryptography.ToBase64Transform.TransformFinalBlock
TransformFinalBlock()
byte[] System.Security.Cryptography.ToBase64Transform.TransformFinalBlock (byte[] inputBuffer, int inputOffset, int inputCount) inline
Implements System.Security.Cryptography.ICryptoTransform.
Definition at line 46 of file ToBase64Transform.cs.
    {
        ThrowHelper.ValidateTransformBlock(inputBuffer, inputOffset, inputCount);
        if (inputCount == 0)
        {
            return Array.Empty<byte>();
        }
        Span<byte> span = inputBuffer.AsSpan(inputOffset, inputCount);
        int result;
        int num = Math.DivRem(inputCount, InputBlockSize, out result);
        int num2 = num + ((result != 0) ? 1 : 0);
        byte[] array = new byte[num2 * OutputBlockSize];
        int bytesConsumed;
        int bytesWritten;
        OperationStatus operationStatus = Base64.EncodeToUtf8(span, array, out bytesConsumed, out bytesWritten);
        return array;
    }
References System.array, System.Math.DivRem(), System.Buffers.Text.Base64.EncodeToUtf8(), System.Security.Cryptography.ToBase64Transform.InputBlockSize, System.Security.Cryptography.ToBase64Transform.OutputBlockSize, and System.Security.Cryptography.ThrowHelper.ValidateTransformBlock().