Terraria: ItemDropResolver.TryDropping
TryDropping()
void ItemDropResolver.TryDropping (DropAttemptInfo info) inline
     {
         List<IItemDropRule> rulesForNPCID = _database.GetRulesForNPCID(info.npc.netID);
         for (int i = 0; i < rulesForNPCID.Count; i++)
         {
             ResolveRule(rulesForNPCID[i], info);
         }
     }
References _database, ItemDropDatabase.GetRulesForNPCID(), NPC.netID, DropAttemptInfo.npc, and ResolveRule().
Referenced by NPC.NPCLoot_DropItems().