Terraria: System.Diagnostics.Process.EnsureState
EnsureState()
void System.Diagnostics.Process.EnsureState (State state) inline private
Definition at line 1006 of file Process.cs.
    {
        if ((state & State.Associated) != 0 && !Associated)
        {
            throw new InvalidOperationException(System.SR.NoAssociatedProcess);
        }
        if ((state & State.HaveId) != 0)
        {
            if (!_haveProcessId)
            {
                if (!_haveProcessHandle)
                {
                    EnsureState(State.Associated);
                    throw new InvalidOperationException(System.SR.ProcessIdRequired);
                }
                SetProcessId(ProcessManager.GetProcessIdFromHandle(_processHandle));
            }
            _ = state & State.HaveNonExitedId;
            _ = 5;
        }
        if ((state & State.IsLocal) != 0 && _isRemoteMachine)
        {
            throw new NotSupportedException(System.SR.NotSupportedRemote);
        }
        if ((state & State.HaveProcessInfo) != 0 && _processInfo == null)
        {
            if ((state & State.HaveNonExitedId) != State.HaveNonExitedId)
            {
                EnsureState(State.HaveNonExitedId);
            }
            _processInfo = ProcessManager.GetProcessInfo(_processId, _machineName);
            if (_processInfo == null)
            {
                throw new InvalidOperationException(System.SR.NoProcessInfo);
            }
        }
        if ((state & State.Exited) != 0)
        {
            if (!HasExited)
            {
                throw new InvalidOperationException(System.SR.WaitTillExit);
            }
            if (!_haveProcessHandle)
            {
                throw new InvalidOperationException(System.SR.NoProcessHandle);
            }
        }
    }
References System.Diagnostics.Process._haveProcessHandle, System.Diagnostics.Process._haveProcessId, System.Diagnostics.Process._isRemoteMachine, System.Diagnostics.Process._machineName, System.Diagnostics.Process._processHandle, System.Diagnostics.Process._processId, System.Diagnostics.Process._processInfo, System.Diagnostics.Process.Associated, System.Diagnostics.Process.EnsureState(), System.Diagnostics.ProcessManager.GetProcessIdFromHandle(), System.Diagnostics.ProcessManager.GetProcessInfo(), System.Diagnostics.Process.HasExited, System.SR.NoAssociatedProcess, System.SR.NoProcessHandle, System.SR.NoProcessInfo, System.SR.NotSupportedRemote, System.SR.ProcessIdRequired, System.Diagnostics.Process.SetProcessId(), System.state, and System.SR.WaitTillExit.
Referenced by System.Diagnostics.Process.EnsureState(), System.Diagnostics.Process.GetProcessHandle(), and System.Diagnostics.Process.Kill().