Terraria: System.Diagnostics.Process.Close
Close()
void System.Diagnostics.Process.Close () inline
Definition at line 949 of file Process.cs.
    {
        if (!Associated)
        {
            return;
        }
        lock (this)
        {
            StopWatchingForExit();
        }
        if (_haveProcessHandle)
        {
            _processHandle.Dispose();
            _processHandle = null;
            _haveProcessHandle = false;
        }
        _haveProcessId = false;
        _isRemoteMachine = false;
        _machineName = ".";
        _raisedOnExited = false;
        try
        {
            if (_standardOutput != null && (_outputStreamReadMode == StreamReadMode.AsyncMode || _outputStreamReadMode == StreamReadMode.Undefined))
            {
                if (_outputStreamReadMode == StreamReadMode.AsyncMode)
                {
                    _output?.CancelOperation();
                    _output?.Dispose();
                }
                _standardOutput.Close();
            }
            if (_standardError != null && (_errorStreamReadMode == StreamReadMode.AsyncMode || _errorStreamReadMode == StreamReadMode.Undefined))
            {
                if (_errorStreamReadMode == StreamReadMode.AsyncMode)
                {
                    _error?.CancelOperation();
                    _error?.Dispose();
                }
                _standardError.Close();
            }
            if (_standardInput != null && !_standardInputAccessed)
            {
                _standardInput.Close();
            }
        }
        finally
        {
            _standardOutput = null;
            _standardInput = null;
            _standardError = null;
            _output = null;
            _error = null;
            CloseCore();
            Refresh();
        }
    }
References System.Diagnostics.Process._error, System.Diagnostics.Process._errorStreamReadMode, System.Diagnostics.Process._haveProcessHandle, System.Diagnostics.Process._haveProcessId, System.Diagnostics.Process._isRemoteMachine, System.Diagnostics.Process._machineName, System.Diagnostics.Process._output, System.Diagnostics.Process._outputStreamReadMode, System.Diagnostics.Process._processHandle, System.Diagnostics.Process._raisedOnExited, System.Diagnostics.Process._standardError, System.Diagnostics.Process._standardInput, System.Diagnostics.Process._standardInputAccessed, System.Diagnostics.Process._standardOutput, System.Diagnostics.Process.Associated, System.Diagnostics.AsyncStreamReader.CancelOperation(), System.IO.StreamReader.Close(), System.IO.StreamWriter.Close(), System.Diagnostics.Process.CloseCore(), System.Runtime.Serialization.Dictionary, System.Diagnostics.AsyncStreamReader.Dispose(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Diagnostics.Process.Refresh(), and System.Diagnostics.Process.StopWatchingForExit().
Referenced by System.Diagnostics.Process.Dispose(), and System.Diagnostics.Process.Start().