Terraria: System.Diagnostics.Process.SetPrivilege
SetPrivilege()
static unsafe void System.Diagnostics.Process.SetPrivilege (string privilegeName, int attrib) inline static private
Definition at line 1943 of file Process.cs.
    {
        SafeTokenHandle TokenHandle = null;
        try
        {
            if (!global::Interop.Advapi32.OpenProcessToken(global::Interop.Kernel32.GetCurrentProcess(), 32, out TokenHandle))
            {
                throw new Win32Exception();
            }
            if (!global::Interop.Advapi32.LookupPrivilegeValue(null, privilegeName, out var lpLuid))
            {
                throw new Win32Exception();
            }
            Unsafe.SkipInit(out global::Interop.Advapi32.TOKEN_PRIVILEGE tOKEN_PRIVILEGE);
            tOKEN_PRIVILEGE.PrivilegeCount = 1u;
            tOKEN_PRIVILEGE.Privileges.Luid = lpLuid;
            tOKEN_PRIVILEGE.Privileges.Attributes = (uint)attrib;
            global::Interop.Advapi32.AdjustTokenPrivileges(TokenHandle, DisableAllPrivileges: false, &tOKEN_PRIVILEGE, 0u, null, null);
            if (Marshal.GetLastWin32Error() != 0)
            {
                throw new Win32Exception();
            }
        }
        finally
        {
            TokenHandle?.Dispose();
        }
    }
References System.Runtime.Serialization.Dictionary, and System.Runtime.InteropServices.Marshal.GetLastWin32Error().
Referenced by System.Diagnostics.Process.EnterDebugMode(), and System.Diagnostics.Process.LeaveDebugMode().