Terraria: System.Diagnostics.Process.KillTree
KillTree() [2/2]
List< Exception > System.Diagnostics.Process.KillTree (SafeProcessHandle handle) inline private
Definition at line 2294 of file Process.cs.
    {
        List<Exception> list = null;
        try
        {
            Kill();
        }
        catch (Win32Exception item)
        {
            (list ?? (list = new List<Exception>())).Add(item);
        }
        List<(Process, SafeProcessHandle)> processHandlePairs = GetProcessHandlePairs((Process thisProcess, Process otherProcess) => thisProcess.IsParentOf(otherProcess));
        try
        {
            foreach (var item2 in processHandlePairs)
            {
                List<Exception> list2 = item2.Item1.KillTree(item2.Item2);
                if (list2 != null)
                {
                    (list ?? (list = new List<Exception>())).AddRange(list2);
                }
            }
            return list;
        }
        finally
        {
            foreach (var item3 in processHandlePairs)
            {
                item3.Item1.Dispose();
                item3.Item2.Dispose();
            }
        }
    }
References System.Diagnostics.Process.Process(), System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.Runtime.Serialization.Dictionary, System.Diagnostics.Process.GetProcessHandlePairs(), System.item, System.Diagnostics.Process.Kill(), and System.list.