Terraria: System.Diagnostics.Process.Process
Process() [1/2]
System.Diagnostics.Process.Process () inline
Definition at line 887 of file Process.cs.
    {
        if (GetType() == typeof(Process))
        {
            GC.SuppressFinalize(this);
        }
        _machineName = ".";
        _outputStreamReadMode = StreamReadMode.Undefined;
        _errorStreamReadMode = StreamReadMode.Undefined;
    }
References System.Diagnostics.Process._errorStreamReadMode, System.Diagnostics.Process._machineName, System.Diagnostics.Process._outputStreamReadMode, System.Runtime.Serialization.Dictionary, and System.GC.SuppressFinalize().
Referenced by System.Diagnostics.Process.GetCurrentProcess(), System.Diagnostics.Process.GetProcessById(), System.Diagnostics.Process.GetProcesses(), System.Diagnostics.Process.GetProcessHandlePairs(), System.Diagnostics.Process.KillTree(), and System.Diagnostics.Process.Start().