Terraria: System.Diagnostics.Process.Equals
Equals()
bool System.Diagnostics.Process.Equals (Process process) inline private
Definition at line 2272 of file Process.cs.
    {
        try
        {
            return Id == process.Id && StartTime == process.StartTime;
        }
        catch (Exception e) when (IsProcessInvalidException(e))
        {
            return false;
        }
    }
References System.Runtime.Serialization.Dictionary, System.Diagnostics.Process.Id, System.Diagnostics.Process.IsProcessInvalidException(), and System.Diagnostics.Process.StartTime.
Referenced by System.Diagnostics.Process.GetProcessesByName(), and System.Diagnostics.Process.IsSelfOrDescendantOf().