Terraria: System.Diagnostics.Process.WaitForExitCore
WaitForExitCore()
bool System.Diagnostics.Process.WaitForExitCore (int milliseconds) inline private
Definition at line 1636 of file Process.cs.
    {
        SafeProcessHandle safeProcessHandle = null;
        try
        {
            safeProcessHandle = GetProcessHandle(1048576, throwIfExited: false);
            if (safeProcessHandle.IsInvalid)
            {
                return true;
            }
            using global::Interop.Kernel32.ProcessWaitHandle processWaitHandle = new global::Interop.Kernel32.ProcessWaitHandle(safeProcessHandle);
            return _signaled = processWaitHandle.WaitOne(milliseconds);
        }
        finally
        {
            if (milliseconds == -1)
            {
                _output?.EOF.GetAwaiter().GetResult();
                _error?.EOF.GetAwaiter().GetResult();
            }
            safeProcessHandle?.Dispose();
        }
    }
References System.Diagnostics.Process._error, System.Diagnostics.Process._output, System.Diagnostics.Process._signaled, System.Diagnostics.AsyncStreamReader.EOF, System.Threading.Tasks.Task< TResult >.GetAwaiter(), and System.Diagnostics.Process.GetProcessHandle().
Referenced by System.Diagnostics.Process.WaitForExit().