Terraria: System.Diagnostics.Process.GetEnvironmentVariablesBlock
GetEnvironmentVariablesBlock()
static string System.Diagnostics.Process.GetEnvironmentVariablesBlock (IDictionary< string, string > sd) inline static private
Definition at line 2033 of file Process.cs.
    {
        string[] array = new string[sd.Count];
        sd.Keys.CopyTo(array, 0);
        Array.Sort(array, (IComparer<string>?)StringComparer.OrdinalIgnoreCase);
        StringBuilder stringBuilder = new StringBuilder(8 * array.Length);
        string[] array2 = array;
        foreach (string text in array2)
        {
            stringBuilder.Append(text).Append('=').Append(sd[text])
                .Append('\0');
        }
        return stringBuilder.ToString();
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.StringComparer.OrdinalIgnoreCase, System.Array.Sort(), and System.text.
Referenced by System.Diagnostics.Process.StartWithCreateProcess().