Terraria: System.Diagnostics.Process.Kill
Kill() [2/2]
void System.Diagnostics.Process.Kill (bool entireProcessTree) inline
Definition at line 2362 of file Process.cs.
    {
        if (!entireProcessTree)
        {
            Kill();
            return;
        }
        EnsureState((State)34);
        if (IsSelfOrDescendantOf(GetCurrentProcess()))
        {
            throw new InvalidOperationException(System.SR.KillEntireProcessTree_DisallowedBecauseTreeContainsCallingProcess);
        }
        List<Exception> list = KillTree();
        if (list == null || list.Count == 0)
        {
            return;
        }
        throw new AggregateException(System.SR.KillEntireProcessTree_TerminationIncomplete, list);
    }
References System.Diagnostics.Process.EnsureState(), System.Diagnostics.Process.GetCurrentProcess(), System.Diagnostics.Process.IsSelfOrDescendantOf(), System.Diagnostics.Process.Kill(), System.SR.KillEntireProcessTree_DisallowedBecauseTreeContainsCallingProcess, System.SR.KillEntireProcessTree_TerminationIncomplete, System.Diagnostics.Process.KillTree(), and System.list.