Terraria: System.Diagnostics.Process.GetProcessHandlePairs
GetProcessHandlePairs()
List<(Process Process, SafeProcessHandle Handle)> System.Diagnostics.Process.GetProcessHandlePairs (Func< Process, Process, bool > predicate) inline private
Definition at line 2328 of file Process.cs.
    {
        List<(Process, SafeProcessHandle)> list = new List<(Process, SafeProcessHandle)>();
        Process[] processes = GetProcesses();
        foreach (Process process2 in processes)
        {
            SafeProcessHandle safeProcessHandle = SafeGetHandle(process2);
            if (!safeProcessHandle.IsInvalid)
            {
                if (predicate(this, process2))
                {
                    list.Add((process2, safeProcessHandle));
                    continue;
                }
                process2.Dispose();
                safeProcessHandle.Dispose();
            }
        }
        return list;
        static SafeProcessHandle SafeGetHandle(Process process)
        {
            try
            {
                return process.GetProcessHandle(4096, throwIfExited: false);
            }
            catch (Win32Exception)
            {
                return SafeProcessHandle.InvalidHandle;
            }
        }
    }
References System.Diagnostics.Process.Process(), System.Runtime.Serialization.Dictionary, System.Diagnostics.Process.GetProcesses(), Microsoft.Win32.SafeHandles.SafeProcessHandle.InvalidHandle, and System.list.
Referenced by System.Diagnostics.Process.KillTree().