Terraria: System.Diagnostics.Process.GetChildProcesses
GetChildProcesses()
IReadOnlyList< Process > System.Diagnostics.Process.GetChildProcesses (Process[] processes = null) inline private
Definition at line 2417 of file Process.cs.
    {
        bool flag = processes == null;
        processes = processes ?? GetProcesses();
        List<Process> list = new List<Process>();
        Process[] array = processes;
        foreach (Process process in array)
        {
            bool flag2 = flag;
            try
            {
                if (IsParentOf(process))
                {
                    list.Add(process);
                    flag2 = false;
                }
            }
            finally
            {
                if (flag2)
                {
                    process.Dispose();
                }
            }
        }
        return list;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Runtime.Serialization.Dictionary, System.Diagnostics.Process.GetProcesses(), System.Diagnostics.Process.IsParentOf(), and System.list.
Referenced by System.Diagnostics.Process.IsSelfOrDescendantOf().