Terraria: System.Diagnostics.Process.EnsureWatchingForExit
EnsureWatchingForExit()
void System.Diagnostics.Process.EnsureWatchingForExit () inline private
Definition at line 1610 of file Process.cs.
    {
        if (_watchingForExit)
        {
            return;
        }
        lock (this)
        {
            if (!_watchingForExit)
            {
                _watchingForExit = true;
                try
                {
                    _waitHandle = new global::Interop.Kernel32.ProcessWaitHandle(GetOrOpenProcessHandle());
                    _registeredWaitHandle = ThreadPool.RegisterWaitForSingleObject(_waitHandle, CompletionCallback, _waitHandle, -1, executeOnlyOnce: true);
                    return;
                }
                catch
                {
                    _watchingForExit = false;
                    throw;
                }
            }
        }
    }
References System.Diagnostics.Process._registeredWaitHandle, System.Diagnostics.Process._waitHandle, System.Diagnostics.Process._watchingForExit, System.Diagnostics.Process.CompletionCallback(), System.Runtime.Serialization.Dictionary, System.Diagnostics.Process.GetOrOpenProcessHandle(), and System.Threading.ThreadPool.RegisterWaitForSingleObject().
Referenced by System.Diagnostics.Process.SetProcessHandle().