Terraria: System.Diagnostics.Process.CompletionCallback
CompletionCallback()
void System.Diagnostics.Process.CompletionCallback (object waitHandleContext, bool wasSignaled) inline private
Definition at line 910 of file Process.cs.
    {
        lock (this)
        {
            if (waitHandleContext == _waitHandle)
            {
                StopWatchingForExit();
                RaiseOnExited();
            }
        }
    }
References System.Diagnostics.Process._waitHandle, System.Runtime.Serialization.Dictionary, System.Diagnostics.Process.RaiseOnExited(), and System.Diagnostics.Process.StopWatchingForExit().
Referenced by System.Diagnostics.Process.EnsureWatchingForExit().