Terraria: System.Diagnostics.Process.GetProcessHandle
GetProcessHandle() [2/2]
SafeProcessHandle System.Diagnostics.Process.GetProcessHandle (int access, bool throwIfExited = true) inline private
Definition at line 1972 of file Process.cs.
    {
        if (_haveProcessHandle)
        {
            if (throwIfExited)
            {
                using global::Interop.Kernel32.ProcessWaitHandle processWaitHandle = new global::Interop.Kernel32.ProcessWaitHandle(_processHandle);
                if (processWaitHandle.WaitOne(0))
                {
                    throw new InvalidOperationException(_haveProcessId ? System.SR.Format(System.SR.ProcessHasExited, _processId.ToString()) : System.SR.ProcessHasExitedNoId);
                }
            }
            return new SafeProcessHandle(_processHandle.DangerousGetHandle(), ownsHandle: false);
        }
        EnsureState((State)3);
        SafeProcessHandle safeProcessHandle = ProcessManager.OpenProcess(_processId, access, throwIfExited);
        if (throwIfExited && ((uint)access & 0x400u) != 0 && global::Interop.Kernel32.GetExitCodeProcess(safeProcessHandle, out _exitCode) && _exitCode != 259)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.ProcessHasExited, _processId.ToString()));
        }
        return safeProcessHandle;
    }
References System.Diagnostics.Process._exitCode, System.Diagnostics.Process._haveProcessHandle, System.Diagnostics.Process._haveProcessId, System.Diagnostics.Process._processHandle, System.Diagnostics.Process._processId, System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.Serialization.Dictionary, System.Diagnostics.Process.EnsureState(), System.SR.Format(), System.Diagnostics.ProcessManager.OpenProcess(), System.SR.ProcessHasExited, and System.SR.ProcessHasExitedNoId.