Terraria: System.Diagnostics.Process.Start
Start() [1/7]
bool System.Diagnostics.Process.Start () inline
Definition at line 1193 of file Process.cs.
    {
        Close();
        ProcessStartInfo startInfo = StartInfo;
        if (startInfo.FileName.Length == 0)
        {
            throw new InvalidOperationException(System.SR.FileNameMissing);
        }
        if (startInfo.StandardInputEncoding != null && !startInfo.RedirectStandardInput)
        {
            throw new InvalidOperationException(System.SR.StandardInputEncodingNotAllowed);
        }
        if (startInfo.StandardOutputEncoding != null && !startInfo.RedirectStandardOutput)
        {
            throw new InvalidOperationException(System.SR.StandardOutputEncodingNotAllowed);
        }
        if (startInfo.StandardErrorEncoding != null && !startInfo.RedirectStandardError)
        {
            throw new InvalidOperationException(System.SR.StandardErrorEncodingNotAllowed);
        }
        if (!string.IsNullOrEmpty(startInfo.Arguments) && startInfo.HasArgumentList)
        {
            throw new InvalidOperationException(System.SR.ArgumentAndArgumentListInitialized);
        }
        CheckDisposed();
        SerializationGuard.ThrowIfDeserializationInProgress("AllowProcessCreation", ref s_cachedSerializationSwitch);
        return StartCore(startInfo);
    }
References System.SR.ArgumentAndArgumentListInitialized, System.Diagnostics.Process.CheckDisposed(), System.Diagnostics.Process.Close(), System.SR.FileNameMissing, System.Diagnostics.Process.s_cachedSerializationSwitch, System.SR.StandardErrorEncodingNotAllowed, System.SR.StandardInputEncodingNotAllowed, System.SR.StandardOutputEncodingNotAllowed, System.Diagnostics.Process.StartCore(), System.Diagnostics.Process.StartInfo, and System.Runtime.Serialization.SerializationGuard.ThrowIfDeserializationInProgress().
Referenced by ReLogic.OS.Linux.Clipboard.GetClipboard(), ReLogic.OS.OSX.Clipboard.GetClipboard(), Terraria.Social.Steam.NetClientSocialModule.LaunchLocalServer(), Terraria.Utils.OpenFolder(), ReLogic.OS.Linux.PathService.OpenURL(), ReLogic.OS.OSX.PathService.OpenURL(), ReLogic.OS.Windows.PathService.OpenURL(), System.Diagnostics.Process.Start(), System.Diagnostics.Process.Start(), System.Diagnostics.Process.Start(), System.Diagnostics.Process.Start(), and System.Diagnostics.Process.Start().