Terraria: System.Diagnostics.Process.StartWithShellExecuteEx
StartWithShellExecuteEx()
unsafe bool System.Diagnostics.Process.StartWithShellExecuteEx (ProcessStartInfo startInfo) inline private
Definition at line 2062 of file Process.cs.
    {
        if (!string.IsNullOrEmpty(startInfo.UserName) || startInfo.Password != null)
        {
            throw new InvalidOperationException(System.SR.CantStartAsUser);
        }
        if (startInfo.RedirectStandardInput || startInfo.RedirectStandardOutput || startInfo.RedirectStandardError)
        {
            throw new InvalidOperationException(System.SR.CantRedirectStreams);
        }
        if (startInfo.StandardInputEncoding != null)
        {
            throw new InvalidOperationException(System.SR.StandardInputEncodingNotAllowed);
        }
        if (startInfo.StandardErrorEncoding != null)
        {
            throw new InvalidOperationException(System.SR.StandardErrorEncodingNotAllowed);
        }
        if (startInfo.StandardOutputEncoding != null)
        {
            throw new InvalidOperationException(System.SR.StandardOutputEncodingNotAllowed);
        }
        if (startInfo._environmentVariables != null)
        {
            throw new InvalidOperationException(System.SR.CantUseEnvVars);
        }
        string text = startInfo.BuildArguments();
        fixed (char* lpFile = ((startInfo.FileName.Length > 0) ? startInfo.FileName : null))
        {
            fixed (char* lpVerb = ((startInfo.Verb.Length > 0) ? startInfo.Verb : null))
            {
                fixed (char* lpParameters = ((text.Length > 0) ? text : null))
                {
                    fixed (char* lpDirectory = ((startInfo.WorkingDirectory.Length > 0) ? startInfo.WorkingDirectory : null))
                    {
                        global::Interop.Shell32.SHELLEXECUTEINFO sHELLEXECUTEINFO = default(global::Interop.Shell32.SHELLEXECUTEINFO);
                        sHELLEXECUTEINFO.cbSize = (uint)sizeof(global::Interop.Shell32.SHELLEXECUTEINFO);
                        sHELLEXECUTEINFO.lpFile = lpFile;
                        sHELLEXECUTEINFO.lpVerb = lpVerb;
                        sHELLEXECUTEINFO.lpParameters = lpParameters;
                        sHELLEXECUTEINFO.lpDirectory = lpDirectory;
                        sHELLEXECUTEINFO.fMask = 320u;
                        global::Interop.Shell32.SHELLEXECUTEINFO sHELLEXECUTEINFO2 = sHELLEXECUTEINFO;
                        if (startInfo.ErrorDialog)
{
                            sHELLEXECUTEINFO2.hwnd = startInfo.ErrorDialogParentHandle;
                        }
                        else
{
                            sHELLEXECUTEINFO2.fMask |= 1024u;
                        }
                        sHELLEXECUTEINFO2.nShow = startInfo.WindowStyle switch
{
                            ProcessWindowStyle.Hidden => 0,
                            ProcessWindowStyle.Minimized => 2,
                            ProcessWindowStyle.Maximized => 3,
                            _ => 1,
                        };
                        ShellExecuteHelper shellExecuteHelper = new ShellExecuteHelper(&sHELLEXECUTEINFO2);
                        if (!shellExecuteHelper.ShellExecuteOnSTAThread())
{
                            int num = shellExecuteHelper.ErrorCode;
                            if (num == 0)
{
                                num = GetShellError(sHELLEXECUTEINFO2.hInstApp);
                            }
                            string text2;
                            switch (num)
{
                            case 120:
                                throw new PlatformNotSupportedException(System.SR.UseShellExecuteNotSupported);
                            default:
                                text2 = GetErrorMessage(num);
                                break;
                            case 193:
                            case 216:
                                text2 = System.SR.InvalidApplication;
                                break;
                            }
                            string errorMessage = text2;
                            throw CreateExceptionForErrorStartingProcess(errorMessage, num, startInfo.FileName, startInfo.WorkingDirectory);
                        }
                        if (sHELLEXECUTEINFO2.hProcess != IntPtr.Zero)
{
                            SetProcessHandle(new SafeProcessHandle(sHELLEXECUTEINFO2.hProcess));
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }
References System.SR.CantRedirectStreams, System.SR.CantStartAsUser, System.SR.CantUseEnvVars, System.Diagnostics.Process.CreateExceptionForErrorStartingProcess(), System.Runtime.Serialization.Dictionary, System.Diagnostics.Process.GetErrorMessage(), System.Diagnostics.Process.GetShellError(), System.SR.InvalidApplication, System.Diagnostics.Process.SetProcessHandle(), System.SR.StandardErrorEncodingNotAllowed, System.SR.StandardInputEncodingNotAllowed, System.SR.StandardOutputEncodingNotAllowed, System.text, System.SR.UseShellExecuteNotSupported, and System.IntPtr.Zero.
Referenced by System.Diagnostics.Process.StartCore().