Terraria: System.Diagnostics.Process.Refresh
Refresh()
void System.Diagnostics.Process.Refresh () inline
Definition at line 1149 of file Process.cs.
    {
        _processInfo = null;
        _threads?.Dispose();
        _threads = null;
        _modules?.Dispose();
        _modules = null;
        _exited = false;
        _haveWorkingSetLimits = false;
        _haveProcessorAffinity = false;
        _havePriorityClass = false;
        _haveExitTime = false;
        _havePriorityBoostEnabled = false;
        RefreshCore();
    }
References System.Diagnostics.Process._exited, System.Diagnostics.Process._haveExitTime, System.Diagnostics.Process._havePriorityBoostEnabled, System.Diagnostics.Process._havePriorityClass, System.Diagnostics.Process._haveProcessorAffinity, System.Diagnostics.Process._haveWorkingSetLimits, System.Diagnostics.Process._modules, System.Diagnostics.Process._processInfo, System.Diagnostics.Process._threads, System.Diagnostics.ProcessModuleCollection.Dispose(), System.Diagnostics.ProcessThreadCollection.Dispose(), and System.Diagnostics.Process.RefreshCore().
Referenced by System.Diagnostics.Process.Close().