Terraria: System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Remove
Remove()
static DiagnosticSubscription System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Remove (DiagnosticSubscription subscriptions, DiagnosticSubscription subscription) inline static private
Definition at line 37 of file DiagnosticListener.cs.
        {
            if (subscriptions == null)
            {
                return null;
            }
            if (subscriptions.Observer == subscription.Observer && subscriptions.IsEnabled1Arg == subscription.IsEnabled1Arg && subscriptions.IsEnabled3Arg == subscription.IsEnabled3Arg)
            {
                return subscriptions.Next;
            }
            return new DiagnosticSubscription
            {
                Observer = subscriptions.Observer,
                Owner = subscriptions.Owner,
                IsEnabled1Arg = subscriptions.IsEnabled1Arg,
                IsEnabled3Arg = subscriptions.IsEnabled3Arg,
                Next = Remove(subscriptions.Next, subscription)
            };
        }
References System.Diagnostics.DiagnosticListener.DiagnosticSubscription.IsEnabled1Arg, System.Diagnostics.DiagnosticListener.DiagnosticSubscription.IsEnabled3Arg, System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Next, System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Observer, System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Owner, and System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Remove().
Referenced by System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Dispose(), and System.Diagnostics.DiagnosticListener.DiagnosticSubscription.Remove().