Terraria: Terraria.GameContent.FlexibleTileWand.TryGetPlacementOption
TryGetPlacementOption()
bool Terraria.GameContent.FlexibleTileWand.TryGetPlacementOption (Player player, int randomSeed, int selectCycleOffset, out PlacementOption option, out Item itemToConsume) inline
    {
        option = null;
        itemToConsume = null;
        Item[] inventory = player.inventory;
        for (int i = 0; i < 58; i++)
        {
            if (i < 50 || i >= 54)
            {
                Item item = inventory[i];
                if (!item.IsAir && _options.TryGetValue(item.type, out var value))
                {
                    _random.SetSeed(randomSeed);
                    option = value.GetOptionWithCycling(selectCycleOffset);
                    itemToConsume = item;
                    return true;
                }
            }
        }
        return false;
    }
References Terraria.GameContent.FlexibleTileWand._options, Terraria.GameContent.FlexibleTileWand._random, Terraria.Player.inventory, Terraria.Item.IsAir, Terraria.Utilities.UnifiedRandom.SetSeed(), and Terraria.Item.type.
Referenced by Terraria.Player.ModifyFlexibleWandPlacementInfo(), Terraria.Player.PlaceThing_Tiles_CheckFlexibleWand(), and Terraria.Player.PlaceThing_Tiles_PlaceIt_ConsumeFlexibleWandMaterial().