Terraria: System.Data.DataRelationCollection.Add
Add() [3/7]
void System.Data.DataRelationCollection.Add (DataRelation relation) inline inherited
Definition at line 430 of file DataRelationCollection.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataRelationCollection.Add|API> {0}, relation={1}", ObjectID, relation?.ObjectID ?? 0);
        try
        {
            if (_inTransition == relation)
            {
                return;
            }
            _inTransition = relation;
            try
            {
                OnCollectionChanging(new CollectionChangeEventArgs(CollectionChangeAction.Add, relation));
                AddCore(relation);
                OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Add, relation));
            }
            finally
            {
                _inTransition = null;
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataRelationCollection._inTransition, System.Data.DataRelationCollection.AddCore(), System.Data.DataCommonEventSource.Log, System.Data.DataRelationCollection.ObjectID, System.Data.DataRelationCollection.OnCollectionChanged(), and System.Data.DataRelationCollection.OnCollectionChanging().
Referenced by System.Data.DataRelationCollection.DataTableRelationCollection.AddCore(), System.Data.DataSet.DeserializeRelations(), System.Data.XSDSchema.HandleRelation(), System.Data.XDRSchema.InstantiateTable(), System.Data.Merger.MergeRelation(), and System.Data.DataTable.ReadXmlSchema().