Terraria: System.Data.DataRelationCollection.Remove
Remove() [1/2]
void System.Data.DataRelationCollection.Remove (DataRelation relation) inline inherited
Definition at line 699 of file DataRelationCollection.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataRelationCollection.Remove|API> {0}, relation={1}", ObjectID, relation?.ObjectID ?? 0);
        if (_inTransition == relation)
        {
            return;
        }
        _inTransition = relation;
        try
        {
            OnCollectionChanging(new CollectionChangeEventArgs(CollectionChangeAction.Remove, relation));
            RemoveCore(relation);
            OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Remove, relation));
        }
        finally
        {
            _inTransition = null;
        }
    }
References System.Data.DataRelationCollection._inTransition, System.Data.DataCommonEventSource.Log, System.Data.DataRelationCollection.ObjectID, System.Data.DataRelationCollection.OnCollectionChanged(), System.Data.DataRelationCollection.OnCollectionChanging(), and System.Data.DataRelationCollection.RemoveCore().
Referenced by System.Data.DataRelationCollection.DataTableRelationCollection.RemoveCore().