Terraria: System.Data.DataRelationCollection.Clear
Clear()
virtual void System.Data.DataRelationCollection.Clear () inline virtual inherited
Reimplemented in System.Data.DataRelationCollection.DataSetRelationCollection.
Definition at line 550 of file DataRelationCollection.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataRelationCollection.Clear|API> {0}", ObjectID);
        try
        {
            int count = Count;
            OnCollectionChanging(InternalDataCollectionBase.s_refreshEventArgs);
            for (int num = count - 1; num >= 0; num--)
            {
                _inTransition = this[num];
                RemoveCore(_inTransition);
            }
            OnCollectionChanged(InternalDataCollectionBase.s_refreshEventArgs);
            _inTransition = null;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataRelationCollection._inTransition, System.Data.InternalDataCollectionBase.Count, System.count, System.Data.DataCommonEventSource.Log, System.Data.DataRelationCollection.ObjectID, System.Data.DataRelationCollection.OnCollectionChanged(), System.Data.DataRelationCollection.OnCollectionChanging(), System.Data.DataRelationCollection.RemoveCore(), and System.Data.InternalDataCollectionBase.s_refreshEventArgs.
Referenced by System.Data.DataSet.Reset().