Terraria: System.Data.DataRelationCollection.AddCore
AddCore()
virtual void System.Data.DataRelationCollection.AddCore (DataRelation relation) inline protected virtual
Reimplemented in System.Data.DataRelationCollection.DataTableRelationCollection, and System.Data.DataRelationCollection.DataSetRelationCollection.
Definition at line 514 of file DataRelationCollection.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataRelationCollection.AddCore|INFO> {0}, relation={1}", ObjectID, relation?.ObjectID ?? 0);
        if (relation == null)
        {
            throw ExceptionBuilder.ArgumentNull("relation");
        }
        relation.CheckState();
        DataSet dataSet = GetDataSet();
        if (relation.DataSet == dataSet)
        {
            throw ExceptionBuilder.RelationAlreadyInTheDataSet();
        }
        if (relation.DataSet != null)
        {
            throw ExceptionBuilder.RelationAlreadyInOtherDataSet();
        }
        if (relation.ChildTable.Locale.LCID != relation.ParentTable.Locale.LCID || relation.ChildTable.CaseSensitive != relation.ParentTable.CaseSensitive)
        {
            throw ExceptionBuilder.CaseLocaleMismatch();
        }
        if (relation.Nested)
        {
            relation.CheckNamespaceValidityForNestedRelations(relation.ParentTable.Namespace);
            relation.ValidateMultipleNestedRelations();
            relation.ParentTable.ElementColumnCount++;
        }
    }
References System.Data.ExceptionBuilder.ArgumentNull(), System.Data.ExceptionBuilder.CaseLocaleMismatch(), System.Data.DataTable.CaseSensitive, System.Data.DataRelation.CheckNamespaceValidityForNestedRelations(), System.Data.DataRelation.CheckState(), System.Data.DataRelation.ChildTable, System.Data.DataRelation.DataSet, System.Data.DataTable.ElementColumnCount, System.Data.DataRelationCollection.GetDataSet(), System.Globalization.CultureInfo.LCID, System.Data.DataTable.Locale, System.Data.DataCommonEventSource.Log, System.Data.DataTable.Namespace, System.Data.DataRelation.Nested, System.Data.DataRelationCollection.ObjectID, System.Data.DataRelation.ParentTable, System.Data.ExceptionBuilder.RelationAlreadyInOtherDataSet(), System.Data.ExceptionBuilder.RelationAlreadyInTheDataSet(), and System.Data.DataRelation.ValidateMultipleNestedRelations().
Referenced by System.Data.DataRelationCollection.Add().