Terraria: System.Data.DataRelationCollection.InternalIndexOf
InternalIndexOf()
int System.Data.DataRelationCollection.InternalIndexOf (string name) inline package inherited
Definition at line 620 of file DataRelationCollection.cs.
    {
        int num = -1;
        if (name != null && 0 < name.Length)
        {
            int count = List.Count;
            int num2 = 0;
            for (int i = 0; i < count; i++)
            {
                DataRelation dataRelation = (DataRelation)List[i];
                switch (NamesEqual(dataRelation.RelationName, name, fCaseSensitive: false, GetDataSet().Locale))
                {
                case 1:
                    return i;
                case -1:
                    num = ((num == -1) ? i : (-2));
                    break;
                }
            }
        }
        return num;
    }
References System.count, System.Collections.ArrayList.Count, System.Data.DataRelationCollection.GetDataSet(), System.Data.InternalDataCollectionBase.List, System.Data.DataSet.Locale, System.Data.InternalDataCollectionBase.NamesEqual(), and System.Data.DataRelation.RelationName.
Referenced by System.Data.DataRelationCollection.Contains(), System.Data.DataRelationCollection.IndexOf(), and System.Data.Merger.MergeRelation().