Terraria: System.Data.DataRelationCollection.OnCollectionChanged
OnCollectionChanged()
virtual void System.Data.DataRelationCollection.OnCollectionChanged (CollectionChangeEventArgs ccevent) inline protected virtual inherited
Definition at line 654 of file DataRelationCollection.cs.
    {
        if (_onCollectionChangedDelegate != null)
        {
            DataCommonEventSource.Log.Trace("<ds.DataRelationCollection.OnCollectionChanged|INFO> {0}", ObjectID);
            _onCollectionChangedDelegate(this, ccevent);
        }
    }
References System.Data.DataRelationCollection._onCollectionChangedDelegate, System.Data.DataCommonEventSource.Log, and System.Data.DataRelationCollection.ObjectID.
Referenced by System.Data.DataRelationCollection.Add(), System.Data.DataRelationCollection.Clear(), and System.Data.DataRelationCollection.Remove().