Terraria: System.Data.DataRelationCollection.RemoveCore
RemoveCore()
virtual void System.Data.DataRelationCollection.RemoveCore (DataRelation relation) inline protected virtual
Reimplemented in System.Data.DataRelationCollection.DataTableRelationCollection, and System.Data.DataRelationCollection.DataSetRelationCollection.
Definition at line 739 of file DataRelationCollection.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataRelationCollection.RemoveCore|INFO> {0}, relation={1}", ObjectID, relation?.ObjectID ?? 0);
        if (relation == null)
        {
            throw ExceptionBuilder.ArgumentNull("relation");
        }
        DataSet dataSet = GetDataSet();
        if (relation.DataSet != dataSet)
        {
            throw ExceptionBuilder.RelationNotInTheDataSet(relation.RelationName);
        }
        if (relation.Nested)
        {
            relation.ParentTable.ElementColumnCount--;
            relation.ParentTable.Columns.UnregisterName(relation.ChildTable.TableName);
        }
    }
References System.Data.ExceptionBuilder.ArgumentNull(), System.Data.DataRelation.ChildTable, System.Data.DataTable.Columns, System.Data.DataRelation.DataSet, System.Data.DataTable.ElementColumnCount, System.Data.DataRelationCollection.GetDataSet(), System.Data.DataCommonEventSource.Log, System.Data.DataRelation.Nested, System.Data.DataRelationCollection.ObjectID, System.Data.DataRelation.ParentTable, System.Data.DataRelation.RelationName, System.Data.ExceptionBuilder.RelationNotInTheDataSet(), System.Data.DataTable.TableName, and System.Data.DataColumnCollection.UnregisterName().
Referenced by System.Data.DataRelationCollection.Clear(), and System.Data.DataRelationCollection.Remove().