Terraria: System.Dynamic.DynamicMetaObjectBinder.Bind
Bind() [3/3]
override Expression System.Dynamic.DynamicMetaObjectBinder.Bind (object[] args, ReadOnlyCollection< ParameterExpression > parameters, LabelTarget returnLabel) inline sealed inherited
Definition at line 15 of file DynamicMetaObjectBinder.cs.
    {
        ContractUtils.RequiresNotNull(args, "args");
        ContractUtils.RequiresNotNull(parameters, "parameters");
        ContractUtils.RequiresNotNull(returnLabel, "returnLabel");
        if (args.Length == 0)
        {
            throw Error.OutOfRange("args.Length", 1);
        }
        if (parameters.Count == 0)
        {
            throw Error.OutOfRange("parameters.Count", 1);
        }
        if (args.Length != parameters.Count)
        {
            throw new ArgumentOutOfRangeException("args");
        }
        Type type;
        if (IsStandardBinder)
        {
            type = ReturnType;
            if (returnLabel.Type != typeof(void) && !TypeUtils.AreReferenceAssignable(returnLabel.Type, type))
            {
                throw Error.BinderNotCompatibleWithCallSite(type, this, returnLabel.Type);
            }
        }
        else
        {
            type = returnLabel.Type;
        }
        DynamicMetaObject dynamicMetaObject = DynamicMetaObject.Create(args[0], parameters[0]);
        DynamicMetaObject[] args2 = CreateArgumentMetaObjects(args, parameters);
        DynamicMetaObject dynamicMetaObject2 = Bind(dynamicMetaObject, args2);
        if (dynamicMetaObject2 == null)
        {
            throw Error.BindingCannotBeNull();
        }
        Expression expression = dynamicMetaObject2.Expression;
        BindingRestrictions restrictions = dynamicMetaObject2.Restrictions;
        if (type != typeof(void) && !TypeUtils.AreReferenceAssignable(type, expression.Type))
        {
            if (dynamicMetaObject.Value is IDynamicMetaObjectProvider)
            {
                throw Error.DynamicObjectResultNotAssignable(expression.Type, dynamicMetaObject.Value.GetType(), this, type);
            }
            throw Error.DynamicBinderResultNotAssignable(expression.Type, this, type);
        }
        if (IsStandardBinder && args[0] is IDynamicMetaObjectProvider && restrictions == BindingRestrictions.Empty)
        {
            throw Error.DynamicBindingNeedsRestrictions(dynamicMetaObject.Value.GetType(), this);
        }
        if (expression.NodeType != ExpressionType.Goto)
        {
            expression = Expression.Return(returnLabel, expression);
        }
        if (restrictions != BindingRestrictions.Empty)
        {
            expression = Expression.IfThen(restrictions.ToExpression(), expression);
        }
        return expression;
    }
References System.Dynamic.Utils.TypeUtils.AreReferenceAssignable(), System.Dynamic.DynamicMetaObjectBinder.Bind(), System.Linq.Expressions.Error.BinderNotCompatibleWithCallSite(), System.Linq.Expressions.Error.BindingCannotBeNull(), System.Collections.ObjectModel.ReadOnlyCollection< T >.Count, System.Dynamic.DynamicMetaObject.Create(), System.Dynamic.DynamicMetaObjectBinder.CreateArgumentMetaObjects(), System.Linq.Expressions.Error.DynamicBinderResultNotAssignable(), System.Linq.Expressions.Error.DynamicBindingNeedsRestrictions(), System.Linq.Expressions.Error.DynamicObjectResultNotAssignable(), System.Dynamic.BindingRestrictions.Empty, System.Dynamic.DynamicMetaObject.Expression, System.Linq.Expressions.Expression< TDelegate >.IfThen(), System.Dynamic.DynamicMetaObjectBinder.IsStandardBinder, System.Linq.Expressions.Expression< TDelegate >.NodeType, System.Linq.Expressions.Error.OutOfRange(), System.Dynamic.Utils.ContractUtils.RequiresNotNull(), System.Dynamic.DynamicMetaObject.Restrictions, System.Linq.Expressions.Expression< TDelegate >.Return(), System.Dynamic.DynamicMetaObjectBinder.ReturnType, System.Dynamic.BindingRestrictions.ToExpression(), System.Linq.Expressions.Expression< TDelegate >.Type, System.Linq.Expressions.LabelTarget.Type, System.type, and System.Dynamic.DynamicMetaObject.Value.
Referenced by System.Dynamic.DynamicMetaObjectBinder.Bind().