Terraria: System.Data.DataRelationCollection.GetDataSet
GetDataSet()
DataSet System.Data.DataRelationCollection.GetDataSet () abstract protected
Referenced by System.Data.DataRelationCollection.AddCore(), System.Data.DataRelationCollection.CanRemove(), System.Data.DataRelationCollection.InternalIndexOf(), System.Data.DataRelationCollection.RegisterName(), System.Data.DataRelationCollection.RemoveCore(), and System.Data.DataRelationCollection.UnregisterName().