Terraria: ItemSlot.DrawRadialDpad
DrawRadialDpad()
static void ItemSlot.DrawRadialDpad (SpriteBatch sb, Vector2 position) inline static
     {
         if (!PlayerInput.UsingGamepad || !PlayerInput.CurrentProfile.UsingDpadHotbar())
         {
             return;
         }
         Player player = Main.player[Main.myPlayer];
         if (player.chest != -1)
         {
             return;
         }
         Texture2D value = TextureAssets.HotbarRadial[0].Value;
         float num = (float)(int)Main.mouseTextColor / 255f;
         float num2 = 1f - (1f - num) * (1f - num);
         num2 *= 0.785f;
         Color color = Color.White * num2;
         sb.Draw(value, position, null, color, 0f, value.Size() / 2f, Main.inventoryScale, SpriteEffects.None, 0f);
         for (int i = 0; i < 4; i++)
         {
             int num3 = player.DpadRadial.Bindings[i];
             if (num3 != -1)
             {
                 Draw(sb, player.inventory, 14, num3, position + new Vector2(value.Width / 3, 0f).RotatedBy(-(float)Math.PI / 2f + (float)Math.PI / 2f * (float)i) + new Vector2(-26f * Main.inventoryScale), Color.White);
             }
         }
     }
References Player.SelectionRadial.Bindings, Player.chest, Color, PlayerInput.CurrentProfile, Player.DpadRadial, Draw(), TextureAssets.HotbarRadial, Player.inventory, Main.inventoryScale, Main.mouseTextColor, Main.myPlayer, Main.player, PlayerInputProfile.UsingDpadHotbar(), PlayerInput.UsingGamepad, and Asset< T >.Value.
Referenced by Main.DrawInventory().