Terraria: ItemSlot.LeftClick
LeftClick() [1/2]
static void ItemSlot.LeftClick (Item[] inv, int context = 0, int slot = 0) inline static
     {
         Player player = Main.player[Main.myPlayer];
         bool flag = Main.mouseLeftRelease && Main.mouseLeft;
         if (flag)
         {
             if (OverrideLeftClick(inv, context, slot))
             {
                 return;
             }
             inv[slot].newAndShiny = false;
             if (LeftClick_SellOrTrash(inv, context, slot) || player.itemAnimation != 0 || player.itemTime != 0)
             {
                 return;
             }
         }
         int num = PickItemMovementAction(inv, context, slot, Main.mouseItem);
         if (num != 3 && !flag)
         {
             return;
         }
         switch (num)
         {
         case 0:
             if (context == 6 && Main.mouseItem.type != 0)
             {
                 inv[slot].SetDefaults();
             }
             if (context == 11 && !inv[slot].FitsAccessoryVanitySlot)
             {
                 break;
             }
             Utils.Swap(ref inv[slot], ref Main.mouseItem);
             if (inv[slot].stack > 0)
             {
                 AnnounceTransfer(new ItemTransferInfo(inv[slot], 21, context, inv[slot].stack));
             }
             else
             {
                 AnnounceTransfer(new ItemTransferInfo(Main.mouseItem, context, 21, Main.mouseItem.stack));
             }
             if (inv[slot].stack > 0)
             {
                 switch (context)
                 {
                 case 0:
                     AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                     break;
                 case 8:
                 case 9:
                 case 10:
                 case 11:
                 case 12:
                 case 16:
                 case 17:
                 case 25:
                 case 27:
                 case 33:
                     AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                     break;
                 }
             }
             if (inv[slot].type == 0 || inv[slot].stack < 1)
             {
                 inv[slot] = new Item();
             }
             if (Main.mouseItem.IsTheSameAs(inv[slot]))
             {
                 Utils.Swap(ref inv[slot].favorited, ref Main.mouseItem.favorited);
                 if (inv[slot].stack != inv[slot].maxStack && Main.mouseItem.stack != Main.mouseItem.maxStack)
                 {
                     if (Main.mouseItem.stack + inv[slot].stack <= Main.mouseItem.maxStack)
                     {
                         inv[slot].stack += Main.mouseItem.stack;
                         Main.mouseItem.stack = 0;
                         AnnounceTransfer(new ItemTransferInfo(inv[slot], 21, context, inv[slot].stack));
                     }
                     else
                     {
                         int num2 = Main.mouseItem.maxStack - inv[slot].stack;
                         inv[slot].stack += num2;
                         Main.mouseItem.stack -= num2;
                         AnnounceTransfer(new ItemTransferInfo(inv[slot], 21, context, num2));
                     }
                 }
             }
             if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
             {
                 Main.mouseItem = new Item();
             }
             if (Main.mouseItem.type > 0 || inv[slot].type > 0)
             {
                 Recipe.FindRecipes();
                 SoundEngine.PlaySound(7);
             }
             if (context == 3 && Main.netMode == 1)
             {
                 NetMessage.SendData(32, -1, -1, null, player.chest, slot);
             }
             break;
         case 1:
             if (Main.mouseItem.stack == 1 && Main.mouseItem.type > 0 && inv[slot].type > 0 && inv[slot].IsNotTheSameAs(Main.mouseItem) && (context != 11 || Main.mouseItem.FitsAccessoryVanitySlot))
             {
                 Utils.Swap(ref inv[slot], ref Main.mouseItem);
                 SoundEngine.PlaySound(7);
                 if (inv[slot].stack > 0)
                 {
                     switch (context)
                     {
                     case 0:
                         AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                         break;
                     case 8:
                     case 9:
                     case 10:
                     case 11:
                     case 12:
                     case 16:
                     case 17:
                     case 25:
                     case 27:
                     case 33:
                         AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                         break;
                     }
                 }
             }
             else if (Main.mouseItem.type == 0 && inv[slot].type > 0)
             {
                 Utils.Swap(ref inv[slot], ref Main.mouseItem);
                 if (inv[slot].type == 0 || inv[slot].stack < 1)
                 {
                     inv[slot] = new Item();
                 }
                 if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
                 {
                     Main.mouseItem = new Item();
                 }
                 if (Main.mouseItem.type > 0 || inv[slot].type > 0)
                 {
                     Recipe.FindRecipes();
                     SoundEngine.PlaySound(7);
                 }
             }
             else if (Main.mouseItem.type > 0 && inv[slot].type == 0 && (context != 11 || Main.mouseItem.FitsAccessoryVanitySlot))
             {
                 if (Main.mouseItem.stack == 1)
                 {
                     Utils.Swap(ref inv[slot], ref Main.mouseItem);
                     if (inv[slot].type == 0 || inv[slot].stack < 1)
                     {
                         inv[slot] = new Item();
                     }
                     if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
                     {
                         Main.mouseItem = new Item();
                     }
                     if (Main.mouseItem.type > 0 || inv[slot].type > 0)
                     {
                         Recipe.FindRecipes();
                         SoundEngine.PlaySound(7);
                     }
                 }
                 else
                 {
                     Main.mouseItem.stack--;
                     inv[slot].SetDefaults(Main.mouseItem.type);
                     Recipe.FindRecipes();
                     SoundEngine.PlaySound(7);
                 }
                 if (inv[slot].stack > 0)
                 {
                     switch (context)
                     {
                     case 0:
                         AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                         break;
                     case 8:
                     case 9:
                     case 10:
                     case 11:
                     case 12:
                     case 16:
                     case 17:
                     case 25:
                     case 27:
                     case 33:
                         AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                         break;
                     }
                 }
             }
             if ((context == 23 || context == 24) && Main.netMode == 1)
             {
                 NetMessage.SendData(121, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot);
             }
             if (context == 26 && Main.netMode == 1)
             {
                 NetMessage.SendData(124, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot);
             }
             break;
         case 2:
             if (Main.mouseItem.stack == 1 && Main.mouseItem.dye > 0 && inv[slot].type > 0 && inv[slot].type != Main.mouseItem.type)
             {
                 Utils.Swap(ref inv[slot], ref Main.mouseItem);
                 SoundEngine.PlaySound(7);
                 if (inv[slot].stack > 0)
                 {
                     switch (context)
                     {
                     case 0:
                         AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                         break;
                     case 8:
                     case 9:
                     case 10:
                     case 11:
                     case 12:
                     case 16:
                     case 17:
                     case 25:
                     case 27:
                     case 33:
                         AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                         break;
                     }
                 }
             }
             else if (Main.mouseItem.type == 0 && inv[slot].type > 0)
             {
                 Utils.Swap(ref inv[slot], ref Main.mouseItem);
                 if (inv[slot].type == 0 || inv[slot].stack < 1)
                 {
                     inv[slot] = new Item();
                 }
                 if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
                 {
                     Main.mouseItem = new Item();
                 }
                 if (Main.mouseItem.type > 0 || inv[slot].type > 0)
                 {
                     Recipe.FindRecipes();
                     SoundEngine.PlaySound(7);
                 }
             }
             else if (Main.mouseItem.dye > 0 && inv[slot].type == 0)
             {
                 if (Main.mouseItem.stack == 1)
                 {
                     Utils.Swap(ref inv[slot], ref Main.mouseItem);
                     if (inv[slot].type == 0 || inv[slot].stack < 1)
                     {
                         inv[slot] = new Item();
                     }
                     if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
                     {
                         Main.mouseItem = new Item();
                     }
                     if (Main.mouseItem.type > 0 || inv[slot].type > 0)
                     {
                         Recipe.FindRecipes();
                         SoundEngine.PlaySound(7);
                     }
                 }
                 else
                 {
                     Main.mouseItem.stack--;
                     inv[slot].SetDefaults(Main.mouseItem.type);
                     Recipe.FindRecipes();
                     SoundEngine.PlaySound(7);
                 }
                 if (inv[slot].stack > 0)
                 {
                     switch (context)
                     {
                     case 0:
                         AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                         break;
                     case 8:
                     case 9:
                     case 10:
                     case 11:
                     case 12:
                     case 16:
                     case 17:
                     case 25:
                     case 27:
                     case 33:
                         AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                         break;
                     }
                 }
             }
             if (context == 25 && Main.netMode == 1)
             {
                 NetMessage.SendData(121, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot, 1f);
             }
             if (context == 27 && Main.netMode == 1)
             {
                 NetMessage.SendData(124, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot, 1f);
             }
             break;
         case 3:
             HandleShopSlot(inv, slot, rightClickIsValid: false, leftClickIsValid: true);
             break;
         case 4:
         {
             Chest chest = Main.instance.shop[Main.npcShop];
             if (player.SellItem(Main.mouseItem))
             {
                 chest.AddItemToShop(Main.mouseItem);
                 Main.mouseItem.SetDefaults();
                 SoundEngine.PlaySound(18);
                 AnnounceTransfer(new ItemTransferInfo(inv[slot], 21, 15));
             }
             else if (Main.mouseItem.value == 0)
             {
                 chest.AddItemToShop(Main.mouseItem);
                 Main.mouseItem.SetDefaults();
                 SoundEngine.PlaySound(7);
                 AnnounceTransfer(new ItemTransferInfo(inv[slot], 21, 15));
             }
             Recipe.FindRecipes();
             Main.stackSplit = 9999;
             break;
         }
         case 5:
             if (Main.mouseItem.IsAir)
             {
                 SoundEngine.PlaySound(7);
                 Main.mouseItem.SetDefaults(inv[slot].netID);
                 Main.mouseItem.stack = Main.mouseItem.maxStack;
                 Main.mouseItem.OnCreated(new JourneyDuplicationItemCreationContext());
                 AnnounceTransfer(new ItemTransferInfo(inv[slot], 29, 21));
             }
             break;
         }
         if ((uint)context > 2u && context != 5 && context != 32)
         {
             inv[slot].favorited = false;
         }
     }
References Chest.AddItemToShop(), AnnounceTransfer(), Player.chest, Item.dye, Item.favorited, Recipe.FindRecipes(), Item.FitsAccessoryVanitySlot, AchievementsHelper.HandleOnEquip(), HandleShopSlot(), Main.instance, PlayerInteractionAnchor.interactEntityID, Item.IsAir, Item.IsNotTheSameAs(), Item.IsTheSameAs(), Player.itemAnimation, Player.itemTime, LeftClick_SellOrTrash(), Item.maxStack, Main.mouseItem, Main.mouseLeft, Main.mouseLeftRelease, Main.myPlayer, Main.netMode, Item.newAndShiny, AchievementsHelper.NotifyItemPickup(), Main.npcShop, Item.OnCreated(), OverrideLeftClick(), PickItemMovementAction(), Main.player, SoundEngine.PlaySound(), Player.SellItem(), NetMessage.SendData(), Item.SetDefaults(), Main.shop, Item.stack, Main.stackSplit, Player.tileEntityAnchor, Item.type, and Item.value.