Terraria: ItemSlot.OverrideHover
OverrideHover() [1/2]
static void ItemSlot.OverrideHover (Item[] inv, int context = 0, int slot = 0) inline static
     {
         Item item = inv[slot];
         if (!PlayerInput.UsingGamepad)
         {
             UILinkPointNavigator.SuggestUsage(GetGamepadPointForSlot(inv, context, slot));
         }
         bool shiftForcedOn = ShiftForcedOn;
         if (NotUsingGamepad && Options.DisableLeftShiftTrashCan && !shiftForcedOn)
         {
             if (ControlInUse && !Options.DisableQuickTrash)
             {
                 if (item.type > 0 && item.stack > 0 && !inv[slot].favorited)
                 {
                     switch (context)
                     {
                     case 0:
                     case 1:
                     case 2:
                         if (Main.npcShop > 0 && !item.favorited)
{
                             Main.cursorOverride = 10;
                         }
                         else
{
                             Main.cursorOverride = 6;
                         }
                         break;
                     case 3:
                     case 4:
                     case 7:
                     case 32:
                         if (Main.player[Main.myPlayer].ItemSpace(item).CanTakeItemToPersonalInventory)
{
                             Main.cursorOverride = 6;
                         }
                         break;
                     }
                 }
             }
             else if (ShiftInUse)
             {
                 bool flag = false;
                 if (Main.LocalPlayer.tileEntityAnchor.IsInValidUseTileEntity())
                 {
                     flag = Main.LocalPlayer.tileEntityAnchor.GetTileEntity().OverrideItemSlotHover(inv, context, slot);
                 }
                 if (item.type > 0 && item.stack > 0 && !inv[slot].favorited && !flag)
                 {
                     switch (context)
                     {
                     case 0:
                         if (Main.CreativeMenu.IsShowingResearchMenu())
{
                             Main.cursorOverride = 9;
                             break;
                         }
                         goto case 1;
                     case 1:
                     case 2:
                         if (context == 0 && Main.InReforgeMenu)
{
                             if (item.maxStack == 1 && item.Prefix(-3))
{
                                 Main.cursorOverride = 9;
                             }
                         }
                         else if (context == 0 && Main.InGuideCraftMenu)
{
                             if (item.material)
{
                                 Main.cursorOverride = 9;
                             }
                         }
                         else if (Main.player[Main.myPlayer].chest != -1 && ChestUI.TryPlacingInChest(item, justCheck: true, context))
{
                             Main.cursorOverride = 9;
                         }
                         break;
                     case 3:
                     case 4:
                     case 32:
                         if (Main.player[Main.myPlayer].ItemSpace(item).CanTakeItemToPersonalInventory)
{
                             Main.cursorOverride = 8;
                         }
                         break;
                     case 5:
                     case 7:
                     case 8:
                     case 9:
                     case 10:
                     case 11:
                     case 12:
                     case 16:
                     case 17:
                     case 18:
                     case 19:
                     case 20:
                     case 23:
                     case 24:
                     case 25:
                     case 26:
                     case 27:
                     case 29:
                     case 33:
                         if (Main.player[Main.myPlayer].ItemSpace(inv[slot]).CanTakeItemToPersonalInventory)
{
                             Main.cursorOverride = 7;
                         }
                         break;
                     }
                 }
             }
         }
         else if (ShiftInUse)
         {
             bool flag2 = false;
             if (Main.LocalPlayer.tileEntityAnchor.IsInValidUseTileEntity())
             {
                 flag2 = Main.LocalPlayer.tileEntityAnchor.GetTileEntity().OverrideItemSlotHover(inv, context, slot);
             }
             if (item.type > 0 && item.stack > 0 && !inv[slot].favorited && !flag2)
             {
                 switch (context)
                 {
                 case 0:
                 case 1:
                 case 2:
                     if (Main.npcShop > 0 && !item.favorited)
                     {
                         if (!Options.DisableQuickTrash)
{
                             Main.cursorOverride = 10;
                         }
                     }
                     else if (context == 0 && Main.CreativeMenu.IsShowingResearchMenu())
                     {
                         Main.cursorOverride = 9;
                     }
                     else if (context == 0 && Main.InReforgeMenu)
                     {
                         if (item.maxStack == 1 && item.Prefix(-3))
{
                             Main.cursorOverride = 9;
                         }
                     }
                     else if (context == 0 && Main.InGuideCraftMenu)
                     {
                         if (item.material)
{
                             Main.cursorOverride = 9;
                         }
                     }
                     else if (Main.player[Main.myPlayer].chest != -1)
                     {
                         if (ChestUI.TryPlacingInChest(item, justCheck: true, context))
{
                             Main.cursorOverride = 9;
                         }
                     }
                     else if (!Options.DisableQuickTrash)
                     {
                         Main.cursorOverride = 6;
                     }
                     break;
                 case 3:
                 case 4:
                 case 32:
                     if (Main.player[Main.myPlayer].ItemSpace(item).CanTakeItemToPersonalInventory)
                     {
                         Main.cursorOverride = 8;
                     }
                     break;
                 case 5:
                 case 7:
                 case 8:
                 case 9:
                 case 10:
                 case 11:
                 case 12:
                 case 16:
                 case 17:
                 case 18:
                 case 19:
                 case 20:
                 case 23:
                 case 24:
                 case 25:
                 case 26:
                 case 27:
                 case 29:
                 case 33:
                     if (Main.player[Main.myPlayer].ItemSpace(inv[slot]).CanTakeItemToPersonalInventory)
                     {
                         Main.cursorOverride = 7;
                     }
                     break;
                 }
             }
         }
         if (Main.keyState.IsKeyDown(Main.FavoriteKey) && (canFavoriteAt[context] || (Main.drawingPlayerChat && canShareAt[context])))
         {
             if (item.type > 0 && item.stack > 0 && Main.drawingPlayerChat)
             {
                 Main.cursorOverride = 2;
             }
             else if (item.type > 0 && item.stack > 0)
             {
                 Main.cursorOverride = 3;
             }
         }
     }
References canFavoriteAt, canShareAt, Player.ItemSpaceStatus.CanTakeItemToPersonalInventory, Player.chest, ControlInUse, Main.CreativeMenu, Main.cursorOverride, ItemSlot.Options.DisableLeftShiftTrashCan, ItemSlot.Options.DisableQuickTrash, Main.drawingPlayerChat, Item.favorited, Main.FavoriteKey, GetGamepadPointForSlot(), PlayerInteractionAnchor.GetTileEntity(), Main.InGuideCraftMenu, Main.InReforgeMenu, PlayerInteractionAnchor.IsInValidUseTileEntity(), CreativeUI.IsShowingResearchMenu(), Player.ItemSpace(), Main.keyState, Main.LocalPlayer, Item.material, Item.maxStack, Main.myPlayer, NotUsingGamepad, Main.npcShop, TileEntity.OverrideItemSlotHover(), Main.player, Item.Prefix(), ShiftForcedOn, ShiftInUse, Item.stack, UILinkPointNavigator.SuggestUsage(), Player.tileEntityAnchor, ChestUI.TryPlacingInChest(), Item.type, and PlayerInput.UsingGamepad.