Terraria: ItemSlot.SwapVanityEquip
SwapVanityEquip()
static void ItemSlot.SwapVanityEquip (Item[] inv, int context, int slot, Player player) inline static private
     {
         if (Main.npcShop > 0 || ((inv[slot].type <= 0 || inv[slot].stack <= 0) && (inv[slot - 10].type <= 0 || inv[slot - 10].stack <= 0)))
         {
             return;
         }
         Item item = inv[slot - 10];
         bool flag = context != 11 || item.FitsAccessoryVanitySlot || item.IsAir;
         if (flag && context == 11 && inv[slot].wingSlot > 0)
         {
             for (int i = 3; i < 10; i++)
             {
                 if (inv[i].wingSlot > 0 && i != slot - 10)
                 {
                     flag = false;
                 }
             }
         }
         if (!flag)
         {
             return;
         }
         Utils.Swap(ref inv[slot], ref inv[slot - 10]);
         SoundEngine.PlaySound(7);
         Recipe.FindRecipes();
         if (inv[slot].stack > 0)
         {
             switch (context)
             {
             case 0:
                 AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                 break;
             case 8:
             case 9:
             case 10:
             case 11:
             case 12:
             case 16:
             case 17:
             case 25:
             case 27:
             case 33:
                 AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                 break;
             }
         }
     }
References Recipe.FindRecipes(), Item.FitsAccessoryVanitySlot, AchievementsHelper.HandleOnEquip(), Item.IsAir, AchievementsHelper.NotifyItemPickup(), Main.npcShop, SoundEngine.PlaySound(), Item.stack, and Item.type.
Referenced by RightClick().