Terraria: ItemSlot.SwapEquip
SwapEquip() [1/2]
static void ItemSlot.SwapEquip (Item[] inv, int context, int slot) inline static
     {
         Player player = Main.player[Main.myPlayer];
         if (isEquipLocked(inv[slot].type) || inv[slot].IsAir)
         {
             return;
         }
         bool success;
         if (inv[slot].dye > 0)
         {
             inv[slot] = DyeSwap(inv[slot], out success);
             if (success)
             {
                 Main.EquipPageSelected = 0;
                 AchievementsHelper.HandleOnEquip(player, inv[slot], 12);
             }
         }
         else if (Main.projHook[inv[slot].shoot])
         {
             inv[slot] = EquipSwap(inv[slot], player.miscEquips, 4, out success);
             if (success)
             {
                 Main.EquipPageSelected = 2;
                 AchievementsHelper.HandleOnEquip(player, inv[slot], 16);
             }
         }
         else if (inv[slot].mountType != -1 && !MountID.Sets.Cart[inv[slot].mountType])
         {
             inv[slot] = EquipSwap(inv[slot], player.miscEquips, 3, out success);
             if (success)
             {
                 Main.EquipPageSelected = 2;
                 AchievementsHelper.HandleOnEquip(player, inv[slot], 17);
             }
         }
         else if (inv[slot].mountType != -1 && MountID.Sets.Cart[inv[slot].mountType])
         {
             inv[slot] = EquipSwap(inv[slot], player.miscEquips, 2, out success);
             if (success)
             {
                 Main.EquipPageSelected = 2;
             }
         }
         else if (inv[slot].buffType > 0 && Main.lightPet[inv[slot].buffType])
         {
             inv[slot] = EquipSwap(inv[slot], player.miscEquips, 1, out success);
             if (success)
             {
                 Main.EquipPageSelected = 2;
             }
         }
         else if (inv[slot].buffType > 0 && Main.vanityPet[inv[slot].buffType])
         {
             inv[slot] = EquipSwap(inv[slot], player.miscEquips, 0, out success);
             if (success)
             {
                 Main.EquipPageSelected = 2;
             }
         }
         else
         {
             Item item = inv[slot];
             inv[slot] = ArmorSwap(inv[slot], out success);
             if (success)
             {
                 Main.EquipPageSelected = 0;
                 AchievementsHelper.HandleOnEquip(player, item, item.accessory ? 10 : 8);
             }
         }
         Recipe.FindRecipes();
         if (context == 3 && Main.netMode == 1)
         {
             NetMessage.SendData(32, -1, -1, null, player.chest, slot);
         }
     }
References Item.accessory, ArmorSwap(), Item.buffType, MountID.Sets.Cart, Player.chest, DyeSwap(), Main.EquipPageSelected, EquipSwap(), Recipe.FindRecipes(), AchievementsHelper.HandleOnEquip(), isEquipLocked(), Main.lightPet, Player.miscEquips, Item.mountType, Main.myPlayer, Main.netMode, Main.player, Main.projHook, NetMessage.SendData(), Item.shoot, and Main.vanityPet.