Terraria: ItemSlot.DrawMoney
DrawMoney()
static void ItemSlot.DrawMoney (SpriteBatch sb, string text, float shopx, float shopy, int[] coinsArray, bool horizontal = false) inline static
     {
         Utils.DrawBorderStringFourWay(sb, FontAssets.MouseText.Value, text, shopx, shopy + 40f, Color.White * ((float)(int)Main.mouseTextColor / 255f), Color.Black, Vector2.Zero);
         if (horizontal)
         {
             for (int i = 0; i < 4; i++)
             {
                 Main.instance.LoadItem(74 - i);
                 if (i == 0)
                 {
                     _ = coinsArray[3 - i];
                     _ = 99;
                 }
                 Vector2 position = new Vector2(shopx + ChatManager.GetStringSize(FontAssets.MouseText.Value, text, Vector2.One).X + (float)(24 * i) + 45f, shopy + 50f);
                 sb.Draw(TextureAssets.Item[74 - i].Value, position, null, Color.White, 0f, TextureAssets.Item[74 - i].Value.Size() / 2f, 1f, SpriteEffects.None, 0f);
                 Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, coinsArray[3 - i].ToString(), position.X - 11f, position.Y, Color.White, Color.Black, new Vector2(0.3f), 0.75f);
             }
         }
         else
         {
             for (int j = 0; j < 4; j++)
             {
                 Main.instance.LoadItem(74 - j);
                 int num = ((j == 0 && coinsArray[3 - j] > 99) ? (-6) : 0);
                 sb.Draw(TextureAssets.Item[74 - j].Value, new Vector2(shopx + 11f + (float)(24 * j), shopy + 75f), null, Color.White, 0f, TextureAssets.Item[74 - j].Value.Size() / 2f, 1f, SpriteEffects.None, 0f);
                 Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, coinsArray[3 - j].ToString(), shopx + (float)(24 * j) + (float)num, shopy + 75f, Color.White, Color.Black, new Vector2(0.3f), 0.75f);
             }
         }
     }
References Color, Utils.DrawBorderStringFourWay(), ChatManager.GetStringSize(), Main.instance, TextureAssets.Item, FontAssets.ItemStack, Main.LoadItem(), FontAssets.MouseText, Main.mouseTextColor, and Asset< T >.Value.
Referenced by DrawSavings(), Main.GUIChatDrawInner(), and CoinLossRevengeSystem.RevengeMarker.UseMouseOver().