Terraria: ItemSlot.TryEnteringFastUseMode
TryEnteringFastUseMode()
static bool ItemSlot.TryEnteringFastUseMode (Item[] inv, int context, int slot, Player player, ref string s) inline static private
     {
         int num = 0;
         if (Main.mouseItem.CanBeQuickUsed)
         {
             num = 1;
         }
         if (num == 0 && Main.mouseItem.stack <= 0 && context == 0 && inv[slot].CanBeQuickUsed)
         {
             num = 2;
         }
         if (num > 0)
         {
             s += PlayerInput.BuildCommand(Language.GetTextValue("UI.QuickUseItem"), false, PlayerInput.ProfileGamepadUI.KeyStatus["QuickMount"]);
             if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.QuickMount)
             {
                 switch (num)
                 {
                 case 1:
                     PlayerInput.TryEnteringFastUseModeForMouseItem();
                     break;
                 case 2:
                     PlayerInput.TryEnteringFastUseModeForInventorySlot(slot);
                     break;
                 }
             }
             return true;
         }
         return false;
     }
References PlayerInput.BuildCommand(), Item.CanBeQuickUsed, CanExecuteCommand(), Language.GetTextValue(), TriggersPack.JustPressed, KeyConfiguration.KeyStatus, Main.mouseItem, PlayerInput.ProfileGamepadUI, TriggersSet.QuickMount, Item.stack, PlayerInput.Triggers, PlayerInput.TryEnteringFastUseModeForInventorySlot(), and PlayerInput.TryEnteringFastUseModeForMouseItem().
Referenced by GetGamepadInstructions().