Terraria: ItemSlot.DrawRadialQuicks
DrawRadialQuicks()
static void ItemSlot.DrawRadialQuicks (SpriteBatch sb, Vector2 position) inline static
     {
         QuicksRadialOpacity = MathHelper.Clamp(QuicksRadialOpacity + ((PlayerInput.UsingGamepad && PlayerInput.Triggers.Current.RadialQuickbar) ? 0.25f : (-0.15f)), 0f, 1f);
         if (QuicksRadialOpacity == 0f)
         {
             return;
         }
         Player player = Main.player[Main.myPlayer];
         Texture2D value = TextureAssets.HotbarRadial[2].Value;
         Texture2D value2 = TextureAssets.QuicksIcon.Value;
         float num = QuicksRadialOpacity * 0.9f;
         float num2 = QuicksRadialOpacity * 1f;
         float num3 = (float)(int)Main.mouseTextColor / 255f;
         float num4 = 1f - (1f - num3) * (1f - num3);
         num4 *= 0.785f;
         Color color = Color.White * num4 * num;
         float num5 = (float)Math.PI * 2f / (float)player.QuicksRadial.RadialCount;
         float num6 = -(float)Math.PI / 2f;
         Item item = player.QuickHeal_GetItemToUse();
         Item item2 = player.QuickMana_GetItemToUse();
         Item item3 = null;
         Item item4 = null;
         if (item == null)
         {
             item = new Item();
             item.SetDefaults(28);
         }
         if (item2 == null)
         {
             item2 = new Item();
             item2.SetDefaults(110);
         }
         if (item3 == null)
         {
             item3 = new Item();
             item3.SetDefaults(292);
         }
         if (item4 == null)
         {
             item4 = new Item();
             item4.SetDefaults(2428);
         }
         for (int i = 0; i < player.QuicksRadial.RadialCount; i++)
         {
             Item inv = item4;
             if (i == 1)
             {
                 inv = item;
             }
             if (i == 2)
             {
                 inv = item3;
             }
             if (i == 3)
             {
                 inv = item2;
             }
             _ = player.QuicksRadial.Bindings[i];
             Vector2 vector = new Vector2(120f, 0f).RotatedBy(num6 + num5 * (float)i) * num2;
             float num7 = 0.85f;
             if (player.QuicksRadial.SelectedBinding == i)
             {
                 num7 = 1.7f;
             }
             sb.Draw(value, position + vector, null, color * num7, 0f, value.Size() / 2f, num2 * num7 * 1.3f, SpriteEffects.None, 0f);
             float inventoryScale = Main.inventoryScale;
             Main.inventoryScale = num2 * num7;
             Draw(sb, ref inv, 14, position + vector + new Vector2(-26f * num2 * num7), Color.White);
             Main.inventoryScale = inventoryScale;
             sb.Draw(value2, position + vector + new Vector2(34f, 20f) * 0.85f * num2 * num7, null, color * num7, 0f, value.Size() / 2f, num2 * num7 * 1.3f, SpriteEffects.None, 0f);
         }
     }
References Player.SelectionRadial.Bindings, Color, TriggersPack.Current, Draw(), TextureAssets.HotbarRadial, Main.inventoryScale, Main.mouseTextColor, Main.myPlayer, Main.player, Player.QuickHeal_GetItemToUse(), Player.QuickMana_GetItemToUse(), TextureAssets.QuicksIcon, Player.QuicksRadial, QuicksRadialOpacity, Player.SelectionRadial.RadialCount, TriggersSet.RadialQuickbar, Player.SelectionRadial.SelectedBinding, Item.SetDefaults(), PlayerInput.Triggers, PlayerInput.UsingGamepad, and Asset< T >.Value.
Referenced by Main.DrawInterface_32_GamepadRadialHotbars().