Terraria: ItemSlot.TryEnteringBuildingMode
TryEnteringBuildingMode()
static bool ItemSlot.TryEnteringBuildingMode (Item[] inv, int context, int slot, Player player, ref string s) inline static private
     {
         int num = 0;
         if (IsABuildingItem(Main.mouseItem))
         {
             num = 1;
         }
         if (num == 0 && Main.mouseItem.stack <= 0 && context == 0 && IsABuildingItem(inv[slot]))
         {
             num = 2;
         }
         if (num > 0)
         {
             Item item = Main.mouseItem;
             if (num == 1)
             {
                 item = Main.mouseItem;
             }
             if (num == 2)
             {
                 item = inv[slot];
             }
             if (num != 1 || player.ItemSpace(item).CanTakeItemToPersonalInventory)
             {
                 if (item.damage > 0 && item.ammo == 0)
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[60].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["QuickMount"]);
                 }
                 else if (item.createTile >= 0 || item.createWall > 0)
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[61].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["QuickMount"]);
                 }
                 else
                 {
                     s += PlayerInput.BuildCommand(Lang.misc[63].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["QuickMount"]);
                 }
                 if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.QuickMount)
                 {
                     PlayerInput.EnterBuildingMode();
                 }
                 return true;
             }
         }
         return false;
     }
References Item.ammo, PlayerInput.BuildCommand(), CanExecuteCommand(), Player.ItemSpaceStatus.CanTakeItemToPersonalInventory, Item.createTile, Item.createWall, Item.damage, PlayerInput.EnterBuildingMode(), IsABuildingItem(), Player.ItemSpace(), TriggersPack.JustPressed, KeyConfiguration.KeyStatus, Lang.misc, Main.mouseItem, PlayerInput.ProfileGamepadUI, TriggersSet.QuickMount, Item.stack, PlayerInput.Triggers, and LocalizedText.Value.
Referenced by GetGamepadInstructions().