Terraria: ItemSlot.TryItemSwap
TryItemSwap()
static void ItemSlot.TryItemSwap (Item item) inline static private
     {
         int type = item.type;
         switch (type)
         {
         case 4131:
         case 5325:
             item.ChangeItemType((item.type == 5325) ? 4131 : 5325);
             AfterItemSwap(type, item.type);
             break;
         case 5059:
         case 5060:
             item.ChangeItemType((item.type == 5059) ? 5060 : 5059);
             AfterItemSwap(type, item.type);
             break;
         case 5324:
             item.ChangeItemType(5329);
             AfterItemSwap(type, item.type);
             break;
         case 5329:
             item.ChangeItemType(5330);
             AfterItemSwap(type, item.type);
             break;
         case 5330:
             item.ChangeItemType(5324);
             AfterItemSwap(type, item.type);
             break;
         case 4346:
         case 5391:
             item.ChangeItemType((item.type == 4346) ? 5391 : 4346);
             AfterItemSwap(type, item.type);
             break;
         case 5323:
         case 5455:
             item.ChangeItemType((item.type == 5323) ? 5455 : 5323);
             AfterItemSwap(type, item.type);
             break;
         case 4767:
         case 5453:
             item.ChangeItemType((item.type == 4767) ? 5453 : 4767);
             AfterItemSwap(type, item.type);
             break;
         case 5309:
         case 5454:
             item.ChangeItemType((item.type == 5309) ? 5454 : 5309);
             AfterItemSwap(type, item.type);
             break;
         case 5358:
             item.ChangeItemType(5360);
             AfterItemSwap(type, item.type);
             break;
         case 5360:
             item.ChangeItemType(5361);
             AfterItemSwap(type, item.type);
             break;
         case 5361:
             item.ChangeItemType(5359);
             AfterItemSwap(type, item.type);
             break;
         case 5359:
             item.ChangeItemType(5358);
             AfterItemSwap(type, item.type);
             break;
         case 5437:
             item.ChangeItemType(5358);
             AfterItemSwap(type, item.type);
             break;
         }
     }
References AfterItemSwap(), Item.ChangeItemType(), and Item.type.
Referenced by RightClick().