Terraria: ItemSlot.HandleShopSlot
HandleShopSlot()
static void ItemSlot.HandleShopSlot (Item[] inv, int slot, bool rightClickIsValid, bool leftClickIsValid) inline static private
     {
         if (Main.cursorOverride == 2)
         {
             return;
         }
         _ = Main.instance.shop[Main.npcShop];
         bool flag = (Main.mouseRight && rightClickIsValid) || (Main.mouseLeft && leftClickIsValid);
         if (!(Main.stackSplit <= 1 && flag) || inv[slot].type <= 0 || (!Main.mouseItem.IsTheSameAs(inv[slot]) && Main.mouseItem.type != 0))
         {
             return;
         }
         int num = Main.superFastStack + 1;
         Player localPlayer = Main.LocalPlayer;
         for (int i = 0; i < num; i++)
         {
             if (Main.mouseItem.stack >= Main.mouseItem.maxStack && Main.mouseItem.type != 0)
             {
                 continue;
             }
             localPlayer.GetItemExpectedPrice(inv[slot], out var _, out var calcForBuying);
             if (!localPlayer.BuyItem(calcForBuying, inv[slot].shopSpecialCurrency) || inv[slot].stack <= 0)
             {
                 continue;
             }
             if (i == 0)
             {
                 if (inv[slot].value > 0)
                 {
                     SoundEngine.PlaySound(18);
                 }
                 else
                 {
                     SoundEngine.PlaySound(7);
                 }
             }
             if (Main.mouseItem.type == 0)
             {
                 Main.mouseItem.netDefaults(inv[slot].netID);
                 if (inv[slot].prefix != 0)
                 {
                     Main.mouseItem.Prefix(inv[slot].prefix);
                 }
                 Main.mouseItem.stack = 0;
             }
             if (!inv[slot].buyOnce)
             {
                 Main.shopSellbackHelper.Add(inv[slot]);
             }
             Main.mouseItem.stack++;
             RefreshStackSplitCooldown();
             if (inv[slot].buyOnce && --inv[slot].stack <= 0)
             {
                 inv[slot].SetDefaults();
             }
             AnnounceTransfer(new ItemTransferInfo(Main.mouseItem, 15, 21));
         }
     }
References ItemShopSellbackHelper.Add(), AnnounceTransfer(), Player.BuyItem(), Main.cursorOverride, Player.GetItemExpectedPrice(), Main.instance, Item.IsTheSameAs(), Main.LocalPlayer, Item.maxStack, Main.mouseItem, Main.mouseLeft, Main.mouseRight, Item.netDefaults(), Main.npcShop, SoundEngine.PlaySound(), Item.Prefix(), RefreshStackSplitCooldown(), Item.SetDefaults(), Main.shop, Main.shopSellbackHelper, Item.shopSpecialCurrency, Item.stack, Main.stackSplit, Main.superFastStack, and Item.type.
Referenced by LeftClick(), and RightClick().