Terraria: ItemSlot.DyeSwap
DyeSwap()
static Item ItemSlot.DyeSwap (Item item, out bool success) inline static private
     {
         success = false;
         if (item.dye <= 0)
         {
             return item;
         }
         Player player = Main.player[Main.myPlayer];
         Item item2 = item;
         for (int i = 0; i < 10; i++)
         {
             if (player.dye[i].type == 0)
             {
                 dyeSlotCount = i;
                 break;
             }
         }
         if (dyeSlotCount >= 10)
         {
             dyeSlotCount = 0;
         }
         if (dyeSlotCount < 0)
         {
             dyeSlotCount = 9;
         }
         item2 = player.dye[dyeSlotCount].Clone();
         player.dye[dyeSlotCount] = item.Clone();
         dyeSlotCount++;
         if (dyeSlotCount >= 10)
         {
             accSlotToSwapTo = 0;
         }
         SoundEngine.PlaySound(7);
         Recipe.FindRecipes();
         success = true;
         return item2;
     }
References accSlotToSwapTo, Item.Clone(), Item.dye, Player.dye, dyeSlotCount, Recipe.FindRecipes(), Main.myPlayer, Main.player, SoundEngine.PlaySound(), and Item.type.
Referenced by SwapEquip().