Terraria: ItemSlot.DrawSavings
DrawSavings()
static void ItemSlot.DrawSavings (SpriteBatch sb, float shopx, float shopy, bool horizontal = false) inline static
     {
         Player player = Main.player[Main.myPlayer];
         if (_customCurrencyForSavings != -1)
         {
             CustomCurrencyManager.DrawSavings(sb, _customCurrencyForSavings, shopx, shopy, horizontal);
             return;
         }
         bool overFlowing;
         long num = Utils.CoinsCount(out overFlowing, player.bank.item);
         long num2 = Utils.CoinsCount(out overFlowing, player.bank2.item);
         long num3 = Utils.CoinsCount(out overFlowing, player.bank3.item);
         long num4 = Utils.CoinsCount(out overFlowing, player.bank4.item);
         long num5 = Utils.CoinsCombineStacks(out overFlowing, num, num2, num3, num4);
         if (num5 > 0)
         {
             Main.GetItemDrawFrame(4076, out var itemTexture, out var itemFrame);
             Main.GetItemDrawFrame(3813, out var itemTexture2, out var itemFrame2);
             Main.GetItemDrawFrame(346, out var itemTexture3, out var _);
             Main.GetItemDrawFrame(87, out var itemTexture4, out var _);
             if (num4 > 0)
             {
                 sb.Draw(itemTexture, Utils.CenteredRectangle(new Vector2(shopx + 92f, shopy + 45f), itemFrame.Size() * 0.65f), null, Color.White);
             }
             if (num3 > 0)
             {
                 sb.Draw(itemTexture2, Utils.CenteredRectangle(new Vector2(shopx + 92f, shopy + 45f), itemFrame2.Size() * 0.65f), null, Color.White);
             }
             if (num2 > 0)
             {
                 sb.Draw(itemTexture3, Utils.CenteredRectangle(new Vector2(shopx + 80f, shopy + 50f), itemTexture3.Size() * 0.65f), null, Color.White);
             }
             if (num > 0)
             {
                 sb.Draw(itemTexture4, Utils.CenteredRectangle(new Vector2(shopx + 70f, shopy + 60f), itemTexture4.Size() * 0.65f), null, Color.White);
             }
             DrawMoney(sb, Lang.inter[66].Value, shopx, shopy, Utils.CoinsSplit(num5), horizontal);
         }
     }
References _customCurrencyForSavings, Player.bank, Player.bank2, Player.bank3, Player.bank4, Utils.CenteredRectangle(), Utils.CoinsCombineStacks(), Utils.CoinsCount(), Utils.CoinsSplit(), Color, DrawMoney(), CustomCurrencyManager.DrawSavings(), Main.GetItemDrawFrame(), Lang.inter, Chest.item, Main.myPlayer, Main.player, and LocalizedText.Value.
Referenced by Main.DrawHairWindow(), and Main.DrawInventory().