Terraria: ItemSlot.TryOpenContainer
TryOpenContainer()
static void ItemSlot.TryOpenContainer (Item item, Player player) inline static private
     {
         if (ItemID.Sets.BossBag[item.type])
         {
             player.OpenBossBag(item.type);
         }
         else if (ItemID.Sets.IsFishingCrate[item.type])
         {
             player.OpenFishingCrate(item.type);
         }
         else if (item.type == 3093)
         {
             player.OpenHerbBag(3093);
         }
         else if (item.type == 4345)
         {
             player.OpenCanofWorms(item.type);
         }
         else if (item.type == 4410)
         {
             player.OpenOyster(item.type);
         }
         else if (item.type == 1774)
         {
             player.OpenGoodieBag(1774);
         }
         else if (item.type == 3085)
         {
             if (!player.ConsumeItem(327, reverseOrder: false, includeVoidBag: true))
             {
                 return;
             }
             player.OpenLockBox(3085);
         }
         else if (item.type == 4879)
         {
             if (!player.HasItemInInventoryOrOpenVoidBag(329))
             {
                 return;
             }
             player.OpenShadowLockbox(4879);
         }
         else if (item.type == 1869)
         {
             player.OpenPresent(1869);
         }
         else
         {
             if (item.type != 599 && item.type != 600 && item.type != 601)
             {
                 return;
             }
             player.OpenLegacyPresent(item.type);
         }
         item.stack--;
         if (item.stack == 0)
         {
             item.SetDefaults();
         }
         SoundEngine.PlaySound(7);
         Main.stackSplit = 30;
         Main.mouseRightRelease = false;
         Recipe.FindRecipes();
     }
References ItemID.Sets.BossBag, Player.ConsumeItem(), Recipe.FindRecipes(), Player.HasItemInInventoryOrOpenVoidBag(), ItemID.Sets.IsFishingCrate, Main.mouseRightRelease, Player.OpenBossBag(), Player.OpenCanofWorms(), Player.OpenFishingCrate(), Player.OpenGoodieBag(), Player.OpenHerbBag(), Player.OpenLegacyPresent(), Player.OpenLockBox(), Player.OpenOyster(), Player.OpenPresent(), Player.OpenShadowLockbox(), SoundEngine.PlaySound(), Item.SetDefaults(), Item.stack, Main.stackSplit, and Item.type.
Referenced by RightClick().