Terraria: Terraria.GameContent.UI.Minimap.MinimapFrame.Button.IsTouchingPoint
IsTouchingPoint()
bool Terraria.GameContent.UI.Minimap.MinimapFrame.Button.IsTouchingPoint (Vector2 testPoint, Vector2 parentPosition) inline
Definition at line 46 of file MinimapFrame.cs.
        {
            Vector2 vector = _position + parentPosition + Size * 0.5f;
            Vector2 vector2 = Vector2.Max(Size, new Vector2(22f, 22f)) * 0.5f;
            Vector2 vector3 = testPoint - vector;
            if (Math.Abs(vector3.X) < vector2.X)
            {
                return Math.Abs(vector3.Y) < vector2.Y;
            }
            return false;
        }
References Terraria.GameContent.UI.Minimap.MinimapFrame.Button._position, System.Math.Abs(), Microsoft.Xna.Framework.Vector2.Max(), Terraria.GameContent.UI.Minimap.MinimapFrame.Button.Size, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.Minimap.MinimapFrame.GetButtonUnderMouse().