Terraria: Terraria.GameContent.UI.Elements.UIWorldListItem.SeedButtonClick
SeedButtonClick()
void Terraria.GameContent.UI.Elements.UIWorldListItem.SeedButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 396 of file UIWorldListItem.cs.
    {
        Platform.Get<IClipboard>().Value = _data.GetFullSeedText();
        _buttonLabel.SetText(Language.GetTextValue("UI.SeedCopied"));
    }
References Terraria.GameContent.UI.Elements.UIWorldListItem._buttonLabel, Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.IO.WorldFileData.GetFullSeedText(), Terraria.Localization.Language.GetTextValue(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem().