Terraria: Terraria.GameContent.UI.Elements.UIWorldListItem.CloudButtonClick
CloudButtonClick()
void Terraria.GameContent.UI.Elements.UIWorldListItem.CloudButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        if (_data.IsCloudSave)
        {
            _data.MoveToLocal();
        }
        else
        {
            _data.MoveToCloud();
        }
        ((UIImageButton)evt.Target).SetImage(_data.IsCloudSave ? _buttonCloudActiveTexture : _buttonCloudInactiveTexture);
        if (_data.IsCloudSave)
        {
            _buttonLabel.SetText(Language.GetTextValue("UI.MoveOffCloud"));
        }
        else
        {
            _buttonLabel.SetText(Language.GetTextValue("UI.MoveToCloud"));
        }
    }
References Terraria.GameContent.UI.Elements.UIWorldListItem._buttonCloudActiveTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonCloudInactiveTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonLabel, Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.Localization.Language.GetTextValue(), Terraria.IO.FileData.IsCloudSave, Terraria.IO.WorldFileData.MoveToCloud(), Terraria.IO.WorldFileData.MoveToLocal(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem().