Terraria: Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem
UIWorldListItem()
Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem (WorldFileData data, int orderInList, bool canBePlayed) inline
Definition at line 50 of file UIWorldListItem.cs.
    {
        _orderInList = orderInList;
        _data = data;
        _canBePlayed = canBePlayed;
        LoadTextures();
        InitializeAppearance();
        _worldIcon = GetIconElement();
        _worldIcon.OnLeftDoubleClick += PlayGame;
        Append(_worldIcon);
        if (_data.DefeatedMoonlord)
        {
            UIImage element = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/IconCompletion", (AssetRequestMode)1))
            {
                HAlign = 0.5f,
                VAlign = 0.5f,
                Top = new StyleDimension(-10f, 0f),
                Left = new StyleDimension(-3f, 0f),
                IgnoresMouseInteraction = true
            };
            _worldIcon.Append(element);
        }
        float num = 4f;
        UIImageButton uIImageButton = new UIImageButton(_buttonPlayTexture);
        uIImageButton.VAlign = 1f;
        uIImageButton.Left.Set(num, 0f);
        uIImageButton.OnLeftClick += PlayGame;
        base.OnLeftDoubleClick += PlayGame;
        uIImageButton.OnMouseOver += PlayMouseOver;
        uIImageButton.OnMouseOut += ButtonMouseOut;
        Append(uIImageButton);
        num += 24f;
        UIImageButton uIImageButton2 = new UIImageButton(_data.IsFavorite ? _buttonFavoriteActiveTexture : _buttonFavoriteInactiveTexture);
        uIImageButton2.VAlign = 1f;
        uIImageButton2.Left.Set(num, 0f);
        uIImageButton2.OnLeftClick += FavoriteButtonClick;
        uIImageButton2.OnMouseOver += FavoriteMouseOver;
        uIImageButton2.OnMouseOut += ButtonMouseOut;
        uIImageButton2.SetVisibility(1f, _data.IsFavorite ? 0.8f : 0.4f);
        Append(uIImageButton2);
        num += 24f;
        if (SocialAPI.Cloud != null)
        {
            UIImageButton uIImageButton3 = new UIImageButton(_data.IsCloudSave ? _buttonCloudActiveTexture : _buttonCloudInactiveTexture);
            uIImageButton3.VAlign = 1f;
            uIImageButton3.Left.Set(num, 0f);
            uIImageButton3.OnLeftClick += CloudButtonClick;
            uIImageButton3.OnMouseOver += CloudMouseOver;
            uIImageButton3.OnMouseOut += ButtonMouseOut;
            uIImageButton3.SetSnapPoint("Cloud", orderInList);
            Append(uIImageButton3);
            num += 24f;
        }
        if (_data.WorldGeneratorVersion != 0L)
        {
            UIImageButton uIImageButton4 = new UIImageButton(_buttonSeedTexture);
            uIImageButton4.VAlign = 1f;
            uIImageButton4.Left.Set(num, 0f);
            uIImageButton4.OnLeftClick += SeedButtonClick;
            uIImageButton4.OnMouseOver += SeedMouseOver;
            uIImageButton4.OnMouseOut += ButtonMouseOut;
            uIImageButton4.SetSnapPoint("Seed", orderInList);
            Append(uIImageButton4);
            num += 24f;
        }
        UIImageButton uIImageButton5 = new UIImageButton(_buttonRenameTexture);
        uIImageButton5.VAlign = 1f;
        uIImageButton5.Left.Set(num, 0f);
        uIImageButton5.OnLeftClick += RenameButtonClick;
        uIImageButton5.OnMouseOver += RenameMouseOver;
        uIImageButton5.OnMouseOut += ButtonMouseOut;
        uIImageButton5.SetSnapPoint("Rename", orderInList);
        Append(uIImageButton5);
        num += 24f;
        UIImageButton uIImageButton6 = new UIImageButton(_buttonDeleteTexture)
        {
            VAlign = 1f,
            HAlign = 1f
        };
        if (!_data.IsFavorite)
        {
            uIImageButton6.OnLeftClick += DeleteButtonClick;
        }
        uIImageButton6.OnMouseOver += DeleteMouseOver;
        uIImageButton6.OnMouseOut += DeleteMouseOut;
        _deleteButton = uIImageButton6;
        Append(uIImageButton6);
        num += 4f;
        _buttonLabel = new UIText("");
        _buttonLabel.VAlign = 1f;
        _buttonLabel.Left.Set(num, 0f);
        _buttonLabel.Top.Set(-3f, 0f);
        Append(_buttonLabel);
        _deleteButtonLabel = new UIText("");
        _deleteButtonLabel.VAlign = 1f;
        _deleteButtonLabel.HAlign = 1f;
        _deleteButtonLabel.Left.Set(-30f, 0f);
        _deleteButtonLabel.Top.Set(-3f, 0f);
        Append(_deleteButtonLabel);
        uIImageButton.SetSnapPoint("Play", orderInList);
        uIImageButton2.SetSnapPoint("Favorite", orderInList);
        uIImageButton5.SetSnapPoint("Rename", orderInList);
        uIImageButton6.SetSnapPoint("Delete", orderInList);
    }
References Terraria.GameContent.UI.Elements.UIWorldListItem._buttonCloudActiveTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonCloudInactiveTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonDeleteTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonFavoriteActiveTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonFavoriteInactiveTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonLabel, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonPlayTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonRenameTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonSeedTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._canBePlayed, Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.GameContent.UI.Elements.UIWorldListItem._deleteButton, Terraria.GameContent.UI.Elements.UIWorldListItem._deleteButtonLabel, Terraria.GameContent.UI.Elements.UIWorldListItem._orderInList, Terraria.GameContent.UI.Elements.UIWorldListItem._worldIcon, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIWorldListItem.ButtonMouseOut(), Terraria.Social.SocialAPI.Cloud, Terraria.GameContent.UI.Elements.UIWorldListItem.CloudButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.CloudMouseOver(), Terraria.IO.WorldFileData.DefeatedMoonlord, Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteMouseOut(), Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteMouseOver(), Terraria.GameContent.UI.Elements.AWorldListItem.GetIconElement(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.GameContent.UI.Elements.UIWorldListItem.InitializeAppearance(), Terraria.IO.FileData.IsCloudSave, Terraria.IO.FileData.IsFavorite, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIWorldListItem.LoadTextures(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayGame(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.SeedButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.SeedMouseOver(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.Elements.UIImageButton.SetVisibility(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.IO.WorldFileData.WorldGeneratorVersion.