Terraria: System.Runtime.Serialization.XPathQueryGenerator.ProcessClassDataContract
ProcessClassDataContract()
static DataContract System.Runtime.Serialization.XPathQueryGenerator.ProcessClassDataContract (ClassDataContract contract, ExportContext context, MemberInfo memberNode) inline static private
Definition at line 96 of file XPathQueryGenerator.cs.
    {
        string prefix = context.SetNamespace(contract.Namespace.Value);
        foreach (DataMember dataMember in GetDataMembers(contract))
        {
            if (dataMember.MemberInfo.Name == memberNode.Name && dataMember.MemberInfo.DeclaringType.IsAssignableFrom(memberNode.DeclaringType))
            {
                context.WriteChildToContext(dataMember, prefix);
                return dataMember.MemberTypeContract;
            }
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.QueryGeneratorPathToMemberNotFound));
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.XPathQueryGenerator.GetDataMembers(), System.prefix, System.SR.QueryGeneratorPathToMemberNotFound, System.Runtime.Serialization.XPathQueryGenerator.ExportContext.SetNamespace(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XPathQueryGenerator.ProcessDataContract().