Terraria: System.Net.Http.MessageProcessingHandler.SendAsync
SendAsync()
override Task< HttpResponseMessage > System.Net.Http.MessageProcessingHandler.SendAsync (HttpRequestMessage request, CancellationToken cancellationToken) inline sealed package
Definition at line 46 of file MessageProcessingHandler.cs.
    {
        if (request == null)
        {
            throw new ArgumentNullException("request", System.SR.net_http_handler_norequest);
        }
        SendState sendState = new SendState(this, cancellationToken);
        try
        {
            HttpRequestMessage request2 = ProcessRequest(request, cancellationToken);
            Task<HttpResponseMessage> task2 = base.SendAsync(request2, cancellationToken);
            task2.ContinueWith(delegate(Task<HttpResponseMessage> task, object state)
            {
                SendState sendState2 = (SendState)state;
                MessageProcessingHandler handler = sendState2._handler;
                CancellationToken token = sendState2._token;
                if (task.IsFaulted)
                {
                    sendState2.TrySetException(task.Exception.GetBaseException());
                }
                else if (task.IsCanceled)
                {
                    sendState2.TrySetCanceled(token);
                }
                else
                {
                    if (task.Result != null)
                    {
                        try
{
                            HttpResponseMessage result = handler.ProcessResponse(task.Result, token);
                            sendState2.TrySetResult(result);
                            return;
                        }
                        catch (OperationCanceledException e2)
{
                            HandleCanceledOperations(token, sendState2, e2);
                            return;
                        }
                        catch (Exception exception2)
{
                            sendState2.TrySetException(exception2);
                            return;
                        }
                    }
                    sendState2.TrySetException(ExceptionDispatchInfo.SetCurrentStackTrace(new InvalidOperationException(System.SR.net_http_handler_noresponse)));
                }
            }, sendState, CancellationToken.None, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
        }
        catch (OperationCanceledException e)
        {
            HandleCanceledOperations(cancellationToken, sendState, e);
        }
        catch (Exception exception)
        {
            sendState.TrySetException(exception);
        }
        return sendState.Task;
    }
References System.Net.Http.MessageProcessingHandler.SendState._handler, System.Net.Http.MessageProcessingHandler.SendState._token, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.TaskScheduler.Default, System.exception, System.Net.Http.MessageProcessingHandler.HandleCanceledOperations(), System.SR.net_http_handler_norequest, System.SR.net_http_handler_noresponse, System.Threading.CancellationToken.None, System.Net.Http.MessageProcessingHandler.ProcessRequest(), System.Net.Http.MessageProcessingHandler.ProcessResponse(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.state, System.Threading.Tasks.TaskCompletionSource< TResult >.Task, System.task, System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetCanceled(), System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetException(), and System.Threading.Tasks.TaskCompletionSource< TResult >.TrySetResult().