Terraria: System.Reflection.MethodInfo.MakeGenericMethod
MakeGenericMethod()
virtual MethodInfo System.Reflection.MethodInfo.MakeGenericMethod (params Type[] typeArguments) inline virtual inherited
Reimplemented in System.Reflection.Emit.MethodBuilderInstantiation, System.Reflection.RuntimeMethodInfo, System.Reflection.Emit.MethodOnTypeBuilderInstantiation, and System.Reflection.Emit.MethodBuilder.
Definition at line 41 of file MethodInfo.cs.
    {
        throw new NotSupportedException(SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Linq.EnumerableRewriter.FindMethod(), System.Dynamic.Utils.DelegateHelpers.GetCSharpThunk(), System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableDictionaryCreateRangeMethod(), and System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableEnumerableCreateRangeMethod().