Terraria: Terraria.ID.MountID.Sets.Cart
Cart
bool [] Terraria.ID.MountID.Sets.Cart = Factory.CreateBoolSet(6, 11, 13, 15, 16, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 38, 39, 51, 53) static
Referenced by Terraria.Mount.DoSpawnDust(), Terraria.ID.ContentSamples.CreativeHelper.GetItemGroup(), Terraria.Player.GrappleMovement(), Terraria.Player.JumpMovement(), Terraria.UI.ItemSlot.PickItemMovementAction(), Terraria.Player.QuickMount_GetItemToUse(), Terraria.Player.StickyMovement(), Terraria.UI.ItemSlot.SwapEquip(), Terraria.Player.TryInteractingWithMinecartTrackInNearbyArea(), and Terraria.Mount.UpdateEffects().