Terraria: System.Reflection.MethodInfo.CreateDelegate
CreateDelegate() [1/2]
virtual Delegate System.Reflection.MethodInfo.CreateDelegate (Type delegateType) inline virtual inherited
Reimplemented in System.Reflection.Emit.DynamicMethod, and System.Reflection.RuntimeMethodInfo.
Definition at line 48 of file MethodInfo.cs.
    {
        throw new NotSupportedException(SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Linq.Expressions.Interpreter.ActionCallInstruction< T0, T1, T2, T3 >.ActionCallInstruction(), System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute(), System.Linq.Expressions.Interpreter.FuncCallInstruction< T0, T1, T2, T3, TRet >.FuncCallInstruction(), System.Security.Cryptography.CryptoConfigForwarder.BindCreateFromName(), System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate(), System.Reflection.MethodInfo.CreateDelegate< T >(), System.Reflection.MethodInfo.CreateDelegate< T >(), System.Runtime.Serialization.SerializationGuard.CreateThrowIfDeserializationInProgressWithSwitchDelegate(), System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType< TObj, TParam >(), System.AppDomain.GetThreadPrincipal(), and System.Diagnostics.StackFrameHelper.InitializeSourceInfo().