Terraria: ContentSource.SetAssetNames
SetAssetNames()
void ContentSource.SetAssetNames (IEnumerable< string > paths) inline protected inherited
     {
         assetPaths = paths.ToArray();
         assetExtensions.Clear();
         string[] array = assetPaths;
         foreach (string obj in array)
         {
             string ext = Path.GetExtension(obj);
             string text = obj;
             int length = ext.Length;
             string name = AssetPathHelper.CleanPath(text.Substring(0, text.Length - length));
             if (assetExtensions.TryGetValue(name, out var ext2))
             {
                 throw new Exception($"Multiple extensions for asset {name}, ({ext}, {ext2})");
             }
             assetExtensions[name] = ext;
         }
     }
References ContentSource.assetExtensions, ContentSource.assetPaths, and AssetPathHelper.CleanPath().
Referenced by FileSystemContentSource.FileSystemContentSource(), XnaDirectContentSource.XnaDirectContentSource(), and BuildEntryList().