Terraria: JunglePass.ApplyPass
ApplyPass()
override void JunglePass.ApplyPass (GenerationProgress progress, GameConfiguration configuration) inline protected virtual
Implements GenPass.
     {
         progress.Message = Lang.gen[11].Value;
         _worldScale = (double)Main.maxTilesX / 4200.0 * 1.5;
         double worldScale = _worldScale;
         Point point = CreateStartPoint();
         int x = point.X;
         int y = point.Y;
         Point zero = Point.Zero;
         ApplyRandomMovement(ref x, ref y, 100, 100);
         zero.X += x;
         zero.Y += y;
         PlaceFirstPassMud(x, y, 3);
         PlaceGemsAt(x, y, 63, 2);
         progress.Set(0.15);
         ApplyRandomMovement(ref x, ref y, 250, 150);
         zero.X += x;
         zero.Y += y;
         PlaceFirstPassMud(x, y, 0);
         PlaceGemsAt(x, y, 65, 2);
         progress.Set(0.3);
         int oldX = x;
         int oldY = y;
         ApplyRandomMovement(ref x, ref y, 400, 150);
         zero.X += x;
         zero.Y += y;
         PlaceFirstPassMud(x, y, -3);
         PlaceGemsAt(x, y, 67, 2);
         progress.Set(0.45);
         x = zero.X / 3;
         y = zero.Y / 3;
         int num = GenBase._random.Next((int)(400.0 * worldScale), (int)(600.0 * worldScale));
         int num2 = (int)(25.0 * worldScale);
         x = Utils.Clamp(x, GenVars.leftBeachEnd + num / 2 + num2, GenVars.rightBeachStart - num / 2 - num2);
         GenVars.mudWall = true;
         WorldGen.TileRunner(x, y, num, 10000, 59, addTile: false, 0.0, -20.0, noYChange: true);
         GenerateTunnelToSurface(x, y);
         GenVars.mudWall = false;
         progress.Set(0.6);
         GenerateHolesInMudWalls();
         GenerateFinishingTouches(progress, oldX, oldY);
     }
References GenBase._random, _worldScale, ApplyRandomMovement(), CreateStartPoint(), Lang.gen, GenerateFinishingTouches(), GenerateHolesInMudWalls(), GenerateTunnelToSurface(), GenVars.leftBeachEnd, Main.maxTilesX, GenerationProgress.Message, GenVars.mudWall, UnifiedRandom.Next(), PlaceFirstPassMud(), PlaceGemsAt(), GenVars.rightBeachStart, GenerationProgress.Set(), WorldGen.TileRunner(), and LocalizedText.Value.