Terraria: ContentSamples.Initialize
Initialize()
static void ContentSamples.Initialize () inline static
     {
         NpcsByNetId.Clear();
         NpcNetIdsByPersistentIds.Clear();
         NpcPersistentIdsByNetIds.Clear();
         NpcBestiarySortingId.Clear();
         for (int i = -65; i < NPCID.Count; i++)
         {
             NPC nPC = new NPC();
             nPC.SetDefaults(i);
             NpcsByNetId[i] = nPC;
             string name = NPCID.Search.GetName(nPC.netID);
             NpcPersistentIdsByNetIds[i] = name;
             NpcBestiaryCreditIdsByNpcNetIds[i] = name;
             NpcNetIdsByPersistentIds[name] = i;
         }
         ModifyNPCIds();
         ProjectilesByType.Clear();
         for (int j = 0; j < ProjectileID.Count; j++)
         {
             Projectile projectile = new Projectile();
             projectile.SetDefaults(j);
             ProjectilesByType[j] = projectile;
         }
         ItemsByType.Clear();
         for (int k = 0; k < ItemID.Count; k++)
         {
             Item item = new Item();
             item.SetDefaults(k);
             ItemsByType[k] = item;
             string name2 = ItemID.Search.GetName(item.netID);
             ItemPersistentIdsByNetIds[k] = name2;
             ItemNetIdsByPersistentIds[name2] = k;
         }
         foreach (int item3 in ItemID.Sets.ItemsThatAreProcessedAfterNormalContentSample)
         {
             Item item2 = new Item();
             item2.SetDefaults(item3);
             ItemsByType[item3] = item2;
             string name3 = ItemID.Search.GetName(item2.netID);
             ItemPersistentIdsByNetIds[item3] = name3;
             ItemNetIdsByPersistentIds[name3] = item3;
         }
         FillResearchItemOverrides();
         FillNpcRarities();
     }
References ItemID.Count, NPCID.Count, ProjectileID.Count, FillNpcRarities(), FillResearchItemOverrides(), IdDictionary.GetName(), ItemNetIdsByPersistentIds, ItemPersistentIdsByNetIds, ItemsByType, ItemID.Sets.ItemsThatAreProcessedAfterNormalContentSample, ModifyNPCIds(), Item.netID, NPC.netID, NPC, NpcBestiaryCreditIdsByNpcNetIds, NpcBestiarySortingId, NpcNetIdsByPersistentIds, NpcPersistentIdsByNetIds, NpcsByNetId, ProjectilesByType, ItemID.Search, NPCID.Search, Projectile.SetDefaults(), NPC.SetDefaults(), and Item.SetDefaults().
Referenced by Main.Initialize().