Terraria: MapHelper.GetTileBaseOption
GetTileBaseOption()
static void MapHelper.GetTileBaseOption (int x, int y, int tileType, Tile tileCache, ref int baseOption) inline static
     {
         switch (tileType)
         {
         case 89:
             switch (tileCache.frameX / 54)
             {
             case 0:
             case 21:
             case 23:
                 baseOption = 0;
                 break;
             case 43:
                 baseOption = 2;
                 break;
             default:
                 baseOption = 1;
                 break;
             }
             break;
         case 160:
         case 627:
         case 628:
         case 692:
             baseOption = (x + y) % 9;
             break;
         case 461:
             if (Main.player[Main.myPlayer].ZoneCorrupt)
             {
                 baseOption = 1;
             }
             else if (Main.player[Main.myPlayer].ZoneCrimson)
             {
                 baseOption = 2;
             }
             else if (Main.player[Main.myPlayer].ZoneHallow)
             {
                 baseOption = 3;
             }
             break;
         case 80:
         {
             WorldGen.GetCactusType(x, y, tileCache.frameX, tileCache.frameY, out var evil, out var good, out var crimson);
             if (evil)
             {
                 baseOption = 1;
             }
             else if (good)
             {
                 baseOption = 2;
             }
             else if (crimson)
             {
                 baseOption = 3;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         }
         case 529:
         {
             int num2 = y + 1;
             WorldGen.GetBiomeInfluence(x, x, num2, num2, out var corruptCount, out var crimsonCount, out var hallowedCount);
             int num3 = corruptCount;
             if (num3 < crimsonCount)
             {
                 num3 = crimsonCount;
             }
             if (num3 < hallowedCount)
             {
                 num3 = hallowedCount;
             }
             int num4 = 0;
             num4 = ((corruptCount == 0 && crimsonCount == 0 && hallowedCount == 0) ? ((x < WorldGen.beachDistance || x > Main.maxTilesX - WorldGen.beachDistance) ? 1 : 0) : ((hallowedCount == num3) ? 2 : ((crimsonCount != num3) ? 4 : 3)));
             baseOption = num4;
             break;
         }
         case 530:
         {
             int num8 = y - tileCache.frameY % 36 / 18 + 2;
             int num9 = x - tileCache.frameX % 54 / 18;
             WorldGen.GetBiomeInfluence(num9, num9 + 3, num8, num8, out var corruptCount2, out var crimsonCount2, out var hallowedCount2);
             int num10 = corruptCount2;
             if (num10 < crimsonCount2)
             {
                 num10 = crimsonCount2;
             }
             if (num10 < hallowedCount2)
             {
                 num10 = hallowedCount2;
             }
             int num11 = 0;
             num11 = ((corruptCount2 != 0 || crimsonCount2 != 0 || hallowedCount2 != 0) ? ((hallowedCount2 == num10) ? 1 : ((crimsonCount2 != num10) ? 3 : 2)) : 0);
             baseOption = num11;
             break;
         }
         case 19:
         {
             int num6 = tileCache.frameY / 18;
             baseOption = 0;
             if (num6 == 48)
             {
                 baseOption = 1;
             }
             break;
         }
         case 15:
         {
             int num13 = tileCache.frameY / 40;
             baseOption = 0;
             if (num13 == 1 || num13 == 20)
             {
                 baseOption = 1;
             }
             break;
         }
         case 518:
         case 519:
             baseOption = tileCache.frameY / 18;
             break;
         case 4:
             if (tileCache.frameX < 66)
             {
                 baseOption = 1;
             }
             baseOption = 0;
             break;
         case 572:
             baseOption = tileCache.frameY / 36;
             break;
         case 21:
         case 441:
             switch (tileCache.frameX / 36)
             {
             case 1:
             case 2:
             case 10:
             case 13:
             case 15:
                 baseOption = 1;
                 break;
             case 3:
             case 4:
                 baseOption = 2;
                 break;
             case 6:
                 baseOption = 3;
                 break;
             case 11:
             case 17:
                 baseOption = 4;
                 break;
             default:
                 baseOption = 0;
                 break;
             }
             break;
         case 467:
         case 468:
         {
             int num = tileCache.frameX / 36;
             switch (num)
             {
             case 0:
             case 1:
             case 2:
             case 3:
             case 4:
             case 5:
             case 6:
             case 7:
             case 8:
             case 9:
             case 10:
             case 11:
                 baseOption = num;
                 break;
             case 12:
             case 13:
                 baseOption = 10;
                 break;
             case 14:
                 baseOption = 0;
                 break;
             case 15:
                 baseOption = 10;
                 break;
             case 16:
                 baseOption = 3;
                 break;
             default:
                 baseOption = 0;
                 break;
             }
             break;
         }
         case 560:
         {
             int num = tileCache.frameX / 36;
             if ((uint)num <= 2u)
             {
                 baseOption = num;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         }
         case 28:
         case 653:
             if (tileCache.frameY < 144)
             {
                 baseOption = 0;
             }
             else if (tileCache.frameY < 252)
             {
                 baseOption = 1;
             }
             else if (tileCache.frameY < 360 || (tileCache.frameY > 900 && tileCache.frameY < 1008))
             {
                 baseOption = 2;
             }
             else if (tileCache.frameY < 468)
             {
                 baseOption = 3;
             }
             else if (tileCache.frameY < 576)
             {
                 baseOption = 4;
             }
             else if (tileCache.frameY < 684)
             {
                 baseOption = 5;
             }
             else if (tileCache.frameY < 792)
             {
                 baseOption = 6;
             }
             else if (tileCache.frameY < 898)
             {
                 baseOption = 8;
             }
             else if (tileCache.frameY < 1006)
             {
                 baseOption = 7;
             }
             else if (tileCache.frameY < 1114)
             {
                 baseOption = 0;
             }
             else if (tileCache.frameY < 1222)
             {
                 baseOption = 3;
             }
             else
             {
                 baseOption = 7;
             }
             break;
         case 27:
             if (tileCache.frameY < 34)
             {
                 baseOption = 1;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         case 31:
             if (tileCache.frameX >= 36)
             {
                 baseOption = 1;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         case 26:
             if (tileCache.frameX >= 54)
             {
                 baseOption = 1;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         case 137:
             switch (tileCache.frameY / 18)
             {
             default:
                 baseOption = 0;
                 break;
             case 1:
             case 2:
             case 3:
             case 4:
                 baseOption = 1;
                 break;
             case 5:
                 baseOption = 2;
                 break;
             }
             break;
         case 82:
         case 83:
         case 84:
             if (tileCache.frameX < 18)
             {
                 baseOption = 0;
             }
             else if (tileCache.frameX < 36)
             {
                 baseOption = 1;
             }
             else if (tileCache.frameX < 54)
             {
                 baseOption = 2;
             }
             else if (tileCache.frameX < 72)
             {
                 baseOption = 3;
             }
             else if (tileCache.frameX < 90)
             {
                 baseOption = 4;
             }
             else if (tileCache.frameX < 108)
             {
                 baseOption = 5;
             }
             else
             {
                 baseOption = 6;
             }
             break;
         case 591:
             baseOption = tileCache.frameX / 36;
             break;
         case 105:
             if (tileCache.frameX >= 1548 && tileCache.frameX <= 1654)
             {
                 baseOption = 1;
             }
             else if (tileCache.frameX >= 1656 && tileCache.frameX <= 1798)
             {
                 baseOption = 2;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         case 133:
             if (tileCache.frameX < 52)
             {
                 baseOption = 0;
             }
             else
             {
                 baseOption = 1;
             }
             break;
         case 134:
             if (tileCache.frameX < 28)
             {
                 baseOption = 0;
             }
             else
             {
                 baseOption = 1;
             }
             break;
         case 149:
             baseOption = y % 3;
             break;
         case 165:
             if (tileCache.frameX < 54)
             {
                 baseOption = 0;
             }
             else if (tileCache.frameX < 106)
             {
                 baseOption = 1;
             }
             else if (tileCache.frameX >= 216)
             {
                 baseOption = 1;
             }
             else if (tileCache.frameX < 162)
             {
                 baseOption = 2;
             }
             else
             {
                 baseOption = 3;
             }
             break;
         case 178:
             if (tileCache.frameX < 18)
             {
                 baseOption = 0;
             }
             else if (tileCache.frameX < 36)
             {
                 baseOption = 1;
             }
             else if (tileCache.frameX < 54)
             {
                 baseOption = 2;
             }
             else if (tileCache.frameX < 72)
             {
                 baseOption = 3;
             }
             else if (tileCache.frameX < 90)
             {
                 baseOption = 4;
             }
             else if (tileCache.frameX < 108)
             {
                 baseOption = 5;
             }
             else
             {
                 baseOption = 6;
             }
             break;
         case 184:
             if (tileCache.frameX < 22)
             {
                 baseOption = 0;
             }
             else if (tileCache.frameX < 44)
             {
                 baseOption = 1;
             }
             else if (tileCache.frameX < 66)
             {
                 baseOption = 2;
             }
             else if (tileCache.frameX < 88)
             {
                 baseOption = 3;
             }
             else if (tileCache.frameX < 110)
             {
                 baseOption = 4;
             }
             else if (tileCache.frameX < 132)
             {
                 baseOption = 5;
             }
             else if (tileCache.frameX < 154)
             {
                 baseOption = 6;
             }
             else if (tileCache.frameX < 176)
             {
                 baseOption = 7;
             }
             else if (tileCache.frameX < 198)
             {
                 baseOption = 8;
             }
             else if (tileCache.frameX < 220)
             {
                 baseOption = 9;
             }
             else if (tileCache.frameX < 242)
             {
                 baseOption = 10;
             }
             break;
         case 650:
         {
             int num = tileCache.frameX / 36;
             int num12 = tileCache.frameY / 18 - 1;
             num += num12 * 18;
             if (num < 6 || num == 19 || num == 20 || num == 21 || num == 22 || num == 23 || num == 24 || num == 33 || num == 38 || num == 39 || num == 40)
             {
                 baseOption = 0;
             }
             else if (num < 16)
             {
                 baseOption = 2;
             }
             else if (num < 19 || num == 31 || num == 32)
             {
                 baseOption = 1;
             }
             else if (num < 31)
             {
                 baseOption = 3;
             }
             else if (num < 38)
             {
                 baseOption = 4;
             }
             else if (num < 59)
             {
                 baseOption = 0;
             }
             else if (num < 62)
             {
                 baseOption = 1;
             }
             break;
         }
         case 649:
         {
             int num = tileCache.frameX / 18;
             if (num < 6 || num == 28 || num == 29 || num == 30 || num == 31 || num == 32)
             {
                 baseOption = 0;
             }
             else if (num < 12 || num == 33 || num == 34 || num == 35)
             {
                 baseOption = 1;
             }
             else if (num < 28)
             {
                 baseOption = 2;
             }
             else if (num < 48)
             {
                 baseOption = 3;
             }
             else if (num < 54)
             {
                 baseOption = 4;
             }
             else if (num < 72)
             {
                 baseOption = 0;
             }
             else if (num == 72)
             {
                 baseOption = 1;
             }
             break;
         }
         case 185:
         {
             int num;
             if (tileCache.frameY < 18)
             {
                 num = tileCache.frameX / 18;
                 if (num < 6 || num == 28 || num == 29 || num == 30 || num == 31 || num == 32)
                 {
                     baseOption = 0;
                 }
                 else if (num < 12 || num == 33 || num == 34 || num == 35)
                 {
                     baseOption = 1;
                 }
                 else if (num < 28)
                 {
                     baseOption = 2;
                 }
                 else if (num < 48)
                 {
                     baseOption = 3;
                 }
                 else if (num < 54)
                 {
                     baseOption = 4;
                 }
                 else if (num < 72)
                 {
                     baseOption = 0;
                 }
                 else if (num == 72)
                 {
                     baseOption = 1;
                 }
                 break;
             }
             num = tileCache.frameX / 36;
             int num7 = tileCache.frameY / 18 - 1;
             num += num7 * 18;
             if (num < 6 || num == 19 || num == 20 || num == 21 || num == 22 || num == 23 || num == 24 || num == 33 || num == 38 || num == 39 || num == 40)
             {
                 baseOption = 0;
             }
             else if (num < 16)
             {
                 baseOption = 2;
             }
             else if (num < 19 || num == 31 || num == 32)
             {
                 baseOption = 1;
             }
             else if (num < 31)
             {
                 baseOption = 3;
             }
             else if (num < 38)
             {
                 baseOption = 4;
             }
             else if (num < 59)
             {
                 baseOption = 0;
             }
             else if (num < 62)
             {
                 baseOption = 1;
             }
             break;
         }
         case 186:
         case 647:
         {
             int num = tileCache.frameX / 54;
             if (num < 7)
             {
                 baseOption = 2;
             }
             else if (num < 22 || num == 33 || num == 34 || num == 35)
             {
                 baseOption = 0;
             }
             else if (num < 25)
             {
                 baseOption = 1;
             }
             else if (num == 25)
             {
                 baseOption = 5;
             }
             else if (num < 32)
             {
                 baseOption = 3;
             }
             break;
         }
         case 187:
         case 648:
         {
             int num = tileCache.frameX / 54;
             int num5 = tileCache.frameY / 36;
             num += num5 * 36;
             if (num < 3 || num == 14 || num == 15 || num == 16)
             {
                 baseOption = 0;
             }
             else if (num < 6)
             {
                 baseOption = 6;
             }
             else if (num < 9)
             {
                 baseOption = 7;
             }
             else if (num < 14)
             {
                 baseOption = 4;
             }
             else if (num < 18)
             {
                 baseOption = 4;
             }
             else if (num < 23)
             {
                 baseOption = 8;
             }
             else if (num < 25)
             {
                 baseOption = 0;
             }
             else if (num < 29)
             {
                 baseOption = 1;
             }
             else if (num < 47)
             {
                 baseOption = 0;
             }
             else if (num < 50)
             {
                 baseOption = 1;
             }
             else if (num < 52)
             {
                 baseOption = 10;
             }
             else if (num < 55)
             {
                 baseOption = 2;
             }
             break;
         }
         case 227:
             baseOption = tileCache.frameX / 34;
             break;
         case 129:
             if (tileCache.frameX >= 324)
             {
                 baseOption = 1;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         case 240:
         {
             int num = tileCache.frameX / 54;
             int num14 = tileCache.frameY / 54;
             num += num14 * 36;
             if ((num < 0 || num > 11) && (num < 47 || num > 53))
             {
                 switch (num)
                 {
                 case 72:
                 case 73:
                 case 75:
                     break;
                 case 12:
                 case 13:
                 case 14:
                 case 15:
                     baseOption = 1;
                     return;
                 default:
                     switch (num)
                     {
                     case 16:
                     case 17:
                         baseOption = 2;
                         break;
                     default:
                         if (num < 63 || num > 71)
{
                             switch (num)
{
                             case 74:
                             case 76:
                             case 77:
                             case 78:
                             case 79:
                             case 80:
                             case 81:
                             case 82:
                             case 83:
                             case 84:
                             case 85:
                             case 86:
                             case 87:
                             case 88:
                             case 89:
                             case 90:
                             case 91:
                             case 92:
                                 break;
                             default:
                                 if (num >= 41 && num <= 45)
{
                                     baseOption = 3;
                                 }
                                 else if (num == 46)
{
                                     baseOption = 4;
                                 }
                                 return;
                             }
                         }
                         goto case 18;
                     case 18:
                     case 19:
                     case 20:
                     case 21:
                     case 22:
                     case 23:
                     case 24:
                     case 25:
                     case 26:
                     case 27:
                     case 28:
                     case 29:
                     case 30:
                     case 31:
                     case 32:
                     case 33:
                     case 34:
                     case 35:
                         baseOption = 1;
                         break;
                     }
                     return;
                 }
             }
             baseOption = 0;
             break;
         }
         case 242:
         {
             int num = tileCache.frameY / 72;
             if (tileCache.frameX / 106 == 0 && num >= 22 && num <= 24)
             {
                 baseOption = 1;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         }
         case 440:
         {
             int num = tileCache.frameX / 54;
             if (num > 6)
             {
                 num = 6;
             }
             baseOption = num;
             break;
         }
         case 457:
         {
             int num = tileCache.frameX / 36;
             if (num > 4)
             {
                 num = 4;
             }
             baseOption = num;
             break;
         }
         case 453:
         {
             int num = tileCache.frameX / 36;
             if (num > 2)
             {
                 num = 2;
             }
             baseOption = num;
             break;
         }
         case 419:
         {
             int num = tileCache.frameX / 18;
             if (num > 2)
             {
                 num = 2;
             }
             baseOption = num;
             break;
         }
         case 428:
         {
             int num = tileCache.frameY / 18;
             if (num > 3)
             {
                 num = 3;
             }
             baseOption = num;
             break;
         }
         case 420:
         {
             int num = tileCache.frameY / 18;
             if (num > 5)
             {
                 num = 5;
             }
             baseOption = num;
             break;
         }
         case 423:
         {
             int num = tileCache.frameY / 18;
             if (num > 6)
             {
                 num = 6;
             }
             baseOption = num;
             break;
         }
         case 493:
             if (tileCache.frameX < 18)
             {
                 baseOption = 0;
             }
             else if (tileCache.frameX < 36)
             {
                 baseOption = 1;
             }
             else if (tileCache.frameX < 54)
             {
                 baseOption = 2;
             }
             else if (tileCache.frameX < 72)
             {
                 baseOption = 3;
             }
             else if (tileCache.frameX < 90)
             {
                 baseOption = 4;
             }
             else
             {
                 baseOption = 5;
             }
             break;
         case 548:
             if (tileCache.frameX / 54 < 7)
             {
                 baseOption = 0;
             }
             else
             {
                 baseOption = 1;
             }
             break;
         case 597:
         {
             int num = tileCache.frameX / 54;
             if ((uint)num <= 8u)
             {
                 baseOption = num;
             }
             else
             {
                 baseOption = 0;
             }
             break;
         }
         default:
             baseOption = 0;
             break;
         }
     }
References WorldGen.beachDistance, Tile.frameX, Tile.frameY, WorldGen.GetBiomeInfluence(), WorldGen.GetCactusType(), Main.maxTilesX, Main.myPlayer, Main.player, Player.ZoneCorrupt, Player.ZoneCrimson, and Player.ZoneHallow.
Referenced by CreateMapTile(), and Main.DrawInfoAccs().