Terraria: MapHelper.SaveMap
SaveMap()
static void MapHelper.SaveMap () inline static
     {
         if ((Main.ActivePlayerFileData.IsCloudSave && SocialAPI.Cloud == null) || !Main.mapEnabled || !Monitor.TryEnter(IOLock))
         {
             return;
         }
         try
         {
             FileUtilities.ProtectedInvoke(InternalSaveMap);
         }
         catch (Exception value)
         {
             using StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", append: true);
             streamWriter.WriteLine(DateTime.Now);
             streamWriter.WriteLine(value);
             streamWriter.WriteLine("");
         }
         finally
         {
             Monitor.Exit(IOLock);
         }
     }
References Main.ActivePlayerFileData, SocialAPI.Cloud, InternalSaveMap(), IOLock, FileData.IsCloudSave, Main.mapEnabled, and FileUtilities.ProtectedInvoke().
Referenced by WorldMap.Save().