Terraria: MapHelper.CreateMapTile
CreateMapTile()
static MapTile MapHelper.CreateMapTile (int i, int j, byte Light) inline static
     {
         Tile tile = Main.tile[i, j];
         if (tile == null)
         {
             return default(MapTile);
         }
         int num = 0;
         int num2 = Light;
         _ = Main.Map[i, j];
         int num3 = 0;
         int baseOption = 0;
         if (tile.active())
         {
             int num4 = tile.type;
             num3 = tileLookup[num4];
             bool flag = tile.invisibleBlock();
             if (tile.fullbrightBlock() && !flag)
             {
                 num2 = 255;
             }
             if (flag)
             {
                 num3 = 0;
             }
             else if (num4 == 5)
             {
                 if (WorldGen.IsThisAMushroomTree(i, j))
                 {
                     baseOption = 1;
                 }
                 num = tile.color();
             }
             else
             {
                 switch (num4)
                 {
                 case 51:
                     if ((i + j) % 2 == 0)
                     {
                         num3 = 0;
                     }
                     break;
                 case 19:
                     if (tile.frameY == 864)
                     {
                         num3 = 0;
                     }
                     break;
                 case 184:
                     if (tile.frameX / 22 == 10)
                     {
                         num4 = 627;
                         num3 = tileLookup[num4];
                     }
                     break;
                 }
                 if (num3 != 0)
                 {
                     GetTileBaseOption(i, j, num4, tile, ref baseOption);
                     num = ((num4 != 160) ? tile.color() : 0);
                 }
             }
         }
         if (num3 == 0)
         {
             bool flag2 = tile.invisibleWall();
             if (tile.wall > 0 && tile.fullbrightWall() && !flag2)
             {
                 num2 = 255;
             }
             if (tile.liquid > 32)
             {
                 int num5 = tile.liquidType();
                 num3 = liquidPosition + num5;
             }
             else if (!tile.invisibleWall() && tile.wall > 0 && tile.wall < WallID.Count)
             {
                 int wall = tile.wall;
                 num3 = wallLookup[wall];
                 num = tile.wallColor();
                 switch (wall)
                 {
                 case 21:
                 case 88:
                 case 89:
                 case 90:
                 case 91:
                 case 92:
                 case 93:
                 case 168:
                 case 241:
                     num = 0;
                     break;
                 case 27:
                     baseOption = i % 2;
                     break;
                 default:
                     baseOption = 0;
                     break;
                 }
             }
         }
         if (num3 == 0)
         {
             if ((double)j < Main.worldSurface)
             {
                 if (Main.remixWorld)
                 {
                     num2 = 5;
                     num3 = 100;
                 }
                 else
                 {
                     int num6 = (byte)(255.0 * ((double)j / Main.worldSurface));
                     num3 = skyPosition + num6;
                     num2 = 255;
                     num = 0;
                 }
             }
             else if (j < Main.UnderworldLayer)
             {
                 num = 0;
                 byte b = 0;
                 float num7 = Main.screenPosition.X / 16f - 5f;
                 float num8 = (Main.screenPosition.X + (float)Main.screenWidth) / 16f + 5f;
                 float num9 = Main.screenPosition.Y / 16f - 5f;
                 float num10 = (Main.screenPosition.Y + (float)Main.screenHeight) / 16f + 5f;
                 if (((float)i < num7 || (float)i > num8 || (float)j < num9 || (float)j > num10) && i > 40 && i < Main.maxTilesX - 40 && j > 40 && j < Main.maxTilesY - 40)
                 {
                     for (int k = i - 36; k <= i + 30; k += 10)
                     {
                         for (int l = j - 36; l <= j + 30; l += 10)
{
                             int type = Main.Map[k, l].Type;
                             for (int m = 0; m < snowTypes.Length; m++)
{
                                 if (snowTypes[m] == type)
{
                                     b = byte.MaxValue;
                                     k = i + 31;
                                     l = j + 31;
                                     break;
                                 }
                             }
                         }
                     }
                 }
                 else
                 {
                     float num11 = (float)Main.SceneMetrics.SnowTileCount / (float)SceneMetrics.SnowTileMax;
                     num11 *= 255f;
                     if (num11 > 255f)
                     {
                         num11 = 255f;
                     }
                     b = (byte)num11;
                 }
                 num3 = ((!((double)j < Main.rockLayer)) ? (rockPosition + b) : (dirtPosition + b));
             }
             else
             {
                 num3 = hellPosition;
             }
         }
         return MapTile.Create((ushort)(num3 + baseOption), (byte)num2, (byte)num);
     }
References Tile.active(), Tile.color(), WallID.Count, MapTile.Create(), dirtPosition, Tile.frameX, Tile.frameY, Tile.fullbrightBlock(), Tile.fullbrightWall(), GetTileBaseOption(), hellPosition, Tile.invisibleBlock(), Tile.invisibleWall(), WorldGen.IsThisAMushroomTree(), Tile.liquid, liquidPosition, Tile.liquidType(), Main.Map, Main.maxTilesX, Main.maxTilesY, Main.remixWorld, Main.rockLayer, rockPosition, Main.SceneMetrics, Main.screenHeight, Main.screenPosition, Main.screenWidth, skyPosition, SceneMetrics.SnowTileCount, SceneMetrics.SnowTileMax, snowTypes, Main.tile, tileLookup, Tile.type, Main.UnderworldLayer, Tile.wall, Tile.wallColor(), wallLookup, and Main.worldSurface.
Referenced by WorldMap.Update(), WorldMap.UpdateLighting(), and WorldMap.UpdateType().