Terraria: Actions.SetTile.Apply
Apply()
override bool Actions.SetTile.Apply (Point origin, int x, int y, params object[] args) inline virtual
Implements GenAction.
         {
             GenBase._tiles[x, y].Clear(~(TileDataType.Wiring | TileDataType.Actuator));
             GenBase._tiles[x, y].type = _type;
             GenBase._tiles[x, y].active(active: true);
             if (_doFraming)
             {
                 WorldUtils.TileFrame(x, y, _doNeighborFraming);
             }
             return UnitApply(origin, x, y, args);
         }
References Actions.SetTile._doFraming, Actions.SetTile._doNeighborFraming, GenBase._tiles, Actions.SetTile._type, Tile.active(), Tile.Clear(), WorldUtils.TileFrame(), Tile.type, and GenAction.UnitApply().