Terraria: System.Xml.Serialization.FieldModel.FieldModel
FieldModel() [3/3]
System.Xml.Serialization.FieldModel.FieldModel (MemberInfo memberInfo, Type fieldType, TypeDesc fieldTypeDesc) inline package
Definition at line 64 of file FieldModel.cs.
    {
        _name = memberInfo.Name;
        _fieldType = fieldType;
        _fieldTypeDesc = fieldTypeDesc;
        _memberInfo = memberInfo;
        _checkShouldPersistMethodInfo = memberInfo.DeclaringType.GetMethod("ShouldSerialize" + memberInfo.Name, Type.EmptyTypes);
        _checkShouldPersist = _checkShouldPersistMethodInfo != null;
        FieldInfo field = memberInfo.DeclaringType.GetField(memberInfo.Name + "Specified");
        if (field != null)
        {
            if (field.FieldType != typeof(bool))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidSpecifiedType, field.Name, field.FieldType.FullName, typeof(bool).FullName));
            }
            _checkSpecified = (field.IsInitOnly ? SpecifiedAccessor.ReadOnly : SpecifiedAccessor.ReadWrite);
            _checkSpecifiedMemberInfo = field;
        }
        else
        {
            PropertyInfo property = memberInfo.DeclaringType.GetProperty(memberInfo.Name + "Specified");
            if (property != null)
            {
                if (StructModel.CheckPropertyRead(property))
                {
                    _checkSpecified = ((!property.CanWrite) ? SpecifiedAccessor.ReadOnly : SpecifiedAccessor.ReadWrite);
                    _checkSpecifiedMemberInfo = property;
                }
                if (_checkSpecified != 0 && property.PropertyType != typeof(bool))
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidSpecifiedType, property.Name, property.PropertyType.FullName, typeof(bool).FullName));
                }
            }
        }
        if (memberInfo is PropertyInfo)
        {
            _readOnly = !((PropertyInfo)memberInfo).CanWrite;
            _isProperty = true;
        }
        else if (memberInfo is FieldInfo)
        {
            _readOnly = ((FieldInfo)memberInfo).IsInitOnly;
        }
    }
References System.Xml.Serialization.FieldModel._checkShouldPersist, System.Xml.Serialization.FieldModel._checkShouldPersistMethodInfo, System.Xml.Serialization.FieldModel._checkSpecified, System.Xml.Serialization.FieldModel._checkSpecifiedMemberInfo, System.Xml.Serialization.FieldModel._fieldType, System.Xml.Serialization.FieldModel._fieldTypeDesc, System.Xml.Serialization.FieldModel._isProperty, System.Xml.Serialization.FieldModel._memberInfo, System.Xml.Serialization.FieldModel._name, System.Xml.Serialization.FieldModel._readOnly, System.Xml.Serialization.StructModel.CheckPropertyRead(), System.Reflection.MemberInfo.DeclaringType, System.Xml.Dictionary, System.Type.EmptyTypes, System.SR.Format(), System.FullName, System.Type.GetField(), System.Type.GetMethod(), System.Type.GetProperty(), and System.SR.XmlInvalidSpecifiedType.