Terraria: System.Net.Sockets.SafeSocketHandle.CloseHandle
CloseHandle()
bool System.Net.Sockets.SafeSocketHandle.CloseHandle (bool abortive, bool canceledOperations) inline private
Definition at line 104 of file SafeSocketHandle.cs.
    {
        bool flag = false;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"handle:{handle}", "CloseHandle");
        }
        canceledOperations |= OnHandleClose();
        if (canceledOperations && !_hasShutdownSend)
        {
            abortive = true;
        }
        SocketError socketError = DoCloseHandle(abortive);
        return flag = socketError == SocketError.Success;
    }
References System.Net.Sockets.SafeSocketHandle._hasShutdownSend, System.Net.Sockets.SafeSocketHandle.DoCloseHandle(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.Net.Sockets.SafeSocketHandle.OnHandleClose().
Referenced by System.Net.Sockets.SafeSocketHandle.CloseAsIs(), and System.Net.Sockets.SafeSocketHandle.ReleaseHandle().