Terraria: AssetRepository.Request< T >
Request< T >() [2/2]
virtual Asset<T> AssetRepository.Request< T > (string assetName, AssetRequestMode mode = AssetRequestMode.AsyncLoad) inline virtual
Implements IAssetRepository.
Type Constraints
T : class
                                                                                                                      : class
     {
         if (_readers == null)
         {
             mode = AssetRequestMode.DoNotLoad;
         }
         ThrowIfDisposed();
         assetName = AssetPathHelper.CleanPath(assetName);
         Asset<T> asset = null;
         lock (_requestLock)
         {
             if (_assets.TryGetValue(assetName, out var value))
             {
                 asset = value as Asset<T>;
             }
             if (asset == null)
             {
                 asset = new Asset<T>(assetName);
                 _assets[assetName] = asset;
             }
             if (asset.State == AssetState.NotLoaded)
             {
                 EnsureReloadActionExistsForType<T>();
                 LoadAsset(asset, mode);
             }
         }
         if (mode == AssetRequestMode.ImmediateLoad)
         {
             asset.Wait();
         }
         return asset;
     }
References _assets, _readers, _requestLock, AssetPathHelper.CleanPath(), EnsureReloadActionExistsForType< T >(), Asset< T >.State, ThrowIfDisposed(), and Asset< T >.Wait.