Terraria: System.Reflection.Metadata.Ecma335.TypeDefOrRefTag.ConvertToHandle
ConvertToHandle()
static EntityHandle System.Reflection.Metadata.Ecma335.TypeDefOrRefTag.ConvertToHandle (uint typeDefOrRefTag) inline static package
Definition at line 24 of file TypeDefOrRefTag.cs.
    {
        uint num = (uint)(1769730 >>> (int)((typeDefOrRefTag & 3) << 3) << 24);
        uint num2 = typeDefOrRefTag >> 2;
        if (num == 0 || (num2 & 0xFF000000u) != 0)
        {
            Throw.InvalidCodedIndex();
        }
        return new EntityHandle(num | num2);
    }
References System.Reflection.Throw.InvalidCodedIndex().
Referenced by System.Reflection.Metadata.Ecma335.GenericParamConstraintTableReader.GetConstraint(), System.Reflection.Metadata.Ecma335.EventTableReader.GetEventType(), System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(), and System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.GetInterface().