Terraria: System.Net.Sockets.SafeSocketHandle.DoCloseHandle
DoCloseHandle()
SocketError System.Net.Sockets.SafeSocketHandle.DoCloseHandle (bool abortive) inline private
Definition at line 205 of file SafeSocketHandle.cs.
    {
        SocketError socketError;
        if (!abortive)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"handle:{handle}, Following 'blockable' branch", "DoCloseHandle");
            }
            socketError = global::Interop.Winsock.closesocket(handle);
            if (socketError == SocketError.SocketError)
            {
                socketError = (SocketError)Marshal.GetLastWin32Error();
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"handle:{handle}, closesocket()#1:{socketError}", "DoCloseHandle");
            }
            if (socketError != SocketError.WouldBlock)
            {
                return socketError;
            }
            int argp = 0;
            socketError = global::Interop.Winsock.ioctlsocket(handle, -2147195266, ref argp);
            if (socketError == SocketError.SocketError)
            {
                socketError = (SocketError)Marshal.GetLastWin32Error();
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"handle:{handle}, ioctlsocket()#1:{socketError}", "DoCloseHandle");
            }
            if (socketError == SocketError.Success)
            {
                socketError = global::Interop.Winsock.closesocket(handle);
                if (socketError == SocketError.SocketError)
                {
                    socketError = (SocketError)Marshal.GetLastWin32Error();
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"handle:{handle}, closesocket#2():{socketError}", "DoCloseHandle");
                }
                if (socketError != SocketError.WouldBlock)
                {
                    return socketError;
                }
            }
        }
        Unsafe.SkipInit(out global::Interop.Winsock.Linger linger);
        linger.OnOff = 1;
        linger.Time = 0;
        socketError = global::Interop.Winsock.setsockopt(handle, SocketOptionLevel.Socket, SocketOptionName.Linger, ref linger, 4);
        if (socketError == SocketError.SocketError)
        {
            socketError = (SocketError)Marshal.GetLastWin32Error();
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"handle:{handle}, setsockopt():{socketError}", "DoCloseHandle");
        }
        if (socketError != 0 && socketError != SocketError.InvalidArgument && socketError != SocketError.ProtocolOption)
        {
            return socketError;
        }
        socketError = global::Interop.Winsock.closesocket(handle);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"handle:{handle}, closesocket#3():{((socketError == SocketError.SocketError) ? ((SocketError)Marshal.GetLastWin32Error()) : socketError)}", "DoCloseHandle");
        }
        return socketError;
    }
References System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Runtime.InteropServices.SafeHandle.handle, System.Net.NetEventSource.Info(), and System.Net.NetEventSource.Log.
Referenced by System.Net.Sockets.SafeSocketHandle.CloseHandle().