Terraria: System.Net.Sockets.SafeSocketHandle.CloseAsIs
CloseAsIs()
void System.Net.Sockets.SafeSocketHandle.CloseAsIs (bool abortive) inline package
Definition at line 83 of file SafeSocketHandle.cs.
    {
        bool flag = TryOwnClose();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"shouldClose={flag}", "CloseAsIs");
        }
        Dispose();
        if (flag)
        {
            bool flag2 = false;
            SpinWait spinWait = default(SpinWait);
            while (!_released)
            {
                flag2 |= TryUnblockSocket(abortive);
                spinWait.SpinOnce();
            }
            CloseHandle(abortive, flag2);
        }
    }
References System.Net.Sockets.SafeSocketHandle._released, System.Net.Sockets.SafeSocketHandle.CloseHandle(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Threading.SpinWait.SpinOnce(), System.Net.Sockets.SafeSocketHandle.TryOwnClose(), and System.Net.Sockets.SafeSocketHandle.TryUnblockSocket().
Referenced by System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle().