Terraria: System.Net.Sockets.IPEndPointExtensions.Create
Create()
static EndPoint System.Net.Sockets.IPEndPointExtensions.Create (this EndPoint thisObj, System::Net::Internals::SocketAddress socketAddress) inline static
Definition at line 17 of file IPEndPointExtensions.cs.
    {
        AddressFamily family = socketAddress.Family;
        if (family != thisObj.AddressFamily)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_InvalidAddressFamily, family.ToString(), thisObj.GetType().FullName, thisObj.AddressFamily.ToString()), "socketAddress");
        }
        switch (family)
        {
        case AddressFamily.InterNetwork:
        case AddressFamily.InterNetworkV6:
            if (socketAddress.Size < 8)
            {
                throw new ArgumentException(System.SR.Format(System.SR.net_InvalidSocketAddressSize, socketAddress.GetType().FullName, thisObj.GetType().FullName), "socketAddress");
            }
            return socketAddress.GetIPEndPoint();
        case AddressFamily.Unknown:
            return thisObj;
        default:
        {
            SocketAddress netSocketAddress = GetNetSocketAddress(socketAddress);
            return thisObj.Create(netSocketAddress);
        }
        }
    }
References System.Net.EndPoint.AddressFamily, System.Net.EndPoint.Create(), System.SR.Format(), System.Net.Sockets.IPEndPointExtensions.GetNetSocketAddress(), System.SR.net_InvalidAddressFamily, and System.SR.net_InvalidSocketAddressSize.