Terraria: System.Data.DataColumnCollection.BaseGroupSwitch
BaseGroupSwitch()
void System.Data.DataColumnCollection.BaseGroupSwitch (DataColumn[] oldArray, int oldLength, DataColumn[] newArray, int newLength) inline private
Definition at line 299 of file DataColumnCollection.cs.
    {
        int num = 0;
        for (int i = 0; i < oldLength; i++)
        {
            bool flag = false;
            for (int j = num; j < newLength; j++)
            {
                if (oldArray[i] == newArray[j])
                {
                    if (num == j)
                    {
                        num++;
                    }
                    flag = true;
                    break;
                }
            }
            if (!flag && oldArray[i].Table == _table)
            {
                BaseRemove(oldArray[i]);
                _list.Remove(oldArray[i]);
                oldArray[i].SetOrdinalInternal(-1);
            }
        }
        for (int k = 0; k < newLength; k++)
        {
            if (newArray[k].Table != _table)
            {
                BaseAdd(newArray[k]);
                _list.Add(newArray[k]);
            }
            newArray[k].SetOrdinalInternal(k);
        }
    }
References System.Data.DataColumnCollection._list, System.Data.DataColumnCollection._table, System.Collections.ArrayList.Add(), System.Data.DataColumnCollection.BaseAdd(), System.Data.DataColumnCollection.BaseRemove(), and System.Collections.ArrayList.Remove().
Referenced by System.Data.DataColumnCollection.Clear().