Terraria: System.Data.DataColumnCollection.OnCollectionChanging
OnCollectionChanging()
void System.Data.DataColumnCollection.OnCollectionChanging (CollectionChangeEventArgs ccevent) inline private
Definition at line 664 of file DataColumnCollection.cs.
    {
        this.CollectionChanging?.Invoke(this, ccevent);
    }
Referenced by System.Data.DataColumnCollection.AddAt(), System.Data.DataColumnCollection.Clear(), and System.Data.DataColumnCollection.Remove().