Terraria: System.Data.DataColumnCollection.CanRemove
CanRemove() [1/2]
bool System.Data.DataColumnCollection.CanRemove (DataColumn column, bool fThrowException) inline package
Definition at line 357 of file DataColumnCollection.cs.
    {
        if (column == null)
        {
            if (!fThrowException)
            {
                return false;
            }
            throw ExceptionBuilder.ArgumentNull("column");
        }
        if (column._table != _table)
        {
            if (!fThrowException)
            {
                return false;
            }
            throw ExceptionBuilder.CannotRemoveColumn();
        }
        _table.OnRemoveColumnInternal(column);
        if (_table._primaryKey != null && _table._primaryKey.Key.ContainsColumn(column))
        {
            if (!fThrowException)
            {
                return false;
            }
            throw ExceptionBuilder.CannotRemovePrimaryKey();
        }
        for (int i = 0; i < _table.ParentRelations.Count; i++)
        {
            if (_table.ParentRelations[i].ChildKey.ContainsColumn(column))
            {
                if (!fThrowException)
                {
                    return false;
                }
                throw ExceptionBuilder.CannotRemoveChildKey(_table.ParentRelations[i].RelationName);
            }
        }
        for (int j = 0; j < _table.ChildRelations.Count; j++)
        {
            if (_table.ChildRelations[j].ParentKey.ContainsColumn(column))
            {
                if (!fThrowException)
                {
                    return false;
                }
                throw ExceptionBuilder.CannotRemoveChildKey(_table.ChildRelations[j].RelationName);
            }
        }
        for (int k = 0; k < _table.Constraints.Count; k++)
        {
            if (_table.Constraints[k].ContainsColumn(column))
            {
                if (!fThrowException)
                {
                    return false;
                }
                throw ExceptionBuilder.CannotRemoveConstraint(_table.Constraints[k].ConstraintName, _table.Constraints[k].Table.TableName);
            }
        }
        if (_table.DataSet != null)
        {
            ParentForeignKeyConstraintEnumerator parentForeignKeyConstraintEnumerator = new ParentForeignKeyConstraintEnumerator(_table.DataSet, _table);
            while (parentForeignKeyConstraintEnumerator.GetNext())
            {
                Constraint constraint = parentForeignKeyConstraintEnumerator.GetConstraint();
                if (((ForeignKeyConstraint)constraint).ParentKey.ContainsColumn(column))
                {
                    if (!fThrowException)
                    {
                        return false;
                    }
                    throw ExceptionBuilder.CannotRemoveConstraint(constraint.ConstraintName, constraint.Table.TableName);
                }
            }
        }
        if (column._dependentColumns != null)
        {
            for (int l = 0; l < column._dependentColumns.Count; l++)
            {
                DataColumn dataColumn = column._dependentColumns[l];
                if ((_fInClear && (dataColumn.Table == _table || dataColumn.Table == null)) || dataColumn.Table == null)
                {
                    continue;
                }
                DataExpression dataExpression = dataColumn.DataExpression;
                if (dataExpression != null && dataExpression.DependsOn(column))
                {
                    if (!fThrowException)
                    {
                        return false;
                    }
                    throw ExceptionBuilder.CannotRemoveExpression(dataColumn.ColumnName, dataColumn.Expression);
                }
            }
        }
        foreach (Index liveIndex in _table.LiveIndexes)
        {
        }
        return true;
    }
References System.Data.DataColumnCollection._fInClear, System.Data.DataTable._primaryKey, System.Data.DataColumnCollection._table, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.ExceptionBuilder.CannotRemoveChildKey(), System.Data.ExceptionBuilder.CannotRemoveColumn(), System.Data.ExceptionBuilder.CannotRemoveConstraint(), System.Data.ExceptionBuilder.CannotRemoveExpression(), System.Data.ExceptionBuilder.CannotRemovePrimaryKey(), System.Data.DataTable.ChildRelations, System.Data.Constraint.ConstraintName, System.Data.DataTable.Constraints, System.Data.DataKey.ContainsColumn(), System.Data.InternalDataCollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.DataTable.DataSet, System.Data.UniqueConstraint.Key, System.Data.DataTable.LiveIndexes, System.Data.DataTable.OnRemoveColumnInternal(), System.Data.DataTable.ParentRelations, System.Data.Constraint.Table, System.Data.ConstraintCollection.Table, and System.Data.DataTable.TableName.