Terraria: System.Data.DataColumnCollection.Clear
Clear()
void System.Data.DataColumnCollection.Clear () inline
Definition at line 474 of file DataColumnCollection.cs.
    {
        int count = _list.Count;
        DataColumn[] array = new DataColumn[_list.Count];
        _list.CopyTo(array, 0);
        OnCollectionChanging(InternalDataCollectionBase.s_refreshEventArgs);
        if (_table.fInitInProgress && _delayedAddRangeColumns != null)
        {
            _delayedAddRangeColumns = null;
        }
        try
        {
            _fInClear = true;
            BaseGroupSwitch(array, count, Array.Empty<DataColumn>(), 0);
            _fInClear = false;
        }
        catch (Exception e) when (ADP.IsCatchableOrSecurityExceptionType(e))
        {
            _fInClear = false;
            BaseGroupSwitch(Array.Empty<DataColumn>(), 0, array, count);
            _list.Clear();
            for (int i = 0; i < count; i++)
            {
                _list.Add(array[i]);
            }
            throw;
        }
        _list.Clear();
        _table.ElementColumnCount = 0;
        OnCollectionChanged(InternalDataCollectionBase.s_refreshEventArgs);
    }
References System.Data.DataColumnCollection._delayedAddRangeColumns, System.Data.DataColumnCollection._fInClear, System.Data.DataColumnCollection._list, System.Data.DataColumnCollection._table, System.Collections.ArrayList.Add(), System.array, System.Data.DataColumnCollection.BaseGroupSwitch(), System.Collections.ArrayList.Clear(), System.Collections.ArrayList.CopyTo(), System.count, System.Collections.ArrayList.Count, System.Data.DataTable.fInitInProgress, System.Data.Common.ADP.IsCatchableOrSecurityExceptionType(), System.Data.DataColumnCollection.OnCollectionChanged(), System.Data.DataColumnCollection.OnCollectionChanging(), and System.Data.InternalDataCollectionBase.s_refreshEventArgs.
Referenced by System.Data.DataTable.Reset().