Terraria: ItemVariants.GetEntry
GetEntry()
static VariantEntry ItemVariants.GetEntry (int itemId, ItemVariant variant) inline static private
     {
         return GetVariants(itemId).SingleOrDefault((VariantEntry v) => v.Variant == variant);
     }
References GetVariants(), and ItemVariants.VariantEntry.Variant.
Referenced by AddVariant(), and HasVariant().