Terraria: System.Data.DataColumnCollection.Add
Add() [2/5]
void System.Data.DataColumnCollection.Add (DataColumn column) inline
Definition at line 111 of file DataColumnCollection.cs.
    {
        AddAt(-1, column);
    }
References System.Data.DataColumnCollection.AddAt().
Referenced by System.Data.DataTable.AddForeignKey(), System.Data.DataTable.AddUniqueKey(), System.Data.DataTable.DeserializeTableSchema(), System.Data.DataTableReader.GetSchemaTableFromDataTable(), System.Data.Common.DbSchemaRow.GetSortedSchemaRows(), System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XDRSchema.HandleColumn(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleSimpleContentColumn(), System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn(), and System.Data.DataTableExtensions.LoadTableFromEnumerable< T >().