Terraria: System.Data.DataColumnCollection.IndexOfCaseInsensitive
IndexOfCaseInsensitive()
int System.Data.DataColumnCollection.IndexOfCaseInsensitive (string name) inline package
Definition at line 586 of file DataColumnCollection.cs.
    {
        int specialHashCode = _table.GetSpecialHashCode(name);
        int num = -1;
        DataColumn dataColumn = null;
        for (int i = 0; i < Count; i++)
        {
            dataColumn = (DataColumn)_list[i];
            if ((specialHashCode == 0 || dataColumn._hashCode == 0 || dataColumn._hashCode == specialHashCode) && NamesEqual(dataColumn.ColumnName, name, fCaseSensitive: false, _table.Locale) != 0)
            {
                if (num != -1)
                {
                    return -2;
                }
                num = i;
            }
        }
        return num;
    }
References System.Data.DataColumnCollection._list, System.Data.DataColumnCollection._table, System.Data.InternalDataCollectionBase.Count, System.Data.DataTable.GetSpecialHashCode(), System.Data.DataTable.Locale, and System.Data.InternalDataCollectionBase.NamesEqual().
Referenced by System.Data.DataColumnCollection.Contains(), System.Data.DataColumnCollection.Contains(), and System.Data.DataColumnCollection.IndexOf().