Terraria: System.Data.DataColumnCollection.Remove
Remove() [1/2]
void System.Data.DataColumnCollection.Remove (DataColumn column) inline
Definition at line 712 of file DataColumnCollection.cs.
    {
        OnCollectionChanging(new CollectionChangeEventArgs(CollectionChangeAction.Remove, column));
        BaseRemove(column);
        ArrayRemove(column);
        OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Remove, column));
        if (column.ColumnMapping == MappingType.Element)
        {
            _table.ElementColumnCount--;
        }
    }
References System.Data.DataColumnCollection._table, System.Data.DataColumnCollection.ArrayRemove(), System.Data.DataColumnCollection.BaseRemove(), System.Data.DataTable.ElementColumnCount, System.Data.DataColumnCollection.OnCollectionChanged(), and System.Data.DataColumnCollection.OnCollectionChanging().