Terraria: System.Data.DataColumnCollection.UnregisterName
UnregisterName()
void System.Data.DataColumnCollection.UnregisterName (string name) inline package
Definition at line 744 of file DataColumnCollection.cs.
    {
        _columnFromName.Remove(name);
        if (NamesEqual(name, MakeName(_defaultNameIndex - 1), fCaseSensitive: true, _table.Locale) != 0)
        {
            do
            {
                _defaultNameIndex--;
            }
            while (_defaultNameIndex > 1 && !Contains(MakeName(_defaultNameIndex - 1)));
        }
    }
References System.Data.DataColumnCollection._columnFromName, System.Data.DataColumnCollection._defaultNameIndex, System.Data.DataColumnCollection._table, System.Data.DataColumnCollection.Contains(), System.Data.DataTable.Locale, System.Data.DataColumnCollection.MakeName(), System.Data.InternalDataCollectionBase.NamesEqual(), and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by System.Data.DataColumnCollection.BaseAdd(), System.Data.DataColumnCollection.BaseRemove(), and System.Data.DataRelationCollection.RemoveCore().