Terraria: System.Data.DataColumnCollection.AddAt
AddAt()
void System.Data.DataColumnCollection.AddAt (int index, DataColumn column) inline package
Definition at line 116 of file DataColumnCollection.cs.
    {
        if (column != null && column.ColumnMapping == MappingType.SimpleContent)
        {
            if (_table.XmlText != null && _table.XmlText != column)
            {
                throw ExceptionBuilder.CannotAddColumn3();
            }
            if (_table.ElementColumnCount > 0)
            {
                throw ExceptionBuilder.CannotAddColumn4(column.ColumnName);
            }
            OnCollectionChanging(new CollectionChangeEventArgs(CollectionChangeAction.Add, column));
            BaseAdd(column);
            if (index != -1)
            {
                ArrayAdd(index, column);
            }
            else
            {
                ArrayAdd(column);
            }
            _table.XmlText = column;
        }
        else
        {
            OnCollectionChanging(new CollectionChangeEventArgs(CollectionChangeAction.Add, column));
            BaseAdd(column);
            if (index != -1)
            {
                ArrayAdd(index, column);
            }
            else
            {
                ArrayAdd(column);
            }
            if (column.ColumnMapping == MappingType.Element)
            {
                _table.ElementColumnCount++;
            }
        }
        if (!_table.fInitInProgress && column != null && column.Computed)
        {
            column.CopyExpressionFrom(column);
        }
        OnCollectionChanged(new CollectionChangeEventArgs(CollectionChangeAction.Add, column));
    }
References System.Data.DataColumnCollection._table, System.Data.DataColumnCollection.ArrayAdd(), System.Data.DataColumnCollection.BaseAdd(), System.Data.ExceptionBuilder.CannotAddColumn3(), System.Data.ExceptionBuilder.CannotAddColumn4(), System.Data.DataTable.ElementColumnCount, System.Data.DataTable.fInitInProgress, System.index, System.Data.DataColumnCollection.OnCollectionChanged(), System.Data.DataColumnCollection.OnCollectionChanging(), and System.Data.DataTable.XmlText.
Referenced by System.Data.DataColumnCollection.Add(), System.Data.DataTable.AddUniqueKey(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleSimpleContentColumn(), and System.Data.XSDSchema.HandleSimpleTypeSimpleContentColumn().