Terraria: Terraria.Achievements.ConditionsCompletedTracker.OnConditionCompleted
OnConditionCompleted()
void Terraria.Achievements.ConditionsCompletedTracker.OnConditionCompleted (AchievementCondition condition) inline private
Definition at line 17 of file ConditionsCompletedTracker.cs.
    {
        SetValue(Math.Min(_value + 1, _maxValue));
    }
References Terraria.Achievements.AchievementTracker< int >._maxValue, Terraria.Achievements.AchievementTracker< int >._value, System.Math.Min(), and Terraria.Achievements.AchievementTracker< int >.SetValue().
Referenced by Terraria.Achievements.ConditionsCompletedTracker.AddCondition().