Terraria: System.Xml.XmlCharCheckingWriter.WriteCDataAsync
WriteCDataAsync() [1/2]
override async Task System.Xml.XmlCharCheckingWriter.WriteCDataAsync (string text) inline
Definition at line 572 of file XmlCharCheckingWriter.cs.
    {
        if (text != null)
        {
            if (_checkValues)
            {
                CheckCharacters(text);
            }
            if (_replaceNewLines)
            {
                text = ReplaceNewLines(text);
            }
            while (true)
            {
                int num;
                int i = (num = text.IndexOf("]]>", StringComparison.Ordinal));
                if (num < 0)
                {
                    break;
                }
                await writer.WriteCDataAsync(text.Substring(0, i + 2)).ConfigureAwait(continueOnCapturedContext: false);
                text = text.Substring(i + 2);
            }
        }
        await writer.WriteCDataAsync(text).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XmlCharCheckingWriter._checkValues, System.Xml.XmlCharCheckingWriter._replaceNewLines, System.Xml.XmlCharCheckingWriter.CheckCharacters(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlCharCheckingWriter.ReplaceNewLines(), System.text, System.Xml.XmlWriter.WriteCDataAsync(), and System.Xml.XmlWrappingWriter.writer.