Terraria: System.Xml.XmlCharCheckingWriter.CheckCharacters
CheckCharacters() [2/2]
void System.Xml.XmlCharCheckingWriter.CheckCharacters (string str) inline private
Definition at line 286 of file XmlCharCheckingWriter.cs.
    {
        XmlConvert.VerifyCharData(str, ExceptionType.ArgumentException);
    }
References System.str, and System.Xml.XmlConvert.VerifyCharData().
Referenced by System.Xml.XmlCharCheckingWriter.WriteCData(), System.Xml.XmlCharCheckingWriter.WriteCDataAsync(), System.Xml.XmlCharCheckingWriter.WriteChars(), System.Xml.XmlCharCheckingWriter.WriteCharsAsync(), System.Xml.XmlCharCheckingWriter.WriteComment(), System.Xml.XmlCharCheckingWriter.WriteCommentAsync(), System.Xml.XmlCharCheckingWriter.WriteDocType(), System.Xml.XmlCharCheckingWriter.WriteDocTypeAsync(), System.Xml.XmlCharCheckingWriter.WriteProcessingInstruction(), System.Xml.XmlCharCheckingWriter.WriteProcessingInstructionAsync(), System.Xml.XmlCharCheckingWriter.WriteString(), and System.Xml.XmlCharCheckingWriter.WriteStringAsync().