Terraria: System.ComponentModel.BaseNumberConverter.ConvertFrom
ConvertFrom() [1/2]
override? object System.ComponentModel.BaseNumberConverter.ConvertFrom (ITypeDescriptorContext? context, CultureInfo? culture, object value) inline virtual inherited
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 30 of file BaseNumberConverter.cs.
    {
        if (value is string text)
        {
            string text2 = text.Trim();
            try
            {
                if (AllowHex && text2[0] == '#')
                {
                    return FromString(text2.Substring(1), 16);
                }
                if (AllowHex && (text2.StartsWith("0x", StringComparison.OrdinalIgnoreCase) || text2.StartsWith("&h", StringComparison.OrdinalIgnoreCase)))
                {
                    return FromString(text2.Substring(2), 16);
                }
                if (culture == null)
                {
                    culture = CultureInfo.CurrentCulture;
                }
                NumberFormatInfo formatInfo = (NumberFormatInfo)culture.GetFormat(typeof(NumberFormatInfo));
                return FromString(text2, formatInfo);
            }
            catch (Exception innerException)
            {
                throw new ArgumentException(System.SR.Format(System.SR.ConvertInvalidPrimitive, text2, TargetType.Name), "value", innerException);
            }
        }
        return base.ConvertFrom(context, culture, value);
    }
References System.ComponentModel.BaseNumberConverter.AllowHex, System.SR.ConvertInvalidPrimitive, System.culture, System.Globalization.CultureInfo.CurrentCulture, System.SR.Format(), System.ComponentModel.BaseNumberConverter.FromString(), System.Globalization.NumberFormatInfo.GetFormat(), System.text, and System.value.