Terraria: System.Xml.XmlCharCheckingWriter.WriteWhitespace
WriteWhitespace() [1/2]
override void System.Xml.XmlCharCheckingWriter.WriteWhitespace (string ws) inline
Definition at line 180 of file XmlCharCheckingWriter.cs.
    {
        if (ws == null)
        {
            ws = string.Empty;
        }
        int invCharIndex;
        if (_checkNames && (invCharIndex = XmlCharType.IsOnlyWhitespaceWithPos(ws)) != -1)
        {
            string xml_InvalidWhitespaceCharacter = System.SR.Xml_InvalidWhitespaceCharacter;
            object[] args = XmlException.BuildCharExceptionArgs(ws, invCharIndex);
            throw new ArgumentException(System.SR.Format(xml_InvalidWhitespaceCharacter, args));
        }
        if (_replaceNewLines)
        {
            ws = ReplaceNewLines(ws);
        }
        writer.WriteWhitespace(ws);
    }
References System.Xml.XmlCharCheckingWriter._checkNames, System.Xml.XmlCharCheckingWriter._replaceNewLines, System.Xml.ArgumentException, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlCharType.IsOnlyWhitespaceWithPos(), System.Xml.XmlCharCheckingWriter.ReplaceNewLines(), System.Xml.XmlWrappingWriter.writer, System.Xml.XmlWriter.WriteWhitespace(), and System.SR.Xml_InvalidWhitespaceCharacter.