Terraria: System.Xml.XmlCharCheckingWriter.ValidateQName
ValidateQName()
void System.Xml.XmlCharCheckingWriter.ValidateQName (string name) inline private
Definition at line 311 of file XmlCharCheckingWriter.cs.
    {
        if (name.Length == 0)
        {
            throw new ArgumentException(System.SR.Xml_EmptyName);
        }
        int colonOffset;
        int num = ValidateNames.ParseQName(name, 0, out colonOffset);
        if (num != name.Length)
        {
            string format = ((num == 0 || (colonOffset > -1 && num == colonOffset + 1)) ? System.SR.Xml_BadStartNameChar : System.SR.Xml_BadNameChar);
            object[] args = XmlException.BuildCharExceptionArgs(name, num);
            throw new ArgumentException(string.Format(format, args));
        }
    }
References System.Xml.ArgumentException, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.Dictionary, System.format, System.Format, System.Xml.ValidateNames.ParseQName(), System.SR.Xml_BadNameChar, and System.SR.Xml_EmptyName.
Referenced by System.Xml.XmlCharCheckingWriter.WriteDocType(), System.Xml.XmlCharCheckingWriter.WriteDocTypeAsync(), System.Xml.XmlCharCheckingWriter.WriteEntityRef(), and System.Xml.XmlCharCheckingWriter.WriteEntityRefAsync().