Terraria: System.Xml.XmlCharCheckingWriter.WriteStringAsync
WriteStringAsync() [1/2]
override Task System.Xml.XmlCharCheckingWriter.WriteStringAsync (string text) inline
Definition at line 666 of file XmlCharCheckingWriter.cs.
    {
        if (text != null)
        {
            if (_checkValues)
            {
                CheckCharacters(text);
            }
            if (_replaceNewLines && WriteState != WriteState.Attribute)
            {
                text = ReplaceNewLines(text);
            }
        }
        return writer.WriteStringAsync(text);
    }
References System.Xml.XmlCharCheckingWriter._checkValues, System.Xml.XmlCharCheckingWriter._replaceNewLines, System.Xml.XmlCharCheckingWriter.CheckCharacters(), System.Xml.XmlCharCheckingWriter.ReplaceNewLines(), System.text, System.Xml.XmlWrappingWriter.writer, and System.Xml.XmlWriter.WriteStringAsync().
Referenced by System.Xml.XmlCharCheckingWriter.WriteCharsAsync().