Terraria: System.Xml.XmlCharCheckingWriter.WriteDocType
WriteDocType() [1/2]
override void System.Xml.XmlCharCheckingWriter.WriteDocType (string name, string pubid, string sysid, string subset) inline
Definition at line 46 of file XmlCharCheckingWriter.cs.
    {
        if (_checkNames)
        {
            ValidateQName(name);
        }
        if (_checkValues)
        {
            int invCharPos;
            if (pubid != null && (invCharPos = XmlCharType.IsPublicId(pubid)) >= 0)
            {
                throw XmlConvert.CreateInvalidCharException(pubid, invCharPos);
            }
            if (sysid != null)
            {
                CheckCharacters(sysid);
            }
            if (subset != null)
            {
                CheckCharacters(subset);
            }
        }
        if (_replaceNewLines)
        {
            sysid = ReplaceNewLines(sysid);
            pubid = ReplaceNewLines(pubid);
            subset = ReplaceNewLines(subset);
        }
        writer.WriteDocType(name, pubid, sysid, subset);
    }
References System.Xml.XmlCharCheckingWriter._checkNames, System.Xml.XmlCharCheckingWriter._checkValues, System.Xml.XmlCharCheckingWriter._replaceNewLines, System.Xml.XmlCharCheckingWriter.CheckCharacters(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.Dictionary, System.Xml.XmlCharType.IsPublicId(), System.Xml.XmlCharCheckingWriter.ReplaceNewLines(), System.Xml.XmlCharCheckingWriter.ValidateQName(), System.Xml.XmlWriter.WriteDocType(), and System.Xml.XmlWrappingWriter.writer.