Terraria: System.Xml.XmlCharCheckingWriter.ValidateNCName
ValidateNCName()
void System.Xml.XmlCharCheckingWriter.ValidateNCName (string ncname) inline private
Definition at line 296 of file XmlCharCheckingWriter.cs.
    {
        if (ncname.Length == 0)
        {
            throw new ArgumentException(System.SR.Xml_EmptyName);
        }
        int num = ValidateNames.ParseNCName(ncname, 0);
        if (num != ncname.Length)
        {
            string resourceFormat = ((num == 0) ? System.SR.Xml_BadStartNameChar : System.SR.Xml_BadNameChar);
            object[] args = XmlException.BuildCharExceptionArgs(ncname, num);
            throw new ArgumentException(System.SR.Format(resourceFormat, args));
        }
    }
References System.Xml.ArgumentException, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.Dictionary, System.SR.Format(), System.Xml.ValidateNames.ParseNCName(), System.SR.Xml_BadNameChar, System.SR.Xml_BadStartNameChar, and System.SR.Xml_EmptyName.
Referenced by System.Xml.XmlCharCheckingWriter.WriteProcessingInstruction(), System.Xml.XmlCharCheckingWriter.WriteProcessingInstructionAsync(), System.Xml.XmlCharCheckingWriter.WriteQualifiedName(), System.Xml.XmlCharCheckingWriter.WriteQualifiedNameAsync(), System.Xml.XmlCharCheckingWriter.WriteStartAttribute(), System.Xml.XmlCharCheckingWriter.WriteStartAttributeAsync(), System.Xml.XmlCharCheckingWriter.WriteStartElement(), and System.Xml.XmlCharCheckingWriter.WriteStartElementAsync().