Terraria: System.Xml.XmlCharCheckingWriter.ReplaceNewLines
ReplaceNewLines() [2/2]
string System.Xml.XmlCharCheckingWriter.ReplaceNewLines (string str) inline private
Definition at line 328 of file XmlCharCheckingWriter.cs.
    {
        if (str == null)
        {
            return null;
        }
        StringBuilder stringBuilder = null;
        int num = 0;
        int i;
        for (i = 0; i < str.Length; i++)
        {
            char c;
            if ((c = str[i]) >= ' ')
            {
                continue;
            }
            if (c == '\n')
            {
                if (_newLineChars == "\n")
                {
                    continue;
                }
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(str.Length + 5);
                }
                stringBuilder.Append(str, num, i - num);
            }
            else
            {
                if (c != '\r')
                {
                    continue;
                }
                if (i + 1 < str.Length && str[i + 1] == '\n')
                {
                    if (_newLineChars == "\r\n")
                    {
                        i++;
                        continue;
                    }
                    if (stringBuilder == null)
                    {
                        stringBuilder = new StringBuilder(str.Length + 5);
                    }
                    stringBuilder.Append(str, num, i - num);
                    i++;
                }
                else
                {
                    if (_newLineChars == "\r")
                    {
                        continue;
                    }
                    if (stringBuilder == null)
                    {
                        stringBuilder = new StringBuilder(str.Length + 5);
                    }
                    stringBuilder.Append(str, num, i - num);
                }
            }
            stringBuilder.Append(_newLineChars);
            num = i + 1;
        }
        if (stringBuilder == null)
        {
            return str;
        }
        stringBuilder.Append(str, num, i - num);
        return stringBuilder.ToString();
    }
References System.Xml.XmlCharCheckingWriter._newLineChars, System.Xml.Dictionary, and System.str.
Referenced by System.Xml.XmlCharCheckingWriter.WriteCData(), System.Xml.XmlCharCheckingWriter.WriteCDataAsync(), System.Xml.XmlCharCheckingWriter.WriteChars(), System.Xml.XmlCharCheckingWriter.WriteCharsAsync(), System.Xml.XmlCharCheckingWriter.WriteComment(), System.Xml.XmlCharCheckingWriter.WriteCommentAsync(), System.Xml.XmlCharCheckingWriter.WriteDocType(), System.Xml.XmlCharCheckingWriter.WriteDocTypeAsync(), System.Xml.XmlCharCheckingWriter.WriteProcessingInstruction(), System.Xml.XmlCharCheckingWriter.WriteProcessingInstructionAsync(), System.Xml.XmlCharCheckingWriter.WriteString(), System.Xml.XmlCharCheckingWriter.WriteStringAsync(), System.Xml.XmlCharCheckingWriter.WriteWhitespace(), and System.Xml.XmlCharCheckingWriter.WriteWhitespaceAsync().