Terraria: System.Xml.XmlCharCheckingWriter.WriteChars
WriteChars()
override void System.Xml.XmlCharCheckingWriter.WriteChars (char[] buffer, int index, int count) inline
Definition at line 221 of file XmlCharCheckingWriter.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (count > buffer.Length - index)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_checkValues)
        {
            CheckCharacters(buffer, index, count);
        }
        if (_replaceNewLines && WriteState != WriteState.Attribute)
        {
            string text = ReplaceNewLines(buffer, index, count);
            if (text != null)
            {
                WriteString(text);
                return;
            }
        }
        writer.WriteChars(buffer, index, count);
    }
References System.Xml.XmlCharCheckingWriter._checkValues, System.Xml.XmlCharCheckingWriter._replaceNewLines, System.buffer, System.Xml.XmlCharCheckingWriter.CheckCharacters(), System.count, System.index, System.Xml.XmlCharCheckingWriter.ReplaceNewLines(), System.text, System.Xml.XmlWriter.WriteChars(), System.Xml.XmlWrappingWriter.writer, and System.Xml.XmlCharCheckingWriter.WriteString().