Terraria: System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.IsAllowedAsciiCodePoint
IsAllowedAsciiCodePoint()
unsafe readonly bool System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.IsAllowedAsciiCodePoint (uint codePoint) inline package
Definition at line 23 of file OptimizedInboxTextEncoder.cs.
        {
            if (codePoint > 127)
            {
                return false;
            }
            uint num = AsBytes[codePoint & 0xF];
            if ((num & (uint)(1 << (int)(codePoint >> 4))) == 0)
            {
                return false;
            }
            return true;
        }
References System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.AsBytes, and System.codePoint.
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeAdvSimd64(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeAdvSimd64(), and System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3().