Terraria: Terraria.GameContent.Events.DD2Event.Difficulty_3_GetRequiredWaveKills
Difficulty_3_GetRequiredWaveKills()
static int Terraria.GameContent.Events.DD2Event.Difficulty_3_GetRequiredWaveKills (ref int waveNumber, ref int currentKillCount, bool currentlyInCheckProgress) inline static private
    {
        switch (waveNumber)
        {
        case -1:
            return 0;
        case 1:
            return 60;
        case 2:
            return 80;
        case 3:
            return 100;
        case 4:
            return 120;
        case 5:
            return 140;
        case 6:
            return 180;
        case 7:
        {
            int num = NPC.FindFirstNPC(551);
            if (num == -1)
            {
                return 1;
            }
            currentKillCount = 100 - (int)((float)Main.npc[num].life / (float)Main.npc[num].lifeMax * 100f);
            return 100;
        }
        case 8:
            waveNumber = 7;
            currentKillCount = 1;
            if (currentlyInCheckProgress)
            {
                StartVictoryScene();
            }
            return 1;
        default:
            return 10;
        }
    }
References Terraria.NPC.FindFirstNPC(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.npc, and Terraria.GameContent.Events.DD2Event.StartVictoryScene().
Referenced by Terraria.GameContent.Events.DD2Event.GetInvasionStatus().