Terraria: Terraria.GameContent.Events.DD2Event.StartInvasion
StartInvasion()
static void Terraria.GameContent.Events.DD2Event.StartInvasion (int difficultyOverride = -1) inline static
Definition at line 230 of file DD2Event.cs.
    {
        if (Main.netMode != 1)
        {
            _crystalsDropping_toDrop = 0;
            _crystalsDropping_alreadyDropped = 0;
            _crystalsDropping_lastWave = 0;
            _timeLeftUntilSpawningBegins = 0;
            Ongoing = true;
            FindProperDifficulty();
            if (difficultyOverride != -1)
            {
                OngoingDifficulty = difficultyOverride;
            }
            _deadGoblinSpots.Clear();
            _downedDarkMageT1 = false;
            _downedOgreT2 = false;
            _spawnedBetsyT3 = false;
            LostThisRun = false;
            WonThisRun = false;
            NPC.totalInvasionPoints = 0f;
            NPC.waveKills = 0f;
            NPC.waveNumber = 1;
            ClearAllTowersInGame();
            WorldGen.BroadcastText(NetworkText.FromKey("DungeonDefenders2.InvasionStart"), INFO_START_INVASION_COLOR);
            NetMessage.SendData(7);
            if (Main.netMode != 1)
            {
                Main.ReportInvasionProgress(0, 1, 3, 1);
            }
            if (Main.netMode == 2)
            {
                NetMessage.SendData(78, -1, -1, null, 0, 1f, 3f, 1f);
            }
            SetEnemySpawningOnHold(300);
            WipeEntities();
        }
    }
References Terraria.GameContent.Events.DD2Event._crystalsDropping_alreadyDropped, Terraria.GameContent.Events.DD2Event._crystalsDropping_lastWave, Terraria.GameContent.Events.DD2Event._crystalsDropping_toDrop, Terraria.GameContent.Events.DD2Event._deadGoblinSpots, Terraria.GameContent.Events.DD2Event._downedDarkMageT1, Terraria.GameContent.Events.DD2Event._downedOgreT2, Terraria.GameContent.Events.DD2Event._spawnedBetsyT3, Terraria.GameContent.Events.DD2Event._timeLeftUntilSpawningBegins, Terraria.WorldGen.BroadcastText(), Terraria.GameContent.Events.DD2Event.ClearAllTowersInGame(), Terraria.GameContent.Events.DD2Event.FindProperDifficulty(), Terraria.Localization.NetworkText.FromKey(), Terraria.GameContent.Events.DD2Event.INFO_START_INVASION_COLOR, Terraria.GameContent.Events.DD2Event.LostThisRun, Terraria.Main.netMode, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.GameContent.Events.DD2Event.OngoingDifficulty, Terraria.Main.ReportInvasionProgress(), Terraria.NetMessage.SendData(), Terraria.GameContent.Events.DD2Event.SetEnemySpawningOnHold(), Terraria.GameContent.Events.DD2Event.WipeEntities(), and Terraria.GameContent.Events.DD2Event.WonThisRun.
Referenced by Terraria.GameContent.Events.DD2Event.SummonCrystalDirect().