Terraria: Terraria.GameContent.Events.DD2Event.SetEnemySpawningOnHold
SetEnemySpawningOnHold()
static void Terraria.GameContent.Events.DD2Event.SetEnemySpawningOnHold (int forHowLong) inline static private
Definition at line 927 of file DD2Event.cs.
    {
        _timeLeftUntilSpawningBegins = forHowLong;
        if (Main.netMode == 2)
        {
            NetMessage.SendData(116, -1, -1, null, _timeLeftUntilSpawningBegins);
        }
    }
References Terraria.GameContent.Events.DD2Event._timeLeftUntilSpawningBegins, Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.GameContent.Events.DD2Event.AttemptToSkipWaitTime(), Terraria.GameContent.Events.DD2Event.CheckProgress(), Terraria.GameContent.Events.DD2Event.ReportLoss(), and Terraria.GameContent.Events.DD2Event.StartInvasion().