Terraria: Terraria.GameContent.Events.DD2Event.Load
Load()
static void Terraria.GameContent.Events.DD2Event.Load (BinaryReader reader, int gameVersionNumber) inline static
Definition at line 132 of file DD2Event.cs.
    {
        if (gameVersionNumber < 178)
        {
            NPC.savedBartender = false;
            ResetProgressEntirely();
            return;
        }
        NPC.savedBartender = reader.ReadBoolean();
        DownedInvasionT1 = reader.ReadBoolean();
        DownedInvasionT2 = reader.ReadBoolean();
        DownedInvasionT3 = reader.ReadBoolean();
    }
References Terraria.GameContent.Events.DD2Event.DownedInvasionT1, Terraria.GameContent.Events.DD2Event.DownedInvasionT2, Terraria.GameContent.Events.DD2Event.DownedInvasionT3, System.IO.BinaryReader.ReadBoolean(), and Terraria.GameContent.Events.DD2Event.ResetProgressEntirely().
Referenced by Terraria.IO.WorldFile.LoadHeader().