Terraria: Terraria.GameContent.Events.DD2Event.RequestToSkipWaitTime
RequestToSkipWaitTime()
static void Terraria.GameContent.Events.DD2Event.RequestToSkipWaitTime (int x, int y) inline static
Definition at line 1762 of file DD2Event.cs.
    {
        if (TimeLeftBetweenWaves > 60 && IsStandActive(x, y))
        {
            SoundEngine.PlaySound(SoundID.NPCDeath7, x * 16 + 8, y * 16 + 8);
            if (Main.netMode == 0)
            {
                AttemptToSkipWaitTime();
            }
            else if (Main.netMode != 2)
            {
                NetMessage.SendData(143);
            }
        }
    }
References Terraria.GameContent.Events.DD2Event.AttemptToSkipWaitTime(), Terraria.GameContent.Events.DD2Event.IsStandActive(), Terraria.Main.netMode, Terraria.ID.SoundID.NPCDeath7, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), and Terraria.GameContent.Events.DD2Event.TimeLeftBetweenWaves.
Referenced by Terraria.Player.TileInteractionsUse().