Terraria: Terraria.GameContent.Events.DD2Event.GetInvasionStatus
GetInvasionStatus()
static void Terraria.GameContent.Events.DD2Event.GetInvasionStatus (out int currentWave, out int requiredKillCount, out int currentKillCount, bool currentlyInCheckProgress = false) inline static private
    {
        currentWave = NPC.waveNumber;
        requiredKillCount = 10;
        currentKillCount = (int)NPC.waveKills;
        switch (OngoingDifficulty)
        {
        case 3:
            requiredKillCount = Difficulty_3_GetRequiredWaveKills(ref currentWave, ref currentKillCount, currentlyInCheckProgress);
            break;
        case 2:
            requiredKillCount = Difficulty_2_GetRequiredWaveKills(ref currentWave, ref currentKillCount, currentlyInCheckProgress);
            break;
        default:
            requiredKillCount = Difficulty_1_GetRequiredWaveKills(ref currentWave, ref currentKillCount, currentlyInCheckProgress);
            break;
        }
    }
References Terraria.GameContent.Events.DD2Event.Difficulty_1_GetRequiredWaveKills(), Terraria.GameContent.Events.DD2Event.Difficulty_2_GetRequiredWaveKills(), Terraria.GameContent.Events.DD2Event.Difficulty_3_GetRequiredWaveKills(), Terraria.GameContent.Events.DD2Event.OngoingDifficulty, Terraria.NPC.waveKills, and Terraria.NPC.waveNumber.
Referenced by Terraria.GameContent.Events.DD2Event.CheckProgress(), Terraria.GameContent.Events.DD2Event.Difficulty_1_SpawnMonsterFromGate(), Terraria.GameContent.Events.DD2Event.Difficulty_2_SpawnMonsterFromGate(), Terraria.GameContent.Events.DD2Event.ReportEventProgress(), Terraria.GameContent.Events.DD2Event.ShouldDropCrystals(), Terraria.GameContent.Events.DD2Event.SyncInvasionProgress(), and Terraria.GameContent.Events.DD2Event.UpdateTime().