Terraria: Terraria.GameContent.Events.DD2Event.FailureMessage
FailureMessage()
static void Terraria.GameContent.Events.DD2Event.FailureMessage (int client) inline static
Definition at line 583 of file DD2Event.cs.
    {
        LocalizedText text = Language.GetText("DungeonDefenders2.BartenderWarning");
        Color color = new Color(255, 255, 0);
        if (Main.netMode == 2)
        {
            ChatHelper.SendChatMessageToClient(NetworkText.FromKey(text.Key), color, client);
        }
        else
        {
            Main.NewText(text.Value, color.R, color.G, color.B);
        }
    }
References Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.Language.GetText(), Terraria.Localization.LocalizedText.Key, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Chat.ChatHelper.SendChatMessageToClient(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.TileInteractionsUse().