Terraria: Terraria.GameContent.Events.DD2Event.SummonCrystalDirect
SummonCrystalDirect()
static void Terraria.GameContent.Events.DD2Event.SummonCrystalDirect (int x, int y, int whoAsks) inline static
Definition at line 552 of file DD2Event.cs.
    {
        if (!NPC.AnyNPCs(548))
        {
            Tile tileSafely = Framing.GetTileSafely(x, y);
            if (tileSafely.active() && tileSafely.type == 466)
            {
                Point point = new Point(x * 16, y * 16);
                point.X -= tileSafely.frameX / 18 * 16;
                point.Y -= tileSafely.frameY / 18 * 16;
                point.X += 40;
                point.Y += 64;
                StartInvasion();
                NPC.NewNPC(Main.player[whoAsks].GetNPCSource_TileInteraction(x, y), point.X, point.Y, 548);
                DropStarterCrystals();
            }
        }
    }
References Terraria.Tile.active(), Terraria.NPC.AnyNPCs(), Terraria.GameContent.Events.DD2Event.DropStarterCrystals(), Terraria.Player.GetNPCSource_TileInteraction(), Terraria.Framing.GetTileSafely(), Terraria.NPC.NewNPC(), Terraria.Main.player, Terraria.GameContent.Events.DD2Event.StartInvasion(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.Events.DD2Event.SummonCrystal().