Terraria: Terraria.GameContent.UI.States.UICreativePowersMenu.InitializePage
InitializePage()
void Terraria.GameContent.UI.States.UICreativePowersMenu.InitializePage () inline private
Definition at line 100 of file UICreativePowersMenu.cs.
    {
        int num = 270;
        int num2 = 20;
        _container = new UIElement
        {
            HAlign = 0f,
            VAlign = 0f,
            Width = new StyleDimension(0f, 1f),
            Height = new StyleDimension(-num - num2, 1f),
            Top = new StyleDimension(num, 0f)
        };
        Append(_container);
        List<UIElement> buttons = CreateMainPowerStrip();
        PowerStripUIElement powerStripUIElement = new PowerStripUIElement("strip 0", buttons)
        {
            HAlign = 0f,
            VAlign = 0.5f,
            Left = new StyleDimension(20f, 0f)
        };
        powerStripUIElement.OnMouseOver += strip_OnMouseOver;
        powerStripUIElement.OnMouseOut += strip_OnMouseOut;
        _mainPowerStrip = powerStripUIElement;
        List<UIElement> buttons2 = CreateTimePowerStrip();
        PowerStripUIElement powerStripUIElement2 = new PowerStripUIElement("strip 1", buttons2)
        {
            HAlign = 0f,
            VAlign = 0.5f,
            Left = new StyleDimension(80f, 0f)
        };
        powerStripUIElement2.OnMouseOver += strip_OnMouseOver;
        powerStripUIElement2.OnMouseOut += strip_OnMouseOut;
        _timePowersStrip = powerStripUIElement2;
        List<UIElement> buttons3 = CreateWeatherPowerStrip();
        PowerStripUIElement powerStripUIElement3 = new PowerStripUIElement("strip 1", buttons3)
        {
            HAlign = 0f,
            VAlign = 0.5f,
            Left = new StyleDimension(80f, 0f)
        };
        powerStripUIElement3.OnMouseOver += strip_OnMouseOver;
        powerStripUIElement3.OnMouseOut += strip_OnMouseOut;
        _weatherPowersStrip = powerStripUIElement3;
        List<UIElement> buttons4 = CreatePersonalPowerStrip();
        PowerStripUIElement powerStripUIElement4 = new PowerStripUIElement("strip 1", buttons4)
        {
            HAlign = 0f,
            VAlign = 0.5f,
            Left = new StyleDimension(80f, 0f)
        };
        powerStripUIElement4.OnMouseOver += strip_OnMouseOver;
        powerStripUIElement4.OnMouseOut += strip_OnMouseOut;
        _personalPowersStrip = powerStripUIElement4;
        _infiniteItemsWindow = new UICreativeInfiniteItemsDisplay(this)
        {
            HAlign = 0f,
            VAlign = 0.5f,
            Left = new StyleDimension(80f, 0f),
            Width = new StyleDimension(480f, 0f),
            Height = new StyleDimension(-88f, 1f)
        };
        RefreshElementsOrder();
        base.OnUpdate += UICreativePowersMenu_OnUpdate;
    }
References Terraria.GameContent.UI.States.UICreativePowersMenu._container, Terraria.GameContent.UI.States.UICreativePowersMenu._infiniteItemsWindow, Terraria.GameContent.UI.States.UICreativePowersMenu._mainPowerStrip, Terraria.GameContent.UI.States.UICreativePowersMenu._personalPowersStrip, Terraria.GameContent.UI.States.UICreativePowersMenu._timePowersStrip, Terraria.GameContent.UI.States.UICreativePowersMenu._weatherPowersStrip, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateMainPowerStrip(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreatePersonalPowerStrip(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateTimePowerStrip(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateWeatherPowerStrip(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UICreativePowersMenu.RefreshElementsOrder(), Terraria.GameContent.UI.States.UICreativePowersMenu.strip_OnMouseOut(), Terraria.GameContent.UI.States.UICreativePowersMenu.strip_OnMouseOver(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.States.UICreativePowersMenu.UICreativePowersMenu_OnUpdate(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.OnActivate().