Terraria: Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 480 of file UICreativePowersMenu.cs.
    {
        int currentID = 10000;
        List<SnapPoint> snapPoints = GetSnapPoints();
        List<SnapPoint> orderedPointsByCategoryName = _helper.GetOrderedPointsByCategoryName(snapPoints, "strip 0");
        List<SnapPoint> orderedPointsByCategoryName2 = _helper.GetOrderedPointsByCategoryName(snapPoints, "strip 1");
        List<SnapPoint> orderedPointsByCategoryName3 = _helper.GetOrderedPointsByCategoryName(snapPoints, "strip 2");
        UILinkPoint[] array = null;
        UILinkPoint[] array2 = null;
        UILinkPoint[] array3 = null;
        if (orderedPointsByCategoryName.Count > 0)
        {
            array = _helper.CreateUILinkStripVertical(ref currentID, orderedPointsByCategoryName);
        }
        if (orderedPointsByCategoryName2.Count > 0)
        {
            array2 = _helper.CreateUILinkStripVertical(ref currentID, orderedPointsByCategoryName2);
        }
        if (orderedPointsByCategoryName3.Count > 0)
        {
            array3 = _helper.CreateUILinkStripVertical(ref currentID, orderedPointsByCategoryName3);
        }
        if (array != null && array2 != null)
        {
            _helper.LinkVerticalStrips(array, array2, (array.Length - array2.Length) / 2);
        }
        if (array2 != null && array3 != null)
        {
            _helper.LinkVerticalStrips(array2, array3, (array.Length - array2.Length) / 2);
        }
        UILinkPoint uILinkPoint = null;
        UILinkPoint uILinkPoint2 = null;
        UILinkPoint uILinkPoint3 = null;
        for (int i = 0; i < snapPoints.Count; i++)
        {
            SnapPoint snapPoint = snapPoints[i];
            string name = snapPoint.Name;
            if (!(name == "CreativeSacrificeConfirm"))
            {
                if (name == "CreativeInfinitesSearch")
                {
                    uILinkPoint3 = _helper.MakeLinkPointFromSnapPoint(currentID++, snapPoint);
                    Main.CreativeMenu.GamepadPointIdForInfiniteItemSearchHack = uILinkPoint3.ID;
                }
            }
            else
            {
                uILinkPoint2 = _helper.MakeLinkPointFromSnapPoint(currentID++, snapPoint);
            }
        }
        uILinkPoint = UILinkPointNavigator.Points[15000];
        List<SnapPoint> orderedPointsByCategoryName4 = _helper.GetOrderedPointsByCategoryName(snapPoints, "CreativeInfinitesFilter");
        UILinkPoint[] array4 = null;
        if (orderedPointsByCategoryName4.Count > 0)
        {
            array4 = _helper.CreateUILinkStripHorizontal(ref currentID, orderedPointsByCategoryName4);
            if (uILinkPoint3 != null)
            {
                uILinkPoint3.Up = array4[0].ID;
                for (int j = 0; j < array4.Length; j++)
                {
                    array4[j].Down = uILinkPoint3.ID;
                }
            }
        }
        List<SnapPoint> orderedPointsByCategoryName5 = _helper.GetOrderedPointsByCategoryName(snapPoints, "CreativeInfinitesSlot");
        UILinkPoint[,] array5 = null;
        if (orderedPointsByCategoryName5.Count > 0)
        {
            array5 = _helper.CreateUILinkPointGrid(ref currentID, orderedPointsByCategoryName5, _infiniteItemsWindow.GetItemsPerLine(), uILinkPoint3, array[0], null, null);
            _helper.LinkVerticalStripRightSideToSingle(array, array5[0, 0]);
        }
        else if (uILinkPoint3 != null)
        {
            _helper.LinkVerticalStripRightSideToSingle(array, uILinkPoint3);
        }
        if (uILinkPoint3 != null && array5 != null)
        {
            _helper.PairUpDown(uILinkPoint3, array5[0, 0]);
        }
        if (uILinkPoint != null && IsShowingResearchMenu)
        {
            _helper.LinkVerticalStripRightSideToSingle(array, uILinkPoint);
        }
        if (uILinkPoint2 != null)
        {
            _helper.PairUpDown(uILinkPoint, uILinkPoint2);
            uILinkPoint2.Left = array[0].ID;
        }
        if (Main.CreativeMenu.GamepadMoveToSearchButtonHack)
        {
            Main.CreativeMenu.GamepadMoveToSearchButtonHack = false;
            if (uILinkPoint3 != null)
            {
                UILinkPointNavigator.ChangePoint(uILinkPoint3.ID);
            }
        }
    }
References Terraria.GameContent.UI.States.UICreativePowersMenu._helper, Terraria.GameContent.UI.States.UICreativePowersMenu._infiniteItemsWindow, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripHorizontal(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripVertical(), Terraria.Main.CreativeMenu, Terraria.UI.Gamepad.UILinkPoint.Down, Terraria.GameContent.Creative.CreativeUI.GamepadMoveToSearchButtonHack, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GetItemsPerLine(), Terraria.GameContent.UI.States.UIGamepadHelper.GetOrderedPointsByCategoryName(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPoint.ID, Terraria.GameContent.UI.States.UICreativePowersMenu.IsShowingResearchMenu, Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStripRightSideToSingle(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStrips(), Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint(), Terraria.UI.SnapPoint.Name, Terraria.GameContent.UI.States.UIGamepadHelper.PairUpDown(), and Terraria.UI.Gamepad.UILinkPointNavigator.Points.
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.Draw().