Terraria: System.Xml.Schema.XsdValidator.Init
Init()
void System.Xml.Schema.XsdValidator.Init () inline private
Definition at line 92 of file XsdValidator.cs.
    {
        _nsManager = reader.NamespaceManager;
        if (_nsManager == null)
        {
            _nsManager = new XmlNamespaceManager(base.NameTable);
            _bManageNamespaces = true;
        }
        _validationStack = new HWStack(10);
        textValue = new StringBuilder();
        _attPresence = new Hashtable();
        schemaInfo = new SchemaInfo();
        checkDatatype = false;
        _processContents = XmlSchemaContentProcessing.Strict;
        Push(XmlQualifiedName.Empty);
        _nsXmlNs = base.NameTable.Add("http://www.w3.org/2000/xmlns/");
        _nsXs = base.NameTable.Add("http://www.w3.org/2001/XMLSchema");
        _nsXsi = base.NameTable.Add("http://www.w3.org/2001/XMLSchema-instance");
        _xsiType = base.NameTable.Add("type");
        _xsiNil = base.NameTable.Add("nil");
        _xsiSchemaLocation = base.NameTable.Add("schemaLocation");
        _xsiNoNamespaceSchemaLocation = base.NameTable.Add("noNamespaceSchemaLocation");
        _xsdSchema = base.NameTable.Add("schema");
    }
References System.Xml.Schema.XsdValidator._attPresence, System.Xml.Schema.XsdValidator._bManageNamespaces, System.Xml.Schema.XsdValidator._nsManager, System.Xml.Schema.XsdValidator._nsXmlNs, System.Xml.Schema.XsdValidator._nsXs, System.Xml.Schema.XsdValidator._nsXsi, System.Xml.Schema.XsdValidator._processContents, System.Xml.Schema.XsdValidator._validationStack, System.Xml.Schema.XsdValidator._xsdSchema, System.Xml.Schema.XsdValidator._xsiNil, System.Xml.Schema.XsdValidator._xsiNoNamespaceSchemaLocation, System.Xml.Schema.XsdValidator._xsiSchemaLocation, System.Xml.Schema.XsdValidator._xsiType, System.Xml.Schema.BaseValidator.checkDatatype, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.XmlValidatingReaderImpl.NamespaceManager, System.Xml.Schema.XsdValidator.Push(), System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.BaseValidator.SchemaInfo, and System.Xml.Schema.BaseValidator.textValue.
Referenced by System.Xml.Schema.XsdValidator.XsdValidator(), and System.Xml.Schema.XsdValidator.XsdValidator().