Terraria: System.Xml.Schema.XsdValidator.ValidateStartElementIdentityConstraints
ValidateStartElementIdentityConstraints()
void System.Xml.Schema.XsdValidator.ValidateStartElementIdentityConstraints () inline private
Definition at line 790 of file XsdValidator.cs.
    {
        if (context.ElementDecl != null)
        {
            if (context.ElementDecl.Constraints != null)
            {
                AddIdentityConstraints();
            }
            if (HasIdentityConstraints)
            {
                ElementIdentityConstraints();
            }
        }
    }
References System.Xml.Schema.XsdValidator.AddIdentityConstraints(), System.Xml.Schema.SchemaElementDecl.Constraints, System.Xml.Schema.BaseValidator.context, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.XsdValidator.ElementIdentityConstraints(), and System.Xml.Schema.XsdValidator.HasIdentityConstraints.
Referenced by System.Xml.Schema.XsdValidator.ProcessElement().