Terraria: System.Xml.Schema.XsdValidator.ValidateChildElement
ValidateChildElement()
object System.Xml.Schema.XsdValidator.ValidateChildElement () inline private
Definition at line 201 of file XsdValidator.cs.
    {
        object obj = null;
        int errorCode = 0;
        if (context.NeedValidateChildren)
        {
            if (context.IsNill)
            {
                SendValidationEvent(System.SR.Sch_ContentInNill, elementName.ToString());
                return null;
            }
            obj = context.ElementDecl.ContentValidator.ValidateElement(elementName, context, out errorCode);
            if (obj == null)
            {
                _processContents = (context.ProcessContents = XmlSchemaContentProcessing.Skip);
                if (errorCode == -2)
                {
                    SendValidationEvent(System.SR.Sch_AllElement, elementName.ToString());
                }
                XmlSchemaValidator.ElementValidationError(elementName, context, base.EventHandler, reader, reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition, null);
            }
        }
        return obj;
    }
References System.Xml.Schema.XsdValidator._processContents, System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.BaseValidator.elementName, System.Xml.Schema.XmlSchemaValidator.ElementValidationError(), System.Xml.Schema.ValidationState.IsNill, System.Xml.Schema.ValidationState.NeedValidateChildren, System.obj, System.Xml.Schema.BaseValidator.reader, System.SR.Sch_AllElement, System.SR.Sch_ContentInNill, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.XmlQualifiedName.ToString(), and System.Xml.Schema.ContentValidator.ValidateElement().
Referenced by System.Xml.Schema.XsdValidator.ValidateElement().