Terraria: System.Xml.Schema.XsdValidator.ValidateStartElement
ValidateStartElement()
void System.Xml.Schema.XsdValidator.ValidateStartElement () inline private
Definition at line 446 of file XsdValidator.cs.
    {
        if (context.ElementDecl != null)
        {
            if (context.ElementDecl.IsAbstract)
            {
                SendValidationEvent(System.SR.Sch_AbstractElement, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
            }
            reader.SchemaTypeObject = context.ElementDecl.SchemaType;
            if (reader.IsEmptyElement && !context.IsNill && context.ElementDecl.DefaultValueTyped != null)
            {
                reader.TypedValueObject = UnWrapUnion(context.ElementDecl.DefaultValueTyped);
                context.IsNill = true;
            }
            else
            {
                reader.TypedValueObject = null;
            }
            if (context.ElementDecl.HasRequiredAttribute || HasIdentityConstraints)
            {
                _attPresence.Clear();
            }
        }
        if (!reader.MoveToFirstAttribute())
        {
            return;
        }
        do
        {
            if ((object)reader.NamespaceURI == _nsXmlNs || (object)reader.NamespaceURI == _nsXsi)
            {
                continue;
            }
            try
            {
                reader.SchemaTypeObject = null;
                XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(reader.LocalName, reader.NamespaceURI);
                bool skip = _processContents == XmlSchemaContentProcessing.Skip;
                SchemaAttDef attributeXsd = schemaInfo.GetAttributeXsd(context.ElementDecl, xmlQualifiedName, ref skip);
                if (attributeXsd != null)
                {
                    if (context.ElementDecl != null && (context.ElementDecl.HasRequiredAttribute || _startIDConstraint != -1))
                    {
                        _attPresence.Add(attributeXsd.Name, attributeXsd);
                    }
                    reader.SchemaTypeObject = attributeXsd.SchemaType;
                    if (attributeXsd.Datatype != null)
                    {
                        CheckValue(reader.Value, attributeXsd);
                    }
                    if (HasIdentityConstraints)
                    {
                        AttributeIdentityConstraints(reader.LocalName, reader.NamespaceURI, reader.TypedValueObject, reader.Value, attributeXsd);
                    }
                }
                else if (!skip)
                {
                    if (context.ElementDecl == null && _processContents == XmlSchemaContentProcessing.Strict && xmlQualifiedName.Namespace.Length != 0 && schemaInfo.Contains(xmlQualifiedName.Namespace))
                    {
                        SendValidationEvent(System.SR.Sch_UndeclaredAttribute, xmlQualifiedName.ToString());
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_NoAttributeSchemaFound, xmlQualifiedName.ToString(), XmlSeverityType.Warning);
                    }
                }
            }
            catch (XmlSchemaException ex)
            {
                ex.SetSource(reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition);
                SendValidationEvent(ex);
            }
        }
        while (reader.MoveToNextAttribute());
        reader.MoveToElement();
    }
References System.Xml.Schema.XsdValidator._attPresence, System.Xml.Schema.XsdValidator._nsXmlNs, System.Xml.Schema.XsdValidator._nsXsi, System.Xml.Schema.XsdValidator._processContents, System.Xml.Schema.XsdValidator._startIDConstraint, System.Collections.Hashtable.Add(), System.Xml.Schema.XsdValidator.AttributeIdentityConstraints(), System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.XsdValidator.CheckValue(), System.Collections.Hashtable.Clear(), System.Xml.Schema.SchemaInfo.Contains(), System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.DefaultValueTyped, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.SchemaInfo.GetAttributeXsd(), System.Xml.Schema.XsdValidator.HasIdentityConstraints, System.Xml.Schema.SchemaElementDecl.HasRequiredAttribute, System.Xml.Schema.SchemaElementDecl.IsAbstract, System.Xml.XmlValidatingReaderImpl.IsEmptyElement, System.Xml.Schema.ValidationState.IsNill, System.Xml.Schema.ValidationState.LocalName, System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.MoveToElement(), System.Xml.XmlValidatingReaderImpl.MoveToFirstAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToNextAttribute(), System.Xml.Schema.ValidationState.Namespace, System.Xml.XmlValidatingReaderImpl.NamespaceURI, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.Xml.Schema.BaseValidator.reader, System.SR.Sch_AbstractElement, System.SR.Sch_NoAttributeSchemaFound, System.SR.Sch_UndeclaredAttribute, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.SchemaDeclBase.SchemaType, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.XmlValidatingReaderImpl.TypedValueObject, System.Xml.Schema.XsdValidator.UnWrapUnion(), and System.Xml.XmlValidatingReaderImpl.Value.
Referenced by System.Xml.Schema.XsdValidator.ProcessElement().