Terraria: System.Xml.Schema.XsdValidator.ElementIdentityConstraints
ElementIdentityConstraints()
void System.Xml.Schema.XsdValidator.ElementIdentityConstraints () inline private
Definition at line 855 of file XsdValidator.cs.
    {
        for (int i = _startIDConstraint; i < _validationStack.Length; i++)
        {
            if (((ValidationState)_validationStack[i]).Constr == null)
            {
                continue;
            }
            ConstraintStruct[] constr = ((ValidationState)_validationStack[i]).Constr;
            for (int j = 0; j < constr.Length; j++)
            {
                if (constr[j].axisSelector.MoveToStartElement(reader.LocalName, reader.NamespaceURI))
                {
                    constr[j].axisSelector.PushKS(base.PositionInfo.LineNumber, base.PositionInfo.LinePosition);
                }
                for (int k = 0; k < constr[j].axisFields.Count; k++)
                {
                    LocatedActiveAxis locatedActiveAxis = (LocatedActiveAxis)constr[j].axisFields[k];
                    if (locatedActiveAxis.MoveToStartElement(reader.LocalName, reader.NamespaceURI) && context.ElementDecl != null)
                    {
                        if (context.ElementDecl.Datatype == null)
{
                            SendValidationEvent(System.SR.Sch_FieldSimpleTypeExpected, reader.LocalName);
                        }
                        else
{
                            locatedActiveAxis.isMatched = true;
                        }
                    }
                }
            }
        }
    }
References System.Xml.Schema.XsdValidator._startIDConstraint, System.Xml.Schema.XsdValidator._validationStack, System.Xml.Schema.ConstraintStruct.axisSelector, System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.Datatype, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.HWStack.Length, System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.NamespaceURI, System.Xml.Schema.SelectorActiveAxis.PushKS(), System.Xml.Schema.BaseValidator.reader, System.SR.Sch_FieldSimpleTypeExpected, and System.Xml.Schema.BaseValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XsdValidator.ValidateStartElementIdentityConstraints().