Terraria: System.Xml.Schema.XsdValidator.ValidateEndStartElement
ValidateEndStartElement()
void System.Xml.Schema.XsdValidator.ValidateEndStartElement () inline private
Definition at line 523 of file XsdValidator.cs.
    {
        if (context.ElementDecl.HasDefaultAttribute)
        {
            for (int i = 0; i < context.ElementDecl.DefaultAttDefs.Count; i++)
            {
                SchemaAttDef schemaAttDef = (SchemaAttDef)context.ElementDecl.DefaultAttDefs[i];
                reader.AddDefaultAttribute(schemaAttDef);
                if (HasIdentityConstraints && !_attPresence.Contains(schemaAttDef.Name))
                {
                    AttributeIdentityConstraints(schemaAttDef.Name.Name, schemaAttDef.Name.Namespace, UnWrapUnion(schemaAttDef.DefaultValueTyped), schemaAttDef.DefaultValueRaw, schemaAttDef);
                }
            }
        }
        if (context.ElementDecl.HasRequiredAttribute)
        {
            try
            {
                context.ElementDecl.CheckAttributes(_attPresence, reader.StandAlone);
            }
            catch (XmlSchemaException ex)
            {
                ex.SetSource(reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition);
                SendValidationEvent(ex);
            }
        }
        if (context.ElementDecl.Datatype != null)
        {
            checkDatatype = true;
            hasSibling = false;
            textString = string.Empty;
            textValue.Length = 0;
        }
    }
References System.Xml.Schema.XsdValidator._attPresence, System.Xml.XmlValidatingReaderImpl.AddDefaultAttribute(), System.Xml.Schema.XsdValidator.AttributeIdentityConstraints(), System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.SchemaElementDecl.CheckAttributes(), System.Xml.Schema.BaseValidator.checkDatatype, System.Collections.Hashtable.Contains(), System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.Datatype, System.Xml.Schema.SchemaElementDecl.DefaultAttDefs, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.SchemaElementDecl.HasDefaultAttribute, System.Xml.Schema.XsdValidator.HasIdentityConstraints, System.Xml.Schema.SchemaElementDecl.HasRequiredAttribute, System.Xml.Schema.BaseValidator.hasSibling, System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.XmlValidatingReaderImpl.StandAlone, System.Xml.Schema.BaseValidator.textString, and System.Xml.Schema.XsdValidator.UnWrapUnion().
Referenced by System.Xml.Schema.XsdValidator.ProcessElement().