Terraria: System.Xml.Schema.XsdValidator.AttributeIdentityConstraints
AttributeIdentityConstraints()
void System.Xml.Schema.XsdValidator.AttributeIdentityConstraints (string name, string ns, object obj, string sobj, SchemaAttDef attdef) inline private
Definition at line 889 of file XsdValidator.cs.
    {
        for (int i = _startIDConstraint; i < _validationStack.Length; i++)
        {
            if (((ValidationState)_validationStack[i]).Constr == null)
            {
                continue;
            }
            ConstraintStruct[] constr = ((ValidationState)_validationStack[i]).Constr;
            for (int j = 0; j < constr.Length; j++)
            {
                for (int k = 0; k < constr[j].axisFields.Count; k++)
                {
                    LocatedActiveAxis locatedActiveAxis = (LocatedActiveAxis)constr[j].axisFields[k];
                    if (locatedActiveAxis.MoveToAttribute(name, ns))
                    {
                        if (locatedActiveAxis.Ks[locatedActiveAxis.Column] != null)
{
                            SendValidationEvent(System.SR.Sch_FieldSingleValueExpected, name);
                        }
                        else if (attdef != null && attdef.Datatype != null)
{
                            locatedActiveAxis.Ks[locatedActiveAxis.Column] = new TypedObject(obj, sobj, attdef.Datatype);
                        }
                    }
                }
            }
        }
    }
References System.Xml.Schema.XsdValidator._startIDConstraint, System.Xml.Schema.XsdValidator._validationStack, System.Xml.Dictionary, System.Xml.HWStack.Length, System.obj, System.SR.Sch_FieldSingleValueExpected, and System.Xml.Schema.BaseValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XsdValidator.ValidateEndStartElement(), and System.Xml.Schema.XsdValidator.ValidateStartElement().