Terraria: System.Xml.Schema.XsdValidator.ProcessElement
ProcessElement()
void System.Xml.Schema.XsdValidator.ProcessElement (object particle) inline private
Definition at line 226 of file XsdValidator.cs.
    {
        SchemaElementDecl schemaElementDecl = FastGetElementDecl(particle);
        Push(elementName);
        if (_bManageNamespaces)
        {
            _nsManager.PushScope();
        }
        ProcessXsiAttributes(out var xsiType, out var xsiNil);
        if (_processContents != XmlSchemaContentProcessing.Skip)
        {
            if (schemaElementDecl == null || !xsiType.IsEmpty || xsiNil != null)
            {
                schemaElementDecl = ThoroughGetElementDecl(schemaElementDecl, xsiType, xsiNil);
            }
            if (schemaElementDecl == null)
            {
                if (HasSchema && _processContents == XmlSchemaContentProcessing.Strict)
                {
                    SendValidationEvent(System.SR.Sch_UndeclaredElement, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_NoElementSchemaFound, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace), XmlSeverityType.Warning);
                }
            }
        }
        context.ElementDecl = schemaElementDecl;
        ValidateStartElementIdentityConstraints();
        ValidateStartElement();
        if (context.ElementDecl != null)
        {
            ValidateEndStartElement();
            context.NeedValidateChildren = _processContents != XmlSchemaContentProcessing.Skip;
            context.ElementDecl.ContentValidator.InitValidation(context);
        }
    }
References System.Xml.Schema.XsdValidator._bManageNamespaces, System.Xml.Schema.XsdValidator._nsManager, System.Xml.Schema.XsdValidator._processContents, System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.BaseValidator.elementName, System.Xml.Schema.XsdValidator.FastGetElementDecl(), System.Xml.Schema.XsdValidator.HasSchema, System.Xml.Schema.ContentValidator.InitValidation(), System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.XsdValidator.ProcessXsiAttributes(), System.Xml.Schema.XsdValidator.Push(), System.Xml.XmlNamespaceManager.PushScope(), System.Xml.Schema.XmlSchemaValidator.QNameString(), System.SR.Sch_NoElementSchemaFound, System.SR.Sch_UndeclaredElement, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.XsdValidator.ThoroughGetElementDecl(), System.Xml.Schema.XsdValidator.ValidateEndStartElement(), System.Xml.Schema.XsdValidator.ValidateStartElement(), and System.Xml.Schema.XsdValidator.ValidateStartElementIdentityConstraints().
Referenced by System.Xml.Schema.XsdValidator.ValidateElement().