Terraria: System.Xml.Schema.XsdValidator.CheckForwardRefs
CheckForwardRefs()
void System.Xml.Schema.XsdValidator.CheckForwardRefs () inline private
Definition at line 774 of file XsdValidator.cs.
    {
        IdRefNode idRefNode = _idRefListHead;
        while (idRefNode != null)
        {
            if (FindId(idRefNode.Id) == null)
            {
                SendValidationEvent(new XmlSchemaException(System.SR.Sch_UndeclaredId, idRefNode.Id, reader.BaseURI, idRefNode.LineNo, idRefNode.LinePos));
            }
            IdRefNode next = idRefNode.Next;
            idRefNode.Next = null;
            idRefNode = next;
        }
        _idRefListHead = null;
    }
References System.Xml.Schema.XsdValidator._idRefListHead, System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Dictionary, System.Xml.Schema.XsdValidator.FindId(), System.Xml.Schema.IdRefNode.Next, System.Xml.Schema.BaseValidator.reader, System.SR.Sch_UndeclaredId, and System.Xml.Schema.BaseValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XsdValidator.CompleteValidation().