Terraria: System.Xml.Schema.XsdValidator.EndElementIdentityConstraints
EndElementIdentityConstraints()
void System.Xml.Schema.XsdValidator.EndElementIdentityConstraints () inline private
Definition at line 928 of file XsdValidator.cs.
    {
        for (int num = _validationStack.Length - 1; num >= _startIDConstraint; num--)
        {
            if (((ValidationState)_validationStack[num]).Constr != null)
            {
                ConstraintStruct[] constr = ((ValidationState)_validationStack[num]).Constr;
                for (int i = 0; i < constr.Length; i++)
                {
                    for (int j = 0; j < constr[i].axisFields.Count; j++)
                    {
                        LocatedActiveAxis locatedActiveAxis = (LocatedActiveAxis)constr[i].axisFields[j];
                        if (locatedActiveAxis.isMatched)
{
                            locatedActiveAxis.isMatched = false;
                            if (locatedActiveAxis.Ks[locatedActiveAxis.Column] != null)
{
                                SendValidationEvent(System.SR.Sch_FieldSingleValueExpected, reader.LocalName);
                            }
                            else
{
                                string text = ((!hasSibling) ? textString : textValue.ToString());
                                if (reader.TypedValueObject != null && text.Length != 0)
{
                                    locatedActiveAxis.Ks[locatedActiveAxis.Column] = new TypedObject(reader.TypedValueObject, text, context.ElementDecl.Datatype);
                                }
                            }
                        }
                        locatedActiveAxis.EndElement(reader.LocalName, reader.NamespaceURI);
                    }
                    if (!constr[i].axisSelector.EndElement(reader.LocalName, reader.NamespaceURI))
                    {
                        continue;
                    }
                    KeySequence keySequence = constr[i].axisSelector.PopKS();
                    switch (constr[i].constraint.Role)
                    {
                    case CompiledIdentityConstraint.ConstraintRole.Key:
                        if (!keySequence.IsQualified())
{
                            SendValidationEvent(new XmlSchemaException(System.SR.Sch_MissingKey, constr[i].constraint.name.ToString(), reader.BaseURI, keySequence.PosLine, keySequence.PosCol));
                        }
                        else if (constr[i].qualifiedTable.Contains(keySequence))
{
                            SendValidationEvent(new XmlSchemaException(System.SR.Sch_DuplicateKey, new string[2]
{
                                keySequence.ToString(),
                                constr[i].constraint.name.ToString()
                            }, reader.BaseURI, keySequence.PosLine, keySequence.PosCol));
                        }
                        else
{
                            constr[i].qualifiedTable.Add(keySequence, keySequence);
                        }
                        break;
                    case CompiledIdentityConstraint.ConstraintRole.Unique:
                        if (keySequence.IsQualified())
{
                            if (constr[i].qualifiedTable.Contains(keySequence))
{
                                SendValidationEvent(new XmlSchemaException(System.SR.Sch_DuplicateKey, new string[2]
{
                                    keySequence.ToString(),
                                    constr[i].constraint.name.ToString()
                                }, reader.BaseURI, keySequence.PosLine, keySequence.PosCol));
                            }
                            else
{
                                constr[i].qualifiedTable.Add(keySequence, keySequence);
                            }
                        }
                        break;
                    case CompiledIdentityConstraint.ConstraintRole.Keyref:
                        if (constr[i].qualifiedTable != null && keySequence.IsQualified() && !constr[i].qualifiedTable.Contains(keySequence))
{
                            constr[i].qualifiedTable.Add(keySequence, keySequence);
                        }
                        break;
                    }
                }
            }
        }
        ConstraintStruct[] constr2 = ((ValidationState)_validationStack[_validationStack.Length - 1]).Constr;
        if (constr2 == null)
        {
            return;
        }
        for (int k = 0; k < constr2.Length; k++)
        {
            if (constr2[k].constraint.Role == CompiledIdentityConstraint.ConstraintRole.Keyref || constr2[k].keyrefTable == null)
            {
                continue;
            }
            foreach (KeySequence key in constr2[k].keyrefTable.Keys)
            {
                if (!constr2[k].qualifiedTable.Contains(key))
                {
                    SendValidationEvent(new XmlSchemaException(System.SR.Sch_UnresolvedKeyref, new string[2]
                    {
                        key.ToString(),
                        constr2[k].constraint.name.ToString()
                    }, reader.BaseURI, key.PosLine, key.PosCol));
                }
            }
        }
    }
References System.Xml.Schema.XsdValidator._startIDConstraint, System.Xml.Schema.XsdValidator._validationStack, System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.Datatype, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.BaseValidator.hasSibling, System.key, System.Xml.HWStack.Length, System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.NamespaceURI, System.Xml.Schema.BaseValidator.reader, System.SR.Sch_DuplicateKey, System.SR.Sch_FieldSingleValueExpected, System.SR.Sch_MissingKey, System.SR.Sch_UnresolvedKeyref, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.text, System.Xml.Schema.BaseValidator.textString, System.Xml.Schema.BaseValidator.textValue, System.Text.StringBuilder.ToString(), and System.Xml.XmlValidatingReaderImpl.TypedValueObject.
Referenced by System.Xml.Schema.XsdValidator.ValidateEndElement().