Terraria: System.Xml.Schema.XsdValidator.CheckValue
CheckValue()
void System.Xml.Schema.XsdValidator.CheckValue (string value, SchemaAttDef attdef) inline private
Definition at line 657 of file XsdValidator.cs.
    {
        try
        {
            reader.TypedValueObject = null;
            bool flag = attdef != null;
            XmlSchemaDatatype xmlSchemaDatatype = (flag ? attdef.Datatype : context.ElementDecl.Datatype);
            if (xmlSchemaDatatype == null)
            {
                return;
            }
            object obj = xmlSchemaDatatype.ParseValue(value, base.NameTable, _nsManager, createAtomicValue: true);
            XmlTokenizedType tokenizedType = xmlSchemaDatatype.TokenizedType;
            if (tokenizedType == XmlTokenizedType.ENTITY || tokenizedType == XmlTokenizedType.ID || tokenizedType == XmlTokenizedType.IDREF)
            {
                if (xmlSchemaDatatype.Variety == XmlSchemaDatatypeVariety.List)
                {
                    string[] array = (string[])obj;
                    for (int i = 0; i < array.Length; i++)
                    {
                        ProcessTokenizedType(xmlSchemaDatatype.TokenizedType, array[i]);
                    }
                }
                else
                {
                    ProcessTokenizedType(xmlSchemaDatatype.TokenizedType, (string)obj);
                }
            }
            SchemaDeclBase schemaDeclBase = (flag ? ((SchemaDeclBase)attdef) : ((SchemaDeclBase)context.ElementDecl));
            if (!schemaDeclBase.CheckValue(obj))
            {
                if (flag)
                {
                    SendValidationEvent(System.SR.Sch_FixedAttributeValue, attdef.Name.ToString());
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_FixedElementValue, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
                }
            }
            if (xmlSchemaDatatype.Variety == XmlSchemaDatatypeVariety.Union)
            {
                obj = UnWrapUnion(obj);
            }
            reader.TypedValueObject = obj;
        }
        catch (XmlSchemaException)
        {
            if (attdef != null)
            {
                SendValidationEvent(System.SR.Sch_AttributeValueDataType, attdef.Name.ToString());
            }
            else
            {
                SendValidationEvent(System.SR.Sch_ElementValueDataType, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
            }
        }
    }
References System.Xml.Schema.XsdValidator._nsManager, System.array, System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.Datatype, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.obj, System.Xml.Schema.XmlSchemaDatatype.ParseValue(), System.Xml.Schema.XsdValidator.ProcessTokenizedType(), System.Xml.Schema.XmlSchemaValidator.QNameString(), System.SR.Sch_AttributeValueDataType, System.SR.Sch_ElementValueDataType, System.SR.Sch_FixedAttributeValue, System.SR.Sch_FixedElementValue, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.XsdValidator.UnWrapUnion(), and System.value.
Referenced by System.Xml.Schema.XsdValidator.ValidateEndElement(), and System.Xml.Schema.XsdValidator.ValidateStartElement().