Terraria: System.Xml.Schema.XsdValidator.ProcessTokenizedType
ProcessTokenizedType()
void System.Xml.Schema.XsdValidator.ProcessTokenizedType (XmlTokenizedType ttype, string name) inline private
Definition at line 626 of file XsdValidator.cs.
    {
        switch (ttype)
        {
        case XmlTokenizedType.ID:
            if (FindId(name) != null)
            {
                SendValidationEvent(System.SR.Sch_DupId, name);
            }
            else
            {
                AddID(name, context.LocalName);
            }
            break;
        case XmlTokenizedType.IDREF:
        {
            object obj = FindId(name);
            if (obj == null)
            {
                _idRefListHead = new IdRefNode(_idRefListHead, name, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition);
            }
            break;
        }
        case XmlTokenizedType.ENTITY:
            BaseValidator.ProcessEntity(schemaInfo, name, this, base.EventHandler, reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition);
            break;
        case XmlTokenizedType.IDREFS:
            break;
        }
    }
References System.Xml.Schema.XsdValidator._idRefListHead, System.Xml.Schema.XsdValidator.AddID(), System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.XsdValidator.FindId(), System.Xml.Schema.ValidationState.LocalName, System.obj, System.Xml.Schema.BaseValidator.ProcessEntity(), System.Xml.Schema.BaseValidator.reader, System.SR.Sch_DupId, System.Xml.Schema.BaseValidator.schemaInfo, and System.Xml.Schema.BaseValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XsdValidator.CheckValue().