Terraria: System.Xml.Schema.XsdValidator.ValidateEndElement
ValidateEndElement()
void System.Xml.Schema.XsdValidator.ValidateEndElement () inline private
Definition at line 328 of file XsdValidator.cs.
    {
        if (_bManageNamespaces)
        {
            _nsManager.PopScope();
        }
        if (context.ElementDecl != null)
        {
            if (!context.IsNill)
            {
                if (context.NeedValidateChildren && !context.ElementDecl.ContentValidator.CompleteValidation(context))
                {
                    XmlSchemaValidator.CompleteValidationError(context, base.EventHandler, reader, reader.BaseURI, base.PositionInfo.LineNumber, base.PositionInfo.LinePosition, null);
                }
                if (checkDatatype && !context.IsNill)
                {
                    string text = ((!hasSibling) ? textString : textValue.ToString());
                    if (text.Length != 0 || context.ElementDecl.DefaultValueTyped == null)
                    {
                        CheckValue(text, null);
                        checkDatatype = false;
                    }
                }
            }
            if (HasIdentityConstraints)
            {
                EndElementIdentityConstraints();
            }
        }
        Pop();
    }
References System.Xml.Schema.XsdValidator._bManageNamespaces, System.Xml.Schema.XsdValidator._nsManager, System.Xml.XmlValidatingReaderImpl.BaseURI, System.Xml.Schema.BaseValidator.checkDatatype, System.Xml.Schema.XsdValidator.CheckValue(), System.Xml.Schema.ContentValidator.CompleteValidation(), System.Xml.Schema.XmlSchemaValidator.CompleteValidationError(), System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Schema.BaseValidator.context, System.Xml.Schema.SchemaDeclBase.DefaultValueTyped, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.XsdValidator.EndElementIdentityConstraints(), System.Xml.Schema.XsdValidator.HasIdentityConstraints, System.Xml.Schema.BaseValidator.hasSibling, System.Xml.Schema.ValidationState.IsNill, System.Xml.Schema.ValidationState.NeedValidateChildren, System.Xml.Schema.XsdValidator.Pop(), System.Xml.XmlNamespaceManager.PopScope(), System.Xml.Schema.BaseValidator.reader, System.text, System.Xml.Schema.BaseValidator.textString, System.Xml.Schema.BaseValidator.textValue, and System.Text.StringBuilder.ToString().
Referenced by System.Xml.Schema.XsdValidator.Validate().