Terraria: System.Xml.Schema.XsdValidator.ThoroughGetElementDecl
ThoroughGetElementDecl()
SchemaElementDecl System.Xml.Schema.XsdValidator.ThoroughGetElementDecl (SchemaElementDecl elementDecl, XmlQualifiedName xsiType, string xsiNil) inline private
Definition at line 378 of file XsdValidator.cs.
    {
        if (elementDecl == null)
        {
            elementDecl = schemaInfo.GetElementDecl(elementName);
        }
        if (elementDecl != null)
        {
            if (xsiType.IsEmpty)
            {
                if (elementDecl.IsAbstract)
                {
                    SendValidationEvent(System.SR.Sch_AbstractElement, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
                    elementDecl = null;
                }
            }
            else if (xsiNil != null && xsiNil.Equals("true"))
            {
                SendValidationEvent(System.SR.Sch_XsiNilAndType);
            }
            else
            {
                if (!schemaInfo.ElementDeclsByType.TryGetValue(xsiType, out var value) && xsiType.Namespace == _nsXs)
                {
                    XmlSchemaSimpleType simpleTypeFromXsdType = DatatypeImplementation.GetSimpleTypeFromXsdType(new XmlQualifiedName(xsiType.Name, _nsXs));
                    if (simpleTypeFromXsdType != null)
                    {
                        value = simpleTypeFromXsdType.ElementDecl;
                    }
                }
                if (value == null)
                {
                    SendValidationEvent(System.SR.Sch_XsiTypeNotFound, xsiType.ToString());
                    elementDecl = null;
                }
                else if (!XmlSchemaType.IsDerivedFrom(value.SchemaType, elementDecl.SchemaType, elementDecl.Block))
                {
                    SendValidationEvent(System.SR.Sch_XsiTypeBlockedEx, new string[2]
                    {
                        xsiType.ToString(),
                        XmlSchemaValidator.QNameString(context.LocalName, context.Namespace)
                    });
                    elementDecl = null;
                }
                else
                {
                    elementDecl = value;
                }
            }
            if (elementDecl != null && elementDecl.IsNillable)
            {
                if (xsiNil != null)
                {
                    context.IsNill = XmlConvert.ToBoolean(xsiNil);
                    if (context.IsNill && elementDecl.DefaultValueTyped != null)
                    {
                        SendValidationEvent(System.SR.Sch_XsiNilAndFixed);
                    }
                }
            }
            else if (xsiNil != null)
            {
                SendValidationEvent(System.SR.Sch_InvalidXsiNill);
            }
        }
        return elementDecl;
    }
References System.Xml.Schema.XsdValidator._nsXs, System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.SchemaInfo.ElementDeclsByType, System.Xml.Schema.BaseValidator.elementName, System.Xml.Schema.SchemaInfo.GetElementDecl(), System.Xml.Schema.DatatypeImplementation.GetSimpleTypeFromXsdType(), System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.Xml.Schema.ValidationState.IsNill, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.SR.Sch_AbstractElement, System.SR.Sch_InvalidXsiNill, System.SR.Sch_XsiNilAndFixed, System.SR.Sch_XsiNilAndType, System.SR.Sch_XsiTypeBlockedEx, System.SR.Sch_XsiTypeNotFound, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.XmlConvert.ToBoolean(), and System.value.
Referenced by System.Xml.Schema.XsdValidator.ProcessElement().