Terraria: System.Xml.Schema.XsdValidator.ProcessXsiAttributes
ProcessXsiAttributes()
void System.Xml.Schema.XsdValidator.ProcessXsiAttributes (out XmlQualifiedName xsiType, out string xsiNil) inline private
Definition at line 264 of file XsdValidator.cs.
    {
        string[] array = null;
        string text = null;
        xsiType = XmlQualifiedName.Empty;
        xsiNil = null;
        if (reader.Depth == 0)
        {
            LoadSchema(string.Empty, null);
            foreach (string value in _nsManager.GetNamespacesInScope(XmlNamespaceScope.ExcludeXml).Values)
            {
                LoadSchema(value, null);
            }
        }
        if (reader.MoveToFirstAttribute())
        {
            do
            {
                string namespaceURI = reader.NamespaceURI;
                string localName = reader.LocalName;
                if (Ref.Equal(namespaceURI, _nsXmlNs))
                {
                    LoadSchema(reader.Value, null);
                    if (_bManageNamespaces)
                    {
                        _nsManager.AddNamespace((reader.Prefix.Length == 0) ? string.Empty : reader.LocalName, reader.Value);
                    }
                }
                else if (Ref.Equal(namespaceURI, _nsXsi))
                {
                    if (Ref.Equal(localName, _xsiSchemaLocation))
                    {
                        array = (string[])s_dtStringArray.ParseValue(reader.Value, base.NameTable, _nsManager);
                    }
                    else if (Ref.Equal(localName, _xsiNoNamespaceSchemaLocation))
                    {
                        text = reader.Value;
                    }
                    else if (Ref.Equal(localName, _xsiType))
                    {
                        xsiType = (XmlQualifiedName)s_dtQName.ParseValue(reader.Value, base.NameTable, _nsManager);
                    }
                    else if (Ref.Equal(localName, _xsiNil))
                    {
                        xsiNil = reader.Value;
                    }
                }
            }
            while (reader.MoveToNextAttribute());
            reader.MoveToElement();
        }
        if (text != null)
        {
            LoadSchema(string.Empty, text);
        }
        if (array != null)
        {
            for (int i = 0; i < array.Length - 1; i += 2)
            {
                LoadSchema(array[i], array[i + 1]);
            }
        }
    }
References System.Xml.Schema.XsdValidator._bManageNamespaces, System.Xml.Schema.XsdValidator._nsManager, System.Xml.Schema.XsdValidator._nsXmlNs, System.Xml.Schema.XsdValidator._nsXsi, System.Xml.Schema.XsdValidator._xsiNil, System.Xml.Schema.XsdValidator._xsiNoNamespaceSchemaLocation, System.Xml.Schema.XsdValidator._xsiSchemaLocation, System.Xml.Schema.XsdValidator._xsiType, System.Xml.XmlNamespaceManager.AddNamespace(), System.array, System.Xml.XmlValidatingReaderImpl.Depth, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.Ref.Equal(), System.Xml.XmlNamespaceManager.GetNamespacesInScope(), System.Xml.Schema.XsdValidator.LoadSchema(), System.Xml.XmlValidatingReaderImpl.LocalName, System.Xml.XmlValidatingReaderImpl.MoveToElement(), System.Xml.XmlValidatingReaderImpl.MoveToFirstAttribute(), System.Xml.XmlValidatingReaderImpl.MoveToNextAttribute(), System.Xml.XmlValidatingReaderImpl.NamespaceURI, System.Xml.XmlValidatingReaderImpl.Prefix, System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.XsdValidator.s_dtQName, System.Xml.Schema.XsdValidator.s_dtStringArray, System.text, System.value, System.Xml.XmlValidatingReaderImpl.Value, and System.Collections.IDictionary.Values.
Referenced by System.Xml.Schema.XsdValidator.ProcessElement().