Terraria: System.Xml.Schema.XsdValidator.ProcessInlineSchema
ProcessInlineSchema()
void System.Xml.Schema.XsdValidator.ProcessInlineSchema () inline private
Definition at line 152 of file XsdValidator.cs.
    {
        if (_inlineSchemaParser.ParseReaderNode())
        {
            return;
        }
        _inlineSchemaParser.FinishParsing();
        XmlSchema xmlSchema = _inlineSchemaParser.XmlSchema;
        string text = null;
        if (xmlSchema != null && xmlSchema.ErrorCount == 0)
        {
            try
            {
                SchemaInfo schemaInfo = new SchemaInfo();
                schemaInfo.SchemaType = SchemaType.XSD;
                text = ((xmlSchema.TargetNamespace == null) ? string.Empty : xmlSchema.TargetNamespace);
                if (!base.SchemaInfo.TargetNamespaces.ContainsKey(text) && base.SchemaCollection.Add(text, schemaInfo, xmlSchema, compile: true) != null)
                {
                    base.SchemaInfo.Add(schemaInfo, base.EventHandler);
                }
            }
            catch (XmlSchemaException ex)
            {
                SendValidationEvent(System.SR.Sch_CannotLoadSchema, new string[2]
                {
                    base.BaseUri.AbsoluteUri,
                    ex.Message
                }, XmlSeverityType.Error);
            }
        }
        _inlineSchemaParser = null;
    }
References System.Xml.Schema.XsdValidator._inlineSchemaParser, System.Xml.Dictionary, System.Xml.Schema.Parser.FinishParsing(), System.Xml.Schema.Parser.ParseReaderNode(), System.SR.Sch_CannotLoadSchema, System.Xml.Schema.BaseValidator.schemaInfo, System.Xml.Schema.BaseValidator.SchemaInfo, System.Xml.Schema.BaseValidator.SendValidationEvent(), System.text, and System.Xml.Schema.Parser.XmlSchema.
Referenced by System.Xml.Schema.XsdValidator.Validate(), and System.Xml.Schema.XsdValidator.ValidateElement().