Terraria: System.Runtime.CompilerServices.FormattableStringFactory.Create
Create()
static FormattableString System.Runtime.CompilerServices.FormattableStringFactory.Create (string format, params object?[] arguments) inline static
Definition at line 37 of file FormattableStringFactory.cs.
    {
        if (format == null)
        {
            throw new ArgumentNullException("format");
        }
        if (arguments == null)
        {
            throw new ArgumentNullException("arguments");
        }
        return new ConcreteFormattableString(format, arguments);
    }
References System.format.
Referenced by System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsyncCore(), System.Net.Security.SafeFreeCredentials.AcquireCredentialsHandle(), System.Net.Security.SafeFreeCredentials.AcquireCredentialsHandle(), System.Net.Security.SafeFreeCredentials.AcquireDefaultCredential(), System.Net.Security.SafeFreeCredentials.AcquireDefaultCredential(), System.Net.HttpListenerResponse.ComputeCookies(), System.Net.CredentialCache.GetCredential(), System.Net.CredentialCache.GetCredential(), System.Net.Mail.SmtpClient.GetFileMailWriter(), System.Net.HttpListenerContext.GetKnownMethod(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventRecv(), System.Net.HttpListenerContext.SetIdentity(), System.Net.TimerThread.ThreadProc(), and System.Net.Http.HttpWindowsProxy.TryCreate().