Terraria: Terraria.Social.WeGame.WeGameHelper.WriteDebugString
WriteDebugString()
static void Terraria.Social.WeGame.WeGameHelper.WriteDebugString (string format, params object[] args) inline static
Definition at line 13 of file WeGameHelper.cs.
    {
        _ = "[WeGame] - " + format;
    }
Referenced by Terraria.Social.WeGame.NetServerSocialModule.AcceptAnUserSession(), Terraria.Social.WeGame.IPCBase.BeginReadData(), Terraria.Social.WeGame.NetClientSocialModule.CheckParameters(), Terraria.Social.WeGame.NetClientSocialModule.Close(), Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState(), Terraria.Social.WeGame.IPCServer.ConnectionCallback(), Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby(), Terraria.Social.WeGame.IPCServer.ContinueReadOrWait(), Terraria.Social.WeGame.NetSocialModule.GetSessionState(), Terraria.Social.WeGame.FriendsSocialModule.GetUsername(), Terraria.Social.WeGame.Lobby.Join(), Terraria.Social.WeGame.NetClientSocialModule.JoinServer(), Terraria.Social.Steam.NetClientSocialModule.LaunchLocalServer(), Terraria.Social.WeGame.NetClientSocialModule.LaunchLocalServer(), Terraria.Social.SocialAPI.LoadSteam(), Terraria.Social.SocialAPI.LoadWeGame(), Terraria.Social.WeGame.NetClientSocialModule.OnAuthSuccess(), Terraria.Social.WeGame.NetServerSocialModule.OnConnected(), Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionFailed(), Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionRequest(), Terraria.Social.WeGame.NetClientSocialModule.OnGetFriendMetaData(), Terraria.Social.WeGame.NetClientSocialModule.OnIPCClientAccess(), Terraria.Social.WeGame.NetServerSocialModule.OnLobbyCreated(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), Terraria.Social.Steam.NetClientSocialModule.OnP2PSessionRequest(), Terraria.Social.WeGame.NetClientSocialModule.OnPacketRead(), Terraria.Social.WeGame.NetServerSocialModule.OnPacketRead(), Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionFailed(), Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionRequest(), Terraria.Social.WeGame.NetServerSocialModule.OnRailEvent(), Terraria.Social.WeGame.Lobby.OnRailEvent(), Terraria.Social.WeGame.NetClientSocialModule.OnRailEvent(), Terraria.Social.WeGame.NetClientSocialModule.OnRailRespondInvation(), Terraria.Social.WeGame.NetClientSocialModule.OnRailSetMetaData(), Terraria.Social.WeGame.NetClientSocialModule.OnReportServerID(), Terraria.Social.Steam.NetClientSocialModule.OnSessionConnectFail(), Terraria.Social.WeGame.Lobby.OpenInviteOverlay(), Terraria.Social.WeGame.FriendsSocialModule.OpenJoinInterface(), Terraria.Social.WeGame.IPCBase.ReadCallback(), Terraria.Social.WeGame.IPCClient.ReadCallback(), Terraria.Social.WeGame.IPCServer.ReadCallback(), Terraria.Social.WeGame.IPCBase.Send(), Terraria.Social.Steam.NetClientSocialModule.SendAuthTicket(), Terraria.Social.WeGame.IPCBase.SendCallback(), Terraria.Social.WeGame.NetClientSocialModule.SendFriendListToLocalServer(), Terraria.Social.WeGame.IPCServer.StartListen(), Terraria.Social.WeGame.NetClientSocialModule.TryAuthUserByRecvData(), Terraria.Social.WeGame.NetServerSocialModule.TryAuthUserByRecvData(), Terraria.Social.WeGame.NetServerSocialModule.UpdateFriendList(), and Terraria.Social.WeGame.NetServerSocialModule.UpdateUserStateBySessionAuthResult().