Terraria: Netplay.KickClient
KickClient()
static void Netplay.KickClient (ISocket client, NetworkText kickMessage) inline static private
     {
         BinaryWriter writer = fullBuffer.writer;
         if (writer == null)
         {
             fullBuffer.ResetWriter();
             writer = fullBuffer.writer;
         }
         writer.BaseStream.Position = 0L;
         long position = writer.BaseStream.Position;
         writer.BaseStream.Position += 2L;
         writer.Write((byte)2);
         kickMessage.Serialize(writer);
         if (Main.dedServ)
         {
             Console.WriteLine(Language.GetTextValue("CLI.ClientWasBooted", client.GetRemoteAddress().ToString(), kickMessage));
         }
         int num = (int)writer.BaseStream.Position;
         writer.BaseStream.Position = position;
         writer.Write((short)num);
         writer.BaseStream.Position = num;
         client.AsyncSend(fullBuffer.writeBuffer, 0, num, ServerFullWriteCallBack, client);
     }
References ISocket.AsyncSend(), Main.dedServ, fullBuffer, ISocket.GetRemoteAddress(), Language.GetTextValue(), L, MessageBuffer.ResetWriter(), NetworkText.Serialize(), ServerFullWriteCallBack(), MessageBuffer.writeBuffer, and MessageBuffer.writer.
Referenced by OnConnectionAccepted().