Terraria: NetClientSocialModule.LaunchLocalServer
LaunchLocalServer() [2/2]
override void NetClientSocialModule.LaunchLocalServer (Process process, ServerMode mode) inline virtual
Implements NetSocialModule.
     {
         //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
         if (_lobby.State != 0)
         {
             _lobby.Leave();
         }
         LazyCreateWeGameMsgServer();
         ProcessStartInfo startInfo = process.StartInfo;
         startInfo.Arguments = startInfo.Arguments + " -wegame -localwegameid " + ((RailComparableID)GetLocalPeer()).id_;
         if (mode.HasFlag(ServerMode.Lobby))
         {
             _hasLocalHost = true;
             if (mode.HasFlag(ServerMode.FriendsCanJoin))
             {
                 process.StartInfo.Arguments += " -lobby friends";
             }
             else
             {
                 process.StartInfo.Arguments += " -lobby private";
             }
             if (mode.HasFlag(ServerMode.FriendsOfFriends))
             {
                 process.StartInfo.Arguments += " -friendsoffriends";
             }
         }
         string text = default(string);
         rail_api.RailFactory().RailUtils().GetLaunchAppParameters((EnumRailLaunchAppType)2, ref text);
         ProcessStartInfo startInfo2 = process.StartInfo;
         startInfo2.Arguments = startInfo2.Arguments + " " + text;
         WeGameHelper.WriteDebugString("LaunchLocalServer,cmd_line:" + process.StartInfo.Arguments);
         AsyncSetMyMetaData("status", Language.GetTextValue("Social.StatusInGame"));
         Netplay.OnDisconnect += OnDisconnect;
         process.Start();
     }
References _hasLocalHost, NetSocialModule._lobby, AsyncSetMyMetaData(), NetSocialModule.GetLocalPeer(), Language.GetTextValue(), LazyCreateWeGameMsgServer(), Lobby.Leave(), OnDisconnect(), Netplay.OnDisconnect, Lobby.State, and WeGameHelper.WriteDebugString().