Terraria: Netplay.UpdateConnectedClients
UpdateConnectedClients()
static void Netplay.UpdateConnectedClients () inline static private
     {
         int num = 0;
         for (int i = 0; i < 256; i++)
         {
             if (Clients[i].PendingTermination)
             {
                 if (Clients[i].PendingTerminationApproved)
                 {
                     Clients[i].Reset();
                     NetMessage.SyncDisconnectedPlayer(i);
                 }
                 continue;
             }
             if (Clients[i].IsConnected())
             {
                 Clients[i].Update();
                 num++;
                 continue;
             }
             if (Clients[i].IsActive)
             {
                 Clients[i].PendingTermination = true;
                 Clients[i].PendingTerminationApproved = true;
                 continue;
             }
             Clients[i].StatusText2 = "";
             if (i < 255)
             {
                 bool active = Main.player[i].active;
                 Main.player[i].active = false;
                 if (active)
                 {
                     Player.Hooks.PlayerDisconnect(i);
                 }
             }
         }
         HasClients = num != 0;
     }
References Entity.active, Clients, HasClients, RemoteClient.PendingTermination, RemoteClient.PendingTerminationApproved, Main.player, Player.Hooks.PlayerDisconnect(), RemoteClient.Reset(), RemoteClient.StatusText2, NetMessage.SyncDisconnectedPlayer(), and RemoteClient.Update().
Referenced by ServerLoop().