Terraria: NetClientSocialModule.Close
Close() [2/4]
void NetClientSocialModule.Close (RailID remote_peer) inline private
     {
         //IL_003e: Unknown result type (might be due to invalid IL or missing references)
         if (_connectionStateMap.ContainsKey(remote_peer))
         {
             WeGameHelper.WriteDebugString("CloseRemotePeer, remote:{0}", ((RailComparableID)remote_peer).id_);
             rail_api.RailFactory().RailNetworkHelper().CloseSession(GetLocalPeer(), remote_peer);
             _connectionStateMap[remote_peer] = ConnectionState.Inactive;
             _lobby.Leave();
             _reader.ClearUser(remote_peer);
             _writer.ClearUser(remote_peer);
         }
     }
References NetSocialModule._connectionStateMap, NetSocialModule._lobby, NetSocialModule._reader, NetSocialModule._writer, SteamP2PReader.ClearUser(), SteamP2PWriter.ClearUser(), NetSocialModule.GetLocalPeer(), Lobby.Leave(), and WeGameHelper.WriteDebugString().