Terraria: Netplay.StartListeningIfNeeded
StartListeningIfNeeded()
static void Netplay.StartListeningIfNeeded () inline static private
     {
         if (IsListening || !Clients.Any((RemoteClient client) => !client.IsConnected()))
         {
             return;
         }
         try
         {
             StartListening();
             IsListening = true;
         }
         catch
         {
             if (!Main.ignoreErrors)
             {
                 throw;
             }
         }
     }
References Clients, Main.ignoreErrors, RemoteClient.IsConnected(), IsListening, and StartListening().
Referenced by ServerLoop().