Terraria: NetClientSocialModule.ConnectToLobby
ConnectToLobby()
void NetClientSocialModule.ConnectToLobby (ulong lobbyId) inline
     {
         //IL_000f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0014: Unknown result type (might be due to invalid IL or missing references)
         CSteamID lobbySteamId = new CSteamID(lobbyId);
         if (((CSteamID)(ref lobbySteamId)).IsValid())
         {
             Main.OpenPlayerSelect(delegate(PlayerFileData playerData)
             {
                 //IL_0041: Unknown result type (might be due to invalid IL or missing references)
                 Main.ServerSideCharacter = false;
                 playerData.SetAsActive();
                 Main.menuMode = 882;
                 Main.statusText = Language.GetTextValue("Social.Joining");
                 WeGameHelper.WriteDebugString(" CheckParameters， lobby.join");
                 _lobby.Join(lobbySteamId, OnLobbyEntered);
             });
         }
     }
References NetSocialModule._lobby, Language.GetTextValue(), Lobby.Join(), Main.menuMode, OnLobbyEntered(), Main.OpenPlayerSelect(), Main.ServerSideCharacter, PlayerFileData.SetAsActive(), Main.statusText, and WeGameHelper.WriteDebugString().
Referenced by CheckParameters().