Terraria: Netplay.OnConnectionAccepted
OnConnectionAccepted()
static void Netplay.OnConnectionAccepted (ISocket client) inline static private
     {
         int num = FindNextOpenClientSlot();
         if (num != -1)
         {
             Clients[num].Reset();
             Clients[num].Socket = client;
         }
         else
         {
             lock (fullBuffer)
             {
                 KickClient(client, NetworkText.FromKey("CLI.ServerIsFull"));
             }
         }
         if (FindNextOpenClientSlot() == -1)
         {
             StopListening();
             IsListening = false;
         }
     }
References Clients, FindNextOpenClientSlot(), NetworkText.FromKey(), fullBuffer, IsListening, KickClient(), RemoteClient.Reset(), RemoteClient.Socket, and StopListening().
Referenced by StartListening().