Terraria: Netplay.InnerClientLoop
InnerClientLoop()
static void Netplay.InnerClientLoop () inline static private
     {
         try
         {
             NetMessage.buffer[256].Reset();
             int num = -1;
             while (!Disconnect)
             {
                 if (Connection.Socket.IsConnected())
                 {
                     if (Connection.ServerWantsToRunCheckBytesInClientLoopThread && NetMessage.buffer[256].checkBytes)
                     {
                         NetMessage.CheckBytes();
                     }
                     Connection.IsActive = true;
                     if (Connection.State == 0)
                     {
                         Main.statusText = Language.GetTextValue("Net.FoundServer");
                         Connection.State = 1;
                         NetMessage.SendData(1);
                     }
                     if (Connection.State == 2 && num != Connection.State)
                     {
                         Main.statusText = Language.GetTextValue("Net.SendingPlayerData");
                     }
                     if (Connection.State == 3 && num != Connection.State)
                     {
                         Main.statusText = Language.GetTextValue("Net.RequestingWorldInformation");
                     }
                     if (Connection.State == 4)
                     {
                         WorldGen.worldCleared = false;
                         Connection.State = 5;
                         if (Main.cloudBGActive >= 1f)
{
                             Main.cloudBGAlpha = 1f;
                         }
                         else
{
                             Main.cloudBGAlpha = 0f;
                         }
                         Main.windSpeedCurrent = Main.windSpeedTarget;
                         Cloud.resetClouds();
                         Main.cloudAlpha = Main.maxRaining;
                         Main.ToggleGameplayUpdates(state: false);
                         WorldGen.clearWorld();
                         if (Main.mapEnabled)
{
                             Main.Map.Load();
                         }
                     }
                     if (Connection.State == 5 && Main.loadMapLock)
                     {
                         float num2 = (float)Main.loadMapLastX / (float)Main.maxTilesX;
                         Main.statusText = Lang.gen[68].Value + " " + (int)(num2 * 100f + 1f) + "%";
                     }
                     else if (Connection.State == 5 && WorldGen.worldCleared)
                     {
                         Connection.State = 6;
                         Main.player[Main.myPlayer].FindSpawn();
                         NetMessage.SendData(8, -1, -1, null, Main.player[Main.myPlayer].SpawnX, Main.player[Main.myPlayer].SpawnY);
                     }
                     if (Connection.State == 6 && num != Connection.State)
                     {
                         Main.statusText = Language.GetTextValue("Net.RequestingTileData");
                     }
                     if (!Connection.IsReading && !Disconnect && Connection.Socket.IsDataAvailable())
                     {
                         Connection.IsReading = true;
                         Connection.Socket.AsyncReceive(Connection.ReadBuffer, 0, Connection.ReadBuffer.Length, Connection.ClientReadCallBack);
                     }
                     if (Connection.StatusMax > 0 && Connection.StatusText != "")
                     {
                         if (Connection.StatusCount >= Connection.StatusMax)
{
                             Main.statusText = Language.GetTextValue("Net.StatusComplete", Connection.StatusText);
                             Connection.StatusText = "";
                             Connection.StatusMax = 0;
                             Connection.StatusCount = 0;
                         }
                         else
{
                             Main.statusText = Connection.StatusText + ": " + (int)((float)Connection.StatusCount / (float)Connection.StatusMax * 100f) + "%";
                         }
                     }
                     Thread.Sleep(1);
                 }
                 else if (Connection.IsActive)
                 {
                     Main.statusText = Language.GetTextValue("Net.LostConnection");
                     Disconnect = true;
                 }
                 num = Connection.State;
             }
             try
             {
                 Connection.Socket.Close();
             }
             catch
             {
             }
             if (!Main.gameMenu)
             {
                 Main.gameMenu = true;
                 Main.SwitchNetMode(0);
                 MapHelper.noStatusText = true;
                 Player.SavePlayer(Main.ActivePlayerFileData);
                 Player.ClearPlayerTempInfo();
                 Main.ActivePlayerFileData.StopPlayTimer();
                 SoundEngine.StopTrackedSounds();
                 MapHelper.noStatusText = false;
                 Main.menuMode = 14;
             }
             NetMessage.buffer[256].Reset();
             if (Main.menuMode == 15 && Main.statusText == Language.GetTextValue("Net.LostConnection"))
             {
                 Main.menuMode = 14;
             }
             if (Connection.StatusText != "" && Connection.StatusText != null)
             {
                 Main.statusText = Language.GetTextValue("Net.LostConnection");
             }
             Connection.StatusCount = 0;
             Connection.StatusMax = 0;
             Connection.StatusText = "";
             Main.SwitchNetMode(0);
         }
         catch (Exception value)
         {
             try
             {
                 using StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", append: true);
                 streamWriter.WriteLine(DateTime.Now);
                 streamWriter.WriteLine(value);
                 streamWriter.WriteLine("");
             }
             catch
             {
             }
             Disconnect = true;
         }
         if (Netplay.OnDisconnect != null)
         {
             Netplay.OnDisconnect();
         }
     }
References Main.ActivePlayerFileData, ISocket.AsyncReceive(), NetMessage.buffer, MessageBuffer.checkBytes, NetMessage.CheckBytes(), Player.ClearPlayerTempInfo(), WorldGen.clearWorld(), RemoteServer.ClientReadCallBack(), ISocket.Close(), Main.cloudAlpha, Main.cloudBGActive, Main.cloudBGAlpha, Connection, Disconnect, Player.FindSpawn(), Main.gameMenu, Lang.gen, Language.GetTextValue(), RemoteServer.IsActive, ISocket.IsConnected(), ISocket.IsDataAvailable(), RemoteServer.IsReading, WorldMap.Load(), Main.loadMapLastX, Main.loadMapLock, Main.Map, Main.mapEnabled, Main.maxRaining, Main.maxTilesX, Main.menuMode, Main.myPlayer, MapHelper.noStatusText, OnDisconnect, Main.player, RemoteServer.ReadBuffer, MessageBuffer.Reset(), Cloud.resetClouds(), Player.SavePlayer(), NetMessage.SendData(), RemoteServer.ServerWantsToRunCheckBytesInClientLoopThread, RemoteServer.Socket, Player.SpawnX, Player.SpawnY, RemoteServer.State, RemoteServer.StatusCount, RemoteServer.StatusMax, Main.statusText, RemoteServer.StatusText, PlayerFileData.StopPlayTimer(), SoundEngine.StopTrackedSounds(), Main.SwitchNetMode(), Main.ToggleGameplayUpdates(), LocalizedText.Value, Main.windSpeedCurrent, Main.windSpeedTarget, and WorldGen.worldCleared.
Referenced by SocialClientLoop(), and TcpClientLoop().