Terraria: Netplay.SetRemoteIPAsync
SetRemoteIPAsync()
static void Netplay.SetRemoteIPAsync (string remoteAddress, Action successCallBack) inline static
     {
         try
         {
             if (IPAddress.TryParse(remoteAddress, out var address))
             {
                 ServerIP = address;
                 ServerIPText = address.ToString();
                 successCallBack();
             }
             else
             {
                 InvalidateAllOngoingIPSetAttempts();
                 Dns.BeginGetHostAddresses(remoteAddress, SetRemoteIPAsyncCallback, new SetRemoteIPRequestInfo
                 {
                     RequestId = _currentRequestId,
                     SuccessCallback = successCallBack,
                     RemoteAddress = remoteAddress
                 });
             }
         }
         catch (Exception)
         {
         }
     }
References _currentRequestId, InvalidateAllOngoingIPSetAttempts(), ServerIP, ServerIPText, and SetRemoteIPAsyncCallback().
Referenced by Main.DrawMenu(), and Main.OnSubmitServerPort().