Terraria: Netplay.UpdateInMainThread
UpdateInMainThread()
static void Netplay.UpdateInMainThread () inline static
     {
         if (Main.dedServ)
         {
             UpdateServerInMainThread();
         }
         else
         {
             UpdateClientInMainThread();
         }
     }
References Main.dedServ, UpdateClientInMainThread(), and UpdateServerInMainThread().
Referenced by Main.DoUpdate().