Terraria: NetClientSocialModule.SendFriendListToLocalServer
SendFriendListToLocalServer()
bool NetClientSocialModule.SendFriendListToLocalServer () inline private
     {
         bool result = false;
         if (_hasLocalHost)
         {
             List<RailFriendInfo> list = new List<RailFriendInfo>();
             if (GetRailFriendList(list))
             {
                 WeGameFriendListInfo t = new WeGameFriendListInfo
                 {
                     _friendList = list
                 };
                 IPCMessage iPCMessage = new IPCMessage();
                 iPCMessage.Build(IPCMessageType.IPCMessageTypeNotifyFriendList, t);
                 result = _msgServer.SendMessage(iPCMessage);
                 WeGameHelper.WriteDebugString("NotifyFriendListToServer: " + result);
             }
         }
         return result;
     }
References _hasLocalHost, _msgServer, GetRailFriendList(), MessageDispatcherServer.SendMessage(), and WeGameHelper.WriteDebugString().
Referenced by OnFriendlistChange(), and OnIPCClientAccess().