Terraria: System.Xml.Serialization.XmlSerializationReader.ReadElementQualifiedName
ReadElementQualifiedName()
XmlQualifiedName System.Xml.Serialization.XmlSerializationReader.ReadElementQualifiedName () inline protected
Definition at line 1075 of file XmlSerializationReader.cs.
    {
        if (_r.IsEmptyElement)
        {
            XmlQualifiedName result = new XmlQualifiedName(string.Empty, _r.LookupNamespace(""));
            _r.Skip();
            return result;
        }
        XmlQualifiedName result2 = ToXmlQualifiedName(CollapseWhitespace(_r.ReadString()));
        _r.ReadEndElement();
        return result2;
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.CollapseWhitespace, System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LookupNamespace(), System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlReader.ReadString(), System.Xml.XmlReader.Skip(), and System.Xml.Serialization.XmlSerializationReader.ToXmlQualifiedName().
Referenced by System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_QName(), System.Xml.Serialization.XmlSerializationReader.ReadNullableQualifiedName(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement().