Terraria: System.Xml.Serialization.XmlSerializationReader.ReadByteArray
ReadByteArray()
byte[] System.Xml.Serialization.XmlSerializationReader.ReadByteArray (bool isBase64) inline private
Definition at line 633 of file XmlSerializationReader.cs.
    {
        ArrayList arrayList = new ArrayList();
        int num = 1024;
        int num2 = -1;
        int num3 = 0;
        int num4 = 0;
        byte[] array = new byte[num];
        arrayList.Add(array);
        while (num2 != 0)
        {
            if (num3 == array.Length)
            {
                num = Math.Min(num * 2, 65536);
                array = new byte[num];
                num3 = 0;
                arrayList.Add(array);
            }
            num2 = ((!isBase64) ? _r.ReadElementContentAsBinHex(array, num3, array.Length - num3) : _r.ReadElementContentAsBase64(array, num3, array.Length - num3));
            num3 += num2;
            num4 += num2;
        }
        byte[] array2 = new byte[num4];
        num3 = 0;
        foreach (byte[] item in arrayList)
        {
            num = Math.Min(item.Length, num4);
            if (num > 0)
            {
                Buffer.BlockCopy(item, 0, array2, num3, num);
                num3 += num;
                num4 -= num;
            }
        }
        arrayList.Clear();
        return array2;
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Buffer.BlockCopy(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.Dictionary, System.item, System.Math.Min(), System.Xml.XmlReader.ReadElementContentAsBase64(), and System.Xml.XmlReader.ReadElementContentAsBinHex().
Referenced by System.Xml.Serialization.XmlSerializationReader.ToByteArrayBase64(), and System.Xml.Serialization.XmlSerializationReader.ToByteArrayHex().