Terraria: System.Xml.Serialization.XmlSerializationReader.ShrinkArray
ShrinkArray()
Array? System.Xml.Serialization.XmlSerializationReader.ShrinkArray (Array? a, int length, Type elementType, bool isNullable) inline protected
Definition at line 1588 of file XmlSerializationReader.cs.
    {
        if (a == null)
        {
            if (isNullable)
            {
                return null;
            }
            return Array.CreateInstance(elementType, 0);
        }
        if (a.Length == length)
        {
            return a;
        }
        Array array = Array.CreateInstance(elementType, length);
        Array.Copy(a, array, length);
        return array;
    }
References System.array, System.Array.Copy(), System.Array.CreateInstance(), System.Xml.Dictionary, System.elementType, and System.length.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadArray().