Terraria: System.Xml.Serialization.XmlSerializationReader.UnknownNode
UnknownNode() [2/3]
void System.Xml.Serialization.XmlSerializationReader.UnknownNode (object? o, string? qnames) inline protected
Definition at line 1422 of file XmlSerializationReader.cs.
    {
        if (_r.NodeType == XmlNodeType.None || _r.NodeType == XmlNodeType.Whitespace)
        {
            _r.Read();
        }
        else
        {
            if (_r.NodeType == XmlNodeType.EndElement)
            {
                return;
            }
            if (_events.OnUnknownNode != null)
            {
                UnknownNode(Document.ReadNode(_r), o, qnames);
            }
            else if (_r.NodeType != XmlNodeType.Attribute || _events.OnUnknownAttribute != null)
            {
                if (_r.NodeType == XmlNodeType.Element && _events.OnUnknownElement == null)
                {
                    _r.Skip();
                }
                else
                {
                    UnknownNode(Document.ReadNode(_r), o, qnames);
                }
            }
        }
    }
References System.Xml.Serialization.XmlSerializationReader._events, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader.Document, System.Xml.XmlReader.NodeType, System.Xml.Serialization.XmlDeserializationEvents.OnUnknownAttribute, System.Xml.Serialization.XmlDeserializationEvents.OnUnknownElement, System.Xml.Serialization.XmlDeserializationEvents.OnUnknownNode, System.Xml.XmlReader.Read(), System.Xml.XmlDocument.ReadNode(), System.Xml.XmlReader.Skip(), and System.Xml.Serialization.XmlSerializationReader.UnknownNode().