Terraria: System.Xml.Serialization.XmlSerializationReader.ReadEndElement
ReadEndElement()
void System.Xml.Serialization.XmlSerializationReader.ReadEndElement () inline protected
Definition at line 2116 of file XmlSerializationReader.cs.
    {
        while (_r.NodeType == XmlNodeType.Whitespace)
        {
            _r.Skip();
        }
        if (_r.NodeType == XmlNodeType.None)
        {
            _r.Skip();
        }
        else
        {
            _r.ReadEndElement();
        }
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadEndElement(), and System.Xml.XmlReader.Skip().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReader.ReadArray(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.XmlSerializationReader.ReadReference(), System.Xml.Serialization.XmlSerializationReader.ReadStringValue(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNodes(), System.Xml.Serialization.XmlSerializationReader.ReadXmlQualifiedName(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEnumAndArrayTypes(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().