Terraria: System.Xml.Serialization.XmlSerializationReader.UnknownNode
UnknownNode() [1/3]
void System.Xml.Serialization.XmlSerializationReader.UnknownNode (object? o) inline protected
Definition at line 1417 of file XmlSerializationReader.cs.
    {
        UnknownNode(o, null);
    }
References System.Xml.Serialization.XmlSerializationReader.UnknownNode().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.DummyReadArrayMethod(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_base64Binary(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_boolean(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_byte(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_char(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_dateTime(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_dateTimeOffset(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_decimal(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_double(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_float(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_guid(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_int(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_long(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_QName(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_short(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_string(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_TimeSpan(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedByte(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedInt(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedLong(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedShort(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNode(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNodes(), System.Xml.Serialization.XmlSerializationReader.UnknownNode(), System.Xml.Serialization.XmlSerializationReader.UnknownNode(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().