Terraria: System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive
ReadTypedPrimitive() [2/2]
object System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive (XmlQualifiedName type, bool elementCanBeType) inline private
Definition at line 676 of file XmlSerializationReader.cs.
    {
        InitPrimitiveIDs();
        object obj = null;
        if (!IsPrimitiveNamespace(type.Namespace) || (object)type.Name == _urTypeID)
        {
            return ReadXmlNodes(elementCanBeType);
        }
        if ((object)type.Namespace == _schemaNsID || (object)type.Namespace == _soapNsID || (object)type.Namespace == _soap12NsID)
        {
            if ((object)type.Name == _stringID || (object)type.Name == _normalizedStringID)
            {
                return ReadStringValue();
            }
            if ((object)type.Name == _anyURIID || (object)type.Name == _durationID || (object)type.Name == _ENTITYID || (object)type.Name == _ENTITIESID || (object)type.Name == _gDayID || (object)type.Name == _gMonthID || (object)type.Name == _gMonthDayID || (object)type.Name == _gYearID || (object)type.Name == _gYearMonthID || (object)type.Name == _IDID || (object)type.Name == _IDREFID || (object)type.Name == _IDREFSID || (object)type.Name == _integerID || (object)type.Name == _languageID || (object)type.Name == _nameID || (object)type.Name == _NCNameID || (object)type.Name == _NMTOKENID || (object)type.Name == _NMTOKENSID || (object)type.Name == _negativeIntegerID || (object)type.Name == _nonPositiveIntegerID || (object)type.Name == _nonNegativeIntegerID || (object)type.Name == _NOTATIONID || (object)type.Name == _positiveIntegerID || (object)type.Name == _tokenID)
            {
                return CollapseWhitespace(ReadStringValue());
            }
            if ((object)type.Name == _intID)
            {
                return XmlConvert.ToInt32(ReadStringValue());
            }
            if ((object)type.Name == _booleanID)
            {
                return XmlConvert.ToBoolean(ReadStringValue());
            }
            if ((object)type.Name == _shortID)
            {
                return XmlConvert.ToInt16(ReadStringValue());
            }
            if ((object)type.Name == _longID)
            {
                return XmlConvert.ToInt64(ReadStringValue());
            }
            if ((object)type.Name == _floatID)
            {
                return XmlConvert.ToSingle(ReadStringValue());
            }
            if ((object)type.Name == _doubleID)
            {
                return XmlConvert.ToDouble(ReadStringValue());
            }
            if ((object)type.Name == _decimalID)
            {
                return XmlConvert.ToDecimal(ReadStringValue());
            }
            if ((object)type.Name == _dateTimeID)
            {
                return ToDateTime(ReadStringValue());
            }
            if ((object)type.Name == _qnameID)
            {
                return ReadXmlQualifiedName();
            }
            if ((object)type.Name == _dateID)
            {
                return ToDate(ReadStringValue());
            }
            if ((object)type.Name == _timeID)
            {
                return ToTime(ReadStringValue());
            }
            if ((object)type.Name == _unsignedByteID)
            {
                return XmlConvert.ToByte(ReadStringValue());
            }
            if ((object)type.Name == _byteID)
            {
                return XmlConvert.ToSByte(ReadStringValue());
            }
            if ((object)type.Name == _unsignedShortID)
            {
                return XmlConvert.ToUInt16(ReadStringValue());
            }
            if ((object)type.Name == _unsignedIntID)
            {
                return XmlConvert.ToUInt32(ReadStringValue());
            }
            if ((object)type.Name == _unsignedLongID)
            {
                return XmlConvert.ToUInt64(ReadStringValue());
            }
            if ((object)type.Name == _hexBinaryID)
            {
                return ToByteArrayHex(isNull: false);
            }
            if ((object)type.Name == _base64BinaryID)
            {
                return ToByteArrayBase64(isNull: false);
            }
            if ((object)type.Name == _base64ID && ((object)type.Namespace == _soapNsID || (object)type.Namespace == _soap12NsID))
            {
                return ToByteArrayBase64(isNull: false);
            }
            return ReadXmlNodes(elementCanBeType);
        }
        if ((object)type.Namespace == _schemaNs2000ID || (object)type.Namespace == _schemaNs1999ID)
        {
            if ((object)type.Name == _stringID || (object)type.Name == _normalizedStringID)
            {
                return ReadStringValue();
            }
            if ((object)type.Name == _anyURIID || (object)type.Name == _anyURIID || (object)type.Name == _durationID || (object)type.Name == _ENTITYID || (object)type.Name == _ENTITIESID || (object)type.Name == _gDayID || (object)type.Name == _gMonthID || (object)type.Name == _gMonthDayID || (object)type.Name == _gYearID || (object)type.Name == _gYearMonthID || (object)type.Name == _IDID || (object)type.Name == _IDREFID || (object)type.Name == _IDREFSID || (object)type.Name == _integerID || (object)type.Name == _languageID || (object)type.Name == _nameID || (object)type.Name == _NCNameID || (object)type.Name == _NMTOKENID || (object)type.Name == _NMTOKENSID || (object)type.Name == _negativeIntegerID || (object)type.Name == _nonPositiveIntegerID || (object)type.Name == _nonNegativeIntegerID || (object)type.Name == _NOTATIONID || (object)type.Name == _positiveIntegerID || (object)type.Name == _tokenID)
            {
                return CollapseWhitespace(ReadStringValue());
            }
            if ((object)type.Name == _intID)
            {
                return XmlConvert.ToInt32(ReadStringValue());
            }
            if ((object)type.Name == _booleanID)
            {
                return XmlConvert.ToBoolean(ReadStringValue());
            }
            if ((object)type.Name == _shortID)
            {
                return XmlConvert.ToInt16(ReadStringValue());
            }
            if ((object)type.Name == _longID)
            {
                return XmlConvert.ToInt64(ReadStringValue());
            }
            if ((object)type.Name == _floatID)
            {
                return XmlConvert.ToSingle(ReadStringValue());
            }
            if ((object)type.Name == _doubleID)
            {
                return XmlConvert.ToDouble(ReadStringValue());
            }
            if ((object)type.Name == _oldDecimalID)
            {
                return XmlConvert.ToDecimal(ReadStringValue());
            }
            if ((object)type.Name == _oldTimeInstantID)
            {
                return ToDateTime(ReadStringValue());
            }
            if ((object)type.Name == _qnameID)
            {
                return ReadXmlQualifiedName();
            }
            if ((object)type.Name == _dateID)
            {
                return ToDate(ReadStringValue());
            }
            if ((object)type.Name == _timeID)
            {
                return ToTime(ReadStringValue());
            }
            if ((object)type.Name == _unsignedByteID)
            {
                return XmlConvert.ToByte(ReadStringValue());
            }
            if ((object)type.Name == _byteID)
            {
                return XmlConvert.ToSByte(ReadStringValue());
            }
            if ((object)type.Name == _unsignedShortID)
            {
                return XmlConvert.ToUInt16(ReadStringValue());
            }
            if ((object)type.Name == _unsignedIntID)
            {
                return XmlConvert.ToUInt32(ReadStringValue());
            }
            if ((object)type.Name == _unsignedLongID)
            {
                return XmlConvert.ToUInt64(ReadStringValue());
            }
            return ReadXmlNodes(elementCanBeType);
        }
        if ((object)type.Namespace == _schemaNonXsdTypesNsID)
        {
            if ((object)type.Name == _charID)
            {
                return ToChar(ReadStringValue());
            }
            if ((object)type.Name == _guidID)
            {
                return new Guid(CollapseWhitespace(ReadStringValue()));
            }
            if ((object)type.Name == _timeSpanID)
            {
                return XmlConvert.ToTimeSpan(ReadStringValue());
            }
            if ((object)type.Name == _dateTimeOffsetID)
            {
                return XmlConvert.ToDateTimeOffset(ReadStringValue());
            }
            return ReadXmlNodes(elementCanBeType);
        }
        return ReadXmlNodes(elementCanBeType);
    }
References System.Xml.Serialization.XmlSerializationReader._anyURIID, System.Xml.Serialization.XmlSerializationReader._base64BinaryID, System.Xml.Serialization.XmlSerializationReader._base64ID, System.Xml.Serialization.XmlSerializationReader._booleanID, System.Xml.Serialization.XmlSerializationReader._byteID, System.Xml.Serialization.XmlSerializationReader._charID, System.Xml.Serialization.XmlSerializationReader._dateID, System.Xml.Serialization.XmlSerializationReader._dateTimeID, System.Xml.Serialization.XmlSerializationReader._dateTimeOffsetID, System.Xml.Serialization.XmlSerializationReader._decimalID, System.Xml.Serialization.XmlSerializationReader._doubleID, System.Xml.Serialization.XmlSerializationReader._durationID, System.Xml.Serialization.XmlSerializationReader._ENTITIESID, System.Xml.Serialization.XmlSerializationReader._ENTITYID, System.Xml.Serialization.XmlSerializationReader._floatID, System.Xml.Serialization.XmlSerializationReader._gDayID, System.Xml.Serialization.XmlSerializationReader._gMonthDayID, System.Xml.Serialization.XmlSerializationReader._gMonthID, System.Xml.Serialization.XmlSerializationReader._guidID, System.Xml.Serialization.XmlSerializationReader._gYearID, System.Xml.Serialization.XmlSerializationReader._gYearMonthID, System.Xml.Serialization.XmlSerializationReader._hexBinaryID, System.Xml.Serialization.XmlSerializationReader._IDID, System.Xml.Serialization.XmlSerializationReader._IDREFID, System.Xml.Serialization.XmlSerializationReader._IDREFSID, System.Xml.Serialization.XmlSerializationReader._integerID, System.Xml.Serialization.XmlSerializationReader._intID, System.Xml.Serialization.XmlSerializationReader._languageID, System.Xml.Serialization.XmlSerializationReader._longID, System.Xml.Serialization.XmlSerializationReader._nameID, System.Xml.Serialization.XmlSerializationReader._NCNameID, System.Xml.Serialization.XmlSerializationReader._negativeIntegerID, System.Xml.Serialization.XmlSerializationReader._NMTOKENID, System.Xml.Serialization.XmlSerializationReader._NMTOKENSID, System.Xml.Serialization.XmlSerializationReader._nonNegativeIntegerID, System.Xml.Serialization.XmlSerializationReader._nonPositiveIntegerID, System.Xml.Serialization.XmlSerializationReader._normalizedStringID, System.Xml.Serialization.XmlSerializationReader._NOTATIONID, System.Xml.Serialization.XmlSerializationReader._oldDecimalID, System.Xml.Serialization.XmlSerializationReader._oldTimeInstantID, System.Xml.Serialization.XmlSerializationReader._positiveIntegerID, System.Xml.Serialization.XmlSerializationReader._qnameID, System.Xml.Serialization.XmlSerializationReader._schemaNonXsdTypesNsID, System.Xml.Serialization.XmlSerializationReader._schemaNs1999ID, System.Xml.Serialization.XmlSerializationReader._schemaNs2000ID, System.Xml.Serialization.XmlSerializationReader._schemaNsID, System.Xml.Serialization.XmlSerializationReader._shortID, System.Xml.Serialization.XmlSerializationReader._soap12NsID, System.Xml.Serialization.XmlSerializationReader._soapNsID, System.Xml.Serialization.XmlSerializationReader._stringID, System.Xml.Serialization.XmlSerializationReader._timeID, System.Xml.Serialization.XmlSerializationReader._timeSpanID, System.Xml.Serialization.XmlSerializationReader._tokenID, System.Xml.Serialization.XmlSerializationReader._unsignedByteID, System.Xml.Serialization.XmlSerializationReader._unsignedIntID, System.Xml.Serialization.XmlSerializationReader._unsignedLongID, System.Xml.Serialization.XmlSerializationReader._unsignedShortID, System.Xml.Serialization.XmlSerializationReader._urTypeID, System.Xml.Serialization.CollapseWhitespace, System.Xml.Dictionary, System.Xml.Guid, System.Xml.Serialization.XmlSerializationReader.InitPrimitiveIDs(), System.Xml.Serialization.XmlSerializationReader.IsPrimitiveNamespace(), System.obj, System.Xml.Serialization.XmlSerializationReader.ReadStringValue(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNodes(), System.Xml.Serialization.XmlSerializationReader.ReadXmlQualifiedName(), System.Xml.XmlConvert.ToBoolean(), System.Xml.XmlConvert.ToByte(), System.Xml.Serialization.XmlSerializationReader.ToByteArrayBase64(), System.Xml.Serialization.XmlSerializationReader.ToByteArrayHex(), System.Xml.Serialization.XmlSerializationReader.ToChar(), System.Xml.Serialization.XmlSerializationReader.ToDate(), System.Xml.Serialization.XmlSerializationReader.ToDateTime(), System.Xml.XmlConvert.ToDateTimeOffset(), System.Xml.XmlConvert.ToDecimal(), System.Xml.XmlConvert.ToDouble(), System.Xml.XmlConvert.ToInt16(), System.Xml.XmlConvert.ToInt32(), System.Xml.XmlConvert.ToInt64(), System.Xml.XmlConvert.ToSByte(), System.Xml.XmlConvert.ToSingle(), System.Xml.Serialization.XmlSerializationReader.ToTime(), System.Xml.XmlConvert.ToTimeSpan(), System.Xml.XmlConvert.ToUInt16(), System.Xml.XmlConvert.ToUInt32(), System.Xml.XmlConvert.ToUInt64(), and System.type.