Terraria: System.Xml.Serialization.XmlSerializationReader.GetTarget
GetTarget()
object System.Xml.Serialization.XmlSerializationReader.GetTarget (string id) inline protected
Definition at line 1739 of file XmlSerializationReader.cs.
    {
        object obj = ((_targets != null) ? _targets[id] : null);
        if (obj == null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidHref, id));
        }
        Referenced(obj);
        return obj;
    }
References System.Xml.Serialization.XmlSerializationReader._targets, System.SR.Format(), System.obj, System.Xml.Serialization.XmlSerializationReader.Referenced(), and System.SR.XmlInvalidHref.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.CreateWriteFixupMethod(), System.Xml.Serialization.XmlSerializationReader.FixupArrayRefs(), and System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement().