Terraria: System.Xml.Serialization.XmlSerializationReader.CreateUnknownNodeException
CreateUnknownNodeException()
Exception System.Xml.Serialization.XmlSerializationReader.CreateUnknownNodeException () inline protected
Definition at line 1535 of file XmlSerializationReader.cs.
    {
        return new InvalidOperationException(System.SR.Format(System.SR.XmlUnknownNode, CurrentTag()));
    }
References System.Xml.Serialization.XmlSerializationReader.CurrentTag(), System.SR.Format(), and System.SR.XmlUnknownNode.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.CreateUnknownNodeException(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_base64Binary(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_boolean(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_byte(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_char(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_dateTime(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_dateTimeOffset(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_decimal(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_double(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_float(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_guid(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_int(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_long(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_QName(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_short(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_string(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_TimeSpan(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedByte(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedInt(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedLong(), and System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedShort().