Terraria: System.Xml.Serialization.XmlSerializationReader.ParseArrayType
ParseArrayType()
SoapArrayInfo System.Xml.Serialization.XmlSerializationReader.ParseArrayType (string value) inline private
Definition at line 1188 of file XmlSerializationReader.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException(System.SR.Format(System.SR.XmlMissingArrayType, CurrentTag()));
        }
        if (value.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.XmlEmptyArrayType, CurrentTag()), "value");
        }
        char[] array = value.ToCharArray();
        int num = array.Length;
        SoapArrayInfo result = default(SoapArrayInfo);
        int num2 = num - 1;
        if (array[num2] != ']')
        {
            throw new ArgumentException(System.SR.XmlInvalidArraySyntax, "value");
        }
        num2--;
        while (num2 != -1 && array[num2] != '[')
        {
            if (array[num2] == ',')
            {
                throw new ArgumentException(System.SR.Format(System.SR.XmlInvalidArrayDimentions, CurrentTag()), "value");
            }
            num2--;
        }
        if (num2 == -1)
        {
            throw new ArgumentException(System.SR.XmlMismatchedArrayBrackets, "value");
        }
        int num3 = num - num2 - 2;
        if (num3 > 0)
        {
            string text = new string(array, num2 + 1, num3);
            try
            {
                result.length = int.Parse(text, CultureInfo.InvariantCulture);
            }
            catch (Exception ex)
            {
                if (ex is OutOfMemoryException)
                {
                    throw;
                }
                throw new ArgumentException(System.SR.Format(System.SR.XmlInvalidArrayLength, text), "value");
            }
        }
        else
        {
            result.length = -1;
        }
        num2--;
        result.jaggedDimensions = 0;
        while (num2 != -1 && array[num2] == ']')
        {
            num2--;
            if (num2 < 0)
            {
                throw new ArgumentException(System.SR.XmlMismatchedArrayBrackets, "value");
            }
            if (array[num2] == ',')
            {
                throw new ArgumentException(System.SR.Format(System.SR.XmlInvalidArrayDimentions, CurrentTag()), "value");
            }
            if (array[num2] != '[')
            {
                throw new ArgumentException(System.SR.XmlInvalidArraySyntax, "value");
            }
            num2--;
            result.jaggedDimensions++;
        }
        result.dimensions = 1;
        result.qname = new string(array, 0, num2 + 1);
        return result;
    }
References System.Xml.ArgumentException, System.array, System.Xml.Serialization.XmlSerializationReader.CurrentTag(), System.Xml.Dictionary, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlSerializationReader.SoapArrayInfo.jaggedDimensions, System.text, System.value, System.SR.XmlEmptyArrayType, System.SR.XmlInvalidArrayDimentions, System.SR.XmlInvalidArrayLength, System.SR.XmlInvalidArraySyntax, System.SR.XmlMismatchedArrayBrackets, and System.SR.XmlMissingArrayType.
Referenced by System.Xml.Serialization.XmlSerializationReader.GetArrayLength(), and System.Xml.Serialization.XmlSerializationReader.ReadArray().