Terraria: System.Xml.Serialization.XmlSerializationReader.ReadTypedNull
ReadTypedNull()
object? System.Xml.Serialization.XmlSerializationReader.ReadTypedNull (XmlQualifiedName type) inline protected
Definition at line 871 of file XmlSerializationReader.cs.
    {
        InitPrimitiveIDs();
        object obj = null;
        if (!IsPrimitiveNamespace(type.Namespace) || (object)type.Name == _urTypeID)
        {
            return null;
        }
        if ((object)type.Namespace == _schemaNsID || (object)type.Namespace == _soapNsID || (object)type.Namespace == _soap12NsID)
        {
            if ((object)type.Name == _stringID || (object)type.Name == _anyURIID || (object)type.Name == _durationID || (object)type.Name == _ENTITYID || (object)type.Name == _ENTITIESID || (object)type.Name == _gDayID || (object)type.Name == _gMonthID || (object)type.Name == _gMonthDayID || (object)type.Name == _gYearID || (object)type.Name == _gYearMonthID || (object)type.Name == _IDID || (object)type.Name == _IDREFID || (object)type.Name == _IDREFSID || (object)type.Name == _integerID || (object)type.Name == _languageID || (object)type.Name == _nameID || (object)type.Name == _NCNameID || (object)type.Name == _NMTOKENID || (object)type.Name == _NMTOKENSID || (object)type.Name == _negativeIntegerID || (object)type.Name == _nonPositiveIntegerID || (object)type.Name == _nonNegativeIntegerID || (object)type.Name == _normalizedStringID || (object)type.Name == _NOTATIONID || (object)type.Name == _positiveIntegerID || (object)type.Name == _tokenID)
            {
                return null;
            }
            if ((object)type.Name == _intID)
            {
                return null;
            }
            if ((object)type.Name == _booleanID)
            {
                return null;
            }
            if ((object)type.Name == _shortID)
            {
                return null;
            }
            if ((object)type.Name == _longID)
            {
                return null;
            }
            if ((object)type.Name == _floatID)
            {
                return null;
            }
            if ((object)type.Name == _doubleID)
            {
                return null;
            }
            if ((object)type.Name == _decimalID)
            {
                return null;
            }
            if ((object)type.Name == _dateTimeID)
            {
                return null;
            }
            if ((object)type.Name == _qnameID)
            {
                return null;
            }
            if ((object)type.Name == _dateID)
            {
                return null;
            }
            if ((object)type.Name == _timeID)
            {
                return null;
            }
            if ((object)type.Name == _unsignedByteID)
            {
                return null;
            }
            if ((object)type.Name == _byteID)
            {
                return null;
            }
            if ((object)type.Name == _unsignedShortID)
            {
                return null;
            }
            if ((object)type.Name == _unsignedIntID)
            {
                return null;
            }
            if ((object)type.Name == _unsignedLongID)
            {
                return null;
            }
            if ((object)type.Name == _hexBinaryID)
            {
                return null;
            }
            if ((object)type.Name == _base64BinaryID)
            {
                return null;
            }
            if ((object)type.Name == _base64ID && ((object)type.Namespace == _soapNsID || (object)type.Namespace == _soap12NsID))
            {
                return null;
            }
            return null;
        }
        if ((object)type.Namespace == _schemaNonXsdTypesNsID)
        {
            if ((object)type.Name == _charID)
            {
                return null;
            }
            if ((object)type.Name == _guidID)
            {
                return null;
            }
            if ((object)type.Name == _timeSpanID)
            {
                return null;
            }
            if ((object)type.Name == _dateTimeOffsetID)
            {
                return null;
            }
            return null;
        }
        return null;
    }
References System.Xml.Serialization.XmlSerializationReader._anyURIID, System.Xml.Serialization.XmlSerializationReader._base64BinaryID, System.Xml.Serialization.XmlSerializationReader._base64ID, System.Xml.Serialization.XmlSerializationReader._booleanID, System.Xml.Serialization.XmlSerializationReader._byteID, System.Xml.Serialization.XmlSerializationReader._charID, System.Xml.Serialization.XmlSerializationReader._dateID, System.Xml.Serialization.XmlSerializationReader._dateTimeID, System.Xml.Serialization.XmlSerializationReader._dateTimeOffsetID, System.Xml.Serialization.XmlSerializationReader._decimalID, System.Xml.Serialization.XmlSerializationReader._doubleID, System.Xml.Serialization.XmlSerializationReader._durationID, System.Xml.Serialization.XmlSerializationReader._ENTITIESID, System.Xml.Serialization.XmlSerializationReader._ENTITYID, System.Xml.Serialization.XmlSerializationReader._floatID, System.Xml.Serialization.XmlSerializationReader._gDayID, System.Xml.Serialization.XmlSerializationReader._gMonthDayID, System.Xml.Serialization.XmlSerializationReader._gMonthID, System.Xml.Serialization.XmlSerializationReader._guidID, System.Xml.Serialization.XmlSerializationReader._gYearID, System.Xml.Serialization.XmlSerializationReader._gYearMonthID, System.Xml.Serialization.XmlSerializationReader._hexBinaryID, System.Xml.Serialization.XmlSerializationReader._IDID, System.Xml.Serialization.XmlSerializationReader._IDREFID, System.Xml.Serialization.XmlSerializationReader._IDREFSID, System.Xml.Serialization.XmlSerializationReader._integerID, System.Xml.Serialization.XmlSerializationReader._intID, System.Xml.Serialization.XmlSerializationReader._languageID, System.Xml.Serialization.XmlSerializationReader._longID, System.Xml.Serialization.XmlSerializationReader._nameID, System.Xml.Serialization.XmlSerializationReader._NCNameID, System.Xml.Serialization.XmlSerializationReader._negativeIntegerID, System.Xml.Serialization.XmlSerializationReader._NMTOKENID, System.Xml.Serialization.XmlSerializationReader._NMTOKENSID, System.Xml.Serialization.XmlSerializationReader._nonNegativeIntegerID, System.Xml.Serialization.XmlSerializationReader._nonPositiveIntegerID, System.Xml.Serialization.XmlSerializationReader._normalizedStringID, System.Xml.Serialization.XmlSerializationReader._NOTATIONID, System.Xml.Serialization.XmlSerializationReader._positiveIntegerID, System.Xml.Serialization.XmlSerializationReader._qnameID, System.Xml.Serialization.XmlSerializationReader._schemaNonXsdTypesNsID, System.Xml.Serialization.XmlSerializationReader._schemaNsID, System.Xml.Serialization.XmlSerializationReader._shortID, System.Xml.Serialization.XmlSerializationReader._soap12NsID, System.Xml.Serialization.XmlSerializationReader._soapNsID, System.Xml.Serialization.XmlSerializationReader._stringID, System.Xml.Serialization.XmlSerializationReader._timeID, System.Xml.Serialization.XmlSerializationReader._timeSpanID, System.Xml.Serialization.XmlSerializationReader._tokenID, System.Xml.Serialization.XmlSerializationReader._unsignedByteID, System.Xml.Serialization.XmlSerializationReader._unsignedIntID, System.Xml.Serialization.XmlSerializationReader._unsignedLongID, System.Xml.Serialization.XmlSerializationReader._unsignedShortID, System.Xml.Serialization.XmlSerializationReader._urTypeID, System.Xml.Serialization.XmlSerializationReader.InitPrimitiveIDs(), System.Xml.Serialization.XmlSerializationReader.IsPrimitiveNamespace(), System.obj, and System.type.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().