Terraria: System.Xml.Serialization.XmlSerializationReader.FixupArrayRefs
FixupArrayRefs()
void System.Xml.Serialization.XmlSerializationReader.FixupArrayRefs (object fixup) inline protected
Definition at line 1808 of file XmlSerializationReader.cs.
    {
        Fixup fixup2 = (Fixup)fixup;
        Array array = (Array)fixup2.Source;
        for (int i = 0; i < array.Length; i++)
        {
            string text = fixup2.Ids[i];
            if (text != null)
            {
                object target = GetTarget(text);
                try
                {
                    array.SetValue(target, i);
                }
                catch (InvalidCastException)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidArrayRef, text, target.GetType().FullName, i.ToString(CultureInfo.InvariantCulture)));
                }
            }
        }
    }
References System.array, System.Xml.Serialization.Array, System.SR.Format(), System.Xml.Serialization.XmlSerializationReader.GetTarget(), System.Globalization.CultureInfo.InvariantCulture, System.text, and System.SR.XmlInvalidArrayRef.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadArray().