Terraria: System.Xml.Serialization.XmlSerializationReader.Referenced
Referenced()
void System.Xml.Serialization.XmlSerializationReader.Referenced (object? o) inline protected
Definition at line 1750 of file XmlSerializationReader.cs.
    {
        if (o != null)
        {
            if (_referencedTargets == null)
            {
                _referencedTargets = new Hashtable();
            }
            _referencedTargets[o] = o;
        }
    }
References System.Xml.Serialization.XmlSerializationReader._referencedTargets, and System.Xml.Dictionary.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateEncodedMembersElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationReader.GetTarget(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement().