Terraria: System.Xml.Serialization.XmlSerializationReader.ReadNull
ReadNull()
bool System.Xml.Serialization.XmlSerializationReader.ReadNull () inline protected
Definition at line 1015 of file XmlSerializationReader.cs.
    {
        if (!GetNullAttr())
        {
            return false;
        }
        if (_r.IsEmptyElement)
        {
            _r.Skip();
            return true;
        }
        _r.ReadStartElement();
        while (_r.NodeType != XmlNodeType.EndElement)
        {
            UnknownNode(null);
        }
        ReadEndElement();
        return true;
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader.GetNullAttr(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.NodeType, System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.XmlReader.ReadStartElement(), System.Xml.XmlReader.Skip(), and System.Xml.Serialization.XmlSerializationReader.UnknownNode().
Referenced by System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_base64Binary(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_QName(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_string(), System.Xml.Serialization.XmlSerializationReader.ReadNullableQualifiedName(), System.Xml.Serialization.XmlSerializationReader.ReadNullableString(), System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(), System.Xml.Serialization.XmlSerializationReader.ReadXmlNode(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteArray(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteNullableMethod().