Terraria: System.Xml.Serialization.XmlSerializationReader.GetPrimitiveType
GetPrimitiveType()
Type System.Xml.Serialization.XmlSerializationReader.GetPrimitiveType (XmlQualifiedName typeName, bool throwOnUnknown) inline private
Definition at line 411 of file XmlSerializationReader.cs.
    {
        InitPrimitiveIDs();
        if ((object)typeName.Namespace == _schemaNsID || (object)typeName.Namespace == _soapNsID || (object)typeName.Namespace == _soap12NsID)
        {
            if ((object)typeName.Name == _stringID || (object)typeName.Name == _anyURIID || (object)typeName.Name == _durationID || (object)typeName.Name == _ENTITYID || (object)typeName.Name == _ENTITIESID || (object)typeName.Name == _gDayID || (object)typeName.Name == _gMonthID || (object)typeName.Name == _gMonthDayID || (object)typeName.Name == _gYearID || (object)typeName.Name == _gYearMonthID || (object)typeName.Name == _IDID || (object)typeName.Name == _IDREFID || (object)typeName.Name == _IDREFSID || (object)typeName.Name == _integerID || (object)typeName.Name == _languageID || (object)typeName.Name == _nameID || (object)typeName.Name == _NCNameID || (object)typeName.Name == _NMTOKENID || (object)typeName.Name == _NMTOKENSID || (object)typeName.Name == _negativeIntegerID || (object)typeName.Name == _nonPositiveIntegerID || (object)typeName.Name == _nonNegativeIntegerID || (object)typeName.Name == _normalizedStringID || (object)typeName.Name == _NOTATIONID || (object)typeName.Name == _positiveIntegerID || (object)typeName.Name == _tokenID)
            {
                return typeof(string);
            }
            if ((object)typeName.Name == _intID)
            {
                return typeof(int);
            }
            if ((object)typeName.Name == _booleanID)
            {
                return typeof(bool);
            }
            if ((object)typeName.Name == _shortID)
            {
                return typeof(short);
            }
            if ((object)typeName.Name == _longID)
            {
                return typeof(long);
            }
            if ((object)typeName.Name == _floatID)
            {
                return typeof(float);
            }
            if ((object)typeName.Name == _doubleID)
            {
                return typeof(double);
            }
            if ((object)typeName.Name == _decimalID)
            {
                return typeof(decimal);
            }
            if ((object)typeName.Name == _dateTimeID)
            {
                return typeof(DateTime);
            }
            if ((object)typeName.Name == _qnameID)
            {
                return typeof(XmlQualifiedName);
            }
            if ((object)typeName.Name == _dateID)
            {
                return typeof(DateTime);
            }
            if ((object)typeName.Name == _timeID)
            {
                return typeof(DateTime);
            }
            if ((object)typeName.Name == _hexBinaryID)
            {
                return typeof(byte[]);
            }
            if ((object)typeName.Name == _base64BinaryID)
            {
                return typeof(byte[]);
            }
            if ((object)typeName.Name == _unsignedByteID)
            {
                return typeof(byte);
            }
            if ((object)typeName.Name == _byteID)
            {
                return typeof(sbyte);
            }
            if ((object)typeName.Name == _unsignedShortID)
            {
                return typeof(ushort);
            }
            if ((object)typeName.Name == _unsignedIntID)
            {
                return typeof(uint);
            }
            if ((object)typeName.Name == _unsignedLongID)
            {
                return typeof(ulong);
            }
            throw CreateUnknownTypeException(typeName);
        }
        if ((object)typeName.Namespace == _schemaNs2000ID || (object)typeName.Namespace == _schemaNs1999ID)
        {
            if ((object)typeName.Name == _stringID || (object)typeName.Name == _anyURIID || (object)typeName.Name == _durationID || (object)typeName.Name == _ENTITYID || (object)typeName.Name == _ENTITIESID || (object)typeName.Name == _gDayID || (object)typeName.Name == _gMonthID || (object)typeName.Name == _gMonthDayID || (object)typeName.Name == _gYearID || (object)typeName.Name == _gYearMonthID || (object)typeName.Name == _IDID || (object)typeName.Name == _IDREFID || (object)typeName.Name == _IDREFSID || (object)typeName.Name == _integerID || (object)typeName.Name == _languageID || (object)typeName.Name == _nameID || (object)typeName.Name == _NCNameID || (object)typeName.Name == _NMTOKENID || (object)typeName.Name == _NMTOKENSID || (object)typeName.Name == _negativeIntegerID || (object)typeName.Name == _nonPositiveIntegerID || (object)typeName.Name == _nonNegativeIntegerID || (object)typeName.Name == _normalizedStringID || (object)typeName.Name == _NOTATIONID || (object)typeName.Name == _positiveIntegerID || (object)typeName.Name == _tokenID)
            {
                return typeof(string);
            }
            if ((object)typeName.Name == _intID)
            {
                return typeof(int);
            }
            if ((object)typeName.Name == _booleanID)
            {
                return typeof(bool);
            }
            if ((object)typeName.Name == _shortID)
            {
                return typeof(short);
            }
            if ((object)typeName.Name == _longID)
            {
                return typeof(long);
            }
            if ((object)typeName.Name == _floatID)
            {
                return typeof(float);
            }
            if ((object)typeName.Name == _doubleID)
            {
                return typeof(double);
            }
            if ((object)typeName.Name == _oldDecimalID)
            {
                return typeof(decimal);
            }
            if ((object)typeName.Name == _oldTimeInstantID)
            {
                return typeof(DateTime);
            }
            if ((object)typeName.Name == _qnameID)
            {
                return typeof(XmlQualifiedName);
            }
            if ((object)typeName.Name == _dateID)
            {
                return typeof(DateTime);
            }
            if ((object)typeName.Name == _timeID)
            {
                return typeof(DateTime);
            }
            if ((object)typeName.Name == _hexBinaryID)
            {
                return typeof(byte[]);
            }
            if ((object)typeName.Name == _byteID)
            {
                return typeof(sbyte);
            }
            if ((object)typeName.Name == _unsignedShortID)
            {
                return typeof(ushort);
            }
            if ((object)typeName.Name == _unsignedIntID)
            {
                return typeof(uint);
            }
            if ((object)typeName.Name == _unsignedLongID)
            {
                return typeof(ulong);
            }
            throw CreateUnknownTypeException(typeName);
        }
        if ((object)typeName.Namespace == _schemaNonXsdTypesNsID)
        {
            if ((object)typeName.Name == _charID)
            {
                return typeof(char);
            }
            if ((object)typeName.Name == _guidID)
            {
                return typeof(Guid);
            }
            throw CreateUnknownTypeException(typeName);
        }
        if (throwOnUnknown)
        {
            throw CreateUnknownTypeException(typeName);
        }
        return null;
    }
References System.Xml.Serialization.XmlSerializationReader._anyURIID, System.Xml.Serialization.XmlSerializationReader._base64BinaryID, System.Xml.Serialization.XmlSerializationReader._booleanID, System.Xml.Serialization.XmlSerializationReader._byteID, System.Xml.Serialization.XmlSerializationReader._charID, System.Xml.Serialization.XmlSerializationReader._dateID, System.Xml.Serialization.XmlSerializationReader._dateTimeID, System.Xml.Serialization.XmlSerializationReader._decimalID, System.Xml.Serialization.XmlSerializationReader._doubleID, System.Xml.Serialization.XmlSerializationReader._durationID, System.Xml.Serialization.XmlSerializationReader._ENTITIESID, System.Xml.Serialization.XmlSerializationReader._ENTITYID, System.Xml.Serialization.XmlSerializationReader._floatID, System.Xml.Serialization.XmlSerializationReader._gDayID, System.Xml.Serialization.XmlSerializationReader._gMonthDayID, System.Xml.Serialization.XmlSerializationReader._gMonthID, System.Xml.Serialization.XmlSerializationReader._guidID, System.Xml.Serialization.XmlSerializationReader._gYearID, System.Xml.Serialization.XmlSerializationReader._gYearMonthID, System.Xml.Serialization.XmlSerializationReader._hexBinaryID, System.Xml.Serialization.XmlSerializationReader._IDID, System.Xml.Serialization.XmlSerializationReader._IDREFID, System.Xml.Serialization.XmlSerializationReader._IDREFSID, System.Xml.Serialization.XmlSerializationReader._integerID, System.Xml.Serialization.XmlSerializationReader._intID, System.Xml.Serialization.XmlSerializationReader._languageID, System.Xml.Serialization.XmlSerializationReader._longID, System.Xml.Serialization.XmlSerializationReader._nameID, System.Xml.Serialization.XmlSerializationReader._NCNameID, System.Xml.Serialization.XmlSerializationReader._negativeIntegerID, System.Xml.Serialization.XmlSerializationReader._NMTOKENID, System.Xml.Serialization.XmlSerializationReader._NMTOKENSID, System.Xml.Serialization.XmlSerializationReader._nonNegativeIntegerID, System.Xml.Serialization.XmlSerializationReader._nonPositiveIntegerID, System.Xml.Serialization.XmlSerializationReader._normalizedStringID, System.Xml.Serialization.XmlSerializationReader._NOTATIONID, System.Xml.Serialization.XmlSerializationReader._oldDecimalID, System.Xml.Serialization.XmlSerializationReader._oldTimeInstantID, System.Xml.Serialization.XmlSerializationReader._positiveIntegerID, System.Xml.Serialization.XmlSerializationReader._qnameID, System.Xml.Serialization.XmlSerializationReader._schemaNonXsdTypesNsID, System.Xml.Serialization.XmlSerializationReader._schemaNs1999ID, System.Xml.Serialization.XmlSerializationReader._schemaNs2000ID, System.Xml.Serialization.XmlSerializationReader._schemaNsID, System.Xml.Serialization.XmlSerializationReader._shortID, System.Xml.Serialization.XmlSerializationReader._soap12NsID, System.Xml.Serialization.XmlSerializationReader._soapNsID, System.Xml.Serialization.XmlSerializationReader._stringID, System.Xml.Serialization.XmlSerializationReader._timeID, System.Xml.Serialization.XmlSerializationReader._tokenID, System.Xml.Serialization.XmlSerializationReader._unsignedByteID, System.Xml.Serialization.XmlSerializationReader._unsignedIntID, System.Xml.Serialization.XmlSerializationReader._unsignedLongID, System.Xml.Serialization.XmlSerializationReader._unsignedShortID, System.Xml.Serialization.XmlSerializationReader.CreateUnknownTypeException(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.InitPrimitiveIDs(), System.Xml.XmlQualifiedName.Name, and System.Xml.XmlQualifiedName.Namespace.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadArray().