Terraria: System.Xml.Serialization.XmlSerializationReader.ReadSerializable
ReadSerializable() [2/2]
IXmlSerializable System.Xml.Serialization.XmlSerializationReader.ReadSerializable (IXmlSerializable serializable, bool wrappedAny) inline protected
Definition at line 1633 of file XmlSerializationReader.cs.
    {
        string text = null;
        string text2 = null;
        if (wrappedAny)
        {
            text = _r.LocalName;
            text2 = _r.NamespaceURI;
            _r.Read();
            _r.MoveToContent();
        }
        serializable.ReadXml(_r);
        if (wrappedAny)
        {
            while (_r.NodeType == XmlNodeType.Whitespace)
            {
                _r.Skip();
            }
            if (_r.NodeType == XmlNodeType.None)
            {
                _r.Skip();
            }
            if (_r.NodeType == XmlNodeType.EndElement && _r.LocalName == text && _r.NamespaceURI == text2)
            {
                Reader.Read();
            }
        }
        return serializable;
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Dictionary, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlReader.Skip(), and System.text.