Terraria: System.Xml.Serialization.XmlSerializationReader.ToXmlQualifiedName
ToXmlQualifiedName() [1/2]
XmlQualifiedName System.Xml.Serialization.XmlSerializationReader.ToXmlQualifiedName (string value, bool decodeName) inline package
Definition at line 1365 of file XmlSerializationReader.cs.
    {
        int num = value?.LastIndexOf(':') ?? (-1);
        string text = ((num < 0) ? null : value.Substring(0, num));
        string text2 = value.Substring(num + 1);
        if (decodeName)
        {
            text = XmlConvert.DecodeName(text);
            text2 = XmlConvert.DecodeName(text2);
        }
        if (text == null || text.Length == 0)
        {
            return new XmlQualifiedName(_r.NameTable.Add(value), _r.LookupNamespace(string.Empty));
        }
        string text3 = _r.LookupNamespace(text);
        if (text3 == null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlUndefinedAlias, text));
        }
        return new XmlQualifiedName(_r.NameTable.Add(text2), text3);
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Xml.XmlNameTable.Add(), System.Xml.XmlConvert.DecodeName(), System.SR.Format(), System.Xml.XmlReader.LookupNamespace(), System.Xml.XmlReader.NameTable, System.text, System.value, and System.SR.XmlUndefinedAlias.