Terraria: System.Xml.Serialization.XmlSerializationReader.Init
Init() [2/2]
void System.Xml.Serialization.XmlSerializationReader.Init (XmlReader r, XmlDeserializationEvents events, string encodingStyle, TempAssembly tempAssembly) inline package
Definition at line 298 of file XmlSerializationReader.cs.
    {
        _events = events;
        _r = r;
        _d = null;
        _soap12 = encodingStyle == "http://www.w3.org/2003/05/soap-encoding";
        Init(tempAssembly);
        _schemaNsID = r.NameTable.Add("http://www.w3.org/2001/XMLSchema");
        _schemaNs2000ID = r.NameTable.Add("http://www.w3.org/2000/10/XMLSchema");
        _schemaNs1999ID = r.NameTable.Add("http://www.w3.org/1999/XMLSchema");
        _schemaNonXsdTypesNsID = r.NameTable.Add("http://microsoft.com/wsdl/types/");
        _instanceNsID = r.NameTable.Add("http://www.w3.org/2001/XMLSchema-instance");
        _instanceNs2000ID = r.NameTable.Add("http://www.w3.org/2000/10/XMLSchema-instance");
        _instanceNs1999ID = r.NameTable.Add("http://www.w3.org/1999/XMLSchema-instance");
        _soapNsID = r.NameTable.Add("http://schemas.xmlsoap.org/soap/encoding/");
        _soap12NsID = r.NameTable.Add("http://www.w3.org/2003/05/soap-encoding");
        _schemaID = r.NameTable.Add("schema");
        _wsdlNsID = r.NameTable.Add("http://schemas.xmlsoap.org/wsdl/");
        _wsdlArrayTypeID = r.NameTable.Add("arrayType");
        _nullID = r.NameTable.Add("null");
        _nilID = r.NameTable.Add("nil");
        _typeID = r.NameTable.Add("type");
        _arrayTypeID = r.NameTable.Add("arrayType");
        _itemTypeID = r.NameTable.Add("itemType");
        _arraySizeID = r.NameTable.Add("arraySize");
        _arrayID = r.NameTable.Add("Array");
        _urTypeID = r.NameTable.Add("anyType");
        InitIDs();
    }
References System.Xml.Serialization.XmlSerializationReader._arrayID, System.Xml.Serialization.XmlSerializationReader._arraySizeID, System.Xml.Serialization.XmlSerializationReader._arrayTypeID, System.Xml.Serialization.XmlSerializationReader._d, System.Xml.Serialization.XmlSerializationReader._events, System.Xml.Serialization.XmlSerializationReader._instanceNs1999ID, System.Xml.Serialization.XmlSerializationReader._instanceNs2000ID, System.Xml.Serialization.XmlSerializationReader._instanceNsID, System.Xml.Serialization.XmlSerializationReader._itemTypeID, System.Xml.Serialization.XmlSerializationReader._nilID, System.Xml.Serialization.XmlSerializationReader._nullID, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._schemaID, System.Xml.Serialization.XmlSerializationReader._schemaNonXsdTypesNsID, System.Xml.Serialization.XmlSerializationReader._schemaNs1999ID, System.Xml.Serialization.XmlSerializationReader._schemaNs2000ID, System.Xml.Serialization.XmlSerializationReader._schemaNsID, System.Xml.Serialization.XmlSerializationReader._soap12, System.Xml.Serialization.XmlSerializationReader._soap12NsID, System.Xml.Serialization.XmlSerializationReader._soapNsID, System.Xml.Serialization.XmlSerializationReader._typeID, System.Xml.Serialization.XmlSerializationReader._urTypeID, System.Xml.Serialization.XmlSerializationReader._wsdlArrayTypeID, System.Xml.Serialization.XmlSerializationReader._wsdlNsID, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.Init(), and System.Xml.Serialization.XmlSerializationReader.InitIDs().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.ReflectionXmlSerializationReader(), and System.Xml.Serialization.XmlSerializationReader.Init().