Terraria: System.Xml.Serialization.XmlSerializationReader.EnsureCallbackTables
EnsureCallbackTables()
void System.Xml.Serialization.XmlSerializationReader.EnsureCallbackTables () inline package
Definition at line 2094 of file XmlSerializationReader.cs.
    {
        if (_callbacks == null)
        {
            _callbacks = new Hashtable();
            _types = new Hashtable();
            XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(_urTypeID, _r.NameTable.Add("http://www.w3.org/2001/XMLSchema"));
            _types.Add(xmlQualifiedName, typeof(object));
            _typesReverse = new Hashtable();
            _typesReverse.Add(typeof(object), xmlQualifiedName);
            InitCallbacks();
        }
    }
References System.Xml.Serialization.XmlSerializationReader._callbacks, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._types, System.Xml.Serialization.XmlSerializationReader._typesReverse, System.Xml.Serialization.XmlSerializationReader._urTypeID, System.Xml.XmlNameTable.Add(), System.Collections.Hashtable.Add(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.InitCallbacks(), and System.Xml.XmlReader.NameTable.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement().