Terraria: System.Xml.Serialization.XmlSerializationReader.HandleUnreferencedObjects
HandleUnreferencedObjects()
void System.Xml.Serialization.XmlSerializationReader.HandleUnreferencedObjects () inline private
Definition at line 1762 of file XmlSerializationReader.cs.
    {
        if (_targets != null)
        {
            foreach (DictionaryEntry target in _targets)
            {
                if (_referencedTargets == null || !_referencedTargets.Contains(target.Value))
                {
                    UnreferencedObject((string)target.Key, target.Value);
                }
            }
        }
        if (_targetsWithoutIds == null)
        {
            return;
        }
        foreach (object targetsWithoutId in _targetsWithoutIds)
        {
            if (_referencedTargets == null || !_referencedTargets.Contains(targetsWithoutId))
            {
                UnreferencedObject(null, targetsWithoutId);
            }
        }
    }
References System.Xml.Serialization.XmlSerializationReader._referencedTargets, System.Xml.Serialization.XmlSerializationReader._targets, System.Xml.Serialization.XmlSerializationReader._targetsWithoutIds, System.Collections.Hashtable.Contains(), System.Collections.DictionaryEntry.Key, System.Xml.Serialization.XmlSerializationReader.UnreferencedObject(), and System.Collections.DictionaryEntry.Value.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadReferencedElements().