Terraria: System.Xml.Serialization.XmlSerializationReader.ReadReference
ReadReference()
bool System.Xml.Serialization.XmlSerializationReader.ReadReference ([NotNullWhen(true)] out string? fixupReference) inline protected
Definition at line 1663 of file XmlSerializationReader.cs.
    {
        string text = (_soap12 ? _r.GetAttribute("ref", "http://www.w3.org/2003/05/soap-encoding") : _r.GetAttribute("href"));
        if (text == null)
        {
            fixupReference = null;
            return false;
        }
        if (!_soap12)
        {
            if (!text.StartsWith('#'))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlMissingHref, text));
            }
            fixupReference = text.Substring(1);
        }
        else
        {
            fixupReference = text;
        }
        if (_r.IsEmptyElement)
        {
            _r.Skip();
        }
        else
        {
            _r.ReadStartElement();
            ReadEndElement();
        }
        return true;
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._soap12, System.SR.Format(), System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.IsEmptyElement, System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.XmlReader.ReadStartElement(), System.Xml.XmlReader.Skip(), System.text, and System.SR.XmlMissingHref.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement().