Terraria: System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.IOCallback
IOCallback()
static unsafe void System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.IOCallback (uint errorCode, uint numBytes, NativeOverlapped * pOVERLAP) inline static package
Definition at line 49 of file FileStreamHelpers.cs.
        {
            AsyncCopyToAwaitable asyncCopyToAwaitable = (AsyncCopyToAwaitable)ThreadPoolBoundHandle.GetNativeOverlappedState(pOVERLAP);
            asyncCopyToAwaitable._errorCode = errorCode;
            asyncCopyToAwaitable._numBytes = numBytes;
            (asyncCopyToAwaitable._continuation ?? Interlocked.CompareExchange(ref asyncCopyToAwaitable._continuation, s_sentinel, null))?.Invoke();
        }
References System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.AsyncCopyToAwaitable(), System.Threading.Interlocked.CompareExchange(), System.Runtime.Serialization.Dictionary, System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(), and System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.s_sentinel.