Terraria: System.Xml.Serialization.XmlSerializationReader.ReadXmlNode
ReadXmlNode()
XmlNode? System.Xml.Serialization.XmlSerializationReader.ReadXmlNode (bool wrapped) inline protected
Definition at line 1106 of file XmlSerializationReader.cs.
    {
        XmlNode result = null;
        if (wrapped)
        {
            if (ReadNull())
            {
                return null;
            }
            _r.ReadStartElement();
            _r.MoveToContent();
            if (_r.NodeType != XmlNodeType.EndElement)
            {
                result = Document.ReadNode(_r);
            }
            while (_r.NodeType != XmlNodeType.EndElement)
            {
                UnknownNode(null);
            }
            _r.ReadEndElement();
        }
        else
        {
            result = Document.ReadNode(_r);
        }
        return result;
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader.Document, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlDocument.ReadNode(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.XmlReader.ReadStartElement(), and System.Xml.Serialization.XmlSerializationReader.UnknownNode().
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadXmlDocument(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement().