Terraria: System.Xml.Serialization.XmlSerializationReader.GetArrayLength
GetArrayLength()
int System.Xml.Serialization.XmlSerializationReader.GetArrayLength (string name, string ns) inline protected
Definition at line 1164 of file XmlSerializationReader.cs.
    {
        if (GetNullAttr())
        {
            return 0;
        }
        string attribute = _r.GetAttribute(_arrayTypeID, _soapNsID);
        SoapArrayInfo soapArrayInfo = ParseArrayType(attribute);
        if (soapArrayInfo.dimensions != 1)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidArrayDimentions, CurrentTag()));
        }
        XmlQualifiedName xmlQualifiedName = ToXmlQualifiedName(soapArrayInfo.qname, decodeName: false);
        if (xmlQualifiedName.Name != name)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidArrayTypeName, xmlQualifiedName.Name, name, CurrentTag()));
        }
        if (xmlQualifiedName.Namespace != ns)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidArrayTypeNamespace, xmlQualifiedName.Namespace, ns, CurrentTag()));
        }
        return soapArrayInfo.length;
    }
References System.Xml.Serialization.XmlSerializationReader._arrayTypeID, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._soapNsID, System.Xml.Serialization.XmlSerializationReader.CurrentTag(), System.SR.Format(), System.Xml.XmlReader.GetAttribute(), System.Xml.Serialization.XmlSerializationReader.GetNullAttr(), System.Xml.Serialization.XmlSerializationReader.ParseArrayType(), System.Xml.Serialization.XmlSerializationReader.ToXmlQualifiedName(), System.SR.XmlInvalidArrayDimentions, System.SR.XmlInvalidArrayTypeName, and System.SR.XmlInvalidArrayTypeNamespace.