Terraria: System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement
ReadReferencingElement() [2/3]
object? System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement (string? name, string? ns, bool elementCanBeType, out string? fixupReference) inline protected
Definition at line 2064 of file XmlSerializationReader.cs.
    {
        object obj = null;
        EnsureCallbackTables();
        _r.MoveToContent();
        if (ReadReference(out fixupReference))
        {
            return null;
        }
        if (ReadNull())
        {
            return null;
        }
        string id = (_soap12 ? _r.GetAttribute("id", "http://www.w3.org/2003/05/soap-encoding") : _r.GetAttribute("id", null));
        if ((obj = ReadArray(name, ns)) == null)
        {
            XmlQualifiedName xmlQualifiedName = GetXsiType();
            if (xmlQualifiedName == null)
            {
                xmlQualifiedName = ((name != null) ? new XmlQualifiedName(_r.NameTable.Add(name), _r.NameTable.Add(ns)) : new XmlQualifiedName(_r.NameTable.Add(_r.LocalName), _r.NameTable.Add(_r.NamespaceURI)));
            }
            XmlSerializationReadCallback xmlSerializationReadCallback = (XmlSerializationReadCallback)_callbacks[xmlQualifiedName];
            obj = ((xmlSerializationReadCallback == null) ? ReadTypedPrimitive(xmlQualifiedName, elementCanBeType) : xmlSerializationReadCallback());
        }
        AddTarget(id, obj);
        return obj;
    }
References System.Xml.Serialization.XmlSerializationReader._callbacks, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._soap12, System.Xml.XmlNameTable.Add(), System.Xml.Serialization.XmlSerializationReader.AddTarget(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.EnsureCallbackTables(), System.Xml.XmlReader.GetAttribute(), System.Xml.Serialization.XmlSerializationReader.GetXsiType(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NameTable, System.obj, System.Xml.Serialization.XmlSerializationReader.ReadArray(), System.Xml.Serialization.XmlSerializationReader.ReadNull(), System.Xml.Serialization.XmlSerializationReader.ReadReference(), System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive(), and System.Xml.Serialization.XmlSerializationReadCallback().