Terraria: System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.UnsafeOnCompleted
UnsafeOnCompleted()
void System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.UnsafeOnCompleted (Action continuation) inline
Implements System.Runtime.CompilerServices.ICriticalNotifyCompletion.
Definition at line 76 of file FileStreamHelpers.cs.
        {
            if ((object)_continuation == s_sentinel || Interlocked.CompareExchange(ref _continuation, continuation, null) != null)
            {
                Task.Run(continuation);
            }
        }
References System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable._continuation, System.Threading.Interlocked.CompareExchange(), System.Runtime.Serialization.Dictionary, System.Threading.Tasks.Task< TResult >.Run(), and System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.s_sentinel.
Referenced by System.IO.Strategies.FileStreamHelpers.AsyncCopyToAwaitable.OnCompleted().