Terraria: System.Xml.Serialization.XmlSerializationReader.GetNullAttr
GetNullAttr()
bool System.Xml.Serialization.XmlSerializationReader.GetNullAttr () inline protected
Definition at line 1035 of file XmlSerializationReader.cs.
    {
        string attribute = _r.GetAttribute(_nilID, _instanceNsID);
        if (attribute == null)
        {
            attribute = _r.GetAttribute(_nullID, _instanceNsID);
        }
        if (attribute == null)
        {
            attribute = _r.GetAttribute(_nullID, _instanceNs2000ID);
            if (attribute == null)
            {
                attribute = _r.GetAttribute(_nullID, _instanceNs1999ID);
            }
        }
        if (attribute == null || !XmlConvert.ToBoolean(attribute))
        {
            return false;
        }
        return true;
    }
References System.Xml.Serialization.XmlSerializationReader._instanceNs1999ID, System.Xml.Serialization.XmlSerializationReader._instanceNs2000ID, System.Xml.Serialization.XmlSerializationReader._instanceNsID, System.Xml.Serialization.XmlSerializationReader._nilID, System.Xml.Serialization.XmlSerializationReader._nullID, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.XmlReader.GetAttribute(), and System.Xml.XmlConvert.ToBoolean().
Referenced by System.Xml.Serialization.XmlSerializationReader.GetArrayLength(), and System.Xml.Serialization.XmlSerializationReader.ReadNull().