Terraria: System.Xml.Serialization.XmlSerializationReader.GetXsiType
GetXsiType()
XmlQualifiedName? System.Xml.Serialization.XmlSerializationReader.GetXsiType () inline protected
Definition at line 393 of file XmlSerializationReader.cs.
    {
        string attribute = _r.GetAttribute(_typeID, _instanceNsID);
        if (attribute == null)
        {
            attribute = _r.GetAttribute(_typeID, _instanceNs2000ID);
            if (attribute == null)
            {
                attribute = _r.GetAttribute(_typeID, _instanceNs1999ID);
                if (attribute == null)
                {
                    return null;
                }
            }
        }
        return ToXmlQualifiedName(attribute, decodeName: false);
    }
References System.Xml.Serialization.XmlSerializationReader._instanceNs1999ID, System.Xml.Serialization.XmlSerializationReader._instanceNs2000ID, System.Xml.Serialization.XmlSerializationReader._instanceNsID, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._typeID, System.Xml.XmlReader.GetAttribute(), and System.Xml.Serialization.XmlSerializationReader.ToXmlQualifiedName().
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(), System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod().