Terraria: System.Xml.Serialization.XmlSerializationReader.CurrentTag
CurrentTag()
string System.Xml.Serialization.XmlSerializationReader.CurrentTag () inline private
Definition at line 1496 of file XmlSerializationReader.cs.
    {
        return _r.NodeType switch
        {
            XmlNodeType.Element => "<" + _r.LocalName + " xmlns='" + _r.NamespaceURI + "'>",
            XmlNodeType.EndElement => ">",
            XmlNodeType.Text => _r.Value,
            XmlNodeType.CDATA => "CDATA",
            XmlNodeType.Comment => "<--",
            XmlNodeType.ProcessingInstruction => "<?",
            _ => "(unknown)",
        };
    }
References System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Dictionary, and System.Xml.XmlReader.Value.
Referenced by System.Xml.Serialization.XmlSerializationReader.CreateAbstractTypeException(), System.Xml.Serialization.XmlSerializationReader.CreateUnknownNodeException(), System.Xml.Serialization.XmlSerializationReader.CreateUnknownTypeException(), System.Xml.Serialization.XmlSerializationReader.GetArrayLength(), System.Xml.Serialization.XmlSerializationReader.ParseArrayType(), and System.Xml.Serialization.XmlSerializationReader.ReadArray().