Terraria: System.Xml.Serialization.XmlSerializationReader.ReadArray
ReadArray()
object System.Xml.Serialization.XmlSerializationReader.ReadArray (string typeName, string typeNs) inline private
Definition at line 1831 of file XmlSerializationReader.cs.
    {
        Type type = null;
        SoapArrayInfo soapArrayInfo;
        if (_soap12)
        {
            string attribute = _r.GetAttribute(_itemTypeID, _soap12NsID);
            string attribute2 = _r.GetAttribute(_arraySizeID, _soap12NsID);
            Type type2 = (Type)_types[new XmlQualifiedName(typeName, typeNs)];
            if (attribute == null && attribute2 == null && (type2 == null || !type2.IsArray))
            {
                return null;
            }
            soapArrayInfo = ParseSoap12ArrayType(attribute, attribute2);
            if (type2 != null)
            {
                type = TypeScope.GetArrayElementType(type2, null);
            }
        }
        else
        {
            string attribute3 = _r.GetAttribute(_arrayTypeID, _soapNsID);
            if (attribute3 == null)
            {
                return null;
            }
            soapArrayInfo = ParseArrayType(attribute3);
        }
        if (soapArrayInfo.dimensions != 1)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidArrayDimentions, CurrentTag()));
        }
        Type type3 = null;
        XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(_urTypeID, _schemaNsID);
        XmlQualifiedName xmlQualifiedName2;
        if (soapArrayInfo.qname.Length > 0)
        {
            xmlQualifiedName2 = ToXmlQualifiedName(soapArrayInfo.qname, decodeName: false);
            type3 = (Type)_types[xmlQualifiedName2];
        }
        else
        {
            xmlQualifiedName2 = xmlQualifiedName;
        }
        if (_soap12 && type3 == typeof(object))
        {
            type3 = null;
        }
        bool flag;
        if (type3 == null)
        {
            if (!_soap12)
            {
                type3 = GetPrimitiveType(xmlQualifiedName2, throwOnUnknown: true);
                flag = true;
            }
            else
            {
                if (xmlQualifiedName2 != xmlQualifiedName)
                {
                    type3 = GetPrimitiveType(xmlQualifiedName2, throwOnUnknown: false);
                }
                if (type3 != null)
                {
                    flag = true;
                }
                else if (type == null)
                {
                    type3 = typeof(object);
                    flag = false;
                }
                else
                {
                    type3 = type;
                    XmlQualifiedName xmlQualifiedName3 = (XmlQualifiedName)_typesReverse[type3];
                    if (xmlQualifiedName3 == null)
                    {
                        xmlQualifiedName3 = XmlSerializationWriter.GetPrimitiveTypeNameInternal(type3);
                        flag = true;
                    }
                    else
                    {
                        flag = type3.IsPrimitive;
                    }
                    if (xmlQualifiedName3 != null)
                    {
                        xmlQualifiedName2 = xmlQualifiedName3;
                    }
                }
            }
        }
        else
        {
            flag = type3.IsPrimitive;
        }
        if (!_soap12 && soapArrayInfo.jaggedDimensions > 0)
        {
            for (int i = 0; i < soapArrayInfo.jaggedDimensions; i++)
            {
                type3 = type3.MakeArrayType();
            }
        }
        if (_r.IsEmptyElement)
        {
            _r.Skip();
            return Array.CreateInstance(type3, 0);
        }
        _r.ReadStartElement();
        _r.MoveToContent();
        int num = 0;
        Array array = null;
        if (type3.IsValueType)
        {
            if (!flag && !type3.IsEnum)
            {
                throw new NotSupportedException(System.SR.Format(System.SR.XmlRpcArrayOfValueTypes, type3.FullName));
            }
            while (_r.NodeType != XmlNodeType.EndElement)
            {
                array = EnsureArrayIndex(array, num, type3);
                array.SetValue(ReadReferencedElement(xmlQualifiedName2.Name, xmlQualifiedName2.Namespace), num);
                num++;
                _r.MoveToContent();
            }
            array = ShrinkArray(array, num, type3, isNullable: false);
        }
        else
        {
            string[] array2 = null;
            int num2 = 0;
            while (_r.NodeType != XmlNodeType.EndElement)
            {
                array = EnsureArrayIndex(array, num, type3);
                array2 = (string[])EnsureArrayIndex(array2, num2, typeof(string));
                string name;
                string ns;
                if (_r.NamespaceURI.Length != 0)
                {
                    name = _r.LocalName;
                    ns = (((object)_r.NamespaceURI != _soapNsID) ? _r.NamespaceURI : "http://www.w3.org/2001/XMLSchema");
                }
                else
                {
                    name = xmlQualifiedName2.Name;
                    ns = xmlQualifiedName2.Namespace;
                }
                array.SetValue(ReadReferencingElement(name, ns, out array2[num2]), num);
                num++;
                num2++;
                _r.MoveToContent();
            }
            if (_soap12 && type3 == typeof(object))
            {
                Type type4 = null;
                for (int j = 0; j < num; j++)
                {
                    object value = array.GetValue(j);
                    if (value != null)
                    {
                        Type type5 = value.GetType();
                        if (type5.IsValueType)
{
                            type4 = null;
                            break;
                        }
                        if (type4 == null || type5.IsAssignableFrom(type4))
{
                            type4 = type5;
                        }
                        else if (!type4.IsAssignableFrom(type5))
{
                            type4 = null;
                            break;
                        }
                    }
                }
                if (type4 != null)
                {
                    type3 = type4;
                }
            }
            array2 = (string[])ShrinkArray(array2, num2, typeof(string), isNullable: false);
            array = ShrinkArray(array, num, type3, isNullable: false);
            Fixup fixup = new Fixup(array, FixupArrayRefs, array2);
            AddFixup(fixup);
        }
        ReadEndElement();
        return array;
    }
References System.Xml.Serialization.XmlSerializationReader._arraySizeID, System.Xml.Serialization.XmlSerializationReader._arrayTypeID, System.Xml.Serialization.XmlSerializationReader._itemTypeID, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._schemaNsID, System.Xml.Serialization.XmlSerializationReader._soap12, System.Xml.Serialization.XmlSerializationReader._soap12NsID, System.Xml.Serialization.XmlSerializationReader._soapNsID, System.Xml.Serialization.XmlSerializationReader._types, System.Xml.Serialization.XmlSerializationReader._typesReverse, System.Xml.Serialization.XmlSerializationReader._urTypeID, System.Xml.Serialization.XmlSerializationReader.AddFixup(), System.array, System.Array.CreateInstance(), System.Xml.Serialization.XmlSerializationReader.CurrentTag(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.EnsureArrayIndex(), System.Xml.Serialization.XmlSerializationReader.FixupArrayRefs(), System.SR.Format(), System.Xml.Serialization.TypeScope.GetArrayElementType(), System.Xml.XmlReader.GetAttribute(), System.Xml.Serialization.XmlSerializationReader.GetPrimitiveType(), System.Xml.Serialization.XmlSerializationWriter.GetPrimitiveTypeNameInternal(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.Serialization.XmlSerializationReader.ParseArrayType(), System.Xml.Serialization.XmlSerializationReader.ParseSoap12ArrayType(), System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.Serialization.XmlSerializationReader.ReadReferencedElement(), System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(), System.Xml.XmlReader.ReadStartElement(), System.Xml.Serialization.XmlSerializationReader.ShrinkArray(), System.Xml.XmlReader.Skip(), System.Xml.Serialization.XmlSerializationReader.ToXmlQualifiedName(), System.type, System.Xml.Serialization.Type, System.value, System.SR.XmlInvalidArrayDimentions, and System.SR.XmlRpcArrayOfValueTypes.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement().