Terraria: System.Xml.Serialization.XmlSerializationReader.ReadXmlNodes
ReadXmlNodes()
object System.Xml.Serialization.XmlSerializationReader.ReadXmlNodes (bool elementCanBeType) inline private
Definition at line 2132 of file XmlSerializationReader.cs.
    {
        List<XmlNode> list = new List<XmlNode>();
        string localName = Reader.LocalName;
        string namespaceURI = Reader.NamespaceURI;
        string name = Reader.Name;
        string text = null;
        string text2 = null;
        int num = 0;
        int lineNumber = -1;
        int linePosition = -1;
        XmlNode xmlNode = null;
        if (Reader.NodeType == XmlNodeType.Attribute)
        {
            XmlAttribute xmlAttribute = Document.CreateAttribute(name, namespaceURI);
            xmlAttribute.Value = Reader.Value;
            xmlNode = xmlAttribute;
        }
        else
        {
            xmlNode = Document.CreateElement(name, namespaceURI);
        }
        GetCurrentPosition(out lineNumber, out linePosition);
        XmlElement xmlElement = xmlNode as XmlElement;
        while (Reader.MoveToNextAttribute())
        {
            if (IsXmlnsAttribute(Reader.Name) || (Reader.Name == "id" && (!_soap12 || Reader.NamespaceURI == "http://www.w3.org/2003/05/soap-encoding")))
            {
                num++;
            }
            if ((object)Reader.LocalName == _typeID && ((object)Reader.NamespaceURI == _instanceNsID || (object)Reader.NamespaceURI == _instanceNs2000ID || (object)Reader.NamespaceURI == _instanceNs1999ID))
            {
                string value = Reader.Value;
                int num2 = value.LastIndexOf(':');
                text = ((num2 >= 0) ? value.Substring(num2 + 1) : value);
                text2 = Reader.LookupNamespace((num2 >= 0) ? value.Substring(0, num2) : "");
            }
            XmlAttribute xmlAttribute2 = (XmlAttribute)Document.ReadNode(_r);
            list.Add(xmlAttribute2);
            xmlElement?.SetAttributeNode(xmlAttribute2);
        }
        if (elementCanBeType && text == null)
        {
            text = localName;
            text2 = namespaceURI;
            XmlAttribute xmlAttribute3 = Document.CreateAttribute(_typeID, _instanceNsID);
            xmlAttribute3.Value = name;
            list.Add(xmlAttribute3);
        }
        if (text == "anyType" && ((object)text2 == _schemaNsID || (object)text2 == _schemaNs1999ID || (object)text2 == _schemaNs2000ID))
        {
            num++;
        }
        Reader.MoveToElement();
        if (Reader.IsEmptyElement)
        {
            Reader.Skip();
        }
        else
        {
            Reader.ReadStartElement();
            Reader.MoveToContent();
            while (Reader.NodeType != XmlNodeType.EndElement)
            {
                XmlNode xmlNode2 = Document.ReadNode(_r);
                list.Add(xmlNode2);
                xmlElement?.AppendChild(xmlNode2);
                Reader.MoveToContent();
            }
            ReadEndElement();
        }
        if (list.Count <= num)
        {
            return new object();
        }
        XmlNode[] result = list.ToArray();
        UnknownNode(xmlNode, null, null);
        return result;
    }
References System.Xml.Serialization.XmlSerializationReader._instanceNs1999ID, System.Xml.Serialization.XmlSerializationReader._instanceNs2000ID, System.Xml.Serialization.XmlSerializationReader._instanceNsID, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._schemaNs1999ID, System.Xml.Serialization.XmlSerializationReader._schemaNs2000ID, System.Xml.Serialization.XmlSerializationReader._schemaNsID, System.Xml.Serialization.XmlSerializationReader._soap12, System.Xml.Serialization.XmlSerializationReader._typeID, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateElement(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReader.Document, System.Xml.Serialization.XmlSerializationReader.GetCurrentPosition(), System.Xml.Serialization.XmlSerializationReader.IsXmlnsAttribute(), System.list, System.Xml.Serialization.XmlSerializationReader.ReadEndElement(), System.Xml.XmlDocument.ReadNode(), System.text, System.Xml.Serialization.XmlSerializationReader.UnknownNode(), System.value, and System.Xml.XmlAttribute.Value.
Referenced by System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive().