Terraria: System.Xml.Serialization.XmlSerializationReader.InitPrimitiveIDs
InitPrimitiveIDs()
void System.Xml.Serialization.XmlSerializationReader.InitPrimitiveIDs () inline private
Definition at line 333 of file XmlSerializationReader.cs.
    {
        if (_tokenID == null)
        {
            _r.NameTable.Add("http://www.w3.org/2001/XMLSchema");
            _r.NameTable.Add("http://microsoft.com/wsdl/types/");
            _stringID = _r.NameTable.Add("string");
            _intID = _r.NameTable.Add("int");
            _booleanID = _r.NameTable.Add("boolean");
            _shortID = _r.NameTable.Add("short");
            _longID = _r.NameTable.Add("long");
            _floatID = _r.NameTable.Add("float");
            _doubleID = _r.NameTable.Add("double");
            _decimalID = _r.NameTable.Add("decimal");
            _dateTimeID = _r.NameTable.Add("dateTime");
            _qnameID = _r.NameTable.Add("QName");
            _dateID = _r.NameTable.Add("date");
            _timeID = _r.NameTable.Add("time");
            _hexBinaryID = _r.NameTable.Add("hexBinary");
            _base64BinaryID = _r.NameTable.Add("base64Binary");
            _unsignedByteID = _r.NameTable.Add("unsignedByte");
            _byteID = _r.NameTable.Add("byte");
            _unsignedShortID = _r.NameTable.Add("unsignedShort");
            _unsignedIntID = _r.NameTable.Add("unsignedInt");
            _unsignedLongID = _r.NameTable.Add("unsignedLong");
            _oldDecimalID = _r.NameTable.Add("decimal");
            _oldTimeInstantID = _r.NameTable.Add("timeInstant");
            _charID = _r.NameTable.Add("char");
            _guidID = _r.NameTable.Add("guid");
            _timeSpanID = _r.NameTable.Add("TimeSpan");
            _dateTimeOffsetID = _r.NameTable.Add("dateTimeOffset");
            _base64ID = _r.NameTable.Add("base64");
            _anyURIID = _r.NameTable.Add("anyURI");
            _durationID = _r.NameTable.Add("duration");
            _ENTITYID = _r.NameTable.Add("ENTITY");
            _ENTITIESID = _r.NameTable.Add("ENTITIES");
            _gDayID = _r.NameTable.Add("gDay");
            _gMonthID = _r.NameTable.Add("gMonth");
            _gMonthDayID = _r.NameTable.Add("gMonthDay");
            _gYearID = _r.NameTable.Add("gYear");
            _gYearMonthID = _r.NameTable.Add("gYearMonth");
            _IDID = _r.NameTable.Add("ID");
            _IDREFID = _r.NameTable.Add("IDREF");
            _IDREFSID = _r.NameTable.Add("IDREFS");
            _integerID = _r.NameTable.Add("integer");
            _languageID = _r.NameTable.Add("language");
            _nameID = _r.NameTable.Add("Name");
            _NCNameID = _r.NameTable.Add("NCName");
            _NMTOKENID = _r.NameTable.Add("NMTOKEN");
            _NMTOKENSID = _r.NameTable.Add("NMTOKENS");
            _negativeIntegerID = _r.NameTable.Add("negativeInteger");
            _nonNegativeIntegerID = _r.NameTable.Add("nonNegativeInteger");
            _nonPositiveIntegerID = _r.NameTable.Add("nonPositiveInteger");
            _normalizedStringID = _r.NameTable.Add("normalizedString");
            _NOTATIONID = _r.NameTable.Add("NOTATION");
            _positiveIntegerID = _r.NameTable.Add("positiveInteger");
            _tokenID = _r.NameTable.Add("token");
        }
    }
References System.Xml.Serialization.XmlSerializationReader._anyURIID, System.Xml.Serialization.XmlSerializationReader._base64BinaryID, System.Xml.Serialization.XmlSerializationReader._base64ID, System.Xml.Serialization.XmlSerializationReader._booleanID, System.Xml.Serialization.XmlSerializationReader._byteID, System.Xml.Serialization.XmlSerializationReader._charID, System.Xml.Serialization.XmlSerializationReader._dateID, System.Xml.Serialization.XmlSerializationReader._dateTimeID, System.Xml.Serialization.XmlSerializationReader._dateTimeOffsetID, System.Xml.Serialization.XmlSerializationReader._decimalID, System.Xml.Serialization.XmlSerializationReader._doubleID, System.Xml.Serialization.XmlSerializationReader._durationID, System.Xml.Serialization.XmlSerializationReader._ENTITIESID, System.Xml.Serialization.XmlSerializationReader._ENTITYID, System.Xml.Serialization.XmlSerializationReader._floatID, System.Xml.Serialization.XmlSerializationReader._gDayID, System.Xml.Serialization.XmlSerializationReader._gMonthDayID, System.Xml.Serialization.XmlSerializationReader._gMonthID, System.Xml.Serialization.XmlSerializationReader._guidID, System.Xml.Serialization.XmlSerializationReader._gYearID, System.Xml.Serialization.XmlSerializationReader._gYearMonthID, System.Xml.Serialization.XmlSerializationReader._hexBinaryID, System.Xml.Serialization.XmlSerializationReader._IDID, System.Xml.Serialization.XmlSerializationReader._IDREFID, System.Xml.Serialization.XmlSerializationReader._IDREFSID, System.Xml.Serialization.XmlSerializationReader._integerID, System.Xml.Serialization.XmlSerializationReader._intID, System.Xml.Serialization.XmlSerializationReader._languageID, System.Xml.Serialization.XmlSerializationReader._longID, System.Xml.Serialization.XmlSerializationReader._nameID, System.Xml.Serialization.XmlSerializationReader._NCNameID, System.Xml.Serialization.XmlSerializationReader._negativeIntegerID, System.Xml.Serialization.XmlSerializationReader._NMTOKENID, System.Xml.Serialization.XmlSerializationReader._NMTOKENSID, System.Xml.Serialization.XmlSerializationReader._nonNegativeIntegerID, System.Xml.Serialization.XmlSerializationReader._nonPositiveIntegerID, System.Xml.Serialization.XmlSerializationReader._normalizedStringID, System.Xml.Serialization.XmlSerializationReader._NOTATIONID, System.Xml.Serialization.XmlSerializationReader._oldDecimalID, System.Xml.Serialization.XmlSerializationReader._oldTimeInstantID, System.Xml.Serialization.XmlSerializationReader._positiveIntegerID, System.Xml.Serialization.XmlSerializationReader._qnameID, System.Xml.Serialization.XmlSerializationReader._r, System.Xml.Serialization.XmlSerializationReader._shortID, System.Xml.Serialization.XmlSerializationReader._stringID, System.Xml.Serialization.XmlSerializationReader._timeID, System.Xml.Serialization.XmlSerializationReader._timeSpanID, System.Xml.Serialization.XmlSerializationReader._tokenID, System.Xml.Serialization.XmlSerializationReader._unsignedByteID, System.Xml.Serialization.XmlSerializationReader._unsignedIntID, System.Xml.Serialization.XmlSerializationReader._unsignedLongID, System.Xml.Serialization.XmlSerializationReader._unsignedShortID, System.Xml.XmlNameTable.Add(), and System.Xml.XmlReader.NameTable.
Referenced by System.Xml.Serialization.XmlSerializationReader.GetPrimitiveType(), System.Xml.Serialization.XmlSerializationReader.ReadTypedNull(), and System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive().