Terraria: System.IO.Pipes.PipeStream.ReadWriteValueTaskSource.CompleteCore
CompleteCore()
override void System.IO.Pipes.PipeStream.ReadWriteValueTaskSource.CompleteCore (uint errorCode, uint numBytes) inline protected
Definition at line 158 of file PipeStream.cs.
        {
            if (!_isWrite)
            {
                bool completion = true;
                switch (errorCode)
                {
                case 109u:
                case 232u:
                case 233u:
                    errorCode = 0u;
                    break;
                case 234u:
                    errorCode = 0u;
                    completion = false;
                    break;
                }
                _pipeStream.UpdateMessageCompletion(completion);
            }
            switch (errorCode)
            {
            case 0u:
                _source.SetResult((int)numBytes);
                break;
            case 995u:
            {
                CancellationToken token = _cancellationRegistration.Token;
                _source.SetException(token.IsCancellationRequested ? new OperationCanceledException(token) : new OperationCanceledException());
                break;
            }
            default:
                _source.SetException(_pipeStream.WinIOError((int)errorCode));
                break;
            }
        }
References System.IO.Pipes.PipeStream.PipeValueTaskSource._cancellationRegistration, System.IO.Pipes.PipeStream.ReadWriteValueTaskSource._isWrite, System.IO.Pipes.PipeStream.PipeValueTaskSource._pipeStream, System.IO.Pipes.PipeStream.PipeValueTaskSource._source, System.Threading.CancellationToken.IsCancellationRequested, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetException(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult(), System.Threading.CancellationTokenRegistration.Token, System.IO.Pipes.PipeStream.UpdateMessageCompletion(), and System.IO.Pipes.PipeStream.WinIOError().