Terraria: System.Runtime.Serialization.ReflectionXmlClassWriter.ReflectionWriteMembers
ReflectionWriteMembers()
override int System.Runtime.Serialization.ReflectionXmlClassWriter.ReflectionWriteMembers (XmlWriterDelegator xmlWriter, object obj, XmlObjectSerializerWriteContext context, ClassDataContract classContract, ClassDataContract derivedMostClassContract, int childElementIndex, XmlDictionaryString[] emptyStringArray) inline protected
Definition at line 10 of file ReflectionXmlClassWriter.cs.
    {
        int num = ((classContract.BaseContract != null) ? ReflectionWriteMembers(xmlWriter, obj, context, classContract.BaseContract, derivedMostClassContract, childElementIndex, emptyStringArray) : 0);
        childElementIndex += num;
        XmlDictionaryString[] memberNames = classContract.MemberNames;
        XmlDictionaryString @namespace = classContract.Namespace;
        context.IncrementItemCount(classContract.Members.Count);
        int num2 = 0;
        while (num2 < classContract.Members.Count)
        {
            DataMember dataMember = classContract.Members[num2];
            Type memberType = dataMember.MemberType;
            if (dataMember.IsGetOnlyCollection)
            {
                context.StoreIsGetOnlyCollection();
            }
            else
            {
                context.ResetIsGetOnlyCollection();
            }
            bool flag = true;
            object obj2 = null;
            if (!dataMember.EmitDefaultValue)
            {
                obj2 = ReflectionGetMemberValue(obj, dataMember);
                object defaultValue = XmlFormatGeneratorStatics.GetDefaultValue(memberType);
                if ((obj2 == null && defaultValue == null) || (obj2 != null && obj2.Equals(defaultValue)))
                {
                    flag = false;
                    if (dataMember.IsRequired)
                    {
                        XmlObjectSerializerWriteContext.ThrowRequiredMemberMustBeEmitted(dataMember.Name, classContract.UnderlyingType);
                    }
                }
            }
            if (flag)
            {
                bool flag2 = CheckIfMemberHasConflict(dataMember, classContract, derivedMostClassContract);
                if (obj2 == null)
                {
                    obj2 = ReflectionGetMemberValue(obj, dataMember);
                }
                PrimitiveDataContract memberPrimitiveContract = dataMember.MemberPrimitiveContract;
                if (flag2 || !ReflectionTryWritePrimitive(xmlWriter, context, memberType, obj2, memberNames[num2 + childElementIndex], @namespace, memberPrimitiveContract))
                {
                    ReflectionWriteStartElement(xmlWriter, memberType, @namespace, @namespace.Value, dataMember.Name, 0);
                    if (classContract.ChildElementNamespaces[num2 + childElementIndex] != null)
                    {
                        XmlDictionaryString ns = classContract.ChildElementNamespaces[num2 + childElementIndex];
                        xmlWriter.WriteNamespaceDecl(ns);
                    }
                    ReflectionWriteValue(xmlWriter, context, memberType, obj2, flag2, null);
                    ReflectionWriteEndElement(xmlWriter);
                }
                if (classContract.HasExtensionData)
                {
                    context.WriteExtensionData(xmlWriter, ((IExtensibleDataObject)obj).ExtensionData, num);
                }
            }
            num2++;
            num++;
        }
        return num;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Xml.Dictionary, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetDefaultValue(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.obj, System.Runtime.Serialization.ReflectionXmlClassWriter.ReflectionWriteMembers(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResetIsGetOnlyCollection(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.StoreIsGetOnlyCollection(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.ThrowRequiredMemberMustBeEmitted(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteExtensionData().
Referenced by System.Runtime.Serialization.ReflectionXmlClassWriter.ReflectionWriteMembers().