Terraria: UIAchievementsMenu.SetupGamepadPoints
SetupGamepadPoints()
void UIAchievementsMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 3;
         int num = 3000;
         UILinkPointNavigator.SetPosition(num, _backpanel.GetInnerDimensions().ToRectangle().Center.ToVector2());
         UILinkPointNavigator.SetPosition(num + 1, _outerContainer.GetInnerDimensions().ToRectangle().Center.ToVector2());
         int num2 = num;
         UILinkPoint uILinkPoint = UILinkPointNavigator.Points[num2];
         uILinkPoint.Unlink();
         uILinkPoint.Up = num2 + 1;
         num2++;
         UILinkPoint uILinkPoint2 = UILinkPointNavigator.Points[num2];
         uILinkPoint2.Unlink();
         uILinkPoint2.Up = num2 + 1;
         uILinkPoint2.Down = num2 - 1;
         for (int i = 0; i < _categoryButtons.Count; i++)
         {
             num2 = (UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = num2 + 1);
             UILinkPointNavigator.SetPosition(num2, _categoryButtons[i].GetInnerDimensions().ToRectangle().Center.ToVector2());
             UILinkPoint uILinkPoint3 = UILinkPointNavigator.Points[num2];
             uILinkPoint3.Unlink();
             uILinkPoint3.Left = ((i == 0) ? (-3) : (num2 - 1));
             uILinkPoint3.Right = ((i == _categoryButtons.Count - 1) ? (-4) : (num2 + 1));
             uILinkPoint3.Down = num;
         }
     }
References _backpanel, _categoryButtons, _outerContainer, UILinkPointNavigator.Shortcuts.BackButtonCommand, UILinkPoint.Down, UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX, UIElement.GetInnerDimensions(), UILinkPoint.Left, UILinkPointNavigator.Points, UILinkPoint.Right, UILinkPointNavigator.SetPosition(), CalculatedStyle.ToRectangle(), UILinkPoint.Unlink(), and UILinkPoint.Up.
Referenced by Draw().