Terraria: UIAchievementsMenu.Draw
Draw()
override void UIAchievementsMenu.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from UIElement.
     {
         base.Draw(spriteBatch);
         for (int i = 0; i < _categoryButtons.Count; i++)
         {
             if (_categoryButtons[i].IsMouseHovering)
             {
                 string text = "";
                 text = i switch
                 {
                     3 => Language.GetTextValue("Achievements.ChallengerCategory"),
                     1 => Language.GetTextValue("Achievements.CollectorCategory"),
                     2 => Language.GetTextValue("Achievements.ExplorerCategory"),
                     0 => Language.GetTextValue("Achievements.SlayerCategory"),
                     -1 => Language.GetTextValue("Achievements.NoCategory"),
                     _ => Language.GetTextValue("Achievements.NoCategory"),
                 };
                 float x = FontAssets.MouseText.Value.MeasureString(text).X;
                 Vector2 vector = new Vector2(Main.mouseX, Main.mouseY) + new Vector2(16f);
                 if (vector.Y > (float)(Main.screenHeight - 30))
                 {
                     vector.Y = Main.screenHeight - 30;
                 }
                 if (vector.X > (float)Main.screenWidth - x)
                 {
                     vector.X = Main.screenWidth - 460;
                 }
                 Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, text, vector.X, vector.Y, new Color(Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor), Color.Black, Vector2.Zero);
                 break;
             }
         }
         SetupGamepadPoints(spriteBatch);
     }
References _categoryButtons, Color, Utils.DrawBorderStringFourWay(), Language.GetTextValue(), UIElement.IsMouseHovering, FontAssets.MouseText, Main.mouseTextColor, Main.mouseX, Main.mouseY, Main.screenHeight, Main.screenWidth, SetupGamepadPoints(), and Asset< T >.Value.