Terraria: LaunchInitializer.LoadClientParameters
LoadClientParameters()
static void LaunchInitializer.LoadClientParameters (Main game) inline static private
     {
         string iP;
         if ((iP = TryParameter("-j", "-join")) != null)
         {
             game.AutoJoin(iP);
         }
         string arg;
         if ((arg = TryParameter("-pass", "-password")) != null)
         {
             Netplay.ServerPassword = Main.ConvertFromSafeArgument(arg);
             game.AutoPass();
         }
         if (HasParameter("-host"))
         {
             game.AutoHost();
         }
     }
References Main.AutoHost(), Main.AutoJoin(), Main.AutoPass(), Main.ConvertFromSafeArgument(), HasParameter(), Netplay.ServerPassword, and TryParameter().
Referenced by LoadParameters().