Terraria: System.Xml.Xsl.XsltOld.VariableAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.VariableAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 120 of file VariableAction.cs.
    {
        object obj = null;
        switch (frame.State)
        {
        default:
            return;
        case 0:
        {
            if (IsGlobal)
            {
                if (frame.GetVariable(_varKey) != null)
                {
                    frame.Finished();
                    return;
                }
                frame.SetVariable(_varKey, BeingComputedMark);
            }
            if (varType == VariableType.GlobalParameter)
            {
                obj = processor.GetGlobalParameter(name);
            }
            else if (varType == VariableType.LocalParameter)
            {
                obj = processor.GetParameter(name);
            }
            if (obj != null)
            {
                break;
            }
            if (selectKey != -1)
            {
                obj = processor.RunQuery(frame, selectKey);
                break;
            }
            if (containedActions == null)
            {
                obj = string.Empty;
                break;
            }
            NavigatorOutput output = new NavigatorOutput(baseUri);
            processor.PushOutput(output);
            processor.PushActionFrame(frame);
            frame.State = 1;
            return;
        }
        case 1:
        {
            IRecordOutput recordOutput = processor.PopOutput();
            obj = ((NavigatorOutput)recordOutput).Navigator;
            break;
        }
        case 2:
            break;
        }
        frame.SetVariable(_varKey, obj);
        frame.Finished();
    }
References System.Xml.Xsl.XsltOld.VariableAction._varKey, System.Xml.Xsl.XsltOld.VariableAction.baseUri, System.Xml.Xsl.XsltOld.VariableAction.BeingComputedMark, System.Xml.Xsl.XsltOld.ContainerAction.containedActions, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.Xsl.XsltOld.ActionFrame.GetVariable(), System.Xml.Xsl.XsltOld.VariableAction.IsGlobal, System.Xml.Xsl.XsltOld.VariableAction.name, System.obj, System.Xml.Xsl.XsltOld.VariableAction.selectKey, System.Xml.Xsl.XsltOld.ActionFrame.SetVariable(), System.Xml.Xsl.XsltOld.ActionFrame.State, and System.Xml.Xsl.XsltOld.VariableAction.varType.