Terraria: System.Xml.Xsl.XsltOld.VariableAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.VariableAction.Compile (Compiler compiler) inline package
Definition at line 74 of file VariableAction.cs.
    {
        stylesheetid = compiler.Stylesheetid;
        baseUri = compiler.Input.BaseURI;
        CompileAttributes(compiler);
        CheckRequiredAttribute(compiler, name, "name");
        if (compiler.Recurse())
        {
            CompileTemplate(compiler);
            compiler.ToParent();
            if (selectKey != -1 && containedActions != null)
            {
                throw XsltException.Create(System.SR.Xslt_VariableCntSel2, nameStr);
            }
        }
        if (containedActions != null)
        {
            baseUri = baseUri + "#" + compiler.GetUnicRtfId();
        }
        else
        {
            baseUri = null;
        }
        _varKey = compiler.InsertVariable(this);
    }
References System.Xml.Xsl.XsltOld.VariableAction._varKey, System.Xml.Xsl.XsltOld.VariableAction.baseUri, System.Xml.Xsl.XsltOld.CompiledAction.CheckRequiredAttribute(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTemplate(), System.Xml.Xsl.XsltOld.ContainerAction.containedActions, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.VariableAction.name, System.Xml.Xsl.XsltOld.VariableAction.nameStr, System.Xml.Xsl.XsltOld.VariableAction.selectKey, System.Xml.Xsl.XsltOld.VariableAction.stylesheetid, and System.SR.Xslt_VariableCntSel2.