Terraria: System.Runtime.Intrinsics.Vector128.Equals
Equals() [3/3]
bool System.Runtime.Intrinsics.Vector128< T >.Equals (Vector128< T > other) inline
Definition at line 1073 of file Vector128.cs.
    {
        ThrowHelper.ThrowForUnsupportedIntrinsicsVectorBaseType<T>();
        if (Sse.IsSupported && typeof(T) == typeof(float))
        {
            Vector128<float> value = Sse.CompareEqual(this.AsSingle(), other.AsSingle());
            return Sse.MoveMask(value) == 15;
        }
        if (Sse2.IsSupported)
        {
            if (typeof(T) == typeof(double))
            {
                Vector128<double> value2 = Sse2.CompareEqual(this.AsDouble(), other.AsDouble());
                return Sse2.MoveMask(value2) == 3;
            }
            Vector128<byte> value3 = Sse2.CompareEqual(this.AsByte(), other.AsByte());
            return Sse2.MoveMask(value3) == 65535;
        }
        return SoftwareFallback(in this, other);
        static bool SoftwareFallback(in Vector128<T> vector, Vector128<T> other)
        {
            for (int i = 0; i < Count; i++)
            {
                if (!((IEquatable<T>)(object)vector.GetElement(i)).Equals(other.GetElement(i)))
                {
                    return false;
                }
            }
            return true;
        }
    }
References System.Runtime.Intrinsics.X86.Sse.CompareEqual(), System.Runtime.Intrinsics.X86.Sse2.CompareEqual(), System.Runtime.Intrinsics.Vector128< T >.Count, System.Runtime.Intrinsics.X86.Sse.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.Runtime.Intrinsics.X86.Sse.MoveMask(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.other, and System.value.
Referenced by System.Runtime.Intrinsics.Vector128< T >.Equals().