Terraria: System.Runtime.Intrinsics.Vector128.Create
Create() [2/30]
static Vector128< byte > System.Runtime.Intrinsics.Vector128< T >.Create (byte value) inline static
Definition at line 138 of file Vector128.cs.
    {
        if (Sse2.IsSupported || AdvSimd.IsSupported)
        {
            return Create(value);
        }
        return SoftwareFallback(value);
        unsafe static Vector128<byte> SoftwareFallback(byte value)
        {
            byte* source = stackalloc byte[16]
            {
                value, value, value, value, value, value, value, value, value, value,
                value, value, value, value, value, value
            };
            return Unsafe.AsRef<Vector128<byte>>(source);
        }
    }
References System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.source, and System.value.
Referenced by System.Collections.BitArray.BitArray(), System.Collections.BitArray.CopyTo(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.HexConverter.EncodeToUtf16_Ssse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeAdvSimd64(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeAdvSimd64(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified(), System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiChar_Sse2(), System.Text.Latin1Utility.GetIndexOfFirstNonLatin1Char_Sse2(), System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.Numerics.Matrix4x4.Invert(), System.Numerics.Matrix4x4.Lerp(), System.Numerics.VectorMath.Lerp(), System.String.MakeSeparatorListVectorized(), System.Text.ASCIIUtility.NarrowUtf16ToAscii_Sse2(), System.Text.Latin1Utility.NarrowUtf16ToLatin1_Sse2(), System.Collections.BitArray.Not(), System.Numerics.Matrix4x4.operator*(), System.Buffers.Text.Base64.Ssse3Decode(), System.Buffers.Text.Base64.Ssse3Encode(), and System.Text.Unicode.Utf8Utility.TranscodeToUtf8().