Terraria: System.Runtime.Intrinsics.Vector128.CreateScalarUnsafe
CreateScalarUnsafe() [1/10]
static unsafe Vector128< byte > System.Runtime.Intrinsics.Vector128< T >.CreateScalarUnsafe (byte value) inline static
Definition at line 829 of file Vector128.cs.
    {
        byte* ptr = stackalloc byte[16];
        *ptr = value;
        return Unsafe.AsRef<Vector128<byte>>(ptr);
    }
References System.value.
Referenced by System.Math.CopySign(), System.MathF.CopySign(), System.Collections.BitArray.CopyTo(), System.Runtime.Intrinsics.Vector128< T >.CreateScalar(), System.Runtime.Intrinsics.Vector128< T >.CreateScalar(), System.BitConverter.DoubleToInt64Bits(), System.HexConverter.EncodeToUtf16_Ssse3(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeAdvSimd64(), System.BitConverter.Int32BitsToSingle(), System.BitConverter.Int64BitsToDouble(), System.MathF.ReciprocalEstimate(), System.MathF.ReciprocalSqrtEstimate(), System.BitConverter.SingleToInt32Bits(), and System.Text.Unicode.Utf8Utility.TranscodeToUtf8().