Terraria: System.Collections.Specialized.BitVector32.Section.Equals
Equals() [1/2]
override bool System.Collections.Specialized.BitVector32.Section.Equals ([NotNullWhen(true)] object? o) inline
Definition at line 24 of file BitVector32.cs.
        {
            if (o is Section obj)
            {
                return Equals(obj);
            }
            return false;
        }
References System.Collections.Specialized.BitVector32.Section.Equals(), and System.obj.
Referenced by System.Collections.Specialized.BitVector32.Section.Equals(), and System.Collections.Specialized.BitVector32.Section.operator==().