Terraria: System.Xml.XPath.XNodeNavigator.MoveToNamespace
MoveToNamespace()
override bool System.Xml.XPath.XNodeNavigator.MoveToNamespace (string localName) inline virtual
Reimplemented from System.Xml.XPath.XPathNavigator.
Definition at line 409 of file XNodeNavigator.cs.
    {
        if (_source is XElement xElement)
        {
            if (localName == "xmlns")
            {
                return false;
            }
            if (localName != null && localName.Length == 0)
            {
                localName = "xmlns";
            }
            for (XAttribute xAttribute = GetFirstNamespaceDeclarationGlobal(xElement); xAttribute != null; xAttribute = GetNextNamespaceDeclarationGlobal(xAttribute))
            {
                if (xAttribute.Name.LocalName == localName)
                {
                    _source = xAttribute;
                    _parent = xElement;
                    return true;
                }
            }
            if (localName == "xml")
            {
                _source = GetXmlNamespaceDeclaration();
                _parent = xElement;
                return true;
            }
        }
        return false;
    }
References System.Xml.XPath.XNodeNavigator._parent, System.Xml.XPath.XNodeNavigator._source, System.Xml.Dictionary, System.Xml.XPath.XNodeNavigator.GetFirstNamespaceDeclarationGlobal(), System.Xml.XPath.XNodeNavigator.GetNextNamespaceDeclarationGlobal(), and System.Xml.XPath.XNodeNavigator.GetXmlNamespaceDeclaration().