Terraria: System.Xml.XPath.XNodeNavigator.GetXmlNamespaceDeclaration
GetXmlNamespaceDeclaration()
static XAttribute System.Xml.XPath.XNodeNavigator.GetXmlNamespaceDeclaration () inline static private
Definition at line 757 of file XNodeNavigator.cs.
    {
        if (s_XmlNamespaceDeclaration == null)
        {
            Interlocked.CompareExchange(ref s_XmlNamespaceDeclaration, new XAttribute(XNamespace.Xmlns.GetName("xml"), xmlPrefixNamespace), null);
        }
        return s_XmlNamespaceDeclaration;
    }
References System.Threading.Interlocked.CompareExchange(), System.Xml.Dictionary, System.Xml.XPath.XNodeNavigator.s_XmlNamespaceDeclaration, System.Xml.Linq.XNamespace.Xmlns, and System.Xml.XPath.XNodeNavigator.xmlPrefixNamespace.
Referenced by System.Xml.XPath.XNodeNavigator.IsXmlNamespaceDeclaration(), System.Xml.XPath.XNodeNavigator.MoveToFirstNamespace(), System.Xml.XPath.XNodeNavigator.MoveToNamespace(), and System.Xml.XPath.XNodeNavigator.MoveToNextNamespace().