Terraria: System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore
GetSpecifiedECCurveCore() [1/2]
static ECCurve System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore (SpecifiedECDomain specifiedParameters) inline static private
Definition at line 161 of file EccKeyFormatHelper.cs.
    {
        if (specifiedParameters.Version < 1 || specifiedParameters.Version > 3)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        if (specifiedParameters.Version > 1 && !specifiedParameters.Curve.Seed.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        string fieldType = specifiedParameters.FieldID.FieldType;
        bool flag;
        byte[] array;
        if (!(fieldType == "1.2.840.10045.1.1"))
        {
            if (!(fieldType == "1.2.840.10045.1.2"))
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            flag = false;
            AsnReader asnReader = new AsnReader(specifiedParameters.FieldID.Parameters, AsnEncodingRules.BER);
            AsnReader asnReader2 = asnReader.ReadSequence();
            asnReader.ThrowIfNotEmpty();
            if (!asnReader2.TryReadInt32(out var value) || value > 661 || value < 0)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            int value2 = -1;
            int value3 = -1;
            string text = asnReader2.ReadObjectIdentifier();
            int value4;
            if (!(text == "1.2.840.10045.1.2.3.2"))
            {
                if (!(text == "1.2.840.10045.1.2.3.3"))
                {
                    throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
                }
                AsnReader asnReader3 = asnReader2.ReadSequence();
                if (!asnReader3.TryReadInt32(out value4) || !asnReader3.TryReadInt32(out value2) || !asnReader3.TryReadInt32(out value3) || value4 < 1 || value2 <= value4 || value3 <= value2 || value3 >= value)
                {
                    throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
                }
                asnReader3.ThrowIfNotEmpty();
            }
            else if (!asnReader2.TryReadInt32(out value4) || value4 >= value || value4 < 1)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            asnReader2.ThrowIfNotEmpty();
            BitArray bitArray = new BitArray(value + 1);
            bitArray.Set(value, value: true);
            bitArray.Set(value4, value: true);
            bitArray.Set(0, value: true);
            if (value2 > 0)
            {
                bitArray.Set(value2, value: true);
                bitArray.Set(value3, value: true);
            }
            array = new byte[(value + 7) / 8];
            bitArray.CopyTo(array, 0);
            Array.Reverse(array);
        }
        else
        {
            flag = true;
            AsnReader asnReader4 = new AsnReader(specifiedParameters.FieldID.Parameters, AsnEncodingRules.BER);
            ReadOnlySpan<byte> readOnlySpan = asnReader4.ReadIntegerBytes().Span;
            asnReader4.ThrowIfNotEmpty();
            if (readOnlySpan[0] == 0)
            {
                readOnlySpan = readOnlySpan.Slice(1);
            }
            if (readOnlySpan.Length > 82)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            array = readOnlySpan.ToArray();
        }
        ECCurve result;
        if (flag)
        {
            ECCurve eCCurve = default(ECCurve);
            eCCurve.CurveType = ECCurve.ECCurveType.PrimeShortWeierstrass;
            eCCurve.Prime = array;
            result = eCCurve;
        }
        else
        {
            ECCurve eCCurve = default(ECCurve);
            eCCurve.CurveType = ECCurve.ECCurveType.Characteristic2;
            eCCurve.Polynomial = array;
            result = eCCurve;
        }
        result.A = specifiedParameters.Curve.A.ToUnsignedIntegerBytes(array.Length);
        result.B = specifiedParameters.Curve.B.ToUnsignedIntegerBytes(array.Length);
        result.Order = specifiedParameters.Order.ToUnsignedIntegerBytes(array.Length);
        ReadOnlySpan<byte> span = specifiedParameters.Base.Span;
        if (span[0] != 4 || span.Length != 2 * array.Length + 1)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        result.G.X = span.Slice(1, array.Length).ToArray();
        result.G.Y = span.Slice(1 + array.Length).ToArray();
        if (specifiedParameters.Cofactor.HasValue)
        {
            result.Cofactor = specifiedParameters.Cofactor.Value.ToUnsignedIntegerBytes();
        }
        return result;
    }
References System.Security.Cryptography.Asn1.CurveAsn.A, System.array, System.Security.Cryptography.Asn1.CurveAsn.B, System.Security.Cryptography.Asn1.SpecifiedECDomain.Base, System.Security.Cryptography.Asn1.SpecifiedECDomain.Cofactor, System.Collections.BitArray.CopyTo(), System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.Asn1.SpecifiedECDomain.Curve, System.Security.Cryptography.Asn1.SpecifiedECDomain.FieldID, System.Security.Cryptography.Asn1.FieldID.FieldType, System.ReadOnlySpan< T >.Length, System.Security.Cryptography.Asn1.SpecifiedECDomain.Order, System.Security.Cryptography.Asn1.FieldID.Parameters, System.Formats.Asn1.AsnReader.ReadIntegerBytes(), System.Formats.Asn1.AsnReader.ReadObjectIdentifier(), System.Formats.Asn1.AsnReader.ReadSequence(), System.Array.Reverse(), System.Security.Cryptography.Asn1.CurveAsn.Seed, System.Collections.BitArray.Set(), System.ReadOnlySpan< T >.Slice(), System.ReadOnlyMemory< T >.Span, System.text, System.Formats.Asn1.AsnReader.ThrowIfNotEmpty(), System.ReadOnlySpan< T >.ToArray(), System.Formats.Asn1.AsnReader.TryReadInt32(), System.value, and System.Security.Cryptography.Asn1.SpecifiedECDomain.Version.
Referenced by System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurve(), and System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurve().