Terraria: System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey
FromECPrivateKey() [4/4]
static void System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey (System::Security::Cryptography::Asn1::ECPrivateKey key, in System::Security::Cryptography::Asn1::AlgorithmIdentifierAsn algId, out ECParameters ret) inline static package
Definition at line 10 of file EccKeyFormatHelper.cs.
    {
        ValidateParameters(key.Parameters, in algId);
        if (key.Version != 1)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        byte[] x = null;
        byte[] y = null;
        if (key.PublicKey.HasValue)
        {
            ReadOnlySpan<byte> span = key.PublicKey.Value.Span;
            if (span.Length == 0)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            if (span[0] != 4)
            {
                throw new CryptographicException(System.SR.Cryptography_NotValidPublicOrPrivateKey);
            }
            if (span.Length != 2 * key.PrivateKey.Length + 1)
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
            x = span.Slice(1, key.PrivateKey.Length).ToArray();
            y = span.Slice(1 + key.PrivateKey.Length).ToArray();
        }
        System.Security.Cryptography.Asn1.ECDomainParameters domainParameters = ((!key.Parameters.HasValue) ? System.Security.Cryptography.Asn1.ECDomainParameters.Decode(algId.Parameters.Value, AsnEncodingRules.DER) : key.Parameters.Value);
        ret = new ECParameters
        {
            Curve = GetCurve(domainParameters),
            Q =
            {
                X = x,
                Y = y
            },
            D = key.PrivateKey.ToArray()
        };
        ret.Validate();
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_NotValidPublicOrPrivateKey, System.D, System.Security.Cryptography.Asn1.ECDomainParameters.Decode(), System.Security.Cryptography.EccKeyFormatHelper.GetCurve(), System.key, System.ReadOnlySpan< T >.Length, System.Q, System.ReadOnlySpan< T >.Slice(), System.Security.Cryptography.EccKeyFormatHelper.ValidateParameters(), System.X, and System.Y.