Terraria: System.Security.Cryptography.EccKeyFormatHelper.WriteEcPrivateKey
WriteEcPrivateKey() [2/2]
static AsnWriter System.Security.Cryptography.EccKeyFormatHelper.WriteEcPrivateKey (in ECParameters ecParameters, bool includeDomainParameters) inline static private
Definition at line 436 of file EccKeyFormatHelper.cs.
    {
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.PushSequence();
        asnWriter.WriteInteger(1L);
        asnWriter.WriteOctetString(ecParameters.D);
        if (includeDomainParameters)
        {
            Asn1Tag value = new Asn1Tag(TagClass.ContextSpecific, 0, isConstructed: true);
            asnWriter.PushSequence(value);
            WriteEcParameters(ecParameters, asnWriter);
            asnWriter.PopSequence(value);
        }
        if (ecParameters.Q.X != null)
        {
            Asn1Tag value2 = new Asn1Tag(TagClass.ContextSpecific, 1, isConstructed: true);
            asnWriter.PushSequence(value2);
            WriteUncompressedPublicKey(in ecParameters, asnWriter);
            asnWriter.PopSequence(value2);
        }
        asnWriter.PopSequence();
        return asnWriter;
    }
References System.L, System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PushSequence(), System.value, System.Security.Cryptography.EccKeyFormatHelper.WriteEcParameters(), System.Formats.Asn1.AsnWriter.WriteInteger(), System.Formats.Asn1.AsnWriter.WriteOctetString(), and System.Security.Cryptography.EccKeyFormatHelper.WriteUncompressedPublicKey().