Terraria: System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey
WritePkcs8PrivateKey() [1/2]
static AsnWriter System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey (ECParameters ecParameters, AttributeAsn[] attributes = null) inline static package
Definition at line 297 of file EccKeyFormatHelper.cs.
    {
        ecParameters.Validate();
        if (ecParameters.D == null)
        {
            throw new CryptographicException(System.SR.Cryptography_CSP_NoPrivateKey);
        }
        AsnWriter privateKeyWriter = WriteEcPrivateKey(in ecParameters, includeDomainParameters: false);
        AsnWriter algorithmIdentifierWriter = WriteAlgorithmIdentifier(in ecParameters);
        AsnWriter attributesWriter = WritePrivateKeyInfoAttributes(attributes);
        return KeyFormatHelper.WritePkcs8(algorithmIdentifierWriter, privateKeyWriter, attributesWriter);
    }
References System.SR.Cryptography_CSP_NoPrivateKey, System.Security.Cryptography.ECParameters.D, System.Security.Cryptography.ECParameters.Validate(), System.Security.Cryptography.EccKeyFormatHelper.WriteAlgorithmIdentifier(), System.Security.Cryptography.EccKeyFormatHelper.WriteEcPrivateKey(), System.Security.Cryptography.KeyFormatHelper.WritePkcs8(), and System.Security.Cryptography.EccKeyFormatHelper.WritePrivateKeyInfoAttributes().
Referenced by System.Security.Cryptography.CngPkcs8.RewritePkcs8ECPrivateKeyWithZeroPublicKey(), System.Security.Cryptography.ECDiffieHellman.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellman.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellman.TryExportPkcs8PrivateKey(), and System.Security.Cryptography.ECDsa.TryExportPkcs8PrivateKey().