Terraria: System.Security.Cryptography.EccKeyFormatHelper.ValidateParameters
ValidateParameters() [1/2]
static void System.Security.Cryptography.EccKeyFormatHelper.ValidateParameters (ECDomainParameters? keyParameters, in AlgorithmIdentifierAsn algId) inline static private
Definition at line 112 of file EccKeyFormatHelper.cs.
    {
        if (!keyParameters.HasValue && !algId.Parameters.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        if (keyParameters.HasValue && algId.Parameters.HasValue)
        {
            ReadOnlySpan<byte> span = algId.Parameters.Value.Span;
            AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
            keyParameters.Value.Encode(asnWriter);
            if (!asnWriter.EncodedValueEquals(span))
            {
                throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
            }
        }
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.Security.Cryptography.Asn1.ECDomainParameters.Encode(), and System.Formats.Asn1.AsnWriter.EncodedValueEquals().
Referenced by System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), and System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey().