Terraria: System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey
WritePkcs8PrivateKey() [2/2]
static AsnWriter System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey (ECParameters ecParameters, System::Security::Cryptography::Asn1::AttributeAsn[] attributes = null) inline static package
Definition at line 225 of file EccKeyFormatHelper.cs.
    {
        ecParameters.Validate();
        if (ecParameters.D == null)
        {
            throw new CryptographicException(System.SR.Cryptography_CSP_NoPrivateKey);
        }
        AsnWriter privateKeyWriter = WriteEcPrivateKey(in ecParameters, includeDomainParameters: false);
        AsnWriter algorithmIdentifierWriter = WriteAlgorithmIdentifier(in ecParameters);
        AsnWriter attributesWriter = WritePrivateKeyInfoAttributes(attributes);
        return System.Security.Cryptography.KeyFormatHelper.WritePkcs8(algorithmIdentifierWriter, privateKeyWriter, attributesWriter);
    }
References System.SR.Cryptography_CSP_NoPrivateKey, System.Security.Cryptography.ECParameters.D, System.Security.Cryptography.ECParameters.Validate(), System.Security.Cryptography.EccKeyFormatHelper.WriteAlgorithmIdentifier(), System.Security.Cryptography.EccKeyFormatHelper.WriteEcPrivateKey(), System.Security.Cryptography.KeyFormatHelper.WritePkcs8(), and System.Security.Cryptography.EccKeyFormatHelper.WritePrivateKeyInfoAttributes().