Terraria: System.Security.Cryptography.EccKeyFormatHelper.GetCurve
GetCurve() [1/2]
static ECCurve System.Security.Cryptography.EccKeyFormatHelper.GetCurve (ECDomainParameters domainParameters) inline static private
Definition at line 130 of file EccKeyFormatHelper.cs.
    {
        if (domainParameters.Specified.HasValue)
        {
            return GetSpecifiedECCurve(domainParameters.Specified.Value);
        }
        if (domainParameters.Named == null)
        {
            throw new CryptographicException(System.SR.Cryptography_ECC_NamedCurvesOnly);
        }
        return ECCurve.CreateFromOid(domainParameters.Named switch
        {
            "1.2.840.10045.3.1.7" => Oids.secp256r1Oid,
            "1.3.132.0.34" => Oids.secp384r1Oid,
            "1.3.132.0.35" => Oids.secp521r1Oid,
            _ => new Oid(domainParameters.Named, null),
        });
    }
References System.Security.Cryptography.ECCurve.CreateFromOid(), System.SR.Cryptography_ECC_NamedCurvesOnly, System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurve(), System.Security.Cryptography.Asn1.ECDomainParameters.Named, and System.Security.Cryptography.Asn1.ECDomainParameters.Specified.
Referenced by System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), and System.Security.Cryptography.EccKeyFormatHelper.FromECPublicKey().