Terraria: System.Security.Cryptography.EccKeyFormatHelper.WriteEcParameters
WriteEcParameters() [2/2]
static void System.Security.Cryptography.EccKeyFormatHelper.WriteEcParameters (ECParameters ecParameters, AsnWriter writer) inline static private
Definition at line 256 of file EccKeyFormatHelper.cs.
    {
        if (ecParameters.Curve.IsNamed)
        {
            Oid oid = ecParameters.Curve.Oid;
            if (string.IsNullOrEmpty(oid.Value))
            {
                oid = Oid.FromFriendlyName(oid.FriendlyName, OidGroup.All);
            }
            writer.WriteObjectIdentifier(oid.Value);
        }
        else
        {
            if (!ecParameters.Curve.IsExplicit)
            {
                throw new CryptographicException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, ecParameters.Curve.CurveType.ToString()));
            }
            WriteSpecifiedECDomain(ecParameters, writer);
        }
    }
References System.SR.Cryptography_CurveNotSupported, System.Security.Cryptography.ECParameters.Curve, System.Security.Cryptography.ECCurve.CurveType, System.SR.Format(), System.Security.Cryptography.Oid.FriendlyName, System.Security.Cryptography.Oid.FromFriendlyName(), System.Security.Cryptography.ECCurve.IsExplicit, System.Security.Cryptography.ECCurve.IsNamed, System.Security.Cryptography.ECCurve.Oid, System.Security.Cryptography.Oid.Value, System.writer, and System.Security.Cryptography.EccKeyFormatHelper.WriteSpecifiedECDomain().