Terraria: System.Security.Cryptography.EccKeyFormatHelper.WritePrivateKeyInfoAttributes
WritePrivateKeyInfoAttributes() [1/2]
static AsnWriter System.Security.Cryptography.EccKeyFormatHelper.WritePrivateKeyInfoAttributes (AttributeAsn[] attributes) inline static private
Definition at line 311 of file EccKeyFormatHelper.cs.
    {
        if (attributes == null)
        {
            return null;
        }
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        Asn1Tag value = new Asn1Tag(TagClass.ContextSpecific, 0);
        asnWriter.PushSetOf(value);
        for (int i = 0; i < attributes.Length; i++)
        {
            attributes[i].Encode(asnWriter);
        }
        asnWriter.PopSetOf(value);
        return asnWriter;
    }
References System.Security.Cryptography.Asn1.AttributeAsn.Encode(), System.Formats.Asn1.AsnWriter.PopSetOf(), System.Formats.Asn1.AsnWriter.PushSetOf(), and System.value.
Referenced by System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey(), and System.Security.Cryptography.EccKeyFormatHelper.WritePkcs8PrivateKey().