Terraria: System.Security.Cryptography.EccKeyFormatHelper.FromECPublicKey
FromECPublicKey()
static void System.Security.Cryptography.EccKeyFormatHelper.FromECPublicKey (ReadOnlyMemory< byte > key, in AlgorithmIdentifierAsn algId, out ECParameters ret) inline static package
Definition at line 79 of file EccKeyFormatHelper.cs.
    {
        if (!algId.Parameters.HasValue)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        ReadOnlySpan<byte> span = key.Span;
        if (span.Length == 0)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        if (span[0] != 4)
        {
            throw new CryptographicException(System.SR.Cryptography_NotValidPublicOrPrivateKey);
        }
        if ((span.Length & 1) != 1)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        int num = span.Length / 2;
        ECDomainParameters domainParameters = ECDomainParameters.Decode(algId.Parameters.Value, AsnEncodingRules.DER);
        ret = new ECParameters
        {
            Curve = GetCurve(domainParameters),
            Q =
            {
                X = span.Slice(1, num).ToArray(),
                Y = span.Slice(1 + num).ToArray()
            }
        };
        ret.Validate();
    }
References System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_NotValidPublicOrPrivateKey, System.Security.Cryptography.Asn1.ECDomainParameters.Decode(), System.Security.Cryptography.EccKeyFormatHelper.GetCurve(), System.key, System.ReadOnlySpan< T >.Length, System.Q, System.ReadOnlySpan< T >.Slice(), System.X, and System.Y.
Referenced by System.Security.Cryptography.ECDiffieHellman.ImportSubjectPublicKeyInfo(), and System.Security.Cryptography.ECDsa.ImportSubjectPublicKeyInfo().