Terraria: System.Linq.Expressions.Scope1.Rewrite
Rewrite() [2/2]
override BlockExpression System.Linq.Expressions.Scope1.Rewrite (ReadOnlyCollection< ParameterExpression > variables, Expression[] args) inline package virtual
Reimplemented from System.Linq.Expressions.BlockExpression.
Definition at line 53 of file Scope1.cs.
    {
        if (args == null)
        {
            Expression.ValidateVariables(variables, "variables");
            return new Scope1(variables, _body);
        }
        return new Scope1(ReuseOrValidateVariables(variables), args[0]);
    }
References System.Linq.Expressions.Scope1.Scope1(), System.Linq.Expressions.Scope1._body, System.Linq.Expressions.ScopeExpression.ReuseOrValidateVariables(), and System.Linq.Expressions.Expression< TDelegate >.ValidateVariables().