Terraria: System.Xml.ValidatingReaderNodeData.Clear
Clear()
void System.Xml.ValidatingReaderNodeData.Clear (XmlNodeType nodeType) inline package
Definition at line 149 of file ValidatingReaderNodeData.cs.
    {
        _nodeType = nodeType;
        _localName = string.Empty;
        _prefix = string.Empty;
        _namespaceUri = string.Empty;
        _rawValue = string.Empty;
        if (_attributePSVIInfo != null)
        {
            _attributePSVIInfo.Reset();
        }
        _nameWPrefix = null;
        _lineNo = 0;
        _linePos = 0;
    }
References System.Xml.ValidatingReaderNodeData._attributePSVIInfo, System.Xml.ValidatingReaderNodeData._lineNo, System.Xml.ValidatingReaderNodeData._linePos, System.Xml.ValidatingReaderNodeData._localName, System.Xml.ValidatingReaderNodeData._namespaceUri, System.Xml.ValidatingReaderNodeData._nameWPrefix, System.Xml.ValidatingReaderNodeData._nodeType, System.Xml.ValidatingReaderNodeData._prefix, System.Xml.ValidatingReaderNodeData._rawValue, and System.Xml.AttributePSVIInfo.Reset().
Referenced by System.Xml.XsdCachingReader.AddAttribute(), and System.Xml.XsdCachingReader.AddContent().