Terraria: System.MemoryExtensions.ClampStart
ClampStart()
static int System.MemoryExtensions.ClampStart (ReadOnlySpan< char > span) inline static private
Definition at line 2108 of file MemoryExtensions.cs.
    {
        int i;
        for (i = 0; i < span.Length && char.IsWhiteSpace(span[i]); i++)
        {
        }
        return i;
    }
Referenced by System.MemoryExtensions.Trim(), System.MemoryExtensions.Trim(), System.MemoryExtensions.Trim(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.TrimStart(), System.MemoryExtensions.TrimStart(), System.MemoryExtensions.TrimStart(), System.MemoryExtensions.TrimStart< T >(), System.MemoryExtensions.TrimStart< T >(), System.MemoryExtensions.TrimStart< T >(), System.MemoryExtensions.TrimStart< T >(), System.MemoryExtensions.TrimStart< T >(), System.MemoryExtensions.TrimStart< T >(), System.MemoryExtensions.TrimStart< T >(), and System.MemoryExtensions.TrimStart< T >().