Terraria: System.MemoryExtensions.AsSpan< T >
AsSpan< T >() [10/10]
static Span< T > System.MemoryExtensions.AsSpan< T > (this T?[] array, Range range) inline static
Definition at line 346 of file MemoryExtensions.cs.
    {
        if (array == null)
        {
            Index start = range.Start;
            Index end = range.End;
            if (!start.Equals(Index.Start) || !end.Equals(Index.Start))
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
            }
            return default(Span<T>);
        }
        if (!typeof(T).IsValueType && array.GetType() != typeof(T[]))
        {
            ThrowHelper.ThrowArrayTypeMismatchException();
        }
        var (num, length) = range.GetOffsetAndLength(array.Length);
        return new Span<T>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(array), (nint)(uint)num), length);
    }
References System.array, System.Index.Equals(), System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), System.length, System.start, System.Index.Start, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArrayTypeMismatchException().