Terraria: System.MemoryExtensions.ClampEnd
ClampEnd()
static int System.MemoryExtensions.ClampEnd (ReadOnlySpan< char > span, int start) inline static private
Definition at line 2117 of file MemoryExtensions.cs.
    {
        int num = span.Length - 1;
        while (num >= start && char.IsWhiteSpace(span[num]))
        {
            num--;
        }
        return num - start + 1;
    }
References System.MemoryExtensions.IsWhiteSpace(), and System.start.
Referenced by System.MemoryExtensions.Trim(), System.MemoryExtensions.Trim(), System.MemoryExtensions.Trim(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.Trim< T >(), System.MemoryExtensions.TrimEnd(), System.MemoryExtensions.TrimEnd(), System.MemoryExtensions.TrimEnd(), System.MemoryExtensions.TrimEnd< T >(), System.MemoryExtensions.TrimEnd< T >(), System.MemoryExtensions.TrimEnd< T >(), System.MemoryExtensions.TrimEnd< T >(), System.MemoryExtensions.TrimEnd< T >(), System.MemoryExtensions.TrimEnd< T >(), System.MemoryExtensions.TrimEnd< T >(), and System.MemoryExtensions.TrimEnd< T >().