Terraria: System.MemoryExtensions.Equals
Equals()
static bool System.MemoryExtensions.Equals (this ReadOnlySpan< char > span, ReadOnlySpan< char > other, StringComparison comparisonType) inline static
Definition at line 1369 of file MemoryExtensions.cs.
    {
        string.CheckStringComparison(comparisonType);
        switch (comparisonType)
        {
        case StringComparison.CurrentCulture:
        case StringComparison.CurrentCultureIgnoreCase:
            return CultureInfo.CurrentCulture.CompareInfo.Compare(span, other, string.GetCaseCompareOfComparisonCulture(comparisonType)) == 0;
        case StringComparison.InvariantCulture:
        case StringComparison.InvariantCultureIgnoreCase:
            return CompareInfo.Invariant.Compare(span, other, string.GetCaseCompareOfComparisonCulture(comparisonType)) == 0;
        case StringComparison.Ordinal:
            return span.EqualsOrdinal(other);
        default:
            return span.EqualsOrdinalIgnoreCase(other);
        }
    }
References System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.Globalization.CompareInfo.Invariant, and System.other.
Referenced by System.Runtime.Versioning.FrameworkName.FrameworkName(), System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.AddNewActivitySourceTransform(), System.Type.FilterNameImpl(), System.Diagnostics.NtProcessManager.GetProcessInfos(), System.Diagnostics.NtProcessInfoHelper.GetProcessShortName(), System.Diagnostics.ProcessManager.IsRemoteMachineCore(), System.IO.Directory.Move(), System.IO.PathHelper.Normalize(), and System.IO.PathHelper.TryExpandShortFileName().