Terraria: System.Diagnostics.TraceInternal.TraceEvent
TraceEvent()
static void System.Diagnostics.TraceInternal.TraceEvent (TraceEventType eventType, int id, string format, params object[] args) inline static
Definition at line 339 of file TraceInternal.cs.
    {
        TraceEventCache eventCache = new TraceEventCache();
        if (UseGlobalLock)
        {
            lock (critSec)
            {
                if (args == null)
                {
                    foreach (TraceListener listener in Listeners)
                    {
                        listener.TraceEvent(eventCache, AppName, eventType, id, format);
                        if (AutoFlush)
{
                            listener.Flush();
                        }
                    }
                    return;
                }
                foreach (TraceListener listener2 in Listeners)
                {
                    listener2.TraceEvent(eventCache, AppName, eventType, id, format, args);
                    if (AutoFlush)
                    {
                        listener2.Flush();
                    }
                }
                return;
            }
        }
        if (args == null)
        {
            foreach (TraceListener listener3 in Listeners)
            {
                if (!listener3.IsThreadSafe)
                {
                    lock (listener3)
                    {
                        listener3.TraceEvent(eventCache, AppName, eventType, id, format);
                        if (AutoFlush)
{
                            listener3.Flush();
                        }
                    }
                }
                else
                {
                    listener3.TraceEvent(eventCache, AppName, eventType, id, format);
                    if (AutoFlush)
                    {
                        listener3.Flush();
                    }
                }
            }
            return;
        }
        foreach (TraceListener listener4 in Listeners)
        {
            if (!listener4.IsThreadSafe)
            {
                lock (listener4)
                {
                    listener4.TraceEvent(eventCache, AppName, eventType, id, format, args);
                    if (AutoFlush)
                    {
                        listener4.Flush();
                    }
                }
            }
            else
            {
                listener4.TraceEvent(eventCache, AppName, eventType, id, format, args);
                if (AutoFlush)
                {
                    listener4.Flush();
                }
            }
        }
    }
References System.Diagnostics.TraceInternal.AppName, System.Diagnostics.TraceInternal.AutoFlush, System.Diagnostics.TraceInternal.critSec, System.Diagnostics.TraceListener.Flush(), System.format, System.Diagnostics.TraceListener.IsThreadSafe, System.Diagnostics.TraceInternal.Listeners, System.Diagnostics.TraceListener.TraceEvent(), and System.Diagnostics.TraceInternal.UseGlobalLock.
Referenced by System.Diagnostics.Trace.TraceError(), System.Diagnostics.Trace.TraceError(), System.Diagnostics.Trace.TraceInformation(), System.Diagnostics.Trace.TraceInformation(), System.Diagnostics.Trace.TraceWarning(), and System.Diagnostics.Trace.TraceWarning().