Terraria: System.Diagnostics.TraceInternal.critSec
critSec
readonly object System.Diagnostics.TraceInternal.critSec = new object() static package
Definition at line 57 of file TraceInternal.cs.
Referenced by System.Diagnostics.TraceListenerCollection.Add(), System.Diagnostics.TraceListenerCollection.Add(), System.Diagnostics.TraceInternal.Close(), System.Diagnostics.TraceSource.Close(), System.Diagnostics.TraceInternal.Fail(), System.Diagnostics.TraceInternal.Fail(), System.Diagnostics.TraceInternal.Flush(), System.Diagnostics.TraceSource.Flush(), System.Diagnostics.TraceInternal.InitializeSettings(), System.Diagnostics.TraceListenerCollection.Insert(), System.Diagnostics.TraceListenerCollection.Insert(), System.Diagnostics.TraceInternal.TraceProvider.OnIndentLevelChanged(), System.Diagnostics.TraceInternal.TraceProvider.OnIndentSizeChanged(), System.Diagnostics.TraceInternal.Refresh(), System.Diagnostics.TraceListenerCollection.Remove(), System.Diagnostics.TraceListenerCollection.RemoveAt(), System.Diagnostics.TraceSource.TraceData(), System.Diagnostics.TraceSource.TraceData(), System.Diagnostics.TraceSource.TraceEvent(), System.Diagnostics.TraceInternal.TraceEvent(), System.Diagnostics.TraceSource.TraceEvent(), System.Diagnostics.TraceSource.TraceEvent(), System.Diagnostics.TraceSource.TraceTransfer(), System.Diagnostics.TraceInternal.Write(), System.Diagnostics.TraceInternal.Write(), System.Diagnostics.TraceInternal.Write(), System.Diagnostics.TraceInternal.Write(), System.Diagnostics.TraceInternal.WriteLine(), System.Diagnostics.TraceInternal.WriteLine(), System.Diagnostics.TraceInternal.WriteLine(), and System.Diagnostics.TraceInternal.WriteLine().