Terraria: System.Diagnostics.TraceInternal.WriteLine
WriteLine() [3/4]
static void System.Diagnostics.TraceInternal.WriteLine (string message) inline static
Definition at line 583 of file TraceInternal.cs.
    {
        if (UseGlobalLock)
        {
            lock (critSec)
            {
                foreach (TraceListener listener in Listeners)
                {
                    listener.WriteLine(message);
                    if (AutoFlush)
                    {
                        listener.Flush();
                    }
                }
                return;
            }
        }
        foreach (TraceListener listener2 in Listeners)
        {
            if (!listener2.IsThreadSafe)
            {
                lock (listener2)
                {
                    listener2.WriteLine(message);
                    if (AutoFlush)
                    {
                        listener2.Flush();
                    }
                }
            }
            else
            {
                listener2.WriteLine(message);
                if (AutoFlush)
                {
                    listener2.Flush();
                }
            }
        }
    }
References System.Diagnostics.TraceInternal.AutoFlush, System.Diagnostics.TraceInternal.critSec, System.Diagnostics.TraceListener.Flush(), System.Diagnostics.TraceListener.IsThreadSafe, System.Diagnostics.TraceInternal.Listeners, System.Diagnostics.TraceInternal.UseGlobalLock, and System.Diagnostics.TraceListener.WriteLine().
Referenced by System.Diagnostics.Trace.WriteLine(), System.Diagnostics.Trace.WriteLine(), System.Diagnostics.TraceInternal.TraceProvider.WriteLine(), System.Diagnostics.Trace.WriteLine(), System.Diagnostics.Trace.WriteLine(), System.Diagnostics.TraceInternal.WriteLineIf(), System.Diagnostics.TraceInternal.WriteLineIf(), System.Diagnostics.TraceInternal.WriteLineIf(), and System.Diagnostics.TraceInternal.WriteLineIf().