Terraria: System.Diagnostics.TraceInternal.WriteIf
WriteIf() [3/4]
static void System.Diagnostics.TraceInternal.WriteIf (bool condition, string message) inline static
Definition at line 747 of file TraceInternal.cs.
    {
        if (condition)
        {
            Write(message);
        }
    }
References System.Diagnostics.TraceInternal.Write().
Referenced by System.Diagnostics.Trace.WriteIf(), System.Diagnostics.Trace.WriteIf(), System.Diagnostics.Trace.WriteIf(), and System.Diagnostics.Trace.WriteIf().