Terraria: System.Diagnostics.TraceInternal.Fail
Fail() [1/2]
static void System.Diagnostics.TraceInternal.Fail (string message) inline static
Definition at line 229 of file TraceInternal.cs.
    {
        if (UseGlobalLock)
        {
            lock (critSec)
            {
                foreach (TraceListener listener in Listeners)
                {
                    listener.Fail(message);
                    if (AutoFlush)
                    {
                        listener.Flush();
                    }
                }
                return;
            }
        }
        foreach (TraceListener listener2 in Listeners)
        {
            if (!listener2.IsThreadSafe)
            {
                lock (listener2)
                {
                    listener2.Fail(message);
                    if (AutoFlush)
                    {
                        listener2.Flush();
                    }
                }
            }
            else
            {
                listener2.Fail(message);
                if (AutoFlush)
                {
                    listener2.Flush();
                }
            }
        }
    }
References System.Diagnostics.TraceInternal.AutoFlush, System.Diagnostics.TraceInternal.critSec, System.Diagnostics.TraceListener.Fail(), System.Diagnostics.TraceListener.Flush(), System.Diagnostics.TraceListener.IsThreadSafe, System.Diagnostics.TraceInternal.Listeners, and System.Diagnostics.TraceInternal.UseGlobalLock.
Referenced by System.Diagnostics.TraceInternal.Assert(), System.Diagnostics.TraceInternal.Assert(), System.Diagnostics.TraceInternal.Assert(), System.Diagnostics.TraceInternal.TraceProvider.Fail(), System.Diagnostics.Trace.Fail(), and System.Diagnostics.Trace.Fail().