Terraria: System.Diagnostics.TraceInternal.Write
Write() [3/4]
static void System.Diagnostics.TraceInternal.Write (string message) inline static
Definition at line 419 of file TraceInternal.cs.
    {
        if (UseGlobalLock)
        {
            lock (critSec)
            {
                foreach (TraceListener listener in Listeners)
                {
                    listener.Write(message);
                    if (AutoFlush)
                    {
                        listener.Flush();
                    }
                }
                return;
            }
        }
        foreach (TraceListener listener2 in Listeners)
        {
            if (!listener2.IsThreadSafe)
            {
                lock (listener2)
                {
                    listener2.Write(message);
                    if (AutoFlush)
                    {
                        listener2.Flush();
                    }
                }
            }
            else
            {
                listener2.Write(message);
                if (AutoFlush)
                {
                    listener2.Flush();
                }
            }
        }
    }
References System.Diagnostics.TraceInternal.AutoFlush, System.Diagnostics.TraceInternal.critSec, System.Diagnostics.TraceListener.Flush(), System.Diagnostics.TraceListener.IsThreadSafe, System.Diagnostics.TraceInternal.Listeners, System.Diagnostics.TraceInternal.UseGlobalLock, and System.Diagnostics.TraceListener.Write().
Referenced by System.Diagnostics.Trace.Write(), System.Diagnostics.Trace.Write(), System.Diagnostics.TraceInternal.TraceProvider.Write(), System.Diagnostics.Trace.Write(), System.Diagnostics.Trace.Write(), System.Diagnostics.TraceInternal.WriteIf(), System.Diagnostics.TraceInternal.WriteIf(), System.Diagnostics.TraceInternal.WriteIf(), and System.Diagnostics.TraceInternal.WriteIf().