Terraria: System.Security.Cryptography.ECCng.ImportKeyBlob
ImportKeyBlob() [3/3]
static SafeNCryptKeyHandle System.Security.Cryptography.ECCng.ImportKeyBlob (string blobType, ReadOnlySpan< byte > keyBlob, string curveName, SafeNCryptProviderHandle provider) inline static package
Definition at line 338 of file ECCng.cs.
    {
        global::Interop.NCrypt.ErrorCode errorCode;
        SafeNCryptKeyHandle phKey;
        using (Microsoft.Win32.SafeHandles.SafeUnicodeStringHandle safeUnicodeStringHandle = new Microsoft.Win32.SafeHandles.SafeUnicodeStringHandle(curveName))
        {
            global::Interop.BCrypt.BCryptBufferDesc structure = default(global::Interop.BCrypt.BCryptBufferDesc);
            global::Interop.BCrypt.BCryptBuffer structure2 = default(global::Interop.BCrypt.BCryptBuffer);
            IntPtr intPtr = IntPtr.Zero;
            IntPtr intPtr2 = IntPtr.Zero;
            try
            {
                intPtr = Marshal.AllocHGlobal(Marshal.SizeOf(structure));
                intPtr2 = Marshal.AllocHGlobal(Marshal.SizeOf(structure2));
                structure2.cbBuffer = (curveName.Length + 1) * 2;
                structure2.BufferType = global::Interop.BCrypt.CngBufferDescriptors.NCRYPTBUFFER_ECC_CURVE_NAME;
                structure2.pvBuffer = safeUnicodeStringHandle.DangerousGetHandle();
                Marshal.StructureToPtr(structure2, intPtr2, fDeleteOld: false);
                structure.cBuffers = 1;
                structure.pBuffers = intPtr2;
                structure.ulVersion = 0;
                Marshal.StructureToPtr(structure, intPtr, fDeleteOld: false);
                errorCode = global::Interop.NCrypt.NCryptImportKey(provider, IntPtr.Zero, blobType, intPtr, out phKey, ref MemoryMarshal.GetReference(keyBlob), keyBlob.Length, 0);
            }
            finally
            {
                Marshal.FreeHGlobal(intPtr);
                Marshal.FreeHGlobal(intPtr2);
            }
        }
        if (errorCode != 0)
        {
            Exception ex = errorCode.ToCryptographicException();
            if (errorCode == global::Interop.NCrypt.ErrorCode.NTE_INVALID_PARAMETER)
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, curveName), ex);
            }
            throw ex;
        }
        return phKey;
    }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.SR.Cryptography_CurveNotSupported, System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.SR.Format(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.ReadOnlySpan< T >.Length, System.Runtime.InteropServices.Marshal.SizeOf(), System.Runtime.InteropServices.Marshal.StructureToPtr(), and System.IntPtr.Zero.