Terraria: System.Security.Cryptography.ECCng.ExportPrimeCurveParameters
ExportPrimeCurveParameters() [2/2]
static unsafe void System.Security.Cryptography.ECCng.ExportPrimeCurveParameters (ref ECParameters ecParams, byte[] ecBlob, bool includePrivateParameters) inline static package
Definition at line 186 of file ECCng.cs.
    {
        global::Interop.BCrypt.KeyBlobMagicNumber magic = (global::Interop.BCrypt.KeyBlobMagicNumber)BitConverter.ToInt32(ecBlob, 0);
        CheckMagicValueOfKey(magic, includePrivateParameters);
        if (ecBlob.Length < sizeof(global::Interop.BCrypt.BCRYPT_ECCFULLKEY_BLOB))
        {
            throw global::Interop.NCrypt.ErrorCode.E_FAIL.ToCryptographicException();
        }
        fixed (byte* ptr = &ecBlob[0])
        {
            global::Interop.BCrypt.BCRYPT_ECCFULLKEY_BLOB* ptr2 = (global::Interop.BCrypt.BCRYPT_ECCFULLKEY_BLOB*)ptr;
            ECCurve curve = default(ECCurve);
            curve.CurveType = ConvertToCurveTypeEnum(ptr2->CurveType);
            curve.Hash = GetHashAlgorithmName(ptr2->CurveGenerationAlgId);
            int offset = sizeof(global::Interop.BCrypt.BCRYPT_ECCFULLKEY_BLOB);
            curve.Prime = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbFieldLength);
            curve.A = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbFieldLength);
            curve.B = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbFieldLength);
            curve.G = new ECPoint
            {
                X = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbFieldLength),
                Y = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbFieldLength)
            };
            curve.Order = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbSubgroupOrder);
            curve.Cofactor = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbCofactor);
            curve.Seed = ((ptr2->cbSeed == 0) ? null : global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbSeed));
            ecParams.Q = new ECPoint
            {
                X = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbFieldLength),
                Y = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbFieldLength)
            };
            if (includePrivateParameters)
            {
                ecParams.D = global::Interop.BCrypt.Consume(ecBlob, ref offset, ptr2->cbSubgroupOrder);
            }
            ecParams.Curve = curve;
        }
    }
References System.Security.Cryptography.ECCng.CheckMagicValueOfKey(), System.Security.Cryptography.ECCng.ConvertToCurveTypeEnum(), System.Security.Cryptography.ECCng.GetHashAlgorithmName(), System.offset, System.BitConverter.ToInt32(), System.X, and System.Y.