Terraria: System.Security.Cryptography.ECCng.ExportFullKeyBlob
ExportFullKeyBlob()
static byte[] System.Security.Cryptography.ECCng.ExportFullKeyBlob (CngKey key, bool includePrivateParameters) inline static package
Definition at line 31 of file ECCng.cs.
    {
        CngKeyBlobFormat format = (includePrivateParameters ? CngKeyBlobFormat.EccFullPrivateBlob : CngKeyBlobFormat.EccFullPublicBlob);
        return key.Export(format);
    }
References System.Security.Cryptography.CngKeyBlobFormat.EccFullPublicBlob, System.format, and System.key.
Referenced by System.Security.Cryptography.ECDiffieHellmanCngPublicKey.ExportExplicitParameters(), System.Security.Cryptography.ECDiffieHellmanCng.ExportFullKeyBlob(), System.Security.Cryptography.ECDsaCng.ExportFullKeyBlob(), and System.Security.Cryptography.ECDiffieHellmanCngPublicKey.ExportParameters().