Terraria: System.Security.Cryptography.ECCng.ExportKeyBlob
ExportKeyBlob() [1/2]
static byte[] System.Security.Cryptography.ECCng.ExportKeyBlob (CngKey key, bool includePrivateParameters) inline static package
Definition at line 25 of file ECCng.cs.
    {
        CngKeyBlobFormat format = (includePrivateParameters ? CngKeyBlobFormat.EccPrivateBlob : CngKeyBlobFormat.EccPublicBlob);
        return key.Export(format);
    }
References System.Security.Cryptography.CngKeyBlobFormat.EccPublicBlob, System.format, and System.key.
Referenced by System.Security.Cryptography.ECDiffieHellmanCng.ExportKeyBlob(), System.Security.Cryptography.ECDsaCng.ExportKeyBlob(), System.Security.Cryptography.ECDiffieHellmanCngPublicKey.ExportParameters(), and System.Security.Cryptography.ECDiffieHellmanCngPublicKey.FromKey().