Terraria: Terraria.Chat.ChatHelper.DisplayMessage
DisplayMessage()
static void Terraria.Chat.ChatHelper.DisplayMessage (NetworkText text, Color color, byte messageAuthor) inline static
    {
        string text2 = text.ToString();
        if (messageAuthor < byte.MaxValue)
        {
            Main.player[messageAuthor].chatOverhead.NewMessage(text2, Main.PlayerOverheadChatMessageDisplayTime);
            Main.player[messageAuthor].chatOverhead.color = color;
            text2 = NameTagHandler.GenerateTag(Main.player[messageAuthor].name) + " " + text2;
        }
        if (ShouldCacheMessage())
        {
            CacheMessage(text2, color);
        }
        else
        {
            Main.NewTextMultiline(text2, force: false, color);
        }
    }
References Terraria.Chat.ChatHelper.CacheMessage(), Terraria.Player.chatOverhead, Terraria.Player.OverheadMessage.color, Terraria.GameContent.UI.Chat.NameTagHandler.GenerateTag(), Terraria.Player.name, Terraria.Player.OverheadMessage.NewMessage(), Terraria.Main.NewTextMultiline(), Terraria.Main.player, Terraria.Main.PlayerOverheadChatMessageDisplayTime, Terraria.Chat.ChatHelper.ShouldCacheMessage(), and Terraria.Localization.NetworkText.ToString().
Referenced by Terraria.Chat.ChatHelper.BroadcastChatMessageAs(), Terraria.GameContent.NetModules.NetTextModule.DeserializeAsClient(), Terraria.Chat.ChatHelper.DisplayMessageOnClient(), and Terraria.Chat.ChatHelper.SendChatMessageToClientAs().