Terraria: System.Reflection.Internal.ImmutableByteArrayInterop.DangerousGetUnderlyingArray
DangerousGetUnderlyingArray()
static ? byte[] System.Reflection.Internal.ImmutableByteArrayInterop.DangerousGetUnderlyingArray (ImmutableArray< byte > array) inline static package
Definition at line 27 of file ImmutableByteArrayInterop.cs.
    {
        ByteArrayUnion byteArrayUnion = default(ByteArrayUnion);
        byteArrayUnion.ImmutableArray = array;
        return byteArrayUnion.UnderlyingArray;
    }
References System.array, and System.Reflection.Internal.ImmutableByteArrayInterop.ByteArrayUnion.UnderlyingArray.
Referenced by System.Reflection.Metadata.BlobContentId.FromHash(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), and System.Reflection.Metadata.BlobWriter.WriteBytes().