Terraria: Terraria.Chat.ChatHelper.SendChatMessageToClient
SendChatMessageToClient()
static void Terraria.Chat.ChatHelper.SendChatMessageToClient (NetworkText text, Color color, int playerId) inline static
    {
        SendChatMessageToClientAs(byte.MaxValue, text, color, playerId);
    }
References Terraria.Chat.ChatHelper.SendChatMessageToClientAs().
Referenced by Terraria.GameContent.Events.DD2Event.FailureMessage(), Terraria.MessageBuffer.GetData(), Terraria.NetMessage.greetPlayer(), Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.Chat.Commands.HelpCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.ListPlayersCommand.ProcessIncomingMessage(), and Terraria.Chat.Commands.PartyChatCommand.SendNoTeamError().