Terraria: Terraria.Chat.ChatHelper.SendChatMessageToClientAs
SendChatMessageToClientAs()
static void Terraria.Chat.ChatHelper.SendChatMessageToClientAs (byte messageAuthor, NetworkText text, Color color, int playerId) inline static
Definition at line 33 of file ChatHelper.cs.
    {
        if (Main.dedServ)
        {
            NetPacket packet = NetTextModule.SerializeServerMessage(text, color, messageAuthor);
            NetManager.Instance.SendToClient(packet, playerId);
        }
        if (playerId == Main.myPlayer)
        {
            DisplayMessage(text, color, messageAuthor);
        }
    }
References Terraria.Main.dedServ, Terraria.Chat.ChatHelper.DisplayMessage(), Terraria.Net.NetManager.Instance, Terraria.Main.myPlayer, Terraria.Net.NetManager.SendToClient(), and Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage().
Referenced by Terraria.Chat.Commands.PartyChatCommand.ProcessIncomingMessage(), and Terraria.Chat.ChatHelper.SendChatMessageToClient().