Terraria: UIWorldSelect.UpdateFavoritesCache
UpdateFavoritesCache()
bool UIWorldSelect.UpdateFavoritesCache () inline private
     {
         List<WorldFileData> list = new List<WorldFileData>(Main.WorldList);
         list.Sort(delegate(WorldFileData x, WorldFileData y)
         {
             if (x.IsFavorite && !y.IsFavorite)
             {
                 return -1;
             }
             if (!x.IsFavorite && y.IsFavorite)
             {
                 return 1;
             }
             if (x.Name == null)
             {
                 return 1;
             }
             return (x.Name.CompareTo(y.Name) != 0) ? x.Name.CompareTo(y.Name) : x.GetFileName().CompareTo(y.GetFileName());
         });
         bool flag = false;
         if (!flag && list.Count != favoritesCache.Count)
         {
             flag = true;
         }
         if (!flag)
         {
             for (int i = 0; i < favoritesCache.Count; i++)
             {
                 Tuple<string, bool> tuple = favoritesCache[i];
                 if (!(list[i].Name == tuple.Item1) || list[i].IsFavorite != tuple.Item2)
                 {
                     flag = true;
                     break;
                 }
             }
         }
         if (flag)
         {
             favoritesCache.Clear();
             foreach (WorldFileData item in list)
             {
                 favoritesCache.Add(Tuple.Create(item.Name, item.IsFavorite));
             }
             UpdateWorldsList();
         }
         return flag;
     }
References favoritesCache, FileData.GetFileName(), FileData.IsFavorite, FileData.Name, UpdateWorldsList(), and Main.WorldList.
Referenced by Draw().