Terraria: Terraria.Chat.ChatHelper.BroadcastChatMessage
BroadcastChatMessage()
static void Terraria.Chat.ChatHelper.BroadcastChatMessage (NetworkText text, Color color, int excludedPlayer = -1) inline static
    {
        BroadcastChatMessageAs(byte.MaxValue, text, color, excludedPlayer);
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessageAs().
Referenced by Terraria.WorldGen.BroadcastText(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckOrb(), Terraria.NPC.CheckProgressFrostMoon(), Terraria.NPC.CheckProgressPumpkinMoon(), Terraria.NPC.CountKillForBannersAndDropThem(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_CelebrateBossDeath(), Terraria.MessageBuffer.GetData(), Terraria.Projectile.HandleMovement(), Terraria.Main.InvasionWarning(), Terraria.Player.KillMe(), Terraria.WorldGen.meteor(), Terraria.NPC.NewNPC(), Terraria.NPC.NPCLoot(), Terraria.Chat.Commands.AllDeathCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.AllPVPDeathCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.DeathCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.EmoteCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.PVPDeathCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.RollCommand.ProcessIncomingMessage(), Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), Terraria.WorldGen.SmashAltar(), Terraria.WorldGen.smCallBack(), Terraria.NPC.SpawnBoss(), Terraria.NPC.SpawnOnPlayer(), Terraria.NPC.SpawnSkeletron(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.NPC.SpawnWOF(), Terraria.Main.startDedInputCallBack(), Terraria.Main.startPumpkinMoon(), Terraria.Main.startSnowMoon(), Terraria.NetMessage.SyncOnePlayer(), Terraria.NPC.UnlockOrExchangePet(), Terraria.WorldGen.UnspawnTravelNPC(), Terraria.Main.UpdateSlimeRainWarning(), Terraria.Main.UpdateTime_StartDay(), and Terraria.Main.UpdateTime_StartNight().