Terraria: System.Text.UnicodeUtility.IsInRangeInclusive
IsInRangeInclusive()
static bool System.Text.UnicodeUtility.IsInRangeInclusive (uint value, uint lowerBound, uint upperBound) inline static
Definition at line 61 of file UnicodeUtility.cs.
    {
        return value - lowerBound <= upperBound - lowerBound;
    }
References System.value.
Referenced by System.Text.Rune.DecodeFromUtf8(), System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte(), System.Text.Rune.IsCategoryLetter(), System.Text.Rune.IsCategoryLetterOrDecimalDigit(), System.Text.Rune.IsCategoryNumber(), System.Text.Rune.IsCategoryPunctuation(), System.Text.Rune.IsCategorySeparator(), System.Text.Rune.IsCategorySymbol(), System.Text.Rune.IsDigit(), System.Text.UnicodeUtility.IsHighSurrogateCodePoint(), System.Text.Rune.IsLower(), System.Text.UnicodeUtility.IsLowSurrogateCodePoint(), System.Text.Rune.IsNumber(), System.Text.Unicode.Utf8Utility.IsSecondCharTwoUtf8Bytes(), System.Text.UnicodeUtility.IsSurrogateCodePoint(), System.Text.Rune.IsUpper(), System.Globalization.TextInfo.ToLowerAsciiInvariant(), System.Globalization.TextInfo.ToUpperAsciiInvariant(), System.Text.Unicode.Utf8Utility.TranscodeToUtf16(), System.Text.Unicode.Utf8Utility.UInt32BeginsWithValidUtf8TwoByteSequenceLittleEndian(), and System.Text.Unicode.Utf8Utility.UInt32EndsWithValidUtf8TwoByteSequenceLittleEndian().