Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.InternalSerializeWithSurrogate
InternalSerializeWithSurrogate()
void System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.InternalSerializeWithSurrogate (XmlWriterDelegator xmlWriter, object obj, bool isDeclaredType, bool writeXsiType, int declaredTypeID, RuntimeTypeHandle declaredTypeHandle) inline private inherited
Definition at line 227 of file XmlObjectSerializerWriteContextComplex.cs.
    {
        RuntimeTypeHandle handle = (isDeclaredType ? declaredTypeHandle : obj.GetType().TypeHandle);
        object obj2 = obj;
        int oldObjId = 0;
        Type objType = Type.GetTypeFromHandle(handle);
        Type surrogatedType = GetSurrogatedType(Type.GetTypeFromHandle(declaredTypeHandle));
        declaredTypeHandle = surrogatedType.TypeHandle;
        obj = DataContractSerializer.SurrogateToDataContractType(_serializationSurrogateProvider, obj, surrogatedType, ref objType);
        handle = objType.TypeHandle;
        if (obj2 != obj)
        {
            oldObjId = base.SerializedObjects.ReassignId(0, obj2, obj);
        }
        if (writeXsiType)
        {
            surrogatedType = Globals.TypeOfObject;
            SerializeWithXsiType(xmlWriter, obj, handle, objType, -1, surrogatedType.TypeHandle, surrogatedType);
        }
        else if (declaredTypeHandle.Equals(handle))
        {
            DataContract dataContract = GetDataContract(handle, objType);
            SerializeWithoutXsiType(dataContract, xmlWriter, obj, declaredTypeHandle);
        }
        else
        {
            SerializeWithXsiType(xmlWriter, obj, handle, objType, -1, declaredTypeHandle, surrogatedType);
        }
        if (obj2 != obj)
        {
            base.SerializedObjects.ReassignId(oldObjId, obj, obj2);
        }
    }
References System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex._serializationSurrogateProvider, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerContext.GetDataContract(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.GetSurrogatedType(), System.Type.GetTypeFromHandle(), System.handle, System.obj, System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(), System.Runtime.Serialization.DataContractSerializer.SurrogateToDataContractType(), and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.InternalSerialize().