Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.CheckIfTypeSerializable
CheckIfTypeSerializable()
override void System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.CheckIfTypeSerializable (Type memberType, bool isMemberTypeSerializable) inline package virtual inherited
Reimplemented from System.Runtime.Serialization.XmlObjectSerializerContext.
Definition at line 190 of file XmlObjectSerializerWriteContextComplex.cs.
    {
        if (_serializationSurrogateProvider != null)
        {
            while (memberType.IsArray)
            {
                memberType = memberType.GetElementType();
            }
            memberType = DataContractSurrogateCaller.GetDataContractType(_serializationSurrogateProvider, memberType);
            if (!DataContract.IsTypeSerializable(memberType))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.TypeNotSerializable, memberType)));
            }
        }
        else
        {
            base.CheckIfTypeSerializable(memberType, isMemberTypeSerializable);
        }
    }
References System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex._serializationSurrogateProvider, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContractSurrogateCaller.GetDataContractType(), System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.TypeNotSerializable.