Terraria: System.Text.UnicodeUtility.GetUtf16SurrogatesFromSupplementaryPlaneScalar
GetUtf16SurrogatesFromSupplementaryPlaneScalar()
static void System.Text.UnicodeUtility.GetUtf16SurrogatesFromSupplementaryPlaneScalar (uint value, out char highSurrogateCodePoint, out char lowSurrogateCodePoint) inline static
Definition at line 26 of file UnicodeUtility.cs.
    {
        highSurrogateCodePoint = (char)(value + 56557568 >> 10);
        lowSurrogateCodePoint = (char)((value & 0x3FF) + 56320);
    }
References System.value.
Referenced by System.Globalization.SurrogateCasing.ToLower(), System.Text.Rune.ToString(), System.Globalization.SurrogateCasing.ToUpper(), and System.Text.Rune.TryEncodeToUtf16().