Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.OnHandleReference
OnHandleReference()
override bool System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.OnHandleReference (XmlWriterDelegator xmlWriter, object obj, bool canContainCyclicReference) inline package virtual inherited
Reimplemented from System.Runtime.Serialization.XmlObjectSerializerWriteContext.
Definition at line 161 of file XmlObjectSerializerWriteContextComplex.cs.
    {
        if (preserveObjectReferences && !IsGetOnlyCollection)
        {
            bool newId = true;
            int id = base.SerializedObjects.GetId(obj, ref newId);
            if (newId)
            {
                xmlWriter.WriteAttributeInt("z", DictionaryGlobals.IdLocalName, DictionaryGlobals.SerializationNamespace, id);
            }
            else
            {
                xmlWriter.WriteAttributeInt("z", DictionaryGlobals.RefLocalName, DictionaryGlobals.SerializationNamespace, id);
                xmlWriter.WriteAttributeBool("i", DictionaryGlobals.XsiNilLocalName, DictionaryGlobals.SchemaInstanceNamespace, value: true);
            }
            return !newId;
        }
        return base.OnHandleReference(xmlWriter, obj, canContainCyclicReference);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DictionaryGlobals.IdLocalName, System.Runtime.Serialization.XmlObjectSerializerWriteContext.IsGetOnlyCollection, System.obj, System.Runtime.Serialization.XmlObjectSerializerWriteContext.preserveObjectReferences, System.Runtime.Serialization.DictionaryGlobals.RefLocalName, System.Runtime.Serialization.DictionaryGlobals.SchemaInstanceNamespace, System.Runtime.Serialization.DictionaryGlobals.SerializationNamespace, System.value, and System.Runtime.Serialization.DictionaryGlobals.XsiNilLocalName.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteAnyType(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteBase64(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteBase64(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteQName(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteQName(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteString(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteString(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteUri(), and System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.WriteUri().