Terraria: System.Net.Mime.QuotedPrintableStream.WriteAsyncResult.CompleteWrite
CompleteWrite()
void System.Net.Mime.QuotedPrintableStream.WriteAsyncResult.CompleteWrite (IAsyncResult result) inline private
Definition at line 39 of file QuotedPrintableStream.cs.
        {
            _parent.BaseStream.EndWrite(result);
            _parent.WriteState.BufferFlushed();
        }
References System.Net.Mime.QuotedPrintableStream.WriteAsyncResult._parent, System.Net.DelegatedStream.BaseStream, System.Net.Mime.WriteStateInfoBase.BufferFlushed(), System.IO.Stream.EndWrite(), and System.Net.Mime.QuotedPrintableStream.WriteState.
Referenced by System.Net.Mime.QuotedPrintableStream.WriteAsyncResult.OnWrite(), and System.Net.Mime.QuotedPrintableStream.WriteAsyncResult.Write().