Terraria: System.Text.UnicodeUtility.GetScalarFromUtf16SurrogatePair
GetScalarFromUtf16SurrogatePair()
static uint System.Text.UnicodeUtility.GetScalarFromUtf16SurrogatePair (uint highSurrogateCodePoint, uint lowSurrogateCodePoint) inline static
Definition at line 12 of file UnicodeUtility.cs.
    {
        return (highSurrogateCodePoint << 10) + lowSurrogateCodePoint - 56613888;
    }
Referenced by System.Text.Rune.ChangeCaseCultureAware(), System.Globalization.OrdinalCasing.CompareStringIgnoreCase(), System.Globalization.InvariantModeCasing.GetScalar(), System.Text.Rune.ReadFirstRuneFromUtf16Buffer(), System.Text.Rune.ReadRuneFromString(), System.Globalization.SurrogateCasing.ToLower(), and System.Globalization.SurrogateCasing.ToUpper().