Terraria: System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.GetSurrogatedType
GetSurrogatedType()
override Type System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.GetSurrogatedType (Type type) inline package virtual inherited
Reimplemented from System.Runtime.Serialization.XmlObjectSerializerContext.
Definition at line 211 of file XmlObjectSerializerWriteContextComplex.cs.
    {
        if (_serializationSurrogateProvider == null)
        {
            return base.GetSurrogatedType(type);
        }
        type = DataContract.UnwrapNullableType(type);
        Type surrogatedType = DataContractSerializer.GetSurrogatedType(_serializationSurrogateProvider, type);
        if (IsGetOnlyCollection && surrogatedType != type)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.SurrogatesWithGetOnlyCollectionsNotSupportedSerDeser, DataContract.GetClrTypeFullName(type))));
        }
        return surrogatedType;
    }
References System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex._serializationSurrogateProvider, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContractSerializer.GetSurrogatedType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.IsGetOnlyCollection, System.SR.SurrogatesWithGetOnlyCollectionsNotSupportedSerDeser, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, and System.Runtime.Serialization.DataContract.UnwrapNullableType().
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.InternalSerializeWithSurrogate().