Terraria: System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.WriteTypeCode
WriteTypeCode()
void System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.WriteTypeCode (SerializationTypeCode value) inline private
Definition at line 12 of file CustomAttributeElementTypeEncoder.cs.
    {
        Builder.WriteByte((byte)value);
    }
References System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Builder, System.value, and System.Reflection.Metadata.BlobBuilder.WriteByte().
Referenced by System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Boolean(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Byte(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Char(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Double(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Enum(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Int16(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Int32(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Int64(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.PrimitiveType(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.SByte(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.Single(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.String(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.SystemType(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.UInt16(), System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.UInt32(), and System.Reflection.Metadata.Ecma335.CustomAttributeElementTypeEncoder.UInt64().