Terraria: Segments.NPCSegment.Draw
Draw()
override void Segments.NPCSegment.Draw (ref GameAnimationSegment info) inline virtual
Implements Segments.AnimationSegmentWithActions< NPC >.
         {
             if ((float)info.TimeInAnimation > (float)_targetTime + base.DedicatedTimeNeeded || info.TimeInAnimation < _targetTime)
             {
                 return;
             }
             ResetNPCAnimation(ref info);
             float localTimeForObject = info.TimeInAnimation - _targetTime;
             ProcessActions(_npc, localTimeForObject);
             if (_npc.alpha < 255)
             {
                 _npc.FindFrame();
                 if (TownNPCProfiles.Instance.GetProfile(_npc.type, out var profile))
                 {
                     TextureAssets.Npc[_npc.type] = profile.GetTextureNPCShouldUse(_npc);
                 }
                 _npc.Opacity *= info.DisplayOpacity;
                 Main.instance.DrawNPCDirect(info.SpriteBatch, _npc, _npc.behindTiles, Vector2.Zero);
             }
         }
References Segments.NPCSegment._npc, Segments.AnimationSegmentWithActions< NPC >._targetTime, NPC.alpha, NPC.behindTiles, Main.DrawNPCDirect(), NPC.FindFrame(), TownNPCProfiles.GetProfile(), TownNPCProfiles.Instance, Main.instance, TextureAssets.Npc, NPC.Opacity, Segments.AnimationSegmentWithActions< NPC >.ProcessActions(), Segments.NPCSegment.ResetNPCAnimation(), and NPC.type.