Terraria: System.Text.RegularExpressions.Regex.Init
Init()
void System.Text.RegularExpressions.Regex.Init (string pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture) inline private
Definition at line 136 of file Regex.cs.
    {
        ValidatePattern(pattern);
        ValidateOptions(options);
        ValidateMatchTimeout(matchTimeout);
        this.pattern = pattern;
        roptions = options;
        internalMatchTimeout = matchTimeout;
        RegexTree regexTree = RegexParser.Parse(pattern, roptions, culture ?? (((options & RegexOptions.CultureInvariant) != 0) ? CultureInfo.InvariantCulture : CultureInfo.CurrentCulture));
        capnames = regexTree.CapNames;
        capslist = regexTree.CapsList;
        _code = RegexWriter.Write(regexTree);
        caps = _code.Caps;
        capsize = _code.CapSize;
        InitializeReferences();
    }
References System.Text.RegularExpressions.Regex._code, System.Text.RegularExpressions.Regex.capnames, System.Text.RegularExpressions.Regex.caps, System.Text.RegularExpressions.RegexCode.Caps, System.Text.RegularExpressions.Regex.capsize, System.Text.RegularExpressions.RegexCode.CapSize, System.Text.RegularExpressions.Regex.capslist, System.culture, System.Globalization.CultureInfo.CurrentCulture, System.Runtime.Serialization.Dictionary, System.Text.RegularExpressions.Regex.InitializeReferences(), System.Text.RegularExpressions.Regex.internalMatchTimeout, System.Globalization.CultureInfo.InvariantCulture, System.Text.RegularExpressions.matchTimeout, System.Text.RegularExpressions.options, System.Text.RegularExpressions.RegexParser.Parse(), System.Text.RegularExpressions.Regex.pattern, System.Text.RegularExpressions.Regex.roptions, System.Text.RegularExpressions.Regex.ValidateMatchTimeout(), System.Text.RegularExpressions.Regex.ValidateOptions(), System.Text.RegularExpressions.Regex.ValidatePattern(), and System.Text.RegularExpressions.RegexWriter.Write().
Referenced by System.Text.RegularExpressions.Regex.Regex(), and System.Text.RegularExpressions.Regex.Regex().