Terraria: System.Text.RegularExpressions.Regex.IsMatch
IsMatch() [3/5]
static bool System.Text.RegularExpressions.Regex.IsMatch (string input, string pattern) inline static
Definition at line 406 of file Regex.cs.
    {
        return RegexCache.GetOrAdd(pattern).IsMatch(input);
    }
References System.Text.RegularExpressions.RegexCache.GetOrAdd(), System.Text.RegularExpressions.input, and System.Text.RegularExpressions.Regex.pattern.
Referenced by System.Data.Common.DbCommandBuilder.ParameterNames.ParameterNames(), System.Runtime.Serialization.DataContract.IsAssemblyFriendOfSerialization(), and System.Data.Common.DbCommandBuilder.ParameterNames.SetAndValidateNamePrefixes().