Terraria: System.Text.RegularExpressions.Regex.Run
Run()
Match System.Text.RegularExpressions.Regex.Run (bool quick, int prevlen, string input, int beginning, int length, int startat) inline package
Definition at line 337 of file Regex.cs.
    {
        if ((uint)startat > (uint)input.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startat, ExceptionResource.BeginIndexNotNegative);
        }
        if ((uint)length > (uint)input.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length, ExceptionResource.LengthNotNegative);
        }
        RegexRunner regexRunner = RentRunner();
        try
        {
            return regexRunner.Scan(this, input, beginning, beginning + length, startat, prevlen, quick, internalMatchTimeout);
        }
        finally
        {
            ReturnRunner(regexRunner);
        }
    }
References System.Text.RegularExpressions.input, System.Text.RegularExpressions.Regex.internalMatchTimeout, System.Text.RegularExpressions.length, System.Text.RegularExpressions.Regex.RentRunner(), System.Text.RegularExpressions.Regex.ReturnRunner(), System.Text.RegularExpressions.startat, and System.Text.RegularExpressions.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Text.RegularExpressions.MatchCollection.GetMatch(), and System.Text.RegularExpressions.Match.NextMatch().