Terraria: System.Text.RegularExpressions.Regex.RentRunner
RentRunner()
RegexRunner System.Text.RegularExpressions.Regex.RentRunner () inline private
Definition at line 372 of file Regex.cs.
    {
        RegexRunner regexRunner = Interlocked.Exchange(ref _runner, null);
        if (regexRunner == null)
        {
            if (factory == null)
            {
                return new RegexInterpreter(_code, UseOptionInvariant() ? CultureInfo.InvariantCulture : CultureInfo.CurrentCulture);
            }
            regexRunner = factory.CreateInstance();
        }
        return regexRunner;
    }
References System.Text.RegularExpressions.Regex._code, System.Text.RegularExpressions.Regex._runner, System.Text.RegularExpressions.RegexRunnerFactory.CreateInstance(), System.Globalization.CultureInfo.CurrentCulture, System.Runtime.Serialization.Dictionary, System.Threading.Interlocked.Exchange(), System.Text.RegularExpressions.Regex.factory, System.Globalization.CultureInfo.InvariantCulture, and System.Text.RegularExpressions.Regex.UseOptionInvariant().
Referenced by System.Text.RegularExpressions.Regex.Run(), and System.Text.RegularExpressions.Regex.Run< TState >().