Terraria: System.Text.RegularExpressions.Regex.s_defaultMatchTimeout
s_defaultMatchTimeout
readonly TimeSpan System.Text.RegularExpressions.Regex.s_defaultMatchTimeout = InitDefaultMatchTimeout() static package
Definition at line 39 of file Regex.cs.
Referenced by System.Text.RegularExpressions.Regex.Regex(), System.Text.RegularExpressions.Regex.Regex(), System.Text.RegularExpressions.RegexCache.GetOrAdd(), System.Text.RegularExpressions.Regex.IsMatch(), System.Text.RegularExpressions.Regex.Match(), System.Text.RegularExpressions.Regex.Matches(), System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.Regex.Replace(), and System.Text.RegularExpressions.Regex.Split().