Terraria: System.Data.LookupNode.Bind
Bind()
override void System.Data.LookupNode.Bind (DataTable table, List< DataColumn > list) inline package
Definition at line 23 of file LookupNode.cs.
    {
        BindTable(table);
        _column = null;
        _relation = null;
        if (table == null)
        {
            throw ExprException.ExpressionUnbound(ToString());
        }
        DataRelationCollection parentRelations = table.ParentRelations;
        if (_relationName == null)
        {
            if (parentRelations.Count > 1)
            {
                throw ExprException.UnresolvedRelation(table.TableName, ToString());
            }
            _relation = parentRelations[0];
        }
        else
        {
            _relation = parentRelations[_relationName];
        }
        if (_relation == null)
        {
            throw ExprException.BindFailure(_relationName);
        }
        DataTable parentTable = _relation.ParentTable;
        _column = parentTable.Columns[_columnName];
        if (_column == null)
        {
            throw ExprException.UnboundName(_columnName);
        }
        int i;
        for (i = 0; i < list.Count; i++)
        {
            DataColumn dataColumn = list[i];
            if (_column == dataColumn)
            {
                break;
            }
        }
        if (i >= list.Count)
        {
            list.Add(_column);
        }
        AggregateNode.Bind(_relation, list);
    }
References System.Data.LookupNode._column, System.Data.LookupNode._columnName, System.Data.LookupNode._relation, System.Data.LookupNode._relationName, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.AggregateNode.Bind(), System.Data.ExprException.BindFailure(), System.Data.ExpressionNode.BindTable(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Data.ExprException.ExpressionUnbound(), System.list, System.Data.DataTable.ParentRelations, System.Data.DataRelation.ParentTable, System.Data.ExpressionNode.table, System.Data.DataTable.TableName, System.ToString, System.Data.ExprException.UnboundName(), and System.Data.ExprException.UnresolvedRelation().