Terraria: TriggersSet.GetNavigatorDirections
GetNavigatorDirections()
Vector2 TriggersSet.GetNavigatorDirections () inline
     {
         bool flag = Main.gameMenu || Main.ingameOptionsWindow || Main.editChest || Main.editSign || ((Main.playerInventory || Main.LocalPlayer.talkNPC != -1) && PlayerInput.CurrentProfile.UsingDpadMovekeys());
         bool value = Up || (flag && MenuUp);
         bool value2 = Right || (flag && MenuRight);
         bool value3 = Down || (flag && MenuDown);
         bool value4 = Left || (flag && MenuLeft);
         return new Vector2(value2.ToInt() - value4.ToInt(), value3.ToInt() - value.ToInt());
     }
References PlayerInput.CurrentProfile, Down, Main.editChest, Main.editSign, Main.gameMenu, Main.ingameOptionsWindow, Left, Main.LocalPlayer, MenuDown, MenuLeft, MenuRight, MenuUp, Main.playerInventory, Right, Player.talkNPC, Up, and PlayerInputProfile.UsingDpadMovekeys().
Referenced by UILinkPointNavigator.ForceMovementCooldown(), SmartCursorHelper.Step_Pickaxe_MineSolids(), and UILinkPointNavigator.Update().