Terraria: System.ComponentModel.DataAnnotations.MaxLengthAttribute.IsValid
IsValid() [1/2]
override bool System.ComponentModel.DataAnnotations.MaxLengthAttribute.IsValid (object? value) inline virtual
Reimplemented from System.ComponentModel.DataAnnotations.ValidationAttribute.
Definition at line 28 of file MaxLengthAttribute.cs.
    {
        EnsureLegalLengths();
        if (value == null)
        {
            return true;
        }
        int num;
        if (value is string text)
        {
            num = text.Length;
        }
        else
        {
            if (!CountPropertyHelper.TryGetCount(value, out var count))
            {
                throw new InvalidCastException(System.SR.Format(System.SR.LengthAttribute_InvalidValueType, value.GetType()));
            }
            num = count;
        }
        if (-1 != Length)
        {
            return num <= Length;
        }
        return true;
    }
References System.count, System.ComponentModel.DataAnnotations.MaxLengthAttribute.EnsureLegalLengths(), System.SR.Format(), System.ComponentModel.DataAnnotations.MaxLengthAttribute.Length, System.SR.LengthAttribute_InvalidValueType, System.text, System.ComponentModel.DataAnnotations.CountPropertyHelper.TryGetCount(), and System.value.