Terraria: LaunchInitializer.LoadSharedParameters
LoadSharedParameters()
static void LaunchInitializer.LoadSharedParameters (Main game) inline static private
     {
         string path;
         if ((path = TryParameter("-loadlib")) != null)
         {
             game.loadLib(path);
         }
         string s;
         if ((s = TryParameter("-p", "-port")) != null && int.TryParse(s, out var result))
         {
             Netplay.ListenPort = result;
         }
     }
References Netplay.ListenPort, Main.loadLib(), and TryParameter().
Referenced by LoadParameters().