Terraria: LaunchInitializer.LoadParameters
LoadParameters()
static void LaunchInitializer.LoadParameters (Main game) inline static
     {
         LoadSharedParameters(game);
         if (Main.dedServ)
         {
             LoadServerParameters(game);
         }
         LoadClientParameters(game);
     }
References Main.dedServ, LoadClientParameters(), LoadServerParameters(), and LoadSharedParameters().
Referenced by Program.RunGame().