Terraria: nativefiledialog.UTF8_ToManaged
UTF8_ToManaged()
static unsafe string nativefiledialog.UTF8_ToManaged (IntPtr s, bool freePtr = false) inline static private
     {
         if (s == IntPtr.Zero)
         {
             return null;
         }
         byte* ptr;
         for (ptr = (byte*)(void*)s; *ptr != 0; ptr++)
         {
         }
         int num = (int)(ptr - (byte*)(void*)s);
         if (num == 0)
         {
             return string.Empty;
         }
         char* ptr2 = stackalloc char[num];
         int chars = Encoding.UTF8.GetChars((byte*)(void*)s, num, ptr2, num);
         string result = new string(ptr2, 0, chars);
         if (freePtr)
         {
             free(s);
         }
         return result;
     }
References free().
Referenced by NFD_GetError(), NFD_OpenDialog(), NFD_PathSet_GetPath(), NFD_PickFolder(), and NFD_SaveDialog().