Terraria: MinimapFrameTemplate.CreateInstance
CreateInstance()
MinimapFrame MinimapFrameTemplate.CreateInstance (AssetRequestMode mode) inline
     {
         //IL_0015: Unknown result type (might be due to invalid IL or missing references)
         //IL_0054: Unknown result type (might be due to invalid IL or missing references)
         //IL_007b: Unknown result type (might be due to invalid IL or missing references)
         //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
         MinimapFrame minimapFrame = new MinimapFrame(LoadAsset<Texture2D>("Images\\UI\\Minimap\\" + name + "\\MinimapFrame", mode), frameOffset);
         minimapFrame.NameKey = name;
         minimapFrame.ConfigKey = name;
         minimapFrame.SetResetButton(LoadAsset<Texture2D>("Images\\UI\\Minimap\\" + name + "\\MinimapButton_Reset", mode), resetPosition);
         minimapFrame.SetZoomOutButton(LoadAsset<Texture2D>("Images\\UI\\Minimap\\" + name + "\\MinimapButton_ZoomOut", mode), zoomOutPosition);
         minimapFrame.SetZoomInButton(LoadAsset<Texture2D>("Images\\UI\\Minimap\\" + name + "\\MinimapButton_ZoomIn", mode), zoomInPosition);
         return minimapFrame;
     }
References MinimapFrame.ConfigKey, frameOffset, name, MinimapFrame.NameKey, resetPosition, MinimapFrame.SetResetButton(), MinimapFrame.SetZoomInButton(), MinimapFrame.SetZoomOutButton(), zoomInPosition, and zoomOutPosition.
Referenced by MinimapFrameManager.CreateAndAdd().