Terraria: System.Reflection.Emit.SignatureHelper.AddElementType
AddElementType()
void System.Reflection.Emit.SignatureHelper.AddElementType (CorElementType cvt) inline private
Definition at line 440 of file SignatureHelper.cs.
    {
        if (m_currSig + 1 > m_signature.Length)
        {
            m_signature = ExpandArray(m_signature);
        }
        m_signature[m_currSig++] = (byte)cvt;
    }
References System.Reflection.Emit.SignatureHelper.ExpandArray(), System.Reflection.Emit.SignatureHelper.m_currSig, and System.Reflection.Emit.SignatureHelper.m_signature.
Referenced by System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(), System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(), System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker(), System.Reflection.Emit.SignatureHelper.AddSentinel(), System.Reflection.Emit.SignatureHelper.GetSignature(), System.Reflection.Emit.SignatureHelper.InternalAddRuntimeType(), and System.Reflection.Emit.SignatureHelper.InternalAddTypeToken().