Terraria: System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper
AddOneArgTypeHelper() [1/3]
void System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper (Type argument, bool pinned) inline private
Definition at line 230 of file SignatureHelper.cs.
    {
        if (pinned)
        {
            AddElementType(CorElementType.ELEMENT_TYPE_PINNED);
        }
        AddOneArgTypeHelper(argument);
    }
References System.Reflection.Emit.SignatureHelper.AddElementType(), and System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper().
Referenced by System.Reflection.Emit.SignatureHelper.SignatureHelper(), System.Reflection.Emit.SignatureHelper.SignatureHelper(), System.Reflection.Emit.SignatureHelper.AddArgument(), System.Reflection.Emit.SignatureHelper.AddArgument(), System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(), System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(), and System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker().