Terraria: System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper
AddOneArgTypeHelper() [3/3]
void System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper (Type clsArgument, Type[] requiredCustomModifiers, Type[] optionalCustomModifiers) inline private
Definition at line 239 of file SignatureHelper.cs.
    {
        if (optionalCustomModifiers != null)
        {
            foreach (Type type in optionalCustomModifiers)
            {
                if (type == null)
                {
                    throw new ArgumentNullException("optionalCustomModifiers");
                }
                if (type.HasElementType)
                {
                    throw new ArgumentException(SR.Argument_ArraysInvalid, "optionalCustomModifiers");
                }
                if (type.ContainsGenericParameters)
                {
                    throw new ArgumentException(SR.Argument_GenericsInvalid, "optionalCustomModifiers");
                }
                AddElementType(CorElementType.ELEMENT_TYPE_CMOD_OPT);
                int typeToken = m_module.GetTypeToken(type);
                AddToken(typeToken);
            }
        }
        if (requiredCustomModifiers != null)
        {
            foreach (Type type2 in requiredCustomModifiers)
            {
                if (type2 == null)
                {
                    throw new ArgumentNullException("requiredCustomModifiers");
                }
                if (type2.HasElementType)
                {
                    throw new ArgumentException(SR.Argument_ArraysInvalid, "requiredCustomModifiers");
                }
                if (type2.ContainsGenericParameters)
                {
                    throw new ArgumentException(SR.Argument_GenericsInvalid, "requiredCustomModifiers");
                }
                AddElementType(CorElementType.ELEMENT_TYPE_CMOD_REQD);
                int typeToken2 = m_module.GetTypeToken(type2);
                AddToken(typeToken2);
            }
        }
        AddOneArgTypeHelper(clsArgument);
    }
References System.Reflection.Emit.SignatureHelper.AddElementType(), System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(), System.Reflection.Emit.SignatureHelper.AddToken(), System.SR.Argument_ArraysInvalid, System.SR.Argument_GenericsInvalid, System.Type.ContainsGenericParameters, System.Reflection.Emit.ModuleBuilder.GetTypeToken(), System.Type.HasElementType, System.Reflection.Emit.SignatureHelper.m_module, and System.type.