Terraria: System.Security.Cryptography.CryptographicOperations.ZeroMemory
ZeroMemory()
static void System.Security.Cryptography.CryptographicOperations.ZeroMemory (Span< byte > buffer) inline static
Definition at line 24 of file CryptographicOperations.cs.
    {
        buffer.Clear();
    }
References System.buffer.
Referenced by System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes(), System.Security.Cryptography.Rfc2898DeriveBytes.Rfc2898DeriveBytes(), System.Security.Cryptography.RSA.ClearPrivateParameters(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.ComputeHashAsyncCore(), System.Security.Cryptography.CryptoStream.CopyTo(), System.Security.Cryptography.CryptoStream.CopyToAsyncInternal(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.AeadCommon.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.SymmetricAlgorithm.DecryptCbc(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.Derive(), System.Security.Cryptography.FromBase64Transform.Dispose(), System.Security.Cryptography.PasswordBasedEncryption.Encrypt(), System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(), System.Security.Cryptography.RSACng.EncryptOrDecrypt(), System.Security.Cryptography.RSAImplementation.RSACng.EncryptOrDecrypt(), System.Security.Cryptography.RSACng.EncryptOrDecrypt(), System.Security.Cryptography.ECDiffieHellman.ExportECPrivateKey(), System.Security.Cryptography.ECDsa.ExportECPrivateKey(), System.Security.Cryptography.CngKeyLite.ExportKeyBlob(), System.Security.Cryptography.CngKeyLite.ExportPkcs8KeyBlob(), Internal.Cryptography.Pbkdf2Implementation.FillKeyDerivation(), System.Security.Cryptography.ECDiffieHellman.ImportECPrivateKey(), System.Security.Cryptography.ECDsa.ImportECPrivateKey(), System.Security.Cryptography.DSA.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellman.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.DSA.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellman.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.DSA.ImportPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellman.ImportPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.ImportPkcs8PrivateKey(), System.Security.Cryptography.PasswordBasedEncryption.OpenPbkdf2(), System.Security.Cryptography.RsaPaddingProcessor.PadOaep(), System.Security.Cryptography.PasswordBasedEncryption.Pbes1Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Pbkdf1(), System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2Core(), System.Security.Cryptography.PasswordBasedEncryption.Pkcs12PbeDecrypt(), System.Security.Cryptography.PasswordBasedEncryption.Pkcs12PbeDecrypt(), System.Security.Cryptography.CryptoStream.ReadAsyncCore(), System.Security.Cryptography.KeyFormatHelper.ReadEncryptedPkcs8< TRet >(), System.Security.Cryptography.CryptoPool.Return(), System.Security.Cryptography.ECDsa.SignDataCore(), System.Security.Cryptography.ECDsa.SignHashCore(), Internal.Cryptography.UniversalCryptoDecryptor.TransformOneShot(), System.Security.Cryptography.RSAImplementation.RSACng.TryEncryptOrDecrypt(), System.Security.Cryptography.RSACng.TryEncryptOrDecrypt(), System.Security.Cryptography.ECDiffieHellman.TryExportECPrivateKey(), System.Security.Cryptography.ECDsa.TryExportECPrivateKey(), System.Security.Cryptography.ECDiffieHellman.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellman.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.TryExportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDiffieHellman.TryExportPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.TryExportPkcs8PrivateKey(), System.Security.Cryptography.CryptoStream.WriteAsyncCore(), System.Security.Cryptography.KeyFormatHelper.WriteEncryptedPkcs8(), and System.Security.Cryptography.DSA.WritePkcs8().