Terraria: System.Reflection.Emit.SignatureHelper.AddData
AddData()
void System.Reflection.Emit.SignatureHelper.AddData (int data) inline private
Definition at line 414 of file SignatureHelper.cs.
    {
        if (m_currSig + 4 > m_signature.Length)
        {
            m_signature = ExpandArray(m_signature);
        }
        if (data <= 127)
        {
            m_signature[m_currSig++] = (byte)data;
            return;
        }
        if (data <= 16383)
        {
            BinaryPrimitives.WriteInt16BigEndian(m_signature.AsSpan(m_currSig), (short)(data | 0x8000));
            m_currSig += 2;
            return;
        }
        if (data <= 536870911)
        {
            BinaryPrimitives.WriteInt32BigEndian(m_signature.AsSpan(m_currSig), (int)(data | 0xC0000000u));
            m_currSig += 4;
            return;
        }
        throw new ArgumentException(SR.Argument_LargeInteger);
    }
References System.SR.Argument_LargeInteger, System.Reflection.Emit.SignatureHelper.ExpandArray(), System.Reflection.Emit.SignatureHelper.m_currSig, System.Reflection.Emit.SignatureHelper.m_signature, System.Buffers.Binary.BinaryPrimitives.WriteInt16BigEndian(), and System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian().
Referenced by System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker(), System.Reflection.Emit.SignatureHelper.AddToken(), System.Reflection.Emit.SignatureHelper.GetMethodSpecSigHelper(), System.Reflection.Emit.SignatureHelper.Init(), and System.Reflection.Emit.SignatureHelper.SetNumberOfSignatureElements().