Terraria: System.Reflection.Emit.SignatureHelper.InternalAddRuntimeType
InternalAddRuntimeType()
unsafe void System.Reflection.Emit.SignatureHelper.InternalAddRuntimeType (Type type) inline private
Definition at line 476 of file SignatureHelper.cs.
    {
        AddElementType(CorElementType.ELEMENT_TYPE_INTERNAL);
        IntPtr value = type.GetTypeHandleInternal().Value;
        if (m_currSig + sizeof(void*) > m_signature.Length)
        {
            m_signature = ExpandArray(m_signature);
        }
        byte* ptr = (byte*)(&value);
        for (int i = 0; i < sizeof(void*); i++)
        {
            m_signature[m_currSig++] = ptr[i];
        }
    }
References System.Reflection.Emit.SignatureHelper.AddElementType(), System.Reflection.Emit.SignatureHelper.ExpandArray(), System.Reflection.Emit.SignatureHelper.m_currSig, System.Reflection.Emit.SignatureHelper.m_signature, System.type, and System.value.
Referenced by System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker().