Terraria: System.Reflection.Emit.SignatureHelper.SignatureHelper
SignatureHelper() [1/4]
System.Reflection.Emit.SignatureHelper.SignatureHelper (Module mod, MdSigCallingConvention callingConvention) inline private
Definition at line 166 of file SignatureHelper.cs.
    {
        Init(mod, callingConvention);
    }
References System.Reflection.Emit.SignatureHelper.Init().
Referenced by System.Reflection.Emit.SignatureHelper.Equals(), System.Reflection.Emit.SignatureHelper.GetFieldSigHelper(), System.Reflection.Emit.SignatureHelper.GetLocalVarSigHelper(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.SignatureHelper.GetMethodSpecSigHelper(), System.Reflection.Emit.SignatureHelper.GetPropertySigHelper(), and System.Reflection.Emit.SignatureHelper.GetTypeSigToken().