Terraria: System.Reflection.Emit.SignatureHelper.GetMethodSpecSigHelper
GetMethodSpecSigHelper()
static SignatureHelper System.Reflection.Emit.SignatureHelper.GetMethodSpecSigHelper (Module scope, Type[] inst) inline static package
Definition at line 34 of file SignatureHelper.cs.
    {
        SignatureHelper signatureHelper = new SignatureHelper(scope, MdSigCallingConvention.GenericInst);
        signatureHelper.AddData(inst.Length);
        foreach (Type clsArgument in inst)
        {
            signatureHelper.AddArgument(clsArgument);
        }
        return signatureHelper;
    }
References System.Reflection.Emit.SignatureHelper.SignatureHelper(), and System.Reflection.Emit.SignatureHelper.AddData().
Referenced by System.Reflection.Emit.ModuleBuilder.GetMethodTokenInternal().