Terraria: System.Reflection.Emit.SignatureHelper.SetNumberOfSignatureElements
SetNumberOfSignatureElements()
void System.Reflection.Emit.SignatureHelper.SetNumberOfSignatureElements (bool forceCopy) inline private
Definition at line 515 of file SignatureHelper.cs.
    {
        int currSig = m_currSig;
        if (m_sizeLoc != -1)
        {
            if (m_argCount < 128 && !forceCopy)
            {
                m_signature[m_sizeLoc] = (byte)m_argCount;
                return;
            }
            int num = ((m_argCount < 128) ? 1 : ((m_argCount >= 16384) ? 4 : 2));
            byte[] array = new byte[m_currSig + num - 1];
            array[0] = m_signature[0];
            Buffer.BlockCopy(m_signature, m_sizeLoc + 1, array, m_sizeLoc + num, currSig - (m_sizeLoc + 1));
            m_signature = array;
            m_currSig = m_sizeLoc;
            AddData(m_argCount);
            m_currSig = currSig + (num - 1);
        }
    }
References System.Reflection.Emit.SignatureHelper.AddData(), System.array, System.Buffer.BlockCopy(), System.Reflection.Emit.SignatureHelper.m_argCount, System.Reflection.Emit.SignatureHelper.m_currSig, System.Reflection.Emit.SignatureHelper.m_signature, and System.Reflection.Emit.SignatureHelper.m_sizeLoc.
Referenced by System.Reflection.Emit.SignatureHelper.GetSignature(), and System.Reflection.Emit.SignatureHelper.InternalGetSignature().