Terraria: System.Reflection.Emit.SignatureHelper.Init
Init() [1/3]
void System.Reflection.Emit.SignatureHelper.Init (Module mod) inline private
Definition at line 193 of file SignatureHelper.cs.
    {
        m_signature = new byte[32];
        m_currSig = 0;
        m_module = mod as ModuleBuilder;
        m_argCount = 0;
        m_sigDone = false;
        m_sizeLoc = -1;
        if (m_module == null && mod != null)
        {
            throw new ArgumentException(SR.NotSupported_MustBeModuleBuilder);
        }
    }
References System.Reflection.Emit.SignatureHelper.m_argCount, System.Reflection.Emit.SignatureHelper.m_currSig, System.Reflection.Emit.SignatureHelper.m_module, System.Reflection.Emit.SignatureHelper.m_sigDone, System.Reflection.Emit.SignatureHelper.m_signature, System.Reflection.Emit.SignatureHelper.m_sizeLoc, and System.SR.NotSupported_MustBeModuleBuilder.
Referenced by System.Reflection.Emit.SignatureHelper.SignatureHelper(), System.Reflection.Emit.SignatureHelper.SignatureHelper(), System.Reflection.Emit.SignatureHelper.SignatureHelper(), System.Reflection.Emit.SignatureHelper.Init(), and System.Reflection.Emit.SignatureHelper.Init().