Terraria: System.Reflection.Emit.SignatureHelper.AddToken
AddToken()
void System.Reflection.Emit.SignatureHelper.AddToken (int token) inline private
Definition at line 449 of file SignatureHelper.cs.
    {
        int num = token & 0xFFFFFF;
        MetadataTokenType metadataTokenType = (MetadataTokenType)(token & -16777216);
        if (num > 67108863)
        {
            throw new ArgumentException(SR.Argument_LargeInteger);
        }
        num <<= 2;
        switch (metadataTokenType)
        {
        case MetadataTokenType.TypeRef:
            num |= 1;
            break;
        case MetadataTokenType.TypeSpec:
            num |= 2;
            break;
        }
        AddData(num);
    }
References System.Reflection.Emit.SignatureHelper.AddData(), and System.SR.Argument_LargeInteger.
Referenced by System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(), and System.Reflection.Emit.SignatureHelper.InternalAddTypeToken().