Terraria: System.Net.Mime.MimeBasePart.DecodeHeaderValue
DecodeHeaderValue()
static string System.Net.Mime.MimeBasePart.DecodeHeaderValue (string value) inline static package inherited
Definition at line 139 of file MimeBasePart.cs.
    {
        if (string.IsNullOrEmpty(value))
        {
            return string.Empty;
        }
        string text = string.Empty;
        string[] array = value.Split(s_headerValueSplitChars, StringSplitOptions.RemoveEmptyEntries);
        string[] array2 = array;
        foreach (string text2 in array2)
        {
            string[] array3 = text2.Split(s_questionMarkSplitChars);
            if (array3.Length != 5 || array3[0] != "=" || array3[4] != "=")
            {
                return value;
            }
            string name = array3[1];
            bool useBase64Encoding = array3[2] == "B";
            byte[] bytes = Encoding.ASCII.GetBytes(array3[3]);
            EncodedStreamFactory encodedStreamFactory = new EncodedStreamFactory();
            IEncodableStream encoderForHeader = encodedStreamFactory.GetEncoderForHeader(Encoding.GetEncoding(name), useBase64Encoding, 0);
            int count = encoderForHeader.DecodeBytes(bytes, 0, bytes.Length);
            Encoding encoding = Encoding.GetEncoding(name);
            text += encoding.GetString(bytes, 0, count);
        }
        return text;
    }
References System.array, System.Text.Encoding.ASCII, System.bytes, System.count, System.Net.Mime.IEncodableStream.DecodeBytes(), System.Net.Mime.EncodedStreamFactory.GetEncoderForHeader(), System.Text.Encoding.GetEncoding(), System.Text.Encoding.GetString(), System.Net.Mime.MimeBasePart.s_headerValueSplitChars, System.Net.Mime.MimeBasePart.s_questionMarkSplitChars, System.text, and System.value.