Terraria: System.Net.Mime.MimeBasePart.EndSend
EndSend()
void System.Net.Mime.MimeBasePart.EndSend (IAsyncResult asyncResult) inline package inherited
Definition at line 223 of file MimeBasePart.cs.
    {
        if (asyncResult == null)
        {
            throw new ArgumentNullException("asyncResult");
        }
        System.Net.LazyAsyncResult lazyAsyncResult = asyncResult as MimePartAsyncResult;
        if (lazyAsyncResult == null || lazyAsyncResult.AsyncObject != this)
        {
            throw new ArgumentException(System.SR.net_io_invalidasyncresult, "asyncResult");
        }
        if (lazyAsyncResult.EndCalled)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_io_invalidendcall, "EndSend"));
        }
        lazyAsyncResult.InternalWaitForCompletion();
        lazyAsyncResult.EndCalled = true;
        if (lazyAsyncResult.Result is Exception)
        {
            throw (Exception)lazyAsyncResult.Result;
        }
    }
References System.Net.LazyAsyncResult.AsyncObject, System.asyncResult, System.Net.LazyAsyncResult.EndCalled, System.SR.Format(), System.Net.LazyAsyncResult.InternalWaitForCompletion(), System.SR.net_io_invalidasyncresult, System.SR.net_io_invalidendcall, and System.Net.LazyAsyncResult.Result.
Referenced by System.Net.Mime.MimeMultiPart.MimePartSentCallbackHandler().