Terraria: System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker
AddOneArgTypeHelperWorker()
void System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker (Type clsArgument, bool lastWasGenericInst) inline private
Definition at line 291 of file SignatureHelper.cs.
    {
        if (clsArgument.IsGenericParameter)
        {
            if (clsArgument.DeclaringMethod != null)
            {
                AddElementType(CorElementType.ELEMENT_TYPE_MVAR);
            }
            else
            {
                AddElementType(CorElementType.ELEMENT_TYPE_VAR);
            }
            AddData(clsArgument.GenericParameterPosition);
            return;
        }
        if (clsArgument.IsGenericType && (!clsArgument.IsGenericTypeDefinition || !lastWasGenericInst))
        {
            AddElementType(CorElementType.ELEMENT_TYPE_GENERICINST);
            AddOneArgTypeHelperWorker(clsArgument.GetGenericTypeDefinition(), lastWasGenericInst: true);
            Type[] genericArguments = clsArgument.GetGenericArguments();
            AddData(genericArguments.Length);
            Type[] array = genericArguments;
            foreach (Type clsArgument2 in array)
            {
                AddOneArgTypeHelper(clsArgument2);
            }
            return;
        }
        if (clsArgument is TypeBuilder)
        {
            TypeBuilder typeBuilder = (TypeBuilder)clsArgument;
            int clsToken = ((!typeBuilder.Module.Equals(m_module)) ? m_module.GetTypeToken(clsArgument) : typeBuilder.TypeToken);
            if (clsArgument.IsValueType)
            {
                InternalAddTypeToken(clsToken, CorElementType.ELEMENT_TYPE_VALUETYPE);
            }
            else
            {
                InternalAddTypeToken(clsToken, CorElementType.ELEMENT_TYPE_CLASS);
            }
            return;
        }
        if (clsArgument is EnumBuilder)
        {
            TypeBuilder typeBuilder2 = ((EnumBuilder)clsArgument).m_typeBuilder;
            int clsToken2 = ((!typeBuilder2.Module.Equals(m_module)) ? m_module.GetTypeToken(clsArgument) : typeBuilder2.TypeToken);
            if (clsArgument.IsValueType)
            {
                InternalAddTypeToken(clsToken2, CorElementType.ELEMENT_TYPE_VALUETYPE);
            }
            else
            {
                InternalAddTypeToken(clsToken2, CorElementType.ELEMENT_TYPE_CLASS);
            }
            return;
        }
        if (clsArgument.IsByRef)
        {
            AddElementType(CorElementType.ELEMENT_TYPE_BYREF);
            clsArgument = clsArgument.GetElementType();
            AddOneArgTypeHelper(clsArgument);
            return;
        }
        if (clsArgument.IsPointer)
        {
            AddElementType(CorElementType.ELEMENT_TYPE_PTR);
            AddOneArgTypeHelper(clsArgument.GetElementType());
            return;
        }
        if (clsArgument.IsArray)
        {
            if (clsArgument.IsSZArray)
            {
                AddElementType(CorElementType.ELEMENT_TYPE_SZARRAY);
                AddOneArgTypeHelper(clsArgument.GetElementType());
                return;
            }
            AddElementType(CorElementType.ELEMENT_TYPE_ARRAY);
            AddOneArgTypeHelper(clsArgument.GetElementType());
            int arrayRank = clsArgument.GetArrayRank();
            AddData(arrayRank);
            AddData(0);
            AddData(arrayRank);
            for (int j = 0; j < arrayRank; j++)
            {
                AddData(0);
            }
            return;
        }
        CorElementType corElementType = CorElementType.ELEMENT_TYPE_MAX;
        if (clsArgument is RuntimeType)
        {
            corElementType = RuntimeTypeHandle.GetCorElementType((RuntimeType)clsArgument);
            if (corElementType == CorElementType.ELEMENT_TYPE_CLASS)
            {
                if (clsArgument == typeof(object))
                {
                    corElementType = CorElementType.ELEMENT_TYPE_OBJECT;
                }
                else if (clsArgument == typeof(string))
                {
                    corElementType = CorElementType.ELEMENT_TYPE_STRING;
                }
            }
        }
        if (IsSimpleType(corElementType))
        {
            AddElementType(corElementType);
        }
        else if (m_module == null)
        {
            InternalAddRuntimeType(clsArgument);
        }
        else if (clsArgument.IsValueType)
        {
            InternalAddTypeToken(m_module.GetTypeToken(clsArgument), CorElementType.ELEMENT_TYPE_VALUETYPE);
        }
        else
        {
            InternalAddTypeToken(m_module.GetTypeToken(clsArgument), CorElementType.ELEMENT_TYPE_CLASS);
        }
    }
References System.Reflection.Emit.SignatureHelper.AddData(), System.Reflection.Emit.SignatureHelper.AddElementType(), System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(), System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker(), System.array, System.Type.DeclaringMethod, System.Reflection.Module.Equals(), System.Type.GenericParameterPosition, System.Type.GetArrayRank(), System.RuntimeTypeHandle.GetCorElementType(), System.Type.GetElementType(), System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Reflection.Emit.ModuleBuilder.GetTypeToken(), System.Reflection.Emit.SignatureHelper.InternalAddRuntimeType(), System.Reflection.Emit.SignatureHelper.InternalAddTypeToken(), System.Type.IsArray, System.Type.IsByRef, System.Type.IsGenericParameter, System.Type.IsGenericType, System.Type.IsGenericTypeDefinition, System.Type.IsPointer, System.Reflection.Emit.SignatureHelper.IsSimpleType(), System.Type.IsSZArray, System.Type.IsValueType, System.Reflection.Emit.SignatureHelper.m_module, System.Reflection.Emit.TypeBuilder.Module, and System.Reflection.Emit.TypeBuilder.TypeToken.
Referenced by System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(), and System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelperWorker().