Terraria: System.Reflection.Emit.SignatureHelper.InternalGetSignature
InternalGetSignature()
byte[] System.Reflection.Emit.SignatureHelper.InternalGetSignature (out int length) inline package
Definition at line 549 of file SignatureHelper.cs.
    {
        if (!m_sigDone)
        {
            m_sigDone = true;
            SetNumberOfSignatureElements(forceCopy: false);
        }
        length = m_currSig;
        return m_signature;
    }
References System.length, System.Reflection.Emit.SignatureHelper.m_currSig, System.Reflection.Emit.SignatureHelper.m_sigDone, System.Reflection.Emit.SignatureHelper.m_signature, and System.Reflection.Emit.SignatureHelper.SetNumberOfSignatureElements().
Referenced by System.Reflection.Emit.ConstructorBuilder.ConstructorBuilder(), System.Reflection.Emit.FieldBuilder.FieldBuilder(), System.Reflection.Emit.MethodBuilder.GetLocalSignature(), and System.Reflection.Emit.MethodBuilder.GetTokenNoLock().