Terraria: System.Reflection.Emit.SignatureHelper.GetMethodSigHelper
GetMethodSigHelper() [7/7]
static SignatureHelper System.Reflection.Emit.SignatureHelper.GetMethodSigHelper (Module? mod, Type? returnType, Type?[] parameterTypes) inline static
Definition at line 24 of file SignatureHelper.cs.
    {
        return GetMethodSigHelper(mod, CallingConventions.Standard, returnType, null, null, parameterTypes, null, null);
    }
References System.Reflection.Emit.SignatureHelper.GetMethodSigHelper().
Referenced by System.Reflection.Emit.SymbolMethod.SymbolMethod(), System.Reflection.Emit.DynamicILGenerator.EmitCalli(), System.Reflection.Emit.ILGenerator.EmitCalli(), System.Reflection.Emit.ModuleBuilder.GetArrayMethodTokenNoLock(), System.Reflection.Emit.DynamicMethod.GetDynamicILInfo(), System.Reflection.Emit.DynamicMethod.GetILGenerator(), System.Reflection.Emit.DynamicILGenerator.GetMemberRefSignature(), System.Reflection.Emit.ModuleBuilder.GetMemberRefSignature(), System.Reflection.Emit.ModuleBuilder.GetMemberRefSignature(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.MethodBuilder.GetMethodSignature(), System.Reflection.Emit.ModuleBuilder.GetMethodTokenNoLock(), and System.Reflection.Emit.ModuleBuilder.InternalGetConstructorToken().