Terraria: System.Reflection.Emit.SignatureHelper.GetTypeSigToken
GetTypeSigToken()
static SignatureHelper System.Reflection.Emit.SignatureHelper.GetTypeSigToken (Module module, Type type) inline static package
Definition at line 153 of file SignatureHelper.cs.
    {
        if (module == null)
        {
            throw new ArgumentNullException("module");
        }
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        return new SignatureHelper(module, type);
    }
References System.Reflection.Emit.SignatureHelper.SignatureHelper(), and System.type.
Referenced by System.Reflection.Emit.ModuleBuilder.GetFieldTokenNoLock(), System.Reflection.Emit.ModuleBuilder.GetMemberRefToken(), and System.Reflection.Emit.ModuleBuilder.GetTypeTokenWorkerNoLock().