Terraria: Terraria.GameContent.Skies.AmbientSky.LostKiteSkyEntity.LostKiteSkyEntity
LostKiteSkyEntity()
Terraria.GameContent.Skies.AmbientSky.LostKiteSkyEntity.LostKiteSkyEntity (Player player, FastRandom random) inline
        {
            VirtualCamera virtualCamera = new VirtualCamera(player);
            Effects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
            int num = 100;
            if (Effects == SpriteEffects.FlipHorizontally)
            {
                Position.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
            }
            else
            {
                Position.X = virtualCamera.Position.X - (float)num;
            }
            Position.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 1600f - 2400f) + 2400f;
            Depth = random.NextFloat() * 3f + 3f;
            SetPositionInWorldBasedOnScreenSpace(Position);
            Texture = Main.Assets.Request<Texture2D>("Images/Backgrounds/Ambience/LostKite", (AssetRequestMode)1);
            Frame = new SpriteFrame(1, 42);
            LifeTime = random.Next(60, 121) * 60;
            OpacityNormalizedTimeToFadeIn = 0.15f;
            OpacityNormalizedTimeToFadeOut = 0.85f;
            BrightnessLerper = 0.2f;
            FinalOpacityMultiplier = 1f;
            FramingSpeed = 6;
            int num2 = random.Next(Frame.RowCount);
            for (int i = 0; i < num2; i++)
            {
                NextFrame();
            }
        }
References Terraria.Main.Assets, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.BrightnessLerper, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Depth, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Frame, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FramingSpeed, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.LifeTime, Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextFloat(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.NextFrame(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Position, Terraria.DataStructures.SpriteFrame.RowCount, Terraria.GameContent.Skies.AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.Texture, and Terraria.Main.worldSurface.