Terraria: System.Xml.Xsl.XPathConvert.BigNumber.BigNumber
BigNumber() [2/2]
System.Xml.Xsl.XPathConvert.BigNumber.BigNumber (FloatingDecimal dec) inline
Definition at line 143 of file XPathConvert.cs.
        {
            int num = 0;
            int exponent = dec.Exponent;
            int mantissaSize = dec.MantissaSize;
            _u2 = (uint)(dec[num] << 28);
            _u1 = 0u;
            _u0 = 0u;
            _exp = 4;
            _error = 0u;
            exponent--;
            Normalize();
            while (++num < mantissaSize)
            {
                uint num2 = MulTenAdd(dec[num]);
                exponent--;
                if (num2 != 0)
                {
                    Round(num2);
                    if (num < mantissaSize - 1)
                    {
                        _error++;
                    }
                    break;
                }
            }
            if (exponent != 0)
            {
                BigNumber[] array;
                if (exponent < 0)
                {
                    array = s_tenPowersNeg;
                    exponent = -exponent;
                }
                else
                {
                    array = s_tenPowersPos;
                }
                int num3 = exponent & 0x1F;
                if (num3 > 0)
                {
                    Mul(ref array[num3 - 1]);
                }
                num3 = (exponent >> 5) & 0xF;
                if (num3 > 0)
                {
                    Mul(ref array[num3 + 30]);
                }
            }
        }
References System.Xml.Xsl.XPathConvert.BigNumber._error, System.Xml.Xsl.XPathConvert.BigNumber._exp, System.Xml.Xsl.XPathConvert.BigNumber._u0, System.Xml.Xsl.XPathConvert.BigNumber._u1, System.Xml.Xsl.XPathConvert.BigNumber._u2, System.array, System.Xml.Dictionary, System.Xml.Xsl.XPathConvert.BigNumber.Mul(), System.Xml.Xsl.XPathConvert.BigNumber.MulTenAdd(), System.Xml.Xsl.XPathConvert.BigNumber.Normalize(), System.Xml.Xsl.XPathConvert.BigNumber.Round(), System.Xml.Xsl.XPathConvert.BigNumber.s_tenPowersNeg, and System.Xml.Xsl.XPathConvert.BigNumber.s_tenPowersPos.