Terraria: System.Xml.Xsl.XPathConvert.BigNumber.MakeUpperBound
MakeUpperBound()
void System.Xml.Xsl.XPathConvert.BigNumber.MakeUpperBound () inline
Definition at line 463 of file XPathConvert.cs.
        {
            uint num = _error + 1 >> 1;
            if (num != 0 && AddU(ref _u0, num) != 0 && AddU(ref _u1, 1u) != 0 && AddU(ref _u2, 1u) != 0)
            {
                _u2 = 2147483648u;
                _u0 = (_u0 >> 1) + (_u0 & 1);
                _exp++;
            }
            _error = 0u;
        }
References System.Xml.Xsl.XPathConvert.BigNumber._error, System.Xml.Xsl.XPathConvert.BigNumber._exp, System.Xml.Xsl.XPathConvert.BigNumber._u0, System.Xml.Xsl.XPathConvert.BigNumber._u1, System.Xml.Xsl.XPathConvert.BigNumber._u2, System.Xml.Xsl.XPathConvert.AddU(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbFast(), and System.Xml.Xsl.XPathConvert.FloatingDecimal.operator double().