Terraria: System.Xml.Xsl.XPathConvert.BigNumber.Normalize
Normalize()
void System.Xml.Xsl.XPathConvert.BigNumber.Normalize () inline private
Definition at line 267 of file XPathConvert.cs.
        {
            if (_u2 == 0)
            {
                if (_u1 == 0)
                {
                    if (_u0 == 0)
                    {
                        _exp = 0;
                        return;
                    }
                    _u2 = _u0;
                    _u0 = 0u;
                    _exp -= 64;
                }
                else
                {
                    _u2 = _u1;
                    _u1 = _u0;
                    _u0 = 0u;
                    _exp -= 32;
                }
            }
            int num;
            if ((num = CbitZeroLeft(_u2)) != 0)
            {
                int num2 = 32 - num;
                _u2 = (_u2 << num) | (_u1 >> num2);
                _u1 = (_u1 << num) | (_u0 >> num2);
                _u0 <<= num;
                _exp -= num;
            }
        }
References System.Xml.Xsl.XPathConvert.BigNumber._exp, System.Xml.Xsl.XPathConvert.BigNumber._u0, System.Xml.Xsl.XPathConvert.BigNumber._u1, System.Xml.Xsl.XPathConvert.BigNumber._u2, System.Xml.Xsl.XPathConvert.CbitZeroLeft(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XPathConvert.BigNumber.BigNumber(), System.Xml.Xsl.XPathConvert.BigNumber.MakeLowerBound(), and System.Xml.Xsl.XPathConvert.BigNumber.UMod1().