Terraria: System.Xml.Xsl.XPathConvert.BigNumber.MakeLowerBound
MakeLowerBound()
void System.Xml.Xsl.XPathConvert.BigNumber.MakeLowerBound () inline
Definition at line 475 of file XPathConvert.cs.
        {
            uint num = _error + 1 >> 1;
            if (num != 0 && AddU(ref _u0, 0 - num) == 0 && AddU(ref _u1, uint.MaxValue) == 0)
            {
                AddU(ref _u2, uint.MaxValue);
                if ((0x80000000u & _u2) == 0)
                {
                    Normalize();
                }
            }
            _error = 0u;
        }
References System.Xml.Xsl.XPathConvert.BigNumber._error, System.Xml.Xsl.XPathConvert.BigNumber._u0, System.Xml.Xsl.XPathConvert.BigNumber._u1, System.Xml.Xsl.XPathConvert.BigNumber._u2, System.Xml.Xsl.XPathConvert.AddU(), System.Xml.Dictionary, and System.Xml.Xsl.XPathConvert.BigNumber.Normalize().
Referenced by System.Xml.Xsl.XPathConvert.FloatingDecimal.operator double().