Terraria: System.Xml.Xsl.XPathConvert.BigNumber.Mul
Mul()
void System.Xml.Xsl.XPathConvert.BigNumber.Mul (ref BigNumber numOp) inline private
Definition at line 301 of file XPathConvert.cs.
        {
            uint num = 0u;
            uint u = 0u;
            uint u2 = 0u;
            uint u3 = 0u;
            uint u4 = 0u;
            uint u5 = 0u;
            uint uHi;
            uint u6;
            uint num2;
            uint num3;
            if ((u6 = _u0) != 0)
            {
                num2 = MulU(u6, numOp._u0, out uHi);
                num = num2;
                u = uHi;
                num2 = MulU(u6, numOp._u1, out uHi);
                num3 = AddU(ref u, num2);
                AddU(ref u2, uHi + num3);
                num2 = MulU(u6, numOp._u2, out uHi);
                num3 = AddU(ref u2, num2);
                AddU(ref u3, uHi + num3);
            }
            if ((u6 = _u1) != 0)
            {
                num2 = MulU(u6, numOp._u0, out uHi);
                num3 = AddU(ref u, num2);
                if (AddU(ref u2, uHi + num3) != 0 && AddU(ref u3, 1u) != 0)
                {
                    AddU(ref u4, 1u);
                }
                num2 = MulU(u6, numOp._u1, out uHi);
                num3 = AddU(ref u2, num2);
                if (AddU(ref u3, uHi + num3) != 0)
                {
                    AddU(ref u4, 1u);
                }
                num2 = MulU(u6, numOp._u2, out uHi);
                num3 = AddU(ref u3, num2);
                AddU(ref u4, uHi + num3);
            }
            u6 = _u2;
            num2 = MulU(u6, numOp._u0, out uHi);
            num3 = AddU(ref u2, num2);
            if (AddU(ref u3, uHi + num3) != 0 && AddU(ref u4, 1u) != 0)
            {
                AddU(ref u5, 1u);
            }
            num2 = MulU(u6, numOp._u1, out uHi);
            num3 = AddU(ref u3, num2);
            if (AddU(ref u4, uHi + num3) != 0)
            {
                AddU(ref u5, 1u);
            }
            num2 = MulU(u6, numOp._u2, out uHi);
            num3 = AddU(ref u4, num2);
            AddU(ref u5, uHi + num3);
            _exp += numOp._exp;
            _error += numOp._error;
            if ((u5 & 0x80000000u) == 0)
            {
                if ((u2 & 0x40000000u) != 0 && ((u2 & 0xBFFFFFFFu) != 0 || u != 0 || num != 0) && AddU(ref u2, 1073741824u) != 0 && AddU(ref u3, 1u) != 0 && AddU(ref u4, 1u) != 0)
                {
                    AddU(ref u5, 1u);
                    if ((u5 & 0x80000000u) != 0)
                    {
                        goto IL_0314;
                    }
                }
                _u2 = (u5 << 1) | (u4 >> 31);
                _u1 = (u4 << 1) | (u3 >> 31);
                _u0 = (u3 << 1) | (u2 >> 31);
                _exp--;
                _error <<= 1;
                if ((u2 & 0x7FFFFFFFu) != 0 || u != 0 || num != 0)
                {
                    _error++;
                }
                return;
            }
            if ((u2 & 0x80000000u) != 0 && ((u3 & (true ? 1u : 0u)) != 0 || (u2 & 0x7FFFFFFFu) != 0 || u != 0 || num != 0) && AddU(ref u3, 1u) != 0 && AddU(ref u4, 1u) != 0 && AddU(ref u5, 1u) != 0)
            {
                u5 = 2147483648u;
                _exp++;
            }
            goto IL_0314;
            IL_0314:
            _u2 = u5;
            _u1 = u4;
            _u0 = u3;
            if (u2 != 0 || u != 0 || num != 0)
            {
                _error++;
            }
        }
References System.Xml.Xsl.XPathConvert.BigNumber._error, System.Xml.Xsl.XPathConvert.BigNumber._exp, System.Xml.Xsl.XPathConvert.BigNumber._u0, System.Xml.Xsl.XPathConvert.BigNumber._u1, System.Xml.Xsl.XPathConvert.BigNumber._u2, System.Xml.Xsl.XPathConvert.AddU(), System.Xml.Dictionary, and System.Xml.Xsl.XPathConvert.MulU().
Referenced by System.Xml.Xsl.XPathConvert.BigNumber.BigNumber().