Terraria: System.Xml.Xsl.XPathConvert.BigNumber.operator double
operator double()
static System.Xml.Xsl.XPathConvert.BigNumber.operator double (BigNumber bn) inline explicit static
Definition at line 398 of file XPathConvert.cs.
        {
            int num = bn._exp + 1022;
            if (num >= 2047)
            {
                return double.PositiveInfinity;
            }
            uint u;
            uint u2;
            uint num2;
            if (num > 0)
            {
                u = (uint)(num << 20) | ((bn._u2 & 0x7FFFFFFF) >> 11);
                u2 = (bn._u2 << 21) | (bn._u1 >> 11);
                num2 = (bn._u1 << 21) | NotZero(bn._u0);
            }
            else if (num > -20)
            {
                int num3 = 12 - num;
                u = bn._u2 >> num3;
                u2 = (bn._u2 << 32 - num3) | (bn._u1 >> num3);
                num2 = (bn._u1 << 32 - num3) | NotZero(bn._u0);
            }
            else if (num == -20)
            {
                u = 0u;
                u2 = bn._u2;
                num2 = bn._u1 | ((bn._u0 != 0) ? 1u : 0u);
            }
            else if (num > -52)
            {
                int num4 = -num - 20;
                u = 0u;
                u2 = bn._u2 >> num4;
                num2 = (bn._u2 << 32 - num4) | NotZero(bn._u1) | NotZero(bn._u0);
            }
            else
            {
                if (num != -52)
                {
                    return 0.0;
                }
                u = 0u;
                u2 = 0u;
                num2 = bn._u2 | NotZero(bn._u1) | NotZero(bn._u0);
            }
            if ((num2 & 0x80000000u) != 0 && ((num2 & 0x7FFFFFFFu) != 0 || (u2 & (true ? 1u : 0u)) != 0) && AddU(ref u2, 1u) != 0)
            {
                AddU(ref u, 1u);
            }
            return BitConverter.UInt64BitsToDouble(((ulong)u << 32) | u2);
        }
References System.Xml.Xsl.XPathConvert.AddU(), System.Xml.Dictionary, System.Xml.Xsl.XPathConvert.NotZero(), and System.BitConverter.UInt64BitsToDouble().