Terraria: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_KingSlime
RegisterBoss_KingSlime()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_KingSlime () inline private
Definition at line 377 of file ItemDropDatabase.cs.
    {
        short type = 50;
        RegisterToNPC(type, ItemDropRule.BossBag(3318));
        RegisterToNPC(type, ItemDropRule.MasterModeCommonDrop(4929));
        RegisterToNPC(type, ItemDropRule.MasterModeDropOnAllPlayers(4797, _masterModeDropRng));
        LeadingConditionRule leadingConditionRule = new LeadingConditionRule(new Conditions.NotExpert());
        RegisterToNPC(type, leadingConditionRule);
        leadingConditionRule.OnSuccess(ItemDropRule.Common(2430, 4));
        leadingConditionRule.OnSuccess(ItemDropRule.Common(2493, 7));
        leadingConditionRule.OnSuccess(ItemDropRule.OneFromOptions(1, 256, 257, 258));
        leadingConditionRule.OnSuccess(ItemDropRule.NotScalingWithLuck(2585, 3)).OnFailedRoll(ItemDropRule.Common(2610));
        leadingConditionRule.OnSuccess(ItemDropRule.Common(998));
    }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._masterModeDropRng, Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag(), Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), Terraria.GameContent.ItemDropRules.ItemDropRule.NotScalingWithLuck(), Terraria.GameContent.ItemDropRules.ItemDropRule.OneFromOptions(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().