Terraria: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses
RegisterBosses()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses () inline private
    {
        RegisterBoss_EOC();
        RegisterBoss_BOC();
        RegisterBoss_EOW();
        RegisterBoss_QueenBee();
        RegisterBoss_Skeletron();
        RegisterBoss_WOF();
        RegisterBoss_AncientCultist();
        RegisterBoss_MoonLord();
        RegisterBoss_LunarTowers();
        RegisterBoss_Betsy();
        RegisterBoss_Golem();
        RegisterBoss_DukeFishron();
        RegisterBoss_SkeletronPrime();
        RegisterBoss_TheDestroyer();
        RegisterBoss_Twins();
        RegisterBoss_Plantera();
        RegisterBoss_KingSlime();
        RegisterBoss_FrostMoon();
        RegisterBoss_PumpkinMoon();
        RegisterBoss_HallowBoss();
        RegisterBoss_QueenSlime();
        RegisterBoss_Deerclops();
    }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_AncientCultist(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Betsy(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_BOC(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Deerclops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_DukeFishron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_EOC(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_EOW(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_FrostMoon(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Golem(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_HallowBoss(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_KingSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_LunarTowers(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_MoonLord(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Plantera(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_PumpkinMoon(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenBee(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_QueenSlime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Skeletron(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_SkeletronPrime(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_TheDestroyer(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Twins(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_WOF().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().