Terraria: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMimic
RegisterMimic()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMimic () inline private
Definition at line 222 of file ItemDropDatabase.cs.
    {
        RegisterToNPC(85, new LeadingConditionRule(new Conditions.NotRemixSeed())).OnSuccess(ItemDropRule.OneFromOptions(1, 437, 517, 535, 536, 532, 554));
        RegisterToNPC(85, new LeadingConditionRule(new Conditions.RemixSeedHardmode())).OnSuccess(ItemDropRule.OneFromOptions(1, 437, 3069, 535, 536, 532, 554));
        RegisterToNPC(85, new LeadingConditionRule(new Conditions.RemixSeedEasymode())).OnSuccess(ItemDropRule.OneFromOptions(1, 49, 50, 53, 54, 5011, 975));
        IItemDropRule itemDropRule = ItemDropRule.Common(1312, 20);
        itemDropRule.OnFailedRoll(new LeadingConditionRule(new Conditions.NotRemixSeed())).OnSuccess(ItemDropRule.OneFromOptions(1, 676, 725, 1264));
        itemDropRule.OnFailedRoll(new LeadingConditionRule(new Conditions.RemixSeedHardmode())).OnSuccess(ItemDropRule.OneFromOptions(1, 676, 1319, 1264));
        itemDropRule.OnFailedRoll(new LeadingConditionRule(new Conditions.RemixSeedEasymode())).OnSuccess(ItemDropRule.OneFromOptions(1, 670, 724, 950, 725, 987, 1579));
        RegisterToNPC(629, itemDropRule);
    }
References Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.OneFromOptions(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().