Terraria: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Skeletron
RegisterBoss_Skeletron()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_Skeletron () inline private
Definition at line 537 of file ItemDropDatabase.cs.
    {
        Conditions.NotExpert condition = new Conditions.NotExpert();
        short type = 35;
        RegisterToNPC(type, ItemDropRule.BossBag(3323));
        RegisterToNPC(type, ItemDropRule.MasterModeCommonDrop(4927));
        RegisterToNPC(type, ItemDropRule.MasterModeDropOnAllPlayers(4801, _masterModeDropRng));
        RegisterToNPC(type, ItemDropRule.ByCondition(condition, 1281, 7)).OnFailedRoll(ItemDropRule.Common(1273, 7)).OnFailedRoll(ItemDropRule.Common(1313, 7));
        RegisterToNPC(type, ItemDropRule.Common(4993, 7));
    }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._masterModeDropRng, Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag(), Terraria.GameContent.ItemDropRules.ItemDropRule.ByCondition(), Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().