Terraria: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_DukeFishron
RegisterBoss_DukeFishron()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBoss_DukeFishron () inline private
Definition at line 634 of file ItemDropDatabase.cs.
    {
        Conditions.NotExpert condition = new Conditions.NotExpert();
        short type = 370;
        RegisterToNPC(type, ItemDropRule.BossBag(3330));
        RegisterToNPC(type, ItemDropRule.MasterModeCommonDrop(4936));
        RegisterToNPC(type, ItemDropRule.MasterModeDropOnAllPlayers(4808, _masterModeDropRng));
        RegisterToNPC(type, ItemDropRule.ByCondition(condition, 2588, 7));
        RegisterToNPC(type, ItemDropRule.ByCondition(condition, 2609, 15));
        RegisterToNPC(type, new LeadingConditionRule(new Conditions.NotRemixSeed())).OnSuccess(new LeadingConditionRule(condition)).OnSuccess(ItemDropRule.OneFromOptions(1, 2611, 2624, 2622, 2621, 2623));
        RegisterToNPC(type, new LeadingConditionRule(new Conditions.RemixSeed())).OnSuccess(new LeadingConditionRule(condition)).OnSuccess(ItemDropRule.OneFromOptions(1, 2611, 2624, 2622, 2621, 157));
    }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._masterModeDropRng, Terraria.GameContent.ItemDropRules.ItemDropRule.BossBag(), Terraria.GameContent.ItemDropRules.ItemDropRule.ByCondition(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeCommonDrop(), Terraria.GameContent.ItemDropRules.ItemDropRule.MasterModeDropOnAllPlayers(), Terraria.GameContent.ItemDropRules.ItemDropRule.OneFromOptions(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses().