Terraria: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterFoodDrops
RegisterFoodDrops()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterFoodDrops () inline private
    {
        RegisterToNPC(48, ItemDropRule.Food(4016, 50));
        RegisterToNPC(224, ItemDropRule.Food(4021, 50));
        RegisterToNPC(44, ItemDropRule.Food(4037, 10));
        RegisterToNPC(469, ItemDropRule.Food(4037, 100));
        RegisterToMultipleNPCs(ItemDropRule.Food(4020, 30), 163, 238, 164, 165, 530, 531);
        RegisterToMultipleNPCs(ItemDropRule.Food(4029, 50), 480, 481);
        RegisterToMultipleNPCs(ItemDropRule.Food(4030, 75), 498, 499, 500, 501, 502, 503, 504, 505, 506, 496, 497, 494, 495);
        RegisterToMultipleNPCs(ItemDropRule.Food(4036, 50), 482, 483);
        RegisterToMultipleNPCs(ItemDropRule.Food(4015, 100), 6, 173);
        RegisterToMultipleNPCs(ItemDropRule.Food(4026, 150), 150, 147, 184);
        RegisterToMultipleNPCs(ItemDropRule.Food(4027, 75), 154, 206);
        RegisterToMultipleNPCs(ItemDropRule.Food(3532, 15), 170, 180, 171);
        RegisterToNPC(289, ItemDropRule.Food(4018, 35));
        RegisterToNPC(34, ItemDropRule.Food(4018, 70));
        RegisterToMultipleNPCs(ItemDropRule.Food(4013, 21), 293, 291, 292);
        RegisterToMultipleNPCs(ItemDropRule.Food(5042, 30), 43, 175, 56);
        RegisterToNPC(287, ItemDropRule.Food(5042, 10));
        RegisterToMultipleNPCs(ItemDropRule.Food(5041, 150), 21, 201, 202, 203, 322, 323, 324, 635, 449, 450, 451, 452);
        RegisterToNPC(290, ItemDropRule.Food(4013, 7));
        RegisterToMultipleNPCs(ItemDropRule.Food(4025, 30), 39, 156);
        RegisterToMultipleNPCs(ItemDropRule.Food(4023, 40), 177, 152);
        RegisterToMultipleNPCs(ItemDropRule.Food(4012, 50), 581, 509, 580, 508, 69);
        RegisterToMultipleNPCs(ItemDropRule.Food(4028, 30), 546, 542, 544, 543, 545);
        RegisterToMultipleNPCs(ItemDropRule.Food(4035, 50), 67, 65);
        RegisterToMultipleNPCs(ItemDropRule.Food(4011, 150), 120, 137, 138);
        RegisterToNPC(122, ItemDropRule.Food(4017, 75));
    }
References Terraria.GameContent.ItemDropRules.ItemDropRule.Food(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToMultipleNPCs(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToNPC().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().