Terraria: Microsoft.Xna.Framework.UserAsyncDispatcher.AsyncDispatcherThreadFunction
AsyncDispatcherThreadFunction()
static void Microsoft.Xna.Framework.UserAsyncDispatcher.AsyncDispatcherThreadFunction () inline static private
Definition at line 57 of file UserAsyncDispatcher.cs.
    {
        while (true)
        {
            ManagedCallType managedCallType;
            uint managedCallArgs;
            KernelReturnCode kernelReturnCode = WaitForAsyncOperationToFinish(out managedCallType, out managedCallArgs);
            if (kernelReturnCode == KernelReturnCode.AsyncShutdown)
            {
                break;
            }
            Helpers.ThrowExceptionFromResult((uint)kernelReturnCode);
            if (managedCallType == ManagedCallType.AsyncOperationCompleted)
            {
                HandleFinishedOperation(managedCallArgs);
            }
            else
            {
                HandleManagedCallback(managedCallType, managedCallArgs);
            }
        }
    }
References Microsoft.Xna.Framework.UserAsyncDispatcher.HandleFinishedOperation(), Microsoft.Xna.Framework.UserAsyncDispatcher.HandleManagedCallback(), Microsoft.Xna.Framework.Helpers.ThrowExceptionFromResult(), and Microsoft.Xna.Framework.UserAsyncDispatcher.WaitForAsyncOperationToFinish().
Referenced by Microsoft.Xna.Framework.UserAsyncDispatcher.Initialize().