Terraria: Microsoft.Xna.Framework.UserAsyncDispatcher.PlatformSpecificInitialize
PlatformSpecificInitialize()
static unsafe void Microsoft.Xna.Framework.UserAsyncDispatcher.PlatformSpecificInitialize () inline static private
Definition at line 18 of file UserAsyncDispatcher.cs.
    {
        UnsafeNativeMethods.SecurityAttributes lpEventAttributes = new UnsafeNativeMethods.SecurityAttributes(inheritHandle: true);
        parentExitEvent = new SafeWaitHandle(UnsafeNativeMethods.CreateEvent(ref lpEventAttributes, bManualReset: true, bInitialState: false, IntPtr.Zero), ownsHandle: true);
        if (parentExitEvent.IsInvalid)
        {
            throw new WaitHandleCannotBeOpenedException();
        }
        AppDomain.CurrentDomain.ProcessExit += OnExit;
        AppDomain.CurrentDomain.DomainUnload += OnExit;
        KernelReturnCode result = (KernelReturnCode)WindowsManagedCallbackHandler.Initialize(parentExitEvent.DangerousGetHandle().ToPointer());
        Helpers.ThrowExceptionFromResult((uint)result);
    }
References Microsoft.Xna.Framework.UnsafeNativeMethods.CreateEvent(), Microsoft.Xna.Framework.WindowsManagedCallbackHandler.Initialize(), Microsoft.Xna.Framework.UserAsyncDispatcher.OnExit(), Microsoft.Xna.Framework.UserAsyncDispatcher.parentExitEvent, Microsoft.Xna.Framework.Helpers.ThrowExceptionFromResult(), and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.UserAsyncDispatcher.Initialize().