Terraria: UIBestiaryEntryGrid.UIBestiaryEntryGrid
UIBestiaryEntryGrid()
UIBestiaryEntryGrid.UIBestiaryEntryGrid (List< BestiaryEntry > workingSet, MouseEvent clickOnEntryEvent) inline
     {
         Width = new StyleDimension(0f, 1f);
         Height = new StyleDimension(0f, 1f);
         _workingSetEntries = workingSet;
         _clickOnEntryEvent = clickOnEntryEvent;
         SetPadding(0f);
         UpdateEntries();
         FillBestiarySpaceWithEntries();
     }
References _clickOnEntryEvent, _workingSetEntries, FillBestiarySpaceWithEntries(), UIElement.Height, UIElement.SetPadding(), UpdateEntries(), and UIElement.Width.