Terraria: Terraria.Item.SetDefaults3
SetDefaults3()
void Terraria.Item.SetDefaults3 (int type) inline
References Terraria.Item.accessory, Terraria.ID.AmmoID.Arrow, Terraria.Item.autoReuse, Terraria.Item.axe, Terraria.Item.backSlot, Terraria.Item.bait, Terraria.Item.beardSlot, Terraria.Item.bodySlot, Terraria.Item.buffTime, Terraria.Item.buffType, Terraria.ID.AmmoID.Bullet, Terraria.Item.buyPrice(), Terraria.Item.cartTrack, Terraria.Item.channel, Terraria.Item.CommonMaxStack, Terraria.Item.consumable, Terraria.Item.createTile, Terraria.Item.createWall, Terraria.Item.crit, Terraria.Item.damage, Terraria.Item.DefaultToQuestFish(), Terraria.Item.DefaultToSeaShell(), Terraria.Item.defense, Terraria.Item.dungeonPrice, Terraria.Item.eclipseMothronPrice, Terraria.Item.fishingPole, Terraria.Item.flame, Terraria.Item.frontSlot, Terraria.Item.glowMask, Terraria.Item.hammer, Terraria.Item.handOffSlot, Terraria.Item.handOnSlot, Terraria.Item.hasVanityEffects, Terraria.Item.headSlot, Terraria.Item.healLife, Terraria.Item.healMana, Terraria.Entity.height, Terraria.Item.holdStyle, Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item2, Terraria.ID.SoundID.Item23, Terraria.ID.SoundID.Item25, Terraria.ID.SoundID.Item3, Terraria.ID.SoundID.Item41, Terraria.ID.SoundID.Item43, Terraria.ID.SoundID.Item44, Terraria.ID.SoundID.Item5, Terraria.ID.SoundID.Item6, Terraria.ID.SoundID.Item75, Terraria.ID.SoundID.Item76, Terraria.ID.SoundID.Item77, Terraria.ID.SoundID.Item78, Terraria.ID.SoundID.Item79, Terraria.ID.SoundID.Item80, Terraria.ID.SoundID.Item81, Terraria.ID.SoundID.Item82, Terraria.ID.SoundID.Item83, Terraria.ID.SoundID.Item84, Terraria.ID.SoundID.Item85, Terraria.ID.SoundID.Item88, Terraria.ID.SoundID.Item90, Terraria.ID.SoundID.Item92, Terraria.ID.SoundID.Item95, Terraria.ID.SoundID.Item97, Terraria.Item.knockBack, Terraria.Item.legSlot, Terraria.Item.magic, Terraria.Item.makeNPC, Terraria.Item.MakeUsableWithChlorophyteExtractinator(), Terraria.Item.mana, Terraria.Item.maxStack, Terraria.Item.mech, Terraria.Item.melee, Terraria.Item.mountType, Terraria.Item.noMelee, Terraria.Item.noUseGraphic, Terraria.Item.noWet, Terraria.Item.pick, Terraria.Item.placeStyle, Terraria.Item.potion, Terraria.Item.queenBeePrice, Terraria.Item.ranged, Terraria.Item.rare, Terraria.Item.reuseDelay, Terraria.Item.scale, Terraria.Item.sellPrice(), Terraria.Item.sentry, Terraria.Item.SetDefaults3(), Terraria.Item.shoeSlot, Terraria.Item.shoot, Terraria.Item.shootSpeed, Terraria.GameContent.Items.ItemVariants.StrongerVariant, Terraria.Item.summon, Terraria.Item.tileBoost, Terraria.Item.type, Terraria.Item.useAmmo, Terraria.Item.useAnimation, Terraria.Item.UseSound, Terraria.Item.useStyle, Terraria.Item.useTime, Terraria.Item.useTurn, Terraria.Item.value, Terraria.Item.vanity, Terraria.Item.Variant, Terraria.GameContent.Items.ItemVariants.WeakerVariant, Terraria.Entity.width, and Terraria.Item.wingSlot.
Referenced by Terraria.Item.SetDefaults(), Terraria.Item.SetDefaults3(), and Terraria.Item.SetDefaults4().