Terraria: Terraria.Item.SetDefaults1
SetDefaults1()
void Terraria.Item.SetDefaults1 (int type) inline
References Terraria.Item.accessory, Terraria.Item.alpha, Terraria.Item.ammo, Terraria.ID.AmmoID.Arrow, Terraria.Item.autoReuse, Terraria.Item.axe, Terraria.Item.backSlot, Terraria.Item.balloonSlot, Terraria.Item.bodySlot, Terraria.Item.buffTime, Terraria.Item.buffType, Terraria.ID.AmmoID.Bullet, Terraria.Item.buyPrice(), Terraria.Item.channel, Terraria.ID.AmmoID.Coin, Terraria.Item.color, Terraria.Item.CommonMaxStack, Terraria.Item.consumable, Terraria.Item.createTile, Terraria.Item.createWall, Terraria.Item.crit, Terraria.Item.damage, Terraria.ID.AmmoID.Dart, Terraria.Item.defense, Terraria.GameContent.Items.ItemVariants.DisabledBossSummonVariant, Terraria.Item.dungeonPrice, Terraria.Item.eclipsePrice, Terraria.Item.faceSlot, Terraria.ID.AmmoID.FallenStar, Terraria.Item.flame, Terraria.ID.AmmoID.Flare, Terraria.ID.AmmoID.Gel, Terraria.Item.glowMask, Terraria.Player.hairColor, Terraria.Item.hammer, Terraria.Item.handOffSlot, Terraria.Item.handOnSlot, Terraria.Item.hasVanityEffects, Terraria.Item.headSlot, Terraria.Item.healLife, Terraria.Item.healMana, Terraria.Entity.height, Terraria.Item.hellPrice, Terraria.Item.holdStyle, Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item10, Terraria.ID.SoundID.Item11, Terraria.ID.SoundID.Item12, Terraria.ID.SoundID.Item13, Terraria.ID.SoundID.Item15, Terraria.ID.SoundID.Item157, Terraria.ID.SoundID.Item16, Terraria.ID.SoundID.Item2, Terraria.ID.SoundID.Item20, Terraria.ID.SoundID.Item21, Terraria.ID.SoundID.Item23, Terraria.ID.SoundID.Item25, Terraria.ID.SoundID.Item28, Terraria.ID.SoundID.Item29, Terraria.ID.SoundID.Item3, Terraria.ID.SoundID.Item31, Terraria.ID.SoundID.Item34, Terraria.ID.SoundID.Item36, Terraria.ID.SoundID.Item38, Terraria.ID.SoundID.Item4, Terraria.ID.SoundID.Item41, Terraria.ID.SoundID.Item43, Terraria.ID.SoundID.Item5, Terraria.ID.SoundID.Item6, Terraria.ID.SoundID.Item61, Terraria.ID.SoundID.Item63, Terraria.ID.SoundID.Item64, Terraria.ID.SoundID.Item8, Terraria.ID.SoundID.Item9, Terraria.Item.knockBack, Terraria.Item.legSlot, Terraria.Item.lifeRegen, Terraria.Item.magic, Terraria.Item.makeNPC, Terraria.Item.MakeUsableWithChlorophyteExtractinator(), Terraria.Item.mana, Terraria.Item.maxStack, Terraria.Item.mech, Terraria.Item.melee, Terraria.Main.myPlayer, Terraria.Item.neckSlot, Terraria.Item.noMelee, Terraria.Item.notAmmo, Terraria.Item.noUseGraphic, Terraria.Item.noWet, Terraria.Player.pantsColor, Terraria.Item.pick, Terraria.Item.placeStyle, Terraria.Main.player, Terraria.Item.potion, Terraria.Item.ranged, Terraria.Item.rare, Terraria.GameContent.Items.ItemVariants.RebalancedVariant, Terraria.Item.reuseDelay, Terraria.ID.AmmoID.Rocket, Terraria.ID.AmmoID.Sand, Terraria.Item.scale, Terraria.Item.sellPrice(), Terraria.Item.SetShopValues(), Terraria.Item.shadowOrbPrice, Terraria.Item.shieldSlot, Terraria.Player.shirtColor, Terraria.Item.shoeSlot, Terraria.Item.shoot, Terraria.Item.shootsEveryUse, Terraria.Item.shootSpeed, Terraria.ID.AmmoID.Snowball, Terraria.ID.AmmoID.Solution, Terraria.GameContent.Items.ItemVariants.StrongerVariant, Terraria.Item.tileBoost, Terraria.Item.tileWand, Terraria.Item.type, Terraria.Item.useAmmo, Terraria.Item.useAnimation, Terraria.Item.UseSound, Terraria.Item.useStyle, Terraria.Item.useTime, Terraria.Item.useTurn, Terraria.Item.value, Terraria.Item.vanity, Terraria.Item.Variant, Terraria.Item.waistSlot, Terraria.GameContent.Items.ItemVariants.WeakerVariant, Terraria.Entity.width, and Terraria.Item.wingSlot.
Referenced by Terraria.Item.SetDefaults(), and Terraria.Item.SetDefaults4().