Terraria: Terraria.Item.SetDefaults
SetDefaults() [2/2]
void Terraria.Item.SetDefaults (int Type = 0) inline
    {
        SetDefaults(Type, noMatCheck: false, null);
    }
References Terraria.Item.SetDefaults().
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.UIBestiaryInfoItemLine(), Terraria.Recipe.AddAshWoodFurnitureArmorAndItems(), Terraria.Recipe.AddBalloonFurniture(), Terraria.Recipe.AddBambooFurniture(), Terraria.WorldGen.AddBuriedChest(), Terraria.Recipe.AddCoralFurniture(), Terraria.Recipe.AddCustomShimmerResult(), Terraria.Recipe.AddLesionFurniture(), Terraria.Recipe.AddNebulaFurniture(), Terraria.Recipe.AddSandstoneFurniture(), Terraria.Recipe.AddSolarFurniture(), Terraria.Recipe.AddSpiderFurniture(), Terraria.Recipe.AddStardustFurniture(), Terraria.Recipe.AddVortexFurniture(), Terraria.Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Terraria.Player.ApplyCoating(), Terraria.Player.ApplyEquipFunctional(), Terraria.Player.ApplyPaint(), Terraria.Player.ApplyWilsonBeard(), Terraria.Lang.BartenderHelpText(), Terraria.NPC.CatchNPC(), Terraria.Item.ChangeItemType(), Terraria.Item.CombineWithNearbyItems(), Terraria.Player.ConsumeItem(), Terraria.Recipe.CreateReversePlatformRecipes(), Terraria.Recipe.CreateReverseWallRecipes(), Terraria.UI.ChestUI.DepositAll(), Terraria.Player.Deserialize(), Terraria.Player.DoCoins(), Terraria.UI.AchievementAdvisor.DrawMouseHover(), Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.DrawSelf(), Terraria.Item.DropCache(), Terraria.Player.DropItems(), Terraria.Cinematics.DSTFilm.EquipDSTShaderItem(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNoTraps(), Terraria.Projectile.FishingCheck(), Terraria.Item.FixAgainstExploit(), Terraria.Player.GetAnglerReward_Bait(), Terraria.Player.GetAnglerReward_Decoration(), Terraria.Player.GetAnglerReward_MainReward(), Terraria.Player.GetAnglerReward_Money(), Terraria.Player.GetDyeTraderReward(), Terraria.Item.GetPickedUpByMonsters_Money(), Terraria.Item.GetPickedUpByMonsters_Special(), Terraria.Item.GetShimmered(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.Player.Hurt(), Terraria.ID.ContentSamples.Initialize(), Terraria.Player.ItemCheck_ApplyHoldStyle(), Terraria.Player.ItemCheck_CheckFishingBobber_PickAndConsumeBait(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.Player.KillMe(), Terraria.UI.ItemSlot.LeftClick(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.UI.ChestUI.MoveCoins(), Terraria.Item.netDefaults(), Terraria.Item.NewItem(), Terraria.Item.OnCreated(), Terraria.UI.ItemSlot.OverrideLeftClick(), Terraria.UI.ItemSlot.PickupItemIntoMouse(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_Walls_FillEmptySpace(), Terraria.Player.PlaceWeapon(), Terraria.Graphics.Renderers.ItemTransferParticle.Prepare(), Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ProvideUIElement(), Terraria.Player.PutItemInInventoryFromItemUsage(), Terraria.Chest.PutItemInNearbyChest(), Terraria.UI.ChestUI.QuickStack(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadItem(), Terraria.GameContent.Tile_Entities.TEHatRack.ReadItem(), Terraria.Player.SellItem(), Terraria.NetMessage.SendData(), Terraria.ID.ContentSamples.CreativeHelper.SetCreativeMenuOrder(), Terraria.Item.SetDefaults(), Terraria.Item.SetDefaults(), Terraria.Item.SetDefaults4(), Terraria.Item.SetDefaults5(), Terraria.Recipe.SetIngredients(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.SetInventoryFromMannequin(), Terraria.Recipe.SetupRecipes(), Terraria.Chest.SetupShop(), Terraria.UI.ItemSorting.SortCoins(), Terraria.Player.TakeUnityPotion(), Terraria.Player.TileInteractionsUse(), Terraria.UI.ItemSlot.TryOpenContainer(), Terraria.UI.ItemSlot.TryPickupDyeToCursor(), Terraria.GameContent.Biomes.DeadMansChestBiome.TurnGoldChestIntoDeadMansChest(), Terraria.Item.TurnToAir(), Terraria.Player.Update(), and Terraria.Recipe.UpdateWhichItemsAreMaterials().