Terraria: Terraria.Item.SetDefaults5
SetDefaults5()
void Terraria.Item.SetDefaults5 (int type) inline
    {
        switch (type)
        {
        case 3990:
            DefaultToAccessory(36, 28);
            shoeSlot = 18;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 2));
            break;
        case 3991:
            DefaultToAccessory(30, 42);
            faceSlot = 9;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            break;
        case 3992:
            defense = 8;
            DefaultToAccessory(20, 40);
            handOnSlot = 20;
            handOffSlot = 12;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            break;
        case 3993:
            DefaultToAccessory(34, 30);
            shoeSlot = 19;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 8));
            break;
        case 3994:
            DefaultToAccessory(24, 30);
            shoeSlot = 20;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 2));
            break;
        case 3995:
            DefaultToAccessory(34, 32);
            handOnSlot = 21;
            handOffSlot = 13;
            shoeSlot = 20;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 5));
            break;
        case 3996:
            DefaultToAccessory(28, 30);
            handOnSlot = 21;
            handOffSlot = 13;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 2));
            break;
        case 3997:
            defense = 6;
            DefaultToAccessory(36, 38);
            shieldSlot = 7;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 8));
            break;
        case 3998:
            defense = 10;
            DefaultToAccessory(36, 40);
            shieldSlot = 8;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            break;
        case 3999:
            DefaultToAccessory(22, 32);
            faceSlot = 10;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 2, 50));
            break;
        case 4000:
            DefaultToAccessory(28, 32);
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 4));
            break;
        case 4001:
            DefaultToAccessory(26, 36);
            backSlot = 14;
            frontSlot = 5;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 3));
            break;
        case 4002:
            DefaultToAccessory(34, 36);
            backSlot = 15;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 7, 50));
            break;
        case 4003:
            DefaultToAccessory(30, 34);
            faceSlot = 11;
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 5));
            break;
        case 4004:
            DefaultToAccessory(30, 32);
            faceSlot = 13;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 3));
            break;
        case 4005:
            DefaultToAccessory(30, 30);
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            break;
        case 4006:
            DefaultToAccessory(36, 38);
            backSlot = 16;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            break;
        case 4007:
            DefaultToAccessory(26, 30);
            neckSlot = 10;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 3));
            break;
        case 4008:
            defense = 4;
            DefaultToHeadgear(24, 22, 216);
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 2));
            break;
        case 4038:
            DefaultToAccessory(28, 34);
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 7, 50));
            neckSlot = 12;
            break;
        case 4039:
            DefaultToGolfClub(20, 20);
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 1));
            break;
        case 4094:
            DefaultToGolfClub(20, 20);
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 1));
            break;
        case 4092:
            DefaultToGolfClub(20, 20);
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 1));
            break;
        case 4093:
            DefaultToGolfClub(20, 20);
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 1));
            break;
        case 4040:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 476;
            width = 12;
            height = 12;
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 1));
            break;
        case 4041:
        case 4042:
        case 4043:
        case 4044:
        case 4045:
        case 4046:
        case 4047:
        case 4048:
        case 4241:
            DefaultToPlaceableTile((ushort)3, 0);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 5));
            autoReuse = false;
            useTime = useAnimation;
            break;
        case 4049:
            DefaultToLawnMower(20, 20);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 1));
            break;
        case 4050:
            DefaultToPlaceableTile((ushort)478, 0);
            break;
        case 4051:
            DefaultToPlaceableTile((ushort)479, 0);
            break;
        case 4052:
            DefaultToPlaceableWall(234);
            break;
        case 4053:
            DefaultToPlaceableWall(235);
            break;
        case 4054:
            DefaultToPlaceableTile((ushort)480, 0);
            width = 22;
            height = 32;
            rare = 3;
            value = sellPrice(0, 1);
            accessory = true;
            vanity = true;
            break;
        case 4055:
            DefaultToAccessory(34, 30);
            shoeSlot = 21;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4056:
            DefaultToAccessory(30, 30);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4057:
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 1));
            DefaultToGuitar();
            break;
        case 4058:
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 10));
            DefaultToBow(17, 11f);
            SetWeaponValues(8, 5f);
            break;
        case 4059:
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 30));
            SetWeaponValues(8, 4f);
            width = 16;
            height = 16;
            melee = true;
            autoReuse = true;
            useTurn = true;
            useTime = 14;
            useAnimation = 18;
            useStyle = 1;
            pick = 55;
            UseSound = SoundID.Item1;
            break;
        case 4060:
            width = 42;
            height = 20;
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 50));
            DefaultToRangedWeapon(728, AmmoID.FallenStar, 18, 20f, hasAutoReuse: true);
            SetWeaponValues(60, 5f);
            if (Variant == ItemVariants.RebalancedVariant)
            {
                damage = (int)((double)damage * 0.9);
                useTime = (int)((double)useTime * 1.1);
            }
            break;
        case 4063:
            DefaultToPlaceableTile((ushort)486, 0);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4064:
            DefaultToPlaceableTile((ushort)487, 0);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 0, 80));
            break;
        case 4065:
            DefaultToPlaceableTile((ushort)487, 1);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 1));
            break;
        case 4061:
            DefaultToSpear(730, 3.5f, 28);
            SetWeaponValues(14, 6f);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 30));
            break;
        case 4062:
            DefaultToStaff(731, 8f, 17, 7);
            SetWeaponValues(20, 3f);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 30));
            break;
        case 4066:
            DefaultToMount(15);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            break;
        case 4067:
            DefaultToMount(16);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4068:
            DefaultToCapturedCritter(583);
            rare = 1;
            value = sellPrice(0, 1);
            break;
        case 4069:
            DefaultToCapturedCritter(584);
            rare = 1;
            value = sellPrice(0, 1);
            break;
        case 4070:
            DefaultToCapturedCritter(585);
            rare = 1;
            value = sellPrice(0, 1);
            break;
        case 4071:
        case 4072:
        case 4073:
            DefaultToSeaShell();
            break;
        case 4074:
            DefaultToPlaceableTile((ushort)489, 0);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 20));
            break;
        case 4075:
            DefaultToPlaceableTile((ushort)490, 0);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 10));
            break;
        case 4076:
            rare = 3;
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 491;
            width = 12;
            height = 12;
            value = 100000;
            break;
        case 4091:
            DefaultToPlaceableTile((ushort)496, 0);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 1));
            break;
        case 4090:
            DefaultToPlaceableTile((ushort)495, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 1));
            break;
        case 4095:
            maxStack = 1;
            consumable = false;
            width = 18;
            height = 18;
            useStyle = 4;
            useTime = 10;
            UseSound = SoundID.Item128;
            useAnimation = 10;
            rare = 4;
            value = sellPrice(0, 2);
            break;
        case 4077:
            DefaultToMusicBox(43);
            break;
        case 4078:
            DefaultToMusicBox(41);
            break;
        case 4079:
            DefaultToMusicBox(42);
            break;
        case 4080:
            DefaultToMusicBox(44);
            break;
        case 4081:
            DefaultToMusicBox(45);
            break;
        case 4082:
            DefaultToMusicBox(40);
            break;
        case 4089:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 494;
            width = 12;
            height = 12;
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 1));
            break;
        case 4083:
        case 4084:
        case 4085:
        case 4086:
        case 4087:
        case 4088:
            DefaultToPlaceableTile((ushort)493, type - 4083);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 20));
            break;
        case 4096:
        case 4097:
        case 4098:
        case 4099:
        case 4100:
        case 4101:
        case 4102:
        case 4103:
        case 4104:
        case 4105:
        case 4106:
        case 4107:
        case 4108:
        case 4109:
        case 4110:
        case 4111:
        case 4112:
        case 4113:
        case 4114:
        case 4115:
        case 4116:
        case 4117:
        case 4118:
        case 4119:
        case 4120:
        case 4121:
        case 4122:
        case 4123:
        case 4124:
        case 4125:
        case 4126:
            DefaultToPlaceableTile((ushort)497, type - 4096);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4127:
            DefaultToPlaceableTile((ushort)497, type - 4096);
            maxStack = CommonMaxStack;
            value = 100000;
            break;
        case 4128:
            width = 18;
            height = 18;
            headSlot = 217;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4129:
            width = 18;
            height = 18;
            bodySlot = 210;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4130:
            width = 18;
            height = 18;
            legSlot = 180;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4131:
        case 5325:
            useStyle = 1;
            shootSpeed = 4f;
            shoot = 734;
            width = 26;
            height = 24;
            UseSound = SoundID.Item130;
            useAnimation = 28;
            useTime = 28;
            rare = 3;
            value = sellPrice(0, 2);
            break;
        case 4132:
            width = 18;
            height = 18;
            headSlot = 218;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4133:
            width = 18;
            height = 18;
            bodySlot = 211;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4134:
            width = 18;
            height = 18;
            legSlot = 184;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4135:
            width = 18;
            height = 18;
            headSlot = 219;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4136:
            width = 18;
            height = 18;
            bodySlot = 212;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4137:
            width = 18;
            height = 18;
            legSlot = 185;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4138:
            width = 18;
            height = 18;
            headSlot = 220;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4141:
            DefaultToPlaceableTile((ushort)497, 32);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4142:
            DefaultToPlaceableTile((ushort)499, 0);
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.White0, 100000);
            break;
        case 4139:
            DefaultToPlaceableTile((ushort)498, 0);
            SetShopValues(ItemRarityColor.White0, 0);
            break;
        case 4140:
            DefaultToPlaceableWall(236);
            SetShopValues(ItemRarityColor.White0, 0);
            break;
        case 4143:
            width = 12;
            height = 12;
            break;
        case 4144:
            width = 14;
            height = 38;
            useAnimation = 25;
            useTime = 15;
            useStyle = 5;
            rare = 2;
            noUseGraphic = true;
            channel = true;
            noMelee = true;
            damage = 17;
            knockBack = 3f;
            autoReuse = false;
            noMelee = true;
            melee = true;
            shoot = 735;
            shootSpeed = 15f;
            value = sellPrice(0, 5);
            break;
        case 4145:
            DefaultToPlaceableTile((ushort)90, 34);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4146:
            DefaultToPlaceableTile((ushort)79, 34);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 4147:
            DefaultToPlaceableTile((ushort)101, 35);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4148:
            DefaultToPlaceableTile((ushort)88, 34);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4149:
            DefaultToPlaceableTile((ushort)100, 34);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4150:
            DefaultToPlaceableTile((ushort)33, 33);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 4151:
            DefaultToPlaceableTile((ushort)15, 39);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 4152:
            DefaultToPlaceableTile((ushort)34, 40);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 4153:
            DefaultToPlaceableTile((ushort)467, 5);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4154:
            DefaultToPlaceableTile((ushort)104, 35);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4155:
            DefaultToPlaceableTile((ushort)10, 39);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 4156:
            DefaultToPlaceableTile((ushort)93, 34);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 4157:
            DefaultToPlaceableTile((ushort)42, 40);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 4158:
            DefaultToPlaceableTile((ushort)87, 34);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4159:
            DefaultToPlaceableTile((ushort)19, 38);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 4160:
            DefaultToPlaceableTile((ushort)172, 35);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4161:
            DefaultToPlaceableTile((ushort)89, 37);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4162:
            DefaultToPlaceableTile((ushort)469, 3);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 4163:
            DefaultToPlaceableTile((ushort)18, 35);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 4164:
            DefaultToPlaceableTile((ushort)468, 5);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4165:
            DefaultToPlaceableTile((ushort)497, 33);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4166:
            DefaultToPlaceableTile((ushort)90, 35);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4167:
            DefaultToPlaceableTile((ushort)79, 35);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 4168:
            DefaultToPlaceableTile((ushort)101, 36);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4169:
            DefaultToPlaceableTile((ushort)88, 35);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4170:
            DefaultToPlaceableTile((ushort)100, 35);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4171:
            DefaultToPlaceableTile((ushort)33, 34);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 4172:
            DefaultToPlaceableTile((ushort)15, 40);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 4173:
            DefaultToPlaceableTile((ushort)34, 41);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 4174:
            DefaultToPlaceableTile((ushort)467, 6);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4175:
            DefaultToPlaceableTile((ushort)104, 36);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4176:
            DefaultToPlaceableTile((ushort)10, 40);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 4177:
            DefaultToPlaceableTile((ushort)93, 35);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 4178:
            DefaultToPlaceableTile((ushort)42, 41);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 4179:
            DefaultToPlaceableTile((ushort)87, 35);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4180:
            DefaultToPlaceableTile((ushort)19, 39);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 4181:
            DefaultToPlaceableTile((ushort)172, 36);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4182:
            DefaultToPlaceableTile((ushort)89, 38);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4183:
            DefaultToPlaceableTile((ushort)469, 4);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 4184:
            DefaultToPlaceableTile((ushort)18, 36);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 4185:
            DefaultToPlaceableTile((ushort)468, 6);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4186:
            DefaultToPlaceableTile((ushort)497, 34);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4187:
            DefaultToPlaceableTile((ushort)90, 36);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4188:
            DefaultToPlaceableTile((ushort)79, 36);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 4189:
            DefaultToPlaceableTile((ushort)101, 37);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4190:
            DefaultToPlaceableTile((ushort)88, 36);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4191:
            DefaultToPlaceableTile((ushort)100, 36);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4192:
            DefaultToPlaceableTile((ushort)33, 35);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 4193:
            DefaultToPlaceableTile((ushort)15, 41);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 4194:
            DefaultToPlaceableTile((ushort)34, 42);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 4195:
            DefaultToPlaceableTile((ushort)467, 7);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4196:
            DefaultToPlaceableTile((ushort)104, 37);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4197:
            DefaultToPlaceableTile((ushort)10, 41);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 4198:
            DefaultToPlaceableTile((ushort)93, 36);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 4199:
            DefaultToPlaceableTile((ushort)42, 42);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 4200:
            DefaultToPlaceableTile((ushort)87, 36);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4201:
            DefaultToPlaceableTile((ushort)19, 40);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 4202:
            DefaultToPlaceableTile((ushort)172, 37);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4203:
            DefaultToPlaceableTile((ushort)89, 39);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4204:
            DefaultToPlaceableTile((ushort)469, 5);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 4205:
            DefaultToPlaceableTile((ushort)18, 37);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 4206:
            DefaultToPlaceableTile((ushort)468, 7);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4207:
            DefaultToPlaceableTile((ushort)497, 35);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4208:
            DefaultToPlaceableTile((ushort)90, 37);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4209:
            DefaultToPlaceableTile((ushort)79, 37);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 4210:
            DefaultToPlaceableTile((ushort)101, 38);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4211:
            DefaultToPlaceableTile((ushort)88, 37);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4212:
            DefaultToPlaceableTile((ushort)100, 37);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4213:
            DefaultToPlaceableTile((ushort)33, 36);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 4214:
            DefaultToPlaceableTile((ushort)15, 42);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 4215:
            DefaultToPlaceableTile((ushort)34, 43);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 4216:
            DefaultToPlaceableTile((ushort)467, 8);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4217:
            DefaultToPlaceableTile((ushort)104, 38);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4218:
            DefaultToPlaceableTile((ushort)10, 42);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 4219:
            DefaultToPlaceableTile((ushort)93, 37);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 4220:
            DefaultToPlaceableTile((ushort)42, 43);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 4221:
            DefaultToPlaceableTile((ushort)87, 37);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4222:
            DefaultToPlaceableTile((ushort)19, 41);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 4223:
            DefaultToPlaceableTile((ushort)172, 38);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4224:
            DefaultToPlaceableTile((ushort)89, 40);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4225:
            DefaultToPlaceableTile((ushort)469, 6);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 4226:
            DefaultToPlaceableTile((ushort)18, 38);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 4227:
            DefaultToPlaceableTile((ushort)468, 8);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4228:
            DefaultToPlaceableTile((ushort)497, 36);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4229:
            DefaultToPlaceableTile((ushort)500, 0);
            break;
        case 4230:
            DefaultToPlaceableTile((ushort)501, 0);
            break;
        case 4231:
            DefaultToPlaceableTile((ushort)502, 0);
            break;
        case 4232:
            DefaultToPlaceableTile((ushort)503, 0);
            break;
        case 4233:
            DefaultToPlaceableWall(237);
            break;
        case 4234:
            DefaultToPlaceableWall(238);
            break;
        case 4235:
            DefaultToPlaceableWall(239);
            break;
        case 4236:
            DefaultToPlaceableWall(240);
            break;
        case 4237:
            DefaultToMusicBox(46);
            break;
        case 4238:
            DefaultToPlaceableTile((ushort)481, 0);
            break;
        case 4239:
            DefaultToPlaceableTile((ushort)482, 0);
            break;
        case 4240:
            DefaultToPlaceableTile((ushort)483, 0);
            break;
        case 4242:
            DefaultToGolfBall(739);
            break;
        case 4243:
            DefaultToGolfBall(740);
            break;
        case 4244:
            DefaultToGolfBall(741);
            break;
        case 4245:
            DefaultToGolfBall(742);
            break;
        case 4246:
            DefaultToGolfBall(743);
            break;
        case 4247:
            DefaultToGolfBall(744);
            break;
        case 4248:
            DefaultToGolfBall(745);
            break;
        case 4249:
            DefaultToGolfBall(746);
            break;
        case 4250:
            DefaultToGolfBall(747);
            break;
        case 4251:
            DefaultToGolfBall(748);
            break;
        case 4252:
            DefaultToGolfBall(749);
            break;
        case 4253:
            DefaultToGolfBall(750);
            break;
        case 4254:
            DefaultToGolfBall(751);
            break;
        case 4255:
            DefaultToGolfBall(752);
            break;
        case 4257:
            noUseGraphic = true;
            damage = 0;
            knockBack = 7f;
            useStyle = 5;
            shootSpeed = 12.5f;
            shoot = 753;
            width = 18;
            height = 28;
            UseSound = SoundID.Item1;
            useAnimation = 20;
            useTime = 20;
            rare = 1;
            noMelee = true;
            value = 20000;
            break;
        case 4256:
            defense = 3;
            width = 18;
            height = 14;
            bodySlot = 213;
            value = sellPrice(0, 0, 50) * 6;
            rare = 2;
            break;
        case 4258:
            useStyle = 1;
            useTime = 18;
            useAnimation = 18;
            knockBack = 3f;
            width = 40;
            height = 40;
            damage = 26;
            scale = 1f;
            UseSound = SoundID.Item15;
            rare = 1;
            value = 27000;
            melee = true;
            break;
        case 4259:
            SetDefaults(198);
            this.type = type;
            damage = 48;
            useTime = 16;
            useAnimation = 16;
            scale = 1f;
            autoReuse = true;
            useTurn = true;
            rare = 4;
            value = sellPrice(0, 1);
            break;
        case 4260:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 7;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createWall = 241;
            width = 12;
            height = 12;
            value = sellPrice(0, 0, 1, 60);
            break;
        case 4261:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 135;
            width = 12;
            height = 12;
            placeStyle = 7;
            mech = true;
            value = 5000;
            break;
        case 4262:
            useTurn = true;
            width = 20;
            height = 20;
            useStyle = 5;
            useTime = 90;
            UseSound = SoundID.Item151;
            useAnimation = 90;
            rare = 1;
            value = 50000;
            shoot = 754;
            break;
        case 4263:
            useTurn = true;
            width = 20;
            height = 20;
            useStyle = 4;
            useTime = 90;
            UseSound = SoundID.Item6;
            useAnimation = 90;
            rare = 1;
            value = 50000;
            break;
        case 4264:
            useStyle = 4;
            channel = true;
            width = 34;
            height = 34;
            UseSound = SoundID.Item25;
            useAnimation = 20;
            useTime = 20;
            rare = 8;
            noMelee = true;
            mountType = 17;
            value = sellPrice(0, 10);
            break;
        case 4265:
            DefaultToPlaceableTile((ushort)467, 9);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 3));
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4266:
            DefaultToPlaceableTile((ushort)468, 9);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4267:
            DefaultToPlaceableTile((ushort)467, 10);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4268:
            DefaultToPlaceableTile((ushort)468, 10);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4269:
            mana = 10;
            damage = 35;
            useStyle = 1;
            shootSpeed = 10f;
            shoot = 755;
            buffType = 213;
            width = 26;
            height = 28;
            UseSound = SoundID.Item83;
            useAnimation = 36;
            useTime = 36;
            rare = 4;
            noMelee = true;
            knockBack = 3f;
            value = sellPrice(0, 5);
            summon = true;
            autoReuse = true;
            reuseDelay = 2;
            break;
        case 4270:
            mana = 20;
            damage = 34;
            useStyle = 4;
            shootSpeed = 32f;
            shoot = 756;
            width = 26;
            height = 28;
            useAnimation = 33;
            useTime = 11;
            rare = 4;
            noMelee = true;
            knockBack = 1f;
            value = sellPrice(0, 4);
            magic = true;
            autoReuse = true;
            break;
        case 4271:
            useStyle = 4;
            width = 22;
            height = 14;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            maxStack = CommonMaxStack;
            rare = 2;
            break;
        case 4272:
            noMelee = true;
            useStyle = 5;
            useAnimation = 40;
            useTime = 40;
            knockBack = 6.5f;
            width = 30;
            height = 10;
            damage = 55;
            scale = 1.1f;
            noUseGraphic = true;
            shoot = 757;
            shootSpeed = 15.9f;
            UseSound = SoundID.Item1;
            rare = 4;
            value = sellPrice(0, 4);
            melee = true;
            channel = true;
            break;
        case 4273:
            mana = 10;
            damage = 11;
            useStyle = 1;
            shootSpeed = 10f;
            shoot = 758;
            width = 26;
            height = 28;
            UseSound = SoundID.Item44;
            useAnimation = 36;
            useTime = 36;
            noMelee = true;
            knockBack = 5f;
            buffType = 214;
            value = sellPrice(0, 1);
            rare = 3;
            summon = true;
            autoReuse = true;
            reuseDelay = 2;
            break;
        case 4274:
            useStyle = 1;
            autoReuse = true;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            noUseGraphic = true;
            value = sellPrice(0, 10);
            rare = 3;
            makeNPC = 592;
            break;
        case 4275:
            width = 18;
            height = 18;
            headSlot = 221;
            value = sellPrice(0, 10);
            rare = 3;
            vanity = true;
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 505;
            width = 12;
            height = 12;
            break;
        case 4276:
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 506;
            width = 20;
            height = 20;
            break;
        case 4277:
            DefaultToPlaceableTile((ushort)507, 0);
            break;
        case 4278:
            DefaultToPlaceableTile((ushort)508, 0);
            break;
        case 4279:
            DefaultToPlaceableWall(242);
            break;
        case 4280:
            DefaultToPlaceableWall(243);
            break;
        case 4281:
            mana = 10;
            damage = 7;
            useStyle = 1;
            shootSpeed = 10f;
            shoot = 759;
            buffType = 216;
            width = 26;
            height = 28;
            UseSound = SoundID.Item44;
            useAnimation = 36;
            useTime = 36;
            rare = 1;
            noMelee = true;
            knockBack = 4f;
            value = sellPrice(0, 1);
            summon = true;
            autoReuse = true;
            reuseDelay = 2;
            break;
        case 4298:
            DefaultToPlaceableTile((ushort)90, 38);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4299:
            DefaultToPlaceableTile((ushort)79, 38);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 4300:
            DefaultToPlaceableTile((ushort)101, 39);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4301:
            DefaultToPlaceableTile((ushort)88, 38);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4302:
            DefaultToPlaceableTile((ushort)100, 38);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4303:
            DefaultToPlaceableTile((ushort)33, 37);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 4304:
            DefaultToPlaceableTile((ushort)15, 43);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 4305:
            DefaultToPlaceableTile((ushort)34, 44);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 4306:
            DefaultToPlaceableTile((ushort)104, 39);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4307:
            DefaultToPlaceableTile((ushort)10, 43);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 4308:
            DefaultToPlaceableTile((ushort)93, 38);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 4309:
            DefaultToPlaceableTile((ushort)42, 44);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 4310:
            DefaultToPlaceableTile((ushort)87, 38);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4311:
            DefaultToPlaceableTile((ushort)19, 42);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 4312:
            DefaultToPlaceableTile((ushort)172, 39);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4313:
            DefaultToPlaceableTile((ushort)89, 41);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4314:
            DefaultToPlaceableTile((ushort)469, 7);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 4315:
            DefaultToPlaceableTile((ushort)18, 39);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 4316:
            DefaultToPlaceableTile((ushort)497, 37);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4317:
            SetShopValues(ItemRarityColor.LightRed4, sellPrice(0, 2));
            SetWeaponValues(30, 7f);
            melee = true;
            autoReuse = true;
            useTime = 11;
            useAnimation = 27;
            useStyle = 1;
            hammer = 80;
            axe = 30;
            UseSound = SoundID.Item1;
            width = 20;
            height = 20;
            break;
        case 4318:
            DefaultToPlaceableTile((ushort)509, 0);
            width = 22;
            height = 32;
            rare = 9;
            value = sellPrice(0, 25);
            accessory = true;
            vanity = true;
            break;
        case 4319:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 510;
            width = 28;
            height = 28;
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 20));
            break;
        case 4320:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 511;
            width = 28;
            height = 28;
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 20));
            break;
        case 4321:
            width = 18;
            height = 18;
            bodySlot = 214;
            rare = 3;
            vanity = true;
            value = buyPrice(0, 5);
            break;
        case 4322:
            width = 18;
            height = 18;
            legSlot = 188;
            rare = 3;
            vanity = true;
            value = buyPrice(0, 5);
            break;
        case 4323:
            width = 18;
            height = 18;
            headSlot = 222;
            rare = 3;
            vanity = true;
            value = buyPrice(0, 50);
            break;
        case 4324:
            width = 18;
            height = 14;
            bodySlot = 215;
            value = buyPrice(0, 50);
            rare = 3;
            vanity = true;
            break;
        case 4325:
            useStyle = 1;
            useAnimation = 8;
            useTime = 8;
            width = 24;
            height = 28;
            UseSound = SoundID.Item1;
            shoot = 760;
            fishingPole = 25;
            shootSpeed = 15f;
            rare = 2;
            value = sellPrice(0, 2);
            break;
        case 4326:
            DefaultToPlaceableTile((ushort)520, 0);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4327:
        case 4328:
        case 4329:
        case 4330:
        case 4331:
        case 4332:
            DefaultToPlaceableTile((ushort)(type - 4327 + 521));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4333:
            DefaultToPlaceableTile((ushort)527, 0);
            value = sellPrice(0, 10);
            rare = 3;
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4334:
        case 4335:
        case 4336:
        case 4337:
        case 4338:
        case 4339:
            DefaultToCapturedCritter((short)(type - 4334 + 595));
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 10));
            width = 20;
            height = 20;
            bait = 20;
            break;
        case 4340:
            DefaultToCapturedCritter(601);
            value = sellPrice(0, 10);
            rare = 3;
            width = 20;
            height = 20;
            bait = 50;
            break;
        case 4341:
            DefaultToAccessory(30, 30);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            break;
        case 4342:
            DefaultToPlaceableTile((ushort)105, 78);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4343:
            width = 22;
            height = 16;
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 10));
            DefaultToThrownWeapon(761, 17, 5f);
            SetWeaponValues(4, 2f);
            break;
        case 4344:
            width = 22;
            height = 16;
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 10));
            DefaultToThrownWeapon(762, 17, 5f);
            SetWeaponValues(4, 2f);
            break;
        case 4345:
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 5));
            maxStack = CommonMaxStack;
            width = 12;
            height = 12;
            break;
        case 4346:
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
            width = 30;
            height = 30;
            break;
        case 4347:
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 17));
            DefaultToMagicWeapon(876, 36, 15f);
            mana = 16;
            width = 40;
            height = 40;
            knockBack = 6f;
            scale = 0.75f;
            damage = 42;
            UseSound = SoundID.Item158;
            break;
        case 4348:
            SetShopValues(ItemRarityColor.Pink5, buyPrice(0, 50));
            DefaultToMagicWeapon(876, 36, 15f);
            mana = 16;
            width = 40;
            height = 40;
            knockBack = 6f;
            scale = 0.75f;
            damage = 100;
            UseSound = SoundID.Item158;
            break;
        case 4349:
        case 4350:
        case 4351:
        case 4352:
        case 4353:
            DefaultToPlaceableTile(179 + type - 4349);
            break;
        case 4354:
            DefaultToPlaceableTile((ushort)381, 0);
            rare = 1;
            break;
        case 4355:
            DefaultToPlaceableTile((ushort)531, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4356:
            DefaultToMusicBox(47);
            break;
        case 4357:
            DefaultToMusicBox(48);
            break;
        case 4358:
            DefaultToMusicBox(49);
            break;
        case 4359:
            DefaultToCapturedCritter(602);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 7, 50));
            width = 20;
            height = 20;
            break;
        case 4360:
            DefaultToPlaceableTile((ushort)105, 77);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4361:
            DefaultToCapturedCritter(604);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 10));
            width = 20;
            height = 20;
            bait = 17;
            break;
        case 4362:
            DefaultToCapturedCritter(605);
            value = sellPrice(0, 10);
            rare = 3;
            width = 20;
            height = 20;
            bait = 50;
            break;
        case 4363:
            DefaultToCapturedCritter(606);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 5));
            width = 12;
            height = 12;
            bait = 22;
            break;
        case 4364:
            DefaultToPlaceableTile((ushort)532, 0);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4365:
            DefaultToVanitypet(764, 217);
            SetShopValues(ItemRarityColor.Pink5, buyPrice(1));
            break;
        case 4366:
            DefaultToVanitypet(765, 218);
            break;
        case 4372:
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 1));
            DefaultToGuitar();
            break;
        case 4367:
        case 4368:
        case 4369:
        case 4370:
        case 4371:
            DefaultTokite(type - 4367 + 766);
            break;
        case 4373:
            DefaultToCapturedCritter(607);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 7, 50));
            width = 12;
            height = 12;
            break;
        case 4374:
            DefaultToCapturedCritter(608);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 7, 50));
            width = 12;
            height = 12;
            break;
        case 4375:
            DefaultToCapturedCritter(610);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 10));
            width = 12;
            height = 12;
            break;
        case 4376:
            DefaultToPlaceableTile((ushort)533, 0);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4377:
            DefaultToPlaceableTile((ushort)534, 0);
            rare = 1;
            break;
        case 4378:
            DefaultToPlaceableTile((ushort)536, 0);
            rare = 1;
            break;
        case 4389:
            DefaultToPlaceableTile((ushort)539, 0);
            rare = 1;
            break;
        case 4379:
            DefaultTokite(771);
            break;
        case 4380:
            DefaultToPlaceableTile((ushort)538, 0);
            maxStack = CommonMaxStack;
            break;
        case 4382:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            rare = 2;
            break;
        case 4383:
            DefaultToTorch(16);
            break;
        case 4384:
            DefaultToTorch(17, allowWaterPlacement: true);
            break;
        case 4385:
            DefaultToTorch(18);
            break;
        case 4386:
            DefaultToTorch(19);
            break;
        case 4387:
            DefaultToTorch(20);
            break;
        case 4388:
            DefaultToTorch(21);
            break;
        case 4390:
            DefaultToPlaceableTile((ushort)484, 0);
            break;
        case 4391:
            DefaultToPlaceableTile((ushort)162, 0);
            break;
        case 4392:
            DefaultToPlaceableTile((ushort)541, 0);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 10));
            break;
        case 4393:
        case 4394:
            DefaultToQuestFish();
            break;
        case 4395:
            DefaultToCapturedCritter(611);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 10));
            width = 12;
            height = 12;
            break;
        case 4396:
            DefaultToPlaceableTile((ushort)542, 0);
            maxStack = CommonMaxStack;
            break;
        case 4397:
            DefaultToPlaceableTile((ushort)105, 76);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4398:
            DefaultToPlaceableTile((ushort)543, 0);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            value = sellPrice(0, 0, 20);
            break;
        case 4399:
            DefaultToPlaceableTile((ushort)544, 0);
            value = sellPrice(0, 10);
            rare = 3;
            maxStack = CommonMaxStack;
            break;
        case 4400:
            useStyle = 1;
            shootSpeed = 7f;
            shoot = 772;
            width = 22;
            height = 22;
            UseSound = SoundID.Item1;
            useAnimation = 15;
            noUseGraphic = true;
            useTime = 15;
            rare = 2;
            value = sellPrice(0, 0, 5);
            consumable = true;
            maxStack = CommonMaxStack;
            break;
        case 4401:
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 7, 50));
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 4402:
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 50));
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 4404:
            DefaultToAccessory(20, 12);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 1));
            hasVanityEffects = true;
            break;
        case 4405:
        case 4406:
        case 4407:
        case 4408:
            DefaultToPlaceableTile((ushort)376, 18 + type - 4405);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 1));
            maxStack = CommonMaxStack;
            break;
        case 4409:
            DefaultToAccessory(28);
            faceSlot = 14;
            SetShopValues(ItemRarityColor.Pink5, buyPrice(0, 10));
            break;
        case 4410:
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 1));
            maxStack = CommonMaxStack;
            width = 32;
            height = 22;
            break;
        case 4412:
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            maxStack = CommonMaxStack;
            width = 22;
            height = 22;
            break;
        case 4413:
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 3));
            maxStack = CommonMaxStack;
            width = 22;
            height = 22;
            break;
        case 4414:
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 15));
            maxStack = CommonMaxStack;
            width = 22;
            height = 22;
            break;
        case 4418:
            DefaultToCapturedCritter(612);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 10));
            width = 20;
            height = 20;
            bait = 17;
            break;
        case 4419:
            DefaultToCapturedCritter(613);
            value = sellPrice(0, 10);
            rare = 3;
            width = 20;
            height = 20;
            bait = 50;
            break;
        case 4415:
            DefaultToPlaceableTile((ushort)10, 44);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 40));
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 4416:
            DefaultToPlaceableTile((ushort)19, 43);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 4417:
            DefaultToPlaceableTile((ushort)207, 9);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 4));
            width = 8;
            height = 10;
            break;
        case 4420:
            DefaultToPlaceableTile((ushort)545, 0);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 5));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4421:
            DefaultToMusicBox(50);
            break;
        case 4422:
            DefaultToPlaceableTile((ushort)546, 0);
            break;
        case 4423:
            useStyle = 1;
            shootSpeed = 5f;
            shoot = 773;
            width = 20;
            height = 20;
            maxStack = CommonMaxStack;
            UseSound = SoundID.Item1;
            consumable = true;
            useAnimation = 25;
            noUseGraphic = true;
            useTime = 25;
            value = sellPrice(0, 0, 3);
            rare = 1;
            break;
        case 4424:
            DefaultToPlaceableWall(245);
            break;
        case 4425:
            DefaultToVanitypet(774, 219);
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 1));
            break;
        case 4426:
            DefaultToMount(18);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4427:
            DefaultToMount(19);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            break;
        case 4428:
            DefaultToMount(20);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4429:
            DefaultToMount(21);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            break;
        case 4430:
            DefaultToPlaceableTile((ushort)547, 0);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4431:
            DefaultToPlaceableTile((ushort)547, 1);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4432:
            DefaultToPlaceableTile((ushort)547, 2);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4433:
            DefaultToPlaceableTile((ushort)547, 3);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4434:
            DefaultToPlaceableTile((ushort)547, 4);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4435:
            DefaultToPlaceableTile((ushort)548, 0);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4436:
            DefaultToPlaceableTile((ushort)548, 1);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4437:
            DefaultToPlaceableTile((ushort)548, 2);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4438:
            DefaultToPlaceableTile((ushort)548, 3);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4439:
            DefaultToPlaceableTile((ushort)548, 4);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4440:
            DefaultToPlaceableTile((ushort)548, 5);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4441:
            DefaultToPlaceableTile((ushort)548, 6);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 3));
            break;
        case 4442:
            useStyle = 1;
            useAnimation = 8;
            useTime = 8;
            width = 24;
            height = 28;
            UseSound = SoundID.Item1;
            shoot = 775;
            fishingPole = 30;
            shootSpeed = 15f;
            rare = 1;
            value = sellPrice(0, 2);
            break;
        case 4443:
            DefaultToMount(22);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4444:
            useStyle = 4;
            channel = true;
            width = 34;
            height = 34;
            UseSound = SoundID.Item25;
            useAnimation = 20;
            useTime = 20;
            rare = 8;
            noMelee = true;
            mountType = 23;
            value = sellPrice(0, 5);
            expert = true;
            break;
        case 4445:
            damage = 50;
            width = 20;
            height = 14;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Rocket;
            knockBack = 4f;
            value = buyPrice(0, 0, 7, 50);
            ranged = true;
            break;
        case 4446:
            damage = 50;
            width = 20;
            height = 14;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Rocket;
            knockBack = 4f;
            value = buyPrice(0, 0, 15);
            ranged = true;
            break;
        case 4447:
            damage = 40;
            width = 20;
            height = 14;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Rocket;
            knockBack = 4f;
            value = sellPrice(0, 0, 10);
            ranged = true;
            break;
        case 4448:
            damage = 40;
            width = 20;
            height = 14;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Rocket;
            knockBack = 4f;
            value = sellPrice(0, 0, 10);
            ranged = true;
            break;
        case 4449:
            damage = 40;
            width = 20;
            height = 14;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Rocket;
            knockBack = 4f;
            value = sellPrice(0, 0, 10);
            ranged = true;
            break;
        case 4450:
            DefaultToMount(24);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4451:
            DefaultToMount(25);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4452:
            DefaultToMount(26);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4453:
            DefaultToMount(27);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4454:
            DefaultToMount(28);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4455:
            DefaultToMount(29);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4456:
            DefaultToMount(30);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4457:
            damage = 75;
            width = 20;
            height = 14;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Rocket;
            knockBack = 4f;
            value = buyPrice(0, 0, 5);
            ranged = true;
            break;
        case 4458:
            damage = 75;
            width = 20;
            height = 14;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Rocket;
            knockBack = 4f;
            value = buyPrice(0, 0, 10);
            ranged = true;
            break;
        case 4459:
            damage = 40;
            width = 20;
            height = 14;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Rocket;
            knockBack = 4f;
            value = buyPrice(0, 0, 50);
            ranged = true;
            break;
        case 4460:
            tileWand = 169;
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            createTile = 552;
            width = 8;
            height = 10;
            rare = 1;
            value = sellPrice(0, 1);
            break;
        case 4463:
            autoReuse = false;
            useStyle = 13;
            useAnimation = 21;
            useTime = 7;
            width = 50;
            height = 18;
            shoot = 802;
            UseSound = SoundID.Item1;
            damage = 15;
            shootSpeed = 2.4f;
            noMelee = true;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 30));
            melee = true;
            knockBack = 3f;
            noUseGraphic = true;
            break;
        case 4464:
            DefaultToCapturedCritter(616);
            value = sellPrice(0, 0, 10);
            break;
        case 4465:
            DefaultToCapturedCritter(617);
            value = sellPrice(0, 0, 10);
            break;
        case 4466:
            DefaultToPlaceableTile((ushort)105, 79);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4461:
            DefaultToPlaceableTile((ushort)550, 0);
            maxStack = CommonMaxStack;
            break;
        case 4462:
            DefaultToPlaceableTile((ushort)551, 0);
            maxStack = CommonMaxStack;
            break;
        case 4467:
            DefaultToMount(31);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4473:
            DefaultToPlaceableTile((ushort)553, 0);
            maxStack = CommonMaxStack;
            break;
        case 4474:
            DefaultToPlaceableTile((ushort)554, 0);
            maxStack = CommonMaxStack;
            break;
        case 4475:
            DefaultToPlaceableTile((ushort)555, 0);
            maxStack = CommonMaxStack;
            break;
        case 4476:
            DefaultToPlaceableTile((ushort)556, 0);
            maxStack = CommonMaxStack;
            value = sellPrice(0, 10);
            rare = 3;
            break;
        case 4468:
            DefaultToMount(32);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 4));
            break;
        case 4469:
            DefaultToMount(33);
            SetShopValues(ItemRarityColor.StrongRed10, sellPrice(0, 10));
            break;
        case 4470:
            DefaultToMount(34);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4471:
            DefaultToMount(35);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4472:
            DefaultToMount(36);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4477:
            UseSound = SoundID.Item3;
            useStyle = 9;
            useTurn = true;
            useAnimation = 17;
            useTime = 17;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 14;
            height = 24;
            buffType = 257;
            buffTime = 18000;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4478:
            UseSound = SoundID.Item3;
            useStyle = 9;
            useTurn = true;
            useAnimation = 17;
            useTime = 17;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 14;
            height = 24;
            buffType = 257;
            buffTime = 36000;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 5));
            break;
        case 4479:
            UseSound = SoundID.Item3;
            useStyle = 9;
            useTurn = true;
            useAnimation = 17;
            useTime = 17;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 14;
            height = 24;
            buffType = 257;
            buffTime = 54000;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 25));
            break;
        case 4480:
            DefaultToCapturedCritter(626);
            value = sellPrice(0, 0, 15);
            break;
        case 4481:
            DefaultToPlaceableTile((ushort)558, 0);
            maxStack = CommonMaxStack;
            break;
        case 4482:
            DefaultToCapturedCritter(627);
            value = sellPrice(0, 10);
            rare = 3;
            break;
        case 4483:
            DefaultToPlaceableTile((ushort)559, 0);
            value = sellPrice(0, 10);
            rare = 3;
            maxStack = CommonMaxStack;
            break;
        case 4484:
        case 4485:
            mech = true;
            noWet = true;
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 144;
            placeStyle = type - 4484 + 3;
            width = 10;
            height = 12;
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 2));
            break;
        case 4541:
        case 4542:
        case 4543:
        case 4544:
        case 4545:
        case 4546:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 91;
            placeStyle = 288 + (type - 4541);
            width = 10;
            height = 24;
            value = 1000;
            rare = 1;
            break;
        case 4486:
        case 4487:
        case 4488:
        case 4489:
        case 4490:
        case 4491:
        case 4492:
        case 4493:
        case 4494:
        case 4495:
        case 4496:
        case 4497:
        case 4498:
        case 4499:
        case 4500:
        case 4501:
        case 4502:
        case 4503:
            DefaultToPlaceableWall((ushort)(246 + type - 4486));
            break;
        case 4504:
        case 4505:
            DefaultToPlaceableWall((ushort)(264 + type - 4504));
            value = 250;
            break;
        case 4506:
        case 4507:
            DefaultToPlaceableWall((ushort)(266 + type - 4506));
            break;
        case 4508:
            DefaultToPlaceableWall((ushort)(268 + type - 4508));
            value = 250;
            break;
        case 4509:
        case 4510:
        case 4511:
            DefaultToPlaceableWall((ushort)(269 + type - 4509));
            break;
        case 4512:
            DefaultToPlaceableWall(274);
            break;
        case 4513:
        case 4514:
        case 4515:
        case 4516:
        case 4517:
        case 4518:
        case 4519:
        case 4520:
        case 4521:
        case 4522:
        case 4523:
        case 4524:
        case 4525:
        case 4526:
        case 4527:
        case 4528:
        case 4529:
        case 4530:
        case 4531:
        case 4532:
        case 4533:
        case 4534:
        case 4535:
        case 4536:
        case 4537:
        case 4538:
        case 4539:
        case 4540:
            DefaultToPlaceableWall((ushort)(276 + type - 4513));
            break;
        case 4599:
        case 4600:
        case 4601:
            DefaultToPlaceableTile((ushort)560, type - 4599);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 1));
            maxStack = CommonMaxStack;
            break;
        case 4587:
        case 4588:
        case 4589:
        case 4590:
            DefaultToGolfClub(20, 20);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 10));
            break;
        case 4591:
        case 4592:
        case 4593:
        case 4594:
            DefaultToGolfClub(20, 20);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 10));
            break;
        case 4595:
        case 4596:
        case 4597:
        case 4598:
            DefaultToGolfClub(20, 20);
            SetShopValues(ItemRarityColor.LightRed4, buyPrice(0, 25));
            break;
        case 4602:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 91;
            placeStyle = 294;
            width = 10;
            height = 24;
            value = 1000;
            rare = 1;
            break;
        case 4606:
            DefaultToMusicBox(51);
            break;
        case 4603:
            DefaultToVanitypet(815, 258);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(1));
            break;
        case 4604:
            DefaultToVanitypet(816, 259);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(1));
            break;
        case 4605:
            DefaultToVanitypet(817, 260);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(1));
            break;
        case 4566:
            DefaultToPlaceableTile((ushort)90, 39);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4567:
            DefaultToPlaceableTile((ushort)79, 39);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 4568:
            DefaultToPlaceableTile((ushort)101, 40);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4569:
            DefaultToPlaceableTile((ushort)88, 39);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4570:
            DefaultToPlaceableTile((ushort)100, 39);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4571:
            DefaultToPlaceableTile((ushort)33, 38);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 4572:
            DefaultToPlaceableTile((ushort)15, 44);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 4573:
            DefaultToPlaceableTile((ushort)34, 45);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 4574:
            DefaultToPlaceableTile((ushort)467, 11);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4575:
            DefaultToPlaceableTile((ushort)104, 40);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4576:
            DefaultToPlaceableTile((ushort)10, 45);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 4577:
            DefaultToPlaceableTile((ushort)93, 39);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 4578:
            DefaultToPlaceableTile((ushort)42, 45);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 4579:
            DefaultToPlaceableTile((ushort)87, 39);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4580:
            DefaultToPlaceableTile((ushort)19, 44);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 4581:
            DefaultToPlaceableTile((ushort)172, 40);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4582:
            DefaultToPlaceableTile((ushort)89, 42);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4583:
            DefaultToPlaceableTile((ushort)469, 8);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 4584:
            DefaultToPlaceableTile((ushort)18, 40);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 4586:
            DefaultToPlaceableTile((ushort)497, 38);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 4585:
            DefaultToPlaceableTile((ushort)468, 11);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4554:
            DefaultToPlaceableTile((ushort)561, 0);
            break;
        case 4564:
            DefaultToPlaceableTile((ushort)562, 0);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 1));
            break;
        case 4565:
            DefaultToPlaceableWall(312);
            break;
        case 4547:
            DefaultToPlaceableTile((ushort)563, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 20));
            break;
        case 4548:
            DefaultToPlaceableWall(313);
            break;
        case 4607:
            mana = 10;
            damage = 41;
            useStyle = 1;
            shootSpeed = 10f;
            shoot = 831;
            buffType = 263;
            width = 26;
            height = 28;
            UseSound = SoundID.Item44;
            useAnimation = 36;
            useTime = 36;
            rare = 8;
            noMelee = true;
            knockBack = 4f;
            value = sellPrice(0, 20);
            summon = true;
            autoReuse = true;
            reuseDelay = 2;
            break;
        case 4381:
            DefaultToBow(19, 9f, hasAutoReuse: true);
            SetWeaponValues(14, 3f);
            value = sellPrice(0, 1);
            rare = 3;
            break;
        case 4549:
            width = 18;
            height = 18;
            headSlot = 223;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4560:
            width = 18;
            height = 18;
            headSlot = 224;
            rare = 1;
            vanity = true;
            value = buyPrice(0, 3);
            break;
        case 4561:
            width = 18;
            height = 18;
            headSlot = 225;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4563:
            DefaultToAccessory(18, 18);
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            hasVanityEffects = true;
            break;
        case 4562:
            width = 18;
            height = 18;
            headSlot = 226;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4555:
            width = 18;
            height = 18;
            headSlot = 227;
            rare = 0;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4556:
            width = 18;
            height = 18;
            bodySlot = 216;
            rare = 0;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4557:
            width = 18;
            height = 18;
            legSlot = 190;
            rare = 0;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4553:
            DefaultToPlaceableTile((ushort)564, 0);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
            break;
        case 4551:
            DefaultToVanitypet(821, 261);
            break;
        case 4609:
            DefaultToPlaceableTile((ushort)567, 0);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 4608:
            useStyle = 1;
            shootSpeed = 7f;
            shoot = 820;
            width = 18;
            height = 20;
            maxStack = CommonMaxStack;
            consumable = true;
            UseSound = SoundID.Item1;
            useAnimation = 19;
            useTime = 19;
            noMelee = true;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 5));
            break;
        case 4610:
            DefaultTokite(822);
            break;
        case 4611:
            DefaultTokite(823);
            break;
        case 4612:
            DefaultTokite(824);
            break;
        case 4558:
            width = 18;
            height = 18;
            headSlot = 228;
            rare = 3;
            vanity = true;
            value = buyPrice(0, 2);
            break;
        case 4559:
            width = 18;
            height = 18;
            headSlot = 229;
            rare = 3;
            vanity = true;
            value = buyPrice(0, 2);
            break;
        case 4550:
            DefaultToVanitypet(825, 262);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(1));
            break;
        case 4613:
            DefaultTokite(826);
            break;
        case 4626:
        case 4627:
        case 4628:
        case 4629:
        case 4630:
        case 4631:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 63 + (type - 4626);
            break;
        case 4632:
        case 4633:
        case 4634:
        case 4635:
        case 4636:
        case 4637:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 37 + (type - 4632);
            break;
        case 4638:
        case 4639:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 7 + (type - 4638);
            break;
        case 4640:
            DefaultToPlaceableTile((ushort)67, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 1));
            break;
        case 4641:
            DefaultToPlaceableTile((ushort)66, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 1));
            break;
        case 4642:
            DefaultToPlaceableTile((ushort)63, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 1));
            break;
        case 4643:
            DefaultToPlaceableTile((ushort)65, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 1));
            break;
        case 4644:
            DefaultToPlaceableTile((ushort)64, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 1));
            break;
        case 4645:
            DefaultToPlaceableTile((ushort)68, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 1));
            break;
        case 4646:
            DefaultToPlaceableTile((ushort)566, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 1));
            break;
        case 4647:
            DefaultToPlaceableWall(314);
            break;
        case 4648:
        case 4649:
        case 4650:
        case 4651:
            DefaultTokite(827 + (type - 4648));
            break;
        case 4652:
            width = 18;
            height = 18;
            headSlot = 230;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4653:
            width = 18;
            height = 18;
            bodySlot = 217;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4654:
            width = 18;
            height = 18;
            legSlot = 191;
            rare = 3;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4655:
            DefaultToPlaceableTile((ushort)568, 0);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4656:
            DefaultToPlaceableTile((ushort)569, 0);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4657:
            DefaultToPlaceableTile((ushort)570, 0);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 4552:
            DefaultToPlaceableTile((ushort)565, 0);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 4));
            break;
        case 4658:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 43;
            break;
        case 4659:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 9;
            break;
        case 4660:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 69;
            break;
        case 4661:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 246;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 19;
            break;
        case 4662:
        case 4663:
        case 4778:
            width = 20;
            height = 20;
            maxStack = CommonMaxStack;
            value = sellPrice(0, 1, 50);
            rare = 3;
            break;
        case 4664:
            width = 18;
            height = 18;
            bodySlot = 218;
            rare = 3;
            vanity = true;
            value = buyPrice(0, 20);
            break;
        case 4665:
            width = 18;
            height = 18;
            legSlot = 193;
            rare = 3;
            vanity = true;
            value = buyPrice(0, 20);
            break;
        case 4666:
            width = 18;
            height = 18;
            headSlot = 232;
            rare = 3;
            vanity = true;
            value = buyPrice(0, 15);
            break;
        case 4667:
            DefaultToPlaceableWall(315);
            break;
        case 4668:
            paintCoating = 1;
            width = 24;
            height = 24;
            value = buyPrice(0, 0, 2);
            maxStack = CommonMaxStack;
            break;
        case 4669:
            DefaultTokite(838);
            break;
        case 4670:
            DefaultTokite(839);
            break;
        case 4671:
            DefaultTokite(840);
            break;
        case 4672:
            DefaultToWhip(841, 14, 1f, 4f);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4673:
            autoReuse = true;
            useStyle = 1;
            useTurn = true;
            useAnimation = 12;
            useTime = 12;
            width = 16;
            height = 16;
            scale = 1f;
            value = buyPrice(0, 0, 50);
            break;
        case 4674:
            DefaultTokite(843);
            break;
        case 4675:
            DefaultTokite(844);
            break;
        case 4676:
            DefaultTokite(845);
            value = buyPrice(0, 2);
            break;
        case 4677:
            DefaultTokite(846);
            break;
        case 4678:
            DefaultToWhip(847, 55, 2f, 4f, 28);
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 4, 60));
            break;
        case 4679:
            DefaultToWhip(848, 165, 11f, 4f, 35);
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 6));
            crit = 10;
            break;
        case 4680:
            DefaultToWhip(849, 100, 3f, 4f, 27);
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 10));
            break;
        case 4681:
            DefaultTokite(850);
            value = buyPrice(0, 2);
            break;
        case 4682:
            width = 20;
            height = 24;
            DefaultToThrownWeapon(851, 25, 4f);
            value = buyPrice(0, 0, 1);
            ranged = false;
            noUseGraphic = true;
            break;
        case 4683:
            DefaultTokite(852);
            break;
        case 4684:
            DefaultTokite(853);
            break;
        case 4685:
            width = 18;
            height = 18;
            headSlot = 231;
            vanity = true;
            value = buyPrice(0, 10);
            break;
        case 4686:
            width = 18;
            height = 18;
            bodySlot = 219;
            vanity = true;
            value = buyPrice(0, 10);
            break;
        case 4687:
        case 4688:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 91;
            placeStyle = 295 + (type - 4687);
            width = 10;
            height = 24;
            value = 1000;
            rare = 1;
            break;
        case 4689:
        case 4690:
        case 4691:
        case 4692:
        case 4693:
        case 4694:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 215;
            placeStyle = 8 + type - 4689;
            width = 12;
            height = 12;
            break;
        case 4695:
        case 4696:
        case 4697:
        case 4698:
        case 4699:
        case 4700:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 572;
            placeStyle = type - 4695;
            width = 12;
            height = 28;
            if (type >= 4695 && type <= 4697)
            {
                value = 1000;
            }
            else
            {
                value = 40000;
            }
            break;
        case 4701:
            DefaultToVanitypet(854, 264);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 50));
            break;
        case 4702:
            width = 20;
            height = 24;
            DefaultToThrownWeapon(855, 25, 4f);
            value = buyPrice(0, 0, 1);
            ranged = false;
            noUseGraphic = true;
            break;
        case 4703:
            DefaultToRangedWeapon(14, AmmoID.Bullet, 55, 7f);
            knockBack = 6.5f;
            width = 50;
            height = 14;
            UseSound = SoundID.Item36;
            damage = 14;
            value = buyPrice(0, 35);
            rare = 3;
            break;
        case 4704:
            width = 18;
            height = 18;
            headSlot = 233;
            vanity = true;
            value = buyPrice(0, 10);
            break;
        case 4705:
            width = 18;
            height = 18;
            bodySlot = 220;
            vanity = true;
            value = buyPrice(0, 10);
            break;
        case 4706:
            width = 18;
            height = 18;
            legSlot = 197;
            vanity = true;
            value = buyPrice(0, 10);
            break;
        case 4707:
            width = 44;
            height = 44;
            rare = 2;
            value = buyPrice(0, 10);
            holdStyle = 2;
            useStyle = 3;
            useAnimation = 22;
            useTime = 22;
            damage = 15;
            knockBack = 5f;
            UseSound = SoundID.Item1;
            melee = true;
            break;
        case 4708:
            width = 18;
            height = 18;
            headSlot = 234;
            vanity = true;
            value = buyPrice(0, 10);
            break;
        case 4709:
            width = 18;
            height = 18;
            bodySlot = 221;
            vanity = true;
            value = buyPrice(0, 10);
            break;
        case 4710:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 573;
            width = 28;
            height = 28;
            break;
        case 4711:
            useStyle = 1;
            useTurn = true;
            useAnimation = 22;
            useTime = 14;
            autoReuse = true;
            width = 24;
            height = 28;
            damage = 12;
            UseSound = SoundID.Item1;
            knockBack = 3.5f;
            rare = 1;
            value = sellPrice(0, 0, 10);
            melee = true;
            break;
        case 4712:
            DefaultToPlaceableTile((ushort)467, 12);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 25));
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4713:
            DefaultToPlaceableTile((ushort)468, 12);
            SetShopValues(ItemRarityColor.White0, buyPrice(0, 0, 5));
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 4714:
            width = 14;
            height = 20;
            maxStack = CommonMaxStack;
            rare = 8;
            break;
        case 4715:
            SetShopValues(ItemRarityColor.Pink5, buyPrice(0, 50));
            DefaultToGuitar();
            useAnimation = (useTime = 12);
            useTime /= 2;
            shoot = 856;
            damage = 85;
            magic = true;
            shootSpeed = 1f;
            crit = 20;
            knockBack = 1.5f;
            mana = 12;
            noMelee = true;
            break;
        case 4716:
            useStyle = 4;
            channel = true;
            width = 34;
            height = 34;
            UseSound = SoundID.Item43;
            useAnimation = 20;
            useTime = 20;
            rare = 8;
            noMelee = true;
            mountType = 37;
            value = buyPrice(0, 20);
            break;
        case 4717:
        case 4718:
        case 4719:
        case 4720:
        case 4721:
            DefaultToPlaceableTile(574 + type - 4717);
            break;
        case 4722:
            useStyle = 5;
            width = 24;
            height = 24;
            noUseGraphic = true;
            UseSound = SoundID.Item1;
            autoReuse = true;
            melee = true;
            channel = true;
            noMelee = true;
            shoot = 857;
            useAnimation = 35;
            useTime = useAnimation / 5;
            shootSpeed = 16f;
            damage = 190;
            knockBack = 6.5f;
            value = sellPrice(0, 20);
            crit = 10;
            rare = 10;
            glowMask = 271;
            break;
        case 4723:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 70;
            break;
        case 4724:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 71;
            break;
        case 4725:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 44;
            break;
        case 4726:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 10;
            break;
        case 4727:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 11;
            break;
        case 4728:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 12;
            break;
        case 4729:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 246;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 20;
            break;
        case 4730:
            width = 24;
            height = 8;
            accessory = true;
            rare = 9;
            wingSlot = 40;
            value = 400000;
            break;
        case 4731:
            DefaultToPlaceableTile((ushort)497, 39);
            maxStack = CommonMaxStack;
            value = 150;
            rare = 8;
            break;
        case 4732:
            width = 18;
            height = 18;
            headSlot = 235;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4733:
            width = 18;
            height = 18;
            bodySlot = 222;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4734:
            width = 18;
            height = 18;
            legSlot = 203;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4735:
            DefaultToVanitypet(858, 266);
            value = buyPrice(0, 50);
            break;
        case 4736:
            DefaultToVanitypet(859, 267);
            value = buyPrice(0, 30);
            break;
        case 4737:
            DefaultToVanitypet(860, 268);
            break;
        case 4738:
            width = 18;
            height = 18;
            headSlot = 236;
            rare = 2;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4739:
            width = 18;
            height = 18;
            bodySlot = 223;
            rare = 2;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4740:
            width = 18;
            height = 18;
            headSlot = 237;
            rare = 2;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4741:
            width = 18;
            height = 18;
            bodySlot = 224;
            rare = 2;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4742:
            width = 18;
            height = 18;
            legSlot = 205;
            rare = 2;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4743:
            useStyle = 1;
            shootSpeed = 11f;
            shoot = 861;
            damage = 0;
            width = 10;
            height = 10;
            maxStack = 1;
            consumable = true;
            UseSound = SoundID.Item1;
            useAnimation = 15;
            useTime = 15;
            noUseGraphic = true;
            noMelee = true;
            value = 20;
            break;
        case 4744:
            DefaultToAccessory(26, 36);
            backSlot = 24;
            frontSlot = 8;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 3));
            vanity = true;
            break;
        case 4745:
            DefaultToMount(38);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 20));
            break;
        case 4750:
            width = 24;
            height = 8;
            accessory = true;
            rare = 9;
            wingSlot = 42;
            value = 400000;
            break;
        case 4751:
            width = 18;
            height = 18;
            headSlot = 239;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4752:
            width = 18;
            height = 18;
            bodySlot = 226;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4753:
            width = 18;
            height = 18;
            legSlot = 209;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4746:
            width = 24;
            height = 8;
            accessory = true;
            rare = 9;
            wingSlot = 41;
            value = 400000;
            break;
        case 4747:
            width = 18;
            height = 18;
            headSlot = 238;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4748:
            width = 18;
            height = 18;
            bodySlot = 225;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4749:
            width = 18;
            height = 18;
            legSlot = 208;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4754:
            width = 24;
            height = 8;
            accessory = true;
            rare = 9;
            wingSlot = 43;
            value = 400000;
            break;
        case 4755:
            width = 18;
            height = 18;
            headSlot = 240;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4756:
            width = 18;
            height = 18;
            bodySlot = 227;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4757:
            width = 18;
            height = 18;
            legSlot = 210;
            rare = 9;
            vanity = true;
            value = sellPrice(0, 5);
            break;
        case 4758:
            mana = 10;
            damage = 6;
            useStyle = 1;
            shootSpeed = 10f;
            shoot = 864;
            buffType = 271;
            width = 26;
            height = 28;
            UseSound = SoundID.Item44;
            useAnimation = 36;
            useTime = 36;
            rare = 5;
            noMelee = true;
            knockBack = 0f;
            value = sellPrice(0, 1);
            summon = true;
            autoReuse = true;
            reuseDelay = 2;
            break;
        case 4759:
            noUseGraphic = true;
            damage = 0;
            knockBack = 7f;
            useStyle = 5;
            shootSpeed = 11.5f;
            shoot = 865;
            width = 18;
            height = 28;
            UseSound = SoundID.Item1;
            useAnimation = 20;
            useTime = 20;
            rare = 1;
            noMelee = true;
            value = 20000;
            break;
        case 4760:
            damage = 80;
            useStyle = 1;
            shootSpeed = 10f;
            shoot = 866;
            width = 26;
            height = 28;
            UseSound = SoundID.Item1;
            useAnimation = 36;
            useTime = 36;
            rare = 5;
            noMelee = true;
            knockBack = 2f;
            value = buyPrice(0, 35);
            melee = true;
            noUseGraphic = true;
            break;
        case 4761:
            width = 12;
            height = 12;
            headSlot = 241;
            rare = 3;
            vanity = true;
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 579;
            break;
        case 4762:
            width = 24;
            height = 24;
            accessory = true;
            vanity = true;
            rare = 1;
            value = buyPrice(0, 10);
            hasVanityEffects = true;
            break;
        case 4763:
            DefaultToMount(39);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 50));
            break;
        case 4764:
            noMelee = true;
            useStyle = 1;
            shootSpeed = 10.5f;
            shoot = 867;
            damage = 23;
            knockBack = 7f;
            width = 14;
            height = 28;
            UseSound = SoundID.Item1;
            useAnimation = 20;
            useTime = 20;
            noUseGraphic = true;
            rare = 1;
            value = 30000;
            melee = true;
            break;
        case 4765:
        case 4766:
            DefaultToThrownWeapon(type - 4765 + 868, 20, 8f);
            UseSound = SoundID.Item106;
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 3));
            width = 18;
            height = 18;
            break;
        case 4767:
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
            width = 30;
            height = 30;
            break;
        case 4768:
            width = 18;
            height = 18;
            headSlot = 242;
            rare = 1;
            vanity = true;
            value = buyPrice(0, 3);
            break;
        case 4769:
            DefaultToAccessory(18, 18);
            backSlot = 25;
            rare = 1;
            vanity = true;
            value = buyPrice(0, 3);
            break;
        case 4770:
            width = 18;
            height = 18;
            headSlot = 243;
            rare = 1;
            vanity = true;
            value = buyPrice(0, 3);
            break;
        case 4771:
            DefaultToAccessory(18, 18);
            backSlot = 26;
            rare = 1;
            vanity = true;
            value = buyPrice(0, 3);
            break;
        case 4772:
            width = 18;
            height = 18;
            headSlot = 244;
            rare = 1;
            vanity = true;
            value = buyPrice(0, 3);
            break;
        case 4773:
            DefaultToAccessory(18, 18);
            backSlot = 27;
            rare = 1;
            vanity = true;
            value = buyPrice(0, 3);
            break;
        case 4774:
            width = 18;
            height = 18;
            headSlot = 245;
            rare = 1;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 4775:
            DefaultToAccessory(18, 18);
            backSlot = 28;
            rare = 1;
            vanity = true;
            value = buyPrice(0, 3);
            break;
        case 4776:
            color = new Color(255, 255, 255, 0);
            useStyle = 1;
            shootSpeed = 6f;
            shoot = 870;
            width = 12;
            height = 12;
            maxStack = CommonMaxStack;
            consumable = true;
            UseSound = SoundID.Item1;
            useAnimation = 15;
            useTime = 15;
            noMelee = true;
            rare = 1;
            value = buyPrice(0, 0, 0, 75);
            holdStyle = 1;
            break;
        case 4777:
            DefaultToVanitypet(875, 274);
            value = buyPrice(0, 50);
            break;
        case 4779:
            width = 18;
            height = 18;
            headSlot = 250;
            rare = 1;
            vanity = true;
            break;
        case 4780:
            width = 18;
            height = 18;
            bodySlot = 228;
            rare = 1;
            vanity = true;
            break;
        case 4781:
            width = 18;
            height = 18;
            legSlot = 211;
            rare = 1;
            vanity = true;
            break;
        case 4782:
            maxStack = CommonMaxStack;
            consumable = true;
            width = 24;
            height = 24;
            rare = 6;
            expert = true;
            break;
        case 4784:
            width = 18;
            height = 18;
            headSlot = 251;
            rare = 1;
            value = sellPrice(0, 0, 75);
            vanity = true;
            break;
        case 4783:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 1);
            rare = 1;
            placeStyle = 72;
            break;
        case 4785:
        case 4786:
        case 4787:
            useStyle = 4;
            channel = true;
            width = 34;
            height = 34;
            UseSound = SoundID.Item76;
            useAnimation = 20;
            useTime = 20;
            rare = 8;
            noMelee = true;
            mountType = 40 + (type - 4785);
            value = sellPrice(0, 5);
            break;
        case 4788:
            DefaultToSpear(877, 3.5f, 24);
            SetWeaponValues(60, 12f);
            SetShopValues(ItemRarityColor.LightRed4, buyPrice(0, 6));
            channel = true;
            break;
        case 4790:
            DefaultToSpear(879, 3.5f, 24);
            SetWeaponValues(90, 13f);
            SetShopValues(ItemRarityColor.Pink5, 230000);
            channel = true;
            break;
        case 4789:
            DefaultToSpear(878, 3.5f, 24);
            SetWeaponValues(130, 14f);
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 10));
            channel = true;
            break;
        case 4791:
            useStyle = 4;
            channel = true;
            width = 10;
            height = 32;
            UseSound = SoundID.Item25;
            useAnimation = 20;
            useTime = 20;
            rare = 8;
            noMelee = true;
            noUseGraphic = true;
            mountType = 43;
            value = sellPrice(0, 5);
            break;
        case 4792:
        case 4793:
        case 4794:
        case 4795:
        case 4796:
            useStyle = 4;
            channel = true;
            width = 10;
            height = 32;
            UseSound = SoundID.Item25;
            useAnimation = 20;
            useTime = 20;
            rare = -13;
            noMelee = true;
            noUseGraphic = true;
            mountType = 44 + type - 4792;
            value = sellPrice(0, 5);
            break;
        case 4797:
        case 4798:
        case 4799:
        case 4800:
        case 4801:
        case 4802:
        case 4803:
        case 4804:
        case 4805:
        case 4806:
        case 4807:
        case 4808:
        case 4809:
        case 4810:
        case 4811:
        case 4812:
        case 4813:
        case 4814:
        case 4815:
        case 4816:
        case 4817:
            DefaultToVanitypet(881 + type - 4797, 284 + type - 4797);
            value = buyPrice(0, 25);
            rare = -13;
            break;
        case 4818:
            noMelee = true;
            useStyle = 1;
            shootSpeed = 8.5f;
            shoot = 902;
            damage = 25;
            knockBack = 3.5f;
            width = 14;
            height = 28;
            UseSound = SoundID.Item1;
            useAnimation = 15;
            useTime = 15;
            noUseGraphic = true;
            rare = 2;
            value = sellPrice(0, 0, 50);
            melee = true;
            break;
        case 4819:
            useTurn = true;
            width = 20;
            height = 20;
            useStyle = 4;
            useTime = 90;
            UseSound = SoundID.Item6;
            useAnimation = 90;
            SetShopValues(ItemRarityColor.LightRed4, buyPrice(0, 5));
            break;
        case 4820:
            useStyle = 1;
            useTurn = true;
            useAnimation = 12;
            useTime = 5;
            width = 20;
            height = 20;
            autoReuse = true;
            rare = 7;
            value = sellPrice(0, 10);
            tileBoost += 2;
            break;
        case 4821:
            useTurn = true;
            useStyle = 1;
            useTime = 21;
            useAnimation = 21;
            width = 24;
            height = 28;
            UseSound = SoundID.Item1;
            value = sellPrice(0, 5);
            autoReuse = true;
            rare = 3;
            scale = 0.85f;
            break;
        case 4822:
            DefaultToAccessory(34, 30);
            shoeSlot = 22;
            SetShopValues(ItemRarityColor.Orange3, sellPrice(0, 2));
            vanity = true;
            break;
        case 4823:
            width = 24;
            height = 8;
            accessory = true;
            rare = 9;
            wingSlot = 44;
            value = buyPrice(0, 40);
            break;
        case 4824:
        case 4825:
        case 4826:
        case 4827:
            useStyle = 1;
            shootSpeed = 5f;
            shoot = 903 + (type - 4824);
            width = 20;
            height = 20;
            maxStack = CommonMaxStack;
            UseSound = SoundID.Item1;
            consumable = true;
            useAnimation = 25;
            noUseGraphic = true;
            useTime = 25;
            value = sellPrice(0, 0, 5);
            rare = 1;
            break;
        case 4828:
            useStyle = 4;
            channel = true;
            width = 10;
            height = 32;
            UseSound = SoundID.Item25;
            useAnimation = 20;
            useTime = 20;
            rare = 8;
            noMelee = true;
            noUseGraphic = true;
            mountType = 49;
            value = sellPrice(0, 5);
            break;
        case 4829:
        case 4830:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 5));
            break;
        case 4831:
        case 4832:
        case 4833:
        case 4834:
        case 4835:
        case 4836:
        case 4837:
            useStyle = 1;
            autoReuse = true;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            noUseGraphic = true;
            value = sellPrice(0, 0, 10);
            makeNPC = (short)(639 + (type - 4831));
            break;
        case 4838:
        case 4839:
        case 4840:
        case 4841:
        case 4842:
        case 4843:
        case 4844:
            useStyle = 1;
            autoReuse = true;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            noUseGraphic = true;
            value = sellPrice(0, 0, 10);
            makeNPC = (short)(646 + (type - 4838));
            break;
        case 4845:
            DefaultToCapturedCritter(653);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 20));
            width = 12;
            height = 12;
            bait = 15;
            break;
        case 4846:
            DefaultToPlaceableTile((ushort)580, 0);
            maxStack = CommonMaxStack;
            break;
        case 4847:
            DefaultToCapturedCritter(654);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 20));
            width = 12;
            height = 12;
            bait = 25;
            break;
        case 4848:
            DefaultToPlaceableTile((ushort)581, 0);
            maxStack = CommonMaxStack;
            break;
        case 4849:
            DefaultToCapturedCritter(655);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            width = 12;
            height = 12;
            bait = 35;
            break;
        case 4850:
            DefaultToPlaceableTile((ushort)582, 0);
            maxStack = CommonMaxStack;
            break;
        case 4851:
            DefaultToPlaceableTile((ushort)590, 0);
            value = sellPrice(0, 0, 7, 50);
            break;
        case 4852:
            DefaultToPlaceableTile((ushort)590, 1);
            value = sellPrice(0, 0, 3, 75);
            break;
        case 4853:
            DefaultToPlaceableTile((ushort)590, 2);
            value = sellPrice(0, 0, 11, 25);
            break;
        case 4854:
            DefaultToPlaceableTile((ushort)590, 3);
            value = sellPrice(0, 0, 15);
            break;
        case 4855:
            DefaultToPlaceableTile((ushort)590, 4);
            value = sellPrice(0, 0, 22, 50);
            break;
        case 4856:
            DefaultToPlaceableTile((ushort)590, 5);
            value = sellPrice(0, 0, 30);
            break;
        case 4857:
            DefaultToPlaceableTile((ushort)590, 6);
            value = sellPrice(0, 0, 30);
            break;
        case 4858:
        case 4859:
        case 4860:
        case 4861:
        case 4862:
        case 4863:
        case 4864:
        case 4865:
        case 4866:
            DefaultToPlaceableTile((ushort)591, type - 4858);
            value = sellPrice(0, 0, 25);
            break;
        case 4867:
            DefaultToPlaceableTile((ushort)592, 0);
            value = sellPrice(0, 0, 25);
            break;
        case 4868:
        case 4869:
            DefaultToPlaceableTile(593 + (type - 4868));
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
            break;
        case 4870:
            UseSound = SoundID.Item6;
            useStyle = 6;
            useTurn = true;
            useTime = (useAnimation = 30);
            maxStack = CommonMaxStack;
            consumable = true;
            width = 14;
            height = 24;
            value = 1000;
            rare = 1;
            break;
        case 4871:
            DefaultToPlaceableTile((ushort)595, 0);
            value = buyPrice(0, 1);
            break;
        case 4872:
            useStyle = 1;
            useTurn = true;
            useAnimation = 12;
            useTime = 5;
            width = 20;
            height = 20;
            autoReuse = true;
            rare = 7;
            value = sellPrice(0, 10);
            tileBoost += 2;
            break;
        case 4873:
            width = 18;
            height = 18;
            defense = 1;
            headSlot = 254;
            rare = 5;
            value = 250000;
            break;
        case 4874:
            DefaultToAccessory(34, 30);
            shoeSlot = 23;
            SetShopValues(ItemRarityColor.Lime7, sellPrice(0, 4));
            hasVanityEffects = true;
            break;
        case 4876:
            DefaultToPlaceableTile((ushort)597, 0);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4875:
            DefaultToPlaceableTile((ushort)597, 1);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4877:
        case 4878:
            DefaultToPlaceableTile((ushort)376, 22 + type - 4877);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 1));
            maxStack = CommonMaxStack;
            break;
        case 4879:
            width = 12;
            height = 12;
            rare = 2;
            maxStack = CommonMaxStack;
            value = buyPrice(0, 2);
            break;
        case 4880:
            DefaultToPlaceableTile((ushort)598, 0);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            value = sellPrice(0, 0, 20);
            break;
        case 4881:
            DefaultToAccessory(34, 30);
            SetShopValues(ItemRarityColor.Lime7, sellPrice(0, 2));
            break;
        case 4882:
        case 4883:
        case 4884:
        case 4885:
        case 4886:
        case 4887:
        case 4888:
        case 4889:
        case 4890:
        case 4891:
        case 4892:
        case 4893:
        case 4894:
        case 4895:
            DefaultToPlaceableTile(599 + (type - 4882));
            maxStack = CommonMaxStack;
            break;
        case 4896:
            width = 18;
            height = 18;
            defense = 24;
            headSlot = 255;
            rare = 5;
            value = 250000;
            break;
        case 4897:
            width = 18;
            height = 18;
            defense = 9;
            headSlot = 256;
            rare = 5;
            value = 250000;
            break;
        case 4898:
            width = 18;
            height = 18;
            defense = 5;
            headSlot = 257;
            rare = 5;
            value = 250000;
            break;
        case 4899:
            width = 18;
            height = 18;
            defense = 1;
            headSlot = 258;
            rare = 5;
            value = 250000;
            break;
        case 4900:
            width = 18;
            height = 18;
            defense = 15;
            bodySlot = 229;
            rare = 5;
            value = 200000;
            break;
        case 4901:
            width = 18;
            height = 18;
            defense = 11;
            legSlot = 212;
            rare = 5;
            value = 150000;
            break;
        case 4902:
            DefaultToPlaceableTile((ushort)548, 7);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 3));
            break;
        case 4903:
            DefaultToPlaceableTile((ushort)548, 8);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 3));
            break;
        case 4904:
            DefaultToPlaceableTile((ushort)613, 0);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 3));
            break;
        case 4905:
            DefaultToPlaceableTile((ushort)613, 1);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 3));
            break;
        case 4906:
            DefaultToPlaceableTile((ushort)614, 0);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 3));
            break;
        case 4907:
            DefaultToPlaceableTile((ushort)615, 0);
            value = buyPrice(0, 1);
            break;
        case 4908:
        case 4909:
            useStyle = 1;
            shootSpeed = 5f;
            shoot = 910 + (type - 4908);
            width = 20;
            height = 20;
            maxStack = CommonMaxStack;
            UseSound = SoundID.Item1;
            consumable = true;
            useAnimation = 25;
            noUseGraphic = true;
            useTime = 25;
            value = sellPrice(0, 0, 1);
            rare = 1;
            break;
        case 4910:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 5));
            break;
        case 4911:
            DefaultToWhip(912, 45, 1.5f, 4f);
            SetShopValues(ItemRarityColor.LightRed4, sellPrice(0, 4));
            break;
        case 4912:
            DefaultToWhip(913, 37, 2f, 4f);
            SetShopValues(ItemRarityColor.LightRed4, sellPrice(0, 3));
            break;
        case 4913:
            DefaultToWhip(914, 18, 1.5f, 4f);
            SetShopValues(ItemRarityColor.Orange3, sellPrice(0, 1));
            break;
        case 4914:
            DefaultToWhip(915, 180, 4f, 4f);
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 5));
            break;
        case 4915:
            shootSpeed = 4.5f;
            shoot = 14;
            damage = 9;
            width = 8;
            height = 8;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Bullet;
            knockBack = 4f;
            value = 18;
            ranged = true;
            break;
        case 4916:
            DefaultToPlaceableTile((ushort)597, 2);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4917:
            DefaultToPlaceableTile((ushort)597, 3);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4918:
            DefaultToPlaceableTile((ushort)597, 4);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4919:
            DefaultToPlaceableTile((ushort)597, 5);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4920:
            DefaultToPlaceableTile((ushort)597, 6);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4921:
            DefaultToPlaceableTile((ushort)597, 7);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 10));
            break;
        case 4922:
            DefaultToPlaceableTile((ushort)207, 8);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 4));
            width = 8;
            height = 10;
            break;
        case 4923:
            width = 14;
            height = 38;
            rare = 8;
            noUseGraphic = true;
            channel = true;
            noMelee = true;
            damage = 80;
            crit = 10;
            knockBack = 4f;
            autoReuse = false;
            noMelee = true;
            melee = true;
            shoot = 927;
            shootSpeed = 15f;
            value = sellPrice(0, 5);
            useStyle = 13;
            useAnimation = 18;
            useTime = 6;
            break;
        case 4924:
        case 4925:
        case 4926:
        case 4927:
        case 4928:
        case 4929:
        case 4930:
        case 4931:
        case 4932:
        case 4933:
        case 4934:
        case 4935:
        case 4936:
        case 4937:
        case 4938:
        case 4939:
        case 4940:
        case 4941:
        case 4942:
        case 4943:
        case 4944:
        case 4945:
        case 4946:
        case 4947:
        case 4948:
        case 4949:
        case 4950:
            DefaultToPlaceableTile((ushort)617, type - 4924);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
            rare = -13;
            maxStack = CommonMaxStack;
            break;
        case 4951:
            DefaultToPlaceableTile((ushort)597, 8);
            SetShopValues(ItemRarityColor.Cyan9, buyPrice(1));
            break;
        case 4954:
            width = 24;
            height = 8;
            accessory = true;
            rare = 9;
            wingSlot = 45;
            value = sellPrice(0, 10);
            expert = true;
            break;
        case 4952:
            autoReuse = true;
            useStyle = 14;
            holdStyle = 6;
            scale = 0.7f;
            useAnimation = 36;
            useTime = 2;
            width = 36;
            height = 22;
            shoot = 931;
            mana = 23;
            UseSound = SoundID.Item82;
            knockBack = 2.5f;
            damage = 50;
            shootSpeed = 17f;
            noMelee = true;
            rare = 8;
            magic = true;
            value = sellPrice(0, 5);
            flame = true;
            break;
        case 4953:
            useStyle = 5;
            autoReuse = true;
            useAnimation = 30;
            useTime = 2;
            width = 50;
            height = 18;
            shoot = 1;
            useAmmo = AmmoID.Arrow;
            UseSound = SoundID.Item5;
            damage = 50;
            shootSpeed = 10f;
            noMelee = true;
            value = sellPrice(0, 5);
            ranged = true;
            rare = 8;
            knockBack = 2f;
            break;
        case 4955:
            width = 18;
            height = 18;
            headSlot = 259;
            value = buyPrice(0, 15);
            rare = 5;
            vanity = true;
            break;
        case 4956:
            useStyle = 1;
            width = 24;
            height = 24;
            UseSound = null;
            autoReuse = true;
            melee = true;
            melee = true;
            shoot = 933;
            useAnimation = 30;
            useTime = useAnimation / 3;
            shootSpeed = 16f;
            damage = 190;
            knockBack = 6.5f;
            value = sellPrice(0, 20);
            crit = 10;
            rare = 10;
            noUseGraphic = true;
            noMelee = true;
            break;
        case 4957:
            maxStack = CommonMaxStack;
            consumable = true;
            width = 24;
            height = 24;
            rare = 6;
            expert = true;
            break;
        case 4958:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 1);
            rare = 1;
            placeStyle = 73;
            break;
        case 4959:
            width = 18;
            height = 18;
            headSlot = 260;
            rare = 1;
            value = sellPrice(0, 0, 75);
            vanity = true;
            break;
        case 4960:
            DefaultToVanitypet(934, 317);
            value = buyPrice(0, 25);
            rare = -13;
            break;
        case 4961:
            DefaultToCapturedCritter(661);
            SetShopValues(ItemRarityColor.Orange3, sellPrice(0, 5));
            width = 12;
            height = 12;
            break;
        case 4962:
            DefaultToPlaceableTile((ushort)618, 0);
            break;
        case 4963:
            DefaultToPlaceableTile((ushort)619, 0);
            maxStack = CommonMaxStack;
            break;
        case 4964:
            DefaultToPlaceableTile((ushort)620, 0);
            maxStack = CommonMaxStack;
            break;
        case 4965:
        case 4966:
        case 4967:
        case 4968:
        case 4969:
        case 4970:
        case 4971:
        case 4972:
        case 4973:
        case 4974:
        case 4975:
        case 4976:
        case 4977:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 91;
            placeStyle = 297 + (type - 4965);
            width = 10;
            height = 24;
            value = 1000;
            rare = 1;
            break;
        case 4978:
            width = 24;
            height = 8;
            accessory = true;
            rare = 0;
            wingSlot = 46;
            value = 2000;
            break;
        case 4979:
            DefaultToMusicBox(52);
            break;
        case 4980:
            noUseGraphic = true;
            damage = 0;
            knockBack = 7f;
            useStyle = 5;
            shootSpeed = 4f;
            shoot = 935;
            width = 18;
            height = 28;
            UseSound = SoundID.Item1;
            useAnimation = 20;
            useTime = 20;
            rare = 5;
            noMelee = true;
            value = sellPrice(0, 5);
            break;
        case 4981:
            useStyle = 4;
            channel = true;
            width = 10;
            height = 32;
            UseSound = SoundID.Item25;
            useAnimation = 20;
            useTime = 20;
            rare = 8;
            noMelee = true;
            noUseGraphic = true;
            mountType = 50;
            value = sellPrice(0, 5);
            break;
        case 4982:
            width = 18;
            height = 18;
            defense = 12;
            headSlot = 261;
            rare = 5;
            value = sellPrice(0, 2);
            break;
        case 4983:
            width = 18;
            height = 18;
            defense = 14;
            bodySlot = 230;
            rare = 5;
            value = sellPrice(0, 2);
            break;
        case 4984:
            width = 18;
            height = 18;
            defense = 10;
            legSlot = 213;
            rare = 5;
            value = sellPrice(0, 2);
            break;
        case 4985:
            DefaultToMusicBox(53);
            break;
        case 4986:
            useStyle = 1;
            shootSpeed = 9f;
            shoot = 936;
            width = 18;
            height = 20;
            maxStack = CommonMaxStack;
            consumable = true;
            UseSound = SoundID.Item1;
            useAnimation = 15;
            useTime = 15;
            noUseGraphic = true;
            noMelee = true;
            value = 200;
            break;
        case 4987:
            width = 16;
            height = 24;
            accessory = true;
            rare = 6;
            value = sellPrice(0, 5);
            expert = true;
            break;
        case 4988:
            useStyle = 4;
            width = 20;
            height = 20;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            maxStack = CommonMaxStack;
            rare = 6;
            value = sellPrice(0, 1);
            break;
        case 4989:
            width = 22;
            height = 22;
            accessory = true;
            rare = 1;
            value = sellPrice(0, 10);
            expert = true;
            break;
        case 4990:
            DefaultToMusicBox(54);
            break;
        case 4991:
            DefaultToMusicBox(55);
            break;
        case 4992:
            DefaultToMusicBox(56);
            break;
        case 4993:
            DefaultToPlaceableTile((ushort)89, 43);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            rare = 9;
            break;
        case 4994:
            width = 18;
            height = 14;
            headSlot = 262;
            rare = 2;
            value = buyPrice(0, 10);
            vanity = true;
            break;
        case 4995:
            width = 18;
            height = 14;
            headSlot = 263;
            rare = 2;
            value = buyPrice(0, 10);
            vanity = true;
            break;
        case 4996:
            width = 18;
            height = 14;
            headSlot = 264;
            rare = 2;
            value = buyPrice(0, 10);
            vanity = true;
            break;
        case 4997:
            width = 18;
            height = 14;
            vanity = true;
            bodySlot = 231;
            value = buyPrice(0, 10);
            rare = 2;
            break;
        case 4998:
            width = 18;
            height = 14;
            vanity = true;
            bodySlot = 232;
            value = buyPrice(0, 10);
            rare = 2;
            break;
        case 4999:
            width = 18;
            height = 14;
            vanity = true;
            bodySlot = 233;
            value = buyPrice(0, 10);
            rare = 2;
            break;
        case 5000:
            DefaultToAccessory(34, 30);
            shoeSlot = 24;
            SetShopValues(ItemRarityColor.Lime7, sellPrice(0, 15));
            hasVanityEffects = true;
            break;
        case 5002:
        case 5003:
            DefaultToPlaceableTile((ushort)376, 24 + type - 5002);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 1));
            maxStack = CommonMaxStack;
            break;
        case 5005:
            mana = 10;
            damage = 90;
            useStyle = 1;
            shootSpeed = 10f;
            shoot = 946;
            buffType = 322;
            width = 26;
            height = 28;
            UseSound = SoundID.Item82;
            useAnimation = 36;
            useTime = 36;
            rare = 5;
            noMelee = true;
            knockBack = 4f;
            value = sellPrice(0, 20);
            summon = true;
            autoReuse = true;
            reuseDelay = 2;
            break;
        case 5004:
            width = 18;
            height = 14;
            headSlot = 265;
            rare = 9;
            value = sellPrice(0, 0, 30);
            vanity = true;
            break;
        case 5006:
            DefaultToMusicBox(57);
            break;
        case 5007:
            width = 18;
            height = 18;
            bodySlot = 234;
            rare = 2;
            value = sellPrice(0, 0, 20);
            vanity = true;
            break;
        case 5008:
            DefaultToPlaceableTile((ushort)622, 0);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 2));
            break;
        case 5001:
            width = 18;
            height = 14;
            defense = 3;
            legSlot = 217;
            value = buyPrice(0, 10);
            rare = 2;
            break;
        case 5010:
            DefaultToAccessory(34, 30);
            waistSlot = 16;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 3));
            break;
        case 5011:
        case 5012:
            noMelee = true;
            useStyle = 5;
            useAnimation = 45;
            useTime = 45;
            knockBack = 4.6f;
            width = 28;
            height = 28;
            damage = 9;
            scale = 1f;
            noUseGraphic = true;
            shoot = 947;
            if (type == 5012)
            {
                shoot = 948;
            }
            shootSpeed = 11f;
            UseSound = SoundID.Item1;
            rare = 1;
            value = sellPrice(0, 2);
            melee = true;
            channel = true;
            break;
        case 5014:
            DefaultToMusicBox(58);
            break;
        case 5015:
            DefaultToMusicBox(59);
            break;
        case 5016:
            DefaultToMusicBox(60);
            break;
        case 5017:
            DefaultToMusicBox(61);
            break;
        case 5018:
            DefaultToMusicBox(62);
            break;
        case 5019:
            DefaultToMusicBox(63);
            break;
        case 5020:
            DefaultToMusicBox(64);
            break;
        case 5021:
            DefaultToMusicBox(65);
            break;
        case 5022:
            DefaultToMusicBox(66);
            break;
        case 5023:
            DefaultToMusicBox(67);
            break;
        case 5024:
            DefaultToMusicBox(68);
            break;
        case 5025:
            DefaultToMusicBox(69);
            break;
        case 5026:
            DefaultToMusicBox(70);
            break;
        case 5027:
            DefaultToMusicBox(71);
            break;
        case 5028:
            DefaultToMusicBox(72);
            break;
        case 5029:
            DefaultToMusicBox(73);
            break;
        case 5030:
            DefaultToMusicBox(74);
            break;
        case 5031:
            DefaultToMusicBox(75);
            break;
        case 5032:
            DefaultToMusicBox(76);
            break;
        case 5033:
            DefaultToMusicBox(77);
            break;
        case 5034:
            DefaultToMusicBox(78);
            break;
        case 5035:
            DefaultToMusicBox(79);
            break;
        case 5036:
            DefaultToMusicBox(80);
            break;
        case 5037:
            DefaultToMusicBox(81);
            break;
        case 5038:
            DefaultToMusicBox(82);
            break;
        case 5039:
            DefaultToMusicBox(83);
            break;
        case 5040:
            DefaultToMusicBox(84);
            break;
        case 5043:
            maxStack = CommonMaxStack;
            consumable = true;
            width = 18;
            height = 18;
            useStyle = 4;
            useTime = 30;
            UseSound = SoundID.Item4;
            useAnimation = 30;
            rare = 4;
            value = sellPrice(0, 2);
            break;
        case 5044:
            DefaultToMusicBox(85);
            break;
        case 5045:
            width = 18;
            height = 14;
            headSlot = 266;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5046:
            width = 18;
            height = 14;
            bodySlot = 235;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5047:
            width = 18;
            height = 14;
            legSlot = 218;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5048:
            width = 18;
            height = 14;
            headSlot = 267;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5049:
            width = 18;
            height = 14;
            bodySlot = 236;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5050:
            width = 18;
            height = 14;
            legSlot = 219;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5051:
            width = 18;
            height = 14;
            headSlot = 268;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5052:
            width = 18;
            height = 14;
            bodySlot = 237;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5053:
            width = 18;
            height = 14;
            legSlot = 222;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5054:
            width = 18;
            height = 14;
            headSlot = 269;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5055:
            width = 18;
            height = 14;
            bodySlot = 238;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5056:
            width = 18;
            height = 14;
            legSlot = 224;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5057:
            width = 18;
            height = 14;
            headSlot = 270;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5058:
            width = 18;
            height = 14;
            bodySlot = 239;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5059:
            width = 18;
            height = 14;
            legSlot = 225;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5060:
            width = 18;
            height = 14;
            legSlot = 226;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5061:
            width = 18;
            height = 14;
            headSlot = 271;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5062:
            width = 18;
            height = 14;
            bodySlot = 240;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5063:
            width = 18;
            height = 14;
            legSlot = 227;
            rare = 2;
            value = sellPrice(0, 0, 1);
            vanity = true;
            break;
        case 5064:
            width = 26;
            height = 30;
            maxStack = 1;
            value = sellPrice(0, 4);
            rare = 8;
            accessory = true;
            backSlot = 33;
            break;
        case 5065:
            DefaultToStaff(950, 10f, 25, 18);
            SetWeaponValues(70, 5f);
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            break;
        case 5066:
            DefaultToPlaceableTile((ushort)444, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 50));
            break;
        case 5067:
            DefaultToPlaceableTile((ushort)485, 0);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 50));
            break;
        case 5068:
            width = 18;
            height = 18;
            bodySlot = 241;
            defense = 1;
            rare = 2;
            value = sellPrice(0, 2, 50);
            break;
        case 5069:
            mana = 5;
            damage = 8;
            useStyle = 1;
            shootSpeed = 10f;
            shoot = 951;
            buffType = 325;
            width = 26;
            height = 28;
            UseSound = SoundID.Item44;
            useAnimation = 36;
            useTime = 36;
            rare = 3;
            noMelee = true;
            knockBack = 2f;
            value = sellPrice(0, 0, 50);
            summon = true;
            autoReuse = true;
            reuseDelay = 2;
            break;
        case 5070:
            width = 16;
            height = 16;
            maxStack = CommonMaxStack;
            value = buyPrice(0, 0, 5);
            rare = 1;
            break;
        case 5071:
            width = 18;
            height = 14;
            headSlot = 272;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            vanity = true;
            break;
        case 5072:
            width = 18;
            height = 14;
            bodySlot = 242;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            vanity = true;
            break;
        case 5073:
            width = 18;
            height = 14;
            legSlot = 228;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            vanity = true;
            break;
        case 5074:
            DefaultToWhip(952, 27, 2f, 5f);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 1, 50));
            break;
        case 5075:
            width = 24;
            height = 24;
            accessory = true;
            vanity = true;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 1));
            hasVanityEffects = true;
            break;
        case 5076:
            width = 16;
            height = 24;
            accessory = true;
            vanity = true;
            balloonSlot = 18;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 20));
            hasVanityEffects = true;
            break;
        case 5077:
            width = 16;
            height = 16;
            accessory = true;
            vanity = true;
            shoeSlot = 25;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 20));
            break;
        case 5078:
            width = 18;
            height = 14;
            bodySlot = 243;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            vanity = true;
            break;
        case 5079:
            width = 18;
            height = 14;
            legSlot = 230;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            vanity = true;
            break;
        case 5080:
            width = 16;
            height = 16;
            accessory = true;
            vanity = true;
            frontSlot = 11;
            backSlot = 34;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 10));
            break;
        case 5081:
            DefaultToPlaceableTile((ushort)623, 0);
            SetShopValues(ItemRarityColor.Pink5, buyPrice(0, 10));
            break;
        case 5082:
            DefaultToPlaceableTile((ushort)623, 1);
            SetShopValues(ItemRarityColor.Pink5, buyPrice(0, 10));
            break;
        case 5083:
            DefaultToPlaceableTile((ushort)623, 2);
            SetShopValues(ItemRarityColor.Pink5, buyPrice(0, 10));
            break;
        case 5084:
            DefaultToPlaceableTile((ushort)623, 3);
            SetShopValues(ItemRarityColor.Pink5, buyPrice(0, 10));
            break;
        case 5085:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 2);
            placeStyle = 45;
            break;
        case 5086:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 2);
            placeStyle = 13;
            break;
        case 5087:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 2);
            placeStyle = 74;
            break;
        case 5088:
            DefaultToVanitypet(956, 327);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 25));
            value = buyPrice(0, 25);
            break;
        case 5089:
            DefaultToVanitypet(957, 328);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 25));
            value = buyPrice(0, 25);
            break;
        case 5090:
            DefaultToVanitypet(958, 329);
            value = buyPrice(0, 25);
            rare = -13;
            break;
        case 5091:
            DefaultToVanitypet(959, 330);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 5));
            break;
        case 5094:
            useStyle = 1;
            useTurn = false;
            useAnimation = 21;
            useTime = 21;
            width = 24;
            height = 28;
            damage = 20;
            knockBack = 5.5f;
            UseSound = SoundID.Item1;
            scale = 1.2f;
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 0, 50));
            melee = true;
            break;
        case 5095:
            useStyle = 1;
            autoReuse = true;
            useAnimation = 15;
            useTime = 15;
            width = 24;
            height = 28;
            damage = 27;
            knockBack = 5f;
            UseSound = SoundID.Item1;
            scale = 1.2f;
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 1, 50));
            melee = true;
            axe = 30;
            crit = 10;
            break;
        case 5096:
            useStyle = 1;
            useTurn = true;
            autoReuse = true;
            useAnimation = 20;
            useTime = 20;
            width = 24;
            height = 28;
            damage = 57;
            knockBack = 6.5f;
            UseSound = SoundID.Item1;
            scale = 1.2f;
            SetShopValues(ItemRarityColor.LightRed4, sellPrice(0, 1));
            melee = true;
            break;
        case 5097:
            useStyle = 1;
            useTurn = false;
            useAnimation = 45;
            useTime = 45;
            width = 24;
            height = 28;
            damage = 36;
            knockBack = 5.5f;
            UseSound = SoundID.Item1;
            scale = 1.15f;
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 0, 25));
            melee = true;
            break;
        case 5098:
            DefaultToVanitypet(960, 331);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 10));
            break;
        case 5099:
            width = 18;
            height = 14;
            headSlot = 273;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 1));
            vanity = true;
            break;
        case 5100:
            width = 18;
            height = 14;
            faceSlot = 19;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 2));
            accessory = true;
            expert = true;
            break;
        case 5101:
            width = 28;
            height = 20;
            headSlot = 275;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            vanity = true;
            break;
        case 5102:
            width = 18;
            height = 14;
            bodySlot = 244;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 40));
            vanity = true;
            break;
        case 5103:
            width = 18;
            height = 14;
            legSlot = 231;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 40));
            vanity = true;
            break;
        case 5104:
        case 5105:
        case 5106:
            width = 18;
            height = 14;
            maxStack = 1;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            beardSlot = (sbyte)(2 + (type - 5104));
            color = Main.player[Main.myPlayer].hairColor;
            accessory = true;
            vanity = true;
            break;
        case 5107:
            DefaultToAccessory(26, 30);
            neckSlot = 11;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            break;
        case 5109:
            width = 18;
            height = 18;
            headSlot = 276;
            rare = 1;
            value = sellPrice(0, 0, 75);
            vanity = true;
            break;
        case 5108:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 1);
            rare = 1;
            placeStyle = 75;
            break;
        case 5110:
            DefaultToPlaceableTile((ushort)617, 27);
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
            rare = -13;
            maxStack = CommonMaxStack;
            break;
        case 5111:
            maxStack = CommonMaxStack;
            consumable = true;
            width = 24;
            height = 24;
            rare = 3;
            expert = true;
            break;
        case 5112:
            DefaultToMusicBox(86);
            break;
        case 5113:
            DefaultToAccessory(26, 30);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            vanity = true;
            hasVanityEffects = true;
            break;
        case 5114:
            mana = 10;
            damage = 6;
            useStyle = 4;
            shootSpeed = 10f;
            shoot = 970;
            buffType = 335;
            width = 26;
            height = 28;
            UseSound = SoundID.AbigailSummon;
            useAnimation = 36;
            useTime = 36;
            rare = 3;
            noMelee = true;
            knockBack = 2f;
            value = sellPrice(0, 0, 50);
            summon = true;
            autoReuse = true;
            reuseDelay = 2;
            break;
        case 5115:
            width = 18;
            height = 14;
            bodySlot = 245;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 40));
            vanity = true;
            break;
        case 5116:
            width = 18;
            height = 14;
            legSlot = 232;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 40));
            vanity = true;
            break;
        case 5117:
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 1, 50));
            autoReuse = true;
            useStyle = 5;
            useAnimation = 15;
            useTime = 15;
            width = 24;
            height = 24;
            shoot = 968;
            UseSound = SoundID.Item61;
            useAmmo = AmmoID.Bullet;
            damage = 20;
            shootSpeed = 14f;
            knockBack = 1f;
            ranged = true;
            noMelee = true;
            break;
        case 5118:
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 1, 50));
            useStyle = 5;
            useAnimation = 45;
            useTime = 45;
            width = 24;
            height = 24;
            shoot = 969;
            UseSound = SoundID.Item66;
            damage = 13;
            shootSpeed = 1f;
            knockBack = 1f;
            magic = true;
            noMelee = true;
            mana = 30;
            break;
        case 5119:
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 1, 50));
            useStyle = 1;
            shootSpeed = 14f;
            shoot = 966;
            damage = 24;
            width = 18;
            height = 20;
            UseSound = SoundID.Item1;
            useAnimation = 30;
            useTime = 30;
            noMelee = true;
            knockBack = 7.5f;
            summon = true;
            mana = 20;
            sentry = true;
            break;
        case 5120:
            SetShopValues(ItemRarityColor.Blue1, 0);
            useStyle = 4;
            width = 22;
            height = 14;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            maxStack = CommonMaxStack;
            break;
        case 5121:
        case 5122:
        case 5123:
        case 5124:
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 20));
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            placeStyle = 46 + (type - 5121);
            break;
        case 5125:
            DefaultToMount(51);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 0, 50));
            break;
        case 5126:
            DefaultToAccessory(26, 30);
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 8));
            backSlot = 35;
            handOnSlot = 23;
            handOffSlot = 15;
            break;
        case 5131:
            DefaultToVanitypet(881, 341);
            value = buyPrice(0, 25);
            rare = -13;
            break;
        case 5127:
            DefaultToPlaceableTile((ushort)625, 0);
            SetShopValues(ItemRarityColor.Blue1, 0);
            break;
        case 5128:
            DefaultToPlaceableTile((ushort)627, 0);
            SetShopValues(ItemRarityColor.Blue1, 0);
            break;
        case 5132:
            DefaultToCapturedCritter(669);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 10));
            width = 20;
            height = 20;
            bait = 10;
            break;
        case 5133:
            DefaultToPlaceableTile((ushort)629, 0);
            maxStack = CommonMaxStack;
            break;
        case 5147:
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 15));
            useStyle = 1;
            useAnimation = 26;
            useTime = 26;
            width = 26;
            height = 28;
            shoot = 979;
            UseSound = SoundID.Item8;
            damage = 15;
            shootSpeed = 7f;
            magic = true;
            noMelee = true;
            mana = 2;
            crit = 10;
            if (Variant == ItemVariants.StrongerVariant)
            {
                value = sellPrice(0, 5, 5);
                rare = 4;
                damage = 42;
                useAnimation = 10;
                useTime = 10;
                mana = 6;
                shootSpeed = 12f;
                autoReuse = true;
            }
            break;
        case 5211:
            UseSound = SoundID.Item3;
            useStyle = 9;
            useTurn = true;
            useAnimation = 17;
            useTime = 17;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 14;
            height = 24;
            buffType = 343;
            buffTime = 18000;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 0, 2));
            break;
        case 5135:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 137;
            placeStyle = 5;
            width = 12;
            height = 12;
            mech = true;
            SetShopValues(ItemRarityColor.LightRed4, sellPrice(0, 0, 60));
            break;
        case 5212:
            useStyle = 1;
            autoReuse = true;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            noUseGraphic = true;
            makeNPC = 671;
            break;
        case 5213:
            DefaultToPlaceableTile((ushort)632, 0);
            maxStack = CommonMaxStack;
            break;
        case 5136:
            width = 18;
            height = 18;
            headSlot = 274;
            color = Main.player[Main.myPlayer].skinColor;
            rare = 1;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 5134:
            useStyle = 5;
            autoReuse = true;
            useAnimation = 30;
            useTime = 5;
            width = 50;
            height = 18;
            shoot = 145;
            useAmmo = AmmoID.Solution;
            UseSound = SoundID.Item34;
            knockBack = 0.3f;
            shootSpeed = 11f;
            noMelee = true;
            SetShopValues(ItemRarityColor.Green2, buyPrice(2));
            rare = 10;
            break;
        case 5214:
            autoReuse = true;
            useTurn = true;
            useStyle = 1;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 633;
            width = 14;
            height = 14;
            value = 150;
            break;
        case 5215:
            DefaultToPlaceableTile((ushort)635, 0);
            break;
        case 5216:
            DefaultToPlaceableWall(316);
            break;
        case 5217:
            DefaultToPlaceableWall(317);
            break;
        case 5148:
            DefaultToPlaceableTile((ushort)90, 40);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5149:
            DefaultToPlaceableTile((ushort)79, 40);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 5150:
            DefaultToPlaceableTile((ushort)101, 41);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5151:
            DefaultToPlaceableTile((ushort)88, 40);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5152:
            DefaultToPlaceableTile((ushort)100, 40);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5153:
            DefaultToPlaceableTile((ushort)33, 39);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 5154:
            DefaultToPlaceableTile((ushort)15, 45);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 5155:
            DefaultToPlaceableTile((ushort)34, 46);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 5156:
            DefaultToPlaceableTile((ushort)467, 14);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 5157:
            DefaultToPlaceableTile((ushort)104, 41);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5158:
            DefaultToPlaceableTile((ushort)10, 46);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 5159:
            DefaultToPlaceableTile((ushort)93, 40);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 5160:
            DefaultToPlaceableTile((ushort)42, 46);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 5161:
            DefaultToPlaceableTile((ushort)87, 40);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5162:
            DefaultToPlaceableTile((ushort)19, 45);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 5163:
            DefaultToPlaceableTile((ushort)172, 41);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5164:
            DefaultToPlaceableTile((ushort)89, 44);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5165:
            DefaultToPlaceableTile((ushort)469, 9);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 5166:
            DefaultToPlaceableTile((ushort)18, 41);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 5168:
            DefaultToPlaceableTile((ushort)497, 40);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 5167:
            DefaultToPlaceableTile((ushort)468, 14);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 5169:
            DefaultToPlaceableTile((ushort)90, 41);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5170:
            DefaultToPlaceableTile((ushort)79, 41);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 5171:
            DefaultToPlaceableTile((ushort)101, 42);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5172:
            DefaultToPlaceableTile((ushort)88, 41);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5173:
            DefaultToPlaceableTile((ushort)100, 41);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5174:
            DefaultToPlaceableTile((ushort)33, 40);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 5175:
            DefaultToPlaceableTile((ushort)15, 46);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 5176:
            DefaultToPlaceableTile((ushort)34, 47);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 5177:
            DefaultToPlaceableTile((ushort)467, 15);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 5178:
            DefaultToPlaceableTile((ushort)104, 42);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5179:
            DefaultToPlaceableTile((ushort)10, 47);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 5180:
            DefaultToPlaceableTile((ushort)93, 41);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 5181:
            DefaultToPlaceableTile((ushort)42, 47);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 5182:
            DefaultToPlaceableTile((ushort)87, 41);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5183:
            DefaultToPlaceableTile((ushort)19, 46);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 5184:
            DefaultToPlaceableTile((ushort)172, 42);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5185:
            DefaultToPlaceableTile((ushort)89, 45);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5186:
            DefaultToPlaceableTile((ushort)469, 10);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 5187:
            DefaultToPlaceableTile((ushort)18, 42);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 5189:
            DefaultToPlaceableTile((ushort)497, 41);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 5188:
            DefaultToPlaceableTile((ushort)468, 15);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 5190:
            DefaultToPlaceableTile((ushort)90, 42);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5191:
            DefaultToPlaceableTile((ushort)79, 42);
            SetShopValues(ItemRarityColor.White0, 2000);
            maxStack = CommonMaxStack;
            width = 28;
            height = 20;
            break;
        case 5192:
            DefaultToPlaceableTile((ushort)101, 43);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5193:
            DefaultToPlaceableTile((ushort)88, 42);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5194:
            DefaultToPlaceableTile((ushort)100, 42);
            SetShopValues(ItemRarityColor.White0, 1500);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5195:
            DefaultToPlaceableTile((ushort)33, 41);
            SetShopValues(ItemRarityColor.White0, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 0, 60);
            noWet = true;
            break;
        case 5196:
            DefaultToPlaceableTile((ushort)15, 47);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 30;
            break;
        case 5197:
            DefaultToPlaceableTile((ushort)34, 48);
            SetShopValues(ItemRarityColor.White0, 3000);
            maxStack = CommonMaxStack;
            width = 26;
            height = 26;
            break;
        case 5198:
            DefaultToPlaceableTile((ushort)467, 16);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 5199:
            DefaultToPlaceableTile((ushort)104, 43);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5200:
            DefaultToPlaceableTile((ushort)10, 48);
            SetShopValues(ItemRarityColor.White0, 200);
            maxStack = CommonMaxStack;
            width = 14;
            height = 28;
            break;
        case 5201:
            DefaultToPlaceableTile((ushort)93, 42);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 10;
            height = 24;
            break;
        case 5202:
            DefaultToPlaceableTile((ushort)42, 48);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 12;
            height = 28;
            break;
        case 5203:
            DefaultToPlaceableTile((ushort)87, 42);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5204:
            DefaultToPlaceableTile((ushort)19, 47);
            SetShopValues(ItemRarityColor.White0, 0);
            width = 8;
            height = 10;
            break;
        case 5205:
            DefaultToPlaceableTile((ushort)172, 43);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5206:
            DefaultToPlaceableTile((ushort)89, 46);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5207:
            DefaultToPlaceableTile((ushort)469, 11);
            SetShopValues(ItemRarityColor.White0, 300);
            maxStack = CommonMaxStack;
            width = 26;
            height = 20;
            break;
        case 5208:
            DefaultToPlaceableTile((ushort)18, 43);
            SetShopValues(ItemRarityColor.White0, 150);
            maxStack = CommonMaxStack;
            width = 28;
            height = 14;
            break;
        case 5210:
            DefaultToPlaceableTile((ushort)497, 42);
            maxStack = CommonMaxStack;
            value = 150;
            break;
        case 5209:
            DefaultToPlaceableTile((ushort)468, 16);
            SetShopValues(ItemRarityColor.White0, 500);
            maxStack = CommonMaxStack;
            width = 26;
            height = 22;
            break;
        case 5130:
            useStyle = 4;
            channel = true;
            width = 10;
            height = 32;
            UseSound = SoundID.Item25;
            useAnimation = 20;
            useTime = 20;
            rare = 8;
            noMelee = true;
            noUseGraphic = true;
            mountType = 52;
            value = sellPrice(0, 5);
            break;
        case 5137:
            DefaultToPlaceableTile((ushort)630, 0);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 0, 10));
            maxStack = CommonMaxStack;
            break;
        case 5138:
            DefaultToPlaceableTile((ushort)631, 0);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 0, 10));
            maxStack = CommonMaxStack;
            break;
        case 5218:
        case 5219:
        case 5220:
        case 5221:
        case 5222:
        case 5223:
        case 5224:
        case 5225:
        case 5226:
        case 5227:
        case 5228:
        case 5229:
        case 5230:
        case 5231:
        case 5232:
        case 5233:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 76 + (type - 5218);
            if (type == 5231)
            {
                value = sellPrice(0, 0, 20);
            }
            if (type == 5228)
            {
                value = sellPrice(0, 2);
            }
            if (type == 5222)
            {
                value = sellPrice(0, 2);
            }
            break;
        case 5234:
        case 5235:
        case 5236:
        case 5237:
        case 5238:
        case 5239:
        case 5240:
        case 5241:
        case 5242:
        case 5243:
        case 5244:
        case 5245:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 50 + (type - 5234);
            if (type == 5243)
            {
                value = sellPrice(0, 0, 60);
            }
            if (type == 5245)
            {
                value = sellPrice(0, 0, 20);
            }
            if (type == 5235)
            {
                value = sellPrice(0, 0, 50);
            }
            break;
        case 5246:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 14;
            break;
        case 5247:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 15;
            break;
        case 5248:
        case 5249:
        case 5250:
        case 5251:
        case 5252:
        case 5253:
        case 5254:
        case 5255:
        case 5256:
        case 5257:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 245;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 19 + (type - 5248);
            if (type == 5251)
            {
                value = sellPrice(0, 0, 20);
            }
            if (type == 5253)
            {
                value = sellPrice(0, 0, 20);
            }
            if (type == 5257)
            {
                value = sellPrice(0, 0, 20);
            }
            if (type == 5252)
            {
                value = sellPrice(0, 0, 50);
            }
            if (type == 5256)
            {
                value = sellPrice(0, 0, 50);
            }
            break;
        case 5258:
        case 5259:
        case 5260:
        case 5261:
        case 5262:
        case 5263:
        case 5264:
        case 5265:
        case 5266:
        case 5267:
        case 5268:
        case 5269:
        case 5270:
        case 5271:
        case 5272:
        case 5273:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 246;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 21 + (type - 5258);
            if (type == 5266)
            {
                value = sellPrice(0, 2);
            }
            if (type == 5259)
            {
                value = sellPrice(0, 0, 50);
            }
            if (type == 5265)
            {
                value = sellPrice(0, 0, 50);
            }
            if (type == 5264)
            {
                value = sellPrice(0, 0, 50);
            }
            if (type == 5263)
            {
                value = sellPrice(0, 0, 50);
            }
            break;
        case 5129:
            SetWeaponValues(15, 5f);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 0, 35));
            useStyle = 1;
            useTurn = false;
            useAnimation = 17;
            useTime = 17;
            width = 24;
            height = 28;
            UseSound = SoundID.Item1;
            scale = 1f;
            melee = true;
            break;
        case 5274:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 62;
            break;
        case 5139:
            DefaultToAccessory(14, 30);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            break;
        case 5140:
        case 5141:
        case 5142:
        case 5143:
        case 5144:
        case 5145:
        case 5146:
            DefaultToAccessory(14, 30);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 1));
            switch (type)
            {
            case 5140:
                glowMask = 318;
                break;
            case 5141:
                glowMask = 319;
                break;
            case 5142:
                glowMask = 320;
                break;
            case 5143:
                glowMask = 321;
                break;
            case 5144:
                glowMask = 322;
                break;
            case 5145:
                glowMask = 323;
                break;
            case 5146:
                glowMask = 324;
                break;
            }
            break;
        case 5276:
            DefaultToVanitypet(994, 345);
            width = 32;
            height = 32;
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 1));
            break;
        case 5279:
            width = 18;
            height = 18;
            defense = 2;
            headSlot = 278;
            if (Variant == ItemVariants.WeakerVariant)
            {
                defense = 1;
            }
            break;
        case 5280:
            width = 18;
            height = 18;
            defense = 3;
            bodySlot = 246;
            if (Variant == ItemVariants.WeakerVariant)
            {
                defense = 1;
            }
            break;
        case 5281:
            width = 18;
            height = 18;
            defense = 2;
            legSlot = 234;
            if (Variant == ItemVariants.WeakerVariant)
            {
                defense = 1;
            }
            break;
        case 5282:
            useStyle = 5;
            useAnimation = 25;
            useTime = 25;
            width = 12;
            height = 28;
            shoot = 1;
            useAmmo = AmmoID.Arrow;
            UseSound = SoundID.Item5;
            damage = 10;
            shootSpeed = 6.6f;
            noMelee = true;
            value = 100;
            ranged = true;
            if (Variant == ItemVariants.WeakerVariant)
            {
                damage = 6;
                useAnimation = 29;
                useTime = 29;
            }
            break;
        case 5283:
            autoReuse = true;
            useStyle = 1;
            useTurn = true;
            useAnimation = 30;
            useTime = 20;
            hammer = 45;
            width = 24;
            height = 28;
            damage = 9;
            knockBack = 5.5f;
            scale = 1f;
            UseSound = SoundID.Item1;
            value = 50;
            melee = true;
            if (Variant == ItemVariants.WeakerVariant)
            {
                damage = 4;
                hammer = 35;
            }
            break;
        case 5284:
            useStyle = 1;
            useTurn = false;
            useAnimation = 17;
            useTime = 17;
            width = 24;
            height = 28;
            damage = 13;
            knockBack = 5f;
            UseSound = SoundID.Item1;
            scale = 1f;
            value = sellPrice(0, 0, 0, 20);
            melee = true;
            if (Variant == ItemVariants.WeakerVariant)
            {
                damage = 8;
                useAnimation = 23;
                useTime = 23;
            }
            break;
        case 5285:
            DefaultToThrownWeapon(996, 20, 8f);
            UseSound = SoundID.Item106;
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 3));
            width = 18;
            height = 18;
            break;
        case 5286:
            DefaultToPlaceableTile((ushort)12, 0);
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 7, 50));
            break;
        case 5287:
            DefaultToPlaceableTile((ushort)639, 0);
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 0, 25));
            break;
        case 5288:
            DefaultToMount(53);
            SetShopValues(ItemRarityColor.Yellow8, buyPrice(0, 5));
            break;
        case 5289:
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 2));
            maxStack = CommonMaxStack;
            consumable = true;
            width = 18;
            height = 18;
            useStyle = 4;
            useTime = 30;
            UseSound = SoundID.Item4;
            useAnimation = 30;
            expert = true;
            break;
        case 5290:
            width = 28;
            height = 20;
            headSlot = 279;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            vanity = true;
            break;
        case 5294:
            useStyle = 5;
            width = 24;
            height = 24;
            noUseGraphic = true;
            UseSound = SoundID.Item1;
            melee = true;
            channel = true;
            noMelee = true;
            shoot = 999;
            useAnimation = 25;
            useTime = 25;
            shootSpeed = 10f;
            knockBack = 3.75f;
            damage = 24;
            value = sellPrice(0, 0, 70);
            rare = 3;
            break;
        case 5293:
            DefaultToTorch(22);
            break;
        case 5299:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 215;
            placeStyle = 14;
            width = 12;
            height = 12;
            break;
        case 5298:
            noMelee = true;
            useStyle = 1;
            shootSpeed = 11.5f;
            shoot = 1000;
            damage = 21;
            knockBack = 4.5f;
            width = 14;
            height = 28;
            UseSound = SoundID.Item1;
            useAnimation = 20;
            useTime = 20;
            noUseGraphic = true;
            SetShopValues(ItemRarityColor.Orange3, sellPrice(0, 2));
            melee = true;
            autoReuse = true;
            break;
        case 5300:
            useStyle = 1;
            autoReuse = true;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            noUseGraphic = true;
            makeNPC = 672;
            break;
        case 5301:
            DefaultToPlaceableTile((ushort)640, 0);
            maxStack = CommonMaxStack;
            break;
        case 5302:
            useStyle = 1;
            useTurn = true;
            useAnimation = 12;
            useTime = 5;
            width = 20;
            height = 20;
            autoReuse = true;
            rare = 7;
            value = sellPrice(0, 10);
            tileBoost += 2;
            break;
        case 5303:
            useStyle = 1;
            useTurn = true;
            useAnimation = 12;
            useTime = 5;
            width = 20;
            height = 20;
            autoReuse = true;
            rare = 7;
            value = sellPrice(0, 10);
            tileBoost += 2;
            break;
        case 5304:
            useStyle = 1;
            useTurn = true;
            useAnimation = 8;
            useTime = 3;
            width = 20;
            height = 20;
            autoReuse = true;
            rare = 8;
            value = sellPrice(0, 30);
            tileBoost += 3;
            break;
        case 5292:
            DefaultToPlaceableTile((ushort)19, 48);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 1));
            width = 8;
            height = 10;
            break;
        case 5291:
            DefaultToPlaceableWall(318);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 0, 50));
            break;
        case 5306:
            DefaultToPlaceableTile((ushort)641, 0);
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 0, 20));
            break;
        case 5307:
            DefaultToPlaceableWall(319);
            break;
        case 5296:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 642;
            width = 26;
            height = 20;
            rare = 7;
            value = 100000;
            break;
        case 5295:
            useStyle = 1;
            autoReuse = true;
            useAnimation = 24;
            useTime = 12;
            width = 24;
            height = 28;
            damage = 20;
            knockBack = 5f;
            UseSound = SoundID.Item1;
            scale = 1f;
            SetShopValues(ItemRarityColor.LightRed4, sellPrice(0, 1, 50));
            melee = true;
            axe = 30;
            createTile = 2;
            break;
        case 5305:
            width = 18;
            height = 18;
            headSlot = 277;
            color = Main.player[Main.myPlayer].skinColor;
            rare = 1;
            vanity = true;
            value = sellPrice(0, 0, 50);
            break;
        case 5297:
            DefaultToVanitypet(998, 349);
            width = 32;
            height = 32;
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 25));
            break;
        case 5308:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 20);
            placeStyle = 63;
            break;
        case 5309:
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
            width = 30;
            height = 30;
            break;
        case 5310:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 2);
            placeStyle = 64;
            break;
        case 5311:
            useStyle = 1;
            autoReuse = true;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            noUseGraphic = true;
            makeNPC = 673;
            break;
        case 5314:
            DefaultToPlaceableTile((ushort)643, 0);
            maxStack = CommonMaxStack;
            break;
        case 5312:
            useStyle = 1;
            autoReuse = true;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            noUseGraphic = true;
            makeNPC = 674;
            break;
        case 5315:
            DefaultToPlaceableTile((ushort)644, 0);
            maxStack = CommonMaxStack;
            break;
        case 5313:
            useStyle = 1;
            autoReuse = true;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            noUseGraphic = true;
            makeNPC = 675;
            break;
        case 5316:
            DefaultToPlaceableTile((ushort)645, 0);
            maxStack = CommonMaxStack;
            break;
        case 5317:
            DefaultToPlaceableTile((ushort)105, 80);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5318:
            DefaultToPlaceableTile((ushort)105, 81);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5319:
            DefaultToPlaceableTile((ushort)105, 82);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5320:
            DefaultToPlaceableTile((ushort)13, 1);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 60));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5321:
            DefaultToPlaceableTile((ushort)13, 2);
            SetShopValues(ItemRarityColor.White0, sellPrice(0, 0, 0, 20));
            maxStack = CommonMaxStack;
            width = 20;
            height = 20;
            break;
        case 5322:
            DefaultToPlaceableTile((ushort)646, 0);
            SetShopValues(ItemRarityColor.Blue1, 0);
            maxStack = CommonMaxStack;
            width = 8;
            height = 18;
            value = sellPrice(0, 0, 1);
            holdStyle = 1;
            noWet = true;
            flame = true;
            break;
        case 5323:
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 10));
            width = 30;
            height = 30;
            break;
        case 5324:
        case 5329:
        case 5330:
            DefaultToPlaceableTile((ushort)647, 0);
            maxStack = 1;
            SetShopValues(ItemRarityColor.StrongRed10, sellPrice(0, 5));
            consumable = false;
            tileBoost = 3;
            break;
        case 5326:
            DefaultToFood(22, 22, 0, 0);
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 10));
            maxStack = 1;
            break;
        case 5327:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 654;
            width = 28;
            height = 14;
            break;
        case 5328:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 8;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            width = 12;
            height = 12;
            break;
        case 5331:
            width = 16;
            height = 24;
            accessory = true;
            balloonSlot = 19;
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 4));
            hasVanityEffects = true;
            break;
        case 5332:
            DefaultToVanitypet(1003, 351);
            width = 32;
            height = 32;
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 10));
            break;
        case 5333:
            DefaultToVanitypet(1004, 352);
            width = 32;
            height = 32;
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 10));
            break;
        case 5334:
            width = 22;
            height = 14;
            if (Variant == ItemVariants.EnabledVariant)
            {
                useStyle = 4;
                consumable = true;
                useAnimation = 45;
                useTime = 45;
            }
            maxStack = CommonMaxStack;
            rare = 3;
            break;
        case 5335:
            autoReuse = false;
            useStyle = 1;
            useAnimation = 20;
            useTime = 20;
            width = 20;
            height = 20;
            UseSound = SoundID.Item8;
            SetShopValues(ItemRarityColor.StrongRed10, sellPrice(0, 10));
            break;
        case 5336:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.LightPurple6, 0);
            break;
        case 5337:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 1, 50));
            break;
        case 5338:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 2));
            break;
        case 5339:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 0, 25));
            break;
        case 5340:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 15));
            break;
        case 5341:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 10));
            break;
        case 5342:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 0, 50));
            break;
        case 5343:
            useStyle = 4;
            consumable = true;
            useAnimation = 45;
            useTime = 45;
            UseSound = SoundID.Item92;
            width = 28;
            height = 28;
            maxStack = CommonMaxStack;
            SetShopValues(ItemRarityColor.LightPurple6, sellPrice(0, 0, 25));
            break;
        case 5345:
            DefaultToPlaceableTile((ushort)657, 0);
            width = 22;
            height = 32;
            rare = 9;
            value = sellPrice(0, 1);
            accessory = true;
            vanity = true;
            break;
        case 5344:
            paintCoating = 2;
            width = 24;
            height = 24;
            value = buyPrice(0, 0, 2);
            maxStack = CommonMaxStack;
            break;
        case 5346:
            width = 18;
            height = 18;
            SetShopValues(ItemRarityColor.Green2, sellPrice(0, 0, 30));
            break;
        case 5356:
            width = 18;
            height = 18;
            SetShopValues(ItemRarityColor.TrashMinus1, 0);
            break;
        case 5347:
            DefaultToPlaceableTile((ushort)658, 0);
            width = 22;
            height = 32;
            rare = 9;
            value = sellPrice(0, 1);
            accessory = true;
            vanity = true;
            break;
        case 5348:
            shootSpeed = 3f;
            shoot = 1006;
            damage = 12;
            width = 10;
            height = 28;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Arrow;
            knockBack = 2f;
            ranged = true;
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 0, 0, 10));
            break;
        case 5349:
            DefaultToPlaceableTile((ushort)659, 0);
            rare = 1;
            break;
        case 5350:
            DefaultToCapturedCritter(677);
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 0, 2, 50));
            width = 12;
            height = 12;
            break;
        case 5351:
            DefaultToPlaceableTile((ushort)660, 0);
            maxStack = CommonMaxStack;
            break;
        case 5352:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 91;
            placeStyle = 310;
            width = 10;
            height = 24;
            value = 1000;
            rare = 1;
            break;
        case 5353:
            DefaultToTorch(23);
            break;
        case 5354:
            DefaultToAccessory(28, 32);
            faceSlot = 20;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 2));
            break;
        case 5355:
            DefaultToAccessory(26, 36);
            backSlot = 36;
            frontSlot = 12;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 2));
            break;
        case 5357:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 215;
            placeStyle = 15;
            width = 12;
            height = 12;
            break;
        case 5358:
        case 5437:
            useTurn = true;
            width = 20;
            height = 20;
            useStyle = 4;
            useTime = 90;
            UseSound = SoundID.Item6;
            useAnimation = 90;
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 10));
            break;
        case 5359:
            useTurn = true;
            width = 20;
            height = 20;
            useStyle = 4;
            useTime = 90;
            UseSound = SoundID.Item6;
            useAnimation = 90;
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 10));
            break;
        case 5360:
            useTurn = true;
            width = 20;
            height = 20;
            useStyle = 4;
            useTime = 90;
            UseSound = SoundID.Item6;
            useAnimation = 90;
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 10));
            break;
        case 5361:
            useTurn = true;
            width = 20;
            height = 20;
            useStyle = 4;
            useTime = 90;
            UseSound = SoundID.Item6;
            useAnimation = 90;
            SetShopValues(ItemRarityColor.Yellow8, sellPrice(0, 10));
            break;
        case 5362:
            DefaultToMusicBox(87);
            break;
        case 5363:
            DefaultToPlaceableWall(62);
            break;
        case 5364:
            useStyle = 1;
            useTurn = true;
            useAnimation = 12;
            useTime = 5;
            width = 20;
            height = 20;
            autoReuse = true;
            rare = 10;
            value = sellPrice(0, 10);
            tileBoost += 2;
            break;
        case 5365:
            DefaultToPlaceableWall(7);
            break;
        case 5366:
            DefaultToPlaceableWall(94);
            break;
        case 5367:
            DefaultToPlaceableWall(95);
            break;
        case 5368:
            DefaultToPlaceableWall(9);
            break;
        case 5369:
            DefaultToPlaceableWall(96);
            break;
        case 5370:
            DefaultToPlaceableWall(97);
            break;
        case 5371:
            DefaultToPlaceableWall(8);
            break;
        case 5372:
            DefaultToPlaceableWall(98);
            break;
        case 5373:
            DefaultToPlaceableWall(99);
            break;
        case 5374:
            DefaultToPlaceableWall(187);
            break;
        case 5375:
            DefaultToPlaceableWall(216);
            break;
        case 5376:
            DefaultToPlaceableWall(87);
            break;
        case 5377:
            shootSpeed = 6f;
            shoot = 1008;
            damage = 1;
            width = 12;
            height = 12;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Flare;
            knockBack = 1.5f;
            rare = 1;
            value = buyPrice(0, 0, 1, 50);
            ranged = true;
            break;
        case 5378:
            shootSpeed = 6f;
            shoot = 1009;
            damage = 1;
            width = 12;
            height = 12;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Flare;
            knockBack = 1.5f;
            value = 7;
            ranged = true;
            break;
        case 5379:
            shootSpeed = 6f;
            shoot = 1010;
            damage = 1;
            width = 12;
            height = 12;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Flare;
            knockBack = 1.5f;
            value = 7;
            ranged = true;
            break;
        case 5380:
            shootSpeed = 6f;
            shoot = 1011;
            damage = 1;
            width = 12;
            height = 12;
            maxStack = CommonMaxStack;
            consumable = true;
            ammo = AmmoID.Flare;
            knockBack = 1.5f;
            value = 7;
            ranged = true;
            break;
        case 5381:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 663;
            width = 18;
            height = 34;
            SetShopValues(ItemRarityColor.Lime7, sellPrice(0, 3));
            break;
        case 5382:
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 3));
            autoReuse = true;
            UseSound = SoundID.Item1;
            useStyle = 1;
            damage = 50;
            useAnimation = 23;
            useTime = 23;
            width = 30;
            height = 30;
            shoot = 1012;
            shootSpeed = 11f;
            knockBack = 4.75f;
            melee = true;
            shootsEveryUse = true;
            break;
        case 5383:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 664;
            width = 18;
            height = 18;
            SetShopValues(ItemRarityColor.Pink5, sellPrice(0, 0, 0, 15));
            break;
        case 5384:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 665;
            width = 18;
            height = 18;
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 7, 50));
            break;
        case 5385:
            width = 28;
            height = 20;
            headSlot = 280;
            SetShopValues(ItemRarityColor.Blue1, sellPrice(0, 0, 50));
            vanity = true;
            break;
        case 5386:
            width = 18;
            height = 14;
            bodySlot = 247;
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 1));
            vanity = true;
            break;
        case 5387:
            width = 18;
            height = 14;
            legSlot = 235;
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 1));
            vanity = true;
            break;
        case 5389:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 242;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 65;
            break;
        case 5388:
            useStyle = 1;
            useTurn = true;
            useAnimation = 15;
            useTime = 10;
            autoReuse = true;
            maxStack = CommonMaxStack;
            consumable = true;
            createTile = 240;
            width = 30;
            height = 30;
            value = sellPrice(0, 0, 10);
            placeStyle = 92;
            break;
        case 5390:
            width = 28;
            height = 20;
            headSlot = 281;
            SetShopValues(ItemRarityColor.Orange3, buyPrice(0, 1));
            vanity = true;
            break;
        case 5391:
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
            width = 30;
            height = 30;
            break;
        case 5397:
            DefaultToPlaceableWall(321);
            break;
        case 5398:
            DefaultToPlaceableTile((ushort)667, 0);
            rare = 1;
            break;
        case 5399:
            DefaultToPlaceableWall(322);
            break;
        case 5392:
            DefaultToSolution(1015);
            break;
        case 5393:
            DefaultToSolution(1016);
            break;
        case 5394:
            DefaultToSolution(1017);
            break;
        case 5401:
            DefaultToPlaceableTile((ushort)669, 0);
            rare = 9;
            break;
        case 5402:
            DefaultToPlaceableTile((ushort)670, 0);
            rare = 9;
            break;
        case 5403:
            DefaultToPlaceableTile((ushort)671, 0);
            rare = 9;
            break;
        case 5404:
            DefaultToPlaceableTile((ushort)672, 0);
            rare = 9;
            break;
        case 5405:
            DefaultToPlaceableTile((ushort)673, 0);
            rare = 9;
            break;
        case 5406:
            DefaultToPlaceableTile((ushort)674, 0);
            rare = 9;
            break;
        case 5407:
            DefaultToPlaceableTile((ushort)675, 0);
            rare = 9;
            break;
        case 5408:
            DefaultToPlaceableTile((ushort)676, 0);
            rare = 9;
            break;
        case 5409:
            DefaultToPlaceableWall(323);
            rare = 9;
            break;
        case 5410:
            DefaultToPlaceableWall(324);
            rare = 9;
            break;
        case 5411:
            DefaultToPlaceableWall(325);
            rare = 9;
            break;
        case 5412:
            DefaultToPlaceableWall(326);
            rare = 9;
            break;
        case 5413:
            DefaultToPlaceableWall(327);
            rare = 9;
            break;
        case 5414:
            DefaultToPlaceableWall(328);
            rare = 9;
            break;
        case 5415:
            DefaultToPlaceableWall(329);
            rare = 9;
            break;
        case 5416:
            DefaultToPlaceableWall(330);
            rare = 9;
            break;
        case 5417:
            DefaultToPlaceableTile((ushort)677, 0);
            break;
        case 5418:
            DefaultToPlaceableWall(331);
            break;
        case 5419:
            DefaultToPlaceableTile((ushort)678, 0);
            break;
        case 5420:
            DefaultToPlaceableWall(332);
            break;
        case 5421:
            DefaultToPlaceableTile((ushort)679, 0);
            break;
        case 5422:
            DefaultToPlaceableWall(333);
            break;
        case 5423:
            DefaultToPlaceableTile((ushort)680, 0);
            break;
        case 5424:
            DefaultToPlaceableWall(334);
            break;
        case 5425:
            DefaultToPlaceableTile((ushort)681, 0);
            break;
        case 5426:
            DefaultToPlaceableWall(335);
            break;
        case 5427:
            DefaultToPlaceableTile((ushort)682, 0);
            break;
        case 5428:
            DefaultToPlaceableWall(336);
            break;
        case 5429:
            DefaultToPlaceableTile((ushort)685, 0);
            break;
        case 5430:
            DefaultToPlaceableWall(339);
            break;
        case 5431:
            DefaultToPlaceableTile((ushort)686, 0);
            break;
        case 5432:
            DefaultToPlaceableWall(340);
            break;
        case 5433:
            DefaultToPlaceableTile((ushort)683, 0);
            break;
        case 5434:
            DefaultToPlaceableWall(337);
            break;
        case 5435:
            DefaultToPlaceableTile((ushort)684, 0);
            break;
        case 5436:
            DefaultToPlaceableWall(338);
            break;
        case 5400:
            DefaultToVanitypet(1018, 354);
            width = 16;
            height = 16;
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 0, 10));
            break;
        case 5395:
            DefaultToPlaceableTile((ushort)666, 0);
            break;
        case 5396:
            DefaultToPlaceableWall(320);
            break;
        case 5439:
            DefaultToPlaceableTile((ushort)687, 0);
            break;
        case 5440:
            DefaultToPlaceableTile((ushort)688, 0);
            break;
        case 5441:
            DefaultToPlaceableTile((ushort)689, 0);
            break;
        case 5442:
            DefaultToPlaceableTile((ushort)690, 0);
            break;
        case 5443:
            DefaultToPlaceableTile((ushort)691, 0);
            break;
        case 5444:
            DefaultToPlaceableTile((ushort)692, 0);
            break;
        case 5445:
            DefaultToPlaceableWall(341);
            break;
        case 5446:
            DefaultToPlaceableWall(342);
            break;
        case 5447:
            DefaultToPlaceableWall(343);
            break;
        case 5448:
            DefaultToPlaceableWall(344);
            break;
        case 5449:
            DefaultToPlaceableWall(345);
            break;
        case 5450:
            DefaultToPlaceableWall(346);
            break;
        case 5438:
            useStyle = 1;
            shootSpeed = 3f;
            shoot = 1019;
            width = 16;
            height = 24;
            maxStack = CommonMaxStack;
            consumable = true;
            UseSound = SoundID.Item1;
            useAnimation = 15;
            value = sellPrice(0, 0, 0, 10);
            useTime = 15;
            noMelee = true;
            break;
        case 5451:
            useStyle = 1;
            autoReuse = false;
            useAnimation = 32;
            holdStyle = 7;
            useTime = 32;
            width = 32;
            height = 20;
            noUseGraphic = true;
            shoot = 1020;
            UseSound = SoundID.Item1;
            shootSpeed = 9f;
            value = buyPrice(0, 10);
            rare = 3;
            break;
        case 5452:
            width = 16;
            height = 24;
            accessory = true;
            rare = 3;
            value = buyPrice(0, 10);
            faceSlot = 21;
            break;
        case 5453:
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
            width = 30;
            height = 30;
            break;
        case 5454:
            SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 5));
            width = 30;
            height = 30;
            break;
        case 5455:
            SetShopValues(ItemRarityColor.Green2, buyPrice(0, 10));
            width = 30;
            height = 30;
            break;
        case 4009:
        case 4010:
        case 4011:
        case 4012:
        case 4013:
        case 4014:
        case 4015:
        case 4016:
        case 4017:
        case 4018:
        case 4019:
        case 4020:
        case 4021:
        case 4022:
        case 4023:
        case 4024:
        case 4025:
        case 4026:
        case 4027:
        case 4028:
        case 4029:
        case 4030:
        case 4031:
        case 4032:
        case 4033:
        case 4034:
        case 4035:
        case 4036:
        case 4037:
        case 4282:
        case 4283:
        case 4284:
        case 4285:
        case 4286:
        case 4287:
        case 4288:
        case 4289:
        case 4290:
        case 4291:
        case 4292:
        case 4293:
        case 4294:
        case 4295:
        case 4296:
        case 4297:
        case 4403:
        case 4411:
        case 4614:
        case 4615:
        case 4616:
        case 4617:
        case 4618:
        case 4619:
        case 4620:
        case 4621:
        case 4622:
        case 4623:
        case 4624:
        case 4625:
        case 5009:
        case 5013:
        case 5041:
        case 5042:
        case 5092:
        case 5093:
        case 5275:
        case 5277:
        case 5278:
            break;
        }
    }
References Terraria.ID.SoundID.AbigailSummon, Terraria.Item.accessory, Terraria.Item.ammo, Terraria.ID.AmmoID.Arrow, Terraria.Item.autoReuse, Terraria.Item.axe, Terraria.Item.backSlot, Terraria.Item.bait, Terraria.Item.balloonSlot, Terraria.Item.beardSlot, Terraria.Item.bodySlot, Terraria.Item.buffTime, Terraria.Item.buffType, Terraria.ID.AmmoID.Bullet, Terraria.Item.buyPrice(), Terraria.Item.channel, Terraria.Item.color, Terraria.Item.CommonMaxStack, Terraria.Item.consumable, Terraria.Item.createTile, Terraria.Item.createWall, Terraria.Item.crit, Terraria.Item.damage, Terraria.Item.DefaultToAccessory(), Terraria.Item.DefaultToBow(), Terraria.Item.DefaultToCapturedCritter(), Terraria.Item.DefaultToFood(), Terraria.Item.DefaultToGolfBall(), Terraria.Item.DefaultToGolfClub(), Terraria.Item.DefaultToGuitar(), Terraria.Item.DefaultToHeadgear(), Terraria.Item.DefaultTokite(), Terraria.Item.DefaultToLawnMower(), Terraria.Item.DefaultToMagicWeapon(), Terraria.Item.DefaultToMount(), Terraria.Item.DefaultToMusicBox(), Terraria.Item.DefaultToPlaceableTile(), Terraria.Item.DefaultToPlaceableWall(), Terraria.Item.DefaultToQuestFish(), Terraria.Item.DefaultToRangedWeapon(), Terraria.Item.DefaultToSeaShell(), Terraria.Item.DefaultToSolution(), Terraria.Item.DefaultToSpear(), Terraria.Item.DefaultToStaff(), Terraria.Item.DefaultToThrownWeapon(), Terraria.Item.DefaultToTorch(), Terraria.Item.DefaultToVanitypet(), Terraria.Item.DefaultToWhip(), Terraria.Item.defense, Terraria.GameContent.Items.ItemVariants.EnabledVariant, Terraria.Item.expert, Terraria.Item.faceSlot, Terraria.ID.AmmoID.FallenStar, Terraria.Item.fishingPole, Terraria.Item.flame, Terraria.ID.AmmoID.Flare, Terraria.Item.frontSlot, Terraria.Item.glowMask, Terraria.Player.hairColor, Terraria.Item.hammer, Terraria.Item.handOffSlot, Terraria.Item.handOnSlot, Terraria.Item.hasVanityEffects, Terraria.Item.headSlot, Terraria.Entity.height, Terraria.Item.holdStyle, Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item106, Terraria.ID.SoundID.Item128, Terraria.ID.SoundID.Item130, Terraria.ID.SoundID.Item15, Terraria.ID.SoundID.Item151, Terraria.ID.SoundID.Item158, Terraria.ID.SoundID.Item25, Terraria.ID.SoundID.Item3, Terraria.ID.SoundID.Item34, Terraria.ID.SoundID.Item36, Terraria.ID.SoundID.Item4, Terraria.ID.SoundID.Item43, Terraria.ID.SoundID.Item44, Terraria.ID.SoundID.Item5, Terraria.ID.SoundID.Item6, Terraria.ID.SoundID.Item61, Terraria.ID.SoundID.Item66, Terraria.ID.SoundID.Item76, Terraria.ID.SoundID.Item8, Terraria.ID.SoundID.Item82, Terraria.ID.SoundID.Item83, Terraria.ID.SoundID.Item92, Terraria.Item.knockBack, Terraria.Item.legSlot, Terraria.Item.magic, Terraria.Item.makeNPC, Terraria.Item.mana, Terraria.Item.maxStack, Terraria.Item.mech, Terraria.Item.melee, Terraria.Item.mountType, Terraria.Main.myPlayer, Terraria.Item.neckSlot, Terraria.Item.noMelee, Terraria.Item.noUseGraphic, Terraria.Item.noWet, Terraria.Item.paintCoating, Terraria.Item.pick, Terraria.Item.placeStyle, Terraria.Main.player, Terraria.Item.ranged, Terraria.Item.rare, Terraria.GameContent.Items.ItemVariants.RebalancedVariant, Terraria.Item.reuseDelay, Terraria.ID.AmmoID.Rocket, Terraria.Item.scale, Terraria.Item.sellPrice(), Terraria.Item.sentry, Terraria.Item.SetDefaults(), Terraria.Item.SetShopValues(), Terraria.Item.SetWeaponValues(), Terraria.Item.shieldSlot, Terraria.Item.shoeSlot, Terraria.Item.shoot, Terraria.Item.shootsEveryUse, Terraria.Item.shootSpeed, Terraria.Player.skinColor, Terraria.ID.AmmoID.Solution, Terraria.GameContent.Items.ItemVariants.StrongerVariant, Terraria.Item.summon, Terraria.Item.tileBoost, Terraria.Item.tileWand, Terraria.Item.type, Terraria.Item.useAmmo, Terraria.Item.useAnimation, Terraria.Item.UseSound, Terraria.Item.useStyle, Terraria.Item.useTime, Terraria.Item.useTurn, Terraria.Item.value, Terraria.Item.vanity, Terraria.Item.Variant, Terraria.Item.waistSlot, Terraria.GameContent.Items.ItemVariants.WeakerVariant, Terraria.Entity.width, and Terraria.Item.wingSlot.
Referenced by Terraria.Item.SetDefaults().