Terraria: Terraria.Item.IsTheSameAs
IsTheSameAs()
bool Terraria.Item.IsTheSameAs (Item compareItem) inline
Definition at line 49926 of file Item.cs.
    {
        if (netID == compareItem.netID)
        {
            return type == compareItem.type;
        }
        return false;
    }
References Terraria.Item.netID, and Terraria.Item.type.
Referenced by Terraria.UI.ItemSlot.AccCheck(), Terraria.UI.ItemSlot.ArmorSwap(), Terraria.Player.CanItemSlotAccept(), Terraria.Recipe.CollectGuideRecipes(), Terraria.Recipe.Create(), Terraria.UI.ChestUI.DepositAll(), Terraria.Player.FillAmmo(), Terraria.Player.GetItem_FillIntoOccupiedSlot(), Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.Player.ItemSpace(), Terraria.UI.ItemSlot.LeftClick(), Terraria.Chest.PutItemInNearbyChest(), and Terraria.UI.ItemSlot.RightClick().