Terraria: Terraria.Item.sellPrice
sellPrice()
static int Terraria.Item.sellPrice (int platinum = 0, int gold = 0, int silver = 0, int copper = 0) inline static
Definition at line 47984 of file Item.cs.
    {
        return (copper + silver * 100 + gold * 100 * 100 + platinum * 100 * 100 * 100) * 5;
    }
References Terraria.Item.copper, Terraria.Item.gold, Terraria.Item.platinum, and Terraria.Item.silver.
Referenced by Terraria.Item.DefaultToSeaShell(), Terraria.Item.DefaultToVanitypet(), Terraria.Item.SetDefaults(), Terraria.Item.SetDefaults1(), Terraria.Item.SetDefaults2(), Terraria.Item.SetDefaults3(), Terraria.Item.SetDefaults4(), and Terraria.Item.SetDefaults5().