Terraria: Terraria.Item.GetFlexibleTileWand
GetFlexibleTileWand()
FlexibleTileWand Terraria.Item.GetFlexibleTileWand () inline
Definition at line 48626 of file Item.cs.
    {
        return type switch
        {
            5324 => FlexibleTileWand.RubblePlacementSmall,
            5329 => FlexibleTileWand.RubblePlacementMedium,
            5330 => FlexibleTileWand.RubblePlacementLarge,
            _ => null,
        };
    }
References Terraria.GameContent.FlexibleTileWand.RubblePlacementLarge, Terraria.GameContent.FlexibleTileWand.RubblePlacementMedium, Terraria.GameContent.FlexibleTileWand.RubblePlacementSmall, and Terraria.Item.type.
Referenced by Terraria.Player.ModifyFlexibleWandPlacementInfo(), Terraria.Player.PlaceThing_Tiles_CheckFlexibleWand(), and Terraria.Player.PlaceThing_Tiles_PlaceIt_ConsumeFlexibleWandMaterial().