Terraria: Terraria.Item.CanShimmer
CanShimmer()
bool Terraria.Item.CanShimmer () inline
Definition at line 47989 of file Item.cs.
    {
        int shimmerEquivalentType = GetShimmerEquivalentType();
        if (ShimmerTransforms.IsItemTransformLocked(shimmerEquivalentType))
        {
            return false;
        }
        bool flag = false;
        if ((type == 1326 || type == 779 || type == 3031 || type == 5364) && NPC.downedMoonlord)
        {
            flag = true;
        }
        if (type == 4986 && !NPC.unlockedSlimeRainbowSpawn)
        {
            flag = true;
        }
        if (type == 3461 || createTile == 139)
        {
            flag = true;
        }
        if (!flag && ItemID.Sets.ShimmerTransformToItem[shimmerEquivalentType] <= 0 && FindDecraftAmount() <= 0 && !ItemID.Sets.CommonCoin[type])
        {
            return makeNPC > 0;
        }
        return true;
    }
References Terraria.ID.ItemID.Sets.CommonCoin, Terraria.Item.createTile, Terraria.NPC.downedMoonlord, Terraria.Item.FindDecraftAmount(), Terraria.Item.GetShimmerEquivalentType(), Terraria.GameContent.ShimmerTransforms.IsItemTransformLocked(), Terraria.Item.makeNPC, Terraria.ID.ItemID.Sets.ShimmerTransformToItem, Terraria.Item.type, and Terraria.NPC.unlockedSlimeRainbowSpawn.
Referenced by Terraria.Item.Shimmering().