Terraria: Terraria.Item.TryCombiningIntoNearbyItems
TryCombiningIntoNearbyItems()
void Terraria.Item.TryCombiningIntoNearbyItems (int i) inline
Definition at line 48608 of file Item.cs.
    {
        bool flag = true;
        int num = type;
        if ((uint)(num - 71) <= 3u)
        {
            flag = false;
        }
        if (ItemID.Sets.NebulaPickup[type])
        {
            flag = false;
        }
        if (playerIndexTheItemIsReservedFor == Main.myPlayer && flag)
        {
            CombineWithNearbyItems(i);
        }
    }
References Terraria.Item.CombineWithNearbyItems(), Terraria.Main.myPlayer, Terraria.ID.ItemID.Sets.NebulaPickup, Terraria.Item.playerIndexTheItemIsReservedFor, and Terraria.Item.type.
Referenced by Terraria.WorldGen.KillTile_DropItems(), and Terraria.Item.UpdateItem().