Terraria: Terraria.Item.GetShimmerEquivalentType
GetShimmerEquivalentType()
int Terraria.Item.GetShimmerEquivalentType () inline private
Definition at line 48064 of file Item.cs.
    {
        if (ItemID.Sets.ShimmerCountsAsItem[type] != -1)
        {
            return ItemID.Sets.ShimmerCountsAsItem[type];
        }
        return type;
    }
References Terraria.ID.ItemID.Sets.ShimmerCountsAsItem, and Terraria.Item.type.
Referenced by Terraria.Item.CanShimmer(), Terraria.Item.FindDecraftAmount(), and Terraria.Item.GetShimmered().