Terraria: Terraria.Item.Shimmering
Shimmering()
void Terraria.Item.Shimmering () inline private
Definition at line 48016 of file Item.cs.
    {
        if (CanShimmer())
        {
            int num = (int)(base.Center.X / 16f);
            int num2 = (int)(position.Y / 16f - 1f);
            if (!WorldGen.InWorld(num, num2) || Main.tile[num, num2] == null || Main.tile[num, num2].liquid <= 0 || !Main.tile[num, num2].shimmer())
            {
                return;
            }
            if (playerIndexTheItemIsReservedFor == Main.myPlayer && Main.netMode != 1)
            {
                shimmerTime += 0.01f;
                if (shimmerTime > 0.9f)
                {
                    shimmerTime = 0.9f;
                    GetShimmered();
                }
            }
            else
            {
                shimmerTime += 0.01f;
                if (shimmerTime > 1f)
                {
                    shimmerTime = 1f;
                }
            }
        }
        else if (shimmerTime > 0f)
        {
            shimmerTime -= 0.01f;
            if (shimmerTime < 0f)
            {
                shimmerTime = 0f;
            }
        }
    }
References Terraria.Item.CanShimmer(), Terraria.Item.GetShimmered(), Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.Tile.shimmer(), Terraria.Item.shimmerTime, and Terraria.Main.tile.
Referenced by Terraria.Item.UpdateItem().