Terraria: Terraria.Item.FindOwner
FindOwner()
void Terraria.Item.FindOwner (int whoAmI) inline
Definition at line 49847 of file Item.cs.
    {
        if (Main.netMode == 1 && shimmerTime > 0f)
        {
            keepTime = 0;
        }
        if (keepTime > 0)
        {
            return;
        }
        int num = playerIndexTheItemIsReservedFor;
        playerIndexTheItemIsReservedFor = 255;
        bool flag = true;
        if (type == 267 && ownIgnore != -1)
        {
            flag = false;
        }
        if (shimmerTime > 0f)
        {
            playerIndexTheItemIsReservedFor = 255;
        }
        else if (flag)
        {
            float num2 = NPC.sWidth;
            for (int i = 0; i < 255; i++)
            {
                if (ownIgnore == i)
                {
                    continue;
                }
                Player player = Main.player[i];
                if (!player.active)
                {
                    continue;
                }
                Player.ItemSpaceStatus status = player.ItemSpace(Main.item[whoAmI]);
                if (player.CanPullItem(Main.item[whoAmI], status))
                {
                    float num3 = Math.Abs(player.position.X + (float)(player.width / 2) - position.X - (float)(width / 2)) + Math.Abs(player.position.Y + (float)(player.height / 2) - position.Y - (float)height);
                    if (player.manaMagnet && (type == 184 || type == 1735 || type == 1868))
                    {
                        num3 -= (float)manaGrabRange;
                    }
                    if (player.lifeMagnet && (type == 58 || type == 1734 || type == 1867))
                    {
                        num3 -= (float)lifeGrabRange;
                    }
                    if (type == 4143)
                    {
                        num3 -= (float)manaGrabRange;
                    }
                    if (num2 > num3)
                    {
                        num2 = num3;
                        playerIndexTheItemIsReservedFor = i;
                    }
                }
            }
        }
        if (playerIndexTheItemIsReservedFor != num && ((num == Main.myPlayer && Main.netMode == 1) || (num == 255 && Main.netMode == 2) || (num != 255 && !Main.player[num].active)))
        {
            NetMessage.SendData(21, -1, -1, null, whoAmI);
            if (active)
            {
                NetMessage.SendData(22, -1, -1, null, whoAmI);
            }
        }
    }
References System.Math.Abs(), Terraria.Entity.active, Terraria.Player.CanPullItem(), Terraria.Entity.height, Terraria.Main.item, Terraria.Player.ItemSpace(), Terraria.Item.keepTime, Terraria.Item.lifeGrabRange, Terraria.Player.lifeMagnet, Terraria.Item.manaGrabRange, Terraria.Player.manaMagnet, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.ownIgnore, Terraria.Main.player, Terraria.Item.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Item.shimmerTime, Terraria.NPC.sWidth, Terraria.Item.type, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.