Terraria: UILinkPoint.Unlink
Unlink()
void UILinkPoint.Unlink () inline
     {
         Left = -3;
         Right = -4;
         Up = -1;
         Down = -2;
     }
References Down, Left, Right, and Up.
Referenced by UICharacterCreation.GetAndSet(), UIBestiaryTest.MakeLinkPointFromSnapPoint(), UIGamepadHelper.MakeLinkPointFromSnapPoint(), UIAchievementsMenu.SetupGamepadPoints(), UICharacterCreation.SetupGamepadPoints(), UICharacterSelect.SetupGamepadPoints(), UIEmotesMenu.SetupGamepadPoints(), UIManageControls.SetupGamepadPoints(), UIVirtualKeyboard.SetupGamepadPoints(), UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), UIWorkshopWorldImport.SetupGamepadPoints(), UIWorldCreation.SetupGamepadPoints(), UIWorldSelect.SetupGamepadPoints(), and UIEmotesMenu.SetupGamepadPoints2().