Terraria: Terraria.Item.GetPickedUpByMonsters_Special
GetPickedUpByMonsters_Special()
void Terraria.Item.GetPickedUpByMonsters_Special (int i) inline private
    {
        bool flag = false;
        bool flag2 = false;
        int num = type;
        if ((num == 89 || num == 3507) && !NPC.unlockedSlimeCopperSpawn)
        {
            flag = true;
            flag2 = true;
        }
        if (!flag2)
        {
            return;
        }
        bool flag3 = false;
        Rectangle hitbox = base.Hitbox;
        for (int j = 0; j < 200; j++)
        {
            NPC nPC = Main.npc[j];
            if (nPC.active && flag && nPC.type >= 0 && nPC.type < NPCID.Count && NPCID.Sets.CanConvertIntoCopperSlimeTownNPC[nPC.type] && hitbox.Intersects(nPC.Hitbox))
            {
                flag3 = true;
                NPC.TransformCopperSlime(j);
                break;
            }
        }
        if (flag3)
        {
            SetDefaults();
            active = false;
            NetMessage.SendData(21, -1, -1, null, i);
        }
    }
References Terraria.Entity.active, Terraria.ID.NPCID.Sets.CanConvertIntoCopperSlimeTownNPC, Terraria.ID.NPCID.Count, Terraria.Entity.Hitbox, Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.NPC.TransformCopperSlime(), Terraria.Item.type, Terraria.NPC.type, and Terraria.NPC.unlockedSlimeCopperSpawn.
Referenced by Terraria.Item.UpdateItem().