Terraria: UICharacterCreation.MakeCategoriesBar
MakeCategoriesBar()
void UICharacterCreation.MakeCategoriesBar (UIElement categoryContainer) inline private
     {
         float xPositionStart = -240f;
         float xPositionPerId = 48f;
         _colorPickers = new UIColoredImageButton[10];
         categoryContainer.Append(CreateColorPicker(CategoryId.HairColor, "Images/UI/CharCreation/ColorHair", xPositionStart, xPositionPerId));
         categoryContainer.Append(CreateColorPicker(CategoryId.Eye, "Images/UI/CharCreation/ColorEye", xPositionStart, xPositionPerId));
         categoryContainer.Append(CreateColorPicker(CategoryId.Skin, "Images/UI/CharCreation/ColorSkin", xPositionStart, xPositionPerId));
         categoryContainer.Append(CreateColorPicker(CategoryId.Shirt, "Images/UI/CharCreation/ColorShirt", xPositionStart, xPositionPerId));
         categoryContainer.Append(CreateColorPicker(CategoryId.Undershirt, "Images/UI/CharCreation/ColorUndershirt", xPositionStart, xPositionPerId));
         categoryContainer.Append(CreateColorPicker(CategoryId.Pants, "Images/UI/CharCreation/ColorPants", xPositionStart, xPositionPerId));
         categoryContainer.Append(CreateColorPicker(CategoryId.Shoes, "Images/UI/CharCreation/ColorShoes", xPositionStart, xPositionPerId));
         _colorPickers[4].SetMiddleTexture(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/ColorEyeBack", (AssetRequestMode)1));
         _clothingStylesCategoryButton = CreatePickerWithoutClick(CategoryId.Clothing, "Images/UI/CharCreation/ClothStyleMale", xPositionStart, xPositionPerId);
         _clothingStylesCategoryButton.OnLeftMouseDown += Click_ClothStyles;
         _clothingStylesCategoryButton.SetSnapPoint("Top", 1);
         categoryContainer.Append(_clothingStylesCategoryButton);
         _hairStylesCategoryButton = CreatePickerWithoutClick(CategoryId.HairStyle, "Images/UI/CharCreation/HairStyle_Hair", xPositionStart, xPositionPerId);
         _hairStylesCategoryButton.OnLeftMouseDown += Click_HairStyles;
         _hairStylesCategoryButton.SetMiddleTexture(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/HairStyle_Arrow", (AssetRequestMode)1));
         _hairStylesCategoryButton.SetSnapPoint("Top", 2);
         categoryContainer.Append(_hairStylesCategoryButton);
         _charInfoCategoryButton = CreatePickerWithoutClick(CategoryId.CharInfo, "Images/UI/CharCreation/CharInfo", xPositionStart, xPositionPerId);
         _charInfoCategoryButton.OnLeftMouseDown += Click_CharInfo;
         _charInfoCategoryButton.SetSnapPoint("Top", 0);
         categoryContainer.Append(_charInfoCategoryButton);
         UpdateColorPickers();
         UIHorizontalSeparator element = new UIHorizontalSeparator
         {
             Width = StyleDimension.FromPixelsAndPercent(-20f, 1f),
             Top = StyleDimension.FromPixels(6f),
             VAlign = 1f,
             HAlign = 0.5f,
             Color = Color.Lerp(Color.White, new Color(63, 65, 151, 255), 0.85f) * 0.9f
         };
         categoryContainer.Append(element);
         int num = 21;
         UIText uIText = new UIText(PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "HotbarMinus"))
         {
             Left = new StyleDimension(-num, 0f),
             VAlign = 0.5f,
             Top = new StyleDimension(-4f, 0f)
         };
         categoryContainer.Append(uIText);
         UIText uIText2 = new UIText(PlayerInput.GenerateInputTag_ForCurrentGamemode(tagForGameplay: false, "HotbarMinus"))
         {
             HAlign = 1f,
             Left = new StyleDimension(12 + num, 0f),
             VAlign = 0.5f,
             Top = new StyleDimension(-4f, 0f)
         };
         categoryContainer.Append(uIText2);
         _helpGlyphLeft = uIText;
         _helpGlyphRight = uIText2;
         categoryContainer.OnUpdate += UpdateHelpGlyphs;
     }
References _charInfoCategoryButton, _clothingStylesCategoryButton, _colorPickers, _hairStylesCategoryButton, _helpGlyphLeft, _helpGlyphRight, UIElement.Append(), Main.Assets, Click_CharInfo(), Click_ClothStyles(), Click_HairStyles(), Color, CreateColorPicker(), CreatePickerWithoutClick(), StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), PlayerInput.GenerateInputTag_ForCurrentGamemode(), UIElement.HAlign, UIElement.Left, UIElement.OnLeftMouseDown, UIElement.OnUpdate, UIColoredImageButton.SetMiddleTexture(), UIElement.SetSnapPoint(), UIElement.Top, UpdateColorPickers(), UpdateHelpGlyphs(), UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().