Terraria: UICharacterCreation.UpdateHSLValue
UpdateHSLValue()
void UICharacterCreation.UpdateHSLValue (HSLSliderId id, float value) inline private
     {
         switch (id)
         {
         case HSLSliderId.Hue:
             _currentColorHSL.X = value;
             break;
         case HSLSliderId.Saturation:
             _currentColorHSL.Y = value;
             break;
         case HSLSliderId.Luminance:
             _currentColorHSL.Z = value;
             break;
         }
         Color color = ScaledHslToRgb(_currentColorHSL.X, _currentColorHSL.Y, _currentColorHSL.Z);
         ApplyPendingColor(color);
         _colorPickers[(int)_selectedPicker]?.SetColor(color);
         if (_selectedPicker == CategoryId.HairColor)
         {
             _hairStylesCategoryButton.SetColor(color);
         }
         UpdateHexText(color);
     }
References _colorPickers, _currentColorHSL, _hairStylesCategoryButton, _selectedPicker, ApplyPendingColor(), Color, ScaledHslToRgb(), UIColoredImageButton.SetColor(), and UpdateHexText().
Referenced by CreateHSLSliderButtonBase(), UpdateHSL_H(), UpdateHSL_L(), and UpdateHSL_S().