Terraria: UICharacterCreation.Click_Naming
Click_Naming()
void UICharacterCreation.Click_Naming (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(10);
         _player.name = "";
         Main.clrInput();
         UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Lang.menu[45].Value, "", OnFinishedNaming, OnCanceledNaming, 0, allowEmpty: true);
         uIVirtualKeyboard.SetMaxInputLength(20);
         Main.MenuUI.SetState(uIVirtualKeyboard);
     }
References _player, Main.clrInput(), Lang.menu, Main.MenuUI, Player.name, OnCanceledNaming(), OnFinishedNaming(), SoundEngine.PlaySound(), UIVirtualKeyboard.SetMaxInputLength(), UserInterface.SetState(), and LocalizedText.Value.
Referenced by MakeInfoMenu().