Terraria: UICharacterCreation.Draw
Draw()
override void UICharacterCreation.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from UIElement.
     {
         base.Draw(spriteBatch);
         string text = null;
         if (_copyHexButton.IsMouseHovering)
         {
             text = Language.GetTextValue("UI.CopyColorToClipboard");
         }
         if (_pasteHexButton.IsMouseHovering)
         {
             text = Language.GetTextValue("UI.PasteColorFromClipboard");
         }
         if (_randomColorButton.IsMouseHovering)
         {
             text = Language.GetTextValue("UI.RandomizeColor");
         }
         if (_copyTemplateButton.IsMouseHovering)
         {
             text = Language.GetTextValue("UI.CopyPlayerToClipboard");
         }
         if (_pasteTemplateButton.IsMouseHovering)
         {
             text = Language.GetTextValue("UI.PastePlayerFromClipboard");
         }
         if (_randomizePlayerButton.IsMouseHovering)
         {
             text = Language.GetTextValue("UI.RandomizePlayer");
         }
         if (text != null)
         {
             float x = FontAssets.MouseText.Value.MeasureString(text).X;
             Vector2 vector = new Vector2(Main.mouseX, Main.mouseY) + new Vector2(16f);
             if (vector.Y > (float)(Main.screenHeight - 30))
             {
                 vector.Y = Main.screenHeight - 30;
             }
             if (vector.X > (float)Main.screenWidth - x)
             {
                 vector.X = Main.screenWidth - 460;
             }
             Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, text, vector.X, vector.Y, new Color(Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor), Color.Black, Vector2.Zero);
         }
         SetupGamepadPoints(spriteBatch);
     }
References _copyHexButton, _copyTemplateButton, _pasteHexButton, _pasteTemplateButton, _randomColorButton, _randomizePlayerButton, Color, Utils.DrawBorderStringFourWay(), Language.GetTextValue(), UIElement.IsMouseHovering, FontAssets.MouseText, Main.mouseTextColor, Main.mouseX, Main.mouseY, Main.screenHeight, Main.screenWidth, SetupGamepadPoints(), and Asset< T >.Value.