Terraria: UICharacterCreation.Click_PastePlayerTemplate
Click_PastePlayerTemplate()
void UICharacterCreation.Click_PastePlayerTemplate (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(12);
         try
         {
             string value = Platform.Get<IClipboard>().Value;
             int num = value.IndexOf("{");
             if (num == -1)
             {
                 return;
             }
             value = value.Substring(num);
             int num2 = value.LastIndexOf("}");
             if (num2 == -1)
             {
                 return;
             }
             value = value.Substring(0, num2 + 1);
             Dictionary<string, object> dictionary = JsonConvert.DeserializeObject<Dictionary<string, object>>(value);
             if (dictionary == null)
             {
                 return;
             }
             Dictionary<string, object> dictionary2 = new Dictionary<string, object>();
             foreach (KeyValuePair<string, object> item in dictionary)
             {
                 dictionary2[item.Key.ToLower()] = item.Value;
             }
             if (dictionary2.TryGetValue("version", out var value2))
             {
                 _ = (long)value2;
             }
             if (dictionary2.TryGetValue("hairstyle", out value2))
             {
                 int num3 = (int)(long)value2;
                 if (Main.Hairstyles.AvailableHairstyles.Contains(num3))
                 {
                     _player.hair = num3;
                 }
             }
             if (dictionary2.TryGetValue("clothingstyle", out value2))
             {
                 int num4 = (int)(long)value2;
                 if (_validClothStyles.Contains(num4))
                 {
                     _player.skinVariant = num4;
                 }
             }
             if (dictionary2.TryGetValue("haircolor", out value2) && GetHexColor((string)value2, out var hsl))
             {
                 _player.hairColor = ScaledHslToRgb(hsl);
             }
             if (dictionary2.TryGetValue("eyecolor", out value2) && GetHexColor((string)value2, out hsl))
             {
                 _player.eyeColor = ScaledHslToRgb(hsl);
             }
             if (dictionary2.TryGetValue("skincolor", out value2) && GetHexColor((string)value2, out hsl))
             {
                 _player.skinColor = ScaledHslToRgb(hsl);
             }
             if (dictionary2.TryGetValue("shirtcolor", out value2) && GetHexColor((string)value2, out hsl))
             {
                 _player.shirtColor = ScaledHslToRgb(hsl);
             }
             if (dictionary2.TryGetValue("undershirtcolor", out value2) && GetHexColor((string)value2, out hsl))
             {
                 _player.underShirtColor = ScaledHslToRgb(hsl);
             }
             if (dictionary2.TryGetValue("pantscolor", out value2) && GetHexColor((string)value2, out hsl))
             {
                 _player.pantsColor = ScaledHslToRgb(hsl);
             }
             if (dictionary2.TryGetValue("shoecolor", out value2) && GetHexColor((string)value2, out hsl))
             {
                 _player.shoeColor = ScaledHslToRgb(hsl);
             }
             Click_CharClothStyle(null, null);
             UpdateColorPickers();
         }
         catch
         {
         }
     }
References _player, _validClothStyles, HairstyleUnlocksHelper.AvailableHairstyles, Click_CharClothStyle(), Player.eyeColor, GetHexColor(), Player.hair, Player.hairColor, Main.Hairstyles, Player.pantsColor, SoundEngine.PlaySound(), ScaledHslToRgb(), Player.shirtColor, Player.shoeColor, Player.skinColor, Player.skinVariant, Player.underShirtColor, and UpdateColorPickers().
Referenced by MakeClothStylesMenu().