Terraria: UICharacterCreation.CreateHSLSliderButtonBase
CreateHSLSliderButtonBase()
UIColoredSlider UICharacterCreation.CreateHSLSliderButtonBase (HSLSliderId id) inline private
     {
         return id switch
         {
             HSLSliderId.Saturation => new UIColoredSlider(LocalizedText.Empty, () => GetHSLSliderPosition(HSLSliderId.Saturation), delegate(float x)
             {
                 UpdateHSLValue(HSLSliderId.Saturation, x);
             }, UpdateHSL_S, (float x) => GetHSLSliderColorAt(HSLSliderId.Saturation, x), Color.Transparent),
             HSLSliderId.Luminance => new UIColoredSlider(LocalizedText.Empty, () => GetHSLSliderPosition(HSLSliderId.Luminance), delegate(float x)
             {
                 UpdateHSLValue(HSLSliderId.Luminance, x);
             }, UpdateHSL_L, (float x) => GetHSLSliderColorAt(HSLSliderId.Luminance, x), Color.Transparent),
             _ => new UIColoredSlider(LocalizedText.Empty, () => GetHSLSliderPosition(HSLSliderId.Hue), delegate(float x)
             {
                 UpdateHSLValue(HSLSliderId.Hue, x);
             }, UpdateHSL_H, (float x) => GetHSLSliderColorAt(HSLSliderId.Hue, x), Color.Transparent),
         };
     }
References Color, LocalizedText.Empty, GetHSLSliderColorAt(), GetHSLSliderPosition(), UpdateHSL_H(), UpdateHSL_L(), UpdateHSL_S(), and UpdateHSLValue().
Referenced by CreateHSLSlider().