Terraria: UICharacterCreation.Click_CopyPlayerTemplate
Click_CopyPlayerTemplate()
void UICharacterCreation.Click_CopyPlayerTemplate (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         //IL_011e: Unknown result type (might be due to invalid IL or missing references)
         //IL_0123: Unknown result type (might be due to invalid IL or missing references)
         //IL_012a: Unknown result type (might be due to invalid IL or missing references)
         //IL_0131: Unknown result type (might be due to invalid IL or missing references)
         //IL_013d: Expected O, but got Unknown
         SoundEngine.PlaySound(12);
         string text = JsonConvert.SerializeObject((object)new Dictionary<string, object>
         {
             { "version", 1 },
             { "hairStyle", _player.hair },
             { "clothingStyle", _player.skinVariant },
             {
                 "hairColor",
                 GetHexText(_player.hairColor)
             },
             {
                 "eyeColor",
                 GetHexText(_player.eyeColor)
             },
             {
                 "skinColor",
                 GetHexText(_player.skinColor)
             },
             {
                 "shirtColor",
                 GetHexText(_player.shirtColor)
             },
             {
                 "underShirtColor",
                 GetHexText(_player.underShirtColor)
             },
             {
                 "pantsColor",
                 GetHexText(_player.pantsColor)
             },
             {
                 "shoeColor",
                 GetHexText(_player.shoeColor)
             }
         }, new JsonSerializerSettings
         {
             TypeNameHandling = (TypeNameHandling)4,
             MetadataPropertyHandling = (MetadataPropertyHandling)1,
             Formatting = (Formatting)1
         });
         PlayerInput.PrettyPrintProfiles(ref text);
         Platform.Get<IClipboard>().Value = text;
     }
References _player, Player.eyeColor, GetHexText(), Player.hair, Player.hairColor, Player.pantsColor, SoundEngine.PlaySound(), PlayerInput.PrettyPrintProfiles(), Player.shirtColor, Player.shoeColor, Player.skinColor, Player.skinVariant, and Player.underShirtColor.
Referenced by MakeClothStylesMenu().