Terraria: UICharacterCreation.MakeClothStylesMenu
MakeClothStylesMenu()
void UICharacterCreation.MakeClothStylesMenu (UIElement middleInnerPanel) inline private
     {
         UIElement uIElement = new UIElement
         {
             Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
             HAlign = 0.5f,
             VAlign = 0.5f
         };
         middleInnerPanel.Append(uIElement);
         uIElement.SetPadding(0f);
         int num = 15;
         for (int i = 0; i < _validClothStyles.Length; i++)
         {
             int num2 = 0;
             if (i >= _validClothStyles.Length / 2)
             {
                 num2 = 20;
             }
             UIClothStyleButton uIClothStyleButton = new UIClothStyleButton(_player, _validClothStyles[i])
             {
                 Left = StyleDimension.FromPixels((float)i * 46f + (float)num2 + 6f),
                 Top = StyleDimension.FromPixels(num)
             };
             uIClothStyleButton.OnLeftMouseDown += Click_CharClothStyle;
             uIClothStyleButton.SetSnapPoint("Middle", i);
             uIElement.Append(uIClothStyleButton);
         }
         for (int j = 0; j < 2; j++)
         {
             int num3 = 0;
             if (j >= 1)
             {
                 num3 = 20;
             }
             UIHorizontalSeparator element = new UIHorizontalSeparator
             {
                 Left = StyleDimension.FromPixels((float)j * 230f + (float)num3 + 6f),
                 Top = StyleDimension.FromPixels(num + 86),
                 Width = StyleDimension.FromPixelsAndPercent(230f, 0f),
                 Color = Color.Lerp(Color.White, new Color(63, 65, 151, 255), 0.85f) * 0.9f
             };
             uIElement.Append(element);
             UIColoredImageButton uIColoredImageButton = CreatePickerWithoutClick(CategoryId.Clothing, "Images/UI/CharCreation/" + ((j == 0) ? "ClothStyleMale" : "ClothStyleFemale"), 0f, 0f);
             uIColoredImageButton.Top = StyleDimension.FromPixelsAndPercent(num + 92, 0f);
             uIColoredImageButton.Left = StyleDimension.FromPixels((float)j * 230f + 92f + (float)num3 + 6f);
             uIColoredImageButton.HAlign = 0f;
             uIColoredImageButton.VAlign = 0f;
             uIElement.Append(uIColoredImageButton);
             if (j == 0)
             {
                 uIColoredImageButton.OnLeftMouseDown += Click_CharGenderMale;
                 _genderMale = uIColoredImageButton;
             }
             else
             {
                 uIColoredImageButton.OnLeftMouseDown += Click_CharGenderFemale;
                 _genderFemale = uIColoredImageButton;
             }
             uIColoredImageButton.SetSnapPoint("Low", j * 4);
         }
         UIElement uIElement2 = new UIElement
         {
             Width = StyleDimension.FromPixels(130f),
             Height = StyleDimension.FromPixels(50f),
             HAlign = 0.5f,
             VAlign = 1f
         };
         uIElement.Append(uIElement2);
         UIColoredImageButton uIColoredImageButton2 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Copy", (AssetRequestMode)1), isSmall: true)
         {
             VAlign = 0.5f,
             HAlign = 0f,
             Left = StyleDimension.FromPixelsAndPercent(0f, 0f)
         };
         uIColoredImageButton2.OnLeftMouseDown += Click_CopyPlayerTemplate;
         uIElement2.Append(uIColoredImageButton2);
         _copyTemplateButton = uIColoredImageButton2;
         UIColoredImageButton uIColoredImageButton3 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Paste", (AssetRequestMode)1), isSmall: true)
         {
             VAlign = 0.5f,
             HAlign = 0.5f
         };
         uIColoredImageButton3.OnLeftMouseDown += Click_PastePlayerTemplate;
         uIElement2.Append(uIColoredImageButton3);
         _pasteTemplateButton = uIColoredImageButton3;
         UIColoredImageButton uIColoredImageButton4 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Randomize", (AssetRequestMode)1), isSmall: true)
         {
             VAlign = 0.5f,
             HAlign = 1f
         };
         uIColoredImageButton4.OnLeftMouseDown += Click_RandomizePlayer;
         uIElement2.Append(uIColoredImageButton4);
         _randomizePlayerButton = uIColoredImageButton4;
         uIColoredImageButton2.SetSnapPoint("Low", 1);
         uIColoredImageButton3.SetSnapPoint("Low", 2);
         uIColoredImageButton4.SetSnapPoint("Low", 3);
         _clothStylesContainer = uIElement;
     }
References _clothStylesContainer, _copyTemplateButton, _genderFemale, _genderMale, _pasteTemplateButton, _player, _randomizePlayerButton, _validClothStyles, UIElement.Append(), Main.Assets, Click_CharClothStyle(), Click_CharGenderFemale(), Click_CharGenderMale(), Click_CopyPlayerTemplate(), Click_PastePlayerTemplate(), Click_RandomizePlayer(), Color, CreatePickerWithoutClick(), StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Height, UIElement.Left, UIElement.OnLeftMouseDown, UIElement.SetPadding(), UIElement.SetSnapPoint(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().