Terraria: UICharacterCreation.OnFinishedNamingAndCreating
OnFinishedNamingAndCreating()
void UICharacterCreation.OnFinishedNamingAndCreating (string name) inline private
     {
         _player.name = name.Trim();
         Main.MenuUI.SetState(this);
         _charName.SetContents(_player.name);
         FinishCreatingCharacter();
     }
References _charName, _player, FinishCreatingCharacter(), Main.MenuUI, Player.name, UICharacterNameButton.SetContents(), and UserInterface.SetState().
Referenced by Click_NamingAndCreating().