Terraria: UICharacterCreation.MakeHSLMenu
MakeHSLMenu()
void UICharacterCreation.MakeHSLMenu (UIElement parentContainer) inline private
     {
         UIElement uIElement = new UIElement
         {
             Width = StyleDimension.FromPixelsAndPercent(220f, 0f),
             Height = StyleDimension.FromPixelsAndPercent(158f, 0f),
             HAlign = 0.5f,
             VAlign = 0f
         };
         uIElement.SetPadding(0f);
         parentContainer.Append(uIElement);
         UIElement uIElement2 = new UIPanel
         {
             Width = StyleDimension.FromPixelsAndPercent(220f, 0f),
             Height = StyleDimension.FromPixelsAndPercent(104f, 0f),
             HAlign = 0.5f,
             VAlign = 0f,
             Top = StyleDimension.FromPixelsAndPercent(10f, 0f)
         };
         uIElement2.SetPadding(0f);
         uIElement2.PaddingTop = 3f;
         uIElement.Append(uIElement2);
         uIElement2.Append(CreateHSLSlider(HSLSliderId.Hue));
         uIElement2.Append(CreateHSLSlider(HSLSliderId.Saturation));
         uIElement2.Append(CreateHSLSlider(HSLSliderId.Luminance));
         UIPanel uIPanel = new UIPanel
         {
             VAlign = 1f,
             HAlign = 1f,
             Width = StyleDimension.FromPixelsAndPercent(100f, 0f),
             Height = StyleDimension.FromPixelsAndPercent(32f, 0f)
         };
         UIText uIText = new UIText("FFFFFF")
         {
             VAlign = 0.5f,
             HAlign = 0.5f
         };
         uIPanel.Append(uIText);
         uIElement.Append(uIPanel);
         UIColoredImageButton uIColoredImageButton = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Copy", (AssetRequestMode)1), isSmall: true)
         {
             VAlign = 1f,
             HAlign = 0f,
             Left = StyleDimension.FromPixelsAndPercent(0f, 0f)
         };
         uIColoredImageButton.OnLeftMouseDown += Click_CopyHex;
         uIElement.Append(uIColoredImageButton);
         _copyHexButton = uIColoredImageButton;
         UIColoredImageButton uIColoredImageButton2 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Paste", (AssetRequestMode)1), isSmall: true)
         {
             VAlign = 1f,
             HAlign = 0f,
             Left = StyleDimension.FromPixelsAndPercent(40f, 0f)
         };
         uIColoredImageButton2.OnLeftMouseDown += Click_PasteHex;
         uIElement.Append(uIColoredImageButton2);
         _pasteHexButton = uIColoredImageButton2;
         UIColoredImageButton uIColoredImageButton3 = new UIColoredImageButton(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/Randomize", (AssetRequestMode)1), isSmall: true)
         {
             VAlign = 1f,
             HAlign = 0f,
             Left = StyleDimension.FromPixelsAndPercent(80f, 0f)
         };
         uIColoredImageButton3.OnLeftMouseDown += Click_RandomizeSingleColor;
         uIElement.Append(uIColoredImageButton3);
         _randomColorButton = uIColoredImageButton3;
         _hslContainer = uIElement;
         _hslHexText = uIText;
         uIColoredImageButton.SetSnapPoint("Low", 0);
         uIColoredImageButton2.SetSnapPoint("Low", 1);
         uIColoredImageButton3.SetSnapPoint("Low", 2);
     }
References _copyHexButton, _hslContainer, _hslHexText, _pasteHexButton, _randomColorButton, UIElement.Append(), Main.Assets, Click_CopyHex(), Click_PasteHex(), Click_RandomizeSingleColor(), CreateHSLSlider(), StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Height, UIElement.Left, UIElement.OnLeftMouseDown, UIElement.PaddingTop, UIElement.SetPadding(), UIElement.SetSnapPoint(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().