Terraria: UICharacterCreation.SetupGamepadPoints
SetupGamepadPoints()
void UICharacterCreation.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
         int num = 3000;
         int num2 = num + 20;
         int num3 = num;
         List<SnapPoint> snapPoints = GetSnapPoints();
         SnapPoint snapPoint = snapPoints.First((SnapPoint a) => a.Name == "Back");
         SnapPoint snapPoint2 = snapPoints.First((SnapPoint a) => a.Name == "Create");
         UILinkPoint uILinkPoint = UILinkPointNavigator.Points[num3];
         uILinkPoint.Unlink();
         UILinkPointNavigator.SetPosition(num3, snapPoint.Position);
         num3++;
         UILinkPoint uILinkPoint2 = UILinkPointNavigator.Points[num3];
         uILinkPoint2.Unlink();
         UILinkPointNavigator.SetPosition(num3, snapPoint2.Position);
         num3++;
         uILinkPoint.Right = uILinkPoint2.ID;
         uILinkPoint2.Left = uILinkPoint.ID;
         _foundPoints.Clear();
         _foundPoints.Add(uILinkPoint.ID);
         _foundPoints.Add(uILinkPoint2.ID);
         List<SnapPoint> list = snapPoints.Where((SnapPoint a) => a.Name == "Top").ToList();
         list.Sort(SortPoints);
         for (int i = 0; i < list.Count; i++)
         {
             UILinkPoint uILinkPoint3 = UILinkPointNavigator.Points[num3];
             uILinkPoint3.Unlink();
             UILinkPointNavigator.SetPosition(num3, list[i].Position);
             uILinkPoint3.Left = num3 - 1;
             uILinkPoint3.Right = num3 + 1;
             uILinkPoint3.Down = num2;
             if (i == 0)
             {
                 uILinkPoint3.Left = -3;
             }
             if (i == list.Count - 1)
             {
                 uILinkPoint3.Right = -4;
             }
             if (_selectedPicker == CategoryId.HairStyle || _selectedPicker == CategoryId.Clothing)
             {
                 uILinkPoint3.Down = num2 + i;
             }
             _foundPoints.Add(num3);
             num3++;
         }
         List<SnapPoint> list2 = snapPoints.Where((SnapPoint a) => a.Name == "Middle").ToList();
         list2.Sort(SortPoints);
         num3 = num2;
         switch (_selectedPicker)
         {
         case CategoryId.CharInfo:
         {
             for (int l = 0; l < list2.Count; l++)
             {
                 UILinkPoint andSet3 = GetAndSet(num3, list2[l]);
                 andSet3.Up = andSet3.ID - 1;
                 andSet3.Down = andSet3.ID + 1;
                 if (l == 0)
                 {
                     andSet3.Up = num + 2;
                 }
                 if (l == list2.Count - 1)
                 {
                     andSet3.Down = uILinkPoint.ID;
                     uILinkPoint.Up = andSet3.ID;
                     uILinkPoint2.Up = andSet3.ID;
                 }
                 _foundPoints.Add(num3);
                 num3++;
             }
             break;
         }
         case CategoryId.HairStyle:
         {
             if (list2.Count == 0)
             {
                 break;
             }
             _helper.CullPointsOutOfElementArea(spriteBatch, list2, _hairstylesContainer);
             SnapPoint snapPoint3 = list2[list2.Count - 1];
             _ = snapPoint3.Id / 10;
             _ = snapPoint3.Id % 10;
             int count = Main.Hairstyles.AvailableHairstyles.Count;
             for (int m = 0; m < list2.Count; m++)
             {
                 SnapPoint snapPoint4 = list2[m];
                 UILinkPoint andSet4 = GetAndSet(num3, snapPoint4);
                 andSet4.Left = andSet4.ID - 1;
                 if (snapPoint4.Id == 0)
                 {
                     andSet4.Left = -3;
                 }
                 andSet4.Right = andSet4.ID + 1;
                 if (snapPoint4.Id == count - 1)
                 {
                     andSet4.Right = -4;
                 }
                 andSet4.Up = andSet4.ID - 10;
                 if (m < 10)
                 {
                     andSet4.Up = num + 2 + m;
                 }
                 andSet4.Down = andSet4.ID + 10;
                 if (snapPoint4.Id + 10 > snapPoint3.Id)
                 {
                     if (snapPoint4.Id % 10 < 5)
                     {
                         andSet4.Down = uILinkPoint.ID;
                     }
                     else
                     {
                         andSet4.Down = uILinkPoint2.ID;
                     }
                 }
                 if (m == list2.Count - 1)
                 {
                     uILinkPoint.Up = andSet4.ID;
                     uILinkPoint2.Up = andSet4.ID;
                 }
                 _foundPoints.Add(num3);
                 num3++;
             }
             break;
         }
         default:
         {
             List<SnapPoint> list4 = snapPoints.Where((SnapPoint a) => a.Name == "Low").ToList();
             list4.Sort(SortPoints);
             num3 = num2 + 20;
             for (int n = 0; n < list4.Count; n++)
             {
                 UILinkPoint andSet5 = GetAndSet(num3, list4[n]);
                 andSet5.Up = num2 + 2;
                 andSet5.Down = uILinkPoint.ID;
                 andSet5.Left = andSet5.ID - 1;
                 andSet5.Right = andSet5.ID + 1;
                 if (n == 0)
                 {
                     andSet5.Left = andSet5.ID + 2;
                     uILinkPoint.Up = andSet5.ID;
                 }
                 if (n == list4.Count - 1)
                 {
                     andSet5.Right = andSet5.ID - 2;
                     uILinkPoint2.Up = andSet5.ID;
                 }
                 _foundPoints.Add(num3);
                 num3++;
             }
             num3 = num2;
             for (int num4 = 0; num4 < list2.Count; num4++)
             {
                 UILinkPoint andSet6 = GetAndSet(num3, list2[num4]);
                 andSet6.Up = andSet6.ID - 1;
                 andSet6.Down = andSet6.ID + 1;
                 if (num4 == 0)
                 {
                     andSet6.Up = num + 2 + 5;
                 }
                 if (num4 == list2.Count - 1)
                 {
                     andSet6.Down = num2 + 20 + 2;
                 }
                 _foundPoints.Add(num3);
                 num3++;
             }
             break;
         }
         case CategoryId.Clothing:
         {
             List<SnapPoint> list3 = snapPoints.Where((SnapPoint a) => a.Name == "Low").ToList();
             list3.Sort(SortPoints);
             int down = -2;
             int down2 = -2;
             num3 = num2 + 20;
             for (int j = 0; j < list3.Count; j++)
             {
                 UILinkPoint andSet = GetAndSet(num3, list3[j]);
                 andSet.Up = num2 + j + 2;
                 andSet.Down = uILinkPoint.ID;
                 if (j >= 3)
                 {
                     andSet.Up++;
                     andSet.Down = uILinkPoint2.ID;
                 }
                 andSet.Left = andSet.ID - 1;
                 andSet.Right = andSet.ID + 1;
                 if (j == 0)
                 {
                     down = andSet.ID;
                     andSet.Left = andSet.ID + 4;
                     uILinkPoint.Up = andSet.ID;
                 }
                 if (j == list3.Count - 1)
                 {
                     down2 = andSet.ID;
                     andSet.Right = andSet.ID - 4;
                     uILinkPoint2.Up = andSet.ID;
                 }
                 _foundPoints.Add(num3);
                 num3++;
             }
             num3 = num2;
             for (int k = 0; k < list2.Count; k++)
             {
                 UILinkPoint andSet2 = GetAndSet(num3, list2[k]);
                 andSet2.Up = num + 2 + k;
                 andSet2.Left = andSet2.ID - 1;
                 andSet2.Right = andSet2.ID + 1;
                 if (k == 0)
                 {
                     andSet2.Left = andSet2.ID + 9;
                 }
                 if (k == list2.Count - 1)
                 {
                     andSet2.Right = andSet2.ID - 9;
                 }
                 andSet2.Down = down;
                 if (k >= 5)
                 {
                     andSet2.Down = down2;
                 }
                 _foundPoints.Add(num3);
                 num3++;
             }
             break;
         }
         }
         if (PlayerInput.UsingGamepadUI && !_foundPoints.Contains(UILinkPointNavigator.CurrentPoint))
         {
             MoveToVisuallyClosestPoint();
         }
     }
References _foundPoints, _hairstylesContainer, _helper, _selectedPicker, HairstyleUnlocksHelper.AvailableHairstyles, UILinkPointNavigator.Shortcuts.BackButtonCommand, UIGamepadHelper.CullPointsOutOfElementArea(), UILinkPointNavigator.CurrentPoint, UILinkPoint.Down, GetAndSet(), UIElement.GetSnapPoints(), Main.Hairstyles, UILinkPoint.ID, SnapPoint.Id, UILinkPoint.Left, MoveToVisuallyClosestPoint(), SnapPoint.Name, UILinkPointNavigator.Points, SnapPoint.Position, UILinkPoint.Right, UILinkPointNavigator.SetPosition(), SortPoints(), UILinkPoint.Unlink(), UILinkPoint.Up, and PlayerInput.UsingGamepadUI.
Referenced by Draw().