Terraria: UICharacterCreation.CreatePickerWithoutClick
CreatePickerWithoutClick()
UIColoredImageButton UICharacterCreation.CreatePickerWithoutClick (CategoryId id, string texturePath, float xPositionStart, float xPositionPerId) inline private
     {
         UIColoredImageButton uIColoredImageButton = new UIColoredImageButton(Main.Assets.Request<Texture2D>(texturePath, (AssetRequestMode)1));
         uIColoredImageButton.VAlign = 0f;
         uIColoredImageButton.HAlign = 0f;
         uIColoredImageButton.Left.Set(xPositionStart + (float)id * xPositionPerId, 0.5f);
         return uIColoredImageButton;
     }
References Main.Assets, UIElement.HAlign, UIElement.Left, StyleDimension.Set(), and UIElement.VAlign.
Referenced by MakeCategoriesBar(), and MakeClothStylesMenu().