Terraria: System.Data.Common.DbDataReaderExtensions.GetColumnSchemaCompatibility
GetColumnSchemaCompatibility()
static ReadOnlyCollection< DbColumn > System.Data.Common.DbDataReaderExtensions.GetColumnSchemaCompatibility (DbDataReader reader) inline static private
Definition at line 80 of file DbDataReaderExtensions.cs.
    {
        List<DbColumn> list = new List<DbColumn>();
        DataTable schemaTable = reader.GetSchemaTable();
        if (schemaTable != null)
        {
            DataColumnCollection columns = schemaTable.Columns;
            foreach (DataRow row in schemaTable.Rows)
            {
                list.Add(new DataRowDbColumn(row, columns));
            }
        }
        return new ReadOnlyCollection<DbColumn>(list);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.Common.DbDataReader.GetSchemaTable(), and System.list.
Referenced by System.Data.Common.DbDataReaderExtensions.GetColumnSchema().