Terraria: Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
Definition at line 187 of file UIWorkshopPublishResourcePackListItem.cs.
    {
        base.DrawSelf(spriteBatch);
        CalculatedStyle innerDimensions = GetInnerDimensions();
        CalculatedStyle dimensions = _iconArea.GetDimensions();
        float num = dimensions.X + dimensions.Width;
        Color white = Color.White;
        Utils.DrawBorderString(spriteBatch, _data.Name, new Vector2(num + 8f, innerDimensions.Y + 3f), white);
        float num2 = (innerDimensions.Width - 22f - dimensions.Width - _publishButton.GetDimensions().Width) / 2f;
        float height = _publishButton.GetDimensions().Height;
        Vector2 vector = new Vector2(num + 8f, innerDimensions.Y + innerDimensions.Height - height);
        float num3 = num2;
        DrawPanel(spriteBatch, vector, num3, height);
        string textValue = Language.GetTextValue("UI.Author", _data.Author);
        Color white2 = Color.White;
        Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(textValue);
        float x = vector2.X;
        float y = vector2.Y;
        float x2 = num3 * 0.5f - x * 0.5f;
        float num4 = height * 0.5f - y * 0.5f;
        Utils.DrawBorderString(spriteBatch, textValue, vector + new Vector2(x2, num4 + 3f), white2);
        vector.X += num3 + 5f;
        float num5 = num2;
        DrawPanel(spriteBatch, vector, num5, height);
        string textValue2 = Language.GetTextValue("UI.Version", _data.Version.GetFormattedVersion());
        Color white3 = Color.White;
        Vector2 vector3 = FontAssets.MouseText.Value.MeasureString(textValue2);
        float x3 = vector3.X;
        float y2 = vector3.Y;
        float x4 = num5 * 0.5f - x3 * 0.5f;
        float num6 = height * 0.5f - y2 * 0.5f;
        Utils.DrawBorderString(spriteBatch, textValue2, vector + new Vector2(x4, num6 + 3f), white3);
        vector.X += num5 + 5f;
    }
References Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._data, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._iconArea, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._publishButton, Terraria.IO.ResourcePack.Author, Terraria.Utils.DrawBorderString(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawPanel(), Terraria.UI.UIElement.GetDimensions(), Terraria.IO.ResourcePackVersion.GetFormattedVersion(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.CalculatedStyle.Height, Terraria.GameContent.FontAssets.MouseText, Terraria.IO.ResourcePack.Name, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.IO.ResourcePack.Version, Microsoft.Xna.Framework.Color.White, Terraria.UI.CalculatedStyle.Width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.UI.CalculatedStyle.Y.