Terraria: System.Reflection.ParameterInfo.GetRequiredCustomModifiers
GetRequiredCustomModifiers()
virtual Type[] System.Reflection.ParameterInfo.GetRequiredCustomModifiers () inline virtual
Reimplemented in System.Reflection.RuntimeParameterInfo.
Definition at line 105 of file ParameterInfo.cs.
    {
        return Type.EmptyTypes;
    }
References System.Type.EmptyTypes.
Referenced by System.Reflection.DispatchProxyGenerator.ProxyBuilder.AddMethodImpl(), System.Reflection.Emit.DynamicILGenerator.GetMemberRefToken(), and System.Reflection.Emit.ModuleBuilder.InternalGetConstructorToken().