Terraria: Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem
UIWorkshopPublishResourcePackListItem()
Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem (UIState ownerState, ResourcePack data, int orderInList, bool canBePublished) inline
Definition at line 41 of file UIWorkshopPublishResourcePackListItem.cs.
    {
        _ownerState = ownerState;
        _orderInList = orderInList;
        _data = data;
        _canPublish = canBePublished;
        LoadTextures();
        InitializeAppearance();
        UIElement uIElement = new UIElement
        {
            Width = new StyleDimension(72f, 0f),
            Height = new StyleDimension(72f, 0f),
            Left = new StyleDimension(4f, 0f),
            VAlign = 0.5f
        };
        uIElement.OnLeftDoubleClick += PublishButtonClick_ImportResourcePackToLocalFiles;
        UIImage element = new UIImage(data.Icon)
        {
            Width = new StyleDimension(-6f, 1f),
            Height = new StyleDimension(-6f, 1f),
            HAlign = 0.5f,
            VAlign = 0.5f,
            ScaleToFit = true,
            AllowResizingDimensions = false,
            IgnoresMouseInteraction = true
        };
        UIImage element2 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Achievement_Borders", (AssetRequestMode)1))
        {
            HAlign = 0.5f,
            VAlign = 0.5f,
            IgnoresMouseInteraction = true
        };
        uIElement.Append(element);
        uIElement.Append(element2);
        Append(uIElement);
        _iconArea = uIElement;
        _ = 4f;
        _publishButton = new UIIconTextButton(Language.GetText("Workshop.Publish"), Color.White, "Images/UI/Workshop/Publish");
        _publishButton.HAlign = 1f;
        _publishButton.VAlign = 1f;
        _publishButton.OnLeftClick += PublishButtonClick_ImportResourcePackToLocalFiles;
        base.OnLeftDoubleClick += PublishButtonClick_ImportResourcePackToLocalFiles;
        Append(_publishButton);
        _publishButton.SetSnapPoint("Publish", orderInList);
    }
References Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._canPublish, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._data, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._iconArea, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._orderInList, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._ownerState, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem._publishButton, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.IO.ResourcePack.Icon, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.InitializeAppearance(), Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.LoadTextures(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.PublishButtonClick_ImportResourcePackToLocalFiles(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.