Terraria: AmbientWindSystem.SpawnFloorCloud
SpawnFloorCloud()
void AmbientWindSystem.SpawnFloorCloud (int x, int y) inline private
     {
         Vector2 position = new Point(x, y - 1).ToWorldCoordinates();
         int type = _random.Next(1087, 1090);
         float num = 16f * _random.NextFloat();
         position.Y -= num;
         if (num < 4f)
         {
             type = 1090;
         }
         float num2 = 0.4f;
         float scale = 0.8f + _random.NextFloat() * 0.2f;
         Gore.NewGorePerfect(position, Vector2.UnitX * num2 * Main.WindForVisuals, type, scale);
     }
References _random, Gore.NewGorePerfect(), UnifiedRandom.Next(), and Main.WindForVisuals.
Referenced by TrySpawningWind().