Terraria: System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid
IsValid() [1/2]
virtual bool System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid (object? value) inline virtual
Reimplemented in System.ComponentModel.DataAnnotations.CreditCardAttribute, System.ComponentModel.DataAnnotations.DataTypeAttribute, System.ComponentModel.DataAnnotations.EmailAddressAttribute, System.ComponentModel.DataAnnotations.EnumDataTypeAttribute, System.ComponentModel.DataAnnotations.FileExtensionsAttribute, System.ComponentModel.DataAnnotations.MaxLengthAttribute, System.ComponentModel.DataAnnotations.MinLengthAttribute, System.ComponentModel.DataAnnotations.PhoneAttribute, System.ComponentModel.DataAnnotations.RangeAttribute, System.ComponentModel.DataAnnotations.RegularExpressionAttribute, System.ComponentModel.DataAnnotations.RequiredAttribute, System.ComponentModel.DataAnnotations.StringLengthAttribute, and System.ComponentModel.DataAnnotations.UrlAttribute.
Definition at line 162 of file ValidationAttribute.cs.
    {
        if (!_hasBaseIsValid)
        {
            _hasBaseIsValid = true;
        }
        return IsValid(value, null) == ValidationResult.Success;
    }
References System.ComponentModel.DataAnnotations.ValidationAttribute._hasBaseIsValid, System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(), System.ComponentModel.DataAnnotations.ValidationResult.Success, and System.value.
Referenced by System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(), System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(), System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(), and System.ComponentModel.DataAnnotations.ValidationAttribute.Validate().