Terraria: System.ComponentModel.DataAnnotations.ValidationAttribute.SetResourceAccessorByPropertyLookup
SetResourceAccessorByPropertyLookup()
void System.ComponentModel.DataAnnotations.ValidationAttribute.SetResourceAccessorByPropertyLookup () inline private
Definition at line 135 of file ValidationAttribute.cs.
    {
        PropertyInfo property = _errorMessageResourceType.GetProperty(_errorMessageResourceName, BindingFlags.DeclaredOnly | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
        if (property != null)
        {
            MethodInfo getMethod = property.GetMethod;
            if (getMethod == null || (!getMethod.IsAssembly && !getMethod.IsPublic))
            {
                property = null;
            }
        }
        if (property == null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.ValidationAttribute_ResourceTypeDoesNotHaveProperty, _errorMessageResourceType.FullName, _errorMessageResourceName));
        }
        if (property.PropertyType != typeof(string))
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.ValidationAttribute_ResourcePropertyNotStringType, property.Name, _errorMessageResourceType.FullName));
        }
        _errorMessageResourceAccessor = () => (string)property.GetValue(null, null);
    }
References System.ComponentModel.DataAnnotations.ValidationAttribute._errorMessageResourceAccessor, System.ComponentModel.DataAnnotations.ValidationAttribute._errorMessageResourceName, System.ComponentModel.DataAnnotations.ValidationAttribute._errorMessageResourceType, System.SR.Format(), System.Type.FullName, System.Type.GetProperty(), System.Reflection.MethodBase.IsAssembly, System.Reflection.MethodBase.IsPublic, System.SR.ValidationAttribute_ResourcePropertyNotStringType, and System.SR.ValidationAttribute_ResourceTypeDoesNotHaveProperty.
Referenced by System.ComponentModel.DataAnnotations.ValidationAttribute.SetupResourceAccessor().