Terraria: System.ComponentModel.DataAnnotations.ValidationAttribute.FormatErrorMessage
FormatErrorMessage()
virtual string System.ComponentModel.DataAnnotations.ValidationAttribute.FormatErrorMessage (string name) inline virtual
Reimplemented in System.ComponentModel.DataAnnotations.CompareAttribute, System.ComponentModel.DataAnnotations.CustomValidationAttribute, System.ComponentModel.DataAnnotations.FileExtensionsAttribute, System.ComponentModel.DataAnnotations.MaxLengthAttribute, System.ComponentModel.DataAnnotations.MinLengthAttribute, System.ComponentModel.DataAnnotations.RangeAttribute, System.ComponentModel.DataAnnotations.RegularExpressionAttribute, and System.ComponentModel.DataAnnotations.StringLengthAttribute.
Definition at line 157 of file ValidationAttribute.cs.
    {
        return string.Format(CultureInfo.CurrentCulture, ErrorMessageString, name);
    }
References System.Globalization.CultureInfo.CurrentCulture, and System.ComponentModel.DataAnnotations.ValidationAttribute.ErrorMessageString.
Referenced by System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(), System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(), and System.ComponentModel.DataAnnotations.ValidationAttribute.Validate().