Terraria: MS.Internal.Xml.Linq.ComponentModel.XPropertyDescriptor.AddValueChanged
AddValueChanged()
override void MS.Internal.Xml.Linq.ComponentModel.XPropertyDescriptor< T, TProperty >.AddValueChanged (object component, EventHandler handler) inline virtual
Reimplemented from System.ComponentModel.PropertyDescriptor.
Definition at line 22 of file XPropertyDescriptor.cs.
    {
        bool flag = GetValueChangedHandler(component) != null;
        base.AddValueChanged(component, handler);
        if (!flag && component is T val && GetValueChangedHandler(component) != null)
        {
            val.Changing += OnChanging;
            val.Changed += OnChanged;
        }
    }
References System.ComponentModel.PropertyDescriptor.GetValueChangedHandler(), MS.Internal.Xml.Linq.ComponentModel.XPropertyDescriptor< T, TProperty >.OnChanged(), and MS.Internal.Xml.Linq.ComponentModel.XPropertyDescriptor< T, TProperty >.OnChanging().