Terraria: System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid
IsValid() [2/2]
virtual ? ValidationResult System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid (object? value, ValidationContext validationContext) inline protected virtual
Reimplemented in System.ComponentModel.DataAnnotations.CompareAttribute, and System.ComponentModel.DataAnnotations.CustomValidationAttribute.
Definition at line 171 of file ValidationAttribute.cs.
    {
        if (_hasBaseIsValid)
        {
            throw System.NotImplemented.ByDesignWithMessage(System.SR.ValidationAttribute_IsValid_NotImplemented);
        }
        ValidationResult result = ValidationResult.Success;
        if (!IsValid(value))
        {
            string memberName = validationContext.MemberName;
            string[] memberNames = ((memberName == null) ? null : new string[1] { memberName });
            result = new ValidationResult(FormatErrorMessage(validationContext.DisplayName), memberNames);
        }
        return result;
    }
References System.ComponentModel.DataAnnotations.ValidationAttribute._hasBaseIsValid, System.NotImplemented.ByDesignWithMessage(), System.ComponentModel.DataAnnotations.ValidationContext.DisplayName, System.ComponentModel.DataAnnotations.ValidationAttribute.FormatErrorMessage(), System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(), System.ComponentModel.DataAnnotations.ValidationContext.MemberName, System.ComponentModel.DataAnnotations.ValidationResult.Success, System.SR.ValidationAttribute_IsValid_NotImplemented, and System.value.