Terraria: System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult
GetValidationResult()
ValidationResult? System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult (object? value, ValidationContext validationContext) inline
Definition at line 187 of file ValidationAttribute.cs.
    {
        if (validationContext == null)
        {
            throw new ArgumentNullException("validationContext");
        }
        ValidationResult validationResult = IsValid(value, validationContext);
        if (validationResult != null && string.IsNullOrEmpty(validationResult.ErrorMessage))
        {
            string errorMessage = FormatErrorMessage(validationContext.DisplayName);
            validationResult = new ValidationResult(errorMessage, validationResult.MemberNames);
        }
        return validationResult;
    }
References System.ComponentModel.DataAnnotations.ValidationContext.DisplayName, System.ComponentModel.DataAnnotations.ValidationResult.ErrorMessage, System.ComponentModel.DataAnnotations.ValidationAttribute.FormatErrorMessage(), System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(), System.ComponentModel.DataAnnotations.ValidationResult.MemberNames, and System.value.
Referenced by System.ComponentModel.DataAnnotations.ValidationAttribute.Validate().