Terraria: System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.IsValid
IsValid() [1/2]
override bool System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.IsValid (object? value) inline virtual
Reimplemented from System.ComponentModel.DataAnnotations.DataTypeAttribute.
Definition at line 16 of file EnumDataTypeAttribute.cs.
    {
        if (EnumType == null)
        {
            throw new InvalidOperationException(System.SR.EnumDataTypeAttribute_TypeCannotBeNull);
        }
        if (!EnumType.IsEnum)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.EnumDataTypeAttribute_TypeNeedsToBeAnEnum, EnumType.FullName));
        }
        if (value == null)
        {
            return true;
        }
        string text = value as string;
        if (text != null && text.Length == 0)
        {
            return true;
        }
        Type type = value.GetType();
        if (type.IsEnum && EnumType != type)
        {
            return false;
        }
        if (!type.IsValueType && type != typeof(string))
        {
            return false;
        }
        if (type == typeof(bool) || type == typeof(float) || type == typeof(double) || type == typeof(decimal) || type == typeof(char))
        {
            return false;
        }
        object obj;
        if (type.IsEnum)
        {
            obj = value;
        }
        else
        {
            try
            {
                obj = ((text != null) ? Enum.Parse(EnumType, text, ignoreCase: false) : Enum.ToObject(EnumType, value));
            }
            catch (ArgumentException)
            {
                return false;
            }
        }
        if (IsEnumTypeInFlagsMode(EnumType))
        {
            string underlyingTypeValueString = GetUnderlyingTypeValueString(EnumType, obj);
            string value2 = obj.ToString();
            return !underlyingTypeValueString.Equals(value2);
        }
        return Enum.IsDefined(EnumType, obj);
    }
References System.SR.EnumDataTypeAttribute_TypeCannotBeNull, System.SR.EnumDataTypeAttribute_TypeNeedsToBeAnEnum, System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.EnumType, System.SR.Format(), System.Type.FullName, System.Type.GetType(), System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.GetUnderlyingTypeValueString(), System.Enum.IsDefined(), System.Type.IsEnum, System.ComponentModel.DataAnnotations.EnumDataTypeAttribute.IsEnumTypeInFlagsMode(), System.obj, System.Enum.Parse(), System.text, System.Enum.ToObject(), System.type, and System.value.