Terraria: Cloud.resetClouds
resetClouds()
static void Cloud.resetClouds () inline static
     {
         if (!Main.dedServ)
         {
             Main.windSpeedCurrent = Main.windSpeedTarget;
             for (int i = 0; i < 200; i++)
             {
                 Main.cloud[i].active = false;
             }
             for (int j = 0; j < Main.numClouds; j++)
             {
                 addCloud();
                 Main.cloud[j].Alpha = 1f;
             }
             for (int k = 0; k < 200; k++)
             {
                 Main.cloud[k].Alpha = 1f;
             }
         }
     }
References active, addCloud(), Alpha, Main.cloud, Main.dedServ, Main.numClouds, Main.windSpeedCurrent, and Main.windSpeedTarget.
Referenced by Main.DrawBG(), Netplay.InnerClientLoop(), WorldFile.LoadWorld(), and WorldGen.RandomizeWeather().