Terraria: PlayerDrawHeadSet.BoringSetup
BoringSetup()
void PlayerDrawHeadSet.BoringSetup (Player drawPlayer2, List< DrawData > drawData, List< int > dust, List< int > gore, float X, float Y, float Alpha, float Scale) inline
     {
         DrawData = drawData;
         Dust = dust;
         Gore = gore;
         drawPlayer = drawPlayer2;
         Position = drawPlayer.position;
         cHead = 0;
         cFace = 0;
         cUnicornHorn = 0;
         cAngelHalo = 0;
         cBeard = 0;
         drawUnicornHorn = false;
         drawAngelHalo = false;
         skinVar = drawPlayer.skinVariant;
         hairShaderPacked = PlayerDrawHelper.PackShader(drawPlayer.hairDye, PlayerDrawHelper.ShaderConfiguration.HairShader);
         if (drawPlayer.head == 0 && drawPlayer.hairDye == 0)
         {
             hairShaderPacked = PlayerDrawHelper.PackShader(1, PlayerDrawHelper.ShaderConfiguration.HairShader);
         }
         skinDyePacked = drawPlayer.skinDyePacked;
         if (drawPlayer.face > 0 && drawPlayer.face < ArmorIDs.Face.Count)
         {
             Main.instance.LoadAccFace(drawPlayer.face);
         }
         cHead = drawPlayer.cHead;
         cFace = drawPlayer.cFace;
         cFaceHead = drawPlayer.cFaceHead;
         cFaceFlower = drawPlayer.cFaceFlower;
         cUnicornHorn = drawPlayer.cUnicornHorn;
         cAngelHalo = drawPlayer.cAngelHalo;
         cBeard = drawPlayer.cBeard;
         drawUnicornHorn = drawPlayer.hasUnicornHorn;
         drawAngelHalo = drawPlayer.hasAngelHalo;
         Main.instance.LoadHair(drawPlayer.hair);
         scale = Scale;
         colorEyeWhites = Main.quickAlpha(Color.White, Alpha);
         colorEyes = Main.quickAlpha(drawPlayer.eyeColor, Alpha);
         colorHair = Main.quickAlpha(drawPlayer.GetHairColor(useLighting: false), Alpha);
         colorHead = Main.quickAlpha(drawPlayer.skinColor, Alpha);
         colorArmorHead = Main.quickAlpha(Color.White, Alpha);
         if (drawPlayer.isDisplayDollOrInanimate)
         {
             colorDisplayDollSkin = Main.quickAlpha(PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, Alpha);
         }
         else
         {
             colorDisplayDollSkin = colorHead;
         }
         playerEffect = SpriteEffects.None;
         if (drawPlayer.direction < 0)
         {
             playerEffect = SpriteEffects.FlipHorizontally;
         }
         headVect = new Vector2((float)drawPlayer.legFrame.Width * 0.5f, (float)drawPlayer.legFrame.Height * 0.4f);
         bodyFrameMemory = drawPlayer.bodyFrame;
         bodyFrameMemory.Y = 0;
         Position = Main.screenPosition;
         Position.X += X;
         Position.Y += Y;
         Position.X -= 6f;
         Position.Y -= 4f;
         Position.Y -= drawPlayer.HeightMapOffset;
         if (drawPlayer.head > 0 && drawPlayer.head < ArmorIDs.Head.Count)
         {
             Main.instance.LoadArmorHead(drawPlayer.head);
             int num = ArmorIDs.Head.Sets.FrontToBackID[drawPlayer.head];
             if (num >= 0)
             {
                 Main.instance.LoadArmorHead(num);
             }
         }
         if (drawPlayer.face > 0 && drawPlayer.face < ArmorIDs.Face.Count)
         {
             Main.instance.LoadAccFace(drawPlayer.face);
         }
         if (drawPlayer.faceHead > 0 && drawPlayer.faceHead < ArmorIDs.Face.Count)
         {
             Main.instance.LoadAccFace(drawPlayer.faceHead);
         }
         if (drawPlayer.faceFlower > 0 && drawPlayer.faceFlower < ArmorIDs.Face.Count)
         {
             Main.instance.LoadAccFace(drawPlayer.faceFlower);
         }
         if (drawPlayer.beard > 0 && drawPlayer.beard < ArmorIDs.Beard.Count)
         {
             Main.instance.LoadAccBeard(drawPlayer.beard);
         }
         drawPlayer.GetHairSettings(out fullHair, out hatHair, out hideHair, out var _, out helmetIsOverFullHair);
         hairOffset = drawPlayer.GetHairDrawOffset(drawPlayer.hair, hatHair);
         hairOffset.Y *= drawPlayer.Directions.Y;
         helmetOffset = drawPlayer.GetHelmetDrawOffset();
         helmetOffset.Y *= drawPlayer.Directions.Y;
         helmetIsTall = drawPlayer.head == 14 || drawPlayer.head == 56 || drawPlayer.head == 158;
         helmetIsNormal = !helmetIsTall && !helmetIsOverFullHair && drawPlayer.head > 0 && drawPlayer.head < ArmorIDs.Head.Count && drawPlayer.head != 28;
     }
References Player.beard, Player.bodyFrame, bodyFrameMemory, cAngelHalo, Player.cAngelHalo, cBeard, Player.cBeard, cFace, Player.cFace, cFaceFlower, Player.cFaceFlower, cFaceHead, Player.cFaceHead, cHead, Player.cHead, Color, colorArmorHead, colorDisplayDollSkin, colorEyes, colorEyeWhites, colorHair, colorHead, ArmorIDs.Head.Count, ArmorIDs.Face.Count, ArmorIDs.Beard.Count, cUnicornHorn, Player.cUnicornHorn, Entity.direction, Player.Directions, PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, drawAngelHalo, drawPlayer, drawUnicornHorn, Player.eyeColor, Player.face, Player.faceFlower, Player.faceHead, ArmorIDs.Head.Sets.FrontToBackID, fullHair, Player.GetHairColor(), Player.GetHairDrawOffset(), Player.GetHairSettings(), Player.GetHelmetDrawOffset(), Player.hair, Player.hairDye, hairOffset, hairShaderPacked, Player.hasAngelHalo, Player.hasUnicornHorn, hatHair, Player.head, headVect, Player.HeightMapOffset, helmetIsNormal, helmetIsOverFullHair, helmetIsTall, helmetOffset, hideHair, Main.instance, Player.isDisplayDollOrInanimate, Player.legFrame, Main.LoadAccBeard(), Main.LoadAccFace(), Main.LoadArmorHead(), Main.LoadHair(), PlayerDrawHelper.PackShader(), playerEffect, Position, Entity.position, Main.quickAlpha(), scale, Main.screenPosition, Player.skinColor, skinDyePacked, Player.skinDyePacked, skinVar, Player.skinVariant, X, and Y.
Referenced by LegacyPlayerRenderer.DrawPlayerHead(), and PlayerHeadDrawRenderTargetContent.DrawTheContent().