Terraria: System.Xml.Xsl.XsltOld.WriterOutput.RecordDone
RecordDone()
Processor.OutputResult System.Xml.Xsl.XsltOld.WriterOutput.RecordDone (RecordBuilder record) inline
Implements System.Xml.Xsl.XsltOld.IRecordOutput.
Definition at line 21 of file WriterOutput.cs.
    {
        BuilderInfo mainNode = record.MainNode;
        switch (mainNode.NodeType)
        {
        case XmlNodeType.Element:
            _writer.WriteStartElement(mainNode.Prefix, mainNode.LocalName, mainNode.NamespaceURI);
            WriteAttributes(record.AttributeList, record.AttributeCount);
            if (mainNode.IsEmptyTag)
            {
                _writer.WriteEndElement();
            }
            break;
        case XmlNodeType.Text:
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            _writer.WriteString(mainNode.Value);
            break;
        case XmlNodeType.CDATA:
            _writer.WriteCData(mainNode.Value);
            break;
        case XmlNodeType.EntityReference:
            _writer.WriteEntityRef(mainNode.LocalName);
            break;
        case XmlNodeType.ProcessingInstruction:
            _writer.WriteProcessingInstruction(mainNode.LocalName, mainNode.Value);
            break;
        case XmlNodeType.Comment:
            _writer.WriteComment(mainNode.Value);
            break;
        case XmlNodeType.DocumentType:
            _writer.WriteRaw(mainNode.Value);
            break;
        case XmlNodeType.EndElement:
            _writer.WriteFullEndElement();
            break;
        }
        record.Reset();
        return Processor.OutputResult.Continue;
    }
References System.Xml.Xsl.XsltOld.WriterOutput._writer, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.WriterOutput.WriteAttributes(), System.Xml.XmlWriter.WriteCData(), System.Xml.XmlWriter.WriteComment(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteEntityRef(), System.Xml.XmlWriter.WriteFullEndElement(), System.Xml.XmlWriter.WriteProcessingInstruction(), System.Xml.XmlWriter.WriteRaw(), System.Xml.XmlWriter.WriteStartElement(), and System.Xml.XmlWriter.WriteString().