Terraria: Terraria.Graphics.RainbowRodDrawer.Draw
Draw()
void Terraria.Graphics.RainbowRodDrawer.Draw (Projectile proj) inline
Definition at line 12 of file RainbowRodDrawer.cs.
    {
        MiscShaderData miscShaderData = GameShaders.Misc["RainbowRod"];
        miscShaderData.UseSaturation(-2.8f);
        miscShaderData.UseOpacity(4f);
        miscShaderData.Apply();
        _vertexStrip.PrepareStripWithProceduralPadding(proj.oldPos, proj.oldRot, StripColors, StripWidth, -Main.screenPosition + proj.Size / 2f);
        _vertexStrip.DrawTrail();
        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
    }
References Terraria.Graphics.RainbowRodDrawer._vertexStrip, Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.Graphics.VertexStrip.DrawTrail(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Main.pixelShader, Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), Terraria.Main.screenPosition, Terraria.Entity.Size, Terraria.Graphics.RainbowRodDrawer.StripColors(), Terraria.Graphics.RainbowRodDrawer.StripWidth(), Terraria.Graphics.Shaders.MiscShaderData.UseOpacity(), and Terraria.Graphics.Shaders.MiscShaderData.UseSaturation().