Terraria: Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
    {
        UISliderBase.CurrentAimedSlider = null;
        if (!Main.mouseLeft)
        {
            UISliderBase.CurrentLockedSlider = null;
        }
        GetUsageLevel();
        FillPercent = _getSliderValue();
        float sliderValueThatWasSet = FillPercent;
        bool flag = false;
        if (DrawValueBarDynamicWidth(spriteBatch, out sliderValueThatWasSet))
        {
            flag = true;
        }
        if (UISliderBase.CurrentLockedSlider == this || flag)
        {
            UISliderBase.CurrentAimedSlider = this;
            if (PlayerInput.Triggers.Current.MouseLeft && !PlayerInput.UsingGamepad && UISliderBase.CurrentLockedSlider == this)
            {
                _slideKeyboardAction(sliderValueThatWasSet);
                if (!_soundedUsage)
                {
                    SoundEngine.PlaySound(12);
                }
                _soundedUsage = true;
            }
            else
            {
                _soundedUsage = false;
            }
        }
        if (UISliderBase.CurrentAimedSlider != null && UISliderBase.CurrentLockedSlider == null)
        {
            UISliderBase.CurrentLockedSlider = UISliderBase.CurrentAimedSlider;
        }
        if (_isReallyMouseOvered)
        {
            _slideGamepadAction();
        }
    }
References Terraria.GameContent.UI.Elements.UIVerticalSlider._getSliderValue, Terraria.GameContent.UI.Elements.UIVerticalSlider._isReallyMouseOvered, Terraria.GameContent.UI.Elements.UIVerticalSlider._slideGamepadAction, Terraria.GameContent.UI.Elements.UIVerticalSlider._slideKeyboardAction, Terraria.GameContent.UI.Elements.UIVerticalSlider._soundedUsage, Terraria.GameInput.TriggersPack.Current, Terraria.GameContent.UI.Elements.UISliderBase.CurrentAimedSlider, Terraria.GameContent.UI.Elements.UISliderBase.CurrentLockedSlider, Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.GameContent.UI.Elements.UIVerticalSlider.FillPercent, Terraria.GameContent.UI.Elements.UISliderBase.GetUsageLevel(), Terraria.GameInput.TriggersSet.MouseLeft, Terraria.Main.mouseLeft, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameInput.PlayerInput.Triggers, and Terraria.GameInput.PlayerInput.UsingGamepad.