Terraria: System.Xml.Schema.XmlSchemaInfo.Clear
Clear()
void System.Xml.Schema.XmlSchemaInfo.Clear () inline package
Definition at line 180 of file XmlSchemaInfo.cs.
    {
        _isNil = false;
        _isDefault = false;
        _schemaType = null;
        _schemaElement = null;
        _schemaAttribute = null;
        _memberType = null;
        _validity = XmlSchemaValidity.NotKnown;
        _contentType = XmlSchemaContentType.Empty;
    }
References System.Xml.Schema.XmlSchemaInfo._contentType, System.Xml.Schema.XmlSchemaInfo._isDefault, System.Xml.Schema.XmlSchemaInfo._isNil, System.Xml.Schema.XmlSchemaInfo._memberType, System.Xml.Schema.XmlSchemaInfo._schemaAttribute, System.Xml.Schema.XmlSchemaInfo._schemaElement, System.Xml.Schema.XmlSchemaInfo._schemaType, and System.Xml.Schema.XmlSchemaInfo._validity.
Referenced by System.Xml.Schema.XmlSchemaInfo.XmlSchemaInfo(), System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.AttributePSVIInfo.Reset(), System.Xml.DocumentSchemaValidator.SetDefaultAttributeSchemaInfo(), and System.Xml.Schema.XmlSchemaValidator.ValidateAttribute().