Terraria: System.IO.Compression.ZipLocalFileHeader.GetExtraFields
GetExtraFields()
static List< ZipGenericExtraField > System.IO.Compression.ZipLocalFileHeader.GetExtraFields (BinaryReader reader) inline static
Definition at line 9 of file ZipLocalFileHeader.cs.
    {
        reader.BaseStream.Seek(26L, SeekOrigin.Current);
        ushort num = reader.ReadUInt16();
        ushort num2 = reader.ReadUInt16();
        reader.BaseStream.Seek(num, SeekOrigin.Current);
        List<ZipGenericExtraField> list;
        using (Stream extraFieldData = new SubReadStream(reader.BaseStream, reader.BaseStream.Position, num2))
        {
            list = ZipGenericExtraField.ParseExtraField(extraFieldData);
        }
        Zip64ExtraField.RemoveZip64Blocks(list);
        return list;
    }
References System.IO.BinaryReader.BaseStream, System.L, System.list, System.IO.Compression.ZipGenericExtraField.ParseExtraField(), System.IO.BinaryReader.ReadUInt16(), and System.IO.Compression.Zip64ExtraField.RemoveZip64Blocks().
Referenced by System.IO.Compression.ZipArchiveEntry.LoadLocalHeaderExtraFieldAndCompressedBytesIfNeeded().