Terraria: System.Xml.XmlDictionaryWriter.WriteNode
WriteNode() [1/3]
virtual void System.Xml.XmlDictionaryWriter.WriteNode (XmlDictionaryReader reader, bool defattr) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter.
Definition at line 681 of file XmlDictionaryWriter.cs.
    {
        if (reader == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("reader"));
        }
        int num = ((reader.NodeType == XmlNodeType.None) ? (-1) : reader.Depth);
        do
        {
            XmlNodeType nodeType = reader.NodeType;
            if (nodeType == XmlNodeType.Text || nodeType == XmlNodeType.Whitespace || nodeType == XmlNodeType.SignificantWhitespace)
            {
                WriteTextNode(reader, isAttribute: false);
                continue;
            }
            if (reader.Depth > num && reader.IsStartArray(out Type type))
            {
                WriteArrayNode(reader, type);
                continue;
            }
            switch (nodeType)
            {
            case XmlNodeType.Element:
                WriteElementNode(reader, defattr);
                break;
            case XmlNodeType.CDATA:
                WriteCData(reader.Value);
                break;
            case XmlNodeType.EntityReference:
                WriteEntityRef(reader.Name);
                break;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.XmlDeclaration:
                WriteProcessingInstruction(reader.Name, reader.Value);
                break;
            case XmlNodeType.DocumentType:
                WriteDocType(reader.Name, reader.GetAttribute("PUBLIC"), reader.GetAttribute("SYSTEM"), reader.Value);
                break;
            case XmlNodeType.Comment:
                WriteComment(reader.Value);
                break;
            case XmlNodeType.EndElement:
                WriteFullEndElement();
                break;
            }
            if (!reader.Read())
            {
                break;
            }
        }
        while (num < reader.Depth || (num == reader.Depth && reader.NodeType == XmlNodeType.EndElement));
    }
References System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlDictionaryReader.GetAttribute(), System.Xml.XmlDictionaryReader.IsStartArray(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, System.Xml.XmlReader.Value, System.Xml.XmlDictionaryWriter.WriteArrayNode(), System.Xml.XmlWriter.WriteCData(), System.Xml.XmlWriter.WriteComment(), System.Xml.XmlWriter.WriteDocType(), System.Xml.XmlDictionaryWriter.WriteElementNode(), System.Xml.XmlWriter.WriteEntityRef(), System.Xml.XmlWriter.WriteFullEndElement(), System.Xml.XmlWriter.WriteProcessingInstruction(), and System.Xml.XmlDictionaryWriter.WriteTextNode().