Terraria: System.Xml.XmlDictionaryWriter.WriteElementNode
WriteElementNode()
void System.Xml.XmlDictionaryWriter.WriteElementNode (XmlDictionaryReader reader, bool defattr) inline private inherited
Definition at line 485 of file XmlDictionaryWriter.cs.
    {
        if (reader.TryGetLocalNameAsDictionaryString(out XmlDictionaryString localName) && reader.TryGetNamespaceUriAsDictionaryString(out XmlDictionaryString namespaceUri))
        {
            WriteStartElement(reader.Prefix, localName, namespaceUri);
        }
        else
        {
            WriteStartElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
        }
        if ((defattr || !reader.IsDefault) && reader.MoveToFirstAttribute())
        {
            do
            {
                if (reader.TryGetLocalNameAsDictionaryString(out localName) && reader.TryGetNamespaceUriAsDictionaryString(out namespaceUri))
                {
                    WriteStartAttribute(reader.Prefix, localName, namespaceUri);
                }
                else
                {
                    WriteStartAttribute(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                }
                while (reader.ReadAttributeValue())
                {
                    if (reader.NodeType == XmlNodeType.EntityReference)
                    {
                        WriteEntityRef(reader.Name);
                    }
                    else
                    {
                        WriteTextNode(reader, isAttribute: true);
                    }
                }
                WriteEndAttribute();
            }
            while (reader.MoveToNextAttribute());
            reader.MoveToElement();
        }
        if (reader.IsEmptyElement)
        {
            WriteEndElement();
        }
    }
References System.Xml.Dictionary, System.Xml.XmlReader.IsDefault, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlDictionaryReader.TryGetLocalNameAsDictionaryString(), System.Xml.XmlDictionaryReader.TryGetNamespaceUriAsDictionaryString(), System.Xml.XmlWriter.WriteEndAttribute(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteEntityRef(), System.Xml.XmlDictionaryWriter.WriteStartAttribute(), System.Xml.XmlDictionaryWriter.WriteStartElement(), and System.Xml.XmlDictionaryWriter.WriteTextNode().
Referenced by System.Xml.XmlDictionaryWriter.WriteArrayNode(), System.Xml.XmlDictionaryWriter.WriteArrayNode(), and System.Xml.XmlDictionaryWriter.WriteNode().