Terraria: System.Xml.XmlDictionaryWriter.WriteValue
WriteValue() [20/20]
virtual void System.Xml.XmlDictionaryWriter.WriteValue (XmlDictionaryString? value) inline virtual inherited
Definition at line 414 of file XmlDictionaryWriter.cs.
    {
        WriteValue(XmlDictionaryString.GetString(value));
    }
References System.Xml.XmlDictionaryString.GetString(), System.value, and System.Xml.XmlDictionaryWriter.WriteValue().
Referenced by System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteValue(), System.Xml.XmlDictionaryWriter.WriteValue(), and System.Xml.XmlDictionaryWriter.WriteValueAsync().