Terraria: System.Xml.XmlDictionaryWriter.WriteString
WriteString() [4/4]
virtual void System.Xml.XmlDictionaryWriter.WriteString (XmlDictionaryString? value) inline virtual inherited
Definition at line 396 of file XmlDictionaryWriter.cs.
    {
        WriteString(XmlDictionaryString.GetString(value));
    }
References System.Xml.XmlDictionaryString.GetString(), System.value, and System.Xml.XmlDictionaryWriter.WriteString().
Referenced by System.Xml.XmlDictionaryWriter.WriteAttributeString(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeStringValue(), System.Xml.XmlDictionaryWriter.WriteElementString(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteString(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteString(), System.Xml.XmlDictionaryWriter.WriteString(), System.Xml.XmlDictionaryWriter.WriteTextNode(), System.Xml.XmlDictionaryWriter.WriteValue(), System.Xml.XmlDictionaryWriter.WriteValue(), and System.Xml.XmlDictionaryWriter.WriteValue().