Terraria: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberInfo
GetMemberInfo()
MemberInfo System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberInfo (string name) inline package
Definition at line 162 of file ReadObjectInfo.cs.
    {
        if (_cache == null)
        {
            return null;
        }
        if (_isSi)
        {
            throw new SerializationException(System.SR.Format(System.SR.Serialization_MemberInfo, _objectType?.ToString() + " " + name));
        }
        if (_cache._memberInfos == null)
        {
            throw new SerializationException(System.SR.Format(System.SR.Serialization_NoMemberInfo, _objectType?.ToString() + " " + name));
        }
        int num = Position(name);
        if (num == -1)
        {
            return null;
        }
        return _cache._memberInfos[num];
    }
References System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo._cache, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo._isSi, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache._memberInfos, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo._objectType, System.SR.Format(), System.SR.Serialization_MemberInfo, System.SR.Serialization_NoMemberInfo, and System.Type.ToString().
Referenced by System.Runtime.Serialization.Formatters.Binary.ValueFixup.Fixup().