Terraria: System.Xml.XmlDictionaryWriter.WriteArray
WriteArray() [1/20]
virtual void System.Xml.XmlDictionaryWriter.WriteArray (string? prefix, string localName, string? namespaceUri, bool[] array, int offset, int count) inline virtual inherited
Definition at line 758 of file XmlDictionaryWriter.cs.
    {
        CheckArray(array, offset, count);
        for (int i = 0; i < count; i++)
        {
            WriteStartElement(prefix, localName, namespaceUri);
            WriteValue(array[offset + i]);
            WriteEndElement();
        }
    }
References System.array, System.Xml.XmlDictionaryWriter.CheckArray(), System.count, System.offset, System.prefix, System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlDictionaryWriter.WriteStartElement(), and System.Xml.XmlDictionaryWriter.WriteValue().
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Runtime.Serialization.XmlWriterDelegator.WriteBooleanArray(), System.Runtime.Serialization.XmlWriterDelegator.WriteDateTimeArray(), System.Runtime.Serialization.XmlWriterDelegator.WriteDecimalArray(), System.Runtime.Serialization.XmlWriterDelegator.WriteDoubleArray(), System.Runtime.Serialization.XmlWriterDelegator.WriteInt32Array(), System.Runtime.Serialization.XmlWriterDelegator.WriteInt64Array(), and System.Runtime.Serialization.XmlWriterDelegator.WriteSingleArray().