Terraria: System.Xml.XmlDictionaryWriter.WriteXmlnsAttribute
WriteXmlnsAttribute() [3/4]
virtual void System.Xml.XmlDictionaryWriter.WriteXmlnsAttribute (string? prefix, string namespaceUri) inline virtual inherited
Definition at line 345 of file XmlDictionaryWriter.cs.
    {
        if (namespaceUri == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("namespaceUri");
        }
        if (prefix == null)
        {
            if (LookupPrefix(namespaceUri) != null)
            {
                return;
            }
            prefix = ((namespaceUri.Length == 0) ? string.Empty : $"d{namespaceUri.Length}");
        }
        WriteAttributeString("xmlns", prefix, null, namespaceUri);
    }
References System.Xml.Dictionary, System.Xml.XmlWriter.LookupPrefix(), System.prefix, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), and System.Xml.XmlDictionaryWriter.WriteAttributeString().
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteXmlnsAttribute(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteXmlnsAttribute(), System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute(), System.Xml.XmlDictionaryWriter.WriteXmlnsAttribute(), and System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute().