Terraria: System.Xml.XmlDictionaryWriter.WriteArrayNode
WriteArrayNode() [1/3]
void System.Xml.XmlDictionaryWriter.WriteArrayNode (XmlDictionaryReader reader, string prefix, string localName, string namespaceUri, Type type) inline private inherited
Definition at line 529 of file XmlDictionaryWriter.cs.
    {
        if (type == typeof(bool))
        {
            BooleanArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(short))
        {
            Int16ArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(int))
        {
            Int32ArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(long))
        {
            Int64ArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(float))
        {
            SingleArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(double))
        {
            DoubleArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(decimal))
        {
            DecimalArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(DateTime))
        {
            DateTimeArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(Guid))
        {
            GuidArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        if (type == typeof(TimeSpan))
        {
            TimeSpanArrayHelperWithString.Instance.WriteArray(this, prefix, localName, namespaceUri, reader);
            return;
        }
        WriteElementNode(reader, defattr: false);
        reader.Read();
    }
References System.Xml.Dictionary, System.Xml.BooleanArrayHelperWithString.Instance, System.Xml.DateTimeArrayHelperWithString.Instance, System.Xml.DecimalArrayHelperWithString.Instance, System.Xml.DoubleArrayHelperWithString.Instance, System.Xml.GuidArrayHelperWithString.Instance, System.Xml.Int16ArrayHelperWithString.Instance, System.Xml.Int32ArrayHelperWithString.Instance, System.Xml.Int64ArrayHelperWithString.Instance, System.Xml.SingleArrayHelperWithString.Instance, System.Xml.TimeSpanArrayHelperWithString.Instance, System.prefix, System.Xml.XmlReader.Read(), System.type, and System.Xml.XmlDictionaryWriter.WriteElementNode().
Referenced by System.Xml.XmlDictionaryWriter.WriteArrayNode(), and System.Xml.XmlDictionaryWriter.WriteNode().