Terraria: System.Xml.XmlDictionaryWriter.WriteStartElement
WriteStartElement() [7/7]
void System.Xml.XmlDictionaryWriter.WriteStartElement (XmlDictionaryString localName, XmlDictionaryString? namespaceUri) inline inherited
Definition at line 320 of file XmlDictionaryWriter.cs.
    {
        WriteStartElement(null, localName, namespaceUri);
    }
References System.Xml.XmlDictionaryWriter.WriteStartElement().
Referenced by System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteElementNode(), System.Xml.XmlDictionaryWriter.WriteElementString(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStartElement(), System.Runtime.Serialization.XmlWriterDelegator.WriteStartElement(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStartElement(), System.Xml.XmlDictionaryWriter.WriteStartElement(), System.Xml.XmlDictionaryWriter.WriteStartElement(), and System.Runtime.Serialization.XmlWriterDelegator.WriteStartElementPrimitive().