Terraria: System.Xml.XmlDictionaryWriter.WriteTextNode
WriteTextNode()
virtual void System.Xml.XmlDictionaryWriter.WriteTextNode (XmlDictionaryReader reader, bool isAttribute) inline protected virtual inherited
Reimplemented in System.Xml.XmlBinaryWriter.
Definition at line 653 of file XmlDictionaryWriter.cs.
    {
        if (reader.TryGetValueAsDictionaryString(out XmlDictionaryString value))
        {
            WriteString(value);
        }
        else
        {
            WriteString(reader.Value);
        }
        if (!isAttribute)
        {
            reader.Read();
        }
    }
References System.Xml.Dictionary, System.Xml.XmlReader.Read(), System.Xml.XmlDictionaryReader.TryGetValueAsDictionaryString(), System.value, System.Xml.XmlReader.Value, and System.Xml.XmlDictionaryWriter.WriteString().
Referenced by System.Xml.XmlDictionaryWriter.WriteElementNode(), and System.Xml.XmlDictionaryWriter.WriteNode().