Terraria: System.Linq.Parallel.CancellationState.ThrowWithStandardMessageIfCanceled
ThrowWithStandardMessageIfCanceled()
static void System.Linq.Parallel.CancellationState.ThrowWithStandardMessageIfCanceled (CancellationToken externalCancellationToken) inline static package
Definition at line 33 of file CancellationState.cs.
    {
        if (externalCancellationToken.IsCancellationRequested)
        {
            string pLINQ_ExternalCancellationRequested = System.SR.PLINQ_ExternalCancellationRequested;
            throw new OperationCanceledException(pLINQ_ExternalCancellationRequested, externalCancellationToken);
        }
    }
References System.Threading.CancellationToken.IsCancellationRequested, and System.SR.PLINQ_ExternalCancellationRequested.
Referenced by System.Linq.Parallel.QueryOpeningEnumerator< TOutput >.MoveNext(), System.Linq.Parallel.QueryOpeningEnumerator< TOutput >.OpenQuery(), and System.Linq.Parallel.ExceptionAggregator.ThrowOCEorAggregateException().