Terraria: UICreativePowersMenu.TimeCategoryButtonClick
TimeCategoryButtonClick()
void UICreativePowersMenu.TimeCategoryButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         GroupOptionButton<int> groupOptionButton = listeningElement as GroupOptionButton<int>;
         int optionValue = groupOptionButton.OptionValue;
         if (optionValue != 1 || CreativePowerManager.Instance.GetPower<CreativePowers.ModifyTimeRate>().GetIsUnlocked())
         {
             ToggleTimeCategory(groupOptionButton.OptionValue);
             RefreshElementsOrder();
         }
     }
References CreativePowers.ModifyTimeRate.GetIsUnlocked(), CreativePowerManager.Instance, GroupOptionButton< T >.OptionValue, RefreshElementsOrder(), and ToggleTimeCategory().
Referenced by CreateTimePowerStrip().