Terraria: System.Text.Json.ThrowHelper.ReThrowWithPath
ReThrowWithPath() [2/3]
static void System.Text.Json.ThrowHelper.ReThrowWithPath (ref ReadStack state, JsonReaderException ex) inline static
Definition at line 904 of file ThrowHelper.cs.
    {
        string text = state.JsonPath();
        string message = ex.Message;
        int num = message.AsSpan().LastIndexOf(" LineNumber: ");
        message = ((num < 0) ? (message + " Path: " + text + ".") : $"{message.Substring(0, num)} Path: {text} |{message.Substring(num)}");
        throw new JsonException(message, text, ex.LineNumber, ex.BytePositionInLine, ex);
    }
References System.Text.Json.Dictionary, System.state, and System.text.
Referenced by System.Text.Json.JsonSerializer.Read< TValue >(), System.Text.Json.Serialization.JsonConverter< T >.ReadCore(), and System.Text.Json.Serialization.JsonConverter< T >.WriteCore().