Terraria: System.Text.Json.ThrowHelper.NotSupportedException_NodeCollectionIsReadOnly
NotSupportedException_NodeCollectionIsReadOnly()
static NotSupportedException System.Text.Json.ThrowHelper.NotSupportedException_NodeCollectionIsReadOnly () inline static
Definition at line 656 of file ThrowHelper.cs.
    {
        return new NotSupportedException(System.SR.NodeCollectionIsReadOnly);
    }
References System.SR.NodeCollectionIsReadOnly.
Referenced by System.Text.Json.JsonPropertyDictionary< T >.KeyCollection.Add(), System.Text.Json.JsonPropertyDictionary< T >.ValueCollection.Add(), System.Text.Json.JsonPropertyDictionary< T >.KeyCollection.Clear(), System.Text.Json.JsonPropertyDictionary< T >.ValueCollection.Clear(), System.Text.Json.JsonPropertyDictionary< T >.KeyCollection.Remove(), System.Text.Json.JsonPropertyDictionary< T >.ValueCollection.Remove(), and System.Text.Json.ThrowHelper.ThrowNotSupportedException_NodeCollectionIsReadOnly().