Terraria: System.Text.Json.ThrowHelper.GetInvalidOperationException
GetInvalidOperationException() [3/5]
static InvalidOperationException System.Text.Json.ThrowHelper.GetInvalidOperationException (string message) inline static private
Definition at line 151 of file ThrowHelper.cs.
    {
        InvalidOperationException ex = new InvalidOperationException(message);
        ex.Source = "System.Text.Json.Rethrowable";
        return ex;
    }
References System.Text.Json.Dictionary.
Referenced by System.Text.Json.ThrowHelper.GetInvalidOperationException(), System.Text.Json.ThrowHelper.GetInvalidOperationException(), System.Text.Json.ThrowHelper.GetInvalidOperationException(), System.Text.Json.ThrowHelper.GetInvalidOperationException_CannotSkipOnPartial(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedArray(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedBoolean(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedChar(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedComment(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedNumber(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedObject(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedString(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedStringComparison(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ReadInvalidUTF8(), System.Text.Json.ThrowHelper.GetJsonElementWrongTypeException(), System.Text.Json.ThrowHelper.GetJsonElementWrongTypeException(), System.Text.Json.ThrowHelper.ThrowInvalidOperationException(), System.Text.Json.ThrowHelper.ThrowInvalidOperationException(), System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NeedLargerSpan(), System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ReadInvalidUTF16(), and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ReadInvalidUTF16().