Terraria: System.Text.Json.ThrowHelper.ThrowJsonException
ThrowJsonException()
static void System.Text.Json.ThrowHelper.ThrowJsonException (string message = null) inline static
Definition at line 752 of file ThrowHelper.cs.
    {
        throw new JsonException(message)
        {
            AppendPathInformation = true
        };
    }
Referenced by System.Text.Json.Serialization.Converters.KeyValuePairConverter< TKey, TValue >.EndRead(), System.Text.Json.Serialization.Converters.EnumConverter< T >.Read(), System.Text.Json.Serialization.Converters.UriConverter.Read(), System.Text.Json.Serialization.Converters.VersionConverter.Read(), System.Text.Json.Serialization.Converters.EnumConverter< T >.ReadAsPropertyNameCore(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataCannotParsePreservedObjectIntoImmutable(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataDuplicateIdFound(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataIdIsNotFirstProperty(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataInvalidPropertyWithLeadingDollarSign(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataInvalidReferenceToValueType(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataMissingIdBeforeValues(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataPreservedArrayInvalidProperty(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataPreservedArrayValuesNotFound(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataReferenceNotFound(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataReferenceObjectCannotContainOtherProperties(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataValuesInvalidToken(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataValueWasNotString(), System.Text.Json.ThrowHelper.ThrowJsonException_MetadataValueWasNotString(), System.Text.Json.Serialization.Converters.KeyValuePairConverter< TKey, TValue >.TryLookupConstructorParameter(), System.Text.Json.Serialization.Converters.EnumConverter< T >.Write(), and System.Text.Json.Serialization.Converters.EnumConverter< T >.WriteAsPropertyNameCore().