Terraria: System.Text.Json.ThrowHelper.GetFormatException
GetFormatException() [1/3]
static FormatException System.Text.Json.ThrowHelper.GetFormatException () inline static
Definition at line 520 of file ThrowHelper.cs.
    {
        FormatException ex = new FormatException();
        ex.Source = "System.Text.Json.Rethrowable";
        return ex;
    }
References System.Text.Json.Dictionary.
Referenced by System.Text.Json.Utf8JsonReader.GetByte(), System.Text.Json.JsonElement.GetBytesFromBase64(), System.Text.Json.Utf8JsonReader.GetBytesFromBase64(), System.Text.Json.Utf8JsonReader.GetByteWithQuotes(), System.Text.Json.JsonElement.GetDateTime(), System.Text.Json.Utf8JsonReader.GetDateTime(), System.Text.Json.Utf8JsonReader.GetDateTimeNoValidation(), System.Text.Json.JsonElement.GetDateTimeOffset(), System.Text.Json.Utf8JsonReader.GetDateTimeOffset(), System.Text.Json.Utf8JsonReader.GetDateTimeOffsetNoValidation(), System.Text.Json.JsonElement.GetDecimal(), System.Text.Json.Utf8JsonReader.GetDecimal(), System.Text.Json.Utf8JsonReader.GetDecimalWithQuotes(), System.Text.Json.JsonElement.GetDouble(), System.Text.Json.Utf8JsonReader.GetDouble(), System.Text.Json.Utf8JsonReader.GetDoubleFloatingPointConstant(), System.Text.Json.Utf8JsonReader.GetDoubleWithQuotes(), System.Text.Json.JsonElement.GetGuid(), System.Text.Json.Utf8JsonReader.GetGuid(), System.Text.Json.Utf8JsonReader.GetGuidNoValidation(), System.Text.Json.Utf8JsonReader.GetInt16(), System.Text.Json.Utf8JsonReader.GetInt16WithQuotes(), System.Text.Json.JsonElement.GetInt32(), System.Text.Json.Utf8JsonReader.GetInt32(), System.Text.Json.Utf8JsonReader.GetInt32WithQuotes(), System.Text.Json.JsonElement.GetInt64(), System.Text.Json.Utf8JsonReader.GetInt64(), System.Text.Json.Utf8JsonReader.GetInt64WithQuotes(), System.Text.Json.Utf8JsonReader.GetSByte(), System.Text.Json.Utf8JsonReader.GetSByteWithQuotes(), System.Text.Json.JsonElement.GetSingle(), System.Text.Json.Utf8JsonReader.GetSingle(), System.Text.Json.Utf8JsonReader.GetSingleFloatingPointConstant(), System.Text.Json.Utf8JsonReader.GetSingleWithQuotes(), System.Text.Json.Utf8JsonReader.GetUInt16(), System.Text.Json.Utf8JsonReader.GetUInt16WithQuotes(), System.Text.Json.JsonElement.GetUInt32(), System.Text.Json.Utf8JsonReader.GetUInt32(), System.Text.Json.Utf8JsonReader.GetUInt32WithQuotes(), System.Text.Json.JsonElement.GetUInt64(), System.Text.Json.Utf8JsonReader.GetUInt64(), System.Text.Json.Utf8JsonReader.GetUInt64WithQuotes(), System.Text.Json.Serialization.Converters.TimeSpanConverter.Read(), and System.Text.Json.Serialization.Converters.BooleanConverter.ReadAsPropertyNameCore().