Terraria: UICreativePowersMenu.WeatherCategoryButtonClick
WeatherCategoryButtonClick()
void UICreativePowersMenu.WeatherCategoryButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         GroupOptionButton<int> groupOptionButton = listeningElement as GroupOptionButton<int>;
         switch (groupOptionButton.OptionValue)
         {
         case 2:
             if (!CreativePowerManager.Instance.GetPower<CreativePowers.ModifyRainPower>().GetIsUnlocked())
             {
                 return;
             }
             break;
         case 1:
             if (!CreativePowerManager.Instance.GetPower<CreativePowers.ModifyWindDirectionAndStrength>().GetIsUnlocked())
             {
                 return;
             }
             break;
         }
         ToggleWeatherCategory(groupOptionButton.OptionValue);
         RefreshElementsOrder();
     }
References CreativePowers.ModifyWindDirectionAndStrength.GetIsUnlocked(), CreativePowers.ModifyRainPower.GetIsUnlocked(), CreativePowerManager.Instance, GroupOptionButton< T >.OptionValue, RefreshElementsOrder(), and ToggleWeatherCategory().
Referenced by CreateWeatherPowerStrip().