Terraria: System.Text.Json.ThrowHelper.GetResourceString
GetResourceString() [2/2]
static string System.Text.Json.ThrowHelper.GetResourceString (ref Utf8JsonReader json, ExceptionResource resource, byte nextByte, string characters) inline static private
Definition at line 286 of file ThrowHelper.cs.
    {
        string printableString = GetPrintableString(nextByte);
        string result = "";
        switch (resource)
        {
        case ExceptionResource.ArrayDepthTooLarge:
            result = System.SR.Format(System.SR.ArrayDepthTooLarge, json.CurrentState.Options.MaxDepth);
            break;
        case ExceptionResource.MismatchedObjectArray:
            result = System.SR.Format(System.SR.MismatchedObjectArray, printableString);
            break;
        case ExceptionResource.TrailingCommaNotAllowedBeforeArrayEnd:
            result = System.SR.TrailingCommaNotAllowedBeforeArrayEnd;
            break;
        case ExceptionResource.TrailingCommaNotAllowedBeforeObjectEnd:
            result = System.SR.TrailingCommaNotAllowedBeforeObjectEnd;
            break;
        case ExceptionResource.EndOfStringNotFound:
            result = System.SR.EndOfStringNotFound;
            break;
        case ExceptionResource.RequiredDigitNotFoundAfterSign:
            result = System.SR.Format(System.SR.RequiredDigitNotFoundAfterSign, printableString);
            break;
        case ExceptionResource.RequiredDigitNotFoundAfterDecimal:
            result = System.SR.Format(System.SR.RequiredDigitNotFoundAfterDecimal, printableString);
            break;
        case ExceptionResource.RequiredDigitNotFoundEndOfData:
            result = System.SR.RequiredDigitNotFoundEndOfData;
            break;
        case ExceptionResource.ExpectedEndAfterSingleJson:
            result = System.SR.Format(System.SR.ExpectedEndAfterSingleJson, printableString);
            break;
        case ExceptionResource.ExpectedEndOfDigitNotFound:
            result = System.SR.Format(System.SR.ExpectedEndOfDigitNotFound, printableString);
            break;
        case ExceptionResource.ExpectedNextDigitEValueNotFound:
            result = System.SR.Format(System.SR.ExpectedNextDigitEValueNotFound, printableString);
            break;
        case ExceptionResource.ExpectedSeparatorAfterPropertyNameNotFound:
            result = System.SR.Format(System.SR.ExpectedSeparatorAfterPropertyNameNotFound, printableString);
            break;
        case ExceptionResource.ExpectedStartOfPropertyNotFound:
            result = System.SR.Format(System.SR.ExpectedStartOfPropertyNotFound, printableString);
            break;
        case ExceptionResource.ExpectedStartOfPropertyOrValueNotFound:
            result = System.SR.ExpectedStartOfPropertyOrValueNotFound;
            break;
        case ExceptionResource.ExpectedStartOfPropertyOrValueAfterComment:
            result = System.SR.Format(System.SR.ExpectedStartOfPropertyOrValueAfterComment, printableString);
            break;
        case ExceptionResource.ExpectedStartOfValueNotFound:
            result = System.SR.Format(System.SR.ExpectedStartOfValueNotFound, printableString);
            break;
        case ExceptionResource.ExpectedValueAfterPropertyNameNotFound:
            result = System.SR.ExpectedValueAfterPropertyNameNotFound;
            break;
        case ExceptionResource.FoundInvalidCharacter:
            result = System.SR.Format(System.SR.FoundInvalidCharacter, printableString);
            break;
        case ExceptionResource.InvalidEndOfJsonNonPrimitive:
            result = System.SR.Format(System.SR.InvalidEndOfJsonNonPrimitive, json.TokenType);
            break;
        case ExceptionResource.ObjectDepthTooLarge:
            result = System.SR.Format(System.SR.ObjectDepthTooLarge, json.CurrentState.Options.MaxDepth);
            break;
        case ExceptionResource.ExpectedFalse:
            result = System.SR.Format(System.SR.ExpectedFalse, characters);
            break;
        case ExceptionResource.ExpectedNull:
            result = System.SR.Format(System.SR.ExpectedNull, characters);
            break;
        case ExceptionResource.ExpectedTrue:
            result = System.SR.Format(System.SR.ExpectedTrue, characters);
            break;
        case ExceptionResource.InvalidCharacterWithinString:
            result = System.SR.Format(System.SR.InvalidCharacterWithinString, printableString);
            break;
        case ExceptionResource.InvalidCharacterAfterEscapeWithinString:
            result = System.SR.Format(System.SR.InvalidCharacterAfterEscapeWithinString, printableString);
            break;
        case ExceptionResource.InvalidHexCharacterWithinString:
            result = System.SR.Format(System.SR.InvalidHexCharacterWithinString, printableString);
            break;
        case ExceptionResource.EndOfCommentNotFound:
            result = System.SR.EndOfCommentNotFound;
            break;
        case ExceptionResource.ZeroDepthAtEnd:
            result = System.SR.Format(System.SR.ZeroDepthAtEnd);
            break;
        case ExceptionResource.ExpectedJsonTokens:
            result = System.SR.ExpectedJsonTokens;
            break;
        case ExceptionResource.NotEnoughData:
            result = System.SR.NotEnoughData;
            break;
        case ExceptionResource.ExpectedOneCompleteToken:
            result = System.SR.ExpectedOneCompleteToken;
            break;
        case ExceptionResource.InvalidCharacterAtStartOfComment:
            result = System.SR.Format(System.SR.InvalidCharacterAtStartOfComment, printableString);
            break;
        case ExceptionResource.UnexpectedEndOfDataWhileReadingComment:
            result = System.SR.Format(System.SR.UnexpectedEndOfDataWhileReadingComment);
            break;
        case ExceptionResource.UnexpectedEndOfLineSeparator:
            result = System.SR.Format(System.SR.UnexpectedEndOfLineSeparator);
            break;
        case ExceptionResource.InvalidLeadingZeroInNumber:
            result = System.SR.Format(System.SR.InvalidLeadingZeroInNumber, printableString);
            break;
        }
        return result;
    }
References System.SR.ArrayDepthTooLarge, System.Text.Json.Dictionary, System.SR.EndOfCommentNotFound, System.SR.EndOfStringNotFound, System.SR.ExpectedEndAfterSingleJson, System.SR.ExpectedEndOfDigitNotFound, System.SR.ExpectedFalse, System.SR.ExpectedJsonTokens, System.SR.ExpectedNextDigitEValueNotFound, System.SR.ExpectedNull, System.SR.ExpectedOneCompleteToken, System.SR.ExpectedSeparatorAfterPropertyNameNotFound, System.SR.ExpectedStartOfPropertyNotFound, System.SR.ExpectedStartOfPropertyOrValueAfterComment, System.SR.ExpectedStartOfPropertyOrValueNotFound, System.SR.ExpectedStartOfValueNotFound, System.SR.ExpectedTrue, System.SR.ExpectedValueAfterPropertyNameNotFound, System.SR.Format(), System.SR.FoundInvalidCharacter, System.Text.Json.ThrowHelper.GetPrintableString(), System.SR.InvalidCharacterAfterEscapeWithinString, System.SR.InvalidCharacterAtStartOfComment, System.SR.InvalidCharacterWithinString, System.SR.InvalidEndOfJsonNonPrimitive, System.SR.InvalidHexCharacterWithinString, System.SR.InvalidLeadingZeroInNumber, System.SR.MismatchedObjectArray, System.SR.NotEnoughData, System.SR.ObjectDepthTooLarge, System.SR.RequiredDigitNotFoundAfterDecimal, System.SR.RequiredDigitNotFoundAfterSign, System.SR.RequiredDigitNotFoundEndOfData, System.SR.TrailingCommaNotAllowedBeforeArrayEnd, System.SR.TrailingCommaNotAllowedBeforeObjectEnd, System.SR.UnexpectedEndOfDataWhileReadingComment, System.SR.UnexpectedEndOfLineSeparator, and System.SR.ZeroDepthAtEnd.
Referenced by System.Text.Json.ThrowHelper.GetInvalidOperationException(), and System.Text.Json.ThrowHelper.GetJsonReaderException().