Terraria: System.Text.Json.ThrowHelper.ThrowJsonReaderException
ThrowJsonReaderException()
static void System.Text.Json.ThrowHelper.ThrowJsonReaderException (ref Utf8JsonReader json, ExceptionResource resource, byte nextByte = 0, ReadOnlySpan< byte > bytes = default(ReadOnlySpan<byte>)) inline static
Definition at line 250 of file ThrowHelper.cs.
    {
        throw GetJsonReaderException(ref json, resource, nextByte, bytes);
    }
References System.bytes, System.Text.Json.Dictionary, and System.Text.Json.ThrowHelper.GetJsonReaderException().
Referenced by System.Text.Json.Utf8JsonReader.ConsumeComment(), System.Text.Json.Utf8JsonReader.ConsumeDecimalDigits(), System.Text.Json.Utf8JsonReader.ConsumeDecimalDigitsMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNegativeSign(), System.Text.Json.Utf8JsonReader.ConsumeNegativeSignMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentToken(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenFromLastNonCommentTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(), System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkippedMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeNumber(), System.Text.Json.Utf8JsonReader.ConsumeNumberMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumePropertyName(), System.Text.Json.Utf8JsonReader.ConsumePropertyNameMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeSign(), System.Text.Json.Utf8JsonReader.ConsumeSignMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeString(), System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(), System.Text.Json.Utf8JsonReader.ConsumeStringAndValidateMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringNextSegment(), System.Text.Json.Utf8JsonReader.ConsumeValue(), System.Text.Json.Utf8JsonReader.ConsumeValueMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeZero(), System.Text.Json.Utf8JsonReader.ConsumeZeroMultiSegment(), System.Text.Json.Utf8JsonReader.EndArray(), System.Text.Json.Utf8JsonReader.EndObject(), System.Text.Json.Utf8JsonReader.HasMoreData(), System.Text.Json.Utf8JsonReader.HasMoreData(), System.Text.Json.Utf8JsonReader.HasMoreDataMultiSegment(), System.Text.Json.Utf8JsonReader.Read(), System.Text.Json.JsonSerializer.Read< TValue >(), System.Text.Json.Utf8JsonReader.ReadMultiSegment(), System.Text.Json.Utf8JsonReader.ReadSingleSegment(), System.Text.Json.Utf8JsonReader.SkipComment(), System.Text.Json.Utf8JsonReader.SkipCommentMultiSegment(), System.Text.Json.Utf8JsonReader.SkipMultiLineComment(), System.Text.Json.Utf8JsonReader.SkipMultiLineCommentMultiSegment(), System.Text.Json.Utf8JsonReader.StartArray(), System.Text.Json.Utf8JsonReader.StartObject(), System.Text.Json.Utf8JsonReader.ThrowInvalidLiteral(), System.Text.Json.Utf8JsonReader.ThrowOnDangerousLineSeparator(), System.Text.Json.Utf8JsonReader.ThrowOnDangerousLineSeparatorMultiSegment(), System.Text.Json.Utf8JsonReader.TryGetNumber(), System.Text.Json.Utf8JsonReader.TryGetNumberMultiSegment(), System.Text.Json.JsonDocument.TryParseValue(), System.Text.Json.Utf8JsonReader.ValidateHexDigits(), and System.Text.Json.Utf8JsonReader.ValidateStateAtEndOfData().