Terraria: System.Text.Json.ThrowHelper.ThrowArgumentException_InvalidUTF8
ThrowArgumentException_InvalidUTF8()
static void System.Text.Json.ThrowHelper.ThrowArgumentException_InvalidUTF8 (ReadOnlySpan< byte > value) inline static
Definition at line 414 of file ThrowHelper.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        int num = Math.Min(value.Length, 10);
        for (int i = 0; i < num; i++)
        {
            byte value2 = value[i];
            if (IsPrintable(value2))
            {
                stringBuilder.Append((char)value2);
                continue;
            }
            StringBuilder stringBuilder2 = stringBuilder;
            StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, stringBuilder2);
            handler.AppendLiteral("0x");
            handler.AppendFormatted(value2, "X2");
            stringBuilder2.Append(ref handler);
        }
        if (num < value.Length)
        {
            stringBuilder.Append("...");
        }
        throw new ArgumentException(System.SR.Format(System.SR.CannotEncodeInvalidUTF8, stringBuilder));
    }
References System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), System.SR.CannotEncodeInvalidUTF8, System.Text.Json.Dictionary, System.SR.Format(), System.Text.Json.ThrowHelper.IsPrintable(), System.Math.Min(), and System.value.
Referenced by System.Text.Json.JsonWriterHelper.EscapeString().