Terraria: System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ReadInvalidUTF16
ThrowInvalidOperationException_ReadInvalidUTF16() [2/2]
static void System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ReadInvalidUTF16 (int charAsInt) inline static
Definition at line 446 of file ThrowHelper.cs.
    {
        throw GetInvalidOperationException(System.SR.Format(System.SR.CannotReadInvalidUTF16, $"0x{charAsInt:X2}"));
    }
References System.SR.CannotReadInvalidUTF16, System.Text.Json.Dictionary, System.SR.Format(), and System.Text.Json.ThrowHelper.GetInvalidOperationException().
Referenced by System.Text.Json.JsonReaderHelper.Unescape().