Terraria: System.Text.Json.ThrowHelper.ThrowJsonException_MetadataPreservedArrayInvalidProperty
ThrowJsonException_MetadataPreservedArrayInvalidProperty()
static void System.Text.Json.ThrowHelper.ThrowJsonException_MetadataPreservedArrayInvalidProperty (ref ReadStack state, Type propertyType, in Utf8JsonReader reader) inline static
Definition at line 1154 of file ThrowHelper.cs.
    {
        ref ReadStackFrame current = ref state.Current;
        byte[] jsonPropertyName;
        if (!reader.HasValueSequence)
        {
            jsonPropertyName = reader.ValueSpan.ToArray();
        }
        else
        {
            ReadOnlySequence<byte> sequence = reader.ValueSequence;
            jsonPropertyName = BuffersExtensions.ToArray(in sequence);
        }
        current.JsonPropertyName = jsonPropertyName;
        string @string = reader.GetString();
        ThrowJsonException(System.SR.Format(System.SR.MetadataPreservedArrayFailed, System.SR.Format(System.SR.MetadataPreservedArrayInvalidProperty, @string), System.SR.Format(System.SR.DeserializeUnableToConvertValue, propertyType)));
    }
References System.SR.DeserializeUnableToConvertValue, System.Text.Json.Dictionary, System.SR.Format(), System.SR.MetadataPreservedArrayFailed, System.SR.MetadataPreservedArrayInvalidProperty, System.state, and System.Text.Json.ThrowHelper.ThrowJsonException().
Referenced by System.Text.Json.Serialization.JsonCollectionConverter< TCollection, TElement >.OnTryRead(), and System.Text.Json.JsonSerializer.ResolveMetadataForJsonArray< T >().