Terraria: UICreativePowersMenu.MainCategoryButtonClick
MainCategoryButtonClick()
void UICreativePowersMenu.MainCategoryButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         GroupOptionButton<int> groupOptionButton = listeningElement as GroupOptionButton<int>;
         ToggleMainCategory(groupOptionButton.OptionValue);
         RefreshElementsOrder();
     }
References GroupOptionButton< T >.OptionValue, RefreshElementsOrder(), and ToggleMainCategory().
Referenced by CreateMainPowerStrip().