Terraria: System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedNumber
GetInvalidOperationException_ExpectedNumber()
static InvalidOperationException System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedNumber (JsonTokenType tokenType) inline static
Definition at line 182 of file ThrowHelper.cs.
    {
        return GetInvalidOperationException("number", tokenType);
    }
References System.Text.Json.ThrowHelper.GetInvalidOperationException().
Referenced by System.Text.Json.Utf8JsonReader.TryGetByte(), System.Text.Json.Utf8JsonReader.TryGetDecimal(), System.Text.Json.Utf8JsonReader.TryGetDouble(), System.Text.Json.Utf8JsonReader.TryGetInt16(), System.Text.Json.Utf8JsonReader.TryGetInt32(), System.Text.Json.Utf8JsonReader.TryGetInt64(), System.Text.Json.Utf8JsonReader.TryGetSByte(), System.Text.Json.Utf8JsonReader.TryGetSingle(), System.Text.Json.Utf8JsonReader.TryGetUInt16(), System.Text.Json.Utf8JsonReader.TryGetUInt32(), and System.Text.Json.Utf8JsonReader.TryGetUInt64().