Terraria: System.Reflection.Metadata.Ecma335.ArrayShapeEncoder.Shape
Shape()
void System.Reflection.Metadata.Ecma335.ArrayShapeEncoder.Shape (int rank, ImmutableArray< int > sizes, ImmutableArray< int > lowerBounds) inline
Definition at line 14 of file ArrayShapeEncoder.cs.
    {
        if ((uint)(rank - 1) > 65534u)
        {
            Throw.ArgumentOutOfRange("rank");
        }
        if (sizes.IsDefault)
        {
            Throw.ArgumentNull("sizes");
        }
        Builder.WriteCompressedInteger(rank);
        if (sizes.Length > rank)
        {
            Throw.ArgumentOutOfRange("rank");
        }
        Builder.WriteCompressedInteger(sizes.Length);
        ImmutableArray<int>.Enumerator enumerator = sizes.GetEnumerator();
        while (enumerator.MoveNext())
        {
            int current = enumerator.Current;
            Builder.WriteCompressedInteger(current);
        }
        if (lowerBounds.IsDefault)
        {
            Builder.WriteCompressedInteger(rank);
            for (int i = 0; i < rank; i++)
            {
                Builder.WriteCompressedSignedInteger(0);
            }
            return;
        }
        if (lowerBounds.Length > rank)
        {
            Throw.ArgumentOutOfRange("rank");
        }
        Builder.WriteCompressedInteger(lowerBounds.Length);
        ImmutableArray<int>.Enumerator enumerator2 = lowerBounds.GetEnumerator();
        while (enumerator2.MoveNext())
        {
            int current2 = enumerator2.Current;
            Builder.WriteCompressedSignedInteger(current2);
        }
    }
References System.Reflection.Throw.ArgumentNull(), System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Metadata.Ecma335.ArrayShapeEncoder.Builder, System.Collections.Immutable.ImmutableArray< T >.Enumerator.Current, System.Collections.Immutable.ImmutableArray< T >.GetEnumerator(), System.Collections.Immutable.ImmutableArray< T >.IsDefault, System.Collections.Immutable.ImmutableArray< T >.Length, System.lowerBounds, System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger(), and System.Reflection.Metadata.BlobBuilder.WriteCompressedSignedInteger().