Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteEndElement
WriteEndElement()
void System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteEndElement () inline private
Definition at line 707 of file JsonFormatWriterGenerator.cs.
        {
            _ilg.Call(_xmlWriterArg, JsonFormatGeneratorStatics.WriteEndElementMethod);
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), and System.Runtime.Serialization.JsonFormatGeneratorStatics.WriteEndElementMethod.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers().