Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter
GenerateCollectionWriter()
JsonFormatCollectionWriterDelegate System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter (CollectionDataContract collectionContract) inline package
Definition at line 54 of file JsonFormatWriterGenerator.cs.
        {
            _ilg = new CodeGenerator();
            bool flag = collectionContract.RequiresMemberAccessForWrite(null);
            try
            {
                BeginMethod(_ilg, "Write" + DataContract.SanitizeTypeName(collectionContract.StableName.Name) + "ToJson", typeof(JsonFormatCollectionWriterDelegate), flag);
            }
            catch (SecurityException securityException)
            {
                if (!flag)
                {
                    throw;
                }
                collectionContract.RequiresMemberAccessForWrite(securityException);
            }
            InitArgs(collectionContract.UnderlyingType);
            if (collectionContract.IsReadOnlyContract)
            {
                ThrowIfCannotSerializeReadOnlyTypes(collectionContract);
            }
            WriteCollection(collectionContract);
            return (JsonFormatCollectionWriterDelegate)_ilg.EndMethod();
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.BeginMethod(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.DataContract.SanitizeTypeName(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.ThrowIfCannotSerializeReadOnlyTypes(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection().
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.GenerateCollectionWriter().