Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers
WriteMembers()
int System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers (ClassDataContract classContract, LocalBuilder extensionDataLocal, ClassDataContract derivedMostClassContract) inline private
Definition at line 197 of file JsonFormatWriterGenerator.cs.
        {
            int num = ((classContract.BaseContract != null) ? WriteMembers(classContract.BaseContract, extensionDataLocal, derivedMostClassContract) : 0);
            int count = classContract.Members.Count;
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.IncrementItemCountMethod, count);
            int num2 = 0;
            while (num2 < count)
            {
                DataMember dataMember = classContract.Members[num2];
                Type memberType = dataMember.MemberType;
                LocalBuilder localBuilder = null;
                _ilg.Load(_contextArg);
                _ilg.Call(dataMember.IsGetOnlyCollection ? XmlFormatGeneratorStatics.StoreIsGetOnlyCollectionMethod : XmlFormatGeneratorStatics.ResetIsGetOnlyCollectionMethod);
                if (!dataMember.EmitDefaultValue)
                {
                    localBuilder = LoadMemberValue(dataMember);
                    _ilg.IfNotDefaultValue(localBuilder);
                }
                bool flag = DataContractJsonSerializer.CheckIfXmlNameRequiresMapping(classContract.MemberNames[num2]);
                if (flag || !TryWritePrimitive(memberType, localBuilder, dataMember.MemberInfo, null, null, num2 + _childElementIndex))
                {
                    if (flag)
                    {
                        _ilg.Call(null, JsonFormatGeneratorStatics.WriteJsonNameWithMappingMethod, _xmlWriterArg, _memberNamesArg, num2 + _childElementIndex);
                    }
                    else
                    {
                        WriteStartElement(null, num2 + _childElementIndex);
                    }
                    if (localBuilder == null)
                    {
                        localBuilder = LoadMemberValue(dataMember);
                    }
                    WriteValue(localBuilder);
                    WriteEndElement();
                }
                if (classContract.HasExtensionData)
                {
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteExtensionDataMethod, _xmlWriterArg, extensionDataLocal, num);
                }
                if (!dataMember.EmitDefaultValue)
                {
                    if (dataMember.IsRequired)
                    {
                        _ilg.Else();
                        _ilg.Call(null, XmlFormatGeneratorStatics.ThrowRequiredMemberMustBeEmittedMethod, dataMember.Name, classContract.UnderlyingType);
                    }
                    _ilg.EndIf();
                }
                num2++;
                num++;
            }
            _typeIndex++;
            _childElementIndex += count;
            return num;
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._childElementIndex, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._typeIndex, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfXmlNameRequiresMapping(), System.count, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue(), System.Runtime.Serialization.XmlFormatGeneratorStatics.IncrementItemCountMethod, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.LoadMemberValue(), System.Type.MemberType, System.Runtime.Serialization.XmlFormatGeneratorStatics.ResetIsGetOnlyCollectionMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.StoreIsGetOnlyCollectionMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.ThrowRequiredMemberMustBeEmittedMethod, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteEndElement(), System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteExtensionDataMethod, System.Runtime.Serialization.JsonFormatGeneratorStatics.WriteJsonNameWithMappingMethod, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteStartElement(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue().
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers().