Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteStartElement
WriteStartElement()
void System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteStartElement (LocalBuilder nameLocal, int nameIndex) inline private
Definition at line 685 of file JsonFormatWriterGenerator.cs.
        {
            _ilg.Load(_xmlWriterArg);
            if (nameLocal == null)
            {
                _ilg.LoadArrayElement(_memberNamesArg, nameIndex);
            }
            else
            {
                _ilg.Load(nameLocal);
            }
            _ilg.Load(null);
            if (nameLocal != null && nameLocal.LocalType == typeof(string))
            {
                _ilg.Call(JsonFormatGeneratorStatics.WriteStartElementStringMethod);
            }
            else
            {
                _ilg.Call(JsonFormatGeneratorStatics.WriteStartElementMethod);
            }
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadArrayElement(), System.Runtime.Serialization.JsonFormatGeneratorStatics.WriteStartElementMethod, and System.Runtime.Serialization.JsonFormatGeneratorStatics.WriteStartElementStringMethod.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers().