Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject
UnwrapNullableObject()
LocalBuilder System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject (LocalBuilder memberValue) inline private
Definition at line 657 of file JsonFormatWriterGenerator.cs.
        {
            Type type = memberValue.LocalType;
            Label label = _ilg.DefineLabel();
            Label label2 = _ilg.DefineLabel();
            _ilg.LoadAddress(memberValue);
            while (type.IsGenericType && type.GetGenericTypeDefinition() == Globals.TypeOfNullable)
            {
                Type type2 = type.GetGenericArguments()[0];
                _ilg.Dup();
                _ilg.Call(typeof(Nullable<>).MakeGenericType(type2).GetMethod("get_HasValue"));
                _ilg.Brfalse(label);
                _ilg.Call(typeof(Nullable<>).MakeGenericType(type2).GetMethod("get_Value"));
                type = type2;
            }
            memberValue = _ilg.DeclareLocal(type, "nullableUnwrappedMemberValue");
            _ilg.Stloc(memberValue);
            _ilg.Load(false);
            _ilg.Br(label2);
            _ilg.MarkLabel(label);
            _ilg.Pop();
            _ilg.LoadAddress(memberValue);
            _ilg.InitObj(type);
            _ilg.Load(true);
            _ilg.MarkLabel(label2);
            return memberValue;
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.CodeGenerator.Br(), System.Runtime.Serialization.CodeGenerator.Brfalse(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.CodeGenerator.DefineLabel(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Dup(), System.Type.GetGenericArguments(), System.Runtime.Serialization.CodeGenerator.InitObj(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.Runtime.Serialization.CodeGenerator.Pop(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.type, and System.Runtime.Serialization.Globals.TypeOfNullable.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue().