Terraria: System.Linq.Expressions.Interpreter.NumericConvertInstruction.Checked.Convert
Convert()
override object System.Linq.Expressions.Interpreter.NumericConvertInstruction.Checked.Convert (object obj) inline protected
Definition at line 127 of file NumericConvertInstruction.cs.
        {
            return _from switch
            {
                TypeCode.Boolean => ConvertInt32(((bool)obj) ? 1 : 0),
                TypeCode.Byte => ConvertInt32((byte)obj),
                TypeCode.SByte => ConvertInt32((sbyte)obj),
                TypeCode.Int16 => ConvertInt32((short)obj),
                TypeCode.Char => ConvertInt32((char)obj),
                TypeCode.Int32 => ConvertInt32((int)obj),
                TypeCode.Int64 => ConvertInt64((long)obj),
                TypeCode.UInt16 => ConvertInt32((ushort)obj),
                TypeCode.UInt32 => ConvertInt64((uint)obj),
                TypeCode.UInt64 => ConvertUInt64((ulong)obj),
                TypeCode.Single => ConvertDouble((float)obj),
                TypeCode.Double => ConvertDouble((double)obj),
                _ => throw ContractUtils.Unreachable,
            };
        }
References System.Linq.Expressions.Interpreter.NumericConvertInstruction._from, System.Linq.Expressions.Interpreter.NumericConvertInstruction.Checked.ConvertDouble(), System.Linq.Expressions.Interpreter.NumericConvertInstruction.Checked.ConvertInt32(), System.Linq.Expressions.Interpreter.NumericConvertInstruction.Checked.ConvertInt64(), System.Linq.Expressions.Interpreter.NumericConvertInstruction.Checked.ConvertUInt64(), System.obj, and System.Dynamic.Utils.ContractUtils.Unreachable.