Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue
WriteValue()
void System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue (LocalBuilder memberValue) inline private
Definition at line 564 of file JsonFormatWriterGenerator.cs.
        {
            Type type = memberValue.LocalType;
            if (type.IsPointer)
            {
                _ilg.Load(memberValue);
                _ilg.Load(type);
                _ilg.Call(JsonFormatGeneratorStatics.BoxPointer);
                type = typeof(Pointer);
                memberValue = _ilg.DeclareLocal(type, "memberValueRefPointer");
                _ilg.Store(memberValue);
            }
            bool flag = type.IsGenericType && type.GetGenericTypeDefinition() == Globals.TypeOfNullable;
            if (type.IsValueType && !flag)
            {
                PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(type);
                if (primitiveDataContract != null)
                {
                    _ilg.Call(_xmlWriterArg, primitiveDataContract.XmlFormatContentWriterMethod, memberValue);
                }
                else
                {
                    InternalSerialize(XmlFormatGeneratorStatics.InternalSerializeMethod, memberValue, type, writeXsiType: false);
                }
                return;
            }
            if (flag)
            {
                memberValue = UnwrapNullableObject(memberValue);
                type = memberValue.LocalType;
            }
            else
            {
                _ilg.Load(memberValue);
                _ilg.Load(null);
                _ilg.Ceq();
            }
            _ilg.If();
            _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteNullMethod, _xmlWriterArg, type, DataContract.IsTypeSerializable(type));
            _ilg.Else();
            PrimitiveDataContract primitiveDataContract2 = PrimitiveDataContract.GetPrimitiveDataContract(type);
            if (primitiveDataContract2 != null && primitiveDataContract2.UnderlyingType != Globals.TypeOfObject)
            {
                if (flag)
                {
                    _ilg.Call(_xmlWriterArg, primitiveDataContract2.XmlFormatContentWriterMethod, memberValue);
                }
                else
                {
                    _ilg.Call(_contextArg, primitiveDataContract2.XmlFormatContentWriterMethod, _xmlWriterArg, memberValue);
                }
            }
            else
            {
                if (type == Globals.TypeOfObject || type == Globals.TypeOfValueType || ((IList)Globals.TypeOfNullable.GetInterfaces()).Contains((object?)type))
                {
                    _ilg.Load(memberValue);
                    _ilg.ConvertValue(memberValue.LocalType, Globals.TypeOfObject);
                    memberValue = _ilg.DeclareLocal(Globals.TypeOfObject, "unwrappedMemberValue");
                    type = memberValue.LocalType;
                    _ilg.Stloc(memberValue);
                    _ilg.If(memberValue, Cmp.EqualTo, null);
                    _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteNullMethod, _xmlWriterArg, type, DataContract.IsTypeSerializable(type));
                    _ilg.Else();
                }
                InternalSerialize(flag ? XmlFormatGeneratorStatics.InternalSerializeMethod : XmlFormatGeneratorStatics.InternalSerializeReferenceMethod, memberValue, type, writeXsiType: false);
                if (type == Globals.TypeOfObject)
                {
                    _ilg.EndIf();
                }
            }
            _ilg.EndIf();
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.JsonFormatGeneratorStatics.BoxPointer, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Ceq(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.XmlFormatGeneratorStatics.InternalSerializeMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.InternalSerializeReferenceMethod, System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.Runtime.Serialization.CodeGenerator.Load(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.CodeGenerator.Store(), System.type, System.Runtime.Serialization.Globals.TypeOfNullable, System.Runtime.Serialization.Globals.TypeOfObject, System.Runtime.Serialization.Globals.TypeOfValueType, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), and System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteNullMethod.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers().