Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs
InitArgs()
void System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs (Type objType) inline private
Definition at line 93 of file JsonFormatWriterGenerator.cs.
        {
            _xmlWriterArg = _ilg.GetArg(0);
            _contextArg = _ilg.GetArg(2);
            _dataContractArg = _ilg.GetArg(3);
            _objectLocal = _ilg.DeclareLocal(objType, "objSerialized");
            ArgBuilder arg = _ilg.GetArg(1);
            _ilg.Load(arg);
            if (objType == Globals.TypeOfDateTimeOffsetAdapter)
            {
                _ilg.ConvertValue(arg.ArgType, Globals.TypeOfDateTimeOffset);
                _ilg.Call(XmlFormatGeneratorStatics.GetDateTimeOffsetAdapterMethod);
            }
            else if (objType == Globals.TypeOfMemoryStreamAdapter)
            {
                _ilg.ConvertValue(arg.ArgType, Globals.TypeOfMemoryStream);
                _ilg.Call(XmlFormatGeneratorStatics.GetMemoryStreamAdapterMethod);
            }
            else if (objType.IsGenericType && objType.GetGenericTypeDefinition() == Globals.TypeOfKeyValuePairAdapter)
            {
                ClassDataContract classDataContract = (ClassDataContract)DataContract.GetDataContract(objType);
                _ilg.ConvertValue(arg.ArgType, Globals.TypeOfKeyValuePair.MakeGenericType(classDataContract.KeyValuePairGenericArguments));
                _ilg.New(classDataContract.KeyValuePairAdapterConstructorInfo);
            }
            else
            {
                _ilg.ConvertValue(arg.ArgType, objType);
            }
            _ilg.Stloc(_objectLocal);
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._dataContractArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.GetArg(), System.Runtime.Serialization.DataContract.GetDataContract(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetDateTimeOffsetAdapterMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetMemoryStreamAdapterMethod, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.New(), System.Runtime.Serialization.CodeGenerator.Stloc(), System.Runtime.Serialization.Globals.TypeOfDateTimeOffset, System.Runtime.Serialization.Globals.TypeOfDateTimeOffsetAdapter, System.Runtime.Serialization.Globals.TypeOfKeyValuePair, System.Runtime.Serialization.Globals.TypeOfKeyValuePairAdapter, System.Runtime.Serialization.Globals.TypeOfMemoryStream, and System.Runtime.Serialization.Globals.TypeOfMemoryStreamAdapter.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateClassWriter(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter().