Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass
WriteClass()
void System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass (ClassDataContract classContract) inline private
Definition at line 172 of file JsonFormatWriterGenerator.cs.
        {
            InvokeOnSerializing(classContract);
            if (classContract.IsISerializable)
            {
                _ilg.Call(_contextArg, JsonFormatGeneratorStatics.WriteJsonISerializableMethod, _xmlWriterArg, _objectLocal);
            }
            else if (classContract.HasExtensionData)
            {
                LocalBuilder localBuilder = _ilg.DeclareLocal(Globals.TypeOfExtensionDataObject, "extensionData");
                _ilg.Load(_objectLocal);
                _ilg.ConvertValue(_objectLocal.LocalType, Globals.TypeOfIExtensibleDataObject);
                _ilg.LoadMember(JsonFormatGeneratorStatics.ExtensionDataProperty);
                _ilg.Store(localBuilder);
                _ilg.Call(_contextArg, XmlFormatGeneratorStatics.WriteExtensionDataMethod, _xmlWriterArg, localBuilder, -1);
                WriteMembers(classContract, localBuilder, classContract);
            }
            else
            {
                WriteMembers(classContract, null, classContract);
            }
            InvokeOnSerialized(classContract);
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.JsonFormatGeneratorStatics.ExtensionDataProperty, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InvokeOnSerialized(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InvokeOnSerializing(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Reflection.Emit.LocalBuilder.LocalType, System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.Globals.TypeOfExtensionDataObject, System.Runtime.Serialization.Globals.TypeOfIExtensibleDataObject, System.Runtime.Serialization.XmlFormatGeneratorStatics.WriteExtensionDataMethod, System.Runtime.Serialization.JsonFormatGeneratorStatics.WriteJsonISerializableMethod, and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers().
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateClassWriter().