Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateClassWriter
GenerateClassWriter()
JsonFormatClassWriterDelegate System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateClassWriter (ClassDataContract classContract) inline package
Definition at line 31 of file JsonFormatWriterGenerator.cs.
        {
            _ilg = new CodeGenerator();
            bool flag = classContract.RequiresMemberAccessForWrite(null);
            try
            {
                BeginMethod(_ilg, "Write" + DataContract.SanitizeTypeName(classContract.StableName.Name) + "ToJson", typeof(JsonFormatClassWriterDelegate), flag);
            }
            catch (SecurityException securityException)
            {
                if (!flag)
                {
                    throw;
                }
                classContract.RequiresMemberAccessForWrite(securityException);
            }
            InitArgs(classContract.UnderlyingType);
            _memberNamesArg = _ilg.GetArg(4);
            WriteClass(classContract);
            return (JsonFormatClassWriterDelegate)_ilg.EndMethod();
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._memberNamesArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.BeginMethod(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.CodeGenerator.GetArg(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.DataContract.SanitizeTypeName(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass().
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.GenerateClassWriter().