Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray
TryWritePrimitiveArray()
bool System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray (Type type, Type itemType, LocalBuilder value, LocalBuilder itemName) inline private
Definition at line 506 of file JsonFormatWriterGenerator.cs.
        {
            PrimitiveDataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(itemType);
            if (primitiveDataContract == null)
            {
                return false;
            }
            string text = null;
            switch (Type.GetTypeCode(itemType))
            {
            case TypeCode.Boolean:
                text = "WriteJsonBooleanArray";
                break;
            case TypeCode.DateTime:
                text = "WriteJsonDateTimeArray";
                break;
            case TypeCode.Decimal:
                text = "WriteJsonDecimalArray";
                break;
            case TypeCode.Int32:
                text = "WriteJsonInt32Array";
                break;
            case TypeCode.Int64:
                text = "WriteJsonInt64Array";
                break;
            case TypeCode.Single:
                text = "WriteJsonSingleArray";
                break;
            case TypeCode.Double:
                text = "WriteJsonDoubleArray";
                break;
            }
            if (text != null)
            {
                WriteArrayAttribute();
                MethodInfo method = typeof(JsonWriterDelegator).GetMethod(text, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[3]
                {
                    type,
                    typeof(XmlDictionaryString),
                    typeof(XmlDictionaryString)
                });
                _ilg.Call(_xmlWriterArg, method, value, itemName, null);
                return true;
            }
            return false;
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Type.GetTypeCode(), System.text, System.value, and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteArrayAttribute().
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection().