Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.LoadMemberValue
LoadMemberValue()
LocalBuilder System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.LoadMemberValue (DataMember member) inline private
Definition at line 254 of file JsonFormatWriterGenerator.cs.
        {
            _ilg.LoadAddress(_objectLocal);
            _ilg.LoadMember(member.MemberInfo);
            LocalBuilder localBuilder = _ilg.DeclareLocal(member.MemberType, member.Name + "Value");
            _ilg.Stloc(localBuilder);
            return localBuilder;
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._objectLocal, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Runtime.Serialization.DataMember.MemberInfo, System.Runtime.Serialization.DataMember.MemberType, System.Runtime.Serialization.DataMember.Name, and System.Runtime.Serialization.CodeGenerator.Stloc().
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers().