Terraria: System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize
InternalSerialize()
void System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize (MethodInfo methodInfo, LocalBuilder memberValue, Type memberType, bool writeXsiType) inline private
Definition at line 638 of file JsonFormatWriterGenerator.cs.
        {
            _ilg.Load(_contextArg);
            _ilg.Load(_xmlWriterArg);
            _ilg.Load(memberValue);
            _ilg.ConvertValue(memberValue.LocalType, Globals.TypeOfObject);
            LocalBuilder localBuilder = _ilg.DeclareLocal(typeof(RuntimeTypeHandle), "typeHandleValue");
            _ilg.Call(memberValue, XmlFormatGeneratorStatics.GetTypeMethod);
            _ilg.Call(XmlFormatGeneratorStatics.GetTypeHandleMethod);
            _ilg.Stloc(localBuilder);
            _ilg.LoadAddress(localBuilder);
            _ilg.Ldtoken(memberType);
            _ilg.Call(typeof(RuntimeTypeHandle).GetMethod("Equals", new Type[1] { typeof(RuntimeTypeHandle) }));
            _ilg.Load(writeXsiType);
            _ilg.Load(DataContract.GetId(memberType.TypeHandle));
            _ilg.Ldtoken(memberType);
            _ilg.Call(methodInfo);
        }
References System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._contextArg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._ilg, System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper._xmlWriterArg, System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetId(), System.Runtime.Serialization.XmlFormatGeneratorStatics.GetTypeHandleMethod, System.Runtime.Serialization.XmlFormatGeneratorStatics.GetTypeMethod, System.Runtime.Serialization.CodeGenerator.Ldtoken(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.CodeGenerator.Stloc(), and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue().