Terraria: CaptureInterface.ModeEdgeSelection.DrawMarkedArea
DrawMarkedArea()
void CaptureInterface.ModeEdgeSelection.DrawMarkedArea (SpriteBatch sb) inline private
         {
             if (!EdgeAPinned || !EdgeBPinned)
             {
                 return;
             }
             int num = Math.Min(EdgeA.X, EdgeB.X);
             int num2 = Math.Min(EdgeA.Y, EdgeB.Y);
             int num3 = Math.Abs(EdgeA.X - EdgeB.X);
             int num4 = Math.Abs(EdgeA.Y - EdgeB.Y);
             if (!Main.mapFullscreen)
             {
                 Rectangle value = Main.ReverseGravitySupport(new Rectangle(num * 16, num2 * 16, (num3 + 1) * 16, (num4 + 1) * 16));
                 Rectangle value2 = Main.ReverseGravitySupport(new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth + 1, Main.screenHeight + 1));
                 Rectangle.Intersect(ref value2, ref value, out var result);
                 if (result.Width != 0 && result.Height != 0)
                 {
                     result.Offset(-value2.X, -value2.Y);
                     sb.Draw(TextureAssets.MagicPixel.Value, result, Settings.MarkedAreaColor);
                     for (int i = 0; i < 2; i++)
                     {
                         sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(result.X, result.Y + ((i == 1) ? result.Height : (-2)), result.Width, 2), Color.White);
                         sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(result.X + ((i == 1) ? result.Width : (-2)), result.Y, 2, result.Height), Color.White);
                     }
                 }
                 return;
             }
             GetMapCoords(num, num2, 1, out var result2);
             GetMapCoords(num + num3 + 1, num2 + num4 + 1, 1, out var result3);
             Rectangle value3 = new Rectangle(result2.X, result2.Y, result3.X - result2.X, result3.Y - result2.Y);
             Rectangle value4 = new Rectangle(0, 0, Main.screenWidth + 1, Main.screenHeight + 1);
             Rectangle.Intersect(ref value4, ref value3, out var result4);
             if (result4.Width != 0 && result4.Height != 0)
             {
                 result4.Offset(-value4.X, -value4.Y);
                 sb.Draw(TextureAssets.MagicPixel.Value, result4, Settings.MarkedAreaColor);
                 for (int j = 0; j < 2; j++)
                 {
                     sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(result4.X, result4.Y + ((j == 1) ? result4.Height : (-2)), result4.Width, 2), Color.White);
                     sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(result4.X + ((j == 1) ? result4.Width : (-2)), result4.Y, 2, result4.Height), Color.White);
                 }
             }
         }
References Color, CaptureInterface.EdgeA, CaptureInterface.EdgeAPinned, CaptureInterface.EdgeB, CaptureInterface.EdgeBPinned, CaptureInterface.GetMapCoords(), TextureAssets.MagicPixel, Main.mapFullscreen, CaptureInterface.Settings.MarkedAreaColor, Main.ReverseGravitySupport(), Main.screenHeight, Main.screenPosition, Main.screenWidth, and Asset< T >.Value.
Referenced by CaptureInterface.ModeEdgeSelection.Draw().