Terraria: MS.Internal.Xml.XPath.MergeFilterQuery.MatchNode
MatchNode()
override XPathNavigator MS.Internal.Xml.XPath.MergeFilterQuery.MatchNode (XPathNavigator current) inline virtual
Reimplemented from MS.Internal.Xml.XPath.Query.
Definition at line 43 of file MergeFilterQuery.cs.
    {
        XPathNavigator xPathNavigator = _child.MatchNode(current);
        if (xPathNavigator == null)
        {
            return null;
        }
        xPathNavigator = input.MatchNode(xPathNavigator);
        if (xPathNavigator == null)
        {
            return null;
        }
        Evaluate(new XPathSingletonIterator(xPathNavigator.Clone(), moved: true));
        for (XPathNavigator xPathNavigator2 = Advance(); xPathNavigator2 != null; xPathNavigator2 = Advance())
        {
            if (xPathNavigator2.IsSamePosition(current))
            {
                return xPathNavigator;
            }
        }
        return null;
    }
References MS.Internal.Xml.XPath.MergeFilterQuery._child, MS.Internal.Xml.XPath.CacheOutputQuery.Advance(), System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.MergeFilterQuery.Evaluate(), MS.Internal.Xml.XPath.CacheOutputQuery.input, and MS.Internal.Xml.XPath.Query.MatchNode().