Terraria: MS.Internal.Xml.XPath.MergeFilterQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.MergeFilterQuery.Evaluate (XPathNodeIterator nodeIterator) inline
Definition at line 28 of file MergeFilterQuery.cs.
    {
        base.Evaluate(nodeIterator);
        while (input.Advance() != null)
        {
            _child.Evaluate(input);
            XPathNavigator nav;
            while ((nav = _child.Advance()) != null)
            {
                Query.Insert(outputBuffer, nav);
            }
        }
        return this;
    }
References MS.Internal.Xml.XPath.MergeFilterQuery._child, MS.Internal.Xml.XPath.Query.Advance(), MS.Internal.Xml.XPath.Query.Evaluate(), MS.Internal.Xml.XPath.CacheOutputQuery.input, MS.Internal.Xml.XPath.Query.Insert(), and MS.Internal.Xml.XPath.CacheOutputQuery.outputBuffer.
Referenced by MS.Internal.Xml.XPath.MergeFilterQuery.MatchNode().