Terraria: Terraria.Initializers.PlayerDataInitializer.LoadStickerMale
LoadStickerMale()
static void Terraria.Initializers.PlayerDataInitializer.LoadStickerMale () inline static private
    {
        CopyVariant(1, 0);
        LoadVariant(1, new int[6] { 4, 6, 8, 11, 12, 13 });
    }
References Terraria.Initializers.PlayerDataInitializer.CopyVariant(), and Terraria.Initializers.PlayerDataInitializer.LoadVariant().
Referenced by Terraria.Initializers.PlayerDataInitializer.Load().