Terraria: System.Xml.Linq.XName.Get
Get() [1/2]
static XName System.Xml.Linq.XName.Get (string expandedName) inline static
Definition at line 36 of file XName.cs.
    {
        if (expandedName == null)
        {
            throw new ArgumentNullException("expandedName");
        }
        if (expandedName.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Argument_InvalidExpandedName, expandedName));
        }
        if (expandedName[0] == '{')
        {
            int num = expandedName.LastIndexOf('}');
            if (num <= 1 || num == expandedName.Length - 1)
            {
                throw new ArgumentException(System.SR.Format(System.SR.Argument_InvalidExpandedName, expandedName));
            }
            return XNamespace.Get(expandedName, 1, num - 1).GetName(expandedName, num + 1, expandedName.Length - num - 1);
        }
        return XNamespace.None.GetName(expandedName);
    }
References System.SR.Argument_InvalidExpandedName, System.Xml.ArgumentException, System.Xml.Dictionary, System.SR.Format(), System.Xml.Linq.XNamespace.Get(), and System.Xml.Linq.XNamespace.None.
Referenced by System.Xml.Linq.XName.operator XName?().