Terraria: System.Security.Cryptography.SafeProvHandle.Dispose
Dispose() [2/2]
override void System.Security.Cryptography.SafeProvHandle.Dispose (bool disposing) inline protected virtual
Reimplemented from System.Runtime.InteropServices.SafeHandle.
Definition at line 74 of file SafeProvHandle.cs.
    {
        if (!SafeHandleCache<SafeProvHandle>.IsCachedInvalidHandle(this))
        {
            base.Dispose(disposing);
        }
    }
Referenced by Internal.NativeCrypto.CapiHelper.AcquireCsp(), Internal.NativeCrypto.CapiHelper.CreateCSP(), Internal.NativeCrypto.CapiHelper.CreateProvHandle(), Internal.Cryptography.BasicSymmetricCipherCsp.Dispose(), System.Security.Cryptography.DSACryptoServiceProvider.Dispose(), System.Security.Cryptography.RSACryptoServiceProvider.Dispose(), and Internal.NativeCrypto.CapiHelper.OpenCSP().