Terraria: System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitChildren
VisitChildren()
override XslFlags System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitChildren (XslNode node) inline protected virtual
Reimplemented from System.Xml.Xsl.Xslt.XslVisitor< XslFlags >.
Definition at line 623 of file XslAstAnalyzer.cs.
    {
        XslFlags xslFlags = XslFlags.None;
        foreach (XslNode item in node.Content)
        {
            xslFlags |= Visit(item);
        }
        return xslFlags;
    }
References System.Xml.Dictionary, System.item, and System.Xml.Xsl.Xslt.XslAstAnalyzer.Visit().
Referenced by System.Xml.Xsl.Xslt.XslAstAnalyzer.ProcessVarPar(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitAttribute(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitAttributeSet(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitComment(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitCopy(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitElement(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitError(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitIf(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitLiteralAttribute(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitLiteralElement(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitMessage(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitPI(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitTemplate(), and System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitText().