Terraria: System.Xml.Xsl.Xslt.XslAstAnalyzer.FillModeFlags
FillModeFlags()
void System.Xml.Xsl.Xslt.XslAstAnalyzer.FillModeFlags (Dictionary< QilName, XslFlags > parentModeFlags, Stylesheet sheet) inline private
Definition at line 582 of file XslAstAnalyzer.cs.
    {
        Stylesheet[] imports = sheet.Imports;
        foreach (Stylesheet sheet2 in imports)
        {
            FillModeFlags(sheet.ModeFlags, sheet2);
        }
        foreach (KeyValuePair<QilName, XslFlags> modeFlag in sheet.ModeFlags)
        {
            if (!parentModeFlags.TryGetValue(modeFlag.Key, out var value))
            {
                value = XslFlags.None;
            }
            parentModeFlags[modeFlag.Key] = value | modeFlag.Value;
        }
        foreach (Template template in sheet.Templates)
        {
            XslFlags xslFlags = template.Flags & (XslFlags.FocusFilter | XslFlags.SideEffects);
            if (xslFlags != 0)
            {
                if (!parentModeFlags.TryGetValue(template.Mode, out var value2))
                {
                    value2 = XslFlags.None;
                }
                parentModeFlags[template.Mode] = value2 | xslFlags;
            }
        }
    }
References System.Xml.Dictionary, System.Xml.Xsl.Xslt.XslAstAnalyzer.FillModeFlags(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Xsl.Xslt.XslAstAnalyzer.Analyze(), and System.Xml.Xsl.Xslt.XslAstAnalyzer.FillModeFlags().