Terraria: System.Xml.Xsl.Xslt.XslAstAnalyzer.ProcessAvt
ProcessAvt()
XslFlags System.Xml.Xsl.Xslt.XslAstAnalyzer.ProcessAvt (string avt) inline private
Definition at line 923 of file XslAstAnalyzer.cs.
    {
        return _xpathAnalyzer.AnalyzeAvt(avt) & ~XslFlags.TypeFilter;
    }
References System.Xml.Xsl.Xslt.XslAstAnalyzer._xpathAnalyzer, and System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.AnalyzeAvt().
Referenced by System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitAttribute(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitElement(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitLiteralAttribute(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitNumber(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitPI(), and System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitSort().