Terraria: System.Xml.Xsl.Xslt.XslAstAnalyzer.ProcessVarPar
ProcessVarPar()
XslFlags System.Xml.Xsl.Xslt.XslAstAnalyzer.ProcessVarPar (VarPar node) inline private
Definition at line 885 of file XslAstAnalyzer.cs.
    {
        XslFlags result;
        if (node.Select != null)
        {
            if (node.Content.Count != 0)
            {
                result = _xpathAnalyzer.Analyze(node.Select) | VisitChildren(node) | XslFlags.TypeFilter;
                _typeDonor = null;
            }
            else
            {
                result = _xpathAnalyzer.Analyze(node.Select);
                _typeDonor = _xpathAnalyzer.TypeDonor;
                if (_typeDonor != null && node.NodeType != XslNodeType.WithParam)
                {
                    _dataFlow.AddEdge(_typeDonor, node);
                }
            }
        }
        else if (node.Content.Count != 0)
        {
            result = XslFlags.Rtf | VisitChildren(node);
            _typeDonor = null;
        }
        else
        {
            result = XslFlags.String;
            _typeDonor = null;
        }
        return result;
    }
References System.Xml.Xsl.Xslt.XslAstAnalyzer._dataFlow, System.Xml.Xsl.Xslt.XslAstAnalyzer._typeDonor, System.Xml.Xsl.Xslt.XslAstAnalyzer._xpathAnalyzer, System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.Analyze(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.TypeDonor, and System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitChildren().
Referenced by System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitParam(), System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitVariable(), and System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitWithParam().