Terraria: System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitApplyTemplates
VisitApplyTemplates()
override XslFlags System.Xml.Xsl.Xslt.XslAstAnalyzer.VisitApplyTemplates (XslNode node) inline protected virtual
Reimplemented from System.Xml.Xsl.Xslt.XslVisitor< XslFlags >.
Definition at line 651 of file XslAstAnalyzer.cs.
    {
        XslFlags xslFlags = ProcessExpr(node.Select);
        foreach (XslNode item in node.Content)
        {
            xslFlags |= Visit(item);
            if (item.NodeType == XslNodeType.WithParam)
            {
                ModeName key = new ModeName(node.Name, item.Name);
                if (!_applyTemplatesParams.TryGetValue(key, out var value))
                {
                    VarPar varPar2 = (_applyTemplatesParams[key] = AstFactory.WithParam(item.Name));
                    value = varPar2;
                }
                if (_typeDonor != null)
                {
                    _dataFlow.AddEdge(_typeDonor, value);
                }
                else
                {
                    value.Flags |= item.Flags & XslFlags.TypeFilter;
                }
            }
        }
        if (_currentTemplate != null)
        {
            AddApplyTemplatesEdge(node.Name, _currentTemplate);
        }
        return XslFlags.Rtf | XslFlags.HasCalls | xslFlags;
    }
References System.Xml.Xsl.Xslt.XslAstAnalyzer._applyTemplatesParams, System.Xml.Xsl.Xslt.XslAstAnalyzer._currentTemplate, System.Xml.Xsl.Xslt.XslAstAnalyzer._dataFlow, System.Xml.Xsl.Xslt.XslAstAnalyzer._typeDonor, System.Xml.Xsl.Xslt.XslAstAnalyzer.AddApplyTemplatesEdge(), System.Xml.Dictionary, System.item, System.key, System.Xml.Xsl.Xslt.XslAstAnalyzer.ProcessExpr(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, System.Xml.Xsl.Xslt.XslAstAnalyzer.Visit(), and System.Xml.Xsl.Xslt.AstFactory.WithParam().