Terraria: System.Xml.Xsl.Xslt.XslAstAnalyzer.DepthFirstSearch
DepthFirstSearch()
void System.Xml.Xsl.Xslt.XslAstAnalyzer.DepthFirstSearch (ProtoTemplate t) inline private
Definition at line 973 of file XslAstAnalyzer.cs.
    {
        t.Flags |= XslFlags.SideEffects | XslFlags.Stop;
        foreach (ProtoTemplate adj in _revCall0Graph.GetAdjList(t))
        {
            if ((adj.Flags & XslFlags.Stop) == 0)
            {
                DepthFirstSearch(adj);
            }
        }
        foreach (ProtoTemplate adj2 in _revCall1Graph.GetAdjList(t))
        {
            if ((adj2.Flags & XslFlags.Stop) == 0)
            {
                DepthFirstSearch(adj2);
            }
        }
        if (!(t is Template template) || !_revApplyTemplatesGraph.TryGetValue(template.Mode, out var value))
        {
            return;
        }
        _revApplyTemplatesGraph.Remove(template.Mode);
        foreach (ProtoTemplate item in value)
        {
            if ((item.Flags & XslFlags.Stop) == 0)
            {
                DepthFirstSearch(item);
            }
        }
    }
References System.Xml.Xsl.Xslt.XslAstAnalyzer._revApplyTemplatesGraph, System.Xml.Xsl.Xslt.XslAstAnalyzer._revCall0Graph, System.Xml.Xsl.Xslt.XslAstAnalyzer._revCall1Graph, System.Xml.Xsl.Xslt.XslAstAnalyzer.DepthFirstSearch(), System.Xml.Dictionary, System.item, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Xsl.Xslt.XslAstAnalyzer.DepthFirstSearch(), and System.Xml.Xsl.Xslt.XslAstAnalyzer.PropagateSideEffectsFlag().