Terraria: System.Xml.Xsl.Xslt.XslAstAnalyzer.Analyze
Analyze()
XslFlags System.Xml.Xsl.Xslt.XslAstAnalyzer.Analyze (Compiler compiler) inline
Definition at line 484 of file XslAstAnalyzer.cs.
    {
        _compiler = compiler;
        _scope = new CompilerScopeManager<VarPar>();
        _xpathAnalyzer = new XPathAnalyzer(compiler, _scope);
        foreach (VarPar externalPar in compiler.ExternalPars)
        {
            _scope.AddVariable(externalPar.Name, externalPar);
        }
        foreach (VarPar globalVar in compiler.GlobalVars)
        {
            _scope.AddVariable(globalVar.Name, globalVar);
        }
        foreach (VarPar externalPar2 in compiler.ExternalPars)
        {
            Visit(externalPar2);
            externalPar2.Flags |= XslFlags.TypeFilter;
        }
        foreach (VarPar globalVar2 in compiler.GlobalVars)
        {
            Visit(globalVar2);
        }
        XslFlags xslFlags = XslFlags.None;
        foreach (ProtoTemplate allTemplate in compiler.AllTemplates)
        {
            xslFlags |= Visit(_currentTemplate = allTemplate);
        }
        foreach (ProtoTemplate allTemplate2 in compiler.AllTemplates)
        {
            foreach (XslNode item in allTemplate2.Content)
            {
                if (item.NodeType != XslNodeType.Text)
                {
                    if (item.NodeType != XslNodeType.Param)
                    {
                        break;
                    }
                    VarPar varPar = (VarPar)item;
                    if ((varPar.Flags & XslFlags.MayBeDefault) != 0)
                    {
                        varPar.Flags |= varPar.DefValueFlags;
                    }
                }
            }
        }
        for (int num = 32; num != 0; num >>= 1)
        {
            _dataFlow.PropagateFlag((XslFlags)num);
        }
        _dataFlow = null;
        foreach (KeyValuePair<Template, Stylesheet> item2 in _fwdApplyImportsGraph)
        {
            Stylesheet[] imports = item2.Value.Imports;
            foreach (Stylesheet sheet in imports)
            {
                AddImportDependencies(sheet, item2.Key);
            }
        }
        _fwdApplyImportsGraph = null;
        if ((xslFlags & XslFlags.Current) != 0)
        {
            _revCall0Graph.PropagateFlag(XslFlags.Current);
        }
        if ((xslFlags & XslFlags.Position) != 0)
        {
            _revCall0Graph.PropagateFlag(XslFlags.Position);
        }
        if ((xslFlags & XslFlags.Last) != 0)
        {
            _revCall0Graph.PropagateFlag(XslFlags.Last);
        }
        if ((xslFlags & XslFlags.SideEffects) != 0)
        {
            PropagateSideEffectsFlag();
        }
        _revCall0Graph = null;
        _revCall1Graph = null;
        _revApplyTemplatesGraph = null;
        FillModeFlags(compiler.Root.ModeFlags, compiler.Root.Imports[0]);
        return xslFlags;
    }
References System.Xml.Xsl.Xslt.XslAstAnalyzer._compiler, System.Xml.Xsl.Xslt.XslAstAnalyzer._currentTemplate, System.Xml.Xsl.Xslt.XslAstAnalyzer._dataFlow, System.Xml.Xsl.Xslt.XslAstAnalyzer._fwdApplyImportsGraph, System.Xml.Xsl.Xslt.XslAstAnalyzer._revApplyTemplatesGraph, System.Xml.Xsl.Xslt.XslAstAnalyzer._revCall0Graph, System.Xml.Xsl.Xslt.XslAstAnalyzer._revCall1Graph, System.Xml.Xsl.Xslt.XslAstAnalyzer._scope, System.Xml.Xsl.Xslt.XslAstAnalyzer._xpathAnalyzer, System.Xml.Xsl.Xslt.XslAstAnalyzer.AddImportDependencies(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XslAstAnalyzer.FillModeFlags(), System.item, System.Xml.Xsl.Xslt.XslAstAnalyzer.PropagateSideEffectsFlag(), and System.Xml.Xsl.Xslt.XslAstAnalyzer.Visit().
Referenced by System.Xml.Xsl.Xslt.QilGenerator.Compile().