Terraria: NewMultiplayerClosePlayersOverlay.Draw
Draw()
void NewMultiplayerClosePlayersOverlay.Draw () inline
Implements IMultiplayerClosePlayersOverlay.
     {
         int teamNamePlateDistance = Main.teamNamePlateDistance;
         if (teamNamePlateDistance <= 0)
         {
             return;
         }
         _playerOnScreenCache.Clear();
         _playerOffScreenCache.Clear();
         SpriteBatch spriteBatch = Main.spriteBatch;
         PlayerInput.SetZoom_World();
         int screenWidth = Main.screenWidth;
         int screenHeight = Main.screenHeight;
         Vector2 screenPosition = Main.screenPosition;
         PlayerInput.SetZoom_UI();
         int num = teamNamePlateDistance * 8;
         Player[] player = Main.player;
         int myPlayer = Main.myPlayer;
         byte mouseTextColor = Main.mouseTextColor;
         Color[] teamColor = Main.teamColor;
         _ = Main.screenPosition;
         Player player2 = player[myPlayer];
         float num2 = (float)(int)mouseTextColor / 255f;
         if (player2.team == 0)
         {
             return;
         }
         DynamicSpriteFont value = FontAssets.MouseText.Value;
         for (int i = 0; i < 255; i++)
         {
             if (i == myPlayer)
             {
                 continue;
             }
             Player player3 = player[i];
             if (!player3.active || player3.dead || player3.team != player2.team)
             {
                 continue;
             }
             string name = player3.name;
             GetDistance(screenWidth, screenHeight, screenPosition, player2, value, player3, name, out var namePlatePos, out var namePlateDist, out var measurement);
             Color color = new Color((byte)((float)(int)teamColor[player3.team].R * num2), (byte)((float)(int)teamColor[player3.team].G * num2), (byte)((float)(int)teamColor[player3.team].B * num2), mouseTextColor);
             if (namePlateDist > 0f)
             {
                 float num3 = player3.Distance(player2.Center);
                 if (!(num3 > (float)num))
                 {
                     float num4 = 20f;
                     float num5 = -27f;
                     num5 -= (measurement.X - 85f) / 2f;
                     string textValue = Language.GetTextValue("GameUI.PlayerDistance", (int)(num3 / 16f * 2f));
                     Vector2 npDistPos = value.MeasureString(textValue);
                     npDistPos.X = namePlatePos.X - num5;
                     npDistPos.Y = namePlatePos.Y + measurement.Y / 2f - npDistPos.Y / 2f - num4;
                     _playerOffScreenCache.Add(new PlayerOffScreenCache(name, namePlatePos, color, npDistPos, textValue, player3, measurement));
                 }
             }
             else
             {
                 _playerOnScreenCache.Add(new PlayerOnScreenCache(name, namePlatePos, color));
             }
         }
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
         for (int j = 0; j < _playerOnScreenCache.Count; j++)
         {
             _playerOnScreenCache[j].DrawPlayerName_WhenPlayerIsOnScreen(spriteBatch);
         }
         for (int k = 0; k < _playerOffScreenCache.Count; k++)
         {
             _playerOffScreenCache[k].DrawPlayerName(spriteBatch);
         }
         for (int l = 0; l < _playerOffScreenCache.Count; l++)
         {
             _playerOffScreenCache[l].DrawPlayerDistance(spriteBatch);
         }
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
         for (int m = 0; m < _playerOffScreenCache.Count; m++)
         {
             _playerOffScreenCache[m].DrawLifeBar();
         }
         spriteBatch.End();
         spriteBatch.Begin(SpriteSortMode.Immediate, null, null, null, null, null, Main.UIScaleMatrix);
         for (int n = 0; n < _playerOffScreenCache.Count; n++)
         {
             _playerOffScreenCache[n].DrawPlayerHead();
         }
     }
References _playerOffScreenCache, _playerOnScreenCache, Entity.active, Entity.Center, Color, Player.dead, Entity.Distance(), GetDistance(), Language.GetTextValue(), DynamicSpriteFont.MeasureString(), FontAssets.MouseText, Main.mouseTextColor, Main.myPlayer, Player.name, Main.player, Main.screenHeight, Main.screenPosition, Main.screenWidth, PlayerInput.SetZoom_UI(), PlayerInput.SetZoom_World(), Main.spriteBatch, Player.team, Main.teamColor, Main.teamNamePlateDistance, Main.UIScaleMatrix, and Asset< T >.Value.