Terraria: ChatCommandProcessor.ProcessIncomingMessage
ProcessIncomingMessage()
void ChatCommandProcessor.ProcessIncomingMessage (ChatMessage message, int clientId) inline
Implements IChatProcessor.
     {
         if (_commands.TryGetValue(message.CommandId, out var value))
         {
             value.ProcessIncomingMessage(message.Text, (byte)clientId);
             message.Consume();
         }
         else if (_defaultCommand != null)
         {
             _defaultCommand.ProcessIncomingMessage(message.Text, (byte)clientId);
             message.Consume();
         }
     }
References _commands, _defaultCommand, ChatMessage.CommandId, ChatMessage.Consume(), IChatCommand.ProcessIncomingMessage(), and ChatMessage.Text.
Referenced by NetTextModule.DeserializeAsServer(), and Main.DoUpdate_HandleChat().