Terraria: ChatCommandProcessor.AddCommand< T >
AddCommand< T >()
ChatCommandProcessor ChatCommandProcessor.AddCommand< T > () inline
Type Constraints
T : IChatCommand
T : new()
                                                         : IChatCommand, new()
     {
         ChatCommandAttribute cacheableAttribute = AttributeUtilities.GetCacheableAttribute<T, ChatCommandAttribute>();
         string commandKey = "ChatCommand." + cacheableAttribute.Name;
         ChatCommandId chatCommandId = ChatCommandId.FromType<T>();
         _commands[chatCommandId] = new T();
         if (Language.Exists(commandKey))
         {
             _localizedCommands.Add(Language.GetText(commandKey), chatCommandId);
         }
         else
         {
             commandKey += "_";
             LocalizedText[] array = Language.FindAll((string key, LocalizedText text) => key.StartsWith(commandKey));
             foreach (LocalizedText key2 in array)
             {
                 _localizedCommands.Add(key2, chatCommandId);
             }
         }
         return this;
     }
References _commands, _localizedCommands, Language.Exists(), Language.FindAll(), Language.GetText(), ChatCommandAttribute.Name, and T.
Referenced by AddDefaultCommand< T >().