Terraria: System.Data.DataRowComparer.CompareArray
CompareArray()
static bool System.Data.DataRowComparer< TRow >.CompareArray (Array a, Array b) inline static private
Definition at line 43 of file DataRowComparer.cs.
    {
        if (b == null || 1 != a.Rank || 1 != b.Rank || a.Length != b.Length)
        {
            return false;
        }
        int num = a.GetLowerBound(0);
        int num2 = b.GetLowerBound(0);
        if (a.GetType() == b.GetType() && num == 0 && num2 == 0)
        {
            switch (Type.GetTypeCode(a.GetType().GetElementType()))
            {
            case TypeCode.Byte:
                return CompareEquatableArray((byte[])a, (byte[])b);
            case TypeCode.Int16:
                return CompareEquatableArray((short[])a, (short[])b);
            case TypeCode.Int32:
                return CompareEquatableArray((int[])a, (int[])b);
            case TypeCode.Int64:
                return CompareEquatableArray((long[])a, (long[])b);
            case TypeCode.String:
                return CompareEquatableArray((string[])a, (string[])b);
            }
        }
        int num3 = num + a.Length;
        while (num < num3)
        {
            if (!AreElementEqual(a.GetValue(num), b.GetValue(num2)))
            {
                return false;
            }
            num++;
            num2++;
        }
        return true;
    }
References System.Data.DataRowComparer< TRow >.AreElementEqual(), and System.Type.GetTypeCode().
Referenced by System.Data.DataRowComparer< TRow >.AreEqual().