Terraria: System.Net.FtpWebRequest.DataStreamClosed
DataStreamClosed()
void System.Net.FtpWebRequest.DataStreamClosed (CloseExState closeState) inline package
Definition at line 1401 of file FtpWebRequest.cs.
    {
        if ((closeState & CloseExState.Abort) == 0)
        {
            if (!_async)
            {
                if (_connection != null)
                {
                    _connection.CheckContinuePipeline();
                }
            }
            else
            {
                _requestCompleteAsyncResult.InternalWaitForCompletion();
                CheckError();
            }
        }
        else
        {
            _connection?.Abort(ExceptionHelper.RequestAbortedException);
        }
    }
References System.Net.CommandStream.Abort(), System.Net.CommandStream.CheckContinuePipeline(), System.Net.LazyAsyncResult.InternalWaitForCompletion(), and System.Net.ExceptionHelper.RequestAbortedException.
Referenced by System.Net.FtpDataStream.CloseEx().