Terraria: System.Net.FtpWebRequest.FtpWebRequest
FtpWebRequest()
System.Net.FtpWebRequest.FtpWebRequest (Uri uri) inline package
Definition at line 467 of file FtpWebRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, uri, ".ctor");
        }
        if ((object)uri.Scheme != Uri.UriSchemeFtp)
        {
            throw new ArgumentOutOfRangeException("uri");
        }
        _timerCallback = TimerCallback;
        _syncObject = new object();
        NetworkCredential networkCredential = null;
        _uri = uri;
        _methodInfo = FtpMethodInfo.GetMethodInfo("RETR");
        if (_uri.UserInfo != null && _uri.UserInfo.Length != 0)
        {
            string userInfo = _uri.UserInfo;
            string userName = userInfo;
            string password = "";
            int num = userInfo.IndexOf(':');
            if (num != -1)
            {
                userName = Uri.UnescapeDataString(userInfo.Substring(0, num));
                num++;
                password = Uri.UnescapeDataString(userInfo.Substring(num, userInfo.Length - num));
            }
            networkCredential = new NetworkCredential(userName, password);
        }
        if (networkCredential == null)
        {
            networkCredential = s_defaultFtpNetworkCredential;
        }
        _authInfo = networkCredential;
    }
References System.Net.FtpWebRequest._authInfo, System.Net.FtpWebRequest._methodInfo, System.Net.FtpWebRequest._syncObject, System.Net.FtpWebRequest._timerCallback, System.Net.FtpWebRequest._uri, System.Net.FtpMethodInfo.GetMethodInfo(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.FtpWebRequest.s_defaultFtpNetworkCredential, System.Uri.Scheme, System.Net.FtpWebRequest.TimerCallback(), System.Uri.UnescapeDataString(), System.Uri.UriSchemeFtp, and System.Uri.UserInfo.