Terraria: System.Net.FtpWebRequest.FinishRequestStage
FinishRequestStage()
RequestStage System.Net.FtpWebRequest.FinishRequestStage (RequestStage stage) inline private
Definition at line 1219 of file FtpWebRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"state:{stage}", "FinishRequestStage");
        }
        if (_exception != null)
        {
            stage = RequestStage.ReleaseConnection;
        }
        RequestStage requestStage;
        LazyAsyncResult writeAsyncResult;
        LazyAsyncResult readAsyncResult;
        FtpControlStream connection;
        lock (_syncObject)
        {
            requestStage = _requestStage;
            if (stage == RequestStage.CheckForError)
            {
                return requestStage;
            }
            if (requestStage == RequestStage.ReleaseConnection && stage == RequestStage.ReleaseConnection)
            {
                return RequestStage.ReleaseConnection;
            }
            if (stage > requestStage)
            {
                _requestStage = stage;
            }
            if (stage <= RequestStage.RequestStarted)
            {
                return requestStage;
            }
            writeAsyncResult = _writeAsyncResult;
            readAsyncResult = _readAsyncResult;
            connection = _connection;
            if (stage == RequestStage.ReleaseConnection)
            {
                if (_exception == null && !_aborted && requestStage != RequestStage.ReadReady && _methodInfo.IsDownload && !_ftpWebResponse.IsFromCache)
                {
                    return requestStage;
                }
                _connection = null;
            }
        }
        try
        {
            if ((stage == RequestStage.ReleaseConnection || requestStage == RequestStage.ReleaseConnection) && connection != null)
            {
                try
                {
                    if (_exception != null)
                    {
                        connection.Abort(_exception);
                    }
                }
                finally
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, $"Releasing connection: {connection}", "FinishRequestStage");
                    }
                    connection.CloseSocket();
                    if (_async && _requestCompleteAsyncResult != null)
                    {
                        _requestCompleteAsyncResult.InvokeCallback();
                    }
                }
            }
            return requestStage;
        }
        finally
        {
            try
            {
                if (stage >= RequestStage.WriteReady)
                {
                    if (_methodInfo.IsUpload && !_getRequestStreamStarted)
                    {
                        if (_stream != null)
{
                            _stream.Close();
                        }
                    }
                    else if (writeAsyncResult != null && !writeAsyncResult.InternalPeekCompleted)
                    {
                        writeAsyncResult.InvokeCallback();
                    }
                }
            }
            finally
            {
                if (stage >= RequestStage.ReadReady && readAsyncResult != null && !readAsyncResult.InternalPeekCompleted)
                {
                    readAsyncResult.InvokeCallback();
                }
            }
        }
    }
References System.Net.CommandStream.Abort(), System.IO.Stream.Close(), System.Net.NetworkStreamWrapper.CloseSocket(), System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InternalPeekCompleted, System.Net.LazyAsyncResult.InvokeCallback(), System.Net.FtpMethodInfo.IsDownload, System.Net.WebResponse.IsFromCache, System.Net.FtpMethodInfo.IsUpload, and System.Net.NetEventSource.Log.
Referenced by System.Net.FtpWebRequest.BeginGetRequestStream(), System.Net.FtpWebRequest.BeginGetResponse(), System.Net.FtpWebRequest.GetRequestStream(), and System.Net.FtpWebRequest.GetResponse().