Terraria: System.Net.FtpWebRequest.SetException
SetException()
void System.Net.FtpWebRequest.SetException (Exception exception) inline private
Definition at line 1018 of file FtpWebRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, null, "SetException");
        }
        if (exception is OutOfMemoryException)
        {
            _exception = exception;
            throw exception;
        }
        FtpControlStream connection = _connection;
        if (_exception == null)
        {
            if (exception is WebException)
            {
                EnsureFtpWebResponse(exception);
                _exception = new WebException(exception.Message, null, ((WebException)exception).Status, _ftpWebResponse);
            }
            else if (exception is AuthenticationException || exception is SecurityException)
            {
                _exception = exception;
            }
            else if (connection != null && connection.StatusCode != 0)
            {
                EnsureFtpWebResponse(exception);
                _exception = new WebException(System.SR.Format(System.SR.net_ftp_servererror, connection.StatusLine), exception, WebExceptionStatus.ProtocolError, _ftpWebResponse);
            }
            else
            {
                _exception = new WebException(exception.Message, exception);
            }
            if (connection != null && _ftpWebResponse != null)
            {
                _ftpWebResponse.UpdateStatus(connection.StatusCode, connection.StatusLine, connection.ExitMessage);
            }
        }
    }
References System.exception, System.Net.FtpControlStream.ExitMessage, System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_ftp_servererror, System.Net.FtpControlStream.StatusCode, System.Net.FtpControlStream.StatusLine, and System.Net.FtpWebResponse.UpdateStatus().
Referenced by System.Net.FtpWebRequest.GetResponse(), and System.Net.FtpWebRequest.SubmitRequest().