Terraria: System.Net.FtpWebRequest.EnsureFtpWebResponse
EnsureFtpWebResponse()
void System.Net.FtpWebRequest.EnsureFtpWebResponse (Exception exception) inline private
Definition at line 1356 of file FtpWebRequest.cs.
    {
        if (_ftpWebResponse == null || (_ftpWebResponse.GetResponseStream() is FtpWebResponse.EmptyStream && _stream != null))
        {
            lock (_syncObject)
            {
                if (_ftpWebResponse == null || (_ftpWebResponse.GetResponseStream() is FtpWebResponse.EmptyStream && _stream != null))
                {
                    Stream stream = _stream;
                    if (_methodInfo.IsUpload)
                    {
                        stream = null;
                    }
                    if (_stream != null && _stream.CanRead && _stream.CanTimeout)
                    {
                        _stream.ReadTimeout = ReadWriteTimeout;
                        _stream.WriteTimeout = ReadWriteTimeout;
                    }
                    FtpControlStream connection = _connection;
                    long num = connection?.ContentLength ?? (-1);
                    if (stream == null && num < 0)
                    {
                        num = 0L;
                    }
                    if (_ftpWebResponse != null)
                    {
                        _ftpWebResponse.SetResponseStream(stream);
                    }
                    else if (connection != null)
                    {
                        _ftpWebResponse = new FtpWebResponse(stream, num, connection.ResponseUri, connection.StatusCode, connection.StatusLine, connection.LastModified, connection.BannerMessage, connection.WelcomeMessage, connection.ExitMessage);
                    }
                    else
                    {
                        _ftpWebResponse = new FtpWebResponse(stream, -1L, _uri, FtpStatusCode.Undefined, null, DateTime.Now, null, null, null);
                    }
                }
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"Returns {_ftpWebResponse} with stream {_ftpWebResponse._responseStream}", "EnsureFtpWebResponse");
        }
    }
References System.Net.FtpControlStream.BannerMessage, System.IO.Stream.CanRead, System.IO.Stream.CanTimeout, System.Net.FtpControlStream.ContentLength, System.Net.FtpControlStream.ExitMessage, System.Net.FtpWebResponse.GetResponseStream(), System.Net.NetEventSource.Info(), System.Net.FtpMethodInfo.IsUpload, System.L, System.Net.FtpControlStream.LastModified, System.Net.NetEventSource.Log, System.DateTime.Now, System.Net.FtpControlStream.ResponseUri, System.Net.FtpWebResponse.SetResponseStream(), System.Net.FtpControlStream.StatusCode, System.Net.FtpControlStream.StatusLine, System.stream, and System.Net.FtpControlStream.WelcomeMessage.
Referenced by System.Net.FtpWebRequest.GetResponse().