Terraria: System.Net.FtpWebRequest.BeginGetResponse
BeginGetResponse()
override IAsyncResult System.Net.FtpWebRequest.BeginGetResponse (AsyncCallback? callback, object? state) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 585 of file FtpWebRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"Method: {_methodInfo.Method}", "BeginGetResponse");
        }
        ContextAwareResult contextAwareResult;
        try
        {
            if (_ftpWebResponse != null)
            {
                contextAwareResult = new ContextAwareResult(this, state, callback);
                contextAwareResult.InvokeCallback(_ftpWebResponse);
                return contextAwareResult;
            }
            if (_getResponseStarted)
            {
                throw new InvalidOperationException(System.SR.net_repcall);
            }
            _getResponseStarted = true;
            CheckError();
            RequestStage requestStage = FinishRequestStage(RequestStage.RequestStarted);
            contextAwareResult = (ContextAwareResult)(_readAsyncResult = new ContextAwareResult(captureIdentity: true, forceCaptureContext: true, this, state, callback));
            if (requestStage >= RequestStage.RequestStarted)
            {
                contextAwareResult.StartPostingAsyncOp();
                contextAwareResult.FinishPostingAsyncOp();
                if (requestStage >= RequestStage.ReadReady)
                {
                    contextAwareResult = null;
                }
                else
                {
                    lock (_syncObject)
                    {
                        if (_requestStage >= RequestStage.ReadReady)
{
                            contextAwareResult = null;
                        }
                    }
                }
                if (contextAwareResult == null)
                {
                    contextAwareResult = (ContextAwareResult)_readAsyncResult;
                    if (!contextAwareResult.InternalPeekCompleted)
                    {
                        contextAwareResult.InvokeCallback();
                    }
                }
            }
            else
            {
                lock (contextAwareResult.StartPostingAsyncOp())
                {
                    SubmitRequest(isAsync: true);
                    contextAwareResult.FinishPostingAsyncOp();
                }
                FinishRequestStage(RequestStage.CheckForError);
            }
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "BeginGetResponse");
            }
            throw;
        }
        return contextAwareResult;
    }
References System.Net.FtpWebRequest._ftpWebResponse, System.Net.FtpWebRequest._getResponseStarted, System.Net.FtpWebRequest._readAsyncResult, System.Net.FtpWebRequest._requestStage, System.Net.FtpWebRequest._syncObject, System.Net.FtpWebRequest.CheckError(), System.Net.NetEventSource.Error(), System.Net.ContextAwareResult.FinishPostingAsyncOp(), System.Net.FtpWebRequest.FinishRequestStage(), System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InternalPeekCompleted, System.Net.LazyAsyncResult.InvokeCallback(), System.Net.NetEventSource.Log, System.SR.net_repcall, System.Net.ContextAwareResult.StartPostingAsyncOp(), System.state, and System.Net.FtpWebRequest.SubmitRequest().