Terraria: System.Net.FtpWebRequest.BeginGetRequestStream
BeginGetRequestStream()
override IAsyncResult System.Net.FtpWebRequest.BeginGetRequestStream (AsyncCallback? callback, object? state) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 736 of file FtpWebRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"Method: {_methodInfo.Method}", "BeginGetRequestStream");
        }
        ContextAwareResult contextAwareResult = null;
        try
        {
            if (_getRequestStreamStarted)
            {
                throw new InvalidOperationException(System.SR.net_repcall);
            }
            _getRequestStreamStarted = true;
            if (!_methodInfo.IsUpload)
            {
                throw new ProtocolViolationException(System.SR.net_nouploadonget);
            }
            CheckError();
            FinishRequestStage(RequestStage.RequestStarted);
            contextAwareResult = new ContextAwareResult(captureIdentity: true, forceCaptureContext: true, this, state, callback);
            lock (contextAwareResult.StartPostingAsyncOp())
            {
                _writeAsyncResult = contextAwareResult;
                SubmitRequest(isAsync: true);
                contextAwareResult.FinishPostingAsyncOp();
                FinishRequestStage(RequestStage.CheckForError);
                return contextAwareResult;
            }
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "BeginGetRequestStream");
            }
            throw;
        }
    }
References System.Net.FtpWebRequest._getRequestStreamStarted, System.Net.FtpWebRequest._methodInfo, System.Net.FtpWebRequest._writeAsyncResult, System.Net.FtpWebRequest.CheckError(), System.Net.NetEventSource.Error(), System.Net.ContextAwareResult.FinishPostingAsyncOp(), System.Net.FtpWebRequest.FinishRequestStage(), System.Net.NetEventSource.Info(), System.Net.FtpMethodInfo.IsUpload, System.Net.NetEventSource.Log, System.SR.net_nouploadonget, System.SR.net_repcall, System.Net.ContextAwareResult.StartPostingAsyncOp(), System.state, and System.Net.FtpWebRequest.SubmitRequest().