Terraria: System.Net.FtpWebRequest.SubmitRequest
SubmitRequest()
void System.Net.FtpWebRequest.SubmitRequest (bool isAsync) inline private
Definition at line 815 of file FtpWebRequest.cs.
    {
        try
        {
            _async = isAsync;
            while (true)
            {
                FtpControlStream ftpControlStream = _connection;
                if (ftpControlStream == null)
                {
                    if (isAsync)
                    {
                        CreateConnectionAsync();
                        return;
                    }
                    ftpControlStream = (_connection = CreateConnection());
                }
                if (!isAsync && Timeout != -1)
                {
                    _remainingTimeout = Timeout - (int)(DateTime.UtcNow - _startTime).TotalMilliseconds;
                    if (_remainingTimeout <= 0)
                    {
                        break;
                    }
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Request being submitted", "SubmitRequest");
                }
                ftpControlStream.SetSocketTimeoutOption(RemainingTimeout);
                try
                {
                    Stream stream = TimedSubmitRequestHelper(isAsync);
                    return;
                }
                catch (Exception e)
                {
                    if (AttemptedRecovery(e))
                    {
                        if (!isAsync && Timeout != -1)
{
                            _remainingTimeout = Timeout - (int)(DateTime.UtcNow - _startTime).TotalMilliseconds;
                            if (_remainingTimeout <= 0)
{
                                throw;
                            }
                        }
                        continue;
                    }
                    throw;
                }
            }
            throw ExceptionHelper.TimeoutException;
        }
        catch (WebException ex)
        {
            if (ex.InnerException is IOException { InnerException: SocketException { SocketErrorCode: SocketError.TimedOut } })
            {
                SetException(ExceptionDispatchInfo.SetCurrentStackTrace(new WebException(System.SR.net_timeout, WebExceptionStatus.Timeout)));
            }
            else
            {
                SetException(ex);
            }
        }
        catch (Exception exception)
        {
            SetException(exception);
        }
    }
References System.Net.FtpWebRequest._async, System.Net.FtpWebRequest._connection, System.Net.FtpWebRequest._remainingTimeout, System.Net.FtpWebRequest._startTime, System.Net.FtpWebRequest.AttemptedRecovery(), System.Net.FtpWebRequest.CreateConnection(), System.Net.FtpWebRequest.CreateConnectionAsync(), System.Net.NetEventSource.Info(), System.Exception.InnerException, System.Net.NetEventSource.Log, System.SR.net_timeout, System.Net.FtpWebRequest.RemainingTimeout, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Net.FtpWebRequest.SetException(), System.Net.NetworkStreamWrapper.SetSocketTimeoutOption(), System.stream, System.Net.FtpWebRequest.TimedSubmitRequestHelper(), System.Net.ExceptionHelper.TimeoutException, and System.DateTime.UtcNow.
Referenced by System.Net.FtpWebRequest.BeginGetRequestStream(), System.Net.FtpWebRequest.BeginGetResponse(), System.Net.FtpWebRequest.GetRequestStream(), and System.Net.FtpWebRequest.GetResponse().