Terraria: System.Net.FtpWebRequest.EndGetRequestStream
EndGetRequestStream()
override Stream System.Net.FtpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 776 of file FtpWebRequest.cs.
    {
        Stream stream = null;
        try
        {
            if (asyncResult == null)
            {
                throw new ArgumentNullException("asyncResult");
            }
            if (!(asyncResult is LazyAsyncResult lazyAsyncResult))
            {
                throw new ArgumentException(System.SR.net_io_invalidasyncresult, "asyncResult");
            }
            if (lazyAsyncResult.EndCalled)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.net_io_invalidendcall, "EndGetResponse"));
            }
            lazyAsyncResult.InternalWaitForCompletion();
            lazyAsyncResult.EndCalled = true;
            CheckError();
            stream = _stream;
            lazyAsyncResult.EndCalled = true;
            if (stream.CanTimeout)
            {
                stream.WriteTimeout = ReadWriteTimeout;
                stream.ReadTimeout = ReadWriteTimeout;
            }
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "EndGetRequestStream");
            }
            throw;
        }
        return stream;
    }
References System.Net.FtpWebRequest._stream, System.asyncResult, System.Net.FtpWebRequest.CheckError(), System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Log, System.SR.net_io_invalidasyncresult, System.SR.net_io_invalidendcall, System.Net.FtpWebRequest.ReadWriteTimeout, and System.stream.