Terraria: System.Net.FtpWebRequest.GetResponse
GetResponse()
override WebResponse System.Net.FtpWebRequest.GetResponse () inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 503 of file FtpWebRequest.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"Method: {_methodInfo.Method}", "GetResponse");
        }
        try
        {
            CheckError();
            if (_ftpWebResponse != null)
            {
                return _ftpWebResponse;
            }
            if (_getResponseStarted)
            {
                throw new InvalidOperationException(System.SR.net_repcall);
            }
            _getResponseStarted = true;
            _startTime = DateTime.UtcNow;
            _remainingTimeout = Timeout;
            if (Timeout != -1)
            {
                _remainingTimeout = Timeout - (int)(DateTime.UtcNow - _startTime).TotalMilliseconds;
                if (_remainingTimeout <= 0)
                {
                    throw ExceptionHelper.TimeoutException;
                }
            }
            RequestStage requestStage = FinishRequestStage(RequestStage.RequestStarted);
            if (requestStage >= RequestStage.RequestStarted)
            {
                if (requestStage < RequestStage.ReadReady)
                {
                    lock (_syncObject)
                    {
                        if (_requestStage < RequestStage.ReadReady)
{
                            _readAsyncResult = new LazyAsyncResult(null, null, null);
                        }
                    }
                    if (_readAsyncResult != null)
                    {
                        _readAsyncResult.InternalWaitForCompletion();
                    }
                    CheckError();
                }
            }
            else
            {
                SubmitRequest(isAsync: false);
                if (_methodInfo.IsUpload)
                {
                    FinishRequestStage(RequestStage.WriteReady);
                }
                else
                {
                    FinishRequestStage(RequestStage.ReadReady);
                }
                CheckError();
                EnsureFtpWebResponse(null);
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex, "GetResponse");
            }
            if (_exception == null)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Error(this, ex, "GetResponse");
                }
                SetException(ex);
                FinishRequestStage(RequestStage.CheckForError);
            }
            throw;
        }
        return _ftpWebResponse;
    }
References System.Net.FtpWebRequest._exception, System.Net.FtpWebRequest._ftpWebResponse, System.Net.FtpWebRequest._getResponseStarted, System.Net.FtpWebRequest._methodInfo, System.Net.FtpWebRequest._readAsyncResult, System.Net.FtpWebRequest._remainingTimeout, System.Net.FtpWebRequest._requestStage, System.Net.FtpWebRequest._startTime, System.Net.FtpWebRequest._syncObject, System.Net.FtpWebRequest.CheckError(), System.Net.FtpWebRequest.EnsureFtpWebResponse(), System.Net.NetEventSource.Error(), System.Net.FtpWebRequest.FinishRequestStage(), System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InternalWaitForCompletion(), System.Net.FtpMethodInfo.IsUpload, System.Net.NetEventSource.Log, System.SR.net_repcall, System.Net.FtpWebRequest.SetException(), System.Net.FtpWebRequest.SubmitRequest(), System.Net.FtpWebRequest.Timeout, System.Net.ExceptionHelper.TimeoutException, and System.DateTime.UtcNow.