Terraria: System.Net.FtpWebRequest.AttemptedRecovery
AttemptedRecovery()
bool System.Net.FtpWebRequest.AttemptedRecovery (Exception e) inline private
Definition at line 995 of file FtpWebRequest.cs.
    {
        if (e is OutOfMemoryException || _onceFailed || _aborted || _timedOut || _connection == null || !_connection.RecoverableFailure)
        {
            return false;
        }
        _onceFailed = true;
        lock (_syncObject)
        {
            if (_connection == null)
            {
                return false;
            }
            _connection.CloseSocket();
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"Releasing connection: {_connection}", "AttemptedRecovery");
            }
            _connection = null;
        }
        return true;
    }
References System.Net.NetworkStreamWrapper.CloseSocket(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.Net.CommandStream.RecoverableFailure.
Referenced by System.Net.FtpWebRequest.SubmitRequest().