Terraria: System.Net.FtpWebRequest.AsyncRequestCallback
AsyncRequestCallback()
void System.Net.FtpWebRequest.AsyncRequestCallback (object obj) inline private
Definition at line 1116 of file FtpWebRequest.cs.
    {
        RequestStage stage = RequestStage.CheckForError;
        try
        {
            FtpControlStream ftpControlStream = obj as FtpControlStream;
            FtpDataStream ftpDataStream = obj as FtpDataStream;
            Exception ex = obj as Exception;
            bool flag = obj == null;
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"stream:{ftpDataStream} conn:{ftpControlStream} exp:{ex} completedRequest:{flag}", "AsyncRequestCallback");
            }
            while (true)
            {
                if (ex != null)
                {
                    if (AttemptedRecovery(ex))
                    {
                        ftpControlStream = CreateConnection();
                        if (ftpControlStream == null)
{
                            return;
                        }
                        ex = null;
                    }
                    if (ex != null)
                    {
                        SetException(ex);
                        return;
                    }
                }
                if (ftpControlStream == null)
                {
                    break;
                }
                lock (_syncObject)
                {
                    if (_aborted)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, $"Releasing connect:{ftpControlStream}", "AsyncRequestCallback");
                        }
                        ftpControlStream.CloseSocket();
                        return;
                    }
                    _connection = ftpControlStream;
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Associate(this, _connection, "AsyncRequestCallback");
                    }
                }
                try
                {
                    ftpDataStream = (FtpDataStream)TimedSubmitRequestHelper(isAsync: true);
                    return;
                }
                catch (Exception ex2)
                {
                    ex = ex2;
                }
            }
            if (ftpDataStream != null)
            {
                lock (_syncObject)
                {
                    if (_aborted)
                    {
                        ((ICloseEx)ftpDataStream).CloseEx(CloseExState.Abort | CloseExState.Silent);
                        return;
                    }
                    _stream = ftpDataStream;
                }
                ftpDataStream.SetSocketTimeoutOption(Timeout);
                EnsureFtpWebResponse(null);
                stage = (ftpDataStream.CanRead ? RequestStage.ReadReady : RequestStage.WriteReady);
            }
            else
            {
                if (!flag)
                {
                    throw new System.Net.InternalException();
                }
                ftpControlStream = _connection;
                if (ftpControlStream != null)
                {
                    EnsureFtpWebResponse(null);
                    _ftpWebResponse.UpdateStatus(ftpControlStream.StatusCode, ftpControlStream.StatusLine, ftpControlStream.ExitMessage);
                }
                stage = RequestStage.ReleaseConnection;
            }
        }
        catch (Exception exception)
        {
            SetException(exception);
        }
        finally
        {
            FinishRequestStage(stage);
        }
    }
References System.Net.NetEventSource.Associate(), System.Net.NetworkStreamWrapper.CloseSocket(), System.exception, System.Net.FtpControlStream.ExitMessage, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.obj, System.Net.FtpDataStream.SetSocketTimeoutOption(), System.Net.FtpControlStream.StatusCode, System.Net.FtpControlStream.StatusLine, and System.Net.FtpWebResponse.UpdateStatus().