Terraria: System.Net.FtpWebRequest.TimedSubmitRequestHelper
TimedSubmitRequestHelper()
Stream System.Net.FtpWebRequest.TimedSubmitRequestHelper (bool isAsync) inline private
Definition at line 931 of file FtpWebRequest.cs.
    {
        if (isAsync)
        {
            if (_requestCompleteAsyncResult == null)
            {
                _requestCompleteAsyncResult = new LazyAsyncResult(null, null, null);
            }
            return _connection.SubmitRequest(this, isAsync: true, readInitalResponseOnConnect: true);
        }
        Stream stream = null;
        bool flag = false;
        TimerThread.Timer timer = TimerQueue.CreateTimer(_timerCallback, null);
        try
        {
            stream = _connection.SubmitRequest(this, isAsync: false, readInitalResponseOnConnect: true);
        }
        catch (Exception ex)
        {
            if ((!(ex is SocketException) && !(ex is ObjectDisposedException)) || !timer.HasExpired)
            {
                timer.Cancel();
                throw;
            }
            flag = true;
        }
        if (flag || !timer.Cancel())
        {
            _timedOut = true;
            throw ExceptionHelper.TimeoutException;
        }
        if (stream != null)
        {
            lock (_syncObject)
            {
                if (_aborted)
                {
                    ((ICloseEx)stream).CloseEx(CloseExState.Abort | CloseExState.Silent);
                    CheckError();
                    throw new System.Net.InternalException();
                }
                _stream = stream;
            }
        }
        return stream;
    }
References System.Net.TimerThread.Timer.Cancel(), System.Net.TimerThread.Timer.HasExpired, System.stream, System.Net.CommandStream.SubmitRequest(), and System.Net.ExceptionHelper.TimeoutException.
Referenced by System.Net.FtpWebRequest.SubmitRequest().