Terraria: Liquid.SettleWaterAt
SettleWaterAt()
static void Liquid.SettleWaterAt (int originX, int originY) inline static private
     {
         Tile tile = Main.tile[originX, originY];
         tilesIgnoreWater(ignoreSolids: true);
         if (tile.liquid == 0)
         {
             return;
         }
         int num = originX;
         int num2 = originY;
         bool tileAtXYHasLava = tile.lava();
         bool flag = tile.honey();
         bool flag2 = tile.shimmer();
         int num3 = tile.liquid;
         byte b = tile.liquidType();
         tile.liquid = 0;
         bool flag3 = true;
         while (true)
         {
             Tile tile2 = Main.tile[num, num2 + 1];
             bool flag4 = false;
             while (num2 < Main.maxTilesY - 5 && tile2.liquid == 0 && (!tile2.nactive() || !Main.tileSolid[tile2.type] || Main.tileSolidTop[tile2.type]))
             {
                 num2++;
                 flag4 = true;
                 flag3 = false;
                 tile2 = Main.tile[num, num2 + 1];
             }
             if (WorldGen.gen && flag4 && !flag && !flag2)
             {
                 if (WorldGen.remixWorldGen)
                 {
                     b = ((num2 > GenVars.lavaLine && ((double)num2 < Main.rockLayer - 80.0 || num2 > Main.maxTilesY - 350) && !WorldGen.oceanDepths(num, num2)) ? ((byte)1) : ((byte)0));
                 }
                 else if (num2 > GenVars.waterLine)
                 {
                     b = 1;
                 }
             }
             int num4 = -1;
             int num5 = 0;
             int num6 = -1;
             int num7 = 0;
             bool flag5 = false;
             bool flag6 = false;
             bool flag7 = false;
             while (true)
             {
                 if (Main.tile[num + num5 * num4, num2].liquid == 0)
                 {
                     num6 = num4;
                     num7 = num5;
                 }
                 if (num4 == -1 && num + num5 * num4 < 5)
                 {
                     flag6 = true;
                 }
                 else if (num4 == 1 && num + num5 * num4 > Main.maxTilesX - 5)
                 {
                     flag5 = true;
                 }
                 tile2 = Main.tile[num + num5 * num4, num2 + 1];
                 if (tile2.liquid != 0 && tile2.liquid != byte.MaxValue && tile2.liquidType() == b)
                 {
                     int num8 = 255 - tile2.liquid;
                     if (num8 > num3)
                     {
                         num8 = num3;
                     }
                     tile2.liquid += (byte)num8;
                     num3 -= num8;
                     if (num3 == 0)
                     {
                         break;
                     }
                 }
                 if (num2 < Main.maxTilesY - 5 && tile2.liquid == 0 && (!tile2.nactive() || !Main.tileSolid[tile2.type] || Main.tileSolidTop[tile2.type]))
                 {
                     flag7 = true;
                     break;
                 }
                 Tile tile3 = Main.tile[num + (num5 + 1) * num4, num2];
                 if ((tile3.liquid != 0 && (!flag3 || num4 != 1)) || (tile3.nactive() && Main.tileSolid[tile3.type] && !Main.tileSolidTop[tile3.type]))
                 {
                     if (num4 == 1)
                     {
                         flag5 = true;
                     }
                     else
                     {
                         flag6 = true;
                     }
                 }
                 if (flag6 && flag5)
                 {
                     break;
                 }
                 if (flag5)
                 {
                     num4 = -1;
                     num5++;
                 }
                 else if (flag6)
                 {
                     if (num4 == 1)
                     {
                         num5++;
                     }
                     num4 = 1;
                 }
                 else
                 {
                     if (num4 == 1)
                     {
                         num5++;
                     }
                     num4 = -num4;
                 }
             }
             num += num7 * num6;
             if (num3 == 0 || !flag7)
             {
                 break;
             }
             num2++;
         }
         Main.tile[num, num2].liquid = (byte)num3;
         Main.tile[num, num2].liquidType(b);
         if (Main.tile[num, num2].liquid > 0)
         {
             AttemptToMoveLava(num, num2, tileAtXYHasLava);
             AttemptToMoveHoney(num, num2, flag);
             AttemptToMoveShimmer(num, num2, flag2);
         }
         tilesIgnoreWater(ignoreSolids: false);
     }
References AttemptToMoveHoney(), AttemptToMoveLava(), AttemptToMoveShimmer(), WorldGen.gen, Tile.honey(), Tile.lava(), GenVars.lavaLine, Tile.liquid, Tile.liquidType(), Main.maxTilesX, Main.maxTilesY, Tile.nactive(), WorldGen.oceanDepths(), WorldGen.remixWorldGen, Tile.shimmer(), Main.tile, tilesIgnoreWater(), Main.tileSolid, Main.tileSolidTop, Tile.type, and GenVars.waterLine.
Referenced by QuickWater().