Terraria: Liquid.UpdateLiquid
UpdateLiquid()
static void Liquid.UpdateLiquid () inline static
     {
         int num = 8;
         tilesIgnoreWater(ignoreSolids: true);
         if (Main.netMode == 2)
         {
             int num2 = 0;
             for (int i = 0; i < 15; i++)
             {
                 if (Main.player[i].active)
                 {
                     num2++;
                 }
             }
             cycles = 10 + num2 / 3;
             curMaxLiquid = maxLiquid - num2 * 250;
             num = 10 + num2 / 3;
             if (Main.Setting_UseReducedMaxLiquids)
             {
                 curMaxLiquid = 5000;
             }
         }
         if (!WorldGen.gen)
         {
             if (!panicMode)
             {
                 if ((double)LiquidBuffer.numLiquidBuffer >= 45000.0)
                 {
                     panicCounter++;
                     if (panicCounter > 3600)
                     {
                         StartPanic();
                     }
                 }
                 else
                 {
                     panicCounter = 0;
                 }
             }
             if (panicMode)
             {
                 int num3 = 0;
                 while (panicY >= 3 && num3 < 5)
                 {
                     num3++;
                     QuickWater(0, panicY, panicY);
                     panicY--;
                     if (panicY >= 3)
                     {
                         continue;
                     }
                     Console.WriteLine(Language.GetTextValue("Misc.WaterSettled"));
                     panicCounter = 0;
                     panicMode = false;
                     WorldGen.WaterCheck();
                     if (Main.netMode != 2)
                     {
                         continue;
                     }
                     for (int j = 0; j < 255; j++)
                     {
                         for (int k = 0; k < Main.maxSectionsX; k++)
{
                             for (int l = 0; l < Main.maxSectionsY; l++)
{
                                 Netplay.Clients[j].TileSections[k, l] = false;
                             }
                         }
                     }
                 }
                 return;
             }
         }
         bool flag = quickSettle;
         if (Main.Setting_UseReducedMaxLiquids)
         {
             flag |= numLiquid > 2000;
         }
         if (flag)
         {
             quickFall = true;
         }
         else
         {
             quickFall = false;
         }
         wetCounter++;
         int num4 = curMaxLiquid / cycles;
         int num5 = num4 * (wetCounter - 1);
         int num6 = num4 * wetCounter;
         if (wetCounter == cycles)
         {
             num6 = numLiquid;
         }
         if (num6 > numLiquid)
         {
             num6 = numLiquid;
             _ = Main.netMode;
             wetCounter = cycles;
         }
         if (quickFall)
         {
             for (int m = num5; m < num6; m++)
             {
                 Main.liquid[m].delay = 10;
                 Main.liquid[m].Update();
                 Main.tile[Main.liquid[m].x, Main.liquid[m].y].skipLiquid(skipLiquid: false);
             }
         }
         else
         {
             for (int n = num5; n < num6; n++)
             {
                 if (!Main.tile[Main.liquid[n].x, Main.liquid[n].y].skipLiquid())
                 {
                     Main.liquid[n].Update();
                 }
                 else
                 {
                     Main.tile[Main.liquid[n].x, Main.liquid[n].y].skipLiquid(skipLiquid: false);
                 }
             }
         }
         if (wetCounter >= cycles)
         {
             wetCounter = 0;
             for (int num7 = numLiquid - 1; num7 >= 0; num7--)
             {
                 if (Main.liquid[num7].kill >= num)
                 {
                     if (Main.tile[Main.liquid[num7].x, Main.liquid[num7].y].liquid == 254)
                     {
                         Main.tile[Main.liquid[num7].x, Main.liquid[num7].y].liquid = byte.MaxValue;
                     }
                     DelWater(num7);
                 }
             }
             int num8 = curMaxLiquid - (curMaxLiquid - numLiquid);
             if (num8 > LiquidBuffer.numLiquidBuffer)
             {
                 num8 = LiquidBuffer.numLiquidBuffer;
             }
             for (int num9 = 0; num9 < num8; num9++)
             {
                 Main.tile[Main.liquidBuffer[0].x, Main.liquidBuffer[0].y].checkingLiquid(checkingLiquid: false);
                 AddWater(Main.liquidBuffer[0].x, Main.liquidBuffer[0].y);
                 LiquidBuffer.DelBuffer(0);
             }
             if (numLiquid > 0 && numLiquid > stuckAmount - 50 && numLiquid < stuckAmount + 50)
             {
                 stuckCount++;
                 if (stuckCount >= 10000)
                 {
                     stuck = true;
                     for (int num10 = numLiquid - 1; num10 >= 0; num10--)
                     {
                         DelWater(num10);
                     }
                     stuck = false;
                     stuckCount = 0;
                 }
             }
             else
             {
                 stuckCount = 0;
                 stuckAmount = numLiquid;
             }
         }
         if (!WorldGen.gen && Main.netMode == 2 && _netChangeSet.Count > 0)
         {
             Utils.Swap(ref _netChangeSet, ref _swapNetChangeSet);
             NetLiquidModule.CreateAndBroadcastByChunk(_swapNetChangeSet);
             _swapNetChangeSet.Clear();
         }
         tilesIgnoreWater(ignoreSolids: false);
     }
References _netChangeSet, _swapNetChangeSet, Entity.active, AddWater(), Tile.checkingLiquid(), Netplay.Clients, NetLiquidModule.CreateAndBroadcastByChunk(), curMaxLiquid, cycles, LiquidBuffer.DelBuffer(), DelWater(), WorldGen.gen, Language.GetTextValue(), Main.liquid, Tile.liquid, Main.liquidBuffer, maxLiquid, Main.maxSectionsX, Main.maxSectionsY, Main.netMode, numLiquid, LiquidBuffer.numLiquidBuffer, panicCounter, panicMode, panicY, Main.player, quickFall, quickSettle, QuickWater(), Main.Setting_UseReducedMaxLiquids, Tile.skipLiquid(), StartPanic(), stuck, stuckAmount, stuckCount, Main.tile, RemoteClient.TileSections, tilesIgnoreWater(), WorldGen.WaterCheck(), wetCounter, LiquidBuffer.x, and LiquidBuffer.y.