Terraria: Liquid.AddWater
AddWater()
static void Liquid.AddWater (int x, int y) inline static
     {
         Tile tile = Main.tile[x, y];
         if (Main.tile[x, y] == null || tile.checkingLiquid() || x >= Main.maxTilesX - 5 || y >= Main.maxTilesY - 5 || x < 5 || y < 5 || tile.liquid == 0 || (tile.nactive() && Main.tileSolid[tile.type] && tile.type != 546 && !Main.tileSolidTop[tile.type]))
         {
             return;
         }
         if (numLiquid >= curMaxLiquid - 1)
         {
             LiquidBuffer.AddBuffer(x, y);
             return;
         }
         tile.checkingLiquid(checkingLiquid: true);
         tile.skipLiquid(skipLiquid: false);
         Main.liquid[numLiquid].kill = 0;
         Main.liquid[numLiquid].x = x;
         Main.liquid[numLiquid].y = y;
         Main.liquid[numLiquid].delay = 0;
         numLiquid++;
         if (Main.netMode == 2)
         {
             NetSendLiquid(x, y);
         }
         if (!tile.active() || WorldGen.gen)
         {
             return;
         }
         bool flag = false;
         if (tile.lava())
         {
             if (TileObjectData.CheckLavaDeath(tile))
             {
                 flag = true;
             }
         }
         else if (TileObjectData.CheckWaterDeath(tile))
         {
             flag = true;
         }
         if (flag)
         {
             WorldGen.KillTile(x, y);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x, y);
             }
         }
     }
References Tile.active(), LiquidBuffer.AddBuffer(), Tile.checkingLiquid(), TileObjectData.CheckLavaDeath(), TileObjectData.CheckWaterDeath(), curMaxLiquid, WorldGen.gen, WorldGen.KillTile(), Tile.lava(), Main.liquid, Tile.liquid, Main.maxTilesX, Main.maxTilesY, Tile.nactive(), Main.netMode, NetSendLiquid(), numLiquid, NetMessage.SendData(), Tile.skipLiquid(), Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.type, x, and y.
Referenced by DelWater(), Update(), and UpdateLiquid().