Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult
GetResult() [3/3]
long Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult (short token) inline
Implements System.Threading.Tasks.Sources.IValueTaskSource< out TResult >.
Definition at line 72 of file SafeFileHandle.cs.
        {
            try
            {
                return _source.GetResult(token);
            }
            finally
            {
                _source.Reset();
                Volatile.Write(ref _fileHandle._reusableThreadPoolValueTaskSource, this);
            }
        }
References Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._fileHandle, Microsoft.Win32.SafeHandles.SafeFileHandle._reusableThreadPoolValueTaskSource, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._source, System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.GetResult(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.Reset(), and System.Threading.Volatile.Write().