Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.QueueToThreadPool
QueueToThreadPool()
void Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.QueueToThreadPool () inline private
Definition at line 165 of file SafeFileHandle.cs.
        {
            _context = ExecutionContext.Capture();
            ThreadPool.UnsafeQueueUserWorkItem(this, preferLocal: true);
        }
References Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._context, System.Threading.ExecutionContext.Capture(), and System.Threading.ThreadPool.UnsafeQueueUserWorkItem().
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.QueueRead(), Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.QueueReadScatter(), Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.QueueWrite(), and Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.QueueWriteGather().