Terraria: Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal
ExecuteInternal()
void Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal () inline private
Definition at line 85 of file SafeFileHandle.cs.
        {
            long num = 0L;
            Exception ex = null;
            try
            {
                if (_cancellationToken.IsCancellationRequested)
                {
                    ex = new OperationCanceledException(_cancellationToken);
                }
                else
                {
                    switch (_operation)
                    {
                    case Operation.Read:
                    {
                        Memory<byte> memory = MemoryMarshal.AsMemory(_singleSegment);
                        num = RandomAccess.ReadAtOffset(_fileHandle, memory.Span, _fileOffset);
                        break;
                    }
                    case Operation.Write:
                        RandomAccess.WriteAtOffset(_fileHandle, _singleSegment.Span, _fileOffset);
                        break;
                    case Operation.ReadScatter:
                        num = RandomAccess.ReadScatterAtOffset(_fileHandle, _readScatterBuffers, _fileOffset);
                        break;
                    case Operation.WriteGather:
                        RandomAccess.WriteGatherAtOffset(_fileHandle, _writeGatherBuffers, _fileOffset);
                        break;
                    }
                }
            }
            catch (Exception ex2)
            {
                ex = ex2;
            }
            finally
            {
                if (_strategy != null)
                {
                    if (ex != null)
                    {
                        _strategy.OnIncompleteOperation(_singleSegment.Length, 0);
                    }
                    else if (_operation == Operation.Read && num != _singleSegment.Length)
                    {
                        _strategy.OnIncompleteOperation(_singleSegment.Length, (int)num);
                    }
                }
                _operation = Operation.None;
                _context = null;
                _strategy = null;
                _cancellationToken = default(CancellationToken);
                _singleSegment = default(ReadOnlyMemory<byte>);
                _readScatterBuffers = null;
                _writeGatherBuffers = null;
            }
            if (ex == null)
            {
                _source.SetResult(num);
            }
            else
            {
                _source.SetException(ex);
            }
        }
References Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._cancellationToken, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._context, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._fileHandle, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._fileOffset, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._operation, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._readScatterBuffers, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._singleSegment, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._source, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._strategy, Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource._writeGatherBuffers, System.Threading.CancellationToken.IsCancellationRequested, System.L, System.ReadOnlyMemory< T >.Length, System.IO.Strategies.OSFileStreamStrategy.OnIncompleteOperation(), System.IO.RandomAccess.ReadAtOffset(), System.IO.RandomAccess.ReadScatterAtOffset(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetException(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.SetResult(), System.ReadOnlyMemory< T >.Span, System.IO.RandomAccess.WriteAtOffset(), and System.IO.RandomAccess.WriteGatherAtOffset().
Referenced by Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.Execute().