Terraria: DeadMansChestBiome.TurnGoldChestIntoDeadMansChest
TurnGoldChestIntoDeadMansChest()
void DeadMansChestBiome.TurnGoldChestIntoDeadMansChest (Point position) inline private
     {
         for (int i = 0; i < 2; i++)
         {
             for (int j = 0; j < 2; j++)
             {
                 int num = position.X + i;
                 int num2 = position.Y + j;
                 Tile tile = Main.tile[num, num2];
                 tile.type = 467;
                 tile.frameX = (short)(144 + i * 18);
                 tile.frameY = (short)(j * 18);
             }
         }
         if (GenBase._random.Next(3) != 0)
         {
             return;
         }
         int num3 = Chest.FindChest(position.X, position.Y);
         if (num3 <= -1)
         {
             return;
         }
         Item[] item = Main.chest[num3].item;
         for (int num4 = item.Length - 2; num4 > 0; num4--)
         {
             Item item2 = item[num4];
             if (item2.stack != 0)
             {
                 item[num4 + 1] = item2.DeepClone();
             }
         }
         item[1] = new Item();
         item[1].SetDefaults(5007);
         Main.chest[num3].item = item;
     }
References GenBase._random, Main.chest, Item.DeepClone(), Chest.FindChest(), Tile.frameX, Tile.frameY, Chest.item, UnifiedRandom.Next(), Item.SetDefaults(), Item.stack, Main.tile, and Tile.type.
Referenced by Place().