Terraria: DeadMansChestBiome.IsAGoodSpot
IsAGoodSpot()
static bool DeadMansChestBiome.IsAGoodSpot (Point position) inline static private
     {
         if (!WorldGen.InWorld(position.X, position.Y, 50))
         {
             return false;
         }
         if (WorldGen.oceanDepths(position.X, position.Y))
         {
             return false;
         }
         Tile tile = Main.tile[position.X, position.Y];
         if (tile.type != 21)
         {
             return false;
         }
         if (tile.frameX / 36 != 1)
         {
             return false;
         }
         tile = Main.tile[position.X, position.Y + 2];
         if (!TileID.Sets.CanBeClearedDuringGeneration[tile.type])
         {
             return false;
         }
         if (WorldGen.countWires(position.X, position.Y, 20) > 0)
         {
             return false;
         }
         if (WorldGen.countTiles(position.X, position.Y, jungle: false, lavaOk: true) < 40)
         {
             return false;
         }
         return true;
     }
References TileID.Sets.CanBeClearedDuringGeneration, WorldGen.countTiles(), WorldGen.countWires(), Tile.frameX, WorldGen.InWorld(), WorldGen.oceanDepths(), Main.tile, and Tile.type.
Referenced by GetPossibleChestsToTrapify(), and Place().