Terraria: DeadMansChestBiome.Place
Place()
override bool DeadMansChestBiome.Place (Point origin, StructureMap structures) inline virtual
Implements GenStructure.
     {
         if (!IsAGoodSpot(origin))
         {
             return false;
         }
         ClearCaches();
         Point position = new Point(origin.X, origin.Y + 1);
         FindBoulderTrapSpots(position);
         FindDartTrapSpots(position);
         FindExplosiveTrapSpots(position);
         if (!AreThereEnoughTraps())
         {
             return false;
         }
         TurnGoldChestIntoDeadMansChest(origin);
         foreach (DartTrapPlacementAttempt dartTrapPlacementSpot in _dartTrapPlacementSpots)
         {
             ActuallyPlaceDartTrap(dartTrapPlacementSpot.position, dartTrapPlacementSpot.directionX, dartTrapPlacementSpot.x, dartTrapPlacementSpot.y, dartTrapPlacementSpot.xPush, dartTrapPlacementSpot.t);
         }
         foreach (WirePlacementAttempt wirePlacementSpot in _wirePlacementSpots)
         {
             PlaceWireLine(wirePlacementSpot.position, wirePlacementSpot.dirX, wirePlacementSpot.dirY, wirePlacementSpot.steps);
         }
         foreach (BoulderPlacementAttempt boulderPlacementSpot in _boulderPlacementSpots)
         {
             ActuallyPlaceBoulderTrap(boulderPlacementSpot.position, boulderPlacementSpot.yPush, boulderPlacementSpot.requiredHeight, boulderPlacementSpot.bestType);
         }
         foreach (ExplosivePlacementAttempt item in _explosivePlacementAttempt)
         {
             ActuallyPlaceExplosive(item.position);
         }
         PlaceWiresForExplosives(origin);
         return true;
     }
References _boulderPlacementSpots, _dartTrapPlacementSpots, _explosivePlacementAttempt, _wirePlacementSpots, ActuallyPlaceBoulderTrap(), ActuallyPlaceDartTrap(), ActuallyPlaceExplosive(), AreThereEnoughTraps(), DeadMansChestBiome.BoulderPlacementAttempt.bestType, ClearCaches(), DeadMansChestBiome.DartTrapPlacementAttempt.directionX, DeadMansChestBiome.WirePlacementAttempt.dirX, DeadMansChestBiome.WirePlacementAttempt.dirY, FindBoulderTrapSpots(), FindDartTrapSpots(), FindExplosiveTrapSpots(), IsAGoodSpot(), PlaceWireLine(), PlaceWiresForExplosives(), DeadMansChestBiome.DartTrapPlacementAttempt.position, DeadMansChestBiome.BoulderPlacementAttempt.position, DeadMansChestBiome.WirePlacementAttempt.position, DeadMansChestBiome.ExplosivePlacementAttempt.position, DeadMansChestBiome.BoulderPlacementAttempt.requiredHeight, DeadMansChestBiome.WirePlacementAttempt.steps, DeadMansChestBiome.DartTrapPlacementAttempt.t, TurnGoldChestIntoDeadMansChest(), DeadMansChestBiome.DartTrapPlacementAttempt.x, DeadMansChestBiome.DartTrapPlacementAttempt.xPush, DeadMansChestBiome.DartTrapPlacementAttempt.y, and DeadMansChestBiome.BoulderPlacementAttempt.yPush.