Terraria: DeadMansChestBiome.FindExplosiveTrapSpots
FindExplosiveTrapSpots()
void DeadMansChestBiome.FindExplosiveTrapSpots (Point position) inline private
     {
         int x = position.X;
         int y = position.Y + 3;
         List<int> list = new List<int>();
         if (IsGoodSpotsForExplosive(x, y))
         {
             list.Add(x);
         }
         x++;
         if (IsGoodSpotsForExplosive(x, y))
         {
             list.Add(x);
         }
         int num = -1;
         if (list.Count > 0)
         {
             num = list[GenBase._random.Next(list.Count)];
         }
         list.Clear();
         x += GenBase._random.Next(2, 6);
         int num2 = 4;
         for (int i = x; i < x + num2; i++)
         {
             if (IsGoodSpotsForExplosive(i, y))
             {
                 list.Add(i);
             }
         }
         int num3 = -1;
         if (list.Count > 0)
         {
             num3 = list[GenBase._random.Next(list.Count)];
         }
         x = position.X - num2 - GenBase._random.Next(2, 6);
         for (int j = x; j < x + num2; j++)
         {
             if (IsGoodSpotsForExplosive(j, y))
             {
                 list.Add(j);
             }
         }
         int num4 = -1;
         if (list.Count > 0)
         {
             num4 = list[GenBase._random.Next(list.Count)];
         }
         if (num4 != -1)
         {
             _explosivePlacementAttempt.Add(new ExplosivePlacementAttempt(new Point(num4, y)));
         }
         if (num != -1)
         {
             _explosivePlacementAttempt.Add(new ExplosivePlacementAttempt(new Point(num, y)));
         }
         if (num3 != -1)
         {
             _explosivePlacementAttempt.Add(new ExplosivePlacementAttempt(new Point(num3, y)));
         }
     }
References _explosivePlacementAttempt, GenBase._random, IsGoodSpotsForExplosive(), and UnifiedRandom.Next().
Referenced by Place().