Terraria: DeadMansChestBiome.GetPossibleChestsToTrapify
GetPossibleChestsToTrapify()
List<int> DeadMansChestBiome.GetPossibleChestsToTrapify (StructureMap structures) inline
     {
         List<int> list = new List<int>();
         bool[] array = new bool[TileID.Sets.GeneralPlacementTiles.Length];
         for (int i = 0; i < array.Length; i++)
         {
             array[i] = TileID.Sets.GeneralPlacementTiles[i];
         }
         array[21] = true;
         array[467] = true;
         for (int j = 0; j < 8000; j++)
         {
             Chest chest = Main.chest[j];
             if (chest == null)
             {
                 continue;
             }
             Point position = new Point(chest.x, chest.y);
             if (IsAGoodSpot(position))
             {
                 ClearCaches();
                 Point position2 = new Point(position.X, position.Y + 1);
                 FindBoulderTrapSpots(position2);
                 FindDartTrapSpots(position2);
                 if (AreThereEnoughTraps() && (structures == null || structures.CanPlace(new Rectangle(position.X, position.Y, 1, 1), array, 10)))
                 {
                     list.Add(j);
                 }
             }
         }
         return list;
     }
References AreThereEnoughTraps(), StructureMap.CanPlace(), Main.chest, ClearCaches(), FindBoulderTrapSpots(), FindDartTrapSpots(), TileID.Sets.GeneralPlacementTiles, IsAGoodSpot(), Chest.x, and Chest.y.