Terraria: System.Text.ISO2022Encoding.GetChars
GetChars() [2/6]
unsafe override int System.Text.ISO2022Encoding.GetChars (byte * bytes, int byteCount, char * chars, int charCount, System::Text::DecoderNLS baseDecoder) inline virtual
Reimplemented from System.Text.DBCSCodePageEncoding.
Definition at line 259 of file ISO2022Encoding.cs.
    {
        ISO2022Decoder decoder = (ISO2022Decoder)baseDecoder;
        int result = 0;
        switch (CodePage)
        {
        case 50220:
        case 50221:
        case 50222:
            result = GetCharsCP5022xJP(bytes, byteCount, chars, charCount, decoder);
            break;
        case 50225:
            result = GetCharsCP50225KR(bytes, byteCount, chars, charCount, decoder);
            break;
        case 52936:
            result = GetCharsCP52936(bytes, byteCount, chars, charCount, decoder);
            break;
        }
        return result;
    }
References System.byteCount, System.bytes, System.charCount, System.chars, System.Text.Encoding.CodePage, System.Text.ISO2022Encoding.GetCharsCP50225KR(), System.Text.ISO2022Encoding.GetCharsCP5022xJP(), and System.Text.ISO2022Encoding.GetCharsCP52936().
Referenced by System.Text.ISO2022Encoding.GetCharCount().