Terraria: Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea
GetScreenDrawArea()
void Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea (Vector2 screenPosition, Vector2 offSet, out int firstTileX, out int lastTileX, out int firstTileY, out int lastTileY) inline private
Definition at line 5592 of file TileDrawing.cs.
    {
        firstTileX = (int)((screenPosition.X - offSet.X) / 16f - 1f);
        lastTileX = (int)((screenPosition.X + (float)Main.screenWidth + offSet.X) / 16f) + 2;
        firstTileY = (int)((screenPosition.Y - offSet.Y) / 16f - 1f);
        lastTileY = (int)((screenPosition.Y + (float)Main.screenHeight + offSet.Y) / 16f) + 5;
        if (firstTileX < 4)
        {
            firstTileX = 4;
        }
        if (lastTileX > Main.maxTilesX - 4)
        {
            lastTileX = Main.maxTilesX - 4;
        }
        if (firstTileY < 4)
        {
            firstTileY = 4;
        }
        if (lastTileY > Main.maxTilesY - 4)
        {
            lastTileY = Main.maxTilesY - 4;
        }
        if (Main.sectionManager.AnyUnfinishedSections)
        {
            TimeLogger.DetailedDrawReset();
            WorldGen.SectionTileFrameWithCheck(firstTileX, firstTileY, lastTileX, lastTileY);
            TimeLogger.DetailedDrawTime(5);
        }
        if (Main.sectionManager.AnyNeedRefresh)
        {
            WorldGen.RefreshSections(firstTileX, firstTileY, lastTileX, lastTileY);
        }
    }
References Terraria.WorldSections.AnyNeedRefresh, Terraria.WorldSections.AnyUnfinishedSections, Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.RefreshSections(), Terraria.Main.sectionManager, and Terraria.WorldGen.SectionTileFrameWithCheck().
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles(), Terraria.GameContent.Drawing.TileDrawing.EnsureWindGridSize(), and Terraria.GameContent.Drawing.TileDrawing.PreparePaintForTilesOnScreen().