Terraria: System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState
ThrowIfInvalidState()
static void System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState (WebSocketState currentState, bool isDisposed, WebSocketState[] validStates) inline static package
Definition at line 7 of file WebSocketValidate.cs.
    {
        string p = string.Empty;
        if (validStates != null && validStates.Length != 0)
        {
            foreach (WebSocketState webSocketState in validStates)
            {
                if (currentState == webSocketState)
                {
                    if (isDisposed)
                    {
                        throw new ObjectDisposedException("WebSocket");
                    }
                    return;
                }
            }
            p = string.Join(", ", validStates);
        }
        throw new WebSocketException(WebSocketError.InvalidState, System.SR.Format(System.SR.net_WebSockets_InvalidState, currentState, p));
    }
References System.SR.Format(), and System.SR.net_WebSockets_InvalidState.
Referenced by System.Net.WebSockets.ManagedWebSocket.CloseAsync(), System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(), System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(), System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(), and System.Net.WebSockets.ManagedWebSocket.SendAsync().