Terraria: Terraria.GameContent.Drawing.TileDrawing.Draw
Draw()
void Terraria.GameContent.Drawing.TileDrawing.Draw (bool solidLayer, bool forRenderTargets, bool intoRenderTargets, int waterStyleOverride = -1) inline
    {
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        _isActiveAndNotPaused = !Main.gamePaused && Main.instance.IsActive;
        _localPlayer = Main.LocalPlayer;
        Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
        Vector2 vector = new Vector2(Main.offScreenRange, Main.offScreenRange);
        if (Main.drawToScreen)
        {
            vector = Vector2.Zero;
        }
        if (!solidLayer)
        {
            Main.critterCage = false;
        }
        EnsureWindGridSize();
        ClearLegacyCachedDraws();
        bool flag = intoRenderTargets || Main.LightingEveryFrame;
        if (flag)
        {
            ClearCachedTileDraws(solidLayer);
        }
        float num = 255f * (1f - Main.gfxQuality) + 30f * Main.gfxQuality;
        _highQualityLightingRequirement.R = (byte)num;
        _highQualityLightingRequirement.G = (byte)((double)num * 1.1);
        _highQualityLightingRequirement.B = (byte)((double)num * 1.2);
        float num2 = 50f * (1f - Main.gfxQuality) + 2f * Main.gfxQuality;
        _mediumQualityLightingRequirement.R = (byte)num2;
        _mediumQualityLightingRequirement.G = (byte)((double)num2 * 1.1);
        _mediumQualityLightingRequirement.B = (byte)((double)num2 * 1.2);
        GetScreenDrawArea(unscaledPosition, vector + (Main.Camera.UnscaledPosition - Main.Camera.ScaledPosition), out var firstTileX, out var lastTileX, out var firstTileY, out var lastTileY);
        byte b = (byte)(100f + 150f * Main.martianLight);
        _martianGlow = new Color(b, b, b, 0);
        TileDrawInfo value = _currentTileDrawInfo.Value;
        for (int i = firstTileY; i < lastTileY + 4; i++)
        {
            for (int j = firstTileX - 2; j < lastTileX + 2; j++)
            {
                Tile tile = Main.tile[j, i];
                if (tile == null)
                {
                    tile = new Tile();
                    Main.tile[j, i] = tile;
                    Main.mapTime += 60;
                }
                else
                {
                    if (!tile.active() || IsTileDrawLayerSolid(tile.type) != solidLayer)
                    {
                        continue;
                    }
                    if (solidLayer)
                    {
                        DrawTile_LiquidBehindTile(solidLayer, inFrontOfPlayers: false, waterStyleOverride, unscaledPosition, vector, j, i, tile);
                    }
                    ushort type = tile.type;
                    short frameX = tile.frameX;
                    short frameY = tile.frameY;
                    if (!TextureAssets.Tile[type].IsLoaded)
                    {
                        Main.instance.LoadTiles(type);
                    }
                    switch (type)
                    {
                    case 52:
                    case 62:
                    case 115:
                    case 205:
                    case 382:
                    case 528:
                    case 636:
                    case 638:
                        if (flag)
{
                            CrawlToTopOfVineAndAddSpecialPoint(i, j);
                        }
                        continue;
                    case 549:
                        if (flag)
{
                            CrawlToBottomOfReverseVineAndAddSpecialPoint(i, j);
                        }
                        continue;
                    case 34:
                        if (frameX % 54 == 0 && frameY % 54 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileVine);
                        }
                        continue;
                    case 454:
                        if (frameX % 72 == 0 && frameY % 54 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileVine);
                        }
                        continue;
                    case 42:
                    case 270:
                    case 271:
                    case 572:
                    case 581:
                    case 660:
                        if (frameX % 18 == 0 && frameY % 36 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileVine);
                        }
                        continue;
                    case 91:
                        if (frameX % 18 == 0 && frameY % 54 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileVine);
                        }
                        continue;
                    case 95:
                    case 126:
                    case 444:
                        if (frameX % 36 == 0 && frameY % 36 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileVine);
                        }
                        continue;
                    case 465:
                    case 591:
                    case 592:
                        if (frameX % 36 == 0 && frameY % 54 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileVine);
                        }
                        continue;
                    case 27:
                        if (frameX % 36 == 0 && frameY == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 236:
                    case 238:
                        if (frameX % 36 == 0 && frameY == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 233:
                        if (frameY == 0 && frameX % 54 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        if (frameY == 34 && frameX % 36 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 652:
                        if (frameX % 36 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 651:
                        if (frameX % 54 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 530:
                        if (frameX < 270)
{
                            if (frameX % 54 == 0 && frameY == 0 && flag)
{
                                AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                            }
                            continue;
                        }
                        break;
                    case 485:
                    case 489:
                    case 490:
                        if (frameY == 0 && frameX % 36 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 521:
                    case 522:
                    case 523:
                    case 524:
                    case 525:
                    case 526:
                    case 527:
                        if (frameY == 0 && frameX % 36 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 493:
                        if (frameY == 0 && frameX % 18 == 0 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 519:
                        if (frameX / 18 <= 4 && flag)
{
                            AddSpecialPoint(j, i, TileCounterType.MultiTileGrass);
                        }
                        continue;
                    case 373:
                    case 374:
                    case 375:
                    case 461:
                        EmitLiquidDrops(i, j, tile, type);
                        continue;
                    case 491:
                        if (flag && frameX == 18 && frameY == 18)
{
                            AddSpecialPoint(j, i, TileCounterType.VoidLens);
                        }
                        break;
                    case 597:
                        if (flag && frameX % 54 == 0 && frameY == 0)
{
                            AddSpecialPoint(j, i, TileCounterType.TeleportationPylon);
                        }
                        break;
                    case 617:
                        if (flag && frameX % 54 == 0 && frameY % 72 == 0)
{
                            AddSpecialPoint(j, i, TileCounterType.MasterTrophy);
                        }
                        break;
                    case 184:
                        if (flag)
{
                            AddSpecialPoint(j, i, TileCounterType.AnyDirectionalGrass);
                        }
                        continue;
                    default:
                        if (ShouldSwayInWind(j, i, tile))
{
                            if (flag)
{
                                AddSpecialPoint(j, i, TileCounterType.WindyGrass);
                            }
                            continue;
                        }
                        break;
                    }
                    DrawSingleTile(value, solidLayer, waterStyleOverride, unscaledPosition, vector, j, i);
                }
            }
        }
        if (solidLayer)
        {
            Main.instance.DrawTileCracks(1, Main.player[Main.myPlayer].hitReplace);
            Main.instance.DrawTileCracks(1, Main.player[Main.myPlayer].hitTile);
        }
        DrawSpecialTilesLegacy(unscaledPosition, vector);
        if (TileObject.objectPreview.Active && _localPlayer.cursorItemIconEnabled && Main.placementPreview && !CaptureManager.Instance.Active)
        {
            Main.instance.LoadTiles(TileObject.objectPreview.Type);
            TileObject.DrawPreview(Main.spriteBatch, TileObject.objectPreview, unscaledPosition - vector);
        }
        if (solidLayer)
        {
            TimeLogger.DrawTime(0, stopwatch.Elapsed.TotalMilliseconds);
        }
        else
        {
            TimeLogger.DrawTime(1, stopwatch.Elapsed.TotalMilliseconds);
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._currentTileDrawInfo, Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._localPlayer, Terraria.GameContent.Drawing.TileDrawing._martianGlow, Terraria.DataStructures.TileObjectPreviewData.Active, Terraria.Graphics.Capture.CaptureManager.Active, Terraria.Tile.active(), Terraria.GameContent.Drawing.TileDrawing.AddSpecialPoint(), Terraria.Main.Camera, Terraria.GameContent.Drawing.TileDrawing.ClearCachedTileDraws(), Terraria.GameContent.Drawing.TileDrawing.ClearLegacyCachedDraws(), Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), Terraria.GameContent.Drawing.TileDrawing.CrawlToTopOfVineAndAddSpecialPoint(), Terraria.Player.cursorItemIconEnabled, Terraria.TileObject.DrawPreview(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.DrawTileCracks(), Terraria.TimeLogger.DrawTime(), Terraria.Main.drawToScreen, Terraria.GameContent.Drawing.TileDrawing.EmitLiquidDrops(), Terraria.GameContent.Drawing.TileDrawing.EnsureWindGridSize(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.Main.gfxQuality, Terraria.Player.hitReplace, Terraria.Player.hitTile, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Main.instance, ReLogic.Content.Asset< T >.IsLoaded, Terraria.GameContent.Drawing.TileDrawing.IsTileDrawLayerSolid(), Terraria.Main.LightingEveryFrame, Terraria.Main.LoadTiles(), Terraria.Main.LocalPlayer, Terraria.Main.martianLight, Terraria.Main.myPlayer, Terraria.TileObject.objectPreview, Terraria.Main.offScreenRange, Terraria.Main.placementPreview, Terraria.Main.player, Terraria.Graphics.Camera.ScaledPosition, Terraria.GameContent.Drawing.TileDrawing.ShouldSwayInWind(), Terraria.Main.spriteBatch, Terraria.DataStructures.Tile, Terraria.GameContent.TextureAssets.Tile, Terraria.Main.tile, Terraria.DataStructures.TileObjectPreviewData.Type, Terraria.Tile.type, and Terraria.Graphics.Camera.UnscaledPosition.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks(), and Terraria.Main.DrawTiles().