Terraria: Terraria.GameContent.Drawing.TileDrawing.CrawlToTopOfVineAndAddSpecialPoint
CrawlToTopOfVineAndAddSpecialPoint()
void Terraria.GameContent.Drawing.TileDrawing.CrawlToTopOfVineAndAddSpecialPoint (int j, int i) inline private
Definition at line 720 of file TileDrawing.cs.
    {
        int y = j;
        for (int num = j - 1; num > 0; num--)
        {
            Tile tile = Main.tile[i, num];
            if (WorldGen.SolidTile(i, num) || !tile.active())
            {
                y = num + 1;
                break;
            }
        }
        Point item = new Point(i, y);
        if (!_vineRootsPositions.Contains(item))
        {
            _vineRootsPositions.Add(item);
            AddSpecialPoint(i, y, TileCounterType.Vine);
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._vineRootsPositions, Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Drawing.TileDrawing.AddSpecialPoint(), System.Collections.Generic.List< T >.Contains(), System.item, Microsoft.Xna.Framework.Graphics.Point, Terraria.WorldGen.SolidTile(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().