Terraria: System.Text.ISO2022Encoding.GetCharsCP5022xJP
GetCharsCP5022xJP()
unsafe int System.Text.ISO2022Encoding.GetCharsCP5022xJP (byte * bytes, int byteCount, char * chars, int charCount, ISO2022Decoder decoder) inline private
Definition at line 614 of file ISO2022Encoding.cs.
    {
        EncodingCharBuffer encodingCharBuffer = new EncodingCharBuffer(this, decoder, chars, charCount, bytes, byteCount);
        ISO2022Modes iSO2022Modes = ISO2022Modes.ModeASCII;
        ISO2022Modes iSO2022Modes2 = ISO2022Modes.ModeASCII;
        byte[] bytes2 = new byte[4];
        int count = 0;
        if (decoder != null)
        {
            iSO2022Modes = decoder.currentMode;
            iSO2022Modes2 = decoder.shiftInOutMode;
            count = decoder.bytesLeftOverCount;
            for (int i = 0; i < count; i++)
            {
                bytes2[i] = decoder.bytesLeftOver[i];
            }
        }
        while (encodingCharBuffer.MoreData || count > 0)
        {
            byte b;
            if (count > 0)
            {
                if (bytes2[0] == 27)
                {
                    if (!encodingCharBuffer.MoreData)
                    {
                        if (decoder != null && !decoder.MustFlush)
{
                            break;
                        }
                    }
                    else
                    {
                        bytes2[count++] = encodingCharBuffer.GetNextByte();
                        ISO2022Modes iSO2022Modes3 = CheckEscapeSequenceJP(bytes2, count);
                        switch (iSO2022Modes3)
{
                        default:
                            count = 0;
                            iSO2022Modes = (iSO2022Modes2 = iSO2022Modes3);
                            continue;
                        case ISO2022Modes.ModeInvalidEscape:
                            break;
                        case ISO2022Modes.ModeIncompleteEscape:
                            continue;
                        }
                    }
                }
                b = DecrementEscapeBytes(ref bytes2, ref count);
            }
            else
            {
                b = encodingCharBuffer.GetNextByte();
                if (b == 27)
                {
                    if (count == 0)
                    {
                        bytes2[0] = b;
                        count = 1;
                        continue;
                    }
                    encodingCharBuffer.AdjustBytes(-1);
                }
            }
            switch (b)
            {
            case 14:
                iSO2022Modes2 = iSO2022Modes;
                iSO2022Modes = ISO2022Modes.ModeHalfwidthKatakana;
                continue;
            case 15:
                iSO2022Modes = iSO2022Modes2;
                continue;
            }
            ushort num = b;
            bool flag = false;
            if (iSO2022Modes == ISO2022Modes.ModeJIS0208)
            {
                if (count > 0)
                {
                    if (bytes2[0] != 27)
                    {
                        num <<= 8;
                        num |= DecrementEscapeBytes(ref bytes2, ref count);
                        flag = true;
                    }
                }
                else
                {
                    if (!encodingCharBuffer.MoreData)
                    {
                        if (decoder == null || decoder.MustFlush)
{
                            encodingCharBuffer.Fallback(b);
                        }
                        else if (chars != null)
{
                            bytes2[0] = b;
                            count = 1;
                        }
                        break;
                    }
                    num <<= 8;
                    num |= encodingCharBuffer.GetNextByte();
                    flag = true;
                }
                if (flag && (num & 0xFF00) == 10752)
                {
                    num = (ushort)(num & 0xFFu);
                    num = (ushort)(num | 0x1000u);
                }
            }
            else if (num >= 161 && num <= 223)
            {
                num = (ushort)(num | 0x1000u);
                num = (ushort)(num & 0xFF7Fu);
            }
            else if (iSO2022Modes == ISO2022Modes.ModeHalfwidthKatakana)
            {
                num = (ushort)(num | 0x1000u);
            }
            char c = mapBytesToUnicode[(int)num];
            if (c == '\0' && num != 0)
            {
                if (flag)
                {
                    if (!encodingCharBuffer.Fallback((byte)(num >> 8), (byte)num))
                    {
                        break;
                    }
                }
                else if (!encodingCharBuffer.Fallback(b))
                {
                    break;
                }
            }
            else if (!encodingCharBuffer.AddChar(c, (!flag) ? 1 : 2))
            {
                break;
            }
        }
        if (chars != null && decoder != null)
        {
            if (!decoder.MustFlush || count != 0)
            {
                decoder.currentMode = iSO2022Modes;
                decoder.shiftInOutMode = iSO2022Modes2;
                decoder.bytesLeftOverCount = count;
                decoder.bytesLeftOver = bytes2;
            }
            else
            {
                decoder.currentMode = ISO2022Modes.ModeASCII;
                decoder.shiftInOutMode = ISO2022Modes.ModeASCII;
                decoder.bytesLeftOverCount = 0;
            }
            decoder.m_bytesUsed = encodingCharBuffer.BytesUsed;
        }
        return encodingCharBuffer.Count;
    }
References System.Text.Encoding.EncodingCharBuffer.AddChar(), System.Text.Encoding.EncodingCharBuffer.AdjustBytes(), System.byteCount, System.bytes, System.Text.ISO2022Encoding.ISO2022Decoder.bytesLeftOver, System.Text.ISO2022Encoding.ISO2022Decoder.bytesLeftOverCount, System.Text.Encoding.EncodingCharBuffer.BytesUsed, System.charCount, System.chars, System.Text.ISO2022Encoding.CheckEscapeSequenceJP(), System.count, System.Text.Encoding.EncodingCharBuffer.Count, System.Text.ISO2022Encoding.ISO2022Decoder.currentMode, System.Text.ISO2022Encoding.DecrementEscapeBytes(), System.Text.Encoding.EncodingCharBuffer.Fallback(), System.Text.Encoding.EncodingCharBuffer.GetNextByte(), System.Text.DBCSCodePageEncoding.mapBytesToUnicode, System.Text.Encoding.EncodingCharBuffer.MoreData, System.Text.DecoderNLS.MustFlush, and System.Text.ISO2022Encoding.ISO2022Decoder.shiftInOutMode.
Referenced by System.Text.ISO2022Encoding.GetChars().