Terraria: System.Text.ISO2022Encoding.GetBytesCP52936
GetBytesCP52936()
unsafe int System.Text.ISO2022Encoding.GetBytesCP52936 (char * chars, int charCount, byte * bytes, int byteCount, ISO2022Encoder encoder) inline private
Definition at line 533 of file ISO2022Encoding.cs.
    {
        EncodingByteBuffer encodingByteBuffer = new EncodingByteBuffer(this, encoder, bytes, byteCount, chars, charCount);
        ISO2022Modes iSO2022Modes = ISO2022Modes.ModeASCII;
        if (encoder != null)
        {
            char charLeftOver = encoder.charLeftOver;
            iSO2022Modes = encoder.currentMode;
            if (charLeftOver > '\0')
            {
                encodingByteBuffer.Fallback(charLeftOver);
            }
        }
        while (encodingByteBuffer.MoreData)
        {
            char nextChar = encodingByteBuffer.GetNextChar();
            ushort num = mapUnicodeToBytes[(int)nextChar];
            if (num == 0 && nextChar != 0)
            {
                encodingByteBuffer.Fallback(nextChar);
                continue;
            }
            byte b = (byte)(num >> 8);
            byte b2 = (byte)(num & 0xFFu);
            if ((b != 0 && (b < 161 || b > 247 || b2 < 161 || b2 > 254)) || (b == 0 && b2 > 128 && b2 != byte.MaxValue))
            {
                encodingByteBuffer.Fallback(nextChar);
                continue;
            }
            if (b != 0)
            {
                if (iSO2022Modes != ISO2022Modes.ModeHZ)
                {
                    if (!encodingByteBuffer.AddByte(126, 123, 2))
                    {
                        break;
                    }
                    iSO2022Modes = ISO2022Modes.ModeHZ;
                }
                if (encodingByteBuffer.AddByte((byte)(b & 0x7Fu), (byte)(b2 & 0x7Fu)))
                {
                    continue;
                }
                break;
            }
            if (iSO2022Modes != ISO2022Modes.ModeASCII)
            {
                if (!encodingByteBuffer.AddByte(126, 125, (b2 != 126) ? 1 : 2))
                {
                    break;
                }
                iSO2022Modes = ISO2022Modes.ModeASCII;
            }
            if ((b2 == 126 && !encodingByteBuffer.AddByte(126, 1)) || !encodingByteBuffer.AddByte(b2))
            {
                break;
            }
        }
        if (iSO2022Modes != ISO2022Modes.ModeASCII && (encoder == null || encoder.MustFlush))
        {
            if (encodingByteBuffer.AddByte((byte)126, (byte)125))
            {
                iSO2022Modes = ISO2022Modes.ModeASCII;
            }
            else
            {
                encodingByteBuffer.GetNextChar();
            }
        }
        if (encoder != null && bytes != null)
        {
            encoder.currentMode = iSO2022Modes;
            if (!encodingByteBuffer.fallbackBufferHelper.bUsedEncoder)
            {
                encoder.charLeftOver = '\0';
            }
            encoder.m_charsUsed = encodingByteBuffer.CharsUsed;
        }
        return encodingByteBuffer.Count;
    }
References System.Text.Encoding.EncodingByteBuffer.AddByte(), System.byteCount, System.bytes, System.charCount, System.Text.EncoderNLS.charLeftOver, System.chars, System.Text.Encoding.EncodingByteBuffer.CharsUsed, System.Text.Encoding.EncodingByteBuffer.Count, System.Text.ISO2022Encoding.ISO2022Encoder.currentMode, System.Text.Encoding.EncodingByteBuffer.GetNextChar(), System.Text.DBCSCodePageEncoding.mapUnicodeToBytes, System.Text.Encoding.EncodingByteBuffer.MoreData, and System.Text.EncoderNLS.MustFlush.
Referenced by System.Text.ISO2022Encoding.GetBytes().