Terraria: Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles
PostDrawTiles()
void Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles (bool solidLayer, bool forRenderTargets, bool intoRenderTargets) inline
Definition at line 402 of file TileDrawing.cs.
    {
        if (!solidLayer && !intoRenderTargets)
        {
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, Main.DefaultSamplerState, DepthStencilState.None, Main.Rasterizer, null, Main.Transform);
            DrawMultiTileVines();
            DrawMultiTileGrass();
            DrawVoidLenses();
            DrawTeleportationPylons();
            DrawMasterTrophies();
            DrawGrass();
            DrawAnyDirectionalGrass();
            DrawTrees();
            DrawVines();
            DrawReverseVines();
            Main.spriteBatch.End();
        }
        if (solidLayer && !intoRenderTargets)
        {
            DrawEntities_HatRacks();
            DrawEntities_DisplayDolls();
        }
    }
References Terraria.Main.DefaultSamplerState, Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVines(), Terraria.GameContent.Drawing.TileDrawing.DrawReverseVines(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVines(), Terraria.GameContent.Drawing.TileDrawing.DrawVoidLenses(), Terraria.Main.Rasterizer, Terraria.Main.spriteBatch, and Terraria.Main.Transform.
Referenced by Terraria.Main.DrawTileEntities().