Terraria: Terraria.GameContent.Drawing.TileDrawing.IsAlchemyPlantHarvestable
IsAlchemyPlantHarvestable()
bool Terraria.GameContent.Drawing.TileDrawing.IsAlchemyPlantHarvestable (int style) inline private
    {
        if (style == 0 && Main.dayTime)
        {
            return true;
        }
        if (style == 1 && !Main.dayTime)
        {
            return true;
        }
        if (style == 3 && !Main.dayTime && (Main.bloodMoon || Main.moonPhase == 0))
        {
            return true;
        }
        if (style == 4 && (Main.raining || Main.cloudAlpha > 0f))
        {
            return true;
        }
        if (style == 5 && !Main.raining && Main.time > 40500.0)
        {
            return true;
        }
        return false;
    }
References Terraria.Main.bloodMoon, Terraria.Main.cloudAlpha, Terraria.Main.dayTime, Terraria.Main.moonPhase, Terraria.Main.raining, and Terraria.Main.time.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), and Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture().