Terraria: System.Text.ISO2022Encoding.GetBytesCP50225KR
GetBytesCP50225KR()
unsafe int System.Text.ISO2022Encoding.GetBytesCP50225KR (char * chars, int charCount, byte * bytes, int byteCount, ISO2022Encoder encoder) inline private
Definition at line 438 of file ISO2022Encoding.cs.
    {
        EncodingByteBuffer encodingByteBuffer = new EncodingByteBuffer(this, encoder, bytes, byteCount, chars, charCount);
        ISO2022Modes iSO2022Modes = ISO2022Modes.ModeASCII;
        ISO2022Modes iSO2022Modes2 = ISO2022Modes.ModeASCII;
        if (encoder != null)
        {
            char charLeftOver = encoder.charLeftOver;
            iSO2022Modes = encoder.currentMode;
            iSO2022Modes2 = encoder.shiftInOutMode;
            if (charLeftOver > '\0')
            {
                encodingByteBuffer.Fallback(charLeftOver);
            }
        }
        while (encodingByteBuffer.MoreData)
        {
            char nextChar = encodingByteBuffer.GetNextChar();
            ushort num = mapUnicodeToBytes[(int)nextChar];
            byte b = (byte)(num >> 8);
            byte b2 = (byte)(num & 0xFFu);
            if (b != 0)
            {
                if (iSO2022Modes2 != ISO2022Modes.ModeKR)
                {
                    if (!encodingByteBuffer.AddByte((byte)27, (byte)36, (byte)41, (byte)67))
                    {
                        break;
                    }
                    iSO2022Modes2 = ISO2022Modes.ModeKR;
                }
                if (iSO2022Modes != ISO2022Modes.ModeKR)
                {
                    if (!encodingByteBuffer.AddByte(14))
                    {
                        break;
                    }
                    iSO2022Modes = ISO2022Modes.ModeKR;
                }
                if (!encodingByteBuffer.AddByte(b, b2))
                {
                    break;
                }
            }
            else if (num != 0 || nextChar == '\0')
            {
                if (iSO2022Modes != ISO2022Modes.ModeASCII)
                {
                    if (!encodingByteBuffer.AddByte(15))
                    {
                        break;
                    }
                    iSO2022Modes = ISO2022Modes.ModeASCII;
                }
                if (!encodingByteBuffer.AddByte(b2))
                {
                    break;
                }
            }
            else
            {
                encodingByteBuffer.Fallback(nextChar);
            }
        }
        if (iSO2022Modes != ISO2022Modes.ModeASCII && (encoder == null || encoder.MustFlush))
        {
            if (encodingByteBuffer.AddByte(15))
            {
                iSO2022Modes = ISO2022Modes.ModeASCII;
            }
            else
            {
                encodingByteBuffer.GetNextChar();
            }
        }
        if (bytes != null && encoder != null)
        {
            if (!encodingByteBuffer.fallbackBufferHelper.bUsedEncoder)
            {
                encoder.charLeftOver = '\0';
            }
            encoder.currentMode = iSO2022Modes;
            if (!encoder.MustFlush || encoder.charLeftOver != 0)
            {
                encoder.shiftInOutMode = iSO2022Modes2;
            }
            else
            {
                encoder.shiftInOutMode = ISO2022Modes.ModeASCII;
            }
            encoder.m_charsUsed = encodingByteBuffer.CharsUsed;
        }
        return encodingByteBuffer.Count;
    }
References System.Text.Encoding.EncodingByteBuffer.AddByte(), System.byteCount, System.bytes, System.charCount, System.Text.EncoderNLS.charLeftOver, System.chars, System.Text.Encoding.EncodingByteBuffer.CharsUsed, System.Text.Encoding.EncodingByteBuffer.Count, System.Text.ISO2022Encoding.ISO2022Encoder.currentMode, System.Text.Encoding.EncodingByteBuffer.GetNextChar(), System.Text.DBCSCodePageEncoding.mapUnicodeToBytes, System.Text.Encoding.EncodingByteBuffer.MoreData, System.Text.EncoderNLS.MustFlush, and System.Text.ISO2022Encoding.ISO2022Encoder.shiftInOutMode.
Referenced by System.Text.ISO2022Encoding.GetBytes().