Terraria: Terraria.GameContent.Drawing.TileDrawing.EnsureWindGridSize
EnsureWindGridSize()
void Terraria.GameContent.Drawing.TileDrawing.EnsureWindGridSize () inline private
Definition at line 6595 of file TileDrawing.cs.
    {
        Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
        Vector2 offSet = new Vector2(Main.offScreenRange, Main.offScreenRange);
        if (Main.drawToScreen)
        {
            offSet = Vector2.Zero;
        }
        GetScreenDrawArea(unscaledPosition, offSet, out var firstTileX, out var lastTileX, out var firstTileY, out var lastTileY);
        _windGrid.SetSize(lastTileX - firstTileX, lastTileY - firstTileY);
    }
References Terraria.GameContent.Drawing.TileDrawing._windGrid, Terraria.Main.Camera, Terraria.Main.drawToScreen, Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.Main.offScreenRange, Terraria.GameContent.Drawing.WindGrid.SetSize(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw(), and Terraria.GameContent.Drawing.TileDrawing.Update().