Terraria: Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeBiome
GetPalmTreeBiome()
int Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeBiome (int tileX, int tileY) inline private
Definition at line 1431 of file TileDrawing.cs.
    {
        int i;
        for (i = tileY; Main.tile[tileX, i].active() && Main.tile[tileX, i].type == 323; i++)
        {
        }
        return GetPalmTreeVariant(tileX, i);
    }
References Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeVariant(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), and Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing().