Terraria: Terraria.GameContent.Drawing.TileDrawing.DrawPartialLiquid
DrawPartialLiquid()
void Terraria.GameContent.Drawing.TileDrawing.DrawPartialLiquid (bool behindBlocks, Tile tileCache, ref Vector2 position, ref Rectangle liquidSize, int liquidType, ref VertexColors colors) inline private
    {
        int num = tileCache.slope();
        bool flag = !TileID.Sets.BlocksWaterDrawingBehindSelf[tileCache.type];
        if (!behindBlocks)
        {
            flag = false;
        }
        if (flag || num == 0)
        {
            Main.tileBatch.Draw(TextureAssets.Liquid[liquidType].Value, position, liquidSize, colors, default(Vector2), 1f, SpriteEffects.None);
            return;
        }
        liquidSize.X += 18 * (num - 1);
        switch (num)
        {
        case 1:
            Main.tileBatch.Draw(TextureAssets.LiquidSlope[liquidType].Value, position, liquidSize, colors, Vector2.Zero, 1f, SpriteEffects.None);
            break;
        case 2:
            Main.tileBatch.Draw(TextureAssets.LiquidSlope[liquidType].Value, position, liquidSize, colors, Vector2.Zero, 1f, SpriteEffects.None);
            break;
        case 3:
            Main.tileBatch.Draw(TextureAssets.LiquidSlope[liquidType].Value, position, liquidSize, colors, Vector2.Zero, 1f, SpriteEffects.None);
            break;
        case 4:
            Main.tileBatch.Draw(TextureAssets.LiquidSlope[liquidType].Value, position, liquidSize, colors, Vector2.Zero, 1f, SpriteEffects.None);
            break;
        }
    }
References Terraria.ID.TileID.Sets.BlocksWaterDrawingBehindSelf, Terraria.Graphics.TileBatch.Draw(), Terraria.GameContent.TextureAssets.Liquid, Terraria.GameContent.TextureAssets.LiquidSlope, Terraria.Tile.slope(), Terraria.Main.tileBatch, Terraria.Tile.type, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile().