Terraria: System.Text.ISO2022Encoding.GetBytesCP5022xJP
GetBytesCP5022xJP()
unsafe int System.Text.ISO2022Encoding.GetBytesCP5022xJP (char * chars, int charCount, byte * bytes, int byteCount, ISO2022Encoder encoder) inline private
Definition at line 280 of file ISO2022Encoding.cs.
    {
        EncodingByteBuffer encodingByteBuffer = new EncodingByteBuffer(this, encoder, bytes, byteCount, chars, charCount);
        ISO2022Modes iSO2022Modes = ISO2022Modes.ModeASCII;
        ISO2022Modes iSO2022Modes2 = ISO2022Modes.ModeASCII;
        if (encoder != null)
        {
            char charLeftOver = encoder.charLeftOver;
            iSO2022Modes = encoder.currentMode;
            iSO2022Modes2 = encoder.shiftInOutMode;
            if (charLeftOver > '\0')
            {
                encodingByteBuffer.Fallback(charLeftOver);
            }
        }
        while (encodingByteBuffer.MoreData)
        {
            char nextChar = encodingByteBuffer.GetNextChar();
            ushort num = mapUnicodeToBytes[(int)nextChar];
            byte b;
            byte b2;
            while (true)
            {
                b = (byte)(num >> 8);
                b2 = (byte)(num & 0xFFu);
                if (b != 16)
                {
                    break;
                }
                if (CodePage == 50220)
                {
                    if (b2 >= 33 && b2 < 33 + s_HalfToFullWidthKanaTable.Length)
                    {
                        num = (ushort)(s_HalfToFullWidthKanaTable[b2 - 33] & 0x7F7Fu);
                        continue;
                    }
                    goto IL_009a;
                }
                goto IL_00be;
            }
            if (b != 0)
            {
                if (CodePage == 50222 && iSO2022Modes == ISO2022Modes.ModeHalfwidthKatakana)
                {
                    if (!encodingByteBuffer.AddByte(15))
                    {
                        break;
                    }
                    iSO2022Modes = iSO2022Modes2;
                }
                if (iSO2022Modes != ISO2022Modes.ModeJIS0208)
                {
                    if (!encodingByteBuffer.AddByte((byte)27, (byte)36, (byte)66))
                    {
                        break;
                    }
                    iSO2022Modes = ISO2022Modes.ModeJIS0208;
                }
                if (!encodingByteBuffer.AddByte(b, b2))
                {
                    break;
                }
            }
            else if (num != 0 || nextChar == '\0')
            {
                if (CodePage == 50222 && iSO2022Modes == ISO2022Modes.ModeHalfwidthKatakana)
                {
                    if (!encodingByteBuffer.AddByte(15))
                    {
                        break;
                    }
                    iSO2022Modes = iSO2022Modes2;
                }
                if (iSO2022Modes != ISO2022Modes.ModeASCII)
                {
                    if (!encodingByteBuffer.AddByte((byte)27, (byte)40, (byte)66))
                    {
                        break;
                    }
                    iSO2022Modes = ISO2022Modes.ModeASCII;
                }
                if (!encodingByteBuffer.AddByte(b2))
                {
                    break;
                }
            }
            else
            {
                encodingByteBuffer.Fallback(nextChar);
            }
            continue;
            IL_009a:
            encodingByteBuffer.Fallback(nextChar);
            continue;
            IL_00be:
            if (iSO2022Modes != 0)
            {
                if (CodePage == 50222)
                {
                    if (!encodingByteBuffer.AddByte(14))
                    {
                        break;
                    }
                    iSO2022Modes2 = iSO2022Modes;
                    iSO2022Modes = ISO2022Modes.ModeHalfwidthKatakana;
                }
                else
                {
                    if (!encodingByteBuffer.AddByte((byte)27, (byte)40, (byte)73))
                    {
                        break;
                    }
                    iSO2022Modes = ISO2022Modes.ModeHalfwidthKatakana;
                }
            }
            if (!encodingByteBuffer.AddByte((byte)(b2 & 0x7Fu)))
            {
                break;
            }
        }
        if (iSO2022Modes != ISO2022Modes.ModeASCII && (encoder == null || encoder.MustFlush))
        {
            if (CodePage == 50222 && iSO2022Modes == ISO2022Modes.ModeHalfwidthKatakana)
            {
                if (encodingByteBuffer.AddByte(15))
                {
                    iSO2022Modes = iSO2022Modes2;
                }
                else
                {
                    encodingByteBuffer.GetNextChar();
                }
            }
            if (iSO2022Modes != ISO2022Modes.ModeASCII && (CodePage != 50222 || iSO2022Modes != 0))
            {
                if (encodingByteBuffer.AddByte((byte)27, (byte)40, (byte)66))
                {
                    iSO2022Modes = ISO2022Modes.ModeASCII;
                }
                else
                {
                    encodingByteBuffer.GetNextChar();
                }
            }
        }
        if (bytes != null && encoder != null)
        {
            encoder.currentMode = iSO2022Modes;
            encoder.shiftInOutMode = iSO2022Modes2;
            if (!encodingByteBuffer.fallbackBufferHelper.bUsedEncoder)
            {
                encoder.charLeftOver = '\0';
            }
            encoder.m_charsUsed = encodingByteBuffer.CharsUsed;
        }
        return encodingByteBuffer.Count;
    }
References System.Text.Encoding.EncodingByteBuffer.AddByte(), System.byteCount, System.bytes, System.charCount, System.Text.EncoderNLS.charLeftOver, System.chars, System.Text.Encoding.EncodingByteBuffer.CharsUsed, System.Text.Encoding.CodePage, System.Text.Encoding.EncodingByteBuffer.Count, System.Text.ISO2022Encoding.ISO2022Encoder.currentMode, System.Text.Encoding.EncodingByteBuffer.GetNextChar(), System.Text.DBCSCodePageEncoding.mapUnicodeToBytes, System.Text.Encoding.EncodingByteBuffer.MoreData, System.Text.EncoderNLS.MustFlush, System.Text.ISO2022Encoding.s_HalfToFullWidthKanaTable, and System.Text.ISO2022Encoding.ISO2022Encoder.shiftInOutMode.
Referenced by System.Text.ISO2022Encoding.GetBytes().