Terraria: System.Text.ISO2022Encoding.GetCharsCP52936
GetCharsCP52936()
unsafe int System.Text.ISO2022Encoding.GetCharsCP52936 (byte * bytes, int byteCount, char * chars, int charCount, ISO2022Decoder decoder) inline private
Definition at line 996 of file ISO2022Encoding.cs.
    {
        EncodingCharBuffer encodingCharBuffer = new EncodingCharBuffer(this, decoder, chars, charCount, bytes, byteCount);
        ISO2022Modes iSO2022Modes = ISO2022Modes.ModeASCII;
        int num = -1;
        bool flag = false;
        if (decoder != null)
        {
            iSO2022Modes = decoder.currentMode;
            if (decoder.bytesLeftOverCount != 0)
            {
                num = decoder.bytesLeftOver[0];
            }
        }
        while (encodingCharBuffer.MoreData || num >= 0)
        {
            byte b;
            if (num >= 0)
            {
                b = (byte)num;
                num = -1;
            }
            else
            {
                b = encodingCharBuffer.GetNextByte();
            }
            if (b == 126)
            {
                if (!encodingCharBuffer.MoreData)
                {
                    if (decoder == null || decoder.MustFlush)
                    {
                        encodingCharBuffer.Fallback(b);
                        break;
                    }
                    decoder.ClearMustFlush();
                    if (chars != null)
                    {
                        decoder.bytesLeftOverCount = 1;
                        decoder.bytesLeftOver[0] = 126;
                        flag = true;
                    }
                    break;
                }
                b = encodingCharBuffer.GetNextByte();
                if (b == 126 && iSO2022Modes == ISO2022Modes.ModeASCII)
                {
                    if (!encodingCharBuffer.AddChar((char)b, 2))
                    {
                        break;
                    }
                    continue;
                }
                if (b == 123)
                {
                    iSO2022Modes = ISO2022Modes.ModeHZ;
                    continue;
                }
                if (b == 125)
                {
                    iSO2022Modes = ISO2022Modes.ModeASCII;
                    continue;
                }
                if (b == 10)
                {
                    continue;
                }
                encodingCharBuffer.AdjustBytes(-1);
                b = 126;
            }
            if (iSO2022Modes != ISO2022Modes.ModeASCII && b >= 32)
            {
                if (!encodingCharBuffer.MoreData)
                {
                    if (decoder == null || decoder.MustFlush)
                    {
                        encodingCharBuffer.Fallback(b);
                        break;
                    }
                    decoder.ClearMustFlush();
                    if (chars != null)
                    {
                        decoder.bytesLeftOverCount = 1;
                        decoder.bytesLeftOver[0] = b;
                        flag = true;
                    }
                    break;
                }
                byte nextByte = encodingCharBuffer.GetNextByte();
                ushort num2 = (ushort)((b << 8) | nextByte);
                char c;
                if (b == 32 && nextByte != 0)
                {
                    c = (char)nextByte;
                }
                else
                {
                    if ((b < 33 || b > 119 || nextByte < 33 || nextByte > 126) && (b < 161 || b > 247 || nextByte < 161 || nextByte > 254))
                    {
                        if (nextByte != 32 || 33 > b || b > 125)
{
                            if (!encodingCharBuffer.Fallback((byte)(num2 >> 8), (byte)num2))
{
                                break;
                            }
                            continue;
                        }
                        num2 = 8481;
                    }
                    num2 = (ushort)(num2 | 0x8080u);
                    c = mapBytesToUnicode[(int)num2];
                }
                if (c == '\0' && num2 != 0)
                {
                    if (!encodingCharBuffer.Fallback((byte)(num2 >> 8), (byte)num2))
                    {
                        break;
                    }
                }
                else if (!encodingCharBuffer.AddChar(c, 2))
                {
                    break;
                }
                continue;
            }
            char c2 = mapBytesToUnicode[(int)b];
            if ((c2 == '\0' || c2 == '\0') && b != 0)
            {
                if (!encodingCharBuffer.Fallback(b))
                {
                    break;
                }
            }
            else if (!encodingCharBuffer.AddChar(c2))
            {
                break;
            }
        }
        if (chars != null && decoder != null)
        {
            if (!flag)
            {
                decoder.bytesLeftOverCount = 0;
            }
            if (decoder.MustFlush && decoder.bytesLeftOverCount == 0)
            {
                decoder.currentMode = ISO2022Modes.ModeASCII;
            }
            else
            {
                decoder.currentMode = iSO2022Modes;
            }
            decoder.m_bytesUsed = encodingCharBuffer.BytesUsed;
        }
        return encodingCharBuffer.Count;
    }
References System.Text.Encoding.EncodingCharBuffer.AddChar(), System.Text.Encoding.EncodingCharBuffer.AdjustBytes(), System.byteCount, System.bytes, System.Text.ISO2022Encoding.ISO2022Decoder.bytesLeftOver, System.Text.ISO2022Encoding.ISO2022Decoder.bytesLeftOverCount, System.Text.Encoding.EncodingCharBuffer.BytesUsed, System.charCount, System.chars, System.Text.DecoderNLS.ClearMustFlush(), System.Text.Encoding.EncodingCharBuffer.Count, System.Text.ISO2022Encoding.ISO2022Decoder.currentMode, System.Text.Encoding.EncodingCharBuffer.Fallback(), System.Text.Encoding.EncodingCharBuffer.GetNextByte(), System.Text.DBCSCodePageEncoding.mapBytesToUnicode, System.Text.Encoding.EncodingCharBuffer.MoreData, and System.Text.DecoderNLS.MustFlush.
Referenced by System.Text.ISO2022Encoding.GetChars().