Terraria: Terraria.GameContent.Drawing.TileDrawing.IsVisible
IsVisible()
bool Terraria.GameContent.Drawing.TileDrawing.IsVisible (Tile tile) inline private
    {
        bool flag = tile.invisibleBlock();
        switch (tile.type)
        {
        case 19:
            if (tile.frameY / 18 == 48)
            {
                flag = true;
            }
            break;
        case 541:
        case 631:
            flag = true;
            break;
        }
        if (flag)
        {
            return _shouldShowInvisibleBlocks;
        }
        return true;
    }
References Terraria.GameContent.Drawing.TileDrawing._shouldShowInvisibleBlocks, Terraria.Tile.frameY, Terraria.Tile.invisibleBlock(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), and Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip().