Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportElement
ImportElement() [1/2]
ElementAccessor System.Xml.Serialization.XmlSchemaImporter.ImportElement (XmlQualifiedName name, Type desiredMappingType, Type baseType) inline private
Definition at line 231 of file XmlSchemaImporter.cs.
    {
        XmlSchemaElement xmlSchemaElement = FindElement(name);
        ElementAccessor elementAccessor = (ElementAccessor)base.ImportedElements[xmlSchemaElement];
        if (elementAccessor != null)
        {
            return elementAccessor;
        }
        elementAccessor = ImportElement(xmlSchemaElement, string.Empty, desiredMappingType, baseType, name.Namespace, topLevelElement: true);
        ElementAccessor elementAccessor2 = (ElementAccessor)base.ImportedElements[xmlSchemaElement];
        if (elementAccessor2 != null)
        {
            return elementAccessor2;
        }
        base.ImportedElements.Add(xmlSchemaElement, elementAccessor);
        return elementAccessor;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindElement(), and System.Xml.Serialization.XmlSchemaImporter.ImportElement().
Referenced by System.Xml.Serialization.XmlSchemaImporter.GatherGroupChoices(), System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportDerivedTypeMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.Xml.Serialization.XmlSchemaImporter.ImportElementMember(), System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping(), and System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping().