Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportAnyMapping
ImportAnyMapping()
SpecialMapping System.Xml.Serialization.XmlSchemaImporter.ImportAnyMapping (XmlSchemaType type, string identifier, string ns, bool repeats) inline private
Definition at line 1382 of file XmlSchemaImporter.cs.
    {
        if (type == null)
        {
            return null;
        }
        if (!type.DerivedFrom.IsEmpty)
        {
            return null;
        }
        bool flag = IsMixed(type);
        TypeItems typeItems = GetTypeItems(type);
        if (typeItems.Particle == null)
        {
            return null;
        }
        if (!(typeItems.Particle is XmlSchemaAll) && !(typeItems.Particle is XmlSchemaSequence))
        {
            return null;
        }
        if (typeItems.Attributes != null && typeItems.Attributes.Count > 0)
        {
            return null;
        }
        XmlSchemaGroupBase particle = typeItems.Particle;
        if (particle.Items.Count != 1 || !(particle.Items[0] is XmlSchemaAny))
        {
            return null;
        }
        XmlSchemaAny xmlSchemaAny = (XmlSchemaAny)particle.Items[0];
        SpecialMapping specialMapping = new SpecialMapping();
        if (typeItems.AnyAttribute != null && xmlSchemaAny.IsMultipleOccurrence && flag)
        {
            specialMapping.NamedAny = true;
            specialMapping.TypeDesc = base.Scope.GetTypeDesc(typeof(XmlElement));
        }
        else
        {
            if (typeItems.AnyAttribute != null || xmlSchemaAny.IsMultipleOccurrence)
            {
                return null;
            }
            specialMapping.TypeDesc = base.Scope.GetTypeDesc(flag ? typeof(XmlNode) : typeof(XmlElement));
        }
        TypeFlags typeFlags = TypeFlags.CanBeElementValue;
        if (typeItems.AnyAttribute != null || flag)
        {
            typeFlags |= TypeFlags.CanBeTextValue;
        }
        RunSchemaExtensions(specialMapping, XmlQualifiedName.Empty, null, xmlSchemaAny, typeFlags);
        specialMapping.TypeName = specialMapping.TypeDesc.Name;
        if (repeats)
        {
            specialMapping.TypeDesc = specialMapping.TypeDesc.CreateArrayTypeDesc();
        }
        return specialMapping;
    }
References System.Collections.CollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.Serialization.XmlSchemaImporter.GetTypeItems(), System.Xml.Serialization.XmlSchemaImporter.IsMixed(), System.Xml.Schema.XmlSchemaGroupBase.Items, System.Xml.Serialization.XmlSchemaImporter.RunSchemaExtensions(), and System.type.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportType().