Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportAnyType
ImportAnyType()
XmlMembersMapping? System.Xml.Serialization.XmlSchemaImporter.ImportAnyType (XmlQualifiedName typeName, string elementName) inline
Definition at line 140 of file XmlSchemaImporter.cs.
    {
        TypeMapping typeMapping = ImportType(typeName, typeof(MembersMapping), null, TypeFlags.CanBeElementValue, addref: true);
        MembersMapping membersMapping = typeMapping as MembersMapping;
        if (membersMapping == null)
        {
            XmlSchemaComplexType xmlSchemaComplexType = new XmlSchemaComplexType();
            XmlSchemaSequence xmlSchemaSequence = (XmlSchemaSequence)(xmlSchemaComplexType.Particle = new XmlSchemaSequence());
            XmlSchemaElement xmlSchemaElement = new XmlSchemaElement();
            xmlSchemaElement.Name = elementName;
            xmlSchemaElement.SchemaTypeName = typeName;
            xmlSchemaSequence.Items.Add(xmlSchemaElement);
            membersMapping = ImportMembersType(xmlSchemaComplexType, typeName.Namespace, elementName);
        }
        if (membersMapping.Members.Length != 1 || !membersMapping.Members[0].Accessor.Any)
        {
            return null;
        }
        membersMapping.Members[0].Name = elementName;
        ElementAccessor elementAccessor = new ElementAccessor();
        elementAccessor.Name = elementName;
        elementAccessor.Namespace = typeName.Namespace;
        elementAccessor.Mapping = membersMapping;
        elementAccessor.Any = true;
        XmlSchemaObject xmlSchemaObject = base.Schemas.SchemaSet.GlobalTypes[typeName];
        if (xmlSchemaObject != null && xmlSchemaObject.Parent is XmlSchema xmlSchema)
        {
            elementAccessor.Form = ((xmlSchema.ElementFormDefault == XmlSchemaForm.None) ? XmlSchemaForm.Unqualified : xmlSchema.ElementFormDefault);
        }
        return new XmlMembersMapping(base.Scope, elementAccessor, XmlMappingAccess.Read | XmlMappingAccess.Write);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.ImportMembersType(), System.Xml.Serialization.XmlSchemaImporter.ImportType(), and System.Xml.XmlQualifiedName.Namespace.