Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup
ImportChoiceGroup()
MemberMapping System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup (XmlSchemaGroupBase group, string identifier, CodeIdentifiers members, CodeIdentifiers membersScope, INameScope elementsScope, string ns, bool groupRepeats, ref bool needExplicitOrder, bool allowDuplicates) inline private
Definition at line 738 of file XmlSchemaImporter.cs.
    {
        NameTable nameTable = new NameTable();
        if (GatherGroupChoices(group, nameTable, identifier, ns, ref needExplicitOrder, allowDuplicates))
        {
            groupRepeats = true;
        }
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.Elements = (ElementAccessor[])nameTable.ToArray(typeof(ElementAccessor));
        Array.Sort(memberMapping.Elements, new ElementComparer());
        AddScopeElements(elementsScope, memberMapping.Elements, ref needExplicitOrder, allowDuplicates);
        bool flag = false;
        bool flag2 = false;
        Hashtable hashtable = new Hashtable(memberMapping.Elements.Length);
        for (int i = 0; i < memberMapping.Elements.Length; i++)
        {
            ElementAccessor elementAccessor = memberMapping.Elements[i];
            string fullName = elementAccessor.Mapping.TypeDesc.FullName;
            object obj = hashtable[fullName];
            if (obj != null)
            {
                flag = true;
                ElementAccessor elementAccessor2 = (ElementAccessor)obj;
                if (!flag2 && elementAccessor2.IsNullable != elementAccessor.IsNullable)
                {
                    flag2 = true;
                }
            }
            else
            {
                hashtable.Add(fullName, elementAccessor);
            }
            if (elementAccessor.Mapping is ArrayMapping arrayMapping && IsNeedXmlSerializationAttributes(arrayMapping))
            {
                elementAccessor.Mapping = arrayMapping.TopLevelMapping;
                elementAccessor.Mapping.ReferencedByTopLevelElement = false;
                elementAccessor.Mapping.ReferencedByElement = true;
            }
        }
        if (flag2)
        {
            memberMapping.TypeDesc = base.Scope.GetTypeDesc(typeof(object));
        }
        else
        {
            TypeDesc[] array = new TypeDesc[hashtable.Count];
            IEnumerator enumerator = hashtable.Values.GetEnumerator();
            for (int j = 0; j < array.Length; j++)
            {
                if (!enumerator.MoveNext())
                {
                    break;
                }
                array[j] = ((ElementAccessor)enumerator.Current).Mapping.TypeDesc;
            }
            memberMapping.TypeDesc = TypeDesc.FindCommonBaseTypeDesc(array);
            if (memberMapping.TypeDesc == null)
            {
                memberMapping.TypeDesc = base.Scope.GetTypeDesc(typeof(object));
            }
        }
        if (groupRepeats)
        {
            memberMapping.TypeDesc = memberMapping.TypeDesc.CreateArrayTypeDesc();
        }
        if (membersScope != null)
        {
            memberMapping.Name = membersScope.AddUnique(groupRepeats ? "Items" : "Item", memberMapping);
            members?.Add(memberMapping.Name, memberMapping);
        }
        if (flag)
        {
            memberMapping.ChoiceIdentifier = new ChoiceIdentifierAccessor();
            memberMapping.ChoiceIdentifier.MemberName = memberMapping.Name + "ElementName";
            memberMapping.ChoiceIdentifier.Mapping = ImportEnumeratedChoice(memberMapping.Elements, ns, memberMapping.Name + "ChoiceType");
            memberMapping.ChoiceIdentifier.MemberIds = new string[memberMapping.Elements.Length];
            ConstantMapping[] constants = ((EnumMapping)memberMapping.ChoiceIdentifier.Mapping).Constants;
            for (int k = 0; k < memberMapping.Elements.Length; k++)
            {
                memberMapping.ChoiceIdentifier.MemberIds[k] = constants[k].Name;
            }
            MemberMapping memberMapping2 = new MemberMapping();
            memberMapping2.Ignore = true;
            memberMapping2.Name = memberMapping.ChoiceIdentifier.MemberName;
            if (groupRepeats)
            {
                memberMapping2.TypeDesc = memberMapping.ChoiceIdentifier.Mapping.TypeDesc.CreateArrayTypeDesc();
            }
            else
            {
                memberMapping2.TypeDesc = memberMapping.ChoiceIdentifier.Mapping.TypeDesc;
            }
            ElementAccessor elementAccessor3 = new ElementAccessor();
            elementAccessor3.Name = memberMapping2.Name;
            elementAccessor3.Namespace = ns;
            elementAccessor3.Mapping = memberMapping.ChoiceIdentifier.Mapping;
            memberMapping2.Elements = new ElementAccessor[1] { elementAccessor3 };
            if (membersScope != null)
            {
                string text2 = (memberMapping.ChoiceIdentifier.MemberName = membersScope.AddUnique(memberMapping.ChoiceIdentifier.MemberName, memberMapping2));
                string name = (memberMapping2.Name = text2);
                elementAccessor3.Name = name;
                members?.Add(elementAccessor3.Name, memberMapping2);
            }
        }
        return memberMapping;
    }
References System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlSchemaImporter.AddScopeElements(), System.array, System.Collections.Hashtable.Count, System.Xml.Dictionary, System.Xml.Serialization.TypeDesc.FindCommonBaseTypeDesc(), System.Xml.Serialization.XmlSchemaImporter.GatherGroupChoices(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedChoice(), System.Xml.Serialization.XmlSchemaImporter.IsNeedXmlSerializationAttributes(), System.obj, System.Array.Sort(), and System.Collections.Hashtable.Values.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportGroup(), System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers(), and System.Xml.Serialization.XmlSchemaImporter.ImportSubstitutionGroupMember().