Terraria: System.Xml.Serialization.XmlSchemaImporter.GetTypeItems
GetTypeItems()
TypeItems System.Xml.Serialization.XmlSchemaImporter.GetTypeItems (XmlSchemaType type) inline private
Definition at line 674 of file XmlSchemaImporter.cs.
    {
        TypeItems typeItems = new TypeItems();
        if (type is XmlSchemaComplexType)
        {
            XmlSchemaParticle xmlSchemaParticle = null;
            XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)type;
            if (xmlSchemaComplexType.ContentModel != null)
            {
                XmlSchemaContent content = xmlSchemaComplexType.ContentModel.Content;
                if (content is XmlSchemaComplexContentExtension)
                {
                    XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension = (XmlSchemaComplexContentExtension)content;
                    typeItems.Attributes = xmlSchemaComplexContentExtension.Attributes;
                    typeItems.AnyAttribute = xmlSchemaComplexContentExtension.AnyAttribute;
                    xmlSchemaParticle = xmlSchemaComplexContentExtension.Particle;
                }
                else if (content is XmlSchemaSimpleContentExtension)
                {
                    XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = (XmlSchemaSimpleContentExtension)content;
                    typeItems.Attributes = xmlSchemaSimpleContentExtension.Attributes;
                    typeItems.AnyAttribute = xmlSchemaSimpleContentExtension.AnyAttribute;
                    typeItems.baseSimpleType = xmlSchemaSimpleContentExtension.BaseTypeName;
                }
            }
            else
            {
                typeItems.Attributes = xmlSchemaComplexType.Attributes;
                typeItems.AnyAttribute = xmlSchemaComplexType.AnyAttribute;
                xmlSchemaParticle = xmlSchemaComplexType.Particle;
            }
            if (xmlSchemaParticle is XmlSchemaGroupRef)
            {
                XmlSchemaGroupRef xmlSchemaGroupRef = (XmlSchemaGroupRef)xmlSchemaParticle;
                typeItems.Particle = FindGroup(xmlSchemaGroupRef.RefName).Particle;
                typeItems.IsUnbounded = xmlSchemaParticle.IsMultipleOccurrence;
            }
            else if (xmlSchemaParticle is XmlSchemaGroupBase)
            {
                typeItems.Particle = (XmlSchemaGroupBase)xmlSchemaParticle;
                typeItems.IsUnbounded = xmlSchemaParticle.IsMultipleOccurrence;
            }
        }
        return typeItems;
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindGroup(), System.Xml.Schema.XmlSchemaGroup.Particle, and System.type.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportAnyMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers(), System.Xml.Serialization.XmlSchemaImporter.IsAllGroup(), and System.Xml.Serialization.XmlSchemaImporter.IsCyclicReferencedType().