Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportType
ImportType() [1/2]
TypeMapping System.Xml.Serialization.XmlSchemaImporter.ImportType (XmlQualifiedName name, Type desiredMappingType, Type baseType, TypeFlags flags, bool addref) inline private
Definition at line 389 of file XmlSchemaImporter.cs.
    {
        if (name.Name == "anyType" && name.Namespace == "http://www.w3.org/2001/XMLSchema")
        {
            return ImportRootMapping();
        }
        object obj = FindType(name, flags);
        TypeMapping typeMapping = (TypeMapping)base.ImportedMappings[obj];
        if (typeMapping != null && desiredMappingType.IsAssignableFrom(typeMapping.GetType()))
        {
            return typeMapping;
        }
        if (addref)
        {
            AddReference(name, base.TypesInUse, System.SR.XmlCircularTypeReference);
        }
        if (obj is XmlSchemaComplexType)
        {
            typeMapping = ImportType((XmlSchemaComplexType)obj, name.Namespace, name.Name, desiredMappingType, baseType, flags);
        }
        else
        {
            if (!(obj is XmlSchemaSimpleType))
            {
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
            typeMapping = ImportDataType((XmlSchemaSimpleType)obj, name.Namespace, name.Name, baseType, flags, isList: false);
        }
        if (addref && name.Namespace != "http://www.w3.org/2001/XMLSchema")
        {
            RemoveReference(name, base.TypesInUse);
        }
        return typeMapping;
    }
References System.Xml.Serialization.SchemaImporter.AddReference(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindType(), System.Xml.Serialization.XmlSchemaImporter.ImportDataType(), System.Xml.Serialization.SchemaImporter.ImportRootMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportType(), System.obj, System.Xml.Serialization.SchemaImporter.RemoveReference(), System.SR.XmlCircularTypeReference, and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportAnyType(), System.Xml.Serialization.XmlSchemaImporter.ImportAttribute(), System.Xml.Serialization.XmlSchemaImporter.ImportDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportDerivedTypes(), System.Xml.Serialization.XmlSchemaImporter.ImportElementType(), System.Xml.Serialization.XmlSchemaImporter.ImportSchemaType(), System.Xml.Serialization.XmlSchemaImporter.ImportStructType(), System.Xml.Serialization.XmlSchemaImporter.ImportTextMember(), and System.Xml.Serialization.XmlSchemaImporter.ImportType().