Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportTextMember
ImportTextMember()
void System.Xml.Serialization.XmlSchemaImporter.ImportTextMember (CodeIdentifiers members, CodeIdentifiers membersScope, XmlQualifiedName simpleContentType) inline private
Definition at line 1104 of file XmlSchemaImporter.cs.
    {
        bool flag = false;
        TypeMapping typeMapping;
        if (simpleContentType != null)
        {
            typeMapping = ImportType(simpleContentType, typeof(TypeMapping), null, (TypeFlags)48, addref: false);
            if (!(typeMapping is PrimitiveMapping) && !typeMapping.TypeDesc.CanBeTextValue)
            {
                return;
            }
        }
        else
        {
            flag = true;
            typeMapping = GetDefaultMapping((TypeFlags)48);
        }
        TextAccessor textAccessor = new TextAccessor();
        textAccessor.Mapping = typeMapping;
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.Elements = Array.Empty<ElementAccessor>();
        memberMapping.Text = textAccessor;
        if (flag)
        {
            memberMapping.TypeDesc = textAccessor.Mapping.TypeDesc.CreateArrayTypeDesc();
            memberMapping.Name = members.MakeRightCase("Text");
        }
        else
        {
            PrimitiveMapping primitiveMapping = (PrimitiveMapping)textAccessor.Mapping;
            if (primitiveMapping.IsList)
            {
                memberMapping.TypeDesc = textAccessor.Mapping.TypeDesc.CreateArrayTypeDesc();
                memberMapping.Name = members.MakeRightCase("Text");
            }
            else
            {
                memberMapping.TypeDesc = textAccessor.Mapping.TypeDesc;
                memberMapping.Name = members.MakeRightCase("Value");
            }
        }
        memberMapping.Name = membersScope.AddUnique(memberMapping.Name, memberMapping);
        members.Add(memberMapping.Name, memberMapping);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.GetDefaultMapping(), and System.Xml.Serialization.XmlSchemaImporter.ImportType().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportGroup(), System.Xml.Serialization.XmlSchemaImporter.ImportStructDataType(), and System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers().