Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportSubstitutionGroupMember
ImportSubstitutionGroupMember()
bool System.Xml.Serialization.XmlSchemaImporter.ImportSubstitutionGroupMember (XmlSchemaElement element, string identifier, CodeIdentifiers members, CodeIdentifiers membersScope, string ns, bool repeats, ref bool needExplicitOrder, bool allowDuplicates) inline private
Definition at line 1082 of file XmlSchemaImporter.cs.
    {
        XmlSchemaElement[] equivalentElements = GetEquivalentElements(element);
        if (equivalentElements.Length == 0)
        {
            return false;
        }
        XmlSchemaChoice xmlSchemaChoice = new XmlSchemaChoice();
        for (int i = 0; i < equivalentElements.Length; i++)
        {
            xmlSchemaChoice.Items.Add(equivalentElements[i]);
        }
        if (!element.IsAbstract)
        {
            xmlSchemaChoice.Items.Add(element);
        }
        identifier = ((identifier.Length != 0) ? (identifier + CodeIdentifier.MakePascal(Accessor.UnescapeName(element.Name))) : CodeIdentifier.MakeValid(Accessor.UnescapeName(element.Name)));
        ImportChoiceGroup(xmlSchemaChoice, identifier, members, membersScope, null, ns, repeats, ref needExplicitOrder, allowDuplicates);
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.GetEquivalentElements(), System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup(), System.Xml.Schema.XmlSchemaElement.IsAbstract, System.Xml.Serialization.CodeIdentifier.MakePascal(), System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Schema.XmlSchemaElement.Name, and System.Xml.Serialization.Accessor.UnescapeName().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportElementMember().