Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedDataType
ImportEnumeratedDataType()
TypeMapping System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedDataType (XmlSchemaSimpleType dataType, string typeNs, string identifier, TypeFlags flags, bool isList) inline private
Definition at line 1760 of file XmlSchemaImporter.cs.
    {
        TypeMapping typeMapping = (TypeMapping)base.ImportedMappings[dataType];
        if (typeMapping != null)
        {
            return typeMapping;
        }
        XmlSchemaType xmlSchemaType = dataType;
        while (!xmlSchemaType.DerivedFrom.IsEmpty)
        {
            xmlSchemaType = FindType(xmlSchemaType.DerivedFrom, (TypeFlags)40);
        }
        if (xmlSchemaType is XmlSchemaComplexType)
        {
            return null;
        }
        TypeDesc typeDesc = base.Scope.GetTypeDesc((XmlSchemaSimpleType)xmlSchemaType);
        if (typeDesc != null && typeDesc.FullName != typeof(string).FullName)
        {
            return ImportPrimitiveDataType(dataType, flags);
        }
        identifier = Accessor.UnescapeName(identifier);
        string text = GenerateUniqueTypeName(identifier);
        EnumMapping enumMapping = new EnumMapping();
        enumMapping.IsReference = base.Schemas.IsReference(dataType);
        enumMapping.TypeDesc = new TypeDesc(text, text, TypeKind.Enum, null, TypeFlags.None);
        if (dataType.Name != null && dataType.Name.Length > 0)
        {
            enumMapping.TypeName = identifier;
        }
        enumMapping.Namespace = typeNs;
        enumMapping.IsFlags = isList;
        CodeIdentifiers codeIdentifiers = new CodeIdentifiers();
        XmlSchemaSimpleTypeContent content = dataType.Content;
        if (content is XmlSchemaSimpleTypeRestriction)
        {
            XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = (XmlSchemaSimpleTypeRestriction)content;
            for (int i = 0; i < xmlSchemaSimpleTypeRestriction.Facets.Count; i++)
            {
                object obj = xmlSchemaSimpleTypeRestriction.Facets[i];
                if (obj is XmlSchemaEnumerationFacet)
                {
                    XmlSchemaEnumerationFacet xmlSchemaEnumerationFacet = (XmlSchemaEnumerationFacet)obj;
                    if (typeDesc != null && typeDesc.HasCustomFormatter)
                    {
                        XmlCustomFormatter.ToDefaultValue(xmlSchemaEnumerationFacet.Value, typeDesc.FormatterName);
                    }
                    ConstantMapping constantMapping = new ConstantMapping();
                    string identifier2 = CodeIdentifier.MakeValid(xmlSchemaEnumerationFacet.Value);
                    constantMapping.Name = codeIdentifiers.AddUnique(identifier2, constantMapping);
                    constantMapping.XmlName = xmlSchemaEnumerationFacet.Value;
                    constantMapping.Value = i;
                }
            }
        }
        enumMapping.Constants = (ConstantMapping[])codeIdentifiers.ToArray(typeof(ConstantMapping));
        if (isList && enumMapping.Constants.Length > 63)
        {
            typeMapping = GetDefaultMapping((TypeFlags)56);
            base.ImportedMappings.Add(dataType, typeMapping);
            return typeMapping;
        }
        base.ImportedMappings.Add(dataType, enumMapping);
        base.Scope.AddTypeMapping(enumMapping);
        return enumMapping;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaSimpleType.Content, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindType(), System.FullName, System.Xml.Serialization.XmlSchemaImporter.GenerateUniqueTypeName(), System.Xml.Serialization.XmlSchemaImporter.GetDefaultMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportPrimitiveDataType(), System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Schema.XmlSchemaType.Name, System.obj, System.text, System.Xml.Serialization.XmlCustomFormatter.ToDefaultValue(), and System.Xml.Serialization.Accessor.UnescapeName().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportDataType().