Terraria: System.Xml.Serialization.XmlSchemaImporter.GatherGroupChoices
GatherGroupChoices() [2/2]
bool System.Xml.Serialization.XmlSchemaImporter.GatherGroupChoices (XmlSchemaParticle particle, NameTable choiceElements, string identifier, string ns, ref bool needExplicitOrder, bool allowDuplicates) inline private
Definition at line 883 of file XmlSchemaImporter.cs.
    {
        if (particle is XmlSchemaGroupRef)
        {
            XmlSchemaGroupRef xmlSchemaGroupRef = (XmlSchemaGroupRef)particle;
            if (!xmlSchemaGroupRef.RefName.IsEmpty)
            {
                AddReference(xmlSchemaGroupRef.RefName, base.GroupsInUse, System.SR.XmlCircularGroupReference);
                if (GatherGroupChoices(FindGroup(xmlSchemaGroupRef.RefName), choiceElements, identifier, xmlSchemaGroupRef.RefName.Namespace, ref needExplicitOrder, allowDuplicates))
                {
                    RemoveReference(xmlSchemaGroupRef.RefName, base.GroupsInUse);
                    return true;
                }
                RemoveReference(xmlSchemaGroupRef.RefName, base.GroupsInUse);
            }
        }
        else if (particle is XmlSchemaGroupBase)
        {
            XmlSchemaGroupBase xmlSchemaGroupBase = (XmlSchemaGroupBase)particle;
            bool flag = xmlSchemaGroupBase.IsMultipleOccurrence;
            XmlSchemaAny xmlSchemaAny = null;
            bool duplicateElements = false;
            for (int i = 0; i < xmlSchemaGroupBase.Items.Count; i++)
            {
                object obj = xmlSchemaGroupBase.Items[i];
                if (obj is XmlSchemaGroupBase || obj is XmlSchemaGroupRef)
                {
                    if (GatherGroupChoices((XmlSchemaParticle)obj, choiceElements, identifier, ns, ref needExplicitOrder, allowDuplicates))
                    {
                        flag = true;
                    }
                }
                else if (obj is XmlSchemaAny)
                {
                    if (GenerateOrder)
                    {
                        AddScopeElements(choiceElements, ImportAny((XmlSchemaAny)obj, makeElement: true, ns), ref duplicateElements, allowDuplicates);
                    }
                    else
                    {
                        xmlSchemaAny = (XmlSchemaAny)obj;
                    }
                }
                else
                {
                    if (!(obj is XmlSchemaElement))
                    {
                        continue;
                    }
                    XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)obj;
                    XmlSchemaElement topLevelElement = GetTopLevelElement(xmlSchemaElement);
                    if (topLevelElement != null)
                    {
                        XmlSchemaElement[] equivalentElements = GetEquivalentElements(topLevelElement);
                        for (int j = 0; j < equivalentElements.Length; j++)
{
                            if (equivalentElements[j].IsMultipleOccurrence)
{
                                flag = true;
                            }
                            AddScopeElement(choiceElements, ImportElement(equivalentElements[j], identifier, typeof(TypeMapping), null, equivalentElements[j].QualifiedName.Namespace, topLevelElement: true), ref duplicateElements, allowDuplicates);
                        }
                    }
                    if (xmlSchemaElement.IsMultipleOccurrence)
                    {
                        flag = true;
                    }
                    AddScopeElement(choiceElements, ImportElement(xmlSchemaElement, identifier, typeof(TypeMapping), null, xmlSchemaElement.QualifiedName.Namespace, topLevelElement: false), ref duplicateElements, allowDuplicates);
                }
            }
            if (xmlSchemaAny != null)
            {
                AddScopeElements(choiceElements, ImportAny(xmlSchemaAny, makeElement: true, ns), ref duplicateElements, allowDuplicates);
            }
            if (!flag && !(xmlSchemaGroupBase is XmlSchemaChoice) && xmlSchemaGroupBase.Items.Count > 1)
            {
                flag = true;
            }
            return flag;
        }
        return false;
    }
References System.Xml.Serialization.SchemaImporter.AddReference(), System.Xml.Serialization.XmlSchemaImporter.AddScopeElement(), System.Xml.Serialization.XmlSchemaImporter.AddScopeElements(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindGroup(), System.Xml.Serialization.XmlSchemaImporter.GatherGroupChoices(), System.Xml.Serialization.XmlSchemaImporter.GenerateOrder, System.Xml.Serialization.XmlSchemaImporter.GetEquivalentElements(), System.Xml.Serialization.XmlSchemaImporter.GetTopLevelElement(), System.Xml.Serialization.XmlSchemaImporter.ImportAny(), System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.obj, System.Xml.Serialization.SchemaImporter.RemoveReference(), and System.SR.XmlCircularGroupReference.