Terraria: System.Xml.Serialization.XmlSchemaImporter.FindDataType
FindDataType()
XmlSchemaSimpleType System.Xml.Serialization.XmlSchemaImporter.FindDataType (XmlQualifiedName name, TypeFlags flags) inline private
Definition at line 1949 of file XmlSchemaImporter.cs.
    {
        if (name == null || name.IsEmpty)
        {
            return (XmlSchemaSimpleType)base.Scope.GetTypeDesc(typeof(string)).DataType;
        }
        TypeDesc typeDesc = base.Scope.GetTypeDesc(name.Name, name.Namespace, flags);
        if (typeDesc != null && typeDesc.DataType is XmlSchemaSimpleType)
        {
            return (XmlSchemaSimpleType)typeDesc.DataType;
        }
        XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)base.Schemas.Find(name, typeof(XmlSchemaSimpleType));
        if (xmlSchemaSimpleType != null)
        {
            return xmlSchemaSimpleType;
        }
        if (name.Namespace == "http://www.w3.org/2001/XMLSchema")
        {
            return (XmlSchemaSimpleType)base.Scope.GetTypeDesc("string", "http://www.w3.org/2001/XMLSchema", flags).DataType;
        }
        if (name.Name == "Array" && name.Namespace == "http://schemas.xmlsoap.org/soap/encoding/")
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidEncoding, name));
        }
        throw new InvalidOperationException(System.SR.Format(System.SR.XmlMissingDataType, name));
    }
References System.Xml.Dictionary, System.SR.Format(), System.SR.XmlInvalidEncoding, and System.SR.XmlMissingDataType.
Referenced by System.Xml.Serialization.XmlSchemaImporter.FindType(), System.Xml.Serialization.XmlSchemaImporter.GetDataTypeSource(), and System.Xml.Serialization.XmlSchemaImporter.ImportDataType().