Terraria: System.Xml.Serialization.XmlSchemaImporter.BaseTypeName
BaseTypeName()
static XmlQualifiedName System.Xml.Serialization.XmlSchemaImporter.BaseTypeName (XmlSchemaSimpleType dataType) inline static package
Definition at line 1904 of file XmlSchemaImporter.cs.
    {
        XmlSchemaSimpleTypeContent content = dataType.Content;
        if (content is XmlSchemaSimpleTypeRestriction)
        {
            return ((XmlSchemaSimpleTypeRestriction)content).BaseTypeName;
        }
        if (content is XmlSchemaSimpleTypeList)
        {
            XmlSchemaSimpleTypeList xmlSchemaSimpleTypeList = (XmlSchemaSimpleTypeList)content;
            if (xmlSchemaSimpleTypeList.ItemTypeName != null && !xmlSchemaSimpleTypeList.ItemTypeName.IsEmpty)
            {
                return xmlSchemaSimpleTypeList.ItemTypeName;
            }
            if (xmlSchemaSimpleTypeList.ItemType != null)
            {
                return BaseTypeName(xmlSchemaSimpleTypeList.ItemType);
            }
        }
        return new XmlQualifiedName("string", "http://www.w3.org/2001/XMLSchema");
    }
References System.Xml.Serialization.XmlSchemaImporter.BaseTypeName(), and System.Xml.Schema.XmlSchemaSimpleType.Content.
Referenced by System.Xml.Serialization.XmlSchemaImporter.BaseTypeName(), and System.Xml.Serialization.XmlSchemaImporter.GetDataTypeSource().