Terraria: System.Xml.Serialization.XmlSchemaImporter.FindType
FindType()
XmlSchemaType System.Xml.Serialization.XmlSchemaImporter.FindType (XmlQualifiedName name, TypeFlags flags) inline private
Definition at line 1977 of file XmlSchemaImporter.cs.
    {
        if (name == null || name.IsEmpty)
        {
            return base.Scope.GetTypeDesc(typeof(string)).DataType;
        }
        object obj = base.Schemas.Find(name, typeof(XmlSchemaComplexType));
        if (obj != null)
        {
            return (XmlSchemaComplexType)obj;
        }
        return FindDataType(name, flags);
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindDataType(), and System.obj.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportElementType(), System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportType(), and System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers().