Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportArray
ImportArray()
ElementAccessor System.Xml.Serialization.XmlSchemaImporter.ImportArray (XmlSchemaElement element, string identifier, string ns, bool repeats) inline private
Definition at line 1221 of file XmlSchemaImporter.cs.
    {
        if (repeats)
        {
            return null;
        }
        if (element.SchemaType == null)
        {
            return null;
        }
        if (element.IsMultipleOccurrence)
        {
            return null;
        }
        XmlSchemaType schemaType = element.SchemaType;
        ArrayMapping arrayMapping = ImportArrayMapping(schemaType, identifier, ns, repeats);
        if (arrayMapping == null)
        {
            return null;
        }
        ElementAccessor elementAccessor = new ElementAccessor();
        elementAccessor.Name = element.Name;
        elementAccessor.Namespace = ns;
        elementAccessor.Mapping = arrayMapping;
        if (arrayMapping.TypeDesc.IsNullable)
        {
            elementAccessor.IsNullable = element.IsNillable;
        }
        elementAccessor.Form = ElementForm(ns, element);
        return elementAccessor;
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.ElementForm(), System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping(), System.Xml.Schema.XmlSchemaParticle.IsMultipleOccurrence, System.Xml.Schema.XmlSchemaElement.IsNillable, System.Xml.Schema.XmlSchemaElement.Name, and System.Xml.Schema.XmlSchemaElement.SchemaType.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportElementMember().