Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportElementType
ImportElementType()
TypeMapping System.Xml.Serialization.XmlSchemaImporter.ImportElementType (XmlSchemaElement element, string identifier, Type desiredMappingType, Type baseType, string ns) inline private
Definition at line 304 of file XmlSchemaImporter.cs.
    {
        TypeMapping typeMapping;
        if (!element.SchemaTypeName.IsEmpty)
        {
            typeMapping = ImportType(element.SchemaTypeName, desiredMappingType, baseType, TypeFlags.CanBeElementValue, addref: false);
            if (!typeMapping.ReferencedByElement)
            {
                object obj = FindType(element.SchemaTypeName, TypeFlags.CanBeElementValue);
                XmlSchemaObject xmlSchemaObject = element;
                while (xmlSchemaObject.Parent != null && obj != xmlSchemaObject)
                {
                    xmlSchemaObject = xmlSchemaObject.Parent;
                }
                typeMapping.ReferencedByElement = obj != xmlSchemaObject;
            }
        }
        else if (element.SchemaType == null)
        {
            typeMapping = ((!element.SubstitutionGroup.IsEmpty) ? ImportElementType(FindElement(element.SubstitutionGroup), identifier, desiredMappingType, baseType, ns) : ((!(desiredMappingType == typeof(MembersMapping))) ? ((TypeMapping)ImportRootMapping()) : ((TypeMapping)ImportMembersType(new XmlSchemaType(), ns, identifier))));
        }
        else
        {
            typeMapping = ((!(element.SchemaType is XmlSchemaComplexType)) ? ImportDataType((XmlSchemaSimpleType)element.SchemaType, ns, identifier, baseType, (TypeFlags)56, isList: false) : ImportType((XmlSchemaComplexType)element.SchemaType, ns, identifier, desiredMappingType, baseType, TypeFlags.CanBeElementValue));
            typeMapping.ReferencedByElement = true;
        }
        if (!desiredMappingType.IsAssignableFrom(typeMapping.GetType()))
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlElementImportedTwice, element.Name, ns, typeMapping.GetType().Name, desiredMappingType.Name));
        }
        if (!typeMapping.TypeDesc.IsMappedType)
        {
            RunSchemaExtensions(typeMapping, element.SchemaTypeName, element.SchemaType, element, TypeFlags.CanBeElementValue);
        }
        return typeMapping;
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindElement(), System.Xml.Serialization.XmlSchemaImporter.FindType(), System.SR.Format(), System.Xml.Serialization.XmlSchemaImporter.ImportDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportElementType(), System.Xml.Serialization.XmlSchemaImporter.ImportMembersType(), System.Xml.Serialization.SchemaImporter.ImportRootMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportType(), System.Xml.XmlQualifiedName.IsEmpty, System.Xml.Schema.XmlSchemaElement.Name, System.obj, System.Xml.Serialization.XmlSchemaImporter.RunSchemaExtensions(), System.Xml.Schema.XmlSchemaElement.SchemaType, System.Xml.Schema.XmlSchemaElement.SchemaTypeName, System.Xml.Schema.XmlSchemaElement.SubstitutionGroup, and System.SR.XmlElementImportedTwice.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportElement(), and System.Xml.Serialization.XmlSchemaImporter.ImportElementType().