Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportElementMember
ImportElementMember()
void System.Xml.Serialization.XmlSchemaImporter.ImportElementMember (XmlSchemaElement element, string identifier, CodeIdentifiers members, CodeIdentifiers membersScope, INameScope elementsScope, string ns, bool repeats, ref bool needExplicitOrder, bool allowDuplicates, bool allowUnboundedElements) inline private
Definition at line 1441 of file XmlSchemaImporter.cs.
    {
        repeats |= element.IsMultipleOccurrence;
        XmlSchemaElement topLevelElement = GetTopLevelElement(element);
        if (topLevelElement != null && ImportSubstitutionGroupMember(topLevelElement, identifier, members, membersScope, ns, repeats, ref needExplicitOrder, allowDuplicates))
        {
            return;
        }
        ElementAccessor elementAccessor;
        if ((elementAccessor = ImportArray(element, identifier, ns, repeats)) == null)
        {
            elementAccessor = ImportElement(element, identifier, typeof(TypeMapping), null, ns, topLevelElement: false);
        }
        MemberMapping memberMapping = new MemberMapping();
        string identifier2 = CodeIdentifier.MakeValid(Accessor.UnescapeName(elementAccessor.Name));
        memberMapping.Name = membersScope.AddUnique(identifier2, memberMapping);
        if (memberMapping.Name.EndsWith("Specified", StringComparison.Ordinal))
        {
            identifier2 = memberMapping.Name;
            memberMapping.Name = membersScope.AddUnique(memberMapping.Name, memberMapping);
            membersScope.Remove(identifier2);
        }
        members.Add(memberMapping.Name, memberMapping);
        if (elementAccessor.Mapping.IsList)
        {
            elementAccessor.Mapping = GetDefaultMapping((TypeFlags)48);
            memberMapping.TypeDesc = elementAccessor.Mapping.TypeDesc;
        }
        else
        {
            memberMapping.TypeDesc = elementAccessor.Mapping.TypeDesc;
        }
        AddScopeElement(elementsScope, elementAccessor, ref needExplicitOrder, allowDuplicates);
        memberMapping.Elements = new ElementAccessor[1] { elementAccessor };
        if (element.IsMultipleOccurrence || repeats)
        {
            if (!allowUnboundedElements && elementAccessor.Mapping is ArrayMapping)
            {
                elementAccessor.Mapping = ((ArrayMapping)elementAccessor.Mapping).TopLevelMapping;
                elementAccessor.Mapping.ReferencedByTopLevelElement = false;
                elementAccessor.Mapping.ReferencedByElement = true;
            }
            memberMapping.TypeDesc = elementAccessor.Mapping.TypeDesc.CreateArrayTypeDesc();
        }
        if (element.MinOccurs == 0m && memberMapping.TypeDesc.IsValueType && !element.HasDefault && !memberMapping.TypeDesc.HasIsEmpty)
        {
            memberMapping.CheckSpecified = SpecifiedAccessor.ReadWrite;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlSchemaImporter.AddScopeElement(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.GetDefaultMapping(), System.Xml.Serialization.XmlSchemaImporter.GetTopLevelElement(), System.Xml.Schema.XmlSchemaElement.HasDefault, System.Xml.Serialization.XmlSchemaImporter.ImportArray(), System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.Xml.Serialization.XmlSchemaImporter.ImportSubstitutionGroupMember(), System.Xml.Schema.XmlSchemaParticle.IsMultipleOccurrence, System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Schema.XmlSchemaParticle.MinOccurs, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Xml.Serialization.Accessor.UnescapeName().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers().