Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportAnyMember
ImportAnyMember()
MemberMapping System.Xml.Serialization.XmlSchemaImporter.ImportAnyMember (XmlSchemaAny any, string identifier, CodeIdentifiers members, CodeIdentifiers membersScope, INameScope elementsScope, string ns, ref bool mixed, ref bool needExplicitOrder, bool allowDuplicates) inline private
Definition at line 1150 of file XmlSchemaImporter.cs.
    {
        ElementAccessor[] array = ImportAny(any, !mixed, ns);
        AddScopeElements(elementsScope, array, ref needExplicitOrder, allowDuplicates);
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.Elements = array;
        memberMapping.Name = membersScope.MakeRightCase("Any");
        memberMapping.Name = membersScope.AddUnique(memberMapping.Name, memberMapping);
        members.Add(memberMapping.Name, memberMapping);
        memberMapping.TypeDesc = array[0].Mapping.TypeDesc;
        bool flag = any.IsMultipleOccurrence;
        if (mixed)
        {
            SpecialMapping specialMapping = new SpecialMapping();
            specialMapping.TypeDesc = base.Scope.GetTypeDesc(typeof(XmlNode));
            specialMapping.TypeName = specialMapping.TypeDesc.Name;
            memberMapping.TypeDesc = specialMapping.TypeDesc;
            TextAccessor textAccessor = new TextAccessor();
            textAccessor.Mapping = specialMapping;
            memberMapping.Text = textAccessor;
            flag = true;
            mixed = false;
        }
        if (flag)
        {
            memberMapping.TypeDesc = memberMapping.TypeDesc.CreateArrayTypeDesc();
        }
        return memberMapping;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlSchemaImporter.AddScopeElements(), System.array, System.Xml.Dictionary, and System.Xml.Serialization.XmlSchemaImporter.ImportAny().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers().