Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedChoice
ImportEnumeratedChoice()
EnumMapping System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedChoice (ElementAccessor[] choice, string typeNs, string typeName) inline private
Definition at line 1827 of file XmlSchemaImporter.cs.
    {
        typeName = GenerateUniqueTypeName(Accessor.UnescapeName(typeName), typeNs);
        EnumMapping enumMapping = new EnumMapping();
        enumMapping.TypeDesc = new TypeDesc(typeName, typeName, TypeKind.Enum, null, TypeFlags.None);
        enumMapping.TypeName = typeName;
        enumMapping.Namespace = typeNs;
        enumMapping.IsFlags = false;
        enumMapping.IncludeInSchema = false;
        if (GenerateOrder)
        {
            Array.Sort(choice, new ElementComparer());
        }
        CodeIdentifiers codeIdentifiers = new CodeIdentifiers();
        for (int i = 0; i < choice.Length; i++)
        {
            ElementAccessor elementAccessor = choice[i];
            ConstantMapping constantMapping = new ConstantMapping();
            string identifier = CodeIdentifier.MakeValid(elementAccessor.Name);
            constantMapping.Name = codeIdentifiers.AddUnique(identifier, constantMapping);
            constantMapping.XmlName = elementAccessor.ToString(typeNs);
            constantMapping.Value = i;
        }
        enumMapping.Constants = (ConstantMapping[])codeIdentifiers.ToArray(typeof(ConstantMapping));
        base.Scope.AddTypeMapping(enumMapping);
        return enumMapping;
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.GenerateOrder, System.Xml.Serialization.XmlSchemaImporter.GenerateUniqueTypeName(), System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Array.Sort(), and System.Xml.Serialization.Accessor.UnescapeName().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup().