Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers
ImportGroupMembers()
void System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers (XmlSchemaParticle particle, string identifier, CodeIdentifiers members, CodeIdentifiers membersScope, INameScope elementsScope, string ns, bool groupRepeats, ref bool mixed, ref bool needExplicitOrder, bool allowDuplicates, bool allowUnboundedElements) inline private
Definition at line 1000 of file XmlSchemaImporter.cs.
    {
        if (particle is XmlSchemaGroupRef)
        {
            XmlSchemaGroupRef xmlSchemaGroupRef = (XmlSchemaGroupRef)particle;
            if (!xmlSchemaGroupRef.RefName.IsEmpty)
            {
                AddReference(xmlSchemaGroupRef.RefName, base.GroupsInUse, System.SR.XmlCircularGroupReference);
                ImportGroupMembers(FindGroup(xmlSchemaGroupRef.RefName).Particle, identifier, members, membersScope, elementsScope, xmlSchemaGroupRef.RefName.Namespace, groupRepeats | xmlSchemaGroupRef.IsMultipleOccurrence, ref mixed, ref needExplicitOrder, allowDuplicates, allowUnboundedElements);
                RemoveReference(xmlSchemaGroupRef.RefName, base.GroupsInUse);
            }
        }
        else
        {
            if (!(particle is XmlSchemaGroupBase))
            {
                return;
            }
            XmlSchemaGroupBase xmlSchemaGroupBase = (XmlSchemaGroupBase)particle;
            if (xmlSchemaGroupBase.IsMultipleOccurrence)
            {
                groupRepeats = true;
            }
            if (GenerateOrder && groupRepeats && xmlSchemaGroupBase.Items.Count > 1)
            {
                ImportChoiceGroup(xmlSchemaGroupBase, identifier, members, membersScope, elementsScope, ns, groupRepeats, ref needExplicitOrder, allowDuplicates);
                return;
            }
            for (int i = 0; i < xmlSchemaGroupBase.Items.Count; i++)
            {
                object obj = xmlSchemaGroupBase.Items[i];
                if (obj is XmlSchemaChoice)
                {
                    ImportChoiceGroup((XmlSchemaGroupBase)obj, identifier, members, membersScope, elementsScope, ns, groupRepeats, ref needExplicitOrder, allowDuplicates);
                }
                else if (obj is XmlSchemaElement)
                {
                    ImportElementMember((XmlSchemaElement)obj, identifier, members, membersScope, elementsScope, ns, groupRepeats, ref needExplicitOrder, allowDuplicates, allowUnboundedElements);
                }
                else if (obj is XmlSchemaAny)
                {
                    ImportAnyMember((XmlSchemaAny)obj, identifier, members, membersScope, elementsScope, ns, ref mixed, ref needExplicitOrder, allowDuplicates);
                }
                else if (obj is XmlSchemaParticle)
                {
                    ImportGroupMembers((XmlSchemaParticle)obj, identifier, members, membersScope, elementsScope, ns, groupRepeats, ref mixed, ref needExplicitOrder, allowDuplicates, allowUnboundedElements: true);
                }
            }
        }
    }
References System.Xml.Serialization.SchemaImporter.AddReference(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.XmlSchemaImporter.FindGroup(), System.Xml.Serialization.XmlSchemaImporter.GenerateOrder, System.Xml.Serialization.XmlSchemaImporter.ImportAnyMember(), System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup(), System.Xml.Serialization.XmlSchemaImporter.ImportElementMember(), System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers(), System.obj, System.Xml.Schema.XmlSchemaGroup.Particle, System.Xml.Serialization.SchemaImporter.RemoveReference(), and System.SR.XmlCircularGroupReference.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportGroup(), and System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers().