Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportAttributeGroupMembers
ImportAttributeGroupMembers()
void System.Xml.Serialization.XmlSchemaImporter.ImportAttributeGroupMembers (XmlSchemaAttributeGroup group, string identifier, CodeIdentifiers members, CodeIdentifiers membersScope, string ns) inline private
Definition at line 1605 of file XmlSchemaImporter.cs.
    {
        for (int i = 0; i < group.Attributes.Count; i++)
        {
            object obj = group.Attributes[i];
            if (obj is XmlSchemaAttributeGroup)
            {
                ImportAttributeGroupMembers((XmlSchemaAttributeGroup)obj, identifier, members, membersScope, ns);
            }
            else if (obj is XmlSchemaAttribute)
            {
                ImportAttributeMember((XmlSchemaAttribute)obj, identifier, members, membersScope, ns);
            }
        }
        if (group.AnyAttribute != null)
        {
            ImportAnyAttributeMember(group.AnyAttribute, members, membersScope);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.XmlSchemaImporter.ImportAnyAttributeMember(), System.Xml.Serialization.XmlSchemaImporter.ImportAttributeGroupMembers(), System.Xml.Serialization.XmlSchemaImporter.ImportAttributeMember(), and System.obj.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportAttributeGroupMembers(), and System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers().