Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportStructDataType
ImportStructDataType()
StructMapping System.Xml.Serialization.XmlSchemaImporter.ImportStructDataType (XmlSchemaSimpleType dataType, string typeNs, string identifier, Type baseType) inline private
Definition at line 591 of file XmlSchemaImporter.cs.
    {
        identifier = Accessor.UnescapeName(identifier);
        string text = GenerateUniqueTypeName(identifier);
        StructMapping structMapping = new StructMapping();
        structMapping.IsReference = base.Schemas.IsReference(dataType);
        TypeFlags flags = TypeFlags.Reference;
        TypeDesc typeDesc = base.Scope.GetTypeDesc(baseType);
        structMapping.TypeDesc = new TypeDesc(text, text, TypeKind.Struct, typeDesc, flags);
        structMapping.Namespace = typeNs;
        structMapping.TypeName = identifier;
        CodeIdentifiers codeIdentifiers = new CodeIdentifiers();
        codeIdentifiers.AddReserved(text);
        AddReservedIdentifiersForDataBinding(codeIdentifiers);
        ImportTextMember(codeIdentifiers, new CodeIdentifiers(), null);
        structMapping.Members = (MemberMapping[])codeIdentifiers.ToArray(typeof(MemberMapping));
        structMapping.Scope = codeIdentifiers;
        base.Scope.AddTypeMapping(structMapping);
        return structMapping;
    }
References System.Xml.Serialization.SchemaImporter.AddReservedIdentifiersForDataBinding(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.GenerateUniqueTypeName(), System.Xml.Serialization.XmlSchemaImporter.ImportTextMember(), System.text, and System.Xml.Serialization.Accessor.UnescapeName().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportDataType().