Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportDerivedTypes
ImportDerivedTypes()
override void System.Xml.Serialization.XmlSchemaImporter.ImportDerivedTypes (XmlQualifiedName baseName) inline package
Definition at line 365 of file XmlSchemaImporter.cs.
    {
        foreach (XmlSchema schema in base.Schemas)
        {
            if (base.Schemas.IsReference(schema) || XmlSchemas.IsDataSet(schema))
            {
                continue;
            }
            XmlSchemas.Preprocess(schema);
            foreach (object value in schema.SchemaTypes.Values)
            {
                if (value is XmlSchemaType)
                {
                    XmlSchemaType xmlSchemaType = (XmlSchemaType)value;
                    if (xmlSchemaType.DerivedFrom == baseName && base.TypesInUse[xmlSchemaType.Name, schema.TargetNamespace] == null)
                    {
                        ImportType(xmlSchemaType.QualifiedName, typeof(TypeMapping), null, TypeFlags.CanBeElementValue, addref: false);
                    }
                }
            }
        }
    }
References System.Xml.Serialization.XmlSchemaImporter.ImportType(), System.Xml.Serialization.XmlSchemas.IsDataSet(), System.Xml.Serialization.XmlSchemas.Preprocess(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping(), and System.Xml.Serialization.XmlSchemaImporter.ImportType().