Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping
ImportArrayMapping()
ArrayMapping System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping (XmlSchemaType type, string identifier, string ns, bool repeats) inline private
Definition at line 1254 of file XmlSchemaImporter.cs.
    {
        if (!(type is XmlSchemaComplexType))
        {
            return null;
        }
        if (!type.DerivedFrom.IsEmpty)
        {
            return null;
        }
        if (IsMixed(type))
        {
            return null;
        }
        Mapping mapping = (Mapping)base.ImportedMappings[type];
        if (mapping != null)
        {
            if (mapping is ArrayMapping)
            {
                return (ArrayMapping)mapping;
            }
            return null;
        }
        TypeItems typeItems = GetTypeItems(type);
        if (typeItems.Attributes != null && typeItems.Attributes.Count > 0)
        {
            return null;
        }
        if (typeItems.AnyAttribute != null)
        {
            return null;
        }
        if (typeItems.Particle == null)
        {
            return null;
        }
        XmlSchemaGroupBase particle = typeItems.Particle;
        ArrayMapping arrayMapping = new ArrayMapping();
        arrayMapping.TypeName = identifier;
        arrayMapping.Namespace = ns;
        if (particle is XmlSchemaChoice)
        {
            XmlSchemaChoice xmlSchemaChoice = (XmlSchemaChoice)particle;
            if (!xmlSchemaChoice.IsMultipleOccurrence)
            {
                return null;
            }
            bool needExplicitOrder = false;
            MemberMapping memberMapping = ImportChoiceGroup(xmlSchemaChoice, identifier, null, null, null, ns, groupRepeats: true, ref needExplicitOrder, allowDuplicates: false);
            if (memberMapping.ChoiceIdentifier != null)
            {
                return null;
            }
            arrayMapping.TypeDesc = memberMapping.TypeDesc;
            arrayMapping.Elements = memberMapping.Elements;
            arrayMapping.TypeName = ((type.Name == null || type.Name.Length == 0) ? ("ArrayOf" + CodeIdentifier.MakePascal(arrayMapping.TypeDesc.Name)) : type.Name);
        }
        else
        {
            if (!(particle is XmlSchemaAll) && !(particle is XmlSchemaSequence))
            {
                return null;
            }
            if (particle.Items.Count != 1 || !(particle.Items[0] is XmlSchemaElement))
            {
                return null;
            }
            XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)particle.Items[0];
            if (!xmlSchemaElement.IsMultipleOccurrence)
            {
                return null;
            }
            if (IsCyclicReferencedType(xmlSchemaElement, new List<string>(1) { identifier }))
            {
                return null;
            }
            ElementAccessor elementAccessor = ImportElement(xmlSchemaElement, identifier, typeof(TypeMapping), null, ns, topLevelElement: false);
            if (elementAccessor.Any)
            {
                return null;
            }
            arrayMapping.Elements = new ElementAccessor[1] { elementAccessor };
            arrayMapping.TypeDesc = elementAccessor.Mapping.TypeDesc.CreateArrayTypeDesc();
            arrayMapping.TypeName = ((type.Name == null || type.Name.Length == 0) ? ("ArrayOf" + CodeIdentifier.MakePascal(elementAccessor.Mapping.TypeDesc.Name)) : type.Name);
        }
        base.ImportedMappings[type] = arrayMapping;
        base.Scope.AddTypeMapping(arrayMapping);
        arrayMapping.TopLevelMapping = ImportStructType(type, ns, identifier, null, arrayLike: true);
        arrayMapping.TopLevelMapping.ReferencedByTopLevelElement = true;
        if (type.Name != null && type.Name.Length != 0)
        {
            ImportDerivedTypes(new XmlQualifiedName(identifier, ns));
        }
        return arrayMapping;
    }
References System.Collections.CollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.GetTypeItems(), System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup(), System.Xml.Serialization.XmlSchemaImporter.ImportDerivedTypes(), System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.Xml.Serialization.XmlSchemaImporter.ImportStructType(), System.Xml.Serialization.XmlSchemaImporter.IsCyclicReferencedType(), System.Xml.Serialization.XmlSchemaImporter.IsMixed(), System.Xml.Schema.XmlSchemaGroupBase.Items, System.Xml.Serialization.CodeIdentifier.MakePascal(), and System.type.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportArray(), and System.Xml.Serialization.XmlSchemaImporter.ImportType().