Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportAny
ImportAny()
ElementAccessor[] System.Xml.Serialization.XmlSchemaImporter.ImportAny (XmlSchemaAny any, bool makeElement, string targetNamespace) inline private
Definition at line 1181 of file XmlSchemaImporter.cs.
    {
        SpecialMapping specialMapping = new SpecialMapping();
        specialMapping.TypeDesc = base.Scope.GetTypeDesc(makeElement ? typeof(XmlElement) : typeof(XmlNode));
        specialMapping.TypeName = specialMapping.TypeDesc.Name;
        TypeFlags typeFlags = TypeFlags.CanBeElementValue;
        if (makeElement)
        {
            typeFlags |= TypeFlags.CanBeTextValue;
        }
        RunSchemaExtensions(specialMapping, XmlQualifiedName.Empty, null, any, typeFlags);
        if (GenerateOrder && any.Namespace != null)
        {
            NamespaceList namespaceList = new NamespaceList(any.Namespace, targetNamespace);
            if (namespaceList.Type == NamespaceList.ListType.Set)
            {
                ICollection enumerate = namespaceList.Enumerate;
                ElementAccessor[] array = new ElementAccessor[(enumerate.Count == 0) ? 1 : enumerate.Count];
                int num = 0;
                foreach (string item in namespaceList.Enumerate)
                {
                    ElementAccessor elementAccessor = new ElementAccessor();
                    elementAccessor.Mapping = specialMapping;
                    elementAccessor.Any = true;
                    elementAccessor.Namespace = item;
                    array[num++] = elementAccessor;
                }
                if (num > 0)
                {
                    return array;
                }
            }
        }
        ElementAccessor elementAccessor2 = new ElementAccessor();
        elementAccessor2.Mapping = specialMapping;
        elementAccessor2.Any = true;
        return new ElementAccessor[1] { elementAccessor2 };
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.NamespaceList.Enumerate, System.Xml.Serialization.XmlSchemaImporter.GenerateOrder, System.item, System.Xml.Serialization.XmlSchemaImporter.RunSchemaExtensions(), and System.Xml.Schema.NamespaceList.Type.
Referenced by System.Xml.Serialization.XmlSchemaImporter.GatherGroupChoices(), and System.Xml.Serialization.XmlSchemaImporter.ImportAnyMember().