Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportSchemaType
ImportSchemaType() [3/3]
XmlTypeMapping System.Xml.Serialization.XmlSchemaImporter.ImportSchemaType (XmlQualifiedName typeName, Type? baseType, bool baseTypeCanBeIndirect) inline
Definition at line 96 of file XmlSchemaImporter.cs.
    {
        TypeMapping typeMapping = ImportType(typeName, typeof(TypeMapping), baseType, TypeFlags.CanBeElementValue, addref: true);
        typeMapping.ReferencedByElement = false;
        ElementAccessor elementAccessor = new ElementAccessor();
        elementAccessor.IsTopLevelInSchema = true;
        elementAccessor.Name = typeName.Name;
        elementAccessor.Namespace = typeName.Namespace;
        elementAccessor.Mapping = typeMapping;
        if (typeMapping is SpecialMapping && ((SpecialMapping)typeMapping).NamedAny)
        {
            elementAccessor.Any = true;
        }
        elementAccessor.IsNullable = typeMapping.TypeDesc.IsNullable;
        elementAccessor.Form = XmlSchemaForm.Qualified;
        if (elementAccessor.Mapping is StructMapping)
        {
            MakeDerived((StructMapping)elementAccessor.Mapping, baseType, baseTypeCanBeIndirect);
        }
        else if (baseType != null)
        {
            if (!(elementAccessor.Mapping is ArrayMapping))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlBadBaseType, typeName.Name, typeName.Namespace, baseType.FullName));
            }
            elementAccessor.Mapping = ((ArrayMapping)elementAccessor.Mapping).TopLevelMapping;
            MakeDerived((StructMapping)elementAccessor.Mapping, baseType, baseTypeCanBeIndirect);
        }
        return new XmlTypeMapping(base.Scope, elementAccessor);
    }
References System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.XmlSchemaImporter.ImportType(), System.Xml.Serialization.SchemaImporter.MakeDerived(), System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, and System.SR.XmlBadBaseType.