Terraria: System.Xml.Serialization.XmlSchemaImporter.ElementForm
ElementForm()
XmlSchemaForm System.Xml.Serialization.XmlSchemaImporter.ElementForm (string ns, XmlSchemaElement element) inline private
Definition at line 2011 of file XmlSchemaImporter.cs.
    {
        if (element.Form == XmlSchemaForm.None)
        {
            XmlSchemaObject xmlSchemaObject = element;
            while (xmlSchemaObject.Parent != null)
            {
                xmlSchemaObject = xmlSchemaObject.Parent;
            }
            if (xmlSchemaObject is XmlSchema xmlSchema)
            {
                if (ns == null || ns.Length == 0)
                {
                    if (xmlSchema.ElementFormDefault != 0)
                    {
                        return xmlSchema.ElementFormDefault;
                    }
                    return XmlSchemaForm.Unqualified;
                }
                XmlSchemas.Preprocess(xmlSchema);
                if (element.QualifiedName.Namespace != null && element.QualifiedName.Namespace.Length != 0)
                {
                    return XmlSchemaForm.Qualified;
                }
                return XmlSchemaForm.Unqualified;
            }
            return XmlSchemaForm.Qualified;
        }
        return element.Form;
    }
References System.Xml.Schema.XmlSchemaElement.Form, System.Xml.XmlQualifiedName.Namespace, System.Xml.Serialization.XmlSchemas.Preprocess(), and System.Xml.Schema.XmlSchemaElement.QualifiedName.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportArray(), and System.Xml.Serialization.XmlSchemaImporter.ImportElement().