Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportAttribute
ImportAttribute()
AttributeAccessor System.Xml.Serialization.XmlSchemaImporter.ImportAttribute (XmlSchemaAttribute attribute, string identifier, string ns, XmlSchemaAttribute defaultValueProvider) inline private
Definition at line 1640 of file XmlSchemaImporter.cs.
    {
        if (attribute.Use == XmlSchemaUse.Prohibited)
        {
            return null;
        }
        if (!attribute.RefName.IsEmpty)
        {
            if (attribute.RefName.Namespace == "http://www.w3.org/XML/1998/namespace")
            {
                return ImportSpecialAttribute(attribute.RefName, identifier);
            }
            return ImportAttribute(FindAttribute(attribute.RefName), identifier, attribute.RefName.Namespace, defaultValueProvider);
        }
        if (attribute.Name.Length == 0)
        {
            throw new InvalidOperationException(System.SR.XmlAttributeHasNoName);
        }
        identifier = ((identifier.Length != 0) ? (identifier + CodeIdentifier.MakePascal(attribute.Name)) : CodeIdentifier.MakeValid(attribute.Name));
        TypeMapping typeMapping = ((!attribute.SchemaTypeName.IsEmpty) ? ImportType(attribute.SchemaTypeName, typeof(TypeMapping), null, TypeFlags.CanBeAttributeValue, addref: false) : ((attribute.SchemaType == null) ? GetDefaultMapping(TypeFlags.CanBeAttributeValue) : ImportDataType(attribute.SchemaType, ns, identifier, null, TypeFlags.CanBeAttributeValue, isList: false)));
        if (typeMapping != null && !typeMapping.TypeDesc.IsMappedType)
        {
            RunSchemaExtensions(typeMapping, attribute.SchemaTypeName, attribute.SchemaType, attribute, (TypeFlags)56);
        }
        AttributeAccessor attributeAccessor = new AttributeAccessor();
        attributeAccessor.Name = attribute.Name;
        attributeAccessor.Namespace = ns;
        attributeAccessor.Form = AttributeForm(ns, attribute);
        attributeAccessor.CheckSpecial();
        attributeAccessor.Mapping = typeMapping;
        attributeAccessor.IsList = typeMapping.IsList;
        attributeAccessor.IsOptional = attribute.Use != XmlSchemaUse.Required;
        if (defaultValueProvider.DefaultValue != null)
        {
            attributeAccessor.Default = defaultValueProvider.DefaultValue;
        }
        else if (defaultValueProvider.FixedValue != null)
        {
            attributeAccessor.Default = defaultValueProvider.FixedValue;
            attributeAccessor.IsFixed = true;
        }
        else if (attribute != defaultValueProvider)
        {
            if (attribute.DefaultValue != null)
            {
                attributeAccessor.Default = attribute.DefaultValue;
            }
            else if (attribute.FixedValue != null)
            {
                attributeAccessor.Default = attribute.FixedValue;
                attributeAccessor.IsFixed = true;
            }
        }
        return attributeAccessor;
    }
References System.Xml.Serialization.XmlSchemaImporter.AttributeForm(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindAttribute(), System.Xml.Serialization.XmlSchemaImporter.GetDefaultMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportAttribute(), System.Xml.Serialization.XmlSchemaImporter.ImportDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportSpecialAttribute(), System.Xml.Serialization.XmlSchemaImporter.ImportType(), System.Xml.Serialization.CodeIdentifier.MakePascal(), System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Serialization.XmlSchemaImporter.RunSchemaExtensions(), and System.SR.XmlAttributeHasNoName.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportAttribute(), and System.Xml.Serialization.XmlSchemaImporter.ImportAttributeMember().