Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportElement
ImportElement() [2/2]
ElementAccessor System.Xml.Serialization.XmlSchemaImporter.ImportElement (XmlSchemaElement element, string identifier, Type desiredMappingType, Type baseType, string ns, bool topLevelElement) inline private
Definition at line 250 of file XmlSchemaImporter.cs.
    {
        if (!element.RefName.IsEmpty)
        {
            ElementAccessor elementAccessor = ImportElement(element.RefName, desiredMappingType, baseType);
            if (element.IsMultipleOccurrence && elementAccessor.Mapping is ArrayMapping)
            {
                ElementAccessor elementAccessor2 = elementAccessor.Clone();
                elementAccessor2.IsTopLevelInSchema = false;
                elementAccessor2.Mapping.ReferencedByElement = true;
                return elementAccessor2;
            }
            return elementAccessor;
        }
        if (element.Name.Length == 0)
        {
            XmlQualifiedName parentName = XmlSchemas.GetParentName(element);
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlElementHasNoName, parentName.Name, parentName.Namespace));
        }
        string identifier2 = Accessor.UnescapeName(element.Name);
        identifier = ((identifier.Length != 0) ? (identifier + CodeIdentifier.MakePascal(identifier2)) : CodeIdentifier.MakeValid(identifier2));
        TypeMapping typeMapping = ImportElementType(element, identifier, desiredMappingType, baseType, ns);
        ElementAccessor elementAccessor3 = new ElementAccessor();
        elementAccessor3.IsTopLevelInSchema = element.Parent is XmlSchema;
        elementAccessor3.Name = element.Name;
        elementAccessor3.Namespace = ns;
        elementAccessor3.Mapping = typeMapping;
        elementAccessor3.IsOptional = element.MinOccurs == 0m;
        if (element.DefaultValue != null)
        {
            elementAccessor3.Default = element.DefaultValue;
        }
        else if (element.FixedValue != null)
        {
            elementAccessor3.Default = element.FixedValue;
            elementAccessor3.IsFixed = true;
        }
        if (typeMapping is SpecialMapping && ((SpecialMapping)typeMapping).NamedAny)
        {
            elementAccessor3.Any = true;
        }
        elementAccessor3.IsNullable = element.IsNillable;
        if (topLevelElement)
        {
            elementAccessor3.Form = XmlSchemaForm.Qualified;
        }
        else
        {
            elementAccessor3.Form = ElementForm(ns, element);
        }
        return elementAccessor3;
    }
References System.Xml.Schema.XmlSchemaElement.DefaultValue, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.ElementForm(), System.Xml.Schema.XmlSchemaElement.FixedValue, System.SR.Format(), System.Xml.Serialization.XmlSchemas.GetParentName(), System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.Xml.Serialization.XmlSchemaImporter.ImportElementType(), System.Xml.XmlQualifiedName.IsEmpty, System.Xml.Schema.XmlSchemaParticle.IsMultipleOccurrence, System.Xml.Schema.XmlSchemaElement.IsNillable, System.Xml.Serialization.CodeIdentifier.MakePascal(), System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Schema.XmlSchemaElement.Name, System.Xml.Schema.XmlSchemaElement.RefName, System.Xml.Serialization.Accessor.UnescapeName(), and System.SR.XmlElementHasNoName.