Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportDataType
ImportDataType()
TypeMapping System.Xml.Serialization.XmlSchemaImporter.ImportDataType (XmlSchemaSimpleType dataType, string typeNs, string identifier, Type baseType, TypeFlags flags, bool isList) inline private
Definition at line 1697 of file XmlSchemaImporter.cs.
    {
        if (baseType != null)
        {
            return ImportStructDataType(dataType, typeNs, identifier, baseType);
        }
        TypeMapping typeMapping = ImportNonXsdPrimitiveDataType(dataType, typeNs, flags);
        if (typeMapping != null)
        {
            return typeMapping;
        }
        if (dataType.Content is XmlSchemaSimpleTypeRestriction)
        {
            XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = (XmlSchemaSimpleTypeRestriction)dataType.Content;
            foreach (XmlSchemaObject facet in xmlSchemaSimpleTypeRestriction.Facets)
            {
                if (facet is XmlSchemaEnumerationFacet)
                {
                    return ImportEnumeratedDataType(dataType, typeNs, identifier, flags, isList);
                }
            }
            if (xmlSchemaSimpleTypeRestriction.BaseType != null)
            {
                return ImportDataType(xmlSchemaSimpleTypeRestriction.BaseType, typeNs, identifier, null, flags, isList: false);
            }
            AddReference(xmlSchemaSimpleTypeRestriction.BaseTypeName, base.TypesInUse, System.SR.XmlCircularTypeReference);
            typeMapping = ImportDataType(FindDataType(xmlSchemaSimpleTypeRestriction.BaseTypeName, flags), xmlSchemaSimpleTypeRestriction.BaseTypeName.Namespace, identifier, null, flags, isList: false);
            if (xmlSchemaSimpleTypeRestriction.BaseTypeName.Namespace != "http://www.w3.org/2001/XMLSchema")
            {
                RemoveReference(xmlSchemaSimpleTypeRestriction.BaseTypeName, base.TypesInUse);
            }
            return typeMapping;
        }
        if (dataType.Content is XmlSchemaSimpleTypeList || dataType.Content is XmlSchemaSimpleTypeUnion)
        {
            if (dataType.Content is XmlSchemaSimpleTypeList)
            {
                XmlSchemaSimpleTypeList xmlSchemaSimpleTypeList = (XmlSchemaSimpleTypeList)dataType.Content;
                if (xmlSchemaSimpleTypeList.ItemType != null)
                {
                    typeMapping = ImportDataType(xmlSchemaSimpleTypeList.ItemType, typeNs, identifier, null, flags, isList: true);
                    if (typeMapping != null)
                    {
                        typeMapping.TypeName = dataType.Name;
                        return typeMapping;
                    }
                }
                else if (xmlSchemaSimpleTypeList.ItemTypeName != null && !xmlSchemaSimpleTypeList.ItemTypeName.IsEmpty)
                {
                    typeMapping = ImportType(xmlSchemaSimpleTypeList.ItemTypeName, typeof(TypeMapping), null, TypeFlags.CanBeAttributeValue, addref: true);
                    if (typeMapping != null && typeMapping is PrimitiveMapping)
                    {
                        ((PrimitiveMapping)typeMapping).IsList = true;
                        return typeMapping;
                    }
                }
            }
            return GetDefaultMapping(flags);
        }
        return ImportPrimitiveDataType(dataType, flags);
    }
References System.Xml.Serialization.SchemaImporter.AddReference(), System.Xml.Schema.XmlSchemaSimpleType.Content, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindDataType(), System.Xml.Serialization.XmlSchemaImporter.GetDefaultMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportEnumeratedDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportNonXsdPrimitiveDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportPrimitiveDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportStructDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportType(), System.Xml.Serialization.TypeMapping.IsList, System.Xml.Schema.XmlSchemaType.Name, System.Xml.Serialization.SchemaImporter.RemoveReference(), and System.SR.XmlCircularTypeReference.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportAttribute(), System.Xml.Serialization.XmlSchemaImporter.ImportDataType(), System.Xml.Serialization.XmlSchemaImporter.ImportElementType(), and System.Xml.Serialization.XmlSchemaImporter.ImportType().