Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers
ImportTypeMembers()
MemberMapping[] System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers (XmlSchemaType type, string typeNs, string identifier, CodeIdentifiers members, CodeIdentifiers membersScope, INameScope elementsScope, ref bool needExplicitOrder, bool order, bool allowUnboundedElements) inline private
Definition at line 613 of file XmlSchemaImporter.cs.
    {
        TypeItems typeItems = GetTypeItems(type);
        bool flag = IsMixed(type);
        if (flag)
        {
            XmlSchemaType xmlSchemaType = type;
            while (!xmlSchemaType.DerivedFrom.IsEmpty)
            {
                xmlSchemaType = FindType(xmlSchemaType.DerivedFrom, (TypeFlags)48);
                if (IsMixed(xmlSchemaType))
                {
                    flag = false;
                    break;
                }
            }
        }
        if (typeItems.Particle != null)
        {
            ImportGroup(typeItems.Particle, identifier, members, membersScope, elementsScope, typeNs, flag, ref needExplicitOrder, order, typeItems.IsUnbounded, allowUnboundedElements);
        }
        for (int i = 0; i < typeItems.Attributes.Count; i++)
        {
            object obj = typeItems.Attributes[i];
            if (obj is XmlSchemaAttribute)
            {
                ImportAttributeMember((XmlSchemaAttribute)obj, identifier, members, membersScope, typeNs);
            }
            else if (obj is XmlSchemaAttributeGroupRef)
            {
                XmlQualifiedName refName = ((XmlSchemaAttributeGroupRef)obj).RefName;
                ImportAttributeGroupMembers(FindAttributeGroup(refName), identifier, members, membersScope, refName.Namespace);
            }
        }
        if (typeItems.AnyAttribute != null)
        {
            ImportAnyAttributeMember(typeItems.AnyAttribute, members, membersScope);
        }
        if (typeItems.baseSimpleType != null || (typeItems.Particle == null && flag))
        {
            ImportTextMember(members, membersScope, flag ? null : typeItems.baseSimpleType);
        }
        ImportXmlnsDeclarationsMember(type, members, membersScope);
        return (MemberMapping[])members.ToArray(typeof(MemberMapping));
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindAttributeGroup(), System.Xml.Serialization.XmlSchemaImporter.FindType(), System.Xml.Serialization.XmlSchemaImporter.GetTypeItems(), System.Xml.Serialization.XmlSchemaImporter.ImportAnyAttributeMember(), System.Xml.Serialization.XmlSchemaImporter.ImportAttributeGroupMembers(), System.Xml.Serialization.XmlSchemaImporter.ImportAttributeMember(), System.Xml.Serialization.XmlSchemaImporter.ImportGroup(), System.Xml.Serialization.XmlSchemaImporter.ImportTextMember(), System.Xml.Serialization.XmlSchemaImporter.ImportXmlnsDeclarationsMember(), System.Xml.Serialization.XmlSchemaImporter.IsMixed(), System.obj, and System.type.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportMembersType(), and System.Xml.Serialization.XmlSchemaImporter.ImportStructType().