Terraria: System.Xml.Serialization.XmlSchemaImporter.AddScopeElements
AddScopeElements()
void System.Xml.Serialization.XmlSchemaImporter.AddScopeElements (INameScope scope, ElementAccessor[] elements, ref bool duplicateElements, bool allowDuplicates) inline private
Definition at line 991 of file XmlSchemaImporter.cs.
    {
        for (int i = 0; i < elements.Length; i++)
        {
            AddScopeElement(scope, elements[i], ref duplicateElements, allowDuplicates);
        }
    }
References System.Xml.Serialization.XmlSchemaImporter.AddScopeElement().
Referenced by System.Xml.Serialization.XmlSchemaImporter.GatherGroupChoices(), System.Xml.Serialization.XmlSchemaImporter.ImportAnyMember(), and System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup().