Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportStructType
ImportStructType()
StructMapping System.Xml.Serialization.XmlSchemaImporter.ImportStructType (XmlSchemaType type, string typeNs, string identifier, Type baseType, bool arrayLike) inline private
Definition at line 474 of file XmlSchemaImporter.cs.
    {
        TypeDesc typeDesc = null;
        TypeMapping typeMapping = null;
        bool flag = false;
        if (!type.DerivedFrom.IsEmpty)
        {
            typeMapping = ImportType(type.DerivedFrom, typeof(TypeMapping), null, (TypeFlags)48, addref: false);
            if (typeMapping is StructMapping)
            {
                typeDesc = ((StructMapping)typeMapping).TypeDesc;
            }
            else if (typeMapping is ArrayMapping)
            {
                typeMapping = ((ArrayMapping)typeMapping).TopLevelMapping;
                if (typeMapping != null)
                {
                    typeMapping.ReferencedByTopLevelElement = false;
                    typeMapping.ReferencedByElement = true;
                    typeDesc = typeMapping.TypeDesc;
                }
            }
            else
            {
                typeMapping = null;
            }
        }
        if (typeDesc == null && baseType != null)
        {
            typeDesc = base.Scope.GetTypeDesc(baseType);
        }
        if (typeMapping == null)
        {
            typeMapping = GetRootMapping();
            flag = true;
        }
        Mapping mapping = (Mapping)base.ImportedMappings[type];
        if (mapping != null)
        {
            if (mapping is StructMapping)
            {
                return (StructMapping)mapping;
            }
            if (!arrayLike || !(mapping is ArrayMapping))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlTypeUsedTwice, type.QualifiedName.Name, type.QualifiedName.Namespace));
            }
            ArrayMapping arrayMapping = (ArrayMapping)mapping;
            if (arrayMapping.TopLevelMapping != null)
            {
                return arrayMapping.TopLevelMapping;
            }
        }
        StructMapping structMapping = new StructMapping();
        structMapping.IsReference = base.Schemas.IsReference(type);
        TypeFlags typeFlags = TypeFlags.Reference;
        if (type is XmlSchemaComplexType && ((XmlSchemaComplexType)type).IsAbstract)
        {
            typeFlags |= TypeFlags.Abstract;
        }
        identifier = Accessor.UnescapeName(identifier);
        string text = ((type.Name == null || type.Name.Length == 0) ? GenerateUniqueTypeName(identifier, typeNs) : GenerateUniqueTypeName(identifier));
        structMapping.TypeDesc = new TypeDesc(text, text, TypeKind.Struct, typeDesc, typeFlags);
        structMapping.Namespace = typeNs;
        structMapping.TypeName = ((type.Name == null || type.Name.Length == 0) ? null : identifier);
        structMapping.BaseMapping = (StructMapping)typeMapping;
        if (!arrayLike)
        {
            base.ImportedMappings.Add(type, structMapping);
        }
        CodeIdentifiers codeIdentifiers = new CodeIdentifiers();
        CodeIdentifiers codeIdentifiers2 = structMapping.BaseMapping.Scope.Clone();
        codeIdentifiers.AddReserved(text);
        codeIdentifiers2.AddReserved(text);
        AddReservedIdentifiersForDataBinding(codeIdentifiers);
        if (flag)
        {
            AddReservedIdentifiersForDataBinding(codeIdentifiers2);
        }
        bool needExplicitOrder = false;
        structMapping.Members = ImportTypeMembers(type, typeNs, identifier, codeIdentifiers, codeIdentifiers2, structMapping, ref needExplicitOrder, order: true, allowUnboundedElements: true);
        if (!IsAllGroup(type))
        {
            if (needExplicitOrder && !GenerateOrder)
            {
                structMapping.SetSequence();
            }
            else if (GenerateOrder)
            {
                structMapping.IsSequence = true;
            }
        }
        for (int i = 0; i < structMapping.Members.Length; i++)
        {
            StructMapping declaringMapping;
            MemberMapping memberMapping = ((StructMapping)typeMapping).FindDeclaringMapping(structMapping.Members[i], out declaringMapping, structMapping.TypeName);
            if (memberMapping != null && memberMapping.TypeDesc != structMapping.Members[i].TypeDesc)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalOverride, type.Name, memberMapping.Name, memberMapping.TypeDesc.FullName, structMapping.Members[i].TypeDesc.FullName, declaringMapping.TypeDesc.FullName));
            }
        }
        structMapping.Scope = codeIdentifiers2;
        base.Scope.AddTypeMapping(structMapping);
        return structMapping;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.SchemaImporter.AddReservedIdentifiersForDataBinding(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.XmlSchemaImporter.GenerateOrder, System.Xml.Serialization.XmlSchemaImporter.GenerateUniqueTypeName(), System.Xml.Serialization.SchemaImporter.GetRootMapping(), System.Xml.Serialization.XmlSchemaImporter.ImportType(), System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers(), System.Xml.Serialization.XmlSchemaImporter.IsAllGroup(), System.text, System.type, System.Xml.Serialization.Accessor.UnescapeName(), System.SR.XmlIllegalOverride, and System.SR.XmlTypeUsedTwice.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping(), and System.Xml.Serialization.XmlSchemaImporter.ImportType().