Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportAnyAttributeMember
ImportAnyAttributeMember()
void System.Xml.Serialization.XmlSchemaImporter.ImportAnyAttributeMember (XmlSchemaAnyAttribute any, CodeIdentifiers members, CodeIdentifiers membersScope) inline private
Definition at line 1518 of file XmlSchemaImporter.cs.
    {
        SpecialMapping specialMapping = new SpecialMapping();
        specialMapping.TypeDesc = base.Scope.GetTypeDesc(typeof(XmlAttribute));
        specialMapping.TypeName = specialMapping.TypeDesc.Name;
        AttributeAccessor attributeAccessor = new AttributeAccessor();
        attributeAccessor.Any = true;
        attributeAccessor.Mapping = specialMapping;
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.Elements = Array.Empty<ElementAccessor>();
        memberMapping.Attribute = attributeAccessor;
        memberMapping.Name = membersScope.MakeRightCase("AnyAttr");
        memberMapping.Name = membersScope.AddUnique(memberMapping.Name, memberMapping);
        members.Add(memberMapping.Name, memberMapping);
        memberMapping.TypeDesc = attributeAccessor.Mapping.TypeDesc;
        memberMapping.TypeDesc = memberMapping.TypeDesc.CreateArrayTypeDesc();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), and System.Xml.Dictionary.
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportAttributeGroupMembers(), and System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers().