Terraria: System.Xml.Serialization.XmlSchemaImporter.GetDataTypeSource
GetDataTypeSource()
TypeDesc System.Xml.Serialization.XmlSchemaImporter.GetDataTypeSource (XmlSchemaSimpleType dataType, TypeFlags flags) inline private
Definition at line 1927 of file XmlSchemaImporter.cs.
    {
        TypeDesc typeDesc = null;
        if (dataType.Name != null && dataType.Name.Length != 0)
        {
            typeDesc = base.Scope.GetTypeDesc(dataType);
            if (typeDesc != null)
            {
                return typeDesc;
            }
        }
        XmlQualifiedName xmlQualifiedName = BaseTypeName(dataType);
        AddReference(xmlQualifiedName, base.TypesInUse, System.SR.XmlCircularTypeReference);
        typeDesc = GetDataTypeSource(FindDataType(xmlQualifiedName, flags), flags);
        if (xmlQualifiedName.Namespace != "http://www.w3.org/2001/XMLSchema")
        {
            RemoveReference(xmlQualifiedName, base.TypesInUse);
        }
        return typeDesc;
    }
References System.Xml.Serialization.SchemaImporter.AddReference(), System.Xml.Serialization.XmlSchemaImporter.BaseTypeName(), System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.FindDataType(), System.Xml.Serialization.XmlSchemaImporter.GetDataTypeSource(), System.Xml.Schema.XmlSchemaType.Name, System.Xml.Serialization.SchemaImporter.RemoveReference(), and System.SR.XmlCircularTypeReference.
Referenced by System.Xml.Serialization.XmlSchemaImporter.GetDataTypeSource(), and System.Xml.Serialization.XmlSchemaImporter.ImportPrimitiveDataType().