Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping
ImportMembersMapping() [1/4]
XmlMembersMapping System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping (string name, string? ns, SoapSchemaMember[] members) inline
Definition at line 209 of file XmlSchemaImporter.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = new XmlSchemaComplexType();
        XmlSchemaSequence xmlSchemaSequence = (XmlSchemaSequence)(xmlSchemaComplexType.Particle = new XmlSchemaSequence());
        foreach (SoapSchemaMember soapSchemaMember in members)
        {
            XmlSchemaElement xmlSchemaElement = new XmlSchemaElement();
            xmlSchemaElement.Name = soapSchemaMember.MemberName;
            xmlSchemaElement.SchemaTypeName = soapSchemaMember.MemberType;
            xmlSchemaSequence.Items.Add(xmlSchemaElement);
        }
        MembersMapping mapping = ImportMembersType(xmlSchemaComplexType, null, name);
        ElementAccessor elementAccessor = new ElementAccessor();
        elementAccessor.Name = Accessor.EscapeName(name);
        elementAccessor.Namespace = ns;
        elementAccessor.Mapping = mapping;
        elementAccessor.IsNullable = false;
        elementAccessor.Form = XmlSchemaForm.Qualified;
        return new XmlMembersMapping(base.Scope, elementAccessor, XmlMappingAccess.Read | XmlMappingAccess.Write);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Serialization.Accessor.EscapeName(), and System.Xml.Serialization.XmlSchemaImporter.ImportMembersType().