Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping
ImportMembersMapping() [4/4]
XmlMembersMapping System.Xml.Serialization.XmlSchemaImporter.ImportMembersMapping (XmlQualifiedName[] names, Type? baseType, bool baseTypeCanBeIndirect) inline
Definition at line 179 of file XmlSchemaImporter.cs.
    {
        CodeIdentifiers codeIdentifiers = new CodeIdentifiers();
        codeIdentifiers.UseCamelCasing = true;
        MemberMapping[] array = new MemberMapping[names.Length];
        for (int i = 0; i < names.Length; i++)
        {
            XmlQualifiedName name = names[i];
            ElementAccessor elementAccessor = ImportElement(name, typeof(TypeMapping), baseType);
            if (baseType != null && elementAccessor.Mapping is StructMapping)
            {
                MakeDerived((StructMapping)elementAccessor.Mapping, baseType, baseTypeCanBeIndirect);
            }
            MemberMapping memberMapping = new MemberMapping();
            memberMapping.Name = CodeIdentifier.MakeValid(Accessor.UnescapeName(elementAccessor.Name));
            memberMapping.Name = codeIdentifiers.AddUnique(memberMapping.Name, memberMapping);
            memberMapping.TypeDesc = elementAccessor.Mapping.TypeDesc;
            memberMapping.Elements = new ElementAccessor[1] { elementAccessor };
            array[i] = memberMapping;
        }
        MembersMapping membersMapping = new MembersMapping();
        membersMapping.HasWrapperElement = false;
        membersMapping.TypeDesc = base.Scope.GetTypeDesc(typeof(object[]));
        membersMapping.Members = array;
        ElementAccessor elementAccessor2 = new ElementAccessor();
        elementAccessor2.Mapping = membersMapping;
        return new XmlMembersMapping(base.Scope, elementAccessor2, XmlMappingAccess.Read | XmlMappingAccess.Write);
    }
References System.array, System.Xml.Dictionary, System.Xml.Serialization.XmlSchemaImporter.ImportElement(), System.Xml.Serialization.SchemaImporter.MakeDerived(), System.Xml.Serialization.CodeIdentifier.MakeValid(), and System.Xml.Serialization.Accessor.UnescapeName().