Terraria: System.Xml.Serialization.XmlSchemaImporter.ImportGroup
ImportGroup()
void System.Xml.Serialization.XmlSchemaImporter.ImportGroup (XmlSchemaGroupBase group, string identifier, CodeIdentifiers members, CodeIdentifiers membersScope, INameScope elementsScope, string ns, bool mixed, ref bool needExplicitOrder, bool allowDuplicates, bool groupRepeats, bool allowUnboundedElements) inline private
Definition at line 721 of file XmlSchemaImporter.cs.
    {
        if (group is XmlSchemaChoice)
        {
            ImportChoiceGroup((XmlSchemaChoice)group, identifier, members, membersScope, elementsScope, ns, groupRepeats, ref needExplicitOrder, allowDuplicates);
        }
        else
        {
            ImportGroupMembers(group, identifier, members, membersScope, elementsScope, ns, groupRepeats, ref mixed, ref needExplicitOrder, allowDuplicates, allowUnboundedElements);
        }
        if (mixed)
        {
            ImportTextMember(members, membersScope, null);
        }
    }
References System.Xml.Serialization.XmlSchemaImporter.ImportChoiceGroup(), System.Xml.Serialization.XmlSchemaImporter.ImportGroupMembers(), and System.Xml.Serialization.XmlSchemaImporter.ImportTextMember().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportTypeMembers().