Terraria: System.Xml.Serialization.XmlSchemaImporter.IsCyclicReferencedType
IsCyclicReferencedType()
bool System.Xml.Serialization.XmlSchemaImporter.IsCyclicReferencedType (XmlSchemaElement element, List< string > identifiers) inline private
Definition at line 1350 of file XmlSchemaImporter.cs.
    {
        if (!element.RefName.IsEmpty)
        {
            XmlSchemaElement xmlSchemaElement = FindElement(element.RefName);
            string text = CodeIdentifier.MakeValid(Accessor.UnescapeName(xmlSchemaElement.Name));
            foreach (string identifier in identifiers)
            {
                if (text == identifier)
                {
                    return true;
                }
            }
            identifiers.Add(text);
            XmlSchemaType schemaType = xmlSchemaElement.SchemaType;
            if (schemaType is XmlSchemaComplexType)
            {
                TypeItems typeItems = GetTypeItems(schemaType);
                if ((typeItems.Particle is XmlSchemaSequence || typeItems.Particle is XmlSchemaAll) && typeItems.Particle.Items.Count == 1 && typeItems.Particle.Items[0] is XmlSchemaElement)
                {
                    XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)typeItems.Particle.Items[0];
                    if (xmlSchemaElement2.IsMultipleOccurrence)
                    {
                        return IsCyclicReferencedType(xmlSchemaElement2, identifiers);
                    }
                }
            }
        }
        return false;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.XmlSchemaImporter.FindElement(), System.Xml.Serialization.XmlSchemaImporter.GetTypeItems(), System.Xml.Serialization.XmlSchemaImporter.IsCyclicReferencedType(), System.Xml.XmlQualifiedName.IsEmpty, System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Schema.XmlSchemaElement.RefName, System.text, and System.Xml.Serialization.Accessor.UnescapeName().
Referenced by System.Xml.Serialization.XmlSchemaImporter.ImportArrayMapping(), and System.Xml.Serialization.XmlSchemaImporter.IsCyclicReferencedType().