Terraria: System.Xml.Xsl.Runtime.XmlExtensionFunction.Bind
Bind() [1/2]
void System.Xml.Xsl.Runtime.XmlExtensionFunction.Bind () inline
Definition at line 94 of file XmlExtensionFunction.cs.
    {
        MethodInfo[] methods = _objectType.GetMethods(_flags);
        MethodInfo methodInfo = null;
        StringComparison comparisonType = (((_flags & BindingFlags.IgnoreCase) != 0) ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal);
        MethodInfo[] array = methods;
        foreach (MethodInfo methodInfo2 in array)
        {
            if (methodInfo2.Name.Equals(_name, comparisonType) && (_numArgs == -1 || methodInfo2.GetParameters().Length == _numArgs))
            {
                if (methodInfo != null)
                {
                    throw new XslTransformException(System.SR.XmlIl_AmbiguousExtensionMethod, _namespaceUri, _name, _numArgs.ToString(CultureInfo.InvariantCulture));
                }
                methodInfo = methodInfo2;
            }
        }
        if (methodInfo == null)
        {
            methods = _objectType.GetMethods(_flags | BindingFlags.NonPublic);
            MethodInfo[] array2 = methods;
            foreach (MethodInfo methodInfo3 in array2)
            {
                if (methodInfo3.Name.Equals(_name, comparisonType) && methodInfo3.GetParameters().Length == _numArgs)
                {
                    throw new XslTransformException(System.SR.XmlIl_NonPublicExtensionMethod, _namespaceUri, _name);
                }
            }
            throw new XslTransformException(System.SR.XmlIl_NoExtensionMethod, _namespaceUri, _name, _numArgs.ToString(CultureInfo.InvariantCulture));
        }
        if (methodInfo.IsGenericMethodDefinition)
        {
            throw new XslTransformException(System.SR.XmlIl_GenericExtensionMethod, _namespaceUri, _name);
        }
        Bind(methodInfo);
    }
References System.Xml.Xsl.Runtime.XmlExtensionFunction._flags, System.Xml.Xsl.Runtime.XmlExtensionFunction._name, System.Xml.Xsl.Runtime.XmlExtensionFunction._namespaceUri, System.Xml.Xsl.Runtime.XmlExtensionFunction._numArgs, System.Xml.Xsl.Runtime.XmlExtensionFunction._objectType, System.array, System.Xml.Xsl.Runtime.XmlExtensionFunction.Bind(), System.comparisonType, System.Xml.Dictionary, System.Type.GetMethods(), System.Globalization.CultureInfo.InvariantCulture, System.SR.XmlIl_AmbiguousExtensionMethod, System.SR.XmlIl_GenericExtensionMethod, System.SR.XmlIl_NoExtensionMethod, and System.SR.XmlIl_NonPublicExtensionMethod.
Referenced by System.Xml.Xsl.Runtime.XmlExtensionFunction.XmlExtensionFunction(), System.Xml.Xsl.Runtime.XmlExtensionFunction.Bind(), and System.Xml.Xsl.Runtime.XmlExtensionFunctionTable.Bind().