Terraria: System.Data.DataViewManager.DataViewManager
DataViewManager() [3/3]
System.Data.DataViewManager.DataViewManager (DataSet dataSet, bool locked) inline package
Definition at line 201 of file DataViewManager.cs.
    {
        GC.SuppressFinalize(this);
        _dataSet = dataSet;
        if (_dataSet != null)
        {
            _dataSet.Tables.CollectionChanged += TableCollectionChanged;
            _dataSet.Relations.CollectionChanged += RelationCollectionChanged;
        }
        _locked = locked;
        _item = new DataViewManagerListItemTypeDescriptor(this);
        _dataViewSettingsCollection = new DataViewSettingCollection(this);
    }
References System.Data.DataViewManager._dataSet, System.Data.DataViewManager._dataViewSettingsCollection, System.Data.DataViewManager._item, System.Data.DataViewManager._locked, System.Xml.Dictionary, System.Data.DataViewManager.RelationCollectionChanged(), System.GC.SuppressFinalize(), and System.Data.DataViewManager.TableCollectionChanged().