Terraria: System.Xml.Xsl.Runtime.XmlExtensionFunction.CanBind
CanBind()
bool System.Xml.Xsl.Runtime.XmlExtensionFunction.CanBind () inline
Definition at line 79 of file XmlExtensionFunction.cs.
    {
        MethodInfo[] methods = _objectType.GetMethods(_flags);
        StringComparison comparisonType = (((_flags & BindingFlags.IgnoreCase) != 0) ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal);
        MethodInfo[] array = methods;
        foreach (MethodInfo methodInfo in array)
        {
            if (methodInfo.Name.Equals(_name, comparisonType) && (_numArgs == -1 || methodInfo.GetParameters().Length == _numArgs) && !methodInfo.IsGenericMethodDefinition)
            {
                return true;
            }
        }
        return false;
    }
References System.Xml.Xsl.Runtime.XmlExtensionFunction._flags, System.Xml.Xsl.Runtime.XmlExtensionFunction._name, System.Xml.Xsl.Runtime.XmlExtensionFunction._numArgs, System.Xml.Xsl.Runtime.XmlExtensionFunction._objectType, System.array, System.comparisonType, System.Xml.Dictionary, and System.Type.GetMethods().
Referenced by System.Xml.Xsl.Runtime.XmlQueryRuntime.EarlyBoundFunctionExists(), and System.Xml.Xsl.Runtime.XmlQueryContext.LateBoundFunctionExists().