Terraria: System.Net.Http.Headers.CacheControlHeaderValue.TrySetCacheControlValues
TrySetCacheControlValues()
static bool System.Net.Http.Headers.CacheControlHeaderValue.TrySetCacheControlValues (CacheControlHeaderValue cc, List< NameValueHeaderValue > nameValueList) inline static private
Definition at line 474 of file CacheControlHeaderValue.cs.
    {
        foreach (NameValueHeaderValue nameValue in nameValueList)
        {
            bool flag = true;
            switch (nameValue.Name.ToLowerInvariant())
            {
            case "no-cache":
                flag = TrySetOptionalTokenList(nameValue, ref cc._noCache, ref cc._noCacheHeaders);
                break;
            case "no-store":
                flag = TrySetTokenOnlyValue(nameValue, ref cc._noStore);
                break;
            case "max-age":
                flag = TrySetTimeSpan(nameValue, ref cc._maxAge);
                break;
            case "max-stale":
                flag = nameValue.Value == null || TrySetTimeSpan(nameValue, ref cc._maxStaleLimit);
                if (flag)
                {
                    cc._maxStale = true;
                }
                break;
            case "min-fresh":
                flag = TrySetTimeSpan(nameValue, ref cc._minFresh);
                break;
            case "no-transform":
                flag = TrySetTokenOnlyValue(nameValue, ref cc._noTransform);
                break;
            case "only-if-cached":
                flag = TrySetTokenOnlyValue(nameValue, ref cc._onlyIfCached);
                break;
            case "public":
                flag = TrySetTokenOnlyValue(nameValue, ref cc._publicField);
                break;
            case "private":
                flag = TrySetOptionalTokenList(nameValue, ref cc._privateField, ref cc._privateHeaders);
                break;
            case "must-revalidate":
                flag = TrySetTokenOnlyValue(nameValue, ref cc._mustRevalidate);
                break;
            case "proxy-revalidate":
                flag = TrySetTokenOnlyValue(nameValue, ref cc._proxyRevalidate);
                break;
            case "s-maxage":
                flag = TrySetTimeSpan(nameValue, ref cc._sharedMaxAge);
                break;
            default:
                cc.Extensions.Add(nameValue);
                break;
            }
            if (!flag)
            {
                return false;
            }
        }
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.Headers.CacheControlHeaderValue.TrySetOptionalTokenList(), System.Net.Http.Headers.CacheControlHeaderValue.TrySetTimeSpan(), and System.Net.Http.Headers.CacheControlHeaderValue.TrySetTokenOnlyValue().
Referenced by System.Net.Http.Headers.CacheControlHeaderValue.GetCacheControlLength().