Terraria: System.Net.Http.Headers.CacheControlHeaderValue.ToString
ToString()
override string System.Net.Http.Headers.CacheControlHeaderValue.ToString () inline
Definition at line 244 of file CacheControlHeaderValue.cs.
    {
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        AppendValueIfRequired(stringBuilder, _noStore, "no-store");
        AppendValueIfRequired(stringBuilder, _noTransform, "no-transform");
        AppendValueIfRequired(stringBuilder, _onlyIfCached, "only-if-cached");
        AppendValueIfRequired(stringBuilder, _publicField, "public");
        AppendValueIfRequired(stringBuilder, _mustRevalidate, "must-revalidate");
        AppendValueIfRequired(stringBuilder, _proxyRevalidate, "proxy-revalidate");
        if (_noCache)
        {
            AppendValueWithSeparatorIfRequired(stringBuilder, "no-cache");
            if (_noCacheHeaders != null && _noCacheHeaders.Count > 0)
            {
                stringBuilder.Append("=\"");
                AppendValues(stringBuilder, _noCacheHeaders);
                stringBuilder.Append('"');
            }
        }
        if (_maxAge.HasValue)
        {
            AppendValueWithSeparatorIfRequired(stringBuilder, "max-age");
            stringBuilder.Append('=');
            int num = (int)_maxAge.GetValueOrDefault().TotalSeconds;
            if (num >= 0)
            {
                stringBuilder.Append(num);
            }
            else
            {
                StringBuilder stringBuilder2 = stringBuilder;
                StringBuilder stringBuilder3 = stringBuilder2;
                IFormatProvider invariantInfo = NumberFormatInfo.InvariantInfo;
                IFormatProvider provider = invariantInfo;
                StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2, invariantInfo);
                handler.AppendFormatted(num);
                stringBuilder3.Append(provider, ref handler);
            }
        }
        if (_sharedMaxAge.HasValue)
        {
            AppendValueWithSeparatorIfRequired(stringBuilder, "s-maxage");
            stringBuilder.Append('=');
            int num2 = (int)_sharedMaxAge.GetValueOrDefault().TotalSeconds;
            if (num2 >= 0)
            {
                stringBuilder.Append(num2);
            }
            else
            {
                StringBuilder stringBuilder2 = stringBuilder;
                StringBuilder stringBuilder4 = stringBuilder2;
                IFormatProvider invariantInfo = NumberFormatInfo.InvariantInfo;
                IFormatProvider provider2 = invariantInfo;
                StringBuilder.AppendInterpolatedStringHandler handler2 = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2, invariantInfo);
                handler2.AppendFormatted(num2);
                stringBuilder4.Append(provider2, ref handler2);
            }
        }
        if (_maxStale)
        {
            AppendValueWithSeparatorIfRequired(stringBuilder, "max-stale");
            if (_maxStaleLimit.HasValue)
            {
                stringBuilder.Append('=');
                int num3 = (int)_maxStaleLimit.GetValueOrDefault().TotalSeconds;
                if (num3 >= 0)
                {
                    stringBuilder.Append(num3);
                }
                else
                {
                    StringBuilder stringBuilder2 = stringBuilder;
                    StringBuilder stringBuilder5 = stringBuilder2;
                    IFormatProvider invariantInfo = NumberFormatInfo.InvariantInfo;
                    IFormatProvider provider3 = invariantInfo;
                    StringBuilder.AppendInterpolatedStringHandler handler3 = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2, invariantInfo);
                    handler3.AppendFormatted(num3);
                    stringBuilder5.Append(provider3, ref handler3);
                }
            }
        }
        if (_minFresh.HasValue)
        {
            AppendValueWithSeparatorIfRequired(stringBuilder, "min-fresh");
            stringBuilder.Append('=');
            int num4 = (int)_minFresh.GetValueOrDefault().TotalSeconds;
            if (num4 >= 0)
            {
                stringBuilder.Append(num4);
            }
            else
            {
                StringBuilder stringBuilder2 = stringBuilder;
                StringBuilder stringBuilder6 = stringBuilder2;
                IFormatProvider invariantInfo = NumberFormatInfo.InvariantInfo;
                IFormatProvider provider4 = invariantInfo;
                StringBuilder.AppendInterpolatedStringHandler handler4 = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2, invariantInfo);
                handler4.AppendFormatted(num4);
                stringBuilder6.Append(provider4, ref handler4);
            }
        }
        if (_privateField)
        {
            AppendValueWithSeparatorIfRequired(stringBuilder, "private");
            if (_privateHeaders != null && _privateHeaders.Count > 0)
            {
                stringBuilder.Append("=\"");
                AppendValues(stringBuilder, _privateHeaders);
                stringBuilder.Append('"');
            }
        }
        NameValueHeaderValue.ToString(_extensions, ',', leadingSeparator: false, stringBuilder);
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Net.Http.Headers.CacheControlHeaderValue._extensions, System.Net.Http.Headers.CacheControlHeaderValue._maxAge, System.Net.Http.Headers.CacheControlHeaderValue._maxStale, System.Net.Http.Headers.CacheControlHeaderValue._maxStaleLimit, System.Net.Http.Headers.CacheControlHeaderValue._minFresh, System.Net.Http.Headers.CacheControlHeaderValue._mustRevalidate, System.Net.Http.Headers.CacheControlHeaderValue._noCache, System.Net.Http.Headers.CacheControlHeaderValue._noCacheHeaders, System.Net.Http.Headers.CacheControlHeaderValue._noStore, System.Net.Http.Headers.CacheControlHeaderValue._noTransform, System.Net.Http.Headers.CacheControlHeaderValue._onlyIfCached, System.Net.Http.Headers.CacheControlHeaderValue._privateField, System.Net.Http.Headers.CacheControlHeaderValue._privateHeaders, System.Net.Http.Headers.CacheControlHeaderValue._proxyRevalidate, System.Net.Http.Headers.CacheControlHeaderValue._publicField, System.Net.Http.Headers.CacheControlHeaderValue._sharedMaxAge, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Net.Http.Headers.CacheControlHeaderValue.AppendValueIfRequired(), System.Net.Http.Headers.CacheControlHeaderValue.AppendValues(), System.Net.Http.Headers.CacheControlHeaderValue.AppendValueWithSeparatorIfRequired(), System.Net.Http.Headers.ObjectCollection< T >.Count, System.Text.StringBuilderCache.GetStringAndRelease(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Net.Http.Headers.NameValueHeaderValue.ToString(), and System.TimeSpan.TotalSeconds.