Terraria: System.Net.Http.Headers.CacheControlHeaderValue.GetCacheControlLength
GetCacheControlLength()
static int System.Net.Http.Headers.CacheControlHeaderValue.GetCacheControlLength (string input, int startIndex, CacheControlHeaderValue storeValue, out CacheControlHeaderValue parsedValue) inline static package
Definition at line 441 of file CacheControlHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int index = startIndex;
        List<NameValueHeaderValue> list = new List<NameValueHeaderValue>();
        while (index < input.Length)
        {
            if (!s_nameValueListParser.TryParseValue(input, null, ref index, out var parsedValue2))
            {
                return 0;
            }
            list.Add((NameValueHeaderValue)parsedValue2);
        }
        CacheControlHeaderValue cacheControlHeaderValue = storeValue;
        if (cacheControlHeaderValue == null)
        {
            cacheControlHeaderValue = new CacheControlHeaderValue();
        }
        if (!TrySetCacheControlValues(cacheControlHeaderValue, list))
        {
            return 0;
        }
        if (storeValue == null)
        {
            parsedValue = cacheControlHeaderValue;
        }
        return input.Length - startIndex;
    }
References System.Net.Http.Headers.CacheControlHeaderValue.CacheControlHeaderValue(), System.index, System.input, System.list, System.Net.Http.Headers.CacheControlHeaderValue.s_nameValueListParser, System.startIndex, and System.Net.Http.Headers.CacheControlHeaderValue.TrySetCacheControlValues().
Referenced by System.Net.Http.Headers.CacheControlHeaderParser.GetParsedValueLength().