Terraria: System.Threading.Tasks.RendezvousAwaitable.NotifyAwaiter
NotifyAwaiter()
void System.Threading.Tasks.RendezvousAwaitable< TResult >.NotifyAwaiter () inline private
Definition at line 55 of file RendezvousAwaitable.cs.
    {
        Action action = _continuation ?? Interlocked.CompareExchange(ref _continuation, s_completionSentinel, null);
        if (action != null)
        {
            if (RunContinuationsAsynchronously)
            {
                Task.Run(action);
            }
            else
            {
                action();
            }
        }
    }
References System.Threading.Tasks.RendezvousAwaitable< TResult >._continuation, System.action, System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Task< TResult >.Run(), System.Threading.Tasks.RendezvousAwaitable< TResult >.RunContinuationsAsynchronously, and System.Threading.Tasks.RendezvousAwaitable< TResult >.s_completionSentinel.
Referenced by System.Threading.Tasks.RendezvousAwaitable< TResult >.SetResult().