Terraria: Actions.SetTileKeepWall.Apply
Apply()
override bool Actions.SetTileKeepWall.Apply (Point origin, int x, int y, params object[] args) inline virtual
Implements GenAction.
         {
             ushort wall = GenBase._tiles[x, y].wall;
             int wallFrameX = GenBase._tiles[x, y].wallFrameX();
             int wallFrameY = GenBase._tiles[x, y].wallFrameY();
             GenBase._tiles[x, y].Clear(~(TileDataType.Wiring | TileDataType.Actuator));
             GenBase._tiles[x, y].type = _type;
             GenBase._tiles[x, y].active(active: true);
             if (wall > 0)
             {
                 GenBase._tiles[x, y].wall = wall;
                 GenBase._tiles[x, y].wallFrameX(wallFrameX);
                 GenBase._tiles[x, y].wallFrameY(wallFrameY);
             }
             if (_doFraming)
             {
                 WorldUtils.TileFrame(x, y, _doNeighborFraming);
             }
             return UnitApply(origin, x, y, args);
         }
References Actions.SetTileKeepWall._doFraming, Actions.SetTileKeepWall._doNeighborFraming, GenBase._tiles, Actions.SetTileKeepWall._type, Tile.active(), Tile.Clear(), WorldUtils.TileFrame(), Tile.type, GenAction.UnitApply(), Tile.wall, Tile.wallFrameX(), and Tile.wallFrameY().