Terraria: MS.Internal.Xml.XPath.UnionExpr.Advance
Advance()
override XPathNavigator MS.Internal.Xml.XPath.UnionExpr.Advance () inline
Definition at line 104 of file UnionExpr.cs.
    {
        XmlNodeOrder xmlNodeOrder = XmlNodeOrder.Before;
        XPathNavigator xPathNavigator = ((!_advance1) ? _nextNode : qy1.Advance());
        XPathNavigator xPathNavigator2 = ((!_advance2) ? _nextNode : qy2.Advance());
        if (xPathNavigator == null || xPathNavigator2 == null)
        {
            if (xPathNavigator2 == null)
            {
                _advance1 = true;
                _advance2 = false;
                _currentNode = xPathNavigator;
                _nextNode = null;
                return xPathNavigator;
            }
            _advance1 = false;
            _advance2 = true;
            _currentNode = xPathNavigator2;
            _nextNode = null;
            return xPathNavigator2;
        }
        return Query.CompareNodes(xPathNavigator, xPathNavigator2) switch
        {
            XmlNodeOrder.Before => ProcessBeforePosition(xPathNavigator, xPathNavigator2),
            XmlNodeOrder.After => ProcessAfterPosition(xPathNavigator, xPathNavigator2),
            _ => ProcessSamePosition(xPathNavigator),
        };
    }
References MS.Internal.Xml.XPath.UnionExpr._advance1, MS.Internal.Xml.XPath.UnionExpr._advance2, MS.Internal.Xml.XPath.UnionExpr._currentNode, MS.Internal.Xml.XPath.UnionExpr._nextNode, MS.Internal.Xml.XPath.Query.Advance(), MS.Internal.Xml.XPath.Query.CompareNodes(), System.Xml.Dictionary, MS.Internal.Xml.XPath.UnionExpr.ProcessAfterPosition(), MS.Internal.Xml.XPath.UnionExpr.ProcessBeforePosition(), MS.Internal.Xml.XPath.UnionExpr.ProcessSamePosition(), MS.Internal.Xml.XPath.UnionExpr.qy1, and MS.Internal.Xml.XPath.UnionExpr.qy2.