Terraria: System.Buffers.Text.Base64.DecodeFromUtf8InPlace
DecodeFromUtf8InPlace()
static unsafe OperationStatus System.Buffers.Text.Base64.DecodeFromUtf8InPlace (Span< byte > buffer, out int bytesWritten) inline static
Definition at line 223 of file Base64.cs.
    {
        if (buffer.IsEmpty)
        {
            bytesWritten = 0;
            return OperationStatus.Done;
        }
        fixed (byte* ptr = &MemoryMarshal.GetReference(buffer))
        {
            int length = buffer.Length;
            uint num = 0u;
            uint num2 = 0u;
            if (length == (length >> 2) * 4)
            {
                if (length == 0)
                {
                    goto IL_0189;
                }
                ref sbyte reference = ref MemoryMarshal.GetReference(DecodingMap);
                while (num < length - 4)
                {
                    int num3 = Decode(ptr + num, ref reference);
                    if (num3 >= 0)
                    {
                        WriteThreeLowOrderBytes(ptr + num2, num3);
                        num2 += 3;
                        num += 4;
                        continue;
                    }
                    goto IL_018f;
                }
                uint num4 = ptr[length - 4];
                uint num5 = ptr[length - 3];
                uint num6 = ptr[length - 2];
                uint num7 = ptr[length - 1];
                int num8 = Internal.Runtime.CompilerServices.Unsafe.Add(ref reference, (IntPtr)num4);
                int num9 = Internal.Runtime.CompilerServices.Unsafe.Add(ref reference, (IntPtr)num5);
                num8 <<= 18;
                num9 <<= 12;
                num8 |= num9;
                if (num7 != 61)
                {
                    int num10 = Internal.Runtime.CompilerServices.Unsafe.Add(ref reference, (IntPtr)num6);
                    int num11 = Internal.Runtime.CompilerServices.Unsafe.Add(ref reference, (IntPtr)num7);
                    num10 <<= 6;
                    num8 |= num11;
                    num8 |= num10;
                    if (num8 >= 0)
                    {
                        WriteThreeLowOrderBytes(ptr + num2, num8);
                        num2 += 3;
                        goto IL_0189;
                    }
                }
                else if (num6 != 61)
                {
                    int num12 = Internal.Runtime.CompilerServices.Unsafe.Add(ref reference, (IntPtr)num6);
                    num12 <<= 6;
                    num8 |= num12;
                    if (num8 >= 0)
                    {
                        ptr[num2] = (byte)(num8 >> 16);
                        ptr[num2 + 1] = (byte)(num8 >> 8);
                        num2 += 2;
                        goto IL_0189;
                    }
                }
                else if (num8 >= 0)
                {
                    ptr[num2] = (byte)(num8 >> 16);
                    num2++;
                    goto IL_0189;
                }
            }
            goto IL_018f;
            IL_018f:
            bytesWritten = (int)num2;
            return OperationStatus.InvalidData;
            IL_0189:
            bytesWritten = (int)num2;
            return OperationStatus.Done;
        }
    }
References System.buffer, System.Buffers.Text.Base64.Decode(), System.Buffers.Text.Base64.DecodingMap, System.length, and System.Buffers.Text.Base64.WriteThreeLowOrderBytes().
Referenced by System.Text.Json.JsonReaderHelper.TryDecodeBase64InPlace().