Terraria: System.Buffers.Text.Base64.Ssse3Decode
Ssse3Decode()
static unsafe void System.Buffers.Text.Base64.Ssse3Decode (ref byte * srcBytes, ref byte * destBytes, byte * srcEnd, int sourceLength, int destLength, byte * srcStart, byte * destStart) inline static private
Definition at line 348 of file Base64.cs.
    {
        Vector128<sbyte> value = Vector128.Create(16, 16, 1, 2, 4, 8, 4, 8, 16, 16, 16, 16, 16, 16, 16, 16);
        Vector128<sbyte> value2 = Vector128.Create(21, 17, 17, 17, 17, 17, 17, 17, 17, 17, 19, 26, 27, 27, 27, 26);
        Vector128<sbyte> value3 = Vector128.Create(0, 16, 19, 4, -65, -65, -71, -71, 0, 0, 0, 0, 0, 0, 0, 0);
        Vector128<sbyte> mask = Vector128.Create(2, 1, 0, 6, 5, 4, 10, 9, 8, 14, 13, 12, -1, -1, -1, -1);
        Vector128<sbyte> right = Vector128.Create((sbyte)47);
        Vector128<sbyte> right2 = Vector128.Create(20971840).AsSByte();
        Vector128<short> right3 = Vector128.Create(69632).AsInt16();
        Vector128<sbyte> zero = Vector128<sbyte>.Zero;
        byte* ptr = srcBytes;
        byte* ptr2 = destBytes;
        do
        {
            Vector128<sbyte> vector = Sse2.LoadVector128(ptr).AsSByte();
            Vector128<sbyte> vector2 = Sse2.And(Sse2.ShiftRightLogical(vector.AsInt32(), 4).AsSByte(), right);
            Vector128<sbyte> mask2 = Sse2.And(vector, right);
            Vector128<sbyte> right4 = Ssse3.Shuffle(value, vector2);
            Vector128<sbyte> left = Ssse3.Shuffle(value2, mask2);
            if (Sse2.MoveMask(Sse2.CompareGreaterThan(Sse2.And(left, right4), zero)) != 0)
            {
                break;
            }
            Vector128<sbyte> left2 = Sse2.CompareEqual(vector, right);
            Vector128<sbyte> right5 = Ssse3.Shuffle(value3, Sse2.Add(left2, vector2));
            vector = Sse2.Add(vector, right5);
            Vector128<short> left3 = Ssse3.MultiplyAddAdjacent(vector.AsByte(), right2);
            Vector128<int> vector3 = Sse2.MultiplyAddAdjacent(left3, right3);
            vector = Ssse3.Shuffle(vector3.AsSByte(), mask);
            Sse2.Store(ptr2, vector.AsByte());
            ptr += 16;
            ptr2 += 12;
        }
        while (ptr <= srcEnd);
        srcBytes = ptr;
        destBytes = ptr2;
    }
References System.Runtime.Intrinsics.X86.Sse2.Add(), System.Runtime.Intrinsics.X86.Sse2.And(), System.Runtime.Intrinsics.X86.Sse2.CompareEqual(), System.Runtime.Intrinsics.X86.Sse2.CompareGreaterThan(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Ssse3.MultiplyAddAdjacent(), System.Runtime.Intrinsics.X86.Sse2.MultiplyAddAdjacent(), System.Runtime.Intrinsics.X86.Sse2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Ssse3.Shuffle(), System.Runtime.Intrinsics.X86.Sse2.Store(), System.value, and System.Runtime.Intrinsics.Vector128< T >.Zero.
Referenced by System.Buffers.Text.Base64.DecodeFromUtf8().