Terraria: System.Buffers.Text.Base64.Avx2Encode
Avx2Encode()
static unsafe void System.Buffers.Text.Base64.Avx2Encode (ref byte * srcBytes, ref byte * destBytes, byte * srcEnd, int sourceLength, int destLength, byte * srcStart, byte * destStart) inline static private
Definition at line 551 of file Base64.cs.
    {
        Vector256<sbyte> mask = Vector256.Create(5, 4, 6, 5, 8, 7, 9, 8, 11, 10, 12, 11, 14, 13, 15, 14, 1, 0, 2, 1, 4, 3, 5, 4, 7, 6, 8, 7, 10, 9, 11, 10);
        Vector256<sbyte> value = Vector256.Create(65, 71, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -19, -16, 0, 0, 65, 71, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -19, -16, 0, 0);
        Vector256<sbyte> right = Vector256.Create(264305664).AsSByte();
        Vector256<sbyte> right2 = Vector256.Create(4129776).AsSByte();
        Vector256<ushort> right3 = Vector256.Create(67108928).AsUInt16();
        Vector256<short> right4 = Vector256.Create(16777232).AsInt16();
        Vector256<byte> right5 = Vector256.Create((byte)51);
        Vector256<sbyte> right6 = Vector256.Create((sbyte)25);
        byte* ptr = srcBytes;
        byte* ptr2 = destBytes;
        Vector256<sbyte> vector = Avx.LoadVector256(ptr).AsSByte();
        vector = Avx2.PermuteVar8x32(vector.AsInt32(), Vector256.Create(0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 6, 0, 0, 0).AsInt32()).AsSByte();
        ptr -= 4;
        while (true)
        {
            vector = Avx2.Shuffle(vector, mask);
            Vector256<sbyte> vector2 = Avx2.And(vector, right);
            Vector256<sbyte> vector3 = Avx2.And(vector, right2);
            Vector256<ushort> vector4 = Avx2.MultiplyHigh(vector2.AsUInt16(), right3);
            Vector256<short> vector5 = Avx2.MultiplyLow(vector3.AsInt16(), right4);
            vector = Avx2.Or(vector4.AsSByte(), vector5.AsSByte());
            Vector256<byte> vector6 = Avx2.SubtractSaturate(vector.AsByte(), right5);
            Vector256<sbyte> right7 = Avx2.CompareGreaterThan(vector, right6);
            Vector256<sbyte> mask2 = Avx2.Subtract(vector6.AsSByte(), right7);
            vector = Avx2.Add(vector, Avx2.Shuffle(value, mask2));
            Avx.Store(ptr2, vector.AsByte());
            ptr += 24;
            ptr2 += 32;
            if (ptr > srcEnd)
            {
                break;
            }
            vector = Avx.LoadVector256(ptr).AsSByte();
        }
        srcBytes = ptr + 4;
        destBytes = ptr2;
    }
References System.Runtime.Intrinsics.X86.Avx2.Add(), System.Runtime.Intrinsics.X86.Avx2.And(), System.Runtime.Intrinsics.X86.Avx2.CompareGreaterThan(), System.Runtime.Intrinsics.Vector256< T >.Create(), System.Runtime.Intrinsics.X86.Avx.LoadVector256(), System.Runtime.Intrinsics.X86.Avx2.MultiplyHigh(), System.Runtime.Intrinsics.X86.Avx2.MultiplyLow(), System.Runtime.Intrinsics.X86.Avx2.Or(), System.Runtime.Intrinsics.X86.Avx2.PermuteVar8x32(), System.Runtime.Intrinsics.X86.Avx2.Shuffle(), System.Runtime.Intrinsics.X86.Avx.Store(), System.Runtime.Intrinsics.X86.Avx2.Subtract(), System.Runtime.Intrinsics.X86.Avx2.SubtractSaturate(), and System.value.
Referenced by System.Buffers.Text.Base64.EncodeToUtf8().