Terraria: System.Buffers.Text.Base64.Ssse3Encode
Ssse3Encode()
static unsafe void System.Buffers.Text.Base64.Ssse3Encode (ref byte * srcBytes, ref byte * destBytes, byte * srcEnd, int sourceLength, int destLength, byte * srcStart, byte * destStart) inline static private
Definition at line 592 of file Base64.cs.
    {
        Vector128<sbyte> mask = Vector128.Create(1, 0, 2, 1, 4, 3, 5, 4, 7, 6, 8, 7, 10, 9, 11, 10);
        Vector128<sbyte> value = Vector128.Create(65, 71, -4, -4, -4, -4, -4, -4, -4, -4, -4, -4, -19, -16, 0, 0);
        Vector128<sbyte> right = Vector128.Create(264305664).AsSByte();
        Vector128<sbyte> right2 = Vector128.Create(4129776).AsSByte();
        Vector128<ushort> right3 = Vector128.Create(67108928).AsUInt16();
        Vector128<short> right4 = Vector128.Create(16777232).AsInt16();
        Vector128<byte> right5 = Vector128.Create((byte)51);
        Vector128<sbyte> right6 = Vector128.Create((sbyte)25);
        byte* ptr = srcBytes;
        byte* ptr2 = destBytes;
        do
        {
            Vector128<sbyte> value2 = Sse2.LoadVector128(ptr).AsSByte();
            value2 = Ssse3.Shuffle(value2, mask);
            Vector128<sbyte> vector = Sse2.And(value2, right);
            Vector128<sbyte> vector2 = Sse2.And(value2, right2);
            Vector128<ushort> vector3 = Sse2.MultiplyHigh(vector.AsUInt16(), right3);
            Vector128<short> vector4 = Sse2.MultiplyLow(vector2.AsInt16(), right4);
            value2 = Sse2.Or(vector3.AsSByte(), vector4.AsSByte());
            Vector128<byte> vector5 = Sse2.SubtractSaturate(value2.AsByte(), right5);
            Vector128<sbyte> right7 = Sse2.CompareGreaterThan(value2, right6);
            Vector128<sbyte> mask2 = Sse2.Subtract(vector5.AsSByte(), right7);
            value2 = Sse2.Add(value2, Ssse3.Shuffle(value, mask2));
            Sse2.Store(ptr2, value2.AsByte());
            ptr += 12;
            ptr2 += 16;
        }
        while (ptr <= srcEnd);
        srcBytes = ptr;
        destBytes = ptr2;
    }
References System.Runtime.Intrinsics.X86.Sse2.Add(), System.Runtime.Intrinsics.X86.Sse2.And(), System.Runtime.Intrinsics.X86.Sse2.CompareGreaterThan(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.X86.Sse2.LoadVector128(), System.Runtime.Intrinsics.X86.Sse2.MultiplyHigh(), System.Runtime.Intrinsics.X86.Sse2.MultiplyLow(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Ssse3.Shuffle(), System.Runtime.Intrinsics.X86.Sse2.Store(), System.Runtime.Intrinsics.X86.Sse2.Subtract(), System.Runtime.Intrinsics.X86.Sse2.SubtractSaturate(), and System.value.
Referenced by System.Buffers.Text.Base64.EncodeToUtf8().