Terraria: System.Buffers.Text.Base64.GetMaxEncodedToUtf8Length
GetMaxEncodedToUtf8Length()
static int System.Buffers.Text.Base64.GetMaxEncodedToUtf8Length (int length) inline static
Definition at line 502 of file Base64.cs.
    {
        if ((uint)length > 1610612733u)
        {
            System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument.length);
        }
        return (length + 2) / 3 * 4;
    }
References System.length, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Buffers.Text.Base64.EncodeToUtf8(), System.Buffers.Text.Base64.EncodeToUtf8InPlace(), System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Minimized(), System.Text.Json.Utf8JsonWriter.WriteBase64Minimized(), and System.Text.Json.Utf8JsonWriter.WriteBase64Minimized().