Terraria: System.Buffers.Text.Base64.Avx2Decode
Avx2Decode()
static unsafe void System.Buffers.Text.Base64.Avx2Decode (ref byte * srcBytes, ref byte * destBytes, byte * srcEnd, int sourceLength, int destLength, byte * srcStart, byte * destStart) inline static private
Definition at line 308 of file Base64.cs.
    {
        Vector256<sbyte> value = Vector256.Create(16, 16, 1, 2, 4, 8, 4, 8, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 1, 2, 4, 8, 4, 8, 16, 16, 16, 16, 16, 16, 16, 16);
        Vector256<sbyte> value2 = Vector256.Create(21, 17, 17, 17, 17, 17, 17, 17, 17, 17, 19, 26, 27, 27, 27, 26, 21, 17, 17, 17, 17, 17, 17, 17, 17, 17, 19, 26, 27, 27, 27, 26);
        Vector256<sbyte> value3 = Vector256.Create(0, 16, 19, 4, -65, -65, -71, -71, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 19, 4, -65, -65, -71, -71, 0, 0, 0, 0, 0, 0, 0, 0);
        Vector256<sbyte> mask = Vector256.Create(2, 1, 0, 6, 5, 4, 10, 9, 8, 14, 13, 12, -1, -1, -1, -1, 2, 1, 0, 6, 5, 4, 10, 9, 8, 14, 13, 12, -1, -1, -1, -1);
        Vector256<int> control = Vector256.Create(0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 6, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1).AsInt32();
        Vector256<sbyte> right = Vector256.Create((sbyte)47);
        Vector256<sbyte> right2 = Vector256.Create(20971840).AsSByte();
        Vector256<short> right3 = Vector256.Create(69632).AsInt16();
        byte* ptr = srcBytes;
        byte* ptr2 = destBytes;
        do
        {
            Vector256<sbyte> vector = Avx.LoadVector256(ptr).AsSByte();
            Vector256<sbyte> vector2 = Avx2.And(Avx2.ShiftRightLogical(vector.AsInt32(), 4).AsSByte(), right);
            Vector256<sbyte> mask2 = Avx2.And(vector, right);
            Vector256<sbyte> right4 = Avx2.Shuffle(value, vector2);
            Vector256<sbyte> left = Avx2.Shuffle(value2, mask2);
            if (!Avx.TestZ(left, right4))
            {
                break;
            }
            Vector256<sbyte> left2 = Avx2.CompareEqual(vector, right);
            Vector256<sbyte> right5 = Avx2.Shuffle(value3, Avx2.Add(left2, vector2));
            vector = Avx2.Add(vector, right5);
            Vector256<short> left3 = Avx2.MultiplyAddAdjacent(vector.AsByte(), right2);
            Vector256<int> vector3 = Avx2.MultiplyAddAdjacent(left3, right3);
            vector3 = Avx2.Shuffle(vector3.AsSByte(), mask).AsInt32();
            vector = Avx2.PermuteVar8x32(vector3, control).AsSByte();
            Avx.Store(ptr2, vector.AsByte());
            ptr += 32;
            ptr2 += 24;
        }
        while (ptr <= srcEnd);
        srcBytes = ptr;
        destBytes = ptr2;
    }
References System.Runtime.Intrinsics.X86.Avx2.Add(), System.Runtime.Intrinsics.X86.Avx2.And(), System.Runtime.Intrinsics.X86.Avx2.CompareEqual(), System.Runtime.Intrinsics.Vector256< T >.Create(), System.Runtime.Intrinsics.X86.Avx.LoadVector256(), System.Runtime.Intrinsics.X86.Avx2.MultiplyAddAdjacent(), System.Runtime.Intrinsics.X86.Avx2.PermuteVar8x32(), System.Runtime.Intrinsics.X86.Avx2.ShiftRightLogical(), System.Runtime.Intrinsics.X86.Avx2.Shuffle(), System.Runtime.Intrinsics.X86.Avx.Store(), System.Runtime.Intrinsics.X86.Avx.TestZ(), and System.value.
Referenced by System.Buffers.Text.Base64.DecodeFromUtf8().