Terraria: System.Buffers.Text.Base64.EncodeToUtf8InPlace
EncodeToUtf8InPlace()
static unsafe OperationStatus System.Buffers.Text.Base64.EncodeToUtf8InPlace (Span< byte > buffer, int dataLength, out int bytesWritten) inline static
Definition at line 511 of file Base64.cs.
    {
        if (buffer.IsEmpty)
        {
            bytesWritten = 0;
            return OperationStatus.Done;
        }
        fixed (byte* ptr = &MemoryMarshal.GetReference(buffer))
        {
            int maxEncodedToUtf8Length = GetMaxEncodedToUtf8Length(dataLength);
            if (buffer.Length >= maxEncodedToUtf8Length)
            {
                int num = dataLength - dataLength / 3 * 3;
                uint num2 = (uint)(maxEncodedToUtf8Length - 4);
                uint num3 = (uint)(dataLength - num);
                uint num4 = 0u;
                ref byte reference = ref MemoryMarshal.GetReference(EncodingMap);
                if (num != 0)
                {
                    num4 = ((num != 1) ? EncodeAndPadOne(ptr + num3, ref reference) : EncodeAndPadTwo(ptr + num3, ref reference));
                    Internal.Runtime.CompilerServices.Unsafe.WriteUnaligned(ptr + num2, num4);
                    num2 -= 4;
                }
                num3 -= 3;
                while ((int)num3 >= 0)
                {
                    num4 = Encode(ptr + num3, ref reference);
                    Internal.Runtime.CompilerServices.Unsafe.WriteUnaligned(ptr + num2, num4);
                    num2 -= 4;
                    num3 -= 3;
                }
                bytesWritten = maxEncodedToUtf8Length;
                return OperationStatus.Done;
            }
            bytesWritten = 0;
            return OperationStatus.DestinationTooSmall;
        }
    }
References System.buffer, System.Buffers.Text.Base64.Encode(), System.Buffers.Text.Base64.EncodeAndPadOne(), System.Buffers.Text.Base64.EncodeAndPadTwo(), System.Buffers.Text.Base64.EncodingMap, and System.Buffers.Text.Base64.GetMaxEncodedToUtf8Length().