Terraria: System.Single.TryParse
TryParse() [6/13]
static bool System.Single.TryParse ([NotNullWhen(true)] string? s, out float result) inline static
Definition at line 354 of file Single.cs.
    {
        if (s == null)
        {
            result = 0f;
            return false;
        }
        return TryParse((ReadOnlySpan<char>)s, NumberStyles.Float | NumberStyles.AllowThousands, NumberFormatInfo.CurrentInfo, out result);
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.s, and System.Single.TryParse().
Referenced by System.Single.TryParse(), System.Single.TryParse(), System.Single.TryParse(), System.Single.TryParse(), System.Single.TryParse(), System.Single.TryParse(), System.Single.TryParse(), and System.Single.TryParse().