Terraria: System.Single.Parse
Parse() [5/12]
static float System.Single.Parse (ReadOnlySpan< char > s, NumberStyles style = NumberStyles::Float | NumberStyles::AllowThousands, IFormatProvider? provider = null) inline static
Definition at line 348 of file Single.cs.
    {
        NumberFormatInfo.ValidateParseStyleFloatingPoint(style);
        return Number.ParseSingle(s, style, NumberFormatInfo.GetInstance(provider));
    }
References System.Globalization.NumberFormatInfo.GetInstance(), System.Number.ParseSingle(), System.s, and System.Globalization.NumberFormatInfo.ValidateParseStyleFloatingPoint().