Terraria: Terraria.GameContent.ItemTrader.CreateChlorophyteExtractinator
CreateChlorophyteExtractinator()
static ItemTrader Terraria.GameContent.ItemTrader.CreateChlorophyteExtractinator () inline static
Definition at line 82 of file ItemTrader.cs.
    {
        ItemTrader itemTrader = new ItemTrader();
        itemTrader.AddOption_Interchangable(12, 699);
        itemTrader.AddOption_Interchangable(11, 700);
        itemTrader.AddOption_Interchangable(14, 701);
        itemTrader.AddOption_Interchangable(13, 702);
        itemTrader.AddOption_Interchangable(56, 880);
        itemTrader.AddOption_Interchangable(364, 1104);
        itemTrader.AddOption_Interchangable(365, 1105);
        itemTrader.AddOption_Interchangable(366, 1106);
        itemTrader.AddOption_CyclicLoop(134, 137, 139);
        itemTrader.AddOption_Interchangable(20, 703);
        itemTrader.AddOption_Interchangable(22, 704);
        itemTrader.AddOption_Interchangable(21, 705);
        itemTrader.AddOption_Interchangable(19, 706);
        itemTrader.AddOption_Interchangable(57, 1257);
        itemTrader.AddOption_Interchangable(381, 1184);
        itemTrader.AddOption_Interchangable(382, 1191);
        itemTrader.AddOption_Interchangable(391, 1198);
        itemTrader.AddOption_Interchangable(86, 1329);
        itemTrader.AddOption_FromAny(3, 61, 836, 409);
        itemTrader.AddOption_FromAny(169, 370, 1246, 408);
        itemTrader.AddOption_FromAny(664, 833, 835, 834);
        itemTrader.AddOption_FromAny(3271, 3276, 3277, 3339);
        itemTrader.AddOption_FromAny(3272, 3274, 3275, 3338);
        return itemTrader;
    }
References Terraria.GameContent.ItemTrader.AddOption_CyclicLoop(), Terraria.GameContent.ItemTrader.AddOption_FromAny(), and Terraria.GameContent.ItemTrader.AddOption_Interchangable().