Terraria: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot
Spawn_LeafCrystalShot()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot (ParticleOrchestraSettings settings) inline static private
Definition at line 968 of file ParticleOrchestrator.cs.
    {
        int num = 30;
        PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
        Vector2 movementVector = settings.MovementVector;
        Color value = Main.hslToRgb((float)settings.UniqueInfoPiece / 255f, 1f, 0.5f);
        value = Color.Lerp(value, Color.Gold, (float)(int)value.R / 255f * 0.5f);
        prettySparkleParticle.ColorTint = value;
        prettySparkleParticle.LocalPosition = settings.PositionInWorld;
        prettySparkleParticle.Rotation = movementVector.ToRotation();
        prettySparkleParticle.Scale = new Vector2(4f, 1f) * 1f;
        prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
        prettySparkleParticle.FadeOutNormalizedTime = 1f;
        prettySparkleParticle.TimeToLive = num;
        prettySparkleParticle.FadeOutEnd = num;
        prettySparkleParticle.FadeInEnd = num / 2;
        prettySparkleParticle.FadeOutStart = num / 2;
        prettySparkleParticle.AdditiveAmount = 0.5f;
        prettySparkleParticle.Velocity = settings.MovementVector;
        prettySparkleParticle.LocalPosition -= prettySparkleParticle.Velocity * 4f;
        prettySparkleParticle.DrawVerticalAxis = false;
        Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, System.E, Microsoft.Xna.Framework.Color.Gold, Terraria.Main.hslToRgb(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.GameContent.Drawing.ParticleOrchestraSettings.UniqueInfoPiece, and System.value.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().