Terraria: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PooFly
Spawn_PooFly()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PooFly (ParticleOrchestraSettings settings) inline static private
    {
        int num = _poolFlies.CountParticlesInUse();
        if (num <= 50 || !(Main.rand.NextFloat() >= Utils.Remap(num, 50f, 400f, 0.5f, 0f)))
        {
            LittleFlyingCritterParticle littleFlyingCritterParticle = _poolFlies.RequestParticle();
            littleFlyingCritterParticle.Prepare(settings.PositionInWorld, 300);
            Main.ParticleSystem_World_OverPlayers.Add(littleFlyingCritterParticle);
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFlies, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Graphics.Renderers.ParticlePool< T >.CountParticlesInUse(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.GameContent.Drawing.ParticleOrchestraSettings.PositionInWorld, Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Prepare(), Terraria.Main.rand, Terraria.Utils.Remap(), and Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().