Terraria: Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn
BroadcastParticleSpawn()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn (ParticleOrchestraType type, ParticleOrchestraSettings settings) inline static
    {
        settings.IndexOfPlayerWhoInvokedThis = (byte)Main.myPlayer;
        NetManager.Instance.BroadcastOrLoopback(NetParticlesModule.Serialize(type, settings));
    }
References Terraria.Net.NetManager.BroadcastOrLoopback(), Terraria.Net.NetManager.Instance, Terraria.Main.myPlayer, and Terraria.GameContent.NetModules.NetParticlesModule.Serialize().
Referenced by Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_Shimmer_TeleportToLandingSpot(), Terraria.NPC.RerollVariation(), Terraria.NPC.TransformCopperSlime(), Terraria.NPC.TransformElderSlime(), and Terraria.NPC.ViolentlySpawnNerdySlime().