Terraria: Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle
_poolPrettySparkle
ParticlePool<PrettySparkleParticle> Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle = new ParticlePool<PrettySparkleParticle>(200, GetNewPrettySparkleParticle) static private
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_AshTreeShake(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Excalibur(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalPassive(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LeafCrystalShot(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NightsEdge(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PrincessWeapon(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPCSend(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_SilverBulletSparkle(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StellarTune(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TerraBlade(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueExcalibur(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueNightsEdge().