Terraria: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall
Spawn_BlackLightningSmall()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall (ParticleOrchestraSettings settings) inline static private
Definition at line 1350 of file ParticleOrchestrator.cs.
    {
        float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        float num2 = Main.rand.Next(1, 3);
        float num3 = 0.7f;
        int num4 = 916;
        Main.instance.LoadProjectile(num4);
        Color value = new Color(255, 255, 255, 255);
        Color indigo = Color.Indigo;
        indigo.A = 0;
        for (float num5 = 0f; num5 < 1f; num5 += 1f / num2)
        {
            float f = (float)Math.PI * 2f * num5 + num + Main.rand.NextFloatDirection() * 0.25f;
            float num6 = Main.rand.NextFloat() * 4f + 0.1f;
            Vector2 vector = Main.rand.NextVector2Circular(12f, 12f) * num3;
            Color.Lerp(Color.Lerp(Color.Black, indigo, Main.rand.NextFloat() * 0.5f), value, Main.rand.NextFloat() * 0.6f);
            Color colorTint = new Color(0, 0, 0, 255);
            int num7 = Main.rand.Next(4);
            if (num7 == 1)
            {
                colorTint = Color.Lerp(new Color(106, 90, 205, 127), Color.Black, 0.1f + 0.7f * Main.rand.NextFloat());
            }
            if (num7 == 2)
            {
                colorTint = Color.Lerp(new Color(106, 90, 205, 60), Color.Black, 0.1f + 0.8f * Main.rand.NextFloat());
            }
            RandomizedFrameParticle randomizedFrameParticle = _poolRandomizedFrame.RequestParticle();
            randomizedFrameParticle.SetBasicInfo(TextureAssets.Projectile[num4], null, Vector2.Zero, vector);
            randomizedFrameParticle.SetTypeInfo(Main.projFrames[num4], 2, 24f);
            randomizedFrameParticle.Velocity = f.ToRotationVector2() * num6 * new Vector2(1f, 0.5f) * 0.2f + settings.MovementVector;
            randomizedFrameParticle.ColorTint = colorTint;
            randomizedFrameParticle.LocalPosition = settings.PositionInWorld + vector;
            randomizedFrameParticle.Rotation = randomizedFrameParticle.Velocity.ToRotation();
            randomizedFrameParticle.Scale = Vector2.One * 0.5f;
            randomizedFrameParticle.FadeInNormalizedTime = 0.01f;
            randomizedFrameParticle.FadeOutNormalizedTime = 0.5f;
            randomizedFrameParticle.ScaleVelocity = new Vector2(0.025f);
            Main.ParticleSystem_World_OverPlayers.Add(randomizedFrameParticle);
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolRandomizedFrame, Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Color.Indigo, Terraria.Main.instance, Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.MovementVector, Terraria.Main.ParticleSystem_World_OverPlayers, System.Math.PI, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.RandomizedFrameParticle.SetTypeInfo(), System.value, Terraria.Graphics.Renderers.ABasicParticle.Velocity, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().