Terraria: Terraria.GameContent.Events.LanternNight.UpdateTime
UpdateTime()
static void Terraria.GameContent.Events.LanternNight.UpdateTime () inline static
Definition at line 128 of file LanternNight.cs.
    {
        if (GenuineLanterns && !LanternsCanPersist())
        {
            GenuineLanterns = false;
        }
        if (_wasLanternNight != LanternsUp)
        {
            if (Main.netMode != 2)
            {
                if (LanternsUp)
                {
                    SkyManager.Instance.Activate("Lantern", default(Vector2));
                }
                else
                {
                    SkyManager.Instance.Deactivate("Lantern");
                }
            }
            else
            {
                NetMessage.SendData(7);
            }
        }
        _wasLanternNight = LanternsUp;
    }
References Terraria.GameContent.Events.LanternNight._wasLanternNight, Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.GameContent.Events.LanternNight.GenuineLanterns, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.GameContent.Events.LanternNight.LanternsCanPersist(), Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.Main.UpdateTime().