Terraria: System.IO.Compression.ZLibStream.ThrowIfClosed
ThrowIfClosed()
void System.IO.Compression.ZLibStream.ThrowIfClosed () inline private
Definition at line 202 of file ZLibStream.cs.
    {
        if (_deflateStream == null)
        {
            ThrowClosedException();
        }
    }
References System.IO.Compression.ZLibStream._deflateStream, and System.IO.Compression.ZLibStream.ThrowClosedException().
Referenced by System.IO.Compression.ZLibStream.BeginRead(), System.IO.Compression.ZLibStream.BeginWrite(), System.IO.Compression.ZLibStream.CopyTo(), System.IO.Compression.ZLibStream.CopyToAsync(), System.IO.Compression.ZLibStream.Flush(), System.IO.Compression.ZLibStream.FlushAsync(), System.IO.Compression.ZLibStream.Read(), System.IO.Compression.ZLibStream.Read(), System.IO.Compression.ZLibStream.ReadAsync(), System.IO.Compression.ZLibStream.ReadAsync(), System.IO.Compression.ZLibStream.ReadByte(), System.IO.Compression.ZLibStream.Write(), System.IO.Compression.ZLibStream.Write(), System.IO.Compression.ZLibStream.WriteAsync(), System.IO.Compression.ZLibStream.WriteAsync(), and System.IO.Compression.ZLibStream.WriteByte().