Terraria: System.Linq.Parallel.FixedMaxHeap.HeapifyRoot
HeapifyRoot()
void System.Linq.Parallel.FixedMaxHeap< TElement >.HeapifyRoot () inline private
Definition at line 81 of file FixedMaxHeap.cs.
    {
        int num = 0;
        int count = _count;
        while (num < count)
        {
            int num2 = (num + 1) * 2 - 1;
            int num3 = num2 + 1;
            if (num2 < count && _comparer.Compare(_elements[num], _elements[num2]) < 0)
            {
                if (num3 < count && _comparer.Compare(_elements[num2], _elements[num3]) < 0)
                {
                    Swap(num, num3);
                    num = num3;
                }
                else
                {
                    Swap(num, num2);
                    num = num2;
                }
            }
            else
            {
                if (num3 >= count || _comparer.Compare(_elements[num], _elements[num3]) >= 0)
                {
                    break;
                }
                Swap(num, num3);
                num = num3;
            }
        }
    }
References System.Linq.Parallel.FixedMaxHeap< TElement >._comparer, System.Linq.Parallel.FixedMaxHeap< TElement >._count, System.Linq.Parallel.FixedMaxHeap< TElement >._elements, System.Collections.Generic.IComparer< in T >.Compare(), System.Linq.count, and System.Linq.Parallel.FixedMaxHeap< TElement >.Swap().
Referenced by System.Linq.Parallel.FixedMaxHeap< TElement >.Insert(), System.Linq.Parallel.FixedMaxHeap< TElement >.RemoveMax(), and System.Linq.Parallel.FixedMaxHeap< TElement >.ReplaceMax().