Terraria: CustomCurrencySingleCoin.DrawSavingsMoney
DrawSavingsMoney()
override void CustomCurrencySingleCoin.DrawSavingsMoney (SpriteBatch sb, string text, float shopx, float shopy, long totalCoins, bool horizontal = false) inline virtual
Reimplemented from CustomCurrencySystem.
     {
         int num = _valuePerUnit.Keys.ElementAt(0);
         Main.instance.LoadItem(num);
         Texture2D value = TextureAssets.Item[num].Value;
         if (horizontal)
         {
             _ = 99;
             Vector2 position = new Vector2(shopx + ChatManager.GetStringSize(FontAssets.MouseText.Value, text, Vector2.One).X + 45f, shopy + 50f);
             sb.Draw(value, position, null, Color.White, 0f, value.Size() / 2f, CurrencyDrawScale, SpriteEffects.None, 0f);
             Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, totalCoins.ToString(), position.X - 11f, position.Y, Color.White, Color.Black, new Vector2(0.3f), 0.75f);
         }
         else
         {
             int num2 = ((totalCoins > 99) ? (-6) : 0);
             sb.Draw(value, new Vector2(shopx + 11f, shopy + 75f), null, Color.White, 0f, value.Size() / 2f, CurrencyDrawScale, SpriteEffects.None, 0f);
             Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, totalCoins.ToString(), shopx + (float)num2, shopy + 75f, Color.White, Color.Black, new Vector2(0.3f), 0.75f);
         }
     }
References CustomCurrencySystem._valuePerUnit, Color, CurrencyDrawScale, Utils.DrawBorderStringFourWay(), ChatManager.GetStringSize(), Main.instance, TextureAssets.Item, FontAssets.ItemStack, Main.LoadItem(), FontAssets.MouseText, and Asset< T >.Value.