Terraria: TrackGenerator.PlacePath
PlacePath()
void TrackGenerator.PlacePath () inline private
     {
         bool[] array = new bool[_length];
         for (int i = 0; i < _length; i++)
         {
             if (WorldGen.genRand.Next(7) == 0)
             {
                 playerHeight = WorldGen.genRand.Next(5, 9);
             }
             for (int j = 0; j < playerHeight; j++)
             {
                 if (Main.tile[_history[i].X, _history[i].Y - j - 1].wall == 244)
                 {
                     Main.tile[_history[i].X, _history[i].Y - j - 1].wall = 0;
                 }
                 if (Main.tile[_history[i].X, _history[i].Y - j].wall == 244)
                 {
                     Main.tile[_history[i].X, _history[i].Y - j].wall = 0;
                 }
                 if (Main.tile[_history[i].X, _history[i].Y - j + 1].wall == 244)
                 {
                     Main.tile[_history[i].X, _history[i].Y - j + 1].wall = 0;
                 }
                 if (Main.tile[_history[i].X, _history[i].Y - j].type == 135)
                 {
                     array[i] = true;
                 }
                 WorldGen.KillTile(_history[i].X, _history[i].Y - j, fail: false, effectOnly: false, noItem: true);
             }
         }
         for (int k = 0; k < _length; k++)
         {
             if (WorldGen.genRand.Next(7) == 0)
             {
                 playerHeight = WorldGen.genRand.Next(5, 9);
             }
             TrackHistory trackHistory = _history[k];
             Tile.SmoothSlope(trackHistory.X, trackHistory.Y + 1);
             Tile.SmoothSlope(trackHistory.X, trackHistory.Y - playerHeight);
             bool wire = Main.tile[trackHistory.X, trackHistory.Y].wire();
             if (array[k] && k < _length && k > 0 && _history[k - 1].Y == trackHistory.Y && _history[k + 1].Y == trackHistory.Y)
             {
                 Main.tile[trackHistory.X, trackHistory.Y].ClearEverything();
                 WorldGen.PlaceTile(trackHistory.X, trackHistory.Y, 314, mute: false, forced: true, -1, 1);
             }
             else
             {
                 Main.tile[trackHistory.X, trackHistory.Y].ResetToType(314);
             }
             Main.tile[trackHistory.X, trackHistory.Y].wire(wire);
             if (k == 0)
             {
                 continue;
             }
             for (int l = 0; l < 8; l++)
             {
                 WorldUtils.TileFrame(_history[k - 1].X, _history[k - 1].Y - l, frameNeighbors: true);
             }
             if (k == _length - 1)
             {
                 for (int m = 0; m < playerHeight; m++)
                 {
                     WorldUtils.TileFrame(trackHistory.X, trackHistory.Y - m, frameNeighbors: true);
                 }
             }
         }
     }
References _history, _length, Tile.ClearEverything(), WorldGen.genRand, WorldGen.KillTile(), UnifiedRandom.Next(), WorldGen.PlaceTile(), playerHeight, Tile.ResetToType(), Tile.SmoothSlope(), Main.tile, WorldUtils.TileFrame(), Tile.type, Tile.wall, Tile.wire(), X, TrackGenerator.TrackHistory.X, Y, and TrackGenerator.TrackHistory.Y.
Referenced by Place().