Terraria: TrackGenerator.CalculateStateForLocation
CalculateStateForLocation()
static TrackPlacementState TrackGenerator.CalculateStateForLocation (int x, int y) inline static private
     {
         for (int i = 0; i < 6; i++)
         {
             if (IsLocationInvalid(x, y - i))
             {
                 return TrackPlacementState.Invalid;
             }
         }
         for (int j = 0; j < 6; j++)
         {
             if (IsMinecartTrack(x, y + j))
             {
                 return TrackPlacementState.Invalid;
             }
         }
         for (int k = 0; k < 6; k++)
         {
             if (WorldGen.SolidTile(x, y - k))
             {
                 return TrackPlacementState.Obstructed;
             }
         }
         if (WorldGen.IsTileNearby(x, y, 314, 30))
         {
             return TrackPlacementState.Invalid;
         }
         return TrackPlacementState.Available;
     }
References IsLocationInvalid(), IsMinecartTrack(), WorldGen.IsTileNearby(), and WorldGen.SolidTile().
Referenced by CreateTunnel(), FindSuitableOrigin(), and GetHistorySegmentPlacementState().