Terraria: TileReachCheckSettings.GetRanges
GetRanges()
void TileReachCheckSettings.GetRanges (Player player, out int x, out int y) inline
     {
         x = Player.tileRangeX * TileRangeMultiplier;
         y = Player.tileRangeY * TileRangeMultiplier;
         int? tileReachLimit = TileReachLimit;
         if (tileReachLimit.HasValue)
         {
             int value = tileReachLimit.Value;
             if (x > value)
             {
                 x = value;
             }
             if (y > value)
             {
                 y = value;
             }
         }
         if (OverrideXReach.HasValue)
         {
             x = OverrideXReach.Value;
         }
         if (OverrideYReach.HasValue)
         {
             y = OverrideYReach.Value;
         }
     }
References OverrideXReach, OverrideYReach, TileRangeMultiplier, Player.tileRangeX, Player.tileRangeY, and TileReachLimit.
Referenced by Player.InInteractionRange(), Player.IsInTileInteractionRange(), and Player.IsTileTypeInInteractionRange().