Terraria: System.SpanHelpers.LastIndexOf
LastIndexOf() [1/3]
static int System.SpanHelpers.LastIndexOf (ref byte searchSpace, byte value, int length) inline static
Definition at line 395 of file SpanHelpers.cs.
    {
        nuint num = (uint)length;
        nuint num2 = (uint)length;
        if (Vector.IsHardwareAccelerated && length >= Vector<byte>.Count * 2)
        {
            num2 = UnalignedCountVectorFromEnd(ref searchSpace, length);
        }
        while (true)
        {
            if (num2 >= 8)
            {
                num2 -= 8;
                num -= 8;
                if (value == Unsafe.AddByteOffset(ref searchSpace, num + 7))
                {
                    break;
                }
                if (value != Unsafe.AddByteOffset(ref searchSpace, num + 6))
                {
                    if (value != Unsafe.AddByteOffset(ref searchSpace, num + 5))
                    {
                        if (value != Unsafe.AddByteOffset(ref searchSpace, num + 4))
{
                            if (value != Unsafe.AddByteOffset(ref searchSpace, num + 3))
{
                                if (value != Unsafe.AddByteOffset(ref searchSpace, num + 2))
{
                                    if (value != Unsafe.AddByteOffset(ref searchSpace, num + 1))
{
                                        if (value != Unsafe.AddByteOffset(ref searchSpace, num))
{
                                            continue;
                                        }
                                        goto IL_01ba;
                                    }
                                    goto IL_01bd;
                                }
                                goto IL_01c3;
                            }
                            goto IL_01c9;
                        }
                        return (int)(num + 4);
                    }
                    return (int)(num + 5);
                }
                return (int)(num + 6);
            }
            if (num2 >= 4)
            {
                num2 -= 4;
                num -= 4;
                if (value == Unsafe.AddByteOffset(ref searchSpace, num + 3))
                {
                    goto IL_01c9;
                }
                if (value == Unsafe.AddByteOffset(ref searchSpace, num + 2))
                {
                    goto IL_01c3;
                }
                if (value == Unsafe.AddByteOffset(ref searchSpace, num + 1))
                {
                    goto IL_01bd;
                }
                if (value == Unsafe.AddByteOffset(ref searchSpace, num))
                {
                    goto IL_01ba;
                }
            }
            while (num2 != 0)
            {
                num2--;
                num--;
                if (value != Unsafe.AddByteOffset(ref searchSpace, num))
                {
                    continue;
                }
                goto IL_01ba;
            }
            if (Vector.IsHardwareAccelerated && num != 0)
            {
                num2 = num & (nuint)(~(Vector<byte>.Count - 1));
                Vector<byte> left = new Vector<byte>(value);
                while (num2 > (nuint)(Vector<byte>.Count - 1))
                {
                    Vector<byte> vector = Vector.Equals(left, LoadVector(ref searchSpace, num - (nuint)Vector<byte>.Count));
                    if (Vector<byte>.Zero.Equals(vector))
                    {
                        num -= (nuint)Vector<byte>.Count;
                        num2 -= (nuint)Vector<byte>.Count;
                        continue;
                    }
                    return (int)num - Vector<byte>.Count + LocateLastFoundByte(vector);
                }
                if (num != 0)
                {
                    num2 = num;
                    continue;
                }
            }
            return -1;
            IL_01ba:
            return (int)num;
            IL_01c3:
            return (int)(num + 2);
            IL_01c9:
            return (int)(num + 3);
            IL_01bd:
            return (int)(num + 1);
        }
        return (int)(num + 7);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Numerics.Vector< T >.Equals(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.length, System.SpanHelpers.LoadVector(), System.SpanHelpers.LocateLastFoundByte(), System.SpanHelpers.UnalignedCountVectorFromEnd(), and System.value.