Terraria: System.SpanHelpers.IndexOf
IndexOf() [2/4]
static int System.SpanHelpers.IndexOf (ref byte searchSpace, int searchSpaceLength, ref byte value, int valueLength) inline static
Definition at line 67 of file SpanHelpers.cs.
    {
        if (valueLength == 0)
        {
            return 0;
        }
        byte value2 = value;
        ref byte second = ref Unsafe.Add(ref value, 1);
        int num = valueLength - 1;
        int num2 = searchSpaceLength - num;
        int num3 = 0;
        while (num2 > 0)
        {
            int num4 = IndexOf(ref Unsafe.Add(ref searchSpace, num3), value2, num2);
            if (num4 == -1)
            {
                break;
            }
            num2 -= num4;
            num3 += num4;
            if (num2 <= 0)
            {
                break;
            }
            if (SequenceEqual(ref Unsafe.Add(ref searchSpace, num3 + 1), ref second, (nuint)num))
            {
                return num3;
            }
            num2--;
            num3++;
        }
        return -1;
    }
References System.SpanHelpers.IndexOf(), System.SpanHelpers.SequenceEqual(), and System.value.
Referenced by System.String.Contains(), System.StubHelpers.CSTRMarshaler.ConvertFixedToManaged(), System.StubHelpers.FixedWSTRMarshaler.ConvertToManaged(), System.String.IndexOf(), System.String.IndexOf(), System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOf(), System.MemoryExtensions.IndexOf(), System.SpanHelpers.IndexOf< T >(), System.Array.IndexOf< T >(), System.MemoryExtensions.IndexOf< T >(), System.MemoryExtensions.IndexOf< T >(), System.MemoryExtensions.IndexOf< T >(), System.MemoryExtensions.IndexOf< T >(), System.MemoryExtensions.IndexOfAny< T >(), System.String.Replace(), System.String.strlen(), and System.String.wcslen().