Terraria: System.SpanHelpers.IndexOfAny
IndexOfAny() [2/6]
static int System.SpanHelpers.IndexOfAny (ref byte searchSpace, byte value0, byte value1, int length) inline static
Definition at line 509 of file SpanHelpers.cs.
    {
        nuint num = 0u;
        nuint num2 = (uint)length;
        if (Sse2.IsSupported || AdvSimd.Arm64.IsSupported)
        {
            nint num3 = (nint)length - (nint)Vector128<byte>.Count;
            if (num3 >= 0)
            {
                num2 = (nuint)num3;
                goto IL_0212;
            }
        }
        else if (Vector.IsHardwareAccelerated)
        {
            nint num4 = (nint)length - (nint)Vector<byte>.Count;
            if (num4 >= 0)
            {
                num2 = (nuint)num4;
                goto IL_0212;
            }
        }
        while (num2 >= 8)
        {
            num2 -= 8;
            uint num5 = Unsafe.AddByteOffset(ref searchSpace, num);
            if (value0 == num5 || value1 == num5)
            {
                goto IL_01e5;
            }
            num5 = Unsafe.AddByteOffset(ref searchSpace, num + 1);
            if (value0 == num5 || value1 == num5)
            {
                goto IL_01e8;
            }
            num5 = Unsafe.AddByteOffset(ref searchSpace, num + 2);
            if (value0 == num5 || value1 == num5)
            {
                goto IL_01ee;
            }
            num5 = Unsafe.AddByteOffset(ref searchSpace, num + 3);
            if (value0 != num5 && value1 != num5)
            {
                num5 = Unsafe.AddByteOffset(ref searchSpace, num + 4);
                if (value0 != num5 && value1 != num5)
                {
                    num5 = Unsafe.AddByteOffset(ref searchSpace, num + 5);
                    if (value0 != num5 && value1 != num5)
                    {
                        num5 = Unsafe.AddByteOffset(ref searchSpace, num + 6);
                        if (value0 != num5 && value1 != num5)
{
                            num5 = Unsafe.AddByteOffset(ref searchSpace, num + 7);
                            if (value0 != num5 && value1 != num5)
{
                                num += 8;
                                continue;
                            }
                            return (int)(num + 7);
                        }
                        return (int)(num + 6);
                    }
                    return (int)(num + 5);
                }
                return (int)(num + 4);
            }
            goto IL_01f4;
        }
        if (num2 >= 4)
        {
            num2 -= 4;
            uint num5 = Unsafe.AddByteOffset(ref searchSpace, num);
            if (value0 == num5 || value1 == num5)
            {
                goto IL_01e5;
            }
            num5 = Unsafe.AddByteOffset(ref searchSpace, num + 1);
            if (value0 == num5 || value1 == num5)
            {
                goto IL_01e8;
            }
            num5 = Unsafe.AddByteOffset(ref searchSpace, num + 2);
            if (value0 == num5 || value1 == num5)
            {
                goto IL_01ee;
            }
            num5 = Unsafe.AddByteOffset(ref searchSpace, num + 3);
            if (value0 == num5 || value1 == num5)
            {
                goto IL_01f4;
            }
            num += 4;
        }
        while (num2 != 0)
        {
            uint num5 = Unsafe.AddByteOffset(ref searchSpace, num);
            if (value0 != num5 && value1 != num5)
            {
                num++;
                num2--;
                continue;
            }
            goto IL_01e5;
        }
        goto IL_01e3;
        IL_0212:
        int num6;
        if (Sse2.IsSupported)
        {
            if (Avx2.IsSupported && num2 >= (nuint)Vector128<byte>.Count)
            {
                Vector256<byte> left = Vector256.Create(value0);
                Vector256<byte> left2 = Vector256.Create(value1);
                num2 -= (nuint)Vector128<byte>.Count;
                Vector256<byte> right;
                while (num2 > num)
                {
                    right = LoadVector256(ref searchSpace, num);
                    num6 = Avx2.MoveMask(Avx2.Or(Avx2.CompareEqual(left, right), Avx2.CompareEqual(left2, right)));
                    if (num6 == 0)
                    {
                        num += (nuint)Vector256<byte>.Count;
                        continue;
                    }
                    goto IL_033c;
                }
                right = LoadVector256(ref searchSpace, num2);
                num = num2;
                num6 = Avx2.MoveMask(Avx2.Or(Avx2.CompareEqual(left, right), Avx2.CompareEqual(left2, right)));
                if (num6 == 0)
                {
                    goto IL_01e3;
                }
            }
            else
            {
                Vector128<byte> left3 = Vector128.Create(value0);
                Vector128<byte> left4 = Vector128.Create(value1);
                Vector128<byte> right2;
                while (num2 > num)
                {
                    right2 = LoadVector128(ref searchSpace, num);
                    num6 = Sse2.MoveMask(Sse2.Or(Sse2.CompareEqual(left3, right2), Sse2.CompareEqual(left4, right2)).AsByte());
                    if (num6 == 0)
                    {
                        num += (nuint)Vector128<byte>.Count;
                        continue;
                    }
                    goto IL_033c;
                }
                right2 = LoadVector128(ref searchSpace, num2);
                num = num2;
                num6 = Sse2.MoveMask(Sse2.Or(Sse2.CompareEqual(left3, right2), Sse2.CompareEqual(left4, right2)));
                if (num6 == 0)
                {
                    goto IL_01e3;
                }
            }
            goto IL_033c;
        }
        if (AdvSimd.Arm64.IsSupported)
        {
        }
        if (!Vector.IsHardwareAccelerated)
        {
            goto IL_01e5;
        }
        Vector<byte> right3 = new Vector<byte>(value0);
        Vector<byte> right4 = new Vector<byte>(value1);
        Vector<byte> left5;
        while (num2 > num)
        {
            left5 = LoadVector(ref searchSpace, num);
            left5 = Vector.BitwiseOr(Vector.Equals(left5, right3), Vector.Equals(left5, right4));
            if (Vector<byte>.Zero.Equals(left5))
            {
                num += (nuint)Vector<byte>.Count;
                continue;
            }
            goto IL_03ec;
        }
        left5 = LoadVector(ref searchSpace, num2);
        num = num2;
        left5 = Vector.BitwiseOr(Vector.Equals(left5, right3), Vector.Equals(left5, right4));
        if (Vector<byte>.Zero.Equals(left5))
        {
            goto IL_01e3;
        }
        goto IL_03ec;
        IL_033c:
        num += (nuint)BitOperations.TrailingZeroCount(num6);
        goto IL_01e5;
        IL_01e3:
        return -1;
        IL_01e5:
        return (int)num;
        IL_03ec:
        num += (nuint)LocateFirstFoundByte(left5);
        goto IL_01e5;
        IL_01ee:
        return (int)(num + 2);
        IL_01e8:
        return (int)(num + 1);
        IL_01f4:
        return (int)(num + 3);
    }
References System.Runtime.Intrinsics.X86.Sse2.CompareEqual(), System.Runtime.Intrinsics.X86.Avx2.CompareEqual(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector256< T >.Create(), System.Numerics.Vector< T >.Equals(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Avx2.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.length, System.SpanHelpers.LoadVector(), System.SpanHelpers.LoadVector128(), System.SpanHelpers.LoadVector256(), System.SpanHelpers.LocateFirstFoundByte(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Avx2.MoveMask(), System.Runtime.Intrinsics.X86.Sse2.Or(), System.Runtime.Intrinsics.X86.Avx2.Or(), and System.Numerics.BitOperations.TrailingZeroCount().
Referenced by System.MemoryExtensions.IndexOfAny< T >(), System.MemoryExtensions.IndexOfAny< T >(), System.MemoryExtensions.IndexOfAny< T >(), System.MemoryExtensions.IndexOfAny< T >(), and System.MemoryExtensions.IndexOfAny< T >().