Terraria: System.SpanHelpers.LocateFirstFoundByte
LocateFirstFoundByte() [2/2]
static int System.SpanHelpers.LocateFirstFoundByte (Vector< byte > match) inline static private
Definition at line 1353 of file SpanHelpers.cs.
    {
        Vector<ulong> vector = Vector.AsVectorUInt64(match);
        ulong num = 0uL;
        int i;
        for (i = 0; i < Vector<ulong>.Count; i++)
        {
            num = vector[i];
            if (num != 0L)
            {
                break;
            }
        }
        return i * 8 + LocateFirstFoundByte(num);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.L, System.SpanHelpers.LocateFirstFoundByte(), and System.match.
Referenced by System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), and System.SpanHelpers.LocateFirstFoundByte().