Terraria: System.SpanHelpers.IndexOfAny
IndexOfAny() [4/6]
static int System.SpanHelpers.IndexOfAny (ref char searchStart, char value0, char value1, char value2, char value3, int length) inline static
Definition at line 2244 of file SpanHelpers.cs.
    {
        nuint num = 0u;
        nuint num2 = (uint)length;
        int num4;
        if (Sse2.IsSupported)
        {
            nint num3 = (nint)length - (nint)Vector128<ushort>.Count;
            if (num3 >= 0)
            {
                num2 = (nuint)num3;
                if (Sse2.IsSupported)
                {
                    if (Avx2.IsSupported && num2 >= (nuint)Vector128<ushort>.Count)
                    {
                        Vector256<ushort> left = Vector256.Create(value0);
                        Vector256<ushort> left2 = Vector256.Create(value1);
                        Vector256<ushort> left3 = Vector256.Create(value2);
                        Vector256<ushort> left4 = Vector256.Create(value3);
                        num2 -= (nuint)Vector128<ushort>.Count;
                        Vector256<ushort> right;
                        while (num2 > num)
{
                            right = LoadVector256(ref searchStart, num);
                            num4 = Avx2.MoveMask(Avx2.CompareEqual(left, right).AsByte());
                            num4 |= Avx2.MoveMask(Avx2.CompareEqual(left2, right).AsByte());
                            num4 |= Avx2.MoveMask(Avx2.CompareEqual(left3, right).AsByte());
                            num4 |= Avx2.MoveMask(Avx2.CompareEqual(left4, right).AsByte());
                            if (num4 == 0)
{
                                num += (nuint)Vector256<ushort>.Count;
                                continue;
                            }
                            goto IL_036f;
                        }
                        right = LoadVector256(ref searchStart, num2);
                        num = num2;
                        num4 = Avx2.MoveMask(Avx2.CompareEqual(left, right).AsByte());
                        num4 |= Avx2.MoveMask(Avx2.CompareEqual(left2, right).AsByte());
                        num4 |= Avx2.MoveMask(Avx2.CompareEqual(left3, right).AsByte());
                        num4 |= Avx2.MoveMask(Avx2.CompareEqual(left4, right).AsByte());
                        if (num4 == 0)
{
                            goto IL_0115;
                        }
                    }
                    else
                    {
                        Vector128<ushort> left5 = Vector128.Create(value0);
                        Vector128<ushort> left6 = Vector128.Create(value1);
                        Vector128<ushort> left7 = Vector128.Create(value2);
                        Vector128<ushort> left8 = Vector128.Create(value3);
                        Vector128<ushort> right2;
                        while (num2 > num)
{
                            right2 = LoadVector128(ref searchStart, num);
                            num4 = Sse2.MoveMask(Sse2.CompareEqual(left5, right2).AsByte());
                            num4 |= Sse2.MoveMask(Sse2.CompareEqual(left6, right2).AsByte());
                            num4 |= Sse2.MoveMask(Sse2.CompareEqual(left7, right2).AsByte());
                            num4 |= Sse2.MoveMask(Sse2.CompareEqual(left8, right2).AsByte());
                            if (num4 == 0)
{
                                num += (nuint)Vector128<ushort>.Count;
                                continue;
                            }
                            goto IL_036f;
                        }
                        right2 = LoadVector128(ref searchStart, num2);
                        num = num2;
                        num4 = Sse2.MoveMask(Sse2.CompareEqual(left5, right2).AsByte());
                        num4 |= Sse2.MoveMask(Sse2.CompareEqual(left6, right2).AsByte());
                        num4 |= Sse2.MoveMask(Sse2.CompareEqual(left7, right2).AsByte());
                        num4 |= Sse2.MoveMask(Sse2.CompareEqual(left8, right2).AsByte());
                        if (num4 == 0)
{
                            goto IL_0115;
                        }
                    }
                    goto IL_036f;
                }
                goto IL_0381;
            }
        }
        else if (Vector.IsHardwareAccelerated)
        {
            nint num5 = (nint)length - (nint)Vector<ushort>.Count;
            if (num5 >= 0)
            {
                num2 = (nuint)num5;
                goto IL_0381;
            }
        }
        while (num2 >= 4)
        {
            ref char reference = ref Add(ref searchStart, num);
            int num6 = reference;
            if (value0 != num6 && value1 != num6 && value2 != num6 && value3 != num6)
            {
                num6 = Unsafe.Add(ref reference, 1);
                if (value0 != num6 && value1 != num6 && value2 != num6 && value3 != num6)
                {
                    num6 = Unsafe.Add(ref reference, 2);
                    if (value0 != num6 && value1 != num6 && value2 != num6 && value3 != num6)
                    {
                        num6 = Unsafe.Add(ref reference, 3);
                        if (value0 != num6 && value1 != num6 && value2 != num6 && value3 != num6)
{
                            num += 4;
                            num2 -= 4;
                            continue;
                        }
                        return (int)(num + 3);
                    }
                    return (int)(num + 2);
                }
                return (int)(num + 1);
            }
            goto IL_0129;
        }
        while (num2 != 0)
        {
            int num6 = Add(ref searchStart, num);
            if (value0 != num6 && value1 != num6 && value2 != num6 && value3 != num6)
            {
                num++;
                num2--;
                continue;
            }
            goto IL_0129;
        }
        goto IL_0115;
        IL_0129:
        return (int)num;
        IL_0115:
        return -1;
        IL_046a:
        Vector<ushort> vector;
        num += (uint)LocateFirstFoundChar(vector);
        goto IL_0129;
        IL_036f:
        num += (nuint)(uint)BitOperations.TrailingZeroCount(num4) >> 1;
        goto IL_0129;
        IL_0381:
        if (!Sse2.IsSupported && Vector.IsHardwareAccelerated)
        {
            Vector<ushort> right3 = new Vector<ushort>(value0);
            Vector<ushort> right4 = new Vector<ushort>(value1);
            Vector<ushort> right5 = new Vector<ushort>(value2);
            Vector<ushort> right6 = new Vector<ushort>(value3);
            while (num2 > num)
            {
                vector = LoadVector(ref searchStart, num);
                vector = Vector.BitwiseOr(Vector.BitwiseOr(Vector.BitwiseOr(Vector.Equals(vector, right3), Vector.Equals(vector, right4)), Vector.Equals(vector, right5)), Vector.Equals(vector, right6));
                if (Vector<ushort>.Zero.Equals(vector))
                {
                    num += (nuint)Vector<ushort>.Count;
                    continue;
                }
                goto IL_046a;
            }
            vector = LoadVector(ref searchStart, num2);
            num = num2;
            vector = Vector.BitwiseOr(Vector.BitwiseOr(Vector.BitwiseOr(Vector.Equals(vector, right3), Vector.Equals(vector, right4)), Vector.Equals(vector, right5)), Vector.Equals(vector, right6));
            if (!Vector<ushort>.Zero.Equals(vector))
            {
                goto IL_046a;
            }
        }
        goto IL_0115;
    }
References System.Add, System.Runtime.Intrinsics.X86.Sse2.CompareEqual(), System.Runtime.Intrinsics.X86.Avx2.CompareEqual(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Vector256< T >.Create(), System.Numerics.Vector< T >.Equals(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.Runtime.Intrinsics.X86.Avx2.IsSupported, System.Runtime.Intrinsics.X86.Sse2.IsSupported, System.length, System.SpanHelpers.LoadVector(), System.SpanHelpers.LoadVector128(), System.SpanHelpers.LoadVector256(), System.SpanHelpers.LocateFirstFoundChar(), System.Runtime.Intrinsics.X86.Sse2.MoveMask(), System.Runtime.Intrinsics.X86.Avx2.MoveMask(), and System.Numerics.BitOperations.TrailingZeroCount().