Terraria: System.SpanHelpers.Contains
Contains() [1/2]
static bool System.SpanHelpers.Contains (ref byte searchSpace, byte value, int length) inline static
Definition at line 102 of file SpanHelpers.cs.
    {
        nuint num = 0u;
        nuint num2 = (uint)length;
        if (Vector.IsHardwareAccelerated && length >= Vector<byte>.Count * 2)
        {
            num2 = UnalignedCountVector(ref searchSpace);
        }
        while (true)
        {
            if (num2 >= 8)
            {
                num2 -= 8;
                if (value == Unsafe.AddByteOffset(ref searchSpace, num + 0) || value == Unsafe.AddByteOffset(ref searchSpace, num + 1) || value == Unsafe.AddByteOffset(ref searchSpace, num + 2) || value == Unsafe.AddByteOffset(ref searchSpace, num + 3) || value == Unsafe.AddByteOffset(ref searchSpace, num + 4) || value == Unsafe.AddByteOffset(ref searchSpace, num + 5) || value == Unsafe.AddByteOffset(ref searchSpace, num + 6) || value == Unsafe.AddByteOffset(ref searchSpace, num + 7))
                {
                    break;
                }
                num += 8;
                continue;
            }
            if (num2 >= 4)
            {
                num2 -= 4;
                if (value == Unsafe.AddByteOffset(ref searchSpace, num + 0) || value == Unsafe.AddByteOffset(ref searchSpace, num + 1) || value == Unsafe.AddByteOffset(ref searchSpace, num + 2) || value == Unsafe.AddByteOffset(ref searchSpace, num + 3))
                {
                    break;
                }
                num += 4;
            }
            while (num2 != 0)
            {
                num2--;
                if (value == Unsafe.AddByteOffset(ref searchSpace, num))
                {
                    goto end_IL_00bd;
                }
                num++;
            }
            if (Vector.IsHardwareAccelerated && num < (uint)length)
            {
                num2 = ((uint)length - num) & (nuint)(~(Vector<byte>.Count - 1));
                Vector<byte> left = new Vector<byte>(value);
                for (; num2 > num; num += (nuint)Vector<byte>.Count)
                {
                    Vector<byte> other = Vector.Equals(left, LoadVector(ref searchSpace, num));
                    if (!Vector<byte>.Zero.Equals(other))
                    {
                        goto end_IL_00bd;
                    }
                }
                if (num < (uint)length)
                {
                    num2 = (uint)length - num;
                    continue;
                }
            }
            return false;
            continue;
            end_IL_00bd:
            break;
        }
        return true;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Numerics.Vector< T >.Equals(), System.Numerics.Vector< T >.IsHardwareAccelerated, System.length, System.SpanHelpers.LoadVector(), System.other, System.SpanHelpers.UnalignedCountVector(), and System.value.
Referenced by System.String.Contains(), System.MemoryExtensions.Contains< T >(), and System.MemoryExtensions.Contains< T >().