Terraria: System.SpanHelpers.ClearWithReferences
ClearWithReferences()
static void System.SpanHelpers.ClearWithReferences (ref IntPtr ip, nuint pointerSizeLength) inline static
Definition at line 2803 of file SpanHelpers.cs.
    {
        while (pointerSizeLength >= 8)
        {
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -1) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -2) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -3) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -4) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -5) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -6) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -7) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -8) = default(IntPtr);
            pointerSizeLength -= 8;
        }
        if (pointerSizeLength < 4)
        {
            if (pointerSizeLength < 2)
            {
                if (pointerSizeLength == 0)
                {
                    return;
                }
                goto IL_012f;
            }
        }
        else
        {
            Unsafe.Add(ref ip, 2) = default(IntPtr);
            Unsafe.Add(ref ip, 3) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -3) = default(IntPtr);
            Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -2) = default(IntPtr);
        }
        Unsafe.Add(ref ip, 1) = default(IntPtr);
        Unsafe.Add(ref Unsafe.Add(ref ip, (nint)pointerSizeLength), -1) = default(IntPtr);
        goto IL_012f;
        IL_012f:
        ip = default(IntPtr);
    }
Referenced by System.Span< T >.Clear(), System.Array.Clear(), and System.Array.Clear().