Terraria: System.SpanHelpers.ClearWithoutReferences
ClearWithoutReferences()
static void System.SpanHelpers.ClearWithoutReferences (ref byte b, nuint byteLength) inline static
Definition at line 2788 of file SpanHelpers.cs.
    {
        if (byteLength != 0)
        {
            if (byteLength <= 768)
            {
                Unsafe.InitBlockUnaligned(ref b, 0, (uint)byteLength);
            }
            else
            {
                Buffer._ZeroMemory(ref b, byteLength);
            }
        }
    }
References System.Buffer._ZeroMemory(), and Internal.Runtime.CompilerServices.Unsafe.InitBlockUnaligned().
Referenced by System.Span< T >.Clear(), System.Array.Clear(), System.Array.Clear(), and System.Buffer.ZeroMemory().