Terraria: System.Net.NetworkCredential.MarshalToString
MarshalToString()
string System.Net.NetworkCredential.MarshalToString (SecureString sstr) inline private inherited
Definition at line 126 of file NetworkCredential.cs.
    {
        if (sstr == null || sstr.Length == 0)
        {
            return string.Empty;
        }
        IntPtr intPtr = IntPtr.Zero;
        string empty = string.Empty;
        try
        {
            intPtr = Marshal.SecureStringToGlobalAllocUnicode(sstr);
            return Marshal.PtrToStringUni(intPtr);
        }
        finally
        {
            if (intPtr != IntPtr.Zero)
            {
                Marshal.ZeroFreeGlobalAllocUnicode(intPtr);
            }
        }
    }
References System.Security.SecureString.Length, System.Runtime.InteropServices.Marshal.PtrToStringUni(), System.Runtime.InteropServices.Marshal.SecureStringToGlobalAllocUnicode(), System.IntPtr.Zero, and System.Runtime.InteropServices.Marshal.ZeroFreeGlobalAllocUnicode().