Terraria: System.SpanHelpers.LocateFirstFoundChar
LocateFirstFoundChar() [2/2]
static int System.SpanHelpers.LocateFirstFoundChar (Vector< ushort > match) inline static private
Definition at line 2670 of file SpanHelpers.cs.
    {
        Vector<ulong> vector = Vector.AsVectorUInt64(match);
        ulong num = 0uL;
        int i;
        for (i = 0; i < Vector<ulong>.Count; i++)
        {
            num = vector[i];
            if (num != 0L)
            {
                break;
            }
        }
        return i * 4 + LocateFirstFoundChar(num);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.L, System.SpanHelpers.LocateFirstFoundChar(), and System.match.
Referenced by System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), System.SpanHelpers.IndexOfAny(), and System.SpanHelpers.LocateFirstFoundChar().