Terraria: System.Security.AccessControl.Privilege.Reset
Reset()
void System.Security.AccessControl.Privilege.Reset () inline private
Definition at line 378 of file Privilege.cs.
    {
        stateWasChanged = false;
        initialState = false;
        needToRevert = false;
        if (tlsContents != null && tlsContents.DecrementReferenceCount() == 0)
        {
            tlsContents = null;
            t_tlsSlotData = null;
        }
    }
References System.Security.AccessControl.Privilege.TlsContents.DecrementReferenceCount(), System.Security.AccessControl.Privilege.initialState, System.Security.AccessControl.Privilege.needToRevert, System.Security.AccessControl.Privilege.stateWasChanged, System.Security.AccessControl.Privilege.t_tlsSlotData, and System.Security.AccessControl.Privilege.tlsContents.
Referenced by System.Security.AccessControl.Privilege.Revert(), and System.Security.AccessControl.Privilege.ToggleState().