Terraria: System.Security.AccessControl.Privilege.ToggleState
ToggleState()
unsafe void System.Security.AccessControl.Privilege.ToggleState (bool enable) inline private
Definition at line 264 of file Privilege.cs.
    {
        int num = 0;
        if (!currentThread.Equals(Thread.CurrentThread))
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_MustBeSameThread);
        }
        if (needToRevert)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_MustRevertPrivilege);
        }
        try
        {
            tlsContents = t_tlsSlotData;
            if (tlsContents == null)
            {
                tlsContents = new TlsContents();
                t_tlsSlotData = tlsContents;
            }
            else
            {
                tlsContents.IncrementReferenceCount();
            }
            Unsafe.SkipInit(out global::Interop.Advapi32.TOKEN_PRIVILEGE tOKEN_PRIVILEGE);
            tOKEN_PRIVILEGE.PrivilegeCount = 1u;
            tOKEN_PRIVILEGE.Privileges.Luid = luid;
            tOKEN_PRIVILEGE.Privileges.Attributes = (enable ? 2u : 0u);
            global::Interop.Advapi32.TOKEN_PRIVILEGE tOKEN_PRIVILEGE2 = default(global::Interop.Advapi32.TOKEN_PRIVILEGE);
            uint num2 = 0u;
            if (!global::Interop.Advapi32.AdjustTokenPrivileges(tlsContents.ThreadHandle, DisableAllPrivileges: false, &tOKEN_PRIVILEGE, (uint)sizeof(global::Interop.Advapi32.TOKEN_PRIVILEGE), &tOKEN_PRIVILEGE2, &num2))
            {
                num = Marshal.GetLastWin32Error();
            }
            else if (1300 == Marshal.GetLastWin32Error())
            {
                num = 1300;
            }
            else
            {
                initialState = (tOKEN_PRIVILEGE2.Privileges.Attributes & 2) != 0;
                stateWasChanged = initialState != enable;
                needToRevert = tlsContents.IsImpersonating || stateWasChanged;
            }
        }
        finally
        {
            if (!needToRevert)
            {
                Reset();
            }
        }
        switch (num)
        {
        case 1300:
            throw new PrivilegeNotHeldException(privileges[luid]);
        case 8:
            throw new OutOfMemoryException();
        case 5:
        case 1347:
            throw new UnauthorizedAccessException();
        default:
            throw new InvalidOperationException();
        case 0:
            break;
        }
    }
References System.Threading.Thread.CurrentThread, System.Security.AccessControl.Privilege.currentThread, System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Security.AccessControl.Privilege.TlsContents.IncrementReferenceCount(), System.Security.AccessControl.Privilege.initialState, System.SR.InvalidOperation_MustBeSameThread, System.SR.InvalidOperation_MustRevertPrivilege, System.Security.AccessControl.Privilege.luid, System.Security.AccessControl.Privilege.needToRevert, System.Security.AccessControl.Privilege.privileges, System.Security.AccessControl.Privilege.Reset(), System.Security.AccessControl.Privilege.stateWasChanged, System.Security.AccessControl.Privilege.t_tlsSlotData, System.Security.AccessControl.Privilege.TlsContents.ThreadHandle, and System.Security.AccessControl.Privilege.tlsContents.
Referenced by System.Security.AccessControl.Privilege.Enable().