Terraria: System.Security.AccessControl.Privilege.Revert
Revert()
unsafe void System.Security.AccessControl.Privilege.Revert () inline
Definition at line 331 of file Privilege.cs.
    {
        int num = 0;
        if (!currentThread.Equals(Thread.CurrentThread))
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_MustBeSameThread);
        }
        if (!NeedToRevert)
        {
            return;
        }
        bool flag = true;
        try
        {
            if (stateWasChanged && (tlsContents.ReferenceCountValue > 1 || !tlsContents.IsImpersonating))
            {
                Unsafe.SkipInit(out global::Interop.Advapi32.TOKEN_PRIVILEGE tOKEN_PRIVILEGE);
                tOKEN_PRIVILEGE.PrivilegeCount = 1u;
                tOKEN_PRIVILEGE.Privileges.Luid = luid;
                tOKEN_PRIVILEGE.Privileges.Attributes = (initialState ? 2u : 0u);
                if (!global::Interop.Advapi32.AdjustTokenPrivileges(tlsContents.ThreadHandle, DisableAllPrivileges: false, &tOKEN_PRIVILEGE, 0u, null, null))
                {
                    num = Marshal.GetLastWin32Error();
                    flag = false;
                }
            }
        }
        finally
        {
            if (flag)
            {
                Reset();
            }
        }
        switch (num)
        {
        case 8:
            throw new OutOfMemoryException();
        case 5:
            throw new UnauthorizedAccessException();
        default:
            throw new InvalidOperationException();
        case 0:
            break;
        }
    }
References System.Threading.Thread.CurrentThread, System.Security.AccessControl.Privilege.currentThread, System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Security.AccessControl.Privilege.initialState, System.SR.InvalidOperation_MustBeSameThread, System.Security.AccessControl.Privilege.TlsContents.IsImpersonating, System.Security.AccessControl.Privilege.luid, System.Security.AccessControl.Privilege.NeedToRevert, System.Security.AccessControl.Privilege.TlsContents.ReferenceCountValue, System.Security.AccessControl.Privilege.Reset(), System.Security.AccessControl.Privilege.stateWasChanged, System.Security.AccessControl.Privilege.TlsContents.ThreadHandle, and System.Security.AccessControl.Privilege.tlsContents.
Referenced by System.Security.AccessControl.Privilege.~Privilege(), System.Security.AccessControl.Win32.GetSecurityInfo(), System.Security.AccessControl.ObjectSecurity< T >.Persist(), and System.Security.AccessControl.Win32.SetSecurityInfo().