Terraria: System.Security.AccessControl.Privilege.LuidFromPrivilege
LuidFromPrivilege()
static global.Interop.Advapi32.LUID System.Security.AccessControl.Privilege.LuidFromPrivilege (string privilege) inline static private
Definition at line 190 of file Privilege.cs.
    {
        Unsafe.SkipInit(out global::Interop.Advapi32.LUID lpLuid);
        lpLuid.LowPart = 0;
        lpLuid.HighPart = 0;
        try
        {
            privilegeLock.EnterReadLock();
            if (luids.ContainsKey(privilege))
            {
                lpLuid = luids[privilege];
                privilegeLock.ExitReadLock();
            }
            else
            {
                privilegeLock.ExitReadLock();
                if (!global::Interop.Advapi32.LookupPrivilegeValue(null, privilege, out lpLuid))
                {
                    switch (Marshal.GetLastWin32Error())
                    {
                    case 8:
                        throw new OutOfMemoryException();
                    case 5:
                        throw new UnauthorizedAccessException();
                    case 1313:
                        throw new ArgumentException(System.SR.Format(System.SR.Argument_InvalidPrivilegeName, privilege));
                    default:
                        throw new InvalidOperationException();
                    }
                }
                privilegeLock.EnterWriteLock();
            }
        }
        finally
        {
            if (privilegeLock.IsReadLockHeld)
            {
                privilegeLock.ExitReadLock();
            }
            if (privilegeLock.IsWriteLockHeld)
            {
                if (!luids.ContainsKey(privilege))
                {
                    luids[privilege] = lpLuid;
                    privileges[lpLuid] = privilege;
                }
                privilegeLock.ExitWriteLock();
            }
        }
        return lpLuid;
    }
References System.SR.Argument_InvalidPrivilegeName, System.SR.Format(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Security.AccessControl.Privilege.luids, System.Security.AccessControl.Privilege.privilegeLock, and System.Security.AccessControl.Privilege.privileges.
Referenced by System.Security.AccessControl.Privilege.Privilege().