Terraria: TEItemFrame.PlaceItemInFrame
PlaceItemInFrame()
static void TEItemFrame.PlaceItemInFrame (Player player, int x, int y) inline static
     {
         if (!player.ItemTimeIsZero)
         {
             return;
         }
         if (Main.tile[x, y].frameX % 36 != 0)
         {
             x--;
         }
         if (Main.tile[x, y].frameY % 36 != 0)
         {
             y--;
         }
         int num = Find(x, y);
         if (num == -1)
         {
             return;
         }
         if (((TEItemFrame)TileEntity.ByID[num]).item.stack > 0)
         {
             WorldGen.KillTile(x, y, fail: true);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, Player.tileTargetX, y, 1f);
             }
         }
         if (Main.netMode == 1)
         {
             NetMessage.SendData(89, -1, -1, null, x, y, player.selectedItem, player.whoAmI, 1);
         }
         else
         {
             TryPlacing(x, y, player.inventory[player.selectedItem].netID, player.inventory[player.selectedItem].prefix, 1);
         }
         player.inventory[player.selectedItem].stack--;
         if (player.inventory[player.selectedItem].stack <= 0)
         {
             player.inventory[player.selectedItem].SetDefaults();
             Main.mouseItem.SetDefaults();
         }
         if (player.selectedItem == 58)
         {
             Main.mouseItem = player.inventory[player.selectedItem].Clone();
         }
         player.releaseUseItem = false;
         player.mouseInterface = true;
         player.PlayDroppedItemAnimation(20);
         WorldGen.RangeFrame(x, y, x + 2, y + 2);
     }
References TileEntity.ByID, Item.Clone(), Find(), Tile.frameX, Tile.frameY, Player.inventory, Player.ItemTimeIsZero, WorldGen.KillTile(), Player.mouseInterface, Main.mouseItem, Item.netID, Main.netMode, Player.PlayDroppedItemAnimation(), Item.prefix, WorldGen.RangeFrame(), Player.releaseUseItem, Player.selectedItem, NetMessage.SendData(), Item.SetDefaults(), Item.stack, Main.tile, Player.tileTargetX, TryPlacing(), and Entity.whoAmI.
Referenced by OnPlayerInteraction().