Terraria: System.Security.AccessControl.ObjectSecurity.SetOwner
SetOwner()
void System.Security.AccessControl.ObjectSecurity< T >.SetOwner (IdentityReference identity) inline
Definition at line 315 of file ObjectSecurity.cs.
    {
        if (identity == null)
        {
            throw new ArgumentNullException("identity");
        }
        WriteLock();
        try
        {
            _securityDescriptor.Owner = identity.Translate(typeof(SecurityIdentifier)) as SecurityIdentifier;
            _ownerModified = true;
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._ownerModified, System.Security.Principal.IdentityReference.Translate(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().
Referenced by System.IO.Pipes.NamedPipeServerStream.Create().