Terraria: System.Security.AccessControl.ObjectSecurity.Persist
Persist() [1/5]
virtual void System.Security.AccessControl.ObjectSecurity< T >.Persist (bool enableOwnershipPrivilege, string name, AccessControlSections includeSections) inline protected virtual
Definition at line 264 of file ObjectSecurity.cs.
    {
        Privilege privilege = null;
        try
        {
            if (enableOwnershipPrivilege)
            {
                privilege = new Privilege("SeTakeOwnershipPrivilege");
                try
                {
                    privilege.Enable();
                }
                catch (PrivilegeNotHeldException)
                {
                }
            }
            Persist(name, includeSections);
        }
        catch
        {
            privilege?.Revert();
            throw;
        }
        finally
        {
            privilege?.Revert();
        }
    }
References System.Security.AccessControl.Privilege.Enable(), System.Security.AccessControl.ObjectSecurity< T >.Persist(), and System.Security.AccessControl.Privilege.Revert().