Terraria: System.Security.AccessControl.ObjectSecurity.WriteLock
WriteLock()
void System.Security.AccessControl.ObjectSecurity< T >.WriteLock () inline protected
Definition at line 249 of file ObjectSecurity.cs.
    {
        _lock.EnterWriteLock();
    }
References System.Security.AccessControl.ObjectSecurity< T >._lock, and System.Threading.ReaderWriterLockSlim.EnterWriteLock().
Referenced by System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(), System.Security.AccessControl.DirectoryObjectSecurity.AddAccessRule(), System.Security.AccessControl.CommonObjectSecurity.AddAuditRule(), System.Security.AccessControl.DirectoryObjectSecurity.AddAuditRule(), System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(), System.Security.AccessControl.ObjectSecurity< T >.ModifyAccessRule(), System.Security.AccessControl.CommonObjectSecurity.ModifyAudit(), System.Security.AccessControl.ObjectSecurity< T >.ModifyAuditRule(), System.Security.AccessControl.FileSystemSecurity.Persist(), System.IO.Pipes.PipeSecurity.Persist(), System.Security.AccessControl.ObjectSecurity< T >.Persist(), System.Security.AccessControl.FileSystemSecurity.Persist(), System.IO.Pipes.PipeSecurity.Persist(), System.Security.AccessControl.ObjectSecurity< T >.Persist(), System.Security.AccessControl.NativeObjectSecurity.Persist(), System.Security.AccessControl.ObjectSecurity< T >.PurgeAccessRules(), System.Security.AccessControl.ObjectSecurity< T >.PurgeAuditRules(), System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRule(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRule(), System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRuleAll(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRuleAll(), System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRuleSpecific(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAccessRuleSpecific(), System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRule(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRule(), System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRuleAll(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRuleAll(), System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRuleSpecific(), System.Security.AccessControl.DirectoryObjectSecurity.RemoveAuditRuleSpecific(), System.Security.AccessControl.CommonObjectSecurity.ResetAccessRule(), System.Security.AccessControl.DirectoryObjectSecurity.ResetAccessRule(), System.Security.AccessControl.CommonObjectSecurity.SetAccessRule(), System.Security.AccessControl.DirectoryObjectSecurity.SetAccessRule(), System.Security.AccessControl.ObjectSecurity< T >.SetAccessRuleProtection(), System.Security.AccessControl.CommonObjectSecurity.SetAuditRule(), System.Security.AccessControl.DirectoryObjectSecurity.SetAuditRule(), System.Security.AccessControl.ObjectSecurity< T >.SetAuditRuleProtection(), System.Security.AccessControl.ObjectSecurity< T >.SetGroup(), System.Security.AccessControl.ObjectSecurity< T >.SetOwner(), System.Security.AccessControl.ObjectSecurity< T >.SetSecurityDescriptorBinaryForm(), and System.Security.AccessControl.ObjectSecurity< T >.SetSecurityDescriptorSddlForm().