Terraria: System.Security.AccessControl.ObjectSecurity.ReadUnlock
ReadUnlock()
void System.Security.AccessControl.ObjectSecurity< T >.ReadUnlock () inline protected
Definition at line 244 of file ObjectSecurity.cs.
    {
        _lock.ExitReadLock();
    }
References System.Security.AccessControl.ObjectSecurity< T >._lock, and System.Threading.ReaderWriterLockSlim.ExitReadLock().
Referenced by System.Security.AccessControl.ObjectSecurity< T >.GetGroup(), System.Security.AccessControl.ObjectSecurity< T >.GetOwner(), System.Security.AccessControl.DirectoryObjectSecurity.GetRules(), System.Security.AccessControl.CommonObjectSecurity.GetRules(), System.Security.AccessControl.ObjectSecurity< T >.GetSecurityDescriptorBinaryForm(), and System.Security.AccessControl.ObjectSecurity< T >.GetSecurityDescriptorSddlForm().