Terraria: System.Security.AccessControl.ObjectSecurity.SetAuditRuleProtection
SetAuditRuleProtection()
void System.Security.AccessControl.ObjectSecurity< T >.SetAuditRuleProtection (bool isProtected, bool preserveInheritance) inline
Definition at line 418 of file ObjectSecurity.cs.
    {
        WriteLock();
        try
        {
            _securityDescriptor.SetSystemAclProtection(isProtected, preserveInheritance);
            _saclModified = true;
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._saclModified, System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.CommonSecurityDescriptor.SetSystemAclProtection(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().