Terraria: System.Security.AccessControl.ObjectSecurity.ModifyAccessRule
ModifyAccessRule()
virtual bool System.Security.AccessControl.ObjectSecurity< T >.ModifyAccessRule (AccessControlModification modification, AccessRule rule, out bool modified) inline virtual
Definition at line 521 of file ObjectSecurity.cs.
    {
        if (rule == null)
        {
            throw new ArgumentNullException("rule");
        }
        if (!AccessRuleType.IsAssignableFrom(rule.GetType()))
        {
            throw new ArgumentException(System.SR.AccessControl_InvalidAccessRuleType, "rule");
        }
        WriteLock();
        try
        {
            return ModifyAccess(modification, rule, out modified);
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.SR.AccessControl_InvalidAccessRuleType, System.Security.AccessControl.ObjectSecurity< T >.AccessRuleType, System.Type.IsAssignableFrom(), System.Security.AccessControl.ObjectSecurity< T >.ModifyAccess(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().