Terraria: System.Security.AccessControl.ObjectSecurity.PurgeAuditRules
PurgeAuditRules()
virtual void System.Security.AccessControl.ObjectSecurity< T >.PurgeAuditRules (IdentityReference identity) inline virtual
Definition at line 386 of file ObjectSecurity.cs.
    {
        if (identity == null)
        {
            throw new ArgumentNullException("identity");
        }
        WriteLock();
        try
        {
            _securityDescriptor.PurgeAudit((SecurityIdentifier)identity.Translate(typeof(SecurityIdentifier)));
            _saclModified = true;
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._saclModified, System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.CommonSecurityDescriptor.PurgeAudit(), System.Security.Principal.IdentityReference.Translate(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().