Terraria: System.Security.AccessControl.ObjectSecurity.GetOwner
GetOwner()
IdentityReference? System.Security.AccessControl.ObjectSecurity< T >.GetOwner (Type targetType) inline
Definition at line 298 of file ObjectSecurity.cs.
    {
        ReadLock();
        try
        {
            if (_securityDescriptor.Owner == null)
            {
                return null;
            }
            return _securityDescriptor.Owner.Translate(targetType);
        }
        finally
        {
            ReadUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.CommonSecurityDescriptor.Owner, System.Security.AccessControl.ObjectSecurity< T >.ReadLock(), System.Security.AccessControl.ObjectSecurity< T >.ReadUnlock(), and System.Security.Principal.SecurityIdentifier.Translate().
Referenced by System.IO.Pipes.NamedPipeClientStream.ValidateRemotePipeUser().