Terraria: System.Security.AccessControl.ObjectSecurity.Persist
Persist() [5/5]
virtual void System.Security.AccessControl.ObjectSecurity< T >.Persist (string name, AccessControlSections includeSections) inline protected virtual
Reimplemented in System.Security.AccessControl.NativeObjectSecurity.
Definition at line 259 of file ObjectSecurity.cs.
    {
        throw System.NotImplemented.ByDesign;
    }
References System.NotImplemented.ByDesign.
Referenced by System.Security.AccessControl.ObjectSecurity< T >.Persist(), System.Security.AccessControl.ObjectSecurity< T >.Persist(), and System.Security.AccessControl.ObjectSecurity< T >.Persist().