Terraria: System.Security.AccessControl.ObjectSecurity.GetSecurityDescriptorBinaryForm
GetSecurityDescriptorBinaryForm()
byte[] System.Security.AccessControl.ObjectSecurity< T >.GetSecurityDescriptorBinaryForm () inline
Definition at line 476 of file ObjectSecurity.cs.
    {
        ReadLock();
        try
        {
            byte[] array = new byte[_securityDescriptor.BinaryLength];
            _securityDescriptor.GetBinaryForm(array, 0);
            return array;
        }
        finally
        {
            ReadUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.array, System.Security.AccessControl.GenericSecurityDescriptor.BinaryLength, System.Security.AccessControl.GenericSecurityDescriptor.GetBinaryForm(), System.Security.AccessControl.ObjectSecurity< T >.ReadLock(), and System.Security.AccessControl.ObjectSecurity< T >.ReadUnlock().
Referenced by System.IO.FileSystemAclExtensions.Create(), System.IO.FileSystemAclExtensions.CreateFileHandle(), and System.IO.Pipes.PipeStream.GetSecAttrs().