Terraria: System.Security.AccessControl.ObjectSecurity.UpdateWithNewSecurityDescriptor
UpdateWithNewSecurityDescriptor()
void System.Security.AccessControl.ObjectSecurity< T >.UpdateWithNewSecurityDescriptor (RawSecurityDescriptor newOne, AccessControlSections includeSections) inline private
Definition at line 198 of file ObjectSecurity.cs.
    {
        if ((includeSections & AccessControlSections.Owner) != 0)
        {
            _ownerModified = true;
            _securityDescriptor.Owner = newOne.Owner;
        }
        if ((includeSections & AccessControlSections.Group) != 0)
        {
            _groupModified = true;
            _securityDescriptor.Group = newOne.Group;
        }
        if ((includeSections & AccessControlSections.Audit) != 0)
        {
            _saclModified = true;
            if (newOne.SystemAcl != null)
            {
                _securityDescriptor.SystemAcl = new SystemAcl(IsContainer, IsDS, newOne.SystemAcl, trusted: true);
            }
            else
            {
                _securityDescriptor.SystemAcl = null;
            }
            _securityDescriptor.UpdateControlFlags(ControlFlags.SystemAclPresent | ControlFlags.SystemAclAutoInherited | ControlFlags.SystemAclProtected, newOne.ControlFlags & (ControlFlags.SystemAclPresent | ControlFlags.SystemAclAutoInherited | ControlFlags.SystemAclProtected));
        }
        if ((includeSections & AccessControlSections.Access) != 0)
        {
            _daclModified = true;
            if (newOne.DiscretionaryAcl != null)
            {
                _securityDescriptor.DiscretionaryAcl = new DiscretionaryAcl(IsContainer, IsDS, newOne.DiscretionaryAcl, trusted: true);
            }
            else
            {
                _securityDescriptor.DiscretionaryAcl = null;
            }
            ControlFlags controlFlags = _securityDescriptor.ControlFlags & ControlFlags.DiscretionaryAclPresent;
            _securityDescriptor.UpdateControlFlags(ControlFlags.DiscretionaryAclPresent | ControlFlags.DiscretionaryAclAutoInherited | ControlFlags.DiscretionaryAclProtected, (newOne.ControlFlags | controlFlags) & (ControlFlags.DiscretionaryAclPresent | ControlFlags.DiscretionaryAclAutoInherited | ControlFlags.DiscretionaryAclProtected));
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._daclModified, System.Security.AccessControl.ObjectSecurity< T >._groupModified, System.Security.AccessControl.ObjectSecurity< T >._ownerModified, System.Security.AccessControl.ObjectSecurity< T >._saclModified, System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.RawSecurityDescriptor.ControlFlags, System.Security.AccessControl.RawSecurityDescriptor.DiscretionaryAcl, System.Security.AccessControl.DiscretionaryAcl, System.Security.AccessControl.RawSecurityDescriptor.Group, System.Security.AccessControl.ObjectSecurity< T >.IsContainer, System.Security.AccessControl.ObjectSecurity< T >.IsDS, System.Security.AccessControl.RawSecurityDescriptor.Owner, System.Security.AccessControl.RawSecurityDescriptor.SystemAcl, System.Security.AccessControl.SystemAcl, and System.Security.AccessControl.CommonSecurityDescriptor.UpdateControlFlags().
Referenced by System.Security.AccessControl.ObjectSecurity< T >.SetSecurityDescriptorBinaryForm(), and System.Security.AccessControl.ObjectSecurity< T >.SetSecurityDescriptorSddlForm().