Terraria: System.Security.AccessControl.ObjectSecurity.SetAccessRuleProtection
SetAccessRuleProtection()
void System.Security.AccessControl.ObjectSecurity< T >.SetAccessRuleProtection (bool isProtected, bool preserveInheritance) inline
Definition at line 404 of file ObjectSecurity.cs.
    {
        WriteLock();
        try
        {
            _securityDescriptor.SetDiscretionaryAclProtection(isProtected, preserveInheritance);
            _daclModified = true;
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._daclModified, System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.CommonSecurityDescriptor.SetDiscretionaryAclProtection(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().
Referenced by System.IO.IsolatedStorage.Helper.CreateDirectory().