Terraria: System.Data.SqlTypes.SqlChars.Read
Read()
long System.Data.SqlTypes.SqlChars.Read (long offset, char[] buffer, int offsetInBuffer, int count) inline
Definition at line 182 of file SqlChars.cs.
    {
        if (IsNull)
        {
            throw new SqlNullValueException();
        }
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (offset > Length || offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (offsetInBuffer > buffer.Length || offsetInBuffer < 0)
        {
            throw new ArgumentOutOfRangeException("offsetInBuffer");
        }
        if (count < 0 || count > buffer.Length - offsetInBuffer)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (count > Length - offset)
        {
            count = (int)(Length - offset);
        }
        if (count != 0)
        {
            SqlBytesCharsState state = _state;
            if (state == SqlBytesCharsState.Stream)
            {
                if (_stream.Position != offset)
                {
                    _stream.Seek(offset, SeekOrigin.Begin);
                }
                _stream.Read(buffer, offsetInBuffer, count);
            }
            else
            {
                Array.Copy(_rgchBuf, offset, buffer, offsetInBuffer, count);
            }
        }
        return count;
    }
References System.Data.SqlTypes.SqlChars._rgchBuf, System.Data.SqlTypes.SqlChars._state, System.Data.SqlTypes.SqlChars._stream, System.buffer, System.Array.Copy(), System.count, System.Runtime.Serialization.Dictionary, System.Data.SqlTypes.SqlChars.IsNull, System.Data.SqlTypes.SqlChars.Length, System.offset, System.Data.SqlTypes.SqlStreamChars.Position, System.Data.SqlTypes.SqlStreamChars.Read(), System.Data.SqlTypes.SqlStreamChars.Seek(), and System.state.
Referenced by System.Data.SqlTypes.SqlStreamChars.Read().