Terraria: System.Data.SqlTypes.SqlChars.Write
Write()
void System.Data.SqlTypes.SqlChars.Write (long offset, char[] buffer, int offsetInBuffer, int count) inline
Definition at line 227 of file SqlChars.cs.
    {
        if (FStream())
        {
            if (_stream.Position != offset)
            {
                _stream.Seek(offset, SeekOrigin.Begin);
            }
            _stream.Write(buffer, offsetInBuffer, count);
            return;
        }
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (_rgchBuf == null)
        {
            throw new SqlTypeException(System.SR.SqlMisc_NoBufferMessage);
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if (offset > _rgchBuf.Length)
        {
            throw new SqlTypeException(System.SR.SqlMisc_BufferInsufficientMessage);
        }
        if (offsetInBuffer < 0 || offsetInBuffer > buffer.Length)
        {
            throw new ArgumentOutOfRangeException("offsetInBuffer");
        }
        if (count < 0 || count > buffer.Length - offsetInBuffer)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (count > _rgchBuf.Length - offset)
        {
            throw new SqlTypeException(System.SR.SqlMisc_BufferInsufficientMessage);
        }
        if (IsNull)
        {
            if (offset != 0L)
            {
                throw new SqlTypeException(System.SR.SqlMisc_WriteNonZeroOffsetOnNullMessage);
            }
            _lCurLen = 0L;
            _state = SqlBytesCharsState.Buffer;
        }
        else if (offset > _lCurLen)
        {
            throw new SqlTypeException(System.SR.SqlMisc_WriteOffsetLargerThanLenMessage);
        }
        if (count != 0)
        {
            Array.Copy(buffer, offsetInBuffer, _rgchBuf, offset, count);
            if (_lCurLen < offset + count)
            {
                _lCurLen = offset + count;
            }
        }
    }
References System.Data.SqlTypes.SqlChars._lCurLen, System.Data.SqlTypes.SqlChars._rgchBuf, System.Data.SqlTypes.SqlChars._state, System.Data.SqlTypes.SqlChars._stream, System.buffer, System.Array.Copy(), System.count, System.Runtime.Serialization.Dictionary, System.Data.SqlTypes.SqlChars.FStream(), System.Data.SqlTypes.SqlChars.IsNull, System.L, System.offset, System.Data.SqlTypes.SqlStreamChars.Position, System.Data.SqlTypes.SqlStreamChars.Seek(), System.SR.SqlMisc_BufferInsufficientMessage, System.SR.SqlMisc_NoBufferMessage, System.SR.SqlMisc_WriteNonZeroOffsetOnNullMessage, System.SR.SqlMisc_WriteOffsetLargerThanLenMessage, and System.Data.SqlTypes.SqlStreamChars.Write().
Referenced by System.Data.SqlTypes.SqlStreamChars.Write().