Terraria: UIVirtualKeyboard.SetKeyState
SetKeyState()
void UIVirtualKeyboard.SetKeyState (KeyState keyState) inline
     {
         UITextPanel<object> uITextPanel = null;
         switch (_keyState)
         {
         case KeyState.Shift:
             uITextPanel = _shiftButton;
             break;
         case KeyState.Symbol:
             uITextPanel = _symbolButton;
             break;
         }
         if (uITextPanel != null)
         {
             if (uITextPanel.IsMouseHovering)
             {
                 uITextPanel.BackgroundColor = new Color(73, 94, 171);
             }
             else
             {
                 uITextPanel.BackgroundColor = new Color(63, 82, 151) * 0.7f;
             }
         }
         string text = null;
         UITextPanel<object> uITextPanel2 = null;
         switch (keyState)
         {
         case KeyState.Default:
             text = "1234567890qwertyuiopasdfghjkl'zxcvbnm,.?";
             break;
         case KeyState.Shift:
             text = "1234567890QWERTYUIOPASDFGHJKL'ZXCVBNM,.?";
             uITextPanel2 = _shiftButton;
             break;
         case KeyState.Symbol:
             text = "1234567890!@#$%^&*()-_+=/\\{}[]<>;:\"`|~£¥";
             uITextPanel2 = _symbolButton;
             break;
         }
         for (int i = 0; i < text.Length; i++)
         {
             _keyList[i].SetText(text[i].ToString());
         }
         _keyState = keyState;
         if (uITextPanel2 != null)
         {
             uITextPanel2.BackgroundColor = new Color(93, 114, 191);
         }
     }
References _keyList, _keyState, _shiftButton, _symbolButton, Color, and UITextPanel< T >.SetText().
Referenced by UIVirtualKeyboard(), CycleSymbols(), TypeText(), and Write().