Terraria: UIVirtualKeyboard.Write
Write()
static void UIVirtualKeyboard.Write (string text) inline static
     {
         if (_currentInstance != null)
         {
             SoundEngine.PlaySound(12);
             bool num = _currentInstance.Text.Length == 0;
             _currentInstance._textBox.Write(text);
             _currentInstance.ValidateText();
             if (num && _currentInstance.Text.Length > 0 && _currentInstance._keyState == KeyState.Shift)
             {
                 _currentInstance.SetKeyState(KeyState.Default);
             }
         }
     }
References _currentInstance, _keyState, _textBox, SoundEngine.PlaySound(), SetKeyState(), Text, ValidateText(), and UITextBox.Write().
Referenced by UILinksInitializer.FancyUISpecialInstructions().