Terraria: UIVirtualKeyboard.Submit
Submit()
static void UIVirtualKeyboard.Submit () inline static
     {
         if (_currentInstance != null)
         {
             _currentInstance.InternalSubmit();
         }
     }
References _currentInstance, and InternalSubmit().
Referenced by UIVirtualKeyboard(), DrawSelf(), and UILinksInitializer.FancyUISpecialInstructions().