Terraria: UIVirtualKeyboard.Cancel
Cancel()
static void UIVirtualKeyboard.Cancel () inline static
     {
         if (_currentInstance != null)
         {
             SoundEngine.PlaySound(11);
             _currentInstance._cancelAction();
         }
     }
References _cancelAction, _currentInstance, and SoundEngine.PlaySound().
Referenced by UILinksInitializer.FancyExit(), and TryEscapingMenu().