Terraria: System.Runtime.Serialization.ReflectionReader.ReflectionReadCollection
ReflectionReadCollection()
object System.Runtime.Serialization.ReflectionReader.ReflectionReadCollection (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, XmlDictionaryString collectionItemName, XmlDictionaryString collectionItemNamespace, CollectionDataContract collectionContract) inline inherited
Definition at line 77 of file ReflectionReader.cs.
    {
        return ReflectionReadCollectionCore(xmlReader, context, collectionItemName, collectionItemNamespace, collectionContract);
    }
References System.Runtime.Serialization.ReflectionReader.ReflectionReadCollectionCore().
Referenced by System.Runtime.Serialization.ReflectionXmlCollectionReader.ReflectionReadCollection(), and System.Runtime.Serialization.Json.ReflectionJsonCollectionReader.ReflectionReadCollection().