Terraria: System.Runtime.Serialization.ReflectionReader.ReflectionReadCollectionCore
ReflectionReadCollectionCore()
object System.Runtime.Serialization.ReflectionReader.ReflectionReadCollectionCore (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, XmlDictionaryString collectionItemName, XmlDictionaryString collectionItemNamespace, CollectionDataContract collectionContract) inline private inherited
Definition at line 83 of file ReflectionReader.cs.
    {
        bool flag = collectionContract.Kind == CollectionKind.Array;
        int arraySize = context.GetArraySize();
        object resultArray = null;
        if (flag && ReflectionTryReadPrimitiveArray(xmlReader, context, collectionItemName, collectionItemNamespace, collectionContract.UnderlyingType, collectionContract.ItemType, arraySize, out resultArray))
        {
            return resultArray;
        }
        object obj = ReflectionCreateCollection(collectionContract);
        context.AddNewObject(obj);
        context.IncrementItemCount(1);
        if (!ReflectionReadSpecialCollection(xmlReader, context, collectionContract, obj))
        {
            bool isReadOnlyCollection = false;
            obj = ReadCollectionItems(xmlReader, context, collectionItemName, collectionItemNamespace, collectionContract, obj, isReadOnlyCollection);
        }
        return obj;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObject(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlObjectSerializerReadContext.GetArraySize(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.obj, System.Runtime.Serialization.ReflectionReader.ReadCollectionItems(), System.Runtime.Serialization.ReflectionReader.ReflectionCreateCollection(), System.Runtime.Serialization.ReflectionReader.ReflectionReadSpecialCollection(), and System.Runtime.Serialization.ReflectionReader.ReflectionTryReadPrimitiveArray().
Referenced by System.Runtime.Serialization.ReflectionReader.ReflectionReadCollection().