Terraria: System.Runtime.Serialization.ReflectionReader.ReadCollectionItems
ReadCollectionItems()
object System.Runtime.Serialization.ReflectionReader.ReadCollectionItems (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, XmlDictionaryString collectionItemName, XmlDictionaryString collectionItemNamespace, CollectionDataContract collectionContract, object resultCollection, bool isReadOnlyCollection) inline private inherited
Definition at line 119 of file ReflectionReader.cs.
    {
        string collectionContractItemName = GetCollectionContractItemName(collectionContract);
        string collectionContractNamespace = GetCollectionContractNamespace(collectionContract);
        Type itemType = collectionContract.ItemType;
        CollectionReadItemDelegate collectionReadItemDelegate = GetCollectionReadItemDelegate(collectionContract);
        MethodInfo methodInfo = CollectionSetItemDelegateMethod.MakeGenericMethod(itemType);
        CollectionSetItemDelegate collectionSetItemDelegate = (CollectionSetItemDelegate)methodInfo.Invoke(this, new object[3] { collectionContract, resultCollection, isReadOnlyCollection });
        int num = 0;
        while (true)
        {
            if (xmlReader.IsStartElement(collectionItemName, collectionItemNamespace))
            {
                object collectionItem = collectionReadItemDelegate(xmlReader, context, collectionContract, itemType, collectionContractItemName, collectionContractNamespace);
                resultCollection = collectionSetItemDelegate(resultCollection, collectionItem, num);
                num++;
                continue;
            }
            if (xmlReader.NodeType == XmlNodeType.EndElement)
            {
                break;
            }
            if (!xmlReader.IsStartElement())
            {
                throw XmlObjectSerializerReadContext.CreateUnexpectedStateException(XmlNodeType.Element, xmlReader);
            }
            context.SkipUnknownElement(xmlReader);
        }
        context.IncrementItemCount(num);
        if (!isReadOnlyCollection && IsArrayLikeCollection(collectionContract))
        {
            MethodInfo methodInfo2 = XmlFormatGeneratorStatics.TrimArraySizeMethod.MakeGenericMethod(itemType);
            resultCollection = methodInfo2.Invoke(null, new object[2] { resultCollection, num });
        }
        return resultCollection;
    }
References System.Runtime.Serialization.ReflectionReader.CollectionReadItemDelegate(), System.Runtime.Serialization.ReflectionReader.CollectionSetItemDelegate(), System.Runtime.Serialization.ReflectionReader.CollectionSetItemDelegateMethod, System.Runtime.Serialization.ReflectionReader.GetCollectionContractItemName(), System.Runtime.Serialization.ReflectionReader.GetCollectionContractNamespace(), and System.Runtime.Serialization.ReflectionReader.GetCollectionReadItemDelegate().
Referenced by System.Runtime.Serialization.ReflectionReader.ReflectionReadCollectionCore(), and System.Runtime.Serialization.ReflectionReader.ReflectionReadGetOnlyCollection().