Terraria: System.Runtime.Serialization.ReflectionReader.ReflectionReadMember
ReflectionReadMember()
void System.Runtime.Serialization.ReflectionReader.ReflectionReadMember (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, ClassDataContract classContract, ref object obj, int memberIndex, DataMember[] members) inline protected inherited
Definition at line 189 of file ReflectionReader.cs.
    {
        DataMember dataMember = members[memberIndex];
        if (dataMember.IsGetOnlyCollection)
        {
            object collectionMember = ReflectionGetMemberValue(obj, dataMember);
            context.StoreCollectionMemberInfo(collectionMember);
            ReflectionReadValue(xmlReader, context, dataMember, GetClassContractNamespace(classContract));
        }
        else
        {
            context.ResetCollectionMemberInfo();
            object memberValue = ReflectionReadValue(xmlReader, context, dataMember, classContract.StableName.Namespace);
            MemberInfo memberInfo = dataMember.MemberInfo;
            ReflectionSetMemberValue(ref obj, memberValue, dataMember);
        }
    }
References System.Runtime.Serialization.Dictionary, System.obj, System.Runtime.Serialization.XmlObjectSerializerReadContext.ResetCollectionMemberInfo(), and System.Runtime.Serialization.XmlObjectSerializerReadContext.StoreCollectionMemberInfo().
Referenced by System.Runtime.Serialization.Json.ReflectionJsonReader.ReflectionReadMembers(), and System.Runtime.Serialization.ReflectionXmlReader.ReflectionReadMembers().