Terraria: System.Runtime.Serialization.ReflectionReader.GetCollectionSetItemDelegate< T >
GetCollectionSetItemDelegate< T >()
CollectionSetItemDelegate System.Runtime.Serialization.ReflectionReader.GetCollectionSetItemDelegate< T > (CollectionDataContract collectionContract, object resultCollectionObject, bool isReadOnlyCollection) inline private inherited
Definition at line 435 of file ReflectionReader.cs.
    {
        if (isReadOnlyCollection && collectionContract.Kind == CollectionKind.Array)
        {
            int arraySize = ((Array)resultCollectionObject).Length;
            return delegate(object resultCollection, object collectionItem, int index)
            {
                if (index == arraySize)
                {
                    XmlObjectSerializerReadContext.ThrowArrayExceededSizeException(arraySize, collectionContract.UnderlyingType);
                }
                ((T[])resultCollection)[index] = (T)collectionItem;
                return resultCollection;
            };
        }
        if (!isReadOnlyCollection && IsArrayLikeCollection(collectionContract))
        {
            return delegate(object resultCollection, object collectionItem, int index)
            {
                resultCollection = XmlObjectSerializerReadContext.EnsureArraySize((T[])resultCollection, index);
                ((T[])resultCollection)[index] = (T)collectionItem;
                return resultCollection;
            };
        }
        if (collectionContract.Kind == CollectionKind.GenericDictionary || collectionContract.Kind == CollectionKind.Dictionary)
        {
            Type keyType2 = collectionContract.ItemType.GenericTypeArguments[0];
            Type valueType2 = collectionContract.ItemType.GenericTypeArguments[1];
            Func<object, object> objectToKeyValuePairGetKey = MakeGenericMethod(s_objectToKeyValuePairGetKey, keyType2, valueType2).CreateDelegate<Func<object, object>>();
            Func<object, object> objectToKeyValuePairGetValue = MakeGenericMethod(s_objectToKeyValuePairGetValue, keyType2, valueType2).CreateDelegate<Func<object, object>>();
            if (collectionContract.Kind == CollectionKind.GenericDictionary)
            {
                return delegate(object resultCollection, object collectionItem, int index)
                {
                    object obj = objectToKeyValuePairGetKey(collectionItem);
                    object obj2 = objectToKeyValuePairGetValue(collectionItem);
                    collectionContract.AddMethod.Invoke(resultCollection, new object[2] { obj, obj2 });
                    return resultCollection;
                };
            }
            return delegate(object resultCollection, object collectionItem, int index)
            {
                object key = objectToKeyValuePairGetKey(collectionItem);
                object value = objectToKeyValuePairGetValue(collectionItem);
                IDictionary dictionary = (IDictionary)resultCollection;
                dictionary.Add(key, value);
                return resultCollection;
            };
        }
        Type type = resultCollectionObject.GetType();
        Type typeFromHandle = typeof(ICollection<T>);
        Type typeOfIList = Globals.TypeOfIList;
        if (typeFromHandle.IsAssignableFrom(type))
        {
            return delegate(object resultCollection, object collectionItem, int index)
            {
                ((ICollection<T>)resultCollection).Add((T)collectionItem);
                return resultCollection;
            };
        }
        if (typeOfIList.IsAssignableFrom(type))
        {
            return delegate(object resultCollection, object collectionItem, int index)
            {
                ((IList)resultCollection).Add(collectionItem);
                return resultCollection;
            };
        }
        MethodInfo addMethod = collectionContract.AddMethod;
        if (addMethod == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.CollectionMustHaveAddMethod, DataContract.GetClrTypeFullName(collectionContract.UnderlyingType))));
        }
        return delegate(object resultCollection, object collectionItem, int index)
        {
            addMethod.Invoke(resultCollection, new object[1] { collectionItem });
            return resultCollection;
        };
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2060:MakeGenericMethod", Justification = "The call to MakeGenericMethod is safe due to the fact that ObjectToKeyValuePairGetKey and ObjectToKeyValuePairGetValue are not annotated.")]
        static MethodInfo MakeGenericMethod(MethodInfo method, Type keyType, Type valueType)
        {
            return method.MakeGenericMethod(keyType, valueType);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Dictionary(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Array, System.SR.CollectionMustHaveAddMethod, System.dictionary, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.index, System.key, System.obj, System.T, System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowArrayExceededSizeException(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.type, System.Runtime.Serialization.Globals.TypeOfIList, and System.value.