Terraria: System.Runtime.Serialization.ReflectionReader.ReadItemOfPrimitiveType
ReadItemOfPrimitiveType()
object System.Runtime.Serialization.ReflectionReader.ReadItemOfPrimitiveType (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, Type type, string name, string ns, PrimitiveDataContract primitiveContract, int nullables) inline private inherited
Definition at line 226 of file ReflectionReader.cs.
    {
        context.ReadAttributes(xmlReader);
        string text = context.ReadIfNullOrRef(xmlReader, type, DataContract.IsTypeSerializable(type));
        bool isValueType = type.IsValueType;
        if (text != null)
        {
            if (text.Length == 0)
            {
                text = context.GetObjectId();
                if (!string.IsNullOrEmpty(text) && isValueType)
                {
                    throw new SerializationException(System.SR.Format(System.SR.ValueTypeCannotHaveId, DataContract.GetClrTypeFullName(type)));
                }
                if (primitiveContract != null && primitiveContract.UnderlyingType != Globals.TypeOfObject)
                {
                    return primitiveContract.ReadXmlValue(xmlReader, context);
                }
                return ReflectionInternalDeserialize(xmlReader, context, null, type, name, ns);
            }
            if (isValueType)
            {
                throw new SerializationException(System.SR.Format(System.SR.ValueTypeCannotHaveRef, DataContract.GetClrTypeFullName(type)));
            }
            return context.GetExistingObject(text, type, name, ns);
        }
        if (isValueType && nullables == 0)
        {
            throw new SerializationException(System.SR.Format(System.SR.ValueTypeCannotBeNull, DataContract.GetClrTypeFullName(type)));
        }
        return null;
    }
References System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObject(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetObjectId(), System.Runtime.Serialization.DataContract.IsTypeSerializable(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAttributes(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadIfNullOrRef(), System.text, System.type, System.Runtime.Serialization.Globals.TypeOfObject, System.SR.ValueTypeCannotBeNull, System.SR.ValueTypeCannotHaveId, and System.SR.ValueTypeCannotHaveRef.