Terraria: System.Runtime.Serialization.ReflectionReader.ReflectionReadClass
ReflectionReadClass()
object System.Runtime.Serialization.ReflectionReader.ReflectionReadClass (XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context, XmlDictionaryString[] memberNames, XmlDictionaryString[] memberNamespaces, ClassDataContract classContract) inline inherited
Definition at line 38 of file ReflectionReader.cs.
    {
        object obj = CreateObject(classContract);
        context.AddNewObject(obj);
        InvokeOnDeserializing(context, classContract, obj);
        if (classContract.IsISerializable)
        {
            obj = ReadISerializable(xmlReader, context, classContract);
        }
        else
        {
            ReflectionReadMembers(xmlReader, context, memberNames, memberNamespaces, classContract, ref obj);
        }
        if (obj is IObjectReference obj2)
        {
            obj = context.GetRealObject(obj2, context.GetObjectId());
        }
        obj = ResolveAdapterObject(obj, classContract);
        InvokeDeserializationCallback(obj);
        InvokeOnDeserialized(context, classContract, obj);
        return obj;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObject(), System.Runtime.Serialization.ReflectionReader.CreateObject(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetObjectId(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetRealObject(), System.Runtime.Serialization.ReflectionReader.InvokeDeserializationCallback(), System.Runtime.Serialization.ReflectionReader.InvokeOnDeserialized(), System.Runtime.Serialization.ReflectionReader.InvokeOnDeserializing(), System.obj, System.Runtime.Serialization.ReflectionReader.ReadISerializable(), System.Runtime.Serialization.ReflectionReader.ReflectionReadMembers(), and System.Runtime.Serialization.ReflectionReader.ResolveAdapterObject().
Referenced by System.Runtime.Serialization.ReflectionXmlClassReader.ReflectionReadClass(), and System.Runtime.Serialization.Json.ReflectionJsonClassReader.ReflectionReadClass().