Terraria: System.Text.Rune.ToUpperInvariant
ToUpperInvariant()
static Rune System.Text.Rune.ToUpperInvariant (Rune value) inline static
Definition at line 836 of file Rune.cs.
    {
        if (value.IsAscii)
        {
            return UnsafeCreate(Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(value._value));
        }
        if (GlobalizationMode.Invariant)
        {
            return UnsafeCreate(CharUnicodeInfo.ToUpper(value._value));
        }
        return ChangeCaseCultureAware(value, TextInfo.Invariant, toUpper: true);
    }
References System.Text.Rune.ChangeCaseCultureAware(), System.Text.Unicode.Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.TextInfo.Invariant, System.Globalization.CharUnicodeInfo.ToUpper(), System.Text.Rune.UnsafeCreate(), and System.value.
Referenced by System.Text.Rune.ToUpper().