Terraria: System.Text.Rune.GetRuneAt
GetRuneAt()
static Rune System.Text.Rune.GetRuneAt (string input, int index) inline static
Definition at line 411 of file Rune.cs.
    {
        int num = ReadRuneFromString(input, index);
        if (num < 0)
        {
            ThrowHelper.ThrowArgumentException_CannotExtractScalar(ExceptionArgument.index);
        }
        return UnsafeCreate((uint)num);
    }
References System.index, System.input, System.Text.Rune.ReadRuneFromString(), System.ThrowHelper.ThrowArgumentException_CannotExtractScalar(), and System.Text.Rune.UnsafeCreate().