Terraria: System.Text.Rune.ToLower
ToLower()
static Rune System.Text.Rune.ToLower (Rune value, CultureInfo culture) inline static
Definition at line 797 of file Rune.cs.
    {
        if (culture == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.culture);
        }
        if (GlobalizationMode.Invariant)
        {
            return ToLowerInvariant(value);
        }
        return ChangeCaseCultureAware(value, culture.TextInfo, toUpper: false);
    }
References System.Text.Rune.ChangeCaseCultureAware(), System.culture, System.Globalization.GlobalizationMode.Invariant, System.ThrowHelper.ThrowArgumentNullException(), System.Text.Rune.ToLowerInvariant(), and System.value.