Terraria: System.Text.Rune.ReadRuneFromString
ReadRuneFromString()
static int System.Text.Rune.ReadRuneFromString (string input, int index) inline static private
Definition at line 459 of file Rune.cs.
    {
        if (input == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.input);
        }
        if ((uint)index >= (uint)input.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRange_IndexException();
        }
        uint num = input[index];
        if (UnicodeUtility.IsSurrogateCodePoint(num))
        {
            if (!UnicodeUtility.IsHighSurrogateCodePoint(num))
            {
                return -1;
            }
            index++;
            if ((uint)index >= (uint)input.Length)
            {
                return -1;
            }
            uint num2 = input[index];
            if (!UnicodeUtility.IsLowSurrogateCodePoint(num2))
            {
                return -1;
            }
            num = UnicodeUtility.GetScalarFromUtf16SurrogatePair(num, num2);
        }
        return (int)num;
    }
References System.Text.UnicodeUtility.GetScalarFromUtf16SurrogatePair(), System.index, System.input, System.Text.UnicodeUtility.IsHighSurrogateCodePoint(), System.Text.UnicodeUtility.IsLowSurrogateCodePoint(), System.Text.UnicodeUtility.IsSurrogateCodePoint(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRange_IndexException().
Referenced by System.Text.Rune.GetRuneAt(), and System.Text.Rune.TryGetRuneAt().