Terraria: System.Text.Rune.TryEncodeToUtf16
TryEncodeToUtf16() [2/2]
bool System.Text.Rune.TryEncodeToUtf16 (Span< char > destination, out int charsWritten) inline
Definition at line 553 of file Rune.cs.
    {
        return TryEncodeToUtf16(this, destination, out charsWritten);
    }
References System.destination, and System.Text.Rune.TryEncodeToUtf16().
Referenced by System.Text.Encodings.Web.OptimizedInboxTextEncoder.Encode(), System.Text.Encodings.Web.TextEncoder.EncodeCore(), System.Text.Rune.EncodeToUtf16(), System.Text.DecoderFallbackBuffer.TryDrainRemainingDataForGetChars(), System.Text.Rune.TryEncodeToUtf16(), and System.Text.Rune.TryFormat().