Terraria: System.Text.Rune.ChangeCaseCultureAware
ChangeCaseCultureAware()
static Rune System.Text.Rune.ChangeCaseCultureAware (Rune rune, TextInfo textInfo, bool toUpper) inline static private
Definition at line 141 of file Rune.cs.
    {
        Span<char> span = stackalloc char[2];
        Span<char> destination = stackalloc char[2];
        int length = rune.EncodeToUtf16(span);
        span = span.Slice(0, length);
        destination = destination.Slice(0, length);
        if (toUpper)
        {
            textInfo.ChangeCaseToUpper(span, destination);
        }
        else
        {
            textInfo.ChangeCaseToLower(span, destination);
        }
        if (rune.IsBmp)
        {
            return UnsafeCreate(destination[0]);
        }
        return UnsafeCreate(UnicodeUtility.GetScalarFromUtf16SurrogatePair(destination[0], destination[1]));
    }
References System.Globalization.TextInfo.ChangeCaseToLower(), System.Globalization.TextInfo.ChangeCaseToUpper(), System.destination, System.Text.Rune.EncodeToUtf16(), System.Text.UnicodeUtility.GetScalarFromUtf16SurrogatePair(), System.Text.Rune.IsBmp, System.length, System.Span< T >.Slice(), and System.Text.Rune.UnsafeCreate().
Referenced by System.Text.Rune.ToLower(), System.Text.Rune.ToLowerInvariant(), System.Text.Rune.ToUpper(), and System.Text.Rune.ToUpperInvariant().