Terraria: System.Text.Rune.DecodeLastFromUtf8
DecodeLastFromUtf8()
static OperationStatus System.Text.Rune.DecodeLastFromUtf8 (ReadOnlySpan< byte > source, out Rune value, out int bytesConsumed) inline static
Definition at line 321 of file Rune.cs.
    {
        int num = source.Length - 1;
        if ((uint)num < (uint)source.Length)
        {
            uint num2 = source[num];
            if (UnicodeUtility.IsAsciiCodePoint(num2))
            {
                bytesConsumed = 1;
                value = UnsafeCreate(num2);
                return OperationStatus.Done;
            }
            if (((byte)num2 & 0x40u) != 0)
            {
                return DecodeFromUtf8(source.Slice(num), out value, out bytesConsumed);
            }
            int num3 = 3;
            OperationStatus result2;
            Rune result;
            int bytesConsumed2;
            while (true)
            {
                if (num3 > 0)
                {
                    num--;
                    if ((uint)num < (uint)source.Length)
                    {
                        if ((sbyte)source[num] < -64)
{
                            num3--;
                            continue;
                        }
                        source = source.Slice(num);
                        result2 = DecodeFromUtf8(source, out result, out bytesConsumed2);
                        if (bytesConsumed2 == source.Length)
{
                            break;
                        }
                    }
                }
                value = ReplacementChar;
                bytesConsumed = 1;
                return OperationStatus.InvalidData;
            }
            bytesConsumed = bytesConsumed2;
            value = result;
            return result2;
        }
        value = ReplacementChar;
        bytesConsumed = 0;
        return OperationStatus.NeedMoreData;
    }
References System.Text.Rune.DecodeFromUtf8(), System.Text.UnicodeUtility.IsAsciiCodePoint(), System.Text.Rune.ReplacementChar, System.source, System.Text.Rune.UnsafeCreate(), and System.value.