Terraria: System.Text.Rune.UnsafeCreate
UnsafeCreate()
static Rune System.Text.Rune.UnsafeCreate (uint scalarValue) inline static package
Definition at line 643 of file Rune.cs.
    {
        return new Rune(scalarValue, unused: false);
    }
References System.Text.Rune.Rune().
Referenced by System.Text.Rune.ChangeCaseCultureAware(), System.Char.ConvertFromUtf32(), System.Text.Rune.DecodeFromUtf8(), System.Text.Rune.DecodeLastFromUtf8(), System.Text.Rune.GetRuneAt(), System.Text.SpanRuneEnumerator.MoveNext(), System.Text.Rune.ToLowerInvariant(), System.Text.Rune.ToUpperInvariant(), System.Text.Rune.TryCreate(), System.Text.Rune.TryCreate(), System.Text.Rune.TryCreate(), and System.Text.Rune.TryGetRuneAt().