Terraria: System.Text.Rune.DecodeFromUtf8
DecodeFromUtf8()
static OperationStatus System.Text.Rune.DecodeFromUtf8 (ReadOnlySpan< byte > source, out Rune result, out int bytesConsumed) inline static
Definition at line 202 of file Rune.cs.
    {
        int num = 0;
        uint num2;
        if ((uint)num < (uint)source.Length)
        {
            num2 = source[num];
            if (UnicodeUtility.IsAsciiCodePoint(num2))
            {
                goto IL_0021;
            }
            if (UnicodeUtility.IsInRangeInclusive(num2, 194u, 244u))
            {
                num2 = num2 - 194 << 6;
                num++;
                if ((uint)num >= (uint)source.Length)
                {
                    goto IL_0163;
                }
                int num3 = (sbyte)source[num];
                if (num3 < -64)
                {
                    num2 += (uint)num3;
                    num2 += 128;
                    num2 += 128;
                    if (num2 < 2048)
                    {
                        goto IL_0021;
                    }
                    if (UnicodeUtility.IsInRangeInclusive(num2, 2080u, 3343u) && !UnicodeUtility.IsInRangeInclusive(num2, 2912u, 2943u) && !UnicodeUtility.IsInRangeInclusive(num2, 3072u, 3087u))
                    {
                        num++;
                        if ((uint)num >= (uint)source.Length)
{
                            goto IL_0163;
                        }
                        num3 = (sbyte)source[num];
                        if (num3 < -64)
{
                            num2 <<= 6;
                            num2 += (uint)num3;
                            num2 += 128;
                            num2 -= 131072;
                            if (num2 > 65535)
{
                                num++;
                                if ((uint)num >= (uint)source.Length)
{
                                    goto IL_0163;
                                }
                                num3 = (sbyte)source[num];
                                if (num3 >= -64)
{
                                    goto IL_0153;
                                }
                                num2 <<= 6;
                                num2 += (uint)num3;
                                num2 += 128;
                                num2 -= 4194304;
                            }
                            goto IL_0021;
                        }
                    }
                }
            }
            else
            {
                num = 1;
            }
            goto IL_0153;
        }
        goto IL_0163;
        IL_0021:
        bytesConsumed = num + 1;
        result = UnsafeCreate(num2);
        return OperationStatus.Done;
        IL_0163:
        bytesConsumed = num;
        result = ReplacementChar;
        return OperationStatus.NeedMoreData;
        IL_0153:
        bytesConsumed = num;
        result = ReplacementChar;
        return OperationStatus.InvalidData;
    }
References System.Text.UnicodeUtility.IsAsciiCodePoint(), System.Text.UnicodeUtility.IsInRangeInclusive(), System.Text.Rune.ReplacementChar, System.source, and System.Text.Rune.UnsafeCreate().
Referenced by System.Text.UTF8Encoding.DecodeFirstRune(), System.Text.Rune.DecodeLastFromUtf8(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.EncodeUtf8(), System.Text.Encodings.Web.TextEncoder.EncodeUtf8Core(), System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode(), System.Text.Unicode.Utf8.ToUtf16(), and System.PercentEncodingHelper.UnescapePercentEncodedUTF8Sequence().