Terraria: System.Text.Rune.DecodeFromUtf16
DecodeFromUtf16()
static OperationStatus System.Text.Rune.DecodeFromUtf16 (ReadOnlySpan< char > source, out Rune result, out int charsConsumed) inline static
Definition at line 168 of file Rune.cs.
    {
        if (!source.IsEmpty)
        {
            char c = source[0];
            if (TryCreate(c, out result))
            {
                charsConsumed = 1;
                return OperationStatus.Done;
            }
            if (source.Length > 1)
            {
                char lowSurrogate = source[1];
                if (TryCreate(c, lowSurrogate, out result))
                {
                    charsConsumed = 2;
                    return OperationStatus.Done;
                }
            }
            else if (char.IsHighSurrogate(c))
            {
                goto IL_004c;
            }
            charsConsumed = 1;
            result = ReplacementChar;
            return OperationStatus.InvalidData;
        }
        goto IL_004c;
        IL_004c:
        charsConsumed = source.Length;
        result = ReplacementChar;
        return OperationStatus.NeedMoreData;
    }
References System.Text.Rune.ReplacementChar, System.source, and System.Text.Rune.TryCreate().
Referenced by System.Text.Encodings.Web.TextEncoder.EncodeCore(), System.Text.Encoding.GetByteCountWithFallback(), System.Text.Encoding.GetBytesWithFallback(), System.Globalization.CompareInfo.IcuIsSortable(), and System.Text.Encodings.Web.TextEncoder.TryEncodeUnicodeScalarUtf8().