Terraria: Terraria.Utilities.FastRandom.NextFloat
NextFloat()
float Terraria.Utilities.FastRandom.NextFloat () inline
Definition at line 53 of file FastRandom.cs.
    {
        return (float)NextBits(24) * 5.9604645E-08f;
    }
References Terraria.Utilities.FastRandom.NextBits().
Referenced by Terraria.GameContent.Skies.AmbientSky.AirBalloonSkyEntity.AirBalloonSkyEntity(), Terraria.GameContent.Skies.AmbientSky.AirshipSkyEntity.AirshipSkyEntity(), Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.BatsGroupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.BirdsPackSkyEntity.BirdsPackSkyEntity(), Terraria.GameContent.Skies.AmbientSky.ButterfliesSkyEntity.ButterfliesSkyEntity(), Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.EOCSkyEntity(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.GastropodGroupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.HellBatsGoupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.LostKiteSkyEntity.LostKiteSkyEntity(), Terraria.GameContent.Skies.AmbientSky.MeteorSkyEntity.MeteorSkyEntity(), Terraria.GameContent.Skies.AmbientSky.PegasusSkyEntity.PegasusSkyEntity(), Terraria.GameContent.Skies.AmbientSky.PixiePosseSkyEntity.PixiePosseSkyEntity(), Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.SeagullsGroupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.SlimeBalloonGroupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.VultureSkyEntity.VultureSkyEntity(), Terraria.GameContent.Skies.AmbientSky.WyvernSkyEntity.WyvernSkyEntity(), Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.CreateGroup(), and Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.CreateGroup().