Terraria: TileObject.Place
Place()
static bool TileObject.Place (TileObject toBePlaced) inline static
     {
         TileObjectData tileData = TileObjectData.GetTileData(toBePlaced.type, toBePlaced.style, toBePlaced.alternate);
         if (tileData == null)
         {
             return false;
         }
         if (tileData.HookPlaceOverride.hook != null)
         {
             int arg;
             int arg2;
             if (tileData.HookPlaceOverride.processedCoordinates)
             {
                 arg = toBePlaced.xCoord;
                 arg2 = toBePlaced.yCoord;
             }
             else
             {
                 arg = toBePlaced.xCoord + tileData.Origin.X;
                 arg2 = toBePlaced.yCoord + tileData.Origin.Y;
             }
             if (tileData.HookPlaceOverride.hook(arg, arg2, toBePlaced.type, toBePlaced.style, 1, toBePlaced.alternate) == tileData.HookPlaceOverride.badReturn)
             {
                 return false;
             }
         }
         else
         {
             ushort num = (ushort)toBePlaced.type;
             int num2 = 0;
             int num3 = 0;
             int num4 = tileData.CalculatePlacementStyle(toBePlaced.style, toBePlaced.alternate, toBePlaced.random);
             int num5 = 0;
             if (tileData.StyleWrapLimit > 0)
             {
                 num5 = num4 / tileData.StyleWrapLimit * tileData.StyleLineSkip;
                 num4 %= tileData.StyleWrapLimit;
             }
             if (tileData.StyleHorizontal)
             {
                 num2 = tileData.CoordinateFullWidth * num4;
                 num3 = tileData.CoordinateFullHeight * num5;
             }
             else
             {
                 num2 = tileData.CoordinateFullWidth * num5;
                 num3 = tileData.CoordinateFullHeight * num4;
             }
             int num6 = toBePlaced.xCoord;
             int num7 = toBePlaced.yCoord;
             for (int i = 0; i < tileData.Width; i++)
             {
                 for (int j = 0; j < tileData.Height; j++)
                 {
                     Tile tileSafely = Framing.GetTileSafely(num6 + i, num7 + j);
                     if (tileSafely.active() && tileSafely.type != 484 && (Main.tileCut[tileSafely.type] || TileID.Sets.BreakableWhenPlacing[tileSafely.type]))
                     {
                         WorldGen.KillTile(num6 + i, num7 + j);
                         if (!Main.tile[num6 + i, num7 + j].active() && Main.netMode != 0)
{
                             NetMessage.SendData(17, -1, -1, null, 0, num6 + i, num7 + j);
                         }
                     }
                 }
             }
             for (int k = 0; k < tileData.Width; k++)
             {
                 int num8 = num2 + k * (tileData.CoordinateWidth + tileData.CoordinatePadding);
                 int num9 = num3;
                 for (int l = 0; l < tileData.Height; l++)
                 {
                     Tile tileSafely2 = Framing.GetTileSafely(num6 + k, num7 + l);
                     if (!tileSafely2.active())
                     {
                         tileSafely2.active(active: true);
                         tileSafely2.frameX = (short)num8;
                         tileSafely2.frameY = (short)num9;
                         tileSafely2.type = num;
                     }
                     num9 += tileData.CoordinateHeights[l] + tileData.CoordinatePadding;
                 }
             }
         }
         if (tileData.FlattenAnchors)
         {
             AnchorData anchorBottom = tileData.AnchorBottom;
             if (anchorBottom.tileCount != 0 && (anchorBottom.type & AnchorType.SolidTile) == AnchorType.SolidTile)
             {
                 int num10 = toBePlaced.xCoord + anchorBottom.checkStart;
                 int j2 = toBePlaced.yCoord + tileData.Height;
                 for (int m = 0; m < anchorBottom.tileCount; m++)
                 {
                     Tile tileSafely3 = Framing.GetTileSafely(num10 + m, j2);
                     if (Main.tileSolid[tileSafely3.type] && !Main.tileSolidTop[tileSafely3.type] && tileSafely3.blockType() != 0)
                     {
                         WorldGen.SlopeTile(num10 + m, j2);
                     }
                 }
             }
             anchorBottom = tileData.AnchorTop;
             if (anchorBottom.tileCount != 0 && (anchorBottom.type & AnchorType.SolidTile) == AnchorType.SolidTile)
             {
                 int num11 = toBePlaced.xCoord + anchorBottom.checkStart;
                 int j3 = toBePlaced.yCoord - 1;
                 for (int n = 0; n < anchorBottom.tileCount; n++)
                 {
                     Tile tileSafely4 = Framing.GetTileSafely(num11 + n, j3);
                     if (Main.tileSolid[tileSafely4.type] && !Main.tileSolidTop[tileSafely4.type] && tileSafely4.blockType() != 0)
                     {
                         WorldGen.SlopeTile(num11 + n, j3);
                     }
                 }
             }
             anchorBottom = tileData.AnchorRight;
             if (anchorBottom.tileCount != 0 && (anchorBottom.type & AnchorType.SolidTile) == AnchorType.SolidTile)
             {
                 int i2 = toBePlaced.xCoord + tileData.Width;
                 int num12 = toBePlaced.yCoord + anchorBottom.checkStart;
                 for (int num13 = 0; num13 < anchorBottom.tileCount; num13++)
                 {
                     Tile tileSafely5 = Framing.GetTileSafely(i2, num12 + num13);
                     if (Main.tileSolid[tileSafely5.type] && !Main.tileSolidTop[tileSafely5.type] && tileSafely5.blockType() != 0)
                     {
                         WorldGen.SlopeTile(i2, num12 + num13);
                     }
                 }
             }
             anchorBottom = tileData.AnchorLeft;
             if (anchorBottom.tileCount != 0 && (anchorBottom.type & AnchorType.SolidTile) == AnchorType.SolidTile)
             {
                 int i3 = toBePlaced.xCoord - 1;
                 int num14 = toBePlaced.yCoord + anchorBottom.checkStart;
                 for (int num15 = 0; num15 < anchorBottom.tileCount; num15++)
                 {
                     Tile tileSafely6 = Framing.GetTileSafely(i3, num14 + num15);
                     if (Main.tileSolid[tileSafely6.type] && !Main.tileSolidTop[tileSafely6.type] && tileSafely6.blockType() != 0)
                     {
                         WorldGen.SlopeTile(i3, num14 + num15);
                     }
                 }
             }
         }
         return true;
     }
References Tile.active(), alternate, TileObjectData.AnchorBottom, TileObjectData.AnchorLeft, TileObjectData.AnchorRight, TileObjectData.AnchorTop, PlacementHook.badReturn, Tile.blockType(), TileID.Sets.BreakableWhenPlacing, TileObjectData.CalculatePlacementStyle(), AnchorData.checkStart, TileObjectData.CoordinateFullHeight, TileObjectData.CoordinateFullWidth, TileObjectData.CoordinateHeights, TileObjectData.CoordinatePadding, TileObjectData.CoordinateWidth, TileObjectData.FlattenAnchors, Tile.frameX, Tile.frameY, TileObjectData.GetTileData(), Framing.GetTileSafely(), TileObjectData.Height, PlacementHook.hook, TileObjectData.HookPlaceOverride, WorldGen.KillTile(), Main.netMode, TileObjectData.Origin, PlacementHook.processedCoordinates, random, NetMessage.SendData(), WorldGen.SlopeTile(), style, TileObjectData.StyleHorizontal, TileObjectData.StyleLineSkip, TileObjectData.StyleWrapLimit, Main.tile, AnchorData.tileCount, Main.tileCut, Main.tileSolid, Main.tileSolidTop, AnchorData.type, Tile.type, type, TileObjectData.Width, Point16.X, xCoord, Point16.Y, and yCoord.
Referenced by WorldGen.PlaceChest(), WorldGen.PlaceObject(), Player.PlaceThing_Tiles_PlaceIt(), and Player.TryReplantingTree().