Terraria: Mount.CastSuperCartLaser
CastSuperCartLaser()
void Mount.CastSuperCartLaser (Player mountedPlayer) inline private
     {
         int num = Math.Sign(mountedPlayer.velocity.X);
         if (num == 0)
         {
             num = mountedPlayer.direction;
         }
         if (mountedPlayer.whoAmI != Main.myPlayer || mountedPlayer.velocity.X == 0f)
         {
             return;
         }
         Vector2 minecartMechPoint = GetMinecartMechPoint(mountedPlayer, 20, -19);
         int damage = 60;
         int num2 = 0;
         float num3 = 0f;
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = Main.npc[i];
             if (nPC.active && nPC.immune[mountedPlayer.whoAmI] <= 0 && !nPC.dontTakeDamage && nPC.Distance(minecartMechPoint) < 300f && nPC.CanBeChasedBy(mountedPlayer) && Collision.CanHitLine(nPC.position, nPC.width, nPC.height, minecartMechPoint, 0, 0) && Math.Abs(MathHelper.WrapAngle(MathHelper.WrapAngle(nPC.AngleFrom(minecartMechPoint)) - MathHelper.WrapAngle((mountedPlayer.fullRotation + (float)num == -1f) ? ((float)Math.PI) : 0f))) < (float)Math.PI / 4f)
             {
                 minecartMechPoint = GetMinecartMechPoint(mountedPlayer, -20, -39);
                 Vector2 v = nPC.position + nPC.Size * Utils.RandomVector2(Main.rand, 0f, 1f) - minecartMechPoint;
                 num3 += v.ToRotation();
                 num2++;
                 int num4 = Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), minecartMechPoint.X, minecartMechPoint.Y, v.X, v.Y, 591, 0, 0f, mountedPlayer.whoAmI, mountedPlayer.whoAmI);
                 Main.projectile[num4].Center = nPC.Center;
                 Main.projectile[num4].damage = damage;
                 Main.projectile[num4].Damage();
                 Main.projectile[num4].damage = 0;
                 Main.projectile[num4].Center = minecartMechPoint;
             }
         }
     }
References Entity.active, Entity.AngleFrom(), NPC.CanBeChasedBy(), Collision.CanHitLine(), Entity.Center, Projectile.damage, Projectile.Damage(), Entity.direction, Entity.Distance(), NPC.dontTakeDamage, Player.fullRotation, Entity.height, NPC.immune, Main.myPlayer, Projectile.NewProjectile(), Main.npc, Entity.position, Main.projectile, Main.rand, Utils.RandomVector2(), Entity.Size, Entity.velocity, Entity.whoAmI, and Entity.width.