Terraria: Mount.DrillSmartCursor_Blocks
DrillSmartCursor_Blocks()
Point16 Mount.DrillSmartCursor_Blocks (Player mountedPlayer, DrillMountData data) inline private
     {
         Vector2 vector = ((mountedPlayer.whoAmI != Main.myPlayer) ? data.crosshairPosition : (Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY)));
         Vector2 center = mountedPlayer.Center;
         Vector2 vector2 = vector - center;
         float num = vector2.Length();
         if (num > 224f)
         {
             num = 224f;
         }
         num += 32f;
         vector2.Normalize();
         Vector2 end = center + vector2 * num;
         Point16 tilePoint = new Point16(-1, -1);
         if (!Utils.PlotTileLine(center, end, 65.6f, delegate(int x, int y)
         {
             tilePoint = new Point16(x, y);
             for (int i = 0; i < data.beams.Length; i++)
             {
                 if (data.beams[i].curTileTarget == tilePoint && data.beams[i].lastPurpose == 0)
                 {
                     return true;
                 }
             }
             if (!WorldGen.CanKillTile(x, y))
             {
                 return true;
             }
             return (Main.tile[x, y] == null || Main.tile[x, y].inActive() || !Main.tile[x, y].active()) ? true : false;
         }))
         {
             return tilePoint;
         }
         return new Point16(-1, -1);
     }
References Tile.active(), Mount.DrillMountData.beams, WorldGen.CanKillTile(), Entity.Center, Mount.DrillMountData.crosshairPosition, Mount.DrillBeam.curTileTarget, Tile.inActive(), Mount.DrillBeam.lastPurpose, Main.mouseX, Main.mouseY, Main.myPlayer, Utils.PlotTileLine(), Main.screenPosition, Main.tile, and Entity.whoAmI.
Referenced by UseDrill().