Terraria: Mount.SetMount
SetMount()
void Mount.SetMount (int m, Player mountedPlayer, bool faceLeft = false) inline
     {
         if (_type == m || m <= -1 || m >= MountID.Count || (m == 5 && mountedPlayer.wet))
         {
             return;
         }
         if (_active)
         {
             mountedPlayer.ClearBuff(_data.buff);
             if (Cart)
             {
                 mountedPlayer.ClearBuff(_data.extraBuff);
                 mountedPlayer.cartFlip = false;
                 mountedPlayer.lastBoost = Vector2.Zero;
             }
             mountedPlayer.fullRotation = 0f;
             mountedPlayer.fullRotationOrigin = Vector2.Zero;
             _mountSpecificData = null;
         }
         else
         {
             _active = true;
         }
         _flyTime = 0;
         _type = m;
         _data = mounts[m];
         _fatigueMax = _data.fatigueMax;
         if (Cart && !faceLeft && !Directional)
         {
             mountedPlayer.AddBuff(_data.extraBuff, 3600);
             _flipDraw = true;
         }
         else
         {
             mountedPlayer.AddBuff(_data.buff, 3600);
             _flipDraw = false;
         }
         if (_type == 44)
         {
             mountedPlayer.velocity *= 0.2f;
             mountedPlayer.dash = 0;
             mountedPlayer.dashType = 0;
             mountedPlayer.dashDelay = 0;
             mountedPlayer.dashTime = 0;
         }
         if (_type == 9 && _abilityCooldown < 20)
         {
             _abilityCooldown = 20;
         }
         if (_type == 46 && _abilityCooldown < 40)
         {
             _abilityCooldown = 40;
         }
         mountedPlayer.position.Y += mountedPlayer.height;
         for (int i = 0; i < mountedPlayer.shadowPos.Length; i++)
         {
             mountedPlayer.shadowPos[i].Y += mountedPlayer.height;
         }
         mountedPlayer.height = 42 + _data.heightBoost;
         mountedPlayer.position.Y -= mountedPlayer.height;
         for (int j = 0; j < mountedPlayer.shadowPos.Length; j++)
         {
             mountedPlayer.shadowPos[j].Y -= mountedPlayer.height;
         }
         mountedPlayer.ResetAdvancedShadows();
         if (_type == 7 || _type == 8)
         {
             mountedPlayer.fullRotationOrigin = new Vector2(mountedPlayer.width / 2, mountedPlayer.height / 2);
         }
         if (_type == 8)
         {
             _mountSpecificData = new DrillMountData();
         }
         if (_type == 35)
         {
             _mountSpecificData = new ExtraFrameMountData();
         }
         DoSpawnDust(mountedPlayer, isDismounting: false);
         if (mountedPlayer.whoAmI == Main.myPlayer)
         {
             NetMessage.SendData(13, -1, -1, null, mountedPlayer.whoAmI);
         }
     }
References Player.AddBuff(), Player.cartFlip, Player.ClearBuff(), MountID.Count, Player.dash, Player.dashDelay, Player.dashTime, Player.dashType, Mount.MountData.fatigueMax, Player.fullRotation, Player.fullRotationOrigin, Entity.height, Player.lastBoost, Main.myPlayer, Entity.position, Player.ResetAdvancedShadows(), NetMessage.SendData(), Player.shadowPos, Entity.velocity, Entity.wet, Entity.whoAmI, and Entity.width.