Terraria: Mount.UseDrill
UseDrill()
void Mount.UseDrill (Player mountedPlayer) inline
     {
         if (_type != 8 || !_abilityActive)
         {
             return;
         }
         DrillMountData drillMountData = (DrillMountData)_mountSpecificData;
         bool flag = mountedPlayer.whoAmI == Main.myPlayer;
         if (mountedPlayer.controlUseItem)
         {
             for (int i = 0; i < amountOfBeamsAtOnce; i++)
             {
                 if (drillMountData.beamCooldown != 0)
                 {
                     break;
                 }
                 for (int j = 0; j < drillMountData.beams.Length; j++)
                 {
                     DrillBeam drillBeam = drillMountData.beams[j];
                     if (drillBeam.cooldown != 0)
                     {
                         continue;
                     }
                     Point16 point = DrillSmartCursor_Blocks(mountedPlayer, drillMountData);
                     if (point == Point16.NegativeOne)
                     {
                         continue;
                     }
                     drillBeam.curTileTarget = point;
                     int pickPower = drillPickPower;
                     if (flag)
                     {
                         bool flag2 = true;
                         if (WorldGen.InWorld(point.X, point.Y) && Main.tile[point.X, point.Y] != null && Main.tile[point.X, point.Y].type == 26 && !Main.hardMode)
{
                             flag2 = false;
                             mountedPlayer.Hurt(PlayerDeathReason.ByOther(4), mountedPlayer.statLife / 2, -mountedPlayer.direction);
                         }
                         if (mountedPlayer.noBuilding)
{
                             flag2 = false;
                         }
                         if (flag2)
{
                             mountedPlayer.PickTile(point.X, point.Y, pickPower);
                         }
                     }
                     Vector2 vector = new Vector2((float)(point.X << 4) + 8f, (float)(point.Y << 4) + 8f);
                     float num = (vector - mountedPlayer.Center).ToRotation();
                     for (int k = 0; k < 2; k++)
                     {
                         float num2 = num + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                         float num3 = (float)Main.rand.NextDouble() * 2f + 2f;
                         Vector2 vector2 = new Vector2((float)Math.Cos(num2) * num3, (float)Math.Sin(num2) * num3);
                         int num4 = Dust.NewDust(vector, 0, 0, 230, vector2.X, vector2.Y);
                         Main.dust[num4].noGravity = true;
                         Main.dust[num4].customData = mountedPlayer;
                     }
                     if (flag)
                     {
                         Tile.SmoothSlope(point.X, point.Y, applyToNeighbors: true, sync: true);
                     }
                     drillBeam.cooldown = drillPickTime;
                     drillBeam.lastPurpose = 0;
                     break;
                 }
             }
         }
         if (!mountedPlayer.controlUseTile)
         {
             return;
         }
         for (int l = 0; l < amountOfBeamsAtOnce; l++)
         {
             if (drillMountData.beamCooldown != 0)
             {
                 break;
             }
             for (int m = 0; m < drillMountData.beams.Length; m++)
             {
                 DrillBeam drillBeam2 = drillMountData.beams[m];
                 if (drillBeam2.cooldown != 0)
                 {
                     continue;
                 }
                 Point16 point2 = DrillSmartCursor_Walls(mountedPlayer, drillMountData);
                 if (point2 == Point16.NegativeOne)
                 {
                     continue;
                 }
                 drillBeam2.curTileTarget = point2;
                 int damage = drillPickPower;
                 if (flag)
                 {
                     bool flag3 = true;
                     if (mountedPlayer.noBuilding)
                     {
                         flag3 = false;
                     }
                     if (flag3)
                     {
                         mountedPlayer.PickWall(point2.X, point2.Y, damage);
                     }
                 }
                 Vector2 vector3 = new Vector2((float)(point2.X << 4) + 8f, (float)(point2.Y << 4) + 8f);
                 float num5 = (vector3 - mountedPlayer.Center).ToRotation();
                 for (int n = 0; n < 2; n++)
                 {
                     float num6 = num5 + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                     float num7 = (float)Main.rand.NextDouble() * 2f + 2f;
                     Vector2 vector4 = new Vector2((float)Math.Cos(num6) * num7, (float)Math.Sin(num6) * num7);
                     int num8 = Dust.NewDust(vector3, 0, 0, 230, vector4.X, vector4.Y);
                     Main.dust[num8].noGravity = true;
                     Main.dust[num8].customData = mountedPlayer;
                 }
                 drillBeam2.cooldown = drillPickTime;
                 drillBeam2.lastPurpose = 1;
                 break;
             }
         }
     }
References _abilityActive, _mountSpecificData, _type, amountOfBeamsAtOnce, Mount.DrillMountData.beamCooldown, Mount.DrillMountData.beams, PlayerDeathReason.ByOther(), Entity.Center, Player.controlUseItem, Player.controlUseTile, Mount.DrillBeam.cooldown, Mount.DrillBeam.curTileTarget, Dust.customData, Entity.direction, drillPickPower, drillPickTime, DrillSmartCursor_Blocks(), DrillSmartCursor_Walls(), Main.dust, Main.hardMode, Player.Hurt(), WorldGen.InWorld(), Mount.DrillBeam.lastPurpose, Main.myPlayer, Point16.NegativeOne, Dust.NewDust(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Player.noBuilding, Dust.noGravity, Player.PickTile(), Player.PickWall(), Main.rand, Tile.SmoothSlope(), Player.statLife, Main.tile, Tile.type, Entity.whoAmI, Point16.X, and Point16.Y.