Terraria: Mount.Hover
Hover()
bool Mount.Hover (Player mountedPlayer) inline
     {
         bool flag = DoesHoverIgnoresFatigue();
         bool flag2 = _frameState == 2 || _frameState == 4;
         if (_type == 49)
         {
             flag2 = _frameState == 4;
         }
         if (flag2)
         {
             bool flag3 = true;
             float num = 1f;
             float num2 = mountedPlayer.gravity / Player.defaultGravity;
             if (mountedPlayer.slowFall)
             {
                 num2 /= 3f;
             }
             if (num2 < 0.25f)
             {
                 num2 = 0.25f;
             }
             if (!flag)
             {
                 if (_flyTime > 0)
                 {
                     _flyTime--;
                 }
                 else if (_fatigue < _fatigueMax)
                 {
                     _fatigue += num2;
                 }
                 else
                 {
                     flag3 = false;
                 }
             }
             if (_type == 12 && !mountedPlayer.MountFishronSpecial)
             {
                 num = 0.5f;
             }
             float num3 = _fatigue / _fatigueMax;
             if (flag)
             {
                 num3 = 0f;
             }
             bool flag4 = true;
             if (_type == 48)
             {
                 flag4 = false;
             }
             float num4 = 4f * num3;
             float num5 = 4f * num3;
             bool flag5 = false;
             if (_type == 48)
             {
                 num4 = 0f;
                 num5 = 0f;
                 if (!flag3)
                 {
                     flag5 = true;
                 }
                 if (mountedPlayer.controlDown)
                 {
                     num5 = 8f;
                 }
             }
             if (num4 == 0f)
             {
                 num4 = -0.001f;
             }
             if (num5 == 0f)
             {
                 num5 = -0.001f;
             }
             float num6 = mountedPlayer.velocity.Y;
             if (flag4 && (mountedPlayer.controlUp || mountedPlayer.controlJump) && flag3)
             {
                 num4 = -2f - 6f * (1f - num3);
                 if (_type == 48)
                 {
                     num4 /= 3f;
                 }
                 num6 -= _data.acceleration * num;
             }
             else if (mountedPlayer.controlDown)
             {
                 num6 += _data.acceleration * num;
                 num5 = 8f;
             }
             else if (flag5)
             {
                 float num7 = mountedPlayer.gravity * mountedPlayer.gravDir;
                 num6 += num7;
                 num5 = 4f;
             }
             else
             {
                 _ = mountedPlayer.jump;
             }
             if (num6 < num4)
             {
                 num6 = ((!(num4 - num6 < _data.acceleration)) ? (num6 + _data.acceleration * num) : num4);
             }
             else if (num6 > num5)
             {
                 num6 = ((!(num6 - num5 < _data.acceleration)) ? (num6 - _data.acceleration * num) : num5);
             }
             mountedPlayer.velocity.Y = num6;
             if (num4 == -0.001f && num5 == -0.001f && num6 == -0.001f)
             {
                 mountedPlayer.position.Y -= -0.001f;
             }
             mountedPlayer.fallStart = (int)(mountedPlayer.position.Y / 16f);
         }
         else if (!flag)
         {
             mountedPlayer.velocity.Y += mountedPlayer.gravity * mountedPlayer.gravDir;
         }
         else if (mountedPlayer.velocity.Y == 0f)
         {
             Vector2 velocity = Vector2.UnitY * mountedPlayer.gravDir * 1f;
             if (Collision.TileCollision(mountedPlayer.position, velocity, mountedPlayer.width, mountedPlayer.height, fallThrough: false, fall2: false, (int)mountedPlayer.gravDir).Y != 0f || mountedPlayer.controlDown)
             {
                 mountedPlayer.velocity.Y = 0.001f;
             }
         }
         else if (mountedPlayer.velocity.Y == -0.001f)
         {
             mountedPlayer.velocity.Y -= -0.001f;
         }
         if (_type == 7)
         {
             float num8 = mountedPlayer.velocity.X / _data.dashSpeed;
             if ((double)num8 > 0.95)
             {
                 num8 = 0.95f;
             }
             if ((double)num8 < -0.95)
             {
                 num8 = -0.95f;
             }
             float fullRotation = (float)Math.PI / 4f * num8 / 2f;
             float num9 = Math.Abs(2f - (float)_frame / 2f) / 2f;
             Lighting.AddLight((int)(mountedPlayer.position.X + (float)(mountedPlayer.width / 2)) / 16, (int)(mountedPlayer.position.Y + (float)(mountedPlayer.height / 2)) / 16, 0.4f, 0.2f * num9, 0f);
             mountedPlayer.fullRotation = fullRotation;
         }
         else if (_type == 8)
         {
             float num10 = mountedPlayer.velocity.X / _data.dashSpeed;
             if ((double)num10 > 0.95)
             {
                 num10 = 0.95f;
             }
             if ((double)num10 < -0.95)
             {
                 num10 = -0.95f;
             }
             float fullRotation2 = (float)Math.PI / 4f * num10 / 2f;
             mountedPlayer.fullRotation = fullRotation2;
             DrillMountData obj = (DrillMountData)_mountSpecificData;
             float outerRingRotation = obj.outerRingRotation;
             outerRingRotation += mountedPlayer.velocity.X / 80f;
             if (outerRingRotation > (float)Math.PI)
             {
                 outerRingRotation -= (float)Math.PI * 2f;
             }
             else if (outerRingRotation < -(float)Math.PI)
             {
                 outerRingRotation += (float)Math.PI * 2f;
             }
             obj.outerRingRotation = outerRingRotation;
         }
         else if (_type == 23)
         {
             float value = (0f - mountedPlayer.velocity.Y) / _data.dashSpeed;
             value = MathHelper.Clamp(value, -1f, 1f);
             float value2 = mountedPlayer.velocity.X / _data.dashSpeed;
             value2 = MathHelper.Clamp(value2, -1f, 1f);
             float num11 = -(float)Math.PI / 16f * value * (float)mountedPlayer.direction;
             float num12 = (float)Math.PI / 16f * value2;
             float fullRotation3 = num11 + num12;
             mountedPlayer.fullRotation = fullRotation3;
             mountedPlayer.fullRotationOrigin = new Vector2(mountedPlayer.width / 2, mountedPlayer.height);
         }
         return true;
     }
References _data, _fatigue, _fatigueMax, _flyTime, _frame, _frameState, _mountSpecificData, _type, Mount.MountData.acceleration, Lighting.AddLight(), Player.controlDown, Player.controlJump, Player.controlUp, Mount.MountData.dashSpeed, Player.defaultGravity, Entity.direction, DoesHoverIgnoresFatigue(), Player.fallStart, Player.fullRotation, Player.fullRotationOrigin, Player.gravDir, Player.gravity, Entity.height, Player.jump, Player.MountFishronSpecial, Entity.position, Player.slowFall, Collision.TileCollision(), Entity.velocity, Entity.width, and Y.