Terraria: Mount.Draw
Draw()
void Mount.Draw (List< DrawData > playerDrawData, int drawType, Player drawPlayer, Vector2 Position, Color drawColor, SpriteEffects playerEffect, float shadow) inline
     {
         if (playerDrawData == null)
         {
             return;
         }
         Texture2D texture2D2;
         Texture2D texture2D;
         switch (drawType)
         {
         case 0:
             texture2D = _data.backTexture.Value;
             texture2D2 = _data.backTextureGlow.Value;
             break;
         case 1:
             texture2D = _data.backTextureExtra.Value;
             texture2D2 = _data.backTextureExtraGlow.Value;
             break;
         case 2:
             if (_type == 0 && _idleTime >= _idleTimeNext)
             {
                 return;
             }
             texture2D = _data.frontTexture.Value;
             texture2D2 = _data.frontTextureGlow.Value;
             break;
         case 3:
             texture2D = _data.frontTextureExtra.Value;
             texture2D2 = _data.frontTextureExtraGlow.Value;
             break;
         default:
             texture2D = null;
             texture2D2 = null;
             break;
         }
         int type = _type;
         if (type == 50 && texture2D != null)
         {
             PlayerQueenSlimeMountTextureContent queenSlimeMount = TextureAssets.RenderTargets.QueenSlimeMount;
             queenSlimeMount.Request();
             if (queenSlimeMount.IsReady)
             {
                 texture2D = queenSlimeMount.GetTarget();
             }
         }
         if (texture2D == null)
         {
             return;
         }
         type = _type;
         if ((type == 0 || type == 9) && drawType == 3 && shadow != 0f)
         {
             return;
         }
         int num = XOffset;
         int num2 = YOffset + PlayerOffset;
         if (drawPlayer.direction <= 0 && (!Cart || !Directional))
         {
             num *= -1;
         }
         Position.X = (int)(Position.X - Main.screenPosition.X + (float)(drawPlayer.width / 2) + (float)num);
         Position.Y = (int)(Position.Y - Main.screenPosition.Y + (float)(drawPlayer.height / 2) + (float)num2);
         int num3 = 0;
         bool flag = true;
         int num4 = _data.totalFrames;
         int num5 = _data.textureHeight;
         switch (_type)
         {
         case 23:
             num3 = _frame;
             break;
         case 9:
             num3 = drawType switch
             {
                 0 => _frame,
                 2 => _frameExtra,
                 3 => _frameExtra,
                 _ => 0,
             };
             break;
         case 46:
             num3 = drawType switch
             {
                 2 => _frame,
                 3 => _frameExtra,
                 _ => 0,
             };
             break;
         case 5:
             num3 = drawType switch
             {
                 0 => _frame,
                 1 => _frameExtra,
                 _ => 0,
             };
             break;
         case 17:
             num5 = texture2D.Height;
             switch (drawType)
             {
             case 0:
                 num3 = _frame;
                 num4 = 4;
                 break;
             case 1:
                 num3 = _frameExtra;
                 num4 = 4;
                 break;
             default:
                 num3 = 0;
                 break;
             }
             break;
         case 52:
             if (drawType == 3)
             {
                 if (drawPlayer.itemAnimation > 0)
                 {
                     Rectangle bodyFrame = drawPlayer.bodyFrame;
                     int num6 = bodyFrame.Y / bodyFrame.Height;
                     int useStyle = drawPlayer.lastVisualizedSelectedItem.useStyle;
                     num3 = Utils.Clamp(num6, 1, 4);
                     if (num3 == 3 || num6 == 0 || useStyle == 13)
                     {
                         num3 = _frame;
                     }
                     if (useStyle == 12 && drawPlayer.itemAnimation > drawPlayer.itemAnimationMax / 2)
                     {
                         num3 = 3;
                     }
                 }
                 else
                 {
                     _ = drawPlayer.lastVisualizedSelectedItem.holdStyle;
                     num3 = _frame;
                 }
             }
             else
             {
                 num3 = _frame;
             }
             break;
         case 39:
             num5 = texture2D.Height;
             switch (drawType)
             {
             case 2:
                 num3 = _frame;
                 num4 = 3;
                 break;
             case 3:
                 num3 = _frameExtra;
                 num4 = 6;
                 break;
             default:
                 num3 = 0;
                 break;
             }
             break;
         default:
             num3 = _frame;
             break;
         }
         int num7 = num5 / num4;
         Rectangle value = new Rectangle(0, num7 * num3, _data.textureWidth, num7);
         if (flag)
         {
             value.Height -= 2;
         }
         switch (_type)
         {
         case 0:
             if (drawType == 3)
             {
                 drawColor = Color.White;
             }
             break;
         case 9:
             if (drawType == 3)
             {
                 if (_abilityCharge == 0)
                 {
                     return;
                 }
                 drawColor = Color.Multiply(Color.White, (float)_abilityCharge / (float)_data.abilityChargeMax);
                 drawColor.A = 0;
             }
             break;
         case 7:
             if (drawType == 3)
             {
                 drawColor = new Color(250, 250, 250, 255) * drawPlayer.stealth * (1f - shadow);
             }
             break;
         }
         Color color = new Color(drawColor.ToVector4() * 0.25f + new Vector4(0.75f));
         switch (_type)
         {
         case 45:
             if (drawType == 2)
             {
                 color = new Color(150, 110, 110, 100);
             }
             break;
         case 11:
             if (drawType == 2)
             {
                 color = Color.White;
                 color.A = 127;
             }
             break;
         case 12:
             if (drawType == 0)
             {
                 float num8 = MathHelper.Clamp(drawPlayer.MountFishronSpecialCounter / 60f, 0f, 1f);
                 color = Colors.CurrentLiquidColor;
                 if (color == Color.Transparent)
                 {
                     color = Color.White;
                 }
                 color.A = 127;
                 color *= num8;
             }
             break;
         case 24:
             if (drawType == 2)
             {
                 color = Color.SkyBlue * 0.5f;
                 color.A = 20;
             }
             break;
         }
         float num9 = 0f;
         switch (_type)
         {
         case 8:
         {
             DrillMountData drillMountData = (DrillMountData)_mountSpecificData;
             switch (drawType)
             {
             case 0:
                 num9 = drillMountData.outerRingRotation - num9;
                 break;
             case 3:
                 num9 = drillMountData.diodeRotation - num9 - drawPlayer.fullRotation;
                 break;
             }
             break;
         }
         case 7:
             num9 = drawPlayer.fullRotation;
             break;
         }
         Vector2 origin = Origin;
         type = _type;
         _ = 8;
         float scale = 1f;
         SpriteEffects spriteEffects;
         switch (_type)
         {
         case 7:
             spriteEffects = SpriteEffects.None;
             break;
         case 8:
             spriteEffects = ((drawPlayer.direction == 1 && drawType == 2) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             break;
         case 6:
         case 13:
             spriteEffects = (_flipDraw ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             break;
         default:
             spriteEffects = playerEffect;
             break;
         }
         if (MountID.Sets.FacePlayersVelocity[_type])
         {
             spriteEffects = ((Math.Sign(drawPlayer.velocity.X) == -drawPlayer.direction) ? (playerEffect ^ SpriteEffects.FlipHorizontally) : playerEffect);
         }
         bool flag2 = false;
         switch (_type)
         {
         case 50:
             if (drawType == 0)
             {
                 Vector2 position = Position + new Vector2(0f, 8 - PlayerOffset + 20);
                 Rectangle value6 = new Rectangle(0, num7 * _frameExtra, _data.textureWidth, num7);
                 if (flag)
                 {
                     value6.Height -= 2;
                 }
                 DrawData item = new DrawData(TextureAssets.Extra[207].Value, position, value6, drawColor, num9, origin, scale, spriteEffects);
                 item.shader = currentShader;
                 playerDrawData.Add(item);
             }
             break;
         case 35:
         {
             if (drawType != 2)
             {
                 break;
             }
             ExtraFrameMountData extraFrameMountData = (ExtraFrameMountData)_mountSpecificData;
             int num11 = -36;
             if (spriteEffects.HasFlag(SpriteEffects.FlipHorizontally))
             {
                 num11 *= -1;
             }
             Vector2 vector2 = new Vector2(num11, -26f);
             if (shadow == 0f)
             {
                 if (Math.Abs(drawPlayer.velocity.X) > 1f)
                 {
                     extraFrameMountData.frameCounter += Math.Min(2f, Math.Abs(drawPlayer.velocity.X * 0.4f));
                     while (extraFrameMountData.frameCounter > 6f)
                     {
                         extraFrameMountData.frameCounter -= 6f;
                         extraFrameMountData.frame++;
                         if ((extraFrameMountData.frame > 2 && extraFrameMountData.frame < 5) || extraFrameMountData.frame > 7)
{
                             extraFrameMountData.frame = 0;
                         }
                     }
                 }
                 else
                 {
                     extraFrameMountData.frameCounter += 1f;
                     while (extraFrameMountData.frameCounter > 6f)
                     {
                         extraFrameMountData.frameCounter -= 6f;
                         extraFrameMountData.frame++;
                         if (extraFrameMountData.frame > 5)
{
                             extraFrameMountData.frame = 5;
                         }
                     }
                 }
             }
             Texture2D value4 = TextureAssets.Extra[142].Value;
             Rectangle value5 = value4.Frame(1, 8, 0, extraFrameMountData.frame);
             if (flag)
             {
                 value5.Height -= 2;
             }
             DrawData item = new DrawData(value4, Position + vector2, value5, drawColor, num9, origin, scale, spriteEffects);
             item.shader = currentShader;
             playerDrawData.Add(item);
             break;
         }
         case 38:
             if (drawType == 0)
             {
                 int num10 = 0;
                 if (spriteEffects.HasFlag(SpriteEffects.FlipHorizontally))
                 {
                     num10 = 22;
                 }
                 Vector2 vector = new Vector2(num10, -10f);
                 Texture2D value2 = TextureAssets.Extra[151].Value;
                 Rectangle value3 = value2.Frame();
                 DrawData item = new DrawData(value2, Position + vector, value3, drawColor, num9, origin, scale, spriteEffects);
                 item.shader = currentShader;
                 playerDrawData.Add(item);
                 flag2 = true;
             }
             break;
         }
         if (!flag2)
         {
             DrawData item = new DrawData(texture2D, Position, value, drawColor, num9, origin, scale, spriteEffects);
             item.shader = currentShader;
             playerDrawData.Add(item);
             if (texture2D2 != null)
             {
                 item = new DrawData(texture2D2, Position, value, color * ((float)(int)drawColor.A / 255f), num9, origin, scale, spriteEffects);
                 item.shader = currentShader;
             }
             playerDrawData.Add(item);
         }
         switch (_type)
         {
         case 50:
             if (drawType == 0)
             {
                 texture2D = TextureAssets.Extra[205].Value;
                 DrawData item = new DrawData(texture2D, Position, value, drawColor, num9, origin, scale, spriteEffects);
                 item.shader = currentShader;
                 playerDrawData.Add(item);
                 Vector2 position3 = Position + new Vector2(0f, 8 - PlayerOffset + 20);
                 Rectangle value8 = new Rectangle(0, num7 * _frameExtra, _data.textureWidth, num7);
                 if (flag)
                 {
                     value8.Height -= 2;
                 }
                 texture2D = TextureAssets.Extra[206].Value;
                 item = new DrawData(texture2D, position3, value8, drawColor, num9, origin, scale, spriteEffects);
                 item.shader = currentShader;
                 playerDrawData.Add(item);
             }
             break;
         case 45:
         {
             if (drawType != 0 || shadow != 0f)
             {
                 break;
             }
             if (Math.Abs(drawPlayer.velocity.X) > DashSpeed * 0.9f)
             {
                 color = new Color(255, 220, 220, 200);
                 scale = 1.1f;
             }
             for (int k = 0; k < 2; k++)
             {
                 Vector2 position2 = Position + new Vector2((float)Main.rand.Next(-10, 11) * 0.1f, (float)Main.rand.Next(-10, 11) * 0.1f);
                 value = new Rectangle(0, num7 * 3, _data.textureWidth, num7);
                 if (flag)
                 {
                     value.Height -= 2;
                 }
                 DrawData item = new DrawData(texture2D2, position2, value, color, num9, origin, scale, spriteEffects);
                 item.shader = currentShader;
                 playerDrawData.Add(item);
             }
             break;
         }
         case 17:
             if (drawType == 1 && ShouldGolfCartEmitLight())
             {
                 value = new Rectangle(0, num7 * 3, _data.textureWidth, num7);
                 if (flag)
                 {
                     value.Height -= 2;
                 }
                 drawColor = Color.White * 1f;
                 drawColor.A = 0;
                 DrawData item = new DrawData(texture2D, Position, value, drawColor, num9, origin, scale, spriteEffects);
                 item.shader = currentShader;
                 playerDrawData.Add(item);
             }
             break;
         case 23:
             if (drawType == 0)
             {
                 texture2D = TextureAssets.Extra[114].Value;
                 value = texture2D.Frame(2);
                 int width = value.Width;
                 value.Width -= 2;
                 float witchBroomTrinketRotation = GetWitchBroomTrinketRotation(drawPlayer);
                 Vector2 vector7 = Position + GetWitchBroomTrinketOriginOffset(drawPlayer);
                 num9 = witchBroomTrinketRotation;
                 origin = new Vector2(value.Width / 2, 0f);
                 DrawData item = new DrawData(texture2D, vector7.Floor(), value, drawColor, num9, origin, scale, spriteEffects);
                 item.shader = currentShader;
                 playerDrawData.Add(item);
                 Color color3 = new Color(new Vector3(0.9f, 0.85f, 0f));
                 color3.A /= 2;
                 float num13 = ((float)drawPlayer.miscCounter / 75f * ((float)Math.PI * 2f)).ToRotationVector2().X * 1f;
                 Color color4 = new Color(80, 70, 40, 0) * (num13 / 8f + 0.5f) * 0.8f;
                 value.X += width;
                 for (int l = 0; l < 4; l++)
                 {
                     item = new DrawData(texture2D, (vector7 + ((float)l * ((float)Math.PI / 2f)).ToRotationVector2() * num13).Floor(), value, color4, num9, origin, scale, spriteEffects);
                     item.shader = currentShader;
                     playerDrawData.Add(item);
                 }
             }
             break;
         case 8:
         {
             if (drawType != 3)
             {
                 break;
             }
             DrillMountData drillMountData2 = (DrillMountData)_mountSpecificData;
             Rectangle value7 = new Rectangle(0, 0, 1, 1);
             Vector2 vector3 = drillDiodePoint1.RotatedBy(drillMountData2.diodeRotation);
             Vector2 vector4 = drillDiodePoint2.RotatedBy(drillMountData2.diodeRotation);
             for (int i = 0; i < drillMountData2.beams.Length; i++)
             {
                 DrillBeam drillBeam = drillMountData2.beams[i];
                 if (drillBeam.curTileTarget == Point16.NegativeOne)
                 {
                     continue;
                 }
                 for (int j = 0; j < 2; j++)
                 {
                     Vector2 vector5 = new Vector2(drillBeam.curTileTarget.X * 16 + 8, drillBeam.curTileTarget.Y * 16 + 8) - Main.screenPosition - Position;
                     Vector2 vector6;
                     Color color2;
                     if (j == 0)
                     {
                         vector6 = vector3;
                         color2 = Color.CornflowerBlue;
                     }
                     else
                     {
                         vector6 = vector4;
                         color2 = Color.LightGreen;
                     }
                     color2.A = 128;
                     color2 *= 0.5f;
                     Vector2 v = vector5 - vector6;
                     float num12 = v.ToRotation();
                     float y = v.Length();
                     DrawData item = new DrawData(scale: new Vector2(2f, y), texture: TextureAssets.MagicPixel.Value, position: vector6 + Position, sourceRect: value7, color: color2, rotation: num12 - (float)Math.PI / 2f, origin: Vector2.Zero, effect: SpriteEffects.None);
                     item.ignorePlayerRotation = true;
                     item.shader = currentShader;
                     playerDrawData.Add(item);
                 }
             }
             break;
         }
         }
     }
References Mount.DrillMountData.beams, Player.bodyFrame, Color, Colors.CurrentLiquidColor, Mount.DrillBeam.curTileTarget, Mount.DrillMountData.diodeRotation, Entity.direction, TextureAssets.Extra, MountID.Sets.FacePlayersVelocity, Mount.ExtraFrameMountData.frame, Mount.ExtraFrameMountData.frameCounter, Player.fullRotation, ARenderTargetContentByRequest.GetTarget(), Entity.height, Item.holdStyle, DrawData.ignorePlayerRotation, ARenderTargetContentByRequest.IsReady, Player.itemAnimation, Player.itemAnimationMax, Player.lastVisualizedSelectedItem, TextureAssets.MagicPixel, Player.miscCounter, Player.MountFishronSpecialCounter, Point16.NegativeOne, UnifiedRandom.Next(), Mount.DrillMountData.outerRingRotation, TextureAssets.RenderTargets.QueenSlimeMount, Main.rand, ARenderTargetContentByRequest.Request(), Main.screenPosition, DrawData.shader, Player.stealth, Item.useStyle, Asset< T >.Value, Entity.velocity, Entity.width, Point16.X, and Point16.Y.