Terraria: ConsoleOutputMirror.ToFile
ToFile()
static void ConsoleOutputMirror.ToFile (string path) inline static
     {
         if (_instance != null)
         {
             _instance.Dispose();
             _instance = null;
         }
         try
         {
             _instance = new ConsoleOutputMirror(path);
         }
         catch (Exception arg)
         {
             Console.WriteLine("Unable to bind console output to file: {0}\r\nException: {1}", path, arg);
         }
     }
References ConsoleOutputMirror(), _instance, and Dispose().
Referenced by Program.SetupLogging().