Terraria: Mount.DoConfettiMinecartEffect
DoConfettiMinecartEffect()
void Mount.DoConfettiMinecartEffect (Player mountedPlayer) inline private
     {
         float num = mountedPlayer.velocity.Length();
         if ((num < 1f && Main.rand.Next(6) != 0) || (num < 3f && Main.rand.Next(3) != 0))
         {
             return;
         }
         int num2 = 1 + (int)num / 6;
         while (num2 > 0)
         {
             num2--;
             float num3 = Main.rand.NextFloat() * 2f;
             Vector2 vector = Main.rand.NextVector2Square(-1f, 1f) * new Vector2(3f, 8f);
             Vector2 vector2 = new Vector2(-18f, 4f) * mountedPlayer.Directions;
             vector2.X += num * (float)mountedPlayer.direction * 0.5f + (float)(mountedPlayer.direction * num2) * num3;
             if (num2 > 0)
             {
                 vector2 += mountedPlayer.velocity * (num2 / 3);
             }
             Vector2 pos = mountedPlayer.Center + vector2 + vector;
             pos = mountedPlayer.RotatedRelativePoint(pos);
             Dust dust = Dust.NewDustPerfect(pos, 139 + Main.rand.Next(4));
             dust.noGravity = true;
             dust.fadeIn = 0.6f;
             dust.scale = 0.5f + num3 / 2f;
             dust.velocity *= 0.2f;
             if (num < 1f)
             {
                 dust.velocity.X -= 0.5f * (float)mountedPlayer.direction;
             }
             dust.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMinecart, mountedPlayer);
         }
     }
References GameShaders.Armor, Entity.Center, Player.cMinecart, Entity.direction, Player.Directions, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Main.rand, Player.RotatedRelativePoint(), Dust.scale, Dust.shader, Dust.velocity, and Entity.velocity.