Terraria: Mount.DoSpawnDust
DoSpawnDust()
void Mount.DoSpawnDust (Player mountedPlayer, bool isDismounting) inline private
     {
         if (Main.netMode == 2)
         {
             return;
         }
         if (_type == 52)
         {
             for (int i = 0; i < 100; i++)
             {
                 _ = _data.spawnDust;
                 Dust dust = Dust.NewDustDirect(new Vector2(mountedPlayer.position.X - 20f, mountedPlayer.position.Y), mountedPlayer.width + 40, mountedPlayer.height, 267, 0f, 0f, 60, new Color(130, 60, 255, 70));
                 dust.scale += (float)Main.rand.Next(-10, 21) * 0.01f;
                 dust.noGravity = true;
                 dust.velocity += mountedPlayer.velocity * 0.8f;
                 dust.velocity *= Main.rand.NextFloat();
                 dust.velocity.Y += 2f * Main.rand.NextFloatDirection();
                 dust.noLight = true;
                 if (Main.rand.Next(3) == 0)
                 {
                     Dust dust2 = Dust.CloneDust(dust);
                     dust2.color = Color.White;
                     dust2.scale *= 0.5f;
                     dust2.alpha = 0;
                 }
             }
             return;
         }
         Color newColor = Color.Transparent;
         if (_type == 23)
         {
             newColor = new Color(255, 255, 0, 255);
         }
         for (int j = 0; j < 100; j++)
         {
             if (MountID.Sets.Cart[_type])
             {
                 if (j % 10 == 0)
                 {
                     int type = Main.rand.Next(61, 64);
                     int num = Gore.NewGore(new Vector2(mountedPlayer.position.X - 20f, mountedPlayer.position.Y), Vector2.Zero, type);
                     Main.gore[num].alpha = 100;
                     Main.gore[num].velocity = Vector2.Transform(new Vector2(1f, 0f), Matrix.CreateRotationZ((float)(Main.rand.NextDouble() * 6.2831854820251465)));
                 }
                 continue;
             }
             int type2 = _data.spawnDust;
             float scale = 1f;
             int alpha = 0;
             if (_type == 40 || _type == 41 || _type == 42)
             {
                 type2 = ((Main.rand.Next(2) != 0) ? 16 : 31);
                 scale = 0.9f;
                 alpha = 50;
                 if (_type == 42)
                 {
                     type2 = 31;
                 }
                 if (_type == 41)
                 {
                     type2 = 16;
                 }
             }
             int num2 = Dust.NewDust(new Vector2(mountedPlayer.position.X - 20f, mountedPlayer.position.Y), mountedPlayer.width + 40, mountedPlayer.height, type2, 0f, 0f, alpha, newColor, scale);
             Main.dust[num2].scale += (float)Main.rand.Next(-10, 21) * 0.01f;
             if (_data.spawnDustNoGravity)
             {
                 Main.dust[num2].noGravity = true;
             }
             else if (Main.rand.Next(2) == 0)
             {
                 Main.dust[num2].scale *= 1.3f;
                 Main.dust[num2].noGravity = true;
             }
             else
             {
                 Main.dust[num2].velocity *= 0.5f;
             }
             Main.dust[num2].velocity += mountedPlayer.velocity * 0.8f;
             if (_type == 40 || _type == 41 || _type == 42)
             {
                 Main.dust[num2].velocity *= Main.rand.NextFloat();
             }
         }
         if (_type == 40 || _type == 41 || _type == 42)
         {
             for (int k = 0; k < 5; k++)
             {
                 int type3 = Main.rand.Next(61, 64);
                 if (_type == 41 || (_type == 40 && Main.rand.Next(2) == 0))
                 {
                     type3 = Main.rand.Next(11, 14);
                 }
                 int num3 = Gore.NewGore(new Vector2(mountedPlayer.position.X + (float)(mountedPlayer.direction * 8), mountedPlayer.position.Y + 20f), Vector2.Zero, type3);
                 Main.gore[num3].alpha = 100;
                 Main.gore[num3].velocity = Vector2.Transform(new Vector2(1f, 0f), Matrix.CreateRotationZ((float)(Main.rand.NextDouble() * 6.2831854820251465))) * 1.4f;
             }
         }
         if (_type == 23)
         {
             for (int l = 0; l < 4; l++)
             {
                 int type4 = Main.rand.Next(61, 64);
                 int num4 = Gore.NewGore(new Vector2(mountedPlayer.position.X - 20f, mountedPlayer.position.Y), Vector2.Zero, type4);
                 Main.gore[num4].alpha = 100;
                 Main.gore[num4].velocity = Vector2.Transform(new Vector2(1f, 0f), Matrix.CreateRotationZ((float)(Main.rand.NextDouble() * 6.2831854820251465)));
             }
         }
     }
References Dust.alpha, Gore.alpha, MountID.Sets.Cart, Dust.CloneDust(), Color, Dust.color, Entity.direction, Main.dust, Main.gore, Entity.height, Main.netMode, Dust.NewDust(), Dust.NewDustDirect(), Gore.NewGore(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, Dust.noLight, Entity.position, Main.rand, Dust.scale, Dust.velocity, Entity.velocity, Gore.velocity, and Entity.width.