Terraria: Mount.Dismount
Dismount()
void Mount.Dismount (Player mountedPlayer) inline
     {
         if (_active)
         {
             bool cart = Cart;
             _active = false;
             mountedPlayer.ClearBuff(_data.buff);
             _mountSpecificData = null;
             _ = _type;
             if (cart)
             {
                 mountedPlayer.ClearBuff(_data.extraBuff);
                 mountedPlayer.cartFlip = false;
                 mountedPlayer.lastBoost = Vector2.Zero;
             }
             mountedPlayer.fullRotation = 0f;
             mountedPlayer.fullRotationOrigin = Vector2.Zero;
             DoSpawnDust(mountedPlayer, isDismounting: true);
             Reset();
             mountedPlayer.position.Y += mountedPlayer.height;
             mountedPlayer.height = 42;
             mountedPlayer.position.Y -= mountedPlayer.height;
             if (mountedPlayer.whoAmI == Main.myPlayer)
             {
                 NetMessage.SendData(13, -1, -1, null, mountedPlayer.whoAmI);
             }
         }
     }
References Player.cartFlip, Player.ClearBuff(), Player.fullRotation, Player.fullRotationOrigin, Entity.height, Player.lastBoost, Main.myPlayer, Entity.position, NetMessage.SendData(), and Entity.whoAmI.
Referenced by PlayerSittingHelper.SitDown(), PlayerSleepingHelper.StartSleeping(), and Main.TryRemovingBuff().