Terraria: Mount.EmitGolfCartWheelDust
EmitGolfCartWheelDust()
static void Mount.EmitGolfCartWheelDust (Player mountedPlayer, Vector2 legSpot) inline static private
     {
         if (Main.rand.Next(5) != 0)
         {
             return;
         }
         Point p = (legSpot + new Vector2(0f, mountedPlayer.gravDir * 2f)).ToTileCoordinates();
         if (!WorldGen.InWorld(p.X, p.Y, 10))
         {
             return;
         }
         Tile tileSafely = Framing.GetTileSafely(p.X, p.Y);
         if (WorldGen.SolidTile(p))
         {
             int num = WorldGen.KillTile_GetTileDustAmount(fail: true, tileSafely);
             if (num > 1)
             {
                 num = 1;
             }
             Vector2 vector = new Vector2(-mountedPlayer.direction, (0f - mountedPlayer.gravDir) * 1f);
             for (int i = 0; i < num; i++)
             {
                 Dust obj = Main.dust[WorldGen.KillTile_MakeTileDust(p.X, p.Y, tileSafely)];
                 obj.velocity *= 0.2f;
                 obj.velocity += vector;
                 obj.position = legSpot;
                 obj.scale *= 0.8f;
                 obj.fadeIn *= 0.8f;
             }
         }
     }
References Entity.direction, Main.dust, Dust.fadeIn, Framing.GetTileSafely(), Player.gravDir, WorldGen.InWorld(), WorldGen.KillTile_GetTileDustAmount(), WorldGen.KillTile_MakeTileDust(), UnifiedRandom.Next(), Dust.position, Main.rand, Dust.scale, WorldGen.SolidTile(), and Dust.velocity.