Terraria: Mount.UseAbility
UseAbility()
void Mount.UseAbility (Player mountedPlayer, Vector2 mousePosition, bool toggleOn) inline
     {
         switch (_type)
         {
         case 9:
         {
             if (Main.myPlayer != mountedPlayer.whoAmI)
             {
                 break;
             }
             int type2 = 606;
             mousePosition = ClampToDeadZone(mountedPlayer, mousePosition);
             Vector2 vector5 = default(Vector2);
             vector5.X = mountedPlayer.position.X + (float)(mountedPlayer.width / 2);
             vector5.Y = mountedPlayer.position.Y + (float)mountedPlayer.height;
             int num3 = (_frameExtra - 6) * 2;
             Vector2 vector6 = default(Vector2);
             for (int i = 0; i < 2; i++)
             {
                 vector6.Y = vector5.Y + scutlixEyePositions[num3 + i].Y + (float)_data.yOffset;
                 if (mountedPlayer.direction == -1)
                 {
                     vector6.X = vector5.X - scutlixEyePositions[num3 + i].X - (float)_data.xOffset;
                 }
                 else
                 {
                     vector6.X = vector5.X + scutlixEyePositions[num3 + i].X + (float)_data.xOffset;
                 }
                 Vector2 vector7 = mousePosition - vector6;
                 vector7.Normalize();
                 vector7 *= 14f;
                 int damage3 = 150;
                 vector6 += vector7;
                 Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), vector6.X, vector6.Y, vector7.X, vector7.Y, type2, damage3, 0f, Main.myPlayer);
             }
             break;
         }
         case 46:
             if (Main.myPlayer == mountedPlayer.whoAmI)
             {
                 if (_abilityCooldown <= 10)
                 {
                     int damage = 120;
                     Vector2 vector = mountedPlayer.Center + new Vector2(mountedPlayer.width * -mountedPlayer.direction, 26f);
                     Vector2 vector2 = new Vector2(0f, -4f).RotatedByRandom(0.10000000149011612);
                     Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), vector.X, vector.Y, vector2.X, vector2.Y, 930, damage, 0f, Main.myPlayer);
                     SoundEngine.PlaySound(SoundID.Item89.SoundId, (int)vector.X, (int)vector.Y, SoundID.Item89.Style, 0.2f);
                 }
                 int type = 14;
                 int damage2 = 100;
                 mousePosition = ClampToDeadZone(mountedPlayer, mousePosition);
                 Vector2 vector3 = default(Vector2);
                 vector3.X = mountedPlayer.position.X + (float)(mountedPlayer.width / 2);
                 vector3.Y = mountedPlayer.position.Y + (float)mountedPlayer.height;
                 Vector2 vector4 = new Vector2(vector3.X + (float)(mountedPlayer.width * mountedPlayer.direction), vector3.Y - 12f);
                 Vector2 v = mousePosition - vector4;
                 v = v.SafeNormalize(Vector2.Zero);
                 v *= 12f;
                 v = v.RotatedByRandom(0.20000000298023224);
                 Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), vector4.X, vector4.Y, v.X, v.Y, type, damage2, 0f, Main.myPlayer);
                 SoundEngine.PlaySound(SoundID.Item11.SoundId, (int)vector4.X, (int)vector4.Y, SoundID.Item11.Style, 0.2f);
             }
             break;
         case 8:
             if (Main.myPlayer == mountedPlayer.whoAmI)
             {
                 if (!toggleOn)
                 {
                     _abilityActive = false;
                 }
                 else if (!_abilityActive)
                 {
                     if (mountedPlayer.whoAmI == Main.myPlayer)
                     {
                         float num = Main.screenPosition.X + (float)Main.mouseX;
                         float num2 = Main.screenPosition.Y + (float)Main.mouseY;
                         float ai = num - mountedPlayer.position.X;
                         float ai2 = num2 - mountedPlayer.position.Y;
                         Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), num, num2, 0f, 0f, 453, 0, 0f, mountedPlayer.whoAmI, ai, ai2);
                     }
                     _abilityActive = true;
                 }
             }
             else
             {
                 _abilityActive = toggleOn;
             }
             break;
         }
     }
References _abilityActive, _abilityCooldown, _data, _frameExtra, _type, Entity.Center, ClampToDeadZone(), Entity.direction, GetProjectileSpawnSource(), Entity.height, SoundID.Item11, SoundID.Item89, Main.mouseX, Main.mouseY, Main.myPlayer, Projectile.NewProjectile(), SoundEngine.PlaySound(), Entity.position, Main.screenPosition, scutlixEyePositions, LegacySoundStyle.SoundId, LegacySoundStyle.Style, Entity.whoAmI, Entity.width, Mount.MountData.xOffset, and Mount.MountData.yOffset.
Referenced by Projectile.Kill().