Terraria: System.Linq.Expressions.MemberInitExpression.ReduceMemberInit
ReduceMemberInit()
static Expression System.Linq.Expressions.MemberInitExpression.ReduceMemberInit (Expression objExpression, ReadOnlyCollection< MemberBinding > bindings, bool keepOnStack) inline static private
Definition at line 37 of file MemberInitExpression.cs.
    {
        ParameterExpression parameterExpression = Expression.Variable(objExpression.Type);
        int count = bindings.Count;
        Expression[] array = new Expression[count + 2];
        array[0] = Expression.Assign(parameterExpression, objExpression);
        for (int i = 0; i < count; i++)
        {
            array[i + 1] = ReduceMemberBinding(parameterExpression, bindings[i]);
        }
        array[count + 1] = (keepOnStack ? ((Expression)parameterExpression) : ((Expression)Utils.Empty));
        return Expression.Block(new ParameterExpression[1] { parameterExpression }, array);
    }
References System.Linq.Expressions.Expression< TDelegate >.Expression(), System.array, System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.Block(), System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Utils.Empty, System.Linq.Expressions.MemberInitExpression.ReduceMemberBinding(), and System.Linq.Expressions.Expression< TDelegate >.Variable().
Referenced by System.Linq.Expressions.MemberInitExpression.Reduce(), and System.Linq.Expressions.MemberInitExpression.ReduceMemberBinding().