Terraria: System.Linq.Expressions.MemberInitExpression.ReduceMemberBinding
ReduceMemberBinding()
static Expression System.Linq.Expressions.MemberInitExpression.ReduceMemberBinding (ParameterExpression objVar, MemberBinding binding) inline static package
Definition at line 66 of file MemberInitExpression.cs.
    {
        MemberExpression memberExpression = Expression.MakeMemberAccess(objVar, binding.Member);
        return binding.BindingType switch
        {
            MemberBindingType.Assignment => Expression.Assign(memberExpression, ((MemberAssignment)binding).Expression),
            MemberBindingType.ListBinding => ReduceListInit(memberExpression, ((MemberListBinding)binding).Initializers, keepOnStack: false),
            MemberBindingType.MemberBinding => ReduceMemberInit(memberExpression, ((MemberMemberBinding)binding).Bindings, keepOnStack: false),
            _ => throw ContractUtils.Unreachable,
        };
    }
References System.Linq.Expressions.Expression< TDelegate >.Assign(), System.Linq.Expressions.Expression< TDelegate >.MakeMemberAccess(), System.Linq.Expressions.MemberInitExpression.ReduceListInit(), System.Linq.Expressions.MemberInitExpression.ReduceMemberInit(), and System.Dynamic.Utils.ContractUtils.Unreachable.
Referenced by System.Linq.Expressions.MemberInitExpression.ReduceMemberInit().