Terraria: System.Globalization.EastAsianLunisolarCalendar.IsLeapDay
IsLeapDay() [2/2]
override bool System.Globalization.EastAsianLunisolarCalendar.IsLeapDay (int year, int month, int day, int era) inline inherited
Definition at line 446 of file EastAsianLunisolarCalendar.cs.
    {
        year = CheckYearMonthRange(year, month, era);
        int num = InternalGetDaysInMonth(year, month);
        if (day < 1 || day > num)
        {
            throw new ArgumentOutOfRangeException("day", day, SR.Format(SR.ArgumentOutOfRange_Day, num, month));
        }
        int yearInfo = GetYearInfo(year, 0);
        if (yearInfo != 0)
        {
            return month == yearInfo + 1;
        }
        return false;
    }
References System.SR.ArgumentOutOfRange_Day, System.Globalization.EastAsianLunisolarCalendar.CheckYearMonthRange(), System.SR.Format(), System.Globalization.EastAsianLunisolarCalendar.GetYearInfo(), System.Globalization.EastAsianLunisolarCalendar.InternalGetDaysInMonth(), and System.year.