Terraria: System.Globalization.EastAsianLunisolarCalendar.LunarToGregorian
LunarToGregorian()
bool System.Globalization.EastAsianLunisolarCalendar.LunarToGregorian (int lunarYear, int lunarMonth, int lunarDate, out int solarYear, out int solarMonth, out int solarDay) inline private inherited
Definition at line 268 of file EastAsianLunisolarCalendar.cs.
    {
        if (lunarDate < 1 || lunarDate > 30)
        {
            solarYear = 0;
            solarMonth = 0;
            solarDay = 0;
            return false;
        }
        int num = lunarDate - 1;
        for (int i = 1; i < lunarMonth; i++)
        {
            num += InternalGetDaysInMonth(lunarYear, i);
        }
        int yearInfo = GetYearInfo(lunarYear, 1);
        int yearInfo2 = GetYearInfo(lunarYear, 2);
        bool flag = GregorianIsLeapYear(lunarYear);
        int[] array = (flag ? s_daysToMonth366 : s_daysToMonth365);
        solarDay = yearInfo2;
        if (yearInfo > 1)
        {
            solarDay += array[yearInfo - 1];
        }
        solarDay += num;
        if (solarDay > 365 + (flag ? 1 : 0))
        {
            solarYear = lunarYear + 1;
            solarDay -= 365 + (flag ? 1 : 0);
        }
        else
        {
            solarYear = lunarYear;
        }
        solarMonth = 1;
        while (solarMonth < 12 && array[solarMonth] < solarDay)
        {
            solarMonth++;
        }
        solarDay -= array[solarMonth - 1];
        return true;
    }
References System.array, System.Globalization.EastAsianLunisolarCalendar.GetYearInfo(), System.Globalization.EastAsianLunisolarCalendar.GregorianIsLeapYear(), System.Globalization.EastAsianLunisolarCalendar.InternalGetDaysInMonth(), System.Globalization.EastAsianLunisolarCalendar.s_daysToMonth365, and System.Globalization.EastAsianLunisolarCalendar.s_daysToMonth366.
Referenced by System.Globalization.EastAsianLunisolarCalendar.LunarToTime(), and System.Globalization.EastAsianLunisolarCalendar.ToDateTime().