Terraria: System.Globalization.EastAsianLunisolarCalendar.TimeToLunar
TimeToLunar()
void System.Globalization.EastAsianLunisolarCalendar.TimeToLunar (DateTime time, out int year, out int month, out int day) inline private inherited
Definition at line 317 of file EastAsianLunisolarCalendar.cs.
    {
        Calendar defaultInstance = GregorianCalendar.GetDefaultInstance();
        int year2 = defaultInstance.GetYear(time);
        int month2 = defaultInstance.GetMonth(time);
        int dayOfMonth = defaultInstance.GetDayOfMonth(time);
        GregorianToLunar(year2, month2, dayOfMonth, out year, out month, out day);
    }
References System.Globalization.Calendar.GetDayOfMonth(), System.Globalization.GregorianCalendar.GetDefaultInstance(), System.Globalization.Calendar.GetMonth(), System.Globalization.Calendar.GetYear(), System.Globalization.EastAsianLunisolarCalendar.GregorianToLunar(), and System.year.
Referenced by System.Globalization.EastAsianLunisolarCalendar.AddMonths(), System.Globalization.EastAsianLunisolarCalendar.AddYears(), System.Globalization.EastAsianLunisolarCalendar.GetDayOfMonth(), System.Globalization.EastAsianLunisolarCalendar.GetDayOfYear(), System.Globalization.EastAsianLunisolarCalendar.GetMonth(), System.Globalization.EastAsianLunisolarCalendar.GetSexagenaryYear(), and System.Globalization.EastAsianLunisolarCalendar.GetYear().