Terraria: System.Globalization.EastAsianLunisolarCalendar.CheckYearMonthRange
CheckYearMonthRange()
int System.Globalization.EastAsianLunisolarCalendar.CheckYearMonthRange (int year, int month, int era) inline package inherited
Definition at line 166 of file EastAsianLunisolarCalendar.cs.
    {
        year = CheckYearRange(year, era);
        if (month == 13 && GetYearInfo(year, 0) == 0)
        {
            ThrowHelper.ThrowArgumentOutOfRange_Month(month);
        }
        if (month < 1 || month > 13)
        {
            ThrowHelper.ThrowArgumentOutOfRange_Month(month);
        }
        return year;
    }
References System.Globalization.EastAsianLunisolarCalendar.CheckYearRange(), System.Globalization.EastAsianLunisolarCalendar.GetYearInfo(), System.ThrowHelper.ThrowArgumentOutOfRange_Month(), and System.year.
Referenced by System.Globalization.EastAsianLunisolarCalendar.GetDaysInMonth(), System.Globalization.EastAsianLunisolarCalendar.IsLeapDay(), System.Globalization.EastAsianLunisolarCalendar.IsLeapMonth(), and System.Globalization.EastAsianLunisolarCalendar.ToDateTime().