Terraria: System.Globalization.EastAsianLunisolarCalendar.MinEraCalendarYear
MinEraCalendarYear()
int System.Globalization.EastAsianLunisolarCalendar.MinEraCalendarYear (int era) inline package inherited
Definition at line 81 of file EastAsianLunisolarCalendar.cs.
    {
        EraInfo[] calEraInfo = CalEraInfo;
        if (calEraInfo == null)
        {
            return MinCalendarYear;
        }
        if (era == 0)
        {
            era = CurrentEraValue;
        }
        if (era == GetEra(MinDate))
        {
            return GetYear(MinCalendarYear, MinDate);
        }
        for (int i = 0; i < calEraInfo.Length; i++)
        {
            if (era == calEraInfo[i].era)
            {
                return calEraInfo[i].minEraYear;
            }
        }
        throw new ArgumentOutOfRangeException("era", era, SR.ArgumentOutOfRange_InvalidEraValue);
    }
References System.SR.ArgumentOutOfRange_InvalidEraValue, System.Globalization.EastAsianLunisolarCalendar.CalEraInfo, System.Globalization.Calendar.CurrentEraValue, System.Globalization.Calendar.GetEra(), System.Globalization.EastAsianLunisolarCalendar.GetYear(), System.Globalization.EastAsianLunisolarCalendar.MinCalendarYear, System.Globalization.EastAsianLunisolarCalendar.MinDate, and System.Globalization.EraInfo.minEraYear.
Referenced by System.Globalization.EastAsianLunisolarCalendar.CheckYearRange().