Terraria: System.Globalization.EastAsianLunisolarCalendar.GregorianToLunar
GregorianToLunar()
void System.Globalization.EastAsianLunisolarCalendar.GregorianToLunar (int solarYear, int solarMonth, int solarDate, out int lunarYear, out int lunarMonth, out int lunarDate) inline private inherited
Definition at line 225 of file EastAsianLunisolarCalendar.cs.
    {
        int num = (GregorianIsLeapYear(solarYear) ? s_daysToMonth366[solarMonth - 1] : s_daysToMonth365[solarMonth - 1]);
        num += solarDate;
        int num2 = num;
        lunarYear = solarYear;
        int yearInfo;
        int yearInfo2;
        if (lunarYear == MaxCalendarYear + 1)
        {
            lunarYear--;
            num2 += (GregorianIsLeapYear(lunarYear) ? 366 : 365);
            yearInfo = GetYearInfo(lunarYear, 1);
            yearInfo2 = GetYearInfo(lunarYear, 2);
        }
        else
        {
            yearInfo = GetYearInfo(lunarYear, 1);
            yearInfo2 = GetYearInfo(lunarYear, 2);
            if (solarMonth < yearInfo || (solarMonth == yearInfo && solarDate < yearInfo2))
            {
                lunarYear--;
                num2 += (GregorianIsLeapYear(lunarYear) ? 366 : 365);
                yearInfo = GetYearInfo(lunarYear, 1);
                yearInfo2 = GetYearInfo(lunarYear, 2);
            }
        }
        num2 -= s_daysToMonth365[yearInfo - 1];
        num2 -= yearInfo2 - 1;
        int num3 = 32768;
        int yearInfo3 = GetYearInfo(lunarYear, 3);
        int num4 = (((yearInfo3 & num3) != 0) ? 30 : 29);
        lunarMonth = 1;
        while (num2 > num4)
        {
            num2 -= num4;
            lunarMonth++;
            num3 >>= 1;
            num4 = (((yearInfo3 & num3) != 0) ? 30 : 29);
        }
        lunarDate = num2;
    }
References System.Globalization.EastAsianLunisolarCalendar.GetYearInfo(), System.Globalization.EastAsianLunisolarCalendar.GregorianIsLeapYear(), System.Globalization.EastAsianLunisolarCalendar.MaxCalendarYear, System.Globalization.EastAsianLunisolarCalendar.s_daysToMonth365, and System.Globalization.EastAsianLunisolarCalendar.s_daysToMonth366.
Referenced by System.Globalization.EastAsianLunisolarCalendar.TimeToLunar().