Terraria: Terraria.GameContent.UI.States.UIBestiaryTest.AddSearchBar
AddSearchBar()
void Terraria.GameContent.UI.States.UIBestiaryTest.AddSearchBar (UIElement innerTopContainer, UIBestiaryEntryInfoPage infoSpace) inline private
Definition at line 305 of file UIBestiaryTest.cs.
    {
        UIImageButton uIImageButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Search", (AssetRequestMode)1))
        {
            Left = new StyleDimension(0f - infoSpace.Width.Pixels, 1f),
            VAlign = 0.5f
        };
        uIImageButton.OnLeftClick += Click_SearchArea;
        uIImageButton.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Search_Border", (AssetRequestMode)1));
        uIImageButton.SetVisibility(1f, 1f);
        uIImageButton.SetSnapPoint("SearchButton", 0);
        innerTopContainer.Append(uIImageButton);
        UIPanel uIPanel = (_searchBoxPanel = new UIPanel
        {
            Left = new StyleDimension(0f - infoSpace.Width.Pixels + uIImageButton.Width.Pixels + 3f, 1f),
            Width = new StyleDimension(infoSpace.Width.Pixels - uIImageButton.Width.Pixels - 3f, 0f),
            Height = new StyleDimension(0f, 1f),
            VAlign = 0.5f
        });
        uIPanel.BackgroundColor = new Color(35, 40, 83);
        uIPanel.BorderColor = new Color(35, 40, 83);
        uIPanel.SetPadding(0f);
        innerTopContainer.Append(uIPanel);
        UISearchBar uISearchBar = (_searchBar = new UISearchBar(Language.GetText("UI.PlayerNameSlot"), 0.8f)
        {
            Width = new StyleDimension(0f, 1f),
            Height = new StyleDimension(0f, 1f),
            HAlign = 0f,
            VAlign = 0.5f,
            Left = new StyleDimension(0f, 0f),
            IgnoresMouseInteraction = true
        });
        uIPanel.OnLeftClick += Click_SearchArea;
        uISearchBar.OnContentsChanged += OnSearchContentsChanged;
        uIPanel.Append(uISearchBar);
        uISearchBar.OnStartTakingInput += OnStartTakingInput;
        uISearchBar.OnEndTakingInput += OnEndTakingInput;
        uISearchBar.OnNeedingVirtualKeyboard += OpenVirtualKeyboardWhenNeeded;
        UIImageButton uIImageButton2 = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/SearchCancel", (AssetRequestMode)1))
        {
            HAlign = 1f,
            VAlign = 0.5f,
            Left = new StyleDimension(-2f, 0f)
        };
        uIImageButton2.OnMouseOver += searchCancelButton_OnMouseOver;
        uIImageButton2.OnLeftClick += searchCancelButton_OnClick;
        uIPanel.Append(uIImageButton2);
    }
References Terraria.GameContent.UI.States.UIBestiaryTest._searchBar, Terraria.GameContent.UI.States.UIBestiaryTest._searchBoxPanel, Terraria.Main.Assets, Terraria.GameContent.UI.States.UIBestiaryTest.Click_SearchArea(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UIBestiaryTest.OnEndTakingInput(), Terraria.GameContent.UI.States.UIBestiaryTest.OnSearchContentsChanged(), Terraria.GameContent.UI.States.UIBestiaryTest.OnStartTakingInput(), Terraria.GameContent.UI.States.UIBestiaryTest.OpenVirtualKeyboardWhenNeeded(), Terraria.GameContent.UI.States.UIBestiaryTest.searchCancelButton_OnClick(), Terraria.GameContent.UI.States.UIBestiaryTest.searchCancelButton_OnMouseOver(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage().