Terraria: Terraria.GameContent.UI.States.UIBestiaryTest.FillProgressBottomBar
FillProgressBottomBar()
void Terraria.GameContent.UI.States.UIBestiaryTest.FillProgressBottomBar (UIElement container) inline private
Definition at line 159 of file UIBestiaryTest.cs.
    {
        UIText progressPercentText = new UIText("", 0.8f)
        {
            HAlign = 0f,
            VAlign = 1f,
            TextOriginX = 0f,
            TextOriginY = 0f
        };
        _progressPercentText = progressPercentText;
        UIColoredSliderSimple uIColoredSliderSimple = new UIColoredSliderSimple
        {
            Width = new StyleDimension(0f, 1f),
            Height = new StyleDimension(15f, 0f),
            VAlign = 1f,
            FilledColor = new Color(51, 137, 255),
            EmptyColor = new Color(35, 43, 81),
            FillPercent = 0f
        };
        uIColoredSliderSimple.OnUpdate += ShowStats_Completion;
        _unlocksProgressBar = uIColoredSliderSimple;
        container.Append(uIColoredSliderSimple);
    }
References Terraria.GameContent.UI.States.UIBestiaryTest._progressPercentText, Terraria.GameContent.UI.States.UIBestiaryTest._unlocksProgressBar, Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Graphics.Color, Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIBestiaryTest.ShowStats_Completion(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage().