Terraria: Terraria.GameContent.UI.States.UIBestiaryTest.FilterEntries
FilterEntries()
void Terraria.GameContent.UI.States.UIBestiaryTest.FilterEntries () inline private
Definition at line 447 of file UIBestiaryTest.cs.
    {
        _workingSetEntries.Clear();
        _workingSetEntries.AddRange(_originalEntriesList.Where(_filterer.FitsFilter));
    }
References Terraria.GameContent.UI.States.UIBestiaryTest._filterer, Terraria.GameContent.UI.States.UIBestiaryTest._originalEntriesList, Terraria.GameContent.UI.States.UIBestiaryTest._workingSetEntries, System.Collections.Generic.List< T >.AddRange(), System.Collections.Generic.List< T >.Clear(), and Terraria.DataStructures.EntryFilterer< T, U >.FitsFilter().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryContents().