Terraria: Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryGridRange
UpdateBestiaryGridRange()
void Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryGridRange () inline
Definition at line 478 of file UIBestiaryTest.cs.
    {
        _indexesRangeText.SetText(_entryGrid.GetRangeText());
    }
References Terraria.GameContent.UI.States.UIBestiaryTest._entryGrid, Terraria.GameContent.UI.States.UIBestiaryTest._indexesRangeText, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetRangeText(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage().