Terraria: Terraria.GameContent.UI.States.UIBestiaryTest.OnFinishedSettingName
OnFinishedSettingName()
void Terraria.GameContent.UI.States.UIBestiaryTest.OnFinishedSettingName (string name) inline private
Definition at line 380 of file UIBestiaryTest.cs.
    {
        string contents = name.Trim();
        _searchBar.SetContents(contents);
        GoBackHere();
    }
References Terraria.GameContent.UI.States.UIBestiaryTest._searchBar, Terraria.GameContent.UI.States.UIBestiaryTest.GoBackHere(), and Terraria.GameContent.UI.Elements.UISearchBar.SetContents().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.OpenVirtualKeyboardWhenNeeded().