Terraria: Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForEntryGrid
SetupPointsForEntryGrid()
void Terraria.GameContent.UI.States.UIBestiaryTest.SetupPointsForEntryGrid (ref int currentID, List< SnapPoint > pts, out int gridWidth, out int gridHeight, out UILinkPoint gridPoints[,]) inline private
Definition at line 837 of file UIBestiaryTest.cs.
    {
        List<SnapPoint> orderedPointsByCategoryName = GetOrderedPointsByCategoryName(pts, "Entries");
        _entryGrid.GetEntriesToShow(out gridWidth, out gridHeight, out var _);
        gridPoints = new UILinkPoint[gridWidth, gridHeight];
        for (int i = 0; i < orderedPointsByCategoryName.Count; i++)
        {
            int num = i % gridWidth;
            int num2 = i / gridWidth;
            gridPoints[num, num2] = MakeLinkPointFromSnapPoint(currentID++, orderedPointsByCategoryName[i]);
        }
        for (int j = 0; j < gridWidth; j++)
        {
            for (int k = 0; k < gridHeight; k++)
            {
                UILinkPoint uILinkPoint = gridPoints[j, k];
                if (j < gridWidth - 1)
                {
                    UILinkPoint uILinkPoint2 = gridPoints[j + 1, k];
                    if (uILinkPoint != null && uILinkPoint2 != null)
                    {
                        PairLeftRight(uILinkPoint, uILinkPoint2);
                    }
                }
                if (k < gridHeight - 1)
                {
                    UILinkPoint uILinkPoint3 = gridPoints[j, k + 1];
                    if (uILinkPoint != null && uILinkPoint3 != null)
                    {
                        PairUpDown(uILinkPoint, uILinkPoint3);
                    }
                }
            }
        }
    }
References Terraria.GameContent.UI.States.UIBestiaryTest._entryGrid, System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetEntriesToShow(), Terraria.GameContent.UI.States.UIBestiaryTest.GetOrderedPointsByCategoryName(), Terraria.GameContent.UI.States.UIBestiaryTest.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIBestiaryTest.PairLeftRight(), and Terraria.GameContent.UI.States.UIBestiaryTest.PairUpDown().
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.SetupGamepadPoints().