Terraria: Terraria.GameContent.UI.States.UIBestiaryTest.MakeExitButton
MakeExitButton()
void Terraria.GameContent.UI.States.UIBestiaryTest.MakeExitButton (UIElement outerContainer) inline private
    {
        UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true)
        {
            Width = StyleDimension.FromPixelsAndPercent(-10f, 0.5f),
            Height = StyleDimension.FromPixels(50f),
            VAlign = 1f,
            HAlign = 0.5f,
            Top = StyleDimension.FromPixels(-25f)
        };
        uITextPanel.OnMouseOver += FadedMouseOver;
        uITextPanel.OnMouseOut += FadedMouseOut;
        uITextPanel.OnLeftMouseDown += Click_GoBack;
        uITextPanel.SetSnapPoint("ExitButton", 0);
        outerContainer.Append(uITextPanel);
    }
References Terraria.GameContent.UI.States.UIBestiaryTest.Click_GoBack(), Terraria.GameContent.UI.States.UIBestiaryTest.FadedMouseOut(), Terraria.GameContent.UI.States.UIBestiaryTest.FadedMouseOver(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage().