Terraria: UIColoredSliderSimple.DrawValueBarDynamicWidth
DrawValueBarDynamicWidth()
void UIColoredSliderSimple.DrawValueBarDynamicWidth (SpriteBatch sb) inline private
     {
         Texture2D value = TextureAssets.ColorBar.Value;
         Rectangle rectangle = GetDimensions().ToRectangle();
         Rectangle rectangle2 = new Rectangle(5, 4, 4, 4);
         Utils.DrawSplicedPanel(sb, value, rectangle.X, rectangle.Y, rectangle.Width, rectangle.Height, rectangle2.X, rectangle2.Width, rectangle2.Y, rectangle2.Height, Color.White);
         Rectangle rectangle3 = rectangle;
         rectangle3.X += rectangle2.Left;
         rectangle3.Width -= rectangle2.Right;
         rectangle3.Y += rectangle2.Top;
         rectangle3.Height -= rectangle2.Bottom;
         Texture2D value2 = TextureAssets.MagicPixel.Value;
         Rectangle value3 = new Rectangle(0, 0, 1, 1);
         sb.Draw(value2, rectangle3, value3, EmptyColor);
         Rectangle destinationRectangle = rectangle3;
         destinationRectangle.Width = (int)((float)destinationRectangle.Width * FillPercent);
         sb.Draw(value2, destinationRectangle, value3, FilledColor);
     }
References Color, TextureAssets.ColorBar, Utils.DrawSplicedPanel(), EmptyColor, FilledColor, FillPercent, UIElement.GetDimensions(), TextureAssets.MagicPixel, CalculatedStyle.ToRectangle(), and Asset< T >.Value.
Referenced by DrawSelf().