Terraria: RgbDevice.GetProcessedLedColor
GetProcessedLedColor()
Vector4 RgbDevice.GetProcessedLedColor (int index) inline protected inherited
     {
         //IL_000c: Unknown result type (might be due to invalid IL or missing references)
         //IL_0011: Unknown result type (might be due to invalid IL or missing references)
         //IL_001f: Unknown result type (might be due to invalid IL or missing references)
         Vector4 color = _backBuffer.Colors[index];
         _colorProfile.Apply(ref color);
         return color;
     }
References RgbDevice._backBuffer, RgbDevice._colorProfile, DeviceColorProfile.Apply(), and Fragment.Colors.
Referenced by CorsairGenericDevice.Present(), CorsairKeyboard.Present(), LogitechKeyboard.Present(), LogitechSingleLightDevice.Present(), RazerHeadset.Present(), RazerKeyboard.Present(), RazerKeypad.Present(), RazerLink.Present(), RazerMouse.Present(), RazerMousepad.Present(), SteelSeriesKeyboard.Present(), and SteelSeriesSecondaryDeviceByZone.Present().