Terraria: Terraria.GameContent.RGB.FrostLegionShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.FrostLegionShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
    {
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            float staticNoise = NoiseHelper.GetStaticNoise(fragment.GetGridPositionOfIndex(i).X / 2);
            float num = (canvasPositionOfIndex.Y + canvasPositionOfIndex.X / 2f - staticNoise + time) % 2f;
            if (num < 0f)
            {
                num += 2f;
            }
            if (num < 0.2f)
            {
                num = 1f - num / 0.2f;
            }
            float amount = num / 2f;
            Vector4 vector = Vector4.Lerp(_primaryColor, _secondaryColor, amount);
            fragment.SetColor(i, vector);
        }
    }
References Terraria.GameContent.RGB.FrostLegionShader._primaryColor, Terraria.GameContent.RGB.FrostLegionShader._secondaryColor, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), and ReLogic.Peripherals.RGB.Fragment.SetColor().