Terraria: System.Threading.ContextCallback
ContextCallback()
delegate void System.Threading.ContextCallback (object? state)
Referenced by System.Net.NetworkInformation.NetworkChange.AvailabilityChangeListener.ChangedAddress(), System.Threading.Barrier.FinishPhase(), and System.IO.Stream.ReadWriteTask.Invoke().