Terraria: System.Data.DataTextWriter.CreateWriter
CreateWriter()
static XmlWriter System.Data.DataTextWriter.CreateWriter (XmlWriter xw) inline static package
Definition at line 28 of file DataTextWriter.cs.
    {
        return new DataTextWriter(xw);
    }
References System.Data.DataTextWriter.DataTextWriter(), and System.Xml.Dictionary.
Referenced by System.Data.NewDiffgramGen.Save(), System.Data.XmlDataTreeWriter.Save(), and System.Data.XmlDataTreeWriter.SaveDiffgramData().