Terraria: UIEmotesMenu.GetEmoteGroup
GetEmoteGroup()
List<SnapPoint> UIEmotesMenu.GetEmoteGroup (List< SnapPoint > ptsOnPage, int groupIndex) inline private
     {
         string groupName = "Group " + groupIndex;
         List<SnapPoint> list = ptsOnPage.Where((SnapPoint a) => a.Name == groupName).ToList();
         list.Sort(SortPoints);
         return list;
     }
References SnapPoint.Name, and SortPoints().
Referenced by SetupGamepadPoints(), and SetupGamepadPoints2().