Terraria: UIEmotesMenu.Recalculate
Recalculate()
override void UIEmotesMenu.Recalculate () inline virtual
Reimplemented from UIElement.
     {
         if (_scrollBar != null)
         {
             if (_isScrollbarAttached && !_scrollBar.CanScroll)
             {
                 _container.RemoveChild(_scrollBar);
                 _isScrollbarAttached = false;
                 _list.Width.Set(0f, 1f);
             }
             else if (!_isScrollbarAttached && _scrollBar.CanScroll)
             {
                 _container.Append(_scrollBar);
                 _isScrollbarAttached = true;
                 _list.Width.Set(-25f, 1f);
             }
         }
         base.Recalculate();
     }
References _container, _isScrollbarAttached, _list, _scrollBar, UIElement.Append(), UIScrollbar.CanScroll, UIElement.RemoveChild(), StyleDimension.Set(), and UIElement.Width.