Terraria: UIEmotesMenu.SetupGamepadPoints2
SetupGamepadPoints2()
void UIEmotesMenu.SetupGamepadPoints2 (SpriteBatch spriteBatch) inline private
     {
         int num = 7;
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
         int num2;
         int iD = (num2 = 3001);
         List<SnapPoint> snapPoints = GetSnapPoints();
         RemoveSnapPointsOutOfScreen(spriteBatch, snapPoints);
         UILinkPointNavigator.SetPosition(iD, _backPanel.GetInnerDimensions().ToRectangle().Center.ToVector2());
         UILinkPoint uILinkPoint = UILinkPointNavigator.Points[num2];
         uILinkPoint.Unlink();
         uILinkPoint.Up = num2 + 1;
         UILinkPoint uILinkPoint2 = uILinkPoint;
         num2++;
         int num3 = 0;
         List<List<SnapPoint>> list = new List<List<SnapPoint>>();
         for (int i = 0; i < num; i++)
         {
             List<SnapPoint> emoteGroup = GetEmoteGroup(snapPoints, i);
             if (emoteGroup.Count > 0)
             {
                 list.Add(emoteGroup);
             }
             num3 += (int)Math.Ceiling((float)emoteGroup.Count / 14f);
         }
         SnapPoint[,] array = new SnapPoint[14, num3];
         int num4 = 0;
         for (int j = 0; j < list.Count; j++)
         {
             List<SnapPoint> list2 = list[j];
             for (int k = 0; k < list2.Count; k++)
             {
                 int num5 = num4 + k / 14;
                 int num6 = k % 14;
                 array[num6, num5] = list2[k];
             }
             num4 += (int)Math.Ceiling((float)list2.Count / 14f);
         }
         int[,] array2 = new int[14, num3];
         int up = 0;
         for (int l = 0; l < array.GetLength(1); l++)
         {
             for (int m = 0; m < array.GetLength(0); m++)
             {
                 SnapPoint snapPoint = array[m, l];
                 if (snapPoint != null)
                 {
                     UILinkPointNavigator.Points[num2].Unlink();
                     UILinkPointNavigator.SetPosition(num2, snapPoint.Position);
                     array2[m, l] = num2;
                     if (m == 0)
                     {
                         up = num2;
                     }
                     num2++;
                 }
             }
         }
         uILinkPoint2.Up = up;
         for (int n = 0; n < array.GetLength(1); n++)
         {
             for (int num7 = 0; num7 < array.GetLength(0); num7++)
             {
                 int num8 = array2[num7, n];
                 if (num8 == 0)
                 {
                     continue;
                 }
                 UILinkPoint uILinkPoint3 = UILinkPointNavigator.Points[num8];
                 if (TryGetPointOnGrid(array2, num7, n, -1, 0))
                 {
                     uILinkPoint3.Left = array2[num7 - 1, n];
                 }
                 else
                 {
                     uILinkPoint3.Left = uILinkPoint3.ID;
                     for (int num9 = num7; num9 < array.GetLength(0); num9++)
                     {
                         if (TryGetPointOnGrid(array2, num9, n, 0, 0))
{
                             uILinkPoint3.Left = array2[num9, n];
                         }
                     }
                 }
                 if (TryGetPointOnGrid(array2, num7, n, 1, 0))
                 {
                     uILinkPoint3.Right = array2[num7 + 1, n];
                 }
                 else
                 {
                     uILinkPoint3.Right = uILinkPoint3.ID;
                     for (int num10 = num7; num10 >= 0; num10--)
                     {
                         if (TryGetPointOnGrid(array2, num10, n, 0, 0))
{
                             uILinkPoint3.Right = array2[num10, n];
                         }
                     }
                 }
                 if (TryGetPointOnGrid(array2, num7, n, 0, -1))
                 {
                     uILinkPoint3.Up = array2[num7, n - 1];
                 }
                 else
                 {
                     uILinkPoint3.Up = uILinkPoint3.ID;
                     for (int num11 = n - 1; num11 >= 0; num11--)
                     {
                         if (TryGetPointOnGrid(array2, num7, num11, 0, 0))
{
                             uILinkPoint3.Up = array2[num7, num11];
                             break;
                         }
                     }
                 }
                 if (TryGetPointOnGrid(array2, num7, n, 0, 1))
                 {
                     uILinkPoint3.Down = array2[num7, n + 1];
                     continue;
                 }
                 uILinkPoint3.Down = uILinkPoint3.ID;
                 for (int num12 = n + 1; num12 < array.GetLength(1); num12++)
                 {
                     if (TryGetPointOnGrid(array2, num7, num12, 0, 0))
                     {
                         uILinkPoint3.Down = array2[num7, num12];
                         break;
                     }
                 }
                 if (uILinkPoint3.Down == uILinkPoint3.ID)
                 {
                     uILinkPoint3.Down = uILinkPoint2.ID;
                 }
             }
         }
     }
References _backPanel, UILinkPointNavigator.Shortcuts.BackButtonCommand, UILinkPoint.Down, GetEmoteGroup(), UIElement.GetInnerDimensions(), UIElement.GetSnapPoints(), UILinkPoint.ID, UILinkPoint.Left, UILinkPointNavigator.Points, SnapPoint.Position, RemoveSnapPointsOutOfScreen(), UILinkPoint.Right, UILinkPointNavigator.SetPosition(), CalculatedStyle.ToRectangle(), TryGetPointOnGrid(), UILinkPoint.Unlink(), and UILinkPoint.Up.
Referenced by Draw().