Terraria: System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCngPublicKey.ExportParameters
ExportParameters()
override ECParameters System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCngPublicKey.ExportParameters () inline virtual
Reimplemented from System.Security.Cryptography.ECDiffieHellmanPublicKey.
Definition at line 440 of file ECDiffieHellmanImplementation.cs.
        {
            if (_keyBlob == null)
            {
                throw new ObjectDisposedException("ECDiffieHellmanPublicKey");
            }
            if (string.IsNullOrEmpty(_curveName))
            {
                return ExportExplicitParameters();
            }
            ECParameters ecParams = default(ECParameters);
            ECCng.ExportNamedCurveParameters(ref ecParams, _keyBlob, includePrivateParameters: false);
            ecParams.Curve = ECCurve.CreateFromFriendlyName(_curveName);
            return ecParams;
        }
References System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCngPublicKey._curveName, System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCngPublicKey._keyBlob, System.Security.Cryptography.ECCurve.CreateFromFriendlyName(), System.Security.Cryptography.ECDiffieHellmanImplementation.ECDiffieHellmanCngPublicKey.ExportExplicitParameters(), and System.Security.Cryptography.ECCng.ExportNamedCurveParameters().