Terraria: System.Collections.Immutable.ImmutableArray.Empty
Empty
readonly ImmutableArray<T> System.Collections.Immutable.ImmutableArray< T >.Empty = new ImmutableArray<T>(new T[0]) static
Definition at line 760 of file ImmutableArray.cs.
Referenced by System.Collections.Immutable.ImmutableArray< T >.Clear(), System.Reflection.Metadata.MethodBodyBlock.Create(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeArrayArgument(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeArrayType(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeFixedArguments(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeMethodSignature(), System.Reflection.Metadata.Ecma335.CustomAttributeDecoder< TType >.DecodeNamedArguments(), System.Reflection.Metadata.EventDefinition.GetAccessors(), System.Reflection.Metadata.PropertyDefinition.GetAccessors(), System.Reflection.PortableExecutable.PEMemoryBlock.GetContent(), System.Reflection.PortableExecutable.PEMemoryBlock.GetContent(), and System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory().