Terraria: System.Collections.Immutable.ImmutableArray.RemoveRange
RemoveRange() [7/7]
ImmutableArray< T > System.Collections.Immutable.ImmutableArray< T >.RemoveRange (int index, int length) inline
Implements System.Collections.Immutable.IImmutableList< T >.
Definition at line 1188 of file ImmutableArray.cs.
    {
        ImmutableArray<T> result = this;
        result.ThrowNullRefIfNotInitialized();
        Requires.Range(index >= 0 && index <= result.Length, "index");
        Requires.Range(length >= 0 && index + length <= result.Length, "length");
        if (length == 0)
        {
            return result;
        }
        T[] array = new T[result.Length - length];
        Array.Copy(result.array, array, index);
        Array.Copy(result.array, index + length, array, index, result.Length - index - length);
        return new ImmutableArray<T>(array);
    }
References System.Collections.Immutable.ImmutableArray< T >.array, System.Array.Copy(), System.index, System.length, and System.Collections.Immutable.Requires.Range().
Referenced by System.Collections.Immutable.ImmutableArray< T >.RemoveAt(), System.Collections.Immutable.ImmutableArray< T >.RemoveRange(), and System.Collections.Immutable.ImmutableArray< T >.RemoveRange().