Terraria: System.Collections.Immutable.ImmutableArray.Add
Add() [4/6]
ImmutableArray< T > System.Collections.Immutable.ImmutableArray< T >.Add (T item) inline
Implements System.Collections.Immutable.IImmutableList< T >.
Definition at line 1117 of file ImmutableArray.cs.
    {
        ImmutableArray<T> immutableArray = this;
        if (immutableArray.Length == 0)
        {
            return ImmutableArray.Create(item);
        }
        return immutableArray.Insert(immutableArray.Length, item);
    }
References System.item.
Referenced by System.Reflection.Metadata.Ecma335.ControlFlowBuilder.AddLabel(), System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeArrayType(), and System.Reflection.Metadata.Ecma335.SignatureDecoder< TType, TGenericContext >.DecodeTypeSequence().