Terraria: System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetDefaultEvent
GetDefaultEvent()
EventDescriptor ICustomTypeDescriptor. System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor.GetDefaultEvent () inline
Implements System.ComponentModel.ICustomTypeDescriptor.
Definition at line 448 of file TypeDescriptor.cs.
            {
                TypeDescriptionProvider provider = _node.Provider;
                if (provider is ReflectTypeDescriptionProvider reflectTypeDescriptionProvider)
                {
                    return reflectTypeDescriptionProvider.GetExtendedDefaultEvent(_instance);
                }
                ICustomTypeDescriptor extendedTypeDescriptor = provider.GetExtendedTypeDescriptor(_instance);
                if (extendedTypeDescriptor == null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.TypeDescriptorProviderError, _node.Provider.GetType().FullName, "GetExtendedTypeDescriptor"));
                }
                return extendedTypeDescriptor.GetDefaultEvent();
            }
References System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor._instance, System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultExtendedTypeDescriptor._node, System.SR.Format(), System.ComponentModel.ICustomTypeDescriptor.GetDefaultEvent(), System.ComponentModel.TypeDescriptionProvider.GetExtendedTypeDescriptor(), System.ComponentModel.TypeDescriptor.TypeDescriptionNode.Provider, and System.SR.TypeDescriptorProviderError.