Terraria: Interop.Kernel32.SystemTimeToFileTime
SystemTimeToFileTime()
static unsafe BOOL Interop.Kernel32.SystemTimeToFileTime (SYSTEMTIME * lpSystemTime, ulong * lpFileTime) package
Referenced by System.DateTime.IsValidTimeWithLeapSeconds(), System.DateTime.ToFileTimeLeapSecondsAware(), and System.DateTime.UpdateLeapSecondCacheAndReturnUtcNow().