Terraria: Interop.Kernel32.MoveFile
MoveFile()
static bool Interop.Kernel32.MoveFile (string src, string dst, bool overwrite) inline static package
Definition at line 969 of file Interop.cs.
        {
            src = PathInternal.EnsureExtendedPrefixIfNeeded(src);
            dst = PathInternal.EnsureExtendedPrefixIfNeeded(dst);
            uint num = 2u;
            if (overwrite)
            {
                num |= 1u;
            }
            return MoveFileExPrivate(src, dst, num);
        }
References System.IO.PathInternal.EnsureExtendedPrefixIfNeeded(), and Interop.Kernel32.MoveFileExPrivate().
Referenced by System.IO.FileSystem.MoveDirectory(), and System.IO.FileSystem.MoveFile().