Terraria: Interop.Kernel32.CreateSymbolicLink
CreateSymbolicLink()
static void Interop.Kernel32.CreateSymbolicLink (string symlinkFileName, string targetFileName, bool isDirectory) inline static package
Definition at line 777 of file Interop.cs.
        {
            string path = symlinkFileName;
            symlinkFileName = PathInternal.EnsureExtendedPrefixIfNeeded(symlinkFileName);
            targetFileName = PathInternal.EnsureExtendedPrefixIfNeeded(targetFileName);
            int num = 0;
            bool flag = (Environment.OSVersion.Version.Major == 10 && Environment.OSVersion.Version.Build >= 14972) || Environment.OSVersion.Version.Major >= 11;
            if (flag)
            {
                num = 2;
            }
            if (isDirectory)
            {
                num |= 1;
            }
            if (!CreateSymbolicLinkPrivate(symlinkFileName, targetFileName, num))
            {
                throw Win32Marshal.GetExceptionForLastWin32Error(path);
            }
            int lastWin32Error;
            if (!flag && (lastWin32Error = Marshal.GetLastWin32Error()) != 0)
            {
                throw Win32Marshal.GetExceptionForWin32Error(lastWin32Error, path);
            }
        }
References Interop.Kernel32.CreateSymbolicLinkPrivate(), System.IO.PathInternal.EnsureExtendedPrefixIfNeeded(), System.IO.Win32Marshal.GetExceptionForLastWin32Error(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), and System.Environment.OSVersion.
Referenced by System.IO.FileSystem.CreateSymbolicLink().