Terraria: Interop.Kernel32.GetMessage
GetMessage() [22/22]
static unsafe string Interop.Kernel32.GetMessage (int errorCode, IntPtr moduleHandle) inline static package
Definition at line 387 of file Interop.cs.
        {
            int num = 12800;
            if (moduleHandle != IntPtr.Zero)
            {
                num |= 0x800;
            }
            Span<char> span = stackalloc char[256];
            fixed (char* lpBuffer = span)
            {
                int num2 = FormatMessage(num, moduleHandle, (uint)errorCode, 0, lpBuffer, span.Length, IntPtr.Zero);
                if (num2 > 0)
                {
                    return GetAndTrimString(span.Slice(0, num2));
                }
            }
            if (Marshal.GetLastWin32Error() == 122)
            {
                IntPtr intPtr = default(IntPtr);
                try
                {
                    int num3 = FormatMessage(num | 0x100, moduleHandle, (uint)errorCode, 0, &intPtr, 0, IntPtr.Zero);
                    if (num3 > 0)
                    {
                        return GetAndTrimString(new Span<char>((void*)intPtr, num3));
                    }
                }
                finally
                {
                    Marshal.FreeHGlobal(intPtr);
                }
            }
            return $"Unknown error (0x{errorCode:x})";
        }
References Interop.Kernel32.FormatMessage(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), Interop.Kernel32.GetAndTrimString(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Span< T >.Length, System.Span< T >.Slice(), and System.IntPtr.Zero.