Terraria: Interop.Kernel32.CopyFileEx
CopyFileEx()
static bool Interop.Kernel32.CopyFileEx (string src, string dst, IntPtr progressRoutine, IntPtr progressData, ref int cancel, int flags) inline static package
Definition at line 716 of file Interop.cs.
        {
            src = PathInternal.EnsureExtendedPrefixIfNeeded(src);
            dst = PathInternal.EnsureExtendedPrefixIfNeeded(dst);
            return CopyFileExPrivate(src, dst, progressRoutine, progressData, ref cancel, flags);
        }
References Interop.Kernel32.CopyFileExPrivate(), and System.IO.PathInternal.EnsureExtendedPrefixIfNeeded().
Referenced by Interop.Kernel32.CopyFile().