Terraria: Interop.Kernel32.CopyFile
CopyFile()
static int Interop.Kernel32.CopyFile (string src, string dst, bool failIfExists) inline static package
Definition at line 702 of file Interop.cs.
        {
            int flags = (failIfExists ? 1 : 0);
            int cancel = 0;
            if (!CopyFileEx(src, dst, IntPtr.Zero, IntPtr.Zero, ref cancel, flags))
            {
                return Marshal.GetLastWin32Error();
            }
            return 0;
        }
References Interop.Kernel32.CopyFileEx(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), and System.IntPtr.Zero.
Referenced by System.IO.FileSystem.CopyFile().