Terraria: System.Xml.Xsl.Runtime.XmlCollation.Create
Create() [2/2]
static XmlCollation System.Xml.Xsl.Runtime.XmlCollation.Create (string collationLiteral, bool throwOnError) inline static package
Definition at line 114 of file XmlCollation.cs.
    {
        if (collationLiteral == "http://www.w3.org/2004/10/xpath-functions/collation/codepoint")
        {
            return CodePointCollation;
        }
        CultureInfo cultureInfo = null;
        Options options = default(Options);
        Uri result;
        if (throwOnError)
        {
            result = new Uri(collationLiteral);
        }
        else if (!Uri.TryCreate(collationLiteral, UriKind.Absolute, out result))
        {
            return null;
        }
        string components = result.GetComponents(UriComponents.SchemeAndServer | UriComponents.UserInfo, UriFormat.UriEscaped);
        if (components == "http://collations.microsoft.com")
        {
            string text = result.LocalPath.Substring(1);
            if (text.Length != 0)
            {
                try
                {
                    cultureInfo = new CultureInfo(text);
                }
                catch (ArgumentException)
                {
                    if (!throwOnError)
                    {
                        return null;
                    }
                    throw new XslTransformException(System.SR.Coll_UnsupportedLanguage, text);
                }
            }
        }
        else
        {
            if (!result.IsBaseOf(new Uri("http://www.w3.org/2004/10/xpath-functions/collation/codepoint")))
            {
                if (!throwOnError)
                {
                    return null;
                }
                throw new XslTransformException(System.SR.Coll_Unsupported, collationLiteral);
            }
            options.CompareOptions = CompareOptions.Ordinal;
        }
        string query = result.Query;
        string text2 = null;
        if (query.Length != 0)
        {
            string[] array = query.Substring(1).Split('&');
            foreach (string text3 in array)
            {
                string[] array2 = text3.Split('=');
                if (array2.Length != 2)
                {
                    if (!throwOnError)
                    {
                        return null;
                    }
                    throw new XslTransformException(System.SR.Coll_BadOptFormat, text3);
                }
                string text4 = array2[0].ToUpperInvariant();
                string text5 = array2[1].ToUpperInvariant();
                if (text4 == "SORT")
                {
                    text2 = text5;
                    continue;
                }
                int flag;
                switch (text4)
                {
                case "IGNORECASE":
                    flag = 1;
                    break;
                case "IGNORENONSPACE":
                    flag = 2;
                    break;
                case "IGNORESYMBOLS":
                    flag = 4;
                    break;
                case "IGNOREKANATYPE":
                    flag = 8;
                    break;
                case "IGNOREWIDTH":
                    flag = 16;
                    break;
                case "UPPERFIRST":
                    flag = 4096;
                    break;
                case "EMPTYGREATEST":
                    flag = 8192;
                    break;
                case "DESCENDINGORDER":
                    flag = 16384;
                    break;
                default:
                    if (!throwOnError)
                    {
                        return null;
                    }
                    throw new XslTransformException(System.SR.Coll_UnsupportedOpt, array2[0]);
                }
                switch (text5)
                {
                case "0":
                case "FALSE":
                    options.SetFlag(flag, value: false);
                    continue;
                case "1":
                case "TRUE":
                    options.SetFlag(flag, value: true);
                    continue;
                }
                if (!throwOnError)
                {
                    return null;
                }
                throw new XslTransformException(System.SR.Coll_UnsupportedOptVal, array2[0], array2[1]);
            }
        }
        if (options.UpperFirst && options.IgnoreCase)
        {
            options.UpperFirst = false;
        }
        if (options.Ordinal)
        {
            options.CompareOptions = CompareOptions.Ordinal;
            options.UpperFirst = false;
        }
        if (text2 != null && cultureInfo != null)
        {
            string name = cultureInfo.Name;
            switch (text2)
            {
            case "bopo":
                if (name == "zh-TW")
                {
                    cultureInfo = new CultureInfo("zh-TW_pronun");
                }
                break;
            case "strk":
                switch (name)
                {
                case "zh-CN":
                case "zh-HK":
                case "zh-SG":
                case "zh-MO":
                    cultureInfo = new CultureInfo(name);
                    break;
                }
                break;
            case "uni":
                if (name == "ja-JP" || name == "ko-KR")
                {
                    cultureInfo = new CultureInfo(name);
                }
                break;
            case "phn":
                if (name == "de-DE")
                {
                    cultureInfo = new CultureInfo("de-DE_phoneb");
                }
                break;
            case "tech":
                if (name == "hu-HU")
                {
                    cultureInfo = new CultureInfo("hu-HU_technl");
                }
                break;
            case "mod":
                if (name == "ka-GE")
                {
                    cultureInfo = new CultureInfo("ka-GE_modern");
                }
                break;
            default:
                if (!throwOnError)
                {
                    return null;
                }
                throw new XslTransformException(System.SR.Coll_UnsupportedSortOpt, text2);
            case "pron":
            case "dict":
            case "trad":
                break;
            }
        }
        return new XmlCollation(cultureInfo, options);
    }
References System.Xml.Xsl.Runtime.XmlCollation.XmlCollation(), System.array, System.Xml.Xsl.Runtime.XmlCollation.CodePointCollation, System.SR.Coll_BadOptFormat, System.SR.Coll_Unsupported, System.SR.Coll_UnsupportedLanguage, System.SR.Coll_UnsupportedOpt, System.SR.Coll_UnsupportedOptVal, System.SR.Coll_UnsupportedSortOpt, System.Xml.Dictionary, System.Uri.GetComponents(), System.Uri.IsBaseOf(), System.Uri.LocalPath, System.options, System.Uri.Query, System.text, System.Uri.TryCreate(), and System.value.