Terraria: TitleLinkButton.DrawTooltip
DrawTooltip()
void TitleLinkButton.DrawTooltip () inline private
     {
         Item fakeItem = _fakeItem;
         fakeItem.SetDefaults(0, noMatCheck: true);
         string textValue = Language.GetTextValue(TooltipTextKey);
         fakeItem.SetNameOverride(textValue);
         fakeItem.type = 1;
         fakeItem.scale = 0f;
         fakeItem.rare = 8;
         fakeItem.value = -1;
         Main.HoverItem = _fakeItem;
         Main.instance.MouseText("", 0, 0);
         Main.mouseText = true;
     }
References _fakeItem, Language.GetTextValue(), Main.HoverItem, Main.instance, Main.mouseText, Main.MouseText(), Item.rare, Item.scale, Item.SetDefaults(), Item.SetNameOverride(), TooltipTextKey, Item.type, and Item.value.
Referenced by Draw().