Terraria: System.Reflection.PortableExecutable.PEReader.GetPESectionBlock
GetPESectionBlock()
AbstractMemoryBlock System.Reflection.PortableExecutable.PEReader.GetPESectionBlock (int index) inline private
Definition at line 229 of file PEReader.cs.
    {
        MemoryBlockProvider pEImage = GetPEImage();
        if (_lazyPESectionBlocks == null)
        {
            Interlocked.CompareExchange(ref _lazyPESectionBlocks, new AbstractMemoryBlock[PEHeaders.SectionHeaders.Length], null);
        }
        AbstractMemoryBlock memoryBlock;
        if (IsLoadedImage)
        {
            memoryBlock = pEImage.GetMemoryBlock(PEHeaders.SectionHeaders[index].VirtualAddress, PEHeaders.SectionHeaders[index].VirtualSize);
        }
        else
        {
            int size = Math.Min(PEHeaders.SectionHeaders[index].VirtualSize, PEHeaders.SectionHeaders[index].SizeOfRawData);
            memoryBlock = pEImage.GetMemoryBlock(PEHeaders.SectionHeaders[index].PointerToRawData, size);
        }
        if (Interlocked.CompareExchange(ref _lazyPESectionBlocks[index], memoryBlock, null) != null)
        {
            memoryBlock.Dispose();
        }
        return _lazyPESectionBlocks[index];
    }
References System.Reflection.PortableExecutable.PEReader._lazyPESectionBlocks, System.Threading.Interlocked.CompareExchange(), System.Reflection.Internal.AbstractMemoryBlock.Dispose(), System.Reflection.Internal.MemoryBlockProvider.GetMemoryBlock(), System.Reflection.PortableExecutable.PEReader.GetPEImage(), System.index, System.Reflection.PortableExecutable.PEReader.IsLoadedImage, System.Math.Min(), and System.Reflection.PortableExecutable.PEHeaders.SectionHeaders.
Referenced by System.Reflection.PortableExecutable.PEReader.GetSectionData(), and System.Reflection.PortableExecutable.PEReader.GetSectionData().