Terraria: System.Reflection.PortableExecutable.PEReader.GetSectionData
GetSectionData() [1/2]
PEMemoryBlock System.Reflection.PortableExecutable.PEReader.GetSectionData (int relativeVirtualAddress) inline
Definition at line 263 of file PEReader.cs.
    {
        if (relativeVirtualAddress < 0)
        {
            Throw.ArgumentOutOfRange("relativeVirtualAddress");
        }
        int containingSectionIndex = PEHeaders.GetContainingSectionIndex(relativeVirtualAddress);
        if (containingSectionIndex < 0)
        {
            return default(PEMemoryBlock);
        }
        AbstractMemoryBlock pESectionBlock = GetPESectionBlock(containingSectionIndex);
        int num = relativeVirtualAddress - PEHeaders.SectionHeaders[containingSectionIndex].VirtualAddress;
        if (num > pESectionBlock.Size)
        {
            return default(PEMemoryBlock);
        }
        return new PEMemoryBlock(pESectionBlock, num);
    }
References System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.PortableExecutable.PEHeaders.GetContainingSectionIndex(), System.Reflection.PortableExecutable.PEReader.GetPESectionBlock(), System.Reflection.PortableExecutable.PEHeaders.SectionHeaders, and System.Reflection.Internal.AbstractMemoryBlock.Size.
Referenced by System.Reflection.Metadata.PEReaderExtensions.GetMethodBody().