Terraria: System.Reflection.PortableExecutable.PEReader.InitializePEHeaders
InitializePEHeaders()
void System.Reflection.PortableExecutable.PEReader.InitializePEHeaders () inline private
Definition at line 174 of file PEReader.cs.
    {
        StreamConstraints constraints;
        Stream stream = GetPEImage().GetStream(out constraints);
        PEHeaders value;
        if (constraints.GuardOpt != null)
        {
            lock (constraints.GuardOpt)
            {
                value = ReadPEHeadersNoLock(stream, constraints.ImageStart, constraints.ImageSize, IsLoadedImage);
            }
        }
        else
        {
            value = ReadPEHeadersNoLock(stream, constraints.ImageStart, constraints.ImageSize, IsLoadedImage);
        }
        Interlocked.CompareExchange(ref _lazyPEHeaders, value, null);
    }
References System.Reflection.PortableExecutable.PEReader._lazyPEHeaders, System.Threading.Interlocked.CompareExchange(), System.Reflection.PortableExecutable.PEReader.GetPEImage(), System.Reflection.Internal.MemoryBlockProvider.GetStream(), System.Reflection.Internal.StreamConstraints.GuardOpt, System.Reflection.Internal.StreamConstraints.ImageSize, System.Reflection.Internal.StreamConstraints.ImageStart, System.Reflection.PortableExecutable.PEReader.IsLoadedImage, System.Reflection.PortableExecutable.PEReader.ReadPEHeadersNoLock(), System.stream, and System.value.
Referenced by System.Reflection.PortableExecutable.PEReader.PEReader().