Terraria: System.Reflection.PortableExecutable.PEReader.DecodeCodeViewDebugDirectoryData
DecodeCodeViewDebugDirectoryData()
static CodeViewDebugDirectoryData System.Reflection.PortableExecutable.PEReader.DecodeCodeViewDebugDirectoryData (AbstractMemoryBlock block) inline static package
Definition at line 354 of file PEReader.cs.
    {
        BlobReader reader = block.GetReader();
        if (reader.ReadByte() != 82 || reader.ReadByte() != 83 || reader.ReadByte() != 68 || reader.ReadByte() != 83)
        {
            throw new BadImageFormatException(System.SR.UnexpectedCodeViewDataSignature);
        }
        Guid guid = reader.ReadGuid();
        int age = reader.ReadInt32();
        string path = reader.ReadUtf8NullTerminated();
        return new CodeViewDebugDirectoryData(guid, age, path);
    }
References System.Reflection.Internal.AbstractMemoryBlock.GetReader(), System.Reflection.Metadata.BlobReader.ReadByte(), System.Reflection.Metadata.BlobReader.ReadGuid(), System.Reflection.Metadata.BlobReader.ReadInt32(), System.Reflection.Metadata.BlobReader.ReadUtf8NullTerminated(), and System.SR.UnexpectedCodeViewDataSignature.
Referenced by System.Reflection.PortableExecutable.PEReader.ReadCodeViewDebugDirectoryData().