Terraria: System.Security.Cryptography.KeyBlobHelpers.ToUnsignedIntegerBytes
ToUnsignedIntegerBytes() [4/4]
static byte[] System.Security.Cryptography.KeyBlobHelpers.ToUnsignedIntegerBytes (this ReadOnlyMemory< byte > memory, int length) inline static package
Definition at line 5 of file KeyBlobHelpers.cs.
    {
        if (memory.Length == length)
        {
            return memory.ToArray();
        }
        ReadOnlySpan<byte> span = memory.Span;
        if (memory.Length == length + 1 && span[0] == 0)
        {
            return span.Slice(1).ToArray();
        }
        if (span.Length > length)
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        byte[] array = new byte[length];
        span.CopyTo(array.AsSpan(length - span.Length));
        return array;
    }
References System.array, System.ReadOnlySpan< T >.CopyTo(), System.SR.Cryptography_Der_Invalid_Encoding, System.length, System.ReadOnlyMemory< T >.Length, System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), System.ReadOnlyMemory< T >.Span, and System.ReadOnlyMemory< T >.ToArray().