Terraria: System.Reflection.PortableExecutable.PEReader.GetSectionData
GetSectionData() [2/2]
PEMemoryBlock System.Reflection.PortableExecutable.PEReader.GetSectionData (string sectionName) inline
Definition at line 283 of file PEReader.cs.
    {
        if (sectionName == null)
        {
            Throw.ArgumentNull("sectionName");
        }
        int num = PEHeaders.IndexOfSection(sectionName);
        if (num < 0)
        {
            return default(PEMemoryBlock);
        }
        return new PEMemoryBlock(GetPESectionBlock(num));
    }
References System.Reflection.Throw.ArgumentNull(), System.Reflection.PortableExecutable.PEReader.GetPESectionBlock(), and System.Reflection.PortableExecutable.PEHeaders.IndexOfSection().