Terraria: System.Reflection.PortableExecutable.PEReader.GetDebugDirectoryEntryDataBlock
GetDebugDirectoryEntryDataBlock()
AbstractMemoryBlock System.Reflection.PortableExecutable.PEReader.GetDebugDirectoryEntryDataBlock (DebugDirectoryEntry entry) inline private
Definition at line 338 of file PEReader.cs.
    {
        int start = (IsLoadedImage ? entry.DataRelativeVirtualAddress : entry.DataPointer);
        return GetPEImage().GetMemoryBlock(start, entry.DataSize);
    }
References System.Reflection.PortableExecutable.DebugDirectoryEntry.DataPointer, System.Reflection.PortableExecutable.DebugDirectoryEntry.DataSize, System.Reflection.Internal.MemoryBlockProvider.GetMemoryBlock(), System.Reflection.PortableExecutable.PEReader.GetPEImage(), System.Reflection.PortableExecutable.PEReader.IsLoadedImage, and System.start.
Referenced by System.Reflection.PortableExecutable.PEReader.ReadCodeViewDebugDirectoryData(), System.Reflection.PortableExecutable.PEReader.ReadEmbeddedPortablePdbDebugDirectoryData(), and System.Reflection.PortableExecutable.PEReader.ReadPdbChecksumDebugDirectoryData().