Terraria: System.Reflection.PortableExecutable.PEReader.PEReader
PEReader() [5/6]
unsafe System.Reflection.PortableExecutable.PEReader.PEReader (Stream peStream, PEStreamOptions options, int size) inline
Definition at line 80 of file PEReader.cs.
    {
        if (peStream == null)
        {
            throw new ArgumentNullException("peStream");
        }
        if (!peStream.CanRead || !peStream.CanSeek)
        {
            throw new ArgumentException(System.SR.StreamMustSupportReadAndSeek, "peStream");
        }
        if (!options.IsValid())
        {
            throw new ArgumentOutOfRangeException("options");
        }
        IsLoadedImage = (options & PEStreamOptions.IsLoadedImage) != 0;
        long position = peStream.Position;
        int andValidateSize = StreamExtensions.GetAndValidateSize(peStream, size, "peStream");
        bool flag = true;
        try
        {
            bool isFileStream = FileStreamReadLightUp.IsFileStream(peStream);
            if ((options & (PEStreamOptions.PrefetchMetadata | PEStreamOptions.PrefetchEntireImage)) == 0)
            {
                _peImage = new StreamMemoryBlockProvider(peStream, position, andValidateSize, isFileStream, (options & PEStreamOptions.LeaveOpen) != 0);
                flag = false;
            }
            else if ((options & PEStreamOptions.PrefetchEntireImage) != 0)
            {
                NativeHeapMemoryBlock nativeHeapMemoryBlock = (NativeHeapMemoryBlock)(_lazyImageBlock = StreamMemoryBlockProvider.ReadMemoryBlockNoLock(peStream, isFileStream, position, andValidateSize));
                _peImage = new ExternalMemoryBlockProvider(nativeHeapMemoryBlock.Pointer, nativeHeapMemoryBlock.Size);
                if ((options & PEStreamOptions.PrefetchMetadata) != 0)
                {
                    InitializePEHeaders();
                }
            }
            else
            {
                _lazyPEHeaders = new PEHeaders(peStream);
                _lazyMetadataBlock = StreamMemoryBlockProvider.ReadMemoryBlockNoLock(peStream, isFileStream, _lazyPEHeaders.MetadataStartOffset, _lazyPEHeaders.MetadataSize);
            }
        }
        finally
        {
            if (flag && (options & PEStreamOptions.LeaveOpen) == 0)
            {
                peStream.Dispose();
            }
        }
    }
References System.Reflection.PortableExecutable.PEReader._lazyImageBlock, System.Reflection.PortableExecutable.PEReader._lazyMetadataBlock, System.Reflection.PortableExecutable.PEReader._lazyPEHeaders, System.Reflection.PortableExecutable.PEReader._peImage, System.IO.Stream.CanRead, System.IO.Stream.CanSeek, System.IO.Stream.Dispose(), System.Reflection.Internal.StreamExtensions.GetAndValidateSize(), System.Reflection.PortableExecutable.PEReader.InitializePEHeaders(), System.Reflection.Internal.FileStreamReadLightUp.IsFileStream(), System.Reflection.PortableExecutable.PEReader.IsLoadedImage, System.Reflection.PortableExecutable.PEHeaders.MetadataSize, System.Reflection.PortableExecutable.PEHeaders.MetadataStartOffset, System.options, System.Reflection.PortableExecutable.PEReader.PEHeaders, System.Reflection.Internal.NativeHeapMemoryBlock.Pointer, System.IO.Stream.Position, System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(), System.Reflection.Internal.NativeHeapMemoryBlock.Size, and System.SR.StreamMustSupportReadAndSeek.