Terraria: System.Reflection.PortableExecutable.PEReader.ReadDebugDirectoryEntries
ReadDebugDirectoryEntries()
static ImmutableArray< DebugDirectoryEntry > System.Reflection.PortableExecutable.PEReader.ReadDebugDirectoryEntries (BlobReader reader) inline static package
Definition at line 316 of file PEReader.cs.
    {
        int num = reader.Length / 28;
        ImmutableArray<DebugDirectoryEntry>.Builder builder = ImmutableArray.CreateBuilder<DebugDirectoryEntry>(num);
        for (int i = 0; i < num; i++)
        {
            if (reader.ReadInt32() != 0)
            {
                throw new BadImageFormatException(System.SR.InvalidDebugDirectoryEntryCharacteristics);
            }
            uint stamp = reader.ReadUInt32();
            ushort majorVersion = reader.ReadUInt16();
            ushort minorVersion = reader.ReadUInt16();
            DebugDirectoryEntryType type = (DebugDirectoryEntryType)reader.ReadInt32();
            int dataSize = reader.ReadInt32();
            int dataRelativeVirtualAddress = reader.ReadInt32();
            int dataPointer = reader.ReadInt32();
            builder.Add(new DebugDirectoryEntry(stamp, majorVersion, minorVersion, type, dataSize, dataRelativeVirtualAddress, dataPointer));
        }
        return builder.MoveToImmutable();
    }
References System.SR.InvalidDebugDirectoryEntryCharacteristics, System.Reflection.Metadata.BlobReader.ReadInt32(), System.Reflection.Metadata.BlobReader.ReadUInt16(), System.Reflection.Metadata.BlobReader.ReadUInt32(), and System.type.
Referenced by System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory().