Terraria: System.Reflection.PortableExecutable.PEReader.DecodePdbChecksumDebugDirectoryData
DecodePdbChecksumDebugDirectoryData()
static PdbChecksumDebugDirectoryData System.Reflection.PortableExecutable.PEReader.DecodePdbChecksumDebugDirectoryData (AbstractMemoryBlock block) inline static package
Definition at line 377 of file PEReader.cs.
    {
        BlobReader reader = block.GetReader();
        string text = reader.ReadUtf8NullTerminated();
        byte[] array = reader.ReadBytes(reader.RemainingBytes);
        if (text.Length == 0 || array.Length == 0)
        {
            throw new BadImageFormatException(System.SR.InvalidPdbChecksumDataFormat);
        }
        return new PdbChecksumDebugDirectoryData(text, ImmutableByteArrayInterop.DangerousCreateFromUnderlyingArray(ref array));
    }
References System.array, System.Reflection.Internal.ImmutableByteArrayInterop.DangerousCreateFromUnderlyingArray(), System.Reflection.Internal.AbstractMemoryBlock.GetReader(), System.SR.InvalidPdbChecksumDataFormat, System.Reflection.Metadata.BlobReader.ReadBytes(), System.Reflection.Metadata.BlobReader.ReadUtf8NullTerminated(), System.Reflection.Metadata.BlobReader.RemainingBytes, and System.text.
Referenced by System.Reflection.PortableExecutable.PEReader.ReadPdbChecksumDebugDirectoryData().