Terraria: System.Reflection.PortableExecutable.PEReader.TryOpenAssociatedPortablePdb
TryOpenAssociatedPortablePdb()
bool System.Reflection.PortableExecutable.PEReader.TryOpenAssociatedPortablePdb (string peImagePath, Func< string, Stream?> pdbFileStreamProvider, out MetadataReaderProvider? pdbReaderProvider, out string? pdbPath) inline
Definition at line 389 of file PEReader.cs.
    {
        if (peImagePath == null)
        {
            Throw.ArgumentNull("peImagePath");
        }
        if (pdbFileStreamProvider == null)
        {
            Throw.ArgumentNull("pdbFileStreamProvider");
        }
        pdbReaderProvider = null;
        pdbPath = null;
        string directoryName;
        try
        {
            directoryName = Path.GetDirectoryName(peImagePath);
        }
        catch (Exception ex)
        {
            throw new ArgumentException(ex.Message, "peImagePath");
        }
        Exception errorToReport = null;
        ImmutableArray<DebugDirectoryEntry> collection = ReadDebugDirectory();
        DebugDirectoryEntry codeViewEntry = collection.FirstOrDefault((DebugDirectoryEntry e) => e.IsPortableCodeView);
        if (codeViewEntry.DataSize != 0 && TryOpenCodeViewPortablePdb(codeViewEntry, directoryName, pdbFileStreamProvider, out pdbReaderProvider, out pdbPath, ref errorToReport))
        {
            return true;
        }
        DebugDirectoryEntry embeddedPdbEntry = collection.FirstOrDefault((DebugDirectoryEntry e) => e.Type == DebugDirectoryEntryType.EmbeddedPortablePdb);
        if (embeddedPdbEntry.DataSize != 0)
        {
            bool openedEmbeddedPdb = false;
            pdbReaderProvider = null;
            TryOpenEmbeddedPortablePdb(embeddedPdbEntry, ref openedEmbeddedPdb, ref pdbReaderProvider, ref errorToReport);
            if (openedEmbeddedPdb)
            {
                return true;
            }
        }
        if (errorToReport != null)
        {
            ExceptionDispatchInfo.Capture(errorToReport).Throw();
        }
        return false;
    }
References System.Reflection.Throw.ArgumentNull(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.collection, System.Reflection.PortableExecutable.DebugDirectoryEntry.DataSize, System.IO.Path.GetDirectoryName(), System.Reflection.PortableExecutable.DebugDirectoryEntry.IsPortableCodeView, System.Exception.Message, System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory(), System.Reflection.PortableExecutable.PEReader.TryOpenCodeViewPortablePdb(), System.Reflection.PortableExecutable.PEReader.TryOpenEmbeddedPortablePdb(), and System.Reflection.PortableExecutable.DebugDirectoryEntry.Type.