Terraria: System.Reflection.PortableExecutable.PEReader.DecodeEmbeddedPortablePdbDebugDirectoryData
DecodeEmbeddedPortablePdbDebugDirectoryData()
static unsafe NativeHeapMemoryBlock System.Reflection.PortableExecutable.PEReader.DecodeEmbeddedPortablePdbDebugDirectoryData (AbstractMemoryBlock block) inline static package
Definition at line 566 of file PEReader.cs.
    {
        BlobReader reader = block.GetReader();
        if (reader.ReadUInt32() != 1111773261)
        {
            throw new BadImageFormatException(System.SR.UnexpectedEmbeddedPortablePdbDataSignature);
        }
        int num = reader.ReadInt32();
        NativeHeapMemoryBlock nativeHeapMemoryBlock;
        try
        {
            nativeHeapMemoryBlock = new NativeHeapMemoryBlock(num);
        }
        catch
        {
            throw new BadImageFormatException(System.SR.DataTooBig);
        }
        bool flag = false;
        try
        {
            ReadOnlyUnmanagedMemoryStream stream = new ReadOnlyUnmanagedMemoryStream(reader.CurrentPointer, reader.RemainingBytes);
            DeflateStream deflateStream = new DeflateStream(stream, CompressionMode.Decompress, leaveOpen: true);
            if (num > 0)
            {
                int num2;
                try
                {
                    num2 = deflateStream.TryReadAll(new Span<byte>(nativeHeapMemoryBlock.Pointer, nativeHeapMemoryBlock.Size));
                }
                catch (Exception ex)
                {
                    throw new BadImageFormatException(ex.Message, ex.InnerException);
                }
                if (num2 != nativeHeapMemoryBlock.Size)
                {
                    throw new BadImageFormatException(System.SR.SizeMismatch);
                }
            }
            if (deflateStream.ReadByte() != -1)
            {
                throw new BadImageFormatException(System.SR.SizeMismatch);
            }
            flag = true;
        }
        finally
        {
            if (!flag)
            {
                nativeHeapMemoryBlock.Dispose();
            }
        }
        return nativeHeapMemoryBlock;
    }
References System.Reflection.Metadata.BlobReader.CurrentPointer, System.SR.DataTooBig, System.Reflection.Internal.NativeHeapMemoryBlock.Dispose(), System.Reflection.Internal.AbstractMemoryBlock.GetReader(), System.Exception.InnerException, System.Exception.Message, System.Reflection.Internal.NativeHeapMemoryBlock.Pointer, System.IO.Compression.DeflateStream.ReadByte(), System.Reflection.Metadata.BlobReader.ReadInt32(), System.Reflection.Metadata.BlobReader.ReadUInt32(), System.Reflection.Metadata.BlobReader.RemainingBytes, System.Reflection.Internal.NativeHeapMemoryBlock.Size, System.SR.SizeMismatch, System.stream, and System.SR.UnexpectedEmbeddedPortablePdbDataSignature.
Referenced by System.Reflection.PortableExecutable.PEReader.ReadEmbeddedPortablePdbDebugDirectoryData().