Terraria: System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory
ReadDebugDirectory()
ImmutableArray< DebugDirectoryEntry > System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory () inline
Definition at line 297 of file PEReader.cs.
    {
        DirectoryEntry debugTableDirectory = PEHeaders.PEHeader.DebugTableDirectory;
        if (debugTableDirectory.Size == 0)
        {
            return ImmutableArray<DebugDirectoryEntry>.Empty;
        }
        if (!PEHeaders.TryGetDirectoryOffset(debugTableDirectory, out var offset))
        {
            throw new BadImageFormatException(System.SR.InvalidDirectoryRVA);
        }
        if (debugTableDirectory.Size % 28 != 0)
        {
            throw new BadImageFormatException(System.SR.InvalidDirectorySize);
        }
        using AbstractMemoryBlock abstractMemoryBlock = GetPEImage().GetMemoryBlock(offset, debugTableDirectory.Size);
        return ReadDebugDirectoryEntries(abstractMemoryBlock.GetReader());
    }
References System.Reflection.PortableExecutable.PEHeader.DebugTableDirectory, System.Collections.Immutable.ImmutableArray< T >.Empty, System.Reflection.Internal.MemoryBlockProvider.GetMemoryBlock(), System.Reflection.PortableExecutable.PEReader.GetPEImage(), System.SR.InvalidDirectoryRVA, System.SR.InvalidDirectorySize, System.offset, System.Reflection.PortableExecutable.PEHeaders.PEHeader, System.Reflection.PortableExecutable.PEReader.ReadDebugDirectoryEntries(), System.Reflection.PortableExecutable.DirectoryEntry.Size, and System.Reflection.PortableExecutable.PEHeaders.TryGetDirectoryOffset().
Referenced by System.Reflection.PortableExecutable.PEReader.TryOpenAssociatedPortablePdb().