Terraria: System.Reflection.PortableExecutable.PEReader.TryOpenCodeViewPortablePdb
TryOpenCodeViewPortablePdb()
bool System.Reflection.PortableExecutable.PEReader.TryOpenCodeViewPortablePdb (DebugDirectoryEntry codeViewEntry, string peImageDirectory, Func< string, Stream > pdbFileStreamProvider, out MetadataReaderProvider provider, out string pdbPath, ref Exception errorToReport) inline private
Definition at line 435 of file PEReader.cs.
    {
        pdbPath = null;
        provider = null;
        CodeViewDebugDirectoryData codeViewDebugDirectoryData;
        try
        {
            codeViewDebugDirectoryData = ReadCodeViewDebugDirectoryData(codeViewEntry);
        }
        catch (Exception ex) when (ex is BadImageFormatException || ex is IOException)
        {
            _ = errorToReport;
            if (ex == null)
            {
            }
            errorToReport = ex;
            return false;
        }
        BlobContentId id = new BlobContentId(codeViewDebugDirectoryData.Guid, codeViewEntry.Stamp);
        string text = PathUtilities.CombinePathWithRelativePath(peImageDirectory, PathUtilities.GetFileName(codeViewDebugDirectoryData.Path));
        if (TryOpenPortablePdbFile(text, id, pdbFileStreamProvider, out provider, ref errorToReport))
        {
            pdbPath = text;
            return true;
        }
        return false;
    }
References System.Reflection.Metadata.PathUtilities.CombinePathWithRelativePath(), System.Reflection.Metadata.PathUtilities.GetFileName(), System.Reflection.PortableExecutable.CodeViewDebugDirectoryData.Guid, System.Reflection.PortableExecutable.CodeViewDebugDirectoryData.Path, System.Reflection.PortableExecutable.PEReader.ReadCodeViewDebugDirectoryData(), System.Reflection.PortableExecutable.DebugDirectoryEntry.Stamp, System.text, and System.Reflection.PortableExecutable.PEReader.TryOpenPortablePdbFile().
Referenced by System.Reflection.PortableExecutable.PEReader.TryOpenAssociatedPortablePdb().