Terraria: System.Reflection.PortableExecutable.PEReader.TryOpenPortablePdbFile
TryOpenPortablePdbFile()
bool System.Reflection.PortableExecutable.PEReader.TryOpenPortablePdbFile (string path, BlobContentId id, Func< string, Stream > pdbFileStreamProvider, out MetadataReaderProvider provider, ref Exception errorToReport) inline private
Definition at line 463 of file PEReader.cs.
    {
        provider = null;
        MetadataReaderProvider metadataReaderProvider = null;
        try
        {
            Stream stream;
            try
            {
                stream = pdbFileStreamProvider(path);
            }
            catch (FileNotFoundException)
            {
                stream = null;
            }
            if (stream == null)
            {
                return false;
            }
            if (!stream.CanRead || !stream.CanSeek)
            {
                throw new InvalidOperationException(System.SR.StreamMustSupportReadAndSeek);
            }
            metadataReaderProvider = MetadataReaderProvider.FromPortablePdbStream(stream);
            if (new BlobContentId(metadataReaderProvider.GetMetadataReader().DebugMetadataHeader.Id) != id)
            {
                return false;
            }
            provider = metadataReaderProvider;
            return true;
        }
        catch (Exception ex2) when (ex2 is BadImageFormatException || ex2 is IOException)
        {
            _ = errorToReport;
            if (ex2 == null)
            {
            }
            errorToReport = ex2;
            return false;
        }
        finally
        {
            if (provider == null)
            {
                metadataReaderProvider?.Dispose();
            }
        }
    }
References System.Reflection.Metadata.MetadataReader.DebugMetadataHeader, System.Reflection.Metadata.MetadataReaderProvider.Dispose(), System.Reflection.Metadata.MetadataReaderProvider.FromPortablePdbStream(), System.Reflection.Metadata.MetadataReaderProvider.GetMetadataReader(), System.Reflection.Metadata.DebugMetadataHeader.Id, System.stream, and System.SR.StreamMustSupportReadAndSeek.
Referenced by System.Reflection.PortableExecutable.PEReader.TryOpenCodeViewPortablePdb().