Terraria: System.Reflection.PortableExecutable.PEReader.ValidateEmbeddedPortablePdbVersion
ValidateEmbeddedPortablePdbVersion()
static void System.Reflection.PortableExecutable.PEReader.ValidateEmbeddedPortablePdbVersion (DebugDirectoryEntry entry) inline static package
Definition at line 552 of file PEReader.cs.
    {
        ushort majorVersion = entry.MajorVersion;
        if (majorVersion < 256)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.UnsupportedFormatVersion, PortablePdbVersions.Format(majorVersion)));
        }
        ushort minorVersion = entry.MinorVersion;
        if (minorVersion != 256)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.UnsupportedFormatVersion, PortablePdbVersions.Format(minorVersion)));
        }
    }
References System.SR.Format(), System.Reflection.Metadata.PortablePdbVersions.Format(), System.Reflection.PortableExecutable.DebugDirectoryEntry.MajorVersion, System.Reflection.PortableExecutable.DebugDirectoryEntry.MinorVersion, and System.SR.UnsupportedFormatVersion.
Referenced by System.Reflection.PortableExecutable.PEReader.ReadEmbeddedPortablePdbDebugDirectoryData().