Terraria: Terraria.GameContent.Creative.CreativePowerManager.Instance
Instance
readonly CreativePowerManager Terraria.GameContent.Creative.CreativePowerManager.Instance = new CreativePowerManager() static
Definition at line 19 of file CreativePowerManager.cs.
Referenced by Terraria.WorldGen.clearWorld(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateMainPowerStrip(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreatePersonalPowerStrip(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateSubcategoryButton< T >(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateTimePowerStrip(), Terraria.GameContent.UI.States.UICreativePowersMenu.CreateWeatherPowerStrip(), Terraria.Projectile.Damage(), Terraria.GameContent.NetModules.NetCreativePowerPermissionsModule.Deserialize(), Terraria.GameContent.NetModules.NetCreativePowersModule.Deserialize(), Terraria.Player.Deserialize(), Terraria.MessageBuffer.GetData(), Terraria.Player.GetItemGrabRange(), Terraria.WorldGen.GetWorldUpdateRate(), Terraria.Player.GrabItems(), Terraria.GameContent.Creative.CreativePowerManager.Initialize(), Terraria.IO.WorldFile.LoadCreativePowers(), Terraria.Player.OpenBossBag(), Terraria.GameContent.UI.States.UICreativePowersMenu.PersonalCategoryButtonClick(), Terraria.Player.ResetEffects(), Terraria.IO.WorldFile.SaveCreativePowers(), Terraria.NPC.ScaleStats(), Terraria.Player.Serialize(), Terraria.Player.SetPlayerDataToOutOfClassFields(), Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty(), Terraria.NPC.SlimeRainSpawns(), Terraria.NPC.SpawnNPC(), Terraria.GameContent.UI.States.UICreativePowersMenu.TimeCategoryButtonClick(), Terraria.GameContent.Creative.CreativePowerManager.TryListingPermissionsFrom(), Terraria.Player.Update(), Terraria.Main.UpdateCreativeGameModeOverride(), Terraria.Main.UpdateTime(), Terraria.Main.UpdateTimeRate(), Terraria.Main.UpdateWeather(), Terraria.WorldGen.UpdateWorld(), Terraria.IO.WorldFile.ValidateWorld(), and Terraria.GameContent.UI.States.UICreativePowersMenu.WeatherCategoryButtonClick().