Terraria: GolemHeadProgressBar.ValidateAndCollectNecessaryInfo
ValidateAndCollectNecessaryInfo()
bool GolemHeadProgressBar.ValidateAndCollectNecessaryInfo (ref BigProgressBarInfo info) inline
Implements IBigProgressBar.
     {
         if (info.npcIndexToAimAt < 0 || info.npcIndexToAimAt > 200)
         {
             return false;
         }
         NPC nPC = Main.npc[info.npcIndexToAimAt];
         if (!nPC.active && !TryFindingAnotherGolemPiece(ref info))
         {
             return false;
         }
         int num = 0;
         _referenceDummy.SetDefaults(245, nPC.GetMatchingSpawnParams());
         num += _referenceDummy.lifeMax;
         _referenceDummy.SetDefaults(246, nPC.GetMatchingSpawnParams());
         num += _referenceDummy.lifeMax;
         float num2 = 0f;
         for (int i = 0; i < 200; i++)
         {
             NPC nPC2 = Main.npc[i];
             if (nPC2.active && ValidIds.Contains(nPC2.type))
             {
                 num2 += (float)nPC2.life;
             }
         }
         _cache.SetLife(num2, num);
         return true;
     }
References _cache, _referenceDummy, Entity.active, NPC.GetMatchingSpawnParams(), NPC.life, NPC.lifeMax, Main.npc, NPC.SetDefaults(), BigProgressBarCache.SetLife(), TryFindingAnotherGolemPiece(), NPC.type, and ValidIds.