Terraria: ReLogic.Threading.FastParallel.For
For()
static void ReLogic.Threading.FastParallel.For (int fromInclusive, int toExclusive, ParallelForAction callback, object context = null) inline static
Definition at line 52 of file FastParallel.cs.
    {
        int num = toExclusive - fromInclusive;
        if (num == 0)
        {
            return;
        }
        int num2 = Math.Min(Math.Max(1, Environment.ProcessorCount + 1 - 1 - 1), num);
        if (ForceTasksOnCallingThread)
        {
            num2 = 1;
        }
        int num3 = num / num2;
        int num4 = num % num2;
        CountdownEvent countdownEvent = new CountdownEvent(num2);
        int num5 = toExclusive;
        for (int num6 = num2 - 1; num6 >= 0; num6--)
        {
            int num7 = num3;
            if (num6 < num4)
            {
                num7++;
            }
            num5 -= num7;
            int num8 = num5;
            int toExclusive2 = num8 + num7;
            RangeTask rangeTask = new RangeTask(callback, num8, toExclusive2, context, countdownEvent);
            if (num6 < 1)
            {
                InvokeTask(rangeTask);
            }
            else
            {
                ThreadPool.QueueUserWorkItem(InvokeTask, rangeTask);
            }
        }
        if (countdownEvent.Wait(10000))
        {
            return;
        }
        ThreadPool.GetAvailableThreads(out var workerThreads, out var _);
        throw new Exception($"Fatal Deadlock in FastParallelFor. pending: {ThreadPool.PendingWorkItemCount}. avail: {workerThreads}");
    }
References ReLogic.Threading.FastParallel.ForceTasksOnCallingThread, System.Threading.ThreadPool.GetAvailableThreads(), ReLogic.Threading.FastParallel.InvokeTask(), System.Math.Max(), System.Math.Min(), System.Environment.ProcessorCount, System.Threading.ThreadPool.QueueUserWorkItem(), and System.Threading.CountdownEvent.Wait().
Referenced by Terraria.Graphics.Light.LightMap.BlurPass(), Terraria.Graphics.Light.LegacyLighting.DoColors(), Terraria.Graphics.Light.TileLightScanner.ExportTo(), and Terraria.Graphics.Light.LightingEngine.ExportToMiniMap().