Terraria: System.Security.Principal.WindowsIdentity.DuplicateAccessToken
DuplicateAccessToken() [1/2]
static SafeAccessTokenHandle System.Security.Principal.WindowsIdentity.DuplicateAccessToken (IntPtr accessToken) inline static private
Definition at line 451 of file WindowsIdentity.cs.
    {
        if (accessToken == IntPtr.Zero)
        {
            throw new ArgumentException(System.SR.Argument_TokenZero);
        }
        uint ReturnLength = 4u;
        if (!global::Interop.Advapi32.GetTokenInformation(accessToken, 8u, IntPtr.Zero, 0u, out ReturnLength) && Marshal.GetLastWin32Error() == 6)
        {
            throw new ArgumentException(System.SR.Argument_InvalidImpersonationToken);
        }
        SafeAccessTokenHandle lpTargetHandle = SafeAccessTokenHandle.InvalidHandle;
        IntPtr currentProcess = global::Interop.Kernel32.GetCurrentProcess();
        if (!global::Interop.Kernel32.DuplicateHandle(currentProcess, accessToken, currentProcess, ref lpTargetHandle, 0u, bInheritHandle: true, 2u))
        {
            throw new SecurityException(new Win32Exception().Message);
        }
        return lpTargetHandle;
    }
References System.SR.Argument_InvalidImpersonationToken, System.SR.Argument_TokenZero, System.Runtime.Serialization.Dictionary, System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Microsoft.Win32.SafeHandles.SafeAccessTokenHandle.InvalidHandle, and System.IntPtr.Zero.
Referenced by System.Security.Principal.WindowsIdentity.CreateFromToken(), System.Security.Principal.WindowsIdentity.DuplicateAccessToken(), and System.Security.Principal.WindowsIdentity.RunImpersonatedInternal().