Terraria: System.Security.Principal.WindowsIdentity.AddGroupSidClaims
AddGroupSidClaims()
void System.Security.Principal.WindowsIdentity.AddGroupSidClaims (List< Claim > instanceClaims) inline private
Definition at line 830 of file WindowsIdentity.cs.
    {
        if (_safeTokenHandle.IsInvalid)
        {
            return;
        }
        SafeLocalAllocHandle safeLocalAllocHandle = null;
        SafeLocalAllocHandle safeLocalAllocHandle2 = null;
        try
        {
            safeLocalAllocHandle2 = GetTokenInformation(_safeTokenHandle, TokenInformationClass.TokenPrimaryGroup);
            SecurityIdentifier securityIdentifier = new SecurityIdentifier(Marshal.PtrToStructure<global::Interop.TOKEN_PRIMARY_GROUP>(safeLocalAllocHandle2.DangerousGetHandle()).PrimaryGroup);
            bool flag = false;
            safeLocalAllocHandle = GetTokenInformation(_safeTokenHandle, TokenInformationClass.TokenGroups);
            int num = Marshal.ReadInt32(safeLocalAllocHandle.DangerousGetHandle());
            IntPtr intPtr = new IntPtr((long)safeLocalAllocHandle.DangerousGetHandle() + (long)Marshal.OffsetOf<global::Interop.TOKEN_GROUPS>("Groups"));
            for (int i = 0; i < num; i++)
            {
                global::Interop.SID_AND_ATTRIBUTES sID_AND_ATTRIBUTES = Marshal.PtrToStructure<global::Interop.SID_AND_ATTRIBUTES>(intPtr);
                uint num2 = 3221225492u;
                SecurityIdentifier securityIdentifier2 = new SecurityIdentifier(sID_AND_ATTRIBUTES.Sid);
                if ((sID_AND_ATTRIBUTES.Attributes & num2) == 4)
                {
                    Claim claim;
                    if (!flag && StringComparer.Ordinal.Equals(securityIdentifier2.Value, securityIdentifier.Value))
                    {
                        claim = new Claim("http://schemas.microsoft.com/ws/2008/06/identity/claims/primarygroupsid", securityIdentifier2.Value, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                        claim.Properties.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority", securityIdentifier2.IdentifierAuthority.ToString());
                        instanceClaims.Add(claim);
                        flag = true;
                    }
                    claim = new Claim("http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid", securityIdentifier2.Value, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                    claim.Properties.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority", securityIdentifier2.IdentifierAuthority.ToString());
                    instanceClaims.Add(claim);
                }
                else if ((sID_AND_ATTRIBUTES.Attributes & num2) == 16)
                {
                    Claim claim;
                    if (!flag && StringComparer.Ordinal.Equals(securityIdentifier2.Value, securityIdentifier.Value))
                    {
                        claim = new Claim("http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlyprimarygroupsid", securityIdentifier2.Value, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                        claim.Properties.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority", securityIdentifier2.IdentifierAuthority.ToString());
                        instanceClaims.Add(claim);
                        flag = true;
                    }
                    claim = new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/denyonlysid", securityIdentifier2.Value, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                    claim.Properties.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority", securityIdentifier2.IdentifierAuthority.ToString());
                    instanceClaims.Add(claim);
                }
                intPtr = new IntPtr((long)intPtr + Marshal.SizeOf<global::Interop.SID_AND_ATTRIBUTES>());
            }
        }
        finally
        {
            safeLocalAllocHandle?.Dispose();
            safeLocalAllocHandle2?.Dispose();
        }
    }
References System.Security.Principal.WindowsIdentity._issuerName, System.Security.Principal.WindowsIdentity._safeTokenHandle, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, System.Security.Principal.WindowsIdentity.GetTokenInformation(), Microsoft.Win32.SafeHandles.SafeAccessTokenHandle.IsInvalid, System.Runtime.InteropServices.Marshal.OffsetOf(), System.StringComparer.Ordinal, System.Runtime.InteropServices.Marshal.PtrToStructure(), System.Runtime.InteropServices.Marshal.ReadInt32(), and System.Runtime.InteropServices.Marshal.SizeOf().
Referenced by System.Security.Principal.WindowsIdentity.InitializeClaims().