Terraria: System.Security.Principal.WindowsIdentity.GetTokenInformation
GetTokenInformation()
static SafeLocalAllocHandle System.Security.Principal.WindowsIdentity.GetTokenInformation (SafeAccessTokenHandle tokenHandle, TokenInformationClass tokenInformationClass, bool nullOnInvalidParam = false) inline static private
Definition at line 760 of file WindowsIdentity.cs.
    {
        SafeLocalAllocHandle invalidHandle = SafeLocalAllocHandle.InvalidHandle;
        uint ReturnLength = 4u;
        bool tokenInformation = global::Interop.Advapi32.GetTokenInformation(tokenHandle, (uint)tokenInformationClass, invalidHandle, 0u, out ReturnLength);
        int lastWin32Error = Marshal.GetLastWin32Error();
        switch (lastWin32Error)
        {
        case 24:
        case 122:
            invalidHandle.Dispose();
            invalidHandle = SafeLocalAllocHandle.LocalAlloc(checked((int)ReturnLength));
            if (!global::Interop.Advapi32.GetTokenInformation(tokenHandle, (uint)tokenInformationClass, invalidHandle, ReturnLength, out ReturnLength))
            {
                throw new SecurityException(new Win32Exception().Message);
            }
            return invalidHandle;
        case 6:
            throw new ArgumentException(System.SR.Argument_InvalidImpersonationToken);
        case 87:
            if (nullOnInvalidParam)
            {
                invalidHandle.Dispose();
                return null;
            }
            break;
        }
        throw new SecurityException(new Win32Exception(lastWin32Error).Message);
    }
References System.SR.Argument_InvalidImpersonationToken, System.Runtime.Serialization.Dictionary, System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.InvalidHandle, and Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc().
Referenced by System.Security.Principal.WindowsIdentity.AddDeviceGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddPrimarySidClaim(), System.Security.Principal.WindowsIdentity.AddTokenClaims(), System.Security.Principal.WindowsIdentity.GetLogonAuthId(), and System.Security.Principal.WindowsIdentity.GetTokenInformation< T >().