Terraria: Terraria.Audio.ActiveSound.PlayLooped
PlayLooped()
void Terraria.Audio.ActiveSound.PlayLooped (LoopedPlayCondition condition) inline private
Definition at line 67 of file ActiveSound.cs.
    {
        SoundEffectInstance soundEffectInstance = Style.GetRandomSound().CreateInstance();
        soundEffectInstance.Pitch += Style.GetRandomPitch();
        Pitch = soundEffectInstance.Pitch;
        soundEffectInstance.IsLooped = true;
        Condition = condition;
        soundEffectInstance.Play();
        SoundInstanceGarbageCollector.Track(soundEffectInstance);
        Sound = soundEffectInstance;
        Update();
    }
References Terraria.Audio.ActiveSound.Condition, Terraria.Audio.SoundStyle.GetRandomPitch(), Terraria.Audio.SoundStyle.GetRandomSound(), Terraria.Audio.ActiveSound.Pitch, Terraria.Audio.ActiveSound.Sound, Terraria.Audio.ActiveSound.Style, Terraria.Audio.SoundInstanceGarbageCollector.Track(), and Terraria.Audio.ActiveSound.Update().
Referenced by Terraria.Audio.ActiveSound.ActiveSound().