Terraria: System.Security.Principal.WindowsIdentity.WindowsIdentity
WindowsIdentity() [8/9]
unsafe System.Security.Principal.WindowsIdentity.WindowsIdentity (string sUserPrincipalName) inline
Definition at line 361 of file WindowsIdentity.cs.
        : base(null, null, null, "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name", "http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid")
    {
        checked
        {
            using SafeLsaHandle lsaHandle = ConnectToLsa();
            int authenticationPackage = LookupAuthenticationPackage(lsaHandle, "Kerberos");
            byte[] array = new byte[4] { 67, 76, 82, 0 };
            Unsafe.SkipInit(out global::Interop.SspiCli.TOKEN_SOURCE SourceContext);
            if (!global::Interop.Advapi32.AllocateLocallyUniqueId(out SourceContext.SourceIdentifier))
            {
                throw new SecurityException(new Win32Exception().Message);
            }
            SourceContext.SourceName = new byte[8];
            Buffer.BlockCopy(array, 0, SourceContext.SourceName, 0, array.Length);
            if (sUserPrincipalName == null)
            {
                throw new ArgumentNullException("sUserPrincipalName");
            }
            byte[] array2 = Encoding.Unicode.GetBytes(sUserPrincipalName);
            if (array2.Length > 65535)
            {
                Array.Resize(ref array2, array2.Length & 0xFFFF);
            }
            int num = sizeof(global::Interop.SspiCli.KERB_S4U_LOGON) + array2.Length;
            using SafeLocalAllocHandle safeLocalAllocHandle = SafeLocalAllocHandle.LocalAlloc(num);
            global::Interop.SspiCli.KERB_S4U_LOGON* ptr = unchecked((global::Interop.SspiCli.KERB_S4U_LOGON*)(void*)safeLocalAllocHandle.DangerousGetHandle());
            ptr->MessageType = global::Interop.SspiCli.KERB_LOGON_SUBMIT_TYPE.KerbS4ULogon;
            ptr->Flags = global::Interop.SspiCli.KerbS4uLogonFlags.None;
            ptr->ClientUpn.Length = (ptr->ClientUpn.MaximumLength = (ushort)array2.Length);
            IntPtr buffer = (IntPtr)(ptr + 1);
            ptr->ClientUpn.Buffer = buffer;
            Marshal.Copy(array2, 0, ptr->ClientUpn.Buffer, array2.Length);
            ptr->ClientRealm.Length = (ptr->ClientRealm.MaximumLength = 0);
            ptr->ClientRealm.Buffer = IntPtr.Zero;
            ushort num2 = (ushort)array.Length;
            using SafeLocalAllocHandle safeLocalAllocHandle2 = SafeLocalAllocHandle.LocalAlloc(num2);
            Marshal.Copy(array, 0, safeLocalAllocHandle2.DangerousGetHandle(), array.Length);
            global::Interop.Advapi32.LSA_STRING OriginName = new global::Interop.Advapi32.LSA_STRING(safeLocalAllocHandle2.DangerousGetHandle(), num2);
            SafeLsaReturnBufferHandle ProfileBuffer;
            int ProfileBufferLength;
            global::Interop.LUID LogonId;
            SafeAccessTokenHandle Token;
            global::Interop.SspiCli.QUOTA_LIMITS Quotas;
            int SubStatus;
            int num3 = global::Interop.SspiCli.LsaLogonUser(lsaHandle, ref OriginName, global::Interop.SspiCli.SECURITY_LOGON_TYPE.Network, authenticationPackage, safeLocalAllocHandle.DangerousGetHandle(), num, IntPtr.Zero, ref SourceContext, out ProfileBuffer, out ProfileBufferLength, out LogonId, out Token, out Quotas, out SubStatus);
            if (num3 == -1073741714 && SubStatus < 0)
            {
                num3 = SubStatus;
            }
            if (num3 < 0)
            {
                throw GetExceptionFromNtStatus(num3);
            }
            if (SubStatus < 0)
            {
                throw GetExceptionFromNtStatus(SubStatus);
            }
            ProfileBuffer?.Dispose();
            _safeTokenHandle = Token;
        }
    }
References System.Security.Principal.WindowsIdentity._safeTokenHandle, System.array, System.Buffer.BlockCopy(), System.buffer, System.Security.Principal.WindowsIdentity.ConnectToLsa(), System.Runtime.InteropServices.Marshal.Copy(), System.Runtime.Serialization.Dictionary, System.Security.Principal.WindowsIdentity.GetExceptionFromNtStatus(), Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc(), System.Security.Principal.WindowsIdentity.LookupAuthenticationPackage(), System.Security.Principal.WindowsIdentity.Token, System.Text.Encoding.Unicode, and System.IntPtr.Zero.