Terraria: System.Security.Principal.WindowsIdentity.InitializeClaims
InitializeClaims()
void System.Security.Principal.WindowsIdentity.InitializeClaims () inline private
Definition at line 804 of file WindowsIdentity.cs.
    {
        bool target = false;
        LazyInitializer.EnsureInitialized(ref target, ref _claimsInitialized, ref _claimsIntiailizedLock, delegate
        {
            _userClaims = new List<Claim>();
            _deviceClaims = new List<Claim>();
            if (!string.IsNullOrEmpty(Name))
            {
                _userClaims.Add(new Claim(base.NameClaimType, Name, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this));
            }
            AddPrimarySidClaim(_userClaims);
            AddGroupSidClaims(_userClaims);
            if (!s_ignoreWindows8Properties)
            {
                AddDeviceGroupSidClaims(_deviceClaims, TokenInformationClass.TokenDeviceGroups);
                if (!s_ignoreWindows8Properties)
                {
                    AddTokenClaims(_userClaims, TokenInformationClass.TokenUserClaimAttributes, "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsuserclaim");
                    AddTokenClaims(_deviceClaims, TokenInformationClass.TokenDeviceClaimAttributes, "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsdeviceclaim");
                }
            }
            return true;
        });
    }
References System.Security.Principal.WindowsIdentity._claimsInitialized, System.Security.Principal.WindowsIdentity._claimsIntiailizedLock, System.Security.Principal.WindowsIdentity._deviceClaims, System.Security.Principal.WindowsIdentity._issuerName, System.Security.Principal.WindowsIdentity._userClaims, System.Collections.Generic.List< T >.Add(), System.Security.Principal.WindowsIdentity.AddDeviceGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddGroupSidClaims(), System.Security.Principal.WindowsIdentity.AddPrimarySidClaim(), System.Security.Principal.WindowsIdentity.AddTokenClaims(), System.Security.Principal.WindowsIdentity.Name, and System.Security.Principal.WindowsIdentity.s_ignoreWindows8Properties.