Terraria: System.Security.Principal.WindowsIdentity.AddDeviceGroupSidClaims
AddDeviceGroupSidClaims()
void System.Security.Principal.WindowsIdentity.AddDeviceGroupSidClaims (List< Claim > instanceClaims, TokenInformationClass tokenInformationClass) inline private
Definition at line 921 of file WindowsIdentity.cs.
    {
        if (_safeTokenHandle.IsInvalid)
        {
            return;
        }
        SafeLocalAllocHandle safeLocalAllocHandle = null;
        try
        {
            safeLocalAllocHandle = GetTokenInformation(_safeTokenHandle, tokenInformationClass, nullOnInvalidParam: true);
            if (safeLocalAllocHandle == null)
            {
                s_ignoreWindows8Properties = true;
                return;
            }
            int num = Marshal.ReadInt32(safeLocalAllocHandle.DangerousGetHandle());
            IntPtr intPtr = new IntPtr((long)safeLocalAllocHandle.DangerousGetHandle() + (long)Marshal.OffsetOf(typeof(global::Interop.TOKEN_GROUPS), "Groups"));
            for (int i = 0; i < num; i++)
            {
                global::Interop.SID_AND_ATTRIBUTES sID_AND_ATTRIBUTES = (global::Interop.SID_AND_ATTRIBUTES)Marshal.PtrToStructure(intPtr, typeof(global::Interop.SID_AND_ATTRIBUTES));
                uint num2 = 3221225492u;
                SecurityIdentifier securityIdentifier = new SecurityIdentifier(sID_AND_ATTRIBUTES.Sid);
                if ((sID_AND_ATTRIBUTES.Attributes & num2) == 4)
                {
                    string text = "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsdevicegroup";
                    Claim claim = new Claim(text, securityIdentifier.Value, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                    claim.Properties.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority", securityIdentifier.IdentifierAuthority.ToString());
                    claim.Properties.Add(text, "");
                    instanceClaims.Add(claim);
                }
                else if ((sID_AND_ATTRIBUTES.Attributes & num2) == 16)
                {
                    string text = "http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlywindowsdevicegroup";
                    Claim claim2 = new Claim(text, securityIdentifier.Value, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                    claim2.Properties.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority", securityIdentifier.IdentifierAuthority.ToString());
                    claim2.Properties.Add(text, "");
                    instanceClaims.Add(claim2);
                }
                intPtr = new IntPtr((long)intPtr + Marshal.SizeOf<global::Interop.SID_AND_ATTRIBUTES>());
            }
        }
        finally
        {
            safeLocalAllocHandle?.Dispose();
        }
    }
References System.Security.Principal.WindowsIdentity._issuerName, System.Security.Principal.WindowsIdentity._safeTokenHandle, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, System.Security.Principal.WindowsIdentity.GetTokenInformation(), Microsoft.Win32.SafeHandles.SafeAccessTokenHandle.IsInvalid, System.Runtime.InteropServices.Marshal.OffsetOf(), System.Runtime.InteropServices.Marshal.PtrToStructure(), System.Runtime.InteropServices.Marshal.ReadInt32(), System.Security.Principal.WindowsIdentity.s_ignoreWindows8Properties, System.Runtime.InteropServices.Marshal.SizeOf(), and System.text.
Referenced by System.Security.Principal.WindowsIdentity.InitializeClaims().