Terraria: System.Security.Principal.WindowsIdentity.RunImpersonatedInternal
RunImpersonatedInternal()
static void System.Security.Principal.WindowsIdentity.RunImpersonatedInternal (SafeAccessTokenHandle token, Action action) inline static private
Definition at line 629 of file WindowsIdentity.cs.
    {
        token = DuplicateAccessToken(token);
        bool isImpersonating;
        int hr;
        SafeAccessTokenHandle currentToken = GetCurrentToken(TokenAccessLevels.MaximumAllowed, threadOnly: false, out isImpersonating, out hr);
        if (currentToken == null || currentToken.IsInvalid)
        {
            throw new SecurityException(new Win32Exception(hr).Message);
        }
        s_currentImpersonatedToken.Value = (isImpersonating ? currentToken : null);
        ExecutionContext executionContext = ExecutionContext.Capture();
        ExecutionContext.Run(executionContext, delegate
        {
            if (!global::Interop.Advapi32.RevertToSelf())
            {
                Environment.FailFast(new Win32Exception().Message);
            }
            s_currentImpersonatedToken.Value = null;
            if (!token.IsInvalid && !global::Interop.Advapi32.ImpersonateLoggedOnUser(token))
            {
                throw new SecurityException(System.SR.Argument_ImpersonateUser);
            }
            s_currentImpersonatedToken.Value = token;
            action();
        }, null);
    }
References System.action, System.SR.Argument_ImpersonateUser, System.Threading.ExecutionContext.Capture(), System.Runtime.Serialization.Dictionary, System.Security.Principal.WindowsIdentity.DuplicateAccessToken(), System.Environment.FailFast(), System.Security.Principal.WindowsIdentity.GetCurrentToken(), Microsoft.Win32.SafeHandles.SafeAccessTokenHandle.IsInvalid, and System.Threading.ExecutionContext.Run().
Referenced by System.Security.Principal.WindowsIdentity.RunImpersonated(), and System.Security.Principal.WindowsIdentity.RunImpersonated< T >().