Terraria: System.Security.Principal.WindowsIdentity.AddPrimarySidClaim
AddPrimarySidClaim()
void System.Security.Principal.WindowsIdentity.AddPrimarySidClaim (List< Claim > instanceClaims) inline private
Definition at line 889 of file WindowsIdentity.cs.
    {
        if (_safeTokenHandle.IsInvalid)
        {
            return;
        }
        SafeLocalAllocHandle safeLocalAllocHandle = null;
        try
        {
            safeLocalAllocHandle = GetTokenInformation(_safeTokenHandle, TokenInformationClass.TokenUser);
            global::Interop.SID_AND_ATTRIBUTES sID_AND_ATTRIBUTES = Marshal.PtrToStructure<global::Interop.SID_AND_ATTRIBUTES>(safeLocalAllocHandle.DangerousGetHandle());
            uint num = 16u;
            SecurityIdentifier securityIdentifier = new SecurityIdentifier(sID_AND_ATTRIBUTES.Sid);
            if (sID_AND_ATTRIBUTES.Attributes == 0)
            {
                Claim claim = new Claim("http://schemas.microsoft.com/ws/2008/06/identity/claims/primarysid", securityIdentifier.Value, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                claim.Properties.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority", securityIdentifier.IdentifierAuthority.ToString());
                instanceClaims.Add(claim);
            }
            else if ((sID_AND_ATTRIBUTES.Attributes & num) == 16)
            {
                Claim claim = new Claim("http://schemas.microsoft.com/ws/2008/06/identity/claims/denyonlyprimarysid", securityIdentifier.Value, "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                claim.Properties.Add("http://schemas.microsoft.com/ws/2008/06/identity/claims/windowssubauthority", securityIdentifier.IdentifierAuthority.ToString());
                instanceClaims.Add(claim);
            }
        }
        finally
        {
            safeLocalAllocHandle?.Dispose();
        }
    }
References System.Security.Principal.WindowsIdentity._issuerName, System.Security.Principal.WindowsIdentity._safeTokenHandle, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, System.Security.Principal.WindowsIdentity.GetTokenInformation(), Microsoft.Win32.SafeHandles.SafeAccessTokenHandle.IsInvalid, and System.Runtime.InteropServices.Marshal.PtrToStructure().
Referenced by System.Security.Principal.WindowsIdentity.InitializeClaims().