Terraria: System.Security.Principal.WindowsIdentity.AddTokenClaims
AddTokenClaims()
void System.Security.Principal.WindowsIdentity.AddTokenClaims (List< Claim > instanceClaims, TokenInformationClass tokenInformationClass, string propertyValue) inline private
Definition at line 968 of file WindowsIdentity.cs.
    {
        if (_safeTokenHandle.IsInvalid)
        {
            return;
        }
        SafeLocalAllocHandle safeLocalAllocHandle = null;
        try
        {
            safeLocalAllocHandle = GetTokenInformation(_safeTokenHandle, tokenInformationClass);
            global::Interop.CLAIM_SECURITY_ATTRIBUTES_INFORMATION cLAIM_SECURITY_ATTRIBUTES_INFORMATION = (global::Interop.CLAIM_SECURITY_ATTRIBUTES_INFORMATION)Marshal.PtrToStructure(safeLocalAllocHandle.DangerousGetHandle(), typeof(global::Interop.CLAIM_SECURITY_ATTRIBUTES_INFORMATION));
            long num = 0L;
            for (int i = 0; i < cLAIM_SECURITY_ATTRIBUTES_INFORMATION.AttributeCount; i++)
            {
                IntPtr ptr = new IntPtr(cLAIM_SECURITY_ATTRIBUTES_INFORMATION.Attribute.pAttributeV1.ToInt64() + num);
                global::Interop.CLAIM_SECURITY_ATTRIBUTE_V1 structure = (global::Interop.CLAIM_SECURITY_ATTRIBUTE_V1)Marshal.PtrToStructure(ptr, typeof(global::Interop.CLAIM_SECURITY_ATTRIBUTE_V1));
                switch (structure.ValueType)
                {
                case global::Interop.ClaimSecurityAttributeType.CLAIM_SECURITY_ATTRIBUTE_TYPE_STRING:
                {
                    IntPtr[] array4 = new IntPtr[structure.ValueCount];
                    Marshal.Copy(structure.Values.ppString, array4, 0, (int)structure.ValueCount);
                    for (int m = 0; m < structure.ValueCount; m++)
                    {
                        Claim claim4 = new Claim(structure.Name, Marshal.PtrToStringAuto(array4[m]), "http://www.w3.org/2001/XMLSchema#string", _issuerName, _issuerName, this);
                        claim4.Properties.Add(propertyValue, string.Empty);
                        instanceClaims.Add(claim4);
                    }
                    break;
                }
                case global::Interop.ClaimSecurityAttributeType.CLAIM_SECURITY_ATTRIBUTE_TYPE_INT64:
                {
                    long[] array2 = new long[structure.ValueCount];
                    Marshal.Copy(structure.Values.pInt64, array2, 0, (int)structure.ValueCount);
                    for (int k = 0; k < structure.ValueCount; k++)
                    {
                        Claim claim2 = new Claim(structure.Name, array2[k].ToString(CultureInfo.InvariantCulture), "http://www.w3.org/2001/XMLSchema#integer64", _issuerName, _issuerName, this);
                        claim2.Properties.Add(propertyValue, string.Empty);
                        instanceClaims.Add(claim2);
                    }
                    break;
                }
                case global::Interop.ClaimSecurityAttributeType.CLAIM_SECURITY_ATTRIBUTE_TYPE_UINT64:
                {
                    long[] array3 = new long[structure.ValueCount];
                    Marshal.Copy(structure.Values.pUint64, array3, 0, (int)structure.ValueCount);
                    for (int l = 0; l < structure.ValueCount; l++)
                    {
                        string name = structure.Name;
                        ulong num2 = (ulong)array3[l];
                        Claim claim3 = new Claim(name, num2.ToString(CultureInfo.InvariantCulture), "http://www.w3.org/2001/XMLSchema#uinteger64", _issuerName, _issuerName, this);
                        claim3.Properties.Add(propertyValue, string.Empty);
                        instanceClaims.Add(claim3);
                    }
                    break;
                }
                case global::Interop.ClaimSecurityAttributeType.CLAIM_SECURITY_ATTRIBUTE_TYPE_BOOLEAN:
                {
                    long[] array = new long[structure.ValueCount];
                    Marshal.Copy(structure.Values.pUint64, array, 0, (int)structure.ValueCount);
                    for (int j = 0; j < structure.ValueCount; j++)
                    {
                        Claim claim = new Claim(structure.Name, (array[j] != 0).ToString(), "http://www.w3.org/2001/XMLSchema#boolean", _issuerName, _issuerName, this);
                        claim.Properties.Add(propertyValue, string.Empty);
                        instanceClaims.Add(claim);
                    }
                    break;
                }
                }
                num += Marshal.SizeOf(structure);
            }
        }
        finally
        {
            safeLocalAllocHandle?.Dispose();
        }
    }
References System.Security.Principal.WindowsIdentity._issuerName, System.Security.Principal.WindowsIdentity._safeTokenHandle, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Runtime.Serialization.Dictionary, System.Security.Principal.WindowsIdentity.GetTokenInformation(), System.Globalization.CultureInfo.InvariantCulture, Microsoft.Win32.SafeHandles.SafeAccessTokenHandle.IsInvalid, System.L, System.Runtime.InteropServices.Marshal.PtrToStringAuto(), System.Runtime.InteropServices.Marshal.PtrToStructure(), System.Runtime.InteropServices.Marshal.SizeOf(), and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Security.Principal.WindowsIdentity.InitializeClaims().