Terraria: System.Security.Principal.WindowsIdentity.GetCurrentToken
GetCurrentToken()
static SafeAccessTokenHandle System.Security.Principal.WindowsIdentity.GetCurrentToken (TokenAccessLevels desiredAccess, bool threadOnly, out bool isImpersonating, out int hr) inline static private
Definition at line 717 of file WindowsIdentity.cs.
    {
        isImpersonating = true;
        hr = 0;
        SafeAccessTokenHandle tokenHandle;
        bool flag = global::Interop.Advapi32.OpenThreadToken(desiredAccess, WinSecurityContext.Both, out tokenHandle);
        if (!flag)
        {
            hr = Marshal.GetHRForLastWin32Error();
        }
        if (!flag && hr == GetHRForWin32Error(1008))
        {
            isImpersonating = false;
            if (!threadOnly)
            {
                return GetCurrentProcessToken(desiredAccess, out hr);
            }
        }
        return tokenHandle;
    }
References System.Runtime.Serialization.Dictionary, System.Security.Principal.WindowsIdentity.GetCurrentProcessToken(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), and System.Security.Principal.WindowsIdentity.GetHRForWin32Error().
Referenced by System.Security.Principal.WindowsIdentity.GetCurrentInternal(), and System.Security.Principal.WindowsIdentity.RunImpersonatedInternal().