Terraria: System.Security.Principal.WindowsIdentity.WindowsIdentity
WindowsIdentity() [5/9]
System.Security.Principal.WindowsIdentity.WindowsIdentity (WindowsIdentity identity) inline protected
Definition at line 322 of file WindowsIdentity.cs.
        : base(identity, null, GetAuthType(identity), null, null)
    {
        bool success = false;
        try
        {
            if (!identity._safeTokenHandle.IsInvalid && identity._safeTokenHandle != SafeAccessTokenHandle.InvalidHandle && identity._safeTokenHandle.DangerousGetHandle() != IntPtr.Zero)
            {
                identity._safeTokenHandle.DangerousAddRef(ref success);
                if (!identity._safeTokenHandle.IsInvalid && identity._safeTokenHandle.DangerousGetHandle() != IntPtr.Zero)
                {
                    CreateFromToken(identity._safeTokenHandle.DangerousGetHandle());
                }
                _authType = identity._authType;
                _isAuthenticated = identity._isAuthenticated;
            }
        }
        finally
        {
            if (success)
            {
                identity._safeTokenHandle.DangerousRelease();
            }
        }
    }
References System.Security.Principal.WindowsIdentity._authType, System.Security.Principal.WindowsIdentity._isAuthenticated, System.Security.Principal.WindowsIdentity._safeTokenHandle, System.Security.Principal.WindowsIdentity.CreateFromToken(), System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), Microsoft.Win32.SafeHandles.SafeAccessTokenHandle.InvalidHandle, Microsoft.Win32.SafeHandles.SafeAccessTokenHandle.IsInvalid, and System.IntPtr.Zero.