Terraria: Terraria.IO.ResourcePackList.CreatePacksFromWorkshopFolders
CreatePacksFromWorkshopFolders()
static void Terraria.IO.ResourcePackList.CreatePacksFromWorkshopFolders (IServiceProvider services, List< ResourcePack > resourcePacks) inline static private
Definition at line 164 of file ResourcePackList.cs.
    {
        WorkshopSocialModule workshop = SocialAPI.Workshop;
        if (workshop == null)
        {
            return;
        }
        List<string> listOfSubscribedResourcePackPaths = workshop.GetListOfSubscribedResourcePackPaths();
        ResourcePack.BrandingType resourcePackBrand = workshop.Branding.ResourcePackBrand;
        foreach (string item in listOfSubscribedResourcePackPaths)
        {
            try
            {
                string folderName = Path.GetFileName(item);
                if (resourcePacks.All((ResourcePack pack) => pack.FileName != folderName))
                {
                    resourcePacks.Add(new ResourcePack(services, item, resourcePackBrand));
                }
            }
            catch (Exception arg)
            {
                Console.WriteLine("Failed to read resource pack {0}: {1}", item, arg);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.IO.Path.GetFileName(), System.item, Terraria.IO.ResourcePackList.pack, Terraria.Social.SocialAPI.Workshop, and System.Console.WriteLine().
Referenced by Terraria.IO.ResourcePackList.FromJson().