Terraria: System.Drawing.SizeF.SizeF
SizeF() [1/4]
System.Drawing.SizeF.SizeF (SizeF size) inline
Definition at line 56 of file SizeF.cs.
    {
        width = size.width;
        height = size.height;
    }
References System.Drawing.SizeF.height, and System.Drawing.SizeF.width.
Referenced by System.Drawing.SizeF.Add(), System.Drawing.SizeF.Multiply(), System.Drawing.SizeF.operator SizeF(), System.Drawing.SizeF.operator/(), and System.Drawing.SizeF.Subtract().