Terraria: System.Net.Mail.AttachmentCollection.Dispose
Dispose()
void System.Net.Mail.AttachmentCollection.Dispose () inline
Implements System.IDisposable.
Definition at line 14 of file AttachmentCollection.cs.
    {
        if (_disposed)
        {
            return;
        }
        using (IEnumerator<Attachment> enumerator = GetEnumerator())
        {
            while (enumerator.MoveNext())
            {
                Attachment current = enumerator.Current;
                current.Dispose();
            }
        }
        Clear();
        _disposed = true;
    }
References System.Net.Mail.AttachmentCollection._disposed, System.Collections.ObjectModel.Collection< Attachment >.Clear(), System.Net.Mail.AttachmentBase.Dispose(), and System.Collections.ObjectModel.Collection< Attachment >.GetEnumerator().
Referenced by System.Net.Mail.MailMessage.Dispose().