Terraria: UIIconTextButton.DrawSelf
DrawSelf()
override void UIIconTextButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         if (_hovered)
         {
             if (!_soundedHover)
             {
                 SoundEngine.PlaySound(12);
             }
             _soundedHover = true;
         }
         else
         {
             _soundedHover = false;
         }
         CalculatedStyle dimensions = GetDimensions();
         Color color = _color;
         float opacity = _opacity;
         Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, 10, 10, 10, 10, Color.Lerp(Color.Black, color, FadeFromBlack) * opacity);
         if (_iconTexture != null)
         {
             Color color2 = Color.Lerp(color, Color.White, _whiteLerp) * opacity;
             spriteBatch.Draw(_iconTexture.Value, new Vector2(dimensions.X + dimensions.Width - (float)_iconTexture.Width() - 5f, dimensions.Center().Y - (float)(_iconTexture.Height() / 2)), color2);
         }
     }
References _BasePanelTexture, _color, _hovered, _iconTexture, _opacity, _soundedHover, _whiteLerp, CalculatedStyle.Center(), Color, Utils.DrawSplicedPanel(), FadeFromBlack, UIElement.GetDimensions(), CalculatedStyle.Height, SoundEngine.PlaySound(), Asset< T >.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.