Terraria: UIWorkshopSelectWorldToPublish.Recalculate
Recalculate()
override void UIWorkshopSelectWorldToPublish.Recalculate () inline virtual
Reimplemented from UIElement.
     {
         if (_scrollbar != null)
         {
             if (_isScrollbarAttached && !_scrollbar.CanScroll)
             {
                 _containerPanel.RemoveChild(_scrollbar);
                 _isScrollbarAttached = false;
                 _entryList.Width.Set(0f, 1f);
             }
             else if (!_isScrollbarAttached && _scrollbar.CanScroll)
             {
                 _containerPanel.Append(_scrollbar);
                 _isScrollbarAttached = true;
                 _entryList.Width.Set(-25f, 1f);
             }
         }
         base.Recalculate();
     }
References _containerPanel, _entryList, _isScrollbarAttached, _scrollbar, UIElement.Append(), UIScrollbar.CanScroll, UIElement.RemoveChild(), StyleDimension.Set(), and UIElement.Width.