Terraria: TEItemFrame.OnPlayerInteraction
OnPlayerInteraction()
static void TEItemFrame.OnPlayerInteraction (Player player, int clickX, int clickY) inline static
     {
         if (FitsItemFrame(player.inventory[player.selectedItem]) && !player.inventory[player.selectedItem].favorited)
         {
             player.GamepadEnableGrappleCooldown();
             PlaceItemInFrame(player, clickX, clickY);
             Recipe.FindRecipes();
             return;
         }
         int num = clickX;
         int num2 = clickY;
         if (Main.tile[num, num2].frameX % 36 != 0)
         {
             num--;
         }
         if (Main.tile[num, num2].frameY % 36 != 0)
         {
             num2--;
         }
         int num3 = Find(num, num2);
         if (num3 != -1 && ((TEItemFrame)TileEntity.ByID[num3]).item.stack > 0)
         {
             player.GamepadEnableGrappleCooldown();
             WorldGen.KillTile(clickX, clickY, fail: true);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, num, num2, 1f);
             }
         }
     }
References TileEntity.ByID, Item.favorited, Find(), Recipe.FindRecipes(), FitsItemFrame(), Tile.frameX, Tile.frameY, Player.GamepadEnableGrappleCooldown(), Player.inventory, WorldGen.KillTile(), Main.netMode, PlaceItemInFrame(), Player.selectedItem, NetMessage.SendData(), and Main.tile.
Referenced by Player.TileInteractionsUse().