Terraria: Internal.Cryptography.BasicSymmetricCipher.Dispose
Dispose() [1/2]
void Internal.Cryptography.BasicSymmetricCipher.Dispose () inline inherited
Implements System.IDisposable.
Definition at line 24 of file BasicSymmetricCipher.cs.
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
References Internal.Cryptography.BasicSymmetricCipher.Dispose(), and System.GC.SuppressFinalize().
Referenced by Internal.Cryptography.BasicSymmetricCipher.Dispose(), and Internal.Cryptography.UniversalCryptoTransform.Dispose().