Terraria: System.Xml.Schema.AxisStack.Push
Push()
void System.Xml.Schema.AxisStack.Push (int depth) inline package
Definition at line 28 of file AxisStack.cs.
    {
        AxisElement value = new AxisElement(_subtree.RootNode, depth);
        _stack.Add(value);
    }
References System.Xml.Schema.AxisStack._stack, System.Xml.Schema.AxisStack._subtree, System.Collections.ArrayList.Add(), System.Xml.Schema.ForwardAxis.RootNode, and System.value.
Referenced by System.Xml.Schema.AxisStack.AxisStack(), and System.Xml.Schema.AxisStack.MoveToChild().