Terraria: Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseReqest
HandleUseReqest()
override void Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseReqest (GraphicsDevice device, SpriteBatch spriteBatch) inline protected
    {
        Main.instance.LoadProjectile(908);
        Asset<Texture2D> val = TextureAssets.Projectile[908];
        UpdateSettingsForRendering(0.6f, 0f, Main.GlobalTimeWrappedHourly, 0.3f);
        PrepareARenderTarget_AndListenToEvents(ref _target, device, val.Width(), val.Height(), RenderTargetUsage.PreserveContents);
        device.SetRenderTarget(_target);
        device.Clear(Color.Transparent);
        DrawData value = new DrawData(val.Value, Vector2.Zero, Color.White);
        spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
        _shaderData.Apply(value);
        value.Draw(spriteBatch);
        spriteBatch.End();
        device.SetRenderTarget(null);
        _wasPrepared = true;
    }
References Terraria.GameContent.PlayerTitaniumStormBuffTextureContent._shaderData, Terraria.GameContent.ARenderTargetContentByRequest._target, Terraria.GameContent.ARenderTargetContentByRequest._wasPrepared, Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.DataStructures.DrawData.Draw(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.instance, Terraria.GameContent.ARenderTargetContentByRequest.PrepareARenderTarget_AndListenToEvents(), Terraria.GameContent.TextureAssets.Projectile, Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.UpdateSettingsForRendering(), and ReLogic.Content.Asset< T >.Value.