Terraria: System.Net.Http.Headers.ContentRangeHeaderValue.GetContentRangeLength
GetContentRangeLength()
static int System.Net.Http.Headers.ContentRangeHeaderValue.GetContentRangeLength (string input, int startIndex, out object parsedValue) inline static package
Definition at line 168 of file ContentRangeHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int tokenLength = HttpRuleParser.GetTokenLength(input, startIndex);
        if (tokenLength == 0)
        {
            return 0;
        }
        string unit = input.Substring(startIndex, tokenLength);
        int num = startIndex + tokenLength;
        int whitespaceLength = HttpRuleParser.GetWhitespaceLength(input, num);
        if (whitespaceLength == 0)
        {
            return 0;
        }
        num += whitespaceLength;
        if (num == input.Length)
        {
            return 0;
        }
        int fromStartIndex = num;
        int fromLength = 0;
        int toStartIndex = 0;
        int toLength = 0;
        if (!TryGetRangeLength(input, ref num, out fromLength, out toStartIndex, out toLength))
        {
            return 0;
        }
        if (num == input.Length || input[num] != '/')
        {
            return 0;
        }
        num++;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        if (num == input.Length)
        {
            return 0;
        }
        int lengthStartIndex = num;
        int lengthLength = 0;
        if (!TryGetLengthLength(input, ref num, out lengthLength))
        {
            return 0;
        }
        if (!TryCreateContentRange(input, unit, fromStartIndex, fromLength, toStartIndex, toLength, lengthStartIndex, lengthLength, out parsedValue))
        {
            return 0;
        }
        return num - startIndex;
    }
References System.Net.Http.HttpRuleParser.GetTokenLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, System.startIndex, System.Net.Http.Headers.ContentRangeHeaderValue.TryCreateContentRange(), System.Net.Http.Headers.ContentRangeHeaderValue.TryGetLengthLength(), and System.Net.Http.Headers.ContentRangeHeaderValue.TryGetRangeLength().