Terraria: System.Net.Http.Headers.ContentRangeHeaderValue.ToString
ToString()
override string System.Net.Http.Headers.ContentRangeHeaderValue.ToString () inline
Definition at line 123 of file ContentRangeHeaderValue.cs.
    {
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire();
        stringBuilder.Append(_unit);
        stringBuilder.Append(' ');
        if (HasRange)
        {
            stringBuilder.Append(_from.Value);
            stringBuilder.Append('-');
            stringBuilder.Append(_to.Value);
        }
        else
        {
            stringBuilder.Append('*');
        }
        stringBuilder.Append('/');
        if (HasLength)
        {
            stringBuilder.Append(_length.Value);
        }
        else
        {
            stringBuilder.Append('*');
        }
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Net.Http.Headers.ContentRangeHeaderValue._from, System.Net.Http.Headers.ContentRangeHeaderValue._length, System.Net.Http.Headers.ContentRangeHeaderValue._to, System.Net.Http.Headers.ContentRangeHeaderValue._unit, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Text.StringBuilderCache.GetStringAndRelease(), System.Net.Http.Headers.ContentRangeHeaderValue.HasLength, and System.Net.Http.Headers.ContentRangeHeaderValue.HasRange.