Terraria: Projectile.AI_155_MysticSnakeCoil
AI_155_MysticSnakeCoil()
void Projectile.AI_155_MysticSnakeCoil () inline private
     {
         if (Main.netMode != 1 && !Main.player[owner].active)
         {
             float num = ai[0];
             float y = position.Y;
             Point point = base.Center.ToTileCoordinates();
             Point end = new Point(point.X, (int)y / 16);
             Point start = new Point(point.X, (int)num / 16);
             AI_155_RemoveRope(start, end);
             Kill();
             return;
         }
         int num2 = 100;
         int num3 = 1800;
         if (ai[1] == 0f)
         {
             spriteDirection = ((!(Main.player[owner].Center.X > base.Center.X)) ? 1 : (-1));
             ai[1] = 1f;
             velocity.Y = -5f;
         }
         if (ai[1] == 1f)
         {
             localAI[1] += 1f;
             float num4 = Utils.Remap(localAI[1], 15f, 30f, 0f, 1f);
             int num5 = ((localAI[1] >= 60f) ? 1 : 0);
             velocity.Y = -3f * (1f - num4) + (float)(-32 * num5);
             velocity.Y = (int)velocity.Y;
             if (localAI[1] == 60f)
             {
                 for (int i = 0; i < 30; i++)
                 {
                     Dust dust = Dust.NewDustDirect(base.TopLeft + new Vector2(-6f, 0f), 24, 16, 27, 0f, 0f, 150, Color.Transparent, 0.6f);
                     dust.velocity *= 1f;
                     dust.velocity.X *= 0.5f;
                     dust.velocity.Y = -3f;
                     dust.fadeIn = 1.2f;
                     dust.noGravity = true;
                     dust.position.X += Main.rand.NextFloatDirection() * 8f;
                     dust.velocity = new Vector2(0f, -1f).RotatedBy((float)Math.PI / 4f * Main.rand.NextFloatDirection() * 0f) * (Main.rand.NextFloatDirection() * 9f);
                     if (dust.velocity.Y < 0f)
                     {
                         dust.velocity.Y *= 1f + Main.rand.NextFloat() * 3f;
                     }
                 }
             }
             bool flag = num4 > 0f && num5 <= 0;
             if ((Main.rand.Next(6) == 0 || num5 > 0) && !flag)
             {
                 Dust dust2 = Dust.NewDustDirect(base.TopLeft + new Vector2(-6f, 0f), 24, 16, 27, 0f, 0f, 150, Color.Transparent, 0.6f);
                 dust2.velocity *= 1f;
                 dust2.velocity.X *= 0.5f;
                 dust2.velocity.Y = -3f;
                 dust2.fadeIn = 1.2f;
                 dust2.noGravity = true;
             }
             alpha = Utils.Clamp(alpha - 5, 0, 255);
             if (++frameCounter >= 12)
             {
                 frameCounter = 0;
                 if (++frame >= 4)
                 {
                     frame = 0;
                 }
             }
             if (Main.myPlayer == owner)
             {
                 float num6 = ai[0];
                 float y2 = position.Y;
                 Point point2 = base.Center.ToTileCoordinates();
                 Point point3 = new Point(point2.X, (int)y2 / 16);
                 Point point4 = new Point(point2.X, (int)num6 / 16);
                 bool flag2 = point4.Y - point3.Y >= num2;
                 int x = point4.X;
                 if (!WorldGen.InWorld(x, point3.Y, 40) || !WorldGen.InWorld(x, point4.Y, 40))
                 {
                     flag2 = true;
                 }
                 if (!flag2)
                 {
                     for (int num7 = point4.Y; num7 >= point3.Y; num7--)
                     {
                         if (Main.tile[x, num7].active() && !Main.tileCut[Main.tile[x, num7].type] && Main.tile[x, num7].type != 504)
{
                             flag2 = true;
                             break;
                         }
                     }
                 }
                 if (flag2)
                 {
                     int num8 = 0;
                     for (int num9 = point4.Y; num9 > point3.Y; num9--)
                     {
                         if ((WorldGen.TileEmpty(x, num9) || Main.tileCut[Main.tile[x, num9].type]) && WorldGen.PlaceTile(x, num9, 504, mute: false, forced: false, owner))
{
                             num8++;
                             if (Main.netMode == 1)
{
                                 NetMessage.SendData(17, -1, -1, null, 1, x, num9, 504f);
                             }
                         }
                     }
                     timeLeft = num3;
                     ai[1] = 2f;
                     netUpdate = true;
                     base.Top = new Vector2(x * 16 + 8, point3.Y * 16 + 16);
                     velocity = Vector2.Zero;
                 }
             }
         }
         if (ai[1] != 2f)
         {
             return;
         }
         alpha = 0;
         _ = timeLeft;
         float num10 = ai[0];
         float y3 = position.Y;
         Point point5 = base.Center.ToTileCoordinates();
         Point end2 = new Point(point5.X, (int)y3 / 16);
         Point start2 = new Point(point5.X, (int)num10 / 16);
         int x2 = start2.X;
         if (localAI[0] == 0f)
         {
             localAI[0] = 1f;
             for (int num11 = start2.Y; num11 >= end2.Y; num11--)
             {
                 Tile tile = Main.tile[x2, num11];
                 if (tile.active() && tile.type == 504)
                 {
                     AI_155_SpawnRopeIn(x2, num11);
                 }
             }
         }
         else
         {
             for (int num12 = start2.Y; num12 >= end2.Y; num12--)
             {
                 Tile tile2 = Main.tile[x2, num12];
                 if (tile2.active() && tile2.type == 504 && Main.rand.Next(80) == 0)
                 {
                     Dust dust3 = Dust.NewDustDirect(new Vector2(x2 * 16 - 6, num12 * 16), 28, 16, 27, 0f, 0f, 150, Color.Transparent, 0.6f);
                     dust3.velocity *= 1f;
                     dust3.velocity.X = 0f;
                     dust3.fadeIn = 1.2f;
                     dust3.noGravity = true;
                 }
             }
         }
         if (timeLeft == 4)
         {
             for (int num13 = start2.Y; num13 >= end2.Y; num13--)
             {
                 Tile tile3 = Main.tile[x2, num13];
                 if (tile3.active() && tile3.type == 504)
                 {
                     AI_155_SpawnRopeIn(x2, num13);
                 }
             }
         }
         if (timeLeft > 4)
         {
             return;
         }
         if (!WorldGen.InWorld(x2, end2.Y, 20) || !WorldGen.InWorld(x2, start2.Y, 20))
         {
             Kill();
             return;
         }
         if (Main.myPlayer == owner)
         {
             AI_155_RemoveRope(start2, end2);
         }
         Kill();
     }
References Entity.active, Tile.active(), Entity.Center, Utils.Center(), Color, Dust.fadeIn, WorldGen.InWorld(), Main.myPlayer, Main.netMode, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, WorldGen.PlaceTile(), Main.player, Dust.position, Main.rand, Utils.Remap(), NetMessage.SendData(), Main.tile, Main.tileCut, WorldGen.TileEmpty(), Tile.type, and Dust.velocity.