Terraria: Projectile.AI_047_MagnetSphere_TryAttacking
AI_047_MagnetSphere_TryAttacking()
void Projectile.AI_047_MagnetSphere_TryAttacking () inline private
     {
         int[] array = new int[20];
         int num = 0;
         float num2 = 300f;
         bool flag = false;
         float num3 = 0f;
         float num4 = 0f;
         for (int i = 0; i < 200; i++)
         {
             if (!Main.npc[i].CanBeChasedBy(this))
             {
                 continue;
             }
             float num5 = Main.npc[i].position.X + (float)(Main.npc[i].width / 2);
             float num6 = Main.npc[i].position.Y + (float)(Main.npc[i].height / 2);
             if (Math.Abs(position.X + (float)(width / 2) - num5) + Math.Abs(position.Y + (float)(height / 2) - num6) < num2 && Collision.CanHit(base.Center, 1, 1, Main.npc[i].Center, 1, 1))
             {
                 if (num < 20)
                 {
                     array[num] = i;
                     num++;
                     num3 = num5;
                     num4 = num6;
                 }
                 flag = true;
             }
         }
         if (timeLeft < 30)
         {
             flag = false;
         }
         if (flag)
         {
             int num7 = Main.rand.Next(num);
             num7 = array[num7];
             num3 = Main.npc[num7].position.X + (float)(Main.npc[num7].width / 2);
             num4 = Main.npc[num7].position.Y + (float)(Main.npc[num7].height / 2);
             localAI[0] += 1f;
             if (localAI[0] > 8f)
             {
                 localAI[0] = 0f;
                 Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 vector += velocity * 4f;
                 float num8 = num3 - vector.X;
                 float num9 = num4 - vector.Y;
                 float num10 = (float)Math.Sqrt(num8 * num8 + num9 * num9);
                 num10 = 6f / num10;
                 num8 *= num10;
                 num9 *= num10;
                 NewProjectile(GetProjectileSource_FromThis(), vector.X, vector.Y, num8, num9, 255, damage, knockBack, owner);
             }
         }
     }
References NPC.CanBeChasedBy(), Collision.CanHit(), Entity.Center, Entity.height, UnifiedRandom.Next(), Main.npc, Entity.position, Main.rand, and Entity.width.