Terraria: Projectile.DoRainbowCrystalStaffExplosion
DoRainbowCrystalStaffExplosion()
void Projectile.DoRainbowCrystalStaffExplosion () inline private
     {
         Vector2 spinningpoint = new Vector2(0f, -3f).RotatedByRandom(3.1415927410125732);
         float num = Main.rand.Next(7, 13);
         Vector2 vector = new Vector2(2.1f, 2f);
         Color newColor = Main.hslToRgb(ai[0], 1f, 0.5f);
         newColor.A = byte.MaxValue;
         for (float num2 = 0f; num2 < num; num2 += 1f)
         {
             int num3 = Dust.NewDust(base.Center, 0, 0, 267, 0f, 0f, 0, newColor);
             Main.dust[num3].position = base.Center;
             Main.dust[num3].velocity = spinningpoint.RotatedBy((float)Math.PI * 2f * num2 / num) * vector * (0.8f + Main.rand.NextFloat() * 0.4f);
             Main.dust[num3].noGravity = true;
             Main.dust[num3].scale = 2f;
             Main.dust[num3].fadeIn = Main.rand.NextFloat() * 2f;
             if (num3 != 6000)
             {
                 Dust dust = Dust.CloneDust(num3);
                 dust.scale /= 2f;
                 dust.fadeIn /= 2f;
                 dust.color = new Color(255, 255, 255, 255);
             }
         }
         for (float num4 = 0f; num4 < num; num4 += 1f)
         {
             int num5 = Dust.NewDust(base.Center, 0, 0, 267, 0f, 0f, 0, newColor);
             Main.dust[num5].position = base.Center;
             Main.dust[num5].velocity = spinningpoint.RotatedBy((float)Math.PI * 2f * num4 / num) * vector * (0.8f + Main.rand.NextFloat() * 0.4f);
             Main.dust[num5].velocity *= Main.rand.NextFloat() * 0.8f;
             Main.dust[num5].noGravity = true;
             Main.dust[num5].scale = Main.rand.NextFloat() * 1f;
             Main.dust[num5].fadeIn = Main.rand.NextFloat() * 2f;
             if (num5 != 6000)
             {
                 Dust dust2 = Dust.CloneDust(num5);
                 dust2.scale /= 2f;
                 dust2.fadeIn /= 2f;
                 dust2.color = new Color(255, 255, 255, 255);
             }
         }
     }
References Dust.CloneDust(), Color, Dust.color, Main.dust, Dust.fadeIn, Main.hslToRgb(), Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.position, Main.rand, Dust.scale, and Dust.velocity.