Terraria: Projectile.AI_142_MonkStaffT2And3
AI_142_MonkStaffT2And3()
void Projectile.AI_142_MonkStaffT2And3 () inline private
     {
         Player player = Main.player[owner];
         Vector2 vector = player.RotatedRelativePoint(player.MountedCenter);
         direction = player.direction;
         player.heldProj = whoAmI;
         base.Center = vector;
         if (player.dead)
         {
             Kill();
             return;
         }
         if (!player.frozen)
         {
             if (type == 699)
             {
                 spriteDirection = (direction = player.direction);
                 Vector2 vector2 = vector;
                 alpha -= 127;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 if (localAI[0] > 0f)
                 {
                     localAI[0] -= 1f;
                 }
                 float num = (float)player.itemAnimation / (float)player.itemAnimationMax;
                 float num2 = 1f - num;
                 float num3 = velocity.ToRotation();
                 float num4 = velocity.Length();
                 float num5 = 22f;
                 Vector2 spinningpoint = new Vector2(1f, 0f).RotatedBy((float)Math.PI + num2 * ((float)Math.PI * 2f)) * new Vector2(num4, ai[0]);
                 position += spinningpoint.RotatedBy(num3) + new Vector2(num4 + num5, 0f).RotatedBy(num3);
                 Vector2 target = vector2 + spinningpoint.RotatedBy(num3) + new Vector2(num4 + num5 + 40f, 0f).RotatedBy(num3);
                 rotation = vector2.AngleTo(target) + (float)Math.PI / 4f * (float)player.direction;
                 if (spriteDirection == -1)
                 {
                     rotation += (float)Math.PI;
                 }
                 vector2.DirectionTo(base.Center);
                 Vector2 vector3 = vector2.DirectionTo(target);
                 Vector2 vector4 = velocity.SafeNormalize(Vector2.UnitY);
                 float num6 = 2f;
                 for (int i = 0; (float)i < num6; i++)
                 {
                     Dust dust = Dust.NewDustDirect(base.Center, 14, 14, 228, 0f, 0f, 110);
                     dust.velocity = vector2.DirectionTo(dust.position) * 2f;
                     dust.position = base.Center + vector4.RotatedBy(num2 * ((float)Math.PI * 2f) * 2f + (float)i / num6 * ((float)Math.PI * 2f)) * 10f;
                     dust.scale = 1f + 0.6f * Main.rand.NextFloat();
                     dust.velocity += vector4 * 3f;
                     dust.noGravity = true;
                 }
                 for (int j = 0; j < 1; j++)
                 {
                     if (Main.rand.Next(3) == 0)
                     {
                         Dust dust2 = Dust.NewDustDirect(base.Center, 20, 20, 228, 0f, 0f, 110);
                         dust2.velocity = vector2.DirectionTo(dust2.position) * 2f;
                         dust2.position = base.Center + vector3 * -110f;
                         dust2.scale = 0.45f + 0.4f * Main.rand.NextFloat();
                         dust2.fadeIn = 0.7f + 0.4f * Main.rand.NextFloat();
                         dust2.noGravity = true;
                         dust2.noLight = true;
                     }
                 }
             }
             else if (type == 708)
             {
                 Lighting.AddLight(player.Center, 0.75f, 0.9f, 1.15f);
                 spriteDirection = (direction = player.direction);
                 alpha -= 127;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 float num7 = (float)player.itemAnimation / (float)player.itemAnimationMax;
                 float num8 = 1f - num7;
                 float num9 = velocity.ToRotation();
                 float num10 = velocity.Length();
                 float num11 = 22f;
                 Vector2 spinningpoint2 = new Vector2(1f, 0f).RotatedBy((float)Math.PI + num8 * ((float)Math.PI * 2f)) * new Vector2(num10, ai[0]);
                 position += spinningpoint2.RotatedBy(num9) + new Vector2(num10 + num11, 0f).RotatedBy(num9);
                 Vector2 vector5 = vector + spinningpoint2.RotatedBy(num9) + new Vector2(num10 + num11 + 40f, 0f).RotatedBy(num9);
                 rotation = (vector5 - vector).SafeNormalize(Vector2.UnitX).ToRotation() + (float)Math.PI / 4f * (float)player.direction;
                 if (spriteDirection == -1)
                 {
                     rotation += (float)Math.PI;
                 }
                 (base.Center - vector).SafeNormalize(Vector2.Zero);
                 (vector5 - vector).SafeNormalize(Vector2.Zero);
                 Vector2 vector6 = velocity.SafeNormalize(Vector2.UnitY);
                 if ((player.itemAnimation == 2 || player.itemAnimation == 6 || player.itemAnimation == 10) && owner == Main.myPlayer)
                 {
                     Vector2 vector7 = vector6 + Main.rand.NextVector2Square(-0.2f, 0.2f);
                     vector7 *= 12f;
                     switch (player.itemAnimation)
                     {
                     case 2:
                         vector7 = vector6.RotatedBy(0.3839724659919739);
                         break;
                     case 6:
                         vector7 = vector6.RotatedBy(-0.3839724659919739);
                         break;
                     case 10:
                         vector7 = vector6.RotatedBy(0.0);
                         break;
                     }
                     vector7 *= 10f + (float)Main.rand.Next(4);
                     NewProjectile(GetProjectileSource_FromThis(), base.Center, vector7, 709, damage, 0f, owner);
                 }
                 for (int k = 0; k < 3; k += 2)
                 {
                     float num12 = 1f;
                     float num13 = 1f;
                     switch (k)
                     {
                     case 1:
                         num13 = -1f;
                         break;
                     case 2:
                         num13 = 1.25f;
                         num12 = 0.5f;
                         break;
                     case 3:
                         num13 = -1.25f;
                         num12 = 0.5f;
                         break;
                     }
                     if (Main.rand.Next(6) != 0)
                     {
                         num13 *= 1.2f;
                         Dust dust3 = Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 100);
                         dust3.velocity = vector6 * (4f + 4f * Main.rand.NextFloat()) * num13 * num12;
                         dust3.noGravity = true;
                         dust3.noLight = true;
                         dust3.scale = 0.75f;
                         dust3.fadeIn = 0.8f;
                         dust3.customData = this;
                         if (Main.rand.Next(3) == 0)
{
                             dust3.noGravity = false;
                             dust3.fadeIn = 0f;
                         }
                     }
                 }
             }
         }
         if (player.whoAmI == Main.myPlayer && player.itemAnimation <= 2)
         {
             Kill();
             player.reuseDelay = 2;
         }
     }
References Lighting.AddLight(), Entity.Center, Dust.customData, Player.dead, Entity.direction, Dust.fadeIn, Player.frozen, Player.heldProj, Player.itemAnimation, Player.itemAnimationMax, Player.MountedCenter, Main.myPlayer, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.player, Dust.position, Main.rand, Player.reuseDelay, Player.RotatedRelativePoint(), Dust.scale, Dust.velocity, and Entity.whoAmI.