Terraria: Projectile.AI_157_SharpTears
AI_157_SharpTears()
void Projectile.AI_157_SharpTears () inline private
     {
         int num = 5;
         float num2 = 1f;
         int num3 = 30;
         int num4 = 30;
         int num5 = 2;
         int num6 = 2;
         int num7 = 20;
         int num8 = 30;
         int num9 = 35;
         int maxValue = 6;
         if (type == 961)
         {
             num = 16;
             num2 = 0.75f;
             num3 = 5;
             num4 = 5;
             num5 = 0;
             num6 = 0;
             num7 = 10;
             num8 = 10;
             num9 = 20;
             maxValue = 5;
         }
         bool flag = ai[0] < (float)num7;
         bool flag2 = ai[0] >= (float)num8;
         bool flag3 = ai[0] >= (float)num9;
         ai[0] += 1f;
         if (localAI[0] == 0f)
         {
             localAI[0] = 1f;
             rotation = velocity.ToRotation();
             frame = Main.rand.Next(maxValue);
             for (int i = 0; i < num3; i++)
             {
                 Dust dust = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(24f, 24f), num, velocity * num2 * MathHelper.Lerp(0.2f, 0.7f, Main.rand.NextFloat()));
                 dust.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                 dust.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
             }
             for (int j = 0; j < num4; j++)
             {
                 Dust dust2 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(24f, 24f), num, Main.rand.NextVector2Circular(2f, 2f) + velocity * num2 * MathHelper.Lerp(0.2f, 0.5f, Main.rand.NextFloat()));
                 dust2.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                 dust2.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
                 dust2.fadeIn = 1f;
             }
             if (type == 961)
             {
                 SoundEngine.PlaySound(SoundID.DeerclopsIceAttack, base.Center);
             }
             else
             {
                 SoundEngine.PlaySound(SoundID.Item60, base.Center);
             }
         }
         if (flag)
         {
             Opacity += 0.1f;
             scale = Opacity * ai[1];
             for (int k = 0; k < num5; k++)
             {
                 Dust dust3 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(16f, 16f), num, velocity * num2 * MathHelper.Lerp(0.2f, 0.5f, Main.rand.NextFloat()));
                 dust3.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                 dust3.velocity *= 0.5f;
                 dust3.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
             }
         }
         if (flag2)
         {
             Opacity -= 0.2f;
             for (int l = 0; l < num6; l++)
             {
                 Dust dust4 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(16f, 16f), num, velocity * num2 * MathHelper.Lerp(0.2f, 0.5f, Main.rand.NextFloat()));
                 dust4.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                 dust4.velocity *= 0.5f;
                 dust4.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
             }
         }
         if (flag3)
         {
             Kill();
         }
         if (type == 756)
         {
             Lighting.AddLight(base.Center, new Vector3(0.5f, 0.1f, 0.1f) * scale);
         }
     }
References Lighting.AddLight(), SoundID.DeerclopsIceAttack, Dust.fadeIn, SoundID.Item60, Dust.NewDustPerfect(), UnifiedRandom.Next(), SoundEngine.PlaySound(), Main.rand, Dust.scale, and Dust.velocity.