Terraria: Projectile.GetAlpha
GetAlpha()
Color Projectile.GetAlpha (Color newColor) inline
     {
         if (type == 920 || type == 921)
         {
             return Color.Lerp(newColor, Color.White, 0.4f) * Opacity;
         }
         if (type == 47 && Main.player[owner].wet)
         {
             return Color.White;
         }
         if (type == 937)
         {
             newColor.A = (byte)((float)(int)newColor.A * 0.75f);
         }
         if (type == 880 || type == 929)
         {
             newColor.A /= 2;
         }
         if (type == 963)
         {
             float num = 0.85f;
             newColor *= num;
             newColor.A = (byte)((float)(int)newColor.A * num);
             if (ai[0] >= 2f)
             {
                 newColor.G = (byte)((float)(int)newColor.G * 0.7f);
                 newColor.B = (byte)((float)(int)newColor.B * 0.7f);
             }
         }
         if (type == 1021)
         {
             return Color.White;
         }
         if (type == 1006)
         {
             return Color.White;
         }
         if (type == 981)
         {
             return Color.White;
         }
         if (type == 75)
         {
             return Color.Lerp(newColor, Color.White, 0.66f) * Opacity;
         }
         int r;
         int g;
         int b;
         if (type == 969)
         {
             int num2 = 210;
             r = (g = (b = num2));
             if (newColor.R < num2)
             {
                 r = newColor.R;
             }
             if (newColor.G < num2)
             {
                 g = newColor.G;
             }
             if (newColor.B < num2)
             {
                 b = newColor.B;
             }
             return new Color(r, g, b, 185) * Opacity;
         }
         if (type == 967)
         {
             return Color.White * Opacity;
         }
         if (type == 855)
         {
             newColor = Color.Lerp(newColor, new Color(255, 200, 60), 0.5f);
         }
         if (type == 933 || type == 1001)
         {
             newColor = Color.White * Opacity;
         }
         if (type == 270)
         {
             return new Color(255, 255, 255, (int)Utils.WrappedLerp(0f, 255f, (float)(timeLeft % 40) / 40f));
         }
         if (type == 837)
         {
             if (alpha > 0)
             {
                 return Color.Transparent;
             }
             return new Color(255, 255, 255, 200);
         }
         if (type == 180 || type == 345)
         {
             return Color.Lerp(newColor, Color.White, 0.75f);
         }
         if (type == 586)
         {
             if (ai[2] == 1f)
             {
                 Color value = new Color(newColor.R / 2, 0, newColor.G);
                 float amount = (float)Math.Sin(ai[0] % 120f * ((float)Math.PI * 2f) / 120f) * 0.5f + 0.5f;
                 newColor = Color.Lerp(newColor, value, amount);
                 return Color.Lerp(newColor, Color.Lerp(Color.White, value, amount), 0.75f);
             }
             return Color.Lerp(newColor, Color.White, 0.75f);
         }
         if (type == 764 || type == 856 || type == 857 || type == 864)
         {
             return Color.White;
         }
         if (type == 873 || type == 872 || type == 931 || type == 913 || type == 34)
         {
             return Color.White * Opacity;
         }
         if (type == 756 || type == 961)
         {
             return Color.Lerp(newColor, Color.Black, 0.25f);
         }
         if (type == 895)
         {
             return Color.White * Opacity;
         }
         if (type == 893 || type == 907)
         {
             return new Color(255, 255, 255, 150);
         }
         if (type == 833 || type == 834 || type == 835 || type == 912)
         {
             return Color.Lerp(newColor, Color.White, 0.25f);
         }
         if (type == 351 || type == 350)
         {
             Point point = base.Center.ToTileCoordinates();
             if (WorldGen.InWorld(point.X, point.Y) && !WorldGen.SolidTile(point.X, point.Y))
             {
                 return Color.Lerp(newColor, Color.White, 0.15f);
             }
             return Color.Lerp(newColor, Color.White, 0.05f);
         }
         if (type == 346 || type == 347 || type == 325 || type == 755)
         {
             return Color.Lerp(newColor, Color.White, 0.75f);
         }
         if (type == 650)
         {
             r = (int)((double)(int)newColor.R * 1.5);
             g = (int)((double)(int)newColor.G * 1.5);
             b = (int)((double)(int)newColor.B * 1.5);
             if (r > 255)
             {
                 r = 255;
             }
             if (g > 255)
             {
                 g = 255;
             }
             if (b > 255)
             {
                 b = 255;
             }
         }
         else
         {
             if (type == 948)
             {
                 return Color.White;
             }
             if (type == 604 || type == 631)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 0);
             }
             if (type == 342)
             {
                 return Color.Lerp(newColor, Color.White, 0.75f) * Opacity;
             }
             if (type == 636)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 64 - alpha / 4);
             }
             if (type == 673 || type == 706)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 180 - alpha / 2 - alpha / 4);
             }
             if (type == 603 || type == 633)
             {
                 return new Color(255, 255, 255, 200);
             }
             if (type == 623 || (type >= 625 && type <= 628) || type == 710)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 255 - alpha);
             }
             if (type == 645 || type == 643)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 127 - alpha / 2);
             }
             if (type == 611)
             {
                 return new Color(255, 255, 255, 200);
             }
             if (type == 640 || type == 644 || type == 658)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 0);
             }
             if (type == 612 || type == 953)
             {
                 return new Color(255, 255, 255, 127);
             }
             if (type == 978)
             {
                 return new Color(255, 255, 255, 127) * Opacity;
             }
             if (aiStyle == 105)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 255 - alpha);
             }
             if (type == 554)
             {
                 return new Color(200, 200, 200, 200);
             }
             if (type == 601)
             {
                 return PortalHelper.GetPortalColor(owner, (int)ai[0]);
             }
             if (type == 602)
             {
                 Color portalColor = PortalHelper.GetPortalColor(owner, (int)ai[1]);
                 portalColor.A = 227;
                 return portalColor;
             }
             if (type == 585)
             {
                 byte a = newColor.A;
                 newColor = Color.Lerp(newColor, Color.White, 0.5f);
                 newColor.A = a;
                 return newColor;
             }
             if (type == 714)
             {
                 byte a2 = newColor.A;
                 newColor = Color.Lerp(newColor, Color.White, 0.8f);
                 newColor.A = a2;
                 newColor *= (float)(int)a2 / 255f;
                 return newColor;
             }
             if (type == 573 || type == 578 || type == 579 || type == 617 || type == 641 || type == 707 || type == 813)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 255 - alpha);
             }
             if (type == 490)
             {
                 return Color.White;
             }
             if (type == 575 || type == 596 || type == 659)
             {
                 if (timeLeft < 30)
                 {
                     float num3 = (float)timeLeft / 30f;
                     alpha = (int)(255f - 255f * num3);
                 }
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 128 - alpha / 2);
             }
             if (type == 546)
             {
                 return new Color(255, 200, 255, 200);
             }
             if (type == 553)
             {
                 return new Color(255, 255, 200, 200);
             }
             if (type == 540)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 0);
             }
             if (type == 498)
             {
                 return new Color(255, 100, 20, 200);
             }
             if (type == 538)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 255 - alpha);
             }
             if (type == 518)
             {
                 float num4 = 1f - (float)alpha / 255f;
                 return new Color((int)(200f * num4), (int)(200f * num4), (int)(200f * num4), (int)(100f * num4));
             }
             if (type == 518 || type == 595 || type == 735)
             {
                 Color color = Color.Lerp(newColor, Color.White, 0.85f);
                 color.A = 128;
                 return color * (1f - (float)alpha / 255f);
             }
             if (type == 536 || type == 607)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 63 - alpha / 4);
             }
             if (type == 591)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 63 - alpha / 4);
             }
             if (type == 493 || type == 494)
             {
                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 255 - alpha);
             }
             if (type == 492)
             {
                 return new Color(255, 255, 255, 255);
             }
             if (type == 491)
             {
                 return new Color(255, 255, 255, 255);
             }
             if (type == 485 || type == 502)
             {
                 return new Color(255, 255, 255, 200);
             }
             if (type == 488)
             {
                 return new Color(255, 255, 255, 255);
             }
             if (type == 477 || type == 478 || type == 479)
             {
                 if (alpha == 0)
                 {
                     return new Color(255, 255, 255, 200);
                 }
                 return new Color(0, 0, 0, 0);
             }
             if (type == 473)
             {
                 return new Color(255, 255, 255, 255);
             }
             if (type == 50 || type == 53 || type == 515 || type == 870)
             {
                 return new Color(255, 255, 255, 0);
             }
             if (type == 723 || type == 724 || type == 725 || type == 726 || type == 728 || type == 9)
             {
                 return new Color(255, 255, 255, 0) * Opacity;
             }
             if (type == 92)
             {
                 return new Color(255, 255, 255, 0);
             }
             if (type == 91)
             {
                 return new Color(200, 200, 200, 0);
             }
             if (type == 34 || type == 15 || type == 93 || type == 94 || type == 95 || type == 96 || type == 253 || type == 258 || (type == 102 && alpha < 255))
             {
                 return new Color(200, 200, 200, 25);
             }
             if (type == 465)
             {
                 return new Color(255, 255, 255, 0) * (1f - (float)alpha / 255f);
             }
             if (type == 503)
             {
                 Color value2 = Color.Lerp(newColor, Color.White, 0.5f) * (1f - (float)alpha / 255f);
                 Color value3 = Color.Lerp(Color.Purple, Color.White, 0.33f);
                 float amount2 = 0.25f + (float)Math.Cos(localAI[0]) * 0.25f;
                 return Color.Lerp(value2, value3, amount2);
             }
             if (type == 467)
             {
                 return new Color(255, 255, 255, 255) * (1f - (float)alpha / 255f);
             }
             if (type == 694 || type == 695 || type == 696)
             {
                 return new Color(255, 255, 255, 127) * (1f - (float)alpha / 255f);
             }
             if (type == 634 || type == 635)
             {
                 return new Color(255, 255, 255, 127) * Opacity;
             }
             if (type == 671)
             {
                 return new Color(255, 255, 255, 255) * Opacity;
             }
             if (type == 664 || type == 666 || type == 668)
             {
                 newColor = Color.Lerp(newColor, Color.White, 0.5f);
                 return new Color(newColor.R, newColor.G, newColor.B, 200) * Opacity;
             }
             if (type == 451)
             {
                 return new Color(255, 255, 255, 200) * ((255f - (float)alpha) / 255f);
             }
             if (type == 684)
             {
                 return new Color(255, 255, 255, 200) * ((255f - (float)alpha) / 255f);
             }
             if (type == 454 || type == 452)
             {
                 return new Color(255, 255, 255, 255) * (1f - (float)alpha / 255f);
             }
             if (type == 464)
             {
                 return new Color(255, 255, 255, 255) * ((255f - (float)alpha) / 255f);
             }
             if (type == 450)
             {
                 return new Color(200, 200, 200, 255 - alpha);
             }
             if (type == 459 || type == 709)
             {
                 return new Color(255, 255, 255, 200);
             }
             if (type == 447)
             {
                 return new Color(255, 255, 255, 200);
             }
             if (type == 446)
             {
                 return Color.Lerp(newColor, Color.White, 0.8f) * (1f - (float)alpha / 255f);
             }
             if (type == 691 || type == 692 || type == 693)
             {
                 return Color.Lerp(newColor, Color.White, 0.4f) * (1f - (float)alpha / 255f);
             }
             if (type >= 646 && type <= 649)
             {
                 return Color.Lerp(newColor, Color.White, 0.8f) * (1f - (float)alpha / 255f);
             }
             if (type == 445)
             {
                 return new Color(255, 255, 255, 128) * (1f - (float)alpha / 255f);
             }
             if (type == 440 || type == 449 || type == 606)
             {
                 r = 255 - alpha;
                 g = 255 - alpha;
                 b = 255 - alpha;
             }
             else
             {
                 if (type == 444)
                 {
                     return newColor * (1f - (float)alpha / 255f);
                 }
                 if (type == 443 || type == 675 || type == 686 || type == 711)
                 {
                     return new Color(255, 255, 255, 128) * (1f - (float)alpha / 255f);
                 }
                 if (type == 676)
                 {
                     return newColor * Opacity;
                 }
                 if (type == 438)
                 {
                     return new Color(255, 255, 255, 128) * (1f - (float)alpha / 255f);
                 }
                 if (type == 592)
                 {
                     return new Color(255, 255, 255, 128) * (1f - (float)alpha / 255f);
                 }
                 if (type == 437 || type == 700)
                 {
                     return new Color(255, 255, 255, 0) * (1f - (float)alpha / 255f);
                 }
                 if (type == 964 || type == 965)
                 {
                     return new Color(255, 255, 255, 255) * Opacity;
                 }
                 if (type == 462)
                 {
                     return new Color(255, 255, 255, 128) * (1f - (float)alpha / 255f);
                 }
                 if (type == 352)
                 {
                     Color color2 = Color.Lerp(newColor, Color.White, 0.5f);
                     color2.A = (byte)((float)(int)color2.A * ((float)alpha / 255f));
                     return new Color(color2.R, color2.G, color2.B, color2.A);
                 }
                 if (type == 435 || type == 732 || type == 731)
                 {
                     newColor = Color.Lerp(newColor, Color.White, 0.8f);
                     return new Color(newColor.R, newColor.G, newColor.B, 25);
                 }
                 if (type == 682)
                 {
                     newColor = Color.Lerp(newColor, Color.White, 0.8f);
                     return new Color(newColor.R, newColor.G, newColor.B, 127);
                 }
                 if (type == 436)
                 {
                     newColor = Color.Lerp(newColor, Color.White, 0.8f);
                     return new Color(newColor.R, newColor.G, newColor.B, 25);
                 }
                 if (type == 409)
                 {
                     return new Color(250, 250, 250, 200);
                 }
                 if (type == 348 || type == 349)
                 {
                     return new Color(200, 200, 200, alpha);
                 }
                 if (type == 337)
                 {
                     return new Color(250, 250, 250, 150);
                 }
                 if (type >= 424 && type <= 426)
                 {
                     byte b2 = 150;
                     if (newColor.R < b2)
                     {
                         newColor.R = b2;
                     }
                     if (newColor.G < b2)
                     {
                         newColor.G = b2;
                     }
                     if (newColor.B < b2)
                     {
                         newColor.B = b2;
                     }
                     return new Color(newColor.R, newColor.G, newColor.B, 255);
                 }
                 if (type == 431 || type == 432)
                 {
                     return new Color(250, 250, 250, 255 - alpha);
                 }
                 if (type == 343 || type == 344)
                 {
                     float num5 = 1f - (float)alpha / 255f;
                     return new Color((int)(250f * num5), (int)(250f * num5), (int)(250f * num5), (int)(100f * num5));
                 }
                 if (type == 332)
                 {
                     return new Color(255, 255, 255, 255);
                 }
                 if (type == 329)
                 {
                     return new Color(200, 200, 200, 50);
                 }
                 if (type >= 326 && type <= 328)
                 {
                     return Color.Transparent;
                 }
                 if (type >= 400 && type <= 402)
                 {
                     return Color.Transparent;
                 }
                 if (type == 324 && frame >= 6 && frame <= 9)
                 {
                     return new Color(255, 255, 255, 255);
                 }
                 if (type == 16)
                 {
                     return new Color(255, 255, 255, 0);
                 }
                 if (type == 321)
                 {
                     return new Color(200, 200, 200, 0);
                 }
                 if (type == 76 || type == 77 || type == 78)
                 {
                     return new Color(255, 255, 255, 0);
                 }
                 if (type == 308)
                 {
                     return new Color(200, 200, 255, 125);
                 }
                 if (type == 263)
                 {
                     if (timeLeft < 255)
                     {
                         return new Color(255, 255, 255, (byte)timeLeft);
                     }
                     return new Color(255, 255, 255, 255);
                 }
                 if (type == 274)
                 {
                     if (timeLeft < 85)
                     {
                         byte b3 = (byte)(timeLeft * 3);
                         byte a3 = (byte)(100f * ((float)(int)b3 / 255f));
                         return new Color(b3, b3, b3, a3);
                     }
                     return new Color(255, 255, 255, 100);
                 }
                 if (type == 5)
                 {
                     return new Color(255, 255, 255, 0);
                 }
                 if (type == 300)
                 {
                     return new Color(250, 250, 250, 50);
                 }
                 if (type == 301)
                 {
                     if (ai[0] == 1f)
                     {
                         return newColor;
                     }
                     return new Color(250, 250, 250, 50);
                 }
                 if (type == 712)
                 {
                     return Color.Lerp(newColor, Color.White, 0.4f) * Opacity;
                 }
                 if (type == 304)
                 {
                     return new Color(255 - alpha, 255 - alpha, 255 - alpha, (byte)((float)(255 - alpha) / 3f));
                 }
                 if (type == 116 || type == 132 || type == 156 || type == 157 || type == 157 || type == 173)
                 {
                     if (localAI[1] >= 15f)
                     {
                         return new Color(255, 255, 255, alpha);
                     }
                     if (localAI[1] < 5f)
                     {
                         return Color.Transparent;
                     }
                     int num6 = (int)((localAI[1] - 5f) / 10f * 255f);
                     return new Color(num6, num6, num6, num6);
                 }
                 if (type == 254)
                 {
                     if (timeLeft < 30)
                     {
                         float num7 = (float)timeLeft / 30f;
                         alpha = (int)(255f - 255f * num7);
                     }
                     return new Color(255 - alpha, 255 - alpha, 255 - alpha, 0);
                 }
                 if (type == 265 || type == 355)
                 {
                     if (alpha > 0)
                     {
                         return Color.Transparent;
                     }
                     return new Color(255, 255, 255, 0);
                 }
                 if (type == 257)
                 {
                     if (alpha > 200)
                     {
                         return Color.Transparent;
                     }
                     return new Color(255 - alpha, 255 - alpha, 255 - alpha, 0);
                 }
                 if (type == 259)
                 {
                     if (alpha > 200)
                     {
                         return Color.Transparent;
                     }
                     return new Color(255 - alpha, 255 - alpha, 255 - alpha, 0);
                 }
                 if (type >= 150 && type <= 152)
                 {
                     return new Color(255 - alpha, 255 - alpha, 255 - alpha, 255 - alpha);
                 }
                 if (type == 250)
                 {
                     return Color.Transparent;
                 }
                 if (type == 251)
                 {
                     r = 255 - alpha;
                     g = 255 - alpha;
                     b = 255 - alpha;
                     return new Color(r, g, b, 0);
                 }
                 if (type == 131)
                 {
                     return new Color(255 - alpha, 255 - alpha, 255 - alpha, 0);
                 }
                 if (type == 211)
                 {
                     return new Color(255, 255, 255, 0);
                 }
                 if (type == 229)
                 {
                     return new Color(255, 255, 255, 50);
                 }
                 if (type == 221 || type == 729 || type == 977)
                 {
                     return new Color(255, 255, 255, 200);
                 }
                 if (type == 20)
                 {
                     if (alpha <= 150)
                     {
                         return new Color(255, 255, 255, 0);
                     }
                     return new Color(0, 0, 0, 0);
                 }
                 if (type == 207)
                 {
                     r = 255 - alpha;
                     g = 255 - alpha;
                     b = 255 - alpha;
                 }
                 else
                 {
                     if (type == 242)
                     {
                         if (alpha < 140)
{
                             return new Color(255, 255, 255, 100);
                         }
                         return Color.Transparent;
                     }
                     if (type == 638)
                     {
                         return new Color(255, 255, 255, 100) * Opacity;
                     }
                     if (type == 660)
                     {
                         return new Color(150, 255, 255, 0) * Opacity;
                     }
                     if (type == 209)
                     {
                         r = newColor.R - alpha;
                         g = newColor.G - alpha;
                         b = newColor.B - alpha / 2;
                     }
                     else
                     {
                         if (type == 130)
{
                             return new Color(255, 255, 255, 175);
                         }
                         if (type == 182)
{
                             return new Color(255, 255, 255, 200);
                         }
                         if (type == 226)
{
                             r = 255;
                             g = 255;
                             b = 255;
                             float num8 = (float)(int)Main.mouseTextColor / 200f - 0.3f;
                             r = (int)((float)r * num8);
                             g = (int)((float)g * num8);
                             b = (int)((float)b * num8);
                             r += 50;
                             if (r > 255)
{
                                 r = 255;
                             }
                             g += 50;
                             if (g > 255)
{
                                 g = 255;
                             }
                             b += 50;
                             if (b > 255)
{
                                 b = 255;
                             }
                             return new Color(r, g, b, 200);
                         }
                         if (type == 227)
{
                             r = (g = (b = 255));
                             float num9 = (float)(int)Main.mouseTextColor / 100f - 1.6f;
                             r = (int)((float)r * num9);
                             g = (int)((float)g * num9);
                             b = (int)((float)b * num9);
                             int a4 = (int)(100f * num9);
                             r += 50;
                             if (r > 255)
{
                                 r = 255;
                             }
                             g += 50;
                             if (g > 255)
{
                                 g = 255;
                             }
                             b += 50;
                             if (b > 255)
{
                                 b = 255;
                             }
                             return new Color(r, g, b, a4);
                         }
                         if (type == 114 || type == 115)
{
                             if (localAI[1] >= 15f)
{
                                 return new Color(255, 255, 255, alpha);
                             }
                             if (localAI[1] < 5f)
{
                                 return Color.Transparent;
                             }
                             int num10 = (int)((localAI[1] - 5f) / 10f * 255f);
                             return new Color(num10, num10, num10, num10);
                         }
                         if (type == 83 || type == 88 || type == 89 || type == 90 || type == 100 || type == 104 || type == 279 || (type >= 283 && type <= 287) || type == 876)
{
                             if (alpha < 200)
{
                                 return new Color(255 - alpha, 255 - alpha, 255 - alpha, 0);
                             }
                             return Color.Transparent;
                         }
                         if (type == 34 || type == 35 || type == 15 || type == 19 || type == 44 || type == 45)
{
                             return Color.White;
                         }
                         if (type == 79)
{
                             r = Main.DiscoR;
                             g = Main.DiscoG;
                             b = Main.DiscoB;
                             return default(Color);
                         }
                         if (type == 9 || type == 15 || type == 34 || type == 50 || type == 53 || type == 76 || type == 77 || type == 78 || type == 92 || type == 91)
{
                             r = newColor.R - alpha / 3;
                             g = newColor.G - alpha / 3;
                             b = newColor.B - alpha / 3;
                         }
                         else
{
                             if (type == 18)
{
                                 return new Color(255, 255, 255, 50);
                             }
                             if (type == 16 || type == 44 || type == 45)
{
                                 r = newColor.R;
                                 g = newColor.G;
                                 b = newColor.B;
                             }
                             else if (type == 12 || type == 72 || type == 86 || type == 87 || type == 955)
{
                                 return new Color(255, 255, 255, newColor.A - alpha);
                             }
                         }
                     }
                 }
             }
         }
         float num11 = (float)(255 - alpha) / 255f;
         r = (int)((float)(int)newColor.R * num11);
         g = (int)((float)(int)newColor.G * num11);
         b = (int)((float)(int)newColor.B * num11);
         int num12 = newColor.A - alpha;
         if (num12 < 0)
         {
             num12 = 0;
         }
         if (num12 > 255)
         {
             num12 = 255;
         }
         return new Color(r, g, b, num12);
     }
References Color, Main.DiscoB, Main.DiscoG, Main.DiscoR, PortalHelper.GetPortalColor(), WorldGen.InWorld(), Main.mouseTextColor, Main.player, WorldGen.SolidTile(), Entity.wet, and Utils.WrappedLerp().
Referenced by Main.DrawKite(), Main.DrawMultisegmentPet(), Main.DrawProj_PiercingStarlight(), Main.DrawProj_Spear(), Main.DrawProjDirect(), Main.DrawTwinsPet(), Main.DrawWhip_CoolWhip(), and Main.DrawWhip_FireWhip().