Terraria: Projectile.AI_144_DD2Pet
AI_144_DD2Pet()
void Projectile.AI_144_DD2Pet () inline private
     {
         Player player = Main.player[owner];
         float num = 4f;
         int num2 = 6;
         int num3 = 4;
         int num4 = Main.projFrames[type];
         int num5 = 0;
         float num6 = 0.08f;
         bool flag = false;
         float num7 = 0.1f;
         Vector2 vector = new Vector2(player.direction * 30, -20f);
         if (player.dead)
         {
             Kill();
             return;
         }
         bool flag2 = true;
         switch (type)
         {
         case 702:
         {
             if (player.petFlagDD2Ghost)
             {
                 timeLeft = 2;
             }
             vector.Y += (float)Math.Cos(localAI[0] * ((float)Math.PI / 60f)) * 2f;
             num3 = 4;
             num2 = 10;
             flag2 = false;
             num = 6f;
             Vector2 vector3 = new Vector2((spriteDirection == -1) ? (-6) : (-2), -26f).RotatedBy(rotation);
             if (Main.rand.Next(24) == 0)
             {
                 Dust dust2 = Dust.NewDustDirect(base.Center + vector3, 4, 4, 135, 0f, 0f, 100);
                 if (Main.rand.Next(3) != 0)
                 {
                     dust2.noGravity = true;
                     dust2.velocity.Y -= 3f;
                     dust2.noLight = true;
                 }
                 else if (Main.rand.Next(2) != 0)
                 {
                     dust2.noLight = true;
                 }
                 dust2.velocity *= 0.5f;
                 dust2.velocity.Y -= 0.9f;
                 dust2.scale += 0.1f + Main.rand.NextFloat() * 0.6f;
             }
             DelegateMethods.v3_1 = new Vector3(0.3f, 0.5f, 1f);
             Utils.PlotTileLine(base.Center, base.Center + velocity * 6f, 20f, DelegateMethods.CastLightOpen);
             Utils.PlotTileLine(base.Left, base.Right, 20f, DelegateMethods.CastLightOpen);
             Utils.PlotTileLine(player.Center, player.Center + player.velocity * 6f, 40f, DelegateMethods.CastLightOpen);
             Utils.PlotTileLine(player.Left, player.Right, 40f, DelegateMethods.CastLightOpen);
             break;
         }
         case 703:
             if (player.petFlagDD2Gato)
             {
                 timeLeft = 2;
             }
             vector.Y += (float)Math.Cos(localAI[0] * ((float)Math.PI / 30f)) * 2f;
             num2 = 4;
             num3 = 2;
             num = 3f;
             num4 = 4;
             break;
         case 701:
             if (player.petFlagDD2Dragon)
             {
                 timeLeft = 2;
             }
             break;
         case 764:
         {
             num7 = 0.025f;
             num6 = 0.04f;
             flag = true;
             localAI[0] += 1f;
             if (localAI[0] > 120f)
             {
                 localAI[0] = 0f;
             }
             localAI[1] += velocity.X * 0.01f;
             localAI[1] += 1f / 120f;
             if (localAI[1] < (float)Math.PI * -2f)
             {
                 localAI[1] += (float)Math.PI * 2f;
             }
             if (localAI[1] > (float)Math.PI * 2f)
             {
                 localAI[1] -= (float)Math.PI * 2f;
             }
             if (velocity.Length() < 4f)
             {
                 localAI[1] *= 0.9f;
                 if (velocity.Length() > 0.1f && Main.rand.Next(30) == 0)
                 {
                     Dust dust = Dust.NewDustDirect(position - velocity, width, height, 292, velocity.X * 0.5f, velocity.Y * 0.5f, 150);
                     dust.velocity *= 0.3f;
                     dust.noLightEmittence = true;
                 }
             }
             else
             {
                 Vector2 vector2 = new Vector2(Main.screenWidth, Main.screenHeight);
                 base.Hitbox.Intersects(Utils.CenteredRectangle(Main.screenPosition + vector2 / 2f, vector2 + new Vector2(400f)));
                 if (Main.rand.Next(15) == 0)
                 {
                     Dust.NewDustDirect(position - velocity, width, height, 292, velocity.X * 0.5f, velocity.Y * 0.5f, 150, default(Color), 0.9f).noLightEmittence = true;
                 }
             }
             float num8 = localAI[0] / 120f * 2f;
             if (num8 > 1f)
             {
                 num8 = 2f - num8;
             }
             Opacity = MathHelper.Lerp(0.4f, 0.75f, num8);
             vector.Y += (float)Math.Cos(localAI[0] / 120f * ((float)Math.PI * 2f)) * 2f;
             if (player.petFlagUpbeatStar)
             {
                 timeLeft = 2;
             }
             break;
         }
         }
         if (flag2 && (player.suspiciouslookingTentacle || player.petFlagDD2Ghost))
         {
             vector.X += -player.direction * 64;
         }
         direction = (spriteDirection = player.direction);
         Vector2 vector4 = player.MountedCenter + vector;
         float num9 = Vector2.Distance(base.Center, vector4);
         if (num9 > 1000f)
         {
             base.Center = player.Center + vector;
         }
         Vector2 vector5 = vector4 - base.Center;
         if (num9 < num)
         {
             velocity *= 0.25f;
         }
         if (vector5 != Vector2.Zero)
         {
             if (vector5.Length() < num * 0.5f)
             {
                 velocity = vector5;
             }
             else
             {
                 velocity = vector5 * num7;
             }
         }
         if (velocity.Length() > 6f)
         {
             float num10 = velocity.X * num6 + velocity.Y * (float)spriteDirection * 0.02f;
             if (Math.Abs(rotation - num10) >= (float)Math.PI)
             {
                 if (num10 < rotation)
                 {
                     rotation -= (float)Math.PI * 2f;
                 }
                 else
                 {
                     rotation += (float)Math.PI * 2f;
                 }
             }
             float num11 = 12f;
             rotation = (rotation * (num11 - 1f) + num10) / num11;
             if (++frameCounter >= num3)
             {
                 frameCounter = 0;
                 if (++frame >= num4)
                 {
                     frame = num5;
                 }
             }
         }
         else
         {
             if (rotation > (float)Math.PI)
             {
                 rotation -= (float)Math.PI * 2f;
             }
             if (rotation > -0.005f && rotation < 0.005f)
             {
                 rotation = 0f;
             }
             else
             {
                 rotation *= 0.96f;
             }
             if (++frameCounter >= num2)
             {
                 frameCounter = 0;
                 if (++frame >= num4)
                 {
                     frame = num5;
                 }
             }
         }
         if (!flag)
         {
             localAI[0] += 1f;
             if (localAI[0] > 120f)
             {
                 localAI[0] = 0f;
             }
         }
     }
References DelegateMethods.CastLightOpen(), Entity.Center, Utils.CenteredRectangle(), Color, Player.dead, Entity.direction, Entity.Left, Player.MountedCenter, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Player.petFlagDD2Dragon, Player.petFlagDD2Gato, Player.petFlagDD2Ghost, Player.petFlagUpbeatStar, Main.player, Utils.PlotTileLine(), Main.projFrames, Main.rand, Entity.Right, Dust.scale, Main.screenHeight, Main.screenPosition, Main.screenWidth, Player.suspiciouslookingTentacle, DelegateMethods.v3_1, Dust.velocity, and Entity.velocity.