Terraria: Projectile.StatusNPC
StatusNPC()
void Projectile.StatusNPC (int i) inline
     {
         NPC nPC = Main.npc[i];
         if ((melee || ProjectileID.Sets.IsAWhip[type]) && Main.player[owner].meleeEnchant > 0 && !noEnchantments)
         {
             byte meleeEnchant = Main.player[owner].meleeEnchant;
             if (meleeEnchant == 1)
             {
                 nPC.AddBuff(70, 60 * Main.rand.Next(5, 10));
             }
             if (meleeEnchant == 2)
             {
                 nPC.AddBuff(39, 60 * Main.rand.Next(3, 7));
             }
             if (meleeEnchant == 3)
             {
                 nPC.AddBuff(24, 60 * Main.rand.Next(3, 7));
             }
             if (meleeEnchant == 5)
             {
                 nPC.AddBuff(69, 60 * Main.rand.Next(10, 20));
             }
             if (meleeEnchant == 6)
             {
                 nPC.AddBuff(31, 60 * Main.rand.Next(1, 4));
             }
             if (meleeEnchant == 8)
             {
                 nPC.AddBuff(20, 60 * Main.rand.Next(5, 10));
             }
             if (meleeEnchant == 4)
             {
                 nPC.AddBuff(72, 120);
             }
         }
         if (type == 195)
         {
             nPC.AddBuff(70, 60 * Main.rand.Next(5, 11));
         }
         if (type == 119)
         {
             nPC.AddBuff(324, 240);
         }
         if (type == 309)
         {
             nPC.AddBuff(324, 300);
         }
         if (type == 359)
         {
             nPC.AddBuff(324, 420);
         }
         switch (type)
         {
         case 841:
             nPC.AddBuff(307, 240);
             break;
         case 952:
             nPC.AddBuff(326, 240);
             break;
         case 847:
             nPC.AddBuff(309, 240);
             break;
         case 849:
             nPC.AddBuff(310, 240);
             break;
         case 913:
             if (localAI[0] == 0f)
             {
                 nPC.AddBuff(313, 240);
             }
             nPC.AddBuff(323, 240);
             break;
         case 912:
             nPC.AddBuff(340, 240);
             nPC.AddBuff(324, 240);
             break;
         case 914:
             nPC.AddBuff(315, 240);
             if (Main.rand.Next(5) == 0)
             {
                 nPC.AddBuff(20, 180);
             }
             break;
         case 848:
             nPC.AddBuff(319, 240);
             break;
         case 915:
             nPC.AddBuff(316, 240);
             break;
         }
         if (type == 664 && Main.rand.Next(3) == 0)
         {
             nPC.AddBuff(24, 60 * Main.rand.Next(3, 6));
         }
         if (type == 666 && Main.rand.Next(2) == 0)
         {
             nPC.AddBuff(323, 60 * Main.rand.Next(3, 9));
         }
         if (type == 668 && Main.rand.Next(3) != 0)
         {
             nPC.AddBuff(323, 60 * Main.rand.Next(6, 9));
         }
         if (type == 567 || type == 568)
         {
             nPC.AddBuff(20, 60 * Main.rand.Next(5, 11));
         }
         if (type == 598 && ai[1] == (float)i)
         {
             nPC.AddBuff(169, 900);
         }
         if (type == 636 && ai[1] == (float)i)
         {
             nPC.AddBuff(189, 300);
         }
         if (type == 971 && ai[1] == (float)i)
         {
             nPC.AddBuff(337, 540);
         }
         if (type == 975 && ai[1] == (float)i)
         {
             nPC.AddBuff(344, 540);
         }
         if (type == 611)
         {
             nPC.AddBuff(189, 300);
         }
         if (type == 612)
         {
             nPC.AddBuff(189, 300);
         }
         if (type == 978)
         {
             nPC.AddBuff(24, 180);
         }
         if (type == 953)
         {
             nPC.AddBuff(189, 300);
         }
         if (type == 711)
         {
             nPC.AddBuff(203, 600);
         }
         if (type == 706)
         {
             nPC.AddBuff(323, 480);
         }
         if (type == 614 && ai[1] == (float)i)
         {
             nPC.AddBuff(183, 900);
         }
         if (type == 585)
         {
             nPC.AddBuff(153, 60 * Main.rand.Next(5, 11));
         }
         if (type == 583)
         {
             nPC.AddBuff(20, 60 * Main.rand.Next(3, 6));
         }
         if (type == 524)
         {
             nPC.AddBuff(69, 60 * Main.rand.Next(3, 8));
         }
         if (type == 954 && Main.rand.Next(2) == 0)
         {
             int num = 24;
             if (Main.remixWorld)
             {
                 num = 323;
             }
             if (Main.rand.Next(3) == 0)
             {
                 nPC.AddBuff(num, Main.rand.Next(60, 240));
             }
             else
             {
                 nPC.AddBuff(num, Main.rand.Next(60, 120));
             }
         }
         if (type == 504 && Main.rand.Next(2) == 0)
         {
             if (Main.rand.Next(3) == 0)
             {
                 nPC.AddBuff(323, Main.rand.Next(60, 240));
             }
             else
             {
                 nPC.AddBuff(323, Main.rand.Next(60, 120));
             }
         }
         if (type == 979 && Main.rand.Next(2) == 0)
         {
             int num2 = 44;
             if (Main.remixWorld)
             {
                 num2 = 324;
             }
             if (Main.rand.Next(3) == 0)
             {
                 nPC.AddBuff(num2, Main.rand.Next(60, 240));
             }
             else
             {
                 nPC.AddBuff(num2, Main.rand.Next(60, 120));
             }
         }
         if ((type == 694 || type == 695 || type == 696) && Main.player[owner].setHuntressT2)
         {
             nPC.AddBuff(204, Main.rand.Next(8, 18) * 30);
         }
         if (type == 545 && Main.rand.Next(3) == 0)
         {
             nPC.AddBuff(24, Main.rand.Next(60, 240));
         }
         if (type == 553)
         {
             nPC.AddBuff(323, Main.rand.Next(180, 480));
         }
         if (type == 552 && Main.rand.Next(3) != 0)
         {
             nPC.AddBuff(324, Main.rand.Next(120, 320));
         }
         if (type == 495)
         {
             nPC.AddBuff(153, Main.rand.Next(120, 300));
         }
         if (type == 497)
         {
             nPC.AddBuff(153, Main.rand.Next(60, 180));
         }
         if (type == 496)
         {
             nPC.AddBuff(153, Main.rand.Next(240, 480));
         }
         if (type == 46)
         {
             nPC.AddBuff(153, Main.rand.Next(240, 300));
         }
         if (type == 476)
         {
             nPC.AddBuff(151, 30);
         }
         if (type == 523)
         {
             nPC.AddBuff(20, 60 * Main.rand.Next(10, 30));
         }
         if (type == 478 || type == 480)
         {
             nPC.AddBuff(39, 60 * Main.rand.Next(3, 7));
         }
         if (type == 479)
         {
             nPC.AddBuff(69, 60 * Main.rand.Next(7, 15));
         }
         if (type == 379)
         {
             nPC.AddBuff(70, 60 * Main.rand.Next(2, 5));
         }
         if (type >= 390 && type <= 392)
         {
             nPC.AddBuff(70, 60 * Main.rand.Next(2, 5));
         }
         if (type == 374)
         {
             nPC.AddBuff(20, 60 * Main.rand.Next(4, 7));
         }
         if (type == 376)
         {
             nPC.AddBuff(24, 60 * Main.rand.Next(3, 7));
         }
         if (type >= 399 && type <= 402)
         {
             nPC.AddBuff(24, 60 * Main.rand.Next(3, 7));
         }
         if (type == 295 || type == 296)
         {
             nPC.AddBuff(323, 60 * Main.rand.Next(8, 16));
         }
         if ((melee || ranged) && !npcProj && Main.player[owner].frostBurn && !noEnchantments)
         {
             nPC.AddBuff(324, 60 * Main.rand.Next(5, 15));
         }
         if (melee && Main.player[owner].magmaStone && !noEnchantments)
         {
             if (Main.rand.Next(7) == 0)
             {
                 nPC.AddBuff(323, 360);
             }
             else if (Main.rand.Next(3) == 0)
             {
                 nPC.AddBuff(323, 120);
             }
             else
             {
                 nPC.AddBuff(323, 60);
             }
         }
         if (type == 287)
         {
             nPC.AddBuff(72, 120);
         }
         if (type == 285)
         {
             if (Main.rand.Next(3) == 0)
             {
                 nPC.AddBuff(31, 180);
             }
             else
             {
                 nPC.AddBuff(31, 60);
             }
         }
         if (type == 2 && Main.rand.Next(3) == 0)
         {
             nPC.AddBuff(24, 180);
         }
         if (type == 172)
         {
             if (Main.rand.Next(3) == 0)
             {
                 nPC.AddBuff(44, 180);
             }
         }
         else if (type == 15)
         {
             int num3 = 24;
             if (Main.remixWorld)
             {
                 num3 = 323;
             }
             if (Main.rand.Next(2) == 0)
             {
                 nPC.AddBuff(num3, 300);
             }
         }
         else if (type == 253)
         {
             nPC.AddBuff(324, 480);
         }
         else if (type == 19)
         {
             if (Main.rand.Next(2) == 0)
             {
                 nPC.AddBuff(24, 360);
             }
         }
         else if (type == 113)
         {
             if (Main.rand.Next(2) == 0)
             {
                 nPC.AddBuff(44, 180);
             }
         }
         else if (type == 33)
         {
             if (Main.rand.Next(2) == 0)
             {
                 nPC.AddBuff(20, 420);
             }
         }
         else if (type == 976)
         {
             if (Main.rand.Next(4) == 0)
             {
                 nPC.AddBuff(20, 420);
             }
         }
         else if (type == 34)
         {
             if (Main.rand.Next(2) == 0)
             {
                 nPC.AddBuff(24, Main.rand.Next(240, 480));
             }
         }
         else if (type == 948)
         {
             if (Main.rand.Next(6) == 0)
             {
                 nPC.AddBuff(24, 60 * Main.rand.Next(2, 4));
             }
         }
         else if (type == 35)
         {
             if (Main.rand.Next(2) == 0)
             {
                 nPC.AddBuff(24, 300);
             }
         }
         else if (type == 54)
         {
             if (Main.rand.Next(2) == 0)
             {
                 nPC.AddBuff(20, 600);
             }
         }
         else if (type == 267)
         {
             if (Main.rand.Next(3) == 0)
             {
                 nPC.AddBuff(20, 3600);
             }
             else
             {
                 nPC.AddBuff(20, 1800);
             }
         }
         else if (type == 63)
         {
             if (Main.rand.Next(5) != 0)
             {
                 nPC.AddBuff(31, 60 * Main.rand.Next(2, 5));
             }
         }
         else if (type == 85)
         {
             int num4 = ((ai[0] == 1f) ? 324 : 323);
             nPC.AddBuff(num4, 1200);
         }
         else if (type == 188)
         {
             nPC.AddBuff(323, 1200);
         }
         else if (type == 95 || type == 103 || type == 104 || type == 482)
         {
             nPC.AddBuff(39, 420);
         }
         else if (type == 278 || type == 279 || type == 280)
         {
             nPC.AddBuff(69, 600);
         }
         else if (type == 282 || type == 283)
         {
             nPC.AddBuff(70, 600);
         }
         if (type == 163 || type == 310 || type == 1008 || type == 1010 || type == 1011)
         {
             if (Main.rand.Next(3) == 0)
             {
                 nPC.AddBuff(24, 600);
             }
             else
             {
                 nPC.AddBuff(24, 300);
             }
         }
         if (type == 1009)
         {
             nPC.AddBuff(39, 600);
         }
         else if (type == 98)
         {
             nPC.AddBuff(20, 600);
         }
         else if (type == 184)
         {
             nPC.AddBuff(20, 900);
         }
         else if (type == 980)
         {
             nPC.AddBuff(70, 300);
         }
         else if (type == 265)
         {
             nPC.AddBuff(20, 1800);
         }
         else if (type == 355)
         {
             nPC.AddBuff(70, 1800);
         }
     }
References NPC.AddBuff(), ai, Player.frostBurn, ProjectileID.Sets.IsAWhip, localAI, Player.magmaStone, melee, Player.meleeEnchant, UnifiedRandom.Next(), noEnchantments, Main.npc, npcProj, owner, Main.player, Main.rand, ranged, Main.remixWorld, Player.setHuntressT2, and type.
Referenced by Player.BloodButcherer_TryButchering(), Damage(), and Player.TentacleSpike_TrySpiking().