Terraria: Projectile.GetFairyQueenWeaponsColor
GetFairyQueenWeaponsColor()
Color Projectile.GetFairyQueenWeaponsColor (float alphaChannelMultiplier = 1f, float lerpToWhite = 0f, float? rawHueOverride = null) inline
     {
         float num = ai[1];
         if (rawHueOverride.HasValue)
         {
             num = rawHueOverride.Value;
         }
         float num2 = (num + 0.5f) % 1f;
         float saturation = 1f;
         float luminosity = 0.5f;
         if (Main.player[owner].active)
         {
             switch (Main.player[owner].name)
             {
             case "Cenx":
             {
                 float amount13 = Utils.PingPongFrom01To010(num2);
                 amount13 = MathHelper.SmoothStep(0f, 1f, amount13);
                 amount13 = MathHelper.SmoothStep(0f, 1f, amount13);
                 Color color3 = Color.Lerp(new Color(0.3f, 1f, 0.2f), Color.HotPink, amount13);
                 if (lerpToWhite != 0f)
                 {
                     color3 = Color.Lerp(color3, Color.White, lerpToWhite);
                 }
                 color3.A = (byte)((float)(int)color3.A * alphaChannelMultiplier);
                 return color3;
             }
             case "Crowno":
                 luminosity = MathHelper.Lerp(0.25f, 0.4f, Utils.Turn01ToCyclic010(num2));
                 num2 = MathHelper.Lerp(127f / 180f, 47f / 60f, Utils.Turn01ToCyclic010(num2));
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                 break;
             case "Yoraiz0r":
                 num2 = MathHelper.Lerp(0.9f, 0.95f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 break;
             case "Jaxrud":
                 num2 = MathHelper.Lerp(13f / 72f, 0.43611112f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 break;
             case "Lazure":
                 num2 = MathHelper.Lerp(8f / 15f, 83f / 90f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 break;
             case "Leinfors":
                 num2 = MathHelper.Lerp(0.7f, 0.77f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 break;
             case "Grox The Great":
                 num2 = MathHelper.Lerp(0.31f, 0.5f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 1f, 0.8f);
                 break;
             case "Acamaeda":
                 num2 = MathHelper.Lerp(0.06f, 0.28f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                 break;
             case "Alchemystics":
                 num2 = MathHelper.Lerp(0.74f, 0.96f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.6f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                 break;
             case "Antithesis":
             {
                 num2 = 0.51f;
                 float amount14 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0f, 0.5f, amount14);
                 break;
             }
             case "Aurora3500":
                 num2 = MathHelper.Lerp(0.33f, 0.8f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                 break;
             case "Bame":
             {
                 float amount12 = Utils.PingPongFrom01To010(num2);
                 amount12 = MathHelper.SmoothStep(0f, 1f, amount12);
                 amount12 = MathHelper.SmoothStep(0f, 1f, amount12);
                 Color color2 = Color.Lerp(Color.Yellow, new Color(0.4f, 0f, 0.75f), amount12);
                 if (lerpToWhite != 0f)
                 {
                     color2 = Color.Lerp(color2, Color.White, lerpToWhite);
                 }
                 color2.A = (byte)((float)(int)color2.A * alphaChannelMultiplier);
                 return color2;
             }
             case "Criddle":
                 num2 = MathHelper.Lerp(0.05f, 0.15f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                 break;
             case "Darthkitten":
             {
                 num2 = 1f;
                 float amount11 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(1f, 0.4f, amount11);
                 break;
             }
             case "darthmorf":
             {
                 num2 = 0f;
                 float amount10 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0f, 0.2f, amount10);
                 break;
             }
             case "Discipile":
             {
                 num2 = 0.53f;
                 float amount9 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0.05f, 0.5f, amount9);
                 break;
             }
             case "Doylee":
                 num2 = MathHelper.Lerp(0.68f, 1f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                 break;
             case "Ghostar":
             {
                 num2 = 0.66f;
                 float amount8 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0.15f, 0.85f, amount8);
                 break;
             }
             case "Jenosis":
                 num2 = MathHelper.Lerp(0.9f, 1.13f, Utils.Turn01ToCyclic010(num2)) % 1f;
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                 break;
             case "Kazzymodus":
             {
                 num2 = 0.33f;
                 float amount7 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0.15f, 0.4f, amount7);
                 break;
             }
             case "Khaios":
             {
                 num2 = 0.33f;
                 float amount6 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0f, 0.2f, amount6);
                 break;
             }
             case "Loki":
             {
                 num2 = 0f;
                 float amount5 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0f, 0.25f, amount5);
                 break;
             }
             case "ManaUser":
                 num2 = MathHelper.Lerp(0.41f, 0.57f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 break;
             case "Mid":
             {
                 num2 = 0f;
                 float amount4 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0f, 0.9f, amount4);
                 break;
             }
             case "Nimbus":
                 num2 = MathHelper.Lerp(0.75f, 1f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 1f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.8f);
                 break;
             case "Nike Leon":
                 num2 = MathHelper.Lerp(0.04f, 0.1f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                 break;
             case "ppowersteef":
                 num2 = MathHelper.Lerp(0f, 0.15f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                 break;
             case "RBrandon":
                 num2 = 0.03f;
                 luminosity = 0.3f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                 break;
             case "Redigit":
                 num2 = 0.7f;
                 luminosity = 0.5f;
                 break;
             case "Serenity":
             {
                 num2 = 0.85f;
                 float amount3 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(1f, 0.5f, amount3);
                 break;
             }
             case "Sigma":
                 num2 = MathHelper.Lerp(0f, 0.12f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                 break;
             case "teiull":
                 num2 = MathHelper.Lerp(0.66f, 1f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 break;
             case "Unit One":
             {
                 float amount2 = Utils.PingPongFrom01To010(num2);
                 amount2 = MathHelper.SmoothStep(0f, 1f, amount2);
                 Color color = Color.Lerp(Color.Yellow, Color.Blue, amount2);
                 if (lerpToWhite != 0f)
                 {
                     color = Color.Lerp(color, Color.White, lerpToWhite);
                 }
                 color.A = (byte)((float)(int)color.A * alphaChannelMultiplier);
                 return color;
             }
             case "Vulpes Inculta":
                 num2 = MathHelper.Lerp(0.65f, 0.75f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                 break;
             case "Waze3174":
                 num2 = MathHelper.Lerp(0.33f, 0f, Utils.Turn01ToCyclic010(num2));
                 luminosity = 0.3f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                 break;
             case "Xman101":
             {
                 num2 = 0.06f;
                 float amount = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                 luminosity = MathHelper.Lerp(0f, 0.5f, amount);
                 break;
             }
             case "Zoomo":
                 num2 = 0.77f;
                 luminosity = 0.5f;
                 alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                 break;
             }
         }
         Color color4 = Main.hslToRgb(num2, saturation, luminosity);
         color4 *= Opacity;
         if (lerpToWhite != 0f)
         {
             color4 = Color.Lerp(color4, Color.White, lerpToWhite);
         }
         color4.A = (byte)((float)(int)color4.A * alphaChannelMultiplier);
         return color4;
     }
References Entity.active, ai, Color, Main.hslToRgb(), Player.name, Opacity, owner, Utils.PingPongFrom01To010(), Main.player, and Utils.Turn01ToCyclic010().
Referenced by Main.DrawProj_EmpressBlade(), Main.DrawProj_FairyQueenRangedItemShot(), Main.DrawProj_PiercingStarlight(), and Main.DrawProjDirect().