Terraria: Projectile.AI_019_Spears
AI_019_Spears()
void Projectile.AI_019_Spears () inline private
     {
         Player player = Main.player[owner];
         Vector2 center = player.RotatedRelativePoint(player.MountedCenter);
         direction = player.direction;
         player.heldProj = whoAmI;
         player.MatchItemTimeToItemAnimation();
         base.Center = center;
         bool flag = Main.player[owner].itemAnimation < Main.player[owner].itemAnimationMax / 3;
         int itemAnimationMax = player.itemAnimationMax;
         int itemAnimation = player.itemAnimation;
         int num = Main.player[owner].itemAnimationMax / 3;
         float num2 = MathHelper.Min(itemAnimation, num);
         float num3 = (float)itemAnimation - num2;
         float num4 = 0f;
         float num5 = 0f;
         float num6 = 0f;
         bool flag2 = false;
         spriteDirection = -direction;
         switch (type)
         {
         case 46:
             num4 = 3f;
             num6 = 1.6f;
             num5 = 1.4f;
             break;
         case 105:
             num4 = 3f;
             num6 = 2.4f;
             num5 = 2.1f;
             break;
         case 367:
             num4 = 3f;
             num6 = 1.6f;
             num5 = 1.5f;
             break;
         case 368:
             num4 = 3f;
             num6 = 1.5f;
             num5 = 1.4f;
             break;
         case 222:
             num4 = 3f;
             num6 = 2.4f;
             num5 = 2.1f;
             break;
         case 342:
             num4 = 3f;
             num6 = 2.4f;
             num5 = 2.1f;
             break;
         case 47:
             num4 = 4f;
             num6 = 1.2f;
             num5 = 0.9f;
             break;
         case 153:
             num4 = 4f;
             num6 = 1.5f;
             num5 = 1.3f;
             break;
         case 49:
             num4 = 4f;
             num6 = 1.1f;
             num5 = 0.85f;
             break;
         case 730:
             num4 = 8f;
             num6 = 1.5f;
             num5 = 1.2f;
             break;
         case 877:
         case 878:
         case 879:
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             num4 = 28f;
             num6 = 0.4f;
             num5 = 0.4f;
             flag2 = true;
             break;
         case 64:
         case 215:
             spriteDirection = -direction;
             num4 = 3f;
             num6 = 1.9f;
             num5 = 1.7f;
             break;
         case 66:
         case 97:
         case 212:
         case 218:
             num4 = 3f;
             num6 = 2.1f;
             num5 = 1.9f;
             break;
         case 130:
             num4 = 3f;
             num6 = 1.3f;
             num5 = 1f;
             break;
         }
         float num7 = (float)(itemAnimationMax - num) - num3;
         float num8 = (float)num - num2;
         float num9 = num4 + num5 * num7 - num6 * num8;
         position += velocity * num9;
         switch (type)
         {
         case 47:
             if (Main.player[owner].wet && Main.rand.Next(2) == 0)
             {
                 int num10 = Dust.NewDust(Main.player[owner].position, Main.player[owner].width, Main.player[owner].height, 15, 0f, 0f, 100, default(Color), 0.8f);
                 Main.dust[num10].velocity *= 0.1f;
             }
             break;
         case 130:
             if ((localAI[0] == 0f || localAI[0] == 4f || localAI[0] == 8f || localAI[0] == 12f || localAI[0] == 16f || localAI[0] == 20f || localAI[0] == 24f) && owner == Main.myPlayer)
             {
                 NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, velocity.X, velocity.Y, 131, damage / 3, 0f, owner);
             }
             localAI[0] += 1f;
             break;
         case 730:
             if (localAI[0] == 0f && Main.myPlayer == owner)
             {
                 localAI[0] = 1f;
                 Vector2 vector = velocity * 4f;
                 NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector.X, vector.Y, 732, (int)((double)damage * 1.5), knockBack * 0.5f, owner);
             }
             break;
         case 342:
             if (flag && localAI[0] == 0f && Main.myPlayer == owner)
             {
                 localAI[0] = 1f;
                 if (Collision.CanHit(player.position, player.width, player.height, position, width, height))
                 {
                     NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, velocity.X * 2.4f, velocity.Y * 2.4f, 343, damage, knockBack * 0.85f, owner);
                 }
             }
             break;
         case 222:
             if (flag && localAI[0] == 0f && Main.myPlayer == owner)
             {
                 localAI[0] = 1f;
                 NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, velocity.X, velocity.Y, 228, damage, knockBack, owner);
             }
             break;
         }
         if (flag2 && player.channel && player.itemAnimation < num)
         {
             player.SetDummyItemTime(num);
         }
         rotation = (float)Math.Atan2(velocity.Y, velocity.X) + (float)Math.PI / 2f + (float)Math.PI / 4f;
         if (spriteDirection == -1)
         {
             rotation -= (float)Math.PI / 2f;
         }
         AI_019_Spears_GetExtensionHitbox(out var _);
         if (type == 878 || type == 879)
         {
             float num11 = 6f;
             float num12 = 0.8f;
             float num13 = Vector2.Dot(velocity.SafeNormalize(Vector2.UnitX * player.direction), player.velocity.SafeNormalize(Vector2.UnitX * player.direction));
             float num14 = player.velocity.Length();
             if (num14 > num11 && num13 > num12)
             {
                 int num15 = 8;
                 if (num14 > num11 + 1f)
                 {
                     num15 = 5;
                 }
                 if (num14 > num11 + 2f)
                 {
                     num15 = 2;
                 }
                 int num16 = 14;
                 int num17 = 27;
                 int num18 = 4;
                 if (type == 879)
                 {
                     num16 = 43;
                     num17 = 57;
                 }
                 if (Main.rand.Next(num15 + 3) == 0)
                 {
                     Dust.NewDust(base.Center - new Vector2(num18, num18), num18 * 2, num18 * 2, num16, 0f, 0f, 150, default(Color), 1.4f);
                 }
                 if (Main.rand.Next(num15) == 0)
                 {
                     int num19 = Dust.NewDust(base.Center - new Vector2(num18, num18), num18 * 2, num18 * 2, num17, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.2f);
                     Main.dust[num19].noGravity = true;
                     Main.dust[num19].velocity *= 0.25f;
                     num19 = Dust.NewDust(base.Center - new Vector2(num18, num18), num18 * 2, num18 * 2, num17, 0f, 0f, 150, default(Color), 1.4f);
                     Main.dust[num19].velocity *= 0.25f;
                 }
             }
         }
         if (type == 46)
         {
             if (Main.rand.Next(5) == 0)
             {
                 Dust.NewDust(position, width, height, 14, 0f, 0f, 150, default(Color), 1.4f);
             }
             int num20 = Dust.NewDust(position, width, height, 27, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.2f);
             Main.dust[num20].noGravity = true;
             Main.dust[num20].velocity /= 2f;
             num20 = Dust.NewDust(position - velocity * 2f, width, height, 27, 0f, 0f, 150, default(Color), 1.4f);
             Main.dust[num20].velocity /= 5f;
         }
         if (type == 730)
         {
             if (Main.rand.Next(5) == 0)
             {
                 Dust dust = Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 150, default(Color), 0.7f);
                 dust.noGravity = true;
                 dust.velocity *= 1.4f;
             }
             if (Main.rand.Next(5) == 0)
             {
                 Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 150, default(Color), 0.5f).velocity.Y -= 0.5f;
             }
         }
         else if (type == 105)
         {
             if (Main.rand.Next(3) == 0)
             {
                 int num21 = Dust.NewDust(position, width, height, 57, velocity.X * 0.2f, velocity.Y * 0.2f, 200, default(Color), 1.2f);
                 Main.dust[num21].velocity += velocity * 0.3f;
                 Main.dust[num21].velocity *= 0.2f;
             }
             if (Main.rand.Next(4) == 0)
             {
                 int num22 = Dust.NewDust(position, width, height, 43, 0f, 0f, 254, default(Color), 0.3f);
                 Main.dust[num22].velocity += velocity * 0.5f;
                 Main.dust[num22].velocity *= 0.5f;
             }
         }
         else if (type == 153)
         {
             int num23 = Dust.NewDust(position - velocity * 3f, width, height, 115, velocity.X * 0.4f, velocity.Y * 0.4f, 140);
             Main.dust[num23].noGravity = true;
             Main.dust[num23].fadeIn = 1.25f;
             Main.dust[num23].velocity *= 0.25f;
         }
         if (type == 342)
         {
             Lighting.AddLight(base.Center, 0.65f, 0.9f, 1f);
             if (timeLeft % 2 == 0)
             {
                 int num24 = 10;
                 int num25 = Dust.NewDust(position - velocity * 3f - new Vector2(num24, num24), width + num24 * 2, height + num24 * 2, 135, velocity.X * 0.4f, velocity.Y * 0.4f, 50, default(Color), 1.2f);
                 Main.dust[num25].velocity *= 0.5f;
                 Main.dust[num25].velocity += velocity * 0.25f;
             }
         }
         ai[0] += 1f;
         bool flag3 = ai[0] >= (float)itemAnimationMax;
         if (flag2)
         {
             flag3 &= !player.channel;
         }
         if (flag3)
         {
             Kill();
         }
     }
References Lighting.AddLight(), Collision.CanHit(), Player.channel, Color, Entity.direction, Main.dust, Dust.fadeIn, Entity.height, Player.heldProj, Player.itemAnimation, Player.itemAnimationMax, Player.MatchItemTimeToItemAnimation(), Player.MountedCenter, Main.myPlayer, Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.player, Entity.position, Main.rand, Player.RotatedRelativePoint(), Player.SetDummyItemTime(), Dust.velocity, Entity.velocity, Entity.wet, and Entity.width.