Terraria: Projectile.EmitEnchantmentVisualsAt
EmitEnchantmentVisualsAt()
void Projectile.EmitEnchantmentVisualsAt (Vector2 boxPosition, int boxWidth, int boxHeight) inline
     {
         Player player = Main.player[owner];
         if (player.frostBurn && (melee || ranged) && friendly && !hostile && !noEnchantments && Main.rand.Next(2 * (1 + extraUpdates)) == 0)
         {
             int num = Dust.NewDust(boxPosition, boxWidth, boxHeight, 135, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2f);
             Main.dust[num].noGravity = true;
             Main.dust[num].velocity *= 0.7f;
             Main.dust[num].velocity.Y -= 0.5f;
         }
         if (melee && player.magmaStone && !noEnchantments && Main.rand.Next(3) != 0)
         {
             int num2 = Dust.NewDust(new Vector2(boxPosition.X - 4f, boxPosition.Y - 4f), boxWidth + 8, boxHeight + 8, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 2f);
             if (Main.rand.Next(2) == 0)
             {
                 Main.dust[num2].scale = 1.5f;
             }
             Main.dust[num2].noGravity = true;
             Main.dust[num2].velocity.X *= 2f;
             Main.dust[num2].velocity.Y *= 2f;
         }
         if ((!melee && !ProjectileID.Sets.IsAWhip[type]) || player.meleeEnchant <= 0 || noEnchantments)
         {
             return;
         }
         if (player.meleeEnchant == 1 && Main.rand.Next(3) == 0)
         {
             int num3 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 171, 0f, 0f, 100);
             Main.dust[num3].noGravity = true;
             Main.dust[num3].fadeIn = 1.5f;
             Main.dust[num3].velocity *= 0.25f;
         }
         if (player.meleeEnchant == 1)
         {
             if (Main.rand.Next(3) == 0)
             {
                 int num4 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 171, 0f, 0f, 100);
                 Main.dust[num4].noGravity = true;
                 Main.dust[num4].fadeIn = 1.5f;
                 Main.dust[num4].velocity *= 0.25f;
             }
         }
         else if (player.meleeEnchant == 2)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num5 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 75, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
                 Main.dust[num5].noGravity = true;
                 Main.dust[num5].velocity *= 0.7f;
                 Main.dust[num5].velocity.Y -= 0.5f;
             }
         }
         else if (player.meleeEnchant == 3)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num6 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
                 Main.dust[num6].noGravity = true;
                 Main.dust[num6].velocity *= 0.7f;
                 Main.dust[num6].velocity.Y -= 0.5f;
             }
         }
         else if (player.meleeEnchant == 4)
         {
             int num7 = 0;
             if (Main.rand.Next(2) == 0)
             {
                 num7 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 57, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.1f);
                 Main.dust[num7].noGravity = true;
                 Main.dust[num7].velocity.X /= 2f;
                 Main.dust[num7].velocity.Y /= 2f;
             }
         }
         else if (player.meleeEnchant == 5)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num8 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 169, 0f, 0f, 100);
                 Main.dust[num8].velocity.X += direction;
                 Main.dust[num8].velocity.Y += 0.2f;
                 Main.dust[num8].noGravity = true;
             }
         }
         else if (player.meleeEnchant == 6)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num9 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 135, 0f, 0f, 100);
                 Main.dust[num9].velocity.X += direction;
                 Main.dust[num9].velocity.Y += 0.2f;
                 Main.dust[num9].noGravity = true;
             }
         }
         else if (player.meleeEnchant == 7)
         {
             Vector2 vector = velocity;
             if (vector.Length() > 4f)
             {
                 vector *= 4f / vector.Length();
             }
             if (Main.rand.Next(20) == 0)
             {
                 int num10 = Main.rand.Next(139, 143);
                 int num11 = Dust.NewDust(boxPosition, boxWidth, boxHeight, num10, vector.X, vector.Y, 0, default(Color), 1.2f);
                 Main.dust[num11].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num11].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.dust[num11].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                 Main.dust[num11].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                 Main.dust[num11].scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
             }
             if (Main.rand.Next(40) == 0)
             {
                 int num12 = Main.rand.Next(276, 283);
                 int num13 = Gore.NewGore(position, vector, num12);
                 Main.gore[num13].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num13].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 Main.gore[num13].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                 Main.gore[num13].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                 Main.gore[num13].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
             }
         }
         else if (player.meleeEnchant == 8 && Main.rand.Next(4) == 0)
         {
             int num14 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 46, 0f, 0f, 100);
             Main.dust[num14].noGravity = true;
             Main.dust[num14].fadeIn = 1.5f;
             Main.dust[num14].velocity *= 0.25f;
         }
     }
References Color, Entity.direction, Main.dust, extraUpdates, Dust.fadeIn, friendly, Player.frostBurn, Main.gore, hostile, ProjectileID.Sets.IsAWhip, Player.magmaStone, melee, Player.meleeEnchant, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), noEnchantments, Dust.noGravity, owner, Main.player, Entity.position, Main.rand, ranged, Dust.scale, Gore.scale, type, Dust.velocity, Entity.velocity, and Gore.velocity.
Referenced by UpdateEnchantmentVisuals().