Terraria: Projectile.SummonMonkGhast
SummonMonkGhast()
void Projectile.SummonMonkGhast () inline private
     {
         if (localAI[0] > 0f)
         {
             return;
         }
         localAI[0] = 1000f;
         List<NPC> list = new List<NPC>();
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = Main.npc[i];
             if (nPC.CanBeChasedBy(this) && Distance(nPC.Center) < 800f)
             {
                 list.Add(nPC);
             }
         }
         Vector2 center = base.Center;
         Vector2 zero = Vector2.Zero;
         if (list.Count > 0)
         {
             NPC nPC2 = list[Main.rand.Next(list.Count)];
             center = nPC2.Center;
             zero = nPC2.velocity;
         }
         int num = Main.rand.Next(2) * 2 - 1;
         Vector2 vector = new Vector2((float)num * (4f + (float)Main.rand.Next(3)), 0f);
         Vector2 vector2 = center + new Vector2(-num * 120, 0f);
         vector += (center + zero * 15f - vector2).SafeNormalize(Vector2.Zero) * 2f;
         NewProjectile(GetProjectileSource_FromThis(), vector2, vector, 700, damage, 0f, owner);
     }
References NPC.CanBeChasedBy(), Entity.Center, damage, Entity.Distance(), GetProjectileSource_FromThis(), localAI, NewProjectile(), UnifiedRandom.Next(), Main.npc, owner, Main.rand, and Entity.velocity.
Referenced by Damage().