Terraria: Projectile.AI_019_Spears_GetExtensionHitbox
AI_019_Spears_GetExtensionHitbox()
bool Projectile.AI_019_Spears_GetExtensionHitbox (out Rectangle extensionBox) inline
     {
         extensionBox = default(Rectangle);
         Player player = Main.player[owner];
         if (player.itemAnimation < player.itemAnimationMax / 3)
         {
             return false;
         }
         int itemAnimationMax = player.itemAnimationMax;
         int itemAnimation = player.itemAnimation;
         int num = player.itemAnimationMax / 3;
         float num2 = Utils.Remap(itemAnimation, itemAnimationMax, num, 0f, 1f);
         float num3 = 10f;
         float num4 = 30f;
         float num5 = 10f;
         float num6 = 10f;
         switch (type)
         {
         default:
             return false;
         case 105:
             num4 = 50f;
             num6 = 20f;
             break;
         case 46:
             num4 = 50f;
             num6 = 15f;
             break;
         case 153:
             num4 = 40f;
             num6 = 10f;
             break;
         }
         num4 *= 1f / player.meleeSpeed;
         float num7 = num3 + num4 * num2;
         float num8 = num5 + num6 * num2;
         float f = velocity.ToRotation();
         Vector2 center = base.Center + f.ToRotationVector2() * num7;
         extensionBox = Utils.CenteredRectangle(center, new Vector2(num8, num8));
         return true;
     }
References Utils.CenteredRectangle(), Player.itemAnimation, Player.itemAnimationMax, Player.meleeSpeed, Main.player, and Utils.Remap().
Referenced by Colliding(), CutTiles(), and Main.DrawProj_Spear().