Terraria: Projectile.AI_075
AI_075()
void Projectile.AI_075 () inline private
     {
         Player player = Main.player[owner];
         float num = (float)Math.PI / 2f;
         Vector2 vector = player.RotatedRelativePoint(player.MountedCenter);
         int num2 = 2;
         float num3 = 0f;
         if (type == 439)
         {
             ai[0] += 1f;
             int num4 = 0;
             if (ai[0] >= 40f)
             {
                 num4++;
             }
             if (ai[0] >= 80f)
             {
                 num4++;
             }
             if (ai[0] >= 120f)
             {
                 num4++;
             }
             int num5 = 24;
             int num6 = 6;
             ai[1] += 1f;
             bool flag = false;
             if (ai[1] >= (float)(num5 - num6 * num4))
             {
                 ai[1] = 0f;
                 flag = true;
             }
             frameCounter += 1 + num4;
             if (frameCounter >= 4)
             {
                 frameCounter = 0;
                 frame++;
                 if (frame >= 6)
                 {
                     frame = 0;
                 }
             }
             if (soundDelay <= 0)
             {
                 soundDelay = num5 - num6 * num4;
                 if (ai[0] != 1f)
                 {
                     SoundEngine.PlaySound(SoundID.Item91, position);
                 }
             }
             if (ai[1] == 1f && ai[0] != 1f)
             {
                 Vector2 spinningpoint = Vector2.UnitX * 24f;
                 spinningpoint = spinningpoint.RotatedBy(rotation - (float)Math.PI / 2f);
                 Vector2 vector2 = base.Center + spinningpoint;
                 for (int i = 0; i < 2; i++)
                 {
                     int num7 = Dust.NewDust(vector2 - Vector2.One * 8f, 16, 16, 135, velocity.X / 2f, velocity.Y / 2f, 100);
                     Main.dust[num7].velocity *= 0.66f;
                     Main.dust[num7].noGravity = true;
                     Main.dust[num7].scale = 1.4f;
                 }
             }
             if (flag && Main.myPlayer == owner)
             {
                 if (player.channel && player.CheckMana(player.inventory[player.selectedItem].mana, pay: true) && !player.noItems && !player.CCed)
                 {
                     float num8 = player.inventory[player.selectedItem].shootSpeed * scale;
                     Vector2 vector3 = vector;
                     Vector2 value = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector3;
                     if (player.gravDir == -1f)
                     {
                         value.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector3.Y;
                     }
                     Vector2 vector4 = Vector2.Normalize(value);
                     if (float.IsNaN(vector4.X) || float.IsNaN(vector4.Y))
                     {
                         vector4 = -Vector2.UnitY;
                     }
                     vector4 *= num8;
                     if (vector4.X != velocity.X || vector4.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = vector4;
                     int num9 = 440;
                     float num10 = 14f;
                     int num11 = 7;
                     for (int j = 0; j < 2; j++)
                     {
                         vector3 = base.Center + new Vector2(Main.rand.Next(-num11, num11 + 1), Main.rand.Next(-num11, num11 + 1));
                         Vector2 spinningpoint2 = Vector2.Normalize(velocity) * num10;
                         spinningpoint2 = spinningpoint2.RotatedBy(Main.rand.NextDouble() * 0.19634954631328583 - 0.09817477315664291);
                         if (float.IsNaN(spinningpoint2.X) || float.IsNaN(spinningpoint2.Y))
{
                             spinningpoint2 = -Vector2.UnitY;
                         }
                         NewProjectile(GetProjectileSource_FromThis(), vector3.X, vector3.Y, spinningpoint2.X, spinningpoint2.Y, num9, damage, knockBack, owner);
                     }
                 }
                 else
                 {
                     Kill();
                 }
             }
         }
         if (type == 445)
         {
             if (soundDelay <= 0)
             {
                 SoundEngine.PlaySound(SoundID.Item132, position);
                 soundDelay = 23;
             }
             localAI[0] += 1f;
             if (localAI[0] >= 60f)
             {
                 localAI[0] = 0f;
             }
             if (Vector2.Distance(vector, base.Center) >= 5f)
             {
                 float num12 = localAI[0] / 60f;
                 if (num12 > 0.5f)
                 {
                     num12 = 1f - num12;
                 }
                 Vector3 value2 = new Vector3(0f, 1f, 0.7f);
                 Vector3 value3 = new Vector3(0f, 0.7f, 1f);
                 Vector3 vector5 = Vector3.Lerp(value2, value3, 1f - num12 * 2f) * 0.5f;
                 if (Vector2.Distance(vector, base.Center) >= 30f)
                 {
                     Vector2 vector6 = base.Center - vector;
                     vector6.Normalize();
                     vector6 *= Vector2.Distance(vector, base.Center) - 30f;
                     DelegateMethods.v3_1 = vector5 * 0.8f;
                     Utils.PlotTileLine(base.Center - vector6, base.Center, 8f, DelegateMethods.CastLightOpen);
                 }
                 Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, vector5.X, vector5.Y, vector5.Z);
             }
             if (Main.myPlayer == owner)
             {
                 if (localAI[1] > 0f)
                 {
                     localAI[1] -= 1f;
                 }
                 if (!player.channel || player.noItems || player.CCed)
                 {
                     Kill();
                 }
                 else if (localAI[1] == 0f)
                 {
                     Vector2 vector7 = vector;
                     Vector2 value4 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector7;
                     if (player.gravDir == -1f)
                     {
                         value4.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector7.Y;
                     }
                     if (Main.tile[Player.tileTargetX, Player.tileTargetY].active())
                     {
                         value4 = new Vector2(Player.tileTargetX, Player.tileTargetY) * 16f + Vector2.One * 8f - vector7;
                         localAI[1] = 2f;
                     }
                     value4 = Vector2.Lerp(value4, velocity, 0.7f);
                     if (float.IsNaN(value4.X) || float.IsNaN(value4.Y))
                     {
                         value4 = -Vector2.UnitY;
                     }
                     float num13 = 30f;
                     if (value4.Length() < num13)
                     {
                         value4 = Vector2.Normalize(value4) * num13;
                     }
                     int tileBoost = player.inventory[player.selectedItem].tileBoost;
                     int num14 = -Player.tileRangeX - tileBoost + 1;
                     int num15 = Player.tileRangeX + tileBoost - 1;
                     int num16 = -Player.tileRangeY - tileBoost;
                     int num17 = Player.tileRangeY + tileBoost - 1;
                     int num18 = 12;
                     bool flag2 = false;
                     if (value4.X < (float)(num14 * 16 - num18))
                     {
                         flag2 = true;
                     }
                     if (value4.Y < (float)(num16 * 16 - num18))
                     {
                         flag2 = true;
                     }
                     if (value4.X > (float)(num15 * 16 + num18))
                     {
                         flag2 = true;
                     }
                     if (value4.Y > (float)(num17 * 16 + num18))
                     {
                         flag2 = true;
                     }
                     if (flag2)
                     {
                         Vector2 vector8 = Vector2.Normalize(value4);
                         float num19 = -1f;
                         if (vector8.X < 0f && ((float)(num14 * 16 - num18) / vector8.X < num19 || num19 == -1f))
{
                             num19 = (float)(num14 * 16 - num18) / vector8.X;
                         }
                         if (vector8.X > 0f && ((float)(num15 * 16 + num18) / vector8.X < num19 || num19 == -1f))
{
                             num19 = (float)(num15 * 16 + num18) / vector8.X;
                         }
                         if (vector8.Y < 0f && ((float)(num16 * 16 - num18) / vector8.Y < num19 || num19 == -1f))
{
                             num19 = (float)(num16 * 16 - num18) / vector8.Y;
                         }
                         if (vector8.Y > 0f && ((float)(num17 * 16 + num18) / vector8.Y < num19 || num19 == -1f))
{
                             num19 = (float)(num17 * 16 + num18) / vector8.Y;
                         }
                         value4 = vector8 * num19;
                     }
                     if (value4.X != velocity.X || value4.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = value4;
                 }
             }
         }
         if (type == 460)
         {
             ai[0] += 1f;
             int num20 = 0;
             if (ai[0] >= 80f)
             {
                 num20++;
             }
             if (ai[0] >= 180f)
             {
                 num20++;
             }
             bool flag3 = false;
             _ = ai[0];
             if (ai[0] == 80f || ai[0] == 180f || (ai[0] > 180f && ai[0] % 20f == 0f))
             {
                 flag3 = true;
             }
             bool flag4 = ai[0] >= 180f;
             int num21 = 5;
             if (!flag4)
             {
                 ai[1] += 1f;
             }
             bool flag5 = false;
             if (ai[0] == 1f)
             {
                 flag5 = true;
             }
             if (flag4 && ai[0] % 20f == 0f)
             {
                 flag5 = true;
             }
             if ((!flag4 && ai[1] >= (float)num21) || (flag4 && ai[0] % 5f == 0f))
             {
                 if (!flag4)
                 {
                     ai[1] = 0f;
                 }
                 flag5 = true;
                 float num22 = player.inventory[player.selectedItem].shootSpeed * scale;
                 Vector2 vector9 = vector;
                 Vector2 value5 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector9;
                 if (player.gravDir == -1f)
                 {
                     value5.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector9.Y;
                 }
                 Vector2 vector10 = Vector2.Normalize(value5);
                 if (float.IsNaN(vector10.X) || float.IsNaN(vector10.Y))
                 {
                     vector10 = -Vector2.UnitY;
                 }
                 vector10 *= num22;
                 if (vector10.X != velocity.X || vector10.Y != velocity.Y)
                 {
                     netUpdate = true;
                 }
                 velocity = vector10;
             }
             if (soundDelay <= 0 && !flag4)
             {
                 soundDelay = num21 - num20;
                 soundDelay *= 2;
                 if (ai[0] != 1f)
                 {
                     SoundEngine.PlaySound(SoundID.Item15, position);
                 }
             }
             if (ai[0] > 10f && !flag4)
             {
                 Vector2 spinningpoint3 = Vector2.UnitX * 18f;
                 spinningpoint3 = spinningpoint3.RotatedBy(rotation - (float)Math.PI / 2f);
                 Vector2 vector11 = base.Center + spinningpoint3;
                 for (int k = 0; k < num20 + 1; k++)
                 {
                     int num23 = 226;
                     float num24 = 0.4f;
                     if (k % 2 == 1)
                     {
                         num23 = 226;
                         num24 = 0.65f;
                     }
                     Vector2 vector12 = vector11 + ((float)Main.rand.NextDouble() * ((float)Math.PI * 2f)).ToRotationVector2() * (12f - (float)(num20 * 2));
                     int num25 = Dust.NewDust(vector12 - Vector2.One * 8f, 16, 16, num23, velocity.X / 2f, velocity.Y / 2f);
                     Main.dust[num25].velocity = Vector2.Normalize(vector11 - vector12) * 1.5f * (10f - (float)num20 * 2f) / 10f;
                     Main.dust[num25].noGravity = true;
                     Main.dust[num25].scale = num24;
                     Main.dust[num25].customData = player;
                 }
             }
             if (flag4)
             {
                 Vector2 spinningpoint4 = Vector2.UnitX * 14f;
                 spinningpoint4 = spinningpoint4.RotatedBy(rotation - (float)Math.PI / 2f);
                 Vector2 vector13 = base.Center + spinningpoint4;
                 for (int l = 0; l < 2; l++)
                 {
                     int num26 = 226;
                     float num27 = 0.35f;
                     if (l % 2 == 1)
                     {
                         num26 = 226;
                         num27 = 0.45f;
                     }
                     float num28 = Main.rand.NextFloatDirection();
                     Vector2 vector14 = vector13 + (rotation + num28 * ((float)Math.PI / 4f) * 0.8f - (float)Math.PI / 2f).ToRotationVector2() * 6f;
                     int num29 = 24;
                     int num30 = Dust.NewDust(vector14 - Vector2.One * (num29 / 2), num29, num29, num26, velocity.X / 2f, velocity.Y / 2f);
                     Main.dust[num30].velocity = (vector14 - vector13).SafeNormalize(Vector2.Zero) * MathHelper.Lerp(1.5f, 9f, Utils.GetLerpValue(1f, 0f, Math.Abs(num28), clamped: true));
                     Main.dust[num30].noGravity = true;
                     Main.dust[num30].scale = num27;
                     Main.dust[num30].customData = player;
                     Main.dust[num30].fadeIn = 0.5f;
                 }
             }
             if (flag5 && Main.myPlayer == owner)
             {
                 bool flag6 = false;
                 flag6 = !flag3 || player.CheckMana(player.inventory[player.selectedItem].mana, pay: true);
                 if (player.channel && flag6 && !player.noItems && !player.CCed)
                 {
                     if (ai[0] == 180f)
                     {
                         Vector2 center = base.Center;
                         Vector2 vector15 = Vector2.Normalize(velocity);
                         if (float.IsNaN(vector15.X) || float.IsNaN(vector15.Y))
{
                             vector15 = -Vector2.UnitY;
                         }
                         int num31 = (int)((float)damage * 1.5f);
                         int num32 = NewProjectile(GetProjectileSource_FromThis(), center.X, center.Y, vector15.X, vector15.Y, 461, num31, knockBack, owner, 0f, whoAmI);
                         ai[1] = num32;
                         netUpdate = true;
                     }
                     else if (flag4)
                     {
                         Projectile projectile = Main.projectile[(int)ai[1]];
                         if (!projectile.active || projectile.type != 461)
{
                             Kill();
                             return;
                         }
                     }
                     else
                     {
                         bool flag7 = false;
                         if (ai[0] == 1f)
{
                             flag7 = true;
                         }
                         if (ai[0] <= 50f && ai[0] % 10f == 0f)
{
                             flag7 = true;
                         }
                         if (ai[0] >= 80f && ai[0] < 180f && ai[0] % 30f == 0f)
{
                             flag7 = true;
                         }
                         if (flag7)
{
                             Vector2 vector16 = vector;
                             int num33 = 459;
                             float num34 = 10f;
                             vector16 = base.Center;
                             Vector2 vector17 = Vector2.Normalize(velocity) * num34;
                             if (float.IsNaN(vector17.X) || float.IsNaN(vector17.Y))
{
                                 vector17 = -Vector2.UnitY;
                             }
                             float num35 = 0.7f + (float)num20 * 0.3f;
                             int num36 = ((num35 < 1f) ? damage : ((int)((float)damage * 2.5f)));
                             NewProjectile(GetProjectileSource_FromThis(), vector16.X, vector16.Y, vector17.X, vector17.Y, num33, num36, knockBack, owner, 0f, num35);
                         }
                     }
                 }
                 else
                 {
                     Kill();
                 }
             }
         }
         if (type == 633)
         {
             float num37 = 30f;
             if (ai[0] > 90f)
             {
                 num37 = 15f;
             }
             if (ai[0] > 120f)
             {
                 num37 = 5f;
             }
             damage = (int)((float)player.inventory[player.selectedItem].damage * player.magicDamage);
             ai[0] += 1f;
             ai[1] += 1f;
             bool flag8 = false;
             if (ai[0] % num37 == 0f)
             {
                 flag8 = true;
             }
             int num38 = 10;
             bool flag9 = false;
             if (ai[0] % num37 == 0f)
             {
                 flag9 = true;
             }
             if (ai[1] >= 1f)
             {
                 ai[1] = 0f;
                 flag9 = true;
                 if (Main.myPlayer == owner)
                 {
                     float num39 = player.inventory[player.selectedItem].shootSpeed * scale;
                     Vector2 vector18 = vector;
                     Vector2 value6 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector18;
                     if (player.gravDir == -1f)
                     {
                         value6.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector18.Y;
                     }
                     Vector2 value7 = Vector2.Normalize(value6);
                     if (float.IsNaN(value7.X) || float.IsNaN(value7.Y))
                     {
                         value7 = -Vector2.UnitY;
                     }
                     value7 = Vector2.Normalize(Vector2.Lerp(value7, Vector2.Normalize(velocity), 0.92f));
                     value7 *= num39;
                     if (value7.X != velocity.X || value7.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = value7;
                 }
             }
             frameCounter++;
             int num40 = ((!(ai[0] < 120f)) ? 1 : 4);
             if (frameCounter >= num40)
             {
                 frameCounter = 0;
                 if (++frame >= 5)
                 {
                     frame = 0;
                 }
             }
             if (soundDelay <= 0)
             {
                 soundDelay = num38;
                 soundDelay *= 2;
                 if (ai[0] != 1f)
                 {
                     SoundEngine.PlaySound(SoundID.Item15, position);
                 }
             }
             if (flag9 && Main.myPlayer == owner)
             {
                 bool flag10 = false;
                 flag10 = !flag8 || player.CheckMana(player.inventory[player.selectedItem].mana, pay: true);
                 if (player.channel && flag10 && !player.noItems && !player.CCed)
                 {
                     if (ai[0] == 1f)
                     {
                         Vector2 center2 = base.Center;
                         Vector2 vector19 = Vector2.Normalize(velocity);
                         if (float.IsNaN(vector19.X) || float.IsNaN(vector19.Y))
{
                             vector19 = -Vector2.UnitY;
                         }
                         int num41 = damage;
                         for (int m = 0; m < 6; m++)
{
                             NewProjectile(GetProjectileSource_FromThis(), center2.X, center2.Y, vector19.X, vector19.Y, 632, num41, knockBack, owner, m, whoAmI);
                         }
                         netUpdate = true;
                     }
                 }
                 else
                 {
                     Kill();
                 }
             }
         }
         if (type == 595)
         {
             num = 0f;
             if (spriteDirection == -1)
             {
                 num = (float)Math.PI;
             }
             if (++frame >= Main.projFrames[type])
             {
                 frame = 0;
             }
             soundDelay--;
             if (soundDelay <= 0)
             {
                 SoundEngine.PlaySound(SoundID.Item1, base.Center);
                 soundDelay = 12;
             }
             if (Main.myPlayer == owner)
             {
                 if (player.channel && !player.noItems && !player.CCed)
                 {
                     float num42 = 1f;
                     if (player.inventory[player.selectedItem].shoot == type)
                     {
                         num42 = player.inventory[player.selectedItem].shootSpeed * scale;
                     }
                     Vector2 vec = Main.MouseWorld - vector;
                     vec.Normalize();
                     if (vec.HasNaNs())
                     {
                         vec = Vector2.UnitX * player.direction;
                     }
                     vec *= num42;
                     if (vec.X != velocity.X || vec.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = vec;
                 }
                 else
                 {
                     Kill();
                 }
             }
             Vector2 vector20 = base.Center + velocity * 3f;
             Lighting.AddLight(vector20, 0.8f, 0.8f, 0.8f);
             if (Main.rand.Next(3) == 0)
             {
                 int num43 = Dust.NewDust(vector20 - base.Size / 2f, width, height, 63, velocity.X, velocity.Y, 100, default(Color), 2f);
                 Main.dust[num43].noGravity = true;
                 Main.dust[num43].position -= velocity;
             }
         }
         if (type == 735)
         {
             num = 0f;
             if (spriteDirection == -1)
             {
                 num = (float)Math.PI;
             }
             if (++frame >= Main.projFrames[type])
             {
                 frame = 0;
             }
             soundDelay--;
             if (soundDelay <= 0)
             {
                 SoundEngine.PlaySound(SoundID.Item1, base.Center);
                 soundDelay = 12;
             }
             if (Main.myPlayer == owner)
             {
                 if (player.channel && !player.noItems && !player.CCed)
                 {
                     float num44 = 1f;
                     if (player.inventory[player.selectedItem].shoot == type)
                     {
                         num44 = player.inventory[player.selectedItem].shootSpeed * scale;
                     }
                     Vector2 vec2 = Main.MouseWorld - vector;
                     vec2.Normalize();
                     if (vec2.HasNaNs())
                     {
                         vec2 = Vector2.UnitX * player.direction;
                     }
                     vec2 *= num44;
                     if (vec2.X != velocity.X || vec2.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = vec2;
                 }
                 else
                 {
                     Kill();
                 }
             }
             Vector2 vector21 = base.Center + velocity * 3f;
             Lighting.AddLight(vector21, 0.8f, 0.8f, 0.8f);
             if (Main.rand.Next(3) == 0)
             {
                 int num45 = Dust.NewDust(vector21 - base.Size / 2f, width, height, 302, velocity.X, velocity.Y, 100, default(Color), 2f);
                 Main.dust[num45].noGravity = true;
                 Main.dust[num45].position -= velocity;
             }
         }
         if (type == 927)
         {
             num = 0f;
             scale = ai[1];
             ai[0] += 1f;
             if (ai[0] >= 8f)
             {
                 ai[0] = 0f;
             }
             num2 = 9;
             num3 = Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.05f;
             soundDelay--;
             if (soundDelay <= 0)
             {
                 SoundEngine.PlaySound(SoundID.Item1, base.Center);
                 soundDelay = 6;
             }
             if (Main.myPlayer == owner)
             {
                 if (player.channel && !player.noItems && !player.CCed)
                 {
                     float num46 = 1f;
                     if (player.inventory[player.selectedItem].shoot == type)
                     {
                         num46 = player.inventory[player.selectedItem].shootSpeed;
                     }
                     Vector2 vec3 = Main.MouseWorld - vector;
                     vec3.Normalize();
                     if (vec3.HasNaNs())
                     {
                         vec3 = Vector2.UnitX * player.direction;
                     }
                     vec3 *= num46;
                     if (vec3.X != velocity.X || vec3.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = vec3;
                 }
                 else
                 {
                     Kill();
                 }
             }
             DelegateMethods.v3_1 = new Vector3(0.5f, 0.5f, 0.5f);
             Utils.PlotTileLine(base.Center - velocity, base.Center + velocity.SafeNormalize(Vector2.Zero) * 80f, 16f, DelegateMethods.CastLightOpen);
         }
         if (type == 600)
         {
             _ = ai[0];
             _ = 0f;
             ai[0] += 1f;
             if (Main.myPlayer == owner && ai[0] == 1f)
             {
                 float num47 = player.inventory[player.selectedItem].shootSpeed * scale;
                 Vector2 vector22 = vector;
                 Vector2 value8 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector22;
                 if (player.gravDir == -1f)
                 {
                     value8.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector22.Y;
                 }
                 Vector2 vector23 = Vector2.Normalize(value8);
                 if (float.IsNaN(vector23.X) || float.IsNaN(vector23.Y))
                 {
                     vector23 = -Vector2.UnitY;
                 }
                 vector23 *= num47;
                 if (vector23.X != velocity.X || vector23.Y != velocity.Y)
                 {
                     netUpdate = true;
                 }
                 velocity = vector23;
                 int num48 = 601;
                 float num49 = 3f;
                 vector22 = base.Center;
                 Vector2 vector24 = Vector2.Normalize(velocity) * num49;
                 if (float.IsNaN(vector24.X) || float.IsNaN(vector24.Y))
                 {
                     vector24 = -Vector2.UnitY;
                 }
                 NewProjectile(GetProjectileSource_FromThis(), vector22.X, vector22.Y, vector24.X, vector24.Y, num48, damage, knockBack, owner, ai[1]);
             }
             if (ai[0] >= 30f)
             {
                 Kill();
             }
         }
         if (type == 611)
         {
             if (Main.netMode != 2 && localAI[0] == 0f)
             {
                 SoundEngine.PlaySound(SoundID.Item116, base.Center);
             }
             if (localAI[1] > 0f)
             {
                 localAI[1] -= 1f;
             }
             alpha -= 42;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (localAI[0] == 0f)
             {
                 localAI[0] = velocity.ToRotation();
             }
             float num50 = ((localAI[0].ToRotationVector2().X >= 0f) ? 1 : (-1));
             if (ai[1] <= 0f)
             {
                 num50 *= -1f;
             }
             Vector2 spinningpoint5 = (num50 * (ai[0] / 30f * ((float)Math.PI * 2f) - (float)Math.PI / 2f)).ToRotationVector2();
             spinningpoint5.Y *= (float)Math.Sin(ai[1]);
             if (ai[1] <= 0f)
             {
                 spinningpoint5.Y *= -1f;
             }
             spinningpoint5 = spinningpoint5.RotatedBy(localAI[0]);
             ai[0] += 1f;
             if (ai[0] < 30f)
             {
                 velocity += 48f * spinningpoint5;
             }
             else
             {
                 Kill();
             }
         }
         if (type == 615)
         {
             num = 0f;
             if (spriteDirection == -1)
             {
                 num = (float)Math.PI;
             }
             ai[0] += 1f;
             int num51 = 0;
             if (ai[0] >= 40f)
             {
                 num51++;
             }
             if (ai[0] >= 80f)
             {
                 num51++;
             }
             if (ai[0] >= 120f)
             {
                 num51++;
             }
             int num52 = 5;
             int num53 = 0;
             ai[1] -= 1f;
             bool flag11 = false;
             int num54 = -1;
             if (ai[1] <= 0f)
             {
                 ai[1] = num52 - num53 * num51;
                 flag11 = true;
                 if ((int)ai[0] / (num52 - num53 * num51) % 7 == 0)
                 {
                     num54 = 0;
                 }
             }
             frameCounter += 1 + num51;
             if (frameCounter >= 4)
             {
                 frameCounter = 0;
                 frame++;
                 if (frame >= Main.projFrames[type])
                 {
                     frame = 0;
                 }
             }
             if (soundDelay <= 0)
             {
                 soundDelay = num52 - num53 * num51;
                 if (ai[0] != 1f)
                 {
                     SoundEngine.PlaySound(SoundID.Item36, position);
                 }
             }
             if (flag11 && Main.myPlayer == owner)
             {
                 bool canShoot = player.channel && player.HasAmmo(player.inventory[player.selectedItem], canUse: true) && !player.noItems && !player.CCed;
                 int projToShoot = 14;
                 float speed = 14f;
                 int Damage = player.GetWeaponDamage(player.inventory[player.selectedItem]);
                 float KnockBack = player.inventory[player.selectedItem].knockBack;
                 if (canShoot)
                 {
                     player.PickAmmo(player.inventory[player.selectedItem], ref projToShoot, ref speed, ref canShoot, ref Damage, ref KnockBack, out var usedAmmoItemId);
                     IEntitySource projectileSource_Item_WithPotentialAmmo = player.GetProjectileSource_Item_WithPotentialAmmo(player.HeldItem, usedAmmoItemId);
                     KnockBack = player.GetWeaponKnockback(player.inventory[player.selectedItem], KnockBack);
                     float num55 = player.inventory[player.selectedItem].shootSpeed * scale;
                     Vector2 vector25 = vector;
                     Vector2 value9 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector25;
                     if (player.gravDir == -1f)
                     {
                         value9.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector25.Y;
                     }
                     Vector2 spinningpoint6 = Vector2.Normalize(value9);
                     if (float.IsNaN(spinningpoint6.X) || float.IsNaN(spinningpoint6.Y))
                     {
                         spinningpoint6 = -Vector2.UnitY;
                     }
                     spinningpoint6 *= num55;
                     spinningpoint6 = spinningpoint6.RotatedBy(Main.rand.NextDouble() * 0.13089969754219055 - 0.06544984877109528);
                     if (spinningpoint6.X != velocity.X || spinningpoint6.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = spinningpoint6;
                     for (int n = 0; n < 1; n++)
                     {
                         Vector2 spinningpoint7 = Vector2.Normalize(velocity) * speed;
                         spinningpoint7 = spinningpoint7.RotatedBy(Main.rand.NextDouble() * 0.19634954631328583 - 0.09817477315664291);
                         if (float.IsNaN(spinningpoint7.X) || float.IsNaN(spinningpoint7.Y))
{
                             spinningpoint7 = -Vector2.UnitY;
                         }
                         NewProjectile(projectileSource_Item_WithPotentialAmmo, vector25.X, vector25.Y, spinningpoint7.X, spinningpoint7.Y, projToShoot, Damage, KnockBack, owner);
                     }
                     if (num54 == 0)
                     {
                         projToShoot = 616;
                         speed = 8f;
                         for (int num56 = 0; num56 < 1; num56++)
{
                             Vector2 spinningpoint8 = Vector2.Normalize(velocity) * speed;
                             spinningpoint8 = spinningpoint8.RotatedBy(Main.rand.NextDouble() * 0.39269909262657166 - 0.19634954631328583);
                             if (float.IsNaN(spinningpoint8.X) || float.IsNaN(spinningpoint8.Y))
{
                                 spinningpoint8 = -Vector2.UnitY;
                             }
                             NewProjectile(projectileSource_Item_WithPotentialAmmo, vector25.X, vector25.Y, spinningpoint8.X, spinningpoint8.Y, projToShoot, Damage + 20, KnockBack * 1.25f, owner);
                         }
                     }
                 }
                 else
                 {
                     Kill();
                 }
             }
         }
         if (type == 714)
         {
             num = 0f;
             if (spriteDirection == -1)
             {
                 num = (float)Math.PI;
             }
             ai[0] += 1f;
             int num57 = 0;
             int num58 = 8;
             int num59 = 0;
             ai[1] -= 1f;
             bool flag12 = false;
             int num60 = -1;
             if (ai[1] <= 0f)
             {
                 ai[1] = num58 - num59 * num57;
                 flag12 = true;
                 int num61 = (int)ai[0] / (num58 - num59 * num57);
                 if (num61 % 7 == 0)
                 {
                     num60 = 0;
                 }
                 num60 = num61 % 7;
             }
             _ = rotation;
             Vector2 center3 = base.Center;
             _ = direction;
             Vector2 v = velocity;
             frameCounter += 1 + num57;
             if (frameCounter >= 4)
             {
                 frameCounter = 0;
                 frame++;
                 if (frame >= Main.projFrames[type])
                 {
                     frame = 0;
                 }
             }
             if (soundDelay <= 0 && Main.player[owner].controlUseItem)
             {
                 soundDelay = num58 - num59 * num57;
                 if (ai[0] != 1f)
                 {
                     SoundEngine.PlaySound(SoundID.Item156, position);
                 }
             }
             if (flag12 && Main.myPlayer == owner)
             {
                 bool canShoot2 = player.channel && player.HasAmmo(player.inventory[player.selectedItem], canUse: true) && !player.noItems && !player.CCed;
                 int projToShoot2 = 134;
                 float speed2 = 8f;
                 int Damage2 = player.GetWeaponDamage(player.inventory[player.selectedItem]);
                 float KnockBack2 = player.inventory[player.selectedItem].knockBack;
                 if (num60 == 3)
                 {
                     speed2 += 1f;
                 }
                 if (canShoot2)
                 {
                     player.PickAmmo(player.inventory[player.selectedItem], ref projToShoot2, ref speed2, ref canShoot2, ref Damage2, ref KnockBack2, out var usedAmmoItemId2);
                     KnockBack2 = player.GetWeaponKnockback(player.inventory[player.selectedItem], KnockBack2);
                     IEntitySource projectileSource_Item_WithPotentialAmmo2 = player.GetProjectileSource_Item_WithPotentialAmmo(player.HeldItem, usedAmmoItemId2);
                     float num62 = player.inventory[player.selectedItem].shootSpeed * scale;
                     Vector2 vector26 = vector;
                     Vector2 value10 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector26;
                     if (player.gravDir == -1f)
                     {
                         value10.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector26.Y;
                     }
                     Vector2 spinningpoint9 = Vector2.Normalize(value10);
                     if (float.IsNaN(spinningpoint9.X) || float.IsNaN(spinningpoint9.Y))
                     {
                         spinningpoint9 = -Vector2.UnitY;
                     }
                     spinningpoint9 *= num62;
                     spinningpoint9 = spinningpoint9.RotatedBy((Main.rand.NextDouble() * 0.13089969754219055 - 0.06544984877109528) * 0.5);
                     if (spinningpoint9.X != velocity.X || spinningpoint9.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = spinningpoint9;
                     for (int num63 = 0; num63 < 1; num63++)
                     {
                         Vector2 spinningpoint10 = Vector2.Normalize(velocity) * speed2;
                         spinningpoint10 = spinningpoint10.RotatedBy(Main.rand.NextDouble() * 0.19634954631328583 - 0.09817477315664291);
                         if (float.IsNaN(spinningpoint10.X) || float.IsNaN(spinningpoint10.Y))
{
                             spinningpoint10 = -Vector2.UnitY;
                         }
                         NewProjectile(projectileSource_Item_WithPotentialAmmo2, vector26.X, vector26.Y, spinningpoint10.X, spinningpoint10.Y, projToShoot2, Damage2, KnockBack2, owner, num60);
                         if (num60 == 5)
{
                             for (float num64 = -1f; num64 <= 1f; num64 += 2f)
{
                                 Vector2 vector27 = spinningpoint10.RotatedBy((float)Math.PI * 2f * num64 * 1f / 80f);
                                 if (float.IsNaN(spinningpoint10.X) || float.IsNaN(spinningpoint10.Y))
{
                                     vector27 = -Vector2.UnitY;
                                 }
                                 NewProjectile(projectileSource_Item_WithPotentialAmmo2, vector26.X, vector26.Y, vector27.X, vector27.Y, projToShoot2, Damage2, KnockBack2, owner, num60);
                             }
                         }
                         if (num60 == 4)
{
                             NewProjectile(projectileSource_Item_WithPotentialAmmo2, vector26.X, vector26.Y, spinningpoint10.X, spinningpoint10.Y, projToShoot2, Damage2, KnockBack2, owner, num60, 1f);
                         }
                     }
                 }
                 else
                 {
                     Kill();
                 }
             }
             Vector2 vector28 = base.Center + velocity.ToRotation().ToRotationVector2() * 40f;
             Vector2 vector29 = center3 + v.ToRotation().ToRotationVector2() * 40f;
             Color color = Main.hslToRgb(ai[0] / 90f % 1f, 1f, 0.5f);
             color.A = 120;
             int num65 = 267;
             Dust dust = Dust.NewDustPerfect(vector28, num65, Vector2.Zero);
             dust.color = color;
             dust.scale = 0.6f;
             dust.fadeIn = 0.9f;
             dust.noGravity = true;
             Dust dust2 = Dust.NewDustPerfect(vector28, num65, Vector2.Zero);
             dust2.color = color;
             dust2.scale = 0.6f;
             dust2.fadeIn = 0.7f;
             dust2.noGravity = true;
             dust2.velocity = -velocity.RotatedBy(2.094395160675049) / 10f;
             Dust dust3 = Dust.NewDustPerfect(vector28, num65, Vector2.Zero);
             dust3.color = color;
             dust3.scale = 0.6f;
             dust3.fadeIn = 0.7f;
             dust3.noGravity = true;
             dust3.velocity = -velocity.RotatedBy(-2.094395160675049) / 10f;
             if (vector28 != vector29)
             {
                 float num66 = -1f;
                 Dust dust4 = Dust.NewDustPerfect(Vector2.Lerp(vector28, vector29, 0.8f), num65, Vector2.Zero);
                 dust4.velocity = (vector28 - vector29).SafeNormalize(Vector2.Zero) * 2f;
                 dust4.color = color;
                 dust4.scale = 0.6f;
                 dust4.fadeIn = 0.9f;
                 dust4.velocity *= num66;
                 dust4.noGravity = true;
                 Dust dust5 = Dust.NewDustPerfect(Vector2.Lerp(vector28, vector29, 0.5f), num65, Vector2.Zero);
                 dust5.velocity = (vector28 - vector29).SafeNormalize(Vector2.Zero) * 2f;
                 dust5.color = color;
                 dust5.scale = 0.6f;
                 dust5.fadeIn = 0.9f;
                 dust5.velocity *= num66;
                 dust5.noGravity = true;
                 Dust dust6 = Dust.NewDustPerfect(Vector2.Lerp(vector28, vector29, 0.2f), num65, Vector2.Zero);
                 dust6.velocity = (vector28 - vector29).SafeNormalize(Vector2.Zero) * 2f;
                 dust6.color = color;
                 dust6.scale = 0.6f;
                 dust6.fadeIn = 0.9f;
                 dust6.velocity *= num66;
                 dust6.noGravity = true;
             }
         }
         if (type == 630)
         {
             num = 0f;
             if (spriteDirection == -1)
             {
                 num = (float)Math.PI;
             }
             ai[0] += 1f;
             int num67 = 0;
             if (ai[0] >= 40f)
             {
                 num67++;
             }
             if (ai[0] >= 80f)
             {
                 num67++;
             }
             if (ai[0] >= 120f)
             {
                 num67++;
             }
             int num68 = 24;
             int num69 = 2;
             ai[1] -= 1f;
             bool flag13 = false;
             if (ai[1] <= 0f)
             {
                 ai[1] = num68 - num69 * num67;
                 flag13 = true;
                 _ = (int)ai[0] / (num68 - num69 * num67);
             }
             bool canShoot3 = player.channel && player.HasAmmo(player.inventory[player.selectedItem], canUse: true) && !player.noItems && !player.CCed;
             if (localAI[0] > 0f)
             {
                 localAI[0] -= 1f;
             }
             if (soundDelay <= 0 && canShoot3)
             {
                 soundDelay = num68 - num69 * num67;
                 if (ai[0] != 1f)
                 {
                     SoundEngine.PlaySound(SoundID.Item5, position);
                 }
                 localAI[0] = 12f;
             }
             player.phantasmTime = 2;
             if (flag13 && Main.myPlayer == owner)
             {
                 int projToShoot3 = 14;
                 float speed3 = 14f;
                 int Damage3 = player.GetWeaponDamage(player.inventory[player.selectedItem]);
                 float KnockBack3 = player.inventory[player.selectedItem].knockBack;
                 if (canShoot3)
                 {
                     player.PickAmmo(player.inventory[player.selectedItem], ref projToShoot3, ref speed3, ref canShoot3, ref Damage3, ref KnockBack3, out var usedAmmoItemId3);
                     IEntitySource projectileSource_Item_WithPotentialAmmo3 = player.GetProjectileSource_Item_WithPotentialAmmo(player.HeldItem, usedAmmoItemId3);
                     KnockBack3 = player.GetWeaponKnockback(player.inventory[player.selectedItem], KnockBack3);
                     float num70 = player.inventory[player.selectedItem].shootSpeed * scale;
                     Vector2 vector30 = vector;
                     Vector2 value11 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector30;
                     if (player.gravDir == -1f)
                     {
                         value11.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector30.Y;
                     }
                     Vector2 vector31 = Vector2.Normalize(value11);
                     if (float.IsNaN(vector31.X) || float.IsNaN(vector31.Y))
                     {
                         vector31 = -Vector2.UnitY;
                     }
                     vector31 *= num70;
                     if (vector31.X != velocity.X || vector31.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = vector31 * 0.55f;
                     for (int num71 = 0; num71 < 4; num71++)
                     {
                         Vector2 vector32 = Vector2.Normalize(velocity) * speed3 * (0.6f + Main.rand.NextFloat() * 0.8f);
                         if (float.IsNaN(vector32.X) || float.IsNaN(vector32.Y))
{
                             vector32 = -Vector2.UnitY;
                         }
                         Vector2 vector33 = vector30 + Utils.RandomVector2(Main.rand, -15f, 15f);
                         int num72 = NewProjectile(projectileSource_Item_WithPotentialAmmo3, vector33.X, vector33.Y, vector32.X, vector32.Y, projToShoot3, Damage3, KnockBack3, owner);
                         Main.projectile[num72].noDropItem = true;
                     }
                 }
                 else
                 {
                     Kill();
                 }
             }
         }
         if (type == 705)
         {
             num = 0f;
             if (spriteDirection == -1)
             {
                 num = (float)Math.PI;
             }
             ai[0] += 1f;
             int itemAnimationMax = player.itemAnimationMax;
             ai[1] -= 1f;
             bool flag14 = false;
             if (ai[1] <= 0f)
             {
                 ai[1] = itemAnimationMax;
                 flag14 = true;
             }
             bool canShoot4 = player.channel && player.HasAmmo(player.inventory[player.selectedItem], canUse: true) && !player.noItems && !player.CCed;
             if (localAI[0] > 0f)
             {
                 localAI[0] -= 1f;
             }
             if (soundDelay <= 0 && canShoot4)
             {
                 soundDelay = itemAnimationMax;
                 if (ai[0] != 1f)
                 {
                     SoundEngine.PlaySound(SoundID.Item5, position);
                 }
                 localAI[0] = 12f;
             }
             if (flag14 && Main.myPlayer == owner)
             {
                 int projToShoot4 = 14;
                 float speed4 = 12f;
                 int Damage4 = player.GetWeaponDamage(player.inventory[player.selectedItem]);
                 float KnockBack4 = player.inventory[player.selectedItem].knockBack;
                 int num73 = 2;
                 float num74 = 1.5f;
                 if (canShoot4)
                 {
                     player.PickAmmo(player.inventory[player.selectedItem], ref projToShoot4, ref speed4, ref canShoot4, ref Damage4, ref KnockBack4, out var usedAmmoItemId4);
                     IEntitySource projectileSource_Item_WithPotentialAmmo4 = player.GetProjectileSource_Item_WithPotentialAmmo(player.HeldItem, usedAmmoItemId4);
                     KnockBack4 = player.GetWeaponKnockback(player.inventory[player.selectedItem], KnockBack4);
                     if (projToShoot4 == 1)
                     {
                         projToShoot4 = 2;
                     }
                     if (++player.phantomPhoneixCounter >= 3)
                     {
                         player.phantomPhoneixCounter = 0;
                         num73 = 1;
                         Damage4 *= 2;
                         num74 = 0f;
                         ai[1] *= 1.5f;
                         projToShoot4 = 706;
                         speed4 = 16f;
                     }
                     float num75 = player.inventory[player.selectedItem].shootSpeed * scale;
                     Vector2 vector34 = vector;
                     Vector2 value12 = Main.screenPosition + new Vector2(Main.mouseX, Main.mouseY) - vector34;
                     if (player.gravDir == -1f)
                     {
                         value12.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector34.Y;
                     }
                     Vector2 vector35 = Vector2.Normalize(value12);
                     if (float.IsNaN(vector35.X) || float.IsNaN(vector35.Y))
                     {
                         vector35 = -Vector2.UnitY;
                     }
                     vector35 *= num75;
                     if (vector35.X != velocity.X || vector35.Y != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity = vector35 * 0.55f;
                     for (int num76 = 0; num76 < num73; num76++)
                     {
                         Vector2 vector36 = Vector2.Normalize(velocity) * speed4;
                         vector36 += Main.rand.NextVector2Square(0f - num74, num74);
                         if (float.IsNaN(vector36.X) || float.IsNaN(vector36.Y))
{
                             vector36 = -Vector2.UnitY;
                         }
                         Vector2 vector37 = vector34;
                         int num77 = NewProjectile(projectileSource_Item_WithPotentialAmmo4, vector37.X, vector37.Y, vector36.X, vector36.Y, projToShoot4, Damage4, KnockBack4, owner);
                         Main.projectile[num77].noDropItem = true;
                     }
                 }
                 else
                 {
                     Kill();
                 }
             }
         }
         position = player.RotatedRelativePoint(player.MountedCenter, reverseRotation: false, addGfxOffY: false) - base.Size / 2f;
         rotation = velocity.ToRotation() + num;
         spriteDirection = direction;
         timeLeft = 2;
         player.ChangeDir(direction);
         player.heldProj = whoAmI;
         player.SetDummyItemTime(num2);
         player.itemRotation = MathHelper.WrapAngle((float)Math.Atan2(velocity.Y * (float)direction, velocity.X * (float)direction) + num3);
         if (type == 460 || type == 611)
         {
             Vector2 vector38 = Main.OffsetsPlayerOnhand[player.bodyFrame.Y / 56] * 2f;
             if (player.direction != 1)
             {
                 vector38.X = (float)player.bodyFrame.Width - vector38.X;
             }
             if (player.gravDir != 1f)
             {
                 vector38.Y = (float)player.bodyFrame.Height - vector38.Y;
             }
             vector38 -= new Vector2(player.bodyFrame.Width - player.width, player.bodyFrame.Height - 42) / 2f;
             base.Center = player.RotatedRelativePoint(player.MountedCenter - new Vector2(20f, 42f) / 2f + vector38, reverseRotation: false, addGfxOffY: false) - velocity;
         }
         if (type == 615)
         {
             position.Y += player.gravDir * 2f;
         }
         if (type == 714)
         {
             position.Y += player.gravDir * 2f;
         }
         if (type == 611 && alpha == 0)
         {
             for (int num78 = 0; num78 < 2; num78++)
             {
                 Dust obj = Main.dust[Dust.NewDust(position + velocity * 2f, width, height, 6, 0f, 0f, 100, Color.Transparent, 2f)];
                 obj.noGravity = true;
                 obj.velocity *= 2f;
                 obj.velocity += localAI[0].ToRotationVector2();
                 obj.fadeIn = 1.5f;
             }
             float num79 = 18f;
             for (int num80 = 0; (float)num80 < num79; num80++)
             {
                 if (Main.rand.Next(4) == 0)
                 {
                     Vector2 vector39 = position + velocity + velocity * ((float)num80 / num79);
                     Dust obj2 = Main.dust[Dust.NewDust(vector39, width, height, 6, 0f, 0f, 100, Color.Transparent)];
                     obj2.noGravity = true;
                     obj2.fadeIn = 0.5f;
                     obj2.velocity += localAI[0].ToRotationVector2();
                     obj2.noLight = true;
                 }
             }
         }
         if (type == 927)
         {
             player.itemAnimation = num2 - (int)ai[0];
         }
     }
References Entity.active, Tile.active(), Lighting.AddLight(), Player.bodyFrame, DelegateMethods.CastLightOpen(), Player.CCed, Entity.Center, Player.ChangeDir(), Player.channel, Player.CheckMana(), Color, Dust.color, Player.controlUseItem, Dust.customData, Damage, Item.damage, Entity.direction, Main.dust, Dust.fadeIn, Utils.GetLerpValue(), Player.GetProjectileSource_Item_WithPotentialAmmo(), Player.GetWeaponDamage(), Player.GetWeaponKnockback(), Player.gravDir, Player.HasAmmo(), Player.HeldItem, Player.heldProj, Main.hslToRgb(), Player.inventory, SoundID.Item1, SoundID.Item116, SoundID.Item132, SoundID.Item15, SoundID.Item156, SoundID.Item36, SoundID.Item5, SoundID.Item91, Player.itemAnimation, Player.itemAnimationMax, Player.itemRotation, Item.knockBack, Player.magicDamage, Item.mana, Player.MountedCenter, Main.MouseWorld, Main.mouseX, Main.mouseY, Main.myPlayer, Main.netMode, Dust.NewDust(), Dust.NewDustPerfect(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), noDropItem, Dust.noGravity, Player.noItems, Dust.noLight, Main.OffsetsPlayerOnhand, Player.phantasmTime, Player.phantomPhoneixCounter, Player.PickAmmo(), Main.player, SoundEngine.PlaySound(), Utils.PlotTileLine(), Dust.position, Main.projectile, Main.projFrames, Main.rand, Utils.RandomVector2(), Player.RotatedRelativePoint(), Dust.scale, Main.screenHeight, Main.screenPosition, Player.selectedItem, Player.SetDummyItemTime(), Item.shoot, Item.shootSpeed, Main.tile, Item.tileBoost, Player.tileRangeX, Player.tileRangeY, Player.tileTargetX, Player.tileTargetY, type, DelegateMethods.v3_1, Dust.velocity, and Entity.width.