Terraria: Projectile.AI_155_RemoveRope
AI_155_RemoveRope()
void Projectile.AI_155_RemoveRope (Point start, Point end) inline private
     {
         int x = start.X;
         for (int num = start.Y; num >= end.Y; num--)
         {
             Tile tile = Main.tile[x, num];
             if (tile.active() && tile.type == 504)
             {
                 WorldGen.KillTile(x, num);
                 if (Main.netMode != 0)
                 {
                     NetMessage.SendData(17, -1, -1, null, 0, x, num);
                 }
             }
         }
     }
References Tile.active(), WorldGen.KillTile(), Main.netMode, NetMessage.SendData(), Main.tile, and Tile.type.