Terraria: Projectile.CanHitWithOwnBody
CanHitWithOwnBody()
bool Projectile.CanHitWithOwnBody (Entity ent) inline
     {
         if (Distance(ent.Center) > ownerHitCheckDistance)
         {
             return false;
         }
         bool flag = Collision.CanHit(base.position, width, height, ent.position, ent.width, ent.height) || Collision.CanHitLine(base.Center + new Vector2(direction * width / 2, -height / 3), 0, 0, ent.Center + new Vector2(0f, -ent.height / 3), 0, 0) || Collision.CanHitLine(base.Center + new Vector2(direction * width / 2, -height / 3), 0, 0, ent.Center, 0, 0) || Collision.CanHitLine(base.Center + new Vector2(direction * width / 2, 0f), 0, 0, ent.Center + new Vector2(0f, ent.height / 3), 0, 0);
         float num = ProjectileID.Sets.ExtendedCanHitCheckRange[type];
         if (num != 0f)
         {
             if (flag)
             {
                 return flag;
             }
             GenSearch genSearch = ProjectileID.Sets.ExtendedCanHitCheckSearch[type];
             Vector2 position = base.Top + new Vector2(0f, 0f - num);
             Vector2 position2 = ent.Top + new Vector2(0f, 0f - num);
             if (genSearch != null)
             {
                 if (WorldUtils.Find(base.Top.ToTileCoordinates(), Searches.Chain(genSearch, _cachedConditions_notNull, _cachedConditions_solid), out var result))
                 {
                     position = result.ToWorldCoordinates();
                 }
                 if (WorldUtils.Find(ent.Top.ToTileCoordinates(), Searches.Chain(genSearch, _cachedConditions_notNull, _cachedConditions_solid), out result))
                 {
                     position2 = result.ToWorldCoordinates();
                 }
             }
             flag |= Collision.CanHitLine(position, 0, 0, position2, 0, 0);
         }
         return flag;
     }
References _cachedConditions_notNull, _cachedConditions_solid, Collision.CanHit(), Collision.CanHitLine(), Entity.Center, Searches.Chain(), Entity.direction, Entity.Distance(), ProjectileID.Sets.ExtendedCanHitCheckRange, ProjectileID.Sets.ExtendedCanHitCheckSearch, WorldUtils.Find(), Entity.height, ownerHitCheckDistance, Entity.position, Entity.Top, type, and Entity.width.