Terraria: Projectile.StatusPvP
StatusPvP()
void Projectile.StatusPvP (int i) inline
     {
         if ((melee || ProjectileID.Sets.IsAWhip[type]) && Main.player[owner].meleeEnchant > 0 && !noEnchantments)
         {
             byte meleeEnchant = Main.player[owner].meleeEnchant;
             if (meleeEnchant == 1)
             {
                 Main.player[i].AddBuff(70, 60 * Main.rand.Next(5, 10), quiet: false);
             }
             if (meleeEnchant == 2)
             {
                 Main.player[i].AddBuff(39, 60 * Main.rand.Next(3, 7), quiet: false);
             }
             if (meleeEnchant == 3)
             {
                 Main.player[i].AddBuff(24, 60 * Main.rand.Next(3, 7), quiet: false);
             }
             if (meleeEnchant == 5)
             {
                 Main.player[i].AddBuff(69, 60 * Main.rand.Next(10, 20), quiet: false);
             }
             if (meleeEnchant == 6)
             {
                 Main.player[i].AddBuff(31, 60 * Main.rand.Next(1, 4), quiet: false);
             }
             if (meleeEnchant == 8)
             {
                 Main.player[i].AddBuff(20, 60 * Main.rand.Next(5, 10), quiet: false);
             }
         }
         if (type == 978)
         {
             Main.player[i].AddBuff(24, 180);
         }
         if (type == 295 || type == 296)
         {
             Main.player[i].AddBuff(323, 60 * Main.rand.Next(8, 16), quiet: false);
         }
         if (type >= 399 && type <= 402)
         {
             Main.player[i].AddBuff(24, 60 * Main.rand.Next(3, 7), quiet: false);
         }
         if (type == 478 || type == 480)
         {
             Main.player[i].AddBuff(39, 60 * Main.rand.Next(3, 7), quiet: false);
         }
         if ((melee || ranged) && Main.player[owner].frostBurn && !noEnchantments)
         {
             Main.player[i].AddBuff(324, 60 * Main.rand.Next(1, 8), quiet: false);
         }
         if (melee && Main.player[owner].magmaStone && !noEnchantments)
         {
             if (Main.rand.Next(4) == 0)
             {
                 Main.player[i].AddBuff(24, 360, quiet: false);
             }
             else if (Main.rand.Next(2) == 0)
             {
                 Main.player[i].AddBuff(24, 240, quiet: false);
             }
             else
             {
                 Main.player[i].AddBuff(24, 120, quiet: false);
             }
         }
         if (type == 2 && Main.rand.Next(3) == 0)
         {
             Main.player[i].AddBuff(24, 180, quiet: false);
         }
         if (type == 172)
         {
             if (Main.rand.Next(3) == 0)
             {
                 Main.player[i].AddBuff(44, 240, quiet: false);
             }
         }
         else if (type == 15)
         {
             int num = 24;
             if (Main.remixWorld)
             {
                 num = 323;
             }
             if (Main.rand.Next(2) == 0)
             {
                 Main.player[i].AddBuff(num, 300, quiet: false);
             }
         }
         else if (type == 253)
         {
             if (Main.rand.Next(2) == 0)
             {
                 Main.player[i].AddBuff(44, 480, quiet: false);
             }
         }
         else if (type == 19)
         {
             if (Main.rand.Next(5) == 0)
             {
                 Main.player[i].AddBuff(24, 180, quiet: false);
             }
         }
         else if (type == 113)
         {
             if (Main.rand.Next(5) == 0)
             {
                 Main.player[i].AddBuff(44, 180, quiet: false);
             }
         }
         else if (type == 33)
         {
             if (Main.rand.Next(5) == 0)
             {
                 Main.player[i].AddBuff(20, 420, quiet: false);
             }
         }
         else if (type == 976)
         {
             if (Main.rand.Next(4) == 0)
             {
                 Main.player[i].AddBuff(20, 420, quiet: false);
             }
         }
         else if (type == 34)
         {
             if (Main.rand.Next(2) == 0)
             {
                 Main.player[i].AddBuff(24, 240, quiet: false);
             }
         }
         else if (type == 35)
         {
             if (Main.rand.Next(4) == 0)
             {
                 Main.player[i].AddBuff(24, 180, quiet: false);
             }
         }
         else if (type == 54)
         {
             if (Main.rand.Next(2) == 0)
             {
                 Main.player[i].AddBuff(20, 600, quiet: false);
             }
         }
         else if (type == 267)
         {
             if (Main.rand.Next(3) == 0)
             {
                 Main.player[i].AddBuff(20, 3600, quiet: false);
             }
             else
             {
                 Main.player[i].AddBuff(20, 1800, quiet: false);
             }
         }
         else if (type == 63)
         {
             if (Main.rand.Next(3) != 0)
             {
                 Main.player[i].AddBuff(31, 120, quiet: false);
             }
         }
         else if (type == 85 || type == 188)
         {
             Main.player[i].AddBuff(24, 1200, quiet: false);
         }
         else if (type == 95 || type == 103 || type == 104 || type == 482)
         {
             Main.player[i].AddBuff(39, 420, quiet: false);
         }
         else if (type == 278 || type == 279 || type == 280)
         {
             Main.player[i].AddBuff(69, 900, quiet: false);
         }
         else if (type == 282 || type == 283)
         {
             Main.player[i].AddBuff(70, 600, quiet: false);
         }
         if (type == 163 || type == 310 || type == 1008 || type == 1010 || type == 1011)
         {
             if (Main.rand.Next(3) == 0)
             {
                 Main.player[i].AddBuff(24, 600, quiet: false);
             }
             else
             {
                 Main.player[i].AddBuff(24, 300, quiet: false);
             }
         }
         if (type == 1009)
         {
             Main.player[i].AddBuff(39, 300, quiet: false);
         }
         else if (type == 265)
         {
             Main.player[i].AddBuff(20, 1200, quiet: false);
         }
         else if (type == 355)
         {
             Main.player[i].AddBuff(70, 1800, quiet: false);
         }
     }
References Player.AddBuff(), Player.frostBurn, ProjectileID.Sets.IsAWhip, Player.magmaStone, melee, Player.meleeEnchant, UnifiedRandom.Next(), noEnchantments, owner, Main.player, Main.rand, ranged, Main.remixWorld, and type.
Referenced by Damage().