Terraria: Projectile.ProjLight
ProjLight()
void Projectile.ProjLight () inline
     {
         if (!(light > 0f))
         {
             return;
         }
         float num = light;
         float num2 = light;
         float num3 = light;
         switch (type)
         {
         case 987:
             num *= 0.6f;
             num2 *= 0.5f;
             num3 *= 0.1f;
             break;
         case 988:
             num *= 0.8f;
             num2 *= 0.35f;
             num3 *= 0f;
             break;
         case 989:
             num *= 0f;
             num2 *= 0.65f;
             num3 *= 0f;
             break;
         case 990:
             num *= 0f;
             num2 *= 0.35f;
             num3 *= 0.7f;
             break;
         case 991:
             num *= 0.9f;
             num2 *= 0f;
             num3 *= 0.5f;
             break;
         case 992:
             num *= 0.75f;
             num2 *= 0f;
             num3 *= 0.75f;
             break;
         case 993:
             num *= (float)Main.DiscoR / 255f;
             num2 *= (float)Main.DiscoG / 255f;
             num3 *= (float)Main.DiscoB / 255f;
             break;
         }
         if (type == 446)
         {
             num *= 0f;
             num3 *= 0.8f;
         }
         else if (type == 493 || type == 494)
         {
             num2 *= 0.3f;
         }
         else if (type == 876)
         {
             num *= 0.1f;
             num2 *= 0.7f;
             num3 *= 1f;
         }
         else if (type == 867)
         {
             float num4 = (float)Main.rand.Next(28, 42) * 0.005f;
             num4 += (float)(270 - Main.mouseTextColor) / 500f;
             num = 0.1f;
             num2 = 0.3f + num4 / 2f;
             num3 = 0.6f + num4;
         }
         else if (type == 1000)
         {
             float num5 = (float)Main.rand.Next(28, 42) * 0.005f;
             num5 += (float)(270 - Main.mouseTextColor) / 500f;
             num = 0.3f + num5 * 0.25f;
             num2 = 0.35f + num5 * 0.75f;
             num3 = 0.5f + num5;
         }
         else if (type == 332)
         {
             num3 *= 0.1f;
             num2 *= 0.6f;
         }
         else if (type == 259)
         {
             num3 *= 0.1f;
             if (Main.getGoodWorld)
             {
                 num = 0f;
                 num2 = 0f;
                 num3 = 0f;
             }
         }
         else if (type == 329)
         {
             num3 *= 0.1f;
             num2 *= 0.9f;
         }
         else if (type == 2 || type == 82)
         {
             num2 *= 0.75f;
             num3 *= 0.55f;
         }
         else if (type == 172)
         {
             num2 *= 0.55f;
             num *= 0.35f;
         }
         else if (type == 308)
         {
             num2 *= 0.7f;
             num *= 0.1f;
         }
         else if (type == 304)
         {
             num2 *= 0.2f;
             num3 *= 0.1f;
         }
         else if (type == 263)
         {
             num2 *= 0.7f;
             num *= 0.1f;
         }
         else if (type == 274)
         {
             num2 *= 0.1f;
             num *= 0.7f;
         }
         else if (type == 254)
         {
             num *= 0.1f;
         }
         else if (type == 94)
         {
             num *= 0.5f;
             num2 *= 0f;
         }
         else if (type == 95 || type == 96 || type == 103 || type == 104)
         {
             num *= 0.35f;
             num2 *= 1f;
             num3 *= 0f;
         }
         else if (type == 4)
         {
             num2 *= 0.1f;
             num *= 0.5f;
         }
         else if (type == 257)
         {
             num2 *= 0.9f;
             num *= 0.1f;
         }
         else if (type == 9)
         {
             num2 *= 0.1f;
             num3 *= 0.6f;
         }
         else if (type == 488)
         {
             num = 0.3f;
             num3 = 0.25f;
             num2 = 0f;
         }
         else if (type == 92)
         {
             num2 *= 0.6f;
             num *= 0.8f;
         }
         else if (type == 93)
         {
             num2 *= 1f;
             num *= 1f;
             num3 *= 0.01f;
         }
         else if (type == 12 || type == 955)
         {
             num *= 0.9f;
             num2 *= 0.8f;
             num3 *= 0.1f;
         }
         else if (type == 14 || type == 110 || type == 180 || type == 242 || type == 302)
         {
             num2 *= 0.7f;
             num3 *= 0.1f;
         }
         else if (type == 981)
         {
             num2 *= 0.7f;
             num3 *= 0.7f;
         }
         else if (type == 15)
         {
             num2 *= 0.4f;
             num3 *= 0.1f;
             num = 1f;
         }
         else if (type == 16)
         {
             num *= 0.1f;
             num2 *= 0.4f;
             num3 = 1f;
         }
         else if (type == 18)
         {
             num2 *= 0.1f;
             num *= 0.6f;
         }
         else if (type == 19)
         {
             num2 *= 0.5f;
             num3 *= 0.1f;
         }
         else if (type == 20)
         {
             num *= 0.1f;
             num3 *= 0.3f;
         }
         else if (type == 22)
         {
             num = 0f;
             num2 = 0f;
         }
         else if (type == 27)
         {
             num *= 0f;
             num2 *= 0.3f;
             num3 = 1f;
         }
         else if (type == 34)
         {
             num2 *= 0.1f;
             num3 *= 0.1f;
         }
         else if (type == 36)
         {
             num = 0.8f;
             num2 *= 0.2f;
             num3 *= 0.6f;
         }
         else if (type == 41)
         {
             num2 *= 0.8f;
             num3 *= 0.6f;
         }
         else if (type == 44 || type == 45)
         {
             num3 = 1f;
             num *= 0.6f;
             num2 *= 0.1f;
         }
         else if (type == 50)
         {
             num *= 0.7f;
             num3 *= 0.8f;
         }
         else if (type == 515)
         {
             num2 *= 0.6f;
             num3 *= 0.85f;
         }
         else if (type == 870)
         {
             num *= 0.9f;
             num2 = 0.35f;
         }
         else if (type == 53)
         {
             num *= 0.7f;
             num2 *= 0.8f;
         }
         else if (type == 473)
         {
             num *= 1.05f;
             num2 *= 0.95f;
             num3 *= 0.55f;
         }
         else if (type == 72)
         {
             num *= 0.45f;
             num2 *= 0.75f;
             num3 = 1f;
         }
         else if (type == 86)
         {
             num *= 1f;
             num2 *= 0.45f;
             num3 = 0.75f;
         }
         else if (type == 87)
         {
             num *= 0.45f;
             num2 = 1f;
             num3 *= 0.75f;
         }
         else if (type == 73)
         {
             num *= 0.4f;
             num2 *= 0.6f;
             num3 *= 1f;
         }
         else if (type == 74)
         {
             num *= 1f;
             num2 *= 0.4f;
             num3 *= 0.6f;
         }
         else if (type == 284)
         {
             num *= 1f;
             num2 *= 0.1f;
             num3 *= 0.8f;
         }
         else if (type == 285)
         {
             num *= 0.1f;
             num2 *= 0.5f;
             num3 *= 1f;
         }
         else if (type == 286)
         {
             num *= 1f;
             num2 *= 0.5f;
             num3 *= 0.1f;
         }
         else if (type == 287)
         {
             num *= 0.9f;
             num2 *= 1f;
             num3 *= 0.4f;
         }
         else if (type == 283)
         {
             num *= 0.8f;
             num2 *= 0.1f;
         }
         else if (type == 76 || type == 77 || type == 78)
         {
             num *= 1f;
             num2 *= 0.3f;
             num3 *= 0.6f;
         }
         else if (type == 79)
         {
             num = (float)Main.DiscoR / 255f;
             num2 = (float)Main.DiscoG / 255f;
             num3 = (float)Main.DiscoB / 255f;
         }
         else if (type == 80)
         {
             num *= 0f;
             num2 *= 0.8f;
             num3 *= 1f;
         }
         else if (type == 83 || type == 88)
         {
             num *= 0.7f;
             num2 *= 0f;
             num3 *= 1f;
         }
         else if (type == 100)
         {
             num *= 1f;
             num2 *= 0.5f;
             num3 *= 0f;
         }
         else if (type == 84 || type == 389)
         {
             num *= 0.8f;
             num2 *= 0f;
             num3 *= 0.5f;
         }
         else if (type == 89 || type == 90)
         {
             num2 *= 0.2f;
             num3 *= 1f;
             num *= 0.05f;
         }
         else if (type == 106)
         {
             num *= 0f;
             num2 *= 0.5f;
             num3 *= 1f;
         }
         else if (type == 113)
         {
             num *= 0.25f;
             num2 *= 0.75f;
             num3 *= 1f;
         }
         else if (type == 114 || type == 115)
         {
             num *= 0.5f;
             num2 *= 0.05f;
             num3 *= 1f;
         }
         else if (type == 116)
         {
             num3 *= 0.25f;
         }
         else if (type == 131)
         {
             num *= 0.1f;
             num2 *= 0.4f;
         }
         else if (type == 132 || type == 157)
         {
             num *= 0.2f;
             num3 *= 0.6f;
         }
         else if (type == 156)
         {
             num *= 1f;
             num3 *= 0.6f;
             num2 = 0f;
         }
         else if (type == 173)
         {
             num *= 0.3f;
             num3 *= 1f;
             num2 = 0.4f;
         }
         else if (type == 207)
         {
             num *= 0.4f;
             num3 *= 0.4f;
         }
         else if (type == 253)
         {
             num = 0f;
             num2 *= 0.4f;
         }
         else if (type == 211)
         {
             num *= 0.5f;
             num2 *= 0.9f;
             num3 *= 1f;
             if (localAI[0] == 0f)
             {
                 light = 1.5f;
             }
             else
             {
                 light = 1f;
             }
         }
         else if (type == 209)
         {
             float num6 = (255f - (float)alpha) / 255f;
             num *= 0.3f;
             num2 *= 0.4f;
             num3 *= 1.75f;
             num3 *= num6;
             num *= num6;
             num2 *= num6;
         }
         else if (type == 226 || ((type == 221) | (type == 229)))
         {
             num *= 0.25f;
             num2 *= 1f;
             num3 *= 0.5f;
         }
         else if (type == 251)
         {
             num = (float)Main.DiscoR / 255f;
             num2 = (float)Main.DiscoG / 255f;
             num3 = (float)Main.DiscoB / 255f;
             num = (num + 1f) / 2f;
             num2 = (num2 + 1f) / 2f;
             num3 = (num3 + 1f) / 2f;
             num *= light;
             num2 *= light;
             num3 *= light;
         }
         else if (type == 278 || type == 279)
         {
             num *= 1f;
             num2 *= 1f;
             num3 *= 0f;
         }
         if (type == 870)
         {
             Vector3 rgb = (DelegateMethods.v3_1 = new Vector3(num, num2, num3));
             Point p = base.Center.ToTileCoordinates();
             DelegateMethods.v2_1 = p.ToVector2();
             DelegateMethods.f_1 = 4.5f;
             Utils.PlotTileArea(p.X, p.Y, DelegateMethods.SpreadLightOpen_StopForSolids);
             Lighting.AddLight(base.Center, rgb);
         }
         else
         {
             Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), num, num2, num3);
         }
     }
References Lighting.AddLight(), alpha, Main.DiscoB, Main.DiscoG, Main.DiscoR, DelegateMethods.f_1, Main.getGoodWorld, Entity.height, light, localAI, Main.mouseTextColor, UnifiedRandom.Next(), Utils.PlotTileArea(), Entity.position, Main.rand, DelegateMethods.SpreadLightOpen_StopForSolids(), type, DelegateMethods.v2_1, DelegateMethods.v3_1, and Entity.width.
Referenced by Update().