Terraria: Projectile.AI_151_SuperStar
AI_151_SuperStar()
void Projectile.AI_151_SuperStar () inline private
     {
         alpha -= 10;
         int num = 100;
         if (alpha < num)
         {
             alpha = num;
         }
         if (soundDelay == 0)
         {
             soundDelay = 20 + Main.rand.Next(40);
             SoundEngine.PlaySound(SoundID.Item9, position);
         }
         rotation += (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.005f * (float)direction;
         Vector2 vector = new Vector2(Main.screenWidth, Main.screenHeight);
         if (base.Hitbox.Intersects(Utils.CenteredRectangle(Main.screenPosition + vector / 2f, vector + new Vector2(400f))) && Main.rand.Next(6) == 0)
         {
             Gore.NewGore(position, velocity * 0.2f, Utils.SelectRandom<int>(Main.rand, 16, 17, 17, 17));
         }
         for (int i = 0; i < 2; i++)
         {
             if (Main.rand.Next(8) == 0)
             {
                 int num2 = 228;
                 Dust dust = Dust.NewDustDirect(position, width, height, num2, 0f, 0f, 127);
                 dust.velocity *= 0.25f;
                 dust.scale = 1.3f;
                 dust.noGravity = true;
                 dust.velocity += velocity.RotatedBy((float)Math.PI / 8f * (1f - (float)(2 * i))) * 0.2f;
             }
         }
     }
References alpha, Utils.CenteredRectangle(), Entity.direction, Entity.height, SoundID.Item9, Dust.NewDustDirect(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, SoundEngine.PlaySound(), Entity.position, Main.rand, rotation, Dust.scale, Main.screenHeight, Main.screenPosition, Main.screenWidth, soundDelay, Dust.velocity, Entity.velocity, and Entity.width.