Terraria: Projectile.AI_015_Flails_Old
AI_015_Flails_Old()
void Projectile.AI_015_Flails_Old () inline private
     {
         AI_015_Flails_Dust(doFastThrowDust: false);
         bool flag = Main.player[owner].dead;
         if (!flag)
         {
             flag = (Main.player[owner].Center - base.Center).Length() > 2000f;
         }
         if (flag)
         {
             Kill();
             return;
         }
         Main.player[owner].SetDummyItemTime(10);
         if (position.X + (float)(width / 2) > Main.player[owner].position.X + (float)(Main.player[owner].width / 2))
         {
             Main.player[owner].ChangeDir(1);
             direction = 1;
         }
         else
         {
             Main.player[owner].ChangeDir(-1);
             direction = -1;
         }
         Vector2 mountedCenter = Main.player[owner].MountedCenter;
         Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num = mountedCenter.X - vector.X;
         float num2 = mountedCenter.Y - vector.Y;
         float num3 = (float)Math.Sqrt(num * num + num2 * num2);
         if (ai[0] == 0f)
         {
             float num4 = 160f;
             if (type == 63)
             {
                 num4 *= 1.5f;
             }
             if (type == 247)
             {
                 num4 *= 1.5f;
             }
             if (type == 757)
             {
                 num4 *= 1.5f;
             }
             tileCollide = true;
             if (num3 > num4)
             {
                 ai[0] = 1f;
                 netUpdate = true;
             }
             else if (!Main.player[owner].channel)
             {
                 if (velocity.Y < 0f)
                 {
                     velocity.Y *= 0.9f;
                 }
                 velocity.Y += 1f;
                 velocity.X *= 0.9f;
             }
         }
         else if (ai[0] == 1f)
         {
             float meleeSpeed = Main.player[owner].meleeSpeed;
             float num5 = 14f / meleeSpeed;
             float num6 = 0.9f / meleeSpeed;
             float num7 = 300f / meleeSpeed;
             int num8 = 60;
             if (type == 63)
             {
                 num7 *= 1.5f;
                 num5 *= 1.5f;
                 num6 *= 1.5f;
             }
             if (type == 247)
             {
                 num7 *= 1.5f;
                 num5 = 15.9f;
                 num6 *= 2f;
                 num8 = 100;
             }
             if (type == 757)
             {
                 num7 *= 1.5f;
                 num5 = 15.9f;
                 num6 *= 2f;
                 num8 = 100;
             }
             Math.Abs(num);
             Math.Abs(num2);
             if (ai[1] == 1f)
             {
                 tileCollide = false;
             }
             if (!Main.player[owner].channel || num3 > num7 || !tileCollide)
             {
                 ai[1] = 1f;
                 if (tileCollide)
                 {
                     netUpdate = true;
                 }
                 tileCollide = false;
                 if (num3 < 20f)
                 {
                     Kill();
                 }
             }
             if (!tileCollide)
             {
                 num6 *= 2f;
             }
             if (num3 > (float)num8 || !tileCollide)
             {
                 num3 = num5 / num3;
                 num *= num3;
                 num2 *= num3;
                 new Vector2(velocity.X, velocity.Y);
                 float num9 = num - velocity.X;
                 float num10 = num2 - velocity.Y;
                 float num11 = (float)Math.Sqrt(num9 * num9 + num10 * num10);
                 num11 = num6 / num11;
                 num9 *= num11;
                 num10 *= num11;
                 velocity.X *= 0.98f;
                 velocity.Y *= 0.98f;
                 velocity.X += num9;
                 velocity.Y += num10;
             }
             else
             {
                 if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) < 6f)
                 {
                     velocity.X *= 0.96f;
                     velocity.Y += 0.2f;
                 }
                 if (Main.player[owner].velocity.X == 0f)
                 {
                     velocity.X *= 0.96f;
                 }
             }
         }
         if (type == 247)
         {
             if (velocity.X < 0f)
             {
                 rotation -= (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.01f;
             }
             else
             {
                 rotation += (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.01f;
             }
             float num12 = position.X;
             float num13 = position.Y;
             float num14 = 600f;
             bool flag2 = false;
             if (owner == Main.myPlayer)
             {
                 localAI[1] += 1f;
                 if (localAI[1] > 20f)
                 {
                     localAI[1] = 20f;
                     for (int i = 0; i < 200; i++)
                     {
                         if (Main.npc[i].CanBeChasedBy(this))
{
                             float num15 = Main.npc[i].position.X + (float)(Main.npc[i].width / 2);
                             float num16 = Main.npc[i].position.Y + (float)(Main.npc[i].height / 2);
                             float num17 = Math.Abs(position.X + (float)(width / 2) - num15) + Math.Abs(position.Y + (float)(height / 2) - num16);
                             if (num17 < num14 && Collision.CanHit(position, width, height, Main.npc[i].position, Main.npc[i].width, Main.npc[i].height))
{
                                 num14 = num17;
                                 num12 = num15;
                                 num13 = num16;
                                 flag2 = true;
                             }
                         }
                     }
                 }
             }
             if (flag2)
             {
                 localAI[1] = 0f;
                 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 num = num12 - vector.X;
                 num2 = num13 - vector.Y;
                 num3 = (float)Math.Sqrt(num * num + num2 * num2);
                 num3 = 14f / num3;
                 num *= num3;
                 num2 *= num3;
                 NewProjectile(GetProjectileSource_FromThis(), vector.X, vector.Y, num, num2, 248, (int)((double)damage / 1.5), knockBack / 2f, Main.myPlayer);
             }
         }
         else
         {
             rotation = (float)Math.Atan2(num2, num) - velocity.X * 0.1f;
         }
     }
References NPC.CanBeChasedBy(), Collision.CanHit(), Entity.Center, Player.ChangeDir(), Player.channel, Player.dead, Entity.height, Player.meleeSpeed, Player.MountedCenter, Main.myPlayer, Main.npc, Main.player, Entity.position, Player.SetDummyItemTime(), Entity.velocity, and Entity.width.