Terraria: Projectile.AI_007_GrapplingHooks
AI_007_GrapplingHooks()
void Projectile.AI_007_GrapplingHooks () inline private
     {
         if (Main.player[owner].dead || Main.player[owner].stoned || Main.player[owner].webbed || Main.player[owner].frozen)
         {
             Kill();
             return;
         }
         Vector2 mountedCenter = Main.player[owner].MountedCenter;
         Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num = mountedCenter.X - vector.X;
         float num2 = mountedCenter.Y - vector.Y;
         float num3 = (float)Math.Sqrt(num * num + num2 * num2);
         rotation = (float)Math.Atan2(num2, num) - 1.57f;
         if (ai[0] == 2f && type == 865)
         {
             float num4 = (float)Math.PI / 2f;
             int num5 = (int)Math.Round(rotation / num4);
             rotation = (float)num5 * num4;
         }
         if (Main.myPlayer == owner)
         {
             int num6 = (int)(base.Center.X / 16f);
             int num7 = (int)(base.Center.Y / 16f);
             if (num6 > 0 && num7 > 0 && num6 < Main.maxTilesX && num7 < Main.maxTilesY && Main.tile[num6, num7].nactive() && TileID.Sets.CrackedBricks[Main.tile[num6, num7].type] && Main.rand.Next(16) == 0)
             {
                 WorldGen.KillTile(num6, num7);
                 if (Main.netMode != 0)
                 {
                     NetMessage.SendData(17, -1, -1, null, 20, num6, num7);
                 }
             }
         }
         if (num3 > 2500f)
         {
             Kill();
         }
         if (type == 256)
         {
             rotation = (float)Math.Atan2(num2, num) + 3.9250002f;
         }
         if (type == 446)
         {
             Lighting.AddLight(mountedCenter, 0f, 0.4f, 0.3f);
             localAI[0] += 1f;
             if (localAI[0] >= 28f)
             {
                 localAI[0] = 0f;
             }
             DelegateMethods.v3_1 = new Vector3(0f, 0.4f, 0.3f);
             Utils.PlotTileLine(base.Center, mountedCenter, 8f, DelegateMethods.CastLightOpen);
         }
         if (type == 652 && ++frameCounter >= 7)
         {
             frameCounter = 0;
             if (++frame >= Main.projFrames[type])
             {
                 frame = 0;
             }
         }
         if (type >= 646 && type <= 649)
         {
             Vector3 vector2 = Vector3.Zero;
             switch (type)
             {
             case 646:
                 vector2 = new Vector3(0.7f, 0.5f, 0.1f);
                 break;
             case 647:
                 vector2 = new Vector3(0f, 0.6f, 0.7f);
                 break;
             case 648:
                 vector2 = new Vector3(0.6f, 0.2f, 0.6f);
                 break;
             case 649:
                 vector2 = new Vector3(0.6f, 0.6f, 0.9f);
                 break;
             }
             Lighting.AddLight(mountedCenter, vector2);
             Lighting.AddLight(base.Center, vector2);
             DelegateMethods.v3_1 = vector2;
             Utils.PlotTileLine(base.Center, mountedCenter, 8f, DelegateMethods.CastLightOpen);
         }
         if (ai[0] == 0f)
         {
             if ((num3 > 300f && type == 13) || (num3 > 400f && type == 32) || (num3 > 440f && type == 73) || (num3 > 440f && type == 74) || (num3 > 375f && type == 165) || (num3 > 350f && type == 256) || (num3 > 500f && type == 315) || (num3 > 550f && type == 322) || (num3 > 400f && type == 331) || (num3 > 550f && type == 332) || (num3 > 400f && type == 372) || (num3 > 300f && type == 396) || (num3 > 550f && type >= 646 && type <= 649) || (num3 > 600f && type == 652) || (num3 > 300f && type == 865) || (num3 > 500f && type == 935) || (num3 > 480f && type >= 486 && type <= 489) || (num3 > 500f && type == 446))
             {
                 ai[0] = 1f;
             }
             else if (type >= 230 && type <= 235)
             {
                 int num8 = 300 + (type - 230) * 30;
                 if (num3 > (float)num8)
                 {
                     ai[0] = 1f;
                 }
             }
             else if (type == 753)
             {
                 int num9 = 420;
                 if (num3 > (float)num9)
                 {
                     ai[0] = 1f;
                 }
             }
             Vector2 vector3 = base.Center - new Vector2(5f);
             Vector2 vector4 = base.Center + new Vector2(5f);
             Point point = (vector3 - new Vector2(16f)).ToTileCoordinates();
             Point point2 = (vector4 + new Vector2(32f)).ToTileCoordinates();
             int num10 = point.X;
             int num11 = point2.X;
             int num12 = point.Y;
             int num13 = point2.Y;
             if (num10 < 0)
             {
                 num10 = 0;
             }
             if (num11 > Main.maxTilesX)
             {
                 num11 = Main.maxTilesX;
             }
             if (num12 < 0)
             {
                 num12 = 0;
             }
             if (num13 > Main.maxTilesY)
             {
                 num13 = Main.maxTilesY;
             }
             Player player = Main.player[owner];
             List<Point> list = new List<Point>();
             for (int i = 0; i < player.grapCount; i++)
             {
                 Projectile projectile = Main.projectile[player.grappling[i]];
                 if (projectile.aiStyle != 7 || projectile.ai[0] != 2f)
                 {
                     continue;
                 }
                 Point pt = projectile.Center.ToTileCoordinates();
                 Tile tileSafely = Framing.GetTileSafely(pt);
                 if (tileSafely.type != 314 && !TileID.Sets.Platforms[tileSafely.type])
                 {
                     continue;
                 }
                 for (int j = -2; j <= 2; j++)
                 {
                     for (int k = -2; k <= 2; k++)
                     {
                         Point point3 = new Point(pt.X + j, pt.Y + k);
                         Tile tileSafely2 = Framing.GetTileSafely(point3);
                         if (tileSafely2.type == 314 || TileID.Sets.Platforms[tileSafely2.type])
{
                             list.Add(point3);
                         }
                     }
                 }
             }
             Vector2 vector5 = default(Vector2);
             for (int l = num10; l < num11; l++)
             {
                 for (int m = num12; m < num13; m++)
                 {
                     if (Main.tile[l, m] == null)
                     {
                         Main.tile[l, m] = new Tile();
                     }
                     vector5.X = l * 16;
                     vector5.Y = m * 16;
                     if (!(vector3.X + 10f > vector5.X) || !(vector3.X < vector5.X + 16f) || !(vector3.Y + 10f > vector5.Y) || !(vector3.Y < vector5.Y + 16f))
                     {
                         continue;
                     }
                     Tile tile = Main.tile[l, m];
                     if (!tile.nactive() || !AI_007_GrapplingHooks_CanTileBeLatchedOnTo(tile) || list.Contains(new Point(l, m)) || (type == 403 && tile.type != 314) || Main.player[owner].IsBlacklistedForGrappling(new Point(l, m)))
                     {
                         continue;
                     }
                     if (Main.player[owner].grapCount < 10)
                     {
                         Main.player[owner].grappling[Main.player[owner].grapCount] = whoAmI;
                         Main.player[owner].grapCount++;
                     }
                     if (Main.myPlayer != owner)
                     {
                         continue;
                     }
                     int num14 = 0;
                     int num15 = -1;
                     int num16 = 100000;
                     if (type == 73 || type == 74)
                     {
                         for (int n = 0; n < 1000; n++)
{
                             if (n != whoAmI && Main.projectile[n].active && Main.projectile[n].owner == owner && Main.projectile[n].aiStyle == 7 && Main.projectile[n].ai[0] == 2f)
{
                                 Main.projectile[n].Kill();
                             }
                         }
                     }
                     else
                     {
                         int num17 = 3;
                         if (type == 165)
{
                             num17 = 8;
                         }
                         if (type == 256)
{
                             num17 = 2;
                         }
                         if (type == 372)
{
                             num17 = 2;
                         }
                         if (type == 652)
{
                             num17 = 1;
                         }
                         if (type >= 646 && type <= 649)
{
                             num17 = 4;
                         }
                         for (int num18 = 0; num18 < 1000; num18++)
{
                             if (Main.projectile[num18].active && Main.projectile[num18].owner == owner && Main.projectile[num18].aiStyle == 7)
{
                                 if (Main.projectile[num18].timeLeft < num16)
{
                                     num15 = num18;
                                     num16 = Main.projectile[num18].timeLeft;
                                 }
                                 num14++;
                             }
                         }
                         if (num14 > num17)
{
                             Main.projectile[num15].Kill();
                         }
                     }
                     WorldGen.KillTile(l, m, fail: true, effectOnly: true);
                     SoundEngine.PlaySound(0, l * 16, m * 16);
                     velocity.X = 0f;
                     velocity.Y = 0f;
                     ai[0] = 2f;
                     position.X = l * 16 + 8 - width / 2;
                     position.Y = m * 16 + 8 - height / 2;
                     Rectangle? tileVisualHitbox = WorldGen.GetTileVisualHitbox(l, m);
                     if (tileVisualHitbox.HasValue)
                     {
                         base.Center = tileVisualHitbox.Value.Center.ToVector2();
                     }
                     damage = 0;
                     netUpdate = true;
                     if (Main.myPlayer == owner)
                     {
                         if (type == 935)
{
                             Main.player[owner].DoQueenSlimeHookTeleport(base.Center);
                         }
                         NetMessage.SendData(13, -1, -1, null, owner);
                     }
                     break;
                 }
                 if (ai[0] == 2f)
                 {
                     break;
                 }
             }
         }
         else if (ai[0] == 1f)
         {
             float num19 = 11f;
             if (type == 32)
             {
                 num19 = 15f;
             }
             if (type == 73 || type == 74)
             {
                 num19 = 17f;
             }
             if (type == 315)
             {
                 num19 = 20f;
             }
             if (type == 322)
             {
                 num19 = 22f;
             }
             if (type >= 230 && type <= 235)
             {
                 num19 = 11f + (float)(type - 230) * 0.75f;
             }
             if (type == 753)
             {
                 num19 = 15f;
             }
             if (type == 446)
             {
                 num19 = 20f;
             }
             if (type >= 486 && type <= 489)
             {
                 num19 = 18f;
             }
             if (type >= 646 && type <= 649)
             {
                 num19 = 24f;
             }
             if (type == 652)
             {
                 num19 = 24f;
             }
             if (type == 332)
             {
                 num19 = 17f;
             }
             if (num3 < 24f)
             {
                 Kill();
             }
             num3 = num19 / num3;
             num *= num3;
             num2 *= num3;
             velocity.X = num;
             velocity.Y = num2;
         }
         else if (ai[0] == 2f)
         {
             Point point4 = base.Center.ToTileCoordinates();
             if (Main.tile[point4.X, point4.Y] == null)
             {
                 Main.tile[point4.X, point4.Y] = new Tile();
             }
             bool flag = true;
             if (Main.tile[point4.X, point4.Y].nactive() && AI_007_GrapplingHooks_CanTileBeLatchedOnTo(Main.tile[point4.X, point4.Y]))
             {
                 flag = false;
             }
             if (flag)
             {
                 ai[0] = 1f;
             }
             else if (Main.player[owner].grapCount < 10)
             {
                 Main.player[owner].grappling[Main.player[owner].grapCount] = whoAmI;
                 Main.player[owner].grapCount++;
             }
         }
     }
References Entity.active, Lighting.AddLight(), ai, aiStyle, DelegateMethods.CastLightOpen(), Entity.Center, TileID.Sets.CrackedBricks, Player.dead, Player.DoQueenSlimeHookTeleport(), Player.frozen, Framing.GetTileSafely(), WorldGen.GetTileVisualHitbox(), Player.grapCount, Player.grappling, Player.IsBlacklistedForGrappling(), Kill(), WorldGen.KillTile(), Main.maxTilesX, Main.maxTilesY, Player.MountedCenter, Main.myPlayer, Tile.nactive(), Main.netMode, UnifiedRandom.Next(), owner, TileID.Sets.Platforms, Main.player, SoundEngine.PlaySound(), Utils.PlotTileLine(), Main.projectile, Main.projFrames, Main.rand, NetMessage.SendData(), Player.stoned, Main.tile, timeLeft, Tile.type, DelegateMethods.v3_1, and Player.webbed.