Terraria: Projectile.AI_015_Flails_Dust
AI_015_Flails_Dust()
void Projectile.AI_015_Flails_Dust (bool doFastThrowDust) inline private
     {
         if (type == 25)
         {
             int maxValue = 15;
             if (doFastThrowDust)
             {
                 maxValue = 1;
             }
             if (Main.rand.Next(maxValue) == 0)
             {
                 Dust.NewDust(position, width, height, 14, 0f, 0f, 150, default(Color), 1.3f);
             }
         }
         else if (type == 757)
         {
             int num = 4;
             if (velocity.Length() < 8f)
             {
                 num = 10;
             }
             if (doFastThrowDust)
             {
                 num /= 2;
             }
             for (int i = 0; i < 2; i++)
             {
                 if (Main.rand.Next(num) == 0)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 5, 0f, 0f, 0, default(Color), 0.8f);
                     dust.velocity += velocity / 4f;
                     dust.fadeIn = 1.3f;
                 }
             }
             num = 40;
             if (doFastThrowDust)
             {
                 num /= 2;
             }
             for (float num2 = 0f; num2 < 1f; num2 += 0.1f)
             {
                 if (Main.rand.Next(num) == 0)
                 {
                     Dust.NewDustDirect(Vector2.Lerp(Main.player[owner].Center, base.Center, Main.rand.NextFloat()) + new Vector2(-8f), 16, 16, 5, 0f, 0f, 0, default(Color), 1.3f).velocity += velocity / 4f;
                 }
             }
         }
         else if (type == 26)
         {
             int num3 = Dust.NewDust(position, width, height, 172, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 1.5f);
             Main.dust[num3].noGravity = true;
             Main.dust[num3].velocity.X /= 2f;
             Main.dust[num3].velocity.Y /= 2f;
         }
         else if (type == 948 && !wet)
         {
             int num4 = Dust.NewDust(position, width, height, 6, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 1.2f);
             Main.dust[num4].noGravity = true;
             Main.dust[num4].velocity.X *= 4f;
             Main.dust[num4].velocity.Y *= 4f;
             Main.dust[num4].velocity = (Main.dust[num4].velocity + velocity) / 2f;
         }
         else if (type == 35)
         {
             int num5 = Dust.NewDust(position, width, height, 6, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3f);
             Main.dust[num5].noGravity = true;
             Main.dust[num5].velocity.X *= 2f;
             Main.dust[num5].velocity.Y *= 2f;
         }
         else if (type == 154)
         {
             int num6 = Dust.NewDust(position, width, height, 115, velocity.X * 0.4f, velocity.Y * 0.4f, 140, default(Color), 1.5f);
             Main.dust[num6].noGravity = true;
             Main.dust[num6].velocity *= 0.25f;
         }
     }
References Entity.Center, Color, Main.dust, Dust.fadeIn, Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.player, Main.rand, and Dust.velocity.