Terraria: Projectile.AI_010
AI_010()
void Projectile.AI_010 () inline private
     {
         if (type == 31 && ai[0] != 2f)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 32, 0f, velocity.Y / 2f);
                 Main.dust[num].velocity.X *= 0.4f;
             }
         }
         else if (type == 39)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num2 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 38, 0f, velocity.Y / 2f);
                 Main.dust[num2].velocity.X *= 0.4f;
             }
         }
         else if (type >= 411 && type <= 414)
         {
             if (Main.rand.Next(3) == 0)
             {
                 int num3 = 9;
                 if (type == 412 || type == 414)
                 {
                     num3 = 11;
                 }
                 if (type == 413)
                 {
                     num3 = 19;
                 }
                 int num4 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num3, 0f, velocity.Y / 2f);
                 Main.dust[num4].noGravity = true;
                 Main.dust[num4].velocity -= velocity * 0.5f;
             }
         }
         else if (type == 40)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num5 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 36, 0f, velocity.Y / 2f);
                 Main.dust[num5].velocity *= 0.4f;
             }
         }
         else if (type == 42 || type == 31)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num6 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 32);
                 Main.dust[num6].velocity.X *= 0.4f;
             }
         }
         else if (type == 56 || type == 65)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num7 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14);
                 Main.dust[num7].velocity.X *= 0.4f;
             }
         }
         else if (type == 67 || type == 68)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num8 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 51);
                 Main.dust[num8].velocity.X *= 0.4f;
             }
         }
         else if (type == 71)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num9 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 53);
                 Main.dust[num9].velocity.X *= 0.4f;
             }
         }
         else if (type == 179)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num10 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 149);
                 Main.dust[num10].velocity.X *= 0.4f;
             }
         }
         else if (type == 241 || type == 354)
         {
             if (Main.rand.Next(2) == 0)
             {
                 int num11 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 36);
                 Main.dust[num11].velocity.X *= 0.4f;
             }
         }
         else if (type >= 736 && type <= 738)
         {
             if (Main.rand.Next(40) == 0)
             {
                 int num12 = Dust.NewDust(position, width, height, type - 736 + 275);
                 if (num12 >= 0)
                 {
                     Main.dust[num12].velocity = Main.dust[num12].velocity * 0.5f + velocity * 0.5f;
                 }
             }
         }
         else if (type != 109 && Main.rand.Next(20) == 0)
         {
             Dust.NewDust(new Vector2(position.X, position.Y), width, height, 0);
         }
         if (type >= 736 && type <= 738)
         {
             if (localAI[0] == 0f)
             {
                 frame = Main.rand.Next(3);
                 scale = 1f - (float)Main.rand.Next(30) * 0.01f;
             }
             localAI[0] += 1f;
         }
         tileCollide = true;
         localAI[1] = 0f;
         if (Main.myPlayer == owner && ai[0] == 0f)
         {
             tileCollide = false;
             if (Main.player[owner].channel && (type < 736 || type > 738) && type != 40)
             {
                 localAI[1] = -1f;
                 float num13 = 12f;
                 Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num14 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                 float num15 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
                 if (Main.player[owner].gravDir == -1f)
                 {
                     num15 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector.Y;
                 }
                 float num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
                 num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
                 if (num16 > num13)
                 {
                     num16 = num13 / num16;
                     num14 *= num16;
                     num15 *= num16;
                     if (num14 != velocity.X || num15 != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity.X = num14;
                     velocity.Y = num15;
                 }
                 else
                 {
                     if (num14 != velocity.X || num15 != velocity.Y)
                     {
                         netUpdate = true;
                     }
                     velocity.X = num14;
                     velocity.Y = num15;
                 }
             }
             else
             {
                 ai[0] = 1f;
                 netUpdate = true;
             }
         }
         if (ai[0] == 1f && type != 109)
         {
             if (type == 42 || type == 65 || type == 68 || type == 354)
             {
                 ai[1] += 1f;
                 if (ai[1] >= 60f)
                 {
                     ai[1] = 60f;
                     velocity.Y += 0.2f;
                 }
             }
             else
             {
                 velocity.Y += 0.41f;
             }
         }
         else if (ai[0] == 2f && type != 109)
         {
             velocity.Y += 0.2f;
             if ((double)velocity.X < -0.04)
             {
                 velocity.X += 0.04f;
             }
             else if ((double)velocity.X > 0.04)
             {
                 velocity.X -= 0.04f;
             }
             else
             {
                 velocity.X = 0f;
             }
         }
         if (owner == Main.myPlayer && tileCollide)
         {
             for (int i = (int)(position.X / 16f); i <= (int)((position.X + (float)width) / 16f); i++)
             {
                 for (int j = (int)(position.Y / 16f); j <= (int)((position.Y + (float)height) / 16f); j++)
                 {
                     if (!WorldGen.InWorld(i, j))
                     {
                         continue;
                     }
                     Tile tile = Main.tile[i, j];
                     if (tile == null || !tile.active())
                     {
                         continue;
                     }
                     if ((tile.type >= 185 && tile.type <= 187) || tile.type == 165 || tile.type == 12 || tile.type == 665 || tile.type == 639 || tile.type == 105 || tile.type == 178)
                     {
                         WorldGen.KillTile(i, j);
                     }
                     else if (tile.topSlope() && !TileID.Sets.Platforms[tile.type])
                     {
                         WorldGen.SlopeTile(i, j);
                         if (Main.netMode != 0)
{
                             NetMessage.SendData(17, -1, -1, null, 14, i, j);
                         }
                         position.Y -= 16f;
                     }
                 }
             }
         }
         if (type >= 736 && type <= 738)
         {
             if (frame == 0)
             {
                 rotation -= 0.1f;
             }
             else if (frame == 1)
             {
                 rotation += 0.1f;
             }
             else
             {
                 rotation += 0.15f;
             }
             if (velocity.Y > 10f)
             {
                 velocity.Y = 10f;
             }
         }
         else
         {
             rotation += 0.1f;
             if (velocity.Y > 10f)
             {
                 velocity.Y = 10f;
             }
         }
     }
References Tile.active(), Player.channel, Main.dust, Player.gravDir, WorldGen.InWorld(), WorldGen.KillTile(), Main.mouseX, Main.mouseY, Main.myPlayer, Main.netMode, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, TileID.Sets.Platforms, Main.player, Main.rand, Main.screenHeight, Main.screenPosition, NetMessage.SendData(), WorldGen.SlopeTile(), Main.tile, Tile.topSlope(), Tile.type, and Dust.velocity.