Terraria: Projectile.AI_067_TigerSpecialAttack
AI_067_TigerSpecialAttack()
bool Projectile.AI_067_TigerSpecialAttack () inline private
     {
         List<NPC> list = new List<NPC>();
         Vector2 center = Main.player[owner].Center;
         Rectangle value = Utils.CenteredRectangle(center, new Vector2(1600f, 800f));
         int num = Main.player[owner].ownedProjectileCounts[831] + 1;
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = Main.npc[i];
             if (nPC.CanBeChasedBy(this) && nPC.Hitbox.Intersects(value))
             {
                 list.Add(nPC);
             }
         }
         if (list.Count == 0)
         {
             return false;
         }
         NPC nPC2 = list[0];
         for (int j = 1; j < list.Count; j++)
         {
             if (Vector2.Distance(nPC2.Center, center) > Vector2.Distance(list[j].Center, center))
             {
                 nPC2 = list[j];
             }
         }
         list.Remove(nPC2);
         NPC nPC3 = null;
         if (list.Count > 0)
         {
             nPC3 = list[0];
             for (int k = 1; k < list.Count; k++)
             {
                 if (Distance(nPC3.Center) > Distance(list[k].Center))
                 {
                     nPC3 = list[k];
                 }
             }
             list.Remove(nPC3);
         }
         List<Vector2> list2 = new List<Vector2>();
         if (nPC3 != null)
         {
             list2.Add(nPC3.Center);
         }
         int num2 = 0;
         while (list.Count > 0 && list2.Count < num - 1)
         {
             int index = Main.rand.Next(list.Count);
             Vector2 vector = list[index].velocity * 4f * (num2 + 1);
             list2.Add(list[index].Center + vector);
             list.RemoveAt(index);
             num2++;
         }
         if (nPC2 != null)
         {
             list2.Add(nPC2.Center);
         }
         if (list2.Count > 0 && Collision.SolidCollision(list2[list2.Count - 1] - base.Size / 2f, width, height))
         {
             list2.Add(center);
         }
         Vector2 vector2 = base.Center;
         float num3 = Math.Min(20, 30 / list2.Count);
         float num4 = 0f;
         for (int l = 0; l < list2.Count; l++)
         {
             float num5 = 20f;
             Vector2 vector3 = list2[l];
             vector3.X += ((vector2.X < vector3.X) ? num5 : (0f - num5));
             Vector2 vector4 = vector3 - vector2;
             int num6 = (int)Math.Min(num3, 4.0 + Math.Ceiling(vector4.Length() / 50f));
             if (num6 < 5)
             {
                 num6 = 5;
             }
             NewProjectile(GetProjectileSource_FromThis(), vector2, vector4, 818, damage, 0f, owner, (0f - num4) * 4f, num6 * 4);
             vector2 = vector3;
             num4 += (float)num6;
         }
         base.Center = vector2;
         ai[0] = 4f;
         ai[1] = num4;
         netUpdate = true;
         return true;
     }
References NPC.CanBeChasedBy(), Entity.Center, Utils.CenteredRectangle(), Entity.Hitbox, UnifiedRandom.Next(), Main.npc, Player.ownedProjectileCounts, Main.player, Main.rand, and Collision.SolidCollision().