Terraria: Projectile.MakeBoulderOfEarthExplosion
MakeBoulderOfEarthExplosion()
void Projectile.MakeBoulderOfEarthExplosion () inline private
     {
         localAI[0] = 40f;
         float mAX_SPREAD = 20f;
         int fluff = 10;
         int distFluff = 50;
         int layerStart = 1;
         int num = 6;
         if (velocity.Length() < 8f || Math.Abs(velocity.Y) < 4f)
         {
             mAX_SPREAD = 15f;
             fluff = 7;
             distFluff = 30;
             num = 4;
         }
         if (velocity.Length() < 4f || Math.Abs(velocity.Y) < 2f)
         {
             mAX_SPREAD = 15f;
             fluff = 7;
             distFluff = 30;
             num = 2;
             layerStart = 0;
         }
         int layerEnd = num;
         int num2 = num - 2;
         if (num2 < 1)
         {
             num2 = 1;
         }
         CreateGroundExplosion(mAX_SPREAD, fluff, distFluff, layerStart, layerEnd, num2);
         for (int i = 0; i < 10; i++)
         {
             Dust dust = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(width / 2, height / 2), 228, Main.rand.NextVector2Circular(3f, 3f));
             dust.scale = 0.6f;
             if (i < 5)
             {
                 dust.noGravity = true;
                 dust.scale = 1.8f;
             }
         }
     }
References CreateGroundExplosion(), Entity.height, localAI, Dust.NewDustPerfect(), Dust.noGravity, Main.rand, Dust.scale, Entity.velocity, and Entity.width.
Referenced by HandleMovement().