Terraria: Projectile.AI_158_BabyBird
AI_158_BabyBird()
void Projectile.AI_158_BabyBird () inline private
     {
         Player player = Main.player[owner];
         if (type == 759)
         {
             if (player.dead)
             {
                 player.babyBird = false;
             }
             if (player.babyBird)
             {
                 timeLeft = 2;
             }
             if (++frameCounter >= 6)
             {
                 frameCounter = 0;
                 if (++frame >= Main.projFrames[type] - 1)
                 {
                     frame = 0;
                 }
             }
         }
         float num = 6f;
         float num2 = 8f;
         int num3 = 800;
         float num4 = 150f;
         int attackTarget = -1;
         Minion_FindTargetInRange(num3, ref attackTarget, skipIfCannotHitWithOwnBody: false);
         if (attackTarget != -1)
         {
             NPC nPC = Main.npc[attackTarget];
             if (player.Distance(nPC.Center) > (float)num3)
             {
                 attackTarget = -1;
             }
         }
         if (attackTarget != -1)
         {
             if (!Collision.SolidCollision(position, width, height))
             {
                 tileCollide = true;
             }
             NPC nPC2 = Main.npc[attackTarget];
             float num5 = Distance(nPC2.Center);
             Rectangle rectangle = new Rectangle((int)position.X, (int)position.Y, width, height);
             Rectangle value = new Rectangle((int)nPC2.position.X, (int)nPC2.position.Y, nPC2.width, nPC2.height);
             if (rectangle.Intersects(value))
             {
                 tileCollide = false;
                 if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) < num2)
                 {
                     velocity *= 1.1f;
                 }
                 if (velocity.Length() > num2)
                 {
                     velocity *= num2 / velocity.Length();
                 }
             }
             else if (num5 > num4)
             {
                 Vector2 vector = DirectionTo(nPC2.Center);
                 velocity = Vector2.Lerp(velocity, vector * num, 0.15f);
             }
             else
             {
                 tileCollide = false;
                 Vector2 vector2 = DirectionTo(nPC2.Center);
                 velocity += new Vector2(Math.Sign(vector2.X), Math.Sign(vector2.Y)) * 0.35f;
                 if (velocity.Length() > num2)
                 {
                     velocity *= num2 / velocity.Length();
                 }
             }
             float num6 = 0.025f;
             float num7 = width * 3;
             for (int i = 0; i < 1000; i++)
             {
                 if (i != whoAmI && Main.projectile[i].active && Main.projectile[i].owner == owner && Main.projectile[i].type == type && Math.Abs(position.X - Main.projectile[i].position.X) + Math.Abs(position.Y - Main.projectile[i].position.Y) < num7)
                 {
                     if (position.X < Main.projectile[i].position.X)
                     {
                         velocity.X -= num6;
                     }
                     else
                     {
                         velocity.X += num6;
                     }
                     if (position.Y < Main.projectile[i].position.Y)
                     {
                         velocity.Y -= num6;
                     }
                     else
                     {
                         velocity.Y += num6;
                     }
                 }
             }
             rotation = velocity.X * 0.1f;
             direction = ((velocity.X > 0f) ? 1 : (-1));
             spriteDirection = ((velocity.X > 0f) ? 1 : (-1));
             return;
         }
         tileCollide = false;
         List<int> ai158_blacklistedTargets = _ai158_blacklistedTargets;
         ai158_blacklistedTargets.Clear();
         AI_GetMyGroupIndexAndFillBlackList(ai158_blacklistedTargets, out var index, out var _);
         localAI[0] = index;
         Vector2 vector3 = AI_158_GetHomeLocation(player, index);
         float num8 = Distance(vector3);
         bool flag = player.gravDir > 0f && player.fullRotation == 0f && player.headRotation == 0f;
         if (num8 > 2000f)
         {
             base.Center = vector3;
             frame = Main.projFrames[type] - 1;
             frameCounter = 0;
             velocity = Vector2.Zero;
             direction = (spriteDirection = player.direction);
             rotation = 0f;
         }
         else if (num8 > 40f)
         {
             float num9 = num + num8 * 0.006f;
             Vector2 vector4 = DirectionTo(vector3);
             vector4 *= MathHelper.Lerp(1f, 5f, Utils.GetLerpValue(40f, 800f, num8, clamped: true));
             velocity = Vector2.Lerp(velocity, vector4 * num9, 0.025f);
             if (velocity.Length() > num9)
             {
                 velocity *= num9 / velocity.Length();
             }
             float num10 = 0.05f;
             float num11 = width;
             for (int j = 0; j < 1000; j++)
             {
                 if (j != whoAmI && Main.projectile[j].active && Main.projectile[j].owner == owner && Main.projectile[j].type == type && Math.Abs(position.X - Main.projectile[j].position.X) + Math.Abs(position.Y - Main.projectile[j].position.Y) < num11)
                 {
                     if (position.X < Main.projectile[j].position.X)
                     {
                         velocity.X -= num10;
                     }
                     else
                     {
                         velocity.X += num10;
                     }
                     if (position.Y < Main.projectile[j].position.Y)
                     {
                         velocity.Y -= num10;
                     }
                     else
                     {
                         velocity.Y += num10;
                     }
                 }
             }
             rotation = velocity.X * 0.04f;
             direction = ((velocity.X > 0f) ? 1 : (-1));
             spriteDirection = ((velocity.X > 0f) ? 1 : (-1));
         }
         else if (num8 > 8f + player.velocity.Length())
         {
             Vector2 vector5 = DirectionTo(vector3);
             velocity += new Vector2(Math.Sign(vector5.X), Math.Sign(vector5.Y)) * 0.05f;
             if (velocity.Length() > num)
             {
                 velocity *= num / velocity.Length();
             }
             rotation = velocity.X * 0.1f;
             direction = ((velocity.X > 0f) ? 1 : (-1));
             spriteDirection = ((velocity.X > 0f) ? 1 : (-1));
         }
         else if (flag)
         {
             base.Center = vector3;
             frame = Main.projFrames[type] - 1;
             frameCounter = 0;
             velocity = Vector2.Zero;
             direction = (spriteDirection = player.direction);
             rotation = 0f;
         }
     }
References Entity.active, Player.babyBird, Entity.Center, Player.dead, Entity.direction, Entity.Distance(), Player.fullRotation, Utils.GetLerpValue(), Player.gravDir, Player.headRotation, Entity.height, Main.npc, owner, Main.player, Entity.position, Main.projectile, Main.projFrames, Collision.SolidCollision(), type, Entity.velocity, and Entity.width.