Terraria: Projectile.AI_186_PrincessWeapon
AI_186_PrincessWeapon()
void Projectile.AI_186_PrincessWeapon () inline private
     {
         float num = 60f;
         ai[0] += 1f;
         if (ai[0] >= num)
         {
             Kill();
             return;
         }
         Opacity = Utils.Remap(ai[0], 0f, num, 1f, 0f);
         float num2 = ai[0] / num;
         float num3 = 1f - (1f - num2) * (1f - num2);
         float num4 = 1f - (1f - num3) * (1f - num3);
         float num5 = Utils.Remap(ai[0], num - 15f, num, 0f, 1f);
         float num6 = num5 * num5;
         float num7 = 1f - num6;
         scale = (0.4f + 0.6f * num4) * num7;
         float num8 = Utils.Remap(ai[0], 20f, num, 0f, 1f);
         float num9 = 1f - (1f - num8) * (1f - num8);
         float num10 = 1f - (1f - num9) * (1f - num9);
         localAI[0] = (0.4f + 0.6f * num10) * num7;
         int num11 = width / 2;
         Color newColor = Main.hslToRgb(0.92f, 1f, 0.5f) * Opacity;
         float num12 = 6f;
         float num13 = 2f;
         if (num2 < 0.9f)
         {
             for (int i = 0; i < 3; i++)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     Vector2 vector = Vector2.UnitX.RotatedBy(Main.rand.NextFloat() * ((float)Math.PI * 2f));
                     Vector2 vector2 = vector * ((float)num11 * scale);
                     Vector2 vector3 = base.Center + vector2;
                     Vector2 vector4 = vector.RotatedBy(0.7853981852531433);
                     vector3 += vector4 * num12;
                     int num14 = Dust.NewDust(vector3, 0, 0, 267, 0f, 0f, 0, newColor);
                     Main.dust[num14].position = vector3;
                     Main.dust[num14].noGravity = true;
                     Main.dust[num14].scale = 0.3f;
                     Main.dust[num14].fadeIn = Main.rand.NextFloat() * 1.2f * scale;
                     Main.dust[num14].velocity = vector4 * scale * (0f - num13);
                     Main.dust[num14].scale *= scale;
                     Main.dust[num14].velocity += velocity * 0.5f;
                     Main.dust[num14].position += Main.dust[num14].velocity * -5f;
                     if (num14 != 6000)
                     {
                         Dust dust = Dust.CloneDust(num14);
                         dust.scale /= 2f;
                         dust.fadeIn *= 0.85f;
                         dust.color = new Color(255, 255, 255, 255);
                     }
                 }
             }
         }
         if (num2 < 0.9f)
         {
             for (int j = 0; j < 3; j++)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     Vector2 vector5 = Vector2.UnitX.RotatedBy(Main.rand.NextFloat() * ((float)Math.PI * 2f));
                     Vector2 vector6 = vector5 * ((float)num11 * scale);
                     Vector2 vector7 = base.Center + vector6;
                     Vector2 vector8 = vector5.RotatedBy(0.7853981852531433);
                     vector7 += vector8 * (0f - num12);
                     int num15 = Dust.NewDust(vector7, 0, 0, 267, 0f, 0f, 0, newColor);
                     Main.dust[num15].position = vector7;
                     Main.dust[num15].noGravity = true;
                     Main.dust[num15].scale = 0.3f;
                     Main.dust[num15].fadeIn = Main.rand.NextFloat() * 1.2f * scale;
                     Main.dust[num15].velocity = vector8 * scale * num13;
                     Main.dust[num15].scale *= scale;
                     Main.dust[num15].velocity = velocity * 0.5f;
                     if (num15 != 6000)
                     {
                         Dust dust2 = Dust.CloneDust(num15);
                         dust2.scale /= 2f;
                         dust2.fadeIn *= 0.85f;
                         dust2.color = new Color(255, 255, 255, 255);
                     }
                 }
             }
         }
         if (num2 < 0.95f)
         {
             for (float num16 = 0f; num16 < 0.8f; num16 += 1f)
             {
                 if (Main.rand.Next(4) == 0)
                 {
                     Vector2 vector9 = Vector2.UnitX.RotatedBy(Main.rand.NextFloat() * ((float)Math.PI * 2f) + (float)Math.PI / 2f) * ((float)num11 * scale);
                     Vector2 positionInWorld = base.Center + vector9;
                     ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
                     {
                         PositionInWorld = positionInWorld,
                         MovementVector = velocity
                     }, owner);
                 }
             }
         }
         if (ai[0] == num - 10f)
         {
             for (float num17 = 0f; num17 < 1f; num17 += 0.25f)
             {
                 Vector2 vector10 = Vector2.UnitX.RotatedBy((float)Math.PI * 2f * num17);
                 _ = vector10 * ((float)num11 * scale);
                 Vector2 center = base.Center;
                 float num18 = 1f;
                 ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
                 {
                     PositionInWorld = center,
                     MovementVector = vector10 * num18
                 }, owner);
                 ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
                 {
                     PositionInWorld = center,
                     MovementVector = vector10 * num18 * 2f
                 }, owner);
             }
         }
     }
References Dust.CloneDust(), Color, Dust.color, Main.dust, Dust.fadeIn, Main.hslToRgb(), Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.position, Main.rand, Utils.Remap(), ParticleOrchestrator.RequestParticleSpawn(), Dust.scale, and Dust.velocity.