Terraria: Projectile.AI_149_GolfBall
AI_149_GolfBall()
void Projectile.AI_149_GolfBall () inline private
     {
         if (!npcProj && timeLeft < 10)
         {
             timeLeft = 10;
         }
         if (ai[1] == -1f)
         {
             Tile tileSafely = Framing.GetTileSafely(base.Bottom.ToTileCoordinates());
             if (!tileSafely.active() || tileSafely.type != 494)
             {
                 ai[1] = 0f;
                 netUpdate = true;
             }
             return;
         }
         BallStepResult ballStepResult = GolfHelper.StepGolfBall(this, ref localAI[0]);
         if (ballStepResult.State == BallState.Resting)
         {
             damage = 0;
             if (Main.netMode == 1 && owner == Main.myPlayer && localAI[1] != (float)ballStepResult.State)
             {
                 netUpdate = true;
             }
         }
         localAI[1] = (float)ballStepResult.State;
         rotation += localAI[0];
         if (velocity.Y != 0f && ballStepResult.State == BallState.Moving)
         {
             rotation += velocity.X * 0.1f + velocity.Y * 0.1f;
         }
         if (ballStepResult.State == BallState.Moving && owner == Main.myPlayer)
         {
             bool? flag = ProjectileID.Sets.ForcePlateDetection[135];
             if ((!flag.HasValue || flag.Value) && localAI[1] != 0f)
             {
                 Collision.SwitchTiles(position, width, height, oldPosition, 4);
             }
         }
         if (ballStepResult.State == BallState.Moving && Main.netMode == 2 && Main.player.IndexInRange(owner) && Main.player[owner].active)
         {
             RemoteClient.CheckSection(owner, position);
         }
     }
References Entity.active, Tile.active(), ai, RemoteClient.CheckSection(), damage, ProjectileID.Sets.ForcePlateDetection, Framing.GetTileSafely(), Entity.height, localAI, Main.myPlayer, Main.netMode, netUpdate, npcProj, Entity.oldPosition, owner, Main.player, Entity.position, rotation, BallStepResult.State, GolfHelper.StepGolfBall(), Collision.SwitchTiles(), timeLeft, Tile.type, Entity.velocity, and Entity.width.