Terraria: Projectile.RandomizeInsanityShadowFor
RandomizeInsanityShadowFor()
static void Projectile.RandomizeInsanityShadowFor (Entity targetEntity, bool isHostile, out Vector2 spawnposition, out Vector2 spawnvelocity, out float ai0, out float ai1) inline static
     {
         int num = Main.rand.Next(2) * 2 - 1;
         int num2 = Main.rand.Next(4);
         float num3 = (isHostile ? 200f : 100f);
         float num4 = (isHostile ? 30 : 20);
         float num5 = (isHostile ? 30 : 0);
         float num6 = Main.rand.NextFloatDirection() * (float)Math.PI * 0.125f;
         if (isHostile && targetEntity.velocity.X * (float)num > 0f)
         {
             num *= -1;
         }
         if (num2 == 0 && isHostile)
         {
             num4 += 10f;
         }
         spawnposition = targetEntity.Center + targetEntity.velocity * num5 + new Vector2((float)num * (0f - num3), 0f).RotatedBy(num6);
         spawnvelocity = new Vector2((float)num * num3 / num4, 0f).RotatedBy(num6);
         ai0 = 0f;
         ai1 = 0f;
         if (num2 == 1)
         {
             float num7 = (float)Math.PI * 2f * Main.rand.NextFloat();
             spawnposition = targetEntity.Center - num7.ToRotationVector2() * (isHostile ? num3 : (num3 * 0.5f));
             ai0 = 180f;
             ai1 = num7 - (float)Math.PI / 2f;
             spawnvelocity = num7.ToRotationVector2() * (isHostile ? 4 : 2);
         }
         if (num2 == 2)
         {
             float num8 = (float)Math.PI * 2f * Main.rand.NextFloat();
             spawnposition = targetEntity.Center - num8.ToRotationVector2() * num3;
             ai0 = 300f;
             ai1 = num8;
             spawnvelocity = num8.ToRotationVector2() * (isHostile ? 4 : 2);
         }
         if (num2 == 3)
         {
             float f = (float)Math.PI * 2f * Main.rand.NextFloat();
             float num9 = (isHostile ? 60 : 30);
             float num10 = (float)Math.PI / 2f / num9 * Main.rand.NextFloatDirection();
             spawnposition = targetEntity.Center + targetEntity.velocity * num9;
             Vector2 vector = f.ToRotationVector2() * (isHostile ? 8 : 3);
             for (int i = 0; (float)i < num9; i++)
             {
                 spawnposition -= vector;
                 vector = vector.RotatedBy(0f - num10);
             }
             spawnvelocity = vector;
             ai0 = 390f;
             ai1 = num10;
         }
     }
References Entity.Center, UnifiedRandom.Next(), Main.rand, and Entity.velocity.
Referenced by NPC.AI_123_Deerclops(), Player.SpawnHallucination(), and NPC.SpawnPassiveShadowHands().