Terraria: Projectile.AI_143_MonkStaffT2Ghast
AI_143_MonkStaffT2Ghast()
void Projectile.AI_143_MonkStaffT2Ghast () inline private
     {
         //IL_0037: Unknown result type (might be due to invalid IL or missing references)
         //IL_0021: Unknown result type (might be due to invalid IL or missing references)
         //IL_0026: Unknown result type (might be due to invalid IL or missing references)
         //IL_004c: Unknown result type (might be due to invalid IL or missing references)
         //IL_0051: Unknown result type (might be due to invalid IL or missing references)
         SlotId val;
         if (ai[0] == 0f)
         {
             float[] array = localAI;
             val = SoundEngine.PlayTrackedSound(SoundID.DD2_GhastlyGlaiveImpactGhost, base.Center);
             array[1] = ((SlotId)(ref val)).ToFloat();
         }
         ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
         if (activeSound == null)
         {
             float[] array2 = localAI;
             val = SlotId.Invalid;
             array2[1] = ((SlotId)(ref val)).ToFloat();
         }
         else
         {
             activeSound.Position = base.Center;
         }
         ai[0] += 1f;
         if (ai[0] > 50f)
         {
             alpha += 25;
             if (alpha > 255)
             {
                 alpha = 255;
             }
         }
         else
         {
             alpha -= 25;
             if (alpha < 100)
             {
                 alpha = 100;
             }
         }
         velocity *= 0.98f;
         if (++frameCounter >= 5)
         {
             frameCounter = 0;
             if (++frame >= 4)
             {
                 frame = 0;
             }
         }
         if (ai[0] >= 60f)
         {
             Kill();
         }
         direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
         rotation = velocity.ToRotation();
         if (spriteDirection == -1)
         {
             rotation += (float)Math.PI;
         }
         if (ai[0] >= 10f && ai[0] < 34f)
         {
             Vector2 vector = velocity.SafeNormalize(Vector2.UnitY);
             float num = ai[0] / 60f;
             float num2 = 2f;
             for (int i = 0; (float)i < num2; i++)
             {
                 Dust dust = Dust.NewDustDirect(base.Center, 14, 14, 228, 0f, 0f, 110);
                 dust.velocity = vector * 2f;
                 dust.position = base.Center + vector.RotatedBy(num * ((float)Math.PI * 2f) * 2f + (float)i / num2 * ((float)Math.PI * 2f)) * 7f;
                 dust.scale = 1f + 0.6f * Main.rand.NextFloat();
                 dust.velocity += vector * 3f;
                 dust.noGravity = true;
             }
         }
     }
References SoundID.DD2_GhastlyGlaiveImpactGhost, SlotId.FromFloat(), SoundEngine.GetActiveSound(), SlotId.Invalid, Dust.NewDustDirect(), Dust.noGravity, SoundEngine.PlayTrackedSound(), ActiveSound.Position, Dust.position, Main.rand, Dust.scale, and Dust.velocity.