Terraria: Projectile.AI_137_LightningAura
AI_137_LightningAura()
void Projectile.AI_137_LightningAura () inline private
     {
         //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
         int num = 10;
         int num2 = 999;
         int num3 = 30;
         int num4 = 40;
         int num5 = 4;
         knockBack = 0f;
         if (Main.player[owner].setMonkT2)
         {
             num3 -= 5;
         }
         if (Main.player[owner].setMonkT3)
         {
             num = 14;
             num5 = 8;
         }
         ai[0] += 1f;
         if (ai[0] >= (float)num3)
         {
             ai[0] = 0f;
         }
         if (ai[0] == 0f)
         {
             bool flag = false;
             for (int i = 0; i < 200; i++)
             {
                 NPC nPC = Main.npc[i];
                 if (nPC.CanBeChasedBy(this) && nPC.Hitbox.Distance(base.Center) < (float)(width / 2) && Colliding(base.Hitbox, nPC.Hitbox))
                 {
                     flag = true;
                     break;
                 }
             }
             if (flag)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_LightningAuraZap, base.Center);
             }
         }
         if (localAI[0] == 0f)
         {
             localAI[0] = 1f;
             velocity = Vector2.Zero;
             Point origin = base.Center.ToTileCoordinates();
             bool flag2 = true;
             if (!WorldUtils.Find(origin, Searches.Chain(new Searches.Down(500), _cachedConditions_notNull, _cachedConditions_solid), out var result))
             {
                 flag2 = false;
                 position.Y += 16f;
                 return;
             }
             if (!WorldUtils.Find(new Point(result.X, result.Y - 1), Searches.Chain(new Searches.Up(num), _cachedConditions_notNull, _cachedConditions_solid), out var result2))
             {
                 result2 = new Point(origin.X, origin.Y - num - 1);
             }
             int num6 = 0;
             if (flag2 && Main.tile[result.X, result.Y] != null && Main.tile[result.X, result.Y].blockType() == 1)
             {
                 num6 += 8;
             }
             Vector2 center = result.ToWorldCoordinates(8f, num6);
             Vector2 vector = result2.ToWorldCoordinates(8f, 0f);
             base.Size = new Vector2(1f, center.Y - vector.Y);
             if (height > num * 16)
             {
                 height = num * 16;
             }
             if (height < num5 * 16)
             {
                 height = num5 * 16;
             }
             height *= 2;
             width = (int)((float)height * 1f);
             if (width > num2)
             {
                 width = num2;
             }
             base.Center = center;
         }
         if (++frameCounter >= 8)
         {
             frameCounter = 0;
             if (++frame >= Main.projFrames[type])
             {
                 frame = 0;
             }
         }
         DelegateMethods.v3_1 = new Vector3(0.2f, 0.7f, 1f);
         Utils.PlotTileLine(base.Center + Vector2.UnitX * -40f, base.Center + Vector2.UnitX * 40f, 80f, DelegateMethods.CastLightOpen);
         Vector2 vector2 = new Vector2(base.Top.X, position.Y + (float)num4);
         for (int j = 0; j < 4; j++)
         {
             if (Main.rand.Next(6) != 0)
             {
                 continue;
             }
             Vector2 vector3 = Main.rand.NextVector2Unit();
             if (!(Math.Abs(vector3.X) < 0.12f))
             {
                 Vector2 targetPosition = base.Center + vector3 * new Vector2((height - num4) / 2);
                 if (!WorldGen.SolidTile((int)targetPosition.X / 16, (int)targetPosition.Y / 16) && AI_137_CanHit(targetPosition))
                 {
                     Dust dust = Dust.NewDustDirect(targetPosition, 0, 0, 226, 0f, 0f, 100);
                     dust.position = targetPosition;
                     dust.velocity = (vector2 - dust.position).SafeNormalize(Vector2.Zero);
                     dust.scale = 0.7f;
                     dust.fadeIn = 1f;
                     dust.noGravity = true;
                     dust.noLight = true;
                 }
             }
         }
         for (int k = 0; k < 0; k++)
         {
             if (Main.rand.Next(10) != 0)
             {
                 continue;
             }
             Vector2 vector4 = Main.rand.NextVector2Unit();
             if (!(Math.Abs(vector4.X) < 0.12f))
             {
                 Vector2 targetPosition2 = base.Center + vector4 * new Vector2((height - num4) / 2) * Main.rand.NextFloat();
                 if (!WorldGen.SolidTile((int)targetPosition2.X / 16, (int)targetPosition2.Y / 16) && AI_137_CanHit(targetPosition2))
                 {
                     Dust dust2 = Dust.NewDustDirect(targetPosition2, 0, 0, 226, 0f, 0f, 100);
                     dust2.velocity *= 0.6f;
                     dust2.velocity += Vector2.UnitY * -2f;
                     dust2.noGravity = true;
                     dust2.noLight = true;
                 }
             }
         }
         for (int l = 0; l < 4; l++)
         {
             if (Main.rand.Next(10) == 0)
             {
                 Dust dust3 = Dust.NewDustDirect(vector2 - new Vector2(8f, 0f), 16, height / 2 - 40, 226, 0f, 0f, 100);
                 dust3.velocity *= 0.6f;
                 dust3.velocity += Vector2.UnitY * -2f;
                 dust3.scale = 0.7f;
                 dust3.noGravity = true;
                 dust3.noLight = true;
             }
         }
         tileCollide = true;
         velocity.Y += 0.2f;
     }
References Tile.blockType(), NPC.CanBeChasedBy(), DelegateMethods.CastLightOpen(), Searches.Chain(), SoundID.DD2_LightningAuraZap, Dust.fadeIn, WorldUtils.Find(), Entity.Hitbox, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.npc, Main.player, SoundEngine.PlayTrackedSound(), Utils.PlotTileLine(), Dust.position, Main.projFrames, Main.rand, Dust.scale, Player.setMonkT2, Player.setMonkT3, WorldGen.SolidTile(), Main.tile, DelegateMethods.v3_1, and Dust.velocity.