Terraria: Projectile.AI_156_Think
AI_156_Think()
void Projectile.AI_156_Think (List< int > blacklist) inline private
     {
         bool flag = type == 755;
         bool flag2 = type == 946;
         int num = 60;
         int num2 = num - 1;
         int num3 = num + 60;
         int num4 = num3 - 1;
         int num5 = num + 1;
         if (flag)
         {
             num = 66;
         }
         if (flag2)
         {
             num = 40;
             num2 = num - 1;
             num3 = num + 40;
             num4 = num3 - 1;
             num5 = num + 1;
         }
         Player player = Main.player[owner];
         if (player.active && Vector2.Distance(player.Center, base.Center) > 2000f)
         {
             ai[0] = 0f;
             ai[1] = 0f;
             netUpdate = true;
         }
         if (ai[0] == -1f)
         {
             AI_GetMyGroupIndexAndFillBlackList(blacklist, out var index, out var totalIndexesInGroup);
             AI_156_GetIdlePosition(index, totalIndexesInGroup, out var idleSpot, out var idleRotation);
             velocity = Vector2.Zero;
             base.Center = base.Center.MoveTowards(idleSpot, 32f);
             rotation = rotation.AngleLerp(idleRotation, 0.2f);
             if (Distance(idleSpot) < 2f)
             {
                 ai[0] = 0f;
                 netUpdate = true;
             }
             return;
         }
         if (ai[0] == 0f)
         {
             if (flag)
             {
                 AI_GetMyGroupIndexAndFillBlackList(blacklist, out var index2, out var totalIndexesInGroup2);
                 AI_156_GetIdlePosition(index2, totalIndexesInGroup2, out var idleSpot2, out var _);
                 velocity = Vector2.Zero;
                 base.Center = Vector2.SmoothStep(base.Center, idleSpot2, 0.45f);
                 if (Main.rand.Next(20) == 0)
                 {
                     int num6 = AI_156_TryAttackingNPCs(blacklist);
                     if (num6 != -1)
                     {
                         AI_156_StartAttack();
                         ai[0] = num;
                         ai[1] = num6;
                         netUpdate = true;
                         return;
                     }
                 }
             }
             if (!flag2)
             {
                 return;
             }
             AI_GetMyGroupIndexAndFillBlackList(blacklist, out var index3, out var totalIndexesInGroup3);
             AI_156_GetIdlePosition(index3, totalIndexesInGroup3, out var idleSpot3, out var idleRotation3);
             velocity = Vector2.Zero;
             base.Center = Vector2.SmoothStep(base.Center, idleSpot3, 0.45f);
             rotation = rotation.AngleLerp(idleRotation3, 0.45f);
             if (Main.rand.Next(20) == 0)
             {
                 int num7 = AI_156_TryAttackingNPCs(blacklist);
                 if (num7 != -1)
                 {
                     AI_156_StartAttack();
                     ai[0] = Main.rand.NextFromList<int>(num, num3);
                     ai[0] = num3;
                     ai[1] = num7;
                     netUpdate = true;
                 }
             }
             return;
         }
         if (flag)
         {
             int num8 = (int)ai[1];
             if (!Main.npc.IndexInRange(num8))
             {
                 ai[0] = 0f;
                 netUpdate = true;
                 return;
             }
             NPC nPC = Main.npc[num8];
             if (!nPC.CanBeChasedBy(this))
             {
                 ai[0] = 0f;
                 netUpdate = true;
                 return;
             }
             ai[0] -= 1f;
             if (ai[0] >= (float)num2)
             {
                 velocity *= 0.8f;
                 if (ai[0] == (float)num2)
                 {
                     localAI[0] = base.Center.X;
                     localAI[1] = base.Center.Y;
                 }
                 return;
             }
             float lerpValue = Utils.GetLerpValue(num2, 0f, ai[0], clamped: true);
             Vector2 vector = new Vector2(localAI[0], localAI[1]);
             if (lerpValue >= 0.5f)
             {
                 vector = Main.player[owner].Center;
             }
             Vector2 center = nPC.Center;
             float num9 = (center - vector).ToRotation();
             float num10 = ((center.X > vector.X) ? (-(float)Math.PI) : ((float)Math.PI));
             float num11 = num10 + (0f - num10) * lerpValue * 2f;
             Vector2 spinningpoint = num11.ToRotationVector2();
             spinningpoint.Y *= (float)Math.Sin((float)identity * 2.3f) * 0.5f;
             spinningpoint = spinningpoint.RotatedBy(num9);
             float num12 = (center - vector).Length() / 2f;
             Vector2 center2 = Vector2.Lerp(vector, center, 0.5f) + spinningpoint * num12;
             base.Center = center2;
             Vector2 vector2 = MathHelper.WrapAngle(num9 + num11 + 0f).ToRotationVector2() * 10f;
             velocity = vector2;
             position -= velocity;
             if (ai[0] == 0f)
             {
                 int num13 = AI_156_TryAttackingNPCs(blacklist);
                 if (num13 != -1)
                 {
                     ai[0] = num;
                     ai[1] = num13;
                     AI_156_StartAttack();
                     netUpdate = true;
                     return;
                 }
                 ai[1] = 0f;
                 netUpdate = true;
             }
         }
         if (!flag2)
         {
             return;
         }
         bool skipBodyCheck = true;
         int num14 = 0;
         int num15 = num2;
         int num16 = 0;
         if (ai[0] >= (float)num5)
         {
             num14 = 1;
             num15 = num4;
             num16 = num5;
         }
         int num17 = (int)ai[1];
         if (!Main.npc.IndexInRange(num17))
         {
             int num18 = AI_156_TryAttackingNPCs(blacklist, skipBodyCheck);
             if (num18 != -1)
             {
                 ai[0] = Main.rand.NextFromList<int>(num, num3);
                 ai[1] = num18;
                 AI_156_StartAttack();
                 netUpdate = true;
             }
             else
             {
                 ai[0] = -1f;
                 ai[1] = 0f;
                 netUpdate = true;
             }
             return;
         }
         NPC nPC2 = Main.npc[num17];
         if (!nPC2.CanBeChasedBy(this))
         {
             int num19 = AI_156_TryAttackingNPCs(blacklist, skipBodyCheck);
             if (num19 != -1)
             {
                 ai[0] = Main.rand.NextFromList<int>(num, num3);
                 AI_156_StartAttack();
                 ai[1] = num19;
                 netUpdate = true;
             }
             else
             {
                 ai[0] = -1f;
                 ai[1] = 0f;
                 netUpdate = true;
             }
             return;
         }
         ai[0] -= 1f;
         if (ai[0] >= (float)num15)
         {
             direction = ((base.Center.X < nPC2.Center.X) ? 1 : (-1));
             if (ai[0] == (float)num15)
             {
                 localAI[0] = base.Center.X;
                 localAI[1] = base.Center.Y;
             }
         }
         float lerpValue2 = Utils.GetLerpValue(num15, num16, ai[0], clamped: true);
         if (num14 == 0)
         {
             Vector2 vector3 = new Vector2(localAI[0], localAI[1]);
             if (lerpValue2 >= 0.5f)
             {
                 vector3 = Vector2.Lerp(nPC2.Center, Main.player[owner].Center, 0.5f);
             }
             Vector2 center3 = nPC2.Center;
             float num20 = (center3 - vector3).ToRotation();
             float num21 = ((direction == 1) ? (-(float)Math.PI) : ((float)Math.PI));
             float num22 = num21 + (0f - num21) * lerpValue2 * 2f;
             Vector2 spinningpoint2 = num22.ToRotationVector2();
             spinningpoint2.Y *= 0.5f;
             spinningpoint2.Y *= 0.8f + (float)Math.Sin((float)identity * 2.3f) * 0.2f;
             spinningpoint2 = spinningpoint2.RotatedBy(num20);
             float num23 = (center3 - vector3).Length() / 2f;
             Vector2 center4 = Vector2.Lerp(vector3, center3, 0.5f) + spinningpoint2 * num23;
             base.Center = center4;
             float num24 = MathHelper.WrapAngle(num20 + num22 + 0f);
             rotation = num24 + (float)Math.PI / 2f;
             Vector2 vector4 = num24.ToRotationVector2() * 10f;
             velocity = vector4;
             position -= velocity;
         }
         if (num14 == 1)
         {
             Vector2 vector5 = new Vector2(localAI[0], localAI[1]);
             vector5 += new Vector2(0f, Utils.GetLerpValue(0f, 0.4f, lerpValue2, clamped: true) * -100f);
             Vector2 v = nPC2.Center - vector5;
             Vector2 vector6 = v.SafeNormalize(Vector2.Zero) * MathHelper.Clamp(v.Length(), 60f, 150f);
             Vector2 value = nPC2.Center + vector6;
             float lerpValue3 = Utils.GetLerpValue(0.4f, 0.6f, lerpValue2, clamped: true);
             float lerpValue4 = Utils.GetLerpValue(0.6f, 1f, lerpValue2, clamped: true);
             float targetAngle = v.SafeNormalize(Vector2.Zero).ToRotation() + (float)Math.PI / 2f;
             rotation = rotation.AngleTowards(targetAngle, (float)Math.PI / 5f);
             base.Center = Vector2.Lerp(vector5, nPC2.Center, lerpValue3);
             if (lerpValue4 > 0f)
             {
                 base.Center = Vector2.Lerp(nPC2.Center, value, lerpValue4);
             }
         }
         if (ai[0] == (float)num16)
         {
             int num25 = AI_156_TryAttackingNPCs(blacklist, skipBodyCheck);
             if (num25 != -1)
             {
                 ai[0] = Main.rand.NextFromList<int>(num, num3);
                 ai[1] = num25;
                 AI_156_StartAttack();
                 netUpdate = true;
             }
             else
             {
                 ai[0] = -1f;
                 ai[1] = 0f;
                 netUpdate = true;
             }
         }
     }
References Entity.active, NPC.CanBeChasedBy(), Entity.Center, Utils.GetLerpValue(), UnifiedRandom.Next(), Main.npc, Main.player, and Main.rand.