Terraria: Projectile.vampireHeal
vampireHeal()
void Projectile.vampireHeal (int dmg, Vector2 Position, Entity victim) inline
     {
         float num = (float)dmg * 0.075f;
         if ((int)num != 0 && !(Main.player[Main.myPlayer].lifeSteal <= 0f))
         {
             Main.player[Main.myPlayer].lifeSteal -= num;
             int num2 = owner;
             NewProjectile(GetProjectileSource_OnHit(victim, 18), Position.X, Position.Y, 0f, 0f, 305, 0, 0f, owner, num2, num);
         }
     }
References GetProjectileSource_OnHit(), Player.lifeSteal, Main.myPlayer, NewProjectile(), owner, and Main.player.
Referenced by Damage().