Terraria: Projectile.Colliding
Colliding()
bool Projectile.Colliding (Rectangle myRect, Rectangle targetRect) inline
     {
         if (aiStyle == 15)
         {
             if (ai[0] == 0f)
             {
                 Vector2 mountedCenter = Main.player[owner].MountedCenter;
                 Vector2 vector = targetRect.ClosestPointInRect(mountedCenter) - mountedCenter;
                 vector.Y /= 0.8f;
                 float num = 55f;
                 return vector.Length() <= num;
             }
         }
         else if (type == 973)
         {
             Vector2 v = targetRect.ClosestPointInRect(base.Center) - base.Center;
             v.SafeNormalize(Vector2.UnitX);
             float num2 = 100f * scale;
             if (v.Length() < num2 && Collision.CanHit(base.Center, 0, 0, targetRect.Center.ToVector2(), 0, 0))
             {
                 return true;
             }
         }
         else
         {
             if (type == 85)
             {
                 if (!myRect.Intersects(targetRect))
                 {
                     return false;
                 }
                 return Collision.CanHit(base.Center, 0, 0, targetRect.Center.ToVector2(), 0, 0);
             }
             if (type == 985)
             {
                 float coneLength = 90f * scale;
                 float maximumAngle = (float)Math.PI / 4f;
                 float coneRotation = rotation;
                 if (targetRect.IntersectsConeFastInaccurate(base.Center, coneLength, coneRotation, maximumAngle) && Collision.CanHit(base.Center, 0, 0, targetRect.Center.ToVector2(), 0, 0))
                 {
                     return true;
                 }
             }
             else
             {
                 if (aiStyle == 190)
                 {
                     float coneLength2 = 94f * scale;
                     float num3 = (float)Math.PI * 2f / 25f * ai[0];
                     float maximumAngle2 = (float)Math.PI / 4f;
                     float num4 = rotation + num3;
                     if (targetRect.IntersectsConeSlowMoreAccurate(base.Center, coneLength2, num4, maximumAngle2))
                     {
                         return true;
                     }
                     float num5 = Utils.Remap(localAI[0], ai[1] * 0.3f, ai[1] * 0.5f, 1f, 0f);
                     if (num5 > 0f)
                     {
                         float coneRotation2 = num4 - (float)Math.PI / 4f * ai[0] * num5;
                         if (targetRect.IntersectsConeSlowMoreAccurate(base.Center, coneLength2, coneRotation2, maximumAngle2))
{
                             return true;
                         }
                     }
                     return false;
                 }
                 if (type == 623)
                 {
                     if (ai[0] == 2f)
                     {
                         Rectangle value = Utils.CenteredRectangle(base.Center + new Vector2(direction * 40, 0f), new Vector2(80f, 40f));
                         if (targetRect.Intersects(value))
{
                             return true;
                         }
                     }
                 }
                 else
                 {
                     if (type == 933)
                     {
                         float collisionPoint = 0f;
                         float num6 = 40f;
                         for (int i = 14; i < oldPos.Length; i += 15)
{
                             float num7 = localAI[0] - (float)i;
                             if (!(num7 < 0f) && !(num7 > 60f))
{
                                 Vector2 vector2 = oldPos[i] + base.Size / 2f;
                                 Vector2 vector3 = (oldRot[i] + (float)Math.PI / 2f).ToRotationVector2();
                                 _lanceHitboxBounds.X = (int)vector2.X - _lanceHitboxBounds.Width / 2;
                                 _lanceHitboxBounds.Y = (int)vector2.Y - _lanceHitboxBounds.Height / 2;
                                 if (_lanceHitboxBounds.Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), vector2 - vector3 * num6, vector2 + vector3 * num6, 20f, ref collisionPoint))
{
                                     return true;
                                 }
                             }
                         }
                         Vector2 vector4 = (rotation + (float)Math.PI / 2f).ToRotationVector2();
                         _lanceHitboxBounds.X = (int)position.X - _lanceHitboxBounds.Width / 2;
                         _lanceHitboxBounds.Y = (int)position.Y - _lanceHitboxBounds.Height / 2;
                         if (_lanceHitboxBounds.Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center - vector4 * num6, base.Center + vector4 * num6, 20f, ref collisionPoint))
{
                             return true;
                         }
                         return false;
                     }
                     if (type == 927)
                     {
                         for (float num8 = 0f; num8 <= 1f; num8 += 0.05f)
{
                             float num9 = Utils.Remap(num8, 0f, 1f, 1f, 5f);
                             Rectangle rectangle = myRect;
                             Vector2 vector5 = velocity.SafeNormalize(Vector2.Zero) * width * num9 * scale;
                             rectangle.Offset((int)vector5.X, (int)vector5.Y);
                             if (rectangle.Intersects(targetRect))
{
                                 return true;
                             }
                         }
                     }
                     else
                     {
                         if (type == 877 || type == 878 || type == 879)
{
                             float f = rotation - (float)Math.PI / 4f - (float)Math.PI / 2f - ((spriteDirection == 1) ? ((float)Math.PI) : 0f);
                             float collisionPoint2 = 0f;
                             float num10 = 95f;
                             _lanceHitboxBounds.X = (int)position.X - _lanceHitboxBounds.Width / 2;
                             _lanceHitboxBounds.Y = (int)position.Y - _lanceHitboxBounds.Height / 2;
                             if (_lanceHitboxBounds.Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + f.ToRotationVector2() * num10, 23f * scale, ref collisionPoint2))
{
                                 return true;
                             }
                             return false;
                         }
                         if (type == 974)
{
                             float f2 = rotation;
                             float collisionPoint3 = 0f;
                             float num11 = 46f * scale;
                             float num12 = 8f;
                             Vector2 vector6 = f2.ToRotationVector2();
                             Rectangle hitbox = base.Hitbox;
                             hitbox.Inflate((int)num11, (int)num11);
                             if (hitbox.Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center - vector6 * num11, base.Center + vector6 * num11, num12 * scale, ref collisionPoint3))
{
                                 return true;
                             }
                             return false;
                         }
                         if (type == 919 || type == 932)
{
                             float f3 = rotation;
                             float collisionPoint4 = 0f;
                             float num13 = 40f;
                             Vector2 vector7 = f3.ToRotationVector2();
                             _lanceHitboxBounds.X = (int)position.X - _lanceHitboxBounds.Width / 2;
                             _lanceHitboxBounds.Y = (int)position.Y - _lanceHitboxBounds.Height / 2;
                             if (_lanceHitboxBounds.Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center - vector7 * num13, base.Center + vector7 * num13, 8f, ref collisionPoint4))
{
                                 return true;
                             }
                             return false;
                         }
                         if (type == 923)
{
                             float collisionPoint5 = 0f;
                             _ = scale;
                             float f4 = rotation;
                             Vector2 objectPosition = targetRect.TopLeft();
                             Vector2 objectDimensions = targetRect.Size();
                             Vector2 vector8 = f4.ToRotationVector2();
                             float num14 = scale * 0.7f;
                             if (Collision.CheckAABBvLineCollision(objectPosition, objectDimensions, base.Center, base.Center + vector8 * scale * 510f, num14 * 100f, ref collisionPoint5))
{
                                 return true;
                             }
                             if (Collision.CheckAABBvLineCollision(objectPosition, objectDimensions, base.Center, base.Center + vector8 * scale * 660f, num14 * 60f, ref collisionPoint5))
{
                                 return true;
                             }
                             if (Collision.CheckAABBvLineCollision(objectPosition, objectDimensions, base.Center, base.Center + vector8 * scale * 800f, num14 * 10f, ref collisionPoint5))
{
                                 return true;
                             }
                             return false;
                         }
                         if (type == 598 && targetRect.Width > 8 && targetRect.Height > 8)
{
                             targetRect.Inflate(-targetRect.Width / 8, -targetRect.Height / 8);
                         }
                         else
{
                             if (type == 872)
{
                                 Rectangle hitbox2 = base.Hitbox;
                                 int num15 = 80;
                                 for (int j = 0; j < num15; j += 2)
{
                                     Vector2 vector9 = oldPos[j];
                                     if (!(vector9 == Vector2.Zero))
{
                                         hitbox2.X = (int)vector9.X;
                                         hitbox2.Y = (int)vector9.Y;
                                         if (hitbox2.Intersects(targetRect))
{
                                             return true;
                                         }
                                     }
                                 }
                                 return false;
                             }
                             if (type == 871)
{
                                 int num16 = AI_172_GetPelletStormsCount();
                                 for (int k = 0; k < num16; k++)
{
                                     HallowBossPelletStormInfo hallowBossPelletStormInfo = AI_172_GetPelletStormInfo(k);
                                     for (int l = 0; l < hallowBossPelletStormInfo.BulletsInStorm; l++)
{
                                         if (hallowBossPelletStormInfo.IsValid(l) && hallowBossPelletStormInfo.GetBulletHitbox(l, base.Center).Intersects(targetRect))
{
                                             return true;
                                         }
                                     }
                                 }
                                 return false;
                             }
                             if (ProjectileID.Sets.IsAWhip[type])
{
                                 WhipPointsForCollision.Clear();
                                 FillWhipControlPoints(this, WhipPointsForCollision);
                                 for (int m = 0; m < WhipPointsForCollision.Count; m++)
{
                                     Point point = WhipPointsForCollision[m].ToPoint();
                                     myRect.Location = new Point(point.X - myRect.Width / 2, point.Y - myRect.Height / 2);
                                     if (myRect.Intersects(targetRect))
{
                                         return true;
                                     }
                                 }
                                 return false;
                             }
                             if (type == 614 && targetRect.Width > 8 && targetRect.Height > 8)
{
                                 targetRect.Inflate(-targetRect.Width / 8, -targetRect.Height / 8);
                             }
                             else if (type == 963 && ai[0] >= 2f)
{
                                 targetRect.Inflate(30, 30);
                             }
                             else if (type == 758)
{
                                 if (ai[0] == 2f && Utils.CenteredRectangle(base.Center + new Vector2(spriteDirection * 30, 0f), new Vector2(50f, 20f)).Intersects(targetRect))
{
                                     return true;
                                 }
                             }
                             else if (type == 636 && targetRect.Width > 8 && targetRect.Height > 8)
{
                                 targetRect.Inflate(-targetRect.Width / 8, -targetRect.Height / 8);
                             }
                             else if (type == 607)
{
                                 myRect.X += (int)velocity.X;
                                 myRect.Y += (int)velocity.Y;
                             }
                             else if (type == 661)
{
                                 if (Vector2.Distance(myRect.Center.ToVector2(), targetRect.Center.ToVector2()) > 500f || !Collision.CanHitLine(myRect.Center.ToVector2(), 0, 0, targetRect.Center.ToVector2(), 0, 0))
{
                                     return false;
                                 }
                             }
                             else
{
                                 if (aiStyle == 137)
{
                                     if (myRect.Intersects(targetRect) && targetRect.Distance(base.Center) < (float)(height / 2 - 20))
{
                                         if (AI_137_CanHit(targetRect.Center.ToVector2()))
{
                                             return true;
                                         }
                                         if (AI_137_CanHit(targetRect.TopLeft() + new Vector2(targetRect.Width / 2, 0f)))
{
                                             return true;
                                         }
                                     }
                                     return false;
                                 }
                                 if (aiStyle == 19)
{
                                     Vector2 center = base.Center;
                                     if (AI_019_Spears_GetExtensionHitbox(out var extensionBox))
{
                                         Vector2 vector10 = extensionBox.Center.ToVector2();
                                         float num17 = Vector2.Distance(vector10, center);
                                         Vector2 size = extensionBox.Size();
                                         float num18 = MathHelper.Max(extensionBox.Width, extensionBox.Height);
                                         if (num18 < 12f)
{
                                             num18 = 12f;
                                         }
                                         for (float num19 = num18; num19 < num17; num19 += num18)
{
                                             if (Utils.CenteredRectangle(Vector2.Lerp(center, vector10, num19 / num17), size).Intersects(targetRect))
{
                                                 return true;
                                             }
                                         }
                                         if (extensionBox.Intersects(targetRect))
{
                                             return true;
                                         }
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
         }
         if (myRect.Intersects(targetRect))
         {
             return true;
         }
         if (type == 461)
         {
             float collisionPoint6 = 0f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 22f * scale, ref collisionPoint6))
             {
                 return true;
             }
             return false;
         }
         if (type == 697 || type == 707)
         {
             float f5 = rotation - (float)Math.PI / 4f * (float)Math.Sign(velocity.X);
             float collisionPoint7 = 0f;
             float num20 = 50f;
             if (type == 697)
             {
                 num20 = 65f;
             }
             if (type == 707)
             {
                 num20 = 110f;
             }
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center + f5.ToRotationVector2() * (0f - num20), base.Center + f5.ToRotationVector2() * num20, 23f * scale, ref collisionPoint7))
             {
                 return true;
             }
             return false;
         }
         if (type == 699)
         {
             float f6 = rotation - (float)Math.PI / 4f * (float)Math.Sign(velocity.X) + ((spriteDirection == -1) ? ((float)Math.PI) : 0f);
             float collisionPoint8 = 0f;
             float num21 = -95f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + f6.ToRotationVector2() * num21, 23f * scale, ref collisionPoint8))
             {
                 return true;
             }
             return false;
         }
         if (type == 642)
         {
             float collisionPoint9 = 0f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 30f * scale, ref collisionPoint9))
             {
                 return true;
             }
             return false;
         }
         if (type == 802 || type == 842 || type == 938 || type == 939 || type == 940 || type == 941 || type == 942 || type == 943 || type == 944 || type == 945)
         {
             float collisionPoint10 = 0f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * 6f, 10f * scale, ref collisionPoint10))
             {
                 return true;
             }
             return false;
         }
         if (type == 632)
         {
             float collisionPoint11 = 0f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 22f * scale, ref collisionPoint11))
             {
                 return true;
             }
             return false;
         }
         if (type == 455)
         {
             float collisionPoint12 = 0f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 36f * scale, ref collisionPoint12))
             {
                 return true;
             }
             return false;
         }
         if (type == 611)
         {
             float collisionPoint13 = 0f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity + velocity.SafeNormalize(Vector2.Zero) * 48f, 16f * scale, ref collisionPoint13))
             {
                 return true;
             }
             return false;
         }
         if (type == 684)
         {
             float collisionPoint14 = 0f;
             Vector2 vector11 = velocity.SafeNormalize(Vector2.UnitY).RotatedBy(-1.5707963705062866) * scale;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center - vector11 * 40f, base.Center + vector11 * 40f, 16f * scale, ref collisionPoint14))
             {
                 return true;
             }
             return false;
         }
         if (type == 537)
         {
             float collisionPoint15 = 0f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 22f * scale, ref collisionPoint15))
             {
                 return true;
             }
             return false;
         }
         if (type == 756 || type == 961)
         {
             float collisionPoint16 = 0f;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity.SafeNormalize(-Vector2.UnitY) * 200f * scale, 22f * scale, ref collisionPoint16))
             {
                 return true;
             }
             return false;
         }
         if (type == 687)
         {
             float collisionPoint17 = 0f;
             float num22 = ai[0] / 25f;
             if (num22 > 1f)
             {
                 num22 = 1f;
             }
             float num23 = (ai[0] - 38f) / 40f;
             if (num23 < 0f)
             {
                 num23 = 0f;
             }
             Vector2 lineStart = base.Center + rotation.ToRotationVector2() * 400f * num23;
             Vector2 lineEnd = base.Center + rotation.ToRotationVector2() * 400f * num22;
             if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), lineStart, lineEnd, 40f * scale, ref collisionPoint17))
             {
                 return true;
             }
             return false;
         }
         if (type == 466 || type == 580 || type == 686)
         {
             for (int n = 0; n < oldPos.Length && (oldPos[n].X != 0f || oldPos[n].Y != 0f); n++)
             {
                 myRect.X = (int)oldPos[n].X;
                 myRect.Y = (int)oldPos[n].Y;
                 if (myRect.Intersects(targetRect))
                 {
                     return true;
                 }
             }
             return false;
         }
         if (type == 711)
         {
             if (penetrate != -1)
             {
                 for (int num24 = 0; num24 < oldPos.Length && (oldPos[num24].X != 0f || oldPos[num24].Y != 0f); num24++)
                 {
                     myRect.X = (int)oldPos[num24].X;
                     myRect.Y = (int)oldPos[num24].Y;
                     if (myRect.Intersects(targetRect))
                     {
                         return true;
                     }
                 }
             }
         }
         else if (type == 464 && ai[1] != 1f)
         {
             Vector2 vector12 = new Vector2(0f, -720f).RotatedBy(velocity.ToRotation());
             float num25 = ai[0] % 45f / 45f;
             Vector2 spinningpoint = vector12 * num25;
             for (int num26 = 0; num26 < 6; num26++)
             {
                 float num27 = (float)num26 * ((float)Math.PI * 2f) / 6f;
                 if (Utils.CenteredRectangle(base.Center + spinningpoint.RotatedBy(num27), new Vector2(30f, 30f)).Intersects(targetRect))
                 {
                     return true;
                 }
             }
         }
         return false;
     }
References _lanceHitboxBounds, ai, AI_019_Spears_GetExtensionHitbox(), AI_137_CanHit(), AI_172_GetPelletStormInfo(), AI_172_GetPelletStormsCount(), aiStyle, Projectile.HallowBossPelletStormInfo.BulletsInStorm, Collision.CanHit(), Collision.CanHitLine(), Utils.CenteredRectangle(), Collision.CheckAABBvLineCollision(), Entity.direction, FillWhipControlPoints(), Projectile.HallowBossPelletStormInfo.GetBulletHitbox(), Entity.height, ProjectileID.Sets.IsAWhip, Projectile.HallowBossPelletStormInfo.IsValid(), localAI, Player.MountedCenter, oldPos, oldRot, owner, penetrate, Main.player, Entity.position, Utils.Remap(), rotation, scale, spriteDirection, type, Entity.velocity, WhipPointsForCollision, Entity.width, X, and Y.
Referenced by AI(), and Damage().