Terraria: Projectile.AI_177_IceWhipSlicer
AI_177_IceWhipSlicer()
void Projectile.AI_177_IceWhipSlicer () inline private
     {
         //IL_009c: Unknown result type (might be due to invalid IL or missing references)
         //IL_0085: Unknown result type (might be due to invalid IL or missing references)
         //IL_008a: Unknown result type (might be due to invalid IL or missing references)
         //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
         //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
         Player player = Main.player[owner];
         if (type == 917 && (!player.active || player.dead))
         {
             player.coolWhipBuff = false;
             Kill();
             return;
         }
         if (type == 917 && player.coolWhipBuff)
         {
             timeLeft = 2;
         }
         if (type == 969)
         {
             SlotId val;
             if (soundDelay == 0)
             {
                 soundDelay = -1;
                 float[] array = localAI;
                 val = SoundEngine.PlayTrackedSound(SoundID.DD2_BookStaffTwisterLoop, base.Center);
                 array[1] = ((SlotId)(ref val)).ToFloat();
             }
             ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
             if (activeSound != null)
             {
                 activeSound.Position = base.Center;
                 activeSound.Volume = 1f - Math.Max(ai[1] - 555f, 0f) / 15f;
             }
             else
             {
                 float[] array2 = localAI;
                 val = SlotId.Invalid;
                 array2[1] = ((SlotId)(ref val)).ToFloat();
             }
             ai[1] += 1f;
             if (ai[1] > 560f)
             {
                 alpha = (int)MathHelper.Lerp(0f, 250f, (ai[1] - 560f) / 10f);
             }
             if (ai[1] >= 570f)
             {
                 Kill();
             }
             float num = 555f;
             for (int i = 0; i < 1000; i++)
             {
                 if (i != whoAmI && Main.projectile[i].active && Main.projectile[i].owner == owner && Main.projectile[i].type == type && timeLeft > Main.projectile[i].timeLeft && Main.projectile[i].ai[1] < num)
                 {
                     Main.projectile[i].ai[1] = num;
                     Main.projectile[i].netUpdate = true;
                 }
             }
         }
         int num2 = (int)ai[0] - 1;
         if (num2 != -1 && (!Main.npc[num2].CanBeChasedBy(this) || localNPCImmunity[num2] > 0))
         {
             ai[0] = 0f;
             num2 = -1;
         }
         if (num2 == -1)
         {
             bool checkCanHit = false;
             if (type == 969)
             {
                 checkCanHit = true;
             }
             NPC nPC = FindTargetWithinRange(400f, checkCanHit);
             if (nPC != null)
             {
                 num2 = nPC.whoAmI;
                 ai[0] = num2 + 1;
                 netUpdate = true;
             }
         }
         float num3 = 18f;
         float amount = 0.1f;
         float num4 = 0f;
         if (type == 969)
         {
             num3 = 8f;
             amount = 0.075f;
             num4 = 25f;
         }
         if (num2 != -1)
         {
             NPC nPC2 = Main.npc[num2];
             float num5 = Distance(nPC2.Center);
             if (num3 > num5)
             {
                 num3 = num5;
             }
             Vector2 vector = DirectionTo(nPC2.Center);
             if (!vector.HasNaNs() && num5 >= num4)
             {
                 velocity = Vector2.Lerp(velocity, vector * num3, amount);
             }
         }
         else if (type == 969)
         {
             Vector2 vector2 = DirectionTo(base.Center + velocity);
             if (!vector2.HasNaNs())
             {
                 velocity = Vector2.Lerp(velocity, vector2 * num3, amount);
             }
         }
         else
         {
             velocity *= 0.92f;
         }
         if (type == 969)
         {
             rotation = velocity.X * 0.0125f;
             if (++frameCounter > 4)
             {
                 frameCounter = 0;
                 frame++;
                 if (frame >= Main.projFrames[type])
                 {
                     frame = 0;
                 }
             }
             if (timeLeft % 3 == 0)
             {
                 int num6 = Dust.NewDust(position, width, height, 16, velocity.X, velocity.Y, 120, default(Color), 0.5f);
                 Main.dust[num6].noGravity = true;
                 Main.dust[num6].fadeIn = 0.9f;
                 Main.dust[num6].velocity = Main.rand.NextVector2Circular(2f, 2f) + new Vector2(0f, -2f) + velocity * 0.75f;
                 for (int j = 0; j < 2; j++)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 16, velocity.X, velocity.Y, 60, default(Color), 0.5f);
                     dust.noGravity = true;
                     dust.fadeIn = 0.7f;
                     dust.velocity = Main.rand.NextVector2Circular(2f, 2f) * 0.2f + new Vector2(0f, -0.4f) + velocity * 1.5f;
                     dust.position -= velocity * 3f;
                 }
             }
         }
         else
         {
             rotation += 0.020943953f + Math.Abs(velocity.X) * 0.2f;
             if (Main.rand.Next(3) == 0)
             {
                 Dust dust2 = Dust.NewDustDirect(base.Center, 0, 0, 43, velocity.X, velocity.Y, 254, Color.White, 0.5f);
                 Vector2 vector3 = Main.rand.NextVector2Circular(1f, 1f);
                 dust2.position = base.Center + vector3 * 10f;
                 dust2.velocity = vector3;
             }
         }
     }
References Entity.active, ai, NPC.CanBeChasedBy(), Entity.Center, Color, Player.coolWhipBuff, SoundID.DD2_BookStaffTwisterLoop, Player.dead, Main.dust, Dust.fadeIn, SlotId.FromFloat(), SoundEngine.GetActiveSound(), SlotId.Invalid, netUpdate, Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.npc, owner, Main.player, SoundEngine.PlayTrackedSound(), ActiveSound.Position, Dust.position, Main.projectile, Main.projFrames, Main.rand, timeLeft, type, Dust.velocity, ActiveSound.Volume, and Entity.whoAmI.