Terraria: Projectile.FishingCheck_ProbeForQuestFish
FishingCheck_ProbeForQuestFish()
void Projectile.FishingCheck_ProbeForQuestFish (ref FishingAttempt fisher) inline private
     {
         fisher.questFish = Main.anglerQuestItemNetIDs[Main.anglerQuest];
         if (Main.player[owner].HasItem(fisher.questFish))
         {
             fisher.questFish = -1;
         }
         if (!NPC.AnyNPCs(369))
         {
             fisher.questFish = -1;
         }
         if (Main.anglerQuestFinished)
         {
             fisher.questFish = -1;
         }
     }
References Main.anglerQuest, Main.anglerQuestFinished, Main.anglerQuestItemNetIDs, NPC.AnyNPCs(), Player.HasItem(), owner, and Main.player.
Referenced by FishingCheck().