Terraria: Projectile.AI_160_Kites
AI_160_Kites()
void Projectile.AI_160_Kites () inline private
     {
         Player player = Main.player[owner];
         Vector2 vector = player.RotatedRelativePoint(player.MountedCenter);
         timeLeft = 60;
         bool flag = false;
         if (player.CCed || player.noItems)
         {
             flag = true;
         }
         else if (player.inventory[player.selectedItem].shoot != type)
         {
             flag = true;
         }
         else if (player.pulley)
         {
             flag = true;
         }
         else if (player.dead)
         {
             flag = true;
         }
         if (!flag)
         {
             flag = (player.Center - base.Center).Length() > 2000f;
         }
         if (flag)
         {
             Kill();
             return;
         }
         float num = 4f;
         float num2 = 500f;
         float num3 = num2 / 2f;
         if (owner == Main.myPlayer && extraUpdates == 0)
         {
             float num4 = ai[0];
             if (ai[0] == 0f)
             {
                 ai[0] = num3;
             }
             float num5 = ai[0];
             if (Main.mouseRight)
             {
                 num5 -= 5f;
             }
             if (Main.mouseLeft)
             {
                 num5 += 5f;
             }
             ai[0] = MathHelper.Clamp(num5, num, num2);
             if (num4 != num5)
             {
                 netUpdate = true;
             }
         }
         if (numUpdates == 1)
         {
             extraUpdates = 0;
         }
         int num6 = 0;
         float cloudAlpha = Main.cloudAlpha;
         float num7 = 0f;
         if (WorldGen.InAPlaceWithWind(position, width, height))
         {
             num7 = Main.WindForVisuals;
         }
         float num8 = Utils.GetLerpValue(0.2f, 0.5f, Math.Abs(num7), clamped: true) * 0.5f;
         switch (num6)
         {
         case 0:
         {
             Vector2 mouseWorld = Main.MouseWorld;
             mouseWorld = base.Center;
             mouseWorld += new Vector2(num7, (float)Math.Sin(Main.GlobalTimeWrappedHourly) + cloudAlpha * 5f) * 25f;
             Vector2 v = mouseWorld - base.Center;
             v = v.SafeNormalize(Vector2.Zero) * (3f + cloudAlpha * 7f);
             if (num8 == 0f)
             {
                 v = velocity;
             }
             float num9 = Distance(mouseWorld);
             float lerpValue = Utils.GetLerpValue(5f, 10f, num9, clamped: true);
             float y = velocity.Y;
             if (num9 > 10f)
             {
                 velocity = Vector2.Lerp(velocity, v, 0.075f * lerpValue);
             }
             velocity.Y = y;
             velocity.Y -= num8;
             velocity.Y += 0.02f + num8 * 0.25f;
             velocity.Y = MathHelper.Clamp(velocity.Y, -2f, 2f);
             if (base.Center.Y + velocity.Y < mouseWorld.Y)
             {
                 velocity.Y = MathHelper.Lerp(velocity.Y, velocity.Y + num8 + 0.01f, 0.75f);
             }
             velocity.X *= 0.98f;
             float num10 = Distance(vector);
             float num11 = ai[0];
             if (num10 > num11)
             {
                 Vector2 vector3 = DirectionTo(vector);
                 float num12 = num10 - num11;
                 base.Center += vector3 * num12;
                 bool num13 = Vector2.Dot(vector3, Vector2.UnitY) < 0.8f || num8 > 0f;
                 velocity.Y += vector3.Y * 0.05f;
                 if (num13)
                 {
                     velocity.Y -= 0.15f;
                 }
                 velocity.X += vector3.X * 0.2f;
                 if (num11 == num && owner == Main.myPlayer)
                 {
                     Kill();
                     return;
                 }
             }
             break;
         }
         case 1:
         {
             Vector2 vector2 = DirectionTo(vector);
             velocity = Vector2.Lerp(velocity, vector2 * 16f, 1f);
             if (Distance(vector) < 10f && owner == Main.myPlayer)
             {
                 Kill();
                 return;
             }
             break;
         }
         }
         timeLeft = 2;
         Vector2 vector4 = base.Center - vector;
         int dir = ((vector4.X > 0f) ? 1 : (-1));
         if (Math.Abs(vector4.X) > Math.Abs(vector4.Y) / 2f)
         {
             player.ChangeDir(dir);
         }
         Vector2 vector5 = DirectionTo(vector).SafeNormalize(Vector2.Zero);
         if (num8 == 0f && velocity.Y > -0.02f)
         {
             rotation *= 0.95f;
         }
         else
         {
             float num14 = (-vector5).ToRotation() + (float)Math.PI / 4f;
             if (spriteDirection == -1)
             {
                 num14 -= (float)Math.PI / 2f * (float)player.direction;
             }
             rotation = num14 + velocity.X * 0.05f;
         }
         float num15 = velocity.Length();
         switch (type)
         {
         case 771:
         case 822:
         case 823:
         case 827:
         case 830:
         case 838:
         case 843:
         case 844:
         case 845:
         case 846:
         case 850:
         case 852:
             frame = 0;
             break;
         case 828:
         case 829:
             if (num15 < 6f)
             {
                 frame = 1;
             }
             else
             {
                 frame = 0;
             }
             break;
         case 826:
             frame = (int)ai[1];
             break;
         case 824:
         case 839:
         case 840:
         case 853:
             if (num8 < 0.15f)
             {
                 frame = 0;
                 break;
             }
             frameCounter++;
             if ((float)frameCounter > (1f - num8) * 10f)
             {
                 frameCounter = 0;
                 frame = Main.rand.Next(4);
             }
             break;
         default:
             if (num15 < 3f)
             {
                 frame = 0;
             }
             else if (num15 < 5f)
             {
                 frame = 1;
             }
             else if (num15 < 7f)
             {
                 frame = 2;
             }
             else
             {
                 frame = 3;
             }
             break;
         }
         spriteDirection = player.direction;
     }
References Player.CCed, Entity.Center, Player.ChangeDir(), Main.cloudAlpha, Player.dead, Entity.direction, Utils.GetLerpValue(), Main.GlobalTimeWrappedHourly, WorldGen.InAPlaceWithWind(), Player.inventory, Player.MountedCenter, Main.mouseLeft, Main.mouseRight, Main.MouseWorld, Main.myPlayer, UnifiedRandom.Next(), Player.noItems, Main.player, Player.pulley, Main.rand, Player.RotatedRelativePoint(), Player.selectedItem, Item.shoot, and Main.WindForVisuals.