Terraria: Projectile.GetWhipSettings
GetWhipSettings()
static void Projectile.GetWhipSettings (Projectile proj, out float timeToFlyOut, out int segments, out float rangeMultiplier) inline static
     {
         timeToFlyOut = Main.player[proj.owner].itemAnimationMax * proj.MaxUpdates;
         segments = 20;
         rangeMultiplier = 1f;
         switch (proj.type)
         {
         case 913:
             rangeMultiplier *= 1.4f;
             break;
         case 912:
             rangeMultiplier *= 1.5f;
             break;
         case 841:
             rangeMultiplier *= 0.75f;
             break;
         case 914:
             rangeMultiplier *= 1f;
             break;
         case 847:
             segments = 20;
             rangeMultiplier *= 1.75f;
             break;
         case 849:
             segments = 30;
             rangeMultiplier = 2.15f;
             break;
         case 915:
             segments = 40;
             rangeMultiplier = 2.2f;
             break;
         case 848:
             segments = 40;
             rangeMultiplier = 1.6f;
             break;
         case 952:
             rangeMultiplier *= 0.95f;
             break;
         }
     }
References Player.itemAnimationMax, MaxUpdates, owner, Main.player, and type.
Referenced by Main.DrawWhip_WhipBland(), Main.DrawWhip_WhipMace(), and Main.DrawWhip_WhipScythe().