Terraria: Projectile.AI_130_FlameBurstTower_FindTarget
AI_130_FlameBurstTower_FindTarget()
int Projectile.AI_130_FlameBurstTower_FindTarget (float shot_range, float angleRatioMax, Vector2 shootingSpot, bool canChangeDirection = true) inline private
     {
         int num = -1;
         NPC ownerMinionAttackTargetNPC = OwnerMinionAttackTargetNPC;
         if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this))
         {
             for (int i = 0; i < 1; i++)
             {
                 if (!ownerMinionAttackTargetNPC.CanBeChasedBy(this))
                 {
                     continue;
                 }
                 float num2 = Vector2.Distance(shootingSpot, ownerMinionAttackTargetNPC.Center);
                 if (!(num2 > shot_range))
                 {
                     Vector2 vector = (ownerMinionAttackTargetNPC.Center - shootingSpot).SafeNormalize(Vector2.UnitY);
                     if (!(Math.Abs(vector.X) < Math.Abs(vector.Y) * angleRatioMax) && (canChangeDirection || !((float)direction * vector.X < 0f)) && (num == -1 || num2 < Vector2.Distance(shootingSpot, Main.npc[num].Center)) && Collision.CanHitLine(shootingSpot, 0, 0, ownerMinionAttackTargetNPC.Center, 0, 0))
                     {
                         num = ownerMinionAttackTargetNPC.whoAmI;
                     }
                 }
             }
             if (num != -1)
             {
                 return num;
             }
         }
         for (int j = 0; j < 200; j++)
         {
             NPC nPC = Main.npc[j];
             if (!nPC.CanBeChasedBy(this))
             {
                 continue;
             }
             float num3 = Vector2.Distance(shootingSpot, nPC.Center);
             if (!(num3 > shot_range))
             {
                 Vector2 vector2 = (nPC.Center - shootingSpot).SafeNormalize(Vector2.UnitY);
                 if (!(Math.Abs(vector2.X) < Math.Abs(vector2.Y) * angleRatioMax) && (canChangeDirection || !((float)direction * vector2.X < 0f)) && (num == -1 || num3 < Vector2.Distance(shootingSpot, Main.npc[num].Center)) && Collision.CanHitLine(shootingSpot, 0, 0, nPC.Center, 0, 0))
                 {
                     num = j;
                 }
             }
         }
         return num;
     }
References NPC.CanBeChasedBy(), Collision.CanHitLine(), Entity.Center, Entity.Distance(), Main.npc, and Entity.whoAmI.