Terraria: Projectile.AI_169_Smolstars
AI_169_Smolstars()
void Projectile.AI_169_Smolstars () inline private
     {
         Player player = Main.player[owner];
         bool num = type == 864;
         Vector2 vector = player.Top + new Vector2(0f, -30f);
         if (num)
         {
             if (player.dead)
             {
                 player.smolstar = false;
             }
             if (player.smolstar)
             {
                 timeLeft = 2;
             }
             if (ai[0] == 0f)
             {
                 AI_GetMyGroupIndexAndFillBlackList(null, out var index, out var totalIndexesInGroup);
                 float num2 = (float)Math.PI * 2f / (float)totalIndexesInGroup;
                 float num3 = (float)totalIndexesInGroup * 0.66f;
                 Vector2 vector2 = new Vector2(30f, 6f) / 5f * (totalIndexesInGroup - 1);
                 Vector2 vector3 = Vector2.UnitY.RotatedBy(num2 * (float)index + Main.GlobalTimeWrappedHourly % num3 / num3 * ((float)Math.PI * 2f));
                 vector += vector3 * vector2;
                 vector.Y += player.gfxOffY;
                 vector = vector.Floor();
             }
         }
         if (ai[0] == 0f)
         {
             Vector2 vector4 = vector - base.Center;
             float num4 = 10f;
             float lerpValue = Utils.GetLerpValue(200f, 600f, vector4.Length(), clamped: true);
             num4 += lerpValue * 30f;
             if (vector4.Length() >= 3000f)
             {
                 base.Center = vector;
             }
             velocity = vector4;
             if (velocity.Length() > num4)
             {
                 velocity *= num4 / velocity.Length();
             }
             int startAttackRange = 800;
             int attackTarget = -1;
             Minion_FindTargetInRange(startAttackRange, ref attackTarget, skipIfCannotHitWithOwnBody: false);
             if (attackTarget != -1)
             {
                 ai[0] = 60f;
                 ai[1] = attackTarget;
                 netUpdate = true;
             }
             float targetAngle = velocity.SafeNormalize(Vector2.UnitY).ToRotation() + (float)Math.PI / 2f;
             if (vector4.Length() < 40f)
             {
                 targetAngle = Vector2.UnitY.ToRotation() + (float)Math.PI / 2f;
             }
             rotation = rotation.AngleLerp(targetAngle, 0.2f);
             return;
         }
         if (ai[0] == -1f)
         {
             if (ai[1] == 0f)
             {
                 SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                 for (int i = 0; i < 2; i++)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 15, oldVelocity.X * 0.2f, oldVelocity.Y * 0.2f, 0, default(Color), 1.4f);
                     if (Main.rand.Next(3) != 0)
                     {
                         dust.scale *= 1.3f;
                         dust.velocity *= 1.1f;
                     }
                     dust.noGravity = true;
                     dust.fadeIn = 0f;
                 }
                 velocity += Main.rand.NextVector2CircularEdge(4f, 4f);
             }
             ai[1] += 1f;
             rotation += velocity.X * 0.1f + velocity.Y * 0.05f;
             velocity *= 0.92f;
             if (ai[1] >= 9f)
             {
                 ai[0] = 0f;
                 ai[1] = 0f;
             }
             return;
         }
         NPC nPC = null;
         int num5 = (int)ai[1];
         if (Main.npc.IndexInRange(num5) && Main.npc[num5].CanBeChasedBy(this))
         {
             nPC = Main.npc[num5];
         }
         if (nPC == null)
         {
             ai[0] = -1f;
             ai[1] = 0f;
             netUpdate = true;
         }
         else if (player.Distance(nPC.Center) >= 900f)
         {
             ai[0] = 0f;
             ai[1] = 0f;
             netUpdate = true;
         }
         else
         {
             Vector2 vector5 = nPC.Center - base.Center;
             float num6 = 16f;
             velocity = vector5;
             if (velocity.Length() > num6)
             {
                 velocity *= num6 / velocity.Length();
             }
             float targetAngle2 = velocity.SafeNormalize(Vector2.UnitY).ToRotation() + (float)Math.PI / 2f;
             rotation = rotation.AngleLerp(targetAngle2, 0.4f);
         }
         float num7 = 0.1f;
         float num8 = width * 5;
         for (int j = 0; j < 1000; j++)
         {
             if (j != whoAmI && Main.projectile[j].active && Main.projectile[j].owner == owner && Main.projectile[j].type == type && Math.Abs(position.X - Main.projectile[j].position.X) + Math.Abs(position.Y - Main.projectile[j].position.Y) < num8)
             {
                 if (position.X < Main.projectile[j].position.X)
                 {
                     velocity.X -= num7;
                 }
                 else
                 {
                     velocity.X += num7;
                 }
                 if (position.Y < Main.projectile[j].position.Y)
                 {
                     velocity.Y -= num7;
                 }
                 else
                 {
                     velocity.Y += num7;
                 }
             }
         }
     }
References Entity.active, NPC.CanBeChasedBy(), Entity.Center, Color, Player.dead, Entity.Distance(), Dust.fadeIn, Utils.GetLerpValue(), Player.gfxOffY, Main.GlobalTimeWrappedHourly, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.npc, owner, Main.player, SoundEngine.PlaySound(), Entity.position, Main.projectile, Main.rand, Dust.scale, Player.smolstar, Entity.Top, type, and Dust.velocity.