Terraria: Projectile.AI_099_1
AI_099_1()
void Projectile.AI_099_1 () inline private
     {
         timeLeft = 6;
         bool flag = true;
         float num = 250f;
         float num2 = 0.1f;
         float num3 = 15f;
         float num4 = 12f;
         num *= 0.5f;
         num3 *= 0.8f;
         num4 *= 1.5f;
         if (owner == Main.myPlayer)
         {
             bool flag2 = false;
             for (int i = 0; i < 1000; i++)
             {
                 if (Main.projectile[i].active && Main.projectile[i].owner == owner && Main.projectile[i].aiStyle == 99 && (Main.projectile[i].type < 556 || Main.projectile[i].type > 561))
                 {
                     flag2 = true;
                 }
             }
             if (!flag2)
             {
                 ai[0] = -1f;
                 netUpdate = true;
             }
         }
         if (Main.player[owner].yoyoString)
         {
             num += num * 0.25f + 10f;
         }
         rotation += 0.5f;
         if (Main.player[owner].dead)
         {
             Kill();
             return;
         }
         if (!flag)
         {
             Main.player[owner].heldProj = whoAmI;
             Main.player[owner].SetDummyItemTime(2);
             if (position.X + (float)(width / 2) > Main.player[owner].position.X + (float)(Main.player[owner].width / 2))
             {
                 Main.player[owner].ChangeDir(1);
                 direction = 1;
             }
             else
             {
                 Main.player[owner].ChangeDir(-1);
                 direction = -1;
             }
         }
         if (ai[0] == 0f || ai[0] == 1f)
         {
             if (ai[0] == 1f)
             {
                 num *= 0.75f;
             }
             num4 *= 0.5f;
             bool flag3 = false;
             Vector2 vector = Main.player[owner].Center - base.Center;
             if ((double)vector.Length() > (double)num * 0.9)
             {
                 flag3 = true;
             }
             if (vector.Length() > num)
             {
                 float num5 = vector.Length() - num;
                 Vector2 vector2 = default(Vector2);
                 vector2.X = vector.Y;
                 vector2.Y = vector.X;
                 vector.Normalize();
                 vector *= num;
                 position = Main.player[owner].Center - vector;
                 position.X -= width / 2;
                 position.Y -= height / 2;
                 float num6 = velocity.Length();
                 velocity.Normalize();
                 if (num5 > num6 - 1f)
                 {
                     num5 = num6 - 1f;
                 }
                 velocity *= num6 - num5;
                 num6 = velocity.Length();
                 Vector2 vector3 = new Vector2(base.Center.X, base.Center.Y);
                 Vector2 vector4 = new Vector2(Main.player[owner].Center.X, Main.player[owner].Center.Y);
                 if (vector3.Y < vector4.Y)
                 {
                     vector2.Y = Math.Abs(vector2.Y);
                 }
                 else if (vector3.Y > vector4.Y)
                 {
                     vector2.Y = 0f - Math.Abs(vector2.Y);
                 }
                 if (vector3.X < vector4.X)
                 {
                     vector2.X = Math.Abs(vector2.X);
                 }
                 else if (vector3.X > vector4.X)
                 {
                     vector2.X = 0f - Math.Abs(vector2.X);
                 }
                 vector2.Normalize();
                 vector2 *= velocity.Length();
                 new Vector2(vector2.X, vector2.Y);
                 if (Math.Abs(velocity.X) > Math.Abs(velocity.Y))
                 {
                     Vector2 vector5 = velocity;
                     vector5.Y += vector2.Y;
                     vector5.Normalize();
                     vector5 *= velocity.Length();
                     if ((double)Math.Abs(vector2.X) < 0.1 || (double)Math.Abs(vector2.Y) < 0.1)
                     {
                         velocity = vector5;
                     }
                     else
                     {
                         velocity = (vector5 + velocity * 2f) / 3f;
                     }
                 }
                 else
                 {
                     Vector2 vector6 = velocity;
                     vector6.X += vector2.X;
                     vector6.Normalize();
                     vector6 *= velocity.Length();
                     if ((double)Math.Abs(vector2.X) < 0.2 || (double)Math.Abs(vector2.Y) < 0.2)
                     {
                         velocity = vector6;
                     }
                     else
                     {
                         velocity = (vector6 + velocity * 2f) / 3f;
                     }
                 }
             }
             if (Main.myPlayer == owner)
             {
                 if (Main.player[owner].channel)
                 {
                     Vector2 vector7 = new Vector2(Main.mouseX - Main.lastMouseX, Main.mouseY - Main.lastMouseY);
                     if (velocity.X != 0f || velocity.Y != 0f)
                     {
                         if (flag)
{
                             vector7 *= -1f;
                         }
                         if (flag3)
{
                             if (base.Center.X < Main.player[owner].Center.X && vector7.X < 0f)
{
                                 vector7.X = 0f;
                             }
                             if (base.Center.X > Main.player[owner].Center.X && vector7.X > 0f)
{
                                 vector7.X = 0f;
                             }
                             if (base.Center.Y < Main.player[owner].Center.Y && vector7.Y < 0f)
{
                                 vector7.Y = 0f;
                             }
                             if (base.Center.Y > Main.player[owner].Center.Y && vector7.Y > 0f)
{
                                 vector7.Y = 0f;
                             }
                         }
                         velocity += vector7 * num2;
                         netUpdate = true;
                     }
                 }
                 else
                 {
                     ai[0] = -1f;
                     netUpdate = true;
                 }
             }
             if (flag || type == 562 || type == 547 || type == 555 || type == 564 || type == 552 || type == 563 || type == 549 || type == 550 || type == 554 || type == 553 || type == 603 || type == 999)
             {
                 float num7 = 800f;
                 Vector2 vector8 = default(Vector2);
                 bool flag4 = false;
                 if (type == 549)
                 {
                     num7 = 200f;
                 }
                 if (type == 554)
                 {
                     num7 = 400f;
                 }
                 if (type == 553)
                 {
                     num7 = 250f;
                 }
                 if (type == 603)
                 {
                     num7 = 320f;
                 }
                 for (int j = 0; j < 200; j++)
                 {
                     if (Main.npc[j].CanBeChasedBy(this))
                     {
                         float num8 = Main.npc[j].position.X + (float)(Main.npc[j].width / 2);
                         float num9 = Main.npc[j].position.Y + (float)(Main.npc[j].height / 2);
                         float num10 = Math.Abs(position.X + (float)(width / 2) - num8) + Math.Abs(position.Y + (float)(height / 2) - num9);
                         if (num10 < num7 && (type != 563 || !(num10 < 200f)) && Collision.CanHit(position, width, height, Main.npc[j].position, Main.npc[j].width, Main.npc[j].height) && (double)(Main.npc[j].Center - Main.player[owner].Center).Length() < (double)num * 0.9)
{
                             num7 = num10;
                             vector8.X = num8;
                             vector8.Y = num9;
                             flag4 = true;
                         }
                     }
                 }
                 if (flag4)
                 {
                     vector8 -= base.Center;
                     vector8.Normalize();
                     if (type == 563)
                     {
                         vector8 *= 4f;
                         velocity = (velocity * 14f + vector8) / 15f;
                     }
                     else if (type == 553)
                     {
                         vector8 *= 5f;
                         velocity = (velocity * 12f + vector8) / 13f;
                     }
                     else if (type == 603)
                     {
                         vector8 *= 16f;
                         velocity = (velocity * 9f + vector8) / 10f;
                     }
                     else if (type == 554)
                     {
                         vector8 *= 8f;
                         velocity = (velocity * 6f + vector8) / 7f;
                     }
                     else
                     {
                         vector8 *= 6f;
                         velocity = (velocity * 7f + vector8) / 8f;
                     }
                 }
             }
             if (velocity.Length() > num3)
             {
                 velocity.Normalize();
                 velocity *= num3;
             }
             if (velocity.Length() < num4)
             {
                 velocity.Normalize();
                 velocity *= num4;
             }
             return;
         }
         tileCollide = false;
         Vector2 vector9 = Main.player[owner].Center - base.Center;
         float num11 = vector9.Length();
         if (num11 < 40f || vector9.HasNaNs() || num11 > 2000f)
         {
             Kill();
             return;
         }
         float num12 = num3 * 1.5f;
         if (type == 546)
         {
             num12 *= 1.5f;
         }
         if (type == 554)
         {
             num12 *= 1.25f;
         }
         if (type == 555)
         {
             num12 *= 1.35f;
         }
         if (type == 562)
         {
             num12 *= 1.25f;
         }
         float num13 = 12f;
         vector9.Normalize();
         vector9 *= num12;
         velocity = (velocity * (num13 - 1f) + vector9) / num13;
     }
References Entity.active, aiStyle, NPC.CanBeChasedBy(), Collision.CanHit(), Entity.Center, Player.ChangeDir(), Player.channel, Player.dead, Entity.height, Player.heldProj, Main.lastMouseX, Main.lastMouseY, Main.mouseX, Main.mouseY, Main.myPlayer, Main.npc, owner, Main.player, Entity.position, Main.projectile, Player.SetDummyItemTime(), type, Entity.width, and Player.yoyoString.