Terraria: Projectile.AI_162_TigerPounce
AI_162_TigerPounce()
void Projectile.AI_162_TigerPounce () inline private
     {
         if (ai[0] < 0f)
         {
             Opacity = 0f;
             ai[0] += 1f;
             return;
         }
         bool flag = false;
         flag = true;
         if (frameCounter == 0)
         {
             frameCounter = 1;
             localAI[0] = base.Center.X;
             localAI[1] = base.Center.Y;
             flag = true;
         }
         Vector2 vector = new Vector2(localAI[0], localAI[1]);
         Vector2 vector2 = vector + velocity;
         float y = Vector2.Distance(vector, vector2) * 1.5f;
         float num = 0.1f;
         Vector2 value = Vector2.Lerp(vector, vector2, 0f - num) + new Vector2(0f, y);
         Vector2 value2 = Vector2.Lerp(vector, vector2, 1f + num) + new Vector2(0f, y);
         if (Opacity < 1f)
         {
             Opacity += 0.1f;
         }
         int num2 = Math.Sign(vector2.X - vector.X);
         rotation += (float)num2 * -0.2f;
         spriteDirection = num2;
         if (ai[1] < 1f)
         {
             ai[1] = 60f;
         }
         ai[0] += 1f / ai[1];
         Vector2 vector3 = Vector2.CatmullRom(amount: Utils.Clamp(ai[0], 0f, 1f), value1: value, value2: vector, value3: vector2, value4: value2);
         if (flag)
         {
             for (float num3 = 0f; num3 < 1f; num3 += 0.5f)
             {
                 if (Main.rand.Next(19) == 0)
                 {
                     Vector2 vector4 = base.Center + DirectionTo(vector3).SafeNormalize(Vector2.UnitY) * 100f;
                     Dust dust = Dust.NewDustPerfect(base.Center + base.Size * Main.rand.NextVector2Square(0f, 1f), 278, Main.rand.NextVector2Circular(3f, 3f), 100, Color.White * 0.4f);
                     dust.velocity.Y += -0.6f;
                     dust.velocity += velocity * 0.1f;
                     Main.rand.Next(5);
                     dust.velocity = (vector4 - base.Center) * 0.05f;
                     dust.fadeIn = 0f;
                     dust.scale = 0.7f;
                     dust.noGravity = true;
                 }
             }
             if (Main.rand.Next(2) == 0)
             {
                 Dust obj = Main.dust[Dust.NewDust(position, width, height, 269)];
                 obj.fadeIn = 0.7f;
                 obj.scale = 0.4f;
                 obj.velocity += velocity * 0.001f;
                 obj.noLight = true;
             }
         }
         base.Center = vector3;
         if (ai[0] >= 1f)
         {
             Kill();
         }
     }
References Color, Main.dust, Dust.fadeIn, Dust.NewDust(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.rand, Dust.scale, and Dust.velocity.