Terraria: Projectile.UseGasTrapInChest
UseGasTrapInChest()
static void Projectile.UseGasTrapInChest (int chestIndex, Chest theChest, int gasTrapIndex, int gasOffsetX, int gasOffsetY) inline static
     {
         if (Main.netMode == 1)
         {
             return;
         }
         bool flag = false;
         int num = -1;
         for (int i = 0; i < 40; i++)
         {
             Item item = theChest.item[i];
             if (item == null)
             {
                 continue;
             }
             if (item.IsAir)
             {
                 if (num == -1)
                 {
                     num = i;
                 }
             }
             else if (item.type == 5356 && item.stack < item.maxStack)
             {
                 flag = true;
                 item.stack++;
                 if (Main.netMode != 0)
                 {
                     NetMessage.SendData(32, -1, -1, null, chestIndex, i);
                 }
                 break;
             }
         }
         theChest.item[gasTrapIndex].stack--;
         if (theChest.item[gasTrapIndex].stack <= 0)
         {
             if (flag)
             {
                 theChest.item[gasTrapIndex].TurnToAir();
             }
             else
             {
                 flag = true;
                 theChest.item[gasTrapIndex].ChangeItemType(5356);
             }
         }
         if (Main.netMode != 0)
         {
             NetMessage.SendData(32, -1, -1, null, chestIndex, gasTrapIndex);
         }
         if (!flag && num > -1)
         {
             flag = true;
             theChest.item[num].ChangeItemType(5356);
             if (Main.netMode != 0)
             {
                 NetMessage.SendData(32, -1, -1, null, chestIndex, num);
             }
         }
         if (!flag)
         {
             Item.NewItem(pos: new Vector2(theChest.x * 16 + gasOffsetX, theChest.y * 16 + gasOffsetY), source: new EntitySource_OverfullChest(theChest.x, theChest.y, theChest), randomBox: Vector2.One, Type: 5356);
         }
     }
References Item.ChangeItemType(), Item.IsAir, Chest.item, Item.maxStack, Main.netMode, Item.NewItem(), NetMessage.SendData(), Item.stack, Item.TurnToAir(), Item.type, Chest.x, and Chest.y.