Terraria: Projectile.ExplodeTiles
ExplodeTiles()
void Projectile.ExplodeTiles (Vector2 compareSpot, int radius, int minI, int maxI, int minJ, int maxJ, bool wallSplode) inline
     {
         AchievementsHelper.CurrentlyMining = true;
         for (int i = minI; i <= maxI; i++)
         {
             for (int j = minJ; j <= maxJ; j++)
             {
                 float num = Math.Abs((float)i - compareSpot.X / 16f);
                 float num2 = Math.Abs((float)j - compareSpot.Y / 16f);
                 if (!(Math.Sqrt(num * num + num2 * num2) < (double)radius))
                 {
                     continue;
                 }
                 bool flag = true;
                 if (Main.tile[i, j] != null && Main.tile[i, j].active())
                 {
                     flag = CanExplodeTile(i, j);
                     if (flag)
                     {
                         WorldGen.KillTile(i, j);
                         if (!Main.tile[i, j].active() && Main.netMode != 0)
{
                             NetMessage.SendData(17, -1, -1, null, 0, i, j);
                         }
                     }
                 }
                 if (!flag)
                 {
                     continue;
                 }
                 for (int k = i - 1; k <= i + 1; k++)
                 {
                     for (int l = j - 1; l <= j + 1; l++)
                     {
                         if (Main.tile[k, l] != null && Main.tile[k, l].wall > 0 && wallSplode)
{
                             WorldGen.KillWall(k, l);
                             if (Main.tile[k, l].wall == 0 && Main.netMode != 0)
{
                                 NetMessage.SendData(17, -1, -1, null, 2, k, l);
                             }
                         }
                     }
                 }
             }
         }
         AchievementsHelper.CurrentlyMining = false;
     }
References Tile.active(), AchievementsHelper.CurrentlyMining, WorldGen.KillTile(), WorldGen.KillWall(), Main.netMode, NetMessage.SendData(), Main.tile, and Tile.wall.