Terraria: Projectile.AI_015_Flails
AI_015_Flails()
void Projectile.AI_015_Flails () inline private
     {
         Player player = Main.player[owner];
         if (!player.active || player.dead || player.noItems || player.CCed || Vector2.Distance(base.Center, player.Center) > 900f)
         {
             Kill();
             return;
         }
         if (Main.myPlayer == owner && Main.mapFullscreen)
         {
             Kill();
             return;
         }
         if (type == 948 && wet && !lavaWet)
         {
             type = 947;
             netUpdate = true;
         }
         Vector2 mountedCenter = player.MountedCenter;
         bool doFastThrowDust = false;
         bool flag = true;
         bool flag2 = false;
         int num = 10;
         float num2 = 24f;
         float num3 = 800f;
         float num4 = 3f;
         float num5 = 16f;
         float num6 = 6f;
         float num7 = 48f;
         float num8 = 1f;
         float num9 = 14f;
         int num10 = 60;
         int num11 = 10;
         int num12 = 15;
         int num13 = 10;
         int num14 = num + 5;
         switch (type)
         {
         case 947:
         case 948:
             num = 13;
             num2 = 12f;
             num5 = 8f;
             num7 = 13f;
             break;
         case 25:
             num = 15;
             num2 = 14f;
             num5 = 10f;
             num7 = 15f;
             break;
         case 154:
             num = 15;
             num2 = 15f;
             num5 = 11f;
             num7 = 16f;
             break;
         case 26:
             num = 15;
             num2 = 16f;
             num5 = 12f;
             num7 = 16f;
             break;
         case 35:
             num = 15;
             num2 = 17f;
             num5 = 14f;
             num7 = 18f;
             break;
         case 63:
             num = 13;
             num2 = 21f;
             num5 = 20f;
             num7 = 24f;
             num12 = 12;
             break;
         case 757:
             num = 13;
             num2 = 22f;
             num5 = 22f;
             num7 = 26f;
             num12 = 12;
             break;
         case 247:
             num = 13;
             num2 = 23f;
             num12 = 12;
             break;
         }
         float meleeSpeed = player.meleeSpeed;
         float num15 = 1f / meleeSpeed;
         num2 *= num15;
         num8 *= num15;
         num9 *= num15;
         num4 *= num15;
         num5 *= num15;
         num6 *= num15;
         num7 *= num15;
         float num16 = num2 * (float)num;
         float num17 = num16 + 160f;
         localNPCHitCooldown = num11;
         switch ((int)ai[0])
         {
         case 0:
         {
             flag2 = true;
             if (owner == Main.myPlayer)
             {
                 Vector2 origin = mountedCenter;
                 Vector2 mouseWorld = Main.MouseWorld;
                 Vector2 vector3 = origin.DirectionTo(mouseWorld).SafeNormalize(Vector2.UnitX * player.direction);
                 player.ChangeDir((vector3.X > 0f) ? 1 : (-1));
                 if (!player.channel)
                 {
                     ai[0] = 1f;
                     ai[1] = 0f;
                     velocity = vector3 * num2 + player.velocity;
                     base.Center = mountedCenter;
                     netUpdate = true;
                     ResetLocalNPCHitImmunity();
                     localNPCHitCooldown = num13;
                     break;
                 }
             }
             localAI[1] += 1f;
             Vector2 vector4 = new Vector2(player.direction).RotatedBy((float)Math.PI * 10f * (localAI[1] / 60f) * (float)player.direction);
             vector4.Y *= 0.8f;
             if (vector4.Y * player.gravDir > 0f)
             {
                 vector4.Y *= 0.5f;
             }
             base.Center = mountedCenter + vector4 * 30f;
             velocity = Vector2.Zero;
             localNPCHitCooldown = num12;
             break;
         }
         case 1:
         {
             doFastThrowDust = true;
             bool flag3 = ai[1]++ >= (float)num;
             flag3 |= Distance(mountedCenter) >= num3;
             if (player.controlUseItem)
             {
                 ai[0] = 6f;
                 ai[1] = 0f;
                 netUpdate = true;
                 velocity *= 0.2f;
                 if (Main.myPlayer == owner && type == 757)
                 {
                     NewProjectile(GetProjectileSource_FromThis(), base.Center, velocity, 928, damage, knockBack, Main.myPlayer);
                 }
                 break;
             }
             if (flag3)
             {
                 ai[0] = 2f;
                 ai[1] = 0f;
                 netUpdate = true;
                 velocity *= 0.3f;
                 if (Main.myPlayer == owner && type == 757)
                 {
                     NewProjectile(GetProjectileSource_FromThis(), base.Center, velocity, 928, damage, knockBack, Main.myPlayer);
                 }
             }
             player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
             localNPCHitCooldown = num13;
             break;
         }
         case 2:
         {
             Vector2 vector = DirectionTo(mountedCenter).SafeNormalize(Vector2.Zero);
             if (Distance(mountedCenter) <= num5)
             {
                 Kill();
                 return;
             }
             if (player.controlUseItem)
             {
                 ai[0] = 6f;
                 ai[1] = 0f;
                 netUpdate = true;
                 velocity *= 0.2f;
             }
             else
             {
                 velocity *= 0.98f;
                 velocity = velocity.MoveTowards(vector * num5, num4);
                 player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
             }
             break;
         }
         case 3:
         {
             if (!player.controlUseItem)
             {
                 ai[0] = 4f;
                 ai[1] = 0f;
                 netUpdate = true;
                 break;
             }
             float num18 = Distance(mountedCenter);
             tileCollide = ai[1] == 1f;
             bool flag4 = num18 <= num16;
             if (flag4 != tileCollide)
             {
                 tileCollide = flag4;
                 ai[1] = (tileCollide ? 1 : 0);
                 netUpdate = true;
             }
             if (num18 > (float)num10)
             {
                 if (num18 >= num16)
                 {
                     velocity *= 0.5f;
                     velocity = velocity.MoveTowards(DirectionTo(mountedCenter).SafeNormalize(Vector2.Zero) * num9, num9);
                 }
                 velocity *= 0.98f;
                 velocity = velocity.MoveTowards(DirectionTo(mountedCenter).SafeNormalize(Vector2.Zero) * num9, num8);
             }
             else
             {
                 if (velocity.Length() < 6f)
                 {
                     velocity.X *= 0.96f;
                     velocity.Y += 0.2f;
                 }
                 if (player.velocity.X == 0f)
                 {
                     velocity.X *= 0.96f;
                 }
             }
             player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
             break;
         }
         case 4:
         {
             tileCollide = false;
             Vector2 vector2 = DirectionTo(mountedCenter).SafeNormalize(Vector2.Zero);
             if (Distance(mountedCenter) <= num7)
             {
                 Kill();
                 return;
             }
             velocity *= 0.98f;
             velocity = velocity.MoveTowards(vector2 * num7, num6);
             Vector2 target = base.Center + velocity;
             Vector2 value = mountedCenter.DirectionFrom(target).SafeNormalize(Vector2.Zero);
             if (Vector2.Dot(vector2, value) < 0f)
             {
                 Kill();
                 return;
             }
             player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
             break;
         }
         case 5:
             if (ai[1]++ >= (float)num14)
             {
                 ai[0] = 6f;
                 ai[1] = 0f;
                 netUpdate = true;
             }
             else
             {
                 localNPCHitCooldown = num13;
                 velocity.Y += 0.6f;
                 velocity.X *= 0.95f;
                 player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
             }
             break;
         case 6:
             if (!player.controlUseItem || Distance(mountedCenter) > num17)
             {
                 ai[0] = 4f;
                 ai[1] = 0f;
                 netUpdate = true;
                 break;
             }
             if (!shimmerWet)
             {
                 velocity.Y += 0.8f;
             }
             velocity.X *= 0.95f;
             player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
             break;
         }
         int num19 = type;
         if (num19 == 247)
         {
             flag = false;
             float num20 = (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.01f;
             rotation += ((velocity.X > 0f) ? num20 : (0f - num20));
             if (ai[0] == 0f)
             {
                 rotation += (float)Math.PI * 2f / 15f * (float)player.direction;
             }
             float num21 = 600f;
             NPC nPC = null;
             if (owner == Main.myPlayer)
             {
                 localAI[0] += 1f;
                 if (localAI[0] >= 20f)
                 {
                     localAI[0] = 17f;
                     for (int i = 0; i < 200; i++)
                     {
                         NPC nPC2 = Main.npc[i];
                         if (nPC2.CanBeChasedBy(this))
{
                             float num22 = Distance(nPC2.Center);
                             if (!(num22 >= num21) && Collision.CanHit(position, width, height, nPC2.position, nPC2.width, nPC2.height))
{
                                 nPC = nPC2;
                                 num21 = num22;
                             }
                         }
                     }
                 }
                 if (nPC != null)
                 {
                     localAI[0] = 0f;
                     float num23 = 14f;
                     Vector2 center = base.Center;
                     Vector2 vector5 = center.DirectionTo(nPC.Center) * num23;
                     NewProjectile(GetProjectileSource_FromThis(), center, vector5, 248, (int)((double)damage / 1.5), knockBack / 2f, Main.myPlayer);
                 }
             }
         }
         direction = ((velocity.X > 0f) ? 1 : (-1));
         spriteDirection = direction;
         ownerHitCheck = flag2;
         if (flag)
         {
             if (velocity.Length() > 1f)
             {
                 rotation = velocity.ToRotation() + velocity.X * 0.1f;
             }
             else
             {
                 rotation += velocity.X * 0.1f;
             }
         }
         timeLeft = 2;
         player.heldProj = whoAmI;
         player.SetDummyItemTime(2);
         player.itemRotation = DirectionFrom(mountedCenter).ToRotation();
         if (base.Center.X < mountedCenter.X)
         {
             player.itemRotation += (float)Math.PI;
         }
         player.itemRotation = MathHelper.WrapAngle(player.itemRotation);
         AI_015_Flails_Dust(doFastThrowDust);
     }
References Entity.active, NPC.CanBeChasedBy(), Collision.CanHit(), Player.CCed, Entity.Center, Player.ChangeDir(), Player.channel, Player.controlUseItem, Player.dead, Entity.direction, Player.gravDir, Entity.height, Player.heldProj, Player.itemRotation, Main.mapFullscreen, Player.meleeSpeed, Player.MountedCenter, Main.MouseWorld, Main.myPlayer, Player.noItems, Main.npc, Main.player, Entity.position, Player.SetDummyItemTime(), Entity.velocity, and Entity.width.