Terraria: Projectile.AI_001
AI_001()
void Projectile.AI_001 () inline private
     {
         //IL_21ea: Unknown result type (might be due to invalid IL or missing references)
         //IL_5a4d: Unknown result type (might be due to invalid IL or missing references)
         //IL_5967: Unknown result type (might be due to invalid IL or missing references)
         //IL_596c: Unknown result type (might be due to invalid IL or missing references)
         //IL_5a73: Unknown result type (might be due to invalid IL or missing references)
         //IL_5a78: Unknown result type (might be due to invalid IL or missing references)
         //IL_7f9f: Unknown result type (might be due to invalid IL or missing references)
         //IL_81c4: Unknown result type (might be due to invalid IL or missing references)
         if (type == 469 && wet && !honeyWet && !shimmerWet)
         {
             Kill();
         }
         if (type == 601)
         {
             Color portalColor = PortalHelper.GetPortalColor(owner, (int)ai[0]);
             Vector3 rgb = portalColor.ToVector3();
             rgb *= 0.5f;
             Lighting.AddLight(base.Center + velocity * 3f, rgb);
             if (alpha > 0 && alpha <= 15)
             {
                 Color color = portalColor;
                 color.A = byte.MaxValue;
                 for (int i = 0; i < 4; i++)
                 {
                     Dust obj = Main.dust[Dust.NewDust(base.Center, 0, 0, 264)];
                     obj.position = base.Center;
                     obj.velocity = velocity * 2f + Utils.RandomVector2(Main.rand, -1f, 1f);
                     obj.color = color;
                     obj.scale = 1.2f;
                     obj.noLight = true;
                     obj.noGravity = true;
                     obj.customData = Main.player[owner];
                 }
                 if (ai[0] != 0f)
                 {
                     SoundEngine.PlaySound(SoundID.Item114, position);
                 }
                 else
                 {
                     SoundEngine.PlaySound(SoundID.Item115, position);
                 }
             }
             alpha -= 15;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (++frameCounter >= 4)
             {
                 frameCounter = 0;
                 if (++frame >= Main.projFrames[type])
                 {
                     frame = 0;
                 }
             }
             if (alpha == 0)
             {
                 Color color2 = portalColor;
                 color2.A = byte.MaxValue;
                 Dust obj2 = Main.dust[Dust.NewDust(base.Center, 0, 0, 263)];
                 obj2.position = base.Center;
                 obj2.velocity = velocity / 4f;
                 obj2.color = color2;
                 obj2.noGravity = true;
                 obj2.scale = 0.6f;
             }
         }
         if (type == 472)
         {
             int num = Dust.NewDust(position, width, height, 30);
             Main.dust[num].noGravity = true;
             Main.dust[num].velocity *= 0.25f;
             Main.dust[num].velocity += velocity * 0.75f;
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(SoundID.Item17, position);
                 for (int j = 0; j < 20; j++)
                 {
                     num = Dust.NewDust(position, width, height, 30);
                     Main.dust[num].noGravity = true;
                     Main.dust[num].velocity *= 0.25f;
                     Main.dust[num].velocity += velocity;
                     Main.dust[num].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                     Main.dust[num].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                 }
             }
         }
         if (type == 323)
         {
             alpha -= 50;
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         if (type == 436)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item12, position);
             }
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             frameCounter++;
             if (frameCounter >= 3)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= 4)
                 {
                     frame = 0;
                 }
             }
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.3f, 1.1f, 0.5f);
         }
         if (type == 467)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item34, position);
             }
             else if (ai[1] == 1f && Main.netMode != 1)
             {
                 int num2 = -1;
                 float num3 = 2000f;
                 for (int k = 0; k < 255; k++)
                 {
                     if (Main.player[k].active && !Main.player[k].dead)
                     {
                         Vector2 center = Main.player[k].Center;
                         float num4 = Vector2.Distance(center, base.Center);
                         if ((num4 < num3 || num2 == -1) && Collision.CanHit(base.Center, 1, 1, center, 1, 1))
{
                             num3 = num4;
                             num2 = k;
                         }
                     }
                 }
                 if (num3 < 20f)
                 {
                     Kill();
                     return;
                 }
                 if (num2 != -1)
                 {
                     ai[1] = 21f;
                     ai[0] = num2;
                     netUpdate = true;
                 }
             }
             else if (ai[1] > 20f && ai[1] < 200f)
             {
                 ai[1] += 1f;
                 int num5 = (int)ai[0];
                 if (!Main.player[num5].active || Main.player[num5].dead)
                 {
                     ai[1] = 1f;
                     ai[0] = 0f;
                     netUpdate = true;
                 }
                 else
                 {
                     float num6 = velocity.ToRotation();
                     Vector2 vector = Main.player[num5].Center - base.Center;
                     if (vector.Length() < 20f)
                     {
                         Kill();
                         return;
                     }
                     float targetAngle = vector.ToRotation();
                     if (vector == Vector2.Zero)
                     {
                         targetAngle = num6;
                     }
                     float num7 = num6.AngleLerp(targetAngle, 0.008f);
                     velocity = new Vector2(velocity.Length(), 0f).RotatedBy(num7);
                 }
             }
             if (ai[1] >= 1f && ai[1] < 20f)
             {
                 ai[1] += 1f;
                 if (ai[1] == 20f)
                 {
                     ai[1] = 1f;
                 }
             }
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             frameCounter++;
             if (frameCounter >= 3)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= 4)
                 {
                     frame = 0;
                 }
             }
             Lighting.AddLight(base.Center, 1.1f, 0.9f, 0.4f);
             localAI[0] += 1f;
             if (localAI[0] == 12f)
             {
                 localAI[0] = 0f;
                 for (int l = 0; l < 12; l++)
                 {
                     Vector2 spinningpoint = Vector2.UnitX * -width / 2f;
                     spinningpoint += -Vector2.UnitY.RotatedBy((float)l * (float)Math.PI / 6f) * new Vector2(8f, 16f);
                     spinningpoint = spinningpoint.RotatedBy(rotation - (float)Math.PI / 2f);
                     int num8 = Dust.NewDust(base.Center, 0, 0, 6, 0f, 0f, 160);
                     Main.dust[num8].scale = 1.1f;
                     Main.dust[num8].noGravity = true;
                     Main.dust[num8].position = base.Center + spinningpoint;
                     Main.dust[num8].velocity = velocity * 0.1f;
                     Main.dust[num8].velocity = Vector2.Normalize(base.Center - velocity * 3f - Main.dust[num8].position) * 1.25f;
                 }
             }
             if (Main.rand.Next(4) == 0)
             {
                 for (int m = 0; m < 1; m++)
                 {
                     Vector2 vector2 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy(velocity.ToRotation());
                     int num9 = Dust.NewDust(position, width, height, 31, 0f, 0f, 100);
                     Main.dust[num9].velocity *= 0.1f;
                     Main.dust[num9].position = base.Center + vector2 * width / 2f;
                     Main.dust[num9].fadeIn = 0.9f;
                 }
             }
             if (Main.rand.Next(32) == 0)
             {
                 for (int n = 0; n < 1; n++)
                 {
                     Vector2 vector3 = -Vector2.UnitX.RotatedByRandom(0.39269909262657166).RotatedBy(velocity.ToRotation());
                     int num10 = Dust.NewDust(position, width, height, 31, 0f, 0f, 155, default(Color), 0.8f);
                     Main.dust[num10].velocity *= 0.3f;
                     Main.dust[num10].position = base.Center + vector3 * width / 2f;
                     if (Main.rand.Next(2) == 0)
                     {
                         Main.dust[num10].fadeIn = 1.4f;
                     }
                 }
             }
             if (Main.rand.Next(2) == 0)
             {
                 for (int num11 = 0; num11 < 2; num11++)
                 {
                     Vector2 vector4 = -Vector2.UnitX.RotatedByRandom(0.7853981852531433).RotatedBy(velocity.ToRotation());
                     int num12 = Dust.NewDust(position, width, height, 6, 0f, 0f, 0, default(Color), 1.2f);
                     Main.dust[num12].velocity *= 0.3f;
                     Main.dust[num12].noGravity = true;
                     Main.dust[num12].position = base.Center + vector4 * width / 2f;
                     if (Main.rand.Next(2) == 0)
                     {
                         Main.dust[num12].fadeIn = 1.4f;
                     }
                 }
             }
         }
         if (type == 468)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item34, position);
             }
             else if (ai[1] == 1f && Main.netMode != 1)
             {
                 int num13 = -1;
                 float num14 = 2000f;
                 for (int num15 = 0; num15 < 255; num15++)
                 {
                     if (Main.player[num15].active && !Main.player[num15].dead)
                     {
                         Vector2 center2 = Main.player[num15].Center;
                         float num16 = Vector2.Distance(center2, base.Center);
                         if ((num16 < num14 || num13 == -1) && Collision.CanHit(base.Center, 1, 1, center2, 1, 1))
{
                             num14 = num16;
                             num13 = num15;
                         }
                     }
                 }
                 if (num14 < 20f)
                 {
                     Kill();
                     return;
                 }
                 if (num13 != -1)
                 {
                     ai[1] = 21f;
                     ai[0] = num13;
                     netUpdate = true;
                 }
             }
             else if (ai[1] > 20f && ai[1] < 200f)
             {
                 ai[1] += 1f;
                 int num17 = (int)ai[0];
                 if (!Main.player[num17].active || Main.player[num17].dead)
                 {
                     ai[1] = 1f;
                     ai[0] = 0f;
                     netUpdate = true;
                 }
                 else
                 {
                     float num18 = velocity.ToRotation();
                     Vector2 vector5 = Main.player[num17].Center - base.Center;
                     if (vector5.Length() < 20f)
                     {
                         Kill();
                         return;
                     }
                     float targetAngle2 = vector5.ToRotation();
                     if (vector5 == Vector2.Zero)
                     {
                         targetAngle2 = num18;
                     }
                     float num19 = num18.AngleLerp(targetAngle2, 0.01f);
                     velocity = new Vector2(velocity.Length(), 0f).RotatedBy(num19);
                 }
             }
             if (ai[1] >= 1f && ai[1] < 20f)
             {
                 ai[1] += 1f;
                 if (ai[1] == 20f)
                 {
                     ai[1] = 1f;
                 }
             }
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             frameCounter++;
             if (frameCounter >= 3)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= 4)
                 {
                     frame = 0;
                 }
             }
             Lighting.AddLight(base.Center, 0.2f, 0.1f, 0.6f);
             localAI[0] += 1f;
             if (localAI[0] == 12f)
             {
                 localAI[0] = 0f;
                 for (int num20 = 0; num20 < 12; num20++)
                 {
                     Vector2 spinningpoint2 = Vector2.UnitX * -width / 2f;
                     spinningpoint2 += -Vector2.UnitY.RotatedBy((float)num20 * (float)Math.PI / 6f) * new Vector2(8f, 16f);
                     spinningpoint2 = spinningpoint2.RotatedBy(rotation - (float)Math.PI / 2f);
                     int num21 = Dust.NewDust(base.Center, 0, 0, 27, 0f, 0f, 160);
                     Main.dust[num21].scale = 1.1f;
                     Main.dust[num21].noGravity = true;
                     Main.dust[num21].position = base.Center + spinningpoint2;
                     Main.dust[num21].velocity = velocity * 0.1f;
                     Main.dust[num21].velocity = Vector2.Normalize(base.Center - velocity * 3f - Main.dust[num21].position) * 1.25f;
                 }
             }
             if (Main.rand.Next(4) == 0)
             {
                 for (int num22 = 0; num22 < 1; num22++)
                 {
                     Vector2 vector6 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy(velocity.ToRotation());
                     int num23 = Dust.NewDust(position, width, height, 31, 0f, 0f, 100);
                     Main.dust[num23].velocity *= 0.1f;
                     Main.dust[num23].position = base.Center + vector6 * width / 2f;
                     Main.dust[num23].fadeIn = 0.9f;
                 }
             }
             if (Main.rand.Next(32) == 0)
             {
                 for (int num24 = 0; num24 < 1; num24++)
                 {
                     Vector2 vector7 = -Vector2.UnitX.RotatedByRandom(0.39269909262657166).RotatedBy(velocity.ToRotation());
                     int num25 = Dust.NewDust(position, width, height, 31, 0f, 0f, 155, default(Color), 0.8f);
                     Main.dust[num25].velocity *= 0.3f;
                     Main.dust[num25].position = base.Center + vector7 * width / 2f;
                     if (Main.rand.Next(2) == 0)
                     {
                         Main.dust[num25].fadeIn = 1.4f;
                     }
                 }
             }
             if (Main.rand.Next(2) == 0)
             {
                 for (int num26 = 0; num26 < 2; num26++)
                 {
                     Vector2 vector8 = -Vector2.UnitX.RotatedByRandom(0.7853981852531433).RotatedBy(velocity.ToRotation());
                     int num27 = Dust.NewDust(position, width, height, 27, 0f, 0f, 0, default(Color), 1.2f);
                     Main.dust[num27].velocity *= 0.3f;
                     Main.dust[num27].noGravity = true;
                     Main.dust[num27].position = base.Center + vector8 * width / 2f;
                     if (Main.rand.Next(2) == 0)
                     {
                         Main.dust[num27].fadeIn = 1.4f;
                     }
                 }
             }
         }
         if (type == 634 || type == 635)
         {
             float num28 = 5f;
             float num29 = 250f;
             float num30 = 6f;
             Vector2 vector9 = new Vector2(8f, 10f);
             float num31 = 1.2f;
             Vector3 rgb2 = new Vector3(0.7f, 0.1f, 0.5f);
             int num32 = 4 * MaxUpdates;
             int num33 = Utils.SelectRandom<int>(Main.rand, 242, 73, 72, 71, 255);
             int num34 = 255;
             if (type == 635)
             {
                 vector9 = new Vector2(10f, 20f);
                 num31 = 1f;
                 num29 = 500f;
                 num34 = 88;
                 num32 = 3 * MaxUpdates;
                 rgb2 = new Vector3(0.4f, 0.6f, 0.9f);
                 num33 = Utils.SelectRandom<int>(Main.rand, 242, 59, 88);
             }
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 localAI[0] = -Main.rand.Next(48);
                 SoundEngine.PlaySound(SoundID.Item34, position);
             }
             else if (ai[1] == 1f && owner == Main.myPlayer)
             {
                 int num35 = -1;
                 float num36 = num29;
                 for (int num37 = 0; num37 < 200; num37++)
                 {
                     if (Main.npc[num37].active && Main.npc[num37].CanBeChasedBy(this))
                     {
                         Vector2 center3 = Main.npc[num37].Center;
                         float num38 = Vector2.Distance(center3, base.Center);
                         if (num38 < num36 && num35 == -1 && Collision.CanHitLine(base.Center, 1, 1, center3, 1, 1))
{
                             num36 = num38;
                             num35 = num37;
                         }
                     }
                 }
                 if (num36 < 20f)
                 {
                     Kill();
                     return;
                 }
                 if (num35 != -1)
                 {
                     ai[1] = num28 + 1f;
                     ai[0] = num35;
                     netUpdate = true;
                 }
             }
             else if (ai[1] > num28)
             {
                 ai[1] += 1f;
                 int num39 = (int)ai[0];
                 if (!Main.npc[num39].active || !Main.npc[num39].CanBeChasedBy(this))
                 {
                     ai[1] = 1f;
                     ai[0] = 0f;
                     netUpdate = true;
                 }
                 else
                 {
                     velocity.ToRotation();
                     Vector2 vector10 = Main.npc[num39].Center - base.Center;
                     if (vector10.Length() < 20f)
                     {
                         Kill();
                         return;
                     }
                     if (vector10 != Vector2.Zero)
                     {
                         vector10.Normalize();
                         vector10 *= num30;
                     }
                     float num40 = 30f;
                     velocity = (velocity * (num40 - 1f) + vector10) / num40;
                 }
             }
             if (ai[1] >= 1f && ai[1] < num28)
             {
                 ai[1] += 1f;
                 if (ai[1] == num28)
                 {
                     ai[1] = 1f;
                 }
             }
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             frameCounter++;
             if (frameCounter >= num32)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= 4)
                 {
                     frame = 0;
                 }
             }
             Lighting.AddLight(base.Center, rgb2);
             rotation = velocity.ToRotation();
             localAI[0] += 1f;
             if (localAI[0] == 48f)
             {
                 localAI[0] = 0f;
             }
             else if (alpha == 0)
             {
                 for (int num41 = 0; num41 < 2; num41++)
                 {
                     Vector2 vector11 = Vector2.UnitX * -30f;
                     vector11 = -Vector2.UnitY.RotatedBy(localAI[0] * ((float)Math.PI / 24f) + (float)num41 * (float)Math.PI) * vector9 - rotation.ToRotationVector2() * 10f;
                     int num42 = Dust.NewDust(base.Center, 0, 0, num34, 0f, 0f, 160);
                     Main.dust[num42].scale = num31;
                     Main.dust[num42].noGravity = true;
                     Main.dust[num42].position = base.Center + vector11 + velocity * 2f;
                     Main.dust[num42].velocity = Vector2.Normalize(base.Center + velocity * 2f * 8f - Main.dust[num42].position) * 2f + velocity * 2f;
                 }
             }
             if (Main.rand.Next(12) == 0)
             {
                 for (int num43 = 0; num43 < 1; num43++)
                 {
                     Vector2 vector12 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy(velocity.ToRotation());
                     int num44 = Dust.NewDust(position, width, height, 31, 0f, 0f, 100);
                     Main.dust[num44].velocity *= 0.1f;
                     Main.dust[num44].position = base.Center + vector12 * width / 2f + velocity * 2f;
                     Main.dust[num44].fadeIn = 0.9f;
                 }
             }
             if (Main.rand.Next(64) == 0)
             {
                 for (int num45 = 0; num45 < 1; num45++)
                 {
                     Vector2 vector13 = -Vector2.UnitX.RotatedByRandom(0.39269909262657166).RotatedBy(velocity.ToRotation());
                     int num46 = Dust.NewDust(position, width, height, 31, 0f, 0f, 155, default(Color), 0.8f);
                     Main.dust[num46].velocity *= 0.3f;
                     Main.dust[num46].position = base.Center + vector13 * width / 2f;
                     if (Main.rand.Next(2) == 0)
                     {
                         Main.dust[num46].fadeIn = 1.4f;
                     }
                 }
             }
             if (Main.rand.Next(4) == 0)
             {
                 for (int num47 = 0; num47 < 2; num47++)
                 {
                     Vector2 vector14 = -Vector2.UnitX.RotatedByRandom(0.7853981852531433).RotatedBy(velocity.ToRotation());
                     int num48 = Dust.NewDust(position, width, height, num33, 0f, 0f, 0, default(Color), 1.2f);
                     Main.dust[num48].velocity *= 0.3f;
                     Main.dust[num48].noGravity = true;
                     Main.dust[num48].position = base.Center + vector14 * width / 2f;
                     if (Main.rand.Next(2) == 0)
                     {
                         Main.dust[num48].fadeIn = 1.4f;
                     }
                 }
             }
             if (Main.rand.Next(12) == 0 && type == 634)
             {
                 Vector2 vector15 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy(velocity.ToRotation());
                 int num49 = Dust.NewDust(position, width, height, num34, 0f, 0f, 100);
                 Main.dust[num49].velocity *= 0.3f;
                 Main.dust[num49].position = base.Center + vector15 * width / 2f;
                 Main.dust[num49].fadeIn = 0.9f;
                 Main.dust[num49].noGravity = true;
             }
             if (Main.rand.Next(3) == 0 && type == 635)
             {
                 Vector2 vector16 = -Vector2.UnitX.RotatedByRandom(0.19634954631328583).RotatedBy(velocity.ToRotation());
                 int num50 = Dust.NewDust(position, width, height, num34, 0f, 0f, 100);
                 Main.dust[num50].velocity *= 0.3f;
                 Main.dust[num50].position = base.Center + vector16 * width / 2f;
                 Main.dust[num50].fadeIn = 1.2f;
                 Main.dust[num50].scale = 1.5f;
                 Main.dust[num50].noGravity = true;
             }
         }
         if (type == 459)
         {
             alpha -= 30;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             frameCounter++;
             if (frameCounter >= 3)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= 3)
                 {
                     frame = 0;
                 }
             }
             position = base.Center;
             scale = ai[1];
             width = (height = (int)(22f * scale));
             base.Center = position;
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 0.85f, 0.9f);
             int num51 = 0;
             if ((double)scale < 0.85)
             {
                 num51 = ((Main.rand.Next(3) == 0) ? 1 : 0);
             }
             else
             {
                 num51 = 1;
                 penetrate = -1;
                 maxPenetrate = -1;
             }
             for (int num52 = 0; num52 < num51; num52++)
             {
                 int num53 = Dust.NewDust(position, width, height, 226, velocity.X);
                 Main.dust[num53].position -= Vector2.One * 3f;
                 Main.dust[num53].scale = 0.5f;
                 Main.dust[num53].noGravity = true;
                 Main.dust[num53].velocity = velocity / 3f;
                 Main.dust[num53].alpha = 255 - (int)(255f * scale);
             }
         }
         if (type == 709)
         {
             alpha -= 30;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             frameCounter++;
             if (frameCounter >= 3)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= 3)
                 {
                     frame = 0;
                 }
             }
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 0.85f, 0.9f);
             if (ai[1] == 0f)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_SkyDragonsFuryShot, base.Center);
             }
             ai[1] += 1f;
             if (ai[1] >= 30f)
             {
                 Kill();
                 return;
             }
         }
         if (type == 442)
         {
             frame = 0;
             if (alpha != 0)
             {
                 localAI[0] += 1f;
                 if (localAI[0] >= 4f)
                 {
                     alpha -= 90;
                     if (alpha < 0)
                     {
                         alpha = 0;
                         localAI[0] = 2f;
                     }
                 }
             }
             if (Vector2.Distance(base.Center, new Vector2(ai[0], ai[1]) * 16f + Vector2.One * 8f) <= 16f)
             {
                 Kill();
                 return;
             }
             if (alpha == 0)
             {
                 localAI[1] += 1f;
                 if (localAI[1] >= 120f)
                 {
                     Kill();
                     return;
                 }
                 Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.3f, 0.45f, 0.8f);
                 localAI[0] += 1f;
                 if (localAI[0] == 3f)
                 {
                     localAI[0] = 0f;
                     for (int num54 = 0; num54 < 8; num54++)
                     {
                         Vector2 spinningpoint3 = Vector2.UnitX * -8f;
                         spinningpoint3 += -Vector2.UnitY.RotatedBy((float)num54 * (float)Math.PI / 4f) * new Vector2(2f, 4f);
                         spinningpoint3 = spinningpoint3.RotatedBy(rotation - (float)Math.PI / 2f);
                         int num55 = Dust.NewDust(base.Center, 0, 0, 135);
                         Main.dust[num55].scale = 1.5f;
                         Main.dust[num55].noGravity = true;
                         Main.dust[num55].position = base.Center + spinningpoint3;
                         Main.dust[num55].velocity = velocity * 0.66f;
                     }
                 }
             }
         }
         if (type == 440 || type == 449 || type == 606)
         {
             if (alpha > 0)
             {
                 alpha -= 25;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (type == 440)
             {
                 Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.25f, 0.4f, 0.7f);
             }
             if (type == 449)
             {
                 Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.7f, 0.65f, 0.3f);
             }
             if (type == 606)
             {
                 Lighting.AddLight(base.Center, 0.7f, 0.3f, 0.3f);
             }
             float num56 = 100f;
             float num57 = 3f;
             if (type == 606)
             {
                 num56 = 150f;
                 num57 = 5f;
             }
             if (ai[1] == 0f)
             {
                 localAI[0] += num57;
                 if (localAI[0] == num57 * 1f && type == 606)
                 {
                     for (int num58 = 0; num58 < 4; num58++)
                     {
                         int num59 = Dust.NewDust(base.Center - velocity / 2f, 0, 0, 182, 0f, 0f, 100, default(Color), 1.4f);
                         Main.dust[num59].velocity *= 0.2f;
                         Main.dust[num59].velocity += velocity / 10f;
                         Main.dust[num59].noGravity = true;
                     }
                 }
                 if (localAI[0] > num56)
                 {
                     localAI[0] = num56;
                 }
             }
             else
             {
                 localAI[0] -= num57;
                 if (localAI[0] <= 0f)
                 {
                     Kill();
                     return;
                 }
             }
         }
         if (type == 438)
         {
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 0.1f, 0.2f);
         }
         if (type == 593)
         {
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 0.1f, 0.3f);
             if (++frameCounter >= 12)
             {
                 if (++frame >= Main.projFrames[type])
                 {
                     frame = 0;
                 }
                 frameCounter = 0;
             }
             if (Main.rand.Next(2) == 0)
             {
                 Vector2 vector17 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                 Dust obj3 = Main.dust[Dust.NewDust(base.Center - vector17 * 8f, 0, 0, 240)];
                 obj3.noGravity = true;
                 obj3.position = base.Center - vector17 * 8f * scale;
                 obj3.velocity = vector17.RotatedBy(-1.5707963705062866) * 2f;
                 obj3.velocity = Vector2.Zero;
                 obj3.scale = 0.5f + Main.rand.NextFloat();
                 obj3.fadeIn = 0.5f;
             }
         }
         if (type == 592)
         {
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.15f, 0.15f, 0.4f);
         }
         if (type == 462)
         {
             int num60 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100);
             Main.dust[num60].noLight = true;
             Main.dust[num60].noGravity = true;
             Main.dust[num60].velocity = velocity;
             Main.dust[num60].position -= Vector2.One * 4f;
             Main.dust[num60].scale = 0.8f;
             if (++frameCounter >= 9)
             {
                 frameCounter = 0;
                 if (++frame >= 5)
                 {
                     frame = 0;
                 }
             }
         }
         if (type == 437)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item12, position);
             }
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 for (int num61 = 0; num61 < 4; num61++)
                 {
                     int num62 = Dust.NewDust(position, width, height, 226, velocity.X);
                     Main.dust[num62].position = Vector2.Lerp(Main.dust[num62].position, base.Center, 0.25f);
                     Main.dust[num62].scale = 0.5f;
                     Main.dust[num62].noGravity = true;
                     Main.dust[num62].velocity /= 2f;
                     Main.dust[num62].velocity += velocity * 0.66f;
                 }
             }
             if (ai[0] < 16f)
             {
                 for (int num63 = 0; num63 < 2; num63++)
                 {
                     int num64 = Dust.NewDust(position, width, height, 226, velocity.X);
                     Main.dust[num64].position = position + new Vector2(((direction == 1) ? 1 : 0) * width, 2 + (height - 4) * num63);
                     Main.dust[num64].scale = 0.3f;
                     Main.dust[num64].noGravity = true;
                     Main.dust[num64].velocity = Vector2.Zero;
                 }
             }
         }
         if (type == 435)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item12, position);
             }
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             frameCounter++;
             if (frameCounter >= 3)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= 4)
                 {
                     frame = 0;
                 }
             }
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.3f, 0.8f, 1.1f);
         }
         if (type == 682)
         {
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.DD2_LightningBugZap, position);
                 for (int num65 = 0; num65 < 8; num65++)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 272);
                     dust.velocity *= 1f;
                     dust.velocity += velocity * 0.65f;
                     dust.scale = 0.6f;
                     dust.fadeIn = 0.8f;
                     dust.noGravity = true;
                     dust.noLight = true;
                     dust.position += dust.velocity * 3f;
                 }
             }
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             frameCounter++;
             if (frameCounter >= 3)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= 4)
                 {
                     frame = 0;
                 }
             }
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.5f, 0.2f, 1.1f);
         }
         if (type == 684)
         {
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
             localAI[0] += 1f;
             for (int num66 = 0; num66 < 1; num66++)
             {
                 Vector2 spinningpoint4 = Utils.RandomVector2(Main.rand, -0.5f, 0.5f) * new Vector2(20f, 80f);
                 spinningpoint4 = spinningpoint4.RotatedBy(velocity.ToRotation());
                 Dust dust2 = Dust.NewDustDirect(base.Center, 0, 0, 60);
                 dust2.alpha = 127;
                 dust2.fadeIn = 1.5f;
                 dust2.scale = 1.3f;
                 dust2.velocity *= 0.3f;
                 dust2.position = base.Center + spinningpoint4;
                 dust2.noGravity = true;
                 dust2.noLight = true;
                 dust2.color = new Color(255, 255, 255, 0);
             }
             Lighting.AddLight(base.Center, 1.1f, 0.3f, 0.4f);
         }
         if (type == 408)
         {
             alpha -= 40;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             spriteDirection = direction;
         }
         if (type == 282)
         {
             int num67 = Dust.NewDust(position, width, height, 171, 0f, 0f, 100);
             Main.dust[num67].scale = (float)Main.rand.Next(1, 10) * 0.1f;
             Main.dust[num67].noGravity = true;
             Main.dust[num67].fadeIn = 1.5f;
             Main.dust[num67].velocity *= 0.25f;
             Main.dust[num67].velocity += velocity * 0.25f;
         }
         if (type == 275 || type == 276)
         {
             frameCounter++;
             if (frameCounter > 1)
             {
                 frameCounter = 0;
                 frame++;
                 if (frame > 1)
                 {
                     frame = 0;
                 }
             }
         }
         if (type == 225 && Main.rand.Next(2) == 0)
         {
             int num68 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 40);
             Main.dust[num68].noGravity = true;
             Main.dust[num68].scale = 1.3f;
             Main.dust[num68].velocity *= 0.5f;
         }
         if (type == 174)
         {
             if (alpha == 0)
             {
                 int num69 = Dust.NewDust(oldPosition - velocity * 3f, width, height, 76, 0f, 0f, 50);
                 Main.dust[num69].noGravity = true;
                 Main.dust[num69].noLight = true;
                 Main.dust[num69].velocity *= 0.5f;
             }
             alpha -= 50;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item17, position);
             }
         }
         else if (type == 605 || type == 920 || type == 921 || type == 926 || type == 937)
         {
             if (type == 920 && frameCounter == 0)
             {
                 frameCounter = 1;
                 frame = Main.rand.Next(3);
             }
             if (type != 920 && type != 921 && alpha == 0 && Main.rand.Next(3) == 0)
             {
                 int num70 = 4;
                 Color newColor = new Color(78, 136, 255, 150);
                 float num71 = 1.2f;
                 bool noGravity = true;
                 int num72 = 0;
                 if (type == 921)
                 {
                     num70 = 243;
                     newColor = default(Color);
                 }
                 if (type == 926)
                 {
                     num70 = 4;
                     newColor = NPC.AI_121_QueenSlime_GetDustColor();
                     newColor.A = 150;
                     num71 = 1.2f;
                     num72 = 8;
                     noGravity = Main.rand.Next(2) == 0;
                 }
                 if (type == 937)
                 {
                     num70 = 4;
                     newColor = NPC.AI_121_QueenSlime_GetDustColor();
                     newColor.A = 150;
                 }
                 int num73 = Dust.NewDust(position - new Vector2(num72, num72) + velocity, width + num72 * 2, height + num72 * 2, num70, 0f, 0f, 50, newColor, num71);
                 Main.dust[num73].velocity *= 0.3f;
                 Main.dust[num73].velocity += velocity * 0.3f;
                 Main.dust[num73].noGravity = noGravity;
             }
             alpha -= 50;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (type != 937 && ai[1] == 0f)
             {
                 ai[1] = 1f;
                 if (type == 926)
                 {
                     SoundEngine.PlaySound(SoundID.Item155, position);
                 }
                 else
                 {
                     SoundEngine.PlaySound(SoundID.Item154, position);
                 }
             }
         }
         else if (type == 176)
         {
             if (alpha == 0)
             {
                 int num74 = Dust.NewDust(oldPosition, width, height, 22, 0f, 0f, 100, default(Color), 0.5f);
                 Main.dust[num74].noGravity = true;
                 Main.dust[num74].noLight = true;
                 Main.dust[num74].velocity *= 0.15f;
                 Main.dust[num74].fadeIn = 0.8f;
             }
             alpha -= 50;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item17, position);
             }
         }
         if (type == 350)
         {
             alpha -= 100;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.9f, 0.6f, 0.2f);
             if (alpha == 0)
             {
                 int num75 = 2;
                 if (Main.rand.Next(3) != 0)
                 {
                     int num76 = Dust.NewDust(new Vector2(base.Center.X - (float)num75, base.Center.Y - (float)num75 - 2f) - velocity * 0.5f, num75 * 2, num75 * 2, 6, 0f, 0f, 100);
                     Main.dust[num76].scale *= 1.3f + (float)Main.rand.Next(10) * 0.05f;
                     Main.dust[num76].velocity *= 0.2f;
                     Main.dust[num76].noGravity = true;
                     Main.dust[num76].noLight = true;
                     Main.dust[num76].velocity += velocity * 0.25f;
                 }
                 if (Main.rand.Next(4) == 0)
                 {
                     int num77 = (num77 = Dust.NewDust(new Vector2(base.Center.X - (float)num75, base.Center.Y - (float)num75 - 2f) - velocity * 0.5f, num75 * 2, num75 * 2, 31, 0f, 0f, 100, default(Color), 0.5f));
                     Main.dust[num77].fadeIn = 0.6f + (float)Main.rand.Next(5) * 0.1f;
                     Main.dust[num77].velocity *= 0.05f;
                     Main.dust[num77].velocity += velocity * 0.25f;
                 }
             }
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item42, position);
             }
         }
         if (type == 325)
         {
             alpha -= 100;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.9f, 0.6f, 0.2f);
             if (alpha == 0)
             {
                 int num78 = 2;
                 if (Main.rand.Next(3) != 0)
                 {
                     int num79 = Dust.NewDust(new Vector2(base.Center.X - (float)num78, base.Center.Y - (float)num78 - 2f) - velocity * 0.5f, num78 * 2, num78 * 2, 6, 0f, 0f, 100);
                     Main.dust[num79].scale *= 1.2f + (float)Main.rand.Next(10) * 0.05f;
                     Main.dust[num79].velocity *= 0.2f;
                     Main.dust[num79].noGravity = true;
                     Main.dust[num79].noLight = true;
                     Main.dust[num79].velocity += velocity * 0.25f;
                 }
                 if (Main.rand.Next(4) == 0)
                 {
                     int num80 = (num80 = Dust.NewDust(new Vector2(base.Center.X - (float)num78, base.Center.Y - (float)num78 - 2f) - velocity * 0.5f, num78 * 2, num78 * 2, 31, 0f, 0f, 100, default(Color), 0.5f));
                     Main.dust[num80].fadeIn = 0.5f + (float)Main.rand.Next(5) * 0.05f;
                     Main.dust[num80].velocity *= 0.05f;
                 }
             }
             if (ai[1] == 0f)
             {
                 ai[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item42, position);
             }
         }
         if (type == 469)
         {
             localAI[1] += 1f;
             if (localAI[1] > 2f)
             {
                 alpha -= 50;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
         }
         else if (type == 83 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item33, position);
         }
         else if (type == 408 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(4, (int)position.X, (int)position.Y, 19);
         }
         else if (type == 259 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item33, position);
         }
         else if (type == 110 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item11, position);
         }
         else if (type == 302 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item11, position);
         }
         else if (type == 438 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item12, position);
         }
         else if (type == 593 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item11, position);
         }
         else if (type == 592 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item12, position);
         }
         else if (type == 462 && ai[1] == 0f)
         {
             ai[1] = 1f;
             if (Main.rand.Next(2) == 0)
             {
                 SoundEngine.PlaySound(SoundID.Item124, position);
             }
             else
             {
                 SoundEngine.PlaySound(SoundID.Item125, position);
             }
             Vector2 vector18 = Vector2.Normalize(velocity);
             int num81 = Main.rand.Next(5, 10);
             for (int num82 = 0; num82 < num81; num82++)
             {
                 int num83 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100);
                 Main.dust[num83].velocity.Y -= 1f;
                 Main.dust[num83].velocity += vector18 * 2f;
                 Main.dust[num83].position -= Vector2.One * 4f;
                 Main.dust[num83].noGravity = true;
             }
         }
         else if (type == 84 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item12, position);
         }
         else if (type == 389 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item12, position);
         }
         else if (type == 257 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item12, position);
         }
         else if (type == 100 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item33, position);
         }
         else if (type == 98 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item17, position);
         }
         else if (type == 184 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item17, position);
         }
         else if (type == 980 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item17, position);
         }
         else if (type == 195 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item17, position);
         }
         else if (type == 275 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item17, position);
         }
         else if (type == 276 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item17, position);
         }
         else if ((type == 81 || type == 82) && ai[1] == 0f)
         {
             SoundEngine.PlaySound(SoundID.Item5, position);
             ai[1] = 1f;
         }
         else if (type == 180 && ai[1] == 0f)
         {
             SoundEngine.PlaySound(SoundID.Item11, position);
             ai[1] = 1f;
         }
         else if (type == 248 && ai[1] == 0f)
         {
             SoundEngine.PlaySound(SoundID.Item17, position);
             ai[1] = 1f;
         }
         else if (type == 576 && ai[1] == 0f)
         {
             ai[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item12, position);
         }
         else if (type == 577 && soundDelay == 0)
         {
             soundDelay = -1;
             SoundEngine.PlaySound(SoundID.Item36, position);
             for (int num84 = 0; num84 < 5; num84++)
             {
                 Vector2 center4 = base.Center;
                 int num85 = ((num84 != 0) ? 3 : 0);
                 float num86 = ((num84 == 0) ? (12f + 8f * Main.rand.NextFloat()) : (12f * Main.rand.NextFloat()));
                 Vector2 vector19 = velocity.SafeNormalize(Vector2.Zero) * num86 + Main.rand.NextVector2Circular(1f, 1f) * num85;
                 Dust obj4 = Main.dust[Dust.NewDust(center4, 8, 8, 229, 0f, 0f, 100, Color.Transparent, 1f + Main.rand.NextFloat() * 0.5f)];
                 obj4.noGravity = true;
                 obj4.velocity = vector19;
                 obj4.position = center4;
             }
         }
         else if (type == 710)
         {
             alpha -= 25;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (Main.rand.Next(4) == 0)
             {
                 int num87;
                 if (Main.rand.Next(2) == 0)
                 {
                     num87 = Dust.NewDust(position, width, height, 31, 0f, 0f, 100, default(Color), 1.6f);
                     Main.dust[num87].noGravity = true;
                 }
                 num87 = Dust.NewDust(position, width, height, 6, 0f, 0f, 100, default(Color), 1.2f);
                 Main.dust[num87].noGravity = true;
                 Main.dust[num87].velocity *= 2f;
                 Main.dust[num87].velocity += velocity;
                 if (ai[1] == -1f)
                 {
                     Main.dust[num87].fadeIn = 1.5f;
                 }
                 else
                 {
                     Main.dust[num87].fadeIn = 1.22f;
                 }
                 if (wet)
                 {
                     Kill();
                 }
             }
         }
         else if (type == 639)
         {
             if (localAI[0] == 0f && localAI[1] == 0f)
             {
                 localAI[0] = base.Center.X;
                 localAI[1] = base.Center.Y;
                 ai[0] = velocity.X;
                 ai[1] = velocity.Y;
             }
             alpha -= 25;
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         else if (type == 640)
         {
             alpha -= 25;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (velocity == Vector2.Zero)
             {
                 ai[0] = 0f;
                 bool flag = true;
                 for (int num88 = 1; num88 < oldPos.Length; num88++)
                 {
                     if (oldPos[num88] != oldPos[0])
                     {
                         flag = false;
                     }
                 }
                 if (flag)
                 {
                     Kill();
                     return;
                 }
                 if (Main.rand.Next(extraUpdates) == 0 && (velocity != Vector2.Zero || Main.rand.Next((localAI[1] == 2f) ? 2 : 6) == 0))
                 {
                     for (int num89 = 0; num89 < 2; num89++)
                     {
                         float num90 = rotation + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                         float num91 = (float)Main.rand.NextDouble() * 0.8f + 1f;
                         Vector2 vector20 = new Vector2((float)Math.Cos(num90) * num91, (float)Math.Sin(num90) * num91);
                         int num92 = Dust.NewDust(base.Center, 0, 0, 229, vector20.X, vector20.Y);
                         Main.dust[num92].noGravity = true;
                         Main.dust[num92].scale = 1.2f;
                     }
                     if (Main.rand.Next(10) == 0)
                     {
                         Vector2 vector21 = velocity.RotatedBy(1.5707963705062866) * ((float)Main.rand.NextDouble() - 0.5f) * width;
                         int num93 = Dust.NewDust(base.Center + vector21 - Vector2.One * 4f, 8, 8, 31, 0f, 0f, 100, default(Color), 1.5f);
                         Main.dust[num93].velocity *= 0.5f;
                         Main.dust[num93].velocity.Y = 0f - Math.Abs(Main.dust[num93].velocity.Y);
                     }
                 }
             }
             else if (numUpdates == 1)
             {
                 float num94 = rotation + (float)Math.PI / 2f + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                 float num95 = (float)Main.rand.NextDouble() * 0.25f + 0.25f;
                 Vector2 vector22 = new Vector2((float)Math.Cos(num94) * num95, (float)Math.Sin(num94) * num95);
                 int num96 = Dust.NewDust(position, 0, 0, 229, vector22.X, vector22.Y);
                 Main.dust[num96].noGravity = true;
                 Main.dust[num96].scale = 1.2f;
             }
         }
         if (type == 41)
         {
             int num97 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.6f);
             Main.dust[num97].noGravity = true;
             num97 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2f);
             Main.dust[num97].noGravity = true;
         }
         else if (type == 55)
         {
             int num98 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 18, 0f, 0f, 0, default(Color), 0.9f);
             Main.dust[num98].noGravity = true;
         }
         else if (type == 719)
         {
             if (Main.rand.Next(2) == 0)
             {
                 Dust.NewDustDirect(position - velocity, width, height, 147, 0f, 0f, 0, default(Color), 0.9f).noGravity = true;
             }
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 for (int num99 = 0; num99 < 20; num99++)
                 {
                     Dust dust3 = Dust.NewDustDirect(position - velocity, width, height, 147, 0f, 0f, 0, default(Color), 1.3f);
                     dust3.noGravity = true;
                     dust3.velocity += velocity * 0.75f;
                 }
                 for (int num100 = 0; num100 < 10; num100++)
                 {
                     Dust dust4 = Dust.NewDustDirect(position - velocity, width, height, 147, 0f, 0f, 0, default(Color), 1.3f);
                     dust4.noGravity = true;
                     dust4.velocity *= 2f;
                 }
             }
         }
         else if (type == 763)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 for (int num101 = 0; num101 < 5; num101++)
                 {
                     Dust dust5 = Dust.NewDustDirect(position - velocity, width, height, 40, 0f, 0f, 0, default(Color), 1.1f);
                     dust5.noGravity = true;
                     dust5.velocity *= 1.5f;
                 }
             }
         }
         else if (type == 772)
         {
             if (Main.rand.Next(7) == 0)
             {
                 for (int num102 = 0; num102 < 1; num102++)
                 {
                     Dust dust6 = Dust.NewDustDirect(position - velocity, width, height, Main.rand.NextFromList<int>(86, 87, 88, 89, 90, 91, 138), 0f, 0f, 0, default(Color), 0.7f);
                     dust6.noGravity = true;
                     dust6.velocity = velocity * 0.6f;
                     dust6.fadeIn = 0.8f;
                 }
             }
         }
         else if (type == 374)
         {
             if (localAI[0] == 0f)
             {
                 SoundEngine.PlaySound(SoundID.Item17, position);
                 localAI[0] = 1f;
             }
             if (Main.rand.Next(2) == 0)
             {
                 int num103 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 18, 0f, 0f, 0, default(Color), 0.9f);
                 Main.dust[num103].noGravity = true;
                 Main.dust[num103].velocity *= 0.5f;
             }
         }
         else if (type == 376)
         {
             if (localAI[0] == 0f)
             {
                 SoundEngine.PlaySound(SoundID.Item20, position);
             }
             localAI[0] += 1f;
             if (localAI[0] > 3f)
             {
                 int num104 = 1;
                 if (localAI[0] > 5f)
                 {
                     num104 = 2;
                 }
                 for (int num105 = 0; num105 < num104; num105++)
                 {
                     int num106 = Dust.NewDust(new Vector2(position.X, position.Y + 2f), width, height, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 2f);
                     Main.dust[num106].noGravity = true;
                     Main.dust[num106].velocity.X *= 0.3f;
                     Main.dust[num106].velocity.Y *= 0.3f;
                     Main.dust[num106].noLight = true;
                 }
                 if (wet && !lavaWet)
                 {
                     Kill();
                     return;
                 }
             }
         }
         else if (type == 91 && Main.rand.Next(2) == 0)
         {
             int num108 = Dust.NewDust(Type: (Main.rand.Next(2) != 0) ? 58 : 15, Position: position, Width: width, Height: height, SpeedX: velocity.X * 0.25f, SpeedY: velocity.Y * 0.25f, Alpha: 150, newColor: default(Color), Scale: 0.9f);
             Main.dust[num108].velocity *= 0.25f;
         }
         if (type == 163 || type == 310 || type == 1008 || type == 1010 || type == 1009 || type == 1011)
         {
             if (alpha > 0)
             {
                 alpha -= 25;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         switch (type)
         {
         case 14:
         case 20:
         case 36:
         case 83:
         case 84:
         case 89:
         case 100:
         case 104:
         case 110:
         case 158:
         case 159:
         case 160:
         case 161:
         case 180:
         case 279:
         case 283:
         case 284:
         case 285:
         case 286:
         case 287:
         case 389:
             if (alpha > 0)
             {
                 alpha -= 15;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             break;
         case 576:
         case 577:
             localAI[1] += 1f;
             if (localAI[1] > 2f)
             {
                 if (alpha > 0)
                 {
                     alpha -= 15;
                 }
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
             break;
         }
         if (type == 484)
         {
             int num109 = Dust.NewDust(position, width, height, 78);
             Main.dust[num109].noGravity = true;
             Main.dust[num109].velocity *= 0.1f;
             Main.dust[num109].scale = 0.75f;
             Main.dust[num109].position = (Main.dust[num109].position + base.Center) / 2f;
             Main.dust[num109].position += velocity * Main.rand.Next(0, 101) * 0.01f;
         }
         if (type == 242 || type == 302 || type == 438 || type == 462 || type == 592)
         {
             float num110 = (float)Math.Sqrt(velocity.X * velocity.X + velocity.Y * velocity.Y);
             if (alpha > 0)
             {
                 alpha -= (byte)((double)num110 * 0.9);
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         if (type == 660)
         {
             DelegateMethods.v3_1 = new Vector3(0.6f, 1f, 1f) * 0.2f;
             Utils.PlotTileLine(base.Center, base.Center + velocity * 10f, 8f, DelegateMethods.CastLightOpen);
             if (alpha > 0)
             {
                 SoundEngine.PlaySound(SoundID.Item9, base.Center);
                 alpha = 0;
                 scale = 1.1f;
                 frame = Main.rand.Next(14);
                 float num111 = 16f;
                 for (int num112 = 0; (float)num112 < num111; num112++)
                 {
                     Vector2 spinningpoint5 = Vector2.UnitX * 0f;
                     spinningpoint5 += -Vector2.UnitY.RotatedBy((float)num112 * ((float)Math.PI * 2f / num111)) * new Vector2(1f, 4f);
                     spinningpoint5 = spinningpoint5.RotatedBy(velocity.ToRotation());
                     int num113 = Dust.NewDust(base.Center, 0, 0, 180);
                     Main.dust[num113].scale = 1.5f;
                     Main.dust[num113].noGravity = true;
                     Main.dust[num113].position = base.Center + spinningpoint5;
                     Main.dust[num113].velocity = velocity * 0f + spinningpoint5.SafeNormalize(Vector2.UnitY) * 1f;
                 }
             }
         }
         if (type == 712)
         {
             DelegateMethods.v3_1 = new Vector3(0.4f, 0.4f, 0.4f) * 0.7f;
             Utils.PlotTileLine(base.Center, base.Center + velocity * 10f, 8f, DelegateMethods.CastLightOpen);
             if (alpha == 255)
             {
                 frame = Main.rand.Next(2) * 4;
             }
             if (++frameCounter >= 4)
             {
                 frameCounter = 0;
                 frame++;
                 if (frame == 4)
                 {
                     frame = 0;
                 }
                 if (frame >= 8)
                 {
                     frame = 4;
                 }
             }
             if (alpha > 0)
             {
                 alpha = 0;
                 scale = 1.1f;
                 frame = Main.rand.Next(14);
                 float num114 = 4f;
                 for (int num115 = 0; (float)num115 < num114; num115++)
                 {
                     Vector2 spinningpoint6 = Vector2.UnitX * 0f;
                     spinningpoint6 += -Vector2.UnitY.RotatedBy((float)num115 * ((float)Math.PI * 2f / num114)) * new Vector2(1f, 4f);
                     spinningpoint6 = spinningpoint6.RotatedBy(velocity.ToRotation());
                     int num116 = Dust.NewDust(base.Center, 0, 0, 15);
                     Main.dust[num116].scale = 1.7f;
                     Main.dust[num116].noGravity = true;
                     Main.dust[num116].position = base.Center + spinningpoint6 + velocity.SafeNormalize(Vector2.Zero) * 50f;
                     Main.dust[num116].velocity = Main.dust[num116].velocity * 2f + spinningpoint6.SafeNormalize(Vector2.UnitY) * 0.3f + velocity.SafeNormalize(Vector2.Zero) * 3f;
                     Main.dust[num116].velocity *= 0.7f;
                     Main.dust[num116].position += Main.dust[num116].velocity * 5f;
                 }
             }
         }
         if (type == 661)
         {
             if (alpha <= 0)
             {
                 for (int num117 = 0; num117 < 3; num117++)
                 {
                     int num118 = Dust.NewDust(position, width, height, 240);
                     Main.dust[num118].noGravity = true;
                     Main.dust[num118].velocity *= 0.3f;
                     Main.dust[num118].noLight = true;
                 }
             }
             if (alpha > 0)
             {
                 alpha -= 55;
                 scale = 1.3f;
                 if (alpha < 0)
                 {
                     alpha = 0;
                     float num119 = 16f;
                     for (int num120 = 0; (float)num120 < num119; num120++)
                     {
                         Vector2 spinningpoint7 = Vector2.UnitX * 0f;
                         spinningpoint7 += -Vector2.UnitY.RotatedBy((float)num120 * ((float)Math.PI * 2f / num119)) * new Vector2(1f, 4f);
                         spinningpoint7 = spinningpoint7.RotatedBy(velocity.ToRotation());
                         int num121 = Dust.NewDust(base.Center, 0, 0, 62);
                         Main.dust[num121].scale = 1.5f;
                         Main.dust[num121].noLight = true;
                         Main.dust[num121].noGravity = true;
                         Main.dust[num121].position = base.Center + spinningpoint7;
                         Main.dust[num121].velocity = Main.dust[num121].velocity * 4f + velocity * 0.3f;
                     }
                 }
             }
         }
         if (type == 706)
         {
             if (wet)
             {
                 Kill();
                 return;
             }
             SlotId val;
             if (localAI[1] == 0f)
             {
                 float[] array = localAI;
                 val = SoundEngine.PlayTrackedSound(SoundID.DD2_PhantomPhoenixShot, base.Center);
                 array[0] = ((SlotId)(ref val)).ToFloat();
                 localAI[1] += 1f;
                 for (int num122 = 0; num122 < 15; num122++)
                 {
                     if (Main.rand.Next(4) != 0)
                     {
                         Dust dust7 = Dust.NewDustDirect(base.Center - base.Size / 4f, width / 2, height / 2, Utils.SelectRandom<int>(Main.rand, 6, 31, 31));
                         dust7.noGravity = true;
                         dust7.velocity *= 2.3f;
                         dust7.fadeIn = 1.5f;
                         dust7.noLight = true;
                     }
                 }
             }
             ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[0]));
             if (activeSound != null)
             {
                 activeSound.Position = base.Center;
             }
             else
             {
                 float[] array2 = localAI;
                 val = SlotId.Invalid;
                 array2[0] = ((SlotId)(ref val)).ToFloat();
             }
             if (alpha <= 0)
             {
                 for (int num123 = 0; num123 < 2; num123++)
                 {
                     if (Main.rand.Next(4) != 0)
                     {
                         Dust dust8 = Dust.NewDustDirect(base.Center - base.Size / 4f, width / 2, height / 2, Utils.SelectRandom<int>(Main.rand, 6, 31, 31));
                         dust8.noGravity = true;
                         dust8.velocity *= 2.3f;
                         dust8.fadeIn = 1.5f;
                         dust8.noLight = true;
                     }
                 }
                 Vector2 spinningpoint8 = new Vector2(0f, (float)Math.Cos((float)frameCounter * ((float)Math.PI * 2f) / 40f - (float)Math.PI / 2f)) * 16f;
                 spinningpoint8 = spinningpoint8.RotatedBy(rotation);
                 Vector2 vector23 = velocity.SafeNormalize(Vector2.Zero);
                 for (int num124 = 0; num124 < 1; num124++)
                 {
                     Dust dust9 = Dust.NewDustDirect(base.Center - base.Size / 4f, width / 2, height / 2, 6);
                     dust9.noGravity = true;
                     dust9.position = base.Center + spinningpoint8;
                     dust9.velocity *= 0f;
                     dust9.fadeIn = 1.4f;
                     dust9.scale = 1.15f;
                     dust9.noLight = true;
                     dust9.position += velocity * 1.2f;
                     dust9.velocity += vector23 * 2f;
                     Dust dust10 = Dust.NewDustDirect(base.Center - base.Size / 4f, width / 2, height / 2, 6);
                     dust10.noGravity = true;
                     dust10.position = base.Center + spinningpoint8;
                     dust10.velocity *= 0f;
                     dust10.fadeIn = 1.4f;
                     dust10.scale = 1.15f;
                     dust10.noLight = true;
                     dust10.position += velocity * 0.5f;
                     dust10.position += velocity * 1.2f;
                     dust10.velocity += vector23 * 2f;
                 }
             }
             if (++frameCounter >= 40)
             {
                 frameCounter = 0;
             }
             frame = frameCounter / 5;
             if (alpha > 0)
             {
                 alpha -= 55;
                 if (alpha < 0)
                 {
                     alpha = 0;
                     float num125 = 16f;
                     for (int num126 = 0; (float)num126 < num125; num126++)
                     {
                         Vector2 spinningpoint9 = Vector2.UnitX * 0f;
                         spinningpoint9 += -Vector2.UnitY.RotatedBy((float)num126 * ((float)Math.PI * 2f / num125)) * new Vector2(1f, 4f);
                         spinningpoint9 = spinningpoint9.RotatedBy(velocity.ToRotation());
                         int num127 = Dust.NewDust(base.Center, 0, 0, 6);
                         Main.dust[num127].scale = 1.5f;
                         Main.dust[num127].noLight = true;
                         Main.dust[num127].noGravity = true;
                         Main.dust[num127].position = base.Center + spinningpoint9;
                         Main.dust[num127].velocity = Main.dust[num127].velocity * 4f + velocity * 0.3f;
                     }
                 }
             }
             DelegateMethods.v3_1 = new Vector3(1f, 0.6f, 0.2f);
             Utils.PlotTileLine(base.Center, base.Center + velocity * 4f, 40f, DelegateMethods.CastLightOpen);
         }
         if (type == 638)
         {
             float num128 = velocity.Length();
             if (alpha > 0)
             {
                 alpha -= (byte)((double)num128 * 0.3);
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             Rectangle hitbox = base.Hitbox;
             hitbox.Offset((int)velocity.X, (int)velocity.Y);
             bool flag2 = false;
             for (int num129 = 0; num129 < 200; num129++)
             {
                 NPC nPC = Main.npc[num129];
                 if (nPC.active && !nPC.dontTakeDamage && nPC.immune[owner] == 0 && localNPCImmunity[num129] == 0 && nPC.Hitbox.Intersects(hitbox) && !nPC.friendly)
                 {
                     flag2 = true;
                     break;
                 }
             }
             if (flag2)
             {
                 int num130 = Main.rand.Next(15, 31);
                 for (int num131 = 0; num131 < num130; num131++)
                 {
                     int num132 = Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, default(Color), 0.8f);
                     Main.dust[num132].velocity *= 1.6f;
                     Main.dust[num132].velocity.Y -= 1f;
                     Main.dust[num132].velocity += velocity;
                     Main.dust[num132].noGravity = true;
                 }
             }
         }
         if (type == 257 || type == 593)
         {
             if (alpha > 0)
             {
                 alpha -= 10;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         if (type == 876)
         {
             if (ai[1] == 0f)
             {
                 tileCollide = true;
             }
             else
             {
                 tileCollide = false;
             }
             if (alpha > 0)
             {
                 alpha -= 10;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         if (type == 88)
         {
             if (alpha > 0)
             {
                 alpha -= 10;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         if (type == 532)
         {
             ai[0] += 1f;
         }
         bool flag3 = true;
         bool flag4 = false;
         switch (type)
         {
         case 5:
         case 14:
         case 20:
         case 36:
         case 38:
         case 55:
         case 83:
         case 84:
         case 88:
         case 89:
         case 98:
         case 100:
         case 104:
         case 110:
         case 158:
         case 159:
         case 160:
         case 161:
         case 180:
         case 184:
         case 242:
         case 248:
         case 257:
         case 259:
         case 265:
         case 270:
         case 279:
         case 283:
         case 284:
         case 285:
         case 286:
         case 287:
         case 299:
         case 302:
         case 323:
         case 325:
         case 348:
         case 349:
         case 350:
         case 355:
         case 374:
         case 376:
         case 389:
         case 435:
         case 436:
         case 438:
         case 440:
         case 442:
         case 449:
         case 459:
         case 462:
         case 467:
         case 468:
         case 469:
         case 472:
         case 483:
         case 484:
         case 485:
         case 498:
         case 576:
         case 577:
         case 585:
         case 592:
         case 593:
         case 601:
         case 606:
         case 616:
         case 634:
         case 635:
         case 638:
         case 639:
         case 660:
         case 661:
         case 682:
         case 684:
         case 706:
         case 709:
         case 710:
         case 712:
         case 876:
         case 980:
         case 981:
             flag3 = false;
             break;
         case 1006:
             flag4 = true;
             break;
         }
         if (flag3)
         {
             ai[0] += 1f;
         }
         if (type == 1006 && Main.rand.Next(8) == 0)
         {
             Dust dust11 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(4f, 4f), 306, velocity * 1.25f, 0, Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f), 1f + Main.rand.NextFloat() * 0.4f);
             dust11.noGravity = true;
             dust11.fadeIn = dust11.scale + 0.05f;
             Dust dust12 = Dust.CloneDust(dust11);
             dust12.color = Color.White;
             dust12.scale -= 0.3f;
         }
         if (type == 270)
         {
             int num133 = 0;
             num133 = Player.FindClosest(base.Center, 1, 1);
             ai[1] += 1f;
             if (ai[1] < 110f && ai[1] > 30f)
             {
                 float num134 = velocity.Length();
                 Vector2 vector24 = Main.player[num133].Center - base.Center;
                 vector24.Normalize();
                 vector24 *= num134;
                 velocity = (velocity * 24f + vector24) / 25f;
                 velocity.Normalize();
                 velocity *= num134;
             }
             if (velocity.Length() < 18f)
             {
                 velocity *= 1.02f;
             }
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(SoundID.Item8, position);
                 for (int num135 = 0; num135 < 10; num135++)
                 {
                     int num136 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 5, velocity.X, velocity.Y, 0, default(Color), 2f);
                     Main.dust[num136].noGravity = true;
                     Main.dust[num136].velocity = base.Center - Main.dust[num136].position;
                     Main.dust[num136].velocity.Normalize();
                     Main.dust[num136].velocity *= -5f;
                     Main.dust[num136].velocity += velocity / 2f;
                 }
             }
         }
         if (type == 585)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(SoundID.Item8, position);
                 for (int num137 = 0; num137 < 3; num137++)
                 {
                     int num138 = Dust.NewDust(position, width, height, 27, velocity.X, velocity.Y, 0, default(Color), 2f);
                     Main.dust[num138].noGravity = true;
                     Main.dust[num138].velocity = base.Center - Main.dust[num138].position;
                     Main.dust[num138].velocity.Normalize();
                     Main.dust[num138].velocity *= -5f;
                     Main.dust[num138].velocity += velocity / 2f;
                     Main.dust[num138].noLight = true;
                 }
             }
             if (alpha > 0)
             {
                 alpha -= 50;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             frameCounter++;
             if (frameCounter >= 12)
             {
                 frameCounter = 0;
             }
             frame = frameCounter / 2;
             if (frame > 3)
             {
                 frame = 6 - frame;
             }
             Vector3 vector25 = NPCID.Sets.MagicAuraColor[54].ToVector3();
             Lighting.AddLight(base.Center, vector25.X, vector25.Y, vector25.Z);
             if (Main.rand.Next(3) == 0)
             {
                 int num139 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, 27, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 2f);
                 Main.dust[num139].position -= velocity * 2f;
                 Main.dust[num139].noLight = true;
                 Main.dust[num139].noGravity = true;
                 Main.dust[num139].velocity.X *= 0.3f;
                 Main.dust[num139].velocity.Y *= 0.3f;
             }
         }
         if (type == 594)
         {
             int num140 = (int)(43f - ai[1]) / 13;
             if (num140 < 1)
             {
                 num140 = 1;
             }
             int num141 = ((ai[1] < 20f) ? 6 : 31);
             for (int num142 = 0; num142 < num140; num142++)
             {
                 int num143 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, num141, velocity.X * 0.2f, velocity.Y * 0.2f, 0, default(Color), 2f);
                 Main.dust[num143].position -= velocity * 2f;
                 Main.dust[num143].noLight = true;
                 Main.dust[num143].noGravity = true;
                 Main.dust[num143].velocity.X *= 0.3f;
                 Main.dust[num143].velocity.Y *= 0.3f;
                 if (num141 == 6)
                 {
                     Main.dust[num143].fadeIn = Main.rand.NextFloat() * 2f;
                 }
             }
             ai[1] += 1f;
             if (ai[1] > (float)(43 * MaxUpdates))
             {
                 Kill();
                 return;
             }
         }
         if (type == 622)
         {
             int num144 = 229;
             if (Main.rand.Next(3) != 0)
             {
                 int num145 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, num144, velocity.X * 0.2f, velocity.Y * 0.2f, 0, default(Color), 1.2f);
                 Main.dust[num145].position -= velocity * 2f;
                 Main.dust[num145].noLight = true;
                 Main.dust[num145].noGravity = true;
                 Main.dust[num145].velocity.X *= 0.3f;
                 Main.dust[num145].velocity.Y *= 0.3f;
             }
             ai[1] += 1f;
             if (ai[1] > (float)(23 * MaxUpdates))
             {
                 Kill();
                 return;
             }
         }
         if (type == 587)
         {
             Color newColor2 = Main.hslToRgb(ai[1], 1f, 0.5f);
             newColor2.A = 200;
             localAI[0] += 1f;
             if (!(localAI[0] < 2f))
             {
                 if (localAI[0] == 2f)
                 {
                     SoundEngine.PlaySound(SoundID.Item5, position);
                     for (int num146 = 0; num146 < 4; num146++)
                     {
                         int num147 = Dust.NewDust(position, width, height, 76, velocity.X, velocity.Y, 0, newColor2, 1.1f);
                         Main.dust[num147].noGravity = true;
                         Main.dust[num147].velocity = base.Center - Main.dust[num147].position;
                         Main.dust[num147].velocity.Normalize();
                         Main.dust[num147].velocity *= -3f;
                         Main.dust[num147].velocity += velocity / 2f;
                     }
                 }
                 else
                 {
                     frame++;
                     if (frame > 2)
                     {
                         frame = 0;
                     }
                     for (int num148 = 0; num148 < 1; num148++)
                     {
                         int num149 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, 76, velocity.X * 0.2f, velocity.Y * 0.2f, 0, newColor2, 0.9f);
                         Main.dust[num149].position = base.Center;
                         Main.dust[num149].noGravity = true;
                         Main.dust[num149].velocity = velocity * 0.5f;
                     }
                 }
             }
         }
         if (type == 349)
         {
             frame = (int)ai[0];
             velocity.Y += 0.2f;
             if (localAI[0] == 0f || localAI[0] == 2f)
             {
                 scale += 0.01f;
                 alpha -= 50;
                 if (alpha <= 0)
                 {
                     localAI[0] = 1f;
                     alpha = 0;
                 }
             }
             else if (localAI[0] == 1f)
             {
                 scale -= 0.01f;
                 alpha += 50;
                 if (alpha >= 255)
                 {
                     localAI[0] = 2f;
                     alpha = 255;
                 }
             }
         }
         if (type == 348)
         {
             if (localAI[1] == 0f)
             {
                 localAI[1] = 1f;
                 SoundEngine.PlaySound(SoundID.Item8, position);
             }
             if (ai[0] == 0f || ai[0] == 2f)
             {
                 scale += 0.01f;
                 alpha -= 50;
                 if (alpha <= 0)
                 {
                     ai[0] = 1f;
                     alpha = 0;
                 }
             }
             else if (ai[0] == 1f)
             {
                 scale -= 0.01f;
                 alpha += 50;
                 if (alpha >= 255)
                 {
                     ai[0] = 2f;
                     alpha = 255;
                 }
             }
         }
         if (type == 572)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(SoundID.Item17, position);
             }
             for (int num150 = 0; num150 < 2; num150++)
             {
                 int num151 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 40, velocity.X, velocity.Y, 100);
                 Main.dust[num151].velocity *= 0.5f;
                 Main.dust[num151].velocity += velocity;
                 Main.dust[num151].velocity *= 0.5f;
                 Main.dust[num151].noGravity = true;
                 Main.dust[num151].scale = 1.2f;
                 Main.dust[num151].position = (base.Center + position) / 2f;
             }
         }
         if (type == 577)
         {
             Lighting.AddLight(base.Center, 0.1f, 0.3f, 0.4f);
         }
         else if (type == 576)
         {
             Lighting.AddLight(base.Center, 0.4f, 0.2f, 0.4f);
             for (int num152 = 0; num152 < 5; num152++)
             {
                 Dust obj5 = Main.dust[Dust.NewDust(position, width, height, 242, velocity.X, velocity.Y, 100)];
                 obj5.velocity = Vector2.Zero;
                 obj5.position -= velocity / 5f * num152;
                 obj5.noGravity = true;
                 obj5.scale = 0.8f;
                 obj5.noLight = true;
             }
         }
         else if (type == 581)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(SoundID.Item17, base.Center);
             }
             for (int num153 = 0; num153 < 2; num153++)
             {
                 int num154 = Utils.SelectRandom<int>(Main.rand, 229, 161, 161);
                 Dust obj6 = Main.dust[Dust.NewDust(position, width, height, num154, velocity.X, velocity.Y, 100)];
                 obj6.velocity = obj6.velocity / 4f + velocity / 2f;
                 obj6.noGravity = true;
                 obj6.scale = 1.2f;
                 obj6.position = base.Center;
                 obj6.noLight = true;
             }
         }
         else if (type == 671)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 for (int num155 = 0; num155 < 8; num155++)
                 {
                     int num156 = Utils.SelectRandom<int>(Main.rand, 27, 62);
                     Dust obj7 = Main.dust[Dust.NewDust(position, width, height, num156, velocity.X, velocity.Y, 100)];
                     obj7.velocity = (Main.rand.NextFloatDirection() * (float)Math.PI).ToRotationVector2() * 2f + velocity.SafeNormalize(Vector2.Zero) * 3f;
                     obj7.noGravity = true;
                     obj7.scale = 1.5f;
                     obj7.fadeIn = 1.2f;
                     obj7.position = base.Center;
                     obj7.noLight = true;
                 }
             }
             alpha -= 20;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             for (int num157 = 0; num157 < 2; num157++)
             {
                 int num158 = Utils.SelectRandom<int>(Main.rand, 27, 27, 62);
                 Dust obj8 = Main.dust[Dust.NewDust(position, width, height, num158, velocity.X, velocity.Y, 100)];
                 obj8.velocity = obj8.velocity / 4f + velocity / 2f;
                 obj8.noGravity = true;
                 obj8.scale = 1.2f;
                 obj8.position = base.Center;
                 obj8.noLight = true;
             }
         }
         else if (type == 811)
         {
             if (localAI[0] == 0f)
             {
                 SoundEngine.PlaySound(SoundID.Item17, base.Center);
                 localAI[0] = 1f;
                 for (int num159 = 0; num159 < 8; num159++)
                 {
                     Dust obj9 = Main.dust[Dust.NewDust(position, width, height, 5, velocity.X, velocity.Y, 100)];
                     obj9.velocity = (Main.rand.NextFloatDirection() * (float)Math.PI).ToRotationVector2() * 2f + velocity.SafeNormalize(Vector2.Zero) * 3f;
                     obj9.scale = 1.5f;
                     obj9.fadeIn = 1.7f;
                     obj9.position = base.Center;
                 }
             }
             alpha -= 20;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             for (int num160 = 0; num160 < 2; num160++)
             {
                 Dust obj10 = Main.dust[Dust.NewDust(position, width, height, 5, velocity.X, velocity.Y, 100)];
                 obj10.velocity = obj10.velocity / 4f + velocity / 2f;
                 obj10.scale = 1.2f;
                 obj10.position = base.Center + Main.rand.NextFloat() * velocity * 2f;
             }
         }
         else if (type == 819)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 for (int num161 = 0; num161 < 8; num161++)
                 {
                     Dust obj11 = Main.dust[Dust.NewDust(position, width, height, 5, velocity.X, velocity.Y, 100)];
                     obj11.velocity = (Main.rand.NextFloatDirection() * (float)Math.PI).ToRotationVector2() * 2f + velocity.SafeNormalize(Vector2.Zero) * 2f;
                     obj11.scale = 0.9f;
                     obj11.fadeIn = 1.3f;
                     obj11.position = base.Center;
                 }
             }
             alpha -= 20;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             for (int num162 = 1; num162 < 6; num162++)
             {
                 Dust obj12 = Main.dust[Dust.NewDust(position, width, height, 5, 0f, 0f, 100)];
                 obj12.velocity = obj12.velocity * 0.5f + velocity * 0.5f;
                 obj12.velocity *= 0.25f;
                 obj12.scale = 0.9f;
                 obj12.position = base.Center - velocity * num162 / 5f;
             }
             if (Main.rand.Next(2) == 0)
             {
                 Dust dust13 = Dust.NewDustPerfect(base.Center - velocity * 3f, 267, velocity * 0.5f, 0, Color.Red * (Main.rand.NextFloat() * 0.3f + 0.1f));
                 dust13.noGravity = true;
                 dust13.scale = 0.7f;
             }
             Lighting.AddLight(base.Center, 0.3f, 0.05f, 0.05f);
         }
         else if (type == 814)
         {
             if (localAI[0] == 0f)
             {
                 SoundEngine.PlaySound(SoundID.Item171, base.Center);
                 localAI[0] = 1f;
                 for (int num163 = 0; num163 < 8; num163++)
                 {
                     Dust obj13 = Main.dust[Dust.NewDust(position, width, height, 5, velocity.X, velocity.Y, 100)];
                     obj13.velocity = (Main.rand.NextFloatDirection() * (float)Math.PI).ToRotationVector2() * 2f + velocity.SafeNormalize(Vector2.Zero) * 2f;
                     obj13.scale = 0.9f;
                     obj13.fadeIn = 1.1f;
                     obj13.position = base.Center;
                 }
             }
             alpha -= 20;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             for (int num164 = 0; num164 < 2; num164++)
             {
                 Dust obj14 = Main.dust[Dust.NewDust(position, width, height, 5, velocity.X, velocity.Y, 100)];
                 obj14.velocity = obj14.velocity / 4f + velocity / 2f;
                 obj14.scale = 1.2f;
                 obj14.position = base.Center + Main.rand.NextFloat() * velocity * 2f;
             }
             for (int num165 = 1; num165 < oldPos.Length && !(oldPos[num165] == Vector2.Zero); num165++)
             {
                 if (Main.rand.Next(3) == 0)
                 {
                     Dust obj15 = Main.dust[Dust.NewDust(oldPos[num165], width, height, 5, velocity.X, velocity.Y, 100)];
                     obj15.velocity = obj15.velocity / 4f + velocity / 2f;
                     obj15.scale = 1.2f;
                     obj15.position = oldPos[num165] + base.Size / 2f + Main.rand.NextFloat() * velocity * 2f;
                 }
             }
         }
         else if (type == 675)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlayTrackedSound(SoundID.DD2_DarkMageAttack, base.Center);
             }
             alpha -= 20;
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         else if (type == 676)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(SoundID.Item17, base.Center);
             }
             alpha -= 20;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             for (int num166 = 0; num166 < 2; num166++)
             {
                 if (Main.rand.Next(5) != 0)
                 {
                     int num167 = Utils.SelectRandom<int>(Main.rand, 4, 256);
                     Dust dust14 = Main.dust[Dust.NewDust(position, width, height, num167, velocity.X, velocity.Y, 100)];
                     dust14.velocity = dust14.velocity / 4f + velocity / 2f;
                     dust14.scale = 0.8f + Main.rand.NextFloat() * 0.4f;
                     dust14.position = base.Center;
                     dust14.position += new Vector2(width * 2, 0f).RotatedBy((float)Math.PI * 2f * Main.rand.NextFloat()) * Main.rand.NextFloat();
                     dust14.noLight = true;
                     if (dust14.type == 4)
                     {
                         dust14.color = new Color(80, 170, 40, 120);
                     }
                 }
             }
         }
         else if (type == 686)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlayTrackedSound(SoundID.DD2_BetsyFireballShot, base.Center);
             }
             if (ai[0] >= 2f)
             {
                 alpha -= 25;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
             if (Main.rand.Next(4) == 0)
             {
                 Dust dust15 = Dust.NewDustDirect(position, width, height, 55, 0f, 0f, 200);
                 dust15.scale *= 0.7f;
                 dust15.velocity += velocity * 1f;
             }
             if (Main.rand.Next(3) == 0 && oldPos[9] != Vector2.Zero)
             {
                 Dust dust16 = Dust.NewDustDirect(oldPos[9], width, height, 55, 0f, 0f, 50);
                 dust16.scale *= 0.85f;
                 dust16.velocity += velocity * 0.85f;
                 dust16.color = Color.Purple;
             }
         }
         else if (type == 711)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 for (int num168 = 0; num168 < 10; num168++)
                 {
                     Dust dust17 = Dust.NewDustDirect(position, width, height, 55, 0f, 0f, 200);
                     dust17.scale *= 0.65f;
                     dust17.velocity *= 1.5f;
                     dust17.velocity += velocity * 0.3f;
                     dust17.fadeIn = 0.7f;
                 }
             }
             if (ai[0] >= 2f)
             {
                 alpha -= 25;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
             if (Main.rand.Next(4) == 0)
             {
                 Dust dust18 = Dust.NewDustDirect(position, width, height, 55, 0f, 0f, 200);
                 dust18.scale *= 0.7f;
                 dust18.velocity += velocity * 1f;
             }
             if (Main.rand.Next(3) == 0 && oldPos[9] != Vector2.Zero)
             {
                 Dust dust19 = Dust.NewDustDirect(oldPos[9], width, height, 55, 0f, 0f, 50);
                 dust19.scale *= 0.85f;
                 dust19.velocity += velocity * 0.85f;
                 dust19.color = Color.Purple;
             }
         }
         if (type == 299)
         {
             if (localAI[0] == 6f)
             {
                 SoundEngine.PlaySound(SoundID.Item8, position);
                 for (int num169 = 0; num169 < 40; num169++)
                 {
                     int num170 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 181, 0f, 0f, 100);
                     Main.dust[num170].velocity *= 3f;
                     Main.dust[num170].velocity += velocity * 0.75f;
                     Main.dust[num170].scale *= 1.2f;
                     Main.dust[num170].noGravity = true;
                 }
             }
             localAI[0] += 1f;
             if (localAI[0] > 6f)
             {
                 for (int num171 = 0; num171 < 3; num171++)
                 {
                     int num172 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 181, velocity.X * 0.2f, velocity.Y * 0.2f, 100);
                     Main.dust[num172].velocity *= 0.6f;
                     Main.dust[num172].scale *= 1.4f;
                     Main.dust[num172].noGravity = true;
                 }
             }
         }
         else if (type == 270 || type == 837)
         {
             if (type == 270)
             {
                 alpha = 0;
             }
             if (alpha > 0)
             {
                 alpha -= 50;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             frame++;
             if (frame > 2)
             {
                 frame = 0;
             }
             if (type == 270)
             {
                 for (int num173 = 0; num173 < 2; num173++)
                 {
                     int num174 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, 5, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 1.5f);
                     Main.dust[num174].position -= velocity;
                     Main.dust[num174].noGravity = true;
                     Main.dust[num174].velocity.X *= 0.3f;
                     Main.dust[num174].velocity.Y *= 0.3f;
                 }
             }
             else
             {
                 for (int num175 = 0; num175 < 2; num175++)
                 {
                     int num176 = Dust.NewDust(new Vector2(position.X + 4f, position.Y + 4f), width - 8, height - 8, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 2f);
                     Main.dust[num176].position -= velocity * 2f;
                     Main.dust[num176].noGravity = true;
                     Main.dust[num176].velocity.X *= 0.3f;
                     Main.dust[num176].velocity.Y *= 0.3f;
                 }
             }
         }
         if (type == 259)
         {
             if (alpha > 0)
             {
                 alpha -= 10;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         if (type == 265)
         {
             if (alpha > 0)
             {
                 alpha -= 50;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (alpha == 0)
             {
                 int num177 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 163, velocity.X, velocity.Y, 100, default(Color), 1.2f);
                 Main.dust[num177].noGravity = true;
                 Main.dust[num177].velocity *= 0.3f;
                 Main.dust[num177].velocity -= velocity * 0.4f;
             }
         }
         if (type == 355)
         {
             if (alpha > 0)
             {
                 alpha -= 50;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (alpha == 0)
             {
                 int num178 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 205, velocity.X, velocity.Y, 100, default(Color), 1.2f);
                 Main.dust[num178].noGravity = true;
                 Main.dust[num178].velocity *= 0.3f;
                 Main.dust[num178].velocity -= velocity * 0.4f;
             }
         }
         if (type == 981 && Main.rand.Next(6) == 0)
         {
             int num179 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 279, velocity.X, velocity.Y, 100, default(Color), 1.2f);
             Main.dust[num179].noLightEmittence = true;
             Main.dust[num179].noGravity = true;
             Main.dust[num179].velocity *= 0.2f;
         }
         if (type == 357)
         {
             if (alpha < 170)
             {
                 for (int num180 = 0; num180 < 10; num180++)
                 {
                     float x = position.X - velocity.X / 10f * (float)num180;
                     float y = position.Y - velocity.Y / 10f * (float)num180;
                     int num181 = Dust.NewDust(new Vector2(x, y), 1, 1, 206);
                     Main.dust[num181].alpha = alpha;
                     Main.dust[num181].position.X = x;
                     Main.dust[num181].position.Y = y;
                     Main.dust[num181].velocity *= 0f;
                     Main.dust[num181].noGravity = true;
                 }
             }
             if (alpha > 0)
             {
                 alpha -= 25;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         else if (type == 207 || type == 837)
         {
             if (type == 207 && alpha < 170)
             {
                 for (int num182 = 0; num182 < 10; num182++)
                 {
                     float x2 = position.X - velocity.X / 10f * (float)num182;
                     float y2 = position.Y - velocity.Y / 10f * (float)num182;
                     int num183 = Dust.NewDust(new Vector2(x2, y2), 1, 1, 75);
                     Main.dust[num183].alpha = alpha;
                     Main.dust[num183].position.X = x2;
                     Main.dust[num183].position.Y = y2;
                     Main.dust[num183].velocity *= 0f;
                     Main.dust[num183].noGravity = true;
                 }
             }
             float num184 = (float)Math.Sqrt(velocity.X * velocity.X + velocity.Y * velocity.Y);
             float num185 = localAI[0];
             if (num185 == 0f)
             {
                 localAI[0] = num184;
                 num185 = num184;
             }
             if (alpha > 0)
             {
                 alpha -= 25;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             float num186 = position.X;
             float num187 = position.Y;
             float num188 = 300f;
             bool flag5 = false;
             int num189 = 0;
             if (ai[1] == 0f)
             {
                 for (int num190 = 0; num190 < 200; num190++)
                 {
                     if (Main.npc[num190].CanBeChasedBy(this) && (ai[1] == 0f || ai[1] == (float)(num190 + 1)))
                     {
                         float num191 = Main.npc[num190].position.X + (float)(Main.npc[num190].width / 2);
                         float num192 = Main.npc[num190].position.Y + (float)(Main.npc[num190].height / 2);
                         float num193 = Math.Abs(position.X + (float)(width / 2) - num191) + Math.Abs(position.Y + (float)(height / 2) - num192);
                         if (num193 < num188 && Collision.CanHit(new Vector2(position.X + (float)(width / 2), position.Y + (float)(height / 2)), 1, 1, Main.npc[num190].position, Main.npc[num190].width, Main.npc[num190].height))
{
                             num188 = num193;
                             num186 = num191;
                             num187 = num192;
                             flag5 = true;
                             num189 = num190;
                         }
                     }
                 }
                 if (flag5)
                 {
                     ai[1] = num189 + 1;
                 }
                 flag5 = false;
             }
             if (ai[1] > 0f)
             {
                 int num194 = (int)(ai[1] - 1f);
                 if (Main.npc[num194].active && Main.npc[num194].CanBeChasedBy(this, ignoreDontTakeDamage: true) && !Main.npc[num194].dontTakeDamage)
                 {
                     float num195 = Main.npc[num194].position.X + (float)(Main.npc[num194].width / 2);
                     float num196 = Main.npc[num194].position.Y + (float)(Main.npc[num194].height / 2);
                     if (Math.Abs(position.X + (float)(width / 2) - num195) + Math.Abs(position.Y + (float)(height / 2) - num196) < 1000f)
                     {
                         flag5 = true;
                         num186 = Main.npc[num194].position.X + (float)(Main.npc[num194].width / 2);
                         num187 = Main.npc[num194].position.Y + (float)(Main.npc[num194].height / 2);
                     }
                 }
                 else
                 {
                     ai[1] = 0f;
                 }
             }
             if (!friendly)
             {
                 flag5 = false;
             }
             if (flag5)
             {
                 float num197 = num185;
                 Vector2 vector26 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num198 = num186 - vector26.X;
                 float num199 = num187 - vector26.Y;
                 float num200 = (float)Math.Sqrt(num198 * num198 + num199 * num199);
                 num200 = num197 / num200;
                 num198 *= num200;
                 num199 *= num200;
                 int num201 = 8;
                 if (type == 837)
                 {
                     num201 = 32;
                 }
                 velocity.X = (velocity.X * (float)(num201 - 1) + num198) / (float)num201;
                 velocity.Y = (velocity.Y * (float)(num201 - 1) + num199) / (float)num201;
             }
         }
         else if (type == 81 || type == 91)
         {
             if (ai[0] >= 20f)
             {
                 ai[0] = 20f;
                 velocity.Y += 0.07f;
             }
         }
         else if (type == 174 || type == 605 || type == 920 || type == 921 || type == 926)
         {
             if (ai[0] >= 5f)
             {
                 ai[0] = 5f;
                 velocity.Y += 0.15f;
             }
         }
         else if (type == 937)
         {
             if (ai[0] >= 5f)
             {
                 ai[0] = 5f;
                 velocity.Y += 0.07f;
             }
         }
         else if (type == 962)
         {
             frame = (int)ai[1];
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 rotation = velocity.ToRotation();
                 for (int num202 = 0; num202 < 5; num202++)
                 {
                     Dust dust20 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(24f, 24f), 16, velocity * MathHelper.Lerp(0.2f, 0.7f, Main.rand.NextFloat()));
                     dust20.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                     dust20.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
                 }
                 for (int num203 = 0; num203 < 5; num203++)
                 {
                     Dust dust21 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(24f, 24f), 16, Main.rand.NextVector2Circular(2f, 2f) + velocity * MathHelper.Lerp(0.2f, 0.5f, Main.rand.NextFloat()));
                     dust21.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                     dust21.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
                     dust21.fadeIn = 1f;
                 }
             }
             if (ai[0] >= 5f)
             {
                 velocity.Y += 0.15f;
             }
         }
         else if (type == 337)
         {
             if (position.Y > Main.player[owner].position.Y - 300f)
             {
                 tileCollide = true;
             }
             if ((double)position.Y < Main.worldSurface * 16.0)
             {
                 tileCollide = true;
             }
             frame = (int)ai[1];
             if (Main.rand.Next(2) == 0)
             {
                 int num204 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 197);
                 Main.dust[num204].velocity *= 0.5f;
                 Main.dust[num204].noGravity = true;
             }
         }
         else if (type == 645)
         {
             if (ai[1] != -1f && position.Y > ai[1])
             {
                 tileCollide = true;
             }
             if (position.HasNaNs())
             {
                 Kill();
                 return;
             }
             bool num205 = WorldGen.SolidTile(Framing.GetTileSafely((int)position.X / 16, (int)position.Y / 16));
             Dust dust22 = Main.dust[Dust.NewDust(new Vector2(position.X, position.Y), width, height, 229)];
             dust22.position = base.Center;
             dust22.velocity = Vector2.Zero;
             dust22.noGravity = true;
             if (num205)
             {
                 dust22.noLight = true;
             }
             if (ai[1] == -1f)
             {
                 ai[0] += 1f;
                 velocity = Vector2.Zero;
                 tileCollide = false;
                 penetrate = -1;
                 position = base.Center;
                 width = (height = 140);
                 base.Center = position;
                 alpha -= 10;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 if (++frameCounter >= MaxUpdates * 3)
                 {
                     frameCounter = 0;
                     frame++;
                 }
                 if (ai[0] >= (float)(Main.projFrames[type] * MaxUpdates * 3))
                 {
                     Kill();
                 }
                 return;
             }
             alpha = 255;
             if (numUpdates == 0)
             {
                 int num206 = -1;
                 float num207 = 60f;
                 for (int num208 = 0; num208 < 200; num208++)
                 {
                     NPC nPC2 = Main.npc[num208];
                     if (nPC2.CanBeChasedBy(this))
                     {
                         float num209 = Distance(nPC2.Center);
                         if (num209 < num207 && Collision.CanHitLine(base.Center, 0, 0, nPC2.Center, 0, 0))
{
                             num207 = num209;
                             num206 = num208;
                         }
                     }
                 }
                 if (num206 != -1)
                 {
                     ai[0] = 0f;
                     ai[1] = -1f;
                     netUpdate = true;
                     return;
                 }
             }
         }
         else if (type >= 424 && type <= 426)
         {
             if (position.Y > Main.player[owner].position.Y - 300f)
             {
                 tileCollide = true;
             }
             if ((double)position.Y < Main.worldSurface * 16.0)
             {
                 tileCollide = true;
             }
             scale = ai[1];
             rotation += velocity.X * 2f;
             Vector2 vector27 = base.Center + Vector2.Normalize(velocity) * 10f;
             Dust obj16 = Main.dust[Dust.NewDust(position, width, height, 6)];
             obj16.position = vector27;
             obj16.velocity = velocity.RotatedBy(1.5707963705062866) * 0.33f + velocity / 4f;
             obj16.position += velocity.RotatedBy(1.5707963705062866);
             obj16.fadeIn = 0.5f;
             obj16.noGravity = true;
             Dust obj17 = Main.dust[Dust.NewDust(position, width, height, 6)];
             obj17.position = vector27;
             obj17.velocity = velocity.RotatedBy(-1.5707963705062866) * 0.33f + velocity / 4f;
             obj17.position += velocity.RotatedBy(-1.5707963705062866);
             obj17.fadeIn = 0.5f;
             obj17.noGravity = true;
             for (int num210 = 0; num210 < 1; num210++)
             {
                 int num211 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6);
                 Main.dust[num211].velocity *= 0.5f;
                 Main.dust[num211].scale *= 1.3f;
                 Main.dust[num211].fadeIn = 1f;
                 Main.dust[num211].noGravity = true;
             }
         }
         else if (type == 344)
         {
             if (WorldGen.SolidTile((int)position.X / 16, (int)(position.Y + velocity.Y) / 16 + 1) || WorldGen.SolidTile((int)(position.X + (float)width) / 16, (int)(position.Y + velocity.Y) / 16 + 1))
             {
                 Kill();
                 return;
             }
             localAI[1] += 1f;
             if (localAI[1] > 5f)
             {
                 alpha -= 50;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
             frame = (int)ai[1];
             if (localAI[1] >= 20f)
             {
                 velocity.Y += 0.15f;
                 velocity.X *= 0.96f;
             }
             if (localAI[1] >= 25f)
             {
                 localAI[1] = 20f;
                 Vector2 zero = Vector2.Zero;
                 float num212 = 0f;
                 int num213 = 60;
                 for (int num214 = 0; num214 < 1000; num214++)
                 {
                     Projectile projectile = Main.projectile[num214];
                     if (projectile.whoAmI != whoAmI && projectile.active && projectile.type == type)
                     {
                         Vector2 vector28 = projectile.position - position;
                         if (!(vector28.Length() > (float)num213))
{
                             num212 += 1f;
                             float num215 = Utils.Remap(vector28.Length(), 0f, num213, 1f, 0f);
                             zero.X += (float)(-Math.Sign(vector28.X)) * num215;
                         }
                     }
                 }
                 if (num212 > 0f)
                 {
                     Vector2 vector29 = zero;
                     vector29.Y = 0f;
                     if (vector29.X == 0f)
                     {
                         vector29.X = 1f;
                     }
                     velocity += vector29 * 0.25f;
                 }
             }
         }
         else if (type == 336 || type == 345)
         {
             if (type == 345 && localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(SoundID.Item1, position);
             }
             if (ai[0] >= 50f)
             {
                 ai[0] = 50f;
                 velocity.Y += 0.5f;
             }
         }
         else if (type == 246)
         {
             alpha -= 20;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (ai[0] >= 60f)
             {
                 ai[0] = 60f;
                 velocity.Y += 0.15f;
             }
         }
         else if (type == 311)
         {
             if (alpha > 0)
             {
                 alpha -= 50;
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (ai[0] >= 30f)
             {
                 ai[0] = 30f;
                 if (ai[1] == 0f)
                 {
                     ai[1] = 1f;
                 }
                 velocity.Y += 0.5f;
             }
         }
         else if (type == 312)
         {
             if (ai[0] >= 5f)
             {
                 alpha = 0;
             }
             if (ai[0] >= 20f)
             {
                 ai[0] = 30f;
                 velocity.Y += 0.5f;
             }
             Lighting.AddLight(base.Center, 0.6f, 0.4f, 0.3f);
         }
         else if (type != 239 && type != 264)
         {
             if (type == 176)
             {
                 if (ai[0] >= 15f)
                 {
                     ai[0] = 15f;
                     velocity.Y += 0.05f;
                 }
             }
             else if (type == 275 || type == 276)
             {
                 if (alpha > 0)
                 {
                     alpha -= 30;
                 }
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 if (ai[0] >= 35f)
                 {
                     ai[0] = 35f;
                     velocity.Y += 0.025f;
                 }
                 if (Main.expertMode)
                 {
                     float num216 = 18f;
                     int num217 = Player.FindClosest(base.Center, 1, 1);
                     Vector2 vector30 = Main.player[num217].Center - base.Center;
                     vector30.Normalize();
                     vector30 *= num216;
                     int num218 = 70;
                     velocity = (velocity * (num218 - 1) + vector30) / num218;
                     if (velocity.Length() < 14f)
                     {
                         velocity.Normalize();
                         velocity *= 14f;
                     }
                     tileCollide = false;
                     if (timeLeft > 180)
                     {
                         timeLeft = 180;
                     }
                 }
             }
             else if (type == 172)
             {
                 if (ai[0] >= 17f)
                 {
                     ai[0] = 17f;
                     velocity.Y += 0.085f;
                 }
             }
             else if (type == 117)
             {
                 if (ai[0] >= 35f)
                 {
                     ai[0] = 35f;
                     velocity.Y += 0.06f;
                 }
             }
             else if (type == 120)
             {
                 int num219 = Dust.NewDust(new Vector2(position.X - velocity.X, position.Y - velocity.Y), width, height, 67, velocity.X, velocity.Y, 100, default(Color), 1.2f);
                 Main.dust[num219].noGravity = true;
                 Main.dust[num219].velocity *= 0.3f;
                 if (ai[0] >= 30f)
                 {
                     ai[0] = 30f;
                     velocity.Y += 0.05f;
                 }
             }
             else if (type == 195)
             {
                 int num220 = 40;
                 if (ai[0] >= (float)num220)
                 {
                     ai[0] = num220;
                     velocity.Y += 0.15f;
                     tileCollide = true;
                 }
                 else
                 {
                     tileCollide = velocity.Y > 0f;
                 }
             }
             else if (type == 267 || type == 477 || type == 478 || type == 479)
             {
                 localAI[0] += 1f;
                 if (localAI[0] > 3f)
                 {
                     alpha = 0;
                 }
                 if (ai[0] >= 20f)
                 {
                     ai[0] = 20f;
                     if (type != 477)
                     {
                         velocity.Y += 0.075f;
                     }
                 }
                 if (type == 479 && Main.myPlayer == owner)
                 {
                     if (ai[1] >= 0f)
                     {
                         maxPenetrate = (penetrate = -1);
                     }
                     else if (penetrate < 0)
                     {
                         maxPenetrate = (penetrate = 1);
                     }
                     if (ai[1] >= 0f)
                     {
                         ai[1] += 1f;
                     }
                     if (ai[1] > (float)Main.rand.Next(5, 30))
                     {
                         ai[1] = -1000f;
                         float num221 = velocity.Length();
                         Vector2 vector31 = velocity;
                         vector31.Normalize();
                         int num222 = Main.rand.Next(2, 4);
                         if (Main.rand.Next(4) == 0)
{
                             num222++;
                         }
                         for (int num223 = 0; num223 < num222; num223++)
{
                             Vector2 vector32 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                             vector32.Normalize();
                             vector32 += vector31 * 2f;
                             vector32.Normalize();
                             vector32 *= num221;
                             NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector32.X, vector32.Y, type, damage, knockBack, owner, 0f, -1000f);
                         }
                     }
                 }
                 if (type == 478 && Main.myPlayer == owner)
                 {
                     ai[1] += 1f;
                     if (ai[1] > (float)Main.rand.Next(5, 20))
                     {
                         if (timeLeft > 40)
{
                             timeLeft -= 20;
                         }
                         ai[1] = 0f;
                         NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, 0f, 0f, 480, (int)((double)damage * 0.8), knockBack * 0.5f, owner);
                     }
                 }
             }
             else if (type == 408)
             {
                 if (ai[0] >= 45f)
                 {
                     ai[0] = 45f;
                     velocity.Y += 0.05f;
                 }
             }
             else if (type == 616)
             {
                 if (alpha < 170)
                 {
                     float num224 = 3f;
                     for (int num225 = 0; (float)num225 < num224; num225++)
                     {
                         int num226 = Dust.NewDust(position, 1, 1, 229);
                         Main.dust[num226].position = base.Center - velocity / num224 * num225;
                         Main.dust[num226].velocity *= 0f;
                         Main.dust[num226].noGravity = true;
                         Main.dust[num226].alpha = 200;
                         Main.dust[num226].scale = 0.5f;
                     }
                 }
                 float num227 = (float)Math.Sqrt(velocity.X * velocity.X + velocity.Y * velocity.Y);
                 float num228 = localAI[0];
                 if (num228 == 0f)
                 {
                     localAI[0] = num227;
                     num228 = num227;
                 }
                 if (alpha > 0)
                 {
                     alpha -= 25;
                 }
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
                 float num229 = position.X;
                 float num230 = position.Y;
                 float num231 = 800f;
                 bool flag6 = false;
                 int num232 = 0;
                 ai[0] += 1f;
                 if (ai[0] > 20f)
                 {
                     ai[0] -= 1f;
                     if (ai[1] == 0f)
                     {
                         for (int num233 = 0; num233 < 200; num233++)
{
                             if (Main.npc[num233].CanBeChasedBy(this) && (ai[1] == 0f || ai[1] == (float)(num233 + 1)))
{
                                 float num234 = Main.npc[num233].position.X + (float)(Main.npc[num233].width / 2);
                                 float num235 = Main.npc[num233].position.Y + (float)(Main.npc[num233].height / 2);
                                 float num236 = Math.Abs(position.X + (float)(width / 2) - num234) + Math.Abs(position.Y + (float)(height / 2) - num235);
                                 if (num236 < num231 && Collision.CanHit(new Vector2(position.X + (float)(width / 2), position.Y + (float)(height / 2)), 1, 1, Main.npc[num233].position, Main.npc[num233].width, Main.npc[num233].height))
{
                                     num231 = num236;
                                     num229 = num234;
                                     num230 = num235;
                                     flag6 = true;
                                     num232 = num233;
                                 }
                             }
                         }
                         if (flag6)
{
                             ai[1] = num232 + 1;
                         }
                         flag6 = false;
                     }
                     if (ai[1] != 0f)
                     {
                         int num237 = (int)(ai[1] - 1f);
                         if (Main.npc[num237].active && Main.npc[num237].CanBeChasedBy(this, ignoreDontTakeDamage: true))
{
                             float num238 = Main.npc[num237].position.X + (float)(Main.npc[num237].width / 2);
                             float num239 = Main.npc[num237].position.Y + (float)(Main.npc[num237].height / 2);
                             if (Math.Abs(position.X + (float)(width / 2) - num238) + Math.Abs(position.Y + (float)(height / 2) - num239) < 1000f)
{
                                 flag6 = true;
                                 num229 = Main.npc[num237].position.X + (float)(Main.npc[num237].width / 2);
                                 num230 = Main.npc[num237].position.Y + (float)(Main.npc[num237].height / 2);
                             }
                         }
                     }
                     if (!friendly)
                     {
                         flag6 = false;
                     }
                     if (flag6)
                     {
                         float num240 = num228;
                         Vector2 vector33 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                         float num241 = num229 - vector33.X;
                         float num242 = num230 - vector33.Y;
                         float num243 = (float)Math.Sqrt(num241 * num241 + num242 * num242);
                         num243 = num240 / num243;
                         num241 *= num243;
                         num242 *= num243;
                         int num244 = 8;
                         velocity.X = (velocity.X * (float)(num244 - 1) + num241) / (float)num244;
                         velocity.Y = (velocity.Y * (float)(num244 - 1) + num242) / (float)num244;
                     }
                 }
             }
             else if (type == 507 || type == 508 || type == 662 || type == 680 || type == 685)
             {
                 if (ai[0] > 60f)
                 {
                     velocity.X *= 0.98f;
                     velocity.Y += 0.3f;
                 }
             }
             else if (type == 495)
             {
                 int num245 = Dust.NewDust(new Vector2(position.X - velocity.X, position.Y - velocity.Y), width, height, 27, velocity.X, velocity.Y, 100, default(Color), 1.2f);
                 Main.dust[num245].noGravity = true;
                 Main.dust[num245].velocity *= 0.3f;
                 if (ai[0] >= 30f)
                 {
                     ai[0] = 30f;
                     velocity.Y += 0.04f;
                 }
             }
             else if (type == 498)
             {
                 if (localAI[0] == 0f)
                 {
                     localAI[0] += 1f;
                     SoundEngine.PlaySound(SoundID.Item17, position);
                 }
                 ai[0] += 1f;
                 if (ai[0] >= 50f)
                 {
                     velocity.X *= 0.98f;
                     velocity.Y += 0.15f;
                     rotation += (float)direction * 0.5f;
                 }
                 else
                 {
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
                 }
             }
             else if (type == 437)
             {
                 if (ai[0] >= 12f)
                 {
                     if (ai[0] >= 20f)
                     {
                         Kill();
                     }
                     alpha += 30;
                 }
             }
             else if (type != 442 && type != 634 && type != 635 && type != 675)
             {
                 if (type == 686 || type == 711)
                 {
                     if (ai[0] >= 10f)
                     {
                         velocity.Y += 0.1f;
                     }
                     if (ai[0] >= 20f)
                     {
                         velocity.Y += 0.1f;
                     }
                     if (ai[0] > 20f)
                     {
                         ai[0] = 20f;
                     }
                     velocity.X *= 0.99f;
                     if (velocity.Y > 32f)
                     {
                         velocity.Y = 32f;
                     }
                 }
                 else if (type == 639)
                 {
                     if (timeLeft <= MaxUpdates * 45 - 14)
                     {
                         velocity.Y += 0.1f;
                     }
                 }
                 else if (type == 710)
                 {
                     if (ai[0] >= 0f)
                     {
                         ai[0] += 1f;
                         if (ai[0] >= 20f)
{
                             velocity.Y += 0.2f;
                             if (velocity.Y > 0f)
{
                                 velocity.X *= 0.98f;
                             }
                             if (velocity.Y > 12f)
{
                                 velocity.Y = 12f;
                             }
                         }
                     }
                 }
                 else if (ai[0] >= 15f)
                 {
                     ai[0] = 15f;
                     if (flag4)
                     {
                         velocity.Y -= 0.1f;
                     }
                     else
                     {
                         velocity.Y += 0.1f;
                     }
                 }
             }
         }
         if (type == 921 || type == 926 || type == 937)
         {
             rotation += (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.05f;
         }
         else if (type == 248)
         {
             if (velocity.X < 0f)
             {
                 rotation -= (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.05f;
             }
             else
             {
                 rotation += (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.05f;
             }
         }
         else if (type == 270 || type == 585 || type == 601 || type == 706 || type == 837)
         {
             spriteDirection = direction;
             if (direction < 0)
             {
                 rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X);
             }
             else
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X);
             }
         }
         else if (type == 311)
         {
             if (ai[1] != 0f)
             {
                 rotation += velocity.X * 0.1f + (float)Main.rand.Next(-10, 11) * 0.025f;
             }
             else
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
             }
         }
         else if (type == 312)
         {
             rotation += velocity.X * 0.02f;
         }
         else if (type == 675)
         {
             rotation += velocity.X * 0.03f;
         }
         else if (type != 676)
         {
             if (type == 408)
             {
                 rotation = velocity.ToRotation();
                 if (direction == -1)
                 {
                     rotation += (float)Math.PI;
                 }
             }
             else if (type == 435 || type == 459 || type == 682 || type == 709)
             {
                 rotation = velocity.ToRotation();
                 if (direction == -1)
                 {
                     rotation += (float)Math.PI;
                 }
             }
             else if (type == 660)
             {
                 rotation = velocity.ToRotation() + (float)Math.PI / 4f;
             }
             else if (type == 662 || type == 685)
             {
                 rotation = velocity.ToRotation() - (float)Math.PI - (float)Math.PI / 4f;
             }
             else if (type == 680 || type == 684 || type == 686 || type == 711 || type == 712)
             {
                 rotation = velocity.ToRotation() + (float)Math.PI / 2f;
             }
             else if (type == 436)
             {
                 rotation = velocity.ToRotation();
                 rotation += (float)Math.PI;
                 if (direction == -1)
                 {
                     rotation += (float)Math.PI;
                 }
             }
             else if (type == 469)
             {
                 if (velocity.X > 0f)
                 {
                     spriteDirection = -1;
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
                 }
                 else
                 {
                     spriteDirection = 1;
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
                 }
             }
             else if (type == 477)
             {
                 if (localAI[1] < 5f)
                 {
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
                     localAI[1] += 1f;
                 }
                 else
                 {
                     rotation = (rotation * 2f + (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f) / 3f;
                 }
             }
             else if (type == 532)
             {
                 rotation += 0.2f + Math.Abs(velocity.X) * 0.1f;
             }
             else if (type == 483)
             {
                 rotation += velocity.X * 0.05f;
             }
             else if (type == 772)
             {
                 rotation += (float)Math.Sign(velocity.X) * (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.05f;
             }
             else if (type == 485)
             {
                 Vector2 vector34 = new Vector2(ai[0], ai[1]);
                 velocity = (velocity * 39f + vector34) / 40f;
                 int num246 = Dust.NewDust(position, width, height, 6);
                 Main.dust[num246].noGravity = true;
                 Main.dust[num246].velocity *= 0.2f;
                 Main.dust[num246].position = (Main.dust[num246].position + base.Center) / 2f;
                 frameCounter++;
                 if (frameCounter >= 2)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame >= 5)
                     {
                         frame = 0;
                     }
                 }
                 if (velocity.X < 0f)
                 {
                     spriteDirection = -1;
                     rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X);
                 }
                 else
                 {
                     spriteDirection = 1;
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                 }
             }
             else if (type == 640)
             {
                 if (velocity != Vector2.Zero)
                 {
                     rotation = velocity.ToRotation() + (float)Math.PI / 2f;
                 }
             }
             else if (type == 325)
             {
                 rotation = velocity.ToRotation() - (float)Math.PI / 2f;
             }
             else if (type != 344 && type != 498)
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
             }
         }
         bool flag7 = true;
         int num247 = type;
         if (num247 == 577)
         {
             flag7 = false;
         }
         if (flag7)
         {
             if (flag4 && velocity.Y < -16f)
             {
                 velocity.Y = -16f;
             }
             if (velocity.Y > 16f)
             {
                 velocity.Y = 16f;
             }
         }
     }
References Entity.active, Lighting.AddLight(), NPC.AI_121_QueenSlime_GetDustColor(), Dust.alpha, NPC.CanBeChasedBy(), Collision.CanHit(), Collision.CanHitLine(), DelegateMethods.CastLightOpen(), Entity.Center, Dust.CloneDust(), Color, Dust.color, Dust.customData, SoundID.DD2_BetsyFireballShot, SoundID.DD2_DarkMageAttack, SoundID.DD2_LightningBugZap, SoundID.DD2_PhantomPhoenixShot, SoundID.DD2_SkyDragonsFuryShot, Player.dead, NPC.dontTakeDamage, Main.dust, Main.expertMode, Dust.fadeIn, Player.FindClosest(), NPC.friendly, SlotId.FromFloat(), SoundEngine.GetActiveSound(), PortalHelper.GetPortalColor(), Framing.GetTileSafely(), Entity.height, Entity.Hitbox, Main.hslToRgb(), NPC.immune, SlotId.Invalid, SoundID.Item1, SoundID.Item11, SoundID.Item114, SoundID.Item115, SoundID.Item12, SoundID.Item124, SoundID.Item125, SoundID.Item154, SoundID.Item155, SoundID.Item17, SoundID.Item171, SoundID.Item20, SoundID.Item33, SoundID.Item34, SoundID.Item36, SoundID.Item42, SoundID.Item5, SoundID.Item8, SoundID.Item9, NPCID.Sets.MagicAuraColor, Main.myPlayer, Main.netMode, Dust.NewDust(), Dust.NewDustDirect(), Dust.NewDustPerfect(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Main.npc, Main.player, SoundEngine.PlaySound(), SoundEngine.PlayTrackedSound(), Utils.PlotTileLine(), ActiveSound.Position, Dust.position, Entity.position, Main.projectile, Main.projFrames, Main.rand, Utils.RandomVector2(), Utils.Remap(), Dust.scale, WorldGen.SolidTile(), type, DelegateMethods.v3_1, Dust.velocity, Entity.whoAmI, Entity.width, and Main.worldSurface.
Referenced by AI().