Terraria: Projectile.AI_009_MagicMissiles
AI_009_MagicMissiles()
void Projectile.AI_009_MagicMissiles () inline private
     {
         if (type == 491)
         {
             AI_009_MagicMissiles_Old();
             return;
         }
         int num = 32;
         Player player = Main.player[owner];
         int num2 = Main.maxTilesY * 16;
         int num3 = 0;
         if (ai[0] >= 0f)
         {
             num3 = (int)(ai[1] / (float)num2);
         }
         bool flag = ai[0] == -1f || ai[0] == -2f;
         if (type == 34)
         {
             if (frameCounter++ >= 4)
             {
                 frameCounter = 0;
                 if (++frame >= Main.projFrames[type])
                 {
                     frame = 0;
                 }
             }
             if (penetrate == 1 && ai[0] >= 0f && num3 == 0)
             {
                 ai[1] += num2;
                 num3 = 1;
                 netUpdate = true;
             }
             if (penetrate == 1 && ai[0] == -1f)
             {
                 ai[0] = -2f;
                 netUpdate = true;
             }
             if (num3 > 0 || ai[0] == -2f)
             {
                 localAI[0] += 1f;
             }
         }
         if (owner == Main.myPlayer)
         {
             if (ai[0] >= 0f)
             {
                 if (player.channel && player.HeldItem.shoot == type)
                 {
                     Vector2 pointPoisition = Main.MouseWorld;
                     player.LimitPointToPlayerReachableArea(ref pointPoisition);
                     if (ai[0] != pointPoisition.X || ai[1] != pointPoisition.Y)
                     {
                         netUpdate = true;
                         ai[0] = pointPoisition.X;
                         ai[1] = pointPoisition.Y + (float)(num2 * num3);
                     }
                 }
                 else
                 {
                     netUpdate = true;
                     ai[0] = -1f;
                     ai[1] = -1f;
                     int num4 = FindTargetWithLineOfSight();
                     if (num4 != -1)
                     {
                         ai[1] = num4;
                     }
                     else if (velocity.Length() < 2f)
                     {
                         velocity = DirectionFrom(player.Center) * num;
                     }
                     else
                     {
                         velocity = velocity.SafeNormalize(Vector2.Zero) * num;
                     }
                 }
             }
             if (flag && ai[1] == -1f)
             {
                 int num5 = FindTargetWithLineOfSight();
                 if (num5 != -1)
                 {
                     ai[1] = num5;
                     netUpdate = true;
                 }
             }
         }
         Vector2? vector = null;
         float amount = 1f;
         if (ai[0] > 0f && ai[1] > 0f)
         {
             vector = new Vector2(ai[0], ai[1] % (float)num2);
         }
         if (flag && ai[1] >= 0f)
         {
             int num6 = (int)ai[1];
             if (Main.npc.IndexInRange(num6))
             {
                 NPC nPC = Main.npc[num6];
                 if (nPC.CanBeChasedBy(this))
                 {
                     vector = nPC.Center;
                     float t = Distance(vector.Value);
                     float num7 = Utils.GetLerpValue(0f, 100f, t, clamped: true) * Utils.GetLerpValue(600f, 400f, t, clamped: true);
                     amount = MathHelper.Lerp(0f, 0.2f, Utils.GetLerpValue(200f, 20f, 1f - num7, clamped: true));
                 }
                 else
                 {
                     ai[1] = -1f;
                     netUpdate = true;
                 }
             }
         }
         bool flag2 = false;
         if (flag)
         {
             flag2 = true;
         }
         if (vector.HasValue)
         {
             Vector2 value = vector.Value;
             if (Distance(value) >= 64f)
             {
                 flag2 = true;
                 Vector2 v = value - base.Center;
                 Vector2 vector2 = v.SafeNormalize(Vector2.Zero);
                 float num8 = Math.Min(num, v.Length());
                 Vector2 value2 = vector2 * num8;
                 if (velocity.Length() < 4f)
                 {
                     velocity += velocity.SafeNormalize(Vector2.Zero).RotatedBy(0.7853981852531433).SafeNormalize(Vector2.Zero) * 4f;
                 }
                 if (velocity.HasNaNs())
                 {
                     Kill();
                 }
                 velocity = Vector2.Lerp(velocity, value2, amount);
             }
             else
             {
                 velocity *= 0.3f;
                 velocity += (value - base.Center) * 0.3f;
                 flag2 = velocity.Length() >= 2f;
             }
             if (timeLeft < 60)
             {
                 timeLeft = 60;
             }
         }
         if (flag && ai[1] < 0f)
         {
             if (velocity.Length() != (float)num)
             {
                 velocity = velocity.MoveTowards(velocity.SafeNormalize(Vector2.UnitY) * num, 4f);
             }
             if (timeLeft > 300)
             {
                 timeLeft = 300;
             }
         }
         if (flag2 && velocity != Vector2.Zero)
         {
             rotation = rotation.AngleTowards(velocity.ToRotation(), (float)Math.PI / 4f);
         }
         else
         {
             rotation = rotation.AngleLerp(0f, 0.2f);
         }
         bool flag3 = velocity.Length() > 0.1f && Vector2.Dot(oldVelocity.SafeNormalize(Vector2.Zero), velocity.SafeNormalize(Vector2.Zero)) < 0.2f;
         if (type == 16)
         {
             if (soundDelay == 0 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 2f)
             {
                 soundDelay = 10;
                 SoundEngine.PlaySound(SoundID.Item9, position);
             }
             if (Main.rand.Next(9) == 0)
             {
                 int num9 = Dust.NewDust(position, width, height, 15, 0f, 0f, 100, default(Color), 2f);
                 Main.dust[num9].velocity *= 0.3f;
                 Main.dust[num9].position.X = position.X + (float)(width / 2) + 4f + (float)Main.rand.Next(-4, 5);
                 Main.dust[num9].position.Y = position.Y + (float)(height / 2) + (float)Main.rand.Next(-4, 5);
                 Main.dust[num9].noGravity = true;
                 Main.dust[num9].velocity += Main.rand.NextVector2Circular(2f, 2f);
             }
             if (flag3)
             {
                 int num10 = Main.rand.Next(2, 5);
                 for (int i = 0; i < num10; i++)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 15, 0f, 0f, 100, default(Color), 1.5f);
                     dust.velocity *= 0.3f;
                     dust.position = base.Center;
                     dust.noGravity = true;
                     dust.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                     dust.fadeIn = 2.2f;
                 }
             }
         }
         if (type != 34)
         {
             return;
         }
         float lerpValue = Utils.GetLerpValue(0f, 10f, localAI[0], clamped: true);
         Color newColor = Color.Lerp(Color.Transparent, Color.Crimson, lerpValue);
         if (Main.rand.Next(6) == 0)
         {
             Dust dust2 = Dust.NewDustDirect(base.Center, 0, 0, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, newColor, 3.5f);
             dust2.noGravity = true;
             dust2.velocity *= 1.4f;
             dust2.velocity += Main.rand.NextVector2Circular(1f, 1f);
             dust2.velocity += velocity * 0.15f;
         }
         if (Main.rand.Next(12) == 0)
         {
             Dust dust3 = Dust.NewDustDirect(base.Center, 0, 0, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, newColor, 1.5f);
             dust3.velocity += Main.rand.NextVector2Circular(1f, 1f);
             dust3.velocity += velocity * 0.15f;
         }
         if (flag3)
         {
             int num11 = Main.rand.Next(2, 5 + (int)(lerpValue * 4f));
             for (int j = 0; j < num11; j++)
             {
                 Dust dust4 = Dust.NewDustDirect(position, width, height, 6, 0f, 0f, 100, newColor, 1.5f);
                 dust4.velocity *= 0.3f;
                 dust4.position = base.Center;
                 dust4.noGravity = true;
                 dust4.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                 dust4.fadeIn = 2.2f;
                 dust4.position += (dust4.position - base.Center) * lerpValue * 10f;
             }
         }
     }
References NPC.CanBeChasedBy(), Entity.Center, Player.channel, Color, Main.dust, Dust.fadeIn, Utils.GetLerpValue(), Player.HeldItem, SoundID.Item9, Player.LimitPointToPlayerReachableArea(), Main.maxTilesY, Main.MouseWorld, Main.myPlayer, Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.npc, Main.player, SoundEngine.PlaySound(), Dust.position, Main.projFrames, Main.rand, Item.shoot, and Dust.velocity.