Terraria: Projectile.AI_171_GetColor
AI_171_GetColor()
Color Projectile.AI_171_GetColor () inline
     {
         if (NPC.ShouldEmpressBeEnraged())
         {
             float lerpValue = Utils.GetLerpValue(0f, 60f, (int)Main.time, clamped: true);
             return Color.Lerp(Color.White, Main.OurFavoriteColor, lerpValue) * Opacity;
         }
         return Main.hslToRgb((ai[1] + 0.5f) % 1f, 1f, 0.5f) * Opacity;
     }
References Color, Utils.GetLerpValue(), Main.hslToRgb(), Main.OurFavoriteColor, NPC.ShouldEmpressBeEnraged(), and Main.time.
Referenced by Main.DrawProj_FairyQueenLance(), and Main.DrawProjDirect().