Terraria: Projectile.AI_163_Chum
AI_163_Chum()
void Projectile.AI_163_Chum () inline private
     {
         float num = 0.05f;
         float num2 = width / 2;
         for (int i = 0; i < 1000; i++)
         {
             if (i != whoAmI && Main.projectile[i].active && Main.projectile[i].type == type && Math.Abs(position.X - Main.projectile[i].position.X) + Math.Abs(position.Y - Main.projectile[i].position.Y) < num2)
             {
                 if (position.X < Main.projectile[i].position.X)
                 {
                     velocity.X -= num;
                 }
                 else
                 {
                     velocity.X += num;
                 }
                 if (position.Y < Main.projectile[i].position.Y)
                 {
                     velocity.Y -= num;
                 }
                 else
                 {
                     velocity.Y += num;
                 }
             }
         }
         if (wet)
         {
             velocity.X *= 0.9f;
             int num3 = (int)(base.Center.X + (float)((width / 2 + 8) * direction)) / 16;
             int num4 = (int)(base.Center.Y / 16f);
             _ = position.Y / 16f;
             int num5 = (int)((position.Y + (float)height) / 16f);
             if (Main.tile[num3, num4] == null)
             {
                 Main.tile[num3, num4] = new Tile();
             }
             if (Main.tile[num3, num5] == null)
             {
                 Main.tile[num3, num5] = new Tile();
             }
             if (velocity.Y > 0f)
             {
                 velocity.Y *= 0.5f;
             }
             num3 = (int)(base.Center.X / 16f);
             num4 = (int)(base.Center.Y / 16f);
             float num6 = AI_061_FishingBobber_GetWaterLine(num3, num4);
             if (base.Center.Y > num6)
             {
                 velocity.Y -= 0.1f;
                 if (velocity.Y < -8f)
                 {
                     velocity.Y = -8f;
                 }
                 if (base.Center.Y + velocity.Y < num6)
                 {
                     velocity.Y = num6 - base.Center.Y;
                 }
             }
             else
             {
                 velocity.Y = num6 - base.Center.Y;
             }
         }
         else
         {
             if (velocity.Y == 0f)
             {
                 velocity.X *= 0.95f;
             }
             velocity.X *= 0.98f;
             velocity.Y += 0.3f;
             if (velocity.Y > 15.9f)
             {
                 velocity.Y = 15.9f;
             }
         }
         if (frameCounter == 0)
         {
             frameCounter = 1;
             frame = Main.rand.Next(4);
         }
         if (frameCounter < 10 && wet)
         {
             frameCounter++;
             for (float num7 = 0f; num7 < 1f; num7 += 0.5f)
             {
                 Gore gore = Gore.NewGoreDirect(position + Vector2.UnitY * 6f, Vector2.Zero, 1201, scale * 0.7f);
                 gore.velocity = Main.rand.NextVector2CircularEdge(10f, 10f);
                 if (gore.velocity.Y > 0f)
                 {
                     gore.velocity.Y *= -1f;
                 }
             }
             for (float num8 = 0f; num8 < 2f; num8 += 1f)
             {
                 Gore gore2 = Gore.NewGoreDirect(position + Vector2.UnitY * 6f, Vector2.Zero, 1208, scale * 0.7f + Main.rand.NextFloat() * 0.15f);
                 gore2.velocity = Main.rand.NextVector2CircularEdge(4f, 4f);
                 if (gore2.velocity.Y > 0f)
                 {
                     gore2.velocity.Y *= -1f;
                 }
             }
         }
         scale = Utils.GetLerpValue(0f, 60f, timeLeft, clamped: true);
         rotation += velocity.X * 0.14f;
         bool flag = !wet && velocity.Length() < 0.8f;
         int maxValue = (wet ? 90 : 5);
         if (Main.rand.Next(maxValue) == 0 && !flag)
         {
             Gore gore3 = Gore.NewGoreDirect(position + Vector2.UnitY * 6f, Vector2.Zero, 1201, scale * 0.7f);
             if (wet)
             {
                 gore3.velocity = Vector2.UnitX * Main.rand.NextFloatDirection() * 0.75f + Vector2.UnitY * Main.rand.NextFloat();
             }
             else if (gore3.velocity.Y < 0f)
             {
                 gore3.velocity.Y = 0f - gore3.velocity.Y;
             }
         }
         Vector2 spot = base.Center + Vector2.UnitY * 16f;
         if (ai[0] >= 10f && timeLeft > 60)
         {
             timeLeft = 60;
             netUpdate = true;
         }
         if (ai[0] < 10f && timeLeft > 60)
         {
             Main.instance.ChumBucketProjectileHelper.AddChumLocation(spot);
         }
     }
References Entity.active, ChumBucketProjectileHelper.AddChumLocation(), Main.ChumBucketProjectileHelper, Utils.GetLerpValue(), Main.instance, Gore.NewGoreDirect(), UnifiedRandom.Next(), Entity.position, Main.projectile, Main.rand, Main.tile, type, and Gore.velocity.