Terraria: Projectile.AI_165_Whip
AI_165_Whip()
void Projectile.AI_165_Whip () inline private
     {
         Player player = Main.player[owner];
         rotation = velocity.ToRotation() + (float)Math.PI / 2f;
         ai[0] += 1f;
         GetWhipSettings(this, out var timeToFlyOut, out var _, out var _);
         base.Center = Main.GetPlayerArmPosition(this) + velocity * (ai[0] - 1f);
         spriteDirection = ((!(Vector2.Dot(velocity, Vector2.UnitX) < 0f)) ? 1 : (-1));
         if (ai[0] >= timeToFlyOut)
         {
             Kill();
             return;
         }
         player.heldProj = whoAmI;
         player.MatchItemTimeToItemAnimation();
         if (ai[0] == (float)(int)(timeToFlyOut / 2f))
         {
             WhipPointsForCollision.Clear();
             FillWhipControlPoints(this, WhipPointsForCollision);
             Vector2 vector = WhipPointsForCollision[WhipPointsForCollision.Count - 1];
             SoundEngine.PlaySound(SoundID.Item153, vector);
         }
         switch (type)
         {
         case 848:
         {
             float t3 = ai[0] / timeToFlyOut;
             float num5 = Utils.GetLerpValue(0.1f, 0.7f, t3, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t3, clamped: true);
             if (num5 > 0.1f && Main.rand.NextFloat() < num5 / 2f)
             {
                 WhipPointsForCollision.Clear();
                 FillWhipControlPoints(this, WhipPointsForCollision);
                 Rectangle r4 = Utils.CenteredRectangle(WhipPointsForCollision[WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                 int num6 = Dust.NewDust(r4.TopLeft(), r4.Width, r4.Height, 172, 0f, 0f, 100, default(Color), 1.5f);
                 Main.dust[num6].noGravity = true;
                 Main.dust[num6].velocity.X /= 2f;
                 Main.dust[num6].velocity.Y /= 2f;
             }
             break;
         }
         case 847:
         {
             float t2 = ai[0] / timeToFlyOut;
             if (Utils.GetLerpValue(0.1f, 0.7f, t2, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t2, clamped: true) > 0.5f && Main.rand.Next(3) != 0)
             {
                 WhipPointsForCollision.Clear();
                 FillWhipControlPoints(this, WhipPointsForCollision);
                 int num2 = Main.rand.Next(WhipPointsForCollision.Count - 10, WhipPointsForCollision.Count);
                 Rectangle r2 = Utils.CenteredRectangle(WhipPointsForCollision[num2], new Vector2(30f, 30f));
                 int num3 = 57;
                 if (Main.rand.Next(3) == 0)
                 {
                     num3 = 43;
                 }
                 Dust dust3 = Dust.NewDustDirect(r2.TopLeft(), r2.Width, r2.Height, num3, 0f, 0f, 100, Color.White);
                 dust3.position = WhipPointsForCollision[num2];
                 dust3.fadeIn = 0.3f;
                 Vector2 spinningpoint = WhipPointsForCollision[num2] - WhipPointsForCollision[num2 - 1];
                 dust3.noGravity = true;
                 dust3.velocity *= 0.5f;
                 dust3.velocity += spinningpoint.RotatedBy((float)player.direction * ((float)Math.PI / 2f));
                 dust3.velocity *= 0.5f;
             }
             break;
         }
         case 849:
         {
             float num4 = ai[0] / timeToFlyOut;
             Utils.GetLerpValue(0.1f, 0.7f, num4, clamped: true);
             Utils.GetLerpValue(0.9f, 0.7f, num4, clamped: true);
             if (num4 > 0.4f && Main.rand.Next(9) != 0)
             {
                 WhipPointsForCollision.Clear();
                 FillWhipControlPoints(this, WhipPointsForCollision);
                 Rectangle r3 = Utils.CenteredRectangle(WhipPointsForCollision[WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                 Vector2 vector3 = WhipPointsForCollision[WhipPointsForCollision.Count - 2].DirectionTo(WhipPointsForCollision[WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                 Dust dust4 = Dust.NewDustDirect(r3.TopLeft(), r3.Width, r3.Height, 191, 0f, 0f, 0, default(Color), 1.3f);
                 dust4.noGravity = true;
                 dust4.velocity += vector3 * 2f;
                 if (Main.rand.Next(2) == 0)
                 {
                     ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.BlackLightningSmall, new ParticleOrchestraSettings
                     {
                         MovementVector = vector3,
                         PositionInWorld = r3.Center.ToVector2()
                     }, owner);
                 }
                 Lighting.AddLight(r3.Center.ToVector2(), new Vector3(0.2f, 0f, 0.4f));
             }
             break;
         }
         case 915:
         {
             float t5 = ai[0] / timeToFlyOut;
             if (Utils.GetLerpValue(0.1f, 0.7f, t5, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t5, clamped: true) > 0.1f)
             {
                 WhipPointsForCollision.Clear();
                 FillWhipControlPoints(this, WhipPointsForCollision);
                 Rectangle r6 = Utils.CenteredRectangle(WhipPointsForCollision[WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                 Vector2 vector5 = WhipPointsForCollision[WhipPointsForCollision.Count - 2].DirectionTo(WhipPointsForCollision[WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                 Dust dust7 = Dust.NewDustDirect(r6.TopLeft(), r6.Width, r6.Height, 267, 0f, 0f, 0, Main.hslToRgb(player.miscCounterNormalized * 9f % 1f, 1f, 0.5f), 1.3f);
                 dust7.velocity *= Main.rand.NextFloat() * 0.8f;
                 dust7.noGravity = true;
                 dust7.scale = 0.9f + Main.rand.NextFloat() * 0.9f;
                 dust7.fadeIn = Main.rand.NextFloat() * 0.9f;
                 dust7.velocity += vector5 * 2f;
                 if (dust7.dustIndex != 6000)
                 {
                     Dust dust8 = Dust.CloneDust(dust7);
                     dust8.scale /= 2f;
                     dust8.fadeIn *= 0.85f;
                     dust8.color = new Color(255, 255, 255, 255);
                 }
             }
             break;
         }
         case 914:
         {
             float t6 = ai[0] / timeToFlyOut;
             float num8 = Utils.GetLerpValue(0.1f, 0.7f, t6, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t6, clamped: true);
             if (num8 > 0.1f && Main.rand.NextFloat() < num8 / 2f)
             {
                 WhipPointsForCollision.Clear();
                 FillWhipControlPoints(this, WhipPointsForCollision);
                 Rectangle r7 = Utils.CenteredRectangle(WhipPointsForCollision[WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                 Vector2 vector6 = WhipPointsForCollision[WhipPointsForCollision.Count - 2].DirectionTo(WhipPointsForCollision[WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                 Dust dust9 = Dust.NewDustDirect(r7.TopLeft(), r7.Width, r7.Height, 39, 0f, 0f, 0, default(Color), 1.2f);
                 dust9.noGravity = Main.rand.Next(3) == 0;
                 dust9.velocity += vector6 * 2f;
             }
             break;
         }
         case 952:
         {
             float t7 = ai[0] / timeToFlyOut;
             float num9 = Utils.GetLerpValue(0.1f, 0.7f, t7, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t7, clamped: true);
             if (num9 > 0.15f && Main.rand.NextFloat() < num9)
             {
                 WhipPointsForCollision.Clear();
                 FillWhipControlPoints(this, WhipPointsForCollision);
                 Rectangle r8 = Utils.CenteredRectangle(WhipPointsForCollision[WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
                 Vector2 vector7 = WhipPointsForCollision[WhipPointsForCollision.Count - 2].DirectionTo(WhipPointsForCollision[WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
                 Dust dust10 = Dust.NewDustDirect(r8.TopLeft(), r8.Width, r8.Height, 26, 0f, 0f, 0, default(Color), 0.7f);
                 dust10.noGravity = Main.rand.Next(3) == 0;
                 if (dust10.noGravity)
                 {
                     dust10.scale += 0.4f;
                 }
                 dust10.velocity += vector7 * 2f;
             }
             break;
         }
         case 912:
         {
             float t4 = ai[0] / timeToFlyOut;
             float num7 = Utils.GetLerpValue(0.1f, 0.7f, t4, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t4, clamped: true);
             if (!(num7 > 0.1f) || !(Main.rand.NextFloat() < num7 / 2f))
             {
                 break;
             }
             WhipPointsForCollision.Clear();
             FillWhipControlPoints(this, WhipPointsForCollision);
             Rectangle r5 = Utils.CenteredRectangle(WhipPointsForCollision[WhipPointsForCollision.Count - 1], new Vector2(30f, 30f));
             Vector2 vector4 = WhipPointsForCollision[WhipPointsForCollision.Count - 2].DirectionTo(WhipPointsForCollision[WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
             for (int j = 0; j < 3; j++)
             {
                 Dust dust5 = Dust.NewDustDirect(r5.TopLeft(), r5.Width, r5.Height, 16, 0f, 0f, 0, default(Color), 1.2f);
                 dust5.noGravity = true;
                 dust5.velocity += vector4 * 2f;
             }
             for (int k = 0; k < 1; k++)
             {
                 Dust.NewDustDirect(r5.TopLeft(), r5.Width, r5.Height, 13, 0f, 0f, 0, default(Color), 0.8f).velocity += vector4 * 2f;
             }
             for (int l = 0; l < 3; l++)
             {
                 if (Main.rand.Next(2) != 0)
                 {
                     Dust dust6 = Dust.NewDustDirect(r5.TopLeft(), r5.Width, r5.Height, 261, 0f, 0f, 0, Color.Transparent, 0.8f);
                     dust6.velocity += vector4 * 2f;
                     dust6.velocity *= 0.3f;
                     dust6.noGravity = true;
                 }
             }
             Lighting.AddLight(r5.Center.ToVector2(), new Vector3(0.1f, 0.1f, 0.2f));
             break;
         }
         case 913:
         {
             float t = ai[0] / timeToFlyOut;
             float num = Utils.GetLerpValue(0.1f, 0.7f, t, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t, clamped: true);
             if (!(num > 0.1f) || !(Main.rand.NextFloat() < num))
             {
                 break;
             }
             WhipPointsForCollision.Clear();
             FillWhipControlPoints(this, WhipPointsForCollision);
             Rectangle r = Utils.CenteredRectangle(WhipPointsForCollision[WhipPointsForCollision.Count - 1], new Vector2(20f, 20f));
             Vector2 vector2 = WhipPointsForCollision[WhipPointsForCollision.Count - 2].DirectionTo(WhipPointsForCollision[WhipPointsForCollision.Count - 1]).SafeNormalize(Vector2.Zero);
             for (int i = 0; i < 3; i++)
             {
                 if (Main.rand.Next(3) != 0)
                 {
                     continue;
                 }
                 if (Main.rand.Next(7) == 0)
                 {
                     Dust dust = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, 31);
                     dust.velocity.X /= 2f;
                     dust.velocity.Y /= 2f;
                     dust.velocity += vector2 * 2f;
                     dust.fadeIn = 1f + Main.rand.NextFloat() * 0.6f;
                     dust.noGravity = true;
                     continue;
                 }
                 Dust dust2 = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, 6, 0f, 0f, 0, default(Color), 1.2f);
                 dust2.velocity += vector2 * 2f;
                 if (Main.rand.Next(3) != 0)
                 {
                     dust2.fadeIn = 0.7f + Main.rand.NextFloat() * 0.9f;
                     dust2.scale = 0.6f;
                     dust2.noGravity = true;
                 }
             }
             break;
         }
         }
     }
References Lighting.AddLight(), Entity.Center, Utils.CenteredRectangle(), Dust.CloneDust(), Color, Dust.color, Entity.direction, Main.dust, Dust.dustIndex, Dust.fadeIn, Utils.GetLerpValue(), Main.GetPlayerArmPosition(), Player.heldProj, Main.hslToRgb(), SoundID.Item153, Player.MatchItemTimeToItemAnimation(), Player.miscCounterNormalized, Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.player, SoundEngine.PlaySound(), Dust.position, Main.rand, ParticleOrchestrator.RequestParticleSpawn(), Dust.scale, and Dust.velocity.