Terraria: Projectile.HandleMovement
HandleMovement()
void Projectile.HandleMovement (Vector2 wetVelocity, out int overrideWidth, out int overrideHeight) inline private
     {
         bool flag = false;
         overrideWidth = -1;
         overrideHeight = -1;
         bool flag2 = false;
         bool? flag3 = ProjectileID.Sets.ForcePlateDetection[type];
         bool flag4 = flag3.HasValue && !flag3.Value;
         bool flag5 = flag3.HasValue && flag3.Value;
         if (tileCollide)
         {
             Vector2 lastVelocity = velocity;
             bool flag6 = true;
             Vector2? vector = null;
             if (Main.projPet[type])
             {
                 flag6 = false;
                 if (Main.player[owner].position.Y + (float)Main.player[owner].height - 12f > position.Y + (float)height)
                 {
                     flag6 = true;
                 }
             }
             if (type == 500)
             {
                 flag6 = false;
                 if (Main.player[owner].Bottom.Y > base.Bottom.Y + 4f)
                 {
                     flag6 = true;
                 }
             }
             if (type == 653 || type == 668)
             {
                 flag6 = false;
                 if (Main.player[owner].Bottom.Y > base.Bottom.Y + 4f)
                 {
                     flag6 = true;
                 }
             }
             if (aiStyle == 62)
             {
                 flag6 = true;
             }
             if (aiStyle == 66)
             {
                 flag6 = true;
             }
             if (type == 317)
             {
                 flag6 = true;
             }
             if (type == 373)
             {
                 flag6 = true;
             }
             if (aiStyle == 53)
             {
                 flag6 = false;
             }
             if (type == 9 || type == 12 || type == 15 || type == 13)
             {
                 flag6 = false;
             }
             if (aiStyle == 10 && ProjectileID.Sets.FallingBlockDoesNotFallThroughPlatforms[type])
             {
                 flag6 = false;
             }
             if (type == 24)
             {
                 flag6 = false;
             }
             switch (type)
             {
             case 663:
             case 665:
             case 667:
             case 677:
             case 678:
             case 679:
             case 688:
             case 689:
             case 690:
             case 691:
             case 692:
             case 693:
                 flag6 = false;
                 break;
             case 759:
                 flag6 = true;
                 break;
             case 1020:
             {
                 float num = MathHelper.WrapAngle(rotation);
                 flag6 = num >= (float)Math.PI / 2f || num < -(float)Math.PI / 2f;
                 break;
             }
             }
             if (decidesManualFallThrough)
             {
                 flag6 = shouldFallThrough;
             }
             if (type == 771 || type == 822 || type == 823 || type == 843 || type == 846 || type == 845 || type == 852)
             {
                 overrideWidth = width;
                 overrideHeight = 34;
                 vector = new Vector2(0.75f, 0.75f);
             }
             if (type == 969)
             {
                 overrideWidth = 18;
                 overrideHeight = 32;
             }
             if (type == 824 || type == 839 || type == 840 || type == 850 || type == 853)
             {
                 overrideWidth = width;
                 overrideHeight = 58;
                 vector = new Vector2(0.75f, 0.75f);
             }
             if (type == 826 || type == 830 || type == 838)
             {
                 overrideWidth = width;
                 overrideHeight = 38;
                 vector = new Vector2(0.75f, 0.75f);
             }
             if (type == 828 || type == 829 || type == 827 || type == 844)
             {
                 overrideWidth = width;
                 overrideHeight = 22;
                 vector = new Vector2(0.75f, 0.75f);
             }
             if (aiStyle == 29 || type == 28 || aiStyle == 49 || type == 906 || type == 903 || type == 904 || type == 910)
             {
                 overrideWidth = width - 8;
                 overrideHeight = height - 8;
             }
             else if (type == 250 || type == 267 || type == 297 || type == 323 || type == 3 || type == 711)
             {
                 overrideWidth = 6;
                 overrideHeight = 6;
             }
             else if (type == 308)
             {
                 overrideWidth = 26;
                 overrideHeight = height;
             }
             else if (type == 663 || type == 665 || type == 667 || type == 677 || type == 678 || type == 679 || type == 691 || type == 692 || type == 693)
             {
                 overrideWidth = 16;
                 overrideHeight = height;
             }
             else if (type == 688 || type == 689 || type == 690)
             {
                 overrideWidth = 16;
                 overrideHeight = height;
                 vector = new Vector2(0.5f, 1f);
             }
             else if (type == 669 || type == 706)
             {
                 overrideWidth = 10;
                 overrideHeight = 10;
             }
             else if (type == 261 || type == 277)
             {
                 overrideWidth = 26;
                 overrideHeight = 26;
             }
             else if (type == 481 || type == 491 || type == 106 || type == 262 || type == 271 || type == 270 || type == 272 || type == 273 || type == 274 || type == 280 || type == 288 || type == 301 || type == 320 || type == 333 || type == 335 || type == 343 || type == 344 || type == 497 || type == 496 || type == 6 || type == 19 || type == 113 || type == 52 || type == 520 || type == 523 || type == 585 || type == 598 || type == 599 || type == 636 || type == 837 || type == 861 || type == 867 || type == 971 || type == 975 || type == 1000)
             {
                 overrideWidth = 10;
                 overrideHeight = 10;
             }
             else if (type == 514)
             {
                 overrideWidth = 4;
                 overrideHeight = 4;
             }
             else if (type == 248 || type == 247 || type == 507 || type == 508 || type == 662 || type == 680 || type == 685 || type == 757 || type == 928)
             {
                 overrideWidth = width - 12;
                 overrideHeight = height - 12;
             }
             else if (aiStyle == 18 || type == 254)
             {
                 overrideWidth = width - 36;
                 overrideHeight = height - 36;
             }
             else if (type == 182 || type == 190 || type == 33 || type == 229 || type == 237 || type == 243 || type == 866)
             {
                 overrideWidth = width - 20;
                 overrideHeight = height - 20;
             }
             else if (aiStyle == 27)
             {
                 overrideWidth = width - 12;
                 overrideHeight = height - 12;
             }
             else if (type == 533 && ai[0] >= 6f)
             {
                 overrideWidth = width + 6;
                 overrideHeight = height + 6;
             }
             else if (type == 755 && ai[0] >= 0f)
             {
                 overrideWidth = width + 6;
                 overrideHeight = height + 6;
             }
             else if (type == 759)
             {
                 if (velocity.X != lastVelocity.X)
                 {
                     velocity.X = 0f - lastVelocity.X;
                 }
                 if (velocity.Y != lastVelocity.Y)
                 {
                     velocity.Y = 0f - lastVelocity.Y;
                 }
             }
             else if (type == 582 || type == 634 || type == 635 || type == 902)
             {
                 overrideWidth = 8;
                 overrideHeight = 8;
             }
             else if (type == 617)
             {
                 overrideWidth = (int)(20f * scale);
                 overrideHeight = (int)(20f * scale);
             }
             else if (type == 304)
             {
                 overrideWidth = 4;
                 overrideHeight = 4;
             }
             else if (aiStyle == 9)
             {
                 overrideWidth = 4;
                 overrideHeight = 4;
             }
             else if (type == 931)
             {
                 overrideWidth = 4;
                 overrideHeight = 4;
             }
             if (((type != 440 && type != 449 && type != 606) || ai[1] != 1f) && (type != 466 || localAI[1] != 1f) && (type != 580 || !(localAI[1] > 0f)) && (type != 640 || !(localAI[1] > 0f)))
             {
                 if (aiStyle == 10)
                 {
                     if (type >= 736 && type <= 738)
                     {
                         velocity = Collision.TileCollision(position, velocity, width, height, flag6, flag6);
                     }
                     else if (type == 411 || type == 412 || type == 413 || type == 414)
                     {
                         velocity = Collision.TileCollision(position, velocity, width, height, flag6, flag6);
                         velocity = Collision.AnyCollisionWithSpecificTiles(position, velocity, width, height, TileID.Sets.Falling, evenActuated: true);
                     }
                     else if (type == 42 || type == 65 || type == 68 || type == 354 || (type == 31 && ai[0] == 2f))
                     {
                         velocity = Collision.TileCollision(position, velocity, width, height, flag6, flag6);
                     }
                     else
                     {
                         velocity = Collision.TileCollision(position, velocity, width, height, flag6, flag6);
                     }
                 }
                 else
                 {
                     Vector2 vector2 = position;
                     int num2 = ((overrideWidth != -1) ? overrideWidth : width);
                     int num3 = ((overrideHeight != -1) ? overrideHeight : height);
                     if (overrideHeight != -1 || overrideWidth != -1)
                     {
                         vector2 = ((!vector.HasValue) ? new Vector2(position.X + (float)(width / 2) - (float)(num2 / 2), position.Y + (float)(height / 2) - (float)(num3 / 2)) : (base.Center - new Vector2(num2, num3) * vector.Value));
                     }
                     if (wet)
                     {
                         if (shimmerWet)
{
                             Vector2 vector3 = velocity;
                             velocity = Collision.TileCollision(vector2, velocity, num2, num3, flag6, flag6);
                             wetVelocity = velocity * 0.375f;
                             if (velocity.X != vector3.X)
{
                                 wetVelocity.X = velocity.X;
                             }
                             if (velocity.Y != vector3.Y)
{
                                 wetVelocity.Y = velocity.Y;
                             }
                         }
                         else if (honeyWet)
{
                             Vector2 vector4 = velocity;
                             velocity = Collision.TileCollision(vector2, velocity, num2, num3, flag6, flag6);
                             wetVelocity = velocity * 0.25f;
                             if (velocity.X != vector4.X)
{
                                 wetVelocity.X = velocity.X;
                             }
                             if (velocity.Y != vector4.Y)
{
                                 wetVelocity.Y = velocity.Y;
                             }
                         }
                         else
{
                             Vector2 vector5 = velocity;
                             velocity = Collision.TileCollision(vector2, velocity, num2, num3, flag6, flag6);
                             wetVelocity = velocity * 0.5f;
                             if (velocity.X != vector5.X)
{
                                 wetVelocity.X = velocity.X;
                             }
                             if (velocity.Y != vector5.Y)
{
                                 wetVelocity.Y = velocity.Y;
                             }
                         }
                         if (!Main.projPet[type])
{
                             Vector4 vector6 = Collision.SlopeCollision(vector2, velocity, num2, num3, 0f, fall: true);
                             Vector2 vector7 = position - vector2;
                             if (aiStyle == 137)
{
                                 if (vector2.Y != vector6.Y)
{
                                     flag = true;
                                 }
                                 if (velocity.Y != vector6.W)
{
                                     flag = true;
                                 }
                                 vector2.Y = vector6.Y;
                                 position.Y = vector2.Y + vector7.Y;
                                 velocity.Y = vector6.W;
                             }
                             else
{
                                 if (vector2.X != vector6.X)
{
                                     flag = true;
                                 }
                                 if (vector2.Y != vector6.Y)
{
                                     flag = true;
                                 }
                                 if (velocity.X != vector6.Z)
{
                                     flag = true;
                                 }
                                 if (velocity.Y != vector6.W)
{
                                     flag = true;
                                 }
                                 vector2.X = vector6.X;
                                 vector2.Y = vector6.Y;
                                 position = vector2 + vector7;
                                 velocity.X = vector6.Z;
                                 velocity.Y = vector6.W;
                             }
                         }
                     }
                     else
                     {
                         int num4 = Math.Min(num2, num3);
                         if (num4 < 3)
{
                             num4 = 3;
                         }
                         if (num4 > 16)
{
                             num4 = 16;
                         }
                         if (velocity.Length() > (float)num4)
{
                             Vector2 vector8 = Collision.TileCollision(vector2, velocity, num2, num3, flag6, flag6);
                             float num5 = velocity.Length();
                             float num6 = num4;
                             Vector2 vector9 = velocity.SafeNormalize(Vector2.Zero);
                             if (vector8.Y == 0f)
{
                                 vector9.Y = 0f;
                             }
                             Vector2 zero = Vector2.Zero;
                             _ = Vector2.Zero;
                             _ = Vector2.Zero;
                             Vector2 vector10 = vector2;
                             int num7 = 0;
                             while (num5 > 0f)
{
                                 num7++;
                                 if (num7 > 300)
{
                                     break;
                                 }
                                 vector10 = vector2;
                                 float num8 = num5;
                                 if (num8 > num6)
{
                                     num8 = num6;
                                 }
                                 num5 -= num8;
                                 Vector2 vector11 = vector9 * num8;
                                 Vector2 vector12 = Collision.TileCollision(vector2, vector11, num2, num3, flag6, flag6);
                                 vector2 += vector12;
                                 velocity = vector12;
                                 if (!Main.projPet[type])
{
                                     Vector4 vector13 = Collision.SlopeCollision(vector2, velocity, num2, num3, 0f, fall: true);
                                     Vector2 vector14 = position - vector2;
                                     if (aiStyle == 137)
{
                                         if (vector2.Y != vector13.Y)
{
                                             flag = true;
                                         }
                                         if (velocity.Y != vector13.W)
{
                                             flag = true;
                                         }
                                         vector2.Y = vector13.Y;
                                         position.Y = vector2.Y + vector14.Y;
                                         velocity.Y = vector13.W;
                                     }
                                     else
{
                                         if (vector2.X != vector13.X)
{
                                             flag = true;
                                         }
                                         if (vector2.Y != vector13.Y)
{
                                             flag = true;
                                         }
                                         if (velocity.X != vector13.Z)
{
                                             flag = true;
                                         }
                                         if (velocity.Y != vector13.W)
{
                                             flag = true;
                                         }
                                         vector2.X = vector13.X;
                                         vector2.Y = vector13.Y;
                                         position = vector2 + vector14;
                                         velocity.X = vector13.Z;
                                         velocity.Y = vector13.W;
                                     }
                                 }
                                 flag2 = true;
                                 if (owner == Main.myPlayer && vector2 != vector10 && !flag4)
{
                                     Collision.SwitchTiles(vector2, num2, num3, vector10, 4);
                                 }
                                 vector12 = velocity;
                                 zero += vector12;
                             }
                             velocity = zero;
                             if (Math.Abs(velocity.X - lastVelocity.X) < 0.0001f)
{
                                 velocity.X = lastVelocity.X;
                             }
                             if (Math.Abs(velocity.Y - lastVelocity.Y) < 0.0001f)
{
                                 velocity.Y = lastVelocity.Y;
                             }
                             if (!Main.projPet[type])
{
                                 Vector4 vector15 = Collision.SlopeCollision(vector2, velocity, num2, num3, 0f, fall: true);
                                 Vector2 vector16 = position - vector2;
                                 if (aiStyle == 137)
{
                                     if (vector2.Y != vector15.Y)
{
                                         flag = true;
                                     }
                                     if (velocity.Y != vector15.W)
{
                                         flag = true;
                                     }
                                     vector2.Y = vector15.Y;
                                     position.Y = vector2.Y + vector16.Y;
                                     velocity.Y = vector15.W;
                                 }
                                 else
{
                                     if (vector2.X != vector15.X)
{
                                         flag = true;
                                     }
                                     if (vector2.Y != vector15.Y)
{
                                         flag = true;
                                     }
                                     if (velocity.X != vector15.Z)
{
                                         flag = true;
                                     }
                                     if (velocity.Y != vector15.W)
{
                                         flag = true;
                                     }
                                     vector2.X = vector15.X;
                                     vector2.Y = vector15.Y;
                                     position = vector2 + vector16;
                                     velocity.X = vector15.Z;
                                     velocity.Y = vector15.W;
                                 }
                             }
                         }
                         else
{
                             velocity = Collision.TileCollision(vector2, velocity, num2, num3, flag6, flag6);
                             if (!Main.projPet[type])
{
                                 Vector4 vector17 = Collision.SlopeCollision(vector2, velocity, num2, num3, 0f, fall: true);
                                 Vector2 vector18 = position - vector2;
                                 if (aiStyle == 137)
{
                                     if (vector2.Y != vector17.Y)
{
                                         flag = true;
                                     }
                                     if (velocity.Y != vector17.W)
{
                                         flag = true;
                                     }
                                     vector2.Y = vector17.Y;
                                     position.Y = vector2.Y + vector18.Y;
                                     velocity.Y = vector17.W;
                                 }
                                 else
{
                                     if (vector2.X != vector17.X)
{
                                         flag = true;
                                     }
                                     if (vector2.Y != vector17.Y)
{
                                         flag = true;
                                     }
                                     if (velocity.X != vector17.Z)
{
                                         flag = true;
                                     }
                                     if (velocity.Y != vector17.W)
{
                                         flag = true;
                                     }
                                     vector2.X = vector17.X;
                                     vector2.Y = vector17.Y;
                                     position = vector2 + vector18;
                                     velocity.X = vector17.Z;
                                     velocity.Y = vector17.W;
                                 }
                             }
                         }
                     }
                 }
             }
             if (lastVelocity != velocity)
             {
                 flag = true;
             }
             if (flag)
             {
                 if (owner == Main.myPlayer && CanCutTiles() && (friendly || hostile) && damage > 0)
                 {
                     int num9 = (int)(position.X + velocity.X - 1f) / 16;
                     int num10 = (int)((position.X + (float)width + velocity.X + 1f) / 16f) + 1;
                     int num11 = (int)(position.Y + velocity.Y - 1f) / 16;
                     int num12 = (int)((position.Y + (float)height + velocity.Y + 1f) / 16f) + 1;
                     if (num9 < 0)
                     {
                         num9 = 0;
                     }
                     if (num10 > Main.maxTilesX)
                     {
                         num10 = Main.maxTilesX;
                     }
                     if (num11 < 0)
                     {
                         num11 = 0;
                     }
                     if (num12 > Main.maxTilesY)
                     {
                         num12 = Main.maxTilesY;
                     }
                     bool[] tileCutIgnorance = Main.player[owner].GetTileCutIgnorance(allowRegrowth: false, trap);
                     for (int i = num9; i < num10; i++)
                     {
                         for (int j = num11; j < num12; j++)
{
                             if (Main.tile[i, j] != null && !tileCutIgnorance[Main.tile[i, j].type] && Main.tile[i, j].type == 484 && WorldGen.CanCutTile(i, j, TileCuttingContext.AttackProjectile))
{
                                 WorldGen.KillTile(i, j);
                                 if (Main.netMode != 0)
{
                                     NetMessage.SendData(17, -1, -1, null, 0, i, j);
                                 }
                             }
                         }
                     }
                 }
                 if (Main.rand.Next(3) == 0 && owner == Main.myPlayer && CanCutTiles() && (friendly || hostile) && damage > 0)
                 {
                     int num13 = (int)(position.X + velocity.X - 1f) / 16;
                     int num14 = (int)((position.X + (float)width + velocity.X + 1f) / 16f) + 1;
                     int num15 = (int)(position.Y + velocity.Y - 1f) / 16;
                     int num16 = (int)((position.Y + (float)height + velocity.Y + 1f) / 16f) + 1;
                     if (num13 < 0)
                     {
                         num13 = 0;
                     }
                     if (num14 > Main.maxTilesX)
                     {
                         num14 = Main.maxTilesX;
                     }
                     if (num15 < 0)
                     {
                         num15 = 0;
                     }
                     if (num16 > Main.maxTilesY)
                     {
                         num16 = Main.maxTilesY;
                     }
                     bool[] tileCutIgnorance2 = Main.player[owner].GetTileCutIgnorance(allowRegrowth: false, trap);
                     for (int k = num13; k < num14; k++)
                     {
                         for (int l = num15; l < num16; l++)
{
                             if (Main.tile[k, l] != null && !tileCutIgnorance2[Main.tile[k, l].type] && TileID.Sets.CrackedBricks[Main.tile[k, l].type] && WorldGen.CanCutTile(k, l, TileCuttingContext.AttackProjectile))
{
                                 WorldGen.KillTile(k, l);
                                 if (Main.netMode != 0)
{
                                     NetMessage.SendData(17, -1, -1, null, 0, k, l);
                                 }
                             }
                         }
                     }
                 }
                 if (type == 663 || type == 665 || type == 667 || type == 677 || type == 678 || type == 679 || type == 691 || type == 692 || type == 693 || type == 688 || type == 689 || type == 690)
                 {
                     position += velocity;
                     velocity = Vector2.Zero;
                 }
                 else if (type == 434)
                 {
                     position += velocity;
                     numUpdates = 0;
                 }
                 else if (type == 1020)
                 {
                     if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 1f)
                     {
                         velocity.X = (0f - lastVelocity.X) * 0.25f;
                     }
                     if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 1f)
                     {
                         velocity.Y = (0f - lastVelocity.Y) * 0.25f;
                     }
                 }
                 else if (type == 601)
                 {
                     if (Main.netMode != 2 && alpha > 0)
                     {
                         if (ai[1] != 0f)
{
                             SoundEngine.PlaySound(SoundID.Item114, position);
                         }
                         else
{
                             SoundEngine.PlaySound(SoundID.Item115, position);
                         }
                     }
                     if (owner == Main.myPlayer)
                     {
                         PortalHelper.TryPlacingPortal(this, lastVelocity, velocity);
                     }
                     position += velocity;
                     Kill();
                 }
                 else if (type == 985)
                 {
                     position += velocity;
                     velocity = lastVelocity;
                     velocity *= 0.01f;
                     localAI[1] = 1f;
                 }
                 else if (type == 451)
                 {
                     ai[0] = 1f;
                     ai[1] = 0f;
                     netUpdate = true;
                     velocity = lastVelocity / 2f;
                 }
                 else if (type == 645)
                 {
                     ai[0] = 0f;
                     ai[1] = -1f;
                     netUpdate = true;
                 }
                 else if (type == 584)
                 {
                     bool flag7 = false;
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = lastVelocity.X * -0.75f;
                         flag7 = true;
                     }
                     if ((velocity.Y != lastVelocity.Y && lastVelocity.Y > 2f) || velocity.Y == 0f)
                     {
                         velocity.Y = lastVelocity.Y * -0.75f;
                         flag7 = true;
                     }
                     if (flag7)
                     {
                         float num17 = lastVelocity.Length() / velocity.Length();
                         if (num17 == 0f)
{
                             num17 = 1f;
                         }
                         velocity /= num17;
                         penetrate--;
                     }
                 }
                 else if (type == 532)
                 {
                     bool flag8 = false;
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = lastVelocity.X * -0.75f;
                         flag8 = true;
                     }
                     if ((velocity.Y != lastVelocity.Y && lastVelocity.Y > 2f) || velocity.Y == 0f)
                     {
                         velocity.Y = lastVelocity.Y * -0.75f;
                         flag8 = true;
                     }
                     if (flag8)
                     {
                         float num18 = lastVelocity.Length() / velocity.Length();
                         if (num18 == 0f)
{
                             num18 = 1f;
                         }
                         velocity /= num18;
                         penetrate--;
                         Collision.HitTiles(position, lastVelocity, width, height);
                     }
                 }
                 else if (type == 533)
                 {
                     float num19 = 1f;
                     bool flag9 = false;
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = lastVelocity.X * (0f - num19);
                         flag9 = true;
                     }
                     if (velocity.Y != lastVelocity.Y || velocity.Y == 0f)
                     {
                         velocity.Y = lastVelocity.Y * (0f - num19) * 0.5f;
                         flag9 = true;
                     }
                     if (flag9)
                     {
                         float num20 = lastVelocity.Length() / velocity.Length();
                         if (num20 == 0f)
{
                             num20 = 1f;
                         }
                         velocity /= num20;
                         if (ai[0] == 7f && (double)velocity.Y < -0.1)
{
                             velocity.Y += 0.1f;
                         }
                         if (ai[0] >= 6f && ai[0] < 9f)
{
                             Collision.HitTiles(position, lastVelocity, width, height);
                         }
                         localAI[2] += 30f;
                     }
                 }
                 else if (type == 502)
                 {
                     ai[0] += 1f;
                     SoundEngine.PlaySound(37, (int)position.X, (int)position.Y, 5 + (int)ai[0]);
                     if (ai[0] >= 5f)
                     {
                         position += velocity;
                         Kill();
                     }
                     else
                     {
                         if (velocity.Y != lastVelocity.Y)
{
                             velocity.Y = 0f - lastVelocity.Y;
                         }
                         if (velocity.X != lastVelocity.X)
{
                             velocity.X = 0f - lastVelocity.X;
                         }
                     }
                     Vector2 spinningpoint = new Vector2(0f, -3f - ai[0]).RotatedByRandom(3.1415927410125732);
                     float num21 = 10f + ai[0] * 4f;
                     Vector2 vector19 = new Vector2(1.05f, 1f);
                     for (float num22 = 0f; num22 < num21; num22 += 1f)
                     {
                         int num23 = Dust.NewDust(base.Center, 0, 0, 66, 0f, 0f, 0, Color.Transparent);
                         Main.dust[num23].position = base.Center;
                         Main.dust[num23].velocity = spinningpoint.RotatedBy((float)Math.PI * 2f * num22 / num21) * vector19 * (0.8f + Main.rand.NextFloat() * 0.4f);
                         Main.dust[num23].color = Main.hslToRgb(num22 / num21, 1f, 0.5f);
                         Main.dust[num23].noGravity = true;
                         Main.dust[num23].scale = 1f + ai[0] / 3f;
                     }
                     if (Main.myPlayer == owner)
                     {
                         int num24 = width;
                         int num25 = height;
                         int num26 = penetrate;
                         position = base.Center;
                         width = (height = 40 + 8 * (int)ai[0]);
                         base.Center = position;
                         penetrate = -1;
                         Damage();
                         penetrate = num26;
                         position = base.Center;
                         width = num24;
                         height = num25;
                         base.Center = position;
                     }
                 }
                 else if (type == 444)
                 {
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = 0f - lastVelocity.X;
                     }
                     if (velocity.Y != lastVelocity.Y)
                     {
                         velocity.Y = 0f - lastVelocity.Y;
                     }
                     ai[0] = velocity.ToRotation();
                 }
                 else if (type == 617)
                 {
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = (0f - lastVelocity.X) * 0.35f;
                     }
                     if (velocity.Y != lastVelocity.Y)
                     {
                         velocity.Y = (0f - lastVelocity.Y) * 0.35f;
                     }
                 }
                 else if (type == 440 || type == 449 || type == 606)
                 {
                     if (ai[1] != 1f)
                     {
                         ai[1] = 1f;
                         position += velocity;
                         velocity = lastVelocity;
                     }
                 }
                 else if (type == 85)
                 {
                     velocity = lastVelocity * 0.95f;
                     position -= velocity;
                 }
                 else if (type == 466 || type == 580 || type == 640)
                 {
                     if (localAI[1] < 1f)
                     {
                         localAI[1] += 2f;
                         position += velocity;
                         velocity = Vector2.Zero;
                     }
                 }
                 else if (type == 851)
                 {
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = (0f - lastVelocity.X) * 0.8f;
                     }
                     if (velocity.Y != lastVelocity.Y)
                     {
                         velocity.Y = (0f - lastVelocity.Y) * 0.5f;
                     }
                 }
                 else if (type == 855)
                 {
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = 0f - lastVelocity.X;
                     }
                     if (velocity.Y != lastVelocity.Y)
                     {
                         velocity.Y = 0f - lastVelocity.Y;
                         if (lastVelocity.Y < 0f)
{
                             velocity.Y *= 0.25f;
                         }
                     }
                 }
                 else if (aiStyle == 54)
                 {
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = lastVelocity.X * -0.6f;
                     }
                     if (velocity.Y != lastVelocity.Y)
                     {
                         velocity.Y = lastVelocity.Y * -0.6f;
                     }
                 }
                 else if (type == 861)
                 {
                     float num27 = -1f;
                     if (ai[1] == 1f)
                     {
                         num27 = -0.6f;
                     }
                     if (velocity.X != lastVelocity.X)
                     {
                         velocity.X = lastVelocity.X * num27;
                     }
                     if (velocity.Y != lastVelocity.Y && (double)lastVelocity.Y > 0.7)
                     {
                         velocity.Y = lastVelocity.Y * num27;
                     }
                     if (Math.Abs(velocity.Y) < 0.5f)
                     {
                         velocity.Y = 0f;
                     }
                     if (ai[1] != 1f)
                     {
                         netUpdate = true;
                     }
                     ai[1] = 1f;
                 }
                 else if (!Main.projPet[type] && type != 500 && type != 820 && aiStyle != 160 && type != 650 && type != 882 && type != 888 && type != 894 && type != 895 && type != 898 && type != 901 && type != 957)
                 {
                     if (aiStyle == 99)
                     {
                         if (type >= 556 && type <= 561)
{
                             bool flag10 = false;
                             if (velocity.X != lastVelocity.X)
{
                                 flag10 = true;
                                 velocity.X = lastVelocity.X * -1f;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 flag10 = true;
                                 velocity.Y = lastVelocity.Y * -1f;
                             }
                             if (flag10)
{
                                 Vector2 vector20 = Main.player[owner].Center - base.Center;
                                 vector20.Normalize();
                                 vector20 *= velocity.Length();
                                 vector20 *= 0.25f;
                                 velocity *= 0.75f;
                                 velocity += vector20;
                                 if (velocity.Length() > 6f)
{
                                     velocity *= 0.5f;
                                 }
                             }
                         }
                     }
                     else if (type == 604)
                     {
                         if (velocity.X != lastVelocity.X)
{
                             velocity.X = 0f - lastVelocity.X;
                         }
                         if (velocity.Y != lastVelocity.Y)
{
                             velocity.Y = 0f - lastVelocity.Y;
                         }
                     }
                     else if (type == 379)
                     {
                         if (velocity.X != lastVelocity.X)
{
                             velocity.X = lastVelocity.X * -0.6f;
                         }
                         if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 2f)
{
                             velocity.Y = lastVelocity.Y * -0.6f;
                         }
                     }
                     else if (type == 491)
                     {
                         if (ai[0] <= 0f)
{
                             ai[0] = -10f;
                         }
                         if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 0f)
{
                             velocity.X = lastVelocity.X * -1f;
                         }
                         if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 0f)
{
                             velocity.Y = lastVelocity.Y * -1f;
                         }
                     }
                     else if ((type >= 515 && type <= 517) || type == 637)
                     {
                         if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 1f)
{
                             velocity.X = lastVelocity.X * -0.9f;
                         }
                         if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 1f)
{
                             velocity.Y = lastVelocity.Y * -0.9f;
                         }
                     }
                     else if (type == 921 || type == 926 || type == 937)
                     {
                         if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 1f)
{
                             velocity.X = lastVelocity.X * -0.4f;
                         }
                         if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 1f)
{
                             velocity.Y = lastVelocity.Y * -0.95f;
                         }
                         penetrate--;
                     }
                     else if (type == 969)
                     {
                         if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 1f)
{
                             velocity.X = lastVelocity.X * -0.75f;
                         }
                         if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 1f)
{
                             velocity.Y = lastVelocity.Y * -0.75f;
                         }
                     }
                     else if (type == 681)
                     {
                         timeLeft = 4;
                     }
                     else if (type == 409)
                     {
                         if (velocity.X != lastVelocity.X)
{
                             velocity.X = lastVelocity.X * -1f;
                         }
                         if (velocity.Y != lastVelocity.Y)
{
                             velocity.Y = lastVelocity.Y * -1f;
                         }
                     }
                     else if (type == 254)
                     {
                         if (velocity.X != lastVelocity.X)
{
                             velocity.X = lastVelocity.X * -1f;
                         }
                         if (velocity.Y != lastVelocity.Y)
{
                             velocity.Y = lastVelocity.Y * -1f;
                         }
                     }
                     else if (type == 225)
                     {
                         ai[1] += 1f;
                         if (ai[1] == 1f)
{
                             damage = (int)((float)damage * 0.66f);
                         }
                         if (ai[1] >= 4f)
{
                             Kill();
                             return;
                         }
                         velocity.X = 0f - lastVelocity.X;
                         velocity.Y = 0f - lastVelocity.Y;
                         int num28 = FindTargetWithLineOfSight();
                         if (num28 != -1)
{
                             NPC nPC = Main.npc[num28];
                             float t = Distance(nPC.Center);
                             Vector2 vector21 = -Vector2.UnitY * MathHelper.Lerp((float)nPC.height * 0.1f, (float)nPC.height * 0.5f, Utils.GetLerpValue(0f, 300f, t));
                             velocity = DirectionTo(nPC.Center + vector21).SafeNormalize(-Vector2.UnitY) * velocity.Length();
                             netUpdate = true;
                         }
                     }
                     else if (type == 285)
                     {
                         ai[1] += 1f;
                         if (ai[1] == 1f)
{
                             damage = (int)((float)damage * 0.66f);
                         }
                         if (ai[1] >= 2f)
{
                             Kill();
                             return;
                         }
                         if (velocity.X != lastVelocity.X)
{
                             velocity.X = lastVelocity.X * -1f;
                         }
                         if (velocity.Y != lastVelocity.Y)
{
                             velocity.Y = lastVelocity.Y * -1f;
                         }
                         int num29 = FindTargetWithLineOfSight();
                         if (num29 != -1)
{
                             NPC nPC2 = Main.npc[num29];
                             Distance(nPC2.Center);
                             velocity = DirectionTo(nPC2.Center).SafeNormalize(-Vector2.UnitY) * velocity.Length();
                             netUpdate = true;
                         }
                     }
                     else if (type == 931)
                     {
                         if (velocity.X != lastVelocity.X)
{
                             velocity.X = lastVelocity.X * -1f;
                         }
                         if (velocity.Y != lastVelocity.Y)
{
                             velocity.Y = lastVelocity.Y * -1f;
                         }
                     }
                     else if (type == 155)
                     {
                         if (ai[1] > 10f)
{
                             NetworkText networkText = NetworkText.FromKey("Game.BallBounceResult", NetworkText.FromKey(Lang.GetProjectileName(type).Key), ai[1]);
                             if (Main.netMode == 0)
{
                                 Main.NewText(networkText.ToString(), byte.MaxValue, 240, 20);
                             }
                             else if (Main.netMode == 2)
{
                                 ChatHelper.BroadcastChatMessage(networkText, new Color(255, 240, 20));
                             }
                         }
                         ai[1] = 0f;
                         if (velocity.X != lastVelocity.X)
{
                             velocity.X = lastVelocity.X * -0.6f;
                         }
                         if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 2f)
{
                             velocity.Y = lastVelocity.Y * -0.6f;
                         }
                     }
                     else if (aiStyle == 33)
                     {
                         if (localAI[0] == 0f)
{
                             if (wet)
{
                                 position += lastVelocity / 2f;
                             }
                             else
{
                                 position += lastVelocity;
                             }
                             velocity *= 0f;
                             localAI[0] = 1f;
                         }
                     }
                     else if (type != 308 && type != 377 && type != 966)
                     {
                         if (type == 477)
{
                             if (velocity.Y != lastVelocity.Y || velocity.X != lastVelocity.X)
{
                                 penetrate--;
                                 if (penetrate <= 0)
{
                                     Kill();
                                 }
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = 0f - lastVelocity.X;
                                 }
                                 if (velocity.Y != lastVelocity.Y)
{
                                     velocity.Y = 0f - lastVelocity.Y;
                                 }
                             }
                             if (penetrate > 0 && owner == Main.myPlayer)
{
                                 int[] array = new int[10];
                                 int num30 = 0;
                                 int num31 = 700;
                                 int num32 = 20;
                                 for (int m = 0; m < 200; m++)
{
                                     if (!Main.npc[m].CanBeChasedBy(this))
{
                                         continue;
                                     }
                                     float num33 = (base.Center - Main.npc[m].Center).Length();
                                     if (num33 > (float)num32 && num33 < (float)num31 && Collision.CanHitLine(base.Center, 1, 1, Main.npc[m].Center, 1, 1))
{
                                         array[num30] = m;
                                         num30++;
                                         if (num30 >= 9)
{
                                             break;
                                         }
                                     }
                                 }
                                 if (num30 > 0)
{
                                     num30 = Main.rand.Next(num30);
                                     Vector2 vector22 = Main.npc[array[num30]].Center - base.Center;
                                     float num34 = velocity.Length();
                                     vector22.Normalize();
                                     velocity = vector22 * num34;
                                     netUpdate = true;
                                 }
                             }
                         }
                         else if (type == 94)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = 0f - lastVelocity.X;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 velocity.Y = 0f - lastVelocity.Y;
                             }
                         }
                         else if (type == 496)
{
                             if (velocity.X != lastVelocity.X)
{
                                 if (Math.Abs(velocity.X) < 1f)
{
                                     velocity.X = 0f - lastVelocity.X;
                                 }
                                 else
{
                                     Kill();
                                 }
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 if (Math.Abs(velocity.Y) < 1f)
{
                                     velocity.Y = 0f - lastVelocity.Y;
                                 }
                                 else
{
                                     Kill();
                                 }
                             }
                         }
                         else if (type == 311)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = 0f - lastVelocity.X;
                                 ai[1] += 1f;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 velocity.Y = 0f - lastVelocity.Y;
                                 ai[1] += 1f;
                             }
                             if (ai[1] > 4f)
{
                                 Kill();
                             }
                         }
                         else if (type == 312)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = 0f - lastVelocity.X;
                                 ai[1] += 1f;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 velocity.Y = 0f - lastVelocity.Y;
                                 ai[1] += 1f;
                             }
                         }
                         else if (type == 522 || type == 620)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = 0f - lastVelocity.X;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 velocity.Y = 0f - lastVelocity.Y;
                             }
                         }
                         else if (type == 524)
{
                             ai[0] += 100f;
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = 0f - lastVelocity.X;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 velocity.Y = 0f - lastVelocity.Y;
                             }
                         }
                         else if (aiStyle == 93)
{
                             if (velocity != lastVelocity)
{
                                 ai[1] = 0f;
                                 ai[0] = 1f;
                                 netUpdate = true;
                                 tileCollide = false;
                                 position += velocity;
                                 velocity = lastVelocity;
                                 velocity.Normalize();
                                 velocity *= 3f;
                             }
                         }
                         else if (type == 281)
{
                             bool flag11 = Math.Abs(velocity.X) + Math.Abs(velocity.Y) < 2f || ai[0] == -1f;
                             if (ai[0] == -2f || ai[0] == -3f)
{
                                 flag11 = false;
                             }
                             if (flag11)
{
                                 if (Main.myPlayer == owner)
{
                                     int num35 = ((velocity.X > 0f) ? 1 : 2);
                                     if (damage == 0)
{
                                         num35 += 2;
                                     }
                                     NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y - 4, 614, num35, owner);
                                     ai[0] = -3f;
                                     netUpdate = true;
                                 }
                             }
                             else
{
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = (0f - lastVelocity.X) * 0.5f;
                                 }
                                 if (velocity.Y != lastVelocity.Y)
{
                                     velocity.Y = (0f - lastVelocity.Y) * 0.5f;
                                 }
                             }
                         }
                         else if (type == 290 || type == 294)
{
                             if (velocity.X != lastVelocity.X)
{
                                 position.X += velocity.X;
                                 velocity.X = 0f - lastVelocity.X;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 position.Y += velocity.Y;
                                 velocity.Y = 0f - lastVelocity.Y;
                             }
                         }
                         else if ((type == 181 || type == 189 || type == 357 || type == 566) && penetrate > 0)
{
                             if (type == 357)
{
                                 damage = (int)((double)damage * 0.9);
                             }
                             penetrate--;
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = 0f - lastVelocity.X;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 velocity.Y = 0f - lastVelocity.Y;
                             }
                         }
                         else if (type == 307 && ai[1] < 5f)
{
                             ai[1] += 1f;
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = 0f - lastVelocity.X;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 velocity.Y = 0f - lastVelocity.Y;
                             }
                         }
                         else if (type == 99 || type == 1005 || type == 1014)
{
                             if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 5f)
{
                                 Collision.HitTiles(position, velocity, width, height);
                                 SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                 velocity.Y = (0f - lastVelocity.Y) * 0.2f;
                             }
                             if (velocity.X != lastVelocity.X)
{
                                 Kill();
                             }
                         }
                         else if (type == 1021)
{
                             if (velocity.Y != lastVelocity.Y)
{
                                 if (lastVelocity.Y > 4f)
{
                                     Collision.HitTiles(position, velocity, width, height);
                                     SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                     velocity.Y = (0f - lastVelocity.Y) * 0.9f;
                                 }
                                 else if (lastVelocity.Y > 0f)
{
                                     localAI[1] = 999f;
                                 }
                             }
                             if (velocity.X != lastVelocity.X)
{
                                 if (localAI[1] <= 3f)
{
                                     velocity.X = lastVelocity.X * -0.75f;
                                     localAI[1] += 1f;
                                 }
                                 else
{
                                     Kill();
                                 }
                             }
                         }
                         else if (type == 1013)
{
                             float num36 = Math.Abs(lastVelocity.X);
                             float num37 = Math.Abs(lastVelocity.Y);
                             float num38 = 0.95f;
                             float num39 = 0.95f;
                             if (num36 < 0.5f)
{
                                 num38 = 0.1f;
                             }
                             else if (num36 < 0.75f)
{
                                 num38 = 0.25f;
                             }
                             else if (num36 < 1f)
{
                                 num38 = 0.5f;
                             }
                             if (num37 < 0.5f)
{
                                 num39 = 0.1f;
                             }
                             else if (num37 < 0.75f)
{
                                 num39 = 0.25f;
                             }
                             else if (num37 < 1f)
{
                                 num39 = 0.5f;
                             }
                             bool flag12 = false;
                             if (velocity.Y != lastVelocity.Y)
{
                                 if (Math.Abs(lastVelocity.Y) > 5f)
{
                                     flag12 = true;
                                 }
                                 velocity.Y = (0f - lastVelocity.Y) * num39;
                             }
                             if (velocity.X != lastVelocity.X)
{
                                 if (Math.Abs(lastVelocity.X) > 5f)
{
                                     flag12 = true;
                                 }
                                 velocity.X = (0f - lastVelocity.X) * num38;
                             }
                             if (flag12)
{
                                 localAI[1] += 1f;
                                 Collision.HitTiles(position, velocity, width, height);
                                 SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                             }
                             if (velocity.Length() < 0.1f && localAI[0] > 50f)
{
                                 Kill();
                             }
                             if (localAI[1] > 20f)
{
                                 Kill();
                             }
                         }
                         else if (type == 727)
{
                             int num40 = 30;
                             float num41 = 2f;
                             float num42 = 2f;
                             if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 5f)
{
                                 Collision.HitTiles(position, velocity, width, height);
                                 SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                 velocity.Y = (0f - lastVelocity.Y) * 0.65f;
                                 if (owner == Main.myPlayer)
{
                                     int num43 = Main.rand.Next(3, 6);
                                     float num44 = Main.rand.NextFloat();
                                     for (float num45 = 0f; num45 < 1f; num45 += 1f / (float)num43)
{
                                         Vector2 vector23 = ((num44 + num45) * ((float)Math.PI * 2f)).ToRotationVector2() * num42;
                                         if (vector23.Y > 0f)
{
                                             vector23 *= -0.7f;
                                         }
                                         NewProjectile(GetProjectileSource_FromThis(), base.Center, vector23, 763, num40, num41, Main.myPlayer);
                                     }
                                 }
                             }
                             if (velocity.X != lastVelocity.X)
{
                                 Kill();
                                 if (owner == Main.myPlayer)
{
                                     int num46 = Main.rand.Next(3, 6);
                                     float num47 = Main.rand.NextFloat();
                                     for (float num48 = 0f; num48 < 1f; num48 += 1f / (float)num46)
{
                                         Vector2 vector24 = ((num47 + num48) * ((float)Math.PI * 2f)).ToRotationVector2() * num42;
                                         if (vector24.Y > 0f)
{
                                             vector24 *= -0.7f;
                                         }
                                         NewProjectile(GetProjectileSource_FromThis(), base.Center, vector24, 763, num40, num41, Main.myPlayer);
                                     }
                                 }
                             }
                         }
                         else if (type == 655)
{
                             if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 5f)
{
                                 Collision.HitTiles(position, velocity, width, height);
                                 SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                 velocity.Y = (0f - lastVelocity.Y) * 0.2f;
                             }
                             if (velocity.X != lastVelocity.X)
{
                                 Kill();
                             }
                         }
                         else if (type == 36)
{
                             if (penetrate > 1)
{
                                 Collision.HitTiles(position, velocity, width, height);
                                 SoundEngine.PlaySound(SoundID.Item10, position);
                                 penetrate--;
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = 0f - lastVelocity.X;
                                 }
                                 if (velocity.Y != lastVelocity.Y)
{
                                     velocity.Y = 0f - lastVelocity.Y;
                                 }
                             }
                             else
{
                                 Kill();
                             }
                         }
                         else if (aiStyle == 21)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = 0f - lastVelocity.X;
                             }
                             if (velocity.Y != lastVelocity.Y)
{
                                 velocity.Y = 0f - lastVelocity.Y;
                             }
                         }
                         else if (aiStyle == 17)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = lastVelocity.X * -0.75f;
                             }
                             if (velocity.Y != lastVelocity.Y && (double)lastVelocity.Y > 1.5)
{
                                 velocity.Y = lastVelocity.Y * -0.7f;
                             }
                         }
                         else if (aiStyle == 15)
{
                             AI_015_HandleMovementCollision(ref wetVelocity, ref lastVelocity);
                         }
                         else if (aiStyle == 9)
{
                             bool flag13 = owner == Main.myPlayer;
                             if (type == 79)
{
                                 bool flag14 = ai[0] >= 0f;
                                 flag13 = flag13 && !flag14;
                                 if (flag14)
{
                                     if (velocity.X != lastVelocity.X)
{
                                         velocity.X *= 0.1f;
                                     }
                                     if (velocity.Y != lastVelocity.Y)
{
                                         velocity.Y *= 0.1f;
                                     }
                                 }
                             }
                             if (flag13)
{
                                 Kill();
                             }
                         }
                         else if (aiStyle == 39)
{
                             Collision.HitTiles(position, velocity, width, height);
                             if (type == 33 || type == 106)
{
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = 0f - lastVelocity.X;
                                 }
                                 if (velocity.Y != lastVelocity.Y)
{
                                     velocity.Y = 0f - lastVelocity.Y;
                                 }
                             }
                             else
{
                                 ai[0] = 1f;
                                 if (aiStyle == 3)
{
                                     velocity.X = 0f - lastVelocity.X;
                                     velocity.Y = 0f - lastVelocity.Y;
                                 }
                             }
                             netUpdate = true;
                             SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                         }
                         else if (aiStyle == 3 || aiStyle == 13 || aiStyle == 69 || aiStyle == 109)
{
                             if (type == 106)
{
                                 Vector2 hitPoint = base.Center + velocity.SafeNormalize(Vector2.UnitX) * 8f * scale;
                                 Vector2 normal = new Vector2((velocity.X != lastVelocity.X) ? (-Math.Sign(lastVelocity.X)) : 0, (velocity.Y != lastVelocity.Y) ? (-Math.Sign(lastVelocity.Y)) : 0);
                                 LightDisc_Bounce(hitPoint, normal);
                             }
                             Collision.HitTiles(position, velocity, width, height);
                             if (type == 33 || type == 106 || type == 866)
{
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = 0f - lastVelocity.X;
                                 }
                                 if (velocity.Y != lastVelocity.Y)
{
                                     velocity.Y = 0f - lastVelocity.Y;
                                 }
                             }
                             else
{
                                 ai[0] = 1f;
                                 if ((aiStyle == 3 || aiStyle == 109) && type != 383)
{
                                     velocity.X = 0f - lastVelocity.X;
                                     velocity.Y = 0f - lastVelocity.Y;
                                 }
                             }
                             netUpdate = true;
                             SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                         }
                         else if (aiStyle == 8 && type != 96)
{
                             SoundEngine.PlaySound(SoundID.Item10, position);
                             ai[0] += 1f;
                             int num49 = 5;
                             switch (type)
{
                             case 15:
                                 num49 = 6;
                                 break;
                             case 253:
                                 num49 = 8;
                                 break;
                             }
                             if (ai[0] >= (float)num49)
{
                                 position += velocity;
                                 Kill();
                             }
                             else
{
                                 if (type == 15 && velocity.Y > 4f)
{
                                     if (velocity.Y != lastVelocity.Y)
{
                                         velocity.Y = (0f - lastVelocity.Y) * 0.8f;
                                     }
                                 }
                                 else if (velocity.Y != lastVelocity.Y)
{
                                     velocity.Y = 0f - lastVelocity.Y;
                                 }
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = 0f - lastVelocity.X;
                                 }
                             }
                         }
                         else if (aiStyle == 61)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = lastVelocity.X * -0.3f;
                             }
                             if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 1f)
{
                                 velocity.Y = lastVelocity.Y * -0.3f;
                             }
                         }
                         else if (aiStyle == 14)
{
                             if (type == 928)
{
                                 int num50 = 0;
                                 for (int num51 = 1000; num51 >= 0; num51--)
{
                                     if (num51 != whoAmI && Main.projectile[num51].active && Main.projectile[num51].owner == owner && Main.projectile[num51].type == type)
{
                                         num50++;
                                         if (num50 >= 2 && timeLeft > Main.projectile[num51].timeLeft && Main.projectile[num51].timeLeft > 30)
{
                                             Main.projectile[num51].timeLeft = 2;
                                         }
                                     }
                                 }
                             }
                             if (type == 261 && ((velocity.X != lastVelocity.X && (lastVelocity.X < -3f || lastVelocity.X > 3f)) || (velocity.Y != lastVelocity.Y && (lastVelocity.Y < -3f || lastVelocity.Y > 3f))))
{
                                 for (int n = 0; n < 10; n++)
{
                                     Collision.HitTiles(position, velocity, width, height);
                                 }
                                 SoundEngine.PlaySound(0, (int)base.Center.X, (int)base.Center.Y);
                                 MakeBoulderOfEarthExplosion();
                             }
                             if (type >= 326 && type <= 328 && velocity.X != lastVelocity.X)
{
                                 velocity.X = lastVelocity.X * -0.1f;
                             }
                             if (type >= 400 && type <= 402)
{
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = lastVelocity.X * -0.1f;
                                 }
                             }
                             else if (type == 870 && ai[1] == 0f)
{
                                 if (velocity.X != lastVelocity.X || velocity.Y != lastVelocity.Y)
{
                                     velocity = -lastVelocity;
                                     ai[1] = 1f;
                                 }
                             }
                             else if (type == 50)
{
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = lastVelocity.X * -0.2f;
                                 }
                                 if (velocity.Y != lastVelocity.Y && (double)lastVelocity.Y > 1.5)
{
                                     velocity.Y = lastVelocity.Y * -0.2f;
                                 }
                             }
                             else if (type == 185)
{
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = lastVelocity.X * -0.9f;
                                 }
                                 if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 1f)
{
                                     velocity.Y = lastVelocity.Y * -0.9f;
                                 }
                             }
                             else if (type == 277)
{
                                 if (velocity.X != lastVelocity.X)
{
                                     velocity.X = lastVelocity.X * -0.9f;
                                 }
                                 if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 3f)
{
                                     velocity.Y = lastVelocity.Y * -0.9f;
                                 }
                             }
                             else if (type != 480)
{
                                 if (type == 450)
{
                                     if (velocity.X != lastVelocity.X)
{
                                         velocity.X = lastVelocity.X * -0.1f;
                                     }
                                 }
                                 else
{
                                     if (velocity.X != lastVelocity.X)
{
                                         velocity.X = lastVelocity.X * -0.5f;
                                     }
                                     if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 1f)
{
                                         velocity.Y = lastVelocity.Y * -0.5f;
                                     }
                                 }
                             }
                         }
                         else if (aiStyle == 16)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = lastVelocity.X * -0.4f;
                                 if (type == 29)
{
                                     velocity.X *= 0.8f;
                                 }
                             }
                             if (velocity.Y != lastVelocity.Y && (double)lastVelocity.Y > 0.7 && type != 102)
{
                                 velocity.Y = lastVelocity.Y * -0.4f;
                                 if (type == 29)
{
                                     velocity.Y *= 0.8f;
                                 }
                             }
                             if (type == 134 || type == 137 || type == 140 || type == 143 || type == 303 || (type >= 338 && type <= 341) || type == 776 || type == 780 || type == 793 || type == 796 || type == 799 || type == 784 || type == 787 || type == 790 || type == 803 || type == 804 || type == 808 || type == 809 || type == 810 || type == 805 || type == 806 || type == 807 || type == 930)
{
                                 velocity *= 0f;
                                 alpha = 255;
                                 timeLeft = 3;
                             }
                         }
                         else if (aiStyle == 68)
{
                             velocity *= 0f;
                             alpha = 255;
                             timeLeft = 3;
                             netUpdate = true;
                         }
                         else if (type == 870)
{
                             if (velocity.X != lastVelocity.X)
{
                                 velocity.X = lastVelocity.X * -0.2f;
                             }
                             if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 0f)
{
                                 velocity.Y = lastVelocity.Y * -0.2f;
                             }
                         }
                         else
{
                             position += velocity;
                             Kill();
                         }
                     }
                 }
             }
         }
         UpdatePosition(wetVelocity);
         if (!flag2 && !flag4 && owner == Main.myPlayer && (tileCollide || flag5) && position != oldPosition)
         {
             Vector2 vector25 = position;
             Vector2 vector26 = oldPosition;
             int num52 = ((overrideWidth != -1) ? overrideWidth : width);
             int num53 = ((overrideHeight != -1) ? overrideHeight : height);
             if (overrideHeight != -1 || overrideWidth != -1)
             {
                 vector25 = new Vector2(position.X + (float)(width / 2) - (float)(num52 / 2), position.Y + (float)(height / 2) - (float)(num53 / 2));
                 vector26 = new Vector2(oldPosition.X + (float)(width / 2) - (float)(num52 / 2), oldPosition.Y + (float)(height / 2) - (float)(num53 / 2));
             }
             Collision.SwitchTiles(vector25, num52, num53, vector26, 4);
         }
     }
References Entity.active, ai, AI_015_HandleMovementCollision(), aiStyle, alpha, Collision.AnyCollisionWithSpecificTiles(), Entity.Bottom, ChatHelper.BroadcastChatMessage(), NPC.CanBeChasedBy(), WorldGen.CanCutTile(), CanCutTiles(), Collision.CanHitLine(), Entity.Center, Color, Dust.color, TileID.Sets.CrackedBricks, damage, Damage(), decidesManualFallThrough, Entity.DirectionTo(), Entity.Distance(), Main.dust, TileID.Sets.Falling, ProjectileID.Sets.FallingBlockDoesNotFallThroughPlatforms, FindTargetWithLineOfSight(), ProjectileID.Sets.ForcePlateDetection, friendly, NetworkText.FromKey(), Utils.GetLerpValue(), Lang.GetProjectileName(), GetProjectileSource_FromThis(), Player.GetTileCutIgnorance(), Entity.height, Collision.HitTiles(), Entity.honeyWet, hostile, Main.hslToRgb(), SoundID.Item10, SoundID.Item114, SoundID.Item115, LocalizedText.Key, Kill(), WorldGen.KillTile(), LightDisc_Bounce(), localAI, MakeBoulderOfEarthExplosion(), Main.maxTilesX, Main.maxTilesY, Main.myPlayer, Main.netMode, netUpdate, Dust.NewDust(), NewProjectile(), Main.NewText(), UnifiedRandom.Next(), Dust.noGravity, Main.npc, numUpdates, Entity.oldPosition, owner, penetrate, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.projectile, Main.projPet, Main.rand, NPC.ReleaseNPC(), rotation, Dust.scale, scale, NetMessage.SendData(), Entity.shimmerWet, shouldFallThrough, Collision.SlopeCollision(), Collision.SwitchTiles(), Main.tile, tileCollide, Collision.TileCollision(), timeLeft, NetworkText.ToString(), trap, PortalHelper.TryPlacingPortal(), type, Tile.type, UpdatePosition(), Dust.velocity, Entity.velocity, Entity.wet, Entity.whoAmI, and Entity.width.
Referenced by Update().