Terraria: Projectile.AI_099_2
AI_099_2()
void Projectile.AI_099_2 () inline private
     {
         bool flag = false;
         for (int i = 0; i < whoAmI; i++)
         {
             if (Main.projectile[i].active && Main.projectile[i].owner == owner && Main.projectile[i].type == type)
             {
                 flag = true;
             }
         }
         if (owner == Main.myPlayer)
         {
             localAI[0] += 1f;
             if (flag)
             {
                 localAI[0] += (float)Main.rand.Next(10, 31) * 0.1f;
             }
             float num = localAI[0] / 60f;
             num /= (1f + Main.player[owner].meleeSpeed) / 2f;
             float num2 = ProjectileID.Sets.YoyosLifeTimeMultiplier[type];
             if (num2 != -1f && num > num2)
             {
                 ai[0] = -1f;
             }
         }
         if (type == 603 && owner == Main.myPlayer)
         {
             localAI[1] += 1f;
             if (localAI[1] >= 6f)
             {
                 float num3 = 400f;
                 Vector2 vector = velocity;
                 Vector2 vector2 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                 vector2.Normalize();
                 vector2 *= (float)Main.rand.Next(10, 41) * 0.1f;
                 if (Main.rand.Next(3) == 0)
                 {
                     vector2 *= 2f;
                 }
                 vector *= 0.25f;
                 vector += vector2;
                 for (int j = 0; j < 200; j++)
                 {
                     if (Main.npc[j].CanBeChasedBy(this))
                     {
                         float num4 = Main.npc[j].position.X + (float)(Main.npc[j].width / 2);
                         float num5 = Main.npc[j].position.Y + (float)(Main.npc[j].height / 2);
                         float num6 = Math.Abs(position.X + (float)(width / 2) - num4) + Math.Abs(position.Y + (float)(height / 2) - num5);
                         if (num6 < num3 && Collision.CanHit(position, width, height, Main.npc[j].position, Main.npc[j].width, Main.npc[j].height))
{
                             num3 = num6;
                             vector.X = num4;
                             vector.Y = num5;
                             vector -= base.Center;
                             vector.Normalize();
                             vector *= 8f;
                         }
                     }
                 }
                 vector *= 0.8f;
                 NewProjectile(GetProjectileSource_FromThis(), base.Center.X - vector.X, base.Center.Y - vector.Y, vector.X, vector.Y, 604, damage, knockBack, owner);
                 localAI[1] = 0f;
             }
         }
         bool flag2 = false;
         if (type >= 556 && type <= 561)
         {
             flag2 = true;
         }
         if (Main.player[owner].dead)
         {
             Kill();
             return;
         }
         if (!flag2 && !flag)
         {
             Main.player[owner].heldProj = whoAmI;
             Main.player[owner].SetDummyItemTime(2);
             if (position.X + (float)(width / 2) > Main.player[owner].position.X + (float)(Main.player[owner].width / 2))
             {
                 Main.player[owner].ChangeDir(1);
                 direction = 1;
             }
             else
             {
                 Main.player[owner].ChangeDir(-1);
                 direction = -1;
             }
         }
         if (velocity.HasNaNs())
         {
             Kill();
         }
         timeLeft = 6;
         float num7 = 10f;
         float num8 = 10f;
         float num9 = 3f;
         float num10 = 200f;
         num10 = ProjectileID.Sets.YoyosMaximumRange[type];
         num8 = ProjectileID.Sets.YoyosTopSpeed[type];
         if (type == 545)
         {
             if (Main.rand.Next(6) == 0)
             {
                 int num11 = Dust.NewDust(position, width, height, 6);
                 Main.dust[num11].noGravity = true;
             }
         }
         else if (type == 553 && Main.rand.Next(2) == 0)
         {
             int num12 = Dust.NewDust(position, width, height, 6);
             Main.dust[num12].noGravity = true;
             Main.dust[num12].scale = 1.6f;
         }
         if (Main.player[owner].yoyoString)
         {
             num10 = num10 * 1.25f + 30f;
         }
         num10 /= (1f + Main.player[owner].meleeSpeed * 3f) / 4f;
         num8 /= (1f + Main.player[owner].meleeSpeed * 3f) / 4f;
         num7 = 14f - num8 / 2f;
         if (num7 < 1f)
         {
             num7 = 1f;
         }
         num9 = 5f + num8 / 2f;
         if (flag)
         {
             num9 += 20f;
         }
         if (ai[0] >= 0f)
         {
             if (velocity.Length() > num8)
             {
                 velocity *= 0.98f;
             }
             bool flag3 = false;
             bool flag4 = false;
             Vector2 vector3 = Main.player[owner].Center - base.Center;
             if (vector3.Length() > num10)
             {
                 flag3 = true;
                 if ((double)vector3.Length() > (double)num10 * 1.3)
                 {
                     flag4 = true;
                 }
             }
             if (owner == Main.myPlayer)
             {
                 if (!Main.player[owner].channel || Main.player[owner].stoned || Main.player[owner].frozen)
                 {
                     ai[0] = -1f;
                     ai[1] = 0f;
                     netUpdate = true;
                 }
                 else
                 {
                     Vector2 vector4 = Main.ReverseGravitySupport(Main.MouseScreen) + Main.screenPosition;
                     float x = vector4.X;
                     float y = vector4.Y;
                     Vector2 vector5 = new Vector2(x, y) - Main.player[owner].Center;
                     if (vector5.Length() > num10)
                     {
                         vector5.Normalize();
                         vector5 *= num10;
                         vector5 = Main.player[owner].Center + vector5;
                         x = vector5.X;
                         y = vector5.Y;
                     }
                     if (ai[0] != x || ai[1] != y)
                     {
                         Vector2 vector6 = new Vector2(x, y) - Main.player[owner].Center;
                         if (vector6.Length() > num10 - 1f)
{
                             vector6.Normalize();
                             vector6 *= num10 - 1f;
                             Vector2 vector7 = Main.player[owner].Center + vector6;
                             x = vector7.X;
                             y = vector7.Y;
                         }
                         ai[0] = x;
                         ai[1] = y;
                         netUpdate = true;
                     }
                 }
             }
             if (flag4 && owner == Main.myPlayer)
             {
                 ai[0] = -1f;
                 netUpdate = true;
             }
             if (ai[0] >= 0f)
             {
                 if (flag3)
                 {
                     num7 /= 2f;
                     num8 *= 2f;
                     if (base.Center.X > Main.player[owner].Center.X && velocity.X > 0f)
                     {
                         velocity.X *= 0.5f;
                     }
                     if (base.Center.Y > Main.player[owner].Center.Y && velocity.Y > 0f)
                     {
                         velocity.Y *= 0.5f;
                     }
                     if (base.Center.X < Main.player[owner].Center.X && velocity.X < 0f)
                     {
                         velocity.X *= 0.5f;
                     }
                     if (base.Center.Y < Main.player[owner].Center.Y && velocity.Y < 0f)
                     {
                         velocity.Y *= 0.5f;
                     }
                 }
                 Vector2 vector8 = new Vector2(ai[0], ai[1]) - base.Center;
                 if (flag3)
                 {
                     num7 = 1f;
                 }
                 velocity.Length();
                 float num13 = vector8.Length();
                 if (num13 > num9)
                 {
                     vector8.Normalize();
                     float num14 = Math.Min(num13 / 2f, num8);
                     if (flag3)
                     {
                         num14 = Math.Min(num14, num8 / 2f);
                     }
                     vector8 *= num14;
                     velocity = (velocity * (num7 - 1f) + vector8) / num7;
                 }
                 else if (flag)
                 {
                     if ((double)velocity.Length() < (double)num8 * 0.6)
                     {
                         vector8 = velocity;
                         vector8.Normalize();
                         vector8 *= num8 * 0.6f;
                         velocity = (velocity * (num7 - 1f) + vector8) / num7;
                     }
                 }
                 else
                 {
                     velocity *= 0.8f;
                 }
                 if (flag && !flag3 && (double)velocity.Length() < (double)num8 * 0.6)
                 {
                     velocity.Normalize();
                     velocity *= num8 * 0.6f;
                 }
             }
         }
         else
         {
             num7 = (int)((double)num7 * 0.8);
             num8 *= 1.5f;
             tileCollide = false;
             Vector2 vector9 = Main.player[owner].Center - base.Center;
             float num15 = vector9.Length();
             if (num15 < num8 + 10f || num15 == 0f || num15 > 2000f)
             {
                 Kill();
             }
             else
             {
                 vector9.Normalize();
                 vector9 *= num8;
                 velocity = (velocity * (num7 - 1f) + vector9) / num7;
             }
         }
         rotation += 0.45f;
     }
References Entity.active, NPC.CanBeChasedBy(), Collision.CanHit(), Entity.Center, Player.ChangeDir(), Player.channel, Player.dead, Main.dust, Player.frozen, Entity.height, Player.heldProj, Player.meleeSpeed, Main.MouseScreen, Main.myPlayer, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Main.npc, owner, Main.player, Entity.position, Main.projectile, Main.rand, Main.ReverseGravitySupport(), Dust.scale, Main.screenPosition, Player.SetDummyItemTime(), Player.stoned, type, Entity.width, ProjectileID.Sets.YoyosLifeTimeMultiplier, ProjectileID.Sets.YoyosMaximumRange, ProjectileID.Sets.YoyosTopSpeed, and Player.yoyoString.