Terraria: Projectile.AI_061_FishingBobber
AI_061_FishingBobber()
void Projectile.AI_061_FishingBobber () inline private
     {
         Player player = Main.player[owner];
         bool flag = type >= 986 && type <= 993;
         timeLeft = 60;
         bool flag2 = false;
         if (player.inventory[player.selectedItem].fishingPole == 0 || player.CCed || player.noItems)
         {
             flag2 = true;
         }
         else if (player.inventory[player.selectedItem].shoot != type && !flag)
         {
             flag2 = true;
         }
         else if (player.pulley)
         {
             flag2 = true;
         }
         else if (player.dead)
         {
             flag2 = true;
         }
         if (flag2)
         {
             Kill();
             return;
         }
         if (ai[1] > 0f && localAI[1] != 0f)
         {
             localAI[1] = 0f;
             if (!lavaWet && !honeyWet)
             {
                 AI_061_FishingBobber_DoASplash();
             }
         }
         if (ai[0] >= 1f)
         {
             if (ai[0] == 2f)
             {
                 ai[0] += 1f;
                 SoundEngine.PlaySound(SoundID.Item17, position);
                 if (!lavaWet && !honeyWet)
                 {
                     AI_061_FishingBobber_DoASplash();
                 }
             }
             if (localAI[0] < 100f)
             {
                 localAI[0] += 1f;
             }
             if (frameCounter == 0)
             {
                 frameCounter = 1;
                 ReduceRemainingChumsInPool();
             }
             tileCollide = false;
             int num = 10;
             Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num2 = player.position.X + (float)(player.width / 2) - vector.X;
             float num3 = player.position.Y + (float)(player.height / 2) - vector.Y;
             float num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
             if (num4 > 3000f)
             {
                 Kill();
             }
             num4 = 15.9f / num4;
             num2 *= num4;
             num3 *= num4;
             velocity.X = (velocity.X * (float)(num - 1) + num2) / (float)num;
             velocity.Y = (velocity.Y * (float)(num - 1) + num3) / (float)num;
             rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
             if (Main.myPlayer == owner && base.Hitbox.Intersects(player.Hitbox))
             {
                 Kill();
             }
             return;
         }
         bool flag3 = false;
         Vector2 vector2 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
         float num5 = player.position.X + (float)(player.width / 2) - vector2.X;
         float num6 = player.position.Y + (float)(player.height / 2) - vector2.Y;
         rotation = (float)Math.Atan2(num6, num5) + 1.57f;
         if ((float)Math.Sqrt(num5 * num5 + num6 * num6) > 900f)
         {
             ai[0] = 1f;
         }
         if (wet)
         {
             if (shimmerWet)
             {
                 if (Main.myPlayer == owner)
                 {
                     Main.player[owner].AddBuff(353, 60);
                 }
                 if (localAI[2] == 0f)
                 {
                     localAI[2] = 1f;
                     SoundEngine.PlaySound(19, (int)Main.player[owner].position.X, (int)Main.player[owner].position.Y, 2);
                 }
             }
             rotation = 0f;
             velocity.X *= 0.9f;
             int num7 = (int)(base.Center.X + (float)((width / 2 + 8) * direction)) / 16;
             int num8 = (int)(base.Center.Y / 16f);
             _ = position.Y / 16f;
             int num9 = (int)((position.Y + (float)height) / 16f);
             if (Main.tile[num7, num8] == null)
             {
                 Main.tile[num7, num8] = new Tile();
             }
             if (Main.tile[num7, num9] == null)
             {
                 Main.tile[num7, num9] = new Tile();
             }
             if (velocity.Y > 0f)
             {
                 velocity.Y *= 0.5f;
             }
             num7 = (int)(base.Center.X / 16f);
             num8 = (int)(base.Center.Y / 16f);
             float num10 = AI_061_FishingBobber_GetWaterLine(num7, num8);
             if (base.Center.Y > num10)
             {
                 velocity.Y -= 0.1f;
                 if (velocity.Y < -8f)
                 {
                     velocity.Y = -8f;
                 }
                 if (base.Center.Y + velocity.Y < num10)
                 {
                     velocity.Y = num10 - base.Center.Y;
                 }
             }
             else
             {
                 velocity.Y = num10 - base.Center.Y;
             }
             if ((double)velocity.Y >= -0.01 && (double)velocity.Y <= 0.01)
             {
                 flag3 = true;
             }
         }
         else
         {
             if (velocity.Y == 0f)
             {
                 velocity.X *= 0.95f;
             }
             velocity.X *= 0.98f;
             velocity.Y += 0.2f;
             if (velocity.Y > 15.9f)
             {
                 velocity.Y = 15.9f;
             }
         }
         if (Main.myPlayer == owner && player.GetFishingConditions().BaitItemType == 2673)
         {
             player.displayedFishingInfo = Language.GetTextValue("GameUI.FishingWarning");
         }
         if (ai[1] != 0f)
         {
             flag3 = true;
         }
         if (!flag3)
         {
             return;
         }
         if (ai[1] == 0f && Main.myPlayer == owner)
         {
             int finalFishingLevel = player.GetFishingConditions().FinalFishingLevel;
             if (Main.rand.Next(300) < finalFishingLevel)
             {
                 localAI[1] += Main.rand.Next(1, 3);
             }
             localAI[1] += finalFishingLevel / 30;
             localAI[1] += Main.rand.Next(1, 3);
             if (Main.rand.Next(60) == 0)
             {
                 localAI[1] += 60f;
             }
             if (localAI[1] > 660f)
             {
                 localAI[1] = 0f;
                 FishingCheck();
             }
         }
         else if (ai[1] < 0f)
         {
             if (velocity.Y == 0f || (honeyWet && Math.Abs(velocity.Y) <= 0.01f))
             {
                 velocity.Y = (float)Main.rand.Next(100, 500) * 0.015f;
                 velocity.X = (float)Main.rand.Next(-100, 101) * 0.015f;
                 wet = false;
                 lavaWet = false;
                 honeyWet = false;
             }
             ai[1] += Main.rand.Next(1, 5);
             if (ai[1] >= 0f)
             {
                 ai[1] = 0f;
                 localAI[1] = 0f;
                 netUpdate = true;
             }
         }
     }
References Player.AddBuff(), PlayerFishingConditions.BaitItemType, Player.CCed, Player.dead, Player.displayedFishingInfo, PlayerFishingConditions.FinalFishingLevel, Item.fishingPole, Player.GetFishingConditions(), Language.GetTextValue(), Entity.height, Entity.Hitbox, Player.inventory, SoundID.Item17, Main.myPlayer, UnifiedRandom.Next(), Player.noItems, Main.player, SoundEngine.PlaySound(), Entity.position, Player.pulley, Main.rand, Player.selectedItem, Item.shoot, Main.tile, and Entity.width.