Terraria: Projectile.AI_136_BetsyBreath
AI_136_BetsyBreath()
void Projectile.AI_136_BetsyBreath () inline private
     {
         if (ai[1] < 0f || ai[1] > 200f)
         {
             Kill();
             return;
         }
         NPC nPC = Main.npc[(int)ai[1]];
         float num = -8f;
         Vector2 center = nPC.Center + new Vector2((110f + num) * (float)nPC.spriteDirection, 30f).RotatedBy(nPC.rotation);
         base.Center = center;
         rotation = nPC.DirectionTo(base.Center).ToRotation();
         DelegateMethods.v3_1 = new Vector3(1.2f, 1f, 0.3f);
         float num2 = ai[0] / 40f;
         if (num2 > 1f)
         {
             num2 = 1f;
         }
         float num3 = (ai[0] - 38f) / 40f;
         if (num3 < 0f)
         {
             num3 = 0f;
         }
         Utils.PlotTileLine(base.Center + rotation.ToRotationVector2() * 400f * num3, base.Center + rotation.ToRotationVector2() * 400f * num2, 16f, DelegateMethods.CastLight);
         Utils.PlotTileLine(base.Center + rotation.ToRotationVector2().RotatedBy(0.19634954631328583) * 400f * num3, base.Center + rotation.ToRotationVector2().RotatedBy(0.19634954631328583) * 400f * num2, 16f, DelegateMethods.CastLight);
         Utils.PlotTileLine(base.Center + rotation.ToRotationVector2().RotatedBy(-0.19634954631328583) * 400f * num3, base.Center + rotation.ToRotationVector2().RotatedBy(-0.19634954631328583) * 400f * num2, 16f, DelegateMethods.CastLight);
         if (num3 == 0f && num2 > 0.1f)
         {
             for (int i = 0; i < 3; i++)
             {
                 Dust dust = Dust.NewDustDirect(position, width, height, 6);
                 dust.fadeIn = 1.5f;
                 dust.velocity = rotation.ToRotationVector2().RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI / 12f)) * (0.5f + Main.rand.NextFloat() * 2.5f) * 15f;
                 dust.velocity += nPC.velocity * 2f;
                 dust.noLight = true;
                 dust.noGravity = true;
                 dust.alpha = 200;
             }
         }
         if (Main.rand.Next(5) == 0 && ai[0] >= 15f)
         {
             Gore gore = Gore.NewGoreDirect(base.Center + rotation.ToRotationVector2() * 300f - Utils.RandomVector2(Main.rand, -20f, 20f), Vector2.Zero, 61 + Main.rand.Next(3), 0.5f);
             gore.velocity *= 0.3f;
             gore.velocity += rotation.ToRotationVector2() * 4f;
         }
         for (int j = 0; j < 1; j++)
         {
             Dust dust2 = Dust.NewDustDirect(position, width, height, 31);
             dust2.fadeIn = 1.5f;
             dust2.scale = 0.4f;
             dust2.velocity = rotation.ToRotationVector2().RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI / 12f)) * (0.5f + Main.rand.NextFloat() * 2.5f) * 15f;
             dust2.velocity += nPC.velocity * 2f;
             dust2.velocity *= 0.3f;
             dust2.noLight = true;
             dust2.noGravity = true;
             float num4 = Main.rand.NextFloat();
             dust2.position = Vector2.Lerp(base.Center + rotation.ToRotationVector2() * 400f * num3, base.Center + rotation.ToRotationVector2() * 400f * num2, num4);
             dust2.position += rotation.ToRotationVector2().RotatedBy(1.5707963705062866) * (20f + 100f * (num4 - 0.5f));
         }
         frameCounter++;
         ai[0] += 1f;
         if (ai[0] >= 78f)
         {
             Kill();
         }
     }
References Dust.alpha, DelegateMethods.CastLight(), Entity.Center, Entity.DirectionTo(), Dust.fadeIn, Dust.NewDustDirect(), Gore.NewGoreDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.npc, Utils.PlotTileLine(), Dust.position, Main.rand, Utils.RandomVector2(), NPC.rotation, Dust.scale, NPC.spriteDirection, DelegateMethods.v3_1, Dust.velocity, Entity.velocity, and Gore.velocity.