Terraria: Projectile.AI_009_MagicMissiles_Old
AI_009_MagicMissiles_Old()
void Projectile.AI_009_MagicMissiles_Old () inline private
     {
         if (Main.myPlayer == owner && ai[0] <= 0f)
         {
             if (Main.player[owner].channel && Main.player[owner].HeldItem.shoot == type)
             {
                 float num = 12f;
                 if (type == 16)
                 {
                     num = 15f;
                 }
                 if (type == 491)
                 {
                     num = 20f;
                 }
                 Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 Vector2 pointPoisition = Main.MouseWorld;
                 Main.player[owner].LimitPointToPlayerReachableArea(ref pointPoisition);
                 float num2 = pointPoisition.X - vector.X;
                 float num3 = pointPoisition.Y - vector.Y;
                 float num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
                 if (ai[0] < 0f)
                 {
                     ai[0] += 1f;
                 }
                 if (type == 491 && num4 < 100f)
                 {
                     if (velocity.Length() < num)
                     {
                         velocity *= 1.1f;
                         if (velocity.Length() > num)
{
                             velocity.Normalize();
                             velocity *= num;
                         }
                     }
                     if (ai[0] == 0f)
                     {
                         ai[0] = -10f;
                     }
                 }
                 else if (num4 > num)
                 {
                     num4 = num / num4;
                     num2 *= num4;
                     num3 *= num4;
                     int num5 = (int)(num2 * 1000f);
                     int num6 = (int)(velocity.X * 1000f);
                     int num7 = (int)(num3 * 1000f);
                     int num8 = (int)(velocity.Y * 1000f);
                     if (num5 != num6 || num7 != num8)
                     {
                         netUpdate = true;
                     }
                     if (type == 491)
                     {
                         Vector2 vector2 = new Vector2(num2, num3);
                         velocity = (velocity * 4f + vector2) / 5f;
                     }
                     else
                     {
                         velocity.X = num2;
                         velocity.Y = num3;
                     }
                 }
                 else
                 {
                     int num9 = (int)(num2 * 1000f);
                     int num10 = (int)(velocity.X * 1000f);
                     int num11 = (int)(num3 * 1000f);
                     int num12 = (int)(velocity.Y * 1000f);
                     if (num9 != num10 || num11 != num12)
                     {
                         netUpdate = true;
                     }
                     velocity.X = num2;
                     velocity.Y = num3;
                 }
             }
             else if (ai[0] <= 0f)
             {
                 netUpdate = true;
                 if (type != 491)
                 {
                     Vector2 vector3 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                     float num13 = (float)Main.mouseX + Main.screenPosition.X - vector3.X;
                     float num14 = (float)Main.mouseY + Main.screenPosition.Y - vector3.Y;
                     if (Main.player[owner].gravDir == -1f)
                     {
                         num14 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector3.Y;
                     }
                     float num15 = (float)Math.Sqrt(num13 * num13 + num14 * num14);
                     if (num15 == 0f || ai[0] < 0f)
                     {
                         vector3 = new Vector2(Main.player[owner].position.X + (float)(Main.player[owner].width / 2), Main.player[owner].position.Y + (float)(Main.player[owner].height / 2));
                         num13 = position.X + (float)width * 0.5f - vector3.X;
                         num14 = position.Y + (float)height * 0.5f - vector3.Y;
                         num15 = (float)Math.Sqrt(num13 * num13 + num14 * num14);
                     }
                     num15 = 12f / num15;
                     num13 *= num15;
                     num14 *= num15;
                     velocity.X = num13;
                     velocity.Y = num14;
                     if (velocity.X == 0f && velocity.Y == 0f)
                     {
                         Kill();
                     }
                 }
                 ai[0] = 1f;
             }
         }
         bool flag = false;
         if (type == 491)
         {
             localAI[0] += 1f;
             if (ai[0] > 0f && localAI[0] > 15f)
             {
                 tileCollide = false;
                 Vector2 vector4 = Main.player[owner].Center - base.Center;
                 if (vector4.Length() < 20f)
                 {
                     Kill();
                 }
                 vector4.Normalize();
                 vector4 *= 25f;
                 velocity = (velocity * 5f + vector4) / 6f;
             }
             flag = true;
             if (ai[0] < 0f || (velocity.X == 0f && velocity.Y == 0f))
             {
                 rotation += 0.3f;
             }
             else if (ai[0] > 0f)
             {
                 rotation += 0.3f * (float)direction;
             }
             else
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
             }
             if (Vector2.Distance(base.Center, Main.player[owner].Center) > 2000f)
             {
                 Kill();
             }
             if (Main.rand.Next(2) == 0)
             {
                 int num16 = Main.rand.Next(3);
                 int num17 = Dust.NewDust(position, width, height, num16 switch
                 {
                     0 => 15,
                     1 => 57,
                     _ => 58,
                 }, velocity.X * 0.25f, velocity.Y * 0.25f, 255, default(Color), 0.7f);
                 Main.dust[num17].velocity *= 0.25f;
                 Main.dust[num17].position = (Main.dust[num17].position + position) / 2f;
             }
         }
         if (type == 79)
         {
             if (soundDelay == 0 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 2f)
             {
                 soundDelay = 10;
                 SoundEngine.PlaySound(SoundID.Item9, position);
             }
             for (int i = 0; i < 1; i++)
             {
                 int num18 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 66, 0f, 0f, 100, new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB), 2.5f);
                 Main.dust[num18].velocity *= 0.1f;
                 Main.dust[num18].velocity += velocity * 0.2f;
                 Main.dust[num18].position.X = position.X + (float)(width / 2) + 4f + (float)Main.rand.Next(-2, 3);
                 Main.dust[num18].position.Y = position.Y + (float)(height / 2) + (float)Main.rand.Next(-2, 3);
                 Main.dust[num18].noGravity = true;
             }
         }
         if (type == 16)
         {
             if (soundDelay == 0 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 2f)
             {
                 soundDelay = 10;
                 SoundEngine.PlaySound(SoundID.Item9, position);
             }
             if (Main.rand.Next(9) == 0)
             {
                 int num19 = Dust.NewDust(position, width, height, 15, 0f, 0f, 100, default(Color), 2f);
                 Main.dust[num19].velocity *= 0.3f;
                 Main.dust[num19].position.X = position.X + (float)(width / 2) + 4f + (float)Main.rand.Next(-4, 5);
                 Main.dust[num19].position.Y = position.Y + (float)(height / 2) + (float)Main.rand.Next(-4, 5);
                 Main.dust[num19].noGravity = true;
                 Main.dust[num19].velocity += Main.rand.NextVector2Circular(2f, 2f);
             }
             flag = true;
             if (velocity != Vector2.Zero)
             {
                 rotation = velocity.ToRotation();
             }
         }
         if (type == 34)
         {
             if (Main.rand.Next(12) == 0)
             {
                 Dust dust = Dust.NewDustDirect(base.Center, 0, 0, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 3.5f);
                 dust.noGravity = true;
                 dust.velocity *= 1.4f;
                 dust.velocity += Main.rand.NextVector2Circular(1f, 1f);
                 dust.velocity += velocity * 0.15f;
             }
             if (Main.rand.Next(24) == 0)
             {
                 Dust dust2 = Dust.NewDustDirect(base.Center, 0, 0, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 1.5f);
                 dust2.velocity += Main.rand.NextVector2Circular(1f, 1f);
                 dust2.velocity += velocity * 0.15f;
             }
             flag = true;
             if (velocity != Vector2.Zero)
             {
                 rotation = velocity.ToRotation();
             }
         }
         if (!flag && velocity != Vector2.Zero)
         {
             rotation = velocity.ToRotation() - (float)Math.PI + (float)Math.PI / 4f;
         }
         if (velocity.Y > 16f)
         {
             velocity.Y = 16f;
         }
     }
References Entity.Center, Player.channel, Color, Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.dust, Player.gravDir, Entity.height, Player.HeldItem, SoundID.Item9, Player.LimitPointToPlayerReachableArea(), Main.MouseWorld, Main.mouseX, Main.mouseY, Main.myPlayer, Dust.NewDust(), Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.rand, Main.screenHeight, Main.screenPosition, Item.shoot, Dust.velocity, and Entity.width.