Terraria: Framing.GetTileSafely
GetTileSafely() [4/4]
static Tile Framing.GetTileSafely (Vector2 position) inline static
Referenced by NPC.AI(), Projectile.AI_001(), NPC.AI_003_Fighters(), Projectile.AI_007_GrapplingHooks(), NPC.AI_007_TownEntities(), NPC.AI_007_TownEntities_GetWalkPrediction(), Projectile.AI_016(), Projectile.AI_026(), Projectile.AI_067_FreakingPirates(), NPC.AI_107_ImprovedWalkers(), NPC.AI_110_Betsy(), NPC.AI_112_FairyCritter(), Projectile.AI_135_OgreStomp(), Projectile.AI_149_GolfBall(), MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack(), TileObject.CanPlace(), WorldGen.CanPlaceSink(), WorldGen.CanUnderwaterPlantGrowHere(), WorldGen.Check2x2(), WorldGen.Check2xX(), CultistRitual.CheckFloor(), Player.CheckForGoodTeleportationSpot(), WorldGen.CheckGnome(), WorldGen.CheckLilyPad(), Wiring.CheckLogicGate(), WorldGen.CheckOasisPlant(), WorldGen.CheckStinkbugBlocker(), WorldGen.CheckSuper(), WorldGen.CheckTallGate(), WorldGen.CheckTileAnchors(), WorldGen.CheckTileFrames(), WorldGen.CheckUnderwaterPlant(), MinecartDiggerHelper.CorrectTrackConnections(), Projectile.CreateGroundExplosion(), Projectile.CreateImpactExplosion(), Player.DamageTileWithShovel(), TEDisplayDoll.Draw(), TEHatRack.Draw(), HitTile.DrawFreshAnimations(), Main.DrawInfoAccs(), TileObject.DrawPreview(), Mount.EmitGolfCartWheelDust(), NPC.FindFrame(), TEDisplayDoll.Framing_CheckTile(), TEHatRack.Framing_CheckTile(), TETeleportationPylon.Framing_CheckTile(), TEWeaponsRack.Framing_CheckTile(), PlayerSittingHelper.GetSittingTargetInfo(), PlayerSleepingHelper.GetSleepingTargetInfo(), TileDrawing.GetTileDrawData(), GetTileSafely(), WorldGen.GetTopLeftAndStyles(), WorldGen.GetTreeBottom(), WorldGen.GetVineTop(), Collision.GetWaterLineIterate(), TeleportPylonsSystem.HandleTeleportRequest(), WorldGen.IsTileALeafyTreeTop(), Projectile.Kill(), WorldGen.KillTile(), Chest.Lock(), Player.MowTheLawn(), Chest.NearOtherChests(), NPC.NPCCanStickToWalls(), TileObject.Place(), WorldGen.Place2x2(), Player.PlaceThing_LockChest(), WorldGen.PlaceUnderwaterPlant(), Player.QuickGrapple(), Player.QuickMinecart(), Player.QuickMinecartSnap(), TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition(), WorldGen.ReplaceTile(), SelfFrame8Way(), WorldGen.ShiftTallGate(), WorldGen.ShiftTrapdoor(), DD2Event.SummonCrystalDirect(), Player.TileInteractionsUse(), WorldGen.ToggleGemLock(), MinecartDiggerHelper.TryDigging(), Minecart.TryFittingTileOrientation(), PlayerSittingHelper.TryGetSittingBlock(), Player.TryLandingOnDetonator(), Player.TryPlacingAGolfBallNearANearbyTee(), Player.TryUsingDiggerCart(), Chest.Unlock(), Player.UpdateBiomes(), Dust.UpdateDust(), and WorldGen.UpdateWorld_UndergroundTile().