Terraria: Framing.Initialize
Initialize()
static void Framing.Initialize () inline static
     {
         selfFrame8WayLookup = new Point16[256][];
         frameSize8Way = new Point16(18, 18);
         Add8WayLookup(0, 9, 3, 10, 3, 11, 3);
         Add8WayLookup(1, 6, 3, 7, 3, 8, 3);
         Add8WayLookup(2, 12, 0, 12, 1, 12, 2);
         Add8WayLookup(3, 15, 2);
         Add8WayLookup(4, 9, 0, 9, 1, 9, 2);
         Add8WayLookup(5, 13, 2);
         Add8WayLookup(6, 6, 4, 7, 4, 8, 4);
         Add8WayLookup(7, 14, 2);
         Add8WayLookup(8, 6, 0, 7, 0, 8, 0);
         Add8WayLookup(9, 5, 0, 5, 1, 5, 2);
         Add8WayLookup(10, 15, 0);
         Add8WayLookup(11, 15, 1);
         Add8WayLookup(12, 13, 0);
         Add8WayLookup(13, 13, 1);
         Add8WayLookup(14, 14, 0);
         Add8WayLookup(15, 14, 1);
         Add8WayLookup(19, 1, 4, 3, 4, 5, 4);
         Add8WayLookup(23, 16, 3);
         Add8WayLookup(27, 17, 0);
         Add8WayLookup(31, 13, 4);
         Add8WayLookup(37, 0, 4, 2, 4, 4, 4);
         Add8WayLookup(39, 17, 3);
         Add8WayLookup(45, 16, 0);
         Add8WayLookup(47, 12, 4);
         Add8WayLookup(55, 1, 2, 2, 2, 3, 2);
         Add8WayLookup(63, 6, 2, 7, 2, 8, 2);
         Add8WayLookup(74, 1, 3, 3, 3, 5, 3);
         Add8WayLookup(75, 17, 1);
         Add8WayLookup(78, 16, 2);
         Add8WayLookup(79, 13, 3);
         Add8WayLookup(91, 4, 0, 4, 1, 4, 2);
         Add8WayLookup(95, 11, 0, 11, 1, 11, 2);
         Add8WayLookup(111, 17, 4);
         Add8WayLookup(127, 14, 3);
         Add8WayLookup(140, 0, 3, 2, 3, 4, 3);
         Add8WayLookup(141, 16, 1);
         Add8WayLookup(142, 17, 2);
         Add8WayLookup(143, 12, 3);
         Add8WayLookup(159, 16, 4);
         Add8WayLookup(173, 0, 0, 0, 1, 0, 2);
         Add8WayLookup(175, 10, 0, 10, 1, 10, 2);
         Add8WayLookup(191, 15, 3);
         Add8WayLookup(206, 1, 0, 2, 0, 3, 0);
         Add8WayLookup(207, 6, 1, 7, 1, 8, 1);
         Add8WayLookup(223, 14, 4);
         Add8WayLookup(239, 15, 4);
         Add8WayLookup(255, 1, 1, 2, 1, 3, 1);
         blockStyleLookup = new BlockStyle[6];
         blockStyleLookup[0] = new BlockStyle(up: true, down: true, left: true, right: true);
         blockStyleLookup[1] = new BlockStyle(up: false, down: true, left: true, right: true);
         blockStyleLookup[2] = new BlockStyle(up: false, down: true, left: true, right: false);
         blockStyleLookup[3] = new BlockStyle(up: false, down: true, left: false, right: true);
         blockStyleLookup[4] = new BlockStyle(up: true, down: false, left: true, right: false);
         blockStyleLookup[5] = new BlockStyle(up: true, down: false, left: false, right: true);
         phlebasTileFrameNumberLookup = new int[4][]
         {
             new int[3] { 2, 4, 2 },
             new int[3] { 1, 3, 1 },
             new int[3] { 2, 2, 4 },
             new int[3] { 1, 1, 3 }
         };
         lazureTileFrameNumberLookup = new int[2][]
         {
             new int[2] { 1, 3 },
             new int[2] { 2, 4 }
         };
         centerWallFrameLookup = new int[3][]
         {
             new int[3] { 2, 0, 0 },
             new int[3] { 0, 1, 4 },
             new int[3] { 0, 3, 0 }
         };
         wallFrameLookup = new Point16[20][];
         wallFrameSize = new Point16(36, 36);
         AddWallFrameLookup(0, 9, 3, 10, 3, 11, 3, 6, 6);
         AddWallFrameLookup(1, 6, 3, 7, 3, 8, 3, 4, 6);
         AddWallFrameLookup(2, 12, 0, 12, 1, 12, 2, 12, 5);
         AddWallFrameLookup(3, 1, 4, 3, 4, 5, 4, 3, 6);
         AddWallFrameLookup(4, 9, 0, 9, 1, 9, 2, 9, 5);
         AddWallFrameLookup(5, 0, 4, 2, 4, 4, 4, 2, 6);
         AddWallFrameLookup(6, 6, 4, 7, 4, 8, 4, 5, 6);
         AddWallFrameLookup(7, 1, 2, 2, 2, 3, 2, 3, 5);
         AddWallFrameLookup(8, 6, 0, 7, 0, 8, 0, 6, 5);
         AddWallFrameLookup(9, 5, 0, 5, 1, 5, 2, 5, 5);
         AddWallFrameLookup(10, 1, 3, 3, 3, 5, 3, 1, 6);
         AddWallFrameLookup(11, 4, 0, 4, 1, 4, 2, 4, 5);
         AddWallFrameLookup(12, 0, 3, 2, 3, 4, 3, 0, 6);
         AddWallFrameLookup(13, 0, 0, 0, 1, 0, 2, 0, 5);
         AddWallFrameLookup(14, 1, 0, 2, 0, 3, 0, 1, 5);
         AddWallFrameLookup(15, 1, 1, 2, 1, 3, 1, 2, 5);
         AddWallFrameLookup(16, 6, 1, 7, 1, 8, 1, 7, 5);
         AddWallFrameLookup(17, 6, 2, 7, 2, 8, 2, 8, 5);
         AddWallFrameLookup(18, 10, 0, 10, 1, 10, 2, 10, 5);
         AddWallFrameLookup(19, 11, 0, 11, 1, 11, 2, 11, 5);
     }
References Add8WayLookup(), AddWallFrameLookup(), blockStyleLookup, centerWallFrameLookup, frameSize8Way, lazureTileFrameNumberLookup, phlebasTileFrameNumberLookup, selfFrame8WayLookup, wallFrameLookup, and wallFrameSize.
Referenced by Main.Initialize_AlmostEverything().