Terraria: Framing.WallFrame
WallFrame()
static void Framing.WallFrame (int i, int j, bool resetFrame = false) inline static
     {
         if (WorldGen.SkipFramingBecauseOfGen || i <= 0 || j <= 0 || i >= Main.maxTilesX - 1 || j >= Main.maxTilesY - 1 || Main.tile[i, j] == null)
         {
             return;
         }
         if (Main.tile[i, j].wall >= WallID.Count)
         {
             Main.tile[i, j].wall = 0;
         }
         WorldGen.UpdateMapTile(i, j);
         Tile tile = Main.tile[i, j];
         if (tile.wall == 0)
         {
             tile.wallColor(0);
             tile.ClearWallPaintAndCoating();
             return;
         }
         int num = 0;
         bool flag = Main.ShouldShowInvisibleWalls();
         if (j - 1 >= 0)
         {
             Tile tile2 = Main.tile[i, j - 1];
             if (tile2 != null && (tile2.wall > 0 || (tile2.active() && tile2.type == 54)) && (flag || !tile2.invisibleWall()))
             {
                 num = 1;
             }
         }
         if (i - 1 >= 0)
         {
             Tile tile2 = Main.tile[i - 1, j];
             if (tile2 != null && (tile2.wall > 0 || (tile2.active() && tile2.type == 54)) && (flag || !tile2.invisibleWall()))
             {
                 num |= 2;
             }
         }
         if (i + 1 <= Main.maxTilesX - 1)
         {
             Tile tile2 = Main.tile[i + 1, j];
             if (tile2 != null && (tile2.wall > 0 || (tile2.active() && tile2.type == 54)) && (flag || !tile2.invisibleWall()))
             {
                 num |= 4;
             }
         }
         if (j + 1 <= Main.maxTilesY - 1)
         {
             Tile tile2 = Main.tile[i, j + 1];
             if (tile2 != null && (tile2.wall > 0 || (tile2.active() && tile2.type == 54)) && (flag || !tile2.invisibleWall()))
             {
                 num |= 8;
             }
         }
         int num2 = 0;
         if (Main.wallLargeFrames[tile.wall] == 1)
         {
             num2 = phlebasTileFrameNumberLookup[j % 4][i % 3] - 1;
             tile.wallFrameNumber((byte)num2);
         }
         else if (Main.wallLargeFrames[tile.wall] == 2)
         {
             num2 = lazureTileFrameNumberLookup[i % 2][j % 2] - 1;
             tile.wallFrameNumber((byte)num2);
         }
         else if (resetFrame)
         {
             num2 = WorldGen.genRand.Next(0, 3);
             if (tile.wall == 21 && WorldGen.genRand.Next(2) == 0)
             {
                 num2 = 2;
             }
             tile.wallFrameNumber((byte)num2);
         }
         else
         {
             num2 = tile.wallFrameNumber();
         }
         if (num == 15)
         {
             num += centerWallFrameLookup[i % 3][j % 3];
         }
         Point16 point = wallFrameLookup[num][num2];
         tile.wallFrameX(point.X);
         tile.wallFrameY(point.Y);
     }
References Tile.active(), centerWallFrameLookup, Tile.ClearWallPaintAndCoating(), WallID.Count, WorldGen.genRand, Tile.invisibleWall(), lazureTileFrameNumberLookup, Main.maxTilesX, Main.maxTilesY, UnifiedRandom.Next(), phlebasTileFrameNumberLookup, Main.ShouldShowInvisibleWalls(), WorldGen.SkipFramingBecauseOfGen, Main.tile, Tile.type, WorldGen.UpdateMapTile(), Tile.wall, Tile.wallColor(), wallFrameLookup, Tile.wallFrameNumber(), Tile.wallFrameX(), Tile.wallFrameY(), Main.wallLargeFrames, Point16.X, and Point16.Y.
Referenced by WorldGen.EveryTileFrame(), WorldGen.RangeFrame(), WorldGen.Reframe(), and WorldGen.SquareWallFrame().