Terraria: System.Threading.LowLevelLock.WaitAndAcquire
WaitAndAcquire()
void System.Threading.LowLevelLock.WaitAndAcquire () inline private
Definition at line 65 of file LowLevelLock.cs.
    {
        if (!_spinWaiter.SpinWaitForCondition(_spinWaitTryAcquireCallback, 8, 4))
        {
            _monitor.Acquire();
            int num = Interlocked.Add(ref _state, 2);
            while (((uint)num & (true ? 1u : 0u)) != 0 || Interlocked.CompareExchange(ref _state, num + -1, num) != num)
            {
                _monitor.Wait();
                _isAnyWaitingThreadSignaled = false;
                num = _state;
            }
            _monitor.Release();
        }
    }
References System.Threading.LowLevelLock._isAnyWaitingThreadSignaled, System.Threading.LowLevelLock._monitor, System.Threading.LowLevelLock._spinWaiter, System.Threading.LowLevelLock._spinWaitTryAcquireCallback, System.Threading.LowLevelLock._state, System.Threading.LowLevelMonitor.Acquire(), System.Threading.Interlocked.Add(), System.Threading.Interlocked.CompareExchange(), System.Threading.LowLevelMonitor.Release(), System.Threading.LowLevelSpinWaiter.SpinWaitForCondition(), and System.Threading.LowLevelMonitor.Wait().
Referenced by System.Threading.LowLevelLock.Acquire().