Terraria: System.Threading.LowLevelLock.SignalWaiter
SignalWaiter()
void System.Threading.LowLevelLock.SignalWaiter () inline private
Definition at line 89 of file LowLevelLock.cs.
    {
        _monitor.Acquire();
        if ((uint)_state >= 2u && !_isAnyWaitingThreadSignaled)
        {
            _isAnyWaitingThreadSignaled = true;
            _monitor.Signal_Release();
        }
        else
        {
            _monitor.Release();
        }
    }
References System.Threading.LowLevelLock._isAnyWaitingThreadSignaled, System.Threading.LowLevelLock._monitor, System.Threading.LowLevelLock._state, System.Threading.LowLevelMonitor.Acquire(), System.Threading.LowLevelMonitor.Release(), and System.Threading.LowLevelMonitor.Signal_Release().
Referenced by System.Threading.LowLevelLock.Release().