Terraria: Terraria.GameInput.KeyConfiguration.ReadPreferences
ReadPreferences()
void Terraria.GameInput.KeyConfiguration.ReadPreferences (Dictionary< string, List< string > > dict) inline
Definition at line 58 of file KeyConfiguration.cs.
    {
        foreach (KeyValuePair<string, List<string>> item in dict)
        {
            if (!KeyStatus.ContainsKey(item.Key))
            {
                continue;
            }
            KeyStatus[item.Key].Clear();
            foreach (string item2 in item.Value)
            {
                KeyStatus[item.Key].Add(item2);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), and Terraria.GameInput.KeyConfiguration.KeyStatus.