Terraria: System.IO.FileSystemWatcher.NotifyInternalBufferOverflowEvent
NotifyInternalBufferOverflowEvent()
void System.IO.FileSystemWatcher.NotifyInternalBufferOverflowEvent () inline private
Definition at line 482 of file FileSystemWatcher.cs.
    {
        if (_onErrorHandler != null)
        {
            OnError(new ErrorEventArgs(new InternalBufferOverflowException(System.SR.Format(System.SR.FSW_BufferOverflow, _directory))));
        }
    }
References System.IO.FileSystemWatcher._directory, System.IO.FileSystemWatcher._onErrorHandler, System.SR.Format(), System.SR.FSW_BufferOverflow, and System.IO.FileSystemWatcher.OnError().
Referenced by System.IO.FileSystemWatcher.ReadDirectoryChangesCallback().