Terraria: System.IO.FileSystemWatcher.StopRaisingEvents
StopRaisingEvents()
void System.IO.FileSystemWatcher.StopRaisingEvents () inline private
Definition at line 754 of file FileSystemWatcher.cs.
    {
        _enabled = false;
        if (!IsSuspended() && !IsHandleInvalid(_directoryHandle))
        {
            Interlocked.Increment(ref _currentSession);
            _directoryHandle.Dispose();
            _directoryHandle = null;
        }
    }
References System.IO.FileSystemWatcher._currentSession, System.IO.FileSystemWatcher._directoryHandle, System.IO.FileSystemWatcher._enabled, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Threading.Interlocked.Increment(), System.IO.FileSystemWatcher.IsHandleInvalid(), and System.IO.FileSystemWatcher.IsSuspended().
Referenced by System.IO.FileSystemWatcher.BeginInit(), System.IO.FileSystemWatcher.Dispose(), and System.IO.FileSystemWatcher.Restart().