Terraria: System.IO.FileSystemWatcher.Monitor
Monitor()
unsafe void System.IO.FileSystemWatcher.Monitor (AsyncReadState state) inline private
Definition at line 782 of file FileSystemWatcher.cs.
    {
        NativeOverlapped* ptr = null;
        bool flag = false;
        try
        {
            if (_enabled && !IsHandleInvalid(state.DirectoryHandle))
            {
                ptr = state.ThreadPoolBinding.AllocateNativeOverlapped(state.PreAllocatedOverlapped);
                flag = global::Interop.Kernel32.ReadDirectoryChangesW(state.DirectoryHandle, state.Buffer, _internalBufferSize, _includeSubdirectories, (uint)_notifyFilters, null, ptr, null);
            }
        }
        catch (ObjectDisposedException)
        {
        }
        catch (ArgumentNullException)
        {
        }
        finally
        {
            if (!flag)
            {
                if (ptr != null)
                {
                    state.ThreadPoolBinding.FreeNativeOverlapped(ptr);
                }
                state.PreAllocatedOverlapped.Dispose();
                state.ThreadPoolBinding.Dispose();
                if (!IsHandleInvalid(state.DirectoryHandle))
                {
                    OnError(new ErrorEventArgs(new Win32Exception()));
                }
            }
        }
    }
References System.IO.FileSystemWatcher._enabled, System.IO.FileSystemWatcher._includeSubdirectories, System.IO.FileSystemWatcher._internalBufferSize, System.IO.FileSystemWatcher._notifyFilters, System.IO.FileSystemWatcher.IsHandleInvalid(), System.IO.FileSystemWatcher.OnError(), and System.state.
Referenced by System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(), and System.IO.FileSystemWatcher.StartRaisingEvents().