Terraria: System.IO.FileSystemWatcher.InvokeOn
InvokeOn()
void System.IO.FileSystemWatcher.InvokeOn (FileSystemEventArgs e, FileSystemEventHandler handler) inline private
Definition at line 533 of file FileSystemWatcher.cs.
    {
        if (handler != null)
        {
            ISynchronizeInvoke synchronizingObject = SynchronizingObject;
            if (synchronizingObject != null && synchronizingObject.InvokeRequired)
            {
                synchronizingObject.BeginInvoke(handler, new object[2] { this, e });
            }
            else
            {
                handler(this, e);
            }
        }
    }
References System.IO.FileSystemWatcher.SynchronizingObject.
Referenced by System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(), System.IO.FileSystemWatcher.OnChanged(), System.IO.FileSystemWatcher.OnCreated(), and System.IO.FileSystemWatcher.OnDeleted().