Terraria: System.IO.FileSystemWatcher.StartRaisingEvents
StartRaisingEvents()
unsafe void System.IO.FileSystemWatcher.StartRaisingEvents () inline private
Definition at line 709 of file FileSystemWatcher.cs.
    {
        if (IsSuspended())
        {
            _enabled = true;
        }
        else
        {
            if (!IsHandleInvalid(_directoryHandle))
            {
                return;
            }
            _directoryHandle = global::Interop.Kernel32.CreateFile(_directory, 1, FileShare.ReadWrite | FileShare.Delete, FileMode.Open, 1107296256);
            if (IsHandleInvalid(_directoryHandle))
            {
                _directoryHandle = null;
                throw new FileNotFoundException(System.SR.Format(System.SR.FSW_IOError, _directory));
            }
            AsyncReadState asyncReadState;
            try
            {
                int session = Interlocked.Increment(ref _currentSession);
                byte[] array = AllocateBuffer();
                asyncReadState = new AsyncReadState(session, array, _directoryHandle, ThreadPoolBoundHandle.BindHandle(_directoryHandle), this);
                asyncReadState.PreAllocatedOverlapped = new PreAllocatedOverlapped(delegate(uint errorCode, uint numBytes, NativeOverlapped* overlappedPointer)
                {
                    AsyncReadState asyncReadState2 = (AsyncReadState)ThreadPoolBoundHandle.GetNativeOverlappedState(overlappedPointer);
                    asyncReadState2.ThreadPoolBinding.FreeNativeOverlapped(overlappedPointer);
                    if (asyncReadState2.WeakWatcher.TryGetTarget(out var target))
                    {
                        target.ReadDirectoryChangesCallback(errorCode, numBytes, asyncReadState2);
                    }
                }, asyncReadState, array);
            }
            catch
            {
                _directoryHandle.Dispose();
                _directoryHandle = null;
                throw;
            }
            _enabled = true;
            Monitor(asyncReadState);
        }
    }
References System.IO.FileSystemWatcher._currentSession, System.IO.FileSystemWatcher._directory, System.IO.FileSystemWatcher._directoryHandle, System.IO.FileSystemWatcher._enabled, System.IO.FileSystemWatcher.AllocateBuffer(), System.array, System.Threading.ThreadPoolBoundHandle.BindHandle(), Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.SR.Format(), System.SR.FSW_IOError, System.Threading.ThreadPoolBoundHandle.GetNativeOverlappedState(), System.Threading.Interlocked.Increment(), System.IO.FileSystemWatcher.IsHandleInvalid(), System.IO.FileSystemWatcher.IsSuspended(), and System.IO.FileSystemWatcher.Monitor().
Referenced by System.IO.FileSystemWatcher.EndInit(), and System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed().