Terraria: System.IO.FileSystemWatcher.IsHandleInvalid
IsHandleInvalid()
static bool System.IO.FileSystemWatcher.IsHandleInvalid ([NotNullWhen(false)] SafeFileHandle handle) inline static private
Definition at line 773 of file FileSystemWatcher.cs.
    {
        if (handle != null && !handle.IsInvalid)
        {
            return handle.IsClosed;
        }
        return true;
    }
References System.handle.
Referenced by System.IO.FileSystemWatcher.FinalizeDispose(), System.IO.FileSystemWatcher.Monitor(), System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(), System.IO.FileSystemWatcher.StartRaisingEvents(), and System.IO.FileSystemWatcher.StopRaisingEvents().