Terraria: System.IO.FileSystemWatcher.ReadDirectoryChangesCallback
ReadDirectoryChangesCallback()
void System.IO.FileSystemWatcher.ReadDirectoryChangesCallback (uint errorCode, uint numBytes, AsyncReadState state) inline private
Definition at line 818 of file FileSystemWatcher.cs.
    {
        try
        {
            if (IsHandleInvalid(state.DirectoryHandle))
            {
                return;
            }
            switch (errorCode)
            {
            default:
                OnError(new ErrorEventArgs(new Win32Exception((int)errorCode)));
                EnableRaisingEvents = false;
                break;
            case 995u:
                break;
            case 0u:
                if (state.Session == Volatile.Read(ref _currentSession))
                {
                    if (numBytes == 0)
                    {
                        NotifyInternalBufferOverflowEvent();
                    }
                    else
                    {
                        ParseEventBufferAndNotifyForEach(new ReadOnlySpan<byte>(state.Buffer, 0, (int)numBytes));
                    }
                }
                break;
            }
        }
        finally
        {
            Monitor(state);
        }
    }
References System.IO.FileSystemWatcher._currentSession, System.IO.FileSystemWatcher.EnableRaisingEvents, System.IO.FileSystemWatcher.IsHandleInvalid(), System.IO.FileSystemWatcher.Monitor(), System.IO.FileSystemWatcher.NotifyInternalBufferOverflowEvent(), System.IO.FileSystemWatcher.OnError(), System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(), System.Threading.Volatile.Read(), and System.state.