Terraria: System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach
ParseEventBufferAndNotifyForEach()
unsafe void System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach (ReadOnlySpan< byte > buffer) inline private
Definition at line 855 of file FileSystemWatcher.cs.
    {
        ReadOnlySpan<char> oldName = ReadOnlySpan<char>.Empty;
        while (sizeof(global::Interop.Kernel32.FILE_NOTIFY_INFORMATION) <= (uint)buffer.Length)
        {
            ref readonly global::Interop.Kernel32.FILE_NOTIFY_INFORMATION reference = ref MemoryMarshal.AsRef<global::Interop.Kernel32.FILE_NOTIFY_INFORMATION>(buffer);
            if (reference.FileNameLength > (uint)buffer.Length - sizeof(global::Interop.Kernel32.FILE_NOTIFY_INFORMATION))
            {
                break;
            }
            ReadOnlySpan<char> readOnlySpan = MemoryMarshal.Cast<byte, char>(buffer.Slice(sizeof(global::Interop.Kernel32.FILE_NOTIFY_INFORMATION), (int)reference.FileNameLength));
            switch (reference.Action)
            {
            case global::Interop.Kernel32.FileAction.FILE_ACTION_RENAMED_OLD_NAME:
                oldName = readOnlySpan;
                break;
            case global::Interop.Kernel32.FileAction.FILE_ACTION_RENAMED_NEW_NAME:
                NotifyRenameEventArgs(WatcherChangeTypes.Renamed, readOnlySpan, oldName);
                oldName = ReadOnlySpan<char>.Empty;
                break;
            default:
                if (!oldName.IsEmpty)
                {
                    NotifyRenameEventArgs(WatcherChangeTypes.Renamed, ReadOnlySpan<char>.Empty, oldName);
                    oldName = ReadOnlySpan<char>.Empty;
                }
                switch (reference.Action)
                {
                case global::Interop.Kernel32.FileAction.FILE_ACTION_ADDED:
                    NotifyFileSystemEventArgs(WatcherChangeTypes.Created, readOnlySpan);
                    break;
                case global::Interop.Kernel32.FileAction.FILE_ACTION_REMOVED:
                    NotifyFileSystemEventArgs(WatcherChangeTypes.Deleted, readOnlySpan);
                    break;
                case global::Interop.Kernel32.FileAction.FILE_ACTION_MODIFIED:
                    NotifyFileSystemEventArgs(WatcherChangeTypes.Changed, readOnlySpan);
                    break;
                }
                break;
            }
            if (reference.NextEntryOffset == 0 || reference.NextEntryOffset > (uint)buffer.Length)
            {
                break;
            }
            buffer = buffer.Slice((int)reference.NextEntryOffset);
        }
        if (!oldName.IsEmpty)
        {
            NotifyRenameEventArgs(WatcherChangeTypes.Renamed, ReadOnlySpan<char>.Empty, oldName);
        }
    }
References System.buffer, System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(), and System.IO.FileSystemWatcher.NotifyRenameEventArgs().
Referenced by System.IO.FileSystemWatcher.ReadDirectoryChangesCallback().