Terraria: System.IO.FileSystemWatcher.MatchPattern
MatchPattern()
bool System.IO.FileSystemWatcher.MatchPattern (ReadOnlySpan< char > relativePath) inline private
Definition at line 459 of file FileSystemWatcher.cs.
    {
        ReadOnlySpan<char> fileName = System.IO.Path.GetFileName(relativePath);
        if (fileName.Length == 0)
        {
            return false;
        }
        string[] filters = _filters.GetFilters();
        if (filters.Length == 0)
        {
            return true;
        }
        string[] array = filters;
        foreach (string text in array)
        {
            if (FileSystemName.MatchesSimpleExpression(text, fileName, !System.IO.PathInternal.IsCaseSensitive))
            {
                return true;
            }
        }
        return false;
    }
References System.IO.FileSystemWatcher._filters, System.array, System.IO.Path.GetFileName(), System.IO.FileSystemWatcher.NormalizedFilterCollection.GetFilters(), System.IO.PathInternal.IsCaseSensitive, System.IO.Enumeration.FileSystemName.MatchesSimpleExpression(), and System.text.
Referenced by System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(), and System.IO.FileSystemWatcher.NotifyRenameEventArgs().