Terraria: System.Net.Quic.Implementations.MsQuic.Internal.MsQuicStatusHelper.SuccessfulStatusCode
SuccessfulStatusCode()
static bool System.Net.Quic.Implementations.MsQuic.Internal.MsQuicStatusHelper.SuccessfulStatusCode (uint status) inline static package
Definition at line 5 of file MsQuicStatusHelper.cs.
    {
        if (OperatingSystem.IsWindows())
        {
            return status < 2147483648u;
        }
        if (OperatingSystem.IsLinux() || OperatingSystem.IsMacOS())
        {
            return (int)status <= 0;
        }
        return false;
    }
References System.OperatingSystem.IsLinux(), System.OperatingSystem.IsMacOS(), and System.OperatingSystem.IsWindows().
Referenced by System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.NativeCallbackHandler(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlyMemoryListAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync(), and System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed().