Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArrayAsBytes
ReadArrayAsBytes()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArrayAsBytes (ParseRecord pr) inline private
Definition at line 828 of file BinaryParser.cs.
    {
        if (pr._arrayElementTypeCode == InternalPrimitiveTypeE.Byte)
        {
            pr._newObj = ReadBytes(pr._lengthA[0]);
            return;
        }
        if (pr._arrayElementTypeCode == InternalPrimitiveTypeE.Char)
        {
            pr._newObj = ReadChars(pr._lengthA[0]);
            return;
        }
        int num = Converter.TypeLength(pr._arrayElementTypeCode);
        pr._newObj = Converter.CreatePrimitiveArray(pr._arrayElementTypeCode, pr._lengthA[0]);
        Array array = (Array)pr._newObj;
        int i = 0;
        if (_byteBuffer == null)
        {
            _byteBuffer = new byte[4096];
        }
        int num2;
        for (; i < array.Length; i += num2)
        {
            num2 = Math.Min(4096 / num, array.Length - i);
            int num3 = num2 * num;
            ReadBytes(_byteBuffer, 0, num3);
            if (!BitConverter.IsLittleEndian)
            {
                for (int j = 0; j < num3; j += num)
                {
                    for (int k = 0; k < num / 2; k++)
                    {
                        byte b = _byteBuffer[j + k];
                        _byteBuffer[j + k] = _byteBuffer[j + num - 1 - k];
                        _byteBuffer[j + num - 1 - k] = b;
                    }
                }
            }
            Buffer.BlockCopy(_byteBuffer, 0, array, i * num, num3);
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._byteBuffer, System.array, System.Runtime.Serialization.Formatters.Binary.Array, System.Buffer.BlockCopy(), System.Runtime.Serialization.Formatters.Binary.Converter.CreatePrimitiveArray(), System.Runtime.Serialization.Dictionary, System.BitConverter.IsLittleEndian, System.Math.Min(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadBytes(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadChars(), and System.Runtime.Serialization.Formatters.Binary.Converter.TypeLength().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArray().