Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveUnTyped
ReadMemberPrimitiveUnTyped()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveUnTyped () inline private
Definition at line 871 of file BinaryParser.cs.
    {
        ObjectProgress objectProgress = (ObjectProgress)_stack.Peek();
        if (memberPrimitiveUnTyped == null)
        {
            memberPrimitiveUnTyped = new MemberPrimitiveUnTyped();
        }
        memberPrimitiveUnTyped.Set((InternalPrimitiveTypeE)_expectedTypeInformation);
        memberPrimitiveUnTyped.Read(this);
        PRs.Init();
        PRs._varValue = memberPrimitiveUnTyped._value;
        PRs._dtTypeCode = (InternalPrimitiveTypeE)_expectedTypeInformation;
        PRs._dtType = Converter.ToType(PRs._dtTypeCode);
        PRs._parseTypeEnum = InternalParseTypeE.Member;
        PRs._memberValueEnum = InternalMemberValueE.InlineValue;
        if (objectProgress._objectTypeEnum == InternalObjectTypeE.Object)
        {
            PRs._memberTypeEnum = InternalMemberTypeE.Field;
            PRs._name = objectProgress._name;
        }
        else
        {
            PRs._memberTypeEnum = InternalMemberTypeE.Item;
        }
        _objectReader.Parse(PRs);
    }
References System.Runtime.Serialization.Formatters.Binary.ParseRecord._dtTypeCode, System.Runtime.Serialization.Formatters.Binary.BinaryParser._expectedTypeInformation, System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped._value, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.memberPrimitiveUnTyped, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.PRs, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Read(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Set(), and System.Runtime.Serialization.Formatters.Binary.Converter.ToType().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().