Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectString
ReadObjectString()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectString (BinaryHeaderEnum binaryHeaderEnum) inline private
Definition at line 605 of file BinaryParser.cs.
    {
        if (_objectString == null)
        {
            _objectString = new BinaryObjectString();
        }
        if (binaryHeaderEnum == BinaryHeaderEnum.ObjectString)
        {
            _objectString.Read(this);
        }
        else
        {
            if (_crossAppDomainString == null)
            {
                _crossAppDomainString = new BinaryCrossAppDomainString();
            }
            _crossAppDomainString.Read(this);
            _objectString._value = _objectReader.CrossAppDomainArray(_crossAppDomainString._value) as string;
            if (_objectString._value == null)
            {
                throw new SerializationException(System.SR.Format(System.SR.Serialization_CrossAppDomainError, "String", _crossAppDomainString._value));
            }
            _objectString._objectId = _crossAppDomainString._objectId;
        }
        PRs.Init();
        PRs._parseTypeEnum = InternalParseTypeE.Object;
        PRs._objectId = _objectReader.GetId(_objectString._objectId);
        if (PRs._objectId == _topId)
        {
            PRs._objectPositionEnum = InternalObjectPositionE.Top;
        }
        PRs._objectTypeEnum = InternalObjectTypeE.Object;
        ObjectProgress objectProgress = (ObjectProgress)_stack.Peek();
        PRs._value = _objectString._value;
        PRs._keyDt = "System.String";
        PRs._dtType = Converter.s_typeofString;
        PRs._dtTypeCode = InternalPrimitiveTypeE.Invalid;
        PRs._varValue = _objectString._value;
        if (objectProgress == null)
        {
            PRs._parseTypeEnum = InternalParseTypeE.Object;
            PRs._name = "System.String";
        }
        else
        {
            PRs._parseTypeEnum = InternalParseTypeE.Member;
            PRs._memberValueEnum = InternalMemberValueE.InlineValue;
            switch (objectProgress._objectTypeEnum)
            {
            case InternalObjectTypeE.Object:
                PRs._name = objectProgress._name;
                PRs._memberTypeEnum = InternalMemberTypeE.Field;
                break;
            case InternalObjectTypeE.Array:
                PRs._memberTypeEnum = InternalMemberTypeE.Item;
                break;
            default:
                throw new SerializationException(System.SR.Format(System.SR.Serialization_ObjectTypeEnum, objectProgress._objectTypeEnum.ToString()));
            }
        }
        _objectReader.Parse(PRs);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._crossAppDomainString, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainString._objectId, System.Runtime.Serialization.Formatters.Binary.BinaryObjectString._objectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord._objectId, System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectString, System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack, System.Runtime.Serialization.Formatters.Binary.BinaryParser._topId, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainString._value, System.Runtime.Serialization.Formatters.Binary.BinaryObjectString._value, System.Runtime.Serialization.Formatters.Binary.ObjectReader.CrossAppDomainArray(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.PRs, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainString.Read(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.Read(), System.Runtime.Serialization.Formatters.Binary.Converter.s_typeofString, System.SR.Serialization_CrossAppDomainError, and System.SR.Serialization_ObjectTypeEnum.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().