Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberReference
ReadMemberReference()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberReference () inline private
Definition at line 899 of file BinaryParser.cs.
    {
        if (_memberReference == null)
        {
            _memberReference = new MemberReference();
        }
        _memberReference.Read(this);
        ObjectProgress objectProgress = (ObjectProgress)_stack.Peek();
        PRs.Init();
        PRs._idRef = _objectReader.GetId(_memberReference._idRef);
        PRs._parseTypeEnum = InternalParseTypeE.Member;
        PRs._memberValueEnum = InternalMemberValueE.Reference;
        if (objectProgress._objectTypeEnum == InternalObjectTypeE.Object)
        {
            PRs._memberTypeEnum = InternalMemberTypeE.Field;
            PRs._name = objectProgress._name;
            PRs._dtType = objectProgress._dtType;
        }
        else
        {
            PRs._memberTypeEnum = InternalMemberTypeE.Item;
        }
        _objectReader.Parse(PRs);
    }
References System.Runtime.Serialization.Formatters.Binary.MemberReference._idRef, System.Runtime.Serialization.Formatters.Binary.BinaryParser._memberReference, System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.MemberReference, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.PRs, and System.Runtime.Serialization.Formatters.Binary.MemberReference.Read().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().