Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap
ReadObjectWithMap() [1/2]
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap (BinaryHeaderEnum binaryHeaderEnum) inline package
Definition at line 432 of file BinaryParser.cs.
    {
        if (_bowm == null)
        {
            _bowm = new BinaryObjectWithMap(binaryHeaderEnum);
        }
        else
        {
            _bowm._binaryHeaderEnum = binaryHeaderEnum;
        }
        _bowm.Read(this);
        ReadObjectWithMap(_bowm);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._bowm, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Read(), and System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadCrossAppDomainMap(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap(), and System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().