Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArray
ReadArray()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArray (BinaryHeaderEnum binaryHeaderEnum) inline private
Definition at line 709 of file BinaryParser.cs.
    {
        BinaryAssemblyInfo binaryAssemblyInfo = null;
        BinaryArray binaryArray = new BinaryArray(binaryHeaderEnum);
        binaryArray.Read(this);
        if (binaryArray._binaryTypeEnum == BinaryTypeEnum.ObjectUser)
        {
            if (binaryArray._assemId < 1)
            {
                throw new SerializationException(System.SR.Format(System.SR.Serialization_AssemblyId, binaryArray._typeInformation));
            }
            binaryAssemblyInfo = (BinaryAssemblyInfo)AssemIdToAssemblyTable[binaryArray._assemId];
        }
        else
        {
            binaryAssemblyInfo = SystemAssemblyInfo;
        }
        ObjectProgress op = GetOp();
        ParseRecord pr = op._pr;
        op._objectTypeEnum = InternalObjectTypeE.Array;
        op._binaryTypeEnum = binaryArray._binaryTypeEnum;
        op._typeInformation = binaryArray._typeInformation;
        ObjectProgress objectProgress = (ObjectProgress)_stack.PeekPeek();
        if (objectProgress == null || binaryArray._objectId > 0)
        {
            op._name = "System.Array";
            pr._parseTypeEnum = InternalParseTypeE.Object;
            op._memberValueEnum = InternalMemberValueE.Empty;
        }
        else
        {
            pr._parseTypeEnum = InternalParseTypeE.Member;
            pr._memberValueEnum = InternalMemberValueE.Nested;
            op._memberValueEnum = InternalMemberValueE.Nested;
            switch (objectProgress._objectTypeEnum)
            {
            case InternalObjectTypeE.Object:
                pr._name = objectProgress._name;
                pr._memberTypeEnum = InternalMemberTypeE.Field;
                op._memberTypeEnum = InternalMemberTypeE.Field;
                pr._keyDt = objectProgress._name;
                pr._dtType = objectProgress._dtType;
                break;
            case InternalObjectTypeE.Array:
                pr._memberTypeEnum = InternalMemberTypeE.Item;
                op._memberTypeEnum = InternalMemberTypeE.Item;
                break;
            default:
                throw new SerializationException(System.SR.Format(System.SR.Serialization_ObjectTypeEnum, objectProgress._objectTypeEnum.ToString()));
            }
        }
        pr._objectId = _objectReader.GetId(binaryArray._objectId);
        if (pr._objectId == _topId)
        {
            pr._objectPositionEnum = InternalObjectPositionE.Top;
        }
        else if (_headerId > 0 && pr._objectId == _headerId)
        {
            pr._objectPositionEnum = InternalObjectPositionE.Headers;
        }
        else
        {
            pr._objectPositionEnum = InternalObjectPositionE.Child;
        }
        pr._objectTypeEnum = InternalObjectTypeE.Array;
        BinaryTypeConverter.TypeFromInfo(binaryArray._binaryTypeEnum, binaryArray._typeInformation, _objectReader, binaryAssemblyInfo, out pr._arrayElementTypeCode, out pr._arrayElementTypeString, out pr._arrayElementType, out pr._isArrayVariant);
        pr._dtTypeCode = InternalPrimitiveTypeE.Invalid;
        pr._rank = binaryArray._rank;
        pr._lengthA = binaryArray._lengthA;
        pr._lowerBoundA = binaryArray._lowerBoundA;
        bool flag = false;
        switch (binaryArray._binaryArrayTypeEnum)
        {
        case BinaryArrayTypeEnum.Single:
        case BinaryArrayTypeEnum.SingleOffset:
            op._numItems = binaryArray._lengthA[0];
            pr._arrayTypeEnum = InternalArrayTypeE.Single;
            if (Converter.IsWriteAsByteArray(pr._arrayElementTypeCode) && binaryArray._lowerBoundA[0] == 0)
            {
                flag = true;
                ReadArrayAsBytes(pr);
            }
            break;
        case BinaryArrayTypeEnum.Jagged:
        case BinaryArrayTypeEnum.JaggedOffset:
            op._numItems = binaryArray._lengthA[0];
            pr._arrayTypeEnum = InternalArrayTypeE.Jagged;
            break;
        case BinaryArrayTypeEnum.Rectangular:
        case BinaryArrayTypeEnum.RectangularOffset:
        {
            int num = 1;
            for (int i = 0; i < binaryArray._rank; i++)
            {
                num *= binaryArray._lengthA[i];
            }
            op._numItems = num;
            pr._arrayTypeEnum = InternalArrayTypeE.Rectangular;
            break;
        }
        default:
            throw new SerializationException(System.SR.Format(System.SR.Serialization_ArrayType, binaryArray._binaryArrayTypeEnum.ToString()));
        }
        if (!flag)
        {
            _stack.Push(op);
        }
        else
        {
            PutOp(op);
        }
        _objectReader.Parse(pr);
        if (flag)
        {
            pr._parseTypeEnum = InternalParseTypeE.ObjectEnd;
            _objectReader.Parse(pr);
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._headerId, System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack, System.Runtime.Serialization.Formatters.Binary.BinaryParser._topId, System.Runtime.Serialization.Formatters.Binary.BinaryParser.AssemIdToAssemblyTable, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.GetOp(), System.Runtime.Serialization.Formatters.Binary.Converter.IsWriteAsByteArray(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.PeekPeek(), System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.PutOp(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArrayAsBytes(), System.SR.Serialization_ArrayType, System.SR.Serialization_AssemblyId, System.SR.Serialization_ObjectTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryParser.SystemAssemblyInfo, and System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.TypeFromInfo().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().