Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadCrossAppDomainMap
ReadCrossAppDomainMap()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadCrossAppDomainMap () inline package
Definition at line 413 of file BinaryParser.cs.
    {
        BinaryCrossAppDomainMap binaryCrossAppDomainMap = new BinaryCrossAppDomainMap();
        binaryCrossAppDomainMap.Read(this);
        object obj = _objectReader.CrossAppDomainArray(binaryCrossAppDomainMap._crossAppDomainArrayIndex);
        if (obj is BinaryObjectWithMap record)
        {
            ReadObjectWithMap(record);
            return;
        }
        if (obj is BinaryObjectWithMapTyped record2)
        {
            ReadObjectWithMapTyped(record2);
            return;
        }
        throw new SerializationException(System.SR.Format(System.SR.Serialization_CrossAppDomainError, "BinaryObjectMap", obj));
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectReader.CrossAppDomainArray(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.obj, System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(), and System.SR.Serialization_CrossAppDomainError.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().