Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadValue
ReadValue()
object System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadValue (InternalPrimitiveTypeE code) inline package
Definition at line 964 of file BinaryParser.cs.
    {
        return code switch
        {
            InternalPrimitiveTypeE.Boolean => ReadBoolean(),
            InternalPrimitiveTypeE.Byte => ReadByte(),
            InternalPrimitiveTypeE.Char => ReadChar(),
            InternalPrimitiveTypeE.Double => ReadDouble(),
            InternalPrimitiveTypeE.Int16 => ReadInt16(),
            InternalPrimitiveTypeE.Int32 => ReadInt32(),
            InternalPrimitiveTypeE.Int64 => ReadInt64(),
            InternalPrimitiveTypeE.SByte => ReadSByte(),
            InternalPrimitiveTypeE.Single => ReadSingle(),
            InternalPrimitiveTypeE.UInt16 => ReadUInt16(),
            InternalPrimitiveTypeE.UInt32 => ReadUInt32(),
            InternalPrimitiveTypeE.UInt64 => ReadUInt64(),
            InternalPrimitiveTypeE.Decimal => ReadDecimal(),
            InternalPrimitiveTypeE.TimeSpan => ReadTimeSpan(),
            InternalPrimitiveTypeE.DateTime => ReadDateTime(),
            _ => throw new SerializationException(System.SR.Format(System.SR.Serialization_TypeCode, code.ToString())),
        };
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadBoolean(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadByte(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadChar(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadDateTime(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadDecimal(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadDouble(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadInt16(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadInt32(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadInt64(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadSByte(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadSingle(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadTimeSpan(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadUInt16(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadUInt32(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadUInt64(), and System.SR.Serialization_TypeCode.