Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveTyped
ReadMemberPrimitiveTyped()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveTyped () inline private
Definition at line 669 of file BinaryParser.cs.
    {
        if (_memberPrimitiveTyped == null)
        {
            _memberPrimitiveTyped = new MemberPrimitiveTyped();
        }
        _memberPrimitiveTyped.Read(this);
        PRs._objectTypeEnum = InternalObjectTypeE.Object;
        ObjectProgress objectProgress = (ObjectProgress)_stack.Peek();
        PRs.Init();
        PRs._varValue = _memberPrimitiveTyped._value;
        PRs._keyDt = Converter.ToComType(_memberPrimitiveTyped._primitiveTypeEnum);
        PRs._dtType = Converter.ToType(_memberPrimitiveTyped._primitiveTypeEnum);
        PRs._dtTypeCode = _memberPrimitiveTyped._primitiveTypeEnum;
        if (objectProgress == null)
        {
            PRs._parseTypeEnum = InternalParseTypeE.Object;
            PRs._name = "System.Variant";
        }
        else
        {
            PRs._parseTypeEnum = InternalParseTypeE.Member;
            PRs._memberValueEnum = InternalMemberValueE.InlineValue;
            switch (objectProgress._objectTypeEnum)
            {
            case InternalObjectTypeE.Object:
                PRs._name = objectProgress._name;
                PRs._memberTypeEnum = InternalMemberTypeE.Field;
                break;
            case InternalObjectTypeE.Array:
                PRs._memberTypeEnum = InternalMemberTypeE.Item;
                break;
            default:
                throw new SerializationException(System.SR.Format(System.SR.Serialization_ObjectTypeEnum, objectProgress._objectTypeEnum.ToString()));
            }
        }
        _objectReader.Parse(PRs);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._memberPrimitiveTyped, System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped._primitiveTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped._value, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.PRs, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Read(), System.SR.Serialization_ObjectTypeEnum, System.Runtime.Serialization.Formatters.Binary.Converter.ToComType(), and System.Runtime.Serialization.Formatters.Binary.Converter.ToType().
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().