Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run
Run()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run () inline package
Definition at line 77 of file BinaryParser.cs.
    {
        try
        {
            bool flag = true;
            ReadBegin();
            ReadSerializationHeaderRecord();
            while (flag)
            {
                BinaryHeaderEnum binaryHeaderEnum = BinaryHeaderEnum.Object;
                switch (_expectedType)
                {
                case BinaryTypeEnum.String:
                case BinaryTypeEnum.Object:
                case BinaryTypeEnum.ObjectUrt:
                case BinaryTypeEnum.ObjectUser:
                case BinaryTypeEnum.ObjectArray:
                case BinaryTypeEnum.StringArray:
                case BinaryTypeEnum.PrimitiveArray:
                {
                    byte b = _dataReader.ReadByte();
                    binaryHeaderEnum = (BinaryHeaderEnum)b;
                    switch (binaryHeaderEnum)
                    {
                    case BinaryHeaderEnum.Assembly:
                    case BinaryHeaderEnum.CrossAppDomainAssembly:
                        ReadAssembly(binaryHeaderEnum);
                        break;
                    case BinaryHeaderEnum.Object:
                        ReadObject();
                        break;
                    case BinaryHeaderEnum.CrossAppDomainMap:
                        ReadCrossAppDomainMap();
                        break;
                    case BinaryHeaderEnum.ObjectWithMap:
                    case BinaryHeaderEnum.ObjectWithMapAssemId:
                        ReadObjectWithMap(binaryHeaderEnum);
                        break;
                    case BinaryHeaderEnum.ObjectWithMapTyped:
                    case BinaryHeaderEnum.ObjectWithMapTypedAssemId:
                        ReadObjectWithMapTyped(binaryHeaderEnum);
                        break;
                    case BinaryHeaderEnum.ObjectString:
                    case BinaryHeaderEnum.CrossAppDomainString:
                        ReadObjectString(binaryHeaderEnum);
                        break;
                    case BinaryHeaderEnum.Array:
                    case BinaryHeaderEnum.ArraySinglePrimitive:
                    case BinaryHeaderEnum.ArraySingleObject:
                    case BinaryHeaderEnum.ArraySingleString:
                        ReadArray(binaryHeaderEnum);
                        break;
                    case BinaryHeaderEnum.MemberPrimitiveTyped:
                        ReadMemberPrimitiveTyped();
                        break;
                    case BinaryHeaderEnum.MemberReference:
                        ReadMemberReference();
                        break;
                    case BinaryHeaderEnum.ObjectNull:
                    case BinaryHeaderEnum.ObjectNullMultiple256:
                    case BinaryHeaderEnum.ObjectNullMultiple:
                        ReadObjectNull(binaryHeaderEnum);
                        break;
                    case BinaryHeaderEnum.MessageEnd:
                        flag = false;
                        ReadMessageEnd();
                        ReadEnd();
                        break;
                    default:
                        throw new SerializationException(System.SR.Format(System.SR.Serialization_BinaryHeader, b));
                    }
                    break;
                }
                case BinaryTypeEnum.Primitive:
                    ReadMemberPrimitiveUnTyped();
                    break;
                default:
                    throw new SerializationException(System.SR.Serialization_TypeExpected);
                }
                if (binaryHeaderEnum == BinaryHeaderEnum.Assembly)
                {
                    continue;
                }
                bool flag2 = false;
                while (!flag2)
                {
                    ObjectProgress objectProgress = (ObjectProgress)_stack.Peek();
                    if (objectProgress == null)
                    {
                        _expectedType = BinaryTypeEnum.ObjectUrt;
                        _expectedTypeInformation = null;
                        flag2 = true;
                        continue;
                    }
                    flag2 = objectProgress.GetNext(out objectProgress._expectedType, out objectProgress._expectedTypeInformation);
                    _expectedType = objectProgress._expectedType;
                    _expectedTypeInformation = objectProgress._expectedTypeInformation;
                    if (!flag2)
                    {
                        PRs.Init();
                        if (objectProgress._memberValueEnum == InternalMemberValueE.Nested)
{
                            PRs._parseTypeEnum = InternalParseTypeE.MemberEnd;
                            PRs._memberTypeEnum = objectProgress._memberTypeEnum;
                            PRs._memberValueEnum = objectProgress._memberValueEnum;
                            _objectReader.Parse(PRs);
                        }
                        else
{
                            PRs._parseTypeEnum = InternalParseTypeE.ObjectEnd;
                            PRs._memberTypeEnum = objectProgress._memberTypeEnum;
                            PRs._memberValueEnum = objectProgress._memberValueEnum;
                            _objectReader.Parse(PRs);
                        }
                        _stack.Pop();
                        PutOp(objectProgress);
                    }
                }
            }
        }
        catch (EndOfStreamException)
        {
            throw new SerializationException(System.SR.Serialization_StreamEnd);
        }
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._dataReader, System.Runtime.Serialization.Formatters.Binary.BinaryParser._expectedType, System.Runtime.Serialization.Formatters.Binary.BinaryParser._expectedTypeInformation, System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.SerStack.Pop(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.PRs, System.Runtime.Serialization.Formatters.Binary.BinaryParser.PutOp(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArray(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadAssembly(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadBegin(), System.IO.BinaryReader.ReadByte(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadCrossAppDomainMap(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadEnd(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveUnTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberReference(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMessageEnd(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObject(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectNull(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectString(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadSerializationHeaderRecord(), System.SR.Serialization_BinaryHeader, System.SR.Serialization_StreamEnd, and System.SR.Serialization_TypeExpected.