Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap
ReadObjectWithMap() [2/2]
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap (BinaryObjectWithMap record) inline private
Definition at line 447 of file BinaryParser.cs.
    {
        BinaryAssemblyInfo binaryAssemblyInfo = null;
        ObjectProgress op = GetOp();
        ParseRecord pr = op._pr;
        _stack.Push(op);
        if (record._binaryHeaderEnum == BinaryHeaderEnum.ObjectWithMapAssemId)
        {
            if (record._assemId < 1)
            {
                throw new SerializationException(System.SR.Format(System.SR.Serialization_Assembly, record._name));
            }
            binaryAssemblyInfo = (BinaryAssemblyInfo)AssemIdToAssemblyTable[record._assemId];
            if (binaryAssemblyInfo == null)
            {
                throw new SerializationException(System.SR.Format(System.SR.Serialization_Assembly, record._assemId + " " + record._name));
            }
        }
        else if (record._binaryHeaderEnum == BinaryHeaderEnum.ObjectWithMap)
        {
            binaryAssemblyInfo = SystemAssemblyInfo;
        }
        Type type = _objectReader.GetType(binaryAssemblyInfo, record._name);
        ObjectMap objectMap = ObjectMap.Create(record._name, type, record._memberNames, _objectReader, record._objectId, binaryAssemblyInfo);
        ObjectMapIdTable[record._objectId] = objectMap;
        op._objectTypeEnum = InternalObjectTypeE.Object;
        op._binaryTypeEnumA = objectMap._binaryTypeEnumA;
        op._typeInformationA = objectMap._typeInformationA;
        op._memberLength = op._binaryTypeEnumA.Length;
        op._memberNames = objectMap._memberNames;
        op._memberTypes = objectMap._memberTypes;
        ObjectProgress objectProgress = (ObjectProgress)_stack.PeekPeek();
        if (objectProgress == null || objectProgress._isInitial)
        {
            op._name = record._name;
            pr._parseTypeEnum = InternalParseTypeE.Object;
            op._memberValueEnum = InternalMemberValueE.Empty;
        }
        else
        {
            pr._parseTypeEnum = InternalParseTypeE.Member;
            pr._memberValueEnum = InternalMemberValueE.Nested;
            op._memberValueEnum = InternalMemberValueE.Nested;
            switch (objectProgress._objectTypeEnum)
            {
            case InternalObjectTypeE.Object:
                pr._name = objectProgress._name;
                pr._memberTypeEnum = InternalMemberTypeE.Field;
                op._memberTypeEnum = InternalMemberTypeE.Field;
                break;
            case InternalObjectTypeE.Array:
                pr._memberTypeEnum = InternalMemberTypeE.Item;
                op._memberTypeEnum = InternalMemberTypeE.Field;
                break;
            default:
                throw new SerializationException(System.SR.Format(System.SR.Serialization_ObjectTypeEnum, objectProgress._objectTypeEnum.ToString()));
            }
        }
        pr._objectTypeEnum = InternalObjectTypeE.Object;
        pr._objectId = _objectReader.GetId(record._objectId);
        pr._objectInfo = objectMap.CreateObjectInfo(ref pr._si, ref pr._memberData);
        if (pr._objectId == _topId)
        {
            pr._objectPositionEnum = InternalObjectPositionE.Top;
        }
        pr._keyDt = record._name;
        pr._dtType = objectMap._objectType;
        pr._dtTypeCode = InternalPrimitiveTypeE.Invalid;
        _objectReader.Parse(pr);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack, System.Runtime.Serialization.Formatters.Binary.BinaryParser._topId, System.Runtime.Serialization.Formatters.Binary.BinaryParser.AssemIdToAssemblyTable, System.Runtime.Serialization.Formatters.Binary.ObjectMap.Create(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.GetOp(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ObjectMapIdTable, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.PeekPeek(), System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), System.SR.Serialization_Assembly, System.SR.Serialization_ObjectTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryParser.SystemAssemblyInfo, and System.type.