Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack
_stack
SerStack System.Runtime.Serialization.Formatters.Binary.BinaryParser._stack = new SerStack("ObjectProgressStack") package
Definition at line 25 of file BinaryParser.cs.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArray(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveUnTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberReference(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMessageEnd(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObject(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectNull(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectString(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMap(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(), and System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().