Terraria: System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadAssembly
ReadAssembly()
void System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadAssembly (BinaryHeaderEnum binaryHeaderEnum) inline package
Definition at line 329 of file BinaryParser.cs.
    {
        BinaryAssembly binaryAssembly = new BinaryAssembly();
        if (binaryHeaderEnum == BinaryHeaderEnum.CrossAppDomainAssembly)
        {
            BinaryCrossAppDomainAssembly binaryCrossAppDomainAssembly = new BinaryCrossAppDomainAssembly();
            binaryCrossAppDomainAssembly.Read(this);
            binaryAssembly._assemId = binaryCrossAppDomainAssembly._assemId;
            binaryAssembly._assemblyString = _objectReader.CrossAppDomainArray(binaryCrossAppDomainAssembly._assemblyIndex) as string;
            if (binaryAssembly._assemblyString == null)
            {
                throw new SerializationException(System.SR.Format(System.SR.Serialization_CrossAppDomainError, "String", binaryCrossAppDomainAssembly._assemblyIndex));
            }
        }
        else
        {
            binaryAssembly.Read(this);
        }
        AssemIdToAssemblyTable[binaryAssembly._assemId] = new BinaryAssemblyInfo(binaryAssembly._assemblyString);
    }
References System.Runtime.Serialization.Formatters.Binary.BinaryParser._objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryParser.AssemIdToAssemblyTable, System.Runtime.Serialization.Formatters.Binary.ObjectReader.CrossAppDomainArray(), System.Runtime.Serialization.Dictionary, System.SR.Format(), and System.SR.Serialization_CrossAppDomainError.
Referenced by System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().