Terraria: System.Data.NewDiffgramGen.Save
Save() [2/2]
void System.Data.NewDiffgramGen.Save (XmlWriter xmlw, DataTable table) inline package
Definition at line 108 of file NewDiffgramGen.cs.
    {
        _xmlw = DataTextWriter.CreateWriter(xmlw);
        _xmlw.WriteStartElement("diffgr", "diffgram", "urn:schemas-microsoft-com:xml-diffgram-v1");
        _xmlw.WriteAttributeString("xmlns", "msdata", null, "urn:schemas-microsoft-com:xml-msdata");
        if (!EmptyData())
        {
            if (table != null)
            {
                new XmlDataTreeWriter(table, _writeHierarchy).SaveDiffgramData(_xmlw, _rowsOrder);
            }
            else
            {
                new XmlDataTreeWriter(_ds).SaveDiffgramData(_xmlw, _rowsOrder);
            }
            if (table == null)
            {
                for (int i = 0; i < _ds.Tables.Count; i++)
                {
                    GenerateTable(_ds.Tables[i]);
                }
            }
            else
            {
                for (int j = 0; j < _tables.Count; j++)
                {
                    GenerateTable((DataTable)_tables[j]);
                }
            }
            if (_fBefore)
            {
                _xmlw.WriteEndElement();
            }
            if (table == null)
            {
                for (int k = 0; k < _ds.Tables.Count; k++)
                {
                    GenerateTableErrors(_ds.Tables[k]);
                }
            }
            else
            {
                for (int l = 0; l < _tables.Count; l++)
                {
                    GenerateTableErrors((DataTable)_tables[l]);
                }
            }
            if (_fErrors)
            {
                _xmlw.WriteEndElement();
            }
        }
        _xmlw.WriteEndElement();
        _xmlw.Flush();
    }
References System.Data.NewDiffgramGen._ds, System.Data.NewDiffgramGen._fBefore, System.Data.NewDiffgramGen._fErrors, System.Data.NewDiffgramGen._rowsOrder, System.Data.NewDiffgramGen._tables, System.Data.NewDiffgramGen._writeHierarchy, System.Data.NewDiffgramGen._xmlw, System.Data.InternalDataCollectionBase.Count, System.Collections.ArrayList.Count, System.Data.DataTextWriter.CreateWriter(), System.Xml.Dictionary, System.Data.NewDiffgramGen.EmptyData(), System.Xml.XmlWriter.Flush(), System.Data.NewDiffgramGen.GenerateTable(), System.Data.NewDiffgramGen.GenerateTableErrors(), System.Data.XmlDataTreeWriter.SaveDiffgramData(), System.Data.DataSet.Tables, System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteEndElement(), and System.Xml.XmlWriter.WriteStartElement().