Terraria: Recipe.SetupRecipes
SetupRecipes()
static void Recipe.SetupRecipes () inline static
References AddAshWoodFurnitureArmorAndItems(), AddBalloonFurniture(), AddBambooFurniture(), AddCoralFurniture(), AddCustomShimmerResult(), AddLesionFurniture(), AddNebulaFurniture(), AddRecipe(), AddSandstoneFurniture(), AddSolarFurniture(), AddSpiderFurniture(), AddStardustFurniture(), AddVortexFurniture(), anyIronBar, anyPressurePlate, anySand, anyWood, RecipeGroupID.Balloons, RecipeGroupID.Birds, RecipeGroupID.BlizzardBalloons, RecipeGroupID.Bugs, RecipeGroupID.Butterflies, RecipeGroupID.CloudBalloons, RecipeGroupID.Cockatiels, corruption, createItem, CreateRequiredItemQuickLookups(), CreateReversePlatformRecipes(), CreateReverseWallRecipes(), crimson, RecipeGroupID.CritterGuides, currentRecipe, RecipeGroupID.Dragonflies, RecipeGroupID.Ducks, RecipeGroupID.Fireflies, RecipeGroupID.Fruit, RecipeGroup.IconicItemId, RecipeGroupID.Macaws, RecipeGroupID.NatureGuides, needEverythingSeed, needGraveyardBiome, needHoney, needLava, needSnowBiome, needWater, notDecraftable, RecipeGroup.recipeGroups, ReplaceItemUseFlagsWithRecipeGroups(), requiredItem, requiredTile, RequireGroup(), RecipeGroupID.SandstormBalloons, RecipeGroupID.Scorpions, SetCraftingStation(), Item.SetDefaults(), SetIngredients(), SetupRecipeGroups(), RecipeGroupID.Snails, RecipeGroupID.Squirrels, Item.stack, ItemID.Sets.TextureCopyLoad, RecipeGroupID.Turtles, UpdateMaterialFieldForAllRecipes(), ShimmerTransforms.UpdateRecipeSets(), UpdateWhichItemsAreCrafted(), and UpdateWhichItemsAreMaterials().
Referenced by Main.Initialize_AlmostEverything().