Terraria: Recipe.UpdateWhichItemsAreMaterials
UpdateWhichItemsAreMaterials()
static void Recipe.UpdateWhichItemsAreMaterials () inline static
     {
         for (int i = 0; i < ItemID.Count; i++)
         {
             Item item = new Item();
             item.SetDefaults(i, noMatCheck: true);
             item.checkMat();
             ItemID.Sets.IsAMaterial[i] = item.material;
         }
     }
References Item.checkMat(), ItemID.Count, ItemID.Sets.IsAMaterial, Item.material, and Item.SetDefaults().
Referenced by SetupRecipes().