Terraria: Recipe.AddNebulaFurniture
AddNebulaFurniture()
static void Recipe.AddNebulaFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(4231);
         currentRecipe.createItem.stack = 10;
         currentRecipe.SetIngredients(3, 10, 3457, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4235);
         currentRecipe.createItem.stack = 4;
         currentRecipe.SetIngredients(4231, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4187);
         currentRecipe.SetIngredients(4231, 14);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4188);
         currentRecipe.SetIngredients(4231, 15, 225, 5);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4189);
         currentRecipe.SetIngredients(4231, 20, 149, 10);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4190);
         currentRecipe.SetIngredients(4231, 16);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4191);
         currentRecipe.SetIngredients(4231, 5, 8, 3);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4192);
         currentRecipe.SetIngredients(4231, 4, 8, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4193);
         currentRecipe.SetIngredients(4231, 4);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4194);
         currentRecipe.SetIngredients(4231, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4195);
         currentRecipe.SetIngredients(4231, 8, 22, 2);
         currentRecipe.SetCraftingStation(412);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4196);
         currentRecipe.SetIngredients(4231, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(412);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4197);
         currentRecipe.SetIngredients(4231, 6);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4198);
         currentRecipe.SetIngredients(8, 1, 4231, 3);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4199);
         currentRecipe.SetIngredients(4231, 6, 8, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4200);
         currentRecipe.SetIngredients(4231, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4202);
         currentRecipe.SetIngredients(4231, 6, 206, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4203);
         currentRecipe.SetIngredients(4231, 5, 225, 2);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4204);
         currentRecipe.SetIngredients(4231, 8);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4205);
         currentRecipe.SetIngredients(4231, 10);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4207);
         currentRecipe.SetIngredients(4231, 6);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), SetIngredients(), and Item.stack.
Referenced by SetupRecipes().