Terraria: System.Data.NewDiffgramGen.GenerateRow
GenerateRow()
void System.Data.NewDiffgramGen.GenerateRow (DataRow row) inline private
Definition at line 238 of file NewDiffgramGen.cs.
    {
        DataRowState rowState = row.RowState;
        if (rowState == DataRowState.Unchanged || rowState == DataRowState.Added)
        {
            return;
        }
        if (!_fBefore)
        {
            _xmlw.WriteStartElement("diffgr", "before", "urn:schemas-microsoft-com:xml-diffgram-v1");
            _fBefore = true;
        }
        DataTable table = row.Table;
        int count = table.Columns.Count;
        string value = table.TableName + row.rowID.ToString(CultureInfo.InvariantCulture);
        string text = null;
        if (rowState == DataRowState.Deleted && row.Table.NestedParentRelations.Length != 0)
        {
            DataRow nestedParentRow = row.GetNestedParentRow(DataRowVersion.Original);
            if (nestedParentRow != null)
            {
                text = nestedParentRow.Table.TableName + nestedParentRow.rowID.ToString(CultureInfo.InvariantCulture);
            }
        }
        string prefix = ((table.Namespace.Length != 0) ? table.Prefix : string.Empty);
        _xmlw.WriteStartElement(prefix, row.Table.EncodedTableName, row.Table.Namespace);
        _xmlw.WriteAttributeString("diffgr", "id", "urn:schemas-microsoft-com:xml-diffgram-v1", value);
        if (rowState == DataRowState.Deleted && XmlDataTreeWriter.RowHasErrors(row))
        {
            _xmlw.WriteAttributeString("diffgr", "hasErrors", "urn:schemas-microsoft-com:xml-diffgram-v1", "true");
        }
        if (text != null)
        {
            _xmlw.WriteAttributeString("diffgr", "parentId", "urn:schemas-microsoft-com:xml-diffgram-v1", text);
        }
        _xmlw.WriteAttributeString("msdata", "rowOrder", "urn:schemas-microsoft-com:xml-msdata", _rowsOrder[row].ToString());
        for (int i = 0; i < count; i++)
        {
            if (row.Table.Columns[i].ColumnMapping == MappingType.Attribute || row.Table.Columns[i].ColumnMapping == MappingType.Hidden)
            {
                GenerateColumn(row, row.Table.Columns[i], DataRowVersion.Original);
            }
        }
        for (int j = 0; j < count; j++)
        {
            if (row.Table.Columns[j].ColumnMapping == MappingType.Element || row.Table.Columns[j].ColumnMapping == MappingType.SimpleContent)
            {
                GenerateColumn(row, row.Table.Columns[j], DataRowVersion.Original);
            }
        }
        _xmlw.WriteEndElement();
    }
References System.Data.NewDiffgramGen._fBefore, System.Data.NewDiffgramGen._rowsOrder, System.Data.NewDiffgramGen._xmlw, System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.count, System.Xml.Dictionary, System.Data.NewDiffgramGen.GenerateColumn(), System.Data.DataRow.GetNestedParentRow(), System.Globalization.CultureInfo.InvariantCulture, System.Data.DataTable.Prefix, System.prefix, System.Data.XmlDataTreeWriter.RowHasErrors(), System.Data.DataRow.rowID, System.text, System.ToString, System.value, System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteEndElement(), and System.Xml.XmlWriter.WriteStartElement().
Referenced by System.Data.NewDiffgramGen.GenerateTable().