Terraria: Recipe.AddAshWoodFurnitureArmorAndItems
AddAshWoodFurnitureArmorAndItems()
static void Recipe.AddAshWoodFurnitureArmorAndItems () inline static private
     {
         currentRecipe.createItem.SetDefaults(5279);
         currentRecipe.SetIngredients(5215, 20);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5280);
         currentRecipe.SetIngredients(5215, 30);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5281);
         currentRecipe.SetIngredients(5215, 25);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5284);
         currentRecipe.SetIngredients(5215, 7);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5283);
         currentRecipe.SetIngredients(5215, 8);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5282);
         currentRecipe.SetIngredients(5215, 10);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5190);
         currentRecipe.SetIngredients(5215, 14);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5191);
         currentRecipe.SetIngredients(5215, 15, 225, 5);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5192);
         currentRecipe.SetIngredients(5215, 20, 149, 10);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5193);
         currentRecipe.SetIngredients(5215, 16);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5194);
         currentRecipe.SetIngredients(5215, 5, 8, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5195);
         currentRecipe.SetIngredients(5215, 4, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5196);
         currentRecipe.SetIngredients(5215, 4);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5197);
         currentRecipe.SetIngredients(5215, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(16);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5198);
         currentRecipe.SetIngredients(5215, 8, 22, 2);
         currentRecipe.SetCraftingStation(18);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5199);
         currentRecipe.SetIngredients(5215, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(106);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5200);
         currentRecipe.SetIngredients(5215, 6);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5201);
         currentRecipe.SetIngredients(8, 1, 5215, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5202);
         currentRecipe.SetIngredients(5215, 6, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5203);
         currentRecipe.SetIngredients(5215, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5205);
         currentRecipe.SetIngredients(5215, 6, 206, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5206);
         currentRecipe.SetIngredients(5215, 5, 225, 2);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5207);
         currentRecipe.SetIngredients(5215, 8);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5208);
         currentRecipe.SetIngredients(5215, 10);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5210);
         currentRecipe.SetIngredients(5215, 6);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), and SetIngredients().
Referenced by SetupRecipes().