Terraria: Recipe.SetIngredients
SetIngredients()
void Recipe.SetIngredients (params int[] ingredients) inline
     {
         if (ingredients.Length == 1)
         {
             ingredients = new int[2]
             {
                 ingredients[0],
                 1
             };
         }
         if (ingredients.Length % 2 != 0)
         {
             throw new Exception("Bad ingredients amount");
         }
         for (int i = 0; i < ingredients.Length; i += 2)
         {
             int num = i / 2;
             requiredItem[num].SetDefaults(ingredients[i]);
             requiredItem[num].stack = ingredients[i + 1];
         }
     }
References requiredItem, Item.SetDefaults(), and Item.stack.
Referenced by AddAshWoodFurnitureArmorAndItems(), AddBalloonFurniture(), AddBambooFurniture(), AddCoralFurniture(), AddLesionFurniture(), AddNebulaFurniture(), AddSandstoneFurniture(), AddSolarFurniture(), AddSpiderFurniture(), AddStardustFurniture(), AddVortexFurniture(), and SetupRecipes().