Terraria: Recipe.AddVortexFurniture
AddVortexFurniture()
static void Recipe.AddVortexFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(4230);
         currentRecipe.createItem.stack = 10;
         currentRecipe.SetIngredients(3, 10, 3456, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4234);
         currentRecipe.createItem.stack = 4;
         currentRecipe.SetIngredients(4230, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4166);
         currentRecipe.SetIngredients(4230, 14);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4167);
         currentRecipe.SetIngredients(4230, 15, 225, 5);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4168);
         currentRecipe.SetIngredients(4230, 20, 149, 10);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4169);
         currentRecipe.SetIngredients(4230, 16);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4170);
         currentRecipe.SetIngredients(4230, 5, 8, 3);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4171);
         currentRecipe.SetIngredients(4230, 4, 8, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4172);
         currentRecipe.SetIngredients(4230, 4);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4173);
         currentRecipe.SetIngredients(4230, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4174);
         currentRecipe.SetIngredients(4230, 8, 22, 2);
         currentRecipe.SetCraftingStation(412);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4175);
         currentRecipe.SetIngredients(4230, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(412);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4176);
         currentRecipe.SetIngredients(4230, 6);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4177);
         currentRecipe.SetIngredients(8, 1, 4230, 3);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4178);
         currentRecipe.SetIngredients(4230, 6, 8, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4179);
         currentRecipe.SetIngredients(4230, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4181);
         currentRecipe.SetIngredients(4230, 6, 206, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4182);
         currentRecipe.SetIngredients(4230, 5, 225, 2);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4183);
         currentRecipe.SetIngredients(4230, 8);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4184);
         currentRecipe.SetIngredients(4230, 10);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4186);
         currentRecipe.SetIngredients(4230, 6);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), SetIngredients(), and Item.stack.
Referenced by SetupRecipes().