Terraria: Recipe.CollectItemsToCraftWithFrom
CollectItemsToCraftWithFrom()
static void Recipe.CollectItemsToCraftWithFrom (Player player) inline static private
     {
         _ownedItems.Clear();
         CollectItems(player.inventory, 58);
         if (player.useVoidBag() && player.chest != -5)
         {
             CollectItems(player.bank4.item, 40);
         }
         if (player.chest != -1)
         {
             Item[] currentInventory = null;
             if (player.chest > -1)
             {
                 currentInventory = Main.chest[player.chest].item;
             }
             else if (player.chest == -2)
             {
                 currentInventory = player.bank.item;
             }
             else if (player.chest == -3)
             {
                 currentInventory = player.bank2.item;
             }
             else if (player.chest == -4)
             {
                 currentInventory = player.bank3.item;
             }
             else if (player.chest == -5)
             {
                 currentInventory = player.bank4.item;
             }
             CollectItems(currentInventory, 40);
         }
         AddFakeCountsForItemGroups();
     }
References _ownedItems, AddFakeCountsForItemGroups(), Player.bank, Player.bank2, Player.bank3, Player.bank4, Main.chest, Player.chest, CollectItems(), Player.inventory, Chest.item, and Player.useVoidBag().
Referenced by FindRecipes().