Terraria: Recipe.AddSandstoneFurniture
AddSandstoneFurniture()
static void Recipe.AddSandstoneFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(4720);
         currentRecipe.createItem.stack = 2;
         currentRecipe.SetIngredients(4051, 1);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4298);
         currentRecipe.SetIngredients(4051, 14);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4299);
         currentRecipe.SetIngredients(4051, 15, 225, 5);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4300);
         currentRecipe.SetIngredients(4051, 20, 149, 10);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4301);
         currentRecipe.SetIngredients(4051, 16);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4302);
         currentRecipe.SetIngredients(4051, 5, 8, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4303);
         currentRecipe.SetIngredients(4051, 4, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4304);
         currentRecipe.SetIngredients(4051, 4);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4305);
         currentRecipe.SetIngredients(4051, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(16);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4267);
         currentRecipe.SetIngredients(4051, 8, 22, 2);
         currentRecipe.SetCraftingStation(18);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4306);
         currentRecipe.SetIngredients(4051, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(106);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4307);
         currentRecipe.SetIngredients(4051, 6);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4308);
         currentRecipe.SetIngredients(8, 1, 4051, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4309);
         currentRecipe.SetIngredients(4051, 6, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4310);
         currentRecipe.SetIngredients(4051, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4312);
         currentRecipe.SetIngredients(4051, 6, 206, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4313);
         currentRecipe.SetIngredients(4051, 5, 225, 2);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4314);
         currentRecipe.SetIngredients(4051, 8);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4315);
         currentRecipe.SetIngredients(4051, 10);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4316);
         currentRecipe.SetIngredients(4051, 6);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), SetIngredients(), and Item.stack.
Referenced by SetupRecipes().