Terraria: Recipe.AddLesionFurniture
AddLesionFurniture()
static void Recipe.AddLesionFurniture () inline static private
     {
         int num = 3955;
         currentRecipe.createItem.SetDefaults(3955);
         currentRecipe.SetIngredients(61, 2);
         currentRecipe.SetCraftingStation(218);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3975);
         currentRecipe.SetIngredients(num, 10);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3956);
         currentRecipe.createItem.stack = 4;
         currentRecipe.SetIngredients(3955, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3967);
         currentRecipe.SetIngredients(num, 6);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3963);
         currentRecipe.SetIngredients(num, 4);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3965);
         Recipe recipe = currentRecipe;
         int[] obj = new int[4] { 0, 8, 22, 2 };
         obj[0] = num;
         recipe.SetIngredients(obj);
         currentRecipe.anyWood = true;
         currentRecipe.anyIronBar = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3974);
         currentRecipe.SetIngredients(num, 8);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3972);
         Recipe recipe2 = currentRecipe;
         int[] obj2 = new int[4] { 0, 6, 206, 1 };
         obj2[0] = num;
         recipe2.SetIngredients(obj2);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3970);
         Recipe recipe3 = currentRecipe;
         int[] obj3 = new int[4] { 0, 6, 8, 1 };
         obj3[0] = num;
         recipe3.SetIngredients(obj3);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3962);
         Recipe recipe4 = currentRecipe;
         int[] obj4 = new int[4] { 0, 4, 8, 1 };
         obj4[0] = num;
         recipe4.SetIngredients(obj4);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3969);
         Recipe recipe5 = currentRecipe;
         int[] obj5 = new int[4] { 0, 3, 8, 1 };
         obj5[0] = num;
         recipe5.SetIngredients(obj5);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3961);
         Recipe recipe6 = currentRecipe;
         int[] obj6 = new int[4] { 0, 5, 8, 3 };
         obj6[0] = num;
         recipe6.SetIngredients(obj6);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3959);
         Recipe recipe7 = currentRecipe;
         int[] obj7 = new int[4] { 0, 15, 225, 5 };
         obj7[0] = num;
         recipe7.SetIngredients(obj7);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3968);
         currentRecipe.SetIngredients(num, 16);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3960);
         Recipe recipe8 = currentRecipe;
         int[] obj8 = new int[4] { 0, 20, 149, 10 };
         obj8[0] = num;
         recipe8.SetIngredients(obj8);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3966);
         Recipe recipe9 = currentRecipe;
         int[] obj9 = new int[6] { 22, 3, 170, 6, 0, 10 };
         obj9[4] = num;
         recipe9.SetIngredients(obj9);
         currentRecipe.anyWood = true;
         currentRecipe.anyIronBar = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3973);
         Recipe recipe10 = currentRecipe;
         int[] obj10 = new int[4] { 0, 5, 225, 2 };
         obj10[0] = num;
         recipe10.SetIngredients(obj10);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3971);
         Recipe recipe11 = currentRecipe;
         int[] obj11 = new int[6] { 154, 4, 0, 15, 149, 1 };
         obj11[2] = num;
         recipe11.SetIngredients(obj11);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3958);
         currentRecipe.SetIngredients(num, 14);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3964);
         Recipe recipe12 = currentRecipe;
         int[] obj12 = new int[6] { 0, 4, 8, 4, 85, 1 };
         obj12[0] = num;
         recipe12.SetIngredients(obj12);
         currentRecipe.anyWood = true;
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4126);
         currentRecipe.SetIngredients(3955, 6);
         currentRecipe.SetCraftingStation(499);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, anyWood, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), SetIngredients(), and Item.stack.
Referenced by SetupRecipes().