Terraria: System.Data.NewDiffgramGen.GenerateTableErrors
GenerateTableErrors()
void System.Data.NewDiffgramGen.GenerateTableErrors (DataTable table) inline private
Definition at line 177 of file NewDiffgramGen.cs.
    {
        int count = table.Rows.Count;
        int count2 = table.Columns.Count;
        if (count <= 0)
        {
            return;
        }
        for (int i = 0; i < count; i++)
        {
            bool flag = false;
            DataRow dataRow = table.Rows[i];
            string prefix = ((table.Namespace.Length != 0) ? table.Prefix : string.Empty);
            if (dataRow.HasErrors && dataRow.RowError.Length > 0)
            {
                if (!_fErrors)
                {
                    _xmlw.WriteStartElement("diffgr", "errors", "urn:schemas-microsoft-com:xml-diffgram-v1");
                    _fErrors = true;
                }
                _xmlw.WriteStartElement(prefix, dataRow.Table.EncodedTableName, dataRow.Table.Namespace);
                _xmlw.WriteAttributeString("diffgr", "id", "urn:schemas-microsoft-com:xml-diffgram-v1", dataRow.Table.TableName + dataRow.rowID.ToString(CultureInfo.InvariantCulture));
                _xmlw.WriteAttributeString("diffgr", "Error", "urn:schemas-microsoft-com:xml-diffgram-v1", dataRow.RowError);
                flag = true;
            }
            if (count2 <= 0)
            {
                continue;
            }
            for (int j = 0; j < count2; j++)
            {
                DataColumn dataColumn = table.Columns[j];
                string columnError = dataRow.GetColumnError(dataColumn);
                string prefix2 = ((dataColumn.Namespace.Length != 0) ? dataColumn.Prefix : string.Empty);
                if (columnError == null || columnError.Length == 0)
                {
                    continue;
                }
                if (!flag)
                {
                    if (!_fErrors)
                    {
                        _xmlw.WriteStartElement("diffgr", "errors", "urn:schemas-microsoft-com:xml-diffgram-v1");
                        _fErrors = true;
                    }
                    _xmlw.WriteStartElement(prefix, dataRow.Table.EncodedTableName, dataRow.Table.Namespace);
                    _xmlw.WriteAttributeString("diffgr", "id", "urn:schemas-microsoft-com:xml-diffgram-v1", dataRow.Table.TableName + dataRow.rowID.ToString(CultureInfo.InvariantCulture));
                    flag = true;
                }
                _xmlw.WriteStartElement(prefix2, dataColumn.EncodedColumnName, dataColumn.Namespace);
                _xmlw.WriteAttributeString("diffgr", "Error", "urn:schemas-microsoft-com:xml-diffgram-v1", columnError);
                _xmlw.WriteEndElement();
            }
            if (flag)
            {
                _xmlw.WriteEndElement();
            }
        }
    }
References System.Data.NewDiffgramGen._fErrors, System.Data.NewDiffgramGen._xmlw, System.Data.DataTable.Columns, System.Data.DataRowCollection.Count, System.Data.InternalDataCollectionBase.Count, System.count, System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Data.DataTable.Prefix, System.prefix, System.Data.DataTable.Rows, System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteEndElement(), and System.Xml.XmlWriter.WriteStartElement().
Referenced by System.Data.NewDiffgramGen.Save().