Terraria: Recipe.AddBambooFurniture
AddBambooFurniture()
static void Recipe.AddBambooFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(4566);
         currentRecipe.SetIngredients(4564, 14);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4567);
         currentRecipe.SetIngredients(4564, 15, 225, 5);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4568);
         currentRecipe.SetIngredients(4564, 20, 149, 10);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4569);
         currentRecipe.SetIngredients(4564, 16);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4570);
         currentRecipe.SetIngredients(4564, 5, 8, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4571);
         currentRecipe.SetIngredients(4564, 4, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4572);
         currentRecipe.SetIngredients(4564, 4);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4573);
         currentRecipe.SetIngredients(4564, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(16);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4574);
         currentRecipe.SetIngredients(4564, 8, 22, 2);
         currentRecipe.SetCraftingStation(18);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4575);
         currentRecipe.SetIngredients(4564, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(106);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4576);
         currentRecipe.SetIngredients(4564, 6);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4577);
         currentRecipe.SetIngredients(8, 1, 4564, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4578);
         currentRecipe.SetIngredients(4564, 6, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4579);
         currentRecipe.SetIngredients(4564, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4581);
         currentRecipe.SetIngredients(4564, 6, 206, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4582);
         currentRecipe.SetIngredients(4564, 5, 225, 2);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4583);
         currentRecipe.SetIngredients(4564, 8);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4584);
         currentRecipe.SetIngredients(4564, 10);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4586);
         currentRecipe.SetIngredients(4564, 6);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), and SetIngredients().
Referenced by SetupRecipes().