Terraria: Recipe.useFragment
useFragment()
bool Recipe.useFragment (int invType, int reqType) inline
     {
         if (reqType != 3458 && reqType != 3456 && reqType != 3457 && reqType != 3459)
         {
             return false;
         }
         if (anyFragment && (invType == 3458 || invType == 3456 || invType == 3457 || invType == 3459))
         {
             return true;
         }
         return false;
     }
References anyFragment.
Referenced by CollectedEnoughItemsToCraftRecipeOld(), CollectGuideRecipes(), and Create().