Terraria: Recipe.AddCoralFurniture
AddCoralFurniture()
static void Recipe.AddCoralFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(5148);
         currentRecipe.SetIngredients(5306, 14);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5149);
         currentRecipe.SetIngredients(5306, 15, 225, 5);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5150);
         currentRecipe.SetIngredients(5306, 20, 149, 10);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5151);
         currentRecipe.SetIngredients(5306, 16);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5152);
         currentRecipe.SetIngredients(5306, 5, 8, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5153);
         currentRecipe.SetIngredients(5306, 4, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5154);
         currentRecipe.SetIngredients(5306, 4);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5155);
         currentRecipe.SetIngredients(5306, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(16);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5156);
         currentRecipe.SetIngredients(5306, 8, 22, 2);
         currentRecipe.SetCraftingStation(18);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5157);
         currentRecipe.SetIngredients(5306, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(106);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5158);
         currentRecipe.SetIngredients(5306, 6);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5159);
         currentRecipe.SetIngredients(8, 1, 5306, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5160);
         currentRecipe.SetIngredients(5306, 6, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5161);
         currentRecipe.SetIngredients(5306, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5163);
         currentRecipe.SetIngredients(5306, 6, 206, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5164);
         currentRecipe.SetIngredients(5306, 5, 225, 2);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5165);
         currentRecipe.SetIngredients(5306, 8);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5166);
         currentRecipe.SetIngredients(5306, 10);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5168);
         currentRecipe.SetIngredients(5306, 6);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), and SetIngredients().
Referenced by SetupRecipes().