Terraria: Recipe.CollectedEnoughItemsToCraftRecipeOld
CollectedEnoughItemsToCraftRecipeOld()
static bool Recipe.CollectedEnoughItemsToCraftRecipeOld (Recipe tempRec) inline static
     {
         for (int i = 0; i < maxRequirements; i++)
         {
             Item item = tempRec.requiredItem[i];
             if (item.type == 0)
             {
                 break;
             }
             int num = item.stack;
             bool flag = false;
             foreach (int key in _ownedItems.Keys)
             {
                 if (tempRec.useWood(key, item.type) || tempRec.useSand(key, item.type) || tempRec.useIronBar(key, item.type) || tempRec.useFragment(key, item.type) || tempRec.usePressurePlate(key, item.type) || tempRec.AcceptedByItemGroups(key, item.type))
                 {
                     num -= _ownedItems[key];
                     flag = true;
                 }
             }
             if (!flag && _ownedItems.ContainsKey(item.netID))
             {
                 num -= _ownedItems[item.netID];
             }
             if (num > 0)
             {
                 return false;
             }
         }
         return true;
     }
References _ownedItems, AcceptedByItemGroups(), maxRequirements, requiredItem, Item.stack, Item.type, useFragment(), useIronBar(), usePressurePlate(), useSand(), and useWood().