Terraria: Recipe.AddSolarFurniture
AddSolarFurniture()
static void Recipe.AddSolarFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(4229);
         currentRecipe.createItem.stack = 10;
         currentRecipe.SetIngredients(3, 10, 3458, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4233);
         currentRecipe.createItem.stack = 4;
         currentRecipe.SetIngredients(4229, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4145);
         currentRecipe.SetIngredients(4229, 14);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4146);
         currentRecipe.SetIngredients(4229, 15, 225, 5);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4147);
         currentRecipe.SetIngredients(4229, 20, 149, 10);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4148);
         currentRecipe.SetIngredients(4229, 16);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4149);
         currentRecipe.SetIngredients(4229, 5, 8, 3);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4150);
         currentRecipe.SetIngredients(4229, 4, 8, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4151);
         currentRecipe.SetIngredients(4229, 4);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4152);
         currentRecipe.SetIngredients(4229, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4153);
         currentRecipe.SetIngredients(4229, 8, 22, 2);
         currentRecipe.SetCraftingStation(412);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4154);
         currentRecipe.SetIngredients(4229, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(412);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4155);
         currentRecipe.SetIngredients(4229, 6);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4156);
         currentRecipe.SetIngredients(8, 1, 4229, 3);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4157);
         currentRecipe.SetIngredients(4229, 6, 8, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4158);
         currentRecipe.SetIngredients(4229, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4160);
         currentRecipe.SetIngredients(4229, 6, 206, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4161);
         currentRecipe.SetIngredients(4229, 5, 225, 2);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4162);
         currentRecipe.SetIngredients(4229, 8);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4163);
         currentRecipe.SetIngredients(4229, 10);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4165);
         currentRecipe.SetIngredients(4229, 6);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), SetIngredients(), and Item.stack.
Referenced by SetupRecipes().