Terraria: Recipe.usePressurePlate
usePressurePlate()
bool Recipe.usePressurePlate (int invType, int reqType) inline
     {
         if (!anyPressurePlate)
         {
             return false;
         }
         switch (reqType)
         {
         default:
             return false;
         case 529:
         case 541:
         case 542:
         case 543:
         case 852:
         case 853:
         case 1151:
         case 4261:
             switch (invType)
             {
             default:
                 return false;
             case 529:
             case 541:
             case 542:
             case 543:
             case 852:
             case 853:
             case 1151:
             case 4261:
                 return true;
             }
         }
     }
References anyPressurePlate.
Referenced by CollectedEnoughItemsToCraftRecipeOld(), CollectGuideRecipes(), and Create().