Terraria: System.Data.NewDiffgramGen.GenerateColumn
GenerateColumn()
void System.Data.NewDiffgramGen.GenerateColumn (DataRow row, DataColumn col, DataRowVersion version) inline private
Definition at line 292 of file NewDiffgramGen.cs.
    {
        string text = null;
        text = col.GetColumnValueAsString(row, version);
        if (text == null)
        {
            if (col.ColumnMapping == MappingType.SimpleContent)
            {
                _xmlw.WriteAttributeString("xsi", "nil", "http://www.w3.org/2001/XMLSchema-instance", "true");
            }
            return;
        }
        string prefix = ((col.Namespace.Length != 0) ? col.Prefix : string.Empty);
        switch (col.ColumnMapping)
        {
        case MappingType.Attribute:
            _xmlw.WriteAttributeString(prefix, col.EncodedColumnName, col.Namespace, text);
            break;
        case MappingType.Hidden:
            _xmlw.WriteAttributeString("msdata", "hidden" + col.EncodedColumnName, "urn:schemas-microsoft-com:xml-msdata", text);
            break;
        case MappingType.SimpleContent:
            _xmlw.WriteString(text);
            break;
        case MappingType.Element:
        {
            bool flag = true;
            object obj = row[col, version];
            if (!col.IsCustomType || !col.IsValueCustomTypeInstance(obj) || typeof(IXmlSerializable).IsAssignableFrom(obj.GetType()))
            {
                _xmlw.WriteStartElement(prefix, col.EncodedColumnName, col.Namespace);
                flag = false;
            }
            Type type = obj.GetType();
            if (!col.IsCustomType)
            {
                if ((type == typeof(char) || type == typeof(string)) && XmlDataTreeWriter.PreserveSpace(text))
                {
                    _xmlw.WriteAttributeString("xml", "space", "http://www.w3.org/XML/1998/namespace", "preserve");
                }
                _xmlw.WriteString(text);
            }
            else if (obj != DBNull.Value && (!col.ImplementsINullable || !DataStorage.IsObjectSqlNull(obj)))
            {
                if (col.IsValueCustomTypeInstance(obj))
                {
                    if (!flag && obj.GetType() != col.DataType)
                    {
                        _xmlw.WriteAttributeString("msdata", "InstanceType", "urn:schemas-microsoft-com:xml-msdata", DataStorage.GetQualifiedName(type));
                    }
                    if (!flag)
                    {
                        col.ConvertObjectToXml(obj, _xmlw, null);
                    }
                    else
                    {
                        if (obj.GetType() != col.DataType)
{
                            throw ExceptionBuilder.PolymorphismNotSupported(type.AssemblyQualifiedName);
                        }
                        XmlRootAttribute xmlRootAttribute = new XmlRootAttribute(col.EncodedColumnName);
                        xmlRootAttribute.Namespace = col.Namespace;
                        col.ConvertObjectToXml(obj, _xmlw, xmlRootAttribute);
                    }
                }
                else
                {
                    if (type == typeof(Type) || type == typeof(Guid) || type == typeof(char) || DataStorage.IsSqlType(type))
                    {
                        _xmlw.WriteAttributeString("msdata", "InstanceType", "urn:schemas-microsoft-com:xml-msdata", type.FullName);
                    }
                    else if (obj is Type)
                    {
                        _xmlw.WriteAttributeString("msdata", "InstanceType", "urn:schemas-microsoft-com:xml-msdata", "Type");
                    }
                    else
                    {
                        string value = "xs:" + XmlTreeGen.XmlDataTypeName(type);
                        _xmlw.WriteAttributeString("xsi", "type", "http://www.w3.org/2001/XMLSchema-instance", value);
                        _xmlw.WriteAttributeString("xs", "xmlns", "http://www.w3.org/2001/XMLSchema", value);
                    }
                    if (!DataStorage.IsSqlType(type))
                    {
                        _xmlw.WriteString(col.ConvertObjectToXml(obj));
                    }
                    else
                    {
                        col.ConvertObjectToXml(obj, _xmlw, null);
                    }
                }
            }
            if (!flag)
            {
                _xmlw.WriteEndElement();
            }
            break;
        }
        }
    }
References System.Data.NewDiffgramGen._xmlw, System.Xml.Dictionary, System.Data.Common.DataStorage.GetQualifiedName(), System.Type.GetType(), System.Data.Common.DataStorage.IsObjectSqlNull(), System.Data.Common.DataStorage.IsSqlType(), System.obj, System.Data.ExceptionBuilder.PolymorphismNotSupported(), System.prefix, System.Data.XmlDataTreeWriter.PreserveSpace(), System.text, System.type, System.DBNull.Value, System.value, System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteStartElement(), System.Xml.XmlWriter.WriteString(), and System.Data.XmlTreeGen.XmlDataTypeName().
Referenced by System.Data.NewDiffgramGen.GenerateRow().