Terraria: Recipe.AddStardustFurniture
AddStardustFurniture()
static void Recipe.AddStardustFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(4232);
         currentRecipe.createItem.stack = 10;
         currentRecipe.SetIngredients(3, 10, 3459, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4236);
         currentRecipe.createItem.stack = 4;
         currentRecipe.SetIngredients(4232, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4208);
         currentRecipe.SetIngredients(4232, 14);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4209);
         currentRecipe.SetIngredients(4232, 15, 225, 5);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4210);
         currentRecipe.SetIngredients(4232, 20, 149, 10);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4211);
         currentRecipe.SetIngredients(4232, 16);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4212);
         currentRecipe.SetIngredients(4232, 5, 8, 3);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4213);
         currentRecipe.SetIngredients(4232, 4, 8, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4214);
         currentRecipe.SetIngredients(4232, 4);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4215);
         currentRecipe.SetIngredients(4232, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4216);
         currentRecipe.SetIngredients(4232, 8, 22, 2);
         currentRecipe.SetCraftingStation(412);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4217);
         currentRecipe.SetIngredients(4232, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(412);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4218);
         currentRecipe.SetIngredients(4232, 6);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4219);
         currentRecipe.SetIngredients(8, 1, 4232, 3);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4220);
         currentRecipe.SetIngredients(4232, 6, 8, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4221);
         currentRecipe.SetIngredients(4232, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4223);
         currentRecipe.SetIngredients(4232, 6, 206, 1);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4224);
         currentRecipe.SetIngredients(4232, 5, 225, 2);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4225);
         currentRecipe.SetIngredients(4232, 8);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4226);
         currentRecipe.SetIngredients(4232, 10);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4228);
         currentRecipe.SetIngredients(4232, 6);
         currentRecipe.SetCraftingStation(412);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), SetIngredients(), and Item.stack.
Referenced by SetupRecipes().