Terraria: System.Reflection.Metadata.Ecma335.BlobHeap.GetMemoryBlock
GetMemoryBlock()
MemoryBlock System.Reflection.Metadata.Ecma335.BlobHeap.GetMemoryBlock (BlobHandle handle) inline package
Definition at line 75 of file BlobHeap.cs.
    {
        if (handle.IsVirtual)
        {
            return GetVirtualHandleMemoryBlock(handle);
        }
        Block.PeekHeapValueOffsetAndSize(handle.GetHeapOffset(), out var offset, out var size);
        return Block.GetMemoryBlockAt(offset, size);
    }
References System.Reflection.Metadata.Ecma335.BlobHeap.Block, System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.BlobHeap.GetVirtualHandleMemoryBlock(), System.handle, System.offset, and System.Reflection.Internal.MemoryBlock.PeekHeapValueOffsetAndSize().
Referenced by System.Reflection.Metadata.Ecma335.BlobHeap.DocumentNameEquals(), System.Reflection.Metadata.Ecma335.BlobHeap.GetBlobReader(), and System.Reflection.Metadata.MetadataReader.ImplementsRedirectedInterface().