Terraria: System.Reflection.Metadata.Ecma335.BlobHeap.DocumentNameEquals
DocumentNameEquals()
bool System.Reflection.Metadata.Ecma335.BlobHeap.DocumentNameEquals (DocumentNameBlobHandle handle, string other, bool ignoreCase) inline package
Definition at line 161 of file BlobHeap.cs.
    {
        BlobReader blobReader = GetBlobReader(handle);
        int num = blobReader.ReadByte();
        if (num > 127)
        {
            return false;
        }
        int ignoreCaseMask = StringUtils.IgnoreCaseMask(ignoreCase);
        int num2 = 0;
        int firstDifferenceIndex;
        for (bool flag = true; blobReader.RemainingBytes > 0; num2 = firstDifferenceIndex, flag = false)
        {
            if (num != 0 && !flag)
            {
                if (num2 == other.Length || !StringUtils.IsEqualAscii(other[num2], num, ignoreCaseMask))
                {
                    return false;
                }
                num2++;
            }
            MemoryBlock memoryBlock = GetMemoryBlock(blobReader.ReadBlobHandle());
            switch (memoryBlock.Utf8NullTerminatedFastCompare(0, other, num2, out firstDifferenceIndex, '\0', ignoreCase))
            {
            case MemoryBlock.FastComparisonResult.Inconclusive:
                return GetDocumentName(handle).Equals(other, ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal);
            default:
                if (firstDifferenceIndex - num2 == memoryBlock.Length)
                {
                    continue;
                }
                break;
            case MemoryBlock.FastComparisonResult.Unequal:
                break;
            }
            return false;
        }
        return num2 == other.Length;
    }
References System.Reflection.Metadata.Ecma335.BlobHeap.GetBlobReader(), System.Reflection.Metadata.Ecma335.BlobHeap.GetDocumentName(), System.Reflection.Metadata.Ecma335.BlobHeap.GetMemoryBlock(), System.handle, System.Reflection.Metadata.StringUtils.IgnoreCaseMask(), System.Reflection.Metadata.StringUtils.IsEqualAscii(), System.Reflection.Internal.MemoryBlock.Length, System.other, System.Reflection.Metadata.BlobReader.ReadBlobHandle(), System.Reflection.Metadata.BlobReader.ReadByte(), and System.Reflection.Internal.MemoryBlock.Utf8NullTerminatedFastCompare().