Terraria: System.Reflection.Metadata.Ecma335.BlobHeap.GetDocumentName
GetDocumentName()
string System.Reflection.Metadata.Ecma335.BlobHeap.GetDocumentName (DocumentNameBlobHandle handle) inline
Definition at line 137 of file BlobHeap.cs.
    {
        BlobReader blobReader = GetBlobReader(handle);
        int num = blobReader.ReadByte();
        if (num > 127)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.InvalidDocumentName, num));
        }
        PooledStringBuilder instance = PooledStringBuilder.GetInstance();
        StringBuilder builder = instance.Builder;
        bool flag = true;
        while (blobReader.RemainingBytes > 0)
        {
            if (num != 0 && !flag)
            {
                builder.Append((char)num);
            }
            BlobReader blobReader2 = GetBlobReader(blobReader.ReadBlobHandle());
            builder.Append(blobReader2.ReadUTF8(blobReader2.Length));
            flag = false;
        }
        return instance.ToStringAndFree();
    }
References System.Text.StringBuilder.Append(), System.Reflection.Internal.PooledStringBuilder.Builder, System.SR.Format(), System.Reflection.Metadata.Ecma335.BlobHeap.GetBlobReader(), System.Reflection.Internal.PooledStringBuilder.GetInstance(), System.handle, System.SR.InvalidDocumentName, System.Reflection.Metadata.BlobReader.Length, System.Reflection.Metadata.BlobReader.ReadBlobHandle(), System.Reflection.Metadata.BlobReader.ReadByte(), System.Reflection.Metadata.BlobReader.ReadUTF8(), System.Reflection.Metadata.BlobReader.RemainingBytes, and System.Reflection.Internal.PooledStringBuilder.ToStringAndFree().
Referenced by System.Reflection.Metadata.Ecma335.BlobHeap.DocumentNameEquals(), and System.Reflection.Metadata.MetadataReader.GetString().