Terraria: Terraria.IO.ResourcePack.ResourcePack
ResourcePack()
Terraria.IO.ResourcePack.ResourcePack (IServiceProvider services, string path, BrandingType branding = BrandingType::None) inline
Definition at line 68 of file ResourcePack.cs.
    {
        if (File.Exists(path))
        {
            IsCompressed = true;
        }
        else if (!Directory.Exists(path))
        {
            throw new FileNotFoundException("Unable to find file or folder for resource pack at: " + path);
        }
        FileName = Path.GetFileName(path);
        _services = services;
        FullPath = path;
        Branding = branding;
        if (IsCompressed)
        {
            _zipFile = ZipFile.Read(path);
        }
        LoadManifest();
    }
References Terraria.IO.ResourcePack._services, Terraria.IO.ResourcePack._zipFile, Terraria.IO.ResourcePack.Branding, System.IO.Directory.Exists(), System.IO.File.Exists(), Terraria.IO.ResourcePack.FileName, Terraria.IO.ResourcePack.FullPath, System.IO.Path.GetFileName(), Terraria.IO.ResourcePack.IsCompressed, and Terraria.IO.ResourcePack.LoadManifest().