Terraria: Chest.DestroyChest
DestroyChest()
static bool Chest.DestroyChest (int X, int Y) inline static
     {
         for (int i = 0; i < 8000; i++)
         {
             Chest chest = Main.chest[i];
             if (chest == null || chest.x != X || chest.y != Y)
             {
                 continue;
             }
             for (int j = 0; j < 40; j++)
             {
                 if (chest.item[j] != null && chest.item[j].type > 0 && chest.item[j].stack > 0)
                 {
                     return false;
                 }
             }
             Main.chest[i] = null;
             if (Main.player[Main.myPlayer].chest == i)
             {
                 Main.player[Main.myPlayer].chest = -1;
             }
             Recipe.FindRecipes();
             return true;
         }
         return true;
     }
References Main.chest, Player.chest, Recipe.FindRecipes(), item, Main.myPlayer, Main.player, Item.stack, Item.type, X, x, Y, and y.
Referenced by NPC.BigMimicSummonCheck(), WorldGen.CheckChest(), and WorldGen.CheckTileBreakability2_ShouldTileSurvive().