Terraria: Chest.SetupTravelShop
SetupTravelShop()
static void Chest.SetupTravelShop () inline static
     {
         for (int i = 0; i < 40; i++)
         {
             Main.travelShop[i] = 0;
         }
         Player player = null;
         for (int j = 0; j < 255; j++)
         {
             Player player2 = Main.player[j];
             if (player2.active && (player == null || player.luck < player2.luck))
             {
                 player = player2;
             }
         }
         if (player == null)
         {
             player = new Player();
         }
         int num = Main.rand.Next(4, 7);
         if (player.RollLuck(4) == 0)
         {
             num++;
         }
         if (player.RollLuck(8) == 0)
         {
             num++;
         }
         if (player.RollLuck(16) == 0)
         {
             num++;
         }
         if (player.RollLuck(32) == 0)
         {
             num++;
         }
         if (Main.expertMode && player.RollLuck(2) == 0)
         {
             num++;
         }
         if (NPC.peddlersSatchelWasUsed)
         {
             num++;
         }
         if (Main.tenthAnniversaryWorld)
         {
             if (!Main.getGoodWorld)
             {
                 num++;
             }
             num++;
         }
         int count = 0;
         int added = 0;
         int[] array = new int[6] { 100, 200, 300, 400, 500, 600 };
         int[] rarity = array;
         int num2 = 0;
         if (Main.hardMode)
         {
             int it = 0;
             while (num2 < 5000)
             {
                 num2++;
                 SetupTravelShop_AdjustSlotRarities(num2, ref rarity);
                 SetupTravelShop_GetItem(player, rarity, ref it, 2);
                 if (SetupTravelShop_CanAddItemToShop(it))
                 {
                     SetupTravelShop_AddToShop(it, ref added, ref count);
                     break;
                 }
             }
         }
         while (added < num)
         {
             int it2 = 0;
             SetupTravelShop_GetItem(player, array, ref it2);
             if (SetupTravelShop_CanAddItemToShop(it2))
             {
                 SetupTravelShop_AddToShop(it2, ref added, ref count);
             }
         }
         rarity = array;
         num2 = 0;
         int it3 = 0;
         while (num2 < 5000)
         {
             num2++;
             SetupTravelShop_AdjustSlotRarities(num2, ref rarity);
             SetupTravelShop_GetPainting(player, rarity, ref it3);
             if (SetupTravelShop_CanAddItemToShop(it3))
             {
                 SetupTravelShop_AddToShop(it3, ref added, ref count);
                 break;
             }
         }
     }
References Entity.active, Main.expertMode, Main.getGoodWorld, Main.hardMode, Player.luck, UnifiedRandom.Next(), NPC.peddlersSatchelWasUsed, Player, Main.player, Main.rand, Player.RollLuck(), SetupTravelShop_AddToShop(), SetupTravelShop_AdjustSlotRarities(), SetupTravelShop_CanAddItemToShop(), SetupTravelShop_GetItem(), SetupTravelShop_GetPainting(), Main.tenthAnniversaryWorld, and Main.travelShop.
Referenced by Main.Initialize_AlmostEverything(), and WorldGen.SpawnTravelNPC().