Terraria: Chest.AddItemToShop
AddItemToShop()
void Chest.AddItemToShop (Item newItem) inline
     {
         int num = Main.shopSellbackHelper.Remove(newItem);
         if (num >= newItem.stack)
         {
             return;
         }
         for (int i = 0; i < 39; i++)
         {
             if (item[i] == null || item[i].type == 0)
             {
                 item[i] = newItem.Clone();
                 item[i].favorited = false;
                 item[i].buyOnce = true;
                 item[i].stack -= num;
                 _ = item[i].value;
                 _ = 0;
                 break;
             }
         }
     }
References Item.buyOnce, Item.Clone(), Item.favorited, item, ItemShopSellbackHelper.Remove(), Main.shopSellbackHelper, Item.stack, and Item.value.
Referenced by ItemSlot.LeftClick(), and ItemSlot.SellOrTrash().