Terraria: Chest.FindChest
FindChest()
static int Chest.FindChest (int X, int Y) inline static
     {
         for (int i = 0; i < 8000; i++)
         {
             if (Main.chest[i] != null && Main.chest[i].x == X && Main.chest[i].y == Y)
             {
                 return i;
             }
         }
         return -1;
     }
References Main.chest, X, x, Y, and y.
Referenced by AskForChestToEatItem(), NPC.BigMimicSummonCheck(), TileDrawing.CacheSpecialDraws_Part2(), NetMessage.CompressTileBlock_Inner(), Main.DrawMap(), Projectile.GasTrapCheck(), MessageBuffer.GetData(), Player.TileInteractionsCheckLongDistance(), Player.TileInteractionsMouseOver(), Player.TileInteractionsMouseOver_Containers(), Player.TileInteractionsUse(), and DeadMansChestBiome.TurnGoldChestIntoDeadMansChest().