Terraria: Chest.Unlock
Unlock()
static bool Chest.Unlock (int X, int Y) inline static
     {
         if (Main.tile[X, Y] == null || Main.tile[X + 1, Y] == null || Main.tile[X, Y + 1] == null || Main.tile[X + 1, Y + 1] == null)
         {
             return false;
         }
         short num = 0;
         int type = 0;
         Tile tileSafely = Framing.GetTileSafely(X, Y);
         int type2 = tileSafely.type;
         int num2 = tileSafely.frameX / 36;
         switch (type2)
         {
         case 21:
             switch (num2)
             {
             case 2:
                 num = 36;
                 type = 11;
                 AchievementsHelper.NotifyProgressionEvent(19);
                 break;
             case 4:
                 num = 36;
                 type = 11;
                 break;
             case 23:
             case 24:
             case 25:
             case 26:
             case 27:
                 if (!NPC.downedPlantBoss)
                 {
                     return false;
                 }
                 num = 180;
                 type = 11;
                 AchievementsHelper.NotifyProgressionEvent(20);
                 break;
             case 36:
             case 38:
             case 40:
                 num = 36;
                 type = 11;
                 break;
             default:
                 return false;
             }
             break;
         case 467:
             if (num2 == 13)
             {
                 if (!NPC.downedPlantBoss)
                 {
                     return false;
                 }
                 num = 36;
                 type = 11;
                 AchievementsHelper.NotifyProgressionEvent(20);
                 break;
             }
             return false;
         }
         SoundEngine.PlaySound(22, X * 16, Y * 16);
         for (int i = X; i <= X + 1; i++)
         {
             for (int j = Y; j <= Y + 1; j++)
             {
                 Tile tileSafely2 = Framing.GetTileSafely(i, j);
                 if (tileSafely2.type == type2)
                 {
                     tileSafely2.frameX -= num;
                     Main.tile[i, j] = tileSafely2;
                     for (int k = 0; k < 4; k++)
                     {
                         Dust.NewDust(new Vector2(i * 16, j * 16), 16, 16, type);
                     }
                 }
             }
         }
         return true;
     }
References NPC.downedPlantBoss, Tile.frameX, Framing.GetTileSafely(), Dust.NewDust(), AchievementsHelper.NotifyProgressionEvent(), SoundEngine.PlaySound(), Main.tile, Tile.type, X, and Y.
Referenced by MessageBuffer.GetData(), and Player.TileInteractionsUse().