Terraria: Chest.ServerPlaceItem
ServerPlaceItem()
static void Chest.ServerPlaceItem (int plr, int slot) inline static
     {
         if (slot >= PlayerItemSlotID.Bank4_0 && slot < PlayerItemSlotID.Bank4_0 + 40)
         {
             int num = slot - PlayerItemSlotID.Bank4_0;
             Main.player[plr].bank4.item[num] = PutItemInNearbyChest(Main.player[plr].bank4.item[num], Main.player[plr].Center);
             NetMessage.SendData(5, -1, -1, null, plr, slot, (int)Main.player[plr].bank4.item[num].prefix);
         }
         else if (slot < 58)
         {
             Main.player[plr].inventory[slot] = PutItemInNearbyChest(Main.player[plr].inventory[slot], Main.player[plr].Center);
             NetMessage.SendData(5, -1, -1, null, plr, slot, (int)Main.player[plr].inventory[slot].prefix);
         }
     }
References Player.bank4, PlayerItemSlotID.Bank4_0, Entity.Center, Player.inventory, item, Main.player, Item.prefix, PutItemInNearbyChest(), and NetMessage.SendData().
Referenced by MessageBuffer.GetData().