Terraria: Chest.NearOtherChests
NearOtherChests()
static bool Chest.NearOtherChests (int x, int y) inline static
     {
         for (int i = x - 25; i < x + 25; i++)
         {
             for (int j = y - 8; j < y + 8; j++)
             {
                 Tile tileSafely = Framing.GetTileSafely(i, j);
                 if (tileSafely.active() && TileID.Sets.BasicChest[tileSafely.type])
                 {
                     return true;
                 }
             }
         }
         return false;
     }
References Tile.active(), TileID.Sets.BasicChest, Framing.GetTileSafely(), Tile.type, x, and y.
Referenced by WorldGen.PlaceChest().