Terraria: AchievementsHelper.NotifyProgressionEvent
NotifyProgressionEvent()
static void AchievementsHelper.NotifyProgressionEvent (int eventID) inline static
     {
         if (Main.netMode == 2)
         {
             NetMessage.SendData(98, -1, -1, null, eventID);
         }
         else if (AchievementsHelper.OnProgressionEvent != null)
         {
             AchievementsHelper.OnProgressionEvent(eventID);
         }
     }
References Main.netMode, OnProgressionEvent, and NetMessage.SendData().
Referenced by NPC.AI_003_Fighters(), WorldGen.CheckAchievement_RealEstateAndTownSlimes(), BirthdayParty.CheckForAchievement(), CheckMechaMayhem(), WorldGen.CheckOrb(), NPC.CheckProgressFrostMoon(), NPC.CheckProgressPumpkinMoon(), NPC.DoDeathEvents(), MessageBuffer.GetData(), Item.GetShimmered(), Player.ItemCheck_UseEventItems(), Chest.Lock(), WorldGen.QuickFindHome(), WorldGen.SmashAltar(), WorldGen.smCallBack(), WorldGen.SpawnTownNPC(), Chest.Unlock(), WorldGen.UnlockDoor(), Main.UpdateInvasion(), Main.UpdateTime_StartDay(), Main.UpdateTime_StartNight(), and DD2Event.WinInvasionInternal().