Terraria: AchievementsHelper.HandleAnglerService
HandleAnglerService()
static void AchievementsHelper.HandleAnglerService () inline static
     {
         Main.Achievements.GetCondition("SERVANT_IN_TRAINING", "Finish").Complete();
         ((CustomIntCondition)Main.Achievements.GetCondition("GOOD_LITTLE_SLAVE", "Finish")).Value++;
         ((CustomIntCondition)Main.Achievements.GetCondition("TROUT_MONKEY", "Finish")).Value++;
         ((CustomIntCondition)Main.Achievements.GetCondition("FAST_AND_FISHIOUS", "Finish")).Value++;
         ((CustomIntCondition)Main.Achievements.GetCondition("SUPREME_HELPER_MINION", "Finish")).Value++;
     }
References Main.Achievements, AchievementCondition.Complete(), and AchievementManager.GetCondition().
Referenced by Main.GUIChatDrawInner().