Terraria: System.Net.Base64Stream.WriteAsyncResult.OnWrite
OnWrite()
static void System.Net.Base64Stream.WriteAsyncResult.OnWrite (IAsyncResult result) inline static private
Definition at line 140 of file Base64Stream.cs.
        {
            if (result.CompletedSynchronously)
            {
                return;
            }
            WriteAsyncResult writeAsyncResult = (WriteAsyncResult)result.AsyncState;
            try
            {
                writeAsyncResult.CompleteWrite(result);
                writeAsyncResult.Write();
            }
            catch (Exception result2)
            {
                if (writeAsyncResult.IsCompleted)
                {
                    throw;
                }
                writeAsyncResult.InvokeCallback(result2);
            }
        }
References System.Net.Base64Stream.WriteAsyncResult.WriteAsyncResult(), System.IAsyncResult.AsyncState, System.IAsyncResult.CompletedSynchronously, System.Net.Base64Stream.WriteAsyncResult.CompleteWrite(), System.Net.LazyAsyncResult.InvokeCallback(), System.Net.LazyAsyncResult.IsCompleted, and System.Net.Base64Stream.WriteAsyncResult.Write().