Terraria: System.Net.Base64Stream.WriteAsyncResult.CompleteWrite
CompleteWrite()
void System.Net.Base64Stream.WriteAsyncResult.CompleteWrite (IAsyncResult result) inline private
Definition at line 134 of file Base64Stream.cs.
        {
            _parent.BaseStream.EndWrite(result);
            _parent.WriteState.Reset();
        }
References System.Net.Base64Stream.WriteAsyncResult._parent, System.Net.DelegatedStream.BaseStream, System.IO.Stream.EndWrite(), System.Net.Mime.WriteStateInfoBase.Reset(), and System.Net.Base64Stream.WriteState.
Referenced by System.Net.Base64Stream.WriteAsyncResult.OnWrite(), and System.Net.Base64Stream.WriteAsyncResult.Write().