Terraria: System.Net.Base64Stream.WriteAsyncResult.Write
Write()
void System.Net.Base64Stream.WriteAsyncResult.Write () inline package
Definition at line 114 of file Base64Stream.cs.
        {
            while (true)
            {
                _written += _parent.EncodeBytes(_buffer, _offset + _written, _count - _written, dontDeferFinalBytes: false, shouldAppendSpaceToCRLF: false);
                if (_written < _count)
                {
                    IAsyncResult asyncResult = _parent.BaseStream.BeginWrite(_parent.WriteState.Buffer, 0, _parent.WriteState.Length, s_onWrite, this);
                    if (asyncResult.CompletedSynchronously)
                    {
                        CompleteWrite(asyncResult);
                        continue;
                    }
                    break;
                }
                InvokeCallback();
                break;
            }
        }
References System.Net.Base64Stream.WriteAsyncResult._buffer, System.Net.Base64Stream.WriteAsyncResult._count, System.Net.Base64Stream.WriteAsyncResult._offset, System.Net.Base64Stream.WriteAsyncResult._parent, System.Net.Base64Stream.WriteAsyncResult._written, System.asyncResult, System.Net.DelegatedStream.BaseStream, System.IO.Stream.BeginWrite(), System.Net.Mime.WriteStateInfoBase.Buffer, System.Net.Base64Stream.WriteAsyncResult.CompleteWrite(), System.Net.Base64Stream.EncodeBytes(), System.Net.LazyAsyncResult.InvokeCallback(), System.Net.Mime.WriteStateInfoBase.Length, System.Net.Base64Stream.WriteAsyncResult.s_onWrite, and System.Net.Base64Stream.WriteState.
Referenced by System.Net.Base64Stream.BeginWrite(), and System.Net.Base64Stream.WriteAsyncResult.OnWrite().