Terraria: UIVerticalSlider.DrawValueBarDynamicWidth
DrawValueBarDynamicWidth()
bool UIVerticalSlider.DrawValueBarDynamicWidth (SpriteBatch spriteBatch, out float sliderValueThatWasSet) inline private
     {
         sliderValueThatWasSet = 0f;
         Texture2D value = TextureAssets.ColorBar.Value;
         Rectangle rectangle = GetDimensions().ToRectangle();
         Rectangle rectangle2 = new Rectangle(5, 4, 4, 4);
         Utils.DrawSplicedPanel(spriteBatch, value, rectangle.X, rectangle.Y, rectangle.Width, rectangle.Height, rectangle2.X, rectangle2.Width, rectangle2.Y, rectangle2.Height, Color.White);
         Rectangle rectangle3 = rectangle;
         rectangle3.X += rectangle2.Left;
         rectangle3.Width -= rectangle2.Right;
         rectangle3.Y += rectangle2.Top;
         rectangle3.Height -= rectangle2.Bottom;
         Texture2D value2 = TextureAssets.MagicPixel.Value;
         Rectangle value3 = new Rectangle(0, 0, 1, 1);
         spriteBatch.Draw(value2, rectangle3, value3, EmptyColor);
         Rectangle destinationRectangle = rectangle3;
         destinationRectangle.Height = (int)((float)destinationRectangle.Height * FillPercent);
         destinationRectangle.Y += rectangle3.Height - destinationRectangle.Height;
         spriteBatch.Draw(value2, destinationRectangle, value3, FilledColor);
         Vector2 center = new Vector2(destinationRectangle.Center.X + 1, destinationRectangle.Top);
         Vector2 size = new Vector2(destinationRectangle.Width + 16, 4f);
         Rectangle rectangle4 = Utils.CenteredRectangle(center, size);
         Rectangle destinationRectangle2 = rectangle4;
         destinationRectangle2.Inflate(2, 2);
         spriteBatch.Draw(value2, destinationRectangle2, value3, Color.Black);
         spriteBatch.Draw(value2, rectangle4, value3, Color.White);
         Rectangle rectangle5 = rectangle3;
         rectangle5.Inflate(4, 0);
         bool flag = (_isReallyMouseOvered = rectangle5.Contains(Main.MouseScreen.ToPoint()));
         if (IgnoresMouseInteraction)
         {
             flag = false;
         }
         int usageLevel = GetUsageLevel();
         if (usageLevel == 2)
         {
             flag = false;
         }
         if (usageLevel == 1)
         {
             flag = true;
         }
         if (flag || usageLevel == 1)
         {
             if (!_alreadyHovered)
             {
                 SoundEngine.PlaySound(12);
             }
             _alreadyHovered = true;
         }
         else
         {
             _alreadyHovered = false;
         }
         if (flag)
         {
             sliderValueThatWasSet = Utils.GetLerpValue(rectangle3.Bottom, rectangle3.Top, Main.mouseY, clamped: true);
             return true;
         }
         return false;
     }
References _alreadyHovered, _isReallyMouseOvered, Utils.CenteredRectangle(), Color, TextureAssets.ColorBar, Utils.DrawSplicedPanel(), EmptyColor, FilledColor, FillPercent, UIElement.GetDimensions(), Utils.GetLerpValue(), UISliderBase.GetUsageLevel(), UIElement.IgnoresMouseInteraction, TextureAssets.MagicPixel, Main.MouseScreen, Main.mouseY, SoundEngine.PlaySound(), CalculatedStyle.ToRectangle(), and Asset< T >.Value.
Referenced by DrawSelf().