Terraria: Terraria.Social.WeGame.NetServerSocialModule.UpdateUserStateBySessionAuthResult
UpdateUserStateBySessionAuthResult()
void Terraria.Social.WeGame.NetServerSocialModule.UpdateUserStateBySessionAuthResult (GameServerStartSessionWithPlayerResponse data) inline private
    {
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        RailID remote_rail_id = data.remote_rail_id;
        RailResult result = ((EventBase)data).result;
        if (_connectionStateMap.ContainsKey(remote_rail_id))
        {
            if ((int)result == 0)
            {
                WeGameHelper.WriteDebugString("UpdateUserStateBySessionAuthResult Auth Success");
                BroadcastConnectedUsers();
            }
            else
            {
                WeGameHelper.WriteDebugString("UpdateUserStateBySessionAuthResult Auth Failed");
                CloseAndUpdateUserState(remote_rail_id);
            }
        }
    }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, Terraria.Social.WeGame.NetServerSocialModule.BroadcastConnectedUsers(), Terraria.Social.WeGame.NetServerSocialModule.CloseAndUpdateUserState(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.OnRailEvent().