Terraria: Terraria.Social.WeGame.NetServerSocialModule.OnRailEvent
OnRailEvent()
void Terraria.Social.WeGame.NetServerSocialModule.OnRailEvent (RAILEventID event_id, EventBase data) inline
Definition at line 292 of file NetServerSocialModule.cs.
    {
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Invalid comparison between Unknown and I4
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Expected O, but got Unknown
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Invalid comparison between Unknown and I4
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Expected O, but got Unknown
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Invalid comparison between Unknown and I4
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Expected O, but got Unknown
        WeGameHelper.WriteDebugString("OnRailEvent,id=" + ((object)(RAILEventID)(ref event_id)).ToString() + " ,result=" + ((object)(RailResult)(ref data.result)).ToString());
        if ((int)event_id != 3006)
        {
            if ((int)event_id != 16001)
            {
                if ((int)event_id == 16002)
                {
                    OnCreateSessionFailed((CreateSessionFailed)data);
                }
            }
            else
            {
                OnCreateSessionRequest((CreateSessionRequest)data);
            }
        }
        else
        {
            UpdateUserStateBySessionAuthResult((GameServerStartSessionWithPlayerResponse)data);
        }
    }
References Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionFailed(), Terraria.Social.WeGame.NetServerSocialModule.OnCreateSessionRequest(), System.ToString, Terraria.Social.WeGame.NetServerSocialModule.UpdateUserStateBySessionAuthResult(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.RegisterRailEvent().