Terraria: Terraria.GameContent.Creative.ItemFilters.AAccessories.IsAnAccessoryOfType
IsAnAccessoryOfType()
bool Terraria.GameContent.Creative.ItemFilters.AAccessories.IsAnAccessoryOfType (Item entry, AccessoriesCategory categoryType) inline inherited
        {
            bool flag = ItemSlot.IsMiscEquipment(entry);
            if (flag && categoryType == AccessoriesCategory.Misc)
            {
                return true;
            }
            if (!flag && categoryType == AccessoriesCategory.NonMisc && entry.accessory)
            {
                return true;
            }
            return false;
        }
References Terraria.UI.ItemSlot.IsMiscEquipment().
Referenced by Terraria.GameContent.Creative.ItemFilters.Accessories.FitsFilter(), and Terraria.GameContent.Creative.ItemFilters.MiscAccessories.FitsFilter().