Terraria: Internal.Cryptography.Pal.StorePal.Remove
Remove()
unsafe void Internal.Cryptography.Pal.StorePal.Remove (ICertificatePal certificate) inline
Implements Internal.Cryptography.Pal.IStorePal.
Definition at line 66 of file StorePal.cs.
    {
        SafeCertContextHandle certContext = ((CertificatePal)certificate).CertContext;
        SafeCertContextHandle pCertContext = null;
        CERT_CONTEXT* certContext2 = certContext.CertContext;
        if (global::Interop.crypt32.CertFindCertificateInStore(_certStore, CertFindType.CERT_FIND_EXISTING, certContext2, ref pCertContext))
        {
            CERT_CONTEXT* pCertContext2 = pCertContext.Disconnect();
            if (!global::Interop.crypt32.CertDeleteCertificateFromStore(pCertContext2))
            {
                throw Marshal.GetLastWin32Error().ToCryptographicException();
            }
            GC.KeepAlive(certContext);
        }
    }
References Internal.Cryptography.Pal.StorePal._certStore, Internal.Cryptography.Pal.Native.SafeCertContextHandle.CertContext, Internal.Cryptography.Pal.Native.SafeCertContextHandle.Disconnect(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), and System.GC.KeepAlive().