Terraria: Internal.Cryptography.Pal.StorePal.FromBlobOrFile
FromBlobOrFile()
static unsafe StorePal Internal.Cryptography.Pal.StorePal.FromBlobOrFile (ReadOnlySpan< byte > rawData, string fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) inline static private
Definition at line 205 of file StorePal.cs.
    {
        bool flag = fileName != null;
        fixed (byte* pbData = rawData)
        {
            fixed (char* ptr = fileName)
            {
                CRYPTOAPI_BLOB cRYPTOAPI_BLOB = new CRYPTOAPI_BLOB((!flag) ? rawData.Length : 0, pbData);
                bool flag2 = (keyStorageFlags & X509KeyStorageFlags.PersistKeySet) != 0;
                PfxCertStoreFlags dwFlags = MapKeyStorageFlags(keyStorageFlags);
                void* pvObject = (flag ? ((void*)ptr) : ((void*)(&cRYPTOAPI_BLOB)));
                if (!global::Interop.crypt32.CryptQueryObject(flag ? CertQueryObjectType.CERT_QUERY_OBJECT_FILE : CertQueryObjectType.CERT_QUERY_OBJECT_BLOB, pvObject, ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_CERT | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_SERIALIZED_STORE | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_SERIALIZED_CERT | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_PKCS7_UNSIGNED | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_PKCS7_SIGNED_EMBED | ExpectedContentTypeFlags.CERT_QUERY_CONTENT_FLAG_PFX, ExpectedFormatTypeFlags.CERT_QUERY_FORMAT_FLAG_ALL, 0, IntPtr.Zero, out var pdwContentType, IntPtr.Zero, out var phCertStore, IntPtr.Zero, IntPtr.Zero))
                {
                    throw Marshal.GetLastWin32Error().ToCryptographicException();
                }
                if (pdwContentType == ContentType.CERT_QUERY_CONTENT_PFX)
                {
                    phCertStore.Dispose();
                    if (flag)
                    {
                        rawData = File.ReadAllBytes(fileName);
                    }
                    fixed (byte* pbData2 = rawData)
                    {
                        CRYPTOAPI_BLOB pPFX = new CRYPTOAPI_BLOB(rawData.Length, pbData2);
                        phCertStore = global::Interop.crypt32.PFXImportCertStore(ref pPFX, password, dwFlags);
                        if (phCertStore == null || phCertStore.IsInvalid)
{
                            throw Marshal.GetLastWin32Error().ToCryptographicException();
                        }
                    }
                    if (!flag2)
                    {
                        SafeCertContextHandle pCertContext = null;
                        while (global::Interop.crypt32.CertEnumCertificatesInStore(phCertStore, ref pCertContext))
{
                            CRYPTOAPI_BLOB cRYPTOAPI_BLOB2 = new CRYPTOAPI_BLOB(0, null);
                            if (!global::Interop.crypt32.CertSetCertificateContextProperty(pCertContext, CertContextPropId.CERT_CLR_DELETE_KEY_PROP_ID, CertSetPropertyFlags.CERT_SET_PROPERTY_INHIBIT_PERSIST_FLAG, &cRYPTOAPI_BLOB2))
{
                                throw Marshal.GetLastWin32Error().ToCryptographicException();
                            }
                        }
                    }
                }
                return new StorePal(phCertStore);
            }
        }
    }
References Internal.Cryptography.Pal.StorePal.StorePal(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.ReadOnlySpan< T >.Length, Internal.Cryptography.Pal.StorePal.MapKeyStorageFlags(), System.IO.File.ReadAllBytes(), and System.IntPtr.Zero.
Referenced by Internal.Cryptography.Pal.StorePal.FromBlob(), and Internal.Cryptography.Pal.StorePal.FromFile().