Terraria: Internal.Cryptography.Pal.StorePal.Export
Export()
unsafe byte[] Internal.Cryptography.Pal.StorePal.Export (X509ContentType contentType, SafePasswordHandle password) inline
Implements Internal.Cryptography.Pal.IExportPal.
Definition at line 100 of file StorePal.cs.
    {
        switch (contentType)
        {
        case X509ContentType.Cert:
        {
            SafeCertContextHandle pCertContext = null;
            if (!global::Interop.crypt32.CertEnumCertificatesInStore(_certStore, ref pCertContext))
            {
                return null;
            }
            try
            {
                byte[] array2 = new byte[pCertContext.CertContext->cbCertEncoded];
                Marshal.Copy((IntPtr)pCertContext.CertContext->pbCertEncoded, array2, 0, array2.Length);
                GC.KeepAlive(pCertContext);
                return array2;
            }
            finally
            {
                pCertContext.Dispose();
            }
        }
        case X509ContentType.SerializedCert:
        {
            SafeCertContextHandle pCertContext2 = null;
            if (!global::Interop.crypt32.CertEnumCertificatesInStore(_certStore, ref pCertContext2))
            {
                return null;
            }
            try
            {
                int pcbElement = 0;
                if (!global::Interop.crypt32.CertSerializeCertificateStoreElement(pCertContext2, 0, null, ref pcbElement))
                {
                    throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
                }
                byte[] array3 = new byte[pcbElement];
                if (!global::Interop.crypt32.CertSerializeCertificateStoreElement(pCertContext2, 0, array3, ref pcbElement))
                {
                    throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
                }
                return array3;
            }
            finally
            {
                pCertContext2.Dispose();
            }
        }
        case X509ContentType.Pfx:
        {
            CRYPTOAPI_BLOB pPFX = new CRYPTOAPI_BLOB(0, null);
            if (!global::Interop.crypt32.PFXExportCertStore(_certStore, ref pPFX, password, PFXExportFlags.REPORT_NOT_ABLE_TO_EXPORT_PRIVATE_KEY | PFXExportFlags.EXPORT_PRIVATE_KEYS))
            {
                throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
            }
            byte[] array = new byte[pPFX.cbData];
            fixed (byte* pbData = array)
            {
                pPFX.pbData = pbData;
                if (!global::Interop.crypt32.PFXExportCertStore(_certStore, ref pPFX, password, PFXExportFlags.REPORT_NOT_ABLE_TO_EXPORT_PRIVATE_KEY | PFXExportFlags.EXPORT_PRIVATE_KEYS))
                {
                    throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
                }
            }
            return array;
        }
        case X509ContentType.SerializedStore:
            return SaveToMemoryStore(CertStoreSaveAs.CERT_STORE_SAVE_AS_STORE);
        case X509ContentType.Pkcs7:
            return SaveToMemoryStore(CertStoreSaveAs.CERT_STORE_SAVE_AS_PKCS7);
        default:
            throw new CryptographicException(System.SR.Cryptography_X509_InvalidContentType);
        }
    }
References Internal.Cryptography.Pal.StorePal._certStore, System.array, Internal.Cryptography.Pal.Native.CERT_CONTEXT.cbCertEncoded, Internal.Cryptography.Pal.Native.CRYPTOAPI_BLOB.cbData, Internal.Cryptography.Pal.Native.SafeCertContextHandle.CertContext, System.Runtime.InteropServices.Marshal.Copy(), System.SR.Cryptography_X509_InvalidContentType, Internal.Cryptography.Pal.Native.SafePointerHandle< T >.Dispose(), System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), System.GC.KeepAlive(), Internal.Cryptography.Pal.Native.CERT_CONTEXT.pbCertEncoded, and Internal.Cryptography.Pal.StorePal.SaveToMemoryStore().