Terraria: Terraria.Social.WeGame.NetServerSocialModule.UpdateFriendList
UpdateFriendList()
void Terraria.Social.WeGame.NetServerSocialModule.UpdateFriendList (WeGameFriendListInfo friendListInfo) inline private
Definition at line 167 of file NetServerSocialModule.cs.
    {
        _wegameFriendList = friendListInfo._friendList;
        WeGameHelper.WriteDebugString("On update friend list - " + DumpFriendListString(friendListInfo._friendList));
    }
References Terraria.Social.WeGame.WeGameFriendListInfo._friendList, Terraria.Social.WeGame.NetServerSocialModule._wegameFriendList, Terraria.Social.WeGame.NetServerSocialModule.DumpFriendListString(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetServerSocialModule.OnWegameMessage().