Terraria: Internal.Cryptography.Pal.StorePal.FromCertificate
FromCertificate()
static IExportPal Internal.Cryptography.Pal.StorePal.FromCertificate (ICertificatePalCore cert) inline static
Definition at line 254 of file StorePal.cs.
    {
        CertificatePal certificatePal = (CertificatePal)cert;
        SafeCertStoreHandle safeCertStoreHandle = global::Interop.crypt32.CertOpenStore(CertStoreProvider.CERT_STORE_PROV_MEMORY, CertEncodingType.All, IntPtr.Zero, CertStoreFlags.CERT_STORE_DEFER_CLOSE_UNTIL_LAST_FREE_FLAG | CertStoreFlags.CERT_STORE_ENUM_ARCHIVED_FLAG | CertStoreFlags.CERT_STORE_CREATE_NEW_FLAG, null);
        if (safeCertStoreHandle.IsInvalid)
        {
            throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
        }
        if (!global::Interop.crypt32.CertAddCertificateLinkToStore(safeCertStoreHandle, certificatePal.CertContext, CertStoreAddDisposition.CERT_STORE_ADD_ALWAYS, IntPtr.Zero))
        {
            throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
        }
        return new StorePal(safeCertStoreHandle);
    }
References Internal.Cryptography.Pal.StorePal.StorePal(), Internal.Cryptography.Pal.CertificatePal.CertContext, System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), Internal.Cryptography.Pal.Native.SafePointerHandle< T >.IsInvalid, and System.IntPtr.Zero.
Referenced by Internal.Cryptography.Pal.CertificatePal.Export().