Terraria: Internal.Cryptography.Pal.StorePal.LinkFromCertificateCollection
LinkFromCertificateCollection()
static IExportPal Internal.Cryptography.Pal.StorePal.LinkFromCertificateCollection (X509Certificate2Collection certificates) inline static
Definition at line 269 of file StorePal.cs.
    {
        SafeCertStoreHandle safeCertStoreHandle = global::Interop.crypt32.CertOpenStore(CertStoreProvider.CERT_STORE_PROV_MEMORY, CertEncodingType.All, IntPtr.Zero, CertStoreFlags.CERT_STORE_ENUM_ARCHIVED_FLAG | CertStoreFlags.CERT_STORE_CREATE_NEW_FLAG, null);
        if (safeCertStoreHandle.IsInvalid)
        {
            throw Marshal.GetHRForLastWin32Error().ToCryptographicException();
        }
        for (int i = 0; i < certificates.Count; i++)
        {
            SafeCertContextHandle certContext = ((CertificatePal)certificates[i].Pal).CertContext;
            if (!global::Interop.crypt32.CertAddCertificateLinkToStore(safeCertStoreHandle, certContext, CertStoreAddDisposition.CERT_STORE_ADD_ALWAYS, IntPtr.Zero))
            {
                throw Marshal.GetLastWin32Error().ToCryptographicException();
            }
        }
        return new StorePal(safeCertStoreHandle);
    }
References Internal.Cryptography.Pal.StorePal.StorePal(), Internal.Cryptography.Pal.Native.SafeCertContextHandle.CertContext, System.Collections.CollectionBase.Count, System.Runtime.InteropServices.Marshal.GetHRForLastWin32Error(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Internal.Cryptography.Pal.Native.SafePointerHandle< T >.IsInvalid, and System.IntPtr.Zero.
Referenced by Internal.Cryptography.Pal.FindPal.FindPal(), Internal.Cryptography.Pal.ChainPal.ConvertStoreToSafeHandle(), and System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Export().