Terraria: Internal.Cryptography.Pal.StorePal.FromSystemStore
FromSystemStore()
static IStorePal Internal.Cryptography.Pal.StorePal.FromSystemStore (string storeName, StoreLocation storeLocation, OpenFlags openFlags) inline static
Definition at line 287 of file StorePal.cs.
    {
        CertStoreFlags dwFlags = MapX509StoreFlags(storeLocation, openFlags);
        SafeCertStoreHandle safeCertStoreHandle = global::Interop.crypt32.CertOpenStore(CertStoreProvider.CERT_STORE_PROV_SYSTEM_W, CertEncodingType.All, IntPtr.Zero, dwFlags, storeName);
        if (safeCertStoreHandle.IsInvalid)
        {
            throw Marshal.GetLastWin32Error().ToCryptographicException();
        }
        global::Interop.crypt32.CertControlStore(safeCertStoreHandle, CertControlStoreFlags.None, CertControlStoreType.CERT_STORE_CTRL_AUTO_RESYNC, IntPtr.Zero);
        return new StorePal(safeCertStoreHandle);
    }
References Internal.Cryptography.Pal.StorePal.StorePal(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Internal.Cryptography.Pal.Native.SafePointerHandle< T >.IsInvalid, Internal.Cryptography.Pal.StorePal.MapX509StoreFlags(), and System.IntPtr.Zero.
Referenced by System.Security.Cryptography.X509Certificates.X509Store.Open().