Terraria: System.Security.Cryptography.ECDsa.HashSpanToTmp
HashSpanToTmp()
ReadOnlySpan< byte > System.Security.Cryptography.ECDsa.HashSpanToTmp (ReadOnlySpan< byte > data, HashAlgorithmName hashAlgorithm, Span< byte > tmp) inline private inherited
Definition at line 538 of file ECDsa.cs.
    {
        if (TryHashData(data, tmp, hashAlgorithm, out var bytesWritten))
        {
            return tmp.Slice(0, bytesWritten);
        }
        return HashSpanToArray(data, hashAlgorithm);
    }
References System.Security.Cryptography.ECDsa.HashSpanToArray(), System.Span< T >.Slice(), and System.Security.Cryptography.ECDsa.TryHashData().
Referenced by System.Security.Cryptography.ECDsa.TrySignData(), System.Security.Cryptography.ECDsa.TrySignDataCore(), and System.Security.Cryptography.ECDsa.VerifyData().