Terraria: System.Security.Cryptography.ECDsa.GetMaxSignatureSize
GetMaxSignatureSize()
int System.Security.Cryptography.ECDsa.GetMaxSignatureSize (DSASignatureFormat signatureFormat) inline inherited
Definition at line 748 of file ECDsa.cs.
    {
        int keySize = KeySize;
        if (keySize == 0)
        {
            ExportParameters(includePrivateParameters: false);
            keySize = KeySize;
            if (keySize == 0)
            {
                throw new NotSupportedException(System.SR.Cryptography_InvalidKeySize);
            }
        }
        return signatureFormat switch
        {
            DSASignatureFormat.IeeeP1363FixedFieldConcatenation => AsymmetricAlgorithmHelpers.BitsToBytes(keySize) * 2,
            DSASignatureFormat.Rfc3279DerSequence => AsymmetricAlgorithmHelpers.GetMaxDerSignatureSize(keySize),
            _ => throw new ArgumentOutOfRangeException("signatureFormat"),
        };
    }
References Internal.Cryptography.AsymmetricAlgorithmHelpers.BitsToBytes(), System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.ECDsa.ExportParameters(), Internal.Cryptography.AsymmetricAlgorithmHelpers.GetMaxDerSignatureSize(), and System.Security.Cryptography.AsymmetricAlgorithm.KeySize.
Referenced by System.Security.Cryptography.ECDsa.SignDataCore(), and System.Security.Cryptography.ECDsa.SignHashCore().