Terraria: System.Security.Cryptography.ECDsa.VerifyDataCore
VerifyDataCore() [1/2]
virtual bool System.Security.Cryptography.ECDsa.VerifyDataCore (ReadOnlySpan< byte > data, ReadOnlySpan< byte > signature, HashAlgorithmName hashAlgorithm, DSASignatureFormat signatureFormat) inline protected virtual inherited
Definition at line 382 of file ECDsa.cs.
    {
        Span<byte> span = stackalloc byte[64];
        span = ((!TryHashData(data, span, hashAlgorithm, out var bytesWritten)) ? ((Span<byte>)HashData(data.ToArray(), 0, data.Length, hashAlgorithm)) : span.Slice(0, bytesWritten));
        return VerifyHashCore(span, signature, signatureFormat);
    }
References System.Security.Cryptography.ECDsa.HashData(), System.ReadOnlySpan< T >.Length, System.Span< T >.Slice(), System.ReadOnlySpan< T >.ToArray(), System.Security.Cryptography.ECDsa.TryHashData(), and System.Security.Cryptography.ECDsa.VerifyHashCore().
Referenced by System.Security.Cryptography.ECDsa.VerifyData(), System.Security.Cryptography.ECDsa.VerifyData(), System.Security.Cryptography.ECDsa.VerifyData(), and System.Security.Cryptography.ECDsa.VerifyData().