Terraria: System.Security.Cryptography.ECDsa.ImportFromPem
ImportFromPem()
override void System.Security.Cryptography.ECDsa.ImportFromPem (ReadOnlySpan< char > input) inline virtual inherited
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 768 of file ECDsa.cs.
    {
        PemKeyImportHelpers.ImportPem(input, delegate(ReadOnlySpan<char> label)
        {
            if (label.SequenceEqual("PRIVATE KEY"))
            {
                return ImportPkcs8PrivateKey;
            }
            if (label.SequenceEqual("PUBLIC KEY"))
            {
                return ImportSubjectPublicKeyInfo;
            }
            return label.SequenceEqual("EC PRIVATE KEY") ? new PemKeyImportHelpers.ImportKeyAction(ImportECPrivateKey) : null;
        });
    }
References System.Security.Cryptography.ECDsa.ImportECPrivateKey(), Internal.Cryptography.PemKeyImportHelpers.ImportKeyAction(), Internal.Cryptography.PemKeyImportHelpers.ImportPem(), and System.input.