Terraria: System.Security.Cryptography.ECDsa.TrySignDataCore
TrySignDataCore()
virtual bool System.Security.Cryptography.ECDsa.TrySignDataCore (ReadOnlySpan< byte > data, Span< byte > destination, HashAlgorithmName hashAlgorithm, DSASignatureFormat signatureFormat, out int bytesWritten) inline protected virtual inherited
Definition at line 252 of file ECDsa.cs.
    {
        Span<byte> tmp = stackalloc byte[128];
        ReadOnlySpan<byte> hash = HashSpanToTmp(data, hashAlgorithm, tmp);
        return TrySignHashCore(hash, destination, signatureFormat, out bytesWritten);
    }
References System.destination, System.Security.Cryptography.ECDsa.HashSpanToTmp(), and System.Security.Cryptography.ECDsa.TrySignHashCore().
Referenced by System.Security.Cryptography.ECDsa.SignDataCore(), and System.Security.Cryptography.ECDsa.TrySignData().