Terraria: System.Security.Cryptography.ECDsa.ImportParameters
ImportParameters()
virtual void System.Security.Cryptography.ECDsa.ImportParameters (ECParameters parameters) inline virtual
Reimplemented in System.Security.Cryptography.ECDsaImplementation.ECDsaCng, System.Security.Cryptography.ECDsaCng, and System.Security.Cryptography.ECDsaOpenSsl.
Definition at line 39 of file ECDsa.cs.
    {
        throw new NotSupportedException(System.SR.NotSupported_SubclassOverride);
    }
References System.SR.NotSupported_SubclassOverride.
Referenced by System.Security.Cryptography.ECDsa.Create(), System.Security.Cryptography.ECDsa.ImportECPrivateKey(), System.Security.Cryptography.ECDsa.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsa.ImportPkcs8PrivateKey(), and System.Security.Cryptography.ECDsa.ImportSubjectPublicKeyInfo().