Terraria: System.Security.Cryptography.ECDsa.TryHashData
TryHashData()
virtual bool System.Security.Cryptography.ECDsa.TryHashData (ReadOnlySpan< byte > data, Span< byte > destination, HashAlgorithmName hashAlgorithm, out int bytesWritten) inline protected virtual inherited
Reimplemented in System.Security.Cryptography.ECDsaImplementation.ECDsaCng, and System.Security.Cryptography.ECDsaCng.
Definition at line 448 of file ECDsa.cs.
    {
        byte[] array = ArrayPool<byte>.Shared.Rent(data.Length);
        bool flag = false;
        try
        {
            data.CopyTo(array);
            byte[] array2 = HashData(array, 0, data.Length, hashAlgorithm);
            flag = true;
            if (array2.Length <= destination.Length)
            {
                new ReadOnlySpan<byte>(array2).CopyTo(destination);
                bytesWritten = array2.Length;
                return true;
            }
            bytesWritten = 0;
            return false;
        }
        finally
        {
            Array.Clear(array, 0, data.Length);
            if (flag)
            {
                ArrayPool<byte>.Shared.Return(array);
            }
        }
    }
References System.array, System.Array.Clear(), System.ReadOnlySpan< T >.CopyTo(), System.destination, System.Security.Cryptography.ECDsa.HashData(), System.ReadOnlySpan< T >.Length, and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.Security.Cryptography.ECDsa.HashSpanToTmp(), and System.Security.Cryptography.ECDsa.VerifyDataCore().