Terraria: System.Security.Cryptography.ECDsa.SignDataCore
SignDataCore() [1/2]
virtual byte[] System.Security.Cryptography.ECDsa.SignDataCore (ReadOnlySpan< byte > data, HashAlgorithmName hashAlgorithm, DSASignatureFormat signatureFormat) inline protected virtual inherited
Definition at line 105 of file ECDsa.cs.
    {
        Span<byte> destination = stackalloc byte[256];
        int maxSignatureSize = GetMaxSignatureSize(signatureFormat);
        byte[] array = null;
        bool flag = false;
        int bytesWritten = 0;
        if (maxSignatureSize > destination.Length)
        {
            array = ArrayPool<byte>.Shared.Rent(maxSignatureSize);
            destination = array;
        }
        try
        {
            if (!TrySignDataCore(data, destination, hashAlgorithm, signatureFormat, out bytesWritten))
            {
                throw new CryptographicException();
            }
            byte[] result = destination.Slice(0, bytesWritten).ToArray();
            flag = true;
            return result;
        }
        finally
        {
            if (array != null)
            {
                CryptographicOperations.ZeroMemory(array.AsSpan(0, bytesWritten));
                if (flag)
                {
                    ArrayPool<byte>.Shared.Return(array);
                }
            }
        }
    }
References System.array, System.destination, System.Security.Cryptography.ECDsa.GetMaxSignatureSize(), System.Buffers.ArrayPool< T >.Shared, System.Security.Cryptography.ECDsa.TrySignDataCore(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().
Referenced by System.Security.Cryptography.ECDsa.SignData(), System.Security.Cryptography.ECDsa.SignData(), and System.Security.Cryptography.ECDsa.SignData().