using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Runtime.Versioning;

[assembly: CLSCompliant(true)]
[assembly: DefaultDllImportSearchPaths(DllImportSearchPath.System32 | DllImportSearchPath.AssemblyDirectory)]
[assembly: AssemblyDefaultAlias("System.Runtime.Intrinsics")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyMetadata("PreferInbox", "True")]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("System.Runtime.Intrinsics")]
[assembly: AssemblyFileVersion("6.0.21.52210")]
[assembly: AssemblyInformationalVersion("6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6")]
[assembly: AssemblyProduct("Microsoft® .NET")]
[assembly: AssemblyTitle("System.Runtime.Intrinsics")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: AssemblyVersion("6.0.0.0")]
[assembly: TypeForwardedTo(typeof(AdvSimd))]
[assembly: TypeForwardedTo(typeof(System.Runtime.Intrinsics.Arm.Aes))]
[assembly: TypeForwardedTo(typeof(ArmBase))]
[assembly: TypeForwardedTo(typeof(Crc32))]
[assembly: TypeForwardedTo(typeof(Dp))]
[assembly: TypeForwardedTo(typeof(Rdm))]
[assembly: TypeForwardedTo(typeof(Sha1))]
[assembly: TypeForwardedTo(typeof(Sha256))]
[assembly: TypeForwardedTo(typeof(Vector128))]
[assembly: TypeForwardedTo(typeof(Vector128<>))]
[assembly: TypeForwardedTo(typeof(Vector256))]
[assembly: TypeForwardedTo(typeof(Vector256<>))]
[assembly: TypeForwardedTo(typeof(Vector64))]
[assembly: TypeForwardedTo(typeof(Vector64<>))]
[assembly: TypeForwardedTo(typeof(System.Runtime.Intrinsics.X86.Aes))]
[assembly: TypeForwardedTo(typeof(Avx))]
[assembly: TypeForwardedTo(typeof(Avx2))]
[assembly: TypeForwardedTo(typeof(AvxVnni))]
[assembly: TypeForwardedTo(typeof(Bmi1))]
[assembly: TypeForwardedTo(typeof(Bmi2))]
[assembly: TypeForwardedTo(typeof(FloatComparisonMode))]
[assembly: TypeForwardedTo(typeof(Fma))]
[assembly: TypeForwardedTo(typeof(Lzcnt))]
[assembly: TypeForwardedTo(typeof(Pclmulqdq))]
[assembly: TypeForwardedTo(typeof(Popcnt))]
[assembly: TypeForwardedTo(typeof(Sse))]
[assembly: TypeForwardedTo(typeof(Sse2))]
[assembly: TypeForwardedTo(typeof(Sse3))]
[assembly: TypeForwardedTo(typeof(Sse41))]
[assembly: TypeForwardedTo(typeof(Sse42))]
[assembly: TypeForwardedTo(typeof(Ssse3))]
[assembly: TypeForwardedTo(typeof(X86Base))]
[module: SkipLocalsInit]
