Terraria: Terraria.GameContent.TownRoomManager.Load
Load()
void Terraria.GameContent.TownRoomManager.Load (BinaryReader reader) inline
Definition at line 108 of file TownRoomManager.cs.
    {
        Clear();
        int num = reader.ReadInt32();
        for (int i = 0; i < num; i++)
        {
            int num2 = reader.ReadInt32();
            Point item = new Point(reader.ReadInt32(), reader.ReadInt32());
            _roomLocationPairs.Add(Tuple.Create(num2, item));
            _hasRoom[num2] = true;
        }
    }
References Terraria.GameContent.TownRoomManager._hasRoom, Terraria.GameContent.TownRoomManager._roomLocationPairs, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.TownRoomManager.Clear(), System.item, and System.IO.BinaryReader.ReadInt32().