Terraria: Terraria.Localization.NetworkText.DeserializeSubstitutionList
DeserializeSubstitutionList()
void Terraria.Localization.NetworkText.DeserializeSubstitutionList (BinaryReader reader) inline private
Definition at line 121 of file NetworkText.cs.
    {
        if (_mode != 0)
        {
            _substitutions = new NetworkText[reader.ReadByte()];
            for (int i = 0; i < _substitutions.Length; i++)
            {
                _substitutions[i] = Deserialize(reader);
            }
        }
    }
References Terraria.Localization.NetworkText._mode, Terraria.Localization.NetworkText._substitutions, Terraria.Localization.NetworkText.Deserialize(), and System.IO.BinaryReader.ReadByte().
Referenced by Terraria.Localization.NetworkText.Deserialize(), and Terraria.Localization.NetworkText.DeserializeLiteral().