Terraria: Terraria.Localization.NetworkText.Serialize
Serialize()
void Terraria.Localization.NetworkText.Serialize (BinaryWriter writer) inline
    {
        writer.Write((byte)_mode);
        writer.Write(_text);
        SerializeSubstitutionList(writer);
    }
References Terraria.Localization.NetworkText._mode, Terraria.Localization.NetworkText._text, and Terraria.Localization.NetworkText.SerializeSubstitutionList().
Referenced by Terraria.Netplay.KickClient(), Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage(), and Terraria.Localization.NetworkText.SerializeSubstitutionList().