Terraria: Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage
SerializeServerMessage() [1/2]
static NetPacket Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage (NetworkText text, Color color) inline static
Definition at line 19 of file NetTextModule.cs.
    {
        return SerializeServerMessage(text, color, byte.MaxValue);
    }
References Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage().
Referenced by Terraria.Chat.ChatHelper.BroadcastChatMessageAs(), Terraria.Chat.ChatHelper.DisplayMessageOnClient(), Terraria.Chat.ChatHelper.SendChatMessageToClientAs(), and Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage().