Terraria: EmoteBubble.CheckForNPCsToReactToEmoteBubble
CheckForNPCsToReactToEmoteBubble()
static void EmoteBubble.CheckForNPCsToReactToEmoteBubble (int emoteID, Player player) inline static
     {
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = Main.npc[i];
             if (nPC != null && nPC.active && nPC.aiStyle == 7 && nPC.townNPC && !(nPC.ai[0] >= 2f) && ((player.CanBeTalkedTo && player.Distance(nPC.Center) < 200f) || !Collision.CanHitLine(nPC.Top, 0, 0, player.Top, 0, 0)))
             {
                 int direction = (nPC.position.X < player.position.X).ToDirectionInt();
                 nPC.ai[0] = 19f;
                 nPC.ai[1] = 220f;
                 nPC.ai[2] = player.whoAmI;
                 nPC.direction = direction;
                 nPC.netUpdate = true;
             }
         }
     }
References Entity.active, NPC.ai, NPC.aiStyle, Player.CanBeTalkedTo, Collision.CanHitLine(), Entity.Center, Entity.direction, Entity.Distance(), NPC.netUpdate, Main.npc, Entity.position, Entity.Top, NPC.townNPC, and Entity.whoAmI.
Referenced by MessageBuffer.GetData(), MakeLocalPlayerEmote(), EmojiCommand.ProcessOutgoingMessage(), and RockPaperScissorsCommand.ProcessOutgoingMessage().