Terraria: EmoteBubble.PickNPCEmote
PickNPCEmote()
void EmoteBubble.PickNPCEmote (WorldUIAnchor other = null) inline
     {
         Player plr = Main.player[Player.FindClosest(((NPC)anchor.entity).Center, 0, 0)];
         List<int> list = new List<int>();
         bool flag = false;
         for (int i = 0; i < 200; i++)
         {
             if (Main.npc[i].active && Main.npc[i].boss)
             {
                 flag = true;
             }
         }
         if (!flag)
         {
             if (Main.rand.Next(3) == 0)
             {
                 ProbeTownNPCs(list);
             }
             if (Main.rand.Next(3) == 0)
             {
                 ProbeEmotions(list);
             }
             if (Main.rand.Next(3) == 0)
             {
                 ProbeBiomes(list, plr);
             }
             if (Main.rand.Next(2) == 0)
             {
                 ProbeCritters(list);
             }
             if (Main.rand.Next(2) == 0)
             {
                 ProbeItems(list, plr);
             }
             if (Main.rand.Next(5) == 0)
             {
                 ProbeBosses(list);
             }
             if (Main.rand.Next(2) == 0)
             {
                 ProbeDebuffs(list, plr);
             }
             if (Main.rand.Next(2) == 0)
             {
                 ProbeEvents(list);
             }
             if (Main.rand.Next(2) == 0)
             {
                 ProbeWeather(list, plr);
             }
             ProbeExceptions(list, plr, other);
         }
         else
         {
             ProbeCombat(list);
         }
         if (list.Count > 0)
         {
             emote = list[Main.rand.Next(list.Count)];
         }
     }
References Entity.active, anchor, NPC.boss, emote, WorldUIAnchor.entity, Player.FindClosest(), UnifiedRandom.Next(), Main.npc, Main.player, ProbeBiomes(), ProbeBosses(), ProbeCombat(), ProbeCritters(), ProbeDebuffs(), ProbeEmotions(), ProbeEvents(), ProbeExceptions(), ProbeItems(), ProbeTownNPCs(), ProbeWeather(), and Main.rand.
Referenced by NewBubbleNPC().