Terraria: EmoteBubble.MakeLocalPlayerEmote
MakeLocalPlayerEmote()
static void EmoteBubble.MakeLocalPlayerEmote (int emoteId) inline static
     {
         if (Main.netMode == 0)
         {
             NewBubble(emoteId, new WorldUIAnchor(Main.LocalPlayer), 360);
             CheckForNPCsToReactToEmoteBubble(emoteId, Main.LocalPlayer);
         }
         else
         {
             NetMessage.SendData(120, -1, -1, null, Main.myPlayer, emoteId);
         }
     }
References CheckForNPCsToReactToEmoteBubble(), Main.LocalPlayer, Main.myPlayer, Main.netMode, NewBubble(), and NetMessage.SendData().
Referenced by EmoteButton.LeftClick(), LucyAxeMessage.SpawnEmoteBubble(), Player.UpdateHungerBuffs(), and Player.UpdateStarvingState().