Terraria: EmoteBubble.NewBubbleNPC
NewBubbleNPC()
static int EmoteBubble.NewBubbleNPC (WorldUIAnchor bubbleAnchor, int time, WorldUIAnchor other = null) inline static
     {
         if (Main.netMode == 1)
         {
             return -1;
         }
         EmoteBubble emoteBubble = new EmoteBubble(0, bubbleAnchor, time);
         emoteBubble.ID = AssignNewID();
         byID[emoteBubble.ID] = emoteBubble;
         emoteBubble.PickNPCEmote(other);
         if (Main.netMode == 2)
         {
             Tuple<int, int> tuple = SerializeNetAnchor(bubbleAnchor);
             NetMessage.SendData(91, -1, -1, null, emoteBubble.ID, tuple.Item1, tuple.Item2, time, emoteBubble.emote, emoteBubble.metadata);
         }
         return emoteBubble.ID;
     }
References EmoteBubble(), AssignNewID(), byID, emote, ID, metadata, Main.netMode, PickNPCEmote(), NetMessage.SendData(), and SerializeNetAnchor().
Referenced by NPC.FindFrame().