Terraria: System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync
ReadAsync() [3/3]
override async ValueTask< int > System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken) inline virtual
Reimplemented from System.Net.Http.HttpBaseStream.
Definition at line 896 of file HttpConnection.cs.
        {
            CancellationHelper.ThrowIfCancellationRequested(cancellationToken);
            HttpConnection connection = _connection;
            if (connection == null || buffer.Length == 0)
            {
                return 0;
            }
            ValueTask<int> valueTask = connection.ReadBufferedAsync(buffer);
            int num;
            if (valueTask.IsCompletedSuccessfully)
            {
                num = valueTask.Result;
            }
            else
            {
                CancellationTokenRegistration ctr = connection.RegisterCancellation(cancellationToken);
                try
                {
                    num = await valueTask.ConfigureAwait(continueOnCapturedContext: false);
                }
                catch (Exception ex) when (CancellationHelper.ShouldWrapInOperationCanceledException(ex, cancellationToken))
                {
                    throw CancellationHelper.CreateOperationCanceledException(ex, cancellationToken);
                }
                finally
                {
                    ctr.Dispose();
                }
            }
            if (num == 0)
            {
                CancellationHelper.ThrowIfCancellationRequested(cancellationToken);
                _connection = null;
                connection.Dispose();
            }
            return num;
        }
References System.Net.Http.HttpContentStream._connection, System.buffer, System.cancellationToken, System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.Net.Http.HttpConnection.Dispose(), System.Net.Http.HttpConnection.ReadBufferedAsync(), System.Net.Http.HttpConnection.RegisterCancellation(), System.Net.Http.CancellationHelper.ShouldWrapInOperationCanceledException(), and System.Net.Http.CancellationHelper.ThrowIfCancellationRequested().