Terraria: System.Xml.Xsl.XsltOld.CopyOfAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.CopyOfAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 29 of file CopyOfAction.cs.
    {
        switch (frame.State)
        {
        case 0:
        {
            Query valueQuery = processor.GetValueQuery(_selectKey);
            object obj = valueQuery.Evaluate(frame.NodeSet);
            if (obj is XPathNodeIterator)
            {
                processor.PushActionFrame(CopyNodeSetAction.GetAction(), new XPathArrayIterator(valueQuery));
                frame.State = 3;
                break;
            }
            if (obj is XPathNavigator nav)
            {
                processor.PushActionFrame(CopyNodeSetAction.GetAction(), new XPathSingletonIterator(nav));
                frame.State = 3;
                break;
            }
            string text = XmlConvert.ToXPathString(obj);
            if (processor.TextEvent(text))
            {
                frame.Finished();
                break;
            }
            frame.StoredOutput = text;
            frame.State = 2;
            break;
        }
        case 2:
            processor.TextEvent(frame.StoredOutput);
            frame.Finished();
            break;
        case 3:
            frame.Finished();
            break;
        case 1:
            break;
        }
    }
References System.Xml.Xsl.XsltOld.CopyOfAction._selectKey, System.Xml.Dictionary, MS.Internal.Xml.XPath.Query.Evaluate(), System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.Xsl.XsltOld.CopyNodeSetAction.GetAction(), System.Xml.Xsl.XsltOld.ActionFrame.NodeSet, System.obj, System.Xml.Xsl.XsltOld.ActionFrame.State, System.Xml.Xsl.XsltOld.ActionFrame.StoredOutput, System.text, and System.Xml.XmlConvert.ToXPathString().