Terraria: System.Net.Http.HttpConnection.RawConnectionStream.WaitWithConnectionCancellationAsync
WaitWithConnectionCancellationAsync()
static async Task System.Net.Http.HttpConnection.RawConnectionStream.WaitWithConnectionCancellationAsync (ValueTask task, HttpConnection connection, CancellationToken cancellationToken) inline static private
Definition at line 1041 of file HttpConnection.cs.
        {
            CancellationTokenRegistration ctr = connection.RegisterCancellation(cancellationToken);
            try
            {
                await task.ConfigureAwait(continueOnCapturedContext: false);
            }
            catch (Exception ex) when (CancellationHelper.ShouldWrapInOperationCanceledException(ex, cancellationToken))
            {
                throw CancellationHelper.CreateOperationCanceledException(ex, cancellationToken);
            }
            finally
            {
                ctr.Dispose();
            }
        }
References System.cancellationToken, System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.Net.Http.HttpConnection.RegisterCancellation(), System.Net.Http.CancellationHelper.ShouldWrapInOperationCanceledException(), and System.task.
Referenced by System.Net.Http.HttpConnection.RawConnectionStream.FlushAsync(), and System.Net.Http.HttpConnection.RawConnectionStream.WriteAsync().