Terraria: System.Net.Http.HttpConnection.RawConnectionStream.FlushAsync
FlushAsync() [2/2]
override Task System.Net.Http.HttpConnection.RawConnectionStream.FlushAsync (CancellationToken cancellationToken) inline virtual
Reimplemented from System.Net.Http.HttpBaseStream.
Definition at line 1022 of file HttpConnection.cs.
        {
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCanceled(cancellationToken);
            }
            HttpConnection connection = _connection;
            if (connection == null)
            {
                return Task.CompletedTask;
            }
            ValueTask task = connection.FlushAsync(async: true);
            if (!task.IsCompleted)
            {
                return WaitWithConnectionCancellationAsync(task, connection, cancellationToken);
            }
            return task.AsTask();
        }
References System.Net.Http.HttpContentStream._connection, System.cancellationToken, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Net.Http.HttpConnection.FlushAsync(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.task, and System.Net.Http.HttpConnection.RawConnectionStream.WaitWithConnectionCancellationAsync().