Terraria: System.Text.RegularExpressions.MatchCollection.EnsureInitialized
EnsureInitialized()
void System.Text.RegularExpressions.MatchCollection.EnsureInitialized () inline private
Definition at line 180 of file MatchCollection.cs.
    {
        if (!_done)
        {
            GetMatch(int.MaxValue);
        }
    }
References System.Text.RegularExpressions.MatchCollection._done, and System.Text.RegularExpressions.MatchCollection.GetMatch().
Referenced by System.Text.RegularExpressions.MatchCollection.Contains(), System.Text.RegularExpressions.MatchCollection.CopyTo(), System.Text.RegularExpressions.MatchCollection.CopyTo(), and System.Text.RegularExpressions.MatchCollection.IndexOf().