Terraria: System.Text.RegularExpressions.MatchCollection.GetMatch
GetMatch()
Match System.Text.RegularExpressions.MatchCollection.GetMatch (int i) inline private
Definition at line 153 of file MatchCollection.cs.
    {
        if (_matches.Count > i)
        {
            return _matches[i];
        }
        if (_done)
        {
            return null;
        }
        Match match;
        do
        {
            match = _regex.Run(quick: false, _prevlen, _input, 0, _input.Length, _startat);
            if (!match.Success)
            {
                _done = true;
                return null;
            }
            _matches.Add(match);
            _prevlen = match.Length;
            _startat = match._textpos;
        }
        while (_matches.Count <= i);
        return match;
    }
References System.Text.RegularExpressions.MatchCollection._done, System.Text.RegularExpressions.MatchCollection._input, System.Text.RegularExpressions.MatchCollection._matches, System.Text.RegularExpressions.MatchCollection._prevlen, System.Text.RegularExpressions.MatchCollection._regex, System.Text.RegularExpressions.MatchCollection._startat, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.RegularExpressions.i, System.match, and System.Text.RegularExpressions.Regex.Run().
Referenced by System.Text.RegularExpressions.MatchCollection.EnsureInitialized(), and System.Text.RegularExpressions.MatchCollection.Enumerator.MoveNext().