Terraria: DesertHive.PlaceClusters
PlaceClusters()
static void DesertHive.PlaceClusters (DesertDescription description, ClusterGroup clusters) inline static private
     {
         Rectangle hive = description.Hive;
         hive.Inflate(20, 20);
         PostPlacementEffect[,] array = new PostPlacementEffect[hive.Width, hive.Height];
         PlaceClustersArea(description, clusters, hive, array, Point.Zero);
         for (int i = hive.Left; i < hive.Right; i++)
         {
             for (int j = hive.Top; j < hive.Bottom; j++)
             {
                 PostPlacementEffect postPlacementEffect = array[i - hive.Left, j - hive.Top];
                 if (postPlacementEffect.HasFlag(PostPlacementEffect.Smooth))
                 {
                     Tile.SmoothSlope(i, j, applyToNeighbors: false);
                 }
             }
         }
     }
References DesertDescription.Hive, PlaceClustersArea(), and Tile.SmoothSlope().
Referenced by Place().