Terraria: LittleFlyingCritterParticle.Prepare
Prepare()
void LittleFlyingCritterParticle.Prepare (Vector2 position, int duration) inline
     {
         _spawnPosition = position;
         _localPosition = position + Main.rand.NextVector2Circular(4f, 8f);
         _neverGoBelowThis = position.Y + 8f;
         RandomizeVelocity();
         _lifeTimeCounted = 0;
         _lifeTimeTotal = 300 + Main.rand.Next(6) * 60;
     }
References _lifeTimeCounted, _lifeTimeTotal, _localPosition, _neverGoBelowThis, _spawnPosition, UnifiedRandom.Next(), Main.rand, and RandomizeVelocity().
Referenced by ParticleOrchestrator.Spawn_PooFly().