Terraria: AmbientSky.HellBatsGoupSkyEntity.HellBatsGoupSkyEntity
HellBatsGoupSkyEntity()
AmbientSky.HellBatsGoupSkyEntity.HellBatsGoupSkyEntity (Player player, FastRandom random) inline
         {
             VirtualCamera virtualCamera = new VirtualCamera(player);
             Effects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             int num = 100;
             if (Effects == SpriteEffects.FlipHorizontally)
             {
                 Position.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
             }
             else
             {
                 Position.X = virtualCamera.Position.X - (float)num;
             }
             Position.Y = random.NextFloat() * 400f + (float)(Main.UnderworldLayer * 16);
             Depth = random.NextFloat() * 5f + 3f;
             SetPositionInWorldBasedOnScreenSpace(Position);
             Texture = Main.Assets.Request<Texture2D>("Images/Backgrounds/Ambience/HellBat" + random.Next(1, 3), (AssetRequestMode)1);
             Frame = new SpriteFrame(1, 10);
             LifeTime = random.Next(60, 121) * 60;
             OpacityNormalizedTimeToFadeIn = 0.1f;
             OpacityNormalizedTimeToFadeOut = 0.9f;
             BrightnessLerper = 0.2f;
             FinalOpacityMultiplier = 1f;
             FramingSpeed = 4;
             FrameOffset = random.Next(0, Frame.RowCount);
             int num2 = random.Next(Frame.RowCount);
             for (int i = 0; i < num2; i++)
             {
                 NextFrame();
             }
         }
References Main.Assets, AmbientSky.FadingSkyEntity.BrightnessLerper, AmbientSky.SkyEntity.Depth, AmbientSky.SkyEntity.Effects, AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, AmbientSky.SkyEntity.Frame, AmbientSky.FadingSkyEntity.FrameOffset, AmbientSky.FadingSkyEntity.FramingSpeed, AmbientSky.FadingSkyEntity.LifeTime, FastRandom.Next(), FastRandom.NextFloat(), AmbientSky.SkyEntity.NextFrame(), AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, AmbientSky.SkyEntity.Position, VirtualCamera.Position, SpriteFrame.RowCount, AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), VirtualCamera.Size, AmbientSky.SkyEntity.Texture, Main.UnderworldLayer, and Main.WindForVisuals.
Referenced by AmbientSky.HellBatsGoupSkyEntity.CreateGroup().