Terraria: System.Linq.Parallel.AsynchronousChannelMergeEnumerator.MoveNextSlowPath
MoveNextSlowPath()
bool System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >.MoveNextSlowPath () inline private
Definition at line 55 of file AsynchronousChannelMergeEnumerator.cs.
    {
        int num = 0;
        int num2 = _channelIndex;
        int channelIndex;
        while ((channelIndex = _channelIndex) != _channels.Length)
        {
            AsynchronousChannel<T> asynchronousChannel = _channels[channelIndex];
            bool flag = _done[channelIndex];
            if (!flag && asynchronousChannel.TryDequeue(ref _currentElement))
            {
                _channelIndex = (channelIndex + 1) % _channels.Length;
                return true;
            }
            if (!flag && asynchronousChannel.IsDone)
            {
                if (!asynchronousChannel.IsChunkBufferEmpty)
                {
                    bool flag2 = asynchronousChannel.TryDequeue(ref _currentElement);
                    return true;
                }
                _done[channelIndex] = true;
                flag = true;
                asynchronousChannel.Dispose();
            }
            if (flag && ++num == _channels.Length)
            {
                channelIndex = (_channelIndex = _channels.Length);
                break;
            }
            channelIndex = (_channelIndex = (channelIndex + 1) % _channels.Length);
            if (channelIndex != num2)
            {
                continue;
            }
            try
            {
                num = 0;
                for (int i = 0; i < _channels.Length; i++)
                {
                    bool isDone = false;
                    if (!_done[i] && _channels[i].TryDequeue(ref _currentElement, ref isDone))
                    {
                        return true;
                    }
                    if (isDone)
                    {
                        if (!_done[i])
{
                            _done[i] = true;
                        }
                        if (++num == _channels.Length)
{
                            channelIndex = (_channelIndex = _channels.Length);
                            break;
                        }
                    }
                }
                if (channelIndex == _channels.Length)
                {
                    break;
                }
                _consumerEvent.Wait();
                channelIndex = (_channelIndex = _consumerEvent.Value);
                _consumerEvent.Reset();
                num2 = channelIndex;
                num = 0;
                continue;
            }
            finally
            {
                for (int j = 0; j < _channels.Length; j++)
                {
                    if (!_done[j])
                    {
                        _channels[j].DoneWithDequeueWait();
                    }
                }
            }
        }
        _taskGroupState.QueryEnd(userInitiatedDispose: false);
        return false;
    }
References System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >._channelIndex, System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >._channels, System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >._consumerEvent, System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >._currentElement, System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >._done, System.Linq.Parallel.MergeEnumerator< T >._taskGroupState, System.Linq.Parallel.AsynchronousChannel< T >.Dispose(), System.Linq.Parallel.AsynchronousChannel< T >.IsChunkBufferEmpty, System.Linq.Parallel.AsynchronousChannel< T >.IsDone, System.Linq.Parallel.QueryTaskGroupState.QueryEnd(), System.Threading.ManualResetEventSlim.Reset(), System.Linq.Parallel.AsynchronousChannel< T >.TryDequeue(), System.Linq.Parallel.IntValueEvent.Value, and System.Threading.ManualResetEventSlim.Wait().
Referenced by System.Linq.Parallel.AsynchronousChannelMergeEnumerator< T >.MoveNext().