Terraria: System.Numerics.BigInteger.TryGetBytes
TryGetBytes()
byte[] System.Numerics.BigInteger.TryGetBytes (GetBytesMode mode, Span< byte > destination, bool isUnsigned, bool isBigEndian, ref int bytesWritten) inline private
Definition at line 1091 of file BigInteger.cs.
    {
        int sign = _sign;
        if (sign == 0)
        {
            switch (mode)
            {
            case GetBytesMode.AllocateArray:
                return new byte[1];
            case GetBytesMode.Count:
                bytesWritten = 1;
                return null;
            default:
                bytesWritten = 1;
                if (destination.Length != 0)
                {
                    destination[0] = 0;
                    return s_success;
                }
                return null;
            }
        }
        if (isUnsigned && sign < 0)
        {
            throw new OverflowException(System.SR.Overflow_Negative_Unsigned);
        }
        int i = 0;
        uint[] bits = _bits;
        byte b;
        uint num;
        if (bits == null)
        {
            b = (byte)((sign < 0) ? 255u : 0u);
            num = (uint)sign;
        }
        else if (sign == -1)
        {
            b = byte.MaxValue;
            for (; bits[i] == 0; i++)
            {
            }
            num = ~bits[^1];
            if (bits.Length - 1 == i)
            {
                num++;
            }
        }
        else
        {
            b = 0;
            num = bits[^1];
        }
        byte b2;
        int num2;
        if ((b2 = (byte)(num >> 24)) != b)
        {
            num2 = 3;
        }
        else if ((b2 = (byte)(num >> 16)) != b)
        {
            num2 = 2;
        }
        else if ((b2 = (byte)(num >> 8)) != b)
        {
            num2 = 1;
        }
        else
        {
            b2 = (byte)num;
            num2 = 0;
        }
        bool flag = (b2 & 0x80) != (b & 0x80) && !isUnsigned;
        int num3 = num2 + 1 + (flag ? 1 : 0);
        if (bits != null)
        {
            num3 = checked(4 * (bits.Length - 1) + num3);
        }
        byte[] result;
        switch (mode)
        {
        case GetBytesMode.AllocateArray:
            destination = (result = new byte[num3]);
            break;
        case GetBytesMode.Count:
            bytesWritten = num3;
            return null;
        default:
            bytesWritten = num3;
            if (destination.Length < num3)
            {
                return null;
            }
            result = s_success;
            break;
        }
        int num4 = (isBigEndian ? (num3 - 1) : 0);
        int num5 = ((!isBigEndian) ? 1 : (-1));
        if (bits != null)
        {
            for (int j = 0; j < bits.Length - 1; j++)
            {
                uint num6 = bits[j];
                if (sign == -1)
                {
                    num6 = ~num6;
                    if (j <= i)
                    {
                        num6++;
                    }
                }
                destination[num4] = (byte)num6;
                num4 += num5;
                destination[num4] = (byte)(num6 >> 8);
                num4 += num5;
                destination[num4] = (byte)(num6 >> 16);
                num4 += num5;
                destination[num4] = (byte)(num6 >> 24);
                num4 += num5;
            }
        }
        destination[num4] = (byte)num;
        if (num2 != 0)
        {
            num4 += num5;
            destination[num4] = (byte)(num >> 8);
            if (num2 != 1)
            {
                num4 += num5;
                destination[num4] = (byte)(num >> 16);
                if (num2 != 2)
                {
                    num4 += num5;
                    destination[num4] = (byte)(num >> 24);
                }
            }
        }
        if (flag)
        {
            num4 += num5;
            destination[num4] = b;
        }
        return result;
    }
References System.Numerics.BigInteger._bits, System.Numerics.BigInteger._sign, System.destination, System.SR.Overflow_Negative_Unsigned, and System.Numerics.BigInteger.s_success.
Referenced by System.Numerics.BigInteger.GetByteCount(), System.Numerics.BigInteger.ToByteArray(), System.Numerics.BigInteger.TryWriteBytes(), and System.Numerics.BigInteger.TryWriteOrCountBytes().