Terraria: System.Numerics.BigInteger.operator^
operator^()
static BigInteger System.Numerics.BigInteger.operator^ (BigInteger left, BigInteger right) inline static
Definition at line 1658 of file BigInteger.cs.
    {
        if (left._bits == null && right._bits == null)
        {
            return left._sign ^ right._sign;
        }
        Span<uint> scratch = stackalloc uint[32];
        ReadOnlySpan<uint> readOnlySpan = left.ToUInt32Span(scratch);
        scratch = stackalloc uint[32];
        ReadOnlySpan<uint> readOnlySpan2 = right.ToUInt32Span(scratch);
        uint[] array = new uint[Math.Max(readOnlySpan.Length, readOnlySpan2.Length)];
        uint num = ((left._sign < 0) ? uint.MaxValue : 0u);
        uint num2 = ((right._sign < 0) ? uint.MaxValue : 0u);
        for (int i = 0; i < array.Length; i++)
        {
            uint num3 = ((i < readOnlySpan.Length) ? readOnlySpan[i] : num);
            uint num4 = ((i < readOnlySpan2.Length) ? readOnlySpan2[i] : num2);
            array[i] = num3 ^ num4;
        }
        return new BigInteger(array);
    }
References System.Numerics.BigInteger.BigInteger(), System.Numerics.BigInteger._bits, System.Numerics.BigInteger._sign, System.array, System.ReadOnlySpan< T >.Length, System.Math.Max(), and System.Numerics.BigInteger.ToUInt32Span().