Terraria: System.Numerics.BigInteger.Pow
Pow()
static BigInteger System.Numerics.BigInteger.Pow (BigInteger value, int exponent) inline static
Definition at line 831 of file BigInteger.cs.
    {
        if (exponent < 0)
        {
            throw new ArgumentOutOfRangeException("exponent", System.SR.ArgumentOutOfRange_MustBeNonNeg);
        }
        switch (exponent)
        {
        case 0:
            return s_bnOneInt;
        case 1:
            return value;
        default:
        {
            bool flag = value._bits == null;
            if (flag)
            {
                if (value._sign == 1)
                {
                    return value;
                }
                if (value._sign == -1)
                {
                    if ((exponent & 1) == 0)
                    {
                        return s_bnOneInt;
                    }
                    return value;
                }
                if (value._sign == 0)
                {
                    return value;
                }
            }
            uint[] array = (flag ? BigIntegerCalculator.Pow(NumericsHelpers.Abs(value._sign), NumericsHelpers.Abs(exponent)) : BigIntegerCalculator.Pow(value._bits, NumericsHelpers.Abs(exponent)));
            return new BigInteger(array, array, value._sign < 0 && (exponent & 1) != 0);
        }
        }
    }
References System.Numerics.BigInteger.BigInteger(), System.Numerics.NumericsHelpers.Abs(), System.SR.ArgumentOutOfRange_MustBeNonNeg, System.array, System.Numerics.BigIntegerCalculator.Pow(), System.Numerics.BigInteger.s_bnOneInt, and System.value.