Terraria: System.Numerics.BigInteger.operator*
operator*()
static BigInteger System.Numerics.BigInteger.operator* (BigInteger left, BigInteger right) inline static
Definition at line 1868 of file BigInteger.cs.
    {
        bool flag = left._bits == null;
        bool flag2 = right._bits == null;
        if (flag && flag2)
        {
            return (long)left._sign * (long)right._sign;
        }
        if (flag)
        {
            uint[] array = BigIntegerCalculator.Multiply(right._bits, NumericsHelpers.Abs(left._sign));
            return new BigInteger(array, array, (left._sign < 0) ^ (right._sign < 0));
        }
        if (flag2)
        {
            uint[] array2 = BigIntegerCalculator.Multiply(left._bits, NumericsHelpers.Abs(right._sign));
            return new BigInteger(array2, array2, (left._sign < 0) ^ (right._sign < 0));
        }
        if (left._bits == right._bits)
        {
            uint[] array3 = BigIntegerCalculator.Square(left._bits);
            return new BigInteger(array3, array3, (left._sign < 0) ^ (right._sign < 0));
        }
        if (left._bits.Length < right._bits.Length)
        {
            uint[] array4 = BigIntegerCalculator.Multiply(right._bits, left._bits);
            return new BigInteger(array4, array4, (left._sign < 0) ^ (right._sign < 0));
        }
        uint[] array5 = BigIntegerCalculator.Multiply(left._bits, right._bits);
        return new BigInteger(array5, array5, (left._sign < 0) ^ (right._sign < 0));
    }
References System.Numerics.BigInteger.BigInteger(), System.Numerics.BigInteger._bits, System.Numerics.BigInteger._sign, System.Numerics.NumericsHelpers.Abs(), System.array, System.Numerics.BigIntegerCalculator.Multiply(), and System.Numerics.BigIntegerCalculator.Square().