Terraria: System.Numerics.BigInteger.operator<<
operator<<()
static BigInteger System.Numerics.BigInteger.operator<< (BigInteger value, int shift) inline static
Definition at line 1680 of file BigInteger.cs.
    {
        if (shift == 0)
        {
            return value;
        }
        if (shift == int.MinValue)
        {
            return value >> int.MaxValue >> 1;
        }
        if (shift < 0)
        {
            return value >> -shift;
        }
        (int Quotient, int Remainder) tuple = Math.DivRem(shift, 32);
        int item = tuple.Quotient;
        int item2 = tuple.Remainder;
        Span<uint> span = stackalloc uint[1];
        Span<uint> xd = span;
        bool partsForBitManipulation = GetPartsForBitManipulation(ref value, ref xd);
        int num = xd.Length + item + 1;
        uint[] valueArray = null;
        Span<uint> span2 = default(Span<uint>);
        if (num <= 64)
        {
            span = stackalloc uint[64];
            span2 = span.Slice(0, num);
            span = span2.Slice(0, item);
            span.Clear();
        }
        else
        {
            span2 = (valueArray = new uint[num]);
        }
        uint num2 = 0u;
        if (item2 == 0)
        {
            for (int i = 0; i < xd.Length; i++)
            {
                span2[i + item] = xd[i];
            }
        }
        else
        {
            int num3 = 32 - item2;
            for (int j = 0; j < xd.Length; j++)
            {
                uint num4 = xd[j];
                span2[j + item] = (num4 << item2) | num2;
                num2 = num4 >> num3;
            }
        }
        span2[^1] = num2;
        return new BigInteger(span2, valueArray, partsForBitManipulation);
    }
References System.Numerics.BigInteger.BigInteger(), System.Span< T >.Clear(), System.Math.DivRem(), System.Numerics.BigInteger.GetPartsForBitManipulation(), System.item, System.Span< T >.Length, System.Numerics.BigInteger.Remainder(), System.Span< T >.Slice(), and System.value.