Terraria: System.Numerics.BigInteger.BigInteger
BigInteger() [1/12]
System.Numerics.BigInteger.BigInteger (int value) inline
Definition at line 98 of file BigInteger.cs.
    {
        if (value == int.MinValue)
        {
            this = s_bnMinInt;
            return;
        }
        _sign = value;
        _bits = null;
    }
References System.Numerics.BigInteger._bits, System.Numerics.BigInteger._sign, System.Numerics.BigInteger.s_bnMinInt, and System.value.
Referenced by System.Numerics.BigInteger.Add(), System.Numerics.BigInteger.DivRem(), System.Numerics.BigInteger.GreatestCommonDivisor(), System.Numerics.BigInteger.GreatestCommonDivisor(), System.Numerics.BigInteger.ModPow(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator BigInteger(), System.Numerics.BigInteger.operator%(), System.Numerics.BigInteger.operator&(), System.Numerics.BigInteger.operator*(), System.Numerics.BigInteger.operator-(), System.Numerics.BigInteger.operator/(), System.Numerics.BigInteger.operator<<(), System.Numerics.BigInteger.operator>>(), System.Numerics.BigInteger.operator^(), System.Numerics.BigInteger.operator|(), System.Numerics.BigInteger.Pow(), and System.Numerics.BigInteger.Subtract().