Terraria: System.Numerics.BigInteger.ModPow
ModPow()
static BigInteger System.Numerics.BigInteger.ModPow (BigInteger value, BigInteger exponent, BigInteger modulus) inline static
Definition at line 814 of file BigInteger.cs.
    {
        if (exponent.Sign < 0)
        {
            throw new ArgumentOutOfRangeException("exponent", System.SR.ArgumentOutOfRange_MustBeNonNeg);
        }
        bool flag = value._bits == null;
        bool flag2 = exponent._bits == null;
        if (modulus._bits == null)
        {
            uint num = ((flag && flag2) ? BigIntegerCalculator.Pow(NumericsHelpers.Abs(value._sign), NumericsHelpers.Abs(exponent._sign), NumericsHelpers.Abs(modulus._sign)) : (flag ? BigIntegerCalculator.Pow(NumericsHelpers.Abs(value._sign), exponent._bits, NumericsHelpers.Abs(modulus._sign)) : (flag2 ? BigIntegerCalculator.Pow(value._bits, NumericsHelpers.Abs(exponent._sign), NumericsHelpers.Abs(modulus._sign)) : BigIntegerCalculator.Pow(value._bits, exponent._bits, NumericsHelpers.Abs(modulus._sign)))));
            return (value._sign < 0 && !exponent.IsEven) ? (-1 * num) : num;
        }
        uint[] array = ((flag && flag2) ? BigIntegerCalculator.Pow(NumericsHelpers.Abs(value._sign), NumericsHelpers.Abs(exponent._sign), modulus._bits) : (flag ? BigIntegerCalculator.Pow(NumericsHelpers.Abs(value._sign), exponent._bits, modulus._bits) : (flag2 ? BigIntegerCalculator.Pow(value._bits, NumericsHelpers.Abs(exponent._sign), modulus._bits) : BigIntegerCalculator.Pow(value._bits, exponent._bits, modulus._bits))));
        return new BigInteger(array, array, value._sign < 0 && !exponent.IsEven);
    }
References System.Numerics.BigInteger.BigInteger(), System.Numerics.BigInteger._bits, System.Numerics.BigInteger._sign, System.Numerics.NumericsHelpers.Abs(), System.SR.ArgumentOutOfRange_MustBeNonNeg, System.array, System.Numerics.BigInteger.IsEven, System.Numerics.BigIntegerCalculator.Pow(), System.Numerics.BigInteger.Sign, and System.value.
Referenced by System.Security.Cryptography.DSAKeyFormatHelper.ReadDsaPrivateKey().