Terraria: System.Numerics.BigInteger.CompareTo
CompareTo() [2/6]
int System.Numerics.BigInteger.CompareTo (long other) inline
Definition at line 960 of file BigInteger.cs.
    {
        if (_bits == null)
        {
            return ((long)_sign).CompareTo(other);
        }
        int num;
        if ((_sign ^ other) < 0 || (num = _bits.Length) > 2)
        {
            return _sign;
        }
        ulong value = (ulong)((other < 0) ? (-other) : other);
        ulong num2 = ((num == 2) ? NumericsHelpers.MakeUlong(_bits[1], _bits[0]) : _bits[0]);
        return _sign * num2.CompareTo(value);
    }
References System.Numerics.BigInteger._bits, System.Numerics.BigInteger._sign, System.Numerics.NumericsHelpers.MakeUlong(), System.other, and System.value.
Referenced by System.Numerics.BigInteger.Compare(), System.Data.Common.BigIntegerStorage.Compare(), System.Numerics.BigInteger.CompareTo(), System.Numerics.BigInteger.CompareTo(), System.Data.Common.BigIntegerStorage.CompareValueTo(), System.Numerics.BigInteger.Max(), System.Numerics.BigInteger.Min(), System.Numerics.BigInteger.operator<(), System.Numerics.BigInteger.operator<(), System.Numerics.BigInteger.operator<(), System.Numerics.BigInteger.operator<(), System.Numerics.BigInteger.operator<(), System.Numerics.BigInteger.operator<=(), System.Numerics.BigInteger.operator<=(), System.Numerics.BigInteger.operator<=(), System.Numerics.BigInteger.operator<=(), System.Numerics.BigInteger.operator<=(), System.Numerics.BigInteger.operator>(), System.Numerics.BigInteger.operator>(), System.Numerics.BigInteger.operator>(), System.Numerics.BigInteger.operator>(), System.Numerics.BigInteger.operator>(), System.Numerics.BigInteger.operator>=(), System.Numerics.BigInteger.operator>=(), System.Numerics.BigInteger.operator>=(), System.Numerics.BigInteger.operator>=(), and System.Numerics.BigInteger.operator>=().