Terraria: System.Numerics.BigInteger.DivRem
DivRem()
static BigInteger System.Numerics.BigInteger.DivRem (BigInteger dividend, BigInteger divisor, out BigInteger remainder) inline static
Definition at line 665 of file BigInteger.cs.
    {
        bool flag = dividend._bits == null;
        bool flag2 = divisor._bits == null;
        if (flag && flag2)
        {
            (int Quotient, int Remainder) tuple = Math.DivRem(dividend._sign, divisor._sign);
            BigInteger bigInteger = tuple.Quotient;
            BigInteger bigInteger2 = tuple.Remainder;
            BigInteger result = bigInteger;
            remainder = bigInteger2;
            return result;
        }
        if (flag)
        {
            remainder = dividend;
            return s_bnZeroInt;
        }
        if (flag2)
        {
            uint remainder2;
            uint[] array = BigIntegerCalculator.Divide(dividend._bits, NumericsHelpers.Abs(divisor._sign), out remainder2);
            remainder = ((dividend._sign < 0) ? (-1 * remainder2) : remainder2);
            return new BigInteger(array, array, (dividend._sign < 0) ^ (divisor._sign < 0));
        }
        if (dividend._bits.Length < divisor._bits.Length)
        {
            remainder = dividend;
            return s_bnZeroInt;
        }
        uint[] remainder3;
        uint[] array2 = BigIntegerCalculator.Divide(dividend._bits, divisor._bits, out remainder3);
        remainder = new BigInteger(remainder3, remainder3, dividend._sign < 0);
        return new BigInteger(array2, array2, (dividend._sign < 0) ^ (divisor._sign < 0));
    }
References System.Numerics.BigInteger.BigInteger(), System.Numerics.BigInteger._bits, System.Numerics.BigInteger._sign, System.Numerics.NumericsHelpers.Abs(), System.array, System.Numerics.BigIntegerCalculator.Divide(), System.Math.DivRem(), System.Numerics.BigInteger.Remainder(), and System.Numerics.BigInteger.s_bnZeroInt.