Terraria: DelegateMethods.SpreadLightOpen_StopForSolids
SpreadLightOpen_StopForSolids()
static bool DelegateMethods.SpreadLightOpen_StopForSolids (int x, int y) inline static
     {
         if (Vector2.Distance(v2_1, new Vector2(x, y)) > f_1)
         {
             return false;
         }
         if (!Main.tile[x, y].active() || Main.tile[x, y].inActive() || Main.tileSolidTop[Main.tile[x, y].type] || !Main.tileSolid[Main.tile[x, y].type])
         {
             Vector3 vector = v3_1;
             new Vector2(x, y);
             Lighting.AddLight(x, y, vector.X, vector.Y, vector.Z);
             return true;
         }
         return false;
     }
References Tile.active(), Lighting.AddLight(), f_1, Tile.inActive(), Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.type, v2_1, and v3_1.
Referenced by Player.ItemCheck_EmitHeldItemLight(), and Projectile.ProjLight().