Terraria: DelegateMethods.EmitGolfCartDust_StopForSolids
EmitGolfCartDust_StopForSolids()
static bool DelegateMethods.EmitGolfCartDust_StopForSolids (int x, int y) inline static
     {
         if (x < 0 || x >= Main.maxTilesX || y < 0 || y >= Main.maxTilesY)
         {
             return false;
         }
         if (Main.tile[x, y] == null)
         {
             return false;
         }
         if (!Main.tile[x, y].active() || Main.tile[x, y].inActive() || Main.tileSolidTop[Main.tile[x, y].type] || !Main.tileSolid[Main.tile[x, y].type])
         {
             Dust.NewDustPerfect(new Vector2(x * 16 + 8, y * 16 + 8), 260, Vector2.UnitY * -0.2f);
             return true;
         }
         return false;
     }
References Tile.active(), Tile.inActive(), Main.maxTilesX, Main.maxTilesY, Dust.NewDustPerfect(), Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.