Terraria: DelegateMethods.CheckStopForSolids
CheckStopForSolids()
static bool DelegateMethods.CheckStopForSolids (int x, int y) inline static
     {
         if (x < 0 || x >= Main.maxTilesX || y < 0 || y >= Main.maxTilesY)
         {
             return false;
         }
         if (Main.tile[x, y] == null)
         {
             return false;
         }
         if (Main.tile[x, y].active() && !Main.tile[x, y].inActive() && !Main.tileSolidTop[Main.tile[x, y].type] && Main.tileSolid[Main.tile[x, y].type])
         {
             CheckResultOut = true;
             return false;
         }
         return true;
     }
References Tile.active(), CheckResultOut, Tile.inActive(), Main.maxTilesX, Main.maxTilesY, Main.tile, Main.tileSolid, Main.tileSolidTop, and Tile.type.
Referenced by WorldGen.IsSafeFromRain().