Terraria: DelegateMethods.CutTiles
CutTiles()
static bool DelegateMethods.CutTiles (int x, int y) inline static
     {
         if (!WorldGen.InWorld(x, y, 1))
         {
             return false;
         }
         if (Main.tile[x, y] == null)
         {
             return false;
         }
         if (!Main.tileCut[Main.tile[x, y].type])
         {
             return true;
         }
         if (tileCutIgnore[Main.tile[x, y].type])
         {
             return true;
         }
         if (WorldGen.CanCutTile(x, y, tilecut_0))
         {
             WorldGen.KillTile(x, y);
             if (Main.netMode != 0)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, x, y);
             }
         }
         return true;
     }
References WorldGen.CanCutTile(), WorldGen.InWorld(), WorldGen.KillTile(), Main.netMode, NetMessage.SendData(), Main.tile, Main.tileCut, tilecut_0, tileCutIgnore, and Tile.type.
Referenced by Projectile.CutTiles().