Terraria: CaptureInterface.ModeDragBounds.DrawMarkedArea
DrawMarkedArea()
void CaptureInterface.ModeDragBounds.DrawMarkedArea (SpriteBatch sb) inline
         {
             if (!EdgeAPinned || !EdgeBPinned)
             {
                 return;
             }
             int num = Math.Min(EdgeA.X, EdgeB.X);
             int num2 = Math.Min(EdgeA.Y, EdgeB.Y);
             int num3 = Math.Abs(EdgeA.X - EdgeB.X);
             int num4 = Math.Abs(EdgeA.Y - EdgeB.Y);
             Rectangle result;
             if (!Main.mapFullscreen)
             {
                 Rectangle value = Main.ReverseGravitySupport(new Rectangle(num * 16, num2 * 16, (num3 + 1) * 16, (num4 + 1) * 16));
                 Rectangle value2 = Main.ReverseGravitySupport(new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth + 1, Main.screenHeight + 1));
                 Rectangle.Intersect(ref value2, ref value, out result);
                 if (result.Width == 0 || result.Height == 0)
                 {
                     return;
                 }
                 result.Offset(-value2.X, -value2.Y);
             }
             else
             {
                 GetMapCoords(num, num2, 1, out var result2);
                 GetMapCoords(num + num3 + 1, num2 + num4 + 1, 1, out var result3);
                 Rectangle value = new Rectangle(result2.X, result2.Y, result3.X - result2.X, result3.Y - result2.Y);
                 Rectangle value2 = new Rectangle(0, 0, Main.screenWidth + 1, Main.screenHeight + 1);
                 Rectangle.Intersect(ref value2, ref value, out result);
                 if (result.Width == 0 || result.Height == 0)
                 {
                     return;
                 }
                 result.Offset(-value2.X, -value2.Y);
             }
             sb.Draw(TextureAssets.MagicPixel.Value, result, Settings.MarkedAreaColor);
             Rectangle rectangle = Rectangle.Empty;
             for (int i = 0; i < 2; i++)
             {
                 if (currentAim != i)
                 {
                     DrawBound(sb, new Rectangle(result.X, result.Y + ((i == 1) ? result.Height : (-2)), result.Width, 2), 0);
                 }
                 else
                 {
                     rectangle = new Rectangle(result.X, result.Y + ((i == 1) ? result.Height : (-2)), result.Width, 2);
                 }
                 if (currentAim != i + 2)
                 {
                     DrawBound(sb, new Rectangle(result.X + ((i == 1) ? result.Width : (-2)), result.Y, 2, result.Height), 0);
                 }
                 else
                 {
                     rectangle = new Rectangle(result.X + ((i == 1) ? result.Width : (-2)), result.Y, 2, result.Height);
                 }
             }
             if (rectangle != Rectangle.Empty)
             {
                 DrawBound(sb, rectangle, 1 + dragging.ToInt());
             }
         }
References CaptureInterface.ModeDragBounds.currentAim, CaptureInterface.ModeDragBounds.dragging, CaptureInterface.ModeDragBounds.DrawBound(), CaptureInterface.EdgeA, CaptureInterface.EdgeAPinned, CaptureInterface.EdgeB, CaptureInterface.EdgeBPinned, CaptureInterface.GetMapCoords(), TextureAssets.MagicPixel, Main.mapFullscreen, CaptureInterface.Settings.MarkedAreaColor, Main.ReverseGravitySupport(), Main.screenHeight, Main.screenPosition, Main.screenWidth, and Asset< T >.Value.
Referenced by CaptureInterface.ModeDragBounds.Draw().