Terraria: System.Runtime.InteropServices.ComEventsMethod.AddDelegate
AddDelegate()
void System.Runtime.InteropServices.ComEventsMethod.AddDelegate (Delegate d, bool wrapArgs = false) inline
Definition at line 130 of file ComEventsMethod.cs.
    {
        lock (_delegateWrappers)
        {
            foreach (DelegateWrapper delegateWrapper in _delegateWrappers)
            {
                if (delegateWrapper.Delegate.GetType() == d.GetType() && delegateWrapper.WrapArgs == wrapArgs)
                {
                    delegateWrapper.Delegate = Delegate.Combine(delegateWrapper.Delegate, d);
                    return;
                }
            }
            DelegateWrapper item = new DelegateWrapper(d, wrapArgs);
            _delegateWrappers.Add(item);
        }
    }
References System.Runtime.InteropServices.ComEventsMethod._delegateWrappers, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Delegate.Combine(), and System.item.
Referenced by System.Runtime.InteropServices.ComEventsHelper.Combine().