Terraria: System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression
RewriteExpression()
Result System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression (Expression node, Stack stack) inline private
Definition at line 1210 of file StackSpiller.cs.
    {
        if (node == null)
        {
            return new Result(RewriteAction.None, null);
        }
        if (!_guard.TryEnterOnCurrentStack())
        {
            return _guard.RunOnEmptyStack((StackSpiller @this, Expression n, Stack s) => @this.RewriteExpression(n, s), this, node, stack);
        }
        Result result;
        switch (node.NodeType)
        {
        case ExpressionType.Add:
        case ExpressionType.AddChecked:
        case ExpressionType.And:
        case ExpressionType.ArrayIndex:
        case ExpressionType.Divide:
        case ExpressionType.Equal:
        case ExpressionType.ExclusiveOr:
        case ExpressionType.GreaterThan:
        case ExpressionType.GreaterThanOrEqual:
        case ExpressionType.LeftShift:
        case ExpressionType.LessThan:
        case ExpressionType.LessThanOrEqual:
        case ExpressionType.Modulo:
        case ExpressionType.Multiply:
        case ExpressionType.MultiplyChecked:
        case ExpressionType.NotEqual:
        case ExpressionType.Or:
        case ExpressionType.Power:
        case ExpressionType.RightShift:
        case ExpressionType.Subtract:
        case ExpressionType.SubtractChecked:
            result = RewriteBinaryExpression(node, stack);
            break;
        case ExpressionType.AndAlso:
        case ExpressionType.Coalesce:
        case ExpressionType.OrElse:
            result = RewriteLogicalBinaryExpression(node, stack);
            break;
        case ExpressionType.Assign:
            result = RewriteAssignBinaryExpression(node, stack);
            break;
        case ExpressionType.ArrayLength:
        case ExpressionType.Convert:
        case ExpressionType.ConvertChecked:
        case ExpressionType.Negate:
        case ExpressionType.UnaryPlus:
        case ExpressionType.NegateChecked:
        case ExpressionType.Not:
        case ExpressionType.TypeAs:
        case ExpressionType.Decrement:
        case ExpressionType.Increment:
        case ExpressionType.Unbox:
        case ExpressionType.OnesComplement:
        case ExpressionType.IsTrue:
        case ExpressionType.IsFalse:
            result = RewriteUnaryExpression(node, stack);
            break;
        case ExpressionType.Throw:
            result = RewriteThrowUnaryExpression(node, stack);
            break;
        case ExpressionType.Call:
            result = RewriteMethodCallExpression(node, stack);
            break;
        case ExpressionType.Conditional:
            result = RewriteConditionalExpression(node, stack);
            break;
        case ExpressionType.Invoke:
            result = RewriteInvocationExpression(node, stack);
            break;
        case ExpressionType.Lambda:
            result = RewriteLambdaExpression(node);
            break;
        case ExpressionType.ListInit:
            result = RewriteListInitExpression(node, stack);
            break;
        case ExpressionType.MemberAccess:
            result = RewriteMemberExpression(node, stack);
            break;
        case ExpressionType.MemberInit:
            result = RewriteMemberInitExpression(node, stack);
            break;
        case ExpressionType.New:
            result = RewriteNewExpression(node, stack);
            break;
        case ExpressionType.NewArrayInit:
        case ExpressionType.NewArrayBounds:
            result = RewriteNewArrayExpression(node, stack);
            break;
        case ExpressionType.TypeIs:
        case ExpressionType.TypeEqual:
            result = RewriteTypeBinaryExpression(node, stack);
            break;
        case ExpressionType.Block:
            result = RewriteBlockExpression(node, stack);
            break;
        case ExpressionType.Dynamic:
            result = RewriteDynamicExpression(node);
            break;
        case ExpressionType.Extension:
            result = RewriteExtensionExpression(node, stack);
            break;
        case ExpressionType.Goto:
            result = RewriteGotoExpression(node, stack);
            break;
        case ExpressionType.Index:
            result = RewriteIndexExpression(node, stack);
            break;
        case ExpressionType.Label:
            result = RewriteLabelExpression(node, stack);
            break;
        case ExpressionType.Loop:
            result = RewriteLoopExpression(node, stack);
            break;
        case ExpressionType.Switch:
            result = RewriteSwitchExpression(node, stack);
            break;
        case ExpressionType.Try:
            result = RewriteTryExpression(node, stack);
            break;
        case ExpressionType.AddAssign:
        case ExpressionType.AndAssign:
        case ExpressionType.DivideAssign:
        case ExpressionType.ExclusiveOrAssign:
        case ExpressionType.LeftShiftAssign:
        case ExpressionType.ModuloAssign:
        case ExpressionType.MultiplyAssign:
        case ExpressionType.OrAssign:
        case ExpressionType.PowerAssign:
        case ExpressionType.RightShiftAssign:
        case ExpressionType.SubtractAssign:
        case ExpressionType.AddAssignChecked:
        case ExpressionType.MultiplyAssignChecked:
        case ExpressionType.SubtractAssignChecked:
        case ExpressionType.PreIncrementAssign:
        case ExpressionType.PreDecrementAssign:
        case ExpressionType.PostIncrementAssign:
        case ExpressionType.PostDecrementAssign:
            result = RewriteReducibleExpression(node, stack);
            break;
        case ExpressionType.Constant:
        case ExpressionType.Parameter:
        case ExpressionType.Quote:
        case ExpressionType.DebugInfo:
        case ExpressionType.Default:
        case ExpressionType.RuntimeVariables:
            result = new Result(RewriteAction.None, node);
            break;
        default:
            result = RewriteExpression(node.ReduceAndCheck(), stack);
            if (result.Action == RewriteAction.None)
            {
                result = new Result(result.Action | RewriteAction.Copy, result.Node);
            }
            break;
        }
        return result;
    }
References System.Linq.Expressions.Compiler.StackSpiller._guard, System.Linq.Expressions.Compiler.StackSpiller.Result.Action, System.Linq.Expressions.Compiler.StackSpiller.Result.Node, System.Linq.Expressions.Compiler.StackSpiller.RewriteAssignBinaryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteBinaryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteBlockExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteConditionalExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteDynamicExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteGotoExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteIndexExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteInvocationExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteLabelExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteListInitExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteLogicalBinaryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteLoopExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteNewArrayExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteNewExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteReducibleExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteSwitchExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteThrowUnaryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteTryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteTypeBinaryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteUnaryExpression(), System.s, and System.Linq.Expressions.StackGuard.TryEnterOnCurrentStack().
Referenced by System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(), System.Linq.Expressions.Compiler.StackSpiller.RewriteBlockExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteConditionalExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(), System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteLabelExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteListInitExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteLogicalBinaryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteLoopExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteReducibleExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteSwitchExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteTryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteTypeBinaryExpression(), System.Linq.Expressions.Compiler.StackSpiller.RewriteUnaryExpression(), and System.Linq.Expressions.Compiler.StackSpiller.RewriteVariableAssignment().