Terraria: System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression
RewriteMemberInitExpression()
Result System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression (Expression expr, Stack stack) inline private
Definition at line 930 of file StackSpiller.cs.
    {
        MemberInitExpression memberInitExpression = (MemberInitExpression)expr;
        Result result = RewriteExpression(memberInitExpression.NewExpression, stack);
        Expression node = result.Node;
        RewriteAction rewriteAction = result.Action;
        ReadOnlyCollection<MemberBinding> bindings = memberInitExpression.Bindings;
        int count = bindings.Count;
        BindingRewriter[] array = new BindingRewriter[count];
        for (int i = 0; i < count; i++)
        {
            MemberBinding binding = bindings[i];
            rewriteAction |= (array[i] = BindingRewriter.Create(binding, this, Stack.NonEmpty)).Action;
        }
        switch (rewriteAction)
        {
        case RewriteAction.Copy:
        {
            MemberBinding[] array2 = new MemberBinding[count];
            for (int k = 0; k < count; k++)
            {
                array2[k] = array[k].AsBinding();
            }
            expr = new MemberInitExpression((NewExpression)node, new TrueReadOnlyCollection<MemberBinding>(array2));
            break;
        }
        case RewriteAction.SpillStack:
        {
            bool flag = IsRefInstance(memberInitExpression.NewExpression);
            System.Collections.Generic.ArrayBuilder<Expression> expressions = new System.Collections.Generic.ArrayBuilder<Expression>(count + 2 + (flag ? 1 : 0));
            ParameterExpression parameterExpression = MakeTemp(node.Type);
            expressions.UncheckedAdd(new AssignBinaryExpression(parameterExpression, node));
            ParameterExpression parameterExpression2 = parameterExpression;
            if (flag)
            {
                parameterExpression2 = MakeTemp(parameterExpression.Type.MakeByRefType());
                expressions.UncheckedAdd(new ByRefAssignBinaryExpression(parameterExpression2, parameterExpression));
            }
            for (int j = 0; j < count; j++)
            {
                BindingRewriter bindingRewriter = array[j];
                Expression item = bindingRewriter.AsExpression(parameterExpression2);
                expressions.UncheckedAdd(item);
            }
            expressions.UncheckedAdd(parameterExpression);
            expr = MakeBlock(expressions);
            break;
        }
        default:
            throw ContractUtils.Unreachable;
        case RewriteAction.None:
            break;
        }
        return new Result(rewriteAction, expr);
    }
References System.Linq.Expressions.Compiler.StackSpiller.Result.Action, System.array, System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(), System.Linq.Expressions.Compiler.StackSpiller.IsRefInstance(), System.item, System.Linq.Expressions.Compiler.StackSpiller.MakeBlock(), System.Linq.Expressions.Compiler.StackSpiller.MakeTemp(), System.Linq.Expressions.Compiler.StackSpiller.Result.Node, System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(), and System.Dynamic.Utils.ContractUtils.Unreachable.
Referenced by System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression().