Terraria: System.Linq.Expressions.Compiler.StackSpiller.RewriteSwitchExpression
RewriteSwitchExpression()
Result System.Linq.Expressions.Compiler.StackSpiller.RewriteSwitchExpression (Expression expr, Stack stack) inline private
Definition at line 1056 of file StackSpiller.cs.
    {
        SwitchExpression switchExpression = (SwitchExpression)expr;
        Result result = RewriteExpressionFreeTemps(switchExpression.SwitchValue, stack);
        RewriteAction rewriteAction = result.Action;
        ReadOnlyCollection<SwitchCase> readOnlyCollection = switchExpression.Cases;
        SwitchCase[] array = null;
        for (int i = 0; i < readOnlyCollection.Count; i++)
        {
            SwitchCase switchCase = readOnlyCollection[i];
            Expression[] array2 = null;
            ReadOnlyCollection<Expression> readOnlyCollection2 = switchCase.TestValues;
            for (int j = 0; j < readOnlyCollection2.Count; j++)
            {
                Result result2 = RewriteExpression(readOnlyCollection2[j], stack);
                rewriteAction |= result2.Action;
                if (array2 == null && result2.Action != 0)
                {
                    array2 = Clone(readOnlyCollection2, j);
                }
                if (array2 != null)
                {
                    array2[j] = result2.Node;
                }
            }
            Result result3 = RewriteExpression(switchCase.Body, stack);
            rewriteAction |= result3.Action;
            if (result3.Action != 0 || array2 != null)
            {
                if (array2 != null)
                {
                    readOnlyCollection2 = new ReadOnlyCollection<Expression>(array2);
                }
                switchCase = new SwitchCase(result3.Node, readOnlyCollection2);
                if (array == null)
                {
                    array = Clone(readOnlyCollection, i);
                }
            }
            if (array != null)
            {
                array[i] = switchCase;
            }
        }
        Result result4 = RewriteExpression(switchExpression.DefaultBody, stack);
        rewriteAction |= result4.Action;
        if (rewriteAction != 0)
        {
            if (array != null)
            {
                readOnlyCollection = new ReadOnlyCollection<SwitchCase>(array);
            }
            expr = new SwitchExpression(switchExpression.Type, result.Node, result4.Node, switchExpression.Comparison, readOnlyCollection);
        }
        return new Result(rewriteAction, expr);
    }
References System.Linq.Expressions.Compiler.StackSpiller.Result.Action, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Compiler.StackSpiller.Result.Node, System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(), and System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps().
Referenced by System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression().