Terraria: System.Linq.Expressions.Compiler.StackSpiller.RewriteConditionalExpression
RewriteConditionalExpression()
Result System.Linq.Expressions.Compiler.StackSpiller.RewriteConditionalExpression (Expression expr, Stack stack) inline private
Definition at line 681 of file StackSpiller.cs.
    {
        ConditionalExpression conditionalExpression = (ConditionalExpression)expr;
        Result result = RewriteExpression(conditionalExpression.Test, stack);
        Result result2 = RewriteExpression(conditionalExpression.IfTrue, stack);
        Result result3 = RewriteExpression(conditionalExpression.IfFalse, stack);
        RewriteAction rewriteAction = result.Action | result2.Action | result3.Action;
        if (rewriteAction != 0)
        {
            expr = ConditionalExpression.Make(result.Node, result2.Node, result3.Node, conditionalExpression.Type);
        }
        return new Result(rewriteAction, expr);
    }
References System.Linq.Expressions.ConditionalExpression.Make(), System.Linq.Expressions.Compiler.StackSpiller.Result.Node, and System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression().
Referenced by System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression().