Terraria: System.Linq.Expressions.Compiler.StackSpiller.RewriteTryExpression
RewriteTryExpression()
Result System.Linq.Expressions.Compiler.StackSpiller.RewriteTryExpression (Expression expr, Stack stack) inline private
Definition at line 1113 of file StackSpiller.cs.
    {
        TryExpression tryExpression = (TryExpression)expr;
        Result result = RewriteExpression(tryExpression.Body, Stack.Empty);
        ReadOnlyCollection<CatchBlock> readOnlyCollection = tryExpression.Handlers;
        CatchBlock[] array = null;
        RewriteAction rewriteAction = result.Action;
        if (readOnlyCollection != null)
        {
            for (int i = 0; i < readOnlyCollection.Count; i++)
            {
                RewriteAction rewriteAction2 = result.Action;
                CatchBlock catchBlock = readOnlyCollection[i];
                Expression filter = catchBlock.Filter;
                if (catchBlock.Filter != null)
                {
                    Result result2 = RewriteExpression(catchBlock.Filter, Stack.Empty);
                    rewriteAction |= result2.Action;
                    rewriteAction2 |= result2.Action;
                    filter = result2.Node;
                }
                Result result3 = RewriteExpression(catchBlock.Body, Stack.Empty);
                rewriteAction |= result3.Action;
                if ((rewriteAction2 | result3.Action) != 0)
                {
                    catchBlock = Expression.MakeCatchBlock(catchBlock.Test, catchBlock.Variable, result3.Node, filter);
                    if (array == null)
                    {
                        array = Clone(readOnlyCollection, i);
                    }
                }
                if (array != null)
                {
                    array[i] = catchBlock;
                }
            }
        }
        Result result4 = RewriteExpression(tryExpression.Fault, Stack.Empty);
        rewriteAction |= result4.Action;
        Result result5 = RewriteExpression(tryExpression.Finally, Stack.Empty);
        rewriteAction |= result5.Action;
        if (stack != 0)
        {
            rewriteAction = RewriteAction.SpillStack;
        }
        if (rewriteAction != 0)
        {
            if (array != null)
            {
                readOnlyCollection = new ReadOnlyCollection<CatchBlock>(array);
            }
            expr = new TryExpression(tryExpression.Type, result.Node, result5.Node, result4.Node, readOnlyCollection);
        }
        return new Result(rewriteAction, expr);
    }
References System.Linq.Expressions.Compiler.StackSpiller.Result.Action, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Expression< TDelegate >.MakeCatchBlock(), System.Linq.Expressions.Compiler.StackSpiller.Result.Node, and System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression().
Referenced by System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression().