Terraria: System.Xml.Xsl.XsltOld.ChooseAction.CompileConditions
CompileConditions()
void System.Xml.Xsl.XsltOld.ChooseAction.CompileConditions (Compiler compiler) inline private
Definition at line 17 of file ChooseAction.cs.
    {
        NavigatorInput input = compiler.Input;
        bool flag = false;
        bool flag2 = false;
        do
        {
            switch (input.NodeType)
            {
            case XPathNodeType.Element:
            {
                compiler.PushNamespaceScope();
                string namespaceURI = input.NamespaceURI;
                string localName = input.LocalName;
                if (Ref.Equal(namespaceURI, input.Atoms.UriXsl))
                {
                    IfAction ifAction = null;
                    if (Ref.Equal(localName, input.Atoms.When))
                    {
                        if (flag2)
{
                            throw XsltException.Create(System.SR.Xslt_WhenAfterOtherwise);
                        }
                        ifAction = compiler.CreateIfAction(IfAction.ConditionType.ConditionWhen);
                        flag = true;
                    }
                    else
                    {
                        if (!Ref.Equal(localName, input.Atoms.Otherwise))
{
                            throw compiler.UnexpectedKeyword();
                        }
                        if (flag2)
{
                            throw XsltException.Create(System.SR.Xslt_DupOtherwise);
                        }
                        ifAction = compiler.CreateIfAction(IfAction.ConditionType.ConditionOtherwise);
                        flag2 = true;
                    }
                    AddAction(ifAction);
                    compiler.PopScope();
                    break;
                }
                throw compiler.UnexpectedKeyword();
            }
            default:
                throw XsltException.Create(System.SR.Xslt_InvalidContents, "choose");
            case XPathNodeType.SignificantWhitespace:
            case XPathNodeType.Whitespace:
            case XPathNodeType.ProcessingInstruction:
            case XPathNodeType.Comment:
                break;
            }
        }
        while (compiler.Advance());
        if (!flag)
        {
            throw XsltException.Create(System.SR.Xslt_NoWhen);
        }
    }
References System.Xml.Xsl.XsltOld.ContainerAction.AddAction(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.input, System.Xml.Xsl.XsltOld.NavigatorInput.NamespaceURI, System.SR.Xslt_DupOtherwise, System.SR.Xslt_InvalidContents, System.SR.Xslt_NoWhen, and System.SR.Xslt_WhenAfterOtherwise.
Referenced by System.Xml.Xsl.XsltOld.ChooseAction.Compile().