Terraria: System.IO.IsolatedStorage.Helper.GetRandomDirectory
GetRandomDirectory()
static string System.IO.IsolatedStorage.Helper.GetRandomDirectory (string rootDirectory, IsolatedStorageScope scope) inline static package
Definition at line 105 of file Helper.cs.
    {
        string text = GetExistingRandomDirectory(rootDirectory);
        if (string.IsNullOrEmpty(text))
        {
            using Mutex mutex = CreateMutexNotOwned(rootDirectory);
            if (!mutex.WaitOne())
            {
                throw new IsolatedStorageException(System.SR.IsolatedStorage_Init);
            }
            try
            {
                text = GetExistingRandomDirectory(rootDirectory);
                if (string.IsNullOrEmpty(text))
                {
                    text = Path.Combine(rootDirectory, Path.GetRandomFileName(), Path.GetRandomFileName());
                    CreateDirectory(text, scope);
                }
            }
            finally
            {
                mutex.ReleaseMutex();
            }
        }
        return text;
    }
References System.IO.Path.Combine(), System.IO.IsolatedStorage.Helper.CreateDirectory(), System.IO.IsolatedStorage.Helper.CreateMutexNotOwned(), System.IO.IsolatedStorage.Helper.GetExistingRandomDirectory(), System.IO.Path.GetRandomFileName(), System.SR.IsolatedStorage_Init, and System.text.
Referenced by System.IO.IsolatedStorage.Helper.GetRootDirectory().