Terraria: System.IO.IsolatedStorage.Helper.CreateDirectory
CreateDirectory()
static void System.IO.IsolatedStorage.Helper.CreateDirectory (string path, IsolatedStorageScope scope) inline static package
Definition at line 164 of file Helper.cs.
    {
        if (!Directory.Exists(path))
        {
            DirectoryInfo directoryInfo = Directory.CreateDirectory(path);
            if (IsMachine(scope))
            {
                DirectorySecurity directorySecurity = new DirectorySecurity();
                directorySecurity.SetAccessRuleProtection(isProtected: true, preserveInheritance: false);
                directorySecurity.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(WellKnownSidType.WorldSid, null), FileSystemRights.Read | FileSystemRights.Write, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None, AccessControlType.Allow));
                directorySecurity.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(WellKnownSidType.BuiltinAdministratorsSid, null), FileSystemRights.FullControl, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None, AccessControlType.Allow));
                directorySecurity.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(WellKnownSidType.CreatorOwnerSid, null), FileSystemRights.FullControl, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None, AccessControlType.Allow));
                directoryInfo.SetAccessControl(directorySecurity);
            }
        }
    }
References System.Security.AccessControl.FileSystemSecurity.AddAccessRule(), System.IO.Directory.CreateDirectory(), System.IO.Directory.Exists(), System.IO.IsolatedStorage.Helper.IsMachine(), and System.Security.AccessControl.ObjectSecurity< T >.SetAccessRuleProtection().
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile(), and System.IO.IsolatedStorage.Helper.GetRandomDirectory().