Terraria: System.IO.IsolatedStorage.Helper.GetRootDirectory
GetRootDirectory()
static string System.IO.IsolatedStorage.Helper.GetRootDirectory (IsolatedStorageScope scope) inline static package
Definition at line 18 of file Helper.cs.
    {
        if (IsRoaming(scope))
        {
            if (string.IsNullOrEmpty(s_roamingUserRootDirectory))
            {
                s_roamingUserRootDirectory = GetDataDirectory(scope);
            }
            return s_roamingUserRootDirectory;
        }
        if (IsMachine(scope))
        {
            if (string.IsNullOrEmpty(s_machineRootDirectory))
            {
                s_machineRootDirectory = GetRandomDirectory(GetDataDirectory(scope), scope);
            }
            return s_machineRootDirectory;
        }
        if (string.IsNullOrEmpty(s_userRootDirectory))
        {
            s_userRootDirectory = GetRandomDirectory(GetDataDirectory(scope), scope);
        }
        return s_userRootDirectory;
    }
References System.IO.IsolatedStorage.Helper.GetDataDirectory(), System.IO.IsolatedStorage.Helper.GetRandomDirectory(), System.IO.IsolatedStorage.Helper.IsMachine(), System.IO.IsolatedStorage.Helper.IsRoaming(), System.IO.IsolatedStorage.Helper.s_machineRootDirectory, System.IO.IsolatedStorage.Helper.s_roamingUserRootDirectory, and System.IO.IsolatedStorage.Helper.s_userRootDirectory.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile(), and System.IO.IsolatedStorage.IsolatedStorageFile.Remove().