Terraria: System.IO.IsolatedStorage.Helper.GetDefaultIdentityAndHash
GetDefaultIdentityAndHash()
static void System.IO.IsolatedStorage.Helper.GetDefaultIdentityAndHash (out object identity, out string hash, char separator) inline static package
Definition at line 76 of file Helper.cs.
    {
        Assembly entryAssembly = Assembly.GetEntryAssembly();
        string text = null;
        if (entryAssembly != null)
        {
            AssemblyName name = entryAssembly.GetName();
            hash = IdentityHelper.GetNormalizedStrongNameHash(name);
            if (hash != null)
            {
                hash = "StrongName" + separator + hash;
                identity = name;
                return;
            }
            text = entryAssembly.Location;
        }
        if (string.IsNullOrEmpty(text))
        {
            text = Environment.ProcessPath;
        }
        if (string.IsNullOrEmpty(text))
        {
            throw new IsolatedStorageException(System.SR.IsolatedStorage_Init);
        }
        Uri uri = new Uri(text);
        hash = "Url" + separator + IdentityHelper.GetNormalizedUriHash(uri);
        identity = uri;
    }
References System.Reflection.Assembly.GetEntryAssembly(), System.Reflection.Assembly.GetName(), System.Security.IdentityHelper.GetNormalizedStrongNameHash(), System.Security.IdentityHelper.GetNormalizedUriHash(), System.SR.IsolatedStorage_Init, System.Reflection.Assembly.Location, System.Environment.ProcessPath, and System.text.
Referenced by System.IO.IsolatedStorage.IsolatedStorage.InitStore().