Terraria: System.Diagnostics.XmlWriterTraceListener.TraceEvent
TraceEvent() [2/3]
override void System.Diagnostics.XmlWriterTraceListener.TraceEvent (TraceEventCache? eventCache, string source, TraceEventType eventType, int id, string? format, params object??[] args) inline virtual
Reimplemented from System.Diagnostics.TraceListener.
Definition at line 80 of file XmlWriterTraceListener.cs.
    {
        if (base.Filter == null || base.Filter.ShouldTrace(eventCache, source, eventType, id, format, args, null, null))
        {
            WriteHeader(source, eventType, id, eventCache);
            WriteEscaped((args != null && args.Length != 0) ? string.Format(CultureInfo.InvariantCulture, format, args) : format);
            WriteFooter(eventCache);
        }
    }
References System.Xml.Dictionary, System.format, System.Globalization.CultureInfo.InvariantCulture, System.source, System.Diagnostics.XmlWriterTraceListener.WriteEscaped(), System.Diagnostics.XmlWriterTraceListener.WriteFooter(), and System.Diagnostics.XmlWriterTraceListener.WriteHeader().
Referenced by System.Diagnostics.XmlWriterTraceListener.Fail(), and System.Diagnostics.XmlWriterTraceListener.WriteLine().