Terraria: System.Diagnostics.XmlWriterTraceListener.WriteData
WriteData()
void System.Diagnostics.XmlWriterTraceListener.WriteData (object data) inline private
Definition at line 141 of file XmlWriterTraceListener.cs.
    {
        if (!(data is XPathNavigator xPathNavigator))
        {
            WriteEscaped(data.ToString());
            return;
        }
        if (_strBldr == null)
        {
            _strBldr = new StringBuilder();
            _xmlBlobWriter = new XmlTextWriter(new StringWriter(_strBldr, CultureInfo.CurrentCulture));
        }
        else
        {
            _strBldr.Length = 0;
        }
        try
        {
            xPathNavigator.MoveToRoot();
            _xmlBlobWriter.WriteNode(xPathNavigator, defattr: false);
            InternalWrite(_strBldr.ToString());
        }
        catch (Exception)
        {
            InternalWrite(data.ToString());
        }
    }
References System.Diagnostics.XmlWriterTraceListener._strBldr, System.Diagnostics.XmlWriterTraceListener._xmlBlobWriter, System.Globalization.CultureInfo.CurrentCulture, System.Xml.Dictionary, System.Diagnostics.XmlWriterTraceListener.InternalWrite(), System.Text.StringBuilder.ToString(), System.Diagnostics.XmlWriterTraceListener.WriteEscaped(), and System.Xml.XmlWriter.WriteNode().
Referenced by System.Diagnostics.XmlWriterTraceListener.TraceData(), and System.Diagnostics.XmlWriterTraceListener.TraceData().