Terraria: ResourcePack.LoadManifest
LoadManifest()
void ResourcePack.LoadManifest () inline private
     {
         if (!HasFile("pack.json"))
         {
             throw new FileNotFoundException(string.Format("Resource Pack at \"{0}\" must contain a {1} file.", FullPath, "pack.json"));
         }
         JObject val;
         using (Stream stream = OpenStream("pack.json"))
         {
             using StreamReader streamReader = new StreamReader(stream);
             val = JObject.Parse(streamReader.ReadToEnd());
         }
         Name = Extensions.Value<string>((IEnumerable<JToken>)val["Name"]);
         Description = Extensions.Value<string>((IEnumerable<JToken>)val["Description"]);
         Author = Extensions.Value<string>((IEnumerable<JToken>)val["Author"]);
         Version = val["Version"].ToObject<ResourcePackVersion>();
     }
References Author, Description, FullPath, HasFile(), Name, OpenStream(), and Version.
Referenced by ResourcePack().