Terraria: System.Diagnostics.XmlWriterTraceListener.WriteStartHeader
WriteStartHeader()
void System.Diagnostics.XmlWriterTraceListener.WriteStartHeader (string source, TraceEventType eventType, int id, TraceEventCache eventCache) inline private
Definition at line 201 of file XmlWriterTraceListener.cs.
    {
        InternalWrite("<E2ETraceEvent xmlns=\"http://schemas.microsoft.com/2004/06/E2ETraceEvent\"><System xmlns=\"http://schemas.microsoft.com/2004/06/windows/eventlog/system\">");
        InternalWrite("<EventID>");
        uint num = (uint)id;
        InternalWrite(num.ToString(CultureInfo.InvariantCulture));
        InternalWrite("</EventID>");
        InternalWrite("<Type>3</Type>");
        InternalWrite("<SubType Name=\"");
        InternalWrite(eventType.ToString());
        InternalWrite("\">0</SubType>");
        InternalWrite("<Level>");
        int num2 = (int)eventType;
        if (num2 > 255)
        {
            num2 = 255;
        }
        if (num2 < 0)
        {
            num2 = 0;
        }
        InternalWrite(num2.ToString(CultureInfo.InvariantCulture));
        InternalWrite("</Level>");
        InternalWrite("<TimeCreated SystemTime=\"");
        if (eventCache != null)
        {
            InternalWrite(eventCache.DateTime.ToString("o", CultureInfo.InvariantCulture));
        }
        else
        {
            InternalWrite(DateTime.Now.ToString("o", CultureInfo.InvariantCulture));
        }
        InternalWrite("\" />");
        InternalWrite("<Source Name=\"");
        WriteEscaped(source);
        InternalWrite("\" />");
        InternalWrite("<Correlation ActivityID=\"");
        if (eventCache != null)
        {
            InternalWrite(Trace.CorrelationManager.ActivityId.ToString("B"));
        }
        else
        {
            InternalWrite(Guid.Empty.ToString("B"));
        }
    }
References System.Diagnostics.Trace.CorrelationManager, System.Xml.Dictionary, System.Guid.Empty, System.Diagnostics.XmlWriterTraceListener.InternalWrite(), System.Globalization.CultureInfo.InvariantCulture, System.DateTime.Now, System.source, and System.Diagnostics.XmlWriterTraceListener.WriteEscaped().
Referenced by System.Diagnostics.XmlWriterTraceListener.WriteHeader(), and System.Diagnostics.XmlWriterTraceListener.WriteHeader().