Terraria: System.Diagnostics.XmlWriterTraceListener.WriteHeader
WriteHeader() [2/2]
void System.Diagnostics.XmlWriterTraceListener.WriteHeader (string source, TraceEventType eventType, int id, TraceEventCache eventCache, Guid relatedActivityId) inline private
Definition at line 187 of file XmlWriterTraceListener.cs.
    {
        WriteStartHeader(source, eventType, id, eventCache);
        InternalWrite("\" RelatedActivityID=\"");
        InternalWrite(relatedActivityId.ToString("B"));
        WriteEndHeader();
    }
References System.Xml.Dictionary, System.Diagnostics.XmlWriterTraceListener.InternalWrite(), System.source, System.Diagnostics.XmlWriterTraceListener.WriteEndHeader(), and System.Diagnostics.XmlWriterTraceListener.WriteStartHeader().
Referenced by System.Diagnostics.XmlWriterTraceListener.TraceData(), System.Diagnostics.XmlWriterTraceListener.TraceData(), System.Diagnostics.XmlWriterTraceListener.TraceEvent(), System.Diagnostics.XmlWriterTraceListener.TraceEvent(), and System.Diagnostics.XmlWriterTraceListener.TraceTransfer().