Terraria: System.Diagnostics.XmlWriterTraceListener.InternalWrite
InternalWrite()
void System.Diagnostics.XmlWriterTraceListener.InternalWrite (string message) inline private
Definition at line 363 of file XmlWriterTraceListener.cs.
    {
        EnsureWriter();
        _writer?.Write(message);
    }
References System.Diagnostics.TextWriterTraceListener._writer, System.Diagnostics.TextWriterTraceListener.EnsureWriter(), and System.IO.TextWriter.Write().
Referenced by System.Diagnostics.XmlWriterTraceListener.TraceData(), System.Diagnostics.XmlWriterTraceListener.TraceData(), System.Diagnostics.XmlWriterTraceListener.WriteData(), System.Diagnostics.XmlWriterTraceListener.WriteEndHeader(), System.Diagnostics.XmlWriterTraceListener.WriteEscaped(), System.Diagnostics.XmlWriterTraceListener.WriteFooter(), System.Diagnostics.XmlWriterTraceListener.WriteHeader(), and System.Diagnostics.XmlWriterTraceListener.WriteStartHeader().