Terraria: System.Diagnostics.XmlWriterTraceListener.WriteFooter
WriteFooter()
void System.Diagnostics.XmlWriterTraceListener.WriteFooter (TraceEventCache eventCache) inline private
Definition at line 279 of file XmlWriterTraceListener.cs.
    {
        bool flag = IsEnabled(TraceOptions.LogicalOperationStack);
        bool flag2 = IsEnabled(TraceOptions.Callstack);
        if (eventCache != null && (flag || flag2))
        {
            InternalWrite("<System.Diagnostics xmlns=\"http://schemas.microsoft.com/2004/08/System.Diagnostics\">");
            if (flag)
            {
                InternalWrite("<LogicalOperationStack>");
                Stack logicalOperationStack = eventCache.LogicalOperationStack;
                foreach (object item in logicalOperationStack)
                {
                    InternalWrite("<LogicalOperation>");
                    WriteEscaped(item?.ToString());
                    InternalWrite("</LogicalOperation>");
                }
                InternalWrite("</LogicalOperationStack>");
            }
            InternalWrite("<Timestamp>");
            InternalWrite(eventCache.Timestamp.ToString(CultureInfo.InvariantCulture));
            InternalWrite("</Timestamp>");
            if (flag2)
            {
                InternalWrite("<Callstack>");
                WriteEscaped(eventCache.Callstack);
                InternalWrite("</Callstack>");
            }
            InternalWrite("</System.Diagnostics>");
        }
        InternalWrite("</ApplicationData></E2ETraceEvent>");
    }
References System.Xml.Dictionary, System.Diagnostics.XmlWriterTraceListener.InternalWrite(), System.Globalization.CultureInfo.InvariantCulture, System.Diagnostics.TextWriterTraceListener.IsEnabled(), System.item, System.ToString, and System.Diagnostics.XmlWriterTraceListener.WriteEscaped().
Referenced by System.Diagnostics.XmlWriterTraceListener.TraceData(), System.Diagnostics.XmlWriterTraceListener.TraceData(), System.Diagnostics.XmlWriterTraceListener.TraceEvent(), System.Diagnostics.XmlWriterTraceListener.TraceEvent(), and System.Diagnostics.XmlWriterTraceListener.TraceTransfer().