Terraria: System.Diagnostics.XmlWriterTraceListener.WriteEndHeader
WriteEndHeader()
void System.Diagnostics.XmlWriterTraceListener.WriteEndHeader () inline private
Definition at line 248 of file XmlWriterTraceListener.cs.
    {
        string text = s_processName;
        if (text == null)
        {
            if (OperatingSystem.IsBrowser())
            {
                text = (s_processName = string.Empty);
            }
            else
            {
                using Process process = Process.GetCurrentProcess();
                text = (s_processName = process.ProcessName);
            }
        }
        InternalWrite("\" />");
        InternalWrite("<Execution ProcessName=\"");
        InternalWrite(text);
        InternalWrite("\" ProcessID=\"");
        InternalWrite(((uint)Environment.ProcessId).ToString(CultureInfo.InvariantCulture));
        InternalWrite("\" ThreadID=\"");
        WriteEscaped(Environment.CurrentManagedThreadId.ToString(CultureInfo.InvariantCulture));
        InternalWrite("\" />");
        InternalWrite("<Channel/>");
        InternalWrite("<Computer>");
        InternalWrite(_machineName);
        InternalWrite("</Computer>");
        InternalWrite("</System>");
        InternalWrite("<ApplicationData>");
    }
References System.Diagnostics.XmlWriterTraceListener._machineName, System.Environment.CurrentManagedThreadId, System.Xml.Dictionary, System.Diagnostics.Process.GetCurrentProcess(), System.Diagnostics.XmlWriterTraceListener.InternalWrite(), System.Globalization.CultureInfo.InvariantCulture, System.OperatingSystem.IsBrowser(), System.Environment.ProcessId, System.Diagnostics.XmlWriterTraceListener.s_processName, System.text, and System.Diagnostics.XmlWriterTraceListener.WriteEscaped().
Referenced by System.Diagnostics.XmlWriterTraceListener.WriteHeader(), and System.Diagnostics.XmlWriterTraceListener.WriteHeader().