Terraria: Recipe.AddBalloonFurniture
AddBalloonFurniture()
static void Recipe.AddBalloonFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(5169);
         currentRecipe.SetIngredients(3738, 14);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5170);
         currentRecipe.SetIngredients(3738, 15, 225, 5);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5171);
         currentRecipe.SetIngredients(3738, 20, 149, 10);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5172);
         currentRecipe.SetIngredients(3738, 16);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5173);
         currentRecipe.SetIngredients(3738, 5, 8, 3);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5174);
         currentRecipe.SetIngredients(3738, 4, 8, 1);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5175);
         currentRecipe.SetIngredients(3738, 4);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5176);
         currentRecipe.SetIngredients(3738, 4, 8, 4, 85, 1);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(16);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5177);
         currentRecipe.SetIngredients(3738, 8, 22, 2);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5178);
         currentRecipe.SetIngredients(3738, 10, 22, 3, 170, 6);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(106);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5179);
         currentRecipe.SetIngredients(3738, 6);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5180);
         currentRecipe.SetIngredients(8, 1, 3738, 3);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5181);
         currentRecipe.SetIngredients(3738, 6, 8, 1);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5182);
         currentRecipe.SetIngredients(3738, 15, 154, 4, 149, 1);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5184);
         currentRecipe.SetIngredients(3738, 6, 206, 1);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5185);
         currentRecipe.SetIngredients(3738, 5, 225, 2);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5186);
         currentRecipe.SetIngredients(3738, 8);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5187);
         currentRecipe.SetIngredients(3738, 10);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(5189);
         currentRecipe.SetIngredients(3738, 6);
         currentRecipe.RequireGroup(RecipeGroupID.Balloons);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, RecipeGroupID.Balloons, createItem, currentRecipe, RequireGroup(), SetCraftingStation(), Item.SetDefaults(), and SetIngredients().
Referenced by SetupRecipes().