Terraria: Recipe.FindRecipes
FindRecipes()
static void Recipe.FindRecipes (bool canDelayCheck = false) inline static
     {
         if (canDelayCheck)
         {
             _hasDelayedFindRecipes = true;
             return;
         }
         int oldRecipe = Main.availableRecipe[Main.focusRecipe];
         float focusY = Main.availableRecipeY[Main.focusRecipe];
         ClearAvailableRecipes();
         if (!Main.guideItem.IsAir && Main.guideItem.Name != "")
         {
             CollectGuideRecipes();
             TryRefocusingRecipe(oldRecipe);
             VisuallyRepositionRecipes(focusY);
             return;
         }
         Player localPlayer = Main.LocalPlayer;
         CollectItemsToCraftWithFrom(localPlayer);
         for (int i = 0; i < maxRecipes; i++)
         {
             Recipe recipe = Main.recipe[i];
             if (recipe.createItem.type == 0)
             {
                 break;
             }
             if (PlayerMeetsTileRequirements(localPlayer, recipe) && PlayerMeetsEnvironmentConditions(localPlayer, recipe) && CollectedEnoughItemsToCraftRecipeNew(recipe))
             {
                 AddToAvailableRecipes(i);
             }
         }
         TryRefocusingRecipe(oldRecipe);
         VisuallyRepositionRecipes(focusY);
     }
References _hasDelayedFindRecipes, AddToAvailableRecipes(), Main.availableRecipe, Main.availableRecipeY, ClearAvailableRecipes(), CollectedEnoughItemsToCraftRecipeNew(), CollectGuideRecipes(), CollectItemsToCraftWithFrom(), createItem, Main.focusRecipe, Main.guideItem, Item.IsAir, Main.LocalPlayer, maxRecipes, Item.Name, PlayerMeetsEnvironmentConditions(), PlayerMeetsTileRequirements(), Main.recipe, TryRefocusingRecipe(), Item.type, and VisuallyRepositionRecipes().
Referenced by Player.AdjTiles(), ItemSlot.AfterItemSwap(), ItemSlot.ArmorSwap(), TileEntity.BasicOpenCloseInteraction(), IngameOptions.Close(), Create(), Chest.DestroyChest(), Chest.DestroyChestDirect(), ChestUI.DrawButton(), Main.DrawInterface_26_InterfaceLogic3(), Main.DrawInventory(), Main.DrawTrashItemSlot(), Player.dropItemCheck(), Player.DropSelectedItem(), ItemSlot.DyeSwap(), ItemSlot.EquipSwap(), Player.FillAmmo(), NPC.GetChat(), MessageBuffer.GetData(), Player.GetItem_FillEmptyInventorySlot(), Player.GetItem_FillEmptyInventorySlot_VoidBag(), Player.GetItem_FillIntoOccupiedSlot(), GetThroughDelayedFindRecipes(), ItemSlot.Handle(), Player.HandleBeingInChestRange(), Main.HoverOverNPCs(), Player.ItemCheck_ManageRightClickFeatures(), Player.ItemCheckWrapped(), ItemSlot.LeftClick(), TEDisplayDoll.OnInventoryDraw(), TEHatRack.OnInventoryDraw(), TEFoodPlatter.OnPlayerInteraction(), TEItemFrame.OnPlayerInteraction(), TEWeaponsRack.OnPlayerInteraction(), TEDisplayDoll.OnPlayerUpdate(), TEHatRack.OnPlayerUpdate(), Player.OpenInventory(), ItemSlot.OverrideLeftClick(), ItemSlot.PickupItemIntoMouse(), Player.QuickBuff(), Player.QuickHeal(), Player.QuickMana(), ItemSlot.SellOrTrash(), ItemSlot.SwapEquip(), ItemSlot.SwapVanityEquip(), Player.TileInteractionsUse(), Player.ToggleCreativeMenu(), CreativeUI.ToggleMenu(), Main.TryFreeingElderSlime(), Main.TryInteractingWithMoneyTrough(), Main.TryInteractingWithMoneyTrough2(), Main.TryInteractingWithVoidLens(), and ItemSlot.TryOpenContainer().