Terraria: Recipe.AcceptedByItemGroups
AcceptedByItemGroups()
bool Recipe.AcceptedByItemGroups (int invType, int reqType) inline
     {
         for (int i = 0; i < maxRequirements; i++)
         {
             int num = acceptedGroups[i];
             if (num == -1)
             {
                 break;
             }
             if (RecipeGroup.recipeGroups[num].ValidItems.Contains(invType) && RecipeGroup.recipeGroups[num].ValidItems.Contains(reqType))
             {
                 return true;
             }
         }
         return false;
     }
References acceptedGroups, maxRequirements, and RecipeGroup.recipeGroups.
Referenced by CollectedEnoughItemsToCraftRecipeOld(), CollectGuideRecipes(), and Create().