Terraria: Recipe.AddSpiderFurniture
AddSpiderFurniture()
static void Recipe.AddSpiderFurniture () inline static private
     {
         currentRecipe.createItem.SetDefaults(4139);
         currentRecipe.createItem.stack = 10;
         currentRecipe.SetIngredients(150, 10, 2607, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4140);
         currentRecipe.createItem.stack = 4;
         currentRecipe.SetIngredients(4139, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3931);
         currentRecipe.SetIngredients(4139, 14);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3932);
         currentRecipe.SetIngredients(4139, 15, 225, 5);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3933);
         currentRecipe.SetIngredients(4139, 20, 149, 10);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3934);
         currentRecipe.SetIngredients(4139, 16);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3935);
         currentRecipe.SetIngredients(4139, 5, 8, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3936);
         currentRecipe.SetIngredients(4139, 4, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3937);
         currentRecipe.SetIngredients(4139, 4);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3938);
         currentRecipe.SetIngredients(4139, 4, 8, 4, 85, 1);
         currentRecipe.SetCraftingStation(16);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3939);
         currentRecipe.SetIngredients(4139, 8, 22, 2);
         currentRecipe.SetCraftingStation(18);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3940);
         currentRecipe.SetIngredients(4139, 10, 22, 3, 170, 6);
         currentRecipe.SetCraftingStation(106);
         currentRecipe.anyIronBar = true;
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3941);
         currentRecipe.SetIngredients(4139, 6);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3942);
         currentRecipe.SetIngredients(8, 1, 4139, 3);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3943);
         currentRecipe.SetIngredients(4139, 6, 8, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3944);
         currentRecipe.SetIngredients(4139, 15, 154, 4, 149, 1);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3946);
         currentRecipe.SetIngredients(4139, 6, 206, 1);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3947);
         currentRecipe.SetIngredients(4139, 5, 225, 2);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3948);
         currentRecipe.SetIngredients(4139, 8);
         currentRecipe.SetCraftingStation(18);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(3949);
         currentRecipe.SetIngredients(4139, 10);
         AddRecipe();
         currentRecipe.createItem.SetDefaults(4125);
         currentRecipe.SetIngredients(4139, 6);
         currentRecipe.SetCraftingStation(106);
         AddRecipe();
     }
References AddRecipe(), anyIronBar, createItem, currentRecipe, SetCraftingStation(), Item.SetDefaults(), SetIngredients(), and Item.stack.
Referenced by SetupRecipes().