Terraria: Recipe.CollectGuideRecipes
CollectGuideRecipes()
static void Recipe.CollectGuideRecipes () inline static private
     {
         int type = Main.guideItem.type;
         for (int i = 0; i < maxRecipes; i++)
         {
             Recipe recipe = Main.recipe[i];
             if (recipe.createItem.type == 0)
             {
                 break;
             }
             for (int j = 0; j < maxRequirements; j++)
             {
                 Item item = recipe.requiredItem[j];
                 if (item.type == 0)
                 {
                     break;
                 }
                 if (Main.guideItem.IsTheSameAs(item) || recipe.useWood(type, item.type) || recipe.useSand(type, item.type) || recipe.useIronBar(type, item.type) || recipe.useFragment(type, item.type) || recipe.AcceptedByItemGroups(type, item.type) || recipe.usePressurePlate(type, item.type))
                 {
                     Main.availableRecipe[Main.numAvailableRecipes] = i;
                     Main.numAvailableRecipes++;
                     break;
                 }
             }
         }
     }
References AcceptedByItemGroups(), Main.availableRecipe, createItem, Main.guideItem, Item.IsTheSameAs(), maxRecipes, maxRequirements, Main.numAvailableRecipes, Main.recipe, requiredItem, Item.type, useFragment(), useIronBar(), usePressurePlate(), useSand(), and useWood().
Referenced by FindRecipes().