Terraria: Recipe.CreateReverseWallRecipes
CreateReverseWallRecipes()
static void Recipe.CreateReverseWallRecipes () inline static private
     {
         int num = numRecipes;
         for (int i = 0; i < num; i++)
         {
             if (Main.recipe[i].createItem.createWall > 0 && Main.recipe[i].requiredItem[1].type == 0 && Main.recipe[i].requiredItem[0].createWall == -1)
             {
                 currentRecipe.createItem.SetDefaults(Main.recipe[i].requiredItem[0].type);
                 currentRecipe.createItem.stack = Main.recipe[i].requiredItem[0].stack;
                 currentRecipe.requiredItem[0].SetDefaults(Main.recipe[i].createItem.type);
                 currentRecipe.requiredItem[0].stack = Main.recipe[i].createItem.stack;
                 for (int j = 0; j < currentRecipe.requiredTile.Length; j++)
                 {
                     currentRecipe.requiredTile[j] = Main.recipe[i].requiredTile[j];
                 }
                 AddRecipe();
                 Recipe recipe = Main.recipe[numRecipes - 1];
                 for (int num2 = numRecipes - 2; num2 > i; num2--)
                 {
                     Main.recipe[num2 + 1] = Main.recipe[num2];
                 }
                 Main.recipe[i + 1] = recipe;
                 Main.recipe[i + 1].notDecraftable = true;
             }
         }
     }
References AddRecipe(), createItem, Item.createWall, currentRecipe, notDecraftable, numRecipes, Main.recipe, requiredItem, requiredTile, Item.SetDefaults(), Item.stack, and Item.type.
Referenced by SetupRecipes().