Terraria: Recipe.AddRecipe
AddRecipe()
static void Recipe.AddRecipe () inline static private
     {
         if (currentRecipe.requiredTile[0] == 13)
         {
             currentRecipe.alchemy = true;
         }
         Main.recipe[numRecipes] = currentRecipe;
         currentRecipe = new Recipe();
         numRecipes++;
     }
References Recipe(), alchemy, currentRecipe, numRecipes, Main.recipe, and requiredTile.
Referenced by AddAshWoodFurnitureArmorAndItems(), AddBalloonFurniture(), AddBambooFurniture(), AddCoralFurniture(), AddLesionFurniture(), AddNebulaFurniture(), AddSandstoneFurniture(), AddSolarFurniture(), AddSpiderFurniture(), AddStardustFurniture(), AddVortexFurniture(), CreateReversePlatformRecipes(), CreateReverseWallRecipes(), and SetupRecipes().