Terraria: System.SR.InternalGetResourceString
InternalGetResourceString()
static string System.SR.InternalGetResourceString (string key) inline static private
Definition at line 2214 of file SR.cs.
    {
        if (key.Length == 0)
        {
            return key;
        }
        bool lockTaken = false;
        try
        {
            Monitor.Enter(_lock, ref lockTaken);
            if (_currentlyLoading != null && _currentlyLoading.Count > 0 && _currentlyLoading.LastIndexOf(key) != -1)
            {
                if (_infinitelyRecursingCount > 0)
                {
                    return key;
                }
                _infinitelyRecursingCount++;
                string message = $"Infinite recursion during resource lookup within {"System.Private.CoreLib"}.  This may be a bug in {"System.Private.CoreLib"}, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: {key}";
                Environment.FailFast(message);
            }
            if (_currentlyLoading == null)
            {
                _currentlyLoading = new List<string>();
            }
            if (!_resourceManagerInited)
            {
                RuntimeHelpers.RunClassConstructor(typeof(ResourceManager).TypeHandle);
                RuntimeHelpers.RunClassConstructor(typeof(ResourceReader).TypeHandle);
                RuntimeHelpers.RunClassConstructor(typeof(RuntimeResourceSet).TypeHandle);
                RuntimeHelpers.RunClassConstructor(typeof(BinaryReader).TypeHandle);
                _resourceManagerInited = true;
            }
            _currentlyLoading.Add(key);
            string @string = ResourceManager.GetString(key, null);
            _currentlyLoading.RemoveAt(_currentlyLoading.Count - 1);
            return @string ?? key;
        }
        catch
        {
            if (lockTaken)
            {
                s_resourceManager = null;
                _currentlyLoading = null;
            }
            throw;
        }
        finally
        {
            if (lockTaken)
            {
                Monitor.Exit(_lock);
            }
        }
    }
References System.SR._currentlyLoading, System.SR._infinitelyRecursingCount, System.SR._lock, System.SR._resourceManagerInited, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Environment.FailFast(), System.Resources.ResourceManager.GetString(), System.key, System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(), and System.SR.s_resourceManager.
Referenced by System.SR.GetResourceString().