Terraria: System.Text.Encoder.Convert
Convert() [2/3]
virtual void System.Text.Encoder.Convert (char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex, int byteCount, bool flush, out int charsUsed, out int bytesUsed, out bool completed) inline virtual inherited
Reimplemented in System.Text.OSEncoder, System.Text.OSEncoder, System.Text.EncoderNLS, and System.Text.EncoderNLS.
Definition at line 135 of file Encoder.cs.
    {
        if (chars == null || bytes == null)
        {
            throw new ArgumentNullException((chars == null) ? "chars" : "bytes", SR.ArgumentNull_Array);
        }
        if (charIndex < 0 || charCount < 0)
        {
            throw new ArgumentOutOfRangeException((charIndex < 0) ? "charIndex" : "charCount", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (byteIndex < 0 || byteCount < 0)
        {
            throw new ArgumentOutOfRangeException((byteIndex < 0) ? "byteIndex" : "byteCount", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (chars.Length - charIndex < charCount)
        {
            throw new ArgumentOutOfRangeException("chars", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        if (bytes.Length - byteIndex < byteCount)
        {
            throw new ArgumentOutOfRangeException("bytes", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        for (charsUsed = charCount; charsUsed > 0; charsUsed /= 2)
        {
            if (GetByteCount(chars, charIndex, charsUsed, flush) <= byteCount)
            {
                bytesUsed = GetBytes(chars, charIndex, charsUsed, bytes, byteIndex, flush);
                completed = charsUsed == charCount && (_fallbackBuffer == null || _fallbackBuffer.Remaining == 0);
                return;
            }
            flush = false;
        }
        throw new ArgumentException(SR.Argument_ConversionOverflow);
    }
References System.Text.Encoder._fallbackBuffer, System.SR.Argument_ConversionOverflow, System.SR.ArgumentNull_Array, System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.byteCount, System.byteIndex, System.bytes, System.charCount, System.charIndex, System.chars, System.Text.Encoder.GetByteCount(), and System.Text.Encoder.GetBytes().
Referenced by System.Text.Encoder.Convert(), System.Text.EncodingExtensions.Convert(), System.Text.EncodingExtensions.Convert(), System.Xml.XmlEncodedRawTextWriter.EncodeChars(), System.Xml.XmlEncodedRawTextWriter.EncodeCharsAsync(), System.Xml.XmlEncodedRawTextWriter.FlushEncoder(), System.Xml.XmlEncodedRawTextWriter.FlushEncoderAsync(), System.Text.TranscodingStream.Write(), System.Text.TranscodingStream.WriteAsync(), and System.IO.BinaryWriter.WriteCharsCommonWithoutLengthPrefix().