Terraria: System.Text.Encoder.GetBytes
GetBytes() [2/3]
int System.Text.Encoder.GetBytes (char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex, bool flush) abstract
Referenced by System.Text.Encoder.Convert(), System.Text.Encoder.Convert(), System.Text.TranscodingStream.FinalFlushWriteBuffers(), System.IO.StreamWriter.Flush(), System.IO.StreamWriter.FlushAsyncInternal(), System.Text.Encoder.GetBytes(), System.Text.Encoder.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.EncodingExtensions.GetBytes(), System.Text.TranscodingStream.Read(), System.Text.TranscodingStream.ReadAsync(), System.Text.Encoder.Reset(), System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.Write(), and System.Xml.EncodingStreamWrapper.Write().