Terraria: System.Text.Encoder.Reset
Reset()
virtual void System.Text.Encoder.Reset () inline virtual inherited
Reimplemented in System.Text.OSEncoder, System.Text.OSEncoder, System.Text.EncoderNLS, System.Text.UTF7Encoding.Encoder, System.Text.EncoderNLS, System.Text.ISCIIEncoding.ISCIIEncoder, and System.Text.ISO2022Encoding.ISO2022Encoder.
Definition at line 53 of file Encoder.cs.
    {
        char[] chars = Array.Empty<char>();
        byte[] bytes = new byte[GetByteCount(chars, 0, 0, flush: true)];
        GetBytes(chars, 0, 0, bytes, 0, flush: true);
        if (_fallbackBuffer != null)
        {
            _fallbackBuffer.Reset();
        }
    }
References System.Text.Encoder._fallbackBuffer, System.bytes, System.chars, System.Text.Encoder.GetByteCount(), System.Text.Encoder.GetBytes(), and System.Text.EncoderFallbackBuffer.Reset().