Terraria: System.Runtime.Serialization.Json.XmlJsonReader.Read
Read()
override bool System.Runtime.Serialization.Json.XmlJsonReader.Read () inline
Definition at line 183 of file XmlJsonReader.cs.
    {
        if (base.Node.CanMoveToElement)
        {
            MoveToElement();
        }
        if (base.Node.ReadState == ReadState.Closed)
        {
            return false;
        }
        if (base.Node.ExitScope)
        {
            ExitScope();
        }
        if (!_buffered)
        {
            base.BufferReader.SetWindow(base.ElementNode.BufferOffset, _maxBytesPerRead);
        }
        byte ch;
        if (!IsReadingComplexText)
        {
            SkipWhitespaceInBufferReader();
            if (TryGetByte(out ch) && (_charactersToSkipOnNextRead[0] == ch || _charactersToSkipOnNextRead[1] == ch))
            {
                base.BufferReader.SkipByte();
                _charactersToSkipOnNextRead[0] = 0;
                _charactersToSkipOnNextRead[1] = 0;
            }
            SkipWhitespaceInBufferReader();
            if (TryGetByte(out ch) && ch == 93 && IsReadingCollection)
            {
                base.BufferReader.SkipByte();
                SkipWhitespaceInBufferReader();
                ExitJsonScope();
            }
            if (base.BufferReader.EndOfFile)
            {
                if (_scopeDepth > 0)
                {
                    MoveToEndElement();
                    return true;
                }
                MoveToEndOfFile();
                return false;
            }
        }
        ch = base.BufferReader.GetByte();
        if (_scopeDepth == 0)
        {
            ReadNonExistentElementName(StringHandleConstStringType.Root);
        }
        else if (IsReadingComplexText)
        {
            switch (_complexTextMode)
            {
            case JsonComplexTextMode.NumericalText:
                ReadNumericalText();
                break;
            case JsonComplexTextMode.QuotedText:
                if (ch == 92)
                {
                    ReadEscapedCharacter(moveToText: true);
                }
                else
                {
                    ReadQuotedText(moveToText: true);
                }
                break;
            case JsonComplexTextMode.None:
                XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, (char)ch)));
                break;
            }
        }
        else if (IsReadingCollection)
        {
            ReadNonExistentElementName(StringHandleConstStringType.Item);
        }
        else if (ch == 93)
        {
            base.BufferReader.SkipByte();
            MoveToEndElement();
            ExitJsonScope();
        }
        else if (ch == 123)
        {
            base.BufferReader.SkipByte();
            SkipWhitespaceInBufferReader();
            ch = base.BufferReader.GetByte();
            if (ch == 125)
            {
                base.BufferReader.SkipByte();
                SkipWhitespaceInBufferReader();
                if (TryGetByte(out ch))
                {
                    if (ch == 44)
                    {
                        base.BufferReader.SkipByte();
                    }
                }
                else
                {
                    _charactersToSkipOnNextRead[0] = 44;
                }
                MoveToEndElement();
            }
            else
            {
                EnterJsonScope(JsonNodeType.Object);
                ParseStartElement();
            }
        }
        else if (ch == 125)
        {
            base.BufferReader.SkipByte();
            if (_expectingFirstElementInNonPrimitiveChild)
            {
                SkipWhitespaceInBufferReader();
                ch = base.BufferReader.GetByte();
                if (ch == 44 || ch == 125)
                {
                    base.BufferReader.SkipByte();
                }
                else
                {
                    XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, (char)ch)));
                }
                _expectingFirstElementInNonPrimitiveChild = false;
            }
            MoveToEndElement();
        }
        else if (ch == 44)
        {
            base.BufferReader.SkipByte();
            MoveToEndElement();
        }
        else if (ch == 34)
        {
            if (_readServerTypeElement)
            {
                _readServerTypeElement = false;
                EnterJsonScope(JsonNodeType.Object);
                ParseStartElement();
            }
            else if (base.Node.NodeType == XmlNodeType.Element)
            {
                if (_expectingFirstElementInNonPrimitiveChild)
                {
                    EnterJsonScope(JsonNodeType.Object);
                    ParseStartElement();
                }
                else
                {
                    base.BufferReader.SkipByte();
                    ReadQuotedText(moveToText: true);
                }
            }
            else if (base.Node.NodeType == XmlNodeType.EndElement)
            {
                EnterJsonScope(JsonNodeType.Element);
                ParseStartElement();
            }
            else
            {
                XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, '"')));
            }
        }
        else if (ch == 102)
        {
            int offset;
            byte[] buffer = base.BufferReader.GetBuffer(5, out offset);
            if (buffer[offset + 1] != 97 || buffer[offset + 2] != 108 || buffer[offset + 3] != 115 || buffer[offset + 4] != 101)
            {
                XmlExceptionHelper.ThrowTokenExpected(this, "false", Encoding.UTF8.GetString(buffer, offset, 5));
            }
            base.BufferReader.Advance(5);
            if (TryGetByte(out ch) && !IsWhitespace(ch) && ch != 44 && ch != 125 && ch != 93)
            {
                string @string = Encoding.UTF8.GetString(buffer, offset, 4);
                char c = (char)ch;
                XmlExceptionHelper.ThrowTokenExpected(this, "false", @string + c);
            }
            MoveToAtomicText().Value.SetValue(ValueHandleType.UTF8, offset, 5);
        }
        else if (ch == 116)
        {
            int offset2;
            byte[] buffer2 = base.BufferReader.GetBuffer(4, out offset2);
            if (buffer2[offset2 + 1] != 114 || buffer2[offset2 + 2] != 117 || buffer2[offset2 + 3] != 101)
            {
                XmlExceptionHelper.ThrowTokenExpected(this, "true", Encoding.UTF8.GetString(buffer2, offset2, 4));
            }
            base.BufferReader.Advance(4);
            if (TryGetByte(out ch) && !IsWhitespace(ch) && ch != 44 && ch != 125 && ch != 93)
            {
                string string2 = Encoding.UTF8.GetString(buffer2, offset2, 4);
                char c = (char)ch;
                XmlExceptionHelper.ThrowTokenExpected(this, "true", string2 + c);
            }
            MoveToAtomicText().Value.SetValue(ValueHandleType.UTF8, offset2, 4);
        }
        else if (ch == 110)
        {
            int offset3;
            byte[] buffer3 = base.BufferReader.GetBuffer(4, out offset3);
            if (buffer3[offset3 + 1] != 117 || buffer3[offset3 + 2] != 108 || buffer3[offset3 + 3] != 108)
            {
                XmlExceptionHelper.ThrowTokenExpected(this, "null", Encoding.UTF8.GetString(buffer3, offset3, 4));
            }
            base.BufferReader.Advance(4);
            SkipWhitespaceInBufferReader();
            if (TryGetByte(out ch))
            {
                switch (ch)
                {
                case 44:
                case 125:
                    base.BufferReader.SkipByte();
                    break;
                default:
                {
                    string string3 = Encoding.UTF8.GetString(buffer3, offset3, 4);
                    char c = (char)ch;
                    XmlExceptionHelper.ThrowTokenExpected(this, "null", string3 + c);
                    break;
                }
                case 93:
                    break;
                }
            }
            else
            {
                _charactersToSkipOnNextRead[0] = 44;
                _charactersToSkipOnNextRead[1] = 125;
            }
            MoveToEndElement();
        }
        else if (ch == 45 || (48 <= ch && ch <= 57) || ch == 73 || ch == 78)
        {
            ReadNumericalText();
        }
        else
        {
            XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, (char)ch)));
        }
        return true;
    }
References System.Runtime.Serialization.Json.XmlJsonReader._buffered, System.Runtime.Serialization.Json.XmlJsonReader._charactersToSkipOnNextRead, System.Runtime.Serialization.Json.XmlJsonReader._complexTextMode, System.Runtime.Serialization.Json.XmlJsonReader._expectingFirstElementInNonPrimitiveChild, System.Runtime.Serialization.Json.XmlJsonReader._maxBytesPerRead, System.Runtime.Serialization.Json.XmlJsonReader._readServerTypeElement, System.Runtime.Serialization.Json.XmlJsonReader._scopeDepth, System.buffer, System.ch, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlJsonReader.EnterJsonScope(), System.Runtime.Serialization.Json.XmlJsonReader.ExitJsonScope(), System.Xml.XmlBaseReader.ExitScope(), System.SR.Format(), System.Runtime.Serialization.Json.XmlJsonReader.IsReadingCollection, System.Runtime.Serialization.Json.XmlJsonReader.IsReadingComplexText, System.Runtime.Serialization.Json.XmlJsonReader.IsWhitespace(), System.SR.JsonEncounteredUnexpectedCharacter, System.Xml.XmlBaseReader.MoveToAtomicText(), System.Xml.XmlBaseReader.MoveToElement(), System.Runtime.Serialization.Json.XmlJsonReader.MoveToEndElement(), System.Xml.XmlBaseReader.MoveToEndOfFile(), System.offset, System.Runtime.Serialization.Json.XmlJsonReader.ParseStartElement(), System.Runtime.Serialization.Json.XmlJsonReader.ReadEscapedCharacter(), System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName(), System.Runtime.Serialization.Json.XmlJsonReader.ReadNumericalText(), System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText(), System.Xml.ValueHandle.SetValue(), System.Runtime.Serialization.Json.XmlJsonReader.SkipWhitespaceInBufferReader(), System.Xml.XmlExceptionHelper.ThrowTokenExpected(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Runtime.Serialization.Json.XmlJsonReader.TryGetByte(), System.Text.Encoding.UTF8, System.Xml.XmlBaseReader.XmlNode.Value, and System.Xml.XmlException.