Terraria: System.Runtime.Serialization.Json.XmlJsonReader.EnterJsonScope
EnterJsonScope()
void System.Runtime.Serialization.Json.XmlJsonReader.EnterJsonScope (JsonNodeType currentNodeType) inline private
Definition at line 787 of file XmlJsonReader.cs.
    {
        _scopeDepth++;
        if (_scopes == null)
        {
            _scopes = new JsonNodeType[4];
        }
        else if (_scopes.Length == _scopeDepth)
        {
            JsonNodeType[] array = new JsonNodeType[_scopeDepth * 2];
            Array.Copy(_scopes, array, _scopeDepth);
            _scopes = array;
        }
        _scopes[_scopeDepth] = currentNodeType;
    }
References System.Runtime.Serialization.Json.XmlJsonReader._scopeDepth, System.Runtime.Serialization.Json.XmlJsonReader._scopes, System.array, System.Array.Copy(), and System.Runtime.Serialization.Dictionary.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.Read(), System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes(), and System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName().