Terraria: System.Runtime.Serialization.Json.XmlJsonReader.SetJsonNameWithMapping
SetJsonNameWithMapping()
void System.Runtime.Serialization.Json.XmlJsonReader.SetJsonNameWithMapping (XmlElementNode elementNode) inline private
Definition at line 1241 of file XmlJsonReader.cs.
    {
        Namespace @namespace = AddNamespace();
        @namespace.Prefix.SetValue(PrefixHandleType.A);
        @namespace.Uri.SetConstantValue(StringHandleConstStringType.Item);
        AddXmlnsAttribute(@namespace);
        XmlAttributeNode xmlAttributeNode = AddAttribute();
        xmlAttributeNode.LocalName.SetConstantValue(StringHandleConstStringType.Item);
        xmlAttributeNode.Namespace.Uri.SetValue(0, 0);
        xmlAttributeNode.Prefix.SetValue(PrefixHandleType.Empty);
        xmlAttributeNode.Value.SetValue(ValueHandleType.UTF8, elementNode.NameOffset, elementNode.NameLength);
        elementNode.NameLength = 0;
        elementNode.Prefix.SetValue(PrefixHandleType.A);
        elementNode.LocalName.SetConstantValue(StringHandleConstStringType.Item);
        elementNode.Namespace = @namespace;
    }
References System.Xml.XmlBaseReader.AddAttribute(), System.Xml.XmlBaseReader.AddNamespace(), System.Xml.XmlBaseReader.AddXmlnsAttribute(), System.Xml.Dictionary, System.Xml.XmlBaseReader.Namespace.Prefix, and System.Xml.PrefixHandle.SetValue().
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.ParseAndSetLocalName().