Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ReadEscapedCharacter
ReadEscapedCharacter()
void System.Runtime.Serialization.Json.XmlJsonReader.ReadEscapedCharacter (bool moveToText) inline private
Definition at line 968 of file XmlJsonReader.cs.
    {
        base.BufferReader.SkipByte();
        char c = (char)base.BufferReader.GetByte();
        switch (c)
        {
        case 'u':
        {
            base.BufferReader.SkipByte();
            int offset;
            byte[] buffer = base.BufferReader.GetBuffer(5, out offset);
            string @string = Encoding.UTF8.GetString(buffer, offset, 4);
            base.BufferReader.Advance(4);
            int num = ParseChar(@string, NumberStyles.HexNumber);
            if (char.IsHighSurrogate((char)num))
            {
                byte @byte = base.BufferReader.GetByte();
                if (@byte == 92)
                {
                    base.BufferReader.SkipByte();
                    SkipExpectedByteInBufferReader(117);
                    buffer = base.BufferReader.GetBuffer(5, out offset);
                    @string = Encoding.UTF8.GetString(buffer, offset, 4);
                    base.BufferReader.Advance(4);
                    char c2 = ParseChar(@string, NumberStyles.HexNumber);
                    if (!char.IsLowSurrogate(c2))
                    {
                        XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.XmlInvalidLowSurrogate, @string)));
                    }
                    num = new SurrogateChar(c2, (char)num).Char;
                }
            }
            if (buffer[offset + 4] == 34)
            {
                base.BufferReader.SkipByte();
                if (moveToText)
                {
                    MoveToAtomicText().Value.SetCharValue(num);
                }
                _complexTextMode = JsonComplexTextMode.None;
            }
            else
            {
                if (moveToText)
                {
                    MoveToComplexText().Value.SetCharValue(num);
                }
                _complexTextMode = JsonComplexTextMode.QuotedText;
            }
            return;
        }
        case 'b':
            c = '\b';
            break;
        case 'f':
            c = '\f';
            break;
        case 'n':
            c = '\n';
            break;
        case 'r':
            c = '\r';
            break;
        case 't':
            c = '\t';
            break;
        default:
            XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, c)));
            break;
        case '"':
        case '/':
        case '\\':
            break;
        }
        base.BufferReader.SkipByte();
        if (base.BufferReader.GetByte() == 34)
        {
            base.BufferReader.SkipByte();
            if (moveToText)
            {
                MoveToAtomicText().Value.SetCharValue(c);
            }
            _complexTextMode = JsonComplexTextMode.None;
        }
        else
        {
            if (moveToText)
            {
                MoveToComplexText().Value.SetCharValue(c);
            }
            _complexTextMode = JsonComplexTextMode.QuotedText;
        }
    }
References System.Runtime.Serialization.Json.XmlJsonReader._complexTextMode, System.buffer, System.Text.SurrogateChar.Char, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.SR.JsonEncounteredUnexpectedCharacter, System.Xml.XmlBaseReader.MoveToAtomicText(), System.Xml.XmlBaseReader.MoveToComplexText(), System.offset, System.Runtime.Serialization.Json.XmlJsonReader.ParseChar(), System.Xml.ValueHandle.SetCharValue(), System.Runtime.Serialization.Json.XmlJsonReader.SkipExpectedByteInBufferReader(), System.Xml.XmlExceptionHelper.ThrowXmlException(), System.Text.Encoding.UTF8, System.Xml.XmlBaseReader.XmlNode.Value, System.Xml.XmlException, and System.SR.XmlInvalidLowSurrogate.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.ParseAndSetLocalName(), System.Runtime.Serialization.Json.XmlJsonReader.Read(), System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText(), and System.Runtime.Serialization.Json.XmlJsonReader.ReadServerTypeAttribute().