Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText
ReadQuotedText()
void System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText (bool moveToText) inline private
Definition at line 1115 of file XmlJsonReader.cs.
    {
        int offset;
        int offsetMax;
        bool escaped;
        bool flag;
        int num;
        if (_buffered)
        {
            byte[] buffer = base.BufferReader.GetBuffer(out offset, out offsetMax);
            num = ComputeQuotedTextLengthUntilEndQuote(buffer, offset, offsetMax, out escaped);
            flag = offset < offsetMax - num;
        }
        else
        {
            byte[] buffer = base.BufferReader.GetBuffer(2048, out offset, out offsetMax);
            num = ComputeQuotedTextLengthUntilEndQuote(buffer, offset, offsetMax, out escaped);
            flag = offset < offsetMax - num;
            num = BreakText(buffer, offset, num);
        }
        if (escaped && base.BufferReader.GetByte() == 239)
        {
            offset = base.BufferReader.Offset;
            num = ReadNonFFFE();
        }
        base.BufferReader.Advance(num);
        if (!escaped && flag)
        {
            if (moveToText)
            {
                MoveToAtomicText().Value.SetValue(ValueHandleType.UTF8, offset, num);
            }
            SkipExpectedByteInBufferReader(34);
            _complexTextMode = JsonComplexTextMode.None;
        }
        else if (num == 0 && escaped)
        {
            ReadEscapedCharacter(moveToText);
        }
        else
        {
            if (moveToText)
            {
                MoveToComplexText().Value.SetValue(ValueHandleType.UTF8, offset, num);
            }
            _complexTextMode = JsonComplexTextMode.QuotedText;
        }
    }
References System.Runtime.Serialization.Json.XmlJsonReader._buffered, System.Runtime.Serialization.Json.XmlJsonReader._complexTextMode, System.Runtime.Serialization.Json.XmlJsonReader.BreakText(), System.buffer, System.Runtime.Serialization.Json.XmlJsonReader.ComputeQuotedTextLengthUntilEndQuote(), System.Runtime.Serialization.Dictionary, System.Xml.XmlBaseReader.MoveToAtomicText(), System.Xml.XmlBaseReader.MoveToComplexText(), System.offset, System.Runtime.Serialization.Json.XmlJsonReader.ReadEscapedCharacter(), System.Runtime.Serialization.Json.XmlJsonReader.ReadNonFFFE(), System.Xml.ValueHandle.SetValue(), System.Runtime.Serialization.Json.XmlJsonReader.SkipExpectedByteInBufferReader(), and System.Xml.XmlBaseReader.XmlNode.Value.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.ParseAndSetLocalName(), System.Runtime.Serialization.Json.XmlJsonReader.Read(), and System.Runtime.Serialization.Json.XmlJsonReader.ReadServerTypeAttribute().