Terraria: System.Runtime.Serialization.Json.XmlJsonReader.UnescapeJsonString
UnescapeJsonString()
string System.Runtime.Serialization.Json.XmlJsonReader.UnescapeJsonString (string val) inline private
Definition at line 1292 of file XmlJsonReader.cs.
    {
        if (val == null)
        {
            return null;
        }
        StringBuilder stringBuilder = null;
        int startIndex = 0;
        int num = 0;
        for (int i = 0; i < val.Length; i++)
        {
            if (val[i] == '\\')
            {
                i++;
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder();
                }
                stringBuilder.Append(val, startIndex, num);
                if (i >= val.Length)
                {
                    XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, val[i])));
                }
                switch (val[i])
                {
                case '"':
                case '\'':
                case '/':
                case '\\':
                    stringBuilder.Append(val[i]);
                    break;
                case 'b':
                    stringBuilder.Append('\b');
                    break;
                case 'f':
                    stringBuilder.Append('\f');
                    break;
                case 'n':
                    stringBuilder.Append('\n');
                    break;
                case 'r':
                    stringBuilder.Append('\r');
                    break;
                case 't':
                    stringBuilder.Append('\t');
                    break;
                case 'u':
                    if (i + 3 >= val.Length)
                    {
                        XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, val[i])));
                    }
                    stringBuilder.Append(ParseChar(val.Substring(i + 1, 4), NumberStyles.HexNumber));
                    i += 4;
                    break;
                }
                startIndex = i + 1;
                num = 0;
            }
            else
            {
                num++;
            }
        }
        if (stringBuilder == null)
        {
            return val;
        }
        if (num > 0)
        {
            stringBuilder.Append(val, startIndex, num);
        }
        return stringBuilder.ToString();
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.SR.JsonEncounteredUnexpectedCharacter, System.Runtime.Serialization.Json.XmlJsonReader.ParseChar(), System.startIndex, System.Xml.XmlExceptionHelper.ThrowXmlException(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.GetAttribute(), System.Runtime.Serialization.Json.XmlJsonReader.GetAttribute(), System.Runtime.Serialization.Json.XmlJsonReader.GetAttribute(), System.Runtime.Serialization.Json.XmlJsonReader.GetAttribute(), and System.Runtime.Serialization.Json.XmlJsonReader.ReadValueChunk().