Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ParseStartElement
ParseStartElement()
void System.Runtime.Serialization.Json.XmlJsonReader.ParseStartElement () inline private
Definition at line 869 of file XmlJsonReader.cs.
    {
        if (!_buffered)
        {
            BufferElement();
        }
        _expectingFirstElementInNonPrimitiveChild = false;
        byte @byte = base.BufferReader.GetByte();
        if (@byte == 34)
        {
            base.BufferReader.SkipByte();
            ParseAndSetLocalName();
            SkipWhitespaceInBufferReader();
            SkipExpectedByteInBufferReader(58);
            SkipWhitespaceInBufferReader();
            if (base.BufferReader.GetByte() == 123)
            {
                base.BufferReader.SkipByte();
                _expectingFirstElementInNonPrimitiveChild = true;
            }
            ReadAttributes();
        }
        else
        {
            XmlExceptionHelper.ThrowTokenExpected(this, "\"", (char)@byte);
        }
    }
References System.Runtime.Serialization.Json.XmlJsonReader._buffered, System.Runtime.Serialization.Json.XmlJsonReader._expectingFirstElementInNonPrimitiveChild, System.Runtime.Serialization.Json.XmlJsonReader.BufferElement(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlJsonReader.ParseAndSetLocalName(), System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes(), System.Runtime.Serialization.Json.XmlJsonReader.SkipExpectedByteInBufferReader(), System.Runtime.Serialization.Json.XmlJsonReader.SkipWhitespaceInBufferReader(), and System.Xml.XmlExceptionHelper.ThrowTokenExpected().
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.Read().