Terraria: System.Runtime.Serialization.Json.XmlJsonReader.SetInput
SetInput() [1/4]
void System.Runtime.Serialization.Json.XmlJsonReader.SetInput (byte[] buffer, int offset, int count, Encoding encoding, XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose) inline
Definition at line 549 of file XmlJsonReader.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative);
        }
        if (offset > buffer.Length)
        {
            throw new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.JsonOffsetExceedsBufferSize, buffer.Length));
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative);
        }
        if (count > buffer.Length - offset)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.JsonSizeExceedsRemainingBufferSpace, buffer.Length - offset));
        }
        MoveToInitial(quotas, onClose);
        ArraySegment<byte> arraySegment = JsonEncodingStreamWrapper.ProcessBuffer(buffer, offset, count, encoding);
        base.BufferReader.SetBuffer(arraySegment.Array, arraySegment.Offset, arraySegment.Count, null, null);
        _buffered = true;
        ResetState();
    }
References System.Runtime.Serialization.Json.XmlJsonReader._buffered, System.buffer, System.count, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.SR.JsonOffsetExceedsBufferSize, System.SR.JsonSizeExceedsRemainingBufferSpace, System.Runtime.Serialization.Json.XmlJsonReader.MoveToInitial(), System.offset, System.Runtime.Serialization.Json.JsonEncodingStreamWrapper.ProcessBuffer(), System.Runtime.Serialization.Json.XmlJsonReader.ResetState(), and System.SR.ValueMustBeNonNegative.