Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ReadValueChunk
ReadValueChunk()
override int System.Runtime.Serialization.Json.XmlJsonReader.ReadValueChunk (char[] chars, int offset, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 506 of file XmlJsonReader.cs.
    {
        if (IsAttributeValue)
        {
            if (chars == null)
            {
                throw new ArgumentNullException("chars");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative);
            }
            if (offset > chars.Length)
            {
                throw new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length));
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative);
            }
            if (count > chars.Length - offset)
            {
                throw new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, chars.Length - offset));
            }
            string text = UnescapeJsonString(base.Node.ValueAsString);
            int num = Math.Min(count, text.Length);
            if (num > 0)
            {
                text.CopyTo(0, chars, offset, num);
                if (base.Node.QNameType == QNameType.Xmlns)
                {
                    base.Node.Namespace.Uri.SetValue(0, 0);
                }
                else
                {
                    base.Node.Value.SetValue(ValueHandleType.UTF8, 0, 0);
                }
            }
            return num;
        }
        return base.ReadValueChunk(chars, offset, count);
    }
References System.chars, System.count, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.Json.XmlJsonReader.IsAttributeValue, System.Math.Min(), System.offset, System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.text, System.Runtime.Serialization.Json.XmlJsonReader.UnescapeJsonString(), and System.SR.ValueMustBeNonNegative.