Terraria: System.Xml.HtmlEncodedRawTextWriterIndent.WriteIndent
WriteIndent()
void System.Xml.HtmlEncodedRawTextWriterIndent.WriteIndent () inline private
Definition at line 126 of file HtmlEncodedRawTextWriterIndent.cs.
    {
        RawText(_newLineChars);
        for (int num = _indentLevel; num > 0; num--)
        {
            RawText(_indentChars);
        }
    }
References System.Xml.HtmlEncodedRawTextWriterIndent._indentChars, System.Xml.HtmlEncodedRawTextWriterIndent._indentLevel, System.Xml.XmlEncodedRawTextWriter._newLineChars, and System.Xml.XmlEncodedRawTextWriter.RawText().
Referenced by System.Xml.HtmlEncodedRawTextWriterIndent.StartElementContent(), System.Xml.HtmlEncodedRawTextWriterIndent.WriteEndElement(), System.Xml.HtmlEncodedRawTextWriterIndent.WriteStartAttribute(), and System.Xml.HtmlEncodedRawTextWriterIndent.WriteStartElement().