Terraria: System.Runtime.Serialization.Json.XmlJsonReader.CheckArray
CheckArray()
static void System.Runtime.Serialization.Json.XmlJsonReader.CheckArray (Array array, int offset, int count) inline static package
Definition at line 596 of file XmlJsonReader.cs.
    {
        if (array == null)
        {
            throw new ArgumentNullException("array");
        }
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException("offset", System.SR.ValueMustBeNonNegative);
        }
        if (offset > array.Length)
        {
            throw new ArgumentOutOfRangeException("offset", System.SR.Format(System.SR.OffsetExceedsBufferSize, array.Length));
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative);
        }
        if (count > array.Length - offset)
        {
            throw new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, array.Length - offset));
        }
    }
References System.array, System.count, System.SR.Format(), System.offset, System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, and System.SR.ValueMustBeNonNegative.
Referenced by System.Runtime.Serialization.Json.ByteArrayHelperWithString.ReadArray(), System.Runtime.Serialization.Json.JsonReaderDelegator.DateTimeArrayJsonHelperWithString.ReadArray(), and System.Runtime.Serialization.Json.ByteArrayHelperWithString.WriteArray().