Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ParseChar
ParseChar()
static char System.Runtime.Serialization.Json.XmlJsonReader.ParseChar (string value, NumberStyles style) inline static private
Definition at line 704 of file XmlJsonReader.cs.
    {
        int value2 = ParseInt(value, style);
        try
        {
            return Convert.ToChar(value2);
        }
        catch (OverflowException exception)
        {
            throw XmlExceptionHelper.CreateConversionException(value, "char", exception);
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Runtime.Serialization.Dictionary, System.exception, System.Runtime.Serialization.Json.XmlJsonReader.ParseInt(), System.Convert.ToChar(), and System.value.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.ReadEscapedCharacter(), and System.Runtime.Serialization.Json.XmlJsonReader.UnescapeJsonString().