Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ReadServerTypeAttribute
ReadServerTypeAttribute()
void System.Runtime.Serialization.Json.XmlJsonReader.ReadServerTypeAttribute (bool consumedObjectChar) inline private
Definition at line 1164 of file XmlJsonReader.cs.
    {
        if (!consumedObjectChar)
        {
            SkipExpectedByteInBufferReader(123);
            SkipWhitespaceInBufferReader();
            byte @byte = base.BufferReader.GetByte();
            if (@byte != 34 && @byte != 125)
            {
                XmlExceptionHelper.ThrowTokenExpected(this, "\"", (char)@byte);
            }
        }
        else
        {
            SkipWhitespaceInBufferReader();
        }
        byte[] buffer = base.BufferReader.GetBuffer(8, out var offset, out var offsetMax);
        if (offset + 8 <= offsetMax && buffer[offset] == 34 && buffer[offset + 1] == 95 && buffer[offset + 2] == 95 && buffer[offset + 3] == 116 && buffer[offset + 4] == 121 && buffer[offset + 5] == 112 && buffer[offset + 6] == 101 && buffer[offset + 7] == 34)
        {
            XmlAttributeNode xmlAttributeNode = AddAttribute();
            xmlAttributeNode.LocalName.SetValue(offset + 1, 6);
            xmlAttributeNode.Namespace.Uri.SetValue(0, 0);
            xmlAttributeNode.Prefix.SetValue(PrefixHandleType.Empty);
            base.BufferReader.Advance(8);
            if (!_buffered)
            {
                BufferElement();
            }
            SkipWhitespaceInBufferReader();
            SkipExpectedByteInBufferReader(58);
            SkipWhitespaceInBufferReader();
            SkipExpectedByteInBufferReader(34);
            buffer = base.BufferReader.GetBuffer(out offset, out offsetMax);
            do
            {
                if (base.BufferReader.GetByte() == 92)
                {
                    ReadEscapedCharacter(moveToText: false);
                }
                else
                {
                    ReadQuotedText(moveToText: false);
                }
            }
            while (_complexTextMode == JsonComplexTextMode.QuotedText);
            xmlAttributeNode.Value.SetValue(ValueHandleType.UTF8, offset, base.BufferReader.Offset - 1 - offset);
            SkipWhitespaceInBufferReader();
            if (base.BufferReader.GetByte() == 44)
            {
                base.BufferReader.SkipByte();
                _readServerTypeElement = true;
            }
        }
        if (base.BufferReader.GetByte() == 125)
        {
            base.BufferReader.SkipByte();
            _readServerTypeElement = false;
            _expectingFirstElementInNonPrimitiveChild = false;
        }
        else
        {
            _readServerTypeElement = true;
        }
    }
References System.Runtime.Serialization.Json.XmlJsonReader._buffered, System.Runtime.Serialization.Json.XmlJsonReader._complexTextMode, System.Runtime.Serialization.Json.XmlJsonReader._expectingFirstElementInNonPrimitiveChild, System.Runtime.Serialization.Json.XmlJsonReader._readServerTypeElement, System.Xml.XmlBaseReader.AddAttribute(), System.buffer, System.Runtime.Serialization.Json.XmlJsonReader.BufferElement(), System.Runtime.Serialization.Dictionary, System.offset, System.Runtime.Serialization.Json.XmlJsonReader.ReadEscapedCharacter(), System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText(), System.Runtime.Serialization.Json.XmlJsonReader.SkipExpectedByteInBufferReader(), System.Runtime.Serialization.Json.XmlJsonReader.SkipWhitespaceInBufferReader(), and System.Xml.XmlExceptionHelper.ThrowTokenExpected().
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes().