Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes
ReadAttributes()
void System.Runtime.Serialization.Json.XmlJsonReader.ReadAttributes () inline private
Definition at line 897 of file XmlJsonReader.cs.
    {
        XmlAttributeNode xmlAttributeNode = AddAttribute();
        xmlAttributeNode.LocalName.SetConstantValue(StringHandleConstStringType.Type);
        xmlAttributeNode.Namespace.Uri.SetValue(0, 0);
        xmlAttributeNode.Prefix.SetValue(PrefixHandleType.Empty);
        SkipWhitespaceInBufferReader();
        byte @byte = base.BufferReader.GetByte();
        switch (@byte)
        {
        case 34:
            if (!_expectingFirstElementInNonPrimitiveChild)
            {
                xmlAttributeNode.Value.SetConstantValue(ValueHandleConstStringType.String);
                return;
            }
            xmlAttributeNode.Value.SetConstantValue(ValueHandleConstStringType.Object);
            ReadServerTypeAttribute(consumedObjectChar: true);
            return;
        case 110:
            xmlAttributeNode.Value.SetConstantValue(ValueHandleConstStringType.Null);
            return;
        case 102:
        case 116:
            xmlAttributeNode.Value.SetConstantValue(ValueHandleConstStringType.Boolean);
            return;
        case 123:
            xmlAttributeNode.Value.SetConstantValue(ValueHandleConstStringType.Object);
            ReadServerTypeAttribute(consumedObjectChar: false);
            return;
        case 125:
            if (_expectingFirstElementInNonPrimitiveChild)
            {
                xmlAttributeNode.Value.SetConstantValue(ValueHandleConstStringType.Object);
            }
            else
            {
                XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, (char)@byte)));
            }
            return;
        case 91:
            xmlAttributeNode.Value.SetConstantValue(ValueHandleConstStringType.Array);
            base.BufferReader.SkipByte();
            EnterJsonScope(JsonNodeType.Collection);
            return;
        }
        switch (@byte)
        {
        default:
            if (@byte != 78 && @byte != 73)
            {
                XmlExceptionHelper.ThrowXmlException(this, new XmlException(System.SR.Format(System.SR.JsonEncounteredUnexpectedCharacter, (char)@byte)));
                break;
            }
            goto case 45;
        case 45:
        case 48:
        case 49:
        case 50:
        case 51:
        case 52:
        case 53:
        case 54:
        case 55:
        case 56:
        case 57:
            xmlAttributeNode.Value.SetConstantValue(ValueHandleConstStringType.Number);
            break;
        }
    }
References System.Runtime.Serialization.Json.XmlJsonReader._expectingFirstElementInNonPrimitiveChild, System.Xml.XmlBaseReader.AddAttribute(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.XmlJsonReader.EnterJsonScope(), System.SR.Format(), System.SR.JsonEncounteredUnexpectedCharacter, System.Runtime.Serialization.Json.XmlJsonReader.ReadServerTypeAttribute(), System.Runtime.Serialization.Json.XmlJsonReader.SkipWhitespaceInBufferReader(), System.Xml.XmlExceptionHelper.ThrowXmlException(), and System.Xml.XmlException.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.ParseStartElement(), and System.Runtime.Serialization.Json.XmlJsonReader.ReadNonExistentElementName().