Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ReadNumericalText
ReadNumericalText()
void System.Runtime.Serialization.Json.XmlJsonReader.ReadNumericalText () inline private
Definition at line 1086 of file XmlJsonReader.cs.
    {
        int offset;
        int offsetMax;
        int num;
        if (_buffered)
        {
            byte[] buffer = base.BufferReader.GetBuffer(out offset, out offsetMax);
            num = ComputeNumericalTextLength(buffer, offset, offsetMax);
        }
        else
        {
            byte[] buffer = base.BufferReader.GetBuffer(2048, out offset, out offsetMax);
            num = ComputeNumericalTextLength(buffer, offset, offsetMax);
            num = BreakText(buffer, offset, num);
        }
        base.BufferReader.Advance(num);
        if (offset <= offsetMax - num)
        {
            MoveToAtomicText().Value.SetValue(ValueHandleType.UTF8, offset, num);
            _complexTextMode = JsonComplexTextMode.None;
        }
        else
        {
            MoveToComplexText().Value.SetValue(ValueHandleType.UTF8, offset, num);
            _complexTextMode = JsonComplexTextMode.NumericalText;
        }
    }
References System.Runtime.Serialization.Json.XmlJsonReader._buffered, System.Runtime.Serialization.Json.XmlJsonReader._complexTextMode, System.Runtime.Serialization.Json.XmlJsonReader.BreakText(), System.buffer, System.Runtime.Serialization.Json.XmlJsonReader.ComputeNumericalTextLength(), System.Runtime.Serialization.Dictionary, System.Xml.XmlBaseReader.MoveToAtomicText(), System.Xml.XmlBaseReader.MoveToComplexText(), System.offset, System.Xml.ValueHandle.SetValue(), and System.Xml.XmlBaseReader.XmlNode.Value.
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.Read().