Terraria: System.Runtime.Serialization.Json.XmlJsonReader.MoveToInitial
MoveToInitial() [2/2]
void System.Runtime.Serialization.Json.XmlJsonReader.MoveToInitial (XmlDictionaryReaderQuotas quotas, OnXmlDictionaryReaderClose onClose) inline private
Definition at line 817 of file XmlJsonReader.cs.
    {
        MoveToInitial(quotas);
        _maxBytesPerRead = quotas.MaxBytesPerRead;
        _onReaderClose = onClose;
    }
References System.Runtime.Serialization.Json.XmlJsonReader._maxBytesPerRead, System.Runtime.Serialization.Json.XmlJsonReader._onReaderClose, System.Runtime.Serialization.Dictionary, and System.Runtime.Serialization.Json.XmlJsonReader.MoveToInitial().
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.MoveToInitial(), System.Runtime.Serialization.Json.XmlJsonReader.SetInput(), and System.Runtime.Serialization.Json.XmlJsonReader.SetInput().