Terraria: System.Runtime.Serialization.Json.XmlJsonReader.ParseAndSetLocalName
ParseAndSetLocalName()
void System.Runtime.Serialization.Json.XmlJsonReader.ParseAndSetLocalName () inline private
Definition at line 824 of file XmlJsonReader.cs.
    {
        XmlElementNode xmlElementNode = EnterScope();
        xmlElementNode.NameOffset = base.BufferReader.Offset;
        do
        {
            if (base.BufferReader.GetByte() == 92)
            {
                ReadEscapedCharacter(moveToText: false);
            }
            else
            {
                ReadQuotedText(moveToText: false);
            }
        }
        while (_complexTextMode == JsonComplexTextMode.QuotedText);
        int num = base.BufferReader.Offset - 1;
        xmlElementNode.LocalName.SetValue(xmlElementNode.NameOffset, num - xmlElementNode.NameOffset);
        xmlElementNode.NameLength = num - xmlElementNode.NameOffset;
        xmlElementNode.Namespace.Uri.SetValue(xmlElementNode.NameOffset, 0);
        xmlElementNode.Prefix.SetValue(PrefixHandleType.Empty);
        xmlElementNode.IsEmptyElement = false;
        xmlElementNode.ExitScope = false;
        xmlElementNode.BufferOffset = num;
        int @byte = base.BufferReader.GetByte(xmlElementNode.NameOffset);
        if ((CharTypes[@byte] & 1) == 0)
        {
            SetJsonNameWithMapping(xmlElementNode);
            return;
        }
        int num2 = 0;
        int num3 = xmlElementNode.NameOffset;
        while (num2 < xmlElementNode.NameLength)
        {
            @byte = base.BufferReader.GetByte(num3);
            if ((CharTypes[@byte] & 2) == 0 || @byte >= 128)
            {
                SetJsonNameWithMapping(xmlElementNode);
                break;
            }
            num2++;
            num3++;
        }
    }
References System.Runtime.Serialization.Json.XmlJsonReader._complexTextMode, System.Runtime.Serialization.Json.XmlJsonReader.CharTypes, System.Runtime.Serialization.Dictionary, System.Xml.XmlBaseReader.EnterScope(), System.Runtime.Serialization.Json.XmlJsonReader.ReadEscapedCharacter(), System.Runtime.Serialization.Json.XmlJsonReader.ReadQuotedText(), and System.Runtime.Serialization.Json.XmlJsonReader.SetJsonNameWithMapping().
Referenced by System.Runtime.Serialization.Json.XmlJsonReader.ParseStartElement().