Terraria: System.Xml.HtmlEncodedRawTextWriterIndent.WriteStartElement
WriteStartElement() [3/4]
override void System.Xml.HtmlEncodedRawTextWriterIndent.WriteStartElement (string prefix, string localName, string ns) inline
Definition at line 33 of file HtmlEncodedRawTextWriterIndent.cs.
    {
        if (_trackTextContent && _inTextContent)
        {
            ChangeTextContentMark(value: false);
        }
        _elementScope.Push((byte)_currentElementProperties);
        if (ns.Length == 0)
        {
            _currentElementProperties = (ElementProperties)HtmlEncodedRawTextWriter._elementPropertySearch.FindCaseInsensitiveString(localName);
            if (_endBlockPos == _bufPos && (_currentElementProperties & ElementProperties.BLOCK_WS) != 0)
            {
                WriteIndent();
            }
            _indentLevel++;
            _bufChars[_bufPos++] = '<';
        }
        else
        {
            _currentElementProperties = (ElementProperties)192u;
            if (_endBlockPos == _bufPos)
            {
                WriteIndent();
            }
            _indentLevel++;
            _bufChars[_bufPos++] = '<';
            if (prefix.Length != 0)
            {
                RawText(prefix);
                _bufChars[_bufPos++] = ':';
            }
        }
        RawText(localName);
        _attrEndPos = _bufPos;
    }
References System.Xml.XmlEncodedRawTextWriter._attrEndPos, System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.HtmlEncodedRawTextWriter._currentElementProperties, System.Xml.HtmlEncodedRawTextWriter._elementPropertySearch, System.Xml.HtmlEncodedRawTextWriter._elementScope, System.Xml.HtmlEncodedRawTextWriterIndent._endBlockPos, System.Xml.HtmlEncodedRawTextWriterIndent._indentLevel, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark(), System.Xml.Dictionary, System.prefix, System.Xml.ByteStack.Push(), System.Xml.XmlEncodedRawTextWriter.RawText(), System.value, and System.Xml.HtmlEncodedRawTextWriterIndent.WriteIndent().