Terraria: Terraria.IO.FavoritesFile.Save
Save()
void Terraria.IO.FavoritesFile.Save () inline
Definition at line 59 of file FavoritesFile.cs.
    {
        try
        {
            string s = JsonConvert.SerializeObject((object)_data, (Formatting)1);
            byte[] bytes = _ourEncoder.GetBytes(s);
            FileUtilities.WriteAllBytes(Path, bytes, IsCloudSave);
        }
        catch (Exception exception)
        {
            FancyErrorPrinter.ShowFileSavingFailError(exception, Path);
            throw;
        }
    }
References Terraria.IO.FavoritesFile._data, Terraria.IO.FavoritesFile._ourEncoder, System.bytes, System.exception, System.Text.UTF8Encoding.GetBytes(), Terraria.IO.FavoritesFile.IsCloudSave, Terraria.IO.FavoritesFile.Path, System.s, Terraria.UI.FancyErrorPrinter.ShowFileSavingFailError(), and Terraria.Utilities.FileUtilities.WriteAllBytes().
Referenced by Terraria.IO.FavoritesFile.ClearEntry(), and Terraria.IO.FavoritesFile.SaveFavorite().