Terraria: Terraria.IO.FavoritesFile.SaveFavorite
SaveFavorite()
void Terraria.IO.FavoritesFile.SaveFavorite (FileData fileData) inline
Definition at line 26 of file FavoritesFile.cs.
    {
        if (!_data.ContainsKey(fileData.Type))
        {
            _data.Add(fileData.Type, new Dictionary<string, bool>());
        }
        _data[fileData.Type][fileData.GetFileName()] = fileData.IsFavorite;
        Save();
    }
References Terraria.IO.FavoritesFile._data, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), and Terraria.IO.FavoritesFile.Save().