Terraria: Terraria.IO.FavoritesFile.Load
Load()
void Terraria.IO.FavoritesFile.Load () inline
Definition at line 74 of file FavoritesFile.cs.
    {
        if (!FileUtilities.Exists(Path, IsCloudSave))
        {
            _data.Clear();
            return;
        }
        try
        {
            byte[] bytes = FileUtilities.ReadAllBytes(Path, IsCloudSave);
            string @string;
            try
            {
                @string = _ourEncoder.GetString(bytes);
            }
            catch
            {
                @string = Encoding.ASCII.GetString(bytes);
            }
            _data = JsonConvert.DeserializeObject<Dictionary<string, Dictionary<string, bool>>>(@string);
            if (_data == null)
            {
                _data = new Dictionary<string, Dictionary<string, bool>>();
            }
        }
        catch (Exception)
        {
            Console.WriteLine("Unable to load favorites.json file ({0} : {1})", Path, IsCloudSave ? "Cloud Save" : "Local Save");
        }
    }
References Terraria.IO.FavoritesFile._data, Terraria.IO.FavoritesFile._ourEncoder, System.Text.Encoding.ASCII, System.bytes, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.Utilities.FileUtilities.Exists(), System.Text.UTF8Encoding.GetString(), Terraria.IO.FavoritesFile.IsCloudSave, Terraria.IO.FavoritesFile.Path, Terraria.Utilities.FileUtilities.ReadAllBytes(), and System.Console.WriteLine().