Terraria: LockOnHelper.SetActive
SetActive()
static void LockOnHelper.SetActive (bool on) inline static private
     {
         if (on)
         {
             if (CanEnable())
             {
                 RefreshTargets(Main.MouseWorld, 2000f);
                 GetClosestTarget(Main.MouseWorld);
                 if (_pickedTarget >= 0)
                 {
                     _enabled = true;
                 }
             }
         }
         else
         {
             _enabled = false;
             _targets.Clear();
             _lifeTimeCounter = 0;
             _threeDSTarget = -1;
             _targetClosestTarget = -1;
         }
     }
References _enabled, _lifeTimeCounter, _pickedTarget, _targetClosestTarget, _targets, _threeDSTarget, CanEnable(), GetClosestTarget(), Main.MouseWorld, and RefreshTargets().
Referenced by CycleTargetFocus(), CycleTargetThreeDS(), HandlePressing(), and Update().