Terraria: LockOnHelper.RefreshTargets
RefreshTargets()
static void LockOnHelper.RefreshTargets (Vector2 position, float radius) inline static private
     {
         _targets.Clear();
         Rectangle rectangle = Utils.CenteredRectangle(Main.player[Main.myPlayer].Center, new Vector2(1920f, 1200f));
         _ = Main.player[Main.myPlayer].Center;
         Main.player[Main.myPlayer].DirectionTo(Main.MouseWorld);
         for (int i = 0; i < Main.npc.Length; i++)
         {
             NPC nPC = Main.npc[i];
             if (ValidTarget(nPC) && !(nPC.Distance(position) > radius) && rectangle.Intersects(nPC.Hitbox) && !(Lighting.GetSubLight(nPC.Center).Length() / 3f < 0.03f))
             {
                 _targets.Add(i);
             }
         }
     }
References _targets, Entity.Center, Utils.CenteredRectangle(), Entity.DirectionTo(), Entity.Distance(), Lighting.GetSubLight(), Entity.Hitbox, Main.MouseWorld, Main.myPlayer, Main.npc, Main.player, and ValidTarget().
Referenced by CycleTargetFocus(), CycleTargetThreeDS(), FindMostViableTarget(), and SetActive().