Terraria: System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper
ChkCast_Helper()
static unsafe object System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper (void * toTypeHnd, object obj) inline static private
Definition at line 286 of file CastHelpers.cs.
    {
        CastResult castResult = TryGet((nuint)RuntimeHelpers.GetMethodTable(obj), (nuint)toTypeHnd);
        if (castResult == CastResult.CanCast)
        {
            return obj;
        }
        return ChkCastAny_NoCacheLookup(toTypeHnd, obj);
    }
References System.Runtime.CompilerServices.CastHelpers.ChkCastAny_NoCacheLookup(), System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable(), System.obj, and System.Runtime.CompilerServices.CastHelpers.TryGet().
Referenced by System.Runtime.CompilerServices.CastHelpers.ChkCastClassSpecial(), and System.Runtime.CompilerServices.CastHelpers.ChkCastInterface().