Terraria: System.Runtime.CompilerServices.CastHelpers.StelemRef_Helper_NoCacheLookup
StelemRef_Helper_NoCacheLookup()
static unsafe void System.Runtime.CompilerServices.CastHelpers.StelemRef_Helper_NoCacheLookup (ref object element, void * elementType, object obj) inline static private
Definition at line 490 of file CastHelpers.cs.
    {
        obj = IsInstanceOfAny_NoCacheLookup(elementType, obj);
        if (obj != null)
        {
            WriteBarrier(ref element, obj);
            return;
        }
        throw new ArrayTypeMismatchException();
    }
References System.elementType, System.Runtime.CompilerServices.CastHelpers.IsInstanceOfAny_NoCacheLookup(), System.obj, and System.Runtime.CompilerServices.CastHelpers.WriteBarrier().
Referenced by System.Runtime.CompilerServices.CastHelpers.StelemRef_Helper().