Terraria: System.Runtime.CompilerServices.CastHelpers.KeyToBucket
KeyToBucket()
static int System.Runtime.CompilerServices.CastHelpers.KeyToBucket (ref int tableData, nuint source, nuint target) inline static private
Definition at line 36 of file CastHelpers.cs.
    {
        int num = HashShift(ref tableData);
        ulong num2 = BitOperations.RotateLeft(source, 32) ^ target;
        return (int)((long)num2 * -7046029254386353131L >>> num);
    }
References System.Runtime.CompilerServices.CastHelpers.HashShift(), System.L, System.Numerics.BitOperations.RotateLeft(), and System.source.
Referenced by System.Runtime.CompilerServices.CastHelpers.TryGet().