Terraria: System.Runtime.CompilerServices.CastHelpers.StelemRef
StelemRef()
static unsafe void System.Runtime.CompilerServices.CastHelpers.StelemRef (Array array, int index, object obj) inline static private
Definition at line 449 of file CastHelpers.cs.
    {
        ref object value = ref Unsafe.As<ArrayElement[]>(array)[index].Value;
        void* elementType = RuntimeHelpers.GetMethodTable(array)->ElementType;
        if (obj != null)
        {
            if (elementType == RuntimeHelpers.GetMethodTable(obj) || array.GetType() == typeof(object[]))
            {
                WriteBarrier(ref value, obj);
            }
            else
            {
                StelemRef_Helper(ref value, elementType, obj);
            }
        }
        else
        {
            value = null;
        }
    }
References System.array, System.elementType, System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable(), System.index, System.obj, System.Runtime.CompilerServices.CastHelpers.StelemRef_Helper(), System.value, and System.Runtime.CompilerServices.CastHelpers.WriteBarrier().