Terraria: System.Runtime.CompilerServices.CastHelpers.IsInstance_Helper
IsInstance_Helper()
static unsafe object System.Runtime.CompilerServices.CastHelpers.IsInstance_Helper (void * toTypeHnd, object obj) inline static private
Definition at line 252 of file CastHelpers.cs.
    {
        return TryGet((nuint)RuntimeHelpers.GetMethodTable(obj), (nuint)toTypeHnd) switch
        {
            CastResult.CanCast => obj,
            CastResult.CannotCast => null,
            _ => IsInstanceOfAny_NoCacheLookup(toTypeHnd, obj),
        };
    }
References System.Runtime.CompilerServices.RuntimeHelpers.GetMethodTable(), System.Runtime.CompilerServices.CastHelpers.IsInstanceOfAny_NoCacheLookup(), System.obj, and System.Runtime.CompilerServices.CastHelpers.TryGet().
Referenced by System.Runtime.CompilerServices.CastHelpers.IsInstanceOfInterface().