Terraria: System.Runtime.CompilerServices.CastHelpers.TryGet
TryGet()
static CastResult System.Runtime.CompilerServices.CastHelpers.TryGet (nuint source, nuint target) inline static private
Definition at line 68 of file CastHelpers.cs.
    {
        ref int tableData = ref TableData(s_table);
        int num = KeyToBucket(ref tableData, source, target);
        int num2 = 0;
        while (num2 < 8)
        {
            ref CastCacheEntry reference = ref Element(ref tableData, num);
            int num3 = Volatile.Read(ref reference._version);
            nuint source2 = reference._source;
            num3 &= -2;
            if (source2 == source)
            {
                nuint targetAndResult = reference._targetAndResult;
                targetAndResult ^= target;
                if (targetAndResult <= 1)
                {
                    Interlocked.ReadMemoryBarrier();
                    if (num3 != reference._version)
                    {
                        break;
                    }
                    return (CastResult)targetAndResult;
                }
            }
            if (num3 == 0)
            {
                break;
            }
            num2++;
            num = (num + num2) & TableMask(ref tableData);
        }
        return CastResult.MaybeCast;
    }
References System.Runtime.CompilerServices.CastHelpers.Element(), System.Runtime.CompilerServices.CastHelpers.KeyToBucket(), System.Threading.Volatile.Read(), System.Threading.Interlocked.ReadMemoryBarrier(), System.Runtime.CompilerServices.CastHelpers.s_table, System.source, System.Runtime.CompilerServices.CastHelpers.TableData(), and System.Runtime.CompilerServices.CastHelpers.TableMask().
Referenced by System.Runtime.CompilerServices.CastHelpers.ChkCast_Helper(), System.Runtime.CompilerServices.CastHelpers.ChkCastAny(), System.Runtime.CompilerServices.CastHelpers.IsInstance_Helper(), System.Runtime.CompilerServices.CastHelpers.IsInstanceOfAny(), and System.Runtime.CompilerServices.CastHelpers.StelemRef_Helper().