Terraria: System.Data.SqlTypes.SqlString.StringCompare
StringCompare()
static int System.Data.SqlTypes.SqlString.StringCompare (SqlString x, SqlString y) inline static private
Definition at line 261 of file SqlString.cs.
    {
        if (x.m_lcid != y.m_lcid || x.m_flag != y.m_flag)
        {
            throw new SqlTypeException(SQLResource.CompareDiffCollationMessage);
        }
        x.SetCompareInfo();
        y.SetCompareInfo();
        if ((x.m_flag & SqlCompareOptions.BinarySort) != 0)
        {
            return CompareBinary(x, y);
        }
        if ((x.m_flag & SqlCompareOptions.BinarySort2) != 0)
        {
            return CompareBinary2(x, y);
        }
        string value = x.m_value;
        string value2 = y.m_value;
        int num = value.Length;
        int num2 = value2.Length;
        while (num > 0 && value[num - 1] == ' ')
        {
            num--;
        }
        while (num2 > 0 && value2[num2 - 1] == ' ')
        {
            num2--;
        }
        CompareOptions options = CompareOptionsFromSqlCompareOptions(x.m_flag);
        return x.m_cmpInfo.Compare(x.m_value, 0, num, y.m_value, 0, num2, options);
    }
References System.Globalization.CompareInfo.Compare(), System.Data.SqlTypes.SqlString.CompareBinary(), System.Data.SqlTypes.SqlString.CompareBinary2(), System.Data.SqlTypes.SQLResource.CompareDiffCollationMessage, System.Data.SqlTypes.SqlString.CompareOptionsFromSqlCompareOptions(), System.Xml.Dictionary, System.Data.SqlTypes.SqlString.m_cmpInfo, System.Data.SqlTypes.SqlString.m_flag, System.Data.SqlTypes.SqlString.m_lcid, System.Data.SqlTypes.SqlString.m_value, System.options, System.Data.SqlTypes.SqlString.SetCompareInfo(), and System.value.
Referenced by System.Data.SqlTypes.SqlString.Compare(), and System.Data.SqlTypes.SqlString.CompareTo().