Terraria: System.Data.SqlTypes.SqlString.CompareOptionsFromSqlCompareOptions
CompareOptionsFromSqlCompareOptions()
static CompareOptions System.Data.SqlTypes.SqlString.CompareOptionsFromSqlCompareOptions (SqlCompareOptions compareOptions) inline static
Definition at line 565 of file SqlString.cs.
    {
        CompareOptions compareOptions2 = CompareOptions.None;
        ValidateSqlCompareOptions(compareOptions);
        if ((compareOptions & (SqlCompareOptions.BinarySort | SqlCompareOptions.BinarySort2)) != 0)
        {
            throw ADP.ArgumentOutOfRange("compareOptions");
        }
        if ((compareOptions & SqlCompareOptions.IgnoreCase) != 0)
        {
            compareOptions2 |= CompareOptions.IgnoreCase;
        }
        if ((compareOptions & SqlCompareOptions.IgnoreNonSpace) != 0)
        {
            compareOptions2 |= CompareOptions.IgnoreNonSpace;
        }
        if ((compareOptions & SqlCompareOptions.IgnoreKanaType) != 0)
        {
            compareOptions2 |= CompareOptions.IgnoreKanaType;
        }
        if ((compareOptions & SqlCompareOptions.IgnoreWidth) != 0)
        {
            compareOptions2 |= CompareOptions.IgnoreWidth;
        }
        return compareOptions2;
    }
References System.Data.Common.ADP.ArgumentOutOfRange(), System.Xml.Dictionary, and System.Data.SqlTypes.SqlString.ValidateSqlCompareOptions().
Referenced by System.Data.SqlTypes.SqlString.GetHashCode(), and System.Data.SqlTypes.SqlString.StringCompare().