Terraria: System.Data.SqlTypes.SqlString.Compare
Compare()
static SqlBoolean System.Data.SqlTypes.SqlString.Compare (SqlString x, SqlString y, EComparison ecExpectedResult) inline static private
Definition at line 293 of file SqlString.cs.
    {
        if (x.IsNull || y.IsNull)
        {
            return SqlBoolean.Null;
        }
        int num = StringCompare(x, y);
        bool flag = false;
        switch (ecExpectedResult)
        {
        case EComparison.EQ:
            flag = num == 0;
            break;
        case EComparison.LT:
            flag = num < 0;
            break;
        case EComparison.LE:
            flag = num <= 0;
            break;
        case EComparison.GT:
            flag = num > 0;
            break;
        case EComparison.GE:
            flag = num >= 0;
            break;
        default:
            return SqlBoolean.Null;
        }
        return new SqlBoolean(flag);
    }
References System.Xml.Dictionary, System.Data.SqlTypes.SqlString.IsNull, System.Data.SqlTypes.SqlBoolean.Null, System.Data.Common.SqlBoolean, and System.Data.SqlTypes.SqlString.StringCompare().
Referenced by System.Data.SqlTypes.SqlString.operator<(), System.Data.SqlTypes.SqlString.operator<=(), System.Data.SqlTypes.SqlString.operator==(), System.Data.SqlTypes.SqlString.operator>(), and System.Data.SqlTypes.SqlString.operator>=().