Terraria: System.Data.SqlTypes.SqlString.CompareTo
CompareTo() [1/3]
int System.Data.SqlTypes.SqlString.CompareTo (object? value) inline
Implements System.IComparable< in T >.
Definition at line 705 of file SqlString.cs.
    {
        if (value is SqlString value2)
        {
            return CompareTo(value2);
        }
        throw ADP.WrongType(value.GetType(), typeof(SqlString));
    }
References System.Data.SqlTypes.SqlString.CompareTo(), System.Xml.Dictionary, System.value, and System.Data.Common.ADP.WrongType().
Referenced by System.Data.SqlTypes.SqlString.CompareTo().