Terraria: System.Data.SqlTypes.SqlString.GetHashCode
GetHashCode()
override int System.Data.SqlTypes.SqlString.GetHashCode () inline
Definition at line 757 of file SqlString.cs.
    {
        if (IsNull)
        {
            return 0;
        }
        byte[] array;
        if (FBinarySort())
        {
            array = s_unicodeEncoding.GetBytes(m_value.TrimEnd());
        }
        else
        {
            CompareInfo compareInfo;
            CompareOptions options;
            try
            {
                SetCompareInfo();
                compareInfo = m_cmpInfo;
                options = CompareOptionsFromSqlCompareOptions(m_flag);
            }
            catch (ArgumentException)
            {
                compareInfo = System.Globalization.CultureInfo.InvariantCulture.CompareInfo;
                options = CompareOptions.None;
            }
            array = compareInfo.GetSortKey(m_value.TrimEnd(), options).KeyData;
        }
        return SqlBinary.HashByteArray(array, array.Length);
    }
References System.array, System.Data.SqlTypes.SqlString.CompareOptionsFromSqlCompareOptions(), System.Xml.Dictionary, System.Data.SqlTypes.SqlString.FBinarySort(), System.Data.SqlTypes.SqlBinary.HashByteArray(), System.Globalization.CultureInfo.InvariantCulture, System.Data.SqlTypes.SqlString.IsNull, System.Data.SqlTypes.SqlString.m_cmpInfo, System.Data.SqlTypes.SqlString.m_flag, System.Data.SqlTypes.SqlString.m_value, System.options, System.Data.SqlTypes.SqlString.s_unicodeEncoding, and System.Data.SqlTypes.SqlString.SetCompareInfo().