Terraria: System.Net.Mime.SmtpDateTime.TryParseTimeZoneString
TryParseTimeZoneString()
bool System.Net.Mime.SmtpDateTime.TryParseTimeZoneString (string timeZoneString, out TimeSpan timeZone) inline package
Definition at line 154 of file SmtpDateTime.cs.
    {
        if (timeZoneString == "-0000")
        {
            timeZone = TimeSpan.Zero;
            return false;
        }
        if (timeZoneString[0] == '+' || timeZoneString[0] == '-')
        {
            ValidateAndGetTimeZoneOffsetValues(timeZoneString, out var positive, out var hours, out var minutes);
            if (!positive)
            {
                if (hours != 0)
                {
                    hours *= -1;
                }
                else if (minutes != 0)
                {
                    minutes *= -1;
                }
            }
            timeZone = new TimeSpan(hours, minutes, 0);
            return true;
        }
        ValidateTimeZoneShortHandValue(timeZoneString);
        return s_timeZoneOffsetLookup.TryGetValue(timeZoneString, out timeZone);
    }
References System.Net.Mime.SmtpDateTime.s_timeZoneOffsetLookup, System.Net.Mime.SmtpDateTime.ValidateAndGetTimeZoneOffsetValues(), System.Net.Mime.SmtpDateTime.ValidateTimeZoneShortHandValue(), and System.TimeSpan.Zero.
Referenced by System.Net.Mime.SmtpDateTime.SmtpDateTime().