Terraria: System.Reflection.Emit.DynamicResolver.GetEHInfo
GetEHInfo()
unsafe override void System.Reflection.Emit.DynamicResolver.GetEHInfo (int excNumber, void * exc) inline package
Definition at line 160 of file DynamicResolver.cs.
    {
        for (int i = 0; i < m_exceptions.Length; i++)
        {
            int numberOfCatches = m_exceptions[i].GetNumberOfCatches();
            if (excNumber < numberOfCatches)
            {
                ((CORINFO_EH_CLAUSE*)exc)->Flags = m_exceptions[i].GetExceptionTypes()[excNumber];
                ((CORINFO_EH_CLAUSE*)exc)->TryOffset = m_exceptions[i].GetStartAddress();
                if ((((CORINFO_EH_CLAUSE*)exc)->Flags & 2) != 2)
                {
                    ((CORINFO_EH_CLAUSE*)exc)->TryLength = m_exceptions[i].GetEndAddress() - ((CORINFO_EH_CLAUSE*)exc)->TryOffset;
                }
                else
                {
                    ((CORINFO_EH_CLAUSE*)exc)->TryLength = m_exceptions[i].GetFinallyEndAddress() - ((CORINFO_EH_CLAUSE*)exc)->TryOffset;
                }
                ((CORINFO_EH_CLAUSE*)exc)->HandlerOffset = m_exceptions[i].GetCatchAddresses()[excNumber];
                ((CORINFO_EH_CLAUSE*)exc)->HandlerLength = m_exceptions[i].GetCatchEndAddresses()[excNumber] - ((CORINFO_EH_CLAUSE*)exc)->HandlerOffset;
                ((CORINFO_EH_CLAUSE*)exc)->ClassTokenOrFilterOffset = m_exceptions[i].GetFilterAddresses()[excNumber];
                break;
            }
            excNumber -= numberOfCatches;
        }
    }
References System.Reflection.Emit.__ExceptionInfo.GetCatchAddresses(), System.Reflection.Emit.__ExceptionInfo.GetCatchEndAddresses(), System.Reflection.Emit.__ExceptionInfo.GetEndAddress(), System.Reflection.Emit.__ExceptionInfo.GetExceptionTypes(), System.Reflection.Emit.__ExceptionInfo.GetFilterAddresses(), System.Reflection.Emit.__ExceptionInfo.GetFinallyEndAddress(), System.Reflection.Emit.__ExceptionInfo.GetNumberOfCatches(), System.Reflection.Emit.__ExceptionInfo.GetStartAddress(), and System.Reflection.Emit.DynamicResolver.m_exceptions.