Terraria: System.Net.Mime.SmtpDateTime.ParseValue
ParseValue()
DateTime System.Net.Mime.SmtpDateTime.ParseValue (string data, out string timeZone) inline package
Definition at line 119 of file SmtpDateTime.cs.
    {
        if (string.IsNullOrEmpty(data))
        {
            throw new FormatException(System.SR.MailDateInvalidFormat);
        }
        int num = data.IndexOf(':');
        if (num == -1)
        {
            throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, data));
        }
        int num2 = data.IndexOfAny(s_allowedWhiteSpaceChars, num);
        if (num2 == -1)
        {
            throw new FormatException(System.SR.Format(System.SR.MailHeaderFieldInvalidCharacter, data));
        }
        string s = data.AsSpan(0, num2).Trim().ToString();
        if (!DateTime.TryParseExact(s, s_validDateTimeFormats, CultureInfo.InvariantCulture, DateTimeStyles.AllowWhiteSpaces, out var result))
        {
            throw new FormatException(System.SR.MailDateInvalidFormat);
        }
        string text = data.AsSpan(num2).Trim().ToString();
        int num3 = text.IndexOfAny(s_allowedWhiteSpaceChars);
        if (num3 != -1)
        {
            text = text.Substring(0, num3);
        }
        if (string.IsNullOrEmpty(text))
        {
            throw new FormatException(System.SR.MailDateInvalidFormat);
        }
        timeZone = text;
        return result;
    }
References System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.SR.MailDateInvalidFormat, System.SR.MailHeaderFieldInvalidCharacter, System.s, System.Net.Mime.SmtpDateTime.s_allowedWhiteSpaceChars, System.Net.Mime.SmtpDateTime.s_validDateTimeFormats, System.text, and System.DateTime.TryParseExact().
Referenced by System.Net.Mime.SmtpDateTime.SmtpDateTime().