Terraria: System.Net.Mime.SmtpDateTime.TimeSpanToOffset
TimeSpanToOffset()
string System.Net.Mime.SmtpDateTime.TimeSpanToOffset (TimeSpan span) inline package
Definition at line 192 of file SmtpDateTime.cs.
    {
        if (span.Ticks == 0L)
        {
            return "+0000";
        }
        uint num = (uint)Math.Abs(Math.Floor(span.TotalHours));
        uint num2 = (uint)Math.Abs(span.Minutes);
        string text = ((span.Ticks > 0) ? "+" : "-");
        if (num < 10)
        {
            text += "0";
        }
        text += num;
        if (num2 < 10)
        {
            text += "0";
        }
        return text + num2;
    }
References System.Math.Abs(), System.Math.Floor(), System.L, and System.text.
Referenced by System.Net.Mime.SmtpDateTime.ToString().