Terraria: System.Reflection.Emit.DynamicResolver.DynamicResolver
DynamicResolver() [1/2]
System.Reflection.Emit.DynamicResolver.DynamicResolver (DynamicILGenerator ilGenerator) inline package
Definition at line 49 of file DynamicResolver.cs.
    {
        m_stackSize = ilGenerator.GetMaxStackSize();
        m_exceptions = ilGenerator.GetExceptions();
        m_code = ilGenerator.BakeByteArray();
        m_localSignature = ilGenerator.m_localSignature.InternalGetSignatureArray();
        m_scope = ilGenerator.m_scope;
        m_method = (DynamicMethod)ilGenerator.m_methodBuilder;
        m_method.m_resolver = this;
    }
References System.Reflection.Emit.ILGenerator.BakeByteArray(), System.Reflection.Emit.ILGenerator.GetExceptions(), System.Reflection.Emit.ILGenerator.GetMaxStackSize(), System.Reflection.Emit.SignatureHelper.InternalGetSignatureArray(), System.Reflection.Emit.DynamicResolver.m_code, System.Reflection.Emit.DynamicResolver.m_exceptions, System.Reflection.Emit.DynamicResolver.m_localSignature, System.Reflection.Emit.ILGenerator.m_localSignature, System.Reflection.Emit.DynamicResolver.m_method, System.Reflection.Emit.ILGenerator.m_methodBuilder, System.Reflection.Emit.DynamicILGenerator.m_scope, System.Reflection.Emit.DynamicResolver.m_scope, and System.Reflection.Emit.DynamicResolver.m_stackSize.