Terraria: BiomePreferenceListTrait.ApplyPreference
ApplyPreference()
void BiomePreferenceListTrait.ApplyPreference (BiomePreference preference, HelperInfo info, ShopHelper shopHelperInstance) inline private
     {
         string nameKey = preference.Biome.NameKey;
         switch (preference.Affection)
         {
         case AffectionLevel.Love:
             shopHelperInstance.LoveBiome(nameKey);
             break;
         case AffectionLevel.Like:
             shopHelperInstance.LikeBiome(nameKey);
             break;
         case AffectionLevel.Dislike:
             shopHelperInstance.DislikeBiome(nameKey);
             break;
         case AffectionLevel.Hate:
             shopHelperInstance.HateBiome(nameKey);
             break;
         }
     }
References BiomePreferenceListTrait.BiomePreference.Affection, BiomePreferenceListTrait.BiomePreference.Biome, ShopHelper.DislikeBiome(), ShopHelper.HateBiome(), ShopHelper.LikeBiome(), ShopHelper.LoveBiome(), and AShoppingBiome.NameKey.
Referenced by ModifyShopPrice().