Terraria: PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers
DrawPlayer_RenderAllLayers()
static void PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers (ref PlayerDrawHeadSet drawinfo) inline static
     {
         List<DrawData> drawData = drawinfo.DrawData;
         Effect pixelShader = Main.pixelShader;
         _ = Main.projectile;
         SpriteBatch spriteBatch = Main.spriteBatch;
         for (int i = 0; i < drawData.Count; i++)
         {
             DrawData cdd = drawData[i];
             if (!cdd.sourceRect.HasValue)
             {
                 cdd.sourceRect = cdd.texture.Frame();
             }
             PlayerDrawHelper.SetShaderForData(drawinfo.drawPlayer, drawinfo.cHead, ref cdd);
             if (cdd.texture != null)
             {
                 cdd.Draw(spriteBatch);
             }
         }
         pixelShader.CurrentTechnique.Passes[0].Apply();
     }
References DrawData.Draw(), Main.pixelShader, Main.projectile, PlayerDrawHelper.SetShaderForData(), DrawData.sourceRect, Main.spriteBatch, and DrawData.texture.
Referenced by LegacyPlayerRenderer.DrawPlayerHead(), and PlayerHeadDrawRenderTargetContent.DrawTheContent().