Terraria: PlayerDrawHeadLayers.DrawPlayer_04_BadgersHat
DrawPlayer_04_BadgersHat()
static void PlayerDrawHeadLayers.DrawPlayer_04_BadgersHat (ref PlayerDrawHeadSet drawinfo) inline static
     {
         int verticalFrames = 6;
         Texture2D value = TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value;
         Rectangle rectangle = value.Frame(1, verticalFrames, 0, drawinfo.drawPlayer.rabbitOrderFrame.DisplayFrame);
         Vector2 origin = rectangle.Size() / 2f;
         int num = 1;
         Vector2 vector = DrawPlayer_04_GetHatDrawPosition(ref drawinfo, new Vector2(0f, -9f), num);
         int hatStacks = GetHatStacks(ref drawinfo, 5004);
         float num2 = (float)Math.PI / 60f;
         float num3 = num2 * drawinfo.drawPlayer.position.X % ((float)Math.PI * 2f);
         int num4 = hatStacks * 4 + 2;
         int num5 = 0;
         bool flag = (Main.GlobalTimeWrappedHourly + 180f) % 600f < 60f;
         for (int num6 = num4 - 1; num6 >= 0; num6--)
         {
             int num7 = 0;
             if (num6 == num4 - 1)
             {
                 rectangle.Y = 0;
                 num7 = 2;
             }
             else if (num6 == 0)
             {
                 rectangle.Y = rectangle.Height * 5;
             }
             else
             {
                 rectangle.Y = rectangle.Height * (num5++ % 4 + 1);
             }
             if (!(rectangle.Y == rectangle.Height * 3 && flag))
             {
                 float x = Vector2.UnitY.RotatedBy(num3 + num2 * (float)num6).X * ((float)num6 / 10f) * 4f - (float)num6 * 0.1f * (float)drawinfo.drawPlayer.direction;
                 QuickCDD(drawinfo.DrawData, drawinfo.cHead, value, vector + new Vector2(x, (num6 * -4 + num7) * num) * drawinfo.scale, rectangle, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, origin, drawinfo.scale, drawinfo.playerEffect, 0f);
             }
         }
     }
References TextureAssets.ArmorHead, DrawPlayer_04_GetHatDrawPosition(), GetHatStacks(), Main.GlobalTimeWrappedHourly, QuickCDD(), Asset< T >.Value, and X.
Referenced by DrawPlayer_06_NormalHats().