Terraria: PlayerDrawHeadLayers.DrawPlayer_05_TallHats
DrawPlayer_05_TallHats()
static void PlayerDrawHeadLayers.DrawPlayer_05_TallHats (ref PlayerDrawHeadSet drawinfo) inline static
     {
         if (drawinfo.helmetIsTall)
         {
             Rectangle hairFrame = drawinfo.HairFrame;
             if (drawinfo.drawPlayer.head == 158)
             {
                 hairFrame.Height -= 2;
             }
             int num = 0;
             if (hairFrame.Y == hairFrame.Height * 6)
             {
                 hairFrame.Height -= 2;
             }
             else if (hairFrame.Y == hairFrame.Height * 7)
             {
                 num = -2;
             }
             else if (hairFrame.Y == hairFrame.Height * 8)
             {
                 num = -2;
             }
             else if (hairFrame.Y == hairFrame.Height * 9)
             {
                 num = -2;
             }
             else if (hairFrame.Y == hairFrame.Height * 10)
             {
                 num = -2;
             }
             else if (hairFrame.Y == hairFrame.Height * 13)
             {
                 hairFrame.Height -= 2;
             }
             else if (hairFrame.Y == hairFrame.Height * 14)
             {
                 num = -2;
             }
             else if (hairFrame.Y == hairFrame.Height * 15)
             {
                 num = -2;
             }
             else if (hairFrame.Y == hairFrame.Height * 16)
             {
                 num = -2;
             }
             hairFrame.Y += num;
             Color color = drawinfo.colorArmorHead;
             int shaderTechnique = drawinfo.cHead;
             if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
             {
                 color = ((!drawinfo.drawPlayer.isDisplayDollOrInanimate) ? drawinfo.colorHead : drawinfo.colorDisplayDollSkin);
                 shaderTechnique = drawinfo.skinDyePacked;
             }
             QuickCDD(drawinfo.DrawData, shaderTechnique, TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f + (float)num) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, hairFrame, color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
         }
     }
References TextureAssets.ArmorHead, Color, QuickCDD(), Main.screenPosition, ArmorIDs.Head.Sets.UseSkinColor, and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayerHead(), and PlayerHeadDrawRenderTargetContent.DrawTheContent().