Terraria: System.Text.DecoderFallbackBufferHelper.InternalFallback
InternalFallback() [2/2]
unsafe bool System.Text.DecoderFallbackBufferHelper.InternalFallback (byte[] bytes, byte * pBytes, ref char * chars) inline package
Definition at line 30 of file DecoderFallbackBufferHelper.cs.
    {
        if (_fallbackBuffer.Fallback(bytes, (int)(pBytes - byteStart - bytes.Length)))
        {
            char* ptr = chars;
            bool flag = false;
            char nextChar;
            while ((nextChar = _fallbackBuffer.GetNextChar()) != 0)
            {
                if (char.IsSurrogate(nextChar))
                {
                    if (char.IsHighSurrogate(nextChar))
                    {
                        if (flag)
{
                            throw new ArgumentException(System.SR.Argument_InvalidCharSequenceNoIndex);
                        }
                        flag = true;
                    }
                    else
                    {
                        if (!flag)
{
                            throw new ArgumentException(System.SR.Argument_InvalidCharSequenceNoIndex);
                        }
                        flag = false;
                    }
                }
                if (ptr >= charEnd)
                {
                    return false;
                }
                *(ptr++) = nextChar;
            }
            if (flag)
            {
                throw new ArgumentException(System.SR.Argument_InvalidCharSequenceNoIndex);
            }
            chars = ptr;
        }
        return true;
    }
References System.Text.DecoderFallbackBufferHelper._fallbackBuffer, System.SR.Argument_InvalidCharSequenceNoIndex, System.bytes, System.Text.DecoderFallbackBufferHelper.byteStart, System.Text.DecoderFallbackBufferHelper.charEnd, System.chars, System.Text.DecoderFallbackBuffer.Fallback(), and System.Text.DecoderFallbackBuffer.GetNextChar().
Referenced by System.Text.EncodingCharBuffer.Fallback(), System.Text.DBCSCodePageEncoding.GetCharCount(), System.Text.SBCSCodePageEncoding.GetCharCount(), System.Text.DBCSCodePageEncoding.GetChars(), and System.Text.SBCSCodePageEncoding.GetChars().