Terraria: System.Text.DecoderFallbackBufferHelper.InternalReset
InternalReset()
unsafe void System.Text.DecoderFallbackBufferHelper.InternalReset () inline package
Definition at line 18 of file DecoderFallbackBufferHelper.cs.
    {
        byteStart = null;
        _fallbackBuffer.Reset();
    }
References System.Text.DecoderFallbackBufferHelper._fallbackBuffer, System.Text.DecoderFallbackBufferHelper.byteStart, and System.Text.DecoderFallbackBuffer.Reset().
Referenced by System.Text.EncodingCharBuffer.Fallback(), System.Text.DBCSCodePageEncoding.GetChars(), and System.Text.SBCSCodePageEncoding.GetChars().