Terraria: RazerMouse.Present
Present()
override void RazerMouse.Present () inline virtual
Implements RgbDevice.
     {
         //IL_0012: Unknown result type (might be due to invalid IL or missing references)
         for (int i = 0; i < base.LedCount; i++)
         {
             _effect.Color[i] = RazerHelper.Vector4ToDeviceColor(GetProcessedLedColor(i));
         }
         _handle.SetAsMouseEffect(ref _effect);
         _handle.Apply();
     }
References _effect, _handle, EffectHandle.Apply(), RgbDevice.GetProcessedLedColor(), EffectHandle.SetAsMouseEffect(), and RazerHelper.Vector4ToDeviceColor().