Terraria: CreativePowerManager.Instance
Instance
readonly CreativePowerManager CreativePowerManager.Instance = new CreativePowerManager() static
Referenced by WorldGen.clearWorld(), UICreativePowersMenu.CreateMainPowerStrip(), UICreativePowersMenu.CreatePersonalPowerStrip(), UICreativePowersMenu.CreateSubcategoryButton< T >(), UICreativePowersMenu.CreateTimePowerStrip(), UICreativePowersMenu.CreateWeatherPowerStrip(), Projectile.Damage(), NetCreativePowerPermissionsModule.Deserialize(), NetCreativePowersModule.Deserialize(), Player.Deserialize(), MessageBuffer.GetData(), Player.GetItemGrabRange(), WorldGen.GetWorldUpdateRate(), Player.GrabItems(), Initialize(), WorldFile.LoadCreativePowers(), Player.OpenBossBag(), UICreativePowersMenu.PersonalCategoryButtonClick(), Player.ResetEffects(), WorldFile.SaveCreativePowers(), NPC.ScaleStats(), Player.Serialize(), Player.SetPlayerDataToOutOfClassFields(), UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty(), NPC.SlimeRainSpawns(), NPC.SpawnNPC(), UICreativePowersMenu.TimeCategoryButtonClick(), TryListingPermissionsFrom(), Player.Update(), Main.UpdateCreativeGameModeOverride(), Main.UpdateTime(), Main.UpdateTimeRate(), Main.UpdateWeather(), WorldGen.UpdateWorld(), WorldFile.ValidateWorld(), and UICreativePowersMenu.WeatherCategoryButtonClick().