Terraria: System.Random.Net5CompatDerivedImpl.NextUInt64
NextUInt64()
ulong System.Random.Net5CompatDerivedImpl.NextUInt64 () inline private
Definition at line 297 of file Random.cs.
        {
            return (uint)_parent.Next(4194304) | ((ulong)(uint)_parent.Next(4194304) << 22) | ((ulong)(uint)_parent.Next(1048576) << 44);
        }
References System.Random.Net5CompatDerivedImpl._parent, and System.Random.Next().
Referenced by System.Random.Net5CompatDerivedImpl.NextInt64(), and System.Random.Net5CompatDerivedImpl.NextInt64().