Terraria: System.Xml.Schema.BaseValidator.ProcessEntity
ProcessEntity() [2/2]
static void System.Xml.Schema.BaseValidator.ProcessEntity (SchemaInfo sinfo, string name, object sender, ValidationEventHandler eventhandler, string baseUri, int lineNumber, int linePosition) inline static protected inherited
Definition at line 262 of file BaseValidator.cs.
    {
        XmlSchemaException ex = null;
        if (!sinfo.GeneralEntities.TryGetValue(new XmlQualifiedName(name), out var value))
        {
            ex = new XmlSchemaException(System.SR.Sch_UndeclaredEntity, name, baseUri, lineNumber, linePosition);
        }
        else if (value.NData.IsEmpty)
        {
            ex = new XmlSchemaException(System.SR.Sch_UnparsedEntityRef, name, baseUri, lineNumber, linePosition);
        }
        if (ex != null)
        {
            if (eventhandler == null)
            {
                throw ex;
            }
            eventhandler(sender, new ValidationEventArgs(ex));
        }
    }
References System.Xml.Dictionary, System.SR.Sch_UndeclaredEntity, System.SR.Sch_UnparsedEntityRef, and System.value.
Referenced by System.Xml.Schema.DtdValidator.CheckDefaultValue(), System.Xml.Schema.XdrValidator.CheckDefaultValue(), System.Xml.Schema.DtdValidator.ProcessTokenizedType(), System.Xml.Schema.XdrValidator.ProcessTokenizedType(), and System.Xml.Schema.XsdValidator.ProcessTokenizedType().