Terraria: System.Xml.Schema.BaseValidator.ValidateText
ValidateText()
void System.Xml.Schema.BaseValidator.ValidateText () inline inherited
Definition at line 146 of file BaseValidator.cs.
    {
        if (!context.NeedValidateChildren)
        {
            return;
        }
        if (context.IsNill)
        {
            SendValidationEvent(System.SR.Sch_ContentInNill, XmlSchemaValidator.QNameString(context.LocalName, context.Namespace));
            return;
        }
        ContentValidator contentValidator = context.ElementDecl.ContentValidator;
        switch (contentValidator.ContentType)
        {
        case XmlSchemaContentType.ElementOnly:
        {
            ArrayList arrayList = contentValidator.ExpectedElements(context, isRequiredOnly: false);
            if (arrayList == null)
            {
                SendValidationEvent(System.SR.Sch_InvalidTextInElement, XmlSchemaValidator.BuildElementName(context.LocalName, context.Namespace));
                break;
            }
            SendValidationEvent(System.SR.Sch_InvalidTextInElementExpecting, new string[2]
            {
                XmlSchemaValidator.BuildElementName(context.LocalName, context.Namespace),
                XmlSchemaValidator.PrintExpectedElements(arrayList, getParticles: false)
            });
            break;
        }
        case XmlSchemaContentType.Empty:
            SendValidationEvent(System.SR.Sch_InvalidTextInEmpty, string.Empty);
            break;
        }
        if (checkDatatype)
        {
            SaveTextValue(reader.Value);
        }
    }
References System.Xml.Schema.XmlSchemaValidator.BuildElementName(), System.Xml.Schema.BaseValidator.checkDatatype, System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Schema.BaseValidator.context, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ValidationState.IsNill, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.ValidationState.NeedValidateChildren, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.Xml.Schema.BaseValidator.reader, System.Xml.Schema.BaseValidator.SaveTextValue(), System.SR.Sch_ContentInNill, System.SR.Sch_InvalidTextInElement, System.SR.Sch_InvalidTextInElementExpecting, System.SR.Sch_InvalidTextInEmpty, System.Xml.Schema.BaseValidator.SendValidationEvent(), and System.Xml.XmlValidatingReaderImpl.Value.
Referenced by System.Xml.Schema.DtdValidator.Validate(), System.Xml.Schema.XdrValidator.Validate(), and System.Xml.Schema.XsdValidator.Validate().