Terraria: System.Xml.Schema.BaseValidator.SendValidationEvent
SendValidationEvent() [1/7]
void System.Xml.Schema.BaseValidator.SendValidationEvent (string code) inline protected inherited
Definition at line 220 of file BaseValidator.cs.
    {
        SendValidationEvent(code, string.Empty);
    }
References System.Xml.Dictionary, and System.Xml.Schema.BaseValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XsdValidator.AddIdentityConstraints(), System.Xml.Schema.XsdValidator.AttributeIdentityConstraints(), System.Xml.Schema.DtdValidator.CheckForwardRefs(), System.Xml.Schema.XdrValidator.CheckForwardRefs(), System.Xml.Schema.XsdValidator.CheckForwardRefs(), System.Xml.Schema.DtdValidator.CheckValue(), System.Xml.Schema.XdrValidator.CheckValue(), System.Xml.Schema.XsdValidator.CheckValue(), System.Xml.Schema.XdrValidator.CompleteValidation(), System.Xml.Schema.XsdValidator.ElementIdentityConstraints(), System.Xml.Schema.XsdValidator.EndElementIdentityConstraints(), System.Xml.Schema.DtdValidator.GenEntity(), System.Xml.Schema.XdrValidator.LoadSchemaFromLocation(), System.Xml.Schema.XsdValidator.LoadSchemaFromLocation(), System.Xml.Schema.DtdValidator.MeetsStandAloneConstraint(), System.Xml.Schema.DtdValidator.ProcessElement(), System.Xml.Schema.XsdValidator.ProcessElement(), System.Xml.Schema.XsdValidator.ProcessInlineSchema(), System.Xml.Schema.DtdValidator.ProcessTokenizedType(), System.Xml.Schema.XdrValidator.ProcessTokenizedType(), System.Xml.Schema.XsdValidator.ProcessTokenizedType(), System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.BaseValidator.SendValidationEvent(), System.Xml.Schema.XdrValidator.ThoroughGetElementDecl(), System.Xml.Schema.XsdValidator.ThoroughGetElementDecl(), System.Xml.Schema.DtdValidator.Validate(), System.Xml.Schema.XsdValidator.ValidateChildElement(), System.Xml.Schema.DtdValidator.ValidateElement(), System.Xml.Schema.DtdValidator.ValidateEndStartElement(), System.Xml.Schema.XdrValidator.ValidateEndStartElement(), System.Xml.Schema.XsdValidator.ValidateEndStartElement(), System.Xml.Schema.DtdValidator.ValidatePIComment(), System.Xml.Schema.DtdValidator.ValidateStartElement(), System.Xml.Schema.XdrValidator.ValidateStartElement(), System.Xml.Schema.XsdValidator.ValidateStartElement(), System.Xml.Schema.BaseValidator.ValidateText(), and System.Xml.Schema.BaseValidator.ValidateWhitespace().