Terraria: Terraria.GameContent.TilePaintSystemV2.TileRenderTargetHolder.PrepareShader
PrepareShader() [1/2]
override void Terraria.GameContent.TilePaintSystemV2.TileRenderTargetHolder.PrepareShader () inline
Definition at line 124 of file TilePaintSystemV2.cs.
        {
            PrepareShader(Key.PaintColor, TreePaintSystemData.GetTileSettings(Key.TileType, Key.TileStyle));
        }
References Terraria.GameContent.TreePaintSystemData.GetTileSettings(), Terraria.GameContent.TilePaintSystemV2.TileRenderTargetHolder.Key, Terraria.GameContent.TilePaintSystemV2.TileVariationkey.PaintColor, Terraria.GameContent.TilePaintSystemV2.TileRenderTargetHolder.PrepareShader(), Terraria.GameContent.TilePaintSystemV2.TileVariationkey.TileStyle, and Terraria.GameContent.TilePaintSystemV2.TileVariationkey.TileType.
Referenced by Terraria.GameContent.TilePaintSystemV2.TileRenderTargetHolder.PrepareShader().