Terraria: PortalHelper.FindCollision
FindCollision()
static Vector2 PortalHelper.FindCollision (Vector2 startPosition, Vector2 stopPosition) inline static private
     {
         int lastX = 0;
         int lastY = 0;
         Utils.PlotLine(startPosition.ToTileCoordinates(), stopPosition.ToTileCoordinates(), delegate(int x, int y)
         {
             lastX = x;
             lastY = y;
             return !WorldGen.SolidOrSlopedTile(x, y);
         }, jump: false);
         return new Vector2((float)lastX * 16f, (float)lastY * 16f);
     }
References Utils.PlotLine(), and WorldGen.SolidOrSlopedTile().
Referenced by TryPlacingPortal().