Terraria: System.Resources.ResourceReader.LoadObjectV1
LoadObjectV1()
object System.Resources.ResourceReader.LoadObjectV1 (int pos) inline package
Definition at line 633 of file ResourceReader.cs.
    {
        try
        {
            return _LoadObjectV1(pos);
        }
        catch (EndOfStreamException inner)
        {
            throw new BadImageFormatException(SR.BadImageFormat_TypeMismatch, inner);
        }
        catch (ArgumentOutOfRangeException inner2)
        {
            throw new BadImageFormatException(SR.BadImageFormat_TypeMismatch, inner2);
        }
    }
References System.Resources.ResourceReader._LoadObjectV1(), and System.SR.BadImageFormat_TypeMismatch.
Referenced by System.Resources.ResourceReader.GetValueForNameIndex(), System.Resources.ResourceReader.LoadObject(), and System.Resources.ResourceReader.LoadObject().