Terraria: System.Resources.ResourceReader._LoadObjectV2
_LoadObjectV2()
unsafe object System.Resources.ResourceReader._LoadObjectV2 (int pos, out ResourceTypeCode typeCode) inline private
Definition at line 738 of file ResourceReader.cs.
    {
        _store.BaseStream.Seek(_dataSectionOffset + pos, SeekOrigin.Begin);
        typeCode = (ResourceTypeCode)_store.Read7BitEncodedInt();
        switch (typeCode)
        {
        case ResourceTypeCode.Null:
            return null;
        case ResourceTypeCode.String:
            return _store.ReadString();
        case ResourceTypeCode.Boolean:
            return _store.ReadBoolean();
        case ResourceTypeCode.Char:
            return (char)_store.ReadUInt16();
        case ResourceTypeCode.Byte:
            return _store.ReadByte();
        case ResourceTypeCode.SByte:
            return _store.ReadSByte();
        case ResourceTypeCode.Int16:
            return _store.ReadInt16();
        case ResourceTypeCode.UInt16:
            return _store.ReadUInt16();
        case ResourceTypeCode.Int32:
            return _store.ReadInt32();
        case ResourceTypeCode.UInt32:
            return _store.ReadUInt32();
        case ResourceTypeCode.Int64:
            return _store.ReadInt64();
        case ResourceTypeCode.UInt64:
            return _store.ReadUInt64();
        case ResourceTypeCode.Single:
            return _store.ReadSingle();
        case ResourceTypeCode.Double:
            return _store.ReadDouble();
        case ResourceTypeCode.Decimal:
            return _store.ReadDecimal();
        case ResourceTypeCode.DateTime:
        {
            long dateData = _store.ReadInt64();
            return DateTime.FromBinary(dateData);
        }
        case ResourceTypeCode.TimeSpan:
        {
            long ticks = _store.ReadInt64();
            return new TimeSpan(ticks);
        }
        case ResourceTypeCode.ByteArray:
        {
            int num2 = _store.ReadInt32();
            if (num2 < 0)
            {
                throw new BadImageFormatException(SR.Format(SR.BadImageFormat_ResourceDataLengthInvalid, num2));
            }
            if (_ums == null)
            {
                if (num2 > _store.BaseStream.Length)
                {
                    throw new BadImageFormatException(SR.Format(SR.BadImageFormat_ResourceDataLengthInvalid, num2));
                }
                return _store.ReadBytes(num2);
            }
            if (num2 > _ums.Length - _ums.Position)
            {
                throw new BadImageFormatException(SR.Format(SR.BadImageFormat_ResourceDataLengthInvalid, num2));
            }
            byte[] array2 = new byte[num2];
            int num3 = _ums.Read(array2, 0, num2);
            return array2;
        }
        case ResourceTypeCode.Stream:
        {
            int num = _store.ReadInt32();
            if (num < 0)
            {
                throw new BadImageFormatException(SR.Format(SR.BadImageFormat_ResourceDataLengthInvalid, num));
            }
            if (_ums == null)
            {
                byte[] array = _store.ReadBytes(num);
                return new PinnedBufferMemoryStream(array);
            }
            if (num > _ums.Length - _ums.Position)
            {
                throw new BadImageFormatException(SR.Format(SR.BadImageFormat_ResourceDataLengthInvalid, num));
            }
            return new UnmanagedMemoryStream(_ums.PositionPointer, num, num, FileAccess.Read);
        }
        default:
        {
            if (typeCode < ResourceTypeCode.StartOfUserTypes)
            {
                throw new BadImageFormatException(SR.BadImageFormat_TypeMismatch);
            }
            int typeIndex = (int)(typeCode - 64);
            return DeserializeObject(typeIndex);
        }
        }
    }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._store, System.Resources.ResourceReader._ums, System.array, System.SR.BadImageFormat_ResourceDataLengthInvalid, System.SR.BadImageFormat_TypeMismatch, System.IO.BinaryReader.BaseStream, System.Resources.ResourceReader.DeserializeObject(), System.SR.Format(), System.DateTime.FromBinary(), System.IO.UnmanagedMemoryStream.Length, System.IO.UnmanagedMemoryStream.Position, System.IO.UnmanagedMemoryStream.PositionPointer, System.IO.UnmanagedMemoryStream.Read(), System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadDecimal(), System.IO.BinaryReader.ReadDouble(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadSByte(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), System.IO.BinaryReader.ReadUInt64(), and System.Resources.TimeSpan.
Referenced by System.Resources.ResourceReader.LoadObjectV2().