Terraria: System.IO.Compression.DeflateManagedStream.ReadAsyncCore
ReadAsyncCore()
async ValueTask< int > System.IO.Compression.DeflateManagedStream.ReadAsyncCore (ValueTask< int > readTask, Memory< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 194 of file DeflateManagedStream.cs.
    {
        try
        {
            int num;
            while (true)
            {
                num = await readTask.ConfigureAwait(continueOnCapturedContext: false);
                EnsureNotDisposed();
                if (num <= 0)
                {
                    return 0;
                }
                if (num > _buffer.Length)
                {
                    throw new InvalidDataException(System.SR.GenericInvalidData);
                }
                cancellationToken.ThrowIfCancellationRequested();
                _inflater.SetInput(_buffer, 0, num);
                num = _inflater.Inflate(buffer.Span);
                if (num != 0 || _inflater.Finished())
                {
                    break;
                }
                readTask = _stream.ReadAsync(_buffer.AsMemory(), cancellationToken);
            }
            return num;
        }
        finally
        {
            Interlocked.Decrement(ref _asyncOperations);
        }
    }
References System.IO.Compression.DeflateManagedStream._asyncOperations, System.IO.Compression.DeflateManagedStream._buffer, System.IO.Compression.DeflateManagedStream._inflater, System.IO.Compression.DeflateManagedStream._stream, System.buffer, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Threading.Interlocked.Decrement(), System.IO.Compression.DeflateManagedStream.EnsureNotDisposed(), System.IO.Compression.InflaterManaged.Finished(), System.SR.GenericInvalidData, System.IO.Compression.InflaterManaged.Inflate(), System.IO.Stream.ReadAsync(), and System.IO.Compression.InflaterManaged.SetInput().
Referenced by System.IO.Compression.DeflateManagedStream.ReadAsyncInternal().