Terraria: System.IO.Compression.DeflateManagedStream.Dispose
Dispose() [2/2]
override void System.IO.Compression.DeflateManagedStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 262 of file DeflateManagedStream.cs.
    {
        try
        {
            PurgeBuffers(disposing);
        }
        finally
        {
            try
            {
                if (disposing && _stream != null)
                {
                    _stream.Dispose();
                }
            }
            finally
            {
                _stream = null;
                try
                {
                    _inflater?.Dispose();
                }
                finally
                {
                    _inflater = null;
                    base.Dispose(disposing);
                }
            }
        }
    }
References System.IO.Compression.DeflateManagedStream._inflater, System.IO.Compression.DeflateManagedStream._stream, System.IO.Compression.InflaterManaged.Dispose(), System.IO.Stream.Dispose(), and System.IO.Compression.DeflateManagedStream.PurgeBuffers().