Terraria: System.IO.Compression.DeflateManagedStream.EnsureNotDisposed
EnsureNotDisposed()
void System.IO.Compression.DeflateManagedStream.EnsureNotDisposed () inline private
Definition at line 139 of file DeflateManagedStream.cs.
    {
        if (_stream == null)
        {
            ThrowStreamClosedException();
        }
    }
References System.IO.Compression.DeflateManagedStream._stream, and System.IO.Compression.DeflateManagedStream.ThrowStreamClosedException().
Referenced by System.IO.Compression.DeflateManagedStream.Flush(), System.IO.Compression.DeflateManagedStream.FlushAsync(), System.IO.Compression.DeflateManagedStream.Read(), System.IO.Compression.DeflateManagedStream.ReadAsync(), System.IO.Compression.DeflateManagedStream.ReadAsync(), and System.IO.Compression.DeflateManagedStream.ReadAsyncCore().