Terraria: System.Resources.ResourceReader.DeserializeObject
DeserializeObject()
object System.Resources.ResourceReader.DeserializeObject (int typeIndex) inline private
Definition at line 184 of file ResourceReader.cs.
    {
        if (!AllowCustomResourceTypes)
        {
            throw new NotSupportedException(SR.ResourceManager_ReflectionNotAllowed);
        }
        if (!_permitDeserialization)
        {
            throw new NotSupportedException(SR.NotSupported_ResourceObjectSerialization);
        }
        if (Volatile.Read(ref _binaryFormatter) == null && !InitializeBinaryFormatter())
        {
            throw new NotSupportedException(SR.BinaryFormatter_SerializationDisallowed);
        }
        Type type = FindType(typeIndex);
        object obj = s_deserializeMethod(_binaryFormatter, _store.BaseStream);
        if (obj.GetType() != type)
        {
            throw new BadImageFormatException(SR.Format(SR.BadImageFormat_ResType_SerBlobMismatch, type.FullName, obj.GetType().FullName));
        }
        return obj;
    }
References System.Resources.ResourceReader._binaryFormatter, System.Resources.ResourceReader._permitDeserialization, System.Resources.ResourceReader._store, System.Resources.ResourceReader.AllowCustomResourceTypes, System.SR.BadImageFormat_ResType_SerBlobMismatch, System.IO.BinaryReader.BaseStream, System.SR.BinaryFormatter_SerializationDisallowed, System.Resources.ResourceReader.FindType(), System.SR.Format(), System.Resources.ResourceReader.InitializeBinaryFormatter(), System.SR.NotSupported_ResourceObjectSerialization, System.obj, System.Threading.Volatile.Read(), System.SR.ResourceManager_ReflectionNotAllowed, System.Resources.ResourceReader.s_deserializeMethod, and System.type.
Referenced by System.Resources.ResourceReader._LoadObjectV1(), and System.Resources.ResourceReader._LoadObjectV2().