Terraria: System.Resources.ResourceReader.InitializeBinaryFormatter
InitializeBinaryFormatter()
bool System.Resources.ResourceReader.InitializeBinaryFormatter () inline private
Definition at line 208 of file ResourceReader.cs.
    {
        if ((object)Volatile.Read(ref s_binaryFormatterType) == null || Volatile.Read(ref s_deserializeMethod) == null)
        {
            Type type = Type.GetType("System.Runtime.Serialization.Formatters.Binary.BinaryFormatter, System.Runtime.Serialization.Formatters", throwOnError: true);
            MethodInfo method = type.GetMethod("Deserialize", new Type[1] { typeof(Stream) });
            MethodInfo? method2 = typeof(ResourceReader).GetMethod("CreateUntypedDelegate", BindingFlags.Static | BindingFlags.NonPublic);
            object obj;
            if ((object)method2 == null)
            {
                obj = null;
            }
            else
            {
                MethodInfo methodInfo = method2.MakeGenericMethod(type);
                object[] parameters = new MethodInfo[1] { method };
                obj = methodInfo.Invoke(null, parameters);
            }
            Func<object, Stream, object> value = (Func<object, Stream, object>)obj;
            Interlocked.CompareExchange(ref s_binaryFormatterType, type, null);
            Interlocked.CompareExchange(ref s_deserializeMethod, value, null);
        }
        Volatile.Write(ref _binaryFormatter, Activator.CreateInstance(s_binaryFormatterType));
        return s_deserializeMethod != null;
    }
References System.Resources.ResourceReader._binaryFormatter, System.Threading.Interlocked.CompareExchange(), System.Activator.CreateInstance(), System.Type.GetType(), System.obj, System.Threading.Volatile.Read(), System.Resources.ResourceReader.s_binaryFormatterType, System.Resources.ResourceReader.s_deserializeMethod, System.type, System.value, and System.Threading.Volatile.Write().
Referenced by System.Resources.ResourceReader.DeserializeObject().