Terraria: System.Resources.ResourceReader.UseReflectionToGetType
UseReflectionToGetType()
Type System.Resources.ResourceReader.UseReflectionToGetType (int typeIndex) inline private
Definition at line 985 of file ResourceReader.cs.
    {
        long position = _store.BaseStream.Position;
        try
        {
            _store.BaseStream.Position = _typeNamePositions[typeIndex];
            string typeName = _store.ReadString();
            _typeTable[typeIndex] = Type.GetType(typeName, throwOnError: true);
            return _typeTable[typeIndex];
        }
        catch (FileNotFoundException)
        {
            throw new NotSupportedException(SR.NotSupported_ResourceObjectSerialization);
        }
        finally
        {
            _store.BaseStream.Position = position;
        }
    }
References System.Resources.ResourceReader._store, System.Resources.ResourceReader._typeNamePositions, System.Resources.ResourceReader._typeTable, System.IO.BinaryReader.BaseStream, System.Type.GetType(), System.SR.NotSupported_ResourceObjectSerialization, and System.IO.BinaryReader.ReadString().
Referenced by System.Resources.ResourceReader.FindType().