Terraria: System.Resources.ResourceReader.FindType
FindType()
Type System.Resources.ResourceReader.FindType (int typeIndex) inline private
Definition at line 971 of file ResourceReader.cs.
    {
        if (!AllowCustomResourceTypes)
        {
            throw new NotSupportedException(SR.ResourceManager_ReflectionNotAllowed);
        }
        if (typeIndex < 0 || typeIndex >= _typeTable.Length)
        {
            throw new BadImageFormatException(SR.BadImageFormat_InvalidType);
        }
        return _typeTable[typeIndex] ?? UseReflectionToGetType(typeIndex);
    }
References System.Resources.ResourceReader._typeTable, System.Resources.ResourceReader.AllowCustomResourceTypes, System.SR.BadImageFormat_InvalidType, System.SR.ResourceManager_ReflectionNotAllowed, and System.Resources.ResourceReader.UseReflectionToGetType().
Referenced by System.Resources.ResourceReader._LoadObjectV1(), System.Resources.ResourceReader.DeserializeObject(), and System.Resources.ResourceReader.LoadString().