Terraria: System.IO.Compression.DeflateManagedStream.Read
Read() [2/2]
override int System.IO.Compression.DeflateManagedStream.Read (Span< byte > buffer) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 103 of file DeflateManagedStream.cs.
    {
        EnsureNotDisposed();
        int length = buffer.Length;
        while (true)
        {
            int start = _inflater.Inflate(buffer);
            buffer = buffer.Slice(start);
            if (buffer.Length == 0 || _inflater.Finished())
            {
                break;
            }
            int num = _stream.Read(_buffer, 0, _buffer.Length);
            if (num <= 0)
            {
                break;
            }
            if (num > _buffer.Length)
            {
                throw new InvalidDataException(System.SR.GenericInvalidData);
            }
            _inflater.SetInput(_buffer, 0, num);
        }
        return length - buffer.Length;
    }
References System.IO.Compression.DeflateManagedStream._buffer, System.IO.Compression.DeflateManagedStream._inflater, System.IO.Compression.DeflateManagedStream._stream, System.buffer, System.IO.Compression.DeflateManagedStream.EnsureNotDisposed(), System.IO.Compression.InflaterManaged.Finished(), System.SR.GenericInvalidData, System.IO.Compression.InflaterManaged.Inflate(), System.length, System.IO.Stream.Read(), System.IO.Compression.InflaterManaged.SetInput(), and System.start.