Terraria: System.Xml.XmlValidatingReaderImpl.ProcessCoreReaderEvent
ProcessCoreReaderEvent()
void System.Xml.XmlValidatingReaderImpl.ProcessCoreReaderEvent () inline private
Definition at line 753 of file XmlValidatingReaderImpl.cs.
    {
        switch (_coreReader.NodeType)
        {
        case XmlNodeType.Whitespace:
            if ((_coreReader.Depth > 0 || _coreReaderImpl.FragmentType != XmlNodeType.Document) && _validator.PreserveWhitespace)
            {
                _coreReaderImpl.ChangeCurrentNodeType(XmlNodeType.SignificantWhitespace);
            }
            break;
        case XmlNodeType.DocumentType:
            ValidateDtd();
            return;
        case XmlNodeType.EntityReference:
            _parsingFunction = ParsingFunction.ResolveEntityInternally;
            break;
        }
        _coreReaderImpl.InternalSchemaType = null;
        _coreReaderImpl.InternalTypedValue = null;
        _validator.Validate();
    }
References System.Xml.XmlValidatingReaderImpl._coreReader, System.Xml.XmlValidatingReaderImpl._coreReaderImpl, System.Xml.XmlValidatingReaderImpl._parsingFunction, System.Xml.XmlValidatingReaderImpl._validator, System.Xml.XmlTextReaderImpl.ChangeCurrentNodeType(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.FragmentType, System.Xml.XmlReader.NodeType, System.Xml.Schema.BaseValidator.PreserveWhitespace, System.Xml.Schema.BaseValidator.Validate(), and System.Xml.XmlValidatingReaderImpl.ValidateDtd().
Referenced by System.Xml.XmlValidatingReaderImpl.Read(), and System.Xml.XmlValidatingReaderImpl.ReadAsync().