Terraria: System.Xml.XmlValidatingReaderImpl.ReadContentAsBase64
ReadContentAsBase64()
override int System.Xml.XmlValidatingReaderImpl.ReadContentAsBase64 (byte[] buffer, int index, int count) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 517 of file XmlValidatingReaderImpl.cs.
    {
        if (ReadState != ReadState.Interactive)
        {
            return 0;
        }
        if (_parsingFunction != ParsingFunction.InReadBinaryContent)
        {
            _readBinaryHelper = ReadContentAsBinaryHelper.CreateOrReset(_readBinaryHelper, _outerReader);
        }
        _parsingFunction = ParsingFunction.Read;
        int result = _readBinaryHelper.ReadContentAsBase64(buffer, index, count);
        _parsingFunction = ParsingFunction.InReadBinaryContent;
        return result;
    }
References System.Xml.XmlValidatingReaderImpl._outerReader, System.Xml.XmlValidatingReaderImpl._parsingFunction, System.Xml.XmlValidatingReaderImpl._readBinaryHelper, System.buffer, System.count, System.Xml.ReadContentAsBinaryHelper.CreateOrReset(), System.index, and System.Xml.ReadContentAsBinaryHelper.ReadContentAsBase64().
Referenced by System.Xml.XmlValidatingReader.ReadContentAsBase64().