Terraria: System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl
XmlValidatingReaderImpl() [1/4]
System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl (XmlReader reader) inline package
Definition at line 289 of file XmlValidatingReaderImpl.cs.
    {
        if (reader is XmlAsyncCheckReader xmlAsyncCheckReader)
        {
            reader = xmlAsyncCheckReader.CoreReader;
        }
        _outerReader = this;
        _coreReader = reader;
        _coreReaderNSResolver = reader as IXmlNamespaceResolver;
        _coreReaderImpl = reader as XmlTextReaderImpl;
        if (_coreReaderImpl == null && reader is XmlTextReader xmlTextReader)
        {
            _coreReaderImpl = xmlTextReader.Impl;
        }
        if (_coreReaderImpl == null)
        {
            throw new ArgumentException(System.SR.Arg_ExpectingXmlTextReader, "reader");
        }
        _coreReaderImpl.EntityHandling = EntityHandling.ExpandEntities;
        _coreReaderImpl.XmlValidatingReaderCompatibilityMode = true;
        _processIdentityConstraints = true;
        _schemaCollection = new XmlSchemaCollection(_coreReader.NameTable);
        _schemaCollection.XmlResolver = GetResolver();
        _eventHandling = new ValidationEventHandling(this);
        _coreReaderImpl.ValidationEventHandling = _eventHandling;
        _coreReaderImpl.OnDefaultAttributeUse = ValidateDefaultAttributeOnUse;
        _validationType = ValidationType.Auto;
        SetupValidation(ValidationType.Auto);
    }
References System.Xml.XmlValidatingReaderImpl._coreReader, System.Xml.XmlValidatingReaderImpl._coreReaderImpl, System.Xml.XmlValidatingReaderImpl._coreReaderNSResolver, System.Xml.XmlValidatingReaderImpl._eventHandling, System.Xml.XmlValidatingReaderImpl._outerReader, System.Xml.XmlValidatingReaderImpl._processIdentityConstraints, System.Xml.XmlValidatingReaderImpl._schemaCollection, System.Xml.XmlValidatingReaderImpl._validationType, System.SR.Arg_ExpectingXmlTextReader, System.Xml.ArgumentException, System.Xml.Dictionary, System.Xml.XmlValidatingReaderImpl.GetResolver(), System.Xml.XmlReader.NameTable, System.Xml.XmlValidatingReaderImpl.SetupValidation(), and System.Xml.XmlValidatingReaderImpl.ValidateDefaultAttributeOnUse().