Terraria: System.Xml.XmlValidatingReaderImpl.ValidateDefaultAttributeOnUse
ValidateDefaultAttributeOnUse()
void System.Xml.XmlValidatingReaderImpl.ValidateDefaultAttributeOnUse (IDtdDefaultAttributeInfo defaultAttribute, XmlTextReaderImpl coreReader) inline package
Definition at line 780 of file XmlValidatingReaderImpl.cs.
    {
        if (defaultAttribute is SchemaAttDef attdef && coreReader.DtdInfo is SchemaInfo sinfo)
        {
            DtdValidator.CheckDefaultValue(attdef, sinfo, _eventHandling, coreReader.BaseURI);
        }
    }
References System.Xml.XmlValidatingReaderImpl._eventHandling, and System.Xml.Schema.DtdValidator.CheckDefaultValue().
Referenced by System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), and System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl().