Terraria: System.Xml.XmlValidatingReaderImpl.MoveOffEntityReference
MoveOffEntityReference()
void System.Xml.XmlValidatingReaderImpl.MoveOffEntityReference () inline package
Definition at line 590 of file XmlValidatingReaderImpl.cs.
    {
        if (_outerReader.NodeType == XmlNodeType.EntityReference && _parsingFunction != ParsingFunction.ResolveEntityInternally && !_outerReader.Read())
        {
            throw new InvalidOperationException(System.SR.Xml_InvalidOperation);
        }
    }
References System.Xml.XmlValidatingReaderImpl._outerReader, System.Xml.XmlValidatingReaderImpl._parsingFunction, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), and System.SR.Xml_InvalidOperation.
Referenced by System.Xml.XmlValidatingReader.ReadString(), and System.Xml.XmlValidatingReaderImpl.ReadString().