Terraria: System.Xml.XmlValidatingReaderImpl.GetResolver
GetResolver()
XmlResolver System.Xml.XmlValidatingReaderImpl.GetResolver () inline private
Definition at line 739 of file XmlValidatingReaderImpl.cs.
    {
        XmlResolver resolver = _coreReaderImpl.GetResolver();
        if (resolver == null && !_coreReaderImpl.IsResolverSet)
        {
            if (s_tempResolver == null)
            {
                s_tempResolver = new XmlUrlResolver();
            }
            return s_tempResolver;
        }
        return resolver;
    }
References System.Xml.XmlValidatingReaderImpl._coreReaderImpl, System.Xml.Dictionary, System.Xml.XmlTextReaderImpl.GetResolver(), and System.Xml.XmlValidatingReaderImpl.s_tempResolver.
Referenced by System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), and System.Xml.XmlValidatingReaderImpl.SetupValidation().