Terraria: System.Xml.XmlValidatingReaderImpl.ValidateDtd
ValidateDtd()
void System.Xml.XmlValidatingReaderImpl.ValidateDtd () inline private
Definition at line 697 of file XmlValidatingReaderImpl.cs.
    {
        IDtdInfo dtdInfo = _coreReaderImpl.DtdInfo;
        if (dtdInfo != null)
        {
            switch (_validationType)
            {
            default:
                return;
            case ValidationType.Auto:
                SetupValidation(ValidationType.DTD);
                break;
            case ValidationType.None:
            case ValidationType.DTD:
                break;
            }
            _validator.DtdInfo = dtdInfo;
        }
    }
References System.Xml.XmlValidatingReaderImpl._coreReaderImpl, System.Xml.XmlValidatingReaderImpl._validationType, System.Xml.Dictionary, System.Xml.XmlReader.DtdInfo, and System.Xml.XmlValidatingReaderImpl.SetupValidation().
Referenced by System.Xml.XmlValidatingReaderImpl.ParseDtdFromParserContext(), System.Xml.XmlValidatingReaderImpl.ParseDtdFromParserContextAsync(), and System.Xml.XmlValidatingReaderImpl.ProcessCoreReaderEvent().