Terraria: System.Xml.XmlValidatingReaderImpl.SetupValidation
SetupValidation()
void System.Xml.XmlValidatingReaderImpl.SetupValidation (ValidationType valType) inline private
Definition at line 727 of file XmlValidatingReaderImpl.cs.
    {
        _validator = BaseValidator.CreateInstance(valType, this, _schemaCollection, _eventHandling, _processIdentityConstraints);
        XmlResolver resolver = GetResolver();
        _validator.XmlResolver = resolver;
        if (_outerReader.BaseURI.Length > 0)
        {
            _validator.BaseUri = ((resolver == null) ? new Uri(_outerReader.BaseURI, UriKind.RelativeOrAbsolute) : resolver.ResolveUri(null, _outerReader.BaseURI));
        }
        _coreReaderImpl.ValidationEventHandling = ((_validationType == ValidationType.None) ? null : _eventHandling);
    }
References System.Xml.XmlValidatingReaderImpl._eventHandling, System.Xml.XmlValidatingReaderImpl._outerReader, System.Xml.XmlValidatingReaderImpl._processIdentityConstraints, System.Xml.XmlValidatingReaderImpl._schemaCollection, System.Xml.XmlValidatingReaderImpl._validationType, System.Xml.XmlValidatingReaderImpl._validator, System.Xml.XmlReader.BaseURI, System.Xml.Schema.BaseValidator.CreateInstance(), System.Xml.Dictionary, and System.Xml.XmlValidatingReaderImpl.GetResolver().
Referenced by System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), System.Xml.XmlValidatingReaderImpl.XmlValidatingReaderImpl(), and System.Xml.XmlValidatingReaderImpl.ValidateDtd().