Terraria: System.Xml.XmlValidatingReaderImpl.MoveToNextAttribute
MoveToNextAttribute()
override bool System.Xml.XmlValidatingReaderImpl.MoveToNextAttribute () inline
Definition at line 431 of file XmlValidatingReaderImpl.cs.
    {
        if (!_coreReader.MoveToNextAttribute())
        {
            return false;
        }
        _parsingFunction = ParsingFunction.Read;
        return true;
    }
References System.Xml.XmlValidatingReaderImpl._coreReader, System.Xml.XmlValidatingReaderImpl._parsingFunction, and System.Xml.XmlReader.MoveToNextAttribute().
Referenced by System.Xml.XmlValidatingReader.MoveToNextAttribute(), System.Xml.Schema.XsdValidator.ProcessXsiAttributes(), System.Xml.Schema.XdrValidator.ThoroughGetElementDecl(), System.Xml.Schema.XdrValidator.ValidateStartElement(), and System.Xml.Schema.XsdValidator.ValidateStartElement().