Terraria: System.Xml.XmlValidatingReaderImpl.ParseDtdFromParserContextAsync
ParseDtdFromParserContextAsync()
async Task System.Xml.XmlValidatingReaderImpl.ParseDtdFromParserContextAsync () inline private
Definition at line 897 of file XmlValidatingReaderImpl.cs.
    {
        if (_parserContext.DocTypeName != null && _parserContext.DocTypeName.Length != 0)
        {
            IDtdParser dtdParser = DtdParser.Create();
            XmlTextReaderImpl.DtdParserProxy adapter = new XmlTextReaderImpl.DtdParserProxy(_coreReaderImpl);
            IDtdInfo dtdInfo = await dtdParser.ParseFreeFloatingDtdAsync(_parserContext.BaseURI, _parserContext.DocTypeName, _parserContext.PublicId, _parserContext.SystemId, _parserContext.InternalSubset, adapter).ConfigureAwait(continueOnCapturedContext: false);
            _coreReaderImpl.SetDtdInfo(dtdInfo);
            ValidateDtd();
        }
    }
References System.Xml.XmlValidatingReaderImpl._coreReaderImpl, System.Xml.XmlValidatingReaderImpl._parserContext, System.Xml.XmlParserContext.BaseURI, System.Xml.DtdParser.Create(), System.Xml.XmlParserContext.DocTypeName, System.Xml.XmlParserContext.InternalSubset, System.Xml.XmlParserContext.PublicId, System.Xml.XmlTextReaderImpl.SetDtdInfo(), System.Xml.XmlParserContext.SystemId, and System.Xml.XmlValidatingReaderImpl.ValidateDtd().
Referenced by System.Xml.XmlValidatingReaderImpl.ReadAsync().