Terraria: System.Xml.XmlValidatingReaderImpl.Read
Read()
override bool System.Xml.XmlValidatingReaderImpl.Read () inline
Definition at line 451 of file XmlValidatingReaderImpl.cs.
    {
        switch (_parsingFunction)
        {
        case ParsingFunction.Read:
            if (_coreReader.Read())
            {
                ProcessCoreReaderEvent();
                return true;
            }
            _validator.CompleteValidation();
            return false;
        case ParsingFunction.ParseDtdFromContext:
            _parsingFunction = ParsingFunction.Read;
            ParseDtdFromParserContext();
            goto case ParsingFunction.Read;
        case ParsingFunction.ReaderClosed:
        case ParsingFunction.Error:
            return false;
        case ParsingFunction.Init:
            _parsingFunction = ParsingFunction.Read;
            if (_coreReader.ReadState == ReadState.Interactive)
            {
                ProcessCoreReaderEvent();
                return true;
            }
            goto case ParsingFunction.Read;
        case ParsingFunction.ResolveEntityInternally:
            _parsingFunction = ParsingFunction.Read;
            ResolveEntityInternally();
            goto case ParsingFunction.Read;
        case ParsingFunction.InReadBinaryContent:
            _parsingFunction = ParsingFunction.Read;
            _readBinaryHelper.Finish();
            goto case ParsingFunction.Read;
        default:
            return false;
        }
    }
References System.Xml.XmlValidatingReaderImpl._coreReader, System.Xml.XmlValidatingReaderImpl._parsingFunction, System.Xml.XmlValidatingReaderImpl._readBinaryHelper, System.Xml.XmlValidatingReaderImpl._validator, System.Xml.Schema.BaseValidator.CompleteValidation(), System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XmlValidatingReaderImpl.ParseDtdFromParserContext(), System.Xml.XmlValidatingReaderImpl.ProcessCoreReaderEvent(), System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadState, and System.Xml.XmlValidatingReaderImpl.ResolveEntityInternally().
Referenced by System.Xml.XmlValidatingReader.Read().