Terraria: System.Xml.XmlValidatingReaderImpl.ReadAsync
ReadAsync()
override async Task< bool > System.Xml.XmlValidatingReaderImpl.ReadAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 793 of file XmlValidatingReaderImpl.cs.
    {
        switch (_parsingFunction)
        {
        case ParsingFunction.Read:
            if (await _coreReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false))
            {
                ProcessCoreReaderEvent();
                return true;
            }
            _validator.CompleteValidation();
            return false;
        case ParsingFunction.ParseDtdFromContext:
            _parsingFunction = ParsingFunction.Read;
            await ParseDtdFromParserContextAsync().ConfigureAwait(continueOnCapturedContext: false);
            goto case ParsingFunction.Read;
        case ParsingFunction.ReaderClosed:
        case ParsingFunction.Error:
            return false;
        case ParsingFunction.Init:
            _parsingFunction = ParsingFunction.Read;
            if (_coreReader.ReadState == ReadState.Interactive)
            {
                ProcessCoreReaderEvent();
                return true;
            }
            goto case ParsingFunction.Read;
        case ParsingFunction.ResolveEntityInternally:
            _parsingFunction = ParsingFunction.Read;
            await ResolveEntityInternallyAsync().ConfigureAwait(continueOnCapturedContext: false);
            goto case ParsingFunction.Read;
        case ParsingFunction.InReadBinaryContent:
            _parsingFunction = ParsingFunction.Read;
            await _readBinaryHelper.FinishAsync().ConfigureAwait(continueOnCapturedContext: false);
            goto case ParsingFunction.Read;
        default:
            return false;
        }
    }
References System.Xml.XmlValidatingReaderImpl._coreReader, System.Xml.XmlValidatingReaderImpl._parsingFunction, System.Xml.XmlValidatingReaderImpl._readBinaryHelper, System.Xml.XmlValidatingReaderImpl._validator, System.Xml.Schema.BaseValidator.CompleteValidation(), System.Xml.ReadContentAsBinaryHelper.FinishAsync(), System.Xml.XmlValidatingReaderImpl.ParseDtdFromParserContextAsync(), System.Xml.XmlValidatingReaderImpl.ProcessCoreReaderEvent(), System.Xml.XmlReader.ReadAsync(), System.Xml.XmlReader.ReadState, and System.Xml.XmlValidatingReaderImpl.ResolveEntityInternallyAsync().