Terraria: System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalFindAndPop
LocalFindAndPop()
bool System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalFindAndPop (object obj) inline
Definition at line 167 of file ThreadPoolWorkQueue.cs.
        {
            if (m_array[(m_tailIndex - 1) & m_mask] == obj)
            {
                object obj2 = LocalPop();
                return obj2 != null;
            }
            for (int num = m_tailIndex - 2; num >= m_headIndex; num--)
            {
                if (m_array[num & m_mask] == obj)
                {
                    bool lockTaken = false;
                    try
                    {
                        m_foreignLock.Enter(ref lockTaken);
                        if (m_array[num & m_mask] == null)
{
                            return false;
                        }
                        Volatile.Write(ref m_array[num & m_mask], null);
                        if (num == m_tailIndex)
{
                            m_tailIndex--;
                        }
                        else if (num == m_headIndex)
{
                            m_headIndex++;
                        }
                        return true;
                    }
                    finally
                    {
                        if (lockTaken)
{
                            m_foreignLock.Exit(useMemoryBarrier: false);
                        }
                    }
                }
            }
            return false;
        }
References System.Threading.SpinLock.Enter(), System.Threading.SpinLock.Exit(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPop(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_array, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_foreignLock, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_headIndex, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_mask, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_tailIndex, System.obj, and System.Threading.Volatile.Write().