Terraria: System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPop
LocalPop()
object System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPop () inline
Definition at line 209 of file ThreadPoolWorkQueue.cs.
        {
            if (m_headIndex >= m_tailIndex)
            {
                return null;
            }
            return LocalPopCore();
        }
References System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPopCore(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_headIndex, and System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_tailIndex.
Referenced by System.Threading.ThreadPoolWorkQueue.Dequeue(), and System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalFindAndPop().