Terraria: System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPopCore
LocalPopCore()
object System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPopCore () inline private
Definition at line 218 of file ThreadPoolWorkQueue.cs.
        {
            int num;
            object obj;
            while (true)
            {
                int tailIndex = m_tailIndex;
                if (m_headIndex >= tailIndex)
                {
                    return null;
                }
                tailIndex--;
                Interlocked.Exchange(ref m_tailIndex, tailIndex);
                if (m_headIndex <= tailIndex)
                {
                    num = tailIndex & m_mask;
                    obj = Volatile.Read(ref m_array[num]);
                    if (obj != null)
                    {
                        break;
                    }
                    continue;
                }
                bool lockTaken = false;
                try
                {
                    m_foreignLock.Enter(ref lockTaken);
                    if (m_headIndex <= tailIndex)
                    {
                        int num2 = tailIndex & m_mask;
                        object obj2 = Volatile.Read(ref m_array[num2]);
                        if (obj2 != null)
{
                            m_array[num2] = null;
                            return obj2;
                        }
                        continue;
                    }
                    m_tailIndex = tailIndex + 1;
                    return null;
                }
                finally
                {
                    if (lockTaken)
                    {
                        m_foreignLock.Exit(useMemoryBarrier: false);
                    }
                }
            }
            m_array[num] = null;
            return obj;
        }
References System.Threading.SpinLock.Enter(), System.Threading.Interlocked.Exchange(), System.Threading.SpinLock.Exit(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_array, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_foreignLock, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_headIndex, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_mask, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_tailIndex, System.obj, and System.Threading.Volatile.Read().
Referenced by System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPop().