Terraria: System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.TrySteal
TrySteal()
object System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.TrySteal (ref bool missedSteal) inline
Definition at line 271 of file ThreadPoolWorkQueue.cs.
        {
            while (CanSteal)
            {
                bool lockTaken = false;
                try
                {
                    m_foreignLock.TryEnter(ref lockTaken);
                    if (lockTaken)
                    {
                        int headIndex = m_headIndex;
                        Interlocked.Exchange(ref m_headIndex, headIndex + 1);
                        if (headIndex < m_tailIndex)
{
                            int num = headIndex & m_mask;
                            object obj = Volatile.Read(ref m_array[num]);
                            if (obj == null)
{
                                continue;
                            }
                            m_array[num] = null;
                            return obj;
                        }
                        m_headIndex = headIndex;
                    }
                }
                finally
                {
                    if (lockTaken)
                    {
                        m_foreignLock.Exit(useMemoryBarrier: false);
                    }
                }
                missedSteal = true;
                break;
            }
            return null;
        }
References System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.CanSteal, System.Threading.Interlocked.Exchange(), System.Threading.SpinLock.Exit(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_array, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_foreignLock, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_headIndex, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_mask, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_tailIndex, System.obj, System.Threading.Volatile.Read(), and System.Threading.SpinLock.TryEnter().
Referenced by System.Threading.ThreadPoolWorkQueue.Dequeue().