Terraria: System.Security.Cryptography.AesGcm.Decrypt
Decrypt() [1/2]
void System.Security.Cryptography.AesGcm.Decrypt (byte[] nonce, byte[] ciphertext, byte[] tag, byte[] plaintext, byte?[] associatedData = null) inline
Definition at line 53 of file AesGcm.cs.
    {
        AeadCommon.CheckArgumentsForNull(nonce, plaintext, ciphertext, tag);
        Decrypt((ReadOnlySpan<byte>)nonce, (ReadOnlySpan<byte>)ciphertext, (ReadOnlySpan<byte>)tag, (Span<byte>)plaintext, (ReadOnlySpan<byte>)associatedData);
    }
References System.Security.Cryptography.AeadCommon.CheckArgumentsForNull(), and System.Security.Cryptography.AesGcm.Decrypt().
Referenced by System.Security.Cryptography.AesGcm.Decrypt().