Terraria: System.Net.NetworkInformation.Ping.GetAddressAndSendAsync
GetAddressAndSendAsync()
async Task< PingReply > System.Net.NetworkInformation.Ping.GetAddressAndSendAsync (string hostNameOrAddress, int timeout, byte[] buffer, PingOptions options) inline private
Definition at line 392 of file Ping.cs.
    {
        CheckStart();
        try
        {
            Task<PingReply> task = SendPingAsyncCore((await Dns.GetHostAddressesAsync(hostNameOrAddress).ConfigureAwait(continueOnCapturedContext: false))[0], buffer, timeout, options);
            return await task.ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception innerException)
        {
            throw new PingException(System.SR.net_ping, innerException);
        }
        finally
        {
            Finish();
        }
    }
References System.buffer, System.Net.NetworkInformation.Ping.CheckStart(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.NetworkInformation.Ping.Finish(), System.Net.Dns.GetHostAddressesAsync(), System.SR.net_ping, System.options, System.Net.NetworkInformation.Ping.SendPingAsyncCore(), System.task, and System.timeout.
Referenced by System.Net.NetworkInformation.Ping.SendPingAsync().