Terraria: System.Net.Sockets.Socket.Socket
Socket() [5/5]
unsafe System.Net.Sockets.Socket.Socket (SocketInformation socketInformation) inline
Definition at line 4368 of file Socket.cs.
    {
        SocketError socketError = SocketPal.CreateSocket(socketInformation, out _handle, ref _addressFamily, ref _socketType, ref _protocolType);
        if (socketError != 0)
        {
            _handle = null;
            if (socketError == SocketError.InvalidArgument)
            {
                throw new ArgumentException(System.SR.net_sockets_invalid_socketinformation, "socketInformation");
            }
            throw new SocketException((int)socketError);
        }
        if (_addressFamily != AddressFamily.InterNetwork && _addressFamily != AddressFamily.InterNetworkV6)
        {
            _handle.Dispose();
            _handle = null;
            throw new NotSupportedException(System.SR.net_invalidversion);
        }
        _isConnected = socketInformation.GetOption(SocketInformationOptions.Connected);
        _willBlock = !socketInformation.GetOption(SocketInformationOptions.NonBlocking);
        InternalSetBlocking(_willBlock);
        _isListening = socketInformation.GetOption(SocketInformationOptions.Listening);
        IPEndPoint iPEndPoint = new IPEndPoint((_addressFamily == AddressFamily.InterNetwork) ? IPAddress.Any : IPAddress.IPv6Any, 0);
        System.Net.Internals.SocketAddress socketAddress = IPEndPointExtensions.Serialize(iPEndPoint);
        fixed (byte* buffer = socketAddress.Buffer)
        {
            fixed (int* nameLen = &socketAddress.InternalSize)
            {
                socketError = SocketPal.GetSockName(_handle, buffer, nameLen);
            }
        }
        switch (socketError)
        {
        case SocketError.Success:
            _rightEndPoint = iPEndPoint.Create(socketAddress);
            break;
        default:
            _handle.Dispose();
            _handle = null;
            throw new SocketException((int)socketError);
        case SocketError.InvalidArgument:
            break;
        }
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket._isListening, System.Net.Sockets.Socket._protocolType, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.Socket._socketType, System.Net.Sockets.Socket._willBlock, System.Net.IPAddress.Any, System.buffer, System.Net.Sockets.SocketPal.CreateSocket(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Net.Sockets.SocketPal.GetSockName(), System.Net.Sockets.Socket.InternalSetBlocking(), System.Net.IPAddress.IPv6Any, System.SR.net_invalidversion, System.SR.net_sockets_invalid_socketinformation, and System.Net.Sockets.IPEndPointExtensions.Serialize().