Terraria: System.Net.Sockets.Socket.BeginReceiveFrom
BeginReceiveFrom()
IAsyncResult System.Net.Sockets.Socket.BeginReceiveFrom (byte[] buffer, int offset, int size, SocketFlags socketFlags, ref EndPoint remoteEP, AsyncCallback? callback, object? state) inline
Definition at line 2649 of file Socket.cs.
    {
        ThrowIfDisposed();
        ValidateBufferArguments(buffer, offset, size);
        ValidateReceiveFromEndpointAndState(remoteEP, "remoteEP");
        Task<SocketReceiveFromResult> task = ReceiveFromAsync(buffer.AsMemory(offset, size), socketFlags, remoteEP).AsTask();
        if (task.IsCompletedSuccessfully)
        {
            EndPoint remoteEndPoint = task.Result.RemoteEndPoint;
            if (!remoteEP.Equals(remoteEndPoint))
            {
                remoteEP = remoteEndPoint;
            }
        }
        return System.Threading.Tasks.TaskToApm.Begin(task, callback, state);
    }
References System.Threading.Tasks.TaskToApm.Begin(), System.buffer, System.offset, System.Net.Sockets.Socket.ReceiveFromAsync(), System.state, System.task, System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.ValidateBufferArguments(), and System.Net.Sockets.Socket.ValidateReceiveFromEndpointAndState().
Referenced by System.Net.Sockets.UdpClient.BeginReceive().