Terraria: System.Net.Sockets.Socket.SetToDisconnected
SetToDisconnected()
void System.Net.Sockets.Socket.SetToDisconnected () inline package
Definition at line 3702 of file Socket.cs.
    {
        if (_isConnected)
        {
            _isConnected = false;
            _isDisconnected = true;
            if (!Disposed && System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "!Disposed", "SetToDisconnected");
            }
        }
    }
References System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket._isDisconnected, System.Net.Sockets.Socket.Disposed, System.Net.NetEventSource.Info(), and System.Net.NetEventSource.Log.
Referenced by System.Net.Sockets.Socket.Disconnect(), System.Net.Sockets.Socket.Dispose(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(), System.Net.Sockets.Socket.SendFileInternal(), System.Net.Sockets.Socket.Shutdown(), and System.Net.Sockets.Socket.UpdateStatusAfterSocketError().