Terraria: System.Net.Sockets.Socket.InternalSetBlocking
InternalSetBlocking() [2/2]
SocketError System.Net.Sockets.Socket.InternalSetBlocking (bool desired, out bool current) inline private
Definition at line 3592 of file Socket.cs.
    {
        if (Disposed)
        {
            current = _willBlock;
            return SocketError.Success;
        }
        bool willBlock = false;
        SocketError socketError;
        try
        {
            socketError = SocketPal.SetBlocking(_handle, desired, out willBlock);
        }
        catch (ObjectDisposedException)
        {
            socketError = SocketError.NotSocket;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"SetBlocking returns errorCode:{socketError}", "InternalSetBlocking");
        }
        if (socketError == SocketError.Success)
        {
            _willBlockInternal = willBlock;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"errorCode:{socketError} willBlock:{_willBlock} willBlockInternal:{_willBlockInternal}", "InternalSetBlocking");
        }
        current = _willBlockInternal;
        return socketError;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._willBlock, System.Net.Sockets.Socket._willBlockInternal, System.Net.Sockets.Socket.Disposed, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.Net.Sockets.SocketPal.SetBlocking().
Referenced by System.Net.Sockets.Socket.Socket(), System.Net.Sockets.Socket.InternalSetBlocking(), and System.Net.Sockets.Socket.Shutdown().