Terraria: System.Net.Sockets.Socket.Socket
Socket() [4/5]
unsafe System.Net.Sockets.Socket.Socket (SafeSocketHandle handle, bool loadPropertiesFromHandle) inline private
Definition at line 1056 of file Socket.cs.
    {
        _handle = handle;
        _addressFamily = AddressFamily.Unknown;
        _socketType = SocketType.Unknown;
        _protocolType = ProtocolType.Unknown;
        if (!loadPropertiesFromHandle)
        {
            return;
        }
        try
        {
            LoadSocketTypeFromHandle(handle, out _addressFamily, out _socketType, out _protocolType, out _willBlockInternal, out _isListening, out var isSocket);
            if (!isSocket)
            {
                return;
            }
            Span<byte> span = stackalloc byte[SocketPal.MaximumAddressSize];
            int nameLen = span.Length;
            fixed (byte* buffer = span)
            {
                if (SocketPal.GetSockName(handle, buffer, &nameLen) != 0)
                {
                    return;
                }
            }
            System.Net.Internals.SocketAddress socketAddress = null;
            switch (_addressFamily)
            {
            case AddressFamily.InterNetwork:
                _rightEndPoint = new IPEndPoint(new IPAddress((long)System.Net.SocketAddressPal.GetIPv4Address(span.Slice(0, nameLen)) & 0xFFFFFFFFL), System.Net.SocketAddressPal.GetPort(span));
                break;
            case AddressFamily.InterNetworkV6:
            {
                Span<byte> span2 = stackalloc byte[16];
                System.Net.SocketAddressPal.GetIPv6Address(span.Slice(0, nameLen), span2, out var scope);
                _rightEndPoint = new IPEndPoint(new IPAddress(span2, scope), System.Net.SocketAddressPal.GetPort(span));
                break;
            }
            case AddressFamily.Unix:
                socketAddress = new System.Net.Internals.SocketAddress(_addressFamily, span.Slice(0, nameLen));
                _rightEndPoint = new UnixDomainSocketEndPoint(IPEndPointExtensions.GetNetSocketAddress(socketAddress));
                break;
            }
            if (_rightEndPoint == null)
            {
                return;
            }
            try
            {
                nameLen = span.Length;
                switch (SocketPal.GetPeerName(handle, span, ref nameLen))
                {
                case SocketError.Success:
                    switch (_addressFamily)
                    {
                    case AddressFamily.InterNetwork:
                        _remoteEndPoint = new IPEndPoint(new IPAddress((long)System.Net.SocketAddressPal.GetIPv4Address(span.Slice(0, nameLen)) & 0xFFFFFFFFL), System.Net.SocketAddressPal.GetPort(span));
                        break;
                    case AddressFamily.InterNetworkV6:
                    {
                        Span<byte> span3 = stackalloc byte[16];
                        System.Net.SocketAddressPal.GetIPv6Address(span.Slice(0, nameLen), span3, out var scope2);
                        _remoteEndPoint = new IPEndPoint(new IPAddress(span3, scope2), System.Net.SocketAddressPal.GetPort(span));
                        break;
                    }
                    case AddressFamily.Unix:
                        socketAddress = new System.Net.Internals.SocketAddress(_addressFamily, span.Slice(0, nameLen));
                        _remoteEndPoint = new UnixDomainSocketEndPoint(IPEndPointExtensions.GetNetSocketAddress(socketAddress));
                        break;
                    }
                    _isConnected = true;
                    break;
                case SocketError.InvalidArgument:
                    _isConnected = true;
                    break;
                }
            }
            catch
            {
            }
        }
        catch
        {
            _handle = null;
            GC.SuppressFinalize(this);
            throw;
        }
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket._isListening, System.Net.Sockets.Socket._protocolType, System.Net.Sockets.Socket._remoteEndPoint, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.Socket._socketType, System.Net.Sockets.Socket._willBlockInternal, System.buffer, System.Net.SocketAddressPal.GetIPv4Address(), System.Net.SocketAddressPal.GetIPv6Address(), System.Net.Sockets.IPEndPointExtensions.GetNetSocketAddress(), System.Net.Sockets.SocketPal.GetPeerName(), System.Net.SocketAddressPal.GetPort(), System.Net.Sockets.SocketPal.GetSockName(), System.handle, System.Net.Sockets.Socket.LoadSocketTypeFromHandle(), System.Net.Sockets.SocketPal.MaximumAddressSize, and System.GC.SuppressFinalize().