Terraria: System.Net.Sockets.Socket.ReceiveMessageFrom
ReceiveMessageFrom() [1/2]
int System.Net.Sockets.Socket.ReceiveMessageFrom (byte[] buffer, int offset, int size, ref SocketFlags socketFlags, ref EndPoint remoteEP, out IPPacketInformation ipPacketInformation) inline
Definition at line 1877 of file Socket.cs.
    {
        ThrowIfDisposed();
        ValidateBufferArguments(buffer, offset, size);
        ValidateReceiveFromEndpointAndState(remoteEP, "remoteEP");
        SocketPal.CheckDualModeReceiveSupport(this);
        ValidateBlockingMode();
        EndPoint remoteEP2 = remoteEP;
        System.Net.Internals.SocketAddress socketAddress = Serialize(ref remoteEP2);
        System.Net.Internals.SocketAddress socketAddress2 = IPEndPointExtensions.Serialize(remoteEP2);
        SetReceivingPacketInformation();
        System.Net.Internals.SocketAddress receiveAddress;
        int bytesTransferred;
        SocketError socketError = SocketPal.ReceiveMessageFrom(this, _handle, buffer, offset, size, ref socketFlags, socketAddress, out receiveAddress, out ipPacketInformation, out bytesTransferred);
        UpdateReceiveSocketErrorForDisposed(ref socketError, bytesTransferred);
        if (socketError != 0 && socketError != SocketError.MessageSize)
        {
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "ReceiveMessageFrom");
        }
        else if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.BytesReceived(bytesTransferred);
            if (socketError == SocketError.Success && SocketType == SocketType.Dgram)
            {
                SocketsTelemetry.Log.DatagramReceived();
            }
        }
        if (!socketAddress2.Equals(receiveAddress))
        {
            try
            {
                remoteEP = remoteEP2.Create(receiveAddress);
            }
            catch
            {
            }
            if (_rightEndPoint == null)
            {
                _rightEndPoint = remoteEP2;
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Error(this, socketError, "ReceiveMessageFrom");
        }
        return bytesTransferred;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._rightEndPoint, System.buffer, System.Net.Sockets.SocketPal.CheckDualModeReceiveSupport(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.offset, System.Net.Sockets.SocketPal.ReceiveMessageFrom(), System.Net.Sockets.IPEndPointExtensions.Serialize(), System.Net.Sockets.Socket.Serialize(), System.Net.Sockets.Socket.SetReceivingPacketInformation(), System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.UpdateReceiveSocketErrorForDisposed(), System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(), System.Net.Sockets.Socket.ValidateBlockingMode(), System.Net.Sockets.Socket.ValidateBufferArguments(), and System.Net.Sockets.Socket.ValidateReceiveFromEndpointAndState().