Terraria: System.Net.Sockets.Socket.GetSocketOption
GetSocketOption() [3/3]
byte[] System.Net.Sockets.Socket.GetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, int optionLength) inline
Definition at line 2278 of file Socket.cs.
    {
        ThrowIfDisposed();
        byte[] array = new byte[optionLength];
        int optionLength2 = optionLength;
        SocketError sockOpt = SocketPal.GetSockOpt(_handle, optionLevel, optionName, array, ref optionLength2);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"GetSockOpt returns errorCode:{sockOpt}", "GetSocketOption");
        }
        if (sockOpt != 0)
        {
            UpdateStatusAfterSocketErrorAndThrowException(sockOpt, "GetSocketOption");
        }
        if (optionLength != optionLength2)
        {
            byte[] array2 = new byte[optionLength2];
            Buffer.BlockCopy(array, 0, array2, 0, optionLength2);
            array = array2;
        }
        return array;
    }
References System.Net.Sockets.Socket._handle, System.array, System.Buffer.BlockCopy(), System.Net.Sockets.SocketPal.GetSockOpt(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException().