Terraria: System.Net.Sockets.Socket.Close
Close() [1/2]
void System.Net.Sockets.Socket.Close () inline
Definition at line 1342 of file Socket.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"timeout = {_closeTimeout}", "Close");
        }
        Dispose();
    }
References System.Net.Sockets.Socket.Dispose(), System.Net.NetEventSource.Info(), and System.Net.NetEventSource.Log.
Referenced by System.Net.Sockets.TcpClient.TcpClient(), System.Net.Sockets.UdpClient.Connect(), System.Net.Sockets.NetworkStream.Dispose(), System.Net.Sockets.TcpClient.Dispose(), System.Net.Sockets.Socket.DuplicateAndClose(), and System.Net.FtpControlStream.QueueOrCreateDataConection().