Terraria: System.Net.Sockets.Socket.SetReceivingPacketInformation
SetReceivingPacketInformation()
void System.Net.Sockets.Socket.SetReceivingPacketInformation () inline package
Definition at line 3450 of file Socket.cs.
    {
        if (!_receivingPacketInformation)
        {
            IPAddress iPAddress = ((_rightEndPoint is IPEndPoint iPEndPoint) ? iPEndPoint.Address : null);
            if (_addressFamily == AddressFamily.InterNetwork)
            {
                SetSocketOption(SocketOptionLevel.IP, SocketOptionName.PacketInformation, optionValue: true);
            }
            if (iPAddress != null && IsDualMode && (iPAddress.IsIPv4MappedToIPv6 || iPAddress.Equals(IPAddress.IPv6Any)))
            {
                SocketPal.SetReceivingDualModeIPv4PacketInformation(this);
            }
            if (_addressFamily == AddressFamily.InterNetworkV6 && (iPAddress == null || !iPAddress.IsIPv4MappedToIPv6))
            {
                SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.PacketInformation, optionValue: true);
            }
            _receivingPacketInformation = true;
        }
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._receivingPacketInformation, System.Net.Sockets.Socket._rightEndPoint, System.Net.IPAddress.IPv6Any, System.Net.Sockets.Socket.IsDualMode, System.Net.Sockets.SocketPal.SetReceivingDualModeIPv4PacketInformation(), and System.Net.Sockets.Socket.SetSocketOption().
Referenced by System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), and System.Net.Sockets.Socket.ReceiveMessageFromAsync().