Terraria: System.Net.NetworkInformation.Ping.SetUnmanagedStructures
SetUnmanagedStructures()
unsafe void System.Net.NetworkInformation.Ping.SetUnmanagedStructures (byte[] buffer) inline private
Definition at line 634 of file Ping.cs.
    {
        _requestBuffer = SafeLocalAllocHandle.LocalAlloc(buffer.Length);
        byte* ptr = (byte*)(void*)_requestBuffer.DangerousGetHandle();
        for (int i = 0; i < buffer.Length; i++)
        {
            ptr[i] = buffer[i];
        }
    }
References System.Net.NetworkInformation.Ping._requestBuffer, System.buffer, System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), and Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc().
Referenced by System.Net.NetworkInformation.Ping.DoSendPingCore().