Terraria: System.Net.Sockets.Socket.EndSendReceive
EndSendReceive()
int System.Net.Sockets.Socket.EndSendReceive (IAsyncResult asyncResult, out SocketError errorCode) inline private
Definition at line 2582 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (!(System.Threading.Tasks.TaskToApm.GetTask(asyncResult) is Task<int> task))
        {
            throw new ArgumentException(null, "asyncResult");
        }
        if (!task.IsCompleted)
        {
            ((IAsyncResult)task).AsyncWaitHandle.WaitOne();
        }
        if (task.IsCompletedSuccessfully)
        {
            errorCode = SocketError.Success;
            return task.Result;
        }
        errorCode = GetSocketErrorFromFaultedTask(task);
        return 0;
    }
References System.asyncResult, System.Net.Sockets.Socket.GetSocketErrorFromFaultedTask(), System.Threading.Tasks.TaskToApm.GetTask(), System.task, and System.Net.Sockets.Socket.ThrowIfDisposed().
Referenced by System.Net.Sockets.Socket.EndReceive(), and System.Net.Sockets.Socket.EndSend().