Terraria: System.Net.Sockets.Socket.SendToAsync
SendToAsync() [4/4]
bool System.Net.Sockets.Socket.SendToAsync (SocketAsyncEventArgs e, CancellationToken cancellationToken) inline private
Definition at line 3169 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (e == null)
        {
            throw new ArgumentNullException("e");
        }
        if (e.RemoteEndPoint == null)
        {
            throw new ArgumentException(System.SR.Format(System.SR.InvalidNullArgument, "e.RemoteEndPoint"), "e");
        }
        EndPoint remoteEP = e.RemoteEndPoint;
        e._socketAddress = Serialize(ref remoteEP);
        e.StartOperationCommon(this, SocketAsyncOperation.SendTo);
        EndPoint rightEndPoint = _rightEndPoint;
        if (_rightEndPoint == null)
        {
            _rightEndPoint = remoteEP;
        }
        SocketError socketError;
        try
        {
            socketError = e.DoOperationSendTo(_handle, cancellationToken);
        }
        catch
        {
            _rightEndPoint = rightEndPoint;
            _localEndPoint = null;
            e.Complete();
            throw;
        }
        if (!CheckErrorAndUpdateStatus(socketError))
        {
            _rightEndPoint = rightEndPoint;
            _localEndPoint = null;
        }
        return socketError == SocketError.IOPending;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._localEndPoint, System.Net.Sockets.Socket._rightEndPoint, System.cancellationToken, System.Net.Sockets.Socket.CheckErrorAndUpdateStatus(), System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendTo(), System.SR.Format(), System.SR.InvalidNullArgument, System.Net.Sockets.SocketAsyncEventArgs.RemoteEndPoint, System.Net.Sockets.Socket.Serialize(), System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(), and System.Net.Sockets.Socket.ThrowIfDisposed().