Terraria: System.Net.Sockets.Socket.ConnectAsync
ConnectAsync() [8/11]
bool System.Net.Sockets.Socket.ConnectAsync (SocketAsyncEventArgs e, bool userSocket, bool saeaCancelable) inline package
Definition at line 2827 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (e == null)
        {
            throw new ArgumentNullException("e");
        }
        if (e.HasMultipleBuffers)
        {
            throw new ArgumentException(System.SR.net_multibuffernotsupported, "BufferList");
        }
        if (e.RemoteEndPoint == null)
        {
            throw new ArgumentNullException("remoteEP");
        }
        if (_isListening)
        {
            throw new InvalidOperationException(System.SR.net_sockets_mustnotlisten);
        }
        if (_isConnected)
        {
            throw new SocketException(10056);
        }
        EndPoint remoteEP = e.RemoteEndPoint;
        if (remoteEP is DnsEndPoint dnsEndPoint)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.ConnectedAsyncDns(this);
            }
            if (dnsEndPoint.AddressFamily != 0 && !CanTryAddressFamily(dnsEndPoint.AddressFamily))
            {
                throw new NotSupportedException(System.SR.net_invalidversion);
            }
            e.StartOperationCommon(this, SocketAsyncOperation.Connect);
            e.StartOperationConnect(saeaCancelable, userSocket);
            try
            {
                return e.DnsConnectAsync(dnsEndPoint, (SocketType)0, ProtocolType.IP);
            }
            catch
            {
                e.Complete();
                throw;
            }
        }
        if (!CanTryAddressFamily(e.RemoteEndPoint.AddressFamily))
        {
            throw new NotSupportedException(System.SR.net_invalidversion);
        }
        e._socketAddress = Serialize(ref remoteEP);
        _pendingConnectRightEndPoint = remoteEP;
        _nonBlockingConnectInProgress = false;
        WildcardBindForConnectIfNecessary(remoteEP.AddressFamily);
        if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.ConnectStart(e._socketAddress);
        }
        e.StartOperationCommon(this, SocketAsyncOperation.Connect);
        e.StartOperationConnect(saeaMultiConnectCancelable: false, userSocket);
        try
        {
            SocketError socketError = ((_socketType == SocketType.Stream && remoteEP.AddressFamily != AddressFamily.Unix) ? e.DoOperationConnectEx(this, _handle) : e.DoOperationConnect(this, _handle));
            return socketError == SocketError.IOPending;
        }
        catch (Exception ex)
        {
            if (SocketsTelemetry.Log.IsEnabled())
            {
                SocketsTelemetry.Log.AfterConnect(SocketError.NotSocket, ex.Message);
            }
            _localEndPoint = null;
            e.Complete();
            throw;
        }
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket._isListening, System.Net.Sockets.Socket._localEndPoint, System.Net.Sockets.Socket._nonBlockingConnectInProgress, System.Net.Sockets.Socket._pendingConnectRightEndPoint, System.Net.Sockets.SocketAsyncEventArgs._socketAddress, System.Net.Sockets.Socket._socketType, System.Net.EndPoint.AddressFamily, System.Net.Sockets.Socket.CanTryAddressFamily(), System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.NetEventSource.ConnectedAsyncDns(), System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnect(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationConnectEx(), System.Net.Sockets.SocketAsyncEventArgs.HasMultipleBuffers, System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.SR.net_invalidversion, System.SR.net_multibuffernotsupported, System.SR.net_sockets_mustnotlisten, System.Net.Sockets.SocketAsyncEventArgs.RemoteEndPoint, System.Net.Sockets.Socket.Serialize(), System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(), System.Net.Sockets.SocketAsyncEventArgs.StartOperationConnect(), System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.Sockets.Socket.WildcardBindForConnectIfNecessary().