Terraria: System.Net.NetworkInformation.Ping.Finish
Finish()
void System.Net.NetworkInformation.Ping.Finish () inline private
Definition at line 136 of file Ping.cs.
    {
        lock (_lockObject)
        {
            _status = 0;
            _lockObject.Set();
        }
        if (_disposeRequested)
        {
            InternalDispose();
        }
    }
References System.Net.NetworkInformation.Ping._disposeRequested, System.Net.NetworkInformation.Ping._lockObject, System.Net.NetworkInformation.Ping._status, System.Net.NetworkInformation.Ping.InternalDispose(), and System.Threading.ManualResetEventSlim.Set().
Referenced by System.Net.NetworkInformation.Ping.GetAddressAndSend(), System.Net.NetworkInformation.Ping.GetAddressAndSendAsync(), System.Net.NetworkInformation.Ping.Send(), and System.Net.NetworkInformation.Ping.SendPingAsyncInternal().