Terraria: System.Net.NetworkInformation.Ping.DoSendPingCore
DoSendPingCore()
Task< PingReply > System.Net.NetworkInformation.Ping.DoSendPingCore (IPAddress address, byte[] buffer, int timeout, PingOptions options, bool isAsync) inline private
Definition at line 457 of file Ping.cs.
    {
        TaskCompletionSource<PingReply> taskCompletionSource = null;
        if (isAsync)
        {
            taskCompletionSource = (_taskCompletionSource = new TaskCompletionSource<PingReply>());
        }
        _ipv6 = address.AddressFamily == AddressFamily.InterNetworkV6;
        _sendSize = buffer.Length;
        InitialiseIcmpHandle();
        if (_replyBuffer == null)
        {
            _replyBuffer = SafeLocalAllocHandle.LocalAlloc(65791);
        }
        int num;
        try
        {
            if (isAsync)
            {
                RegisterWaitHandle();
            }
            SetUnmanagedStructures(buffer);
            num = SendEcho(address, buffer, timeout, options, isAsync);
        }
        catch
        {
            Cleanup(isAsync);
            throw;
        }
        if (num == 0)
        {
            num = Marshal.GetLastPInvokeError();
            if (!isAsync || (long)num != 997)
            {
                Cleanup(isAsync);
                IPStatus statusFromCode = GetStatusFromCode(num);
                return Task.FromResult(new PingReply(address, null, statusFromCode, 0L, Array.Empty<byte>()));
            }
        }
        if (taskCompletionSource != null)
        {
            return taskCompletionSource.Task;
        }
        Cleanup(isAsync);
        return Task.FromResult(CreatePingReply());
    }
References System.Net.NetworkInformation.Ping._ipv6, System.Net.NetworkInformation.Ping._replyBuffer, System.Net.NetworkInformation.Ping._sendSize, System.Net.NetworkInformation.Ping._taskCompletionSource, System.buffer, System.Net.NetworkInformation.Ping.Cleanup(), System.Net.NetworkInformation.Ping.CreatePingReply(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.Net.NetworkInformation.Ping.GetStatusFromCode(), System.Net.NetworkInformation.Ping.InitialiseIcmpHandle(), System.L, Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc(), System.options, System.Net.NetworkInformation.Ping.RegisterWaitHandle(), System.Net.NetworkInformation.Ping.SendEcho(), System.Net.NetworkInformation.Ping.SetUnmanagedStructures(), System.Threading.Tasks.TaskCompletionSource< TResult >.Task, and System.timeout.
Referenced by System.Net.NetworkInformation.Ping.SendPingAsyncCore(), and System.Net.NetworkInformation.Ping.SendPingCore().