Terraria: System.Net.NetworkInformation.Ping.CheckArgs
CheckArgs() [1/2]
void System.Net.NetworkInformation.Ping.CheckArgs (int timeout, byte[] buffer, PingOptions options) inline private
Definition at line 71 of file Ping.cs.
    {
        CheckDisposed();
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (buffer.Length > 65500)
        {
            throw new ArgumentException(System.SR.net_invalidPingBufferSize, "buffer");
        }
        if (timeout < 0)
        {
            throw new ArgumentOutOfRangeException("timeout");
        }
    }
References System.buffer, System.Net.NetworkInformation.Ping.CheckDisposed(), System.SR.net_invalidPingBufferSize, and System.timeout.
Referenced by System.Net.NetworkInformation.Ping.CheckArgs(), System.Net.NetworkInformation.Ping.Send(), System.Net.NetworkInformation.Ping.Send(), System.Net.NetworkInformation.Ping.SendPingAsync(), and System.Net.NetworkInformation.Ping.SendPingAsync().