Terraria: System.Net.Sockets.Socket.ValidateBuffer
ValidateBuffer()
static void System.Net.Sockets.Socket.ValidateBuffer (ArraySegment< byte > buffer) inline static private
Definition at line 4266 of file Socket.cs.
    {
        if (buffer.Array == null)
        {
            throw new ArgumentNullException("Array");
        }
        if ((uint)buffer.Offset > (uint)buffer.Array.Length)
        {
            throw new ArgumentOutOfRangeException("Offset");
        }
        if ((uint)buffer.Count > (uint)(buffer.Array.Length - buffer.Offset))
        {
            throw new ArgumentOutOfRangeException("Count");
        }
    }
References System.buffer.
Referenced by System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveFromAsync(), System.Net.Sockets.Socket.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.SendAsync(), and System.Net.Sockets.Socket.SendToAsync().