Terraria: System.Net.Sockets.Socket.Connect
Connect() [4/4]
void System.Net.Sockets.Socket.Connect (string host, int port) inline
Definition at line 1270 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (host == null)
        {
            throw new ArgumentNullException("host");
        }
        if (!System.Net.TcpValidationHelpers.ValidatePortNumber(port))
        {
            throw new ArgumentOutOfRangeException("port");
        }
        if (_addressFamily != AddressFamily.InterNetwork && _addressFamily != AddressFamily.InterNetworkV6)
        {
            throw new NotSupportedException(System.SR.net_invalidversion);
        }
        if (IPAddress.TryParse(host, out IPAddress address))
        {
            Connect(address, port);
            return;
        }
        IPAddress[] hostAddresses = Dns.GetHostAddresses(host);
        Connect(hostAddresses, port);
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Connect, System.Net.Dns.GetHostAddresses(), System.SR.net_invalidversion, System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.IPAddress.TryParse(), and System.Net.TcpValidationHelpers.ValidatePortNumber().