Terraria: System.Net.Sockets.Socket.SendPacketsAsync
SendPacketsAsync() [2/2]
bool System.Net.Sockets.Socket.SendPacketsAsync (SocketAsyncEventArgs e, CancellationToken cancellationToken) inline private
Definition at line 3135 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (e == null)
        {
            throw new ArgumentNullException("e");
        }
        if (e.SendPacketsElements == null)
        {
            throw new ArgumentException(System.SR.Format(System.SR.InvalidNullArgument, "e.SendPacketsElements"), "e");
        }
        if (!Connected)
        {
            throw new NotSupportedException(System.SR.net_notconnected);
        }
        e.StartOperationCommon(this, SocketAsyncOperation.SendPackets);
        SocketError socketError;
        try
        {
            socketError = e.DoOperationSendPackets(this, _handle, cancellationToken);
        }
        catch (Exception)
        {
            e.Complete();
            throw;
        }
        return socketError == SocketError.IOPending;
    }
References System.Net.Sockets.Socket._handle, System.cancellationToken, System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.Sockets.Socket.Connected, System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets(), System.SR.Format(), System.SR.InvalidNullArgument, System.SR.net_notconnected, System.Net.Sockets.SocketAsyncEventArgs.SendPacketsElements, System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(), and System.Net.Sockets.Socket.ThrowIfDisposed().