Terraria: System.Net.Sockets.Socket.SendAsync
SendAsync() [2/5]
Task< int > System.Net.Sockets.Socket.SendAsync (IList< ArraySegment< byte > > buffers, SocketFlags socketFlags) inline
Definition at line 4158 of file Socket.cs.
    {
        ValidateBuffersList(buffers);
        TaskSocketAsyncEventArgs<int> taskSocketAsyncEventArgs = Interlocked.Exchange(ref _multiBufferSendEventArgs, null);
        if (taskSocketAsyncEventArgs == null)
        {
            taskSocketAsyncEventArgs = new TaskSocketAsyncEventArgs<int>();
            taskSocketAsyncEventArgs.Completed += delegate(object s, SocketAsyncEventArgs e)
            {
                CompleteSendReceive((Socket)s, (TaskSocketAsyncEventArgs<int>)e, isReceive: false);
            };
        }
        taskSocketAsyncEventArgs.BufferList = buffers;
        taskSocketAsyncEventArgs.SocketFlags = socketFlags;
        return GetTaskForSendReceive(SendAsync(taskSocketAsyncEventArgs), taskSocketAsyncEventArgs, fromNetworkStream: false, isReceive: false);
    }
References System.Net.Sockets.Socket._multiBufferSendEventArgs, System.buffers, System.Net.Sockets.Socket.CompleteSendReceive(), System.Threading.Interlocked.Exchange(), System.Net.Sockets.Socket.GetTaskForSendReceive(), System.s, System.Net.Sockets.Socket.SendAsync(), and System.Net.Sockets.Socket.ValidateBuffersList().