Terraria: System.Net.Sockets.Socket.GetTaskForSendReceive
GetTaskForSendReceive()
Task< int > System.Net.Sockets.Socket.GetTaskForSendReceive (bool pending, TaskSocketAsyncEventArgs< int > saea, bool fromNetworkStream, bool isReceive) inline private
Definition at line 4294 of file Socket.cs.
    {
        Task<int> result;
        if (pending)
        {
            result = saea.GetCompletionResponsibility(out var responsibleForReturningToPool).Task;
            if (responsibleForReturningToPool)
            {
                ReturnSocketAsyncEventArgs(saea, isReceive);
            }
        }
        else
        {
            result = ((saea.SocketError != 0) ? Task.FromException<int>(GetException(saea.SocketError, fromNetworkStream)) : Task.FromResult((!(fromNetworkStream && !isReceive)) ? saea.BytesTransferred : 0));
            ReturnSocketAsyncEventArgs(saea, isReceive);
        }
        return result;
    }
References System.Threading.Tasks.Task< TResult >.FromException(), System.Net.Sockets.Socket.GetException(), and System.Net.Sockets.Socket.ReturnSocketAsyncEventArgs().
Referenced by System.Net.Sockets.Socket.ReceiveAsync(), and System.Net.Sockets.Socket.SendAsync().