Terraria: System.Net.Sockets.Socket.ConnectAsync
ConnectAsync() [9/11]
static bool System.Net.Sockets.Socket.ConnectAsync (SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e) inline static
Definition at line 2904 of file Socket.cs.
    {
        if (e == null)
        {
            throw new ArgumentNullException("e");
        }
        if (e.HasMultipleBuffers)
        {
            throw new ArgumentException(System.SR.net_multibuffernotsupported, "e");
        }
        if (e.RemoteEndPoint == null)
        {
            throw new ArgumentException(System.SR.Format(System.SR.InvalidNullArgument, "e.RemoteEndPoint"), "e");
        }
        EndPoint remoteEndPoint = e.RemoteEndPoint;
        if (remoteEndPoint is DnsEndPoint dnsEndPoint)
        {
            Socket socket = ((dnsEndPoint.AddressFamily != 0) ? new Socket(dnsEndPoint.AddressFamily, socketType, protocolType) : null);
            e.StartOperationCommon(socket, SocketAsyncOperation.Connect);
            e.StartOperationConnect(saeaMultiConnectCancelable: true, userSocket: false);
            try
            {
                return e.DnsConnectAsync(dnsEndPoint, socketType, protocolType);
            }
            catch
            {
                e.Complete();
                throw;
            }
        }
        Socket socket2 = new Socket(remoteEndPoint.AddressFamily, socketType, protocolType);
        return socket2.ConnectAsync(e, userSocket: false, saeaCancelable: true);
    }
References System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), System.SR.Format(), System.Net.Sockets.SocketAsyncEventArgs.HasMultipleBuffers, System.SR.InvalidNullArgument, System.SR.net_multibuffernotsupported, System.Net.Sockets.SocketAsyncEventArgs.RemoteEndPoint, System.Net.Sockets.Socket, System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(), and System.Net.Sockets.SocketAsyncEventArgs.StartOperationConnect().