Terraria: System.Net.Sockets.Socket.ReceiveMessageFrom
ReceiveMessageFrom() [2/2]
int System.Net.Sockets.Socket.ReceiveMessageFrom (Span< byte > buffer, ref SocketFlags socketFlags, ref EndPoint remoteEP, out IPPacketInformation ipPacketInformation) inline
Definition at line 1925 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (remoteEP == null)
        {
            throw new ArgumentNullException("remoteEP");
        }
        if (!CanTryAddressFamily(remoteEP.AddressFamily))
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_InvalidEndPointAddressFamily, remoteEP.AddressFamily, _addressFamily), "remoteEP");
        }
        if (_rightEndPoint == null)
        {
            throw new InvalidOperationException(System.SR.net_sockets_mustbind);
        }
        SocketPal.CheckDualModeReceiveSupport(this);
        ValidateBlockingMode();
        EndPoint remoteEP2 = remoteEP;
        System.Net.Internals.SocketAddress socketAddress = Serialize(ref remoteEP2);
        System.Net.Internals.SocketAddress socketAddress2 = IPEndPointExtensions.Serialize(remoteEP2);
        SetReceivingPacketInformation();
        System.Net.Internals.SocketAddress receiveAddress;
        int bytesTransferred;
        SocketError socketError = SocketPal.ReceiveMessageFrom(this, _handle, buffer, ref socketFlags, socketAddress, out receiveAddress, out ipPacketInformation, out bytesTransferred);
        UpdateReceiveSocketErrorForDisposed(ref socketError, bytesTransferred);
        if (socketError != 0 && socketError != SocketError.MessageSize)
        {
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "ReceiveMessageFrom");
        }
        else if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.BytesReceived(bytesTransferred);
            if (socketError == SocketError.Success && SocketType == SocketType.Dgram)
            {
                SocketsTelemetry.Log.DatagramReceived();
            }
        }
        if (!socketAddress2.Equals(receiveAddress))
        {
            try
            {
                remoteEP = remoteEP2.Create(receiveAddress);
            }
            catch
            {
            }
            if (_rightEndPoint == null)
            {
                _rightEndPoint = remoteEP2;
            }
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Error(this, socketError, "ReceiveMessageFrom");
        }
        return bytesTransferred;
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._rightEndPoint, System.buffer, System.Net.Sockets.Socket.CanTryAddressFamily(), System.Net.Sockets.SocketPal.CheckDualModeReceiveSupport(), System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.SR.net_InvalidEndPointAddressFamily, System.SR.net_sockets_mustbind, System.Net.Sockets.SocketPal.ReceiveMessageFrom(), System.Net.Sockets.IPEndPointExtensions.Serialize(), System.Net.Sockets.Socket.Serialize(), System.Net.Sockets.Socket.SetReceivingPacketInformation(), System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.UpdateReceiveSocketErrorForDisposed(), System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(), and System.Net.Sockets.Socket.ValidateBlockingMode().