Terraria: System.Net.Sockets.Socket.ThrowIfDisposed
ThrowIfDisposed()
void System.Net.Sockets.Socket.ThrowIfDisposed () inline private
Definition at line 3822 of file Socket.cs.
    {
        if (Disposed)
        {
            ThrowObjectDisposedException();
        }
    }
References System.Net.Sockets.Socket.Disposed, and System.Net.Sockets.Socket.ThrowObjectDisposedException().
Referenced by System.Net.Sockets.Socket.Accept(), System.Net.Sockets.Socket.AcceptAsync(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceiveFrom(), System.Net.Sockets.Socket.BeginReceiveMessageFrom(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSendFile(), System.Net.Sockets.Socket.BeginSendTo(), System.Net.Sockets.Socket.Bind(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.Socket.Disconnect(), System.Net.Sockets.Socket.DisconnectAsync(), System.Net.Sockets.Socket.DuplicateAndClose(), System.Net.Sockets.Socket.EndAccept(), System.Net.Sockets.Socket.EndAccept(), System.Net.Sockets.Socket.EndConnect(), System.Net.Sockets.Socket.EndDisconnect(), System.Net.Sockets.Socket.EndReceive(), System.Net.Sockets.Socket.EndReceiveFrom(), System.Net.Sockets.Socket.EndReceiveMessageFrom(), System.Net.Sockets.Socket.EndSend(), System.Net.Sockets.Socket.EndSendFile(), System.Net.Sockets.Socket.EndSendReceive(), System.Net.Sockets.Socket.EndSendTo(), System.Net.Sockets.Socket.GetRawSocketOption(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.IOControl(), System.Net.Sockets.Socket.Listen(), System.Net.Sockets.Socket.Poll(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveFromAsync(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.Socket.SendFile(), System.Net.Sockets.Socket.SendPacketsAsync(), System.Net.Sockets.Socket.SendTo(), System.Net.Sockets.Socket.SendTo(), System.Net.Sockets.Socket.SendToAsync(), System.Net.Sockets.Socket.SetRawSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), and System.Net.Sockets.Socket.Shutdown().