Terraria: System.Net.Sockets.Socket.SetSocketOption
SetSocketOption() [5/5]
void System.Net.Sockets.Socket.SetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, object optionValue) inline
Definition at line 2176 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (optionValue == null)
        {
            throw new ArgumentNullException("optionValue");
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"optionLevel:{optionLevel} optionName:{optionName} optionValue:{optionValue}", "SetSocketOption");
        }
        if (optionLevel == SocketOptionLevel.Socket && optionName == SocketOptionName.Linger)
        {
            if (!(optionValue is LingerOption lingerOption))
            {
                throw new ArgumentException(System.SR.Format(System.SR.net_sockets_invalid_optionValue, "LingerOption"), "optionValue");
            }
            if (lingerOption.LingerTime < 0 || lingerOption.LingerTime > 65535)
            {
                throw new ArgumentException(System.SR.Format(System.SR.ArgumentOutOfRange_Bounds_Lower_Upper_Named, 0, 65535, "optionValue.LingerTime"), "optionValue");
            }
            SetLingerOption(lingerOption);
        }
        else if (optionLevel == SocketOptionLevel.IP && (optionName == SocketOptionName.AddMembership || optionName == SocketOptionName.DropMembership))
        {
            if (!(optionValue is MulticastOption mR))
            {
                throw new ArgumentException(System.SR.Format(System.SR.net_sockets_invalid_optionValue, "MulticastOption"), "optionValue");
            }
            SetMulticastOption(optionName, mR);
        }
        else
        {
            if (optionLevel != SocketOptionLevel.IPv6 || (optionName != SocketOptionName.AddMembership && optionName != SocketOptionName.DropMembership))
            {
                throw new ArgumentException(System.SR.net_sockets_invalid_optionValue_all, "optionValue");
            }
            if (!(optionValue is IPv6MulticastOption mR2))
            {
                throw new ArgumentException(System.SR.Format(System.SR.net_sockets_invalid_optionValue, "IPv6MulticastOption"), "optionValue");
            }
            SetIPv6MulticastOption(optionName, mR2);
        }
    }
References System.SR.ArgumentOutOfRange_Bounds_Lower_Upper_Named, System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_sockets_invalid_optionValue, System.SR.net_sockets_invalid_optionValue_all, System.Net.Sockets.Socket.SetIPv6MulticastOption(), System.Net.Sockets.Socket.SetLingerOption(), System.Net.Sockets.Socket.SetMulticastOption(), and System.Net.Sockets.Socket.ThrowIfDisposed().