Terraria: System.Net.Sockets.Socket.ValidateBlockingMode
ValidateBlockingMode()
void System.Net.Sockets.Socket.ValidateBlockingMode () inline private
Definition at line 3773 of file Socket.cs.
    {
        if (_willBlock && !_willBlockInternal)
        {
            throw new InvalidOperationException(System.SR.net_invasync);
        }
    }
References System.Net.Sockets.Socket._willBlock, System.Net.Sockets.Socket._willBlockInternal, and System.SR.net_invasync.
Referenced by System.Net.Sockets.Socket.Accept(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.SendFile(), System.Net.Sockets.Socket.SendTo(), and System.Net.Sockets.Socket.SendTo().