Terraria: System.Net.Sockets.Socket.GetSocketOption
GetSocketOption() [1/3]
object? System.Net.Sockets.Socket.GetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName) inline
Definition at line 2235 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (optionLevel == SocketOptionLevel.Socket && optionName == SocketOptionName.Linger)
        {
            return GetLingerOpt();
        }
        if (optionLevel == SocketOptionLevel.IP && (optionName == SocketOptionName.AddMembership || optionName == SocketOptionName.DropMembership))
        {
            return GetMulticastOpt(optionName);
        }
        if (optionLevel == SocketOptionLevel.IPv6 && (optionName == SocketOptionName.AddMembership || optionName == SocketOptionName.DropMembership))
        {
            return GetIPv6MulticastOpt(optionName);
        }
        int optionValue = 0;
        SocketError sockOpt = SocketPal.GetSockOpt(_handle, optionLevel, optionName, out optionValue);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"GetSockOpt returns errorCode:{sockOpt}", "GetSocketOption");
        }
        if (sockOpt != 0)
        {
            UpdateStatusAfterSocketErrorAndThrowException(sockOpt, "GetSocketOption");
        }
        return optionValue;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket.GetIPv6MulticastOpt(), System.Net.Sockets.Socket.GetLingerOpt(), System.Net.Sockets.Socket.GetMulticastOpt(), System.Net.Sockets.SocketPal.GetSockOpt(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException().