Terraria: System.Net.Sockets.Socket.SendAsync
SendAsync() [4/5]
bool System.Net.Sockets.Socket.SendAsync (SocketAsyncEventArgs e) inline
Definition at line 3104 of file Socket.cs.
    {
        return SendAsync(e, default(CancellationToken));
    }
References System.Net.Sockets.Socket.SendAsync().
Referenced by System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.UdpClient.SendAsync(), System.Net.Sockets.Socket.SendAsync(), System.Net.Sockets.UdpClient.SendAsync(), and System.Net.Sockets.Socket.SendAsync().