Terraria: System.Net.NetworkInformation.Ping.SendEcho
SendEcho()
int System.Net.NetworkInformation.Ping.SendEcho (IPAddress address, byte[] buffer, int timeout, PingOptions options, bool isAsync) inline private
Definition at line 563 of file Ping.cs.
    {
        global::Interop.IpHlpApi.IPOptions options2 = new global::Interop.IpHlpApi.IPOptions(options);
        if (!_ipv6)
        {
            return (int)global::Interop.IpHlpApi.IcmpSendEcho2(_handlePingV4, GetWaitHandle(isAsync), IntPtr.Zero, IntPtr.Zero, (uint)address.Address, _requestBuffer, (ushort)buffer.Length, ref options2, _replyBuffer, 65791u, (uint)timeout);
        }
        IPEndPoint endpoint = new IPEndPoint(address, 0);
        System.Net.Internals.SocketAddress socketAddress = IPEndPointExtensions.Serialize(endpoint);
        byte[] sourceSocketAddress = new byte[28];
        return (int)global::Interop.IpHlpApi.Icmp6SendEcho2(_handlePingV6, GetWaitHandle(isAsync), IntPtr.Zero, IntPtr.Zero, sourceSocketAddress, socketAddress.Buffer, _requestBuffer, (ushort)buffer.Length, ref options2, _replyBuffer, 65791u, (uint)timeout);
    }
References System.Net.NetworkInformation.Ping._handlePingV4, System.Net.NetworkInformation.Ping._handlePingV6, System.Net.NetworkInformation.Ping._ipv6, System.Net.NetworkInformation.Ping._replyBuffer, System.Net.NetworkInformation.Ping._requestBuffer, System.Net.IPAddress.Address, System.Net.Internals.SocketAddress.Buffer, System.buffer, System.Net.NetworkInformation.Ping.GetWaitHandle(), System.options, System.Net.Sockets.IPEndPointExtensions.Serialize(), System.timeout, and System.IntPtr.Zero.
Referenced by System.Net.NetworkInformation.Ping.DoSendPingCore().