Terraria: System.Net.NetworkInformation.Ping.TranslateTaskToEap
TranslateTaskToEap()
void System.Net.NetworkInformation.Ping.TranslateTaskToEap (object userToken, Task< PingReply > pingTask) inline private
Definition at line 279 of file Ping.cs.
    {
        pingTask.ContinueWith(delegate(Task<PingReply> t, object state)
        {
            AsyncOperation asyncOperation = (AsyncOperation)state;
            PingCompletedEventArgs arg = new PingCompletedEventArgs(t.IsCompletedSuccessfully ? t.Result : null, t.Exception, t.IsCanceled, asyncOperation.UserSuppliedState);
            SendOrPostCallback d = delegate(object o)
            {
                OnPingCompleted((PingCompletedEventArgs)o);
            };
            asyncOperation.PostOperationCompleted(d, arg);
        }, AsyncOperationManager.CreateOperation(userToken), CancellationToken.None, TaskContinuationOptions.DenyChildAttach, TaskScheduler.Default);
    }
References System.Threading.Tasks.Task< TResult >.ContinueWith(), System.ComponentModel.AsyncOperationManager.CreateOperation(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Exception, System.Threading.Tasks.Task< TResult >.IsCanceled, System.Threading.Tasks.Task< TResult >.IsCompletedSuccessfully, System.Threading.CancellationToken.None, System.Net.NetworkInformation.Ping.OnPingCompleted(), System.ComponentModel.AsyncOperation.PostOperationCompleted(), System.Threading.Tasks.Task< TResult >.Result, System.state, and System.ComponentModel.AsyncOperation.UserSuppliedState.
Referenced by System.Net.NetworkInformation.Ping.SendAsync(), and System.Net.NetworkInformation.Ping.SendAsync().