Terraria: System.Net.Sockets.Socket.GetSocketErrorFromFaultedTask
GetSocketErrorFromFaultedTask()
static SocketError System.Net.Sockets.Socket.GetSocketErrorFromFaultedTask (Task t) inline static private
Definition at line 3854 of file Socket.cs.
    {
        if (t.IsCanceled)
        {
            return SocketError.OperationAborted;
        }
        Exception innerException = t.Exception.InnerException;
        if (!(innerException is SocketException { SocketErrorCode: var socketErrorCode }))
        {
            if (!(innerException is ObjectDisposedException))
            {
                if (innerException is OperationCanceledException)
                {
                    return SocketError.OperationAborted;
                }
                return SocketError.SocketError;
            }
            return SocketError.OperationAborted;
        }
        return socketErrorCode;
    }
References System.Threading.Tasks.Task< TResult >.Exception, System.Exception.InnerException, and System.Threading.Tasks.Task< TResult >.IsCanceled.
Referenced by System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSend(), and System.Net.Sockets.Socket.EndSendReceive().