Terraria: System.Net.Sockets.Socket.BeginReceiveMessageFrom
BeginReceiveMessageFrom()
IAsyncResult System.Net.Sockets.Socket.BeginReceiveMessageFrom (byte[] buffer, int offset, int size, SocketFlags socketFlags, ref EndPoint remoteEP, AsyncCallback? callback, object? state) inline
Definition at line 2602 of file Socket.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"size:{size}", "BeginReceiveMessageFrom");
        }
        ThrowIfDisposed();
        ValidateBufferArguments(buffer, offset, size);
        ValidateReceiveFromEndpointAndState(remoteEP, "remoteEP");
        Task<SocketReceiveMessageFromResult> task = ReceiveMessageFromAsync(buffer.AsMemory(offset, size), socketFlags, remoteEP).AsTask();
        if (task.IsCompletedSuccessfully)
        {
            EndPoint remoteEndPoint = task.Result.RemoteEndPoint;
            if (!remoteEP.Equals(remoteEndPoint))
            {
                remoteEP = remoteEndPoint;
            }
        }
        IAsyncResult asyncResult = System.Threading.Tasks.TaskToApm.Begin(task, callback, state);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"size:{size} returning AsyncResult:{asyncResult}", "BeginReceiveMessageFrom");
        }
        return asyncResult;
    }
References System.asyncResult, System.Threading.Tasks.TaskToApm.Begin(), System.buffer, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.offset, System.Net.Sockets.Socket.ReceiveMessageFromAsync(), System.state, System.task, System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.ValidateBufferArguments(), and System.Net.Sockets.Socket.ValidateReceiveFromEndpointAndState().