Terraria: System.Net.Sockets.Socket.Serialize
Serialize()
System.Net.Internals.SocketAddress System.Net.Sockets.Socket.Serialize (ref EndPoint remoteEP) inline private
Definition at line 3225 of file Socket.cs.
    {
        if (remoteEP is IPEndPoint iPEndPoint)
        {
            IPAddress address = iPEndPoint.Address;
            if (address.AddressFamily == AddressFamily.InterNetwork && IsDualMode)
            {
                address = address.MapToIPv6();
                remoteEP = new IPEndPoint(address, iPEndPoint.Port);
            }
        }
        else if (remoteEP is DnsEndPoint)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_sockets_invalid_dnsendpoint, "remoteEP"), "remoteEP");
        }
        return IPEndPointExtensions.Serialize(remoteEP);
    }
References System.Net.IPAddress.AddressFamily, System.SR.Format(), System.Net.Sockets.Socket.IsDualMode, System.Net.IPAddress.MapToIPv6(), System.SR.net_sockets_invalid_dnsendpoint, and System.Net.Sockets.IPEndPointExtensions.Serialize().
Referenced by System.Net.Sockets.Socket.Bind(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveFromAsync(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFromAsync(), System.Net.Sockets.Socket.SendTo(), System.Net.Sockets.Socket.SendTo(), and System.Net.Sockets.Socket.SendToAsync().