Terraria: System.Net.Sockets.Socket.SelectFileDescriptor
SelectFileDescriptor()
static void System.Net.Sockets.Socket.SelectFileDescriptor (IList socketList, Span< IntPtr > fileDescriptorSet, ref int refsAdded) inline static package
Definition at line 4532 of file Socket.cs.
    {
        int num;
        if (socketList == null || (num = socketList.Count) == 0)
        {
            return;
        }
        int num2 = (int)fileDescriptorSet[0];
        if (num2 == 0)
        {
            SocketListDangerousReleaseRefs(socketList, ref refsAdded);
            socketList.Clear();
            return;
        }
        lock (socketList)
        {
            for (int i = 0; i < num; i++)
            {
                Socket socket = socketList[i] as Socket;
                int j;
                for (j = 0; j < num2 && !(fileDescriptorSet[j + 1] == socket._handle.DangerousGetHandle()); j++)
                {
                }
                if (j == num2)
                {
                    socket.InternalSafeHandle.DangerousRelease();
                    refsAdded--;
                    socketList.RemoveAt(i--);
                    num--;
                }
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.Sockets.Socket, and System.Net.Sockets.Socket.SocketListDangerousReleaseRefs().
Referenced by System.Net.Sockets.SocketPal.Select().