Terraria: System.Net.Sockets.Socket.ConnectAsync
ConnectAsync() [2/11]
ValueTask System.Net.Sockets.Socket.ConnectAsync (EndPoint remoteEP, CancellationToken cancellationToken) inline
Definition at line 3909 of file Socket.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled(cancellationToken);
        }
        AwaitableSocketAsyncEventArgs awaitableSocketAsyncEventArgs = Interlocked.Exchange(ref _singleBufferReceiveEventArgs, null) ?? new AwaitableSocketAsyncEventArgs(this, isReceiveForCaching: true);
        awaitableSocketAsyncEventArgs.RemoteEndPoint = remoteEP;
        ValueTask valueTask = awaitableSocketAsyncEventArgs.ConnectAsync(this);
        if (valueTask.IsCompleted || !cancellationToken.CanBeCanceled)
        {
            return valueTask;
        }
        return WaitForConnectWithCancellation(awaitableSocketAsyncEventArgs, valueTask, cancellationToken);
        static async ValueTask WaitForConnectWithCancellation(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
        {
            try
            {
                using (cancellationToken.UnsafeRegister(delegate(object o)
                {
                    CancelConnectAsync((SocketAsyncEventArgs)o);
                }, saea))
                {
                    await connectTask.ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            catch (SocketException ex) when (ex.SocketErrorCode == SocketError.OperationAborted)
            {
                cancellationToken.ThrowIfCancellationRequested();
                throw;
            }
        }
    }
References System.Net.Sockets.Socket._singleBufferReceiveEventArgs, System.Net.Sockets.Socket.CancelConnectAsync(), System.cancellationToken, System.Threading.Interlocked.Exchange(), and System.Threading.Tasks.ValueTask< TResult >.FromCanceled().