Terraria: System.Net.Sockets.Socket.SendFileAsync
SendFileAsync() [2/2]
ValueTask System.Net.Sockets.Socket.SendFileAsync (string? fileName, ReadOnlyMemory< byte > preBuffer, ReadOnlyMemory< byte > postBuffer, TransmitFileOptions flags, CancellationToken cancellationToken = default(CancellationToken)) inline
Definition at line 4204 of file Socket.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled(cancellationToken);
        }
        if (!IsConnectionOriented)
        {
            SocketException exception = new SocketException(10057);
            return ValueTask.FromException((Exception)(object)exception);
        }
        int num = 0;
        if (fileName != null)
        {
            num++;
        }
        if (!preBuffer.IsEmpty)
        {
            num++;
        }
        if (!postBuffer.IsEmpty)
        {
            num++;
        }
        AwaitableSocketAsyncEventArgs awaitableSocketAsyncEventArgs = Interlocked.Exchange(ref _singleBufferSendEventArgs, null) ?? new AwaitableSocketAsyncEventArgs(this, isReceiveForCaching: false);
        SendPacketsElement[]? sendPacketsElements = awaitableSocketAsyncEventArgs.SendPacketsElements;
        SendPacketsElement[] array = ((sendPacketsElements != null && sendPacketsElements.Length == num) ? awaitableSocketAsyncEventArgs.SendPacketsElements : new SendPacketsElement[num]);
        int num2 = 0;
        if (!preBuffer.IsEmpty)
        {
            array[num2++] = new SendPacketsElement(preBuffer, num2 == num);
        }
        if (fileName != null)
        {
            array[num2++] = new SendPacketsElement(fileName, 0, 0, num2 == num);
        }
        if (!postBuffer.IsEmpty)
        {
            array[num2++] = new SendPacketsElement(postBuffer, num2 == num);
        }
        awaitableSocketAsyncEventArgs.SendPacketsFlags = flags;
        awaitableSocketAsyncEventArgs.SendPacketsElements = array;
        awaitableSocketAsyncEventArgs.WrapExceptionsForNetworkStream = false;
        return awaitableSocketAsyncEventArgs.SendPacketsAsync(this, cancellationToken);
    }
References System.Net.Sockets.Socket._singleBufferSendEventArgs, System.array, System.cancellationToken, System.exception, System.Threading.Interlocked.Exchange(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.Threading.Tasks.ValueTask< TResult >.FromException(), and System.Net.Sockets.Socket.IsConnectionOriented.