Terraria: System.Net.Sockets.Socket.Send
Send() [8/11]
int System.Net.Sockets.Socket.Send (IList< ArraySegment< byte > > buffers, SocketFlags socketFlags, out SocketError errorCode) inline
Definition at line 1476 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (buffers == null)
        {
            throw new ArgumentNullException("buffers");
        }
        if (buffers.Count == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_sockets_zerolist, "buffers"), "buffers");
        }
        ValidateBlockingMode();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"SRC:{LocalEndPoint} DST:{RemoteEndPoint}", "Send");
        }
        errorCode = SocketPal.Send(_handle, buffers, socketFlags, out var bytesTransferred);
        if (errorCode != 0)
        {
            UpdateSendSocketErrorForDisposed(ref errorCode);
            UpdateStatusAfterSocketError(errorCode);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, new SocketException((int)errorCode), "Send");
            }
            return 0;
        }
        if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.BytesSent(bytesTransferred);
            if (SocketType == SocketType.Dgram)
            {
                SocketsTelemetry.Log.DatagramSent();
            }
        }
        return bytesTransferred;
    }
References System.Net.Sockets.Socket._handle, System.buffers, System.Net.NetEventSource.Error(), System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.SR.net_sockets_zerolist, System.Net.Sockets.SocketPal.Send(), System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.UpdateSendSocketErrorForDisposed(), System.Net.Sockets.Socket.UpdateStatusAfterSocketError(), and System.Net.Sockets.Socket.ValidateBlockingMode().