Terraria: System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmpEchoReply
CreatePingReplyFromIcmpEchoReply()
static PingReply System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmpEchoReply (global::Interop::IpHlpApi::IcmpEchoReply reply) inline static private
Definition at line 662 of file Ping.cs.
    {
        IPAddress address = new IPAddress(reply.address);
        IPStatus statusFromCode = GetStatusFromCode((int)reply.status);
        long rtt;
        PingOptions options;
        byte[] array;
        if (statusFromCode == IPStatus.Success)
        {
            rtt = reply.roundTripTime;
            options = new PingOptions(reply.options.ttl, (reply.options.flags & 2) > 0);
            array = new byte[reply.dataSize];
            Marshal.Copy(reply.data, array, 0, reply.dataSize);
        }
        else
        {
            rtt = 0L;
            options = null;
            array = Array.Empty<byte>();
        }
        return new PingReply(address, options, statusFromCode, rtt, array);
    }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Net.NetworkInformation.Ping.GetStatusFromCode(), System.L, and System.options.
Referenced by System.Net.NetworkInformation.Ping.CreatePingReply().