Terraria: System.Net.Sockets.Socket.UpdateStatusAfterSocketError
UpdateStatusAfterSocketError() [1/2]
void System.Net.Sockets.Socket.UpdateStatusAfterSocketError (SocketError errorCode) inline package
Definition at line 3731 of file Socket.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Error(this, $"errorCode:{errorCode}", "UpdateStatusAfterSocketError");
        }
        if (_isConnected && (_handle.IsInvalid || (errorCode != SocketError.WouldBlock && errorCode != SocketError.IOPending && errorCode != SocketError.NoBufferSpaceAvailable && errorCode != SocketError.TimedOut)))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "Invalidating socket.", "UpdateStatusAfterSocketError");
            }
            SetToDisconnected();
        }
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isConnected, System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.Sockets.SafeSocketHandle.IsInvalid, System.Net.NetEventSource.Log, and System.Net.Sockets.Socket.SetToDisconnected().