Terraria: System.Net.Sockets.Socket.CanTryAddressFamily
CanTryAddressFamily()
bool System.Net.Sockets.Socket.CanTryAddressFamily (AddressFamily family) inline package
Definition at line 1159 of file Socket.cs.
    {
        if (family != _addressFamily)
        {
            if (family == AddressFamily.InterNetwork)
            {
                return IsDualMode;
            }
            return false;
        }
        return true;
    }
References System.Net.Sockets.Socket._addressFamily, and System.Net.Sockets.Socket.IsDualMode.
Referenced by System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), System.Net.Sockets.Socket.EndReceiveFrom(), System.Net.Sockets.Socket.EndReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveFromAsync(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFromAsync(), and System.Net.Sockets.Socket.ValidateReceiveFromEndpointAndState().