Terraria: System.Net.Sockets.Socket.Connect
Connect() [1/4]
void System.Net.Sockets.Socket.Connect (EndPoint remoteEP) inline
Definition at line 1206 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (remoteEP == null)
        {
            throw new ArgumentNullException("remoteEP");
        }
        if (_isDisconnected)
        {
            throw new InvalidOperationException(System.SR.net_sockets_disconnectedConnect);
        }
        if (_isListening)
        {
            throw new InvalidOperationException(System.SR.net_sockets_mustnotlisten);
        }
        if (_isConnected)
        {
            throw new SocketException(10056);
        }
        ValidateBlockingMode();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"DST:{remoteEP}", "Connect");
        }
        if (remoteEP is DnsEndPoint dnsEndPoint)
        {
            if (dnsEndPoint.AddressFamily != 0 && !CanTryAddressFamily(dnsEndPoint.AddressFamily))
            {
                throw new NotSupportedException(System.SR.net_invalidversion);
            }
            Connect(dnsEndPoint.Host, dnsEndPoint.Port);
        }
        else
        {
            System.Net.Internals.SocketAddress socketAddress = Serialize(ref remoteEP);
            _pendingConnectRightEndPoint = remoteEP;
            _nonBlockingConnectInProgress = !Blocking;
            DoConnect(remoteEP, socketAddress);
        }
    }
References System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket._isDisconnected, System.Net.Sockets.Socket._isListening, System.Net.Sockets.Socket._nonBlockingConnectInProgress, System.Net.Sockets.Socket._pendingConnectRightEndPoint, System.Net.Sockets.Socket.Blocking, System.Net.Sockets.Socket.CanTryAddressFamily(), System.Net.Sockets.Connect, System.Net.Sockets.Socket.DoConnect(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_invalidversion, System.SR.net_sockets_disconnectedConnect, System.SR.net_sockets_mustnotlisten, System.Net.Sockets.Socket.Serialize(), System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.Sockets.Socket.ValidateBlockingMode().
Referenced by System.Net.Sockets.TcpClient.Connect(), System.Net.Sockets.UdpClient.Connect(), System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), and System.Net.FtpControlStream.QueueOrCreateDataConection().