Terraria: System.Net.Sockets.Socket.Dispose
Dispose() [2/2]
virtual void System.Net.Sockets.Socket.Dispose (bool disposing) inline protected virtual
Definition at line 3294 of file Socket.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            try
            {
                System.Net.NetEventSource.Info(this, $"disposing:{disposing} Disposed:{Disposed}", "Dispose");
            }
            catch (Exception exception) when (!ExceptionCheck.IsFatal(exception))
            {
            }
        }
        if (Interlocked.CompareExchange(ref _disposed, 1, 0) == 1)
        {
            return;
        }
        SetToDisconnected();
        SafeSocketHandle handle = _handle;
        if (handle != null && handle.OwnsHandle)
        {
            if (!disposing)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Calling _handle.Dispose()", "Dispose");
                }
                handle.Dispose();
            }
            else
            {
                try
                {
                    int closeTimeout = _closeTimeout;
                    if (closeTimeout == 0)
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            System.Net.NetEventSource.Info(this, "Calling _handle.CloseAsIs()", "Dispose");
                        }
                        handle.CloseAsIs(abortive: true);
                    }
                    else
                    {
                        if (!_willBlock || !_willBlockInternal)
{
                            bool willBlock;
                            SocketError socketError = SocketPal.SetBlocking(handle, shouldBlock: false, out willBlock);
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"handle:{handle} ioctlsocket(FIONBIO):{socketError}", "Dispose");
                            }
                        }
                        if (closeTimeout < 0)
{
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, "Calling _handle.CloseAsIs()", "Dispose");
                            }
                            handle.CloseAsIs(abortive: false);
                        }
                        else
{
                            SocketError socketError = SocketPal.Shutdown(handle, _isConnected, _isDisconnected, SocketShutdown.Send);
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"handle:{handle} shutdown():{socketError}", "Dispose");
                            }
                            socketError = SocketPal.SetSockOpt(handle, SocketOptionLevel.Socket, SocketOptionName.ReceiveTimeout, closeTimeout);
                            if (System.Net.NetEventSource.Log.IsEnabled())
{
                                System.Net.NetEventSource.Info(this, $"handle:{handle} setsockopt():{socketError}", "Dispose");
                            }
                            if (socketError != 0)
{
                                handle.CloseAsIs(abortive: true);
                            }
                            else
{
                                socketError = SocketPal.Receive(handle, Array.Empty<byte>(), 0, 0, SocketFlags.None, out var _);
                                if (System.Net.NetEventSource.Log.IsEnabled())
{
                                    System.Net.NetEventSource.Info(this, $"handle:{handle} recv():{socketError}", "Dispose");
                                }
                                if (socketError != 0)
{
                                    handle.CloseAsIs(abortive: true);
                                }
                                else
{
                                    int available = 0;
                                    socketError = SocketPal.GetAvailable(handle, out available);
                                    if (System.Net.NetEventSource.Log.IsEnabled())
{
                                        System.Net.NetEventSource.Info(this, $"handle:{handle} ioctlsocket(FIONREAD):{socketError}", "Dispose");
                                    }
                                    if (socketError != 0 || available != 0)
{
                                        handle.CloseAsIs(abortive: true);
                                    }
                                    else
{
                                        handle.CloseAsIs(abortive: false);
                                    }
                                }
                            }
                        }
                    }
                }
                catch (ObjectDisposedException)
                {
                }
            }
            if (_rightEndPoint is UnixDomainSocketEndPoint { BoundFileName: not null } unixDomainSocketEndPoint)
            {
                try
                {
                    File.Delete(unixDomainSocketEndPoint.BoundFileName);
                }
                catch
                {
                }
            }
        }
        DisposeCachedTaskSocketAsyncEventArgs();
    }
References System.Net.Sockets.Socket._closeTimeout, System.Net.Sockets.Socket._disposed, System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket._isDisconnected, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.Socket._willBlock, System.Net.Sockets.Socket._willBlockInternal, System.Threading.Interlocked.CompareExchange(), System.IO.File.Delete(), System.Net.Sockets.Socket.DisposeCachedTaskSocketAsyncEventArgs(), System.exception, System.Net.Sockets.SocketPal.GetAvailable(), System.handle, System.Net.NetEventSource.Info(), System.Net.ExceptionCheck.IsFatal(), System.Net.NetEventSource.Log, System.Net.Sockets.SocketPal.Receive(), System.Net.Sockets.SocketPal.SetBlocking(), System.Net.Sockets.SocketPal.SetSockOpt(), System.Net.Sockets.Socket.SetToDisconnected(), and System.Net.Sockets.SocketPal.Shutdown().
Referenced by System.Net.Sockets.SocketAsyncEventArgs.CancelConnectAsync(), System.Net.Sockets.TcpClient.Connect(), System.Net.Sockets.UdpClient.Dispose(), System.Net.Sockets.SocketAsyncEventArgs.DnsConnectAsync(), and System.Net.Sockets.TcpListener.Stop().