Terraria: System.Net.NetworkInformation.Ping.Send
Send() [8/8]
PingReply System.Net.NetworkInformation.Ping.Send (string hostNameOrAddress, int timeout, byte[] buffer, PingOptions? options) inline
Definition at line 206 of file Ping.cs.
    {
        if (string.IsNullOrEmpty(hostNameOrAddress))
        {
            throw new ArgumentNullException("hostNameOrAddress");
        }
        if (IPAddress.TryParse(hostNameOrAddress, out IPAddress address))
        {
            return Send(address, timeout, buffer, options);
        }
        CheckArgs(timeout, buffer, options);
        return GetAddressAndSend(hostNameOrAddress, timeout, buffer, options);
    }
References System.buffer, System.Net.NetworkInformation.Ping.CheckArgs(), System.Net.NetworkInformation.Ping.GetAddressAndSend(), System.options, System.Net.Sockets.Send, System.timeout, and System.Net.IPAddress.TryParse().