Terraria: System.Net.NetworkInformation.Ping.InternalDisposeCore
InternalDisposeCore()
void System.Net.NetworkInformation.Ping.InternalDisposeCore () inline private
Definition at line 422 of file Ping.cs.
    {
        if (_handlePingV4 != null)
        {
            _handlePingV4.Dispose();
            _handlePingV4 = null;
        }
        if (_handlePingV6 != null)
        {
            _handlePingV6.Dispose();
            _handlePingV6 = null;
        }
        UnregisterWaitHandle();
        if (_pingEvent != null)
        {
            _pingEvent.Dispose();
            _pingEvent = null;
        }
        if (_replyBuffer != null)
        {
            _replyBuffer.Dispose();
            _replyBuffer = null;
        }
    }
References System.Net.NetworkInformation.Ping._handlePingV4, System.Net.NetworkInformation.Ping._handlePingV6, System.Net.NetworkInformation.Ping._pingEvent, System.Net.NetworkInformation.Ping._replyBuffer, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Threading.WaitHandle.Dispose(), and System.Net.NetworkInformation.Ping.UnregisterWaitHandle().
Referenced by System.Net.NetworkInformation.Ping.InternalDispose().