Terraria: System.Net.Sockets.Socket.SetIPProtectionLevel
SetIPProtectionLevel()
void System.Net.Sockets.Socket.SetIPProtectionLevel (IPProtectionLevel level) inline
Definition at line 2318 of file Socket.cs.
    {
        if (level == IPProtectionLevel.Unspecified)
        {
            throw new ArgumentException(System.SR.net_sockets_invalid_optionValue_all, "level");
        }
        if (_addressFamily == AddressFamily.InterNetworkV6)
        {
            SocketPal.SetIPProtectionLevel(this, SocketOptionLevel.IPv6, (int)level);
            return;
        }
        if (_addressFamily == AddressFamily.InterNetwork)
        {
            SocketPal.SetIPProtectionLevel(this, SocketOptionLevel.IP, (int)level);
            return;
        }
        throw new NotSupportedException(System.SR.net_invalidversion);
    }
References System.Net.Sockets.Socket._addressFamily, System.SR.net_invalidversion, System.SR.net_sockets_invalid_optionValue_all, and System.Net.Sockets.SocketPal.SetIPProtectionLevel().
Referenced by System.Net.Sockets.UdpClient.AllowNatTraversal(), and System.Net.Sockets.TcpListener.SetIPProtectionLevel().