Terraria: System.Net.Sockets.Socket.DoConnect
DoConnect()
void System.Net.Sockets.Socket.DoConnect (EndPoint endPointSnapshot, System::Net::Internals::SocketAddress socketAddress) inline private
Definition at line 3243 of file Socket.cs.
    {
        if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.ConnectStart(socketAddress);
        }
        SocketError socketError;
        try
        {
            socketError = SocketPal.Connect(_handle, socketAddress.Buffer, socketAddress.Size);
        }
        catch (Exception ex)
        {
            if (SocketsTelemetry.Log.IsEnabled())
            {
                SocketsTelemetry.Log.AfterConnect(SocketError.NotSocket, ex.Message);
            }
            throw;
        }
        if (socketError != 0)
        {
            UpdateConnectSocketErrorForDisposed(ref socketError);
            SocketException ex2 = System.Net.Internals.SocketExceptionFactory.CreateSocketException((int)socketError, endPointSnapshot);
            UpdateStatusAfterSocketError(ex2);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex2, "DoConnect");
            }
            if (SocketsTelemetry.Log.IsEnabled())
            {
                SocketsTelemetry.Log.AfterConnect(socketError);
            }
            throw ex2;
        }
        if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.AfterConnect(SocketError.Success);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"connection to:{endPointSnapshot}", "DoConnect");
        }
        _pendingConnectRightEndPoint = endPointSnapshot;
        _nonBlockingConnectInProgress = false;
        SetToConnected();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Connected(this, LocalEndPoint, RemoteEndPoint);
        }
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._nonBlockingConnectInProgress, System.Net.Sockets.Socket._pendingConnectRightEndPoint, System.Net.Sockets.SocketPal.Connect(), System.Net.NetEventSource.Connected(), System.Net.Internals.SocketExceptionFactory.CreateSocketException(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.Sockets.Socket.LocalEndPoint, System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.Net.Sockets.Socket.RemoteEndPoint, System.Net.Sockets.Socket.SetToConnected(), System.Net.Sockets.Socket.UpdateConnectSocketErrorForDisposed(), and System.Net.Sockets.Socket.UpdateStatusAfterSocketError().
Referenced by System.Net.Sockets.Socket.Connect().