Terraria: System.Net.NetworkInformation.Ping.CheckStart
CheckStart()
void System.Net.NetworkInformation.Ping.CheckStart () inline private
Definition at line 110 of file Ping.cs.
    {
        int status;
        lock (_lockObject)
        {
            status = _status;
            if (status == 0)
            {
                _canceled = false;
                _status = 1;
                _lockObject.Reset();
                return;
            }
        }
        if (status == 1)
        {
            throw new InvalidOperationException(System.SR.net_inasync);
        }
        throw new ObjectDisposedException(GetType().FullName);
    }
References System.Net.NetworkInformation.Ping._canceled, System.Net.NetworkInformation.Ping._lockObject, System.Net.NetworkInformation.Ping._status, System.FullName, System.SR.net_inasync, and System.Threading.ManualResetEventSlim.Reset().
Referenced by System.Net.NetworkInformation.Ping.GetAddressAndSend(), System.Net.NetworkInformation.Ping.GetAddressAndSendAsync(), System.Net.NetworkInformation.Ping.Send(), and System.Net.NetworkInformation.Ping.SendPingAsyncInternal().