Terraria: System.Net.Sockets.Socket.Receive
Receive() [11/11]
int System.Net.Sockets.Socket.Receive (Span< byte > buffer, SocketFlags socketFlags, out SocketError errorCode) inline
Definition at line 1797 of file Socket.cs.
    {
        ThrowIfDisposed();
        ValidateBlockingMode();
        errorCode = SocketPal.Receive(_handle, buffer, socketFlags, out var bytesTransferred);
        UpdateReceiveSocketErrorForDisposed(ref errorCode, bytesTransferred);
        if (errorCode != 0)
        {
            UpdateStatusAfterSocketError(errorCode);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, new SocketException((int)errorCode), "Receive");
            }
            return 0;
        }
        if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.BytesReceived(bytesTransferred);
            if (SocketType == SocketType.Dgram)
            {
                SocketsTelemetry.Log.DatagramReceived();
            }
        }
        return bytesTransferred;
    }
References System.Net.Sockets.Socket._handle, System.buffer, System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.Net.Sockets.SocketPal.Receive(), System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.UpdateReceiveSocketErrorForDisposed(), System.Net.Sockets.Socket.UpdateStatusAfterSocketError(), and System.Net.Sockets.Socket.ValidateBlockingMode().