Terraria: System.Net.Sockets.Socket.ValidateBufferArguments
ValidateBufferArguments()
static void System.Net.Sockets.Socket.ValidateBufferArguments (byte[] buffer, int offset, int size) inline static private
Definition at line 4250 of file Socket.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if ((uint)offset > (uint)buffer.Length)
        {
            throw new ArgumentOutOfRangeException("offset");
        }
        if ((uint)size > (uint)(buffer.Length - offset))
        {
            throw new ArgumentOutOfRangeException("size");
        }
    }
References System.buffer, and System.offset.
Referenced by System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceiveFrom(), System.Net.Sockets.Socket.BeginReceiveMessageFrom(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSend(), System.Net.Sockets.Socket.BeginSendTo(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.Send(), and System.Net.Sockets.Socket.SendTo().