Terraria: System.Net.Sockets.Socket.SetSocketOption
SetSocketOption() [3/5]
void System.Net.Sockets.Socket.SetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, int optionValue) inline
Definition at line 2143 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"optionLevel:{optionLevel} optionName:{optionName} optionValue:{optionValue}", "SetSocketOption");
        }
        SetSocketOption(optionLevel, optionName, optionValue, silent: false);
    }
References System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Sockets.Socket.SetSocketOption(), and System.Net.Sockets.Socket.ThrowIfDisposed().
Referenced by System.Net.Sockets.UdpClient.CheckForBroadcast(), System.Net.Sockets.UdpClient.DropMulticastGroup(), System.Net.Sockets.UdpClient.DropMulticastGroup(), System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.UdpClient.JoinMulticastGroup(), System.Net.Sockets.Socket.SetReceivingPacketInformation(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), and System.Net.Sockets.NetworkStream.SetSocketTimeoutOption().