Terraria: System.Net.Sockets.Socket.LoadSocketTypeFromHandle
LoadSocketTypeFromHandle()
unsafe void System.Net.Sockets.Socket.LoadSocketTypeFromHandle (SafeSocketHandle handle, out AddressFamily addressFamily, out SocketType socketType, out ProtocolType protocolType, out bool blocking, out bool isListening, out bool isSocket) inline private
Definition at line 4413 of file Socket.cs.
    {
        global::Interop.Winsock.EnsureInitialized();
        global::Interop.Winsock.WSAPROTOCOL_INFOW wSAPROTOCOL_INFOW = default(global::Interop.Winsock.WSAPROTOCOL_INFOW);
        int optionLength = sizeof(global::Interop.Winsock.WSAPROTOCOL_INFOW);
        if (global::Interop.Winsock.getsockopt(handle, SocketOptionLevel.Socket, (SocketOptionName)8197, (byte*)(&wSAPROTOCOL_INFOW), ref optionLength) == SocketError.SocketError)
        {
            throw new SocketException((int)SocketPal.GetLastSocketError());
        }
        addressFamily = wSAPROTOCOL_INFOW.iAddressFamily;
        socketType = wSAPROTOCOL_INFOW.iSocketType;
        protocolType = wSAPROTOCOL_INFOW.iProtocol;
        isListening = SocketPal.GetSockOpt(_handle, SocketOptionLevel.Socket, SocketOptionName.AcceptConnection, out var optionValue) == SocketError.Success && optionValue != 0;
        blocking = true;
        isSocket = true;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.SocketPal.GetLastSocketError(), System.Net.Sockets.SocketPal.GetSockOpt(), and System.handle.
Referenced by System.Net.Sockets.Socket.Socket().