Terraria: System.Net.Sockets.Socket.UpdateAcceptSocket
UpdateAcceptSocket()
Socket System.Net.Sockets.Socket.UpdateAcceptSocket (Socket socket, EndPoint remoteEP) inline package
Definition at line 3636 of file Socket.cs.
    {
        socket._addressFamily = _addressFamily;
        socket._socketType = _socketType;
        socket._protocolType = _protocolType;
        socket._remoteEndPoint = remoteEP;
        if (_rightEndPoint is UnixDomainSocketEndPoint { BoundFileName: not null } unixDomainSocketEndPoint)
        {
            socket._rightEndPoint = unixDomainSocketEndPoint.CreateUnboundEndPoint();
        }
        else
        {
            socket._rightEndPoint = _rightEndPoint;
        }
        socket._localEndPoint = ((!IsWildcardEndPoint(_localEndPoint)) ? _localEndPoint : null);
        socket.SetToConnected();
        socket._willBlock = _willBlock;
        socket.InternalSetBlocking(_willBlock);
        return socket;
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._localEndPoint, System.Net.Sockets.Socket._protocolType, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.Socket._socketType, System.Net.Sockets.Socket._willBlock, and System.Net.Sockets.Socket.IsWildcardEndPoint().
Referenced by System.Net.Sockets.Socket.CreateAcceptSocket(), and System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess().