Terraria: System.Net.NetworkInformation.Ping.GetStatusFromCode
GetStatusFromCode()
static IPStatus System.Net.NetworkInformation.Ping.GetStatusFromCode (int statusCode) inline static private
Definition at line 653 of file Ping.cs.
    {
        if (statusCode != 0 && statusCode < 11000)
        {
            throw new Win32Exception(statusCode);
        }
        return (IPStatus)statusCode;
    }
Referenced by System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmp6EchoReply(), System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmpEchoReply(), and System.Net.NetworkInformation.Ping.DoSendPingCore().