Terraria: System.Net.NetworkInformation.Ping.GetAddressAndSend
GetAddressAndSend()
PingReply System.Net.NetworkInformation.Ping.GetAddressAndSend (string hostNameOrAddress, int timeout, byte[] buffer, PingOptions options) inline private
Definition at line 374 of file Ping.cs.
    {
        CheckStart();
        try
        {
            IPAddress[] hostAddresses = Dns.GetHostAddresses(hostNameOrAddress);
            return SendPingCore(hostAddresses[0], buffer, timeout, options);
        }
        catch (Exception innerException)
        {
            throw new PingException(System.SR.net_ping, innerException);
        }
        finally
        {
            Finish();
        }
    }
References System.buffer, System.Net.NetworkInformation.Ping.CheckStart(), System.Net.NetworkInformation.Ping.Finish(), System.Net.Dns.GetHostAddresses(), System.SR.net_ping, System.options, System.Net.NetworkInformation.Ping.SendPingCore(), and System.timeout.
Referenced by System.Net.NetworkInformation.Ping.Send().