Terraria: System.Net.NetworkInformation.Ping.RegisterWaitHandle
RegisterWaitHandle()
void System.Net.NetworkInformation.Ping.RegisterWaitHandle () inline private
Definition at line 504 of file Ping.cs.
    {
        if (_pingEvent == null)
        {
            _pingEvent = new ManualResetEvent(initialState: false);
        }
        else
        {
            _pingEvent.Reset();
        }
        _registeredWait = ThreadPool.RegisterWaitForSingleObject(_pingEvent, delegate(object state, bool _)
        {
            ((Ping)state).PingCallback();
        }, this, -1, executeOnlyOnce: true);
    }
References System.Net.NetworkInformation.Ping.Ping(), System.Net.NetworkInformation.Ping._pingEvent, System.Net.NetworkInformation.Ping._registeredWait, System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.EventWaitHandle.Reset(), and System.state.
Referenced by System.Net.NetworkInformation.Ping.DoSendPingCore().