Terraria: System.Net.Sockets.Socket.ConnectAsync
ConnectAsync() [6/11]
ValueTask System.Net.Sockets.Socket.ConnectAsync (IPAddress[] addresses, int port, CancellationToken cancellationToken) inline
Definition at line 3958 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (addresses == null)
        {
            throw new ArgumentNullException("addresses");
        }
        if (addresses.Length == 0)
        {
            throw new ArgumentException(System.SR.net_invalidAddressList, "addresses");
        }
        if (!System.Net.TcpValidationHelpers.ValidatePortNumber(port))
        {
            throw new ArgumentOutOfRangeException("port");
        }
        if (_isListening)
        {
            throw new InvalidOperationException(System.SR.net_sockets_mustnotlisten);
        }
        if (_isConnected)
        {
            throw new SocketException(10056);
        }
        return Core(addresses, port, cancellationToken);
        async ValueTask Core(IPAddress[] addresses, int port, CancellationToken cancellationToken)
        {
            Exception source = null;
            IPEndPoint endPoint = null;
            foreach (IPAddress address in addresses)
            {
                try
                {
                    if (endPoint == null)
                    {
                        endPoint = new IPEndPoint(address, port);
                    }
                    else
                    {
                        endPoint.Address = address;
                    }
                    await ConnectAsync(endPoint, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    return;
                }
                catch (Exception ex) when (!(ex is OperationCanceledException))
                {
                    source = ex;
                }
            }
            ExceptionDispatchInfo.Throw(source);
        }
    }
References System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket._isListening, System.cancellationToken, System.Net.Sockets.Socket.ConnectAsync(), System.SR.net_invalidAddressList, System.SR.net_sockets_mustnotlisten, System.source, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(), System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.TcpValidationHelpers.ValidatePortNumber().