Terraria: System.Net.Sockets.Socket.InternalShutdown
InternalShutdown()
void System.Net.Sockets.Socket.InternalShutdown (SocketShutdown how) inline package
Definition at line 3435 of file Socket.cs.
    {
        if (Disposed || _handle.IsInvalid)
        {
            return;
        }
        try
        {
            SocketPal.Shutdown(_handle, _isConnected, _isDisconnected, how);
        }
        catch (ObjectDisposedException)
        {
        }
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket._isDisconnected, System.Net.Sockets.Socket.Disposed, System.Net.Sockets.SafeSocketHandle.IsInvalid, and System.Net.Sockets.SocketPal.Shutdown().
Referenced by System.Net.Sockets.NetworkStream.Dispose(), System.Net.Sockets.TcpClient.Dispose(), and System.Net.Sockets.UdpClient.Dispose().