Terraria: System.Net.Sockets.Socket.WildcardBindForConnectIfNecessary
WildcardBindForConnectIfNecessary()
void System.Net.Sockets.Socket.WildcardBindForConnectIfNecessary (AddressFamily addressFamily) inline private
Definition at line 2938 of file Socket.cs.
    {
        if (_rightEndPoint == null)
        {
            CachedSerializedEndPoint cachedSerializedEndPoint;
            switch (addressFamily)
            {
            default:
                return;
            case AddressFamily.InterNetwork:
                cachedSerializedEndPoint = (IsDualMode ? (s_cachedMappedAnyV6EndPoint ?? (s_cachedMappedAnyV6EndPoint = new CachedSerializedEndPoint(s_IPAddressAnyMapToIPv6))) : (s_cachedAnyEndPoint ?? (s_cachedAnyEndPoint = new CachedSerializedEndPoint(IPAddress.Any))));
                break;
            case AddressFamily.InterNetworkV6:
                cachedSerializedEndPoint = s_cachedAnyV6EndPoint ?? (s_cachedAnyV6EndPoint = new CachedSerializedEndPoint(IPAddress.IPv6Any));
                break;
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, cachedSerializedEndPoint.IPEndPoint, "WildcardBindForConnectIfNecessary");
            }
            if (_socketType == SocketType.Stream && _protocolType == ProtocolType.Tcp)
            {
                EnableReuseUnicastPort();
            }
            DoBind(cachedSerializedEndPoint.IPEndPoint, cachedSerializedEndPoint.SocketAddress);
        }
    }
References System.Net.Sockets.Socket._protocolType, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.Socket._socketType, System.Net.IPAddress.Any, System.Net.Sockets.Socket.DoBind(), System.Net.Sockets.Socket.EnableReuseUnicastPort(), System.Net.NetEventSource.Info(), System.Net.IPAddress.IPv6Any, System.Net.Sockets.Socket.IsDualMode, System.Net.NetEventSource.Log, System.Net.Sockets.Socket.s_cachedAnyEndPoint, System.Net.Sockets.Socket.s_cachedAnyV6EndPoint, System.Net.Sockets.Socket.s_cachedMappedAnyV6EndPoint, and System.Net.Sockets.Socket.s_IPAddressAnyMapToIPv6.
Referenced by System.Net.Sockets.Socket.ConnectAsync().