Terraria: System.Net.Sockets.Socket.SendFile
SendFile() [3/3]
void System.Net.Sockets.Socket.SendFile (string? fileName, ReadOnlySpan< byte > preBuffer, ReadOnlySpan< byte > postBuffer, TransmitFileOptions flags) inline
Definition at line 1614 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (!Connected)
        {
            throw new NotSupportedException(System.SR.net_notconnected);
        }
        ValidateBlockingMode();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"::SendFile() SRC:{LocalEndPoint} DST:{RemoteEndPoint} fileName:{fileName}", "SendFile");
        }
        SendFileInternal(fileName, preBuffer, postBuffer, flags);
    }
References System.Net.Sockets.Socket.Connected, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_notconnected, System.Net.Sockets.Socket.SendFileInternal(), System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.Sockets.Socket.ValidateBlockingMode().