Terraria: System.Net.Sockets.Socket.SendTo
SendTo() [6/6]
int System.Net.Sockets.Socket.SendTo (ReadOnlySpan< byte > buffer, SocketFlags socketFlags, EndPoint remoteEP) inline
Definition at line 1689 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (remoteEP == null)
        {
            throw new ArgumentNullException("remoteEP");
        }
        ValidateBlockingMode();
        System.Net.Internals.SocketAddress socketAddress = Serialize(ref remoteEP);
        int bytesTransferred;
        SocketError socketError = SocketPal.SendTo(_handle, buffer, socketFlags, socketAddress.Buffer, socketAddress.Size, out bytesTransferred);
        if (socketError != 0)
        {
            UpdateSendSocketErrorForDisposed(ref socketError);
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "SendTo");
        }
        else if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.BytesSent(bytesTransferred);
            if (SocketType == SocketType.Dgram)
            {
                SocketsTelemetry.Log.DatagramSent();
            }
        }
        if (_rightEndPoint == null)
        {
            _rightEndPoint = remoteEP;
        }
        return bytesTransferred;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._rightEndPoint, System.Net.Internals.SocketAddress.Buffer, System.buffer, System.Net.Sockets.SocketsTelemetry.Log, System.Net.Sockets.SocketPal.SendTo(), System.Net.Sockets.Socket.Serialize(), System.Net.Internals.SocketAddress.Size, System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.UpdateSendSocketErrorForDisposed(), System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(), and System.Net.Sockets.Socket.ValidateBlockingMode().