Terraria: System.Net.NetworkInformation.Ping.PingCallback
PingCallback()
void System.Net.NetworkInformation.Ping.PingCallback () inline private
Definition at line 597 of file Ping.cs.
    {
        TaskCompletionSource<PingReply> taskCompletionSource = _taskCompletionSource;
        _taskCompletionSource = null;
        PingReply pingReply = null;
        Exception exception = null;
        bool flag = false;
        try
        {
            lock (_lockObject)
            {
                flag = _canceled;
                pingReply = CreatePingReply();
            }
        }
        catch (Exception innerException)
        {
            exception = new PingException(System.SR.net_ping, innerException);
        }
        finally
        {
            Cleanup(isAsync: true);
        }
        if (flag)
        {
            taskCompletionSource.SetCanceled();
        }
        else if (pingReply != null)
        {
            taskCompletionSource.SetResult(pingReply);
        }
        else
        {
            taskCompletionSource.SetException(exception);
        }
    }
References System.Net.NetworkInformation.Ping._canceled, System.Net.NetworkInformation.Ping._lockObject, System.Net.NetworkInformation.Ping._taskCompletionSource, System.Net.NetworkInformation.Ping.Cleanup(), System.Net.NetworkInformation.Ping.CreatePingReply(), System.exception, System.SR.net_ping, System.Threading.Tasks.TaskCompletionSource< TResult >.SetCanceled(), System.Threading.Tasks.TaskCompletionSource< TResult >.SetException(), and System.Threading.Tasks.TaskCompletionSource< TResult >.SetResult().