Terraria: System.Net.Sockets.Socket.ReceiveAsync
ReceiveAsync() [6/7]
bool System.Net.Sockets.Socket.ReceiveAsync (SocketAsyncEventArgs e) inline
Definition at line 3001 of file Socket.cs.
    {
        return ReceiveAsync(e, default(CancellationToken));
    }
References System.Net.Sockets.Socket.ReceiveAsync().
Referenced by System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.Socket.BeginReceive(), System.Net.Sockets.NetworkStream.ReadAsync(), System.Net.Sockets.NetworkStream.ReadAsync(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveAsync(), System.Net.Sockets.Socket.ReceiveAsync(), and System.Net.Sockets.Socket.ReceiveAsync().