Terraria: System.Net.Sockets.Socket.SetSocketOption
SetSocketOption() [2/5]
void System.Net.Sockets.Socket.SetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, byte[] optionValue) inline
Definition at line 2153 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"optionLevel:{optionLevel} optionName:{optionName} optionValue:{optionValue}", "SetSocketOption");
        }
        SocketError socketError = SocketPal.SetSockOpt(_handle, optionLevel, optionName, optionValue);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"SetSockOpt returns errorCode:{socketError}", "SetSocketOption");
        }
        if (socketError != 0)
        {
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "SetSocketOption");
        }
    }
References System.Net.Sockets.Socket._handle, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Sockets.SocketPal.SetSockOpt(), System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException().