Terraria: System.Net.Sockets.Socket.SendTo
SendTo() [2/6]
int System.Net.Sockets.Socket.SendTo (byte[] buffer, int offset, int size, SocketFlags socketFlags, EndPoint remoteEP) inline
Definition at line 1629 of file Socket.cs.
    {
        ThrowIfDisposed();
        ValidateBufferArguments(buffer, offset, size);
        if (remoteEP == null)
        {
            throw new ArgumentNullException("remoteEP");
        }
        ValidateBlockingMode();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"SRC:{LocalEndPoint} size:{size} remoteEP:{remoteEP}", "SendTo");
        }
        System.Net.Internals.SocketAddress socketAddress = Serialize(ref remoteEP);
        int bytesTransferred;
        SocketError socketError = SocketPal.SendTo(_handle, buffer, offset, size, socketFlags, socketAddress.Buffer, socketAddress.Size, out bytesTransferred);
        if (socketError != 0)
        {
            UpdateSendSocketErrorForDisposed(ref socketError);
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "SendTo");
        }
        else if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.BytesSent(bytesTransferred);
            if (SocketType == SocketType.Dgram)
            {
                SocketsTelemetry.Log.DatagramSent();
            }
        }
        if (_rightEndPoint == null)
        {
            _rightEndPoint = remoteEP;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.DumpBuffer(this, buffer, offset, size, "SendTo");
        }
        return bytesTransferred;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._rightEndPoint, System.Net.Internals.SocketAddress.Buffer, System.buffer, System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.offset, System.Net.Sockets.SocketPal.SendTo(), System.Net.Sockets.Socket.Serialize(), System.Net.Internals.SocketAddress.Size, System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.UpdateSendSocketErrorForDisposed(), System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(), System.Net.Sockets.Socket.ValidateBlockingMode(), and System.Net.Sockets.Socket.ValidateBufferArguments().