Terraria: System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException
UpdateStatusAfterSocketErrorAndThrowException()
void System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException (SocketError error, [CallerMemberName] string callerName = null) inline private
Definition at line 3715 of file Socket.cs.
    {
        SocketException ex = new SocketException((int)error);
        UpdateStatusAfterSocketError(ex);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Error(this, ex, callerName);
        }
        throw ex;
    }
References System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, and System.Net.Sockets.Socket.UpdateStatusAfterSocketError().
Referenced by System.Net.Sockets.Socket.Accept(), System.Net.Sockets.Socket.Disconnect(), System.Net.Sockets.Socket.DoBind(), System.Net.Sockets.Socket.GetIPv6MulticastOpt(), System.Net.Sockets.Socket.GetLingerOpt(), System.Net.Sockets.Socket.GetMulticastOpt(), System.Net.Sockets.Socket.GetRawSocketOption(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.IOControl(), System.Net.Sockets.Socket.Listen(), System.Net.Sockets.Socket.Poll(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.SendFileInternal(), System.Net.Sockets.Socket.SendTo(), System.Net.Sockets.Socket.SendTo(), System.Net.Sockets.Socket.SetIPv6MulticastOption(), System.Net.Sockets.Socket.SetLingerOption(), System.Net.Sockets.Socket.SetMulticastOption(), System.Net.Sockets.Socket.SetRawSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), and System.Net.Sockets.Socket.Shutdown().