Terraria: System.Net.NetworkInformation.Ping.InternalDispose
InternalDispose()
void System.Net.NetworkInformation.Ping.InternalDispose () inline private
Definition at line 149 of file Ping.cs.
    {
        _disposeRequested = true;
        lock (_lockObject)
        {
            if (_status != 0)
            {
                return;
            }
            _status = 2;
        }
        InternalDisposeCore();
    }
References System.Net.NetworkInformation.Ping._disposeRequested, System.Net.NetworkInformation.Ping._lockObject, System.Net.NetworkInformation.Ping._status, and System.Net.NetworkInformation.Ping.InternalDisposeCore().
Referenced by System.Net.NetworkInformation.Ping.Dispose(), and System.Net.NetworkInformation.Ping.Finish().