Terraria: System.Net.Sockets.Socket.SetSocketOption
SetSocketOption() [4/5]
void System.Net.Sockets.Socket.SetSocketOption (SocketOptionLevel optionLevel, SocketOptionName optionName, int optionValue, bool silent) inline package
Definition at line 3471 of file Socket.cs.
    {
        if (silent && (Disposed || _handle.IsInvalid))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "skipping the call", "SetSocketOption");
            }
            return;
        }
        SocketError socketError = SocketError.Success;
        try
        {
            socketError = SocketPal.SetSockOpt(_handle, optionLevel, optionName, optionValue);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, $"SetSockOpt returns errorCode:{socketError}", "SetSocketOption");
            }
        }
        catch
        {
            if (silent && _handle.IsInvalid)
            {
                return;
            }
            throw;
        }
        if (optionName == SocketOptionName.PacketInformation && optionValue == 0 && socketError == SocketError.Success)
        {
            _receivingPacketInformation = false;
        }
        if (!silent && socketError != 0)
        {
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "SetSocketOption");
        }
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._receivingPacketInformation, System.Net.Sockets.Socket.Disposed, System.Net.NetEventSource.Info(), System.Net.Sockets.SafeSocketHandle.IsInvalid, System.Net.NetEventSource.Log, System.Net.Sockets.SocketPal.SetSockOpt(), and System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException().