Terraria: System.Net.Sockets.Socket.ReceiveFrom
ReceiveFrom() [6/6]
int System.Net.Sockets.Socket.ReceiveFrom (Span< byte > buffer, SocketFlags socketFlags, ref EndPoint remoteEP) inline
Definition at line 2067 of file Socket.cs.
    {
        ThrowIfDisposed();
        ValidateReceiveFromEndpointAndState(remoteEP, "remoteEP");
        SocketPal.CheckDualModeReceiveSupport(this);
        ValidateBlockingMode();
        EndPoint remoteEP2 = remoteEP;
        System.Net.Internals.SocketAddress socketAddress = Serialize(ref remoteEP2);
        System.Net.Internals.SocketAddress socketAddress2 = IPEndPointExtensions.Serialize(remoteEP2);
        int bytesTransferred;
        SocketError socketError = SocketPal.ReceiveFrom(_handle, buffer, socketFlags, socketAddress.Buffer, ref socketAddress.InternalSize, out bytesTransferred);
        UpdateReceiveSocketErrorForDisposed(ref socketError, bytesTransferred);
        SocketException ex = null;
        if (socketError != 0)
        {
            ex = new SocketException((int)socketError);
            UpdateStatusAfterSocketError(ex);
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex, "ReceiveFrom");
            }
            if (ex.SocketErrorCode != SocketError.MessageSize)
            {
                throw ex;
            }
        }
        else if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.BytesReceived(bytesTransferred);
            if (SocketType == SocketType.Dgram)
            {
                SocketsTelemetry.Log.DatagramReceived();
            }
        }
        if (!socketAddress2.Equals(socketAddress))
        {
            try
            {
                remoteEP = remoteEP2.Create(socketAddress);
            }
            catch
            {
            }
            if (_rightEndPoint == null)
            {
                _rightEndPoint = remoteEP2;
            }
        }
        if (ex != null)
        {
            throw ex;
        }
        return bytesTransferred;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._rightEndPoint, System.Net.Internals.SocketAddress.Buffer, System.buffer, System.Net.Sockets.SocketPal.CheckDualModeReceiveSupport(), System.Net.NetEventSource.Error(), System.Net.Internals.SocketAddress.InternalSize, System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.Net.Sockets.SocketPal.ReceiveFrom(), System.Net.Sockets.IPEndPointExtensions.Serialize(), System.Net.Sockets.Socket.Serialize(), System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.UpdateReceiveSocketErrorForDisposed(), System.Net.Sockets.Socket.UpdateStatusAfterSocketError(), System.Net.Sockets.Socket.ValidateBlockingMode(), and System.Net.Sockets.Socket.ValidateReceiveFromEndpointAndState().