Terraria: System.Net.Sockets.Socket.AcceptAsync
AcceptAsync() [6/6]
bool System.Net.Sockets.Socket.AcceptAsync (SocketAsyncEventArgs e, CancellationToken cancellationToken) inline private
Definition at line 2779 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (e == null)
        {
            throw new ArgumentNullException("e");
        }
        if (e.HasMultipleBuffers)
        {
            throw new ArgumentException(System.SR.net_multibuffernotsupported, "e");
        }
        if (_rightEndPoint == null)
        {
            throw new InvalidOperationException(System.SR.net_sockets_mustbind);
        }
        if (!_isListening)
        {
            throw new InvalidOperationException(System.SR.net_sockets_mustlisten);
        }
        e.AcceptSocket = GetOrCreateAcceptSocket(e.AcceptSocket, checkDisconnected: true, "AcceptSocket", out var handle);
        if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.AcceptStart(_rightEndPoint);
        }
        e.StartOperationCommon(this, SocketAsyncOperation.Accept);
        e.StartOperationAccept();
        SocketError socketError;
        try
        {
            socketError = e.DoOperationAccept(this, _handle, handle, cancellationToken);
        }
        catch (Exception ex)
        {
            if (SocketsTelemetry.Log.IsEnabled())
            {
                SocketsTelemetry.Log.AfterAccept(SocketError.Interrupted, ex.Message);
            }
            e.Complete();
            throw;
        }
        return socketError == SocketError.IOPending;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isListening, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.SocketAsyncEventArgs.AcceptSocket, System.cancellationToken, System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationAccept(), System.Net.Sockets.Socket.GetOrCreateAcceptSocket(), System.handle, System.Net.Sockets.SocketAsyncEventArgs.HasMultipleBuffers, System.Net.Sockets.SocketsTelemetry.Log, System.SR.net_multibuffernotsupported, System.SR.net_sockets_mustbind, System.SR.net_sockets_mustlisten, System.Net.Sockets.SocketAsyncEventArgs.StartOperationAccept(), System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(), and System.Net.Sockets.Socket.ThrowIfDisposed().