Terraria: System.Net.Sockets.Socket.ReceiveAsync
ReceiveAsync() [7/7]
bool System.Net.Sockets.Socket.ReceiveAsync (SocketAsyncEventArgs e, CancellationToken cancellationToken) inline private
Definition at line 3006 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (e == null)
        {
            throw new ArgumentNullException("e");
        }
        e.StartOperationCommon(this, SocketAsyncOperation.Receive);
        SocketError socketError;
        try
        {
            socketError = e.DoOperationReceive(_handle, cancellationToken);
        }
        catch
        {
            e.Complete();
            throw;
        }
        return socketError == SocketError.IOPending;
    }
References System.Net.Sockets.Socket._handle, System.cancellationToken, System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceive(), System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(), and System.Net.Sockets.Socket.ThrowIfDisposed().