Terraria: System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmp6EchoReply
CreatePingReplyFromIcmp6EchoReply()
static PingReply System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmp6EchoReply (global::Interop::IpHlpApi::Icmp6EchoReply reply, IntPtr dataPtr, int sendSize) inline static private
Definition at line 685 of file Ping.cs.
    {
        IPAddress address = new IPAddress(reply.Address.Address, reply.Address.ScopeID);
        IPStatus statusFromCode = GetStatusFromCode((int)reply.Status);
        long rtt;
        byte[] array;
        if (statusFromCode == IPStatus.Success)
        {
            rtt = reply.RoundTripTime;
            array = new byte[sendSize];
            Marshal.Copy(dataPtr + 36, array, 0, sendSize);
        }
        else
        {
            rtt = 0L;
            array = Array.Empty<byte>();
        }
        return new PingReply(address, null, statusFromCode, rtt, array);
    }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Net.NetworkInformation.Ping.GetStatusFromCode(), and System.L.
Referenced by System.Net.NetworkInformation.Ping.CreatePingReply().