Terraria: System.Net.Sockets.Socket.AcceptAsync
AcceptAsync() [1/6]
Task< Socket > System.Net.Sockets.Socket.AcceptAsync () inline
Definition at line 3876 of file Socket.cs.
    {
        return AcceptAsync((Socket?)null, CancellationToken.None).AsTask();
    }
References System.Net.Sockets.Socket.AcceptAsync(), and System.Threading.CancellationToken.None.
Referenced by System.Net.Sockets.Socket.AcceptAndReceiveHelperAsync(), System.Net.Sockets.Socket.AcceptAsync(), System.Net.Sockets.Socket.AcceptAsync(), System.Net.Sockets.Socket.AcceptAsync(), System.Net.Sockets.Socket.AcceptAsync(), and System.Net.Sockets.Socket.BeginAccept().