Terraria: System.Net.Sockets.Socket.ReceiveAsync
ReceiveAsync() [3/7]
Task< int > System.Net.Sockets.Socket.ReceiveAsync (IList< ArraySegment< byte > > buffers, SocketFlags socketFlags) inline
Definition at line 4067 of file Socket.cs.
    {
        ValidateBuffersList(buffers);
        TaskSocketAsyncEventArgs<int> taskSocketAsyncEventArgs = Interlocked.Exchange(ref _multiBufferReceiveEventArgs, null);
        if (taskSocketAsyncEventArgs == null)
        {
            taskSocketAsyncEventArgs = new TaskSocketAsyncEventArgs<int>();
            taskSocketAsyncEventArgs.Completed += delegate(object s, SocketAsyncEventArgs e)
            {
                CompleteSendReceive((Socket)s, (TaskSocketAsyncEventArgs<int>)e, isReceive: true);
            };
        }
        taskSocketAsyncEventArgs.BufferList = buffers;
        taskSocketAsyncEventArgs.SocketFlags = socketFlags;
        return GetTaskForSendReceive(ReceiveAsync(taskSocketAsyncEventArgs), taskSocketAsyncEventArgs, fromNetworkStream: false, isReceive: true);
    }
References System.Net.Sockets.Socket._multiBufferReceiveEventArgs, System.buffers, System.Net.Sockets.Socket.CompleteSendReceive(), System.Threading.Interlocked.Exchange(), System.Net.Sockets.Socket.GetTaskForSendReceive(), System.Net.Sockets.Socket.ReceiveAsync(), System.s, and System.Net.Sockets.Socket.ValidateBuffersList().