Terraria: System.Net.Sockets.Socket.ReceiveMessageFromAsync
ReceiveMessageFromAsync() [4/4]
bool System.Net.Sockets.Socket.ReceiveMessageFromAsync (SocketAsyncEventArgs e, CancellationToken cancellationToken) inline private
Definition at line 3070 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (e == null)
        {
            throw new ArgumentNullException("e");
        }
        if (e.RemoteEndPoint == null)
        {
            throw new ArgumentException(System.SR.Format(System.SR.InvalidNullArgument, "e.RemoteEndPoint"), "e");
        }
        if (!CanTryAddressFamily(e.RemoteEndPoint.AddressFamily))
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_InvalidEndPointAddressFamily, e.RemoteEndPoint.AddressFamily, _addressFamily), "e");
        }
        SocketPal.CheckDualModeReceiveSupport(this);
        EndPoint remoteEP = e.RemoteEndPoint;
        e._socketAddress = Serialize(ref remoteEP);
        e.RemoteEndPoint = remoteEP;
        SetReceivingPacketInformation();
        e.StartOperationCommon(this, SocketAsyncOperation.ReceiveMessageFrom);
        SocketError socketError;
        try
        {
            socketError = e.DoOperationReceiveMessageFrom(this, _handle, cancellationToken);
        }
        catch
        {
            e.Complete();
            throw;
        }
        return socketError == SocketError.IOPending;
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._handle, System.Net.EndPoint.AddressFamily, System.cancellationToken, System.Net.Sockets.Socket.CanTryAddressFamily(), System.Net.Sockets.SocketPal.CheckDualModeReceiveSupport(), System.Net.Sockets.SocketAsyncEventArgs.Complete(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceiveMessageFrom(), System.SR.Format(), System.SR.InvalidNullArgument, System.SR.net_InvalidEndPointAddressFamily, System.Net.Sockets.SocketAsyncEventArgs.RemoteEndPoint, System.Net.Sockets.Socket.Serialize(), System.Net.Sockets.Socket.SetReceivingPacketInformation(), System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(), and System.Net.Sockets.Socket.ThrowIfDisposed().