Terraria: System.Net.Sockets.Socket.DuplicateAndClose
DuplicateAndClose()
SocketInformation System.Net.Sockets.Socket.DuplicateAndClose (int targetProcessId) inline
Definition at line 4431 of file Socket.cs.
    {
        ThrowIfDisposed();
        SocketInformation socketInformation;
        SocketError socketError = SocketPal.DuplicateSocket(_handle, targetProcessId, out socketInformation);
        if (socketError != 0)
        {
            throw new SocketException((int)socketError);
        }
        socketInformation.SetOption(SocketInformationOptions.Connected, Connected);
        socketInformation.SetOption(SocketInformationOptions.NonBlocking, !Blocking);
        socketInformation.SetOption(SocketInformationOptions.Listening, _isListening);
        Close(-1);
        return socketInformation;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isListening, System.Net.Sockets.Socket.Blocking, System.Net.Sockets.Socket.Close(), System.Net.Sockets.Socket.Connected, System.Net.Sockets.SocketPal.DuplicateSocket(), and System.Net.Sockets.Socket.ThrowIfDisposed().