Terraria: System.Net.Sockets.Socket.BeginReceive
BeginReceive() [2/4]
IAsyncResult? System.Net.Sockets.Socket.BeginReceive (byte[] buffer, int offset, int size, SocketFlags socketFlags, out SocketError errorCode, AsyncCallback? callback, object? state) inline
Definition at line 2538 of file Socket.cs.
    {
        ThrowIfDisposed();
        ValidateBufferArguments(buffer, offset, size);
        Task<int> task = ReceiveAsync(new ArraySegment<byte>(buffer, offset, size), socketFlags, fromNetworkStream: false, default(CancellationToken)).AsTask();
        if (task.IsFaulted || task.IsCanceled)
        {
            errorCode = GetSocketErrorFromFaultedTask(task);
            return null;
        }
        errorCode = SocketError.Success;
        return System.Threading.Tasks.TaskToApm.Begin(task, callback, state);
    }
References System.Threading.Tasks.TaskToApm.Begin(), System.buffer, System.Net.Sockets.Socket.GetSocketErrorFromFaultedTask(), System.offset, System.Net.Sockets.Socket.ReceiveAsync(), System.state, System.task, System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.Sockets.Socket.ValidateBufferArguments().