Terraria: System.Net.Sockets.Socket.DoBind
DoBind()
void System.Net.Sockets.Socket.DoBind (EndPoint endPointSnapshot, System::Net::Internals::SocketAddress socketAddress) inline private
Definition at line 1191 of file Socket.cs.
    {
        IPEndPoint iPEndPoint = endPointSnapshot as IPEndPoint;
        if (!OSSupportsIPv4 && iPEndPoint != null && iPEndPoint.Address.IsIPv4MappedToIPv6)
        {
            UpdateStatusAfterSocketErrorAndThrowException(SocketError.InvalidArgument, "DoBind");
        }
        SocketError socketError = SocketPal.Bind(_handle, _protocolType, socketAddress.Buffer, socketAddress.Size);
        if (socketError != 0)
        {
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "DoBind");
        }
        _rightEndPoint = ((endPointSnapshot is UnixDomainSocketEndPoint unixDomainSocketEndPoint) ? unixDomainSocketEndPoint.CreateBoundEndPoint() : endPointSnapshot);
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._protocolType, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.SocketPal.Bind(), System.Net.Sockets.Socket.OSSupportsIPv4, and System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException().
Referenced by System.Net.Sockets.Socket.Bind(), and System.Net.Sockets.Socket.WildcardBindForConnectIfNecessary().