Terraria: System.Net.Sockets.Socket.BeginSendFile
BeginSendFile() [2/2]
IAsyncResult System.Net.Sockets.Socket.BeginSendFile (string? fileName, byte?[] preBuffer, byte?[] postBuffer, TransmitFileOptions flags, AsyncCallback? callback, object? state) inline
Definition at line 2489 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (!Connected)
        {
            throw new NotSupportedException(System.SR.net_notconnected);
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"::DoBeginSendFile() SRC:{LocalEndPoint} DST:{RemoteEndPoint} fileName:{fileName}", "BeginSendFile");
        }
        return System.Threading.Tasks.TaskToApm.Begin(SendFileAsync(fileName, preBuffer, postBuffer, flags).AsTask(), callback, state);
    }
References System.Threading.Tasks.TaskToApm.Begin(), System.Net.Sockets.Socket.Connected, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.SR.net_notconnected, System.Net.Sockets.Socket.SendFileAsync(), System.state, and System.Net.Sockets.Socket.ThrowIfDisposed().