Terraria: System.Net.Sockets.Socket.GetLingerOpt
GetLingerOpt()
LingerOption System.Net.Sockets.Socket.GetLingerOpt () inline private
Definition at line 3547 of file Socket.cs.
    {
        LingerOption optionValue;
        SocketError lingerOption = SocketPal.GetLingerOption(_handle, out optionValue);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"GetLingerOption returns errorCode:{lingerOption}", "GetLingerOpt");
        }
        if (lingerOption != 0)
        {
            UpdateStatusAfterSocketErrorAndThrowException(lingerOption, "GetLingerOpt");
        }
        return optionValue;
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.SocketPal.GetLingerOption(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, and System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException().
Referenced by System.Net.Sockets.Socket.GetSocketOption().