Terraria: System.Net.NetworkInformation.Ping.CreatePingReply
CreatePingReply()
PingReply System.Net.NetworkInformation.Ping.CreatePingReply () inline private
Definition at line 576 of file Ping.cs.
    {
        SafeLocalAllocHandle replyBuffer = _replyBuffer;
        if (_ipv6)
        {
            global::Interop.IpHlpApi.Icmp6EchoReply reply = Marshal.PtrToStructure<global::Interop.IpHlpApi.Icmp6EchoReply>(replyBuffer.DangerousGetHandle());
            return CreatePingReplyFromIcmp6EchoReply(reply, replyBuffer.DangerousGetHandle(), _sendSize);
        }
        global::Interop.IpHlpApi.IcmpEchoReply reply2 = Marshal.PtrToStructure<global::Interop.IpHlpApi.IcmpEchoReply>(replyBuffer.DangerousGetHandle());
        return CreatePingReplyFromIcmpEchoReply(reply2);
    }
References System.Net.NetworkInformation.Ping._ipv6, System.Net.NetworkInformation.Ping._replyBuffer, System.Net.NetworkInformation.Ping._sendSize, System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmp6EchoReply(), System.Net.NetworkInformation.Ping.CreatePingReplyFromIcmpEchoReply(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), and System.Runtime.InteropServices.Marshal.PtrToStructure().
Referenced by System.Net.NetworkInformation.Ping.DoSendPingCore(), and System.Net.NetworkInformation.Ping.PingCallback().