Terraria: System.Net.Sockets.Socket.Accept
Accept()
Socket System.Net.Sockets.Socket.Accept () inline
Definition at line 1385 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (_rightEndPoint == null)
        {
            throw new InvalidOperationException(System.SR.net_sockets_mustbind);
        }
        if (!_isListening)
        {
            throw new InvalidOperationException(System.SR.net_sockets_mustlisten);
        }
        if (_isDisconnected)
        {
            throw new InvalidOperationException(System.SR.net_sockets_disconnectedAccept);
        }
        ValidateBlockingMode();
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, $"SRC:{LocalEndPoint}", "Accept");
        }
        System.Net.Internals.SocketAddress socketAddress = ((_addressFamily == AddressFamily.InterNetwork || _addressFamily == AddressFamily.InterNetworkV6) ? IPEndPointExtensions.Serialize(_rightEndPoint) : new System.Net.Internals.SocketAddress(_addressFamily, SocketPal.MaximumAddressSize));
        if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.AcceptStart(socketAddress);
        }
        SocketError socketError;
        SafeSocketHandle socket;
        try
        {
            socketError = SocketPal.Accept(_handle, socketAddress.Buffer, ref socketAddress.InternalSize, out socket);
        }
        catch (Exception ex)
        {
            if (SocketsTelemetry.Log.IsEnabled())
            {
                SocketsTelemetry.Log.AfterAccept(SocketError.Interrupted, ex.Message);
            }
            throw;
        }
        if (socketError != 0)
        {
            UpdateAcceptSocketErrorForDisposed(ref socketError);
            if (SocketsTelemetry.Log.IsEnabled())
            {
                SocketsTelemetry.Log.AfterAccept(socketError);
            }
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "Accept");
        }
        if (SocketsTelemetry.Log.IsEnabled())
        {
            SocketsTelemetry.Log.AfterAccept(SocketError.Success);
        }
        Socket socket2 = CreateAcceptSocket(socket, _rightEndPoint.Create(socketAddress));
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Accepted(socket2, socket2.RemoteEndPoint, socket2.LocalEndPoint);
        }
        return socket2;
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._isDisconnected, System.Net.Sockets.Socket._isListening, System.Net.Sockets.Socket._rightEndPoint, System.Net.Sockets.SocketPal.Accept(), System.Net.NetEventSource.Accepted(), System.Net.Internals.SocketAddress.Buffer, System.Net.EndPoint.Create(), System.Net.Sockets.Socket.CreateAcceptSocket(), System.Net.NetEventSource.Info(), System.Net.Internals.SocketAddress.InternalSize, System.Net.NetEventSource.Log, System.Net.Sockets.SocketsTelemetry.Log, System.Net.Sockets.SocketPal.MaximumAddressSize, System.SR.net_sockets_disconnectedAccept, System.SR.net_sockets_mustbind, System.SR.net_sockets_mustlisten, System.Net.Sockets.IPEndPointExtensions.Serialize(), System.Net.Sockets.Socket.ThrowIfDisposed(), System.Net.Sockets.Socket.UpdateAcceptSocketErrorForDisposed(), System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(), and System.Net.Sockets.Socket.ValidateBlockingMode().
Referenced by System.Net.Sockets.TcpListener.AcceptSocket(), System.Net.Sockets.TcpListener.AcceptTcpClient(), and System.Net.FtpControlStream.QueueOrCreateDataConection().