Terraria: System.Net.Sockets.Socket.GetDynamicWinsockMethods
GetDynamicWinsockMethods()
DynamicWinsockMethods System.Net.Sockets.Socket.GetDynamicWinsockMethods () inline private
Definition at line 4447 of file Socket.cs.
    {
        return _dynamicWinsockMethods ?? (_dynamicWinsockMethods = DynamicWinsockMethods.GetMethods(_addressFamily, _socketType, _protocolType));
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._dynamicWinsockMethods, System.Net.Sockets.Socket._protocolType, System.Net.Sockets.Socket._socketType, and System.Net.Sockets.DynamicWinsockMethods.GetMethods().
Referenced by System.Net.Sockets.Socket.AcceptEx(), System.Net.Sockets.Socket.ConnectEx(), System.Net.Sockets.Socket.DisconnectEx(), System.Net.Sockets.Socket.DisconnectExBlocking(), System.Net.Sockets.Socket.GetAcceptExSockaddrs(), System.Net.Sockets.Socket.TransmitPackets(), System.Net.Sockets.Socket.WSARecvMsg(), and System.Net.Sockets.Socket.WSARecvMsgBlocking().