Terraria: System.Net.NetworkInformation.Ping.UnregisterWaitHandle
UnregisterWaitHandle()
void System.Net.NetworkInformation.Ping.UnregisterWaitHandle () inline private
Definition at line 520 of file Ping.cs.
    {
        lock (_lockObject)
        {
            if (_registeredWait != null)
            {
                _registeredWait.Unregister(null);
                _registeredWait = null;
            }
        }
    }
References System.Net.NetworkInformation.Ping._lockObject, System.Net.NetworkInformation.Ping._registeredWait, and System.Threading.RegisteredWaitHandle.Unregister().
Referenced by System.Net.NetworkInformation.Ping.Cleanup(), and System.Net.NetworkInformation.Ping.InternalDisposeCore().