Terraria: System.Net.Sockets.Socket.Connect
Connect() [3/4]
void System.Net.Sockets.Socket.Connect (IPAddress[] addresses, int port) inline
Definition at line 1294 of file Socket.cs.
    {
        ThrowIfDisposed();
        if (addresses == null)
        {
            throw new ArgumentNullException("addresses");
        }
        if (addresses.Length == 0)
        {
            throw new ArgumentException(System.SR.net_sockets_invalid_ipaddress_length, "addresses");
        }
        if (!System.Net.TcpValidationHelpers.ValidatePortNumber(port))
        {
            throw new ArgumentOutOfRangeException("port");
        }
        if (_addressFamily != AddressFamily.InterNetwork && _addressFamily != AddressFamily.InterNetworkV6)
        {
            throw new NotSupportedException(System.SR.net_invalidversion);
        }
        if (_isConnected)
        {
            throw new SocketException(10056);
        }
        ExceptionDispatchInfo exceptionDispatchInfo = null;
        foreach (IPAddress iPAddress in addresses)
        {
            if (CanTryAddressFamily(iPAddress.AddressFamily))
            {
                try
                {
                    Connect(new IPEndPoint(iPAddress, port));
                    exceptionDispatchInfo = null;
                }
                catch (Exception ex) when (!ExceptionCheck.IsFatal(ex))
                {
                    exceptionDispatchInfo = ExceptionDispatchInfo.Capture(ex);
                    continue;
                }
                break;
            }
        }
        exceptionDispatchInfo?.Throw();
        if (!Connected)
        {
            throw new ArgumentException(System.SR.net_invalidAddressList, "addresses");
        }
    }
References System.Net.Sockets.Socket._addressFamily, System.Net.Sockets.Socket._isConnected, System.Net.Sockets.Socket.CanTryAddressFamily(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Net.Sockets.Connect, System.Net.Sockets.Socket.Connected, System.Net.ExceptionCheck.IsFatal(), System.SR.net_invalidAddressList, System.SR.net_invalidversion, System.SR.net_sockets_invalid_ipaddress_length, System.Net.Sockets.Socket.ThrowIfDisposed(), and System.Net.TcpValidationHelpers.ValidatePortNumber().