Terraria: System.Net.Sockets.Socket.SendFileInternal
SendFileInternal()
void System.Net.Sockets.Socket.SendFileInternal (string fileName, ReadOnlySpan< byte > preBuffer, ReadOnlySpan< byte > postBuffer, TransmitFileOptions flags) inline private
Definition at line 4580 of file Socket.cs.
    {
        SocketError socketError;
        using (SafeFileHandle fileHandle = OpenFileHandle(fileName))
        {
            socketError = SocketPal.SendFile(_handle, fileHandle, preBuffer, postBuffer, flags);
        }
        if (socketError != 0)
        {
            UpdateSendSocketErrorForDisposed(ref socketError);
            UpdateStatusAfterSocketErrorAndThrowException(socketError, "SendFileInternal");
        }
        if ((flags & (TransmitFileOptions.Disconnect | TransmitFileOptions.ReuseSocket)) != 0)
        {
            SetToDisconnected();
            _remoteEndPoint = null;
        }
    }
References System.Net.Sockets.Socket._handle, System.Net.Sockets.Socket._remoteEndPoint, System.Net.Sockets.Socket.OpenFileHandle(), System.Net.Sockets.SocketPal.SendFile(), System.Net.Sockets.Socket.SetToDisconnected(), System.Net.Sockets.Socket.UpdateSendSocketErrorForDisposed(), and System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException().
Referenced by System.Net.Sockets.Socket.SendFile().