Terraria: System.Reflection.Metadata.Ecma335.ParametersEncoder.StartVarArgs
StartVarArgs()
ParametersEncoder System.Reflection.Metadata.Ecma335.ParametersEncoder.StartVarArgs () inline
Definition at line 20 of file ParametersEncoder.cs.
    {
        if (!HasVarArgs)
        {
            Throw.SignatureNotVarArg();
        }
        Builder.WriteByte(65);
        return new ParametersEncoder(Builder);
    }
References System.Reflection.Metadata.Ecma335.ParametersEncoder.ParametersEncoder(), System.Reflection.Metadata.Ecma335.ParametersEncoder.Builder, System.Reflection.Metadata.Ecma335.ParametersEncoder.HasVarArgs, System.Reflection.Throw.SignatureNotVarArg(), and System.Reflection.Metadata.BlobBuilder.WriteByte().