Terraria: AmbientSky.SlimeBalloonGroupSkyEntity.CreateGroup
CreateGroup()
static List<SlimeBalloonGroupSkyEntity> AmbientSky.SlimeBalloonGroupSkyEntity.CreateGroup (Player player, FastRandom random) inline static
         {
             List<SlimeBalloonGroupSkyEntity> list = new List<SlimeBalloonGroupSkyEntity>();
             int num = 100;
             int num2 = random.Next(5, 10);
             VirtualCamera virtualCamera = new VirtualCamera(player);
             SpriteEffects spriteEffects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             Vector2 vector = default(Vector2);
             if (spriteEffects == SpriteEffects.FlipHorizontally)
             {
                 vector.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
             }
             else
             {
                 vector.X = virtualCamera.Position.X - (float)num;
             }
             vector.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 1600f - 2400f) + 2400f;
             float num3 = random.NextFloat() * 3f + 3f;
             int num4 = random.Next(80, 121) * 60;
             Vector2 vector2 = new Vector2(random.NextFloat() * 0.1f + 0.1f, random.NextFloat() * 0.1f + 0.1f);
             Vector2 targetOffset = new Vector2(random.NextFloat() * 2f - 1f, random.NextFloat() * 2f - 1f) * 150f;
             for (int i = 0; i < num2; i++)
             {
                 SlimeBalloonGroupSkyEntity slimeBalloonGroupSkyEntity = new SlimeBalloonGroupSkyEntity(player, random);
                 slimeBalloonGroupSkyEntity.Depth = num3 + random.NextFloat() * 0.5f;
                 slimeBalloonGroupSkyEntity.Position = vector + new Vector2(random.NextFloat() * 20f - 10f, random.NextFloat() * 3f) * 80f;
                 slimeBalloonGroupSkyEntity.Effects = spriteEffects;
                 slimeBalloonGroupSkyEntity.SetPositionInWorldBasedOnScreenSpace(slimeBalloonGroupSkyEntity.Position);
                 slimeBalloonGroupSkyEntity.LifeTime = num4 + random.Next(301);
                 slimeBalloonGroupSkyEntity.SetMagnetization(vector2 * (random.NextFloat() * 0.2f) * 0.05f, targetOffset);
                 list.Add(slimeBalloonGroupSkyEntity);
             }
             return list;
         }
References AmbientSky.SlimeBalloonGroupSkyEntity.SlimeBalloonGroupSkyEntity(), AmbientSky.SkyEntity.Depth, AmbientSky.SkyEntity.Effects, AmbientSky.FadingSkyEntity.LifeTime, FastRandom.Next(), FastRandom.NextFloat(), AmbientSky.SkyEntity.Position, VirtualCamera.Position, AmbientSky.SlimeBalloonGroupSkyEntity.SetMagnetization(), AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), VirtualCamera.Size, Main.WindForVisuals, and Main.worldSurface.
Referenced by AmbientSky.Spawn().