Terraria: Terraria.Initializers.ChromaInitializer.AddDevices
AddDevices()
static void Terraria.Initializers.ChromaInitializer.AddDevices () inline static private
Definition at line 584 of file ChromaInitializer.cs.
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Expected O, but got Unknown
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Expected O, but got Unknown
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Expected O, but got Unknown
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Expected O, but got Unknown
        _engine.AddDeviceGroup("Razer", (RgbDeviceGroup)new RazerDeviceGroup(_razerColorProfile));
        _engine.AddDeviceGroup("Corsair", (RgbDeviceGroup)new CorsairDeviceGroup(_corsairColorProfile));
        _engine.AddDeviceGroup("Logitech", (RgbDeviceGroup)new LogitechDeviceGroup(_logitechColorProfile));
        _engine.AddDeviceGroup("SteelSeries", (RgbDeviceGroup)new SteelSeriesDeviceGroup(_steelSeriesColorProfile, "TERRARIA", "Terraria", IconColor.Green));
        _engine.FrameTimeInSeconds = 1f / _rgbUpdateRate;
        if (_useRazer)
        {
            _engine.EnableDeviceGroup("Razer");
        }
        if (_useCorsair)
        {
            _engine.EnableDeviceGroup("Corsair");
        }
        if (_useLogitech)
        {
            _engine.EnableDeviceGroup("Logitech");
        }
        if (_useSteelSeries)
        {
            _engine.EnableDeviceGroup("SteelSeries");
        }
        LoadSpecialRulesForDevices();
        AppDomain.CurrentDomain.ProcessExit += OnProcessExit;
        if (Platform.IsWindows)
        {
            Application.ApplicationExit += OnProcessExit;
        }
    }
References Terraria.Initializers.ChromaInitializer._corsairColorProfile, Terraria.Initializers.ChromaInitializer._engine, Terraria.Initializers.ChromaInitializer._logitechColorProfile, Terraria.Initializers.ChromaInitializer._razerColorProfile, Terraria.Initializers.ChromaInitializer._rgbUpdateRate, Terraria.Initializers.ChromaInitializer._steelSeriesColorProfile, Terraria.Initializers.ChromaInitializer._useCorsair, Terraria.Initializers.ChromaInitializer._useLogitech, Terraria.Initializers.ChromaInitializer._useRazer, Terraria.Initializers.ChromaInitializer._useSteelSeries, ReLogic.Peripherals.RGB.ChromaEngine.AddDeviceGroup(), ReLogic.Peripherals.RGB.ChromaEngine.EnableDeviceGroup(), ReLogic.OS.Platform.IsWindows, Terraria.Initializers.ChromaInitializer.LoadSpecialRulesForDevices(), and Terraria.Initializers.ChromaInitializer.OnProcessExit().