Terraria: Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_GameSense_Keyboard
LoadSpecialRulesFor_GameSense_Keyboard()
static void Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_GameSense_Keyboard (List< Bind_Event > eventsToBind) inline static private
Definition at line 724 of file ChromaInitializer.cs.
    {
        Dictionary<string, byte> xnaKeyNamesToSteelSeriesKeyIndex = HIDCodes.XnaKeyNamesToSteelSeriesKeyIndex;
        Color white = Color.White;
        foreach (KeyValuePair<string, List<string>> item3 in PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus)
        {
            string key = item3.Key;
            List<string> value = item3.Value;
            List<byte> list = new List<byte>();
            foreach (string item4 in value)
            {
                if (xnaKeyNamesToSteelSeriesKeyIndex.TryGetValue(item4, out var value2))
                {
                    list.Add(value2);
                }
            }
            RGBPerkeyZoneCustom deviceZone = new RGBPerkeyZoneCustom(list.ToArray());
            new ColorStatic
            {
                red = white.R,
                green = white.G,
                blue = white.B
            };
            Bind_Event item = new Bind_Event("TERRARIA", "KEY_" + key.ToUpper(), 0, 10, EventIconId.Default, new AbstractHandler[1]
            {
                new ContextColorEventHandlerType
                {
                    ContextFrameKey = key,
                    DeviceZone = deviceZone
                }
            });
            eventsToBind.Add(item);
        }
        Bind_Event item2 = new Bind_Event("TERRARIA", "DO_RAINBOWS", 0, 10, EventIconId.Default, new AbstractHandler[1]
        {
            new PartialBitmapEventHandlerType
            {
                EventsToExclude = eventsToBind.Select((Bind_Event x) => x.eventName).ToArray()
            }
        });
        eventsToBind.Add(item2);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.GameInput.PlayerInput.CurrentProfile, System.item, System.key, System.list, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_GameSense().