Terraria: System.Security.AccessControl.DiscretionaryAcl.SetAccess
SetAccess() [2/3]
void System.Security.AccessControl.DiscretionaryAcl.SetAccess (AccessControlType accessType, SecurityIdentifier sid, int accessMask, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags, ObjectAceFlags objectFlags, Guid objectType, Guid inheritedObjectType) inline
Definition at line 95 of file DiscretionaryAcl.cs.
    {
        if (!base.IsDS)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_OnlyValidForDS);
        }
        CheckAccessType(accessType);
        CheckFlags(inheritanceFlags, propagationFlags);
        everyOneFullAccessForNullDacl = false;
        SetQualifiedAce(sid, (accessType != 0) ? AceQualifier.AccessDenied : AceQualifier.AccessAllowed, accessMask, GenericAce.AceFlagsFromInheritanceFlags(inheritanceFlags, propagationFlags), objectFlags, objectType, inheritedObjectType);
    }
References System.Security.AccessControl.GenericAce.AceFlagsFromInheritanceFlags(), System.Security.AccessControl.CommonAcl.CheckAccessType(), System.Security.AccessControl.CommonAcl.CheckFlags(), System.Security.AccessControl.DiscretionaryAcl.everyOneFullAccessForNullDacl, System.SR.InvalidOperation_OnlyValidForDS, and System.Security.AccessControl.CommonAcl.SetQualifiedAce().