Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject
InternalReadObject() [2/2]
override object System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject (XmlReaderDelegator xmlReader, bool verifyObjectName) inline package virtual
Reimplemented from System.Runtime.Serialization.XmlObjectSerializer.
Definition at line 366 of file DataContractJsonSerializer.cs.
    {
        if (MaxItemsInObjectGraph == 0)
        {
            throw XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ExceededMaxItemsQuota, MaxItemsInObjectGraph));
        }
        if (verifyObjectName)
        {
            if (!InternalIsStartObject(xmlReader))
            {
                throw XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(System.SR.Format(System.SR.ExpectingElement, XmlDictionaryString.Empty, RootName), xmlReader);
            }
        }
        else if (!IsStartElement(xmlReader))
        {
            throw XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(System.SR.Format(System.SR.ExpectingElementAtDeserialize, XmlNodeType.Element), xmlReader);
        }
        DataContract rootContract = RootContract;
        if (rootContract.IsPrimitive && (object)rootContract.UnderlyingType == _rootType)
        {
            return ReadJsonValue(rootContract, xmlReader, null);
        }
        XmlObjectSerializerReadContextComplexJson xmlObjectSerializerReadContextComplexJson = XmlObjectSerializerReadContextComplexJson.CreateContext(this, rootContract);
        return xmlObjectSerializerReadContextComplexJson.InternalDeserialize(xmlReader, _rootType, rootContract, null, null);
    }
References System.Runtime.Serialization.Json.DataContractJsonSerializer._rootType, System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.CreateContext(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(), System.Xml.XmlDictionaryString.Empty, System.SR.ExceededMaxItemsQuota, System.SR.ExpectingElement, System.SR.ExpectingElementAtDeserialize, System.SR.Format(), System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalIsStartObject(), System.Runtime.Serialization.XmlObjectSerializer.IsStartElement(), System.Runtime.Serialization.Json.DataContractJsonSerializer.MaxItemsInObjectGraph, System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadJsonValue(), System.Runtime.Serialization.Json.DataContractJsonSerializer.RootContract, and System.Runtime.Serialization.Json.DataContractJsonSerializer.RootName.