Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfJsonNameRequiresMapping
CheckIfJsonNameRequiresMapping() [1/2]
static bool System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfJsonNameRequiresMapping (string jsonName) inline static package
Definition at line 254 of file DataContractJsonSerializer.cs.
    {
        if (jsonName != null)
        {
            if (!DataContract.IsValidNCName(jsonName))
            {
                return true;
            }
            for (int i = 0; i < jsonName.Length; i++)
            {
                if (XmlJsonWriter.CharacterNeedsEscaping(jsonName[i]))
                {
                    return true;
                }
            }
        }
        return false;
    }
References System.Runtime.Serialization.Json.XmlJsonWriter.CharacterNeedsEscaping(), and System.Runtime.Serialization.DataContract.IsValidNCName().
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfJsonNameRequiresMapping(), System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfXmlNameRequiresMapping(), and System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize().