Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObjectContent
InternalWriteObjectContent()
override void System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObjectContent (XmlWriterDelegator writer, object graph) inline package virtual
Reimplemented from System.Runtime.Serialization.XmlObjectSerializer.
Definition at line 407 of file DataContractJsonSerializer.cs.
    {
        if (MaxItemsInObjectGraph == 0)
        {
            throw XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ExceededMaxItemsQuota, MaxItemsInObjectGraph));
        }
        DataContract rootContract = RootContract;
        Type underlyingType = rootContract.UnderlyingType;
        Type type = ((graph == null) ? underlyingType : graph.GetType());
        if (graph == null)
        {
            WriteJsonNull(writer);
            return;
        }
        if (underlyingType == type)
        {
            if (rootContract.CanContainReferences)
            {
                XmlObjectSerializerWriteContextComplexJson xmlObjectSerializerWriteContextComplexJson = XmlObjectSerializerWriteContextComplexJson.CreateContext(this, rootContract);
                xmlObjectSerializerWriteContextComplexJson.OnHandleReference(writer, graph, canContainCyclicReference: true);
                xmlObjectSerializerWriteContextComplexJson.SerializeWithoutXsiType(rootContract, writer, graph, underlyingType.TypeHandle);
            }
            else
            {
                WriteJsonValue(JsonDataContract.GetJsonDataContract(rootContract), writer, graph, null, underlyingType.TypeHandle);
            }
            return;
        }
        XmlObjectSerializerWriteContextComplexJson xmlObjectSerializerWriteContextComplexJson2 = XmlObjectSerializerWriteContextComplexJson.CreateContext(this, RootContract);
        rootContract = GetDataContract(rootContract, underlyingType, type);
        if (rootContract.CanContainReferences)
        {
            xmlObjectSerializerWriteContextComplexJson2.OnHandleReference(writer, graph, canContainCyclicReference: true);
            xmlObjectSerializerWriteContextComplexJson2.SerializeWithXsiTypeAtTopLevel(rootContract, writer, graph, underlyingType.TypeHandle, type);
        }
        else
        {
            xmlObjectSerializerWriteContextComplexJson2.SerializeWithoutXsiType(rootContract, writer, graph, underlyingType.TypeHandle);
        }
    }
References System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.CreateContext(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ExceededMaxItemsQuota, System.SR.Format(), System.Runtime.Serialization.Json.DataContractJsonSerializer.GetDataContract(), System.Runtime.Serialization.Json.JsonDataContract.GetJsonDataContract(), System.Runtime.Serialization.Json.DataContractJsonSerializer.MaxItemsInObjectGraph, System.Runtime.Serialization.Json.DataContractJsonSerializer.RootContract, System.type, System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteJsonNull(), System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteJsonValue(), and System.writer.
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObject().