Terraria: System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific
RemoveAccessSpecific() [1/3]
void System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific (AccessControlType accessType, SecurityIdentifier sid, int accessMask, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags) inline
Definition at line 66 of file DiscretionaryAcl.cs.
    {
        CheckAccessType(accessType);
        everyOneFullAccessForNullDacl = false;
        RemoveQualifiedAcesSpecific(sid, (accessType != 0) ? AceQualifier.AccessDenied : AceQualifier.AccessAllowed, accessMask, GenericAce.AceFlagsFromInheritanceFlags(inheritanceFlags, propagationFlags), ObjectAceFlags.None, Guid.Empty, Guid.Empty);
    }
References System.Security.AccessControl.GenericAce.AceFlagsFromInheritanceFlags(), System.Security.AccessControl.CommonAcl.CheckAccessType(), System.Guid.Empty, System.Security.AccessControl.DiscretionaryAcl.everyOneFullAccessForNullDacl, and System.Security.AccessControl.CommonAcl.RemoveQualifiedAcesSpecific().
Referenced by System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(), and System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific().