Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize
Initialize() [1/2]
void System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize (Type type, IEnumerable< Type > knownTypes, int maxItemsInObjectGraph, bool ignoreExtensionDataObject, EmitTypeInformation emitTypeInformation, bool serializeReadOnlyTypes, DateTimeFormat dateTimeFormat, bool useSimpleDictionaryFormat) inline private
Definition at line 480 of file DataContractJsonSerializer.cs.
    {
        XmlObjectSerializer.CheckNull(type, "type");
        _rootType = type;
        if (knownTypes != null)
        {
            knownTypeList = new List<Type>();
            foreach (Type knownType in knownTypes)
            {
                knownTypeList.Add(knownType);
                if (knownType != null)
                {
                    AddCollectionItemTypeToKnownTypes(knownType);
                }
            }
        }
        if (maxItemsInObjectGraph < 0)
        {
            throw new ArgumentOutOfRangeException("maxItemsInObjectGraph", System.SR.ValueMustBeNonNegative);
        }
        _maxItemsInObjectGraph = maxItemsInObjectGraph;
        _ignoreExtensionDataObject = ignoreExtensionDataObject;
        _emitTypeInformation = emitTypeInformation;
        _serializeReadOnlyTypes = serializeReadOnlyTypes;
        _dateTimeFormat = dateTimeFormat;
        _useSimpleDictionaryFormat = useSimpleDictionaryFormat;
    }
References System.Runtime.Serialization.Json.DataContractJsonSerializer._dateTimeFormat, System.Runtime.Serialization.Json.DataContractJsonSerializer._emitTypeInformation, System.Runtime.Serialization.Json.DataContractJsonSerializer._ignoreExtensionDataObject, System.Runtime.Serialization.Json.DataContractJsonSerializer._maxItemsInObjectGraph, System.Runtime.Serialization.Json.DataContractJsonSerializer._rootType, System.Runtime.Serialization.Json.DataContractJsonSerializer._serializeReadOnlyTypes, System.Runtime.Serialization.Json.DataContractJsonSerializer._useSimpleDictionaryFormat, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Json.DataContractJsonSerializer.AddCollectionItemTypeToKnownTypes(), System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.DataContractJsonSerializer.knownTypeList, System.type, and System.SR.ValueMustBeNonNegative.
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.DataContractJsonSerializer(), System.Runtime.Serialization.Json.DataContractJsonSerializer.DataContractJsonSerializer(), and System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize().