Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.AddCollectionItemTypeToKnownTypes
AddCollectionItemTypeToKnownTypes()
void System.Runtime.Serialization.Json.DataContractJsonSerializer.AddCollectionItemTypeToKnownTypes (Type knownType) inline private
Definition at line 463 of file DataContractJsonSerializer.cs.
    {
        Type type = knownType;
        Type itemType;
        while (CollectionDataContract.IsCollection(type, out itemType))
        {
            if (itemType.IsGenericType && itemType.GetGenericTypeDefinition() == Globals.TypeOfKeyValue)
            {
                itemType = Globals.TypeOfKeyValuePair.MakeGenericType(itemType.GenericTypeArguments);
            }
            knownTypeList.Add(itemType);
            type = itemType;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CollectionDataContract.IsCollection(), System.Runtime.Serialization.Json.DataContractJsonSerializer.knownTypeList, System.type, System.Runtime.Serialization.Globals.TypeOfKeyValue, and System.Runtime.Serialization.Globals.TypeOfKeyValuePair.
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize().