Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObject
InternalWriteObject() [1/2]
override void System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObject (XmlWriterDelegator writer, object graph) inline package virtual
Reimplemented from System.Runtime.Serialization.XmlObjectSerializer.
Definition at line 399 of file DataContractJsonSerializer.cs.
    {
        InternalWriteStartObject(writer, graph);
        InternalWriteObjectContent(writer, graph);
        InternalWriteEndObject(writer);
    }
References System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteEndObject(), System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObjectContent(), System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteStartObject(), and System.writer.