Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject
WriteObject() [1/3]
override void System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject (Stream stream, object? graph) inline virtual
Reimplemented from System.Runtime.Serialization.XmlObjectSerializer.
Definition at line 210 of file DataContractJsonSerializer.cs.
    {
        XmlObjectSerializer.CheckNull(stream, "stream");
        XmlDictionaryWriter xmlDictionaryWriter = JsonReaderWriterFactory.CreateJsonWriter(stream, Encoding.UTF8, ownsStream: false);
        WriteObject(xmlDictionaryWriter, graph);
        xmlDictionaryWriter.Flush();
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.Json.JsonReaderWriterFactory.CreateJsonWriter(), System.stream, System.Text.Encoding.UTF8, and System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject().
Referenced by Terraria.Social.WeGame.WeGameHelper.Serialize< T >(), and System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject().