Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfTypeIsReference
CheckIfTypeIsReference()
static void System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfTypeIsReference (DataContract dataContract) inline static package
Definition at line 517 of file DataContractJsonSerializer.cs.
    {
        if (dataContract.IsReference)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.JsonUnsupportedForIsReference, DataContract.GetClrTypeFullName(dataContract.UnderlyingType), dataContract.IsReference)));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.JsonUnsupportedForIsReference, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.GetDataContract(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetDataContract(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.GetDataContract(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetDataContract(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.GetDataContract(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.GetDataContractSkipValidation(), and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.GetDataContractSkipValidation().