Terraria: System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize
Initialize() [2/2]
void System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize (Type type, XmlDictionaryString rootName, IEnumerable< Type > knownTypes, int maxItemsInObjectGraph, bool ignoreExtensionDataObject, EmitTypeInformation emitTypeInformation, bool serializeReadOnlyTypes, DateTimeFormat dateTimeFormat, bool useSimpleDictionaryFormat) inline private
Definition at line 510 of file DataContractJsonSerializer.cs.
    {
        Initialize(type, knownTypes, maxItemsInObjectGraph, ignoreExtensionDataObject, emitTypeInformation, serializeReadOnlyTypes, dateTimeFormat, useSimpleDictionaryFormat);
        _rootName = ConvertXmlNameToJsonName(rootName);
        _rootNameRequiresMapping = CheckIfJsonNameRequiresMapping(_rootName);
    }
References System.Runtime.Serialization.Json.DataContractJsonSerializer._rootName, System.Runtime.Serialization.Json.DataContractJsonSerializer._rootNameRequiresMapping, System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfJsonNameRequiresMapping(), System.Runtime.Serialization.Json.DataContractJsonSerializer.ConvertXmlNameToJsonName(), System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize(), and System.type.