Terraria: System.Security.AccessControl.DiscretionaryAcl.AddAccess
AddAccess() [1/3]
void System.Security.AccessControl.DiscretionaryAcl.AddAccess (AccessControlType accessType, SecurityIdentifier sid, int accessMask, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags) inline
Definition at line 43 of file DiscretionaryAcl.cs.
    {
        CheckAccessType(accessType);
        CheckFlags(inheritanceFlags, propagationFlags);
        everyOneFullAccessForNullDacl = false;
        AddQualifiedAce(sid, (accessType != 0) ? AceQualifier.AccessDenied : AceQualifier.AccessAllowed, accessMask, GenericAce.AceFlagsFromInheritanceFlags(inheritanceFlags, propagationFlags), ObjectAceFlags.None, Guid.Empty, Guid.Empty);
    }
References System.Security.AccessControl.GenericAce.AceFlagsFromInheritanceFlags(), System.Security.AccessControl.CommonAcl.AddQualifiedAce(), System.Security.AccessControl.CommonAcl.CheckAccessType(), System.Security.AccessControl.CommonAcl.CheckFlags(), System.Guid.Empty, and System.Security.AccessControl.DiscretionaryAcl.everyOneFullAccessForNullDacl.
Referenced by System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.DiscretionaryAcl.CreateAllowEveryoneFullAccess(), and System.Security.AccessControl.CommonObjectSecurity.ModifyAccess().