Terraria: System.Security.Cryptography.X509Certificates.X509Store.Remove
Remove()
void System.Security.Cryptography.X509Certificates.X509Store.Remove (X509Certificate2 certificate) inline
Definition at line 160 of file X509Store.cs.
    {
        if (certificate == null)
        {
            throw new ArgumentNullException("certificate");
        }
        if (_storePal == null)
        {
            throw new CryptographicException(System.SR.Cryptography_X509_StoreNotOpen);
        }
        if (certificate.Pal != null)
        {
            _storePal.Remove(certificate.Pal);
        }
    }
References System.Security.Cryptography.X509Certificates.X509Store._storePal, System.SR.Cryptography_X509_StoreNotOpen, System.Security.Cryptography.X509Certificates.X509Certificate2.Pal, and Internal.Cryptography.Pal.IStorePal.Remove().
Referenced by System.Security.Cryptography.X509Certificates.X509Store.AddRange(), and System.Security.Cryptography.X509Certificates.X509Store.RemoveRange().