Terraria: CavernShader.ProcessHighDetail
ProcessHighDetail()
void CavernShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
     {
         time *= _speed * 0.5f;
         float num = time % 1f;
         bool num2 = time % 2f > 1f;
         Vector4 vector = (num2 ? _frontColor : _backColor);
         Vector4 value = (num2 ? _backColor : _frontColor);
         num *= 1.2f;
         for (int i = 0; i < fragment.Count; i++)
         {
             float staticNoise = NoiseHelper.GetStaticNoise(fragment.GetCanvasPositionOfIndex(i) * 0.5f + new Vector2(0f, time * 0.5f));
             Vector4 vector2 = vector;
             staticNoise += num;
             if (staticNoise > 0.999f)
             {
                 float amount = MathHelper.Clamp((staticNoise - 0.999f) / 0.2f, 0f, 1f);
                 vector2 = Vector4.Lerp(vector2, value, amount);
             }
             fragment.SetColor(i, vector2);
         }
     }
References _backColor, _frontColor, _speed, Fragment.Count, Fragment.GetCanvasPositionOfIndex(), NoiseHelper.GetStaticNoise(), and Fragment.SetColor().