Terraria: Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar.ValidateAndCollectNecessaryInfo
ValidateAndCollectNecessaryInfo()
bool Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar.ValidateAndCollectNecessaryInfo (ref BigProgressBarInfo info) inline
Implements Terraria.GameContent.UI.BigProgressBar.IBigProgressBar.
    {
        if (info.npcIndexToAimAt < 0 || info.npcIndexToAimAt > 200)
        {
            return false;
        }
        NPC nPC = Main.npc[info.npcIndexToAimAt];
        if (!nPC.active && !TryFindingAnotherEOWPiece(ref info))
        {
            return false;
        }
        int num = 2;
        int num2 = NPC.GetEaterOfWorldsSegmentsCount() + num;
        _segmentForReference.SetDefaults(14, nPC.GetMatchingSpawnParams());
        int num3 = 0;
        int num4 = _segmentForReference.lifeMax * num2;
        for (int i = 0; i < 200; i++)
        {
            NPC nPC2 = Main.npc[i];
            if (nPC2.active && nPC2.type >= 13 && nPC2.type <= 15)
            {
                num3 += nPC2.life;
            }
        }
        int num5 = num3;
        int num6 = num4;
        _cache.SetLife(num5, num6);
        return true;
    }
References Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar._cache, Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar._segmentForReference, Terraria.Entity.active, Terraria.NPC.GetEaterOfWorldsSegmentsCount(), Terraria.NPC.GetMatchingSpawnParams(), Terraria.NPC.life, Terraria.Main.npc, Terraria.NPC.SetDefaults(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarCache.SetLife(), Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar.TryFindingAnotherEOWPiece(), and Terraria.NPC.type.