Terraria: System.Data.RecordManager.CopyRecord
CopyRecord()
int System.Data.RecordManager.CopyRecord (DataTable src, int record, int copy) inline package
Definition at line 198 of file RecordManager.cs.
    {
        if (record == -1)
        {
            return copy;
        }
        int record2 = -1;
        try
        {
            record2 = ((copy == -1) ? _table.NewUninitializedRecord() : copy);
            int count = _table.Columns.Count;
            for (int i = 0; i < count; i++)
            {
                DataColumn dataColumn = _table.Columns[i];
                DataColumn dataColumn2 = src.Columns[dataColumn.ColumnName];
                if (dataColumn2 != null)
                {
                    object obj = dataColumn2[record];
                    if (obj is ICloneable cloneable)
                    {
                        dataColumn[record2] = cloneable.Clone();
                    }
                    else
                    {
                        dataColumn[record2] = obj;
                    }
                }
                else if (-1 == copy)
                {
                    dataColumn.Init(record2);
                }
            }
            return record2;
        }
        catch (Exception e) when (ADP.IsCatchableOrSecurityExceptionType(e))
        {
            if (-1 == copy)
            {
                FreeRecord(ref record2);
            }
            throw;
        }
    }
References System.Data.RecordManager._table, System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.count, System.Data.RecordManager.FreeRecord(), System.Data.Common.ADP.IsCatchableOrSecurityExceptionType(), System.Data.DataTable.NewUninitializedRecord(), and System.obj.
Referenced by System.Data.RecordManager.ImportRecord(), and System.Data.DataTable.MergeRow().