Terraria: System.Data.RecordManager.NewRecordBase
NewRecordBase()
int System.Data.RecordManager.NewRecordBase () inline package
Definition at line 118 of file RecordManager.cs.
    {
        int result;
        if (_freeRecordList.Count != 0)
        {
            result = _freeRecordList[_freeRecordList.Count - 1];
            _freeRecordList.RemoveAt(_freeRecordList.Count - 1);
        }
        else
        {
            if (_lastFreeRecord >= _recordCapacity)
            {
                GrowRecordCapacity();
            }
            result = _lastFreeRecord;
            _lastFreeRecord++;
        }
        return result;
    }
References System.Data.RecordManager._freeRecordList, System.Data.RecordManager._lastFreeRecord, System.Data.RecordManager._recordCapacity, System.Collections.Generic.List< T >.Count, System.Data.RecordManager.GrowRecordCapacity(), and System.Collections.Generic.List< T >.RemoveAt().
Referenced by System.Data.DataTable.NewRecord(), System.Data.DataTable.NewRecordFromArray(), and System.Data.DataTable.NewUninitializedRecord().