Terraria: System.Data.RecordManager.Clear
Clear()
void System.Data.RecordManager.Clear (bool clearAll) inline package
Definition at line 160 of file RecordManager.cs.
    {
        if (clearAll)
        {
            for (int i = 0; i < _recordCapacity; i++)
            {
                _rows[i] = null;
            }
            int count = _table._columnCollection.Count;
            for (int j = 0; j < count; j++)
            {
                DataColumn dataColumn = _table._columnCollection[j];
                for (int k = 0; k < _recordCapacity; k++)
                {
                    dataColumn.FreeRecord(k);
                }
            }
            _lastFreeRecord = 0;
            _freeRecordList.Clear();
            return;
        }
        _freeRecordList.Capacity = _freeRecordList.Count + _table.Rows.Count;
        for (int l = 0; l < _recordCapacity; l++)
        {
            DataRow dataRow = _rows[l];
            if (dataRow != null && dataRow.rowID != -1)
            {
                int record = l;
                FreeRecord(ref record);
            }
        }
    }
References System.Data.DataTable._columnCollection, System.Data.RecordManager._freeRecordList, System.Data.RecordManager._lastFreeRecord, System.Data.RecordManager._recordCapacity, System.Data.RecordManager._rows, System.Data.RecordManager._table, System.Collections.Generic.List< T >.Clear(), System.Data.DataRowCollection.Count, System.Data.InternalDataCollectionBase.Count, System.count, System.Data.RecordManager.FreeRecord(), and System.Data.DataTable.Rows.
Referenced by System.Data.DataTable.Clear().