Terraria: System.Data.RecordManager.GrowRecordCapacity
GrowRecordCapacity()
void System.Data.RecordManager.GrowRecordCapacity () inline private
Definition at line 81 of file RecordManager.cs.
    {
        RecordCapacity = ((NewCapacity(_recordCapacity) < NormalizedMinimumCapacity(_minimumCapacity)) ? NormalizedMinimumCapacity(_minimumCapacity) : NewCapacity(_recordCapacity));
        DataRow[] array = _table.NewRowArray(_recordCapacity);
        if (_rows != null)
        {
            Array.Copy(_rows, array, Math.Min(_lastFreeRecord, _rows.Length));
        }
        _rows = array;
    }
References System.Data.RecordManager._lastFreeRecord, System.Data.RecordManager._minimumCapacity, System.Data.RecordManager._recordCapacity, System.Data.RecordManager._rows, System.Data.RecordManager._table, System.array, System.Array.Copy(), System.Math.Min(), System.Data.RecordManager.NewCapacity(), System.Data.DataTable.NewRowArray(), System.Data.RecordManager.NormalizedMinimumCapacity(), and System.Data.RecordManager.RecordCapacity.
Referenced by System.Data.RecordManager.NewRecordBase().