Terraria: System.Data.RecordManager.FreeRecord
FreeRecord()
void System.Data.RecordManager.FreeRecord (ref int record) inline package
Definition at line 138 of file RecordManager.cs.
    {
        if (-1 != record)
        {
            _rows[record] = null;
            int count = _table._columnCollection.Count;
            for (int i = 0; i < count; i++)
            {
                _table._columnCollection[i].FreeRecord(record);
            }
            if (_lastFreeRecord == record + 1)
            {
                _lastFreeRecord--;
            }
            else if (record < _lastFreeRecord)
            {
                _freeRecordList.Add(record);
            }
            record = -1;
        }
    }
References System.Data.DataTable._columnCollection, System.Data.RecordManager._freeRecordList, System.Data.RecordManager._lastFreeRecord, System.Data.RecordManager._rows, System.Data.RecordManager._table, System.Collections.Generic.List< T >.Add(), System.Data.InternalDataCollectionBase.Count, and System.count.
Referenced by System.Data.RecordManager.Clear(), System.Data.RecordManager.CopyRecord(), and System.Data.DataTable.FreeRecord().