Terraria: System.Xml.Xsl.Runtime.XmlQueryRuntime.GenerateId
GenerateId()
string System.Xml.Xsl.Runtime.XmlQueryRuntime.GenerateId (XPathNavigator navigator) inline
Definition at line 608 of file XmlQueryRuntime.cs.
    {
        IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
        DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(2, 2, invariantCulture);
        handler.AppendLiteral("ID");
        handler.AppendFormatted(_docOrderCmp.GetDocumentIndex(navigator));
        handler.AppendFormatted(navigator.UniqueId);
        return string.Create(invariantCulture, ref handler);
    }
References System.Xml.Xsl.Runtime.XmlQueryRuntime._docOrderCmp, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Xml.Xsl.Runtime.DocumentOrderComparer.GetDocumentIndex(), and System.Globalization.CultureInfo.InvariantCulture.