Terraria: System.Xml.Xsl.Runtime.XmlQueryRuntime.MatchesXmlType
MatchesXmlType() [1/4]
bool System.Xml.Xsl.Runtime.XmlQueryRuntime.MatchesXmlType (IList< XPathItem > seq, int indexType) inline
Definition at line 472 of file XmlQueryRuntime.cs.
    {
        XmlQueryType xmlType = GetXmlType(indexType);
        if (!(seq.Count switch
        {
            0 => XmlQueryCardinality.Zero,
            1 => XmlQueryCardinality.One,
            _ => XmlQueryCardinality.More,
        } <= xmlType.Cardinality))
        {
            return false;
        }
        xmlType = xmlType.Prime;
        for (int i = 0; i < seq.Count; i++)
        {
            if (!CreateXmlType(seq[0]).IsSubtypeOf(xmlType))
            {
                return false;
            }
        }
        return true;
    }
References System.Xml.Xsl.XmlQueryType.Cardinality, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Xsl.Runtime.XmlQueryRuntime.CreateXmlType(), System.Xml.Xsl.Runtime.XmlQueryRuntime.GetXmlType(), and System.Xml.Xsl.XmlQueryType.Prime.
Referenced by System.Xml.Xsl.Runtime.XmlQueryRuntime.MatchesXmlType().