Terraria: System.Xml.Xsl.Runtime.XmlQueryRuntime.ParseTagName
ParseTagName() [2/3]
XmlQualifiedName System.Xml.Xsl.Runtime.XmlQueryRuntime.ParseTagName (string tagName, int indexPrefixMappings) inline
Definition at line 226 of file XmlQueryRuntime.cs.
    {
        ParseTagName(tagName, indexPrefixMappings, out var _, out var localName, out var ns);
        return new XmlQualifiedName(localName, ns);
    }
References System.Xml.Xsl.Runtime.XmlQueryRuntime.ParseTagName().
Referenced by System.Xml.Xsl.Runtime.XmlQueryRuntime.ParseTagName(), and System.Xml.Xsl.Runtime.XmlQueryOutput.WriteStartComputed().