Terraria: System.Xml.Xsl.Runtime.XmlQueryRuntime.ComparePosition
ComparePosition()
int System.Xml.Xsl.Runtime.XmlQueryRuntime.ComparePosition (XPathNavigator navigatorThis, XPathNavigator navigatorThat) inline
Definition at line 589 of file XmlQueryRuntime.cs.
    {
        return _docOrderCmp.Compare(navigatorThis, navigatorThat);
    }
References System.Xml.Xsl.Runtime.XmlQueryRuntime._docOrderCmp, and System.Xml.Xsl.Runtime.DocumentOrderComparer.Compare().
Referenced by System.Xml.Xsl.Runtime.DodSequenceMerge.InsertSequence(), System.Xml.Xsl.Runtime.DifferenceIterator.MoveNext(), System.Xml.Xsl.Runtime.IntersectIterator.MoveNext(), and System.Xml.Xsl.Runtime.UnionIterator.MoveNext().