Terraria: System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator
SyncToNavigator()
static XPathNavigator System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator (XPathNavigator navigatorThis, XPathNavigator navigatorThat) inline static package
Definition at line 707 of file XmlQueryRuntime.cs.
    {
        if (navigatorThis == null || !navigatorThis.MoveTo(navigatorThat))
        {
            return navigatorThat.Clone();
        }
        return navigatorThis;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Runtime.AttributeContentIterator.Create(), System.Xml.Xsl.Runtime.AttributeIterator.Create(), System.Xml.Xsl.Runtime.ContentIterator.Create(), System.Xml.Xsl.Runtime.ElementContentIterator.Create(), System.Xml.Xsl.Runtime.IdIterator.Create(), System.Xml.Xsl.Runtime.FollowingSiblingIterator.Create(), System.Xml.Xsl.Runtime.ParentIterator.Create(), System.Xml.Xsl.Runtime.PrecedingIterator.Create(), System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator.Create(), System.Xml.Xsl.Runtime.PrecedingSiblingIterator.Create(), System.Xml.Xsl.Runtime.AncestorIterator.Create(), System.Xml.Xsl.Runtime.NodeKindContentIterator.Create(), System.Xml.Xsl.Runtime.XPathFollowingIterator.Create(), System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.Create(), System.Xml.Xsl.Runtime.DescendantIterator.Create(), System.Xml.Xsl.Runtime.NodeRangeIterator.Create(), System.Xml.Xsl.Runtime.DescendantMergeIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.MoveNext(), and System.Xml.Xsl.Runtime.ContentMergeIterator.MoveNext().