Terraria: System.Xml.Xsl.Runtime.XmlQueryRuntime.ChangeTypeXsltResult
ChangeTypeXsltResult() [2/2]
object System.Xml.Xsl.Runtime.XmlQueryRuntime.ChangeTypeXsltResult (XmlQueryType xmlType, object value) inline package
Definition at line 377 of file XmlQueryRuntime.cs.
    {
        if (value == null)
        {
            throw new XslTransformException(System.SR.Xslt_ItemNull, string.Empty);
        }
        switch (xmlType.TypeCode)
        {
        case XmlTypeCode.String:
            if (value.GetType() == XsltConvert.DateTimeType)
            {
                value = XsltConvert.ToString((DateTime)value);
            }
            break;
        case XmlTypeCode.Double:
            if (value.GetType() != XsltConvert.DoubleType)
            {
                value = ((IConvertible)value).ToDouble(null);
            }
            break;
        case XmlTypeCode.Node:
            if (xmlType.IsSingleton)
            {
                break;
            }
            if (value is XPathArrayIterator xPathArrayIterator && xPathArrayIterator.AsList is XmlQueryNodeSequence)
            {
                value = xPathArrayIterator.AsList as XmlQueryNodeSequence;
            }
            else
            {
                XmlQueryNodeSequence xmlQueryNodeSequence = new XmlQueryNodeSequence();
                if (value is IList list)
                {
                    for (int i = 0; i < list.Count; i++)
                    {
                        xmlQueryNodeSequence.Add(EnsureNavigator(list[i]));
                    }
                }
                else
                {
                    foreach (object item in (IEnumerable)value)
                    {
                        xmlQueryNodeSequence.Add(EnsureNavigator(item));
                    }
                }
                value = xmlQueryNodeSequence;
            }
            value = ((XmlQueryNodeSequence)value).DocOrderDistinct(_docOrderCmp);
            break;
        case XmlTypeCode.Item:
        {
            Type type = value.GetType();
            switch (XsltConvert.InferXsltType(type).TypeCode)
            {
            case XmlTypeCode.Boolean:
                value = new XmlQueryItemSequence(new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Boolean), value));
                break;
            case XmlTypeCode.Double:
                value = new XmlQueryItemSequence(new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Double), ((IConvertible)value).ToDouble(null)));
                break;
            case XmlTypeCode.String:
                value = ((!(type == XsltConvert.DateTimeType)) ? new XmlQueryItemSequence(new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String), value)) : new XmlQueryItemSequence(new XmlAtomicValue(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String), XsltConvert.ToString((DateTime)value))));
                break;
            case XmlTypeCode.Node:
                value = ChangeTypeXsltResult(XmlQueryTypeFactory.NodeS, value);
                break;
            case XmlTypeCode.Item:
                if (value is XPathNodeIterator)
                {
                    value = ChangeTypeXsltResult(XmlQueryTypeFactory.NodeS, value);
                    break;
                }
                if (!(value is IXPathNavigable iXPathNavigable))
                {
                    throw new XslTransformException(System.SR.Xslt_UnsupportedClrType, type.Name);
                }
                value = ((!(value is XPathNavigator)) ? new XmlQueryNodeSequence(iXPathNavigable.CreateNavigator()) : new XmlQueryNodeSequence((XPathNavigator)value));
                break;
            }
            break;
        }
        }
        return value;
    }
References System.Xml.Xsl.Runtime.XmlQueryRuntime._docOrderCmp, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ChangeTypeXsltResult(), System.Xml.Xsl.Runtime.XsltConvert.DateTimeType, System.Xml.Dictionary, System.Xml.Xsl.Runtime.XsltConvert.DoubleType, System.Xml.Xsl.Runtime.XmlQueryRuntime.EnsureNavigator(), System.Xml.Schema.XmlSchemaType.GetBuiltInSimpleType(), System.Type.GetType(), System.Xml.Xsl.Runtime.XsltConvert.InferXsltType(), System.Xml.Xsl.XmlQueryType.IsSingleton, System.item, System.list, System.Xml.Xsl.XmlQueryTypeFactory.NodeS, System.Xml.Xsl.Runtime.XsltConvert.ToString(), System.type, System.Xml.Xsl.XmlQueryType.TypeCode, System.value, System.SR.Xslt_ItemNull, and System.SR.Xslt_UnsupportedClrType.