Terraria: System.Xml.Xsl.Runtime.XmlQueryRuntime.CreateXmlType
CreateXmlType()
XmlQueryType System.Xml.Xsl.Runtime.XmlQueryRuntime.CreateXmlType (XPathItem item) inline private
Definition at line 548 of file XmlQueryRuntime.cs.
    {
        if (item.IsNode)
        {
            if (item is RtfNavigator)
            {
                return XmlQueryTypeFactory.Node;
            }
            XPathNavigator xPathNavigator = (XPathNavigator)item;
            switch (xPathNavigator.NodeType)
            {
            case XPathNodeType.Root:
            case XPathNodeType.Element:
                if (xPathNavigator.XmlType == null)
                {
                    return XmlQueryTypeFactory.Type(xPathNavigator.NodeType, XmlQualifiedNameTest.New(xPathNavigator.LocalName, xPathNavigator.NamespaceURI), XmlSchemaComplexType.UntypedAnyType, isNillable: false);
                }
                return XmlQueryTypeFactory.Type(xPathNavigator.NodeType, XmlQualifiedNameTest.New(xPathNavigator.LocalName, xPathNavigator.NamespaceURI), xPathNavigator.XmlType, xPathNavigator.SchemaInfo.SchemaElement.IsNillable);
            case XPathNodeType.Attribute:
                if (xPathNavigator.XmlType == null)
                {
                    return XmlQueryTypeFactory.Type(xPathNavigator.NodeType, XmlQualifiedNameTest.New(xPathNavigator.LocalName, xPathNavigator.NamespaceURI), DatatypeImplementation.UntypedAtomicType, isNillable: false);
                }
                return XmlQueryTypeFactory.Type(xPathNavigator.NodeType, XmlQualifiedNameTest.New(xPathNavigator.LocalName, xPathNavigator.NamespaceURI), xPathNavigator.XmlType, isNillable: false);
            default:
                return XmlQueryTypeFactory.Type(xPathNavigator.NodeType, XmlQualifiedNameTest.Wildcard, XmlSchemaComplexType.AnyType, isNillable: false);
            }
        }
        return XmlQueryTypeFactory.Type((XmlSchemaSimpleType)item.XmlType, isStrict: true);
    }
References System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Dictionary, System.item, System.Xml.Xsl.XmlQualifiedNameTest.New(), System.Xml.Xsl.XmlQueryTypeFactory.Node, System.Xml.Xsl.XmlQueryTypeFactory.Type(), System.Xml.Schema.XmlSchemaComplexType.UntypedAnyType, System.Xml.Schema.DatatypeImplementation.UntypedAtomicType, and System.Xml.Xsl.XmlQualifiedNameTest.Wildcard.
Referenced by System.Xml.Xsl.Runtime.XmlQueryRuntime.MatchesXmlType(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.MatchesXmlType().