Terraria: System.Xml.Xsl.Runtime.XmlQueryRuntime.AddNewIndex
AddNewIndex()
void System.Xml.Xsl.Runtime.XmlQueryRuntime.AddNewIndex (XPathNavigator context, int indexId, XmlILIndex index) inline
Definition at line 641 of file XmlQueryRuntime.cs.
    {
        XPathNavigator xPathNavigator = context.Clone();
        xPathNavigator.MoveToRoot();
        if (_indexes == null)
        {
            _indexes = new ArrayList[indexId + 4];
        }
        else if (indexId >= _indexes.Length)
        {
            ArrayList[] array = new ArrayList[indexId + 4];
            Array.Copy(_indexes, array, _indexes.Length);
            _indexes = array;
        }
        ArrayList arrayList = _indexes[indexId];
        if (arrayList == null)
        {
            arrayList = new ArrayList();
            _indexes[indexId] = arrayList;
        }
        arrayList.Add(xPathNavigator);
        arrayList.Add(index);
    }
References System.Xml.Xsl.Runtime.XmlQueryRuntime._indexes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Xml.XPath.XPathNavigator.Clone(), System.Array.Copy(), System.Xml.Dictionary, and System.index.