Terraria: Terraria.DataStructures.DrawData.Draw
Draw() [1/2]
void Terraria.DataStructures.DrawData.Draw (SpriteBatch sb) inline
Definition at line 146 of file DrawData.cs.
    {
        if (useDestinationRectangle)
        {
            sb.Draw(texture, destinationRectangle, sourceRect, color, rotation, origin, effect, 0f);
        }
        else
        {
            sb.Draw(texture, position, sourceRect, color, rotation, origin, scale, effect, 0f);
        }
    }
References Terraria.DataStructures.DrawData.color, Terraria.DataStructures.DrawData.destinationRectangle, Terraria.DataStructures.DrawData.effect, Terraria.DataStructures.DrawData.origin, Terraria.DataStructures.DrawData.position, Terraria.DataStructures.DrawData.rotation, Terraria.DataStructures.DrawData.scale, Terraria.DataStructures.DrawData.sourceRect, Terraria.DataStructures.DrawData.texture, and Terraria.DataStructures.DrawData.useDestinationRectangle.
Referenced by Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayers(), Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld(), Terraria.GameContent.Drawing.TileDrawing.DrawVoidLenses(), Terraria.Main.EntitySpriteDraw(), Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseReqest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseReqest(), Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseReqest(), and Terraria.Graphics.Renderers.MapHeadRenderer.RenderDrawData().