Terraria: Internal.Cryptography.DesImplementation.GenerateKey
GenerateKey()
override void Internal.Cryptography.DesImplementation.GenerateKey () inline sealed
Definition at line 34 of file DesImplementation.cs.
    {
        byte[] array = new byte[KeySize / 8];
        RandomNumberGenerator.Fill(array);
        while (DES.IsWeakKey(array) || DES.IsSemiWeakKey(array))
        {
            RandomNumberGenerator.Fill(array);
        }
        KeyValue = array;
    }
References System.array, System.Security.Cryptography.RandomNumberGenerator.Fill(), System.Security.Cryptography.DES.IsSemiWeakKey(), System.Security.Cryptography.DES.IsWeakKey(), System.Security.Cryptography.SymmetricAlgorithm.KeySize, and System.Security.Cryptography.SymmetricAlgorithm.KeyValue.