Terraria: Internal.Cryptography.DesImplementation.TryDecryptCfbCore
TryDecryptCfbCore()
override bool Internal.Cryptography.DesImplementation.TryDecryptCfbCore (ReadOnlySpan< byte > ciphertext, ReadOnlySpan< byte > iv, Span< byte > destination, PaddingMode paddingMode, int feedbackSizeInBits, out int bytesWritten) inline protected virtual
Reimplemented from System.Security.Cryptography.SymmetricAlgorithm.
Definition at line 115 of file DesImplementation.cs.
    {
        ValidateCFBFeedbackSize(feedbackSizeInBits);
        UniversalCryptoTransform universalCryptoTransform = CreateTransformCore(CipherMode.CFB, paddingMode, Key, iv.ToArray(), BlockSize / 8, feedbackSizeInBits / 8, feedbackSizeInBits / 8, encrypting: false);
        using (universalCryptoTransform)
        {
            return universalCryptoTransform.TransformOneShot(ciphertext, destination, out bytesWritten);
        }
    }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSize, Internal.Cryptography.DesImplementation.CreateTransformCore(), System.destination, System.Security.Cryptography.DES.Key, System.ReadOnlySpan< T >.ToArray(), Internal.Cryptography.UniversalCryptoTransform.TransformOneShot(), and Internal.Cryptography.DesImplementation.ValidateCFBFeedbackSize().