Terraria: Internal.Cryptography.DesImplementation.CreateTransform
CreateTransform()
ICryptoTransform Internal.Cryptography.DesImplementation.CreateTransform (byte[] rgbKey, byte[] rgbIV, bool encrypting) inline private
Definition at line 45 of file DesImplementation.cs.
    {
        if (rgbKey == null)
        {
            throw new ArgumentNullException("rgbKey");
        }
        long num = (long)rgbKey.Length * 8L;
        if (num > int.MaxValue || !((int)num).IsLegalSize(LegalKeySizes))
        {
            throw new ArgumentException(System.SR.Cryptography_InvalidKeySize, "rgbKey");
        }
        if (DES.IsWeakKey(rgbKey))
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidKey_Weak, "DES");
        }
        if (DES.IsSemiWeakKey(rgbKey))
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidKey_SemiWeak, "DES");
        }
        if (rgbIV != null)
        {
            long num2 = (long)rgbIV.Length * 8L;
            if (num2 != BlockSize)
            {
                throw new ArgumentException(System.SR.Cryptography_InvalidIVSize, "rgbIV");
            }
        }
        if (Mode == CipherMode.CFB)
        {
            ValidateCFBFeedbackSize(FeedbackSize);
        }
        return CreateTransformCore(Mode, Padding, rgbKey, rgbIV, BlockSize / 8, FeedbackSize / 8, this.GetPaddingSize(Mode, FeedbackSize), encrypting);
    }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSize, Internal.Cryptography.DesImplementation.CreateTransformCore(), System.SR.Cryptography_InvalidIVSize, System.SR.Cryptography_InvalidKey_SemiWeak, System.SR.Cryptography_InvalidKey_Weak, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.SymmetricAlgorithm.FeedbackSize, System.Security.Cryptography.DES.IsSemiWeakKey(), System.Security.Cryptography.DES.IsWeakKey(), System.L, System.Security.Cryptography.SymmetricAlgorithm.LegalKeySizes, System.Security.Cryptography.SymmetricAlgorithm.Padding, and Internal.Cryptography.DesImplementation.ValidateCFBFeedbackSize().
Referenced by Internal.Cryptography.DesImplementation.CreateDecryptor(), Internal.Cryptography.DesImplementation.CreateDecryptor(), Internal.Cryptography.DesImplementation.CreateEncryptor(), and Internal.Cryptography.DesImplementation.CreateEncryptor().