Terraria: System.IO.Directory.GetParent
GetParent()
static ? DirectoryInfo System.IO.Directory.GetParent (string path) inline static
Definition at line 9 of file Directory.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(SR.Argument_PathEmpty, "path");
        }
        string fullPath = Path.GetFullPath(path);
        string directoryName = Path.GetDirectoryName(fullPath);
        if (directoryName == null)
        {
            return null;
        }
        return new DirectoryInfo(directoryName);
    }
References System.SR.Argument_PathEmpty, System.IO.Path.GetDirectoryName(), and System.IO.Path.GetFullPath().
Referenced by ReLogic.IO.ConsoleOutputMirror.ConsoleOutputMirror(), and Terraria.IO.Preferences.Save().