Terraria: System.IO.Directory.GetDirectories
GetDirectories() [1/4]
static string[] System.IO.Directory.GetDirectories (string path) inline static
Definition at line 156 of file Directory.cs.
    {
        return GetDirectories(path, "*", EnumerationOptions.Compatible);
    }
References System.IO.EnumerationOptions.Compatible, and System.IO.Directory.GetDirectories().
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.ContainsUnknownFiles(), Terraria.Utilities.FileUtilities.CopyFolder(), Terraria.IO.ResourcePackList.CreatePacksFromDirectories(), System.IO.Directory.GetDirectories(), System.IO.Directory.GetDirectories(), System.IO.Directory.GetDirectories(), and System.IO.IsolatedStorage.Helper.GetExistingRandomDirectory().