Terraria: System.IO.Directory.Exists
Exists()
static bool System.IO.Directory.Exists ([NotNullWhen(true)] string? path) inline static
Definition at line 43 of file Directory.cs.
    {
        try
        {
            if (path == null)
            {
                return false;
            }
            if (path.Length == 0)
            {
                return false;
            }
            string fullPath = Path.GetFullPath(path);
            return FileSystem.DirectoryExists(fullPath);
        }
        catch (ArgumentException)
        {
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
        return false;
    }
References System.IO.FileSystem.DirectoryExists(), and System.IO.Path.GetFullPath().
Referenced by Terraria.IO.ResourcePack.ResourcePack(), ReLogic.Content.Sources.FileSystemContentSource.BuildNameToAbsolutePathDictionary(), System.IO.FileSystemWatcher.CheckPathValidity(), System.IO.IsolatedStorage.IsolatedStorageFile.CreateDirectory(), System.IO.IsolatedStorage.Helper.CreateDirectory(), Terraria.IO.ResourcePackList.CreatePacksFromSavedJson(), System.IO.IsolatedStorage.IsolatedStorageFile.DirectoryExists(), Terraria.Main.ErasePlayer(), Terraria.IO.ResourcePackList.FromJson(), System.IO.IsolatedStorage.Helper.GetExistingRandomDirectory(), System.IO.Directory.Move(), Terraria.IO.PlayerFileData.MoveToCloud(), Terraria.IO.ResourcePackList.Publishable(), Terraria.Utils.TryCreatingDirectory(), Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForResourcePack(), and Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForWorld().