Terraria: System.IO.Directory.EnumerateFiles
EnumerateFiles() [1/4]
static IEnumerable< string > System.IO.Directory.EnumerateFiles (string path) inline static
Definition at line 236 of file Directory.cs.
    {
        return EnumerateFiles(path, "*", EnumerationOptions.Compatible);
    }
References System.IO.EnumerationOptions.Compatible, and System.IO.Directory.EnumerateFiles().
Referenced by System.IO.Directory.EnumerateFiles(), System.IO.Directory.EnumerateFiles(), System.IO.Directory.EnumerateFiles(), and System.IO.IsolatedStorage.IsolatedStorageFile.GetFileNames().