Terraria: System.Net.Http.Json.JsonContent.Create
Create()
static JsonContent System.Net.Http.Json.JsonContent< TValue >.Create (object? inputValue, Type inputType, MediaTypeHeaderValue? mediaType = null, JsonSerializerOptions? options = null) inline static
Definition at line 44 of file JsonContent.cs.
    {
        return new JsonContent(inputValue, inputType, mediaType, options);
    }
References System.Net.Http.Json.JsonContent< TValue >.JsonContent(), System.Text.Json.Dictionary, and System.options.
Referenced by System.Net.Http.Json.HttpClientJsonExtensions.PostAsJsonAsync< TValue >(), System.Net.Http.Json.HttpClientJsonExtensions.PostAsJsonAsync< TValue >(), System.Net.Http.Json.HttpClientJsonExtensions.PutAsJsonAsync< TValue >(), and System.Net.Http.Json.HttpClientJsonExtensions.PutAsJsonAsync< TValue >().