Terraria: System.Net.Http.Json.JsonContent.SerializeToStreamAsyncCore
SerializeToStreamAsyncCore() [2/2]
async Task System.Net.Http.Json.JsonContent< TValue >.SerializeToStreamAsyncCore (Stream targetStream, bool async, CancellationToken cancellationToken) inline private
Definition at line 144 of file JsonContent.cs.
    {
        Encoding encoding = JsonHelpers.GetEncoding(base.Headers.ContentType?.CharSet);
        if (encoding != null && encoding != Encoding.UTF8)
        {
            Stream transcodingStream = Encoding.CreateTranscodingStream(targetStream, encoding, Encoding.UTF8, leaveOpen: true);
            try
            {
                if (async)
                {
                    await JsonSerializer.SerializeAsync(transcodingStream, _typedValue, _typeInfo, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    JsonSerializer.Serialize(transcodingStream, _typedValue, _typeInfo);
                }
            }
            finally
            {
                if (async)
                {
                    await transcodingStream.DisposeAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    transcodingStream.Dispose();
                }
            }
        }
        else if (async)
        {
            await JsonSerializer.SerializeAsync(targetStream, _typedValue, _typeInfo, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        else
        {
            JsonSerializer.Serialize(targetStream, _typedValue, _typeInfo);
        }
    }
References System.Net.Http.Json.JsonContent< TValue >._typedValue, System.Net.Http.Json.JsonContent< TValue >._typeInfo, System.cancellationToken, System.Text.Encoding.CreateTranscodingStream(), System.Text.Json.Dictionary, System.Net.Http.Json.JsonHelpers.GetEncoding(), System.Text.Json.JsonSerializer.Serialize(), System.Text.Json.JsonSerializer.SerializeAsync(), and System.Text.Encoding.UTF8.