Terraria: System.IO.Directory.Move
Move()
static void System.IO.Directory.Move (string sourceDirName, string destDirName) inline static
Definition at line 304 of file Directory.cs.
    {
        if (sourceDirName == null)
        {
            throw new ArgumentNullException("sourceDirName");
        }
        if (sourceDirName.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyFileName, "sourceDirName");
        }
        if (destDirName == null)
        {
            throw new ArgumentNullException("destDirName");
        }
        if (destDirName.Length == 0)
        {
            throw new ArgumentException(SR.Argument_EmptyFileName, "destDirName");
        }
        string fullPath = Path.GetFullPath(sourceDirName);
        string text = PathInternal.EnsureTrailingSeparator(fullPath);
        string fullPath2 = Path.GetFullPath(destDirName);
        string text2 = PathInternal.EnsureTrailingSeparator(fullPath2);
        ReadOnlySpan<char> fileName = Path.GetFileName(fullPath.AsSpan());
        ReadOnlySpan<char> fileName2 = Path.GetFileName(fullPath2.AsSpan());
        StringComparison stringComparison = PathInternal.StringComparison;
        bool flag = !fileName.SequenceEqual(fileName2) && MemoryExtensions.Equals(fileName, fileName2, StringComparison.OrdinalIgnoreCase) && MemoryExtensions.Equals(fileName2, fileName, stringComparison);
        if (!flag && string.Equals(text, text2, stringComparison))
        {
            throw new IOException(SR.IO_SourceDestMustBeDifferent);
        }
        ReadOnlySpan<char> pathRoot = Path.GetPathRoot(text.AsSpan());
        ReadOnlySpan<char> pathRoot2 = Path.GetPathRoot(text2.AsSpan());
        if (!MemoryExtensions.Equals(pathRoot, pathRoot2, StringComparison.OrdinalIgnoreCase))
        {
            throw new IOException(SR.IO_SourceDestMustHaveSameRoot);
        }
        if (!FileSystem.DirectoryExists(fullPath) && !FileSystem.FileExists(fullPath))
        {
            throw new DirectoryNotFoundException(SR.Format(SR.IO_PathNotFound_Path, fullPath));
        }
        if (!flag && FileSystem.DirectoryExists(fullPath2))
        {
            throw new IOException(SR.Format(SR.IO_AlreadyExists_Name, fullPath2));
        }
        if (!flag && Exists(fullPath2))
        {
            throw new IOException(SR.Format(SR.IO_AlreadyExists_Name, fullPath2));
        }
        FileSystem.MoveDirectory(fullPath, fullPath2);
    }
References System.SR.Argument_EmptyFileName, System.IO.FileSystem.DirectoryExists(), System.IO.PathInternal.EnsureTrailingSeparator(), System.MemoryExtensions.Equals(), System.IO.Directory.Exists(), System.IO.FileSystem.FileExists(), System.SR.Format(), System.IO.Path.GetFileName(), System.IO.Path.GetFullPath(), System.IO.Path.GetPathRoot(), System.SR.IO_AlreadyExists_Name, System.SR.IO_PathNotFound_Path, System.SR.IO_SourceDestMustBeDifferent, System.SR.IO_SourceDestMustHaveSameRoot, System.IO.FileSystem.MoveDirectory(), System.IO.PathInternal.StringComparison, and System.text.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.MoveDirectory().