Terraria: System.Text.Json.Serialization.Converters.TimeSpanConverter.Read
Read()
override TimeSpan System.Text.Json.Serialization.Converters.TimeSpanConverter.Read (ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) inline
Definition at line 8 of file TimeSpanConverter.cs.
    {
        if (reader.TokenType != JsonTokenType.String)
        {
            throw ThrowHelper.GetInvalidOperationException_ExpectedString(reader.TokenType);
        }
        bool stringHasEscaping = reader._stringHasEscaping;
        int num = (stringHasEscaping ? 156 : 26);
        ReadOnlySpan<byte> readOnlySpan = default(Span<byte>);
        if (reader.HasValueSequence)
        {
            ReadOnlySequence<byte> source = reader.ValueSequence;
            long length = source.Length;
            if (!JsonHelpers.IsInRangeInclusive(length, 8L, num))
            {
                throw ThrowHelper.GetFormatException(DataType.TimeSpan);
            }
            Span<byte> destination = stackalloc byte[stringHasEscaping ? 156 : 26];
            source.CopyTo(destination);
            readOnlySpan = destination.Slice(0, (int)length);
        }
        else
        {
            readOnlySpan = reader.ValueSpan;
            if (!JsonHelpers.IsInRangeInclusive(readOnlySpan.Length, 8, num))
            {
                throw ThrowHelper.GetFormatException(DataType.TimeSpan);
            }
        }
        if (stringHasEscaping)
        {
            int idx = readOnlySpan.IndexOf<byte>(92);
            Span<byte> destination2 = stackalloc byte[156];
            JsonReaderHelper.Unescape(readOnlySpan, destination2, idx, out var written);
            readOnlySpan = destination2.Slice(0, written);
        }
        byte b = readOnlySpan[0];
        if (!JsonHelpers.IsDigit(b) && b != 45)
        {
            throw ThrowHelper.GetFormatException(DataType.TimeSpan);
        }
        if (Utf8Parser.TryParse(readOnlySpan, out TimeSpan value, out int bytesConsumed, 'c') && readOnlySpan.Length == bytesConsumed)
        {
            return value;
        }
        throw ThrowHelper.GetFormatException(DataType.TimeSpan);
    }
References System.Span< T >.CopyTo(), System.destination, System.Text.Json.Dictionary, System.Text.Json.ThrowHelper.GetFormatException(), System.Text.Json.ThrowHelper.GetInvalidOperationException_ExpectedString(), System.Text.Json.JsonHelpers.IsDigit(), System.Text.Json.JsonHelpers.IsInRangeInclusive(), System.L, System.Buffers.ReadOnlySequence< T >.Length, System.length, System.source, System.Buffers.Text.Utf8Parser.TryParse(), System.Text.Json.JsonReaderHelper.Unescape(), and System.value.