Terraria: System.IO.Directory.CreateDirectory
CreateDirectory()
static DirectoryInfo System.IO.Directory.CreateDirectory (string path) inline static
Definition at line 28 of file Directory.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (path.Length == 0)
        {
            throw new ArgumentException(SR.Argument_PathEmpty, "path");
        }
        string fullPath = Path.GetFullPath(path);
        FileSystem.CreateDirectory(fullPath);
        return new DirectoryInfo(path, fullPath, null, isNormalized: true);
    }
References System.SR.Argument_PathEmpty, System.IO.FileSystem.CreateDirectory(), and System.IO.Path.GetFullPath().
Referenced by ReLogic.IO.ConsoleOutputMirror.ConsoleOutputMirror(), Terraria.Utilities.FileUtilities.CopyFolder(), System.IO.IsolatedStorage.IsolatedStorageFile.CreateDirectory(), System.IO.IsolatedStorage.Helper.CreateDirectory(), Terraria.Testing.PacketHistory.Dump(), System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.Remove(), and Terraria.Utils.TryCreatingDirectory().