Terraria: System.IO.Directory.GetFiles
GetFiles() [1/4]
static string[] System.IO.Directory.GetFiles (string path) inline static
Definition at line 136 of file Directory.cs.
    {
        return GetFiles(path, "*", EnumerationOptions.Compatible);
    }
References System.IO.EnumerationOptions.Compatible, and System.IO.Directory.GetFiles().
Referenced by ReLogic.Content.Sources.XnaDirectContentSource.XnaDirectContentSource(), ReLogic.Content.Sources.FileSystemContentSource.BuildNameToAbsolutePathDictionary(), System.IO.IsolatedStorage.IsolatedStorageFile.ContainsUnknownFiles(), Terraria.Utilities.FileUtilities.CopyFolder(), Terraria.IO.ResourcePackList.CreatePacksFromZips(), System.IO.Directory.GetFiles(), System.IO.Directory.GetFiles(), System.IO.Directory.GetFiles(), Terraria.Main.LoadPlayers(), Terraria.Main.LoadWorlds(), and Terraria.IO.PlayerFileData.MoveToCloud().