Terraria: System.IO.Directory.InternalEnumeratePaths
InternalEnumeratePaths()
static IEnumerable< string > System.IO.Directory.InternalEnumeratePaths (string path, string searchPattern, SearchTarget searchTarget, EnumerationOptions options) inline static package
Definition at line 196 of file Directory.cs.
    {
        if (path == null)
        {
            throw new ArgumentNullException("path");
        }
        if (searchPattern == null)
        {
            throw new ArgumentNullException("searchPattern");
        }
        FileSystemEnumerableFactory.NormalizeInputs(ref path, ref searchPattern, options.MatchType);
        return searchTarget switch
        {
            SearchTarget.Files => FileSystemEnumerableFactory.UserFiles(path, searchPattern, options),
            SearchTarget.Directories => FileSystemEnumerableFactory.UserDirectories(path, searchPattern, options),
            SearchTarget.Both => FileSystemEnumerableFactory.UserEntries(path, searchPattern, options),
            _ => throw new ArgumentOutOfRangeException("searchTarget"),
        };
    }
References System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(), System.options, System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(), System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(), and System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles().
Referenced by System.IO.Directory.EnumerateDirectories(), System.IO.Directory.EnumerateFiles(), System.IO.Directory.EnumerateFileSystemEntries(), System.IO.Directory.GetDirectories(), System.IO.Directory.GetFiles(), and System.IO.Directory.GetFileSystemEntries().