Terraria: Terraria.Chat.Commands.RockPaperScissorsCommand.ProcessOutgoingMessage
ProcessOutgoingMessage()
void Terraria.Chat.Commands.RockPaperScissorsCommand.ProcessOutgoingMessage (ChatMessage message) inline
Implements Terraria.Chat.Commands.IChatCommand.
Definition at line 12 of file RockPaperScissorsCommand.cs.
    {
        int num = Main.rand.NextFromList<int>(37, 38, 36);
        if (Main.netMode == 0)
        {
            EmoteBubble.NewBubble(num, new WorldUIAnchor(Main.LocalPlayer), 360);
            EmoteBubble.CheckForNPCsToReactToEmoteBubble(num, Main.LocalPlayer);
        }
        else
        {
            NetMessage.SendData(120, -1, -1, null, Main.myPlayer, num);
        }
        message.Consume();
    }
References Terraria.GameContent.UI.EmoteBubble.CheckForNPCsToReactToEmoteBubble(), Terraria.Chat.ChatMessage.Consume(), Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.GameContent.UI.EmoteBubble.NewBubble(), Terraria.Main.rand, and Terraria.NetMessage.SendData().