Terraria: System.Globalization.IcuLocaleData.GetLocaleDataNumericPart
GetLocaleDataNumericPart()
static int System.Globalization.IcuLocaleData.GetLocaleDataNumericPart (string cultureName, IcuLocaleDataParts part) inline static package
Definition at line 1746 of file IcuLocaleData.cs.
    {
        int num = SearchCultureName(cultureName);
        if (num < 0)
        {
            return -1;
        }
        ReadOnlySpan<byte> readOnlySpan = NameIndexToNumericData.Slice(num * 18, 18);
        return part switch
        {
            IcuLocaleDataParts.Lcid => readOnlySpan[2] | (readOnlySpan[1] << 8) | (readOnlySpan[0] << 16),
            IcuLocaleDataParts.AnsiCodePage => ((readOnlySpan[4] & 0xF0) >> 4) | ((readOnlySpan[3] & 0xFF) << 4),
            IcuLocaleDataParts.OemCodePage => readOnlySpan[5] | ((readOnlySpan[4] & 0xF) << 8),
            IcuLocaleDataParts.MacCodePage => readOnlySpan[7] | (readOnlySpan[6] << 8),
            IcuLocaleDataParts.EbcdicCodePage => readOnlySpan[9] | (readOnlySpan[8] << 8),
            IcuLocaleDataParts.GeoId => readOnlySpan[13] | (readOnlySpan[12] << 8) | (readOnlySpan[11] << 16) | (readOnlySpan[10] << 24),
            IcuLocaleDataParts.DigitSubstitutionOrListSeparator => ResolveDigitListSeparator(readOnlySpan[14]),
            IcuLocaleDataParts.SpecificLocaleIndex => ResolveIndex(((readOnlySpan[16] & 0xF0) >> 4) | ((readOnlySpan[15] & 0xFF) << 4)),
            IcuLocaleDataParts.ConsoleLocaleIndex => ResolveIndex(readOnlySpan[17] | ((readOnlySpan[16] & 0xF) << 8)),
            _ => -1,
        };
        static int ResolveDigitListSeparator(int value)
        {
            return ((value & 0xF0) << 12) | (value & 0xF);
        }
        static int ResolveIndex(int value)
        {
            if (value != 4095)
            {
                return value;
            }
            return -1;
        }
    }
References System.Globalization.IcuLocaleData.NameIndexToNumericData, System.Globalization.IcuLocaleData.SearchCultureName(), and System.value.
Referenced by System.Globalization.IcuLocaleData.GetLocaleDataMappedCulture(), System.Globalization.CultureData.IcuGetDigitSubstitution(), System.Globalization.CultureData.IcuGetGeoId(), System.Globalization.CultureData.IcuGetListSeparator(), and System.Globalization.CultureData.IcuLocaleNameToLCID().