Terraria: System.Globalization.IcuLocaleData.GetThreeLetterWindowsLanguageName
GetThreeLetterWindowsLanguageName()
static string System.Globalization.IcuLocaleData.GetThreeLetterWindowsLanguageName (string cultureName) inline static package
Definition at line 1781 of file IcuLocaleData.cs.
    {
        int num = SearchCultureName(cultureName);
        if (num < 0)
        {
            return null;
        }
        return GetString(ThreeLetterWindowsLanguageName.Slice(num * 3, 3));
    }
References System.Globalization.IcuLocaleData.GetString(), System.Globalization.IcuLocaleData.SearchCultureName(), and System.Globalization.IcuLocaleData.ThreeLetterWindowsLanguageName.
Referenced by System.Globalization.CultureData.IcuGetThreeLetterWindowsLanguageName().