Terraria: System.Array.SorterObjectArray.IntrospectiveSort
IntrospectiveSort()
void System.Array.SorterObjectArray.IntrospectiveSort (int left, int length) inline private
Definition at line 71 of file Array.cs.
        {
            if (length < 2)
            {
                return;
            }
            try
            {
                IntroSort(left, length + left - 1, 2 * (BitOperations.Log2((uint)length) + 1));
            }
            catch (IndexOutOfRangeException)
            {
                ThrowHelper.ThrowArgumentException_BadComparer(comparer);
            }
            catch (Exception e)
            {
                ThrowHelper.ThrowInvalidOperationException(ExceptionResource.InvalidOperation_IComparerFailed, e);
            }
        }
References System.Array.SorterObjectArray.comparer, System.Array.SorterObjectArray.IntroSort(), System.length, System.Numerics.BitOperations.Log2(), System.ThrowHelper.ThrowArgumentException_BadComparer(), and System.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Array.SorterObjectArray.Sort().