Terraria: System.Array.SorterObjectArray.Heapsort
Heapsort()
void System.Array.SorterObjectArray.Heapsort (int lo, int hi) inline private
Definition at line 157 of file Array.cs.
        {
            int num = hi - lo + 1;
            for (int num2 = num / 2; num2 >= 1; num2--)
            {
                DownHeap(num2, num, lo);
            }
            for (int num3 = num; num3 > 1; num3--)
            {
                Swap(lo, lo + num3 - 1);
                DownHeap(1, num3 - 1, lo);
            }
        }
References System.Array.SorterObjectArray.DownHeap(), and System.Array.SorterObjectArray.Swap().
Referenced by System.Array.SorterObjectArray.IntroSort().