Terraria: Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.ProvideSlider
ProvideSlider()
override UIElement Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.ProvideSlider () inline
Implements Terraria.GameContent.Creative.IProvideSliderElement.
Definition at line 1026 of file CreativePowers.cs.
        {
            UIVerticalSlider uIVerticalSlider = CreativePowersHelper.CreateSlider(base.GetSliderValue, base.SetValueKeyboard, base.SetValueGamepad);
            UIPanel uIPanel = new UIPanel();
            uIPanel.Width = new StyleDimension(82f, 0f);
            uIPanel.Height = new StyleDimension(180f, 0f);
            uIPanel.HAlign = 0f;
            uIPanel.VAlign = 0.5f;
            uIPanel.Append(uIVerticalSlider);
            uIPanel.OnUpdate += CreativePowersHelper.UpdateUseMouseInterface;
            uIVerticalSlider.OnUpdate += UpdateSliderColorAndShowMultiplierMouseOver;
            AddIndication(uIPanel, 0f, "x3", "Images/UI/WorldCreation/IconDifficultyMaster", MouseOver_Master, Click_Master);
            AddIndication(uIPanel, 1f / 3f, "x2", "Images/UI/WorldCreation/IconDifficultyExpert", MouseOver_Expert, Click_Expert);
            AddIndication(uIPanel, 2f / 3f, "x1", "Images/UI/WorldCreation/IconDifficultyNormal", MouseOver_Normal, Click_Normal);
            AddIndication(uIPanel, 1f, "x0.5", "Images/UI/WorldCreation/IconDifficultyCreative", MouseOver_Journey, Click_Journey);
            return uIPanel;
        }
References Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.AddIndication(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Click_Expert(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Click_Journey(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Click_Master(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Click_Normal(), Terraria.GameContent.Creative.CreativePowersHelper.CreateSlider(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Expert(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Journey(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Master(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Normal(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.UpdateSliderColorAndShowMultiplierMouseOver(), and Terraria.GameContent.Creative.CreativePowersHelper.UpdateUseMouseInterface().