Terraria: AWorldListItem.GetDifficulty
GetDifficulty()
void AWorldListItem.GetDifficulty (out string expertText, out Color gameModeColor) inline protected inherited
     {
         expertText = "";
         gameModeColor = Color.White;
         if (_data.GameMode == 3)
         {
             expertText = Language.GetTextValue("UI.Creative");
             gameModeColor = Main.creativeModeColor;
             return;
         }
         int num = 1;
         switch (_data.GameMode)
         {
         case 1:
             num = 2;
             break;
         case 2:
             num = 3;
             break;
         }
         if (_data.ForTheWorthy)
         {
             num++;
         }
         switch (num)
         {
         default:
             expertText = Language.GetTextValue("UI.Normal");
             break;
         case 2:
             expertText = Language.GetTextValue("UI.Expert");
             gameModeColor = Main.mcColor;
             break;
         case 3:
             expertText = Language.GetTextValue("UI.Master");
             gameModeColor = Main.hcColor;
             break;
         case 4:
             expertText = Language.GetTextValue("UI.Legendary");
             gameModeColor = Main.legendaryModeColor;
             break;
         }
     }
References AWorldListItem._data, Color, Main.creativeModeColor, WorldFileData.ForTheWorthy, WorldFileData.GameMode, Language.GetTextValue(), Main.hcColor, Main.legendaryModeColor, and Main.mcColor.
Referenced by UIWorkshopImportWorldListItem.DrawSelf(), UIWorkshopPublishWorldListItem.DrawSelf(), and DrawSelf().