Terraria: System.Xml.Xsl.Xslt.XslAstRewriter.Rewrite
Rewrite()
void System.Xml.Xsl.Xslt.XslAstRewriter.Rewrite (Compiler compiler) inline
Definition at line 16 of file XslAstRewriter.cs.
    {
        _compiler = compiler;
        _scope = new CompilerScopeManager<VarPar>();
        _newTemplates = new Stack<Template>();
        foreach (ProtoTemplate allTemplate in compiler.AllTemplates)
        {
            _scope.EnterScope();
            CheckNodeCost(allTemplate);
        }
        while (_newTemplates.Count > 0)
        {
            Template template = _newTemplates.Pop();
            compiler.AllTemplates.Add(template);
            compiler.NamedTemplates.Add(template.Name, template);
            _scope.EnterScope();
            CheckNodeCost(template);
        }
    }
References System.Xml.Xsl.Xslt.XslAstRewriter._compiler, System.Xml.Xsl.Xslt.XslAstRewriter._newTemplates, System.Xml.Xsl.Xslt.XslAstRewriter._scope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Xslt.XslAstRewriter.CheckNodeCost(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, and System.Xml.Name.
Referenced by System.Xml.Xsl.Xslt.QilGenerator.Compile().