Terraria: System.Xml.Xsl.Xslt.XslAstRewriter.CheckNodeCost
CheckNodeCost()
int System.Xml.Xsl.Xslt.XslAstRewriter.CheckNodeCost (XslNode node) inline private
Definition at line 58 of file XslAstRewriter.cs.
    {
        _scope.EnterScope(node.Namespaces);
        bool flag = false;
        int num = 1;
        if (NodeTypeTest(node.NodeType, -247451132))
        {
            num += NodeCostForXPath(node.Select);
        }
        IList<XslNode> content = node.Content;
        int num2 = content.Count - 1;
        for (int i = 0; i <= num2; i++)
        {
            XslNode xslNode = content[i];
            int num3 = CheckNodeCost(xslNode);
            num += num3;
            if (flag && num > 100)
            {
                if (i < num2 || num3 > 1)
                {
                    Refactor(node, i);
                    num -= num3;
                    num++;
                }
                break;
            }
            if (xslNode.NodeType == XslNodeType.Variable || xslNode.NodeType == XslNodeType.Param)
            {
                _scope.AddVariable(xslNode.Name, (VarPar)xslNode);
                if (xslNode.NodeType == XslNodeType.Param)
                {
                    num -= num3;
                }
            }
            else if (!flag)
            {
                flag = NodeTypeTest(node.NodeType, -1025034872);
            }
        }
        _scope.ExitScope();
        return num;
    }
References System.Xml.Xsl.Xslt.XslAstRewriter._scope, System.Xml.Xsl.Xslt.XslAstRewriter.CheckNodeCost(), System.Xml.Dictionary, System.Xml.Xsl.Xslt.XslAstRewriter.NodeCostForXPath(), System.Xml.Xsl.Xslt.XslAstRewriter.NodeTypeTest(), and System.Xml.Xsl.Xslt.XslAstRewriter.Refactor().
Referenced by System.Xml.Xsl.Xslt.XslAstRewriter.CheckNodeCost(), and System.Xml.Xsl.Xslt.XslAstRewriter.Rewrite().