Terraria: System.Net.Sockets.TcpClient.GetStream
GetStream()
NetworkStream System.Net.Sockets.TcpClient.GetStream () inline
Definition at line 391 of file TcpClient.cs.
    {
        ThrowIfDisposed();
        if (!Connected)
        {
            throw new InvalidOperationException(System.SR.net_notconnected);
        }
        if (_dataStream == null)
        {
            _dataStream = new NetworkStream(Client, ownsSocket: true);
        }
        return _dataStream;
    }
References System.Net.Sockets.TcpClient._dataStream, System.Net.Sockets.TcpClient.Connected, System.SR.net_notconnected, and System.Net.Sockets.TcpClient.ThrowIfDisposed().
Referenced by System.Net.NetworkStreamWrapper.NetworkStreamWrapper(), Terraria.Net.Sockets.TcpSocket.AsyncReceive(), Terraria.Net.Sockets.TcpSocket.AsyncSend(), System.Net.Mail.SmtpConnection.EndInitializeConnection(), System.Net.Mail.SmtpConnection.InitializeConnection(), Terraria.Net.Sockets.TcpSocket.IsDataAvailable(), Terraria.Net.Sockets.TcpSocket.ReadCallback(), and Terraria.Net.Sockets.TcpSocket.SendCallback().