Terraria: System.Net.Sockets.TcpClient.TcpClient
TcpClient() [2/5]
System.Net.Sockets.TcpClient.TcpClient (AddressFamily family) inline
Definition at line 148 of file TcpClient.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, family, ".ctor");
        }
        if (family != AddressFamily.InterNetwork && family != AddressFamily.InterNetworkV6 && family != AddressFamily.Unknown)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_protocol_invalid_family, "TCP"), "family");
        }
        _family = family;
        InitializeClientSocket();
    }
References System.Net.Sockets.TcpClient._family, System.SR.Format(), System.Net.NetEventSource.Info(), System.Net.Sockets.TcpClient.InitializeClientSocket(), System.Net.NetEventSource.Log, and System.SR.net_protocol_invalid_family.