Terraria: System.Net.Sockets.TcpClient.TcpClient
TcpClient() [3/5]
System.Net.Sockets.TcpClient.TcpClient (IPEndPoint localEP) inline
Definition at line 162 of file TcpClient.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info(this, localEP, ".ctor");
        }
        if (localEP == null)
        {
            throw new ArgumentNullException("localEP");
        }
        _family = localEP.AddressFamily;
        InitializeClientSocket();
        _clientSocket.Bind(localEP);
    }
References System.Net.Sockets.TcpClient._clientSocket, System.Net.Sockets.TcpClient._family, System.Net.IPEndPoint.AddressFamily, System.Net.Sockets.Socket.Bind(), System.Net.NetEventSource.Info(), System.Net.Sockets.TcpClient.InitializeClientSocket(), and System.Net.NetEventSource.Log.