Terraria: System.Net.Sockets.TcpClient.Connect
Connect() [4/4]
void System.Net.Sockets.TcpClient.Connect (string hostname, int port) inline
Definition at line 209 of file TcpClient.cs.
    {
        ThrowIfDisposed();
        if (hostname == null)
        {
            throw new ArgumentNullException("hostname");
        }
        if (!System.Net.TcpValidationHelpers.ValidatePortNumber(port))
        {
            throw new ArgumentOutOfRangeException("port");
        }
        if (_active)
        {
            throw new SocketException(10056);
        }
        IPAddress[] hostAddresses = Dns.GetHostAddresses(hostname);
        ExceptionDispatchInfo exceptionDispatchInfo = null;
        try
        {
            IPAddress[] array = hostAddresses;
            foreach (IPAddress iPAddress in array)
            {
                try
                {
                    if (_clientSocket == null)
                    {
                        if ((iPAddress.AddressFamily == AddressFamily.InterNetwork && Socket.OSSupportsIPv4) || Socket.OSSupportsIPv6)
{
                            Socket socket = new Socket(iPAddress.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
                            if (iPAddress.IsIPv4MappedToIPv6)
{
                                socket.DualMode = true;
                            }
                            Interlocked.Exchange(ref _clientSocket, socket);
                            if (Disposed)
{
                                socket.Dispose();
                            }
                            try
{
                                socket.Connect(iPAddress, port);
                            }
                            catch
{
                                _clientSocket = null;
                                throw;
                            }
                        }
                        _family = iPAddress.AddressFamily;
                        _active = true;
                        break;
                    }
                    if (iPAddress.AddressFamily == _family || _family == AddressFamily.Unknown)
                    {
                        Connect(new IPEndPoint(iPAddress, port));
                        _active = true;
                        break;
                    }
                }
                catch (Exception ex) when (!(ex is OutOfMemoryException))
                {
                    exceptionDispatchInfo = ExceptionDispatchInfo.Capture(ex);
                }
            }
        }
        finally
        {
            if (!_active)
            {
                exceptionDispatchInfo?.Throw();
                throw new SocketException(10057);
            }
        }
    }
References System.Net.Sockets.TcpClient._active, System.Net.Sockets.TcpClient._clientSocket, System.Net.Sockets.TcpClient._family, System.Net.IPAddress.AddressFamily, System.array, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Connect, System.Net.Sockets.Socket.Dispose(), System.Net.Sockets.TcpClient.Disposed, System.Threading.Interlocked.Exchange(), System.Net.Dns.GetHostAddresses(), System.Net.IPAddress.IsIPv4MappedToIPv6, System.Net.Sockets.Socket.OSSupportsIPv4, System.Net.Sockets.Socket.OSSupportsIPv6, System.Net.Sockets.Socket, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(), System.Net.Sockets.TcpClient.ThrowIfDisposed(), and System.Net.TcpValidationHelpers.ValidatePortNumber().
Referenced by Terraria.Net.Sockets.TcpSocket.Connect(), System.Net.FtpWebRequest.CreateConnection(), and System.Net.Mail.SmtpConnection.InitializeConnection().