Terraria: System.Net.Sockets.TcpClient.Dispose
Dispose() [2/2]
virtual void System.Net.Sockets.TcpClient.Dispose (bool disposing) inline protected virtual
Definition at line 410 of file TcpClient.cs.
    {
        if (Interlocked.CompareExchange(ref _disposed, 1, 0) != 0 || !disposing)
        {
            return;
        }
        IDisposable dataStream = _dataStream;
        if (dataStream != null)
        {
            dataStream.Dispose();
        }
        else
        {
            Socket socket = Volatile.Read(ref _clientSocket);
            if (socket != null)
            {
                try
                {
                    socket.InternalShutdown(SocketShutdown.Both);
                }
                finally
                {
                    socket.Close();
                }
            }
        }
        GC.SuppressFinalize(this);
    }
References System.Net.Sockets.TcpClient._clientSocket, System.Net.Sockets.TcpClient._dataStream, System.Net.Sockets.TcpClient._disposed, System.Net.Sockets.Socket.Close(), System.Threading.Interlocked.CompareExchange(), System.IDisposable.Dispose(), System.Net.Sockets.Socket.InternalShutdown(), System.Threading.Volatile.Read(), and System.GC.SuppressFinalize().
Referenced by System.Net.NetworkStreamWrapper.Close(), System.Net.NetworkStreamWrapper.CloseSocket(), and System.Net.Mail.SmtpConnection.ShutdownConnection().