Terraria: System.Runtime.Serialization.Json.JsonObjectDataContract.ParseJsonNumber
ParseJsonNumber() [2/2]
static object System.Runtime.Serialization.Json.JsonObjectDataContract.ParseJsonNumber (string value, out TypeCode objectTypeCode) inline static package
Definition at line 55 of file JsonObjectDataContract.cs.
    {
        if (value == null)
        {
            throw new XmlException(System.SR.Format(System.SR.XmlInvalidConversion, value, Globals.TypeOfInt));
        }
        if (value.IndexOfAny(JsonGlobals.FloatingPointCharacters) == -1)
        {
            if (int.TryParse(value, NumberStyles.Float, NumberFormatInfo.InvariantInfo, out var result))
            {
                objectTypeCode = TypeCode.Int32;
                return result;
            }
            if (long.TryParse(value, NumberStyles.Float, NumberFormatInfo.InvariantInfo, out var result2))
            {
                objectTypeCode = TypeCode.Int64;
                return result2;
            }
        }
        if (decimal.TryParse(value, NumberStyles.Float, NumberFormatInfo.InvariantInfo, out var result3))
        {
            objectTypeCode = TypeCode.Decimal;
            if (result3 == 0m)
            {
                double num = XmlConverter.ToDouble(value);
                if (num != 0.0)
                {
                    objectTypeCode = TypeCode.Double;
                    return num;
                }
            }
            return result3;
        }
        objectTypeCode = TypeCode.Double;
        return XmlConverter.ToDouble(value);
    }
References System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Json.JsonGlobals.FloatingPointCharacters, System.SR.Format(), System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlConverter.ToDouble(), System.Runtime.Serialization.Globals.TypeOfInt, System.value, System.Xml.XmlException, and System.SR.XmlInvalidConversion.
Referenced by System.Runtime.Serialization.Json.JsonObjectDataContract.ParseJsonNumber(), System.Runtime.Serialization.Json.JsonObjectDataContract.ReadJsonValueCore(), and System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadNumericalPrimitiveExtensionDataValue().