Terraria: System.Runtime.Serialization.Json.JsonObjectDataContract.ReadJsonValueCore
ReadJsonValueCore()
override object System.Runtime.Serialization.Json.JsonObjectDataContract.ReadJsonValueCore (XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context) inline virtual
Reimplemented from System.Runtime.Serialization.Json.JsonDataContract.
Definition at line 16 of file JsonObjectDataContract.cs.
    {
        string attribute = jsonReader.GetAttribute("type");
        object obj;
        switch (attribute)
        {
        case "null":
            jsonReader.Skip();
            obj = null;
            break;
        case "boolean":
            obj = jsonReader.ReadElementContentAsBoolean();
            break;
        case "string":
        case null:
            obj = jsonReader.ReadElementContentAsString();
            break;
        case "number":
            obj = ParseJsonNumber(jsonReader.ReadElementContentAsString());
            break;
        case "object":
            jsonReader.Skip();
            obj = new object();
            break;
        case "array":
            return DataContractJsonSerializer.ReadJsonValue(DataContract.GetDataContract(Globals.TypeOfObjectArray), jsonReader, context);
        default:
            throw XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.JsonUnexpectedAttributeValue, attribute));
        }
        context?.AddNewObject(obj);
        return obj;
    }
References System.Runtime.Serialization.XmlObjectSerializerReadContext.AddNewObject(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetDataContract(), System.SR.JsonUnexpectedAttributeValue, System.obj, System.Runtime.Serialization.Json.JsonObjectDataContract.ParseJsonNumber(), System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadJsonValue(), and System.Runtime.Serialization.Globals.TypeOfObjectArray.