Terraria: System.Data.Common.DbConnectionOptions.AppendKeyValuePairBuilder
AppendKeyValuePairBuilder()
static void System.Data.Common.DbConnectionOptions.AppendKeyValuePairBuilder (StringBuilder builder, string keyName, string keyValue, bool useOdbcRules) inline static package
Definition at line 62 of file DbConnectionOptions.cs.
    {
        ADP.CheckArgumentNull(builder, "builder");
        ADP.CheckArgumentLength(keyName, "keyName");
        if (keyName == null || !s_connectionStringValidKeyRegex.IsMatch(keyName))
        {
            throw ADP.InvalidKeyname(keyName);
        }
        if (keyValue != null && !IsValueValidInternal(keyValue))
        {
            throw ADP.InvalidValue(keyName);
        }
        if (0 < builder.Length && ';' != builder[builder.Length - 1])
        {
            builder.Append(';');
        }
        if (useOdbcRules)
        {
            builder.Append(keyName);
        }
        else
        {
            builder.Append(keyName.Replace("=", "=="));
        }
        builder.Append('=');
        if (keyValue == null)
        {
            return;
        }
        if (useOdbcRules)
        {
            if (0 < keyValue.Length && ('{' == keyValue[0] || 0 <= keyValue.IndexOf(';') || string.Equals("Driver", keyName, StringComparison.OrdinalIgnoreCase)) && !s_connectionStringQuoteOdbcValueRegex.IsMatch(keyValue))
            {
                builder.Append('{').Append(keyValue.Replace("}", "}}")).Append('}');
            }
            else
            {
                builder.Append(keyValue);
            }
        }
        else if (s_connectionStringQuoteValueRegex.IsMatch(keyValue))
        {
            builder.Append(keyValue);
        }
        else if (keyValue.Contains('"') && !keyValue.Contains('\''))
        {
            builder.Append('\'');
            builder.Append(keyValue);
            builder.Append('\'');
        }
        else
        {
            builder.Append('"');
            builder.Append(keyValue.Replace("\"", "\"\""));
            builder.Append('"');
        }
    }
References System.Data.Common.ADP.CheckArgumentLength(), System.Data.Common.ADP.CheckArgumentNull(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Data.Common.ADP.InvalidKeyname(), System.Data.Common.ADP.InvalidValue(), System.Data.Common.DbConnectionOptions.IsValueValidInternal(), System.Data.Common.DbConnectionOptions.s_connectionStringQuoteOdbcValueRegex, System.Data.Common.DbConnectionOptions.s_connectionStringQuoteValueRegex, and System.Data.Common.DbConnectionOptions.s_connectionStringValidKeyRegex.
Referenced by System.Data.Common.DbConnectionStringBuilder.AppendKeyValuePair(), and System.Data.Common.DbConnectionStringBuilder.AppendKeyValuePair().