Terraria: System.Data.Common.DbConnectionOptions.ParseInternal
ParseInternal()
static NameValuePair System.Data.Common.DbConnectionOptions.ParseInternal (Dictionary< string, string > parsetable, string connectionString, bool buildChain, Dictionary< string, string > synonyms, bool firstKey) inline static private
Definition at line 417 of file DbConnectionOptions.cs.
    {
        StringBuilder buffer = new StringBuilder();
        NameValuePair nameValuePair = null;
        NameValuePair result = null;
        int num = 0;
        int length = connectionString.Length;
        while (num < length)
        {
            int num2 = num;
            num = GetKeyValuePair(connectionString, num2, buffer, firstKey, out var keyname, out var keyvalue);
            if (string.IsNullOrEmpty(keyname))
            {
                break;
            }
            string value;
            string text = ((synonyms == null) ? keyname : (synonyms.TryGetValue(keyname, out value) ? value : null));
            if (!IsKeyNameValid(text))
            {
                throw ADP.KeywordNotSupported(keyname);
            }
            if (!firstKey || !parsetable.ContainsKey(text))
            {
                parsetable[text] = keyvalue;
            }
            if (nameValuePair != null)
            {
                NameValuePair nameValuePair3 = (nameValuePair.Next = new NameValuePair(text, keyvalue, num - num2));
                nameValuePair = nameValuePair3;
            }
            else if (buildChain)
            {
                result = (nameValuePair = new NameValuePair(text, keyvalue, num - num2));
            }
        }
        return result;
    }
References System.buffer, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Data.Common.DbConnectionOptions.GetKeyValuePair(), System.Data.Common.DbConnectionOptions.IsKeyNameValid(), System.Data.Common.ADP.KeywordNotSupported(), System.length, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Data.Common.DbConnectionOptions.DbConnectionOptions().