Terraria: System.Data.Common.DbConnectionOptions.GetKeyValuePair
GetKeyValuePair()
static int System.Data.Common.DbConnectionOptions.GetKeyValuePair (string connectionString, int currentPosition, StringBuilder buffer, bool useOdbcRules, out string keyname, out string keyvalue) inline static package
Definition at line 159 of file DbConnectionOptions.cs.
    {
        int index = currentPosition;
        buffer.Length = 0;
        keyname = null;
        keyvalue = null;
        char c = '\0';
        ParserState parserState = ParserState.NothingYet;
        for (int length = connectionString.Length; currentPosition < length; currentPosition++)
        {
            c = connectionString[currentPosition];
            switch (parserState)
            {
            case ParserState.NothingYet:
                if (';' == c || char.IsWhiteSpace(c))
                {
                    continue;
                }
                if (c == '\0')
                {
                    parserState = ParserState.NullTermination;
                    continue;
                }
                if (char.IsControl(c))
                {
                    throw ADP.ConnectionStringSyntax(index);
                }
                index = currentPosition;
                if ('=' != c)
                {
                    parserState = ParserState.Key;
                    goto IL_0248;
                }
                parserState = ParserState.KeyEqual;
                continue;
            case ParserState.Key:
                if ('=' == c)
                {
                    parserState = ParserState.KeyEqual;
                    continue;
                }
                if (!char.IsWhiteSpace(c) && char.IsControl(c))
                {
                    throw ADP.ConnectionStringSyntax(index);
                }
                goto IL_0248;
            case ParserState.KeyEqual:
                if (!useOdbcRules && '=' == c)
                {
                    parserState = ParserState.Key;
                    goto IL_0248;
                }
                keyname = GetKeyName(buffer);
                if (string.IsNullOrEmpty(keyname))
                {
                    throw ADP.ConnectionStringSyntax(index);
                }
                buffer.Length = 0;
                parserState = ParserState.KeyEnd;
                goto case ParserState.KeyEnd;
            case ParserState.KeyEnd:
                if (char.IsWhiteSpace(c))
                {
                    continue;
                }
                if (useOdbcRules)
                {
                    if ('{' == c)
                    {
                        parserState = ParserState.BraceQuoteValue;
                        goto IL_0248;
                    }
                }
                else
                {
                    if ('\'' == c)
                    {
                        parserState = ParserState.SingleQuoteValue;
                        continue;
                    }
                    if ('"' == c)
                    {
                        parserState = ParserState.DoubleQuoteValue;
                        continue;
                    }
                }
                if (';' == c || c == '\0')
                {
                    break;
                }
                if (char.IsControl(c))
                {
                    throw ADP.ConnectionStringSyntax(index);
                }
                parserState = ParserState.UnquotedValue;
                goto IL_0248;
            case ParserState.UnquotedValue:
                if (!char.IsWhiteSpace(c) && (char.IsControl(c) || ';' == c))
                {
                    break;
                }
                goto IL_0248;
            case ParserState.DoubleQuoteValue:
                if ('"' == c)
                {
                    parserState = ParserState.DoubleQuoteValueQuote;
                    continue;
                }
                if (c == '\0')
                {
                    throw ADP.ConnectionStringSyntax(index);
                }
                goto IL_0248;
            case ParserState.DoubleQuoteValueQuote:
                if ('"' == c)
                {
                    parserState = ParserState.DoubleQuoteValue;
                    goto IL_0248;
                }
                keyvalue = GetKeyValue(buffer, trimWhitespace: false);
                parserState = ParserState.QuotedValueEnd;
                goto case ParserState.QuotedValueEnd;
            case ParserState.SingleQuoteValue:
                if ('\'' == c)
                {
                    parserState = ParserState.SingleQuoteValueQuote;
                    continue;
                }
                if (c == '\0')
                {
                    throw ADP.ConnectionStringSyntax(index);
                }
                goto IL_0248;
            case ParserState.SingleQuoteValueQuote:
                if ('\'' == c)
                {
                    parserState = ParserState.SingleQuoteValue;
                    goto IL_0248;
                }
                keyvalue = GetKeyValue(buffer, trimWhitespace: false);
                parserState = ParserState.QuotedValueEnd;
                goto case ParserState.QuotedValueEnd;
            case ParserState.BraceQuoteValue:
                if ('}' == c)
                {
                    parserState = ParserState.BraceQuoteValueQuote;
                }
                else if (c == '\0')
                {
                    throw ADP.ConnectionStringSyntax(index);
                }
                goto IL_0248;
            case ParserState.BraceQuoteValueQuote:
                if ('}' == c)
                {
                    parserState = ParserState.BraceQuoteValue;
                    goto IL_0248;
                }
                keyvalue = GetKeyValue(buffer, trimWhitespace: false);
                parserState = ParserState.QuotedValueEnd;
                goto case ParserState.QuotedValueEnd;
            case ParserState.QuotedValueEnd:
                if (char.IsWhiteSpace(c))
                {
                    continue;
                }
                if (';' != c)
                {
                    if (c == '\0')
                    {
                        parserState = ParserState.NullTermination;
                        continue;
                    }
                    throw ADP.ConnectionStringSyntax(index);
                }
                break;
            case ParserState.NullTermination:
                if (c == '\0' || char.IsWhiteSpace(c))
                {
                    continue;
                }
                throw ADP.ConnectionStringSyntax(currentPosition);
            default:
                {
                    throw ADP.InternalError(ADP.InternalErrorCode.InvalidParserState1);
                }
                IL_0248:
                buffer.Append(c);
                continue;
            }
            break;
        }
        switch (parserState)
        {
        case ParserState.Key:
        case ParserState.DoubleQuoteValue:
        case ParserState.SingleQuoteValue:
        case ParserState.BraceQuoteValue:
            throw ADP.ConnectionStringSyntax(index);
        case ParserState.KeyEqual:
            keyname = GetKeyName(buffer);
            if (string.IsNullOrEmpty(keyname))
            {
                throw ADP.ConnectionStringSyntax(index);
            }
            break;
        case ParserState.UnquotedValue:
        {
            keyvalue = GetKeyValue(buffer, trimWhitespace: true);
            char c2 = keyvalue[keyvalue.Length - 1];
            if (!useOdbcRules && ('\'' == c2 || '"' == c2))
            {
                throw ADP.ConnectionStringSyntax(index);
            }
            break;
        }
        case ParserState.DoubleQuoteValueQuote:
        case ParserState.SingleQuoteValueQuote:
        case ParserState.BraceQuoteValueQuote:
        case ParserState.QuotedValueEnd:
            keyvalue = GetKeyValue(buffer, trimWhitespace: false);
            break;
        default:
            throw ADP.InternalError(ADP.InternalErrorCode.InvalidParserState2);
        case ParserState.NothingYet:
        case ParserState.KeyEnd:
        case ParserState.NullTermination:
            break;
        }
        if (';' == c && currentPosition < connectionString.Length)
        {
            currentPosition++;
        }
        return currentPosition;
    }
References System.buffer, System.Data.Common.ADP.ConnectionStringSyntax(), System.Data.Common.DbConnectionOptions.GetKeyName(), System.Data.Common.DbConnectionOptions.GetKeyValue(), System.index, System.Data.Common.ADP.InternalError(), and System.length.
Referenced by System.Data.Common.DbConnectionOptions.ParseInternal().