Terraria: System.Net.Http.HttpContent.CopyToAsync
CopyToAsync() [4/4]
Task System.Net.Http.HttpContent.CopyToAsync (Stream stream, TransportContext? context, CancellationToken cancellationToken) inline inherited
Definition at line 472 of file HttpContent.cs.
    {
        CheckDisposed();
        if (stream == null)
        {
            throw new ArgumentNullException("stream");
        }
        try
        {
            return WaitAsync(InternalCopyToAsync(stream, context, cancellationToken));
        }
        catch (Exception ex) when (StreamCopyExceptionNeedsWrapping(ex))
        {
            return Task.FromException(GetStreamCopyException(ex));
        }
        static async Task WaitAsync(ValueTask copyTask)
        {
            try
            {
                await copyTask.ConfigureAwait(continueOnCapturedContext: false);
            }
            catch (Exception e) when (StreamCopyExceptionNeedsWrapping(e))
            {
                throw WrapStreamCopyException(e);
            }
        }
    }
References System.cancellationToken, System.Net.Http.HttpContent.CheckDisposed(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Threading.Tasks.Task< TResult >.FromException(), System.Net.Http.HttpContent.GetStreamCopyException(), System.Net.Http.HttpContent.InternalCopyToAsync(), System.stream, System.Net.Http.HttpContent.StreamCopyExceptionNeedsWrapping(), and System.Net.Http.HttpContent.WrapStreamCopyException().