Terraria: System.Security.AccessControl.ObjectAce.GetBinaryForm
GetBinaryForm()
override void System.Security.AccessControl.ObjectAce.GetBinaryForm (byte[] binaryForm, int offset) inline
Definition at line 227 of file ObjectAce.cs.
    {
        MarshalHeader(binaryForm, offset);
        int num = offset + 4;
        int num2 = 0;
        binaryForm[num] = (byte)base.AccessMask;
        binaryForm[num + 1] = (byte)(base.AccessMask >> 8);
        binaryForm[num + 2] = (byte)(base.AccessMask >> 16);
        binaryForm[num + 3] = (byte)(base.AccessMask >> 24);
        num2 += 4;
        binaryForm[num + num2] = (byte)ObjectAceFlags;
        binaryForm[num + num2 + 1] = (byte)((uint)ObjectAceFlags >> 8);
        binaryForm[num + num2 + 2] = (byte)((uint)ObjectAceFlags >> 16);
        binaryForm[num + num2 + 3] = (byte)((uint)ObjectAceFlags >> 24);
        num2 += 4;
        if ((ObjectAceFlags & ObjectAceFlags.ObjectAceTypePresent) != 0)
        {
            ObjectAceType.ToByteArray().CopyTo(binaryForm, num + num2);
            num2 += 16;
        }
        if ((ObjectAceFlags & ObjectAceFlags.InheritedObjectAceTypePresent) != 0)
        {
            InheritedObjectAceType.ToByteArray().CopyTo(binaryForm, num + num2);
            num2 += 16;
        }
        base.SecurityIdentifier.GetBinaryForm(binaryForm, num + num2);
        num2 += base.SecurityIdentifier.BinaryLength;
        if (GetOpaque() != null)
        {
            if (base.OpaqueLength > MaxOpaqueLengthInternal)
            {
                throw new InvalidOperationException();
            }
            GetOpaque().CopyTo(binaryForm, num + num2);
        }
    }
References System.Security.AccessControl.QualifiedAce.GetOpaque(), System.Security.AccessControl.ObjectAce.InheritedObjectAceType, System.Security.AccessControl.GenericAce.MarshalHeader(), System.Security.AccessControl.ObjectAce.MaxOpaqueLengthInternal, System.Security.AccessControl.ObjectAce.ObjectAceType, System.offset, and System.Guid.ToByteArray().