Terraria: System.Net.Http.HttpContent.TryReadAsStream
TryReadAsStream()
Stream System.Net.Http.HttpContent.TryReadAsStream () inline package inherited
Definition at line 401 of file HttpContent.cs.
    {
        CheckDisposed();
        ArraySegment<byte> buffer;
        if (_contentReadStream == null)
        {
            return (Stream)(_contentReadStream = (TryGetBuffer(out buffer) ? new MemoryStream(buffer.Array, buffer.Offset, buffer.Count, writable: false) : TryCreateContentReadStream()));
        }
        if (_contentReadStream is Stream result)
        {
            return result;
        }
        Task<Stream> task = (Task<Stream>)_contentReadStream;
        if (task.Status != TaskStatus.RanToCompletion)
        {
            return null;
        }
        return task.Result;
    }
References System.Net.Http.HttpContent._contentReadStream, System.buffer, System.Net.Http.HttpContent.CheckDisposed(), System.task, System.Net.Http.HttpContent.TryCreateContentReadStream(), and System.Net.Http.HttpContent.TryGetBuffer().
Referenced by System.Net.Http.DecompressionHandler.DecompressedContent.CreateContentReadStreamAsyncCore(), System.Net.Http.HttpClient.GetByteArrayAsyncCore(), System.Net.Http.HttpClient.GetStreamAsyncCore(), System.Net.Http.HttpClient.GetStringAsyncCore(), and System.Net.Http.DecompressionHandler.DecompressedContent.TryCreateContentReadStream().