Terraria: System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRuleSpecific
RemoveAccessRuleSpecific() [1/2]
void System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRuleSpecific (AccessRule rule) inline protected inherited
Definition at line 368 of file CommonObjectSecurity.cs.
    {
        if (rule == null)
        {
            throw new ArgumentNullException("rule");
        }
        WriteLock();
        try
        {
            if (_securityDescriptor != null)
            {
                ModifyAccess(AccessControlModification.RemoveSpecific, rule, out var _);
            }
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().