Terraria: System.Net.Http.HttpContent.ReadBufferedContentAsString
ReadBufferedContentAsString()
string System.Net.Http.HttpContent.ReadBufferedContentAsString () inline private inherited
Definition at line 307 of file HttpContent.cs.
    {
        if (_bufferedContent.Length == 0L)
        {
            return string.Empty;
        }
        if (!TryGetBuffer(out var buffer))
        {
            buffer = new ArraySegment<byte>(_bufferedContent.ToArray());
        }
        return ReadBufferAsString(buffer, Headers);
    }
References System.Net.Http.HttpContent._bufferedContent, System.buffer, System.L, System.IO.MemoryStream.Length, System.Net.Http.HttpContent.ReadBufferAsString(), System.IO.MemoryStream.ToArray(), and System.Net.Http.HttpContent.TryGetBuffer().