Terraria: System.Net.Http.HttpContent.LoadIntoBufferAsyncCore
LoadIntoBufferAsyncCore()
async Task System.Net.Http.HttpContent.LoadIntoBufferAsyncCore (Task serializeToStreamTask, MemoryStream tempBuffer) inline private inherited
Definition at line 592 of file HttpContent.cs.
    {
        try
        {
            await serializeToStreamTask.ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception ex)
        {
            tempBuffer.Dispose();
            Exception streamCopyException = GetStreamCopyException(ex);
            if (streamCopyException != ex)
            {
                throw streamCopyException;
            }
            throw;
        }
        try
        {
            tempBuffer.Seek(0L, SeekOrigin.Begin);
            _bufferedContent = tempBuffer;
        }
        catch (Exception message)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, message, "LoadIntoBufferAsyncCore");
            }
            throw;
        }
    }
References System.Net.Http.HttpContent._bufferedContent, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.MemoryStream.Dispose(), System.Net.NetEventSource.Error(), System.Net.Http.HttpContent.GetStreamCopyException(), System.L, System.Net.NetEventSource.Log, and System.IO.MemoryStream.Seek().
Referenced by System.Net.Http.HttpContent.LoadIntoBufferAsync().