Terraria: System.Net.Http.HttpContent.CreateContentReadStreamAsync
CreateContentReadStreamAsync() [1/2]
virtual Task< Stream > System.Net.Http.HttpContent.CreateContentReadStreamAsync () inline protected virtual inherited
Reimplemented in System.Net.Http.ByteArrayContent, System.Net.Http.EmptyContent, System.Net.Http.HttpConnectionResponseContent, System.Net.Http.MultipartContent, System.Net.Http.ReadOnlyMemoryContent, and System.Net.Http.StreamContent.
Definition at line 629 of file HttpContent.cs.
    {
        return WaitAndReturnAsync(LoadIntoBufferAsync(), this, (Func<HttpContent, Stream>)((HttpContent s) => s._bufferedContent));
    }
References System.Net.Http.HttpContent.LoadIntoBufferAsync(), and System.s.
Referenced by System.Net.Http.HttpContent.CreateContentReadStreamAsync(), System.Net.Http.HttpContent.ReadAsStreamAsync(), and System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync().