Terraria: System.Security.AccessControl.CommonObjectSecurity.ModifyAccess
ModifyAccess()
override bool System.Security.AccessControl.CommonObjectSecurity.ModifyAccess (AccessControlModification modification, AccessRule rule, out bool modified) inline protected inherited
Definition at line 120 of file CommonObjectSecurity.cs.
    {
        if (rule == null)
        {
            throw new ArgumentNullException("rule");
        }
        WriteLock();
        try
        {
            bool flag = true;
            if (_securityDescriptor.DiscretionaryAcl == null)
            {
                if (modification == AccessControlModification.Remove || modification == AccessControlModification.RemoveAll || modification == AccessControlModification.RemoveSpecific)
                {
                    modified = false;
                    return flag;
                }
                _securityDescriptor.DiscretionaryAcl = new DiscretionaryAcl(base.IsContainer, base.IsDS, GenericAcl.AclRevision, 1);
                _securityDescriptor.AddControlFlags(ControlFlags.DiscretionaryAclPresent);
            }
            SecurityIdentifier sid = (SecurityIdentifier)rule.IdentityReference.Translate(typeof(SecurityIdentifier));
            if (rule.AccessControlType == AccessControlType.Allow)
            {
                switch (modification)
                {
                case AccessControlModification.Add:
                    _securityDescriptor.DiscretionaryAcl.AddAccess(AccessControlType.Allow, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                case AccessControlModification.Set:
                    _securityDescriptor.DiscretionaryAcl.SetAccess(AccessControlType.Allow, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                case AccessControlModification.Reset:
                    _securityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Deny, sid, -1, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None);
                    _securityDescriptor.DiscretionaryAcl.SetAccess(AccessControlType.Allow, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                case AccessControlModification.Remove:
                    flag = _securityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Allow, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                case AccessControlModification.RemoveAll:
                    flag = _securityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Allow, sid, -1, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None);
                    if (!flag)
                    {
                        throw new InvalidOperationException();
                    }
                    break;
                case AccessControlModification.RemoveSpecific:
                    _securityDescriptor.DiscretionaryAcl.RemoveAccessSpecific(AccessControlType.Allow, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                default:
                    throw new ArgumentOutOfRangeException("modification", System.SR.ArgumentOutOfRange_Enum);
                }
            }
            else
            {
                if (rule.AccessControlType != AccessControlType.Deny)
                {
                    throw new ArgumentException(System.SR.Format(System.SR.Arg_EnumIllegalVal, (int)rule.AccessControlType), "rule");
                }
                switch (modification)
                {
                case AccessControlModification.Add:
                    _securityDescriptor.DiscretionaryAcl.AddAccess(AccessControlType.Deny, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                case AccessControlModification.Set:
                    _securityDescriptor.DiscretionaryAcl.SetAccess(AccessControlType.Deny, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                case AccessControlModification.Reset:
                    _securityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Allow, sid, -1, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None);
                    _securityDescriptor.DiscretionaryAcl.SetAccess(AccessControlType.Deny, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                case AccessControlModification.Remove:
                    flag = _securityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Deny, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                case AccessControlModification.RemoveAll:
                    flag = _securityDescriptor.DiscretionaryAcl.RemoveAccess(AccessControlType.Deny, sid, -1, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None);
                    if (!flag)
                    {
                        throw new InvalidOperationException();
                    }
                    break;
                case AccessControlModification.RemoveSpecific:
                    _securityDescriptor.DiscretionaryAcl.RemoveAccessSpecific(AccessControlType.Deny, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                    break;
                default:
                    throw new ArgumentOutOfRangeException("modification", System.SR.ArgumentOutOfRange_Enum);
                }
            }
            modified = flag;
            base.AccessRulesModified |= modified;
            return flag;
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.AccessRule< T >.AccessControlType, System.Security.AccessControl.AuthorizationRule.AccessMask, System.Security.AccessControl.GenericAcl.AclRevision, System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.CommonSecurityDescriptor.AddControlFlags(), System.SR.Arg_EnumIllegalVal, System.SR.ArgumentOutOfRange_Enum, System.Security.AccessControl.CommonSecurityDescriptor.DiscretionaryAcl, System.Security.AccessControl.DiscretionaryAcl, System.SR.Format(), System.Security.AccessControl.AuthorizationRule.IdentityReference, System.Security.AccessControl.AuthorizationRule.InheritanceFlags, System.Security.AccessControl.AuthorizationRule.PropagationFlags, System.Security.AccessControl.DiscretionaryAcl.RemoveAccess(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), System.Security.Principal.IdentityReference.Translate(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().
Referenced by System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(), System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRule(), System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRuleAll(), System.Security.AccessControl.CommonObjectSecurity.RemoveAccessRuleSpecific(), System.Security.AccessControl.CommonObjectSecurity.ResetAccessRule(), and System.Security.AccessControl.CommonObjectSecurity.SetAccessRule().