Terraria: System.Net.Http.HttpContent.WrapStreamCopyException
WrapStreamCopyException()
static Exception System.Net.Http.HttpContent.WrapStreamCopyException (Exception e) inline static package inherited
Definition at line 759 of file HttpContent.cs.
    {
        return new HttpRequestException(System.SR.net_http_content_stream_copy_error, e);
    }
References System.SR.net_http_content_stream_copy_error.
Referenced by System.Net.Http.HttpContent.CopyToAsync(), System.Net.Http.HttpClient.GetByteArrayAsyncCore(), System.Net.Http.HttpContent.GetStreamCopyException(), and System.Net.Http.HttpClient.GetStringAsyncCore().