Terraria: System.Net.Http.HttpContent.LoadIntoBuffer
LoadIntoBuffer()
void System.Net.Http.HttpContent.LoadIntoBuffer (long maxBufferSize, CancellationToken cancellationToken) inline package inherited
Definition at line 511 of file HttpContent.cs.
    {
        CheckDisposed();
        if (!CreateTemporaryBuffer(maxBufferSize, out var tempBuffer, out var error))
        {
            return;
        }
        if (tempBuffer == null)
        {
            throw error;
        }
        CancellationTokenRegistration cancellationTokenRegistration = cancellationToken.Register(delegate(object s)
        {
            ((HttpContent)s).Dispose();
        }, this);
        try
        {
            SerializeToStream(tempBuffer, null, cancellationToken);
            tempBuffer.Seek(0L, SeekOrigin.Begin);
            _bufferedContent = tempBuffer;
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, ex, "LoadIntoBuffer");
            }
            if (CancellationHelper.ShouldWrapInOperationCanceledException(ex, cancellationToken))
            {
                throw CancellationHelper.CreateOperationCanceledException(ex, cancellationToken);
            }
            if (StreamCopyExceptionNeedsWrapping(ex))
            {
                throw GetStreamCopyException(ex);
            }
            throw;
        }
        finally
        {
            cancellationTokenRegistration.Dispose();
        }
    }
References System.Net.Http.HttpContent.HttpContent(), System.Net.Http.HttpContent._bufferedContent, System.cancellationToken, System.Net.Http.HttpContent.CheckDisposed(), System.Net.Http.CancellationHelper.CreateOperationCanceledException(), System.Net.Http.HttpContent.CreateTemporaryBuffer(), System.Threading.CancellationTokenRegistration.Dispose(), System.Net.NetEventSource.Error(), System.Net.Http.HttpContent.GetStreamCopyException(), System.L, System.Net.NetEventSource.Log, System.s, System.Net.Http.HttpContent.SerializeToStream(), System.Net.Http.CancellationHelper.ShouldWrapInOperationCanceledException(), and System.Net.Http.HttpContent.StreamCopyExceptionNeedsWrapping().
Referenced by System.Net.Http.HttpContent.CreateContentReadStream(), and System.Net.Http.HttpClient.Send().