Terraria: System.Security.AccessControl.CommonObjectSecurity.ModifyAudit
ModifyAudit()
override bool System.Security.AccessControl.CommonObjectSecurity.ModifyAudit (AccessControlModification modification, AuditRule rule, out bool modified) inline protected inherited
Definition at line 217 of file CommonObjectSecurity.cs.
    {
        if (rule == null)
        {
            throw new ArgumentNullException("rule");
        }
        WriteLock();
        try
        {
            bool flag = true;
            if (_securityDescriptor.SystemAcl == null)
            {
                if (modification == AccessControlModification.Remove || modification == AccessControlModification.RemoveAll || modification == AccessControlModification.RemoveSpecific)
                {
                    modified = false;
                    return flag;
                }
                _securityDescriptor.SystemAcl = new SystemAcl(base.IsContainer, base.IsDS, GenericAcl.AclRevision, 1);
                _securityDescriptor.AddControlFlags(ControlFlags.SystemAclPresent);
            }
            SecurityIdentifier sid = (SecurityIdentifier)rule.IdentityReference.Translate(typeof(SecurityIdentifier));
            switch (modification)
            {
            case AccessControlModification.Add:
                _securityDescriptor.SystemAcl.AddAudit(rule.AuditFlags, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                break;
            case AccessControlModification.Set:
                _securityDescriptor.SystemAcl.SetAudit(rule.AuditFlags, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                break;
            case AccessControlModification.Reset:
                _securityDescriptor.SystemAcl.SetAudit(rule.AuditFlags, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                break;
            case AccessControlModification.Remove:
                flag = _securityDescriptor.SystemAcl.RemoveAudit(rule.AuditFlags, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                break;
            case AccessControlModification.RemoveAll:
                flag = _securityDescriptor.SystemAcl.RemoveAudit(AuditFlags.Success | AuditFlags.Failure, sid, -1, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None);
                if (!flag)
                {
                    throw new InvalidOperationException();
                }
                break;
            case AccessControlModification.RemoveSpecific:
                _securityDescriptor.SystemAcl.RemoveAuditSpecific(rule.AuditFlags, sid, rule.AccessMask, rule.InheritanceFlags, rule.PropagationFlags);
                break;
            default:
                throw new ArgumentOutOfRangeException("modification", System.SR.ArgumentOutOfRange_Enum);
            }
            modified = flag;
            base.AuditRulesModified |= modified;
            return flag;
        }
        finally
        {
            WriteUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.AuthorizationRule.AccessMask, System.Security.AccessControl.GenericAcl.AclRevision, System.Security.AccessControl.SystemAcl.AddAudit(), System.Security.AccessControl.CommonSecurityDescriptor.AddControlFlags(), System.SR.ArgumentOutOfRange_Enum, System.Security.AccessControl.AuditRule< T >.AuditFlags, System.Security.AccessControl.AuthorizationRule.IdentityReference, System.Security.AccessControl.AuthorizationRule.InheritanceFlags, System.Security.AccessControl.AuthorizationRule.PropagationFlags, System.Security.AccessControl.SystemAcl.RemoveAudit(), System.Security.AccessControl.SystemAcl.RemoveAuditSpecific(), System.Security.AccessControl.SystemAcl.SetAudit(), System.Security.AccessControl.CommonSecurityDescriptor.SystemAcl, System.Security.AccessControl.SystemAcl, System.Security.Principal.IdentityReference.Translate(), System.Security.AccessControl.ObjectSecurity< T >.WriteLock(), and System.Security.AccessControl.ObjectSecurity< T >.WriteUnlock().
Referenced by System.Security.AccessControl.CommonObjectSecurity.AddAuditRule(), System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRule(), System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRuleAll(), System.Security.AccessControl.CommonObjectSecurity.RemoveAuditRuleSpecific(), and System.Security.AccessControl.CommonObjectSecurity.SetAuditRule().