Terraria: System.Net.Http.HttpContent.ReadAsStreamAsync
ReadAsStreamAsync() [2/2]
Task< Stream > System.Net.Http.HttpContent.ReadAsStreamAsync (CancellationToken cancellationToken) inline inherited
Definition at line 386 of file HttpContent.cs.
    {
        CheckDisposed();
        ArraySegment<byte> buffer;
        if (_contentReadStream == null)
        {
            return (Task<Stream>)(_contentReadStream = (TryGetBuffer(out buffer) ? ((Task)Task.FromResult((Stream)new MemoryStream(buffer.Array, buffer.Offset, buffer.Count, writable: false))) : ((Task)CreateContentReadStreamAsync(cancellationToken))));
        }
        if (_contentReadStream is Task<Stream> result)
        {
            return result;
        }
        return (Task<Stream>)(_contentReadStream = Task.FromResult((Stream)_contentReadStream));
    }
References System.Net.Http.HttpContent._contentReadStream, System.buffer, System.cancellationToken, System.Net.Http.HttpContent.CheckDisposed(), System.Net.Http.HttpContent.CreateContentReadStreamAsync(), and System.Net.Http.HttpContent.TryGetBuffer().