Terraria: System.Security.AccessControl.CommonObjectSecurity.GetRules
GetRules()
AuthorizationRuleCollection System.Security.AccessControl.CommonObjectSecurity.GetRules (bool access, bool includeExplicit, bool includeInherited, Type targetType) inline private inherited
Definition at line 31 of file CommonObjectSecurity.cs.
    {
        ReadLock();
        try
        {
            AuthorizationRuleCollection authorizationRuleCollection = new AuthorizationRuleCollection();
            if (!IsValidTargetTypeStatic(targetType))
            {
                throw new ArgumentException(System.SR.Arg_MustBeIdentityReferenceType, "targetType");
            }
            CommonAcl commonAcl = null;
            if (access)
            {
                if ((_securityDescriptor.ControlFlags & ControlFlags.DiscretionaryAclPresent) != 0)
                {
                    commonAcl = _securityDescriptor.DiscretionaryAcl;
                }
            }
            else if ((_securityDescriptor.ControlFlags & ControlFlags.SystemAclPresent) != 0)
            {
                commonAcl = _securityDescriptor.SystemAcl;
            }
            if (commonAcl == null)
            {
                return authorizationRuleCollection;
            }
            IdentityReferenceCollection identityReferenceCollection = null;
            if (targetType != typeof(SecurityIdentifier))
            {
                IdentityReferenceCollection identityReferenceCollection2 = new IdentityReferenceCollection(commonAcl.Count);
                for (int i = 0; i < commonAcl.Count; i++)
                {
                    CommonAce commonAce = commonAcl[i] as CommonAce;
                    if (AceNeedsTranslation(commonAce, access, includeExplicit, includeInherited))
                    {
                        identityReferenceCollection2.Add(commonAce.SecurityIdentifier);
                    }
                }
                identityReferenceCollection = identityReferenceCollection2.Translate(targetType);
            }
            int num = 0;
            for (int j = 0; j < commonAcl.Count; j++)
            {
                CommonAce commonAce2 = commonAcl[j] as CommonAce;
                if (AceNeedsTranslation(commonAce2, access, includeExplicit, includeInherited))
                {
                    IdentityReference identityReference = ((targetType == typeof(SecurityIdentifier)) ? commonAce2.SecurityIdentifier : identityReferenceCollection[num++]);
                    if (access)
                    {
                        authorizationRuleCollection.AddRule(AccessRuleFactory(type: (commonAce2.AceQualifier != 0) ? AccessControlType.Deny : AccessControlType.Allow, identityReference: identityReference, accessMask: commonAce2.AccessMask, isInherited: commonAce2.IsInherited, inheritanceFlags: commonAce2.InheritanceFlags, propagationFlags: commonAce2.PropagationFlags));
                    }
                    else
                    {
                        authorizationRuleCollection.AddRule(AuditRuleFactory(identityReference, commonAce2.AccessMask, commonAce2.IsInherited, commonAce2.InheritanceFlags, commonAce2.PropagationFlags, commonAce2.AuditFlags));
                    }
                }
            }
            return authorizationRuleCollection;
        }
        finally
        {
            ReadUnlock();
        }
    }
References System.Security.AccessControl.ObjectSecurity< T >._securityDescriptor, System.Security.AccessControl.KnownAce.AccessMask, System.Security.AccessControl.ObjectSecurity< T >.AccessRuleFactory(), System.Security.AccessControl.CommonObjectSecurity.AceNeedsTranslation(), System.Security.Principal.IdentityReferenceCollection.Add(), System.Security.AccessControl.AuthorizationRuleCollection.AddRule(), System.SR.Arg_MustBeIdentityReferenceType, System.Security.AccessControl.GenericAce.AuditFlags, System.Security.AccessControl.ObjectSecurity< T >.AuditRuleFactory(), System.Security.AccessControl.CommonSecurityDescriptor.ControlFlags, System.Security.AccessControl.CommonAcl.Count, System.Security.AccessControl.CommonSecurityDescriptor.DiscretionaryAcl, System.Security.AccessControl.GenericAce.InheritanceFlags, System.Security.AccessControl.GenericAce.IsInherited, System.Security.AccessControl.CommonObjectSecurity.IsValidTargetTypeStatic(), System.Security.AccessControl.GenericAce.PropagationFlags, System.Security.AccessControl.ObjectSecurity< T >.ReadLock(), System.Security.AccessControl.ObjectSecurity< T >.ReadUnlock(), System.Security.AccessControl.KnownAce.SecurityIdentifier, System.Security.AccessControl.CommonSecurityDescriptor.SystemAcl, System.Security.Principal.IdentityReferenceCollection.Translate(), and System.type.
Referenced by System.Security.AccessControl.CommonObjectSecurity.GetAccessRules(), and System.Security.AccessControl.CommonObjectSecurity.GetAuditRules().