Terraria: System.Net.Http.HttpContent.ReadAsStream
ReadAsStream() [1/2]
Stream System.Net.Http.HttpContent.ReadAsStream () inline inherited
Definition at line 361 of file HttpContent.cs.
    {
        return ReadAsStream(CancellationToken.None);
    }
References System.Threading.CancellationToken.None, and System.Net.Http.HttpContent.ReadAsStream().
Referenced by System.Net.Http.DecompressionHandler.DecompressedContent.CreateContentReadStreamAsyncCore(), System.Net.HttpWebResponse.GetResponseStream(), and System.Net.Http.HttpContent.ReadAsStream().