Terraria: System.Net.Http.HttpContent.Dispose
Dispose() [2/2]
virtual void System.Net.Http.HttpContent.Dispose (bool disposing) inline protected virtual inherited
Reimplemented in System.Net.Http.DecompressionHandler.DecompressedContent, System.Net.Http.HttpConnectionResponseContent, System.Net.Http.MultipartContent, and System.Net.Http.StreamContent.
Definition at line 697 of file HttpContent.cs.
    {
        if (disposing && !_disposed)
        {
            _disposed = true;
            if (_contentReadStream != null)
            {
                ((_contentReadStream as Stream) ?? ((_contentReadStream is Task<Stream> { Status: TaskStatus.RanToCompletion } task) ? task.Result : null))?.Dispose();
                _contentReadStream = null;
            }
            if (IsBuffered)
            {
                _bufferedContent.Dispose();
            }
        }
    }
References System.Net.Http.HttpContent._bufferedContent, System.Net.Http.HttpContent._contentReadStream, System.Net.Http.HttpContent._disposed, System.IO.MemoryStream.Dispose(), System.Net.Http.HttpContent.IsBuffered, and System.task.
Referenced by System.Net.Http.DecompressionHandler.DecompressedContent.Dispose(), System.Net.Http.HttpRequestMessage.Dispose(), and System.Net.Http.HttpResponseMessage.Dispose().