Terraria: System.Net.Http.HttpContent.ReadBufferAsString
ReadBufferAsString()
static string System.Net.Http.HttpContent.ReadBufferAsString (ArraySegment< byte > buffer, HttpContentHeaders headers) inline static package inherited
Definition at line 320 of file HttpContent.cs.
    {
        Encoding encoding = null;
        int preambleLength = -1;
        string text = headers.ContentType?.CharSet;
        if (text != null)
        {
            try
            {
                encoding = ((text.Length <= 2 || text[0] != '"' || text[text.Length - 1] != '"') ? Encoding.GetEncoding(text) : Encoding.GetEncoding(text.Substring(1, text.Length - 2)));
                preambleLength = GetPreambleLength(buffer, encoding);
            }
            catch (ArgumentException innerException)
            {
                throw new InvalidOperationException(System.SR.net_http_content_invalid_charset, innerException);
            }
        }
        if (encoding == null && !TryDetectEncoding(buffer, out encoding, out preambleLength))
        {
            encoding = DefaultStringEncoding;
            preambleLength = 0;
        }
        return encoding.GetString(buffer.Array, buffer.Offset + preambleLength, buffer.Count - preambleLength);
    }
References System.buffer, System.Net.Http.Headers.MediaTypeHeaderValue.CharSet, System.Net.Http.Headers.HttpContentHeaders.ContentType, System.Net.Http.HttpContent.DefaultStringEncoding, System.Text.Encoding.GetEncoding(), System.Net.Http.HttpContent.GetPreambleLength(), System.Text.Encoding.GetString(), System.SR.net_http_content_invalid_charset, System.text, and System.Net.Http.HttpContent.TryDetectEncoding().
Referenced by System.Net.Http.HttpClient.GetStringAsyncCore(), and System.Net.Http.HttpContent.ReadBufferedContentAsString().