Terraria: System.Security.AccessControl.ObjectAce.ParseBinaryForm
ParseBinaryForm()
static bool System.Security.AccessControl.ObjectAce.ParseBinaryForm (byte[] binaryForm, int offset, out AceQualifier qualifier, out int accessMask, [NotNullWhen(true)] out SecurityIdentifier sid, out ObjectAceFlags objectFlags, out Guid objectAceType, out Guid inheritedObjectAceType, out bool isCallback, out byte[] opaque) inline static package
Definition at line 107 of file ObjectAce.cs.
    {
        byte[] array = new byte[16];
        GenericAce.VerifyHeader(binaryForm, offset);
        if (binaryForm.Length - offset >= 12 + System.Security.Principal.SecurityIdentifier.MinBinaryLength)
        {
            AceType aceType = (AceType)binaryForm[offset];
            if (aceType == AceType.AccessAllowedObject || aceType == AceType.AccessDeniedObject || aceType == AceType.SystemAuditObject || aceType == AceType.SystemAlarmObject)
            {
                isCallback = false;
            }
            else
            {
                if (aceType != AceType.AccessAllowedCallbackObject && aceType != AceType.AccessDeniedCallbackObject && aceType != AceType.SystemAuditCallbackObject && aceType != AceType.SystemAlarmCallbackObject)
                {
                    goto IL_0209;
                }
                isCallback = true;
            }
            if (aceType == AceType.AccessAllowedObject || aceType == AceType.AccessAllowedCallbackObject)
            {
                qualifier = AceQualifier.AccessAllowed;
            }
            else if (aceType == AceType.AccessDeniedObject || aceType == AceType.AccessDeniedCallbackObject)
            {
                qualifier = AceQualifier.AccessDenied;
            }
            else if (aceType == AceType.SystemAuditObject || aceType == AceType.SystemAuditCallbackObject)
            {
                qualifier = AceQualifier.SystemAudit;
            }
            else
            {
                if (aceType != AceType.SystemAlarmObject && aceType != AceType.SystemAlarmCallbackObject)
                {
                    goto IL_0209;
                }
                qualifier = AceQualifier.SystemAlarm;
            }
            int num = offset + 4;
            int num2 = 0;
            accessMask = binaryForm[num] + (binaryForm[num + 1] << 8) + (binaryForm[num + 2] << 16) + (binaryForm[num + 3] << 24);
            num2 += 4;
            objectFlags = (ObjectAceFlags)(binaryForm[num + num2] + (binaryForm[num + num2 + 1] << 8) + (binaryForm[num + num2 + 2] << 16) + (binaryForm[num + num2 + 3] << 24));
            num2 += 4;
            if ((objectFlags & ObjectAceFlags.ObjectAceTypePresent) != 0)
            {
                for (int i = 0; i < 16; i++)
                {
                    array[i] = binaryForm[num + num2 + i];
                }
                num2 += 16;
            }
            else
            {
                for (int j = 0; j < 16; j++)
                {
                    array[j] = 0;
                }
            }
            objectAceType = new Guid(array);
            if ((objectFlags & ObjectAceFlags.InheritedObjectAceTypePresent) != 0)
            {
                for (int k = 0; k < 16; k++)
                {
                    array[k] = binaryForm[num + num2 + k];
                }
                num2 += 16;
            }
            else
            {
                for (int l = 0; l < 16; l++)
                {
                    array[l] = 0;
                }
            }
            inheritedObjectAceType = new Guid(array);
            sid = new SecurityIdentifier(binaryForm, num + num2);
            opaque = null;
            int num3 = (binaryForm[offset + 3] << 8) + binaryForm[offset + 2];
            if (num3 % 4 == 0)
            {
                int num4 = num3 - 4 - 4 - 4 - (byte)sid.BinaryLength;
                if ((objectFlags & ObjectAceFlags.ObjectAceTypePresent) != 0)
                {
                    num4 -= 16;
                }
                if ((objectFlags & ObjectAceFlags.InheritedObjectAceTypePresent) != 0)
                {
                    num4 -= 16;
                }
                if (num4 > 0)
                {
                    opaque = new byte[num4];
                    for (int m = 0; m < num4; m++)
                    {
                        opaque[m] = binaryForm[offset + num3 - num4 + m];
                    }
                }
                return true;
            }
        }
        goto IL_0209;
        IL_0209:
        qualifier = AceQualifier.AccessAllowed;
        accessMask = 0;
        sid = null;
        objectFlags = ObjectAceFlags.None;
        objectAceType = Guid.NewGuid();
        inheritedObjectAceType = Guid.NewGuid();
        isCallback = false;
        opaque = null;
        return false;
    }
References System.array, System.Security.Principal.SecurityIdentifier.MinBinaryLength, System.Guid.NewGuid(), System.Security.AccessControl.ObjectAce.ObjectAceFlags, System.offset, System.Security.AccessControl.KnownAce.SecurityIdentifier, and System.Security.AccessControl.GenericAce.VerifyHeader().
Referenced by System.Security.AccessControl.GenericAce.CreateFromBinaryForm().