Terraria: Terraria.Chat.Commands.SayChatCommand.ProcessIncomingMessage
ProcessIncomingMessage()
void Terraria.Chat.Commands.SayChatCommand.ProcessIncomingMessage (string text, byte clientId) inline
Implements Terraria.Chat.Commands.IChatCommand.
Definition at line 9 of file SayChatCommand.cs.
    {
        ChatHelper.BroadcastChatMessageAs(clientId, NetworkText.FromLiteral(text), Main.player[clientId].ChatColor());
        if (Main.dedServ)
        {
            Console.WriteLine("<{0}> {1}", Main.player[clientId].name, text);
        }
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessageAs(), Terraria.Player.ChatColor(), Terraria.Main.dedServ, Terraria.Localization.NetworkText.FromLiteral(), Terraria.Player.name, and Terraria.Main.player.