Terraria: System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveNext
MoveNext()
IteratorResult System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveNext (XPathNavigator input) inline
Definition at line 34 of file XPathFollowingMergeIterator.cs.
    {
        switch (_state)
        {
        case IteratorState.NeedCandidateCurrent:
            if (input == null)
            {
                return IteratorResult.NoMoreNodes;
            }
            _navCurrent = XmlQueryRuntime.SyncToNavigator(_navCurrent, input);
            _state = IteratorState.HaveCandidateCurrent;
            return IteratorResult.NeedInputNode;
        case IteratorState.HaveCandidateCurrent:
            if (input == null)
            {
                _state = IteratorState.HaveCurrentNoNext;
                return MoveFirst();
            }
            if (_navCurrent.IsDescendant(input))
            {
                goto case IteratorState.NeedCandidateCurrent;
            }
            _state = IteratorState.HaveCurrentNeedNext;
            goto case IteratorState.HaveCurrentNeedNext;
        case IteratorState.HaveCurrentNeedNext:
            if (input == null)
            {
                _state = IteratorState.HaveCurrentNoNext;
                return MoveFirst();
            }
            if (_navCurrent.ComparePosition(input) != XmlNodeOrder.Unknown)
            {
                return IteratorResult.NeedInputNode;
            }
            _navNext = XmlQueryRuntime.SyncToNavigator(_navNext, input);
            _state = IteratorState.HaveCurrentHaveNext;
            return MoveFirst();
        default:
            if (!_filter.MoveToFollowing(_navCurrent, null))
            {
                return MoveFailed();
            }
            return IteratorResult.HaveCurrentNode;
        }
    }
References System.Xml.Xsl.Runtime.XPathFollowingMergeIterator._filter, System.Xml.Xsl.Runtime.XPathFollowingMergeIterator._navCurrent, System.Xml.Xsl.Runtime.XPathFollowingMergeIterator._navNext, System.Xml.Xsl.Runtime.XPathFollowingMergeIterator._state, System.Xml.XPath.XPathNavigator.ComparePosition(), System.input, System.Xml.XPath.XPathNavigator.IsDescendant(), System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveFailed(), System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveFirst(), System.Xml.Xsl.Runtime.XmlNavigatorFilter.MoveToFollowing(), and System.Xml.Xsl.Runtime.XmlQueryRuntime.SyncToNavigator().