Terraria: System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveFirst
MoveFirst()
IteratorResult System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveFirst () inline private
Definition at line 94 of file XPathFollowingMergeIterator.cs.
    {
        if (!XPathFollowingIterator.MoveFirst(_filter, _navCurrent))
        {
            return MoveFailed();
        }
        return IteratorResult.HaveCurrentNode;
    }
References System.Xml.Xsl.Runtime.XPathFollowingMergeIterator._filter, System.Xml.Xsl.Runtime.XPathFollowingMergeIterator._navCurrent, System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveFailed(), and System.Xml.Xsl.Runtime.XPathFollowingIterator.MoveFirst().
Referenced by System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveNext().