Terraria: System.Xml.Schema.XmlNumeric10Converter.ChangeType
ChangeType() [9/9]
override object System.Xml.Schema.XmlNumeric10Converter.ChangeType (string value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 314 of file XmlNumeric10Converter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.DecimalType)
        {
            return ToDecimal(value);
        }
        if (destinationType == XmlBaseConverter.Int32Type)
        {
            return ToInt32(value);
        }
        if (destinationType == XmlBaseConverter.Int64Type)
        {
            return ToInt64(value);
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            return value;
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            return new XmlAtomicValue(base.SchemaType, value);
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            return new XmlAtomicValue(base.SchemaType, value);
        }
        return ChangeTypeWildcardSource(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardSource(), System.Xml.Schema.XmlBaseConverter.DecimalType, System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.Int32Type, System.Xml.Schema.XmlBaseConverter.Int64Type, System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlNumeric10Converter.ToDecimal(), System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XmlBaseConverter.XPathItemType.