Terraria: System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardSource
ChangeTypeWildcardSource()
object System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardSource (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline private
Definition at line 513 of file XmlNumeric10Converter.cs.
    {
        if (destinationType == XmlBaseConverter.ByteType)
        {
            return XmlBaseConverter.Int32ToByte(ToInt32(value));
        }
        if (destinationType == XmlBaseConverter.Int16Type)
        {
            return XmlBaseConverter.Int32ToInt16(ToInt32(value));
        }
        if (destinationType == XmlBaseConverter.SByteType)
        {
            return XmlBaseConverter.Int32ToSByte(ToInt32(value));
        }
        if (destinationType == XmlBaseConverter.UInt16Type)
        {
            return XmlBaseConverter.Int32ToUInt16(ToInt32(value));
        }
        if (destinationType == XmlBaseConverter.UInt32Type)
        {
            return XmlBaseConverter.Int64ToUInt32(ToInt64(value));
        }
        if (destinationType == XmlBaseConverter.UInt64Type)
        {
            return XmlBaseConverter.DecimalToUInt64(ToDecimal(value));
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.ByteType, System.Xml.Schema.XmlBaseConverter.ChangeListType(), System.Xml.Schema.XmlBaseConverter.DecimalToUInt64(), System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.Int16Type, System.Xml.Schema.XmlBaseConverter.Int32ToByte(), System.Xml.Schema.XmlBaseConverter.Int32ToInt16(), System.Xml.Schema.XmlBaseConverter.Int32ToSByte(), System.Xml.Schema.XmlBaseConverter.Int32ToUInt16(), System.Xml.Schema.XmlBaseConverter.Int64ToUInt32(), System.Xml.Schema.XmlBaseConverter.SByteType, System.Xml.Schema.XmlNumeric10Converter.ToDecimal(), System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), System.Xml.Schema.XmlBaseConverter.UInt16Type, System.Xml.Schema.XmlBaseConverter.UInt32Type, System.Xml.Schema.XmlBaseConverter.UInt64Type, and System.value.
Referenced by System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), and System.Xml.Schema.XmlNumeric10Converter.ChangeType().