Terraria: System.Threading.CancellationTokenSource.Cancel
Cancel() [1/2]
void System.Threading.CancellationTokenSource.Cancel () inline inherited
Definition at line 362 of file CancellationTokenSource.cs.
    {
        Cancel(throwOnFirstException: false);
    }
References System.Threading.CancellationTokenSource.Cancel().
Referenced by System.Net.HttpWebRequest.Abort(), System.Net.WebSockets.WebSocketHandle.Abort(), System.Threading.CancellationTokenSource.Cancel(), System.Net.Http.HttpClient.CancelPendingRequests(), System.Collections.Concurrent.BlockingCollection< T >.CancelWaitingConsumers(), System.Collections.Concurrent.BlockingCollection< T >.CancelWaitingProducers(), System.Threading.Tasks.Dataflow.DataflowBlock.ReceiveTarget< T >.CleanupAndComplete(), System.Diagnostics.Metrics.AggregationManager.Dispose(), System.Diagnostics.AsyncStreamReader.Dispose(), System.Linq.Parallel.QueryOpeningEnumerator< TOutput >.Dispose(), System.Net.Http.HttpConnectionPool.Dispose(), System.Net.Http.HttpClient.Dispose(), System.Threading.Tasks.Parallel.ForEachAsyncState< TSource >.RecordException(), Terraria.Social.WeGame.IPCBase.Reset(), and ReLogic.Threading.AsyncActionDispatcher.Stop().