Terraria: System.Xml.Schema.XmlNumeric10Converter.ToInt32
ToInt32() [5/6]
override int System.Xml.Schema.XmlNumeric10Converter.ToInt32 (object value) inline
Definition at line 76 of file XmlNumeric10Converter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        Type type = value.GetType();
        if (type == XmlBaseConverter.DecimalType)
        {
            return XmlBaseConverter.DecimalToInt32((decimal)value);
        }
        if (type == XmlBaseConverter.Int32Type)
        {
            return (int)value;
        }
        if (type == XmlBaseConverter.Int64Type)
        {
            return XmlBaseConverter.Int64ToInt32((long)value);
        }
        if (type == XmlBaseConverter.StringType)
        {
            return ToInt32((string)value);
        }
        if (type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAsInt;
        }
        return (int)ChangeTypeWildcardDestination(value, XmlBaseConverter.Int32Type, null);
    }
References System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlBaseConverter.DecimalToInt32(), System.Xml.Schema.XmlBaseConverter.DecimalType, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.Int32Type, System.Xml.Schema.XmlBaseConverter.Int64ToInt32(), System.Xml.Schema.XmlBaseConverter.Int64Type, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.type, System.value, and System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType.