Terraria: System.Runtime.CompilerServices.ContractHelper.GetFailureMessage
GetFailureMessage()
static string System.Runtime.CompilerServices.ContractHelper.GetFailureMessage (ContractFailureKind failureKind, string conditionText) inline static private
Definition at line 69 of file ContractHelper.cs.
    {
        bool flag = !string.IsNullOrEmpty(conditionText);
        switch (failureKind)
        {
        case ContractFailureKind.Assert:
            if (!flag)
            {
                return SR.AssertionFailed;
            }
            return SR.Format(SR.AssertionFailed_Cnd, conditionText);
        case ContractFailureKind.Assume:
            if (!flag)
            {
                return SR.AssumptionFailed;
            }
            return SR.Format(SR.AssumptionFailed_Cnd, conditionText);
        case ContractFailureKind.Precondition:
            if (!flag)
            {
                return SR.PreconditionFailed;
            }
            return SR.Format(SR.PreconditionFailed_Cnd, conditionText);
        case ContractFailureKind.Postcondition:
            if (!flag)
            {
                return SR.PostconditionFailed;
            }
            return SR.Format(SR.PostconditionFailed_Cnd, conditionText);
        case ContractFailureKind.Invariant:
            if (!flag)
            {
                return SR.InvariantFailed;
            }
            return SR.Format(SR.InvariantFailed_Cnd, conditionText);
        case ContractFailureKind.PostconditionOnException:
            if (!flag)
            {
                return SR.PostconditionOnExceptionFailed;
            }
            return SR.Format(SR.PostconditionOnExceptionFailed_Cnd, conditionText);
        default:
            Contract.Assume(condition: false, "Unreachable code");
            return SR.AssumptionFailed;
        }
    }
References System.SR.AssertionFailed, System.SR.AssertionFailed_Cnd, System.Diagnostics.Contracts.Contract.Assume(), System.SR.AssumptionFailed, System.SR.AssumptionFailed_Cnd, System.SR.Format(), System.SR.InvariantFailed, System.SR.InvariantFailed_Cnd, System.SR.PostconditionFailed, System.SR.PostconditionFailed_Cnd, System.SR.PostconditionOnExceptionFailed, System.SR.PostconditionOnExceptionFailed_Cnd, System.SR.PreconditionFailed, and System.SR.PreconditionFailed_Cnd.
Referenced by System.Runtime.CompilerServices.ContractHelper.GetDisplayMessage(), and System.Runtime.CompilerServices.ContractHelper.TriggerFailure().