Terraria: System.Threading.CancellationTokenSource.CreateLinkedTokenSource
CreateLinkedTokenSource() [2/3]
static CancellationTokenSource System.Threading.CancellationTokenSource.CreateLinkedTokenSource (CancellationToken token1, CancellationToken token2) inline static inherited
Definition at line 642 of file CancellationTokenSource.cs.
    {
        if (token1.CanBeCanceled)
        {
            if (!token2.CanBeCanceled)
            {
                return new Linked1CancellationTokenSource(token1);
            }
            return new Linked2CancellationTokenSource(token1, token2);
        }
        return CreateLinkedTokenSource(token2);
    }
References System.Threading.CancellationTokenSource.CreateLinkedTokenSource().
Referenced by System.Threading.Tasks.Dataflow.DataflowBlock.ChooseCoreByLinking< T1, T2, T3 >(), System.Net.WebSockets.WebSocketHandle.ConnectAsync(), System.Net.WebSockets.WebSocketBase.OutstandingOperationHelper.CreateLinkedCancellationToken(), System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Threading.CancellationTokenSource.CreateLinkedTokenSource(), System.Collections.Concurrent.BlockingCollection< T >.GetConsumingEnumerable(), System.Net.Http.Http3RequestStream.SendAsync(), System.Collections.Concurrent.BlockingCollection< T >.TryAddToAnyCore(), System.Collections.Concurrent.BlockingCollection< T >.TryAddWithNoTimeValidation(), System.Collections.Concurrent.BlockingCollection< T >.TryTakeFromAnyCoreSlow(), System.Collections.Concurrent.BlockingCollection< T >.TryTakeWithNoTimeValidation(), and System.Linq.Parallel.QuerySettings.WithPerExecutionSettings().