Terraria: System.Threading.CancellationTokenSource.Register
Register()
CancellationTokenRegistration System.Threading.CancellationTokenSource.Register (Delegate callback, object stateForCallback, SynchronizationContext syncContext, ExecutionContext executionContext) inline package inherited
Definition at line 480 of file CancellationTokenSource.cs.
    {
        if (!IsCancellationRequested)
        {
            if (_disposed)
            {
                return default(CancellationTokenRegistration);
            }
            Registrations registrations = Volatile.Read(ref _registrations);
            if (registrations == null)
            {
                registrations = new Registrations(this);
                registrations = Interlocked.CompareExchange(ref _registrations, registrations, null) ?? registrations;
            }
            CallbackNode callbackNode = null;
            long id = 0L;
            if (registrations.FreeNodeList != null)
            {
                registrations.EnterLock();
                try
                {
                    callbackNode = registrations.FreeNodeList;
                    if (callbackNode != null)
                    {
                        registrations.FreeNodeList = callbackNode.Next;
                        id = (callbackNode.Id = registrations.NextAvailableId++);
                        callbackNode.Callback = callback;
                        callbackNode.CallbackState = stateForCallback;
                        callbackNode.ExecutionContext = executionContext;
                        callbackNode.SynchronizationContext = syncContext;
                        callbackNode.Next = registrations.Callbacks;
                        registrations.Callbacks = callbackNode;
                        if (callbackNode.Next != null)
{
                            callbackNode.Next.Prev = callbackNode;
                        }
                    }
                }
                finally
                {
                    registrations.ExitLock();
                }
            }
            if (callbackNode == null)
            {
                callbackNode = new CallbackNode(registrations);
                callbackNode.Callback = callback;
                callbackNode.CallbackState = stateForCallback;
                callbackNode.ExecutionContext = executionContext;
                callbackNode.SynchronizationContext = syncContext;
                registrations.EnterLock();
                try
                {
                    id = (callbackNode.Id = registrations.NextAvailableId++);
                    callbackNode.Next = registrations.Callbacks;
                    if (callbackNode.Next != null)
                    {
                        callbackNode.Next.Prev = callbackNode;
                    }
                    registrations.Callbacks = callbackNode;
                }
                finally
                {
                    registrations.ExitLock();
                }
            }
            if (!IsCancellationRequested || !registrations.Unregister(id, callbackNode))
            {
                return new CancellationTokenRegistration(id, callbackNode);
            }
        }
        Invoke(callback, stateForCallback, this);
        return default(CancellationTokenRegistration);
    }
References System.Threading.CancellationTokenSource._disposed, System.Threading.CancellationTokenSource._registrations, System.Threading.Interlocked.CompareExchange(), System.Threading.CancellationTokenSource.Invoke(), System.Threading.CancellationTokenSource.IsCancellationRequested, System.L, and System.Threading.Volatile.Read().
Referenced by System.Threading.CancellationToken.Register().