Terraria: System.Xml.Schema.XmlNumeric10Converter.ToDecimal
ToDecimal() [2/2]
override decimal System.Xml.Schema.XmlNumeric10Converter.ToDecimal (string value) inline
Definition at line 15 of file XmlNumeric10Converter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (base.TypeCode == XmlTypeCode.Decimal)
        {
            return XmlConvert.ToDecimal(value);
        }
        return XmlConvert.ToInteger(value);
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.ToDecimal(), System.Xml.XmlConvert.ToInteger(), and System.value.
Referenced by System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardSource(), and System.Xml.Schema.XmlNumeric10Converter.ToDecimal().