Terraria: System.Xml.Schema.XmlNumeric10Converter.ChangeType
ChangeType() [8/9]
override object System.Xml.Schema.XmlNumeric10Converter.ChangeType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 355 of file XmlNumeric10Converter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        Type type = value.GetType();
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.DecimalType)
        {
            return ToDecimal(value);
        }
        if (destinationType == XmlBaseConverter.Int32Type)
        {
            return ToInt32(value);
        }
        if (destinationType == XmlBaseConverter.Int64Type)
        {
            return ToInt64(value);
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            return ToString(value, nsResolver);
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            if (type == XmlBaseConverter.DecimalType)
            {
                return new XmlAtomicValue(base.SchemaType, value);
            }
            if (type == XmlBaseConverter.Int32Type)
            {
                return new XmlAtomicValue(base.SchemaType, (int)value);
            }
            if (type == XmlBaseConverter.Int64Type)
            {
                return new XmlAtomicValue(base.SchemaType, (long)value);
            }
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            if (type == XmlBaseConverter.DecimalType)
            {
                return new XmlAtomicValue(base.SchemaType, value);
            }
            if (type == XmlBaseConverter.Int32Type)
            {
                return new XmlAtomicValue(base.SchemaType, (int)value);
            }
            if (type == XmlBaseConverter.Int64Type)
            {
                return new XmlAtomicValue(base.SchemaType, (long)value);
            }
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
        }
        if (destinationType == XmlBaseConverter.ByteType)
        {
            return XmlBaseConverter.Int32ToByte(ToInt32(value));
        }
        if (destinationType == XmlBaseConverter.Int16Type)
        {
            return XmlBaseConverter.Int32ToInt16(ToInt32(value));
        }
        if (destinationType == XmlBaseConverter.SByteType)
        {
            return XmlBaseConverter.Int32ToSByte(ToInt32(value));
        }
        if (destinationType == XmlBaseConverter.UInt16Type)
        {
            return XmlBaseConverter.Int32ToUInt16(ToInt32(value));
        }
        if (destinationType == XmlBaseConverter.UInt32Type)
        {
            return XmlBaseConverter.Int64ToUInt32(ToInt64(value));
        }
        if (destinationType == XmlBaseConverter.UInt64Type)
        {
            return XmlBaseConverter.DecimalToUInt64(ToDecimal(value));
        }
        if (type == XmlBaseConverter.ByteType)
        {
            return ChangeType((byte)value, destinationType);
        }
        if (type == XmlBaseConverter.Int16Type)
        {
            return ChangeType((short)value, destinationType);
        }
        if (type == XmlBaseConverter.SByteType)
        {
            return ChangeType((sbyte)value, destinationType);
        }
        if (type == XmlBaseConverter.UInt16Type)
        {
            return ChangeType((ushort)value, destinationType);
        }
        if (type == XmlBaseConverter.UInt32Type)
        {
            return ChangeType((uint)value, destinationType);
        }
        if (type == XmlBaseConverter.UInt64Type)
        {
            return ChangeType((decimal)(ulong)value, destinationType);
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.ByteType, System.Xml.Schema.XmlBaseConverter.ChangeListType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlBaseConverter.DecimalToUInt64(), System.Xml.Schema.XmlBaseConverter.DecimalType, System.Xml.Dictionary, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.Int16Type, System.Xml.Schema.XmlBaseConverter.Int32ToByte(), System.Xml.Schema.XmlBaseConverter.Int32ToInt16(), System.Xml.Schema.XmlBaseConverter.Int32ToSByte(), System.Xml.Schema.XmlBaseConverter.Int32ToUInt16(), System.Xml.Schema.XmlBaseConverter.Int32Type, System.Xml.Schema.XmlBaseConverter.Int64ToUInt32(), System.Xml.Schema.XmlBaseConverter.Int64Type, System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.SByteType, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlNumeric10Converter.ToDecimal(), System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), System.ToString, System.type, System.Xml.Schema.XmlBaseConverter.UInt16Type, System.Xml.Schema.XmlBaseConverter.UInt32Type, System.Xml.Schema.XmlBaseConverter.UInt64Type, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XmlBaseConverter.XPathItemType.