Terraria: System.Xml.Schema.XmlNumeric10Converter.ChangeType
ChangeType() [6/9]
override object System.Xml.Schema.XmlNumeric10Converter.ChangeType (long value, Type destinationType) inline
Definition at line 277 of file XmlNumeric10Converter.cs.
    {
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.DecimalType)
        {
            return (decimal)value;
        }
        if (destinationType == XmlBaseConverter.Int32Type)
        {
            return XmlBaseConverter.Int64ToInt32(value);
        }
        if (destinationType == XmlBaseConverter.Int64Type)
        {
            return value;
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            return XmlConvert.ToString(value);
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            return new XmlAtomicValue(base.SchemaType, value);
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            return new XmlAtomicValue(base.SchemaType, value);
        }
        return ChangeTypeWildcardSource(value, destinationType, null);
    }
References System.Xml.Schema.XmlNumeric10Converter.ChangeTypeWildcardSource(), System.Xml.Schema.XmlBaseConverter.DecimalType, System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.Int32Type, System.Xml.Schema.XmlBaseConverter.Int64ToInt32(), System.Xml.Schema.XmlBaseConverter.Int64Type, System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.XmlConvert.ToString(), System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XmlBaseConverter.XPathItemType.