Terraria: System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent
RaiseContractFailedEvent()
static ? string System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent (ContractFailureKind failureKind, string? userMessage, string? conditionText, Exception? innerException) inline static
Definition at line 12 of file ContractHelper.cs.
    {
        if (failureKind < ContractFailureKind.Precondition || failureKind > ContractFailureKind.Assume)
        {
            throw new ArgumentException(SR.Format(SR.Arg_EnumIllegalVal, failureKind), "failureKind");
        }
        string text = "contract failed.";
        ContractFailedEventArgs contractFailedEventArgs = null;
        string result;
        try
        {
            text = GetDisplayMessage(failureKind, userMessage, conditionText);
            EventHandler<ContractFailedEventArgs> internalContractFailed = ContractHelper.InternalContractFailed;
            if (internalContractFailed != null)
            {
                contractFailedEventArgs = new ContractFailedEventArgs(failureKind, text, conditionText, innerException);
                Delegate[] invocationList = internalContractFailed.GetInvocationList();
                for (int i = 0; i < invocationList.Length; i++)
                {
                    EventHandler<ContractFailedEventArgs> eventHandler = (EventHandler<ContractFailedEventArgs>)invocationList[i];
                    try
                    {
                        eventHandler(null, contractFailedEventArgs);
                    }
                    catch (Exception thrownDuringHandler)
                    {
                        contractFailedEventArgs.thrownDuringHandler = thrownDuringHandler;
                        contractFailedEventArgs.SetUnwind();
                    }
                }
                if (contractFailedEventArgs.Unwind)
                {
                    if (innerException == null)
                    {
                        innerException = contractFailedEventArgs.thrownDuringHandler;
                    }
                    throw new ContractException(failureKind, text, userMessage, conditionText, innerException);
                }
            }
        }
        finally
        {
            result = ((contractFailedEventArgs == null || !contractFailedEventArgs.Handled) ? text : null);
        }
        return result;
    }
References System.SR.Arg_EnumIllegalVal, System.SR.Format(), System.Runtime.CompilerServices.ContractHelper.GetDisplayMessage(), System.Diagnostics.Contracts.ContractFailedEventArgs.Handled, System.Runtime.CompilerServices.ContractHelper.InternalContractFailed, System.Diagnostics.Contracts.ContractFailedEventArgs.SetUnwind(), System.text, System.Diagnostics.Contracts.ContractFailedEventArgs.thrownDuringHandler, and System.Diagnostics.Contracts.ContractFailedEventArgs.Unwind.
Referenced by System.Diagnostics.Contracts.Contract.ReportFailure().