Terraria: System.Data.Common.SqlUdtStorage.Set
Set()
override void System.Data.Common.SqlUdtStorage.Set (int recordNo, object value) inline
Definition at line 105 of file SqlUdtStorage.cs.
    {
        if (DBNull.Value == value)
        {
            _values[recordNo] = _nullValue;
            SetNullBit(recordNo, flag: true);
        }
        else if (value == null)
        {
            if (_isValueType)
            {
                throw ExceptionBuilder.StorageSetFailed();
            }
            _values[recordNo] = _nullValue;
            SetNullBit(recordNo, flag: true);
        }
        else
        {
            if (!_dataType.IsInstanceOfType(value))
            {
                throw ExceptionBuilder.StorageSetFailed();
            }
            _values[recordNo] = value;
            SetNullBit(recordNo, flag: false);
        }
    }
References System.Data.Common.DataStorage._dataType, System.Data.Common.DataStorage._isValueType, System.Data.Common.DataStorage._nullValue, System.Data.Common.SqlUdtStorage._values, System.Xml.Dictionary, System.Type.IsInstanceOfType(), System.Data.Common.DataStorage.SetNullBit(), System.Data.ExceptionBuilder.StorageSetFailed(), System.DBNull.Value, and System.value.