Terraria: System.Data.AggregateNode.Eval
Eval() [2/3]
override object System.Data.AggregateNode.Eval (DataRow row, DataRowVersion version) inline package
Definition at line 148 of file AggregateNode.cs.
    {
        if (_childTable == null)
        {
            throw ExprException.AggregateUnbound(ToString());
        }
        DataRow[] array;
        if (_local)
        {
            array = new DataRow[_childTable.Rows.Count];
            _childTable.Rows.CopyTo(array, 0);
        }
        else
        {
            if (row == null)
            {
                throw ExprException.EvalNoContext();
            }
            if (_relation == null)
            {
                throw ExprException.AggregateUnbound(ToString());
            }
            array = row.GetChildRows(_relation, version);
        }
        if (version == DataRowVersion.Proposed)
        {
            version = DataRowVersion.Default;
        }
        List<int> list = new List<int>();
        for (int i = 0; i < array.Length; i++)
        {
            if (array[i].RowState == DataRowState.Deleted)
            {
                if (DataRowAction.Rollback != array[i]._action)
                {
                    continue;
                }
                version = DataRowVersion.Original;
            }
            else if (DataRowAction.Rollback == array[i]._action && array[i].RowState == DataRowState.Added)
            {
                continue;
            }
            if (version != DataRowVersion.Original || array[i]._oldRecord != -1)
            {
                list.Add(array[i].GetRecordFromVersion(version));
            }
        }
        int[] records = list.ToArray();
        return _column.GetAggregateValue(records, _type);
    }
References System.Data.AggregateNode._childTable, System.Data.AggregateNode._column, System.Data.AggregateNode._local, System.Data.AggregateNode._relation, System.Data.AggregateNode._type, System.Data.ExprException.AggregateUnbound(), System.array, System.Data.DataRowCollection.CopyTo(), System.Data.DataRowCollection.Count, System.Data.ExprException.EvalNoContext(), System.Data.DataColumn.GetAggregateValue(), System.list, System.Data.DataTable.Rows, and System.ToString.