Terraria: System.Data.AggregateNode.Eval
Eval() [3/3]
override object System.Data.AggregateNode.Eval (int[] records) inline package
Definition at line 201 of file AggregateNode.cs.
    {
        if (_childTable == null)
        {
            throw ExprException.AggregateUnbound(ToString());
        }
        if (!_local)
        {
            throw ExprException.ComputeNotAggregate(ToString());
        }
        return _column.GetAggregateValue(records, _type);
    }
References System.Data.AggregateNode._childTable, System.Data.AggregateNode._column, System.Data.AggregateNode._local, System.Data.AggregateNode._type, System.Data.ExprException.AggregateUnbound(), System.Data.ExprException.ComputeNotAggregate(), System.Data.DataColumn.GetAggregateValue(), and System.ToString.