Terraria: System.Data.AggregateNode.Bind
Bind() [2/2]
override void System.Data.AggregateNode.Bind (DataTable table, List< DataColumn > list) inline package
Definition at line 64 of file AggregateNode.cs.
    {
        BindTable(table);
        if (table == null)
        {
            throw ExprException.AggregateUnbound(ToString());
        }
        if (_local)
        {
            _relation = null;
        }
        else
        {
            DataRelationCollection childRelations = table.ChildRelations;
            if (_relationName == null)
            {
                if (childRelations.Count > 1)
                {
                    throw ExprException.UnresolvedRelation(table.TableName, ToString());
                }
                if (childRelations.Count != 1)
                {
                    throw ExprException.AggregateUnbound(ToString());
                }
                _relation = childRelations[0];
            }
            else
            {
                _relation = childRelations[_relationName];
            }
        }
        _childTable = ((_relation == null) ? table : _relation.ChildTable);
        _column = _childTable.Columns[_columnName];
        if (_column == null)
        {
            throw ExprException.UnboundName(_columnName);
        }
        int i;
        for (i = 0; i < list.Count; i++)
        {
            DataColumn dataColumn = list[i];
            if (_column == dataColumn)
            {
                break;
            }
        }
        if (i >= list.Count)
        {
            list.Add(_column);
        }
        Bind(_relation, list);
    }
References System.Data.AggregateNode._childTable, System.Data.AggregateNode._column, System.Data.AggregateNode._columnName, System.Data.AggregateNode._local, System.Data.AggregateNode._relation, System.Data.AggregateNode._relationName, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ExprException.AggregateUnbound(), System.Data.AggregateNode.Bind(), System.Data.ExpressionNode.BindTable(), System.Data.DataTable.ChildRelations, System.Data.DataRelation.ChildTable, System.Data.DataTable.Columns, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.list, System.Data.ExpressionNode.table, System.Data.DataTable.TableName, System.ToString, System.Data.ExprException.UnboundName(), and System.Data.ExprException.UnresolvedRelation().
Referenced by System.Data.AggregateNode.Bind(), and System.Data.LookupNode.Bind().