Terraria: System.Transactions.TransactionStateVolatilePhase1.EnterState
EnterState()
override void System.Transactions.TransactionStateVolatilePhase1.EnterState (InternalTransaction tx) inline package
Definition at line 5 of file TransactionStateVolatilePhase1.cs.
    {
        CommonEnterState(tx);
        tx._committableTransaction._complete = true;
        if (tx._phase1Volatiles._dependentClones != 0)
        {
            TransactionState.TransactionStateAborted.EnterState(tx);
        }
        else if (tx._phase1Volatiles._volatileEnlistmentCount == 1 && tx._durableEnlistment == null && tx._phase1Volatiles._volatileEnlistments[0].SinglePhaseNotification != null)
        {
            TransactionState.TransactionStateVolatileSPC.EnterState(tx);
        }
        else if (tx._phase1Volatiles._volatileEnlistmentCount > 0)
        {
            for (int i = 0; i < tx._phase1Volatiles._volatileEnlistmentCount; i++)
            {
                tx._phase1Volatiles._volatileEnlistments[i]._twoPhaseState.ChangeStatePreparing(tx._phase1Volatiles._volatileEnlistments[i]);
                if (!tx.State.ContinuePhase1Prepares())
                {
                    break;
                }
            }
        }
        else
        {
            TransactionState.TransactionStateSPC.EnterState(tx);
        }
    }
References System.Transactions.VolatileEnlistmentSet._dependentClones, System.Transactions.InternalTransaction._durableEnlistment, System.Transactions.InternalTransaction._phase1Volatiles, System.Transactions.InternalEnlistment._twoPhaseState, System.Transactions.VolatileEnlistmentSet._volatileEnlistmentCount, System.Transactions.VolatileEnlistmentSet._volatileEnlistments, System.Transactions.EnlistmentState.ChangeStatePreparing(), System.Transactions.TransactionState.CommonEnterState(), System.Transactions.TransactionState.ContinuePhase1Prepares(), System.Transactions.InternalEnlistment.SinglePhaseNotification, System.Transactions.InternalTransaction.State, System.Transactions.TransactionState.TransactionStateAborted, System.Transactions.TransactionState.TransactionStateSPC, and System.Transactions.TransactionState.TransactionStateVolatileSPC.