Terraria: System.Char.IsInRange
IsInRange() [1/2]
static bool System.Char.IsInRange (char c, char min, char max) inline static package
Definition at line 191 of file Char.cs.
    {
        return (uint)(c - min) <= (uint)(max - min);
    }
Referenced by System.Char.CheckLetter(), System.Char.CheckNumber(), System.Char.CheckPunctuation(), System.Char.CheckSeparator(), System.Char.CheckSymbol(), System.Char.IsDigit(), System.Char.IsDigit(), System.Char.IsHighSurrogate(), System.Char.IsLowSurrogate(), System.Char.IsNumber(), System.Char.IsNumber(), and System.Char.IsSurrogate().