Terraria: System.Char.IsSeparator
IsSeparator() [2/2]
static bool System.Char.IsSeparator (string s, int index) inline static
Definition at line 568 of file Char.cs.
    {
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        if ((uint)index >= (uint)s.Length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.index);
        }
        char c = s[index];
        if (IsLatin1(c))
        {
            return IsSeparatorLatin1(c);
        }
        return CheckSeparator(CharUnicodeInfo.GetUnicodeCategoryInternal(s, index));
    }
References System.Char.CheckSeparator(), System.Globalization.CharUnicodeInfo.GetUnicodeCategoryInternal(), System.index, System.Char.IsLatin1(), System.Char.IsSeparatorLatin1(), System.s, System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowArgumentOutOfRangeException().