Terraria: System.Char.GetLatin1UnicodeCategory
GetLatin1UnicodeCategory()
static UnicodeCategory System.Char.GetLatin1UnicodeCategory (char c) inline static private
Definition at line 79 of file Char.cs.
    {
        return (UnicodeCategory)(Latin1CharInfo[c] & 0x1F);
    }
References System.Char.Latin1CharInfo.
Referenced by System.Char.GetUnicodeCategory(), System.Char.GetUnicodeCategory(), System.Char.IsLetterOrDigit(), System.Char.IsLetterOrDigit(), System.Char.IsNumber(), System.Char.IsNumber(), System.Char.IsPunctuation(), System.Char.IsPunctuation(), System.Char.IsSymbol(), and System.Char.IsSymbol().