Terraria: System.Char.IsSeparator
IsSeparator() [1/2]
static bool System.Char.IsSeparator (char c) inline static
Definition at line 559 of file Char.cs.
    {
        if (IsLatin1(c))
        {
            return IsSeparatorLatin1(c);
        }
        return CheckSeparator(CharUnicodeInfo.GetUnicodeCategory(c));
    }
References System.Char.CheckSeparator(), System.Globalization.CharUnicodeInfo.GetUnicodeCategory(), System.Char.IsLatin1(), and System.Char.IsSeparatorLatin1().