Terraria: System.Char.IsNumber
IsNumber() [1/2]
static bool System.Char.IsNumber (char c) inline static
Definition at line 492 of file Char.cs.
    {
        if (IsLatin1(c))
        {
            if (IsAscii(c))
            {
                return IsInRange(c, '0', '9');
            }
            return CheckNumber(GetLatin1UnicodeCategory(c));
        }
        return CheckNumber(CharUnicodeInfo.GetUnicodeCategory(c));
    }
References System.Char.CheckNumber(), System.Char.GetLatin1UnicodeCategory(), System.Globalization.CharUnicodeInfo.GetUnicodeCategory(), System.Char.IsAscii(), System.Char.IsInRange(), and System.Char.IsLatin1().