Terraria: System.Math.Atan2
Atan2()
static double System.Math.Atan2 (double y, double x)
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_015_Flails_Old(), Terraria.Projectile.AI_016(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.Utils.AngleFrom(), Terraria.Entity.AngleFrom(), Terraria.Utils.AngleTo(), Terraria.Entity.AngleTo(), System.Double.Atan2(), Terraria.Collision.CheckAABBvLineCollision(), ReLogic.Graphics.BasicDebugDrawer.DrawLine(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCs(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_FlailChains_Old(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawSuperSpecialProjectiles(), Terraria.Main.DrawWOFRopeToTheHungry(), Terraria.Main.DrawWOFTongueToPlayer(), Terraria.NPC.FindFrame(), Terraria.Player.ItemCheck_Shoot(), Terraria.Projectile.Kill(), System.Numerics.Complex.Log(), Terraria.Rain.NewRain(), Terraria.Rain.NewRainForced(), System.Numerics.Complex.Pow(), Terraria.GameContent.RGB.PillarShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail(), Terraria.Utils.ToRotation(), Terraria.Minecart.TrackRotation(), and Terraria.GameContent.PortalHelper.TryPlacingPortal().