Terraria: System.Runtime.Versioning.FrameworkName.FrameworkName
FrameworkName() [3/3]
System.Runtime.Versioning.FrameworkName.FrameworkName (string frameworkName) inline
Definition at line 86 of file FrameworkName.cs.
    {
        if (frameworkName == null)
        {
            throw new ArgumentNullException("frameworkName");
        }
        if (frameworkName.Length == 0)
        {
            throw new ArgumentException(SR.Format(SR.net_emptystringcall, "frameworkName"), "frameworkName");
        }
        string[] array = frameworkName.Split(',');
        if (array.Length < 2 || array.Length > 3)
        {
            throw new ArgumentException(SR.Argument_FrameworkNameTooShort, "frameworkName");
        }
        _identifier = array[0].Trim();
        if (_identifier.Length == 0)
        {
            throw new ArgumentException(SR.Argument_FrameworkNameInvalid, "frameworkName");
        }
        bool flag = false;
        _profile = string.Empty;
        for (int i = 1; i < array.Length; i++)
        {
            string text = array[i];
            int num = text.IndexOf('=');
            if (num == -1 || num != text.LastIndexOf('='))
            {
                throw new ArgumentException(SR.Argument_FrameworkNameInvalid, "frameworkName");
            }
            ReadOnlySpan<char> span = text.AsSpan(0, num).Trim();
            ReadOnlySpan<char> input = text.AsSpan(num + 1).Trim();
            if (MemoryExtensions.Equals(span, "Version", StringComparison.OrdinalIgnoreCase))
            {
                flag = true;
                if (input.Length > 0 && (input[0] == 'v' || input[0] == 'V'))
                {
                    input = input.Slice(1);
                }
                try
                {
                    _version = System.Version.Parse(input);
                }
                catch (Exception innerException)
                {
                    throw new ArgumentException(SR.Argument_FrameworkNameInvalidVersion, "frameworkName", innerException);
                }
            }
            else
            {
                if (!MemoryExtensions.Equals(span, "Profile", StringComparison.OrdinalIgnoreCase))
                {
                    throw new ArgumentException(SR.Argument_FrameworkNameInvalid, "frameworkName");
                }
                if (input.Length > 0)
                {
                    _profile = input.ToString();
                }
            }
        }
        if (!flag)
        {
            throw new ArgumentException(SR.Argument_FrameworkNameMissingVersion, "frameworkName");
        }
    }
References System.Runtime.Versioning.FrameworkName._identifier, System.Runtime.Versioning.FrameworkName._profile, System.Runtime.Versioning.FrameworkName._version, System.SR.Argument_FrameworkNameInvalid, System.SR.Argument_FrameworkNameInvalidVersion, System.SR.Argument_FrameworkNameMissingVersion, System.SR.Argument_FrameworkNameTooShort, System.array, System.MemoryExtensions.Equals(), System.SR.Format(), System.input, System.SR.net_emptystringcall, System.Version.Parse(), and System.text.