Terraria: System.Math.Ceiling
Ceiling() [2/2]
static double System.Math.Ceiling (double a)
Referenced by System.Diagnostics.Metrics.ExponentialHistogramAggregator.ExponentialHistogramAggregator(), System.Runtime.MemoryFailPoint.MemoryFailPoint(), System.Timers.Timer.Timer(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_066_TryInterceptingTarget(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_084_LunaticCultist(), System.Double.Ceiling(), System.Drawing.Point.Ceiling(), System.Drawing.Rectangle.Ceiling(), System.Drawing.Size.Ceiling(), MS.Internal.Xml.XPath.NumberFunctions.Ceiling(), System.Diagnostics.Metrics.AggregationManager.CollectWorker(), Terraria.GameContent.Bestiary.NPCPortraitInfoElement.CreateStarsContainer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone(), System.Number.Dragon4(), Terraria.Main.DrawBackground(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawUnderworldBackgroudLayer(), Terraria.Main.FakeLoadInvasionStart(), Terraria.Projectile.GasTrapCheck(), System.Number.Grisu3.GetCachedPowerForBinaryExponentRange(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetDisplaySettings(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetGridParameters(), Terraria.Main.GetInfoAccIconPosition(), Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.Graphics.Shaders.MiscShaderData.IsPowerOfTwo(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.OnPlayerJoining(), System.Diagnostics.Tracing.CounterGroup.OnTimer(), System.Math.Round(), System.Numerics.Vector< T >.ScalarCeiling(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2(), Terraria.Physics.BallCollision.Step(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.UpdateSize(), System.Timers.Timer.UpdateTimer(), and Terraria.WorldGen.WavyCaverer().