Terraria: System.Math.Log
Log() [2/2]
static double System.Math.Log (double d)
Referenced by System.Diagnostics.Metrics.ExponentialHistogramAggregator.ExponentialHistogramAggregator(), System.Numerics.Complex.Asin_Internal(), Terraria.Graphics.Shaders.MiscShaderData.IsPowerOfTwo(), System.Numerics.BigInteger.Log(), System.Numerics.Complex.Log(), System.Math.Log(), System.Double.Log(), System.Double.Log(), System.Numerics.Complex.Log1P(), System.Numerics.Complex.Pow(), and Terraria.Utils.RandomConsecutive().