Terraria: System.Math.Abs
Abs() [2/8]
static double System.Math.Abs (double value)
Referenced by System.Random.CompatPrng.CompatPrng(), System.Decimal.Abs(), System.Double.Abs(), System.MathF.Abs(), System.Int32.Abs(), System.Int64.Abs(), System.IntPtr.Abs(), System.SByte.Abs(), System.Int16.Abs(), System.Numerics.Complex.Acos(), Terraria.Collision.AdvancedTileCollision(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_FindGoodRestingSpot(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_IsInAGoodRestingSpot(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_015_Flails_Old(), Terraria.Projectile.AI_015_HandleMovementCollision(), Terraria.Projectile.AI_015_HandleMovementCollision_Old(), Terraria.Projectile.AI_016(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_047_MagnetSphere(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_099_1(), Terraria.Projectile.AI_099_2(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_119_Dandelion(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_121_QueenSlime_FlyMovement(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_123_Deerclops_FindSpotToSpawnSpike(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.NPC.AI_124_DeerclopsLeg(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.Projectile.AI_130_FlameBurstTower_FindTarget(), Terraria.Projectile.AI_134_Ballista_FindTarget(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_148_StarSpawner(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_153_ToiletPop(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_160_Kites(), Terraria.Projectile.AI_163_Chum(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_174_MultisegmentPet(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.Main.Ambience(), Terraria.Main.AnimateTiles(), Terraria.Main.AnimateTiles_WeatherVane(), Terraria.GameContent.Biomes.TerrainPass.ApplyPass(), System.Numerics.Complex.Asin(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Collision.CanHitWithCheck(), Terraria.Player.CarpetMovement(), Terraria.Mount.CastSuperCartLaser(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.ChasmRunner(), Terraria.WorldGen.ChasmRunnerSideways(), Terraria.WorldGen.Check3x3(), Terraria.Collision.CheckAABBvLineCollision(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckOrb(), Terraria.Mount.ClampToDeadZone(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.NPC.Collision_MoveSlopesAndStairFall(), Terraria.Item.CombineWithNearbyItems(), Terraria.Player.CommandForbiddenStorm(), Microsoft.Xna.Framework.Curve.ComputeTangent(), Terraria.WorldGen.Convert(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Terraria.Projectile.CreateGroundExplosion(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.CreateOutlines(), Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines(), Terraria.WorldGen.CrimEnt(), Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.CrimStart(), Terraria.WorldGen.CrimVein(), Microsoft.Xna.Framework.Matrix.Decompose(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.digTunnel(), Terraria.WorldGen.DirtyRockRunner(), Microsoft.Xna.Framework.MathHelper.Distance(), Terraria.Collision.DistFromSeg(), Terraria.Main.DoDraw(), Terraria.Main.DoDraw_UpdateCameraPosition(), Terraria.Mount.DoSteamMinecartEffect(), Terraria.Main.DoUpdate(), Terraria.Utilities.NPCUtils.SearchFilters.DownwindFromNPC(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds(), Terraria.Mount.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.Utils.DrawCursorSingle(), Terraria.Main.DrawDust(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.Main.DrawInfernoRings(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInterface_33_MouseText(), Terraria.Main.DrawInterface_4_Ruler(), Terraria.Main.DrawInventory(), Terraria.Main.DrawItem(), Terraria.Main.DrawKite(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.Main.DrawWithOutlines(), Terraria.WorldGen.DungeonHalls(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion_v1(), System.Globalization.CalendricalCalculationsHelper.EquationOfTime(), System.Data.FunctionNode.EvalFunction(), Terraria.Projectile.ExplodeCrackedTiles(), Terraria.Projectile.ExplodeTiles(), Terraria.Player.FindClosest(), Terraria.NPC.FindFrame(), Terraria.Item.FindOwner(), Terraria.Player.FindPulley(), Terraria.GameContent.Golf.GolfHelper.FindVectorOnOval(), Terraria.WorldGen.FloatingIsland(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), Terraria.WorldGen.GenerateWorld(), Terraria.WorldGen.GERunner(), Terraria.Graphics.Capture.CaptureInterface.GetArea(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoiseInternal(), Terraria.Player.GetFarthestSpawnPositionOnLine(), System.DateTime.GetGetSystemTimeAsFileTimeFnPtr(), Terraria.Mount.GetMinecartMechPoint(), Terraria.WorldSections.GetNextMapDraw(), Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor(), Terraria.GameInput.SmartSelectGamepadPointer.GetPointerPosition(), Terraria.Player.GetRespawnTime(), Terraria.Projectile.GetScarabBombDigDirectionSnap8(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.Mount.GetWitchBroomTrinketRotation(), Terraria.Projectile.ghostHurt(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Gore.Gore_UpdateSail(), Terraria.WorldGen.GrowDungeonTree(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowSpike(), Terraria.Projectile.HandleMovement(), Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), Terraria.Initializers.UILinksInitializer.HandleSliderVerticalInput(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseReqest(), Terraria.GameContent.Events.Sandstorm.HasSufficientWind(), Terraria.WorldGen.HellHouse(), ReLogic.Utilities.Vector2D.Hermite(), Terraria.NPC.HitEffect(), Terraria.Player.HorizontalMovement(), Terraria.Mount.Hover(), System.Numerics.Complex.Hypot(), System.Math.IEEERemainder(), Terraria.GameContent.UI.WorldUIAnchor.InRange(), Microsoft.Xna.Framework.Ray.Intersects(), Microsoft.Xna.Framework.BoundingBox.Intersects(), Microsoft.Xna.Framework.Ray.Intersects(), Microsoft.Xna.Framework.BoundingBox.Intersects(), Microsoft.Xna.Framework.BoundingFrustum.Intersects(), Terraria.GameContent.Generation.TrackGenerator.IsLocationInvalid(), Terraria.GameContent.UI.Minimap.MinimapFrame.Button.IsTouchingPoint(), Terraria.Player.ItemCheck_Shoot(), Terraria.Mount.JumpHeight(), Terraria.Mount.JumpSpeed(), Terraria.Projectile.Kill(), Terraria.WorldGen.Lakinater(), Terraria.Collision.LaserScan(), Terraria.Player.LimitPointToPlayerReachableArea(), Terraria.GameContent.UI.WiresUI.WiresRadial.LineUpdate(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.Initializers.DyeInitializer.LoadLegacyHairdyes(), Terraria.Projectile.MakeBoulderOfEarthExplosion(), Terraria.WorldGen.MakeDungeon(), Terraria.WorldGen.MakeDungeon_Pictures(), Terraria.Player.MakeFloorDust(), Terraria.Rain.MakeRain(), Terraria.Wiring.MassWireOperationInner(), System.Math.MaxMagnitude(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.meteor(), System.Math.MinMagnitude(), Terraria.Player.MoonLeechRope(), Terraria.WorldGen.Mountinater(), Terraria.Item.MoveInWorld(), Terraria.WorldGen.MudWallRunner(), Terraria.WorldGen.neonMossBiome(), System.Globalization.Normalization.NlsNormalize(), Microsoft.Xna.Framework.Plane.Normalize(), Microsoft.Xna.Framework.Plane.Normalize(), Microsoft.Xna.Framework.Plane.Normalize(), Terraria.NPC.NPCLoot_DropMoney(), System.Number.NumberToDoubleFloatingPointBits(), System.Number.NumberToHalfFloatingPointBits(), System.Number.NumberToSingleFloatingPointBits(), Terraria.WorldGen.oceanCave(), Terraria.Main.oldDrawWater(), Terraria.Collision.OneDimensionalIntersection(), System.Numerics.Complex.operator/(), System.Numerics.Complex.operator/(), Terraria.WorldGen.OreRunner(), Terraria.GameContent.Generation.ShapeRunner.Perform(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.GameContent.Biomes.HiveBiome.Place(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.MarbleBiome.Place(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.PlaceAt(), Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), Terraria.WorldGen.PlaceOasis(), Terraria.GameContent.Biomes.DunesBiome.PlaceSingle(), Terraria.Player.PlayerFrame(), Terraria.Audio.LegacySoundPlayer.PlaySound(), Terraria.Utils.PlotLine(), Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), Terraria.GameContent.RGB.EyeballShader.ProcessHighDetail(), Terraria.GameContent.RGB.GolemShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.Mount.ResetFlightTime(), System.Math.Round(), System.Data.SqlTypes.SqlDecimal.Round(), System.Numerics.Vector< T >.ScalarAbs(), Terraria.WorldGen.ScoreRoom(), Terraria.WorldGen.SeaOatWaterCheck(), Terraria.StrayMethods.SendWalker(), Terraria.Player.SetArmorEffectVisuals(), Terraria.Utilities.UnifiedRandom.SetSeed(), Terraria.IO.WorldFileData.SetSeed(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.WorldGen.ShimmerRemoveWater(), Terraria.Projectile.ShouldWallExplode(), Terraria.WorldGen.ShroomPatch(), Terraria.Collision.SlopeCollision(), Terraria.Player.SlopingCollision(), Terraria.Player.SmartSelectLookup(), Terraria.WorldGen.SnowCloudIsland(), Terraria.Main.snowing(), Terraria.WorldGen.SonOfLakinater(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Digestion(), Terraria.WorldGen.SpawnFallingBlockProjectile(), Terraria.NPC.SpawnNPC(), Terraria.Star.SpawnStars(), Terraria.Projectile.SpawnWebs(), System.Numerics.Complex.Sqrt(), Terraria.Star.StarFall(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.Collision.StepConveyorBelt(), Terraria.Player.StickyMovement(), Terraria.Collision.StickyTiles(), System.Numerics.Complex.Tan(), Terraria.Collision.TileCollision(), Terraria.WorldGen.TileRunner(), System.Net.Mime.SmtpDateTime.TimeSpanToOffset(), System.Xml.XmlConverter.ToChars(), Terraria.Minecart.TrackCollision(), Terraria.Player.TryBouncingBlocks(), System.Buffers.Text.Utf8Formatter.TryFormat(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), Terraria.NPC.TryTrackingTarget(), Terraria.Collision.TupleHitLine(), Terraria.Collision.TupleHitLineWall(), Terraria.GameContent.Drawing.TileDrawing.Update(), Terraria.GameContent.Events.MoonlordDeathDrama.Update(), Terraria.UI.Gamepad.UILinkPointNavigator.Update(), Terraria.Gore.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Main.UpdateAudio(), Terraria.Player.UpdateBiomes(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.GameContent.Drawing.TileDrawing.UpdateLeafFrequency(), Terraria.NPC.UpdateNetworkCode(), Terraria.NPC.UpdateNPC(), Terraria.NPC.UpdateNPC_BuffApplyVFX(), Terraria.NPC.UpdateNPC_CritterSounds(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UpdateOffsetDown(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateSliderAndShowMultiplierMouseOver(), Terraria.Player.UpdateTouchingTiles(), Terraria.GameContent.Skies.AmbientSky.ButterfliesSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.LostKiteSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.PegasusSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.VultureSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.PixiePosseSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.BirdsPackSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.WyvernSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.AirshipSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.AirBalloonSkyEntity.UpdateVelocity(), Terraria.Main.UpdateWeather(), Terraria.Main.UpdateWindyDayState(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), System.Net.Mime.SmtpDateTime.ValidateAndGetSanitizedTimeSpan(), Terraria.Collision.WalkDownSlope(), and Terraria.Player.Yoraiz0rEye().