Terraria: System.Math.Round
Round() [7/8]
static unsafe double System.Math.Round (double value, int digits, MidpointRounding mode) inline static
Definition at line 1156 of file Math.cs.
    {
        if (digits < 0 || digits > 15)
        {
            throw new ArgumentOutOfRangeException("digits", SR.ArgumentOutOfRange_RoundingDigits);
        }
        if (mode < MidpointRounding.ToEven || mode > MidpointRounding.ToPositiveInfinity)
        {
            throw new ArgumentException(SR.Format(SR.Argument_InvalidEnumValue, mode, "MidpointRounding"), "mode");
        }
        if (Abs(value) < 10000000000000000.0)
        {
            double num = roundPower10Double[digits];
            value *= num;
            switch (mode)
            {
            case MidpointRounding.ToEven:
                value = Round(value);
                break;
            case MidpointRounding.AwayFromZero:
            {
                double value2 = ModF(value, &value);
                if (Abs(value2) >= 0.5)
                {
                    value += (double)Sign(value2);
                }
                break;
            }
            case MidpointRounding.ToZero:
                value = Truncate(value);
                break;
            case MidpointRounding.ToNegativeInfinity:
                value = Floor(value);
                break;
            case MidpointRounding.ToPositiveInfinity:
                value = Ceiling(value);
                break;
            default:
                throw new ArgumentException(SR.Format(SR.Argument_InvalidEnumValue, mode, "MidpointRounding"), "mode");
            }
            value /= num;
        }
        return value;
    }
References System.Math.Abs(), System.SR.Argument_InvalidEnumValue, System.SR.ArgumentOutOfRange_RoundingDigits, System.Math.Ceiling(), System.Math.Floor(), System.SR.Format(), System.Math.ModF(), System.Math.Round(), System.Math.roundPower10Double, System.Math.Sign(), System.Math.Truncate(), and System.value.