Terraria: System.Math.unsafe
unsafe()
static System.Math.unsafe (double Sin, double Cos) inline static
Definition at line 114 of file Math.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out double item);
        System.Runtime.CompilerServices.Unsafe.SkipInit(out double item2);
        SinCos(x, &item, &item2);
        return (Sin: item, Cos: item2);
    }
References System.Math.Cos(), System.item, System.Math.Sin(), and System.Math.SinCos().