Terraria: System.Math.Floor
Floor() [2/2]
static double System.Math.Floor (double d)
Referenced by System.Data.SqlTypes.SqlDecimal.SqlDecimal(), Terraria.Main.AnimateTiles(), Terraria.Main.AnimateTiles_WeatherVane(), Internal.Cryptography.Pal.ChainPal.BuildChain(), Terraria.Graphics.Capture.CaptureCamera.Capture(), System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.ConvertToArabic(), Terraria.Graphics.Light.LegacyLighting.CopyFullyProcessedDataOver(), ReLogic.Peripherals.RGB.Corsair.CorsairHelper.CreateFragment(), System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbFast(), Terraria.Main.DrawBlack(), Terraria.Main.DrawProjDirect(), System.Double.Floor(), MS.Internal.Xml.XPath.NumberFunctions.Floor(), Terraria.Main.GetAreaToLight(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetColor(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetColor2(), System.Globalization.PersianCalendar.GetDatePart(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), System.Globalization.CalendricalCalculationsHelper.GetGregorianYear(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetPosition(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Terraria.Physics.BallCollision.GetTileBounds(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.Graphics.Shaders.MiscShaderData.IsPowerOfTwo(), System.Globalization.TimeSpanParse.TimeSpanToken.NormalizeAndValidateFraction(), System.Globalization.CalendricalCalculationsHelper.PersianNewYearOnOrBefore(), Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), System.Globalization.CalendricalCalculationsHelper.Reminder(), System.Math.Round(), System.Numerics.Vector< T >.ScalarFloor(), Terraria.Graphics.Light.LegacyLighting.ShiftUnProcessedDataOver(), Terraria.Collision.StepDown(), Terraria.GameContent.Shaders.WaterShaderData.StepLiquids(), System.Net.Mime.SmtpDateTime.TimeSpanToOffset(), and Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight().