Terraria: System.Math.Sqrt
Sqrt()
static double System.Math.Sqrt (double d)
Referenced by Microsoft.Xna.Framework.Plane.Plane(), System.Threading.PortableThreadPool.HillClimbing.Complex.Abs(), System.Data.Common.ByteStorage.Aggregate(), System.Data.Common.DecimalStorage.Aggregate(), System.Data.Common.DoubleStorage.Aggregate(), System.Data.Common.Int16Storage.Aggregate(), System.Data.Common.Int32Storage.Aggregate(), System.Data.Common.Int64Storage.Aggregate(), System.Data.Common.SByteStorage.Aggregate(), System.Data.Common.SingleStorage.Aggregate(), System.Data.Common.SqlByteStorage.Aggregate(), System.Data.Common.SqlDecimalStorage.Aggregate(), System.Data.Common.SqlDoubleStorage.Aggregate(), System.Data.Common.SqlInt16Storage.Aggregate(), System.Data.Common.SqlInt32Storage.Aggregate(), System.Data.Common.SqlInt64Storage.Aggregate(), System.Data.Common.SqlMoneyStorage.Aggregate(), System.Data.Common.SqlSingleStorage.Aggregate(), System.Data.Common.TimeSpanStorage.Aggregate(), System.Data.Common.UInt16Storage.Aggregate(), System.Data.Common.UInt32Storage.Aggregate(), System.Data.Common.UInt64Storage.Aggregate(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_010(), Terraria.Projectile.AI_015_Flails_Old(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.NPC.AI_87_BigMimic_ShootItem(), Terraria.Player.ApplyEquipFunctional(), System.Numerics.Complex.Asin_Internal(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Microsoft.Xna.Framework.Matrix.CreateBillboard(), Microsoft.Xna.Framework.Matrix.CreateBillboard(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Microsoft.Xna.Framework.Quaternion.CreateFromRotationMatrix(), Microsoft.Xna.Framework.Quaternion.CreateFromRotationMatrix(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.WorldGen.CrimEnt(), Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.CrimStart(), Terraria.WorldGen.CrimVein(), Terraria.WorldGen.DesertCloudIsland(), Microsoft.Xna.Framework.Vector2.Distance(), ReLogic.Utilities.Vector2D.Distance(), Microsoft.Xna.Framework.Vector3.Distance(), Microsoft.Xna.Framework.Vector4.Distance(), Microsoft.Xna.Framework.Vector2.Distance(), ReLogic.Utilities.Vector2D.Distance(), Microsoft.Xna.Framework.Vector3.Distance(), Microsoft.Xna.Framework.Vector4.Distance(), Terraria.Collision.DistFromSeg(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCs(), Terraria.Main.DrawProj_Excalibur(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_FlailChains_Old(), Terraria.Main.DrawProj_NightsEdge(), Terraria.Main.DrawProj_TerraBlade2(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProj_TheHorsemansBlade(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjDirect(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.Main.DrawWOFRopeToTheHungry(), Terraria.Main.DrawWOFTongueToPlayer(), Terraria.Projectile.ExplodeCrackedTiles(), Terraria.Projectile.ExplodeTiles(), Terraria.NPC.FindClosestPlayer(), Terraria.WorldGen.FloatingIsland(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetDisplaySettings(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.GetDistance(), Terraria.Player.GetGrapplingForces(), Terraria.Player.GetPointOnSwungItemPath(), Terraria.GameContent.Animations.Actions.Sprites.OutCircleScale.GetProgress(), Terraria.Projectile.ghostHurt(), Terraria.WorldGen.HellHouse(), Terraria.Wiring.HitWireSingle(), Terraria.Player.HorsemansBlade_SpawnPumpkin(), Terraria.Player.Hurt(), System.Numerics.Complex.Hypot(), Microsoft.Xna.Framework.Ray.Intersects(), Microsoft.Xna.Framework.Ray.Intersects(), System.Collections.HashHelpers.IsPrime(), Terraria.Player.ItemCheck_PlayInstruments(), Terraria.Player.ItemCheck_Shoot(), Terraria.Projectile.Kill(), Terraria.WorldGen.Lakinater(), Microsoft.Xna.Framework.Quaternion.Length(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector3.Length(), Microsoft.Xna.Framework.Vector4.Length(), ReLogic.Utilities.Vector2D.Length(), Microsoft.Xna.Framework.Quaternion.Lerp(), Microsoft.Xna.Framework.Quaternion.Lerp(), Terraria.WorldGen.MakeDungeon(), Terraria.Item.MechSpawn(), Terraria.NPC.MechSpawn(), Terraria.WorldGen.meteor(), Terraria.WorldGen.Mountinater(), Microsoft.Xna.Framework.Plane.Normalize(), Microsoft.Xna.Framework.Quaternion.Normalize(), Microsoft.Xna.Framework.Vector2.Normalize(), Microsoft.Xna.Framework.Vector3.Normalize(), Microsoft.Xna.Framework.Vector4.Normalize(), ReLogic.Utilities.Vector2D.Normalize(), Microsoft.Xna.Framework.Plane.Normalize(), Microsoft.Xna.Framework.Quaternion.Normalize(), Microsoft.Xna.Framework.Plane.Normalize(), Microsoft.Xna.Framework.Quaternion.Normalize(), Microsoft.Xna.Framework.Vector2.Normalize(), ReLogic.Utilities.Vector2D.Normalize(), Microsoft.Xna.Framework.Vector3.Normalize(), Microsoft.Xna.Framework.Vector4.Normalize(), Microsoft.Xna.Framework.Vector2.Normalize(), ReLogic.Utilities.Vector2D.Normalize(), Microsoft.Xna.Framework.Vector3.Normalize(), Microsoft.Xna.Framework.Vector4.Normalize(), Terraria.Main.oldDrawWater(), Terraria.Player.OnHit(), Terraria.WorldBuilding.Shapes.Circle.Perform(), Terraria.WorldBuilding.Shapes.HalfCircle.Perform(), Terraria.WorldBuilding.Shapes.Slime.Perform(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.GameContent.Biomes.MarbleBiome.Place(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), Terraria.WorldGen.PlaceOasis(), Terraria.Audio.LegacySoundPlayer.PlaySound(), Terraria.GameContent.RGB.SkyShader.ProcessAnyDetail(), Terraria.GameContent.RGB.EyeballShader.ProcessHighDetail(), Terraria.GameContent.RGB.KingSlimeShader.ProcessHighDetail(), Terraria.GameContent.RGB.MeteoriteShader.ProcessHighDetail(), Terraria.GameContent.RGB.MoonShader.ProcessHighDetail(), Terraria.GameContent.RGB.QueenSlimeShader.ProcessHighDetail(), Terraria.GameContent.RGB.WallOfFleshShader.ProcessHighDetail(), Terraria.GameContent.RGB.MoonShader.ProcessLowDetail(), Terraria.Player.PullItem_Pickup(), Terraria.Player.QuickGrapple(), System.Math.ReciprocalSqrtEstimate(), System.Numerics.Vector< T >.ScalarSqrt(), Terraria.Utilities.NPCUtils.SearchForTarget(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerRemoveWater(), Terraria.WorldGen.ShootFromCannon(), Terraria.Projectile.ShouldWallExplode(), Terraria.WorldGen.ShroomPatch(), Terraria.Player.SmartSelectLookup(), Terraria.WorldGen.SnowCloudIsland(), Terraria.Main.snowing(), Terraria.Utils.SolveQuadratic(), Terraria.WorldGen.SonOfLakinater(), System.Numerics.Complex.Sqrt(), System.Double.Sqrt(), Terraria.Player.TileInteractionsUse(), Microsoft.Xna.Framework.BoundingSphere.Transform(), Microsoft.Xna.Framework.BoundingSphere.Transform(), Terraria.Player.Update(), Terraria.Player.UpdateArmorSets(), Terraria.WorldGen.UpdateWorld(), Terraria.Player.WOFTongue(), and System.Diagnostics.Tracing.EventCounter.WritePayload().