Terraria: System.Math.Acos
Acos()
static double System.Math.Acos (double d)
Referenced by System.Numerics.Complex.Acos(), System.Double.Acos(), Terraria.Main.DrawNPCDirect(), Microsoft.Xna.Framework.Quaternion.Slerp(), and Microsoft.Xna.Framework.Quaternion.Slerp().