Terraria: System.Math.Round
Round() [1/8]
static decimal System.Math.Round (decimal d) inline static
Definition at line 1096 of file Math.cs.
    {
        return decimal.Round(d, 0);
    }
Referenced by System.Data.Common.TimeSpanStorage.Aggregate(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.WorldGen.CountTiles(), Terraria.GameContent.UI.States.UIManageControls.CreatePanel(), Terraria.Main.DamageVar(), System.DateTimeParse.DoStrictParse(), Terraria.IngameOptions.Draw(), Terraria.Main.DrawBackground(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawMenu(), Terraria.Projectile.FishingCheck(), Terraria.Main.GetInputText(), Terraria.Player.GetItemExpectedPrice(), Terraria.GameContent.PortalHelper.GetPortalOutingPoint(), Terraria.Main.hslToRgb(), System.Math.IEEERemainder(), Terraria.Player.ItemCheck_PlayInstruments(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseMiningTools_TryFindingWallToHammer(), Terraria.GameContent.ShopHelper.LimitAndRoundMultiplier(), Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), System.Globalization.TimeSpanParse.TimeSpanToken.NormalizeAndValidateFraction(), Terraria.Main.OldDrawBackground(), System.TimeSpan.operator*(), System.TimeSpan.operator/(), System.DateTimeParse.ParseFormatO(), System.DateTimeParse.ParseISO8601(), Terraria.Item.Prefix(), System.Xml.Xsl.Runtime.XsltFunctions.Round(), System.Math.Round(), System.Math.Round(), System.Math.Round(), System.Double.Round(), System.Double.Round(), System.Drawing.Point.Round(), System.Drawing.Rectangle.Round(), System.Drawing.Size.Round(), Terraria.Utils.Round(), System.Double.Round< TInteger >(), System.Double.Round< TInteger >(), Terraria.GameContent.PortalHelper.SupportedTilesAreFine(), System.Convert.ToInt64(), System.Convert.ToUInt64(), Terraria.Minecart.TrackCollision(), Terraria.Item.TryGetPrefixStatMultipliersForItem(), System.DateTimeParse.TryParse(), Terraria.Liquid.Update(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.UpdateInfoFromSliderValueCache(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.UpdateInfoFromSliderValueCache(), Terraria.Player.UpdateLifeRegen(), System.Decimal.DecCalc.VarDecFromR4(), System.Decimal.DecCalc.VarDecFromR8(), and System.Xml.XmlConvert.XPathRound().