Terraria: System.Math.Min
Min() [1/13]
static byte System.Math.Min (byte val1, byte val2) inline static
Definition at line 912 of file Math.cs.
    {
        if (val1 > val2)
        {
            return val2;
        }
        return val1;
    }
Referenced by System.Threading.PortableThreadPool.BlockingConfig.BlockingConfig(), System.Collections.Concurrent.ConcurrentQueue< T >.ConcurrentQueue(), System.Net.Http.Http3RequestStream.Http3RequestStream(), System.Net.Http.HttpConnectionPoolManager.HttpConnectionPoolManager(), System.Net.Security.SecurityBuffer.SecurityBuffer(), System.Net.Security.SecurityBuffer.SecurityBuffer(), System.Text.StringBuilder.StringBuilder(), System.Text.StringBuilder.StringBuilder(), Terraria.GameContent.Biomes.Desert.SurfaceMap.SurfaceMap(), System.Linq.Parallel.ZipQueryOperator< TLeftInput, TRightInput, TOutput >.ZipQueryOperatorResults.ZipQueryOperatorResults(), System.Number.AccumulateDecimalDigitsIntoBigInteger(), System.Xml.XmlBinaryReaderSession.Add(), ReLogic.Utilities.MultiTimer.TimerData.AddTick(), Terraria.PopupText.AddToCoinValue(), System.Net.Http.CreditManager.AdjustCredit(), System.Data.SqlTypes.SqlDecimal.AdjustScale(), System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindowDynamic(), System.Net.CookieContainer.AgeCookies(), System.Data.Common.ByteStorage.Aggregate(), System.Data.Common.DecimalStorage.Aggregate(), System.Data.Common.DoubleStorage.Aggregate(), System.Data.Common.Int16Storage.Aggregate(), System.Data.Common.Int32Storage.Aggregate(), System.Data.Common.Int64Storage.Aggregate(), System.Data.Common.SByteStorage.Aggregate(), System.Data.Common.SingleStorage.Aggregate(), System.Data.Common.UInt16Storage.Aggregate(), System.Data.Common.UInt32Storage.Aggregate(), System.Data.Common.UInt64Storage.Aggregate(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.Projectile.AI_099_2(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_118_Seahorses(), Terraria.NPC.AI_124_DeerclopsLeg(), Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.Projectile.AI_174_MultisegmentPet(), System.Collections.Generic.LargeArrayBuilder< T >.AllocateBuffer(), System.IO.ChunkedMemoryStream.AppendChunk(), System.Text.StringBuilder.AppendCore(), Terraria.WorldBuilding.Modifiers.RadialDither.Apply(), Terraria.GameContent.Biomes.TerrainPass.ApplyPass(), System.Data.Common.ADP.BuildSchemaTableInfoTableNames(), Terraria.Graphics.Capture.CaptureCamera.Capture(), Terraria.Collision.CheckAABBvLineCollision(), System.Text.Json.Utf8JsonReader.CheckLiteralMultiSegment(), System.Xml.EncodingStreamWrapper.CheckUTF8DeclarationEncoding(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.CircularCopyUtf16BE(), Terraria.GameContent.UI.Chat.RemadeChatMonitor.ClampMessageIndex(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), System.Xml.XmlCanonicalWriter.Compare(), System.Xml.XmlBufferReader.Compare(), System.Net.PathList.PathListComparer.Compare(), System.Formats.Asn1.SetOfValueComparer.Compare(), System.String.Compare(), System.String.Compare(), System.String.Compare(), System.String.CompareOrdinal(), System.String.CompareOrdinalHelper(), System.Globalization.InvariantModeCasing.CompareStringIgnoreCase(), System.Globalization.Ordinal.CompareStringIgnoreCase(), System.Globalization.OrdinalCasing.CompareStringIgnoreCase(), System.Text.RegularExpressions.RegexNode.ComputeMinLength(), System.Text.RegularExpressions.RegexPrefixAnalyzer.ComputeMultipleCharClasses(), System.Reflection.Metadata.BlobBuilder.ContentEquals(), System.StubHelpers.FixedWSTRMarshaler.ConvertToNative(), System.Reflection.Metadata.Ecma335.ControlFlowBuilder.CopyCodeAndFixupBranches(), System.Net.Security.SslStream.CopyDecryptedData(), System.IO.Compression.OutputWindow.CopyFrom(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.CopyMsQuicBuffersToUserBuffer(), System.Collections.Generic.LargeArrayBuilder< T >.CopyTo(), System.Text.StringBuilder.CopyTo(), System.IO.Compression.InputBuffer.CopyTo(), System.Collections.Generic.Queue< T >.CopyTo(), System.Collections.Generic.LargeArrayBuilder< T >.CopyTo(), System.Collections.Generic.SparseArrayBuilder< T >.CopyTo(), System.Reflection.Internal.StreamExtensions.CopyTo(), System.Net.Http.HttpConnection.CopyToContentLengthAsync(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CreateBuffer(), ReLogic.Peripherals.RGB.Fragment.CreateCanvasPositions(), ReLogic.Peripherals.RGB.Corsair.CorsairHelper.CreateFragment(), Terraria.GameContent.Bestiary.NPCPortraitInfoElement.CreateStarsContainer(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.CreateSupportBeamList(), Microsoft.Xna.Framework.Graphics.Texture3D.CreateTexture(), Interop.NCrypt.DeriveKeyMaterial(), System.Threading.Barrier.DiscontinuousWait(), Terraria.Graphics.Light.LegacyLighting.doColors_Mode0_Swipe(), Terraria.Main.DoUpdate(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds(), Terraria.Mount.Draw(), Terraria.GameContent.Skies.BlizzardSky.Draw(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.SandstormSky.Draw(), Terraria.GameContent.Skies.SolarSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.GameContent.Skies.VortexSky.Draw(), Terraria.Main.DrawBG(), Terraria.Main.DrawBlack(), Terraria.Main.DrawCapture(), Terraria.GameContent.UI.Chat.RemadeChatMonitor.DrawChat(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea(), Terraria.DataStructures.PlayerDrawLayers.DrawMeowcartTrail(), Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer(), Terraria.Main.DrawSimpleSurfaceBackground(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.Main.DrawWaters(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.Cinematics.DD2Film.DryadPortalKnock(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.DumpBuffer(), System.Globalization.CompareInfo.EndsWithOrdinalHelper(), System.Globalization.CompareInfo.EndsWithOrdinalIgnoreCaseHelper(), System.Collections.Concurrent.ConcurrentQueue< T >.EnqueueSlow(), System.Net.MultiArrayBuffer.EnsureAvailableSpaceUpToLimit(), System.IO.BufferedStream.EnsureShadowBufferAllocated(), System.Threading.TimerQueue.EnsureTimerFiresBy(), System.Xml.XmlBufferReader.Equals2(), System.Globalization.CalendricalCalculationsHelper.EquationOfTime(), System.Reflection.AssemblyName.EscapeString(), Terraria.GameContent.UI.States.UIWorldCreation.EstablishUpDownRelationship(), System.Globalization.CalendricalCalculationsHelper.EstimatePrior(), System.Text.StringBuilder.ExpandByABlock(), Terraria.Graphics.Light.LightingEngine.ExportToMiniMap(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms(), Terraria.WorldGen.FillWallHolesInArea(), Terraria.WorldGen.FillWallHolesInColumn(), Terraria.Collision.FindCollisionTile(), Terraria.NPC.FindFrame(), System.Text.Json.Utf8JsonReader.FindMismatch(), Terraria.Collision.FindOverlapPoints(), Terraria.GameContent.Generation.TrackGenerator.FindPath(), Terraria.GameContent.DontStarveSeed.FixBiomeDarkness(), ReLogic.Threading.FastParallel.For(), System.Globalization.FormatProvider.Number.FormatFixed(), System.Number.FormatFixed(), Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate(), System.Security.Cryptography.PKCS1MaskGenerationMethod.GenerateMask(), System.Xml.Serialization.ReflectionXmlSerializationWriter.GenerateMembersElement(), Terraria.WorldGen.GenerateWorld(), Terraria.Player.GetAnglerReward_Decoration(), Terraria.Graphics.Capture.CaptureInterface.GetArea(), System.Runtime.Serialization.XmlReaderDelegator.GetArrayLengthQuota(), Terraria.WorldBuilding.ShapeData.GetBounds(), System.Xml.XmlBufferReader.GetBuffer(), System.Data.DataTableReader.GetBytes(), System.Text.ASCIIEncoding.GetBytesFast(), System.Text.Latin1Encoding.GetBytesFast(), System.Text.ASCIIEncoding.GetBytesWithFallback(), System.Data.DataTableReader.GetChars(), System.Text.ASCIIEncoding.GetCharsFast(), System.Text.Latin1Encoding.GetCharsFast(), System.Text.ASCIIEncoding.GetCharsWithFallback(), Terraria.Utils.GetChaseResults(), System.Reflection.PortableExecutable.PEBuilder.GetContentToSign(), System.IO.Stream.GetCopyBufferSize(), System.Reflection.Internal.MemoryBlock.GetDebuggerDisplay(), System.Globalization.CalendricalCalculationsHelper.GetGregorianYear(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetGridParameters(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetKey(), System.Threading.PortableThreadPool.GateThread.DelayHelper.GetNextDelay(), Terraria.WorldBuilding.Actions.SetTileAndWallRainbowPaint.GetPaintIDForPosition(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetParameter(), System.Net.Http.Headers.AltSvcHeaderParser.GetParsedValueLength(), System.Reflection.PortableExecutable.PEReader.GetPESectionBlock(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.GetProperty(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.GetRangeText(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueBooleanArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueInt32Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingleArray(), Terraria.WorldGen.GetWorldUpdateRate(), System.Text.RegularExpressions.RegexInterpreter.Go(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumeratorForIndexRange_Abstract< TSource, TSourceReader >.GrabNextChunk(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.GrowCore(), System.Data.RecordManager.GrowRecordCapacity(), Terraria.Projectile.HandleMovement(), System.Globalization.IdnMapping.IcuGetAsciiCore(), System.Data.DataError.IndexOf(), System.IO.Compression.InflaterManaged.Inflate(), System.IO.Compression.Inflater.InflateVerified(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), System.Xml.XmlUTF8NodeWriter.InternalWriteBase64Text(), System.Xml.XmlUTF8NodeWriter.InternalWriteBase64TextAsync(), System.Drawing.Rectangle.Intersect(), System.Drawing.RectangleF.Intersect(), System.Xml.Schema.BitSet.Intersects(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStripRightSideToSingle(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStrips(), Terraria.Main.LoadPlayers(), Terraria.Main.LoadWorlds(), System.Net.Sockets.SocketAsyncEventArgs.LogBuffer(), System.Threading.PortableThreadPool.HillClimbing.LogTransition(), System.Text.StringBuilder.MakeRoom(), System.Linq.Parallel.SortHelper< TInputOutput, TKey >.MergeSortCooperatively(), System.Byte.Min(), System.Char.Min(), System.Decimal.Min(), System.Double.Min(), Microsoft.Xna.Framework.MathHelper.Min(), System.MathF.Min(), System.Int32.Min(), System.Int64.Min(), System.IntPtr.Min(), System.UIntPtr.Min(), System.SByte.Min(), System.Int16.Min(), System.UInt32.Min(), System.UInt64.Min(), System.UInt16.Min(), Terraria.Main.MouseText_DrawItemTooltip(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveDownCustomComparer(), System.Collections.Generic.PriorityQueue< TElement, TPriority >.MoveDownDefaultComparer(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumerator_Abstract< TSource, TSourceReader >.MoveNext(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext(), System.Runtime.CompilerServices.RuleCache< T >.MoveRule(), Terraria.Rain.NewRain(), System.Globalization.CalendarData.NlsGetCalendars(), System.Numerics.BigNumber.NumberToBigInteger(), System.Number.NumberToDoubleFloatingPointBits(), System.Number.NumberToHalfFloatingPointBits(), System.Number.NumberToSingleFloatingPointBits(), Terraria.Achievements.ConditionsCompletedTracker.OnConditionCompleted(), System.Threading.PortableThreadPool.OnGen2GCCallback(), System.Net.Http.Http2Connection.Http2Stream.OnWindowUpdate(), System.Net.WebClient.OpenFileInternal(), System.Data.SqlTypes.SqlDecimal.operator*(), System.Data.SqlTypes.SqlDecimal.operator+(), System.Data.SqlTypes.SqlDecimal.operator/(), System.Net.Http.HPack.HPackDecoder.ParseHeaderName(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValue(), System.Formats.Asn1.AsnWriter.ParseSubIdentifier(), Terraria.GameContent.Generation.ShapeRunner.Perform(), Terraria.WorldBuilding.Shapes.Circle.Perform(), Terraria.WorldBuilding.Shapes.HalfCircle.Perform(), Terraria.WorldBuilding.Shapes.Slime.Perform(), Terraria.WorldBuilding.Shapes.Mound.Perform(), System.Threading.PortableThreadPool.PerformBlockingAdjustment(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.GameContent.Biomes.MarbleBiome.Place(), Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt(), System.Diagnostics.Tracing.CounterGroup.PollForValues(), Terraria.GameContent.Shaders.WaterShaderData.PreDraw(), System.Net.WebSockets.Compression.WebSocketInflater.Prepare(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.ProcessAction_IndicateReceiveComplete(), System.Xml.EncodingStreamWrapper.ProcessBuffer(), Terraria.GameContent.RGB.EyeballShader.ProcessHighDetail(), Terraria.GameContent.RGB.MoonShader.ProcessHighDetail(), Terraria.GameContent.RGB.PirateInvasionShader.ProcessHighDetail(), System.Threading.ProcessorIdCache.ProcessorNumberSpeedCheck(), System.Net.Mail.SmtpReplyReaderFactory.ReadLinesAsyncResult.ProcessRead(), System.Net.Http.Http3Connection.ProcessServerControlStreamAsync(), System.Diagnostics.Metrics.ExponentialHistogramAggregator.QuantileToRank(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.Social.Steam.SteamP2PWriter.QueueSend(), Terraria.Social.WeGame.WeGameP2PWriter.QueueSend(), System.Net.BufferedReadStream.ReadAsyncResult.Read(), System.Net.BufferedReadStream.Read(), System.Reflection.Internal.ImmutableMemoryStream.Read(), System.Reflection.Internal.ReadOnlyUnmanagedMemoryStream.Read(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.Read(), System.IO.MemoryStream.Read(), System.Text.TranscodingStream.Read(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Xml.XmlBinaryReader.ReadArray(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadArrayAsBytes(), System.Net.BufferedReadStream.ReadAsync(), System.Text.TranscodingStream.ReadAsync(), System.Net.Security.NegotiateStream.ReadAsync< TAdapter >(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(), System.Security.Cryptography.CryptoStream.ReadAsyncCore(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsyncInternal(), System.Net.Http.HttpConnection.ReadBuffered(), System.Net.Http.HttpConnection.ReadBufferedAsyncCore(), System.Xml.Serialization.XmlSerializationReader.ReadByteArray(), System.Xml.XmlBaseReader.ReadBytes(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer(), System.Xml.XmlBaseReader.ReadContentAsBase64(), System.Xml.XmlBaseReader.ReadContentAsBinHex(), System.IO.UnmanagedMemoryStream.ReadCore(), System.Net.Http.Http2Connection.ReadFrameAsync(), System.IO.BufferedStream.ReadFromBuffer(), System.Net.Http.HttpConnection.ContentLengthReadStream.ReadFromConnectionBuffer(), System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync(), System.Net.Http.Http3RequestStream.ReadHeadersAsync(), System.Net.Mail.SmtpReplyReaderFactory.ReadLines(), System.Net.Http.Http3RequestStream.ReadResponseContent(), System.Net.Http.Http3RequestStream.ReadResponseContentAsync(), System.IO.BinaryReader.ReadString(), System.Xml.XmlBaseReader.ReadValueAsBase64(), System.Runtime.Serialization.Json.XmlJsonReader.ReadValueChunk(), System.Xml.XmlBaseReader.ReadValueChunk(), Terraria.Social.Steam.SteamP2PReader.Receive(), Terraria.Social.WeGame.WeGameP2PReader.Receive(), System.Net.WebSockets.WebSocketBuffer.ReceiveFromBufferedPayload(), System.Text.RegularExpressions.RegexNode.ReduceAlternation(), System.Net.Http.Http2Connection.RttEstimator.RefreshRtt(), Terraria.WorldGen.RefreshSection(), System.Threading.LowLevelLifoSemaphore.Release(), System.Threading.SemaphoreSlim.Release(), System.Threading.WaitHandle.RentSafeWaitHandleArray(), System.Text.StringBuilder.Replace(), System.Text.StringBuilder.ReplaceInPlaceAtChunk(), System.Net.Http.HPack.DynamicTable.Resize(), System.Array.Resize< T >(), Terraria.Main.rgbToHsl(), System.Data.SqlTypes.SqlDecimal.Round(), Terraria.GameContent.Creative.CreativeUI.SacrificeItem(), Terraria.Player.SellItem(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.Http.Http2Connection.Http2Stream.SendDataAsync(), System.Diagnostics.Tracing.EventSource.SendManifest(), System.Net.Http.Http2Connection.SendStreamDataAsync(), System.Diagnostics.Tracing.EventSource.SerializeEventArgs(), System.Data.Common.BigIntegerStorage.SetCapacity(), System.Data.Common.BooleanStorage.SetCapacity(), System.Data.Common.ByteStorage.SetCapacity(), System.Data.Common.CharStorage.SetCapacity(), System.Data.Common.DateTimeOffsetStorage.SetCapacity(), System.Data.Common.DateTimeStorage.SetCapacity(), System.Data.Common.DecimalStorage.SetCapacity(), System.Data.Common.DoubleStorage.SetCapacity(), System.Data.Common.Int16Storage.SetCapacity(), System.Data.Common.Int32Storage.SetCapacity(), System.Data.Common.Int64Storage.SetCapacity(), System.Data.Common.ObjectStorage.SetCapacity(), System.Data.Common.SByteStorage.SetCapacity(), System.Data.Common.SingleStorage.SetCapacity(), System.Data.Common.SqlBinaryStorage.SetCapacity(), System.Data.Common.SqlBooleanStorage.SetCapacity(), System.Data.Common.SqlBytesStorage.SetCapacity(), System.Data.Common.SqlByteStorage.SetCapacity(), System.Data.Common.SqlCharsStorage.SetCapacity(), System.Data.Common.SqlDateTimeStorage.SetCapacity(), System.Data.Common.SqlDecimalStorage.SetCapacity(), System.Data.Common.SqlDoubleStorage.SetCapacity(), System.Data.Common.SqlGuidStorage.SetCapacity(), System.Data.Common.SqlInt16Storage.SetCapacity(), System.Data.Common.SqlInt32Storage.SetCapacity(), System.Data.Common.SqlInt64Storage.SetCapacity(), System.Data.Common.SqlMoneyStorage.SetCapacity(), System.Data.Common.SqlSingleStorage.SetCapacity(), System.Data.Common.SqlStringStorage.SetCapacity(), System.Data.Common.SqlUdtStorage.SetCapacity(), System.Data.Common.StringStorage.SetCapacity(), System.Data.Common.TimeSpanStorage.SetCapacity(), System.Data.Common.UInt16Storage.SetCapacity(), System.Data.Common.UInt32Storage.SetCapacity(), System.Data.Common.UInt64Storage.SetCapacity(), Terraria.Main.SetDisplayMode(), System.Threading.PortableThreadPool.SetMaxThreads(), System.Threading.PortableThreadPool.SetMinThreads(), Terraria.GameContent.UI.Elements.UITextBox.SetText(), ReLogic.Peripherals.RGB.Fragment.SetupCanvasBounds(), System.Data.ProviderBase.SchemaMapping.SetupMapping(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), System.Net.Http.Http3RequestStream.SkipUnknownPayloadAsync(), System.Formats.Asn1.AsnDecoder.SliceAtMost(), Terraria.GameContent.Generation.TrackGenerator.SmoothTrack(), System.Globalization.CompareInfo.StartsWithOrdinalHelper(), System.Globalization.CompareInfo.StartsWithOrdinalIgnoreCaseHelper(), System.Linq.Enumerable.TakeRangeFromEndIterator< TSource >(), System.Net.TimerThread.ThreadProc(), System.Text.Json.ThrowHelper.ThrowArgumentException_InvalidUTF8(), Terraria.Player.TileInteractionsMouseOver(), System.Reflection.Metadata.BlobBuilder.ToArray(), System.Text.Json.JsonWriterHelper.ToUtf8(), System.Text.Unicode.Utf8Utility.TranscodeToUtf16(), System.Text.Unicode.Utf8Utility.TranscodeToUtf8(), System.Buffers.SequenceReader< T >.TryCopyMultisegment(), System.Xml.XmlBufferReader.TryEnsureBytes(), System.Buffers.Text.Utf8Formatter.TryFormatDecimalF(), System.Linq.Enumerable.ListPartition< TSource >.TryGetLast(), System.Linq.Enumerable.SelectListPartitionIterator< TSource, TResult >.TryGetLast(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TryGrowingGlowTulip(), System.Text.Json.JsonHelpers.TryParseDateTimeOffset(), System.Buffers.Text.Utf8Parser.TryParseNumber(), System.Number.TryParseNumber(), System.Xml.ValueHandle.TryReadBase64(), System.Xml.ValueHandle.TryReadChars(), System.IO.StreamBuffer.TryReadFromBuffer(), System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(), System.Xml.ValueHandle.TryReadUnicodeChars(), System.Net.Http.CreditManager.TryRequestCreditNoLock(), Terraria.GameContent.Generation.TrackGenerator.TryRewriteHistoryToAvoidTiles(), Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight(), System.Reflection.Metadata.BlobBuilder.TryWriteBytes(), System.IO.StreamBuffer.TryWriteToBuffer(), System.Drawing.Rectangle.Union(), System.Drawing.RectangleF.Union(), System.Data.Common.DbDataAdapter.Update(), Terraria.GameContent.Skies.MoonLordSky.Update(), Terraria.GameContent.Skies.NebulaSky.Update(), Terraria.GameContent.Skies.SolarSky.Update(), Terraria.GameContent.Skies.StardustSky.Update(), Terraria.GameContent.Skies.VortexSky.Update(), Terraria.Graphics.Effects.FilterManager.Update(), Terraria.Graphics.Effects.OverlayManager.Update(), Terraria.Player.Update(), Terraria.Player.UpdateBiomes(), Terraria.Dust.UpdateDust(), ReLogic.Peripherals.RGB.ShaderSelector.ConditionalShader.UpdateVisibility(), System.Net.WebClient.UploadDataAsync(), System.Net.WebClient.UploadValuesAsync(), Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters(), System.ComponentModel.Container.ValidateName(), System.Decimal.DecCalc.VarDecDiv(), System.Threading.PortableThreadPool.WaitThread.WaitThreadStart(), Terraria.WorldGen.WavyCaverer(), Terraria.Utils.WordwrapStringSmart(), System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart(), System.IO.ChunkedMemoryStream.Write(), Terraria.Social.Steam.CloudSocialModule.Write(), Terraria.Utilities.FileUtilities.Write(), System.Xml.ArrayHelper< TArgument, TArray >.WriteArray(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterWriter.WriteArrayAsBytes(), System.Net.Security.NegotiateStream.WriteAsync< TAdapter >(), System.Net.Security.SslStream.WriteAsyncChunked< TIOAdapter >(), System.IO.StreamWriter.WriteAsyncInternal(), System.Xml.XmlSigningNodeWriter.WriteBase64Text(), System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Net.Http.HttpConnection.WriteBytesSlowAsync(), System.Reflection.Metadata.BlobBuilder.WriteBytesUnchecked(), System.Security.Cryptography.XmlKeyHelper.WriteCryptoBinary(), System.Buffers.BuffersExtensions.WriteMultiSegment< T >(), System.IO.StreamWriter.WriteSpan(), System.Diagnostics.Tracing.EventSource.WriteToAllListeners(), System.IO.BufferedStream.WriteToBuffer(), and System.IO.BufferedStream.WriteToBuffer().