Terraria: System.Math.DivRem
DivRem() [2/12]
static int System.Math.DivRem (int a, int b, out int result) inline static
Definition at line 329 of file Math.cs.
    {
        int num = a / b;
        result = a - num * b;
        return num;
    }
Referenced by System.Number.ConvertBigIntegerToFloatingPointBits(), System.Formats.Asn1.AsnWriter.DetermineCerBitStringTotalLength(), System.Numerics.BigInteger.DivRem(), System.Byte.DivRem(), System.Char.DivRem(), System.Int32.DivRem(), System.Int64.DivRem(), System.IntPtr.DivRem(), System.UIntPtr.DivRem(), System.Number.BigInteger.DivRem(), System.SByte.DivRem(), System.Int16.DivRem(), System.UInt32.DivRem(), System.UInt64.DivRem(), System.UInt16.DivRem(), System.Buffers.StandardFormat.Format(), System.Net.IPAddressParser.FormatIPv4AddressNumber(), Internal.Cryptography.UniversalCryptoEncryptor.GetCiphertextLength(), System.Security.Cryptography.SymmetricAlgorithm.GetCiphertextLengthBlockAligned(), System.Security.Cryptography.SymmetricAlgorithm.GetCiphertextLengthCfb(), System.Security.Cryptography.PemEncoding.GetEncodedSize(), System.Numerics.BigNumber.HexNumberToBigInteger(), System.Numerics.BigInteger.operator<<(), System.Numerics.BigInteger.operator>>(), System.Formats.Asn1.AsnWriter.PopTag(), System.Convert.ToBase64_CalculateAndValidateOutputLength(), System.Security.Cryptography.ToBase64Transform.TransformBlock(), System.Security.Cryptography.ToBase64Transform.TransformFinalBlock(), System.Number.Grisu3.TryDigitGenCounted(), System.Number.Grisu3.TryDigitGenShortest(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormatDateTimeG(), System.Buffers.Text.Utf8Formatter.TryFormatDateTimeO(), System.DateTimeFormat.TryFormatO(), System.Globalization.TimeSpanFormat.TryFormatStandard(), System.Number.TryUInt32ToDecStr(), System.Number.UInt32ToDecChars(), System.Number.UInt32ToDecChars(), System.Number.UInt32ToDecStr(), and System.Formats.Asn1.AsnWriter.WriteConstructedCerOctetString().