Terraria: System.Math.Clamp
Clamp() [1/13]
static byte System.Math.Clamp (byte value, byte min, byte max) inline static
Definition at line 435 of file Math.cs.
    {
        if (min > max)
        {
            ThrowMinMaxException(min, max);
        }
        if (value < min)
        {
            return min;
        }
        if (value > max)
        {
            return max;
        }
        return value;
    }
References System.value.
Referenced by System.Byte.Clamp(), System.Char.Clamp(), System.Decimal.Clamp(), System.Double.Clamp(), System.Single.Clamp(), System.Half.Clamp(), System.Int32.Clamp(), System.Int64.Clamp(), System.IntPtr.Clamp(), System.UIntPtr.Clamp(), System.SByte.Clamp(), System.Int16.Clamp(), System.UInt32.Clamp(), System.UInt64.Clamp(), System.UInt16.Clamp(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.GrowCore(), System.Number.TryNumberToDecimal(), System.Text.TranscodingStream.Write(), and System.Text.TranscodingStream.WriteAsync().