Terraria: System.Math.Cos
Cos()
static double System.Math.Cos (double d)
Referenced by Terraria.GameContent.Generation.ShapeBranch.ShapeBranch(), Terraria.NPC.AI(), Terraria.Projectile.AI_001(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_171_HallowBossRainbowStreak(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), System.Numerics.Complex.Cos(), System.Double.Cos(), System.Globalization.CalendricalCalculationsHelper.CosOfDegree(), Microsoft.Xna.Framework.Matrix.CreateFromAxisAngle(), Microsoft.Xna.Framework.Quaternion.CreateFromAxisAngle(), Microsoft.Xna.Framework.Matrix.CreateFromAxisAngle(), Microsoft.Xna.Framework.Quaternion.CreateFromAxisAngle(), Microsoft.Xna.Framework.Quaternion.CreateFromYawPitchRoll(), Microsoft.Xna.Framework.Quaternion.CreateFromYawPitchRoll(), Microsoft.Xna.Framework.Matrix.CreateRotationX(), Microsoft.Xna.Framework.Matrix.CreateRotationX(), Microsoft.Xna.Framework.Matrix.CreateRotationY(), Microsoft.Xna.Framework.Matrix.CreateRotationY(), Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Terraria.GameContent.Generation.ShapeRoot.DoRoot(), Terraria.Main.DrawMenu(), Terraria.Main.DrawNPCDirect(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), System.Numerics.Complex.Exp(), Terraria.DelegateMethods.CharacterPreview.Float(), System.Numerics.Complex.FromPolarCoordinates(), Terraria.Projectile.GetAlpha(), Terraria.Player.GetBackHandPosition(), Terraria.Projectile.GetFairyQueenWeaponsColor(), Terraria.Player.GetFrontHandPosition(), Terraria.Projectile.GetLastPrismHue(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetScale(), System.Threading.PortableThreadPool.HillClimbing.GetWaveComponent(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.GameContent.Skies.MartianSky.ZipBehavior.InitializeUfo(), Terraria.Player.ItemCheck_ApplyUseStyle(), Microsoft.Xna.Framework.Graphics.SpriteBatch.PlatformRenderBatch(), System.Numerics.Complex.Pow(), Terraria.GameContent.RGB.LowLifeShader.ProcessAnyDetail(), Terraria.GameContent.RGB.CultistShader.ProcessHighDetail(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.RGB.KeybindsMenuShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail(), Terraria.GameContent.RGB.MoonShader.ProcessHighDetail(), Terraria.DataStructures.SpriteDrawBuffer.QueueSprite(), Terraria.Graphics.TileBatch.RenderBatch(), Terraria.Utils.RotatedBy(), Terraria.Utils.RotatedBy(), System.Numerics.Complex.Sin(), Terraria.GameContent.Biomes.Desert.PitEntrance.SmootherStep(), System.Numerics.Complex.Tan(), Terraria.Utils.ToRotationVector2(), Terraria.Utils.Turn01ToCyclic010(), System.Math.unsafe(), Terraria.UI.Gamepad.GamepadMainMenuHandler.Update(), Terraria.GameContent.RGB.EyeballShader.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Graphics.CameraModifiers.PunchCameraModifier.Update(), Terraria.GameContent.UI.States.UIWorldLoad.UpdateGamepadSquiggle(), Terraria.Mount.UseDrill(), Terraria.GameContent.Golf.GolfHelper.ValidateShot(), and Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.ZigzagMove().