Terraria: SmartCursorHelper.Step_LawnMower
Step_LawnMower()
static void SmartCursorHelper.Step_LawnMower (SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
     {
         int reachableStartX = providedInfo.reachableStartX;
         int reachableStartY = providedInfo.reachableStartY;
         int reachableEndX = providedInfo.reachableEndX;
         int reachableEndY = providedInfo.reachableEndY;
         _ = providedInfo.screenTargetX;
         _ = providedInfo.screenTargetY;
         if (providedInfo.item.type != 4049 || fX != -1 || fY != -1)
         {
             return;
         }
         _targets.Clear();
         for (int i = reachableStartX; i <= reachableEndX; i++)
         {
             for (int j = reachableStartY; j <= reachableEndY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile.active() && (tile.type == 2 || tile.type == 109))
                 {
                     _targets.Add(new Tuple<int, int>(i, j));
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int k = 0; k < _targets.Count; k++)
             {
                 float num2 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                 if (num == -1f || num2 < num)
                 {
                     num = num2;
                     tuple = _targets[k];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
             {
                 fX = tuple.Item1;
                 fY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Tile.active(), Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Main.tile, Item.type, and Tile.type.
Referenced by SmartCursorLookup().