Terraria: SmartCursorHelper.Step_Acorns
Step_Acorns()
static void SmartCursorHelper.Step_Acorns (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         if (providedInfo.item.type != 27 || focusedX != -1 || focusedY != -1 || providedInfo.reachableStartY <= 20)
         {
             return;
         }
         _targets.Clear();
         for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
         {
             for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 Tile tile2 = Main.tile[i, j - 1];
                 Tile tile3 = Main.tile[i, j + 1];
                 Tile tile4 = Main.tile[i - 1, j];
                 Tile tile5 = Main.tile[i + 1, j];
                 Tile tile6 = Main.tile[i - 2, j];
                 Tile tile7 = Main.tile[i + 2, j];
                 Tile tile8 = Main.tile[i - 3, j];
                 Tile tile9 = Main.tile[i + 3, j];
                 if ((tile.active() && !Main.tileCut[tile.type] && !TileID.Sets.BreakableWhenPlacing[tile.type]) || (tile2.active() && !Main.tileCut[tile2.type] && !TileID.Sets.BreakableWhenPlacing[tile2.type]) || (tile4.active() && TileID.Sets.CommonSapling[tile4.type]) || (tile5.active() && TileID.Sets.CommonSapling[tile5.type]) || (tile6.active() && TileID.Sets.CommonSapling[tile6.type]) || (tile7.active() && TileID.Sets.CommonSapling[tile7.type]) || (tile8.active() && TileID.Sets.CommonSapling[tile8.type]) || (tile9.active() && TileID.Sets.CommonSapling[tile9.type]) || !tile3.active() || !WorldGen.SolidTile2(tile3))
                 {
                     continue;
                 }
                 switch (tile3.type)
                 {
                 case 60:
                     if (WorldGen.EmptyTileCheck(i - 2, i + 2, j - 20, j, 20))
                     {
                         _targets.Add(new Tuple<int, int>(i, j));
                     }
                     break;
                 case 2:
                 case 23:
                 case 53:
                 case 109:
                 case 112:
                 case 116:
                 case 147:
                 case 199:
                 case 234:
                 case 477:
                 case 492:
                 case 633:
                 case 661:
                 case 662:
                     if (tile4.liquid == 0 && tile.liquid == 0 && tile5.liquid == 0 && WorldGen.EmptyTileCheck(i - 2, i + 2, j - 20, j, 20))
                     {
                         _targets.Add(new Tuple<int, int>(i, j));
                     }
                     break;
                 }
             }
         }
         _toRemove.Clear();
         for (int k = 0; k < _targets.Count; k++)
         {
             bool flag = false;
             for (int l = -1; l < 2; l += 2)
             {
                 Tile tile10 = Main.tile[_targets[k].Item1 + l, _targets[k].Item2 + 1];
                 if (tile10.active())
                 {
                     switch (tile10.type)
                     {
                     case 2:
                     case 23:
                     case 53:
                     case 60:
                     case 109:
                     case 112:
                     case 116:
                     case 147:
                     case 199:
                     case 234:
                     case 477:
                     case 492:
                     case 633:
                     case 661:
                     case 662:
                         flag = true;
                         break;
                     }
                 }
             }
             if (!flag)
             {
                 _toRemove.Add(_targets[k]);
             }
         }
         for (int m = 0; m < _toRemove.Count; m++)
         {
             _targets.Remove(_toRemove[m]);
         }
         _toRemove.Clear();
         if (_targets.Count > 0)
         {
             float num = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int n = 0; n < _targets.Count; n++)
             {
                 float num2 = Vector2.Distance(new Vector2(_targets[n].Item1, _targets[n].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                 if (num == -1f || num2 < num)
                 {
                     num = num2;
                     tuple = _targets[n];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
             {
                 focusedX = tuple.Item1;
                 focusedY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, _toRemove, Tile.active(), TileID.Sets.BreakableWhenPlacing, TileID.Sets.CommonSapling, WorldGen.EmptyTileCheck(), Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, Tile.liquid, SmartCursorHelper.SmartCursorUsageInfo.mouse, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, WorldGen.SolidTile2(), Main.tile, Main.tileCut, Item.type, and Tile.type.
Referenced by SmartCursorLookup().