Terraria: SmartCursorHelper.Step_Walls
Step_Walls()
static void SmartCursorHelper.Step_Walls (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         int width = providedInfo.player.width;
         int height = providedInfo.player.height;
         if (providedInfo.item.createWall <= 0 || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         _targets.Clear();
         for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
         {
             for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile.wall == 0 && (!tile.active() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type]) && Collision.CanHitWithCheck(providedInfo.position, width, height, new Vector2(i, j) * 16f, 16, 16, DelegateMethods.NotDoorStand))
                 {
                     bool flag = false;
                     if (Main.tile[i - 1, j].active() || Main.tile[i - 1, j].wall > 0)
                     {
                         flag = true;
                     }
                     if (Main.tile[i + 1, j].active() || Main.tile[i + 1, j].wall > 0)
                     {
                         flag = true;
                     }
                     if (Main.tile[i, j - 1].active() || Main.tile[i, j - 1].wall > 0)
                     {
                         flag = true;
                     }
                     if (Main.tile[i, j + 1].active() || Main.tile[i, j + 1].wall > 0)
                     {
                         flag = true;
                     }
                     if (WorldGen.IsOpenDoorAnchorFrame(i, j))
                     {
                         flag = false;
                     }
                     if (flag)
                     {
                         _targets.Add(new Tuple<int, int>(i, j));
                     }
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int k = 0; k < _targets.Count; k++)
             {
                 float num2 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                 if (num == -1f || num2 < num)
                 {
                     num = num2;
                     tuple = _targets[k];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
             {
                 focusedX = tuple.Item1;
                 focusedY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Tile.active(), Collision.CanHitWithCheck(), Item.createWall, Entity.height, Collision.InTileBounds(), WorldGen.IsOpenDoorAnchorFrame(), SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, DelegateMethods.NotDoorStand(), SmartCursorHelper.SmartCursorUsageInfo.player, SmartCursorHelper.SmartCursorUsageInfo.position, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Main.tile, Main.tileSolid, Main.tileSolidTop, Tile.type, Tile.wall, and Entity.width.
Referenced by SmartCursorLookup().