Terraria: System.Linq.OrderedEnumerable.TryGetLast
TryGetLast() [2/3]
TElement System.Linq.OrderedEnumerable< TElement, TKey >.TryGetLast (int minIdx, int maxIdx, out bool found) inline
Definition at line 200 of file OrderedEnumerable.cs.
    {
        Buffer<TElement> buffer = new Buffer<TElement>(_source);
        int count = buffer._count;
        if (minIdx >= count)
        {
            found = false;
            return default(TElement);
        }
        found = true;
        if (maxIdx >= count - 1)
        {
            return Last(buffer);
        }
        return GetEnumerableSorter().ElementAt(buffer._items, count, maxIdx);
    }
References System.Linq.OrderedEnumerable< TElement, TKey >._source, System.buffer, System.Linq.count, System.Linq.EnumerableSorter< TElement, TKey >.ElementAt(), System.Linq.OrderedEnumerable< TElement, TKey >.GetEnumerableSorter(), and System.Linq.OrderedEnumerable< TElement, TKey >.Last().