Terraria: SmartCursorHelper.Step_Pigronata
Step_Pigronata()
static void SmartCursorHelper.Step_Pigronata (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         if (providedInfo.item.createTile != 454 || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         _targets.Clear();
         for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
         {
             for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY && !((double)j > Main.worldSurface - 2.0); j++)
             {
                 bool flag = true;
                 for (int k = i - 2; k <= i + 1; k++)
                 {
                     for (int l = j - 1; l <= j + 2; l++)
                     {
                         Tile tile = Main.tile[k, l];
                         if (l == j - 1)
{
                             if (!WorldGen.SolidTile(tile))
{
                                 flag = false;
                             }
                         }
                         else if (tile.active() && (!Main.tileCut[tile.type] || tile.type == 454))
{
                             flag = false;
                         }
                     }
                 }
                 if (flag)
                 {
                     _targets.Add(new Tuple<int, int>(i, j));
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int m = 0; m < _targets.Count; m++)
             {
                 float num2 = Vector2.Distance(new Vector2(_targets[m].Item1, _targets[m].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                 if (num == -1f || num2 < num)
                 {
                     num = num2;
                     tuple = _targets[m];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
             {
                 focusedX = tuple.Item1;
                 focusedY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Tile.active(), Item.createTile, Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, WorldGen.SolidTile(), Main.tile, Main.tileCut, Tile.type, and Main.worldSurface.
Referenced by SmartCursorLookup().