Terraria: SmartCursorHelper.Step_PaintScrapper
Step_PaintScrapper()
static void SmartCursorHelper.Step_PaintScrapper (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         if (!ItemID.Sets.IsPaintScraper[providedInfo.item.type] || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         _targets.Clear();
         for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
         {
             for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
             {
                 Tile tile = Main.tile[i, j];
                 bool flag = false;
                 if (tile.active())
                 {
                     flag |= tile.color() > 0;
                     flag |= tile.type == 184;
                     flag |= tile.fullbrightBlock();
                     flag |= tile.invisibleBlock();
                 }
                 if (tile.wall > 0)
                 {
                     flag |= tile.wallColor() > 0;
                     flag |= tile.fullbrightWall();
                     flag |= tile.invisibleWall();
                 }
                 if (flag)
                 {
                     _targets.Add(new Tuple<int, int>(i, j));
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int k = 0; k < _targets.Count; k++)
             {
                 float num2 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                 if (num == -1f || num2 < num)
                 {
                     num = num2;
                     tuple = _targets[k];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
             {
                 focusedX = tuple.Item1;
                 focusedY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Tile.active(), Tile.color(), Tile.fullbrightBlock(), Tile.fullbrightWall(), Collision.InTileBounds(), Tile.invisibleBlock(), Tile.invisibleWall(), ItemID.Sets.IsPaintScraper, SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Main.tile, Item.type, Tile.type, Tile.wall, and Tile.wallColor().
Referenced by SmartCursorLookup().