Terraria: SmartCursorHelper.Step_ForceCursorToAnyMinableThing
Step_ForceCursorToAnyMinableThing()
static void SmartCursorHelper.Step_ForceCursorToAnyMinableThing (SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
     {
         int reachableStartX = providedInfo.reachableStartX;
         int reachableStartY = providedInfo.reachableStartY;
         int reachableEndX = providedInfo.reachableEndX;
         int reachableEndY = providedInfo.reachableEndY;
         _ = providedInfo.screenTargetX;
         _ = providedInfo.screenTargetY;
         Vector2 mouse = providedInfo.mouse;
         Item item = providedInfo.item;
         if (fX != -1 || fY != -1 || PlayerInput.UsingGamepad)
         {
             return;
         }
         Point point = mouse.ToTileCoordinates();
         int x = point.X;
         int y = point.Y;
         if (Collision.InTileBounds(x, y, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
         {
             Tile tile = Main.tile[x, y];
             bool flag = tile.active() && WorldGen.CanKillTile(x, y) && (!Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type]);
             if (flag && Main.tileAxe[tile.type] && item.axe < 1)
             {
                 flag = false;
             }
             if (flag && Main.tileHammer[tile.type] && item.hammer < 1)
             {
                 flag = false;
             }
             if (flag && !Main.tileHammer[tile.type] && !Main.tileAxe[tile.type] && item.pick < 1)
             {
                 flag = false;
             }
             if (flag)
             {
                 fX = x;
                 fY = y;
             }
         }
     }
References Tile.active(), Item.axe, WorldGen.CanKillTile(), Item.hammer, Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, Item.pick, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Main.tile, Main.tileAxe, Main.tileHammer, Main.tileSolid, Main.tileSolidTop, Tile.type, and PlayerInput.UsingGamepad.
Referenced by SmartCursorLookup().