Terraria: SmartCursorHelper.SmartCursorLookup
SmartCursorLookup()
static void SmartCursorHelper.SmartCursorLookup (Player player) inline static
     {
         Main.SmartCursorShowing = false;
         if (!Main.SmartCursorIsUsed)
         {
             return;
         }
         SmartCursorUsageInfo smartCursorUsageInfo = new SmartCursorUsageInfo
         {
             player = player,
             item = player.inventory[player.selectedItem],
             mouse = Main.MouseWorld,
             position = player.position,
             Center = player.Center
         };
         _ = player.gravDir;
         int tileTargetX = Player.tileTargetX;
         int tileTargetY = Player.tileTargetY;
         int tileRangeX = Player.tileRangeX;
         int tileRangeY = Player.tileRangeY;
         smartCursorUsageInfo.screenTargetX = Utils.Clamp(tileTargetX, 10, Main.maxTilesX - 10);
         smartCursorUsageInfo.screenTargetY = Utils.Clamp(tileTargetY, 10, Main.maxTilesY - 10);
         if (Main.tile[smartCursorUsageInfo.screenTargetX, smartCursorUsageInfo.screenTargetY] == null)
         {
             return;
         }
         bool num = IsHoveringOverAnInteractibleTileThatBlocksSmartCursor(smartCursorUsageInfo);
         TryFindingPaintInplayerInventory(smartCursorUsageInfo, out smartCursorUsageInfo.paintLookup, out smartCursorUsageInfo.paintCoatingLookup);
         int tileBoost = smartCursorUsageInfo.item.tileBoost;
         smartCursorUsageInfo.reachableStartX = (int)(player.position.X / 16f) - tileRangeX - tileBoost + 1;
         smartCursorUsageInfo.reachableEndX = (int)((player.position.X + (float)player.width) / 16f) + tileRangeX + tileBoost - 1;
         smartCursorUsageInfo.reachableStartY = (int)(player.position.Y / 16f) - tileRangeY - tileBoost + 1;
         smartCursorUsageInfo.reachableEndY = (int)((player.position.Y + (float)player.height) / 16f) + tileRangeY + tileBoost - 2;
         smartCursorUsageInfo.reachableStartX = Utils.Clamp(smartCursorUsageInfo.reachableStartX, 10, Main.maxTilesX - 10);
         smartCursorUsageInfo.reachableEndX = Utils.Clamp(smartCursorUsageInfo.reachableEndX, 10, Main.maxTilesX - 10);
         smartCursorUsageInfo.reachableStartY = Utils.Clamp(smartCursorUsageInfo.reachableStartY, 10, Main.maxTilesY - 10);
         smartCursorUsageInfo.reachableEndY = Utils.Clamp(smartCursorUsageInfo.reachableEndY, 10, Main.maxTilesY - 10);
         if (!num || smartCursorUsageInfo.screenTargetX < smartCursorUsageInfo.reachableStartX || smartCursorUsageInfo.screenTargetX > smartCursorUsageInfo.reachableEndX || smartCursorUsageInfo.screenTargetY < smartCursorUsageInfo.reachableStartY || smartCursorUsageInfo.screenTargetY > smartCursorUsageInfo.reachableEndY)
         {
             _grappleTargets.Clear();
             int[] grappling = player.grappling;
             int grapCount = player.grapCount;
             for (int i = 0; i < grapCount; i++)
             {
                 Projectile obj = Main.projectile[grappling[i]];
                 int item = (int)obj.Center.X / 16;
                 int item2 = (int)obj.Center.Y / 16;
                 _grappleTargets.Add(new Tuple<int, int>(item, item2));
             }
             int fX = -1;
             int fY = -1;
             if (!Player.SmartCursorSettings.SmartAxeAfterPickaxe)
             {
                 Step_Axe(smartCursorUsageInfo, ref fX, ref fY);
             }
             Step_ForceCursorToAnyMinableThing(smartCursorUsageInfo, ref fX, ref fY);
             Step_Pickaxe_MineShinies(smartCursorUsageInfo, ref fX, ref fY);
             Step_Pickaxe_MineSolids(player, smartCursorUsageInfo, _grappleTargets, ref fX, ref fY);
             if (Player.SmartCursorSettings.SmartAxeAfterPickaxe)
             {
                 Step_Axe(smartCursorUsageInfo, ref fX, ref fY);
             }
             Step_ColoredWrenches(smartCursorUsageInfo, ref fX, ref fY);
             Step_MulticolorWrench(smartCursorUsageInfo, ref fX, ref fY);
             Step_Hammers(smartCursorUsageInfo, ref fX, ref fY);
             Step_ActuationRod(smartCursorUsageInfo, ref fX, ref fY);
             Step_WireCutter(smartCursorUsageInfo, ref fX, ref fY);
             Step_Platforms(smartCursorUsageInfo, ref fX, ref fY);
             Step_MinecartTracks(smartCursorUsageInfo, ref fX, ref fY);
             Step_Walls(smartCursorUsageInfo, ref fX, ref fY);
             Step_PumpkinSeeds(smartCursorUsageInfo, ref fX, ref fY);
             Step_GrassSeeds(smartCursorUsageInfo, ref fX, ref fY);
             Step_Pigronata(smartCursorUsageInfo, ref fX, ref fY);
             Step_Boulders(smartCursorUsageInfo, ref fX, ref fY);
             Step_Torch(smartCursorUsageInfo, ref fX, ref fY);
             Step_LawnMower(smartCursorUsageInfo, ref fX, ref fY);
             Step_BlocksFilling(smartCursorUsageInfo, ref fX, ref fY);
             Step_BlocksLines(smartCursorUsageInfo, ref fX, ref fY);
             Step_PaintRoller(smartCursorUsageInfo, ref fX, ref fY);
             Step_PaintBrush(smartCursorUsageInfo, ref fX, ref fY);
             Step_PaintScrapper(smartCursorUsageInfo, ref fX, ref fY);
             Step_Acorns(smartCursorUsageInfo, ref fX, ref fY);
             Step_GemCorns(smartCursorUsageInfo, ref fX, ref fY);
             Step_EmptyBuckets(smartCursorUsageInfo, ref fX, ref fY);
             Step_Actuators(smartCursorUsageInfo, ref fX, ref fY);
             Step_AlchemySeeds(smartCursorUsageInfo, ref fX, ref fY);
             Step_PlanterBox(smartCursorUsageInfo, ref fX, ref fY);
             Step_ClayPots(smartCursorUsageInfo, ref fX, ref fY);
             Step_StaffOfRegrowth(smartCursorUsageInfo, ref fX, ref fY);
             if (fX != -1 && fY != -1)
             {
                 Main.SmartCursorX = (Player.tileTargetX = fX);
                 Main.SmartCursorY = (Player.tileTargetY = fY);
                 Main.SmartCursorShowing = true;
             }
             _grappleTargets.Clear();
         }
     }
References _grappleTargets, Entity.Center, Player.grapCount, Player.grappling, Player.gravDir, Entity.height, Player.inventory, IsHoveringOverAnInteractibleTileThatBlocksSmartCursor(), SmartCursorHelper.SmartCursorUsageInfo.item, Main.maxTilesX, Main.maxTilesY, Main.MouseWorld, SmartCursorHelper.SmartCursorUsageInfo.paintCoatingLookup, SmartCursorHelper.SmartCursorUsageInfo.paintLookup, Entity.position, Main.projectile, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Player.selectedItem, Player.SmartCursorSettings.SmartAxeAfterPickaxe, Main.SmartCursorIsUsed, Main.SmartCursorShowing, Main.SmartCursorX, Main.SmartCursorY, Step_Acorns(), Step_ActuationRod(), Step_Actuators(), Step_AlchemySeeds(), Step_Axe(), Step_BlocksFilling(), Step_BlocksLines(), Step_Boulders(), Step_ClayPots(), Step_ColoredWrenches(), Step_EmptyBuckets(), Step_ForceCursorToAnyMinableThing(), Step_GemCorns(), Step_GrassSeeds(), Step_Hammers(), Step_LawnMower(), Step_MinecartTracks(), Step_MulticolorWrench(), Step_PaintBrush(), Step_PaintRoller(), Step_PaintScrapper(), Step_Pickaxe_MineShinies(), Step_Pickaxe_MineSolids(), Step_Pigronata(), Step_PlanterBox(), Step_Platforms(), Step_PumpkinSeeds(), Step_StaffOfRegrowth(), Step_Torch(), Step_Walls(), Step_WireCutter(), Main.tile, Item.tileBoost, Player.tileRangeX, Player.tileRangeY, Player.tileTargetX, Player.tileTargetY, TryFindingPaintInplayerInventory(), and Entity.width.
Referenced by Player.Update().