Terraria: SmartCursorHelper.Step_ColoredWrenches
Step_ColoredWrenches()
static void SmartCursorHelper.Step_ColoredWrenches (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         if ((providedInfo.item.type != 509 && providedInfo.item.type != 850 && providedInfo.item.type != 851 && providedInfo.item.type != 3612) || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         _targets.Clear();
         int num = 0;
         if (providedInfo.item.type == 509)
         {
             num = 1;
         }
         if (providedInfo.item.type == 850)
         {
             num = 2;
         }
         if (providedInfo.item.type == 851)
         {
             num = 3;
         }
         if (providedInfo.item.type == 3612)
         {
             num = 4;
         }
         bool flag = false;
         if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire() && num == 1)
         {
             flag = true;
         }
         if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire2() && num == 2)
         {
             flag = true;
         }
         if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire3() && num == 3)
         {
             flag = true;
         }
         if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].wire4() && num == 4)
         {
             flag = true;
         }
         if (!flag)
         {
             for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
             {
                 for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                 {
                     Tile tile = Main.tile[i, j];
                     if ((!tile.wire() || num != 1) && (!tile.wire2() || num != 2) && (!tile.wire3() || num != 3) && (!tile.wire4() || num != 4))
                     {
                         continue;
                     }
                     if (num == 1)
                     {
                         if (!Main.tile[i - 1, j].wire())
{
                             _targets.Add(new Tuple<int, int>(i - 1, j));
                         }
                         if (!Main.tile[i + 1, j].wire())
{
                             _targets.Add(new Tuple<int, int>(i + 1, j));
                         }
                         if (!Main.tile[i, j - 1].wire())
{
                             _targets.Add(new Tuple<int, int>(i, j - 1));
                         }
                         if (!Main.tile[i, j + 1].wire())
{
                             _targets.Add(new Tuple<int, int>(i, j + 1));
                         }
                     }
                     if (num == 2)
                     {
                         if (!Main.tile[i - 1, j].wire2())
{
                             _targets.Add(new Tuple<int, int>(i - 1, j));
                         }
                         if (!Main.tile[i + 1, j].wire2())
{
                             _targets.Add(new Tuple<int, int>(i + 1, j));
                         }
                         if (!Main.tile[i, j - 1].wire2())
{
                             _targets.Add(new Tuple<int, int>(i, j - 1));
                         }
                         if (!Main.tile[i, j + 1].wire2())
{
                             _targets.Add(new Tuple<int, int>(i, j + 1));
                         }
                     }
                     if (num == 3)
                     {
                         if (!Main.tile[i - 1, j].wire3())
{
                             _targets.Add(new Tuple<int, int>(i - 1, j));
                         }
                         if (!Main.tile[i + 1, j].wire3())
{
                             _targets.Add(new Tuple<int, int>(i + 1, j));
                         }
                         if (!Main.tile[i, j - 1].wire3())
{
                             _targets.Add(new Tuple<int, int>(i, j - 1));
                         }
                         if (!Main.tile[i, j + 1].wire3())
{
                             _targets.Add(new Tuple<int, int>(i, j + 1));
                         }
                     }
                     if (num == 4)
                     {
                         if (!Main.tile[i - 1, j].wire4())
{
                             _targets.Add(new Tuple<int, int>(i - 1, j));
                         }
                         if (!Main.tile[i + 1, j].wire4())
{
                             _targets.Add(new Tuple<int, int>(i + 1, j));
                         }
                         if (!Main.tile[i, j - 1].wire4())
{
                             _targets.Add(new Tuple<int, int>(i, j - 1));
                         }
                         if (!Main.tile[i, j + 1].wire4())
{
                             _targets.Add(new Tuple<int, int>(i, j + 1));
                         }
                     }
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num2 = -1f;
             Tuple<int, int> tuple = _targets[0];
             for (int k = 0; k < _targets.Count; k++)
             {
                 float num3 = Vector2.Distance(new Vector2(_targets[k].Item1, _targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                 if (num2 == -1f || num3 < num2)
                 {
                     num2 = num3;
                     tuple = _targets[k];
                 }
             }
             if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
             {
                 focusedX = tuple.Item1;
                 focusedY = tuple.Item2;
             }
         }
         _targets.Clear();
     }
References _targets, Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, SmartCursorHelper.SmartCursorUsageInfo.mouse, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, SmartCursorHelper.SmartCursorUsageInfo.screenTargetX, SmartCursorHelper.SmartCursorUsageInfo.screenTargetY, Main.tile, Item.type, Tile.wire(), Tile.wire2(), Tile.wire3(), and Tile.wire4().
Referenced by SmartCursorLookup().