Terraria: SmartCursorHelper.Step_Hammers
Step_Hammers()
static void SmartCursorHelper.Step_Hammers (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
     {
         int width = providedInfo.player.width;
         int height = providedInfo.player.height;
         if (providedInfo.item.hammer > 0 && focusedX == -1 && focusedY == -1)
         {
             Vector2 vector = providedInfo.mouse - providedInfo.Center;
             int num = Math.Sign(vector.X);
             int num2 = Math.Sign(vector.Y);
             if (Math.Abs(vector.X) > Math.Abs(vector.Y) * 3f)
             {
                 num2 = 0;
                 providedInfo.mouse.Y = providedInfo.Center.Y;
             }
             if (Math.Abs(vector.Y) > Math.Abs(vector.X) * 3f)
             {
                 num = 0;
                 providedInfo.mouse.X = providedInfo.Center.X;
             }
             _ = (int)providedInfo.Center.X / 16;
             _ = (int)providedInfo.Center.Y / 16;
             _points.Clear();
             _endpoints.Clear();
             int num3 = 1;
             if (num2 == -1 && num != 0)
             {
                 num3 = -1;
             }
             int num4 = (int)((providedInfo.position.X + (float)(width / 2) + (float)((width / 2 - 1) * num)) / 16f);
             int num5 = (int)(((double)providedInfo.position.Y + 0.1) / 16.0);
             if (num3 == -1)
             {
                 num5 = (int)((providedInfo.position.Y + (float)height - 1f) / 16f);
             }
             int num6 = width / 16 + ((width % 16 != 0) ? 1 : 0);
             int num7 = height / 16 + ((height % 16 != 0) ? 1 : 0);
             if (num != 0)
             {
                 for (int i = 0; i < num7; i++)
                 {
                     if (Main.tile[num4, num5 + i * num3] != null)
                     {
                         _points.Add(new Tuple<int, int>(num4, num5 + i * num3));
                     }
                 }
             }
             if (num2 != 0)
             {
                 for (int j = 0; j < num6; j++)
                 {
                     if (Main.tile[(int)(providedInfo.position.X / 16f) + j, num5] != null)
                     {
                         _points.Add(new Tuple<int, int>((int)(providedInfo.position.X / 16f) + j, num5));
                     }
                 }
             }
             int num8 = (int)((providedInfo.mouse.X + (float)((width / 2 - 1) * num)) / 16f);
             int num9 = (int)(((double)providedInfo.mouse.Y + 0.1 - (double)(height / 2 + 1)) / 16.0);
             if (num3 == -1)
             {
                 num9 = (int)((providedInfo.mouse.Y + (float)(height / 2) - 1f) / 16f);
             }
             if (providedInfo.player.gravDir == -1f && num2 == 0)
             {
                 num9++;
             }
             if (num9 < 10)
             {
                 num9 = 10;
             }
             if (num9 > Main.maxTilesY - 10)
             {
                 num9 = Main.maxTilesY - 10;
             }
             int num10 = width / 16 + ((width % 16 != 0) ? 1 : 0);
             int num11 = height / 16 + ((height % 16 != 0) ? 1 : 0);
             if (num != 0)
             {
                 for (int k = 0; k < num11; k++)
                 {
                     if (Main.tile[num8, num9 + k * num3] != null)
                     {
                         _endpoints.Add(new Tuple<int, int>(num8, num9 + k * num3));
                     }
                 }
             }
             if (num2 != 0)
             {
                 for (int l = 0; l < num10; l++)
                 {
                     if (Main.tile[(int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num9] != null)
                     {
                         _endpoints.Add(new Tuple<int, int>((int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num9));
                     }
                 }
             }
             _targets.Clear();
             while (_points.Count > 0)
             {
                 Tuple<int, int> tuple = _points[0];
                 Tuple<int, int> tuple2 = _endpoints[0];
                 Tuple<int, int> tuple3 = Collision.TupleHitLineWall(tuple.Item1, tuple.Item2, tuple2.Item1, tuple2.Item2);
                 if (tuple3.Item1 == -1 || tuple3.Item2 == -1)
                 {
                     _points.Remove(tuple);
                     _endpoints.Remove(tuple2);
                     continue;
                 }
                 if (tuple3.Item1 != tuple2.Item1 || tuple3.Item2 != tuple2.Item2)
                 {
                     _targets.Add(tuple3);
                 }
                 _ = Main.tile[tuple3.Item1, tuple3.Item2];
                 if (Collision.HitWallSubstep(tuple3.Item1, tuple3.Item2))
                 {
                     _targets.Add(tuple3);
                 }
                 _points.Remove(tuple);
                 _endpoints.Remove(tuple2);
             }
             if (_targets.Count > 0)
             {
                 float num12 = -1f;
                 Tuple<int, int> tuple4 = null;
                 for (int m = 0; m < _targets.Count; m++)
                 {
                     if (!Main.tile[_targets[m].Item1, _targets[m].Item2].active() || Main.tile[_targets[m].Item1, _targets[m].Item2].type != 26)
                     {
                         float num13 = Vector2.Distance(new Vector2(_targets[m].Item1, _targets[m].Item2) * 16f + Vector2.One * 8f, providedInfo.Center);
                         if (num12 == -1f || num13 < num12)
{
                             num12 = num13;
                             tuple4 = _targets[m];
                         }
                     }
                 }
                 if (tuple4 != null && Collision.InTileBounds(tuple4.Item1, tuple4.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                 {
                     providedInfo.player.poundRelease = false;
                     focusedX = tuple4.Item1;
                     focusedY = tuple4.Item2;
                 }
             }
             _targets.Clear();
             _points.Clear();
             _endpoints.Clear();
         }
         if (providedInfo.item.hammer <= 0 || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         _targets.Clear();
         for (int n = providedInfo.reachableStartX; n <= providedInfo.reachableEndX; n++)
         {
             for (int num14 = providedInfo.reachableStartY; num14 <= providedInfo.reachableEndY; num14++)
             {
                 if (Main.tile[n, num14].wall > 0 && Collision.HitWallSubstep(n, num14))
                 {
                     _targets.Add(new Tuple<int, int>(n, num14));
                 }
             }
         }
         if (_targets.Count > 0)
         {
             float num15 = -1f;
             Tuple<int, int> tuple5 = null;
             for (int num16 = 0; num16 < _targets.Count; num16++)
             {
                 if (!Main.tile[_targets[num16].Item1, _targets[num16].Item2].active() || Main.tile[_targets[num16].Item1, _targets[num16].Item2].type != 26)
                 {
                     float num17 = Vector2.Distance(new Vector2(_targets[num16].Item1, _targets[num16].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                     if (num15 == -1f || num17 < num15)
                     {
                         num15 = num17;
                         tuple5 = _targets[num16];
                     }
                 }
             }
             if (tuple5 != null && Collision.InTileBounds(tuple5.Item1, tuple5.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
             {
                 providedInfo.player.poundRelease = false;
                 focusedX = tuple5.Item1;
                 focusedY = tuple5.Item2;
             }
         }
         _targets.Clear();
     }
References _endpoints, _points, _targets, Tile.active(), SmartCursorHelper.SmartCursorUsageInfo.Center, Player.gravDir, Item.hammer, Entity.height, Collision.HitWallSubstep(), Collision.InTileBounds(), SmartCursorHelper.SmartCursorUsageInfo.item, Main.maxTilesY, SmartCursorHelper.SmartCursorUsageInfo.mouse, SmartCursorHelper.SmartCursorUsageInfo.player, SmartCursorHelper.SmartCursorUsageInfo.position, Player.poundRelease, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Main.tile, Collision.TupleHitLineWall(), Tile.type, Tile.wall, and Entity.width.
Referenced by SmartCursorLookup().