Terraria: SmartCursorHelper.Step_Pickaxe_MineSolids
Step_Pickaxe_MineSolids()
static void SmartCursorHelper.Step_Pickaxe_MineSolids (Player player, SmartCursorUsageInfo providedInfo, List< Tuple< int, int >> grappleTargets, ref int focusedX, ref int focusedY) inline static private
     {
         int width = player.width;
         int height = player.height;
         int direction = player.direction;
         Vector2 center = player.Center;
         Vector2 position = player.position;
         float gravDir = player.gravDir;
         int whoAmI = player.whoAmI;
         if (providedInfo.item.pick <= 0 || focusedX != -1 || focusedY != -1)
         {
             return;
         }
         if (PlayerInput.UsingGamepad)
         {
             Vector2 navigatorDirections = PlayerInput.Triggers.Current.GetNavigatorDirections();
             Vector2 gamepadThumbstickLeft = PlayerInput.GamepadThumbstickLeft;
             Vector2 gamepadThumbstickRight = PlayerInput.GamepadThumbstickRight;
             if (navigatorDirections == Vector2.Zero && gamepadThumbstickLeft.Length() < 0.05f && gamepadThumbstickRight.Length() < 0.05f)
             {
                 providedInfo.mouse = center + new Vector2(direction * 1000, 0f);
             }
         }
         Vector2 vector = providedInfo.mouse - center;
         int num = Math.Sign(vector.X);
         int num2 = Math.Sign(vector.Y);
         if (Math.Abs(vector.X) > Math.Abs(vector.Y) * 3f)
         {
             num2 = 0;
             providedInfo.mouse.Y = center.Y;
         }
         if (Math.Abs(vector.Y) > Math.Abs(vector.X) * 3f)
         {
             num = 0;
             providedInfo.mouse.X = center.X;
         }
         _ = (int)center.X / 16;
         _ = (int)center.Y / 16;
         _points.Clear();
         _endpoints.Clear();
         int num3 = 1;
         if (num2 == -1 && num != 0)
         {
             num3 = -1;
         }
         int num4 = (int)((position.X + (float)(width / 2) + (float)((width / 2 - 1) * num)) / 16f);
         int num5 = (int)(((double)position.Y + 0.1) / 16.0);
         if (num3 == -1)
         {
             num5 = (int)((position.Y + (float)height - 1f) / 16f);
         }
         int num6 = width / 16 + ((width % 16 != 0) ? 1 : 0);
         int num7 = height / 16 + ((height % 16 != 0) ? 1 : 0);
         if (num != 0)
         {
             for (int i = 0; i < num7; i++)
             {
                 if (Main.tile[num4, num5 + i * num3] != null)
                 {
                     _points.Add(new Tuple<int, int>(num4, num5 + i * num3));
                 }
             }
         }
         if (num2 != 0)
         {
             for (int j = 0; j < num6; j++)
             {
                 if (Main.tile[(int)(position.X / 16f) + j, num5] != null)
                 {
                     _points.Add(new Tuple<int, int>((int)(position.X / 16f) + j, num5));
                 }
             }
         }
         int num8 = (int)((providedInfo.mouse.X + (float)((width / 2 - 1) * num)) / 16f);
         int num9 = (int)(((double)providedInfo.mouse.Y + 0.1 - (double)(height / 2 + 1)) / 16.0);
         if (num3 == -1)
         {
             num9 = (int)((providedInfo.mouse.Y + (float)(height / 2) - 1f) / 16f);
         }
         if (gravDir == -1f && num2 == 0)
         {
             num9++;
         }
         if (num9 < 10)
         {
             num9 = 10;
         }
         if (num9 > Main.maxTilesY - 10)
         {
             num9 = Main.maxTilesY - 10;
         }
         int num10 = width / 16 + ((width % 16 != 0) ? 1 : 0);
         int num11 = height / 16 + ((height % 16 != 0) ? 1 : 0);
         if (WorldGen.InWorld(num8, num9, 40))
         {
             if (num != 0)
             {
                 for (int k = 0; k < num11; k++)
                 {
                     if (Main.tile[num8, num9 + k * num3] != null)
                     {
                         _endpoints.Add(new Tuple<int, int>(num8, num9 + k * num3));
                     }
                 }
             }
             if (num2 != 0)
             {
                 for (int l = 0; l < num10; l++)
                 {
                     if (Main.tile[(int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num9] != null)
                     {
                         _endpoints.Add(new Tuple<int, int>((int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num9));
                     }
                 }
             }
         }
         _targets.Clear();
         while (_points.Count > 0 && _endpoints.Count > 0)
         {
             Tuple<int, int> tuple = _points[0];
             Tuple<int, int> tuple2 = _endpoints[0];
             if (!Collision.TupleHitLine(tuple.Item1, tuple.Item2, tuple2.Item1, tuple2.Item2, num * (int)gravDir, -num2 * (int)gravDir, grappleTargets, out var col))
             {
                 _points.Remove(tuple);
                 _endpoints.Remove(tuple2);
                 continue;
             }
             if (col.Item1 != tuple2.Item1 || col.Item2 != tuple2.Item2)
             {
                 _targets.Add(col);
             }
             Tile tile = Main.tile[col.Item1, col.Item2];
             if (!tile.inActive() && tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type] && !grappleTargets.Contains(col))
             {
                 _targets.Add(col);
             }
             _points.Remove(tuple);
             _endpoints.Remove(tuple2);
         }
         _toRemove.Clear();
         for (int m = 0; m < _targets.Count; m++)
         {
             if (!WorldGen.CanKillTile(_targets[m].Item1, _targets[m].Item2))
             {
                 _toRemove.Add(_targets[m]);
             }
         }
         for (int n = 0; n < _toRemove.Count; n++)
         {
             _targets.Remove(_toRemove[n]);
         }
         _toRemove.Clear();
         if (_targets.Count > 0)
         {
             float num12 = -1f;
             Tuple<int, int> tuple3 = _targets[0];
             Vector2 value = center;
             if (Main.netMode == 1)
             {
                 int num13 = 0;
                 int num14 = 0;
                 int num15 = 0;
                 for (int num16 = 0; num16 < whoAmI; num16++)
                 {
                     Player player2 = Main.player[num16];
                     if (player2.active && !player2.dead && player2.HeldItem.pick > 0 && player2.itemAnimation > 0)
                     {
                         if (player.Distance(player2.Center) <= 8f)
{
                             num13++;
                         }
                         if (player.Distance(player2.Center) <= 80f && Math.Abs(player2.Center.Y - center.Y) <= 12f)
{
                             num14++;
                         }
                     }
                 }
                 for (int num17 = whoAmI + 1; num17 < 255; num17++)
                 {
                     Player player3 = Main.player[num17];
                     if (player3.active && !player3.dead && player3.HeldItem.pick > 0 && player3.itemAnimation > 0 && player.Distance(player3.Center) <= 8f)
                     {
                         num15++;
                     }
                 }
                 if (num13 > 0)
                 {
                     if (num13 % 2 == 1)
                     {
                         value.X += 12f;
                     }
                     else
                     {
                         value.X -= 12f;
                     }
                     if (num14 % 2 == 1)
                     {
                         value.Y -= 12f;
                     }
                 }
                 if (num15 > 0 && num13 == 0)
                 {
                     if (num15 % 2 == 1)
                     {
                         value.X -= 12f;
                     }
                     else
                     {
                         value.X += 12f;
                     }
                 }
             }
             for (int num18 = 0; num18 < _targets.Count; num18++)
             {
                 float num19 = Vector2.Distance(new Vector2(_targets[num18].Item1, _targets[num18].Item2) * 16f + Vector2.One * 8f, value);
                 if (num12 == -1f || num19 < num12)
                 {
                     num12 = num19;
                     tuple3 = _targets[num18];
                 }
             }
             if (Collision.InTileBounds(tuple3.Item1, tuple3.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
             {
                 focusedX = tuple3.Item1;
                 focusedY = tuple3.Item2;
             }
         }
         _points.Clear();
         _endpoints.Clear();
         _targets.Clear();
     }
References _endpoints, _points, _targets, _toRemove, Entity.active, Tile.active(), WorldGen.CanKillTile(), Entity.Center, TriggersPack.Current, Player.dead, Entity.direction, Entity.Distance(), PlayerInput.GamepadThumbstickLeft, PlayerInput.GamepadThumbstickRight, TriggersSet.GetNavigatorDirections(), Player.gravDir, Entity.height, Player.HeldItem, Tile.inActive(), Collision.InTileBounds(), WorldGen.InWorld(), SmartCursorHelper.SmartCursorUsageInfo.item, Player.itemAnimation, Main.maxTilesY, SmartCursorHelper.SmartCursorUsageInfo.mouse, Main.netMode, Item.pick, Main.player, Entity.position, SmartCursorHelper.SmartCursorUsageInfo.reachableEndX, SmartCursorHelper.SmartCursorUsageInfo.reachableEndY, SmartCursorHelper.SmartCursorUsageInfo.reachableStartX, SmartCursorHelper.SmartCursorUsageInfo.reachableStartY, Main.tile, Main.tileSolid, Main.tileSolidTop, PlayerInput.Triggers, Collision.TupleHitLine(), Tile.type, PlayerInput.UsingGamepad, Entity.whoAmI, and Entity.width.
Referenced by SmartCursorLookup().