Terraria: System.Globalization.TimeSpanFormat.FormatCustomized
FormatCustomized()
static StringBuilder System.Globalization.TimeSpanFormat.FormatCustomized (TimeSpan value, ReadOnlySpan< char > format, DateTimeFormatInfo dtfi, StringBuilder result = null) inline static private
Definition at line 410 of file TimeSpanFormat.cs.
    {
        bool flag = false;
        if (result == null)
        {
            result = StringBuilderCache.Acquire();
            flag = true;
        }
        int num = (int)(value.Ticks / 864000000000L);
        long num2 = value.Ticks % 864000000000L;
        if (value.Ticks < 0)
        {
            num = -num;
            num2 = -num2;
        }
        int value2 = (int)(num2 / 36000000000L % 24);
        int value3 = (int)(num2 / 600000000 % 60);
        int value4 = (int)(num2 / 10000000 % 60);
        int num3 = (int)(num2 % 10000000);
        long num4 = 0L;
        int num6;
        for (int i = 0; i < format.Length; i += num6)
        {
            char c = format[i];
            switch (c)
            {
            case 'h':
                num6 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                if (num6 <= 2)
                {
                    DateTimeFormat.FormatDigits(result, value2, num6);
                    continue;
                }
                break;
            case 'm':
                num6 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                if (num6 <= 2)
                {
                    DateTimeFormat.FormatDigits(result, value3, num6);
                    continue;
                }
                break;
            case 's':
                num6 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                if (num6 <= 2)
                {
                    DateTimeFormat.FormatDigits(result, value4, num6);
                    continue;
                }
                break;
            case 'f':
                num6 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                if (num6 <= 7)
                {
                    num4 = num3;
                    num4 /= TimeSpanParse.Pow10(7 - num6);
                    result.AppendSpanFormattable(num4, DateTimeFormat.fixedNumberFormats[num6 - 1], CultureInfo.InvariantCulture);
                    continue;
                }
                break;
            case 'F':
                num6 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                if (num6 <= 7)
                {
                    num4 = num3;
                    num4 /= TimeSpanParse.Pow10(7 - num6);
                    int num7 = num6;
                    while (num7 > 0 && num4 % 10 == 0L)
                    {
                        num4 /= 10;
                        num7--;
                    }
                    if (num7 > 0)
                    {
                        result.AppendSpanFormattable(num4, DateTimeFormat.fixedNumberFormats[num7 - 1], CultureInfo.InvariantCulture);
                    }
                    continue;
                }
                break;
            case 'd':
                num6 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                if (num6 <= 8)
                {
                    DateTimeFormat.FormatDigits(result, num, num6, overrideLengthLimit: true);
                    continue;
                }
                break;
            case '"':
            case '\'':
                num6 = DateTimeFormat.ParseQuoteString(format, i, result);
                continue;
            case '%':
            {
                int num5 = DateTimeFormat.ParseNextChar(format, i);
                if (num5 >= 0 && num5 != 37)
                {
                    char reference = (char)num5;
                    StringBuilder stringBuilder = FormatCustomized(value, MemoryMarshal.CreateReadOnlySpan(ref reference, 1), dtfi, result);
                    num6 = 2;
                    continue;
                }
                break;
            }
            case '\\':
            {
                int num5 = DateTimeFormat.ParseNextChar(format, i);
                if (num5 >= 0)
                {
                    result.Append((char)num5);
                    num6 = 2;
                    continue;
                }
                break;
            }
            }
            if (flag)
            {
                StringBuilderCache.Release(result);
            }
            throw new FormatException(SR.Format_InvalidString);
        }
        return result;
    }
References System.Text.StringBuilderCache.Acquire(), System.DateTimeFormat.fixedNumberFormats, System.format, System.SR.Format_InvalidString, System.Globalization.TimeSpanFormat.FormatCustomized(), System.DateTimeFormat.FormatDigits(), System.Globalization.CultureInfo.InvariantCulture, System.L, System.DateTimeFormat.ParseNextChar(), System.DateTimeFormat.ParseQuoteString(), System.DateTimeFormat.ParseRepeatPattern(), System.Globalization.TimeSpanParse.Pow10(), System.Text.StringBuilderCache.Release(), and System.value.
Referenced by System.Globalization.TimeSpanFormat.Format(), System.Globalization.TimeSpanFormat.FormatCustomized(), and System.Globalization.TimeSpanFormat.TryFormat().