Terraria: System.Globalization.TimeSpanFormat.TryFormat
TryFormat()
static bool System.Globalization.TimeSpanFormat.TryFormat (TimeSpan value, Span< char > destination, out int charsWritten, ReadOnlySpan< char > format, IFormatProvider formatProvider) inline static package
Definition at line 206 of file TimeSpanFormat.cs.
    {
        if (format.Length == 0)
        {
            return TryFormatStandard(value, StandardFormat.C, null, destination, out charsWritten);
        }
        if (format.Length == 1)
        {
            char c = format[0];
            if (c == 'c' || (c | 0x20) == 116)
            {
                return TryFormatStandard(value, StandardFormat.C, null, destination, out charsWritten);
            }
            return TryFormatStandard(value, c switch
            {
                'G' => StandardFormat.G,
                'g' => StandardFormat.g,
                _ => throw new FormatException(SR.Format_InvalidString),
            }, DateTimeFormatInfo.GetInstance(formatProvider).DecimalSeparator, destination, out charsWritten);
        }
        StringBuilder stringBuilder = FormatCustomized(value, format, DateTimeFormatInfo.GetInstance(formatProvider));
        if (stringBuilder.Length <= destination.Length)
        {
            stringBuilder.CopyTo(0, destination, stringBuilder.Length);
            charsWritten = stringBuilder.Length;
            StringBuilderCache.Release(stringBuilder);
            return true;
        }
        charsWritten = 0;
        StringBuilderCache.Release(stringBuilder);
        return false;
    }
References System.Text.StringBuilder.CopyTo(), System.destination, System.format, System.SR.Format_InvalidString, System.Globalization.TimeSpanFormat.FormatCustomized(), System.Text.StringBuilder.Length, System.Text.StringBuilderCache.Release(), System.Globalization.TimeSpanFormat.TryFormatStandard(), and System.value.
Referenced by System.TimeSpan.TryFormat().