Terraria: MS.Internal.Xml.XPath.Query.Advance
Advance()
XPathNavigator MS.Internal.Xml.XPath.Query.Advance () abstract
Referenced by MS.Internal.Xml.XPath.AttributeQuery.Advance(), MS.Internal.Xml.XPath.ChildrenQuery.Advance(), MS.Internal.Xml.XPath.DescendantOverDescendantQuery.Advance(), MS.Internal.Xml.XPath.DescendantQuery.Advance(), MS.Internal.Xml.XPath.FilterQuery.Advance(), MS.Internal.Xml.XPath.FollowingQuery.Advance(), MS.Internal.Xml.XPath.FollSiblingQuery.Advance(), MS.Internal.Xml.XPath.GroupQuery.Advance(), MS.Internal.Xml.XPath.NamespaceQuery.Advance(), MS.Internal.Xml.XPath.PrecedingQuery.Advance(), MS.Internal.Xml.XPath.UnionExpr.Advance(), MS.Internal.Xml.XPath.XPathSelfQuery.Advance(), MS.Internal.Xml.XPath.SortQuery.BuildResultsList(), MS.Internal.Xml.XPath.DocumentOrderQuery.Evaluate(), MS.Internal.Xml.XPath.ForwardPositionQuery.Evaluate(), MS.Internal.Xml.XPath.IDQuery.Evaluate(), MS.Internal.Xml.XPath.NodeFunctions.Evaluate(), MS.Internal.Xml.XPath.ParentQuery.Evaluate(), MS.Internal.Xml.XPath.PreSiblingQuery.Evaluate(), MS.Internal.Xml.XPath.XPathAncestorQuery.Evaluate(), MS.Internal.Xml.XPath.MergeFilterQuery.Evaluate(), MS.Internal.Xml.XPath.NodeFunctions.EvaluateArg(), MS.Internal.Xml.XPath.FilterQuery.EvaluatePredicate(), MS.Internal.Xml.XPath.FollSiblingQuery.FetchInput(), MS.Internal.Xml.XPath.CacheChildrenQuery.GetNextInput(), MS.Internal.Xml.XPath.FilterQuery.MatchNode(), MS.Internal.Xml.XPath.LogicalExpr.NodeSet.MoveNext(), MS.Internal.Xml.XPath.Query.MoveNext(), MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext(), MS.Internal.Xml.XPath.NumberFunctions.Number(), MS.Internal.Xml.XPath.NumberFunctions.Sum(), and MS.Internal.Xml.XPath.BooleanFunctions.toBoolean().