Terraria: MS.Internal.Xml.XPath.Query.SetXsltContext
SetXsltContext()
virtual void MS.Internal.Xml.XPath.Query.SetXsltContext (XsltContext context) inline virtual inherited
Reimplemented in MS.Internal.Xml.XPath.BaseAxisQuery, MS.Internal.Xml.XPath.BooleanExpr, MS.Internal.Xml.XPath.BooleanFunctions, MS.Internal.Xml.XPath.CacheOutputQuery, MS.Internal.Xml.XPath.FunctionQuery, MS.Internal.Xml.XPath.LogicalExpr, MS.Internal.Xml.XPath.NodeFunctions, MS.Internal.Xml.XPath.NumberFunctions, MS.Internal.Xml.XPath.NumericExpr, MS.Internal.Xml.XPath.StringFunctions, MS.Internal.Xml.XPath.VariableQuery, MS.Internal.Xml.XPath.FilterQuery, MS.Internal.Xml.XPath.MergeFilterQuery, MS.Internal.Xml.XPath.SortQuery, and MS.Internal.Xml.XPath.UnionExpr.
Definition at line 52 of file Query.cs.
    {
    }
Referenced by MS.Internal.Xml.XPath.CompiledXpathExpr.SetContext(), MS.Internal.Xml.XPath.BaseAxisQuery.SetXsltContext(), MS.Internal.Xml.XPath.BooleanExpr.SetXsltContext(), MS.Internal.Xml.XPath.BooleanFunctions.SetXsltContext(), MS.Internal.Xml.XPath.CacheOutputQuery.SetXsltContext(), MS.Internal.Xml.XPath.LogicalExpr.SetXsltContext(), MS.Internal.Xml.XPath.NodeFunctions.SetXsltContext(), MS.Internal.Xml.XPath.NumberFunctions.SetXsltContext(), MS.Internal.Xml.XPath.NumericExpr.SetXsltContext(), MS.Internal.Xml.XPath.FilterQuery.SetXsltContext(), MS.Internal.Xml.XPath.MergeFilterQuery.SetXsltContext(), MS.Internal.Xml.XPath.SortQuery.SetXsltContext(), and MS.Internal.Xml.XPath.UnionExpr.SetXsltContext().