Terraria: MS.Internal.Xml.XPath.Query.MatchNode
MatchNode()
virtual XPathNavigator MS.Internal.Xml.XPath.Query.MatchNode (XPathNavigator current) inline virtual inherited
Reimplemented in MS.Internal.Xml.XPath.AbsoluteQuery, MS.Internal.Xml.XPath.AttributeQuery, MS.Internal.Xml.XPath.ChildrenQuery, MS.Internal.Xml.XPath.DescendantBaseQuery, MS.Internal.Xml.XPath.DocumentOrderQuery, MS.Internal.Xml.XPath.ForwardPositionQuery, MS.Internal.Xml.XPath.IDQuery, MS.Internal.Xml.XPath.ContextQuery, MS.Internal.Xml.XPath.FilterQuery, MS.Internal.Xml.XPath.MergeFilterQuery, MS.Internal.Xml.XPath.FunctionQuery, and MS.Internal.Xml.XPath.UnionExpr.
Definition at line 60 of file Query.cs.
    {
        throw XPathException.Create(System.SR.Xp_InvalidPattern);
    }
References System.Xml.XPath.XPathException.Create(), and System.SR.Xp_InvalidPattern.
Referenced by MS.Internal.Xml.XPath.AttributeQuery.MatchNode(), MS.Internal.Xml.XPath.ChildrenQuery.MatchNode(), MS.Internal.Xml.XPath.DescendantBaseQuery.MatchNode(), MS.Internal.Xml.XPath.DocumentOrderQuery.MatchNode(), MS.Internal.Xml.XPath.ForwardPositionQuery.MatchNode(), MS.Internal.Xml.XPath.FilterQuery.MatchNode(), MS.Internal.Xml.XPath.MergeFilterQuery.MatchNode(), and MS.Internal.Xml.XPath.UnionExpr.MatchNode().