Terraria: System.Globalization.TimeSpanFormat.TryFormatStandard
TryFormatStandard()
static bool System.Globalization.TimeSpanFormat.TryFormatStandard (TimeSpan value, StandardFormat format, string decimalSeparator, Span< char > destination, out int charsWritten) inline static private
Definition at line 256 of file TimeSpanFormat.cs.
    {
        int num = 8;
        long num2 = value.Ticks;
        uint valueWithoutTrailingZeros;
        ulong num3;
        if (num2 < 0)
        {
            num = 9;
            num2 = -num2;
            if (num2 < 0)
            {
                valueWithoutTrailingZeros = 4775808u;
                num3 = 922337203685uL;
                goto IL_0050;
            }
        }
        (ulong Quotient, ulong Remainder) tuple = Math.DivRem((ulong)num2, 10000000uL);
        num3 = tuple.Quotient;
        ulong item = tuple.Remainder;
        valueWithoutTrailingZeros = (uint)item;
        goto IL_0050;
        IL_0050:
        int num4 = 0;
        switch (format)
        {
        case StandardFormat.C:
            if (valueWithoutTrailingZeros != 0)
            {
                num4 = 7;
                num += num4 + 1;
            }
            break;
        case StandardFormat.G:
            num4 = 7;
            num += num4 + 1;
            break;
        default:
            if (valueWithoutTrailingZeros != 0)
            {
                num4 = 7 - FormattingHelpers.CountDecimalTrailingZeros(valueWithoutTrailingZeros, out valueWithoutTrailingZeros);
                num += num4 + 1;
            }
            break;
        }
        ulong num5 = 0uL;
        ulong num6 = 0uL;
        if (num3 != 0)
        {
            (num5, num6) = Math.DivRem(num3, 60uL);
        }
        ulong num7 = 0uL;
        ulong num8 = 0uL;
        if (num5 != 0)
        {
            (num7, num8) = Math.DivRem(num5, 60uL);
        }
        uint num9 = 0u;
        uint num10 = 0u;
        if (num7 != 0)
        {
            (num9, num10) = Math.DivRem((uint)num7, 24u);
        }
        int num11 = 2;
        if (format == StandardFormat.g && num10 < 10)
        {
            num11 = 1;
            num--;
        }
        int num12 = 0;
        if (num9 != 0)
        {
            num12 = FormattingHelpers.CountDigits(num9);
            num += num12 + 1;
        }
        else if (format == StandardFormat.G)
        {
            num += 2;
            num12 = 1;
        }
        if (destination.Length < num)
        {
            charsWritten = 0;
            return false;
        }
        int num13 = 0;
        if (value.Ticks < 0)
        {
            destination[num13++] = '-';
        }
        if (num12 != 0)
        {
            WriteDigits(num9, destination.Slice(num13, num12));
            num13 += num12;
            destination[num13++] = ((format == StandardFormat.C) ? '.' : ':');
        }
        if (num11 == 2)
        {
            WriteTwoDigits(num10, destination.Slice(num13));
            num13 += 2;
        }
        else
        {
            destination[num13++] = (char)(48 + num10);
        }
        destination[num13++] = ':';
        WriteTwoDigits((uint)num8, destination.Slice(num13));
        num13 += 2;
        destination[num13++] = ':';
        WriteTwoDigits((uint)num6, destination.Slice(num13));
        num13 += 2;
        if (num4 != 0)
        {
            if (format == StandardFormat.C)
            {
                destination[num13++] = '.';
            }
            else if (decimalSeparator.Length == 1)
            {
                destination[num13++] = decimalSeparator[0];
            }
            else
            {
                decimalSeparator.CopyTo(destination);
                num13 += decimalSeparator.Length;
            }
            WriteDigits(valueWithoutTrailingZeros, destination.Slice(num13, num4));
            num13 += num4;
        }
        charsWritten = num;
        return true;
    }
References System.Buffers.Text.FormattingHelpers.CountDecimalTrailingZeros(), System.Buffers.Text.FormattingHelpers.CountDigits(), System.destination, System.Math.DivRem(), System.format, System.item, System.value, System.Globalization.TimeSpanFormat.WriteDigits(), and System.Globalization.TimeSpanFormat.WriteTwoDigits().
Referenced by System.Globalization.TimeSpanFormat.FormatC(), System.Globalization.TimeSpanFormat.FormatG(), and System.Globalization.TimeSpanFormat.TryFormat().