Terraria: MS.Internal.Xml.XPath.Query.Insert
Insert()
static bool MS.Internal.Xml.XPath.Query.Insert (List< XPathNavigator > buffer, XPathNavigator nav) inline static inherited
Definition at line 87 of file Query.cs.
    {
        int num = 0;
        int num2 = buffer.Count;
        if (num2 != 0)
        {
            switch (CompareNodes(buffer[num2 - 1], nav))
            {
            case XmlNodeOrder.Same:
                return false;
            case XmlNodeOrder.Before:
                buffer.Add(nav.Clone());
                return true;
            }
            num2--;
        }
        while (num < num2)
        {
            int median = GetMedian(num, num2);
            switch (CompareNodes(buffer[median], nav))
            {
            case XmlNodeOrder.Same:
                return false;
            case XmlNodeOrder.Before:
                num = median + 1;
                break;
            default:
                num2 = median;
                break;
            }
        }
        buffer.Insert(num, nav.Clone());
        return true;
    }
References System.buffer, System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.Query.CompareNodes(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, and MS.Internal.Xml.XPath.Query.GetMedian().
Referenced by MS.Internal.Xml.XPath.DocumentOrderQuery.Evaluate(), MS.Internal.Xml.XPath.ParentQuery.Evaluate(), MS.Internal.Xml.XPath.PreSiblingQuery.Evaluate(), MS.Internal.Xml.XPath.XPathAncestorQuery.Evaluate(), MS.Internal.Xml.XPath.MergeFilterQuery.Evaluate(), and MS.Internal.Xml.XPath.IDQuery.ProcessIds().