Terraria: MS.Internal.Xml.XPath.Query.GetXPathType
GetXPathType()
XPathResultType MS.Internal.Xml.XPath.Query.GetXPathType (object value) inline protected inherited
Definition at line 147 of file Query.cs.
    {
        if (value is XPathNodeIterator)
        {
            return XPathResultType.NodeSet;
        }
        if (value is string)
        {
            return XPathResultType.String;
        }
        if (value is double)
        {
            return XPathResultType.Number;
        }
        if (value is bool)
        {
            return XPathResultType.Boolean;
        }
        return (XPathResultType)4;
    }
References System.value.
Referenced by MS.Internal.Xml.XPath.IDQuery.Evaluate(), MS.Internal.Xml.XPath.LogicalExpr.Evaluate(), MS.Internal.Xml.XPath.NumberFunctions.Number(), and MS.Internal.Xml.XPath.StringFunctions.toString().