Terraria: System.Globalization.TimeSpanFormat.Format
Format()
static string System.Globalization.TimeSpanFormat.Format (TimeSpan value, string format, IFormatProvider formatProvider) inline static package
Definition at line 184 of file TimeSpanFormat.cs.
    {
        if (string.IsNullOrEmpty(format))
        {
            return FormatC(value);
        }
        if (format.Length == 1)
        {
            char c = format[0];
            if (c == 'c' || (c | 0x20) == 116)
            {
                return FormatC(value);
            }
            if ((c | 0x20) == 103)
            {
                return FormatG(value, DateTimeFormatInfo.GetInstance(formatProvider), (c == 'G') ? StandardFormat.G : StandardFormat.g);
            }
            throw new FormatException(SR.Format_InvalidString);
        }
        return StringBuilderCache.GetStringAndRelease(FormatCustomized(value, format, DateTimeFormatInfo.GetInstance(formatProvider)));
    }
References System.format, System.SR.Format_InvalidString, System.Globalization.TimeSpanFormat.FormatC(), System.Globalization.TimeSpanFormat.FormatCustomized(), System.Globalization.TimeSpanFormat.FormatG(), System.Text.StringBuilderCache.GetStringAndRelease(), and System.value.
Referenced by System.TimeSpan.ToString(), and System.TimeSpan.ToString().