Terraria: System.Globalization.TimeSpanFormat.NegativeInvariantFormatLiterals
NegativeInvariantFormatLiterals
readonly FormatLiterals System.Globalization.TimeSpanFormat.NegativeInvariantFormatLiterals = FormatLiterals.InitInvariant(isNegative: true) static package
Definition at line 182 of file TimeSpanFormat.cs.
Referenced by System.Globalization.TimeSpanParse.ProcessTerminal_D(), System.Globalization.TimeSpanParse.ProcessTerminal_DHMSF(), System.Globalization.TimeSpanParse.ProcessTerminal_HM(), System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(), and System.Globalization.TimeSpanParse.ProcessTerminal_HMS_F_D().