Terraria: MS.Internal.Xml.XPath.Query.Clone
Clone() [2/4]
static Query MS.Internal.Xml.XPath.Query.Clone (Query input) inline static inherited
Definition at line 66 of file Query.cs.
    {
        if (input != null)
        {
            return (Query)input.Clone();
        }
        return null;
    }
References System.input.
Referenced by MS.Internal.Xml.XPath.BaseAxisQuery.BaseAxisQuery(), MS.Internal.Xml.XPath.BooleanExpr.BooleanExpr(), MS.Internal.Xml.XPath.BooleanFunctions.BooleanFunctions(), MS.Internal.Xml.XPath.CacheChildrenQuery.CacheChildrenQuery(), MS.Internal.Xml.XPath.CacheOutputQuery.CacheOutputQuery(), MS.Internal.Xml.XPath.ChildrenQuery.ChildrenQuery(), MS.Internal.Xml.XPath.DescendantQuery.DescendantQuery(), MS.Internal.Xml.XPath.ExtensionQuery.ExtensionQuery(), MS.Internal.Xml.XPath.FilterQuery.FilterQuery(), MS.Internal.Xml.XPath.FollowingQuery.FollowingQuery(), MS.Internal.Xml.XPath.FollSiblingQuery.FollSiblingQuery(), MS.Internal.Xml.XPath.FunctionQuery.FunctionQuery(), MS.Internal.Xml.XPath.LogicalExpr.LogicalExpr(), MS.Internal.Xml.XPath.MergeFilterQuery.MergeFilterQuery(), MS.Internal.Xml.XPath.NumberFunctions.NumberFunctions(), MS.Internal.Xml.XPath.NumericExpr.NumericExpr(), MS.Internal.Xml.XPath.PrecedingQuery.PrecedingQuery(), System.Xml.Xsl.XsltOld.Processor.Processor(), MS.Internal.Xml.XPath.SortQuery.SortQuery(), MS.Internal.Xml.XPath.StringFunctions.StringFunctions(), MS.Internal.Xml.XPath.UnionExpr.UnionExpr(), MS.Internal.Xml.XPath.XPathSelectionIterator.XPathSelectionIterator(), MS.Internal.Xml.XPath.CompiledXpathExpr.Clone(), MS.Internal.Xml.XPath.NodeFunctions.Clone(), System.Xml.XPath.XPathNavigator.Evaluate(), System.Xml.Xsl.XsltOld.Processor.GetCompiledQuery(), and System.Xml.XPath.XPathNavigator.Matches().