Terraria: MS.Internal.Xml.XPath.Query.Evaluate
Evaluate()
object MS.Internal.Xml.XPath.Query.Evaluate (XPathNodeIterator nodeIterator) abstract inherited
Referenced by MS.Internal.Xml.XPath.SortQuery.BuildResultsList(), MS.Internal.Xml.XPath.NumberFunctions.Ceiling(), System.Xml.Xsl.XsltOld.Processor.Evaluate(), MS.Internal.Xml.XPath.CacheOutputQuery.Evaluate(), MS.Internal.Xml.XPath.NodeFunctions.Evaluate(), MS.Internal.Xml.XPath.SortQuery.Evaluate(), MS.Internal.Xml.XPath.UnionExpr.Evaluate(), MS.Internal.Xml.XPath.BaseAxisQuery.Evaluate(), MS.Internal.Xml.XPath.BooleanExpr.Evaluate(), MS.Internal.Xml.XPath.GroupQuery.Evaluate(), MS.Internal.Xml.XPath.LogicalExpr.Evaluate(), MS.Internal.Xml.XPath.MergeFilterQuery.Evaluate(), MS.Internal.Xml.XPath.NumericExpr.Evaluate(), MS.Internal.Xml.XPath.NodeFunctions.EvaluateArg(), MS.Internal.Xml.XPath.FilterQuery.EvaluatePredicate(), System.Xml.Xsl.XsltOld.CopyOfAction.Execute(), MS.Internal.Xml.XPath.NumberFunctions.Floor(), MS.Internal.Xml.XPath.BooleanFunctions.Lang(), MS.Internal.Xml.XPath.FilterQuery.MatchNode(), MS.Internal.Xml.XPath.BooleanFunctions.Not(), MS.Internal.Xml.XPath.NumberFunctions.Number(), MS.Internal.Xml.XPath.NumberFunctions.Round(), MS.Internal.Xml.XPath.NumberFunctions.Sum(), and MS.Internal.Xml.XPath.BooleanFunctions.toBoolean().