Terraria: Terraria.GameContent.UI.States.UIWorldSelect.OnActivate
OnActivate()
override void Terraria.GameContent.UI.States.UIWorldSelect.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 136 of file UIWorldSelect.cs.
    {
        Main.LoadWorlds();
        UpdateWorldsList();
        if (PlayerInput.UsingGamepadUI)
        {
            UILinkPointNavigator.ChangePoint(3000 + ((_worldList.Count == 0) ? 1 : 2));
        }
    }
References Terraria.GameContent.UI.States.UIWorldSelect._worldList, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.GameContent.UI.Elements.UIList.Count, Terraria.Main.LoadWorlds(), Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList(), and Terraria.GameInput.PlayerInput.UsingGamepadUI.