Terraria: Terraria.GameContent.UI.States.UIWorldSelect.NewWorldClick
NewWorldClick()
void Terraria.GameContent.UI.States.UIWorldSelect.NewWorldClick (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        SoundEngine.PlaySound(10);
        Main.newWorldName = Lang.gen[57].Value + " " + (Main.WorldList.Count + 1);
        Main.menuMode = 888;
        Main.MenuUI.SetState(new UIWorldCreation());
    }
References Terraria.Lang.gen, Terraria.Main.MenuUI, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.UserInterface.SetState(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize().