Terraria: System.Buffers.Text.FormattingHelpers.WriteFourDecimalDigits
WriteFourDecimalDigits()
static void System.Buffers.Text.FormattingHelpers.WriteFourDecimalDigits (uint value, Span< byte > buffer, int startingIndex = 0) inline static
Definition at line 147 of file FormattingHelpers.cs.
    {
        uint num = 48 + value;
        value /= 10;
        buffer[startingIndex + 3] = (byte)(num - value * 10);
        num = 48 + value;
        value /= 10;
        buffer[startingIndex + 2] = (byte)(num - value * 10);
        num = 48 + value;
        value /= 10;
        buffer[startingIndex + 1] = (byte)(num - value * 10);
        buffer[startingIndex] = (byte)(48 + value);
    }
References System.buffer, and System.value.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormatDateTimeG(), System.Buffers.Text.Utf8Formatter.TryFormatDateTimeL(), System.Buffers.Text.Utf8Formatter.TryFormatDateTimeO(), and System.Buffers.Text.Utf8Formatter.TryFormatDateTimeR().