Terraria: System.Buffers.Text.FormattingHelpers.WriteDigits
WriteDigits() [2/2]
static void System.Buffers.Text.FormattingHelpers.WriteDigits (ulong value, Span< byte > buffer) inline static
Definition at line 101 of file FormattingHelpers.cs.
    {
        for (int num = buffer.Length - 1; num >= 1; num--)
        {
            ulong num2 = 48 + value;
            value /= 10;
            buffer[num] = (byte)(num2 - value * 10);
        }
        buffer[0] = (byte)(48 + value);
    }
References System.buffer, and System.value.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormatDateTimeO(), System.Buffers.Text.Utf8Formatter.TryFormatInt64MultipleDigits(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64D(), and System.Buffers.Text.Utf8Formatter.TryFormatUInt64MultipleDigits().