Terraria: System.Buffers.Text.FormattingHelpers.CountDigits
CountDigits() [2/2]
static int System.Buffers.Text.FormattingHelpers.CountDigits (ulong value) inline static
Definition at line 9 of file FormattingHelpers.cs.
    {
        int num = 1;
        uint num2;
        if (value >= 10000000)
        {
            if (value >= 100000000000000L)
            {
                num2 = (uint)(value / 100000000000000L);
                num += 14;
            }
            else
            {
                num2 = (uint)(value / 10000000);
                num += 7;
            }
        }
        else
        {
            num2 = (uint)value;
        }
        if (num2 >= 10)
        {
            num = ((num2 < 100) ? (num + 1) : ((num2 < 1000) ? (num + 2) : ((num2 < 10000) ? (num + 3) : ((num2 < 100000) ? (num + 4) : ((num2 >= 1000000) ? (num + 6) : (num + 5))))));
        }
        return num;
    }
References System.L, and System.value.
Referenced by System.Number.NegativeInt32ToDecStr(), System.Number.NegativeInt64ToDecStr(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormatInt64MultipleDigits(), System.Globalization.TimeSpanFormat.TryFormatStandard(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64D(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64MultipleDigits(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64N(), System.Number.TryNegativeInt32ToDecStr(), System.Number.TryNegativeInt64ToDecStr(), System.Number.TryUInt32ToDecStr(), System.Number.TryUInt64ToDecStr(), System.Number.UInt32ToDecStr(), System.Number.UInt32ToDecStr(), and System.Number.UInt64ToDecStr().