Terraria: System.Buffers.Text.FormattingHelpers.TryFormatThrowFormatException
TryFormatThrowFormatException()
static bool System.Buffers.Text.FormattingHelpers.TryFormatThrowFormatException (out int bytesWritten) inline static
Definition at line 170 of file FormattingHelpers.cs.
    {
        bytesWritten = 0;
        ThrowHelper.ThrowFormatException_BadFormatSpecifier();
        return false;
    }
References System.ThrowHelper.ThrowFormatException_BadFormatSpecifier().
Referenced by System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.Buffers.Text.Utf8Formatter.TryFormatInt64(), and System.Buffers.Text.Utf8Formatter.TryFormatUInt64().