Terraria: System.Buffers.SequenceReader.TryReadTo
TryReadTo() [1/6]
bool System.Buffers.SequenceReader< T >.TryReadTo (out ReadOnlySequence< T > sequence, ReadOnlySpan< T > delimiter, bool advancePastDelimiter = true) inline
Definition at line 622 of file SequenceReader.cs.
    {
        if (delimiter.Length == 0)
        {
            sequence = default(ReadOnlySequence<T>);
            return true;
        }
        SequenceReader<T> sequenceReader = this;
        bool flag = false;
        while (!End)
        {
            if (!TryReadTo(out sequence, delimiter[0], advancePastDelimiter: false))
            {
                this = sequenceReader;
                return false;
            }
            if (delimiter.Length == 1)
            {
                if (advancePastDelimiter)
                {
                    Advance(1L);
                }
                return true;
            }
            if (IsNext(delimiter))
            {
                if (flag)
                {
                    sequence = sequenceReader.Sequence.Slice(sequenceReader.Consumed, Consumed - sequenceReader.Consumed);
                }
                if (advancePastDelimiter)
                {
                    Advance(delimiter.Length);
                }
                return true;
            }
            Advance(1L);
            flag = true;
        }
        this = sequenceReader;
        sequence = default(ReadOnlySequence<T>);
        return false;
    }
References System.Buffers.SequenceReader< T >.Advance(), System.Buffers.SequenceReader< T >.Consumed, System.Buffers.SequenceReader< T >.End, System.Buffers.SequenceReader< T >.IsNext(), System.L, System.ReadOnlySpan< T >.Length, System.Buffers.SequenceReader< T >.Sequence, and System.Buffers.SequenceReader< T >.TryReadTo().