Terraria: System.Buffers.SequenceReader.RetreatToPreviousSpan
RetreatToPreviousSpan()
void System.Buffers.SequenceReader< T >.RetreatToPreviousSpan (long consumed) inline private
Definition at line 155 of file SequenceReader.cs.
    {
        ResetReader();
        Advance(consumed);
    }
References System.Buffers.SequenceReader< T >.Advance(), and System.Buffers.SequenceReader< T >.ResetReader().
Referenced by System.Buffers.SequenceReader< T >.Rewind().