Terraria: System.Buffers.SequenceReader.TryReadToSlow
TryReadToSlow() [1/4]
bool System.Buffers.SequenceReader< T >.TryReadToSlow (out ReadOnlySequence< T > sequence, T delimiter, T delimiterEscape, int index, bool advancePastDelimiter) inline private
Definition at line 354 of file SequenceReader.cs.
    {
        SequenceReader<T> sequenceReader = this;
        ReadOnlySpan<T> span = UnreadSpan;
        bool flag = false;
        do
        {
            if (index >= 0)
            {
                if (!(index == 0 && flag))
                {
                    if (index > 0 && span[index - 1].Equals(delimiterEscape))
                    {
                        int num = 1;
                        int num2 = index - 2;
                        while (num2 >= 0 && span[num2].Equals(delimiterEscape))
{
                            num2--;
                        }
                        if (num2 < 0 && flag)
{
                            num++;
                        }
                        num += index - 2 - num2;
                        if (((uint)num & (true ? 1u : 0u)) != 0)
{
                            Advance(index + 1);
                            flag = false;
                            span = UnreadSpan;
                            goto IL_01bd;
                        }
                    }
                    AdvanceCurrentSpan(index);
                    sequence = Sequence.Slice(sequenceReader.Position, Position);
                    if (advancePastDelimiter)
                    {
                        Advance(1L);
                    }
                    return true;
                }
                flag = false;
                Advance(index + 1);
                span = UnreadSpan;
            }
            else
            {
                if (span.Length > 0 && span[span.Length - 1].Equals(delimiterEscape))
                {
                    int num3 = 1;
                    int num4 = span.Length - 2;
                    while (num4 >= 0 && span[num4].Equals(delimiterEscape))
                    {
                        num4--;
                    }
                    num3 += span.Length - 2 - num4;
                    flag = ((!(num4 < 0 && flag)) ? ((num3 & 1) != 0) : ((num3 & 1) == 0));
                }
                else
                {
                    flag = false;
                }
                AdvanceCurrentSpan(span.Length);
                span = CurrentSpan;
            }
            goto IL_01bd;
            IL_01bd:
            index = span.IndexOf(delimiter);
        }
        while (!End);
        this = sequenceReader;
        sequence = default(ReadOnlySequence<T>);
        return false;
    }
References System.Buffers.SequenceReader< T >.Advance(), System.Buffers.SequenceReader< T >.AdvanceCurrentSpan(), System.Buffers.SequenceReader< T >.CurrentSpan, System.Buffers.SequenceReader< T >.End, System.ReadOnlySpan< T >.Equals(), System.index, System.L, System.ReadOnlySpan< T >.Length, System.Buffers.SequenceReader< T >.Position, System.Buffers.SequenceReader< T >.Sequence, and System.Buffers.SequenceReader< T >.UnreadSpan.