Terraria: System.Buffers.SequenceReader.Advance
Advance()
void System.Buffers.SequenceReader< T >.Advance (long count) inline
Definition at line 211 of file SequenceReader.cs.
    {
        if ((count & int.MinValue) == 0L && CurrentSpan.Length - CurrentSpanIndex > (int)count)
        {
            CurrentSpanIndex += (int)count;
            Consumed += count;
        }
        else
        {
            AdvanceToNextSpan(count);
        }
    }
References System.Buffers.SequenceReader< T >.AdvanceToNextSpan(), System.Buffers.SequenceReader< T >.Consumed, System.count, System.Buffers.SequenceReader< T >.CurrentSpan, System.Buffers.SequenceReader< T >.CurrentSpanIndex, and System.L.
Referenced by System.Buffers.SequenceReader< T >.IsNextSlow(), System.Buffers.SequenceReader< T >.RetreatToPreviousSpan(), System.Buffers.SequenceReader< T >.TryAdvanceTo(), System.Buffers.SequenceReader< T >.TryReadTo(), System.Buffers.SequenceReader< T >.TryReadTo(), System.Buffers.SequenceReader< T >.TryReadToAny(), System.Buffers.SequenceReader< T >.TryReadToAnyInternal(), System.Buffers.SequenceReader< T >.TryReadToInternal(), and System.Buffers.SequenceReader< T >.TryReadToSlow().