Terraria: System.Buffers.SequenceReader.AdvanceToNextSpan
AdvanceToNextSpan()
void System.Buffers.SequenceReader< T >.AdvanceToNextSpan (long count) inline private
Definition at line 235 of file SequenceReader.cs.
    {
        if (count < 0)
        {
            System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument.count);
        }
        Consumed += count;
        while (_moreData)
        {
            int num = CurrentSpan.Length - CurrentSpanIndex;
            if (num > count)
            {
                CurrentSpanIndex += (int)count;
                count = 0L;
                break;
            }
            CurrentSpanIndex += num;
            count -= num;
            GetNextSpan();
            if (count == 0L)
            {
                break;
            }
        }
        if (count != 0L)
        {
            Consumed -= count;
            System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument.count);
        }
    }
References System.Buffers.SequenceReader< T >._moreData, System.Buffers.SequenceReader< T >.Consumed, System.count, System.Buffers.SequenceReader< T >.CurrentSpanIndex, System.Buffers.SequenceReader< T >.GetNextSpan(), System.L, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Buffers.SequenceReader< T >.Advance().