Terraria: System.Reflection.AssemblyNameFormatter.ComputeDisplayName
ComputeDisplayName()
static string System.Reflection.AssemblyNameFormatter.ComputeDisplayName (string name, Version version, string cultureName, byte[] pkt, AssemblyNameFlags flags = AssemblyNameFlags::None, AssemblyContentType contentType = AssemblyContentType::Default) inline static
Definition at line 7 of file AssemblyNameFormatter.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.AppendQuoted(name);
        if (version != null)
        {
            Version version2 = version.CanonicalizeVersion();
            if (version2.Major != 65535)
            {
                stringBuilder.Append(", Version=");
                stringBuilder.Append(version2.Major);
                if (version2.Minor != 65535)
                {
                    stringBuilder.Append('.');
                    stringBuilder.Append(version2.Minor);
                    if (version2.Build != 65535)
                    {
                        stringBuilder.Append('.');
                        stringBuilder.Append(version2.Build);
                        if (version2.Revision != 65535)
{
                            stringBuilder.Append('.');
                            stringBuilder.Append(version2.Revision);
                        }
                    }
                }
            }
        }
        if (cultureName != null)
        {
            if (cultureName.Length == 0)
            {
                cultureName = "neutral";
            }
            stringBuilder.Append(", Culture=");
            stringBuilder.AppendQuoted(cultureName);
        }
        if (pkt != null)
        {
            if (pkt.Length > 8)
            {
                throw new ArgumentException();
            }
            stringBuilder.Append(", PublicKeyToken=");
            if (pkt.Length == 0)
            {
                stringBuilder.Append("null");
            }
            else
            {
                stringBuilder.Append(HexConverter.ToString(pkt, HexConverter.Casing.Lower));
            }
        }
        if ((flags & AssemblyNameFlags.Retargetable) != 0)
        {
            stringBuilder.Append(", Retargetable=Yes");
        }
        if (contentType == AssemblyContentType.WindowsRuntime)
        {
            stringBuilder.Append(", ContentType=WindowsRuntime");
        }
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.Version.Build, System.Version.Major, System.Version.Minor, System.Version.Revision, System.Text.StringBuilder.ToString(), and System.HexConverter.ToString().
Referenced by System.Resources.ManifestBasedResourceGroveler.HandleSatelliteMissing().