Terraria: System.IO.Enumeration.FileSystemEnumerator.DirectoryFinished
DirectoryFinished()
unsafe void System.IO.Enumeration.FileSystemEnumerator< TResult >.DirectoryFinished () inline private inherited
Definition at line 77 of file FileSystemEnumerator.cs.
    {
        _entry = default(Interop.NtDll.FILE_FULL_DIR_INFORMATION*);
        CloseDirectoryHandle();
        OnDirectoryFinished(_currentPath.AsSpan());
        if (!DequeueNextDirectory())
        {
            _lastEntryFound = true;
        }
        else
        {
            FindNextEntry();
        }
    }
References System.IO.Enumeration.FileSystemEnumerator< TResult >._currentPath, System.IO.Enumeration.FileSystemEnumerator< TResult >._entry, System.IO.Enumeration.FileSystemEnumerator< TResult >._lastEntryFound, System.IO.Enumeration.FileSystemEnumerator< TResult >.CloseDirectoryHandle(), System.IO.Enumeration.FileSystemEnumerator< TResult >.DequeueNextDirectory(), System.IO.Enumeration.FileSystemEnumerator< TResult >.FindNextEntry(), and System.IO.Enumeration.FileSystemEnumerator< TResult >.OnDirectoryFinished().
Referenced by System.IO.Enumeration.FileSystemEnumerator< TResult >.GetData().