Terraria: System.IO.Enumeration.FileSystemEnumerator.FindNextEntry
FindNextEntry()
unsafe void System.IO.Enumeration.FileSystemEnumerator< TResult >.FindNextEntry () inline private inherited
Definition at line 282 of file FileSystemEnumerator.cs.
    {
        _entry = Interop.NtDll.FILE_FULL_DIR_INFORMATION.GetNextInfo(_entry);
        if (_entry == null && GetData())
        {
            _entry = (Interop.NtDll.FILE_FULL_DIR_INFORMATION*)(void*)_buffer;
        }
    }
References System.IO.Enumeration.FileSystemEnumerator< TResult >._buffer, System.IO.Enumeration.FileSystemEnumerator< TResult >._entry, System.IO.Enumeration.FileSystemEnumerator< TResult >.GetData(), and Interop.NtDll.FILE_FULL_DIR_INFORMATION.GetNextInfo().
Referenced by System.IO.Enumeration.FileSystemEnumerator< TResult >.DirectoryFinished(), and System.IO.Enumeration.FileSystemEnumerator< TResult >.MoveNext().