Terraria: System.IO.Enumeration.FileSystemEnumerator.InternalDispose
InternalDispose()
void System.IO.Enumeration.FileSystemEnumerator< TResult >.InternalDispose (bool disposing) inline private inherited
Definition at line 301 of file FileSystemEnumerator.cs.
    {
        if (_lock != null)
        {
            lock (_lock)
            {
                _lastEntryFound = true;
                CloseDirectoryHandle();
                if (_pending != null)
                {
                    while (_pending.Count > 0)
                    {
                        Interop.Kernel32.CloseHandle(_pending.Dequeue().Handle);
                    }
                    _pending = null;
                }
                if (_buffer != (IntPtr)0)
                {
                    Marshal.FreeHGlobal(_buffer);
                }
                _buffer = default(IntPtr);
            }
        }
        Dispose(disposing);
    }
References System.IO.Enumeration.FileSystemEnumerator< TResult >._buffer, System.IO.Enumeration.FileSystemEnumerator< TResult >._lastEntryFound, System.IO.Enumeration.FileSystemEnumerator< TResult >._lock, System.IO.Enumeration.FileSystemEnumerator< TResult >._pending, System.IO.Enumeration.FileSystemEnumerator< TResult >.CloseDirectoryHandle(), Interop.Kernel32.CloseHandle(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.IO.Enumeration.FileSystemEnumerator< TResult >.Dispose(), and System.Runtime.InteropServices.Marshal.FreeHGlobal().
Referenced by System.IO.Enumeration.FileSystemEnumerator< TResult >.~FileSystemEnumerator(), and System.IO.Enumeration.FileSystemEnumerator< TResult >.Dispose().