Terraria: System.IO.Enumeration.FileSystemEnumerator.Init
Init()
void System.IO.Enumeration.FileSystemEnumerator< TResult >.Init () inline private inherited
Definition at line 112 of file FileSystemEnumerator.cs.
    {
        using (default(DisableMediaInsertionPrompt))
        {
            _directoryHandle = CreateDirectoryHandle(_rootDirectory);
            if (_directoryHandle == IntPtr.Zero)
            {
                _lastEntryFound = true;
            }
        }
        _currentPath = _rootDirectory;
        int bufferSize = _options.BufferSize;
        _bufferLength = ((bufferSize <= 0) ? 4096 : Math.Max(1024, bufferSize));
        try
        {
            _buffer = Marshal.AllocHGlobal(_bufferLength);
        }
        catch
        {
            CloseDirectoryHandle();
            throw;
        }
    }
References System.IO.Enumeration.FileSystemEnumerator< TResult >._buffer, System.IO.Enumeration.FileSystemEnumerator< TResult >._bufferLength, System.IO.Enumeration.FileSystemEnumerator< TResult >._currentPath, System.IO.Enumeration.FileSystemEnumerator< TResult >._directoryHandle, System.IO.Enumeration.FileSystemEnumerator< TResult >._lastEntryFound, System.IO.Enumeration.FileSystemEnumerator< TResult >._options, System.IO.Enumeration.FileSystemEnumerator< TResult >._rootDirectory, System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.IO.EnumerationOptions.BufferSize, System.IO.Enumeration.FileSystemEnumerator< TResult >.CloseDirectoryHandle(), System.IO.Enumeration.FileSystemEnumerator< TResult >.CreateDirectoryHandle(), System.Math.Max(), and System.IntPtr.Zero.
Referenced by System.IO.Enumeration.FileSystemEnumerator< TResult >.FileSystemEnumerator().