Terraria: System.IO.Enumeration.FileSystemEnumerator.GetData
GetData()
unsafe bool System.IO.Enumeration.FileSystemEnumerator< TResult >.GetData () inline private inherited
Definition at line 137 of file FileSystemEnumerator.cs.
    {
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Interop.NtDll.IO_STATUS_BLOCK iO_STATUS_BLOCK);
        int num = Interop.NtDll.NtQueryDirectoryFile(_directoryHandle, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero, &iO_STATUS_BLOCK, _buffer, (uint)_bufferLength, Interop.NtDll.FILE_INFORMATION_CLASS.FileFullDirectoryInformation, Interop.BOOLEAN.FALSE, null, Interop.BOOLEAN.FALSE);
        switch ((uint)num)
        {
        case 2147483654u:
            DirectoryFinished();
            return false;
        case 0u:
            return true;
        case 3221225487u:
            DirectoryFinished();
            return false;
        default:
        {
            int num2 = (int)Interop.NtDll.RtlNtStatusToDosError(num);
            if ((num2 == 5 && _options.IgnoreInaccessible) || ContinueOnError(num2))
            {
                DirectoryFinished();
                return false;
            }
            throw Win32Marshal.GetExceptionForWin32Error(num2, _currentPath);
        }
        }
    }
References System.IO.Enumeration.FileSystemEnumerator< TResult >._buffer, System.IO.Enumeration.FileSystemEnumerator< TResult >._bufferLength, System.IO.Enumeration.FileSystemEnumerator< TResult >._currentPath, System.IO.Enumeration.FileSystemEnumerator< TResult >._directoryHandle, System.IO.Enumeration.FileSystemEnumerator< TResult >._options, System.IO.Enumeration.FileSystemEnumerator< TResult >.ContinueOnError(), System.IO.Enumeration.FileSystemEnumerator< TResult >.DirectoryFinished(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.IO.EnumerationOptions.IgnoreInaccessible, Interop.NtDll.NtQueryDirectoryFile(), and System.IntPtr.Zero.
Referenced by System.IO.Enumeration.FileSystemEnumerator< TResult >.FindNextEntry().