Terraria: Terraria.GameContent.UI.Minimap.MinimapFrameTemplate.CreateInstance
CreateInstance()
MinimapFrame Terraria.GameContent.UI.Minimap.MinimapFrameTemplate.CreateInstance (AssetRequestMode mode) inline
Definition at line 28 of file MinimapFrameTemplate.cs.
    {
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        MinimapFrame minimapFrame = new MinimapFrame(LoadAsset<Texture2D>("Images\\UI\\Minimap\\" + name + "\\MinimapFrame", mode), frameOffset);
        minimapFrame.NameKey = name;
        minimapFrame.ConfigKey = name;
        minimapFrame.SetResetButton(LoadAsset<Texture2D>("Images\\UI\\Minimap\\" + name + "\\MinimapButton_Reset", mode), resetPosition);
        minimapFrame.SetZoomOutButton(LoadAsset<Texture2D>("Images\\UI\\Minimap\\" + name + "\\MinimapButton_ZoomOut", mode), zoomOutPosition);
        minimapFrame.SetZoomInButton(LoadAsset<Texture2D>("Images\\UI\\Minimap\\" + name + "\\MinimapButton_ZoomIn", mode), zoomInPosition);
        return minimapFrame;
    }
References Terraria.GameContent.UI.Minimap.MinimapFrameTemplate.frameOffset, Terraria.GameContent.UI.Minimap.MinimapFrameTemplate.name, Terraria.GameContent.UI.Minimap.MinimapFrameTemplate.resetPosition, Terraria.GameContent.UI.Minimap.MinimapFrame.SetResetButton(), Terraria.GameContent.UI.Minimap.MinimapFrame.SetZoomInButton(), Terraria.GameContent.UI.Minimap.MinimapFrame.SetZoomOutButton(), Terraria.GameContent.UI.Minimap.MinimapFrameTemplate.zoomInPosition, and Terraria.GameContent.UI.Minimap.MinimapFrameTemplate.zoomOutPosition.
Referenced by Terraria.GameContent.UI.Minimap.MinimapFrameManager.CreateAndAdd().