Terraria: Cloud.addCloud
addCloud()
static void Cloud.addCloud () inline static
     {
         if (Main.netMode == 2)
         {
             return;
         }
         int num = -1;
         for (int i = 0; i < 200; i++)
         {
             if (!Main.cloud[i].active)
             {
                 num = i;
                 break;
             }
         }
         if (num < 0)
         {
             return;
         }
         Main.cloud[num].kill = false;
         Main.cloud[num].rSpeed = 0f;
         Main.cloud[num].sSpeed = 0f;
         Main.cloud[num].scale = (float)rand.Next(70, 131) * 0.01f;
         Main.cloud[num].rotation = (float)rand.Next(-10, 11) * 0.01f;
         Main.cloud[num].width = (int)((float)TextureAssets.Cloud[Main.cloud[num].type].Width() * Main.cloud[num].scale);
         Main.cloud[num].height = (int)((float)TextureAssets.Cloud[Main.cloud[num].type].Height() * Main.cloud[num].scale);
         Main.cloud[num].Alpha = 0f;
         Main.cloud[num].spriteDir = SpriteEffects.None;
         if (rand.Next(2) == 0)
         {
             Main.cloud[num].spriteDir = SpriteEffects.FlipHorizontally;
         }
         float num2 = Main.windSpeedCurrent;
         if (!Main.gameMenu)
         {
             num2 = Main.windSpeedCurrent - Main.player[Main.myPlayer].velocity.X * 0.1f;
         }
         int num3 = 0;
         int num4 = 0;
         if (num2 > 0f)
         {
             num3 -= 200;
         }
         if (num2 < 0f)
         {
             num4 += 200;
         }
         int num5 = 300;
         float x = rand.Next(num3 - num5, Main.screenWidth + num4 + num5);
         Main.cloud[num].Alpha = 0f;
         Main.cloud[num].position.Y = rand.Next((int)((float)(-Main.screenHeight) * 0.25f), (int)((float)Main.screenHeight * 0.15f));
         if (rand.Next(3) == 0)
         {
             Main.cloud[num].position.Y -= rand.Next((int)((float)Main.screenHeight * 0.1f));
         }
         Main.cloud[num].type = rand.Next(4);
         if ((Main.cloudAlpha > 0f && rand.Next(4) != 0) || (Main.cloudBGActive >= 1f && rand.Next(2) == 0))
         {
             Main.cloud[num].type = rand.Next(18, 22);
             if ((double)Main.cloud[num].scale >= 1.15)
             {
                 Main.cloud[num].position.Y -= 150f;
             }
             if (Main.cloud[num].scale >= 1f)
             {
                 Main.cloud[num].position.Y -= 150f;
             }
         }
         else if (Main.cloudBGActive <= 0f && Main.cloudAlpha == 0f && Main.cloud[num].scale < 1f && Main.cloud[num].position.Y < (float)(-Main.screenHeight) * 0.15f && (double)Main.numClouds <= 80.0)
         {
             Main.cloud[num].type = rand.Next(9, 14);
         }
         else if ((((double)Main.cloud[num].scale < 1.15 && Main.cloud[num].position.Y < (float)(-Main.screenHeight) * 0.3f) || ((double)Main.cloud[num].scale < 0.85 && Main.cloud[num].position.Y < (float)Main.screenHeight * 0.15f)) && ((double)Main.numClouds > 70.0 || Main.cloudBGActive >= 1f))
         {
             Main.cloud[num].type = rand.Next(4, 9);
         }
         else if (Main.cloud[num].position.Y > (float)(-Main.screenHeight) * 0.15f && rand.Next(2) == 0 && (double)Main.numClouds > 20.0)
         {
             Main.cloud[num].type = rand.Next(14, 18);
         }
         if (rand.Next((Main.dontStarveWorld || Main.tenthAnniversaryWorld) ? 25 : 150) == 0)
         {
             Main.cloud[num].type = RollRareCloud();
         }
         else if (Main.tenthAnniversaryWorld && rand.Next(3) == 0)
         {
             Main.cloud[num].type = RollRareCloud();
         }
         if ((double)Main.cloud[num].scale > 1.2)
         {
             Main.cloud[num].position.Y += 100f;
         }
         if ((double)Main.cloud[num].scale > 1.3)
         {
             Main.cloud[num].scale = 1.3f;
         }
         if ((double)Main.cloud[num].scale < 0.7)
         {
             Main.cloud[num].scale = 0.7f;
         }
         Main.cloud[num].active = true;
         Main.cloud[num].position.X = x;
         if (Main.cloud[num].position.X > (float)(Main.screenWidth + 400))
         {
             Main.cloud[num].Alpha = 1f;
         }
         if (Main.cloud[num].position.X + (float)TextureAssets.Cloud[Main.cloud[num].type].Width() * Main.cloud[num].scale < -400f)
         {
             Main.cloud[num].Alpha = 1f;
         }
         Rectangle rectangle = new Rectangle((int)Main.cloud[num].position.X, (int)Main.cloud[num].position.Y, Main.cloud[num].width, Main.cloud[num].height);
         for (int j = 0; j < 200; j++)
         {
             if (num != j && Main.cloud[j].active)
             {
                 Rectangle value = new Rectangle((int)Main.cloud[j].position.X, (int)Main.cloud[j].position.Y, Main.cloud[j].width, Main.cloud[j].height);
                 if (rectangle.Intersects(value))
                 {
                     Main.cloud[num].active = false;
                 }
             }
         }
     }
References active, Alpha, TextureAssets.Cloud, Main.cloud, Main.cloudAlpha, Main.cloudBGActive, Main.dontStarveWorld, Main.gameMenu, height, kill, Main.myPlayer, Main.netMode, UnifiedRandom.Next(), Main.numClouds, Main.player, position, rand, RollRareCloud(), rotation, rSpeed, scale, Main.screenHeight, Main.screenWidth, spriteDir, sSpeed, Main.tenthAnniversaryWorld, type, Entity.velocity, width, and Main.windSpeedCurrent.
Referenced by resetClouds(), and UpdateClouds().