Terraria: Terraria.GameContent.UI.Elements.UIDynamicItemCollection.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIDynamicItemCollection.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 35 of file UIDynamicItemCollection.cs.
    {
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        Main.inventoryScale = 0.84615386f;
        GetGridParameters(out var startX, out var startY, out var startItemIndex, out var endItemIndex);
        int num = _itemsPerLine;
        for (int i = startItemIndex; i < endItemIndex; i++)
        {
            int num2 = _itemIdsAvailableToShow[i];
            Rectangle itemSlotHitbox = GetItemSlotHitbox(startX, startY, startItemIndex, i);
            Item inv = ContentSamples.ItemsByType[num2];
            int context = 29;
            if ((int)TextureAssets.Item[num2].State == 0)
            {
                num--;
            }
            bool cREATIVE_ItemSlotShouldHighlightAsSelected = false;
            if (base.IsMouseHovering && itemSlotHitbox.Contains(Main.MouseScreen.ToPoint()) && !PlayerInput.IgnoreMouseInterface)
            {
                _item.SetDefaults(inv.type);
                inv = _item;
                Main.LocalPlayer.mouseInterface = true;
                ItemSlot.OverrideHover(ref inv, context);
                ItemSlot.LeftClick(ref inv, context);
                ItemSlot.RightClick(ref inv, context);
                ItemSlot.MouseHover(ref inv, context);
                cREATIVE_ItemSlotShouldHighlightAsSelected = true;
            }
            UILinkPointNavigator.Shortcuts.CREATIVE_ItemSlotShouldHighlightAsSelected = cREATIVE_ItemSlotShouldHighlightAsSelected;
            ItemSlot.Draw(spriteBatch, ref inv, context, itemSlotHitbox.TopLeft());
            if (num <= 0)
            {
                break;
            }
        }
        while (_itemIdsToLoadTexturesFor.Count > 0 && num > 0)
        {
            int num3 = _itemIdsToLoadTexturesFor[0];
            _itemIdsToLoadTexturesFor.RemoveAt(0);
            if ((int)TextureAssets.Item[num3].State == 0)
            {
                Main.instance.LoadItem(num3);
                num -= 4;
            }
        }
    }
References Terraria.GameContent.UI.Elements.UIDynamicItemCollection._item, Terraria.GameContent.UI.Elements.UIDynamicItemCollection._itemIdsAvailableToShow, Terraria.GameContent.UI.Elements.UIDynamicItemCollection._itemIdsToLoadTexturesFor, Terraria.GameContent.UI.Elements.UIDynamicItemCollection._itemsPerLine, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.List< T >.Count, Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetGridParameters(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetItemSlotHitbox(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.ID.ContentSamples.ItemsByType, Terraria.UI.ItemSlot.LeftClick(), Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.MouseScreen, Terraria.UI.ItemSlot.OverrideHover(), System.Collections.Generic.List< T >.RemoveAt(), Terraria.UI.ItemSlot.RightClick(), and Terraria.Item.SetDefaults().