Terraria: Terraria.GameContent.UI.Elements.UIDynamicItemCollection.UpdateSize
UpdateSize()
void Terraria.GameContent.UI.Elements.UIDynamicItemCollection.UpdateSize () inline
Definition at line 171 of file UIDynamicItemCollection.cs.
    {
        int num = (_itemsPerLine = GetDimensions().ToRectangle().Width / 44);
        int num2 = (int)Math.Ceiling((float)_itemIdsAvailableToShow.Count / (float)num);
        MinHeight.Set(44 * num2, 0f);
    }
References Terraria.GameContent.UI.Elements.UIDynamicItemCollection._itemsPerLine, System.Math.Ceiling(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.MinHeight, Terraria.UI.StyleDimension.Set(), Terraria.UI.CalculatedStyle.ToRectangle(), and Microsoft.Xna.Framework.Rectangle.Width.
Referenced by Terraria.GameContent.UI.Elements.UIDynamicItemCollection.UIDynamicItemCollection(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.Recalculate(), and Terraria.GameContent.UI.Elements.UIDynamicItemCollection.SetContentsToShow().