Terraria: Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetGridParameters
GetGridParameters()
void Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetGridParameters (out int startX, out int startY, out int startItemIndex, out int endItemIndex) inline private
Definition at line 91 of file UIDynamicItemCollection.cs.
    {
        Rectangle rectangle = GetDimensions().ToRectangle();
        Rectangle viewCullingArea = base.Parent.GetViewCullingArea();
        int x = rectangle.Center.X;
        startX = x - (int)((float)(44 * _itemsPerLine) * 0.5f);
        startY = rectangle.Top;
        startItemIndex = 0;
        endItemIndex = _itemIdsAvailableToShow.Count;
        int num = (Math.Min(viewCullingArea.Top, rectangle.Top) - viewCullingArea.Top) / 44;
        startY += -num * 44;
        startItemIndex += -num * _itemsPerLine;
        int num2 = (int)Math.Ceiling((float)viewCullingArea.Height / 44f) * _itemsPerLine;
        if (endItemIndex > num2 + startItemIndex + _itemsPerLine)
        {
            endItemIndex = num2 + startItemIndex + _itemsPerLine;
        }
    }
References Terraria.GameContent.UI.Elements.UIDynamicItemCollection._itemIdsAvailableToShow, Terraria.GameContent.UI.Elements.UIDynamicItemCollection._itemsPerLine, System.Math.Ceiling(), System.Collections.Generic.List< T >.Count, Terraria.UI.UIElement.GetDimensions(), System.Math.Min(), and Terraria.UI.CalculatedStyle.ToRectangle().
Referenced by Terraria.GameContent.UI.Elements.UIDynamicItemCollection.DrawSelf(), and Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetSnapPoints().