Terraria: Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetSnapPoints
GetSnapPoints()
override List< SnapPoint > Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetSnapPoints () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 139 of file UIDynamicItemCollection.cs.
    {
        List<SnapPoint> list = new List<SnapPoint>();
        GetGridParameters(out var startX, out var startY, out var startItemIndex, out var endItemIndex);
        _ = _itemsPerLine;
        Rectangle viewCullingArea = base.Parent.GetViewCullingArea();
        int num = endItemIndex - startItemIndex;
        while (_dummySnapPoints.Count < num)
        {
            _dummySnapPoints.Add(new SnapPoint("CreativeInfinitesSlot", 0, Vector2.Zero, Vector2.Zero));
        }
        int num2 = 0;
        Vector2 vector = GetDimensions().Position();
        for (int i = startItemIndex; i < endItemIndex; i++)
        {
            Point center = GetItemSlotHitbox(startX, startY, startItemIndex, i).Center;
            if (viewCullingArea.Contains(center))
            {
                SnapPoint snapPoint = _dummySnapPoints[num2];
                snapPoint.ThisIsAHackThatChangesTheSnapPointsInfo(Vector2.Zero, center.ToVector2() - vector, num2);
                snapPoint.Calculate(this);
                num2++;
                list.Add(snapPoint);
            }
        }
        foreach (UIElement element in Elements)
        {
            list.AddRange(element.GetSnapPoints());
        }
        return list;
    }
References Terraria.GameContent.UI.Elements.UIDynamicItemCollection._dummySnapPoints, Terraria.GameContent.UI.Elements.UIDynamicItemCollection._itemsPerLine, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), Microsoft.Xna.Framework.Rectangle.Center, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.List< T >.Count, Terraria.UI.UIElement.GetDimensions(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetGridParameters(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetItemSlotHitbox(), Terraria.UI.UIElement.GetSnapPoints(), System.list, Terraria.UI.CalculatedStyle.Position(), and Microsoft.Xna.Framework.Vector2.Zero.