Terraria: System.ComponentModel.NullableConverter.ConvertTo
ConvertTo() [1/2]
override? object System.ComponentModel.NullableConverter.ConvertTo (ITypeDescriptorContext? context, CultureInfo? culture, object? value, Type destinationType) inline virtual
Reimplemented from System.ComponentModel.TypeConverter.
Definition at line 78 of file NullableConverter.cs.
    {
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        if (destinationType == UnderlyingType && value != null && NullableType.IsInstanceOfType(value))
        {
            return value;
        }
        if (destinationType == typeof(InstanceDescriptor))
        {
            ConstructorInfo member = (ConstructorInfo)NullableType.GetMemberWithSameMetadataDefinitionAs(s_nullableConstructor);
            return new InstanceDescriptor(member, new object[1] { value }, isComplete: true);
        }
        if (value == null)
        {
            if (destinationType == typeof(string))
            {
                return string.Empty;
            }
        }
        else if (UnderlyingTypeConverter != null)
        {
            return UnderlyingTypeConverter.ConvertTo(context, culture, value, destinationType);
        }
        return base.ConvertTo(context, culture, value, destinationType);
    }
References System.ComponentModel.TypeConverter.ConvertTo(), System.culture, System.Type.GetMemberWithSameMetadataDefinitionAs(), System.Type.IsInstanceOfType(), System.ComponentModel.NullableConverter.NullableType, System.ComponentModel.NullableConverter.s_nullableConstructor, System.ComponentModel.NullableConverter.UnderlyingType, System.ComponentModel.NullableConverter.UnderlyingTypeConverter, and System.value.