Terraria: System.Reflection.Emit.PropertyBuilder.SetCustomAttribute
SetCustomAttribute() [1/2]
void System.Reflection.Emit.PropertyBuilder.SetCustomAttribute (ConstructorInfo con, byte[] binaryAttribute) inline
Definition at line 116 of file PropertyBuilder.cs.
    {
        if (con == null)
        {
            throw new ArgumentNullException("con");
        }
        if (binaryAttribute == null)
        {
            throw new ArgumentNullException("binaryAttribute");
        }
        m_containingType.ThrowIfCreated();
        TypeBuilder.DefineCustomAttribute(m_moduleBuilder, m_tkProperty, m_moduleBuilder.GetConstructorToken(con), binaryAttribute);
    }
References System.Reflection.Emit.TypeBuilder.DefineCustomAttribute(), System.Reflection.Emit.ModuleBuilder.GetConstructorToken(), System.Reflection.Emit.PropertyBuilder.m_containingType, System.Reflection.Emit.PropertyBuilder.m_moduleBuilder, System.Reflection.Emit.PropertyBuilder.m_tkProperty, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().