Terraria: System.Threading.Channels.UnboundedChannel.UnboundedChannelWriter.WriteAsync
WriteAsync()
override ValueTask System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelWriter.WriteAsync (T item, CancellationToken cancellationToken) inline virtual
Reimplemented from System.Threading.Channels.ChannelWriter< T >.
Definition at line 238 of file UnboundedChannel.cs.
        {
            if (!cancellationToken.IsCancellationRequested)
            {
                if (!TryWrite(item))
                {
                    return new ValueTask(Task.FromException(ChannelUtilities.CreateInvalidCompletionException(_parent._doneWriting)));
                }
                return default(ValueTask);
            }
            return new ValueTask(Task.FromCanceled(cancellationToken));
        }
References System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelWriter._parent, System.cancellationToken, System.Threading.Channels.ChannelUtilities.CreateInvalidCompletionException(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.item, and System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelWriter.TryWrite().