Terraria: System.Reflection.Emit.PropertyBuilder.SetMethodSemantics
SetMethodSemantics()
void System.Reflection.Emit.PropertyBuilder.SetMethodSemantics (MethodBuilder mdBuilder, MethodSemanticsAttributes semantics) inline private
Definition at line 88 of file PropertyBuilder.cs.
    {
        if (mdBuilder == null)
        {
            throw new ArgumentNullException("mdBuilder");
        }
        m_containingType.ThrowIfCreated();
        ModuleBuilder module = m_moduleBuilder;
        TypeBuilder.DefineMethodSemantics(new QCallModule(ref module), m_tkProperty, semantics, mdBuilder.MetadataToken);
    }
References System.Reflection.Emit.TypeBuilder.DefineMethodSemantics(), System.Reflection.Emit.PropertyBuilder.m_containingType, System.Reflection.Emit.PropertyBuilder.m_moduleBuilder, System.Reflection.Emit.PropertyBuilder.m_tkProperty, System.Reflection.Emit.MethodBuilder.MetadataToken, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.PropertyBuilder.AddOtherMethod(), System.Reflection.Emit.PropertyBuilder.SetGetMethod(), and System.Reflection.Emit.PropertyBuilder.SetSetMethod().