Terraria: System.TimeSpan.FromTicks
FromTicks()
static TimeSpan System.TimeSpan.FromTicks (long value) inline static
Definition at line 277 of file TimeSpan.cs.
    {
        return new TimeSpan(value);
    }
References System.TimeSpan.TimeSpan(), and System.value.
Referenced by System.Net.Quic.QuicClientConnectionOptions.QuicClientConnectionOptions(), System.Net.Quic.QuicListenerOptions.QuicListenerOptions(), System.Data.Common.TimeSpanStorage.Aggregate(), Microsoft.Xna.Framework.GameClock.CounterToTimeSpan(), System.Runtime.JitInfo.GetCompilationTime(), System.Net.Http.Headers.AltSvcHeaderParser.GetParsedValueLength(), System.Net.Http.HttpConnectionPool.HandleAltSvc(), System.Xml.XmlBufferReader.ReadTimeSpan(), and System.Net.Http.Headers.AltSvcHeaderValue.ToString().