Terraria: System.TimeSpan.Zero
Zero
readonly TimeSpan System.TimeSpan.Zero = new TimeSpan(0L) static
Definition at line 21 of file TimeSpan.cs.
Referenced by System.DateTimeOffset.DateTimeOffset(), System.Net.Http.HttpConnectionPoolManager.HttpConnectionPoolManager(), System.Net.WebSockets.ManagedWebSocket.ManagedWebSocket(), System.Net.Mime.SmtpDateTime.SmtpDateTime(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindowDynamic(), System.TimeZone.CalculateUtcOffset(), System.Net.Http.HttpConnectionPool.CheckExpirationOnReturn(), System.Net.WebSockets.WebSocketHandle.ConnectAsync(), System.TimeZoneInfo.ConvertTime(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(), System.TimeZoneInfo.CreateAdjustmentRuleFromTimeZoneInformation(), System.Net.WebSockets.WebSocket.CreateClientWebSocket(), System.CurrentSystemTimeZone.CreateDaylightChanges(), System.Net.WebSockets.WebSocket.CreateFromStream(), System.TimeZoneInfo.CreateUtcTimeZone(), System.DateTimeParse.DateTimeOffsetTimeZonePostProcessing(), Terraria.Player.Deserialize(), System.DateTimeParse.DetermineTimeZoneAdjustments(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.DrainAsync(), System.Net.Http.HttpConnection.ContentLengthReadStream.DrainAsync(), System.Transactions.TransactionStatePromoted.EnterState(), System.DateTimeOffset.FromUnixTimeMilliseconds(), System.DateTimeOffset.FromUnixTimeSeconds(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.IO.IsolatedStorage.IsolatedStorageFile.GetCreationTime(), System.TimeZoneInfo.CachedData.GetCurrentOneYearLocal(), System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc(), System.TimeZoneInfo.GetIsAmbiguousTime(), System.TimeZoneInfo.GetIsDaylightSavings(), System.TimeZoneInfo.GetIsInvalidTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastAccessTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastWriteTime(), System.TimeZoneInfo.GetLocalTimeZone(), System.TimeZoneInfo.GetLocalTimeZoneFromWin32Data(), System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleValue(), System.TimeZoneInfo.StringSerializer.GetSerializedString(), System.CurrentSystemTimeZone.GetUtcOffset(), System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.GetUtcOffsetFromUtc(), System.Net.Http.HttpConnectionPool.HandleAltSvc(), System.Transactions.TransactionScope.Initialize(), System.Net.Mime.SmtpDateTime.InitializeShortHandLookups(), System.TimeZone.IsDaylightSavingTime(), System.DateTimeParse.ParseByFormat(), System.Formats.Asn1.AsnDecoder.ParseGeneralizedTime(), System.DateTimeParse.ParseISO8601(), Microsoft.Xna.Framework.GameClock.Reset(), System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset(), Terraria.Main.SaveSettings(), System.Diagnostics.Activity.Stop(), System.Diagnostics.DiagnosticSource.StopActivity(), System.Transactions.TransactionTable.TimeoutTicks(), System.DateTimeParse.TryParse(), System.DateTimeParse.TryParseExact(), System.DateTimeParse.TryParseExactMultiple(), System.Net.Mime.SmtpDateTime.TryParseTimeZoneString(), Microsoft.Xna.Framework.GameClock.UpdateElapsedTime(), System.TimeZoneInfo.AdjustmentRule.ValidateAdjustmentRule(), System.Transactions.TransactionScope.ValidateScopeTimeout(), System.Transactions.TransactionManager.ValidateTimeout(), System.Diagnostics.Tracing.IncrementingEventCounter.WritePayload(), System.Diagnostics.Tracing.IncrementingPollingCounter.WritePayload(), and System.Xml.XmlWriter.WriteValue().