Terraria: System.TimeSpan.CompareTo
CompareTo() [1/4]
int System.TimeSpan.CompareTo (object? value) inline
Implements System.IComparable< in T >.
Definition at line 126 of file TimeSpan.cs.
    {
        if (value == null)
        {
            return 1;
        }
        if (!(value is TimeSpan))
        {
            throw new ArgumentException(SR.Arg_MustBeTimeSpan);
        }
        long ticks = ((TimeSpan)value)._ticks;
        if (_ticks > ticks)
        {
            return 1;
        }
        if (_ticks < ticks)
        {
            return -1;
        }
        return 0;
    }
References System.TimeSpan.TimeSpan(), System.TimeSpan._ticks, System.SR.Arg_MustBeTimeSpan, and System.value.
Referenced by System.Data.Common.TimeSpanStorage.CompareValueTo(), and System.TimeZoneInfo.GetSystemTimeZones().