Terraria: System.TimeSpan.IntervalFromDoubleTicks
IntervalFromDoubleTicks()
static TimeSpan System.TimeSpan.IntervalFromDoubleTicks (double ticks) inline static private
Definition at line 215 of file TimeSpan.cs.
    {
        if (ticks > 9.223372036854776E+18 || ticks < -9.223372036854776E+18 || double.IsNaN(ticks))
        {
            throw new OverflowException(SR.Overflow_TimeSpanTooLong);
        }
        if (ticks == 9.223372036854776E+18)
        {
            return MaxValue;
        }
        return new TimeSpan((long)ticks);
    }
References System.TimeSpan.TimeSpan(), System.E, System.TimeSpan.MaxValue, and System.SR.Overflow_TimeSpanTooLong.
Referenced by System.TimeSpan.Interval(), System.TimeSpan.operator*(), and System.TimeSpan.operator/().