Terraria: System.TimeSpan.Parse
Parse() [4/5]
static TimeSpan System.TimeSpan.Parse (string s) inline static
Definition at line 301 of file TimeSpan.cs.
    {
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.input);
        }
        return TimeSpanParse.Parse(s, null);
    }
References System.Globalization.TimeSpanParse.Parse(), System.s, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.ComponentModel.DefaultValueAttribute.DefaultValueAttribute(), System.ComponentModel.TimeSpanConverter.ConvertFrom(), System.Data.Common.TimeSpanStorage.ConvertToTimeSpan(), System.TimeSpan.Parse(), and System.TimeSpan.Parse().