Terraria: System.TimeSpan.Compare
Compare()
static int System.TimeSpan.Compare (TimeSpan t1, TimeSpan t2) inline static
Definition at line 113 of file TimeSpan.cs.
    {
        if (t1._ticks > t2._ticks)
        {
            return 1;
        }
        if (t1._ticks < t2._ticks)
        {
            return -1;
        }
        return 0;
    }
References System.TimeSpan._ticks.
Referenced by System.Data.Common.TimeSpanStorage.Aggregate(), System.Xml.Schema.DurationFacetsChecker.CheckValueFacets(), System.Data.Common.TimeSpanStorage.Compare(), and System.Xml.Schema.DurationFacetsChecker.MatchEnumeration().