Terraria: System.TimeSpan.FromMilliseconds
FromMilliseconds()
static TimeSpan System.TimeSpan.FromMilliseconds (double value) inline static
Definition at line 228 of file TimeSpan.cs.
    {
        return Interval(value, 10000.0);
    }
References System.TimeSpan.Interval(), and System.value.
Referenced by System.Net.HttpWebRequest.HttpClientParameters.HttpClientParameters(), System.Text.RegularExpressions.RegexRunner.DoCheckTimeout(), Terraria.Main.LoadSettings(), System.Diagnostics.Tracing.CounterGroup.OnTimer(), System.Transactions.TransactionTable.RecalcTimeout(), System.ComponentModel.DataAnnotations.RegularExpressionAttribute.SetupRegex(), System.Net.WebSockets.ManagedWebSocket.WaitForServerToCloseConnectionAsync(), and System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync().