Terraria: System.Runtime.InteropServices.SafeHandle.DangerousRelease
DangerousRelease()
void System.Runtime.InteropServices.SafeHandle.DangerousRelease () inline inherited
Definition at line 93 of file SafeHandle.cs.
    {
        InternalRelease(disposeOrFinalizeOperation: false);
    }
References System.Runtime.InteropServices.SafeHandle.InternalRelease().
Referenced by Microsoft.Win32.SafeHandles.SafeNCryptHandle.SafeNCryptHandle(), System.Security.Principal.WindowsIdentity.WindowsIdentity(), System.Threading.RegisteredWaitHandle.~RegisteredWaitHandle(), System.Security.SecureString.AppendChar(), System.Security.SecureString.Clear(), System.Net.SSPIAuthType.DecryptMessage(), System.Net.SSPISecureChannelType.DecryptMessage(), System.Net.SSPIAuthType.EncryptMessage(), System.Net.SSPISecureChannelType.EncryptMessage(), System.Net.NegotiationInfoClass.GetAuthenticationPackageName(), System.Net.SSPIAuthType.GetSecurityContextToken(), System.Security.SecureString.Initialize(), System.Security.SecureString.InsertAt(), System.Net.SSPIAuthType.MakeSignature(), System.Security.SecureString.MarshalToBSTR(), System.Security.SecureString.MarshalToString(), System.Threading.WaitHandle.ObtainSafeWaitHandles(), System.Threading.PortableThreadPool.WaitThread.ProcessRemovals(), System.Net.Security.SafeFreeContextBuffer.QueryContextAttributes(), System.Net.Security.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding(), System.Runtime.InteropServices.SafeBuffer.Read< T >(), System.Runtime.InteropServices.SafeBuffer.ReadSpan< T >(), Interop.WinHttp.SafeWinHttpHandle.ReleaseHandle(), Internal.NativeCrypto.SafeKeyHandle.ReleaseHandle(), Microsoft.Win32.SafeHandles.DuplicateSafeNCryptKeyHandle.ReleaseHandle(), Microsoft.Win32.SafeHandles.SafeNCryptHandle.ReleaseHandle(), System.Security.Cryptography.SafeHashHandle.ReleaseHandle(), System.Security.Cryptography.SafeKeyHandle.ReleaseHandle(), System.Runtime.InteropServices.SafeBuffer.ReleasePointer(), System.Security.SecureString.RemoveAt(), System.Security.SecureString.SetAt(), System.Threading.WaitHandle.SignalAndWait(), System.Threading.RegisteredWaitHandle.SignalUserWaitHandle(), System.Net.Sockets.SocketPal.TransmitFileHelper(), System.Threading.RegisteredWaitHandle.Unregister(), System.Threading.RegisteredWaitHandle.UnregisterPortable(), System.Net.SSPIAuthType.VerifySignature(), System.Threading.WaitHandle.WaitMultiple(), System.Threading.WaitHandle.WaitOneNoCheck(), System.Runtime.InteropServices.SafeBuffer.Write< T >(), and System.Runtime.InteropServices.SafeBuffer.WriteSpan< T >().