Terraria: System.Runtime.InteropServices.SafeHandle.SetHandle
SetHandle()
void System.Runtime.InteropServices.SafeHandle.SetHandle (IntPtr handle) inline package inherited
Definition at line 42 of file SafeHandle.cs.
    {
        this.handle = handle;
    }
References System.Runtime.InteropServices.SafeHandle.handle.
Referenced by Microsoft.Win32.SafeHandles.DuplicateSafeNCryptKeyHandle.DuplicateSafeNCryptKeyHandle(), System.Net.HttpServerSessionHandle.HttpServerSessionHandle(), Microsoft.Win32.SafeHandles.SafeAllocHHandle.SafeAllocHHandle(), Internal.Cryptography.Pal.Native.SafeChainEngineHandle.SafeChainEngineHandle(), Microsoft.Win32.SafeHandles.SafeFileHandle.SafeFileHandle(), System.Security.Cryptography.SafeHashHandle.SafeHashHandle(), System.Security.Cryptography.SafeKeyHandle.SafeKeyHandle(), Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.SafeLocalAllocHandle(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConnectionHandle.SafeMsQuicConnectionHandle(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicStreamHandle.SafeMsQuicStreamHandle(), Microsoft.Win32.SafeHandles.SafeNCryptHandle.SafeNCryptHandle(), Microsoft.Win32.SafeHandles.SafeProcessHandle.SafeProcessHandle(), System.Security.Cryptography.SafeProvHandle.SafeProvHandle(), Internal.Win32.SafeHandles.SafeRegistryHandle.SafeRegistryHandle(), Microsoft.Win32.SafeHandles.SafeTokenHandle.SafeTokenHandle(), Microsoft.Win32.SafeHandles.SafeWaitHandle.SafeWaitHandle(), System.IO.Compression.ZLibNative.ZLibStreamHandle.ZLibStreamHandle(), System.Security.SecureString.UnmanagedBuffer.Allocate(), System.Runtime.InteropServices.Marshal.InitHandle(), Microsoft.Win32.SafeHandles.SafeLocalAllocHandle.LocalAlloc(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.ReleaseHandle(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConnectionHandle.ReleaseHandle(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicListenerHandle.ReleaseHandle(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicRegistrationHandle.ReleaseHandle(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicStreamHandle.ReleaseHandle(), Microsoft.Win32.SafeHandles.DuplicateSafeNCryptKeyHandle.ReleaseHandle(), System.Security.Cryptography.SafeProvHandle.ReleaseHandle(), Internal.Cryptography.Pal.Native.SafeChainEngineHandle.ReleaseHandle(), Microsoft.Win32.SafeHandles.SafePasswordHandle.ReleaseHandle(), System.Net.Sockets.SafeSocketHandle.SetHandleAndValid(), and Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle.SetHandleValue().