Terraria: System.Runtime.InteropServices.SafeHandle.SetHandleAsInvalid
SetHandleAsInvalid()
void System.Runtime.InteropServices.SafeHandle.SetHandleAsInvalid () inline inherited
Definition at line 68 of file SafeHandle.cs.
    {
        Interlocked.Or(ref _state, 1);
        GC.SuppressFinalize(this);
    }
References System.Runtime.InteropServices.SafeHandle._state, System.Threading.Interlocked.Or(), and System.GC.SuppressFinalize().
Referenced by System.Threading.EventWaitHandle.CreateEventCore(), System.Threading.Mutex.CreateMutexCore(), System.Security.Cryptography.CngKey.Delete(), System.Net.Security.SafeFreeContextBuffer.EnumeratePackages(), System.Net.Security.SafeFreeContextBuffer.EnumeratePackages(), System.Net.Security.SafeDeleteContext.MustRunAcceptSecurityContext_SECURITY(), System.Net.Security.SafeDeleteContext.MustRunInitializeSecurityContext(), System.Net.Security.SafeFreeContextBuffer.QueryContextAttributes(), System.Net.Security.SafeFreeContextBuffer.QueryContextAttributes(), System.Net.Security.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding(), System.Net.Sockets.SafeSocketHandle.SetHandleAndValid(), and System.IO.Pipes.PipeStream.WinIOError().