Terraria: System.Runtime.InteropServices.SafeHandle.Dispose
Dispose() [1/2]
void System.Runtime.InteropServices.SafeHandle.Dispose () inline inherited
Implements System.IDisposable.
Definition at line 57 of file SafeHandle.cs.
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
References System.Runtime.InteropServices.SafeHandle.Dispose(), and System.GC.SuppressFinalize().
Referenced by Internal.Cryptography.HashProviderCng.HashProviderCng(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream(), System.IO.Strategies.Net5CompatFileStreamStrategy.Net5CompatFileStreamStrategy(), System.IO.Strategies.OSFileStreamStrategy.OSFileStreamStrategy(), System.Diagnostics.ProcessManager.ProcessManager(), System.Net.Sockets.Socket.Socket(), System.Runtime.InteropServices.SafeHandle.~SafeHandle(), System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(), Interop.BCrypt.BCryptDuplicateHash(), System.Net.WebSockets.WebSocketBase.CleanUp(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Cleanup(), System.Net.HttpListener.CleanupV2Config(), System.Diagnostics.Process.Close(), System.Net.Security.SecureChannel.Close(), System.Runtime.InteropServices.SafeHandle.Close(), System.Net.Sockets.SafeSocketHandle.CloseAsIs(), System.Net.HttpListenerSession.CloseRequestQueueHandle(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ConnectAsync(), System.IO.Pipes.AnonymousPipeServerStream.Create(), System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(), System.IO.FileSystemAclExtensions.Create(), System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(), System.Net.WebSockets.Compression.WebSocketDeflater.CreateDeflater(), System.Net.WebSockets.Compression.WebSocketInflater.CreateInflater(), System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpenCore(), System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(), Internal.NativeCrypto.CapiHelper.DeriveKey(), Internal.Cryptography.HashProviderCng.DestroyHash(), System.IO.Compression.BrotliDecoder.Dispose(), System.IO.Compression.BrotliEncoder.Dispose(), System.Net.NetworkInformation.TeredoHelper.Dispose(), Internal.Win32.RegistryKey.Dispose(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.Security.SecureString.Dispose(), System.TypeNameParser.Dispose(), System.Security.Cryptography.CngKey.Dispose(), System.IO.MemoryMappedFiles.MemoryMappedFile.Dispose(), System.IO.MemoryMappedFiles.MemoryMappedView.Dispose(), System.IO.Pipes.AnonymousPipeServerStream.Dispose(), System.IO.Pipes.PipeStream.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.Dispose(), System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose(), System.IO.Strategies.OSFileStreamStrategy.Dispose(), System.Security.AccessControl.Privilege.TlsContents.Dispose(), Internal.Cryptography.BasicSymmetricCipherBCrypt.Dispose(), System.Security.Cryptography.DSAImplementation.DSACng.Dispose(), System.Security.Cryptography.RSAImplementation.RSACng.Dispose(), Internal.Cryptography.BasicSymmetricCipherCsp.Dispose(), System.Security.Principal.WindowsIdentity.Dispose(), System.IO.Strategies.Net5CompatFileStreamStrategy.DisposeAsync(), System.IO.Strategies.OSFileStreamStrategy.DisposeAsync(), System.Security.Cryptography.ECCngKey.DisposeKey(), System.IO.Pipes.AnonymousPipeServerStream.DisposeLocalCopyOfClientHandle(), System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendPackets(), System.Security.SecureString.EnsureCapacity(), System.Net.SSPIWrapper.EnumerateSecurityPackages(), System.Net.SSPIWrapper.EnumerateSecurityPackages(), System.Security.Cryptography.CngKey.Exists(), Internal.Cryptography.Pbkdf2Implementation.FillKeyDerivation(), System.IO.FileSystemWatcher.FinalizeDispose(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSendPackets(), System.Security.Cryptography.CngPkcs8.Pkcs8Response.FreeKey(), System.Net.NetworkInformation.Ping.FreeUnmanagedStructures(), System.Net.Security.SecureChannel.GenerateToken(), Internal.Cryptography.BCryptAeadHandleCache.GetCachedAlgorithmHandle(), System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle(), System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle(), Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(), Internal.NativeCrypto.CapiHelper.GetProviderParameter(), System.Net.CertificateValidationPal.GetRemoteCertificate(), System.Net.CertificateValidationPal.GetRequestCertificateAuthorities(), System.Net.WebSockets.WebSocketProtocolComponent.GetSupportedVersion(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventNewStream(), Microsoft.Win32.SafeHandles.SafeFileHandle.InitThreadPoolBinding(), System.Net.NetworkInformation.Ping.InternalDisposeCore(), System.IO.MemoryMappedFiles.MemoryMappedFile.OpenCore(), Microsoft.Win32.SafeHandles.SafeFileHandle.Preallocate(), System.Net.SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_REMOTE_CERT_CONTEXT(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.RemoveStream(), System.Security.Cryptography.ECCngKey.SetHandle(), System.Net.HttpListener.SetupV2Config(), System.IO.FileSystemWatcher.StartRaisingEvents(), System.IO.FileSystemWatcher.StopRaisingEvents(), System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(), System.Security.Principal.NTAccount.TranslateToSids(), Internal.NativeCrypto.CapiHelper.UnloadKey(), and System.Net.NetworkInformation.TeredoHelper.UnsafeNotifyStableUnicastIpAddressTable().