Terraria: System.Runtime.InteropServices.SafeHandle.DangerousAddRef
DangerousAddRef()
void System.Runtime.InteropServices.SafeHandle.DangerousAddRef (ref bool success) inline inherited
Definition at line 76 of file SafeHandle.cs.
    {
        int state;
        int value;
        do
        {
            state = _state;
            if (((uint)state & (true ? 1u : 0u)) != 0)
            {
                throw new ObjectDisposedException("SafeHandle", SR.ObjectDisposed_SafeHandleClosed);
            }
            value = state + 4;
        }
        while (Interlocked.CompareExchange(ref _state, value, state) != state);
        success = true;
    }
References System.Runtime.InteropServices.SafeHandle._state, System.Threading.Interlocked.CompareExchange(), System.SR.ObjectDisposed_SafeHandleClosed, System.state, and System.value.
Referenced by Microsoft.Win32.SafeHandles.DuplicateSafeNCryptKeyHandle.DuplicateSafeNCryptKeyHandle(), System.Net.Security.SafeCredentialReference.SafeCredentialReference(), Microsoft.Win32.SafeHandles.SafeNCryptHandle.SafeNCryptHandle(), System.Security.Principal.WindowsIdentity.WindowsIdentity(), System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.Security.SecureString.AcquireSpan(), System.Net.Security.SafeDeleteContext.CompleteAuthToken(), System.Net.SSPIAuthType.DecryptMessage(), System.Net.SSPISecureChannelType.DecryptMessage(), Microsoft.Win32.SafeHandles.SafeNCryptHandle.DuplicateDuplicatedHandle< T >(), System.Net.SSPIAuthType.EncryptMessage(), System.Net.SSPISecureChannelType.EncryptMessage(), System.Net.NegotiationInfoClass.GetAuthenticationPackageName(), System.Net.SSPIAuthType.GetSecurityContextToken(), System.Net.SSPIAuthType.MakeSignature(), System.Threading.WaitHandle.ObtainSafeWaitHandles(), System.Threading.RegisteredWaitHandle.OnBeforeRegister(), System.Net.Security.SafeFreeContextBuffer.QueryContextAttributes(), System.Net.Security.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding(), System.Runtime.InteropServices.SafeBuffer.Read< T >(), System.Runtime.InteropServices.SafeBuffer.ReadSpan< T >(), System.Security.Cryptography.SafeHashHandle.SetParent(), System.Security.Cryptography.SafeKeyHandle.SetParent(), Internal.NativeCrypto.SafeKeyHandle.SetParentHandle(), System.Threading.WaitHandle.SignalAndWait(), System.Net.Sockets.SocketPal.TransmitFileHelper(), System.Threading.RegisteredWaitHandle.UnregisterPortable(), System.Net.SSPIAuthType.VerifySignature(), System.Threading.WaitHandle.WaitOneNoCheck(), System.Runtime.InteropServices.SafeBuffer.Write< T >(), and System.Runtime.InteropServices.SafeBuffer.WriteSpan< T >().