Terraria: System.Runtime.InteropServices.SafeHandle.DangerousGetHandle
DangerousGetHandle()
IntPtr System.Runtime.InteropServices.SafeHandle.DangerousGetHandle () inline inherited
Definition at line 47 of file SafeHandle.cs.
    {
        return handle;
    }
References System.Runtime.InteropServices.SafeHandle.handle.
Referenced by Microsoft.Win32.SafeHandles.DuplicateSafeNCryptKeyHandle.DuplicateSafeNCryptKeyHandle(), System.Net.SecurityPackageInfoClass.SecurityPackageInfoClass(), System.Security.Principal.WindowsIdentity.WindowsIdentity(), System.Net.HttpListener.AttachRequestQueueToUrlGroup(), System.Net.CertificateValidation.BuildChainAndVerifyProperties(), System.Text.BaseCodePageEncoding.CheckMemorySection(), System.Net.NetworkInformation.Ping.CreatePingReply(), Microsoft.Win32.SafeHandles.SafeNCryptHandle.DuplicateDuplicatedHandle< T >(), Microsoft.Win32.SafeHandles.SafeNCryptHandle.DuplicateOwnerHandle< T >(), System.Net.NegotiationInfoClass.GetAuthenticationPackageName(), System.IO.Pipes.AnonymousPipeServerStream.GetClientHandleAsString(), System.Text.BaseCodePageEncoding.GetNativeMemory(), System.Diagnostics.Process.GetProcessHandle(), System.Net.CertificateValidationPal.GetRemoteCertificate(), System.Net.UnmanagedCertificateContext.GetRemoteCertificatesFromStoreContext(), System.Net.CertificateValidationPal.GetRequestCertificateAuthorities(), System.Security.Cryptography.CngKey.ImportEncryptedPkcs8(), System.Security.Cryptography.ECCng.ImportKeyBlob(), System.Threading.WaitHandle.ObtainSafeWaitHandles(), System.Net.SSPIWrapper.QueryStringContextAttributes(), System.Net.SSPIWrapper.QueryStringContextAttributes(), System.Net.NetworkInformation.Ping.SetUnmanagedStructures(), System.Net.Sockets.SocketAsyncEventArgs.SetupPinHandlesSendPackets(), System.Threading.WaitHandle.SignalAndWait(), System.Net.Sockets.SocketPal.TransmitFileHelper(), System.Threading.RegisteredWaitHandle.UnregisterPortable(), System.Threading.WaitHandle.WaitOneNoCheck(), and System.Net.HttpResponseStream.WriteCore().