Terraria: System.IO.UnmanagedMemoryStreamWrapper.CopyToAsync
CopyToAsync() [4/4]
override Task System.IO.UnmanagedMemoryStreamWrapper.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.MemoryStream.
Definition at line 135 of file UnmanagedMemoryStreamWrapper.cs.
    {
        if (destination == null)
        {
            throw new ArgumentNullException("destination");
        }
        if (bufferSize <= 0)
        {
            throw new ArgumentOutOfRangeException("bufferSize", SR.ArgumentOutOfRange_NeedPosNum);
        }
        if (!CanRead && !CanWrite)
        {
            ThrowHelper.ThrowObjectDisposedException_StreamClosed(null);
        }
        if (!destination.CanRead && !destination.CanWrite)
        {
            ThrowHelper.ThrowObjectDisposedException_StreamClosed("destination");
        }
        if (!CanRead)
        {
            ThrowHelper.ThrowNotSupportedException_UnreadableStream();
        }
        if (!destination.CanWrite)
        {
            ThrowHelper.ThrowNotSupportedException_UnwritableStream();
        }
        return _unmanagedStream.CopyToAsync(destination, bufferSize, cancellationToken);
    }
References System.IO.UnmanagedMemoryStreamWrapper._unmanagedStream, System.SR.ArgumentOutOfRange_NeedPosNum, System.cancellationToken, System.IO.UnmanagedMemoryStreamWrapper.CanRead, System.IO.UnmanagedMemoryStreamWrapper.CanWrite, System.IO.Stream.CopyToAsync(), System.destination, System.ThrowHelper.ThrowNotSupportedException_UnreadableStream(), System.ThrowHelper.ThrowNotSupportedException_UnwritableStream(), and System.ThrowHelper.ThrowObjectDisposedException_StreamClosed().