Terraria: System.Xml.Linq.Inserter.AddNode
AddNode()
void System.Xml.Linq.Inserter.AddNode (XNode n) inline private
Definition at line 111 of file Inserter.cs.
    {
        _parent.ValidateNode(n, _previous);
        if (n.parent != null)
        {
            n = n.CloneNode();
        }
        else
        {
            XNode parent = _parent;
            while (parent.parent != null)
            {
                parent = parent.parent;
            }
            if (n == parent)
            {
                n = n.CloneNode();
            }
        }
        _parent.ConvertTextToNode();
        if (_text != null)
        {
            if (_text.Length > 0)
            {
                if (_previous is XText xText && !(_previous is XCData))
                {
                    xText.Value += _text;
                }
                else
                {
                    InsertNode(new XText(_text));
                }
            }
            _text = null;
        }
        InsertNode(n);
    }
References System.Xml.Linq.Inserter._parent, System.Xml.Linq.Inserter._previous, System.Xml.Linq.Inserter._text, System.Xml.Linq.XNode.CloneNode(), System.Xml.Linq.XContainer.ConvertTextToNode(), System.Xml.Dictionary, System.Xml.Linq.Inserter.InsertNode(), System.Xml.Linq.XObject.parent, and System.Xml.Linq.XContainer.ValidateNode().
Referenced by System.Xml.Linq.Inserter.AddContent().