Terraria: System.Xml.Linq.Inserter.InsertNode
InsertNode()
void System.Xml.Linq.Inserter.InsertNode (XNode n) inline private
Definition at line 155 of file Inserter.cs.
    {
        bool flag = _parent.NotifyChanging(n, XObjectChangeEventArgs.Add);
        if (n.parent != null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
        }
        n.parent = _parent;
        if (_parent.content == null || _parent.content is string)
        {
            n.next = n;
            _parent.content = n;
        }
        else if (_previous == null)
        {
            XNode xNode = (XNode)_parent.content;
            n.next = xNode.next;
            xNode.next = n;
        }
        else
        {
            n.next = _previous.next;
            _previous.next = n;
            if (_parent.content == _previous)
            {
                _parent.content = n;
            }
        }
        _previous = n;
        if (flag)
        {
            _parent.NotifyChanged(n, XObjectChangeEventArgs.Add);
        }
    }
References System.Xml.Linq.Inserter._parent, System.Xml.Linq.Inserter._previous, System.Xml.Linq.XObjectChangeEventArgs.Add, System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.SR.InvalidOperation_ExternalCode, System.Xml.Linq.XNode.next, System.Xml.Linq.XObject.NotifyChanged(), and System.Xml.Linq.XObject.NotifyChanging().
Referenced by System.Xml.Linq.Inserter.Add(), and System.Xml.Linq.Inserter.AddNode().