Terraria: System.Xml.Linq.Inserter.AddContent
AddContent()
void System.Xml.Linq.Inserter.AddContent (object content) inline private
Definition at line 64 of file Inserter.cs.
    {
        if (content == null)
        {
            return;
        }
        if (content is XNode n)
        {
            AddNode(n);
            return;
        }
        if (content is string s)
        {
            AddString(s);
            return;
        }
        if (content is XStreamingElement other)
        {
            AddNode(new XElement(other));
            return;
        }
        if (content is object[] array)
        {
            object[] array2 = array;
            foreach (object content2 in array2)
            {
                AddContent(content2);
            }
            return;
        }
        if (content is IEnumerable enumerable)
        {
            {
                foreach (object item in enumerable)
                {
                    AddContent(item);
                }
                return;
            }
        }
        if (content is XAttribute)
        {
            throw new ArgumentException(System.SR.Argument_AddAttribute);
        }
        AddString(XContainer.GetStringValue(content));
    }
References System.Xml.Linq.Inserter.AddContent(), System.Xml.Linq.Inserter.AddNode(), System.Xml.Linq.Inserter.AddString(), System.SR.Argument_AddAttribute, System.Xml.ArgumentException, System.array, System.Xml.Dictionary, System.Xml.Linq.XContainer.GetStringValue(), System.item, System.other, and System.s.
Referenced by System.Xml.Linq.Inserter.Add(), and System.Xml.Linq.Inserter.AddContent().