Terraria: System.Xml.Linq.Inserter.Add
Add()
void System.Xml.Linq.Inserter.Add (object content) inline
Definition at line 20 of file Inserter.cs.
    {
        AddContent(content);
        if (_text == null)
        {
            return;
        }
        if (_parent.content == null)
        {
            if (_parent.SkipNotify())
            {
                _parent.content = _text;
            }
            else if (_text.Length > 0)
            {
                InsertNode(new XText(_text));
            }
            else if (_parent is XElement)
            {
                _parent.NotifyChanging(_parent, XObjectChangeEventArgs.Value);
                if (_parent.content != null)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
                }
                _parent.content = _text;
                _parent.NotifyChanged(_parent, XObjectChangeEventArgs.Value);
            }
            else
            {
                _parent.content = _text;
            }
        }
        else if (_text.Length > 0)
        {
            if (_previous is XText xText && !(_previous is XCData))
            {
                xText.Value += _text;
                return;
            }
            _parent.ConvertTextToNode();
            InsertNode(new XText(_text));
        }
    }
References System.Xml.Linq.Inserter._parent, System.Xml.Linq.Inserter._previous, System.Xml.Linq.Inserter._text, System.Xml.Linq.Inserter.AddContent(), System.Xml.Linq.XContainer.content, System.Xml.Linq.XContainer.ConvertTextToNode(), System.Xml.Dictionary, System.Xml.Linq.Inserter.InsertNode(), System.SR.InvalidOperation_ExternalCode, System.Xml.Linq.XObject.NotifyChanged(), System.Xml.Linq.XObject.NotifyChanging(), System.Xml.Linq.XObject.SkipNotify(), and System.Xml.Linq.XObjectChangeEventArgs.Value.
Referenced by System.Xml.Linq.XNode.AddAfterSelf(), System.Xml.Linq.XNode.AddBeforeSelf(), System.Xml.Linq.XContainer.AddFirst(), and System.Xml.Linq.XNode.ReplaceWith().