Terraria: System.Net.Http.DecompressionHandler.DecompressedContent.TryCreateContentReadStream
TryCreateContentReadStream()
override Stream System.Net.Http.DecompressionHandler.DecompressedContent.TryCreateContentReadStream () inline package virtual inherited
Reimplemented from System.Net.Http.HttpContent.
Definition at line 98 of file DecompressionHandler.cs.
        {
            Stream stream = _originalContent.TryReadAsStream();
            if (stream != null)
            {
                return GetDecompressedStream(stream);
            }
            return null;
        }
References System.Net.Http.DecompressionHandler.DecompressedContent._originalContent, System.Net.Http.DecompressionHandler.DecompressedContent.GetDecompressedStream(), System.stream, and System.Net.Http.HttpContent.TryReadAsStream().
Referenced by System.Net.Http.DecompressionHandler.DecompressedContent.SerializeToStreamAsync().