Terraria: System.Net.Http.DecompressionHandler.DecompressedContent.CreateContentReadStreamAsyncCore
CreateContentReadStreamAsyncCore()
async ValueTask< Stream > System.Net.Http.DecompressionHandler.DecompressedContent.CreateContentReadStreamAsyncCore (bool async, CancellationToken cancellationToken) inline private inherited
Definition at line 73 of file DecompressionHandler.cs.
        {
            if (_contentConsumed)
            {
                throw new InvalidOperationException(System.SR.net_http_content_stream_already_read);
            }
            _contentConsumed = true;
            Stream originalStream;
            if (async)
            {
                Stream stream = _originalContent.TryReadAsStream();
                Stream stream2 = stream;
                if (stream2 == null)
                {
                    stream2 = await _originalContent.ReadAsStreamAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
                originalStream = stream2;
            }
            else
            {
                originalStream = _originalContent.ReadAsStream(cancellationToken);
            }
            return GetDecompressedStream(originalStream);
        }
References System.Net.Http.DecompressionHandler.DecompressedContent._contentConsumed, System.Net.Http.DecompressionHandler.DecompressedContent._originalContent, System.cancellationToken, System.Net.Http.DecompressionHandler.DecompressedContent.GetDecompressedStream(), System.SR.net_http_content_stream_already_read, System.Net.Http.HttpContent.ReadAsStream(), System.Net.Http.HttpContent.ReadAsStreamAsync(), System.stream, and System.Net.Http.HttpContent.TryReadAsStream().
Referenced by System.Net.Http.DecompressionHandler.DecompressedContent.CreateContentReadStream(), and System.Net.Http.DecompressionHandler.DecompressedContent.CreateContentReadStreamAsync().