Terraria: MS.Internal.Xml.XPath.XPathScanner.XPathScanner
XPathScanner()
MS.Internal.Xml.XPath.XPathScanner.XPathScanner (string xpathExpr) inline
Definition at line 80 of file XPathScanner.cs.
    {
        this = default(XPathScanner);
        if (xpathExpr == null)
        {
            throw XPathException.Create(System.SR.Xp_ExprExpected, string.Empty);
        }
        _xpathExpr = xpathExpr;
        _numberValue = double.NaN;
        NextChar();
        NextLex();
    }
References MS.Internal.Xml.XPath.XPathScanner._numberValue, MS.Internal.Xml.XPath.XPathScanner._xpathExpr, System.Xml.XPath.XPathException.Create(), System.Xml.Dictionary, MS.Internal.Xml.XPath.XPathScanner.NextChar(), MS.Internal.Xml.XPath.XPathScanner.NextLex(), and System.SR.Xp_ExprExpected.