Terraria: MS.Internal.Xml.XPath.XPathScanner.NextLex
NextLex()
bool MS.Internal.Xml.XPath.XPathScanner.NextLex () inline
Definition at line 123 of file XPathScanner.cs.
    {
        SkipSpace();
        switch (CurrentChar)
        {
        case '\0':
            _kind = LexKind.Eof;
            return false;
        case '#':
        case '$':
        case '(':
        case ')':
        case '*':
        case '+':
        case ',':
        case '-':
        case '=':
        case '@':
        case '[':
        case ']':
        case '|':
            _kind = (LexKind)Convert.ToInt32(CurrentChar, CultureInfo.InvariantCulture);
            NextChar();
            break;
        case '<':
            _kind = LexKind.Lt;
            NextChar();
            if (CurrentChar == '=')
            {
                _kind = LexKind.Le;
                NextChar();
            }
            break;
        case '>':
            _kind = LexKind.Gt;
            NextChar();
            if (CurrentChar == '=')
            {
                _kind = LexKind.Ge;
                NextChar();
            }
            break;
        case '!':
            _kind = LexKind.Bang;
            NextChar();
            if (CurrentChar == '=')
            {
                _kind = LexKind.Ne;
                NextChar();
            }
            break;
        case '.':
            _kind = LexKind.Dot;
            NextChar();
            if (CurrentChar == '.')
            {
                _kind = LexKind.DotDot;
                NextChar();
            }
            else if (XmlCharType.IsDigit(CurrentChar))
            {
                _kind = LexKind.Number;
                _numberValue = ScanFraction();
            }
            break;
        case '/':
            _kind = LexKind.Slash;
            NextChar();
            if (CurrentChar == '/')
            {
                _kind = LexKind.SlashSlash;
                NextChar();
            }
            break;
        case '"':
        case '\'':
            _kind = LexKind.String;
            _stringValue = ScanString();
            break;
        default:
            if (XmlCharType.IsDigit(CurrentChar))
            {
                _kind = LexKind.Number;
                _numberValue = ScanNumber();
                break;
            }
            if (XmlCharType.IsStartNCNameSingleChar(CurrentChar))
            {
                _kind = LexKind.Name;
                _name = ScanName();
                _prefix = string.Empty;
                if (CurrentChar == ':')
                {
                    NextChar();
                    if (CurrentChar == ':')
                    {
                        NextChar();
                        _kind = LexKind.Axe;
                    }
                    else
                    {
                        _prefix = _name;
                        if (CurrentChar == '*')
{
                            NextChar();
                            _name = "*";
                        }
                        else
{
                            if (!XmlCharType.IsStartNCNameSingleChar(CurrentChar))
{
                                throw XPathException.Create(System.SR.Xp_InvalidName, SourceText);
                            }
                            _name = ScanName();
                        }
                    }
                }
                else
                {
                    SkipSpace();
                    if (CurrentChar == ':')
                    {
                        NextChar();
                        if (CurrentChar != ':')
{
                            throw XPathException.Create(System.SR.Xp_InvalidName, SourceText);
                        }
                        NextChar();
                        _kind = LexKind.Axe;
                    }
                }
                SkipSpace();
                _canBeFunction = CurrentChar == '(';
                break;
            }
            throw XPathException.Create(System.SR.Xp_InvalidToken, SourceText);
        }
        return true;
    }
References MS.Internal.Xml.XPath.XPathScanner._canBeFunction, MS.Internal.Xml.XPath.XPathScanner._kind, MS.Internal.Xml.XPath.XPathScanner._name, MS.Internal.Xml.XPath.XPathScanner._numberValue, MS.Internal.Xml.XPath.XPathScanner._prefix, MS.Internal.Xml.XPath.XPathScanner._stringValue, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathScanner.CurrentChar, System.Globalization.CultureInfo.InvariantCulture, System.Xml.XmlCharType.IsDigit(), System.Xml.XmlCharType.IsStartNCNameSingleChar(), MS.Internal.Xml.XPath.XPathScanner.NextChar(), MS.Internal.Xml.XPath.XPathScanner.ScanFraction(), MS.Internal.Xml.XPath.XPathScanner.ScanName(), MS.Internal.Xml.XPath.XPathScanner.ScanNumber(), MS.Internal.Xml.XPath.XPathScanner.ScanString(), MS.Internal.Xml.XPath.XPathScanner.SkipSpace(), MS.Internal.Xml.XPath.XPathScanner.SourceText, System.Convert.ToInt32(), System.SR.Xp_InvalidName, and System.SR.Xp_InvalidToken.
Referenced by MS.Internal.Xml.XPath.XPathScanner.XPathScanner(), and MS.Internal.Xml.XPath.XPathParser.NextLex().