Terraria: MS.Internal.Xml.XPath.XPathScanner.ScanString
ScanString()
string MS.Internal.Xml.XPath.XPathScanner.ScanString () inline private
Definition at line 297 of file XPathScanner.cs.
    {
        char currentChar = CurrentChar;
        NextChar();
        int startIndex = _xpathExprIndex - 1;
        int num = 0;
        while (CurrentChar != currentChar)
        {
            if (!NextChar())
            {
                throw XPathException.Create(System.SR.Xp_UnclosedString);
            }
            num++;
        }
        NextChar();
        return _xpathExpr.Substring(startIndex, num);
    }
References MS.Internal.Xml.XPath.XPathScanner._xpathExpr, MS.Internal.Xml.XPath.XPathScanner._xpathExprIndex, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.XPathScanner.CurrentChar, System.Xml.Dictionary, MS.Internal.Xml.XPath.XPathScanner.NextChar(), System.startIndex, and System.SR.Xp_UnclosedString.
Referenced by MS.Internal.Xml.XPath.XPathScanner.NextLex().