Terraria: MS.Internal.Xml.XPath.XPathScanner.SkipSpace
SkipSpace()
void MS.Internal.Xml.XPath.XPathScanner.SkipSpace () inline private
Definition at line 108 of file XPathScanner.cs.
    {
        if (XmlCharType.IsWhiteSpace(CurrentChar))
        {
            SkipKnownSpace();
        }
    }
References MS.Internal.Xml.XPath.XPathScanner.CurrentChar, System.Xml.XmlCharType.IsWhiteSpace(), and MS.Internal.Xml.XPath.XPathScanner.SkipKnownSpace().
Referenced by MS.Internal.Xml.XPath.XPathScanner.NextLex().