Terraria: MS.Internal.Xml.XPath.XPathScanner.ScanFraction
ScanFraction()
double MS.Internal.Xml.XPath.XPathScanner.ScanFraction () inline private
Definition at line 285 of file XPathScanner.cs.
    {
        int startIndex = _xpathExprIndex - 2;
        int num = 1;
        while (XmlCharType.IsDigit(CurrentChar))
        {
            NextChar();
            num++;
        }
        return XmlConvert.ToXPathDouble(_xpathExpr.Substring(startIndex, num));
    }
References MS.Internal.Xml.XPath.XPathScanner._xpathExpr, MS.Internal.Xml.XPath.XPathScanner._xpathExprIndex, MS.Internal.Xml.XPath.XPathScanner.CurrentChar, System.Xml.XmlCharType.IsDigit(), MS.Internal.Xml.XPath.XPathScanner.NextChar(), System.startIndex, and System.Xml.XmlConvert.ToXPathDouble().
Referenced by MS.Internal.Xml.XPath.XPathScanner.NextLex().