Terraria: MS.Internal.Xml.XPath.XPathScanner.NextChar
NextChar()
bool MS.Internal.Xml.XPath.XPathScanner.NextChar () inline private
Definition at line 93 of file XPathScanner.cs.
    {
        string xpathExpr = _xpathExpr;
        int xpathExprIndex = _xpathExprIndex;
        if ((uint)xpathExprIndex < (uint)xpathExpr.Length)
        {
            _currentChar = xpathExpr[xpathExprIndex];
            _xpathExprIndex = xpathExprIndex + 1;
            return true;
        }
        _currentChar = '\0';
        return false;
    }
References MS.Internal.Xml.XPath.XPathScanner._currentChar, MS.Internal.Xml.XPath.XPathScanner._xpathExpr, MS.Internal.Xml.XPath.XPathScanner._xpathExprIndex, and System.Xml.Dictionary.
Referenced by MS.Internal.Xml.XPath.XPathScanner.XPathScanner(), MS.Internal.Xml.XPath.XPathScanner.NextLex(), MS.Internal.Xml.XPath.XPathScanner.ScanFraction(), MS.Internal.Xml.XPath.XPathScanner.ScanNumber(), MS.Internal.Xml.XPath.XPathScanner.ScanString(), and MS.Internal.Xml.XPath.XPathScanner.SkipKnownSpace().