Terraria: System.Threading.Channels.ChannelWriter.WriteAsync
WriteAsync()
virtual ValueTask System.Threading.Channels.ChannelWriter< T >.WriteAsync (T item, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented in System.Threading.Channels.BoundedChannel< T >.BoundedChannelWriter, System.Threading.Channels.SingleConsumerUnboundedChannel< T >.UnboundedChannelWriter, and System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelWriter.
Definition at line 16 of file ChannelWriter.cs.
    {
        try
        {
            return cancellationToken.IsCancellationRequested ? new ValueTask(Task.FromCanceled<T>(cancellationToken)) : (TryWrite(item) ? default(ValueTask) : WriteAsyncCore(item, cancellationToken));
        }
        catch (Exception exception)
        {
            return new ValueTask(Task.FromException(exception));
        }
    }
References System.cancellationToken, System.exception, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.item, System.Threading.Channels.ChannelWriter< T >.TryWrite(), and System.Threading.Channels.ChannelWriter< T >.WriteAsyncCore().