Terraria: System.Linq.Expressions.Utils.Constant
Constant() [1/2]
static ConstantExpression System.Linq.Expressions.Utils.Constant (bool value) inline static
Definition at line 64 of file Utils.cs.
    {
        if (!value)
        {
            return s_false;
        }
        return s_true;
    }
References System.Linq.Expressions.Utils.s_false, System.Linq.Expressions.Utils.s_true, and System.value.
Referenced by System.Dynamic.ExpandoObject.MetaExpando.BindDeleteMember(), System.Dynamic.ExpandoObject.MetaExpando.BindGetOrInvokeMember(), System.Dynamic.ExpandoObject.MetaExpando.BindSetMember(), System.Runtime.CompilerServices.CallSite< T >.CreateCustomUpdateDelegate(), System.Linq.Expressions.TypeBinaryExpression.ReduceConstantTypeEqual(), System.Linq.Expressions.TypeBinaryExpression.ReduceTypeEqual(), System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign(), and System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch().