Terraria: System.Linq.Expressions.Utils.Empty
Empty
readonly DefaultExpression System.Linq.Expressions.Utils.Empty = Expression.Empty() static
Definition at line 60 of file Utils.cs.
Referenced by System.Linq.Expressions.Compiler.StackSpiller.MemberMemberBindingRewriter.AsExpression(), System.Linq.Expressions.Compiler.StackSpiller.ListBindingRewriter.AsExpression(), System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter.AsExpression(), System.Dynamic.DynamicObject.MetaDynamic.BuildCallMethodWithResult< TBinder >(), System.Dynamic.DynamicObject.MetaDynamic.CallMethodNoResult< TBinder >(), System.Linq.Expressions.Interpreter.LightCompiler.CompileConditionalExpression(), System.Linq.Expressions.Interpreter.LightCompiler.CompileSwitchExpression(), System.Linq.Expressions.ConditionalExpression.GetFalse(), System.Linq.Expressions.MemberInitExpression.ReduceListInit(), System.Linq.Expressions.MemberInitExpression.ReduceMemberInit(), System.Dynamic.DynamicObject.MetaDynamic.ReferenceArgAssign(), and System.Linq.Expressions.Compiler.LambdaCompiler.TryEmitHashtableSwitch().