Terraria: MiscShaderData.Apply
Apply() [2/2]
virtual void MiscShaderData.Apply (DrawData? drawData = null) inline virtual
     {
         base.Shader.Parameters["uColor"].SetValue(_uColor);
         base.Shader.Parameters["uSaturation"].SetValue(_uSaturation);
         base.Shader.Parameters["uSecondaryColor"].SetValue(_uSecondaryColor);
         base.Shader.Parameters["uTime"].SetValue(Main.GlobalTimeWrappedHourly);
         base.Shader.Parameters["uOpacity"].SetValue(_uOpacity);
         base.Shader.Parameters["uShaderSpecificData"].SetValue(_shaderSpecificData);
         if (drawData.HasValue)
         {
             DrawData value = drawData.Value;
             Vector4 value2 = Vector4.Zero;
             if (drawData.Value.sourceRect.HasValue)
             {
                 value2 = new Vector4(value.sourceRect.Value.X, value.sourceRect.Value.Y, value.sourceRect.Value.Width, value.sourceRect.Value.Height);
             }
             base.Shader.Parameters["uSourceRect"].SetValue(value2);
             base.Shader.Parameters["uWorldPosition"].SetValue(Main.screenPosition + value.position);
             base.Shader.Parameters["uImageSize0"].SetValue(new Vector2(value.texture.Width, value.texture.Height));
         }
         else
         {
             base.Shader.Parameters["uSourceRect"].SetValue(new Vector4(0f, 0f, 4f, 4f));
         }
         SamplerState value3 = SamplerState.LinearWrap;
         if (_customSamplerState != null)
         {
             value3 = _customSamplerState;
         }
         if (_uImage0 != null)
         {
             Main.graphics.GraphicsDevice.Textures[0] = _uImage0.Value;
             Main.graphics.GraphicsDevice.SamplerStates[0] = value3;
             base.Shader.Parameters["uImageSize0"].SetValue(new Vector2(_uImage0.Width(), _uImage0.Height()));
         }
         if (_uImage1 != null)
         {
             Main.graphics.GraphicsDevice.Textures[1] = _uImage1.Value;
             Main.graphics.GraphicsDevice.SamplerStates[1] = value3;
             base.Shader.Parameters["uImageSize1"].SetValue(new Vector2(_uImage1.Width(), _uImage1.Height()));
         }
         if (_uImage2 != null)
         {
             Main.graphics.GraphicsDevice.Textures[2] = _uImage2.Value;
             Main.graphics.GraphicsDevice.SamplerStates[2] = value3;
             base.Shader.Parameters["uImageSize2"].SetValue(new Vector2(_uImage2.Width(), _uImage2.Height()));
         }
         _ = _useProjectionMatrix;
         base.Apply();
     }
References _customSamplerState, _shaderSpecificData, _uColor, _uImage0, _uImage1, _uImage2, _uOpacity, _uSaturation, _uSecondaryColor, _useProjectionMatrix, Main.GlobalTimeWrappedHourly, Main.graphics, DrawData.position, Main.screenPosition, DrawData.sourceRect, DrawData.texture, and Asset< T >.Value.
Referenced by Segments.SpriteSegment.MaskedFadeEffect.BeforeDrawing(), EmpressBladeDrawer.Draw(), FinalFractalHelper.Draw(), FlameLashDrawer.Draw(), LightDiscDrawer.Draw(), MagicMissileDrawer.Draw(), RainbowRodDrawer.Draw(), and PlayerTitaniumStormBuffTextureContent.HandleUseReqest().