Terraria: System.Globalization.TimeSpanParse.TryTimeToTicks
TryTimeToTicks()
static bool System.Globalization.TimeSpanParse.TryTimeToTicks (bool positive, TimeSpanToken days, TimeSpanToken hours, TimeSpanToken minutes, TimeSpanToken seconds, TimeSpanToken fraction, out long result) inline static private
Definition at line 695 of file TimeSpanParse.cs.
    {
        if (days._num > 10675199 || hours._num > 23 || minutes._num > 59 || seconds._num > 59 || !fraction.NormalizeAndValidateFraction())
        {
            result = 0L;
            return false;
        }
        long num = ((long)days._num * 3600L * 24 + (long)hours._num * 3600L + (long)minutes._num * 60L + seconds._num) * 1000;
        if (num > 922337203685477L || num < -922337203685477L)
        {
            result = 0L;
            return false;
        }
        result = num * 10000 + fraction._num;
        if (positive && result < 0)
        {
            result = 0L;
            return false;
        }
        return true;
    }
References System.Globalization.TimeSpanParse.TimeSpanToken._num, System.L, and System.Globalization.TimeSpanParse.TimeSpanToken.NormalizeAndValidateFraction().
Referenced by System.Globalization.TimeSpanParse.ProcessTerminal_D(), System.Globalization.TimeSpanParse.ProcessTerminal_DHMSF(), System.Globalization.TimeSpanParse.ProcessTerminal_HM(), System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(), System.Globalization.TimeSpanParse.ProcessTerminal_HMS_F_D(), and System.Globalization.TimeSpanParse.TryParseByFormat().