Terraria: System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync
HandleReceivedCloseAsync()
async ValueTask System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync (MessageHeader header, CancellationToken cancellationToken) inline private
Definition at line 1048 of file ManagedWebSocket.cs.
    {
        lock (StateUpdateLock)
        {
            _receivedCloseFrame = true;
            if (_sentCloseFrame && _state < WebSocketState.Closed)
            {
                _state = WebSocketState.Closed;
            }
            else if (_state < WebSocketState.CloseReceived)
            {
                _state = WebSocketState.CloseReceived;
            }
        }
        WebSocketCloseStatus closeStatus = WebSocketCloseStatus.NormalClosure;
        string closeStatusDescription = string.Empty;
        if (header.PayloadLength == 1)
        {
            await CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus.ProtocolError, WebSocketError.Faulted).ConfigureAwait(continueOnCapturedContext: false);
        }
        else if (header.PayloadLength >= 2)
        {
            if (_receiveBufferCount < header.PayloadLength)
            {
                await EnsureBufferContainsAsync((int)header.PayloadLength, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (_isServer)
            {
                ApplyMask(_receiveBuffer.Span.Slice(_receiveBufferOffset, (int)header.PayloadLength), header.Mask, 0);
            }
            closeStatus = (WebSocketCloseStatus)((_receiveBuffer.Span[_receiveBufferOffset] << 8) | _receiveBuffer.Span[_receiveBufferOffset + 1]);
            if (!IsValidCloseStatus(closeStatus))
            {
                await CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus.ProtocolError, WebSocketError.Faulted).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (header.PayloadLength > 2)
            {
                try
                {
                    closeStatusDescription = s_textEncoding.GetString(_receiveBuffer.Span.Slice(_receiveBufferOffset + 2, (int)header.PayloadLength - 2));
                }
                catch (DecoderFallbackException innerException)
                {
                    await CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus.ProtocolError, WebSocketError.Faulted, null, innerException).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            ConsumeFromBuffer((int)header.PayloadLength);
        }
        _closeStatus = closeStatus;
        _closeStatusDescription = closeStatusDescription;
        if (!_isServer && _sentCloseFrame)
        {
            await WaitForServerToCloseConnectionAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Net.WebSockets.ManagedWebSocket._closeStatus, System.Net.WebSockets.ManagedWebSocket._closeStatusDescription, System.Net.WebSockets.ManagedWebSocket._isServer, System.Net.WebSockets.ManagedWebSocket._receiveBuffer, System.Net.WebSockets.ManagedWebSocket._receiveBufferCount, System.Net.WebSockets.ManagedWebSocket._receiveBufferOffset, System.Net.WebSockets.ManagedWebSocket._receivedCloseFrame, System.Net.WebSockets.ManagedWebSocket._sentCloseFrame, System.Net.WebSockets.ManagedWebSocket._state, System.Net.WebSockets.ManagedWebSocket.ApplyMask(), System.cancellationToken, System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.WebSockets.ManagedWebSocket.ConsumeFromBuffer(), System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(), System.Net.WebSockets.ManagedWebSocket.IsValidCloseStatus(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.Mask, System.Net.WebSockets.ManagedWebSocket.MessageHeader.PayloadLength, System.Net.WebSockets.ManagedWebSocket.s_textEncoding, System.Memory< T >.Span, System.Net.WebSockets.ManagedWebSocket.StateUpdateLock, and System.Net.WebSockets.ManagedWebSocket.WaitForServerToCloseConnectionAsync().
Referenced by System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext().