Terraria: System.Net.WebSockets.ManagedWebSocket.WaitForWriteTaskAsync
WaitForWriteTaskAsync()
async ValueTask System.Net.WebSockets.ManagedWebSocket.WaitForWriteTaskAsync (ValueTask writeTask) inline private
Definition at line 889 of file ManagedWebSocket.cs.
    {
        try
        {
            await writeTask.ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception ex) when (!(ex is OperationCanceledException))
        {
            throw (_state == WebSocketState.Aborted) ? CreateOperationCanceledException(ex) : new WebSocketException(WebSocketError.ConnectionClosedPrematurely, ex);
        }
        finally
        {
            ReleaseSendBuffer();
            _sendMutex.Exit();
        }
    }
References System.Net.WebSockets.ManagedWebSocket._sendMutex, System.Net.WebSockets.ManagedWebSocket._state, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.WebSockets.ManagedWebSocket.CreateOperationCanceledException(), System.Threading.AsyncMutex.Exit(), and System.Net.WebSockets.ManagedWebSocket.ReleaseSendBuffer().
Referenced by System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync().