Terraria: System.Net.WebSockets.ManagedWebSocket.WaitForServerToCloseConnectionAsync
WaitForServerToCloseConnectionAsync()
async ValueTask System.Net.WebSockets.ManagedWebSocket.WaitForServerToCloseConnectionAsync (CancellationToken cancellationToken) inline private
Definition at line 1104 of file ManagedWebSocket.cs.
    {
        ValueTask<int> valueTask = _stream.ReadAsync(_receiveBuffer, cancellationToken);
        if (valueTask.IsCompletedSuccessfully)
        {
            valueTask.GetAwaiter().GetResult();
            return;
        }
        try
        {
            await valueTask.AsTask().WaitAsync(TimeSpan.FromMilliseconds(1000.0)).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch
        {
            Abort();
        }
    }
References System.Net.WebSockets.ManagedWebSocket._receiveBuffer, System.Net.WebSockets.ManagedWebSocket._stream, System.Net.WebSockets.ManagedWebSocket.Abort(), System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.cancellationToken, System.TimeSpan.FromMilliseconds(), System.Threading.Tasks.ValueTask< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ValueTaskAwaiter< TResult >.GetResult(), System.Threading.Tasks.ValueTask< TResult >.IsCompletedSuccessfully, System.IO.Stream.ReadAsync(), and System.Threading.Tasks.Task< TResult >.WaitAsync().
Referenced by System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(), and System.Net.WebSockets.ManagedWebSocket.SendCloseFrameAsync().