Terraria: System.Globalization.TimeSpanParse.Parse
Parse()
static TimeSpan System.Globalization.TimeSpanParse.Parse (ReadOnlySpan< char > input, IFormatProvider formatProvider) inline static package
Definition at line 717 of file TimeSpanParse.cs.
    {
        TimeSpanResult result = new TimeSpanResult(throwOnFailure: true, input);
        bool flag = TryParseTimeSpan(input, TimeSpanStandardStyles.Any, formatProvider, ref result);
        return result.parsedTimeSpan;
    }
References System.input, System.Globalization.TimeSpanParse.TimeSpanResult.parsedTimeSpan, and System.Globalization.TimeSpanParse.TryParseTimeSpan().
Referenced by System.TimeSpan.Parse(), System.TimeSpan.Parse(), and System.TimeSpan.Parse().