Terraria: System.Net.WebSockets.ManagedWebSocket.ApplyMask
ApplyMask() [1/2]
static int System.Net.WebSockets.ManagedWebSocket.ApplyMask (Span< byte > toMask, byte[] mask, int maskOffset, int maskOffsetIndex) inline static private
Definition at line 1407 of file ManagedWebSocket.cs.
    {
        return ApplyMask(toMask, CombineMaskBytes(mask, maskOffset), maskOffsetIndex);
    }
References System.Net.WebSockets.ManagedWebSocket.ApplyMask(), and System.Net.WebSockets.ManagedWebSocket.CombineMaskBytes().
Referenced by System.Net.WebSockets.ManagedWebSocket.ApplyMask(), System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(), System.Net.WebSockets.ManagedWebSocket.HandleReceivedPingPongAsync(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), and System.Net.WebSockets.ManagedWebSocket.WriteFrameToSendBuffer().