Terraria: System.Net.WebSockets.ManagedWebSocket.ManagedWebSocket
ManagedWebSocket() [1/2]
System.Net.WebSockets.ManagedWebSocket.ManagedWebSocket (Stream stream, bool isServer, string subprotocol, TimeSpan keepAliveInterval) inline package
Definition at line 659 of file ManagedWebSocket.cs.
    {
        _stream = stream;
        _isServer = isServer;
        _subprotocol = subprotocol;
        _receiveBuffer = new byte[125];
        if (!(keepAliveInterval > TimeSpan.Zero))
        {
            return;
        }
        _keepAliveTimer = new Timer(delegate(object s)
        {
            WeakReference<ManagedWebSocket> weakReference = (WeakReference<ManagedWebSocket>)s;
            if (weakReference.TryGetTarget(out var target))
            {
                target.SendKeepAliveFrameAsync();
            }
        }, new WeakReference<ManagedWebSocket>(this), keepAliveInterval, keepAliveInterval);
    }
References System.Net.WebSockets.ManagedWebSocket._isServer, System.Net.WebSockets.ManagedWebSocket._keepAliveTimer, System.Net.WebSockets.ManagedWebSocket._receiveBuffer, System.Net.WebSockets.ManagedWebSocket._stream, System.Net.WebSockets.ManagedWebSocket._subprotocol, System.s, System.stream, System.WeakReference< T >.TryGetTarget(), and System.TimeSpan.Zero.
Referenced by System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), and System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync().