Terraria: System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync
SendFrameFallbackAsync()
async ValueTask System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync (MessageOpcode opcode, bool endOfMessage, bool disableCompression, ReadOnlyMemory< byte > payloadBuffer, Task lockTask, CancellationToken cancellationToken) inline private
Definition at line 906 of file ManagedWebSocket.cs.
    {
        await lockTask.ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            int length = WriteFrameToSendBuffer(opcode, endOfMessage, disableCompression, payloadBuffer.Span);
            using (cancellationToken.Register(delegate(object s)
            {
                ((ManagedWebSocket)s).Abort();
            }, this))
            {
                await _stream.WriteAsync(new ReadOnlyMemory<byte>(_sendBuffer, 0, length), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
        }
        catch (Exception ex) when (!(ex is OperationCanceledException))
        {
            throw (_state == WebSocketState.Aborted) ? CreateOperationCanceledException(ex, cancellationToken) : new WebSocketException(WebSocketError.ConnectionClosedPrematurely, ex);
        }
        finally
        {
            ReleaseSendBuffer();
            _sendMutex.Exit();
        }
    }
References System.Net.WebSockets.ManagedWebSocket.ManagedWebSocket(), System.Net.WebSockets.ManagedWebSocket._sendBuffer, System.Net.WebSockets.ManagedWebSocket._sendMutex, System.Net.WebSockets.ManagedWebSocket._state, System.Net.WebSockets.ManagedWebSocket._stream, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.WebSockets.ManagedWebSocket.CreateOperationCanceledException(), System.Threading.AsyncMutex.Exit(), System.length, System.Net.WebSockets.ManagedWebSocket.ReleaseSendBuffer(), System.s, System.ReadOnlyMemory< T >.Span, System.IO.Stream.WriteAsync(), and System.Net.WebSockets.ManagedWebSocket.WriteFrameToSendBuffer().
Referenced by System.Net.WebSockets.ManagedWebSocket.SendFrameAsync().