Terraria: System.Net.WebSockets.ManagedWebSocket.SendAsync
SendAsync() [3/3]
override ValueTask System.Net.WebSockets.ManagedWebSocket.SendAsync (ReadOnlyMemory< byte > buffer, WebSocketMessageType messageType, WebSocketMessageFlags messageFlags, CancellationToken cancellationToken) inline virtual
Reimplemented from System.Net.WebSockets.WebSocket.
Definition at line 737 of file ManagedWebSocket.cs.
    {
        if (messageType != 0 && messageType != WebSocketMessageType.Binary)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_WebSockets_Argument_InvalidMessageType, "Close", "SendAsync", "Binary", "Text", "CloseOutputAsync"), "messageType");
        }
        try
        {
            WebSocketValidate.ThrowIfInvalidState(_state, _disposed, s_validSendStates);
        }
        catch (Exception exception)
        {
            return new ValueTask(Task.FromException(exception));
        }
        bool flag = messageFlags.HasFlag(WebSocketMessageFlags.EndOfMessage);
        bool flag2 = messageFlags.HasFlag(WebSocketMessageFlags.DisableCompression);
        MessageOpcode opcode;
        if (_lastSendWasFragment)
        {
            if (_lastSendHadDisableCompression != flag2)
            {
                throw new ArgumentException(System.SR.net_WebSockets_Argument_MessageFlagsHasDifferentCompressionOptions, "messageFlags");
            }
            opcode = MessageOpcode.Continuation;
        }
        else
        {
            opcode = ((messageType != WebSocketMessageType.Binary) ? MessageOpcode.Text : MessageOpcode.Binary);
        }
        ValueTask result = SendFrameAsync(opcode, flag, flag2, buffer, cancellationToken);
        _lastSendWasFragment = !flag;
        _lastSendHadDisableCompression = flag2;
        return result;
    }
References System.Net.WebSockets.ManagedWebSocket._disposed, System.Net.WebSockets.ManagedWebSocket._lastSendHadDisableCompression, System.Net.WebSockets.ManagedWebSocket._lastSendWasFragment, System.Net.WebSockets.ManagedWebSocket._state, System.buffer, System.cancellationToken, System.exception, System.SR.Format(), System.Threading.Tasks.Task< TResult >.FromException(), System.SR.net_WebSockets_Argument_InvalidMessageType, System.SR.net_WebSockets_Argument_MessageFlagsHasDifferentCompressionOptions, System.Net.WebSockets.ManagedWebSocket.s_validSendStates, System.Net.WebSockets.ManagedWebSocket.SendFrameAsync(), and System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState().