Terraria: System.Net.WebSockets.ManagedWebSocket.CloseOutputAsync
CloseOutputAsync() [1/2]
override Task System.Net.WebSockets.ManagedWebSocket.CloseOutputAsync (WebSocketCloseStatus closeStatus, string statusDescription, CancellationToken cancellationToken) inline
Definition at line 813 of file ManagedWebSocket.cs.
    {
        WebSocketValidate.ValidateCloseStatus(closeStatus, statusDescription);
        return CloseOutputAsyncCore(closeStatus, statusDescription, cancellationToken);
    }
References System.cancellationToken, System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(), and System.Net.WebSockets.WebSocketValidate.ValidateCloseStatus().
Referenced by System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync().