Terraria: System.Globalization.TimeSpanParse.TryParseTimeSpan
TryParseTimeSpan()
static bool System.Globalization.TimeSpanParse.TryParseTimeSpan (ReadOnlySpan< char > input, TimeSpanStandardStyles style, IFormatProvider formatProvider, ref TimeSpanResult result) inline static private
Definition at line 774 of file TimeSpanParse.cs.
    {
        input = input.Trim();
        if (input.IsEmpty)
        {
            return result.SetBadTimeSpanFailure();
        }
        TimeSpanTokenizer timeSpanTokenizer = new TimeSpanTokenizer(input);
        TimeSpanRawInfo raw = default(TimeSpanRawInfo);
        raw.Init(DateTimeFormatInfo.GetInstance(formatProvider));
        TimeSpanToken tok = timeSpanTokenizer.GetNextToken();
        while (tok._ttt != TTT.End)
        {
            if (!raw.ProcessToken(ref tok, ref result))
            {
                return result.SetBadTimeSpanFailure();
            }
            tok = timeSpanTokenizer.GetNextToken();
        }
        if (!ProcessTerminalState(ref raw, style, ref result))
        {
            return result.SetBadTimeSpanFailure();
        }
        return true;
    }
References System.Globalization.TimeSpanParse.TimeSpanToken._ttt, System.Globalization.TimeSpanParse.TimeSpanTokenizer.GetNextToken(), System.Globalization.TimeSpanParse.TimeSpanRawInfo.Init(), System.input, System.Globalization.TimeSpanParse.ProcessTerminalState(), and System.Globalization.TimeSpanParse.TimeSpanRawInfo.ProcessToken().
Referenced by System.Globalization.TimeSpanParse.Parse(), System.Globalization.TimeSpanParse.TryParse(), and System.Globalization.TimeSpanParse.TryParseExactTimeSpan().