Terraria: System.Net.WebSockets.ManagedWebSocket.HandleReceivedPingPongAsync
HandleReceivedPingPongAsync()
async ValueTask System.Net.WebSockets.ManagedWebSocket.HandleReceivedPingPongAsync (MessageHeader header, CancellationToken cancellationToken) inline private
Definition at line 1122 of file ManagedWebSocket.cs.
    {
        if (header.PayloadLength > 0 && _receiveBufferCount < header.PayloadLength)
        {
            await EnsureBufferContainsAsync((int)header.PayloadLength, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        if (header.Opcode == MessageOpcode.Ping)
        {
            if (_isServer)
            {
                ApplyMask(_receiveBuffer.Span.Slice(_receiveBufferOffset, (int)header.PayloadLength), header.Mask, 0);
            }
            await SendFrameAsync(MessageOpcode.Pong, endOfMessage: true, disableCompression: true, _receiveBuffer.Slice(_receiveBufferOffset, (int)header.PayloadLength), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        if (header.PayloadLength > 0)
        {
            ConsumeFromBuffer((int)header.PayloadLength);
        }
    }
References System.Net.WebSockets.ManagedWebSocket._isServer, System.Net.WebSockets.ManagedWebSocket._receiveBuffer, System.Net.WebSockets.ManagedWebSocket._receiveBufferCount, System.Net.WebSockets.ManagedWebSocket._receiveBufferOffset, System.Net.WebSockets.ManagedWebSocket.ApplyMask(), System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.WebSockets.ManagedWebSocket.ConsumeFromBuffer(), System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.Mask, System.Net.WebSockets.ManagedWebSocket.MessageHeader.Opcode, System.Net.WebSockets.ManagedWebSocket.MessageHeader.PayloadLength, System.Net.WebSockets.ManagedWebSocket.SendFrameAsync(), System.Memory< T >.Slice(), and System.Memory< T >.Span.
Referenced by System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext().