Terraria: System.Xml.Xsl.XsltOld.ForEachAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.ForEachAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 36 of file ForEachAction.cs.
    {
        switch (frame.State)
        {
        default:
            return;
        case 0:
            if (_sortContainer != null)
            {
                processor.InitSortArray();
                processor.PushActionFrame(_sortContainer, frame.NodeSet);
                frame.State = 2;
                return;
            }
            goto case 2;
        case 2:
            frame.InitNewNodeSet(processor.StartQuery(frame.NodeSet, _selectKey));
            if (_sortContainer != null)
            {
                frame.SortNewNodeSet(processor, processor.SortArray);
            }
            frame.State = 3;
            goto case 3;
        case 3:
            if (frame.NewNextNode(processor))
            {
                frame.State = 4;
                break;
            }
            frame.Finished();
            return;
        case 4:
            break;
        case 5:
            frame.State = 3;
            goto case 3;
        case 1:
            return;
        }
        processor.PushActionFrame(frame, frame.NewNodeSet);
        frame.State = 5;
    }
References System.Xml.Xsl.XsltOld.ForEachAction._selectKey, System.Xml.Xsl.XsltOld.ForEachAction._sortContainer, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.ActionFrame.Finished(), System.Xml.Xsl.XsltOld.ActionFrame.InitNewNodeSet(), System.Xml.Xsl.XsltOld.ActionFrame.NewNextNode(), System.Xml.Xsl.XsltOld.ActionFrame.NewNodeSet, System.Xml.Xsl.XsltOld.ActionFrame.NodeSet, System.Xml.Xsl.XsltOld.ActionFrame.SortNewNodeSet(), and System.Xml.Xsl.XsltOld.ActionFrame.State.