Terraria: System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync
SendFrameLockAcquiredNonCancelableAsync()
ValueTask System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync (MessageOpcode opcode, bool endOfMessage, bool disableCompression, ReadOnlyMemory< byte > payloadBuffer) inline private
Definition at line 860 of file ManagedWebSocket.cs.
    {
        ValueTask valueTask = default(ValueTask);
        bool flag = true;
        try
        {
            int length = WriteFrameToSendBuffer(opcode, endOfMessage, disableCompression, payloadBuffer.Span);
            valueTask = _stream.WriteAsync(new ReadOnlyMemory<byte>(_sendBuffer, 0, length));
            if (valueTask.IsCompleted)
            {
                return valueTask;
            }
            flag = false;
        }
        catch (Exception ex)
        {
            return new ValueTask(Task.FromException((ex is OperationCanceledException) ? ex : ((_state == WebSocketState.Aborted) ? CreateOperationCanceledException(ex) : new WebSocketException(WebSocketError.ConnectionClosedPrematurely, ex))));
        }
        finally
        {
            if (flag)
            {
                ReleaseSendBuffer();
                _sendMutex.Exit();
            }
        }
        return WaitForWriteTaskAsync(valueTask);
    }
References System.Net.WebSockets.ManagedWebSocket._sendBuffer, System.Net.WebSockets.ManagedWebSocket._sendMutex, System.Net.WebSockets.ManagedWebSocket._state, System.Net.WebSockets.ManagedWebSocket._stream, System.Net.WebSockets.ManagedWebSocket.CreateOperationCanceledException(), System.Threading.AsyncMutex.Exit(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.Tasks.ValueTask< TResult >.IsCompleted, System.length, System.Net.WebSockets.ManagedWebSocket.ReleaseSendBuffer(), System.ReadOnlyMemory< T >.Span, System.Net.WebSockets.ManagedWebSocket.WaitForWriteTaskAsync(), System.IO.Stream.WriteAsync(), and System.Net.WebSockets.ManagedWebSocket.WriteFrameToSendBuffer().
Referenced by System.Net.WebSockets.ManagedWebSocket.SendFrameAsync().