Terraria: System.Net.WebSockets.ManagedWebSocket.SendFrameAsync
SendFrameAsync()
ValueTask System.Net.WebSockets.ManagedWebSocket.SendFrameAsync (MessageOpcode opcode, bool endOfMessage, bool disableCompression, ReadOnlyMemory< byte > payloadBuffer, CancellationToken cancellationToken) inline private
Definition at line 850 of file ManagedWebSocket.cs.
    {
        Task task = _sendMutex.EnterAsync(cancellationToken);
        if (!cancellationToken.CanBeCanceled && task.IsCompletedSuccessfully)
        {
            return SendFrameLockAcquiredNonCancelableAsync(opcode, endOfMessage, disableCompression, payloadBuffer);
        }
        return SendFrameFallbackAsync(opcode, endOfMessage, disableCompression, payloadBuffer, task, cancellationToken);
    }
References System.Net.WebSockets.ManagedWebSocket._sendMutex, System.cancellationToken, System.Threading.AsyncMutex.EnterAsync(), System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(), System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(), and System.task.
Referenced by System.Net.WebSockets.ManagedWebSocket.HandleReceivedPingPongAsync(), System.Net.WebSockets.ManagedWebSocket.SendAsync(), System.Net.WebSockets.ManagedWebSocket.SendCloseFrameAsync(), and System.Net.WebSockets.ManagedWebSocket.SendKeepAliveFrameAsync().