Terraria: System.Globalization.TimeSpanParse.ProcessTerminalState
ProcessTerminalState()
static bool System.Globalization.TimeSpanParse.ProcessTerminalState (ref TimeSpanRawInfo raw, TimeSpanStandardStyles style, ref TimeSpanResult result) inline static private
Definition at line 800 of file TimeSpanParse.cs.
    {
        if (raw._lastSeenTTT == TTT.Num)
        {
            TimeSpanToken tok = default(TimeSpanToken);
            tok._ttt = TTT.Sep;
            if (!raw.ProcessToken(ref tok, ref result))
            {
                return result.SetBadTimeSpanFailure();
            }
        }
        return raw._numCount switch
        {
            1 => ProcessTerminal_D(ref raw, style, ref result),
            2 => ProcessTerminal_HM(ref raw, style, ref result),
            3 => ProcessTerminal_HM_S_D(ref raw, style, ref result),
            4 => ProcessTerminal_HMS_F_D(ref raw, style, ref result),
            5 => ProcessTerminal_DHMSF(ref raw, style, ref result),
            _ => result.SetBadTimeSpanFailure(),
        };
    }
References System.Globalization.TimeSpanParse.ProcessTerminal_D(), System.Globalization.TimeSpanParse.ProcessTerminal_DHMSF(), System.Globalization.TimeSpanParse.ProcessTerminal_HM(), System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(), and System.Globalization.TimeSpanParse.ProcessTerminal_HMS_F_D().
Referenced by System.Globalization.TimeSpanParse.TryParseTimeSpan().