Terraria: System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync
CloseWithReceiveErrorAndThrowAsync()
async ValueTask System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync (WebSocketCloseStatus closeStatus, WebSocketError error, string errorMessage = null, Exception innerException = null) inline private
Definition at line 1159 of file ManagedWebSocket.cs.
    {
        if (!_sentCloseFrame)
        {
            await CloseOutputAsync(closeStatus, string.Empty, default(CancellationToken)).ConfigureAwait(continueOnCapturedContext: false);
        }
        _receiveBufferCount = 0;
        throw (errorMessage != null) ? new WebSocketException(error, errorMessage, innerException) : new WebSocketException(error, innerException);
    }
References System.Net.WebSockets.ManagedWebSocket._receiveBufferCount, System.Net.WebSockets.ManagedWebSocket._sentCloseFrame, System.Net.WebSockets.ManagedWebSocket.CloseOutputAsync(), and System.Threading.Tasks.Task< TResult >.ConfigureAwait().
Referenced by System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(), and System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext().