Terraria: System.Net.WebSockets.ManagedWebSocket.WriteFrameToSendBuffer
WriteFrameToSendBuffer()
int System.Net.WebSockets.ManagedWebSocket.WriteFrameToSendBuffer (MessageOpcode opcode, bool endOfMessage, bool disableCompression, ReadOnlySpan< byte > payloadBuffer) inline private
Definition at line 931 of file ManagedWebSocket.cs.
    {
        if (_deflater != null && !disableCompression)
        {
            payloadBuffer = _deflater.Deflate(payloadBuffer, endOfMessage);
        }
        int length = payloadBuffer.Length;
        AllocateSendBuffer(length + 14);
        int? num = null;
        int num2;
        if (_isServer)
        {
            num2 = WriteHeader(opcode, _sendBuffer, payloadBuffer, endOfMessage, useMask: false, _deflater != null && !disableCompression);
        }
        else
        {
            num = WriteHeader(opcode, _sendBuffer, payloadBuffer, endOfMessage, useMask: true, _deflater != null && !disableCompression);
            num2 = num.GetValueOrDefault() + 4;
        }
        if (payloadBuffer.Length > 0)
        {
            payloadBuffer.CopyTo(new Span<byte>(_sendBuffer, num2, length));
            _deflater?.ReleaseBuffer();
            if (num.HasValue)
            {
                ApplyMask(new Span<byte>(_sendBuffer, num2, length), _sendBuffer, num.Value, 0);
            }
        }
        return num2 + length;
    }
References System.Net.WebSockets.ManagedWebSocket._deflater, System.Net.WebSockets.ManagedWebSocket._isServer, System.Net.WebSockets.ManagedWebSocket._sendBuffer, System.Net.WebSockets.ManagedWebSocket.AllocateSendBuffer(), System.Net.WebSockets.ManagedWebSocket.ApplyMask(), System.ReadOnlySpan< T >.CopyTo(), System.Net.WebSockets.Compression.WebSocketDeflater.Deflate(), System.length, System.ReadOnlySpan< T >.Length, System.Net.WebSockets.Compression.WebSocketDeflater.ReleaseBuffer(), and System.Net.WebSockets.ManagedWebSocket.WriteHeader().
Referenced by System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(), and System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync().