Terraria: System.Net.WebSockets.ManagedWebSocket.TryParseMessageHeaderFromReceiveBuffer
TryParseMessageHeaderFromReceiveBuffer()
string System.Net.WebSockets.ManagedWebSocket.TryParseMessageHeaderFromReceiveBuffer (out MessageHeader resultHeader) inline private
Definition at line 1169 of file ManagedWebSocket.cs.
    {
        MessageHeader messageHeader = default(MessageHeader);
        Span<byte> span = _receiveBuffer.Span;
        messageHeader.Fin = (span[_receiveBufferOffset] & 0x80) != 0;
        bool flag = (span[_receiveBufferOffset] & 0x30) != 0;
        messageHeader.Opcode = (MessageOpcode)(span[_receiveBufferOffset] & 0xFu);
        messageHeader.Compressed = (span[_receiveBufferOffset] & 0x40) != 0;
        bool flag2 = (span[_receiveBufferOffset + 1] & 0x80) != 0;
        messageHeader.PayloadLength = span[_receiveBufferOffset + 1] & 0x7F;
        ConsumeFromBuffer(2);
        if (messageHeader.PayloadLength == 126)
        {
            messageHeader.PayloadLength = (span[_receiveBufferOffset] << 8) | span[_receiveBufferOffset + 1];
            ConsumeFromBuffer(2);
        }
        else if (messageHeader.PayloadLength == 127)
        {
            messageHeader.PayloadLength = 0L;
            for (int i = 0; i < 8; i++)
            {
                messageHeader.PayloadLength = (messageHeader.PayloadLength << 8) | span[_receiveBufferOffset + i];
            }
            ConsumeFromBuffer(8);
        }
        if (flag)
        {
            resultHeader = default(MessageHeader);
            return System.SR.net_Websockets_ReservedBitsSet;
        }
        if (messageHeader.PayloadLength < 0)
        {
            resultHeader = default(MessageHeader);
            return System.SR.net_Websockets_InvalidPayloadLength;
        }
        if (messageHeader.Compressed && _inflater == null)
        {
            resultHeader = default(MessageHeader);
            return System.SR.net_Websockets_PerMessageCompressedFlagWhenNotEnabled;
        }
        if (flag2)
        {
            if (!_isServer)
            {
                resultHeader = default(MessageHeader);
                return System.SR.net_Websockets_ClientReceivedMaskedFrame;
            }
            messageHeader.Mask = CombineMaskBytes(span, _receiveBufferOffset);
            ConsumeFromBuffer(4);
        }
        switch (messageHeader.Opcode)
        {
        case MessageOpcode.Continuation:
            if (_lastReceiveHeader.Fin)
            {
                resultHeader = default(MessageHeader);
                return System.SR.net_Websockets_ContinuationFromFinalFrame;
            }
            if (messageHeader.Compressed)
            {
                resultHeader = default(MessageHeader);
                return System.SR.net_Websockets_PerMessageCompressedFlagInContinuation;
            }
            messageHeader.Compressed = _lastReceiveHeader.Compressed;
            break;
        case MessageOpcode.Text:
        case MessageOpcode.Binary:
            if (!_lastReceiveHeader.Fin)
            {
                resultHeader = default(MessageHeader);
                return System.SR.net_Websockets_NonContinuationAfterNonFinalFrame;
            }
            break;
        case MessageOpcode.Close:
        case MessageOpcode.Ping:
        case MessageOpcode.Pong:
            if (messageHeader.PayloadLength > 125 || !messageHeader.Fin)
            {
                resultHeader = default(MessageHeader);
                return System.SR.net_Websockets_InvalidControlMessage;
            }
            break;
        default:
            resultHeader = default(MessageHeader);
            return System.SR.Format(System.SR.net_Websockets_UnknownOpcode, messageHeader.Opcode);
        }
        messageHeader.Processed = messageHeader.PayloadLength == 0L && !messageHeader.Compressed;
        resultHeader = messageHeader;
        return null;
    }
References System.Net.WebSockets.ManagedWebSocket._inflater, System.Net.WebSockets.ManagedWebSocket._isServer, System.Net.WebSockets.ManagedWebSocket._lastReceiveHeader, System.Net.WebSockets.ManagedWebSocket._receiveBuffer, System.Net.WebSockets.ManagedWebSocket._receiveBufferOffset, System.Net.WebSockets.ManagedWebSocket.CombineMaskBytes(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.Compressed, System.Net.WebSockets.ManagedWebSocket.ConsumeFromBuffer(), System.Net.WebSockets.ManagedWebSocket.MessageHeader.Fin, System.SR.Format(), System.L, System.SR.net_Websockets_ClientReceivedMaskedFrame, System.SR.net_Websockets_ContinuationFromFinalFrame, System.SR.net_Websockets_InvalidControlMessage, System.SR.net_Websockets_InvalidPayloadLength, System.SR.net_Websockets_NonContinuationAfterNonFinalFrame, System.SR.net_Websockets_PerMessageCompressedFlagInContinuation, System.SR.net_Websockets_PerMessageCompressedFlagWhenNotEnabled, System.SR.net_Websockets_ReservedBitsSet, System.SR.net_Websockets_UnknownOpcode, System.Net.WebSockets.ManagedWebSocket.MessageHeader.Opcode, System.Net.WebSockets.ManagedWebSocket.MessageHeader.PayloadLength, and System.Memory< T >.Span.
Referenced by System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext().