Terraria: System.Net.WebSockets.ManagedWebSocket.SendAsync
SendAsync() [1/3]
override Task System.Net.WebSockets.ManagedWebSocket.SendAsync (ArraySegment< byte > buffer, WebSocketMessageType messageType, bool endOfMessage, CancellationToken cancellationToken) inline
Definition at line 722 of file ManagedWebSocket.cs.
    {
        if (messageType != 0 && messageType != WebSocketMessageType.Binary)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_WebSockets_Argument_InvalidMessageType, "Close", "SendAsync", "Binary", "Text", "CloseOutputAsync"), "messageType");
        }
        WebSocketValidate.ValidateArraySegment(buffer, "buffer");
        return SendAsync(buffer, messageType, endOfMessage ? WebSocketMessageFlags.EndOfMessage : WebSocketMessageFlags.None, cancellationToken).AsTask();
    }
References System.buffer, System.cancellationToken, System.SR.Format(), System.SR.net_WebSockets_Argument_InvalidMessageType, System.Net.WebSockets.ManagedWebSocket.SendAsync(), and System.Net.WebSockets.WebSocketValidate.ValidateArraySegment().
Referenced by System.Net.WebSockets.ManagedWebSocket.SendAsync(), and System.Net.WebSockets.ManagedWebSocket.SendAsync().