Terraria: System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync
EnsureBufferContainsAsync()
ValueTask System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync (int minimumRequiredBytes, CancellationToken cancellationToken, bool throwOnPrematureClosure = true) inline private
Definition at line 1362 of file ManagedWebSocket.cs.
    {
        Unsafe.SkipInit(out _003CEnsureBufferContainsAsync_003Ed__74 stateMachine);
        stateMachine._003C_003Et__builder = PoolingAsyncValueTaskMethodBuilder.Create();
        stateMachine._003C_003E4__this = this;
        stateMachine.minimumRequiredBytes = minimumRequiredBytes;
        stateMachine.cancellationToken = cancellationToken;
        stateMachine.throwOnPrematureClosure = throwOnPrematureClosure;
        stateMachine._003C_003E1__state = -1;
        stateMachine._003C_003Et__builder.Start(ref stateMachine);
        return stateMachine._003C_003Et__builder.Task;
    }
References System.cancellationToken, System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.Create(), and System.stateMachine.
Referenced by System.Net.WebSockets.ManagedWebSocket.HandleReceivedCloseAsync(), System.Net.WebSockets.ManagedWebSocket.HandleReceivedPingPongAsync(), and System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext().