Terraria: System.Net.WebSockets.ManagedWebSocket.SendCloseFrameAsync
SendCloseFrameAsync()
async ValueTask System.Net.WebSockets.ManagedWebSocket.SendCloseFrameAsync (WebSocketCloseStatus closeStatus, string closeStatusDescription, CancellationToken cancellationToken) inline private
Definition at line 1308 of file ManagedWebSocket.cs.
    {
        byte[] buffer = null;
        try
        {
            int num = 2;
            if (string.IsNullOrEmpty(closeStatusDescription))
            {
                buffer = ArrayPool<byte>.Shared.Rent(num);
            }
            else
            {
                num += s_textEncoding.GetByteCount(closeStatusDescription);
                buffer = ArrayPool<byte>.Shared.Rent(num);
                s_textEncoding.GetBytes(closeStatusDescription, 0, closeStatusDescription.Length, buffer, 2);
            }
            ushort num2 = (ushort)closeStatus;
            buffer[0] = (byte)(num2 >> 8);
            buffer[1] = (byte)(num2 & 0xFFu);
            await SendFrameAsync(MessageOpcode.Close, endOfMessage: true, disableCompression: true, new Memory<byte>(buffer, 0, num), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        finally
        {
            if (buffer != null)
            {
                ArrayPool<byte>.Shared.Return(buffer);
            }
        }
        lock (StateUpdateLock)
        {
            _sentCloseFrame = true;
            if (_receivedCloseFrame && _state < WebSocketState.Closed)
            {
                _state = WebSocketState.Closed;
            }
            else if (_state < WebSocketState.CloseSent)
            {
                _state = WebSocketState.CloseSent;
            }
        }
        if (!_isServer && _receivedCloseFrame)
        {
            await WaitForServerToCloseConnectionAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
    }
References System.Net.WebSockets.ManagedWebSocket._isServer, System.Net.WebSockets.ManagedWebSocket._receivedCloseFrame, System.Net.WebSockets.ManagedWebSocket._sentCloseFrame, System.Net.WebSockets.ManagedWebSocket._state, System.buffer, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.WebSockets.ManagedWebSocket.s_textEncoding, System.Net.WebSockets.ManagedWebSocket.SendFrameAsync(), System.Buffers.ArrayPool< T >.Shared, System.Net.WebSockets.ManagedWebSocket.StateUpdateLock, and System.Net.WebSockets.ManagedWebSocket.WaitForServerToCloseConnectionAsync().
Referenced by System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(), and System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore().