Terraria: System.Net.WebSockets.ManagedWebSocket.DisposeCore
DisposeCore()
void System.Net.WebSockets.ManagedWebSocket.DisposeCore () inline private
Definition at line 706 of file ManagedWebSocket.cs.
    {
        if (!_disposed)
        {
            _disposed = true;
            _keepAliveTimer?.Dispose();
            _stream.Dispose();
            _inflater?.Dispose();
            _deflater?.Dispose();
            if (_state < WebSocketState.Aborted)
            {
                _state = WebSocketState.Closed;
            }
        }
    }
References System.Net.WebSockets.ManagedWebSocket._deflater, System.Net.WebSockets.ManagedWebSocket._disposed, System.Net.WebSockets.ManagedWebSocket._inflater, System.Net.WebSockets.ManagedWebSocket._keepAliveTimer, System.Net.WebSockets.ManagedWebSocket._state, System.Net.WebSockets.ManagedWebSocket._stream, System.Net.WebSockets.Compression.WebSocketDeflater.Dispose(), System.Net.WebSockets.Compression.WebSocketInflater.Dispose(), System.IO.Stream.Dispose(), and System.Threading.Timer.Dispose().
Referenced by System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate(), System.Net.WebSockets.ManagedWebSocket.CloseOutputAsyncCore(), and System.Net.WebSockets.ManagedWebSocket.Dispose().