Terraria: System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate
CloseAsyncPrivate()
async Task System.Net.WebSockets.ManagedWebSocket.CloseAsyncPrivate (WebSocketCloseStatus closeStatus, string statusDescription, CancellationToken cancellationToken) inline private
Definition at line 1260 of file ManagedWebSocket.cs.
    {
        if (!_sentCloseFrame)
        {
            await SendCloseFrameAsync(closeStatus, statusDescription, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        if (State == WebSocketState.CloseSent)
        {
            byte[] closeBuffer = ArrayPool<byte>.Shared.Rent(139);
            try
            {
                while (!_receivedCloseFrame)
                {
                    ValueTask<ValueWebSocketReceiveResult> receiveTask = default(ValueTask<ValueWebSocketReceiveResult>);
                    try
                    {
                        await _receiveMutex.EnterAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        try
{
                            if (!_receivedCloseFrame)
{
                                receiveTask = ReceiveAsyncPrivate<ValueWebSocketReceiveResult>(closeBuffer, cancellationToken);
                            }
                        }
                        finally
{
                            _receiveMutex.Exit();
                        }
                    }
                    catch (OperationCanceledException)
                    {
                        Abort();
                        throw;
                    }
                    await receiveTask.ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            finally
            {
                ArrayPool<byte>.Shared.Return(closeBuffer);
            }
        }
        lock (StateUpdateLock)
        {
            DisposeCore();
        }
    }
References System.Net.WebSockets.ManagedWebSocket._receivedCloseFrame, System.Net.WebSockets.ManagedWebSocket._receiveMutex, System.Net.WebSockets.ManagedWebSocket._sentCloseFrame, System.Net.WebSockets.ManagedWebSocket.Abort(), System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.WebSockets.ManagedWebSocket.DisposeCore(), System.Threading.AsyncMutex.EnterAsync(), System.Threading.AsyncMutex.Exit(), System.Net.WebSockets.ManagedWebSocket.SendCloseFrameAsync(), System.Buffers.ArrayPool< T >.Shared, and System.Net.WebSockets.ManagedWebSocket.StateUpdateLock.
Referenced by System.Net.WebSockets.ManagedWebSocket.CloseAsync().