Terraria: System.Net.NetworkInformation.SystemIPInterfaceProperties.SystemIPInterfaceProperties
SystemIPInterfaceProperties()
System.Net.NetworkInformation.SystemIPInterfaceProperties.SystemIPInterfaceProperties (in global::Interop::IpHlpApi::FIXED_INFO fixedInfo, in global::Interop::IpHlpApi::IpAdapterAddresses ipAdapterAddresses) inline package
Definition at line 53 of file SystemIPInterfaceProperties.cs.
    {
        _adapterFlags = ipAdapterAddresses.flags;
        _dnsSuffix = ipAdapterAddresses.dnsSuffix;
        _dnsEnabled = fixedInfo.enableDns;
        _dynamicDnsEnabled = (ipAdapterAddresses.flags & global::Interop.IpHlpApi.AdapterFlags.DnsEnabled) > (global::Interop.IpHlpApi.AdapterFlags)0;
        _multicastAddresses = SystemMulticastIPAddressInformation.ToMulticastIpAddressInformationCollection(global::Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressInformationCollection(ipAdapterAddresses.firstMulticastAddress));
        _dnsAddresses = global::Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressCollection(ipAdapterAddresses.firstDnsServerAddress);
        _anycastAddresses = global::Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressInformationCollection(ipAdapterAddresses.firstAnycastAddress);
        _unicastAddresses = SystemUnicastIPAddressInformation.MarshalUnicastIpAddressInformationCollection(ipAdapterAddresses.firstUnicastAddress);
        _winsServersAddresses = global::Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressCollection(ipAdapterAddresses.firstWinsServerAddress);
        _gatewayAddresses = SystemGatewayIPAddressInformation.ToGatewayIpAddressInformationCollection(global::Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressCollection(ipAdapterAddresses.firstGatewayAddress));
        _dhcpServers = new InternalIPAddressCollection();
        if (ipAdapterAddresses.dhcpv4Server.address != IntPtr.Zero)
        {
            _dhcpServers.InternalAdd(ipAdapterAddresses.dhcpv4Server.MarshalIPAddress());
        }
        if (ipAdapterAddresses.dhcpv6Server.address != IntPtr.Zero)
        {
            _dhcpServers.InternalAdd(ipAdapterAddresses.dhcpv6Server.MarshalIPAddress());
        }
        if ((_adapterFlags & global::Interop.IpHlpApi.AdapterFlags.IPv4Enabled) != 0)
        {
            _ipv4Properties = new SystemIPv4InterfaceProperties(fixedInfo, ipAdapterAddresses);
        }
        if ((_adapterFlags & global::Interop.IpHlpApi.AdapterFlags.IPv6Enabled) != 0)
        {
            _ipv6Properties = new SystemIPv6InterfaceProperties(ipAdapterAddresses.ipv6Index, ipAdapterAddresses.mtu, ipAdapterAddresses.zoneIndices);
        }
    }
References System.Net.NetworkInformation.SystemIPInterfaceProperties._adapterFlags, System.Net.NetworkInformation.SystemIPInterfaceProperties._anycastAddresses, System.Net.NetworkInformation.SystemIPInterfaceProperties._dhcpServers, System.Net.NetworkInformation.SystemIPInterfaceProperties._dnsAddresses, System.Net.NetworkInformation.SystemIPInterfaceProperties._dnsEnabled, System.Net.NetworkInformation.SystemIPInterfaceProperties._dnsSuffix, System.Net.NetworkInformation.SystemIPInterfaceProperties._dynamicDnsEnabled, System.Net.NetworkInformation.SystemIPInterfaceProperties._gatewayAddresses, System.Net.NetworkInformation.SystemIPInterfaceProperties._ipv4Properties, System.Net.NetworkInformation.SystemIPInterfaceProperties._ipv6Properties, System.Net.NetworkInformation.SystemIPInterfaceProperties._multicastAddresses, System.Net.NetworkInformation.SystemIPInterfaceProperties._unicastAddresses, System.Net.NetworkInformation.SystemIPInterfaceProperties._winsServersAddresses, System.Net.NetworkInformation.InternalIPAddressCollection.InternalAdd(), System.Net.NetworkInformation.SystemUnicastIPAddressInformation.MarshalUnicastIpAddressInformationCollection(), System.Net.NetworkInformation.SystemGatewayIPAddressInformation.ToGatewayIpAddressInformationCollection(), System.Net.NetworkInformation.SystemMulticastIPAddressInformation.ToMulticastIpAddressInformationCollection(), and System.IntPtr.Zero.