Terraria: System.Xml.Schema.ContentValidator.ValidateElement
ValidateElement()
virtual object System.Xml.Schema.ContentValidator.ValidateElement (XmlQualifiedName name, ValidationState context, out int errorCode) inline virtual
Reimplemented in System.Xml.Schema.AllElementsContentValidator, System.Xml.Schema.DfaContentValidator, System.Xml.Schema.NfaContentValidator, System.Xml.Schema.ParticleContentValidator, and System.Xml.Schema.RangeContentValidator.
Definition at line 70 of file ContentValidator.cs.
    {
        if (_contentType == XmlSchemaContentType.TextOnly || _contentType == XmlSchemaContentType.Empty)
        {
            context.NeedValidateChildren = false;
        }
        errorCode = -1;
        return null;
    }
References System.Xml.Schema.ContentValidator._contentType, and System.Xml.Dictionary.
Referenced by System.Xml.Schema.DtdValidator.ValidateChildElement(), System.Xml.Schema.XdrValidator.ValidateChildElement(), System.Xml.Schema.XsdValidator.ValidateChildElement(), and System.Xml.Schema.XmlSchemaValidator.ValidateElementContext().