Terraria: System.Xml.Schema.ContentValidator.ExpectedParticles
ExpectedParticles()
virtual ArrayList System.Xml.Schema.ContentValidator.ExpectedParticles (ValidationState context, bool isRequiredOnly, XmlSchemaSet schemaSet) inline virtual inherited
Reimplemented in System.Xml.Schema.AllElementsContentValidator, System.Xml.Schema.DfaContentValidator, System.Xml.Schema.NfaContentValidator, and System.Xml.Schema.RangeContentValidator.
Definition at line 90 of file ContentValidator.cs.
    {
        return null;
    }
Referenced by System.Xml.Schema.XmlSchemaValidator.CompleteValidationError(), System.Xml.Schema.XmlSchemaValidator.GetExpectedParticles(), and System.Xml.Schema.XmlSchemaValidator.ValidateText().