Terraria: Terraria.GameContent.Bestiary.BestiaryEntry.Enemy
Enemy()
static BestiaryEntry Terraria.GameContent.Bestiary.BestiaryEntry.Enemy (int npcNetId) inline static
    {
        NPC nPC = ContentSamples.NpcsByNetId[npcNetId];
        List<IBestiaryInfoElement> list = new List<IBestiaryInfoElement>
        {
            new NPCNetIdBestiaryInfoElement(npcNetId),
            new NamePlateInfoElement(Lang.GetNPCName(npcNetId).Key, npcNetId),
            new NPCPortraitInfoElement(ContentSamples.NpcBestiaryRarityStars[npcNetId]),
            new NPCKillCounterInfoElement(npcNetId)
        };
        list.Add(new NPCStatsReportInfoElement(npcNetId));
        if (nPC.rarity != 0)
        {
            list.Add(new RareSpawnBestiaryInfoElement(nPC.rarity));
        }
        IBestiaryUICollectionInfoProvider uIInfoProvider;
        if (nPC.boss || NPCID.Sets.ShouldBeCountedAsBoss[nPC.type])
        {
            list.Add(new BossBestiaryInfoElement());
            uIInfoProvider = new CommonEnemyUICollectionInfoProvider(nPC.GetBestiaryCreditId(), quickUnlock: true);
        }
        else
        {
            uIInfoProvider = new CommonEnemyUICollectionInfoProvider(nPC.GetBestiaryCreditId(), quickUnlock: false);
        }
        string key = Lang.GetNPCName(nPC.netID).Key;
        key = key.Replace("NPCName.", "");
        string text = "Bestiary_FlavorText.npc_" + key;
        if (Language.Exists(text))
        {
            list.Add(new FlavorTextBestiaryInfoElement(text));
        }
        return new BestiaryEntry
        {
            Icon = new UnlockableNPCEntryIcon(npcNetId),
            Info = list,
            UIInfoProvider = uIInfoProvider
        };
    }
References Terraria.NPC.boss, Terraria.Localization.Language.Exists(), Terraria.NPC.GetBestiaryCreditId(), Terraria.Lang.GetNPCName(), Terraria.GameContent.Bestiary.BestiaryEntry.Icon, Terraria.GameContent.Bestiary.BestiaryEntry.Info, Terraria.Localization.LocalizedText.Key, Terraria.NPC.netID, Terraria.ID.ContentSamples.NpcBestiaryRarityStars, Terraria.ID.ContentSamples.NpcsByNetId, Terraria.NPC.rarity, Terraria.ID.NPCID.Sets.ShouldBeCountedAsBoss, Terraria.NPC.type, and Terraria.GameContent.Bestiary.BestiaryEntry.UIInfoProvider.
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated(), and Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddMultiEntryNPCS_Manual().