Terraria: Terraria.GameContent.Bestiary.BestiaryEntry.TownNPC
TownNPC()
static BestiaryEntry Terraria.GameContent.Bestiary.BestiaryEntry.TownNPC (int npcNetId) inline static
Definition at line 61 of file BestiaryEntry.cs.
    {
        NPC nPC = ContentSamples.NpcsByNetId[npcNetId];
        List<IBestiaryInfoElement> list = new List<IBestiaryInfoElement>
        {
            new NPCNetIdBestiaryInfoElement(npcNetId),
            new NamePlateInfoElement(Lang.GetNPCName(npcNetId).Key, npcNetId),
            new NPCPortraitInfoElement(ContentSamples.NpcBestiaryRarityStars[npcNetId]),
            new NPCKillCounterInfoElement(npcNetId)
        };
        string key = Lang.GetNPCName(nPC.netID).Key;
        key = key.Replace("NPCName.", "");
        string text = "Bestiary_FlavorText.npc_" + key;
        if (Language.Exists(text))
        {
            list.Add(new FlavorTextBestiaryInfoElement(text));
        }
        return new BestiaryEntry
        {
            Icon = new UnlockableNPCEntryIcon(npcNetId),
            Info = list,
            UIInfoProvider = new TownNPCUICollectionInfoProvider(nPC.GetBestiaryCreditId())
        };
    }
References Terraria.Localization.Language.Exists(), Terraria.NPC.GetBestiaryCreditId(), Terraria.Lang.GetNPCName(), Terraria.GameContent.Bestiary.BestiaryEntry.Icon, Terraria.GameContent.Bestiary.BestiaryEntry.Info, Terraria.Localization.LocalizedText.Key, Terraria.NPC.netID, Terraria.ID.ContentSamples.NpcBestiaryRarityStars, Terraria.ID.ContentSamples.NpcsByNetId, and Terraria.GameContent.Bestiary.BestiaryEntry.UIInfoProvider.
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddTownNPCs_Manual().