Terraria: System.RuntimeType.RuntimeTypeCache.GetEnclosingType
GetEnclosingType()
RuntimeType System.RuntimeType.RuntimeTypeCache.GetEnclosingType () inline package
Definition at line 1267 of file RuntimeType.cs.
        {
            if (m_enclosingType == null)
            {
                RuntimeType declaringType = RuntimeTypeHandle.GetDeclaringType(GetRuntimeType());
                m_enclosingType = declaringType ?? ((RuntimeType)typeof(void));
            }
            if (!(m_enclosingType == typeof(void)))
            {
                return m_enclosingType;
            }
            return null;
        }
References System.RuntimeType.RuntimeType(), System.RuntimeTypeHandle.GetDeclaringType(), System.RuntimeType.RuntimeTypeCache.GetRuntimeType(), and System.RuntimeType.RuntimeTypeCache.m_enclosingType.