Terraria: System.RuntimeType.RuntimeTypeCache.GetGenericMethodInfo
GetGenericMethodInfo()
MethodInfo System.RuntimeType.RuntimeTypeCache.GetGenericMethodInfo (RuntimeMethodHandleInternal genericMethod) inline package
Definition at line 1325 of file RuntimeType.cs.
        {
            LoaderAllocator loaderAllocator = RuntimeMethodHandle.GetLoaderAllocator(genericMethod);
            RuntimeMethodInfo runtimeMethodInfo = new RuntimeMethodInfo(genericMethod, RuntimeMethodHandle.GetDeclaringType(genericMethod), this, RuntimeMethodHandle.GetAttributes(genericMethod), (BindingFlags)(-1), loaderAllocator);
            RuntimeMethodInfo runtimeMethodInfo2 = ((loaderAllocator == null) ? s_methodInstantiations[runtimeMethodInfo] : loaderAllocator.m_methodInstantiations[runtimeMethodInfo]);
            if (runtimeMethodInfo2 != null)
            {
                return runtimeMethodInfo2;
            }
            if (s_methodInstantiationsLock == null)
            {
                Interlocked.CompareExchange(ref s_methodInstantiationsLock, new object(), null);
            }
            bool lockTaken = false;
            try
            {
                Monitor.Enter(s_methodInstantiationsLock, ref lockTaken);
                if (loaderAllocator != null)
                {
                    runtimeMethodInfo2 = loaderAllocator.m_methodInstantiations[runtimeMethodInfo];
                    if (runtimeMethodInfo2 != null)
                    {
                        return runtimeMethodInfo2;
                    }
                    loaderAllocator.m_methodInstantiations[runtimeMethodInfo] = runtimeMethodInfo;
                }
                else
                {
                    runtimeMethodInfo2 = s_methodInstantiations[runtimeMethodInfo];
                    if (runtimeMethodInfo2 != null)
                    {
                        return runtimeMethodInfo2;
                    }
                    s_methodInstantiations[runtimeMethodInfo] = runtimeMethodInfo;
                }
            }
            finally
            {
                if (lockTaken)
                {
                    Monitor.Exit(s_methodInstantiationsLock);
                }
            }
            return runtimeMethodInfo;
        }
References System.Threading.Interlocked.CompareExchange(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.RuntimeMethodHandle.GetAttributes(), System.RuntimeMethodHandle.GetDeclaringType(), System.RuntimeMethodHandle.GetLoaderAllocator(), System.RuntimeType.RuntimeTypeCache.s_methodInstantiations, and System.RuntimeType.RuntimeTypeCache.s_methodInstantiationsLock.