Terraria: System.Array.SorterGenericArray.PickPivotAndPartition
PickPivotAndPartition()
int System.Array.SorterGenericArray.PickPivotAndPartition (int lo, int hi) inline private
Definition at line 331 of file Array.cs.
        {
            int num = lo + (hi - lo) / 2;
            SwapIfGreater(lo, num);
            SwapIfGreater(lo, hi);
            SwapIfGreater(num, hi);
            object value = keys.GetValue(num);
            Swap(num, hi - 1);
            int num2 = lo;
            int num3 = hi - 1;
            while (num2 < num3)
            {
                while (comparer.Compare(keys.GetValue(++num2), value) < 0)
                {
                }
                while (comparer.Compare(value, keys.GetValue(--num3)) < 0)
                {
                }
                if (num2 >= num3)
                {
                    break;
                }
                Swap(num2, num3);
            }
            if (num2 != hi - 1)
            {
                Swap(num2, hi - 1);
            }
            return num2;
        }
References System.Collections.Generic.IComparer< in T >.Compare(), System.Array.SorterGenericArray.comparer, System.Array.GetValue(), System.Array.SorterGenericArray.keys, System.Array.SorterGenericArray.Swap(), System.Array.SorterGenericArray.SwapIfGreater(), and System.value.
Referenced by System.Array.SorterGenericArray.IntroSort().