Terraria: AmbienceServer.AmbienceServer
AmbienceServer()
AmbienceServer.AmbienceServer () inline
     {
         ResetSpawnTime();
         _spawnConditions[SkyEntityType.BirdsV] = IsSunnyDay;
         _spawnConditions[SkyEntityType.Wyvern] = () => IsSunnyDay() && Main.hardMode;
         _spawnConditions[SkyEntityType.Airship] = () => IsSunnyDay() && Main.IsItAHappyWindyDay;
         _spawnConditions[SkyEntityType.AirBalloon] = () => IsSunnyDay() && !Main.IsItAHappyWindyDay;
         _spawnConditions[SkyEntityType.Eyeball] = () => !Main.dayTime;
         _spawnConditions[SkyEntityType.Butterflies] = () => IsSunnyDay() && !Main.IsItAHappyWindyDay && !NPC.TooWindyForButterflies && NPC.butterflyChance < 6;
         _spawnConditions[SkyEntityType.LostKite] = () => Main.dayTime && !Main.eclipse && Main.IsItAHappyWindyDay;
         _spawnConditions[SkyEntityType.Vulture] = () => IsSunnyDay();
         _spawnConditions[SkyEntityType.Bats] = () => (IsSunset() && IsSunnyDay()) || IsCalmNight();
         _spawnConditions[SkyEntityType.PixiePosse] = () => IsSunnyDay() || IsCalmNight();
         _spawnConditions[SkyEntityType.Seagulls] = () => IsSunnyDay();
         _spawnConditions[SkyEntityType.SlimeBalloons] = () => IsSunnyDay() && Main.IsItAHappyWindyDay;
         _spawnConditions[SkyEntityType.Gastropods] = () => IsCalmNight();
         _spawnConditions[SkyEntityType.Pegasus] = () => IsSunnyDay();
         _spawnConditions[SkyEntityType.EaterOfSouls] = () => IsSunnyDay() || IsCalmNight();
         _spawnConditions[SkyEntityType.Crimera] = () => IsSunnyDay() || IsCalmNight();
         _spawnConditions[SkyEntityType.Hellbats] = () => true;
         _secondarySpawnConditionsPerPlayer[SkyEntityType.Vulture] = (Player player) => player.ZoneDesert;
         _secondarySpawnConditionsPerPlayer[SkyEntityType.PixiePosse] = (Player player) => player.ZoneHallow;
         _secondarySpawnConditionsPerPlayer[SkyEntityType.Seagulls] = (Player player) => player.ZoneBeach;
         _secondarySpawnConditionsPerPlayer[SkyEntityType.Gastropods] = (Player player) => player.ZoneHallow;
         _secondarySpawnConditionsPerPlayer[SkyEntityType.Pegasus] = (Player player) => player.ZoneHallow;
         _secondarySpawnConditionsPerPlayer[SkyEntityType.EaterOfSouls] = (Player player) => player.ZoneCorrupt;
         _secondarySpawnConditionsPerPlayer[SkyEntityType.Crimera] = (Player player) => player.ZoneCrimson;
         _secondarySpawnConditionsPerPlayer[SkyEntityType.Bats] = (Player player) => player.ZoneJungle;
     }
References _secondarySpawnConditionsPerPlayer, _spawnConditions, NPC.butterflyChance, Main.dayTime, Main.eclipse, Main.hardMode, IsCalmNight(), Main.IsItAHappyWindyDay, IsSunnyDay(), IsSunset(), ResetSpawnTime(), NPC.TooWindyForButterflies, Player.ZoneBeach, Player.ZoneCorrupt, Player.ZoneCrimson, Player.ZoneHallow, and Player.ZoneJungle.