Terraria: AmbienceServer.Update
Update()
void AmbienceServer.Update () inline
     {
         SpawnForcedEntities();
         if (_updatesUntilNextAttempt > 0)
         {
             _updatesUntilNextAttempt -= Main.dayRate;
             return;
         }
         ResetSpawnTime();
         IEnumerable<SkyEntityType> source = from pair in _spawnConditions
             where pair.Value()
             select pair.Key;
         if (source.Count((SkyEntityType type) => true) == 0)
         {
             return;
         }
         FindPlayerThatCanSeeBackgroundAmbience(out var player);
         if (player == null)
         {
             return;
         }
         IEnumerable<SkyEntityType> source2 = source.Where((SkyEntityType type) => IsPlayerAtRightHeightForType(type, player) && _secondarySpawnConditionsPerPlayer.ContainsKey(type) && _secondarySpawnConditionsPerPlayer[type](player));
         int num = source2.Count((SkyEntityType type) => true);
         if (num == 0 || Main.rand.Next(5) < 3)
         {
             source2 = source.Where((SkyEntityType type) => IsPlayerAtRightHeightForType(type, player) && (!_secondarySpawnConditionsPerPlayer.ContainsKey(type) || _secondarySpawnConditionsPerPlayer[type](player)));
             num = source2.Count((SkyEntityType type) => true);
         }
         if (num != 0)
         {
             SkyEntityType type2 = source2.ElementAt(Main.rand.Next(num));
             SpawnForPlayer(player, type2);
         }
     }
References _secondarySpawnConditionsPerPlayer, _spawnConditions, _updatesUntilNextAttempt, Main.dayRate, FindPlayerThatCanSeeBackgroundAmbience(), IsPlayerAtRightHeightForType(), UnifiedRandom.Next(), Main.rand, ResetSpawnTime(), SpawnForcedEntities(), and SpawnForPlayer().
Referenced by Main.DoUpdate().