Terraria: MinimapFrame.Update
Update()
void MinimapFrame.Update () inline
     {
         Button buttonUnderMouse = GetButtonUnderMouse();
         _zoomInButton.IsHighlighted = buttonUnderMouse == _zoomInButton;
         _zoomOutButton.IsHighlighted = buttonUnderMouse == _zoomOutButton;
         _resetButton.IsHighlighted = buttonUnderMouse == _resetButton;
         if (buttonUnderMouse == null || Main.LocalPlayer.lastMouseInterface)
         {
             return;
         }
         buttonUnderMouse.IsHighlighted = true;
         if (PlayerInput.IgnoreMouseInterface)
         {
             return;
         }
         Main.LocalPlayer.mouseInterface = true;
         if (Main.mouseLeft)
         {
             buttonUnderMouse.Click();
             if (Main.mouseLeftRelease)
             {
                 SoundEngine.PlaySound(12);
             }
         }
     }
References _resetButton, _zoomInButton, _zoomOutButton, MinimapFrame.Button.Click(), GetButtonUnderMouse(), PlayerInput.IgnoreMouseInterface, MinimapFrame.Button.IsHighlighted, Player.lastMouseInterface, Main.LocalPlayer, Player.mouseInterface, Main.mouseLeft, Main.mouseLeftRelease, and SoundEngine.PlaySound().