Terraria: System.Diagnostics.Tracing.NullableTypeInfo.WriteData
WriteData()
override void System.Diagnostics.Tracing.NullableTypeInfo.WriteData (PropertyValue value) inline
Definition at line 27 of file NullableTypeInfo.cs.
    {
        object referenceValue = value.ReferenceValue;
        bool flag = referenceValue != null;
        TraceLoggingDataCollector.AddScalar(flag);
        PropertyValue value2 = valueInfo.PropertyValueFactory(flag ? referenceValue : RuntimeHelpers.GetUninitializedObject(valueInfo.DataType));
        valueInfo.WriteData(value2);
    }
References System.Diagnostics.Tracing.TraceLoggingDataCollector.AddScalar(), System.Diagnostics.Tracing.TraceLoggingTypeInfo.DataType, System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(), System.Diagnostics.Tracing.TraceLoggingTypeInfo.PropertyValueFactory, System.value, System.Diagnostics.Tracing.NullableTypeInfo.valueInfo, and System.Diagnostics.Tracing.TraceLoggingTypeInfo.WriteData().