Terraria: WaterShaderData.StepLiquids
StepLiquids()
void WaterShaderData.StepLiquids () inline private
     {
         _isWaveBufferDirty = true;
         Vector2 vector = (Main.drawToScreen ? Vector2.Zero : new Vector2(Main.offScreenRange, Main.offScreenRange));
         Vector2 vector2 = vector - Main.screenPosition;
         TileBatch tileBatch = Main.tileBatch;
         GraphicsDevice graphicsDevice = Main.instance.GraphicsDevice;
         graphicsDevice.SetRenderTarget(_distortionTarget);
         if (_clearNextFrame)
         {
             graphicsDevice.Clear(new Color(0.5f, 0.5f, 0f, 1f));
             _clearNextFrame = false;
         }
         DrawWaves();
         graphicsDevice.SetRenderTarget(_distortionTargetSwap);
         graphicsDevice.Clear(new Color(0.5f, 0.5f, 0.5f, 1f));
         Main.tileBatch.Begin();
         vector2 *= 0.25f;
         vector2.X = (float)Math.Floor(vector2.X);
         vector2.Y = (float)Math.Floor(vector2.Y);
         Vector2 vector3 = vector2 - _lastDistortionDrawOffset;
         _lastDistortionDrawOffset = vector2;
         tileBatch.Draw(_distortionTarget, new Vector4(vector3.X, vector3.Y, _distortionTarget.Width, _distortionTarget.Height), new VertexColors(Color.White));
         GameShaders.Misc["WaterProcessor"].Apply(new DrawData(_distortionTarget, Vector2.Zero, Color.White));
         tileBatch.End();
         RenderTarget2D distortionTarget = _distortionTarget;
         _distortionTarget = _distortionTargetSwap;
         _distortionTargetSwap = distortionTarget;
         if (_useViscosityFilter)
         {
             LiquidRenderer.Instance.SetWaveMaskData(ref _viscosityMaskChain[_activeViscosityMask]);
             tileBatch.Begin();
             Rectangle cachedDrawArea = LiquidRenderer.Instance.GetCachedDrawArea();
             Rectangle rectangle = new Rectangle(0, 0, cachedDrawArea.Height, cachedDrawArea.Width);
             Vector4 destination = new Vector4(cachedDrawArea.X + cachedDrawArea.Width, cachedDrawArea.Y, cachedDrawArea.Height, cachedDrawArea.Width);
             destination *= 16f;
             destination.X -= vector.X;
             destination.Y -= vector.Y;
             destination *= 0.25f;
             destination.X += vector2.X;
             destination.Y += vector2.Y;
             graphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
             tileBatch.Draw(_viscosityMaskChain[_activeViscosityMask], destination, rectangle, new VertexColors(Color.White), rectangle.Size(), SpriteEffects.FlipHorizontally, -(float)Math.PI / 2f);
             tileBatch.End();
             _activeViscosityMask++;
             _activeViscosityMask %= _viscosityMaskChain.Length;
         }
         graphicsDevice.SetRenderTarget(null);
     }
References _activeViscosityMask, _clearNextFrame, _distortionTarget, _distortionTargetSwap, _isWaveBufferDirty, _lastDistortionDrawOffset, _useViscosityFilter, _viscosityMaskChain, TileBatch.Begin(), Color, TileBatch.Draw(), Main.drawToScreen, DrawWaves(), TileBatch.End(), LiquidRenderer.GetCachedDrawArea(), Game.GraphicsDevice, LiquidRenderer.Instance, Main.instance, GameShaders.Misc, Main.offScreenRange, Main.screenPosition, LiquidRenderer.SetWaveMaskData(), and Main.tileBatch.
Referenced by PreDraw().