Terraria: WaterShaderData.WaterShaderData
WaterShaderData()
WaterShaderData.WaterShaderData (string passName) inline
         : base(passName)
     {
         Main.OnRenderTargetsInitialized += InitRenderTargets;
         Main.OnRenderTargetsReleased += ReleaseRenderTargets;
         _rippleShapeTexture = Main.Assets.Request<Texture2D>("Images/Misc/Ripples", (AssetRequestMode)1);
         Main.OnPreDraw += PreDraw;
     }
References _rippleShapeTexture, Main.Assets, InitRenderTargets(), Main.OnPreDraw, Main.OnRenderTargetsInitialized, Main.OnRenderTargetsReleased, PreDraw(), and ReleaseRenderTargets().