Terraria: WaterShaderData.Apply
Apply()
override void WaterShaderData.Apply () inline virtual
Reimplemented from ShaderData.
     {
         if (_usingRenderTargets && Main.IsGraphicsDeviceAvailable)
         {
             UseProgress(_progress);
             Main.graphics.GraphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
             Vector2 vector = new Vector2(Main.screenWidth, Main.screenHeight) * 0.5f * (Vector2.One - Vector2.One / Main.GameViewMatrix.Zoom);
             Vector2 vector2 = (Main.drawToScreen ? Vector2.Zero : new Vector2(Main.offScreenRange, Main.offScreenRange)) - Main.screenPosition - vector;
             UseImage(_distortionTarget, 1);
             UseImage(Main.waterTarget, 2, SamplerState.PointClamp);
             UseTargetPosition(Main.screenPosition - Main.sceneWaterPos + new Vector2(Main.offScreenRange, Main.offScreenRange) + vector);
             UseImageOffset(-(vector2 * 0.25f - _lastDistortionDrawOffset) / new Vector2(_distortionTarget.Width, _distortionTarget.Height));
             base.Apply();
         }
     }
References _distortionTarget, _lastDistortionDrawOffset, _progress, _usingRenderTargets, Main.drawToScreen, Main.GameViewMatrix, Main.graphics, Main.IsGraphicsDeviceAvailable, Main.offScreenRange, Main.sceneWaterPos, Main.screenHeight, Main.screenPosition, Main.screenWidth, ScreenShaderData.UseImage(), ScreenShaderData.UseImageOffset(), ScreenShaderData.UseProgress(), ScreenShaderData.UseTargetPosition(), Main.waterTarget, and SpriteViewMatrix.Zoom.