Terraria: WaterShaderData.PreDraw
PreDraw()
void WaterShaderData.PreDraw (GameTime gameTime) inline private
     {
         ValidateRenderTargets();
         if (!_usingRenderTargets || !Main.IsGraphicsDeviceAvailable)
         {
             return;
         }
         if (_useProjectileWaves || _useRippleWaves || _useCustomWaves || _usePlayerWaves)
         {
             for (int i = 0; i < Math.Min(_queuedSteps, 2); i++)
             {
                 StepLiquids();
             }
         }
         else if (_isWaveBufferDirty || _clearNextFrame)
         {
             GraphicsDevice graphicsDevice = Main.instance.GraphicsDevice;
             graphicsDevice.SetRenderTarget(_distortionTarget);
             graphicsDevice.Clear(new Color(0.5f, 0.5f, 0f, 1f));
             _clearNextFrame = false;
             _isWaveBufferDirty = false;
             graphicsDevice.SetRenderTarget(null);
         }
         _queuedSteps = 0;
     }
References _clearNextFrame, _distortionTarget, _isWaveBufferDirty, _queuedSteps, _useCustomWaves, _usePlayerWaves, _useProjectileWaves, _useRippleWaves, _usingRenderTargets, Color, Game.GraphicsDevice, Main.instance, Main.IsGraphicsDeviceAvailable, StepLiquids(), and ValidateRenderTargets().
Referenced by WaterShaderData().