Terraria: WaterShaderData.DrawWaves
DrawWaves()
void WaterShaderData.DrawWaves () inline private
     {
         Vector2 screenPosition = Main.screenPosition;
         Vector2 vector = (Main.drawToScreen ? Vector2.Zero : new Vector2(Main.offScreenRange, Main.offScreenRange));
         Vector2 vector2 = -_lastDistortionDrawOffset / 0.25f + vector;
         TileBatch tileBatch = Main.tileBatch;
         _ = Main.instance.GraphicsDevice;
         Vector2 dimensions = new Vector2(Main.screenWidth, Main.screenHeight);
         Vector2 vector3 = new Vector2(16f, 16f);
         tileBatch.Begin();
         GameShaders.Misc["WaterDistortionObject"].Apply();
         if (_useNPCWaves)
         {
             for (int i = 0; i < 200; i++)
             {
                 if (Main.npc[i] == null || !Main.npc[i].active || (!Main.npc[i].wet && Main.npc[i].wetCount == 0) || !Collision.CheckAABBvAABBCollision(screenPosition, dimensions, Main.npc[i].position - vector3, Main.npc[i].Size + vector3))
                 {
                     continue;
                 }
                 NPC nPC = Main.npc[i];
                 Vector2 vector4 = nPC.Center - vector2;
                 Vector2 vector5 = nPC.velocity.RotatedBy(0f - nPC.rotation) / new Vector2(nPC.height, nPC.width);
                 float num = vector5.LengthSquared();
                 num = num * 0.3f + 0.7f * num * (1024f / (float)(nPC.height * nPC.width));
                 num = Math.Min(num, 0.08f);
                 num += (nPC.velocity - nPC.oldVelocity).Length() * 0.5f;
                 vector5.Normalize();
                 Vector2 velocity = nPC.velocity;
                 velocity.Normalize();
                 vector4 -= velocity * 10f;
                 if (!_useViscosityFilter && (nPC.honeyWet || nPC.lavaWet))
                 {
                     num *= 0.3f;
                 }
                 if (nPC.wet)
                 {
                     tileBatch.Draw(TextureAssets.MagicPixel.Value, new Vector4(vector4.X, vector4.Y, (float)nPC.width * 2f, (float)nPC.height * 2f) * 0.25f, null, new VertexColors(new Color(vector5.X * 0.5f + 0.5f, vector5.Y * 0.5f + 0.5f, 0.5f * num)), new Vector2((float)TextureAssets.MagicPixel.Width() / 2f, (float)TextureAssets.MagicPixel.Height() / 2f), SpriteEffects.None, nPC.rotation);
                 }
                 if (nPC.wetCount != 0)
                 {
                     num = nPC.velocity.Length();
                     num = 0.195f * (float)Math.Sqrt(num);
                     float num2 = 5f;
                     if (!nPC.wet)
                     {
                         num2 = -20f;
                     }
                     QueueRipple(nPC.Center + velocity * num2, new Color(0.5f, (nPC.wet ? num : (0f - num)) * 0.5f + 0.5f, 0f, 1f) * 0.5f, new Vector2(nPC.width, (float)nPC.height * ((float)(int)nPC.wetCount / 9f)) * MathHelper.Clamp(num * 10f, 0f, 1f), RippleShape.Circle);
                 }
             }
         }
         if (_usePlayerWaves)
         {
             for (int j = 0; j < 255; j++)
             {
                 if (Main.player[j] == null || !Main.player[j].active || (!Main.player[j].wet && Main.player[j].wetCount == 0) || !Collision.CheckAABBvAABBCollision(screenPosition, dimensions, Main.player[j].position - vector3, Main.player[j].Size + vector3))
                 {
                     continue;
                 }
                 Player player = Main.player[j];
                 Vector2 vector6 = player.Center - vector2;
                 float num3 = player.velocity.Length();
                 num3 = 0.05f * (float)Math.Sqrt(num3);
                 Vector2 velocity2 = player.velocity;
                 velocity2.Normalize();
                 vector6 -= velocity2 * 10f;
                 if (!_useViscosityFilter && (player.honeyWet || player.lavaWet))
                 {
                     num3 *= 0.3f;
                 }
                 if (player.wet)
                 {
                     tileBatch.Draw(TextureAssets.MagicPixel.Value, new Vector4(vector6.X - (float)player.width * 2f * 0.5f, vector6.Y - (float)player.height * 2f * 0.5f, (float)player.width * 2f, (float)player.height * 2f) * 0.25f, new VertexColors(new Color(velocity2.X * 0.5f + 0.5f, velocity2.Y * 0.5f + 0.5f, 0.5f * num3)));
                 }
                 if (player.wetCount != 0)
                 {
                     float num4 = 5f;
                     if (!player.wet)
                     {
                         num4 = -20f;
                     }
                     num3 *= 3f;
                     QueueRipple(player.Center + velocity2 * num4, player.wet ? num3 : (0f - num3), new Vector2(player.width, (float)player.height * ((float)(int)player.wetCount / 9f)) * MathHelper.Clamp(num3 * 10f, 0f, 1f), RippleShape.Circle);
                 }
             }
         }
         if (_useProjectileWaves)
         {
             for (int k = 0; k < 1000; k++)
             {
                 Projectile projectile = Main.projectile[k];
                 if (projectile.wet && !projectile.lavaWet)
                 {
                     _ = !projectile.honeyWet;
                 }
                 else
                     _ = 0;
                 bool flag = projectile.lavaWet;
                 bool flag2 = projectile.honeyWet;
                 bool flag3 = projectile.wet;
                 if (projectile.ignoreWater)
                 {
                     flag3 = true;
                 }
                 if (!(projectile != null && projectile.active && ProjectileID.Sets.CanDistortWater[projectile.type] && flag3) || ProjectileID.Sets.NoLiquidDistortion[projectile.type] || !Collision.CheckAABBvAABBCollision(screenPosition, dimensions, projectile.position - vector3, projectile.Size + vector3))
                 {
                     continue;
                 }
                 if (projectile.ignoreWater)
                 {
                     bool num5 = Collision.LavaCollision(projectile.position, projectile.width, projectile.height);
                     flag = Collision.WetCollision(projectile.position, projectile.width, projectile.height);
                     flag2 = Collision.honey;
                     if (!(num5 || flag || flag2))
                     {
                         continue;
                     }
                 }
                 Vector2 vector7 = projectile.Center - vector2;
                 float num6 = projectile.velocity.Length();
                 num6 = 2f * (float)Math.Sqrt(0.05f * num6);
                 Vector2 velocity3 = projectile.velocity;
                 velocity3.Normalize();
                 if (!_useViscosityFilter && (flag2 || flag))
                 {
                     num6 *= 0.3f;
                 }
                 float num7 = Math.Max(12f, (float)projectile.width * 0.75f);
                 float num8 = Math.Max(12f, (float)projectile.height * 0.75f);
                 tileBatch.Draw(TextureAssets.MagicPixel.Value, new Vector4(vector7.X - num7 * 0.5f, vector7.Y - num8 * 0.5f, num7, num8) * 0.25f, new VertexColors(new Color(velocity3.X * 0.5f + 0.5f, velocity3.Y * 0.5f + 0.5f, num6 * 0.5f)));
             }
         }
         tileBatch.End();
         if (_useRippleWaves)
         {
             tileBatch.Begin();
             for (int l = 0; l < _rippleQueueCount; l++)
             {
                 Vector2 vector8 = _rippleQueue[l].Position - vector2;
                 Vector2 size = _rippleQueue[l].Size;
                 Rectangle sourceRectangle = _rippleQueue[l].SourceRectangle;
                 Texture2D value = _rippleShapeTexture.Value;
                 tileBatch.Draw(value, new Vector4(vector8.X, vector8.Y, size.X, size.Y) * 0.25f, sourceRectangle, new VertexColors(_rippleQueue[l].WaveData), new Vector2(sourceRectangle.Width / 2, sourceRectangle.Height / 2), SpriteEffects.None, _rippleQueue[l].Rotation);
             }
             tileBatch.End();
         }
         _rippleQueueCount = 0;
         if (_useCustomWaves && this.OnWaveDraw != null)
         {
             tileBatch.Begin();
             this.OnWaveDraw(tileBatch);
             tileBatch.End();
         }
     }
References _lastDistortionDrawOffset, _rippleQueue, _rippleQueueCount, _rippleShapeTexture, _useCustomWaves, _useNPCWaves, _usePlayerWaves, _useProjectileWaves, _useRippleWaves, _useViscosityFilter, Entity.active, TileBatch.Begin(), ProjectileID.Sets.CanDistortWater, Entity.Center, Collision.CheckAABBvAABBCollision(), Color, TileBatch.Draw(), Main.drawToScreen, TileBatch.End(), Game.GraphicsDevice, Entity.height, Collision.honey, Entity.honeyWet, Projectile.ignoreWater, Main.instance, Collision.LavaCollision(), Entity.lavaWet, TextureAssets.MagicPixel, GameShaders.Misc, ProjectileID.Sets.NoLiquidDistortion, Main.npc, Main.offScreenRange, Entity.oldVelocity, OnWaveDraw, Main.player, WaterShaderData.Ripple.Position, Entity.position, Main.projectile, QueueRipple(), WaterShaderData.Ripple.Rotation, NPC.rotation, Main.screenHeight, Main.screenPosition, Main.screenWidth, WaterShaderData.Ripple.Size, Entity.Size, WaterShaderData.Ripple.SourceRectangle, Main.tileBatch, Projectile.type, Asset< T >.Value, Entity.velocity, Entity.wet, Collision.WetCollision(), Entity.wetCount, and Entity.width.
Referenced by StepLiquids().