Terraria: Mount.MountDelegatesData.MountDelegatesData
MountDelegatesData()
Mount.MountDelegatesData.MountDelegatesData () inline
         {
             MinecartDust = DelegateMethods.Minecart.Sparks;
             MinecartJumpingSound = DelegateMethods.Minecart.JumpingSound;
             MinecartLandingSound = DelegateMethods.Minecart.LandingSound;
             MinecartBumperSound = DelegateMethods.Minecart.BumperSound;
         }
References DelegateMethods.Minecart.BumperSound(), DelegateMethods.Minecart.JumpingSound(), DelegateMethods.Minecart.LandingSound(), Mount.MountDelegatesData.MinecartBumperSound, Mount.MountDelegatesData.MinecartDust, Mount.MountDelegatesData.MinecartJumpingSound, Mount.MountDelegatesData.MinecartLandingSound, and DelegateMethods.Minecart.Sparks().