Terraria: WaterShaderData.ValidateRenderTargets
ValidateRenderTargets()
void WaterShaderData.ValidateRenderTargets () inline private
     {
         int backBufferWidth = Main.instance.GraphicsDevice.PresentationParameters.BackBufferWidth;
         int backBufferHeight = Main.instance.GraphicsDevice.PresentationParameters.BackBufferHeight;
         bool flag = !Main.drawToScreen;
         if (_usingRenderTargets && !flag)
         {
             ReleaseRenderTargets();
         }
         else if (!_usingRenderTargets && flag)
         {
             InitRenderTargets(backBufferWidth, backBufferHeight);
         }
         else if (_usingRenderTargets && flag && (_distortionTarget.IsContentLost || _distortionTargetSwap.IsContentLost))
         {
             _clearNextFrame = true;
         }
     }
References _clearNextFrame, _distortionTarget, _distortionTargetSwap, _usingRenderTargets, Main.drawToScreen, Game.GraphicsDevice, InitRenderTargets(), Main.instance, and ReleaseRenderTargets().
Referenced by PreDraw().