Terraria: System.Net.Mail.MailAddressParser.TryNormalizeOrThrow
TryNormalizeOrThrow()
static bool System.Net.Mail.MailAddressParser.TryNormalizeOrThrow (string input, [NotNullWhen(true)] out string normalizedString, bool throwExceptionIfFail) inline static package
Definition at line 239 of file MailAddressParser.cs.
    {
        try
        {
            normalizedString = input.Normalize(NormalizationForm.FormC);
            return true;
        }
        catch (ArgumentException innerException)
        {
            if (throwExceptionIfFail)
            {
                throw new FormatException(System.SR.MailAddressInvalidFormat, innerException);
            }
            normalizedString = null;
            return false;
        }
    }
References System.input, and System.SR.MailAddressInvalidFormat.
Referenced by System.Net.Mail.MailAddress.TryParse(), System.Net.Mail.MailAddressParser.TryParseDisplayName(), System.Net.Mail.MailAddressParser.TryParseDomain(), and System.Net.Mail.MailAddressParser.TryParseLocalPart().