Terraria: System.Threading.Tasks.Dataflow.Internal.TargetRegistry.Remove
Remove()
void System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.Remove (ITargetBlock< T > target, bool onlyIfReachedMaxMessages = false) inline package
Definition at line 173 of file TargetRegistry.cs.
    {
        if (!onlyIfReachedMaxMessages || _linksWithRemainingMessages != 0)
        {
            Remove_Slow(target, onlyIfReachedMaxMessages);
        }
    }
References System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >._linksWithRemainingMessages, and System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.Remove_Slow().
Referenced by System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.ConsumeMessage(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.ConsumeMessage(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferCurrentMessageToNewTarget(), System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.OfferMessageToTarget(), and System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.OfferMessageToTarget().