Terraria: System.Threading.Tasks.Dataflow.Internal.TargetRegistry.ClearEntryPoints
ClearEntryPoints()
LinkedTargetInfo System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >.ClearEntryPoints () inline package
Definition at line 207 of file TargetRegistry.cs.
    {
        LinkedTargetInfo firstTarget = _firstTarget;
        _firstTarget = (_lastTarget = null);
        _targetInformation.Clear();
        _linksWithRemainingMessages = 0;
        return firstTarget;
    }
References System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >._firstTarget, System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >._lastTarget, System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >._linksWithRemainingMessages, System.Threading.Tasks.Dataflow.Internal.TargetRegistry< T >._targetInformation, and System.Collections.Generic.Dictionary< TKey, TValue >.Clear().
Referenced by System.Threading.Tasks.Dataflow.Internal.SourceCore< TOutput >.CompleteBlockOncePossible(), and System.Threading.Tasks.Dataflow.BroadcastBlock< T >.BroadcastingSourceCore< TOutput >.CompleteBlockOncePossible().