Terraria: AssetRepository.ThrowIfDisposed
ThrowIfDisposed()
void AssetRepository.ThrowIfDisposed () inline private
     {
         if (_isDisposed)
         {
             throw new ObjectDisposedException("AssetRepository is disposed.");
         }
     }
References _isDisposed.
Referenced by Request< T >(), SetSources(), and TransferCompletedAssets().