Terraria: Terraria.GameContent.Biomes.DunesBiome.PlaceSingle
PlaceSingle()
void Terraria.GameContent.Biomes.DunesBiome.PlaceSingle (DunesDescription description, StructureMap structures) inline private
Definition at line 66 of file DunesBiome.cs.
    {
        int num = GenBase._random.Next(3) + 8;
        for (int i = 0; i < num - 1; i++)
        {
            int num2 = (int)(2.0 / (double)num * (double)description.Area.Width);
            int num3 = (int)((double)i / (double)num * (double)description.Area.Width + (double)description.Area.Left) + num2 * 2 / 5;
            num3 += GenBase._random.Next(-5, 6);
            double num4 = (double)i / (double)(num - 2);
            double num5 = 1.0 - Math.Abs(num4 - 0.5) * 2.0;
            PlaceHill(num3 - num2 / 2, num3 + num2 / 2, (num5 * 0.3 + 0.2) * _heightScale, description);
        }
        int num6 = GenBase._random.Next(2) + 1;
        for (int j = 0; j < num6; j++)
        {
            int num7 = description.Area.Width / 2;
            int x = description.Area.Center.X;
            x += GenBase._random.Next(-10, 11);
            PlaceHill(x - num7 / 2, x + num7 / 2, 0.8 * _heightScale, description);
        }
        structures.AddStructure(description.Area, 20);
    }
References Terraria.GameContent.Biomes.DunesBiome._heightScale, Terraria.WorldBuilding.GenBase._random, System.Math.Abs(), Terraria.WorldBuilding.StructureMap.AddStructure(), Terraria.GameContent.Biomes.DunesBiome.DunesDescription.Area, Microsoft.Xna.Framework.Rectangle.Center, Microsoft.Xna.Framework.Rectangle.Left, Terraria.GameContent.Biomes.DunesBiome.PlaceHill(), Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Point.X.
Referenced by Terraria.GameContent.Biomes.DunesBiome.Place().