Terraria: Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine
PlaceCurvedLine()
static void Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine (Point startPoint, Point endPoint, Point anchorOffset, DunesDescription description) inline static private
Definition at line 110 of file DunesBiome.cs.
    {
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        Point p = new Point((startPoint.X + endPoint.X) / 2, (startPoint.Y + endPoint.Y) / 2);
        p.X += anchorOffset.X;
        p.Y += anchorOffset.Y;
        Vector2D val = startPoint.ToVector2D();
        Vector2D val2 = endPoint.ToVector2D();
        Vector2D val3 = p.ToVector2D();
        double num = 0.5 / (val2.X - val.X);
        Point point = new Point(-1, -1);
        for (double num2 = 0.0; num2 <= 1.0; num2 += num)
        {
            Vector2D val4 = Vector2D.Lerp(val, val3, num2);
            Vector2D val5 = Vector2D.Lerp(val3, val2, num2);
            Point point2 = Vector2D.Lerp(val4, val5, num2).ToPoint();
            if (point2 == point)
            {
                continue;
            }
            point = point2;
            int num3 = description.Area.Width / 2 - Math.Abs(point2.X - description.Area.Center.X);
            int num4 = description.Surface[point2.X] + (int)(Math.Sqrt(num3) * 3.0);
            for (int i = point2.Y - 10; i < point2.Y; i++)
            {
                if (GenBase._tiles[point2.X, i].active() && GenBase._tiles[point2.X, i].type != 53)
                {
                    GenBase._tiles[point2.X, i].ClearEverything();
                }
            }
            for (int j = point2.Y; j < num4; j++)
            {
                GenBase._tiles[point2.X, j].ResetToType(53);
                Tile.SmoothSlope(point2.X, j);
            }
        }
    }
References Terraria.WorldBuilding.GenBase._tiles, System.Math.Abs(), Terraria.GameContent.Biomes.DunesBiome.DunesDescription.Area, Microsoft.Xna.Framework.Rectangle.Center, ReLogic.Utilities.Vector2D.Lerp(), Terraria.Tile.SmoothSlope(), System.Math.Sqrt(), Terraria.GameContent.Biomes.DunesBiome.DunesDescription.Surface, Microsoft.Xna.Framework.Point.X, ReLogic.Utilities.Vector2D.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.DunesBiome.PlaceHill().