Terraria: Terraria.GameContent.Biomes.DunesBiome.Place
Place()
override bool Terraria.GameContent.Biomes.DunesBiome.Place (Point origin, StructureMap structures) inline
Definition at line 53 of file DunesBiome.cs.
    {
        int height = (int)((double)GenBase._random.Next(60, 100) * _heightScale);
        int height2 = (int)((double)GenBase._random.Next(60, 100) * _heightScale);
        int random = _singleDunesWidth.GetRandom(GenBase._random);
        int random2 = _singleDunesWidth.GetRandom(GenBase._random);
        DunesDescription description = DunesDescription.CreateFromPlacement(new Point(origin.X - random / 2 + 30, origin.Y), random, height);
        DunesDescription description2 = DunesDescription.CreateFromPlacement(new Point(origin.X + random2 / 2 - 30, origin.Y), random2, height2);
        PlaceSingle(description, structures);
        PlaceSingle(description2, structures);
        return true;
    }
References Terraria.GameContent.Biomes.DunesBiome._heightScale, Terraria.WorldBuilding.GenBase._random, Terraria.GameContent.Biomes.DunesBiome._singleDunesWidth, Terraria.GameContent.Biomes.DunesBiome.DunesDescription.CreateFromPlacement(), Terraria.WorldBuilding.WorldGenRange.GetRandom(), Terraria.GameContent.Biomes.DunesBiome.PlaceSingle(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.