Terraria: UIGamepadHelper.CreateUILinkPointGrid
CreateUILinkPointGrid()
UILinkPoint [,] UIGamepadHelper.CreateUILinkPointGrid (ref int currentID, List< SnapPoint > pointsForGrid, int pointsPerLine, UILinkPoint topLinkPoint, UILinkPoint leftLinkPoint, UILinkPoint rightLinkPoint, UILinkPoint bottomLinkPoint) inline
     {
         int num = (int)Math.Ceiling((float)pointsForGrid.Count / (float)pointsPerLine);
         UILinkPoint[,] array = new UILinkPoint[pointsPerLine, num];
         for (int i = 0; i < pointsForGrid.Count; i++)
         {
             int num2 = i % pointsPerLine;
             int num3 = i / pointsPerLine;
             array[num2, num3] = MakeLinkPointFromSnapPoint(currentID++, pointsForGrid[i]);
         }
         for (int j = 0; j < array.GetLength(0); j++)
         {
             for (int k = 0; k < array.GetLength(1); k++)
             {
                 UILinkPoint uILinkPoint = array[j, k];
                 if (uILinkPoint == null)
                 {
                     continue;
                 }
                 if (j < array.GetLength(0) - 1)
                 {
                     UILinkPoint uILinkPoint2 = array[j + 1, k];
                     if (uILinkPoint2 != null)
                     {
                         PairLeftRight(uILinkPoint, uILinkPoint2);
                     }
                 }
                 if (k < array.GetLength(1) - 1)
                 {
                     UILinkPoint uILinkPoint3 = array[j, k + 1];
                     if (uILinkPoint3 != null)
                     {
                         PairUpDown(uILinkPoint, uILinkPoint3);
                     }
                 }
                 if (leftLinkPoint != null && j == 0)
                 {
                     uILinkPoint.Left = leftLinkPoint.ID;
                 }
                 if (topLinkPoint != null && k == 0)
                 {
                     uILinkPoint.Up = topLinkPoint.ID;
                 }
                 if (rightLinkPoint != null && j == pointsPerLine - 1)
                 {
                     uILinkPoint.Right = rightLinkPoint.ID;
                 }
                 if (bottomLinkPoint != null && k == num - 1)
                 {
                     uILinkPoint.Down = bottomLinkPoint.ID;
                 }
             }
         }
         return array;
     }
References UILinkPoint.Down, UILinkPoint.ID, UILinkPoint.Left, MakeLinkPointFromSnapPoint(), PairLeftRight(), PairUpDown(), UILinkPoint.Right, and UILinkPoint.Up.
Referenced by AWorkshopPublishInfoState< TPublishedObjectType >.SetupGamepadPoints(), and UICreativePowersMenu.SetupGamepadPoints().