Terraria: System.ReadOnlySpan.ToArray
ToArray()
T[] System.ReadOnlySpan< T >.ToArray () inline
Definition at line 251 of file ReadOnlySpan.cs.
    {
        if (_length == 0)
        {
            return Array.Empty<T>();
        }
        T[] array = new T[_length];
        Buffer.Memmove(ref MemoryMarshal.GetArrayDataReference(array), ref _pointer.Value, (uint)_length);
        return array;
    }
References System.ReadOnlySpan< T >._length, System.ReadOnlySpan< T >._pointer, System.array, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), and System.Buffer.Memmove().
Referenced by System.SpanDebugView< T >.SpanDebugView(), Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertSignatureToIeeeP1363(), System.Security.Principal.SecurityIdentifier.CreateFromParts(), System.Security.Cryptography.DSA.CreateSignatureCore(), System.Security.Cryptography.PasswordBasedEncryption.Encrypt(), System.Enum.GetNames< TEnum >(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), System.Security.Cryptography.AsnEncodedData.Reset(), System.Security.Cryptography.KeyBlobHelpers.ToUnsignedIntegerBytes(), System.Security.Cryptography.DSA.TryCreateSignatureCore(), System.Security.Cryptography.RSA.TryDecrypt(), Internal.Cryptography.AesImplementation.TryDecryptCbcCore(), Internal.Cryptography.DesImplementation.TryDecryptCbcCore(), Internal.Cryptography.RC2Implementation.TryDecryptCbcCore(), Internal.Cryptography.TripleDesImplementation.TryDecryptCbcCore(), System.Security.Cryptography.AesCng.TryDecryptCbcCore(), System.Security.Cryptography.TripleDESCng.TryDecryptCbcCore(), Internal.Cryptography.AesImplementation.TryDecryptCfbCore(), Internal.Cryptography.DesImplementation.TryDecryptCfbCore(), Internal.Cryptography.TripleDesImplementation.TryDecryptCfbCore(), System.Security.Cryptography.AesCng.TryDecryptCfbCore(), System.Security.Cryptography.TripleDESCng.TryDecryptCfbCore(), System.Security.Cryptography.RSA.TryEncrypt(), Internal.Cryptography.AesImplementation.TryEncryptCbcCore(), Internal.Cryptography.DesImplementation.TryEncryptCbcCore(), Internal.Cryptography.RC2Implementation.TryEncryptCbcCore(), Internal.Cryptography.TripleDesImplementation.TryEncryptCbcCore(), System.Security.Cryptography.AesCng.TryEncryptCbcCore(), System.Security.Cryptography.TripleDESCng.TryEncryptCbcCore(), Internal.Cryptography.AesImplementation.TryEncryptCfbCore(), Internal.Cryptography.DesImplementation.TryEncryptCfbCore(), Internal.Cryptography.TripleDesImplementation.TryEncryptCfbCore(), System.Security.Cryptography.AesCng.TryEncryptCfbCore(), System.Security.Cryptography.TripleDESCng.TryEncryptCfbCore(), System.Security.Cryptography.RSA.TrySignHash(), System.Security.Cryptography.ECDsa.TrySignHashCore(), System.UriHelper.UnescapeString(), System.Security.Cryptography.ECDsa.VerifyDataCore(), System.Security.Cryptography.RSA.VerifyHash(), System.Security.Cryptography.ECDsa.VerifyHashCore(), and System.Security.Cryptography.DSA.VerifySignature().