Terraria: System.ReadOnlySpan.Slice
Slice() [1/2]
ReadOnlySpan< T > System.ReadOnlySpan< T >.Slice (int start) inline
Definition at line 232 of file ReadOnlySpan.cs.
    {
        if ((uint)start > (uint)_length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException();
        }
        return new ReadOnlySpan<T>(ref Unsafe.Add(ref _pointer.Value, (nint)(uint)start), _length - start);
    }
References System.ReadOnlySpan< T >._length, System.ReadOnlySpan< T >._pointer, System.start, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Diagnostics.ActivityTraceId.ActivityTraceId(), System.Security.Cryptography.DSAImplementation.DSACng.AdjustHashSizeIfNecessary(), System.Security.Cryptography.DSACng.AdjustHashSizeIfNecessary(), System.Text.Json.Utf8JsonReader.CheckLiteralMultiSegment(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.CircularCopyUtf16BE(), System.Text.Json.Utf8JsonReader.ConsumeComment(), System.Text.Json.Utf8JsonReader.ConsumeLiteral(), System.Text.Json.Utf8JsonReader.ConsumeLiteralMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeMultiLineComment(), System.Text.Json.Utf8JsonReader.ConsumeNumber(), System.Text.Json.Utf8JsonReader.ConsumeNumberMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeSingleLineComment(), System.Text.Json.Utf8JsonReader.ConsumeString(), System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(), System.Text.Json.Utf8JsonReader.ConsumeStringAndValidateMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringMultiSegment(), Internal.Cryptography.AsymmetricAlgorithmHelpers.ConvertDerToIeee1363(), System.StubHelpers.FixedWSTRMarshaler.ConvertToNative(), Internal.Cryptography.AsymmetricAlgorithmHelpers.CopySignatureField(), System.Net.Http.HPack.HPackDecoder.DecodeInternal(), System.Diagnostics.Tracing.EventPipePayloadDecoder.DecodePayload(), System.Net.WebSockets.Compression.WebSocketDeflater.Deflate(), System.Text.Encodings.Web.TextEncoder.Encode(), System.Text.Encodings.Web.TextEncoder.EncodeToNewString(), System.Text.Encodings.Web.TextEncoder.EncodeUtf8(), System.Text.Encodings.Web.TextEncoder.EncodeUtf8Core(), System.Text.Json.Utf8JsonReader.EndArray(), System.Text.Json.Utf8JsonReader.EndObject(), System.UriHelper.EscapeString(), System.Type.FilterNameImpl(), System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(), System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), System.Security.Cryptography.EccKeyFormatHelper.FromECPrivateKey(), System.Security.Cryptography.EccKeyFormatHelper.FromECPublicKey(), System.IO.Path.GetDirectoryName(), System.Environment.GetEnvironmentVariables(), System.IO.Path.GetExtension(), System.IO.Path.GetFileName(), System.IO.Path.GetFileNameWithoutExtension(), System.Buffers.ReadOnlySequence< T >.GetFirstSpan(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode(), Interop.Advapi32.PERF_INSTANCE_DEFINITION.GetName(), System.Globalization.TimeSpanParse.TimeSpanTokenizer.GetNextToken(), System.IO.Path.GetPathRoot(), System.Net.Security.TlsFrameHelper.GetSniFromHostNameStruct(), System.Net.Security.TlsFrameHelper.GetSniFromServerName(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), System.Security.Cryptography.EccKeyFormatHelper.GetSpecifiedECCurveCore(), System.IO.Path.GetUncRootLength(), System.Text.Json.JsonReaderHelper.GetUnescapedSpan(), System.IO.Path.GetVolumeName(), Internal.Cryptography.PemKeyImportHelpers.ImportEncryptedPem< TPass >(), Internal.Cryptography.PemKeyImportHelpers.ImportPem(), System.Security.Cryptography.CngPkcs8.ImportPkcs8PrivateKey(), System.Text.DecoderFallbackBuffer.InternalFallbackGetCharCount(), System.Buffers.SequenceReader< T >.IsNextSlow(), System.Globalization.GlobalizationMode.LoadAppLocalIcuCore(), System.__DTString.Match(), System.IO.Enumeration.FileSystemName.MatchPattern(), System.__DTString.MatchSpecifiedWord(), System.__DTString.MatchSpecifiedWords(), System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext(), System.Text.SpanLineEnumerator.MoveNext(), System.Text.SpanRuneEnumerator.MoveNext(), System.Numerics.BigNumber.NumberToBigInteger(), System.IPv6AddressHelper.Parse(), System.Net.Http.HPack.HPackDecoder.ParseHeaderName(), System.Net.Http.HPack.HPackDecoder.ParseHeaderValue(), System.Formats.Asn1.AsnValueReader.PeekEncodedValue(), System.Net.Security.SslStream.ProcessBlob(), System.Net.Http.HPack.HPackDecoder.ProcessHeaderValue(), System.IO.StreamReader.ReadAsyncInternal(), System.Formats.Asn1.AsnValueReader.ReadBitString(), System.Formats.Asn1.AsnValueReader.ReadBoolean(), System.IO.ReadOnlyMemoryStream.ReadBuffer(), System.Formats.Asn1.AsnValueReader.ReadEncodedValue(), System.Text.Json.Utf8JsonReader.ReadFirstToken(), System.Text.Json.Utf8JsonReader.ReadFirstTokenMultiSegment(), System.Formats.Asn1.AsnValueReader.ReadGeneralizedTime(), System.Formats.Asn1.AsnValueReader.ReadInteger(), System.Formats.Asn1.AsnValueReader.ReadIntegerBytes(), System.Formats.Asn1.AsnValueReader.ReadObjectIdentifier(), System.Formats.Asn1.AsnValueReader.ReadOctetString(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.Formats.Asn1.AsnValueReader.ReadSetOf(), System.Formats.Asn1.AsnValueReader.ReadUtcTime(), System.__DTString.RemoveLeadingInQuoteSpaces(), System.IO.PathInternal.RemoveRelativeSegments(), System.__DTString.RemoveTrailingInQuoteSpaces(), System.Text.Json.Utf8JsonReader.SkipComment(), System.Text.Json.Utf8JsonReader.SkipCommentMultiSegment(), System.Text.Json.Utf8JsonReader.StartArray(), System.Text.Json.Utf8JsonReader.StartObject(), System.Globalization.InvariantModeCasing.ToLower(), System.IO.Enumeration.FileSystemEntry.ToSpecifiedFullPath(), System.Security.Cryptography.KeyBlobHelpers.ToUnsignedIntegerBytes(), System.Security.Cryptography.KeyBlobHelpers.ToUnsignedIntegerBytes(), System.Globalization.InvariantModeCasing.ToUpper(), System.IO.PathInternal.TrimEndingDirectorySeparator(), System.__DTString.TrimTail(), System.Buffers.SequenceReader< T >.TryCopyMultisegment(), System.Buffers.SequenceReader< T >.TryCopyTo(), System.Net.Security.TlsFrameHelper.TryGetApplicationProtocolsFromExtension(), System.Net.Security.TlsFrameHelper.TryGetFrameInfo(), System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), System.Text.Json.Utf8JsonReader.TryGetNumber(), System.Text.Json.Utf8JsonReader.TryGetNumberMultiSegment(), System.Net.Security.TlsFrameHelper.TryGetSniFromServerNameList(), System.Net.Security.TlsFrameHelper.TryGetSupportedVersionsFromExtension(), System.Text.DecoderFallbackBuffer.TryInternalFallbackGetChars(), System.Enum.TryParseByName(), System.Number.TryParseDouble(), System.Guid.TryParseExactB(), System.Guid.TryParseExactD(), System.Guid.TryParseExactP(), System.Guid.TryParseExactX(), System.Number.TryParseHalf(), System.Net.Security.TlsFrameHelper.TryParseHelloExtensions(), System.Net.Security.TlsFrameHelper.TryParseHelloFrame(), System.Guid.TryParseHex(), System.Net.Http.MultiProxy.TryParseProxyConfigPart(), System.Number.TryParseSingle(), System.Formats.Asn1.AsnValueReader.TryReadInt32(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveBitString(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveOctetString(), System.Net.Http.Headers.AltSvcHeaderParser.TryReadQuotedAltAuthority(), System.Buffers.SequenceReader< T >.TryReadTo(), System.Buffers.SequenceReader< T >.TryReadTo(), System.Buffers.SequenceReader< T >.TryReadTo(), System.Buffers.SequenceReader< T >.TryReadToAny(), System.Security.Cryptography.PemEncoding.TryWrite(), Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformBlock(), System.IO.StreamWriter.WriteAsyncInternal(), System.Security.Cryptography.KeyBlobHelpers.WriteKeyParameterInteger(), System.Buffers.BuffersExtensions.WriteMultiSegment< T >(), System.Text.Json.Utf8JsonWriter.WriteNullSection(), and System.Text.Json.Utf8JsonWriter.WritePropertyNameSection().