Terraria: System.ReadOnlySpan.CopyTo
CopyTo()
void System.ReadOnlySpan< T >.CopyTo (Span< T > destination) inline
Definition at line 190 of file ReadOnlySpan.cs.
    {
        if ((uint)_length <= (uint)destination.Length)
        {
            Buffer.Memmove<T>(ref destination._pointer.Value, ref _pointer.Value, (uint)_length);
        }
        else
        {
            ThrowHelper.ThrowArgumentException_DestinationTooShort();
        }
    }
References System.ReadOnlySpan< T >._length, System.ReadOnlySpan< T >._pointer, System.destination, System.Buffer.Memmove(), and System.ThrowHelper.ThrowArgumentException_DestinationTooShort().
Referenced by Microsoft.Win32.SafeHandles.SafePasswordHandle.SafePasswordHandle(), System.Xml.XmlUtf8RawTextWriter.XmlUtf8RawTextWriter(), System.Security.Cryptography.DSAImplementation.DSACng.AdjustHashSizeIfNecessary(), System.Security.Cryptography.DSACng.AdjustHashSizeIfNecessary(), System.Net.Security.SslStream.CopyDecryptedData(), Internal.Cryptography.AsymmetricAlgorithmHelpers.CopySignatureField(), System.Buffers.BuffersExtensions.CopyTo< T >(), System.Buffers.BuffersExtensions.CopyToMultiSegment< T >(), System.Net.Http.HPack.HPackDecoder.DecodeInternal(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Encrypt(), System.UriHelper.EscapeString(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.Security.Cryptography.RandomNumberGenerator.GetNonZeroBytes(), System.Security.Cryptography.DSA.HashSpanToArray(), System.Security.Cryptography.ECDsa.HashSpanToArray(), System.IO.Strategies.BufferedFileStreamStrategy._003CWriteAsyncSlowPath_003Ed__50.MoveNext(), System.Security.Cryptography.PasswordBasedEncryption.OpenPbkdf2(), Internal.Cryptography.UniversalCryptoEncryptor.PadBlock(), System.IO.Stream.Read(), System.IO.Stream.ReadAsync(), System.Security.Cryptography.CryptoStream.ReadAsyncCore(), System.IO.ReadOnlyMemoryStream.ReadBuffer(), System.IO.BufferedStream.ReadFromBuffer(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadSpan(), System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(), System.Text.SegmentStringBuilder.ToString(), System.Collections.Specialized.BitVector32.ToString(), System.Security.Cryptography.KeyBlobHelpers.ToUnsignedIntegerBytes(), System.Buffers.SequenceReader< T >.TryCopyMultisegment(), System.IO.Compression.BrotliStream.TryDecompress(), System.Security.Cryptography.RSA.TryDecrypt(), System.Security.Cryptography.RSA.TryEncrypt(), System.Security.Cryptography.PemEncoding.TryFind(), System.Security.Cryptography.ECDsa.TryHashData(), System.Security.Cryptography.RSA.TryHashData(), System.Security.Cryptography.HashAlgorithm.TryHashFinal(), System.IO.Path.TryJoin(), System.IO.Path.TryJoin(), System.Security.Cryptography.RSA.TrySignHash(), Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(), System.IO.StreamWriter.WriteAsyncInternal(), and System.Net.WebSockets.ManagedWebSocket.WriteFrameToSendBuffer().