Terraria: UIWorldCreation.MakeBackAndCreatebuttons
MakeBackAndCreatebuttons()
void UIWorldCreation.MakeBackAndCreatebuttons (UIElement outerContainer) inline private
     {
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true)
         {
             Width = StyleDimension.FromPixelsAndPercent(-10f, 0.5f),
             Height = StyleDimension.FromPixels(50f),
             VAlign = 1f,
             HAlign = 0f,
             Top = StyleDimension.FromPixels(-45f)
         };
         uITextPanel.OnMouseOver += FadedMouseOver;
         uITextPanel.OnMouseOut += FadedMouseOut;
         uITextPanel.OnLeftMouseDown += Click_GoBack;
         uITextPanel.SetSnapPoint("Back", 0);
         outerContainer.Append(uITextPanel);
         UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Create"), 0.7f, large: true)
         {
             Width = StyleDimension.FromPixelsAndPercent(-10f, 0.5f),
             Height = StyleDimension.FromPixels(50f),
             VAlign = 1f,
             HAlign = 1f,
             Top = StyleDimension.FromPixels(-45f)
         };
         uITextPanel2.OnMouseOver += FadedMouseOver;
         uITextPanel2.OnMouseOut += FadedMouseOut;
         uITextPanel2.OnLeftMouseDown += Click_NamingAndCreating;
         uITextPanel2.SetSnapPoint("Create", 0);
         outerContainer.Append(uITextPanel2);
     }
References UIElement.Append(), Click_GoBack(), Click_NamingAndCreating(), FadedMouseOut(), FadedMouseOver(), StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), Language.GetText(), UIElement.HAlign, UIElement.Height, UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().