Terraria: UIWorldCreation.ClickRandomizeName
ClickRandomizeName()
void UIWorldCreation.ClickRandomizeName (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         AssignRandomWorldName();
         UpdateInputFields();
         UpdateSliders();
         UpdatePreviewPlate();
     }
References AssignRandomWorldName(), UpdateInputFields(), UpdatePreviewPlate(), and UpdateSliders().
Referenced by MakeInfoMenu().