Terraria: UIWorldCreation.AssignRandomWorldName
AssignRandomWorldName()
void UIWorldCreation.AssignRandomWorldName () inline private
     {
         do
         {
             LocalizedText localizedText = Language.SelectRandom(Lang.CreateDialogFilter("RandomWorldName_Composition."));
             LocalizedText localizedText2 = Language.SelectRandom(Lang.CreateDialogFilter("RandomWorldName_Adjective."));
             LocalizedText localizedText3 = Language.SelectRandom(Lang.CreateDialogFilter("RandomWorldName_Location."));
             LocalizedText localizedText4 = Language.SelectRandom(Lang.CreateDialogFilter("RandomWorldName_Noun."));
             var obj = new
             {
                 Adjective = localizedText2.Value,
                 Location = localizedText3.Value,
                 Noun = localizedText4.Value
             };
             _optionwWorldName = localizedText.FormatWith(obj);
             if (Main.rand.Next(10000) == 0)
             {
                 _optionwWorldName = Language.GetTextValue("SpecialWorldName.TheConstant");
             }
         }
         while (_optionwWorldName.Length > 27);
     }
References _optionwWorldName, Lang.CreateDialogFilter(), LocalizedText.FormatWith(), Language.GetTextValue(), UnifiedRandom.Next(), Main.rand, Language.SelectRandom(), and LocalizedText.Value.
Referenced by ClickRandomizeName(), and SetDefaultOptions().