Terraria: UIWorldCreation.AddWorldEvilOptions
AddWorldEvilOptions()
void UIWorldCreation.AddWorldEvilOptions (UIElement container, float accumualtedHeight, MouseEvent clickEvent, string tagGroup, float usableWidthPercent) inline private
     {
         WorldEvilId[] array = new WorldEvilId[3]
         {
             WorldEvilId.Random,
             WorldEvilId.Corruption,
             WorldEvilId.Crimson
         };
         LocalizedText[] array2 = new LocalizedText[3]
         {
             Lang.misc[103],
             Lang.misc[101],
             Lang.misc[102]
         };
         LocalizedText[] array3 = new LocalizedText[3]
         {
             Language.GetText("UI.WorldDescriptionEvilRandom"),
             Language.GetText("UI.WorldDescriptionEvilCorrupt"),
             Language.GetText("UI.WorldDescriptionEvilCrimson")
         };
         Color[] array4 = new Color[3]
         {
             Color.White,
             Color.MediumPurple,
             Color.IndianRed
         };
         string[] array5 = new string[3] { "Images/UI/WorldCreation/IconEvilRandom", "Images/UI/WorldCreation/IconEvilCorruption", "Images/UI/WorldCreation/IconEvilCrimson" };
         GroupOptionButton<WorldEvilId>[] array6 = new GroupOptionButton<WorldEvilId>[array.Length];
         for (int i = 0; i < array6.Length; i++)
         {
             GroupOptionButton<WorldEvilId> groupOptionButton = new GroupOptionButton<WorldEvilId>(array[i], array2[i], array3[i], array4[i], array5[i], 1f, 1f, 16f);
             groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(-4 * (array6.Length - 1), 1f / (float)array6.Length * usableWidthPercent);
             groupOptionButton.Left = StyleDimension.FromPercent(1f - usableWidthPercent);
             groupOptionButton.HAlign = (float)i / (float)(array6.Length - 1);
             groupOptionButton.Top.Set(accumualtedHeight, 0f);
             groupOptionButton.OnLeftMouseDown += clickEvent;
             groupOptionButton.OnMouseOver += ShowOptionDescription;
             groupOptionButton.OnMouseOut += ClearOptionDescription;
             groupOptionButton.SetSnapPoint(tagGroup, i);
             container.Append(groupOptionButton);
             array6[i] = groupOptionButton;
         }
         _evilButtons = array6;
     }
References _evilButtons, UIElement.Append(), ClearOptionDescription(), Color, StyleDimension.FromPercent(), StyleDimension.FromPixelsAndPercent(), Language.GetText(), Lang.misc, and ShowOptionDescription().
Referenced by MakeInfoMenu().