Terraria: UIWorldCreation.OnFinishedSettingName
OnFinishedSettingName()
void UIWorldCreation.OnFinishedSettingName (string name) inline private
     {
         _optionwWorldName = name.Trim();
         UpdateInputFields();
         GoBackHere();
     }
References _optionwWorldName, GoBackHere(), and UpdateInputFields().
Referenced by Click_SetName(), and OnFinishedNamingAndCreating().