Terraria: UIWorldCreation.UpdateInputFields
UpdateInputFields()
void UIWorldCreation.UpdateInputFields () inline private
     {
         _namePlate.SetContents(_optionwWorldName);
         _namePlate.Recalculate();
         _namePlate.TrimDisplayIfOverElementDimensions(27);
         _namePlate.Recalculate();
         _seedPlate.SetContents(_optionSeed);
         _seedPlate.Recalculate();
         _seedPlate.TrimDisplayIfOverElementDimensions(40);
         _seedPlate.Recalculate();
     }
References _namePlate, _optionSeed, _optionwWorldName, _seedPlate, UIElement.Recalculate(), UICharacterNameButton.SetContents(), and UICharacterNameButton.TrimDisplayIfOverElementDimensions().
Referenced by ClickRandomizeName(), ClickRandomizeSeed(), OnFinishedSettingName(), OnFinishedSettingSeed(), and SetDefaultOptions().