Terraria: UIWorldCreation.ClickEvilOption
ClickEvilOption()
void UIWorldCreation.ClickEvilOption (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         GroupOptionButton<WorldEvilId> groupOptionButton = (GroupOptionButton<WorldEvilId>)listeningElement;
         _optionEvil = groupOptionButton.OptionValue;
         GroupOptionButton<WorldEvilId>[] evilButtons = _evilButtons;
         for (int i = 0; i < evilButtons.Length; i++)
         {
             evilButtons[i].SetCurrentOption(groupOptionButton.OptionValue);
         }
         UpdatePreviewPlate();
     }
References _evilButtons, _optionEvil, GroupOptionButton< T >.OptionValue, GroupOptionButton< T >.SetCurrentOption(), and UpdatePreviewPlate().
Referenced by MakeInfoMenu().