Terraria: UIWorldCreation.ProcessSpecialWorldSeeds
ProcessSpecialWorldSeeds()
static void UIWorldCreation.ProcessSpecialWorldSeeds (string processedSeed) inline static
     {
         WorldGen.noTrapsWorldGen = false;
         WorldGen.notTheBees = false;
         WorldGen.getGoodWorldGen = false;
         WorldGen.tenthAnniversaryWorldGen = false;
         WorldGen.dontStarveWorldGen = false;
         WorldGen.tempRemixWorldGen = false;
         WorldGen.tempTenthAnniversaryWorldGen = false;
         WorldGen.everythingWorldGen = false;
         if (processedSeed.ToLower() == "no traps" || processedSeed.ToLower() == "notraps")
         {
             WorldGen.noTrapsWorldGen = true;
         }
         if (processedSeed.ToLower() == "not the bees" || processedSeed.ToLower() == "not the bees!" || processedSeed.ToLower() == "notthebees")
         {
             WorldGen.notTheBees = true;
         }
         if (processedSeed.ToLower() == "for the worthy" || processedSeed.ToLower() == "fortheworthy")
         {
             WorldGen.getGoodWorldGen = true;
         }
         if (processedSeed.ToLower() == "don't dig up" || processedSeed.ToLower() == "dont dig up" || processedSeed.ToLower() == "dontdigup")
         {
             WorldGen.tempRemixWorldGen = true;
         }
         if (processedSeed.ToLower() == "celebrationmk10")
         {
             WorldGen.tempTenthAnniversaryWorldGen = true;
         }
         if (processedSeed.ToLower() == "constant" || processedSeed.ToLower() == "theconstant" || processedSeed.ToLower() == "the constant" || processedSeed.ToLower() == "eye4aneye" || processedSeed.ToLower() == "eyeforaneye")
         {
             WorldGen.dontStarveWorldGen = true;
         }
         if (processedSeed.ToLower() == "get fixed boi" || processedSeed.ToLower() == "getfixedboi")
         {
             WorldGen.noTrapsWorldGen = true;
             WorldGen.notTheBees = true;
             WorldGen.getGoodWorldGen = true;
             WorldGen.tempTenthAnniversaryWorldGen = true;
             WorldGen.dontStarveWorldGen = true;
             WorldGen.tempRemixWorldGen = true;
             WorldGen.everythingWorldGen = true;
         }
     }
References WorldGen.dontStarveWorldGen, WorldGen.everythingWorldGen, WorldGen.getGoodWorldGen, WorldGen.noTrapsWorldGen, WorldGen.notTheBees, WorldGen.tempRemixWorldGen, WorldGen.tempTenthAnniversaryWorldGen, and WorldGen.tenthAnniversaryWorldGen.
Referenced by Main.DedServ(), WorldFile.LoadWorld(), and ProcessSeed().