Terraria: UIWorldCreation.FinishCreatingWorld
FinishCreatingWorld()
void UIWorldCreation.FinishCreatingWorld () inline private
     {
         ProcessSeed(out var processedSeed);
         switch (_optionSize)
         {
         case WorldSizeId.Small:
             Main.maxTilesX = 4200;
             Main.maxTilesY = 1200;
             break;
         case WorldSizeId.Medium:
             Main.maxTilesX = 6400;
             Main.maxTilesY = 1800;
             break;
         case WorldSizeId.Large:
             Main.maxTilesX = 8400;
             Main.maxTilesY = 2400;
             break;
         }
         WorldGen.setWorldSize();
         switch (_optionDifficulty)
         {
         case WorldDifficultyId.Creative:
             Main.GameMode = 3;
             break;
         case WorldDifficultyId.Normal:
             Main.GameMode = 0;
             break;
         case WorldDifficultyId.Expert:
             Main.GameMode = 1;
             break;
         case WorldDifficultyId.Master:
             Main.GameMode = 2;
             break;
         }
         switch (_optionEvil)
         {
         case WorldEvilId.Random:
             WorldGen.WorldGenParam_Evil = -1;
             break;
         case WorldEvilId.Corruption:
             WorldGen.WorldGenParam_Evil = 0;
             break;
         case WorldEvilId.Crimson:
             WorldGen.WorldGenParam_Evil = 1;
             break;
         }
         Main.ActiveWorldFileData = WorldFile.CreateMetadata(Main.worldName = _optionwWorldName.Trim(), SocialAPI.Cloud != null && SocialAPI.Cloud.EnabledByDefault, Main.GameMode);
         if (processedSeed.Length == 0)
         {
             Main.ActiveWorldFileData.SetSeedToRandom();
         }
         else
         {
             Main.ActiveWorldFileData.SetSeed(processedSeed);
         }
         Main.menuMode = 10;
         WorldGen.CreateNewWorld();
     }
References _optionDifficulty, _optionEvil, _optionSize, _optionwWorldName, Main.ActiveWorldFileData, SocialAPI.Cloud, WorldFile.CreateMetadata(), WorldGen.CreateNewWorld(), CloudSocialModule.EnabledByDefault, Main.GameMode, Main.maxTilesX, Main.maxTilesY, Main.menuMode, ProcessSeed(), WorldFileData.SetSeed(), WorldFileData.SetSeedToRandom(), WorldGen.setWorldSize(), WorldGen.WorldGenParam_Evil, and Main.worldName.
Referenced by Click_NamingAndCreating(), and OnFinishedNamingAndCreating().