Terraria: UIWorldCreation.AddWorldDifficultyOptions
AddWorldDifficultyOptions()
void UIWorldCreation.AddWorldDifficultyOptions (UIElement container, float accumualtedHeight, MouseEvent clickEvent, string tagGroup, float usableWidthPercent) inline private
     {
         WorldDifficultyId[] array = new WorldDifficultyId[4]
         {
             WorldDifficultyId.Creative,
             WorldDifficultyId.Normal,
             WorldDifficultyId.Expert,
             WorldDifficultyId.Master
         };
         LocalizedText[] array2 = new LocalizedText[4]
         {
             Language.GetText("UI.Creative"),
             Language.GetText("UI.Normal"),
             Language.GetText("UI.Expert"),
             Language.GetText("UI.Master")
         };
         LocalizedText[] array3 = new LocalizedText[4]
         {
             Language.GetText("UI.WorldDescriptionCreative"),
             Language.GetText("UI.WorldDescriptionNormal"),
             Language.GetText("UI.WorldDescriptionExpert"),
             Language.GetText("UI.WorldDescriptionMaster")
         };
         Color[] array4 = new Color[4]
         {
             Main.creativeModeColor,
             Color.White,
             Main.mcColor,
             Main.hcColor
         };
         string[] array5 = new string[4] { "Images/UI/WorldCreation/IconDifficultyCreative", "Images/UI/WorldCreation/IconDifficultyNormal", "Images/UI/WorldCreation/IconDifficultyExpert", "Images/UI/WorldCreation/IconDifficultyMaster" };
         GroupOptionButton<WorldDifficultyId>[] array6 = new GroupOptionButton<WorldDifficultyId>[array.Length];
         for (int i = 0; i < array6.Length; i++)
         {
             GroupOptionButton<WorldDifficultyId> groupOptionButton = new GroupOptionButton<WorldDifficultyId>(array[i], array2[i], array3[i], array4[i], array5[i], 1f, 1f, 16f);
             groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(-1 * (array6.Length - 1), 1f / (float)array6.Length * usableWidthPercent);
             groupOptionButton.Left = StyleDimension.FromPercent(1f - usableWidthPercent);
             groupOptionButton.HAlign = (float)i / (float)(array6.Length - 1);
             groupOptionButton.Top.Set(accumualtedHeight, 0f);
             groupOptionButton.OnLeftMouseDown += clickEvent;
             groupOptionButton.OnMouseOver += ShowOptionDescription;
             groupOptionButton.OnMouseOut += ClearOptionDescription;
             groupOptionButton.SetSnapPoint(tagGroup, i);
             container.Append(groupOptionButton);
             array6[i] = groupOptionButton;
         }
         _difficultyButtons = array6;
     }
References _difficultyButtons, UIElement.Append(), ClearOptionDescription(), Color, Main.creativeModeColor, StyleDimension.FromPercent(), StyleDimension.FromPixelsAndPercent(), Language.GetText(), Main.hcColor, Main.mcColor, and ShowOptionDescription().
Referenced by MakeInfoMenu().