Terraria: System.Threading.Channels.UnboundedChannel.UnboundedChannelReader.WaitToReadAsync
WaitToReadAsync()
override ValueTask< bool > System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelReader.WaitToReadAsync (CancellationToken cancellationToken) inline
Definition at line 101 of file UnboundedChannel.cs.
        {
            if (cancellationToken.IsCancellationRequested)
            {
                return new ValueTask<bool>(Task.FromCanceled<bool>(cancellationToken));
            }
            if (!_parent._items.IsEmpty)
            {
                return new ValueTask<bool>(result: true);
            }
            UnboundedChannel<T> parent = _parent;
            lock (parent.SyncObj)
            {
                if (!parent._items.IsEmpty)
                {
                    return new ValueTask<bool>(result: true);
                }
                if (parent._doneWriting != null)
                {
                    return (parent._doneWriting != ChannelUtilities.s_doneWritingSentinel) ? new ValueTask<bool>(Task.FromException<bool>(parent._doneWriting)) : default(ValueTask<bool>);
                }
                if (!cancellationToken.CanBeCanceled)
                {
                    AsyncOperation<bool> waiterSingleton = _waiterSingleton;
                    if (waiterSingleton.TryOwnAndReset())
                    {
                        ChannelUtilities.QueueWaiter(ref parent._waitingReadersTail, waiterSingleton);
                        return waiterSingleton.ValueTaskOfT;
                    }
                }
                AsyncOperation<bool> asyncOperation = new AsyncOperation<bool>(parent._runContinuationsAsynchronously, cancellationToken);
                ChannelUtilities.QueueWaiter(ref parent._waitingReadersTail, asyncOperation);
                return asyncOperation.ValueTaskOfT;
            }
        }
References System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelReader._parent, System.Threading.Channels.UnboundedChannel< T >.UnboundedChannelReader._waiterSingleton, System.cancellationToken, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.Channels.ChannelUtilities.QueueWaiter(), and System.Threading.Channels.ChannelUtilities.s_doneWritingSentinel.