Terraria: System.Net.Http.VariableLengthIntegerHelper.TryRead
TryRead()
static bool System.Net.Http.VariableLengthIntegerHelper.TryRead (ReadOnlySpan< byte > buffer, out long value, out int bytesRead) inline static
Definition at line 7 of file VariableLengthIntegerHelper.cs.
    {
        if (buffer.Length != 0)
        {
            byte b = buffer[0];
            switch (b & 0xC0)
            {
            case 0:
                value = b;
                bytesRead = 1;
                return true;
            case 64:
            {
                if (BinaryPrimitives.TryReadUInt16BigEndian(buffer, out var value3))
                {
                    value = (uint)(value3 - 16384);
                    bytesRead = 2;
                    return true;
                }
                break;
            }
            case 128:
            {
                if (BinaryPrimitives.TryReadUInt32BigEndian(buffer, out var value4))
                {
                    value = (uint)((int)value4 - int.MinValue);
                    bytesRead = 4;
                    return true;
                }
                break;
            }
            default:
            {
                if (BinaryPrimitives.TryReadUInt64BigEndian(buffer, out var value2))
                {
                    value = (long)value2 - -4611686018427387904L;
                    bytesRead = 8;
                    return true;
                }
                break;
            }
            }
        }
        value = 0L;
        bytesRead = 0;
        return false;
    }
References System.buffer, System.L, System.Buffers.Binary.BinaryPrimitives.TryReadUInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt64BigEndian(), and System.value.
Referenced by System.Net.Http.Http3Connection.ProcessServerControlStreamAsync(), System.Net.Http.Http3Connection.ProcessServerStreamAsync(), and System.Net.Http.Http3Frame.TryReadIntegerPair().