Terraria: Terraria.GameContent.RGB.DungeonShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.DungeonShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 16 of file DungeonShader.cs.
    {
        for (int i = 0; i < fragment.Count; i++)
        {
            Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            float num = ((NoiseHelper.GetStaticNoise(gridPositionOfIndex.Y) * 10f + time) % 10f - (canvasPositionOfIndex.X + 2f)) * 0.5f;
            Vector4 vector = _backgroundColor;
            if (num > 0f)
            {
                float num2 = Math.Max(0f, 1.2f - num);
                float amount = MathHelper.Clamp(num2 * num2 * num2, 0f, 1f);
                if (num < 0.2f)
                {
                    num2 = num / 0.2f;
                }
                Vector4 value = Vector4.Lerp(_spiritTrailColor, _spiritColor, amount);
                vector = Vector4.Lerp(vector, value, num2);
            }
            fragment.SetColor(i, vector);
        }
    }
References Terraria.GameContent.RGB.DungeonShader._backgroundColor, Terraria.GameContent.RGB.DungeonShader._spiritColor, Terraria.GameContent.RGB.DungeonShader._spiritTrailColor, Microsoft.Xna.Framework.MathHelper.Clamp(), ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), ReLogic.Peripherals.RGB.Fragment.SetColor(), System.value, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Point.Y.