Terraria: System.AggregateException.Flatten
Flatten()
AggregateException System.AggregateException.Flatten () inline
Definition at line 175 of file AggregateException.cs.
    {
        List<Exception> list = new List<Exception>();
        List<AggregateException> list2 = new List<AggregateException> { this };
        int num = 0;
        while (list2.Count > num)
        {
            ReadOnlyCollection<Exception> innerExceptions = list2[num++].InnerExceptions;
            for (int i = 0; i < innerExceptions.Count; i++)
            {
                Exception ex = innerExceptions[i];
                if (ex != null)
                {
                    if (ex is AggregateException item)
                    {
                        list2.Add(item);
                    }
                    else
                    {
                        list.Add(ex);
                    }
                }
            }
        }
        return new AggregateException((GetType() == typeof(AggregateException)) ? base.Message : Message, list.ToArray(), cloneExceptions: false);
    }
References System.AggregateException.AggregateException(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Runtime.Serialization.Dictionary, System.Exception.GetType(), System.item, System.list, and System.AggregateException.Message.
Referenced by System.Linq.Parallel.QueryTaskGroupState.QueryEnd().