Terraria: Terraria.GameContent.UI.States.UIResourcePackInfoMenu.Recalculate
Recalculate()
override void Terraria.GameContent.UI.States.UIResourcePackInfoMenu.Recalculate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 150 of file UIResourcePackInfoMenu.cs.
    {
        if (_scrollbar != null)
        {
            if (_isScrollbarAttached && !_scrollbar.CanScroll)
            {
                _container.RemoveChild(_scrollbar);
                _isScrollbarAttached = false;
                _list.Width.Set(0f, 1f);
            }
            else if (!_isScrollbarAttached && _scrollbar.CanScroll)
            {
                _container.Append(_scrollbar);
                _isScrollbarAttached = true;
                _list.Width.Set(-25f, 1f);
            }
        }
        base.Recalculate();
    }
References Terraria.GameContent.UI.States.UIResourcePackInfoMenu._container, Terraria.GameContent.UI.States.UIResourcePackInfoMenu._isScrollbarAttached, Terraria.GameContent.UI.States.UIResourcePackInfoMenu._list, Terraria.GameContent.UI.States.UIResourcePackInfoMenu._scrollbar, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIScrollbar.CanScroll, Terraria.UI.UIElement.RemoveChild(), Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.Width.