Terraria: Terraria.GameContent.UI.States.UIResourcePackInfoMenu.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIResourcePackInfoMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 194 of file UIResourcePackInfoMenu.cs.
    {
        UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
        int num = 3000;
        int idRangeEndExclusive = num;
        List<SnapPoint> snapPoints = GetSnapPoints();
        for (int i = 0; i < snapPoints.Count; i++)
        {
            SnapPoint snapPoint = snapPoints[i];
            string name = snapPoint.Name;
            if (name == "GoBack")
            {
                _helper.MakeLinkPointFromSnapPoint(idRangeEndExclusive++, snapPoint);
            }
        }
        _helper.MoveToVisuallyClosestPoint(num, idRangeEndExclusive);
    }
References Terraria.GameContent.UI.States.UIResourcePackInfoMenu._helper, Terraria.UI.UIElement.GetSnapPoints(), Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), and ReLogic.Content.Asset< T >.Name.
Referenced by Terraria.GameContent.UI.States.UIResourcePackInfoMenu.Draw().