Terraria: System.ApplicationId.Equals
Equals()
override bool System.ApplicationId.Equals ([NotNullWhen(true)] object? o) inline
Definition at line 79 of file ApplicationId.cs.
    {
        if (!(o is ApplicationId applicationId))
        {
            return false;
        }
        if (!object.Equals(Name, applicationId.Name) || !object.Equals(Version, applicationId.Version) || !object.Equals(ProcessorArchitecture, applicationId.ProcessorArchitecture) || !object.Equals(Culture, applicationId.Culture))
        {
            return false;
        }
        if (_publicKeyToken.Length != applicationId._publicKeyToken.Length)
        {
            return false;
        }
        for (int i = 0; i < _publicKeyToken.Length; i++)
        {
            if (_publicKeyToken[i] != applicationId._publicKeyToken[i])
            {
                return false;
            }
        }
        return true;
    }
References System.Version.Version(), System.ApplicationId._publicKeyToken, System.ApplicationId.Culture, System.ApplicationId.Equals(), System.ApplicationId.Name, and System.ApplicationId.ProcessorArchitecture.
Referenced by System.ApplicationId.Equals().