Terraria: System.ApplicationId.ToString
ToString()
override string System.ApplicationId.ToString () inline
Definition at line 50 of file ApplicationId.cs.
    {
        Span<char> initialBuffer = stackalloc char[128];
        ValueStringBuilder valueStringBuilder = new ValueStringBuilder(initialBuffer);
        valueStringBuilder.Append(Name);
        if (Culture != null)
        {
            valueStringBuilder.Append(", culture=\"");
            valueStringBuilder.Append(Culture);
            valueStringBuilder.Append('"');
        }
        valueStringBuilder.Append(", version=\"");
        valueStringBuilder.Append(Version.ToString());
        valueStringBuilder.Append('"');
        if (_publicKeyToken != null)
        {
            valueStringBuilder.Append(", publicKeyToken=\"");
            HexConverter.EncodeToUtf16(_publicKeyToken, valueStringBuilder.AppendSpan(2 * _publicKeyToken.Length));
            valueStringBuilder.Append('"');
        }
        if (ProcessorArchitecture != null)
        {
            valueStringBuilder.Append(", processorArchitecture =\"");
            valueStringBuilder.Append(ProcessorArchitecture);
            valueStringBuilder.Append('"');
        }
        return valueStringBuilder.ToString();
    }
References System.ApplicationId._publicKeyToken, System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.AppendSpan(), System.ApplicationId.Culture, System.HexConverter.EncodeToUtf16(), System.ApplicationId.Name, System.ApplicationId.ProcessorArchitecture, System.Text.ValueStringBuilder.ToString(), and System.Version.ToString().