Terraria: LiquidRenderer.DrawShimmer
DrawShimmer()
unsafe void LiquidRenderer.DrawShimmer (SpriteBatch spriteBatch, Vector2 drawOffset, bool isBackgroundDraw) inline
     {
         Rectangle drawArea = _drawArea;
         Main.tileBatch.Begin();
         fixed (SpecialLiquidDrawCache* ptr = &_drawCacheForShimmer[0])
         {
             SpecialLiquidDrawCache* ptr2 = ptr;
             int num = _drawCacheForShimmer.Length;
             for (int i = 0; i < num; i++)
             {
                 if (!ptr2->IsVisible)
                 {
                     break;
                 }
                 Rectangle sourceRectangle = ptr2->SourceRectangle;
                 if (ptr2->IsSurfaceLiquid)
                 {
                     sourceRectangle.Y = 1280;
                 }
                 else
                 {
                     sourceRectangle.Y += _animationFrame * 80;
                 }
                 Vector2 liquidOffset = ptr2->LiquidOffset;
                 float val = ptr2->Opacity * (isBackgroundDraw ? 1f : 0.75f);
                 int num2 = 14;
                 val = Math.Min(1f, val);
                 int num3 = ptr2->X + drawArea.X - 2;
                 int num4 = ptr2->Y + drawArea.Y - 2;
                 Lighting.GetCornerColors(num3, num4, out var vertices);
                 SetShimmerVertexColors(ref vertices, val, num3, num4);
                 Main.DrawTileInWater(drawOffset, num3, num4);
                 Main.tileBatch.Draw(_liquidTextures[num2].Value, new Vector2(num3 << 4, num4 << 4) + drawOffset + liquidOffset, sourceRectangle, vertices, Vector2.Zero, 1f, SpriteEffects.None);
                 sourceRectangle = ptr2->SourceRectangle;
                 bool flag = sourceRectangle.X != 16 || sourceRectangle.Y % 80 != 48;
                 if (flag || (num3 + num4) % 2 == 0)
                 {
                     sourceRectangle.X += 48;
                     sourceRectangle.Y += 80 * GetShimmerFrame(flag, num3, num4);
                     SetShimmerVertexColors_Sparkle(ref vertices, ptr2->Opacity, num3, num4, flag);
                     Main.tileBatch.Draw(_liquidTextures[num2].Value, new Vector2(num3 << 4, num4 << 4) + drawOffset + liquidOffset, sourceRectangle, vertices, Vector2.Zero, 1f, SpriteEffects.None);
                 }
                 ptr2++;
             }
         }
         Main.tileBatch.End();
     }
References _animationFrame, _drawArea, _drawCacheForShimmer, _liquidTextures, TileBatch.Begin(), TileBatch.Draw(), Main.DrawTileInWater(), TileBatch.End(), Lighting.GetCornerColors(), GetShimmerFrame(), LiquidRenderer.SpecialLiquidDrawCache.IsSurfaceLiquid, LiquidRenderer.SpecialLiquidDrawCache.IsVisible, LiquidRenderer.SpecialLiquidDrawCache.LiquidOffset, LiquidRenderer.SpecialLiquidDrawCache.Opacity, SetShimmerVertexColors(), SetShimmerVertexColors_Sparkle(), LiquidRenderer.SpecialLiquidDrawCache.SourceRectangle, Main.tileBatch, LiquidRenderer.SpecialLiquidDrawCache.X, and LiquidRenderer.SpecialLiquidDrawCache.Y.
Referenced by Main.DrawLiquid().