Terraria: LiquidRenderer.SetShimmerVertexColors
SetShimmerVertexColors()
static void LiquidRenderer.SetShimmerVertexColors (ref VertexColors colors, float opacity, int x, int y) inline static
     {
         colors.BottomLeftColor = Color.White;
         colors.BottomRightColor = Color.White;
         colors.TopLeftColor = Color.White;
         colors.TopRightColor = Color.White;
         colors.BottomLeftColor *= opacity;
         colors.BottomRightColor *= opacity;
         colors.TopLeftColor *= opacity;
         colors.TopRightColor *= opacity;
         colors.BottomLeftColor = new Color(colors.BottomLeftColor.ToVector4() * GetShimmerBaseColor(x, y + 1));
         colors.BottomRightColor = new Color(colors.BottomRightColor.ToVector4() * GetShimmerBaseColor(x + 1, y + 1));
         colors.TopLeftColor = new Color(colors.TopLeftColor.ToVector4() * GetShimmerBaseColor(x, y));
         colors.TopRightColor = new Color(colors.TopRightColor.ToVector4() * GetShimmerBaseColor(x + 1, y));
     }
References Color, and GetShimmerBaseColor().
Referenced by DrawShimmer(), TileDrawing.DrawTile_LiquidBehindTile(), and WaterfallManager.DrawWaterfall().