Terraria: System.Linq.Parallel.DistinctQueryOperator.OrderedDistinctQueryOperatorEnumerator.MoveNext
MoveNext() [2/2]
override bool System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.OrderedDistinctQueryOperatorEnumerator< TKey >.MoveNext ([AllowNull] ref TInputOutput currentElement, [AllowNull] ref TKey currentKey) inline package
Definition at line 75 of file DistinctQueryOperator.cs.
        {
            if (_hashLookupEnumerator == null)
            {
                Pair<TInputOutput, NoKeyMemoizationRequired> currentElement2 = default(Pair<TInputOutput, NoKeyMemoizationRequired>);
                TKey currentKey2 = default(TKey);
                int num = 0;
                while (_source.MoveNext(ref currentElement2, ref currentKey2))
                {
                    if ((num++ & 0x3F) == 0)
                    {
                        _cancellationToken.ThrowIfCancellationRequested();
                    }
                    Wrapper<TInputOutput> key = new Wrapper<TInputOutput>(currentElement2.First);
                    if (!_hashLookup.TryGetValue(key, out var value) || _keyComparer.Compare(currentKey2, value) < 0)
                    {
                        _hashLookup[key] = currentKey2;
                    }
                }
                _hashLookupEnumerator = _hashLookup.GetEnumerator();
            }
            if (_hashLookupEnumerator.MoveNext())
            {
                KeyValuePair<Wrapper<TInputOutput>, TKey> current = _hashLookupEnumerator.Current;
                currentElement = current.Key.Value;
                currentKey = current.Value;
                return true;
            }
            return false;
        }
References System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.OrderedDistinctQueryOperatorEnumerator< TKey >._cancellationToken, System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.OrderedDistinctQueryOperatorEnumerator< TKey >._hashLookup, System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.OrderedDistinctQueryOperatorEnumerator< TKey >._hashLookupEnumerator, System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.OrderedDistinctQueryOperatorEnumerator< TKey >._keyComparer, System.Linq.Parallel.DistinctQueryOperator< TInputOutput >.OrderedDistinctQueryOperatorEnumerator< TKey >._source, System.Collections.Generic.IComparer< in T >.Compare(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.key, System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.