Terraria: Internal.Cryptography.BasicSymmetricCipherCsp.BasicSymmetricCipherCsp
BasicSymmetricCipherCsp()
Internal.Cryptography.BasicSymmetricCipherCsp.BasicSymmetricCipherCsp (int algId, CipherMode cipherMode, int blockSizeInBytes, byte[] key, int effectiveKeyLength, bool addNoSaltFlag, byte[] iv, bool encrypting, int feedbackSize, int paddingSizeInBytes) inline
Definition at line 15 of file BasicSymmetricCipherCsp.cs.
        : base(cipherMode.GetCipherIv(iv), blockSizeInBytes, paddingSizeInBytes)
    {
        _encrypting = encrypting;
        _hProvider = AcquireSafeProviderHandle();
        _hKey = ImportCspBlob(_hProvider, algId, key, addNoSaltFlag);
        CapiHelper.SetKeyParameter(_hKey, CapiHelper.CryptGetKeyParamQueryType.KP_MODE, (int)cipherMode);
        if (cipherMode == CipherMode.CFB)
        {
            CapiHelper.SetKeyParameter(_hKey, CapiHelper.CryptGetKeyParamQueryType.KP_MODE_BITS, feedbackSize);
        }
        byte[] cipherIv = cipherMode.GetCipherIv(iv);
        if (cipherIv != null)
        {
            CapiHelper.SetKeyParameter(_hKey, CapiHelper.CryptGetKeyParamQueryType.KP_IV, cipherIv);
        }
        if (effectiveKeyLength != 0)
        {
            CapiHelper.SetKeyParameter(_hKey, CapiHelper.CryptGetKeyParamQueryType.KP_EFFECTIVE_KEYLEN, effectiveKeyLength);
        }
    }
References Internal.Cryptography.BasicSymmetricCipherCsp._encrypting, Internal.Cryptography.BasicSymmetricCipherCsp._hKey, Internal.Cryptography.BasicSymmetricCipherCsp._hProvider, Internal.Cryptography.BasicSymmetricCipherCsp.AcquireSafeProviderHandle(), Internal.Cryptography.BasicSymmetricCipherCsp.ImportCspBlob(), System.key, and Internal.NativeCrypto.CapiHelper.SetKeyParameter().