Terraria: System.DateTimeParse.GetYearMonthDayOrder
GetYearMonthDayOrder()
static bool System.DateTimeParse.GetYearMonthDayOrder (string datePattern, out int order) inline static private
Definition at line 1286 of file DateTimeParse.cs.
    {
        int num = -1;
        int num2 = -1;
        int num3 = -1;
        int num4 = 0;
        bool flag = false;
        for (int i = 0; i < datePattern.Length && num4 < 3; i++)
        {
            char c = datePattern[i];
            switch (c)
            {
            case '%':
            case '\\':
                i++;
                continue;
            case '"':
            case '\'':
                flag = !flag;
                break;
            }
            if (flag)
            {
                continue;
            }
            switch (c)
            {
            case 'y':
                num = num4++;
                for (; i + 1 < datePattern.Length && datePattern[i + 1] == 'y'; i++)
                {
                }
                break;
            case 'M':
                num2 = num4++;
                for (; i + 1 < datePattern.Length && datePattern[i + 1] == 'M'; i++)
                {
                }
                break;
            case 'd':
            {
                int num5 = 1;
                for (; i + 1 < datePattern.Length && datePattern[i + 1] == 'd'; i++)
                {
                    num5++;
                }
                if (num5 <= 2)
                {
                    num3 = num4++;
                }
                break;
            }
            }
        }
        if (num == 0 && num2 == 1 && num3 == 2)
        {
            order = 0;
            return true;
        }
        if (num2 == 0 && num3 == 1 && num == 2)
        {
            order = 1;
            return true;
        }
        if (num3 == 0 && num2 == 1 && num == 2)
        {
            order = 2;
            return true;
        }
        if (num == 0 && num3 == 1 && num2 == 2)
        {
            order = 3;
            return true;
        }
        order = -1;
        return false;
    }
Referenced by System.DateTimeParse.GetDateOfNNDS(), System.DateTimeParse.GetDayOfMNN(), System.DateTimeParse.GetDayOfNNN(), System.DateTimeParse.GetDayOfNNY(), and System.DateTimeParse.GetDayOfYNN().