Terraria: System.Net.Http.HttpTelemetry.WriteEvent
WriteEvent() [15/21]
unsafe void System.Net.Http.HttpTelemetry.WriteEvent (int eventId, string arg1, string arg2, int arg3, string arg4, byte arg5, byte arg6, HttpVersionPolicy arg7) inline private
Definition at line 163 of file HttpTelemetry.cs.
    {
        //The blocks IL_004b, IL_004e, IL_0060, IL_01e3 are reachable both inside and outside the pinned region starting at IL_0048. ILSpy has duplicated these blocks in order to place them both within and outside the `fixed` statement.
        if (!IsEnabled())
        {
            return;
        }
        if (arg1 == null)
        {
            arg1 = "";
        }
        if (arg2 == null)
        {
            arg2 = "";
        }
        if (arg4 == null)
        {
            arg4 = "";
        }
        fixed (char* ptr5 = arg1)
        {
            char* intPtr;
            EventData* intPtr2;
            nint num;
            nint num2;
            nint num3;
            nint num4;
            nint num5;
            nint num6;
            if (arg2 == null)
            {
                char* ptr;
                intPtr = (ptr = null);
                fixed (char* ptr2 = arg4)
                {
                    char* ptr3 = ptr2;
                    EventData* ptr4 = stackalloc EventData[7];
                    intPtr2 = ptr4;
                    *intPtr2 = new EventData
                    {
                        DataPointer = (IntPtr)ptr5,
                        Size = (arg1.Length + 1) * 2
                    };
                    num = (nint)(ptr4 + 1);
                    *(EventData*)num = new EventData
                    {
                        DataPointer = (IntPtr)ptr,
                        Size = (arg2.Length + 1) * 2
                    };
                    num2 = (nint)(ptr4 + 2);
                    *(EventData*)num2 = new EventData
                    {
                        DataPointer = (IntPtr)(&arg3),
                        Size = 4
                    };
                    num3 = (nint)(ptr4 + 3);
                    *(EventData*)num3 = new EventData
                    {
                        DataPointer = (IntPtr)ptr3,
                        Size = (arg4.Length + 1) * 2
                    };
                    num4 = (nint)(ptr4 + 4);
                    *(EventData*)num4 = new EventData
                    {
                        DataPointer = (IntPtr)(&arg5),
                        Size = 1
                    };
                    num5 = (nint)(ptr4 + 5);
                    *(EventData*)num5 = new EventData
                    {
                        DataPointer = (IntPtr)(&arg6),
                        Size = 1
                    };
                    num6 = (nint)(ptr4 + 6);
                    *(EventData*)num6 = new EventData
                    {
                        DataPointer = (IntPtr)(&arg7),
                        Size = 4
                    };
                    WriteEventCore(eventId, 7, ptr4);
                }
                return;
            }
            fixed (char* ptr6 = &arg2.GetPinnableReference())
            {
                char* ptr;
                intPtr = (ptr = ptr6);
                fixed (char* ptr2 = arg4)
                {
                    char* ptr3 = ptr2;
                    EventData* ptr4 = stackalloc EventData[7];
                    intPtr2 = ptr4;
                    *intPtr2 = new EventData
                    {
                        DataPointer = (IntPtr)ptr5,
                        Size = (arg1.Length + 1) * 2
                    };
                    num = (nint)(ptr4 + 1);
                    *(EventData*)num = new EventData
                    {
                        DataPointer = (IntPtr)ptr,
                        Size = (arg2.Length + 1) * 2
                    };
                    num2 = (nint)(ptr4 + 2);
                    *(EventData*)num2 = new EventData
                    {
                        DataPointer = (IntPtr)(&arg3),
                        Size = 4
                    };
                    num3 = (nint)(ptr4 + 3);
                    *(EventData*)num3 = new EventData
                    {
                        DataPointer = (IntPtr)ptr3,
                        Size = (arg4.Length + 1) * 2
                    };
                    num4 = (nint)(ptr4 + 4);
                    *(EventData*)num4 = new EventData
                    {
                        DataPointer = (IntPtr)(&arg5),
                        Size = 1
                    };
                    num5 = (nint)(ptr4 + 5);
                    *(EventData*)num5 = new EventData
                    {
                        DataPointer = (IntPtr)(&arg6),
                        Size = 1
                    };
                    num6 = (nint)(ptr4 + 6);
                    *(EventData*)num6 = new EventData
                    {
                        DataPointer = (IntPtr)(&arg7),
                        Size = 4
                    };
                    WriteEventCore(eventId, 7, ptr4);
                }
            }
        }
    }
References System.Diagnostics.Tracing.EventSource.IsEnabled(), and System.Diagnostics.Tracing.EventSource.WriteEventCore().
Referenced by System.Net.Http.HttpTelemetry.ConnectionClosed(), System.Net.Http.HttpTelemetry.ConnectionEstablished(), System.Net.Http.HttpTelemetry.RequestContentStart(), System.Net.Http.HttpTelemetry.RequestContentStop(), System.Net.Http.HttpTelemetry.RequestFailed(), System.Net.Http.HttpTelemetry.RequestHeadersStart(), System.Net.Http.HttpTelemetry.RequestHeadersStop(), System.Net.Http.HttpTelemetry.RequestLeftQueue(), System.Net.Http.HttpTelemetry.RequestStart(), System.Net.Http.HttpTelemetry.RequestStop(), System.Net.Http.HttpTelemetry.ResponseContentStart(), System.Net.Http.HttpTelemetry.ResponseContentStop(), System.Net.Http.HttpTelemetry.ResponseHeadersStart(), and System.Net.Http.HttpTelemetry.ResponseHeadersStop().