Terraria: System.DateTimeParse.TryParse
TryParse() [1/3]
static bool System.DateTimeParse.TryParse (ReadOnlySpan< char > s, DateTimeFormatInfo dtfi, DateTimeStyles styles, out DateTime result) inline static package
Definition at line 2271 of file DateTimeParse.cs.
    {
        DateTimeResult result2 = default(DateTimeResult);
        result2.Init(s);
        if (TryParse(s, dtfi, styles, ref result2))
        {
            result = result2.parsedDate;
            return true;
        }
        result = DateTime.MinValue;
        return false;
    }
References System.DateTimeResult.Init(), System.DateTime.MinValue, System.DateTimeResult.parsedDate, System.s, and System.DateTimeParse.TryParse().
Referenced by System.DateTimeParse.Parse(), System.DateTimeParse.Parse(), System.DateTimeOffset.TryParse(), System.DateTimeOffset.TryParse(), System.DateTime.TryParse(), System.DateTime.TryParse(), System.DateTimeOffset.TryParse(), System.DateTimeOffset.TryParse(), System.DateTimeParse.TryParse(), System.DateTimeParse.TryParse(), System.DateTime.TryParse(), System.DateTime.TryParse(), System.DateOnly.TryParseInternal(), and System.TimeOnly.TryParseInternal().