Terraria: System.DateTimeParse.ExpandPredefinedFormat
ExpandPredefinedFormat()
static string System.DateTimeParse.ExpandPredefinedFormat (ReadOnlySpan< char > format, ref DateTimeFormatInfo dtfi, ref ParsingInfo parseInfo, ref DateTimeResult result) inline static private
Definition at line 3157 of file DateTimeParse.cs.
    {
        switch (format[0])
        {
        case 'O':
        case 'o':
        case 's':
            ConfigureFormatOS(ref dtfi, ref parseInfo);
            break;
        case 'R':
        case 'r':
            ConfigureFormatR(ref dtfi, ref parseInfo, ref result);
            break;
        case 'u':
            parseInfo.calendar = GregorianCalendar.GetDefaultInstance();
            dtfi = DateTimeFormatInfo.InvariantInfo;
            if ((result.flags & ParseFlags.CaptureOffset) != 0)
            {
                result.flags |= ParseFlags.UtcSortPattern;
            }
            break;
        case 'U':
            parseInfo.calendar = GregorianCalendar.GetDefaultInstance();
            result.flags |= ParseFlags.TimeZoneUsed;
            result.timeZoneOffset = new TimeSpan(0L);
            result.flags |= ParseFlags.TimeZoneUtc;
            if (dtfi.Calendar.GetType() != typeof(GregorianCalendar))
            {
                dtfi = (DateTimeFormatInfo)dtfi.Clone();
                dtfi.Calendar = GregorianCalendar.GetDefaultInstance();
            }
            break;
        }
        return DateTimeFormat.GetRealFormat(format, dtfi);
    }
References System.DateTimeParse.ConfigureFormatOS(), System.DateTimeParse.ConfigureFormatR(), System.format, System.Globalization.GregorianCalendar.GetDefaultInstance(), System.DateTimeFormat.GetRealFormat(), System.Globalization.DateTimeFormatInfo.InvariantInfo, and System.L.
Referenced by System.DateTimeParse.DoStrictParse().