Terraria: System.DateTimeParse.TryAdjustYear
TryAdjustYear()
static bool System.DateTimeParse.TryAdjustYear (ref DateTimeResult result, int year, out int adjustedYear) inline static private
Definition at line 1479 of file DateTimeParse.cs.
    {
        if (year < 100)
        {
            try
            {
                year = result.calendar.ToFourDigitYear(year);
            }
            catch (ArgumentOutOfRangeException)
            {
                adjustedYear = -1;
                return false;
            }
        }
        adjustedYear = year;
        return true;
    }
References System.year.
Referenced by System.DateTimeParse.GetDateOfNDS(), System.DateTimeParse.GetDateOfNNDS(), System.DateTimeParse.GetDayOfMN(), System.DateTimeParse.GetDayOfMNN(), System.DateTimeParse.GetDayOfNM(), and System.DateTimeParse.GetDayOfNNN().