Terraria: System.DateTimeParse.GetDayOfNNN
GetDayOfNNN()
static bool System.DateTimeParse.GetDayOfNNN (ref DateTimeResult result, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static private
Definition at line 1560 of file DateTimeParse.cs.
    {
        if ((result.flags & ParseFlags.HaveDate) != 0)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        int number = raw.GetNumber(0);
        int number2 = raw.GetNumber(1);
        int number3 = raw.GetNumber(2);
        if (!GetYearMonthDayOrder(dtfi.ShortDatePattern, out var order))
        {
            result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_BadDatePattern", dtfi.ShortDatePattern);
            return false;
        }
        int adjustedYear;
        switch (order)
        {
        case 0:
            if (TryAdjustYear(ref result, number, out adjustedYear) && SetDateYMD(ref result, adjustedYear, number2, number3))
            {
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            break;
        case 1:
            if (TryAdjustYear(ref result, number3, out adjustedYear) && SetDateMDY(ref result, number, number2, adjustedYear))
            {
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            break;
        case 2:
            if (TryAdjustYear(ref result, number3, out adjustedYear) && SetDateDMY(ref result, number, number2, adjustedYear))
            {
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            break;
        case 3:
            if (TryAdjustYear(ref result, number, out adjustedYear) && SetDateYDM(ref result, adjustedYear, number2, number3))
            {
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            break;
        }
        result.SetBadDateTimeFailure();
        return false;
    }
References System.DateTimeParse.GetYearMonthDayOrder(), System.DateTimeParse.SetDateDMY(), System.DateTimeParse.SetDateMDY(), System.DateTimeParse.SetDateYDM(), System.DateTimeParse.SetDateYMD(), System.Globalization.DateTimeFormatInfo.ShortDatePattern, and System.DateTimeParse.TryAdjustYear().
Referenced by System.DateTimeParse.ProcessTerminalState().