Terraria: System.DateTimeParse.ProcessTerminalState
ProcessTerminalState()
static bool System.DateTimeParse.ProcessTerminalState (DS dps, ref DateTimeResult result, ref DateTimeStyles styles, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static package
Definition at line 2176 of file DateTimeParse.cs.
    {
        bool flag = true;
        switch (dps)
        {
        case DS.DX_NN:
            flag = GetDayOfNN(ref result, ref styles, ref raw, dtfi);
            break;
        case DS.DX_NNN:
            flag = GetDayOfNNN(ref result, ref raw, dtfi);
            break;
        case DS.DX_MN:
            flag = GetDayOfMN(ref result, ref styles, ref raw, dtfi);
            break;
        case DS.DX_NM:
            flag = GetDayOfNM(ref result, ref styles, ref raw, dtfi);
            break;
        case DS.DX_MNN:
            flag = GetDayOfMNN(ref result, ref raw, dtfi);
            break;
        case DS.DX_DS:
            flag = true;
            break;
        case DS.DX_YNN:
            flag = GetDayOfYNN(ref result, ref raw, dtfi);
            break;
        case DS.DX_NNY:
            flag = GetDayOfNNY(ref result, ref raw, dtfi);
            break;
        case DS.DX_YMN:
            flag = GetDayOfYMN(ref result, ref raw);
            break;
        case DS.DX_YN:
            flag = GetDayOfYN(ref result, ref raw);
            break;
        case DS.DX_YM:
            flag = GetDayOfYM(ref result, ref raw);
            break;
        case DS.TX_N:
            flag = GetTimeOfN(ref result, ref raw);
            break;
        case DS.TX_NN:
            flag = GetTimeOfNN(ref result, ref raw);
            break;
        case DS.TX_NNN:
            flag = GetTimeOfNNN(ref result, ref raw);
            break;
        case DS.TX_TS:
            flag = true;
            break;
        case DS.DX_DSN:
            flag = GetDateOfDSN(ref result, ref raw);
            break;
        case DS.DX_NDS:
            flag = GetDateOfNDS(ref result, ref raw);
            break;
        case DS.DX_NNDS:
            flag = GetDateOfNNDS(ref result, ref raw, dtfi);
            break;
        }
        if (!flag)
        {
            return false;
        }
        if (dps > DS.ERROR)
        {
            raw.numCount = 0;
        }
        return true;
    }
References System.DateTimeParse.GetDateOfDSN(), System.DateTimeParse.GetDateOfNDS(), System.DateTimeParse.GetDateOfNNDS(), System.DateTimeParse.GetDayOfMN(), System.DateTimeParse.GetDayOfMNN(), System.DateTimeParse.GetDayOfNM(), System.DateTimeParse.GetDayOfNN(), System.DateTimeParse.GetDayOfNNN(), System.DateTimeParse.GetDayOfNNY(), System.DateTimeParse.GetDayOfYM(), System.DateTimeParse.GetDayOfYMN(), System.DateTimeParse.GetDayOfYN(), System.DateTimeParse.GetDayOfYNN(), System.DateTimeParse.GetTimeOfN(), System.DateTimeParse.GetTimeOfNN(), and System.DateTimeParse.GetTimeOfNNN().
Referenced by System.DateTimeParse.Lex(), and System.DateTimeParse.TryParse().