Terraria: System.DateTimeParse.ParseFormatO
ParseFormatO()
static bool System.DateTimeParse.ParseFormatO (ReadOnlySpan< char > source, ref DateTimeResult result) inline static private
Definition at line 3992 of file DateTimeParse.cs.
    {
        if ((uint)source.Length < 27u || source[4] != '-' || source[7] != '-' || source[10] != 'T' || source[13] != ':' || source[16] != ':' || source[19] != '.')
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        uint num = (uint)(source[0] - 48);
        uint num2 = (uint)(source[1] - 48);
        uint num3 = (uint)(source[2] - 48);
        uint num4 = (uint)(source[3] - 48);
        if (num > 9 || num2 > 9 || num3 > 9 || num4 > 9)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        int year = (int)(num * 1000 + num2 * 100 + num3 * 10 + num4);
        uint num5 = (uint)(source[5] - 48);
        uint num6 = (uint)(source[6] - 48);
        if (num5 > 9 || num6 > 9)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        int month = (int)(num5 * 10 + num6);
        uint num7 = (uint)(source[8] - 48);
        uint num8 = (uint)(source[9] - 48);
        if (num7 > 9 || num8 > 9)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        int day = (int)(num7 * 10 + num8);
        uint num9 = (uint)(source[11] - 48);
        uint num10 = (uint)(source[12] - 48);
        if (num9 > 9 || num10 > 9)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        int hour = (int)(num9 * 10 + num10);
        uint num11 = (uint)(source[14] - 48);
        uint num12 = (uint)(source[15] - 48);
        if (num11 > 9 || num12 > 9)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        int minute = (int)(num11 * 10 + num12);
        uint num13 = (uint)(source[17] - 48);
        uint num14 = (uint)(source[18] - 48);
        if (num13 > 9 || num14 > 9)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        int second = (int)(num13 * 10 + num14);
        uint num15 = (uint)(source[20] - 48);
        uint num16 = (uint)(source[21] - 48);
        uint num17 = (uint)(source[22] - 48);
        uint num18 = (uint)(source[23] - 48);
        uint num19 = (uint)(source[24] - 48);
        uint num20 = (uint)(source[25] - 48);
        uint num21 = (uint)(source[26] - 48);
        if (num15 > 9 || num16 > 9 || num17 > 9 || num18 > 9 || num19 > 9 || num20 > 9 || num21 > 9)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        double num22 = (double)(num15 * 1000000 + num16 * 100000 + num17 * 10000 + num18 * 1000 + num19 * 100 + num20 * 10 + num21) / 10000000.0;
        if (!DateTime.TryCreate(year, month, day, hour, minute, second, 0, out var result2))
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        if (!result2.TryAddTicks((long)Math.Round(num22 * 10000000.0), out result.parsedDate))
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        if ((uint)source.Length > 27u)
        {
            char c = source[27];
            switch (c)
            {
            case 'Z':
                if (source.Length != 28)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                result.flags |= ParseFlags.TimeZoneUsed | ParseFlags.TimeZoneUtc;
                break;
            case '+':
            case '-':
            {
                int num25;
                int num26;
                if (source.Length == 33)
                {
                    uint num23 = (uint)(source[28] - 48);
                    uint num24 = (uint)(source[29] - 48);
                    if (num23 > 9 || num24 > 9)
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    num25 = (int)(num23 * 10 + num24);
                    num26 = 30;
                }
                else
                {
                    if (source.Length != 32)
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    num25 = source[28] - 48;
                    if ((uint)num25 > 9u)
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    num26 = 29;
                }
                if (source[num26] != ':')
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                uint num27 = (uint)(source[num26 + 1] - 48);
                uint num28 = (uint)(source[num26 + 2] - 48);
                if (num27 > 9 || num28 > 9)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                int minutes = (int)(num27 * 10 + num28);
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = new TimeSpan(num25, minutes, 0);
                if (c == '-')
                {
                    result.timeZoneOffset = result.timeZoneOffset.Negate();
                }
                break;
            }
            default:
                result.SetBadDateTimeFailure();
                return false;
            }
        }
        return DetermineTimeZoneAdjustments(ref result, DateTimeStyles.None, bTimeOnly: false);
    }
References System.DateTimeParse.DetermineTimeZoneAdjustments(), System.Math.Round(), System.source, System.DateTime.TryCreate(), and System.year.
Referenced by System.DateTimeParse.DoStrictParse().