Terraria: System.DateTimeParse.ProcessHebrewTerminalState
ProcessHebrewTerminalState()
static bool System.DateTimeParse.ProcessHebrewTerminalState (DS dps, ref DateTimeResult result, ref DateTimeStyles styles, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static package
Definition at line 2081 of file DateTimeParse.cs.
    {
        switch (dps)
        {
        case DS.DX_MNN:
            raw.year = raw.GetNumber(1);
            if (!dtfi.YearMonthAdjustment(ref raw.year, ref raw.month, parsedMonthName: true))
            {
                result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "Format_BadDateTimeCalendar");
                return false;
            }
            if (!GetDayOfMNN(ref result, ref raw, dtfi))
            {
                return false;
            }
            break;
        case DS.DX_YMN:
            if (!dtfi.YearMonthAdjustment(ref raw.year, ref raw.month, parsedMonthName: true))
            {
                result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "Format_BadDateTimeCalendar");
                return false;
            }
            if (!GetDayOfYMN(ref result, ref raw))
            {
                return false;
            }
            break;
        case DS.DX_NNY:
            if (raw.year < 1000)
            {
                raw.year += 5000;
            }
            if (!GetDayOfNNY(ref result, ref raw, dtfi))
            {
                return false;
            }
            if (!dtfi.YearMonthAdjustment(ref result.Year, ref raw.month, parsedMonthName: true))
            {
                result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "Format_BadDateTimeCalendar");
                return false;
            }
            break;
        case DS.DX_MN:
        case DS.DX_NM:
            GetDefaultYear(ref result, ref styles);
            if (!dtfi.YearMonthAdjustment(ref result.Year, ref raw.month, parsedMonthName: true))
            {
                result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "Format_BadDateTimeCalendar");
                return false;
            }
            if (!GetHebrewDayOfNM(ref result, ref raw, dtfi))
            {
                return false;
            }
            break;
        case DS.DX_YM:
            if (!dtfi.YearMonthAdjustment(ref raw.year, ref raw.month, parsedMonthName: true))
            {
                result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "Format_BadDateTimeCalendar");
                return false;
            }
            if (!GetDayOfYM(ref result, ref raw))
            {
                return false;
            }
            break;
        case DS.TX_N:
            if (!GetTimeOfN(ref result, ref raw))
            {
                return false;
            }
            break;
        case DS.TX_NN:
            if (!GetTimeOfNN(ref result, ref raw))
            {
                return false;
            }
            break;
        case DS.TX_NNN:
            if (!GetTimeOfNNN(ref result, ref raw))
            {
                return false;
            }
            break;
        default:
            result.SetBadDateTimeFailure();
            return false;
        }
        if (dps > DS.ERROR)
        {
            raw.numCount = 0;
        }
        return true;
    }
References System.DateTimeParse.GetDayOfMNN(), System.DateTimeParse.GetDayOfNNY(), System.DateTimeParse.GetDayOfYM(), System.DateTimeParse.GetDayOfYMN(), System.DateTimeParse.GetDefaultYear(), System.DateTimeParse.GetHebrewDayOfNM(), System.DateTimeParse.GetTimeOfN(), System.DateTimeParse.GetTimeOfNN(), and System.DateTimeParse.GetTimeOfNNN().
Referenced by System.DateTimeParse.TryParse().