Terraria: System.DateTimeParse.ParseByFormat
ParseByFormat()
static bool System.DateTimeParse.ParseByFormat (ref __DTString str, ref __DTString format, ref ParsingInfo parseInfo, DateTimeFormatInfo dtfi, ref DateTimeResult result) inline static private
Definition at line 3224 of file DateTimeParse.cs.
    {
        int result2 = 0;
        int result3 = 0;
        int result4 = 0;
        int result5 = 0;
        int result6 = 0;
        int result7 = 0;
        int result8 = 0;
        double result9 = 0.0;
        TM result10 = TM.AM;
        char @char = format.GetChar();
        switch (@char)
        {
        case 'y':
        {
            int repeatCount = format.GetRepeatCount();
            bool flag;
            if (ParseJapaneseEraStart(ref str, dtfi))
            {
                result2 = 1;
                flag = true;
            }
            else if (dtfi.HasForceTwoDigitYears)
            {
                flag = ParseDigits(ref str, 1, 4, out result2);
            }
            else
            {
                if (repeatCount <= 2)
                {
                    parseInfo.fUseTwoDigitYear = true;
                }
                flag = ParseDigits(ref str, repeatCount, out result2);
            }
            if (!flag && parseInfo.fCustomNumberParser)
            {
                flag = parseInfo.parseNumberDelegate(ref str, repeatCount, out result2);
            }
            if (!flag)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (!CheckNewValue(ref result.Year, result2, @char, ref result))
            {
                return false;
            }
            break;
        }
        case 'M':
        {
            int repeatCount = format.GetRepeatCount();
            if (repeatCount <= 2)
            {
                if (!ParseDigits(ref str, repeatCount, out result3) && (!parseInfo.fCustomNumberParser || !parseInfo.parseNumberDelegate(ref str, repeatCount, out result3)))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            else
            {
                if (repeatCount == 3)
                {
                    if (!MatchAbbreviatedMonthName(ref str, dtfi, ref result3))
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                }
                else if (!MatchMonthName(ref str, dtfi, ref result3))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                result.flags |= ParseFlags.ParsedMonthName;
            }
            if (!CheckNewValue(ref result.Month, result3, @char, ref result))
            {
                return false;
            }
            break;
        }
        case 'd':
        {
            int repeatCount = format.GetRepeatCount();
            if (repeatCount <= 2)
            {
                if (!ParseDigits(ref str, repeatCount, out result4) && (!parseInfo.fCustomNumberParser || !parseInfo.parseNumberDelegate(ref str, repeatCount, out result4)))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if (!CheckNewValue(ref result.Day, result4, @char, ref result))
                {
                    return false;
                }
                break;
            }
            if (repeatCount == 3)
            {
                if (!MatchAbbreviatedDayName(ref str, dtfi, ref result5))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            else if (!MatchDayName(ref str, dtfi, ref result5))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (!CheckNewValue(ref parseInfo.dayOfWeek, result5, @char, ref result))
            {
                return false;
            }
            break;
        }
        case 'g':
            format.GetRepeatCount();
            if (!MatchEraName(ref str, dtfi, ref result.era))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            break;
        case 'h':
        {
            parseInfo.fUseHour12 = true;
            int repeatCount = format.GetRepeatCount();
            if (!ParseDigits(ref str, (repeatCount < 2) ? 1 : 2, out result6))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (!CheckNewValue(ref result.Hour, result6, @char, ref result))
            {
                return false;
            }
            break;
        }
        case 'H':
        {
            int repeatCount = format.GetRepeatCount();
            if (!ParseDigits(ref str, (repeatCount < 2) ? 1 : 2, out result6))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (!CheckNewValue(ref result.Hour, result6, @char, ref result))
            {
                return false;
            }
            break;
        }
        case 'm':
        {
            int repeatCount = format.GetRepeatCount();
            if (!ParseDigits(ref str, (repeatCount < 2) ? 1 : 2, out result7))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (!CheckNewValue(ref result.Minute, result7, @char, ref result))
            {
                return false;
            }
            break;
        }
        case 's':
        {
            int repeatCount = format.GetRepeatCount();
            if (!ParseDigits(ref str, (repeatCount < 2) ? 1 : 2, out result8))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (!CheckNewValue(ref result.Second, result8, @char, ref result))
            {
                return false;
            }
            break;
        }
        case 'F':
        case 'f':
        {
            int repeatCount = format.GetRepeatCount();
            if (repeatCount <= 7)
            {
                if (!ParseFractionExact(ref str, repeatCount, ref result9) && @char == 'f')
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if (result.fraction < 0.0)
                {
                    result.fraction = result9;
                }
                else if (result9 != result.fraction)
                {
                    result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_RepeatDateTimePattern", @char);
                    return false;
                }
                break;
            }
            result.SetBadDateTimeFailure();
            return false;
        }
        case 't':
        {
            int repeatCount = format.GetRepeatCount();
            if (repeatCount == 1)
            {
                if (!MatchAbbreviatedTimeMark(ref str, dtfi, ref result10))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            else if (!MatchTimeMark(ref str, dtfi, ref result10))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (parseInfo.timeMark == TM.NotSet)
            {
                parseInfo.timeMark = result10;
            }
            else if (parseInfo.timeMark != result10)
            {
                result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_RepeatDateTimePattern", @char);
                return false;
            }
            break;
        }
        case 'z':
        {
            int repeatCount = format.GetRepeatCount();
            TimeSpan result11 = new TimeSpan(0L);
            if (!ParseTimeZoneOffset(ref str, repeatCount, ref result11))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if ((result.flags & ParseFlags.TimeZoneUsed) != 0 && result11 != result.timeZoneOffset)
            {
                result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_RepeatDateTimePattern", 'z');
                return false;
            }
            result.timeZoneOffset = result11;
            result.flags |= ParseFlags.TimeZoneUsed;
            break;
        }
        case 'Z':
            if ((result.flags & ParseFlags.TimeZoneUsed) != 0 && result.timeZoneOffset != TimeSpan.Zero)
            {
                result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_RepeatDateTimePattern", 'Z');
                return false;
            }
            result.flags |= ParseFlags.TimeZoneUsed;
            result.timeZoneOffset = new TimeSpan(0L);
            result.flags |= ParseFlags.TimeZoneUtc;
            str.Index++;
            if (!GetTimeZoneName(ref str))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            str.Index--;
            break;
        case 'K':
            if (str.Match('Z'))
            {
                if ((result.flags & ParseFlags.TimeZoneUsed) != 0 && result.timeZoneOffset != TimeSpan.Zero)
                {
                    result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_RepeatDateTimePattern", 'K');
                    return false;
                }
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = new TimeSpan(0L);
                result.flags |= ParseFlags.TimeZoneUtc;
            }
            else if (str.Match('+') || str.Match('-'))
            {
                str.Index--;
                TimeSpan result12 = new TimeSpan(0L);
                if (!ParseTimeZoneOffset(ref str, 3, ref result12))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                if ((result.flags & ParseFlags.TimeZoneUsed) != 0 && result12 != result.timeZoneOffset)
                {
                    result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_RepeatDateTimePattern", 'K');
                    return false;
                }
                result.timeZoneOffset = result12;
                result.flags |= ParseFlags.TimeZoneUsed;
            }
            break;
        case ':':
            if (((dtfi.TimeSeparator.Length > 1 && dtfi.TimeSeparator[0] == ':') || !str.Match(':')) && !str.Match(dtfi.TimeSeparator))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            break;
        case '/':
            if (((dtfi.DateSeparator.Length > 1 && dtfi.DateSeparator[0] == '/') || !str.Match('/')) && !str.Match(dtfi.DateSeparator))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            break;
        case '"':
        case '\'':
        {
            StringBuilder stringBuilder = StringBuilderCache.Acquire();
            if (!TryParseQuoteString(format.Value, format.Index, stringBuilder, out var repeatCount))
            {
                result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_BadQuote", @char);
                StringBuilderCache.Release(stringBuilder);
                return false;
            }
            format.Index += repeatCount - 1;
            string stringAndRelease = StringBuilderCache.GetStringAndRelease(stringBuilder);
            for (int i = 0; i < stringAndRelease.Length; i++)
            {
                if (stringAndRelease[i] == ' ' && parseInfo.fAllowInnerWhite)
                {
                    str.SkipWhiteSpaces();
                }
                else if (!str.Match(stringAndRelease[i]))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            if ((result.flags & ParseFlags.CaptureOffset) != 0 && (((result.flags & ParseFlags.Rfc1123Pattern) != 0 && stringAndRelease == "GMT") || ((result.flags & ParseFlags.UtcSortPattern) != 0 && stringAndRelease == "Z")))
            {
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = TimeSpan.Zero;
            }
            break;
        }
        case '%':
            if (format.Index >= format.Value.Length - 1 || format.Value[format.Index + 1] == '%')
            {
                result.SetBadFormatSpecifierFailure(format.Value);
                return false;
            }
            break;
        case '\\':
            if (format.GetNext())
            {
                if (!str.Match(format.GetChar()))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                break;
            }
            result.SetBadFormatSpecifierFailure(format.Value);
            return false;
        case '.':
            if (!str.Match(@char))
            {
                if (!format.GetNext() || !format.Match('F'))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                format.GetRepeatCount();
            }
            break;
        default:
            if (@char == ' ')
            {
                if (!parseInfo.fAllowInnerWhite && !str.Match(@char))
                {
                    if (parseInfo.fAllowTrailingWhite && format.GetNext() && ParseByFormat(ref str, ref format, ref parseInfo, dtfi, ref result))
                    {
                        return true;
                    }
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            else if (format.MatchSpecifiedWord("GMT"))
            {
                format.Index += "GMT".Length - 1;
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = TimeSpan.Zero;
                if (!str.Match("GMT"))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
            }
            else if (!str.Match(@char))
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            break;
        }
        return true;
    }
References System.Text.StringBuilderCache.Acquire(), System.DateTimeParse.CheckNewValue(), System.Globalization.DateTimeFormatInfo.DateSeparator, System.format, System.Text.StringBuilderCache.GetStringAndRelease(), System.DateTimeParse.GetTimeZoneName(), System.L, System.DateTimeParse.MatchAbbreviatedDayName(), System.DateTimeParse.MatchAbbreviatedMonthName(), System.DateTimeParse.MatchAbbreviatedTimeMark(), System.DateTimeParse.MatchDayName(), System.DateTimeParse.MatchEraName(), System.DateTimeParse.MatchMonthName(), System.DateTimeParse.MatchTimeMark(), System.DateTimeParse.ParseByFormat(), System.DateTimeParse.ParseDigits(), System.DateTimeParse.ParseFractionExact(), System.DateTimeParse.ParseJapaneseEraStart(), System.DateTimeParse.ParseTimeZoneOffset(), System.Text.StringBuilderCache.Release(), System.str, System.DateTimeParse.TryParseQuoteString(), and System.TimeSpan.Zero.
Referenced by System.DateTimeParse.DoStrictParse(), and System.DateTimeParse.ParseByFormat().