Terraria: System.DateTimeParse.ParseExactMultiple
ParseExactMultiple() [1/2]
static DateTime System.DateTimeParse.ParseExactMultiple (ReadOnlySpan< char > s, string[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style) inline static package
Definition at line 580 of file DateTimeParse.cs.
    {
        DateTimeResult result = default(DateTimeResult);
        result.Init(s);
        if (TryParseExactMultiple(s, formats, dtfi, style, ref result))
        {
            return result.parsedDate;
        }
        throw GetDateTimeParseException(ref result);
    }
References System.formats, System.DateTimeParse.GetDateTimeParseException(), System.DateTimeResult.Init(), System.DateTimeResult.parsedDate, System.s, and System.DateTimeParse.TryParseExactMultiple().
Referenced by System.DateTimeOffset.ParseExact(), System.DateTime.ParseExact(), System.DateTimeOffset.ParseExact(), and System.DateTime.ParseExact().