Terraria: System.DateTimeParse.GetDayOfMNN
GetDayOfMNN()
static bool System.DateTimeParse.GetDayOfMNN (ref DateTimeResult result, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static private
Definition at line 1704 of file DateTimeParse.cs.
    {
        if ((result.flags & ParseFlags.HaveDate) != 0)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        int number = raw.GetNumber(0);
        int number2 = raw.GetNumber(1);
        if (!GetYearMonthDayOrder(dtfi.ShortDatePattern, out var order))
        {
            result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_BadDatePattern", dtfi.ShortDatePattern);
            return false;
        }
        int adjustedYear;
        switch (order)
        {
        case 1:
            if (TryAdjustYear(ref result, number2, out adjustedYear) && result.calendar.IsValidDay(adjustedYear, raw.month, number, result.era))
            {
                result.SetDate(adjustedYear, raw.month, number);
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            if (TryAdjustYear(ref result, number, out adjustedYear) && result.calendar.IsValidDay(adjustedYear, raw.month, number2, result.era))
            {
                result.SetDate(adjustedYear, raw.month, number2);
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            break;
        case 0:
            if (TryAdjustYear(ref result, number, out adjustedYear) && result.calendar.IsValidDay(adjustedYear, raw.month, number2, result.era))
            {
                result.SetDate(adjustedYear, raw.month, number2);
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            if (TryAdjustYear(ref result, number2, out adjustedYear) && result.calendar.IsValidDay(adjustedYear, raw.month, number, result.era))
            {
                result.SetDate(adjustedYear, raw.month, number);
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            break;
        case 2:
            if (TryAdjustYear(ref result, number2, out adjustedYear) && result.calendar.IsValidDay(adjustedYear, raw.month, number, result.era))
            {
                result.SetDate(adjustedYear, raw.month, number);
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            if (TryAdjustYear(ref result, number, out adjustedYear) && result.calendar.IsValidDay(adjustedYear, raw.month, number2, result.era))
            {
                result.SetDate(adjustedYear, raw.month, number2);
                result.flags |= ParseFlags.HaveDate;
                return true;
            }
            break;
        }
        result.SetBadDateTimeFailure();
        return false;
    }
References System.DateTimeParse.GetYearMonthDayOrder(), System.Globalization.DateTimeFormatInfo.ShortDatePattern, and System.DateTimeParse.TryAdjustYear().
Referenced by System.DateTimeParse.ProcessHebrewTerminalState(), and System.DateTimeParse.ProcessTerminalState().