Terraria: System.DateTimeParse.GetDayOfNM
GetDayOfNM()
static bool System.DateTimeParse.GetDayOfNM (ref DateTimeResult result, ref DateTimeStyles styles, ref DateTimeRawInfo raw, DateTimeFormatInfo dtfi) inline static private
Definition at line 1666 of file DateTimeParse.cs.
    {
        if ((result.flags & ParseFlags.HaveDate) != 0)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        if (!GetMonthDayOrder(dtfi.MonthDayPattern, out var order))
        {
            result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_BadDatePattern", dtfi.MonthDayPattern);
            return false;
        }
        if (order == 6)
        {
            if (!GetYearMonthOrder(dtfi.YearMonthPattern, out var order2))
            {
                result.SetFailure(ParseFailureKind.FormatWithParameter, "Format_BadDatePattern", dtfi.YearMonthPattern);
                return false;
            }
            if (order2 == 4)
            {
                if (!TryAdjustYear(ref result, raw.GetNumber(0), out var adjustedYear) || !SetDateYMD(ref result, adjustedYear, raw.month, 1))
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                return true;
            }
        }
        GetDefaultYear(ref result, ref styles);
        if (!SetDateYMD(ref result, result.Year, raw.month, raw.GetNumber(0)))
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        return true;
    }
References System.DateTimeParse.GetDefaultYear(), System.DateTimeParse.GetMonthDayOrder(), System.DateTimeParse.GetYearMonthOrder(), System.Globalization.DateTimeFormatInfo.MonthDayPattern, System.DateTimeParse.SetDateYMD(), and System.DateTimeParse.TryAdjustYear().
Referenced by System.DateTimeParse.ProcessTerminalState().