Terraria: System.DateTimeParse.GetMonthDayOrder
GetMonthDayOrder()
static bool System.DateTimeParse.GetMonthDayOrder (string pattern, out int order) inline static private
Definition at line 1418 of file DateTimeParse.cs.
    {
        int num = -1;
        int num2 = -1;
        int num3 = 0;
        bool flag = false;
        for (int i = 0; i < pattern.Length && num3 < 2; i++)
        {
            char c = pattern[i];
            switch (c)
            {
            case '%':
            case '\\':
                i++;
                continue;
            case '"':
            case '\'':
                flag = !flag;
                break;
            }
            if (flag)
            {
                continue;
            }
            switch (c)
            {
            case 'd':
            {
                int num4 = 1;
                for (; i + 1 < pattern.Length && pattern[i + 1] == 'd'; i++)
                {
                    num4++;
                }
                if (num4 <= 2)
                {
                    num2 = num3++;
                }
                break;
            }
            case 'M':
                num = num3++;
                for (; i + 1 < pattern.Length && pattern[i + 1] == 'M'; i++)
                {
                }
                break;
            }
        }
        if (num == 0 && num2 == 1)
        {
            order = 6;
            return true;
        }
        if (num2 == 0 && num == 1)
        {
            order = 7;
            return true;
        }
        order = -1;
        return false;
    }
Referenced by System.DateTimeParse.GetDayOfMN(), System.DateTimeParse.GetDayOfNM(), System.DateTimeParse.GetDayOfNN(), and System.DateTimeParse.GetHebrewDayOfNM().