Terraria: System.DateTimeParse.Lex
Lex()
static bool System.DateTimeParse.Lex (DS dps, ref __DTString str, ref DateTimeToken dtok, ref DateTimeRawInfo raw, ref DateTimeResult result, ref DateTimeFormatInfo dtfi, DateTimeStyles styles) inline static private
Definition at line 822 of file DateTimeParse.cs.
    {
        dtok.dtt = DTT.Unk;
        str.GetRegularToken(out var tokenType, out var tokenValue, dtfi);
        int indexBeforeSeparator;
        char charBeforeSeparator;
        switch (tokenType)
        {
        case TokenType.NumberToken:
        case TokenType.YearNumberToken:
        {
            if (raw.numCount == 3 || tokenValue == -1)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (dps == DS.T_NNt && str.Index < str.Length - 1)
            {
                char c = str.Value[str.Index];
                if (c == '.')
                {
                    ParseFraction(ref str, out raw.fraction);
                }
            }
            if ((dps == DS.T_NNt || dps == DS.T_Nt) && str.Index < str.Length - 1 && !HandleTimeZone(ref str, ref result))
            {
                return false;
            }
            dtok.num = tokenValue;
            TokenType separatorToken;
            if (tokenType == TokenType.YearNumberToken)
            {
                if (raw.year == -1)
                {
                    raw.year = tokenValue;
                    switch (separatorToken = str.GetSeparatorToken(dtfi, out indexBeforeSeparator, out charBeforeSeparator))
                    {
                    case TokenType.SEP_End:
                        dtok.dtt = DTT.YearEnd;
                        break;
                    case TokenType.SEP_Am:
                    case TokenType.SEP_Pm:
                        if (raw.timeMark == TM.NotSet)
{
                            raw.timeMark = ((separatorToken != TokenType.SEP_Am) ? TM.PM : TM.AM);
                            dtok.dtt = DTT.YearSpace;
                        }
                        else
{
                            result.SetBadDateTimeFailure();
                        }
                        break;
                    case TokenType.SEP_Space:
                        dtok.dtt = DTT.YearSpace;
                        break;
                    case TokenType.SEP_Date:
                        dtok.dtt = DTT.YearDateSep;
                        break;
                    case TokenType.SEP_Time:
                        if (!raw.hasSameDateAndTimeSeparators)
{
                            result.SetBadDateTimeFailure();
                            return false;
                        }
                        dtok.dtt = DTT.YearDateSep;
                        break;
                    case TokenType.SEP_DateOrOffset:
                        if (s_dateParsingStates[(int)dps][13] == DS.ERROR && s_dateParsingStates[(int)dps][12] > DS.ERROR)
{
                            str.Index = indexBeforeSeparator;
                            str.m_current = charBeforeSeparator;
                            dtok.dtt = DTT.YearSpace;
                        }
                        else
{
                            dtok.dtt = DTT.YearDateSep;
                        }
                        break;
                    case TokenType.SEP_YearSuff:
                    case TokenType.SEP_MonthSuff:
                    case TokenType.SEP_DaySuff:
                        dtok.dtt = DTT.NumDatesuff;
                        dtok.suffix = separatorToken;
                        break;
                    case TokenType.SEP_HourSuff:
                    case TokenType.SEP_MinuteSuff:
                    case TokenType.SEP_SecondSuff:
                        dtok.dtt = DTT.NumTimesuff;
                        dtok.suffix = separatorToken;
                        break;
                    default:
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    return true;
                }
                result.SetBadDateTimeFailure();
                return false;
            }
            switch (separatorToken = str.GetSeparatorToken(dtfi, out indexBeforeSeparator, out charBeforeSeparator))
            {
            case TokenType.SEP_End:
                dtok.dtt = DTT.NumEnd;
                raw.AddNumber(dtok.num);
                break;
            case TokenType.SEP_Am:
            case TokenType.SEP_Pm:
                if (raw.timeMark == TM.NotSet)
                {
                    raw.timeMark = ((separatorToken != TokenType.SEP_Am) ? TM.PM : TM.AM);
                    dtok.dtt = DTT.NumAmpm;
                    if (dps == DS.D_NN && !ProcessTerminalState(DS.DX_NN, ref result, ref styles, ref raw, dtfi))
                    {
                        return false;
                    }
                    raw.AddNumber(dtok.num);
                    if ((dps == DS.T_NNt || dps == DS.T_Nt) && !HandleTimeZone(ref str, ref result))
                    {
                        return false;
                    }
                }
                else
                {
                    result.SetBadDateTimeFailure();
                }
                break;
            case TokenType.SEP_Space:
                dtok.dtt = DTT.NumSpace;
                raw.AddNumber(dtok.num);
                break;
            case TokenType.SEP_Date:
                dtok.dtt = DTT.NumDatesep;
                raw.AddNumber(dtok.num);
                break;
            case TokenType.SEP_DateOrOffset:
                if (s_dateParsingStates[(int)dps][4] == DS.ERROR && s_dateParsingStates[(int)dps][3] > DS.ERROR)
                {
                    str.Index = indexBeforeSeparator;
                    str.m_current = charBeforeSeparator;
                    dtok.dtt = DTT.NumSpace;
                }
                else
                {
                    dtok.dtt = DTT.NumDatesep;
                }
                raw.AddNumber(dtok.num);
                break;
            case TokenType.SEP_Time:
                if (raw.hasSameDateAndTimeSeparators && (dps == DS.D_Y || dps == DS.D_YN || dps == DS.D_YNd || dps == DS.D_YM || dps == DS.D_YMd))
                {
                    dtok.dtt = DTT.NumDatesep;
                    raw.AddNumber(dtok.num);
                }
                else
                {
                    dtok.dtt = DTT.NumTimesep;
                    raw.AddNumber(dtok.num);
                }
                break;
            case TokenType.SEP_YearSuff:
                try
                {
                    dtok.num = dtfi.Calendar.ToFourDigitYear(tokenValue);
                }
                catch (ArgumentOutOfRangeException)
                {
                    result.SetBadDateTimeFailure();
                    return false;
                }
                dtok.dtt = DTT.NumDatesuff;
                dtok.suffix = separatorToken;
                break;
            case TokenType.SEP_MonthSuff:
            case TokenType.SEP_DaySuff:
                dtok.dtt = DTT.NumDatesuff;
                dtok.suffix = separatorToken;
                break;
            case TokenType.SEP_HourSuff:
            case TokenType.SEP_MinuteSuff:
            case TokenType.SEP_SecondSuff:
                dtok.dtt = DTT.NumTimesuff;
                dtok.suffix = separatorToken;
                break;
            case TokenType.SEP_LocalTimeMark:
                dtok.dtt = DTT.NumLocalTimeMark;
                raw.AddNumber(dtok.num);
                break;
            default:
                result.SetBadDateTimeFailure();
                return false;
            }
            break;
        }
        case TokenType.HebrewNumber:
        {
            TokenType separatorToken;
            if (tokenValue >= 100)
            {
                if (raw.year == -1)
                {
                    raw.year = tokenValue;
                    TokenType tokenType2 = (separatorToken = str.GetSeparatorToken(dtfi, out indexBeforeSeparator, out charBeforeSeparator));
                    if (tokenType2 != TokenType.SEP_End)
                    {
                        if (tokenType2 != TokenType.SEP_Space)
{
                            if (tokenType2 != TokenType.SEP_DateOrOffset || s_dateParsingStates[(int)dps][12] <= DS.ERROR)
{
                                result.SetBadDateTimeFailure();
                                return false;
                            }
                            str.Index = indexBeforeSeparator;
                            str.m_current = charBeforeSeparator;
                            dtok.dtt = DTT.YearSpace;
                        }
                        else
{
                            dtok.dtt = DTT.YearSpace;
                        }
                    }
                    else
                    {
                        dtok.dtt = DTT.YearEnd;
                    }
                    break;
                }
                result.SetBadDateTimeFailure();
                return false;
            }
            dtok.num = tokenValue;
            raw.AddNumber(dtok.num);
            switch (separatorToken = str.GetSeparatorToken(dtfi, out indexBeforeSeparator, out charBeforeSeparator))
            {
            case TokenType.SEP_End:
                dtok.dtt = DTT.NumEnd;
                break;
            case TokenType.SEP_Space:
            case TokenType.SEP_Date:
                dtok.dtt = DTT.NumDatesep;
                break;
            case TokenType.SEP_DateOrOffset:
                if (s_dateParsingStates[(int)dps][4] == DS.ERROR && s_dateParsingStates[(int)dps][3] > DS.ERROR)
                {
                    str.Index = indexBeforeSeparator;
                    str.m_current = charBeforeSeparator;
                    dtok.dtt = DTT.NumSpace;
                }
                else
                {
                    dtok.dtt = DTT.NumDatesep;
                }
                break;
            default:
                result.SetBadDateTimeFailure();
                return false;
            }
            break;
        }
        case TokenType.DayOfWeekToken:
            if (raw.dayOfWeek == -1)
            {
                raw.dayOfWeek = tokenValue;
                dtok.dtt = DTT.DayOfWeek;
                break;
            }
            result.SetBadDateTimeFailure();
            return false;
        case TokenType.MonthToken:
            if (raw.month == -1)
            {
                TokenType separatorToken;
                switch (separatorToken = str.GetSeparatorToken(dtfi, out indexBeforeSeparator, out charBeforeSeparator))
                {
                case TokenType.SEP_End:
                    dtok.dtt = DTT.MonthEnd;
                    break;
                case TokenType.SEP_Space:
                    dtok.dtt = DTT.MonthSpace;
                    break;
                case TokenType.SEP_Date:
                    dtok.dtt = DTT.MonthDatesep;
                    break;
                case TokenType.SEP_Time:
                    if (!raw.hasSameDateAndTimeSeparators)
                    {
                        result.SetBadDateTimeFailure();
                        return false;
                    }
                    dtok.dtt = DTT.MonthDatesep;
                    break;
                case TokenType.SEP_DateOrOffset:
                    if (s_dateParsingStates[(int)dps][8] == DS.ERROR && s_dateParsingStates[(int)dps][7] > DS.ERROR)
                    {
                        str.Index = indexBeforeSeparator;
                        str.m_current = charBeforeSeparator;
                        dtok.dtt = DTT.MonthSpace;
                    }
                    else
                    {
                        dtok.dtt = DTT.MonthDatesep;
                    }
                    break;
                default:
                    result.SetBadDateTimeFailure();
                    return false;
                }
                raw.month = tokenValue;
                break;
            }
            result.SetBadDateTimeFailure();
            return false;
        case TokenType.EraToken:
            if (result.era != -1)
            {
                result.era = tokenValue;
                dtok.dtt = DTT.Era;
                break;
            }
            result.SetBadDateTimeFailure();
            return false;
        case TokenType.JapaneseEraToken:
            if (GlobalizationMode.Invariant)
            {
                return false;
            }
            result.calendar = JapaneseCalendar.GetDefaultInstance();
            dtfi = DateTimeFormatInfo.GetJapaneseCalendarDTFI();
            if (result.era != -1)
            {
                result.era = tokenValue;
                dtok.dtt = DTT.Era;
                break;
            }
            result.SetBadDateTimeFailure();
            return false;
        case TokenType.TEraToken:
            if (GlobalizationMode.Invariant)
            {
                return false;
            }
            result.calendar = TaiwanCalendar.GetDefaultInstance();
            dtfi = DateTimeFormatInfo.GetTaiwanCalendarDTFI();
            if (result.era != -1)
            {
                result.era = tokenValue;
                dtok.dtt = DTT.Era;
                break;
            }
            result.SetBadDateTimeFailure();
            return false;
        case TokenType.TimeZoneToken:
            if ((result.flags & ParseFlags.TimeZoneUsed) != 0)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            dtok.dtt = DTT.TimeZone;
            result.flags |= ParseFlags.TimeZoneUsed;
            result.timeZoneOffset = new TimeSpan(0L);
            result.flags |= ParseFlags.TimeZoneUtc;
            break;
        case TokenType.EndOfString:
            dtok.dtt = DTT.End;
            break;
        case TokenType.Am:
        case TokenType.Pm:
            if (raw.timeMark == TM.NotSet)
            {
                raw.timeMark = (TM)tokenValue;
                break;
            }
            result.SetBadDateTimeFailure();
            return false;
        case TokenType.UnknownToken:
            if (char.IsLetter(str.m_current))
            {
                result.SetFailure(ParseFailureKind.FormatWithOriginalDateTimeAndParameter, "Format_UnknownDateTimeWord", str.Index);
                return false;
            }
            if ((str.m_current == '-' || str.m_current == '+') && (result.flags & ParseFlags.TimeZoneUsed) == 0)
            {
                int index = str.Index;
                if (ParseTimeZone(ref str, ref result.timeZoneOffset))
                {
                    result.flags |= ParseFlags.TimeZoneUsed;
                    return true;
                }
                str.Index = index;
            }
            if (VerifyValidPunctuation(ref str))
            {
                return true;
            }
            result.SetBadDateTimeFailure();
            return false;
        }
        return true;
    }
References System.Globalization.JapaneseCalendar.GetDefaultInstance(), System.Globalization.TaiwanCalendar.GetDefaultInstance(), System.DateTimeParse.HandleTimeZone(), System.index, System.Globalization.GlobalizationMode.Invariant, System.L, System.DateTimeParse.ParseFraction(), System.DateTimeParse.ParseTimeZone(), System.DateTimeParse.ProcessTerminalState(), System.DateTimeParse.s_dateParsingStates, System.str, and System.DateTimeParse.VerifyValidPunctuation().
Referenced by System.DateTimeParse.TryParse().