Terraria: System.DateTimeParse.DateTimeOffsetTimeZonePostProcessing
DateTimeOffsetTimeZonePostProcessing()
static bool System.DateTimeParse.DateTimeOffsetTimeZonePostProcessing (ref DateTimeResult result, DateTimeStyles styles) inline static private
Definition at line 2495 of file DateTimeParse.cs.
    {
        if ((result.flags & ParseFlags.TimeZoneUsed) == 0)
        {
            if ((styles & DateTimeStyles.AssumeUniversal) != 0)
            {
                result.timeZoneOffset = TimeSpan.Zero;
            }
            else
            {
                result.timeZoneOffset = TimeZoneInfo.GetLocalUtcOffset(result.parsedDate, TimeZoneInfoOptions.NoThrowOnInvalidTime);
            }
        }
        long ticks = result.timeZoneOffset.Ticks;
        long num = result.parsedDate.Ticks - ticks;
        if (num < 0 || num > 3155378975999999999L)
        {
            result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "Format_UTCOutOfRange");
            return false;
        }
        if (ticks < -504000000000L || ticks > 504000000000L)
        {
            result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "Format_OffsetOutOfRange");
            return false;
        }
        if ((styles & DateTimeStyles.AdjustToUniversal) != 0)
        {
            if ((result.flags & ParseFlags.TimeZoneUsed) == 0 && (styles & DateTimeStyles.AssumeUniversal) == 0)
            {
                bool result2 = AdjustTimeZoneToUniversal(ref result);
                result.timeZoneOffset = TimeSpan.Zero;
                return result2;
            }
            result.parsedDate = new DateTime(num, DateTimeKind.Utc);
            result.timeZoneOffset = TimeSpan.Zero;
        }
        return true;
    }
References System.DateTimeParse.AdjustTimeZoneToUniversal(), System.DateTime, System.TimeZoneInfo.GetLocalUtcOffset(), System.L, and System.TimeSpan.Zero.
Referenced by System.DateTimeParse.DetermineTimeZoneAdjustments().