Terraria: System.DateTimeParse.DetermineTimeZoneAdjustments
DetermineTimeZoneAdjustments()
static bool System.DateTimeParse.DetermineTimeZoneAdjustments (ref DateTimeResult result, DateTimeStyles styles, bool bTimeOnly) inline static private
Definition at line 2444 of file DateTimeParse.cs.
    {
        if ((result.flags & ParseFlags.CaptureOffset) != 0)
        {
            return DateTimeOffsetTimeZonePostProcessing(ref result, styles);
        }
        long ticks = result.timeZoneOffset.Ticks;
        if (ticks < -504000000000L || ticks > 504000000000L)
        {
            result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "Format_OffsetOutOfRange");
            return false;
        }
        if ((result.flags & ParseFlags.TimeZoneUsed) == 0)
        {
            if ((styles & DateTimeStyles.AssumeLocal) != 0)
            {
                if ((styles & DateTimeStyles.AdjustToUniversal) == 0)
                {
                    result.parsedDate = DateTime.SpecifyKind(result.parsedDate, DateTimeKind.Local);
                    return true;
                }
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = TimeZoneInfo.GetLocalUtcOffset(result.parsedDate, TimeZoneInfoOptions.NoThrowOnInvalidTime);
            }
            else
            {
                if ((styles & DateTimeStyles.AssumeUniversal) == 0)
                {
                    return true;
                }
                if ((styles & DateTimeStyles.AdjustToUniversal) != 0)
                {
                    result.parsedDate = DateTime.SpecifyKind(result.parsedDate, DateTimeKind.Utc);
                    return true;
                }
                result.flags |= ParseFlags.TimeZoneUsed;
                result.timeZoneOffset = TimeSpan.Zero;
            }
        }
        if ((styles & DateTimeStyles.RoundtripKind) != 0 && (result.flags & ParseFlags.TimeZoneUtc) != 0)
        {
            result.parsedDate = DateTime.SpecifyKind(result.parsedDate, DateTimeKind.Utc);
            return true;
        }
        if ((styles & DateTimeStyles.AdjustToUniversal) != 0)
        {
            return AdjustTimeZoneToUniversal(ref result);
        }
        return AdjustTimeZoneToLocal(ref result, bTimeOnly);
    }
References System.DateTimeParse.AdjustTimeZoneToLocal(), System.DateTimeParse.AdjustTimeZoneToUniversal(), System.DateTimeParse.DateTimeOffsetTimeZonePostProcessing(), System.TimeZoneInfo.GetLocalUtcOffset(), System.L, System.DateTime.SpecifyKind(), and System.TimeSpan.Zero.
Referenced by System.DateTimeParse.DoStrictParse(), System.DateTimeParse.ParseFormatO(), System.DateTimeParse.ParseISO8601(), and System.DateTimeParse.TryParse().