Terraria: System.Net.Http.HttpTelemetry.Log
Log
readonly HttpTelemetry System.Net.Http.HttpTelemetry.Log = new HttpTelemetry() static
Definition at line 10 of file HttpTelemetry.cs.
Referenced by System.Net.Http.Http2Connection.Http2Connection(), System.Net.Http.HttpConnection.HttpConnection(), System.Net.Http.HttpConnection.Dispose(), System.Net.Http.Http2Connection.FinalTeardown(), System.Net.Http.HttpClient.FinishSend(), System.Net.Http.HttpClient.GetByteArrayAsyncCore(), System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(), System.Net.Http.HttpClient.GetStringAsyncCore(), System.Net.Http.HttpMessageInvoker.LogRequestFailed(), System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(), System.Net.Http.HttpMessageInvoker.Send(), System.Net.Http.HttpClient.Send(), System.Net.Http.HttpMessageInvoker.SendAsync(), System.Net.Http.HttpClient.SendAsync(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.Http.Http2Connection.SendHeadersAsync(), System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(), System.Net.Http.HttpConnection.SendRequestContentAsync(), System.Net.Http.HttpMessageInvoker.ShouldSendWithTelemetry(), and System.Net.Http.HttpClient.StartSend().