Terraria: System.DateTimeParse.TryParseQuoteString
TryParseQuoteString()
static bool System.DateTimeParse.TryParseQuoteString (ReadOnlySpan< char > format, int pos, StringBuilder result, out int returnValue) inline static package
Definition at line 3634 of file DateTimeParse.cs.
    {
        returnValue = 0;
        int length = format.Length;
        int num = pos;
        char c = format[pos++];
        bool flag = false;
        while (pos < length)
        {
            char c2 = format[pos++];
            if (c2 == c)
            {
                flag = true;
                break;
            }
            if (c2 == '\\')
            {
                if (pos >= length)
                {
                    return false;
                }
                result.Append(format[pos++]);
            }
            else
            {
                result.Append(c2);
            }
        }
        if (!flag)
        {
            return false;
        }
        returnValue = pos - num;
        return true;
    }
References System.Text.StringBuilder.Append(), System.format, and System.length.
Referenced by System.DateTimeParse.ParseByFormat(), and System.Globalization.TimeSpanParse.TryParseByFormat().