Terraria: System.DateTimeParse.DoStrictParse
DoStrictParse()
static bool System.DateTimeParse.DoStrictParse (ReadOnlySpan< char > s, ReadOnlySpan< char > formatParam, DateTimeStyles styles, DateTimeFormatInfo dtfi, ref DateTimeResult result) inline static private
Definition at line 3670 of file DateTimeParse.cs.
    {
        ParsingInfo parseInfo = default(ParsingInfo);
        parseInfo.Init();
        parseInfo.calendar = dtfi.Calendar;
        parseInfo.fAllowInnerWhite = (styles & DateTimeStyles.AllowInnerWhite) != 0;
        parseInfo.fAllowTrailingWhite = (styles & DateTimeStyles.AllowTrailingWhite) != 0;
        if (formatParam.Length == 1)
        {
            char c = formatParam[0];
            if (styles == DateTimeStyles.None)
            {
                switch (c)
                {
                case 'R':
                case 'r':
                    ConfigureFormatR(ref dtfi, ref parseInfo, ref result);
                    return ParseFormatR(s, ref parseInfo, ref result);
                case 'O':
                case 'o':
                    ConfigureFormatOS(ref dtfi, ref parseInfo);
                    return ParseFormatO(s, ref result);
                }
            }
            if ((result.flags & ParseFlags.CaptureOffset) != 0 && c == 'U')
            {
                result.SetBadFormatSpecifierFailure(formatParam);
                return false;
            }
            formatParam = ExpandPredefinedFormat(formatParam, ref dtfi, ref parseInfo, ref result);
        }
        result.calendar = parseInfo.calendar;
        if (parseInfo.calendar.ID == CalendarId.HEBREW)
        {
            parseInfo.parseNumberDelegate = s_hebrewNumberParser;
            parseInfo.fCustomNumberParser = true;
        }
        result.Hour = (result.Minute = (result.Second = -1));
        __DTString format = new __DTString(formatParam, dtfi, checkDigitToken: false);
        __DTString str = new __DTString(s, dtfi, checkDigitToken: false);
        if (parseInfo.fAllowTrailingWhite)
        {
            format.TrimTail();
            format.RemoveTrailingInQuoteSpaces();
            str.TrimTail();
        }
        if ((styles & DateTimeStyles.AllowLeadingWhite) != 0)
        {
            format.SkipWhiteSpaces();
            format.RemoveLeadingInQuoteSpaces();
            str.SkipWhiteSpaces();
        }
        while (format.GetNext())
        {
            if (parseInfo.fAllowInnerWhite)
            {
                str.SkipWhiteSpaces();
            }
            if (!ParseByFormat(ref str, ref format, ref parseInfo, dtfi, ref result))
            {
                return false;
            }
        }
        if (str.Index < str.Value.Length - 1)
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        if (parseInfo.fUseTwoDigitYear && (dtfi.FormatFlags & DateTimeFormatFlags.UseHebrewRule) == 0)
        {
            if (result.Year >= 100)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            try
            {
                result.Year = parseInfo.calendar.ToFourDigitYear(result.Year);
            }
            catch (ArgumentOutOfRangeException)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
        }
        if (parseInfo.fUseHour12)
        {
            if (parseInfo.timeMark == TM.NotSet)
            {
                parseInfo.timeMark = TM.AM;
            }
            if (result.Hour > 12)
            {
                result.SetBadDateTimeFailure();
                return false;
            }
            if (parseInfo.timeMark == TM.AM)
            {
                if (result.Hour == 12)
                {
                    result.Hour = 0;
                }
            }
            else
            {
                result.Hour = ((result.Hour == 12) ? 12 : (result.Hour + 12));
            }
        }
        else if ((parseInfo.timeMark == TM.AM && result.Hour >= 12) || (parseInfo.timeMark == TM.PM && result.Hour < 12))
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        bool flag = result.Year == -1 && result.Month == -1 && result.Day == -1;
        if (!CheckDefaultDateTime(ref result, ref parseInfo.calendar, styles))
        {
            return false;
        }
        if (!flag && dtfi.HasYearMonthAdjustment && !dtfi.YearMonthAdjustment(ref result.Year, ref result.Month, (result.flags & ParseFlags.ParsedMonthName) != 0))
        {
            result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "Format_BadDateTimeCalendar");
            return false;
        }
        if (!parseInfo.calendar.TryToDateTime(result.Year, result.Month, result.Day, result.Hour, result.Minute, result.Second, 0, result.era, out result.parsedDate))
        {
            result.SetFailure(ParseFailureKind.FormatBadDateTimeCalendar, "Format_BadDateTimeCalendar");
            return false;
        }
        if (result.fraction > 0.0 && !result.parsedDate.TryAddTicks((long)Math.Round(result.fraction * 10000000.0), out result.parsedDate))
        {
            result.SetBadDateTimeFailure();
            return false;
        }
        if (parseInfo.dayOfWeek != -1 && parseInfo.dayOfWeek != (int)parseInfo.calendar.GetDayOfWeek(result.parsedDate))
        {
            result.SetFailure(ParseFailureKind.FormatWithOriginalDateTime, "Format_BadDayOfWeek");
            return false;
        }
        return DetermineTimeZoneAdjustments(ref result, styles, flag);
    }
References System.Globalization.DateTimeFormatInfo.Calendar, System.ParsingInfo.calendar, System.DateTimeParse.CheckDefaultDateTime(), System.DateTimeParse.ConfigureFormatOS(), System.DateTimeParse.ConfigureFormatR(), System.ParsingInfo.dayOfWeek, System.DateTimeParse.DetermineTimeZoneAdjustments(), System.DateTimeParse.ExpandPredefinedFormat(), System.ParsingInfo.fAllowInnerWhite, System.ParsingInfo.fAllowTrailingWhite, System.format, System.ParsingInfo.fUseHour12, System.ParsingInfo.fUseTwoDigitYear, System.Globalization.Calendar.GetDayOfWeek(), System.Globalization.Calendar.ID, System.ParsingInfo.Init(), System.ReadOnlySpan< T >.Length, System.DateTimeParse.ParseByFormat(), System.DateTimeParse.ParseFormatO(), System.DateTimeParse.ParseFormatR(), System.Math.Round(), System.s, System.DateTimeParse.s_hebrewNumberParser, System.str, System.ParsingInfo.timeMark, System.Globalization.Calendar.ToFourDigitYear(), System.__DTString.TrimTail(), and System.Globalization.Calendar.TryToDateTime().
Referenced by System.DateTimeParse.TryParseExact().