Terraria: System.Net.Http.HttpTelemetry.RequestStart
RequestStart() [2/2]
void System.Net.Http.HttpTelemetry.RequestStart (string scheme, string host, int port, string pathAndQuery, byte versionMajor, byte versionMinor, HttpVersionPolicy versionPolicy) inline private
Definition at line 41 of file HttpTelemetry.cs.
    {
        Interlocked.Increment(ref _startedRequests);
        WriteEvent(1, scheme, host, port, pathAndQuery, versionMajor, versionMinor, versionPolicy);
    }
References System.Net.Http.HttpTelemetry._startedRequests, System.Threading.Interlocked.Increment(), and System.Net.Http.HttpTelemetry.WriteEvent().
Referenced by System.Net.Http.HttpTelemetry.RequestStart().