Terraria: System.Diagnostics.StackTrace.InitializeForException
InitializeForException()
void System.Diagnostics.StackTrace.InitializeForException (Exception exception, int skipFrames, bool fNeedFileInfo) inline private
Definition at line 56 of file StackTrace.cs.
    {
        CaptureStackTrace(skipFrames, fNeedFileInfo, exception);
    }
References System.Diagnostics.StackTrace.CaptureStackTrace(), and System.exception.
Referenced by System.Diagnostics.StackTrace.StackTrace(), System.Diagnostics.StackTrace.StackTrace(), System.Diagnostics.StackTrace.StackTrace(), and System.Diagnostics.StackTrace.StackTrace().