Terraria: System.Diagnostics.StackTrace.CaptureStackTrace
CaptureStackTrace()
void System.Diagnostics.StackTrace.CaptureStackTrace (int skipFrames, bool fNeedFileInfo, Exception e) inline private
Definition at line 66 of file StackTrace.cs.
    {
        _methodsToSkip = skipFrames;
        StackFrameHelper stackFrameHelper = new StackFrameHelper(null);
        stackFrameHelper.InitializeSourceInfo(0, fNeedFileInfo, e);
        _numOfFrames = stackFrameHelper.GetNumberOfFrames();
        if (_methodsToSkip > _numOfFrames)
        {
            _methodsToSkip = _numOfFrames;
        }
        if (_numOfFrames != 0)
        {
            _stackFrames = new StackFrame[_numOfFrames];
            for (int i = 0; i < _numOfFrames; i++)
            {
                _stackFrames[i] = new StackFrame(stackFrameHelper, i, fNeedFileInfo);
            }
            if (e == null)
            {
                _methodsToSkip += CalculateFramesToSkip(stackFrameHelper, _numOfFrames);
            }
            _numOfFrames -= _methodsToSkip;
            if (_numOfFrames < 0)
            {
                _numOfFrames = 0;
            }
        }
    }
References System.Diagnostics.StackTrace._methodsToSkip, System.Diagnostics.StackTrace._numOfFrames, System.Diagnostics.StackTrace._stackFrames, and System.Diagnostics.StackTrace.CalculateFramesToSkip().
Referenced by System.Diagnostics.StackTrace.InitializeForCurrentThread(), and System.Diagnostics.StackTrace.InitializeForException().