Terraria: System.Diagnostics.StackTrace.ToString
ToString() [3/3]
void System.Diagnostics.StackTrace.ToString (TraceFormat traceFormat, StringBuilder sb) inline package
Definition at line 209 of file StackTrace.cs.
    {
        string resourceString = SR.GetResourceString("Word_At", "at");
        string resourceString2 = SR.GetResourceString("StackTrace_InFileLineNumber", "in {0}:line {1}");
        string resourceString3 = SR.GetResourceString("StackTrace_InFileILOffset", "in {0}:token 0x{1:x}+0x{2:x}");
        bool flag = true;
        for (int i = 0; i < _numOfFrames; i++)
        {
            StackFrame frame = GetFrame(i);
            MethodBase method = frame?.GetMethod();
            if (!(method != null) || (!ShowInStackTrace(method) && i != _numOfFrames - 1))
            {
                continue;
            }
            if (flag)
            {
                flag = false;
            }
            else
            {
                sb.AppendLine();
            }
            sb.Append("   ").Append(resourceString).Append(' ');
            bool flag2 = false;
            Type declaringType = method.DeclaringType;
            string name = method.Name;
            bool flag3 = false;
            if (declaringType != null && declaringType.IsDefined(typeof(CompilerGeneratedAttribute), inherit: false))
            {
                flag2 = declaringType.IsAssignableTo(typeof(IAsyncStateMachine));
                if (flag2 || declaringType.IsAssignableTo(typeof(IEnumerator)))
                {
                    flag3 = TryResolveStateMachineMethod(ref method, out declaringType);
                }
            }
            if (declaringType != null)
            {
                string fullName = declaringType.FullName;
                foreach (char c in fullName)
                {
                    sb.Append((c == '+') ? '.' : c);
                }
                sb.Append('.');
            }
            sb.Append(method.Name);
            if (method is MethodInfo { IsGenericMethod: not false } methodInfo)
            {
                Type[] genericArguments = methodInfo.GetGenericArguments();
                sb.Append('[');
                int k = 0;
                bool flag4 = true;
                for (; k < genericArguments.Length; k++)
                {
                    if (!flag4)
                    {
                        sb.Append(',');
                    }
                    else
                    {
                        flag4 = false;
                    }
                    sb.Append(genericArguments[k].Name);
                }
                sb.Append(']');
            }
            ParameterInfo[] array = null;
            try
            {
                array = method.GetParameters();
            }
            catch
            {
            }
            if (array != null)
            {
                sb.Append('(');
                bool flag5 = true;
                for (int l = 0; l < array.Length; l++)
                {
                    if (!flag5)
                    {
                        sb.Append(", ");
                    }
                    else
                    {
                        flag5 = false;
                    }
                    string value = "<UnknownType>";
                    if (array[l].ParameterType != null)
                    {
                        value = array[l].ParameterType.Name;
                    }
                    sb.Append(value);
                    sb.Append(' ');
                    sb.Append(array[l].Name);
                }
                sb.Append(')');
            }
            if (flag3)
            {
                sb.Append('+');
                sb.Append(name);
                sb.Append('(').Append(')');
            }
            if (frame.GetILOffset() != -1)
            {
                string fileName = frame.GetFileName();
                if (fileName != null)
                {
                    sb.Append(' ');
                    sb.AppendFormat(CultureInfo.InvariantCulture, resourceString2, fileName, frame.GetFileLineNumber());
                }
                else if (LocalAppContextSwitches.ShowILOffsets && method.ReflectedType != null)
                {
                    string scopeName = method.ReflectedType.Module.ScopeName;
                    try
                    {
                        int metadataToken = method.MetadataToken;
                        sb.Append(' ');
                        sb.AppendFormat(CultureInfo.InvariantCulture, resourceString3, scopeName, metadataToken, frame.GetILOffset());
                    }
                    catch (InvalidOperationException)
                    {
                    }
                }
            }
            if (frame.IsLastFrameFromForeignExceptionStackTrace && !flag2)
            {
                sb.AppendLine();
                sb.Append(SR.GetResourceString("Exception_EndStackTraceFromPreviousThrow", "--- End of stack trace from previous location ---"));
            }
        }
        if (traceFormat == TraceFormat.TrailingNewLine)
        {
            sb.AppendLine();
        }
    }
References System.Diagnostics.StackTrace._numOfFrames, System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendLine(), System.array, System.Diagnostics.StackFrame.GetFileLineNumber(), System.Diagnostics.StackFrame.GetFileName(), System.Diagnostics.StackTrace.GetFrame(), System.Diagnostics.StackFrame.GetILOffset(), System.Diagnostics.StackFrame.GetMethod(), System.SR.GetResourceString(), System.Globalization.CultureInfo.InvariantCulture, System.Diagnostics.StackFrame.IsLastFrameFromForeignExceptionStackTrace, System.Name, System.LocalAppContextSwitches.ShowILOffsets, System.Diagnostics.StackTrace.ShowInStackTrace(), System.Diagnostics.StackTrace.TryResolveStateMachineMethod(), and System.value.