Terraria: System.RuntimeMethodHandle.EnsureNonNullMethodInfo
EnsureNonNullMethodInfo()
static IRuntimeMethodInfo System.RuntimeMethodHandle.EnsureNonNullMethodInfo (IRuntimeMethodInfo method) inline static package
Definition at line 28 of file RuntimeMethodHandle.cs.
    {
        if (method == null)
        {
            throw new ArgumentNullException(null, SR.Arg_InvalidHandle);
        }
        return method;
    }
References System.SR.Arg_InvalidHandle, and System.Runtime.Serialization.Dictionary.
Referenced by System.RuntimeMethodHandle.ConstructInstantiation(), System.RuntimeMethodHandle.GetFunctionPointer(), System.RuntimeMethodHandle.GetMethodInstantiationInternal(), and System.RuntimeMethodHandle.GetMethodInstantiationPublic().