Terraria: System.RuntimeMethodHandle.GetUtf8Name
GetUtf8Name()
static unsafe MdUtf8String System.RuntimeMethodHandle.GetUtf8Name (RuntimeMethodHandleInternal method) inline static package
Definition at line 176 of file RuntimeMethodHandle.cs.
    {
        return new MdUtf8String(_GetUtf8Name(method));
    }
References System.RuntimeMethodHandle._GetUtf8Name(), and System.Runtime.Serialization.Dictionary.
Referenced by System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateConstructors(), and System.RuntimeType.RuntimeTypeCache.MemberInfoCache< T >.PopulateMethods().