Terraria: System.RuntimeMethodHandle.GetFunctionPointer
GetFunctionPointer() [1/2]
IntPtr System.RuntimeMethodHandle.GetFunctionPointer () inline
Definition at line 94 of file RuntimeMethodHandle.cs.
    {
        IntPtr functionPointer = GetFunctionPointer(EnsureNonNullMethodInfo(m_value).Value);
        GC.KeepAlive(m_value);
        return functionPointer;
    }
References System.Runtime.Serialization.Dictionary, System.RuntimeMethodHandle.EnsureNonNullMethodInfo(), System.RuntimeMethodHandle.GetFunctionPointer(), System.GC.KeepAlive(), System.RuntimeMethodHandle.m_value, and System.RuntimeMethodHandle.Value.
Referenced by System.RuntimeMethodHandle.GetFunctionPointer().