Terraria: System.RuntimeMethodHandle.ConstructInstantiation
ConstructInstantiation() [1/2]
static string System.RuntimeMethodHandle.ConstructInstantiation (IRuntimeMethodInfo method, TypeNameFormatFlags format) inline static package
Definition at line 131 of file RuntimeMethodHandle.cs.
    {
        string s = null;
        IRuntimeMethodInfo runtimeMethodInfo = EnsureNonNullMethodInfo(method);
        ConstructInstantiation(runtimeMethodInfo.Value, format, new StringHandleOnStack(ref s));
        GC.KeepAlive(runtimeMethodInfo);
        return s;
    }
References System.RuntimeMethodHandle.ConstructInstantiation(), System.Runtime.Serialization.Dictionary, System.RuntimeMethodHandle.EnsureNonNullMethodInfo(), System.format, System.GC.KeepAlive(), and System.s.