Terraria: System.Net.WebSockets.WebSocketHandle.ValidateHeader
ValidateHeader()
static void System.Net.WebSockets.WebSocketHandle.ValidateHeader (HttpHeaders headers, string name, string expectedValue) inline static private
Definition at line 389 of file WebSocketHandle.cs.
    {
        if (headers.NonValidated.TryGetValues(name, out var values))
        {
            if (values.Count == 1)
            {
                using HeaderStringValues.Enumerator enumerator = values.GetEnumerator();
                if (enumerator.MoveNext())
                {
                    string current = enumerator.Current;
                    if (string.Equals(current, expectedValue, StringComparison.OrdinalIgnoreCase))
                    {
                        return;
                    }
                }
            }
            throw new WebSocketException(WebSocketError.HeaderError, System.SR.Format(System.SR.net_WebSockets_InvalidResponseHeader, name, values));
        }
        throw new WebSocketException(WebSocketError.Faulted, System.SR.Format(System.SR.net_WebSockets_MissingResponseHeader, name));
    }
References System.Net.Equals, System.SR.Format(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.SR.net_WebSockets_InvalidResponseHeader, System.SR.net_WebSockets_MissingResponseHeader, and System.values.
Referenced by System.Net.WebSockets.WebSocketHandle.ConnectAsync().