Terraria: System.Net.WebSockets.WebSocketHandle.AddWebSocketHeaders
AddWebSocketHeaders()
static void System.Net.WebSockets.WebSocketHandle.AddWebSocketHeaders (HttpRequestMessage request, string secKey, ClientWebSocketOptions options) inline static private
Definition at line 314 of file WebSocketHandle.cs.
    {
        request.Headers.TryAddWithoutValidation("Connection", "Upgrade");
        request.Headers.TryAddWithoutValidation("Upgrade", "websocket");
        request.Headers.TryAddWithoutValidation("Sec-WebSocket-Version", "13");
        request.Headers.TryAddWithoutValidation("Sec-WebSocket-Key", secKey);
        List<string> requestedSubProtocols = options._requestedSubProtocols;
        if (requestedSubProtocols != null && requestedSubProtocols.Count > 0)
        {
            request.Headers.TryAddWithoutValidation("Sec-WebSocket-Protocol", string.Join(", ", options.RequestedSubProtocols));
        }
        if (options.DangerousDeflateOptions != null)
        {
            request.Headers.TryAddWithoutValidation("Sec-WebSocket-Extensions", GetDeflateOptions(options.DangerousDeflateOptions));
        }
        static string GetDeflateOptions(WebSocketDeflateOptions options)
        {
            StringBuilder stringBuilder = new StringBuilder(128);
            stringBuilder.Append("permessage-deflate").Append("; ");
            if (options.ClientMaxWindowBits != 15)
            {
                StringBuilder stringBuilder2 = stringBuilder;
                StringBuilder stringBuilder3 = stringBuilder2;
                IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
                IFormatProvider provider = invariantCulture;
                StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(1, 2, stringBuilder2, invariantCulture);
                handler.AppendFormatted("client_max_window_bits");
                handler.AppendLiteral("=");
                handler.AppendFormatted(options.ClientMaxWindowBits);
                stringBuilder3.Append(provider, ref handler);
            }
            else
            {
                stringBuilder.Append("client_max_window_bits");
            }
            if (!options.ClientContextTakeover)
            {
                stringBuilder.Append("; ").Append("client_no_context_takeover");
            }
            if (options.ServerMaxWindowBits != 15)
            {
                StringBuilder stringBuilder2 = stringBuilder;
                StringBuilder stringBuilder4 = stringBuilder2;
                IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
                IFormatProvider provider2 = invariantCulture;
                StringBuilder.AppendInterpolatedStringHandler handler2 = new StringBuilder.AppendInterpolatedStringHandler(3, 2, stringBuilder2, invariantCulture);
                handler2.AppendLiteral("; ");
                handler2.AppendFormatted("server_max_window_bits");
                handler2.AppendLiteral("=");
                handler2.AppendFormatted(options.ServerMaxWindowBits);
                stringBuilder4.Append(provider2, ref handler2);
            }
            if (!options.ServerContextTakeover)
            {
                stringBuilder.Append("; ").Append("server_no_context_takeover");
            }
            return stringBuilder.ToString();
        }
    }
References System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Globalization.CultureInfo.InvariantCulture, System.Threading.Tasks.Join, and System.options.
Referenced by System.Net.WebSockets.WebSocketHandle.ConnectAsync().