Terraria: System.Net.WebSockets.WebSocketHandle.CreateSecKeyAndSecWebSocketAccept
CreateSecKeyAndSecWebSocketAccept()
static KeyValuePair< string, string > System.Net.WebSockets.WebSocketHandle.CreateSecKeyAndSecWebSocketAccept () inline static private
Definition at line 374 of file WebSocketHandle.cs.
    {
        ReadOnlySpan<byte> readOnlySpan = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"u8;
        Span<byte> span = stackalloc byte[24 + readOnlySpan.Length];
        bool flag = Guid.NewGuid().TryWriteBytes(span);
        string text = Convert.ToBase64String(span.Slice(0, 16));
        for (int i = 0; i < text.Length; i++)
        {
            span[i] = (byte)text[i];
        }
        readOnlySpan.CopyTo(span.Slice(text.Length));
        SHA1.TryHashData(span, span, out var bytesWritten);
        return new KeyValuePair<string, string>(text, Convert.ToBase64String(span.Slice(0, bytesWritten)));
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Guid.NewGuid(), System.text, System.Convert.ToBase64String(), and System.Security.Cryptography.SHA1.TryHashData().
Referenced by System.Net.WebSockets.WebSocketHandle.ConnectAsync().