Terraria: NetTextModule.DeserializeAsClient
DeserializeAsClient()
bool NetTextModule.DeserializeAsClient (BinaryReader reader, int senderPlayerId) inline private
     {
         byte messageAuthor = reader.ReadByte();
         NetworkText text = NetworkText.Deserialize(reader);
         Color color = reader.ReadRGB();
         ChatHelper.DisplayMessage(text, color, messageAuthor);
         return true;
     }
References Color, NetworkText.Deserialize(), and ChatHelper.DisplayMessage().
Referenced by Deserialize().