Terraria: NetTextModule.DeserializeAsServer
DeserializeAsServer()
bool NetTextModule.DeserializeAsServer (BinaryReader reader, int senderPlayerId) inline private
     {
         ChatMessage message = ChatMessage.Deserialize(reader);
         ChatManager.Commands.ProcessIncomingMessage(message, senderPlayerId);
         return true;
     }
References ChatManager.Commands, ChatMessage.Deserialize(), and ChatCommandProcessor.ProcessIncomingMessage().
Referenced by Deserialize().