Terraria: System.Xml.Resolvers.XmlPreloadedResolver.GetEntityAsync
GetEntityAsync()
override Task< object > System.Xml.Resolvers.XmlPreloadedResolver.GetEntityAsync (Uri absoluteUri, string? role, Type? ofObjectToReturn) inline virtual
Reimplemented from System.Xml.XmlResolver.
Definition at line 359 of file XmlPreloadedResolver.cs.
    {
        if (absoluteUri == null)
        {
            throw new ArgumentNullException("absoluteUri");
        }
        if (!_mappings.TryGetValue(absoluteUri, out var value))
        {
            if (_fallbackResolver != null)
            {
                return _fallbackResolver.GetEntityAsync(absoluteUri, role, ofObjectToReturn);
            }
            throw new XmlException(System.SR.Format(System.SR.Xml_CannotResolveUrl, absoluteUri));
        }
        if (ofObjectToReturn == null || ofObjectToReturn == typeof(Stream) || ofObjectToReturn == typeof(object))
        {
            return Task.FromResult((object)value.AsStream());
        }
        if (ofObjectToReturn == typeof(TextReader))
        {
            return Task.FromResult((object)value.AsTextReader());
        }
        throw new XmlException(System.SR.Xml_UnsupportedClass);
    }
References System.Xml.Resolvers.XmlPreloadedResolver._fallbackResolver, System.Xml.Resolvers.XmlPreloadedResolver._mappings, System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlResolver.GetEntityAsync(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, System.SR.Xml_CannotResolveUrl, System.SR.Xml_UnsupportedClass, and System.Xml.XmlException.