Terraria: TileObjectPreviewData.Reset
Reset()
void TileObjectPreviewData.Reset () inline
     {
         _active = false;
         _size = Point16.Zero;
         _coordinates = Point16.Zero;
         _objectStart = Point16.Zero;
         _percentValid = 0f;
         _type = 0;
         _style = 0;
         _alternate = -1;
         _random = -1;
         if (_data != null)
         {
             Array.Clear(_data, 0, _dataSize.X * _dataSize.Y);
         }
     }
References _active, _alternate, _coordinates, _data, _dataSize, _objectStart, _percentValid, _random, _size, _style, _type, Point16.X, Point16.Y, and Point16.Zero.
Referenced by TileObject.CanPlace(), Player.PlaceThing_TryReplacingTiles(), and Player.Update().