Terraria: System.Xml.Serialization.XmlSerializerNamespaces.Add
Add()
void System.Xml.Serialization.XmlSerializerNamespaces.Add (string prefix, string? ns) inline
Definition at line 76 of file XmlSerializerNamespaces.cs.
    {
        if (prefix != null && prefix.Length > 0)
        {
            XmlConvert.VerifyNCName(prefix);
        }
        if (ns != null && ns.Length > 0)
        {
            ExtensionMethods.ToUri(ns);
        }
        AddInternal(prefix, ns);
    }
References System.Xml.Serialization.XmlSerializerNamespaces.AddInternal(), System.prefix, System.Xml.Extensions.ExtensionMethods.ToUri(), and System.Xml.XmlConvert.VerifyNCName().
Referenced by System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateLiteralMembersElementInternal().