Terraria: WorldMap.Load
Load()
void WorldMap.Load () inline
     {
         Lighting.Clear();
         bool isCloudSave = Main.ActivePlayerFileData.IsCloudSave;
         if ((isCloudSave && SocialAPI.Cloud == null) || !Main.mapEnabled)
         {
             return;
         }
         string text = Main.playerPathName.Substring(0, Main.playerPathName.Length - 4) + Path.DirectorySeparatorChar;
         if (Main.ActiveWorldFileData.UseGuidAsMapName)
         {
             string text2 = text;
             text = string.Concat(text, Main.ActiveWorldFileData.UniqueId, ".map");
             if (!FileUtilities.Exists(text, isCloudSave))
             {
                 text = text2 + Main.worldID + ".map";
             }
         }
         else
         {
             text = text + Main.worldID + ".map";
         }
         if (!FileUtilities.Exists(text, isCloudSave))
         {
             Main.MapFileMetadata = FileMetadata.FromCurrentSettings(FileType.Map);
             return;
         }
         using MemoryStream input = new MemoryStream(FileUtilities.ReadAllBytes(text, isCloudSave));
         using BinaryReader binaryReader = new BinaryReader(input);
         try
         {
             int num = binaryReader.ReadInt32();
             if (num <= 279)
             {
                 if (num <= 91)
                 {
                     MapHelper.LoadMapVersion1(binaryReader, num);
                 }
                 else
                 {
                     MapHelper.LoadMapVersion2(binaryReader, num);
                 }
                 ClearEdges();
                 Main.clearMap = true;
                 Main.loadMap = true;
                 Main.loadMapLock = true;
                 Main.refreshMap = false;
             }
         }
         catch (Exception value)
         {
             using (StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", append: true))
             {
                 streamWriter.WriteLine(DateTime.Now);
                 streamWriter.WriteLine(value);
                 streamWriter.WriteLine("");
             }
             if (!isCloudSave)
             {
                 File.Copy(text, text + ".bad", overwrite: true);
             }
             Clear();
         }
     }
References Main.ActivePlayerFileData, Main.ActiveWorldFileData, Clear(), Lighting.Clear(), ClearEdges(), Main.clearMap, SocialAPI.Cloud, FileUtilities.Exists(), FileMetadata.FromCurrentSettings(), FileData.IsCloudSave, Main.loadMap, Main.loadMapLock, MapHelper.LoadMapVersion1(), MapHelper.LoadMapVersion2(), Main.mapEnabled, Main.MapFileMetadata, Main.playerPathName, FileUtilities.ReadAllBytes(), Main.refreshMap, WorldFileData.UniqueId, WorldFileData.UseGuidAsMapName, and Main.worldID.
Referenced by Netplay.InnerClientLoop(), and WorldGen.playWorldCallBack().