Terraria: Terraria.GameContent.Events.CultistRitual.UpdateTime
UpdateTime()
static void Terraria.GameContent.Events.CultistRitual.UpdateTime () inline static
Definition at line 21 of file CultistRitual.cs.
    {
        if (Main.netMode == 1)
        {
            return;
        }
        delay -= Main.dayRate;
        if (delay < 0)
        {
            delay = 0;
        }
        recheck -= Main.dayRate;
        if (recheck < 0)
        {
            recheck = 0;
        }
        if (delay == 0 && recheck == 0)
        {
            recheck = 600;
            if (NPC.AnyDanger())
            {
                recheck *= 6;
            }
            else
            {
                TrySpawning(Main.dungeonX, Main.dungeonY);
            }
        }
    }
References Terraria.NPC.AnyDanger(), Terraria.Main.dayRate, Terraria.GameContent.Events.CultistRitual.delay, Terraria.Main.dungeonX, Terraria.Main.dungeonY, Terraria.Main.netMode, Terraria.GameContent.Events.CultistRitual.recheck, and Terraria.GameContent.Events.CultistRitual.TrySpawning().
Referenced by Terraria.Main.UpdateTime().