Terraria: Terraria.GameContent.Events.CultistRitual.CheckRitual
CheckRitual()
static bool Terraria.GameContent.Events.CultistRitual.CheckRitual (int x, int y) inline static private
Definition at line 69 of file CultistRitual.cs.
    {
        if (delay != 0 || !Main.hardMode || !NPC.downedGolemBoss || !NPC.downedBoss3)
        {
            return false;
        }
        if (y < 7 || WorldGen.SolidTile(Main.tile[x, y - 7]))
        {
            return false;
        }
        if (NPC.AnyNPCs(437))
        {
            return false;
        }
        Vector2 center = new Vector2(x * 16 + 8, y * 16 - 64 - 8 - 27);
        Point[] spawnPoints = null;
        if (!CheckFloor(center, out spawnPoints))
        {
            return false;
        }
        return true;
    }
References Terraria.NPC.AnyNPCs(), Terraria.GameContent.Events.CultistRitual.CheckFloor(), Terraria.GameContent.Events.CultistRitual.delay, Terraria.NPC.downedBoss3, Terraria.NPC.downedGolemBoss, Terraria.Main.hardMode, Terraria.WorldGen.SolidTile(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.Events.CultistRitual.TrySpawning().