Terraria: UIBestiaryEntryButton.UIBestiaryEntryButton
UIBestiaryEntryButton()
UIBestiaryEntryButton.UIBestiaryEntryButton (BestiaryEntry entry, bool isAPrettyPortrait) inline
     {
         Entry = entry;
         Height.Set(72f, 0f);
         Width.Set(72f, 0f);
         SetPadding(0f);
         UIElement uIElement = new UIElement
         {
             Width = new StyleDimension(-4f, 1f),
             Height = new StyleDimension(-4f, 1f),
             IgnoresMouseInteraction = true,
             OverflowHidden = true,
             HAlign = 0.5f,
             VAlign = 0.5f
         };
         uIElement.SetPadding(0f);
         uIElement.Append(new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Slot_Back", (AssetRequestMode)1))
         {
             VAlign = 0.5f,
             HAlign = 0.5f
         });
         if (isAPrettyPortrait)
         {
             Asset<Texture2D> val = TryGettingBackgroundImageProvider(entry);
             if (val != null)
             {
                 uIElement.Append(new UIImage(val)
                 {
                     HAlign = 0.5f,
                     VAlign = 0.5f
                 });
             }
         }
         UIBestiaryEntryIcon uIBestiaryEntryIcon = new UIBestiaryEntryIcon(entry, isAPrettyPortrait);
         uIElement.Append(uIBestiaryEntryIcon);
         Append(uIElement);
         _icon = uIBestiaryEntryIcon;
         int? num = TryGettingDisplayIndex(entry);
         if (num.HasValue)
         {
             UIText element = new UIText(num.Value.ToString(), 0.9f)
             {
                 Top = new StyleDimension(10f, 0f),
                 Left = new StyleDimension(10f, 0f),
                 IgnoresMouseInteraction = true
             };
             Append(element);
         }
         _bordersGlow = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Slot_Selection", (AssetRequestMode)1))
         {
             VAlign = 0.5f,
             HAlign = 0.5f,
             IgnoresMouseInteraction = true
         };
         _bordersOverlay = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Slot_Overlay", (AssetRequestMode)1))
         {
             VAlign = 0.5f,
             HAlign = 0.5f,
             IgnoresMouseInteraction = true,
             Color = Color.White * 0.6f
         };
         Append(_bordersOverlay);
         UIImage uIImage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Slot_Front", (AssetRequestMode)1))
         {
             VAlign = 0.5f,
             HAlign = 0.5f,
             IgnoresMouseInteraction = true
         };
         Append(uIImage);
         _borders = uIImage;
         if (isAPrettyPortrait)
         {
             RemoveChild(_bordersOverlay);
         }
         if (!isAPrettyPortrait)
         {
             base.OnMouseOver += MouseOver;
             base.OnMouseOut += MouseOut;
         }
     }
References _borders, _bordersGlow, _bordersOverlay, _icon, UIElement.Append(), Main.Assets, Color, Entry, UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, UIElement.Left, MouseOut(), MouseOver(), UIElement.OverflowHidden, UIElement.RemoveChild(), StyleDimension.Set(), UIElement.SetPadding(), UIElement.Top, TryGettingBackgroundImageProvider(), TryGettingDisplayIndex(), UIElement.VAlign, and UIElement.Width.