Terraria: UIBestiaryEntryButton.MouseOver
MouseOver() [2/2]
void UIBestiaryEntryButton.MouseOver (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(12);
         RemoveChild(_borders);
         RemoveChild(_bordersGlow);
         RemoveChild(_bordersOverlay);
         Append(_borders);
         Append(_bordersGlow);
         _icon.ForceHover = true;
     }
References _borders, _bordersGlow, _bordersOverlay, _icon, UIElement.Append(), UIBestiaryEntryIcon.ForceHover, SoundEngine.PlaySound(), and UIElement.RemoveChild().
Referenced by UIBestiaryEntryButton().