Terraria: System.Globalization.OrdinalCasing.LastIndexOf
LastIndexOf()
static unsafe int System.Globalization.OrdinalCasing.LastIndexOf (ReadOnlySpan< char > source, ReadOnlySpan< char > value) inline static package
Definition at line 210 of file OrdinalCasing.cs.
    {
        fixed (char* ptr3 = &MemoryMarshal.GetReference(source))
        {
            fixed (char* ptr = &MemoryMarshal.GetReference(value))
            {
                char* ptr2 = ptr + value.Length - 1;
                for (char* ptr4 = ptr3 + (source.Length - value.Length); ptr4 >= ptr3; ptr4--)
                {
                    char* ptr5 = ptr;
                    char* ptr6 = ptr4;
                    while (ptr5 <= ptr2)
                    {
                        if (!char.IsHighSurrogate(*ptr5) || ptr5 == ptr2)
{
                            if (*ptr5 != *ptr6 && ToUpper(*ptr5) != ToUpper(*ptr6))
{
                                break;
                            }
                            ptr5++;
                            ptr6++;
                        }
                        else if (char.IsHighSurrogate(*ptr6) && char.IsLowSurrogate(ptr6[1]) && char.IsLowSurrogate(ptr5[1]))
{
                            if (!SurrogateCasing.Equal(*ptr6, ptr6[1], *ptr5, ptr5[1]))
{
                                break;
                            }
                            ptr6 += 2;
                            ptr5 += 2;
                        }
                        else
{
                            if (*ptr5 != *ptr6)
{
                                break;
                            }
                            ptr6++;
                            ptr5++;
                        }
                    }
                    if (ptr5 > ptr2)
                    {
                        return (int)(ptr4 - ptr3);
                    }
                }
                return -1;
            }
        }
    }
References System.Globalization.SurrogateCasing.Equal(), System.source, System.Globalization.OrdinalCasing.ToUpper(), and System.value.
Referenced by System.Globalization.Ordinal.LastIndexOfOrdinalIgnoreCase().