Terraria: System.Globalization.OrdinalCasing.CompareStringIgnoreCase
CompareStringIgnoreCase()
static int System.Globalization.OrdinalCasing.CompareStringIgnoreCase (ref char strA, int lengthA, ref char strB, int lengthB) inline static package
Definition at line 97 of file OrdinalCasing.cs.
    {
        int num = Math.Min(lengthA, lengthB);
        ref char reference = ref strA;
        ref char reference2 = ref strB;
        int num2 = 0;
        while (num2 < num)
        {
            char c = reference;
            char c2 = reference2;
            char c3 = '\0';
            if (!char.IsHighSurrogate(c) || num2 >= lengthA - 1 || !char.IsLowSurrogate(c3 = Unsafe.Add(ref reference, 1)))
            {
                if (!char.IsHighSurrogate(c2) || num2 >= lengthB - 1 || !char.IsLowSurrogate(Unsafe.Add(ref reference2, 1)))
                {
                    if (c2 == c)
                    {
                        num2++;
                        reference = ref Unsafe.Add(ref reference, 1);
                        reference2 = ref Unsafe.Add(ref reference2, 1);
                        continue;
                    }
                    char c4 = ToUpper(c);
                    char c5 = ToUpper(c2);
                    if (c4 == c5)
                    {
                        num2++;
                        reference = ref Unsafe.Add(ref reference, 1);
                        reference2 = ref Unsafe.Add(ref reference2, 1);
                        continue;
                    }
                    return c - c2;
                }
                return -1;
            }
            char c6 = '\0';
            if (!char.IsHighSurrogate(c2) || num2 >= lengthB - 1 || !char.IsLowSurrogate(c6 = Unsafe.Add(ref reference2, 1)))
            {
                return 1;
            }
            if (c == c2 && c3 == c6)
            {
                num2 += 2;
                reference = ref Unsafe.Add(ref reference, 2);
                reference2 = ref Unsafe.Add(ref reference2, 2);
                continue;
            }
            uint num3 = CharUnicodeInfo.ToUpper(UnicodeUtility.GetScalarFromUtf16SurrogatePair(c, c3));
            uint num4 = CharUnicodeInfo.ToUpper(UnicodeUtility.GetScalarFromUtf16SurrogatePair(c2, c6));
            if (num3 == num4)
            {
                num2 += 2;
                reference = ref Unsafe.Add(ref reference, 2);
                reference2 = ref Unsafe.Add(ref reference2, 2);
                continue;
            }
            return (int)(num3 - num4);
        }
        return lengthA - lengthB;
    }
References System.Text.UnicodeUtility.GetScalarFromUtf16SurrogatePair(), System.Math.Min(), System.Globalization.OrdinalCasing.ToUpper(), and System.Globalization.CharUnicodeInfo.ToUpper().
Referenced by System.Globalization.Ordinal.CompareStringIgnoreCaseNonAscii().