Terraria: System.Globalization.OrdinalCasing.InitOrdinalCasingPage
InitOrdinalCasingPage()
static unsafe ushort[] System.Globalization.OrdinalCasing.InitOrdinalCasingPage (int pageNumber) inline static private
Definition at line 276 of file OrdinalCasing.cs.
    {
        ushort[] array = new ushort[256];
        fixed (ushort* ptr = array)
        {
            char* pTarget = (char*)ptr;
            Interop.Globalization.InitOrdinalCasingPage(pageNumber, pTarget);
        }
        Volatile.Write(ref s_casingTable[pageNumber], array);
        return array;
    }
References System.array, Interop.Globalization.InitOrdinalCasingPage(), System.Globalization.OrdinalCasing.s_casingTable, and System.Threading.Volatile.Write().
Referenced by System.Globalization.OrdinalCasing.ToUpper().