Terraria: System.Net.Http.Headers.RangeItemHeaderValue.GetRangeItemListLength
GetRangeItemListLength()
static int System.Net.Http.Headers.RangeItemHeaderValue.GetRangeItemListLength (string input, int startIndex, ICollection< RangeItemHeaderValue > rangeCollection) inline static package
Definition at line 110 of file RangeItemHeaderValue.cs.
    {
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        bool separatorFound = false;
        int nextNonEmptyOrWhitespaceIndex = HeaderUtilities.GetNextNonEmptyOrWhitespaceIndex(input, startIndex, skipEmptyValues: true, out separatorFound);
        if (nextNonEmptyOrWhitespaceIndex == input.Length)
        {
            return 0;
        }
        do
        {
            RangeItemHeaderValue parsedValue;
            int rangeItemLength = GetRangeItemLength(input, nextNonEmptyOrWhitespaceIndex, out parsedValue);
            if (rangeItemLength == 0)
            {
                return 0;
            }
            rangeCollection.Add(parsedValue);
            nextNonEmptyOrWhitespaceIndex += rangeItemLength;
            nextNonEmptyOrWhitespaceIndex = HeaderUtilities.GetNextNonEmptyOrWhitespaceIndex(input, nextNonEmptyOrWhitespaceIndex, skipEmptyValues: true, out separatorFound);
            if (nextNonEmptyOrWhitespaceIndex < input.Length && !separatorFound)
            {
                return 0;
            }
        }
        while (nextNonEmptyOrWhitespaceIndex != input.Length);
        return nextNonEmptyOrWhitespaceIndex - startIndex;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.Headers.HeaderUtilities.GetNextNonEmptyOrWhitespaceIndex(), System.Net.Http.Headers.RangeItemHeaderValue.GetRangeItemLength(), System.input, and System.startIndex.
Referenced by System.Net.Http.Headers.RangeHeaderValue.GetRangeLength().