Terraria: System.Net.Http.Headers.RangeItemHeaderValue.GetRangeItemLength
GetRangeItemLength()
static int System.Net.Http.Headers.RangeItemHeaderValue.GetRangeItemLength (string input, int startIndex, out RangeItemHeaderValue parsedValue) inline static package
Definition at line 142 of file RangeItemHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int num = startIndex;
        int offset = num;
        int numberLength = HttpRuleParser.GetNumberLength(input, num, allowDecimal: false);
        if (numberLength > 19)
        {
            return 0;
        }
        num += numberLength;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        if (num == input.Length || input[num] != '-')
        {
            return 0;
        }
        num++;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        int offset2 = num;
        int num2 = 0;
        if (num < input.Length)
        {
            num2 = HttpRuleParser.GetNumberLength(input, num, allowDecimal: false);
            if (num2 > 19)
            {
                return 0;
            }
            num += num2;
            num += HttpRuleParser.GetWhitespaceLength(input, num);
        }
        if (numberLength == 0 && num2 == 0)
        {
            return 0;
        }
        long result = 0L;
        if (numberLength > 0 && !HeaderUtilities.TryParseInt64(input, offset, numberLength, out result))
        {
            return 0;
        }
        long result2 = 0L;
        if (num2 > 0 && !HeaderUtilities.TryParseInt64(input, offset2, num2, out result2))
        {
            return 0;
        }
        if (numberLength > 0 && num2 > 0 && result > result2)
        {
            return 0;
        }
        parsedValue = new RangeItemHeaderValue((numberLength == 0) ? null : new long?(result), (num2 == 0) ? null : new long?(result2));
        return num - startIndex;
    }
References System.Net.Http.Headers.RangeItemHeaderValue.RangeItemHeaderValue(), System.Net.Http.HttpRuleParser.GetNumberLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, System.L, System.offset, System.startIndex, and System.Net.Http.Headers.HeaderUtilities.TryParseInt64().
Referenced by System.Net.Http.Headers.RangeItemHeaderValue.GetRangeItemListLength().