Terraria: UICharacterCreation.CreateHSLSlider
CreateHSLSlider()
UIColoredSlider UICharacterCreation.CreateHSLSlider (HSLSliderId id) inline private
     {
         UIColoredSlider uIColoredSlider = CreateHSLSliderButtonBase(id);
         uIColoredSlider.VAlign = 0f;
         uIColoredSlider.HAlign = 0f;
         uIColoredSlider.Width = StyleDimension.FromPixelsAndPercent(-10f, 1f);
         uIColoredSlider.Top.Set(30 * (int)id, 0f);
         uIColoredSlider.OnLeftMouseDown += Click_ColorPicker;
         uIColoredSlider.SetSnapPoint("Middle", (int)id, null, new Vector2(0f, 20f));
         return uIColoredSlider;
     }
References Click_ColorPicker(), CreateHSLSliderButtonBase(), StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.OnLeftMouseDown, StyleDimension.Set(), UIElement.SetSnapPoint(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by MakeHSLMenu().