Terraria: UICharacterCreation.ApplyPendingColor
ApplyPendingColor()
void UICharacterCreation.ApplyPendingColor (Color pendingColor) inline private
     {
         switch (_selectedPicker)
         {
         case CategoryId.HairColor:
             _player.hairColor = pendingColor;
             break;
         case CategoryId.Eye:
             _player.eyeColor = pendingColor;
             break;
         case CategoryId.Skin:
             _player.skinColor = pendingColor;
             break;
         case CategoryId.Shirt:
             _player.shirtColor = pendingColor;
             break;
         case CategoryId.Undershirt:
             _player.underShirtColor = pendingColor;
             break;
         case CategoryId.Pants:
             _player.pantsColor = pendingColor;
             break;
         case CategoryId.Shoes:
             _player.shoeColor = pendingColor;
             break;
         }
     }
References _player, _selectedPicker, Player.eyeColor, Player.hairColor, Player.pantsColor, Player.shirtColor, Player.shoeColor, Player.skinColor, and Player.underShirtColor.
Referenced by Click_PasteHex(), Click_RandomizeSingleColor(), and UpdateHSLValue().