Terraria: UICharacterCreation.MakeCharPreview
MakeCharPreview()
void UICharacterCreation.MakeCharPreview (UIPanel container) inline private
     {
         float num = 70f;
         for (float num2 = 0f; num2 <= 1f; num2 += 1f)
         {
             UICharacter element = new UICharacter(_player, animated: true, hasBackPanel: false, 1.5f)
             {
                 Width = StyleDimension.FromPixels(80f),
                 Height = StyleDimension.FromPixelsAndPercent(80f, 0f),
                 Top = StyleDimension.FromPixelsAndPercent(0f - num, 0f),
                 VAlign = 0f,
                 HAlign = 0.5f
             };
             container.Append(element);
         }
     }
References _player, UIElement.Append(), StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Height, UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().