Terraria: UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty
SetupPlayerStatsAndInventoryBasedOnDifficulty()
void UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty () inline private
     {
         int num = 0;
         byte difficulty = _player.difficulty;
         if (difficulty == 3)
         {
             _player.statLife = (_player.statLifeMax = 100);
             _player.statMana = (_player.statManaMax = 20);
             _player.inventory[num].SetDefaults(6);
             _player.inventory[num++].Prefix(-1);
             _player.inventory[num].SetDefaults(1);
             _player.inventory[num++].Prefix(-1);
             _player.inventory[num].SetDefaults(10);
             _player.inventory[num++].Prefix(-1);
             _player.inventory[num].SetDefaults(7);
             _player.inventory[num++].Prefix(-1);
             _player.inventory[num].SetDefaults(4281);
             _player.inventory[num++].Prefix(-1);
             _player.inventory[num].SetDefaults(8);
             _player.inventory[num++].stack = 100;
             _player.inventory[num].SetDefaults(965);
             _player.inventory[num++].stack = 100;
             _player.inventory[num++].SetDefaults(50);
             _player.inventory[num++].SetDefaults(84);
             _player.armor[3].SetDefaults(4978);
             _player.armor[3].Prefix(-1);
             if (_player.name == "Wolf Pet" || _player.name == "Wolfpet")
             {
                 _player.miscEquips[3].SetDefaults(5130);
             }
             _player.AddBuff(216, 3600);
         }
         else
         {
             _player.inventory[num].SetDefaults(3507);
             _player.inventory[num++].Prefix(-1);
             _player.inventory[num].SetDefaults(3509);
             _player.inventory[num++].Prefix(-1);
             _player.inventory[num].SetDefaults(3506);
             _player.inventory[num++].Prefix(-1);
         }
         if (Main.runningCollectorsEdition)
         {
             _player.inventory[num++].SetDefaults(603);
         }
         _player.savedPerPlayerFieldsThatArentInThePlayerClass = new Player.SavedPlayerDataWithAnnoyingRules();
         CreativePowerManager.Instance.ResetDataForNewPlayer(_player);
     }
References _player, Player.AddBuff(), Player.armor, Player.difficulty, CreativePowerManager.Instance, Player.inventory, Player.miscEquips, Player.name, Item.Prefix(), CreativePowerManager.ResetDataForNewPlayer(), Main.runningCollectorsEdition, Player.savedPerPlayerFieldsThatArentInThePlayerClass, Item.SetDefaults(), Item.stack, Player.statLife, Player.statLifeMax, Player.statMana, and Player.statManaMax.
Referenced by FinishCreatingCharacter().