Terraria: UICharacterCreation.Click_ClothStyles
Click_ClothStyles()
void UICharacterCreation.Click_ClothStyles (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(12);
         UnselectAllCategories();
         _selectedPicker = CategoryId.Clothing;
         _middleContainer.Append(_clothStylesContainer);
         _clothingStylesCategoryButton.SetSelected(selected: true);
         UpdateSelectedGender();
     }
References _clothingStylesCategoryButton, _clothStylesContainer, _middleContainer, _selectedPicker, UIElement.Append(), SoundEngine.PlaySound(), UIColoredImageButton.SetSelected(), UnselectAllCategories(), and UpdateSelectedGender().
Referenced by MakeCategoriesBar(), and SelectColorPicker().