Terraria: UICharacterCreation.Click_RandomizePlayer
Click_RandomizePlayer()
void UICharacterCreation.Click_RandomizePlayer (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(12);
         Player player = _player;
         int index = Main.rand.Next(Main.Hairstyles.AvailableHairstyles.Count);
         player.hair = Main.Hairstyles.AvailableHairstyles[index];
         player.eyeColor = ScaledHslToRgb(GetRandomColorVector());
         while (player.eyeColor.R + player.eyeColor.G + player.eyeColor.B > 300)
         {
             player.eyeColor = ScaledHslToRgb(GetRandomColorVector());
         }
         float num = (float)Main.rand.Next(60, 120) * 0.01f;
         if (num > 1f)
         {
             num = 1f;
         }
         player.skinColor.R = (byte)((float)Main.rand.Next(240, 255) * num);
         player.skinColor.G = (byte)((float)Main.rand.Next(110, 140) * num);
         player.skinColor.B = (byte)((float)Main.rand.Next(75, 110) * num);
         player.hairColor = ScaledHslToRgb(GetRandomColorVector());
         player.shirtColor = ScaledHslToRgb(GetRandomColorVector());
         player.underShirtColor = ScaledHslToRgb(GetRandomColorVector());
         player.pantsColor = ScaledHslToRgb(GetRandomColorVector());
         player.shoeColor = ScaledHslToRgb(GetRandomColorVector());
         player.skinVariant = _validClothStyles[Main.rand.Next(_validClothStyles.Length)];
         switch (player.hair + 1)
         {
         case 5:
         case 6:
         case 7:
         case 10:
         case 12:
         case 19:
         case 22:
         case 23:
         case 26:
         case 27:
         case 30:
         case 33:
         case 34:
         case 35:
         case 37:
         case 38:
         case 39:
         case 40:
         case 41:
         case 44:
         case 45:
         case 46:
         case 47:
         case 48:
         case 49:
         case 51:
         case 56:
         case 65:
         case 66:
         case 67:
         case 68:
         case 69:
         case 70:
         case 71:
         case 72:
         case 73:
         case 74:
         case 79:
         case 80:
         case 81:
         case 82:
         case 84:
         case 85:
         case 86:
         case 87:
         case 88:
         case 90:
         case 91:
         case 92:
         case 93:
         case 95:
         case 96:
         case 98:
         case 100:
         case 102:
         case 104:
         case 107:
         case 108:
         case 113:
         case 124:
         case 126:
         case 133:
         case 134:
         case 135:
         case 144:
         case 146:
         case 147:
         case 163:
         case 165:
             player.Male = false;
             break;
         default:
             player.Male = true;
             break;
         }
         Click_CharClothStyle(null, null);
         UpdateSelectedGender();
         UpdateColorPickers();
     }
References _player, _validClothStyles, HairstyleUnlocksHelper.AvailableHairstyles, Click_CharClothStyle(), Player.eyeColor, GetRandomColorVector(), Player.hair, Player.hairColor, Main.Hairstyles, Player.Male, UnifiedRandom.Next(), Player.pantsColor, SoundEngine.PlaySound(), Main.rand, ScaledHslToRgb(), Player.shirtColor, Player.shoeColor, Player.skinColor, Player.skinVariant, Player.underShirtColor, UpdateColorPickers(), and UpdateSelectedGender().
Referenced by MakeClothStylesMenu().