Terraria: UICharacterCreation.Click_HairStyles
Click_HairStyles()
void UICharacterCreation.Click_HairStyles (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(12);
         UnselectAllCategories();
         _selectedPicker = CategoryId.HairStyle;
         _middleContainer.Append(_hairstylesContainer);
         _hairStylesCategoryButton.SetSelected(selected: true);
     }
References _hairStylesCategoryButton, _hairstylesContainer, _middleContainer, _selectedPicker, UIElement.Append(), SoundEngine.PlaySound(), UIColoredImageButton.SetSelected(), and UnselectAllCategories().
Referenced by MakeCategoriesBar(), and SelectColorPicker().