Terraria: UICharacterCreation.SelectColorPicker
SelectColorPicker()
void UICharacterCreation.SelectColorPicker (CategoryId selection) inline private
     {
         _selectedPicker = selection;
         switch (selection)
         {
         case CategoryId.CharInfo:
             Click_CharInfo(null, null);
             return;
         case CategoryId.Clothing:
             Click_ClothStyles(null, null);
             return;
         case CategoryId.HairStyle:
             Click_HairStyles(null, null);
             return;
         }
         UnselectAllCategories();
         _middleContainer.Append(_hslContainer);
         for (int i = 0; i < _colorPickers.Length; i++)
         {
             if (_colorPickers[i] != null)
             {
                 _colorPickers[i].SetSelected(i == (int)selection);
             }
         }
         Vector3 currentColorHSL = Vector3.One;
         switch (_selectedPicker)
         {
         case CategoryId.HairColor:
             currentColorHSL = RgbToScaledHsl(_player.hairColor);
             break;
         case CategoryId.Eye:
             currentColorHSL = RgbToScaledHsl(_player.eyeColor);
             break;
         case CategoryId.Skin:
             currentColorHSL = RgbToScaledHsl(_player.skinColor);
             break;
         case CategoryId.Shirt:
             currentColorHSL = RgbToScaledHsl(_player.shirtColor);
             break;
         case CategoryId.Undershirt:
             currentColorHSL = RgbToScaledHsl(_player.underShirtColor);
             break;
         case CategoryId.Pants:
             currentColorHSL = RgbToScaledHsl(_player.pantsColor);
             break;
         case CategoryId.Shoes:
             currentColorHSL = RgbToScaledHsl(_player.shoeColor);
             break;
         }
         _currentColorHSL = currentColorHSL;
         UpdateHexText(ScaledHslToRgb(currentColorHSL.X, currentColorHSL.Y, currentColorHSL.Z));
     }
References _colorPickers, _currentColorHSL, _hslContainer, _middleContainer, _player, _selectedPicker, UIElement.Append(), Click_CharInfo(), Click_ClothStyles(), Click_HairStyles(), Player.eyeColor, Player.hairColor, Player.pantsColor, RgbToScaledHsl(), ScaledHslToRgb(), UIColoredImageButton.SetSelected(), Player.shirtColor, Player.shoeColor, Player.skinColor, Player.underShirtColor, UnselectAllCategories(), and UpdateHexText().
Referenced by Click_ColorPicker(), and TryMovingCategory().