Terraria: UICharacterCreation.UpdateHSL_S
UpdateHSL_S()
void UICharacterCreation.UpdateHSL_S () inline private
     {
         float value = UILinksInitializer.HandleSliderHorizontalInput(_currentColorHSL.Y, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
         UpdateHSLValue(HSLSliderId.Saturation, value);
     }
References _currentColorHSL, PlayerInput.CurrentProfile, UILinksInitializer.HandleSliderHorizontalInput(), PlayerInputProfile.InterfaceDeadzoneX, and UpdateHSLValue().
Referenced by CreateHSLSliderButtonBase().