Terraria: UICharacterCreation.MakeInfoMenu
MakeInfoMenu()
void UICharacterCreation.MakeInfoMenu (UIElement parentContainer) inline private
     {
         UIElement uIElement = new UIElement
         {
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
             HAlign = 0.5f,
             VAlign = 0f
         };
         uIElement.SetPadding(10f);
         uIElement.PaddingBottom = 0f;
         uIElement.PaddingTop = 0f;
         parentContainer.Append(uIElement);
         UICharacterNameButton uICharacterNameButton = new UICharacterNameButton(Language.GetText("UI.WorldCreationName"), Language.GetText("UI.PlayerEmptyName"));
         uICharacterNameButton.Width = StyleDimension.FromPixelsAndPercent(0f, 1f);
         uICharacterNameButton.HAlign = 0.5f;
         uIElement.Append(uICharacterNameButton);
         _charName = uICharacterNameButton;
         uICharacterNameButton.OnLeftMouseDown += Click_Naming;
         uICharacterNameButton.SetSnapPoint("Middle", 0);
         float num = 4f;
         float num2 = 0f;
         float num3 = 0.4f;
         UIElement uIElement2 = new UIElement
         {
             HAlign = 0f,
             VAlign = 1f,
             Width = StyleDimension.FromPixelsAndPercent(0f - num, num3),
             Height = StyleDimension.FromPixelsAndPercent(-50f, 1f)
         };
         uIElement2.SetPadding(0f);
         uIElement.Append(uIElement2);
         UISlicedImage uISlicedImage = new UISlicedImage(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1))
         {
             HAlign = 1f,
             VAlign = 1f,
             Width = StyleDimension.FromPixelsAndPercent((0f - num) * 2f, 1f - num3),
             Left = StyleDimension.FromPixels(0f - num),
             Height = StyleDimension.FromPixelsAndPercent(uIElement2.Height.Pixels, uIElement2.Height.Precent)
         };
         uISlicedImage.SetSliceDepths(10);
         uISlicedImage.Color = Color.LightGray * 0.7f;
         uIElement.Append(uISlicedImage);
         float num4 = 4f;
         UIDifficultyButton uIDifficultyButton = new UIDifficultyButton(_player, Lang.menu[26], Lang.menu[31], 0, Color.Cyan)
         {
             HAlign = 0f,
             VAlign = 1f / (num4 - 1f),
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f - num2, 1f / num4)
         };
         UIDifficultyButton uIDifficultyButton2 = new UIDifficultyButton(_player, Lang.menu[25], Lang.menu[30], 1, Main.mcColor)
         {
             HAlign = 0f,
             VAlign = 2f / (num4 - 1f),
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f - num2, 1f / num4)
         };
         UIDifficultyButton uIDifficultyButton3 = new UIDifficultyButton(_player, Lang.menu[24], Lang.menu[29], 2, Main.hcColor)
         {
             HAlign = 0f,
             VAlign = 1f,
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f - num2, 1f / num4)
         };
         UIDifficultyButton uIDifficultyButton4 = new UIDifficultyButton(_player, Language.GetText("UI.Creative"), Language.GetText("UI.CreativeDescriptionPlayer"), 3, Main.creativeModeColor)
         {
             HAlign = 0f,
             VAlign = 0f,
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f - num2, 1f / num4)
         };
         UIText uIText = new UIText(Lang.menu[26])
         {
             HAlign = 0f,
             VAlign = 0.5f,
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Top = StyleDimension.FromPixelsAndPercent(15f, 0f),
             IsWrapped = true
         };
         uIText.PaddingLeft = 20f;
         uIText.PaddingRight = 20f;
         uISlicedImage.Append(uIText);
         uIElement2.Append(uIDifficultyButton4);
         uIElement2.Append(uIDifficultyButton);
         uIElement2.Append(uIDifficultyButton2);
         uIElement2.Append(uIDifficultyButton3);
         _infoContainer = uIElement;
         _difficultyDescriptionText = uIText;
         uIDifficultyButton4.OnLeftMouseDown += UpdateDifficultyDescription;
         uIDifficultyButton.OnLeftMouseDown += UpdateDifficultyDescription;
         uIDifficultyButton2.OnLeftMouseDown += UpdateDifficultyDescription;
         uIDifficultyButton3.OnLeftMouseDown += UpdateDifficultyDescription;
         UpdateDifficultyDescription(null, null);
         uIDifficultyButton4.SetSnapPoint("Middle", 1);
         uIDifficultyButton.SetSnapPoint("Middle", 2);
         uIDifficultyButton2.SetSnapPoint("Middle", 3);
         uIDifficultyButton3.SetSnapPoint("Middle", 4);
     }
References _charName, _difficultyDescriptionText, _infoContainer, _player, UIElement.Append(), Main.Assets, Click_Naming(), UISlicedImage.Color, Color, Main.creativeModeColor, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), Language.GetText(), UIElement.HAlign, Main.hcColor, UIElement.Height, UIElement.Left, Main.mcColor, Lang.menu, UIElement.OnLeftMouseDown, UIElement.PaddingBottom, UIElement.PaddingLeft, UIElement.PaddingRight, UIElement.PaddingTop, StyleDimension.Pixels, StyleDimension.Precent, UIElement.SetPadding(), UISlicedImage.SetSliceDepths(), UIElement.SetSnapPoint(), UIElement.Top, UpdateDifficultyDescription(), UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().