Terraria: UICharacterCreation.MakeHairsylesMenu
MakeHairsylesMenu()
void UICharacterCreation.MakeHairsylesMenu (UIElement middleInnerPanel) inline private
     {
         Main.Hairstyles.UpdateUnlocks();
         UIElement uIElement = new UIElement
         {
             Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
             HAlign = 0.5f,
             VAlign = 0.5f,
             Top = StyleDimension.FromPixels(6f)
         };
         middleInnerPanel.Append(uIElement);
         uIElement.SetPadding(0f);
         UIList uIList = new UIList
         {
             Width = StyleDimension.FromPixelsAndPercent(-18f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(-6f, 1f)
         };
         uIList.SetPadding(4f);
         uIElement.Append(uIList);
         UIScrollbar uIScrollbar = new UIScrollbar
         {
             HAlign = 1f,
             Height = StyleDimension.FromPixelsAndPercent(-30f, 1f),
             Top = StyleDimension.FromPixels(10f)
         };
         uIScrollbar.SetView(100f, 1000f);
         uIList.SetScrollbar(uIScrollbar);
         uIElement.Append(uIScrollbar);
         int count = Main.Hairstyles.AvailableHairstyles.Count;
         UIElement uIElement2 = new UIElement
         {
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(48 * (count / 10 + ((count % 10 != 0) ? 1 : 0)), 0f)
         };
         uIList.Add(uIElement2);
         uIElement2.SetPadding(0f);
         for (int i = 0; i < count; i++)
         {
             UIHairStyleButton uIHairStyleButton = new UIHairStyleButton(_player, Main.Hairstyles.AvailableHairstyles[i])
             {
                 Left = StyleDimension.FromPixels((float)(i % 10) * 46f + 6f),
                 Top = StyleDimension.FromPixels((float)(i / 10) * 48f + 1f)
             };
             uIHairStyleButton.SetSnapPoint("Middle", i);
             uIHairStyleButton.SkipRenderingContent(i);
             uIElement2.Append(uIHairStyleButton);
         }
         _hairstylesContainer = uIElement;
     }
References _hairstylesContainer, _player, UIList.Add(), UIElement.Append(), HairstyleUnlocksHelper.AvailableHairstyles, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), Main.Hairstyles, UIElement.HAlign, UIElement.Height, UIElement.Left, UIElement.SetPadding(), UIList.SetScrollbar(), UIElement.SetSnapPoint(), UIScrollbar.SetView(), UIHairStyleButton.SkipRenderingContent(), UIElement.Top, HairstyleUnlocksHelper.UpdateUnlocks(), UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().