Terraria: System.Xml.EncodingStreamWrapper.EncodingStreamWrapper
EncodingStreamWrapper() [2/2]
System.Xml.EncodingStreamWrapper.EncodingStreamWrapper (Stream stream, Encoding encoding, bool emitBOM) inline
Definition at line 235 of file EncodingStreamWrapper.cs.
    {
        _isReading = false;
        _encoding = encoding;
        _stream = stream;
        _encodingCode = GetSupportedEncoding(encoding);
        if (_encodingCode == SupportedEncoding.UTF8)
        {
            return;
        }
        EnsureBuffers();
        _dec = s_validatingUTF8.GetDecoder();
        _enc = _encoding.GetEncoder();
        if (emitBOM)
        {
            ReadOnlySpan<byte> preamble = _encoding.Preamble;
            if (preamble.Length > 0)
            {
                _stream.Write(preamble);
            }
        }
    }
References System.Xml.EncodingStreamWrapper._dec, System.Xml.EncodingStreamWrapper._enc, System.Xml.EncodingStreamWrapper._encoding, System.Xml.EncodingStreamWrapper._encodingCode, System.Xml.EncodingStreamWrapper._isReading, System.Xml.EncodingStreamWrapper._stream, System.Xml.Dictionary, System.Xml.EncodingStreamWrapper.EnsureBuffers(), System.Text.Encoding.GetEncoder(), System.Xml.EncodingStreamWrapper.GetSupportedEncoding(), System.Text.Encoding.Preamble, System.Xml.EncodingStreamWrapper.s_validatingUTF8, System.stream, and System.IO.Stream.Write().