Terraria: System.Xml.EncodingStreamWrapper.GetSupportedEncoding
GetSupportedEncoding()
static SupportedEncoding System.Xml.EncodingStreamWrapper.GetSupportedEncoding (Encoding encoding) inline static private
Definition at line 214 of file EncodingStreamWrapper.cs.
    {
        if (encoding == null)
        {
            return SupportedEncoding.None;
        }
        if (encoding.WebName == s_validatingUTF8.WebName)
        {
            return SupportedEncoding.UTF8;
        }
        if (encoding.WebName == s_validatingUTF16.WebName)
        {
            return SupportedEncoding.UTF16LE;
        }
        if (encoding.WebName == s_validatingBEUTF16.WebName)
        {
            return SupportedEncoding.UTF16BE;
        }
        throw new XmlException(System.SR.XmlEncodingNotSupported);
    }
References System.Xml.EncodingStreamWrapper.s_validatingBEUTF16, System.Xml.EncodingStreamWrapper.s_validatingUTF16, System.Xml.EncodingStreamWrapper.s_validatingUTF8, System.Text.Encoding.WebName, System.SR.XmlEncodingNotSupported, and System.Xml.XmlException.
Referenced by System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), and System.Xml.EncodingStreamWrapper.ProcessBuffer().