Terraria: System.Xml.EncodingStreamWrapper.ProcessBuffer
ProcessBuffer()
static ArraySegment< byte > System.Xml.EncodingStreamWrapper.ProcessBuffer (byte[] buffer, int offset, int count, Encoding encoding) inline static package
Definition at line 522 of file EncodingStreamWrapper.cs.
    {
        if (count < 4)
        {
            throw new XmlException(System.SR.UnexpectedEndOfFile);
        }
        try
        {
            SupportedEncoding supportedEncoding = GetSupportedEncoding(encoding);
            int preserve;
            SupportedEncoding supportedEncoding2 = ReadBOMEncoding(buffer[offset], buffer[offset + 1], buffer[offset + 2], buffer[offset + 3], encoding == null, out preserve);
            if (supportedEncoding != SupportedEncoding.None && supportedEncoding != supportedEncoding2)
            {
                ThrowExpectedEncodingMismatch(supportedEncoding, supportedEncoding2);
            }
            offset += 4 - preserve;
            count -= 4 - preserve;
            if (supportedEncoding2 == SupportedEncoding.UTF8)
            {
                if (buffer[offset + 1] != 63 || buffer[offset] != 60)
                {
                    return new ArraySegment<byte>(buffer, offset, count);
                }
                CheckUTF8DeclarationEncoding(buffer, offset, count, supportedEncoding2, supportedEncoding);
                return new ArraySegment<byte>(buffer, offset, count);
            }
            Encoding safeEncoding = GetSafeEncoding(supportedEncoding2);
            int byteCount = Math.Min(count, 256);
            char[] chars = new char[safeEncoding.GetMaxCharCount(byteCount)];
            int chars2 = safeEncoding.GetChars(buffer, offset, byteCount, chars, 0);
            byte[] array = new byte[s_validatingUTF8.GetMaxByteCount(chars2)];
            int bytes = s_validatingUTF8.GetBytes(chars, 0, chars2, array, 0);
            if (array[1] == 63 && array[0] == 60)
            {
                CheckUTF8DeclarationEncoding(array, 0, bytes, supportedEncoding2, supportedEncoding);
            }
            else if (supportedEncoding == SupportedEncoding.None)
            {
                throw new XmlException(System.SR.XmlDeclarationRequired);
            }
            return new ArraySegment<byte>(s_validatingUTF8.GetBytes(GetEncoding(supportedEncoding2).GetChars(buffer, offset, count)));
        }
        catch (DecoderFallbackException innerException)
        {
            throw new XmlException(System.SR.XmlInvalidBytes, innerException);
        }
    }
References System.array, System.buffer, System.byteCount, System.bytes, System.chars, System.Xml.EncodingStreamWrapper.CheckUTF8DeclarationEncoding(), System.count, System.Xml.Dictionary, System.Xml.EncodingStreamWrapper.GetEncoding(), System.Xml.EncodingStreamWrapper.GetSafeEncoding(), System.Xml.EncodingStreamWrapper.GetSupportedEncoding(), System.Math.Min(), System.offset, System.Xml.EncodingStreamWrapper.ReadBOMEncoding(), System.Xml.EncodingStreamWrapper.s_validatingUTF8, System.Xml.EncodingStreamWrapper.ThrowExpectedEncodingMismatch(), System.SR.UnexpectedEndOfFile, System.SR.XmlDeclarationRequired, System.Xml.XmlException, and System.SR.XmlInvalidBytes.
Referenced by System.Xml.XmlUTF8TextReader.SetInput().