Terraria: System.Xml.EncodingStreamWrapper.CheckUTF8DeclarationEncoding
CheckUTF8DeclarationEncoding()
static void System.Xml.EncodingStreamWrapper.CheckUTF8DeclarationEncoding (byte[] buffer, int offset, int count, SupportedEncoding e, SupportedEncoding expectedEnc) inline static private
Definition at line 382 of file EncodingStreamWrapper.cs.
    {
        byte b = 0;
        int num = -1;
        int num2 = offset + Math.Min(count, 128);
        int num3 = 0;
        int num4 = 0;
        for (num3 = offset + 2; num3 < num2; num3++)
        {
            if (b != 0)
            {
                if (buffer[num3] == b)
                {
                    b = 0;
                }
            }
            else if (buffer[num3] == 39 || buffer[num3] == 34)
            {
                b = buffer[num3];
            }
            else if (buffer[num3] == 61)
            {
                if (num4 == 1)
                {
                    num = num3;
                    break;
                }
                num4++;
            }
            else if (buffer[num3] == 63)
            {
                break;
            }
        }
        if (num == -1)
        {
            if (e != 0 && expectedEnc == SupportedEncoding.None)
            {
                throw new XmlException(System.SR.XmlDeclarationRequired);
            }
            return;
        }
        if (num < 28)
        {
            throw new XmlException(System.SR.XmlMalformedDecl);
        }
        num3 = num - 1;
        while (IsWhitespace(buffer[num3]))
        {
            num3--;
        }
        if (!Compare(s_encodingAttr, buffer, num3 - s_encodingAttr.Length + 1))
        {
            if (e == SupportedEncoding.UTF8 || expectedEnc != SupportedEncoding.None)
            {
                return;
            }
            throw new XmlException(System.SR.XmlDeclarationRequired);
        }
        for (num3 = num + 1; num3 < num2 && IsWhitespace(buffer[num3]); num3++)
        {
        }
        if (buffer[num3] != 39 && buffer[num3] != 34)
        {
            throw new XmlException(System.SR.XmlMalformedDecl);
        }
        b = buffer[num3];
        int num5 = num3++;
        for (; buffer[num3] != b && num3 < num2; num3++)
        {
        }
        if (buffer[num3] != b)
        {
            throw new XmlException(System.SR.XmlMalformedDecl);
        }
        int num6 = num5 + 1;
        int num7 = num3 - num6;
        SupportedEncoding supportedEncoding = e;
        if (num7 == s_encodingUTF8.Length && CompareCaseInsensitive(s_encodingUTF8, buffer, num6))
        {
            supportedEncoding = SupportedEncoding.UTF8;
        }
        else if (num7 == s_encodingUnicodeLE.Length && CompareCaseInsensitive(s_encodingUnicodeLE, buffer, num6))
        {
            supportedEncoding = SupportedEncoding.UTF16LE;
        }
        else if (num7 == s_encodingUnicodeBE.Length && CompareCaseInsensitive(s_encodingUnicodeBE, buffer, num6))
        {
            supportedEncoding = SupportedEncoding.UTF16BE;
        }
        else if (num7 == s_encodingUnicode.Length && CompareCaseInsensitive(s_encodingUnicode, buffer, num6))
        {
            if (e == SupportedEncoding.UTF8)
            {
                ThrowEncodingMismatch(s_safeUTF8.GetString(buffer, num6, num7), s_safeUTF8.GetString(s_encodingUTF8, 0, s_encodingUTF8.Length));
            }
        }
        else
        {
            ThrowEncodingMismatch(s_safeUTF8.GetString(buffer, num6, num7), e);
        }
        if (e != supportedEncoding)
        {
            ThrowEncodingMismatch(s_safeUTF8.GetString(buffer, num6, num7), e);
        }
    }
References System.buffer, System.Xml.EncodingStreamWrapper.Compare(), System.Xml.EncodingStreamWrapper.CompareCaseInsensitive(), System.count, System.Xml.Dictionary, System.Xml.EncodingStreamWrapper.IsWhitespace(), System.Math.Min(), System.offset, System.Xml.EncodingStreamWrapper.s_encodingAttr, System.Xml.EncodingStreamWrapper.s_encodingUnicode, System.Xml.EncodingStreamWrapper.s_encodingUnicodeBE, System.Xml.EncodingStreamWrapper.s_encodingUnicodeLE, System.Xml.EncodingStreamWrapper.s_encodingUTF8, System.Xml.EncodingStreamWrapper.s_safeUTF8, System.Xml.EncodingStreamWrapper.ThrowEncodingMismatch(), System.SR.XmlDeclarationRequired, System.Xml.XmlException, and System.SR.XmlMalformedDecl.
Referenced by System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), and System.Xml.EncodingStreamWrapper.ProcessBuffer().