Terraria: System.Xml.EncodingStreamWrapper.CleanupCharBreak
CleanupCharBreak()
void System.Xml.EncodingStreamWrapper.CleanupCharBreak () inline private
Definition at line 648 of file EncodingStreamWrapper.cs.
    {
        int num = _byteOffset + _byteCount;
        if (_byteCount % 2 != 0)
        {
            int num2 = _stream.ReadByte();
            if (num2 < 0)
            {
                throw new XmlException(System.SR.UnexpectedEndOfFile);
            }
            _bytes[num++] = (byte)num2;
            _byteCount++;
        }
        int num3 = ((_encodingCode != SupportedEncoding.UTF16LE) ? (_bytes[num - 1] + (_bytes[num - 2] << 8)) : (_bytes[num - 2] + (_bytes[num - 1] << 8)));
        if ((num3 & 0xDC00) != 56320 && num3 >= 55296 && num3 <= 56319)
        {
            int num4 = _stream.ReadByte();
            int num5 = _stream.ReadByte();
            if (num5 < 0)
            {
                throw new XmlException(System.SR.UnexpectedEndOfFile);
            }
            _bytes[num++] = (byte)num4;
            _bytes[num++] = (byte)num5;
            _byteCount += 2;
        }
    }
References System.Xml.EncodingStreamWrapper._byteCount, System.Xml.EncodingStreamWrapper._byteOffset, System.Xml.EncodingStreamWrapper._bytes, System.Xml.EncodingStreamWrapper._encodingCode, System.Xml.EncodingStreamWrapper._stream, System.Xml.Dictionary, System.IO.Stream.ReadByte(), System.SR.UnexpectedEndOfFile, and System.Xml.XmlException.
Referenced by System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), and System.Xml.EncodingStreamWrapper.Read().