Terraria: System.Xml.EncodingStreamWrapper.EncodingStreamWrapper
EncodingStreamWrapper() [1/2]
System.Xml.EncodingStreamWrapper.EncodingStreamWrapper (Stream stream, Encoding encoding) inline
Definition at line 129 of file EncodingStreamWrapper.cs.
    {
        try
        {
            _isReading = true;
            _stream = stream;
            SupportedEncoding supportedEncoding = GetSupportedEncoding(encoding);
            SupportedEncoding supportedEncoding2 = ReadBOMEncoding(encoding == null);
            if (supportedEncoding != SupportedEncoding.None && supportedEncoding != supportedEncoding2)
            {
                ThrowExpectedEncodingMismatch(supportedEncoding, supportedEncoding2);
            }
            if (supportedEncoding2 == SupportedEncoding.UTF8)
            {
                FillBuffer(2);
                if (_bytes[_byteOffset + 1] == 63 && _bytes[_byteOffset] == 60)
                {
                    FillBuffer(128);
                    CheckUTF8DeclarationEncoding(_bytes, _byteOffset, _byteCount, supportedEncoding2, supportedEncoding);
                }
                return;
            }
            EnsureBuffers();
            FillBuffer(254);
            SetReadDocumentEncoding(supportedEncoding2);
            CleanupCharBreak();
            int chars = _encoding.GetChars(_bytes, _byteOffset, _byteCount, _chars, 0);
            _byteOffset = 0;
            _byteCount = s_validatingUTF8.GetBytes(_chars, 0, chars, _bytes, 0);
            if (_bytes[1] == 63 && _bytes[0] == 60)
            {
                CheckUTF8DeclarationEncoding(_bytes, 0, _byteCount, supportedEncoding2, supportedEncoding);
            }
            else if (supportedEncoding == SupportedEncoding.None)
            {
                throw new XmlException(System.SR.XmlDeclarationRequired);
            }
        }
        catch (DecoderFallbackException innerException)
        {
            throw new XmlException(System.SR.XmlInvalidBytes, innerException);
        }
    }
References System.Xml.EncodingStreamWrapper._byteCount, System.Xml.EncodingStreamWrapper._byteOffset, System.Xml.EncodingStreamWrapper._bytes, System.Xml.EncodingStreamWrapper._chars, System.Xml.EncodingStreamWrapper._encoding, System.Xml.EncodingStreamWrapper._isReading, System.Xml.EncodingStreamWrapper._stream, System.chars, System.Xml.EncodingStreamWrapper.CheckUTF8DeclarationEncoding(), System.Xml.EncodingStreamWrapper.CleanupCharBreak(), System.Xml.Dictionary, System.Xml.EncodingStreamWrapper.EnsureBuffers(), System.Xml.EncodingStreamWrapper.FillBuffer(), System.Text.Encoding.GetChars(), System.Xml.EncodingStreamWrapper.GetSupportedEncoding(), System.Xml.EncodingStreamWrapper.ReadBOMEncoding(), System.Xml.EncodingStreamWrapper.s_validatingUTF8, System.Xml.EncodingStreamWrapper.SetReadDocumentEncoding(), System.stream, System.Xml.EncodingStreamWrapper.ThrowExpectedEncodingMismatch(), System.SR.XmlDeclarationRequired, System.Xml.XmlException, and System.SR.XmlInvalidBytes.