Terraria: System.Xml.EncodingStreamWrapper.ThrowExpectedEncodingMismatch
ThrowExpectedEncodingMismatch()
static void System.Xml.EncodingStreamWrapper.ThrowExpectedEncodingMismatch (SupportedEncoding expEnc, SupportedEncoding actualEnc) inline static private
Definition at line 570 of file EncodingStreamWrapper.cs.
    {
        throw new XmlException(System.SR.Format(System.SR.XmlExpectedEncoding, GetEncodingName(expEnc), GetEncodingName(actualEnc)));
    }
References System.Xml.Dictionary, System.SR.Format(), System.Xml.EncodingStreamWrapper.GetEncodingName(), System.Xml.XmlException, and System.SR.XmlExpectedEncoding.
Referenced by System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), and System.Xml.EncodingStreamWrapper.ProcessBuffer().