Terraria: System.Xml.EncodingStreamWrapper.Read
Read() [1/2]
override int System.Xml.EncodingStreamWrapper.Read (byte[] buffer, int offset, int count) inline
Definition at line 613 of file EncodingStreamWrapper.cs.
    {
        try
        {
            if (_byteCount == 0)
            {
                if (_encodingCode == SupportedEncoding.UTF8)
                {
                    return _stream.Read(buffer, offset, count);
                }
                _byteOffset = 0;
                _byteCount = _stream.Read(_bytes, _byteCount, (_chars.Length - 1) * 2);
                if (_byteCount == 0)
                {
                    return 0;
                }
                CleanupCharBreak();
                int chars = _encoding.GetChars(_bytes, 0, _byteCount, _chars, 0);
                _byteCount = Encoding.UTF8.GetBytes(_chars, 0, chars, _bytes, 0);
            }
            if (_byteCount < count)
            {
                count = _byteCount;
            }
            Buffer.BlockCopy(_bytes, _byteOffset, buffer, offset, count);
            _byteOffset += count;
            _byteCount -= count;
            return count;
        }
        catch (DecoderFallbackException innerException)
        {
            throw new XmlException(System.SR.XmlInvalidBytes, innerException);
        }
    }
References System.Xml.EncodingStreamWrapper._byteCount, System.Xml.EncodingStreamWrapper._byteOffset, System.Xml.EncodingStreamWrapper._bytes, System.Xml.EncodingStreamWrapper._chars, System.Xml.EncodingStreamWrapper._encoding, System.Xml.EncodingStreamWrapper._encodingCode, System.Xml.EncodingStreamWrapper._stream, System.Buffer.BlockCopy(), System.buffer, System.chars, System.Xml.EncodingStreamWrapper.CleanupCharBreak(), System.count, System.Xml.Dictionary, System.Text.Encoding.GetChars(), System.offset, System.IO.Stream.Read(), System.Text.Encoding.UTF8, System.Xml.XmlException, and System.SR.XmlInvalidBytes.