Terraria: System.Xml.EncodingStreamWrapper.Write
Write() [1/2]
override void System.Xml.EncodingStreamWrapper.Write (byte[] buffer, int offset, int count) inline
Definition at line 692 of file EncodingStreamWrapper.cs.
    {
        if (_encodingCode == SupportedEncoding.UTF8)
        {
            _stream.Write(buffer, offset, count);
            return;
        }
        while (count > 0)
        {
            int num = ((_chars.Length < count) ? _chars.Length : count);
            int chars = _dec.GetChars(buffer, offset, num, _chars, 0, flush: false);
            _byteCount = _enc.GetBytes(_chars, 0, chars, _bytes, 0, flush: false);
            _stream.Write(_bytes, 0, _byteCount);
            offset += num;
            count -= num;
        }
    }
References System.Xml.EncodingStreamWrapper._byteCount, System.Xml.EncodingStreamWrapper._bytes, System.Xml.EncodingStreamWrapper._chars, System.Xml.EncodingStreamWrapper._dec, System.Xml.EncodingStreamWrapper._enc, System.Xml.EncodingStreamWrapper._encodingCode, System.Xml.EncodingStreamWrapper._stream, System.buffer, System.chars, System.count, System.Xml.Dictionary, System.Text.Encoder.GetBytes(), System.Text.Decoder.GetChars(), System.offset, and System.IO.Stream.Write().