Terraria: System.Xml.EncodingStreamWrapper.ReadBOMEncoding
ReadBOMEncoding() [1/2]
SupportedEncoding System.Xml.EncodingStreamWrapper.ReadBOMEncoding (bool notOutOfBand) inline private
Definition at line 259 of file EncodingStreamWrapper.cs.
    {
        int num = _stream.ReadByte();
        int num2 = _stream.ReadByte();
        int num3 = _stream.ReadByte();
        int num4 = _stream.ReadByte();
        if (num4 == -1)
        {
            throw new XmlException(System.SR.UnexpectedEndOfFile);
        }
        int preserve;
        SupportedEncoding result = ReadBOMEncoding((byte)num, (byte)num2, (byte)num3, (byte)num4, notOutOfBand, out preserve);
        EnsureByteBuffer();
        switch (preserve)
        {
        case 1:
            _bytes[0] = (byte)num4;
            break;
        case 2:
            _bytes[0] = (byte)num3;
            _bytes[1] = (byte)num4;
            break;
        case 4:
            _bytes[0] = (byte)num;
            _bytes[1] = (byte)num2;
            _bytes[2] = (byte)num3;
            _bytes[3] = (byte)num4;
            break;
        }
        _byteCount = preserve;
        return result;
    }
References System.Xml.EncodingStreamWrapper._byteCount, System.Xml.EncodingStreamWrapper._bytes, System.Xml.EncodingStreamWrapper._stream, System.Xml.Dictionary, System.Xml.EncodingStreamWrapper.EnsureByteBuffer(), System.Xml.EncodingStreamWrapper.ReadBOMEncoding(), System.IO.Stream.ReadByte(), System.SR.UnexpectedEndOfFile, and System.Xml.XmlException.
Referenced by System.Xml.EncodingStreamWrapper.EncodingStreamWrapper(), System.Xml.EncodingStreamWrapper.ProcessBuffer(), and System.Xml.EncodingStreamWrapper.ReadBOMEncoding().