Terraria: Film.AddSequence
AddSequence()
void Film.AddSequence (int start, int duration, FrameEvent frameEvent) inline
     {
         _sequences.Add(new Sequence(frameEvent, start, duration));
         _nextSequenceAppendTime = Math.Max(_nextSequenceAppendTime, start + duration);
         _frameCount = Math.Max(_frameCount, start + duration);
     }
References _frameCount, _nextSequenceAppendTime, and _sequences.
Referenced by DD2Film.DD2Film(), AddSequences(), AppendEmptySequence(), and AppendSequence().