Terraria: System.Xml.Xsl.XslCompiledTransform.CheckArguments
CheckArguments() [1/2]
static void System.Xml.Xsl.XslCompiledTransform.CheckArguments (object input, object results) inline static private
Definition at line 307 of file XslCompiledTransform.cs.
    {
        if (input == null)
        {
            throw new ArgumentNullException("input");
        }
        if (results == null)
        {
            throw new ArgumentNullException("results");
        }
    }
References System.Xml.Dictionary, and System.input.
Referenced by System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), and System.Xml.Xsl.XslCompiledTransform.Transform().