Terraria: System.Net.NameResolutionPal.GetAddrInfoExState.FromHandleAndFree
FromHandleAndFree()
static GetAddrInfoExState System.Net.NameResolutionPal.GetAddrInfoExState.FromHandleAndFree (IntPtr handle) inline static
Definition at line 133 of file NameResolutionPal.cs.
        {
            GCHandle gCHandle = GCHandle.FromIntPtr(handle);
            GetAddrInfoExState result = (GetAddrInfoExState)gCHandle.Target;
            gCHandle.Free();
            return result;
        }
References System.Net.NameResolutionPal.GetAddrInfoExState.GetAddrInfoExState(), System.Runtime.InteropServices.GCHandle.Free(), System.Runtime.InteropServices.GCHandle.FromIntPtr(), System.handle, and System.Runtime.InteropServices.GCHandle.Target.
Referenced by System.Net.NameResolutionPal.ProcessResult().