Terraria: System.Xml.Xsl.XslCompiledTransform.Load
Load() [6/8]
void System.Xml.Xsl.XslCompiledTransform.Load (Type compiledStylesheet) inline
Definition at line 140 of file XslCompiledTransform.cs.
    {
        Reset();
        if (compiledStylesheet == null)
        {
            throw new ArgumentNullException("compiledStylesheet");
        }
        object[] customAttributes = compiledStylesheet.GetCustomAttributes(typeof(GeneratedCodeAttribute), inherit: false);
        GeneratedCodeAttribute generatedCodeAttribute = ((customAttributes.Length != 0) ? ((GeneratedCodeAttribute)customAttributes[0]) : null);
        if (generatedCodeAttribute != null && generatedCodeAttribute.Tool == typeof(XslCompiledTransform).FullName)
        {
            if (s_version < Version.Parse(generatedCodeAttribute.Version))
            {
                throw new ArgumentException(System.SR.Format(System.SR.Xslt_IncompatibleCompiledStylesheetVersion, generatedCodeAttribute.Version, s_version), "compiledStylesheet");
            }
            FieldInfo field = compiledStylesheet.GetField("staticData", BindingFlags.Static | BindingFlags.NonPublic);
            FieldInfo field2 = compiledStylesheet.GetField("ebTypes", BindingFlags.Static | BindingFlags.NonPublic);
            if (field != null && field2 != null && field.GetValue(null) is byte[] queryData)
            {
                MethodInfo method = compiledStylesheet.GetMethod("Execute", BindingFlags.Static | BindingFlags.NonPublic);
                Type[] earlyBoundTypes = (Type[])field2.GetValue(null);
                Load(method, queryData, earlyBoundTypes);
                return;
            }
        }
        if (_command == null)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Xslt_NotCompiledStylesheet, compiledStylesheet.FullName), "compiledStylesheet");
        }
    }
References System.Xml.Xsl.XslCompiledTransform._command, System.Xml.ArgumentException, System.Xml.Dictionary, System.SR.Format(), System.Xml.Xsl.XslCompiledTransform.Load(), System.Version.Parse(), System.Xml.Xsl.XslCompiledTransform.Reset(), System.Xml.Xsl.XslCompiledTransform.s_version, System.SR.Xslt_IncompatibleCompiledStylesheetVersion, and System.SR.Xslt_NotCompiledStylesheet.