Terraria: System.Xml.Xsl.XslCompiledTransform.Transform
Transform() [9/15]
void System.Xml.Xsl.XslCompiledTransform.Transform (string inputUri, XsltArgumentList? arguments, TextWriter results) inline
Definition at line 259 of file XslCompiledTransform.cs.
    {
        CheckArguments(inputUri, results);
        using XmlReader input = XmlReader.Create(inputUri);
        using XmlWriter xmlWriter = XmlWriter.Create(results, OutputSettings);
        Transform(input, arguments, xmlWriter, CreateDefaultResolver());
        xmlWriter.Close();
    }
References System.Xml.Xsl.XslCompiledTransform.CheckArguments(), System.Xml.XmlReader.Create(), System.Xml.XmlWriter.Create(), System.Xml.Xsl.XslCompiledTransform.CreateDefaultResolver(), System.Xml.Dictionary, System.input, System.Xml.Xsl.XslCompiledTransform.OutputSettings, and System.Xml.Xsl.XslCompiledTransform.Transform().