Terraria: System.Xml.Xsl.XslCompiledTransform.Reset
Reset()
void System.Xml.Xsl.XslCompiledTransform.Reset () inline private
Definition at line 38 of file XslCompiledTransform.cs.
    {
        _compilerErrorColl = null;
        _outputSettings = null;
        _qil = null;
        _command = null;
    }
References System.Xml.Xsl.XslCompiledTransform._command, System.Xml.Xsl.XslCompiledTransform._compilerErrorColl, System.Xml.Xsl.XslCompiledTransform._outputSettings, and System.Xml.Xsl.XslCompiledTransform._qil.
Referenced by System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Load(), and System.Xml.Xsl.XslCompiledTransform.Load().