Terraria: System.Net.NameResolutionPal.GetAddrInfoExState.RegisterForCancellation
RegisterForCancellation()
unsafe void System.Net.NameResolutionPal.GetAddrInfoExState.RegisterForCancellation (CancellationToken cancellationToken) inline
Definition at line 57 of file NameResolutionPal.cs.
        {
            if (!cancellationToken.CanBeCanceled)
            {
                return;
            }
            lock (this)
            {
                if (_cancellationContext == null)
                {
                    return;
                }
                _cancellationRegistration = cancellationToken.UnsafeRegister(delegate(object o)
                {
                    GetAddrInfoExState getAddrInfoExState = (GetAddrInfoExState)o;
                    int num = 0;
                    lock (getAddrInfoExState)
                    {
                        GetAddrInfoExContext* cancellationContext = getAddrInfoExState._cancellationContext;
                        if (cancellationContext != null)
{
                            num = global::Interop.Winsock.GetAddrInfoExCancel(&cancellationContext->CancelHandle);
                        }
                    }
                    if (num != 0 && num != 6 && System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(getAddrInfoExState, $"GetAddrInfoExCancel returned error {num}", "RegisterForCancellation");
                    }
                }, this);
            }
        }
References System.Net.NameResolutionPal.GetAddrInfoExState.GetAddrInfoExState(), System.Net.NameResolutionPal.GetAddrInfoExState._cancellationContext, System.Net.NameResolutionPal.GetAddrInfoExState._cancellationRegistration, System.Net.NameResolutionPal.GetAddrInfoExContext.CancelHandle, System.cancellationToken, System.Net.NetEventSource.Info(), and System.Net.NetEventSource.Log.
Referenced by System.Net.NameResolutionPal.GetAddrInfoAsync().