Terraria: System.Xml.Xsl.XslCompiledTransform.CreateDefaultResolver
CreateDefaultResolver()
static XmlResolver System.Xml.Xsl.XslCompiledTransform.CreateDefaultResolver () inline static private
Definition at line 340 of file XslCompiledTransform.cs.
    {
        if (System.LocalAppContextSwitches.AllowDefaultResolver)
        {
            return new XmlUrlResolver();
        }
        return XmlNullResolver.Singleton;
    }
References System.LocalAppContextSwitches.AllowDefaultResolver, and System.Xml.XmlNullResolver.Singleton.
Referenced by System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Load(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), and System.Xml.Xsl.XslCompiledTransform.Transform().