Terraria: System.Net.Http.Http2Connection.ProcessAltSvcFrame
ProcessAltSvcFrame()
void System.Net.Http.Http2Connection.ProcessAltSvcFrame (FrameHeader frameHeader) inline private
Definition at line 2221 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{frameHeader}", "ProcessAltSvcFrame");
        }
        ReadOnlySpan<byte> readOnlySpan = _incomingBuffer.ActiveSpan.Slice(0, frameHeader.PayloadLength);
        if (BinaryPrimitives.TryReadUInt16BigEndian(readOnlySpan, out var value))
        {
            readOnlySpan = readOnlySpan.Slice(2);
            if ((frameHeader.StreamId != 0 && value == 0) || (frameHeader.StreamId == 0 && readOnlySpan.Length >= value && readOnlySpan.Slice(0, value).SequenceEqual(_pool.Http2AltSvcOriginUri)))
            {
                readOnlySpan = readOnlySpan.Slice(value);
                string @string = Encoding.ASCII.GetString(readOnlySpan);
                _pool.HandleAltSvc(new string[1] { @string }, null);
            }
        }
        _incomingBuffer.Discard(frameHeader.PayloadLength);
    }
References System.Net.Http.Http2Connection._incomingBuffer, System.Net.Http.Http2Connection._pool, System.Text.Encoding.ASCII, System.Net.Http.HttpConnectionPool.HandleAltSvc(), System.Net.Http.HttpConnectionPool.Http2AltSvcOriginUri, System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.Trace(), System.Buffers.Binary.BinaryPrimitives.TryReadUInt16BigEndian(), and System.value.
Referenced by System.Net.Http.Http2Connection.ProcessIncomingFramesAsync().