Terraria: System.Net.Http.Http2Connection.SendPingAsync
SendPingAsync()
Task System.Net.Http.Http2Connection.SendPingAsync (long pingContent, bool isAck = false) inline private
Definition at line 2583 of file Http2Connection.cs.
    {
        return PerformWriteAsync(17, (this, pingContent, isAck), delegate((Http2Connection thisRef, long pingContent, bool isAck) state, Memory<byte> writeBuffer)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                state.thisRef.Trace($"Started writing. {"pingContent"}={state.pingContent}", "SendPingAsync");
            }
            Span<byte> span = writeBuffer.Span;
            FrameHeader.WriteTo(span, 8, FrameType.Ping, state.isAck ? FrameFlags.EndStream : FrameFlags.None, 0);
            BinaryPrimitives.WriteInt64BigEndian(span.Slice(9), state.pingContent);
            return true;
        });
    }
References System.Net.NetEventSource.Log, System.state, System.Buffers.Binary.BinaryPrimitives.WriteInt64BigEndian(), and System.Net.Http.Http2Connection.FrameHeader.WriteTo().
Referenced by System.Net.Http.Http2Connection.RttEstimator.OnDataOrHeadersReceived(), System.Net.Http.Http2Connection.ProcessPingFrame(), and System.Net.Http.Http2Connection.VerifyKeepAlive().