Terraria: System.Net.Http.Http2Connection.FlushOutgoingBytesAsync
FlushOutgoingBytesAsync()
async Task System.Net.Http.Http2Connection.FlushOutgoingBytesAsync () inline private
Definition at line 1969 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{"ActiveLength"}={_outgoingBuffer.ActiveLength}", "FlushOutgoingBytesAsync");
        }
        if (_outgoingBuffer.ActiveLength > 0)
        {
            try
            {
                await _stream.WriteAsync(_outgoingBuffer.ActiveMemory).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch (Exception abortException)
            {
                Abort(abortException);
            }
            _lastPendingWriterShouldFlush = false;
            _outgoingBuffer.Discard(_outgoingBuffer.ActiveLength);
        }
    }
References System.Net.Http.Http2Connection._lastPendingWriterShouldFlush, System.Net.Http.Http2Connection._outgoingBuffer, System.Net.Http.Http2Connection._stream, System.Net.Abort, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.Trace(), and System.IO.Stream.WriteAsync().
Referenced by System.Net.Http.Http2Connection.ProcessOutgoingFramesAsync().