Terraria: System.Net.Http.Http2Connection.ProcessOutgoingFramesAsync
ProcessOutgoingFramesAsync()
async Task System.Net.Http.Http2Connection.ProcessOutgoingFramesAsync () inline private
Definition at line 2506 of file Http2Connection.cs.
    {
        _ = 2;
        try
        {
            while (await _writeChannel.Reader.WaitToReadAsync().ConfigureAwait(continueOnCapturedContext: false))
            {
                WriteQueueEntry writeEntry;
                while (_writeChannel.Reader.TryRead(out writeEntry))
                {
                    if (_abortException != null)
                    {
                        if (writeEntry.TryDisableCancellation())
{
                            writeEntry.SetException(_abortException);
                        }
                        continue;
                    }
                    int writeBytes = writeEntry.WriteBytes;
                    int capacity = _outgoingBuffer.Capacity;
                    if (capacity >= 32768)
                    {
                        int activeLength = _outgoingBuffer.ActiveLength;
                        if (writeBytes >= capacity - activeLength)
{
                            await FlushOutgoingBytesAsync().ConfigureAwait(continueOnCapturedContext: false);
                        }
                    }
                    if (!writeEntry.TryDisableCancellation())
                    {
                        continue;
                    }
                    _outgoingBuffer.EnsureAvailableSpace(writeBytes);
                    try
                    {
                        if (System.Net.NetEventSource.Log.IsEnabled())
{
                            Trace($"{"writeBytes"}={writeBytes}", "ProcessOutgoingFramesAsync");
                        }
                        bool flag = writeEntry.InvokeWriteAction(_outgoingBuffer.AvailableMemorySliced(writeBytes));
                        writeEntry.SetResult();
                        _outgoingBuffer.Commit(writeBytes);
                        _lastPendingWriterShouldFlush |= flag;
                    }
                    catch (Exception exception)
                    {
                        writeEntry.SetException(exception);
                    }
                }
                if (_lastPendingWriterShouldFlush)
                {
                    await FlushOutgoingBytesAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
            }
        }
        catch (Exception value)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"Unexpected exception in {"ProcessOutgoingFramesAsync"}: {value}", "ProcessOutgoingFramesAsync");
            }
        }
    }
References System.Net.Http.Http2Connection._abortException, System.Net.Http.Http2Connection._lastPendingWriterShouldFlush, System.Net.Http.Http2Connection._outgoingBuffer, System.Net.Http.Http2Connection._writeChannel, System.capacity, System.exception, System.Net.Http.Http2Connection.FlushOutgoingBytesAsync(), System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.ProcessOutgoingFramesAsync(), System.Net.Http.Http2Connection.Trace(), and System.value.
Referenced by System.Net.Http.Http2Connection.ProcessOutgoingFramesAsync(), and System.Net.Http.Http2Connection.SetupAsync().