Terraria: System.Net.Http.Http2Connection.ProcessGoAwayFrame
ProcessGoAwayFrame()
void System.Net.Http.Http2Connection.ProcessGoAwayFrame (FrameHeader frameHeader) inline private
Definition at line 2449 of file Http2Connection.cs.
    {
        if (frameHeader.PayloadLength < 8)
        {
            ThrowProtocolError(Http2ProtocolErrorCode.FrameSizeError);
        }
        if (frameHeader.StreamId != 0)
        {
            ThrowProtocolError();
        }
        int num = (int)(BinaryPrimitives.ReadUInt32BigEndian(_incomingBuffer.ActiveSpan) & 0x7FFFFFFF);
        Http2ProtocolErrorCode http2ProtocolErrorCode = (Http2ProtocolErrorCode)BinaryPrimitives.ReadInt32BigEndian(_incomingBuffer.ActiveSpan.Slice(4));
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace(frameHeader.StreamId, $"{"lastStreamId"}={num}, {"errorCode"}={http2ProtocolErrorCode}", "ProcessGoAwayFrame");
        }
        _incomingBuffer.Discard(frameHeader.PayloadLength);
        Exception resetException = new Http2ConnectionException(http2ProtocolErrorCode);
        _rttEstimator.OnGoAwayReceived();
        List<Http2Stream> list = new List<Http2Stream>();
        lock (SyncObject)
        {
            Shutdown();
            foreach (KeyValuePair<int, Http2Stream> httpStream in _httpStreams)
            {
                int key = httpStream.Key;
                if (key > num)
                {
                    list.Add(httpStream.Value);
                }
            }
        }
        foreach (Http2Stream item in list)
        {
            item.OnReset(resetException, null, canRetry: true);
        }
    }
References System.Net.Http.Http2Connection._httpStreams, System.Net.Http.Http2Connection._incomingBuffer, System.Net.Http.Http2Connection._rttEstimator, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.item, System.key, System.list, System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.RttEstimator.OnGoAwayReceived(), System.Buffers.Binary.BinaryPrimitives.ReadInt32BigEndian(), System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(), System.Net.Http.Http2Connection.Shutdown(), System.Net.Http.Http2Connection.SyncObject, System.Net.Http.Http2Connection.ThrowProtocolError(), and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.ProcessIncomingFramesAsync().