Terraria: System.Net.Http.Http2Connection.ReadFrameAsync
ReadFrameAsync()
async ValueTask< FrameHeader > System.Net.Http.Http2Connection.ReadFrameAsync (bool initialFrame = false) inline private
Definition at line 1990 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{"initialFrame"}={initialFrame}", "ReadFrameAsync");
        }
        if (_incomingBuffer.ActiveLength < 9)
        {
            _incomingBuffer.EnsureAvailableSpace(9 - _incomingBuffer.ActiveLength);
            do
            {
                int num = await _stream.ReadAsync(_incomingBuffer.AvailableMemory).ConfigureAwait(continueOnCapturedContext: false);
                _incomingBuffer.Commit(num);
                if (num == 0)
                {
                    if (_incomingBuffer.ActiveLength == 0)
                    {
                        ThrowMissingFrame();
                    }
                    else
                    {
                        ThrowPrematureEOF(9);
                    }
                }
            }
            while (_incomingBuffer.ActiveLength < 9);
        }
        FrameHeader frameHeader = FrameHeader.ReadFrom(_incomingBuffer.ActiveSpan);
        if (frameHeader.PayloadLength > 16384)
        {
            if (initialFrame && System.Net.NetEventSource.Log.IsEnabled())
            {
                string @string = Encoding.ASCII.GetString(_incomingBuffer.ActiveSpan.Slice(0, Math.Min(20, _incomingBuffer.ActiveLength)));
                Trace("HTTP/2 handshake failed. Server returned " + @string, "ReadFrameAsync");
            }
            _incomingBuffer.Discard(9);
            ThrowProtocolError(initialFrame ? Http2ProtocolErrorCode.ProtocolError : Http2ProtocolErrorCode.FrameSizeError);
        }
        _incomingBuffer.Discard(9);
        if (_incomingBuffer.ActiveLength < frameHeader.PayloadLength)
        {
            _incomingBuffer.EnsureAvailableSpace(frameHeader.PayloadLength - _incomingBuffer.ActiveLength);
            do
            {
                int num2 = await _stream.ReadAsync(_incomingBuffer.AvailableMemory).ConfigureAwait(continueOnCapturedContext: false);
                _incomingBuffer.Commit(num2);
                if (num2 == 0)
                {
                    ThrowPrematureEOF(frameHeader.PayloadLength);
                }
            }
            while (_incomingBuffer.ActiveLength < frameHeader.PayloadLength);
        }
        return frameHeader;
        static void ThrowMissingFrame()
        {
            throw new IOException(System.SR.net_http_invalid_response_missing_frame);
        }
        void ThrowPrematureEOF(int requiredBytes)
        {
            throw new IOException(System.SR.Format(System.SR.net_http_invalid_response_premature_eof_bytecount, requiredBytes - _incomingBuffer.ActiveLength));
        }
    }
References System.Net.Http.Http2Connection._incomingBuffer, System.Net.Http.Http2Connection._stream, System.Text.Encoding.ASCII, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.SR.Format(), System.Net.NetEventSource.Log, System.Math.Min(), System.SR.net_http_invalid_response_missing_frame, System.SR.net_http_invalid_response_premature_eof_bytecount, System.IO.Stream.ReadAsync(), System.Net.Http.Http2Connection.FrameHeader.ReadFrom(), System.Net.Http.Http2Connection.ThrowProtocolError(), and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.ProcessHeadersFrame(), and System.Net.Http.Http2Connection.ProcessIncomingFramesAsync().