Terraria: System.Net.Http.Http2Connection.ProcessDataFrame
ProcessDataFrame()
void System.Net.Http.Http2Connection.ProcessDataFrame (FrameHeader frameHeader) inline private
Definition at line 2241 of file Http2Connection.cs.
    {
        Http2Stream stream = GetStream(frameHeader.StreamId);
        ReadOnlySpan<byte> frameData = GetFrameData(_incomingBuffer.ActiveSpan.Slice(0, frameHeader.PayloadLength), frameHeader.PaddedFlag, hasPriority: false);
        if (stream != null)
        {
            bool endStreamFlag = frameHeader.EndStreamFlag;
            stream.OnResponseData(frameData, endStreamFlag);
            if (!endStreamFlag && frameData.Length > 0)
            {
                _rttEstimator.OnDataOrHeadersReceived(this);
            }
        }
        if (frameData.Length > 0)
        {
            ExtendWindow(frameData.Length);
        }
        _incomingBuffer.Discard(frameHeader.PayloadLength);
    }
References System.Net.Http.Http2Connection._incomingBuffer, System.Net.Http.Http2Connection._rttEstimator, System.Net.Http.Http2Connection.ExtendWindow(), System.Net.Http.Http2Connection.GetFrameData(), System.Net.Http.Http2Connection.GetStream(), System.Net.Http.Http2Connection.RttEstimator.OnDataOrHeadersReceived(), and System.stream.
Referenced by System.Net.Http.Http2Connection.ProcessIncomingFramesAsync().