Terraria: System.Net.Http.Http2Connection.SendAsync
SendAsync()
async Task< HttpResponseMessage > System.Net.Http.Http2Connection.SendAsync (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline
Definition at line 3115 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{request}", "SendAsync");
        }
        try
        {
            bool mustFlush = request.Content != null && request.HasHeaders && request.Headers.ExpectContinue == true;
            Http2Stream http2Stream = await SendHeadersAsync(request, cancellationToken, mustFlush).ConfigureAwait(continueOnCapturedContext: false);
            bool flag = request.Content != null && request.Content.AllowDuplex;
            CancellationToken cancellationToken2 = (flag ? CancellationToken.None : cancellationToken);
            Task requestBodyTask = http2Stream.SendRequestBodyAsync(cancellationToken2);
            Task responseHeadersTask = http2Stream.ReadResponseHeadersAsync(cancellationToken);
            bool flag2 = requestBodyTask.IsCompleted || !flag;
            bool flag3 = flag2;
            if (!flag3)
            {
                flag3 = await Task.WhenAny(requestBodyTask, responseHeadersTask).ConfigureAwait(continueOnCapturedContext: false) == requestBodyTask;
            }
            if (flag3 || requestBodyTask.IsCompleted || http2Stream.SendRequestFinished)
            {
                try
                {
                    await requestBodyTask.ConfigureAwait(continueOnCapturedContext: false);
                }
                catch (Exception value)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        Trace($"Sending request content failed: {value}", "SendAsync");
                    }
                    LogExceptions(responseHeadersTask);
                    throw;
                }
            }
            else
            {
                LogExceptions(requestBodyTask);
            }
            await responseHeadersTask.ConfigureAwait(continueOnCapturedContext: false);
            return http2Stream.GetAndClearResponse();
        }
        catch (Exception ex)
        {
            if (ex is IOException || ex is ObjectDisposedException || ex is Http2ProtocolException || ex is InvalidOperationException)
            {
                throw new HttpRequestException(System.SR.net_http_client_execution_error, ex);
            }
            throw;
        }
    }
References System.cancellationToken, System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionBase.LogExceptions(), System.SR.net_http_client_execution_error, System.Net.Http.Http2Connection.SendHeadersAsync(), System.Net.Http.Http2Connection.Trace(), System.value, and System.Threading.Tasks.Task< TResult >.WhenAny().