Terraria: System.Net.Http.Http2Connection.ProcessPingFrame
ProcessPingFrame()
void System.Net.Http.Http2Connection.ProcessPingFrame (FrameHeader frameHeader) inline private
Definition at line 2364 of file Http2Connection.cs.
    {
        if (frameHeader.StreamId != 0)
        {
            ThrowProtocolError();
        }
        if (frameHeader.PayloadLength != 8)
        {
            ThrowProtocolError(Http2ProtocolErrorCode.FrameSizeError);
        }
        ReadOnlySpan<byte> source = _incomingBuffer.ActiveSpan.Slice(0, 8);
        long num = BinaryPrimitives.ReadInt64BigEndian(source);
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"Received PING frame, content:{num} ack: {frameHeader.AckFlag}", "ProcessPingFrame");
        }
        if (frameHeader.AckFlag)
        {
            ProcessPingAck(num);
        }
        else
        {
            LogExceptions(SendPingAsync(num, isAck: true));
        }
        _incomingBuffer.Discard(frameHeader.PayloadLength);
    }
References System.Net.Http.Http2Connection._incomingBuffer, System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionBase.LogExceptions(), System.Net.Http.Http2Connection.ProcessPingAck(), System.Buffers.Binary.BinaryPrimitives.ReadInt64BigEndian(), System.Net.Http.Http2Connection.SendPingAsync(), System.source, System.Net.Http.Http2Connection.ThrowProtocolError(), and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.ProcessIncomingFramesAsync().