Terraria: System.Net.Http.Http2Connection.WriteHeaderCollection
WriteHeaderCollection()
void System.Net.Http.Http2Connection.WriteHeaderCollection (HttpRequestMessage request, HttpHeaders headers, ref System::Net::ArrayBuffer headerBuffer) inline private
Definition at line 2726 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("", "WriteHeaderCollection");
        }
        if (headers.HeaderStore == null)
        {
            return;
        }
        HeaderEncodingSelector<HttpRequestMessage> requestHeaderEncodingSelector = _pool.Settings._requestHeaderEncodingSelector;
        foreach (KeyValuePair<HeaderDescriptor, object> item in headers.HeaderStore)
        {
            int storeValuesIntoStringArray = HttpHeaders.GetStoreValuesIntoStringArray(item.Key, item.Value, ref t_headerValues);
            ReadOnlySpan<string> readOnlySpan = t_headerValues.AsSpan(0, storeValuesIntoStringArray);
            Encoding valueEncoding = requestHeaderEncodingSelector?.Invoke(item.Key.Name, request);
            KnownHeader knownHeader = item.Key.KnownHeader;
            if (knownHeader != null)
            {
                if (knownHeader == KnownHeaders.Host || knownHeader == KnownHeaders.Connection || knownHeader == KnownHeaders.Upgrade || knownHeader == KnownHeaders.ProxyConnection)
                {
                    continue;
                }
                if (item.Key.KnownHeader == KnownHeaders.TE)
                {
                    ReadOnlySpan<string> readOnlySpan2 = readOnlySpan;
                    for (int i = 0; i < readOnlySpan2.Length; i++)
                    {
                        string text = readOnlySpan2[i];
                        if (string.Equals(text, "trailers", StringComparison.OrdinalIgnoreCase))
{
                            WriteBytes(knownHeader.Http2EncodedName, ref headerBuffer);
                            WriteLiteralHeaderValue(text, valueEncoding, ref headerBuffer);
                            break;
                        }
                    }
                }
                else
                {
                    WriteBytes(knownHeader.Http2EncodedName, ref headerBuffer);
                    string separator = null;
                    if (readOnlySpan.Length > 1)
                    {
                        HttpHeaderParser parser = item.Key.Parser;
                        separator = ((parser == null || !parser.SupportsMultipleValues) ? ", " : parser.Separator);
                    }
                    WriteLiteralHeaderValues(readOnlySpan, separator, valueEncoding, ref headerBuffer);
                }
            }
            else
            {
                WriteLiteralHeader(item.Key.Name, readOnlySpan, valueEncoding, ref headerBuffer);
            }
        }
    }
References System.Net.Http.Http2Connection._pool, System.Net.Http.HttpConnectionSettings._requestHeaderEncodingSelector, System.Net.Http.Headers.KnownHeaders.Connection, System.Net.Equals, System.Net.Http.Headers.HttpHeaders.GetStoreValuesIntoStringArray(), System.Net.Http.Headers.KnownHeaders.Host, System.item, System.Net.NetEventSource.Log, System.Net.Http.Headers.KnownHeaders.ProxyConnection, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.Http2Connection.t_headerValues, System.Net.Http.Headers.KnownHeaders.TE, System.text, System.Net.Http.Http2Connection.Trace(), System.Net.Http.Headers.KnownHeaders.Upgrade, System.Net.Http.Http2Connection.WriteBytes(), System.Net.Http.Http2Connection.WriteLiteralHeader(), System.Net.Http.Http2Connection.WriteLiteralHeaderValue(), and System.Net.Http.Http2Connection.WriteLiteralHeaderValues().
Referenced by System.Net.Http.Http2Connection.WriteHeaders().