Terraria: System.Net.Http.Http2Connection.VerifyKeepAlive
VerifyKeepAlive()
void System.Net.Http.Http2Connection.VerifyKeepAlive () inline private
Definition at line 3207 of file Http2Connection.cs.
    {
        if (_keepAlivePingPolicy == HttpKeepAlivePingPolicy.WithActiveRequests)
        {
            lock (SyncObject)
            {
                if (_streamsInUse == 0)
                {
                    return;
                }
            }
        }
        long tickCount = Environment.TickCount64;
        switch (_keepAliveState)
        {
        case KeepAliveState.None:
            if (tickCount > _nextPingRequestTimestamp)
            {
                _keepAliveState = KeepAliveState.PingSent;
                _keepAlivePingTimeoutTimestamp = tickCount + _keepAlivePingTimeout;
                long pingContent = Interlocked.Increment(ref _keepAlivePingPayload);
                SendPingAsync(pingContent);
            }
            break;
        case KeepAliveState.PingSent:
            if (tickCount > _keepAlivePingTimeoutTimestamp)
            {
                ThrowProtocolError();
            }
            break;
        }
    }
References System.Net.Http.Http2Connection._keepAlivePingPayload, System.Net.Http.Http2Connection._keepAlivePingPolicy, System.Net.Http.Http2Connection._keepAlivePingTimeout, System.Net.Http.Http2Connection._keepAlivePingTimeoutTimestamp, System.Net.Http.Http2Connection._keepAliveState, System.Net.Http.Http2Connection._nextPingRequestTimestamp, System.Net.Http.Http2Connection._streamsInUse, System.Threading.Interlocked.Increment(), System.Net.Http.Http2Connection.SendPingAsync(), System.Net.Http.Http2Connection.SyncObject, System.Net.Http.Http2Connection.ThrowProtocolError(), and System.Environment.TickCount64.
Referenced by System.Net.Http.Http2Connection.HeartBeat().