Terraria: System.Net.Http.Http2Connection.ProcessSettingsFrame
ProcessSettingsFrame()
void System.Net.Http.Http2Connection.ProcessSettingsFrame (FrameHeader frameHeader, bool initialFrame = false) inline private
Definition at line 2261 of file Http2Connection.cs.
    {
        if (frameHeader.StreamId != 0)
        {
            ThrowProtocolError();
        }
        if (frameHeader.AckFlag)
        {
            if (frameHeader.PayloadLength != 0)
            {
                ThrowProtocolError(Http2ProtocolErrorCode.FrameSizeError);
            }
            if (!_expectingSettingsAck)
            {
                ThrowProtocolError();
            }
            _expectingSettingsAck = false;
            _rttEstimator.OnInitialSettingsAckReceived(this);
            return;
        }
        if (frameHeader.PayloadLength % 6 != 0)
        {
            ThrowProtocolError(Http2ProtocolErrorCode.FrameSizeError);
        }
        ReadOnlySpan<byte> source = _incomingBuffer.ActiveSpan.Slice(0, frameHeader.PayloadLength);
        bool flag = false;
        while (source.Length > 0)
        {
            ushort num = BinaryPrimitives.ReadUInt16BigEndian(source);
            source = source.Slice(2);
            uint num2 = BinaryPrimitives.ReadUInt32BigEndian(source);
            source = source.Slice(4);
            switch ((SettingId)num)
            {
            case SettingId.MaxConcurrentStreams:
                ChangeMaxConcurrentStreams(num2);
                flag = true;
                break;
            case SettingId.InitialWindowSize:
                if (num2 > int.MaxValue)
                {
                    ThrowProtocolError(Http2ProtocolErrorCode.FlowControlError);
                }
                ChangeInitialWindowSize((int)num2);
                break;
            case SettingId.MaxFrameSize:
                if (num2 < 16384 || num2 > 16777215)
                {
                    ThrowProtocolError();
                }
                break;
            }
        }
        if (initialFrame && !flag)
        {
            ChangeMaxConcurrentStreams(2147483647u);
        }
        _incomingBuffer.Discard(frameHeader.PayloadLength);
        LogExceptions(SendSettingsAckAsync());
    }
References System.Net.Http.Http2Connection._expectingSettingsAck, System.Net.Http.Http2Connection._incomingBuffer, System.Net.Http.Http2Connection._rttEstimator, System.Net.Http.Http2Connection.ChangeInitialWindowSize(), System.Net.Http.Http2Connection.ChangeMaxConcurrentStreams(), System.Net.Http.HttpConnectionBase.LogExceptions(), System.Net.Http.Http2Connection.RttEstimator.OnInitialSettingsAckReceived(), System.Buffers.Binary.BinaryPrimitives.ReadUInt16BigEndian(), System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(), System.Net.Http.Http2Connection.SendSettingsAckAsync(), System.source, and System.Net.Http.Http2Connection.ThrowProtocolError().
Referenced by System.Net.Http.Http2Connection.ProcessIncomingFramesAsync().