Terraria: System.Net.Http.Http2Connection.Abort
Abort()
void System.Net.Http.Http2Connection.Abort (Exception abortException) inline private
Definition at line 3047 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{"abortException"}=={abortException}", "Abort");
        }
        List<Http2Stream> list = new List<Http2Stream>();
        lock (SyncObject)
        {
            if (_abortException != null)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Abort called while already aborting. {"abortException"}={abortException}", "Abort");
                }
                return;
            }
            _abortException = abortException;
            Shutdown();
            foreach (KeyValuePair<int, Http2Stream> httpStream in _httpStreams)
            {
                int key = httpStream.Key;
                list.Add(httpStream.Value);
            }
        }
        foreach (Http2Stream item in list)
        {
            item.OnReset(_abortException);
        }
    }
References System.Net.Http.Http2Connection._abortException, System.Net.Http.Http2Connection._httpStreams, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.item, System.key, System.list, System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.Shutdown(), System.Net.Http.Http2Connection.SyncObject, and System.Net.Http.Http2Connection.Trace().