Terraria: System.Net.Http.Http2Connection.ExtendWindow
ExtendWindow()
void System.Net.Http.Http2Connection.ExtendWindow (int amount) inline private
Definition at line 3015 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{"amount"}={amount}", "ExtendWindow");
        }
        int pendingWindowUpdate;
        lock (SyncObject)
        {
            _pendingWindowUpdate += amount;
            if (_pendingWindowUpdate < 8388608)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"{"_pendingWindowUpdate"} {_pendingWindowUpdate} < {8388608}.", "ExtendWindow");
                }
                return;
            }
            pendingWindowUpdate = _pendingWindowUpdate;
            _pendingWindowUpdate = 0;
        }
        LogExceptions(SendWindowUpdateAsync(0, pendingWindowUpdate));
    }
References System.Net.Http.Http2Connection._pendingWindowUpdate, System.Net.NetEventSource.Log, System.Net.Http.HttpConnectionBase.LogExceptions(), System.Net.Http.Http2Connection.SendWindowUpdateAsync(), System.Net.Http.Http2Connection.SyncObject, and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.ProcessDataFrame().