Terraria: System.Net.Http.Http2Connection.ProcessIncomingFramesAsync
ProcessIncomingFramesAsync()
async Task System.Net.Http.Http2Connection.ProcessIncomingFramesAsync () inline private
Definition at line 2054 of file Http2Connection.cs.
    {
        _ = 3;
        try
        {
            try
            {
                FrameHeader frameHeader = await ReadFrameAsync(initialFrame: true).ConfigureAwait(continueOnCapturedContext: false);
                if (frameHeader.Type != FrameType.Settings || frameHeader.AckFlag)
                {
                    ThrowProtocolError();
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Frame 0: {frameHeader}.", "ProcessIncomingFramesAsync");
                }
                ProcessSettingsFrame(frameHeader, initialFrame: true);
            }
            catch (IOException innerException)
            {
                throw new IOException(System.SR.net_http_http2_connection_not_established, innerException);
            }
            long frameNum = 1L;
            while (true)
            {
                if (_incomingBuffer.ActiveLength < 9)
                {
                    _incomingBuffer.EnsureAvailableSpace(9 - _incomingBuffer.ActiveLength);
                    int num;
                    do
                    {
                        num = await _stream.ReadAsync(_incomingBuffer.AvailableMemory).ConfigureAwait(continueOnCapturedContext: false);
                        _incomingBuffer.Commit(num);
                    }
                    while (num != 0 && _incomingBuffer.ActiveLength < 9);
                }
                FrameHeader frameHeader = await ReadFrameAsync().ConfigureAwait(continueOnCapturedContext: false);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Frame {frameNum}: {frameHeader}.", "ProcessIncomingFramesAsync");
                }
                RefreshPingTimestamp();
                switch (frameHeader.Type)
                {
                case FrameType.Headers:
                    await ProcessHeadersFrame(frameHeader).ConfigureAwait(continueOnCapturedContext: false);
                    break;
                case FrameType.Data:
                    ProcessDataFrame(frameHeader);
                    break;
                case FrameType.Settings:
                    ProcessSettingsFrame(frameHeader);
                    break;
                case FrameType.Priority:
                    ProcessPriorityFrame(frameHeader);
                    break;
                case FrameType.Ping:
                    ProcessPingFrame(frameHeader);
                    break;
                case FrameType.WindowUpdate:
                    ProcessWindowUpdateFrame(frameHeader);
                    break;
                case FrameType.RstStream:
                    ProcessRstStreamFrame(frameHeader);
                    break;
                case FrameType.GoAway:
                    ProcessGoAwayFrame(frameHeader);
                    break;
                case FrameType.AltSvc:
                    ProcessAltSvcFrame(frameHeader);
                    break;
                default:
                    ThrowProtocolError();
                    break;
                }
                frameNum++;
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace("ProcessIncomingFramesAsync: " + ex.Message, "ProcessIncomingFramesAsync");
            }
            Abort(ex);
        }
    }
References System.Net.Http.Http2Connection._incomingBuffer, System.Net.Http.Http2Connection._stream, System.Net.Abort, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.L, System.Net.NetEventSource.Log, System.SR.net_http_http2_connection_not_established, System.Net.Http.Http2Connection.ProcessAltSvcFrame(), System.Net.Http.Http2Connection.ProcessDataFrame(), System.Net.Http.Http2Connection.ProcessGoAwayFrame(), System.Net.Http.Http2Connection.ProcessHeadersFrame(), System.Net.Http.Http2Connection.ProcessPingFrame(), System.Net.Http.Http2Connection.ProcessPriorityFrame(), System.Net.Http.Http2Connection.ProcessRstStreamFrame(), System.Net.Http.Http2Connection.ProcessSettingsFrame(), System.Net.Http.Http2Connection.ProcessWindowUpdateFrame(), System.IO.Stream.ReadAsync(), System.Net.Http.Http2Connection.ReadFrameAsync(), System.Net.Http.Http2Connection.RefreshPingTimestamp(), System.Net.Http.Http2Connection.ThrowProtocolError(), and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.SetupAsync().