Terraria: System.Net.Http.Http2Connection.SendRstStreamAsync
SendRstStreamAsync()
Task System.Net.Http.Http2Connection.SendRstStreamAsync (int streamId, Http2ProtocolErrorCode errorCode) inline private
Definition at line 2598 of file Http2Connection.cs.
    {
        return PerformWriteAsync(13, (this, streamId, errorCode), delegate((Http2Connection thisRef, int streamId, Http2ProtocolErrorCode errorCode) s, Memory<byte> writeBuffer)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                s.thisRef.Trace(s.streamId, $"Started writing. {"errorCode"}={s.errorCode}", "SendRstStreamAsync");
            }
            Span<byte> span = writeBuffer.Span;
            FrameHeader.WriteTo(span, 4, FrameType.RstStream, FrameFlags.None, s.streamId);
            BinaryPrimitives.WriteInt32BigEndian(span.Slice(9), (int)s.errorCode);
            return true;
        });
    }
References System.Net.NetEventSource.Log, System.s, System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(), and System.Net.Http.Http2Connection.FrameHeader.WriteTo().
Referenced by System.Net.Http.Http2Connection.Http2Stream.SendReset().