Terraria: System.Net.Http.Http2Connection.ProcessPingAck
ProcessPingAck()
void System.Net.Http.Http2Connection.ProcessPingAck (long payload) inline private
Definition at line 3189 of file Http2Connection.cs.
    {
        if (payload < 0)
        {
            _rttEstimator.OnPingAckReceived(payload, this);
            return;
        }
        if (_keepAliveState != KeepAliveState.PingSent)
        {
            ThrowProtocolError();
        }
        if (Interlocked.Read(ref _keepAlivePingPayload) != payload)
        {
            ThrowProtocolError();
        }
        _keepAliveState = KeepAliveState.None;
    }
References System.Net.Http.Http2Connection._keepAlivePingPayload, System.Net.Http.Http2Connection._keepAliveState, System.Net.Http.Http2Connection._rttEstimator, System.Net.Http.Http2Connection.RttEstimator.OnPingAckReceived(), System.Threading.Interlocked.Read(), and System.Net.Http.Http2Connection.ThrowProtocolError().
Referenced by System.Net.Http.Http2Connection.ProcessPingFrame().