Terraria: System.Net.Http.Http2Connection.WriteHeaders
WriteHeaders()
void System.Net.Http.Http2Connection.WriteHeaders (HttpRequestMessage request, ref System::Net::ArrayBuffer headerBuffer) inline private
Definition at line 2782 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("", "WriteHeaders");
        }
        if (request.HasHeaders && request.Headers.TransferEncodingChunked == true)
        {
            request.Headers.TransferEncodingChunked = false;
        }
        HttpMethod httpMethod = HttpMethod.Normalize(request.Method);
        if ((object)httpMethod == HttpMethod.Get)
        {
            WriteIndexedHeader(2, ref headerBuffer);
        }
        else if ((object)httpMethod == HttpMethod.Post)
        {
            WriteIndexedHeader(3, ref headerBuffer);
        }
        else
        {
            WriteIndexedHeader(2, httpMethod.Method, ref headerBuffer);
        }
        WriteIndexedHeader((_stream is SslStream) ? 7 : 6, ref headerBuffer);
        if (request.HasHeaders && request.Headers.Host != null)
        {
            WriteIndexedHeader(1, request.Headers.Host, ref headerBuffer);
        }
        else
        {
            WriteBytes(_pool._http2EncodedAuthorityHostHeader, ref headerBuffer);
        }
        string pathAndQuery = request.RequestUri.PathAndQuery;
        if (pathAndQuery == "/")
        {
            WriteIndexedHeader(4, ref headerBuffer);
        }
        else
        {
            WriteIndexedHeader(4, pathAndQuery, ref headerBuffer);
        }
        if (request.HasHeaders)
        {
            WriteHeaderCollection(request, request.Headers, ref headerBuffer);
        }
        if (_pool.Settings._useCookies)
        {
            string cookieHeader = _pool.Settings._cookieContainer.GetCookieHeader(request.RequestUri);
            if (cookieHeader != string.Empty)
            {
                WriteBytes(KnownHeaders.Cookie.Http2EncodedName, ref headerBuffer);
                Encoding valueEncoding = _pool.Settings._requestHeaderEncodingSelector?.Invoke(KnownHeaders.Cookie.Name, request);
                WriteLiteralHeaderValue(cookieHeader, valueEncoding, ref headerBuffer);
            }
        }
        if (request.Content == null)
        {
            if (httpMethod.MustHaveRequestBody)
            {
                WriteBytes(KnownHeaders.ContentLength.Http2EncodedName, ref headerBuffer);
                WriteLiteralHeaderValue("0", null, ref headerBuffer);
            }
        }
        else
        {
            WriteHeaderCollection(request, request.Content.Headers, ref headerBuffer);
        }
    }
References System.Net.Http.HttpConnectionSettings._cookieContainer, System.Net.Http.HttpConnectionPool._http2EncodedAuthorityHostHeader, System.Net.Http.Http2Connection._pool, System.Net.Http.HttpConnectionSettings._requestHeaderEncodingSelector, System.Net.Http.Http2Connection._stream, System.Net.Http.HttpConnectionSettings._useCookies, System.Net.Http.Headers.KnownHeaders.ContentLength, System.Net.Http.Headers.KnownHeaders.Cookie, System.Net.Http.HttpMethod.Get, System.Net.CookieContainer.GetCookieHeader(), System.Net.NetEventSource.Log, System.Net.Http.HttpMethod.Normalize(), System.Net.Http.HttpMethod.Post, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.Http2Connection.Trace(), System.Net.Http.Http2Connection.WriteBytes(), System.Net.Http.Http2Connection.WriteHeaderCollection(), System.Net.Http.Http2Connection.WriteIndexedHeader(), and System.Net.Http.Http2Connection.WriteLiteralHeaderValue().
Referenced by System.Net.Http.Http2Connection.SendHeadersAsync().