Terraria: System.Net.Http.Http2Connection.ProcessWindowUpdateFrame
ProcessWindowUpdateFrame()
void System.Net.Http.Http2Connection.ProcessWindowUpdateFrame (FrameHeader frameHeader) inline private
Definition at line 2391 of file Http2Connection.cs.
    {
        if (frameHeader.PayloadLength != 4)
        {
            ThrowProtocolError(Http2ProtocolErrorCode.FrameSizeError);
        }
        int num = BinaryPrimitives.ReadInt32BigEndian(_incomingBuffer.ActiveSpan) & 0x7FFFFFFF;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{frameHeader}. {"amount"}={num}", "ProcessWindowUpdateFrame");
        }
        if (num == 0)
        {
            ThrowProtocolError();
        }
        _incomingBuffer.Discard(frameHeader.PayloadLength);
        if (frameHeader.StreamId == 0)
        {
            _connectionWindow.AdjustCredit(num);
        }
        else
        {
            GetStream(frameHeader.StreamId)?.OnWindowUpdate(num);
        }
    }
References System.Net.Http.Http2Connection._connectionWindow, System.Net.Http.Http2Connection._incomingBuffer, System.Net.Http.CreditManager.AdjustCredit(), System.Net.Http.Http2Connection.GetStream(), System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.Http2Stream.OnWindowUpdate(), System.Buffers.Binary.BinaryPrimitives.ReadInt32BigEndian(), System.Net.Http.Http2Connection.ThrowProtocolError(), and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.ProcessIncomingFramesAsync().