Terraria: System.Net.Http.Http2Connection.RemoveStream
RemoveStream()
void System.Net.Http.Http2Connection.RemoveStream (Http2Stream http2Stream) inline private
Definition at line 3168 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace(http2Stream.StreamId, "", "RemoveStream");
        }
        lock (SyncObject)
        {
            if (!_httpStreams.Remove(http2Stream.StreamId))
            {
                return;
            }
        }
        ReleaseStream();
    }
References System.Net.Http.Http2Connection._httpStreams, System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.ReleaseStream(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Net.Http.Http2Connection.SyncObject, and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.Http2Stream.Complete().