Terraria: System.Net.Http.Http2Connection.Trace
Trace() [2/2]
override void System.Net.Http.Http2Connection.Trace (string message, [CallerMemberName] string memberName = null) inline
Implements System.Net.Http.IHttpTrace.
Definition at line 3245 of file Http2Connection.cs.
    {
        Trace(0, message, memberName);
    }
References System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.Abort(), System.Net.Http.Http2Connection.ChangeInitialWindowSize(), System.Net.Http.Http2Connection.ChangeMaxConcurrentStreams(), System.Net.Http.HttpConnectionPool.DisableHttp2Connection(), System.Net.Http.Http2Connection.Dispose(), System.Net.Http.Http2Connection.ExtendWindow(), System.Net.Http.Http2Connection.FinalTeardown(), System.Net.Http.Http2Connection.FlushOutgoingBytesAsync(), System.Net.Http.Http2Connection.HeartBeat(), System.Net.Http.HttpConnectionPool.InvalidateHttp2Connection(), System.Net.Http.Http2Connection.RttEstimator.OnDataOrHeadersReceived(), System.Net.Http.Http2Connection.RttEstimator.OnPingAckReceived(), System.Net.Http.Http2Connection.ProcessAltSvcFrame(), System.Net.Http.Http2Connection.ProcessGoAwayFrame(), System.Net.Http.Http2Connection.ProcessHeadersFrame(), System.Net.Http.Http2Connection.ProcessIncomingFramesAsync(), System.Net.Http.Http2Connection.ProcessOutgoingFramesAsync(), System.Net.Http.Http2Connection.ProcessPingFrame(), System.Net.Http.Http2Connection.ProcessRstStreamFrame(), System.Net.Http.Http2Connection.ProcessWindowUpdateFrame(), System.Net.Http.Http2Connection.ReadFrameAsync(), System.Net.Http.Http2Connection.RttEstimator.RefreshRtt(), System.Net.Http.Http2Connection.ReleaseStream(), System.Net.Http.Http2Connection.RemoveStream(), System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(), System.Net.Http.Http2Connection.SendAsync(), System.Net.Http.Http2Connection.SetupAsync(), System.Net.Http.Http2Connection.Shutdown(), System.Net.Http.Http2Connection.SignalAvailableStreamsWaiter(), System.Net.Http.Http2Connection.SignalShutdownWaiter(), System.Net.Http.Http2Connection.Http2Stream.Trace(), System.Net.Http.Http2Connection.Trace(), System.Net.Http.Http2Connection.WriteBytes(), System.Net.Http.Http2Connection.WriteHeaderCollection(), System.Net.Http.Http2Connection.WriteHeaders(), System.Net.Http.Http2Connection.WriteIndexedHeader(), System.Net.Http.Http2Connection.WriteIndexedHeader(), System.Net.Http.Http2Connection.WriteLiteralHeader(), System.Net.Http.Http2Connection.WriteLiteralHeaderValue(), and System.Net.Http.Http2Connection.WriteLiteralHeaderValues().