Terraria: System.Net.Http.Http2Connection.AddStream
AddStream()
void System.Net.Http.Http2Connection.AddStream (Http2Stream http2Stream) inline private
Definition at line 2851 of file Http2Connection.cs.
    {
        lock (SyncObject)
        {
            if (_nextStream == int.MaxValue)
            {
                Shutdown();
            }
            if (_abortException != null)
            {
                throw GetRequestAbortedException(_abortException);
            }
            if (_shutdown)
            {
                ThrowRetry(System.SR.net_http_server_shutdown);
            }
            if (_streamsInUse > _maxConcurrentStreams)
            {
                ThrowRetry(System.SR.net_http_request_aborted);
            }
            http2Stream.Initialize(_nextStream, _initialServerStreamWindowSize);
            _nextStream += 2;
            _httpStreams.Add(http2Stream.StreamId, http2Stream);
        }
    }
References System.Net.Http.Http2Connection._abortException, System.Net.Http.Http2Connection._httpStreams, System.Net.Http.Http2Connection._initialServerStreamWindowSize, System.Net.Http.Http2Connection._maxConcurrentStreams, System.Net.Http.Http2Connection._nextStream, System.Net.Http.Http2Connection._shutdown, System.Net.Http.Http2Connection._streamsInUse, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.Http2Connection.GetRequestAbortedException(), System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.SR.net_http_request_aborted, System.SR.net_http_server_shutdown, System.Net.Http.Http2Connection.Shutdown(), System.Net.Http.Http2Connection.SyncObject, and System.Net.Http.Http2Connection.ThrowRetry().