Terraria: System.Net.Http.Http2Connection.Shutdown
Shutdown()
void System.Net.Http.Http2Connection.Shutdown () inline private
Definition at line 1866 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{"_shutdown"}={_shutdown}, {"_abortException"}={_abortException}", "Shutdown");
        }
        SignalAvailableStreamsWaiter(result: false);
        SignalShutdownWaiter();
        _shutdown = true;
    }
References System.Net.Http.Http2Connection._abortException, System.Net.Http.Http2Connection._shutdown, System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.SignalAvailableStreamsWaiter(), System.Net.Http.Http2Connection.SignalShutdownWaiter(), and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.Abort(), System.Net.Http.Http2Connection.AddStream(), and System.Net.Http.Http2Connection.ProcessGoAwayFrame().