Terraria: System.Net.Http.Http2Connection.FinalTeardown
FinalTeardown()
void System.Net.Http.Http2Connection.FinalTeardown () inline private
Definition at line 3078 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace("", "FinalTeardown");
        }
        GC.SuppressFinalize(this);
        _stream.Dispose();
        _connectionWindow.Dispose();
        _writeChannel.Writer.Complete();
        if (HttpTelemetry.Log.IsEnabled() && Interlocked.Exchange(ref _markedByTelemetryStatus, 2) == 1)
        {
            HttpTelemetry.Log.Http20ConnectionClosed();
        }
    }
References System.Net.Http.Http2Connection._connectionWindow, System.Net.Http.Http2Connection._markedByTelemetryStatus, System.Net.Http.Http2Connection._stream, System.Net.Http.Http2Connection._writeChannel, System.Net.Http.CreditManager.Dispose(), System.IO.Stream.Dispose(), System.Threading.Interlocked.Exchange(), System.Net.Http.HttpTelemetry.Log, System.Net.NetEventSource.Log, System.GC.SuppressFinalize(), and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.Dispose(), and System.Net.Http.Http2Connection.ReleaseStream().