Terraria: System.Net.Http.Http2Connection.SendStreamDataAsync
SendStreamDataAsync()
async Task System.Net.Http.Http2Connection.SendStreamDataAsync (int streamId, ReadOnlyMemory< byte > buffer, bool finalFlush, CancellationToken cancellationToken) inline private
Definition at line 2947 of file Http2Connection.cs.
    {
        ReadOnlyMemory<byte> remaining = buffer;
        while (remaining.Length > 0)
        {
            int frameSize = Math.Min(remaining.Length, 16384);
            frameSize = await _connectionWindow.RequestCreditAsync(frameSize, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            (ReadOnlyMemory<byte>, ReadOnlyMemory<byte>) tuple = SplitBuffer(remaining, frameSize);
            ReadOnlyMemory<byte> item = tuple.Item1;
            remaining = tuple.Item2;
            bool item2 = false;
            if (finalFlush && remaining.Length == 0)
            {
                item2 = true;
            }
            if (!_connectionWindow.IsCreditAvailable)
            {
                item2 = true;
            }
            try
            {
                await PerformWriteAsync(9 + item.Length, (this, streamId, item, item2), delegate((Http2Connection thisRef, int streamId, ReadOnlyMemory<byte> current, bool flush) s, Memory<byte> writeBuffer)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        s.thisRef.Trace(s.streamId, $"Started writing. {"Length"}={writeBuffer.Length}", "SendStreamDataAsync");
                    }
                    FrameHeader.WriteTo(writeBuffer.Span, s.current.Length, FrameType.Data, FrameFlags.None, s.streamId);
                    s.current.CopyTo(writeBuffer.Slice(9));
                    return s.flush;
                }, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            catch
            {
                _connectionWindow.AdjustCredit(frameSize);
                throw;
            }
        }
    }
References System.Net.Http.Http2Connection._connectionWindow, System.Net.Http.CreditManager.AdjustCredit(), System.buffer, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Http.CreditManager.IsCreditAvailable, System.item, System.Net.NetEventSource.Log, System.Math.Min(), System.Net.Http.CreditManager.RequestCreditAsync(), System.s, System.Net.Http.Http2Connection.SplitBuffer(), and System.Net.Http.Http2Connection.FrameHeader.WriteTo().
Referenced by System.Net.Http.Http2Connection.Http2Stream.SendDataAsync().