Terraria: System.Net.Http.Http2Connection.SendHeadersAsync
SendHeadersAsync()
async ValueTask< Http2Stream > System.Net.Http.Http2Connection.SendHeadersAsync (HttpRequestMessage request, CancellationToken cancellationToken, bool mustFlush) inline private
Definition at line 2877 of file Http2Connection.cs.
    {
        System.Net.ArrayBuffer headerBuffer = default(System.Net.ArrayBuffer);
        try
        {
            if (HttpTelemetry.Log.IsEnabled())
            {
                HttpTelemetry.Log.RequestHeadersStart();
            }
            headerBuffer = new System.Net.ArrayBuffer(4096, usePool: true);
            WriteHeaders(request, ref headerBuffer);
            ReadOnlyMemory<byte> item = headerBuffer.ActiveMemory;
            int num = (item.Length - 1) / 16384 + 1;
            int writeBytes = item.Length + num * 9;
            Http2Stream http2Stream = new Http2Stream(request, this);
            await PerformWriteAsync(writeBytes, (this, http2Stream, item, request.Content == null, mustFlush), delegate((Http2Connection thisRef, Http2Stream http2Stream, ReadOnlyMemory<byte> headerBytes, bool endStream, bool mustFlush) s, Memory<byte> writeBuffer)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    s.thisRef.Trace(s.http2Stream.StreamId, $"Started writing. Total header bytes={s.headerBytes.Length}", "SendHeadersAsync");
                }
                s.thisRef.AddStream(s.http2Stream);
                Span<byte> destination = writeBuffer.Span;
                (ReadOnlyMemory<byte> first, ReadOnlyMemory<byte> rest) tuple = SplitBuffer(s.headerBytes, 16384);
                ReadOnlyMemory<byte> item2 = tuple.first;
                ReadOnlyMemory<byte> item3 = tuple.rest;
                FrameFlags frameFlags = ((item3.Length == 0) ? FrameFlags.EndHeaders : FrameFlags.None);
                frameFlags |= (s.endStream ? FrameFlags.EndStream : FrameFlags.None);
                FrameHeader.WriteTo(destination, item2.Length, FrameType.Headers, frameFlags, s.http2Stream.StreamId);
                destination = destination.Slice(9);
                item2.Span.CopyTo(destination);
                destination = destination.Slice(item2.Length);
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    s.thisRef.Trace(s.http2Stream.StreamId, $"Wrote HEADERS frame. Length={item2.Length}, flags={frameFlags}", "SendHeadersAsync");
                }
                while (item3.Length > 0)
                {
                    (ReadOnlyMemory<byte> first, ReadOnlyMemory<byte> rest) tuple2 = SplitBuffer(item3, 16384);
                    item2 = tuple2.first;
                    item3 = tuple2.rest;
                    frameFlags = ((item3.Length == 0) ? FrameFlags.EndHeaders : FrameFlags.None);
                    FrameHeader.WriteTo(destination, item2.Length, FrameType.Continuation, frameFlags, s.http2Stream.StreamId);
                    destination = destination.Slice(9);
                    item2.Span.CopyTo(destination);
                    destination = destination.Slice(item2.Length);
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        s.thisRef.Trace(s.http2Stream.StreamId, $"Wrote CONTINUATION frame. Length={item2.Length}, flags={frameFlags}", "SendHeadersAsync");
                    }
                }
                return s.mustFlush || s.endStream;
            }, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            if (HttpTelemetry.Log.IsEnabled())
            {
                HttpTelemetry.Log.RequestHeadersStop();
            }
            return http2Stream;
        }
        catch
        {
            ReleaseStream();
            throw;
        }
        finally
        {
            headerBuffer.Dispose();
        }
    }
References System.cancellationToken, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.destination, System.Net.Http.Http2Connection.first, System.item, System.Net.Http.HttpTelemetry.Log, System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.ReleaseStream(), System.s, System.Net.Http.Http2Connection.SplitBuffer(), System.Net.Http.Http2Connection.WriteHeaders(), and System.Net.Http.Http2Connection.FrameHeader.WriteTo().
Referenced by System.Net.Http.Http2Connection.SendAsync().