Terraria: System.Net.Http.Http2Connection.SetupAsync
SetupAsync()
async ValueTask System.Net.Http.Http2Connection.SetupAsync () inline
Definition at line 1806 of file Http2Connection.cs.
    {
        try
        {
            _outgoingBuffer.EnsureAvailableSpace(s_http2ConnectionPreface.Length + 9 + 6 + 9 + 4);
            s_http2ConnectionPreface.AsSpan().CopyTo(_outgoingBuffer.AvailableSpan);
            _outgoingBuffer.Commit(s_http2ConnectionPreface.Length);
            FrameHeader.WriteTo(_outgoingBuffer.AvailableSpan, 12, FrameType.Settings, FrameFlags.None, 0);
            _outgoingBuffer.Commit(9);
            BinaryPrimitives.WriteUInt16BigEndian(_outgoingBuffer.AvailableSpan, 2);
            _outgoingBuffer.Commit(2);
            BinaryPrimitives.WriteUInt32BigEndian(_outgoingBuffer.AvailableSpan, 0u);
            _outgoingBuffer.Commit(4);
            BinaryPrimitives.WriteUInt16BigEndian(_outgoingBuffer.AvailableSpan, 4);
            _outgoingBuffer.Commit(2);
            BinaryPrimitives.WriteUInt32BigEndian(_outgoingBuffer.AvailableSpan, (uint)_pool.Settings._initialHttp2StreamWindowSize);
            _outgoingBuffer.Commit(4);
            uint value = 67043329u;
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"Initial connection-level WINDOW_UPDATE, windowUpdateAmount={value}", "SetupAsync");
            }
            FrameHeader.WriteTo(_outgoingBuffer.AvailableSpan, 4, FrameType.WindowUpdate, FrameFlags.None, 0);
            _outgoingBuffer.Commit(9);
            BinaryPrimitives.WriteUInt32BigEndian(_outgoingBuffer.AvailableSpan, value);
            _outgoingBuffer.Commit(4);
            await _stream.WriteAsync(_outgoingBuffer.ActiveMemory).ConfigureAwait(continueOnCapturedContext: false);
            _rttEstimator.OnInitialSettingsSent();
            _outgoingBuffer.Discard(_outgoingBuffer.ActiveLength);
            _expectingSettingsAck = true;
        }
        catch (Exception innerException)
        {
            Dispose();
            throw new IOException(System.SR.net_http_http2_connection_not_established, innerException);
        }
        ProcessIncomingFramesAsync();
        ProcessOutgoingFramesAsync();
    }
References System.Net.Http.Http2Connection._expectingSettingsAck, System.Net.Http.HttpConnectionSettings._initialHttp2StreamWindowSize, System.Net.Http.Http2Connection._outgoingBuffer, System.Net.Http.Http2Connection._pool, System.Net.Http.Http2Connection._rttEstimator, System.Net.Http.Http2Connection._stream, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.Http2Connection.Dispose(), System.Net.NetEventSource.Log, System.SR.net_http_http2_connection_not_established, System.Net.Http.Http2Connection.RttEstimator.OnInitialSettingsSent(), System.Net.Http.Http2Connection.ProcessIncomingFramesAsync(), System.Net.Http.Http2Connection.ProcessOutgoingFramesAsync(), System.Net.Http.Http2Connection.s_http2ConnectionPreface, System.Net.Http.HttpConnectionPool.Settings, System.Net.Http.Http2Connection.Trace(), System.value, System.IO.Stream.WriteAsync(), System.Net.Http.Http2Connection.FrameHeader.WriteTo(), System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(), and System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian().