Terraria: System.Net.Http.Http2Connection.WriteLiteralHeader
WriteLiteralHeader()
void System.Net.Http.Http2Connection.WriteLiteralHeader (string name, ReadOnlySpan< string > values, Encoding valueEncoding, ref System::Net::ArrayBuffer headerBuffer) inline private
Definition at line 2670 of file Http2Connection.cs.
    {
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            Trace($"{"name"}={name}, {"values"}={string.Join(", ", values.ToArray())}", "WriteLiteralHeader");
        }
        int bytesWritten;
        while (!HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewName(name, values, ", ", valueEncoding, headerBuffer.AvailableSpan, out bytesWritten))
        {
            headerBuffer.EnsureAvailableSpace(headerBuffer.AvailableLength + 1);
        }
        headerBuffer.Commit(bytesWritten);
    }
References System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingNewName(), System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.Trace(), and System.values.
Referenced by System.Net.Http.Http2Connection.WriteHeaderCollection().