Terraria: System.Net.Http.Http2Connection.ThrowProtocolError
ThrowProtocolError() [1/2]
static void System.Net.Http.Http2Connection.ThrowProtocolError () inline static private
Definition at line 3273 of file Http2Connection.cs.
    {
        ThrowProtocolError(Http2ProtocolErrorCode.ProtocolError);
    }
References System.Net.Http.Http2Connection.ThrowProtocolError().
Referenced by System.Net.Http.Http2Connection.GetFrameData(), System.Net.Http.Http2Connection.GetStream(), System.Net.Http.Http2Connection.Http2Stream.OnHeadersComplete(), System.Net.Http.Http2Connection.Http2Stream.OnHeadersStart(), System.Net.Http.Http2Connection.RttEstimator.OnPingAckReceived(), System.Net.Http.Http2Connection.Http2Stream.OnResponseData(), System.Net.Http.Http2Connection.ProcessGoAwayFrame(), System.Net.Http.Http2Connection.ProcessHeadersFrame(), System.Net.Http.Http2Connection.ProcessIncomingFramesAsync(), System.Net.Http.Http2Connection.ProcessPingAck(), System.Net.Http.Http2Connection.ProcessPingFrame(), System.Net.Http.Http2Connection.ProcessPriorityFrame(), System.Net.Http.Http2Connection.ProcessRstStreamFrame(), System.Net.Http.Http2Connection.ProcessSettingsFrame(), System.Net.Http.Http2Connection.ProcessWindowUpdateFrame(), System.Net.Http.Http2Connection.ReadFrameAsync(), System.Net.Http.Http2Connection.ThrowProtocolError(), and System.Net.Http.Http2Connection.VerifyKeepAlive().