Terraria: System.Net.Http.Http2Connection.ChangeMaxConcurrentStreams
ChangeMaxConcurrentStreams()
void System.Net.Http.Http2Connection.ChangeMaxConcurrentStreams (uint newValue) inline private
Definition at line 2322 of file Http2Connection.cs.
    {
        lock (SyncObject)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"{"newValue"}={newValue}, {"_streamsInUse"}={_streamsInUse}, {"_availableStreamsWaiter"}?={_availableStreamsWaiter != null}", "ChangeMaxConcurrentStreams");
            }
            _maxConcurrentStreams = newValue;
            if (_streamsInUse < _maxConcurrentStreams)
            {
                SignalAvailableStreamsWaiter(result: true);
            }
        }
    }
References System.Net.Http.Http2Connection._availableStreamsWaiter, System.Net.Http.Http2Connection._maxConcurrentStreams, System.Net.Http.Http2Connection._streamsInUse, System.Net.NetEventSource.Log, System.Net.Http.Http2Connection.SignalAvailableStreamsWaiter(), System.Net.Http.Http2Connection.SyncObject, and System.Net.Http.Http2Connection.Trace().
Referenced by System.Net.Http.Http2Connection.ProcessSettingsFrame().