Terraria: System.Text.Json.JsonDocument.Parse
Parse() [5/7]
static void System.Text.Json.JsonDocument.Parse (ReadOnlySpan< byte > utf8JsonSpan, JsonReaderOptions readerOptions, ref MetadataDb database, ref StackRowStack stack) inline static private
Definition at line 949 of file JsonDocument.cs.
    {
        bool flag = false;
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        Utf8JsonReader utf8JsonReader = new Utf8JsonReader(utf8JsonSpan, isFinalBlock: true, new JsonReaderState(readerOptions));
        while (utf8JsonReader.Read())
        {
            JsonTokenType tokenType = utf8JsonReader.TokenType;
            int num4 = (int)utf8JsonReader.TokenStartIndex;
            switch (tokenType)
            {
            case JsonTokenType.StartObject:
            {
                if (flag)
                {
                    num++;
                }
                num3++;
                database.Append(tokenType, num4, -1);
                StackRow row2 = new StackRow(num2 + 1);
                stack.Push(row2);
                num2 = 0;
                break;
            }
            case JsonTokenType.EndObject:
            {
                int index = database.FindIndexOfFirstUnsetSizeOrLength(JsonTokenType.StartObject);
                num3++;
                num2++;
                database.SetLength(index, num2);
                int length2 = database.Length;
                database.Append(tokenType, num4, utf8JsonReader.ValueSpan.Length);
                database.SetNumberOfRows(index, num2);
                database.SetNumberOfRows(length2, num2);
                num2 += stack.Pop().SizeOrLength;
                break;
            }
            case JsonTokenType.StartArray:
            {
                if (flag)
                {
                    num++;
                }
                num2++;
                database.Append(tokenType, num4, -1);
                StackRow row = new StackRow(num, num3 + 1);
                stack.Push(row);
                num = 0;
                num3 = 0;
                break;
            }
            case JsonTokenType.EndArray:
            {
                int num5 = database.FindIndexOfFirstUnsetSizeOrLength(JsonTokenType.StartArray);
                num3++;
                num2++;
                database.SetLength(num5, num);
                database.SetNumberOfRows(num5, num3);
                if (num + 1 != num3)
                {
                    database.SetHasComplexChildren(num5);
                }
                int length = database.Length;
                database.Append(tokenType, num4, utf8JsonReader.ValueSpan.Length);
                database.SetNumberOfRows(length, num3);
                StackRow stackRow = stack.Pop();
                num = stackRow.SizeOrLength;
                num3 += stackRow.NumberOfRows;
                break;
            }
            case JsonTokenType.PropertyName:
                num3++;
                num2++;
                database.Append(tokenType, num4 + 1, utf8JsonReader.ValueSpan.Length);
                if (utf8JsonReader._stringHasEscaping)
                {
                    database.SetHasComplexChildren(database.Length - 12);
                }
                break;
            default:
                num3++;
                num2++;
                if (flag)
                {
                    num++;
                }
                if (tokenType == JsonTokenType.String)
                {
                    database.Append(tokenType, num4 + 1, utf8JsonReader.ValueSpan.Length);
                    if (utf8JsonReader._stringHasEscaping)
                    {
                        database.SetHasComplexChildren(database.Length - 12);
                    }
                }
                else
                {
                    database.Append(tokenType, num4, utf8JsonReader.ValueSpan.Length);
                }
                break;
            }
            flag = utf8JsonReader.IsInArray;
        }
        database.CompleteAllocations();
    }
References System.Text.Json.Dictionary, System.index, System.Text.Json.JsonDocument.int, System.length, System.length2, and System.Text.Json.Utf8JsonReader.TokenType.
Referenced by System.Text.Json.JsonDocument.Parse(), System.Text.Json.JsonDocument.Parse(), System.Text.Json.JsonDocument.Parse(), System.Text.Json.JsonDocument.Parse(), System.Text.Json.JsonDocument.Parse(), System.Text.Json.JsonDocument.Parse(), System.Text.Json.JsonDocument.ParseAsyncCore(), System.Text.Json.JsonDocument.ParseRented(), System.Text.Json.JsonDocument.ParseUnrented(), and System.Text.Json.JsonDocument.TryParseValue().