Terraria: System.Text.Json.JsonDocument.CloneElement
CloneElement()
JsonElement System.Text.Json.JsonDocument.CloneElement (int index) inline package
Definition at line 808 of file JsonDocument.cs.
    {
        int endIndex = GetEndIndex(index, includeEndElement: true);
        MetadataDb parsedData = _parsedData.CopySegment(index, endIndex);
        ReadOnlyMemory<byte> utf8Json = GetRawValue(index, includeQuotes: true).ToArray();
        JsonDocument jsonDocument = new JsonDocument(utf8Json, parsedData, null, null, isDisposable: false);
        return jsonDocument.RootElement;
    }
References System.Text.Json.JsonDocument.JsonDocument(), System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument.MetadataDb.CopySegment(), System.Text.Json.Dictionary, System.endIndex, System.Text.Json.JsonDocument.GetEndIndex(), System.Text.Json.JsonDocument.GetRawValue(), System.index, and System.Text.Json.JsonDocument.RootElement.
Referenced by System.Text.Json.JsonElement.Clone().