Terraria: System.Text.Json.JsonDocument.JsonDocument
JsonDocument()
System.Text.Json.JsonDocument.JsonDocument (ReadOnlyMemory< byte > utf8Json, MetadataDb parsedData, byte[] extraRentedArrayPoolBytes = null, PooledByteBufferWriter extraPooledByteBufferWriter = null, bool isDisposable = true) inline private
Definition at line 303 of file JsonDocument.cs.
    {
        _utf8Json = utf8Json;
        _parsedData = parsedData;
        if (extraRentedArrayPoolBytes != null)
        {
            _hasExtraRentedArrayPoolBytes = true;
            _extraRentedArrayPoolBytes = extraRentedArrayPoolBytes;
        }
        else if (extraPooledByteBufferWriter != null)
        {
            _hasExtraPooledByteBufferWriter = true;
            _extraPooledByteBufferWriter = extraPooledByteBufferWriter;
        }
        IsDisposable = isDisposable;
    }
References System.Text.Json.JsonDocument._extraPooledByteBufferWriter, System.Text.Json.JsonDocument._extraRentedArrayPoolBytes, System.Text.Json.JsonDocument._hasExtraPooledByteBufferWriter, System.Text.Json.JsonDocument._hasExtraRentedArrayPoolBytes, System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument._utf8Json, System.Text.Json.Dictionary, and System.Text.Json.JsonDocument.IsDisposable.
Referenced by System.Text.Json.JsonDocument.CloneElement(), System.Text.Json.JsonDocument.CreateForLiteral(), System.Text.Json.JsonDocument.Parse(), and System.Text.Json.JsonDocument.ParseUnrented().