Terraria: System.Text.Json.JsonDocument.WriteComplexElement
WriteComplexElement()
void System.Text.Json.JsonDocument.WriteComplexElement (int index, Utf8JsonWriter writer) inline private
Definition at line 854 of file JsonDocument.cs.
    {
        int endIndex = GetEndIndex(index, includeEndElement: true);
        for (int i = index + 12; i < endIndex; i += 12)
        {
            DbRow row = _parsedData.Get(i);
            switch (row.TokenType)
            {
            case JsonTokenType.String:
                WriteString(in row, writer);
                break;
            case JsonTokenType.Number:
                writer.WriteNumberValue(_utf8Json.Slice(row.Location, row.SizeOrLength).Span);
                break;
            case JsonTokenType.True:
                writer.WriteBooleanValue(value: true);
                break;
            case JsonTokenType.False:
                writer.WriteBooleanValue(value: false);
                break;
            case JsonTokenType.Null:
                writer.WriteNullValue();
                break;
            case JsonTokenType.StartObject:
                writer.WriteStartObject();
                break;
            case JsonTokenType.EndObject:
                writer.WriteEndObject();
                break;
            case JsonTokenType.StartArray:
                writer.WriteStartArray();
                break;
            case JsonTokenType.EndArray:
                writer.WriteEndArray();
                break;
            case JsonTokenType.PropertyName:
                WritePropertyName(in row, writer);
                break;
            }
        }
    }
References System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument._utf8Json, System.Text.Json.Dictionary, System.endIndex, System.Text.Json.JsonDocument.MetadataDb.Get(), System.Text.Json.JsonDocument.GetEndIndex(), System.index, System.ReadOnlyMemory< T >.Slice(), System.value, System.Text.Json.JsonDocument.WritePropertyName(), System.writer, and System.Text.Json.JsonDocument.WriteString().
Referenced by System.Text.Json.JsonDocument.WriteElementTo().