Terraria: System.Text.Json.JsonDocument.CreateForLiteral
CreateForLiteral()
static JsonDocument System.Text.Json.JsonDocument.CreateForLiteral (JsonTokenType tokenType) inline static private
Definition at line 1389 of file JsonDocument.cs.
    {
        switch (tokenType)
        {
        case JsonTokenType.False:
            if (s_falseLiteral == null)
            {
                s_falseLiteral = Create(JsonConstants.FalseValue.ToArray());
            }
            return s_falseLiteral;
        case JsonTokenType.True:
            if (s_trueLiteral == null)
            {
                s_trueLiteral = Create(JsonConstants.TrueValue.ToArray());
            }
            return s_trueLiteral;
        default:
            if (s_nullLiteral == null)
            {
                s_nullLiteral = Create(JsonConstants.NullValue.ToArray());
            }
            return s_nullLiteral;
        }
        JsonDocument Create(byte[] utf8Json)
        {
            MetadataDb parsedData = MetadataDb.CreateLocked(utf8Json.Length);
            parsedData.Append(tokenType, 0, utf8Json.Length);
            return new JsonDocument(utf8Json, parsedData);
        }
    }
References System.Text.Json.JsonDocument.JsonDocument(), System.IO.Create, System.Text.Json.JsonDocument.MetadataDb.CreateLocked(), System.Text.Json.Dictionary, System.Text.Json.JsonConstants.FalseValue, System.Text.Json.JsonConstants.NullValue, System.Text.Json.JsonDocument.s_falseLiteral, System.Text.Json.JsonDocument.s_nullLiteral, System.Text.Json.JsonDocument.s_trueLiteral, and System.Text.Json.JsonConstants.TrueValue.
Referenced by System.Text.Json.JsonDocument.TryParseValue().