Terraria: System.Text.Json.JsonDocument.CheckNotDisposed
CheckNotDisposed()
void System.Text.Json.JsonDocument.CheckNotDisposed () inline private
Definition at line 1056 of file JsonDocument.cs.
    {
        if (_utf8Json.IsEmpty)
        {
            throw new ObjectDisposedException("JsonDocument");
        }
    }
References System.Text.Json.JsonDocument._utf8Json, and System.ReadOnlyMemory< T >.IsEmpty.
Referenced by System.Text.Json.JsonDocument.GetArrayIndexElement(), System.Text.Json.JsonDocument.GetArrayLength(), System.Text.Json.JsonDocument.GetEndIndex(), System.Text.Json.JsonDocument.GetJsonTokenType(), System.Text.Json.JsonDocument.GetPropertyRawValue(), System.Text.Json.JsonDocument.GetRawValue(), System.Text.Json.JsonDocument.GetString(), System.Text.Json.JsonDocument.TextEquals(), System.Text.Json.JsonDocument.TextEquals(), System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), System.Text.Json.JsonDocument.TryGetValue(), and System.Text.Json.JsonDocument.WriteElementTo().