Terraria: System.Text.Json.JsonDocument.GetString
GetString()
string System.Text.Json.JsonDocument.GetString (int index, JsonTokenType expectedType) inline package
Definition at line 458 of file JsonDocument.cs.
    {
        CheckNotDisposed();
        int num;
        string result;
        (num, result) = _lastIndexAndString;
        if (num == index)
        {
            return result;
        }
        DbRow dbRow = _parsedData.Get(index);
        JsonTokenType tokenType = dbRow.TokenType;
        if (tokenType == JsonTokenType.Null)
        {
            return null;
        }
        CheckExpectedType(expectedType, tokenType);
        ReadOnlySpan<byte> readOnlySpan = _utf8Json.Span.Slice(dbRow.Location, dbRow.SizeOrLength);
        if (dbRow.HasComplexChildren)
        {
            int idx = readOnlySpan.IndexOf<byte>(92);
            result = JsonReaderHelper.GetUnescapedString(readOnlySpan, idx);
        }
        else
        {
            result = JsonReaderHelper.TranscodeHelper(readOnlySpan);
        }
        _lastIndexAndString = (index, result);
        return result;
    }
References System.Text.Json.JsonDocument._lastIndexAndString, System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument._utf8Json, System.Text.Json.JsonDocument.CheckExpectedType(), System.Text.Json.JsonDocument.CheckNotDisposed(), System.Text.Json.Dictionary, System.Text.Json.JsonDocument.MetadataDb.Get(), System.Text.Json.JsonReaderHelper.GetUnescapedString(), System.index, System.ReadOnlyMemory< T >.Span, System.Text.Json.JsonDocument.DbRow.TokenType, and System.Text.Json.JsonReaderHelper.TranscodeHelper().
Referenced by System.Text.Json.JsonDocument.GetNameOfPropertyValue(), and System.Text.Json.JsonElement.GetString().