Terraria: System.Text.Json.JsonDocument.ParseAsyncCore
ParseAsyncCore()
static async Task< JsonDocument > System.Text.Json.JsonDocument.ParseAsyncCore (Stream utf8Json, JsonDocumentOptions options = default(JsonDocumentOptions), CancellationToken cancellationToken = default(CancellationToken)) inline static private
Definition at line 1162 of file JsonDocument.cs.
    {
        ArraySegment<byte> segment = await ReadToEndAsync(utf8Json, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        try
        {
            return Parse(segment.AsMemory(), options.GetReaderOptions(), segment.Array);
        }
        catch
        {
            segment.AsSpan().Clear();
            ArrayPool<byte>.Shared.Return(segment.Array);
            throw;
        }
    }
References System.cancellationToken, System.Text.Json.Dictionary, System.options, System.Text.Json.JsonDocument.Parse(), System.Text.Json.JsonDocument.ReadToEndAsync(), and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.Text.Json.JsonDocument.ParseAsync().