Terraria: System.Text.Json.JsonDocument.TryGetValue
TryGetValue() [3/15]
bool System.Text.Json.JsonDocument.TryGetValue (int index, out DateTime value) inline package
Definition at line 726 of file JsonDocument.cs.
    {
        CheckNotDisposed();
        DbRow dbRow = _parsedData.Get(index);
        CheckExpectedType(JsonTokenType.String, dbRow.TokenType);
        ReadOnlySpan<byte> source = _utf8Json.Span.Slice(dbRow.Location, dbRow.SizeOrLength);
        if (!JsonHelpers.IsValidDateTimeOffsetParseLength(source.Length))
        {
            value = default(DateTime);
            return false;
        }
        if (dbRow.HasComplexChildren)
        {
            return JsonReaderHelper.TryGetEscapedDateTime(source, out value);
        }
        if (JsonHelpers.TryParseAsISO(source, out DateTime value2))
        {
            value = value2;
            return true;
        }
        value = default(DateTime);
        return false;
    }
References System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument._utf8Json, System.Text.Json.JsonDocument.CheckExpectedType(), System.Text.Json.JsonDocument.CheckNotDisposed(), System.Text.Json.Dictionary, System.Text.Json.JsonDocument.MetadataDb.Get(), System.index, System.Text.Json.JsonHelpers.IsValidDateTimeOffsetParseLength(), System.source, System.ReadOnlyMemory< T >.Span, System.Text.Json.JsonReaderHelper.TryGetEscapedDateTime(), System.Text.Json.JsonHelpers.TryParseAsISO(), and System.value.