Terraria: System.Text.Json.JsonDocument.GetRawValue
GetRawValue()
ReadOnlyMemory< byte > System.Text.Json.JsonDocument.GetRawValue (int index, bool includeQuotes) inline package
Definition at line 419 of file JsonDocument.cs.
    {
        CheckNotDisposed();
        DbRow dbRow = _parsedData.Get(index);
        if (dbRow.IsSimpleValue)
        {
            if (includeQuotes && dbRow.TokenType == JsonTokenType.String)
            {
                return _utf8Json.Slice(dbRow.Location - 1, dbRow.SizeOrLength + 2);
            }
            return _utf8Json.Slice(dbRow.Location, dbRow.SizeOrLength);
        }
        int endIndex = GetEndIndex(index, includeEndElement: false);
        int location = dbRow.Location;
        dbRow = _parsedData.Get(endIndex);
        return _utf8Json.Slice(location, dbRow.Location - location + dbRow.SizeOrLength);
    }
References System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument._utf8Json, System.Text.Json.JsonDocument.CheckNotDisposed(), System.Text.Json.Dictionary, System.endIndex, System.Text.Json.JsonDocument.MetadataDb.Get(), System.Text.Json.JsonDocument.GetEndIndex(), System.index, and System.ReadOnlyMemory< T >.Slice().
Referenced by System.Text.Json.JsonDocument.CloneElement(), System.Text.Json.JsonElement.GetRawValue(), System.Text.Json.JsonDocument.GetRawValueAsString(), and System.Text.Json.JsonDocument.GetRootRawValue().