Terraria: System.Text.Json.JsonDocument.UnescapeString
UnescapeString()
ReadOnlySpan< byte > System.Text.Json.JsonDocument.UnescapeString (in DbRow row, out ArraySegment< byte > rented) inline private
Definition at line 896 of file JsonDocument.cs.
    {
        int location = row.Location;
        int sizeOrLength = row.SizeOrLength;
        ReadOnlySpan<byte> span = _utf8Json.Slice(location, sizeOrLength).Span;
        if (!row.HasComplexChildren)
        {
            rented = default(ArraySegment<byte>);
            return span;
        }
        int num = span.IndexOf<byte>(92);
        byte[] array = ArrayPool<byte>.Shared.Rent(sizeOrLength);
        span.Slice(0, num).CopyTo(array);
        JsonReaderHelper.Unescape(span, array, num, out var written);
        rented = new ArraySegment<byte>(array, 0, written);
        return rented.AsSpan();
    }
References System.Text.Json.JsonDocument._utf8Json, System.array, System.Text.Json.Dictionary, System.Buffers.ArrayPool< T >.Shared, System.ReadOnlyMemory< T >.Slice(), and System.Text.Json.JsonReaderHelper.Unescape().
Referenced by System.Text.Json.JsonDocument.WritePropertyName(), and System.Text.Json.JsonDocument.WriteString().