Terraria: System.Text.Json.JsonDocument.ReadToEnd
ReadToEnd()
static ArraySegment< byte > System.Text.Json.JsonDocument.ReadToEnd (Stream stream) inline static private
Definition at line 1467 of file JsonDocument.cs.
    {
        int num = 0;
        byte[] array = null;
        ReadOnlySpan<byte> utf8Bom = JsonConstants.Utf8Bom;
        try
        {
            if (stream.CanSeek)
            {
                long num2 = Math.Max(utf8Bom.Length, stream.Length - stream.Position) + 1;
                array = ArrayPool<byte>.Shared.Rent(checked((int)num2));
            }
            else
            {
                array = ArrayPool<byte>.Shared.Rent(4096);
            }
            int num3;
            do
            {
                num3 = stream.Read(array, num, utf8Bom.Length - num);
                num += num3;
            }
            while (num3 > 0 && num < utf8Bom.Length);
            if (num == utf8Bom.Length && utf8Bom.SequenceEqual(array.AsSpan(0, utf8Bom.Length)))
            {
                num = 0;
            }
            do
            {
                if (array.Length == num)
                {
                    byte[] array2 = array;
                    array = ArrayPool<byte>.Shared.Rent(checked(array2.Length * 2));
                    Buffer.BlockCopy(array2, 0, array, 0, array2.Length);
                    ArrayPool<byte>.Shared.Return(array2, clearArray: true);
                }
                num3 = stream.Read(array, num, array.Length - num);
                num += num3;
            }
            while (num3 > 0);
            return new ArraySegment<byte>(array, 0, num);
        }
        catch
        {
            if (array != null)
            {
                array.AsSpan(0, num).Clear();
                ArrayPool<byte>.Shared.Return(array);
            }
            throw;
        }
    }
References System.array, System.Buffer.BlockCopy(), System.Text.Json.Dictionary, System.Math.Max(), System.Buffers.ArrayPool< T >.Shared, System.stream, and System.Text.Json.JsonConstants.Utf8Bom.
Referenced by System.Text.Json.JsonDocument.Parse(), and System.Text.Json.JsonDocument.ParseValue().