Terraria: System.Text.Json.JsonDocument.TryGetNamedPropertyValue
TryGetNamedPropertyValue() [3/3]
bool System.Text.Json.JsonDocument.TryGetNamedPropertyValue (int startIndex, int endIndex, ReadOnlySpan< byte > propertyName, out JsonElement value) inline private
Definition at line 1634 of file JsonDocument.cs.
    {
        ReadOnlySpan<byte> span = _utf8Json.Span;
        Span<byte> span2 = stackalloc byte[256];
        int num;
        for (num = endIndex - 12; num > startIndex; num -= 12)
        {
            DbRow dbRow = _parsedData.Get(num);
            num = ((!dbRow.IsSimpleValue) ? (num - 12 * (dbRow.NumberOfRows + 1)) : (num - 12));
            dbRow = _parsedData.Get(num);
            ReadOnlySpan<byte> span3 = span.Slice(dbRow.Location, dbRow.SizeOrLength);
            if (dbRow.HasComplexChildren)
            {
                if (span3.Length > propertyName.Length)
                {
                    int num2 = span3.IndexOf<byte>(92);
                    if (propertyName.Length > num2 && span3.Slice(0, num2).SequenceEqual(propertyName.Slice(0, num2)))
                    {
                        int num3 = span3.Length - num2;
                        int written = 0;
                        byte[] array = null;
                        try
{
                            Span<byte> destination = ((num3 <= span2.Length) ? span2 : ((Span<byte>)(array = ArrayPool<byte>.Shared.Rent(num3))));
                            JsonReaderHelper.Unescape(span3.Slice(num2), destination, 0, out written);
                            if (destination.Slice(0, written).SequenceEqual(propertyName.Slice(num2)))
{
                                value = new JsonElement(this, num + 12);
                                return true;
                            }
                        }
                        finally
{
                            if (array != null)
{
                                array.AsSpan(0, written).Clear();
                                ArrayPool<byte>.Shared.Return(array);
                            }
                        }
                    }
                }
            }
            else if (span3.SequenceEqual(propertyName))
            {
                value = new JsonElement(this, num + 12);
                return true;
            }
        }
        value = default(JsonElement);
        return false;
    }
References System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument._utf8Json, System.array, System.destination, System.Text.Json.Dictionary, System.endIndex, System.Text.Json.JsonDocument.MetadataDb.Get(), System.Buffers.ArrayPool< T >.Rent(), System.Buffers.ArrayPool< T >.Shared, System.ReadOnlySpan< T >.Slice(), System.ReadOnlyMemory< T >.Span, System.startIndex, System.Text.Json.JsonReaderHelper.Unescape(), and System.value.