Terraria: System.Text.Json.JsonDocument.TryGetValue
TryGetValue() [14/15]
bool System.Text.Json.JsonDocument.TryGetValue (int index, out ulong value) inline package
Definition at line 666 of file JsonDocument.cs.
    {
        CheckNotDisposed();
        DbRow dbRow = _parsedData.Get(index);
        CheckExpectedType(JsonTokenType.Number, dbRow.TokenType);
        ReadOnlySpan<byte> source = _utf8Json.Span.Slice(dbRow.Location, dbRow.SizeOrLength);
        if (Utf8Parser.TryParse(source, out ulong value2, out int bytesConsumed, '\0') && bytesConsumed == source.Length)
        {
            value = value2;
            return true;
        }
        value = 0uL;
        return false;
    }
References System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument._utf8Json, System.Text.Json.JsonDocument.CheckExpectedType(), System.Text.Json.JsonDocument.CheckNotDisposed(), System.Text.Json.Dictionary, System.Text.Json.JsonDocument.MetadataDb.Get(), System.index, System.source, System.ReadOnlyMemory< T >.Span, System.Buffers.Text.Utf8Parser.TryParse(), and System.value.