Terraria: System.Text.Json.JsonDocument.TryGetNamedPropertyValue
TryGetNamedPropertyValue() [2/3]
bool System.Text.Json.JsonDocument.TryGetNamedPropertyValue (int index, ReadOnlySpan< char > propertyName, out JsonElement value) inline package
Definition at line 1573 of file JsonDocument.cs.
    {
        CheckNotDisposed();
        DbRow dbRow = _parsedData.Get(index);
        CheckExpectedType(JsonTokenType.StartObject, dbRow.TokenType);
        if (dbRow.NumberOfRows == 1)
        {
            value = default(JsonElement);
            return false;
        }
        int maxByteCount = JsonReaderHelper.s_utf8Encoding.GetMaxByteCount(propertyName.Length);
        int startIndex = index + 12;
        int num = checked(dbRow.NumberOfRows * 12 + index);
        if (maxByteCount < 256)
        {
            Span<byte> span = stackalloc byte[256];
            span = span[..JsonReaderHelper.GetUtf8FromText(propertyName, span)];
            return TryGetNamedPropertyValue(startIndex, num, span, out value);
        }
        int length = propertyName.Length;
        int num2;
        for (num2 = num - 12; num2 > index; num2 -= 12)
        {
            int num3 = num2;
            dbRow = _parsedData.Get(num2);
            num2 = ((!dbRow.IsSimpleValue) ? (num2 - 12 * (dbRow.NumberOfRows + 1)) : (num2 - 12));
            if (_parsedData.Get(num2).SizeOrLength >= length)
            {
                byte[] array = ArrayPool<byte>.Shared.Rent(maxByteCount);
                Span<byte> span2 = default(Span<byte>);
                try
                {
                    int utf8FromText = JsonReaderHelper.GetUtf8FromText(propertyName, array);
                    span2 = array.AsSpan(0, utf8FromText);
                    return TryGetNamedPropertyValue(startIndex, num3 + 12, span2, out value);
                }
                finally
                {
                    span2.Clear();
                    ArrayPool<byte>.Shared.Return(array);
                }
            }
        }
        value = default(JsonElement);
        return false;
    }
References System.Text.Json.JsonDocument._parsedData, System.array, System.Text.Json.JsonDocument.CheckExpectedType(), System.Text.Json.JsonDocument.CheckNotDisposed(), System.Text.Json.Dictionary, System.Text.Json.JsonDocument.MetadataDb.Get(), System.Text.Json.JsonReaderHelper.GetUtf8FromText(), System.index, System.length, System.Text.Json.JsonReaderHelper.s_utf8Encoding, System.Buffers.ArrayPool< T >.Shared, System.Text.Json.JsonDocument.DbRow.SizeOrLength, System.startIndex, System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), and System.value.
Referenced by System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), System.Text.Json.JsonDocument.TryGetNamedPropertyValue(), System.Text.Json.JsonElement.TryGetProperty(), and System.Text.Json.JsonElement.TryGetProperty().