Terraria: System.Text.Json.JsonDocument.WriteElementTo
WriteElementTo()
void System.Text.Json.JsonDocument.WriteElementTo (int index, Utf8JsonWriter writer) inline package
Definition at line 817 of file JsonDocument.cs.
    {
        CheckNotDisposed();
        DbRow row = _parsedData.Get(index);
        switch (row.TokenType)
        {
        case JsonTokenType.StartObject:
            writer.WriteStartObject();
            WriteComplexElement(index, writer);
            break;
        case JsonTokenType.StartArray:
            writer.WriteStartArray();
            WriteComplexElement(index, writer);
            break;
        case JsonTokenType.String:
            WriteString(in row, writer);
            break;
        case JsonTokenType.Number:
            writer.WriteNumberValue(_utf8Json.Slice(row.Location, row.SizeOrLength).Span);
            break;
        case JsonTokenType.True:
            writer.WriteBooleanValue(value: true);
            break;
        case JsonTokenType.False:
            writer.WriteBooleanValue(value: false);
            break;
        case JsonTokenType.Null:
            writer.WriteNullValue();
            break;
        case JsonTokenType.EndObject:
        case JsonTokenType.EndArray:
        case JsonTokenType.PropertyName:
        case JsonTokenType.Comment:
            break;
        }
    }
References System.Text.Json.JsonDocument._parsedData, System.Text.Json.JsonDocument._utf8Json, System.Text.Json.JsonDocument.CheckNotDisposed(), System.Text.Json.Dictionary, System.Text.Json.JsonDocument.MetadataDb.Get(), System.index, System.ReadOnlyMemory< T >.Slice(), System.value, System.Text.Json.JsonDocument.WriteComplexElement(), System.writer, and System.Text.Json.JsonDocument.WriteString().
Referenced by System.Text.Json.JsonElement.WriteTo().