Terraria: System.Text.Json.JsonDocument.WritePropertyName
WritePropertyName()
void System.Text.Json.JsonDocument.WritePropertyName (in DbRow row, Utf8JsonWriter writer) inline private
Definition at line 923 of file JsonDocument.cs.
    {
        ArraySegment<byte> rented = default(ArraySegment<byte>);
        try
        {
            writer.WritePropertyName(UnescapeString(in row, out rented));
        }
        finally
        {
            ClearAndReturn(rented);
        }
    }
References System.Text.Json.JsonDocument.ClearAndReturn(), System.Text.Json.Dictionary, System.Text.Json.JsonDocument.UnescapeString(), and System.writer.
Referenced by System.Text.Json.JsonDocument.WriteComplexElement().