Terraria: System.Text.Json.JsonDocument.TextEquals
TextEquals() [2/2]
bool System.Text.Json.JsonDocument.TextEquals (int index, ReadOnlySpan< char > otherText, bool isPropertyName) inline package
Definition at line 489 of file JsonDocument.cs.
    {
        CheckNotDisposed();
        int num = (isPropertyName ? (index - 12) : index);
        var (num2, text) = _lastIndexAndString;
        if (num2 == num)
        {
            return otherText.SequenceEqual(text.AsSpan());
        }
        byte[] array = null;
        int num3 = checked(otherText.Length * 3);
        Span<byte> span = ((num3 > 256) ? ((Span<byte>)(array = ArrayPool<byte>.Shared.Rent(num3))) : stackalloc byte[256]);
        Span<byte> utf8Destination = span;
        ReadOnlySpan<byte> utf16Source = MemoryMarshal.AsBytes(otherText);
        int bytesConsumed;
        int bytesWritten;
        OperationStatus operationStatus = JsonWriterHelper.ToUtf8(utf16Source, utf8Destination, out bytesConsumed, out bytesWritten);
        bool result = operationStatus <= OperationStatus.DestinationTooSmall && TextEquals(index, utf8Destination.Slice(0, bytesWritten), isPropertyName, shouldUnescape: true);
        if (array != null)
        {
            utf8Destination.Slice(0, bytesWritten).Clear();
            ArrayPool<byte>.Shared.Return(array);
        }
        return result;
    }
References System.Text.Json.JsonDocument._lastIndexAndString, System.array, System.Text.Json.JsonDocument.CheckNotDisposed(), System.Text.Json.Dictionary, System.index, System.Buffers.ArrayPool< T >.Shared, System.text, System.Text.Json.JsonDocument.TextEquals(), and System.Text.Json.JsonWriterHelper.ToUtf8().
Referenced by System.Text.Json.JsonDocument.TextEquals(), System.Text.Json.JsonElement.TextEqualsHelper(), and System.Text.Json.JsonElement.TextEqualsHelper().