Terraria: System.Text.Json.JsonDocument.ParseUnrented
ParseUnrented()
static JsonDocument System.Text.Json.JsonDocument.ParseUnrented (ReadOnlyMemory< byte > utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType = JsonTokenType::None) inline static private
Definition at line 1441 of file JsonDocument.cs.
    {
        ReadOnlySpan<byte> span = utf8Json.Span;
        MetadataDb database;
        if (tokenType == JsonTokenType.String || tokenType == JsonTokenType.Number)
        {
            database = MetadataDb.CreateLocked(utf8Json.Length);
            StackRowStack stack = default(StackRowStack);
            Parse(span, readerOptions, ref database, ref stack);
        }
        else
        {
            database = MetadataDb.CreateRented(utf8Json.Length, convertToAlloc: true);
            StackRowStack stack2 = new StackRowStack(512);
            try
            {
                Parse(span, readerOptions, ref database, ref stack2);
            }
            finally
            {
                stack2.Dispose();
            }
        }
        return new JsonDocument(utf8Json, database);
    }
References System.Text.Json.JsonDocument.JsonDocument(), System.Text.Json.JsonDocument.MetadataDb.CreateLocked(), System.Text.Json.JsonDocument.MetadataDb.CreateRented(), System.Text.Json.Dictionary, and System.Text.Json.JsonDocument.Parse().
Referenced by System.Text.Json.JsonDocument.ParseValue(), System.Text.Json.JsonDocument.ParseValue(), System.Text.Json.JsonDocument.ParseValue(), and System.Text.Json.JsonDocument.TryParseValue().