Terraria: System.Text.Json.JsonDocument.ReadToEndAsync
ReadToEndAsync()
static async ValueTask< ArraySegment< byte > > System.Text.Json.JsonDocument.ReadToEndAsync (Stream stream, CancellationToken cancellationToken) inline static private
Definition at line 1520 of file JsonDocument.cs.
    {
        int written = 0;
        byte[] rented = null;
        try
        {
            int utf8BomLength = JsonConstants.Utf8Bom.Length;
            if (stream.CanSeek)
            {
                long num = Math.Max(utf8BomLength, stream.Length - stream.Position) + 1;
                rented = ArrayPool<byte>.Shared.Rent(checked((int)num));
            }
            else
            {
                rented = ArrayPool<byte>.Shared.Rent(4096);
            }
            int num2;
            do
            {
                num2 = await stream.ReadAsync(rented.AsMemory(written, utf8BomLength - written), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                written += num2;
            }
            while (num2 > 0 && written < utf8BomLength);
            if (written == utf8BomLength && JsonConstants.Utf8Bom.SequenceEqual(rented.AsSpan(0, utf8BomLength)))
            {
                written = 0;
            }
            do
            {
                if (rented.Length == written)
                {
                    byte[] array = rented;
                    rented = ArrayPool<byte>.Shared.Rent(array.Length * 2);
                    Buffer.BlockCopy(array, 0, rented, 0, array.Length);
                    ArrayPool<byte>.Shared.Return(array, clearArray: true);
                }
                num2 = await stream.ReadAsync(rented.AsMemory(written), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                written += num2;
            }
            while (num2 > 0);
            return new ArraySegment<byte>(rented, 0, written);
        }
        catch
        {
            if (rented != null)
            {
                rented.AsSpan(0, written).Clear();
                ArrayPool<byte>.Shared.Return(rented);
            }
            throw;
        }
    }
References System.array, System.Buffer.BlockCopy(), System.cancellationToken, System.Text.Json.Dictionary, System.Math.Max(), System.Buffers.ArrayPool< T >.Shared, System.stream, and System.Text.Json.JsonConstants.Utf8Bom.
Referenced by System.Text.Json.JsonDocument.ParseAsyncCore().