Terraria: System.Text.Json.JsonDocument.ParseValue
ParseValue() [1/5]
static JsonDocument System.Text.Json.JsonDocument.ParseValue (ReadOnlyMemory< char > json, JsonDocumentOptions options) inline static package
Definition at line 1195 of file JsonDocument.cs.
    {
        ReadOnlySpan<char> span = json.Span;
        int utf8ByteCount = JsonReaderHelper.GetUtf8ByteCount(span);
        byte[] array = ArrayPool<byte>.Shared.Rent(utf8ByteCount);
        byte[] array2;
        try
        {
            int utf8FromText = JsonReaderHelper.GetUtf8FromText(span, array);
            array2 = new byte[utf8FromText];
            Buffer.BlockCopy(array, 0, array2, 0, utf8FromText);
        }
        finally
        {
            array.AsSpan(0, utf8ByteCount).Clear();
            ArrayPool<byte>.Shared.Return(array);
        }
        return ParseUnrented(array2.AsMemory(), options.GetReaderOptions());
    }
References System.array, System.Buffer.BlockCopy(), System.Text.Json.Dictionary, System.Text.Json.JsonReaderHelper.GetUtf8ByteCount(), System.Text.Json.JsonReaderHelper.GetUtf8FromText(), System.options, System.Text.Json.JsonDocument.ParseUnrented(), and System.Buffers.ArrayPool< T >.Shared.