Terraria: System.Security.Cryptography.Asn1.PBEParameter.DecodeCore
DecodeCore() [1/2]
static void System.Security.Cryptography.Asn1.PBEParameter.DecodeCore (ref AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out PBEParameter decoded) inline static private
Definition at line 31 of file PBEParameter.cs.
    {
        decoded = default(PBEParameter);
        AsnValueReader asnValueReader = reader.ReadSequence(expectedTag);
        ReadOnlySpan<byte> span = rebind.Span;
        if (asnValueReader.TryReadPrimitiveOctetString(out var value))
        {
            decoded.Salt = (span.Overlaps(value, out var elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        }
        else
        {
            decoded.Salt = asnValueReader.ReadOctetString();
        }
        if (!asnValueReader.TryReadInt32(out decoded.IterationCount))
        {
            asnValueReader.ThrowIfNotEmpty();
        }
        asnValueReader.ThrowIfNotEmpty();
    }
References System.Formats.Asn1.AsnValueReader.ReadOctetString(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty(), System.Formats.Asn1.AsnValueReader.TryReadInt32(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveOctetString(), and System.value.
Referenced by System.Security.Cryptography.Asn1.PBEParameter.Decode().