Terraria: Terraria.GameContent.UI.States.UIVirtualKeyboard.TypeText
TypeText()
void Terraria.GameContent.UI.States.UIVirtualKeyboard.TypeText (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 521 of file UIVirtualKeyboard.cs.
    {
        string text = ((UITextPanel<object>)listeningElement).Text;
        if (CustomTextValidationForUpdate != null && !CustomTextValidationForUpdate(Text + text))
        {
            SoundEngine.PlaySound(11);
            return;
        }
        SoundEngine.PlaySound(12);
        bool num = Text.Length == 0;
        _textBox.Write(text);
        ValidateText();
        if (num && Text.Length > 0 && _keyState == KeyState.Shift)
        {
            SetKeyState(KeyState.Default);
        }
    }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._keyState, Terraria.GameContent.UI.States.UIVirtualKeyboard._textBox, Terraria.GameContent.UI.States.UIVirtualKeyboard.CustomTextValidationForUpdate, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UIVirtualKeyboard.SetKeyState(), Terraria.GameContent.UI.States.UIVirtualKeyboard.ValidateText(), and Terraria.GameContent.UI.Elements.UITextBox.Write().
Referenced by Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard().