Terraria: UILinkPointNavigator.Update
Update()
static void UILinkPointNavigator.Update () inline static
     {
         bool inUse = InUse;
         InUse = false;
         bool flag = true;
         if (flag)
         {
             InputMode currentInputMode = PlayerInput.CurrentInputMode;
             if ((uint)currentInputMode <= 2u && !Main.gameMenu)
             {
                 flag = false;
             }
         }
         if (flag && PlayerInput.NavigatorRebindingLock > 0)
         {
             flag = false;
         }
         if (flag && !Main.gameMenu && !PlayerInput.UsingGamepadUI)
         {
             flag = false;
         }
         if (flag && !Main.gameMenu && PlayerInput.InBuildingMode)
         {
             flag = false;
         }
         if (flag && !Main.gameMenu && !Available)
         {
             flag = false;
         }
         bool flag2 = false;
         if (!Pages.TryGetValue(CurrentPage, out var value))
         {
             flag2 = true;
         }
         else if (!value.IsValid())
         {
             flag2 = true;
         }
         if (flag2)
         {
             GoToDefaultPage();
             ProcessChanges();
             flag = false;
         }
         if (inUse != flag)
         {
             if (!flag)
             {
                 value.Leave();
                 GoToDefaultPage();
                 ProcessChanges();
             }
             else
             {
                 GoToDefaultPage();
                 ProcessChanges();
                 ConsumeSuggestion();
                 value.Enter();
             }
             if (flag)
             {
                 if (!PlayerInput.SteamDeckIsUsed || PlayerInput.PreventCursorModeSwappingToGamepad)
                 {
                     Main.player[Main.myPlayer].releaseInventory = false;
                 }
                 Main.player[Main.myPlayer].releaseUseTile = false;
                 PlayerInput.LockGamepadTileUseButton = true;
             }
             if (!Main.gameMenu)
             {
                 if (flag)
                 {
                     PlayerInput.NavigatorCachePosition();
                 }
                 else
                 {
                     PlayerInput.NavigatorUnCachePosition();
                 }
             }
         }
         ClearSuggestion();
         if (!flag)
         {
             return;
         }
         InUse = true;
         OverridePoint = -1;
         if (PageLeftCD > 0)
         {
             PageLeftCD--;
         }
         if (PageRightCD > 0)
         {
             PageRightCD--;
         }
         Vector2 navigatorDirections = PlayerInput.Triggers.Current.GetNavigatorDirections();
         bool num = PlayerInput.Triggers.Current.HotbarMinus && !PlayerInput.Triggers.Current.HotbarPlus;
         bool flag3 = PlayerInput.Triggers.Current.HotbarPlus && !PlayerInput.Triggers.Current.HotbarMinus;
         if (!num)
         {
             PageLeftCD = 0;
         }
         if (!flag3)
         {
             PageRightCD = 0;
         }
         bool num2 = num && PageLeftCD == 0;
         flag3 = flag3 && PageRightCD == 0;
         if (LastInput.X != navigatorDirections.X)
         {
             XCooldown = 0;
         }
         if (LastInput.Y != navigatorDirections.Y)
         {
             YCooldown = 0;
         }
         if (XCooldown > 0)
         {
             XCooldown--;
         }
         if (YCooldown > 0)
         {
             YCooldown--;
         }
         LastInput = navigatorDirections;
         if (num2)
         {
             PageLeftCD = 16;
         }
         if (flag3)
         {
             PageRightCD = 16;
         }
         Pages[CurrentPage].Update();
         int num3 = 10;
         if (!Main.gameMenu && Main.playerInventory && !Main.ingameOptionsWindow && !Main.inFancyUI && (CurrentPage == 0 || CurrentPage == 4 || CurrentPage == 2 || CurrentPage == 1 || CurrentPage == 20 || CurrentPage == 21))
         {
             num3 = PlayerInput.CurrentProfile.InventoryMoveCD;
         }
         if (navigatorDirections.X == -1f && XCooldown == 0)
         {
             XCooldown = num3;
             Pages[CurrentPage].TravelLeft();
         }
         if (navigatorDirections.X == 1f && XCooldown == 0)
         {
             XCooldown = num3;
             Pages[CurrentPage].TravelRight();
         }
         if (navigatorDirections.Y == -1f && YCooldown == 0)
         {
             YCooldown = num3;
             Pages[CurrentPage].TravelUp();
         }
         if (navigatorDirections.Y == 1f && YCooldown == 0)
         {
             YCooldown = num3;
             Pages[CurrentPage].TravelDown();
         }
         XCooldown = (YCooldown = Math.Max(XCooldown, YCooldown));
         if (num2)
         {
             Pages[CurrentPage].SwapPageLeft();
         }
         if (flag3)
         {
             Pages[CurrentPage].SwapPageRight();
         }
         if (PlayerInput.Triggers.Current.UsedMovementKey)
         {
             Vector2 position = Points[CurrentPoint].Position;
             Vector2 value2 = new Vector2(PlayerInput.MouseX, PlayerInput.MouseY);
             float amount = 0.3f;
             if (PlayerInput.InvisibleGamepadInMenus)
             {
                 amount = 1f;
             }
             Vector2 vector = Vector2.Lerp(value2, position, amount);
             if (Main.gameMenu)
             {
                 if (Math.Abs(vector.X - position.X) <= 5f)
                 {
                     vector.X = position.X;
                 }
                 if (Math.Abs(vector.Y - position.Y) <= 5f)
                 {
                     vector.Y = position.Y;
                 }
             }
             PlayerInput.MouseX = (int)vector.X;
             PlayerInput.MouseY = (int)vector.Y;
         }
         ResetFlagsEnd();
     }
References Available, ClearSuggestion(), ConsumeSuggestion(), TriggersPack.Current, PlayerInput.CurrentInputMode, CurrentPage, CurrentPoint, PlayerInput.CurrentProfile, Main.gameMenu, TriggersSet.GetNavigatorDirections(), GoToDefaultPage(), TriggersSet.HotbarMinus, TriggersSet.HotbarPlus, PlayerInput.InBuildingMode, Main.inFancyUI, Main.ingameOptionsWindow, InUse, PlayerInputProfile.InventoryMoveCD, PlayerInput.InvisibleGamepadInMenus, LastInput, PlayerInput.LockGamepadTileUseButton, PlayerInput.MouseX, PlayerInput.MouseY, Main.myPlayer, PlayerInput.NavigatorCachePosition(), PlayerInput.NavigatorRebindingLock, PlayerInput.NavigatorUnCachePosition(), OverridePoint, PageLeftCD, PageRightCD, Pages, Main.player, Main.playerInventory, Points, PlayerInput.PreventCursorModeSwappingToGamepad, ProcessChanges(), Player.releaseInventory, Player.releaseUseTile, ResetFlagsEnd(), PlayerInput.SteamDeckIsUsed, PlayerInput.Triggers, TriggersSet.UsedMovementKey, PlayerInput.UsingGamepadUI, XCooldown, and YCooldown.
Referenced by Main.DoUpdate_HandleInput().