Terraria: System.Linq.Expressions.BlockExpression.GetExpression
GetExpression()
virtual Expression System.Linq.Expressions.BlockExpression.GetExpression (int index) inline package virtual inherited
Reimplemented in System.Linq.Expressions.Block2, System.Linq.Expressions.Block3, System.Linq.Expressions.Block4, System.Linq.Expressions.Block5, System.Linq.Expressions.BlockN, System.Linq.Expressions.Scope1, and System.Linq.Expressions.ScopeN.
Definition at line 90 of file BlockExpression.cs.
    {
        throw ContractUtils.Unreachable;
    }
References System.Dynamic.Utils.ContractUtils.Unreachable.
Referenced by System.Linq.Expressions.BlockExpressionList.CopyTo(), System.Linq.Expressions.BlockExpressionList.GetEnumerator(), System.Linq.Expressions.BlockExpressionList.IndexOf(), and System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions().