Terraria: System.Transactions.TransactionStateDelegatedBase.EnterState
EnterState()
override void System.Transactions.TransactionStateDelegatedBase.EnterState (InternalTransaction tx) inline package inherited
Definition at line 8 of file TransactionStateDelegatedBase.cs.
    {
        if (tx._outcomeSource._isoLevel == IsolationLevel.Snapshot)
        {
            throw TransactionException.CreateInvalidOperationException(TraceSourceType.TraceSourceLtm, System.SR.CannotPromoteSnapshot, null, tx?.DistributedTxId ?? Guid.Empty);
        }
        CommonEnterState(tx);
        DistributedTransaction distributedTransaction = null;
        try
        {
            if (tx._durableEnlistment != null)
            {
                TransactionsEtwProvider log = TransactionsEtwProvider.Log;
                if (log.IsEnabled())
                {
                    log.EnlistmentStatus(tx._durableEnlistment, NotificationCall.Promote);
                }
            }
            distributedTransaction = TransactionState.TransactionStatePSPEOperation.PSPEPromote(tx);
        }
        catch (TransactionPromotionException innerException)
        {
            TransactionPromotionException exception = (TransactionPromotionException)(tx._innerException = innerException);
            TransactionsEtwProvider log2 = TransactionsEtwProvider.Log;
            if (log2.IsEnabled())
            {
                log2.ExceptionConsumed(exception);
            }
        }
        finally
        {
            if (distributedTransaction == null)
            {
                tx.State.ChangeStateAbortedDuringPromotion(tx);
            }
        }
        if (distributedTransaction != null && tx.PromotedTransaction != distributedTransaction)
        {
            tx.PromotedTransaction = distributedTransaction;
            Hashtable promotedTransactionTable = TransactionManager.PromotedTransactionTable;
            lock (promotedTransactionTable)
            {
                tx._finalizedObject = new FinalizedObject(tx, tx.PromotedTransaction.Identifier);
                WeakReference value = new WeakReference(tx._outcomeSource, trackResurrection: false);
                promotedTransactionTable[tx.PromotedTransaction.Identifier] = value;
            }
            TransactionManager.FireDistributedTransactionStarted(tx._outcomeSource);
            TransactionsEtwProvider log3 = TransactionsEtwProvider.Log;
            if (log3.IsEnabled())
            {
                log3.TransactionPromoted(tx.TransactionTraceId, distributedTransaction.TransactionTraceId);
            }
            PromoteEnlistmentsAndOutcome(tx);
        }
    }
References System.Transactions.InternalTransaction._durableEnlistment, System.Transactions.InternalTransaction._innerException, System.Transactions.Transaction._isoLevel, System.Transactions.InternalTransaction._outcomeSource, System.SR.CannotPromoteSnapshot, System.Transactions.TransactionState.ChangeStateAbortedDuringPromotion(), System.Transactions.TransactionState.CommonEnterState(), System.Transactions.TransactionException.CreateInvalidOperationException(), System.Transactions.InternalTransaction.DistributedTxId, System.Guid.Empty, System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.exception, System.Transactions.TransactionsEtwProvider.ExceptionConsumed(), System.Transactions.TransactionManager.FireDistributedTransactionStarted(), System.Transactions.Distributed.DistributedTransaction.Identifier, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.Log, System.Transactions.InternalTransaction.PromotedTransaction, System.Transactions.TransactionManager.PromotedTransactionTable, System.Transactions.TransactionStatePromoted.PromoteEnlistmentsAndOutcome(), System.Transactions.InternalTransaction.State, System.Transactions.TransactionsEtwProvider.TransactionPromoted(), System.Transactions.TransactionState.TransactionStatePSPEOperation, System.Transactions.Distributed.DistributedTransaction.TransactionTraceId, System.Transactions.InternalTransaction.TransactionTraceId, and System.value.