Terraria: System.Data.UnaryNode.EvalUnaryOp
EvalUnaryOp()
object System.Data.UnaryNode.EvalUnaryOp (int op, object vl) inline private
Definition at line 45 of file UnaryNode.cs.
    {
        object value = DBNull.Value;
        if (DataExpression.IsUnknown(vl))
        {
            return DBNull.Value;
        }
        switch (op)
        {
        case 0:
            return vl;
        case 2:
        {
            StorageType storageType = DataStorage.GetStorageType(vl.GetType());
            if (ExpressionNode.IsNumericSql(storageType))
            {
                return vl;
            }
            throw ExprException.TypeMismatch(ToString());
        }
        case 1:
        {
            StorageType storageType = DataStorage.GetStorageType(vl.GetType());
            if (ExpressionNode.IsNumericSql(storageType))
            {
                return storageType switch
                {
                    StorageType.Byte => -(byte)vl,
                    StorageType.Int16 => -(short)vl,
                    StorageType.Int32 => -(int)vl,
                    StorageType.Int64 => -(long)vl,
                    StorageType.Single => 0f - (float)vl,
                    StorageType.Double => 0.0 - (double)vl,
                    StorageType.Decimal => -(decimal)vl,
                    StorageType.SqlDecimal => -(SqlDecimal)vl,
                    StorageType.SqlDouble => -(SqlDouble)vl,
                    StorageType.SqlSingle => -(SqlSingle)vl,
                    StorageType.SqlMoney => -(SqlMoney)vl,
                    StorageType.SqlInt64 => -(SqlInt64)vl,
                    StorageType.SqlInt32 => -(SqlInt32)vl,
                    StorageType.SqlInt16 => -(SqlInt16)vl,
                    _ => DBNull.Value,
                };
            }
            throw ExprException.TypeMismatch(ToString());
        }
        case 3:
            if (vl is SqlBoolean sqlBoolean)
            {
                if (sqlBoolean.IsFalse)
                {
                    return SqlBoolean.True;
                }
                if (((SqlBoolean)vl).IsTrue)
                {
                    return SqlBoolean.False;
                }
                throw ExprException.UnsupportedOperator(op);
            }
            if (DataExpression.ToBoolean(vl))
            {
                return false;
            }
            return true;
        default:
            throw ExprException.UnsupportedOperator(op);
        }
    }
References System.Data.SqlTypes.SqlBoolean.False, System.Data.Common.DataStorage.GetStorageType(), System.Data.ExpressionNode.IsNumericSql(), System.Data.DataExpression.IsUnknown(), System.Data.Common.SqlDouble, System.Data.Common.SqlInt32, System.Data.Common.SqlMoney, System.Data.DataExpression.ToBoolean(), System.ToString, System.Data.SqlTypes.SqlBoolean.True, System.Data.ExprException.TypeMismatch(), System.Data.ExprException.UnsupportedOperator(), System.DBNull.Value, and System.value.
Referenced by System.Data.UnaryNode.Eval().