Terraria: System.Xml.Xsl.Xslt.Scripts.ResolveFunction
ResolveFunction()
XmlExtensionFunction System.Xml.Xsl.Xslt.Scripts.ResolveFunction (string name, string ns, int numArgs, IErrorHelper errorHelper) inline
Definition at line 58 of file Scripts.cs.
    {
        if (_nsToType.TryGetValue(ns, out var value))
        {
            try
            {
                return _extFuncs.Bind(name, ns, numArgs, value, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public);
            }
            catch (XslTransformException ex)
            {
                errorHelper.ReportError(ex.Message);
            }
        }
        return null;
    }
References System.Xml.Xsl.Xslt.Scripts._extFuncs, System.Xml.Xsl.Xslt.Scripts._nsToType, System.Xml.Xsl.Runtime.XmlExtensionFunctionTable.Bind(), System.Xml.Xsl.Xslt.Scripts.TrimSafeDictionary.TryGetValue(), and System.value.
Referenced by System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.Function(), and System.Xml.Xsl.Xslt.QilGenerator.ResolveFunction().