Terraria: MS.Internal.Xml.XPath.BaseAxisQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.BaseAxisQuery.Evaluate (XPathNodeIterator nodeIterator) inline inherited
Definition at line 118 of file BaseAxisQuery.cs.
    {
        ResetCount();
        Reset();
        qyInput.Evaluate(nodeIterator);
        return this;
    }
References MS.Internal.Xml.XPath.Query.Evaluate(), MS.Internal.Xml.XPath.BaseAxisQuery.qyInput, MS.Internal.Xml.XPath.BaseAxisQuery.Reset(), and MS.Internal.Xml.XPath.ResetableIterator.ResetCount().
Referenced by MS.Internal.Xml.XPath.FilterQuery.MatchNode().