Terraria: System.Threading.Tasks.Dataflow.Internal.QueuedMap.Push
Push()
void System.Threading.Tasks.Dataflow.Internal.QueuedMap< TKey, TValue >.Push (TKey key, TValue value) inline package
Definition at line 102 of file QueuedMap.cs.
    {
        if (!_queue.IsEmpty && _mapKeyToIndex.TryGetValue(key, out var value2))
        {
            _queue.Replace(value2, new KeyValuePair<TKey, TValue>(key, value));
            return;
        }
        value2 = _queue.Enqueue(new KeyValuePair<TKey, TValue>(key, value));
        _mapKeyToIndex.Add(key, value2);
    }
References System.Threading.Tasks.Dataflow.Internal.QueuedMap< TKey, TValue >._mapKeyToIndex, System.Threading.Tasks.Dataflow.Internal.QueuedMap< TKey, TValue >._queue, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.Tasks.Dataflow.Internal.QueuedMap< TKey, TValue >.ArrayBasedLinkedQueue< T >.Enqueue(), System.Threading.Tasks.Dataflow.Internal.QueuedMap< TKey, TValue >.ArrayBasedLinkedQueue< T >.IsEmpty, System.key, System.Threading.Tasks.Dataflow.Internal.QueuedMap< TKey, TValue >.ArrayBasedLinkedQueue< T >.Replace(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.