Terraria: Interop.IpHlpApi.IpSocketAddress.MarshalIPAddress
MarshalIPAddress()
IPAddress Interop.IpHlpApi.IpSocketAddress.MarshalIPAddress () inline package
Definition at line 93 of file Interop.cs.
            {
                AddressFamily family = ((addressLength > System.Net.Internals.SocketAddress.IPv4AddressSize) ? AddressFamily.InterNetworkV6 : AddressFamily.InterNetwork);
                System.Net.Internals.SocketAddress socketAddress = new System.Net.Internals.SocketAddress(family, addressLength);
                Marshal.Copy(address, socketAddress.Buffer, 0, addressLength);
                return socketAddress.GetIPAddress();
            }
References Interop.IpHlpApi.IpSocketAddress.address, Interop.IpHlpApi.IpSocketAddress.addressLength, System.Net.Internals.SocketAddress.Buffer, System.Runtime.InteropServices.Marshal.Copy(), System.Net.Internals.SocketAddress.GetIPAddress(), and System.Net.Internals.SocketAddress.IPv4AddressSize.
Referenced by Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressCollection(), and Interop.IpHlpApi.IpAdapterAddress.MarshalIpAddressInformationCollection().