Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportEnumMapping
ImportEnumMapping()
EnumMapping System.Xml.Serialization.XmlReflectionImporter.ImportEnumMapping (EnumModel model, string ns, bool repeats) inline private
Definition at line 1191 of file XmlReflectionImporter.cs.
    {
        XmlAttributes attributes = GetAttributes(model.Type, canBeSimpleType: false);
        string text = ns;
        if (attributes.XmlType != null && attributes.XmlType.Namespace != null)
        {
            text = attributes.XmlType.Namespace;
        }
        string name = (IsAnonymousType(attributes, ns) ? null : XsdTypeName(model.Type, attributes, model.TypeDesc.Name));
        name = XmlConvert.EncodeLocalName(name);
        EnumMapping enumMapping = (EnumMapping)GetTypeMapping(name, text, model.TypeDesc, _types, model.Type);
        if (enumMapping == null)
        {
            enumMapping = new EnumMapping();
            enumMapping.TypeDesc = model.TypeDesc;
            enumMapping.TypeName = name;
            enumMapping.Namespace = text;
            enumMapping.IsFlags = model.Type.IsDefined(typeof(FlagsAttribute), inherit: false);
            if (enumMapping.IsFlags && repeats)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalAttributeFlagsArray, model.TypeDesc.FullName));
            }
            enumMapping.IsList = repeats;
            enumMapping.IncludeInSchema = attributes.XmlType == null || attributes.XmlType.IncludeInSchema;
            if (!enumMapping.IsAnonymousType)
            {
                _types.Add(name, text, enumMapping);
            }
            else
            {
                _anonymous[model.Type] = enumMapping;
            }
            List<ConstantMapping> list = new List<ConstantMapping>();
            for (int i = 0; i < model.Constants.Length; i++)
            {
                ConstantMapping constantMapping = ImportConstantMapping(model.Constants[i]);
                if (constantMapping != null)
                {
                    list.Add(constantMapping);
                }
            }
            if (list.Count == 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlNoSerializableMembers, model.TypeDesc.FullName));
            }
            enumMapping.Constants = list.ToArray();
            _typeScope.AddTypeMapping(enumMapping);
        }
        return enumMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._anonymous, System.Xml.Serialization.XmlReflectionImporter._types, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.NameTable.Add(), System.Xml.Serialization.TypeScope.AddTypeMapping(), System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.SR.Format(), System.Xml.Serialization.XmlReflectionImporter.GetAttributes(), System.Xml.Serialization.XmlReflectionImporter.GetTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportConstantMapping(), System.Xml.Serialization.XmlTypeAttribute.IncludeInSchema, System.Xml.Serialization.XmlReflectionImporter.IsAnonymousType(), System.list, System.Xml.Serialization.XmlTypeAttribute.Namespace, System.text, System.SR.XmlIllegalAttributeFlagsArray, System.SR.XmlNoSerializableMembers, System.Xml.Serialization.XmlAttributes.XmlType, and System.Xml.Serialization.XmlReflectionImporter.XsdTypeName().
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping().