Terraria: System.Xml.Serialization.XmlReflectionImporter.CreateArrayElementsFromAttributes
CreateArrayElementsFromAttributes()
void System.Xml.Serialization.XmlReflectionImporter.CreateArrayElementsFromAttributes (ArrayMapping arrayMapping, XmlArrayItemAttributes attributes, Type arrayElementType, string arrayElementNs, RecursionLimiter limiter) inline private
Definition at line 1509 of file XmlReflectionImporter.cs.
    {
        NameTable nameTable = new NameTable();
        int num = 0;
        while (attributes != null && num < attributes.Count)
        {
            XmlArrayItemAttribute xmlArrayItemAttribute = attributes[num];
            if (xmlArrayItemAttribute.NestingLevel == _arrayNestingLevel)
            {
                Type type = ((xmlArrayItemAttribute.Type != null) ? xmlArrayItemAttribute.Type : arrayElementType);
                TypeDesc typeDesc = _typeScope.GetTypeDesc(type);
                ElementAccessor elementAccessor = new ElementAccessor();
                elementAccessor.Namespace = ((xmlArrayItemAttribute.Namespace == null) ? arrayElementNs : xmlArrayItemAttribute.Namespace);
                elementAccessor.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(type), elementAccessor.Namespace, ImportContext.Element, xmlArrayItemAttribute.DataType, null, limiter);
                elementAccessor.Name = ((xmlArrayItemAttribute.ElementName.Length == 0) ? elementAccessor.Mapping.DefaultElementName : XmlConvert.EncodeLocalName(xmlArrayItemAttribute.ElementName));
                elementAccessor.IsNullable = (xmlArrayItemAttribute.GetIsNullableSpecified() ? xmlArrayItemAttribute.IsNullable : (typeDesc.IsNullable || typeDesc.IsOptionalValue));
                elementAccessor.Form = ((xmlArrayItemAttribute.Form == XmlSchemaForm.None) ? XmlSchemaForm.Qualified : xmlArrayItemAttribute.Form);
                CheckForm(elementAccessor.Form, arrayElementNs != elementAccessor.Namespace);
                CheckNullable(elementAccessor.IsNullable, typeDesc, elementAccessor.Mapping);
                AddUniqueAccessor(nameTable, elementAccessor);
            }
            num++;
        }
        arrayMapping.Elements = (ElementAccessor[])nameTable.ToArray(typeof(ElementAccessor));
    }
References System.Xml.Serialization.XmlReflectionImporter._arrayNestingLevel, System.Xml.Serialization.XmlReflectionImporter._modelScope, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.XmlReflectionImporter.AddUniqueAccessor(), System.Xml.Serialization.XmlReflectionImporter.CheckForm(), System.Xml.Serialization.XmlReflectionImporter.CheckNullable(), System.Collections.CollectionBase.Count, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), and System.type.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping().