Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping
ImportTypeMapping() [4/6]
XmlTypeMapping System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping (Type type, XmlRootAttribute? root, string? defaultNamespace) inline
Definition at line 145 of file XmlReflectionImporter.cs.
    {
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        XmlTypeMapping xmlTypeMapping = new XmlTypeMapping(_typeScope, ImportElement(_modelScope.GetTypeModel(type), root, defaultNamespace, new RecursionLimiter()));
        xmlTypeMapping.SetKeyInternal(XmlMapping.GenerateKey(type, root, defaultNamespace));
        xmlTypeMapping.GenerateSerializer = true;
        return xmlTypeMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._modelScope, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Dictionary, System.Xml.Serialization.XmlMapping.GenerateKey(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.XmlReflectionImporter.ImportElement(), and System.type.