Terraria: System.Xml.Serialization.XmlReflectionImporter.SetArrayMappingType
SetArrayMappingType()
void System.Xml.Serialization.XmlReflectionImporter.SetArrayMappingType (ArrayMapping mapping, string defaultNs, Type type) inline private
Definition at line 993 of file XmlReflectionImporter.cs.
    {
        XmlAttributes attributes = GetAttributes(type, canBeSimpleType: false);
        if (IsAnonymousType(attributes, defaultNs))
        {
            mapping.TypeName = null;
            mapping.Namespace = defaultNs;
            return;
        }
        ElementAccessor elementAccessor = null;
        TypeMapping typeMapping;
        if (mapping.Elements.Length == 1)
        {
            elementAccessor = mapping.Elements[0];
            typeMapping = elementAccessor.Mapping;
        }
        else
        {
            typeMapping = null;
        }
        bool flag = true;
        string text;
        string name;
        if (attributes.XmlType != null)
        {
            text = attributes.XmlType.Namespace;
            name = XsdTypeName(type, attributes, attributes.XmlType.TypeName);
            name = XmlConvert.EncodeLocalName(name);
            flag = name == null;
        }
        else if (typeMapping is EnumMapping)
        {
            text = typeMapping.Namespace;
            name = typeMapping.DefaultElementName;
        }
        else if (typeMapping is PrimitiveMapping)
        {
            text = defaultNs;
            name = typeMapping.TypeDesc.DataType.Name;
        }
        else if (typeMapping is StructMapping && typeMapping.TypeDesc.IsRoot)
        {
            text = defaultNs;
            name = "anyType";
        }
        else if (typeMapping != null)
        {
            text = ((typeMapping.Namespace == "http://www.w3.org/2001/XMLSchema") ? defaultNs : typeMapping.Namespace);
            name = typeMapping.DefaultElementName;
        }
        else
        {
            text = defaultNs;
            name = "Choice" + _choiceNum++;
        }
        if (name == null)
        {
            name = "Any";
        }
        if (elementAccessor != null)
        {
            text = elementAccessor.Namespace;
        }
        if (text == null)
        {
            text = defaultNs;
        }
        string text2 = (name = (flag ? ("ArrayOf" + CodeIdentifier.MakePascal(name)) : name));
        int num = 1;
        TypeMapping typeMapping2 = (TypeMapping)_types[text2, text];
        while (typeMapping2 != null)
        {
            if (typeMapping2 is ArrayMapping)
            {
                ArrayMapping arrayMapping = (ArrayMapping)typeMapping2;
                if (AccessorMapping.ElementsMatch(arrayMapping.Elements, mapping.Elements))
                {
                    break;
                }
            }
            text2 = name + num.ToString(CultureInfo.InvariantCulture);
            typeMapping2 = (TypeMapping)_types[text2, text];
            num++;
        }
        mapping.TypeName = text2;
        mapping.Namespace = text;
    }
References System.Xml.Serialization.XmlReflectionImporter._choiceNum, System.Xml.Serialization.XmlReflectionImporter._types, System.Xml.Dictionary, System.Xml.Serialization.AccessorMapping.ElementsMatch(), System.Xml.XmlConvert.EncodeLocalName(), System.Xml.Serialization.XmlReflectionImporter.GetAttributes(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlReflectionImporter.IsAnonymousType(), System.Xml.Serialization.CodeIdentifier.MakePascal(), System.Xml.Serialization.XmlTypeAttribute.Namespace, System.text, System.type, System.Xml.Serialization.XmlTypeAttribute.TypeName, System.Xml.Serialization.XmlAttributes.XmlType, and System.Xml.Serialization.XmlReflectionImporter.XsdTypeName().
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping().