Terraria: System.Xml.Serialization.XmlReflectionImporter.CheckChoiceIdentifierMapping
CheckChoiceIdentifierMapping()
void System.Xml.Serialization.XmlReflectionImporter.CheckChoiceIdentifierMapping (EnumMapping choiceMapping) inline private
Definition at line 2138 of file XmlReflectionImporter.cs.
    {
        NameTable nameTable = new NameTable();
        for (int i = 0; i < choiceMapping.Constants.Length; i++)
        {
            string xmlName = choiceMapping.Constants[i].XmlName;
            int num = xmlName.LastIndexOf(':');
            string name = ((num < 0) ? xmlName : xmlName.Substring(num + 1));
            string ns = ((num < 0) ? "" : xmlName.Substring(0, num));
            if (nameTable[name, ns] != null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceIdDuplicate, choiceMapping.TypeName, xmlName));
            }
            nameTable.Add(name, ns, choiceMapping.Constants[i]);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.Format(), and System.SR.XmlChoiceIdDuplicate.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping().