Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping
ImportMembersMapping() [4/5]
XmlMembersMapping System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping (string? elementName, string? ns, XmlReflectionMember[] members, bool hasWrapperElement, bool rpc, bool openModel, XmlMappingAccess access) inline
Definition at line 176 of file XmlReflectionImporter.cs.
    {
        ElementAccessor elementAccessor = new ElementAccessor();
        elementAccessor.Name = ((elementName == null || elementName.Length == 0) ? elementName : XmlConvert.EncodeLocalName(elementName));
        elementAccessor.Namespace = ns;
        MembersMapping membersMapping = (MembersMapping)(elementAccessor.Mapping = ImportMembersMapping(members, ns, hasWrapperElement, rpc, openModel, new RecursionLimiter()));
        elementAccessor.Form = XmlSchemaForm.Qualified;
        if (!rpc)
        {
            if (hasWrapperElement)
            {
                elementAccessor = (ElementAccessor)ReconcileAccessor(elementAccessor, _elements);
            }
            else
            {
                MemberMapping[] members2 = membersMapping.Members;
                foreach (MemberMapping memberMapping in members2)
                {
                    if (memberMapping.Elements != null && memberMapping.Elements.Length != 0)
                    {
                        memberMapping.Elements[0] = (ElementAccessor)ReconcileAccessor(memberMapping.Elements[0], _elements);
                    }
                }
            }
        }
        XmlMembersMapping xmlMembersMapping = new XmlMembersMapping(_typeScope, elementAccessor, access);
        xmlMembersMapping.GenerateSerializer = true;
        return xmlMembersMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._elements, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping(), and System.Xml.Serialization.XmlReflectionImporter.ReconcileAccessor().