Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping
ImportStructLikeMapping()
StructMapping System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping (StructModel model, string ns, bool openModel, XmlAttributes a, RecursionLimiter limiter) inline private
Definition at line 709 of file XmlReflectionImporter.cs.
    {
        if (model.TypeDesc.Kind == TypeKind.Root)
        {
            return GetRootMapping();
        }
        if (a == null)
        {
            a = GetAttributes(model.Type, canBeSimpleType: false);
        }
        string text = ns;
        if (a.XmlType != null && a.XmlType.Namespace != null)
        {
            text = a.XmlType.Namespace;
        }
        else if (a.XmlRoot != null && a.XmlRoot.Namespace != null)
        {
            text = a.XmlRoot.Namespace;
        }
        string name = (IsAnonymousType(a, ns) ? null : XsdTypeName(model.Type, a, model.TypeDesc.Name));
        name = XmlConvert.EncodeLocalName(name);
        StructMapping structMapping = (StructMapping)GetTypeMapping(name, text, model.TypeDesc, _types, model.Type);
        if (structMapping == null)
        {
            structMapping = new StructMapping();
            structMapping.TypeDesc = model.TypeDesc;
            structMapping.Namespace = text;
            structMapping.TypeName = name;
            if (!structMapping.IsAnonymousType)
            {
                _types.Add(name, text, structMapping);
            }
            else
            {
                _anonymous[model.Type] = structMapping;
            }
            if (a.XmlType != null)
            {
                structMapping.IncludeInSchema = a.XmlType.IncludeInSchema;
            }
            if (limiter.IsExceededLimit)
            {
                limiter.DeferredWorkItems.Add(new ImportStructWorkItem(model, structMapping));
                return structMapping;
            }
            limiter.Depth++;
            InitializeStructMembers(structMapping, model, openModel, name, limiter);
            while (limiter.DeferredWorkItems.Count > 0)
            {
                int index = limiter.DeferredWorkItems.Count - 1;
                ImportStructWorkItem importStructWorkItem = limiter.DeferredWorkItems[index];
                if (InitializeStructMembers(importStructWorkItem.Mapping, importStructWorkItem.Model, openModel, name, limiter))
                {
                    limiter.DeferredWorkItems.RemoveAt(index);
                }
            }
            limiter.Depth--;
        }
        return structMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._anonymous, System.Xml.Serialization.XmlReflectionImporter._types, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.NameTable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.Serialization.XmlReflectionImporter.GetAttributes(), System.Xml.Serialization.XmlReflectionImporter.GetRootMapping(), System.Xml.Serialization.XmlReflectionImporter.GetTypeMapping(), System.index, System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(), System.Xml.Serialization.XmlReflectionImporter.IsAnonymousType(), System.text, and System.Xml.Serialization.XmlReflectionImporter.XsdTypeName().
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), and System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers().