Terraria: System.Xml.Serialization.XmlReflectionImporter.GetMethodFromSchemaProvider
GetMethodFromSchemaProvider()
static MethodInfo System.Xml.Serialization.XmlReflectionImporter.GetMethodFromSchemaProvider (XmlSchemaProviderAttribute provider, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods)] Type type) inline static package
Definition at line 478 of file XmlReflectionImporter.cs.
    {
        if (provider.IsAny)
        {
            return null;
        }
        if (provider.MethodName == null)
        {
            throw new ArgumentNullException("MethodName");
        }
        if (!CSharpHelpers.IsValidLanguageIndependentIdentifier(provider.MethodName))
        {
            throw new ArgumentException(System.SR.Format(System.SR.XmlGetSchemaMethodName, provider.MethodName), "MethodName");
        }
        MethodInfo method = (method = type.GetMethod(provider.MethodName, BindingFlags.Static | BindingFlags.Public, new Type[1] { typeof(XmlSchemaSet) }));
        if (method == null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlGetSchemaMethodMissing, provider.MethodName, "XmlSchemaSet", type.FullName));
        }
        if (!typeof(XmlQualifiedName).IsAssignableFrom(method.ReturnType) && !typeof(XmlSchemaType).IsAssignableFrom(method.ReturnType))
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlGetSchemaMethodReturnType, type.Name, provider.MethodName, "XmlSchemaProviderAttribute", typeof(XmlQualifiedName).FullName, typeof(XmlSchemaType).FullName));
        }
        return method;
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, System.SR.Format(), System.FullName, System.CSharpHelpers.IsValidLanguageIndependentIdentifier(), System.type, System.SR.XmlGetSchemaMethodMissing, System.SR.XmlGetSchemaMethodName, and System.SR.XmlGetSchemaMethodReturnType.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportSpecialMapping().