Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportElement
ImportElement()
ElementAccessor System.Xml.Serialization.XmlReflectionImporter.ImportElement (TypeModel model, XmlRootAttribute root, string defaultNamespace, RecursionLimiter limiter) inline private
Definition at line 231 of file XmlReflectionImporter.cs.
    {
        XmlAttributes attributes = GetAttributes(model.Type, canBeSimpleType: true);
        if (root == null)
        {
            root = attributes.XmlRoot;
        }
        string text = root?.Namespace;
        if (text == null)
        {
            text = defaultNamespace;
        }
        if (text == null)
        {
            text = _defaultNs;
        }
        _arrayNestingLevel = -1;
        _savedArrayItemAttributes = null;
        _savedArrayNamespace = null;
        ElementAccessor elementAccessor = CreateElementAccessor(ImportTypeMapping(model, text, ImportContext.Element, string.Empty, attributes, limiter), text);
        if (root != null)
        {
            if (root.ElementName.Length > 0)
            {
                elementAccessor.Name = XmlConvert.EncodeLocalName(root.ElementName);
            }
            if (root.GetIsNullableSpecified() && !root.IsNullable && model.TypeDesc.IsOptionalValue)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidNotNullable, model.TypeDesc.BaseTypeDesc.FullName, "XmlRoot"));
            }
            elementAccessor.IsNullable = (root.GetIsNullableSpecified() ? root.IsNullable : (model.TypeDesc.IsNullable || model.TypeDesc.IsOptionalValue));
            CheckNullable(elementAccessor.IsNullable, model.TypeDesc, elementAccessor.Mapping);
        }
        else
        {
            elementAccessor.IsNullable = model.TypeDesc.IsNullable || model.TypeDesc.IsOptionalValue;
        }
        elementAccessor.Form = XmlSchemaForm.Qualified;
        return (ElementAccessor)ReconcileAccessor(elementAccessor, _elements);
    }
References System.Xml.Serialization.XmlReflectionImporter._arrayNestingLevel, System.Xml.Serialization.XmlReflectionImporter._defaultNs, System.Xml.Serialization.XmlReflectionImporter._elements, System.Xml.Serialization.XmlReflectionImporter._savedArrayItemAttributes, System.Xml.Serialization.XmlReflectionImporter._savedArrayNamespace, System.Xml.Serialization.XmlReflectionImporter.CheckNullable(), System.Xml.Serialization.XmlReflectionImporter.CreateElementAccessor(), System.Xml.Dictionary, System.Xml.Serialization.XmlRootAttribute.ElementName, System.Xml.XmlConvert.EncodeLocalName(), System.SR.Format(), System.Xml.Serialization.XmlReflectionImporter.GetAttributes(), System.Xml.Serialization.XmlRootAttribute.GetIsNullableSpecified(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.XmlRootAttribute.IsNullable, System.Xml.Serialization.XmlRootAttribute.Namespace, System.Xml.Serialization.XmlReflectionImporter.ReconcileAccessor(), System.text, System.SR.XmlInvalidNotNullable, and System.Xml.Serialization.XmlAttributes.XmlRoot.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping().