Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping
ImportAccessorMapping()
void System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping (MemberMapping accessor, FieldModel model, XmlAttributes a, string ns, Type choiceIdentifierType, bool rpc, bool openModel, RecursionLimiter limiter) inline private
Definition at line 1536 of file XmlReflectionImporter.cs.
    {
        XmlSchemaForm xmlSchemaForm = XmlSchemaForm.Qualified;
        int arrayNestingLevel = _arrayNestingLevel;
        int num = -1;
        XmlArrayItemAttributes savedArrayItemAttributes = _savedArrayItemAttributes;
        string savedArrayNamespace = _savedArrayNamespace;
        _arrayNestingLevel = 0;
        _savedArrayItemAttributes = null;
        _savedArrayNamespace = null;
        Type fieldType = model.FieldType;
        string name = model.Name;
        ArrayList arrayList = new ArrayList();
        NameTable nameTable = new NameTable();
        accessor.TypeDesc = _typeScope.GetTypeDesc(fieldType);
        XmlAttributeFlags xmlFlags = a.XmlFlags;
        accessor.Ignore = a.XmlIgnore;
        if (rpc)
        {
            CheckTopLevelAttributes(a, name);
        }
        else
        {
            CheckAmbiguousChoice(a, fieldType, name);
        }
        XmlAttributeFlags xmlAttributeFlags = (XmlAttributeFlags)1300;
        XmlAttributeFlags xmlAttributeFlags2 = (XmlAttributeFlags)544;
        XmlAttributeFlags xmlAttributeFlags3 = (XmlAttributeFlags)10;
        if ((xmlFlags & xmlAttributeFlags3) != 0 && fieldType == typeof(byte[]))
        {
            accessor.TypeDesc = _typeScope.GetArrayTypeDesc(fieldType);
        }
        if (a.XmlChoiceIdentifier != null)
        {
            accessor.ChoiceIdentifier = new ChoiceIdentifierAccessor();
            accessor.ChoiceIdentifier.MemberName = a.XmlChoiceIdentifier.MemberName;
            accessor.ChoiceIdentifier.MemberInfo = a.XmlChoiceIdentifier.GetMemberInfo();
            accessor.ChoiceIdentifier.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(choiceIdentifierType), ns, ImportContext.Element, string.Empty, null, limiter);
            CheckChoiceIdentifierMapping((EnumMapping)accessor.ChoiceIdentifier.Mapping);
        }
        if (accessor.TypeDesc.IsArrayLike)
        {
            Type arrayElementType = TypeScope.GetArrayElementType(fieldType, model.FieldTypeDesc.FullName + "." + model.Name);
            if ((xmlFlags & xmlAttributeFlags2) != 0)
            {
                if ((xmlFlags & xmlAttributeFlags2) != xmlFlags)
                {
                    throw new InvalidOperationException(System.SR.XmlIllegalAttributesArrayAttribute);
                }
                if (a.XmlAttribute != null && !accessor.TypeDesc.ArrayElementTypeDesc.IsPrimitive && !accessor.TypeDesc.ArrayElementTypeDesc.IsEnum)
                {
                    if (accessor.TypeDesc.ArrayElementTypeDesc.Kind == TypeKind.Serializable)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalAttrOrTextInterface, name, accessor.TypeDesc.ArrayElementTypeDesc.FullName, "IXmlSerializable"));
                    }
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalAttrOrText, name, accessor.TypeDesc.ArrayElementTypeDesc.FullName));
                }
                bool flag = a.XmlAttribute != null && (accessor.TypeDesc.ArrayElementTypeDesc.IsPrimitive || accessor.TypeDesc.ArrayElementTypeDesc.IsEnum);
                if (a.XmlAnyAttribute != null)
                {
                    a.XmlAttribute = new XmlAttributeAttribute();
                }
                AttributeAccessor attributeAccessor = new AttributeAccessor();
                Type type = ((a.XmlAttribute.Type == null) ? arrayElementType : a.XmlAttribute.Type);
                TypeDesc typeDesc = _typeScope.GetTypeDesc(type);
                attributeAccessor.Name = Accessor.EscapeQName((a.XmlAttribute.AttributeName.Length == 0) ? name : a.XmlAttribute.AttributeName);
                attributeAccessor.Namespace = ((a.XmlAttribute.Namespace == null) ? ns : a.XmlAttribute.Namespace);
                attributeAccessor.Form = a.XmlAttribute.Form;
                if (attributeAccessor.Form == XmlSchemaForm.None && ns != attributeAccessor.Namespace)
                {
                    attributeAccessor.Form = XmlSchemaForm.Qualified;
                }
                attributeAccessor.CheckSpecial();
                CheckForm(attributeAccessor.Form, ns != attributeAccessor.Namespace);
                attributeAccessor.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(type), ns, ImportContext.Attribute, a.XmlAttribute.DataType, null, flag, openModel: false, limiter);
                attributeAccessor.IsList = flag;
                attributeAccessor.Default = GetDefaultValue(model.FieldTypeDesc, model.FieldType, a);
                attributeAccessor.Any = a.XmlAnyAttribute != null;
                if (attributeAccessor.Form == XmlSchemaForm.Qualified && attributeAccessor.Namespace != ns)
                {
                    if (_xsdAttributes == null)
                    {
                        _xsdAttributes = new NameTable();
                    }
                    attributeAccessor = (AttributeAccessor)ReconcileAccessor(attributeAccessor, _xsdAttributes);
                }
                accessor.Attribute = attributeAccessor;
            }
            else if ((xmlFlags & xmlAttributeFlags) != 0)
            {
                if ((xmlFlags & xmlAttributeFlags) != xmlFlags)
                {
                    throw new InvalidOperationException(System.SR.XmlIllegalElementsArrayAttribute);
                }
                if (a.XmlText != null)
                {
                    TextAccessor textAccessor = new TextAccessor();
                    Type type2 = ((a.XmlText.Type == null) ? arrayElementType : a.XmlText.Type);
                    TypeDesc typeDesc2 = _typeScope.GetTypeDesc(type2);
                    textAccessor.Name = name;
                    textAccessor.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(type2), ns, ImportContext.Text, a.XmlText.DataType, null, repeats: true, openModel: false, limiter);
                    if (!(textAccessor.Mapping is SpecialMapping) && typeDesc2 != _typeScope.GetTypeDesc(typeof(string)))
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalArrayTextAttribute, name));
                    }
                    accessor.Text = textAccessor;
                }
                if (a.XmlText == null && a.XmlElements.Count == 0 && a.XmlAnyElements.Count == 0)
                {
                    a.XmlElements.Add(CreateElementAttribute(accessor.TypeDesc));
                }
                for (int i = 0; i < a.XmlElements.Count; i++)
                {
                    XmlElementAttribute xmlElementAttribute = a.XmlElements[i];
                    Type type3 = ((xmlElementAttribute.Type == null) ? arrayElementType : xmlElementAttribute.Type);
                    TypeDesc typeDesc3 = _typeScope.GetTypeDesc(type3);
                    TypeModel typeModel = _modelScope.GetTypeModel(type3);
                    ElementAccessor elementAccessor = new ElementAccessor();
                    elementAccessor.Namespace = (rpc ? null : ((xmlElementAttribute.Namespace == null) ? ns : xmlElementAttribute.Namespace));
                    elementAccessor.Mapping = ImportTypeMapping(typeModel, rpc ? ns : elementAccessor.Namespace, ImportContext.Element, xmlElementAttribute.DataType, null, limiter);
                    if (a.XmlElements.Count == 1)
                    {
                        elementAccessor.Name = XmlConvert.EncodeLocalName((xmlElementAttribute.ElementName.Length == 0) ? name : xmlElementAttribute.ElementName);
                    }
                    else
                    {
                        elementAccessor.Name = ((xmlElementAttribute.ElementName.Length == 0) ? elementAccessor.Mapping.DefaultElementName : XmlConvert.EncodeLocalName(xmlElementAttribute.ElementName));
                    }
                    elementAccessor.Default = GetDefaultValue(model.FieldTypeDesc, model.FieldType, a);
                    if (xmlElementAttribute.GetIsNullableSpecified() && !xmlElementAttribute.IsNullable && typeModel.TypeDesc.IsOptionalValue)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidNotNullable, typeModel.TypeDesc.BaseTypeDesc.FullName, "XmlElement"));
                    }
                    elementAccessor.IsNullable = (xmlElementAttribute.GetIsNullableSpecified() ? xmlElementAttribute.IsNullable : typeModel.TypeDesc.IsOptionalValue);
                    elementAccessor.Form = (rpc ? XmlSchemaForm.Unqualified : ((xmlElementAttribute.Form == XmlSchemaForm.None) ? xmlSchemaForm : xmlElementAttribute.Form));
                    CheckNullable(elementAccessor.IsNullable, typeDesc3, elementAccessor.Mapping);
                    if (!rpc)
                    {
                        CheckForm(elementAccessor.Form, ns != elementAccessor.Namespace);
                        elementAccessor = ReconcileLocalAccessor(elementAccessor, ns);
                    }
                    if (xmlElementAttribute.Order != -1)
                    {
                        if (xmlElementAttribute.Order != num && num != -1)
{
                            throw new InvalidOperationException(System.SR.Format(System.SR.XmlSequenceMatch, "Order"));
                        }
                        num = xmlElementAttribute.Order;
                    }
                    AddUniqueAccessor(nameTable, elementAccessor);
                    arrayList.Add(elementAccessor);
                }
                NameTable nameTable2 = new NameTable();
                for (int j = 0; j < a.XmlAnyElements.Count; j++)
                {
                    XmlAnyElementAttribute xmlAnyElementAttribute = a.XmlAnyElements[j];
                    Type type4 = (typeof(IXmlSerializable).IsAssignableFrom(arrayElementType) ? arrayElementType : (typeof(XmlNode).IsAssignableFrom(arrayElementType) ? arrayElementType : typeof(XmlElement)));
                    if (!arrayElementType.IsAssignableFrom(type4))
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalAnyElement, arrayElementType.FullName));
                    }
                    string name2 = ((xmlAnyElementAttribute.Name.Length == 0) ? xmlAnyElementAttribute.Name : XmlConvert.EncodeLocalName(xmlAnyElementAttribute.Name));
                    string text = (xmlAnyElementAttribute.GetNamespaceSpecified() ? xmlAnyElementAttribute.Namespace : null);
                    if (nameTable2[name2, text] != null)
                    {
                        continue;
                    }
                    nameTable2[name2, text] = xmlAnyElementAttribute;
                    if (nameTable[name2, (text == null) ? ns : text] != null)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlAnyElementDuplicate, name, xmlAnyElementAttribute.Name, (xmlAnyElementAttribute.Namespace == null) ? "null" : xmlAnyElementAttribute.Namespace));
                    }
                    ElementAccessor elementAccessor2 = new ElementAccessor();
                    elementAccessor2.Name = name2;
                    elementAccessor2.Namespace = ((text == null) ? ns : text);
                    elementAccessor2.Any = true;
                    elementAccessor2.AnyNamespaces = text;
                    TypeDesc typeDesc4 = _typeScope.GetTypeDesc(type4);
                    TypeModel typeModel2 = _modelScope.GetTypeModel(type4);
                    if (elementAccessor2.Name.Length > 0)
                    {
                        typeModel2.TypeDesc.IsMixed = true;
                    }
                    elementAccessor2.Mapping = ImportTypeMapping(typeModel2, elementAccessor2.Namespace, ImportContext.Element, string.Empty, null, limiter);
                    elementAccessor2.Default = GetDefaultValue(model.FieldTypeDesc, model.FieldType, a);
                    elementAccessor2.IsNullable = false;
                    elementAccessor2.Form = xmlSchemaForm;
                    CheckNullable(elementAccessor2.IsNullable, typeDesc4, elementAccessor2.Mapping);
                    if (!rpc)
                    {
                        CheckForm(elementAccessor2.Form, ns != elementAccessor2.Namespace);
                        elementAccessor2 = ReconcileLocalAccessor(elementAccessor2, ns);
                    }
                    nameTable.Add(elementAccessor2.Name, elementAccessor2.Namespace, elementAccessor2);
                    arrayList.Add(elementAccessor2);
                    if (xmlAnyElementAttribute.Order != -1)
                    {
                        if (xmlAnyElementAttribute.Order != num && num != -1)
{
                            throw new InvalidOperationException(System.SR.Format(System.SR.XmlSequenceMatch, "Order"));
                        }
                        num = xmlAnyElementAttribute.Order;
                    }
                }
            }
            else
            {
                if ((xmlFlags & xmlAttributeFlags3) != 0 && (xmlFlags & xmlAttributeFlags3) != xmlFlags)
                {
                    throw new InvalidOperationException(System.SR.XmlIllegalArrayArrayAttribute);
                }
                TypeDesc typeDesc5 = _typeScope.GetTypeDesc(arrayElementType);
                if (a.XmlArray == null)
                {
                    a.XmlArray = CreateArrayAttribute(accessor.TypeDesc);
                }
                if (CountAtLevel(a.XmlArrayItems, _arrayNestingLevel) == 0)
                {
                    a.XmlArrayItems.Add(CreateArrayItemAttribute(typeDesc5, _arrayNestingLevel));
                }
                ElementAccessor elementAccessor3 = new ElementAccessor();
                elementAccessor3.Name = XmlConvert.EncodeLocalName((a.XmlArray.ElementName.Length == 0) ? name : a.XmlArray.ElementName);
                elementAccessor3.Namespace = (rpc ? null : ((a.XmlArray.Namespace == null) ? ns : a.XmlArray.Namespace));
                _savedArrayItemAttributes = a.XmlArrayItems;
                _savedArrayNamespace = elementAccessor3.Namespace;
                ArrayMapping mapping = ImportArrayLikeMapping(_modelScope.GetArrayModel(fieldType), ns, limiter);
                elementAccessor3.Mapping = mapping;
                elementAccessor3.IsNullable = a.XmlArray.IsNullable;
                elementAccessor3.Form = (rpc ? XmlSchemaForm.Unqualified : ((a.XmlArray.Form == XmlSchemaForm.None) ? xmlSchemaForm : a.XmlArray.Form));
                num = a.XmlArray.Order;
                CheckNullable(elementAccessor3.IsNullable, accessor.TypeDesc, elementAccessor3.Mapping);
                if (!rpc)
                {
                    CheckForm(elementAccessor3.Form, ns != elementAccessor3.Namespace);
                    elementAccessor3 = ReconcileLocalAccessor(elementAccessor3, ns);
                }
                _savedArrayItemAttributes = null;
                _savedArrayNamespace = null;
                AddUniqueAccessor(nameTable, elementAccessor3);
                arrayList.Add(elementAccessor3);
            }
        }
        else if (!accessor.TypeDesc.IsVoid)
        {
            XmlAttributeFlags xmlAttributeFlags4 = (XmlAttributeFlags)3380;
            if ((xmlFlags & xmlAttributeFlags4) != xmlFlags)
            {
                throw new InvalidOperationException(System.SR.XmlIllegalAttribute);
            }
            if (accessor.TypeDesc.IsPrimitive || accessor.TypeDesc.IsEnum)
            {
                if (a.XmlAnyElements.Count > 0)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalAnyElement, accessor.TypeDesc.FullName));
                }
                if (a.XmlAttribute != null)
                {
                    if (a.XmlElements.Count > 0)
                    {
                        throw new InvalidOperationException(System.SR.XmlIllegalAttribute);
                    }
                    if (a.XmlAttribute.Type != null)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalType, "XmlAttribute"));
                    }
                    AttributeAccessor attributeAccessor2 = new AttributeAccessor();
                    attributeAccessor2.Name = Accessor.EscapeQName((a.XmlAttribute.AttributeName.Length == 0) ? name : a.XmlAttribute.AttributeName);
                    attributeAccessor2.Namespace = ((a.XmlAttribute.Namespace == null) ? ns : a.XmlAttribute.Namespace);
                    attributeAccessor2.Form = a.XmlAttribute.Form;
                    if (attributeAccessor2.Form == XmlSchemaForm.None && ns != attributeAccessor2.Namespace)
                    {
                        attributeAccessor2.Form = XmlSchemaForm.Qualified;
                    }
                    attributeAccessor2.CheckSpecial();
                    CheckForm(attributeAccessor2.Form, ns != attributeAccessor2.Namespace);
                    attributeAccessor2.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(fieldType), ns, ImportContext.Attribute, a.XmlAttribute.DataType, null, limiter);
                    attributeAccessor2.Default = GetDefaultValue(model.FieldTypeDesc, model.FieldType, a);
                    attributeAccessor2.Any = a.XmlAnyAttribute != null;
                    if (attributeAccessor2.Form == XmlSchemaForm.Qualified && attributeAccessor2.Namespace != ns)
                    {
                        if (_xsdAttributes == null)
{
                            _xsdAttributes = new NameTable();
                        }
                        attributeAccessor2 = (AttributeAccessor)ReconcileAccessor(attributeAccessor2, _xsdAttributes);
                    }
                    accessor.Attribute = attributeAccessor2;
                }
                else
                {
                    if (a.XmlText != null)
                    {
                        if (a.XmlText.Type != null && a.XmlText.Type != fieldType)
{
                            throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalType, "XmlText"));
                        }
                        TextAccessor textAccessor2 = new TextAccessor();
                        textAccessor2.Name = name;
                        textAccessor2.Mapping = ImportTypeMapping(_modelScope.GetTypeModel(fieldType), ns, ImportContext.Text, a.XmlText.DataType, null, limiter);
                        accessor.Text = textAccessor2;
                    }
                    else if (a.XmlElements.Count == 0)
                    {
                        a.XmlElements.Add(CreateElementAttribute(accessor.TypeDesc));
                    }
                    for (int k = 0; k < a.XmlElements.Count; k++)
                    {
                        XmlElementAttribute xmlElementAttribute2 = a.XmlElements[k];
                        if (xmlElementAttribute2.Type != null && _typeScope.GetTypeDesc(xmlElementAttribute2.Type) != accessor.TypeDesc)
{
                            throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalType, "XmlElement"));
                        }
                        ElementAccessor elementAccessor4 = new ElementAccessor();
                        elementAccessor4.Name = XmlConvert.EncodeLocalName((xmlElementAttribute2.ElementName.Length == 0) ? name : xmlElementAttribute2.ElementName);
                        elementAccessor4.Namespace = (rpc ? null : ((xmlElementAttribute2.Namespace == null) ? ns : xmlElementAttribute2.Namespace));
                        TypeModel typeModel3 = _modelScope.GetTypeModel(fieldType);
                        elementAccessor4.Mapping = ImportTypeMapping(typeModel3, rpc ? ns : elementAccessor4.Namespace, ImportContext.Element, xmlElementAttribute2.DataType, null, limiter);
                        if (elementAccessor4.Mapping.TypeDesc.Kind == TypeKind.Node)
{
                            elementAccessor4.Any = true;
                        }
                        elementAccessor4.Default = GetDefaultValue(model.FieldTypeDesc, model.FieldType, a);
                        if (xmlElementAttribute2.GetIsNullableSpecified() && !xmlElementAttribute2.IsNullable && typeModel3.TypeDesc.IsOptionalValue)
{
                            throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidNotNullable, typeModel3.TypeDesc.BaseTypeDesc.FullName, "XmlElement"));
                        }
                        elementAccessor4.IsNullable = (xmlElementAttribute2.GetIsNullableSpecified() ? xmlElementAttribute2.IsNullable : typeModel3.TypeDesc.IsOptionalValue);
                        elementAccessor4.Form = (rpc ? XmlSchemaForm.Unqualified : ((xmlElementAttribute2.Form == XmlSchemaForm.None) ? xmlSchemaForm : xmlElementAttribute2.Form));
                        CheckNullable(elementAccessor4.IsNullable, accessor.TypeDesc, elementAccessor4.Mapping);
                        if (!rpc)
{
                            CheckForm(elementAccessor4.Form, ns != elementAccessor4.Namespace);
                            elementAccessor4 = ReconcileLocalAccessor(elementAccessor4, ns);
                        }
                        if (xmlElementAttribute2.Order != -1)
{
                            if (xmlElementAttribute2.Order != num && num != -1)
{
                                throw new InvalidOperationException(System.SR.Format(System.SR.XmlSequenceMatch, "Order"));
                            }
                            num = xmlElementAttribute2.Order;
                        }
                        AddUniqueAccessor(nameTable, elementAccessor4);
                        arrayList.Add(elementAccessor4);
                    }
                }
            }
            else if (a.Xmlns)
            {
                if (xmlFlags != XmlAttributeFlags.XmlnsDeclarations)
                {
                    throw new InvalidOperationException(System.SR.XmlSoleXmlnsAttribute);
                }
                if (fieldType != typeof(XmlSerializerNamespaces))
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlXmlnsInvalidType, name, fieldType.FullName, typeof(XmlSerializerNamespaces).FullName));
                }
                accessor.Xmlns = new XmlnsAccessor();
                accessor.Ignore = true;
            }
            else
            {
                if (a.XmlAttribute != null || a.XmlText != null)
                {
                    if (accessor.TypeDesc.Kind == TypeKind.Serializable)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalAttrOrTextInterface, name, accessor.TypeDesc.FullName, "IXmlSerializable"));
                    }
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalAttrOrText, name, accessor.TypeDesc));
                }
                if (a.XmlElements.Count == 0 && a.XmlAnyElements.Count == 0)
                {
                    a.XmlElements.Add(CreateElementAttribute(accessor.TypeDesc));
                }
                for (int l = 0; l < a.XmlElements.Count; l++)
                {
                    XmlElementAttribute xmlElementAttribute3 = a.XmlElements[l];
                    Type type5 = ((xmlElementAttribute3.Type == null) ? fieldType : xmlElementAttribute3.Type);
                    TypeDesc typeDesc6 = _typeScope.GetTypeDesc(type5);
                    ElementAccessor elementAccessor5 = new ElementAccessor();
                    TypeModel typeModel4 = _modelScope.GetTypeModel(type5);
                    elementAccessor5.Namespace = (rpc ? null : ((xmlElementAttribute3.Namespace == null) ? ns : xmlElementAttribute3.Namespace));
                    elementAccessor5.Mapping = ImportTypeMapping(typeModel4, rpc ? ns : elementAccessor5.Namespace, ImportContext.Element, xmlElementAttribute3.DataType, null, repeats: false, openModel, limiter);
                    if (a.XmlElements.Count == 1)
                    {
                        elementAccessor5.Name = XmlConvert.EncodeLocalName((xmlElementAttribute3.ElementName.Length == 0) ? name : xmlElementAttribute3.ElementName);
                    }
                    else
                    {
                        elementAccessor5.Name = ((xmlElementAttribute3.ElementName.Length == 0) ? elementAccessor5.Mapping.DefaultElementName : XmlConvert.EncodeLocalName(xmlElementAttribute3.ElementName));
                    }
                    elementAccessor5.Default = GetDefaultValue(model.FieldTypeDesc, model.FieldType, a);
                    if (xmlElementAttribute3.GetIsNullableSpecified() && !xmlElementAttribute3.IsNullable && typeModel4.TypeDesc.IsOptionalValue)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidNotNullable, typeModel4.TypeDesc.BaseTypeDesc.FullName, "XmlElement"));
                    }
                    elementAccessor5.IsNullable = (xmlElementAttribute3.GetIsNullableSpecified() ? xmlElementAttribute3.IsNullable : typeModel4.TypeDesc.IsOptionalValue);
                    elementAccessor5.Form = (rpc ? XmlSchemaForm.Unqualified : ((xmlElementAttribute3.Form == XmlSchemaForm.None) ? xmlSchemaForm : xmlElementAttribute3.Form));
                    CheckNullable(elementAccessor5.IsNullable, typeDesc6, elementAccessor5.Mapping);
                    if (!rpc)
                    {
                        CheckForm(elementAccessor5.Form, ns != elementAccessor5.Namespace);
                        elementAccessor5 = ReconcileLocalAccessor(elementAccessor5, ns);
                    }
                    if (xmlElementAttribute3.Order != -1)
                    {
                        if (xmlElementAttribute3.Order != num && num != -1)
{
                            throw new InvalidOperationException(System.SR.Format(System.SR.XmlSequenceMatch, "Order"));
                        }
                        num = xmlElementAttribute3.Order;
                    }
                    AddUniqueAccessor(nameTable, elementAccessor5);
                    arrayList.Add(elementAccessor5);
                }
                NameTable nameTable3 = new NameTable();
                for (int m = 0; m < a.XmlAnyElements.Count; m++)
                {
                    XmlAnyElementAttribute xmlAnyElementAttribute2 = a.XmlAnyElements[m];
                    Type type6 = (typeof(IXmlSerializable).IsAssignableFrom(fieldType) ? fieldType : (typeof(XmlNode).IsAssignableFrom(fieldType) ? fieldType : typeof(XmlElement)));
                    if (!fieldType.IsAssignableFrom(type6))
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlIllegalAnyElement, fieldType.FullName));
                    }
                    string name3 = ((xmlAnyElementAttribute2.Name.Length == 0) ? xmlAnyElementAttribute2.Name : XmlConvert.EncodeLocalName(xmlAnyElementAttribute2.Name));
                    string text2 = (xmlAnyElementAttribute2.GetNamespaceSpecified() ? xmlAnyElementAttribute2.Namespace : null);
                    if (nameTable3[name3, text2] != null)
                    {
                        continue;
                    }
                    nameTable3[name3, text2] = xmlAnyElementAttribute2;
                    if (nameTable[name3, (text2 == null) ? ns : text2] != null)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlAnyElementDuplicate, name, xmlAnyElementAttribute2.Name, (xmlAnyElementAttribute2.Namespace == null) ? "null" : xmlAnyElementAttribute2.Namespace));
                    }
                    ElementAccessor elementAccessor6 = new ElementAccessor();
                    elementAccessor6.Name = name3;
                    elementAccessor6.Namespace = ((text2 == null) ? ns : text2);
                    elementAccessor6.Any = true;
                    elementAccessor6.AnyNamespaces = text2;
                    TypeDesc typeDesc7 = _typeScope.GetTypeDesc(type6);
                    TypeModel typeModel5 = _modelScope.GetTypeModel(type6);
                    if (elementAccessor6.Name.Length > 0)
                    {
                        typeModel5.TypeDesc.IsMixed = true;
                    }
                    elementAccessor6.Mapping = ImportTypeMapping(typeModel5, elementAccessor6.Namespace, ImportContext.Element, string.Empty, null, repeats: false, openModel, limiter);
                    elementAccessor6.Default = GetDefaultValue(model.FieldTypeDesc, model.FieldType, a);
                    elementAccessor6.IsNullable = false;
                    elementAccessor6.Form = xmlSchemaForm;
                    CheckNullable(elementAccessor6.IsNullable, typeDesc7, elementAccessor6.Mapping);
                    if (!rpc)
                    {
                        CheckForm(elementAccessor6.Form, ns != elementAccessor6.Namespace);
                        elementAccessor6 = ReconcileLocalAccessor(elementAccessor6, ns);
                    }
                    if (xmlAnyElementAttribute2.Order != -1)
                    {
                        if (xmlAnyElementAttribute2.Order != num && num != -1)
{
                            throw new InvalidOperationException(System.SR.Format(System.SR.XmlSequenceMatch, "Order"));
                        }
                        num = xmlAnyElementAttribute2.Order;
                    }
                    nameTable.Add(elementAccessor6.Name, elementAccessor6.Namespace, elementAccessor6);
                    arrayList.Add(elementAccessor6);
                }
            }
        }
        accessor.Elements = (ElementAccessor[])arrayList.ToArray(typeof(ElementAccessor));
        accessor.SequenceId = num;
        if (rpc)
        {
            if (accessor.TypeDesc.IsArrayLike && accessor.Elements.Length != 0 && !(accessor.Elements[0].Mapping is ArrayMapping))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlRpcLitArrayElement, accessor.Elements[0].Name));
            }
            if (accessor.Xmlns != null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlRpcLitXmlns, accessor.Name));
            }
        }
        if (accessor.ChoiceIdentifier != null)
        {
            accessor.ChoiceIdentifier.MemberIds = new string[accessor.Elements.Length];
            for (int n = 0; n < accessor.Elements.Length; n++)
            {
                bool flag2 = false;
                ElementAccessor elementAccessor7 = accessor.Elements[n];
                EnumMapping enumMapping = (EnumMapping)accessor.ChoiceIdentifier.Mapping;
                for (int num2 = 0; num2 < enumMapping.Constants.Length; num2++)
                {
                    string xmlName = enumMapping.Constants[num2].XmlName;
                    if (elementAccessor7.Any && elementAccessor7.Name.Length == 0)
                    {
                        string text3 = ((elementAccessor7.AnyNamespaces == null) ? "##any" : elementAccessor7.AnyNamespaces);
                        if (xmlName.Substring(0, xmlName.Length - 1) == text3)
{
                            accessor.ChoiceIdentifier.MemberIds[n] = enumMapping.Constants[num2].Name;
                            flag2 = true;
                            break;
                        }
                        continue;
                    }
                    int num3 = xmlName.LastIndexOf(':');
                    string text4 = ((num3 < 0) ? enumMapping.Namespace : xmlName.Substring(0, num3));
                    string text5 = ((num3 < 0) ? xmlName : xmlName.Substring(num3 + 1));
                    if (elementAccessor7.Name == text5 && ((elementAccessor7.Form == XmlSchemaForm.Unqualified && string.IsNullOrEmpty(text4)) || elementAccessor7.Namespace == text4))
                    {
                        accessor.ChoiceIdentifier.MemberIds[n] = enumMapping.Constants[num2].Name;
                        flag2 = true;
                        break;
                    }
                }
                if (!flag2)
                {
                    if (elementAccessor7.Any && elementAccessor7.Name.Length == 0)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceMissingAnyValue, accessor.ChoiceIdentifier.Mapping.TypeDesc.FullName));
                    }
                    string text6 = ((elementAccessor7.Namespace != null && elementAccessor7.Namespace.Length > 0) ? (elementAccessor7.Namespace + ":" + elementAccessor7.Name) : elementAccessor7.Name);
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceMissingValue, accessor.ChoiceIdentifier.Mapping.TypeDesc.FullName, text6, elementAccessor7.Name, elementAccessor7.Namespace));
                }
            }
        }
        _arrayNestingLevel = arrayNestingLevel;
        _savedArrayItemAttributes = savedArrayItemAttributes;
        _savedArrayNamespace = savedArrayNamespace;
    }
References System.Xml.Serialization.XmlReflectionImporter._arrayNestingLevel, System.Xml.Serialization.XmlReflectionImporter._modelScope, System.Xml.Serialization.XmlReflectionImporter._savedArrayItemAttributes, System.Xml.Serialization.XmlReflectionImporter._savedArrayNamespace, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.XmlReflectionImporter._xsdAttributes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlReflectionImporter.AddUniqueAccessor(), System.Xml.Serialization.XmlReflectionImporter.CheckAmbiguousChoice(), System.Xml.Serialization.XmlReflectionImporter.CheckChoiceIdentifierMapping(), System.Xml.Serialization.XmlReflectionImporter.CheckForm(), System.Xml.Serialization.XmlReflectionImporter.CheckNullable(), System.Xml.Serialization.XmlReflectionImporter.CheckTopLevelAttributes(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.XmlReflectionImporter.CountAtLevel(), System.Xml.Serialization.XmlReflectionImporter.CreateArrayAttribute(), System.Xml.Serialization.XmlReflectionImporter.CreateArrayItemAttribute(), System.Xml.Serialization.XmlReflectionImporter.CreateElementAttribute(), System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.Serialization.Accessor.EscapeQName(), System.SR.Format(), System.FullName, System.Xml.Serialization.TypeScope.GetArrayElementType(), System.Xml.Serialization.ModelScope.GetArrayModel(), System.Xml.Serialization.TypeScope.GetArrayTypeDesc(), System.Xml.Serialization.XmlReflectionImporter.GetDefaultValue(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.ReconcileAccessor(), System.Xml.Serialization.XmlReflectionImporter.ReconcileLocalAccessor(), System.text, System.type, System.SR.XmlAnyElementDuplicate, System.SR.XmlChoiceMissingAnyValue, System.SR.XmlChoiceMissingValue, System.SR.XmlIllegalAnyElement, System.SR.XmlIllegalArrayArrayAttribute, System.SR.XmlIllegalArrayTextAttribute, System.SR.XmlIllegalAttribute, System.SR.XmlIllegalAttributesArrayAttribute, System.SR.XmlIllegalAttrOrText, System.SR.XmlIllegalAttrOrTextInterface, System.SR.XmlIllegalElementsArrayAttribute, System.SR.XmlIllegalType, System.SR.XmlInvalidNotNullable, System.SR.XmlRpcLitArrayElement, System.SR.XmlRpcLitXmlns, System.SR.XmlSequenceMatch, System.SR.XmlSoleXmlnsAttribute, and System.SR.XmlXmlnsInvalidType.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportFieldMapping(), and System.Xml.Serialization.XmlReflectionImporter.ImportMemberMapping().