Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping
ImportTypeMapping() [5/6]
TypeMapping System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping (TypeModel model, string ns, ImportContext context, string dataType, XmlAttributes a, bool repeats, bool openModel, RecursionLimiter limiter) inline private
Definition at line 378 of file XmlReflectionImporter.cs.
    {
        try
        {
            if (dataType.Length > 0)
            {
                TypeDesc typeDesc = (TypeScope.IsOptionalValue(model.Type) ? model.TypeDesc.BaseTypeDesc : model.TypeDesc);
                if (!typeDesc.IsPrimitive)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDataTypeUsage, dataType, "XmlElementAttribute.DataType"));
                }
                TypeDesc typeDesc2 = _typeScope.GetTypeDesc(dataType, "http://www.w3.org/2001/XMLSchema");
                if (typeDesc2 == null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidXsdDataType, dataType, "XmlElementAttribute.DataType", new XmlQualifiedName(dataType, "http://www.w3.org/2001/XMLSchema").ToString()));
                }
                if (typeDesc.FullName != typeDesc2.FullName)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlDataTypeMismatch, dataType, "XmlElementAttribute.DataType", typeDesc.FullName));
                }
            }
            if (a == null)
            {
                a = GetAttributes(model.Type, canBeSimpleType: false);
            }
            if (((uint)a.XmlFlags & 0xFFFFFF3Fu) != 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidTypeAttributes, model.Type.FullName));
            }
            switch (model.TypeDesc.Kind)
            {
            case TypeKind.Enum:
                return ImportEnumMapping((EnumModel)model, ns, repeats);
            case TypeKind.Primitive:
                if (a.XmlFlags != 0)
                {
                    throw InvalidAttributeUseException(model.Type);
                }
                return ImportPrimitiveMapping((PrimitiveModel)model, context, dataType, repeats);
            case TypeKind.Array:
            case TypeKind.Collection:
            case TypeKind.Enumerable:
            {
                if (context != ImportContext.Element)
                {
                    throw UnsupportedException(model.TypeDesc, context);
                }
                _arrayNestingLevel++;
                ArrayMapping result = ImportArrayLikeMapping((ArrayModel)model, ns, limiter);
                _arrayNestingLevel--;
                return result;
            }
            case TypeKind.Root:
            case TypeKind.Struct:
            case TypeKind.Class:
                if (context != ImportContext.Element)
                {
                    throw UnsupportedException(model.TypeDesc, context);
                }
                if (model.TypeDesc.IsOptionalValue)
                {
                    TypeDesc typeDesc3 = (string.IsNullOrEmpty(dataType) ? model.TypeDesc.BaseTypeDesc : _typeScope.GetTypeDesc(dataType, "http://www.w3.org/2001/XMLSchema"));
                    string typeName = ((typeDesc3.DataType == null) ? typeDesc3.Name : typeDesc3.DataType.Name);
                    TypeMapping typeMapping = GetTypeMapping(typeName, ns, typeDesc3, _types, null);
                    if (typeMapping == null)
                    {
                        typeMapping = ImportTypeMapping(_modelScope.GetTypeModel(model.TypeDesc.BaseTypeDesc.Type), ns, context, dataType, null, repeats, openModel, limiter);
                    }
                    return CreateNullableMapping(typeMapping, model.TypeDesc.Type);
                }
                return ImportStructLikeMapping((StructModel)model, ns, openModel, a, limiter);
            default:
                if (model.TypeDesc.Kind == TypeKind.Serializable)
                {
                    if (((uint)a.XmlFlags & 0xFFFFFFBFu) != 0)
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.XmlSerializableAttributes, model.TypeDesc.FullName, "XmlSchemaProviderAttribute"));
                    }
                }
                else if (a.XmlFlags != 0)
                {
                    throw InvalidAttributeUseException(model.Type);
                }
                if (model.TypeDesc.IsSpecial)
                {
                    return ImportSpecialMapping(model.Type, model.TypeDesc, ns, context, limiter);
                }
                throw UnsupportedException(model.TypeDesc, context);
            }
        }
        catch (Exception ex)
        {
            if (ex is OutOfMemoryException)
            {
                throw;
            }
            throw CreateTypeReflectionException(model.TypeDesc.FullName, ex);
        }
    }
References System.Xml.Serialization.XmlReflectionImporter._arrayNestingLevel, System.Xml.Serialization.XmlReflectionImporter._modelScope, System.Xml.Serialization.XmlReflectionImporter._types, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.XmlReflectionImporter.CreateNullableMapping(), System.Xml.Serialization.XmlReflectionImporter.CreateTypeReflectionException(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.XmlReflectionImporter.GetAttributes(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.XmlReflectionImporter.GetTypeMapping(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportEnumMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportPrimitiveMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportSpecialMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.InvalidAttributeUseException(), System.Xml.Serialization.TypeScope.IsOptionalValue(), System.ToString, System.Xml.Serialization.XmlReflectionImporter.UnsupportedException(), System.SR.XmlDataTypeMismatch, System.SR.XmlInvalidDataTypeUsage, System.SR.XmlInvalidTypeAttributes, System.SR.XmlInvalidXsdDataType, and System.SR.XmlSerializableAttributes.