Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportSpecialMapping
ImportSpecialMapping()
SpecialMapping System.Xml.Serialization.XmlReflectionImporter.ImportSpecialMapping (Type type, TypeDesc typeDesc, string ns, ImportContext context, RecursionLimiter limiter) inline private
Definition at line 505 of file XmlReflectionImporter.cs.
    {
        if (_specials == null)
        {
            _specials = new Hashtable();
        }
        SpecialMapping specialMapping = (SpecialMapping)_specials[type];
        if (specialMapping != null)
        {
            CheckContext(specialMapping.TypeDesc, context);
            return specialMapping;
        }
        if (typeDesc.Kind == TypeKind.Serializable)
        {
            SerializableMapping serializableMapping = null;
            object[] customAttributes = type.GetCustomAttributes(typeof(XmlSchemaProviderAttribute), inherit: false);
            if (customAttributes.Length != 0)
            {
                XmlSchemaProviderAttribute xmlSchemaProviderAttribute = (XmlSchemaProviderAttribute)customAttributes[0];
                MethodInfo methodFromSchemaProvider = GetMethodFromSchemaProvider(xmlSchemaProviderAttribute, type);
                serializableMapping = new SerializableMapping(methodFromSchemaProvider, xmlSchemaProviderAttribute.IsAny, ns);
                XmlQualifiedName xsiType = serializableMapping.XsiType;
                if (xsiType != null && !xsiType.IsEmpty)
                {
                    if (_serializables == null)
                    {
                        _serializables = new NameTable();
                    }
                    SerializableMapping serializableMapping2 = (SerializableMapping)_serializables[xsiType];
                    if (serializableMapping2 != null)
                    {
                        if (serializableMapping2.Type == null)
{
                            serializableMapping = serializableMapping2;
                        }
                        else if (serializableMapping2.Type != type)
{
                            SerializableMapping next = serializableMapping2.Next;
                            serializableMapping2.Next = serializableMapping;
                            serializableMapping.Next = next;
                        }
                    }
                    else
                    {
                        XmlSchemaType xsdType = serializableMapping.XsdType;
                        if (xsdType != null)
{
                            SetBase(serializableMapping, xsdType.DerivedFrom);
                        }
                        _serializables[xsiType] = serializableMapping;
                    }
                    serializableMapping.TypeName = xsiType.Name;
                    serializableMapping.Namespace = xsiType.Namespace;
                }
                serializableMapping.TypeDesc = typeDesc;
                serializableMapping.Type = type;
                IncludeTypes(type);
            }
            else
            {
                serializableMapping = new SerializableMapping();
                serializableMapping.TypeDesc = typeDesc;
                serializableMapping.Type = type;
            }
            specialMapping = serializableMapping;
        }
        else
        {
            specialMapping = new SpecialMapping();
            specialMapping.TypeDesc = typeDesc;
        }
        CheckContext(typeDesc, context);
        _specials.Add(type, specialMapping);
        _typeScope.AddTypeMapping(specialMapping);
        return specialMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._serializables, System.Xml.Serialization.XmlReflectionImporter._specials, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Collections.Hashtable.Add(), System.Xml.Serialization.TypeScope.AddTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.CheckContext(), System.Xml.Dictionary, System.Xml.Serialization.XmlReflectionImporter.GetMethodFromSchemaProvider(), System.Xml.Serialization.XmlReflectionImporter.IncludeTypes(), System.Xml.Serialization.XmlReflectionImporter.SetBase(), and System.type.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping().