Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportPrimitiveMapping
ImportPrimitiveMapping()
PrimitiveMapping System.Xml.Serialization.XmlReflectionImporter.ImportPrimitiveMapping (PrimitiveModel model, ImportContext context, string dataType, bool repeats) inline private
Definition at line 1164 of file XmlReflectionImporter.cs.
    {
        PrimitiveMapping primitiveMapping = new PrimitiveMapping();
        if (dataType.Length > 0)
        {
            primitiveMapping.TypeDesc = _typeScope.GetTypeDesc(dataType, "http://www.w3.org/2001/XMLSchema");
            if (primitiveMapping.TypeDesc == null)
            {
                primitiveMapping.TypeDesc = _typeScope.GetTypeDesc(dataType, "http://microsoft.com/wsdl/types/");
                if (primitiveMapping.TypeDesc == null)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlUdeclaredXsdType, dataType));
                }
            }
        }
        else
        {
            primitiveMapping.TypeDesc = model.TypeDesc;
        }
        primitiveMapping.TypeName = primitiveMapping.TypeDesc.DataType.Name;
        primitiveMapping.Namespace = (primitiveMapping.TypeDesc.IsXsdType ? "http://www.w3.org/2001/XMLSchema" : "http://microsoft.com/wsdl/types/");
        primitiveMapping.IsList = repeats;
        CheckContext(primitiveMapping.TypeDesc, context);
        return primitiveMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.XmlReflectionImporter.CheckContext(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.TypeScope.GetTypeDesc(), and System.SR.XmlUdeclaredXsdType.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping().