Terraria: System.Xml.Serialization.XmlReflectionImporter.ReconcileAccessor
ReconcileAccessor()
Accessor System.Xml.Serialization.XmlReflectionImporter.ReconcileAccessor (Accessor accessor, NameTable accessors) inline private
Definition at line 294 of file XmlReflectionImporter.cs.
    {
        if (accessor.Any && accessor.Name.Length == 0)
        {
            return accessor;
        }
        Accessor accessor2 = (Accessor)accessors[accessor.Name, accessor.Namespace];
        if (accessor2 == null)
        {
            accessor.IsTopLevelInSchema = true;
            accessors.Add(accessor.Name, accessor.Namespace, accessor);
            return accessor;
        }
        if (accessor2.Mapping == accessor.Mapping)
        {
            return accessor2;
        }
        if (!(accessor.Mapping is MembersMapping) && !(accessor2.Mapping is MembersMapping) && (accessor.Mapping.TypeDesc == accessor2.Mapping.TypeDesc || (accessor2.Mapping is NullableMapping && accessor.Mapping.TypeDesc == ((NullableMapping)accessor2.Mapping).BaseMapping.TypeDesc) || (accessor.Mapping is NullableMapping && ((NullableMapping)accessor.Mapping).BaseMapping.TypeDesc == accessor2.Mapping.TypeDesc)))
        {
            string text = Convert.ToString(accessor.Default, CultureInfo.InvariantCulture);
            string text2 = Convert.ToString(accessor2.Default, CultureInfo.InvariantCulture);
            if (text == text2)
            {
                return accessor2;
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlCannotReconcileAccessorDefault, accessor.Name, accessor.Namespace, text, text2));
        }
        if (accessor.Mapping is MembersMapping || accessor2.Mapping is MembersMapping)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlMethodTypeNameConflict, accessor.Name, accessor.Namespace));
        }
        if (accessor.Mapping is ArrayMapping)
        {
            if (!(accessor2.Mapping is ArrayMapping))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlCannotReconcileAccessor, accessor.Name, accessor.Namespace, GetMappingName(accessor2.Mapping), GetMappingName(accessor.Mapping)));
            }
            ArrayMapping arrayMapping = (ArrayMapping)accessor.Mapping;
            ArrayMapping arrayMapping2 = (arrayMapping.IsAnonymousType ? null : ((ArrayMapping)_types[accessor2.Mapping.TypeName, accessor2.Mapping.Namespace]));
            ArrayMapping next = arrayMapping2;
            while (arrayMapping2 != null)
            {
                if (arrayMapping2 == accessor.Mapping)
                {
                    return accessor2;
                }
                arrayMapping2 = arrayMapping2.Next;
            }
            arrayMapping.Next = next;
            if (!arrayMapping.IsAnonymousType)
            {
                _types[accessor2.Mapping.TypeName, accessor2.Mapping.Namespace] = arrayMapping;
            }
            return accessor2;
        }
        if (accessor is AttributeAccessor)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlCannotReconcileAttributeAccessor, accessor.Name, accessor.Namespace, GetMappingName(accessor2.Mapping), GetMappingName(accessor.Mapping)));
        }
        throw new InvalidOperationException(System.SR.Format(System.SR.XmlCannotReconcileAccessor, accessor.Name, accessor.Namespace, GetMappingName(accessor2.Mapping), GetMappingName(accessor.Mapping)));
    }
References System.Xml.Serialization.XmlReflectionImporter._types, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.NullableMapping.BaseMapping, System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.XmlReflectionImporter.GetMappingName(), System.Globalization.CultureInfo.InvariantCulture, System.text, System.Convert.ToString(), System.Xml.Serialization.TypeMapping.TypeDesc, System.SR.XmlCannotReconcileAccessor, System.SR.XmlCannotReconcileAccessorDefault, System.SR.XmlCannotReconcileAttributeAccessor, and System.SR.XmlMethodTypeNameConflict.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportElement(), System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping(), and System.Xml.Serialization.XmlReflectionImporter.ReconcileLocalAccessor().