Terraria: System.Xml.Serialization.XmlReflectionImporter.GetDefaultValue
GetDefaultValue()
object System.Xml.Serialization.XmlReflectionImporter.GetDefaultValue (TypeDesc fieldTypeDesc, Type t, XmlAttributes a) inline private
Definition at line 2155 of file XmlReflectionImporter.cs.
    {
        if (a.XmlDefaultValue == null || a.XmlDefaultValue == DBNull.Value)
        {
            return null;
        }
        if (fieldTypeDesc.Kind != TypeKind.Primitive && fieldTypeDesc.Kind != TypeKind.Enum)
        {
            a.XmlDefaultValue = null;
            return a.XmlDefaultValue;
        }
        if (fieldTypeDesc.Kind == TypeKind.Enum)
        {
            string text = Enum.Format(t, a.XmlDefaultValue, "G").Replace(",", " ");
            string text2 = Enum.Format(t, a.XmlDefaultValue, "D");
            if (text == text2)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidDefaultValue, text, a.XmlDefaultValue.GetType().FullName));
            }
            return text;
        }
        return a.XmlDefaultValue;
    }
References System.Xml.Dictionary, System.SR.Format(), System.Enum.Format(), System.text, System.DBNull.Value, and System.SR.XmlInvalidDefaultValue.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping().