Terraria: System.Xml.Serialization.XmlReflectionImporter.GetRootMapping
GetRootMapping()
StructMapping System.Xml.Serialization.XmlReflectionImporter.GetRootMapping () inline private
Definition at line 684 of file XmlReflectionImporter.cs.
    {
        if (_root == null)
        {
            _root = CreateRootMapping();
            _typeScope.AddTypeMapping(_root);
        }
        return _root;
    }
References System.Xml.Serialization.XmlReflectionImporter._root, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.TypeScope.AddTypeMapping(), and System.Xml.Serialization.XmlReflectionImporter.CreateRootMapping().
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(), and System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers().