Terraria: System.Xml.Serialization.XmlReflectionImporter.CheckChoiceIdentifierType
CheckChoiceIdentifierType()
Type System.Xml.Serialization.XmlReflectionImporter.CheckChoiceIdentifierType (Type type, bool isArrayLike, string identifierName, string memberName) inline private
Definition at line 1448 of file XmlReflectionImporter.cs.
    {
        if (type.IsArray)
        {
            if (!isArrayLike)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceIdentifierType, identifierName, memberName, type.GetElementType().FullName));
            }
            type = type.GetElementType();
        }
        else if (isArrayLike)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceIdentifierArrayType, identifierName, memberName, type.FullName));
        }
        if (!type.IsEnum)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceIdentifierTypeEnum, identifierName));
        }
        return type;
    }
References System.SR.Format(), System.type, System.SR.XmlChoiceIdentifierArrayType, System.SR.XmlChoiceIdentifierType, and System.SR.XmlChoiceIdentifierTypeEnum.
Referenced by System.Xml.Serialization.XmlReflectionImporter.GetChoiceIdentifierType(), and System.Xml.Serialization.XmlReflectionImporter.GetChoiceIdentifierType().