Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportMemberMapping
ImportMemberMapping()
MemberMapping System.Xml.Serialization.XmlReflectionImporter.ImportMemberMapping (XmlReflectionMember xmlReflectionMember, string ns, XmlReflectionMember[] xmlReflectionMembers, bool rpc, bool openModel, RecursionLimiter limiter) inline private
Definition at line 1338 of file XmlReflectionImporter.cs.
    {
        XmlSchemaForm form = ((!rpc) ? XmlSchemaForm.Qualified : XmlSchemaForm.Unqualified);
        XmlAttributes xmlAttributes = xmlReflectionMember.XmlAttributes;
        TypeDesc typeDesc = _typeScope.GetTypeDesc(xmlReflectionMember.MemberType);
        if (xmlAttributes.XmlFlags == (XmlAttributeFlags)0)
        {
            if (typeDesc.IsArrayLike)
            {
                XmlArrayAttribute xmlArrayAttribute = CreateArrayAttribute(typeDesc);
                xmlArrayAttribute.ElementName = xmlReflectionMember.MemberName;
                xmlArrayAttribute.Namespace = (rpc ? null : ns);
                xmlArrayAttribute.Form = form;
                xmlAttributes.XmlArray = xmlArrayAttribute;
            }
            else
            {
                XmlElementAttribute xmlElementAttribute = CreateElementAttribute(typeDesc);
                if (typeDesc.IsStructLike)
                {
                    XmlAttributes xmlAttributes2 = new XmlAttributes(xmlReflectionMember.MemberType);
                    if (xmlAttributes2.XmlRoot != null)
                    {
                        if (xmlAttributes2.XmlRoot.ElementName.Length > 0)
{
                            xmlElementAttribute.ElementName = xmlAttributes2.XmlRoot.ElementName;
                        }
                        if (rpc)
{
                            xmlElementAttribute.Namespace = null;
                            if (xmlAttributes2.XmlRoot.GetIsNullableSpecified())
{
                                xmlElementAttribute.IsNullable = xmlAttributes2.XmlRoot.IsNullable;
                            }
                        }
                        else
{
                            xmlElementAttribute.Namespace = xmlAttributes2.XmlRoot.Namespace;
                            xmlElementAttribute.IsNullable = xmlAttributes2.XmlRoot.IsNullable;
                        }
                    }
                }
                if (xmlElementAttribute.ElementName.Length == 0)
                {
                    xmlElementAttribute.ElementName = xmlReflectionMember.MemberName;
                }
                if (xmlElementAttribute.Namespace == null && !rpc)
                {
                    xmlElementAttribute.Namespace = ns;
                }
                xmlElementAttribute.Form = form;
                xmlAttributes.XmlElements.Add(xmlElementAttribute);
            }
        }
        else if (xmlAttributes.XmlRoot != null)
        {
            CheckNullable(xmlAttributes.XmlRoot.IsNullable, typeDesc, null);
        }
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.Name = xmlReflectionMember.MemberName;
        bool checkSpecified = FindSpecifiedMember(xmlReflectionMember.MemberName, xmlReflectionMembers) != null;
        FieldModel fieldModel = new FieldModel(xmlReflectionMember.MemberName, xmlReflectionMember.MemberType, _typeScope.GetTypeDesc(xmlReflectionMember.MemberType), checkSpecified, checkShouldPersist: false);
        memberMapping.CheckShouldPersist = fieldModel.CheckShouldPersist;
        memberMapping.CheckSpecified = fieldModel.CheckSpecified;
        memberMapping.ReadOnly = fieldModel.ReadOnly;
        Type choiceIdentifierType = null;
        if (xmlAttributes.XmlChoiceIdentifier != null)
        {
            choiceIdentifierType = GetChoiceIdentifierType(xmlAttributes.XmlChoiceIdentifier, xmlReflectionMembers, typeDesc.IsArrayLike, fieldModel.Name);
        }
        ImportAccessorMapping(memberMapping, fieldModel, xmlAttributes, ns, choiceIdentifierType, rpc, openModel, limiter);
        if (xmlReflectionMember.OverrideIsNullable && memberMapping.Elements.Length != 0)
        {
            memberMapping.Elements[0].IsNullable = false;
        }
        return memberMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlReflectionImporter.CheckNullable(), System.Xml.Serialization.XmlReflectionImporter.CreateArrayAttribute(), System.Xml.Serialization.XmlReflectionImporter.CreateElementAttribute(), System.Xml.Dictionary, System.Xml.Serialization.XmlReflectionImporter.FindSpecifiedMember(), System.Xml.Serialization.XmlReflectionImporter.GetChoiceIdentifierType(), System.Xml.Serialization.TypeScope.GetTypeDesc(), and System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping().
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping().