Terraria: System.Xml.Serialization.XmlReflectionImporter.CreateNullableMapping
CreateNullableMapping()
NullableMapping System.Xml.Serialization.XmlReflectionImporter.CreateNullableMapping (TypeMapping baseMapping, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type) inline private
Definition at line 643 of file XmlReflectionImporter.cs.
    {
        TypeDesc nullableTypeDesc = baseMapping.TypeDesc.GetNullableTypeDesc(type);
        TypeMapping typeMapping = (baseMapping.IsAnonymousType ? ((TypeMapping)_anonymous[type]) : ((TypeMapping)_nullables[baseMapping.TypeName, baseMapping.Namespace]));
        NullableMapping nullableMapping;
        if (typeMapping != null)
        {
            if (typeMapping is NullableMapping)
            {
                nullableMapping = (NullableMapping)typeMapping;
                if (nullableMapping.BaseMapping is PrimitiveMapping && baseMapping is PrimitiveMapping)
                {
                    return nullableMapping;
                }
                if (nullableMapping.BaseMapping == baseMapping)
                {
                    return nullableMapping;
                }
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlTypesDuplicate, nullableTypeDesc.FullName, typeMapping.TypeDesc.FullName, nullableTypeDesc.Name, typeMapping.Namespace));
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlTypesDuplicate, nullableTypeDesc.FullName, typeMapping.TypeDesc.FullName, nullableTypeDesc.Name, typeMapping.Namespace));
        }
        nullableMapping = new NullableMapping();
        nullableMapping.BaseMapping = baseMapping;
        nullableMapping.TypeDesc = nullableTypeDesc;
        nullableMapping.TypeName = baseMapping.TypeName;
        nullableMapping.Namespace = baseMapping.Namespace;
        nullableMapping.IncludeInSchema = baseMapping.IncludeInSchema;
        if (!baseMapping.IsAnonymousType)
        {
            _nullables.Add(baseMapping.TypeName, baseMapping.Namespace, nullableMapping);
        }
        else
        {
            _anonymous[type] = nullableMapping;
        }
        _typeScope.AddTypeMapping(nullableMapping);
        return nullableMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._anonymous, System.Xml.Serialization.XmlReflectionImporter._nullables, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.NameTable.Add(), System.Xml.Serialization.TypeScope.AddTypeMapping(), System.Xml.Dictionary, System.SR.Format(), System.type, and System.SR.XmlTypesDuplicate.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping().