Terraria: System.Xml.Serialization.XmlReflectionImporter.GetAttributes
GetAttributes() [2/2]
XmlAttributes System.Xml.Serialization.XmlReflectionImporter.GetAttributes (Type type, bool canBeSimpleType) inline private
Definition at line 206 of file XmlReflectionImporter.cs.
    {
        XmlAttributes xmlAttributes = _attributeOverrides[type];
        if (xmlAttributes != null)
        {
            return xmlAttributes;
        }
        if (canBeSimpleType && TypeScope.IsKnownType(type))
        {
            return _defaultAttributes;
        }
        return new XmlAttributes(type);
    }
References System.Xml.Serialization.XmlReflectionImporter._attributeOverrides, System.Xml.Serialization.XmlReflectionImporter._defaultAttributes, System.Xml.Dictionary, System.Xml.Serialization.TypeScope.IsKnownType(), and System.type.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportConstantMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportElement(), System.Xml.Serialization.XmlReflectionImporter.ImportEnumMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(), System.Xml.Serialization.XmlReflectionImporter.SetArrayMappingType(), and System.Xml.Serialization.XmlReflectionImporter.XsdTypeName().