Terraria: System.Xml.Serialization.XmlReflectionImporter.GetTopLevelMapping
GetTopLevelMapping()
static XmlTypeMapping System.Xml.Serialization.XmlReflectionImporter.GetTopLevelMapping (Type type, string defaultNamespace) inline static package
Definition at line 2266 of file XmlReflectionImporter.cs.
    {
        defaultNamespace = defaultNamespace ?? string.Empty;
        XmlAttributes xmlAttributes = new XmlAttributes(type);
        TypeDesc typeDesc = new TypeScope().GetTypeDesc(type);
        ElementAccessor elementAccessor = new ElementAccessor();
        if (typeDesc.Kind == TypeKind.Node)
        {
            elementAccessor.Any = true;
        }
        else
        {
            string @namespace = ((xmlAttributes.XmlRoot == null) ? defaultNamespace : xmlAttributes.XmlRoot.Namespace);
            string text = string.Empty;
            if (xmlAttributes.XmlType != null)
            {
                text = xmlAttributes.XmlType.TypeName;
            }
            if (text.Length == 0)
            {
                text = type.Name;
            }
            elementAccessor.Name = XmlConvert.EncodeLocalName(text);
            elementAccessor.Namespace = @namespace;
        }
        XmlTypeMapping xmlTypeMapping = new XmlTypeMapping(null, elementAccessor);
        xmlTypeMapping.SetKeyInternal(XmlMapping.GenerateKey(type, xmlAttributes.XmlRoot, defaultNamespace));
        return xmlTypeMapping;
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.EncodeLocalName(), System.Xml.Serialization.XmlMapping.GenerateKey(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.text, and System.type.
Referenced by System.Xml.Serialization.XmlSerializer.XmlSerializer().