Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping
ImportMembersMapping() [5/5]
MembersMapping System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping (XmlReflectionMember[] xmlReflectionMembers, string ns, bool hasWrapperElement, bool rpc, bool openModel, RecursionLimiter limiter) inline private
Definition at line 1265 of file XmlReflectionImporter.cs.
    {
        MembersMapping membersMapping = new MembersMapping();
        membersMapping.TypeDesc = _typeScope.GetTypeDesc(typeof(object[]));
        MemberMapping[] array = new MemberMapping[xmlReflectionMembers.Length];
        NameTable elements = new NameTable();
        NameTable attributes = new NameTable();
        TextAccessor textAccessor = null;
        bool flag = false;
        for (int i = 0; i < array.Length; i++)
        {
            try
            {
                MemberMapping memberMapping = ImportMemberMapping(xmlReflectionMembers[i], ns, xmlReflectionMembers, rpc, openModel, limiter);
                if (!hasWrapperElement && memberMapping.Attribute != null)
                {
                    if (rpc)
                    {
                        throw new InvalidOperationException(System.SR.XmlRpcLitAttributeAttributes);
                    }
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidAttributeType, "XmlAttribute"));
                }
                if (rpc && xmlReflectionMembers[i].IsReturnValue)
                {
                    if (i > 0)
                    {
                        throw new InvalidOperationException(System.SR.XmlInvalidReturnPosition);
                    }
                    memberMapping.IsReturnValue = true;
                }
                array[i] = memberMapping;
                flag |= memberMapping.IsSequence;
                if (!xmlReflectionMembers[i].XmlAttributes.XmlIgnore)
                {
                    AddUniqueAccessor(memberMapping, elements, attributes, flag);
                }
                array[i] = memberMapping;
                if (memberMapping.Text != null)
                {
                    if (textAccessor != null)
                    {
                        throw new InvalidOperationException(System.SR.XmlIllegalMultipleTextMembers);
                    }
                    textAccessor = memberMapping.Text;
                }
                if (memberMapping.Xmlns != null)
                {
                    if (membersMapping.XmlnsMember != null)
                    {
                        throw new InvalidOperationException(System.SR.XmlMultipleXmlnsMembers);
                    }
                    membersMapping.XmlnsMember = memberMapping;
                }
            }
            catch (Exception ex)
            {
                if (ex is OutOfMemoryException)
                {
                    throw;
                }
                throw CreateReflectionException(xmlReflectionMembers[i].MemberName, ex);
            }
        }
        if (flag)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlSequenceMembers, "Order"));
        }
        membersMapping.Members = array;
        membersMapping.HasWrapperElement = hasWrapperElement;
        return membersMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.XmlReflectionImporter.AddUniqueAccessor(), System.array, System.Xml.Serialization.XmlReflectionImporter.CreateReflectionException(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.XmlReflectionImporter.ImportMemberMapping(), System.Xml.Serialization.XmlAttributes.XmlIgnore, System.SR.XmlIllegalMultipleTextMembers, System.SR.XmlInvalidAttributeType, System.SR.XmlInvalidReturnPosition, System.SR.XmlMultipleXmlnsMembers, System.SR.XmlRpcLitAttributeAttributes, and System.SR.XmlSequenceMembers.