Terraria: System.Xml.Serialization.XmlReflectionImporter.CheckAmbiguousChoice
CheckAmbiguousChoice()
void System.Xml.Serialization.XmlReflectionImporter.CheckAmbiguousChoice (XmlAttributes a, Type accessorType, string accessorName) inline private
Definition at line 2099 of file XmlReflectionImporter.cs.
    {
        Hashtable hashtable = new Hashtable();
        XmlElementAttributes xmlElements = a.XmlElements;
        if (xmlElements != null && xmlElements.Count >= 2 && a.XmlChoiceIdentifier == null)
        {
            for (int i = 0; i < xmlElements.Count; i++)
            {
                Type key = ((xmlElements[i].Type == null) ? accessorType : xmlElements[i].Type);
                if (hashtable.Contains(key))
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceIdentiferMissing, "XmlChoiceIdentifierAttribute", accessorName));
                }
                hashtable.Add(key, false);
            }
        }
        if (hashtable.Contains(typeof(XmlElement)) && a.XmlAnyElements.Count > 0)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlChoiceIdentiferMissing, "XmlChoiceIdentifierAttribute", accessorName));
        }
        XmlArrayItemAttributes xmlArrayItems = a.XmlArrayItems;
        if (xmlArrayItems == null || xmlArrayItems.Count < 2)
        {
            return;
        }
        NameTable nameTable = new NameTable();
        for (int j = 0; j < xmlArrayItems.Count; j++)
        {
            Type type = ((xmlArrayItems[j].Type == null) ? accessorType : xmlArrayItems[j].Type);
            string ns = xmlArrayItems[j].NestingLevel.ToString(CultureInfo.InvariantCulture);
            XmlArrayItemAttribute xmlArrayItemAttribute = (XmlArrayItemAttribute)nameTable[type.FullName, ns];
            if (xmlArrayItemAttribute != null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlArrayItemAmbiguousTypes, accessorName, xmlArrayItemAttribute.ElementName, xmlArrayItems[j].ElementName, "XmlElementAttribute", "XmlChoiceIdentifierAttribute", accessorName));
            }
            nameTable[type.FullName, ns] = xmlArrayItems[j];
        }
    }
References System.Collections.Hashtable.Add(), System.Collections.Hashtable.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.key, System.type, System.SR.XmlArrayItemAmbiguousTypes, and System.SR.XmlChoiceIdentiferMissing.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping().