Terraria: System.Xml.Serialization.XmlReflectionImporter.IncludeType
IncludeType() [2/2]
void System.Xml.Serialization.XmlReflectionImporter.IncludeType (Type type, RecursionLimiter limiter) inline private
Definition at line 108 of file XmlReflectionImporter.cs.
    {
        int arrayNestingLevel = _arrayNestingLevel;
        XmlArrayItemAttributes savedArrayItemAttributes = _savedArrayItemAttributes;
        string savedArrayNamespace = _savedArrayNamespace;
        _arrayNestingLevel = 0;
        _savedArrayItemAttributes = null;
        _savedArrayNamespace = null;
        TypeMapping typeMapping = ImportTypeMapping(_modelScope.GetTypeModel(type), _defaultNs, ImportContext.Element, string.Empty, null, limiter);
        if (typeMapping.IsAnonymousType && !typeMapping.TypeDesc.IsSpecial)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlAnonymousInclude, type.FullName));
        }
        _arrayNestingLevel = arrayNestingLevel;
        _savedArrayItemAttributes = savedArrayItemAttributes;
        _savedArrayNamespace = savedArrayNamespace;
    }
References System.Xml.Serialization.XmlReflectionImporter._arrayNestingLevel, System.Xml.Serialization.XmlReflectionImporter._defaultNs, System.Xml.Serialization.XmlReflectionImporter._modelScope, System.Xml.Serialization.XmlReflectionImporter._savedArrayItemAttributes, System.Xml.Serialization.XmlReflectionImporter._savedArrayNamespace, System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.ModelScope.GetTypeModel(), System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(), System.type, and System.SR.XmlAnonymousInclude.