Terraria: System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping
ImportArrayLikeMapping()
ArrayMapping System.Xml.Serialization.XmlReflectionImporter.ImportArrayLikeMapping (ArrayModel model, string ns, RecursionLimiter limiter) inline private
Definition at line 1082 of file XmlReflectionImporter.cs.
    {
        ArrayMapping arrayMapping = new ArrayMapping();
        arrayMapping.TypeDesc = model.TypeDesc;
        if (_savedArrayItemAttributes == null)
        {
            _savedArrayItemAttributes = new XmlArrayItemAttributes();
        }
        if (CountAtLevel(_savedArrayItemAttributes, _arrayNestingLevel) == 0)
        {
            _savedArrayItemAttributes.Add(CreateArrayItemAttribute(_typeScope.GetTypeDesc(model.Element.Type), _arrayNestingLevel));
        }
        CreateArrayElementsFromAttributes(arrayMapping, _savedArrayItemAttributes, model.Element.Type, (_savedArrayNamespace == null) ? ns : _savedArrayNamespace, limiter);
        SetArrayMappingType(arrayMapping, ns, model.Type);
        for (int i = 0; i < arrayMapping.Elements.Length; i++)
        {
            arrayMapping.Elements[i] = ReconcileLocalAccessor(arrayMapping.Elements[i], arrayMapping.Namespace);
        }
        IncludeTypes(model.Type);
        ArrayMapping arrayMapping2 = (ArrayMapping)_types[arrayMapping.TypeName, arrayMapping.Namespace];
        if (arrayMapping2 != null)
        {
            ArrayMapping next = arrayMapping2;
            while (arrayMapping2 != null)
            {
                if (arrayMapping2.TypeDesc == model.TypeDesc)
                {
                    return arrayMapping2;
                }
                arrayMapping2 = arrayMapping2.Next;
            }
            arrayMapping.Next = next;
            if (!arrayMapping.IsAnonymousType)
            {
                _types[arrayMapping.TypeName, arrayMapping.Namespace] = arrayMapping;
            }
            else
            {
                _anonymous[model.Type] = arrayMapping;
            }
            return arrayMapping;
        }
        _typeScope.AddTypeMapping(arrayMapping);
        if (!arrayMapping.IsAnonymousType)
        {
            _types.Add(arrayMapping.TypeName, arrayMapping.Namespace, arrayMapping);
        }
        else
        {
            _anonymous[model.Type] = arrayMapping;
        }
        return arrayMapping;
    }
References System.Xml.Serialization.XmlReflectionImporter._anonymous, System.Xml.Serialization.XmlReflectionImporter._arrayNestingLevel, System.Xml.Serialization.XmlReflectionImporter._savedArrayItemAttributes, System.Xml.Serialization.XmlReflectionImporter._savedArrayNamespace, System.Xml.Serialization.XmlReflectionImporter._types, System.Xml.Serialization.XmlReflectionImporter._typeScope, System.Xml.Serialization.XmlArrayItemAttributes.Add(), System.Xml.Serialization.NameTable.Add(), System.Xml.Serialization.TypeScope.AddTypeMapping(), System.Xml.Serialization.XmlReflectionImporter.CountAtLevel(), System.Xml.Serialization.XmlReflectionImporter.CreateArrayElementsFromAttributes(), System.Xml.Serialization.XmlReflectionImporter.CreateArrayItemAttribute(), System.Xml.Dictionary, System.Xml.Serialization.TypeScope.GetTypeDesc(), System.Xml.Serialization.XmlReflectionImporter.IncludeTypes(), System.Xml.Serialization.XmlReflectionImporter.ReconcileLocalAccessor(), and System.Xml.Serialization.XmlReflectionImporter.SetArrayMappingType().
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(), and System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping().