Terraria: System.Xml.Serialization.XmlReflectionImporter.SetBase
SetBase()
void System.Xml.Serialization.XmlReflectionImporter.SetBase (SerializableMapping mapping, XmlQualifiedName baseQname) inline package
Definition at line 582 of file XmlReflectionImporter.cs.
    {
        if (!baseQname.IsEmpty && !(baseQname.Namespace == "http://www.w3.org/2001/XMLSchema"))
        {
            XmlSchemaSet schemas = mapping.Schemas;
            ArrayList arrayList = (ArrayList)schemas.Schemas(baseQname.Namespace);
            if (arrayList.Count == 0)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlMissingSchema, baseQname.Namespace));
            }
            if (arrayList.Count > 1)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlGetSchemaInclude, baseQname.Namespace, "IXmlSerializable", "GetSchema"));
            }
            XmlSchema xmlSchema = (XmlSchema)arrayList[0];
            XmlSchemaType xmlSchemaType = (XmlSchemaType)xmlSchema.SchemaTypes[baseQname];
            xmlSchemaType = ((xmlSchemaType.Redefined != null) ? xmlSchemaType.Redefined : xmlSchemaType);
            if (_serializables[baseQname] == null)
            {
                SerializableMapping serializableMapping = new SerializableMapping(baseQname, schemas);
                SetBase(serializableMapping, xmlSchemaType.DerivedFrom);
                _serializables.Add(baseQname, serializableMapping);
            }
            mapping.SetBaseMapping((SerializableMapping)_serializables[baseQname]);
        }
    }
References System.Xml.Serialization.XmlReflectionImporter._serializables, System.Xml.Serialization.NameTable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.SR.Format(), System.Xml.Schema.XmlSchemaSet.Schemas(), System.Xml.Serialization.XmlReflectionImporter.SetBase(), System.SR.XmlGetSchemaInclude, and System.SR.XmlMissingSchema.
Referenced by System.Xml.Serialization.XmlReflectionImporter.ImportSpecialMapping(), and System.Xml.Serialization.XmlReflectionImporter.SetBase().