Terraria: System.IO.TextReader.ReadToEndAsync
ReadToEndAsync()
virtual async Task< string > System.IO.TextReader.ReadToEndAsync () inline virtual inherited
Reimplemented in System.IO.SyncTextReader, System.IO.StreamReader, System.IO.StringReader, and System.IO.TextReader.SyncTextReader.
Definition at line 286 of file TextReader.cs.
    {
        StringBuilder sb = new StringBuilder(4096);
        char[] chars = ArrayPool<char>.Shared.Rent(4096);
        try
        {
            int charCount;
            while ((charCount = await ReadAsyncInternal(chars, default(CancellationToken)).ConfigureAwait(continueOnCapturedContext: false)) != 0)
            {
                sb.Append(chars, 0, charCount);
            }
        }
        finally
        {
            ArrayPool<char>.Shared.Return(chars);
        }
        return sb.ToString();
    }
References System.Text.StringBuilder.Append(), System.charCount, System.chars, System.IO.TextReader.ReadAsyncInternal(), System.Buffers.ArrayPool< T >.Shared, and System.Text.StringBuilder.ToString().