Terraria: System.IO.TextReader.ReadBlockAsyncInternal
ReadBlockAsyncInternal()
async ValueTask< int > System.IO.TextReader.ReadBlockAsyncInternal (Memory< char > buffer, CancellationToken cancellationToken) inline package inherited
Definition at line 368 of file TextReader.cs.
    {
        int i = 0;
        int num;
        do
        {
            num = await ReadAsyncInternal(buffer.Slice(i), cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            i += num;
        }
        while (num > 0 && i < buffer.Length);
        return i;
    }
References System.buffer, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), and System.IO.TextReader.ReadAsyncInternal().
Referenced by System.IO.TextReader.ReadBlockAsync(), and System.IO.StreamReader.ReadBlockAsync().