Terraria: System.IO.TextReader.ReadBlockAsync
ReadBlockAsync() [1/2]
virtual Task< int > System.IO.TextReader.ReadBlockAsync (char[] buffer, int index, int count) inline virtual inherited
Reimplemented in System.IO.SyncTextReader, System.IO.StreamReader, System.IO.StringReader, and System.IO.TextReader.SyncTextReader.
Definition at line 341 of file TextReader.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer", SR.ArgumentNull_Buffer);
        }
        if (index < 0 || count < 0)
        {
            throw new ArgumentOutOfRangeException((index < 0) ? "index" : "count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (buffer.Length - index < count)
        {
            throw new ArgumentException(SR.Argument_InvalidOffLen);
        }
        return ReadBlockAsyncInternal(new Memory<char>(buffer, index, count), default(CancellationToken)).AsTask();
    }
References System.SR.Argument_InvalidOffLen, System.SR.ArgumentNull_Buffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.buffer, System.count, System.index, and System.IO.TextReader.ReadBlockAsyncInternal().
Referenced by System.IO.TextReader.ReadBlockAsync().