Terraria: System.IO.TextReader.Read
Read() [1/3]
virtual int System.IO.TextReader.Read () inline virtual inherited
Reimplemented in System.IO.SyncTextReader, System.IO.StreamReader.NullStreamReader, System.IO.StreamReader, System.IO.StringReader, and System.IO.TextReader.SyncTextReader.
Definition at line 157 of file TextReader.cs.
    {
        return -1;
    }
Referenced by System.IO.SyncTextReader.Read(), System.IO.TextReader.SyncTextReader.Read(), System.IO.SyncTextReader.Read(), System.IO.TextReader.SyncTextReader.Read(), System.IO.TextReader.Read(), System.IO.TextReader.Read(), System.IO.TextReader.ReadBlock(), System.Xml.XmlTextReaderImpl.ReadData(), System.IO.TextReader.ReadLine(), and System.IO.TextReader.ReadToEnd().