Terraria: System.IO.TextReader.ReadAsyncInternal
ReadAsyncInternal()
virtual ValueTask< int > System.IO.TextReader.ReadAsyncInternal (Memory< char > buffer, CancellationToken cancellationToken) inline package virtual inherited
Reimplemented in System.IO.StreamReader.
Definition at line 332 of file TextReader.cs.
    {
        return new ValueTask<int>(Task<int>.Factory.StartNew(delegate(object state)
        {
            TupleSlim<TextReader, Memory<char>> tupleSlim = (TupleSlim<TextReader, Memory<char>>)state;
            return tupleSlim.Item1.Read(tupleSlim.Item2.Span);
        }, new TupleSlim<TextReader, Memory<char>>(this, buffer), cancellationToken, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default));
    }
References System.buffer, System.cancellationToken, System.Threading.Tasks.TaskScheduler.Default, System.TupleSlim< T1, T2, T3, T4 >.Item1, System.TupleSlim< T1, T2, T3, T4 >.Item2, System.Threading.Tasks.Task< TResult >.StartNew(), and System.state.
Referenced by System.IO.TextReader.ReadAsync(), System.IO.TextReader.ReadBlockAsyncInternal(), and System.IO.TextReader.ReadToEndAsync().