Terraria: System.IO.TextReader.ReadLine
ReadLine()
virtual ? string System.IO.TextReader.ReadLine () inline virtual
Reimplemented in System.IO.SyncTextReader, System.IO.StreamReader.NullStreamReader, System.IO.StreamReader, System.IO.StringReader, System.IO.TextReader.NullTextReader, and System.IO.TextReader.SyncTextReader.
Definition at line 255 of file TextReader.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        while (true)
        {
            int num = Read();
            switch (num)
            {
            case 10:
            case 13:
                if (num == 13 && Peek() == 10)
                {
                    Read();
                }
                return stringBuilder.ToString();
            case -1:
                if (stringBuilder.Length > 0)
                {
                    return stringBuilder.ToString();
                }
                return null;
            }
            stringBuilder.Append((char)num);
        }
    }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.Length, System.IO.TextReader.Peek(), System.IO.TextReader.Read(), and System.Text.StringBuilder.ToString().
Referenced by System.IO.SyncTextReader.ReadLine(), System.IO.TextReader.SyncTextReader.ReadLine(), and System.IO.TextReader.ReadLineAsync().