Terraria: System.IO.TextReader.ReadToEnd
ReadToEnd()
virtual string System.IO.TextReader.ReadToEnd () inline virtual inherited
Reimplemented in System.IO.SyncTextReader, System.IO.StreamReader.NullStreamReader, System.IO.StreamReader, System.IO.StringReader, and System.IO.TextReader.SyncTextReader.
Definition at line 212 of file TextReader.cs.
    {
        char[] array = new char[4096];
        StringBuilder stringBuilder = new StringBuilder(4096);
        int charCount;
        while ((charCount = Read(array, 0, array.Length)) != 0)
        {
            stringBuilder.Append(array, 0, charCount);
        }
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.array, System.charCount, System.IO.TextReader.Read(), and System.Text.StringBuilder.ToString().
Referenced by System.IO.SyncTextReader.ReadToEnd(), System.IO.TextReader.SyncTextReader.ReadToEnd(), and System.Data.DataSet.ReadXml().