Terraria: Internal.Console.Write
Write()
static unsafe void Internal.Console.Write (string s) inline static
Definition at line 20 of file Console.cs.
    {
        byte[] bytes = Encoding.UTF8.GetBytes(s);
        fixed (byte* bytes2 = bytes)
        {
            Interop.Kernel32.WriteFile(s_outputHandle, bytes2, bytes.Length, out var _, IntPtr.Zero);
        }
    }
References System.bytes, System.s, Internal.Console.s_outputHandle, System.Text.Encoding.UTF8, Interop.Kernel32.WriteFile(), and System.IntPtr.Zero.
Referenced by Internal.Console.WriteLine(), and Internal.Console.WriteLine().