Terraria: Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent
DrawTheContent()
override void Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent (SpriteBatch spriteBatch) inline package
Definition at line 22 of file PlayerHeadDrawRenderTargetContent.cs.
    {
        if (_player != null && !_player.ShouldNotDraw)
        {
            _drawData.Clear();
            _dust.Clear();
            _gore.Clear();
            PlayerDrawHeadSet drawinfo = default(PlayerDrawHeadSet);
            drawinfo.BoringSetup(_player, _drawData, _dust, _gore, width / 2, height / 2, 1f, 1f);
            PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_05_TallHats(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_07_JustHair(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(ref drawinfo);
            PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(ref drawinfo);
        }
    }
References Terraria.GameContent.PlayerHeadDrawRenderTargetContent._drawData, Terraria.GameContent.PlayerHeadDrawRenderTargetContent._dust, Terraria.GameContent.PlayerHeadDrawRenderTargetContent._gore, Terraria.GameContent.PlayerHeadDrawRenderTargetContent._player, Terraria.DataStructures.PlayerDrawHeadSet.BoringSetup(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_01_FaceSkin(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_02_DrawArmorWithFullHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_03_HelmetHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_05_TallHats(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_06_NormalHats(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_07_JustHair(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_08_FaceAcc(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.height, Terraria.Player.ShouldNotDraw, and Terraria.GameContent.AnOutlinedDrawRenderTargetContent.width.