Terraria: Terraria.Social.WeGame.IPCBase.ProcessDataArriveEvent
ProcessDataArriveEvent()
virtual void Terraria.Social.WeGame.IPCBase.ProcessDataArriveEvent () inline virtual inherited
Definition at line 86 of file IPCBase.cs.
    {
        if (!HaveDataToRead())
        {
            return;
        }
        List<List<byte>> packList = GetPackList();
        if (packList == null || _onDataArrive == null)
        {
            return;
        }
        foreach (List<byte> item in packList)
        {
            _onDataArrive(item.ToArray());
        }
    }
References Terraria.Social.WeGame.IPCBase._onDataArrive, Terraria.Social.WeGame.IPCBase.GetPackList(), Terraria.Social.WeGame.IPCBase.HaveDataToRead(), and System.item.
Referenced by Terraria.Social.WeGame.IPCClient.CheckFlagAndFireEvent(), and Terraria.Social.WeGame.IPCServer.CheckFlagAndFireEvent().