Terraria: System.Reflection.Metadata.Ecma335.MetadataAggregator.MetadataAggregator
MetadataAggregator() [3/4]
System.Reflection.Metadata.Ecma335.MetadataAggregator.MetadataAggregator (MetadataReader baseReader, IReadOnlyList< int > baseTableRowCounts, IReadOnlyList< int > baseHeapSizes, IReadOnlyList< MetadataReader > deltaReaders) inline private
Definition at line 39 of file MetadataAggregator.cs.
    {
        if (baseTableRowCounts == null)
        {
            if (baseReader == null)
            {
                throw new ArgumentNullException("baseReader");
            }
            if (baseReader.GetTableRowCount(TableIndex.EncMap) != 0)
            {
                throw new ArgumentException(System.SR.BaseReaderMustBeFullMetadataReader, "baseReader");
            }
            CalculateBaseCounts(baseReader, out baseTableRowCounts, out baseHeapSizes);
        }
        else
        {
            if (baseTableRowCounts.Count != MetadataTokens.TableCount)
            {
                throw new ArgumentException(System.SR.Format(System.SR.ExpectedListOfSize, MetadataTokens.TableCount), "baseTableRowCounts");
            }
            if (baseHeapSizes == null)
            {
                throw new ArgumentNullException("baseHeapSizes");
            }
            if (baseHeapSizes.Count != MetadataTokens.HeapCount)
            {
                throw new ArgumentException(System.SR.Format(System.SR.ExpectedListOfSize, MetadataTokens.HeapCount), "baseTableRowCounts");
            }
        }
        if (deltaReaders == null || deltaReaders.Count == 0)
        {
            throw new ArgumentException(System.SR.ExpectedNonEmptyList, "deltaReaders");
        }
        for (int i = 0; i < deltaReaders.Count; i++)
        {
            if (deltaReaders[i].GetTableRowCount(TableIndex.EncMap) == 0 || !deltaReaders[i].IsMinimalDelta)
            {
                throw new ArgumentException(System.SR.ReadersMustBeDeltaReaders, "deltaReaders");
            }
        }
        _heapSizes = CalculateHeapSizes(baseHeapSizes, deltaReaders);
        _rowCounts = CalculateRowCounts(baseTableRowCounts, deltaReaders);
    }
References System.Reflection.Metadata.Ecma335.MetadataAggregator._heapSizes, System.Reflection.Metadata.Ecma335.MetadataAggregator._rowCounts, System.SR.BaseReaderMustBeFullMetadataReader, System.Reflection.Metadata.Ecma335.MetadataAggregator.CalculateBaseCounts(), System.Reflection.Metadata.Ecma335.MetadataAggregator.CalculateHeapSizes(), System.Reflection.Metadata.Ecma335.MetadataAggregator.CalculateRowCounts(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.ExpectedListOfSize, System.SR.ExpectedNonEmptyList, System.SR.Format(), System.Reflection.Metadata.Ecma335.MetadataTokens.HeapCount, System.SR.ReadersMustBeDeltaReaders, and System.Reflection.Metadata.Ecma335.MetadataTokens.TableCount.