Terraria: System.ComponentModel.ReflectEventDescriptor.FillAttributes
FillAttributes() [2/2]
override void System.ComponentModel.ReflectEventDescriptor.FillAttributes (IList attributes) inline protected
Definition at line 125 of file ReflectEventDescriptor.cs.
    {
        FillMethods();
        if (_realEvent != null)
        {
            FillEventInfoAttribute(_realEvent, attributes);
        }
        else
        {
            FillSingleMethodAttribute(_removeMethod, attributes);
            FillSingleMethodAttribute(_addMethod, attributes);
        }
        base.FillAttributes(attributes);
    }
References System.ComponentModel.ReflectEventDescriptor._addMethod, System.ComponentModel.ReflectEventDescriptor._realEvent, System.ComponentModel.ReflectEventDescriptor._removeMethod, System.ComponentModel.ReflectEventDescriptor.FillEventInfoAttribute(), System.ComponentModel.ReflectEventDescriptor.FillMethods(), and System.ComponentModel.ReflectEventDescriptor.FillSingleMethodAttribute().