Terraria: System.ComponentModel.ReflectEventDescriptor.FillMethods
FillMethods()
void System.ComponentModel.ReflectEventDescriptor.FillMethods () inline private
Definition at line 181 of file ReflectEventDescriptor.cs.
    {
        if (_filledMethods)
        {
            return;
        }
        if (_realEvent != null)
        {
            _addMethod = _realEvent.GetAddMethod();
            _removeMethod = _realEvent.GetRemoveMethod();
            EventInfo eventInfo = null;
            if (_addMethod == null || _removeMethod == null)
            {
                Type baseType = _componentClass.BaseType;
                while (baseType != null && baseType != typeof(object))
                {
                    BindingFlags bindingAttr = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
                    EventInfo @event = baseType.GetEvent(_realEvent.Name, bindingAttr);
                    if (@event.GetAddMethod() != null)
                    {
                        eventInfo = @event;
                        break;
                    }
                }
            }
            if (eventInfo != null)
            {
                _addMethod = eventInfo.GetAddMethod();
                _removeMethod = eventInfo.GetRemoveMethod();
                _type = eventInfo.EventHandlerType;
            }
            else
            {
                _type = _realEvent.EventHandlerType;
            }
        }
        else
        {
            _realEvent = _componentClass.GetEvent(Name);
            if (_realEvent != null)
            {
                FillMethods();
                return;
            }
            Type[] args = new Type[1] { _type };
            _addMethod = MemberDescriptor.FindMethod(_componentClass, "AddOn" + Name, args, typeof(void));
            _removeMethod = MemberDescriptor.FindMethod(_componentClass, "RemoveOn" + Name, args, typeof(void));
            if (_addMethod == null || _removeMethod == null)
            {
                throw new ArgumentException(System.SR.Format(System.SR.ErrorMissingEventAccessors, Name));
            }
        }
        _filledMethods = true;
    }
References System.ComponentModel.ReflectEventDescriptor._addMethod, System.ComponentModel.ReflectEventDescriptor._componentClass, System.ComponentModel.ReflectEventDescriptor._filledMethods, System.ComponentModel.ReflectEventDescriptor._realEvent, System.ComponentModel.ReflectEventDescriptor._removeMethod, System.ComponentModel.ReflectEventDescriptor._type, System.Type.BaseType, System.SR.ErrorMissingEventAccessors, System.Reflection.EventInfo.EventHandlerType, System.ComponentModel.ReflectEventDescriptor.FillMethods(), System.ComponentModel.MemberDescriptor.FindMethod(), System.SR.Format(), System.Reflection.EventInfo.GetAddMethod(), System.Type.GetEvent(), System.Reflection.EventInfo.GetRemoveMethod(), System.ComponentModel.MemberDescriptor.Name, and System.Reflection.MemberInfo.Name.
Referenced by System.ComponentModel.ReflectEventDescriptor.AddEventHandler(), System.ComponentModel.ReflectEventDescriptor.FillAttributes(), System.ComponentModel.ReflectEventDescriptor.FillMethods(), and System.ComponentModel.ReflectEventDescriptor.RemoveEventHandler().