Terraria: System.ComponentModel.ReflectEventDescriptor.AddEventHandler
AddEventHandler()
override void System.ComponentModel.ReflectEventDescriptor.AddEventHandler (object component, Delegate value) inline
Definition at line 71 of file ReflectEventDescriptor.cs.
    {
        FillMethods();
        if (component == null)
        {
            return;
        }
        ISite site = MemberDescriptor.GetSite(component);
        IComponentChangeService componentChangeService = null;
        if (site != null)
        {
            componentChangeService = (IComponentChangeService)site.GetService(typeof(IComponentChangeService));
        }
        if (componentChangeService != null)
        {
            try
            {
                componentChangeService.OnComponentChanging(component, this);
            }
            catch (CheckoutException ex)
            {
                if (ex == CheckoutException.Canceled)
                {
                    return;
                }
                throw;
            }
            componentChangeService.OnComponentChanging(component, this);
        }
        bool flag = false;
        if (site != null && site.DesignMode)
        {
            if (EventType != value.GetType())
            {
                throw new ArgumentException(System.SR.Format(System.SR.ErrorInvalidEventHandler, Name));
            }
            IDictionaryService dictionaryService = (IDictionaryService)site.GetService(typeof(IDictionaryService));
            if (dictionaryService != null)
            {
                Delegate a = (Delegate)dictionaryService.GetValue(this);
                a = Delegate.Combine(a, value);
                dictionaryService.SetValue(this, a);
                flag = true;
            }
        }
        if (!flag)
        {
            MethodInfo addMethod = _addMethod;
            object[] parameters = new Delegate[1] { value };
            addMethod.Invoke(component, parameters);
        }
        componentChangeService?.OnComponentChanged(component, this, null, value);
    }
References System.ComponentModel.ReflectEventDescriptor._addMethod, System.ComponentModel.Design.CheckoutException.Canceled, System.Delegate.Combine(), System.Delegate, System.ComponentModel.ISite.DesignMode, System.SR.ErrorInvalidEventHandler, System.ComponentModel.ReflectEventDescriptor.EventType, System.ComponentModel.ReflectEventDescriptor.FillMethods(), System.SR.Format(), System.IServiceProvider.GetService(), System.ComponentModel.MemberDescriptor.GetSite(), System.Type.GetType(), System.ComponentModel.Design.IDictionaryService.GetValue(), System.Reflection.MethodBase.Invoke(), System.ComponentModel.MemberDescriptor.Name, System.ComponentModel.Design.IComponentChangeService.OnComponentChanged(), System.ComponentModel.Design.IComponentChangeService.OnComponentChanging(), System.ComponentModel.Design.IDictionaryService.SetValue(), and System.value.