Terraria: System.ComponentModel.ReflectEventDescriptor.RemoveEventHandler
RemoveEventHandler()
override void System.ComponentModel.ReflectEventDescriptor.RemoveEventHandler (object component, Delegate value) inline
Definition at line 277 of file ReflectEventDescriptor.cs.
    {
        FillMethods();
        if (component == null)
        {
            return;
        }
        ISite site = MemberDescriptor.GetSite(component);
        IComponentChangeService componentChangeService = null;
        if (site != null)
        {
            componentChangeService = (IComponentChangeService)site.GetService(typeof(IComponentChangeService));
        }
        if (componentChangeService != null)
        {
            try
            {
                componentChangeService.OnComponentChanging(component, this);
            }
            catch (CheckoutException ex)
            {
                if (ex == CheckoutException.Canceled)
                {
                    return;
                }
                throw;
            }
            componentChangeService.OnComponentChanging(component, this);
        }
        bool flag = false;
        if (site != null && site.DesignMode)
        {
            IDictionaryService dictionaryService = (IDictionaryService)site.GetService(typeof(IDictionaryService));
            if (dictionaryService != null)
            {
                Delegate source = (Delegate)dictionaryService.GetValue(this);
                source = Delegate.Remove(source, value);
                dictionaryService.SetValue(this, source);
                flag = true;
            }
        }
        if (!flag)
        {
            MethodInfo removeMethod = _removeMethod;
            object[] parameters = new Delegate[1] { value };
            removeMethod.Invoke(component, parameters);
        }
        componentChangeService?.OnComponentChanged(component, this, null, value);
    }
References System.ComponentModel.ReflectEventDescriptor._removeMethod, System.ComponentModel.Design.CheckoutException.Canceled, System.Delegate, System.ComponentModel.ISite.DesignMode, System.ComponentModel.ReflectEventDescriptor.FillMethods(), System.IServiceProvider.GetService(), System.ComponentModel.MemberDescriptor.GetSite(), System.ComponentModel.Design.IDictionaryService.GetValue(), System.Reflection.MethodBase.Invoke(), System.ComponentModel.Design.IComponentChangeService.OnComponentChanged(), System.ComponentModel.Design.IComponentChangeService.OnComponentChanging(), System.Delegate.Remove(), System.ComponentModel.Design.IDictionaryService.SetValue(), System.source, and System.value.