Terraria: System.Net.NetworkInformation.PhysicalAddress.TryParse
TryParse() [1/2]
static bool System.Net.NetworkInformation.PhysicalAddress.TryParse (ReadOnlySpan< char > address, [NotNullWhen(true)] out PhysicalAddress? value) inline static
Definition at line 112 of file PhysicalAddress.cs.
    {
        char? c = null;
        value = null;
        byte[] array;
        int value2;
        if (address.Contains('-'))
        {
            if ((address.Length + 1) % 3 != 0)
            {
                return false;
            }
            c = '-';
            array = new byte[(address.Length + 1) / 3];
            value2 = 2;
        }
        else if (address.Contains(':'))
        {
            c = ':';
            if (!TryGetValidSegmentLength(address, ':', out value2))
            {
                return false;
            }
            if (value2 != 2 && value2 != 4)
            {
                return false;
            }
            array = new byte[6];
        }
        else if (address.Contains('.'))
        {
            c = '.';
            if (!TryGetValidSegmentLength(address, '.', out value2))
            {
                return false;
            }
            if (value2 != 4)
            {
                return false;
            }
            array = new byte[6];
        }
        else
        {
            if (address.Length % 2 > 0)
            {
                return false;
            }
            value2 = address.Length;
            array = new byte[address.Length / 2];
        }
        int num = 0;
        int num2 = 0;
        for (int i = 0; i < address.Length; i++)
        {
            int num3 = address[i];
            int num4;
            if ((num4 = System.HexConverter.FromChar(num3)) == 255)
            {
                if (c == num3 && num == value2)
                {
                    num = 0;
                    continue;
                }
                return false;
            }
            num3 = num4;
            if (num >= value2)
            {
                return false;
            }
            if (num % 2 == 0)
            {
                array[num2] = (byte)(num3 << 4);
            }
            else
            {
                array[num2++] |= (byte)num3;
            }
            num++;
        }
        if (num < value2)
        {
            return false;
        }
        value = new PhysicalAddress(array);
        return true;
    }
References System.Net.NetworkInformation.PhysicalAddress.PhysicalAddress(), System.array, System.HexConverter.FromChar(), System.ReadOnlySpan< T >.Length, System.Net.NetworkInformation.PhysicalAddress.TryGetValidSegmentLength(), and System.value.