Terraria: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_08_Backpacks
DrawPlayer_08_Backpacks()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_08_Backpacks (ref PlayerDrawSet drawinfo) inline static
Definition at line 369 of file PlayerDrawLayers.cs.
    {
        if (DrawPlayer_08_PlayerVisuallyHasFullArmorSet(drawinfo, 266, 235, 218))
        {
            Vector2 vec = new Vector2(-2f + -2f * drawinfo.drawPlayer.Directions.X, 0f) + drawinfo.Position - Main.screenPosition + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.width / 2, drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2);
            vec = vec.Floor();
            Texture2D value = TextureAssets.Extra[212].Value;
            Rectangle value2 = value.Frame(1, 5, 0, drawinfo.drawPlayer.miscCounter % 25 / 5);
            Color immuneAlphaPure = drawinfo.drawPlayer.GetImmuneAlphaPure(new Color(250, 250, 250, 200), drawinfo.shadow);
            immuneAlphaPure *= drawinfo.drawPlayer.stealth;
            DrawData item = new DrawData(value, vec, value2, immuneAlphaPure, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
            item.shader = drawinfo.cBody;
            drawinfo.DrawDataCache.Add(item);
        }
        if (DrawPlayer_08_PlayerVisuallyHasFullArmorSet(drawinfo, 268, 237, 222))
        {
            Vector2 vec2 = new Vector2(-9f + 1f * drawinfo.drawPlayer.Directions.X, -4f * drawinfo.drawPlayer.Directions.Y) + drawinfo.Position - Main.screenPosition + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.width / 2, drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2);
            vec2 = vec2.Floor();
            Texture2D value3 = TextureAssets.Extra[213].Value;
            Rectangle value4 = value3.Frame(1, 5, 0, drawinfo.drawPlayer.miscCounter % 25 / 5);
            Color immuneAlphaPure2 = drawinfo.drawPlayer.GetImmuneAlphaPure(new Color(250, 250, 250, 200), drawinfo.shadow);
            immuneAlphaPure2 *= drawinfo.drawPlayer.stealth;
            DrawData item = new DrawData(value3, vec2, value4, immuneAlphaPure2, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
            item.shader = drawinfo.cBody;
            drawinfo.DrawDataCache.Add(item);
        }
        if (drawinfo.heldItem.type == 4818 && drawinfo.drawPlayer.ownedProjectileCounts[902] == 0)
        {
            int num = 8;
            Vector2 vector = new Vector2(0f, 8f);
            Vector2 vec3 = drawinfo.Position - Main.screenPosition + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.width / 2, drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2) + new Vector2(0f, -4f) + vector;
            vec3 = vec3.Floor();
            DrawData item = new DrawData(TextureAssets.BackPack[num].Value, vec3, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
            drawinfo.DrawDataCache.Add(item);
        }
        if (drawinfo.drawPlayer.backpack > 0 && drawinfo.drawPlayer.backpack < ArmorIDs.Back.Count && !drawinfo.drawPlayer.mount.Active)
        {
            Vector2 vector2 = new Vector2(0f, 8f);
            Vector2 vec4 = drawinfo.Position - Main.screenPosition + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.width / 2, drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2) + new Vector2(0f, -4f) + vector2;
            vec4 = vec4.Floor();
            DrawData item = new DrawData(TextureAssets.AccBack[drawinfo.drawPlayer.backpack].Value, vec4, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
            item.shader = drawinfo.cBackpack;
            drawinfo.DrawDataCache.Add(item);
        }
        else
        {
            if (drawinfo.heldItem.type != 1178 && drawinfo.heldItem.type != 779 && drawinfo.heldItem.type != 5134 && drawinfo.heldItem.type != 1295 && drawinfo.heldItem.type != 1910 && !drawinfo.drawPlayer.turtleArmor && drawinfo.drawPlayer.body != 106 && drawinfo.drawPlayer.body != 170)
            {
                return;
            }
            int type = drawinfo.heldItem.type;
            int num2 = 1;
            float num3 = -4f;
            float num4 = -8f;
            int shader = 0;
            if (drawinfo.drawPlayer.turtleArmor)
            {
                num2 = 4;
                shader = drawinfo.cBody;
            }
            else if (drawinfo.drawPlayer.body == 106)
            {
                num2 = 6;
                shader = drawinfo.cBody;
            }
            else if (drawinfo.drawPlayer.body == 170)
            {
                num2 = 7;
                shader = drawinfo.cBody;
            }
            else
            {
                switch (type)
                {
                case 1178:
                    num2 = 1;
                    break;
                case 779:
                    num2 = 2;
                    break;
                case 5134:
                    num2 = 9;
                    break;
                case 1295:
                    num2 = 3;
                    break;
                case 1910:
                    num2 = 5;
                    break;
                }
            }
            Vector2 vector3 = new Vector2(0f, 8f);
            Vector2 vec5 = drawinfo.Position - Main.screenPosition + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.width / 2, drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2) + new Vector2(0f, -4f) + vector3;
            vec5 = vec5.Floor();
            Vector2 vec6 = drawinfo.Position - Main.screenPosition + new Vector2(drawinfo.drawPlayer.width / 2, drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height / 2) + new Vector2((-9f + num3) * (float)drawinfo.drawPlayer.direction, (2f + num4) * drawinfo.drawPlayer.gravDir) + vector3;
            vec6 = vec6.Floor();
            switch (num2)
            {
            case 7:
            {
                DrawData item = new DrawData(TextureAssets.BackPack[num2].Value, vec5, new Rectangle(0, drawinfo.drawPlayer.bodyFrame.Y, TextureAssets.BackPack[num2].Width(), drawinfo.drawPlayer.bodyFrame.Height), drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, new Vector2((float)TextureAssets.BackPack[num2].Width() * 0.5f, drawinfo.bodyVect.Y), 1f, drawinfo.playerEffect);
                item.shader = shader;
                drawinfo.DrawDataCache.Add(item);
                break;
            }
            case 4:
            case 6:
            {
                DrawData item = new DrawData(TextureAssets.BackPack[num2].Value, vec5, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                item.shader = shader;
                drawinfo.DrawDataCache.Add(item);
                break;
            }
            default:
            {
                DrawData item = new DrawData(TextureAssets.BackPack[num2].Value, vec6, new Rectangle(0, 0, TextureAssets.BackPack[num2].Width(), TextureAssets.BackPack[num2].Height()), drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, new Vector2(TextureAssets.BackPack[num2].Width() / 2, TextureAssets.BackPack[num2].Height() / 2), 1f, drawinfo.playerEffect);
                item.shader = shader;
                drawinfo.DrawDataCache.Add(item);
                break;
            }
            }
        }
    }
References Terraria.GameContent.TextureAssets.AccBack, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Terraria.GameContent.TextureAssets.BackPack, Microsoft.Xna.Framework.Graphics.Color, Terraria.ID.ArmorIDs.Back.Count, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_08_PlayerVisuallyHasFullArmorSet(), Terraria.GameContent.TextureAssets.Extra, System.item, System.type, System.value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().