Terraria: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_1_Magiluminescence
DrawPlayer_21_1_Magiluminescence()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_1_Magiluminescence (ref PlayerDrawSet drawinfo) inline static
Definition at line 2177 of file PlayerDrawLayers.cs.
    {
        if (drawinfo.shadow == 0f && drawinfo.drawPlayer.neck == 11 && !drawinfo.hideEntirePlayer)
        {
            Color colorArmorBody = drawinfo.colorArmorBody;
            Color value = new Color(140, 140, 35, 12);
            float amount = (float)(colorArmorBody.R + colorArmorBody.G + colorArmorBody.B) / 3f / 255f;
            value = Color.Lerp(value, Color.Transparent, amount);
            if (!(value == Color.Transparent))
            {
                DrawData item = new DrawData(TextureAssets.GlowMask[310].Value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2), drawinfo.drawPlayer.bodyFrame, value, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                item.shader = drawinfo.cNeck;
                drawinfo.DrawDataCache.Add(item);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Color.G, Terraria.GameContent.TextureAssets.GlowMask, System.item, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Color.R, Terraria.Main.screenPosition, Microsoft.Xna.Framework.Color.Transparent, and System.value.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().