Terraria: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_36_CTG
DrawPlayer_36_CTG()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_36_CTG (ref PlayerDrawSet drawinfo) inline static
Definition at line 3255 of file PlayerDrawLayers.cs.
    {
        if (drawinfo.shadow != 0f || (byte)drawinfo.drawPlayer.ownedLargeGems <= 0)
        {
            return;
        }
        bool flag = false;
        BitsByte ownedLargeGems = drawinfo.drawPlayer.ownedLargeGems;
        float num = 0f;
        for (int i = 0; i < 7; i++)
        {
            if (ownedLargeGems[i])
            {
                num += 1f;
            }
        }
        float num2 = 1f - num * 0.06f;
        float num3 = (num - 1f) * 4f;
        switch ((int)num)
        {
        case 2:
            num3 += 10f;
            break;
        case 3:
            num3 += 8f;
            break;
        case 4:
            num3 += 6f;
            break;
        case 5:
            num3 += 6f;
            break;
        case 6:
            num3 += 2f;
            break;
        case 7:
            num3 += 0f;
            break;
        }
        float num4 = (float)drawinfo.drawPlayer.miscCounter / 300f * ((float)Math.PI * 2f);
        if (!(num > 0f))
        {
            return;
        }
        float num5 = (float)Math.PI * 2f / num;
        float num6 = 0f;
        Vector2 vector = new Vector2(1.3f, 0.65f);
        if (!flag)
        {
            vector = Vector2.One;
        }
        List<DrawData> list = new List<DrawData>();
        for (int j = 0; j < 7; j++)
        {
            if (!ownedLargeGems[j])
            {
                num6 += 1f;
                continue;
            }
            Vector2 vector2 = (num4 + num5 * ((float)j - num6)).ToRotationVector2();
            float num7 = num2;
            if (flag)
            {
                num7 = MathHelper.Lerp(num2 * 0.7f, 1f, vector2.Y / 2f + 0.5f);
            }
            Texture2D value = TextureAssets.Gem[j].Value;
            DrawData item = new DrawData(value, new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - 80f)) + vector2 * vector * num3, null, new Color(250, 250, 250, Main.mouseTextColor / 2), 0f, value.Size() / 2f, ((float)(int)Main.mouseTextColor / 1000f + 0.8f) * num7, SpriteEffects.None);
            list.Add(item);
        }
        if (flag)
        {
            list.Sort(DelegateMethods.CompareDrawSorterByYScale);
        }
        drawinfo.DrawDataCache.AddRange(list);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), Terraria.DelegateMethods.CompareDrawSorterByYScale(), Terraria.GameContent.TextureAssets.Gem, System.item, Microsoft.Xna.Framework.MathHelper.Lerp(), System.list, Terraria.Main.mouseTextColor, Microsoft.Xna.Framework.Vector2.One, System.Math.PI, Terraria.Main.screenPosition, System.value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().