Terraria: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing
DrawPlayer_05_ForbiddenSetRing()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_05_ForbiddenSetRing (ref PlayerDrawSet drawinfo) inline static
Definition at line 219 of file PlayerDrawLayers.cs.
    {
        if (drawinfo.drawPlayer.setForbidden && drawinfo.shadow == 0f)
        {
            Color color = Color.Lerp(drawinfo.colorArmorBody, Color.White, 0.7f);
            Texture2D value = TextureAssets.Extra[74].Value;
            Texture2D value2 = TextureAssets.GlowMask[217].Value;
            bool num = !drawinfo.drawPlayer.setForbiddenCooldownLocked;
            int num2 = 0;
            num2 = (int)(((float)drawinfo.drawPlayer.miscCounter / 300f * ((float)Math.PI * 2f)).ToRotationVector2().Y * 6f);
            float num3 = ((float)drawinfo.drawPlayer.miscCounter / 75f * ((float)Math.PI * 2f)).ToRotationVector2().X * 4f;
            Color color2 = new Color(80, 70, 40, 0) * (num3 / 8f + 0.5f) * 0.8f;
            if (!num)
            {
                num2 = 0;
                num3 = 2f;
                color2 = new Color(80, 70, 40, 0) * 0.3f;
                color = color.MultiplyRGB(new Color(0.5f, 0.5f, 1f));
            }
            Vector2 vector = new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(drawinfo.drawPlayer.bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2);
            int num4 = 10;
            int num5 = 20;
            if (drawinfo.drawPlayer.head == 238)
            {
                num4 += 4;
                num5 += 4;
            }
            vector += new Vector2(-drawinfo.drawPlayer.direction * num4, (float)(-num5) * drawinfo.drawPlayer.gravDir + (float)num2 * drawinfo.drawPlayer.gravDir);
            DrawData item = new DrawData(value, vector, null, color, drawinfo.drawPlayer.bodyRotation, value.Size() / 2f, 1f, drawinfo.playerEffect);
            item.shader = drawinfo.cBody;
            drawinfo.DrawDataCache.Add(item);
            for (float num6 = 0f; num6 < 4f; num6 += 1f)
            {
                item = new DrawData(value2, vector + (num6 * ((float)Math.PI / 2f)).ToRotationVector2() * num3, null, color2, drawinfo.drawPlayer.bodyRotation, value.Size() / 2f, 1f, drawinfo.playerEffect);
                drawinfo.DrawDataCache.Add(item);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.GlowMask, System.item, Microsoft.Xna.Framework.Color.Lerp(), System.Math.PI, Terraria.Main.screenPosition, System.value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().