Terraria: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_25_Shield
DrawPlayer_25_Shield()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_25_Shield (ref PlayerDrawSet drawinfo) inline static
Definition at line 2391 of file PlayerDrawLayers.cs.
    {
        if (drawinfo.drawPlayer.shield <= 0 || drawinfo.drawPlayer.shield >= ArmorIDs.Shield.Count)
        {
            return;
        }
        Vector2 zero = Vector2.Zero;
        if (drawinfo.drawPlayer.shieldRaised)
        {
            zero.Y -= 4f * drawinfo.drawPlayer.gravDir;
        }
        Rectangle bodyFrame = drawinfo.drawPlayer.bodyFrame;
        Vector2 zero2 = Vector2.Zero;
        Vector2 bodyVect = drawinfo.bodyVect;
        if (bodyFrame.Width != TextureAssets.AccShield[drawinfo.drawPlayer.shield].Value.Width)
        {
            bodyFrame.Width = TextureAssets.AccShield[drawinfo.drawPlayer.shield].Value.Width;
            bodyVect.X += bodyFrame.Width - TextureAssets.AccShield[drawinfo.drawPlayer.shield].Value.Width;
            if (drawinfo.playerEffect.HasFlag(SpriteEffects.FlipHorizontally))
            {
                bodyVect.X = (float)bodyFrame.Width - bodyVect.X;
            }
        }
        DrawData item;
        if (drawinfo.drawPlayer.shieldRaised)
        {
            float num = (float)Math.Sin(Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f));
            float x = 2.5f + 1.5f * num;
            Color colorArmorBody = drawinfo.colorArmorBody;
            colorArmorBody.A = 0;
            colorArmorBody *= 0.45f - num * 0.15f;
            for (float num2 = 0f; num2 < 4f; num2 += 1f)
            {
                item = new DrawData(TextureAssets.AccShield[drawinfo.drawPlayer.shield].Value, zero2 + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2) + zero + new Vector2(x, 0f).RotatedBy(num2 / 4f * ((float)Math.PI * 2f)), bodyFrame, colorArmorBody, drawinfo.drawPlayer.bodyRotation, bodyVect, 1f, drawinfo.playerEffect);
                item.shader = drawinfo.cShield;
                drawinfo.DrawDataCache.Add(item);
            }
        }
        item = new DrawData(TextureAssets.AccShield[drawinfo.drawPlayer.shield].Value, zero2 + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2) + zero, bodyFrame, drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, bodyVect, 1f, drawinfo.playerEffect);
        item.shader = drawinfo.cShield;
        drawinfo.DrawDataCache.Add(item);
        if (drawinfo.drawPlayer.shieldRaised)
        {
            Color colorArmorBody2 = drawinfo.colorArmorBody;
            float num3 = (float)Math.Sin(Main.GlobalTimeWrappedHourly * (float)Math.PI);
            colorArmorBody2.A = (byte)((float)(int)colorArmorBody2.A * (0.5f + 0.5f * num3));
            colorArmorBody2 *= 0.5f + 0.5f * num3;
            item = new DrawData(TextureAssets.AccShield[drawinfo.drawPlayer.shield].Value, zero2 + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2) + zero, bodyFrame, colorArmorBody2, drawinfo.drawPlayer.bodyRotation, bodyVect, 1f, drawinfo.playerEffect);
            item.shader = drawinfo.cShield;
        }
        if (drawinfo.drawPlayer.shieldRaised && drawinfo.drawPlayer.shieldParryTimeLeft > 0)
        {
            float num4 = (float)drawinfo.drawPlayer.shieldParryTimeLeft / 20f;
            float num5 = 1.5f * num4;
            Vector2 vector = zero2 + new Vector2((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2(bodyFrame.Width / 2, drawinfo.drawPlayer.bodyFrame.Height / 2) + zero;
            Color colorArmorBody3 = drawinfo.colorArmorBody;
            float num6 = 1f;
            Vector2 vector2 = drawinfo.Position + drawinfo.drawPlayer.Size / 2f - Main.screenPosition;
            Vector2 vector3 = vector - vector2;
            vector += vector3 * num5;
            num6 += num5;
            colorArmorBody3.A = (byte)((float)(int)colorArmorBody3.A * (1f - num4));
            colorArmorBody3 *= 1f - num4;
            item = new DrawData(TextureAssets.AccShield[drawinfo.drawPlayer.shield].Value, vector, bodyFrame, colorArmorBody3, drawinfo.drawPlayer.bodyRotation, bodyVect, num6, drawinfo.playerEffect);
            item.shader = drawinfo.cShield;
            drawinfo.DrawDataCache.Add(item);
        }
        if (drawinfo.drawPlayer.mount.Cart)
        {
            drawinfo.DrawDataCache.Reverse(drawinfo.DrawDataCache.Count - 2, 2);
        }
    }
References Terraria.GameContent.TextureAssets.AccShield, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, Terraria.ID.ArmorIDs.Shield.Count, Terraria.Main.GlobalTimeWrappedHourly, System.item, System.Math.PI, Terraria.Main.screenPosition, System.Math.Sin(), Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().