Terraria: Terraria.DataStructures.PlayerDrawLayers.DrawMeowcartTrail
DrawMeowcartTrail()
static void Terraria.DataStructures.PlayerDrawLayers.DrawMeowcartTrail (ref PlayerDrawSet drawinfo) inline static
Definition at line 2313 of file PlayerDrawLayers.cs.
    {
        if (drawinfo.drawPlayer.mount.Type == 33 && !(drawinfo.shadow > 0f))
        {
            int num = Math.Min(drawinfo.drawPlayer.availableAdvancedShadowsCount - 1, 20);
            float num2 = 0f;
            for (int num3 = num; num3 > 0; num3--)
            {
                EntityShadowInfo advancedShadow = drawinfo.drawPlayer.GetAdvancedShadow(num3);
                EntityShadowInfo advancedShadow2 = drawinfo.drawPlayer.GetAdvancedShadow(num3 - 1);
                num2 += Vector2.Distance(advancedShadow.Position, advancedShadow2.Position);
            }
            float num4 = MathHelper.Clamp(num2 / 160f, 0f, 1f);
            Main.instance.LoadProjectile(250);
            Texture2D value = TextureAssets.Projectile[250].Value;
            float x = 1.5f;
            Vector2 origin = new Vector2(value.Width / 2, 0f);
            Vector2 vector = new Vector2(drawinfo.drawPlayer.width, drawinfo.drawPlayer.height) / 2f;
            Vector2 vector2 = new Vector2(-drawinfo.drawPlayer.direction * 10, 15f);
            Color white = Color.White;
            white.A = 127;
            Vector2 vector3 = vector + vector2;
            vector3 = Vector2.Zero;
            Vector2 vector4 = drawinfo.drawPlayer.RotatedRelativePoint(drawinfo.drawPlayer.Center + vector3 + vector2) - drawinfo.drawPlayer.position;
            for (int num5 = num; num5 > 0; num5--)
            {
                EntityShadowInfo advancedShadow3 = drawinfo.drawPlayer.GetAdvancedShadow(num5);
                EntityShadowInfo advancedShadow4 = drawinfo.drawPlayer.GetAdvancedShadow(num5 - 1);
                Vector2 pos = advancedShadow3.Position + vector3;
                Vector2 pos2 = advancedShadow4.Position + vector3;
                pos += vector4;
                pos2 += vector4;
                pos = drawinfo.drawPlayer.RotatedRelativePoint(pos, reverseRotation: true, addGfxOffY: false);
                pos2 = drawinfo.drawPlayer.RotatedRelativePoint(pos2, reverseRotation: true, addGfxOffY: false);
                float rotation = (pos2 - pos).ToRotation() - (float)Math.PI / 2f;
                float num6 = Vector2.Distance(pos, pos2);
                Vector2 scale = new Vector2(x, num6 / (float)value.Height);
                float num7 = 1f - (float)num5 / (float)num;
                num7 *= num7;
                Color color = white * num7 * num4;
                DrawData item = new DrawData(value, pos - Main.screenPosition, null, color, rotation, origin, scale, drawinfo.playerEffect);
                drawinfo.DrawDataCache.Add(item);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.instance, System.item, System.Math.Min(), System.Math.PI, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, System.value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_02_MountBehindPlayer().