Terraria: System.Xml.Xsl.Runtime.WhitespaceRuleReader.Read
Read()
override bool System.Xml.Xsl.Runtime.WhitespaceRuleReader.Read () inline
Definition at line 66 of file WhitespaceRuleReader.cs.
    {
        string text = null;
        _val = null;
        while (base.Read())
        {
            switch (base.NodeType)
            {
            case XmlNodeType.Element:
                if (!base.IsEmptyElement)
                {
                    _stkStrip.PushBit(_shouldStrip);
                    _shouldStrip = _wsRules.ShouldStripSpace(base.LocalName, base.NamespaceURI) && base.XmlSpace != XmlSpace.Preserve;
                }
                break;
            case XmlNodeType.EndElement:
                _shouldStrip = _stkStrip.PopBit();
                break;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
                if (_preserveAdjacent)
                {
                    return true;
                }
                if (!_shouldStrip)
                {
                    break;
                }
                if (!XmlCharType.IsOnlyWhitespace(base.Value))
                {
                    if (text != null)
                    {
                        _val = text + base.Value;
                    }
                    _preserveAdjacent = true;
                    return true;
                }
                goto case XmlNodeType.Whitespace;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                if (_preserveAdjacent)
                {
                    return true;
                }
                if (_shouldStrip)
                {
                    text = ((text != null) ? (text + base.Value) : base.Value);
                    continue;
                }
                break;
            case XmlNodeType.EndEntity:
                continue;
            }
            _preserveAdjacent = false;
            return true;
        }
        return false;
    }
References System.Xml.Xsl.Runtime.WhitespaceRuleReader._preserveAdjacent, System.Xml.Xsl.Runtime.WhitespaceRuleReader._shouldStrip, System.Xml.Xsl.Runtime.WhitespaceRuleReader._stkStrip, System.Xml.Xsl.Runtime.WhitespaceRuleReader._val, System.Xml.Xsl.Runtime.WhitespaceRuleReader._wsRules, System.Xml.Dictionary, System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.BitStack.PopBit(), System.Xml.BitStack.PushBit(), System.Xml.Xsl.Runtime.WhitespaceRuleLookup.ShouldStripSpace(), and System.text.