Terraria: System.Text.Json.JsonSerializerOptions.DetermineConverter
DetermineConverter()
JsonConverter System.Text.Json.JsonSerializerOptions.DetermineConverter (Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo) inline package
Definition at line 408 of file JsonSerializerOptions.cs.
    {
        JsonConverter jsonConverter = null;
        if (memberInfo != null)
        {
            JsonConverterAttribute jsonConverterAttribute = (JsonConverterAttribute)GetAttributeThatCanHaveMultiple(parentClassType, typeof(JsonConverterAttribute), memberInfo);
            if (jsonConverterAttribute != null)
            {
                jsonConverter = GetConverterFromAttribute(jsonConverterAttribute, runtimePropertyType, parentClassType, memberInfo);
            }
        }
        if (jsonConverter == null)
        {
            jsonConverter = GetConverterInternal(runtimePropertyType);
        }
        if (jsonConverter is JsonConverterFactory jsonConverterFactory)
        {
            jsonConverter = jsonConverterFactory.GetConverterInternal(runtimePropertyType, this);
        }
        if (runtimePropertyType.IsValueType && jsonConverter.IsValueType && (runtimePropertyType.IsNullableOfT() ^ jsonConverter.TypeToConvert.IsNullableOfT()))
        {
            ThrowHelper.ThrowInvalidOperationException_ConverterCanConvertMultipleTypes(runtimePropertyType, jsonConverter);
        }
        return jsonConverter;
    }
References System.Text.Json.Dictionary, System.Text.Json.JsonSerializerOptions.GetAttributeThatCanHaveMultiple(), System.Text.Json.JsonSerializerOptions.GetConverterFromAttribute(), System.Text.Json.JsonSerializerOptions.GetConverterInternal(), and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConverterCanConvertMultipleTypes().