Terraria: System.Text.Json.JsonSerializerOptions.VerifyMutable
VerifyMutable()
void System.Text.Json.JsonSerializerOptions.VerifyMutable () inline package
Definition at line 753 of file JsonSerializerOptions.cs.
    {
        if (_haveTypesBeenCreated || _context != null)
        {
            ThrowHelper.ThrowInvalidOperationException_SerializerOptionsImmutable(_context);
        }
    }
References System.Text.Json.JsonSerializerOptions._context, System.Text.Json.JsonSerializerOptions._haveTypesBeenCreated, and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerOptionsImmutable().
Referenced by System.Text.Json.Serialization.ConverterList.Add(), System.Text.Json.Serialization.ConverterList.Clear(), System.Text.Json.Serialization.ConverterList.Insert(), System.Text.Json.Serialization.ConverterList.Remove(), and System.Text.Json.Serialization.ConverterList.RemoveAt().