Terraria: System.Text.Json.JsonSerializerOptions.GetConverterInternal
GetConverterInternal()
JsonConverter System.Text.Json.JsonSerializerOptions.GetConverterInternal (Type typeToConvert) inline package
Definition at line 445 of file JsonSerializerOptions.cs.
    {
        if (_converters.TryGetValue(typeToConvert, out var value))
        {
            return value;
        }
        value = _context?.GetTypeInfo(typeToConvert)?.PropertyInfoForTypeInfo?.ConverterBase;
        foreach (JsonConverter converter in Converters)
        {
            if (converter.CanConvert(typeToConvert))
            {
                value = converter;
                break;
            }
        }
        if (value == null)
        {
            JsonConverterAttribute jsonConverterAttribute = (JsonConverterAttribute)GetAttributeThatCanHaveMultiple(typeToConvert, typeof(JsonConverterAttribute));
            if (jsonConverterAttribute != null)
            {
                value = GetConverterFromAttribute(jsonConverterAttribute, typeToConvert, typeToConvert, null);
            }
        }
        if (value == null)
        {
            if (s_defaultSimpleConverters == null || s_defaultFactoryConverters == null)
            {
                ThrowHelper.ThrowNotSupportedException_BuiltInConvertersNotRooted(typeToConvert);
                return null;
            }
            if (s_defaultSimpleConverters.TryGetValue(typeToConvert, out var value2))
            {
                value = value2;
            }
            else
            {
                JsonConverter[] array = s_defaultFactoryConverters;
                foreach (JsonConverter jsonConverter in array)
                {
                    if (jsonConverter.CanConvert(typeToConvert))
                    {
                        value = jsonConverter;
                        break;
                    }
                }
            }
        }
        if (value is JsonConverterFactory jsonConverterFactory)
        {
            value = jsonConverterFactory.GetConverterInternal(typeToConvert, this);
        }
        Type typeToConvert2 = value.TypeToConvert;
        if (!typeToConvert2.IsAssignableFromInternal(typeToConvert) && !typeToConvert.IsAssignableFromInternal(typeToConvert2))
        {
            ThrowHelper.ThrowInvalidOperationException_SerializationConverterNotCompatible(value.GetType(), typeToConvert);
        }
        if (_haveTypesBeenCreated)
        {
            _converters.TryAdd(typeToConvert, value);
        }
        return value;
    }
References System.Text.Json.JsonSerializerOptions._context, System.Text.Json.JsonSerializerOptions._converters, System.Text.Json.JsonSerializerOptions._haveTypesBeenCreated, System.array, System.converter, System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ConverterBase, System.Text.Json.Dictionary, System.Text.Json.JsonSerializerOptions.GetAttributeThatCanHaveMultiple(), System.Text.Json.JsonSerializerOptions.GetConverterFromAttribute(), System.Text.Json.Serialization.JsonSerializerContext.GetTypeInfo(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.PropertyInfoForTypeInfo, System.Text.Json.JsonSerializerOptions.s_defaultFactoryConverters, System.Text.Json.JsonSerializerOptions.s_defaultSimpleConverters, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializationConverterNotCompatible(), System.Text.Json.ThrowHelper.ThrowNotSupportedException_BuiltInConvertersNotRooted(), System.Collections.Generic.Dictionary< TKey, TValue >.TryAdd(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Text.Json.JsonSerializerOptions.DetermineConverter(), System.Text.Json.JsonSerializerOptions.GetConverter(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.IsValidDataExtensionProperty(), System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ReadJsonAndAddExtensionProperty(), and System.Text.Json.Serialization.Metadata.JsonPropertyInfo< T >.ReadJsonExtensionDataValue().