Terraria: System.Text.Json.JsonSerializerOptions.GetConverterFromAttribute
GetConverterFromAttribute()
JsonConverter System.Text.Json.JsonSerializerOptions.GetConverterFromAttribute (JsonConverterAttribute converterAttribute, Type typeToConvert, Type classTypeAttributeIsOn, MemberInfo memberInfo) inline private
Definition at line 508 of file JsonSerializerOptions.cs.
    {
        Type converterType = converterAttribute.ConverterType;
        JsonConverter jsonConverter;
        if (converterType == null)
        {
            jsonConverter = converterAttribute.CreateConverter(typeToConvert);
            if (jsonConverter == null)
            {
                ThrowHelper.ThrowInvalidOperationException_SerializationConverterOnAttributeNotCompatible(classTypeAttributeIsOn, memberInfo, typeToConvert);
            }
        }
        else
        {
            ConstructorInfo constructor = converterType.GetConstructor(Type.EmptyTypes);
            if (!typeof(JsonConverter).IsAssignableFrom(converterType) || constructor == null || !constructor.IsPublic)
            {
                ThrowHelper.ThrowInvalidOperationException_SerializationConverterOnAttributeInvalid(classTypeAttributeIsOn, memberInfo);
            }
            jsonConverter = (JsonConverter)Activator.CreateInstance(converterType);
        }
        if (!jsonConverter.CanConvert(typeToConvert))
        {
            Type underlyingType = Nullable.GetUnderlyingType(typeToConvert);
            if (underlyingType != null && jsonConverter.CanConvert(underlyingType))
            {
                if (jsonConverter is JsonConverterFactory jsonConverterFactory)
                {
                    jsonConverter = jsonConverterFactory.GetConverterInternal(underlyingType, this);
                }
                return NullableConverterFactory.CreateValueConverter(underlyingType, jsonConverter);
            }
            ThrowHelper.ThrowInvalidOperationException_SerializationConverterOnAttributeNotCompatible(classTypeAttributeIsOn, memberInfo, typeToConvert);
        }
        return jsonConverter;
    }
References System.Activator.CreateInstance(), System.Text.Json.Serialization.Converters.NullableConverterFactory.CreateValueConverter(), System.Text.Json.Dictionary, System.Type.EmptyTypes, System.Nullable< T >.GetUnderlyingType(), System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializationConverterOnAttributeInvalid(), and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializationConverterOnAttributeNotCompatible().
Referenced by System.Text.Json.JsonSerializerOptions.DetermineConverter(), and System.Text.Json.JsonSerializerOptions.GetConverterInternal().