Terraria: Gore.UpdateFogMachineCloud
UpdateFogMachineCloud()
void Gore.UpdateFogMachineCloud () inline private
     {
         timeLeft -= GoreID.Sets.DisappearSpeed[type];
         if (timeLeft <= 0)
         {
             active = false;
             return;
         }
         bool flag = false;
         Point point = (position + new Vector2(15f, 0f)).ToTileCoordinates();
         if (WorldGen.SolidTile(Main.tile[point.X, point.Y]))
         {
             flag = true;
         }
         if (timeLeft <= 240)
         {
             flag = true;
         }
         if (!flag)
         {
             if (alpha > 225 && Main.rand.Next(2) == 0)
             {
                 alpha--;
             }
         }
         else
         {
             if (Main.rand.Next(2) == 0)
             {
                 alpha++;
             }
             if (alpha >= 255)
             {
                 active = false;
                 return;
             }
         }
         position += velocity;
     }
References active, alpha, GoreID.Sets.DisappearSpeed, UnifiedRandom.Next(), position, Main.rand, WorldGen.SolidTile(), Main.tile, timeLeft, type, and velocity.
Referenced by Update().