Terraria: Gore.Gore_UpdateLeaf
Gore_UpdateLeaf()
void Gore.Gore_UpdateLeaf () inline private
     {
         Vector2 vector = position + new Vector2(12f) / 2f - new Vector2(4f) / 2f;
         vector.Y -= 4f;
         Vector2 vector2 = position - vector;
         if (velocity.Y < 0f)
         {
             Vector2 vector3 = new Vector2(velocity.X, -0.2f);
             int num = 4;
             num = (int)((float)num * 0.9f);
             Point point = (new Vector2(num, num) / 2f + vector).ToTileCoordinates();
             if (!WorldGen.InWorld(point.X, point.Y))
             {
                 active = false;
                 return;
             }
             Tile tile = Main.tile[point.X, point.Y];
             if (tile == null)
             {
                 active = false;
                 return;
             }
             int num2 = 6;
             Rectangle rectangle = new Rectangle(point.X * 16, point.Y * 16 + tile.liquid / 16, 16, 16 - tile.liquid / 16);
             Rectangle value = new Rectangle((int)vector.X, (int)vector.Y + num2, num, num);
             bool flag = tile != null && tile.liquid > 0 && rectangle.Intersects(value);
             if (flag)
             {
                 if (tile.honey())
                 {
                     vector3.X = 0f;
                 }
                 else if (tile.lava())
                 {
                     active = false;
                     for (int i = 0; i < 5; i++)
                     {
                         Dust.NewDust(position, num, num, 31, 0f, -0.2f);
                     }
                 }
                 else
                 {
                     vector3.X = Main.WindForVisuals;
                 }
                 if ((double)position.Y > Main.worldSurface * 16.0)
                 {
                     vector3.X = 0f;
                 }
             }
             if (!WorldGen.SolidTile(point.X, point.Y + 1) && !flag)
             {
                 velocity.Y = 0.1f;
                 timeLeft = 0;
                 alpha += 20;
             }
             vector3 = Collision.TileCollision(vector, vector3, num, num);
             if (flag)
             {
                 rotation = vector3.ToRotation() + (float)Math.PI / 2f;
             }
             vector3.X *= 0.94f;
             if (!flag || ((double)vector3.X > -0.01 && (double)vector3.X < 0.01))
             {
                 vector3.X = 0f;
             }
             if (timeLeft > 0)
             {
                 timeLeft -= GoreID.Sets.DisappearSpeed[type];
             }
             else
             {
                 alpha += GoreID.Sets.DisappearSpeedAlpha[type];
             }
             velocity.X = vector3.X;
             position.X += velocity.X;
             return;
         }
         velocity.Y += (float)Math.PI / 180f;
         Vector2 vector4 = new Vector2(Vector2.UnitY.RotatedBy(velocity.Y).X * 1f, Math.Abs(Vector2.UnitY.RotatedBy(velocity.Y).Y) * 1f);
         int num3 = 4;
         if ((double)position.Y < Main.worldSurface * 16.0)
         {
             vector4.X += Main.WindForVisuals * 4f;
         }
         Vector2 vector5 = vector4;
         vector4 = Collision.TileCollision(vector, vector4, num3, num3);
         Vector4 vector6 = Collision.SlopeCollision(vector, vector4, num3, num3, 1f);
         position.X = vector6.X;
         position.Y = vector6.Y;
         vector4.X = vector6.Z;
         vector4.Y = vector6.W;
         position += vector2;
         if (vector4 != vector5)
         {
             velocity.Y = -1f;
         }
         Point point2 = (new Vector2(Width, Height) * 0.5f + position).ToTileCoordinates();
         if (!WorldGen.InWorld(point2.X, point2.Y))
         {
             active = false;
             return;
         }
         Tile tile2 = Main.tile[point2.X, point2.Y];
         if (tile2 == null)
         {
             active = false;
             return;
         }
         int num4 = 6;
         Rectangle rectangle2 = new Rectangle(point2.X * 16, point2.Y * 16 + tile2.liquid / 16, 16, 16 - tile2.liquid / 16);
         Rectangle value2 = new Rectangle((int)vector.X, (int)vector.Y + num4, num3, num3);
         if (tile2 != null && tile2.liquid > 0 && rectangle2.Intersects(value2))
         {
             velocity.Y = -1f;
         }
         position += vector4;
         rotation = vector4.ToRotation() + (float)Math.PI / 2f;
         if (timeLeft > 0)
         {
             timeLeft -= GoreID.Sets.DisappearSpeed[type];
         }
         else
         {
             alpha += GoreID.Sets.DisappearSpeedAlpha[type];
         }
     }
References active, alpha, GoreID.Sets.DisappearSpeed, GoreID.Sets.DisappearSpeedAlpha, Height, Tile.honey(), WorldGen.InWorld(), Tile.lava(), Tile.liquid, Dust.NewDust(), position, rotation, Collision.SlopeCollision(), WorldGen.SolidTile(), Main.tile, Collision.TileCollision(), timeLeft, type, velocity, Width, Main.WindForVisuals, and Main.worldSurface.
Referenced by Update().