Terraria: AWorkshopEntry.TryReadingManifest
TryReadingManifest()
static bool AWorkshopEntry.TryReadingManifest (string filePath, out FoundWorkshopEntryInfo info) inline static inherited
     {
         info = null;
         if (!File.Exists(filePath))
         {
             return false;
         }
         string text = File.ReadAllText(filePath);
         info = new FoundWorkshopEntryInfo();
         Dictionary<string, object> dictionary = JsonConvert.DeserializeObject<Dictionary<string, object>>(text, SerializerSettings);
         if (dictionary == null)
         {
             return false;
         }
         if (!TryGet<ulong>(dictionary, "SteamEntryId", out info.workshopEntryId))
         {
             return false;
         }
         if (!TryGet<int>(dictionary, "WorkshopPublishedVersion", out var outputValue))
         {
             outputValue = 1;
         }
         info.publishedVersion = outputValue;
         if (TryGet<JArray>(dictionary, "Tags", out var outputValue2))
         {
             info.tags = ((JToken)outputValue2).ToObject<string[]>();
         }
         if (TryGet<int>(dictionary, "Publicity", out var outputValue3))
         {
             info.publicity = (WorkshopItemPublicSettingId)outputValue3;
         }
         TryGet<string>(dictionary, "PreviewImagePath", out info.previewImagePath);
         return true;
     }
References AWorkshopEntry.SerializerSettings.
Referenced by WorkshopHelper.UGCBased.APublisherInstance.PublishContent(), WorkshopSocialModule.TryGetInfoForResourcePack(), and WorkshopSocialModule.TryGetInfoForWorld().