Terraria: Gore.Update
Update()
void Gore.Update () inline
     {
         if (Main.netMode == 2 || !active)
         {
             return;
         }
         if (sticky)
         {
             if (DeactivateIfOutsideOfWorld())
             {
                 return;
             }
             float num = velocity.Length();
             if (num > 32f)
             {
                 velocity *= 32f / num;
             }
         }
         switch (GoreID.Sets.SpecialAI[type])
         {
         case 4:
             UpdateAmbientFloorCloud();
             return;
         case 5:
             UpdateAmbientAirborneCloud();
             return;
         case 6:
             UpdateFogMachineCloud();
             return;
         case 7:
             UpdateLightningBunnySparks();
             return;
         }
         if ((type == 1217 || type == 1218) && frameCounter == 0)
         {
             frameCounter = 1;
             Frame.CurrentRow = (byte)Main.rand.Next(3);
         }
         bool flag = type >= 1024 && type <= 1026;
         if (type >= 276 && type <= 282)
         {
             velocity.X *= 0.98f;
             velocity.Y *= 0.98f;
             if (velocity.Y < scale)
             {
                 velocity.Y += 0.05f;
             }
             if ((double)velocity.Y > 0.1)
             {
                 if (velocity.X > 0f)
                 {
                     rotation += 0.01f;
                 }
                 else
                 {
                     rotation -= 0.01f;
                 }
             }
         }
         if (type >= 570 && type <= 572)
         {
             scale -= 0.001f;
             if ((double)scale <= 0.01)
             {
                 scale = 0.01f;
                 timeLeft = 0;
             }
             sticky = false;
             rotation = velocity.X * 0.1f;
         }
         else if ((type >= 706 && type <= 717) || type == 943 || type == 1147 || (type >= 1160 && type <= 1162))
         {
             if (type == 943 || (type >= 1160 && type <= 1162))
             {
                 alpha = 0;
             }
             else if ((double)position.Y < Main.worldSurface * 16.0 + 8.0)
             {
                 alpha = 0;
             }
             else
             {
                 alpha = 100;
             }
             int num2 = 4;
             frameCounter++;
             if (frame <= 4)
             {
                 int num3 = (int)(position.X / 16f);
                 int num4 = (int)(position.Y / 16f) - 1;
                 if (WorldGen.InWorld(num3, num4) && !Main.tile[num3, num4].active())
                 {
                     active = false;
                 }
                 if (frame == 0)
                 {
                     num2 = 24 + Main.rand.Next(256);
                 }
                 if (frame == 1)
                 {
                     num2 = 24 + Main.rand.Next(256);
                 }
                 if (frame == 2)
                 {
                     num2 = 24 + Main.rand.Next(256);
                 }
                 if (frame == 3)
                 {
                     num2 = 24 + Main.rand.Next(96);
                 }
                 if (frame == 5)
                 {
                     num2 = 16 + Main.rand.Next(64);
                 }
                 if (type == 716)
                 {
                     num2 *= 2;
                 }
                 if (type == 717)
                 {
                     num2 *= 4;
                 }
                 if ((type == 943 || (type >= 1160 && type <= 1162)) && frame < 6)
                 {
                     num2 = 4;
                 }
                 if (frameCounter >= num2)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame == 5)
                     {
                         int num5 = NewGore(position, velocity, type);
                         Main.gore[num5].frame = 9;
                         Main.gore[num5].velocity *= 0f;
                     }
                 }
             }
             else if (frame <= 6)
             {
                 num2 = 8;
                 if (type == 716)
                 {
                     num2 *= 2;
                 }
                 if (type == 717)
                 {
                     num2 *= 3;
                 }
                 if (frameCounter >= num2)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame == 7)
                     {
                         active = false;
                     }
                 }
             }
             else if (frame <= 9)
             {
                 num2 = 6;
                 if (type == 716)
                 {
                     num2 = (int)((double)num2 * 1.5);
                     velocity.Y += 0.175f;
                 }
                 else if (type == 717)
                 {
                     num2 *= 2;
                     velocity.Y += 0.15f;
                 }
                 else if (type == 943)
                 {
                     num2 = (int)((double)num2 * 1.5);
                     velocity.Y += 0.2f;
                 }
                 else
                 {
                     velocity.Y += 0.2f;
                 }
                 if ((double)velocity.Y < 0.5)
                 {
                     velocity.Y = 0.5f;
                 }
                 if (velocity.Y > 12f)
                 {
                     velocity.Y = 12f;
                 }
                 if (frameCounter >= num2)
                 {
                     frameCounter = 0;
                     frame++;
                 }
                 if (frame > 9)
                 {
                     frame = 7;
                 }
             }
             else
             {
                 if (type == 716)
                 {
                     num2 *= 2;
                 }
                 else if (type == 717)
                 {
                     num2 *= 6;
                 }
                 velocity.Y += 0.1f;
                 if (frameCounter >= num2)
                 {
                     frameCounter = 0;
                     frame++;
                 }
                 velocity *= 0f;
                 if (frame > 14)
                 {
                     active = false;
                 }
             }
         }
         else if (type == 11 || type == 12 || type == 13 || type == 61 || type == 62 || type == 63 || type == 99 || type == 220 || type == 221 || type == 222 || (type >= 375 && type <= 377) || (type >= 435 && type <= 437) || (type >= 861 && type <= 862))
         {
             velocity.Y *= 0.98f;
             velocity.X *= 0.98f;
             scale -= 0.007f;
             if ((double)scale < 0.1)
             {
                 scale = 0.1f;
                 alpha = 255;
             }
         }
         else if (type == 16 || type == 17)
         {
             velocity.Y *= 0.98f;
             velocity.X *= 0.98f;
             scale -= 0.01f;
             if ((double)scale < 0.1)
             {
                 scale = 0.1f;
                 alpha = 255;
             }
         }
         else if (type == 1201)
         {
             if (frameCounter == 0)
             {
                 frameCounter = 1;
                 Frame.CurrentRow = (byte)Main.rand.Next(4);
             }
             scale -= 0.002f;
             if ((double)scale < 0.1)
             {
                 scale = 0.1f;
                 alpha = 255;
             }
             rotation += velocity.X * 0.1f;
             int num6 = (int)(position.X + 6f) / 16;
             int num7 = (int)(position.Y - 6f) / 16;
             if (Main.tile[num6, num7] == null || Main.tile[num6, num7].liquid <= 0)
             {
                 velocity.Y += 0.2f;
                 if (velocity.Y < 0f)
                 {
                     velocity *= 0.92f;
                 }
             }
             else
             {
                 velocity.Y += 0.005f;
                 float num8 = velocity.Length();
                 if (num8 > 1f)
                 {
                     velocity *= 0.1f;
                 }
                 else if (num8 > 0.1f)
                 {
                     velocity *= 0.98f;
                 }
             }
         }
         else if (type == 1208)
         {
             if (frameCounter == 0)
             {
                 frameCounter = 1;
                 Frame.CurrentRow = (byte)Main.rand.Next(4);
             }
             Vector2 vector = position + new Vector2(Width, Height) / 2f;
             int num9 = (int)vector.X / 16;
             int num10 = (int)vector.Y / 16;
             bool flag2 = Main.tile[num9, num10] != null && Main.tile[num9, num10].liquid > 0;
             scale -= 0.0005f;
             if ((double)scale < 0.1)
             {
                 scale = 0.1f;
                 alpha = 255;
             }
             rotation += velocity.X * 0.1f;
             if (flag2)
             {
                 velocity.X *= 0.9f;
                 int num11 = (int)vector.X / 16;
                 int num12 = (int)(vector.Y / 16f);
                 _ = position.Y / 16f;
                 int num13 = (int)((position.Y + Height) / 16f);
                 if (Main.tile[num11, num12] == null)
                 {
                     Main.tile[num11, num12] = new Tile();
                 }
                 if (Main.tile[num11, num13] == null)
                 {
                     Main.tile[num11, num13] = new Tile();
                 }
                 if (velocity.Y > 0f)
                 {
                     velocity.Y *= 0.5f;
                 }
                 num11 = (int)(vector.X / 16f);
                 num12 = (int)(vector.Y / 16f);
                 float num14 = ChumFloatingChunk_GetWaterLine(num11, num12);
                 if (vector.Y > num14)
                 {
                     velocity.Y -= 0.1f;
                     if (velocity.Y < -8f)
                     {
                         velocity.Y = -8f;
                     }
                     if (vector.Y + velocity.Y < num14)
                     {
                         velocity.Y = num14 - vector.Y;
                     }
                 }
                 else
                 {
                     velocity.Y = num14 - vector.Y;
                 }
                 bool flag3 = !flag2 && velocity.Length() < 0.8f;
                 int maxValue = (flag2 ? 270 : 15);
                 if (Main.rand.Next(maxValue) == 0 && !flag3)
                 {
                     Gore gore = NewGoreDirect(position + Vector2.UnitY * 6f, Vector2.Zero, 1201, scale * 0.7f);
                     if (flag2)
                     {
                         gore.velocity = Vector2.UnitX * Main.rand.NextFloatDirection() * 0.5f + Vector2.UnitY * Main.rand.NextFloat();
                     }
                     else if (gore.velocity.Y < 0f)
                     {
                         gore.velocity.Y = 0f - gore.velocity.Y;
                     }
                 }
             }
             else
             {
                 if (velocity.Y == 0f)
                 {
                     velocity.X *= 0.95f;
                 }
                 velocity.X *= 0.98f;
                 velocity.Y += 0.3f;
                 if (velocity.Y > 15.9f)
                 {
                     velocity.Y = 15.9f;
                 }
             }
         }
         else if (type == 331)
         {
             alpha += 5;
             velocity.Y *= 0.95f;
             velocity.X *= 0.95f;
             rotation = velocity.X * 0.1f;
         }
         else if (GoreID.Sets.SpecialAI[type] == 3)
         {
             if (++frameCounter >= 8 && velocity.Y > 0.2f)
             {
                 frameCounter = 0;
                 int num15 = Frame.CurrentRow / 4;
                 if (++Frame.CurrentRow >= 4 + num15 * 4)
                 {
                     Frame.CurrentRow = (byte)(num15 * 4);
                 }
             }
         }
         else if (GoreID.Sets.SpecialAI[type] != 1 && GoreID.Sets.SpecialAI[type] != 2)
         {
             if (type >= 907 && type <= 909)
             {
                 rotation = 0f;
                 velocity.X *= 0.98f;
                 if (velocity.Y > 0f && velocity.Y < 0.001f)
                 {
                     velocity.Y = -0.5f + Main.rand.NextFloat() * -3f;
                 }
                 if (velocity.Y > -1f)
                 {
                     velocity.Y -= 0.1f;
                 }
                 if (scale < 1f)
                 {
                     scale += 0.1f;
                 }
                 if (++frameCounter >= 8)
                 {
                     frameCounter = 0;
                     if (++frame >= 3)
                     {
                         frame = 0;
                     }
                 }
             }
             else if (type == 1218)
             {
                 if (timeLeft > 8)
                 {
                     timeLeft = 8;
                 }
                 velocity.X *= 0.95f;
                 if (Math.Abs(velocity.X) <= 0.1f)
                 {
                     velocity.X = 0f;
                 }
                 if (alpha < 100 && velocity.Length() > 0f && Main.rand.Next(5) == 0)
                 {
                     int num16 = 246;
                     switch (Frame.CurrentRow)
                     {
                     case 0:
                         num16 = 246;
                         break;
                     case 1:
                         num16 = 245;
                         break;
                     case 2:
                         num16 = 244;
                         break;
                     }
                     int num17 = Dust.NewDust(position + new Vector2(6f, 4f), 4, 4, num16);
                     Main.dust[num17].alpha = 255;
                     Main.dust[num17].scale = 0.8f;
                     Main.dust[num17].velocity = Vector2.Zero;
                 }
                 velocity.Y += 0.2f;
                 rotation = 0f;
             }
             else if (type < 411 || type > 430)
             {
                 velocity.Y += 0.2f;
                 rotation += velocity.X * 0.05f;
             }
             else if (GoreID.Sets.SpecialAI[type] != 3)
             {
                 rotation += velocity.X * 0.1f;
             }
         }
         if (type >= 580 && type <= 582)
         {
             rotation = 0f;
             velocity.X *= 0.95f;
         }
         if (GoreID.Sets.SpecialAI[type] == 2)
         {
             if (timeLeft < 60)
             {
                 alpha += Main.rand.Next(1, 7);
             }
             else if (alpha > 100)
             {
                 alpha -= Main.rand.Next(1, 4);
             }
             if (alpha < 0)
             {
                 alpha = 0;
             }
             if (alpha > 255)
             {
                 timeLeft = 0;
             }
             velocity.X = (velocity.X * 50f + Main.WindForVisuals * 2f + (float)Main.rand.Next(-10, 11) * 0.1f) / 51f;
             float num18 = 0f;
             if (velocity.X < 0f)
             {
                 num18 = velocity.X * 0.2f;
             }
             velocity.Y = (velocity.Y * 50f + -0.35f + num18 + (float)Main.rand.Next(-10, 11) * 0.2f) / 51f;
             rotation = velocity.X * 0.6f;
             float num19 = -1f;
             if (TextureAssets.Gore[type].IsLoaded)
             {
                 Rectangle rectangle = new Rectangle((int)position.X, (int)position.Y, (int)((float)TextureAssets.Gore[type].Width() * scale), (int)((float)TextureAssets.Gore[type].Height() * scale));
                 for (int i = 0; i < 255; i++)
                 {
                     if (Main.player[i].active && !Main.player[i].dead)
                     {
                         Rectangle value = new Rectangle((int)Main.player[i].position.X, (int)Main.player[i].position.Y, Main.player[i].width, Main.player[i].height);
                         if (rectangle.Intersects(value))
{
                             timeLeft = 0;
                             num19 = Main.player[i].velocity.Length();
                             break;
                         }
                     }
                 }
             }
             if (timeLeft > 0)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     timeLeft--;
                 }
                 if (Main.rand.Next(50) == 0)
                 {
                     timeLeft -= 5;
                 }
                 if (Main.rand.Next(100) == 0)
                 {
                     timeLeft -= 10;
                 }
             }
             else
             {
                 alpha = 255;
                 if (TextureAssets.Gore[type].IsLoaded && num19 != -1f)
                 {
                     float num20 = (float)TextureAssets.Gore[type].Width() * scale * 0.8f;
                     float x = position.X;
                     float y = position.Y;
                     float num21 = (float)TextureAssets.Gore[type].Width() * scale;
                     float num22 = (float)TextureAssets.Gore[type].Height() * scale;
                     int num23 = 31;
                     for (int j = 0; (float)j < num20; j++)
                     {
                         int num24 = Dust.NewDust(new Vector2(x, y), (int)num21, (int)num22, num23);
                         Main.dust[num24].velocity *= (1f + num19) / 3f;
                         Main.dust[num24].noGravity = true;
                         Main.dust[num24].alpha = 100;
                         Main.dust[num24].scale = scale;
                     }
                 }
             }
         }
         if (type >= 411 && type <= 430)
         {
             alpha = 50;
             velocity.X = (velocity.X * 50f + Main.WindForVisuals * 2f + (float)Main.rand.Next(-10, 11) * 0.1f) / 51f;
             velocity.Y = (velocity.Y * 50f + -0.25f + (float)Main.rand.Next(-10, 11) * 0.2f) / 51f;
             rotation = velocity.X * 0.3f;
             if (TextureAssets.Gore[type].IsLoaded)
             {
                 Rectangle rectangle2 = new Rectangle((int)position.X, (int)position.Y, (int)((float)TextureAssets.Gore[type].Width() * scale), (int)((float)TextureAssets.Gore[type].Height() * scale));
                 for (int k = 0; k < 255; k++)
                 {
                     if (Main.player[k].active && !Main.player[k].dead)
                     {
                         Rectangle value2 = new Rectangle((int)Main.player[k].position.X, (int)Main.player[k].position.Y, Main.player[k].width, Main.player[k].height);
                         if (rectangle2.Intersects(value2))
{
                             timeLeft = 0;
                         }
                     }
                 }
                 if (Collision.SolidCollision(position, (int)((float)TextureAssets.Gore[type].Width() * scale), (int)((float)TextureAssets.Gore[type].Height() * scale)))
                 {
                     timeLeft = 0;
                 }
             }
             if (timeLeft > 0)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     timeLeft--;
                 }
                 if (Main.rand.Next(50) == 0)
                 {
                     timeLeft -= 5;
                 }
                 if (Main.rand.Next(100) == 0)
                 {
                     timeLeft -= 10;
                 }
             }
             else
             {
                 alpha = 255;
                 if (TextureAssets.Gore[type].IsLoaded)
                 {
                     float num25 = (float)TextureAssets.Gore[type].Width() * scale * 0.8f;
                     float x2 = position.X;
                     float y2 = position.Y;
                     float num26 = (float)TextureAssets.Gore[type].Width() * scale;
                     float num27 = (float)TextureAssets.Gore[type].Height() * scale;
                     int num28 = 176;
                     if (type >= 416 && type <= 420)
                     {
                         num28 = 177;
                     }
                     if (type >= 421 && type <= 425)
                     {
                         num28 = 178;
                     }
                     if (type >= 426 && type <= 430)
                     {
                         num28 = 179;
                     }
                     for (int l = 0; (float)l < num25; l++)
                     {
                         int num29 = Dust.NewDust(new Vector2(x2, y2), (int)num26, (int)num27, num28);
                         Main.dust[num29].noGravity = true;
                         Main.dust[num29].alpha = 100;
                         Main.dust[num29].scale = scale;
                     }
                 }
             }
         }
         else if (GoreID.Sets.SpecialAI[type] != 3 && GoreID.Sets.SpecialAI[type] != 1)
         {
             if ((type >= 706 && type <= 717) || type == 943 || type == 1147 || (type >= 1160 && type <= 1162))
             {
                 if (type == 716)
                 {
                     float num30 = 1f;
                     float num31 = 1f;
                     float num32 = 1f;
                     float num33 = 0.6f;
                     num33 = ((frame == 0) ? (num33 * 0.1f) : ((frame == 1) ? (num33 * 0.2f) : ((frame == 2) ? (num33 * 0.3f) : ((frame == 3) ? (num33 * 0.4f) : ((frame == 4) ? (num33 * 0.5f) : ((frame == 5) ? (num33 * 0.4f) : ((frame == 6) ? (num33 * 0.2f) : ((frame <= 9) ? (num33 * 0.5f) : ((frame == 10) ? (num33 * 0.5f) : ((frame == 11) ? (num33 * 0.4f) : ((frame == 12) ? (num33 * 0.3f) : ((frame == 13) ? (num33 * 0.2f) : ((frame != 14) ? 0f : (num33 * 0.1f))))))))))))));
                     num30 = 1f * num33;
                     num31 = 0.5f * num33;
                     num32 = 0.1f * num33;
                     Lighting.AddLight(position + new Vector2(8f, 8f), num30, num31, num32);
                 }
                 Vector2 vector2 = velocity;
                 velocity = Collision.TileCollision(position, velocity, 16, 14);
                 if (velocity != vector2)
                 {
                     if (frame < 10)
                     {
                         frame = 10;
                         frameCounter = 0;
                         if (type != 716 && type != 717 && type != 943 && (type < 1160 || type > 1162))
{
                             SoundEngine.PlaySound(39, (int)position.X + 8, (int)position.Y + 8, Main.rand.Next(2));
                         }
                     }
                 }
                 else if (Collision.WetCollision(position + velocity, 16, 14))
                 {
                     if (frame < 10)
                     {
                         frame = 10;
                         frameCounter = 0;
                         if (type != 716 && type != 717 && type != 943 && (type < 1160 || type > 1162))
{
                             SoundEngine.PlaySound(39, (int)position.X + 8, (int)position.Y + 8, 2);
                         }
                         ((WaterShaderData)Filters.Scene["WaterDistortion"].GetShader()).QueueRipple(position + new Vector2(8f, 8f));
                     }
                     int num34 = (int)(position.X + 8f) / 16;
                     int num35 = (int)(position.Y + 14f) / 16;
                     if (Main.tile[num34, num35] != null && Main.tile[num34, num35].liquid > 0)
                     {
                         velocity *= 0f;
                         position.Y = num35 * 16 - Main.tile[num34, num35].liquid / 16;
                     }
                 }
             }
             else if (sticky)
             {
                 int num36 = 32;
                 if (TextureAssets.Gore[type].IsLoaded)
                 {
                     num36 = TextureAssets.Gore[type].Width();
                     if (TextureAssets.Gore[type].Height() < num36)
                     {
                         num36 = TextureAssets.Gore[type].Height();
                     }
                 }
                 if (flag)
                 {
                     num36 = 4;
                 }
                 num36 = (int)((float)num36 * 0.9f);
                 _ = velocity;
                 velocity = Collision.TileCollision(position, velocity, (int)((float)num36 * scale), (int)((float)num36 * scale));
                 if (velocity.Y == 0f)
                 {
                     if (flag)
                     {
                         velocity.X *= 0.94f;
                     }
                     else
                     {
                         velocity.X *= 0.97f;
                     }
                     if ((double)velocity.X > -0.01 && (double)velocity.X < 0.01)
                     {
                         velocity.X = 0f;
                     }
                 }
                 if (timeLeft > 0)
                 {
                     timeLeft -= GoreID.Sets.DisappearSpeed[type];
                 }
                 else
                 {
                     alpha += GoreID.Sets.DisappearSpeedAlpha[type];
                 }
             }
             else
             {
                 alpha += 2 * GoreID.Sets.DisappearSpeedAlpha[type];
             }
         }
         if (type >= 907 && type <= 909)
         {
             int num37 = 32;
             if (TextureAssets.Gore[type].IsLoaded)
             {
                 num37 = TextureAssets.Gore[type].Width();
                 if (TextureAssets.Gore[type].Height() < num37)
                 {
                     num37 = TextureAssets.Gore[type].Height();
                 }
             }
             num37 = (int)((float)num37 * 0.9f);
             Vector4 vector3 = Collision.SlopeCollision(position, velocity, num37, num37, 0f, fall: true);
             position.X = vector3.X;
             position.Y = vector3.Y;
             velocity.X = vector3.Z;
             velocity.Y = vector3.W;
         }
         if (GoreID.Sets.SpecialAI[type] == 1)
         {
             Gore_UpdateSail();
         }
         else if (GoreID.Sets.SpecialAI[type] == 3)
         {
             Gore_UpdateLeaf();
         }
         else
         {
             position += velocity;
         }
         if (alpha >= 255)
         {
             active = false;
         }
         if (light > 0f)
         {
             float num38 = light * scale;
             float num39 = light * scale;
             float num40 = light * scale;
             if (type == 16)
             {
                 num40 *= 0.3f;
                 num39 *= 0.8f;
             }
             else if (type == 17)
             {
                 num39 *= 0.6f;
                 num38 *= 0.3f;
             }
             if (TextureAssets.Gore[type].IsLoaded)
             {
                 Lighting.AddLight((int)((position.X + (float)TextureAssets.Gore[type].Width() * scale / 2f) / 16f), (int)((position.Y + (float)TextureAssets.Gore[type].Height() * scale / 2f) / 16f), num38, num39, num40);
             }
             else
             {
                 Lighting.AddLight((int)((position.X + 32f * scale / 2f) / 16f), (int)((position.Y + 32f * scale / 2f) / 16f), num38, num39, num40);
             }
         }
     }
References Entity.active, active, Tile.active(), Lighting.AddLight(), Dust.alpha, alpha, ChumFloatingChunk_GetWaterLine(), SpriteFrame.CurrentRow, DeactivateIfOutsideOfWorld(), Player.dead, GoreID.Sets.DisappearSpeed, GoreID.Sets.DisappearSpeedAlpha, Main.dust, Frame, frame, frameCounter, TextureAssets.Gore, Main.gore, Gore_UpdateLeaf(), Gore_UpdateSail(), Entity.height, Height, WorldGen.InWorld(), Asset< T >.IsLoaded, light, Tile.liquid, Main.netMode, Dust.NewDust(), NewGore(), NewGoreDirect(), UnifiedRandom.Next(), Dust.noGravity, Main.player, SoundEngine.PlaySound(), Entity.position, position, Main.rand, rotation, Dust.scale, scale, Filters.Scene, Collision.SlopeCollision(), Collision.SolidCollision(), GoreID.Sets.SpecialAI, sticky, Tile, Main.tile, Collision.TileCollision(), timeLeft, type, UpdateAmbientAirborneCloud(), UpdateAmbientFloorCloud(), UpdateFogMachineCloud(), UpdateLightningBunnySparks(), Dust.velocity, Entity.velocity, velocity, Collision.WetCollision(), Entity.width, Width, Main.WindForVisuals, and Main.worldSurface.
Referenced by Main.DoUpdateInWorld().