Terraria: Gore.UpdateAmbientAirborneCloud
UpdateAmbientAirborneCloud()
void Gore.UpdateAmbientAirborneCloud () inline private
References active, alpha, GoreID.Sets.DisappearSpeed, UnifiedRandom.Next(), position, Main.rand, rotation, WorldGen.SolidTile(), Main.tile, timeLeft, type, and velocity.
Referenced by Update().