Terraria: Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.OnApply
OnApply()
override void Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.OnApply () inline package virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.Effect.
Definition at line 378 of file EnvironmentMapEffect.cs.
    {
        dirtyFlags = EffectHelpers.SetWorldViewProjAndFog(dirtyFlags, ref world, ref view, ref projection, ref worldView, fogEnabled, fogStart, fogEnd, worldViewProjParam, fogVectorParam);
        dirtyFlags = EffectHelpers.SetLightingMatrices(dirtyFlags, ref world, ref view, worldParam, worldInverseTransposeParam, eyePositionParam);
        if ((dirtyFlags & EffectDirtyFlags.MaterialColor) != 0)
        {
            EffectHelpers.SetMaterialColor(lightingEnabled: true, alpha, ref diffuseColor, ref emissiveColor, ref ambientLightColor, diffuseColorParam, emissiveColorParam);
            dirtyFlags &= ~EffectDirtyFlags.MaterialColor;
        }
        bool flag = !light1.Enabled && !light2.Enabled;
        if (oneLight != flag)
        {
            oneLight = flag;
            dirtyFlags |= EffectDirtyFlags.ShaderIndex;
        }
        if ((dirtyFlags & EffectDirtyFlags.ShaderIndex) != 0)
        {
            int num = 0;
            if (!fogEnabled)
            {
                num++;
            }
            if (fresnelEnabled)
            {
                num += 2;
            }
            if (specularEnabled)
            {
                num += 4;
            }
            if (oneLight)
            {
                num += 8;
            }
            shaderIndexParam.SetValue(num);
            dirtyFlags &= ~EffectDirtyFlags.ShaderIndex;
        }
    }
References Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.alpha, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.ambientLightColor, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.diffuseColor, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.diffuseColorParam, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.dirtyFlags, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.emissiveColor, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.emissiveColorParam, Microsoft.Xna.Framework.Graphics.DirectionalLight.Enabled, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.eyePositionParam, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.fogEnabled, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.fogEnd, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.fogStart, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.fogVectorParam, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.fresnelEnabled, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.light2, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.oneLight, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.projection, Microsoft.Xna.Framework.Graphics.EffectHelpers.SetLightingMatrices(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetMaterialColor(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetWorldViewProjAndFog(), Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.shaderIndexParam, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.specularEnabled, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.view, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.world, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.worldInverseTransposeParam, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.worldParam, Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.worldView, and Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.worldViewProjParam.