Terraria: UIElement.GetElementAt
GetElementAt()
UIElement UIElement.GetElementAt (Vector2 point) inline inherited
     {
         UIElement uIElement = null;
         for (int num = Elements.Count - 1; num >= 0; num--)
         {
             UIElement uIElement2 = Elements[num];
             if (!uIElement2.IgnoresMouseInteraction && uIElement2.ContainsPoint(point))
             {
                 uIElement = uIElement2;
                 break;
             }
         }
         if (uIElement != null)
         {
             return uIElement.GetElementAt(point);
         }
         if (IgnoresMouseInteraction)
         {
             return null;
         }
         if (ContainsPoint(point))
         {
             return this;
         }
         return null;
     }
References UIElement.ContainsPoint(), UIElement.Elements, UIElement.GetElementAt(), and UIElement.IgnoresMouseInteraction.
Referenced by UIElement.GetElementAt(), and UserInterface.Update().