Terraria: InGameNotificationsTracker.DrawInGame
DrawInGame()
static void InGameNotificationsTracker.DrawInGame (SpriteBatch sb) inline static
     {
         float num = Main.screenHeight - 40;
         if (PlayerInput.UsingGamepad)
         {
             num -= 25f;
         }
         Vector2 positionAnchorBottom = new Vector2(Main.screenWidth / 2, num);
         foreach (IInGameNotification notification in _notifications)
         {
             notification.DrawInGame(sb, positionAnchorBottom);
             notification.PushAnchor(ref positionAnchorBottom);
             if (positionAnchorBottom.Y < -100f)
             {
                 break;
             }
         }
     }
References _notifications, IInGameNotification.DrawInGame(), IInGameNotification.PushAnchor(), Main.screenHeight, Main.screenWidth, and PlayerInput.UsingGamepad.
Referenced by Main.DrawInterface_13_AchievementCompletePopups().