Terraria: UIElement.Draw
Draw()
virtual void UIElement.Draw (SpriteBatch spriteBatch) inline virtual inherited
Reimplemented in UIWorldSelect, UIWorldLoad, UIWorldCreation, UIWorkshopWorldImport, UIWorkshopSelectWorldToPublish, UIWorkshopSelectResourcePackToPublish, UIWorkshopHub, UIResourcePackSelectionMenu, UIResourcePackInfoMenu, UIReportsPage, UIManageControls, UIEmotesMenu, UICreativePowersMenu, UICharacterSelect, UICharacterCreation, UIBestiaryTest, UIAchievementsMenu, AWorkshopPublishInfoState< TPublishedObjectType >, and UIClothStyleButton.
     {
         bool overflowHidden = OverflowHidden;
         bool useImmediateMode = UseImmediateMode;
         RasterizerState rasterizerState = spriteBatch.GraphicsDevice.RasterizerState;
         Rectangle scissorRectangle = spriteBatch.GraphicsDevice.ScissorRectangle;
         SamplerState anisotropicClamp = SamplerState.AnisotropicClamp;
         if (useImmediateMode || OverrideSamplerState != null)
         {
             spriteBatch.End();
             spriteBatch.Begin(useImmediateMode ? SpriteSortMode.Immediate : SpriteSortMode.Deferred, BlendState.AlphaBlend, (OverrideSamplerState != null) ? OverrideSamplerState : anisotropicClamp, DepthStencilState.None, OverflowHiddenRasterizerState, null, Main.UIScaleMatrix);
             DrawSelf(spriteBatch);
             spriteBatch.End();
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, anisotropicClamp, DepthStencilState.None, OverflowHiddenRasterizerState, null, Main.UIScaleMatrix);
         }
         else
         {
             DrawSelf(spriteBatch);
         }
         if (overflowHidden)
         {
             spriteBatch.End();
             Rectangle clippingRectangle = GetClippingRectangle(spriteBatch);
             spriteBatch.GraphicsDevice.ScissorRectangle = clippingRectangle;
             spriteBatch.GraphicsDevice.RasterizerState = OverflowHiddenRasterizerState;
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, anisotropicClamp, DepthStencilState.None, OverflowHiddenRasterizerState, null, Main.UIScaleMatrix);
         }
         DrawChildren(spriteBatch);
         if (overflowHidden)
         {
             spriteBatch.End();
             spriteBatch.GraphicsDevice.ScissorRectangle = scissorRectangle;
             spriteBatch.GraphicsDevice.RasterizerState = rasterizerState;
             spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, anisotropicClamp, DepthStencilState.None, rasterizerState, null, Main.UIScaleMatrix);
         }
     }
References UIElement.DrawChildren(), UIElement.DrawSelf(), UIElement.GetClippingRectangle(), UIElement.OverflowHidden, UIElement.OverflowHiddenRasterizerState, UIElement.OverrideSamplerState, Main.UIScaleMatrix, and UIElement.UseImmediateMode.
Referenced by UserInterface.Draw(), UIList.UIInnerList.DrawChildren(), and UIElement.DrawChildren().