Terraria: UIElement.Append
Append()
void UIElement.Append (UIElement element) inline inherited
     {
         element.Remove();
         element.Parent = this;
         Elements.Add(element);
         element.Recalculate();
     }
References UIElement.Elements, UIElement.Parent, UIElement.Recalculate(), and UIElement.Remove().
Referenced by EmotesGroupListItem.EmotesGroupListItem(), GroupOptionButton< T >.GroupOptionButton(), PowerStripUIElement.PowerStripUIElement(), UIAchievementListItem.UIAchievementListItem(), UIBestiaryEntryButton.UIBestiaryEntryButton(), UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), UIBestiaryInfoItemLine.UIBestiaryInfoItemLine(), UIBestiaryNPCEntryPortrait.UIBestiaryNPCEntryPortrait(), UICharacterListItem.UICharacterListItem(), UICharacterNameButton.UICharacterNameButton(), UIClothStyleButton.UIClothStyleButton(), UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions(), UIDifficultyButton.UIDifficultyButton(), UIList.UIList(), UIProgressBar.UIProgressBar(), UISearchBar.UISearchBar(), UIVirtualKeyboard.UIVirtualKeyboard(), UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem(), UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem(), UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), UIWorldListItem.UIWorldListItem(), UIWorldLoad.UIWorldLoad(), UIList.Add(), UIResourcePackSelectionMenu.AddBackAndFolderButtons(), UIBestiaryTest.AddBackAndForwardButtons(), AWorkshopPublishInfoState< TPublishedObjectType >.AddBackButton(), UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu(), UIWorkshopHub.AddDescriptionPanel(), UIWorldCreation.AddDescriptionPanel(), AWorkshopPublishInfoState< TPublishedObjectType >.AddDescriptionPanel(), UIWorkshopHub.AddHorizontalSeparator(), UIWorldCreation.AddHorizontalSeparator(), AWorkshopPublishInfoState< TPublishedObjectType >.AddHorizontalSeparator(), CreativePowers.DifficultySliderPower.AddIndication(), AWorkshopPublishInfoState< TPublishedObjectType >.AddPublishButton(), UIBestiaryTest.AddSearchBar(), UICreativeInfiniteItemsDisplay.AddSearchBar(), UIBestiaryTest.AddSortAndFilterButtons(), UICreativeInfiniteItemsDisplay.AddSymetricalCogsPair(), AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList(), UIWorldCreation.AddWorldDifficultyOptions(), UIWorldCreation.AddWorldEvilOptions(), UIWorldCreation.AddWorldSizeOptions(), UIBestiaryEntryInfoPage.AppendBorderOverEverything(), UIResourcePack.BuildChildren(), UIBestiaryFilteringOptionsGrid.BuildContainer(), UIBestiarySortingOptionsGrid.BuildGrid(), UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents(), UIBestiaryTest.BuildPage(), UICharacterCreation.BuildPage(), UIReportsPage.BuildPage(), UIResourcePackInfoMenu.BuildPage(), UIResourcePackSelectionMenu.BuildPage(), UIWorldCreation.BuildPage(), UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents(), UIVirtualKeyboard.BuildSpaceBarArea(), UIBestiaryEntryInfoPage.CheckScrollBar(), UICharacterCreation.Click_CharInfo(), UICharacterCreation.Click_ClothStyles(), UICharacterCreation.Click_HairStyles(), UIManageControls.CreateBindingGroup(), UIManageControls.CreateElementGroup(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateInsturctionsPanel(), UICreativePowersMenu.CreateMainPowerStrip(), UIResourcePackSelectionMenu.CreateOffsetButton(), UIResourcePackSelectionMenu.CreatePackInfoButton(), UIResourcePackSelectionMenu.CreatePackToggleButton(), AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), NPCPortraitInfoElement.CreateStarsContainer(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), CreativePowers.FreezeTime.CustomizeButton(), CreativePowers.FreezeWindDirectionAndStrength.CustomizeButton(), CreativePowers.FreezeRainPower.CustomizeButton(), CreativePowers.StopBiomeSpreadPower.CustomizeButton(), UIVirtualKeyboard.DrawSelf(), UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), UIBestiaryTest.FillProgressBottomBar(), CreativePowers.APerPlayerSliderPower.GetOptionButton(), CreativePowers.ASharedSliderPower.GetOptionButton(), UIAchievementsMenu.InitializePage(), UICreativePowersMenu.InitializePage(), UIEmotesMenu.InitializePage(), UICharacterCreation.MakeBackAndCreatebuttons(), UIWorldCreation.MakeBackAndCreatebuttons(), UICharacterCreation.MakeCategoriesBar(), UICharacterCreation.MakeCharPreview(), UICharacterCreation.MakeClothStylesMenu(), UIBestiaryTest.MakeExitButton(), UIWorkshopHub.MakeFancyButton(), UICharacterCreation.MakeHairsylesMenu(), UICharacterCreation.MakeHSLMenu(), UICharacterCreation.MakeInfoMenu(), UIWorldCreation.MakeInfoMenu(), UIBestiaryEntryButton.MouseOut(), UIBestiaryEntryButton.MouseOver(), AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize(), UICharacterSelect.OnInitialize(), UIManageControls.OnInitialize(), UIWorkshopHub.OnInitialize(), UIWorkshopSelectResourcePackToPublish.OnInitialize(), UIWorkshopSelectWorldToPublish.OnInitialize(), UIWorkshopWorldImport.OnInitialize(), OnInitialize(), UIBestiaryTest.OpenOrCloseFilteringGrid(), UIBestiaryTest.OpenOrCloseSortingOptions(), UIReportsPage.PopulateLogs(), UIResourcePackSelectionMenu.PopulatePackList(), CreativePowers.APerPlayerTogglePower.ProvidePowerButtons(), CreativePowers.ASharedButtonPower.ProvidePowerButtons(), CreativePowers.ModifyTimeRate.ProvideSlider(), CreativePowers.DifficultySliderPower.ProvideSlider(), CreativePowers.ModifyWindDirectionAndStrength.ProvideSlider(), CreativePowers.ModifyRainPower.ProvideSlider(), CreativePowers.SpawnRateSliderPerPlayerPower.ProvideSlider(), FilterProviderInfoElement.ProvideUIElement(), FlavorTextBestiaryInfoElement.ProvideUIElement(), NamePlateInfoElement.ProvideUIElement(), NPCKillCounterInfoElement.ProvideUIElement(), NPCPortraitInfoElement.ProvideUIElement(), NPCStatsReportInfoElement.ProvideUIElement(), UnlockProgressDisplayBestiaryInfoElement.ProvideUIElement(), UICharacterSelect.Recalculate(), UIEmotesMenu.Recalculate(), UIReportsPage.Recalculate(), UIResourcePackInfoMenu.Recalculate(), UIWorkshopSelectResourcePackToPublish.Recalculate(), UIWorkshopSelectWorldToPublish.Recalculate(), UIWorkshopWorldImport.Recalculate(), Recalculate(), UICreativePowersMenu.RefreshElementsOrder(), UICharacterCreation.SelectColorPicker(), GroupOptionButton< T >.SetText(), UIIconTextButton.SetText(), UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay_OnUpdate(), UIBestiaryFilteringOptionsGrid.UpdateAvailability(), and AWorkshopPublishInfoState< TPublishedObjectType >.UpdateScrollbar().