Terraria: UIElement.DrawDebugHitbox
DrawDebugHitbox()
void UIElement.DrawDebugHitbox (BasicDebugDrawer drawer, float colorIntensity = 0f) inline inherited
     {
         if (IsMouseHovering)
         {
             colorIntensity += 0.1f;
         }
         Color color = Main.hslToRgb(colorIntensity, colorIntensity, 0.5f);
         CalculatedStyle innerDimensions = GetInnerDimensions();
         drawer.DrawLine(innerDimensions.Position(), innerDimensions.Position() + new Vector2(innerDimensions.Width, 0f), 2f, color);
         drawer.DrawLine(innerDimensions.Position() + new Vector2(innerDimensions.Width, 0f), innerDimensions.Position() + new Vector2(innerDimensions.Width, innerDimensions.Height), 2f, color);
         drawer.DrawLine(innerDimensions.Position() + new Vector2(innerDimensions.Width, innerDimensions.Height), innerDimensions.Position() + new Vector2(0f, innerDimensions.Height), 2f, color);
         drawer.DrawLine(innerDimensions.Position() + new Vector2(0f, innerDimensions.Height), innerDimensions.Position(), 2f, color);
         foreach (UIElement element in Elements)
         {
             _ = element;
         }
     }
References Color, BasicDebugDrawer.DrawLine(), UIElement.Elements, UIElement.GetInnerDimensions(), CalculatedStyle.Height, Main.hslToRgb(), UIElement.IsMouseHovering, CalculatedStyle.Position(), and CalculatedStyle.Width.