Terraria: UIElement.SetSnapPoint
SetSnapPoint()
void UIElement.SetSnapPoint (string name, int id, Vector2? anchor = null, Vector2? offset = null) inline inherited
     {
         if (!anchor.HasValue)
         {
             anchor = new Vector2(0.5f);
         }
         if (!offset.HasValue)
         {
             offset = Vector2.Zero;
         }
         _snapPoint = new SnapPoint(name, id, anchor.Value, offset.Value);
     }
References UIElement._snapPoint.
Referenced by EmotesGroupListItem.EmotesGroupListItem(), PowerStripUIElement.PowerStripUIElement(), UICharacterListItem.UICharacterListItem(), UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions(), UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem(), UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem(), UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), UIWorldListItem.UIWorldListItem(), UIBestiaryTest.AddBackAndForwardButtons(), UIBestiaryTest.AddSearchBar(), UICreativeInfiniteItemsDisplay.AddSearchBar(), UIBestiaryTest.AddSortAndFilterButtons(), UIBestiarySortingOptionsGrid.BuildGrid(), UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents(), UICharacterCreation.CreateColorPicker(), UIManageControls.CreateElementGroup(), UICharacterCreation.CreateHSLSlider(), AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), UICharacterCreation.MakeCategoriesBar(), UICharacterCreation.MakeClothStylesMenu(), UIWorkshopHub.MakeFancyButton(), UICharacterCreation.MakeHairsylesMenu(), UICharacterCreation.MakeHSLMenu(), UICharacterCreation.MakeInfoMenu(), UIWorldCreation.MakeInfoMenu(), UIResourcePackSelectionMenu.PopulatePackList(), and UIBestiaryFilteringOptionsGrid.UpdateAvailability().