Terraria: UIElement.Recalculate
Recalculate()
virtual void UIElement.Recalculate () inline virtual inherited
Reimplemented in UIWorldSelect, UIWorkshopWorldImport, UIWorkshopSelectWorldToPublish, UIWorkshopSelectResourcePackToPublish, UIResourcePackInfoMenu, UIReportsPage, UIEmotesMenu, UICharacterSelect, UIBestiaryTest, AWorkshopPublishInfoState< TPublishedObjectType >, UITextPanel< T >, UIText, UIParticleLayer, UIList, UIGenProgressBar, UIDynamicItemCollection, UIBestiaryInfoLine< T >, UIBestiaryEntryInfoPage, and UIBestiaryEntryGrid.
     {
         CalculatedStyle parentDimensions = ((Parent == null) ? UserInterface.ActiveInstance.GetDimensions() : Parent.GetInnerDimensions());
         if (Parent != null && Parent is UIList)
         {
             parentDimensions.Height = float.MaxValue;
         }
         CalculatedStyle calculatedStyle = (_outerDimensions = GetDimensionsBasedOnParentDimensions(parentDimensions));
         calculatedStyle.X += MarginLeft;
         calculatedStyle.Y += MarginTop;
         calculatedStyle.Width -= MarginLeft + MarginRight;
         calculatedStyle.Height -= MarginTop + MarginBottom;
         _dimensions = calculatedStyle;
         calculatedStyle.X += PaddingLeft;
         calculatedStyle.Y += PaddingTop;
         calculatedStyle.Width -= PaddingLeft + PaddingRight;
         calculatedStyle.Height -= PaddingTop + PaddingBottom;
         _innerDimensions = calculatedStyle;
         RecalculateChildren();
     }
References UIElement._dimensions, UIElement._innerDimensions, UIElement._outerDimensions, UserInterface.ActiveInstance, UserInterface.GetDimensions(), UIElement.GetDimensionsBasedOnParentDimensions(), UIElement.GetInnerDimensions(), CalculatedStyle.Height, UIElement.MarginBottom, UIElement.MarginLeft, UIElement.MarginRight, UIElement.MarginTop, UIElement.PaddingBottom, UIElement.PaddingLeft, UIElement.PaddingRight, UIElement.PaddingTop, UIElement.Parent, UIElement.RecalculateChildren(), CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.
Referenced by UIProgressBar.UIProgressBar(), UIState.UIState(), UIWorldLoad(), UIList.Add(), UIElement.Append(), UIResourcePack.BuildChildren(), UIElement.CopyStyle(), UIManageControls.CreateBindingGroup(), UserInterface.Draw(), UIProgressBar.DrawSelf(), UIVirtualKeyboard.DrawSelf(), UIAchievementsMenu.FilterList(), UserInterface.Recalculate(), UIElement.RecalculateChildren(), UserInterface.RefreshState(), UserInterface.SetState(), Update(), UIWorldCreation.UpdateInputFields(), and UIVirtualKeyboard.UpdateOffsetDown().