Terraria: RandomizedFrameParticle.RandomizeFrame
RandomizeFrame()
void RandomizedFrameParticle.RandomizeFrame () inline private
     {
         _frame = _texture.Frame(1, AnimationFramesAmount, 0, Main.rand.Next(AnimationFramesAmount));
         _origin = _frame.Size() / 2f;
     }
References ABasicParticle._frame, ABasicParticle._origin, ABasicParticle._texture, AnimationFramesAmount, UnifiedRandom.Next(), and Main.rand.
Referenced by SetTypeInfo(), and Update().