Terraria: Program.SetupLogging
SetupLogging()
static void Program.SetupLogging () inline static private
     {
         if (LaunchParameters.ContainsKey("-logfile"))
         {
             string text = LaunchParameters["-logfile"];
             text = ((text != null && !(text.Trim() == "")) ? Path.Combine(text, $"Log_{DateTime.Now:yyyyMMddHHmmssfff}.log") : Path.Combine(SavePath, "Logs", $"Log_{DateTime.Now:yyyyMMddHHmmssfff}.log"));
             ConsoleOutputMirror.ToFile(text);
         }
         CrashWatcher.Inititialize();
         CrashWatcher.DumpOnException = LaunchParameters.ContainsKey("-minidump");
         CrashWatcher.LogAllExceptions = LaunchParameters.ContainsKey("-logerrors");
         if (LaunchParameters.ContainsKey("-fulldump"))
         {
             Console.WriteLine("Full Dump logs enabled.");
             CrashWatcher.EnableCrashDumps(CrashDump.Options.WithFullMemory);
         }
     }
References CrashWatcher.DumpOnException, CrashWatcher.EnableCrashDumps(), CrashWatcher.Inititialize(), LaunchParameters, CrashWatcher.LogAllExceptions, SavePath, and ConsoleOutputMirror.ToFile().
Referenced by LaunchGame().