Terraria: Program.RunGame
RunGame()
static void Program.RunGame () inline static
     {
         LanguageManager.Instance.SetLanguage(GameCulture.DefaultCulture);
         if (Platform.IsOSX)
         {
             Main.OnEngineLoad += delegate
             {
                 Main.instance.IsMouseVisible = false;
             };
         }
         using Main main = new Main();
         try
         {
             Lang.InitializeLegacyLocalization();
             SocialAPI.Initialize();
             LaunchInitializer.LoadParameters(main);
             Main.OnEnginePreload += StartForceLoad;
             if (Main.dedServ)
             {
                 main.DedServ();
             }
             main.Run();
         }
         catch (Exception e)
         {
             DisplayException(e);
         }
     }
References Main.dedServ, Main.DedServ(), GameCulture.DefaultCulture, DisplayException(), SocialAPI.Initialize(), Lang.InitializeLegacyLocalization(), LanguageManager.Instance, Main.instance, Game.IsMouseVisible, Platform.IsOSX, LaunchInitializer.LoadParameters(), Main.OnEngineLoad, Main.OnEnginePreload, Game.Run(), LanguageManager.SetLanguage(), and StartForceLoad().
Referenced by LaunchGame().