Terraria: Program.LaunchGame
LaunchGame()
static void Program.LaunchGame (string[] args, bool monoArgs = false) inline static
     {
         Thread.CurrentThread.Name = "Main Thread";
         if (monoArgs)
         {
             args = Utils.ConvertMonoArgsToDotNet(args);
         }
         if (IsFna)
         {
             TrySettingFNAToOpenGL(args);
         }
         LaunchParameters = Utils.ParseArguements(args);
         SavePath = (LaunchParameters.ContainsKey("-savedirectory") ? LaunchParameters["-savedirectory"] : Platform.Get<IPathService>().GetStoragePath("Terraria"));
         ThreadPool.SetMinThreads(8, 8);
         InitializeConsoleOutput();
         SetupLogging();
         Platform.Get<IWindowService>().SetQuickEditEnabled(false);
         RunGame();
     }
References Utils.ConvertMonoArgsToDotNet(), InitializeConsoleOutput(), IsFna, LaunchParameters, Utils.ParseArguements(), RunGame(), SavePath, SetupLogging(), and TrySettingFNAToOpenGL().
Referenced by WindowsLaunch.Main().