Terraria: Microsoft.Xna.Framework.Graphics.ProfileCapabilities.GetInstance
GetInstance()
static ProfileCapabilities Microsoft.Xna.Framework.Graphics.ProfileCapabilities.GetInstance (GraphicsProfile graphicsProfile) inline static package
Definition at line 282 of file ProfileCapabilities.cs.
    {
        return graphicsProfile switch
        {
            GraphicsProfile.Reach => Reach,
            GraphicsProfile.HiDef => HiDef,
            _ => throw new ArgumentOutOfRangeException("graphicsProfile"),
        };
    }
References Microsoft.Xna.Framework.Graphics.ProfileCapabilities.HiDef, and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.Reach.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), Microsoft.Xna.Framework.Graphics.ProfileChecker.IsProfileSupported(), and Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryFormat().