Terraria: Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException
ThrowNotSupportedException() [1/3]
void Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException (string message) inline package
Definition at line 292 of file ProfileCapabilities.cs.
    {
        throw new NotSupportedException(string.Format(CultureInfo.CurrentCulture, message, new object[1] { Profile }));
    }
References System.Globalization.CultureInfo.CurrentCulture, and System.Globalization.Format.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsDevice.GraphicsDevice(), Microsoft.Xna.Framework.Graphics.OcclusionQuery.OcclusionQuery(), Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.BlendState.Apply(), Microsoft.Xna.Framework.Graphics.IndexBuffer.CreateBuffer(), Microsoft.Xna.Framework.Graphics.VertexBuffer.CreateBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateDevice(), Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode(), Microsoft.Xna.Framework.Graphics.DeclarationManager.CreateNativeDeclaration(), Microsoft.Xna.Framework.Graphics.Texture3D.CreateTexture(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers(), Microsoft.Xna.Framework.Graphics.VertexElementValidator.Validate(), Microsoft.Xna.Framework.Graphics.TextureCube.ValidateCreationParameters(), Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VerifyCanDraw().