Terraria: System.Runtime.Serialization.DictionaryGlobals.SchemaInstanceNamespace
SchemaInstanceNamespace
readonly XmlDictionaryString System.Runtime.Serialization.DictionaryGlobals.SchemaInstanceNamespace = s_dictionary.Add("http://www.w3.org/2001/XMLSchema-instance") static
Definition at line 9 of file DictionaryGlobals.cs.
Referenced by System.Runtime.Serialization.XmlObjectSerializerWriteContext.HandleGraphAtTopLevel(), System.Runtime.Serialization.XmlObjectSerializerWriteContextComplex.OnHandleReference(), System.Runtime.Serialization.Attributes.Read(), System.Runtime.Serialization.XmlObjectSerializer.WriteNull(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo(), and System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo().