Terraria: IPCBase.ReadCallback
ReadCallback()
virtual void IPCBase.ReadCallback (IAsyncResult result) inline virtual
Reimplemented in IPCServer, and IPCClient.
     {
         WeGameHelper.WriteDebugString("ReadCallback: " + Thread.CurrentThread.ManagedThreadId);
         IPCContent iPCContent = (IPCContent)result.AsyncState;
         try
         {
             int num = _pipeStream.EndRead(result);
             if (!iPCContent.CancelToken.IsCancellationRequested)
             {
                 if (num > 0)
                 {
                     _totalData.AddRange(iPCContent.data.Take(num));
                     if (_pipeStream.IsMessageComplete)
                     {
                         AddPackToList(_totalData);
                         _totalData = new List<byte>();
                     }
                 }
             }
             else
             {
                 WeGameHelper.WriteDebugString("IPCBase.ReadCallback.cancel");
             }
         }
         catch (IOException ex)
         {
             _pipeBrokenFlag = true;
             WeGameHelper.WriteDebugString("ReadCallback Exception, {0}", ex.Message);
         }
         catch (InvalidOperationException ex2)
         {
             _pipeBrokenFlag = true;
             WeGameHelper.WriteDebugString("ReadCallback Exception, {0}", ex2.Message);
         }
     }
References _pipeStream, _totalData, AddPackToList(), IPCContent.CancelToken, IPCContent.data, and WeGameHelper.WriteDebugString().
Referenced by BeginReadData().