Terraria: System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.InterfaceImplTableReader
InterfaceImplTableReader()
System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.InterfaceImplTableReader (int numberOfRows, bool declaredSorted, int typeDefTableRowRefSize, int typeDefOrRefRefSize, MemoryBlock containingBlock, int containingBlockOffset) inline package
Definition at line 21 of file InterfaceImplTableReader.cs.
    {
        NumberOfRows = numberOfRows;
        _IsTypeDefTableRowRefSizeSmall = typeDefTableRowRefSize == 2;
        _IsTypeDefOrRefRefSizeSmall = typeDefOrRefRefSize == 2;
        _ClassOffset = 0;
        _InterfaceOffset = _ClassOffset + typeDefTableRowRefSize;
        RowSize = _InterfaceOffset + typeDefOrRefRefSize;
        Block = containingBlock.GetMemoryBlockAt(containingBlockOffset, RowSize * numberOfRows);
        if (!declaredSorted && !CheckSorted())
        {
            Throw.TableNotSorted(TableIndex.InterfaceImpl);
        }
    }
References System.Reflection.Metadata.Ecma335.InterfaceImplTableReader._ClassOffset, System.Reflection.Metadata.Ecma335.InterfaceImplTableReader._InterfaceOffset, System.Reflection.Metadata.Ecma335.InterfaceImplTableReader._IsTypeDefOrRefRefSizeSmall, System.Reflection.Metadata.Ecma335.InterfaceImplTableReader._IsTypeDefTableRowRefSizeSmall, System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.Block, System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.CheckSorted(), System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.InterfaceImplTableReader.RowSize, and System.Reflection.Throw.TableNotSorted().