Terraria: System.Data.NameNode.Eval
Eval() [2/3]
override object System.Data.NameNode.Eval (DataRow row, DataRowVersion version) inline package
Definition at line 77 of file NameNode.cs.
    {
        if (!_found)
        {
            throw ExprException.UnboundName(_name);
        }
        if (row == null)
        {
            if (IsTableConstant())
            {
                return _column.DataExpression.Evaluate();
            }
            throw ExprException.UnboundName(_name);
        }
        return _column[row.GetRecordFromVersion(version)];
    }
References System.Data.NameNode._column, System.Data.NameNode._found, System.Data.NameNode._name, System.Data.DataColumn.DataExpression, System.Data.DataExpression.Evaluate(), System.Data.NameNode.IsTableConstant(), and System.Data.ExprException.UnboundName().