Terraria: System.Data.NameNode.ParseName
ParseName()
static string System.Data.NameNode.ParseName (char[] text, int start, int pos) inline static package
Definition at line 150 of file NameNode.cs.
    {
        char c = '\0';
        string text2 = string.Empty;
        int num = start;
        int num2 = pos;
        checked
        {
            if (text[start] == '`')
            {
                start++;
                pos--;
                c = '\\';
                text2 = "`";
            }
            else if (text[start] == '[')
            {
                start++;
                pos--;
                c = '\\';
                text2 = "]\\";
            }
        }
        if (c != 0)
        {
            int num3 = start;
            for (int i = start; i < pos; i++)
            {
                if (text[i] == c && i + 1 < pos && text2.Contains(text[i + 1]))
                {
                    i++;
                }
                text[num3] = text[i];
                num3++;
            }
            pos = num3;
        }
        if (pos == start)
        {
            throw ExprException.InvalidName(new string(text, num, num2 - num));
        }
        return new string(text, start, pos - start);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Data.ExprException.InvalidName(), System.start, and System.text.
Referenced by System.Data.NameNode.NameNode(), System.Data.ExpressionParser.Parse(), and System.Data.ExpressionParser.ParseAggregateArgument().