Terraria: System.Data.NameNode.Bind
Bind()
override void System.Data.NameNode.Bind (DataTable table, List< DataColumn > list) inline package
Definition at line 29 of file NameNode.cs.
    {
        BindTable(table);
        if (table == null)
        {
            throw ExprException.UnboundName(_name);
        }
        try
        {
            _column = table.Columns[_name];
        }
        catch (Exception e)
        {
            _found = false;
            if (!ADP.IsCatchableExceptionType(e))
            {
                throw;
            }
            throw ExprException.UnboundName(_name);
        }
        if (_column == null)
        {
            throw ExprException.UnboundName(_name);
        }
        _name = _column.ColumnName;
        _found = true;
        int i;
        for (i = 0; i < list.Count; i++)
        {
            DataColumn dataColumn = list[i];
            if (_column == dataColumn)
            {
                break;
            }
        }
        if (i >= list.Count)
        {
            list.Add(_column);
        }
    }
References System.Data.NameNode._column, System.Data.NameNode._found, System.Data.NameNode._name, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ExpressionNode.BindTable(), System.Data.DataColumn.ColumnName, System.Data.DataTable.Columns, System.Data.Common.ADP.IsCatchableExceptionType(), System.list, System.Data.ExpressionNode.table, and System.Data.ExprException.UnboundName().