Terraria: System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction
RunOrScheduleAction() [2/2]
static void System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (IAsyncStateMachineBox box, bool allowInlining) inline static package inherited
Definition at line 177 of file AwaitTaskContinuation.cs.
    {
        Task t_currentTask = Task.t_currentTask;
        if (!allowInlining || !IsValidLocationForInlining)
        {
            if (TplEventSource.Log.IsEnabled())
            {
                UnsafeScheduleAction(box.MoveNextAction, t_currentTask);
            }
            else
            {
                ThreadPool.UnsafeQueueUserWorkItemInternal(box, preferLocal: true);
            }
            return;
        }
        try
        {
            if (t_currentTask != null)
            {
                Task.t_currentTask = null;
            }
            box.MoveNext();
        }
        catch (Exception exception)
        {
            Task.ThrowAsync(exception, null);
        }
        finally
        {
            if (t_currentTask != null)
            {
                Task.t_currentTask = t_currentTask;
            }
        }
    }
References System.exception, System.Threading.Tasks.AwaitTaskContinuation.IsValidLocationForInlining, System.Threading.Tasks.TplEventSource.Log, System.Runtime.CompilerServices.IAsyncStateMachineBox.MoveNext(), System.Runtime.CompilerServices.IAsyncStateMachineBox.MoveNextAction, System.Threading.Tasks.Task< TResult >.t_currentTask, System.Threading.Tasks.Task< TResult >.ThrowAsync(), System.Threading.ThreadPool.UnsafeQueueUserWorkItemInternal(), and System.Threading.Tasks.AwaitTaskContinuation.UnsafeScheduleAction().