Terraria: System.Xml.XPath.XPathNodeIterator.Clone
Clone() [1/2]
object ICloneable. System.Xml.XPath.XPathNodeIterator.Clone () inline private
Implements System.ICloneable.
Definition at line 93 of file XPathNodeIterator.cs.
    {
        return Clone();
    }
References System.Xml.XPath.XPathNodeIterator.Clone().
Referenced by System.Xml.XPath.XPathNodeIterator.Enumerator.Enumerator(), MS.Internal.Xml.XPath.IteratorFilter.IteratorFilter(), MS.Internal.Xml.XPath.XPathMultyIterator.XPathMultyIterator(), System.Xml.XPath.XPathNodeIterator.Clone(), System.Xml.Xsl.XsltOld.XsltCompileContext.FuncKey.Invoke(), System.Xml.XPath.XPathNodeIterator.Enumerator.MoveNext(), and MS.Internal.Xml.XPath.ExtensionQuery.ProcessResult().