Terraria: System.Net.Mail.MailAddress.GetAddress
GetAddress()
string System.Net.Mail.MailAddress.GetAddress (bool allowUnicode) inline private
Definition at line 147 of file MailAddress.cs.
    {
        return GetUser(allowUnicode) + "@" + GetHost(allowUnicode);
    }
References System.Net.Mail.MailAddress.GetHost(), and System.Net.Mail.MailAddress.GetUser().
Referenced by System.Net.Mail.MailAddress.Encode(), and System.Net.Mail.MailAddress.GetSmtpAddress().