Terraria: System.Net.Mail.MailAddress.Encode
Encode()
string System.Net.Mail.MailAddress.Encode (int charsConsumed, bool allowUnicode) inline package
Definition at line 180 of file MailAddress.cs.
    {
        string empty = string.Empty;
        if (!string.IsNullOrEmpty(_displayName))
        {
            if (MimeBasePart.IsAscii(_displayName, permitCROrLF: false) || allowUnicode)
            {
                empty = "\"" + _displayName + "\"";
            }
            else
            {
                IEncodableStream encoderForHeader = s_encoderFactory.GetEncoderForHeader(_displayNameEncoding, useBase64Encoding: false, charsConsumed);
                encoderForHeader.EncodeString(_displayName, _displayNameEncoding);
                empty = encoderForHeader.GetEncodedString();
            }
            return empty + " " + GetSmtpAddress(allowUnicode);
        }
        return GetAddress(allowUnicode);
    }
References System.Net.Mail.MailAddress._displayName, System.Net.Mail.MailAddress._displayNameEncoding, System.Net.Mime.IEncodableStream.EncodeString(), System.Net.Mail.MailAddress.GetAddress(), System.Net.Mime.IEncodableStream.GetEncodedString(), System.Net.Mail.MailAddress.GetSmtpAddress(), System.Net.Mime.MimeBasePart.IsAscii(), and System.Net.Mail.MailAddress.s_encoderFactory.
Referenced by System.Net.Mail.MailAddressCollection.Encode(), System.Net.Mail.Message.PrepareEnvelopeHeaders(), and System.Net.Mail.Message.PrepareHeaders().