Terraria: System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitCatchBlock
VisitCatchBlock()
override CatchBlock System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitCatchBlock (CatchBlock node) inline protected virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 65 of file QuoteInstruction.cs.
        {
            if (node.Variable != null)
            {
                _shadowedVars.Push(new HashSet<ParameterExpression> { node.Variable });
            }
            Expression expression = Visit(node.Body);
            Expression expression2 = Visit(node.Filter);
            if (node.Variable != null)
            {
                _shadowedVars.Pop();
            }
            if (expression == node.Body && expression2 == node.Filter)
            {
                return node;
            }
            return Expression.MakeCatchBlock(node.Test, node.Variable, expression, expression2);
        }
References System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter._shadowedVars, System.Linq.Expressions.Expression< TDelegate >.MakeCatchBlock(), System.Collections.Generic.Stack< T >.Pop(), System.Collections.Generic.Stack< T >.Push(), and System.Linq.Expressions.ExpressionVisitor.Visit().