Terraria: System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitRuntimeVariables
VisitRuntimeVariables()
override Expression System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.VisitRuntimeVariables (RuntimeVariablesExpression node) inline package virtual
Reimplemented from System.Linq.Expressions.ExpressionVisitor.
Definition at line 84 of file QuoteInstruction.cs.
        {
            int count = node.Variables.Count;
            List<IStrongBox> list = new List<IStrongBox>();
            List<ParameterExpression> list2 = new List<ParameterExpression>();
            int[] array = new int[count];
            for (int i = 0; i < array.Length; i++)
            {
                IStrongBox box = GetBox(node.Variables[i]);
                if (box == null)
                {
                    array[i] = list2.Count;
                    list2.Add(node.Variables[i]);
                }
                else
                {
                    array[i] = -1 - list.Count;
                    list.Add(box);
                }
            }
            if (list.Count == 0)
            {
                return node;
            }
            ConstantExpression constantExpression = Expression.Constant(new RuntimeOps.RuntimeVariables(list.ToArray()), typeof(IRuntimeVariables));
            if (list2.Count == 0)
            {
                return constantExpression;
            }
            return Expression.Invoke(Expression.Constant(new Func<IRuntimeVariables, IRuntimeVariables, int[], IRuntimeVariables>(MergeRuntimeVariables)), Expression.RuntimeVariables(new TrueReadOnlyCollection<ParameterExpression>(list2.ToArray())), constantExpression, Expression.Constant(array));
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Linq.Expressions.Expression< TDelegate >.Constant(), System.Linq.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.GetBox(), System.Linq.Expressions.Expression< TDelegate >.Invoke(), System.list, System.Linq.Expressions.Interpreter.QuoteInstruction.ExpressionQuoter.MergeRuntimeVariables(), and System.Linq.Expressions.Expression< TDelegate >.RuntimeVariables().