Terraria: System.Net.Mail.MailAddress.GetHost
GetHost()
string System.Net.Mail.MailAddress.GetHost (bool allowUnicode) inline private
Definition at line 129 of file MailAddress.cs.
    {
        string text = _host;
        if (!allowUnicode && !MimeBasePart.IsAscii(text, permitCROrLF: true))
        {
            IdnMapping idnMapping = new IdnMapping();
            try
            {
                text = idnMapping.GetAscii(text);
            }
            catch (ArgumentException innerException)
            {
                throw new SmtpException(System.SR.Format(System.SR.SmtpInvalidHostName, Address), innerException);
            }
        }
        return text;
    }
References System.Net.Mail.MailAddress._host, System.Net.Mail.MailAddress.Address, System.SR.Format(), System.Globalization.IdnMapping.GetAscii(), System.Net.Mime.MimeBasePart.IsAscii(), System.SR.SmtpInvalidHostName, and System.text.
Referenced by System.Net.Mail.MailAddress.GetAddress().