Terraria: System.Net.Mail.MailAddress.TryParse
TryParse()
static bool System.Net.Mail.MailAddress.TryParse (string address, string displayName, Encoding displayNameEncoding, out(string displayName, string user, string host, Encoding displayNameEncoding) parsedData, bool throwExceptionIfFail) inline static private
Definition at line 76 of file MailAddress.cs.
    {
        if (string.IsNullOrEmpty(address))
        {
            if (throwExceptionIfFail)
            {
                throw (address == null) ? new ArgumentNullException("address") : new ArgumentException(System.SR.Format(System.SR.net_emptystringcall, "address"), "address");
            }
            parsedData = default((string, string, string, Encoding));
            return false;
        }
        if (displayNameEncoding == null)
        {
            displayNameEncoding = Encoding.GetEncoding("utf-8");
        }
        if (displayName == null)
        {
            displayName = string.Empty;
        }
        if (!string.IsNullOrEmpty(displayName))
        {
            if (!MailAddressParser.TryNormalizeOrThrow(displayName, out displayName, throwExceptionIfFail))
            {
                parsedData = default((string, string, string, Encoding));
                return false;
            }
            if (displayName.Length >= 2 && displayName[0] == '"' && displayName[^1] == '"')
            {
                displayName = displayName.Substring(1, displayName.Length - 2);
            }
        }
        if (!MailAddressParser.TryParseAddress(address, out var parsedAddress, throwExceptionIfFail))
        {
            parsedData = default((string, string, string, Encoding));
            return false;
        }
        if (string.IsNullOrEmpty(displayName))
        {
            displayName = parsedAddress.DisplayName;
        }
        parsedData = (displayName: displayName, user: parsedAddress.User, host: parsedAddress.Host, displayNameEncoding: displayNameEncoding);
        return true;
    }
References System.SR.Format(), System.Text.Encoding.GetEncoding(), System.SR.net_emptystringcall, System.Net.Mail.MailAddressParser.TryNormalizeOrThrow(), and System.Net.Mail.MailAddressParser.TryParseAddress().
Referenced by System.Net.Mail.MailAddress.MailAddress(), and System.Net.Mail.MailAddress.TryCreate().