Terraria: System.Net.Mail.MailAddress.GetSmtpAddress
GetSmtpAddress()
string System.Net.Mail.MailAddress.GetSmtpAddress (bool allowUnicode) inline package
Definition at line 152 of file MailAddress.cs.
    {
        return "<" + GetAddress(allowUnicode) + ">";
    }
References System.Net.Mail.MailAddress.GetAddress().
Referenced by System.Net.Mail.MailAddress.Encode(), System.Net.Mail.MailCommand.PrepareCommand(), and System.Net.Mail.SmtpClient.ValidateUnicodeRequirement().