Terraria: System.Net.Mail.MailAddress.GetUser
GetUser()
string System.Net.Mail.MailAddress.GetUser (bool allowUnicode) inline private
Definition at line 120 of file MailAddress.cs.
    {
        if (!allowUnicode && !MimeBasePart.IsAscii(_userName, permitCROrLF: true))
        {
            throw new SmtpException(System.SR.Format(System.SR.SmtpNonAsciiUserNotSupported, Address));
        }
        return _userName;
    }
References System.Net.Mail.MailAddress._userName, System.Net.Mail.MailAddress.Address, System.SR.Format(), System.Net.Mime.MimeBasePart.IsAscii(), and System.SR.SmtpNonAsciiUserNotSupported.
Referenced by System.Net.Mail.MailAddress.GetAddress().