Terraria: Terraria.GameContent.Biomes.GraniteBiome.Magma.Magma
Magma()
Terraria.GameContent.Biomes.GraniteBiome.Magma.Magma (double pressure, double resistance, bool active) inline private
        {
            Pressure = pressure;
            Resistance = resistance;
            IsActive = active;
        }
References Terraria.GameContent.Biomes.GraniteBiome.Magma.IsActive, Terraria.GameContent.Biomes.GraniteBiome.Magma.Pressure, and Terraria.GameContent.Biomes.GraniteBiome.Magma.Resistance.
Referenced by Terraria.GameContent.Biomes.GraniteBiome.Magma.CreateEmpty(), Terraria.GameContent.Biomes.GraniteBiome.Magma.CreateFlow(), and Terraria.GameContent.Biomes.GraniteBiome.Magma.ToFlow().