Terraria: System.Diagnostics.Tracing.TypeAnalysis.TypeAnalysis
TypeAnalysis()
System.Diagnostics.Tracing.TypeAnalysis.TypeAnalysis (Type dataType, EventDataAttribute eventAttrib, List< Type > recursionCheck) inline
Definition at line 22 of file TypeAnalysis.cs.
    {
        List<PropertyAnalysis> list = new List<PropertyAnalysis>();
        PropertyInfo[] array = dataType.GetProperties();
        foreach (PropertyInfo propertyInfo in array)
        {
            if (!Statics.HasCustomAttribute(propertyInfo, typeof(EventIgnoreAttribute)) && propertyInfo.CanRead && propertyInfo.GetIndexParameters().Length == 0)
            {
                MethodInfo getMethod = propertyInfo.GetGetMethod();
                if (!(getMethod == null) && !getMethod.IsStatic && getMethod.IsPublic)
                {
                    Type propertyType = propertyInfo.PropertyType;
                    TraceLoggingTypeInfo instance = TraceLoggingTypeInfo.GetInstance(propertyType, recursionCheck);
                    EventFieldAttribute customAttribute = Statics.GetCustomAttribute<EventFieldAttribute>(propertyInfo);
                    string text = ((customAttribute != null && customAttribute.Name != null) ? customAttribute.Name : (Statics.ShouldOverrideFieldName(propertyInfo.Name) ? instance.Name : propertyInfo.Name));
                    list.Add(new PropertyAnalysis(text, propertyInfo, instance, customAttribute));
                }
            }
        }
        properties = list.ToArray();
        PropertyAnalysis[] array2 = properties;
        foreach (PropertyAnalysis propertyAnalysis in array2)
        {
            TraceLoggingTypeInfo typeInfo = propertyAnalysis.typeInfo;
            level = (EventLevel)Statics.Combine((int)typeInfo.Level, (int)level);
            opcode = (EventOpcode)Statics.Combine((int)typeInfo.Opcode, (int)opcode);
            keywords |= typeInfo.Keywords;
            tags |= typeInfo.Tags;
        }
        if (eventAttrib != null)
        {
            level = (EventLevel)Statics.Combine((int)eventAttrib.Level, (int)level);
            opcode = (EventOpcode)Statics.Combine((int)eventAttrib.Opcode, (int)opcode);
            keywords |= eventAttrib.Keywords;
            tags |= eventAttrib.Tags;
            name = eventAttrib.Name;
        }
        if (name == null)
        {
            name = dataType.Name;
        }
    }
References System.array, System.Reflection.PropertyInfo.CanRead, System.Diagnostics.Tracing.Statics.Combine(), System.Reflection.PropertyInfo.GetGetMethod(), System.Reflection.PropertyInfo.GetIndexParameters(), System.Diagnostics.Tracing.TraceLoggingTypeInfo.GetInstance(), System.Type.GetProperties(), System.Diagnostics.Tracing.Statics.HasCustomAttribute(), System.Diagnostics.Tracing.TraceLoggingTypeInfo.Keywords, System.Diagnostics.Tracing.TypeAnalysis.keywords, System.Diagnostics.Tracing.TraceLoggingTypeInfo.Level, System.Diagnostics.Tracing.TypeAnalysis.level, System.list, System.Diagnostics.Tracing.TypeAnalysis.name, System.Reflection.MemberInfo.Name, System.Diagnostics.Tracing.TraceLoggingTypeInfo.Opcode, System.Diagnostics.Tracing.TypeAnalysis.opcode, System.Diagnostics.Tracing.TypeAnalysis.properties, System.Reflection.PropertyInfo.PropertyType, System.Diagnostics.Tracing.Statics.ShouldOverrideFieldName(), System.Diagnostics.Tracing.TraceLoggingTypeInfo.Tags, System.Diagnostics.Tracing.TypeAnalysis.tags, and System.text.