Terraria: System.Reflection.Internal.ExceptionUtilities.UnexpectedValue
UnexpectedValue()
static Exception System.Reflection.Internal.ExceptionUtilities.UnexpectedValue (object value) inline static package
Definition at line 7 of file ExceptionUtilities.cs.
    {
        if (value != null && value.GetType().FullName != null)
        {
            return new InvalidOperationException(System.SR.Format(System.SR.UnexpectedValue, value, value.GetType().FullName));
        }
        return new InvalidOperationException(System.SR.Format(System.SR.UnexpectedValueUnknownType, value));
    }
References System.SR.Format(), System.SR.UnexpectedValue, System.SR.UnexpectedValueUnknownType, and System.value.
Referenced by System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualHandleMemoryBlock(), System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualHandleString(), and System.Reflection.Metadata.Ecma335.MetadataReaderExtensions.ResolveSignatureTypeKind().