Terraria: Terraria.GameContent.Skies.AmbientSky.ButterfliesSkyEntity.ButterfliesSkyEntity
ButterfliesSkyEntity()
Terraria.GameContent.Skies.AmbientSky.ButterfliesSkyEntity.ButterfliesSkyEntity (Player player, FastRandom random) inline
Definition at line 188 of file AmbientSky.cs.
        {
            VirtualCamera virtualCamera = new VirtualCamera(player);
            Effects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
            int num = 100;
            if (Effects == SpriteEffects.FlipHorizontally)
            {
                Position.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
            }
            else
            {
                Position.X = virtualCamera.Position.X - (float)num;
            }
            Position.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 4000f) + 4000f;
            Depth = random.NextFloat() * 3f + 3f;
            SetPositionInWorldBasedOnScreenSpace(Position);
            int num2 = random.Next(2) + 1;
            Texture = Main.Assets.Request<Texture2D>("Images/Backgrounds/Ambience/ButterflySwarm" + num2, (AssetRequestMode)1);
            Frame = new SpriteFrame(1, (byte)((num2 == 2) ? 19u : 17u));
            LifeTime = random.Next(60, 121) * 60;
            OpacityNormalizedTimeToFadeIn = 0.15f;
            OpacityNormalizedTimeToFadeOut = 0.85f;
            BrightnessLerper = 0.2f;
            FinalOpacityMultiplier = 1f;
            FramingSpeed = 5;
        }
References Terraria.Main.Assets, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.BrightnessLerper, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Depth, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Frame, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FramingSpeed, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.LifeTime, Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextFloat(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Position, Terraria.GameContent.Skies.AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.Texture, and Terraria.Main.worldSurface.