Terraria: System.Xml.DocumentSchemaValidator.ValidateElement
ValidateElement()
void System.Xml.DocumentSchemaValidator.ValidateElement () inline private
Definition at line 312 of file DocumentSchemaValidator.cs.
    {
        _nsManager.PushScope();
        XmlElement xmlElement = _currentNode as XmlElement;
        XmlAttributeCollection attributes = xmlElement.Attributes;
        XmlAttribute xmlAttribute = null;
        string xsiNil = null;
        string xsiType = null;
        for (int i = 0; i < attributes.Count; i++)
        {
            xmlAttribute = attributes[i];
            string namespaceURI = xmlAttribute.NamespaceURI;
            string localName = xmlAttribute.LocalName;
            if (Ref.Equal(namespaceURI, _nsXsi))
            {
                if (Ref.Equal(localName, _xsiType))
                {
                    xsiType = xmlAttribute.Value;
                }
                else if (Ref.Equal(localName, _xsiNil))
                {
                    xsiNil = xmlAttribute.Value;
                }
            }
            else if (Ref.Equal(namespaceURI, _nsXmlNs))
            {
                _nsManager.AddNamespace((xmlAttribute.Prefix.Length == 0) ? string.Empty : xmlAttribute.LocalName, xmlAttribute.Value);
            }
        }
        _validator.ValidateElement(xmlElement.LocalName, xmlElement.NamespaceURI, _schemaInfo, xsiType, xsiNil, null, null);
        ValidateAttributes(xmlElement);
        _validator.ValidateEndOfAttributes(_schemaInfo);
        for (XmlNode xmlNode = xmlElement.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            ValidateNode(xmlNode);
        }
        _currentNode = xmlElement;
        _validator.ValidateEndElement(_schemaInfo);
        if (_psviAugmentation)
        {
            xmlElement.XmlName = _document.AddXmlName(xmlElement.Prefix, xmlElement.LocalName, xmlElement.NamespaceURI, _schemaInfo);
            if (_schemaInfo.IsDefault)
            {
                XmlText newChild = _document.CreateTextNode(_schemaInfo.SchemaElement.ElementDecl.DefaultValueRaw);
                xmlElement.AppendChild(newChild);
            }
        }
        _nsManager.PopScope();
    }
References System.Xml.DocumentSchemaValidator._currentNode, System.Xml.DocumentSchemaValidator._document, System.Xml.DocumentSchemaValidator._nsManager, System.Xml.DocumentSchemaValidator._nsXmlNs, System.Xml.DocumentSchemaValidator._nsXsi, System.Xml.DocumentSchemaValidator._psviAugmentation, System.Xml.DocumentSchemaValidator._schemaInfo, System.Xml.DocumentSchemaValidator._validator, System.Xml.DocumentSchemaValidator._xsiNil, System.Xml.DocumentSchemaValidator._xsiType, System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlDocument.AddXmlName(), System.Xml.XmlAttributeCollection.Count, System.Xml.XmlDocument.CreateTextNode(), System.Xml.Schema.SchemaDeclBase.DefaultValueRaw, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaElement.ElementDecl, System.Xml.Ref.Equal(), System.Xml.Schema.XmlSchemaInfo.IsDefault, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XmlNamespaceManager.PushScope(), System.Xml.Schema.XmlSchemaInfo.SchemaElement, System.Xml.DocumentSchemaValidator.ValidateAttributes(), System.Xml.Schema.XmlSchemaValidator.ValidateElement(), System.Xml.Schema.XmlSchemaValidator.ValidateEndElement(), System.Xml.Schema.XmlSchemaValidator.ValidateEndOfAttributes(), and System.Xml.DocumentSchemaValidator.ValidateNode().
Referenced by System.Xml.DocumentSchemaValidator.ValidateNode().