Terraria: System.Xml.DocumentSchemaValidator.ValidateSingleElement
ValidateSingleElement()
void System.Xml.DocumentSchemaValidator.ValidateSingleElement (XmlElement elementNode, bool skipToEnd, XmlSchemaInfo newSchemaInfo) inline private
Definition at line 590 of file DocumentSchemaValidator.cs.
    {
        _nsManager.PushScope();
        XmlAttributeCollection attributes = elementNode.Attributes;
        XmlAttribute xmlAttribute = null;
        string xsiNil = null;
        string xsiType = null;
        for (int i = 0; i < attributes.Count; i++)
        {
            xmlAttribute = attributes[i];
            string namespaceURI = xmlAttribute.NamespaceURI;
            string localName = xmlAttribute.LocalName;
            if (Ref.Equal(namespaceURI, _nsXsi))
            {
                if (Ref.Equal(localName, _xsiType))
                {
                    xsiType = xmlAttribute.Value;
                }
                else if (Ref.Equal(localName, _xsiNil))
                {
                    xsiNil = xmlAttribute.Value;
                }
            }
            else if (Ref.Equal(namespaceURI, _nsXmlNs))
            {
                _nsManager.AddNamespace((xmlAttribute.Prefix.Length == 0) ? string.Empty : xmlAttribute.LocalName, xmlAttribute.Value);
            }
        }
        _validator.ValidateElement(elementNode.LocalName, elementNode.NamespaceURI, newSchemaInfo, xsiType, xsiNil, null, null);
        if (skipToEnd)
        {
            _validator.ValidateEndOfAttributes(newSchemaInfo);
            _validator.SkipToEndElement(newSchemaInfo);
            _nsManager.PopScope();
        }
    }
References System.Xml.DocumentSchemaValidator._nsManager, System.Xml.DocumentSchemaValidator._nsXmlNs, System.Xml.DocumentSchemaValidator._nsXsi, System.Xml.DocumentSchemaValidator._validator, System.Xml.DocumentSchemaValidator._xsiNil, System.Xml.DocumentSchemaValidator._xsiType, System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlAttributeCollection.Count, System.Xml.Ref.Equal(), System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XmlNamespaceManager.PushScope(), System.Xml.Schema.XmlSchemaValidator.SkipToEndElement(), System.Xml.Schema.XmlSchemaValidator.ValidateElement(), and System.Xml.Schema.XmlSchemaValidator.ValidateEndOfAttributes().
Referenced by System.Xml.DocumentSchemaValidator.GetTypeFromAncestors(), and System.Xml.DocumentSchemaValidator.ValidateChildrenTillNextAncestor().