Terraria: System.Xml.DocumentSchemaValidator.ValidateNode
ValidateNode()
void System.Xml.DocumentSchemaValidator.ValidateNode (XmlNode node) inline private
Definition at line 257 of file DocumentSchemaValidator.cs.
    {
        _currentNode = node;
        switch (_currentNode.NodeType)
        {
        case XmlNodeType.Document:
        {
            XmlElement documentElement = ((XmlDocument)node).DocumentElement;
            if (documentElement == null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.Xml_InvalidXmlDocument, System.SR.Xdom_NoRootEle));
            }
            ValidateNode(documentElement);
            break;
        }
        case XmlNodeType.EntityReference:
        case XmlNodeType.DocumentFragment:
        {
            for (XmlNode xmlNode = node.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
            {
                ValidateNode(xmlNode);
            }
            break;
        }
        case XmlNodeType.Element:
            ValidateElement();
            break;
        case XmlNodeType.Attribute:
        {
            XmlAttribute xmlAttribute = _currentNode as XmlAttribute;
            _validator.ValidateAttribute(xmlAttribute.LocalName, xmlAttribute.NamespaceURI, _nodeValueGetter, _attributeSchemaInfo);
            if (_psviAugmentation)
            {
                xmlAttribute.XmlName = _document.AddAttrXmlName(xmlAttribute.Prefix, xmlAttribute.LocalName, xmlAttribute.NamespaceURI, _attributeSchemaInfo);
            }
            break;
        }
        case XmlNodeType.Text:
            _validator.ValidateText(_nodeValueGetter);
            break;
        case XmlNodeType.CDATA:
            _validator.ValidateText(_nodeValueGetter);
            break;
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            _validator.ValidateWhitespace(_nodeValueGetter);
            break;
        default:
            throw new InvalidOperationException(System.SR.Format(System.SR.Xml_UnexpectedNodeType, _currentNode.NodeType));
        case XmlNodeType.ProcessingInstruction:
        case XmlNodeType.Comment:
            break;
        }
    }
References System.Xml.DocumentSchemaValidator._attributeSchemaInfo, System.Xml.DocumentSchemaValidator._currentNode, System.Xml.DocumentSchemaValidator._document, System.Xml.DocumentSchemaValidator._nodeValueGetter, System.Xml.DocumentSchemaValidator._psviAugmentation, System.Xml.DocumentSchemaValidator._validator, System.Xml.XmlDocument.AddAttrXmlName(), System.Xml.Dictionary, System.Xml.XmlNode.Document, System.SR.Format(), System.Xml.XmlNode.NodeType, System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), System.Xml.DocumentSchemaValidator.ValidateElement(), System.Xml.DocumentSchemaValidator.ValidateNode(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace(), System.SR.Xdom_NoRootEle, System.SR.Xml_InvalidXmlDocument, and System.SR.Xml_UnexpectedNodeType.
Referenced by System.Xml.DocumentSchemaValidator.Validate(), System.Xml.DocumentSchemaValidator.ValidateElement(), and System.Xml.DocumentSchemaValidator.ValidateNode().