Terraria: System.Xml.DocumentSchemaValidator.DocumentSchemaValidator
DocumentSchemaValidator()
System.Xml.DocumentSchemaValidator.DocumentSchemaValidator (XmlDocument ownerDocument, XmlSchemaSet schemas, ValidationEventHandler eventHandler) inline
Definition at line 72 of file DocumentSchemaValidator.cs.
    {
        _schemas = schemas;
        _eventHandler = eventHandler;
        _document = ownerDocument;
        _internalEventHandler = InternalValidationCallBack;
        _nameTable = _document.NameTable;
        _nsManager = new XmlNamespaceManager(_nameTable);
        _nodeValueGetter = GetNodeValue;
        _psviAugmentation = true;
        _nsXmlNs = _nameTable.Add("http://www.w3.org/2000/xmlns/");
        _nsXsi = _nameTable.Add("http://www.w3.org/2001/XMLSchema-instance");
        _xsiType = _nameTable.Add("type");
        _xsiNil = _nameTable.Add("nil");
    }
References System.Xml.DocumentSchemaValidator._document, System.Xml.DocumentSchemaValidator._eventHandler, System.Xml.DocumentSchemaValidator._internalEventHandler, System.Xml.DocumentSchemaValidator._nameTable, System.Xml.DocumentSchemaValidator._nodeValueGetter, System.Xml.DocumentSchemaValidator._nsManager, System.Xml.DocumentSchemaValidator._nsXmlNs, System.Xml.DocumentSchemaValidator._nsXsi, System.Xml.DocumentSchemaValidator._psviAugmentation, System.Xml.DocumentSchemaValidator._schemas, System.Xml.DocumentSchemaValidator._xsiNil, System.Xml.DocumentSchemaValidator._xsiType, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, System.Xml.DocumentSchemaValidator.GetNodeValue(), System.Xml.DocumentSchemaValidator.InternalValidationCallBack(), and System.Xml.XmlDocument.NameTable.