Terraria: System.Xml.DocumentSchemaValidator.GetNamespacesInScope
GetNamespacesInScope()
IDictionary< string, string > System.Xml.DocumentSchemaValidator.GetNamespacesInScope (XmlNamespaceScope scope) inline
Implements System.Xml.IXmlNamespaceResolver.
Definition at line 169 of file DocumentSchemaValidator.cs.
    {
        IDictionary<string, string> namespacesInScope = _nsManager.GetNamespacesInScope(scope);
        if (scope != XmlNamespaceScope.Local)
        {
            XmlNode xmlNode = _startNode;
            while (xmlNode != null)
            {
                switch (xmlNode.NodeType)
                {
                case XmlNodeType.Element:
                {
                    XmlElement xmlElement = (XmlElement)xmlNode;
                    if (xmlElement.HasAttributes)
                    {
                        XmlAttributeCollection attributes = xmlElement.Attributes;
                        for (int i = 0; i < attributes.Count; i++)
{
                            XmlAttribute xmlAttribute = attributes[i];
                            if (!Ref.Equal(xmlAttribute.NamespaceURI, _document.strReservedXmlns))
{
                                continue;
                            }
                            if (xmlAttribute.Prefix.Length == 0)
{
                                if (!namespacesInScope.ContainsKey(string.Empty))
{
                                    namespacesInScope.Add(string.Empty, xmlAttribute.Value);
                                }
                            }
                            else if (!namespacesInScope.ContainsKey(xmlAttribute.LocalName))
{
                                namespacesInScope.Add(xmlAttribute.LocalName, xmlAttribute.Value);
                            }
                        }
                    }
                    xmlNode = xmlNode.ParentNode;
                    break;
                }
                case XmlNodeType.Attribute:
                    xmlNode = ((XmlAttribute)xmlNode).OwnerElement;
                    break;
                default:
                    xmlNode = xmlNode.ParentNode;
                    break;
                }
            }
        }
        return namespacesInScope;
    }
References System.Xml.DocumentSchemaValidator._document, System.Xml.DocumentSchemaValidator._nsManager, System.Xml.DocumentSchemaValidator._startNode, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.XmlAttributeCollection.Count, System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.XmlNamespaceManager.GetNamespacesInScope(), and System.Xml.XmlDocument.strReservedXmlns.