Terraria: System.Xml.DocumentSchemaValidator.GetDefaultPrefix
GetDefaultPrefix()
string System.Xml.DocumentSchemaValidator.GetDefaultPrefix (string attributeNS) inline private
Definition at line 424 of file DocumentSchemaValidator.cs.
    {
        IDictionary<string, string> namespacesInScope = NamespaceResolver.GetNamespacesInScope(XmlNamespaceScope.All);
        string text = null;
        attributeNS = _nameTable.Add(attributeNS);
        foreach (KeyValuePair<string, string> item in namespacesInScope)
        {
            string text2 = _nameTable.Add(item.Value);
            if ((object)text2 == attributeNS)
            {
                text = item.Key;
                if (text.Length != 0)
                {
                    return text;
                }
            }
        }
        return text;
    }
References System.Xml.DocumentSchemaValidator._nameTable, System.Xml.XmlNameTable.Add(), System.Xml.IXmlNamespaceResolver.GetNamespacesInScope(), System.item, System.Xml.DocumentSchemaValidator.NamespaceResolver, and System.text.
Referenced by System.Xml.DocumentSchemaValidator.ValidateAttributes().