Terraria: System.Xml.DocumentSchemaValidator.CreateTypeFinderValidator
CreateTypeFinderValidator()
XmlSchemaValidator System.Xml.DocumentSchemaValidator.CreateTypeFinderValidator (XmlSchemaObject partialValidationType) inline private
Definition at line 658 of file DocumentSchemaValidator.cs.
    {
        XmlSchemaValidator xmlSchemaValidator = new XmlSchemaValidator(_document.NameTable, _document.Schemas, _nsManager, XmlSchemaValidationFlags.None);
        xmlSchemaValidator.ValidationEventHandler += TypeFinderCallBack;
        if (partialValidationType != null)
        {
            xmlSchemaValidator.Initialize(partialValidationType);
        }
        else
        {
            xmlSchemaValidator.Initialize();
        }
        return xmlSchemaValidator;
    }
References System.Xml.DocumentSchemaValidator._document, System.Xml.DocumentSchemaValidator._nsManager, System.Xml.Dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.Initialize(), System.Xml.XmlDocument.NameTable, System.Xml.XmlDocument.Schemas, and System.Xml.DocumentSchemaValidator.TypeFinderCallBack().
Referenced by System.Xml.DocumentSchemaValidator.GetTypeFromAncestors().