Terraria: System.Xml.DocumentSchemaValidator.CreateValidator
CreateValidator()
void System.Xml.DocumentSchemaValidator.CreateValidator (XmlSchemaObject partialValidationType, XmlSchemaValidationFlags validationFlags) inline private
Definition at line 240 of file DocumentSchemaValidator.cs.
    {
        _validator = new XmlSchemaValidator(_nameTable, _schemas, NamespaceResolver, validationFlags);
        _validator.SourceUri = XmlConvert.ToUri(_document.BaseURI);
        _validator.XmlResolver = null;
        _validator.ValidationEventHandler += _internalEventHandler;
        _validator.ValidationEventSender = this;
        if (partialValidationType != null)
        {
            _validator.Initialize(partialValidationType);
        }
        else
        {
            _validator.Initialize();
        }
    }
References System.Xml.DocumentSchemaValidator._document, System.Xml.DocumentSchemaValidator._internalEventHandler, System.Xml.DocumentSchemaValidator._nameTable, System.Xml.DocumentSchemaValidator._schemas, System.Xml.DocumentSchemaValidator._validator, System.Xml.XmlDocument.BaseURI, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.Initialize(), System.Xml.DocumentSchemaValidator.NamespaceResolver, and System.Xml.XmlConvert.ToUri().
Referenced by System.Xml.DocumentSchemaValidator.Validate().