Terraria: System.Xml.DocumentSchemaValidator.Validate
Validate()
bool System.Xml.DocumentSchemaValidator.Validate (XmlNode nodeToValidate) inline
Definition at line 88 of file DocumentSchemaValidator.cs.
    {
        XmlSchemaObject xmlSchemaObject = null;
        XmlSchemaValidationFlags xmlSchemaValidationFlags = XmlSchemaValidationFlags.AllowXmlAttributes;
        _startNode = nodeToValidate;
        XmlNodeType nodeType = nodeToValidate.NodeType;
        if (nodeType <= XmlNodeType.Attribute)
        {
            if (nodeType != XmlNodeType.Element)
            {
                if (nodeType != XmlNodeType.Attribute || nodeToValidate.XPNodeType == XPathNodeType.Namespace)
                {
                    goto IL_00fe;
                }
                xmlSchemaObject = nodeToValidate.SchemaInfo.SchemaAttribute;
                if (xmlSchemaObject == null)
                {
                    xmlSchemaObject = FindSchemaInfo(nodeToValidate as XmlAttribute);
                    if (xmlSchemaObject == null)
                    {
                        throw new XmlSchemaValidationException(System.SR.XmlDocument_NoNodeSchemaInfo, null, nodeToValidate);
                    }
                }
            }
            else
            {
                IXmlSchemaInfo schemaInfo = nodeToValidate.SchemaInfo;
                XmlSchemaElement schemaElement = schemaInfo.SchemaElement;
                if (schemaElement != null)
                {
                    xmlSchemaObject = (schemaElement.RefName.IsEmpty ? schemaElement : _schemas.GlobalElements[schemaElement.QualifiedName]);
                }
                else
                {
                    xmlSchemaObject = schemaInfo.SchemaType;
                    if (xmlSchemaObject == null)
                    {
                        if (nodeToValidate.ParentNode.NodeType == XmlNodeType.Document)
{
                            nodeToValidate = nodeToValidate.ParentNode;
                        }
                        else
{
                            xmlSchemaObject = FindSchemaInfo(nodeToValidate as XmlElement);
                            if (xmlSchemaObject == null)
{
                                throw new XmlSchemaValidationException(System.SR.XmlDocument_NoNodeSchemaInfo, null, nodeToValidate);
                            }
                        }
                    }
                }
            }
        }
        else if (nodeType != XmlNodeType.Document)
        {
            if (nodeType != XmlNodeType.DocumentFragment)
            {
                goto IL_00fe;
            }
        }
        else
        {
            xmlSchemaValidationFlags |= XmlSchemaValidationFlags.ProcessIdentityConstraints;
        }
        _isValid = true;
        CreateValidator(xmlSchemaObject, xmlSchemaValidationFlags);
        if (_psviAugmentation)
        {
            if (_schemaInfo == null)
            {
                _schemaInfo = new XmlSchemaInfo();
            }
            _attributeSchemaInfo = new XmlSchemaInfo();
        }
        ValidateNode(nodeToValidate);
        _validator.EndValidation();
        return _isValid;
        IL_00fe:
        throw new InvalidOperationException(System.SR.Format(System.SR.XmlDocument_ValidateInvalidNodeType, null));
    }
References System.Xml.DocumentSchemaValidator._attributeSchemaInfo, System.Xml.DocumentSchemaValidator._isValid, System.Xml.DocumentSchemaValidator._psviAugmentation, System.Xml.DocumentSchemaValidator._schemaInfo, System.Xml.DocumentSchemaValidator._schemas, System.Xml.DocumentSchemaValidator._startNode, System.Xml.DocumentSchemaValidator._validator, System.Xml.DocumentSchemaValidator.CreateValidator(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.EndValidation(), System.Xml.DocumentSchemaValidator.FindSchemaInfo(), System.SR.Format(), System.Xml.Schema.XmlSchemaSet.GlobalElements, System.Xml.Schema.IXmlSchemaInfo.SchemaElement, System.Xml.Schema.IXmlSchemaInfo.SchemaType, System.Xml.DocumentSchemaValidator.ValidateNode(), System.SR.XmlDocument_NoNodeSchemaInfo, and System.SR.XmlDocument_ValidateInvalidNodeType.