Terraria: System.Xml.DocumentSchemaValidator.FindSchemaInfo
FindSchemaInfo() [2/2]
XmlSchemaObject System.Xml.DocumentSchemaValidator.FindSchemaInfo (XmlElement elementToValidate) inline private
Definition at line 449 of file DocumentSchemaValidator.cs.
    {
        _isPartialTreeValid = true;
        IXmlSchemaInfo xmlSchemaInfo = null;
        int num = 0;
        XmlNode parentNode = elementToValidate.ParentNode;
        do
        {
            xmlSchemaInfo = parentNode.SchemaInfo;
            if (xmlSchemaInfo.SchemaElement != null || xmlSchemaInfo.SchemaType != null)
            {
                break;
            }
            CheckNodeSequenceCapacity(num);
            _nodeSequenceToValidate[num++] = parentNode;
            parentNode = parentNode.ParentNode;
        }
        while (parentNode != null);
        if (parentNode == null)
        {
            num--;
            _nodeSequenceToValidate[num] = null;
            return GetTypeFromAncestors(elementToValidate, null, num);
        }
        CheckNodeSequenceCapacity(num);
        _nodeSequenceToValidate[num++] = parentNode;
        XmlSchemaObject xmlSchemaObject = xmlSchemaInfo.SchemaElement;
        if (xmlSchemaObject == null)
        {
            xmlSchemaObject = xmlSchemaInfo.SchemaType;
        }
        return GetTypeFromAncestors(elementToValidate, xmlSchemaObject, num);
    }
References System.Xml.DocumentSchemaValidator._isPartialTreeValid, System.Xml.DocumentSchemaValidator._nodeSequenceToValidate, System.Xml.DocumentSchemaValidator.CheckNodeSequenceCapacity(), System.Xml.DocumentSchemaValidator.GetTypeFromAncestors(), System.Xml.XmlNode.ParentNode, and System.Xml.XmlNode.SchemaInfo.
Referenced by System.Xml.DocumentSchemaValidator.FindSchemaInfo(), and System.Xml.DocumentSchemaValidator.Validate().