Terraria: System.Xml.DocumentSchemaValidator.ValidateAttributes
ValidateAttributes()
void System.Xml.DocumentSchemaValidator.ValidateAttributes (XmlElement elementNode) inline private
Definition at line 362 of file DocumentSchemaValidator.cs.
    {
        XmlAttributeCollection attributes = elementNode.Attributes;
        XmlAttribute xmlAttribute = null;
        for (int i = 0; i < attributes.Count; i++)
        {
            xmlAttribute = (XmlAttribute)(_currentNode = attributes[i]);
            if (!Ref.Equal(xmlAttribute.NamespaceURI, _nsXmlNs))
            {
                _validator.ValidateAttribute(xmlAttribute.LocalName, xmlAttribute.NamespaceURI, _nodeValueGetter, _attributeSchemaInfo);
                if (_psviAugmentation)
                {
                    xmlAttribute.XmlName = _document.AddAttrXmlName(xmlAttribute.Prefix, xmlAttribute.LocalName, xmlAttribute.NamespaceURI, _attributeSchemaInfo);
                }
            }
        }
        if (!_psviAugmentation)
        {
            return;
        }
        if (_defaultAttributes == null)
        {
            _defaultAttributes = new ArrayList();
        }
        else
        {
            _defaultAttributes.Clear();
        }
        _validator.GetUnspecifiedDefaultAttributes(_defaultAttributes);
        xmlAttribute = null;
        for (int j = 0; j < _defaultAttributes.Count; j++)
        {
            XmlSchemaAttribute xmlSchemaAttribute = _defaultAttributes[j] as XmlSchemaAttribute;
            XmlQualifiedName qualifiedName = xmlSchemaAttribute.QualifiedName;
            xmlAttribute = _document.CreateDefaultAttribute(GetDefaultPrefix(qualifiedName.Namespace), qualifiedName.Name, qualifiedName.Namespace);
            SetDefaultAttributeSchemaInfo(xmlSchemaAttribute);
            xmlAttribute.XmlName = _document.AddAttrXmlName(xmlAttribute.Prefix, xmlAttribute.LocalName, xmlAttribute.NamespaceURI, _attributeSchemaInfo);
            xmlAttribute.AppendChild(_document.CreateTextNode(xmlSchemaAttribute.AttDef.DefaultValueRaw));
            attributes.Append(xmlAttribute);
            if (xmlAttribute is XmlUnspecifiedAttribute xmlUnspecifiedAttribute)
            {
                xmlUnspecifiedAttribute.SetSpecified(f: false);
            }
        }
    }
References System.Xml.DocumentSchemaValidator._attributeSchemaInfo, System.Xml.DocumentSchemaValidator._currentNode, System.Xml.DocumentSchemaValidator._defaultAttributes, System.Xml.DocumentSchemaValidator._document, System.Xml.DocumentSchemaValidator._nodeValueGetter, System.Xml.DocumentSchemaValidator._nsXmlNs, System.Xml.DocumentSchemaValidator._psviAugmentation, System.Xml.DocumentSchemaValidator._validator, System.Xml.XmlDocument.AddAttrXmlName(), System.Xml.XmlAttributeCollection.Append(), System.Collections.ArrayList.Clear(), System.Collections.ArrayList.Count, System.Xml.XmlAttributeCollection.Count, System.Xml.XmlDocument.CreateDefaultAttribute(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.DocumentSchemaValidator.GetDefaultPrefix(), System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.DocumentSchemaValidator.SetDefaultAttributeSchemaInfo(), and System.Xml.Schema.XmlSchemaValidator.ValidateAttribute().
Referenced by System.Xml.DocumentSchemaValidator.ValidateElement().