Terraria: System.Xml.DocumentSchemaValidator.ValidateChildrenTillNextAncestor
ValidateChildrenTillNextAncestor()
void System.Xml.DocumentSchemaValidator.ValidateChildrenTillNextAncestor (XmlNode parentNode, XmlNode childToStopAt) inline private
Definition at line 627 of file DocumentSchemaValidator.cs.
    {
        XmlNode xmlNode = parentNode.FirstChild;
        while (xmlNode != null && xmlNode != childToStopAt)
        {
            switch (xmlNode.NodeType)
            {
            case XmlNodeType.EntityReference:
                ValidateChildrenTillNextAncestor(xmlNode, childToStopAt);
                break;
            case XmlNodeType.Element:
                ValidateSingleElement(xmlNode as XmlElement, skipToEnd: true, null);
                break;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
                _validator.ValidateText(xmlNode.Value);
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                _validator.ValidateWhitespace(xmlNode.Value);
                break;
            default:
                throw new InvalidOperationException(System.SR.Format(System.SR.Xml_UnexpectedNodeType, _currentNode.NodeType));
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
                break;
            }
            xmlNode = xmlNode.NextSibling;
        }
    }
References System.Xml.DocumentSchemaValidator._currentNode, System.Xml.DocumentSchemaValidator._validator, System.Xml.XmlNode.FirstChild, System.SR.Format(), System.Xml.XmlNode.NodeType, System.Xml.DocumentSchemaValidator.ValidateChildrenTillNextAncestor(), System.Xml.DocumentSchemaValidator.ValidateSingleElement(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace(), and System.SR.Xml_UnexpectedNodeType.
Referenced by System.Xml.DocumentSchemaValidator.GetTypeFromAncestors(), and System.Xml.DocumentSchemaValidator.ValidateChildrenTillNextAncestor().