Terraria: System.Xml.DocumentSchemaValidator.GetTypeFromAncestors
GetTypeFromAncestors()
XmlSchemaObject System.Xml.DocumentSchemaValidator.GetTypeFromAncestors (XmlElement elementToValidate, XmlSchemaObject ancestorType, int ancestorsCount) inline private
Definition at line 519 of file DocumentSchemaValidator.cs.
    {
        _validator = CreateTypeFinderValidator(ancestorType);
        _schemaInfo = new XmlSchemaInfo();
        int num = ancestorsCount - 1;
        bool flag = AncestorTypeHasWildcard(ancestorType);
        for (int num2 = num; num2 >= 0; num2--)
        {
            XmlNode xmlNode = _nodeSequenceToValidate[num2];
            XmlElement xmlElement = xmlNode as XmlElement;
            ValidateSingleElement(xmlElement, skipToEnd: false, _schemaInfo);
            if (!flag)
            {
                xmlElement.XmlName = _document.AddXmlName(xmlElement.Prefix, xmlElement.LocalName, xmlElement.NamespaceURI, _schemaInfo);
                flag = AncestorTypeHasWildcard(_schemaInfo.SchemaElement);
            }
            _validator.ValidateEndOfAttributes(null);
            if (num2 > 0)
            {
                ValidateChildrenTillNextAncestor(xmlNode, _nodeSequenceToValidate[num2 - 1]);
            }
            else
            {
                ValidateChildrenTillNextAncestor(xmlNode, elementToValidate);
            }
        }
        ValidateSingleElement(elementToValidate, skipToEnd: false, _schemaInfo);
        XmlSchemaObject xmlSchemaObject = null;
        xmlSchemaObject = ((_schemaInfo.SchemaElement == null) ? ((XmlSchemaAnnotated)_schemaInfo.SchemaType) : ((XmlSchemaAnnotated)_schemaInfo.SchemaElement));
        if (xmlSchemaObject == null)
        {
            if (_validator.CurrentProcessContents == XmlSchemaContentProcessing.Skip)
            {
                if (_isPartialTreeValid)
                {
                    return XmlSchemaComplexType.AnyTypeSkip;
                }
            }
            else if (_validator.CurrentProcessContents == XmlSchemaContentProcessing.Lax)
            {
                return XmlSchemaComplexType.AnyType;
            }
        }
        return xmlSchemaObject;
    }
References System.Xml.DocumentSchemaValidator._document, System.Xml.DocumentSchemaValidator._isPartialTreeValid, System.Xml.DocumentSchemaValidator._nodeSequenceToValidate, System.Xml.DocumentSchemaValidator._schemaInfo, System.Xml.DocumentSchemaValidator._validator, System.Xml.XmlDocument.AddXmlName(), System.Xml.DocumentSchemaValidator.AncestorTypeHasWildcard(), System.Xml.Schema.XmlSchemaComplexType.AnyType, System.Xml.Schema.XmlSchemaComplexType.AnyTypeSkip, System.Xml.DocumentSchemaValidator.CreateTypeFinderValidator(), System.Xml.Schema.XmlSchemaValidator.CurrentProcessContents, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaInfo.SchemaElement, System.Xml.Schema.XmlSchemaInfo.SchemaType, System.Xml.DocumentSchemaValidator.ValidateChildrenTillNextAncestor(), System.Xml.Schema.XmlSchemaValidator.ValidateEndOfAttributes(), and System.Xml.DocumentSchemaValidator.ValidateSingleElement().
Referenced by System.Xml.DocumentSchemaValidator.FindSchemaInfo().