Terraria: ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup.Initialize
Initialize()
override void ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup.Initialize () inline protected
Definition at line 23 of file RazerDeviceGroup.cs.
    {
        if (_isInitialized || _initializationFailed)
        {
            return;
        }
        if (!NativeLibrary.TryLoad("RzChromaSDK64.dll", Assembly.GetEntryAssembly(), DllImportSearchPath.SafeDirectories, out var _))
        {
            _initializationFailed = true;
            return;
        }
        try
        {
            RzResult rzResult = NativeMethods.Init();
            if (rzResult != 0)
            {
                int num = (int)rzResult;
                throw new DeviceInitializationException("Unable to initialize Razer Synapse: " + num);
            }
            _isInitialized = true;
            _devices.Add(new RazerMouse(_colorProfiles.Mouse));
            _devices.Add(new RazerKeyboard(_colorProfiles.Keyboard));
            _devices.Add(new RazerMousepad(_colorProfiles.Mousepad));
            _devices.Add(new RazerKeypad(_colorProfiles.Keypad));
            _devices.Add(new RazerHeadset(_colorProfiles.Headset));
            _devices.Add(new RazerLink(_colorProfiles.Generic));
            Console.WriteLine("Razer Chroma initialized.");
        }
        catch (DeviceInitializationException)
        {
            Console.WriteLine("Razer Chroma not supported. (Can be disabled via Config.json)");
            Uninitialize();
        }
        catch (Exception ex2)
        {
            Console.WriteLine("Razer Chroma not supported: " + ex2);
            Uninitialize();
        }
    }
References ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup._colorProfiles, ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup._devices, ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup._initializationFailed, ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup._isInitialized, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), ReLogic.Peripherals.RGB.VendorColorProfile.Generic, System.Reflection.Assembly.GetEntryAssembly(), ReLogic.Peripherals.RGB.VendorColorProfile.Headset, ReLogic.Peripherals.RGB.Razer.NativeMethods.Init(), ReLogic.Peripherals.RGB.VendorColorProfile.Keyboard, ReLogic.Peripherals.RGB.VendorColorProfile.Keypad, ReLogic.Peripherals.RGB.VendorColorProfile.Mouse, ReLogic.Peripherals.RGB.VendorColorProfile.Mousepad, System.Runtime.InteropServices.NativeLibrary.TryLoad(), ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup.Uninitialize(), and System.Console.WriteLine().