Terraria: ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup.Uninitialize
Uninitialize()
override void ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup.Uninitialize () inline protected
Definition at line 63 of file RazerDeviceGroup.cs.
    {
        if (!_isInitialized)
        {
            return;
        }
        try
        {
            _devices.Clear();
            RzResult rzResult = NativeMethods.UnInit();
            if (rzResult != 0)
            {
                int num = (int)rzResult;
                throw new DeviceInitializationException("Unable to uninitialize Razer Synapse: " + num);
            }
            Console.WriteLine("Razer Chroma unitialized.");
        }
        catch (Exception ex)
        {
            if (!(ex is ObjectDisposedException))
            {
                Console.WriteLine("Razer Chroma failed to uninitialize: " + ex);
            }
        }
        _isInitialized = false;
    }
References ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup._devices, ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup._isInitialized, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), ReLogic.Peripherals.RGB.Razer.NativeMethods.UnInit(), and System.Console.WriteLine().
Referenced by ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup.Initialize().