Terraria: CorsairHeadset.Create
Create()
static CorsairHeadset CorsairHeadset.Create (int deviceIndex, DeviceColorProfile colorProfile) inline static
     {
         //IL_0084: Unknown result type (might be due to invalid IL or missing references)
         CorsairLedPosition[] ledPositions = new CorsairLedPosition[2]
         {
             new CorsairLedPosition
             {
                 Width = 1.0,
                 Height = 1.0,
                 LedId = CorsairLedId.CLH_LeftLogo
             },
             new CorsairLedPosition
             {
                 Width = 1.0,
                 Height = 1.0,
                 LedId = CorsairLedId.CLH_RightLogo
             }
         };
         return new CorsairHeadset(Fragment.FromGrid(new Rectangle(-2, 0, 2, 1)), ledPositions, colorProfile);
     }
References CorsairHeadset(), and Fragment.FromGrid().
Referenced by CorsairDeviceGroup.AddDeviceIfSupported().