Terraria: System.Net.Security.SSPIHandleCache.CacheCredential
CacheCredential() [4/4]
static void System.Net.Security.SSPIHandleCache.CacheCredential (System::Net::Security::SafeFreeCredentials newHandle) inline static package
Definition at line 11 of file SSPIHandleCache.cs.
    {
        try
        {
            System.Net.Security.SafeCredentialReference safeCredentialReference = System.Net.Security.SafeCredentialReference.CreateReference(newHandle);
            if (safeCredentialReference != null)
            {
                int num = Interlocked.Increment(ref s_current) & 0x1F;
                Interlocked.Exchange(ref s_cacheSlots[num], safeCredentialReference)?.Dispose();
            }
        }
        catch (Exception ex)
        {
            if (System.Net.NetEventSource.Log.IsEnabled() && !System.Net.ExceptionCheck.IsFatal(ex))
            {
                System.Net.NetEventSource.Error(null, $"Attempted to throw: {ex}", "CacheCredential");
            }
        }
    }
References System.Net.Security.SafeCredentialReference.CreateReference(), System.Net.NetEventSource.Error(), System.Threading.Interlocked.Exchange(), System.Threading.Interlocked.Increment(), System.Net.ExceptionCheck.IsFatal(), System.Net.NetEventSource.Log, System.Net.Security.SSPIHandleCache.s_cacheSlots, and System.Net.Security.SSPIHandleCache.s_current.