Terraria: Terraria.GameContent.Tile_Entities.TETrainingDummy.Place
Place()
static int Terraria.GameContent.Tile_Entities.TETrainingDummy.Place (int x, int y) inline static
Definition at line 112 of file TETrainingDummy.cs.
    {
        TETrainingDummy tETrainingDummy = new TETrainingDummy();
        tETrainingDummy.Position = new Point16(x, y);
        tETrainingDummy.ID = TileEntity.AssignNewID();
        tETrainingDummy.type = _myEntityID;
        lock (TileEntity.EntityCreationLock)
        {
            TileEntity.ByID[tETrainingDummy.ID] = tETrainingDummy;
            TileEntity.ByPosition[tETrainingDummy.Position] = tETrainingDummy;
        }
        return tETrainingDummy.ID;
    }
References Terraria.GameContent.Tile_Entities.TETrainingDummy.TETrainingDummy(), Terraria.GameContent.Tile_Entities.TETrainingDummy._myEntityID, Terraria.DataStructures.TileEntity.AssignNewID(), Terraria.DataStructures.TileEntity.ByID, Terraria.DataStructures.TileEntity.ByPosition, Terraria.DataStructures.TileEntity.EntityCreationLock, Terraria.DataStructures.TileEntity.ID, and Terraria.DataStructures.TileEntity.Position.
Referenced by Terraria.GameContent.Tile_Entities.TETrainingDummy.Hook_AfterPlacement(), and Terraria.GameContent.Tile_Entities.TETrainingDummy.NetPlaceEntity().