Terraria: System.Collections.Immutable.ImmutableInterlocked.TryUpdate< TKey, TValue >
TryUpdate< TKey, TValue >()
static bool System.Collections.Immutable.ImmutableInterlocked.TryUpdate< TKey, TValue > (ref ImmutableDictionary< TKey, TValue > location, TKey key, TValue newValue, TValue comparisonValue) inline static
Type Constraints
TKey : notnull
Definition at line 218 of file ImmutableInterlocked.cs.
                                                                                                                                                             : notnull
    {
        EqualityComparer<TValue> @default = EqualityComparer<TValue>.Default;
        ImmutableDictionary<TKey, TValue> immutableDictionary = Volatile.Read(ref location);
        bool flag;
        do
        {
            Requires.NotNull(immutableDictionary, "location");
            if (!immutableDictionary.TryGetValue(key, out var value) || !@default.Equals(value, comparisonValue))
            {
                return false;
            }
            ImmutableDictionary<TKey, TValue> value2 = immutableDictionary.SetItem(key, newValue);
            ImmutableDictionary<TKey, TValue> immutableDictionary2 = Interlocked.CompareExchange(ref location, value2, immutableDictionary);
            flag = immutableDictionary == immutableDictionary2;
            immutableDictionary = immutableDictionary2;
        }
        while (!flag);
        return true;
    }
References System.Threading.Interlocked.CompareExchange(), System.key, System.Threading.Volatile.Read(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.