Terraria: System.Data.LinqDataView.FindRowsByKey
FindRowsByKey()
override DataRowView[] System.Data.LinqDataView.FindRowsByKey (object[] key) inline package virtual
Reimplemented from System.Data.DataView.
Definition at line 142 of file LinqDataView.cs.
    {
        if (base.SortComparison == null && string.IsNullOrEmpty(base.Sort))
        {
            throw ExceptionBuilder.IndexKeyLength(0, 0);
        }
        if (base.SortComparison != null && key.Length != sortExpressionBuilder.Count)
        {
            throw DataSetUtil.InvalidOperation(System.SR.Format(System.SR.LDV_InvalidNumOfKeys, sortExpressionBuilder.Count));
        }
        if (base.SortComparison == null)
        {
            return base.FindRowsByKey(key);
        }
        Range range = FindRecords<object, DataRow>(comparerKeyRow.Invoke, new List<object>(key));
        return GetDataRowViewFromRange(range);
    }
References System.Data.LinqDataView.comparerKeyRow, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.Format(), System.Data.DataView.GetDataRowViewFromRange(), System.Data.ExceptionBuilder.IndexKeyLength(), DataSetUtil.InvalidOperation(), System.key, System.SR.LDV_InvalidNumOfKeys, and System.Data.LinqDataView.sortExpressionBuilder.