Terraria: System.Data.LinqDataView.FindByKey
FindByKey() [1/2]
override int System.Data.LinqDataView.FindByKey (object key) inline package virtual
Reimplemented from System.Data.DataView.
Definition at line 89 of file LinqDataView.cs.
    {
        if (!string.IsNullOrEmpty(base.Sort))
        {
            return base.FindByKey(key);
        }
        if (base.SortComparison == null)
        {
            throw ExceptionBuilder.IndexKeyLength(0, 0);
        }
        if (sortExpressionBuilder.Count != 1)
        {
            throw DataSetUtil.InvalidOperation(System.SR.Format(System.SR.LDV_InvalidNumOfKeys, sortExpressionBuilder.Count));
        }
        Index.ComparisonBySelector<object, DataRow> comparison = comparerKeyRow.Invoke;
        List<object> list = new List<object>();
        list.Add(key);
        Range range = FindRecords(comparison, list);
        if (range.Count != 0)
        {
            return range.Min;
        }
        return -1;
    }
References System.Data.LinqDataView.comparerKeyRow, System.comparison, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.Format(), System.Data.ExceptionBuilder.IndexKeyLength(), DataSetUtil.InvalidOperation(), System.key, System.SR.LDV_InvalidNumOfKeys, System.list, and System.Data.LinqDataView.sortExpressionBuilder.