Terraria: Item.MoveInWorld
MoveInWorld()
void Item.MoveInWorld (float gravity, float maxFallSpeed, ref Vector2 wetVelocity, int i) inline private
     {
         if (!shimmered && ItemID.Sets.ItemNoGravity[type])
         {
             velocity.X *= 0.95f;
             if ((double)velocity.X < 0.1 && (double)velocity.X > -0.1)
             {
                 velocity.X = 0f;
             }
             velocity.Y *= 0.95f;
             if ((double)velocity.Y < 0.1 && (double)velocity.Y > -0.1)
             {
                 velocity.Y = 0f;
             }
         }
         else
         {
             bool flag = false;
             if (shimmered && active)
             {
                 int num = 50;
                 for (int j = 0; j < 400; j++)
                 {
                     if (i == j || !Main.item[j].active || !Main.item[j].shimmered)
                     {
                         continue;
                     }
                     if (num-- <= 0)
                     {
                         break;
                     }
                     float num2 = (width + Main.item[j].width) / 2;
                     if (!(Math.Abs(base.Center.X - Main.item[j].Center.X) <= num2) || !(Math.Abs(base.Center.Y - Main.item[j].Center.Y) <= num2))
                     {
                         continue;
                     }
                     flag = true;
                     float num3 = Vector2.Distance(base.Center, Main.item[j].Center);
                     num2 /= num3;
                     if (num2 > 10f)
                     {
                         num2 = 10f;
                     }
                     if (base.Center.X < Main.item[j].Center.X)
                     {
                         if (velocity.X > -3f * num2)
{
                             velocity.X -= 0.1f * num2;
                         }
                         if (Main.item[j].velocity.X < 3f)
{
                             Main.item[j].velocity.X += 0.1f * num2;
                         }
                     }
                     else if (base.Center.X > Main.item[j].Center.X)
                     {
                         if (velocity.X < 3f * num2)
{
                             velocity.X += 0.1f * num2;
                         }
                         if (Main.item[j].velocity.X > -3f)
{
                             Main.item[j].velocity.X -= 0.1f * num2;
                         }
                     }
                     else if (i < j)
                     {
                         if (velocity.X > -3f * num2)
{
                             velocity.X -= 0.1f * num2;
                         }
                         if (Main.item[j].velocity.X < 3f * num2)
{
                             Main.item[j].velocity.X += 0.1f * num2;
                         }
                     }
                 }
             }
             velocity.Y += gravity;
             if (velocity.Y > maxFallSpeed)
             {
                 velocity.Y = maxFallSpeed;
             }
             velocity.X *= 0.95f;
             if ((double)velocity.X < 0.1 && (double)velocity.X > -0.1)
             {
                 velocity.X = 0f;
             }
             if (flag)
             {
                 velocity.X *= 0.8f;
             }
         }
         bool flag2 = Collision.LavaCollision(position, width, height);
         if (flag2)
         {
             lavaWet = true;
         }
         bool num4 = Collision.WetCollision(position, width, height);
         if (Collision.honey)
         {
             honeyWet = true;
         }
         if (Collision.shimmer)
         {
             shimmerWet = true;
         }
         if (num4)
         {
             if (!wet)
             {
                 if (wetCount == 0)
                 {
                     wetCount = 20;
                     if (!flag2)
                     {
                         if (shimmerWet)
{
                             for (int k = 0; k < 10; k++)
{
                                 int num5 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                                 Main.dust[num5].velocity.Y -= 4f;
                                 Main.dust[num5].velocity.X *= 2.5f;
                                 Main.dust[num5].scale = 0.8f;
                                 Main.dust[num5].noGravity = true;
                                 switch (Main.rand.Next(6))
{
                                 case 0:
                                     Main.dust[num5].color = new Color(255, 255, 210);
                                     break;
                                 case 1:
                                     Main.dust[num5].color = new Color(190, 245, 255);
                                     break;
                                 case 2:
                                     Main.dust[num5].color = new Color(255, 150, 255);
                                     break;
                                 default:
                                     Main.dust[num5].color = new Color(190, 175, 255);
                                     break;
                                 }
                             }
                             SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 4);
                         }
                         else if (honeyWet)
{
                             for (int l = 0; l < 5; l++)
{
                                 int num6 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                                 Main.dust[num6].velocity.Y -= 1f;
                                 Main.dust[num6].velocity.X *= 2.5f;
                                 Main.dust[num6].scale = 1.3f;
                                 Main.dust[num6].alpha = 100;
                                 Main.dust[num6].noGravity = true;
                             }
                             SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                         }
                         else
{
                             for (int m = 0; m < 10; m++)
{
                                 int num7 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, Dust.dustWater());
                                 Main.dust[num7].velocity.Y -= 4f;
                                 Main.dust[num7].velocity.X *= 2.5f;
                                 Main.dust[num7].scale *= 0.8f;
                                 Main.dust[num7].alpha = 100;
                                 Main.dust[num7].noGravity = true;
                             }
                             SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                         }
                     }
                     else
                     {
                         for (int n = 0; n < 5; n++)
{
                             int num8 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                             Main.dust[num8].velocity.Y -= 1.5f;
                             Main.dust[num8].velocity.X *= 2.5f;
                             Main.dust[num8].scale = 1.3f;
                             Main.dust[num8].alpha = 100;
                             Main.dust[num8].noGravity = true;
                         }
                         SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                     }
                 }
                 wet = true;
             }
         }
         else if (wet)
         {
             wet = false;
             if (wetCount == 0)
             {
                 wetCount = 20;
                 if (!lavaWet)
                 {
                     if (shimmerWet)
                     {
                         for (int num9 = 0; num9 < 10; num9++)
{
                             int num10 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                             Main.dust[num10].velocity.Y -= 4f;
                             Main.dust[num10].velocity.X *= 2.5f;
                             Main.dust[num10].scale = 0.8f;
                             Main.dust[num10].noGravity = true;
                             switch (Main.rand.Next(6))
{
                             case 0:
                                 Main.dust[num10].color = new Color(255, 255, 210);
                                 break;
                             case 1:
                                 Main.dust[num10].color = new Color(190, 245, 255);
                                 break;
                             case 2:
                                 Main.dust[num10].color = new Color(255, 150, 255);
                                 break;
                             default:
                                 Main.dust[num10].color = new Color(190, 175, 255);
                                 break;
                             }
                         }
                         SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 5);
                     }
                     else if (honeyWet)
                     {
                         for (int num11 = 0; num11 < 5; num11++)
{
                             int num12 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                             Main.dust[num12].velocity.Y -= 1f;
                             Main.dust[num12].velocity.X *= 2.5f;
                             Main.dust[num12].scale = 1.3f;
                             Main.dust[num12].alpha = 100;
                             Main.dust[num12].noGravity = true;
                         }
                         SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                     }
                     else
                     {
                         for (int num13 = 0; num13 < 10; num13++)
{
                             int num14 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2)), width + 12, 24, Dust.dustWater());
                             Main.dust[num14].velocity.Y -= 4f;
                             Main.dust[num14].velocity.X *= 2.5f;
                             Main.dust[num14].scale *= 0.8f;
                             Main.dust[num14].alpha = 100;
                             Main.dust[num14].noGravity = true;
                         }
                         SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                     }
                 }
                 else
                 {
                     for (int num15 = 0; num15 < 5; num15++)
                     {
                         int num16 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                         Main.dust[num16].velocity.Y -= 1.5f;
                         Main.dust[num16].velocity.X *= 2.5f;
                         Main.dust[num16].scale = 1.3f;
                         Main.dust[num16].alpha = 100;
                         Main.dust[num16].noGravity = true;
                     }
                     SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                 }
             }
         }
         if (!wet)
         {
             lavaWet = false;
             honeyWet = false;
             shimmerWet = false;
         }
         if (wetCount > 0)
         {
             wetCount--;
         }
         if (wet)
         {
             if (wet)
             {
                 Vector2 vector = velocity;
                 velocity = Collision.TileCollision(position, velocity, width, height);
                 if (velocity.X != vector.X)
                 {
                     wetVelocity.X = velocity.X;
                 }
                 if (velocity.Y != vector.Y)
                 {
                     wetVelocity.Y = velocity.Y;
                 }
             }
         }
         else
         {
             velocity = Collision.TileCollision(position, velocity, width, height);
         }
         Vector4 vector2 = Collision.SlopeCollision(position, velocity, width, height, gravity);
         position.X = vector2.X;
         position.Y = vector2.Y;
         velocity.X = vector2.Z;
         velocity.Y = vector2.W;
         Collision.StepConveyorBelt(this, 1f);
     }
References Entity.active, Dust.alpha, Entity.Center, Color, Dust.color, Main.dust, Dust.dustWater(), Entity.height, Collision.honey, Entity.honeyWet, Main.item, ItemID.Sets.ItemNoGravity, Collision.LavaCollision(), Entity.lavaWet, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, SoundEngine.PlaySound(), Entity.position, Main.rand, Dust.scale, Collision.shimmer, shimmered, Entity.shimmerWet, Collision.SlopeCollision(), Collision.StepConveyorBelt(), Collision.TileCollision(), type, Dust.velocity, Entity.velocity, Entity.wet, Collision.WetCollision(), Entity.wetCount, and Entity.width.
Referenced by UpdateItem().