Terraria: Item.DeserializeFrom
DeserializeFrom()
void Item.DeserializeFrom (BinaryReader reader, ItemSerializationContext context) inline
     {
         if (context == ItemSerializationContext.SavingAndLoading)
         {
             netDefaults(reader.ReadInt32());
             stack = reader.ReadInt32();
             Prefix(reader.ReadByte());
         }
         if (type >= ItemID.Count)
         {
             TurnToAir();
         }
     }
References ItemID.Count, netDefaults(), Prefix(), stack, TurnToAir(), and type.
Referenced by EquipmentLoadout.Deserialize().