Terraria: Item.SetDefaults
SetDefaults() [1/2]
void Item.SetDefaults (int Type, bool noMatCheck = false, ItemVariant variant = null) inline
     {
         if (Type < 0)
         {
             netDefaults(Type);
             return;
         }
         if (Main.netMode == 1 || Main.netMode == 2)
         {
             playerIndexTheItemIsReservedFor = 255;
         }
         else
         {
             playerIndexTheItemIsReservedFor = Main.myPlayer;
         }
         ResetStats(Type);
         if (type >= ItemID.Count)
         {
             type = 0;
         }
         if (variant == null)
         {
             variant = ItemVariants.SelectVariant(Type);
         }
         else if (!ItemVariants.HasVariant(Type, variant))
         {
             variant = null;
         }
         Variant = variant;
         if (type == 0)
         {
             netID = 0;
             stack = 0;
         }
         else if (ItemID.Sets.IsFood[type])
         {
             SetFoodDefaults(type);
         }
         else if (type <= 1000)
         {
             SetDefaults1(type);
         }
         else if (type <= 2001)
         {
             SetDefaults2(type);
         }
         else if (type <= 3000)
         {
             SetDefaults3(type);
         }
         else if (type <= 3989)
         {
             SetDefaults4(type);
         }
         else
         {
             SetDefaults5(type);
         }
         dye = (byte)GameShaders.Armor.GetShaderIdFromItemId(type);
         if (hairDye != 0)
         {
             hairDye = GameShaders.Hair.GetShaderIdFromItemId(type);
         }
         if (type == 2015)
         {
             value = sellPrice(0, 0, 5);
         }
         if (type == 2016)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 2017)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 5212)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 5300)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 5311)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 5312)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 5313)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 2019)
         {
             value = sellPrice(0, 0, 5);
         }
         if (type == 2018)
         {
             value = sellPrice(0, 0, 5);
         }
         if (type == 3563)
         {
             value = sellPrice(0, 0, 5);
         }
         if (type == 261)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 2205)
         {
             value = sellPrice(0, 0, 12, 50);
         }
         if (type == 2123)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 2122)
         {
             value = sellPrice(0, 0, 7, 50);
         }
         if (type == 2003)
         {
             value = sellPrice(0, 0, 10);
         }
         if (type == 2156)
         {
             value = sellPrice(0, 0, 15);
         }
         if (type == 2157)
         {
             value = sellPrice(0, 0, 15);
         }
         if (type == 2121)
         {
             value = sellPrice(0, 0, 10);
         }
         if (type == 1992)
         {
             value = sellPrice(0, 0, 3);
         }
         if (type == 2004)
         {
             value = sellPrice(0, 0, 5);
         }
         if (type == 2002)
         {
             value = sellPrice(0, 0, 5);
         }
         if (type == 2740)
         {
             value = sellPrice(0, 0, 2, 50);
         }
         if (type == 2006)
         {
             value = sellPrice(0, 0, 10);
         }
         if (type == 3191)
         {
             value = sellPrice(0, 0, 20);
         }
         if (type == 3192)
         {
             value = sellPrice(0, 0, 2, 50);
         }
         if (type == 3193)
         {
             value = sellPrice(0, 0, 5);
         }
         if (type == 3194)
         {
             value = sellPrice(0, 0, 10);
         }
         if (type == 2007)
         {
             value = sellPrice(0, 0, 50);
         }
         if (type == 2673)
         {
             value = sellPrice(0, 10);
         }
         if (bait > 0)
         {
             if (bait >= 50)
             {
                 rare = 3;
             }
             else if (bait >= 30)
             {
                 rare = 2;
             }
             else if (bait >= 15)
             {
                 rare = 1;
             }
         }
         if (type >= 1994 && type <= 2001)
         {
             int num = type - 1994;
             if (num == 0)
             {
                 value = sellPrice(0, 0, 5);
             }
             if (num == 4)
             {
                 value = sellPrice(0, 0, 10);
             }
             if (num == 6)
             {
                 value = sellPrice(0, 0, 15);
             }
             if (num == 3)
             {
                 value = sellPrice(0, 0, 20);
             }
             if (num == 7)
             {
                 value = sellPrice(0, 0, 30);
             }
             if (num == 2)
             {
                 value = sellPrice(0, 0, 40);
             }
             if (num == 1)
             {
                 value = sellPrice(0, 0, 75);
             }
             if (num == 5)
             {
                 value = sellPrice(0, 1);
             }
         }
         if (type == 2663 || type == 1720 || type == 2137 || type == 2155 || type == 2151 || type == 1704 || type == 2143 || type == 1710 || type == 2238 || type == 2133 || type == 2147 || type == 2405 || type == 1716 || type == 1705)
         {
             value = sellPrice(0, 2);
         }
         if (Main.projHook[shoot])
         {
             useStyle = 0;
             useTime = 0;
             useAnimation = 0;
         }
         if (ItemID.Sets.IsDrill[type] || ItemID.Sets.IsChainsaw[type] || type == 1262)
         {
             useTime = (int)((double)useTime * 0.6);
             if (useTime < 1)
             {
                 useTime = 1;
             }
             useAnimation = (int)((double)useAnimation * 0.6);
             if (useAnimation < 1)
             {
                 useAnimation = 1;
             }
             tileBoost--;
         }
         if (ItemID.Sets.IsFood[type])
         {
             holdStyle = 1;
         }
         if (type >= 1803 && type <= 1807)
         {
             SetDefaults(1533 + type - 1803);
         }
         if (dye > 0)
         {
             maxStack = CommonMaxStack;
         }
         if (createTile == 19)
         {
             maxStack = CommonMaxStack;
         }
         netID = type;
         if (!noMatCheck)
         {
             material = ItemID.Sets.IsAMaterial[type];
         }
         RebuildTooltip();
         if (type > 0 && type < ItemID.Count && ItemID.Sets.Deprecated[type])
         {
             netID = 0;
             type = 0;
             stack = 0;
         }
     }
References GameShaders.Armor, bait, CommonMaxStack, ItemID.Count, createTile, ItemID.Sets.Deprecated, dye, ArmorShaderDataSet.GetShaderIdFromItemId(), HairShaderDataSet.GetShaderIdFromItemId(), GameShaders.Hair, hairDye, ItemVariants.HasVariant(), holdStyle, ItemID.Sets.IsAMaterial, ItemID.Sets.IsChainsaw, ItemID.Sets.IsDrill, ItemID.Sets.IsFood, material, maxStack, Main.myPlayer, netDefaults(), netID, Main.netMode, playerIndexTheItemIsReservedFor, Main.projHook, rare, RebuildTooltip(), ResetStats(), ItemVariants.SelectVariant(), sellPrice(), SetDefaults(), SetDefaults1(), SetDefaults2(), SetDefaults3(), SetDefaults4(), SetDefaults5(), SetFoodDefaults(), shoot, stack, tileBoost, type, useAnimation, useStyle, useTime, value, and Variant.