Terraria: Item.GetFlexibleTileWand
GetFlexibleTileWand()
FlexibleTileWand Item.GetFlexibleTileWand () inline
     {
         return type switch
         {
             5324 => FlexibleTileWand.RubblePlacementSmall,
             5329 => FlexibleTileWand.RubblePlacementMedium,
             5330 => FlexibleTileWand.RubblePlacementLarge,
             _ => null,
         };
     }
References FlexibleTileWand.RubblePlacementLarge, FlexibleTileWand.RubblePlacementMedium, FlexibleTileWand.RubblePlacementSmall, and type.
Referenced by Player.ModifyFlexibleWandPlacementInfo(), Player.PlaceThing_Tiles_CheckFlexibleWand(), and Main.TryGetAmmo().