Terraria: Item.ShimmerEffect
ShimmerEffect()
static void Item.ShimmerEffect (Vector2 shimmerPositon) inline static
     {
         SoundEngine.PlaySound(SoundID.Item176, (int)shimmerPositon.X, (int)shimmerPositon.Y);
         for (int i = 0; i < 20; i++)
         {
             int num = Dust.NewDust(shimmerPositon, 1, 1, 309);
             Main.dust[num].scale *= 1.2f;
             switch (Main.rand.Next(6))
             {
             case 0:
                 Main.dust[num].color = new Color(255, 255, 210);
                 break;
             case 1:
                 Main.dust[num].color = new Color(190, 245, 255);
                 break;
             case 2:
                 Main.dust[num].color = new Color(255, 150, 255);
                 break;
             default:
                 Main.dust[num].color = new Color(190, 175, 255);
                 break;
             }
         }
     }
References Color, Dust.color, Main.dust, SoundID.Item176, Dust.NewDust(), UnifiedRandom.Next(), SoundEngine.PlaySound(), Main.rand, and Dust.scale.
Referenced by MessageBuffer.GetData(), GetShimmered(), and NPC.GetShimmered().