Terraria: Item.Refresh
Refresh()
void Item.Refresh (bool onlyIfVariantChanged = true) inline
     {
         if (!IsAir && (!onlyIfVariantChanged || ItemVariants.SelectVariant(type) != Variant))
         {
             bool flag = favorited;
             int num = stack;
             int num2 = netID;
             int prefixWeWant = prefix;
             netDefaults(num2);
             Prefix(prefixWeWant);
             stack = num;
             favorited = flag;
         }
     }
References favorited, IsAir, netDefaults(), netID, prefix, Prefix(), ItemVariants.SelectVariant(), stack, type, and Variant.
Referenced by Player.RefreshItems(), ResetPrefix(), and Recipe.UpdateItemVariants().