Terraria: Item.DefaultTokite
DefaultTokite()
void Item.DefaultTokite (int projId) inline
     {
         width = 20;
         height = 28;
         DefaultToThrownWeapon(projId, 30, 2f);
         consumable = false;
         ranged = false;
         noUseGraphic = true;
         maxStack = 1;
         SetShopValues(ItemRarityColor.Blue1, buyPrice(0, 2));
     }
References buyPrice(), consumable, DefaultToThrownWeapon(), Entity.height, maxStack, noUseGraphic, ranged, SetShopValues(), and Entity.width.
Referenced by SetDefaults5().