Terraria: Item.MakeUsableWithChlorophyteExtractinator
MakeUsableWithChlorophyteExtractinator()
void Item.MakeUsableWithChlorophyteExtractinator () inline
     {
         useStyle = 1;
         useAnimation = 15;
         useTime = 10;
         chlorophyteExtractinatorConsumable = true;
         autoReuse = true;
         consumable = true;
     }
References autoReuse, chlorophyteExtractinatorConsumable, consumable, useAnimation, useStyle, and useTime.
Referenced by SetDefaults1(), SetDefaults2(), and SetDefaults3().