Terraria: Item.GetShimmered
GetShimmered()
void Item.GetShimmered () inline private
     {
         int shimmerEquivalentType = GetShimmerEquivalentType();
         int decraftingRecipeIndex = ShimmerTransforms.GetDecraftingRecipeIndex(shimmerEquivalentType);
         if (ItemID.Sets.CommonCoin[shimmerEquivalentType])
         {
             switch (shimmerEquivalentType)
             {
             case 72:
                 stack *= 100;
                 break;
             case 73:
                 stack *= 10000;
                 break;
             case 74:
                 if (stack > 1)
                 {
                     stack = 1;
                 }
                 stack *= 1000000;
                 break;
             }
             Main.player[Main.myPlayer].AddCoinLuck(base.Center, stack);
             NetMessage.SendData(146, -1, -1, null, 1, (int)base.Center.X, (int)base.Center.Y, stack);
             type = 0;
             stack = 0;
         }
         else if (shimmerEquivalentType == 1326 && NPC.downedMoonlord)
         {
             int num = stack;
             SetDefaults(5335);
             stack = num;
             shimmered = true;
         }
         else if (shimmerEquivalentType == 779 && NPC.downedMoonlord)
         {
             int num2 = stack;
             SetDefaults(5134);
             stack = num2;
             shimmered = true;
         }
         else if (shimmerEquivalentType == 3031 && NPC.downedMoonlord)
         {
             int num3 = stack;
             SetDefaults(5364);
             stack = num3;
             shimmered = true;
         }
         else if (shimmerEquivalentType == 5364 && NPC.downedMoonlord)
         {
             int num4 = stack;
             SetDefaults(3031);
             stack = num4;
             shimmered = true;
         }
         else if (shimmerEquivalentType == 3461)
         {
             short num5 = 3461;
             num5 = Main.GetMoonPhase() switch
             {
                 MoonPhase.QuarterAtRight => 5407,
                 MoonPhase.HalfAtRight => 5405,
                 MoonPhase.ThreeQuartersAtRight => 5404,
                 MoonPhase.Full => 5408,
                 MoonPhase.ThreeQuartersAtLeft => 5401,
                 MoonPhase.HalfAtLeft => 5403,
                 MoonPhase.QuarterAtLeft => 5402,
                 _ => 5406,
             };
             int num6 = stack;
             SetDefaults(num5);
             stack = num6;
             shimmered = true;
         }
         else if (createTile == 139)
         {
             int num7 = stack;
             SetDefaults(576);
             stack = num7;
             shimmered = true;
         }
         else if (ItemID.Sets.ShimmerTransformToItem[shimmerEquivalentType] > 0)
         {
             int num8 = stack;
             SetDefaults(ItemID.Sets.ShimmerTransformToItem[shimmerEquivalentType]);
             stack = num8;
             shimmered = true;
         }
         else if (type == 4986)
         {
             if (NPC.unlockedSlimeRainbowSpawn)
             {
                 return;
             }
             NPC.unlockedSlimeRainbowSpawn = true;
             NetMessage.SendData(7);
             int num9 = NPC.NewNPC(GetNPCSource_FromThis(), (int)base.Center.X + 4, (int)base.Center.Y, 681);
             if (num9 >= 0)
             {
                 NPC obj = Main.npc[num9];
                 obj.velocity = velocity;
                 obj.netUpdate = true;
                 obj.shimmerTransparency = 1f;
                 NetMessage.SendData(146, -1, -1, null, 2, num9);
             }
             WorldGen.CheckAchievement_RealEstateAndTownSlimes();
             stack--;
             if (stack <= 0)
             {
                 type = 0;
             }
         }
         else if (makeNPC > 0)
         {
             int num10 = 50;
             int highestNPCSlotIndexWeWillPick = 200;
             int num11 = NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(stack, highestNPCSlotIndexWeWillPick);
             while (num10 > 0 && num11 > 0 && stack > 0)
             {
                 num10--;
                 num11--;
                 stack--;
                 int num12 = -1;
                 num12 = ((NPCID.Sets.ShimmerTransformToNPC[makeNPC] < 0) ? NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y, makeNPC, placeStyle, Main.myPlayer) : NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y, NPCID.Sets.ShimmerTransformToNPC[makeNPC], 0, Main.myPlayer));
                 if (num12 >= 0)
                 {
                     Main.npc[num12].shimmerTransparency = 1f;
                     NetMessage.SendData(146, -1, -1, null, 2, num12);
                 }
             }
             shimmered = true;
             if (stack <= 0)
             {
                 type = 0;
             }
         }
         else if (decraftingRecipeIndex >= 0)
         {
             int num13 = FindDecraftAmount();
             Recipe recipe = Main.recipe[decraftingRecipeIndex];
             int num14 = 0;
             bool flag = recipe.requiredItem[1].stack > 0;
             IEnumerable<Item> enumerable = recipe.requiredItem;
             if (recipe.customShimmerResults != null)
             {
                 enumerable = recipe.customShimmerResults;
             }
             int num15 = 0;
             foreach (Item item2 in enumerable)
             {
                 if (item2.type <= 0)
                 {
                     break;
                 }
                 num15++;
                 int num16 = num13 * item2.stack;
                 if (recipe.alchemy)
                 {
                     for (int num17 = num16; num17 > 0; num17--)
                     {
                         if (Main.rand.Next(3) == 0)
{
                             num16--;
                         }
                     }
                 }
                 while (num16 > 0)
                 {
                     int num18 = num16;
                     if (num18 > 9999)
                     {
                         num18 = 9999;
                     }
                     num16 -= num18;
                     int num19 = NewItem(GetItemSource_Misc(8), (int)position.X, (int)position.Y, width, height, item2.type);
                     Item item = Main.item[num19];
                     item.stack = num18;
                     item.shimmerTime = 1f;
                     item.shimmered = true;
                     item.shimmerWet = true;
                     item.wet = true;
                     item.velocity *= 0.1f;
                     item.playerIndexTheItemIsReservedFor = Main.myPlayer;
                     if (flag)
                     {
                         item.velocity.X = 1f * (float)num15;
                         item.velocity.X *= 1f + (float)num15 * 0.05f;
                         if (num14 % 2 == 0)
{
                             item.velocity.X *= -1f;
                         }
                     }
                     NetMessage.SendData(145, -1, -1, null, num19, 1f);
                 }
             }
             stack -= num13 * recipe.createItem.stack;
             if (stack <= 0)
             {
                 stack = 0;
                 type = 0;
             }
         }
         if (stack > 0)
         {
             shimmerTime = 1f;
         }
         else
         {
             shimmerTime = 0f;
         }
         shimmerWet = true;
         wet = true;
         velocity *= 0.1f;
         if (Main.netMode == 0)
         {
             ShimmerEffect(base.Center);
         }
         else
         {
             NetMessage.SendData(146, -1, -1, null, 0, (int)base.Center.X, (int)base.Center.Y);
             NetMessage.SendData(145, -1, -1, null, whoAmI, 1f);
         }
         AchievementsHelper.NotifyProgressionEvent(27);
         if (stack == 0)
         {
             makeNPC = -1;
             active = false;
         }
     }
References Entity.active, Player.AddCoinLuck(), WorldGen.CheckAchievement_RealEstateAndTownSlimes(), ItemID.Sets.CommonCoin, createTile, Recipe.customShimmerResults, NPC.downedMoonlord, FindDecraftAmount(), NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(), ShimmerTransforms.GetDecraftingRecipeIndex(), GetItemSource_Misc(), Main.GetMoonPhase(), GetNPCSource_FromThis(), GetShimmerEquivalentType(), Entity.height, Main.item, makeNPC, Main.myPlayer, Main.netMode, NPC.netUpdate, NewItem(), NPC.NewNPC(), UnifiedRandom.Next(), AchievementsHelper.NotifyProgressionEvent(), Main.npc, placeStyle, Main.player, playerIndexTheItemIsReservedFor, Entity.position, Main.rand, Main.recipe, NPC.ReleaseNPC(), Recipe.requiredItem, NetMessage.SendData(), SetDefaults(), shimmered, ShimmerEffect(), shimmerTime, ItemID.Sets.ShimmerTransformToItem, NPCID.Sets.ShimmerTransformToNPC, NPC.shimmerTransparency, Entity.shimmerWet, stack, type, NPC.unlockedSlimeRainbowSpawn, Entity.velocity, Entity.wet, Entity.whoAmI, and Entity.width.
Referenced by Shimmering().