Terraria: Item.SetDefaults
SetDefaults() [2/2]
void Item.SetDefaults (int Type = 0) inline
     {
         SetDefaults(Type, noMatCheck: false, null);
     }
Referenced by UIBestiaryInfoItemLine.UIBestiaryInfoItemLine(), Recipe.AddAshWoodFurnitureArmorAndItems(), Recipe.AddBalloonFurniture(), Recipe.AddBambooFurniture(), WorldGen.AddBuriedChest(), Recipe.AddCoralFurniture(), Recipe.AddCustomShimmerResult(), Recipe.AddLesionFurniture(), Recipe.AddNebulaFurniture(), Recipe.AddSandstoneFurniture(), Recipe.AddSolarFurniture(), Recipe.AddSpiderFurniture(), Recipe.AddStardustFurniture(), Recipe.AddVortexFurniture(), Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Player.ApplyCoating(), Player.ApplyEquipFunctional(), Player.ApplyPaint(), Player.ApplyWilsonBeard(), Lang.BartenderHelpText(), NPC.CatchNPC(), ChangeItemType(), CombineWithNearbyItems(), Recipe.CreateReversePlatformRecipes(), Recipe.CreateReverseWallRecipes(), ChestUI.DepositAll(), Player.Deserialize(), AchievementAdvisor.DrawMouseHover(), ItemSlot.DrawRadialQuicks(), UIDynamicItemCollection.DrawSelf(), TitleLinkButton.DrawTooltip(), DropCache(), DSTFilm.EquipDSTShaderItem(), WorldGen.FinishDrunkGen(), WorldGen.FinishGetGoodWorld(), WorldGen.FinishNoTraps(), Projectile.FishingCheck(), FixAgainstExploit(), Player.GetAnglerReward_Bait(), Player.GetAnglerReward_Decoration(), Player.GetAnglerReward_MainReward(), Player.GetAnglerReward_Money(), Player.GetDyeTraderReward(), GetPickedUpByMonsters_Money(), GetPickedUpByMonsters_Special(), GetShimmered(), ItemSlot.HandleShopSlot(), ContentSamples.Initialize(), Main.Initialize_Items(), Player.ItemCheck_ApplyHoldStyle(), Player.ItemCheck_CheckFishingBobber_PickAndConsumeBait(), Player.ItemCheck_TryPlacingWearablesOnMannequins(), Player.ItemCheck_UseWiringTools(), ItemSlot.LeftClick(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), ChestUI.MoveCoins(), netDefaults(), NewItem(), OnCreated(), ItemSlot.OverrideLeftClick(), ItemSlot.PickupItemIntoMouse(), TEFoodPlatter.PlaceItemInFrame(), TEItemFrame.PlaceItemInFrame(), TEWeaponsRack.PlaceItemInFrame(), Player.PlaceWeapon(), ItemTransferParticle.Prepare(), NPCKillCounterInfoElement.ProvideUIElement(), Player.PutItemInInventoryFromItemUsage(), Chest.PutItemInNearbyChest(), ChestUI.QuickStack(), TEDisplayDoll.ReadItem(), TEHatRack.ReadItem(), NetMessage.SendData(), ContentSamples.CreativeHelper.SetCreativeMenuOrder(), SetDefaults(), SetDefaults4(), SetDefaults5(), Recipe.SetIngredients(), TEDisplayDoll.SetInventoryFromMannequin(), UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty(), Recipe.SetupRecipes(), Chest.SetupShop(), ItemSorting.SortCoins(), ItemSlot.TryOpenContainer(), ItemSlot.TryPickupDyeToCursor(), DeadMansChestBiome.TurnGoldChestIntoDeadMansChest(), TurnToAir(), and Recipe.UpdateWhichItemsAreMaterials().