Terraria: Item.TryCombiningIntoNearbyItems
TryCombiningIntoNearbyItems()
void Item.TryCombiningIntoNearbyItems (int i) inline
     {
         bool flag = true;
         int num = type;
         if ((uint)(num - 71) <= 3u)
         {
             flag = false;
         }
         if (ItemID.Sets.NebulaPickup[type])
         {
             flag = false;
         }
         if (playerIndexTheItemIsReservedFor == Main.myPlayer && flag)
         {
             CombineWithNearbyItems(i);
         }
     }
References CombineWithNearbyItems(), Main.myPlayer, ItemID.Sets.NebulaPickup, playerIndexTheItemIsReservedFor, and type.
Referenced by WorldGen.KillTile_DropItems(), and UpdateItem().