Terraria: Item.GetRollablePrefixes
GetRollablePrefixes()
int [] Item.GetRollablePrefixes () inline
     {
         _ = type;
         if (PrefixLegacy.ItemSets.SwordsHammersAxesPicks[type])
         {
             return PrefixLegacy.Prefixes.PrefixesForSwords;
         }
         if (PrefixLegacy.ItemSets.SpearsMacesChainsawsDrillsPunchCannon[type])
         {
             return PrefixLegacy.Prefixes.PrefixesForSpears;
         }
         if (PrefixLegacy.ItemSets.GunsBows[type])
         {
             return PrefixLegacy.Prefixes.PrefixesForGunsBows;
         }
         if (PrefixLegacy.ItemSets.MagicAndSummon[type])
         {
             return PrefixLegacy.Prefixes.PrefixesForMagicAndSummons;
         }
         if (PrefixLegacy.ItemSets.BoomerangsChakrams[type])
         {
             return PrefixLegacy.Prefixes.PrefixesForBoomeransAndChakrums;
         }
         if (PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2[type])
         {
             return PrefixLegacy.Prefixes.PrefixesForBoomeransAndChakrums_TerrarianYoyo;
         }
         if (IsAPrefixableAccessory())
         {
             return PrefixLegacy.Prefixes.PrefixesForAccessories;
         }
         return null;
     }
References PrefixLegacy.ItemSets.BoomerangsChakrams, PrefixLegacy.ItemSets.GunsBows, IsAPrefixableAccessory(), PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2, PrefixLegacy.ItemSets.MagicAndSummon, PrefixLegacy.Prefixes.PrefixesForAccessories, PrefixLegacy.Prefixes.PrefixesForBoomeransAndChakrums, PrefixLegacy.Prefixes.PrefixesForBoomeransAndChakrums_TerrarianYoyo, PrefixLegacy.Prefixes.PrefixesForGunsBows, PrefixLegacy.Prefixes.PrefixesForMagicAndSummons, PrefixLegacy.Prefixes.PrefixesForSpears, PrefixLegacy.Prefixes.PrefixesForSwords, PrefixLegacy.ItemSets.SpearsMacesChainsawsDrillsPunchCannon, PrefixLegacy.ItemSets.SwordsHammersAxesPicks, and type.
Referenced by CanRollPrefix(), and RollAPrefix().