Terraria: Item.OnCreated
OnCreated()
void Item.OnCreated (ItemCreationContext context) inline
     {
         if (type == 5437)
         {
             SetDefaults(5358);
         }
     }
References SetDefaults(), and type.
Referenced by Main.CraftItem(), ItemSlot.LeftClick(), ItemSlot.OverrideLeftClick(), and ItemSlot.PickupItemIntoMouse().