Terraria: Item.DefaultToSeaShell
DefaultToSeaShell()
void Item.DefaultToSeaShell () inline private
     {
         useStyle = 1;
         autoReuse = true;
         useAnimation = 15;
         useTime = 10;
         maxStack = CommonMaxStack;
         consumable = true;
         createTile = 324;
         width = 22;
         height = 22;
         switch (type)
         {
         case 4071:
             placeStyle = 4;
             value = sellPrice(0, 1);
             break;
         case 4073:
             placeStyle = 3;
             value = sellPrice(0, 0, 20);
             break;
         case 4072:
             placeStyle = 2;
             value = sellPrice(0, 0, 20);
             break;
         case 2626:
             placeStyle = 1;
             value = sellPrice(0, 0, 10);
             break;
         default:
             value = sellPrice(0, 0, 5);
             break;
         }
     }
References autoReuse, CommonMaxStack, consumable, createTile, Entity.height, maxStack, placeStyle, sellPrice(), type, useAnimation, useStyle, useTime, value, and Entity.width.
Referenced by SetDefaults3(), and SetDefaults5().