Terraria: Item.DespawnIfMeetingConditions
DespawnIfMeetingConditions()
void Item.DespawnIfMeetingConditions (int i) inline private
     {
         if (type == 75 && Main.dayTime && !Main.remixWorld && !shimmered && !beingGrabbed)
         {
             for (int j = 0; j < 10; j++)
             {
                 Dust.NewDust(position, width, height, 15, velocity.X, velocity.Y, 150, default(Color), 1.2f);
             }
             for (int k = 0; k < 3; k++)
             {
                 Gore.NewGore(position, new Vector2(velocity.X, velocity.Y), Main.rand.Next(16, 18));
             }
             active = false;
             type = 0;
             stack = 0;
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(21, -1, -1, null, i);
             }
         }
         if (type == 4143 && timeSinceItemSpawned > 300)
         {
             for (int l = 0; l < 20; l++)
             {
                 Dust.NewDust(position, width, height, 15, velocity.X, velocity.Y, 150, Color.Lerp(Color.CornflowerBlue, Color.Indigo, Main.rand.NextFloat()), 1.2f);
             }
             active = false;
             type = 0;
             stack = 0;
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(21, -1, -1, null, i);
             }
         }
         if (type == 3822 && !DD2Event.Ongoing)
         {
             int num = Main.rand.Next(18, 24);
             for (int m = 0; m < num; m++)
             {
                 int num2 = Dust.NewDust(base.Center, 0, 0, 61, 0f, 0f, 0, default(Color), 1.7f);
                 Main.dust[num2].velocity *= 8f;
                 Main.dust[num2].velocity.Y -= 1f;
                 Main.dust[num2].position = Vector2.Lerp(Main.dust[num2].position, base.Center, 0.5f);
                 Main.dust[num2].noGravity = true;
                 Main.dust[num2].noLight = true;
             }
             active = false;
             type = 0;
             stack = 0;
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(21, -1, -1, null, i);
             }
         }
     }
References Entity.active, beingGrabbed, Color, Main.dayTime, Main.dust, Entity.height, Main.netMode, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, DD2Event.Ongoing, Dust.position, Entity.position, Main.rand, Main.remixWorld, NetMessage.SendData(), shimmered, stack, timeSinceItemSpawned, type, Dust.velocity, Entity.velocity, and Entity.width.
Referenced by UpdateItem().