Terraria: System.Diagnostics.Tracing.NameInfo.NameInfo
NameInfo()
System.Diagnostics.Tracing.NameInfo.NameInfo (string name, EventTags tags, int typeMetadataSize) inline
Definition at line 31 of file NameInfo.cs.
    {
        this.name = name;
        this.tags = tags & (EventTags)268435455;
        identity = Interlocked.Increment(ref lastIdentity);
        int pos = 0;
        Statics.EncodeTags((int)this.tags, ref pos, null);
        nameMetadata = Statics.MetadataForString(name, pos, 0, typeMetadataSize);
        pos = 2;
        Statics.EncodeTags((int)this.tags, ref pos, nameMetadata);
    }
References System.Diagnostics.Tracing.Statics.EncodeTags(), System.Diagnostics.Tracing.NameInfo.identity, System.Threading.Interlocked.Increment(), System.Diagnostics.Tracing.NameInfo.lastIdentity, System.Diagnostics.Tracing.Statics.MetadataForString(), System.Diagnostics.Tracing.NameInfo.name, System.Diagnostics.Tracing.NameInfo.nameMetadata, and System.Diagnostics.Tracing.NameInfo.tags.