Terraria: System.Diagnostics.Tracing.NameInfo.ReserveEventIDsBelow
ReserveEventIDsBelow()
static void System.Diagnostics.Tracing.NameInfo.ReserveEventIDsBelow (int eventId) inline static package
Definition at line 18 of file NameInfo.cs.
    {
        int num;
        int val;
        do
        {
            num = lastIdentity;
            val = (lastIdentity & -16777216) + eventId;
            val = Math.Max(val, num);
        }
        while (Interlocked.CompareExchange(ref lastIdentity, val, num) != num);
    }
References System.Threading.Interlocked.CompareExchange(), System.Diagnostics.Tracing.NameInfo.lastIdentity, and System.Math.Max().
Referenced by System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors().