Terraria: System.Xml.XsdValidatingReader.GetIsDefault
GetIsDefault()
void System.Xml.XsdValidatingReader.GetIsDefault () inline private
Definition at line 1987 of file XsdValidatingReader.cs.
    {
        XsdCachingReader xsdCachingReader = _coreReader as XsdCachingReader;
        if (xsdCachingReader != null || !_xmlSchemaInfo.HasDefaultValue)
        {
            return;
        }
        _coreReader = GetCachingReader();
        if (_xmlSchemaInfo.IsUnionType && !_xmlSchemaInfo.IsNil)
        {
            ReadAheadForMemberType();
        }
        else if (_coreReader.Read())
        {
            switch (_coreReader.NodeType)
            {
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
                _validator.ValidateText(_valueGetter);
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                _validator.ValidateWhitespace(_valueGetter);
                break;
            case XmlNodeType.EndElement:
                _atomicValue = _validator.ValidateEndElement(_xmlSchemaInfo);
                _originalAtomicValueString = GetOriginalAtomicValueStringOfElement();
                if (_xmlSchemaInfo.IsDefault)
                {
                    _cachingReader.SwitchTextNodeAndEndElement(_xmlSchemaInfo.XmlType.ValueConverter.ToString(_atomicValue), _originalAtomicValueString);
                }
                break;
            }
        }
        _cachingReader.SetToReplayMode();
        _replayCache = true;
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._cachingReader, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._replayCache, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._valueGetter, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.XsdValidatingReader.GetCachingReader(), System.Xml.XsdValidatingReader.GetOriginalAtomicValueStringOfElement(), System.Xml.Schema.XmlSchemaInfo.HasDefaultValue, System.Xml.Schema.XmlSchemaInfo.IsDefault, System.Xml.Schema.XmlSchemaInfo.IsNil, System.Xml.Schema.XmlSchemaInfo.IsUnionType, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XsdValidatingReader.ReadAheadForMemberType(), System.Xml.XsdCachingReader.SetToReplayMode(), System.Xml.XsdCachingReader.SwitchTextNodeAndEndElement(), System.Xml.Schema.XmlValueConverter.ToString(), System.Xml.Schema.XmlSchemaValidator.ValidateEndElement(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace(), System.Xml.Schema.XmlSchemaType.ValueConverter, and System.Xml.Schema.XmlSchemaInfo.XmlType.