Terraria: System.Xml.XsdValidatingReader.XsdValidatingReader
XsdValidatingReader() [1/2]
System.Xml.XsdValidatingReader.XsdValidatingReader (XmlReader reader, XmlResolver xmlResolver, XmlReaderSettings readerSettings, XmlSchemaObject partialValidationType) inline package
Definition at line 470 of file XsdValidatingReader.cs.
    {
        _coreReader = reader;
        _coreReaderNSResolver = reader as IXmlNamespaceResolver;
        _lineInfo = reader as IXmlLineInfo;
        _coreReaderNameTable = _coreReader.NameTable;
        if (_coreReaderNSResolver == null)
        {
            _nsManager = new XmlNamespaceManager(_coreReaderNameTable);
            _manageNamespaces = true;
        }
        _thisNSResolver = this;
        _xmlResolver = xmlResolver;
        _processInlineSchema = (readerSettings.ValidationFlags & XmlSchemaValidationFlags.ProcessInlineSchema) != 0;
        _validationState = ValidatingReaderState.Init;
        _defaultAttributes = new ArrayList();
        _currentAttrIndex = -1;
        _attributePSVINodes = new AttributePSVIInfo[8];
        _valueGetter = GetStringValue;
        s_typeOfString = typeof(string);
        _xmlSchemaInfo = new XmlSchemaInfo();
        _nsXmlNs = _coreReaderNameTable.Add("http://www.w3.org/2000/xmlns/");
        _nsXs = _coreReaderNameTable.Add("http://www.w3.org/2001/XMLSchema");
        _nsXsi = _coreReaderNameTable.Add("http://www.w3.org/2001/XMLSchema-instance");
        _xsiType = _coreReaderNameTable.Add("type");
        _xsiNil = _coreReaderNameTable.Add("nil");
        _xsiSchemaLocation = _coreReaderNameTable.Add("schemaLocation");
        _xsiNoNamespaceSchemaLocation = _coreReaderNameTable.Add("noNamespaceSchemaLocation");
        _xsdSchema = _coreReaderNameTable.Add("schema");
        SetupValidator(readerSettings, reader, partialValidationType);
        _validationEvent = readerSettings.GetEventHandler();
    }
References System.Xml.XsdValidatingReader._attributePSVINodes, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._coreReaderNameTable, System.Xml.XsdValidatingReader._coreReaderNSResolver, System.Xml.XsdValidatingReader._currentAttrIndex, System.Xml.XsdValidatingReader._defaultAttributes, System.Xml.XsdValidatingReader._lineInfo, System.Xml.XsdValidatingReader._manageNamespaces, System.Xml.XsdValidatingReader._nsManager, System.Xml.XsdValidatingReader._nsXmlNs, System.Xml.XsdValidatingReader._nsXs, System.Xml.XsdValidatingReader._nsXsi, System.Xml.XsdValidatingReader._processInlineSchema, System.Xml.XsdValidatingReader._thisNSResolver, System.Xml.XsdValidatingReader._validationEvent, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._valueGetter, System.Xml.XsdValidatingReader._xmlResolver, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.XsdValidatingReader._xsdSchema, System.Xml.XsdValidatingReader._xsiNil, System.Xml.XsdValidatingReader._xsiNoNamespaceSchemaLocation, System.Xml.XsdValidatingReader._xsiSchemaLocation, System.Xml.XsdValidatingReader._xsiType, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, System.Xml.XsdValidatingReader.GetStringValue(), System.Xml.XmlReader.NameTable, System.Xml.XsdValidatingReader.s_typeOfString, and System.Xml.XsdValidatingReader.SetupValidator().