Terraria: System.Xml.XsdValidatingReader.ReadAsync
ReadAsync()
override Task< bool > System.Xml.XsdValidatingReader.ReadAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 2313 of file XsdValidatingReader.cs.
    {
        switch (_validationState)
        {
        case ValidatingReaderState.Read:
        {
            Task<bool> task = _coreReader.ReadAsync();
            return ReadAsync_Read(task);
        }
        case ValidatingReaderState.ParseInlineSchema:
            return ProcessInlineSchemaAsync().ReturnTrueTaskWhenFinishAsync();
        case ValidatingReaderState.OnReadAttributeValue:
        case ValidatingReaderState.OnDefaultAttribute:
        case ValidatingReaderState.OnAttribute:
        case ValidatingReaderState.ClearAttributes:
            ClearAttributesInfo();
            if (_inlineSchemaParser != null)
            {
                _validationState = ValidatingReaderState.ParseInlineSchema;
                goto case ValidatingReaderState.ParseInlineSchema;
            }
            _validationState = ValidatingReaderState.Read;
            goto case ValidatingReaderState.Read;
        case ValidatingReaderState.ReadAhead:
        {
            ClearAttributesInfo();
            Task task2 = ProcessReaderEventAsync();
            return ReadAsync_ReadAhead(task2);
        }
        case ValidatingReaderState.OnReadBinaryContent:
            _validationState = _savedState;
            return _readBinaryHelper.FinishAsync().CallBoolTaskFuncWhenFinishAsync((XsdValidatingReader thisRef) => thisRef.ReadAsync(), this);
        case ValidatingReaderState.Init:
            _validationState = ValidatingReaderState.Read;
            if (_coreReader.ReadState == ReadState.Interactive)
            {
                return ProcessReaderEventAsync().ReturnTrueTaskWhenFinishAsync();
            }
            goto case ValidatingReaderState.Read;
        case ValidatingReaderState.ReaderClosed:
        case ValidatingReaderState.EOF:
            return AsyncHelper.DoneTaskFalse;
        default:
            return AsyncHelper.DoneTaskFalse;
        }
    }
References System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._inlineSchemaParser, System.Xml.XsdValidatingReader._readBinaryHelper, System.Xml.XsdValidatingReader._savedState, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader.ClearAttributesInfo(), System.Xml.AsyncHelper.DoneTaskFalse, System.Xml.ReadContentAsBinaryHelper.FinishAsync(), System.Xml.XsdValidatingReader.ProcessInlineSchemaAsync(), System.Xml.XsdValidatingReader.ProcessReaderEventAsync(), System.Xml.XmlReader.ReadAsync(), System.Xml.XsdValidatingReader.ReadAsync_Read(), System.Xml.XsdValidatingReader.ReadAsync_ReadAhead(), System.Xml.XmlReader.ReadState, and System.task.
Referenced by System.Xml.XsdValidatingReader.InternalReadElementContentAsObjectTupleAsync(), and System.Xml.XsdValidatingReader.SkipAsync().