Terraria: System.Xml.XsdValidatingReader.GetDefaultAttribute
GetDefaultAttribute() [2/2]
ValidatingReaderNodeData System.Xml.XsdValidatingReader.GetDefaultAttribute (string name, bool updatePosition) inline private
Definition at line 1710 of file XsdValidatingReader.cs.
    {
        ValidateNames.SplitQName(name, out var prefix, out var lname);
        prefix = _coreReaderNameTable.Add(prefix);
        lname = _coreReaderNameTable.Add(lname);
        string ns = ((prefix.Length != 0) ? _thisNSResolver.LookupNamespace(prefix) : string.Empty);
        return GetDefaultAttribute(lname, ns, updatePosition);
    }
References System.Xml.XsdValidatingReader._coreReaderNameTable, System.Xml.XsdValidatingReader._thisNSResolver, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, System.Xml.XsdValidatingReader.GetDefaultAttribute(), System.Xml.IXmlNamespaceResolver.LookupNamespace(), System.prefix, and System.Xml.ValidateNames.SplitQName().
Referenced by System.Xml.XsdValidatingReader.GetAttribute(), System.Xml.XsdValidatingReader.GetAttribute(), System.Xml.XsdValidatingReader.GetDefaultAttribute(), System.Xml.XsdValidatingReader.MoveToAttribute(), and System.Xml.XsdValidatingReader.MoveToAttribute().