Terraria: System.Xml.XsdValidatingReader.ReadContentAsDouble
ReadContentAsDouble()
override double System.Xml.XsdValidatingReader.ReadContentAsDouble () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 593 of file XsdValidatingReader.cs.
    {
        if (!XmlReader.CanReadContentAs(NodeType))
        {
            throw CreateReadContentAsException("ReadContentAsDouble");
        }
        object value = InternalReadContentAsObject();
        XmlSchemaType xmlSchemaType = ((NodeType == XmlNodeType.Attribute) ? AttributeXmlType : ElementXmlType);
        try
        {
            return xmlSchemaType?.ValueConverter.ToDouble(value) ?? XmlUntypedConverter.Untyped.ToDouble(value);
        }
        catch (InvalidCastException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Double", innerException, this);
        }
        catch (FormatException innerException2)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Double", innerException2, this);
        }
        catch (OverflowException innerException3)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "Double", innerException3, this);
        }
    }
References System.Xml.XsdValidatingReader.AttributeXmlType, System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.XsdValidatingReader.ElementXmlType, System.Xml.XsdValidatingReader.InternalReadContentAsObject(), System.Xml.XsdValidatingReader.NodeType, System.Xml.Schema.XmlUntypedConverter.Untyped, System.value, System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.