Terraria: System.Xml.XsdValidatingReader.InternalReadContentAsObject
InternalReadContentAsObject() [1/3]
object System.Xml.XsdValidatingReader.InternalReadContentAsObject () inline private
Definition at line 1792 of file XsdValidatingReader.cs.
    {
        return InternalReadContentAsObject(unwrapTypedValue: false);
    }
References System.Xml.XsdValidatingReader.InternalReadContentAsObject().
Referenced by System.Xml.XsdValidatingReader.InternalReadContentAsObject(), System.Xml.XsdValidatingReader.InternalReadContentAsObject(), System.Xml.XsdValidatingReader.InternalReadElementContentAsObject(), System.Xml.XsdValidatingReader.ReadContentAs(), System.Xml.XsdValidatingReader.ReadContentAsBoolean(), System.Xml.XsdValidatingReader.ReadContentAsDateTime(), System.Xml.XsdValidatingReader.ReadContentAsDecimal(), System.Xml.XsdValidatingReader.ReadContentAsDouble(), System.Xml.XsdValidatingReader.ReadContentAsFloat(), System.Xml.XsdValidatingReader.ReadContentAsInt(), System.Xml.XsdValidatingReader.ReadContentAsLong(), System.Xml.XsdValidatingReader.ReadContentAsObject(), and System.Xml.XsdValidatingReader.ReadContentAsString().