Terraria: System.Xml.XsdValidatingReader.ClearAttributesInfo
ClearAttributesInfo()
void System.Xml.XsdValidatingReader.ClearAttributesInfo () inline private
Definition at line 1673 of file XsdValidatingReader.cs.
    {
        _attributeCount = 0;
        _coreReaderAttributeCount = 0;
        _currentAttrIndex = -1;
        _defaultAttributes.Clear();
        _attributePSVI = null;
    }
References System.Xml.XsdValidatingReader._attributeCount, System.Xml.XsdValidatingReader._attributePSVI, System.Xml.XsdValidatingReader._coreReaderAttributeCount, System.Xml.XsdValidatingReader._currentAttrIndex, System.Xml.XsdValidatingReader._defaultAttributes, and System.Collections.ArrayList.Clear().
Referenced by System.Xml.XsdValidatingReader.ProcessInlineSchema(), System.Xml.XsdValidatingReader.ProcessInlineSchemaAsync(), System.Xml.XsdValidatingReader.Read(), and System.Xml.XsdValidatingReader.ReadAsync().