Terraria: System.Xml.XsdValidatingReader.GetAttribute
GetAttribute() [3/4]
override string System.Xml.XsdValidatingReader.GetAttribute (string name, string namespaceURI) inline
Definition at line 1059 of file XsdValidatingReader.cs.
    {
        string attribute = _coreReader.GetAttribute(name, namespaceURI);
        if (attribute == null && _attributeCount > 0)
        {
            string text = ((namespaceURI == null) ? string.Empty : _coreReaderNameTable.Get(namespaceURI));
            string text2 = _coreReaderNameTable.Get(name);
            if (text2 == null || text == null)
            {
                return null;
            }
            ValidatingReaderNodeData defaultAttribute = GetDefaultAttribute(text2, text, updatePosition: false);
            if (defaultAttribute != null)
            {
                return defaultAttribute.RawValue;
            }
        }
        return attribute;
    }
References System.Xml.XsdValidatingReader._attributeCount, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._coreReaderNameTable, System.Xml.Dictionary, System.Xml.XmlNameTable.Get(), System.Xml.XmlReader.GetAttribute(), System.Xml.XsdValidatingReader.GetDefaultAttribute(), and System.text.