Terraria: System.Xml.XsdValidatingReader.GetMemberType
GetMemberType()
void System.Xml.XsdValidatingReader.GetMemberType () inline private
Definition at line 2025 of file XsdValidatingReader.cs.
    {
        if (_xmlSchemaInfo.MemberType == null && _atomicValue != this)
        {
            XsdCachingReader xsdCachingReader = _coreReader as XsdCachingReader;
            if (xsdCachingReader == null && _xmlSchemaInfo.IsUnionType && !_xmlSchemaInfo.IsNil)
            {
                _coreReader = GetCachingReader();
                ReadAheadForMemberType();
                _cachingReader.SetToReplayMode();
                _replayCache = true;
            }
        }
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._cachingReader, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._replayCache, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.XsdValidatingReader.GetCachingReader(), System.Xml.Schema.XmlSchemaInfo.IsNil, System.Xml.Schema.XmlSchemaInfo.IsUnionType, System.Xml.Schema.XmlSchemaInfo.MemberType, System.Xml.XsdValidatingReader.ReadAheadForMemberType(), and System.Xml.XsdCachingReader.SetToReplayMode().