Terraria: System.Xml.XsdValidatingReader.MoveToAttribute
MoveToAttribute() [3/4]
override bool System.Xml.XsdValidatingReader.MoveToAttribute (string name, string ns) inline
Definition at line 1123 of file XsdValidatingReader.cs.
    {
        string text = _coreReaderNameTable.Get(name);
        ns = ((ns != null) ? _coreReaderNameTable.Get(ns) : string.Empty);
        if (text == null || ns == null)
        {
            return false;
        }
        if (_coreReader.MoveToAttribute(text, ns))
        {
            _validationState = ValidatingReaderState.OnAttribute;
            if (_inlineSchemaParser == null)
            {
                _attributePSVI = GetAttributePSVI(text, ns);
            }
            else
            {
                _attributePSVI = null;
            }
        }
        else
        {
            ValidatingReaderNodeData defaultAttribute = GetDefaultAttribute(text, ns, updatePosition: true);
            if (defaultAttribute == null)
            {
                return false;
            }
            _attributePSVI = defaultAttribute.AttInfo;
            _cachedNode = defaultAttribute;
            _validationState = ValidatingReaderState.OnDefaultAttribute;
        }
        if (_validationState == ValidatingReaderState.OnReadBinaryContent)
        {
            _readBinaryHelper.Finish();
            _validationState = _savedState;
        }
        return true;
    }
References System.Xml.XsdValidatingReader._attributePSVI, System.Xml.XsdValidatingReader._cachedNode, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._coreReaderNameTable, System.Xml.XsdValidatingReader._inlineSchemaParser, System.Xml.XsdValidatingReader._readBinaryHelper, System.Xml.XsdValidatingReader._savedState, System.Xml.XsdValidatingReader._validationState, System.Xml.Dictionary, System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XmlNameTable.Get(), System.Xml.XsdValidatingReader.GetAttributePSVI(), System.Xml.XsdValidatingReader.GetDefaultAttribute(), System.Xml.XmlReader.MoveToAttribute(), and System.text.