Terraria: System.Xml.XsdValidatingReader.ProcessEndElementEventAsync
ProcessEndElementEventAsync()
async Task System.Xml.XsdValidatingReader.ProcessEndElementEventAsync () inline private
Definition at line 2564 of file XsdValidatingReader.cs.
    {
        _atomicValue = _validator.ValidateEndElement(_xmlSchemaInfo);
        _originalAtomicValueString = GetOriginalAtomicValueStringOfElement();
        if (_xmlSchemaInfo.IsDefault)
        {
            int depth = _coreReader.Depth;
            _coreReader = GetCachingReader();
            _cachingReader.RecordTextNode(_xmlSchemaInfo.XmlType.ValueConverter.ToString(_atomicValue), _originalAtomicValueString, depth + 1, 0, 0);
            _cachingReader.RecordEndElementNode();
            await _cachingReader.SetToReplayModeAsync().ConfigureAwait(continueOnCapturedContext: false);
            _replayCache = true;
        }
        else if (_manageNamespaces)
        {
            _nsManager.PopScope();
        }
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._cachingReader, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._manageNamespaces, System.Xml.XsdValidatingReader._nsManager, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._replayCache, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XmlReader.Depth, System.Xml.XsdValidatingReader.GetCachingReader(), System.Xml.XsdValidatingReader.GetOriginalAtomicValueStringOfElement(), System.Xml.Schema.XmlSchemaInfo.IsDefault, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XsdCachingReader.RecordEndElementNode(), System.Xml.XsdCachingReader.RecordTextNode(), System.Xml.XsdCachingReader.SetToReplayModeAsync(), System.Xml.Schema.XmlValueConverter.ToString(), System.Xml.Schema.XmlSchemaValidator.ValidateEndElement(), System.Xml.Schema.XmlSchemaType.ValueConverter, and System.Xml.Schema.XmlSchemaInfo.XmlType.
Referenced by System.Xml.XsdValidatingReader.ProcessElementEventAsync(), and System.Xml.XsdValidatingReader.ProcessReaderEventAsync().