Terraria: System.Xml.XsdValidatingReader.ReadAsync_Read
ReadAsync_Read()
Task< bool > System.Xml.XsdValidatingReader.ReadAsync_Read (Task< bool > task) inline private
Definition at line 2263 of file XsdValidatingReader.cs.
    {
        if (task.IsSuccess())
        {
            if (task.Result)
            {
                return ProcessReaderEventAsync().ReturnTrueTaskWhenFinishAsync();
            }
            _validator.EndValidation();
            if (_coreReader.EOF)
            {
                _validationState = ValidatingReaderState.EOF;
            }
            return AsyncHelper.DoneTaskFalse;
        }
        return _ReadAsync_Read(task);
    }
References System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._ReadAsync_Read(), System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._validator, System.Xml.AsyncHelper.DoneTaskFalse, System.Xml.Schema.XmlSchemaValidator.EndValidation(), System.Xml.XmlReader.EOF, System.Xml.XsdValidatingReader.ProcessReaderEventAsync(), and System.task.
Referenced by System.Xml.XsdValidatingReader.ReadAsync().