Terraria: System.Xml.XsdValidatingReader.ProcessReaderEventAsync
ProcessReaderEventAsync()
Task System.Xml.XsdValidatingReader.ProcessReaderEventAsync () inline private
Definition at line 2462 of file XsdValidatingReader.cs.
    {
        if (_replayCache)
        {
            return Task.CompletedTask;
        }
        switch (_coreReader.NodeType)
        {
        case XmlNodeType.Element:
            return ProcessElementEventAsync();
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            _validator.ValidateWhitespace(GetStringValue);
            break;
        case XmlNodeType.Text:
        case XmlNodeType.CDATA:
            _validator.ValidateText(GetStringValue);
            break;
        case XmlNodeType.EndElement:
            return ProcessEndElementEventAsync();
        case XmlNodeType.EntityReference:
            throw new InvalidOperationException();
        case XmlNodeType.DocumentType:
            _validator.SetDtdSchemaInfo(_coreReader.DtdInfo);
            break;
        }
        return Task.CompletedTask;
    }
References System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._replayCache, System.Xml.XsdValidatingReader._validator, System.Threading.Tasks.Task< TResult >.CompletedTask, System.Xml.XmlReader.DtdInfo, System.Xml.XsdValidatingReader.GetStringValue(), System.Xml.XmlReader.NodeType, System.Xml.XsdValidatingReader.ProcessElementEventAsync(), System.Xml.XsdValidatingReader.ProcessEndElementEventAsync(), System.Xml.Schema.XmlSchemaValidator.SetDtdSchemaInfo(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), and System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace().
Referenced by System.Xml.XsdValidatingReader._ReadAsync_Read(), System.Xml.XsdValidatingReader.ReadAsync(), System.Xml.XsdValidatingReader.ReadAsync_Read(), and System.Xml.XsdValidatingReader.ReadTillEndElementAsync().