Terraria: System.Xml.XsdValidatingReader.ProcessReaderEvent
ProcessReaderEvent()
void System.Xml.XsdValidatingReader.ProcessReaderEvent () inline private
Definition at line 1507 of file XsdValidatingReader.cs.
    {
        if (!_replayCache)
        {
            switch (_coreReader.NodeType)
            {
            case XmlNodeType.Element:
                ProcessElementEvent();
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                _validator.ValidateWhitespace(_valueGetter);
                break;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
                _validator.ValidateText(_valueGetter);
                break;
            case XmlNodeType.EndElement:
                ProcessEndElementEvent();
                break;
            case XmlNodeType.EntityReference:
                throw new InvalidOperationException();
            case XmlNodeType.DocumentType:
                _validator.SetDtdSchemaInfo(_coreReader.DtdInfo);
                break;
            case XmlNodeType.Attribute:
            case XmlNodeType.Entity:
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
            case XmlNodeType.Document:
            case XmlNodeType.DocumentFragment:
            case XmlNodeType.Notation:
                break;
            }
        }
    }
References System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._replayCache, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._valueGetter, System.Xml.XmlReader.DtdInfo, System.Xml.XmlReader.NodeType, System.Xml.XsdValidatingReader.ProcessElementEvent(), System.Xml.XsdValidatingReader.ProcessEndElementEvent(), System.Xml.Schema.XmlSchemaValidator.SetDtdSchemaInfo(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), and System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace().
Referenced by System.Xml.XsdValidatingReader.Read(), and System.Xml.XsdValidatingReader.ReadTillEndElement().