Terraria: System.Xml.XsdValidatingReader.ReadContentAsStringAsync
ReadContentAsStringAsync()
override async Task< string > System.Xml.XsdValidatingReader.ReadContentAsStringAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 2126 of file XsdValidatingReader.cs.
    {
        if (!XmlReader.CanReadContentAs(NodeType))
        {
            throw CreateReadContentAsException("ReadContentAsString");
        }
        object obj = await InternalReadContentAsObjectAsync().ConfigureAwait(continueOnCapturedContext: false);
        XmlSchemaType xmlSchemaType = ((NodeType == XmlNodeType.Attribute) ? AttributeXmlType : ElementXmlType);
        try
        {
            if (xmlSchemaType != null)
            {
                return xmlSchemaType.ValueConverter.ToString(obj);
            }
            return obj as string;
        }
        catch (InvalidCastException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "String", innerException, this);
        }
        catch (FormatException innerException2)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "String", innerException2, this);
        }
        catch (OverflowException innerException3)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, "String", innerException3, this);
        }
    }
References System.Xml.XsdValidatingReader.AttributeXmlType, System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.XsdValidatingReader.ElementXmlType, System.Xml.XsdValidatingReader.InternalReadContentAsObjectAsync(), System.Xml.XsdValidatingReader.NodeType, System.obj, System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.