Terraria: System.Xml.XsdValidatingReader.SetupValidator
SetupValidator()
void System.Xml.XsdValidatingReader.SetupValidator (XmlReaderSettings readerSettings, XmlReader reader, XmlSchemaObject partialValidationType) inline private
Definition at line 509 of file XsdValidatingReader.cs.
    {
        _validator = new XmlSchemaValidator(_coreReaderNameTable, readerSettings.Schemas, _thisNSResolver, readerSettings.ValidationFlags);
        _validator.XmlResolver = _xmlResolver;
        _validator.SourceUri = XmlConvert.ToUri(reader.BaseURI);
        _validator.ValidationEventSender = this;
        _validator.ValidationEventHandler += readerSettings.GetEventHandler();
        _validator.LineInfoProvider = _lineInfo;
        if (_validator.ProcessSchemaHints)
        {
            _validator.SchemaSet.ReaderSettings.DtdProcessing = readerSettings.DtdProcessing;
        }
        _validator.SetDtdSchemaInfo(reader.DtdInfo);
        if (partialValidationType != null)
        {
            _validator.Initialize(partialValidationType);
        }
        else
        {
            _validator.Initialize();
        }
    }
References System.Xml.XsdValidatingReader._coreReaderNameTable, System.Xml.XsdValidatingReader._lineInfo, System.Xml.XsdValidatingReader._thisNSResolver, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlResolver, System.Xml.XmlReader.BaseURI, System.Xml.Dictionary, System.Xml.XmlReader.DtdInfo, System.Xml.Schema.XmlSchemaValidator.Initialize(), System.Xml.Schema.XmlSchemaValidator.ProcessSchemaHints, System.Xml.Schema.XmlSchemaValidator.SetDtdSchemaInfo(), and System.Xml.XmlConvert.ToUri().
Referenced by System.Xml.XsdValidatingReader.XsdValidatingReader().