Terraria: System.Xml.XsdValidatingReader.GetOriginalAtomicValueStringOfElement
GetOriginalAtomicValueStringOfElement()
string System.Xml.XsdValidatingReader.GetOriginalAtomicValueStringOfElement () inline private
Definition at line 2090 of file XsdValidatingReader.cs.
    {
        if (_xmlSchemaInfo.IsDefault)
        {
            XmlSchemaElement schemaElement = _xmlSchemaInfo.SchemaElement;
            if (schemaElement != null)
            {
                if (schemaElement.DefaultValue == null)
                {
                    return schemaElement.FixedValue;
                }
                return schemaElement.DefaultValue;
            }
            return string.Empty;
        }
        return _validator.GetConcatenatedValue();
    }
References System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.Schema.XmlSchemaValidator.GetConcatenatedValue(), System.Xml.Schema.XmlSchemaInfo.IsDefault, and System.Xml.Schema.XmlSchemaInfo.SchemaElement.
Referenced by System.Xml.XsdValidatingReader.GetIsDefault(), System.Xml.XsdValidatingReader.ProcessEndElementEvent(), System.Xml.XsdValidatingReader.ProcessEndElementEventAsync(), System.Xml.XsdValidatingReader.ReadAheadForMemberType(), System.Xml.XsdValidatingReader.ReadTillEndElement(), and System.Xml.XsdValidatingReader.ReadTillEndElementAsync().