Terraria: System.Xml.XsdValidatingReader.ReadElementContentAs
ReadElementContentAs() [1/2]
override object System.Xml.XsdValidatingReader.ReadElementContentAs (Type returnType, IXmlNamespaceResolver namespaceResolver) inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 1010 of file XsdValidatingReader.cs.
    {
        if (NodeType != XmlNodeType.Element)
        {
            throw CreateReadElementContentAsException("ReadElementContentAs");
        }
        XmlSchemaType xmlType;
        string originalString;
        object value = InternalReadElementContentAsObject(out xmlType, unwrapTypedValue: false, out originalString);
        try
        {
            if (xmlType != null)
            {
                if (returnType == typeof(DateTimeOffset) && xmlType.Datatype is Datatype_dateTimeBase)
                {
                    value = originalString;
                }
                return xmlType.ValueConverter.ChangeType(value, returnType, namespaceResolver);
            }
            return XmlUntypedConverter.Untyped.ChangeType(value, returnType, namespaceResolver);
        }
        catch (FormatException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException, this);
        }
        catch (InvalidCastException innerException2)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException2, this);
        }
        catch (OverflowException innerException3)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException3, this);
        }
    }
References System.Xml.Schema.XmlValueConverter.ChangeType(), System.Xml.XmlReader.CreateReadElementContentAsException(), System.Xml.Dictionary, System.Xml.XsdValidatingReader.InternalReadElementContentAsObject(), System.Xml.XsdValidatingReader.NodeType, System.Xml.Schema.XmlUntypedConverter.Untyped, System.value, System.Xml.Schema.XmlSchemaType.ValueConverter, System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.