Terraria: System.Xml.XsdValidatingReader.ReadTillEndElement
ReadTillEndElement()
object System.Xml.XsdValidatingReader.ReadTillEndElement () inline private
Definition at line 1900 of file XsdValidatingReader.cs.
    {
        if (_atomicValue == null)
        {
            while (_coreReader.Read())
            {
                if (_replayCache)
                {
                    continue;
                }
                switch (_coreReader.NodeType)
                {
                case XmlNodeType.Element:
                    ProcessReaderEvent();
                    break;
                case XmlNodeType.Text:
                case XmlNodeType.CDATA:
                    _validator.ValidateText(_valueGetter);
                    continue;
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                    _validator.ValidateWhitespace(_valueGetter);
                    continue;
                case XmlNodeType.EndElement:
                    _atomicValue = _validator.ValidateEndElement(_xmlSchemaInfo);
                    _originalAtomicValueString = GetOriginalAtomicValueStringOfElement();
                    if (_manageNamespaces)
                    {
                        _nsManager.PopScope();
                    }
                    break;
                default:
                    continue;
                }
                break;
            }
        }
        else
        {
            if (_atomicValue == this)
            {
                _atomicValue = null;
            }
            SwitchReader();
        }
        return _atomicValue;
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._manageNamespaces, System.Xml.XsdValidatingReader._nsManager, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._replayCache, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._valueGetter, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.XsdValidatingReader.GetOriginalAtomicValueStringOfElement(), System.Xml.XmlReader.NodeType, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XsdValidatingReader.ProcessReaderEvent(), System.Xml.XmlReader.Read(), System.Xml.XsdValidatingReader.SwitchReader(), System.Xml.Schema.XmlSchemaValidator.ValidateEndElement(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), and System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace().
Referenced by System.Xml.XsdValidatingReader.InternalReadContentAsObject().