Terraria: System.Xml.XsdValidatingReader.InternalReadContentAsObjectTupleAsync
InternalReadContentAsObjectTupleAsync()
async Task<(string, object)> System.Xml.XsdValidatingReader.InternalReadContentAsObjectTupleAsync (bool unwrapTypedValue) inline private
Definition at line 2616 of file XsdValidatingReader.cs.
    {
        switch (NodeType)
        {
        case XmlNodeType.Attribute:
        {
            string originalAtomicValueString = Value;
            if (_attributePSVI != null && _attributePSVI.typedAttributeValue != null)
            {
                if (_validationState == ValidatingReaderState.OnDefaultAttribute)
                {
                    XmlSchemaAttribute schemaAttribute = _attributePSVI.attributeSchemaInfo.SchemaAttribute;
                    originalAtomicValueString = ((schemaAttribute.DefaultValue != null) ? schemaAttribute.DefaultValue : schemaAttribute.FixedValue);
                }
                return (originalAtomicValueString, ReturnBoxedValue(_attributePSVI.typedAttributeValue, AttributeSchemaInfo.XmlType, unwrapTypedValue));
            }
            return (originalAtomicValueString, Value);
        }
        case XmlNodeType.EndElement:
        {
            string originalAtomicValueString;
            if (_atomicValue != null)
            {
                originalAtomicValueString = _originalAtomicValueString;
                return (originalAtomicValueString, _atomicValue);
            }
            originalAtomicValueString = string.Empty;
            return (originalAtomicValueString, string.Empty);
        }
        default:
        {
            string originalAtomicValueString;
            if (_validator.CurrentContentType == XmlSchemaContentType.TextOnly)
            {
                object item = ReturnBoxedValue(await ReadTillEndElementAsync().ConfigureAwait(continueOnCapturedContext: false), _xmlSchemaInfo.XmlType, unwrapTypedValue);
                originalAtomicValueString = _originalAtomicValueString;
                return (originalAtomicValueString, item);
            }
            originalAtomicValueString = ((!(_coreReader is XsdCachingReader xsdCachingReader)) ? (await InternalReadContentAsStringAsync().ConfigureAwait(continueOnCapturedContext: false)) : xsdCachingReader.ReadOriginalContentAsString());
            return (originalAtomicValueString, originalAtomicValueString);
        }
        }
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._attributePSVI, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.AttributePSVIInfo.attributeSchemaInfo, System.Xml.XsdValidatingReader.AttributeSchemaInfo, System.Xml.Schema.XmlSchemaValidator.CurrentContentType, System.Xml.Dictionary, System.Xml.XmlReader.InternalReadContentAsStringAsync(), System.item, System.Xml.XsdValidatingReader.NodeType, System.Xml.XsdValidatingReader.ReadTillEndElementAsync(), System.Xml.XsdValidatingReader.ReturnBoxedValue(), System.Xml.Schema.XmlSchemaInfo.SchemaAttribute, System.Xml.AttributePSVIInfo.typedAttributeValue, System.Xml.XsdValidatingReader.Value, and System.Xml.Schema.XmlSchemaInfo.XmlType.
Referenced by System.Xml.XsdValidatingReader.InternalReadContentAsObjectAsync(), System.Xml.XsdValidatingReader.InternalReadElementContentAsObjectTupleAsync(), and System.Xml.XsdValidatingReader.ReadContentAsAsync().