Terraria: System.Xml.XsdValidatingReader.Skip
Skip()
override void System.Xml.XsdValidatingReader.Skip () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 1338 of file XsdValidatingReader.cs.
    {
        XmlNodeType nodeType = NodeType;
        if (nodeType != XmlNodeType.Element)
        {
            if (nodeType != XmlNodeType.Attribute)
            {
                goto IL_007a;
            }
            MoveToElement();
        }
        if (!_coreReader.IsEmptyElement)
        {
            bool flag = true;
            if ((_xmlSchemaInfo.IsUnionType || _xmlSchemaInfo.IsDefault) && _coreReader is XsdCachingReader)
            {
                flag = false;
            }
            _coreReader.Skip();
            _validationState = ValidatingReaderState.ReadAhead;
            if (flag)
            {
                _validator.SkipToEndElement(_xmlSchemaInfo);
            }
        }
        goto IL_007a;
        IL_007a:
        Read();
    }
References System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaInfo.IsDefault, System.Xml.XmlReader.IsEmptyElement, System.Xml.Schema.XmlSchemaInfo.IsUnionType, System.Xml.XsdValidatingReader.MoveToElement(), System.Xml.XsdValidatingReader.NodeType, System.Xml.XsdValidatingReader.Read(), System.Xml.XmlReader.Skip(), and System.Xml.Schema.XmlSchemaValidator.SkipToEndElement().