Terraria: System.Xml.XsdValidatingReader.ReadTillEndElementAsync
ReadTillEndElementAsync()
async Task< object > System.Xml.XsdValidatingReader.ReadTillEndElementAsync () inline private
Definition at line 2715 of file XsdValidatingReader.cs.
    {
        if (_atomicValue == null)
        {
            while (await _coreReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false))
            {
                if (_replayCache)
                {
                    continue;
                }
                switch (_coreReader.NodeType)
                {
                case XmlNodeType.Element:
                    await ProcessReaderEventAsync().ConfigureAwait(continueOnCapturedContext: false);
                    break;
                case XmlNodeType.Text:
                case XmlNodeType.CDATA:
                    _validator.ValidateText(GetStringValue);
                    continue;
                case XmlNodeType.Whitespace:
                case XmlNodeType.SignificantWhitespace:
                    _validator.ValidateWhitespace(GetStringValue);
                    continue;
                case XmlNodeType.EndElement:
                    _atomicValue = _validator.ValidateEndElement(_xmlSchemaInfo);
                    _originalAtomicValueString = GetOriginalAtomicValueStringOfElement();
                    if (_manageNamespaces)
                    {
                        _nsManager.PopScope();
                    }
                    break;
                default:
                    continue;
                }
                break;
            }
        }
        else
        {
            if (_atomicValue == this)
            {
                _atomicValue = null;
            }
            SwitchReader();
        }
        return _atomicValue;
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._manageNamespaces, System.Xml.XsdValidatingReader._nsManager, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._replayCache, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.XsdValidatingReader.GetOriginalAtomicValueStringOfElement(), System.Xml.XsdValidatingReader.GetStringValue(), System.Xml.XmlReader.NodeType, System.Xml.XmlNamespaceManager.PopScope(), System.Xml.XsdValidatingReader.ProcessReaderEventAsync(), System.Xml.XmlReader.ReadAsync(), System.Xml.XsdValidatingReader.SwitchReader(), System.Xml.Schema.XmlSchemaValidator.ValidateEndElement(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), and System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace().
Referenced by System.Xml.XsdValidatingReader.InternalReadContentAsObjectTupleAsync().