Terraria: System.Xml.XsdValidatingReader.SkipAsync
SkipAsync()
override async Task System.Xml.XsdValidatingReader.SkipAsync () inline virtual
Reimplemented from System.Xml.XmlReader.
Definition at line 2360 of file XsdValidatingReader.cs.
    {
        XmlNodeType nodeType = NodeType;
        if (nodeType != XmlNodeType.Element)
        {
            if (nodeType != XmlNodeType.Attribute)
            {
                goto IL_010f;
            }
            MoveToElement();
        }
        if (!_coreReader.IsEmptyElement)
        {
            bool callSkipToEndElem = true;
            if ((_xmlSchemaInfo.IsUnionType || _xmlSchemaInfo.IsDefault) && _coreReader is XsdCachingReader)
            {
                callSkipToEndElem = false;
            }
            await _coreReader.SkipAsync().ConfigureAwait(continueOnCapturedContext: false);
            _validationState = ValidatingReaderState.ReadAhead;
            if (callSkipToEndElem)
            {
                _validator.SkipToEndElement(_xmlSchemaInfo);
            }
        }
        goto IL_010f;
        IL_010f:
        await ReadAsync().ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaInfo.IsDefault, System.Xml.XmlReader.IsEmptyElement, System.Xml.Schema.XmlSchemaInfo.IsUnionType, System.Xml.XsdValidatingReader.MoveToElement(), System.Xml.XsdValidatingReader.NodeType, System.Xml.XsdValidatingReader.ReadAsync(), System.Xml.XmlReader.SkipAsync(), and System.Xml.Schema.XmlSchemaValidator.SkipToEndElement().