Terraria: System.Xml.XsdValidatingReader.MoveToAttribute
MoveToAttribute() [2/4]
override bool System.Xml.XsdValidatingReader.MoveToAttribute (string name) inline
Definition at line 1094 of file XsdValidatingReader.cs.
    {
        if (_coreReader.MoveToAttribute(name))
        {
            _validationState = ValidatingReaderState.OnAttribute;
            _attributePSVI = GetAttributePSVI(name);
            goto IL_0057;
        }
        if (_attributeCount > 0)
        {
            ValidatingReaderNodeData defaultAttribute = GetDefaultAttribute(name, updatePosition: true);
            if (defaultAttribute != null)
            {
                _validationState = ValidatingReaderState.OnDefaultAttribute;
                _attributePSVI = defaultAttribute.AttInfo;
                _cachedNode = defaultAttribute;
                goto IL_0057;
            }
        }
        return false;
        IL_0057:
        if (_validationState == ValidatingReaderState.OnReadBinaryContent)
        {
            _readBinaryHelper.Finish();
            _validationState = _savedState;
        }
        return true;
    }
References System.Xml.XsdValidatingReader._attributeCount, System.Xml.XsdValidatingReader._attributePSVI, System.Xml.XsdValidatingReader._cachedNode, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._readBinaryHelper, System.Xml.XsdValidatingReader._savedState, System.Xml.XsdValidatingReader._validationState, System.Xml.Dictionary, System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XsdValidatingReader.GetAttributePSVI(), System.Xml.XsdValidatingReader.GetDefaultAttribute(), and System.Xml.XmlReader.MoveToAttribute().