Terraria: System.Xml.XsdValidatingReader.GetCachingReader
GetCachingReader()
XsdCachingReader System.Xml.XsdValidatingReader.GetCachingReader () inline private
Definition at line 2058 of file XsdValidatingReader.cs.
    {
        if (_cachingReader == null)
        {
            _cachingReader = new XsdCachingReader(_coreReader, _lineInfo, CachingCallBack);
        }
        else
        {
            _cachingReader.Reset(_coreReader);
        }
        _lineInfo = _cachingReader;
        return _cachingReader;
    }
References System.Xml.XsdValidatingReader._cachingReader, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._lineInfo, System.Xml.XsdValidatingReader.CachingCallBack(), and System.Xml.XsdCachingReader.Reset().
Referenced by System.Xml.XsdValidatingReader.GetIsDefault(), System.Xml.XsdValidatingReader.GetMemberType(), System.Xml.XsdValidatingReader.ProcessEndElementEvent(), and System.Xml.XsdValidatingReader.ProcessEndElementEventAsync().