Terraria: System.Xml.XsdValidatingReader.InternalReadContentAsObject
InternalReadContentAsObject() [3/3]
object System.Xml.XsdValidatingReader.InternalReadContentAsObject (bool unwrapTypedValue, out string originalStringValue) inline private
Definition at line 1803 of file XsdValidatingReader.cs.
    {
        switch (NodeType)
        {
        case XmlNodeType.Attribute:
            originalStringValue = Value;
            if (_attributePSVI != null && _attributePSVI.typedAttributeValue != null)
            {
                if (_validationState == ValidatingReaderState.OnDefaultAttribute)
                {
                    XmlSchemaAttribute schemaAttribute = _attributePSVI.attributeSchemaInfo.SchemaAttribute;
                    originalStringValue = ((schemaAttribute.DefaultValue != null) ? schemaAttribute.DefaultValue : schemaAttribute.FixedValue);
                }
                return ReturnBoxedValue(_attributePSVI.typedAttributeValue, AttributeSchemaInfo.XmlType, unwrapTypedValue);
            }
            return Value;
        case XmlNodeType.EndElement:
            if (_atomicValue != null)
            {
                originalStringValue = _originalAtomicValueString;
                return _atomicValue;
            }
            originalStringValue = string.Empty;
            return string.Empty;
        default:
            if (_validator.CurrentContentType == XmlSchemaContentType.TextOnly)
            {
                object result = ReturnBoxedValue(ReadTillEndElement(), _xmlSchemaInfo.XmlType, unwrapTypedValue);
                originalStringValue = _originalAtomicValueString;
                return result;
            }
            if (_coreReader is XsdCachingReader xsdCachingReader)
            {
                originalStringValue = xsdCachingReader.ReadOriginalContentAsString();
            }
            else
            {
                originalStringValue = InternalReadContentAsString();
            }
            return originalStringValue;
        }
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._attributePSVI, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.AttributePSVIInfo.attributeSchemaInfo, System.Xml.XsdValidatingReader.AttributeSchemaInfo, System.Xml.Schema.XmlSchemaValidator.CurrentContentType, System.Xml.Dictionary, System.Xml.XmlReader.InternalReadContentAsString(), System.Xml.XsdValidatingReader.NodeType, System.Xml.XsdValidatingReader.ReadTillEndElement(), System.Xml.XsdValidatingReader.ReturnBoxedValue(), System.Xml.Schema.XmlSchemaInfo.SchemaAttribute, System.Xml.AttributePSVIInfo.typedAttributeValue, System.Xml.XsdValidatingReader.Value, and System.Xml.Schema.XmlSchemaInfo.XmlType.