Terraria: System.Xml.XsdValidatingReader.GetAttributePSVI
GetAttributePSVI() [2/2]
AttributePSVIInfo System.Xml.XsdValidatingReader.GetAttributePSVI (string name) inline private
Definition at line 1682 of file XsdValidatingReader.cs.
    {
        if (_inlineSchemaParser != null)
        {
            return null;
        }
        ValidateNames.SplitQName(name, out var prefix, out var lname);
        prefix = _coreReaderNameTable.Add(prefix);
        lname = _coreReaderNameTable.Add(lname);
        string ns = ((prefix.Length != 0) ? _thisNSResolver.LookupNamespace(prefix) : string.Empty);
        return GetAttributePSVI(lname, ns);
    }
References System.Xml.XsdValidatingReader._coreReaderNameTable, System.Xml.XsdValidatingReader._inlineSchemaParser, System.Xml.XsdValidatingReader._thisNSResolver, System.Xml.XmlNameTable.Add(), System.Xml.Dictionary, System.Xml.XsdValidatingReader.GetAttributePSVI(), System.Xml.IXmlNamespaceResolver.LookupNamespace(), System.prefix, and System.Xml.ValidateNames.SplitQName().
Referenced by System.Xml.XsdValidatingReader.GetAttributePSVI(), System.Xml.XsdValidatingReader.MoveToAttribute(), and System.Xml.XsdValidatingReader.MoveToAttribute().