Terraria: System.Xml.XsdValidatingReader.Read
Read()
override bool System.Xml.XsdValidatingReader.Read () inline
Definition at line 1276 of file XsdValidatingReader.cs.
    {
        switch (_validationState)
        {
        case ValidatingReaderState.Read:
            if (_coreReader.Read())
            {
                ProcessReaderEvent();
                return true;
            }
            _validator.EndValidation();
            if (_coreReader.EOF)
            {
                _validationState = ValidatingReaderState.EOF;
            }
            return false;
        case ValidatingReaderState.ParseInlineSchema:
            ProcessInlineSchema();
            return true;
        case ValidatingReaderState.OnReadAttributeValue:
        case ValidatingReaderState.OnDefaultAttribute:
        case ValidatingReaderState.OnAttribute:
        case ValidatingReaderState.ClearAttributes:
            ClearAttributesInfo();
            if (_inlineSchemaParser != null)
            {
                _validationState = ValidatingReaderState.ParseInlineSchema;
                goto case ValidatingReaderState.ParseInlineSchema;
            }
            _validationState = ValidatingReaderState.Read;
            goto case ValidatingReaderState.Read;
        case ValidatingReaderState.ReadAhead:
            ClearAttributesInfo();
            ProcessReaderEvent();
            _validationState = ValidatingReaderState.Read;
            return true;
        case ValidatingReaderState.OnReadBinaryContent:
            _validationState = _savedState;
            _readBinaryHelper.Finish();
            return Read();
        case ValidatingReaderState.Init:
            _validationState = ValidatingReaderState.Read;
            if (_coreReader.ReadState == ReadState.Interactive)
            {
                ProcessReaderEvent();
                return true;
            }
            goto case ValidatingReaderState.Read;
        case ValidatingReaderState.ReaderClosed:
        case ValidatingReaderState.EOF:
            return false;
        default:
            return false;
        }
    }
References System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._inlineSchemaParser, System.Xml.XsdValidatingReader._readBinaryHelper, System.Xml.XsdValidatingReader._savedState, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader.ClearAttributesInfo(), System.Xml.Schema.XmlSchemaValidator.EndValidation(), System.Xml.XmlReader.EOF, System.Xml.ReadContentAsBinaryHelper.Finish(), System.Xml.XsdValidatingReader.ProcessInlineSchema(), System.Xml.XsdValidatingReader.ProcessReaderEvent(), System.Xml.XmlReader.Read(), System.Xml.XsdValidatingReader.Read(), and System.Xml.XmlReader.ReadState.
Referenced by System.Xml.XsdValidatingReader.InternalReadElementContentAsObject(), System.Xml.XsdValidatingReader.Read(), and System.Xml.XsdValidatingReader.Skip().