Terraria: System.Xml.XsdValidatingReader.ProcessElementEventAsync
ProcessElementEventAsync()
async Task System.Xml.XsdValidatingReader.ProcessElementEventAsync () inline private
Definition at line 2491 of file XsdValidatingReader.cs.
    {
        if (_processInlineSchema && IsXSDRoot(_coreReader.LocalName, _coreReader.NamespaceURI) && _coreReader.Depth > 0)
        {
            _xmlSchemaInfo.Clear();
            _attributeCount = (_coreReaderAttributeCount = _coreReader.AttributeCount);
            if (!_coreReader.IsEmptyElement)
            {
                _inlineSchemaParser = new Parser(SchemaType.XSD, _coreReaderNameTable, _validator.SchemaSet.GetSchemaNames(_coreReaderNameTable), _validationEvent);
                await _inlineSchemaParser.StartParsingAsync(_coreReader, null).ConfigureAwait(continueOnCapturedContext: false);
                _inlineSchemaParser.ParseReaderNode();
                _validationState = ValidatingReaderState.ParseInlineSchema;
            }
            else
            {
                _validationState = ValidatingReaderState.ClearAttributes;
            }
            return;
        }
        _atomicValue = null;
        _originalAtomicValueString = null;
        _xmlSchemaInfo.Clear();
        if (_manageNamespaces)
        {
            _nsManager.PushScope();
        }
        string xsiSchemaLocation = null;
        string xsiNoNamespaceSchemaLocation = null;
        string xsiNil = null;
        string xsiType = null;
        if (_coreReader.MoveToFirstAttribute())
        {
            do
            {
                string namespaceURI = _coreReader.NamespaceURI;
                string localName = _coreReader.LocalName;
                if (Ref.Equal(namespaceURI, _nsXsi))
                {
                    if (Ref.Equal(localName, _xsiSchemaLocation))
                    {
                        xsiSchemaLocation = _coreReader.Value;
                    }
                    else if (Ref.Equal(localName, _xsiNoNamespaceSchemaLocation))
                    {
                        xsiNoNamespaceSchemaLocation = _coreReader.Value;
                    }
                    else if (Ref.Equal(localName, _xsiType))
                    {
                        xsiType = _coreReader.Value;
                    }
                    else if (Ref.Equal(localName, _xsiNil))
                    {
                        xsiNil = _coreReader.Value;
                    }
                }
                if (_manageNamespaces && Ref.Equal(_coreReader.NamespaceURI, _nsXmlNs))
                {
                    _nsManager.AddNamespace((_coreReader.Prefix.Length == 0) ? string.Empty : _coreReader.LocalName, _coreReader.Value);
                }
            }
            while (_coreReader.MoveToNextAttribute());
            _coreReader.MoveToElement();
        }
        _validator.ValidateElement(_coreReader.LocalName, _coreReader.NamespaceURI, _xmlSchemaInfo, xsiType, xsiNil, xsiSchemaLocation, xsiNoNamespaceSchemaLocation);
        ValidateAttributes();
        _validator.ValidateEndOfAttributes(_xmlSchemaInfo);
        if (_coreReader.IsEmptyElement)
        {
            await ProcessEndElementEventAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        _validationState = ValidatingReaderState.ClearAttributes;
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._attributeCount, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._coreReaderAttributeCount, System.Xml.XsdValidatingReader._coreReaderNameTable, System.Xml.XsdValidatingReader._inlineSchemaParser, System.Xml.XsdValidatingReader._manageNamespaces, System.Xml.XsdValidatingReader._nsManager, System.Xml.XsdValidatingReader._nsXmlNs, System.Xml.XsdValidatingReader._nsXsi, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._processInlineSchema, System.Xml.XsdValidatingReader._validationEvent, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.XsdValidatingReader._xsiNil, System.Xml.XsdValidatingReader._xsiNoNamespaceSchemaLocation, System.Xml.XsdValidatingReader._xsiSchemaLocation, System.Xml.XsdValidatingReader._xsiType, System.Xml.XmlNamespaceManager.AddNamespace(), System.Xml.XmlReader.AttributeCount, System.Xml.Schema.XmlSchemaInfo.Clear(), System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.Schema.XmlSchemaSet.GetSchemaNames(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XsdValidatingReader.IsXSDRoot(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.NamespaceURI, System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.XmlReader.Prefix, System.Xml.XsdValidatingReader.ProcessEndElementEventAsync(), System.Xml.XmlNamespaceManager.PushScope(), System.Xml.Schema.XmlSchemaValidator.SchemaSet, System.Xml.Schema.Parser.StartParsingAsync(), System.Xml.XsdValidatingReader.ValidateAttributes(), System.Xml.Schema.XmlSchemaValidator.ValidateElement(), System.Xml.Schema.XmlSchemaValidator.ValidateEndOfAttributes(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.XsdValidatingReader.ProcessReaderEventAsync().