Terraria: System.Xml.XsdValidatingReader.ReturnBoxedValue
ReturnBoxedValue()
object System.Xml.XsdValidatingReader.ReturnBoxedValue (object typedValue, XmlSchemaType xmlType, bool unWrap) inline private
Definition at line 2040 of file XsdValidatingReader.cs.
    {
        if (typedValue != null)
        {
            if (unWrap && xmlType.Datatype.Variety == XmlSchemaDatatypeVariety.List)
            {
                Datatype_List datatype_List = xmlType.Datatype as Datatype_List;
                if (datatype_List.ItemType.Variety == XmlSchemaDatatypeVariety.Union)
                {
                    typedValue = xmlType.ValueConverter.ChangeType(typedValue, xmlType.Datatype.ValueType, _thisNSResolver);
                }
            }
            return typedValue;
        }
        typedValue = _validator.GetConcatenatedValue();
        return typedValue;
    }
References System.Xml.XsdValidatingReader._thisNSResolver, System.Xml.XsdValidatingReader._validator, System.Xml.Schema.XmlValueConverter.ChangeType(), System.Xml.Schema.XmlSchemaType.Datatype, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.GetConcatenatedValue(), System.Xml.Schema.XmlSchemaType.ValueConverter, System.Xml.Schema.XmlSchemaDatatype.ValueType, and System.Xml.Schema.XmlSchemaDatatype.Variety.
Referenced by System.Xml.XsdValidatingReader.InternalReadContentAsObject(), System.Xml.XsdValidatingReader.InternalReadContentAsObjectTupleAsync(), System.Xml.XsdValidatingReader.InternalReadElementContentAsObject(), and System.Xml.XsdValidatingReader.InternalReadElementContentAsObjectTupleAsync().