Terraria: System.Xml.XsdValidatingReader.ProcessInlineSchemaAsync
ProcessInlineSchemaAsync()
async Task System.Xml.XsdValidatingReader.ProcessInlineSchemaAsync () inline private
Definition at line 2583 of file XsdValidatingReader.cs.
    {
        if (await _coreReader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false))
        {
            if (_coreReader.NodeType == XmlNodeType.Element)
            {
                _attributeCount = (_coreReaderAttributeCount = _coreReader.AttributeCount);
            }
            else
            {
                ClearAttributesInfo();
            }
            if (!_inlineSchemaParser.ParseReaderNode())
            {
                _inlineSchemaParser.FinishParsing();
                XmlSchema xmlSchema = _inlineSchemaParser.XmlSchema;
                _validator.AddSchema(xmlSchema);
                _inlineSchemaParser = null;
                _validationState = ValidatingReaderState.Read;
            }
        }
    }
References System.Xml.XsdValidatingReader._attributeCount, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._coreReaderAttributeCount, System.Xml.XsdValidatingReader._inlineSchemaParser, System.Xml.XsdValidatingReader._validationState, System.Xml.XsdValidatingReader._validator, System.Xml.Schema.XmlSchemaValidator.AddSchema(), System.Xml.XmlReader.AttributeCount, System.Xml.XsdValidatingReader.ClearAttributesInfo(), System.Xml.Schema.Parser.FinishParsing(), System.Xml.XmlReader.NodeType, System.Xml.Schema.Parser.ParseReaderNode(), System.Xml.XmlReader.ReadAsync(), and System.Xml.Schema.Parser.XmlSchema.
Referenced by System.Xml.XsdValidatingReader.ReadAsync().