Terraria: System.Xml.XsdValidatingReader.InternalReadElementContentAsObject
InternalReadElementContentAsObject() [1/3]
object System.Xml.XsdValidatingReader.InternalReadElementContentAsObject (out XmlSchemaType xmlType) inline private
Definition at line 1846 of file XsdValidatingReader.cs.
    {
        return InternalReadElementContentAsObject(out xmlType, unwrapTypedValue: false);
    }
References System.Xml.XsdValidatingReader.InternalReadElementContentAsObject().
Referenced by System.Xml.XsdValidatingReader.InternalReadElementContentAsObject(), System.Xml.XsdValidatingReader.InternalReadElementContentAsObject(), System.Xml.XsdValidatingReader.ReadElementContentAs(), System.Xml.XsdValidatingReader.ReadElementContentAsBoolean(), System.Xml.XsdValidatingReader.ReadElementContentAsDateTime(), System.Xml.XsdValidatingReader.ReadElementContentAsDecimal(), System.Xml.XsdValidatingReader.ReadElementContentAsDouble(), System.Xml.XsdValidatingReader.ReadElementContentAsFloat(), System.Xml.XsdValidatingReader.ReadElementContentAsInt(), System.Xml.XsdValidatingReader.ReadElementContentAsLong(), System.Xml.XsdValidatingReader.ReadElementContentAsObject(), and System.Xml.XsdValidatingReader.ReadElementContentAsString().