Terraria: System.Xml.XsdValidatingReader.ReadAheadForMemberType
ReadAheadForMemberType()
void System.Xml.XsdValidatingReader.ReadAheadForMemberType () inline private
Definition at line 1957 of file XsdValidatingReader.cs.
    {
        while (_coreReader.Read())
        {
            switch (_coreReader.NodeType)
            {
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
                _validator.ValidateText(_valueGetter);
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                _validator.ValidateWhitespace(_valueGetter);
                break;
            case XmlNodeType.EndElement:
                _atomicValue = _validator.ValidateEndElement(_xmlSchemaInfo);
                _originalAtomicValueString = GetOriginalAtomicValueStringOfElement();
                if (_atomicValue == null)
                {
                    _atomicValue = this;
                }
                else if (_xmlSchemaInfo.IsDefault)
                {
                    _cachingReader.SwitchTextNodeAndEndElement(_xmlSchemaInfo.XmlType.ValueConverter.ToString(_atomicValue), _originalAtomicValueString);
                }
                return;
            }
        }
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._cachingReader, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._valueGetter, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.XsdValidatingReader.GetOriginalAtomicValueStringOfElement(), System.Xml.Schema.XmlSchemaInfo.IsDefault, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XsdCachingReader.SwitchTextNodeAndEndElement(), System.Xml.Schema.XmlValueConverter.ToString(), System.Xml.Schema.XmlSchemaValidator.ValidateEndElement(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace(), System.Xml.Schema.XmlSchemaType.ValueConverter, and System.Xml.Schema.XmlSchemaInfo.XmlType.
Referenced by System.Xml.XsdValidatingReader.GetIsDefault(), and System.Xml.XsdValidatingReader.GetMemberType().