Terraria: System.Xml.XsdValidatingReader.ValidateAttributes
ValidateAttributes()
void System.Xml.XsdValidatingReader.ValidateAttributes () inline private
Definition at line 1636 of file XsdValidatingReader.cs.
    {
        _attributeCount = (_coreReaderAttributeCount = _coreReader.AttributeCount);
        int num = 0;
        bool flag = false;
        if (_coreReader.MoveToFirstAttribute())
        {
            do
            {
                string localName = _coreReader.LocalName;
                string namespaceURI = _coreReader.NamespaceURI;
                AttributePSVIInfo attributePSVIInfo = AddAttributePSVI(num);
                attributePSVIInfo.localName = localName;
                attributePSVIInfo.namespaceUri = namespaceURI;
                if ((object)namespaceURI == _nsXmlNs)
                {
                    num++;
                    continue;
                }
                attributePSVIInfo.typedAttributeValue = _validator.ValidateAttribute(localName, namespaceURI, _valueGetter, attributePSVIInfo.attributeSchemaInfo);
                if (!flag)
                {
                    flag = attributePSVIInfo.attributeSchemaInfo.Validity == XmlSchemaValidity.Invalid;
                }
                num++;
            }
            while (_coreReader.MoveToNextAttribute());
        }
        _coreReader.MoveToElement();
        if (flag)
        {
            _xmlSchemaInfo.Validity = XmlSchemaValidity.Invalid;
        }
        _validator.GetUnspecifiedDefaultAttributes(_defaultAttributes, createNodeData: true);
        _attributeCount += _defaultAttributes.Count;
    }
References System.Xml.XsdValidatingReader._attributeCount, System.Xml.XsdValidatingReader._coreReader, System.Xml.XsdValidatingReader._coreReaderAttributeCount, System.Xml.XsdValidatingReader._defaultAttributes, System.Xml.XsdValidatingReader._nsXmlNs, System.Xml.XsdValidatingReader._validator, System.Xml.XsdValidatingReader._valueGetter, System.Xml.XsdValidatingReader.AddAttributePSVI(), System.Xml.XmlReader.AttributeCount, System.Collections.ArrayList.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.NamespaceURI, and System.Xml.Schema.XmlSchemaValidator.ValidateAttribute().
Referenced by System.Xml.XsdValidatingReader.ProcessElementEvent(), and System.Xml.XsdValidatingReader.ProcessElementEventAsync().