Terraria: System.Xml.XsdValidatingReader.ReadContentAsAsync
ReadContentAsAsync() [1/2]
override async Task< object > System.Xml.XsdValidatingReader.ReadContentAsAsync (Type returnType, IXmlNamespaceResolver namespaceResolver) inline
Definition at line 2156 of file XsdValidatingReader.cs.
    {
        if (!XmlReader.CanReadContentAs(NodeType))
        {
            throw CreateReadContentAsException("ReadContentAs");
        }
        (string, object) tuple = await InternalReadContentAsObjectTupleAsync(unwrapTypedValue: false).ConfigureAwait(continueOnCapturedContext: false);
        string item = tuple.Item1;
        object value = tuple.Item2;
        XmlSchemaType xmlSchemaType = ((NodeType == XmlNodeType.Attribute) ? AttributeXmlType : ElementXmlType);
        try
        {
            if (xmlSchemaType != null)
            {
                if (returnType == typeof(DateTimeOffset) && xmlSchemaType.Datatype is Datatype_dateTimeBase)
                {
                    value = item;
                }
                return xmlSchemaType.ValueConverter.ChangeType(value, returnType);
            }
            return XmlUntypedConverter.Untyped.ChangeType(value, returnType, namespaceResolver);
        }
        catch (FormatException innerException)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException, this);
        }
        catch (InvalidCastException innerException2)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException2, this);
        }
        catch (OverflowException innerException3)
        {
            throw new XmlException(System.SR.Xml_ReadContentAsFormatException, returnType.ToString(), innerException3, this);
        }
    }
References System.Xml.XsdValidatingReader.AttributeXmlType, System.Xml.XmlReader.CanReadContentAs(), System.Xml.XmlReader.CreateReadContentAsException(), System.Xml.Dictionary, System.Xml.XsdValidatingReader.ElementXmlType, System.Xml.XsdValidatingReader.InternalReadContentAsObjectTupleAsync(), System.item, System.Xml.XsdValidatingReader.NodeType, System.Xml.Schema.XmlUntypedConverter.Untyped, System.value, System.SR.Xml_ReadContentAsFormatException, and System.Xml.XmlException.