Terraria: System.Xml.XsdValidatingReader.InternalReadElementContentAsObject
InternalReadElementContentAsObject() [3/3]
object System.Xml.XsdValidatingReader.InternalReadElementContentAsObject (out XmlSchemaType xmlType, bool unwrapTypedValue, out string originalString) inline private
Definition at line 1857 of file XsdValidatingReader.cs.
    {
        object obj = null;
        xmlType = null;
        if (IsEmptyElement)
        {
            obj = ((_xmlSchemaInfo.ContentType != 0) ? _atomicValue : ReturnBoxedValue(_atomicValue, _xmlSchemaInfo.XmlType, unwrapTypedValue));
            originalString = _originalAtomicValueString;
            xmlType = ElementXmlType;
            Read();
            return obj;
        }
        Read();
        if (NodeType == XmlNodeType.EndElement)
        {
            if (_xmlSchemaInfo.IsDefault)
            {
                obj = ((_xmlSchemaInfo.ContentType != 0) ? _atomicValue : ReturnBoxedValue(_atomicValue, _xmlSchemaInfo.XmlType, unwrapTypedValue));
                originalString = _originalAtomicValueString;
            }
            else
            {
                obj = string.Empty;
                originalString = string.Empty;
            }
        }
        else
        {
            if (NodeType == XmlNodeType.Element)
            {
                throw new XmlException(System.SR.Xml_MixedReadElementContentAs, string.Empty, this);
            }
            obj = InternalReadContentAsObject(unwrapTypedValue, out originalString);
            if (NodeType != XmlNodeType.EndElement)
            {
                throw new XmlException(System.SR.Xml_MixedReadElementContentAs, string.Empty, this);
            }
        }
        xmlType = ElementXmlType;
        Read();
        return obj;
    }
References System.Xml.XsdValidatingReader._atomicValue, System.Xml.XsdValidatingReader._originalAtomicValueString, System.Xml.XsdValidatingReader._xmlSchemaInfo, System.Xml.Dictionary, System.Xml.XsdValidatingReader.ElementXmlType, System.Xml.XsdValidatingReader.InternalReadContentAsObject(), System.Xml.Schema.XmlSchemaInfo.IsDefault, System.Xml.XsdValidatingReader.IsEmptyElement, System.Xml.XsdValidatingReader.NodeType, System.obj, System.Xml.XsdValidatingReader.Read(), System.Xml.XsdValidatingReader.ReturnBoxedValue(), System.SR.Xml_MixedReadElementContentAs, System.Xml.XmlException, and System.Xml.Schema.XmlSchemaInfo.XmlType.