Terraria: System.Numerics.Vector.ToString
ToString() [3/3]
readonly string System.Numerics.Vector< T >.ToString (string? format, IFormatProvider? formatProvider) inline
Implements System.IFormattable.
Definition at line 1059 of file Vector.cs.
    {
        ThrowHelper.ThrowForUnsupportedNumericsVectorBaseType<T>();
        StringBuilder stringBuilder = new StringBuilder();
        string numberGroupSeparator = NumberFormatInfo.GetInstance(formatProvider).NumberGroupSeparator;
        stringBuilder.Append('<');
        for (int i = 0; i < Count - 1; i++)
        {
            stringBuilder.Append(((IFormattable)(object)GetElement(i)).ToString(format, formatProvider));
            stringBuilder.Append(numberGroupSeparator);
            stringBuilder.Append(' ');
        }
        stringBuilder.Append(((IFormattable)(object)GetElement(Count - 1)).ToString(format, formatProvider));
        stringBuilder.Append('>');
        return stringBuilder.ToString();
    }
References System.Numerics.Vector< T >.Count, System.format, System.Numerics.Vector< T >.GetElement(), System.Globalization.NumberFormatInfo.GetInstance(), and System.Numerics.Vector< T >.ToString().