Terraria: System.Numerics.Vector.GreaterThan
GreaterThan() [2/5]
static Vector< int > System.Numerics.Vector< T >.GreaterThan (Vector< float > left, Vector< float > right) inline static
Definition at line 193 of file Vector.cs.
    {
        return (Vector<int>)Vector<float>.GreaterThan(left, right);
    }
References System.Numerics.Vector< T >.GreaterThan().
Referenced by System.Numerics.Vector< T >.GreaterThan(), System.Numerics.Vector< T >.GreaterThan(), System.Numerics.Vector< T >.GreaterThan(), System.Numerics.Vector< T >.GreaterThan(), System.Numerics.Vector< T >.GreaterThan< T >(), System.Numerics.Vector< T >.GreaterThanAll< T >(), and System.Numerics.Vector< T >.GreaterThanAny< T >().