Terraria: System.Numerics.Vector.ScalarMultiply
ScalarMultiply()
static T System.Numerics.Vector< T >.ScalarMultiply (T left, T right) inline static private
Definition at line 1874 of file Vector.cs.
    {
        if (typeof(T) == typeof(byte))
        {
            return (T)(object)(byte)((byte)(object)left * (byte)(object)right);
        }
        if (typeof(T) == typeof(sbyte))
        {
            return (T)(object)(sbyte)((sbyte)(object)left * (sbyte)(object)right);
        }
        if (typeof(T) == typeof(ushort))
        {
            return (T)(object)(ushort)((ushort)(object)left * (ushort)(object)right);
        }
        if (typeof(T) == typeof(short))
        {
            return (T)(object)(short)((short)(object)left * (short)(object)right);
        }
        if (typeof(T) == typeof(uint))
        {
            return (T)(object)((uint)(object)left * (uint)(object)right);
        }
        if (typeof(T) == typeof(int))
        {
            return (T)(object)((int)(object)left * (int)(object)right);
        }
        if (typeof(T) == typeof(ulong))
        {
            return (T)(object)((ulong)(object)left * (ulong)(object)right);
        }
        if (typeof(T) == typeof(long))
        {
            return (T)(object)((long)(object)left * (long)(object)right);
        }
        if (typeof(T) == typeof(float))
        {
            return (T)(object)((float)(object)left * (float)(object)right);
        }
        if (typeof(T) == typeof(double))
        {
            return (T)(object)((double)(object)left * (double)(object)right);
        }
        if (typeof(T) == typeof(UIntPtr))
        {
            return (T)(object)(nuint)((nint)(nuint)(UIntPtr)(object)left * (nint)(nuint)(UIntPtr)(object)right);
        }
        if (typeof(T) == typeof(IntPtr))
        {
            return (T)(object)((nint)(IntPtr)(object)left * (nint)(IntPtr)(object)right);
        }
        throw new NotSupportedException(SR.Arg_TypeNotSupported);
    }
References System.SR.Arg_TypeNotSupported.
Referenced by System.Numerics.Vector< T >.Dot(), System.Numerics.Vector< T >.operator*(), and System.Numerics.Vector< T >.operator*().