Terraria: System.Numerics.Vector.LessThan
LessThan() [2/5]
static Vector< int > System.Numerics.Vector< T >.LessThan (Vector< float > left, Vector< float > right) inline static
Definition at line 99 of file Vector.cs.
    {
        return (Vector<int>)Vector<float>.LessThan(left, right);
    }
References System.Numerics.Vector< T >.LessThan().
Referenced by System.Text.Unicode.Utf16Utility.GetPointerToFirstInvalidChar(), System.Text.Json.JsonReaderHelper.IndexOfOrLessThan(), System.Numerics.Vector< T >.LessThan(), System.Numerics.Vector< T >.LessThan(), System.Numerics.Vector< T >.LessThan(), System.Numerics.Vector< T >.LessThan(), System.Numerics.Vector< T >.LessThan< T >(), System.Numerics.Vector< T >.LessThanAll< T >(), and System.Numerics.Vector< T >.LessThanAny< T >().