Terraria: GraniteBiome.BuildMagmaMap
BuildMagmaMap()
void GraniteBiome.BuildMagmaMap (Point tileOrigin) inline private
     {
         _sourceMagmaMap = new Magma[200, 200];
         _targetMagmaMap = new Magma[200, 200];
         for (int i = 0; i < _sourceMagmaMap.GetLength(0); i++)
         {
             for (int j = 0; j < _sourceMagmaMap.GetLength(1); j++)
             {
                 int i2 = i + tileOrigin.X;
                 int j2 = j + tileOrigin.Y;
                 _sourceMagmaMap[i, j] = Magma.CreateEmpty((!WorldGen.SolidTile(i2, j2)) ? 1 : 4);
                 _targetMagmaMap[i, j] = _sourceMagmaMap[i, j];
             }
         }
     }
References _sourceMagmaMap, _targetMagmaMap, GraniteBiome.Magma.CreateEmpty(), and WorldGen.SolidTile().
Referenced by Place().