Terraria: System.Net.WebSockets.WebSocketBuffer.IsNativeBuffer
IsNativeBuffer()
bool System.Net.WebSockets.WebSocketBuffer.IsNativeBuffer (IntPtr pBuffer, uint bufferSize) inline private
Definition at line 400 of file WebSocketBuffer.cs.
    {
        long num = pBuffer.ToInt64();
        long num2 = bufferSize + num;
        if (num >= _startAddress && num <= _endAddress && num2 >= _startAddress && num2 <= _endAddress)
        {
            return true;
        }
        return false;
    }
References System.Net.WebSockets.WebSocketBuffer._endAddress, System.Net.WebSockets.WebSocketBuffer._startAddress, and System.IntPtr.ToInt64().
Referenced by System.Net.WebSockets.WebSocketBuffer.ConvertCloseBuffer(), System.Net.WebSockets.WebSocketBuffer.ConvertNativeBuffer(), and System.Net.WebSockets.WebSocketBuffer.ValidateNativeBuffers().