Terraria: System.Net.WebSockets.WebSocketBuffer.Validate
Validate()
static void System.Net.WebSockets.WebSocketBuffer.Validate (int count, int receiveBufferSize, int sendBufferSize, bool isServerBuffer) inline static package
Definition at line 426 of file WebSocketBuffer.cs.
    {
        int internalBufferSize = GetInternalBufferSize(receiveBufferSize, sendBufferSize, isServerBuffer);
        if (count < internalBufferSize)
        {
            throw new ArgumentOutOfRangeException("internalBuffer", System.SR.Format(System.SR.net_WebSockets_ArgumentOutOfRange_InternalBuffer, internalBufferSize));
        }
    }
References System.count, System.SR.Format(), System.Net.WebSockets.WebSocketBuffer.GetInternalBufferSize(), and System.SR.net_WebSockets_ArgumentOutOfRange_InternalBuffer.
Referenced by System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsync(), and System.Net.WebSockets.ServerWebSocket.Create().