Terraria: System.Net.WebSockets.WebSocketBuffer.ValidateNativeBuffers
ValidateNativeBuffers()
void System.Net.WebSockets.WebSocketBuffer.ValidateNativeBuffers (WebSocketProtocolComponent::Action action, WebSocketProtocolComponent::BufferType bufferType, global::Interop::WebSocket::Buffer[] dataBuffers, uint dataBufferCount) inline package
Definition at line 292 of file WebSocketBuffer.cs.
    {
        ThrowIfDisposed();
        if (dataBufferCount > dataBuffers.Length)
        {
            throw new AccessViolationException();
        }
        int num = dataBuffers.Length;
        bool flag = action == WebSocketProtocolComponent.Action.IndicateSendComplete || action == WebSocketProtocolComponent.Action.SendToNetwork;
        if (flag)
        {
            num = (int)dataBufferCount;
        }
        bool flag2 = false;
        for (int i = 0; i < num; i++)
        {
            global::Interop.WebSocket.Buffer buffer = dataBuffers[i];
            UnwrapWebSocketBuffer(buffer, bufferType, out var bufferData, out var bufferLength);
            if (!(bufferData == IntPtr.Zero))
            {
                flag2 = true;
                bool flag3 = IsPinnedSendPayloadBuffer(buffer, bufferType);
                if (bufferLength > GetMaxBufferSize() && (!flag || !flag3))
                {
                    throw new AccessViolationException();
                }
                if (!flag3 && !IsNativeBuffer(bufferData, bufferLength))
                {
                    throw new AccessViolationException();
                }
            }
        }
        if (!flag2 && action != 0 && action != WebSocketProtocolComponent.Action.IndicateReceiveComplete)
        {
            _ = 2;
        }
    }
References System.action, System.buffer, System.Net.WebSockets.WebSocketBuffer.GetMaxBufferSize(), System.Net.WebSockets.WebSocketBuffer.IsNativeBuffer(), System.Net.WebSockets.WebSocketBuffer.IsPinnedSendPayloadBuffer(), System.Net.WebSockets.WebSocketBuffer.ThrowIfDisposed(), System.Net.WebSockets.WebSocketBuffer.UnwrapWebSocketBuffer(), and System.IntPtr.Zero.
Referenced by System.Net.WebSockets.WebSocketBase.ValidateNativeBuffers().