Terraria: System.Net.WebSockets.WebSocketBuffer.IsPinnedSendPayloadBuffer
IsPinnedSendPayloadBuffer() [1/2]
bool System.Net.WebSockets.WebSocketBuffer.IsPinnedSendPayloadBuffer (byte[] buffer, int offset, int count) inline private
Definition at line 191 of file WebSocketBuffer.cs.
    {
        if (_sendBufferState != 1)
        {
            return false;
        }
        if (buffer == _pinnedSendBuffer.Array && offset >= _pinnedSendBuffer.Offset)
        {
            return offset + count <= _pinnedSendBuffer.Offset + _pinnedSendBuffer.Count;
        }
        return false;
    }
References System.Net.WebSockets.WebSocketBuffer._pinnedSendBuffer, System.Net.WebSockets.WebSocketBuffer._sendBufferState, System.ArraySegment< T >.Array, System.buffer, System.count, System.ArraySegment< T >.Count, System.offset, and System.ArraySegment< T >.Offset.
Referenced by System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadFromNative(), System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadToNative(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process(), and System.Net.WebSockets.WebSocketBuffer.ValidateNativeBuffers().