Terraria: System.Net.WebSockets.WebSocketBuffer.CreateProperties
CreateProperties()
global.Interop.WebSocket.Property[] System.Net.WebSockets.WebSocketBuffer.CreateProperties (bool useZeroMaskingKey) inline package
Definition at line 103 of file WebSocketBuffer.cs.
    {
        ThrowIfDisposed();
        IntPtr intPtr = _gcHandle.AddrOfPinnedObject();
        int offset = _propertyBuffer.Offset;
        Marshal.WriteInt32(intPtr, offset, _receiveBufferSize);
        offset += 4;
        Marshal.WriteInt32(intPtr, offset, _sendBufferSize);
        offset += 4;
        Marshal.WriteIntPtr(intPtr, offset, intPtr + _internalBuffer.Offset);
        offset += IntPtr.Size;
        Marshal.WriteInt32(intPtr, offset, useZeroMaskingKey ? 1 : 0);
        int num = (useZeroMaskingKey ? 4 : 3);
        global::Interop.WebSocket.Property[] array = new global::Interop.WebSocket.Property[num];
        offset = _propertyBuffer.Offset;
        array[0] = new global::Interop.WebSocket.Property
        {
            Type = WebSocketProtocolComponent.PropertyType.ReceiveBufferSize,
            PropertySize = 4u,
            PropertyData = IntPtr.Add(intPtr, offset)
        };
        offset += 4;
        array[1] = new global::Interop.WebSocket.Property
        {
            Type = WebSocketProtocolComponent.PropertyType.SendBufferSize,
            PropertySize = 4u,
            PropertyData = IntPtr.Add(intPtr, offset)
        };
        offset += 4;
        array[2] = new global::Interop.WebSocket.Property
        {
            Type = WebSocketProtocolComponent.PropertyType.AllocatedBuffer,
            PropertySize = (uint)_nativeBuffer.Count,
            PropertyData = IntPtr.Add(intPtr, offset)
        };
        offset += IntPtr.Size;
        if (useZeroMaskingKey)
        {
            array[3] = new global::Interop.WebSocket.Property
            {
                Type = WebSocketProtocolComponent.PropertyType.DisableMasking,
                PropertySize = 4u,
                PropertyData = IntPtr.Add(intPtr, offset)
            };
        }
        return array;
    }
References System.Net.WebSockets.WebSocketBuffer._gcHandle, System.Net.WebSockets.WebSocketBuffer._internalBuffer, System.Net.WebSockets.WebSocketBuffer._nativeBuffer, System.Net.WebSockets.WebSocketBuffer._propertyBuffer, System.Net.WebSockets.WebSocketBuffer._receiveBufferSize, System.Net.WebSockets.WebSocketBuffer._sendBufferSize, System.IntPtr.Add(), System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject(), System.array, System.ArraySegment< T >.Count, System.offset, System.ArraySegment< T >.Offset, System.IntPtr.Size, System.Net.WebSockets.WebSocketBuffer.ThrowIfDisposed(), System.Runtime.InteropServices.Marshal.WriteInt32(), and System.Runtime.InteropServices.Marshal.WriteIntPtr().