Terraria: System.Net.WebSockets.WebSocketBuffer.ConvertNativeBuffer
ConvertNativeBuffer()
ArraySegment< byte > System.Net.WebSockets.WebSocketBuffer.ConvertNativeBuffer (WebSocketProtocolComponent::Action action, global::Interop::WebSocket::Buffer buffer, WebSocketProtocolComponent::BufferType bufferType) inline package
Definition at line 258 of file WebSocketBuffer.cs.
    {
        ThrowIfDisposed();
        UnwrapWebSocketBuffer(buffer, bufferType, out var bufferData, out var bufferLength);
        if (bufferData == IntPtr.Zero)
        {
            return ArraySegment<byte>.Empty;
        }
        if (IsNativeBuffer(bufferData, bufferLength))
        {
            return new ArraySegment<byte>(_internalBuffer.Array, GetOffset(bufferData), (int)bufferLength);
        }
        throw new AccessViolationException();
    }
References System.Net.WebSockets.WebSocketBuffer._internalBuffer, System.ArraySegment< T >.Array, System.buffer, System.ArraySegment< T >.Empty, System.Net.WebSockets.WebSocketBuffer.GetOffset(), System.Net.WebSockets.WebSocketBuffer.IsNativeBuffer(), System.Net.WebSockets.WebSocketBuffer.ThrowIfDisposed(), System.Net.WebSockets.WebSocketBuffer.UnwrapWebSocketBuffer(), and System.IntPtr.Zero.
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process(), and System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.ProcessAction_IndicateReceiveComplete().