Terraria: System.Net.WebSockets.WebSocketBuffer.ConvertCloseBuffer
ConvertCloseBuffer()
void System.Net.WebSockets.WebSocketBuffer.ConvertCloseBuffer (WebSocketProtocolComponent::Action action, global::Interop::WebSocket::Buffer buffer, out WebSocketCloseStatus closeStatus, out string reason) inline package
Definition at line 273 of file WebSocketBuffer.cs.
    {
        ThrowIfDisposed();
        closeStatus = (WebSocketCloseStatus)buffer.CloseStatus.CloseStatus;
        UnwrapWebSocketBuffer(buffer, WebSocketProtocolComponent.BufferType.Close, out var bufferData, out var bufferLength);
        if (bufferData == IntPtr.Zero)
        {
            reason = null;
            return;
        }
        if (IsNativeBuffer(bufferData, bufferLength))
        {
            ArraySegment<byte> arraySegment = new ArraySegment<byte>(_internalBuffer.Array, GetOffset(bufferData), (int)bufferLength);
            reason = Encoding.UTF8.GetString(arraySegment.Array, arraySegment.Offset, arraySegment.Count);
            return;
        }
        throw new AccessViolationException();
    }
References System.Net.WebSockets.WebSocketBuffer._internalBuffer, System.ArraySegment< T >.Array, System.buffer, System.ArraySegment< T >.Count, System.Net.WebSockets.WebSocketBuffer.GetOffset(), System.Net.WebSockets.WebSocketBuffer.IsNativeBuffer(), System.ArraySegment< T >.Offset, System.Net.WebSockets.WebSocketBuffer.ThrowIfDisposed(), System.Net.WebSockets.WebSocketBuffer.UnwrapWebSocketBuffer(), System.Text.Encoding.UTF8, and System.IntPtr.Zero.
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.ReceiveOperation.ProcessAction_IndicateReceiveComplete().