Terraria: System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadToNative
ConvertPinnedSendPayloadToNative() [1/2]
IntPtr System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadToNative (ArraySegment< byte > payload) inline package
Definition at line 166 of file WebSocketBuffer.cs.
    {
        return ConvertPinnedSendPayloadToNative(payload.Array, payload.Offset, payload.Count);
    }
References System.ArraySegment< T >.Array, System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadToNative(), System.ArraySegment< T >.Count, and System.ArraySegment< T >.Offset.
Referenced by System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadToNative(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.CreateBuffer(), System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CreateBuffer(), and System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.UpdateDataChunk().