Terraria: System.Net.WebSockets.WebSocketBuffer.ReleasePinnedSendBuffer
ReleasePinnedSendBuffer()
void System.Net.WebSockets.WebSocketBuffer.ReleasePinnedSendBuffer () inline package
Definition at line 220 of file WebSocketBuffer.cs.
    {
        int num = Interlocked.Exchange(ref _sendBufferState, 0);
        if (num == 1)
        {
            if (_pinnedSendBufferHandle.IsAllocated)
            {
                _pinnedSendBufferHandle.Free();
            }
            _pinnedSendBuffer = ArraySegment<byte>.Empty;
        }
    }
References System.Net.WebSockets.WebSocketBuffer._pinnedSendBuffer, System.Net.WebSockets.WebSocketBuffer._pinnedSendBufferHandle, System.Net.WebSockets.WebSocketBuffer._sendBufferState, System.ArraySegment< T >.Empty, System.Threading.Interlocked.Exchange(), System.Runtime.InteropServices.GCHandle.Free(), and System.Runtime.InteropServices.GCHandle.IsAllocated.
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.Cleanup(), and System.Net.WebSockets.WebSocketBuffer.CleanUp().