Terraria: System.Net.WebSockets.WebSocketBuffer.WebSocketBuffer
WebSocketBuffer()
System.Net.WebSockets.WebSocketBuffer.WebSocketBuffer (ArraySegment< byte > internalBuffer, int receiveBufferSize, int sendBufferSize) inline private
Definition at line 69 of file WebSocketBuffer.cs.
    {
        _receiveBufferSize = receiveBufferSize;
        _sendBufferSize = sendBufferSize;
        _internalBuffer = internalBuffer;
        _gcHandle = GCHandle.Alloc(internalBuffer.Array, GCHandleType.Pinned);
        int num = _receiveBufferSize + _sendBufferSize + 144;
        _startAddress = Marshal.UnsafeAddrOfPinnedArrayElement(internalBuffer.Array, internalBuffer.Offset).ToInt64();
        _endAddress = _startAddress + num;
        _nativeBuffer = new ArraySegment<byte>(internalBuffer.Array, internalBuffer.Offset, num);
        _payloadBuffer = new ArraySegment<byte>(internalBuffer.Array, _nativeBuffer.Offset + _nativeBuffer.Count, _receiveBufferSize);
        _propertyBuffer = new ArraySegment<byte>(internalBuffer.Array, _payloadBuffer.Offset + _payloadBuffer.Count, s_PropertyBufferSize);
        _sendBufferState = 0;
    }
References System.Net.WebSockets.WebSocketBuffer._endAddress, System.Net.WebSockets.WebSocketBuffer._gcHandle, System.Net.WebSockets.WebSocketBuffer._internalBuffer, System.Net.WebSockets.WebSocketBuffer._nativeBuffer, System.Net.WebSockets.WebSocketBuffer._payloadBuffer, System.Net.WebSockets.WebSocketBuffer._propertyBuffer, System.Net.WebSockets.WebSocketBuffer._receiveBufferSize, System.Net.WebSockets.WebSocketBuffer._sendBufferSize, System.Net.WebSockets.WebSocketBuffer._sendBufferState, System.Net.WebSockets.WebSocketBuffer._startAddress, System.Runtime.InteropServices.GCHandle.Alloc(), System.ArraySegment< T >.Array, System.ArraySegment< T >.Count, System.ArraySegment< T >.Offset, System.Net.WebSockets.WebSocketBuffer.s_PropertyBufferSize, and System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement().
Referenced by System.Net.WebSockets.WebSocketBuffer.CreateServerBuffer().