Terraria: System.Net.WebSockets.WebSocketBuffer.UnwrapWebSocketBuffer
UnwrapWebSocketBuffer()
static void System.Net.WebSockets.WebSocketBuffer.UnwrapWebSocketBuffer (global::Interop::WebSocket::Buffer buffer, WebSocketProtocolComponent::BufferType bufferType, out IntPtr bufferData, out uint bufferLength) inline static package
Definition at line 339 of file WebSocketBuffer.cs.
    {
        bufferData = IntPtr.Zero;
        bufferLength = 0u;
        switch (bufferType)
        {
        case WebSocketProtocolComponent.BufferType.Close:
            bufferData = buffer.CloseStatus.ReasonData;
            bufferLength = buffer.CloseStatus.ReasonLength;
            break;
        case WebSocketProtocolComponent.BufferType.UTF8Message:
        case WebSocketProtocolComponent.BufferType.UTF8Fragment:
        case WebSocketProtocolComponent.BufferType.BinaryMessage:
        case WebSocketProtocolComponent.BufferType.BinaryFragment:
        case WebSocketProtocolComponent.BufferType.PingPong:
        case WebSocketProtocolComponent.BufferType.UnsolicitedPong:
        case WebSocketProtocolComponent.BufferType.None:
            bufferData = buffer.Data.BufferData;
            bufferLength = buffer.Data.BufferLength;
            break;
        }
    }
References System.buffer, and System.IntPtr.Zero.
Referenced by System.Net.WebSockets.WebSocketBuffer.ConvertCloseBuffer(), System.Net.WebSockets.WebSocketBuffer.ConvertNativeBuffer(), System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadFromNative(), System.Net.WebSockets.WebSocketBuffer.IsPinnedSendPayloadBuffer(), and System.Net.WebSockets.WebSocketBuffer.ValidateNativeBuffers().