Terraria: System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadFromNative
ConvertPinnedSendPayloadFromNative()
ArraySegment< byte > System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadFromNative (global::Interop::WebSocket::Buffer buffer, WebSocketProtocolComponent::BufferType bufferType) inline package
Definition at line 180 of file WebSocketBuffer.cs.
    {
        if (!IsPinnedSendPayloadBuffer(buffer, bufferType))
        {
            throw new AccessViolationException();
        }
        UnwrapWebSocketBuffer(buffer, bufferType, out var bufferData, out var bufferLength);
        int num = (int)(bufferData.ToInt64() - _pinnedSendBufferStartAddress);
        return new ArraySegment<byte>(_pinnedSendBuffer.Array, _pinnedSendBuffer.Offset + num, (int)bufferLength);
    }
References System.Net.WebSockets.WebSocketBuffer._pinnedSendBuffer, System.Net.WebSockets.WebSocketBuffer._pinnedSendBufferStartAddress, System.ArraySegment< T >.Array, System.buffer, System.Net.WebSockets.WebSocketBuffer.IsPinnedSendPayloadBuffer(), System.ArraySegment< T >.Offset, and System.Net.WebSockets.WebSocketBuffer.UnwrapWebSocketBuffer().
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.Process().