Terraria: System.Globalization.GlobalizationMode.UseNls
UseNls
bool System.Globalization.GlobalizationMode.UseNls = !Invariant && (AppContextConfigHelper.GetBooleanConfig("System.Globalization.UseNls", "DOTNET_SYSTEM_GLOBALIZATION_USENLS") || !LoadIcu()) static get package
Definition at line 21 of file GlobalizationMode.cs.
{ get; } = !Invariant && (AppContextConfigHelper.GetBooleanConfig("System.Globalization.UseNls", "DOTNET_SYSTEM_GLOBALIZATION_USENLS") || !LoadIcu());
Referenced by System.Globalization.TextInfo.TextInfo(), System.Globalization.TextInfo.ChangeCaseCore(), System.Globalization.CompareInfo.CompareStringCore(), System.Globalization.Ordinal.CompareStringIgnoreCaseNonAscii(), System.Globalization.CompareInfo.CreateSortKeyCore(), System.Globalization.CompareInfo.EndsWithCore(), System.Globalization.IdnMapping.GetAscii(), System.Globalization.CalendarData.GetCalendarsCore(), System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureInfo.GetCultureInfo(), System.Globalization.CultureData.GetCultures(), System.Globalization.CompareInfo.GetHashCodeOfStringCore(), System.Globalization.CultureData.GetLanguageDisplayNameCore(), System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CultureData.GetLocaleInfoCore(), System.Globalization.CompareInfo.GetSortKeyCore(), System.Globalization.CompareInfo.GetSortKeyLengthCore(), System.Globalization.CultureData.GetTimeFormatsCore(), System.Globalization.IdnMapping.GetUnicode(), System.Globalization.CompareInfo.IndexOfCore(), System.Globalization.Ordinal.IndexOfOrdinalIgnoreCase(), System.Globalization.CultureData.InitCultureDataCore(), System.Globalization.CompareInfo.InitSort(), System.Globalization.Normalization.IsNormalized(), System.Globalization.CompareInfo.IsSortable(), System.Globalization.Ordinal.LastIndexOfOrdinalIgnoreCase(), System.Globalization.CalendarData.LoadCalendarDataFromSystemCore(), System.Globalization.Normalization.Normalize(), System.Globalization.CompareInfo.StartsWithCore(), System.Globalization.CalendarData.SystemSupportsTaiwaneseCalendar(), System.Globalization.Ordinal.ToUpperOrdinal(), System.TimeZoneInfo.TryConvertIanaIdToWindowsId(), and System.TimeZoneInfo.TryConvertWindowsIdToIanaId().