Terraria: System.Net.WebSockets.WebSocketBuffer.PinSendBuffer
PinSendBuffer()
void System.Net.WebSockets.WebSocketBuffer.PinSendBuffer (ArraySegment< byte > payload, out bool bufferHasBeenPinned) inline package
Definition at line 151 of file WebSocketBuffer.cs.
    {
        bufferHasBeenPinned = false;
        System.Net.WebSockets.WebSocketValidate.ValidateBuffer(payload.Array, payload.Offset, payload.Count);
        if (Interlocked.Exchange(ref _sendBufferState, 1) != 0)
        {
            throw new AccessViolationException();
        }
        _pinnedSendBuffer = payload;
        _pinnedSendBufferHandle = GCHandle.Alloc(_pinnedSendBuffer.Array, GCHandleType.Pinned);
        bufferHasBeenPinned = true;
        _pinnedSendBufferStartAddress = Marshal.UnsafeAddrOfPinnedArrayElement(_pinnedSendBuffer.Array, _pinnedSendBuffer.Offset).ToInt64();
        _pinnedSendBufferEndAddress = _pinnedSendBufferStartAddress + _pinnedSendBuffer.Count;
    }
References System.Net.WebSockets.WebSocketBuffer._pinnedSendBuffer, System.Net.WebSockets.WebSocketBuffer._pinnedSendBufferEndAddress, System.Net.WebSockets.WebSocketBuffer._pinnedSendBufferHandle, System.Net.WebSockets.WebSocketBuffer._pinnedSendBufferStartAddress, System.Net.WebSockets.WebSocketBuffer._sendBufferState, System.Runtime.InteropServices.GCHandle.Alloc(), System.ArraySegment< T >.Array, System.ArraySegment< T >.Count, System.Threading.Interlocked.Exchange(), System.ArraySegment< T >.Offset, System.Runtime.InteropServices.Marshal.UnsafeAddrOfPinnedArrayElement(), and System.Net.WebSockets.WebSocketValidate.ValidateBuffer().
Referenced by System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.CreateBuffer(), and System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CreateBuffer().