Terraria: System.Globalization.GlobalizationMode.LoadAppLocalIcuCore
LoadAppLocalIcuCore()
static void System.Globalization.GlobalizationMode.LoadAppLocalIcuCore (ReadOnlySpan< char > version, ReadOnlySpan< char > suffix) inline static private
Definition at line 88 of file GlobalizationMode.cs.
    {
        IntPtr intPtr = IntPtr.Zero;
        IntPtr intPtr2 = IntPtr.Zero;
        int num = version.IndexOf('.');
        if (num > 0)
        {
            ReadOnlySpan<char> version2 = version.Slice(0, num);
            intPtr = LoadLibrary(CreateLibraryName("icuuc", suffix, ".dll", version2), failOnLoadFailure: false);
            if (intPtr != IntPtr.Zero)
            {
                intPtr2 = LoadLibrary(CreateLibraryName("icuin", suffix, ".dll", version2), failOnLoadFailure: false);
            }
        }
        if (intPtr == IntPtr.Zero)
        {
            intPtr = LoadLibrary(CreateLibraryName("icuuc", suffix, ".dll", version), failOnLoadFailure: true);
        }
        if (intPtr2 == IntPtr.Zero)
        {
            intPtr2 = LoadLibrary(CreateLibraryName("icuin", suffix, ".dll", version), failOnLoadFailure: true);
        }
        Interop.Globalization.InitICUFunctions(intPtr, intPtr2, version, suffix);
    }
References System.Globalization.GlobalizationMode.CreateLibraryName(), Interop.Globalization.InitICUFunctions(), System.Globalization.GlobalizationMode.LoadLibrary(), System.ReadOnlySpan< T >.Slice(), System.suffix, and System.IntPtr.Zero.
Referenced by System.Globalization.GlobalizationMode.LoadAppLocalIcu().