Terraria: System.Net.WebSockets.WebSocketBuffer.CleanUp
CleanUp()
void System.Net.WebSockets.WebSocketBuffer.CleanUp () inline private
Definition at line 411 of file WebSocketBuffer.cs.
    {
        if (_gcHandle.IsAllocated)
        {
            _gcHandle.Free();
        }
        ReleasePinnedSendBuffer();
    }
References System.Net.WebSockets.WebSocketBuffer._gcHandle, System.Runtime.InteropServices.GCHandle.Free(), System.Runtime.InteropServices.GCHandle.IsAllocated, and System.Net.WebSockets.WebSocketBuffer.ReleasePinnedSendBuffer().
Referenced by System.Net.WebSockets.WebSocketBuffer.Dispose().