Terraria: System.Xml.XmlConverter.ToString
ToString() [2/14]
static string System.Xml.XmlConverter.ToString (byte[] buffer, int offset, int count) inline static
Definition at line 374 of file XmlConverter.cs.
    {
        try
        {
            return UTF8Encoding.GetString(buffer, offset, count);
        }
        catch (DecoderFallbackException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateEncodingException(buffer, offset, count, exception));
        }
    }
References System.buffer, System.count, System.Xml.XmlExceptionHelper.CreateEncodingException(), System.exception, System.Text.UTF8Encoding.GetString(), System.offset, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Xml.XmlBufferReader.Equals2(), System.Xml.ValueHandle.GetString(), System.Xml.XmlSigningNodeWriter.WriteGuidText(), System.Xml.XmlSigningNodeWriter.WriteTimeSpanText(), System.Xml.XmlSigningNodeWriter.WriteUniqueIdText(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), System.Xml.XmlBaseWriter.WriteValue(), and System.Xml.XmlBaseWriter.WriteValue().