Terraria: System.Xml.XmlConverter.ToSingle
ToSingle() [2/2]
static float System.Xml.XmlConverter.ToSingle (string value) inline static
Definition at line 158 of file XmlConverter.cs.
    {
        try
        {
            return XmlConvert.ToSingle(value);
        }
        catch (ArgumentException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "float", exception));
        }
        catch (FormatException exception2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "float", exception2));
        }
        catch (OverflowException exception3)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "float", exception3));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlConvert.ToSingle(), and System.value.
Referenced by System.Xml.XmlBaseReader.ReadContentAsFloat(), System.Xml.XmlDictionaryReader.ReadContentAsFloat(), System.Xml.XmlDictionaryReader.ReadElementContentAsFloat(), System.Xml.ValueHandle.ToSingle(), and System.Xml.XmlConverter.ToSingle().