Terraria: System.Xml.XmlConverter.ToChars
ToChars() [3/9]
static int System.Xml.XmlConverter.ToChars (DateTime value, byte[] chars, int offset) inline static
Definition at line 1209 of file XmlConverter.cs.
    {
        int num = offset;
        offset += ToCharsD4(value.Year, chars, offset);
        chars[offset++] = 45;
        offset += ToCharsD2(value.Month, chars, offset);
        chars[offset++] = 45;
        offset += ToCharsD2(value.Day, chars, offset);
        chars[offset++] = 84;
        offset += ToCharsD2(value.Hour, chars, offset);
        chars[offset++] = 58;
        offset += ToCharsD2(value.Minute, chars, offset);
        chars[offset++] = 58;
        offset += ToCharsD2(value.Second, chars, offset);
        int num2 = (int)(value.Ticks % 10000000);
        if (num2 != 0)
        {
            chars[offset++] = 46;
            offset += ToCharsD7(num2, chars, offset);
        }
        switch (value.Kind)
        {
        case DateTimeKind.Local:
        {
            TimeSpan utcOffset = TimeZoneInfo.Local.GetUtcOffset(value);
            if (utcOffset.Ticks < 0)
            {
                chars[offset++] = 45;
            }
            else
            {
                chars[offset++] = 43;
            }
            offset += ToCharsD2(Math.Abs(utcOffset.Hours), chars, offset);
            chars[offset++] = 58;
            offset += ToCharsD2(Math.Abs(utcOffset.Minutes), chars, offset);
            break;
        }
        case DateTimeKind.Utc:
            chars[offset++] = 90;
            break;
        default:
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException());
        case DateTimeKind.Unspecified:
            break;
        }
        return offset - num;
    }
References System.Math.Abs(), System.chars, System.Xml.Dictionary, System.TimeZoneInfo.Local, System.offset, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlConverter.ToCharsD2(), System.Xml.XmlConverter.ToCharsD4(), System.Xml.XmlConverter.ToCharsD7(), and System.value.