Terraria: System.Xml.XmlConverter.ToDouble
ToDouble() [2/2]
static double System.Xml.XmlConverter.ToDouble (string value) inline static
Definition at line 187 of file XmlConverter.cs.
    {
        try
        {
            return XmlConvert.ToDouble(value);
        }
        catch (ArgumentException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "double", exception));
        }
        catch (FormatException exception2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "double", exception2));
        }
        catch (OverflowException exception3)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "double", exception3));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlConvert.ToDouble(), and System.value.
Referenced by System.Runtime.Serialization.Json.JsonObjectDataContract.ParseJsonNumber(), System.Xml.XmlBaseReader.ReadContentAsDouble(), System.Xml.XmlDictionaryReader.ReadElementContentAsDouble(), System.Xml.ValueHandle.ToDouble(), and System.Xml.XmlConverter.ToDouble().