Terraria: System.Xml.XmlConverter.ToGuid
ToGuid() [2/2]
static Guid System.Xml.XmlConverter.ToGuid (string value) inline static
Definition at line 324 of file XmlConverter.cs.
    {
        try
        {
            return new Guid(Trim(value));
        }
        catch (FormatException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "Guid", exception));
        }
        catch (ArgumentException exception2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "Guid", exception2));
        }
        catch (OverflowException exception3)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "Guid", exception3));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Xml.Guid, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlConverter.Trim(), and System.value.
Referenced by System.Xml.XmlDictionaryReader.ReadContentAs(), System.Xml.XmlBaseReader.ReadContentAsGuid(), System.Xml.XmlDictionaryReader.ReadContentAsGuid(), System.Xml.ValueHandle.ToGuid(), and System.Xml.XmlConverter.ToGuid().