Terraria: System.Xml.XmlConverter.ToUniqueId
ToUniqueId() [2/2]
static UniqueId System.Xml.XmlConverter.ToUniqueId (string value) inline static
Definition at line 278 of file XmlConverter.cs.
    {
        try
        {
            return new UniqueId(Trim(value));
        }
        catch (ArgumentException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "UniqueId", exception));
        }
        catch (FormatException exception2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "UniqueId", exception2));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlConverter.Trim(), System.Xml.UniqueId, and System.value.
Referenced by System.Xml.XmlDictionaryReader.ReadContentAs(), System.Xml.XmlBaseReader.ReadContentAsUniqueId(), System.Xml.XmlDictionaryReader.ReadContentAsUniqueId(), System.Xml.ValueHandle.ToUniqueId(), and System.Xml.XmlConverter.ToUniqueId().