Terraria: System.Xml.XmlConverter.ToDateTime
ToDateTime() [2/3]
static DateTime System.Xml.XmlConverter.ToDateTime (long value) inline static
Definition at line 241 of file XmlConverter.cs.
    {
        try
        {
            return DateTime.FromBinary(value);
        }
        catch (ArgumentException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(ToString(value), "DateTime", exception));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.exception, System.DateTime.FromBinary(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.ToString, and System.value.
Referenced by System.Xml.XmlBaseReader.ReadContentAsDateTime(), System.Xml.ValueHandle.ToDateTime(), and System.Xml.XmlConverter.ToDateTime().