Terraria: System.Xml.XmlConverter.ToChars
ToChars() [6/9]
static int System.Xml.XmlConverter.ToChars (float value, byte[] buffer, int offset) inline static
Definition at line 941 of file XmlConverter.cs.
    {
        if (float.IsInfinity(value))
        {
            return ToInfinity(float.IsNegativeInfinity(value), buffer, offset);
        }
        if ((double)value == 0.0)
        {
            return ToZero(IsNegativeZero(value), buffer, offset);
        }
        return ToAsciiChars(value.ToString("R", NumberFormatInfo.InvariantInfo), buffer, offset);
    }
References System.buffer, System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlConverter.IsNegativeZero(), System.offset, System.Xml.XmlConverter.ToAsciiChars(), System.Xml.XmlConverter.ToInfinity(), System.ToZero, and System.value.