Terraria: System.Xml.XmlConverter.ToChars
ToChars() [2/9]
static int System.Xml.XmlConverter.ToChars (byte[] buffer, int offset, int count, char[] chars, int charOffset) inline static
Definition at line 410 of file XmlConverter.cs.
    {
        try
        {
            return UTF8Encoding.GetChars(buffer, offset, count, chars, charOffset);
        }
        catch (DecoderFallbackException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateEncodingException(buffer, offset, count, exception));
        }
    }
References System.buffer, System.chars, System.count, System.Xml.XmlExceptionHelper.CreateEncodingException(), System.Xml.Dictionary, System.exception, System.Text.UTF8Encoding.GetChars(), System.offset, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Xml.XmlBufferReader.GetChars(), System.Xml.XmlBufferReader.GetChars(), System.Xml.XmlConverter.ToString(), System.Xml.XmlSigningNodeWriter.WriteBoolText(), System.Xml.XmlUTF8NodeWriter.WriteBoolText(), System.Xml.XmlSigningNodeWriter.WriteDateTimeText(), System.Xml.XmlUTF8NodeWriter.WriteDateTimeText(), System.Xml.XmlSigningNodeWriter.WriteDecimalText(), System.Xml.XmlUTF8NodeWriter.WriteDecimalText(), System.Xml.XmlSigningNodeWriter.WriteDoubleText(), System.Xml.XmlUTF8NodeWriter.WriteDoubleText(), System.Xml.XmlSigningNodeWriter.WriteFloatText(), System.Xml.XmlUTF8NodeWriter.WriteFloatText(), System.Xml.XmlSigningNodeWriter.WriteInt32Text(), System.Xml.XmlUTF8NodeWriter.WriteInt32Text(), System.Xml.XmlSigningNodeWriter.WriteInt64Text(), System.Xml.XmlUTF8NodeWriter.WriteInt64Text(), System.Xml.XmlSigningNodeWriter.WriteUInt64Text(), and System.Xml.XmlUTF8NodeWriter.WriteUInt64Text().