Terraria: System.Xml.XmlConverter.ToCharsR
ToCharsR() [2/2]
static int System.Xml.XmlConverter.ToCharsR (long value, byte[] chars, int offset) inline static
Definition at line 862 of file XmlConverter.cs.
    {
        int num = 0;
        if (value >= 0)
        {
            while (value > int.MaxValue)
            {
                long num2 = value / 10;
                num++;
                chars[--offset] = (byte)(48 + (int)(value - num2 * 10));
                value = num2;
            }
        }
        else
        {
            while (value < int.MinValue)
            {
                long num3 = value / 10;
                num++;
                chars[--offset] = (byte)(48 - (int)(value - num3 * 10));
                value = num3;
            }
        }
        return num + ToCharsR((int)value, chars, offset);
    }
References System.chars, System.Xml.Dictionary, System.offset, System.Xml.XmlConverter.ToCharsR(), and System.value.
Referenced by System.Xml.XmlConverter.ToChars(), System.Xml.XmlConverter.ToChars(), System.Xml.XmlConverter.ToCharsD7(), and System.Xml.XmlConverter.ToCharsR().