Terraria: System.Xml.XmlConverter.ToUInt64
ToUInt64() [2/2]
static ulong System.Xml.XmlConverter.ToUInt64 (string value) inline static
Definition at line 349 of file XmlConverter.cs.
    {
        try
        {
            return ulong.Parse(value, NumberStyles.Any, NumberFormatInfo.InvariantInfo);
        }
        catch (ArgumentException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "UInt64", exception));
        }
        catch (FormatException exception2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "UInt64", exception2));
        }
        catch (OverflowException exception3)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(value, "UInt64", exception3));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Globalization.NumberFormatInfo.InvariantInfo, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.value.
Referenced by System.Runtime.Serialization.EnumDataContract.GetEnumValueFromString(), System.Xml.XmlBaseReader.ReadContentAs(), System.Runtime.Serialization.XmlReaderDelegator.ReadContentAsUnsignedLong(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsUnsignedLong(), System.Xml.XmlConverter.ToUInt64(), and System.Xml.ValueHandle.ToULong().