Terraria: System.Xml.XmlConverter.ToAsciiChars
ToAsciiChars()
static int System.Xml.XmlConverter.ToAsciiChars (string s, byte[] buffer, int offset) inline static private
Definition at line 964 of file XmlConverter.cs.
    {
        for (int i = 0; i < s.Length; i++)
        {
            buffer[offset++] = (byte)s[i];
        }
        return s.Length;
    }
References System.buffer, System.offset, and System.s.
Referenced by System.Xml.XmlConverter.ToChars(), System.Xml.XmlConverter.ToChars(), System.Xml.XmlConverter.ToChars(), and System.Xml.XmlConverter.ToChars().