Terraria: System.Xml.XmlConverter.TryParseDateTime
TryParseDateTime()
static bool System.Xml.XmlConverter.TryParseDateTime (byte[] chars, int offset, int count, out DateTime result) inline static private
Definition at line 1022 of file XmlConverter.cs.
    {
        int num = offset + count;
        result = DateTime.MaxValue;
        if (count < 19)
        {
            return false;
        }
        if (chars[offset + 4] != 45 || chars[offset + 7] != 45 || chars[offset + 10] != 84 || chars[offset + 13] != 58 || chars[offset + 16] != 58)
        {
            return false;
        }
        int num2 = ToInt32D4(chars, offset, 4);
        int num3 = ToInt32D2(chars, offset + 5);
        int num4 = ToInt32D2(chars, offset + 8);
        int num5 = ToInt32D2(chars, offset + 11);
        int num6 = ToInt32D2(chars, offset + 14);
        int num7 = ToInt32D2(chars, offset + 17);
        if ((num2 | num3 | num4 | num5 | num6 | num7) < 0)
        {
            return false;
        }
        DateTimeKind kind = DateTimeKind.Unspecified;
        offset += 19;
        int num8 = 0;
        if (offset < num && chars[offset] == 46)
        {
            offset++;
            int num9 = offset;
            while (offset < num)
            {
                byte b = chars[offset];
                if (b < 48 || b > 57)
                {
                    break;
                }
                offset++;
            }
            int num10 = offset - num9;
            if (num10 < 1 || num10 > 7)
            {
                return false;
            }
            num8 = ToInt32D7(chars, num9, num10);
            if (num8 < 0)
            {
                return false;
            }
            for (int i = num10; i < 7; i++)
            {
                num8 *= 10;
            }
        }
        bool flag = false;
        int num11 = 0;
        int num12 = 0;
        if (offset < num)
        {
            byte b2 = chars[offset];
            switch (b2)
            {
            case 90:
                offset++;
                kind = DateTimeKind.Utc;
                break;
            case 43:
            case 45:
                offset++;
                if (offset + 5 > num || chars[offset + 2] != 58)
                {
                    return false;
                }
                kind = DateTimeKind.Utc;
                flag = true;
                num11 = ToInt32D2(chars, offset);
                num12 = ToInt32D2(chars, offset + 3);
                if ((num11 | num12) < 0)
                {
                    return false;
                }
                if (b2 == 43)
                {
                    num11 = -num11;
                    num12 = -num12;
                }
                offset += 5;
                break;
            }
        }
        if (offset < num)
        {
            return false;
        }
        DateTime dateTime;
        try
        {
            dateTime = new DateTime(num2, num3, num4, num5, num6, num7, kind);
        }
        catch (ArgumentException)
        {
            return false;
        }
        if (num8 > 0)
        {
            dateTime = dateTime.AddTicks(num8);
        }
        if (flag)
        {
            try
            {
                TimeSpan timeSpan = new TimeSpan(num11, num12, 0);
                dateTime = (((num11 < 0 || !(dateTime < DateTime.MaxValue - timeSpan)) && (num11 >= 0 || !(dateTime > DateTime.MinValue - timeSpan))) ? dateTime.ToLocalTime().Add(timeSpan) : dateTime.Add(timeSpan).ToLocalTime());
            }
            catch (ArgumentOutOfRangeException)
            {
                return false;
            }
        }
        result = dateTime;
        return true;
    }
References System.chars, System.count, System.Xml.DateTime, System.Xml.Dictionary, System.DateTime.MaxValue, System.offset, System.Xml.TimeSpan, System.Xml.XmlConverter.ToInt32D2(), System.Xml.XmlConverter.ToInt32D4(), and System.Xml.XmlConverter.ToInt32D7().
Referenced by System.Xml.XmlConverter.ToDateTime().