Terraria: System.Xml.XmlConverter.Trim
Trim()
static string System.Xml.XmlConverter.Trim (string s) inline static private
Definition at line 1310 of file XmlConverter.cs.
    {
        int i;
        for (i = 0; i < s.Length && IsWhitespace(s[i]); i++)
        {
        }
        int num = s.Length;
        while (num > 0 && IsWhitespace(s[num - 1]))
        {
            num--;
        }
        if (i == 0 && num == s.Length)
        {
            return s;
        }
        if (num == 0)
        {
            return string.Empty;
        }
        return s.Substring(i, num - i);
    }
References System.Xml.Dictionary, System.Xml.XmlConverter.IsWhitespace(), and System.s.
Referenced by System.Xml.XmlConverter.ToGuid(), System.Xml.XmlConverter.ToQualifiedName(), and System.Xml.XmlConverter.ToUniqueId().