Terraria: System.Xml.XmlConverter.ToQualifiedName
ToQualifiedName()
static void System.Xml.XmlConverter.ToQualifiedName (string qname, out string prefix, out string localName) inline static
Definition at line 552 of file XmlConverter.cs.
    {
        int num = qname.IndexOf(':');
        if (num < 0)
        {
            prefix = string.Empty;
            localName = Trim(qname);
            return;
        }
        if (num == qname.Length - 1)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new XmlException(System.SR.Format(System.SR.XmlInvalidQualifiedName, qname)));
        }
        prefix = Trim(qname.Substring(0, num));
        localName = Trim(qname.Substring(num + 1));
    }
References System.SR.Format(), System.prefix, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlConverter.Trim(), System.Xml.XmlException, and System.SR.XmlInvalidQualifiedName.
Referenced by System.Xml.XmlDictionaryReader.ReadContentAsQualifiedName().