Terraria: CreativePowers.ModifyTimeRate.ProvideSlider
ProvideSlider()
override UIElement CreativePowers.ModifyTimeRate.ProvideSlider () inline virtual
Implements CreativePowers.ASharedSliderPower.
         {
             UIVerticalSlider uIVerticalSlider = CreativePowersHelper.CreateSlider(base.GetSliderValue, base.SetValueKeyboard, base.SetValueGamepad);
             uIVerticalSlider.OnUpdate += UpdateSliderAndShowMultiplierMouseOver;
             UIPanel uIPanel = new UIPanel();
             uIPanel.Width = new StyleDimension(87f, 0f);
             uIPanel.Height = new StyleDimension(180f, 0f);
             uIPanel.HAlign = 0f;
             uIPanel.VAlign = 0.5f;
             uIPanel.Append(uIVerticalSlider);
             uIPanel.OnUpdate += CreativePowersHelper.UpdateUseMouseInterface;
             UIText uIText = new UIText("x24")
             {
                 HAlign = 1f,
                 VAlign = 0f
             };
             uIText.OnMouseOver += Button_OnMouseOver;
             uIText.OnMouseOut += Button_OnMouseOut;
             uIText.OnLeftClick += topText_OnClick;
             uIPanel.Append(uIText);
             UIText uIText2 = new UIText("x12")
             {
                 HAlign = 1f,
                 VAlign = 0.5f
             };
             uIText2.OnMouseOver += Button_OnMouseOver;
             uIText2.OnMouseOut += Button_OnMouseOut;
             uIText2.OnLeftClick += middleText_OnClick;
             uIPanel.Append(uIText2);
             UIText uIText3 = new UIText("x1")
             {
                 HAlign = 1f,
                 VAlign = 1f
             };
             uIText3.OnMouseOver += Button_OnMouseOver;
             uIText3.OnMouseOut += Button_OnMouseOut;
             uIText3.OnLeftClick += bottomText_OnClick;
             uIPanel.Append(uIText3);
             return uIPanel;
         }
References UIElement.Append(), CreativePowers.ModifyTimeRate.bottomText_OnClick(), CreativePowers.ModifyTimeRate.Button_OnMouseOut(), CreativePowers.ModifyTimeRate.Button_OnMouseOver(), CreativePowersHelper.CreateSlider(), UIElement.HAlign, UIElement.Height, CreativePowers.ModifyTimeRate.middleText_OnClick(), UIElement.OnLeftClick, UIElement.OnMouseOut, UIElement.OnMouseOver, UIElement.OnUpdate, CreativePowers.ModifyTimeRate.topText_OnClick(), CreativePowers.ModifyTimeRate.UpdateSliderAndShowMultiplierMouseOver(), CreativePowersHelper.UpdateUseMouseInterface(), UIElement.VAlign, and UIElement.Width.