Terraria: System.Collections.Immutable.SecureObjectPool.NewId
NewId()
static int System.Collections.Immutable.SecureObjectPool< T, TCaller >.NewId () inline static package
Definition at line 11 of file SecureObjectPool.cs.
    {
        int num;
        do
        {
            num = Interlocked.Increment(ref s_poolUserIdCounter);
        }
        while (num == -1);
        return num;
    }
References System.Threading.Interlocked.Increment(), and System.Collections.Immutable.SecureObjectPool< T, TCaller >.s_poolUserIdCounter.
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Enumerator.Enumerator(), System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator.Enumerator(), System.Collections.Immutable.ImmutableList< T >.Enumerator.Enumerator(), and System.Collections.Immutable.SortedInt32KeyNode< TValue >.Enumerator.Enumerator().