Terraria: System.Xml.Xsl.XsltOld.AttributeAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.AttributeAction.Compile (Compiler compiler) inline package
Definition at line 53 of file AttributeAction.cs.
    {
        CompileAttributes(compiler);
        CheckRequiredAttribute(compiler, _nameAvt, "name");
        _name = CompiledAction.PrecalculateAvt(ref _nameAvt);
        _nsUri = CompiledAction.PrecalculateAvt(ref _nsAvt);
        if (_nameAvt == null && _nsAvt == null)
        {
            if (_name != "xmlns")
            {
                _qname = CreateAttributeQName(_name, _nsUri, compiler.CloneScopeManager());
            }
        }
        else
        {
            _manager = compiler.CloneScopeManager();
        }
        if (compiler.Recurse())
        {
            CompileTemplate(compiler);
            compiler.ToParent();
        }
    }
References System.Xml.Xsl.XsltOld.AttributeAction._manager, System.Xml.Xsl.XsltOld.AttributeAction._name, System.Xml.Xsl.XsltOld.AttributeAction._nameAvt, System.Xml.Xsl.XsltOld.AttributeAction._nsAvt, System.Xml.Xsl.XsltOld.AttributeAction._nsUri, System.Xml.Xsl.XsltOld.AttributeAction._qname, System.Xml.Xsl.XsltOld.CompiledAction.CheckRequiredAttribute(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTemplate(), System.Xml.Xsl.XsltOld.AttributeAction.CreateAttributeQName(), System.Xml.Dictionary, and System.Xml.Xsl.XsltOld.CompiledAction.PrecalculateAvt().