Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable.Unsubscribe
Unsubscribe()
void System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.Unsubscribe (IObserver< TOutput > observer) inline private
Definition at line 1112 of file DataflowBlock.cs.
        {
            lock (_SubscriptionLock)
            {
                ObserversState observersState = _observersState;
                if (observersState.Observers.Contains(observer))
                {
                    if (observersState.Observers.Count == 1)
                    {
                        ResetObserverState();
                    }
                    else
                    {
                        observersState.Observers = observersState.Observers.Remove(observer);
                    }
                }
            }
        }
References System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >._observersState, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >._SubscriptionLock, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ResetObserverState().