Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable.Subscribe
Subscribe() [2/2]
IDisposable IObservable< TOutput >. System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.Subscribe (IObserver< TOutput > observer) inline private
Definition at line 1072 of file DataflowBlock.cs.
        {
            if (observer == null)
            {
                throw new ArgumentNullException("observer");
            }
            Task potentiallyNotSupportedCompletionTask = Common.GetPotentiallyNotSupportedCompletionTask(_source);
            Exception ex = null;
            lock (_SubscriptionLock)
            {
                if (potentiallyNotSupportedCompletionTask == null || !potentiallyNotSupportedCompletionTask.IsCompleted || !_observersState.Target.Completion.IsCompleted)
                {
                    _observersState.Observers = _observersState.Observers.Add(observer);
                    if (_observersState.Observers.Count == 1)
                    {
                        _observersState.Unlinker = _source.LinkTo(_observersState.Target);
                        if (_observersState.Unlinker == null)
{
                            _observersState.Observers = ImmutableArray<IObserver<TOutput>>.Empty;
                            return Disposables.Nop;
                        }
                    }
                    return Disposables.Create(delegate(SourceObservable<TOutput> s, IObserver<TOutput> o)
                    {
                        s.Unsubscribe(o);
                    }, this, observer);
                }
                ex = GetCompletionError();
            }
            if (ex != null)
            {
                observer.OnError(ex);
            }
            else
            {
                observer.OnCompleted();
            }
            return Disposables.Nop;
        }
References System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >._observersState, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >._source, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >._SubscriptionLock, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.Tasks.Dataflow.ActionBlock< TInput >.Completion, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.GetCompletionError(), System.Threading.Tasks.Dataflow.Internal.Common.GetPotentiallyNotSupportedCompletionTask(), System.Threading.Tasks.Task< TResult >.IsCompleted, System.Threading.Tasks.Dataflow.ISourceBlock< out TOutput >.LinkTo(), System.Threading.Tasks.Dataflow.Internal.Disposables.Nop, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.Observers, System.s, System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.Target, and System.Threading.Tasks.Dataflow.DataflowBlock.SourceObservable< TOutput >.ObserversState.Unlinker.