Terraria: System.Xml.Schema.BaseProcessor.AddToTable
AddToTable()
void System.Xml.Schema.BaseProcessor.AddToTable (XmlSchemaObjectTable table, XmlQualifiedName qname, XmlSchemaObject item) inline protected inherited
Definition at line 51 of file BaseProcessor.cs.
    {
        if (qname.Name.Length == 0)
        {
            return;
        }
        XmlSchemaObject xmlSchemaObject = table[qname];
        if (xmlSchemaObject != null)
        {
            if (xmlSchemaObject == item)
            {
                return;
            }
            string code = System.SR.Sch_DupGlobalElement;
            if (item is XmlSchemaAttributeGroup)
            {
                string strA = _nameTable.Add(qname.Namespace);
                if (Ref.Equal(strA, _nsXml))
                {
                    XmlSchema buildInSchema = Preprocessor.GetBuildInSchema();
                    XmlSchemaObject xmlSchemaObject2 = buildInSchema.AttributeGroups[qname];
                    if (xmlSchemaObject == xmlSchemaObject2)
                    {
                        table.Insert(qname, item);
                        return;
                    }
                    if (item == xmlSchemaObject2)
                    {
                        return;
                    }
                }
                else if (IsValidAttributeGroupRedefine(xmlSchemaObject, item, table))
                {
                    return;
                }
                code = System.SR.Sch_DupAttributeGroup;
            }
            else if (item is XmlSchemaAttribute)
            {
                string strA2 = _nameTable.Add(qname.Namespace);
                if (Ref.Equal(strA2, _nsXml))
                {
                    XmlSchema buildInSchema2 = Preprocessor.GetBuildInSchema();
                    XmlSchemaObject xmlSchemaObject3 = buildInSchema2.Attributes[qname];
                    if (xmlSchemaObject == xmlSchemaObject3)
                    {
                        table.Insert(qname, item);
                        return;
                    }
                    if (item == xmlSchemaObject3)
                    {
                        return;
                    }
                }
                code = System.SR.Sch_DupGlobalAttribute;
            }
            else if (item is XmlSchemaSimpleType)
            {
                if (IsValidTypeRedefine(xmlSchemaObject, item, table))
                {
                    return;
                }
                code = System.SR.Sch_DupSimpleType;
            }
            else if (item is XmlSchemaComplexType)
            {
                if (IsValidTypeRedefine(xmlSchemaObject, item, table))
                {
                    return;
                }
                code = System.SR.Sch_DupComplexType;
            }
            else if (item is XmlSchemaGroup)
            {
                if (IsValidGroupRedefine(xmlSchemaObject, item, table))
                {
                    return;
                }
                code = System.SR.Sch_DupGroup;
            }
            else if (item is XmlSchemaNotation)
            {
                code = System.SR.Sch_DupNotation;
            }
            else if (item is XmlSchemaIdentityConstraint)
            {
                code = System.SR.Sch_DupIdentityConstraint;
            }
            SendValidationEvent(code, qname.ToString(), item);
        }
        else
        {
            table.Add(qname, item);
        }
    }
References System.Xml.Schema.BaseProcessor._nameTable, System.Xml.Schema.BaseProcessor._nsXml, System.Xml.XmlNameTable.Add(), System.Xml.Schema.XmlSchemaObjectTable.Add(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.Schema.Preprocessor.GetBuildInSchema(), System.Xml.Schema.XmlSchemaObjectTable.Insert(), System.Xml.Schema.BaseProcessor.IsValidAttributeGroupRedefine(), System.Xml.Schema.BaseProcessor.IsValidGroupRedefine(), System.Xml.Schema.BaseProcessor.IsValidTypeRedefine(), System.item, System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, System.SR.Sch_DupAttributeGroup, System.SR.Sch_DupComplexType, System.SR.Sch_DupGlobalAttribute, System.SR.Sch_DupGlobalElement, System.SR.Sch_DupGroup, System.SR.Sch_DupIdentityConstraint, System.SR.Sch_DupNotation, System.SR.Sch_DupSimpleType, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.Xml.XmlQualifiedName.ToString().
Referenced by System.Xml.Schema.Preprocessor.CopyIncludedComponents(), System.Xml.Schema.Compiler.Prepare(), System.Xml.Schema.Preprocessor.Preprocess(), System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), System.Xml.Schema.Preprocessor.PreprocessRedefine(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessRedefine().