Terraria: System.IO.Pipes.PipeStream.ReadAsync
ReadAsync() [2/3]
override Task< int > System.IO.Pipes.PipeStream.ReadAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 669 of file PipeStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        if (!CanRead)
        {
            throw Error.GetReadNotSupported();
        }
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled<int>(cancellationToken);
        }
        CheckReadOperations();
        if (!_isAsync)
        {
            return base.ReadAsync(buffer, offset, count, cancellationToken);
        }
        if (count == 0)
        {
            UpdateMessageCompletion(completion: false);
            return Task.FromResult(0);
        }
        return ReadAsyncCore(new Memory<byte>(buffer, offset, count), cancellationToken).AsTask();
    }
References System.IO.Pipes.PipeStream._isAsync, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.buffer, System.cancellationToken, System.IO.Pipes.PipeStream.CanRead, System.IO.Pipes.PipeStream.CheckReadOperations(), System.count, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.IO.Error.GetReadNotSupported(), System.offset, System.IO.Pipes.PipeStream.ReadAsyncCore(), System.IO.Pipes.PipeStream.UpdateMessageCompletion(), and System.IO.Stream.ValidateBufferArguments().
Referenced by System.IO.Pipes.PipeStream.BeginRead(), and System.IO.Pipes.PipeStream.Read().