Terraria: System.IO.Pipes.PipeStream.Read
Read() [1/2]
override int System.IO.Pipes.PipeStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 640 of file PipeStream.cs.
    {
        if (_isAsync)
        {
            return ReadAsync(buffer, offset, count, CancellationToken.None).GetAwaiter().GetResult();
        }
        Stream.ValidateBufferArguments(buffer, offset, count);
        if (!CanRead)
        {
            throw Error.GetReadNotSupported();
        }
        CheckReadOperations();
        return ReadCore(new Span<byte>(buffer, offset, count));
    }
References System.IO.Pipes.PipeStream._isAsync, System.buffer, System.IO.Pipes.PipeStream.CanRead, System.IO.Pipes.PipeStream.CheckReadOperations(), System.count, System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.IO.Error.GetReadNotSupported(), System.Threading.CancellationToken.None, System.offset, System.IO.Pipes.PipeStream.ReadAsync(), System.IO.Pipes.PipeStream.ReadCore(), and System.IO.Stream.ValidateBufferArguments().