Terraria: System.IO.Pipes.PipeStream.WinIOError
WinIOError()
Exception System.IO.Pipes.PipeStream.WinIOError (int errorCode) inline package
Definition at line 1037 of file PipeStream.cs.
    {
        switch (errorCode)
        {
        case 109:
        case 232:
        case 233:
            _state = PipeState.Broken;
            return new IOException(System.SR.IO_PipeBroken, System.IO.Win32Marshal.MakeHRFromErrorCode(errorCode));
        case 38:
            return Error.GetEndOfFile();
        case 6:
            _handle.SetHandleAsInvalid();
            _state = PipeState.Broken;
            break;
        }
        return System.IO.Win32Marshal.GetExceptionForWin32Error(errorCode);
    }
References System.IO.Pipes.PipeStream._handle, System.IO.Pipes.PipeStream._state, System.IO.Error.GetEndOfFile(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.SR.IO_PipeBroken, System.IO.Win32Marshal.MakeHRFromErrorCode(), and System.Runtime.InteropServices.SafeHandle.SetHandleAsInvalid().
Referenced by System.IO.Pipes.PipeStream.ReadWriteValueTaskSource.CompleteCore(), System.IO.Pipes.NamedPipeServerStream.HandleGetImpersonationUserNameError(), System.IO.Pipes.NamedPipeServerStream.RunAsClient(), System.IO.Pipes.PipeStream.UpdateReadMode(), System.IO.Pipes.PipeStream.WaitForPipeDrain(), System.IO.Pipes.PipeStream.WriteAsyncCore(), and System.IO.Pipes.PipeStream.WriteCore().