Terraria: System.IO.Pipes.PipeStream.ValidateHandleIsPipe
ValidateHandleIsPipe()
void System.IO.Pipes.PipeStream.ValidateHandleIsPipe (SafePipeHandle safePipeHandle) inline package
Definition at line 841 of file PipeStream.cs.
    {
        if (global::Interop.Kernel32.GetFileType(safePipeHandle) != 3)
        {
            throw new IOException(System.SR.IO_InvalidPipeHandle);
        }
    }
References System.SR.IO_InvalidPipeHandle.
Referenced by System.IO.Pipes.AnonymousPipeServerStream.AnonymousPipeServerStream(), System.IO.Pipes.NamedPipeClientStream.NamedPipeClientStream(), System.IO.Pipes.NamedPipeServerStream.NamedPipeServerStream(), and System.IO.Pipes.AnonymousPipeClientStream.Init().