Terraria: System.IO.Pipes.PipeStream.Write
Write() [1/2]
override void System.IO.Pipes.PipeStream.Write (byte[] buffer, int offset, int count) inline
Definition at line 734 of file PipeStream.cs.
    {
        if (_isAsync)
        {
            WriteAsync(buffer, offset, count, CancellationToken.None).GetAwaiter().GetResult();
            return;
        }
        Stream.ValidateBufferArguments(buffer, offset, count);
        if (!CanWrite)
        {
            throw Error.GetWriteNotSupported();
        }
        CheckWriteOperations();
        WriteCore(new ReadOnlySpan<byte>(buffer, offset, count));
    }
References System.IO.Pipes.PipeStream._isAsync, System.buffer, System.IO.Pipes.PipeStream.CanWrite, System.IO.Pipes.PipeStream.CheckWriteOperations(), System.count, System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.IO.Error.GetWriteNotSupported(), System.Threading.CancellationToken.None, System.offset, System.IO.Stream.ValidateBufferArguments(), System.IO.Pipes.PipeStream.WriteAsync(), and System.IO.Pipes.PipeStream.WriteCore().