Terraria: System.IO.Pipes.PipeStream.WriteCore
WriteCore()
unsafe void System.IO.Pipes.PipeStream.WriteCore (ReadOnlySpan< byte > buffer) inline private
Definition at line 941 of file PipeStream.cs.
    {
        if (buffer.Length == 0)
        {
            return;
        }
        fixed (byte* bytes = &MemoryMarshal.GetReference(buffer))
        {
            int numBytesWritten = 0;
            if (global::Interop.Kernel32.WriteFile(_handle, bytes, buffer.Length, out numBytesWritten, IntPtr.Zero) == 0)
            {
                throw WinIOError(Marshal.GetLastPInvokeError());
            }
        }
    }
References System.IO.Pipes.PipeStream._handle, System.buffer, System.bytes, System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.IO.Pipes.PipeStream.WinIOError(), and System.IntPtr.Zero.
Referenced by System.IO.Pipes.PipeStream.Write(), and System.IO.Pipes.PipeStream.Write().