Terraria: System.IO.Pipes.PipeStream.CheckReadOperations
CheckReadOperations()
void System.IO.Pipes.PipeStream.CheckReadOperations () inline package
Definition at line 596 of file PipeStream.cs.
    {
        if (_state == PipeState.WaitingToConnect)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_PipeNotYetConnected);
        }
        if (_state == PipeState.Disconnected)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_PipeDisconnected);
        }
        if (_handle == null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_PipeHandleNotSet);
        }
        if (_state == PipeState.Closed || (_handle != null && _handle.IsClosed))
        {
            throw Error.GetPipeNotOpen();
        }
    }
References System.IO.Pipes.PipeStream._handle, System.IO.Pipes.PipeStream._state, System.IO.Error.GetPipeNotOpen(), System.SR.InvalidOperation_PipeDisconnected, System.SR.InvalidOperation_PipeHandleNotSet, System.SR.InvalidOperation_PipeNotYetConnected, and System.Runtime.InteropServices.SafeHandle.IsClosed.
Referenced by System.IO.Pipes.PipeStream.Read(), System.IO.Pipes.PipeStream.Read(), System.IO.Pipes.PipeStream.ReadAsync(), and System.IO.Pipes.PipeStream.ReadAsync().