Terraria: System.IO.Pipes.PipeStream.InitializeHandle
InitializeHandle()
void System.IO.Pipes.PipeStream.InitializeHandle (SafePipeHandle? handle, bool isExposed, bool isAsync) inline protected
Definition at line 507 of file PipeStream.cs.
    {
        if (isAsync && handle != null)
        {
            InitializeAsyncHandle(handle);
        }
        _handle = handle;
        _isAsync = isAsync;
        _isHandleExposed = isExposed;
        _isFromExistingHandle = isExposed;
    }
References System.IO.Pipes.PipeStream._handle, System.IO.Pipes.PipeStream._isAsync, System.IO.Pipes.PipeStream._isFromExistingHandle, System.IO.Pipes.PipeStream._isHandleExposed, System.handle, and System.IO.Pipes.PipeStream.InitializeAsyncHandle().
Referenced by System.IO.Pipes.AnonymousPipeServerStream.AnonymousPipeServerStream(), System.IO.Pipes.NamedPipeClientStream.NamedPipeClientStream(), System.IO.Pipes.NamedPipeServerStream.NamedPipeServerStream(), System.IO.Pipes.AnonymousPipeServerStream.Create(), System.IO.Pipes.NamedPipeServerStream.Create(), System.IO.Pipes.AnonymousPipeClientStream.Init(), and System.IO.Pipes.NamedPipeClientStream.TryConnect().