Terraria: System.IO.Pipes.PipeStream.Dispose
Dispose() [2/2]
override void System.IO.Pipes.PipeStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 552 of file PipeStream.cs.
    {
        try
        {
            if (_handle != null && !_handle.IsClosed)
            {
                _handle.Dispose();
            }
            DisposeCore(disposing);
        }
        finally
        {
            base.Dispose(disposing);
        }
        _state = PipeState.Closed;
    }
References System.IO.Pipes.PipeStream._handle, System.IO.Pipes.PipeStream._state, System.Runtime.InteropServices.SafeHandle.Dispose(), System.IO.Pipes.PipeStream.DisposeCore(), and System.Runtime.InteropServices.SafeHandle.IsClosed.
Referenced by Terraria.Social.WeGame.IPCBase.Reset().