Terraria: System.IO.Pipes.PipeStream.ReadCore
ReadCore()
unsafe int System.IO.Pipes.PipeStream.ReadCore (Span< byte > buffer) inline private
Definition at line 873 of file PipeStream.cs.
    {
        if (buffer.Length == 0)
        {
            return 0;
        }
        fixed (byte* bytes = &MemoryMarshal.GetReference(buffer))
        {
            int numBytesRead = 0;
            if (global::Interop.Kernel32.ReadFile(_handle, bytes, buffer.Length, out numBytesRead, IntPtr.Zero) != 0)
            {
                _isMessageComplete = true;
                return numBytesRead;
            }
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            _isMessageComplete = lastPInvokeError != 234;
            switch (lastPInvokeError)
            {
            case 234:
                return numBytesRead;
            case 109:
            case 233:
                State = PipeState.Broken;
                return 0;
            default:
                throw System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError, string.Empty);
            }
        }
    }
References System.IO.Pipes.PipeStream._handle, System.IO.Pipes.PipeStream._isMessageComplete, System.buffer, System.bytes, System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), and System.IntPtr.Zero.
Referenced by System.IO.Pipes.PipeStream.Read(), and System.IO.Pipes.PipeStream.Read().