Terraria: System.IO.Pipes.PipeStream.ReadAsyncCore
ReadAsyncCore()
unsafe ValueTask< int > System.IO.Pipes.PipeStream.ReadAsyncCore (Memory< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 903 of file PipeStream.cs.
    {
        ReadWriteValueTaskSource readWriteValueTaskSource = Interlocked.Exchange(ref _reusableReadValueTaskSource, null) ?? new ReadWriteValueTaskSource(this, isWrite: false);
        try
        {
            readWriteValueTaskSource.PrepareForOperation(buffer);
            if (global::Interop.Kernel32.ReadFile(_handle, (byte*)readWriteValueTaskSource._memoryHandle.Pointer, buffer.Length, IntPtr.Zero, readWriteValueTaskSource._overlapped) == 0)
            {
                int lastPInvokeError = Marshal.GetLastPInvokeError();
                switch (lastPInvokeError)
                {
                case 997:
                    readWriteValueTaskSource.RegisterForCancellation(cancellationToken);
                    break;
                case 109:
                case 233:
                    State = PipeState.Broken;
                    readWriteValueTaskSource._overlapped->InternalLow = IntPtr.Zero;
                    readWriteValueTaskSource.Dispose();
                    UpdateMessageCompletion(completion: true);
                    return new ValueTask<int>(0);
                default:
                    readWriteValueTaskSource.Dispose();
                    return ValueTask.FromException<int>(System.IO.Win32Marshal.GetExceptionForWin32Error(lastPInvokeError));
                case 234:
                    break;
                }
            }
        }
        catch
        {
            readWriteValueTaskSource.Dispose();
            throw;
        }
        readWriteValueTaskSource.FinishedScheduling();
        return new ValueTask<int>(readWriteValueTaskSource, readWriteValueTaskSource.Version);
    }
References System.IO.Pipes.PipeStream._handle, System.IO.Pipes.PipeStream.PipeValueTaskSource._memoryHandle, System.IO.Pipes.PipeStream.PipeValueTaskSource._overlapped, System.IO.Pipes.PipeStream._reusableReadValueTaskSource, System.buffer, System.cancellationToken, System.IO.Pipes.PipeStream.PipeValueTaskSource.Dispose(), System.Threading.Interlocked.Exchange(), System.IO.Pipes.PipeStream.PipeValueTaskSource.FinishedScheduling(), System.Threading.Tasks.ValueTask< TResult >.FromException(), System.IO.Win32Marshal.GetExceptionForWin32Error(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.Threading.NativeOverlapped.InternalLow, System.Buffers.MemoryHandle.Pointer, System.IO.Pipes.PipeStream.PipeValueTaskSource.PrepareForOperation(), System.IO.Pipes.PipeStream.PipeValueTaskSource.RegisterForCancellation(), System.IO.Pipes.PipeStream.UpdateMessageCompletion(), System.IO.Pipes.PipeStream.PipeValueTaskSource.Version, and System.IntPtr.Zero.
Referenced by System.IO.Pipes.PipeStream.ReadAsync(), and System.IO.Pipes.PipeStream.ReadAsync().