Terraria: System.IO.Pipes.PipeStream.WriteAsyncCore
WriteAsyncCore()
unsafe ValueTask System.IO.Pipes.PipeStream.WriteAsyncCore (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken) inline private
Definition at line 957 of file PipeStream.cs.
    {
        ReadWriteValueTaskSource readWriteValueTaskSource = Interlocked.Exchange(ref _reusableWriteValueTaskSource, null) ?? new ReadWriteValueTaskSource(this, isWrite: true);
        try
        {
            readWriteValueTaskSource.PrepareForOperation(buffer);
            if (global::Interop.Kernel32.WriteFile(_handle, (byte*)readWriteValueTaskSource._memoryHandle.Pointer, buffer.Length, IntPtr.Zero, readWriteValueTaskSource._overlapped) == 0)
            {
                int lastPInvokeError = Marshal.GetLastPInvokeError();
                if (lastPInvokeError != 997)
                {
                    readWriteValueTaskSource.Dispose();
                    return ValueTask.FromException(ExceptionDispatchInfo.SetCurrentStackTrace(WinIOError(lastPInvokeError)));
                }
                readWriteValueTaskSource.RegisterForCancellation(cancellationToken);
            }
        }
        catch
        {
            readWriteValueTaskSource.Dispose();
            throw;
        }
        readWriteValueTaskSource.FinishedScheduling();
        return new ValueTask(readWriteValueTaskSource, readWriteValueTaskSource.Version);
    }
References System.IO.Pipes.PipeStream._handle, System.IO.Pipes.PipeStream.PipeValueTaskSource._memoryHandle, System.IO.Pipes.PipeStream.PipeValueTaskSource._overlapped, System.IO.Pipes.PipeStream._reusableWriteValueTaskSource, System.buffer, System.cancellationToken, System.IO.Pipes.PipeStream.PipeValueTaskSource.Dispose(), System.Threading.Interlocked.Exchange(), System.IO.Pipes.PipeStream.PipeValueTaskSource.FinishedScheduling(), System.Threading.Tasks.ValueTask< TResult >.FromException(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.Buffers.MemoryHandle.Pointer, System.IO.Pipes.PipeStream.PipeValueTaskSource.PrepareForOperation(), System.IO.Pipes.PipeStream.PipeValueTaskSource.RegisterForCancellation(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.IO.Pipes.PipeStream.PipeValueTaskSource.Version, System.IO.Pipes.PipeStream.WinIOError(), and System.IntPtr.Zero.
Referenced by System.IO.Pipes.PipeStream.WriteAsync(), and System.IO.Pipes.PipeStream.WriteAsync().