Terraria: System.IO.Pipes.PipeStream.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.IO.Pipes.PipeStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 693 of file PipeStream.cs.
    {
        if (!_isAsync)
        {
            return base.ReadAsync(buffer, cancellationToken);
        }
        if (!CanRead)
        {
            throw Error.GetReadNotSupported();
        }
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled<int>(cancellationToken);
        }
        CheckReadOperations();
        if (buffer.Length == 0)
        {
            UpdateMessageCompletion(completion: false);
            return new ValueTask<int>(0);
        }
        return ReadAsyncCore(buffer, cancellationToken);
    }
References System.IO.Pipes.PipeStream._isAsync, System.buffer, System.cancellationToken, System.IO.Pipes.PipeStream.CanRead, System.IO.Pipes.PipeStream.CheckReadOperations(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.IO.Error.GetReadNotSupported(), System.IO.Pipes.PipeStream.ReadAsyncCore(), and System.IO.Pipes.PipeStream.UpdateMessageCompletion().