Terraria: System.IO.Pipes.PipeStream.DisposeCore
DisposeCore()
void System.IO.Pipes.PipeStream.DisposeCore (bool disposing) inline private
Definition at line 863 of file PipeStream.cs.
    {
        if (disposing)
        {
            _threadPoolBinding?.Dispose();
            Interlocked.Exchange(ref _reusableReadValueTaskSource, null)?.Dispose();
            Interlocked.Exchange(ref _reusableWriteValueTaskSource, null)?.Dispose();
        }
    }
References System.IO.Pipes.PipeStream._reusableReadValueTaskSource, System.IO.Pipes.PipeStream._reusableWriteValueTaskSource, System.IO.Pipes.PipeStream._threadPoolBinding, System.Threading.ThreadPoolBoundHandle.Dispose(), and System.Threading.Interlocked.Exchange().
Referenced by System.IO.Pipes.PipeStream.Dispose().