Terraria: System.Xml.Schema.BaseProcessor.SendValidationEvent
SendValidationEvent() [6/9]
void System.Xml.Schema.BaseProcessor.SendValidationEvent (string code, XmlSchemaObject source) inline protected inherited
Definition at line 204 of file BaseProcessor.cs.
    {
        SendValidationEvent(new XmlSchemaException(code, source), XmlSeverityType.Error);
    }
References System.Xml.Dictionary, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.source.
Referenced by System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Schema.Compiler.CannonicalizeAll(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeAll(), System.Xml.Schema.Compiler.CannonicalizeChoice(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeChoice(), System.Xml.Schema.Compiler.CannonicalizeGroupRef(), System.Xml.Schema.SchemaCollectionCompiler.CannonicalizeGroupRef(), System.Xml.Schema.Compiler.CheckAtrributeGroupRestriction(), System.Xml.Schema.Compiler.CheckParticleDerivation(), System.Xml.Schema.SchemaCollectionCompiler.CheckParticleDerivation(), System.Xml.Schema.Compiler.CheckParticleDerivation(), System.Xml.Schema.Preprocessor.CheckRefinedAttributeGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.CheckRefinedAttributeGroup(), System.Xml.Schema.Preprocessor.CheckRefinedComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.CheckRefinedComplexType(), System.Xml.Schema.Preprocessor.CheckRefinedGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.CheckRefinedGroup(), System.Xml.Schema.Preprocessor.CheckRefinedSimpleType(), System.Xml.Schema.SchemaCollectionPreprocessor.CheckRefinedSimpleType(), System.Xml.Schema.SchemaCollectionCompiler.CheckSubstitutionGroup(), System.Xml.Schema.Compiler.CheckUnionType(), System.Xml.Schema.SchemaCollectionCompiler.CheckUnionType(), System.Xml.Schema.Compiler.CompileAnyAttributeIntersection(), System.Xml.Schema.SchemaCollectionCompiler.CompileAnyAttributeIntersection(), System.Xml.Schema.Compiler.CompileAnyAttributeUnion(), System.Xml.Schema.SchemaCollectionCompiler.CompileAnyAttributeUnion(), System.Xml.Schema.Compiler.CompileAttribute(), System.Xml.Schema.SchemaCollectionCompiler.CompileAttribute(), System.Xml.Schema.Compiler.CompileAttributeGroup(), System.Xml.Schema.SchemaCollectionCompiler.CompileAttributeGroup(), System.Xml.Schema.Compiler.CompileBaseMemberTypes(), System.Xml.Schema.SchemaCollectionCompiler.CompileBaseMemberTypes(), System.Xml.Schema.SchemaCollectionCompiler.CompileCompexTypeElements(), System.Xml.Schema.Compiler.CompileComplexContent(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContent(), System.Xml.Schema.Compiler.CompileComplexContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentExtension(), System.Xml.Schema.Compiler.CompileComplexContentRestriction(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexContentRestriction(), System.Xml.Schema.Compiler.CompileComplexType(), System.Xml.Schema.SchemaCollectionCompiler.CompileComplexType(), System.Xml.Schema.Compiler.CompileComplexTypeElements(), System.Xml.Schema.Compiler.CompileContentTypeParticle(), System.Xml.Schema.SchemaCollectionCompiler.CompileContentTypeParticle(), System.Xml.Schema.Compiler.CompileElement(), System.Xml.Schema.SchemaCollectionCompiler.CompileElement(), System.Xml.Schema.Compiler.CompileGroup(), System.Xml.Schema.SchemaCollectionCompiler.CompileGroup(), System.Xml.Schema.Compiler.CompileIdentityConstraint(), System.Xml.Schema.SchemaCollectionCompiler.CompileIdentityConstraint(), System.Xml.Schema.Compiler.CompileLocalAttributes(), System.Xml.Schema.SchemaCollectionCompiler.CompileLocalAttributes(), System.Xml.Schema.Compiler.CompileParticleElements(), System.Xml.Schema.SchemaCollectionCompiler.CompileParticleElements(), System.Xml.Schema.Compiler.CompileSimpleContentExtension(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentExtension(), System.Xml.Schema.Compiler.CompileSimpleContentRestriction(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleContentRestriction(), System.Xml.Schema.Compiler.CompileSimpleType(), System.Xml.Schema.SchemaCollectionCompiler.CompileSimpleType(), System.Xml.Schema.Compiler.CompileSubstitutionGroup(), System.Xml.Schema.SchemaCollectionCompiler.CompileSubstitutionGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.CountGroupSelfReference(), System.Xml.Schema.Preprocessor.CountGroupSelfReference(), System.Xml.Schema.Preprocessor.Execute(), System.Xml.Schema.Preprocessor.LoadExternals(), System.Xml.Schema.SchemaCollectionPreprocessor.LoadExternals(), System.Xml.Schema.Preprocessor.ParseUri(), System.Xml.Schema.Preprocessor.Preprocess(), System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), System.Xml.Schema.Preprocessor.PreprocessAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttribute(), System.Xml.Schema.Preprocessor.PreprocessAttributeContent(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeContent(), System.Xml.Schema.Preprocessor.PreprocessAttributeGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeGroup(), System.Xml.Schema.Preprocessor.PreprocessAttributes(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes(), System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.Preprocessor.PreprocessElement(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElement(), System.Xml.Schema.Preprocessor.PreprocessElementContent(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent(), System.Xml.Schema.Preprocessor.PreprocessGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessGroup(), System.Xml.Schema.Preprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.Preprocessor.PreprocessLocalAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalAttribute(), System.Xml.Schema.Preprocessor.PreprocessLocalElement(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalElement(), System.Xml.Schema.Preprocessor.PreprocessNotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessNotation(), System.Xml.Schema.Preprocessor.PreprocessParticle(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle(), System.Xml.Schema.Preprocessor.PreprocessRedefine(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessRedefine(), System.Xml.Schema.Preprocessor.PreprocessSimpleType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType(), System.Xml.Schema.Compiler.ProcessSubstitutionGroups(), System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.Compiler.SetDefaultFixed(), System.Xml.Schema.Preprocessor.SetSchemaDefaults(), System.Xml.Schema.Preprocessor.ValidateIdAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), System.Xml.Schema.Preprocessor.ValidateNameAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute(), System.Xml.Schema.Preprocessor.ValidateQNameAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().