Terraria: System.IO.Pipes.PipeStream.WriteAsync
WriteAsync() [2/3]
override Task System.IO.Pipes.PipeStream.WriteAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 765 of file PipeStream.cs.
    {
        Stream.ValidateBufferArguments(buffer, offset, count);
        if (!CanWrite)
        {
            throw Error.GetWriteNotSupported();
        }
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled<int>(cancellationToken);
        }
        CheckWriteOperations();
        if (!_isAsync)
        {
            return base.WriteAsync(buffer, offset, count, cancellationToken);
        }
        if (count == 0)
        {
            return Task.CompletedTask;
        }
        return WriteAsyncCore(new ReadOnlyMemory<byte>(buffer, offset, count), cancellationToken).AsTask();
    }
References System.IO.Pipes.PipeStream._isAsync, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.buffer, System.cancellationToken, System.IO.Pipes.PipeStream.CanWrite, System.IO.Pipes.PipeStream.CheckWriteOperations(), System.Threading.Tasks.Task< TResult >.CompletedTask, System.count, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.IO.Error.GetWriteNotSupported(), System.offset, System.IO.Stream.ValidateBufferArguments(), and System.IO.Pipes.PipeStream.WriteAsyncCore().
Referenced by System.IO.Pipes.PipeStream.BeginWrite(), and System.IO.Pipes.PipeStream.Write().