Terraria: Microsoft.Xna.Framework.Graphics.EffectParameter.SaveDataForRecreation
SaveDataForRecreation()
void Microsoft.Xna.Framework.Graphics.EffectParameter.SaveDataForRecreation () inline package
Definition at line 122 of file EffectParameter.cs.
    {
        pElementCollection.SaveDataForRecreation();
        pParamCollection.SaveDataForRecreation();
        if (pElementCollection.Count > 0)
        {
            return;
        }
        switch (_paramType)
        {
        case EffectParameterType.String:
            savedValue = GetValueString();
            break;
        case EffectParameterType.Bool:
        case EffectParameterType.Int32:
        case EffectParameterType.Single:
        {
            int num = _columns * _rows;
            if (num > 0)
            {
                savedValue = GetValueSingleArray(num);
            }
            break;
        }
        }
    }
References Microsoft.Xna.Framework.Graphics.EffectParameter._columns, Microsoft.Xna.Framework.Graphics.EffectParameter._paramType, Microsoft.Xna.Framework.Graphics.EffectParameter._rows, Microsoft.Xna.Framework.Graphics.EffectParameterCollection.Count, Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingleArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueString(), Microsoft.Xna.Framework.Graphics.EffectParameter.pElementCollection, Microsoft.Xna.Framework.Graphics.EffectParameter.pParamCollection, Microsoft.Xna.Framework.Graphics.EffectParameterCollection.SaveDataForRecreation(), and Microsoft.Xna.Framework.Graphics.EffectParameter.savedValue.