Terraria: Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector4Array
GetValueVector4Array()
unsafe Vector4[] Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector4Array (int count) inline
Definition at line 2161 of file EffectParameter.cs.
    {
        //Discarded unreachable code: IL_00d8
        if (count <= 0)
        {
            throw new ArgumentOutOfRangeException();
        }
        ID3DXBaseEffect* ptr = pEffect;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DXPARAMETER_DESC d3DXPARAMETER_DESC);
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, sbyte*, _D3DXPARAMETER_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 16)))((nint)ptr, _handle, &d3DXPARAMETER_DESC);
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
        int num2 = System.Runtime.CompilerServices.Unsafe.As<_D3DXPARAMETER_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DXPARAMETER_DESC, 40)) >>> 2;
        int num3 = count * 4;
        int num4 = ((num3 >= num2) ? num2 : num3);
        float[] array;
        if (_paramClass == EffectParameterClass.Matrix)
        {
            array = GetValueSingleArray(num4);
        }
        else
        {
            array = new float[num2];
            fixed (void* ptr2 = &System.Runtime.CompilerServices.Unsafe.As<float, void>(ref array[0]))
            {
                try
                {
                    int num5 = *(int*)pEffect + 132;
                    int num6 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, sbyte*, float*, uint, int>)(int)(*(uint*)num5))((nint)pEffect, _handle, (float*)ptr2, (uint)num4);
                    if (num6 < 0)
                    {
                        throw GraphicsHelpers.GetExceptionFromResult((uint)num6);
                    }
                }
                catch
                {
                    //try-fault
                    ptr2 = null;
                    throw;
                }
            }
        }
        Vector4[] array2 = new Vector4[count];
        fixed (void* value = &System.Runtime.CompilerServices.Unsafe.As<Vector4, void>(ref array2[0]))
        {
            IntPtr destination = new IntPtr(value);
            Marshal.Copy(array, 0, destination, num4);
            return array2;
        }
    }
References Microsoft.Xna.Framework.Graphics.EffectParameter._handle, Microsoft.Xna.Framework.Graphics.EffectParameter._paramClass, System.array, System.Runtime.InteropServices.Marshal.Copy(), System.count, System.destination, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingleArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.pEffect, and System.value.