Terraria: Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingleArray
GetValueSingleArray()
unsafe float[] Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingleArray (int count) inline
Definition at line 1768 of file EffectParameter.cs.
    {
        //Discarded unreachable code: IL_023f
        if (count <= 0)
        {
            throw new ArgumentOutOfRangeException();
        }
        float[] array = new float[count];
        if (_paramClass == EffectParameterClass.Matrix)
        {
            int columns = _columns;
            int val = _rows * columns;
            int count2 = pElementCollection.Count;
            if (count2 == 0)
            {
                Matrix valueMatrix = GetValueMatrix();
                int num = Math.Min(count, val);
                fixed (float* ptr = &System.Runtime.CompilerServices.Unsafe.AsRef<float>(&valueMatrix.M11))
                {
                    try
                    {
                        int num2 = 0;
                        int num3 = 0;
                        int rows = _rows;
                        if (0 < rows)
{
                            while (num2 < num)
{
                                int num4 = 0;
                                int columns2 = _columns;
                                if (0 < columns2)
{
                                    while (num2 < num)
{
                                        array[num2] = *(float*)((ref *(_003F*)((num3 * 4 + num4) * 4)) + (ref *(_003F*)ptr));
                                        num2++;
                                        num4++;
                                        columns2 = _columns;
                                        if (num4 >= columns2)
{
                                            break;
                                        }
                                    }
                                }
                                num3++;
                                rows = _rows;
                                if (num3 >= rows)
{
                                    break;
                                }
                            }
                        }
                    }
                    catch
                    {
                        //try-fault
                        ptr = null;
                        throw;
                    }
                }
            }
            else
            {
                Matrix[] valueMatrixArray = GetValueMatrixArray(count2);
                int num5 = Math.Min(count, count2 * 16);
                fixed (float* ptr2 = &valueMatrixArray[0].M11)
                {
                    try
                    {
                        int num6 = 0;
                        int num7 = 0;
                        if (0 < count2)
{
                            while (num6 < num5)
{
                                int num8 = 0;
                                int rows2 = _rows;
                                if (0 < rows2)
{
                                    while (num6 < num5)
{
                                        int num9 = 0;
                                        int columns3 = _columns;
                                        if (0 < columns3)
{
                                            while (num6 < num5)
{
                                                array[num6] = *(float*)((ref *(_003F*)(((num7 * 4 + num8) * 4 + num9) * 4)) + (ref *(_003F*)ptr2));
                                                num6++;
                                                num9++;
                                                columns3 = _columns;
                                                if (num9 >= columns3)
{
                                                    break;
                                                }
                                            }
                                        }
                                        num8++;
                                        rows2 = _rows;
                                        if (num8 >= rows2)
{
                                            break;
                                        }
                                    }
                                }
                                num7++;
                                if (num7 >= count2)
{
                                    break;
                                }
                            }
                        }
                    }
                    catch
                    {
                        //try-fault
                        ptr2 = null;
                        throw;
                    }
                }
            }
        }
        else
        {
            ID3DXBaseEffect* ptr3 = pEffect;
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DXPARAMETER_DESC d3DXPARAMETER_DESC);
            int num10 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, sbyte*, _D3DXPARAMETER_DESC*, int>)(int)(*(uint*)(*(int*)ptr3 + 16)))((nint)ptr3, _handle, &d3DXPARAMETER_DESC);
            if (num10 < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num10);
            }
            int num11 = System.Runtime.CompilerServices.Unsafe.As<_D3DXPARAMETER_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DXPARAMETER_DESC, 40)) >>> 2;
            fixed (void* ptr4 = &System.Runtime.CompilerServices.Unsafe.As<float, void>(ref (new float[num11])[0]))
            {
                try
                {
                    int num12 = ((count >= num11) ? num11 : count);
                    int num13 = *(int*)pEffect + 132;
                    int num14 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, sbyte*, float*, uint, int>)(int)(*(uint*)num13))((nint)pEffect, _handle, (float*)ptr4, (uint)num12);
                    if (num14 < 0)
                    {
                        throw GraphicsHelpers.GetExceptionFromResult((uint)num14);
                    }
                    IntPtr source = new IntPtr(ptr4);
                    Marshal.Copy(source, array, 0, num12);
                }
                catch
                {
                    //try-fault
                    ptr4 = null;
                    throw;
                }
            }
        }
        return array;
    }
References Microsoft.Xna.Framework.Graphics.EffectParameter._columns, Microsoft.Xna.Framework.Graphics.EffectParameter._handle, Microsoft.Xna.Framework.Graphics.EffectParameter._paramClass, Microsoft.Xna.Framework.Graphics.EffectParameter._rows, System.array, System.Runtime.InteropServices.Marshal.Copy(), Microsoft.Xna.Framework.Graphics.EffectParameterCollection.Count, System.count, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrix(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrixArray(), Microsoft.Xna.Framework.Matrix.M11, System.Math.Min(), Microsoft.Xna.Framework.Graphics.EffectParameter.pEffect, Microsoft.Xna.Framework.Graphics.EffectParameter.pElementCollection, and System.source.
Referenced by Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueQuaternionArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector2Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector3Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueVector4Array(), and Microsoft.Xna.Framework.Graphics.EffectParameter.SaveDataForRecreation().