Terraria: Microsoft.Xna.Framework.Graphics.EffectParameter.UpdateHandle
UpdateHandle()
unsafe void Microsoft.Xna.Framework.Graphics.EffectParameter.UpdateHandle (ID3DXBaseEffect * parent, sbyte * handle) inline package
Definition at line 84 of file EffectParameter.cs.
    {
        pEffect = parent;
        _handle = handle;
        pAnnotations.UpdateParent(parent, handle);
        pParamCollection.UpdateParent(parent, handle, arrayElements: false);
        pElementCollection.UpdateParent(parent, handle, arrayElements: true);
        SetLastValue();
    }
References Microsoft.Xna.Framework.Graphics.EffectParameter._handle, System.handle, Microsoft.Xna.Framework.Graphics.EffectParameter.pAnnotations, Microsoft.Xna.Framework.Graphics.EffectParameter.pEffect, Microsoft.Xna.Framework.Graphics.EffectParameter.pElementCollection, Microsoft.Xna.Framework.Graphics.EffectParameter.pParamCollection, Microsoft.Xna.Framework.Graphics.EffectParameter.SetLastValue(), Microsoft.Xna.Framework.Graphics.EffectAnnotationCollection.UpdateParent(), and Microsoft.Xna.Framework.Graphics.EffectParameterCollection.UpdateParent().