Terraria: Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrixArray
GetValueMatrixArray()
unsafe Matrix[] Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueMatrixArray (int count) inline
Definition at line 2359 of file EffectParameter.cs.
    {
        if (count <= 0)
        {
            throw new ArgumentOutOfRangeException();
        }
        if (_paramClass == EffectParameterClass.Matrix && pElementCollection.Count != 0)
        {
            int num = pElementCollection.Count * 16;
            float[] array = new float[num];
            fixed (void* ptr = &System.Runtime.CompilerServices.Unsafe.As<float, void>(ref array[0]))
            {
                int num2 = count * 16;
                int num3 = ((num2 >= num) ? num : num2);
                int num4 = *(int*)pEffect + 164;
                int num5 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, sbyte*, D3DXMATRIX*, uint, int>)(int)(*(uint*)num4))((nint)pEffect, _handle, (D3DXMATRIX*)ptr, (uint)((num3 + 15) / 16));
                if (num5 < 0)
                {
                    throw GraphicsHelpers.GetExceptionFromResult((uint)num5);
                }
                Matrix[] array2 = new Matrix[count];
                fixed (void* value = &System.Runtime.CompilerServices.Unsafe.As<Matrix, void>(ref array2[0]))
                {
                    IntPtr destination = new IntPtr(value);
                    Marshal.Copy(array, 0, destination, num3);
                    return array2;
                }
            }
        }
        throw new InvalidCastException();
    }
References Microsoft.Xna.Framework.Graphics.EffectParameter._handle, Microsoft.Xna.Framework.Graphics.EffectParameter._paramClass, System.array, System.Runtime.InteropServices.Marshal.Copy(), Microsoft.Xna.Framework.Graphics.EffectParameterCollection.Count, System.count, System.destination, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.EffectParameter.pEffect, Microsoft.Xna.Framework.Graphics.EffectParameter.pElementCollection, and System.value.
Referenced by Microsoft.Xna.Framework.Graphics.SkinnedEffect.GetBoneTransforms(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueBooleanArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueInt32Array(), Microsoft.Xna.Framework.Graphics.EffectParameter.GetValueSingleArray(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), and Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue().