Terraria: Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue
SetValue() [12/18]
unsafe void Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue (Texture value) inline
Definition at line 149 of file EffectParameter.cs.
    {
        IDirect3DBaseTexture9* ptr = null;
        if (value != null)
        {
            ptr = (IDirect3DBaseTexture9*)value.pStateTracker;
            IntPtr pComPtr = (IntPtr)ptr;
            Helpers.CheckDisposed(value, pComPtr);
            if (value.isActiveRenderTarget)
            {
                throw new InvalidOperationException(FrameworkResources.MustResolveRenderTarget);
            }
        }
        EffectParameterType paramType = _paramType;
        if (paramType != EffectParameterType.Texture && paramType != EffectParameterType.Texture1D && paramType != EffectParameterType.Texture2D && paramType != EffectParameterType.Texture3D && paramType != EffectParameterType.TextureCube)
        {
            throw new InvalidCastException();
        }
        ID3DXBaseEffect* ptr2 = pEffect;
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, sbyte*, IDirect3DBaseTexture9*, int>)(int)(*(uint*)(*(int*)ptr2 + 208)))((nint)ptr2, _handle, ptr);
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
        savedValue = value;
    }
References Microsoft.Xna.Framework.Graphics.EffectParameter._handle, Microsoft.Xna.Framework.Graphics.EffectParameter._paramType, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.FrameworkResources.MustResolveRenderTarget, Microsoft.Xna.Framework.Graphics.EffectParameter.pEffect, Microsoft.Xna.Framework.Graphics.EffectParameter.savedValue, and System.value.
Referenced by Microsoft.Xna.Framework.Graphics.AlphaTestEffect.OnApply(), Microsoft.Xna.Framework.Graphics.BasicEffect.OnApply(), Microsoft.Xna.Framework.Graphics.DualTextureEffect.OnApply(), Microsoft.Xna.Framework.Graphics.EnvironmentMapEffect.OnApply(), Microsoft.Xna.Framework.Graphics.SkinnedEffect.OnApply(), Microsoft.Xna.Framework.Graphics.SkinnedEffect.SetBoneTransforms(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetFogVector(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetLastValue(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetLightingMatrices(), Microsoft.Xna.Framework.Graphics.EffectHelpers.SetMaterialColor(), Microsoft.Xna.Framework.Graphics.SpriteBatch.SetRenderState(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), and Microsoft.Xna.Framework.Graphics.EffectHelpers.SetWorldViewProjAndFog().