Terraria: System.Xml.Xsl.XPath.XPathParser.ParseFunctionCall
ParseFunctionCall()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParseFunctionCall () inline private
Definition at line 410 of file XPathParser.cs.
    {
        List<Node> list = new List<Node>();
        string name = _scanner.Name;
        string prefix = _scanner.Prefix;
        int lexStart = _scanner.LexStart;
        _scanner.PassToken(LexKind.Name);
        _scanner.PassToken(LexKind.LParens);
        if (_scanner.Kind != LexKind.RParens)
        {
            while (true)
            {
                list.Add(ParseExpr());
                if (_scanner.Kind != LexKind.Comma)
                {
                    break;
                }
                _scanner.NextLex();
            }
            _scanner.CheckToken(LexKind.RParens);
        }
        _scanner.NextLex();
        PushPosInfo(lexStart, _scanner.PrevLexEnd);
        Node result = _builder.Function(prefix, name, list);
        PopPosInfo();
        return result;
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.XPath.XPathScanner.CheckToken(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathScanner.Kind, System.Xml.Xsl.XPath.XPathScanner.LexStart, System.list, System.Xml.Xsl.XPath.XPathScanner.Name, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.ParseExpr(), System.Xml.Xsl.XPath.XPathScanner.PassToken(), System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo(), System.prefix, System.Xml.Xsl.XPath.XPathScanner.Prefix, System.Xml.Xsl.XPath.XPathScanner.PrevLexEnd, and System.Xml.Xsl.XPath.XPathParser< Node >.PushPosInfo().
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParsePrimaryExpr().