Terraria: System.Xml.Xsl.XPath.XPathParser.ParseStep
ParseStep()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParseStep () inline private
Definition at line 102 of file XPathParser.cs.
    {
        Node val;
        if (LexKind.Dot == _scanner.Kind)
        {
            _scanner.NextLex();
            val = _builder.Axis(XPathAxis.Self, XPathNodeType.All, null, null);
            if (LexKind.LBracket == _scanner.Kind)
            {
                throw _scanner.CreateException(System.SR.XPath_PredicateAfterDot);
            }
        }
        else if (LexKind.DotDot == _scanner.Kind)
        {
            _scanner.NextLex();
            val = _builder.Axis(XPathAxis.Parent, XPathNodeType.All, null, null);
            if (LexKind.LBracket == _scanner.Kind)
            {
                throw _scanner.CreateException(System.SR.XPath_PredicateAfterDotDot);
            }
        }
        else
        {
            XPathAxis axis;
            switch (_scanner.Kind)
            {
            case LexKind.Axis:
                axis = _scanner.Axis;
                _scanner.NextLex();
                _scanner.NextLex();
                break;
            case LexKind.At:
                axis = XPathAxis.Attribute;
                _scanner.NextLex();
                break;
            case LexKind.Name:
            case LexKind.Star:
                axis = XPathAxis.Child;
                break;
            default:
                throw _scanner.CreateException(System.SR.XPath_UnexpectedToken, _scanner.RawValue);
            }
            val = ParseNodeTest(axis);
            while (LexKind.LBracket == _scanner.Kind)
            {
                val = _builder.Predicate(val, ParsePredicate(), IsReverseAxis(axis));
            }
        }
        return val;
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Xml.Xsl.XPath.XPathScanner.Axis, System.Xml.Xsl.XPath.XPathScanner.CreateException(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathParser< Node >.IsReverseAxis(), System.Xml.Xsl.XPath.XPathScanner.Kind, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.ParseNodeTest(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePredicate(), System.Xml.Xsl.XPath.XPathScanner.RawValue, System.SR.XPath_PredicateAfterDot, System.SR.XPath_PredicateAfterDotDot, and System.SR.XPath_UnexpectedToken.
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParseRelativeLocationPath().