Terraria: System.Xml.Xsl.XPath.XPathParser.ParseFilterExpr
ParseFilterExpr()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParseFilterExpr () inline private
Definition at line 347 of file XPathParser.cs.
    {
        int lexStart = _scanner.LexStart;
        Node val = ParsePrimaryExpr();
        int prevLexEnd = _scanner.PrevLexEnd;
        while (_scanner.Kind == LexKind.LBracket)
        {
            PushPosInfo(lexStart, prevLexEnd);
            val = _builder.Predicate(val, ParsePredicate(), reverseStep: false);
            PopPosInfo();
        }
        return val;
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Xml.Xsl.XPath.XPathScanner.Kind, System.Xml.Xsl.XPath.XPathScanner.LexStart, System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.ParsePredicate(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePrimaryExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo(), System.Xml.Xsl.XPath.XPathScanner.PrevLexEnd, and System.Xml.Xsl.XPath.XPathParser< Node >.PushPosInfo().
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParsePathExpr().