Terraria: System.Xml.Xsl.XPath.XPathParser.ParseSubExpr
ParseSubExpr()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParseSubExpr (int callerPrec) inline private
Definition at line 266 of file XPathParser.cs.
    {
        if (++_parseSubExprDepth > 1024 && System.LocalAppContextSwitches.LimitXPathComplexity)
        {
            throw _scanner.CreateException(System.SR.Xslt_InputTooComplex);
        }
        Node val;
        if (_scanner.Kind == LexKind.Minus)
        {
            XPathOperator xPathOperator = XPathOperator.UnaryMinus;
            int callerPrec2 = s_XPathOperatorPrecedence[(int)xPathOperator];
            _scanner.NextLex();
            val = _builder.Operator(xPathOperator, ParseSubExpr(callerPrec2), default(Node));
        }
        else
        {
            val = ParseUnionExpr();
        }
        while (true)
        {
            XPathOperator xPathOperator = (XPathOperator)((_scanner.Kind <= LexKind.Union) ? _scanner.Kind : LexKind.Unknown);
            int num = s_XPathOperatorPrecedence[(int)xPathOperator];
            if (num <= callerPrec)
            {
                break;
            }
            _scanner.NextLex();
            val = _builder.Operator(xPathOperator, val, ParseSubExpr(num));
        }
        _parseSubExprDepth--;
        return val;
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._parseSubExprDepth, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Xml.Xsl.XPath.XPathScanner.CreateException(), System.Xml.Dictionary, System.Xml.Xsl.XPath.XPathScanner.Kind, System.LocalAppContextSwitches.LimitXPathComplexity, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.ParseSubExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseUnionExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.s_XPathOperatorPrecedence, and System.SR.Xslt_InputTooComplex.
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParseExpr(), and System.Xml.Xsl.XPath.XPathParser< Node >.ParseSubExpr().