Terraria: System.Xml.Xsl.XPath.XPathParser.ParsePathExpr
ParsePathExpr()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParsePathExpr () inline private
Definition at line 321 of file XPathParser.cs.
    {
        if (IsPrimaryExpr())
        {
            int lexStart = _scanner.LexStart;
            Node val = ParseFilterExpr();
            int prevLexEnd = _scanner.PrevLexEnd;
            if (_scanner.Kind == LexKind.Slash)
            {
                _scanner.NextLex();
                PushPosInfo(lexStart, prevLexEnd);
                val = _builder.JoinStep(val, ParseRelativeLocationPath());
                PopPosInfo();
            }
            else if (_scanner.Kind == LexKind.SlashSlash)
            {
                _scanner.NextLex();
                PushPosInfo(lexStart, prevLexEnd);
                val = _builder.JoinStep(val, _builder.JoinStep(_builder.Axis(XPathAxis.DescendantOrSelf, XPathNodeType.All, null, null), ParseRelativeLocationPath()));
                PopPosInfo();
            }
            return val;
        }
        return ParseLocationPath();
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Xml.Xsl.XPath.XPathParser< Node >.IsPrimaryExpr(), System.Xml.Xsl.XPath.XPathScanner.Kind, System.Xml.Xsl.XPath.XPathScanner.LexStart, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.ParseFilterExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseLocationPath(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseRelativeLocationPath(), System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo(), System.Xml.Xsl.XPath.XPathScanner.PrevLexEnd, and System.Xml.Xsl.XPath.XPathParser< Node >.PushPosInfo().
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParseUnionExpr().