Terraria: System.Xml.Xsl.XPath.XPathParser.ParseExpr
ParseExpr()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParseExpr () inline private
Definition at line 261 of file XPathParser.cs.
    {
        return ParseSubExpr(0);
    }
References System.Xml.Xsl.XPath.XPathParser< Node >.ParseSubExpr().
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.Parse(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseFunctionCall(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePredicate(), and System.Xml.Xsl.XPath.XPathParser< Node >.ParsePrimaryExpr().