Terraria: System.Xml.Xsl.XPath.XPathParser.ParseUnionExpr
ParseUnionExpr()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParseUnionExpr () inline private
Definition at line 299 of file XPathParser.cs.
    {
        int lexStart = _scanner.LexStart;
        Node val = ParsePathExpr();
        if (_scanner.Kind == LexKind.Union)
        {
            PushPosInfo(lexStart, _scanner.PrevLexEnd);
            val = _builder.Operator(XPathOperator.Union, default(Node), val);
            PopPosInfo();
            while (_scanner.Kind == LexKind.Union)
            {
                _scanner.NextLex();
                lexStart = _scanner.LexStart;
                Node right = ParsePathExpr();
                PushPosInfo(lexStart, _scanner.PrevLexEnd);
                val = _builder.Operator(XPathOperator.Union, val, right);
                PopPosInfo();
            }
        }
        return val;
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Xml.Xsl.XPath.XPathScanner.Kind, System.Xml.Xsl.XPath.XPathScanner.LexStart, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.ParsePathExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo(), System.Xml.Xsl.XPath.XPathScanner.PrevLexEnd, and System.Xml.Xsl.XPath.XPathParser< Node >.PushPosInfo().
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParseSubExpr().