Terraria: System.Xml.Xsl.XPath.XPathParser.PopPosInfo
PopPosInfo() [1/2]
void System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo () inline private
Definition at line 444 of file XPathParser.cs.
    {
        _posInfo.Pop();
        _posInfo.Pop();
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._posInfo, and System.Collections.Generic.Stack< T >.Pop().
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.Parse(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseFilterExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseFunctionCall(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseNodeTest(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePathExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.ParsePrimaryExpr(), and System.Xml.Xsl.XPath.XPathParser< Node >.ParseUnionExpr().