Terraria: System.Xml.Xsl.XPath.XPathParser.Parse
Parse()
Node System.Xml.Xsl.XPath.XPathParser< Node >.Parse (XPathScanner scanner, IXPathBuilder< Node > builder, LexKind endLex) inline
Definition at line 24 of file XPathParser.cs.
    {
        Node result = default(Node);
        _scanner = scanner;
        _builder = builder;
        _posInfo.Clear();
        try
        {
            builder.StartBuild();
            result = ParseExpr();
            scanner.CheckToken(endLex);
        }
        catch (XPathCompileException ex)
        {
            if (ex.queryString == null)
            {
                ex.queryString = scanner.Source;
                PopPosInfo(out ex.startChar, out ex.endChar);
            }
            throw;
        }
        finally
        {
            result = builder.EndBuild(result);
        }
        return result;
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._posInfo, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Collections.Generic.Stack< T >.Clear(), System.Xml.Dictionary, System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.ParseExpr(), and System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo().
Referenced by System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.Analyze(), System.Xml.Xsl.Xslt.XslAstAnalyzer.XPathAnalyzer.AnalyzeAvt(), System.Xml.Xsl.Xslt.QilGenerator.CompileKeyUse(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpression(), System.Xml.Xsl.Xslt.QilGenerator.CompileXPathExpressionWithinAvt(), and System.Xml.Xsl.Xslt.XPathPatternParser.ParsePredicate().