Terraria: System.Xml.Xsl.XPath.XPathParser.InternalParseNodeTest
InternalParseNodeTest()
static void System.Xml.Xsl.XPath.XPathParser< Node >.InternalParseNodeTest (XPathScanner scanner, XPathAxis axis, out XPathNodeType nodeType, out string nodePrefix, out string nodeName) inline static package
Definition at line 195 of file XPathParser.cs.
    {
        switch (scanner.Kind)
        {
        case LexKind.Name:
            if (scanner.CanBeFunction && IsNodeType(scanner))
            {
                nodePrefix = null;
                nodeName = null;
                switch (scanner.Name)
                {
                case "comment":
                    nodeType = XPathNodeType.Comment;
                    break;
                case "text":
                    nodeType = XPathNodeType.Text;
                    break;
                case "node":
                    nodeType = XPathNodeType.All;
                    break;
                default:
                    nodeType = XPathNodeType.ProcessingInstruction;
                    break;
                }
                scanner.NextLex();
                scanner.PassToken(LexKind.LParens);
                if (nodeType == XPathNodeType.ProcessingInstruction && scanner.Kind != LexKind.RParens)
                {
                    scanner.CheckToken(LexKind.String);
                    nodePrefix = string.Empty;
                    nodeName = scanner.StringValue;
                    scanner.NextLex();
                }
                scanner.PassToken(LexKind.RParens);
            }
            else
            {
                nodePrefix = scanner.Prefix;
                nodeName = scanner.Name;
                nodeType = PrincipalNodeType(axis);
                scanner.NextLex();
                if (nodeName == "*")
                {
                    nodeName = null;
                }
            }
            break;
        case LexKind.Star:
            nodePrefix = null;
            nodeName = null;
            nodeType = PrincipalNodeType(axis);
            scanner.NextLex();
            break;
        default:
            throw scanner.CreateException(System.SR.XPath_NodeTestExpected, scanner.RawValue);
        }
    }
References System.Xml.Xsl.XPath.XPathParser< Node >.IsNodeType(), System.Xml.Xsl.XPath.XPathParser< Node >.PrincipalNodeType(), and System.SR.XPath_NodeTestExpected.
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParseNodeTest().