Terraria: System.Xml.Xsl.XPath.XPathParser.ParseNodeTest
ParseNodeTest()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParseNodeTest (XPathAxis axis) inline private
Definition at line 162 of file XPathParser.cs.
    {
        int lexStart = _scanner.LexStart;
        InternalParseNodeTest(_scanner, axis, out var nodeType, out var nodePrefix, out var nodeName);
        PushPosInfo(lexStart, _scanner.PrevLexEnd);
        Node result = _builder.Axis(axis, nodeType, nodePrefix, nodeName);
        PopPosInfo();
        return result;
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Xml.Xsl.XPath.XPathParser< Node >.InternalParseNodeTest(), System.Xml.Xsl.XPath.XPathScanner.LexStart, System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo(), System.Xml.Xsl.XPath.XPathScanner.PrevLexEnd, and System.Xml.Xsl.XPath.XPathParser< Node >.PushPosInfo().
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParseStep().