Terraria: System.Xml.Xsl.XPath.XPathParser.ParsePrimaryExpr
ParsePrimaryExpr()
Node System.Xml.Xsl.XPath.XPathParser< Node >.ParsePrimaryExpr () inline private
Definition at line 374 of file XPathParser.cs.
    {
        Node result;
        switch (_scanner.Kind)
        {
        case LexKind.String:
            result = _builder.String(_scanner.StringValue);
            _scanner.NextLex();
            break;
        case LexKind.Number:
            result = _builder.Number(XPathConvert.StringToDouble(_scanner.RawValue));
            _scanner.NextLex();
            break;
        case LexKind.Dollar:
        {
            int lexStart = _scanner.LexStart;
            _scanner.NextLex();
            _scanner.CheckToken(LexKind.Name);
            PushPosInfo(lexStart, _scanner.LexStart + _scanner.LexSize);
            result = _builder.Variable(_scanner.Prefix, _scanner.Name);
            PopPosInfo();
            _scanner.NextLex();
            break;
        }
        case LexKind.LParens:
            _scanner.NextLex();
            result = ParseExpr();
            _scanner.PassToken(LexKind.RParens);
            break;
        default:
            result = ParseFunctionCall();
            break;
        }
        return result;
    }
References System.Xml.Xsl.XPath.XPathParser< Node >._builder, System.Xml.Xsl.XPath.XPathParser< Node >._scanner, System.Xml.Xsl.XPath.XPathScanner.CheckToken(), System.Xml.Xsl.XPath.XPathScanner.Kind, System.Xml.Xsl.XPath.XPathScanner.LexSize, System.Xml.Xsl.XPath.XPathScanner.LexStart, System.Xml.Xsl.XPath.XPathScanner.Name, System.Xml.Xsl.XPath.XPathScanner.NextLex(), System.Xml.Xsl.Node, System.Xml.Xsl.XPath.XPathParser< Node >.ParseExpr(), System.Xml.Xsl.XPath.XPathParser< Node >.ParseFunctionCall(), System.Xml.Xsl.XPath.XPathScanner.PassToken(), System.Xml.Xsl.XPath.XPathParser< Node >.PopPosInfo(), System.Xml.Xsl.XPath.XPathScanner.Prefix, System.Xml.Xsl.XPath.XPathParser< Node >.PushPosInfo(), System.Xml.Xsl.XPath.XPathScanner.RawValue, System.Xml.Xsl.XPathConvert.StringToDouble(), and System.Xml.Xsl.XPath.XPathScanner.StringValue.
Referenced by System.Xml.Xsl.XPath.XPathParser< Node >.ParseFilterExpr().