Terraria: System.Reflection.Metadata.SequencePointCollection.Enumerator.MoveNext
MoveNext()
bool System.Reflection.Metadata.SequencePointCollection.Enumerator.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 32 of file SequencePointCollection.cs.
        {
            if (_reader.RemainingBytes == 0)
            {
                return false;
            }
            DocumentHandle document = _current.Document;
            int offset;
            if (_reader.Offset == 0)
            {
                _reader.ReadCompressedInteger();
                if (document.IsNil)
                {
                    document = ReadDocumentHandle();
                }
                offset = _reader.ReadCompressedInteger();
            }
            else
            {
                int delta;
                while ((delta = _reader.ReadCompressedInteger()) == 0)
                {
                    document = ReadDocumentHandle();
                }
                offset = AddOffsets(_current.Offset, delta);
            }
            ReadDeltaLinesAndColumns(out var deltaLines, out var deltaColumns);
            if (deltaLines == 0 && deltaColumns == 0)
            {
                _current = new SequencePoint(document, offset);
                return true;
            }
            int num;
            ushort num2;
            if (_previousNonHiddenStartLine < 0)
            {
                num = ReadLine();
                num2 = ReadColumn();
            }
            else
            {
                num = AddLines(_previousNonHiddenStartLine, _reader.ReadCompressedSignedInteger());
                num2 = AddColumns(_previousNonHiddenStartColumn, _reader.ReadCompressedSignedInteger());
            }
            _previousNonHiddenStartLine = num;
            _previousNonHiddenStartColumn = num2;
            _current = new SequencePoint(document, offset, num, num2, AddLines(num, deltaLines), AddColumns(num2, deltaColumns));
            return true;
        }
References System.Reflection.Metadata.SequencePointCollection.Enumerator._current, System.Reflection.Metadata.SequencePointCollection.Enumerator._previousNonHiddenStartColumn, System.Reflection.Metadata.SequencePointCollection.Enumerator._previousNonHiddenStartLine, System.Reflection.Metadata.SequencePointCollection.Enumerator._reader, System.Reflection.Metadata.SequencePointCollection.Enumerator.AddColumns(), System.Reflection.Metadata.SequencePointCollection.Enumerator.AddLines(), System.Reflection.Metadata.SequencePointCollection.Enumerator.AddOffsets(), System.Reflection.Metadata.SequencePoint.Document, System.offset, System.Reflection.Metadata.BlobReader.Offset, System.Reflection.Metadata.SequencePoint.Offset, System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadColumn(), System.Reflection.Metadata.BlobReader.ReadCompressedInteger(), System.Reflection.Metadata.BlobReader.ReadCompressedSignedInteger(), System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadDeltaLinesAndColumns(), System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadDocumentHandle(), System.Reflection.Metadata.SequencePointCollection.Enumerator.ReadLine(), and System.Reflection.Metadata.BlobReader.RemainingBytes.