Terraria: System.Reflection.PortableExecutable.PEBuilder.PEBuilder
PEBuilder()
System.Reflection.PortableExecutable.PEBuilder.PEBuilder (PEHeaderBuilder header, Func< IEnumerable< Blob >, BlobContentId >? deterministicIdProvider) inline protected
Definition at line 83 of file PEBuilder.cs.
    {
        if (header == null)
        {
            Throw.ArgumentNull("header");
        }
        IdProvider = deterministicIdProvider ?? BlobContentId.GetTimeBasedProvider();
        IsDeterministic = deterministicIdProvider != null;
        Header = header;
        _lazySections = new Lazy<ImmutableArray<Section>>(CreateSections);
    }
References System.Reflection.PortableExecutable.PEBuilder._lazySections, System.Reflection.Throw.ArgumentNull(), System.Reflection.PortableExecutable.PEBuilder.CreateSections(), System.Reflection.Metadata.BlobContentId.GetTimeBasedProvider(), System.Reflection.PortableExecutable.PEBuilder.Header, System.Reflection.PortableExecutable.PEBuilder.IdProvider, and System.Reflection.PortableExecutable.PEBuilder.IsDeterministic.