Terraria: System.Reflection.PortableExecutable.PEBuilder.GetContentToSign
GetContentToSign()
static IEnumerable< Blob > System.Reflection.PortableExecutable.PEBuilder.GetContentToSign (BlobBuilder peImage, int peHeadersSize, int peHeaderAlignment, Blob strongNameSignatureFixup) inline static package inherited
Definition at line 319 of file PEBuilder.cs.
    {
        int remainingHeaderToSign = peHeadersSize;
        int remainingHeader = BitArithmetic.Align(peHeadersSize, peHeaderAlignment);
        foreach (Blob blob in peImage.GetBlobs())
        {
            int blobStart = blob.Start;
            int blobLength = blob.Length;
            while (blobLength > 0)
            {
                if (remainingHeader > 0)
                {
                    int length;
                    if (remainingHeaderToSign > 0)
                    {
                        length = Math.Min(remainingHeaderToSign, blobLength);
                        yield return new Blob(blob.Buffer, blobStart, length);
                        remainingHeaderToSign -= length;
                    }
                    else
                    {
                        length = Math.Min(remainingHeader, blobLength);
                    }
                    remainingHeader -= length;
                    blobStart += length;
                    blobLength -= length;
                    continue;
                }
                if (blob.Buffer == strongNameSignatureFixup.Buffer)
                {
                    yield return GetPrefixBlob(new Blob(blob.Buffer, blobStart, blobLength), strongNameSignatureFixup);
                    yield return GetSuffixBlob(new Blob(blob.Buffer, blobStart, blobLength), strongNameSignatureFixup);
                }
                else
                {
                    yield return new Blob(blob.Buffer, blobStart, blobLength);
                }
                break;
            }
        }
    }
References System.Reflection.Internal.BitArithmetic.Align(), System.Reflection.Metadata.Blob, System.Reflection.Metadata.Blob.Buffer, System.Reflection.PortableExecutable.PEBuilder.GetPrefixBlob(), System.Reflection.PortableExecutable.PEBuilder.GetSuffixBlob(), System.length, System.Reflection.Metadata.Blob.Length, System.Math.Min(), and System.Reflection.Metadata.Blob.Start.
Referenced by System.Reflection.PortableExecutable.PEBuilder.Sign().