Terraria: System.Reflection.PortableExecutable.PEBuilder.SerializeSections
SerializeSections()
ImmutableArray< SerializedSection > System.Reflection.PortableExecutable.PEBuilder.SerializeSections () inline private inherited
Definition at line 131 of file PEBuilder.cs.
    {
        ImmutableArray<Section> sections = GetSections();
        ImmutableArray<SerializedSection>.Builder builder = ImmutableArray.CreateBuilder<SerializedSection>(sections.Length);
        int position = Header.ComputeSizeOfPEHeaders(sections.Length);
        int relativeVirtualAddress = BitArithmetic.Align(position, Header.SectionAlignment);
        int pointerToRawData = BitArithmetic.Align(position, Header.FileAlignment);
        ImmutableArray<Section>.Enumerator enumerator = sections.GetEnumerator();
        while (enumerator.MoveNext())
        {
            Section current = enumerator.Current;
            BlobBuilder blobBuilder = SerializeSection(current.Name, new SectionLocation(relativeVirtualAddress, pointerToRawData));
            SerializedSection item = new SerializedSection(blobBuilder, current.Name, current.Characteristics, relativeVirtualAddress, BitArithmetic.Align(blobBuilder.Count, Header.FileAlignment), pointerToRawData);
            builder.Add(item);
            relativeVirtualAddress = BitArithmetic.Align(item.RelativeVirtualAddress + item.VirtualSize, Header.SectionAlignment);
            pointerToRawData = item.PointerToRawData + item.SizeOfRawData;
        }
        return builder.MoveToImmutable();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Internal.BitArithmetic.Align(), System.Reflection.PortableExecutable.PEBuilder.Section.Characteristics, System.Reflection.PortableExecutable.PEHeaderBuilder.ComputeSizeOfPEHeaders(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Reflection.PortableExecutable.PEHeaderBuilder.FileAlignment, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Reflection.PortableExecutable.PEBuilder.GetSections(), System.Reflection.PortableExecutable.PEBuilder.Header, System.item, System.Reflection.PortableExecutable.PEBuilder.Section.Name, System.Reflection.PortableExecutable.PEHeaderBuilder.SectionAlignment, and System.Reflection.PortableExecutable.PEBuilder.SerializeSection().
Referenced by System.Reflection.PortableExecutable.PEBuilder.Serialize().