Terraria: System.Reflection.PortableExecutable.PEBuilder.GetContentToChecksum
GetContentToChecksum()
static IEnumerable< Blob > System.Reflection.PortableExecutable.PEBuilder.GetContentToChecksum (BlobBuilder peImage, Blob checksumFixup) inline static package inherited
Definition at line 371 of file PEBuilder.cs.
    {
        foreach (Blob blob in peImage.GetBlobs())
        {
            if (blob.Buffer == checksumFixup.Buffer)
            {
                yield return GetPrefixBlob(blob, checksumFixup);
                yield return GetSuffixBlob(blob, checksumFixup);
            }
            else
            {
                yield return blob;
            }
        }
    }
References System.Reflection.Metadata.Blob.Buffer, System.Reflection.PortableExecutable.PEBuilder.GetPrefixBlob(), and System.Reflection.PortableExecutable.PEBuilder.GetSuffixBlob().
Referenced by System.Reflection.PortableExecutable.PEBuilder.CalculateChecksum().