Terraria: System.Reflection.PortableExecutable.PEBuilder.CalculateChecksum
CalculateChecksum() [1/2]
static uint System.Reflection.PortableExecutable.PEBuilder.CalculateChecksum (BlobBuilder peImage, Blob checksumFixup) inline static package inherited
Definition at line 400 of file PEBuilder.cs.
    {
        return CalculateChecksum(GetContentToChecksum(peImage, checksumFixup)) + (uint)peImage.Count;
    }
References System.Reflection.PortableExecutable.PEBuilder.CalculateChecksum(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Reflection.PortableExecutable.PEBuilder.GetContentToChecksum().
Referenced by System.Reflection.PortableExecutable.PEBuilder.CalculateChecksum(), and System.Reflection.PortableExecutable.PEBuilder.Sign().