Terraria: System.Reflection.PortableExecutable.PEBuilder.WritePEHeader
WritePEHeader()
void System.Reflection.PortableExecutable.PEBuilder.WritePEHeader (BlobBuilder builder, PEDirectoriesBuilder directories, ImmutableArray< SerializedSection > sections) inline private inherited
Definition at line 168 of file PEBuilder.cs.
    {
        builder.WriteUInt16((ushort)(Header.Is32Bit ? 267 : 523));
        builder.WriteByte(Header.MajorLinkerVersion);
        builder.WriteByte(Header.MinorLinkerVersion);
        builder.WriteUInt32((uint)SumRawDataSizes(sections, SectionCharacteristics.ContainsCode));
        builder.WriteUInt32((uint)SumRawDataSizes(sections, SectionCharacteristics.ContainsInitializedData));
        builder.WriteUInt32((uint)SumRawDataSizes(sections, SectionCharacteristics.ContainsUninitializedData));
        builder.WriteUInt32((uint)directories.AddressOfEntryPoint);
        int num = IndexOfSection(sections, SectionCharacteristics.ContainsCode);
        builder.WriteUInt32((num != -1) ? ((uint)sections[num].RelativeVirtualAddress) : 0u);
        if (Header.Is32Bit)
        {
            int num2 = IndexOfSection(sections, SectionCharacteristics.ContainsInitializedData);
            builder.WriteUInt32((num2 != -1) ? ((uint)sections[num2].RelativeVirtualAddress) : 0u);
            builder.WriteUInt32((uint)Header.ImageBase);
        }
        else
        {
            builder.WriteUInt64(Header.ImageBase);
        }
        builder.WriteUInt32((uint)Header.SectionAlignment);
        builder.WriteUInt32((uint)Header.FileAlignment);
        builder.WriteUInt16(Header.MajorOperatingSystemVersion);
        builder.WriteUInt16(Header.MinorOperatingSystemVersion);
        builder.WriteUInt16(Header.MajorImageVersion);
        builder.WriteUInt16(Header.MinorImageVersion);
        builder.WriteUInt16(Header.MajorSubsystemVersion);
        builder.WriteUInt16(Header.MinorSubsystemVersion);
        builder.WriteUInt32(0u);
        SerializedSection serializedSection = sections[sections.Length - 1];
        builder.WriteUInt32((uint)BitArithmetic.Align(serializedSection.RelativeVirtualAddress + serializedSection.VirtualSize, Header.SectionAlignment));
        builder.WriteUInt32((uint)BitArithmetic.Align(Header.ComputeSizeOfPEHeaders(sections.Length), Header.FileAlignment));
        _lazyChecksum = builder.ReserveBytes(4);
        new BlobWriter(_lazyChecksum).WriteUInt32(0u);
        builder.WriteUInt16((ushort)Header.Subsystem);
        builder.WriteUInt16((ushort)Header.DllCharacteristics);
        if (Header.Is32Bit)
        {
            builder.WriteUInt32((uint)Header.SizeOfStackReserve);
            builder.WriteUInt32((uint)Header.SizeOfStackCommit);
            builder.WriteUInt32((uint)Header.SizeOfHeapReserve);
            builder.WriteUInt32((uint)Header.SizeOfHeapCommit);
        }
        else
        {
            builder.WriteUInt64(Header.SizeOfStackReserve);
            builder.WriteUInt64(Header.SizeOfStackCommit);
            builder.WriteUInt64(Header.SizeOfHeapReserve);
            builder.WriteUInt64(Header.SizeOfHeapCommit);
        }
        builder.WriteUInt32(0u);
        builder.WriteUInt32(16u);
        builder.WriteUInt32((uint)directories.ExportTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.ExportTable.Size);
        builder.WriteUInt32((uint)directories.ImportTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.ImportTable.Size);
        builder.WriteUInt32((uint)directories.ResourceTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.ResourceTable.Size);
        builder.WriteUInt32((uint)directories.ExceptionTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.ExceptionTable.Size);
        builder.WriteUInt32(0u);
        builder.WriteUInt32(0u);
        builder.WriteUInt32((uint)directories.BaseRelocationTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.BaseRelocationTable.Size);
        builder.WriteUInt32((uint)directories.DebugTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.DebugTable.Size);
        builder.WriteUInt32((uint)directories.CopyrightTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.CopyrightTable.Size);
        builder.WriteUInt32((uint)directories.GlobalPointerTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.GlobalPointerTable.Size);
        builder.WriteUInt32((uint)directories.ThreadLocalStorageTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.ThreadLocalStorageTable.Size);
        builder.WriteUInt32((uint)directories.LoadConfigTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.LoadConfigTable.Size);
        builder.WriteUInt32((uint)directories.BoundImportTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.BoundImportTable.Size);
        builder.WriteUInt32((uint)directories.ImportAddressTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.ImportAddressTable.Size);
        builder.WriteUInt32((uint)directories.DelayImportTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.DelayImportTable.Size);
        builder.WriteUInt32((uint)directories.CorHeaderTable.RelativeVirtualAddress);
        builder.WriteUInt32((uint)directories.CorHeaderTable.Size);
        builder.WriteUInt64(0uL);
    }
References System.Reflection.PortableExecutable.PEBuilder._lazyChecksum, System.Reflection.Internal.BitArithmetic.Align(), System.Reflection.PortableExecutable.PEHeaderBuilder.ComputeSizeOfPEHeaders(), System.Reflection.PortableExecutable.PEHeaderBuilder.DllCharacteristics, System.Reflection.PortableExecutable.PEHeaderBuilder.FileAlignment, System.Reflection.PortableExecutable.PEBuilder.Header, System.Reflection.PortableExecutable.PEHeaderBuilder.ImageBase, System.Reflection.PortableExecutable.PEBuilder.IndexOfSection(), System.Reflection.PortableExecutable.PEHeaderBuilder.Is32Bit, System.Reflection.PortableExecutable.PEHeaderBuilder.MajorImageVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MajorLinkerVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MajorOperatingSystemVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MajorSubsystemVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MinorImageVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MinorLinkerVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MinorOperatingSystemVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MinorSubsystemVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.SectionAlignment, System.Reflection.PortableExecutable.PEHeaderBuilder.SizeOfHeapCommit, System.Reflection.PortableExecutable.PEHeaderBuilder.SizeOfHeapReserve, System.Reflection.PortableExecutable.PEHeaderBuilder.SizeOfStackCommit, System.Reflection.PortableExecutable.PEHeaderBuilder.SizeOfStackReserve, System.Reflection.PortableExecutable.PEHeaderBuilder.Subsystem, System.Reflection.PortableExecutable.PEBuilder.SumRawDataSizes(), and System.Reflection.Metadata.BlobWriter.WriteUInt32().
Referenced by System.Reflection.PortableExecutable.PEBuilder.Serialize().