Terraria: System.Reflection.PortableExecutable.PEBuilder.WriteSectionHeaders
WriteSectionHeaders()
void System.Reflection.PortableExecutable.PEBuilder.WriteSectionHeaders (BlobBuilder builder, ImmutableArray< SerializedSection > serializedSections) inline private inherited
Definition at line 254 of file PEBuilder.cs.
    {
        ImmutableArray<SerializedSection>.Enumerator enumerator = serializedSections.GetEnumerator();
        while (enumerator.MoveNext())
        {
            SerializedSection current = enumerator.Current;
            WriteSectionHeader(builder, current);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), and System.Reflection.PortableExecutable.PEBuilder.WriteSectionHeader().
Referenced by System.Reflection.PortableExecutable.PEBuilder.Serialize().