Terraria: Terraria.GameContent.UI.Elements.UIHorizontalSeparator.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIHorizontalSeparator.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 31 of file UIHorizontalSeparator.cs.
    {
        CalculatedStyle dimensions = GetDimensions();
        Utils.DrawPanel(_texture.Value, EdgeWidth, 0, spriteBatch, dimensions.Position(), dimensions.Width, Color);
    }
References Terraria.GameContent.UI.Elements.UIHorizontalSeparator._texture, Terraria.Utils.DrawPanel(), Terraria.GameContent.UI.Elements.UIHorizontalSeparator.EdgeWidth, Terraria.UI.UIElement.GetDimensions(), Terraria.UI.CalculatedStyle.Position(), ReLogic.Content.Asset< T >.Value, and Terraria.UI.CalculatedStyle.Width.