Terraria: System.Reflection.PortableExecutable.PEBuilder.Serialize
Serialize()
BlobContentId System.Reflection.PortableExecutable.PEBuilder.Serialize (BlobBuilder builder) inline inherited
Definition at line 111 of file PEBuilder.cs.
    {
        ImmutableArray<SerializedSection> immutableArray = SerializeSections();
        PEDirectoriesBuilder directories = GetDirectories();
        WritePESignature(builder);
        WriteCoffHeader(builder, immutableArray, out var stampFixup);
        WritePEHeader(builder, directories, immutableArray);
        WriteSectionHeaders(builder, immutableArray);
        builder.Align(Header.FileAlignment);
        ImmutableArray<SerializedSection>.Enumerator enumerator = immutableArray.GetEnumerator();
        while (enumerator.MoveNext())
        {
            builder.LinkSuffix(enumerator.Current.Builder);
            builder.Align(Header.FileAlignment);
        }
        BlobContentId result = IdProvider(builder.GetBlobs());
        new BlobWriter(stampFixup).WriteUInt32(result.Stamp);
        return result;
    }
References System.Reflection.PortableExecutable.PEHeaderBuilder.FileAlignment, System.Reflection.PortableExecutable.PEBuilder.GetDirectories(), System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Reflection.PortableExecutable.PEBuilder.Header, System.Reflection.PortableExecutable.PEBuilder.IdProvider, System.Reflection.PortableExecutable.PEBuilder.SerializeSections(), System.Reflection.Metadata.BlobContentId.Stamp, System.Reflection.PortableExecutable.PEBuilder.WriteCoffHeader(), System.Reflection.PortableExecutable.PEBuilder.WritePEHeader(), System.Reflection.PortableExecutable.PEBuilder.WritePESignature(), System.Reflection.PortableExecutable.PEBuilder.WriteSectionHeaders(), and System.Reflection.Metadata.BlobWriter.WriteUInt32().