Terraria: System.Reflection.PortableExecutable.PEBuilder.Sign
Sign() [1/2]
void System.Reflection.PortableExecutable.PEBuilder.Sign (BlobBuilder peImage, Blob strongNameSignatureFixup, Func< IEnumerable< Blob >, byte[]> signatureProvider) inline package inherited
Definition at line 387 of file PEBuilder.cs.
    {
        int peHeadersSize = Header.ComputeSizeOfPEHeaders(GetSections().Length);
        byte[] array = signatureProvider(GetContentToSign(peImage, peHeadersSize, Header.FileAlignment, strongNameSignatureFixup));
        if (array == null || array.Length > strongNameSignatureFixup.Length)
        {
            throw new InvalidOperationException(System.SR.SignatureProviderReturnedInvalidSignature);
        }
        new BlobWriter(strongNameSignatureFixup).WriteBytes(array);
        uint value = CalculateChecksum(peImage, _lazyChecksum);
        new BlobWriter(_lazyChecksum).WriteUInt32(value);
    }
References System.Reflection.PortableExecutable.PEBuilder._lazyChecksum, System.array, System.Reflection.PortableExecutable.PEBuilder.CalculateChecksum(), System.Reflection.PortableExecutable.PEHeaderBuilder.ComputeSizeOfPEHeaders(), System.Reflection.PortableExecutable.PEHeaderBuilder.FileAlignment, System.Reflection.PortableExecutable.PEBuilder.GetContentToSign(), System.Reflection.PortableExecutable.PEBuilder.GetSections(), System.Reflection.PortableExecutable.PEBuilder.Header, System.SR.SignatureProviderReturnedInvalidSignature, System.value, System.Reflection.Metadata.BlobWriter.WriteBytes(), and System.Reflection.Metadata.BlobWriter.WriteUInt32().