Terraria: System.Reflection.PortableExecutable.PEBuilder.GetSections
GetSections()
ImmutableArray< Section > System.Reflection.PortableExecutable.PEBuilder.GetSections () inline protected inherited
Definition at line 95 of file PEBuilder.cs.
    {
        ImmutableArray<Section> value = _lazySections.Value;
        if (value.IsDefault)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.MustNotReturnNull, "CreateSections"));
        }
        return value;
    }
References System.Reflection.PortableExecutable.PEBuilder._lazySections, System.SR.Format(), System.SR.MustNotReturnNull, and System.value.
Referenced by System.Reflection.PortableExecutable.PEBuilder.SerializeSections(), and System.Reflection.PortableExecutable.PEBuilder.Sign().