Terraria: System.Collections.Immutable.ImmutableSortedSet.Enumerator.MoveNext
MoveNext()
bool System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 418 of file ImmutableSortedSet.cs.
        {
            ThrowIfDisposed();
            ThrowIfChanged();
            Stack<RefAsValueType<Node>> stack = _stack.Use(ref this);
            if (stack.Count > 0)
            {
                Node node = (_current = stack.Pop().Value);
                PushNext(_reverse ? node.Left : node.Right);
                return true;
            }
            _current = null;
            return false;
        }
References System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator._current, System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator._reverse, System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator._stack, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator.PushNext(), System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator.ThrowIfChanged(), and System.Collections.Immutable.ImmutableSortedSet< T >.Enumerator.ThrowIfDisposed().