Terraria: UICharacterSelect.UpdateFavoritesCache
UpdateFavoritesCache()
bool UICharacterSelect.UpdateFavoritesCache () inline private
     {
         List<PlayerFileData> list = new List<PlayerFileData>(Main.PlayerList);
         list.Sort(delegate(PlayerFileData x, PlayerFileData y)
         {
             if (x.IsFavorite && !y.IsFavorite)
             {
                 return -1;
             }
             if (!x.IsFavorite && y.IsFavorite)
             {
                 return 1;
             }
             return (x.Name.CompareTo(y.Name) != 0) ? x.Name.CompareTo(y.Name) : x.GetFileName().CompareTo(y.GetFileName());
         });
         bool flag = false;
         if (!flag && list.Count != favoritesCache.Count)
         {
             flag = true;
         }
         if (!flag)
         {
             for (int i = 0; i < favoritesCache.Count; i++)
             {
                 Tuple<string, bool> tuple = favoritesCache[i];
                 if (!(list[i].Name == tuple.Item1) || list[i].IsFavorite != tuple.Item2)
                 {
                     flag = true;
                     break;
                 }
             }
         }
         if (flag)
         {
             favoritesCache.Clear();
             foreach (PlayerFileData item in list)
             {
                 favoritesCache.Add(Tuple.Create(item.Name, item.IsFavorite));
             }
             UpdatePlayersList();
         }
         return flag;
     }
References favoritesCache, FileData.GetFileName(), FileData.IsFavorite, FileData.Name, Main.PlayerList, and UpdatePlayersList().
Referenced by Draw().