Terraria: System.ComponentModel.DataAnnotations.RangeAttribute.SetupConversion
SetupConversion()
void System.ComponentModel.DataAnnotations.RangeAttribute.SetupConversion () inline private
Definition at line 101 of file RangeAttribute.cs.
    {
        if (Conversion != null)
        {
            return;
        }
        object minimum = Minimum;
        object maximum = Maximum;
        if (minimum == null || maximum == null)
        {
            throw new InvalidOperationException(System.SR.RangeAttribute_Must_Set_Min_And_Max);
        }
        Type type2 = minimum.GetType();
        if (type2 == typeof(int))
        {
            Initialize((int)minimum, (int)maximum, (object v) => Convert.ToInt32(v, CultureInfo.InvariantCulture));
            return;
        }
        if (type2 == typeof(double))
        {
            Initialize((double)minimum, (double)maximum, (object v) => Convert.ToDouble(v, CultureInfo.InvariantCulture));
            return;
        }
        Type type = OperandType;
        if (type == null)
        {
            throw new InvalidOperationException(System.SR.RangeAttribute_Must_Set_Operand_Type);
        }
        Type typeFromHandle = typeof(IComparable);
        if (!typeFromHandle.IsAssignableFrom(type))
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.RangeAttribute_ArbitraryTypeNotIComparable, type.FullName, typeFromHandle.FullName));
        }
        TypeConverter converter = GetOperandTypeConverter();
        IComparable minimum2 = (IComparable)(ParseLimitsInInvariantCulture ? converter.ConvertFromInvariantString((string)minimum) : converter.ConvertFromString((string)minimum));
        IComparable maximum2 = (IComparable)(ParseLimitsInInvariantCulture ? converter.ConvertFromInvariantString((string)maximum) : converter.ConvertFromString((string)maximum));
        Func<object, object> conversion = ((!ConvertValueInInvariantCulture) ? ((Func<object, object>)((object value) => (!(value.GetType() == type)) ? converter.ConvertFrom(value) : value)) : ((Func<object, object>)((object value) => (!(value.GetType() == type)) ? converter.ConvertFrom(null, CultureInfo.InvariantCulture, value) : value)));
        Initialize(minimum2, maximum2, conversion);
    }
References System.ComponentModel.DataAnnotations.RangeAttribute.Conversion, System.converter, System.ComponentModel.DataAnnotations.RangeAttribute.ConvertValueInInvariantCulture, System.SR.Format(), System.Type.FullName, System.ComponentModel.DataAnnotations.RangeAttribute.GetOperandTypeConverter(), System.ComponentModel.DataAnnotations.RangeAttribute.Initialize(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsAssignableFrom(), System.ComponentModel.DataAnnotations.RangeAttribute.Maximum, System.ComponentModel.DataAnnotations.RangeAttribute.Minimum, System.ComponentModel.DataAnnotations.RangeAttribute.OperandType, System.ComponentModel.DataAnnotations.RangeAttribute.ParseLimitsInInvariantCulture, System.SR.RangeAttribute_ArbitraryTypeNotIComparable, System.SR.RangeAttribute_Must_Set_Min_And_Max, System.SR.RangeAttribute_Must_Set_Operand_Type, System.Convert.ToDouble(), System.Convert.ToInt32(), System.type, and System.value.
Referenced by System.ComponentModel.DataAnnotations.RangeAttribute.FormatErrorMessage(), and System.ComponentModel.DataAnnotations.RangeAttribute.IsValid().