Terraria: UICharacterSelect.Draw
Draw()
override void UICharacterSelect.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from UIElement.
     {
         if (skipDraw)
         {
             skipDraw = false;
             return;
         }
         if (UpdateFavoritesCache())
         {
             skipDraw = true;
             Main.MenuUI.Draw(spriteBatch, new GameTime());
         }
         base.Draw(spriteBatch);
         SetupGamepadPoints(spriteBatch);
     }
References UserInterface.Draw(), Main.MenuUI, SetupGamepadPoints(), skipDraw, and UpdateFavoritesCache().