Terraria: Terraria.Entity.DirectionTo
DirectionTo()
Vector2 Terraria.Entity.DirectionTo (Vector2 Destination) inline inherited
    {
        return Vector2.Normalize(Destination - Center);
    }
References Terraria.Entity.Center.
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_120_HallowBoss_DashTo(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.Damage(), Terraria.GameInput.LockOnHelper.GetClosestTarget(), Terraria.Projectile.HandleMovement(), and Terraria.GameInput.LockOnHelper.RefreshTargets().