Terraria: System.Xml.Xsl.XmlILGenerator.GenerateExecuteFunction
GenerateExecuteFunction()
MethodInfo System.Xml.Xsl.XmlILGenerator.GenerateExecuteFunction (MethodInfo methExec, MethodInfo methRoot) inline private
Definition at line 104 of file XmlILGenerator.cs.
    {
        _helper.MethodBegin(methExec, null, initWriters: false);
        EvaluateGlobalValues(_qil.GlobalVariableList);
        EvaluateGlobalValues(_qil.GlobalParameterList);
        _helper.LoadQueryRuntime();
        _helper.Call(methRoot);
        _helper.MethodEnd();
        return methExec;
    }
References System.Xml.Xsl.XmlILGenerator._helper, System.Xml.Xsl.XmlILGenerator._qil, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Dictionary, System.Xml.Xsl.XmlILGenerator.EvaluateGlobalValues(), System.Xml.Xsl.Qil.QilExpression.GlobalParameterList, System.Xml.Xsl.Qil.QilExpression.GlobalVariableList, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin(), and System.Xml.Xsl.IlGen.GenerateHelper.MethodEnd().
Referenced by System.Xml.Xsl.XmlILGenerator.Generate().