Terraria: System.Xml.Xsl.XmlILGenerator.CreateFunctionMetadata
CreateFunctionMetadata()
void System.Xml.Xsl.XmlILGenerator.CreateFunctionMetadata (IList< QilNode > funcList) inline private
Definition at line 67 of file XmlILGenerator.cs.
    {
        foreach (QilFunction func in funcList)
        {
            Type[] array = new Type[func.Arguments.Count];
            string[] array2 = new string[func.Arguments.Count];
            for (int i = 0; i < func.Arguments.Count; i++)
            {
                QilParameter qilParameter = (QilParameter)func.Arguments[i];
                array[i] = XmlILTypeHelper.GetStorageType(qilParameter.XmlType);
                if (qilParameter.DebugName != null)
                {
                    array2[i] = qilParameter.DebugName;
                }
            }
            Type returnType = ((!XmlILConstructInfo.Read(func).PushToWriterLast) ? XmlILTypeHelper.GetStorageType(func.XmlType) : typeof(void));
            XmlILMethodAttributes xmlAttrs = ((func.SourceLine == null) ? XmlILMethodAttributes.NonUser : XmlILMethodAttributes.None);
            MethodInfo functionBinding = _module.DefineMethod(func.DebugName, returnType, array, array2, xmlAttrs);
            for (int j = 0; j < func.Arguments.Count; j++)
            {
                XmlILAnnotation.Write(func.Arguments[j]).ArgumentPosition = j;
            }
            XmlILAnnotation.Write(func).FunctionBinding = functionBinding;
        }
    }
References System.Xml.Xsl.XmlILGenerator._module, System.array, System.Xml.Xsl.IlGen.XmlILModule.DefineMethod(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.XmlILTypeHelper.GetStorageType(), System.Xml.Xsl.IlGen.XmlILConstructInfo.Read(), and System.Xml.Xsl.IlGen.XmlILAnnotation.Write().
Referenced by System.Xml.Xsl.XmlILGenerator.Generate().