Terraria: System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions
CreateHelperFunctions()
void System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions () inline private
Definition at line 115 of file XmlILGenerator.cs.
    {
        MethodInfo methInfo = _module.DefineMethod("SyncToNavigator", typeof(XPathNavigator), new Type[2]
        {
            typeof(XPathNavigator),
            typeof(XPathNavigator)
        }, new string[2], (XmlILMethodAttributes)3);
        _helper.MethodBegin(methInfo, null, initWriters: false);
        Label label = _helper.DefineLabel();
        _helper.Emit(OpCodes.Ldarg_0);
        _helper.Emit(OpCodes.Brfalse, label);
        _helper.Emit(OpCodes.Ldarg_0);
        _helper.Emit(OpCodes.Ldarg_1);
        _helper.Call(XmlILMethods.NavMoveTo);
        _helper.Emit(OpCodes.Brfalse, label);
        _helper.Emit(OpCodes.Ldarg_0);
        _helper.Emit(OpCodes.Ret);
        _helper.MarkLabel(label);
        _helper.Emit(OpCodes.Ldarg_1);
        _helper.Call(XmlILMethods.NavClone);
        _helper.MethodEnd();
    }
References System.Xml.Xsl.XmlILGenerator._helper, System.Xml.Xsl.XmlILGenerator._module, System.Reflection.Emit.OpCodes.Brfalse, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DefineLabel(), System.Xml.Xsl.IlGen.XmlILModule.DefineMethod(), System.Xml.Dictionary, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Reflection.Emit.OpCodes.Ldarg_0, System.Reflection.Emit.OpCodes.Ldarg_1, System.Xml.Xsl.IlGen.GenerateHelper.MarkLabel(), System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin(), System.Xml.Xsl.IlGen.GenerateHelper.MethodEnd(), System.Xml.Xsl.IlGen.XmlILMethods.NavClone, System.Xml.Xsl.IlGen.XmlILMethods.NavMoveTo, and System.Reflection.Emit.OpCodes.Ret.
Referenced by System.Xml.Xsl.XmlILGenerator.Generate().