Terraria: System.Xml.Xsl.XmlILGenerator.Generate
Generate()
XmlILCommand System.Xml.Xsl.XmlILGenerator.Generate (QilExpression query, TypeBuilder typeBldr) inline
Definition at line 25 of file XmlILGenerator.cs.
    {
        _qil = query;
        bool useLRE = !_qil.IsDebug && typeBldr == null;
        bool isDebug = _qil.IsDebug;
        _optVisitor = new XmlILOptimizerVisitor(_qil, !_qil.IsDebug);
        _qil = _optVisitor.Optimize();
        if (typeBldr != null)
        {
            _module = new XmlILModule(typeBldr);
        }
        else
        {
            _module = new XmlILModule(useLRE, isDebug);
        }
        _helper = new GenerateHelper(_module, _qil.IsDebug);
        CreateHelperFunctions();
        MethodInfo methExec = _module.DefineMethod("Execute", typeof(void), Type.EmptyTypes, Array.Empty<string>(), XmlILMethodAttributes.NonUser);
        XmlILMethodAttributes xmlAttrs = ((_qil.Root.SourceLine == null) ? XmlILMethodAttributes.NonUser : XmlILMethodAttributes.None);
        MethodInfo methRoot = _module.DefineMethod("Root", typeof(void), Type.EmptyTypes, Array.Empty<string>(), xmlAttrs);
        foreach (EarlyBoundInfo earlyBoundType in _qil.EarlyBoundTypes)
        {
            _helper.StaticData.DeclareEarlyBound(earlyBoundType.NamespaceUri, earlyBoundType.EarlyBoundType);
        }
        CreateFunctionMetadata(_qil.FunctionList);
        CreateGlobalValueMetadata(_qil.GlobalVariableList);
        CreateGlobalValueMetadata(_qil.GlobalParameterList);
        GenerateExecuteFunction(methExec, methRoot);
        _xmlIlVisitor = new XmlILVisitor();
        _xmlIlVisitor.Visit(_qil, _helper, methRoot);
        XmlQueryStaticData staticData = new XmlQueryStaticData(_qil.DefaultWriterSettings, _qil.WhitespaceRules, _helper.StaticData);
        if (typeBldr != null)
        {
            CreateTypeInitializer(staticData);
            _module.BakeMethods();
            return null;
        }
        _module.BakeMethods();
        ExecuteDelegate delExec = (ExecuteDelegate)_module.CreateDelegate("Execute", typeof(ExecuteDelegate));
        return new XmlILCommand(delExec, staticData);
    }
References System.Xml.Xsl.XmlILGenerator._helper, System.Xml.Xsl.XmlILGenerator._module, System.Xml.Xsl.XmlILGenerator._optVisitor, System.Xml.Xsl.XmlILGenerator._qil, System.Xml.Xsl.XmlILGenerator._xmlIlVisitor, System.Xml.Xsl.IlGen.XmlILModule.BakeMethods(), System.Xml.Xsl.IlGen.XmlILModule.CreateDelegate(), System.Xml.Xsl.XmlILGenerator.CreateFunctionMetadata(), System.Xml.Xsl.XmlILGenerator.CreateGlobalValueMetadata(), System.Xml.Xsl.XmlILGenerator.CreateHelperFunctions(), System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer(), System.Xml.Xsl.IlGen.StaticDataManager.DeclareEarlyBound(), System.Xml.Xsl.Qil.QilExpression.DefaultWriterSettings, System.Xml.Xsl.IlGen.XmlILModule.DefineMethod(), System.Xml.Dictionary, System.Xml.Xsl.Qil.QilExpression.EarlyBoundTypes, System.Type.EmptyTypes, System.Xml.Xsl.ExecuteDelegate(), System.Xml.Xsl.Qil.QilExpression.FunctionList, System.Xml.Xsl.XmlILGenerator.GenerateExecuteFunction(), System.Xml.Xsl.Qil.QilExpression.GlobalParameterList, System.Xml.Xsl.Qil.QilExpression.GlobalVariableList, System.Xml.Xsl.Qil.QilExpression.IsDebug, System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.Optimize(), System.Xml.Xsl.IlGen.GenerateHelper.StaticData, System.Xml.Xsl.IlGen.XmlILVisitor.Visit(), and System.Xml.Xsl.Qil.QilExpression.WhitespaceRules.
Referenced by System.Xml.Xsl.XslCompiledTransform.CompileQilToMsil().