Terraria: System.Xml.Xsl.XmlILGenerator.EvaluateGlobalValues
EvaluateGlobalValues()
void System.Xml.Xsl.XmlILGenerator.EvaluateGlobalValues (IList< QilNode > iterList) inline private
Definition at line 138 of file XmlILGenerator.cs.
    {
        foreach (QilIterator iter in iterList)
        {
            if (_qil.IsDebug || OptimizerPatterns.Read(iter).MatchesPattern(OptimizerPatternName.MaybeSideEffects))
            {
                MethodInfo functionBinding = XmlILAnnotation.Write(iter).FunctionBinding;
                _helper.LoadQueryRuntime();
                _helper.Call(functionBinding);
                _helper.Emit(OpCodes.Pop);
            }
        }
    }
References System.Xml.Xsl.XmlILGenerator._helper, System.Xml.Xsl.XmlILGenerator._qil, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Xml.Xsl.Qil.QilExpression.IsDebug, System.Xml.Xsl.IlGen.GenerateHelper.LoadQueryRuntime(), System.Reflection.Emit.OpCodes.Pop, System.Xml.Xsl.IlGen.OptimizerPatterns.Read(), and System.Xml.Xsl.IlGen.XmlILAnnotation.Write().
Referenced by System.Xml.Xsl.XmlILGenerator.GenerateExecuteFunction().