Terraria: System.Runtime.InteropServices.ComWrappers.TryGetOrCreateComInterfaceForObjectInternal
TryGetOrCreateComInterfaceForObjectInternal() [1/2]
static bool System.Runtime.InteropServices.ComWrappers.TryGetOrCreateComInterfaceForObjectInternal (ComWrappers impl, object instance, CreateComInterfaceFlags flags, out IntPtr retValue) inline static private
Definition at line 56 of file ComWrappers.cs.
    {
        if (instance == null)
        {
            throw new ArgumentNullException("instance");
        }
        return TryGetOrCreateComInterfaceForObjectInternal(ObjectHandleOnStack.Create(ref impl), impl.id, ObjectHandleOnStack.Create(ref instance), flags, out retValue);
    }
References System.Runtime.InteropServices.ComWrappers.id, and System.Runtime.InteropServices.ComWrappers.TryGetOrCreateComInterfaceForObjectInternal().
Referenced by System.Runtime.InteropServices.ComWrappers.GetOrCreateComInterfaceForObject(), and System.Runtime.InteropServices.ComWrappers.TryGetOrCreateComInterfaceForObjectInternal().