Terraria: System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal
TryGetOrCreateObjectForComInstanceInternal() [1/2]
static bool System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal (ComWrappers impl, IntPtr externalComObject, IntPtr innerMaybe, CreateObjectFlags flags, object wrapperMaybe, out object retValue) inline static private
Definition at line 136 of file ComWrappers.cs.
    {
        if (externalComObject == IntPtr.Zero)
        {
            throw new ArgumentNullException("externalComObject");
        }
        if (innerMaybe != IntPtr.Zero && !flags.HasFlag(CreateObjectFlags.Aggregation))
        {
            throw new InvalidOperationException(SR.InvalidOperation_SuppliedInnerMustBeMarkedAggregation);
        }
        object o = wrapperMaybe;
        retValue = null;
        return TryGetOrCreateObjectForComInstanceInternal(ObjectHandleOnStack.Create(ref impl), impl.id, externalComObject, innerMaybe, flags, ObjectHandleOnStack.Create(ref o), ObjectHandleOnStack.Create(ref retValue));
    }
References System.Runtime.InteropServices.ComWrappers.id, System.SR.InvalidOperation_SuppliedInnerMustBeMarkedAggregation, System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal(), and System.IntPtr.Zero.
Referenced by System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(), System.Runtime.InteropServices.ComWrappers.GetOrRegisterObjectForComInstance(), and System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal().