Terraria: System.Xml.Xsl.XmlILGenerator.CreateGlobalValueMetadata
CreateGlobalValueMetadata()
void System.Xml.Xsl.XmlILGenerator.CreateGlobalValueMetadata (IList< QilNode > globalList) inline private
Definition at line 93 of file XmlILGenerator.cs.
    {
        foreach (QilReference global in globalList)
        {
            Type storageType = XmlILTypeHelper.GetStorageType(global.XmlType);
            XmlILMethodAttributes xmlAttrs = ((global.SourceLine == null) ? XmlILMethodAttributes.NonUser : XmlILMethodAttributes.None);
            MethodInfo functionBinding = _module.DefineMethod(global.DebugName.ToString(), storageType, Type.EmptyTypes, Array.Empty<string>(), xmlAttrs);
            XmlILAnnotation.Write(global).FunctionBinding = functionBinding;
        }
    }
References System.Xml.Xsl.XmlILGenerator._module, System.Xml.Xsl.IlGen.XmlILModule.DefineMethod(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Xsl.IlGen.XmlILTypeHelper.GetStorageType(), and System.Xml.Xsl.IlGen.XmlILAnnotation.Write().
Referenced by System.Xml.Xsl.XmlILGenerator.Generate().