Terraria: System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer
CreateTypeInitializer()
void System.Xml.Xsl.XmlILGenerator.CreateTypeInitializer (XmlQueryStaticData staticData) inline
Definition at line 152 of file XmlILGenerator.cs.
    {
        staticData.GetObjectData(out var data, out var ebTypes);
        FieldInfo fldInfo = _module.DefineInitializedData("__staticData", data);
        FieldInfo fldInfo2 = _module.DefineField("staticData", typeof(object));
        FieldInfo fldInfo3 = _module.DefineField("ebTypes", typeof(Type[]));
        ConstructorInfo methInfo = _module.DefineTypeInitializer();
        _helper.MethodBegin(methInfo, null, initWriters: false);
        _helper.LoadInteger(data.Length);
        _helper.Emit(OpCodes.Newarr, typeof(byte));
        _helper.Emit(OpCodes.Dup);
        _helper.Emit(OpCodes.Ldtoken, fldInfo);
        _helper.Call(XmlILMethods.InitializeArray);
        _helper.Emit(OpCodes.Stsfld, fldInfo2);
        if (ebTypes != null)
        {
            LocalBuilder locBldr = _helper.DeclareLocal("$$$types", typeof(Type[]));
            _helper.LoadInteger(ebTypes.Length);
            _helper.Emit(OpCodes.Newarr, typeof(Type));
            _helper.Emit(OpCodes.Stloc, locBldr);
            for (int i = 0; i < ebTypes.Length; i++)
            {
                _helper.Emit(OpCodes.Ldloc, locBldr);
                _helper.LoadInteger(i);
                _helper.LoadType(ebTypes[i]);
                _helper.Emit(OpCodes.Stelem_Ref);
            }
            _helper.Emit(OpCodes.Ldloc, locBldr);
            _helper.Emit(OpCodes.Stsfld, fldInfo3);
        }
        _helper.MethodEnd();
    }
References System.Xml.Xsl.XmlILGenerator._helper, System.Xml.Xsl.XmlILGenerator._module, System.Xml.Xsl.IlGen.GenerateHelper.Call(), System.Xml.Xsl.IlGen.GenerateHelper.DeclareLocal(), System.Xml.Xsl.IlGen.XmlILModule.DefineField(), System.Xml.Xsl.IlGen.XmlILModule.DefineInitializedData(), System.Xml.Xsl.IlGen.XmlILModule.DefineTypeInitializer(), System.Xml.Dictionary, System.Reflection.Emit.OpCodes.Dup, System.Xml.Xsl.IlGen.GenerateHelper.Emit(), System.Collections.Generic.Dictionary< TKey, TValue >.GetObjectData(), System.Xml.Xsl.IlGen.XmlILMethods.InitializeArray, System.Reflection.Emit.OpCodes.Ldloc, System.Reflection.Emit.OpCodes.Ldtoken, System.Xml.Xsl.IlGen.GenerateHelper.LoadInteger(), System.Xml.Xsl.IlGen.GenerateHelper.LoadType(), System.Xml.Xsl.IlGen.GenerateHelper.MethodBegin(), System.Xml.Xsl.IlGen.GenerateHelper.MethodEnd(), System.Reflection.Emit.OpCodes.Newarr, System.Reflection.Emit.OpCodes.Stelem_Ref, System.Reflection.Emit.OpCodes.Stloc, and System.Reflection.Emit.OpCodes.Stsfld.
Referenced by System.Xml.Xsl.XmlILGenerator.Generate().