Terraria: Microsoft.Xna.Framework.Curve.Evaluate
Evaluate()
float Microsoft.Xna.Framework.Curve.Evaluate (float position) inline
Definition at line 142 of file Curve.cs.
    {
        if (keys.Count == 0)
        {
            return 0f;
        }
        if (keys.Count == 1)
        {
            return keys[0].internalValue;
        }
        CurveKey curveKey = keys[0];
        CurveKey curveKey2 = keys[keys.Count - 1];
        float num = position;
        float num2 = 0f;
        if (num < curveKey.position)
        {
            if (preLoop == CurveLoopType.Constant)
            {
                return curveKey.internalValue;
            }
            if (preLoop == CurveLoopType.Linear)
            {
                return curveKey.internalValue - curveKey.tangentIn * (curveKey.position - num);
            }
            if (!keys.IsCacheAvailable)
            {
                keys.ComputeCacheValues();
            }
            float num3 = CalcCycle(num);
            float num4 = num - (curveKey.position + num3 * keys.TimeRange);
            if (preLoop == CurveLoopType.Cycle)
            {
                num = curveKey.position + num4;
            }
            else if (preLoop == CurveLoopType.CycleOffset)
            {
                num = curveKey.position + num4;
                num2 = (curveKey2.internalValue - curveKey.internalValue) * num3;
            }
            else
            {
                num = ((((uint)(int)num3 & (true ? 1u : 0u)) != 0) ? (curveKey2.position - num4) : (curveKey.position + num4));
            }
        }
        else if (curveKey2.position < num)
        {
            if (postLoop == CurveLoopType.Constant)
            {
                return curveKey2.internalValue;
            }
            if (postLoop == CurveLoopType.Linear)
            {
                return curveKey2.internalValue - curveKey2.tangentOut * (curveKey2.position - num);
            }
            if (!keys.IsCacheAvailable)
            {
                keys.ComputeCacheValues();
            }
            float num5 = CalcCycle(num);
            float num6 = num - (curveKey.position + num5 * keys.TimeRange);
            if (postLoop == CurveLoopType.Cycle)
            {
                num = curveKey.position + num6;
            }
            else if (postLoop == CurveLoopType.CycleOffset)
            {
                num = curveKey.position + num6;
                num2 = (curveKey2.internalValue - curveKey.internalValue) * num5;
            }
            else
            {
                num = ((((uint)(int)num5 & (true ? 1u : 0u)) != 0) ? (curveKey2.position - num6) : (curveKey.position + num6));
            }
        }
        CurveKey k = null;
        CurveKey k2 = null;
        num = FindSegment(num, ref k, ref k2);
        return num2 + Hermite(k, k2, num);
    }
References Microsoft.Xna.Framework.Curve.CalcCycle(), Microsoft.Xna.Framework.CurveKeyCollection.ComputeCacheValues(), Microsoft.Xna.Framework.CurveKeyCollection.Count, Microsoft.Xna.Framework.Curve.FindSegment(), Microsoft.Xna.Framework.Curve.Hermite(), Microsoft.Xna.Framework.CurveKey.internalValue, Microsoft.Xna.Framework.CurveKeyCollection.IsCacheAvailable, Microsoft.Xna.Framework.Curve.keys, Microsoft.Xna.Framework.CurveKey.position, Microsoft.Xna.Framework.Curve.postLoop, Microsoft.Xna.Framework.Curve.preLoop, and Microsoft.Xna.Framework.CurveKeyCollection.TimeRange.