Terraria: System.Diagnostics.DiagnosticListener.SubscribeInternal
SubscribeInternal()
IDisposable System.Diagnostics.DiagnosticListener.SubscribeInternal (IObserver< KeyValuePair< string, object > > observer, Predicate< string > isEnabled1Arg, Func< string, object, object, bool > isEnabled3Arg, Action< Activity, object > onActivityImport, Action< Activity, object > onActivityExport) inline private
Definition at line 264 of file DiagnosticListener.cs.
    {
        if (_disposed)
        {
            return new DiagnosticSubscription
            {
                Owner = this
            };
        }
        DiagnosticSubscription diagnosticSubscription = new DiagnosticSubscription
        {
            Observer = observer,
            IsEnabled1Arg = isEnabled1Arg,
            IsEnabled3Arg = isEnabled3Arg,
            OnActivityImport = onActivityImport,
            OnActivityExport = onActivityExport,
            Owner = this,
            Next = _subscriptions
        };
        while (Interlocked.CompareExchange(ref _subscriptions, diagnosticSubscription, diagnosticSubscription.Next) != diagnosticSubscription.Next)
        {
            diagnosticSubscription.Next = _subscriptions;
        }
        return diagnosticSubscription;
    }
References System.Diagnostics.DiagnosticListener._disposed, System.Diagnostics.DiagnosticListener._subscriptions, System.Threading.Interlocked.CompareExchange(), System.Diagnostics.DiagnosticListener.OnActivityExport(), and System.Diagnostics.DiagnosticListener.OnActivityImport().
Referenced by System.Diagnostics.DiagnosticListener.Subscribe(), System.Diagnostics.DiagnosticListener.Subscribe(), System.Diagnostics.DiagnosticListener.Subscribe(), and System.Diagnostics.DiagnosticListener.Subscribe().