Terraria: Terraria.Social.WeGame.IPCClient.ConnectTo
ConnectTo()
void Terraria.Social.WeGame.IPCClient.ConnectTo (string serverName) inline
Definition at line 63 of file IPCClient.cs.
    {
        if (GetPipeStream() != null)
        {
            return;
        }
        _pipeStream = new NamedPipeClientStream(".", serverName, PipeDirection.InOut, PipeOptions.Asynchronous);
        _cancelTokenSrc = new CancellationTokenSource();
        Task.Factory.StartNew(delegate(object content)
        {
            GetPipeStream().Connect();
            if (!((CancellationToken)content).IsCancellationRequested)
            {
                GetPipeStream().ReadMode = PipeTransmissionMode.Message;
                BeginReadData();
                _connectedFlag = true;
            }
        }, _cancelTokenSrc.Token);
    }
References Terraria.Social.WeGame.IPCBase._cancelTokenSrc, Terraria.Social.WeGame.IPCClient._connectedFlag, Terraria.Social.WeGame.IPCBase._pipeStream, Terraria.Social.WeGame.IPCBase.BeginReadData(), System.IO.Pipes.NamedPipeClientStream.Connect(), System.Threading.Tasks.Task< TResult >.Factory, Terraria.Social.WeGame.IPCClient.GetPipeStream(), System.IO.Pipes.PipeStream.ReadMode, and System.Threading.CancellationTokenSource.Token.
Referenced by Terraria.Social.WeGame.MessageDispatcherClient.Start().