Terraria: Terraria.DataStructures.TileEntity.ByPosition
ByPosition
Dictionary<Point16, TileEntity> Terraria.DataStructures.TileEntity.ByPosition = new Dictionary<Point16, TileEntity>() static inherited
Referenced by Terraria.DataStructures.TileEntity.Clear(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Find(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Find(), Terraria.GameContent.Tile_Entities.TEHatRack.Find(), Terraria.GameContent.Tile_Entities.TEItemFrame.Find(), Terraria.GameContent.Tile_Entities.TELogicSensor.Find(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Find(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Find(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Find(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Kill(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Kill(), Terraria.GameContent.Tile_Entities.TEHatRack.Kill(), Terraria.GameContent.Tile_Entities.TEItemFrame.Kill(), Terraria.GameContent.Tile_Entities.TELogicSensor.Kill(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Kill(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Kill(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Kill(), Terraria.IO.WorldFile.LoadTileEntities(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Place(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Place(), Terraria.GameContent.Tile_Entities.TEHatRack.Place(), Terraria.GameContent.Tile_Entities.TEItemFrame.Place(), Terraria.GameContent.Tile_Entities.TELogicSensor.Place(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Place(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Place(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Place(), Terraria.DataStructures.TileEntity.PlaceEntityNet(), Terraria.GameContent.Tile_Entities.TELogicSensor.UpdateEndInternal(), and Terraria.GameContent.TeleportPylonsSystem.UpdatePylonsListAndBroadcastChanges().