Terraria: Terraria.DataStructures.TileEntity.SetInteractionAnchor
SetInteractionAnchor()
static void Terraria.DataStructures.TileEntity.SetInteractionAnchor (Player player, int x, int y, int id) inline static inherited
Definition at line 209 of file TileEntity.cs.
    {
        player.chest = -1;
        player.SetTalkNPC(-1);
        if (player.whoAmI == Main.myPlayer)
        {
            Main.playerInventory = true;
            Main.recBigList = false;
            Main.CreativeMenu.CloseMenu();
            if (PlayerInput.GrappleAndInteractAreShared)
            {
                PlayerInput.Triggers.JustPressed.Grapple = false;
            }
            if (player.tileEntityAnchor.interactEntityID != -1)
            {
                SoundEngine.PlaySound(12);
            }
            else
            {
                SoundEngine.PlaySound(10);
            }
        }
        player.tileEntityAnchor.Set(id, x, y);
    }
References Terraria.Main.CreativeMenu, Terraria.GameInput.PlayerInput.GrappleAndInteractAreShared, Terraria.Main.myPlayer, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.SetTalkNPC(), Terraria.Player.tileEntityAnchor, and Terraria.Entity.whoAmI.
Referenced by Terraria.DataStructures.TileEntity.BasicOpenCloseInteraction(), and Terraria.MessageBuffer.GetData().