Terraria: Terraria.DataStructures.TileEntity.Read
Read()
static TileEntity Terraria.DataStructures.TileEntity.Read (BinaryReader reader, bool networkSend = false) inline static inherited
    {
        byte id = reader.ReadByte();
        TileEntity tileEntity = manager.GenerateInstance(id);
        tileEntity.type = id;
        tileEntity.ReadInner(reader, networkSend);
        return tileEntity;
    }
References Terraria.DataStructures.TileEntitiesManager.GenerateInstance(), Terraria.DataStructures.TileEntity.manager, and Terraria.DataStructures.TileEntity.ReadInner().
Referenced by Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.MessageBuffer.GetData(), Terraria.IO.WorldFile.LoadTileEntities(), and Terraria.IO.WorldFile.ValidateWorld().