Terraria: Terraria.DataStructures.TileEntity.ByID
ByID
Dictionary<int, TileEntity> Terraria.DataStructures.TileEntity.ByID = new Dictionary<int, TileEntity>() static inherited
Definition at line 18 of file TileEntity.cs.
Referenced by Terraria.NPC.AI(), Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2(), Terraria.WorldGen.CheckFoodPlatter(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.DataStructures.TileEntity.Clear(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.IO.WorldFile.ConvertOldTileEntities(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.IO.WorldFile.FixAgainstExploits(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.MessageBuffer.GetData(), Terraria.DataStructures.PlayerInteractionAnchor.GetTileEntity(), Terraria.GameContent.Tile_Entities.TELogicSensor.Hook_AfterPlacement(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.IsBreakable(), Terraria.GameContent.Tile_Entities.TEHatRack.IsBreakable(), Terraria.DataStructures.PlayerInteractionAnchor.IsInValidUseTileEntity(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Kill(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Kill(), Terraria.GameContent.Tile_Entities.TEHatRack.Kill(), Terraria.GameContent.Tile_Entities.TEItemFrame.Kill(), Terraria.GameContent.Tile_Entities.TELogicSensor.Kill(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Kill(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Kill(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Kill(), Terraria.WorldGen.KillTile(), Terraria.IO.WorldFile.LoadTileEntities(), Terraria.GameContent.Tile_Entities.TELogicSensor.NetPlaceEntity(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEItemFrame.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Place(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Place(), Terraria.GameContent.Tile_Entities.TEHatRack.Place(), Terraria.GameContent.Tile_Entities.TEItemFrame.Place(), Terraria.GameContent.Tile_Entities.TELogicSensor.Place(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Place(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Place(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Place(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.IO.WorldFile.SaveTileEntities(), Terraria.NetMessage.SendData(), Terraria.Player.TileInteractionsMouseOver(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing(), Terraria.GameContent.Tile_Entities.TELogicSensor.UpdateEndInternal(), and Terraria.WorldGen.UpdateWorld().