Terraria: ChromaPipeline.ProcessDevice
ProcessDevice()
void ChromaPipeline.ProcessDevice (RgbDevice device, IEnumerable< ShaderOperation > shaders, float time) inline private
     {
         Fragment fragment = device.Rasterize();
         if (shaders != null)
         {
             foreach (ShaderOperation shader in shaders)
             {
                 shader.Process(device, fragment, time);
                 device.Render(fragment, shader.BlendState);
             }
         }
         if (_hotkeys != null && device is RgbKeyboard rgbKeyboard)
         {
             rgbKeyboard.Render(_hotkeys.Where((RgbKey key) => key.IsVisible));
         }
         if (this.PostProcessingEvents != null)
         {
             fragment.Clear();
             this.PostProcessingEvents(device, fragment, time);
             device.Render(fragment, new ShaderBlendState(BlendMode.PerPixelOpacity));
         }
     }
References _hotkeys, ShaderOperation.BlendState, Fragment.Clear(), RgbKey.IsVisible, PostProcessingEvents, ShaderOperation.Process(), RgbDevice.Rasterize(), and RgbDevice.Render().
Referenced by Process().