Terraria: Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.Draw
Draw()
void Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.Draw (SpriteBatch spriteBatch, ref bool isHovered) inline
Definition at line 27 of file ResourceDrawSettings.cs.
    {
        int elementCount = ElementCount;
        Vector2 topLeftAnchor = TopLeftAnchor;
        Point value = Main.MouseScreen.ToPoint();
        for (int i = 0; i < elementCount; i++)
        {
            int elementIndex = i + ElementIndexOffset;
            GetTextureMethod(elementIndex, ElementIndexOffset, ElementIndexOffset + elementCount - 1, out var texture, out var drawOffset, out var drawScale, out var sourceRect);
            Rectangle rectangle = texture.Frame();
            if (sourceRect.HasValue)
            {
                rectangle = sourceRect.Value;
            }
            Vector2 position = topLeftAnchor + drawOffset;
            Vector2 origin = OffsetSpriteAnchor + rectangle.Size() * OffsetSpriteAnchorByTexturePercentile;
            Rectangle rectangle2 = rectangle;
            rectangle2.X += (int)(position.X - origin.X);
            rectangle2.Y += (int)(position.Y - origin.Y);
            if (rectangle2.Contains(value))
            {
                isHovered = true;
            }
            spriteBatch.Draw(texture.Value, position, rectangle, Color.White, 0f, origin, drawScale, SpriteEffects.None, 0f);
            topLeftAnchor += OffsetPerDraw + rectangle.Size() * OffsetPerDrawByTexturePercentile;
        }
    }
References Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.ElementCount, Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.ElementIndexOffset, Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.GetTextureMethod, Terraria.Main.MouseScreen, Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.OffsetPerDraw, Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.OffsetPerDrawByTexturePercentile, Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.OffsetSpriteAnchor, Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.OffsetSpriteAnchorByTexturePercentile, Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.TopLeftAnchor, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.Draw(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawLifeBar(), and Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawManaBar().