Terraria: DSTFilm.TurnPlayerToTheLeft
TurnPlayerToTheLeft()
void DSTFilm.TurnPlayerToTheLeft (FrameEventData evt) inline private
     {
         Main.LocalPlayer.ChangeDir(-1);
         _chester.velocity = new Vector2(-0.1f, 0f);
         _chester.spriteDirection = (_chester.direction = -1);
         _deerclops.ai[0] = 1f;
         _deerclops.ai[1] = 0f;
         _deerclops.TargetClosest();
     }
References _chester, _deerclops, NPC.ai, Player.ChangeDir(), Entity.direction, Main.LocalPlayer, Projectile.spriteDirection, NPC.TargetClosest(), and Entity.velocity.
Referenced by BuildSequence().