Terraria: System.Security.Cryptography.X509Certificates.X509SignatureGenerator.CreateForRSA
CreateForRSA()
static X509SignatureGenerator System.Security.Cryptography.X509Certificates.X509SignatureGenerator.CreateForRSA (RSA key, RSASignaturePadding signaturePadding) inline static
Definition at line 34 of file X509SignatureGenerator.cs.
    {
        if (key == null)
        {
            throw new ArgumentNullException("key");
        }
        if (signaturePadding == null)
        {
            throw new ArgumentNullException("signaturePadding");
        }
        if (signaturePadding == RSASignaturePadding.Pkcs1)
        {
            return new RSAPkcs1X509SignatureGenerator(key);
        }
        if (signaturePadding.Mode == RSASignaturePaddingMode.Pss)
        {
            return new RSAPssX509SignatureGenerator(key, signaturePadding);
        }
        throw new ArgumentException(System.SR.Cryptography_InvalidPaddingMode);
    }
References System.SR.Cryptography_InvalidPaddingMode, System.key, System.Security.Cryptography.RSASignaturePadding.Mode, and System.Security.Cryptography.RSASignaturePadding.Pkcs1.
Referenced by System.Security.Cryptography.X509Certificates.CertificateRequest.CertificateRequest(), System.Security.Cryptography.X509Certificates.CertificateRequest.CertificateRequest(), and System.Security.Cryptography.X509Certificates.CertificateRequest.Create().