Terraria: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place
Place()
virtual void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place (HouseBuilderContext context, StructureMap structures) inline virtual inherited
Reimplemented in Terraria.GameContent.Biomes.CaveHouse.WoodHouseBuilder.
Definition at line 80 of file HouseBuilder.cs.
    {
        PlaceEmptyRooms();
        foreach (Rectangle room in Rooms)
        {
            structures.AddProtectedStructure(room, 8);
        }
        PlaceStairs();
        PlaceDoors();
        PlacePlatforms();
        PlaceSupportBeams();
        PlaceBiomeSpecificPriorityTool(context);
        FillRooms();
        foreach (Rectangle room2 in Rooms)
        {
            AgeRoom(room2);
        }
        PlaceChests();
        PlaceBiomeSpecificTool(context);
    }
References Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificPriorityTool(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificTool(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceChests(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceDoors(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceEmptyRooms(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlacePlatforms(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceStairs(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceSupportBeams(), and Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Rooms.
Referenced by Terraria.GameContent.Biomes.CaveHouseBiome.Place().