Terraria: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceEmptyRooms
PlaceEmptyRooms()
void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceEmptyRooms () inline private inherited
Definition at line 101 of file HouseBuilder.cs.
    {
        foreach (Rectangle room in Rooms)
        {
            WorldUtils.Gen(new Point(room.X, room.Y), new Shapes.Rectangle(room.Width, room.Height), Actions.Chain(new Actions.SetTileKeepWall(TileType), new Actions.SetFrames(frameNeighbors: true)));
            WorldUtils.Gen(new Point(room.X + 1, room.Y + 1), new Shapes.Rectangle(room.Width - 2, room.Height - 2), Actions.Chain(new Actions.ClearTile(frameNeighbors: true), new Actions.PlaceWall(WallType)));
        }
    }
References Terraria.WorldBuilding.Actions.Chain(), Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Rooms, Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.TileType, and Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.WallType.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place().