Terraria: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FindVerticalExit
FindVerticalExit()
static bool Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FindVerticalExit (Rectangle wall, bool isUp, out int exitX) inline static private inherited
Definition at line 344 of file HouseBuilder.cs.
    {
        Point result;
        bool result2 = WorldUtils.Find(new Point(wall.X + wall.Width - 3, wall.Y + (isUp ? (-5) : 0)), Searches.Chain(new Searches.Left(wall.Width - 3), new Conditions.IsSolid().Not().AreaOr(3, 5)), out result);
        exitX = result.X;
        return result2;
    }
References Terraria.WorldBuilding.GenCondition.AreaOr(), Terraria.WorldBuilding.Searches.Chain(), Terraria.WorldBuilding.WorldUtils.Find(), Terraria.WorldBuilding.GenCondition.Not(), Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.CreatePlatformsList().