Terraria: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlacePlatforms
PlacePlatforms()
void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlacePlatforms () inline private inherited
Definition at line 259 of file HouseBuilder.cs.
    {
        foreach (Point item in CreatePlatformsList())
        {
            WorldUtils.Gen(item, new Shapes.Rectangle(3, 1), Actions.Chain(new Actions.ClearMetadata(), new Actions.PlaceTile(19, PlatformStyle), new Actions.SetFrames(frameNeighbors: true)));
        }
    }
References Terraria.WorldBuilding.Actions.Chain(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.CreatePlatformsList(), Terraria.WorldBuilding.WorldUtils.Gen(), System.item, and Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlatformStyle.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place().