Terraria: System.Data.Common.DateTimeStorage.SetStorage
SetStorage()
override void System.Data.Common.DateTimeStorage.SetStorage (object store, BitArray nullbits) inline protected
Definition at line 224 of file DateTimeStorage.cs.
    {
        _values = (DateTime[])store;
        SetNullStorage(nullbits);
        if (base.DateTimeMode == DataSetDateTime.UnspecifiedLocal)
        {
            for (int i = 0; i < _values.Length; i++)
            {
                if (HasValue(i))
                {
                    _values[i] = DateTime.SpecifyKind(_values[i].ToLocalTime(), DateTimeKind.Unspecified);
                }
            }
        }
        else
        {
            if (base.DateTimeMode != DataSetDateTime.Local)
            {
                return;
            }
            for (int j = 0; j < _values.Length; j++)
            {
                if (HasValue(j))
                {
                    _values[j] = _values[j].ToLocalTime();
                }
            }
        }
    }
References System.Data.Common.DateTimeStorage._values, System.Xml.Dictionary, System.Data.Common.DataStorage.HasValue(), System.Data.Common.DataStorage.SetNullStorage(), System.DateTime.SpecifyKind(), and System.DateTime.ToLocalTime().