Terraria: System.Data.Common.DateTimeStorage.Set
Set()
override void System.Data.Common.DateTimeStorage.Set (int record, object value) inline
Definition at line 144 of file DateTimeStorage.cs.
    {
        if (_nullValue == value)
        {
            _values[record] = s_defaultValue;
            SetNullBit(record, flag: true);
            return;
        }
        DateTime dateTime = ((IConvertible)value).ToDateTime(base.FormatProvider);
        DateTime dateTime2;
        switch (base.DateTimeMode)
        {
        case DataSetDateTime.Utc:
            dateTime2 = ((dateTime.Kind != DateTimeKind.Utc) ? ((dateTime.Kind != DateTimeKind.Local) ? DateTime.SpecifyKind(dateTime, DateTimeKind.Utc) : dateTime.ToUniversalTime()) : dateTime);
            break;
        case DataSetDateTime.Local:
            dateTime2 = ((dateTime.Kind != DateTimeKind.Local) ? ((dateTime.Kind != DateTimeKind.Utc) ? DateTime.SpecifyKind(dateTime, DateTimeKind.Local) : dateTime.ToLocalTime()) : dateTime);
            break;
        case DataSetDateTime.Unspecified:
        case DataSetDateTime.UnspecifiedLocal:
            dateTime2 = DateTime.SpecifyKind(dateTime, DateTimeKind.Unspecified);
            break;
        default:
            throw ExceptionBuilder.InvalidDateTimeMode(base.DateTimeMode);
        }
        _values[record] = dateTime2;
        SetNullBit(record, flag: false);
    }
References System.Data.Common.DataStorage._nullValue, System.Data.Common.DateTimeStorage._values, System.Xml.Dictionary, System.Data.ExceptionBuilder.InvalidDateTimeMode(), System.Data.Common.DateTimeStorage.s_defaultValue, System.Data.Common.DataStorage.SetNullBit(), System.DateTime.SpecifyKind(), System.DateTime.ToDateTime(), and System.value.