Terraria: System.Text.DecoderNLS.DrainLeftoverDataForGetChars
DrainLeftoverDataForGetChars()
int System.Text.DecoderNLS.DrainLeftoverDataForGetChars (ReadOnlySpan< byte > bytes, Span< char > chars, out int bytesConsumed) inline package inherited
Definition at line 226 of file DecoderNLS.cs.
    {
        Span<byte> span = stackalloc byte[4];
        span = span.Slice(0, ConcatInto(GetLeftoverData(), bytes, span));
        int charsWritten = 0;
        bool flag = false;
        Rune value;
        int bytesConsumed2;
        switch (_encoding.DecodeFirstRune(span, out value, out bytesConsumed2))
        {
        case OperationStatus.Done:
            if (!value.TryEncodeToUtf16(chars, out charsWritten))
            {
                break;
            }
            goto IL_00aa;
        case OperationStatus.NeedMoreData:
            if (MustFlush)
            {
                goto default;
            }
            flag = true;
            goto IL_00aa;
        default:
            {
                if (base.FallbackBuffer.Fallback(span.Slice(0, bytesConsumed2).ToArray(), -_leftoverByteCount) && !_fallbackBuffer.TryDrainRemainingDataForGetChars(chars, out charsWritten))
                {
                    break;
                }
                goto IL_00aa;
            }
            IL_00aa:
            bytesConsumed = bytesConsumed2 - _leftoverByteCount;
            if (flag)
            {
                SetLeftoverData(span);
            }
            else
            {
                ClearLeftoverData();
            }
            return charsWritten;
        }
        _encoding.ThrowCharsOverflow(this, nothingDecoded: true);
        throw null;
    }
References System.Text.DecoderNLS._encoding, System.Text.Decoder._fallbackBuffer, System.Text.DecoderNLS._leftoverByteCount, System.bytes, System.chars, System.Text.DecoderNLS.ClearLeftoverData(), System.Text.DecoderNLS.ConcatInto(), System.Text.Encoding.DecodeFirstRune(), System.Text.DecoderNLS.GetLeftoverData(), System.Text.DecoderNLS.MustFlush, System.Text.DecoderNLS.SetLeftoverData(), System.Span< T >.Slice(), System.Text.Encoding.ThrowCharsOverflow(), System.Text.DecoderFallbackBuffer.TryDrainRemainingDataForGetChars(), and System.value.
Referenced by System.Text.Encoding.GetCharsWithFallback().