Terraria: System.Text.DecoderNLS.DrainLeftoverDataForGetCharCount
DrainLeftoverDataForGetCharCount()
int System.Text.DecoderNLS.DrainLeftoverDataForGetCharCount (ReadOnlySpan< byte > bytes, out int bytesConsumed) inline package inherited
Definition at line 197 of file DecoderNLS.cs.
    {
        Span<byte> span = stackalloc byte[4];
        span = span.Slice(0, ConcatInto(GetLeftoverData(), bytes, span));
        int result = 0;
        Rune value;
        int bytesConsumed2;
        switch (_encoding.DecodeFirstRune(span, out value, out bytesConsumed2))
        {
        case OperationStatus.Done:
            result = value.Utf16SequenceLength;
            break;
        case OperationStatus.NeedMoreData:
            if (!MustFlush)
            {
                break;
            }
            goto default;
        default:
            if (base.FallbackBuffer.Fallback(span.Slice(0, bytesConsumed2).ToArray(), -_leftoverByteCount))
            {
                result = _fallbackBuffer.DrainRemainingDataForGetCharCount();
            }
            break;
        }
        bytesConsumed = bytesConsumed2 - _leftoverByteCount;
        return result;
    }
References System.Text.DecoderNLS._encoding, System.Text.Decoder._fallbackBuffer, System.Text.DecoderNLS._leftoverByteCount, System.bytes, System.Text.DecoderNLS.ConcatInto(), System.Text.Encoding.DecodeFirstRune(), System.Text.DecoderFallbackBuffer.DrainRemainingDataForGetCharCount(), System.Text.DecoderNLS.GetLeftoverData(), System.Text.DecoderNLS.MustFlush, System.Span< T >.Slice(), and System.value.
Referenced by System.Text.Encoding.GetCharCountWithFallback().