Terraria: System.Data.DataRowView.CreateChildView
CreateChildView() [2/4]
DataView System.Data.DataRowView.CreateChildView (DataRelation relation, bool followParent) inline
Definition at line 137 of file DataRowView.cs.
    {
        if (relation == null || relation.ParentKey.Table != DataView.Table)
        {
            throw ExceptionBuilder.CreateChildView();
        }
        RelatedView relatedView;
        if (!followParent)
        {
            int record = GetRecord();
            object[] keyValues = relation.ParentKey.GetKeyValues(record);
            relatedView = new RelatedView(relation.ChildColumnsReference, keyValues);
        }
        else
        {
            relatedView = new RelatedView(this, relation.ParentKey, relation.ChildColumnsReference);
        }
        relatedView.SetIndex("", DataViewRowState.CurrentRows, null);
        relatedView.SetDataViewManager(DataView.DataViewManager);
        return relatedView;
    }
References System.Data.DataRelation.ChildColumnsReference, System.Data.ExceptionBuilder.CreateChildView(), System.Data.DataView.DataViewManager, System.Data.DataKey.GetKeyValues(), System.Data.DataRowView.GetRecord(), System.Data.DataRelation.ParentKey, System.Data.DataView.SetDataViewManager(), System.Data.RelatedView.SetIndex(), System.Data.DataKey.Table, and System.Data.DataView.Table.
Referenced by System.Data.DataRowView.CreateChildView(), System.Data.DataRowView.CreateChildView(), System.Data.DataRowView.CreateChildView(), and System.Data.DataRelationPropertyDescriptor.GetValue().