Terraria: System.Xml.Linq.XObject.AddAnnotation
AddAnnotation()
void System.Xml.Linq.XObject.AddAnnotation (object annotation) inline inherited
Definition at line 133 of file XObject.cs.
    {
        if (annotation == null)
        {
            throw new ArgumentNullException("annotation");
        }
        if (annotations == null)
        {
            annotations = ((!(annotation is object[])) ? annotation : new object[1] { annotation });
            return;
        }
        object[] array = annotations as object[];
        if (array == null)
        {
            annotations = new object[2] { annotations, annotation };
            return;
        }
        int i;
        for (i = 0; i < array.Length && array[i] != null; i++)
        {
        }
        if (i == array.Length)
        {
            Array.Resize(ref array, i * 2);
            annotations = array;
        }
        array[i] = annotation;
    }
References System.Xml.Linq.XObject.annotations, System.array, and System.Xml.Dictionary.
Referenced by System.Xml.Linq.XObject.SetBaseUri(), System.Xml.Linq.XElement.SetEndElementLineInfo(), and System.Xml.Linq.XObject.SetLineInfo().