Terraria: ReLogic.Peripherals.RGB.Razer.RazerLink.Present
Present()
override void ReLogic.Peripherals.RGB.Razer.RazerLink.Present () inline
Definition at line 18 of file RazerLink.cs.
    {
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < _effect.Color.Length; i++)
        {
            _effect.Color[i] = RazerHelper.Vector4ToDeviceColor(GetProcessedLedColor(i));
        }
        _handle.SetAsChromaLinkEffect(ref _effect);
        _handle.Apply();
    }
References ReLogic.Peripherals.RGB.Razer.RazerLink._effect, ReLogic.Peripherals.RGB.Razer.RazerLink._handle, ReLogic.Peripherals.RGB.Razer.EffectHandle.Apply(), ReLogic.Peripherals.RGB.RgbDevice.GetProcessedLedColor(), ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsChromaLinkEffect(), and ReLogic.Peripherals.RGB.Razer.RazerHelper.Vector4ToDeviceColor().