Terraria: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.ToCode
ToCode()
InternalPrimitiveTypeE System.Runtime.Serialization.Formatters.Binary.ObjectWriter.ToCode (Type type) inline package
Definition at line 723 of file ObjectWriter.cs.
    {
        if ((object)_previousType == type)
        {
            return _previousCode;
        }
        InternalPrimitiveTypeE internalPrimitiveTypeE = Converter.ToCode(type);
        if (internalPrimitiveTypeE != 0)
        {
            _previousType = type;
            _previousCode = internalPrimitiveTypeE;
        }
        return internalPrimitiveTypeE;
    }
References System.Runtime.Serialization.Formatters.Binary.ObjectWriter._previousCode, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._previousType, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.Converter.ToCode(), and System.type.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write().