Terraria: System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize
Serialize()
void System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize (object graph, BinaryFormatterWriter serWriter) inline package
Definition at line 59 of file ObjectWriter.cs.
    {
        if (graph == null)
        {
            throw new ArgumentNullException("graph");
        }
        if (serWriter == null)
        {
            throw new ArgumentNullException("serWriter");
        }
        _serWriter = serWriter;
        serWriter.WriteBegin();
        long num = 0L;
        _idGenerator = new ObjectIDGenerator();
        _objectQueue = new Queue<object>();
        _formatterConverter = new FormatterConverter();
        _serObjectInfoInit = new SerObjectInfoInit();
        _topId = InternalGetId(graph, assignUniqueIdToValueType: false, null, out var _);
        num = -1L;
        WriteSerializedStreamHeader(_topId, num);
        _objectQueue.Enqueue(graph);
        object next;
        long objID;
        while ((next = GetNext(out objID)) != null)
        {
            WriteObjectInfo writeObjectInfo = null;
            if (next is WriteObjectInfo)
            {
                writeObjectInfo = (WriteObjectInfo)next;
            }
            else
            {
                writeObjectInfo = WriteObjectInfo.Serialize(next, _surrogates, _context, _serObjectInfoInit, _formatterConverter, this, _binder);
                writeObjectInfo._assemId = GetAssemblyId(writeObjectInfo);
            }
            writeObjectInfo._objectId = objID;
            NameInfo nameInfo = TypeToNameInfo(writeObjectInfo);
            Write(writeObjectInfo, nameInfo, nameInfo);
            PutNameInfo(nameInfo);
            writeObjectInfo.ObjectEnd();
        }
        serWriter.WriteSerializationHeaderEnd();
        serWriter.WriteEnd();
        _objectManager.RaiseOnSerializedEvent();
    }
References System.Runtime.Serialization.Formatters.Binary.ObjectWriter._binder, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._context, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._formatterConverter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._idGenerator, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._objectManager, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._objectQueue, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._serWriter, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._surrogates, System.Runtime.Serialization.Formatters.Binary.ObjectWriter._topId, System.Runtime.Serialization.Dictionary, System.Collections.Generic.Queue< T >.Enqueue(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetNext(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId(), System.L, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.PutNameInfo(), System.Runtime.Serialization.SerializationObjectManager.RaiseOnSerializedEvent(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.TypeToNameInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteSerializedStreamHeader().