Terraria: System.Diagnostics.Tracing.EventSource.DispatchToAllListeners
DispatchToAllListeners()
void System.Diagnostics.Tracing.EventSource.DispatchToAllListeners (EventWrittenEventArgs eventCallbackArgs) inline package inherited
Definition at line 1543 of file EventSource.cs.
    {
        int eventId = eventCallbackArgs.EventId;
        Exception ex = null;
        for (EventDispatcher eventDispatcher = m_Dispatchers; eventDispatcher != null; eventDispatcher = eventDispatcher.m_Next)
        {
            if (eventId == -1 || eventDispatcher.m_EventEnabled[eventId])
            {
                try
                {
                    eventDispatcher.m_Listener.OnEventWritten(eventCallbackArgs);
                }
                catch (Exception ex2)
                {
                    ReportOutOfBandMessage("ERROR: Exception during EventSource.OnEventWritten: " + ex2.Message);
                    ex = ex2;
                }
            }
        }
        if (ex != null && ThrowOnEventWriteErrors)
        {
            throw new EventSourceException(ex);
        }
    }
References System.Diagnostics.Tracing.EventSource.m_Dispatchers, System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage(), and System.Diagnostics.Tracing.EventSource.ThrowOnEventWriteErrors.
Referenced by System.Diagnostics.Tracing.NativeRuntimeEventSource.ProcessEvent(), System.Diagnostics.Tracing.EventSource.WriteEventVarargs(), System.Diagnostics.Tracing.EventSource.WriteToAllListeners(), and System.Diagnostics.Tracing.EventSource.WriteToAllListeners().