Terraria: System.Diagnostics.Tracing.EventSource.WriteMultiMergeInner
WriteMultiMergeInner()
unsafe void System.Diagnostics.Tracing.EventSource.WriteMultiMergeInner (string eventName, ref EventSourceOptions options, TraceLoggingEventTypes eventTypes, Guid * activityID, Guid * childActivityID, params object[] values) inline private inherited
Definition at line 2842 of file EventSource.cs.
    {
        int num = 0;
        byte level = (((options.valuesSet & 4u) != 0) ? options.level : eventTypes.level);
        byte opcode = (((options.valuesSet & 8u) != 0) ? options.opcode : eventTypes.opcode);
        EventTags tags = (((options.valuesSet & 2u) != 0) ? options.tags : eventTypes.Tags);
        EventKeywords keywords = ((((uint)options.valuesSet & (true ? 1u : 0u)) != 0) ? options.keywords : eventTypes.keywords);
        NameInfo nameInfo = eventTypes.GetNameInfo(eventName ?? eventTypes.Name, tags);
        if (nameInfo == null)
        {
            return;
        }
        num = nameInfo.identity;
        EventDescriptor eventDescriptor = new EventDescriptor(num, level, opcode, (long)keywords);
        IntPtr orCreateEventHandle = nameInfo.GetOrCreateEventHandle(m_eventPipeProvider, m_eventHandleTable, eventDescriptor, eventTypes);
        int pinCount = eventTypes.pinCount;
        byte* scratch = stackalloc byte[(int)(uint)eventTypes.scratchSize];
        EventData* ptr = stackalloc EventData[eventTypes.dataCount + 3];
        for (int i = 0; i < eventTypes.dataCount + 3; i++)
        {
            ptr[i] = default(EventData);
        }
        GCHandle* ptr2 = stackalloc GCHandle[pinCount];
        for (int j = 0; j < pinCount; j++)
        {
            ptr2[j] = default(GCHandle);
        }
        ReadOnlySpan<byte> providerMetadata = ProviderMetadata;
        fixed (byte* pointer = providerMetadata)
        {
            fixed (byte* pointer2 = nameInfo.nameMetadata)
            {
                fixed (byte* pointer3 = eventTypes.typeMetadata)
                {
                    ptr->SetMetadata(pointer, providerMetadata.Length, 2);
                    ptr[1].SetMetadata(pointer2, nameInfo.nameMetadata.Length, 1);
                    ptr[2].SetMetadata(pointer3, eventTypes.typeMetadata.Length, 1);
                    try
                    {
                        DataCollector.ThreadInstance.Enable(scratch, eventTypes.scratchSize, ptr + 3, eventTypes.dataCount, ptr2, pinCount);
                        for (int k = 0; k < eventTypes.typeInfos.Length; k++)
{
                            TraceLoggingTypeInfo traceLoggingTypeInfo = eventTypes.typeInfos[k];
                            traceLoggingTypeInfo.WriteData(traceLoggingTypeInfo.PropertyValueFactory(values[k]));
                        }
                        WriteEventRaw(eventName, ref eventDescriptor, orCreateEventHandle, activityID, childActivityID, (int)(DataCollector.ThreadInstance.Finish() - ptr), (IntPtr)ptr);
                    }
                    finally
                    {
                        WriteCleanup(ptr2, pinCount);
                    }
                }
            }
        }
    }
References System.Diagnostics.Tracing.EventSource.m_eventHandleTable, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, System.options, System.pointer, System.Diagnostics.Tracing.EventSource.ProviderMetadata, System.Diagnostics.Tracing.DataCollector.ThreadInstance, System.values, System.Diagnostics.Tracing.EventSource.WriteCleanup(), and System.Diagnostics.Tracing.EventSource.WriteEventRaw().
Referenced by System.Diagnostics.Tracing.EventSource.WriteEventString(), and System.Diagnostics.Tracing.EventSource.WriteMultiMerge().