Terraria: System.Diagnostics.Tracing.EventSource.WriteEventString
WriteEventString()
unsafe void System.Diagnostics.Tracing.EventSource.WriteEventString (string msgString) inline private inherited
Definition at line 1568 of file EventSource.cs.
    {
        bool flag = true;
        flag &= m_etwProvider == null;
        if (flag & (m_eventPipeProvider == null))
        {
            return;
        }
        EventLevel eventLevel = EventLevel.LogAlways;
        long keywords = -1L;
        if (SelfDescribingEvents)
        {
            EventSourceOptions eventSourceOptions = default(EventSourceOptions);
            eventSourceOptions.Keywords = (EventKeywords)keywords;
            eventSourceOptions.Level = eventLevel;
            EventSourceOptions options = eventSourceOptions;
            TraceLoggingEventTypes eventTypes = GetTrimSafeTraceLoggingEventTypes();
            WriteMultiMergeInner("EventSourceMessage", ref options, eventTypes, null, null, msgString);
            return;
        }
        if (m_rawManifest == null && m_outOfBandMessageCount == 1)
        {
            ManifestBuilder manifestBuilder = new ManifestBuilder(Name, Guid, Name, null, EventManifestOptions.None);
            manifestBuilder.StartEvent("EventSourceMessage", new EventAttribute(0)
            {
                Level = eventLevel,
                Task = (EventTask)65534
            });
            manifestBuilder.AddEventParameter(typeof(string), "message");
            manifestBuilder.EndEvent();
            SendManifest(manifestBuilder.CreateManifest());
        }
        fixed (char* ptr = msgString)
        {
            EventDescriptor eventDescriptor = new EventDescriptor(0, 0, 0, (byte)eventLevel, 0, 0, keywords);
            EventProvider.EventData eventData = default(EventProvider.EventData);
            eventData.Ptr = (ulong)ptr;
            eventData.Size = (uint)(2 * (msgString.Length + 1));
            eventData.Reserved = 0u;
            if (m_etwProvider != null)
            {
                m_etwProvider.WriteEvent(ref eventDescriptor, IntPtr.Zero, null, null, 1, (IntPtr)(&eventData));
            }
            if (m_eventPipeProvider == null)
            {
                return;
            }
            if (m_writeEventStringEventHandle == IntPtr.Zero)
            {
                if (m_createEventLock == null)
                {
                    Interlocked.CompareExchange(ref m_createEventLock, new object(), null);
                }
                lock (m_createEventLock)
                {
                    if (m_writeEventStringEventHandle == IntPtr.Zero)
                    {
                        string eventName = "EventSourceMessage";
                        EventParameterInfo eventParameterInfo = default(EventParameterInfo);
                        eventParameterInfo.SetInfo("message", typeof(string));
                        byte[] array = EventPipeMetadataGenerator.Instance.GenerateMetadata(0, eventName, keywords, (uint)eventLevel, 0u, EventOpcode.Info, new EventParameterInfo[1] { eventParameterInfo });
                        uint metadataLength = ((array != null) ? ((uint)array.Length) : 0u);
                        fixed (byte* pMetadata = array)
{
                            m_writeEventStringEventHandle = m_eventPipeProvider.m_eventProvider.DefineEventHandle(0u, eventName, keywords, 0u, (uint)eventLevel, pMetadata, metadataLength);
                        }
                    }
                }
            }
            m_eventPipeProvider.WriteEvent(ref eventDescriptor, m_writeEventStringEventHandle, null, null, 1, (IntPtr)(&eventData));
        }
        [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "The call to TraceLoggingEventTypes with the below parameter values are trim safe")]
        static TraceLoggingEventTypes GetTrimSafeTraceLoggingEventTypes()
        {
            return new TraceLoggingEventTypes("EventSourceMessage", EventTags.None, typeof(string));
        }
    }
References System.array, System.Threading.Interlocked.CompareExchange(), System.Diagnostics.Tracing.EventPipeMetadataGenerator.Instance, System.L, System.Diagnostics.Tracing.EventSource.m_createEventLock, System.Diagnostics.Tracing.EventSource.m_etwProvider, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, System.Diagnostics.Tracing.EventSource.m_outOfBandMessageCount, System.Diagnostics.Tracing.EventSource.m_rawManifest, System.Diagnostics.Tracing.EventSource.m_writeEventStringEventHandle, System.Diagnostics.Tracing.EventSource.Name, System.options, System.Diagnostics.Tracing.EventSource.SelfDescribingEvents, System.Diagnostics.Tracing.SendManifest, System.Diagnostics.Tracing.EventSource.WriteMultiMergeInner(), and System.IntPtr.Zero.
Referenced by System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage().