Terraria: System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized
EnsureDescriptorsInitialized()
void System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized () inline private inherited
Definition at line 1996 of file EventSource.cs.
    {
        if (m_eventData != null)
        {
            return;
        }
        m_rawManifest = CreateManifestAndDescriptors(GetType(), Name, this);
        if (!AllowDuplicateSourceNames)
        {
            foreach (WeakReference<EventSource> s_EventSource in EventListener.s_EventSources)
            {
                if (s_EventSource.TryGetTarget(out var target) && target.Guid == m_guid && !target.IsDisposed && target != this)
                {
                    throw new ArgumentException(SR.Format(SR.EventSource_EventSourceGuidInUse, m_guid));
                }
            }
        }
        for (EventDispatcher eventDispatcher = m_Dispatchers; eventDispatcher != null; eventDispatcher = eventDispatcher.m_Next)
        {
            EventDispatcher eventDispatcher2 = eventDispatcher;
            if (eventDispatcher2.m_EventEnabled == null)
            {
                eventDispatcher2.m_EventEnabled = new bool[m_eventData.Length];
            }
        }
        DefineEventPipeEvents();
    }
References System.Diagnostics.Tracing.EventSource.AllowDuplicateSourceNames, System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors(), System.Diagnostics.Tracing.EventSource.DefineEventPipeEvents(), System.SR.EventSource_EventSourceGuidInUse, System.SR.Format(), System.Diagnostics.Tracing.EventSource.m_Dispatchers, System.Diagnostics.Tracing.EventSource.m_eventData, System.Diagnostics.Tracing.EventSource.m_guid, System.Diagnostics.Tracing.EventSource.m_rawManifest, System.Diagnostics.Tracing.EventSource.Name, and System.Diagnostics.Tracing.EventListener.s_EventSources.
Referenced by System.Diagnostics.Tracing.EventSource.DoCommand().