Terraria: System.Diagnostics.Tracing.EventSource.InitializeProviderMetadata
InitializeProviderMetadata()
void System.Diagnostics.Tracing.EventSource.InitializeProviderMetadata () inline private inherited
Definition at line 3076 of file EventSource.cs.
    {
        if (ProviderMetadata.Length > 0)
        {
            return;
        }
        if (m_traits != null)
        {
            List<byte> list = new List<byte>(100);
            for (int i = 0; i < m_traits.Length - 1; i += 2)
            {
                if (!m_traits[i].StartsWith("ETW_", StringComparison.Ordinal))
                {
                    continue;
                }
                string text = m_traits[i].Substring(4);
                if (!byte.TryParse(text, out var result))
                {
                    if (!(text == "GROUP"))
                    {
                        throw new ArgumentException(SR.Format(SR.EventSource_UnknownEtwTrait, text), "traits");
                    }
                    result = 1;
                }
                string value = m_traits[i + 1];
                int count = list.Count;
                list.Add(0);
                list.Add(0);
                list.Add(result);
                int num = AddValueToMetaData(list, value) + 3;
                list[count] = (byte)num;
                list[count + 1] = (byte)(num >> 8);
            }
            byte[] array = Statics.MetadataForString(Name, 0, list.Count, 0);
            int num2 = array.Length - list.Count;
            foreach (byte item in list)
            {
                array[num2++] = item;
            }
            m_providerMetadata = array;
        }
        else
        {
            m_providerMetadata = Statics.MetadataForString(Name, 0, 0, 0);
        }
    }
References System.Diagnostics.Tracing.EventSource.AddValueToMetaData(), System.array, System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.EventSource_UnknownEtwTrait, System.SR.Format(), System.item, System.list, System.Diagnostics.Tracing.EventSource.m_providerMetadata, System.Diagnostics.Tracing.EventSource.m_traits, System.Diagnostics.Tracing.Statics.MetadataForString(), System.Diagnostics.Tracing.EventSource.Name, System.Diagnostics.Tracing.EventSource.ProviderMetadata, System.text, and System.value.
Referenced by System.Diagnostics.Tracing.EventSource.Initialize().