Terraria: System.Diagnostics.Tracing.EventSource.WriteEvent
WriteEvent() [1/18]
unsafe void System.Diagnostics.Tracing.EventSource.WriteEvent (int eventId) inline protected inherited
Definition at line 535 of file EventSource.cs.
    {
        WriteEventCore(eventId, 0, null);
    }
References System.Diagnostics.Tracing.EventSource.WriteEventCore().
Referenced by System.Net.Sockets.SocketsTelemetry.AcceptFailed(), System.Net.Sockets.SocketsTelemetry.AcceptStart(), System.Net.Sockets.SocketsTelemetry.AcceptStop(), System.Diagnostics.Metrics.MetricsEventSource.BeginInstrumentReporting(), System.Buffers.ArrayPoolEventSource.BufferReturned(), System.Buffers.ArrayPoolEventSource.BufferTrimmed(), System.Buffers.ArrayPoolEventSource.BufferTrimPoll(), System.Diagnostics.Metrics.MetricsEventSource.CollectionStart(), System.Diagnostics.Metrics.MetricsEventSource.CollectionStop(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentBag_TryPeekSteals(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentBag_TryTakeSteals(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentDictionary_AcquiringAllLocks(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentStack_FastPopFailed(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentStack_FastPushFailed(), System.Transactions.TransactionsEtwProvider.ConfiguredDefaultTimeoutAdjustedTrace(), System.Net.Sockets.SocketsTelemetry.ConnectFailed(), System.Net.Sockets.SocketsTelemetry.ConnectStart(), System.Net.Sockets.SocketsTelemetry.ConnectStop(), System.Diagnostics.Metrics.MetricsEventSource.CounterRateValuePublished(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCompleted(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockCreated(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockLinking(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.DataflowBlockUnlinking(), System.Threading.Tasks.TplEventSource.DebugFacilityMessage(), System.Threading.Tasks.TplEventSource.DebugFacilityMessage1(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.DeserializationStart(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.DeserializationStop(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.DeserializingObject(), System.Diagnostics.Metrics.MetricsEventSource.EndInstrumentReporting(), System.Transactions.TransactionsEtwProvider.EnlistmentAborted(), System.Transactions.TransactionsEtwProvider.EnlistmentCommitted(), System.Transactions.TransactionsEtwProvider.EnlistmentDone(), System.Transactions.TransactionsEtwProvider.EnlistmentForceRollback(), System.Transactions.TransactionsEtwProvider.EnlistmentInDoubt(), System.Transactions.TransactionsEtwProvider.EnlistmentPrepared(), System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.Data.DataCommonEventSource.EnterScope(), System.Diagnostics.Metrics.MetricsEventSource.Error(), System.Transactions.TransactionsEtwProvider.ExceptionConsumedBase(), System.Transactions.TransactionsEtwProvider.ExceptionConsumedLtm(), System.Data.DataCommonEventSource.ExitScope(), System.Diagnostics.Metrics.MetricsEventSource.GaugeValuePublished(), System.Diagnostics.Metrics.MetricsEventSource.HistogramLimitReached(), System.Diagnostics.Metrics.MetricsEventSource.HistogramValuePublished(), System.Threading.Tasks.TplEventSource.IncompleteAsyncMethod(), System.Diagnostics.Metrics.MetricsEventSource.InitialInstrumentEnumerationComplete(), System.Diagnostics.Metrics.MetricsEventSource.InstrumentPublished(), System.Diagnostics.Tracing.RuntimeEventSource.LogAppContextSwitch(), System.Diagnostics.Metrics.MetricsEventSource.Message(), System.Transactions.TransactionsEtwProvider.MethodEnterTraceBase(), System.Transactions.TransactionsEtwProvider.MethodEnterTraceDistributed(), System.Transactions.TransactionsEtwProvider.MethodEnterTraceLtm(), System.Transactions.TransactionsEtwProvider.MethodExitTraceBase(), System.Transactions.TransactionsEtwProvider.MethodExitTraceDistributed(), System.Transactions.TransactionsEtwProvider.MethodExitTraceLtm(), System.Diagnostics.Metrics.MetricsEventSource.MultipleSessionsNotSupportedError(), System.Threading.Tasks.TplEventSource.NewID(), System.Diagnostics.Metrics.MetricsEventSource.ObservableInstrumentCallbackError(), System.Threading.Tasks.ParallelEtwProvider.ParallelFork(), System.Threading.Tasks.ParallelEtwProvider.ParallelInvokeEnd(), System.Threading.Tasks.ParallelEtwProvider.ParallelJoin(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryBegin(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryEnd(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryFork(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryJoin(), System.Net.NameResolutionTelemetry.ResolutionFailed(), System.Net.NameResolutionTelemetry.ResolutionStart(), System.Net.NameResolutionTelemetry.ResolutionStop(), System.Threading.Tasks.TplEventSource.RunningContinuation(), System.Threading.Tasks.TplEventSource.RunningContinuationList(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.SerializationStart(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.SerializationStop(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatterEventSource.SerializingObject(), System.Threading.Tasks.TplEventSource.SetActivityId(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.TaskLaunchedForMessageHandling(), System.Threading.Tasks.TplEventSource.TaskStarted(), System.Threading.Tasks.TplEventSource.TaskWaitContinuationComplete(), System.Threading.Tasks.TplEventSource.TaskWaitContinuationStarted(), System.Threading.Tasks.TplEventSource.TaskWaitEnd(), System.Diagnostics.Metrics.MetricsEventSource.TimeSeriesLimitReached(), System.Data.DataCommonEventSource.Trace(), System.Threading.Tasks.TplEventSource.TraceOperationEnd(), System.Threading.Tasks.TplEventSource.TraceOperationRelation(), System.Threading.Tasks.TplEventSource.TraceSynchronousWorkBegin(), System.Transactions.TransactionsEtwProvider.TransactionAborted(), System.Transactions.TransactionsEtwProvider.TransactionCloneCreate(), System.Transactions.TransactionsEtwProvider.TransactionCommit(), System.Transactions.TransactionsEtwProvider.TransactionCommitted(), System.Transactions.TransactionsEtwProvider.TransactionCreated(), System.Transactions.TransactionsEtwProvider.TransactionDependentCloneComplete(), System.Transactions.TransactionsEtwProvider.TransactionExceptionBase(), System.Transactions.TransactionsEtwProvider.TransactionExceptionLtm(), System.Transactions.TransactionsEtwProvider.TransactionInDoubt(), System.Transactions.TransactionsEtwProvider.TransactionInvalidOperation(), System.Transactions.TransactionsEtwProvider.TransactionManagerRecoveryComplete(), System.Transactions.TransactionsEtwProvider.TransactionManagerReenlistTrace(), System.Transactions.TransactionsEtwProvider.TransactionPromoted(), System.Transactions.TransactionsEtwProvider.TransactionRollback(), System.Transactions.TransactionsEtwProvider.TransactionScopeCreated(), System.Transactions.TransactionsEtwProvider.TransactionScopeCurrentChanged(), System.Transactions.TransactionsEtwProvider.TransactionScopeDisposed(), System.Transactions.TransactionsEtwProvider.TransactionScopeIncomplete(), System.Transactions.TransactionsEtwProvider.TransactionScopeInternalErrorTrace(), System.Transactions.TransactionsEtwProvider.TransactionScopeNestedIncorrectly(), System.Transactions.TransactionsEtwProvider.TransactionScopeTimeout(), System.Transactions.TransactionsEtwProvider.TransactionstateEnlist(), System.Transactions.TransactionsEtwProvider.TransactionTimeout(), and System.Xml.Serialization.XmlSerializationEventSource.XmlSerializerExpired().