Terraria: System.Diagnostics.Tracing.EventSource.UpdateDescriptor
UpdateDescriptor()
NameInfo System.Diagnostics.Tracing.EventSource.UpdateDescriptor (string name, TraceLoggingEventTypes eventInfo, ref EventSourceOptions options, out EventDescriptor descriptor) inline private inherited
Definition at line 3183 of file EventSource.cs.
    {
        NameInfo nameInfo = null;
        int traceloggingId = 0;
        byte level = (((options.valuesSet & 4u) != 0) ? options.level : eventInfo.level);
        byte opcode = (((options.valuesSet & 8u) != 0) ? options.opcode : eventInfo.opcode);
        EventTags tags = (((options.valuesSet & 2u) != 0) ? options.tags : eventInfo.Tags);
        EventKeywords keywords = ((((uint)options.valuesSet & (true ? 1u : 0u)) != 0) ? options.keywords : eventInfo.keywords);
        if (IsEnabled((EventLevel)level, keywords))
        {
            nameInfo = eventInfo.GetNameInfo(name ?? eventInfo.Name, tags);
            traceloggingId = nameInfo.identity;
        }
        descriptor = new EventDescriptor(traceloggingId, level, opcode, (long)keywords);
        return nameInfo;
    }
References System.Diagnostics.Tracing.EventSource.IsEnabled(), and System.options.
Referenced by System.Diagnostics.Tracing.EventSource.WriteImpl(), and System.Diagnostics.Tracing.EventSource.WriteMultiMerge().