Terraria: System.Diagnostics.Tracing.EventSource.AddValueToMetaData
AddValueToMetaData()
static int System.Diagnostics.Tracing.EventSource.AddValueToMetaData (List< byte > metaData, string value) inline static private inherited
Definition at line 3123 of file EventSource.cs.
    {
        if (value.Length == 0)
        {
            return 0;
        }
        int count = metaData.Count;
        char c = value[0];
        switch (c)
        {
        case '@':
            metaData.AddRange(Encoding.UTF8.GetBytes(value.Substring(1)));
            break;
        case '{':
            metaData.AddRange(new Guid(value).ToByteArray());
            break;
        case '#':
        {
            for (int i = 1; i < value.Length; i++)
            {
                if (value[i] != ' ')
                {
                    if (i + 1 >= value.Length)
                    {
                        throw new ArgumentException(SR.EventSource_EvenHexDigits, "traits");
                    }
                    metaData.Add((byte)(HexDigit(value[i]) * 16 + HexDigit(value[i + 1])));
                    i++;
                }
            }
            break;
        }
        default:
            if ('A' <= c || ' ' == c)
            {
                metaData.AddRange(Encoding.UTF8.GetBytes(value));
                break;
            }
            throw new ArgumentException(SR.Format(SR.EventSource_IllegalValue, value), "traits");
        }
        return metaData.Count - count;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.EventSource_EvenHexDigits, System.SR.EventSource_IllegalValue, System.SR.Format(), System.Diagnostics.Tracing.EventSource.Guid, System.Diagnostics.Tracing.EventSource.HexDigit(), System.Text.Encoding.UTF8, and System.value.
Referenced by System.Diagnostics.Tracing.EventSource.InitializeProviderMetadata().