Terraria: System.Diagnostics.Tracing.EventSource.Initialize
Initialize()
unsafe void System.Diagnostics.Tracing.EventSource.Initialize (Guid eventSourceGuid, string eventSourceName, string[] traits) inline private inherited
Definition at line 1132 of file EventSource.cs.
    {
        try
        {
            m_traits = traits;
            if (m_traits != null && m_traits.Length % 2 != 0)
            {
                throw new ArgumentException(SR.EventSource_TraitEven, "traits");
            }
            if (eventSourceGuid == Guid.Empty)
            {
                throw new ArgumentException(SR.EventSource_NeedGuid);
            }
            if (eventSourceName == null)
            {
                throw new ArgumentException(SR.EventSource_NeedName);
            }
            m_name = eventSourceName;
            m_guid = eventSourceGuid;
            m_activityTracker = ActivityTracker.Instance;
            if (ProviderMetadata.Length == 0)
            {
                InitializeProviderMetadata();
            }
            OverrideEventProvider overrideEventProvider = new OverrideEventProvider(this, EventProviderType.ETW);
            overrideEventProvider.Register(this);
            OverrideEventProvider overrideEventProvider2 = new OverrideEventProvider(this, EventProviderType.EventPipe);
            lock (EventListener.EventListenersLock)
            {
                overrideEventProvider2.Register(this);
            }
            EventListener.AddEventSource(this);
            m_etwProvider = overrideEventProvider;
            if (Name != "System.Diagnostics.Eventing.FrameworkEventSource" || Environment.IsWindows8OrAbove)
            {
                ReadOnlySpan<byte> providerMetadata = ProviderMetadata;
                fixed (byte* data = providerMetadata)
                {
                    m_etwProvider.SetInformation(Interop.Advapi32.EVENT_INFO_CLASS.SetTraits, data, (uint)providerMetadata.Length);
                }
            }
            m_eventPipeProvider = overrideEventProvider2;
            m_completelyInited = true;
        }
        catch (Exception ex)
        {
            if (m_constructionException == null)
            {
                m_constructionException = ex;
            }
            ReportOutOfBandMessage("ERROR: Exception during construction of EventSource " + Name + ": " + ex.Message);
        }
        lock (EventListener.EventListenersLock)
        {
            for (EventCommandEventArgs eventCommandEventArgs = m_deferredCommands; eventCommandEventArgs != null; eventCommandEventArgs = eventCommandEventArgs.nextCommand)
            {
                DoCommand(eventCommandEventArgs);
            }
        }
    }
References System.Diagnostics.Tracing.EventListener.AddEventSource(), System.Diagnostics.Tracing.EventSource.DoCommand(), System.Guid.Empty, System.Diagnostics.Tracing.EventListener.EventListenersLock, System.SR.EventSource_NeedGuid, System.SR.EventSource_NeedName, System.SR.EventSource_TraitEven, System.Diagnostics.Tracing.EventSource.InitializeProviderMetadata(), System.Diagnostics.Tracing.ActivityTracker.Instance, System.Environment.IsWindows8OrAbove, System.Diagnostics.Tracing.EventSource.m_activityTracker, System.Diagnostics.Tracing.EventSource.m_completelyInited, System.Diagnostics.Tracing.EventSource.m_constructionException, System.Diagnostics.Tracing.EventSource.m_deferredCommands, System.Diagnostics.Tracing.EventSource.m_etwProvider, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, System.Diagnostics.Tracing.EventSource.m_guid, System.Diagnostics.Tracing.EventSource.m_name, System.Diagnostics.Tracing.EventSource.m_traits, System.Diagnostics.Tracing.EventSource.Name, System.Diagnostics.Tracing.EventSource.ProviderMetadata, and System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage().
Referenced by System.Diagnostics.Tracing.EventSource.EventSource(), and System.Diagnostics.Tracing.EventSource.EventSource().