Terraria: System.Diagnostics.Tracing.EventSource.SendManifest
SendManifest()
unsafe void System.Diagnostics.Tracing.EventSource.SendManifest (byte[] rawManifest) inline private inherited
Definition at line 2024 of file EventSource.cs.
    {
        if (rawManifest == null)
        {
            return;
        }
        fixed (byte* ptr2 = rawManifest)
        {
            EventDescriptor eventDescriptor = new EventDescriptor(65534, 1, 0, 0, 254, 65534, 72057594037927935L);
            ManifestEnvelope manifestEnvelope = default(ManifestEnvelope);
            manifestEnvelope.Format = ManifestEnvelope.ManifestFormats.SimpleXmlFormat;
            manifestEnvelope.MajorVersion = 1;
            manifestEnvelope.MinorVersion = 0;
            manifestEnvelope.Magic = 91;
            int num = rawManifest.Length;
            manifestEnvelope.ChunkNumber = 0;
            EventProvider.EventData* ptr = stackalloc EventProvider.EventData[2];
            ptr->Ptr = (ulong)(&manifestEnvelope);
            ptr->Size = (uint)sizeof(ManifestEnvelope);
            ptr->Reserved = 0u;
            ptr[1].Ptr = (ulong)ptr2;
            ptr[1].Reserved = 0u;
            int num2 = 65280;
            while (true)
            {
                IL_00c7:
                manifestEnvelope.TotalChunks = (ushort)((num + (num2 - 1)) / num2);
                while (num > 0)
                {
                    ptr[1].Size = (uint)Math.Min(num, num2);
                    if (m_etwProvider != null && !m_etwProvider.WriteEvent(ref eventDescriptor, IntPtr.Zero, null, null, 2, (IntPtr)ptr))
                    {
                        if (EventProvider.GetLastWriteEventError() == EventProvider.WriteEventErrorCode.EventTooBig && manifestEnvelope.ChunkNumber == 0 && num2 > 256)
{
                            num2 /= 2;
                            goto IL_00c7;
                        }
                        if (ThrowOnEventWriteErrors)
{
                            ThrowEventSourceException("SendManifest");
                        }
                        break;
                    }
                    num -= num2;
                    ptr[1].Ptr += (uint)num2;
                    manifestEnvelope.ChunkNumber++;
                    if (manifestEnvelope.ChunkNumber % 5 == 0)
                    {
                        Thread.Sleep(15);
                    }
                }
                break;
            }
        }
    }
References System.Diagnostics.Tracing.EventProvider.GetLastWriteEventError(), System.L, System.Diagnostics.Tracing.EventSource.m_etwProvider, System.Math.Min(), System.Threading.Thread.Sleep(), System.Diagnostics.Tracing.EventSource.ThrowEventSourceException(), System.Diagnostics.Tracing.EventSource.ThrowOnEventWriteErrors, and System.IntPtr.Zero.