Terraria: System.Diagnostics.Tracing.EventSource.WriteToAllListeners
WriteToAllListeners() [1/2]
unsafe void System.Diagnostics.Tracing.EventSource.WriteToAllListeners (EventWrittenEventArgs eventCallbackArgs, int eventDataCount, EventData * data) inline private inherited
Definition at line 1499 of file EventSource.cs.
    {
        ref EventMetadata reference = ref m_eventData[eventCallbackArgs.EventId];
        if (eventDataCount != reference.EventListenerParameterCount)
        {
            ReportOutOfBandMessage(SR.Format(SR.EventSource_EventParametersMismatch, eventCallbackArgs.EventId, eventDataCount, reference.Parameters.Length));
        }
        if (eventDataCount == 0)
        {
            eventCallbackArgs.Payload = EventWrittenEventArgs.EmptyPayload;
        }
        else
        {
            object[] array = new object[Math.Min(eventDataCount, reference.Parameters.Length)];
            if (reference.AllParametersAreString)
            {
                int num = 0;
                while (num < array.Length)
                {
                    IntPtr dataPointer = data->DataPointer;
                    array[num] = ((dataPointer == IntPtr.Zero) ? null : new string((char*)(void*)dataPointer, 0, (data->Size >> 1) - 1));
                    num++;
                    data++;
                }
            }
            else if (reference.AllParametersAreInt32)
            {
                int num2 = 0;
                while (num2 < array.Length)
                {
                    array[num2] = *(int*)(void*)data->DataPointer;
                    num2++;
                    data++;
                }
            }
            else
            {
                DecodeObjects(array, reference.ParameterTypes, data);
            }
            eventCallbackArgs.Payload = new ReadOnlyCollection<object>(array);
        }
        DispatchToAllListeners(eventCallbackArgs);
    }
References System.array, System.Diagnostics.Tracing.EventSource.EventData.DataPointer, System.Diagnostics.Tracing.EventSource.DecodeObjects(), System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(), System.Diagnostics.Tracing.EventWrittenEventArgs.EmptyPayload, System.SR.EventSource_EventParametersMismatch, System.SR.Format(), System.Diagnostics.Tracing.EventSource.m_eventData, System.Math.Min(), System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage(), System.Diagnostics.Tracing.EventSource.EventData.Size, and System.IntPtr.Zero.
Referenced by System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(), and System.Diagnostics.Tracing.EventSource.WriteImpl().