Terraria: System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper
GetCustomAttributeHelper()
static Attribute System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper (MemberInfo member, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.PublicProperties)] Type attributeType, EventManifestOptions flags = EventManifestOptions::None) inline static package inherited
Definition at line 2097 of file EventSource.cs.
    {
        if (!member.Module.Assembly.ReflectionOnly && (flags & EventManifestOptions.AllowEventSourceOverride) == 0)
        {
            return member.GetCustomAttribute(attributeType, inherit: false);
        }
        foreach (CustomAttributeData customAttribute in CustomAttributeData.GetCustomAttributes(member))
        {
            if (!AttributeTypeNamesMatch(attributeType, customAttribute.Constructor.ReflectedType))
            {
                continue;
            }
            Attribute attribute = null;
            if (customAttribute.ConstructorArguments.Count == 1)
            {
                attribute = (Attribute)Activator.CreateInstance(attributeType, customAttribute.ConstructorArguments[0].Value);
            }
            else if (customAttribute.ConstructorArguments.Count == 0)
            {
                attribute = (Attribute)Activator.CreateInstance(attributeType);
            }
            if (attribute == null)
            {
                continue;
            }
            foreach (CustomAttributeNamedArgument namedArgument in customAttribute.NamedArguments)
            {
                PropertyInfo property = attributeType.GetProperty(namedArgument.MemberInfo.Name, BindingFlags.Instance | BindingFlags.Public);
                object obj = namedArgument.TypedValue.Value;
                if (property.PropertyType.IsEnum)
                {
                    string value = obj.ToString();
                    obj = Enum.Parse(property.PropertyType, value);
                }
                property.SetValue(attribute, obj, null);
            }
            return attribute;
        }
        return null;
    }
References System.Diagnostics.Tracing.EventSource.AttributeTypeNamesMatch(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Activator.CreateInstance(), System.Reflection.CustomAttributeData.GetCustomAttributes(), System.Reflection.MemberInfo.Module, System.obj, System.Enum.Parse(), and System.value.
Referenced by System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors(), System.Diagnostics.Tracing.EventSource.GetGuid(), and System.Diagnostics.Tracing.EventSource.GetName().