Terraria: System.Diagnostics.Tracing.EventSource.DoCommand
DoCommand()
void System.Diagnostics.Tracing.EventSource.DoCommand (EventCommandEventArgs commandArgs) inline package inherited
Definition at line 1836 of file EventSource.cs.
    {
        if (!IsSupported || m_etwProvider == null || m_eventPipeProvider == null)
        {
            return;
        }
        m_outOfBandMessageCount = 0;
        try
        {
            EnsureDescriptorsInitialized();
            commandArgs.dispatcher = GetDispatcher(commandArgs.listener);
            if (commandArgs.dispatcher == null && commandArgs.listener != null)
            {
                throw new ArgumentException(SR.EventSource_ListenerNotFound);
            }
            if (commandArgs.Arguments == null)
            {
                IDictionary<string, string> dictionary2 = (commandArgs.Arguments = new Dictionary<string, string>());
            }
            if (commandArgs.Command == EventCommand.Update)
            {
                for (int i = 0; i < m_eventData.Length; i++)
                {
                    EnableEventForDispatcher(commandArgs.dispatcher, commandArgs.eventProviderType, i, IsEnabledByDefault(i, commandArgs.enable, commandArgs.level, commandArgs.matchAnyKeyword));
                }
                if (commandArgs.enable)
                {
                    if (!m_eventSourceEnabled)
                    {
                        m_level = commandArgs.level;
                        m_matchAnyKeyword = commandArgs.matchAnyKeyword;
                    }
                    else
                    {
                        if (commandArgs.level > m_level)
{
                            m_level = commandArgs.level;
                        }
                        if (commandArgs.matchAnyKeyword == EventKeywords.None)
{
                            m_matchAnyKeyword = EventKeywords.None;
                        }
                        else if (m_matchAnyKeyword != EventKeywords.None)
{
                            m_matchAnyKeyword |= commandArgs.matchAnyKeyword;
                        }
                    }
                }
                bool flag = commandArgs.perEventSourceSessionId >= 0;
                if (commandArgs.perEventSourceSessionId == 0 && !commandArgs.enable)
                {
                    flag = false;
                }
                if (commandArgs.listener == null)
                {
                    if (!flag)
                    {
                        commandArgs.perEventSourceSessionId = -commandArgs.perEventSourceSessionId;
                    }
                    commandArgs.perEventSourceSessionId--;
                }
                commandArgs.Command = (flag ? EventCommand.Enable : EventCommand.Disable);
                if (flag && commandArgs.dispatcher == null && !SelfDescribingEvents)
                {
                    SendManifest(m_rawManifest);
                }
                if (commandArgs.enable)
                {
                    m_eventSourceEnabled = true;
                }
                OnEventCommand(commandArgs);
                m_eventCommandExecuted?.Invoke(this, commandArgs);
                if (commandArgs.enable)
                {
                    return;
                }
                for (int j = 0; j < m_eventData.Length; j++)
                {
                    bool enabledForAnyListener = false;
                    for (EventDispatcher eventDispatcher = m_Dispatchers; eventDispatcher != null; eventDispatcher = eventDispatcher.m_Next)
                    {
                        if (eventDispatcher.m_EventEnabled[j])
{
                            enabledForAnyListener = true;
                            break;
                        }
                    }
                    m_eventData[j].EnabledForAnyListener = enabledForAnyListener;
                }
                if (!AnyEventEnabled())
                {
                    m_level = EventLevel.LogAlways;
                    m_matchAnyKeyword = EventKeywords.None;
                    m_eventSourceEnabled = false;
                }
            }
            else
            {
                if (commandArgs.Command == EventCommand.SendManifest && m_rawManifest != null)
                {
                    SendManifest(m_rawManifest);
                }
                OnEventCommand(commandArgs);
                m_eventCommandExecuted?.Invoke(this, commandArgs);
            }
        }
        catch (Exception ex)
        {
            ReportOutOfBandMessage("ERROR: Exception in Command Processing for EventSource " + Name + ": " + ex.Message);
        }
    }
References System.Diagnostics.Tracing.EventSource.AnyEventEnabled(), System.Diagnostics.Tracing.EventSource.EnableEventForDispatcher(), System.Diagnostics.Tracing.EventSource.EnsureDescriptorsInitialized(), System.SR.EventSource_ListenerNotFound, System.Diagnostics.Tracing.EventSource.GetDispatcher(), System.Diagnostics.Tracing.EventSource.IsEnabledByDefault(), System.Diagnostics.Tracing.EventSource.IsSupported, System.Diagnostics.Tracing.EventSource.m_Dispatchers, System.Diagnostics.Tracing.EventSource.m_etwProvider, System.Diagnostics.Tracing.EventSource.m_eventCommandExecuted, System.Diagnostics.Tracing.EventSource.m_eventData, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, System.Diagnostics.Tracing.EventSource.m_eventSourceEnabled, System.Diagnostics.Tracing.EventSource.m_level, System.Diagnostics.Tracing.EventSource.m_matchAnyKeyword, System.Diagnostics.Tracing.EventSource.m_outOfBandMessageCount, System.Diagnostics.Tracing.EventSource.m_rawManifest, System.Diagnostics.Tracing.EventSource.Name, System.Diagnostics.Tracing.EventSource.OnEventCommand(), System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage(), System.Diagnostics.Tracing.EventSource.SelfDescribingEvents, and System.Diagnostics.Tracing.SendManifest.
Referenced by System.Diagnostics.Tracing.EventSource.Initialize(), and System.Diagnostics.Tracing.EventSource.SendCommand().