Terraria: System.Diagnostics.Tracing.EventSource.WriteMultiMerge
WriteMultiMerge() [1/2]
unsafe void System.Diagnostics.Tracing.EventSource.WriteMultiMerge (string eventName, ref EventSourceOptions options, TraceLoggingEventTypes eventTypes, Guid * activityID, Guid * childActivityID, EventData * data) inline package inherited
Definition at line 2898 of file EventSource.cs.
    {
        if (!IsEnabled())
        {
            return;
        }
        fixed (EventSourceOptions* ptr2 = &options)
        {
            EventDescriptor descriptor;
            NameInfo nameInfo = UpdateDescriptor(eventName, eventTypes, ref options, out descriptor);
            if (nameInfo == null)
            {
                return;
            }
            IntPtr orCreateEventHandle = nameInfo.GetOrCreateEventHandle(m_eventPipeProvider, m_eventHandleTable, descriptor, eventTypes);
            int num = eventTypes.dataCount + eventTypes.typeInfos.Length * 2 + 3;
            EventData* ptr = stackalloc EventData[num];
            for (int i = 0; i < num; i++)
            {
                ptr[i] = default(EventData);
            }
            ReadOnlySpan<byte> providerMetadata = ProviderMetadata;
            fixed (byte* pointer = providerMetadata)
            {
                fixed (byte* pointer2 = nameInfo.nameMetadata)
                {
                    fixed (byte* pointer3 = eventTypes.typeMetadata)
                    {
                        ptr->SetMetadata(pointer, providerMetadata.Length, 2);
                        ptr[1].SetMetadata(pointer2, nameInfo.nameMetadata.Length, 1);
                        ptr[2].SetMetadata(pointer3, eventTypes.typeMetadata.Length, 1);
                        int num2 = 3;
                        for (int j = 0; j < eventTypes.typeInfos.Length; j++)
{
                            ptr[num2].m_Ptr = data[j].m_Ptr;
                            ptr[num2].m_Size = data[j].m_Size;
                            if (data[j].m_Size == 4 && eventTypes.typeInfos[j].DataType == typeof(bool))
{
                                ptr[num2].m_Size = 1;
                            }
                            num2++;
                        }
                        WriteEventRaw(eventName, ref descriptor, orCreateEventHandle, activityID, childActivityID, num2, (IntPtr)ptr);
                    }
                }
            }
        }
    }
References System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Diagnostics.Tracing.EventSource.m_eventHandleTable, System.Diagnostics.Tracing.EventSource.m_eventPipeProvider, System.Diagnostics.Tracing.EventSource.EventData.m_Ptr, System.Diagnostics.Tracing.EventSource.EventData.m_Size, System.options, System.pointer, System.Diagnostics.Tracing.EventSource.ProviderMetadata, System.Diagnostics.Tracing.EventSource.UpdateDescriptor(), and System.Diagnostics.Tracing.EventSource.WriteEventRaw().