Terraria: System.Diagnostics.Tracing.EventSource.WriteMultiMerge
WriteMultiMerge() [2/2]
unsafe void System.Diagnostics.Tracing.EventSource.WriteMultiMerge (string eventName, ref EventSourceOptions options, TraceLoggingEventTypes eventTypes, Guid * activityID, Guid * childActivityID, params object[] values) inline private inherited
Definition at line 2829 of file EventSource.cs.
    {
        if (IsEnabled())
        {
            byte level = (((options.valuesSet & 4u) != 0) ? options.level : eventTypes.level);
            EventKeywords keywords = ((((uint)options.valuesSet & (true ? 1u : 0u)) != 0) ? options.keywords : eventTypes.keywords);
            if (IsEnabled((EventLevel)level, keywords))
            {
                WriteMultiMergeInner(eventName, ref options, eventTypes, activityID, childActivityID, values);
            }
        }
    }
References System.Diagnostics.Tracing.EventSource.IsEnabled(), System.options, System.values, and System.Diagnostics.Tracing.EventSource.WriteMultiMergeInner().
Referenced by System.Diagnostics.Tracing.EventSource.WriteEventVarargs(), and System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore().