Terraria: System.Diagnostics.Tracing.EventSource.ToString
ToString()
override string System.Diagnostics.Tracing.EventSource.ToString () inline inherited
Definition at line 437 of file EventSource.cs.
    {
        if (!IsSupported)
        {
            return base.ToString();
        }
        return SR.Format(SR.EventSource_ToString, Name, Guid);
    }
References System.SR.EventSource_ToString, System.SR.Format(), System.Diagnostics.Tracing.EventSource.IsSupported, and System.Diagnostics.Tracing.EventSource.Name.
Referenced by System.Net.NetEventSource.AttemptingRestartUsingCert(), System.Net.NetEventSource.AuthenticationError(), System.Net.NetEventSource.AuthenticationInfo(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.RemoteCertificate(), System.Net.NetEventSource.SelectedCert(), and System.Net.NetEventSource.UriBaseAddress().