Terraria: System.Diagnostics.Tracing.EventSource.DecodeObjects
DecodeObjects()
static unsafe void System.Diagnostics.Tracing.EventSource.DecodeObjects (object[] decodedObjects, Type[] parameterTypes, EventData * data) inline static private inherited
Definition at line 1225 of file EventSource.cs.
    {
        object obj;
        for (int i = 0; i < decodedObjects.Length; decodedObjects[i] = obj, i++, data++)
        {
            IntPtr dataPointer = data->DataPointer;
            Type type = parameterTypes[i];
            if (!(type == typeof(string)))
            {
                if (type == typeof(int))
                {
                    obj = *(int*)(void*)dataPointer;
                    continue;
                }
                TypeCode typeCode = Type.GetTypeCode(type);
                int size = data->Size;
                if (size == 4)
                {
                    if ((uint)(typeCode - 5) <= 4u)
                    {
                        obj = *(int*)(void*)dataPointer;
                        continue;
                    }
                    if (typeCode == TypeCode.UInt32)
                    {
                        obj = *(uint*)(void*)dataPointer;
                        continue;
                    }
                    if (typeCode == TypeCode.Single)
                    {
                        obj = *(float*)(void*)dataPointer;
                        continue;
                    }
                    if (typeCode == TypeCode.Boolean)
                    {
                        obj = *(int*)(void*)dataPointer == 1;
                        continue;
                    }
                    if (type == typeof(byte[]))
                    {
                        data++;
                        goto IL_0256;
                    }
                    if (IntPtr.Size != 4)
                    {
                        goto IL_0244;
                    }
                }
                if (size <= 2)
                {
                    switch (typeCode)
                    {
                    case TypeCode.Byte:
                        obj = *(byte*)(void*)dataPointer;
                        continue;
                    case TypeCode.SByte:
                        obj = *(sbyte*)(void*)dataPointer;
                        continue;
                    case TypeCode.Int16:
                        obj = *(short*)(void*)dataPointer;
                        continue;
                    case TypeCode.UInt16:
                        obj = *(ushort*)(void*)dataPointer;
                        continue;
                    case TypeCode.Char:
                        obj = *(char*)(void*)dataPointer;
                        continue;
                    }
                }
                else if (size == 8)
                {
                    switch (typeCode)
                    {
                    case TypeCode.Int64:
                        obj = *(long*)(void*)dataPointer;
                        continue;
                    case TypeCode.UInt64:
                        obj = *(ulong*)(void*)dataPointer;
                        continue;
                    case TypeCode.Double:
                        obj = *(double*)(void*)dataPointer;
                        continue;
                    case TypeCode.DateTime:
                        obj = *(DateTime*)(void*)dataPointer;
                        continue;
                    }
                    _ = IntPtr.Size;
                    if (type == typeof(IntPtr))
                    {
                        obj = *(IntPtr*)(void*)dataPointer;
                        continue;
                    }
                }
                else
                {
                    if (typeCode == TypeCode.Decimal)
                    {
                        obj = *(decimal*)(void*)dataPointer;
                        continue;
                    }
                    if (type == typeof(Guid))
                    {
                        obj = *(Guid*)(void*)dataPointer;
                        continue;
                    }
                }
                goto IL_0244;
            }
            goto IL_028a;
            IL_0256:
            if (data->Size == 0)
            {
                obj = Array.Empty<byte>();
                continue;
            }
            byte[] array = new byte[data->Size];
            Marshal.Copy(data->DataPointer, array, 0, array.Length);
            obj = array;
            continue;
            IL_0244:
            if (!(type != typeof(byte*)))
            {
                goto IL_0256;
            }
            goto IL_028a;
            IL_028a:
            obj = ((dataPointer == IntPtr.Zero) ? null : new string((char*)(void*)dataPointer, 0, (data->Size >> 1) - 1));
        }
    }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Diagnostics.Tracing.EventSource.EventData.DataPointer, System.Type.GetTypeCode(), System.obj, System.Diagnostics.Tracing.EventSource.EventData.Size, System.IntPtr.Size, System.type, and System.IntPtr.Zero.
Referenced by System.Diagnostics.Tracing.EventSource.WriteToAllListeners().