Terraria: System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage
ReportOutOfBandMessage()
void System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage (string msg) inline package inherited
Definition at line 2704 of file EventSource.cs.
    {
        try
        {
            if (m_outOfBandMessageCount < 15)
            {
                m_outOfBandMessageCount++;
            }
            else
            {
                if (m_outOfBandMessageCount == 16)
                {
                    return;
                }
                m_outOfBandMessageCount = 16;
                msg = "Reached message limit.   End of EventSource error messages.";
            }
            Debugger.Log(0, null, "EventSource Error: " + msg + Environment.NewLine);
            WriteEventString(msg);
            WriteStringToAllListeners("EventSourceMessage", msg);
        }
        catch
        {
        }
    }
References System.Diagnostics.Debugger.Log(), System.Diagnostics.Tracing.EventSource.m_outOfBandMessageCount, System.Environment.NewLine, System.Diagnostics.Tracing.EventSource.WriteEventString(), and System.Diagnostics.Tracing.EventSource.WriteStringToAllListeners().
Referenced by System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(), System.Diagnostics.Tracing.EventSource.DoCommand(), System.Diagnostics.Tracing.EventSource.Initialize(), System.Diagnostics.Tracing.EventSource.LogEventArgsMismatches(), System.Diagnostics.Tracing.DiagnosticCounter.ReportOutOfBandMessage(), System.Diagnostics.Tracing.EventSource.ThrowEventSourceException(), and System.Diagnostics.Tracing.EventSource.WriteToAllListeners().