Terraria: System.Diagnostics.Tracing.EventSource.DebugCheckEvent
DebugCheckEvent()
static void System.Diagnostics.Tracing.EventSource.DebugCheckEvent (ref Dictionary< string, string > eventsByName, EventMetadata[] eventData, MethodInfo method, EventAttribute eventAttribute, ManifestBuilder manifest, EventManifestOptions options) inline static private inherited
Definition at line 2542 of file EventSource.cs.
    {
        int eventId = eventAttribute.EventId;
        string name = method.Name;
        int helperCallFirstArg = GetHelperCallFirstArg(method);
        if (helperCallFirstArg >= 0 && eventId != helperCallFirstArg)
        {
            manifest.ManifestError(SR.Format(SR.EventSource_MismatchIdToWriteEvent, name, eventId, helperCallFirstArg), runtimeCritical: true);
        }
        if (eventId < eventData.Length && eventData[eventId].Descriptor.EventId != 0)
        {
            manifest.ManifestError(SR.Format(SR.EventSource_EventIdReused, name, eventId, eventData[eventId].Name), runtimeCritical: true);
        }
        for (int i = 0; i < eventData.Length; i++)
        {
            if (eventData[i].Name != null && eventData[i].Descriptor.Task == (int)eventAttribute.Task && (EventOpcode)eventData[i].Descriptor.Opcode == eventAttribute.Opcode)
            {
                manifest.ManifestError(SR.Format(SR.EventSource_TaskOpcodePairReused, name, eventId, eventData[i].Name, i));
                if ((options & EventManifestOptions.Strict) == 0)
                {
                    break;
                }
            }
        }
        if (eventAttribute.Opcode != 0)
        {
            bool flag = false;
            if (eventAttribute.Task == EventTask.None)
            {
                flag = true;
            }
            else
            {
                EventTask eventTask = (EventTask)(65534 - eventId);
                if (eventAttribute.Opcode != EventOpcode.Start && eventAttribute.Opcode != EventOpcode.Stop && eventAttribute.Task == eventTask)
                {
                    flag = true;
                }
            }
            if (flag)
            {
                manifest.ManifestError(SR.Format(SR.EventSource_EventMustHaveTaskIfNonDefaultOpcode, name, eventId));
            }
        }
        if (eventsByName == null)
        {
            eventsByName = new Dictionary<string, string>();
        }
        if (eventsByName.ContainsKey(name))
        {
            manifest.ManifestError(SR.Format(SR.EventSource_EventNameReused, name), runtimeCritical: true);
        }
        eventsByName[name] = name;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.SR.EventSource_EventIdReused, System.SR.EventSource_EventMustHaveTaskIfNonDefaultOpcode, System.SR.EventSource_EventNameReused, System.SR.EventSource_MismatchIdToWriteEvent, System.SR.EventSource_TaskOpcodePairReused, System.SR.Format(), System.Diagnostics.Tracing.EventSource.GetHelperCallFirstArg(), System.Diagnostics.Tracing.EventSource.Name, and System.options.
Referenced by System.Diagnostics.Tracing.EventSource.CreateManifestAndDescriptors().